### ISSUE TITLE
Popup breaks remapped commands

### ISSUE THREAD

**Issue by noscript** [vim/vim#10004]
### Steps to reproduce

This is a continuation of https://github.com/vim/vim/issues/8176 but now user mapped commands are being canceled by mouse movement.

1. Run vim:
```sh
vim -g --clean -f +"help version8.txt" +"only" \
  +"call popup_create('hello', #{line: 1, close: 'click'})" \
  +"nnoremap cc <cmd>echo 'world'<CR>"  \
  +"set notimeout nottimeout showcmd"
```
2. Type `c` (one character).
3. Observe cursor is full height. Command in the right bottom corner printed as `c`.
4. Move the mouse.
5. Cursor changes to half height. Command in the right bottom corner disappears.
6. Type another `c`.
7. Vim tried to delete the line and errors `E21: Cannot make changes, 'modifiable' is off`.

### Expected behaviour

Prints "world".

### Version of Vim

8.2.4532

### Environment

OS: Debian 11
Terminal: GUI

**Comment by noscript** [comment]
Oh, sorry, I didn't realize the fix has been committed.

**Comment by brammool** [comment]
> > we can avoid it when the mouse move events are not actually used
> 
> I tried to use `#{line: 1, drag: v:false, dragall: v:false, close:
> 'button', mousemoved: [0, 0, 0]}` to forbid mouse interaction but it
> didn't help.

Before the patch it would use mouse move events whenever a popup is
visible.  Now it does matter whether mouse move is actually relevant.

-- 
Shit makes the flowers grow and that's beautiful

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
