### ISSUE TITLE
ch_readraw()  can only read stdout on windows

### ISSUE THREAD

**Issue by zoumi** [vim/vim#10016]
### Steps to reproduce

1,use ch_open to run an xx.exe file (the xx.exe should only output data to it's stderr)
2,call ch_readraw(a:channel)
3,Vim will get "E906: not an open channel"

### Expected behaviour

 ch_readraw() should return the data in stderr

### Version of Vim

gvim 8.2

### Environment

Windows 10 64 bit

**Comment by brammool** [comment]
Please call ch_logfile() and check the logging information.

**Comment by zoumi** [comment]
The code:

```vim
function Close_cb(channel)
    echomsg ch_info(a:channel)
    echomsg 'read_all:' . ch_readraw(a:channel)
endfunction


call ch_logfile("test_ch_readraw.log","w")
let job = job_start("git trig_error", {"close_cb": "Close_cb","out_mode":'raw'})
```

the log
```
==== start log session ====
  0.000038 : Starting job: git trig_error
  0.000292 on 0: Created channel
  0.002058 : SafeState: Start triggering
  0.004896 : looking for messages on channels
  0.004975 : SafeState: back to waiting, triggering SafeStateAgain
  0.150956 ERR on 0: channel_handle_events(): Read error from ch_part[1], closing
  0.151128 RECV on 0(err): 'git: 'trig_error' is not a git command. See 'git --help'.
'
  0.151138 : looking for messages on channels
  0.151184 on 0: Job ended
  0.151236 ERR on 0: channel_handle_events(): Read error from ch_part[2], closing
  0.151273 : looking for messages on channels
  0.151299 on 0: Closing channel because all readable fds are closed
  0.151326 on 0: Closing channel
  0.151556 on 0: Invoking callbacks and flushing buffers before closing
  0.151584 on 0: Invoking close callback Close_cb
  0.156538 : ERROR: Error detected while processing function Close_cb:
  0.157220 : ERROR: line    2:
  0.157800 : ERROR: E906: not an open channel
  0.159051 : ui_delay(1006)
  1.179901 on 0: Dropping message 'git: 'trig_error' is not a git command. See 'git --help'.
'
  1.179959 : SafeState: back to waiting, triggering SafeStateAgain
  1.180859 : looking for messages on channels
  1.180888 : SafeState: back to waiting, triggering SafeStateAgain
  2.262652 : SafeState: reset: key typed
  2.262731 : SafeState: Start triggering
  2.263132 : looking for messages on channels
  2.263142 : SafeState: back to waiting, triggering SafeStateAgain
  2.938626 : SafeState: reset: key typed
  2.938690 : SafeState: Start triggering
  2.944324 : looking for messages on channels
  2.944364 : SafeState: back to waiting, triggering SafeStateAgain
  3.239253 : SafeState: reset: key typed
  3.239344 : SafeState: Start triggering
  3.240173 : looking for messages on channels
  3.240196 : SafeState: back to waiting, triggering SafeStateAgain
  3.449301 : SafeState: reset: key typed
  3.449406 : SafeState: Start triggering
  3.450219 : looking for messages on channels
  3.450244 : SafeState: back to waiting, triggering SafeStateAgain
  3.689153 : SafeState: reset: key typed
  3.689226 : SafeState: Start triggering
  3.689840 : looking for messages on channels
  3.689858 : SafeState: back to waiting, triggering SafeStateAgain
  3.749266 : SafeState: reset: key typed
  3.749299 : SafeState: Start triggering
  3.749572 : looking for messages on channels
  3.749580 : SafeState: back to waiting, triggering SafeStateAgain
  4.078723 : SafeState: reset: key typed
  4.078803 : SafeState: Start triggering
  4.079632 : looking for messages on channels
  4.079657 : SafeState: back to waiting, triggering SafeStateAgain
  4.289105 : SafeState: reset: key typed
  4.303424 : looking for messages on channels
  5.369194 : SafeState: Start triggering
  5.375266 : looking for messages on channels
  5.375290 : SafeState: back to waiting, triggering SafeStateAgain
  7.048431 : SafeState: Start triggering
  7.048635 : looking for messages on channels
  7.048647 : SafeState: back to waiting, triggering SafeStateAgain
```

**Comment by brammool** [comment]
> The code:
> 
> ```vim
> function Close_cb(channel)
>     echomsg ch_info(a:channel)
>     echomsg 'read_all:' . ch_readraw(a:channel)
> endfunction
> 
> 
> call ch_logfile("test_ch_readraw.log","w")
> let job = job_start("git trig_error", {"close_cb": "Close_cb","out_mode":'raw'})
> ```
> 
> the log
> ```
> ==== start log session ====
>   0.000038 : Starting job: git trig_error
>   0.000292 on 0: Created channel
>   0.002058 : SafeState: Start triggering
>   0.004896 : looking for messages on channels
>   0.004975 : SafeState: back to waiting, triggering SafeStateAgain
>   0.150956 ERR on 0: channel_handle_events(): Read error from ch_part[1], closing
>   0.151128 RECV on 0(err): 'git: 'trig_error' is not a git command. See 'git --help'.
> '
>   0.151138 : looking for messages on channels
>   0.151184 on 0: Job ended
>   0.151236 ERR on 0: channel_handle_events(): Read error from ch_part[2], closing
>   0.151273 : looking for messages on channels
>   0.151299 on 0: Closing channel because all readable fds are closed
>   0.151326 on 0: Closing channel
>   0.151556 on 0: Invoking callbacks and flushing buffers before closing
>   0.151584 on 0: Invoking close callback Close_cb
>   0.156538 : ERROR: Error detected while processing function Close_cb:
>   0.157220 : ERROR: line    2:
>   0.157800 : ERROR: E906: not an open channel
>   0.159051 : ui_delay(1006)
>   1.179901 on 0: Dropping message 'git: 'trig_error' is not a git command. See 'git --help'.

The message is on "err" but you are trying to read "out".  Use this:

function Close_cb(channel)
    echomsg ch_info(a:channel)
    echomsg 'read_all:' . ch_readraw(a:channel, {'part': 'err'})
endfunction


-- 
WOMAN:   Well, 'ow did you become king then?
ARTHUR:  The Lady of the Lake, [angels sing] her arm clad in the purest
         shimmering samite, held aloft Excalibur from the bosom of the water
         signifying by Divine Providence that I, Arthur, was to carry
         Excalibur.  [singing stops] That is why I am your king!
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by zoumi** [comment]
'''vim
function Close_cb(channel)
    " echomsg ch_info(a:channel)
    if ch_status(a:channel, {'part': 'err'}) == 'buffered'
        let std_err = ch_readraw(a:channel, {"part": "err"})
        echoerr 'stderr:' . std_err
    endif

    if ch_status(a:channel, {'part': 'out'}) == 'buffered'
        let std_output = ch_readraw(a:channel,{"part": "out"})
        echomsg 'stdout:' . std_output
    endif
endfunction

" call ch_logfile("test_ch_readraw.log","w")
let job = job_start("git trig_error", {"close_cb": "Close_cb","out_mode":'raw'})
let job = job_start("git --help", {"close_cb": "Close_cb","out_mode":'raw'})
'''
output:
![Snipaste_2022-06-22_14-50-32](https://user-images.githubusercontent.com/5162901/174962807-9496de85-e5f6-414b-8db2-0ac5f510bc41.jpg)
@brammool 
ch_readraw(a:channel, {"part": "err"}) only read a line, but ch_readraw(a:channel,{"part": "out"}) read all, why?

**Comment by brammool** [comment]
Not sure.  If you check the status of stdout you can see it is "closed".  Perhaps the output was not read before the job finished.
Behavior of a finished process is tricky, what happens with stdout/stderr depends on details. It would require debugging to find out what happens. Using ch_logfile() and ch_log() should work best, to avoid timing changes when stepping through the code with a debugger.

**Comment by zoumi** [comment]
@brammool I got it. There is an option called 'err_mode'.
```
let job = job_start("git --trig_error", {"close_cb": "Close_cb","out_mode":'raw', 'err_mode':'raw'}
```
Thank you.
