### ISSUE TITLE
Vim9: segmentation fault

### ISSUE THREAD

**Issue by noscript** [vim/vim#10011]
### Steps to reproduce

1. Create `~/vim9_segfault`:
```vim
vim9script

var vname = "g:hello"

if exists(vname) | finish | endif | execute vname '= "world"'

echo g:hello

if exists(vname) | finish | endif | execute vname '= "world"'

echo g:hello
```
2. Run vim:
```sh
vim -g --clean -u ~/vim9_segfault
```
3. Vim crashes:
```
Vim: Caught deadly signal SEGV
Vim: Finished.
```

### Expected behaviour

Not crash.

### Version of Vim

8.2.4620

### Environment

OS: Debian 11
Terminal: GUI

**Comment by lacygoill** [comment]
Backtrace:

    #0  0x000055555589ae12 in skipwhite (q=0x0) at charset.c:1430
            p = 0x0
    #1  0x00005555555f7c79 in eval_next_line (evalarg=0x7fffffffb040) at eval.c:2227
            gap = 0x7fffffffb068
            line = 0x0
    #2  0x00005555555f7a1d in getline_peek_skip_comments (evalarg=0x7fffffffb040) at eval.c:2147
            next = 0x55555597feb0 ""
            p = 0x55555597feb0 ""
    #3  0x00005555555f7ae1 in eval_next_non_blank (arg=0x5555559eeb6a "", evalarg=0x7fffffffb040, getnext=0x7fffffffa908)
        at eval.c:2174
            next = 0x5555558acc00 <__libc_csu_init> "\363\017\036\372AWL\215=\003u\a"
            p = 0x5555559eeb6a ""
    #4  0x00005555555ff3a2 in handle_subscript
        (arg=0x7fffffffb108, name_start=0x0, rettv=0x7fffffffb120, evalarg=0x7fffffffb040, verbose=1) at eval.c:6113
            evaluate = 1
            ret = 1
            selfdict = 0x0
            check_white = 1
            getnext = 0
            p = 0x7fffffffb108 "j\353\236UUU"
    #5  0x00005555555fb369 in eval7 (arg=0x7fffffffb108, rettv=0x7fffffffb120, evalarg=0x7fffffffb040, want_string=0)
        at eval.c:3886
            evaluate = 1
            len = 5
            s = 0x5555559eeb59 "vname '= \"world\"'"
            name_start = 0x0
            start_leader = 0x5555559eeb5f "'= \"world\"'"
            end_leader = 0x5555559eeb5f "'= \"world\"'"
            ret = 1
            alias = 0x0
            recurse = 1
            vim9script = 1
    #6  0x00005555555fa5ee in eval7t (arg=0x7fffffffb108, rettv=0x7fffffffb120, evalarg=0x7fffffffb040, want_string=0)
        at eval.c:3429
            want_type = 0x0
            type_list = {ga_len = 0, ga_maxlen = 0, ga_itemsize = -21824, ga_growsize = 32767, ga_data = 0x7fffffffb040}
            res = 1
            evaluate = 1
    #7  0x00005555555fa046 in eval6 (arg=0x7fffffffb108, rettv=0x7fffffffb120, evalarg=0x7fffffffb040, want_string=0)
        at eval.c:3221
            use_float = 0
    #8  0x00005555555f9792 in eval5 (arg=0x7fffffffb108, rettv=0x7fffffffb120, evalarg=0x7fffffffb040) at eval.c:2984
    #9  0x00005555555f9251 in eval4 (arg=0x7fffffffb108, rettv=0x7fffffffb120, evalarg=0x7fffffffb040) at eval.c:2834
            p = 0x5555559eeb5f "'= \"world\"'"
            getnext = 0
            type = EXPR_UNKNOWN
            len = 2
            type_is = 0
    #10 0x00005555555f8d6d in eval3 (arg=0x7fffffffb108, rettv=0x7fffffffb120, evalarg=0x7fffffffb040) at eval.c:2695
            p = 0x5555559eeb5f "'= \"world\"'"
            getnext = 0
    #11 0x00005555555f88a2 in eval2 (arg=0x7fffffffb108, rettv=0x7fffffffb120, evalarg=0x7fffffffb040) at eval.c:2569
            p = 0x5555559eeb5f "'= \"world\"'"
            getnext = 0
    #12 0x00005555555f816a in eval1 (arg=0x7fffffffb108, rettv=0x7fffffffb120, evalarg=0x7fffffffb040) at eval.c:2415
            p = 0x5555559eeb5f "'= \"world\"'"
            getnext = 0
    #13 0x00005555555f33ca in eval1_emsg (arg=0x7fffffffb108, rettv=0x7fffffffb120, eap=0x7fffffffb250) at eval.c:206
            start = 0x5555559eeb5f "'= \"world\"'"
            ret = 1
            did_emsg_before = 0
            called_emsg_before = 0
            evalarg = 
              {eval_flags = 1, eval_break_count = 1, eval_getline = 0x55555576c08d <getsourceline>, eval_cookie = 0x7fffffffbcc0, eval_cctx = 0x0, eval_cstack = 0x7fffffffb560, eval_ga = {ga_len = 0, ga_maxlen = 0, ga_itemsize = 0, ga_growsize = 0, ga_data = 0x0}, eval_freega = {ga_len = 0, ga_maxlen = 0, ga_itemsize = 0, ga_growsize = 0, ga_data = 0x0}, eval_tofree = 0x0, eval_tofree_ga = {ga_len = 0, ga_maxlen = 0, ga_itemsize = 8, ga_growsize = 20, ga_data = 0x0}, eval_using_cmdline = 0, eval_tofree_lambda = 0x0}
    #14 0x00005555556001df in ex_execute (eap=0x7fffffffb250) at eval.c:6518
            arg = 0x5555559eeb6a ""
            rettv = 
                {v_type = VAR_STRING, v_lock = 0 '\000', vval = {v_number = 93824997060288, v_float = 4.6355707768644249e-310, v_string = 0x5555559eeec0 "= \"world\"", v_list = 0x5555559eeec0, v_dict = 0x5555559eeec0, v_partial = 0x5555559eeec0, v_job = 0x5555559eeec0, v_channel = 0x5555559eeec0, v_blob = 0x5555559eeec0, v_instr = 0x5555559eeec0}}
            ret = 1
            p = 0x5555559eeec0 "= \"world\""
            ga = {ga_len = 7, ga_maxlen = 80, ga_itemsize = 1, ga_growsize = 80, ga_data = 0x5555559ebb50}
            len = 7
            start_lnum = 9
    #15 0x000055555562e2d8 in do_one_cmd (cmdlinep=0x7fffffffb480, flags=7, cstack=0x7fffffffb560, fgetline=
        0x55555576c08d <getsourceline>, cookie=0x7fffffffbcc0) at ex_docmd.c:2567
            p = 0x5555559eeb58 " vname '= \"world\"'"
            lnum = 7885636024599258446
            n = 5630959013080084325
            errormsg = 0x0
            after_modifier = 0x5555559eeb51 "execute vname '= \"world\"'"
            ea = 
              {arg = 0x5555559eeb59 "vname '= \"world\"'", nextcmd = 0x0, cmd = 0x5555559eeb51 "execute vname '= \"world\"'", cmdlinep = 0x7fffffffb480, cmdline_tofree = 0x0, cmdidx = CMD_execute, argt = 151783428, skip = 0, forceit = 0, addr_count = 0, line1 = 1, line2 = 1, addr_type = ADDR_NONE, flags = 0, do_ecmd_cmd = 0x0, do_ecmd_lnum = 0, append = 0, usefilter = 0, amount = 0, regname = 0, force_bin = 0, read_edit = 0, force_ff = 0, force_enc = 0, bad_char = 0, useridx = 0, errmsg = 0x0, getline = 0x55555576c08d <getsourceline>, cookie = 0x7fffffffbcc0, cstack = 0x7fffffffb560}
            save_cmdmod = 
              {cmod_flags = 0, cmod_split = 0, cmod_tab = 0, cmod_filter_regmatch = {regprog = 0x0, startp = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, endp = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, rm_ic = 0}, cmod_filter_force = 0, cmod_verbose = 0, cmod_save_ei = 0x0, cmod_did_sandbox = 0, cmod_verbose_save = 0, cmod_save_msg_silent = 0, cmod_save_msg_scroll = 0, cmod_did_esilent = 0}
            save_reg_executing = 0
            ni = 0
            cmd = 0x5555559eeb51 "execute vname '= \"world\"'"
            starts_with_colon = 0
            may_have_range = 0
            vim9script = 1
            did_set_expr_line = 0
            sourcing = 1
    #16 0x000055555562b4ba in do_cmdline (cmdline=0x55555597ffc0 "vim9script", fgetline=
        0x55555576c08d <getsourceline>, cookie=0x7fffffffbcc0, flags=7) at ex_docmd.c:993
            next_cmdline = 0x5555559eeb50 " execute vname '= \"world\"'"
            cmdline_copy = 0x5555559eeb50 " execute vname '= \"world\"'"
            used_getline = 1
            recursive = 2
            msg_didout_before_start = 0
            count = 12
            did_inc = 0
            retval = 1
            cstack = 
              {cs_flags = {1, 0 <repeats 49 times>}, cs_pending = '\000' <repeats 49 times>, cs_pend = {csp_rv = {0x0 <repeats 50 times>}, csp_ex = {0x0 <repeats 50 times>}}, cs_forinfo = {0x0 <repeats 50 times>}, cs_line = {0 <repeats 50 times>}, cs_block_id = {2, 0 <repeats 49 times>}, cs_script_var_len = {1, 0 <repeats 49 times>}, cs_idx = -1, cs_looplevel = 0, cs_trylevel = 0, cs_emsg_silent_list = 0x0, cs_lflags = 0 '\000'}
            lines_ga = {ga_len = 0, ga_maxlen = 0, ga_itemsize = 16, ga_growsize = 10, ga_data = 0x0}
            current_line = 0
            current_line_before = 0
            fname = 0x5555559ee620 "/tmp/t.vim"
            breakpoint = 0x7fffffffbd00
            dbg_tick = 0x7fffffffbd10
            debug_saved = 
              {trylevel = 0, force_abort = 0, caught_stack = 0x0, vv_exception = 0x0, vv_throwpoint = 0x0, did_emsg = 0, got_int = 0, did_throw = 0, need_rethrow = 0, check_cstack = 0, current_exception = 0x0}
            initial_trylevel = 0
            saved_msg_list = 0x7fffffffc0d8
            private_msg_list = 0x0
            cmd_getline = 0x55555576c08d <getsourceline>
            cmd_cookie = 0x7fffffffbcc0
            cmd_loop_cookie = {lines_gap = 0x0, current_line = 0, repeating = 0, getline = 0x0, cookie = 0x0}
            real_cookie = 0x7fffffffbcc0
            getline_is_func = 0
            call_depth = 2
    #17 0x000055555576b4db in do_source_ext
        (fname=0x55555599a553 "/tmp/t.vim", check_other=0, is_vimrc=0, ret_sid=0x0, eap=0x0, clearvars=0)
        at scriptfile.c:1632
            cookie = 
                {fp = 0x5555559edcf0, nextline = 0x55555597feb0 "", sourcing_lnum = 9, finished = 1, source_from_buf = 0, buf_lnum = 0, buflines = {ga_len = 0, ga_maxlen = 0, ga_itemsize = 0, ga_growsize = 0, ga_data = 0x0}, breakpoint = 0, fname = 0x5555559ee620 "/tmp/t.vim", dbg_tick = 0, level = 1, conv = {vc_type = 0, vc_factor = 0, vc_fd = 0x0, vc_fail = 0}}
            p = 0x5555559f14c0 "vim9script\n\nvar vname = \"g:hello\"\n\nif exists(vname) | finish | endif | execute vname '= \"world\"'\n\necho g:hello\n\nif exists(vname) | finish | endif | execute vname '= \"world\"'\n\necho g:hello\n"
            fname_exp = 0x5555559ee640 "/tmp/t.vim"
            firstline = 0x55555597ffc0 "vim9script"
            retval = 0
            save_current_sctx = {sc_sid = -3, sc_seq = 0, sc_lnum = 0, sc_version = 0}
            funccalp_entry = {top_funccal = 0x0, next = 0x0}
            save_debug_break_level = -1
            sid = -1
            si = 0x5555559ee710
            save_estack_compiling = 0
            tv_rel = {tv_sec = 140733461823488, tv_usec = 140737325612880}
            tv_start = {tv_sec = 18, tv_usec = 0}
            wait_start = {tv_sec = 2118, tv_usec = 140737336577696}
            save_sticky_cmdmod_flags = 0
            trigger_source_post = 0
            estack_len_before = 3
    #18 0x000055555576bb7d in do_source (fname=0x55555599a553 "/tmp/t.vim", check_other=0, is_vimrc=0, ret_sid=0x0)
        at scriptfile.c:1758
    #19 0x000055555576a5d9 in cmd_source (fname=0x55555599a553 "/tmp/t.vim", eap=0x7fffffffbea0) at scriptfile.c:1132
            clearvars = 0
    #20 0x000055555576a6bb in ex_source (eap=0x7fffffffbea0) at scriptfile.c:1158
    #21 0x000055555562e2d8 in do_one_cmd (cmdlinep=0x7fffffffc0d0, flags=11, cstack=0x7fffffffc1b0, fgetline=
        0x0, cookie=0x0) at ex_docmd.c:2567
            p = 0x55555599a552 " /tmp/t.vim"
            lnum = 140737336554032
            n = 140737354009482
            errormsg = 0x0
            after_modifier = 0x55555599a550 "so /tmp/t.vim"
            ea = 
              {arg = 0x55555599a553 "/tmp/t.vim", nextcmd = 0x0, cmd = 0x55555599a550 "so /tmp/t.vim", cmdlinep = 0x7fffffffc0d0, cmdline_tofree = 0x0, cmdidx = CMD_source, argt = 17563967, skip = 0, forceit = 0, addr_count = 0, line1 = 1, line2 = 1, addr_type = ADDR_LINES, flags = 0, do_ecmd_cmd = 0x0, do_ecmd_lnum = 0, append = 0, usefilter = 0, amount = 0, regname = 0, force_bin = 0, read_edit = 0, force_ff = 0, force_enc = 0, bad_char = 0, useridx = 0, errmsg = 0x0, getline = 0x0, cookie = 0x0, cstack = 0x7fffffffc1b0}
            save_cmdmod = 
              {cmod_flags = 0, cmod_split = 0, cmod_tab = 0, cmod_filter_regmatch = {regprog = 0x0, startp = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, endp = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, rm_ic = 0}, cmod_filter_force = 0, cmod_verbose = 0, cmod_save_ei = 0x0, cmod_did_sandbox = 0, cmod_verbose_save = 0, cmod_save_msg_silent = 0, cmod_save_msg_scroll = 0, cmod_did_esilent = 0}
            save_reg_executing = 0
            ni = 0
            cmd = 0x55555599a550 "so /tmp/t.vim"
            starts_with_colon = 0
            may_have_range = 1
            vim9script = 0
            did_set_expr_line = 0
            sourcing = 1
    #22 0x000055555562b4ba in do_cmdline (cmdline=0x555555992c20 "so /tmp/t.vim", fgetline=0x0, cookie=0x0, flags=11)
        at ex_docmd.c:993
            next_cmdline = 0x55555599a550 "so /tmp/t.vim"
            cmdline_copy = 0x55555599a550 "so /tmp/t.vim"
            used_getline = 0
            recursive = 2
            msg_didout_before_start = 0
            count = 1
            did_inc = 0
            retval = 1
            cstack = 
              {cs_flags = {0 <repeats 50 times>}, cs_pending = '\000' <repeats 49 times>, cs_pend = {csp_rv = {0x0 <repeats 50 times>}, csp_ex = {0x0 <repeats 50 times>}}, cs_forinfo = {0x0 <repeats 50 times>}, cs_line = {0 <repeats 50 times>}, cs_block_id = {0 <repeats 50 times>}, cs_script_var_len = {0 <repeats 50 times>}, cs_idx = -1, cs_looplevel = 0, cs_trylevel = 0, cs_emsg_silent_list = 0x0, cs_lflags = 0 '\000'}
            lines_ga = {ga_len = 0, ga_maxlen = 0, ga_itemsize = 16, ga_growsize = 10, ga_data = 0x0}
            current_line = 0
            current_line_before = 0
            fname = 0x0
            breakpoint = 0x0
            dbg_tick = 0x0
            debug_saved = 
              {trylevel = 0, force_abort = 0, caught_stack = 0x0, vv_exception = 0x0, vv_throwpoint = 0x0, did_emsg = 0, got_int = 0, did_throw = 0, need_rethrow = 0, check_cstack = 0, current_exception = 0x0}
            initial_trylevel = 0
            saved_msg_list = 0x0
            private_msg_list = 0x0
            cmd_getline = 0x0
            cmd_cookie = 0x0
            cmd_loop_cookie = 
              {lines_gap = 0x7fffffffc4f0, current_line = 529823011, repeating = 0, getline = 0x7e51d4, cookie = 0x7fffffffc1b4}
            real_cookie = 0x0
            getline_is_func = 0
            call_depth = 2
    #23 0x000055555562a945 in do_cmdline_cmd (cmd=0x555555992c20 "so /tmp/t.vim") at ex_docmd.c:587
    #24 0x00005555558a2fc8 in exe_commands (parmp=0x5555559728c0 <params>) at main.c:3084
            i = 0
            estack_len_before = 2
    #25 0x000055555589f869 in vim_main2 () at main.c:772
    #26 0x000055555589f128 in main (argc=5, argv=0x7fffffffc9b8) at main.c:424
            i = 5

Valgrind log:

    ==299804== Invalid read of size 1
    ==299804==    at 0x45027B: skipwhite (charset.c:1430)
    ==299804==    by 0x1AC1F2: eval_next_line (eval.c:2227)
    ==299804==    by 0x1ABF96: getline_peek_skip_comments (eval.c:2147)
    ==299804==    by 0x1AC05A: eval_next_non_blank (eval.c:2174)
    ==299804==    by 0x1B391B: handle_subscript (eval.c:6113)
    ==299804==    by 0x1AF8E2: eval7 (eval.c:3886)
    ==299804==    by 0x1AEB67: eval7t (eval.c:3429)
    ==299804==    by 0x1AE5BF: eval6 (eval.c:3221)
    ==299804==    by 0x1ADD0B: eval5 (eval.c:2984)
    ==299804==    by 0x1AD7CA: eval4 (eval.c:2834)
    ==299804==    by 0x1AD2E6: eval3 (eval.c:2695)
    ==299804==    by 0x1ACE1B: eval2 (eval.c:2569)
    ==299804==    by 0x1AC6E3: eval1 (eval.c:2415)
    ==299804==    by 0x1A7943: eval1_emsg (eval.c:206)
    ==299804==    by 0x1B4758: ex_execute (eval.c:6518)
    ==299804==    by 0x1E2998: do_one_cmd (ex_docmd.c:2567)
    ==299804==    by 0x1DFB7A: do_cmdline (ex_docmd.c:993)
    ==299804==    by 0x320265: do_source_ext (scriptfile.c:1632)
    ==299804==    by 0x320907: do_source (scriptfile.c:1758)
    ==299804==    by 0x31F363: cmd_source (scriptfile.c:1132)
    ==299804==    by 0x31F445: ex_source (scriptfile.c:1158)
    ==299804==    by 0x1E2998: do_one_cmd (ex_docmd.c:2567)
    ==299804==    by 0x1DFB7A: do_cmdline (ex_docmd.c:993)
    ==299804==    by 0x1DF005: do_cmdline_cmd (ex_docmd.c:587)
    ==299804==    by 0x458430: exe_commands (main.c:3084)
    ==299804==    by 0x454CD1: vim_main2 (main.c:772)
    ==299804==    by 0x454590: main (main.c:424)
    ==299804==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
    ==299804== 
    ==299804== 
    ==299804== Process terminating with default action of signal 11 (SIGSEGV)
    ==299804==    at 0x573340B: kill (syscall-template.S:78)
    ==299804==    by 0x2B62E7: may_core_dump (os_unix.c:3529)
    ==299804==    by 0x2B6282: mch_exit (os_unix.c:3495)
    ==299804==    by 0x455FBD: getout (main.c:1714)
    ==299804==    by 0x276ABE: preserve_exit (misc1.c:2194)
    ==299804==    by 0x2B387C: deathtrap (os_unix.c:1175)
    ==299804==    by 0x57330BF: ??? (in /usr/lib/x86_64-linux-gnu/libc-2.31.so)
    ==299804==    by 0x45027A: skipwhite (charset.c:1430)
    ==299804==    by 0x1AC1F2: eval_next_line (eval.c:2227)
    ==299804==    by 0x1ABF96: getline_peek_skip_comments (eval.c:2147)
    ==299804==    by 0x1AC05A: eval_next_non_blank (eval.c:2174)
    ==299804==    by 0x1B391B: handle_subscript (eval.c:6113)
    ==299804==    by 0x1AF8E2: eval7 (eval.c:3886)
    ==299804==    by 0x1AEB67: eval7t (eval.c:3429)
    ==299804==    by 0x1AE5BF: eval6 (eval.c:3221)
    ==299804==    by 0x1ADD0B: eval5 (eval.c:2984)
    ==299804==    by 0x1AD7CA: eval4 (eval.c:2834)
    ==299804==    by 0x1AD2E6: eval3 (eval.c:2695)
    ==299804==    by 0x1ACE1B: eval2 (eval.c:2569)
    ==299804==    by 0x1AC6E3: eval1 (eval.c:2415)
    ==299804==    by 0x1A7943: eval1_emsg (eval.c:206)
    ==299804==    by 0x1B4758: ex_execute (eval.c:6518)
    ==299804==    by 0x1E2998: do_one_cmd (ex_docmd.c:2567)
    ==299804==    by 0x1DFB7A: do_cmdline (ex_docmd.c:993)
    ==299804==    by 0x320265: do_source_ext (scriptfile.c:1632)
    ==299804==    by 0x320907: do_source (scriptfile.c:1758)
    ==299804==    by 0x31F363: cmd_source (scriptfile.c:1132)
    ==299804==    by 0x31F445: ex_source (scriptfile.c:1158)
    ==299804==    by 0x1E2998: do_one_cmd (ex_docmd.c:2567)
    ==299804==    by 0x1DFB7A: do_cmdline (ex_docmd.c:993)
    ==299804==    by 0x1DF005: do_cmdline_cmd (ex_docmd.c:587)
    ==299804==    by 0x458430: exe_commands (main.c:3084)
    ==299804==    by 0x454CD1: vim_main2 (main.c:772)
    ==299804==    by 0x454590: main (main.c:424)
    ==299804== 
    ==299804== HEAP SUMMARY:
    ==299804==     in use at exit: 744,684 bytes in 3,443 blocks
    ==299804==   total heap usage: 5,279 allocs, 1,836 frees, 1,425,691 bytes allocated
