### ISSUE TITLE
'cursorbind' horizontal scrolling behavior is inconsistent depending whether 'cursorline' is set in inactive window

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#10014]
### Steps to reproduce

1. Run `vim --clean`
2. `:set sidescroll=1` (`sidescroll=1` makes the difference more obvious)
3. `:set nowrap`
4. Insert a long line of text
5. `:20vsplit`
6. `:windo set cursorbind`
7. Move cursor horizontally in the wider window. The narrower window is not horizontally scrolled.
8. `:windo set cursorline`
9. Move cursor horizontally in the wider window. The narrower window is horizontally scrolled.

### Expected behaviour

'cursorbind' horizontal scrolling behavior should be consistent whether 'cursorline' is set or not. I'm not sure which behavior is better.

### Version of Vim

8.2.4621

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

**Comment by brammool** [comment]
I'm not sure, but I would think that the other window should also scroll when 'cursorline' is not set.
What do others think?

**Comment by chrisbra** [comment]
yes, agree

**Comment by chrisbra** [comment]
Actually, the cursor does always scroll. It's just that the scrollbinded window isn't redrawn, so you do not notice. You only notice once you move back to the previous window. The following patch fixes this annoying behaviour (at the cost of redrawing a bit more):

```diff
diff --git a/src/move.c b/src/move.c
index a6d2fde74..31dc95b2f 100644
--- a/src/move.c
+++ b/src/move.c
@@ -2918,10 +2918,7 @@ do_check_cursorbind(void)
            restart_edit_save = restart_edit;
            restart_edit = TRUE;
            check_cursor();
-# ifdef FEAT_SYN_HL
-           if (curwin->w_p_cul || curwin->w_p_cuc)
-               validate_cursor();
-# endif
+           validate_cursor();
            restart_edit = restart_edit_save;
            // Correct cursor for multi-byte character.
            if (has_mbyte)
```
