### ISSUE TITLE
flattennew semantics seem wrong

### ISSUE THREAD

**Issue by errael** [vim/vim#10012]
### Steps to reproduce

```
flattennew
lev2: [['a', 'b'], ['c', 'd']] lev1 [['a', 'b'], ['c', 'd']]
equals
lev2: ['a', 'b'] lev1 ['a', 'b']
not same

FlattenNewDepthOne
lev2: [['a', 'b'], ['c', 'd']] lev1 [['a', 'b'], ['c', 'd']]
equals
lev2: ['a', 'b'] lev1 ['a', 'b']
same

deepcopy()->FlattenNewDepthOne
lev2: [['a', 'b'], ['c', 'd']] lev1 [['a', 'b'], ['c', 'd']]
equals
lev2: ['a', 'b'] lev1 ['a', 'b']
not same
```

The above output is produced by the following script. The thing to notice is that in the first test, 'flattennew', the items that are brought up to the top level of the flatten'd list are different ("not same") as in the original list.

In the 'FlattenNewDepthOne' test, they are the same; this seems like the prefered semantics.

The third test, using 'deepcopy()->FlattenNewDepthOne' shows that it is simple to get the current semantics ("not same"). Whereas the converse is not true. I see no simple way to get the "FlattenNewDepthOne" semantics.

```
vim9script

var level_2 = [ [ ['a', 'b'], ['c', 'd' ] ] ]

def Test(lev2: list<any>, lev1: list<any>)
    echo 'lev2:' lev2[0] 'lev1' lev1
    if lev2[0] == lev1 | echo 'equals' | else | echo 'not equals' | endif

    echo 'lev2:' lev2[0][0] 'lev1' lev1[0]
    if lev2[0][0] is lev1[0] | echo 'same' | else | echo 'not same' | endif

    echo ' '
enddef

def FlattenNewDepthOne(list: list<any>): list<any>
    var result: list<any>
    for l in list
        result->extend(l)
    endfor
    return result
enddef

echo 'flattennew'
Test(level_2, level_2->flattennew(1))

echo 'FlattenNewDepthOne'
Test(level_2, level_2->FlattenNewDepthOne())

echo 'deepcopy()->FlattenNewDepthOne'
Test(level_2, level_2->deepcopy()->FlattenNewDepthOne())
```

### Expected behaviour

As mentioned, there is no builtin way to get a flattened list that preserves the items below "depth"; they currently become different items. In the situation where I ran into this, I wanted to adjust the items below depth, not new items. If I wanted new items I could have done deepcopy()->flattennew().

Note the flattennew doc says "copy" not "deep copy", I'm not sure what the intent was.

If the current behavior isn't considered a bug, or otherwise can't be changed, one way to get the desired functionality would be to have an optional 3rd argument, for example
```
flattennew({list}, {depth}, doDeepCopy: bool = true)
```

### Version of Vim

8.2.4607

### Environment

ubuntu, gvim-gtk3

**Comment by errael** [comment]
Sleeping on it, I think I came up with a workaround (and wrote my first original vimscript function in the process). Using the `Test` function from the original post, the following seems to do what I'm looking for. I'll have to try a few heavy duty tests, but I suspect it works as hoped for, preserving items that make their way to the top level of the resulting list.

In fact, _maybe flatten could be made to work this way and become usable in vim9script_.

```
def FlattenNewHybrid(l: list<any>, maxdepth: number = 999999): list<any>
    function FlattenNewInternal(il, id)
        return flatten(a:il,a:id)
    endfu
    return FlattenNewInternal(copy(l), maxdepth)
enddef

echo 'FlattenNewHybrid'
Test(level_2, level_2->FlattenNewHybrid(1))

echo 'FlattenNewHybrid - DEEP'
Test(level_2, level_2->FlattenNewHybrid())
```
produces the output
```
FlattenNewHybrid
lev2: [['a', 'b'], ['c', 'd']] lev1 [['a', 'b'], ['c', 'd']]
equals
lev2: ['a', 'b'] lev1 ['a', 'b']
same

FlattenNewHybrid - DEEP
lev2: [['a', 'b'], ['c', 'd']] lev1 ['a', 'b', 'c', 'd']
not equals
lev2: ['a', 'b'] lev1 a
not same

```

**Comment by errael** [comment]
Ignore the `DEEP` test, it's pretty meaningless.

**Comment by errael** [comment]
```
CheckSame('original', data)
CheckSame('deepcopy', data->deepcopy())
CheckSame('flattennew(2)', data->flattennew(2))
CheckSame('FlattenHybrid(2)', data->FlattenHybrid(2))
CheckSame('Flatten(2)', data->Flatten(2))
CheckSame('flatten(2)', data->flatten(2))
```
Produces the following output, tested with flatten fix 8.2.4628. As expected `deepcopy` and `flattennew` do not find "is same". FlattenHybrid (in previous message; uses `flatten` gets "is same". Flatten(2), a pure vim9 implementation "is same"

Still can't use flatten directly from vim9script. Since FlattenHybrid is mostly builtins should have reasonable performance characteristics.

```
=== original ===
looking to fetch: [5, 1, 1, 0] from [0, [1, 2], 1, [[[1, 2]]], [1, 2], [1, [2, [['x', 'y'], 3, [1, 2], 4]]]]
FOUND: ['x', 'y']
is same
=== deepcopy ===
looking to fetch: [5, 1, 1, 0] from [0, [1, 2], 1, [[[1, 2]]], [1, 2], [1, [2, [['x', 'y'], 3, [1, 2], 4]]]]
FOUND: ['x', 'y']
NOT is same
=== flattennew(2) ===
looking to fetch: [9, 0] from [0, 1, 2, 1, [1, 2], 1, 2, 1, 2, [['x', 'y'], 3, [1, 2], 4]]
FOUND: ['x', 'y']
NOT is same
=== FlattenHybrid(2) ===
looking to fetch: [9, 0] from [0, 1, 2, 1, [1, 2], 1, 2, 1, 2, [['x', 'y'], 3, [1, 2], 4]]
FOUND: ['x', 'y']
is same
=== Flatten(2) ===
looking to fetch: [9, 0] from [0, 1, 2, 1, [1, 2], 1, 2, 1, 2, [['x', 'y'], 3, [1, 2], 4]]
FOUND: ['x', 'y']
is same
Error detected while processing /home/err/bugs/vim/flatten-depth-two.vim:
line  103:
E1158: Cannot use flatten() in Vim9 script, use flattennew()
E116: Invalid arguments for function CheckSame('flatten(2)', data->flatten(2))
```

**Comment by brammool** [comment]
Now that I had a closer look at the flattennew() I see that only the toplevel list is changed.  Items that are a list are moved or copied, but the nested lists are not changed.  Thus it looks like a shallow copy would work.

**Comment by errael** [comment]
Everything I had to throw at it looks good.
