### ISSUE TITLE
Segfault when closing non-current tabpage and an autocommand makes the tabpage the current one on BufWipeout

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#10024]
### Steps to reproduce

1. Run `vim --clean`
2. Source the following file:
```vim
tabedit
let s:window_id = win_getid()
topleft new
setlocal bufhidden=wipe
autocmd BufWipeout <buffer> call win_gotoid(s:window_id)
tabprevious
+tabclose
```
3. Vim segfaults

### Expected behaviour

Vim does not segfault

### Version of Vim

8.2.4628

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

**Comment by zeertzjq** [comment]
Closing the tabpage fails here:
<https://github.com/vim/vim/blob/5e877baf87530d5c4fe4da2c5a6269cf19526c27/src/ex_docmd.c#L6177>
but the buffer is already freed, so drawing the tabline causes a segfault.

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> 1. Run `vim --clean`
> 2. Source the following file:
> ```vim
> tabedit
> let s:window_id = win_getid()
> topleft new
> setlocal bufhidden=wipe
> autocmd BufWipeout <buffer> call win_gotoid(s:window_id)
> tabprevious
> +tabclose
> ```
> 3. Vim segfaults
> 
> ### Expected behaviour
> 
> Vim does not segfault

The documentation for BufWipeout does have this warning:

				Don't change to another buffer, it will cause
				problems.

But Vim should not crash.  I'll see if I can think of a crude way to
avoid the crash.

-- 
Courtroom Quote #19:
Q:  Doctor, how many autopsies have you performed on dead people?
A:  All my autopsies have been performed on dead people.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
