### ISSUE TITLE
Wildmenu popup-window is at the wrong position when a terminal job is running in current tab page

### ISSUE THREAD

**Issue by bfrg** [vim/vim#10035]
### Steps to reproduce

1. Run `vim --clean -c 'set wildoptions=pum | term'`
2. In Vim, type `<c-w>:h <tab>`
3. Result: The popup-menu is not displayed directly above the command-line.

![screenshot-2022-03-28_061200](https://user-images.githubusercontent.com/6266600/160325389-84fcdf88-af2f-44c4-bf2d-f7b91017b242.png)

This happens only when the terminal job is still running. When running `:term ls`, and then typing `<c-w>:e <tab>`, the popup-menu is correctly displayed above the command-line.

### Expected behaviour

Wildmenu pum should always be displayed right above the command-line.

### Version of Vim

8.2.4639

### Environment

Linux

**Comment by brammool** [comment]
I cannot reproduce this.  I also can't think of anything that influences this.

**Comment by bfrg** [comment]
I noticed when I first go to terminal-normal mode with `<c-w>N` before typing `:h <tab>`, everything is fine.

It seems to be related to my bash prompt. Can you reproduce it with a bash prompt that spans two lines?

For example:
```bash
export PS1="\u@\h in \w\n$ "
```

**Comment by vim-ml** [comment]
Hi,

On Mon, Mar 28, 2022 at 12:17 PM bfrg ***@***.***> wrote:

> I noticed when I first go to terminal-normal mode with <c-w>N before
> typing :h <tab>, everything is fine.
>
> It seems to be related to my bash prompt. Can you reproduce it with a bash
> prompt that spans two lines?
>
> For example:
>
> export PS1="\u@\h in \w\n$ "
>
>
>
I am able to reproduce the problem on Ubuntu by adding one or two dummy
echo lines
to the .bashrc file.  The attached patch fixes this problem.  In the
failing case, the
pum_display() function computes the context_lines as 2.  In the working
case, the
context_lines is set to 0.  I am not sure whether the changes in the
attached patch
is the correct way to fix this issue.

- Yegappan

**Comment by brammool** [comment]
[For those reading this on github: the attachment was sent to the vim-dev maillist]

Since you can reproduce the problem, can you write a test that way?  Probably using a screendump.

**Comment by yegappan** [comment]
I have created PR #10050 with the fix and a test. But I think the changes to pum_display()
need to be reviewed. For a cmdline completion popup menu, pum_display() should not
use the curwin to compute the popup menu dimensions.

**Comment by bfrg** [comment]
Thank you! Just tested it and can confirm that it fixes the issue.
