### ISSUE TITLE
vim9: seems LOADSCRIPT of null_* fails

### ISSUE THREAD

**Issue by errael** [vim/vim#10034]
### Steps to reproduce

source the following script
```
vim9script

var hud_item = null_list

def CheckItem(item: list<any>)
    echo 'CheckItem'
    if item != null
        throw 'item empty but not null'
    endif
enddef

#WORKS
CheckItem(hud_item)

def Release()
    echo 'Release'
    if hud_item != null
        throw 'hud_item empty but not null'
    endif
enddef

#FAILS
Release()
```
observe
```
CheckItem
Release
Error detected while processing :source buffer=1[23]..:source buffer=1[23]..function <SNR>37_Release
:
line    3:
E605: Exception not caught: hud_item empty but not null
```

### Expected behaviour

No exception

### Version of Vim

8.2.4636

### Environment

ubuntu gvim-gtk3

**Comment by brammool** [comment]
It is quite tricky to get this right.  If a script variable is declared but not initialized, when fetching the value it must be initialized.  That makes this work:
```
var l: list<number>
add(l, 8)
```

But when initializing the variable to a null value explicitly, it should not be change to an empty list.
Let's see if we can make this work....
