### ISSUE TITLE
E77: Too many file names with expandcmd('{1..10}')

### ISSUE THREAD

**Issue by bfrg** [vim/vim#10048]
### Steps to reproduce

Run: `vim --clean -c 'echo expandcmd("{1..10}")'`

Result:
```
Error detected while processing command line:
E77: Too many file names
{1..10}
```

It seems that the expression `{1..10}` is expanded by the shell (in my case Bash). When I run `:argedit test_{1..5}.c`, Vim will add `test_1.c` to `test_5.c` to the argument list. I haven't seen this documented anywhere. Running `:echo expand('{1..5}')` will print 1 to 5 separated by newlines.

Escaping the opening curly bracket works `expandcmd('\{1..10}')`, but why is this even necessary? Are there more special characters or character combinations that we need to be aware of? For example, `expandcmd('{1..test}')` works fine.

### Expected behaviour

No errors?

### Version of Vim

8.2.4649

### Environment

Linux, Bash

**Comment by gdupras** [comment]
> I haven't seen this documented anywhere.

The closest thing I've seen is at `:help wildcard`, which says

```
Wildcards in {file} are expanded, but as with file completion, 'wildignore'
and 'suffixes' apply.  Which wildcards are supported depends on the system.
```
Now why does `expandcmd('{1..10}')` give `E77: Too many file names`? I don't know. Seems like a bug.

**Comment by chrisbra** [comment]
Yes, there is a note at `:h expand()`

> 		expand() can also be used to expand variables and environment
> 		variables that are only known in a shell.  But this can be
> 		slow, because a shell may be used to do the expansion.  See
> 		|expr-env-expand|.
> 		The expanded variable is still handled like a list of file
> 		names.  When an environment variable cannot be expanded, it is
> 		left unchanged.  Thus ":echo expand('$FOOBAR')" results in
> 		"$FOOBAR".

Also, I can disable this using:  `vim --clean --cmd 'set shell=sh' -c 'echo expandcmd("{1..2}")'`

Note: This can also be verified by `:set verbose=4`.

and finally `:h expandcmd()` shows this:

> expandcmd({string})					*expandcmd()*
> 		Expand special items in String {string} like what is done for
> 		an Ex **command such as `:edit`**.  This expands special keywords,
> 		like with |expand()|, and environment variables, anywhere in
> 		{string}.  "~user" and "~/path" are only expanded at the
> 		start.


See the emphasis. So if you expand something to several words, you'll end up with `E77` as `:e` would complain. Note: `:e {1..10}` also errors out with `E77`. So best is to avoid this.

**Comment by bfrg** [comment]
The note at `:help expand()` only mentions environment variables. It is not clear that it expands any other shell syntax. I thought that's what `backtick-expansion` is for. With backticks I explicitly state that I want it shell-expanded. 

Changing the shell temporarily to something else is a workaround that can work but is not very nice or reliable. What if the specified shell doesn't exist on a system? Setting it to an empty string doesn't work either, then `expandcmd()` throws another error:
```
E91: 'shell' option is empty                                                                                  
E79: Cannot expand wildcards                                                                                  
{1..3}                                                                                                        
```

> See the emphasis. So if you expand something to several words, you'll end up with E77 as :e would complain. Note: :e {1..10} also errors out with E77. So best is to avoid this.

Who says that I want to use it with `:e`? There are commands that do accept several words, for example `:argedit`.

For me this error is unexpected. All I need is the result of `expandcmd({string})`, Vim shouldn't be worried what I use it for. It seems that the implementation uses the same functions as for the expansion of `{file}` in `:edit_f`. See also Bram's comment https://github.com/vim/vim/pull/5122#issuecomment-546622284.

I was looking for a function that expands any `cmdline-special` and `filename-modifiers` in a string passed to a user command. I thought `expandcmd()` would do this without hiccups. Maybe an option could be added to specify whether to invoke the shell for further expansion? Something like `expandcmd({string}, {shellexpand})`?

Somehow related: https://github.com/vim/vim/issues/5120

**Comment by matveyt** [comment]
@chrisbra Yes, you're right. But, the problem is that sometimes we need to expand cmdline-specials while keeping wildcards intact. For example,

```VimL
:!find %:p:h -name '*.txt'
```

works okay. But

```VimL
:let arg = "%:p:h -name '*.txt'"
:call system("find " . arg)
```
fails miserably.

It would be nice if we expandcmd would accept optional argument to step shell-expansion and to process cmdline-specials only.

@bfrg As a workaround, I split command into words and check if any of them matches cmdline-special. If so, then expand() that word.

**Comment by bfrg** [comment]
Okay just checked with `vim -Nu NONE test.c -c 'set verbose=4 | echo expandcmd("% {1..2}")'`:
```
Calling shell to execute: "vimglob() { while [ $# -ge 1 ]; do echo "$1"; shift; done }; vimglob >/tmp/v3zyWFt/0 test.c\ {1..2}"

Error detected while processing command line:
E77: Too many file names
{1..2}
```
So the entire `{string}` in `expandcmd({string})` is first expanded by Vim, and then passed to the shell function `vimglob()`. Maybe it would help if it was documented like this?

**Comment by chrisbra** [comment]
> Changing the shell temporarily to something else is a workaround that can work but is not very nice or reliable. What if the specified shell doesn't exist on a system?

As far as I can see, `/bin/sh` should always exists. Why Vim doesn't make it use brace expansion I do not know. Perhaps the original Posix sh does not support it, so Vim does not attempt to do it or only because this was missing. Don't know.

> Who says that I want to use it with :e

No-one. I was just showing the help. Besides, you may need to use `fnameescape()` in your case.


> :let arg = "%:p:h -name '*.txt'"
> :call system("find " . expandcmd(arg))
> fails miserably.

I don't see this. Seems to work okay for me. My guess is you would need to escape each word separately and not on a complete string.

**Comment by brammool** [comment]
Please keep in mind that some command line expansion is traditionally done with the shell, and different shell implementations work differently.  And it also depends on various options.

The help for expandcmd() states that it works like expanding the argument of ":edit".  For the examples given, please compare to what happens with ":edit".  I could not reproduce the problems or get something different.
