### ISSUE TITLE
Opening a Terminal Emulator in vim(:term) and quitting without closing it leaves a gap in the bottom of the terminal screen 

### ISSUE THREAD

**Issue by ghost** [vim/vim#10056]
### Steps to reproduce

1. :term
2. :q, :q!, or wq (without closing the terminal)

### Expected behaviour

just the terminal screen to get back to what it was before opening vim

### Version of Vim

8.2

### Environment

OS: Arch Linux
Terminal: Kitty
$TERM: xterm-kitty
shell: ZSH

**Comment by chrisbra** [comment]
not sure I understand. Can you please show a screenshot of what you mean?

**Comment by adeldude13** [comment]
im sorry the video is slow, but im sure you can tell what i mean now
https://drive.google.com/file/d/1bmRXSbtuchrlis1A8154fklPsp3gxGk0/view?usp=sharing

**Comment by lacygoill** [comment]
After executing `:q`, you're still inside Vim.  There is still a terminal buffer.  So, when you execute the `vim` command on the shell prompt, you're running a nested Vim instance (Vim inside Vim).  That leads to a confusing environment (2 tablines, 2 statuslines, 2 command-lines, ...).  Unless you have a good reason to do so, I suggest you don't nest Vim.

**Comment by adeldude13** [comment]
ohhhhhhhh im really sorry i did not know that it will nest them, my mistake, thank you for the reply
