### ISSUE TITLE
Vim9: cannot call autoload function imported from relative path in compiled code

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#10054]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        var vimdir = '/tmp/.vim'
        vimdir->mkdir('p')
        var vimrc = vimdir .. '/vimrc'
        var lines =<< trim END
            vim9script
            import autoload './autoload/script.vim'
            def Foo()
                script.Bar()
            enddef
            Foo()
        END
        lines->writefile(vimrc)
        var autodir = vimdir .. '/autoload'
        autodir->mkdir('p')
        lines =<< trim END
            vim9script
            export def Bar()
                echo 'from Bar()'
            enddef
        END
        lines->writefile(autodir .. '/script.vim')
        execute 'source ' .. vimrc
    EOF
    )

An error is given:

    E117: Unknown function: <80><fd>R3_Bar

**Expected behavior**

No error is given.  `from Bar()` is echo'ed.

**Version of Vim**

8.2 Included patches: 1-4655

**Environment**

Operating system: Ubuntu 20.04.4 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: GNU bash, version 5.0.17

**Additional context**

No issue if `Bar()` is called at the script level, rather than from a function:
```vim
vim9script
var vimdir = '/tmp/.vim'
vimdir->mkdir('p')
var vimrc = vimdir .. '/vimrc'
var lines =<< trim END
    vim9script
    import autoload './autoload/script.vim'
    script.Bar()
END
lines->writefile(vimrc)
var autodir = vimdir .. '/autoload'
autodir->mkdir('p')
lines =<< trim END
    vim9script
    export def Bar()
        echo 'from Bar()'
    enddef
END
lines->writefile(autodir .. '/script.vim')
execute 'source ' .. vimrc
```
    from Bar()

---

No issue if we don't use a relative path to autoload `Bar()`:
```vim
vim9script
var vimdir = '/tmp/.vim'
&runtimepath = vimdir
vimdir->mkdir('p')
var vimrc = vimdir .. '/vimrc'
var lines =<< trim END
    vim9script
    import autoload 'script.vim'
    def Foo()
        script.Bar()
    enddef
    Foo()
END
lines->writefile(vimrc)
var autodir = vimdir .. '/autoload'
autodir->mkdir('p')
lines =<< trim END
    vim9script
    export def Bar()
        echo 'from Bar()'
    enddef
END
lines->writefile(autodir .. '/script.vim')
execute 'source ' .. vimrc
```
    from Bar()

**Comment by lacygoill** [comment]
Unrelated to the current issue, but with regards to the error message:

    E117: Unknown function: <80><fd>R3_Bar
                            ^-------^

The byte sequence `<80><fd>R` looks weird.  I guess it's how Vim encodes the pseudo-key `<SNR>` internally, but it seems unexpected for that implementation detail to leak in an error message which is intended to be read by a user.  `<SNR>` would look less weird:

    E117: Unknown function: <SNR>3_Bar
                            ^---^

Here are 2 other examples where the byte sequence is used inside a message:
```vim
vim9script
def Func()
enddef
echo Func
```
    <80><fd>R1_Func
    ^-------^
```vim
vim9script
def Func()
enddef
def Test()
    var d: dict<func> = {func: Func}
    d.func(0)
enddef
Test()
```
    E118: Too many arguments for function: <80><fd>R1_Func
                                           ^-------^

**Comment by brammool** [comment]
> **Steps to reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(tee <<'EOF'
>         vim9script
>         var vimdir = '/tmp/.vim'
>         vimdir->mkdir('p')
>         var vimrc = vimdir .. '/vimrc'
>         var lines =<< trim END
>             vim9script
>             import autoload './autoload/script.vim'
>             def Foo()
>                 script.Bar()
>             enddef
>             Foo()
>         END
>         lines->writefile(vimrc)
>         var autodir = vimdir .. '/autoload'
>         autodir->mkdir('p')
>         lines =<< trim END
>             vim9script
>             export def Bar()
>                 echo 'from Bar()'
>             enddef
>         END
>         lines->writefile(autodir .. '/script.vim')
>         execute 'source ' .. vimrc
>     EOF
>     )
> 
> An error is given:
> 
>     E117: Unknown function: <80><fd>R3_Bar

Some time ago there was a short discussion about how to recognize that
a script is an autoload script, resulting in items defined with
"script#item" names and being able to access them that way.  Then it was
accepted that the directory being "autoload" would be sufficient.

So the script here loads an autoload script, but uses a relative name.
Now the items would be expected to be available as script.item, but they
are actually defined as script#item.  This works:

             vim9script
             import autoload './autoload/script.vim'
             def Foo()
                 script#Bar()
             enddef
             Foo()

> **Additional context**
> 
> No issue if `Bar()` is called at the script level, rather than from a
> function:

Strange that this does work... Ah, the script has both an autoload
prefix and has sn_import_autoload set.  Here the prefix overrules the
other, other places work the other way around.  I can fix that.

-- 
TIM: But follow only if you are men of valour.  For the entrance to this cave
     is guarded by a monster, a creature so foul and cruel that no man yet has
     fought with it and lived.  Bones of full fifty men lie strewn about its
     lair ...
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
> Unrelated to the current issue, but with regards to the error message:
> 
>     E117: Unknown function: <80><fd>R3_Bar
>                             ^-------^
> 
> The byte sequence `<80><fd>R` looks weird.  I guess it's how Vim
> encodes the pseudo-key `<SNR>` internally, but it seems unexpected for
> that implementation detail to leak in an error message which is
> intended to be read by a user.  `<SNR>` would look less weird:
> 
>     E117: Unknown function: <SNR>3_Bar
>                             ^---^

Yeah, this does happen when the function is known.  I'll make a patch to
catch a few more places.  Let me know if you find one I missed.

-- 
The Law of VIM:
For each member b of the possible behaviour space B of program P, there exists
a finite time t before which at least one user u in the total user space U of
program P will request b becomes a member of the allowed behaviour space B'
(B' <= B).
In other words: Sooner or later everyone wants everything as an option.
                                        -- Vince Negri

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
