### ISSUE TITLE
Netrw fails to open file with long filename

### ISSUE THREAD

**Issue by xudongzheng** [vim/vim#10055]
### Steps to reproduce

Add `let g:netrw_liststyle = 1` to `.vimrc`

Create a directory with several files like in the following screenshot

![Screen Shot 2022-03-31 at 13 22 27](https://user-images.githubusercontent.com/4230040/161114095-c5476d5f-8262-4895-9093-ffaddaab0d9d.png)

- `123456789012345678901234567890` and `1234567890123456789012345678901` open correctly
- `12345678901234567890123456789012` does not open correctly. Vim opens the `12345678901234567890123456789012 29 Thu Mar 31 13:17:54 2022` file instead. Same problem with `123456789012345678901234567890123`.

### Expected behaviour

File `12345678901234567890123456789012` should open correctly.

### Version of Vim

8.2.4113

### Environment

Operating System: macOS 12.3 (I'm running the macOS default version of Vim)

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 12 2022 04:26:50)
macOS version - x86_64
Included patches: 1-4113
Compiled by root@apple.com

**Comment by cecamp** [comment]
See  :help g:netrw_maxfilenamelen  and set it to a larger number.

**Comment by cecamp** [comment]
And the next complaint will be that for 33+ character filenames that the long listing display is uneven. I suppose that that's better than picking up an incorrectly named file, so I'll include it.
