### ISSUE TITLE
`:highlight clear` sets color scheme to `default`

### ISSUE THREAD

**Issue by Ace-Who** [vim/vim#10060]
### Steps to reproduce

    :highlight clear

### Expected behaviour

Don't change color scheme.

### Version of Vim

8.2.4602

### Environment

Windows 7, cmd.exe and gvim

**Comment by brammool** [comment]
":hi clear" intentionally removes all non-default highlighting, that is what it's for.
If you want to re-apply the colorscheme (after you messed with the colors) use ":exe 'colors ' .. colors_name".

**Comment by Ace-Who** [comment]
Thanks. Seems misguided by its behavior in an old version.
