### ISSUE TITLE
Popup window not always drawn correctly, and redrawing issues

### ISSUE THREAD

**Issue by bfrg** [vim/vim#10061]
### Steps to reproduce

There are quite a few drawing issues when the popup window doesn't fit on the screen.

#### Drawing issues after opening popup window

1. Run `vim --clean -S test.vim`, with
```vim
call range(100)
        \ ->map({_,i -> string(i)})
        \ ->popup_create({
        \   'drag': 1,
        \   'wrap': 0,
        \   'border': [],
        \   'scrollbar': 1,
        \   'minwidth': 1000,
        \   'filter': {w, k -> k ==# 'q' ? len([popup_close(w)]) : 0},
        \ })
```
2. Result: The right side of the popup window is not drawn correctly. It looks like Vim is trying to draw the scrollbar (my guess). But since no `maxheight` has been specified, I thought there shouldn't even be one. I would have expected the popup window to be extended beyond the screen in vertical direction, similar to gui windows when they are dragged to the bottom. At least that what it looks like in the screenshot below. The bottom and right side are cut off.

**Screenshot**
![screenshot-2022-04-02_000627](https://user-images.githubusercontent.com/6266600/161347372-89de5d9e-9431-4742-a190-7aa0d1f838bc.png)

---

#### Drawing issues after dragging the popup window around

1. Now start moving the window around with the mouse.
2. Result: The right side of the popup window is not drawn correctly. Notice also that if you move the popup window in vertical direction, the lower border of the window suddenly appears on the screen. I don't know which behavior was initially intended, either cutting off the bottom of the popup window or resizing it so that it fits onto the screen. Either way it should be consistent behavior. It also looks like only the height is readjusted. The right border is never displayed.

**Screenshot** 
![screenshot-2022-04-02_001202](https://user-images.githubusercontent.com/6266600/161347855-af323d2c-b43d-4bc4-93f1-79137bc52da9.png)

---

#### Drawing issues when closing the popup window from the command-line

1. While the popup window is displayed, go into command-line mode with `:`, and then press `<C-c>` twice.
2. Result: The command-line is not redrawn after the popup window is closed.

**Screenshot**
![screenshot-2022-04-02_004058](https://user-images.githubusercontent.com/6266600/161351294-453ec0b5-37f0-455e-8cef-46e852823252.png)

---

#### Drawing issues in vertical direction

1. Now make the popup width smaller so that it fits into the screen.
```vim
call range(30)
        \ ->map({_,i -> string(i)})
        \ ->popup_create({
        \   'drag': 1,
        \   'wrap': 0,
        \   'border': [],
        \   'scrollbar': 1,
        \   'minwidth': 10,
        \   'filter': {w, k -> k ==# 'q' ? len([popup_close(w)]) : 0},
        \ })
```
2. Result: The scrollbar appears, even though no `maxheight` has been set. But the bottom border isn't displayed. If you scroll with the mouse wheel to the bottom of the text, the last line won't be displayed.

**Screenshot**
![screenshot-2022-04-02_005046](https://user-images.githubusercontent.com/6266600/161353211-e401a392-f724-4485-b58b-d806b9e54a87.png)

### Expected behaviour

No drawing artifacts.

And I don't understand the current behavior. It looks like Vim is trying to resize the popup to the correct width and height so that it always stays fully visible on the screen. But it doesn't do it right. Maybe it is easier to not do any resizing and leave it to the user?

Related  #6676.

### Version of Vim

8.2.4663

### Environment

Linux

**Comment by brammool** [comment]
This turns out to be very tricky, many options matter.
I managed to avoid the drawing problems, but the resulting behavior might not be exactly what you expect.
Try it out after the patch and we'll see if this is acceptable.

**Comment by Shane-XB-Qian** [comment]
sorry jump in, but BTW:
![image](https://user-images.githubusercontent.com/13550529/161388214-7fbbc6a3-5e3e-42d7-9dd7-1fe35d04a99b.png)

was there a way to make selected/matched item always on top of the list/items?
or was there a way to scroll the scrollbar when tui vim (without mouse)?
sorry but i did not find a good way so far...

**Comment by bfrg** [comment]
@Shane-XB-Qian are you talking about ins-completion-menu?

**Comment by Shane-XB-Qian** [comment]
> are you talking about ins-completion-menu? 

yes. 
// similar topic about scrollbar.. :-)

was there a way to scroll the pum scrollbar without mouse?
or how to make the selected/matched item always on or near the top?

-- 
shane.xb.qian

**Comment by bfrg** [comment]
You can scroll with `<Up>`, `<Down>`, `<PageUp>` and `<PageDown>`. This will move the popup's cursorline without inserting the item. See `:h popupmenu-keys`.

**Comment by Shane-XB-Qian** [comment]
um... that's different thing... after those 4 keys actually selected item changed.. and besides, it did not make selected item on/near the top.
