### ISSUE TITLE
block visual mode insert not working

### ISSUE THREAD

**Issue by leyafo** [vim/vim#10069]
### Steps to reproduce

1. ctrl + v enter the visual mode
2. select some lines
3. enter I(shift+i)
4. enter #
5. esc
6. nothing to insert

### Expected behaviour

insert a '#' in the beginning of every selected line.

### Version of Vim

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 24 2022 18:41:57)

### Environment

Manjaro Linux x86_64 
Kernel: 5.10.105-1-MANJARO
Gnome terminal/gvim
xterm-256color

**Comment by brammool** [comment]
Works just fine for me.  Did you start with "vim --clean" ?

**Comment by leyafo** [comment]
> Works just fine for me. Did you start with "vim --clean" ?
vim --clean works fine.

**Comment by leyafo** [comment]
> It may also depend on the lines. Can you please give an example with the content to be commented out?

What I should do? as @brammool say, when I run `vim --clean`, it works fine.

**Comment by chrisbra** [comment]
reproduce with a minimal vimrc without problems.  See https://vimhelp.org/vim_faq.txt.html#faq-2.5

And show the content of the file where you are trying to use the block insert.

**Comment by brammool** [comment]
Most likely a plugin is interfering.  Disable all your plugins (how depends on how you installed them).
You can also try to set 'filetype' to see if that makes a difference.
