### ISSUE TITLE
sh.vim: Syntax highlighting thinks quote does not close

### ISSUE THREAD

**Issue by JohnVillalovos** [vim/vim#1008]
I have this code:

```
host_ip_iface=${host_ip_iface:-$(ip -f $af route | awk '/default/ {print $5}' | head -1)}
true
```

The ' after {print 5} makes everything show up as quoted text after that point.

The snippet is from this file:
https://github.com/openstack-dev/devstack/blob/38245da0b8ab1a08ae192ef2c0d5755a8f88841a/functions-common#L665

**Comment by JohnVillalovos** [comment]
Doing a git bisect. This commit introduced the issue.

commit 91c4937be15b0b743b6bc495df602c1abbff6b87
Author: Bram Moolenaar Bram@vim.org
Date:   Sun May 8 09:50:29 2016 +0200

```
Updated runtime files.
```

**Comment by cecamp** [comment]
John Villalovos wrote:

> I have this code:
> 
> |host_ip_iface=${host_ip_iface:-$(ip -f $af route | awk '/default/
> {print $5}' | head -1)} |
> 
> The ' after {print 5} makes everything show up as quoted text after
> that point.
> 
> [snip]

The latest syntax/sh.vim does not exhibit a problem with this code; you
may get it from http://www.drchip.org/astronaut/vim/index.html#SYNTAX_SH .

Regards,
Chip Campbell

**Comment by JohnVillalovos** [comment]
Not in my testing.  I just downloaded it and I still see the same issue.

Downloaded version was: 160
Working version is: 147

I tested by putting the `sh.vim` file in `~/.vim/syntax/sh.vim`

John

**Comment by chdiza** [comment]
I tried version 161 and the issue is still there, whether I put the file in `~/.vim/syntax` or `$VIMRUNTIME/syntax`.

**Comment by cecamp** [comment]
chdiza wrote:

> I tried version 161 and the issue is still there, whether I put the
> file in |~/.vim/syntax| or |$VIMRUNTIME/syntax|.
> 
> I was able to duplicate the issue -- looks like its a bash vs kornshell
> thing.  Please try v162 of syntax/sh.vim, available at
> http://www.drchip.org/astronaut/vim/index.html#SYNTAX_SH .

Regards,
Chip Campbell

**Comment by chdiza** [comment]
I can confirm that v162 works.

**Comment by JohnVillalovos** [comment]
v162 fixed the issue for me :)

Thanks!
John

**Comment by norman-abramovitz** [comment]
Still seeing incorrect syntax highlighting  for shell scripts

" Vim syntax file
" Language:     shell (sh) Korn shell (ksh) bash (sh)
" Maintainer:       Charles E. Campbell  <NdrOchipS@PcampbellAfamily.Mbiz>
" Previous Maintainer:  Lennart Schultz <Lennart.Schultz@ecmwf.int>
" Last Change:      Sep 22, 2016
" Version:      165

```bash
#!/bin/bash

a="\""

# syntax highlighting is correct
[[ "${a}" = [\"\'] ]] && {
    echo "found quote 1"
}

# syntax highlighting is incorrect (flipped around the quotes in [])
[[ "${a}" = [\'\"] ]] && {
    echo found quote 2
}
```

**Comment by cecamp** [comment]
I don't see this problem with v168 of syntax.sh.vim .  Please try it. (http://www.drchip.org/astronaut/vim/index.html#SYNTAX_SH)

Regards,
Chip Campbell

**Comment by norman-abramovitz** [comment]
Still seeing incorrect colorization with 168

<img width="733" alt="screen shot 2017-02-06 at 10 26 41 am" src="https://cloud.githubusercontent.com/assets/13754664/22660577/f147131a-ec56-11e6-8313-e7b193222a6b.png">

**Comment by marcelpaulo** [comment]
I'm running vim 606cb8b08 with _syntax/sh.vim_ version **174**, and @norman-abramovitz's snippet is correctly syntax-highlighted:
![image](https://user-images.githubusercontent.com/10074769/39659379-6cccd866-4ffd-11e8-94ff-c9266abe678b.png)

**Comment by marcelpaulo** [comment]
On the other hand, in the default _.bashrc_, created from _/etc/skel/.bashrc_, the alias definition for `alert` is treated as if the quotes didn't close properly (I added a phony alias after it, just to reinforce that the syntax highlighting is wrong:
![image](https://user-images.githubusercontent.com/10074769/39666170-bb341cbc-5075-11e8-856a-b17b9fbbe09b.png)

I'm running vim 606cb8b08 on Xubuntu 18.04 with _syntax/sh.vim_ version **174**.

I downloaded the `vim-runtime` package (version **8.0.1453**) from the Ubuntu repositories, extracted _syntax/sh.vim_ (version **172**), placed it in _~/.vim/syntax_, and that same alias was then correctly highlighted. So it seems that whatever is the cause for this issue, it crept in version **173** or **174**.

**Comment by meereeum** [comment]
@cecamp thanks for all your work on this! I'm seeing an edge case where syntax highlighting fails to ignore quote in a comment..

running:
```.vim
" Vim syntax file
" Language:		shell (sh) Korn shell (ksh) bash (sh)
" Maintainer:		Charles E. Campbell  <NdrOchipS@PcampbellAfamily.Mbiz>
" Previous Maintainer:	Lennart Schultz <Lennart.Schultz@ecmwf.int>
" Last Change:		May 22, 2018
" Version:		175	ASTRO-ONLY
" URL:		http://www.drchip.org/astronaut/vim/index.html#SYNTAX_SH
```
(also tested with my distro default, v. 165)

![vimsyntaxfail](https://user-images.githubusercontent.com/7970350/40439859-3e276cf6-5e8a-11e8-8991-2a965e3922f8.png)

**Comment by norman-abramovitz** [comment]
At least for my example above dated Feb 1, 2017, sh.vim version 174 is working.  Thank you whoever fixed it!

**Comment by chrisbra** [comment]
closing then.

**Comment by meereeum** [comment]
ok, I'll start a new issue

**Comment by marcelpaulo** [comment]
@chrisbra, as I showed in my example, this issue is still present. It should not have been closed. It would be more useful to track it here than opening new issues.

@meereeum, when you open a new issue, please mention me, so that I can also add my edge case to your issue.

**Comment by cecamp** [comment]
Paulo Marcel Coelho Aragão wrote:
    
    
      On the other hand, in the default .bashrc, created
        from /etc/skel/.bashrc, the alias definition for alert
        is treated as if the quotes didn't close properly (I added a
        phony alias after it, just to reinforce that the syntax
        highlighting is wrong:
        
      
    
    Please try the latest syntax/sh.vim from my website (v177): 
    http://www.drchip.org/astronaut/vim/index.html#SYNTAX_SH
    
    I used the following shell script - please check that I typed it in
    correctly:
    
      alias alert='notify-send --urgency=low -i "$([ $? = 0]
      && echo terminal || echo error)" "$(history|tail -n1|sed
      -e '\'s/^\s*[0-9]\+\s*//;s[;&|]\s*alert$//'\'')"'
    
    I'd appreciate it if you and others with syntax issues would send me
    some clean text (or an attached file) rather than making me re-type
    it from an image/screenshot, by the way.
    
    Regards,
    Chip Campbell

**Comment by vim-ml** [comment]
On 2018-05-24, cecamp wrote:

> Please try the latest syntax/sh.vim from my website (v177): 
> http://www.drchip.org/astronaut/vim/index.html#SYNTAX_SH

That's really nice!  It fixes a problem I've seen for quite a while
with single-quotes/apostrophes within shell comments.  Thank you.

Regards,
Gary

**Comment by marcelpaulo** [comment]
> I'd appreciate it if you and others with syntax issues would send me
    some clean text (or an attached file) rather than making me re-type
    it from an image/screenshot

You're absolutely, right, @cecamp, my sincerest apologies.

With **v177**, the following line is correctly syntax-highlighted:

```
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
```

I've also checked @meereeum's snippet:

```
#!/bin/bash

set -u
ls -alh # I'm a comment
set -u # I'm also a comment
WORKS=":)"
echo $WORKS

set -u # I'm a comment
WORKS=":)"
echo $WORKS
```

and it's also correctly syntax-highlighted.

Thanks a bunch, @cecamp !

**Comment by vim-ml** [comment]
On 2018-05-24, Gary Johnson wrote:
> On 2018-05-24, cecamp wrote:
> 
> > Please try the latest syntax/sh.vim from my website (v177): 
> > http://www.drchip.org/astronaut/vim/index.html#SYNTAX_SH
> 
> That's really nice!  It fixes a problem I've seen for quite a while
> with single-quotes/apostrophes within shell comments.  Thank you.

I may have written too soon.  While this version does solve that
problem, it introduces another.  Given the following file,

    set -o ignoreeof # 
    shopt -s extglob

and this command,

    $ vim -N -u NONE -i NONE -c 'let b:is_bash=1' -c 'set ft=sh' -c 'syn on' file

the word "shopt" is highlighted as shSetList instead of shStatement.
Deleting the '#' fixes the highlighting so that "shopt" is
highlighted as shStatement.

Another problem is that "extglob" is not given any highlighting at
all.  It should probably be Identifier (like shSetList), as
"ignoreeof" is.

Regards,
Gary

**Comment by yankee14** [comment]
Syntax highlighting/coloring is broken for me, too:

```bash
function get_gpio_mode()
{
    IFS='|' read -r -a gpio_mode_power <<< "$(gpio readall | tr --delete ' ' | grep 'GPIO.25')"
}
```

It thinks that the very last double quote is not matched to another quote. It's clearly possible to highlight correctly, since GitHub was able to color it correctly.

**Comment by cecamp** [comment]
yankee4 : I don't see anything wrong with the highlighting for your example.  Are you using v8.0-23?
Gary: I don't see the problem with shopt using v8.0-23.  Its being highlighted as shStatement.

**Comment by yankee14** [comment]
@cecamp: crap, I'm using neovim, so nevermind. In case someone stumbles on this from a Google search, my nvim version is v0.3.4

**Comment by vim-ml** [comment]
On 2019-08-07, cecamp wrote:

> Gary: I don't see the problem with shopt using v8.0-23. Its being
> highlighted as shStatement.

I repeated the experiment today using vim 8.1.1200 and syntax/sh.vim
version 186.  The shopt is highlighted as shStatement, as it should
be.

I don't remember all the changes I may have made since May 24.
I may just have gotten rid of v177 in favor of the v186 in
$VIMRUNTIME.  In any case, thanks for getting back to me on that.
It looks good now.

Regards,
Gary

**Comment by yankee14** [comment]
@cecamp I installed vim and used it instead of neovim, and the issue persists:

```
$ apt policy vim
vim:
  Installed: 2:8.1.0875-5
  Candidate: 2:8.1.0875-5
  Version table:
 *** 2:8.1.0875-5 500
        500 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages
```

[File where it happens](https://gist.github.com/yankee14/31146be21c4e44d56932fa8e1e5afc59#file-smarthub-networking-cellular-lib-sh-L58). The escaped single quote in `delimiter=\'` is what seems to be causing it:

```bash
function get_cellular_registration_state()
{
    declare -r registration_state_raw="$(mbimcli --device-open-proxy --device=${MBIM_DEVICE} --query-registration-state | grep --extended-regexp "Register state" | cut --delimiter=\' -f2)"
}

function wait_for_cellular_registration()
{
    declare -r start_time_s=$SECONDS
}
```

**Comment by k-takata** [comment]
@yankee14 syntax/sh.vim which comes with Vim 8.1.0875 is version 185, and the latest syntax/sh.vim is version 188. Please try with the newer version.

**Comment by yankee14** [comment]
I downloaded sh.vim from 6c1e157 and placed it at `~/.vim/syntax/test.vim`. I loaded it with `:set syntax=test`. Issue persists. Unfortunately, I'm not going to be able to update the actual vim version.

EDIT: m_ben on freenode#vim confirmed issue exists in 8.1.1846
EDIT2: Compiled vim from source, issue exists in 8.1.1847

**Comment by zdm** [comment]
5 years passed, but after hard efforts issue is still present. ;-)

**Comment by k-takata** [comment]
I don't see the issue originally reported.
Could you show a reproducible code?

**Comment by yankee14** [comment]
I can confirm that at least my code example is fixed:

![image](https://user-images.githubusercontent.com/12487802/87026281-230a6280-c1a1-11ea-8900-79332a259c87.png)

As of:

```
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 12 2020 02:37:13)
Included patches: 1-716
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
-autoservername    +folding           +multi_byte        +termguicolors
-balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
-browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              -perl              +title
-clientserver      +job               +persistent_undo   -toolbar
-clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           -python            +visual
+conceal           +linebreak         -python3           +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       -lua               -ruby              +wildmenu
+dialog_con        +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
-dnd               +mouse             +sound             -xfontset
-ebcdic            -mouseshape        +spell             -xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              +mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-RuXSEA/vim-8.2.0716=. -fstack-protector-strong -Wformat -Werror=format-security -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo  -lselinux -lcanberra -lacl -lattr -lgpm -ldl
```

**Comment by zdm** [comment]
vim 8.2.1154
```
FILES=$(git diff --cached --name-only --diff-filter=ACM)
```
<img width="960" alt="Annotation 2020-07-09 131159" src="https://user-images.githubusercontent.com/1025608/87027465-df861780-c1e5-11ea-8a6f-6c5222921d45.png">

**Comment by chrisbra** [comment]
looks like you want to configure to use bash as shell syntax

**Comment by chrisbra** [comment]
Have a look at `:h ft-sh-syntax` for how to configure it

**Comment by k-takata** [comment]
Looks correct. If you don't want to show `$()` as an error, add `let g:is_posix = 1` in your .vimrc as the help says.

**Comment by zdm** [comment]
yes, with set ft=bash error has gone.

**Comment by SuperSandro2000** [comment]
Using version 197 from the website I get alternating colors when escaping quotes: 
![image](https://user-images.githubusercontent.com/7258858/108432716-2096dd80-7245-11eb-9128-b9db3b8b8428.png)

**Comment by cecamp** [comment]
The a="\"\"..." is a problem that can't be solved with current vim highlighting syntax. To do it properly would I would need to have something like "nextgroup" (maybe begingroup=...) so vim could start with trying to recognize the initial backslash+character as an escape sequence.

**Comment by cecamp** [comment]
Sorry -- should have used code; the backslashes I put in were ignored: `a="\"\"\"...\""`.
