### ISSUE TITLE
Vim9: type not recognized when using lambda with `<SID>`

### ISSUE THREAD

**Issue by noscript** [vim/vim#10082]
### Steps to reproduce

1. Create `~/lambda_type9.vim`:
```vim
vim9script

def MyFunc()
enddef

echo type(() => MyFunc())
execute 'echo type(() => MyFunc())'
execute 'echo type(() => ' .. expand('<SID>') .. 'MyFunc())'
```
2. Run vim:
```sh
vim --clean -g +'so ~/lambda_type9.vim'
```

3. Error:
```
2
2
Error detected while compiling command line..script ~/lambda_type9.vim[8]..function <lambda>3:
line    1:
E1010: Type not recognized: SNR>11_MyFunc()
Error detected while processing command line..script ~/lambda_type9.vim:
line    8:
E116: Invalid arguments for function type(() => <SNR>11_MyFunc())
```

### Expected behaviour

Outputs:
```
2
2
2
```

Equivalent Vim8 code that works as expected:
```vim
function MyFunc()
endfunction

echo type({-> MyFunc()})
execute 'echo type({-> MyFunc()})'
execute 'echo type({-> ' .. expand('<SID>') .. 'MyFunc()})'
```

### Version of Vim

8.2.4621

### Environment

OS: Debian 11
Terminal: GUI

**Comment by brammool** [comment]
Sergey Vlasov wrote:

> ### Steps to reproduce
> 
> 1. Create `~/lambda_type9.vim`:
> ```vim
> vim9script
> 
> def MyFunc()
> enddef
> 
> echo type(() => MyFunc())
> execute 'echo type(() => MyFunc())'
> execute 'echo type(() => ' .. expand('<SID>') .. 'MyFunc())'
> ```
> 2. Run vim:
> ```sh
> vim --clean -g +'so ~/lambda_type9.vim'
> ```
> 
> 3. Error:
> ```
> 2
> 2
> Error detected while compiling command line..script ~/lambda_type9.vim[8]..function <lambda>3:
> line    1:
> E1010: Type not recognized: SNR>11_MyFunc()
> Error detected while processing command line..script ~/lambda_type9.vim:
> line    8:
> E116: Invalid arguments for function type(() => <SNR>11_MyFunc())
> ```
> 
> ### Expected behaviour
> 
> Outputs:
> ```
> 2
> 2
> 2
> ```
> 
> Equivalent Vim8 code that works as expected:
> ```vim
> function MyFunc()
> endfunction
> 
> echo type({-> MyFunc()})
> execute 'echo type({-> MyFunc()})'
> execute 'echo type({-> ' .. expand('<SID>') .. 'MyFunc()})'
> ```

Using the expanded <SID> was a workaround to be able to call a
script-local function in another script.  In Vim9 you should export the
function and import it where you want to use it.

If there is a situation where calling the script-local function is
impossible, please show an example.

-- 
A parent can be arrested if his child cannot hold back a burp during a church
service.
		[real standing law in Nebraska, United States of America]

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by noscript** [comment]
I have a command that takes expression as an argument. Using `<SID>` I can pass a script-local function. I would like the function to remain script-local and not export it or make it global.

>If there is a situation where calling the script-local function is
impossible, please show an example.

It is impossible to use script-local functions with commands defined in another script. Here is an example:

`~/vim9_cmd.vim`:
```vim
vim9script

def My_exec(expr: string)
  execute expr
enddef

command! -nargs=1 MyCmd My_exec(<f-args>)
```

`~/vim9_cmd_use.vim`:
```vim
vim9script

def MyFunc()
  echo 'hello'
enddef

#MyCmd MyFunc() # E117: Unknown function: MyFunc
execute 'MyCmd ' .. expand('<SID>') .. 'MyFunc()' # this works
```
```sh
vim -g --clean +'so ~/vim9_cmd.vim' +'so ~/vim9_cmd_use.vim'
```

If there only was something similar to `<ScriptCmd>` for commands it would solve the problem.

**Comment by brammool** [comment]
> I have a command that takes expression as an argument. Using `<SID>` I
> can pass a script-local function. I would like the function to remain
> script-local and not export it or make it global.
> 
> >If there is a situation where calling the script-local function is
> >impossible, please show an example.
> 
> It is impossible to use script-local functions with commands defined
> in another script. Here is an example:
> 
> `~/vim9_cmd.vim`:
> ```vim
> vim9script
> 
> def My_exec(expr: string)
>   execute expr
> enddef
> 
> command! -nargs=1 MyCmd My_exec(<f-args>)
> ```

Using this directly works:  :MyCmd ls

> `~/vim9_cmd_use.vim`:
> ```vim
> vim9script
> 
> def MyFunc()
>   echo 'hello'
> enddef
> 
> #MyCmd MyFunc() # E117: Unknown function: MyFunc
> execute 'MyCmd ' .. expand('<SID>') .. 'MyFunc()' # this works
> ```
> ```sh
> vim -g --clean +'so ~/vim9_cmd.vim' +'so ~/vim9_cmd_use.vim'
> ```

Your My_exec() functions does "execute expr", which is evaluated in the
context of that function.  There you have no access to MyFunc(), since
it is script-local in another script.
 
> If there only was something similar to `<ScriptCmd>` for commands it
> would solve the problem.

I think you need to take a step back: Why are you tring to use a command
to execute an expression?  We have the export/import mechanism to use a
script-local function in one script in another script.  The export makes
clear that the function is intended to be called from elsewhere.

-- 
For a moment, nothing happened.
Then, after a second or so, nothing continued to happen.
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
