### ISSUE TITLE
E383: Invalid search string: \%>0l even though search pattern correctly highlighted

### ISSUE THREAD

**Issue by bfrg** [vim/vim#10089]
### Steps to reproduce

1. Open a random file
2. `set hlsearch incsearch`
3. Type `/\%>0l`
4. Result: as long as ENTER hasn't been hit, no errors. The entire file is highlighted (as expected).
5. Now hit ENTER.
6. Result:
```
E1273: (NFA regexp) missing value in '\%l'
E383: Invalid search string: \%>0l
```

The same errors occurs with `/\%>0c` and `/\%>0v`.

### Expected behaviour

The error is unexpected since Vim correctly highlights every line > 0. I don't see anything wrong with the regex.

### Version of Vim

8.2.4688

### Environment

Linux

**Comment by lacygoill** [comment]
I think it will be fixed tomorrow:

> I assumed the value zero would not be useful, it would always match.
> But your example shows how it might be used anyway.  I'll come up with a
> fix tomorrow.

[source](https://github.com/vim/vim/commit/91ff3d4f52a55a7c37a52aaad524cd9dd12efae4#commitcomment-70463949)

**Comment by bfrg** [comment]
Okay, sorry for the noise.
