### ISSUE TITLE
Cannot remap `<LeftDrag>` with `<Cmd>` in INSERT mode

### ISSUE THREAD

**Issue by noscript** [vim/vim#10080]
### Steps to reproduce

1. Create `~/leftdrag.vim`:
```vim
let s:counter = 0
function! LeftDrag()
  execute 'set titlestring=' .. s:counter
  let s:counter += 1
endfunction

noremap  <LeftDrag> <LeftDrag><Cmd>call LeftDrag()<CR>
noremap! <LeftDrag> <LeftDrag><Cmd>call LeftDrag()<CR>
```
2. Run vim:
```sh
vim --clean -g +'so ~/leftdrag.vim' README.md
```
3. Do text selection with mouse. Counter in the GUI title bar will be increasing.
4. Go to INSERT mode and do text selection with mouse. 
5. Error:
```
E492: Not an editor command: ^Ocall LeftDrag(): ^Ocall LeftDrag()
```

### Expected behaviour

No error.

### Version of Vim

8.2.4621

### Environment

OS: Debian 11
Terminal: GUI

**Comment by brammool** [comment]
I managed to fix this (in two tries), but writing a test for it turns out to be complicated.
I hope someone can have a go at it.
