### ISSUE TITLE
vim9: "var t: list<any> = null_list" doesn't work as expected

### ISSUE THREAD

**Issue by errael** [vim/vim#10088]
### Steps to reproduce

The first two lines of this output are unexpected
```
list<unknown>: []
list<unknown>: []
list<unknown>: NULL
```
Produced  by the following script
```
vim9script

def Dump(last: list<any>): string
    if last == null
        return typename(last) .. ': NULL'
    else
        return typename(last) .. ': ' ..  string(last)
    endif
enddef

# fails: list<unknown>: []
var t: list<any>
t = null_list
echo Dump(t)

# fails: list<unknown>: []
var u: list<any> = null_list
echo Dump(u)

# works: list<unknown>: NULL
var v = null_list
echo Dump(v)
```

### Expected behaviour

```
list<unknown>: NULL
```

is output 3 times

### Version of Vim

8.2.4676

### Environment

ubuntu, gvim-gtk3

**Comment by brammool** [comment]
Currently it guesses the variable wasn't initialized by the type.  Apparently that doesn't work in this situation.
I'll add a flag explicitly keeping track of whether the variable was assigned a value.
Only when not then it should default to an empty list.
