### ISSUE TITLE
Provide a function for converting display columns to byte indexes

### ISSUE THREAD

**Issue by bfrg** [vim/vim#10098]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

Vim doesn't provide any functions to  convert display (screen) columns to byte columns. Some compilers and linters print the locations in display columns. While this doesn't matter for the quickfix list (`errorformat` needs `%v` instead of `%c`), the byte index is nevertheless necessary when highlighting the quickfix locations with text properties.

**Describe the solution you'd like**

It would be nice to have a function like
```
display2byte({string}, {col})
```
that returns the byte index of a display column, i.e. the opposite of `strdisplaywidth({string})`. Other names I've considered were `virt2byte()`.

Alternatively, maybe `byteidx({string}, {nr})` could be extended with an optional parameter `{display}`, that, if set to true treats `{nr}` like a display column and not character index.

**Describe alternatives you've considered**

The following works but looks weird and is probably not very efficient:
```vim
vim9script

export def Display2byte(str: string, virtcol: number): number
    const ts_old: number = &tabstop
    &tabstop = 8
    var col: number
    try
        col = match(str, printf('\%%%dv', virtcol)) + 1
    finally
        &tabstop = ts_old
    endtry
    return col
enddef
```

**Comment by brammool** [comment]
So, it would work like using col() on the given string?  Thus you could open a new window, put the string in there and use col() to get the result.  I don't think there is an internal function for this, everything works on text in the buffer.  Thus it's not trivial to add.

**Comment by zeertzjq** [comment]
Does `vcol2col()` do this?

**Comment by brammool** [comment]
The existing functions work an a buffer line.  If that is sufficient it should be possible to use an existing function (or perhaps we can tweak it a bit).  If the desire is really to pass a string that is more complicated.

**Comment by bfrg** [comment]
Yes that's sufficient, assuming the function optionally accepts a window ID. Then the buffer doesn't have to be in the current window. And it will certainly be more efficient than calling `getbufline()`.

**Comment by brammool** [comment]
> Yes that's sufficient, assuming the function optionally accepts a
> window ID. Then the buffer doesn't have to be in the current window.
> And it will certainly be more efficient than calling `getbufline()`.

As mentioned, the existing vcol2col() function should do the job then.
It is currently used to convert the mouse position to a byte index in a
line.

It looks like screenpos() is doing the opposite, so how about calling it
screenpos2col()?

I hope someone can look into implementing this.  Then please review if
indeed does what you needed.

-- 
Corn oil comes from corn and olive oil comes from olives, so where
does baby oil come from?

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
