### ISSUE TITLE
Disable auto visual mode on when double-clicking mouse

### ISSUE THREAD

**Issue by ydzhou** [vim/vim#10094]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
If you set your mouse in all mode (`set mouse=a`) and double click mouse on any text, the vim automatically switch to visual mode. This can cause a lot of frustration such as random highlighting bunch of text when you start navigating the doc or preventing correct highlighting during search. 

This design is very anti-pattern in following ways
1. Intuitively speaking, even tho it sounds like full mouse support, but most of people will not expect a mode change by some unrelated mouse event.
2. This mode change can be easily triggered unintentionally. So sometimes you will not even notice you double clicked until you find out you are not in normal mode and performed some wrong actions.
3. The visual mode in Vim is not a sole mouse job, it relies on a lot of keyboard typing. It is OK to switch to visual mode only by explicitly typing the keyboard since you need to type even in the visual mode.

**Describe the solution you'd like**
Simply disable this auto-enable visual mode for `set mouse=a` or provide an option to enable/disable.

**Describe alternatives you've considered**
Unless certain mode (auto switch visual mode) is set for `set mouse`, mouse events will not autoswitch Vim mode.

**Comment by brammool** [comment]
I find the double click to select a word very convenient.
If you don't want it, you can use this:
```
:map <2-LeftMouse> <Nop>
:map! <2-LeftMouse> <Nop>
```

**Comment by ydzhou** [comment]
Good ot see there is a workaround. It works for my use case.
