### ISSUE TITLE
Error from WinClosed autocommand prevents buffer from being closed

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#10097]
### Steps to reproduce

1. Run `vim --clean`
2. Source the following file:
```vim
vnew
autocmd WinClosed * throw 'foo'
try
  close
catch /.*/
endtry
```
3. `:ls` lists two active buffers

### Expected behaviour

`:ls` lists one active buffer

### Version of Vim

8.2.4651

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

**Comment by chrisbra** [comment]
I am not sure I understand. Doesn't that prevent a possible data loss?

**Comment by zeertzjq** [comment]
Maybe, but the information shown by `:ls` is confusing.

**Comment by zeertzjq** [comment]
Yes. That buffer's `b_nwindows` flags is not decremented.
