### ISSUE TITLE
User1 highlighting seems broken

### ISSUE THREAD

**Issue by andmis** [vim/vim#10106]
### Steps to reproduce

Load `vim --clean` and run these commands:

```
set termguicolors
vsplit
let &statusline = 'hello %1*world%0*'
" Immediately, 'world' loses its highlighting, even though there is no User1 highlight group.
hi User1 guifg=red
" Only the active window's 'world' gets a red FG -- but both should get a red FG!
hi User1 ctermfg=green
" !!! Now the non-active-window's 'world' gets a green foreground,
" but `termguicolors` is set, so `ctermfg` should do nothing!
```

### Expected behaviour

Listed in the steps to reproduce

### Version of Vim

8.2, latest on Homebrew as of today

### Environment

macOS 12
iTerm2
`TERM=xterm-256color`

**Comment by brammool** [comment]
With the current Vim version I cannot reproduce it.  This is with an xterm, but that probably doesn't matter.

**Comment by andmis** [comment]
It looks like this may be related to the terminal. It reproduces for me over an SSH connection to an Ubuntu machine. Neovim also has the same behavior. But I'm having trouble reproducing it from Terminal.app.
