### ISSUE TITLE
vim9script: "import autoload" relative gets wrong file

### ISSUE THREAD

**Issue by errael** [vim/vim#10114]
### Steps to reproduce
With the p1 and p2 plugins installed, `Init1` is in p1.
```
gvim
:Init1
```
give the following error. Note that vim reports it is processing stuff from p2, but p1 should be self contained since only relative imports are used. Started with `import autoload` in the  import statements, changed to just `import`; still fails.
```
Error detected while processing /home/err/bugs/vim/plugin-autoload-relative.d/p2/autoload/splice.vim
[9]../home/err/bugs/vim/plugin-autoload-relative.d/p2/autoload/splicelib/util/log.vim:
line    5:
E1073: Name already defined: splicelib#util#log#Log
Error detected while processing function splice#Boot[2]..<SNR>28_Log:
line    1:
E118: Too many arguments for function: splicelib#util#log#Log
```
This should give the relevant information, I'll attach the files
```
err@harmony:~/.vim/pack/random-packages/start
$ srcgrep p1/ p2/ command
p1/plugin/startup_co.vim:command! -nargs=0 Init1 call splice.Boot()
p2/plugin/startup_co.vim:command! -nargs=0 Init2 call splice.Boot()

err@harmony:~/.vim/pack/random-packages/start
$ srcgrep p1/ p2/ import
p1/plugin/startup_co.vim:import autoload '../autoload/splice.vim'
p1/autoload/splice.vim:import autoload './splicelib/util/log.vim'
p2/plugin/startup_co.vim:import autoload '../autoload/splice.vim'
p2/autoload/splice.vim:import autoload './splicelib/util/log.vim'
```

### Expected behaviour

No error.

Remove p2 and no error is generated

### Version of Vim

8.2.4701

### Environment

ubuntu, gvim-gtk3

**Comment by errael** [comment]
[import-autoload-issue.zip](https://github.com/vim/vim/files/8447328/import-autoload-issue.zip)

**Comment by errael** [comment]
Enter the command `Init2` and that get trailing characters. `rm p1` then `Init2` works ok.

**Comment by lacygoill** [comment]
I was only able to reproduce the first error.  Here is an MRE:
```vim
vim9script
var dir = '/tmp/.vim'
dir->delete('rf')
&packpath = dir
dir ..= '/pack/mine/opt'
for n in [1, 2]
    (dir .. '/p' .. n .. '/plugin/')->mkdir('p')
    var lines =<< trim END
        vim9script
        import '../autoload/script.vim'
    END
    lines->writefile(dir .. '/p' .. n .. '/plugin/script.vim')
    (dir .. '/p' .. n .. '/autoload/')->mkdir('p')
    lines =<< trim END
        vim9script
        export def Func()
        enddef
    END
    lines->writefile(dir .. '/p' .. n .. '/autoload/script.vim')
endfor
packadd p1
packadd p2
```
    E1073: Name already defined: script#Func

However, I don't think it's a bug.

---

> Note that vim reports it is processing stuff from p2, but p1 should be self contained since only relative imports are used.

When an autoload function is installed, it's given a name in the global namespace, using the `path#to#script` syntax.  That's the root cause for the error.

Here is what happens when the first plugin is sourced:

   - `p1/plugin/startup_co.vim` is sourced
   - `import  '../autoload/splice.vim'` is executed
   - `p1/autoload/splice.vim` is sourced
   - `import './splicelib/util/log.vim'` is executed
   - `p1/autoload/splicelib/util/log.vim` is sourced
   - the `Log()` function is exported, and given a name in the global namespace: `splicelib#util#log#Log()`

So far so good.

Next, the second plugin is processed with the same steps.  But the last one gives an error, because the public name is already taken.

> Started with import autoload in the import statements, changed to just import; still fails.

The `autoload` argument makes Vim postpone the sourcing of the script until one of its functions is called.  But it doesn't change the fact that the autoload function gets a name in the global namespace.

If you want your function to be private, it needs to be under an `import/` directory.
If you want your function to be lazy-loaded, it needs to be under an `autoload/` directory.
If you want your function to be private and lazy-loaded, you need to wait for this todo item to be fixed:

   > - Implement "import lazy" - like autoload but with a relative or absolute
   >   path. #9595

Relevant issue: https://github.com/vim/vim/issues/9595

**Comment by lacygoill** [comment]
I forgot: the recent ability to pass relative paths to `import autoload` is useful to decrease Vim's startup time (because there is no need to look for the right directory in the runtimepath), and to prevent an earlier script in the runtimepath with the same relative path to shadow the one you're really looking for.  Those are significant advantages, but unfortunately they still do not turn an autoload function into a private one.  I don't think this can easily be changed; an autoload function is ultimately public no matter what (regardless of the type of script: legacy vs Vim9).

But again, [`import lazy`](https://github.com/vim/vim/blob/ac72c21da696cf6c31630a9e5ff4c0d3e2049c11/runtime/doc/todo.txt#L70-L71) should provide this feature.

Also, ignore the title of the issue #9595; it's misleading.  `import autoload` does currently accept a relative path.  But it doesn't help for the goal discussed in the report.  `import lazy` will.

**Comment by errael** [comment]
When the discussion went by, I probably remembered mention of name collision and erroneously thought that relative imports solved that problem. I guess this can be closed. In the closing message, saying Duplicate of #xxxx is a good way to do it?

I recall from the conversation that the performance issue can be a big win. But

> to prevent an earlier script in the runtimepath with the same relative path to shadow the one you're really looking for

might be useful, but seems of limited advantage considering that the file might be in a different plugin and so easily run into this problem.

**Comment by brammool** [comment]
You can use "import autoload" with a relative path to find it quickly.  But having "autoload" in the path of the script still has a special meaning, causing the path#file#item names to be used for exported items.  This is so that the same script can both be found in 'runtimepath' directories and also loaded directly by scripts that know where it is.
If you only want to use the items from scripts that know what file to source, then make sure not to use an "autoload" directory in the path.

I know this is a bit tricky, but I can't think of a better way right now.  Perhaps adding some hints in the help would avoid mistakes.

**Comment by errael** [comment]
So I can have, under `~/.vim/pack/stuff/start/myplug/`, `plugin`, `private`. And load everything relative from, `.../private/...`, with a little finesse to avoid everything loaded at vim startup. To only have them loaded when plugin is going to run, seems like it requires conditionally doing a primary import conditionally and from a :def. But
```
E1094: Import can only be used in a script 
```
precludes that. 

This isn't a production issue. I only ran into the problem because, I was tracking down a strange problem, and wanted to install two versions of the same plugin. Winnowing the test_version to get a small failing case.

**Comment by errael** [comment]
Out of curiosity and to clarify my understanding. When `import autolaod 'xxx.vim' is encounterd, is the file `xxx.vim` scanned looking for `export` lines and building a global dict of exported stuff? Actually, I guess everything in all autoload directories are scanned?

**Comment by brammool** [comment]
> Out of curiosity and to clarify my understanding. When `import
> autolaod 'xxx.vim' is encounterd, is the file `xxx.vim` scanned
> looking for `export` lines and building a global dict of exported
> stuff? Actually, I guess everything in all autoload directories are
> scanned?

When an :import command is encountered the script file is found.  That
way we know the script ID.  This also avoids that a script loaded in
different ways will have two different script IDs.

This is also the reason why importing a script found in an "autoload"
directory in 'runtimepath' can be slow if there are many directories to
search.  Using a relative path only needs to convert it to an absolute
path and check for existence.

For "import autoload" the script is not actually sourced, whether an
item used for it actually exists will only be discovered at runtime.

-- 
Mushrooms always grow in damp places and so they look like umbrellas.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
> So I can have, under `~/.vim/pack/stuff/start/myplug/`, `plugin`,
> `private`. And load everything relative from, `.../private/...`, with
> a little finesse to avoid everything loaded at vim startup. To only
> have them loaded when plugin is going to run, seems like it requires
> conditionally doing a primary import conditionally and from a :def.
> But
> ```
> E1094: Import can only be used in a script 
> ```
> precludes that. 
> 
> This isn't a production issue. I only ran into the problem because, I
> was tracking down a strange problem, and wanted to install two
> versions of the same plugin. Winnowing the test_version to get a small
> failing case.
 
For such special cases that you don't want to always import a script
there is one trick you can use:

	vim9script

	if IWantToLoadIt
	  import autoload 'script.vim'
	else
	  import autoload 'dummy.vim' as script
	endif

	if IWantToLoadIt
	  script.DoSomething()
	endif

	def SomeFunc()
	  if IWantToLoadIt
	    script.DoSomething()
	  else
	    echo "not loaded"
	  endif
	enddef
	SomeFunc()

The "dummy.vim" script must exist, but it can be empty.

You can also use this mechanism to load one of multiple versions of a
script.

-- 
I am always surprised in the Linux world how quickly solutions can be
obtained.  (Imagine sending an email to Bill Gates, asking why Windows
crashed, and how to fix it...  and then getting an answer that fixed the
problem... <0>_<0> !)		              -- Mark Langdon

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by errael** [comment]
@lacygoill says about the error his script generates
> However, I don't think it's a bug.

@brammool , in your comment you say
> For "import autoload" the script is not actually sourced

But I modified @lacygoill 's script, so that 

- instead of /tmp/.vim, the stuff is in /tmp/simple_relative/.vim
- each of his generated scripts creates a timestamp when it runs in /tmp/simple_relative
- after sourcing the new script, run: HOME=/tmp/simplerelative and generate the error

observe
```
$ ls /tmp/simple_relative
autoload_p1  autoload_p2  plugin_p1
```
If it's true that "import autoload" does not run the autoload script, there should not be autoload_p?

```
var home = '/tmp/simple_relative'
var dir = home .. '/.vim'
dir->delete('rf')
&packpath = dir
#dir ..= '/pack/mine/opt'
dir ..= '/pack/mine/start'
for n in [1, 2]
    (dir .. '/p' .. n .. '/plugin/')->mkdir('p')
    var lines =<< trim END
        vim9script
        import '../autoload/script.vim'
        system('date > HOME/plugin_pN')
    END
    lines->map((_, v) => substitute(v, '\CHOME', home, ''))
    lines->map((_, v) => substitute(v, '\CN', n, ''))
    lines->writefile(dir .. '/p' .. n .. '/plugin/script.vim')
    (dir .. '/p' .. n .. '/autoload/')->mkdir('p')
    lines =<< trim END
        vim9script
        system('date > HOME/autoload_pN')
        export def Func()
        enddef
    END
    lines->map((_, v) => substitute(v, '\CHOME', home, ''))
    lines->map((_, v) => substitute(v, '\CN', n, ''))
    lines->writefile(dir .. '/p' .. n .. '/autoload/script.vim')
endfor
#packadd p1
#packadd p2
```

**Comment by lacygoill** [comment]
> If it's true that "import autoload" does not run the autoload script, there should not be autoload_p?

`autoload_p` is created because the optional `autoload` argument was not passed to the `:import` command:

    import '../autoload/script.vim'
          ^
          ✘

    import autoload '../autoload/script.vim'
           ^------^
              ✔

`import` is not lazy.  It imports right away, regardless of the path it's given.  Even if this path contains an `/autoload/` component.

Here is the fixed version of the script:
```vim
vim9script
var home = '/tmp/simple_relative'
home->delete('rf')
var dir = home .. '/.vim'
&packpath = dir
dir ..= '/pack/mine/start'
for n in [1, 2]
    (dir .. '/p' .. n .. '/plugin/')->mkdir('p')
    var lines =<< trim END
        vim9script
        import autoload '../autoload/script.vim'
        system('date > HOME/plugin_pN')
    END
    lines->map((_, v) => substitute(v, '\CHOME', home, ''))
    lines->map((_, v) => substitute(v, '\CN', n, ''))
    lines->writefile(dir .. '/p' .. n .. '/plugin/script.vim')
    (dir .. '/p' .. n .. '/autoload/')->mkdir('p')
    lines =<< trim END
        vim9script
        system('date > HOME/autoload_pN')
        export def Func()
        enddef
    END
    lines->map((_, v) => substitute(v, '\CHOME', home, ''))
    lines->map((_, v) => substitute(v, '\CN', n, ''))
    lines->writefile(dir .. '/p' .. n .. '/autoload/script.vim')
endfor
autocmd VimEnter * echo system('ls ' .. home)
```

**Comment by errael** [comment]
Doh! Assumptions... I was tricked by the title of this issue. Thanks.

**Comment by brammool** [comment]
>    > If it's true that "import autoload" does not run the autoload script, there should not be autoload_p?
> 
> `autoload_p` is created because the optional `autoload` argument was not passed to the `:import` command:
> 
>     import '../autoload/script.vim'
>           ^
>           ✘
> 
>     import autoload '../autoload/script.vim'
>            ^------^
>               ✔
> 
> `import` is not lazy.  It imports right away, regardless of the path it's given.  Even if this path contains an `/autoload/` component.
> 
> Here is the fixed version of the script:
> ```vim
> vim9script
> var home = '/tmp/simple_relative'
> home->delete('rf')
> var dir = home .. '/.vim'
> &packpath = dir
> dir ..= '/pack/mine/start'
> for n in [1, 2]
>     (dir .. '/p' .. n .. '/plugin/')->mkdir('p')
>     var lines =<< trim END
>         vim9script
>         import autoload '../autoload/script.vim'
>         system('date > HOME/plugin_pN')
>     END
>     lines->map((_, v) => substitute(v, '\CHOME', home, ''))
>     lines->map((_, v) => substitute(v, '\CN', n, ''))
>     lines->writefile(dir .. '/p' .. n .. '/plugin/script.vim')
>     (dir .. '/p' .. n .. '/autoload/')->mkdir('p')
>     lines =<< trim END
>         vim9script
>         system('date > HOME/autoload_pN')
>         export def Func()
>         enddef
>     END
>     lines->map((_, v) => substitute(v, '\CHOME', home, ''))
>     lines->map((_, v) => substitute(v, '\CN', n, ''))
>     lines->writefile(dir .. '/p' .. n .. '/autoload/script.vim')
> endfor
> autocmd VimEnter * echo system('ls ' .. home)
> ```

This example still has the problem that you have two
"/autoload/script.vim" files.  Items in both will use the name
"script#item", thus there are likely name clashes.  Every script under
"autoload" should have a different name, since relying on finding the
right one is not a good idea.

-- 
To keep milk from turning sour: Keep it in the cow.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by errael** [comment]
> Every script under "autoload" should have a different name

That's among all the plugins in your system? Wow.

Anyway, DUPLICATE of #9595. 

(someone, @Bakudankun, nice if title contains `import lazy`)

**Comment by errael** [comment]
DUPLICATE of #9595

**Comment by brammool** [comment]
> > Every script under "autoload" should have a different name
> 
> That's among all the plugins in your system? Wow.

Yes, that is why using :import with a relative path is a nice solution.

If using the autoload directory anyway, either use a longer name or use
a directory, like we have "dist" for distributed files.  Using the name
of the plugin for the directory in autoload should work.

-- 
SOLDIER: What?  Ridden on a horse?
ARTHUR:  Yes!
SOLDIER: You're using coconuts!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by errael** [comment]
> Perhaps adding some hints in the help would avoid mistakes.

> Using the name of the plugin for the directory in autoload should work

I think I get it now. I can think of it like this: all `autoload` directories from all plugins can be looked at like a single /home directory, and each plugin should have a unique directory name under autoload. Generally there should only be one small file in the plugin directory and lets most of the work be done by autoload files.

With this setup, if all autoload files are under a plugin unique directory and they refer to each other by relative paths, then a second copy of the plugin could be installed into its own unique directory under autotlaod and only the file in the `plugin` directory has to be given a new name and modified to refer to the new/second autoload directory.

Generally it is not advised to put a file directly into the autoload directory; all files should go into the uniquely named plugin directory.

**Advanced consideration**
If two installations of a plugin are expected to be simultaneously active in the same vim session, care must be taken with the command names; the command name could incorporate the unique plugin name. But if only one of the plugins is active at a time, then there is no problem if command names overlap.
