### ISSUE TITLE
`@@@` can go out of the window with `display=lastline`

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#10130]
### Steps to reproduce

1. Run `vim --clean`
2. `:set display=lastline`
3. Type long line in a buffer
4. `:vsplit`
5. Resize either split to 1-wide

If the left split is resized to 1-wide:
![Screenshot_20220409_182520](https://user-images.githubusercontent.com/35768171/162568020-33cf7de1-5de6-4236-9b49-8a7aa0397d5c.png)

If the right split is resized to 1-wide:
![Screenshot_20220409_182535](https://user-images.githubusercontent.com/35768171/162568028-db0db309-bf8d-46c9-b537-089118eca913.png)

### Expected behaviour

`@@@` should not go out of the window

### Version of Vim

8.2.4651

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

**Comment by zeertzjq** [comment]
Issue may be easier to reproduce with `display=lastline,truncate`

**Comment by brammool** [comment]
After some attempts I only managed to see the first issue.  I could not make the second one show up.
Can you write a (failing) test that shows the problem?

**Comment by zeertzjq** [comment]
Maybe the second issue is only reproducible in certain terminals. I cannot reproduce it using GVim. The first issue is reproducible using GVim.

**Comment by zeertzjq** [comment]
A failing test for the first issue:
```vim
20new
set display=lastline,truncate
vsplit
call setline(1, ['aaa', repeat('a', 100)])
vert resize 1
redraw!
call assert_equal('|', screenstring(20, 2))

set display&
%bwipe!
```

**Comment by brammool** [comment]
OK, I see that it matters where the cursor is, and the first line needs to be short.
