### ISSUE TITLE
vim inserts comment on new line after specific code pattern

### ISSUE THREAD

**Issue by dineshKumar777** [vim/vim#10151]
### Steps to reproduce

1. launch vim
2. set filetype=typescript or javascript
3. type this code => await page.goto('https://google.co.in/');
4. click enter for new line
5. new line inserted with doubleslash(comment) as prefix.

### Expected behaviour

new blank line should be inserted

### Version of Vim

8.2.4732

### Environment

OS: Windows10, GVim

https://user-images.githubusercontent.com/21097695/162745883-331d4b55-2ce3-4326-ba1e-b75f8d8f81a9.mp4

Note:
This is working as expected in following vim version.
Public@DESKTOP MINGW64 ~
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov 22 2021 19:31:05)
Included patches: 1-3582

**Comment by lacygoill** [comment]
I reported the same issue for [an url inside a double-quoted string](https://github.com/vim/vim/issues/9426#issuecomment-1002680232), but not for an url inside a single-quoted one.

The patch [8.2.3938](https://github.com/vim/vim/releases/tag/v8.2.3938) might give a clue as to how to fix the issue.

**Comment by brammool** [comment]
Looking at the code, it is actually not intentional that this functionality is active when 'indentexpr' is set.  That's easy to fix.
