### ISSUE TITLE
Spanish translations are outdated

### ISSUE THREAD

**Issue by brammool** [vim/vim#10163]
### Steps to reproduce

Start Vim with language set to Spanish.
Observe that many messages are in English

### Expected behaviour

Most messages are translated to Spanish.

### Version of Vim

8.2

### Environment

Spanish

**Comment by brammool** [comment]
@elric @palopezv

**Comment by palopezv** [comment]
Hi @brammool I'm afraid we threw the towel a long time ago. In fact, I moved the trnaslation project to github from sourceforge and archived the repositories some time ago.

I'll be more than happy to transfer ownership of the project to anyone who is willing to take over and upddate the translation to current vim.

My apologies for the delayed answer.

**Comment by victorhck** [comment]
What would be the best way to help in translation?

**Comment by brammool** [comment]
> What would be the best way to help in translation?

The instructions are in src/po/README.txt
On github: https://github.com/vim/vim/blob/master/src/po/README.txt

-- 
hundred-and-one symptoms of being an internet addict:
66. You create a homepage with the impression to cure the afflicted...but
    your hidden agenda is to receive more e-mail.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by palopezv** [comment]
@victorhck Basically yes. Let me unarchive the repos first. Will do in a minute.

**Comment by palopezv** [comment]
@victorhck @brammool One thing of note. I'd rather have all pull requests go to a new directory matching vim's present version. I'll duplicate the directory sometime today.

**Comment by victorhck** [comment]
I have create a new branch in my local repo to updat tutor. it's fine?
I'm updating the tutor.es.utf8. How I create tutor.es from that file with make?

Excuse me if questions sounds a bit dumb, since I'm not a developer I want to do the things in the right way! :)

**Comment by brammool** [comment]
> I would like to start updating tutor.es
> Not sure what would be the workflow:
> * clone repo
> * create branch
> * update tutor.es.utf8
> * create tutor.es from tutor.es.utf8 with make 

The other way around: update tutor.es and generate tutor.es.utf-8
with "make".  You can turn this around, but you need to change the
Makefile then.  Make sure you backup your files before running "make"
to avoid risking you loose your work.

I'm not sure when the current version was translated, you might want to
find out and diff the English tutor to find out what changed since then.

-- 
hundred-and-one symptoms of being an internet addict:
75. You start wondering whether you could actually upgrade your brain
    with a Pentium Pro microprocessor 80.  The upgrade works just fine.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by victorhck** [comment]
I did it.
Changed the make file to generate the tutor.es file from tutor.es.utf-8 file
But after make file, the tutor.es file shows weird symbols...

![utf8](https://user-images.githubusercontent.com/1514206/165599248-6c6ebdf8-7dd8-4b37-bad0-dd97369ba86c.png)

**Comment by brammool** [comment]
> I did it.
> Changed the make file to generate the tutor.es file from tutor.es.utf-8 file
> But after make file, the tutor.es file shows weird symbols...
> 
> ![utf8](https://user-images.githubusercontent.com/1514206/165599248-6c6ebdf8-7dd8-4b37-bad0-dd97369ba86c.png)

Looks like the iconv command in Makefile isn't right.
It should work the same as using ":w ++enc=latin1 tutor.es".

-- 
hundred-and-one symptoms of being an internet addict:
78. You find yourself dialing IP numbers on the phone.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by victorhck** [comment]
> It should work the same as using ":w ++enc=latin1 tutor.es"

did the magic! adding ! to overwrite the file!! :)

**Comment by victorhck** [comment]
Updated the tutor to version 1.7 ( PR #10329 )
What would be the next thing to update? I would like to help...
Greetings.

**Comment by victorhck** [comment]
I would like to contribute updating the spanish translation.
I configure and run make in vim/src/ directory and get this errors, so I can't continue the process to get new strings and start the translation:

![Screenshot_20220429_211856](https://user-images.githubusercontent.com/1514206/166724391-31ccc204-4f9e-4e42-947b-776f6952243e.png)

I miss something? Or something to install?

Greetings.

**Comment by brammool** [comment]
Not sure, maybe "make reconfig" helps?

**Comment by chrisbra** [comment]
I am not sure. Apparently you are trying to compile with `libsodium` but the libsodium dll is not found. How did you do this? It should only be set, when explicitly set via the commandline (e.g. SODIUM=...).

In any case, if you just want to start translating, it should be possible to copy an existing vim/or gvim into the checkout repository below the `src/` directory. Then the Makefile for the translations should be happy.

**Comment by victorhck** [comment]
> Not sure, maybe "make reconfig" helps?

Nope, didn't work. Same issues...

> How did you do this?

I'm trying to update the spanish po files translations in my GNU/Linux openSUSE Tumbleweed, just following the README file. I jus run ./configure in my local cloned copy, and after that trying to run `make es` to update the es.po file and start updating the translation. I'm not a developer or such, so maybe I made some mistakes int easiest tasks...

>In any case, if you just want to start translating, it should be possible to copy an existing vim/or gvim into the checkout repository below the src/ directory. Then the Makefile for the translations should be happy.

Not sure how to do that... sorry, but didn't understood what to do...
So sorry for (maybe) so many dumb questions...
Greetings and thanks for your answers...

**Comment by chrisbra** [comment]
but the screenshot was on windows? Try running `./configure --disable-sodium`

> Not sure how to do that... sorry, but didn't understood what to do...
> So sorry for (maybe) so many dumb questions...
> Greetings and thanks for your answers...

Say you  have checked out the vim repo in `~/vim/src`, just do `cp /usr/bin/vim ~/vim/src`

**Comment by victorhck** [comment]
> but the screenshot was on windows? Try running ./configure --disable-sodium

No, it's openSUSE Tumbleweed + Plasma and Konsole terminal. And after running the command I get:

``` 
./configure --disable-sodium                                                                                 
configure: WARNING: unrecognized options: --disable-sodium
configure: loading cache auto/config.cache
configure: error: `CC' was set to `' in the previous run
configure: error: `CFLAGS' was set to `' in the previous run
configure: error: `LDFLAGS' was set to `' in the previous run
configure: error: `CPPFLAGS' was set to `' in the previous run
configure: error: in `/home/victorhck/Git/vim/src':
configure: error: changes in the environment can compromise the build
configure: error: run `make distclean' and/or `rm auto/config.cache' and start over

```

> Say you have checked out the vim repo in ~/vim/src, just do cp /usr/bin/vim ~/vim/src

And that did the trick! :) So now I have to start update es.po

**Comment by chrisbra** [comment]
cool. Just short comment for this one:

```
./configure --disable-sodium                                                                                 
configure: WARNING: unrecognized options: --disable-sodium
configure: loading cache auto/config.cache
configure: error: `CC' was set to `' in the previous run
configure: error: `CFLAGS' was set to `' in the previous run
configure: error: `LDFLAGS' was set to `' in the previous run
configure: error: `CPPFLAGS' was set to `' in the previous run
configure: error: in `/home/victorhck/Git/vim/src':
configure: error: changes in the environment can compromise the build
configure: error: run `make distclean' and/or `rm auto/config.cache' and start over
```

just rm `vim/src/auto/config.cache` where vim is the top level checked out worktree. 

And if you can reproduce the following error:  
![image](https://user-images.githubusercontent.com/244927/166979906-683c5c69-63ab-46ec-9326-c38349e502df.png)

Please create a new issue for that one. That shouldn't happen. looks like configure found a wrong libsodium.

Thanks,
Chris

**Comment by victorhck** [comment]
just for the record, I'm working on spanish translation and will provide a PR from my personal repo when finished.

**Comment by brammool** [comment]
> just for the record, I'm working on spanish translation and will
> provide a PR from my personal repo when finished.

Great, looking forward to that.

Note that I just updated runtime files, which includes capitalization of
the English text for error messages.

-- 
hundred-and-one symptoms of being an internet addict:
159. You get excited whenever discussing your hard drive.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by victorhck** [comment]
provided a PR #10413  with spanish translation

**Comment by brammool** [comment]
Closing this in favor of #10413

**Comment by brammool** [comment]
> > Not sure, maybe "make reconfig" helps?
> 
> Nope, didn't work. Same issues...
> 
> > How did you do this?
> 
> I'm trying to update the spanish po files translations in my GNU/Linux
> openSUSE Tumbleweed, just following the README file. I jus run
> ./configure in my local cloned copy, and after that trying to run
> `make es` to update the es.po file and start updating the translation.
> I'm not a developer or such, so maybe I made some mistakes int easiest
> tasks...

Instead of running "./configure", just run "make" in the src directory.
Check if that succeeds.

If you only run "configure" then Vim has not been build yet.

-- 
A meeting is an event at which the minutes are kept and the hours are lost.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
