### ISSUE TITLE
Russian translations are outdated

### ISSUE THREAD

**Issue by brammool** [vim/vim#10170]
### Steps to reproduce

Start Vim with language set to Russian.
Observe that many messages are in English

### Expected behaviour

Most messages are translated to Russian

### Version of Vim

8.2

### Environment

Russian

**Comment by brammool** [comment]
@alyoshin

**Comment by matveyt** [comment]
If no one else is willing to work on the translation then I'm ready to do this. I think I'll need about a week or so.

**Comment by RestorerZ** [comment]
Брам, я вижу, что уже есть предложение, но если интересно
Bram, I see that there is already an offer, but if you are interested
https://sourceforge.net/projects/ruvim2/
https://github.com/RestorerZ/RuVim

**Comment by brammool** [comment]
I have included the PR to update the messages.  Let's close this now.
Of course, if there are more translations or corrections, that is ongoing work.
