### ISSUE TITLE
vim9script: E723: Missing end of Dictionary '}': [end of lines]

### ISSUE THREAD

**Issue by bfrg** [vim/vim#10203]
### Steps to reproduce

```vim
vim9script

const Func = () => {
    return {
        one: 1,
        two: 2
    }
}

echo Func()
```

Result:
```
Error detected while compiling /tmp/test.vim[7]..function <lambda>125:
line    3:
E723: Missing end of Dictionary '}': [end of lines]
```

### Expected behaviour

No errors

### Version of Vim

8.2.4754

### Environment

Linux

**Comment by bfrg** [comment]
This one works:
```vim
const Func = () => {
    return {
        one: 1,
        two: 2 }
}
```

**Comment by lacygoill** [comment]
This looks similar to https://github.com/vim/vim/issues/9352

   > A simple workaround is to put the terminaing "}" of the dictionary at
   > the end of the previous line.  In my opinion that is totally acceptable.
   >
   > Parsing the lines inside the block would require rewriting the whole
   > command parsing code, that is infeasible.

[source](https://github.com/vim/vim/issues/9352#issuecomment-994997867)

**Comment by bfrg** [comment]
Thank you. Indeed this looks very similar, so I close this one.

**Comment by brammool** [comment]
> This looks similar to https://github.com/vim/vim/issues/9352
> 
>    > A simple workaround is to put the terminaing "}" of the dictionary at
>    > the end of the previous line.  In my opinion that is totally acceptable.
>    >
>    > Parsing the lines inside the block would require rewriting the whole
>    > command parsing code, that is infeasible.
> 
> [source](https://github.com/vim/vim/issues/9352#issuecomment-994997867)

This is still true.  This specific situation might be recognized, as a
nested block or inline function is also found.  But in many other
situations this will fail and only cause more confusion.

As is stated in the help, just avoid putting the closing "}" of the
dictionary at the start of the line.

-- 
An operatingsystem is just a name you give to the rest of bloating
idiosyncratic machine-based-features you left out of your editor.
			(author unknown)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
