### ISSUE TITLE
Preview for the substitute command

### ISSUE THREAD

**Issue by jclsn** [vim/vim#10205]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
When using the substitute command, it sometimes takes a few shots to get it right, because you only see if it worked after you hit enter.

**Describe the solution you'd like**
It would be nice to see a preview of the replacement pattern in real time for all occurrences.

**Comment by brammool** [comment]
Have you enabled 'incsearch' ?  If that's not what you want, please explain what you mean with "search and replace function".

**Comment by jclsn** [comment]
Well, kind of, but I would like it to be extended to the following functionality:

1. Provide an option to highlight all occurrences of the search. Currently it just highlights the first one. This might be a matter of taste.
2. More importantly: When using search and replace, it would be great to preview the replacement. So after you type ```:%s/someword/`` all occurences should instantly show a preview. This would immensely help with strings that contain a lot of escaped characters.

**Comment by vim-ml** [comment]
On 2022-04-16, jclsn wrote:
> Well, kind of, but I would like it to be extended to the following
> functionality:
> 
>  1. Provide an option to highlight all occurrences of the search. Currently it
>     just highlights the first one. This might be a matter of taste.

    :set hlsearch

See

    :help 'hlsearch'

>  2. More importantly: When using search and replace, it would be great to
>     preview the replacement. So after you type ```:%s/someword/`` all
>     occurences should instantly show a preview. This would immensely help with
>     strings that contain a lot of escaped characters.

Since you can easily undo the effects of a :substitute command,
I don't see much advantage to having a preview.  If you don't like
the results, undo them and try again.  You can also try it on one
line at a time instead of the whole file while you're experimenting
with it.  Another approach to finding out if the command is what you
want is to use the :DiffOrig command,

    :help :DiffOrig

to see a side-by-side comparison of the before and after states of
your file.

HTH,
Gary

**Comment by lacygoill** [comment]
FWIW [traces.vim](https://github.com/markonm/traces.vim) provides this feature.

**Comment by jclsn** [comment]
@lacygoill: Noice! Thanks! I guess I can close this now
