### ISSUE TITLE
Excessive dedent on split ELSE IF in Fortran

### ISSUE THREAD

**Issue by naught101** [vim/vim#1020]
Indenting using `gg=G` on this program works:

``` fortran
      program blah
         IF (logi == ical .and. &
            expre == ssion) THEN
            print *, 'blah'
         ELSE IF (logical == expression) THEN
            print *, 'blah'
         ELSE IF (logi == ical .and. expre == ssion) THEN
            print *, 'blah'
         ELSE
            print *, 'blah'
         END IF  
      endprogram
```

but if the last logical expression is split into two lines, then the indenter chokes and dedents the second part of the line and all of the following parts of the code by one level:

``` fortran
      program blah
         IF (logi == ical .and. &
            expre == ssion) THEN
            print *, 'blah'
         ELSE IF (logical == expression) THEN
            print *, 'blah'
         ELSE IF (logi == ical .and. &
         expre == ssion) THEN
         print *, 'blah'
      ELSE
         print *, 'blah'
      END IF  
   endprogram
```

**Comment by vim-ml** [comment]
On Monday, August 29, 2016 at 2:45:54 AM UTC-3, naught101 wrote:

> Indenting using gg=G on this program works:
> [snip] 
> but if the last logical expression is split into two lines, then the indenter chokes and dedents the second part of the line and all of the following parts of the code by one level:

This has now been fixed. I'll send the updates to Bram. If you want to give the revised indent file a whirl immediately, please email me (Ajit Thakkar) directly. My email address can be found in the distributed indent file.

Ajit

**Comment by chrisbra** [comment]
closing then.
