### ISSUE TITLE
Multiple input is broken when `set cmdheight > 1` and redraw

### ISSUE THREAD

**Issue by Shougo** [vim/vim#10210]
### Steps to reproduce

```vim
set cmdheight=2
autocmd CmdlineChanged * redraw
```

`vim -Nu test_vimrc`

Please input below texts.

```
for i in range(4)
  echo 'hello'
endfor
```

My result is...

![スクリーンショット_2022-04-14_20-11-08](https://user-images.githubusercontent.com/41495/163700068-f8f452c0-99da-4ab2-a595-6f29e22ce7e5.png)

The redraw seems broken.

### Expected behaviour

The input text should be redrawed like when `set cmdheight=1`

### Version of Vim

8.2.4756

### Environment

OS: Manjaro Linux
Terminal Alacritty
TERM: alacritty

**Comment by brammool** [comment]
The redraw command redraws the text in the windows, not the command line.
You should not use :redraw while editing the command line, because it will clear any messages.
I don't see why you have that autocmmand, it serves no purpose by itself.

**Comment by Shougo** [comment]
> The redraw command redraws the text in the windows, not the command line.
> You should not use :redraw while editing the command line, because it will clear any messages.

> I don't see why you have that autocmmand, it serves no purpose by itself.

OK.   I should explain why the feature is needed.

I have developed pum.vim plugin.
https://github.com/Shougo/pum.vim

The plugin supports the original command line popup menu by floting window or popup window.
But in command line, `:redraw` is needed to update popup window feature.
I don't know the replacement feature.
I use both `CmdlineChanged` autocmd and `:redraw` for it.

But `:redraw` seems broken when `set cmdheight > 1`.  So I have reported it.

**Comment by brammool** [comment]
Shougo wrote:

> > The redraw command redraws the text in the windows, not the command
> > line.
> > You should not use :redraw while editing the command line, because
> > it will clear any messages.
> 
> > I don't see why you have that autocmmand, it serves no purpose by itself.
> 
> OK.   I should explain why the feature is needed.
> 
> I have developed pum.vim plugin.
> https://github.com/Shougo/pum.vim
> 
> The plugin supports the original command line popup menu by floting window or popup window.
> But in command line, `:redraw` is needed to update popup window feature.
> I don't know the replacement feature.
> I use both `CmdlineChanged` autocmd and `:redraw` for it.
> 
> But `:redraw` seems broken when `set cmdheight > 1`.  So I have reported it.

I see.  Well, we can redraw the command line with :redraw.  That's a
small change.  However, the first line will be gone, since only the
second line is being edited.

Perhaps we should have a redraw command to only update popup windows.
However, I would first want to know when this is needed, when are they
not updated automatically?

-- 
How To Keep A Healthy Level Of Insanity:
4. Put your garbage can on your desk and label it "in".

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Shougo** [comment]
> Perhaps we should have a redraw command to only update popup windows.
> However, I would first want to know when this is needed, when are they
> not updated automatically?

Thank you.  I want to use the feature if possible.
Popup window is updated in other modes, but it is not updated automatically when command line mode.
If I execute `:redraw` in command line mode, it is updated.

**Comment by brammool** [comment]
> > Perhaps we should have a redraw command to only update popup windows.
> > However, I would first want to know when this is needed, when are they
> > not updated automatically?
> 
> Thank you.  I want to use the feature if possible.
> Popup window is updated in other modes, but it is not updated
> automatically when command line mode.
> If I execute `:redraw` in command line mode, it is updated.

The main problem with command line mode is that if output caused the
screen to scroll up, redrawing popups in their old positon would cause a
big mess.

If you use a popup for something related to the command line (completion
I guess), then just redrawing that one is probably what you want.  This
also has the advantage that you don't need to know about any other
plugin that might have a popup displayed.

I'll add this to the todo list, but don't expect it soon...

-- 
'Well, here's something to occupy you and keep your mind off things.'
'It won't work, I have an exceptionally large mind.'
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
Looking at the todo item for this:  We could add a ":redrawpopups" command that redraws all the popup windows.
However, I wonder in exactly what situation it would be needed.  And whether it is OK they might be drawn in the wrong
place when the command line has scrolled up.
Can you provide a script (as simple as possible, no plugins) that illustrates this?  Ideally in a way it could be used in a test.

**Comment by Shougo** [comment]
OK.

Please test the script.

```vim
autocmd CmdlineChanged * call s:redraw_popup()

let s:id = -1
function! s:redraw_popup()
  let winopts = {
        \ 'pos': 'topleft',
        \ 'line': &lines + 1,
        \ 'col': getcmdpos() + 1,
        \ 'wrap': 0,
        \ }
  let lines = [getcmdline()]

  if s:id > 0
    call popup_move(s:id, winopts)
    call popup_settext(s:id, lines)
  else
    let s:id = popup_create(lines, winopts)
  endif

  " :redraw is needed now
  "redraw
endfunction
```

**Comment by Shougo** [comment]
It prints the current command line in the popup window, but `:redraw` is needed now.
