### ISSUE TITLE
Window change in VISUAL overwrites `*` register

### ISSUE THREAD

**Issue by noscript** [vim/vim#10217]
### Steps to reproduce

1. Create script `~/win_change_bug.vim`:
```vim
set noshowmode cmdheight=5

function On_click()
  call win_gotoid(getmousepos().winid)
  execute "norm! \<LeftMouse>"
endfunction
noremap <LeftMouse> <Cmd>call On_click()<CR>

autocmd SafeState * echo '' | reg *
```
2. Run Vim and open two different text files in splits:
```sh
cd ~/vim.git/
vim -g --clean +'so ~/win_change_bug.vim' ./README.md ./README.txt -o
```
3. Select text in one window. At the bottom `*` register content will be show.
4. Click to another window.
5. `*` register content changes to something that came from another window.

### Expected behaviour

`*` register content does not change.

Demonstration:

https://user-images.githubusercontent.com/717109/163738237-966f16ba-6a54-46b3-8b71-c11fbee67e4b.mp4

### Version of Vim

8.2.4768

### Environment

OS: Debian 11
Terminal: GUI

**Comment by brammool** [comment]
Sergey Vlasov wrote:

> ### Steps to reproduce
> 
> 1. Create script `~/win_change_bug.vim`:
> ```vim
> set noshowmode cmdheight=5
> 
> function On_click()
>   call win_gotoid(getmousepos().winid)
>   execute "norm! \<LeftMouse>"
> endfunction
> noremap <LeftMouse> <Cmd>call On_click()<CR>
> 
> autocmd SafeState * echo '' | reg *
> ```
> 2. Run Vim and open two different text files in splits:
> ```sh
> cd ~/vim.git/
> vim -g --clean +'so ~/win_change_bug.vim' ./README.md ./README.txt -o
> ```
> 3. Select text in one window. At the bottom `*` register content will be show.
> 4. Click to another window.
> 5. `*` register content changes to something that came from another window.
> 
> ### Expected behaviour
> 
> `*` register content does not change.

I can reproduce it.  Visual mode is stopped only after switching to the
other window.  I'll make a patch to fix it.

I wrote a test, but it also passes without the fix.  Not sure why.
Perhaps someone can take some time to find out what I missed.


-- 
hundred-and-one symptoms of being an internet addict:
28. You have comandeered your teenager's phone line for the net and even his
    friends know not to call on his line anymore.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
