### ISSUE TITLE
minlines in gvimrc

### ISSUE THREAD

**Issue by 89z** [vim/vim#10221]
I notice when I work with larger Markdown files, the syntax highlighting is broken if I skip around the page. This seems to fix the issue:

~~~
syntax sync minlines=999
~~~

but if I put it into my `_gvimrc`, it doesn't do anything. Is it possible to save this setting?

**Comment by brammool** [comment]
> I notice when I work with larger Mardown files, the syntax
> highlighting is broken if I skip around the page. This seems to fix
> the issue:
> 
> ~~~
> syntax sync minlines=999
> ~~~
> 
> but if I put it into my `_gvimrc`, it doesnt do anything. Is it
> possible to save this setting?

Put this in your .vimrc:

	let g:markdown_minlines = 999


-- 
How To Keep A Healthy Level Of Insanity:
3. Every time someone asks you to do something, ask if they want fries
   with that.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
> syntax sync minlines=999
> but if I put it into my _gvimrc, it doesnt do anything. Is it possible to save this setting?

This should probably go to a filetype plugin, not into your global vimrc file. 

BTW: I think this should be documented at `:h ft-markdown-plugin`?

**Comment by 89z** [comment]
Thank you for the response. Is a general solution available? I suspect that other languages could have the same problem

**Comment by brammool** [comment]
No, every syntax is different and syncing may work different.  If there are no regions then no syncing is needed.
I'll add a remark in the help, apparently that was missing.
