### ISSUE TITLE
Visual block column, insert register 0 (a copied line)

### ISSUE THREAD

**Issue by duianto** [vim/vim#10225]
### Steps to reproduce

1. Start `gvim.exe`
2. Switch to insert state: `i`
3. Type:
```
abc
123
123
123
```
4. Switch to normal state: `Esc`
5. Move the cursor to the first line: `gg`
6. Copy the first line: `yy`
7. Move the cursor to the second line's second character (number) 2: `jl` (down once and right once)
8. Enter visual block mode: `Ctrl v`
9. Select the column of 2's by moving the cursor down twice: `jj`
10. Switch to insert state at the beginning of the block: `I` (Shift i)
11. Insert from register 0: `Ctrl r 0`

### Observed
```
abc
1abc
23
123
123
```
The copied line: abc
was inserted on the first line, without a leading newline.
Nothing happened on the second and third lines.

### Expected behaviour

The copied line should be inserted on every line with a selection.
With a leading new line.
```
abc
1
abc
3
1
abc
3
1
abc
3
```

### Notes

A leading new line is inserted when the insert state cursor is on the first column.
This is also observed without a selection.

#### First column

1. Copy the first line: abc
2. Move the cursor to the third line's first column
3. Switch to insert state: `i`
4. Insert register 0: `Ctrl r 0`

```
abc
123
abc
123
123
```

#### Second+ column

There is no leading new line when the insert state cursor is not on the first column.
1. Copy the first line: abc
2. Move the cursor to the third line's second column (on the number 2)
3. Switch to insert state: `i`
4. Insert register 0: `Ctrl r 0`

```
abc
123
1abc
23
123
```

### Version of Vim

8.2.4779

### Environment

Windows 10 21H2

**Comment by chrisbra** [comment]
Note, that depending on how you yank, the register may be in linewise, characterwise or block mode. To workaround this, you can use `setreg()` and set the register content correctly for the way to paste it. Or you may use @inkarkat's [unconditionalpaste](https://github.com/inkarkat/vim-UnconditionalPaste) plugin (there are probably other alternatives)

**Comment by chrisbra** [comment]
I am closing this, as working as expected.
