### ISSUE TITLE
Vim9: `feedkeys()` 'c' flag does not clear context saved by `<ScriptCmd>`

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#10228]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        nnoremap <F3> <ScriptCmd>eval 1+2<CR>
        feedkeys("\<F3>", 'cx')
    EOF
    )

An error is given:

    E1004: White space required before and after '+' at "+2"

**Expected behavior**

Not sure.  Here is what [`:help feedkeys()`](https://vimhelp.org/builtin.txt.html#feedkeys%28%29) says about the `c` flag:

   > 'c'     Remove any script context when executing, so that
   >         legacy script syntax applies, "s:var" does not work,
   >         etc.

This means that `eval 1+2` should have been processed in legacy context, where whitespace around binary operators is not enforced; thus, no error should have been given.

IOW, `<ScriptCmd>` overrides the `c` flag.  Is it working as intended?  If it is, maybe it should be documented.  As a suggestion, here is a patch:
```diff
diff --git a/runtime/doc/builtin.txt b/runtime/doc/builtin.txt
index 8695edd2d..edf084826 100644
--- a/runtime/doc/builtin.txt
+++ b/runtime/doc/builtin.txt
@@ -2417,7 +2417,8 @@ feedkeys({string} [, {mode}])				*feedkeys()*
 			all typeahead will be consumed by the last call.
 		'c'	Remove any script context when executing, so that
 			legacy script syntax applies, "s:var" does not work,
-			etc.
+			etc.  Does not clear a script context saved by
+			|<ScriptCmd>|.
 		'!'	When used with 'x' will not end Insert mode. Can be
 			used in a test when a timer is set to exit Insert mode
 			a little later.  Useful for testing CursorHoldI.
```
**Version of Vim**

8.2 Included patches: 1-4787

**Environment**

Operating system: Ubuntu 20.04.4 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: GNU bash, version 5.0.17

**Additional context**

If we replace `<ScriptCmd>` with `<Cmd>`, the `c` flag works as documented:
```vim
vim9script
nnoremap <F3> <Cmd>eval 1+2<CR>
feedkeys("\<F3>", 'cx')
```
    no error

**Comment by brammool** [comment]
> **Steps to reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(tee <<'EOF'
>         vim9script
>         nnoremap <F3> <ScriptCmd>eval 1+2<CR>
>         feedkeys("\<F3>", 'cx')
>     EOF
>     )
> 
> An error is given:
> 
>     E1004: White space required before and after '+' at "+2"
> 
> **Expected behavior**
> 
> Not sure.  Here is what [`:help feedkeys()`](https://vimhelp.org/builtin.txt.html#feedkeys%28%29) says about the `c` flag:
> 
>    > 'c'     Remove any script context when executing, so that
>    >         legacy script syntax applies, "s:var" does not work,
>    >         etc.
> 
> This means that `eval 1+2` should have been processed in legacy
> context, where whitespace around binary operators is not enforced;
> thus, no error should have been given.

The context is only removed for the moment the keys are inserted.  When
a context is set by the keys, it is still used.  I thought that would be
obvious, but I can add a remark about it.

> IOW, `<ScriptCmd>` overrides the `c` flag.  Is it working as intended?
> If it is, maybe it should be documented.  As a suggestion, here is a
> patch: ```diff
> diff --git a/runtime/doc/builtin.txt b/runtime/doc/builtin.txt
> index 8695edd2d..edf084826 100644
> --- a/runtime/doc/builtin.txt
> +++ b/runtime/doc/builtin.txt
> @@ -2417,7 +2417,8 @@ feedkeys({string} [, {mode}])				*feedkeys()*
>  			all typeahead will be consumed by the last call.
>  		'c'	Remove any script context when executing, so that
>  			legacy script syntax applies, "s:var" does not work,
> -			etc.
> +			etc.  Does not clear a script context saved by
> +			|<ScriptCmd>|.
>  		'!'	When used with 'x' will not end Insert mode. Can be
>  			used in a test when a timer is set to exit Insert mode
>  			a little later.  Useful for testing CursorHoldI.
> ```

It is not just <ScriptCmd>, any function call, source command, etc. can
also set the context.

-- 
hundred-and-one symptoms of being an internet addict:
32. You don't know what sex three of your closest friends are, because they
    have neutral nicknames and you never bothered to ask.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
