### ISSUE TITLE
Visual block column, paste a copied line

### ISSUE THREAD

**Issue by duianto** [vim/vim#10224]
### Steps to reproduce

1. Start `gvim.exe`
2. Switch to insert state: `i`
3. Type:
```
abc
123
123
123
```
4. Switch to normal state: `Esc`
5. Move the cursor to the first line: `gg`
6. Copy the first line: `yy`
7. Move the cursor to the second line's second character (number) 2: `jl` (down once and right once)
8. Enter visual block mode: `Ctrl v`
9. Select the column of 2's by moving the cursor down twice: `jj`
10. Paste: `p`

### Observed
```
abc
13
13
13
abc
```
The column of 2's was removed, and the copied line: abc
was pasted after the last line that had a selection.

### Expected behaviour

The copied line: `abc`
Should be pasted with a leading and ending new line, on every line with a visual block selection.
```
abc
1
abc
3
1
abc
3
1
abc
3
```

This behavior is observed when entering visual mode: `v`
on the second line's second character (number): 2
And pasting: `p`
```
abc
1
abc
3
123
123
```

### Version of Vim

8.2.4779

### Environment

Windows 10 21H2

**Comment by chrisbra** [comment]
I think [my comment](https://github.com/vim/vim/issues/10225#issuecomment-1102647870) from your other issue applies here as well.

**Comment by chrisbra** [comment]
Closing as working as expected. If you want to paste blockwise, make sure the register has the correct type attached to it.
