### ISSUE TITLE
WinScrolled not triggered when scroll the mouse wheel

### ISSUE THREAD

**Issue by wsdjeg** [vim/vim#10243]
### Steps to reproduce

1. run vim --clean
2. run `:autocmd WinScrolled * echo expand('<amatch>') localtime()`
3. scroll the mouse wheel

### Expected behaviour

Window ID of the window under mouse is printed.

### Version of Vim

vim 8.2.4732

### Environment

gvim + win 10

**Comment by LemonBoy** [comment]
Works for me, perhaps you're experiencing the same problem as in #10235 ?

**Comment by chrisbra** [comment]
this should have been fixed by [8.2.4803](https://github.com/vim/vim/releases/tag/v8.2.4803)

I guess this can be closed now
