### ISSUE TITLE
Cursorline behavior different in Gvim Windows and Vim in terminal.

### ISSUE THREAD

**Issue by hungpham3112** [vim/vim#10241]
set cursorline will overwrite syntax highlighting in vim-terminal, e.g cmd.exe. wt.exe, pwsh.exe.

https://user-images.githubusercontent.com/75968004/164345481-1e8e547d-8c41-447b-b099-09c7c275cf20.mp4

Gvim:

https://user-images.githubusercontent.com/75968004/164345490-aa0dccb2-4876-4ebf-b887-c9017d88631b.mp4

This bug doesn't appear in neovim.

https://user-images.githubusercontent.com/75968004/164345681-d44fe13a-3491-4125-95fc-dd0486014cc7.mp4

Expected: Cursorline won't overwrite syntax highlighting.

**Comment by zeertzjq** [comment]
FYI Nvim makes `CursorLine` low-priority if it doesn't have a foreground color, and high-priority if it does.

**Comment by hungpham3112** [comment]
> 

Hope vim consider some tiny things like this. It make user experience better. One of things neovim does so well.

**Comment by chrisbra** [comment]
Hm,
I just tried this out on windows with the new terminal and wsl, cmd.exe and gvim I don't see this. I also checked on linux using terminal vim with putty and do not see it. Then I thought it may depend on the 'termguicolor' setting, but also this did not seem to make a difference.

So, please can you reproduce starting with `vim --clean` ?

**Comment by hungpham3112** [comment]
> Hm, I just tried this out on windows with the new terminal and wsl, cmd.exe and gvim I don't see this. I also checked on linux using terminal vim with putty and do not see it. Then I thought it may depend on the 'termguicolor' setting, but also this did not seem to make a difference.
> 
> So, please can you reproduce starting with `vim --clean` ?

This's caused by termguicolor. I have `set t_Co = 256` and `set termguicolor` when remove termguicolor. It's ok.

https://user-images.githubusercontent.com/75968004/164427989-05fea996-9098-4a96-a42f-76b1d53011b2.mp4

**Comment by chrisbra** [comment]
again, please provide minimal reproduction steps. Here is an example for me:

## Windows Terminal:
`vim --clean -c "set cul termguicolors"  "c:\Program Files\Vim\vim82\defaults.vim"`

Looks like this:
![image](https://user-images.githubusercontent.com/244927/164429248-8831ba32-1e76-4532-9013-fca51bb01158.png)


Now use `:set notermguicolors`
![image](https://user-images.githubusercontent.com/244927/164429378-4162244d-e5a7-4456-9d8d-3496286bff64.png)

![image](https://user-images.githubusercontent.com/244927/164429426-c5b8e9d1-35bf-4176-ab62-314b61bc1cfe.png)

<hr> 

## CMD

`vim --clean -c "set cul termguicolors"  "c:\Program Files\Vim\vim82\defaults.vim"`

![image](https://user-images.githubusercontent.com/244927/164429668-0bf8d90f-1d5e-400b-8d38-f3997caf7190.png)

`:set notermguicolors`
![image](https://user-images.githubusercontent.com/244927/164429761-e2093382-2362-4ed0-a1a3-11650c7a4c3a.png)


So looks good?

That's why, please reproduce with a minimal vimrc file.

BTW: I think we have a similar issue regarding termguicolors and cursorline highlighting here. Just did not find it.


Here is my `:version`

```



VIM - Vi IMproved 8.2 (2019 Dec 12 kompiliert am Mar 10 2022 23:04:00)
MS-Windows 64 Bit Konsolen-Version
Inklusive der Patches: 1-4542
Übersetzt von appveyor@APPVYR-WIN
Riesige Version ohne GUI. Ein- (+) oder ausschließlich (-) der Eigenschaften:
+acl                +cscope             +iconv/dyn          +multi_lang         +smartindent        -toolbar
+arabic             +cursorbind         +insert_expand      +mzscheme/dyn       +sodium/dyn         +user_commands
+autocmd            +cursorshape        +ipv6               -netbeans_intg      +sound              +vartabs
+autochdir          +dialog_con         +job                +num64              +spell              +vertsplit
+autoservername     +diff               +jumplist           +packages           +startuptime        +vim9script
-balloon_eval       +digraphs           +keymap             +path_extra         +statusline         +viminfo
+balloon_eval_term  -dnd                +lambda             +perl/dyn           -sun_workshop       +virtualedit
-browse             -ebcdic             +langmap            +persistent_undo    +syntax             +visual
++builtin_terms     +emacs_tags         +libcall            +popupwin           +tag_binary         +visualextra
+byte_offset        +eval               +linebreak          -postscript         -tag_old_static     +vreplace
+channel            +ex_extra           +lispindent         +printer            -tag_any_white      +vtp
+cindent            +extra_search       +listcmds           +profile            -tcl                +wildignore
+clientserver       -farsi              +localmap           +python/dyn         +termguicolors      +wildmenu
+clipboard          +file_in_path       +lua/dyn            +python3/dyn        +terminal           +windows
+cmdline_compl      +find_in_path       +menu               +quickfix           -termresponse       +writebackup
+cmdline_hist       +float              +mksession          +reltime            +textobjects        -xfontset
+cmdline_info       +folding            +modify_fname       +rightleft          +textprop           -xim
+comments           -footer             +mouse              +ruby/dyn           -tgetent            -xpm_w32
+conceal            +gettext/dyn        -mouseshape         +scrollbind         +timers             -xterm_save
+cryptv             -hangul_input       +multi_byte_ime/dyn +signs              +title              
          System-vimrc-Datei: "$VIM\vimrc"
        Benutzer-vimrc-Datei: "$HOME\_vimrc"
 zweite Benutzer-vimrc-Datei: "$HOME\vimfiles\vimrc"
 dritte Benutzer-vimrc-Datei: "$VIM\_vimrc"
         Benutzer-exrc-Datei: "$HOME\_exrc"
 zweite Benutzer-exrc-Datei: "$VIM\_exrc"
      defaults Datei: "$VIMRUNTIME\defaults.vim"
Übersetzt: cl -c /W3 /GF /nologo -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_TERMINAL -DFEAT_SOUND  -DFEAT_JOB_CHANNEL -DFEAT_IPV6    -DHAVE_SODIUM -DDYNAMIC_SODIUM -DDYNAMIC_SODIUM_DLL=\"libsodium.dll\" /I "C:\libsodium\include" -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 /source-charset:utf-8 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG /Zl /MT /D_CRT_SECURE_NO_DEPRECATE /D_CRT_NONSTDC_NO_DEPRECATE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua54.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python310.dll\" -DFEAT_MZSCHEME -I "C:\racket\include" -DMZ_PRECISE_GC -DDYNAMIC_MZSCHEME -DDYNAMIC_MZSCH_DLL=\"libracket3m_da32rk.dll\" -DDYNAMIC_MZGC_DLL=\"libracket3m_da32rk.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl532.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_DLL=\"x64-msvcrt-ruby300.dll\" -DRUBY_VERSION=30 -DFEAT_HUGE /Fd.\ObjCULYHRZAMD64/ /Zi
Linken: link /nologo /opt:ref /LTCG oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib netapi32.lib uuid.lib user32.lib  /machine:AMD64   libcmt.lib   /nodefaultlib:lua54.lib  /STACK:8388608  /nodefaultlib:python27.lib /nodefaultlib:python310.lib    winmm.lib WSock32.lib Ws2_32.lib   /PDB:vim.pdb -debug
```

**Comment by hungpham3112** [comment]
Sorry to waste your time. This is the problem with Vim-polyglot. I will close this issue now.

**Comment by chrisbra** [comment]
No problem. Just try to always reproduce with a minimal vimrc or start from `vim --clean` to rule out other settings or plugins

**Comment by hungpham3112** [comment]
I'm tried to reproduce this. I will response if I have more information.

**Comment by brammool** [comment]
> > Hm, I just tried this out on windows with the new terminal and wsl,
> > cmd.exe and gvim I don't see this. I also checked on linux using
> > terminal vim with putty and do not see it. Then I thought it may
> > depend on the 'termguicolor' setting, but also this did not seem to
> > make a difference.
> > 
> > So, please can you reproduce starting with `vim --clean` ?
> 
> This's caused by termguicolor. I have `set t_Co = 256` and `set
> termguicolor` when remove termguicolor. It's ok.
> 
> https://user-images.githubusercontent.com/75968004/164427989-05fea996-9098-4a96-a42f-76b1d53011b2.mp4

I tried in an xterm and it works fine.

Can you please state exactly what settings and highlight you use?
Start with "vim --clean", check the value of 'term'.

-- 
"You know, it's at times like this when I'm trapped in a Vogon airlock with
a man from Betelgeuse and about to die of asphyxiation in deep space that I
really wish I'd listened to what my mother told me when I was young!"
"Why, what did she tell you?"
"I don't know, I didn't listen!"
		-- Arthur Dent and Ford Prefect in Douglas Adams'
		   "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
can reproduce. This seems to come from setting a Normal highlighting group. This line is to blame:

> hi Normal ctermbg=DarkGrey ctermfg=White guifg=White guibg=grey20

**Comment by hungpham3112** [comment]
> can reproduce. This seems to come from setting a Normal highlighting group. This line is to blame:
> 
> > hi Normal ctermbg=DarkGrey ctermfg=White guifg=White guibg=grey20

Has this been fixed yet?

**Comment by chrisbra** [comment]
No, I did spend some time debugging this, and checked several things. So far the `win_line()` seems to be fine, not sure where this breaks. I am not super familiar with the terminal Windows part of gvim.

**Comment by chrisbra** [comment]
Okay, I found it. This here is too blame:

https://github.com/vim/vim/blob/87f74106f96737e7b8ceaafe1a131aa718077de6/src/highlight.c#L3285-L3306

This comes from patch [v8.0.1531](http://github.com/vim/vim/commit/cafafb381a04e33f3ce9cd15d) and it does intentionally overwrite non-existing fg and bg color attributes with those from the normal group. I wonder why this is only done for terminal  windows vim. 

This will defeat the purpose to combine attributes from the CursorLine highlighting with the Syntax highlighting, because the existing CursorLine attributes will take priority over those from the Syntax highlight and will therefore overwrite syntax highlighting when the cursorline and termguicolors is on.

If we remove that part:
```diff
diff --git a/src/highlight.c b/src/highlight.c
index 6a2b0874d..387384a96 100644
--- a/src/highlight.c
+++ b/src/highlight.c
@@ -3283,27 +3283,6 @@ set_hl_attr(
        at_en.ae_u.cterm.bg_color = sgp->sg_cterm_bg;
        at_en.ae_u.cterm.ul_color = sgp->sg_cterm_ul;
 # ifdef FEAT_TERMGUICOLORS
-#  ifdef MSWIN
-#   ifdef VIMDLL
-       // Only when not using the GUI.
-       if (!gui.in_use && !gui.starting)
-#   endif
-       {
-           int id;
-           guicolor_T fg, bg;
-
-           id = syn_name2id((char_u *)"Normal");
-           if (id > 0)
-           {
-               syn_id2colors(id, &fg, &bg);
-               if (sgp->sg_gui_fg == INVALCOLOR)
-                   sgp->sg_gui_fg = fg;
-               if (sgp->sg_gui_bg == INVALCOLOR)
-                   sgp->sg_gui_bg = bg;
-           }
-
-       }
-#  endif
        at_en.ae_u.cterm.fg_rgb = GUI_MCH_GET_RGB2(sgp->sg_gui_fg);
        at_en.ae_u.cterm.bg_rgb = GUI_MCH_GET_RGB2(sgp->sg_gui_bg);
        // Only use the underline/undercurl color when used, it may clear the

```

ping @k-takata as he may remember why this was done?

**Comment by ntakcat** [comment]
In the environment where the error occurred, create an environment variable like
$> set "WT_SESSION=dummy"

Is it still abnormal?

**Comment by chrisbra** [comment]
doesn't help unfortunately.

**Comment by ntakcat** [comment]
Yes, I understand. Thank you very much.

**Comment by hungpham3112** [comment]
I still have this issue today when I check it. 

vim:
https://user-images.githubusercontent.com/75968004/168516330-9b61e652-7b10-42eb-886e-d8619a8eab3d.mp4

neovim
https://user-images.githubusercontent.com/75968004/168516447-d949db57-0c84-476f-8d83-326a3ab2129a.mp4

**Comment by chrisbra** [comment]
you need patch [v8.2.4877](https://github.com/vim/vim/commit/d560014e032e0646234a56af18ae1bfa6c1f5c90)
