### ISSUE TITLE
Errors when trying to set diffopt on macOS 8.2.4113 normal build

### ISSUE THREAD

**Issue by craigmac** [vim/vim#10250]
### Steps to reproduce

1. Use the vim shipped with macOS monterey 12.3.1 in /usr/bin/vim
2. run `/usr/bin/vim --clean`
3. `:echo has('diff')` should be 1
4. `:verbose set diffopt?` returns `diffopt=filler,closeoff`, note no `internal` for some reason..
5. `:set diffopt+=algorithm:patience`, this should produce `E474: invalid argument: diffopt+=algorith:patience`
6.  Also attempt `:set diffopt+=internal` this will produce the same `E474` error.
7.  Even `:set diffopt=internal` fails. 

Full /usr/bin/vim --version output:
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 12 2022 04:26:50)
macOS version - x86_64
Included patches: 1-4113
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
+acl               +file_in_path      -mouse_urxvt       -tag_any_white
-arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        -termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
-balloon_eval      +fork()            +netbeans_intg     +termresponse
-balloon_eval_term -gettext           +num64             +textobjects
-browse            -hangul_input      +packages          +textprop
+builtin_terms     +iconv             +path_extra        +timers
+byte_offset       +insert_expand     -perl              +title
+channel           +ipv6              +persistent_undo   -toolbar
+cindent           +job               +popupwin          +user_commands
-clientserver      +jumplist          +postscript        -vartabs
+clipboard         -keymap            +printer           +vertsplit
+cmdline_compl     +lambda            -profile           +vim9script
+cmdline_hist      -langmap           -python            +viminfo
+cmdline_info      +libcall           -python3           +virtualedit
+comments          +linebreak         +quickfix          +visual
-conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          -rightleft         +vreplace
+cscope            +localmap          +ruby/dyn          +wildignore
+cursorbind        -lua               +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con        +mksession         +smartindent       +writebackup
+diff              +modify_fname      -sodium            -X11
+digraphs          +mouse             -sound             -xfontset
-dnd               -mouseshape        +spell             -xim
-ebcdic            -mouse_dec         +startuptime       -xpm
-emacs_tags        -mouse_gpm         +statusline        -xsmp
+eval              -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+ex_extra          -mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary
-farsi             -mouse_sysmouse    -tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L/usr/local/lib -o vim        -lm -lncurses  -liconv -framework Cocoa
```

### Expected behaviour

To be able to set something like:

```
:set diffopt+=algorithm:patience,indent-heuristic
```

I have a recent enough Vim for it according to patch level mentioned in https://vimways.org/2018/the-power-of-diff/ article. I've search through issues here and the blame of the runtime/doc/options.txt to see when the features arrived to confirm. `:help 'diffopt'` mentions that you must have `+diff` enabled, which I do when I check with `:echo has('diff')` and can be seen in `:version` output. Is there something else missing? Diff Apple remove the xdiff library or something?

### Version of Vim

8.2.4113

### Environment

macOS Monterey 12.3.1
Terminal.app
xterm-256
/bin/bash (3.2)

**Comment by craigmac** [comment]
Closing because I have found the answer here: https://github.com/agude/dotfiles/issues/2

**Comment by craigmac** [comment]
Maybe this should be documented in `:help mac`? With the workound found in above link as alternative, and a note in `options.txt`? Maybe I'll get around to doing a PR for that, just commenting here in case some else wants to suggest it before I do.

**Comment by chrisbra** [comment]
Please complain to Apple about this.  I am not sure that the LGPL is an issue here, because Vims license is compatible to GPL and LGPL is also compatible to GPL so this should be okay. (And Apple doesn't seem to have a problem with git, which is GPL and includes xdiff as well). 

FWIW, we could of course add an additional version flag, that checks whether xdiff has been compiled in. That would allow to easier check this. But I'd rather see Apple not removing the xdiff part obviously :)
