### ISSUE TITLE
[TeX] Use 'texDelimiter' everywhere instead of 'Delimiter'

### ISSUE THREAD

**Issue by adrian5** [vim/vim#10252]
I think it would be preferable if [TeX syntax](https://github.com/vim/vim/blob/master/runtime/syntax/tex.vim) didn't reference vim's `Delimiter` group directly, but stuck to `texDelimiter`, which also exists. This is common practice is many syntax files, to give per-language control over highlight groups.

```tex
\begin{figure}[!htp]
  \caption{A picture of a toucan.}  %\ These braces are `Delimiter`
  \begin{center}
    \includegraphics{toucan.eps}    %\ These braces are `texInputCurlies` => `texDelimiter`
  \end{center}
\end{figure}
```

**Comment by cecamp** [comment]
Sounds good

**Comment by adrian5** [comment]
I contacted the maintainer back then (2 weeks ago) and got not response until now. So maybe reopen this then.

**Comment by brammool** [comment]
Charles said "sounds good", thus I assume he will include it, try it out and later send the updated file.
You can check his website if the updated test version is already there.

**Comment by adrian5** [comment]
Oh I totally failed to make the cecamp = Charles = TeX maintainer connection! I hesitantly read "Sound good" as "Take care of this yourself, we're not here to process your requests; closed.", since I've ran into plenty of people of this kind (dismissive, short on words) in the tech field. I think the issue has already been taken care of upstream, thanks!
