### ISSUE TITLE
Improvement for `%` and text-objects like `i(`, `a(` and other brackets

### ISSUE THREAD

**Issue by monkoose** [vim/vim#10267]
Currently `%` and text-objects like `i(` works good enough only for C. It is documented, but maybe can be improved? It's understandable that it is hard to make it works perfectly for every filetype, but maybe let the user/plugin authors ability to control how it behaves in some way?
I'm not sure about internals, but maybe some skip function can be exposed, so you could control it's behavior and unwonted brackets could be skipped? The same as it possible with matchit plugin with `b:match_skip` buffer option? 

How it behaves currently described below, lets say for lua. `|` is cursor position

```lua
-- works as expected
pri|nt("hello(world")

-- works as expected
pri|nt("hello)world")

-- lua has single quote strings, also [[ ... ]], but I will skip them in this examples
-- `%` jump to `)` inside the string
-- and `di(` deletes from `(` to the `)` inside a string
pri|nt('hello)world')

-- `%` doesn't move the cursor
-- `di(` doesn't do anything
pri|nt('hello(world')

-- even weirder 
-- `%` doesn't work in doulbe quoted string
-- `di(` works as expected
print("h|ello(world")

-- `%` works, `di(` doesn't do anything
print("hello(wo|rld")

-- `%` jumps between `(` in a string and `)`
-- `diw` doesn't do anything
print('h|ello(world')

-- `%` behaves as above example
-- `di(` deletes inside wrong brackets
print('hello(w|orld')
```

**Comment by brammool** [comment]
The matchit plugin already improves how % works.  This works by mapping the command, thus no extra support in Vim is required.  Make i( work differently should also be possible with a mapping, thus can be done with a plugin.

**Comment by monkoose** [comment]
> The matchit plugin already improves how % works.

Not sure how this fixes behavior of `%` for brackets and not keywords. Am I missing something. So fixing behavior of it from a plugin requires one to implement `matchit` on top of it.

Yes the work of `i(` and friends could be done from plugins. Was just thinking that it internally uses the same alghoright, because I can see some familiarity of how `%` and `i(` currently works.
