### ISSUE TITLE
Gtk-CRITICAL gtk_notebook_get_tab_label: assertion 'list != NULL' failed

### ISSUE THREAD

**Issue by kruthers64** [vim/vim#10271]
### Steps to reproduce

(Sorry if this is the wrong place to report this, I'm using the Ubuntu package version of vim-gtk3.  If this problem doesn't exist in a more recent version of gvim I'll go away...)

1. open gvim w/ tabs on any group of files
2. close gvim
3. get these errors in the shell, one for each tab

Ex:
`gvim --clean -p *.py`

### Expected behaviour

Not having GTK errors filling the terminal.

### Version of Vim

VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 01 2022 09:16:32) Included patches: 1-2269, 3612, 3625, 3669, 3741

### Environment

OS: Linux Mint 20.3 Una (based on Ubuntu 20.04)
Terminal: roxterm 3.12.1
$TERM: xterm-256color
Shell: GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

But I think the relevant info is GTK.  These error messages have just started showing up recently, maybe because GTK was upgraded on my machine?
```
> dpkg-query --list | grep libgtk-3
ii  libgtk-3-0:amd64                           3.24.20-0ubuntu1.1                              amd64        GTK graphical user interface library
ii  libgtk-3-bin                               3.24.20-0ubuntu1.1                              amd64        programs for the GTK graphical user interface library
ii  libgtk-3-common                            3.24.20-0ubuntu1.1                              all          common files for the GTK graphical user interface library
ii  libgtk-3-dev:amd64                         3.24.20-0ubuntu1.1                              amd64        development files for the GTK library
```

And here's the vim package itself:
```
> dpkg-query --list | grep vim-gtk
ii  vim-gtk3                                   2:8.1.2269-1ubuntu5.7                           amd64        Vi IMproved - enhanced vi editor - with GTK3 GUI
```

### Logs and stack traces

```shell
Here's a more detailed capture of the errors showing up in the terminal:

(gvim:11324): Gtk-CRITICAL **: 09:49:57.151: gtk_notebook_get_tab_label: assertion 'list != NULL' failed

(gvim:11324): Gtk-CRITICAL **: 09:49:57.151: gtk_notebook_get_tab_label: assertion 'list != NULL' failed

(gvim:11324): Gtk-CRITICAL **: 09:49:57.151: gtk_notebook_get_tab_label: assertion 'list != NULL' failed

(gvim:11324): Gtk-CRITICAL **: 09:49:57.151: gtk_notebook_get_tab_label: assertion 'list != NULL' failed

(gvim:11324): Gtk-CRITICAL **: 09:49:57.151: gtk_notebook_get_tab_label: assertion 'list != NULL' failed
```

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> (Sorry if this is the wrong place to report this, I'm using the Ubuntu package version of vim-gtk3.  If this problem doesn't exist in a more recent version of gvim I'll go away...)
> 
> 1. open gvim w/ tabs on any group of files
> 2. close gvim
> 3. get these errors in the shell, one for each tab
> 
> Ex:
> `gvim --clean -p *.py`
> 
> ### Expected behaviour
> 
> Not having GTK errors filling the terminal.
> 
> ### Version of Vim
> 
> VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 01 2022 09:16:32) Included patches: 1-2269, 3612, 3625, 3669, 3741
> 
> ### Environment
> 
> OS: Linux Mint 20.3 Una (based on Ubuntu 20.04)
> Terminal: roxterm 3.12.1
> $TERM: xterm-256color
> Shell: GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
> 
> But I think the relevant info is GTK.  These error messages have just
> started showing up recently, maybe because GTK was upgraded on my
> machine?

[...]

> (gvim:11324): Gtk-CRITICAL **: 09:49:57.151: gtk_notebook_get_tab_label: assertion 'list != NULL' failed

I'm using 3.24.30 and do not see these messages.  Perhaps update your
system?


-- 
"Oh, no!  NOT the Spanish Inquisition!"
"NOBODY expects the Spanish Inquisition!!!"
				-- Monty Python sketch --
"Oh, no!  NOT another option!"
"EVERYBODY expects another option!!!"
				-- Discussion in vim-dev mailing list --

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by kruthers64** [comment]
Hmmm, it's fully up to date but still on that version of gtk.  Maybe because linux mint isn't against the latest ubuntu.

In any case, if you don't get the error then that answers my question - not something you can fix.  Thanks for checking!

**Comment by chrisbra** [comment]
so you may want to report this against the mint distribution. Anyhow, closing.
