### ISSUE TITLE
Pressing Shift+Backspace results in Îy character in Powershell

### ISSUE THREAD

**Issue by awa5114** [vim/vim#10279]
### Steps to reproduce

1. Install Vim on a windows machine using `choco install vim`
2. Enter following in vimrc:
```
set number
set belloff=all
syntax on
set backspace=indent,eol,start
set expandtab
set tabstop=4
set shiftwidth=4
set autoindent
set ruler
```

3. Open vim in Powershell
4. Enter some text then press Shift+Backspace in insert mode

### Expected behaviour

That it would delete the previous character or at the very least do nothing.

### Version of Vim

8.2, compiled Jan 7 2022 23:03:22

### Environment

Windows 11 on a standard powershell terminal

**Comment by chrisbra** [comment]
please show full `:version` output

**Comment by chrisbra** [comment]
why are you using `Shift-Backspace`?

**Comment by awa5114** [comment]
Here's the full version output:

![image](https://user-images.githubusercontent.com/24267968/165078295-d0981c3c-286d-490d-9dc1-c39a6772e1fe.png)
 
I would like for Shift+Backspace to have the exact same effect as Backspace as is the case with most notepad editors. When I'm typing a capital letter my finger is already resting on the Shift button. If I need to delete that capital letter I have to remember to remove my finger from the shift button *every time*. If I don't do that then it inserts those characters and I have to delete them, which hurts my workflow.

**Comment by chrisbra** [comment]
Hm, I see. 

It seems to me, this patch fixes it:
```diff
diff --git a/src/os_win32.c b/src/os_win32.c
index 53107d530..dbff37188 100644
--- a/src/os_win32.c
+++ b/src/os_win32.c
@@ -976,7 +976,7 @@ static const struct
     { VK_NEXT, TRUE,   'Q',    '\322', 'v',        '\323', }, // PgDn
     { VK_INSERT,TRUE,  'R',    '\324', '\325',     '\326', },
     { VK_DELETE,TRUE,  'S',    '\327', '\330',     '\331', },
-    { VK_BACK, TRUE,   'x',    'y',    'z',        '{', }, // Backspace
+    { VK_BACK, TRUE,   'x',    'x',    'z',        '{', }, // Backspace

     { VK_SNAPSHOT,TRUE,        0,      0,      0,          'r', }, // PrtScrn

```

not sure, why it is `y` and `z` and `{`  for `<S-Backspace>` and `<C-Backspace>` and `<M-Backspace>`

This all comes from #1833 but not with some documentation on why those values have been used :(

**Comment by brammool** [comment]
The character with and without shift is intentionally different, so that we can tell them apart.
The K_NUL 'x' sequence is recognized as K_BS in term.c.  for shifted backspace there is no special key code.

Have you tried mapping the key?  Use ":map " then CTRL-V and the key, the space and "<BS>".

**Comment by chrisbra** [comment]
I do not understand.

in a terminal on windows, pressing `C-V` + `Backspace` / `S-Backspace` results in:

![image](https://user-images.githubusercontent.com/244927/165119958-0227bb71-6639-4238-8ff9-33579d53bd52.png)

This looks like it is actually the value of `t_kb` however: 
![image](https://user-images.githubusercontent.com/244927/165120182-88b5a050-f115-4b75-b1c1-0c3d12fb1d92.png)

BTW: a mapping doesn't seem to work: 
![image](https://user-images.githubusercontent.com/244927/165121051-dae2d39d-ba76-445b-aaa8-1a1285813722.png)
Vim will still insert the the `Îy` in insert mode.

so I thought if we make `<S-Backspace>` emit the same, this would work. Doesn't seem the correct way then.

**Comment by chrisbra** [comment]
I guess this should do it then:
```diff
diff --git a/src/edit.c b/src/edit.c
index 3790bfb5d..2b4f56ce1 100644
--- a/src/edit.c
+++ b/src/edit.c
@@ -963,6 +963,7 @@ doESCkey:
            break;

        case K_BS:      // delete character before the cursor
+       case K_S_BS:
        case Ctrl_H:
            did_backspace = ins_bs(c, BACKSPACE_CHAR, &inserted_space);
            auto_format(FALSE, TRUE);
diff --git a/src/keymap.h b/src/keymap.h
index 85bf7d0b5..fad1e82cf 100644
--- a/src/keymap.h
+++ b/src/keymap.h
@@ -378,6 +378,7 @@ enum key_extra
 #define K_UNDO         TERMCAP2KEY('&', '8')

 #define K_BS           TERMCAP2KEY('k', 'b')
+#define K_S_BS         TERMCAP2KEY('K', 'M')

 #define K_INS          TERMCAP2KEY('k', 'I')
 #define K_KINS         TERMCAP2KEY(KS_EXTRA, KE_KINS)
diff --git a/src/term.c b/src/term.c
index 0f80e9c40..6b7f394e7 100644
--- a/src/term.c
+++ b/src/term.c
@@ -688,6 +688,7 @@ static struct builtin_term builtin_termcaps[] =
     {K_K8,             "\316\372"},
     {K_K9,             "\316\376"},
     {K_BS,             "\316x"},
+    {K_S_BS,            "\316y"},
 # endif

 # if defined(VMS) || defined(ALL_BUILTIN_TCAPS)
diff --git a/src/testdir/test_edit.vim b/src/testdir/test_edit.vim
index 9ed899d83..e5d99ec46 100644
--- a/src/testdir/test_edit.vim
+++ b/src/testdir/test_edit.vim
@@ -2148,5 +2148,15 @@ func Test_edit_overlong_file_name()
   bwipe!
 endfunc

+func Test_edit_shift_bs()
+  new
+  call setline(1, ['abc'])
+  " Shift Backspace should work like Backspace in insert mode
+  call feedkeys("A\<S-BS> \<esc>", 'xt')
+  "exe ":norm! A\<S-BS> \<esc>"
+  call assert_equal(['ab '], getline(1,'$'))
+  call assert_equal('<CE>^Cx', &t_kb)
+  bw!
+endfunc

 " vim: shiftwidth=2 sts=2 expandtab

```

however I cannot make the test pass.

**Comment by brammool** [comment]
> I do not understand.
> 
> in a terminal on windows, pressing `C-V` + `Backspace` / `S-Backspace` results in:
> 
> ![image](https://user-images.githubusercontent.com/244927/165119958-0227bb71-6639-4238-8ff9-33579d53bd52.png)
> 
> This looks like it is actually the value of `t_kb` however: 
> ![image](https://user-images.githubusercontent.com/244927/165120182-88b5a050-f115-4b75-b1c1-0c3d12fb1d92.png)
> 
> BTW: a mapping doesn't seem to work: 
> ![image](https://user-images.githubusercontent.com/244927/165121051-dae2d39d-ba76-445b-aaa8-1a1285813722.png)
> Vim will still insert the the `Îy` in insert mode.
> 
> so I thought if we make `<S-Backspace>` emit the same, this would work. Doesn't seem the correct way then.

This was implemented a long time ago.  Every key and modifier results in
a different byte sequence, for which most have an entry in the "win32"
default terminal.  But some don't.  I thought that when at least they
have a different byte sequence it would be possible to map them.

The alternative is to insert the modifier separately.  But this requires
some refactoring and might break things.  Just like modifyOtherKeys was
hard to get right.

Running this in a debugger might reveal why mapping doesn't work.

-- 
Never go to the toilet in a paperless office.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
> I guess this should do it then:
> ```diff
> diff --git a/src/edit.c b/src/edit.c
> index 3790bfb5d..2b4f56ce1 100644
> --- a/src/edit.c
> +++ b/src/edit.c
> @@ -963,6 +963,7 @@ doESCkey:
>             break;
> 
>         case K_BS:      // delete character before the cursor
> +       case K_S_BS:
>         case Ctrl_H:
>             did_backspace = ins_bs(c, BACKSPACE_CHAR, &inserted_space);
>             auto_format(FALSE, TRUE);
> diff --git a/src/keymap.h b/src/keymap.h
> index 85bf7d0b5..fad1e82cf 100644
> --- a/src/keymap.h
> +++ b/src/keymap.h
> @@ -378,6 +378,7 @@ enum key_extra
>  #define K_UNDO         TERMCAP2KEY('&', '8')
> 
>  #define K_BS           TERMCAP2KEY('k', 'b')
> +#define K_S_BS         TERMCAP2KEY('K', 'M')

It's probably better to use KE_S_BS instead of "M".
Compare with K_S_UP.


-- 
hundred-and-one symptoms of being an internet addict:
54. You start tilting your head sideways to smile. :-)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by awa5114** [comment]
How can I update my local install to include the fix?

**Comment by brammool** [comment]
> @brammool and @chrisbra Would it be possible to obtain a response about this? Several windows users have been reporting about this issue:

Have you tried the patch in PR #10283?

-- 
From "know your smileys":
 :-O>-o   Smiley American tourist (note big mouth and camera)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by awa5114** [comment]
@brammool I haven't for the following reasons:

- it seems to break a number of tests
- it doesn't seem to have been deployed to a binary or release which I can just install on my system.

Are there any options for users who just want to get this working without messing with the C code in their local install?

**Comment by chrisbra** [comment]
> it seems to break a number of tests

It doesn't. The newly added test does not work, but it works when run interactively.

>it doesn't seem to have been deployed to a binary or release which I can just install on my system.

Yes, if you want to try it out, you need to build vim yourself.

**Comment by awa5114** [comment]
@chrisbra in that case I think I'd rather wait until the next release. Do you have an idea of when that might happen?
