### ISSUE TITLE
Typo in usr_03.txt

### ISSUE THREAD

**Issue by tanishyadav** [vim/vim#10285]
### Steps to reproduce

:h usr_03.txt
/Go:set

### Expected behaviour

`Go:set hlsearch<Esc>`
should instead be
`Goset hlsearch<Esc>`

### Version of Vim

8.2.3995

### Environment

Not relevant

**Comment by brammool** [comment]
That's not a typo.  When this was written the idea is to keep it as simple as possible.  All the previous commands use ":set", thus it's used here as well.  The colon can be left out, but it doesn't hurt.
