### ISSUE TITLE
netrw 171 (regression?) LONGLIST file size column missing left-padding with spaces

### ISSUE THREAD

**Issue by david-fong** [vim/vim#10315]
Yesterday I did an update from Ubuntu 21.10 to ubuntu 22.04. My vim got updated, and my netrw went from v170 to v171. With that change, I noticed that the LONGLIST format no longer left-pads the size information column with spaces to make each entry of the column the same width. It causes the entries of the time column to the right become unaligned. I made a feeble attempt to browse the netrw code. I am not familiar with vim scripting, so I might say or guess stuff that is wrong.

I did notice that the following definition of fsz (a left-padded-with-spaces) doesn't seem to be used? (I'm assuming the definition is scoped to the "if-block"). If it's intended to be used instead of sz, that could be why, in which case I wonder why fsz is defined _before_ the following modification of sz in the case of human-readable units.

https://github.com/vim/vim/blob/202b4bd3a452898cfe3ed72facfbf7cb8199fa4b/runtime/autoload/netrw.vim#L11088

I'm not confident that this is actually the problem because the git blame of those lines says that they haven't been changed for several years.

Sorry if this is a noob issue. Let me know if there's any more information I can provide to help find out why this seems to have changed. I don't know how to go back at test the older version but I do have a screenshot.

<details>
<summary>before and after screenshots</summary>
before:

![Screenshot from 2022-03-05 15-31-53](https://user-images.githubusercontent.com/42986768/165895923-40c1bab7-9381-4e30-bc89-9b5797f2c479.png)

after (note: the size is now in human readable format (`"H"`) because I changed it to be that way after learning that that setting exists):

![Screenshot from 2022-04-28 23-40-37](https://user-images.githubusercontent.com/42986768/165896022-a0723620-29eb-4654-bb43-5b596a66b4db.png)
</details>

**Comment by brammool** [comment]
@cecamp

**Comment by david-fong** [comment]
I also noticed that if a file name is long (longer than around 32 characters), it overflows into the columns for file size and timestamp info, and then the file size and timestamp info get treated as part of the file name when opening the file, which creates a new file with that concatenated name instead of the intended file.

I suppose I should file a separate issue for this?
