### ISSUE TITLE
inconsistency in breakindentopt (briopt) shift item

### ISSUE THREAD

**Issue by NoSuck** [vim/vim#10325]
### Steps to reproduce

1. Size terminal such that `$COLUMNS == 100`.
2. `vim -u NONE`
3. :`set breakindent`
4. :`set breakindentopt=shift:33`
5. :`let &showbreak = "» "` (technically optional)
6. Paste the given sample text and compare with the following results.

Sample text:
```
2022年04月29日 17時07分58秒 [!] …（転んで痛かったものの、２人を巻き込んだので少し気が晴れたまるちゃんである）
2022年04月29日 17時07分58秒 [↓] ログを開始しました。
    　  　  　   　  　  　 [ ] 読み込みます… /mnt/xyz/ス/パル/タ教/育よ/XYZ (xxxxx xxxxx xxxxxxxxxxxx) <xxx.xxxxxxx.xxx>/xxxxxxx/0-0/00-xxxx/xxx.xxxxxxxxx.tar.gz
```

Result, raw:
```
2022年04月29日 17時07分58秒 [!] …（転んで痛かったものの、２人を巻き込んだので少し気が晴れたまるちゃ>                                 » んである）
2022年04月29日 17時07分58秒 [↓] ログを開始しました。
    　  　  　   　  　  　 [ ] 読み込みます… /mnt/xyz/ス/パル/タ教/育よ/XYZ (xxxxx xxxxx xxxxxxxxxx                                     » xx) <xxx.xxxxxxx.xxx>/xxxxxxx/0-0/00-xxxx/xxx.xxxxxxxxx.tar.g                                     » z
```

Result as it appears in the terminal emulator (wrapped at edges):
```
2022年04月29日 17時07分58秒 [!] …（転んで痛かったものの、２人を巻き込んだので少し気が晴れたまるちゃ>
                                 » んである）
2022年04月29日 17時07分58秒 [↓] ログを開始しました。
    　  　  　   　  　  　 [ ] 読み込みます… /mnt/xyz/ス/パル/タ教/育よ/XYZ (xxxxx xxxxx xxxxxxxxxx
                                     » xx) <xxx.xxxxxxx.xxx>/xxxxxxx/0-0/00-xxxx/xxx.xxxxxxxxx.tar.g
                                     » z
```

***IMPORTANT:***  The GitHub web interface might fail to correctly align text in this report.  When in doubt, please view in a terminal with `cjkWidth` set to false, i.e. `Ambiguous (A)` characters of Unicode's `East_Asian_Width (ea)` property occupying 1 column (as opposed to 2).  This is the default setting in XTerm.

### Expected behaviour

Text wrapped at column 100 to column 33:
```
2022年04月29日 17時07分58秒 [!] …（転んで痛かったものの、２人を巻き込んだので少し気が晴れたまるちゃ
    　  　  　   　  　  　     » んである）
2022年04月29日 17時07分58秒 [↓] ログを開始しました。
    　  　  　   　  　  　 [ ] 読み込みます… /mnt/xyz/ス/パル/タ教/育よ/XYZ (xxxxx xxxxx xxxxxxxxx
    　  　  　   　  　  　     » xxx) <xxx.xxxxxxx.xxx>/xxxxxxx/0-0/00-xxxx/xxx.xxxxxxxxx.tar.gz
```

### Version of Vim

8.2.1-2434

### Environment

Raspberry Pi OS (Debian 11.3)
XTerm(366)
xterm
5.1.4(1)-release

**Comment by chrisbra** [comment]
I would say this works as documented. Your line 4 has a 
```
'　' U+3000 Dec:12288 IDEOGRAPHIC SPACE (IS) &#x3000; /\%u3000 "\u3000"
```
In position 4. Indent is only calculated as leading `Space` or `Tab`, that means, the `indent()` function
returns `4` for this line. Now you add an additional number of `33` on top of that indent, which will
wrap it after the logical screen column `37` and this is what you see.

So perhaps, the indent function should consider additional multibyte characters, that are essential whitespace?

I don't know, but this may break a lot of use-cases (but could be considered a bug fix).

**Comment by brammool** [comment]
> I would say this works as documented. Your line 4 has a 
> ```
> '　' U+3000 Dec:12288 IDEOGRAPHIC SPACE (IS) &#x3000; /\%u3000 "\u3000"
> ```
> In position 4. Indent is only calculated as leading `Space` or `Tab`, that means, the `indent()` function
> returns `4` for this line. Now you add an additional number of `33` on top of that indent, which will
> wrap it after the logical screen column `37` and this is what you see.
> 
> So perhaps, the indent function should consider additional multibyte characters, that are essential whitespace?
> 
> I don't know, but this may break a lot of use-cases (but could be
> considered a bug fix).

AFAIK this unicode character is not something you would use for
indenting.  It's more like punctuation.

-- 
% cat /usr/include/long_life.h
long life(double fun);

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by NoSuck** [comment]
The double-width space character is simply that. Furthermore, you can replace it with two U+0020 space characters and still reproduce the issue.

**Comment by chrisbra** [comment]
I am not following. Breakindent, using the shift option, will add the shift-value in addition to the indent of the line. 

So please check: what does `:echo indent('.')` for the line output? And if you add the `shift` value on top of it, does it work as expected or not?

**Comment by NoSuck** [comment]
Take the first line, for example:

```
2022年04月29日 17時07分58秒 [!] …（転んで痛かったものの、２人を巻き込んだので少し気が晴れたまるちゃんである）
```

Its indentation is 0 (confirmed with `:echo indent('.')`), yet it is wrapped to column 34...

```
2022年04月29日 17時07分58秒 [!] …（転んで痛かったものの、２人を巻き込んだので少し気が晴れたまるちゃ>
                                 » んである）
```

... instead of 33:

```
2022年04月29日 17時07分58秒 [!] …（転んで痛かったものの、２人を巻き込んだので少し気が晴れたまるちゃ>
                                » んである）
```

Is that intended behavior?

**Comment by chrisbra** [comment]
yes, I believe we need additional space for the 'showbreak' character to display.

**Comment by NoSuck** [comment]
So `showbreak` has an additional space prepended?  Thank you for the info.  Perhaps such behavior should be documented.  (If it already is, I apologize for being unable to find it.)

In any case, I think U+3000 and all other [isspace](https://docs.python.org/3/library/stdtypes.html#str.isspace) characters should be counted toward indentation.  It is confusing to count a space character as the first non-space character of a line.

Incidentally, is there a way to force all lines to wrap to a specific column?  I recently started using `breakindentopt`, and experimentation showed that `shift` could do this, because of U+3000.  When this did not prove the case, I found behavior to be inconsistent and opened this issue.  If all `isspace` characters counted toward indentation, behavior would be consistent (and there would be no issue), but the ability to wrap at an absolute column might still be nice.  It can be helpful for viewing logs and whatnot, as it helps lines stand out individually.

Thank you for looking into this.  By the way, I know it's been a part of Vim for some years now, but `breakindent` is a great feature!

**Comment by chrisbra** [comment]
adding a `column:` suboption for the `breakindentopt` should be fairly trivial, I think. However I am not yet convinced that this is really needed. I think for logfiles shouldn't a `shift:10` also work?

Regarding the `isspace` issue, that is a different issue and not sure how involved this is, and this may break existing use cases.

**Comment by NoSuck** [comment]
> I think for logfiles shouldn't a `shift:10` also work?

That depends entirely on the log's format.  Take the already provided sample text with `shift:32`, for example:

```
2022年04月29日 17時07分58秒 [!] …（転んで痛かったものの、２人を巻き込んだので少し気が晴れたまるちゃ>
    　  　  　   　  　  　     » んである）
2022年04月29日 17時07分58秒 [↓] ログを開始しました。
    　  　  　   　  　  　 [ ] 読み込みます… /mnt/xyz/ス/パル/タ教/育よ/XYZ (xxxxx xxxxx xxxxxxxxx>
    　  　  　   　  　  　                                     » xxx) <xxx.xxxxxxx.xxx>/xxxxxxx/0->
    　  　  　   　  　  　                                     » 0/00-xxxx/xxx.xxxxxxxxx.tar.gz
```

Desired output, with `column:32` (or perhaps `column:33`):

```
2022年04月29日 17時07分58秒 [!] …（転んで痛かったものの、２人を巻き込んだので少し気が晴れたまるちゃ>
    　  　  　   　  　  　     » んである）
2022年04月29日 17時07分58秒 [↓] ログを開始しました。
    　  　  　   　  　  　 [ ] 読み込みます… /mnt/xyz/ス/パル/タ教/育よ/XYZ (xxxxx xxxxx xxxxxxxxx>
    　  　  　   　  　  　     » xxx) <xxx.xxxxxxx.xxx>/xxxxxxx/0-0/00-xxxx/xxx.xxxxxxxxx.tar.gz```
```

> However I am not yet convinced that this is really needed.

Of course it is not needed, but that can also be said of many things.

> Regarding the isspace issue, that is a different issue...

Is it not precisely what created the “inconsistency” described in this issue?  Should I open a new one?

**Comment by chrisbra** [comment]
Check vim/vim#10362

> Is it not precisely what created the “inconsistency” described in this issue? Should I open a new one?

No. The other issue would be, whether indenting should count/consider other unusual spaces within a line. I think this is controversial, as indenting for various programming languages probably is rather strict and only expects spaces or tabs.

**Comment by NoSuck** [comment]
Holy heck, you make it look easy 😉 I promise to tell everyone about the new feature.  Thank you!

I see what you mean about potential controversy.  And now that you mention it, one might understandably *want* vim to regard certain space characters as non-spaces when programming, as typically only 0x9 or 0x20 would belong there.

Still, it is confusing in non-programming situations.  This is a tough call.
