### ISSUE TITLE
When closing a tab with :q TabEnter event is not triggered

### ISSUE THREAD

**Issue by ghost** [vim/vim#10342]
### Steps to reproduce

1. Add the following code to `.vimrc`: `autocmd TabEnter * echo 'hello'`.
2. Open at least two tabs. 
3. Close one tab with `:q`.

### Expected behaviour

I expect to see the 'hello' message after closing a tab and entering another but it is not shown. However If I close the second tab with `:tabclose` the 'hello' message is shown.

### Version of Vim

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 25 2022 22:13:25) Included patches: 1-4827

### Environment

OS: Arch Linux
Kernel: Linux 5.17.5-arch1-1
terminal: Sakura
value of $TERM: xterm-256color
shell: zsh

**Comment by AvSaba** [comment]
I investigated the problem a bit further and it seems like the problem is with one of the plugins that I'm using and not vim itself. Sorry for false alarm.
