### ISSUE TITLE
undesirable insertion of comment leader in recent vim versions with cindent

### ISSUE THREAD

**Issue by mvduin** [vim/vim#10345]
### Steps to reproduce

1. Enable `cindent` and set `formatoptions+=ro`
2. Type a line with a single-line comment at the end, e.g.
```c
        foo();  // do foo
```
and then press enter
3. Observe insertion of comment leader lined up with the single comment:
```c
        foo();  // do foo
                // 
                   ^--(cursor now here)
```

### Expected behaviour

I absolutely _never_ want this new behaviour. Single-line comments at the end of a statement are for small remarks about that line alone, if you need multiple lines for the comment I'd put them on their own line before the statement.  For me, the expected behaviour is how it always used to work and still does in the version (debian pkg 2:8.2.2434-3+deb11u1) currently in debian stable (bullseye), which is also how it still works when using autoindent or smartindent instead of cindent, i.e. simply go to the next line with appropriate indent so that I can continue typing code.

```c
        foo();  // do foo
        
        ^--(cursor now here)
```

I only expect the comment leader insertion if I'm in an actual comment block:
```c
        // comments comments yada yada press enter at end of line
        // 
           ^--(cursor now here)
```
(this behaviour hasn't changed and works the same for cindent, smartindent, and autoindent)

I can understand that different people can have a different opinion about this, and that they'd appreciate a flag for this behaviour, but changing the default from the way it always used to work and forcing me to remove the comment leader every single time I press enter at the end of a line that has an inline comment is really obnoxious and conflicts with years of muscle memory.

### Version of Vim

8.2.3955 ?  (debian package 2:8.2.4793-1)

### Environment

Operating system: Debian sid

`:version` says:
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 06 2022 17:44:00)
Included patches: 1-3995
Modified by team+vim@tracker.debian.org
```

The version that worked correctly (imo), in debian stable, reports:
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 01 2021 01:51:08)
Included patches: 1-2434
Extra patches: 8.2.3402, 8.2.3403, 8.2.3409, 8.2.3428
Modified by team+vim@tracker.debian.org
```

**Comment by zeertzjq** [comment]
Duplicate of #10006?

**Comment by mvduin** [comment]
Indeed, my bad!
