### ISSUE TITLE
conceal hi

### ISSUE THREAD

**Issue by spavlovich001** [vim/vim#1036]
Two plugin use conceal. indentLine set conceal color and cute-python use this color too.
https://github.com/ehamberg/vim-cute-python/issues/24

**Comment by chrisbra** [comment]
please describe precisly what your problem is.

**Comment by spavlovich001** [comment]
the ability to override conceal

**Comment by chrisbra** [comment]
That should already be possible using match() functions for conceal.

**Comment by chrisbra** [comment]
I am closing this.
