### ISSUE TITLE
doc: command abbreviation error within *Q_wi* in quickref.txt: "cl[ose]" should be "clo[se]" 

### ISSUE THREAD

**Issue by proofer** [vim/vim#10361]
### Steps to reproduce

https://raw.githubusercontent.com/vim/vim/master/runtime/doc/quickref.txt contains, under *Q_wi*      Multi-window commands, at line 1353:
|CTRL-W_c|  CTRL-W c  or  :cl[ose]  make buffer hidden and close window

It is "well known" that the correct, i.e., unambiguous, abbreviation is clo[se], because "cl" conflicts with:
|:clist|    :cl     list all errors
under *Q_qf*      Quickfix commands, at line 1036.

### Expected behaviour

[see Steps to reproduce]

### Version of Vim

N/A

### Environment

N/A

**Comment by brammool** [comment]
Thanks, I'll include it.
