### ISSUE TITLE
Vim9: inconsistencies when `:verbose` outputs lambda's definition

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#10364]
First inconsistency:
```vim
vim9script
var Lambda = () =>
{
    eval 1 + 1
    eval 2 + 2
    eval 3 + 3
}
verbose function <lambda>1
```
    Last set from ... line 3

To get the address of the lambda's definition, `:verbose` used its *first* line.
```vim
vim9script
var Lambda = () =>
    1
    +
    2
    +
    3
verbose function <lambda>1
```
    Last set from ... line 7

This time, to get the address of the lambda's definition, `:verbose` used its *last* line.
It would be more consistent to always use its first line.

---

Second inconsistency:
```vim
vim9script
var Lambda = () =>
{
    eval 1 + 1
    eval 2 + 2
    eval 3 + 3
}
verbose function <lambda>1
```
    def <lambda>1()
            Last set from ... line 3
    1      eval 1 + 1
    2      eval 2 + 2
    3      eval 3 + 3
    enddef

`:verbose` has respected the original formatting of the lambda's body.
For example, it did not join all the lines with bars:

    eval 1 + 1 | eval 2 + 2 | eval 3 + 3
```vim
vim9script
var Lambda = () =>
    1
    +
    2
    +
    3
verbose function <lambda>1
```
    def <lambda>1(): number
         Last set from ... line 7
    1  return 1     +     2     +     3
    enddef

This time, `:verbose` did not respect the original formatting.  It joined all the lines with newlines.
It would be more consistent to always respect the original formatting.

    def <lambda>1(): number
         Last set from ... line 7
    1  return 1
    2         +
    3         2
    4         +
    5         3
    enddef

Respecting the formatting would be very helpful to let us find the exact line from where an error is given.
Currently, whenever we have an error from a lambda, using the info given by the stack trace, we end up on its last line, regardless of how many lines it contains, and regardless of where the error really is.  The only time where the stack trace gives us the correct location is when:

   - the lambda executes a block ([`:help inline-function`](https://vimhelp.org/vim9.txt.html#inline-function))
   - the lambda is executed from a function
   - the error is given at runtime (not at compile time)

Only when all of these conditions are satisfied simultaneously, does a stack trace give us enough information to find where the error is.

---

Third inconsistency:
```vim
vim9script
def Func(..._)
enddef
verbose def Func
```
    def <SNR>1_Func(..._: list<any>)
         Last set from /path/to/script line 2
    enddef

The variable arguments are correctly shown with 3 dots followed by an underscore:

    def <SNR>1_Func(..._: list<any>)
                    ^--^
                     ✔
```vim
vim9script
def Func()
    [0]->map((..._) => 0)
enddef
defcompile
verbose def <lambda>1
```
       def <lambda>1(......_: list<any>): number
            Last set from /path/to/script line 3
    1  return 0
       enddef

This time, the variable arguments are shown with 6 dots followed by an underscore:

       def <lambda>1(......_: list<any>): number
                     ^-----^
                        ✘
It would be more consistent to always use 3 dots followed by an underscore.

**Comment by brammool** [comment]
> First inconsistency:
> ```vim
> vim9script
> var Lambda = () =>
> {
>     eval 1 + 1
>     eval 2 + 2
>     eval 3 + 3
> }
> verbose function <lambda>1
> ```
>     Last set from ... line 3
> 
> To get the address of the lambda's definition, `:verbose` used its
> *first* line.
> ```vim
> vim9script
> var Lambda = () =>
>     1
>     +
>     2
>     +
>     3
> verbose function <lambda>1
> ```
>     Last set from ... line 7
> 
> This time, to get the address of the lambda's definition, `:verbose` used its *last* line.
> It would be more consistent to always use its first line.

Best would be to refer to the very start of the lambda, which is the
arguments.  I can make that work.

> ---
> 
> Second inconsistency:
> ```vim
> vim9script
> var Lambda = () =>
> {
>     eval 1 + 1
>     eval 2 + 2
>     eval 3 + 3
> }
> verbose function <lambda>1
> ```
>     def <lambda>1()
>             Last set from ... line 3
>     1      eval 1 + 1
>     2      eval 2 + 2
>     3      eval 3 + 3
>     enddef
> 
> `:verbose` has respected the original formatting of the lambda's body.
> For example, it did not join all the lines with bars:
> 
>     eval 1 + 1 | eval 2 + 2 | eval 3 + 3
> ```vim
> vim9script
> var Lambda = () =>
>     1
>     +
>     2
>     +
>     3
> verbose function <lambda>1
> ```
>     def <lambda>1(): number
>          Last set from ... line 7
>     1  return 1     +     2     +     3
>     enddef
> 
> This time, `:verbose` did not respect the original formatting.  It
> joined all the lines with newlines.
> It would be more consistent to always respect the original formatting.
> 
>     def <lambda>1(): number
>          Last set from ... line 7
>     1  return 1
>               +
>               2
>               +
>               3
>     enddef

This is quite complicated.  It is also less efficient.  I'm not going to
do this now.

> Respecting the formatting would be very helpful to let us find the
> exact line from where an error is given.
> Currently, whenever we have an error from a lambda, using the info
> given by the stack trace, we end up on its last line, regardless of
> how many lines it contains, and regardless of where the error really
> is.  The only time where the stack trace gives us the correct location
> is when:
> 
>    - the lambda executes a block ([`:help inline-function`](https://vimhelp.org/vim9.txt.html#inline-function))
>    - the lambda is executed from a function
>    - the error is given at runtime (not at compile time)
> 
> Only when all of these conditions are satisfied simultaneously, does a
> stack trace give us enough information to find where the error is.

In most cases it will still be quite easy to figure out what happened.

> ---
> 
> Third inconsistency:
> ```vim
> vim9script
> def Func(..._)
> enddef
> verbose def Func
> ```
>     def <SNR>1_Func(..._: list<any>)
>          Last set from /path/to/script line 2
>     enddef
> 
> The variable arguments are correctly shown with 3 dots followed by an underscore:
> 
>     def <SNR>1_Func(..._: list<any>)
>                     ^--^
>                      ✔
> ```vim
> vim9script
> def Func()
>     [0]->map((..._) => 0)
> enddef
> defcompile
> verbose def <lambda>1
> ```
>        def <lambda>1(......_: list<any>): number
>             Last set from /path/to/script line 3
>     1  return 0
>        enddef
> 
> This time, the variable arguments are shown with 6 dots followed by an underscore:
> 
>        def <lambda>1(......_: list<any>): number
>                      ^-----^
>                         ✘
> It would be more consistent to always use 3 dots followed by an underscore.

That can be fixed.

I'll make a patch for the fixes.  Adding tests is a bit of work, I'll
leave that to someone else.

-- 
Amnesia is one of my favorite words, but I forgot what it means.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
