### ISSUE TITLE
Problems dynamically creating functions

### ISSUE THREAD

**Issue by errael** [vim/vim#10375]
### Steps to reproduce

The issue comes from consideration of passing a small lambda into a small function. I thought the biggest performance issue might come from PCALL/RETURN and its frame maintenance. Wondered if I could dynamically build a function that put it all together.

I didn't expect it to work, but the following does work. 
```
vim9script

def BuildFunc(expr: string): func
    var x =<< trim eval END
        g:SomeRandomFunc = (d: dict<any>) => {expr}
    END
    execute(x)
    return g:SomeRandomFunc
enddef

var ResultPlus = BuildFunc('d.k1 + d.k2')
var ResultMinus = BuildFunc('d.k1 - d.k2')
echo ResultPlus({k1: 3, k2: 4}) ResultMinus({k1: 3, k2: 4})
```
Output: 7 -1

However trying this with a multiline lambda behaves strangley. Run the following and vim appears to hang; hit ESC and an error shows up
```
vim9script
def BuildFuncMultiLine(expr: string): func
    var x =<< trim END
        g:SomeRandomFunc = (d: dict<any>) => {
            return 42
        }
    END
    execute(x)
    return g:SomeRandomFunc
enddef
var ResultPlus = BuildFuncMultiLine('d.k1 + d.k2')
echo ResultPlus({k1: 3, k2: 4})
```
This is the error seen after hitting ESC
```
Error detected while processing :source buffer=2[29]..function <SNR>41_BuildFuncMultiLine:
line    6:
E1171: Missing } after inline function
```

BTW, a multiline define works OK. The following is a workaround, and having to name the function doesn't seem right, and I presume prevents it from being garbage collected.  There might be some tricks I'm missing...
```

vim9script

def BuildFunc(name: string, expr: string): func
    var x =<< trim eval END
        def {name}(): number
            return {expr}
        enddef
        g:MyRandomFunc = {name}
    END

    execute(x)
    var t = g:MyRandomFunc
    g:MyRandomFunc = null
    return t
enddef

var G = BuildFunc('F1', '42')
echo G()

G = BuildFunc('F2', '999')
echo G()
```

### Expected behaviour

BuildFuncMultiLine does not give an error and produces a usable function.

### Version of Vim

8.2.4891

### Environment

ubuntu, gtk3

**Comment by brammool** [comment]
Ernie Rael wrote:

> ### Steps to reproduce
> 
> The issue comes from consideration of passing a small lambda into a
> small function. I thought the biggest performance issue might come
> from PCALL/RETURN and its frame maintenance. Wondered if I could
> dynamically build a function that put it all together.
> 
> I didn't expect it to work, but the following does work. 
> ```
> vim9script
> 
> def BuildFunc(expr: string): func
>     var x =<< trim eval END
>         g:SomeRandomFunc = (d: dict<any>) => {expr}
>     END
>     execute(x)
>     return g:SomeRandomFunc
> enddef
> 
> var ResultPlus = BuildFunc('d.k1 + d.k2')
> var ResultMinus = BuildFunc('d.k1 - d.k2')
> echo ResultPlus({k1: 3, k2: 4}) ResultMinus({k1: 3, k2: 4})
> ```
> Output: 7 -1

In the early days of Vim script adding an "if" statement with a
condition expression was a nice, simple feature.  Seeing the above it
looks like we have gone a long way since then :-).

> However trying this with a multiline lambda behaves strangley. Run the
> following and vim appears to hang; hit ESC and an error shows up
> ```
> vim9script
> def BuildFuncMultiLine(expr: string): func
>     var x =<< trim END
>         g:SomeRandomFunc = (d: dict<any>) => {
>             return 42
>         }
>     END
>     execute(x)
>     return g:SomeRandomFunc
> enddef
> var ResultPlus = BuildFuncMultiLine('d.k1 + d.k2')
> echo ResultPlus({k1: 3, k2: 4})
> ```
> This is the error seen after hitting ESC
> ```
> Error detected while processing :source buffer=2[29]..function <SNR>41_BuildFuncMultiLine:
> line    6:
> E1171: Missing } after inline function
> ```

Looks like the function to get the line from the list isn't passed down
to the lower levels.

-- 
Why is it called "Windows"?  "Gates" would be more appropriate...

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
