### ISSUE TITLE
no start or plus register exists, even vim --version tells +clipboard and +xterm_clipboard.

### ISSUE THREAD

**Issue by cliusz** [vim/vim#10371]
Default compiling vim, tell -clipboard and -xterm_clipboard.
+(xterm_)?clipboard appear after ./configure --with-x.
BUT in cmdline, echo no * or + register for register command.
WHY and HOW?
Thank you very much!

**Comment by chrisbra** [comment]
You need to configure Vim and enable gui. That should make sure the clipboard feature is available (if vim can connect to an X11 server). 

Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. Closing.
