### ISSUE TITLE
redirect all messages to log

### ISSUE THREAD

**Issue by spavlovich001** [vim/vim#1037]
When some plugin crushed messages output to vim. This is uncomfortably. It would be nice to be able to forward all messages to a log. 
exampe:

```
set debug_msg_log = 1
set debug_msg_log_path = '/home/user/.vim/debug.log'
```

**Comment by chrisbra** [comment]
are you looking for `verbosefile` setting?

**Comment by chrisbra** [comment]
I am closing this, as I am not sure, what exactly is asked here. Please use the mailinglist for user questions.
