### ISSUE TITLE
Vim9: cannot use partial in completion spec

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#10370]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        &wildmenu = true
        &wildoptions = 'pum'
        def Completion(..._): string
            return ['a', 'b', 'c']->join("\n")
        enddef
        var Ref: func = function(Completion, [0])
        input('', '', 'custom,' .. Ref->string())
    EOF
    )

Press `Tab` to complete.  This error is given:

    E117: Unknown function: function('<80><fd>R1_Completion', [0])

**Expected behavior**

No error is given.  The pum is open to suggest these completions:

    a
    b
    c

**Version of Vim**

8.2 Included patches: 1-4897

**Environment**

Operating system: Ubuntu 20.04.4 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: GNU bash, version 5.0.17

**Additional context**

If we turn the partial into a simple funcref, by removing the bound `0`, the code works as expected:
```vim
vim9script
&wildmenu = true
&wildoptions = 'pum'
def Completion(..._): string
    return ['a', 'b', 'c']->join("\n")
enddef
var Ref: func = function(Completion)
input('', '', 'custom,' .. Ref->string())
```
    # press Tab
    a
    b
    c

**Comment by lacygoill** [comment]
Also, the byte sequence `<80><fd>R` makes the error message hard to read:

    E117: Unknown function: function('<80><fd>R1_Completion', [0])

This might suggest that there is a place where we need to use `printable_func_name()`.
Similar to what was done in patch [8.2.4657](https://github.com/vim/vim/releases/tag/v8.2.4657).

**Comment by brammool** [comment]
The argument of "custom" is the name of a function, not an expression.  You need to create a function that then invokes the partial.

**Comment by lacygoill** [comment]
> The argument of "custom" is the name of a function, not an expression.

So, why does this work:
```vim
vim9script
&wildmenu = true
&wildoptions = 'pum'
def Completion(..._): string
    return ['a', 'b', 'c']->join("\n")
enddef
var Ref: func = function(Completion)
input('', '', 'custom,' .. Ref->string())
```
`Ref` is not the name of a function, but a funcref expression.  And yet, when we press `Tab`, the pum is open without any error.

---

   > You need to create a function that then invokes the partial.

Yes, this works:
```vim
vim9script
&wildmenu = true
&wildoptions = 'pum'
def Completion(..._): string
    return ['a', 'b', 'c']->join("\n")
enddef
def Wrapper(..._): string
    return Completion(0)
enddef
input('', '', 'custom,' .. Wrapper->string())
```
Just like this works:
```vim
vim9script
var dir = '/tmp/.vim'
dir->delete('rf')
&runtimepath = dir
dir ..= '/autoload'
dir->mkdir('p')
var lines =<< trim END
    vim9script
    export def CompleteWords(..._): string
        return getline(1, '$')
            ->join(' ')
            ->split('\s\+')
            ->filter((_, word) => word =~ '^\a\k\+$')
            ->sort()
            ->uniq()
            ->join("\n")
    enddef
END
lines->writefile(dir .. '/script.vim')
import autoload 'script.vim'
'the quick brown fox jumps over the lazy dog'->setline(1)
def Wrapper(..._): string
    return script.CompleteWords()
enddef
var word: string = input('word: ', '', 'custom,' .. expand('<SID>') .. 'Wrapper')
```
But it was considered as clumsy:

   > This seems a reasonable alternative, but clumsy.

Source: <https://github.com/vim/vim/issues/10197#issuecomment-1100431974>

If we really need a wrapper function, I'll use one.  But the code would be easier to read without.

**Comment by brammool** [comment]
>    > The argument of "custom" is the name of a function, not an expression.
> 
> So, why does this work:
> ```vim
> vim9script
> &wildmenu = true
> &wildoptions = 'pum'
> def Completion(..._): string
>     return ['a', 'b', 'c']->join("\n")
> enddef
> var Ref: func = function(Completion)
> input('', '', 'custom,' .. Ref->string())
> ```
> `Ref` is not the name of a function, but a funcref expression.

Well:
	echomsg 'custom,' .. Ref->string()
shows:
	custom,function('<SNR>89_Completion')

And:
	echo function('<SNR>89_Completion')
shows:
	<SNR>89_Completion

Thus in the end it's just a function name.

The problem with the partial is that it can't be reduced to just a
function name.


-- 
hundred-and-one symptoms of being an internet addict:
129. You cancel your newspaper subscription.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> The problem with the partial is that it can't be reduced to just a
   > function name.

Understood, it's too complex.  I would have then also asked for lambdas, which I guess would have been quite difficult to support.  This would have let us simplify this snippet:
```vim
vim9script
var YesNo: func = (..._) => "yes\nno"
var answer: string = input('do it?', '', 'custom,' .. YesNo->string())
```
Into this one:
```vim
vim9script
var answer: string = input('do it?', '', 'custom,' .. ((..._) => "yes\nno")->string())
```
So, closing the issue.
