### ISSUE TITLE
SIGSEGV with Perl global variables in plugins

### ISSUE THREAD

**Issue by senioria** [vim/vim#10386]
# Steps to reproduce

`rc.vim`:
```vim
vim9script

perl <<EOF
my $tick = 0;
my $last = "";
sub WordCount {
    if (@_[0] == $tick) {
        return $last;
    }
    $tick = @_[0];
    my $ctnt = join ' ', $curbuf->Get(1..$curbuf->Count());
    utf8::decode($ctnt);
    my $hanzi = 0 + $ctnt =~ s/\p{Han}/ i /g;
    my $count = () = $ctnt =~ /\b\w[\w'.]*\b/g;
    $last = "$count WD";
    if ($hanzi != 0) {
        $last = $last . ", $hanzi HZ";
    }
    return $last;
}
EOF
def QAQ(): string
    return perleval("WordCount " .. b:changedtick)
enddef
au InsertLeave * QAQ()
au TextChanged * QAQ()
```

Start vim with `vim -Nu rc.vim rand.txt`, where `rand.txt` is a file with a lot text. Randomly insert many parentheses in the file, move around, and save the file, and vim crashes.

At first when I tried to edit markdown files (my config is at [here](https://github.com/91khr/dotfile/tree/efc4f7197b9f1d4ba72023225c225f391ad3b01e)), this issue behaves as the source code of `<SNR>7_Highlight_Matching_Pair()`, starting from line 103, is replaced with random content, and if insist to edit after the first error of unknown command, vim soon crashes.

vim version: 8.2.4877

**Comment by lacygoill** [comment]
I can reproduce with this `rand.txt` file:

    xxxxxxx {x
    xx xxxxx xxx xxxxx xxxxxxx{
    xxxxxxxxx
    xxxxxxx
    xxxxxxx
    xxx xxxx xxxx xxx xxxxx xxxx
    xxxxxxx xxxx xxxxxxx xxxx xxxxxx xxxxxxxx xxxxx xxxxxxx xxx xxxxxxxxxx xx xxx
    xxxxxxxxxxx
    }
    xxxxxxxxxxxxxxxxxxxxxxx  xxxx
    xxxxxxxxxxxxxxx  xxxx
    xxxxxxxxx  xxxxxxxx
    xxxxxxxxxxxxxxxxxxxxx  xxxx
    xxxxxxxxxxxxxxx  xxxx
    xxx xx xxxxxxx xxxxx{
    xx xxxxxxxxx
    xxxxxxxxxxxxxxxxxxx  xxxx
    xx xxxxxxxx
    xxxxxxxxxxxxx  xxxx
    xxx xxxx xxxxxxxxxxx
    }
    xxx xxxxx xx xx x xxx xxxx{
    xxxx xxxxxxxxxx xxxxxxx  xxxxx xxxx xx xxxxx  xxx x xxxx xxxx  xx xxxx xxxx
    xxxxxxxxx xxxx
    xxx xxxxxxx xxxxxxx xxxxx xxx  xxxxxxx xxxxxxx xxxxxxxx xx xxxxxxxxxxx
    xxx xxxxxxxxxx xxxxxx xxxx
    xxxxx xxxx xxxx xxx xxxx x xxxxxx xxxx xxxxxxx xx xx xxxxxxxxx xxx
    xxx xxxxxxx xx xxx xxxxx xx xx xxxx xxx
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    xx xxxx xxxx xxx xxxxxxxxxxx xxxx xx x xxx xxxxx
    xxxx xxxxx xxxx xxxx xxxx
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    }

And starting Vim like this:

    vim -Nu NORC -S /tmp/crash.vim /tmp/rand.txt

Press `o` to open a new line below the first one, then insert some parens (`()()()...`).  Quit insert mode, and do it again.  Usually, it crashes after 2 or 3 times of entering and quitting insert mode to write new parens.

   - [backtrace](https://github.com/vim/vim/files/8651064/gdb.txt)
   - [ubsan log](https://github.com/vim/vim/files/8651065/ubsan.log)
   - [valgrind log](https://github.com/vim/vim/files/8651066/valgrind.log)

**Comment by brammool** [comment]
> I can reproduce with this `rand.txt` file:
> 
>     xxxxxxx {x
>     xx xxxxx xxx xxxxx xxxxxxx{
>     xxxxxxxxx
>     xxxxxxx
>     xxxxxxx
>     xxx xxxx xxxx xxx xxxxx xxxx
>     xxxxxxx xxxx xxxxxxx xxxx xxxxxx xxxxxxxx xxxxx xxxxxxx xxx xxxxxxxxxx xx xxx
>     xxxxxxxxxxx
>     }
>     xxxxxxxxxxxxxxxxxxxxxxx  xxxx
>     xxxxxxxxxxxxxxx  xxxx
>     xxxxxxxxx  xxxxxxxx
>     xxxxxxxxxxxxxxxxxxxxx  xxxx
>     xxxxxxxxxxxxxxx  xxxx
>     xxx xx xxxxxxx xxxxx{
>     xx xxxxxxxxx
>     xxxxxxxxxxxxxxxxxxx  xxxx
>     xx xxxxxxxx
>     xxxxxxxxxxxxx  xxxx
>     xxx xxxx xxxxxxxxxxx
>     }
>     xxx xxxxx xx xx x xxx xxxx{
>     xxxx xxxxxxxxxx xxxxxxx  xxxxx xxxx xx xxxxx  xxx x xxxx xxxx  xx xxxx xxxx
>     xxxxxxxxx xxxx
>     xxx xxxxxxx xxxxxxx xxxxx xxx  xxxxxxx xxxxxxx xxxxxxxx xx xxxxxxxxxxx
>     xxx xxxxxxxxxx xxxxxx xxxx
>     xxxxx xxxx xxxx xxx xxxx x xxxxxx xxxx xxxxxxx xx xx xxxxxxxxx xxx
>     xxx xxxxxxx xx xxx xxxxx xx xx xxxx xxx
>     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
>     xx xxxx xxxx xxx xxxxxxxxxxx xxxx xx x xxx xxxxx
>     xxxx xxxxx xxxx xxxx xxxx
>     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
>     }
> 
> And starting Vim like this:
> 
>     vim -Nu NORC -S /tmp/crash.vim /tmp/rand.txt
> 
> Press `o` to open a new line below the first one, then insert some parens (`()()()...`).  Quit insert mode, and do it again.  Usually, it crashes after 2 or 3 times of entering and quitting insert mode to write new parens.
> 
>    - [backtrace](https://github.com/vim/vim/files/8651064/gdb.txt)
>    - [ubsan log](https://github.com/vim/vim/files/8651065/ubsan.log)
>    - [valgrind log](https://github.com/vim/vim/files/8651066/valgrind.log)

The valgrind log is most useful.  It shows a double free in
call_def_function().  Most likely before this something failed, was
there any error message?

The stack shows a call to invoke_popup_filter(), but I don't see a
popup in the script.  I assume this is using a plugin?

-- 
hundred-and-one symptoms of being an internet addict:
145. You e-mail your boss, informing him you'll be late.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
Oh, really sorry, it's not the right valgrind log.  I'll post a new one later.

**Comment by lacygoill** [comment]
Here is the [correct log](https://github.com/vim/vim/files/8651586/valgrind.log).

**Comment by lacygoill** [comment]
And here is the correct [backtrace](https://github.com/vim/vim/files/8651614/gdb.txt).
