### ISSUE TITLE
Documentation: missing `let` when assigning the `g:current_compiler` variable in the example

### ISSUE THREAD

**Issue by matteocoder** [vim/vim#10382]
### Steps to reproduce

In `usr_41.txt`, in the `write-compiler-plugin` section, the beginning of the example compiler file is missing the `let` keyword when assigning the `g:current_compiler` variable.

```
There are two special items about these files.  First is a mechanism to allow
a user to overrule or add to the default file.  The default files start with: >

	if exists("g:current_compiler")
	  finish
	endif
	g:current_compiler = "mine"

``` 

### Expected behaviour

The last line should be `let g:current_compiler="mine"`.

### Version of Vim

8.2.4877

### Environment

OS: Microsoft Windows [Version 10.0.19043.1645].

**Comment by nickspoons** [comment]
That line, and most of the file, is written in vim9 syntax, which does not use `:let`. See the top of the file under `vim-script-intro` where it says:

> Vim script comes in two flavors: legacy and |Vim9|.  Since this help file is for new users, we'll teach you the newer and more convenient |Vim9| syntax.

**Comment by matteocoder** [comment]
@nickspoons Thanks for your reply and sorry for not noticing that part. I'll close the issue.

**Comment by nickspoons** [comment]
It's not a problem, I'm sure Bram appreciates having people report documentation errors when they find them.
