### ISSUE TITLE
min() and max() spawn lots of error messages if sorted list/dictionary contains invalid data

### ISSUE THREAD

**Issue by ZyX-I** [vim/vim#1039]
max_min function in evalfunc.c always returns 0 if error is given, but neveretherless all cycles ignore error condition and proceed finding minimal/maximal value which will then never be used. To check see

```
vim -u NONE -i NONE -N --cmd 'echo max([[], [], [], 5])' --cmd cq
```

This will show

```
Error detected while processing pre-vimrc command line:
E745: Using a List as a Number
E745: Using a List as a Number
E745: Using a List as a Number
0
```

: three error messages where one is enough.

---

Also it is strange that function uses “infinite” `for (;;)` cycle while code is completely fine and more compact when written as

```
            for (li = li->li_next; li != NULL && !error; li = li->li_next)
            {
                i = get_tv_number_chk(&li->li_tv, &error);
                if (domax ? i > n : i < n)
                    n = i;
            }
```

**Comment by lacygoill** [comment]
This todo item is no longer relevant:

> min() and max() spawn lots of error messages if sorted list/dictionary
> contains invalid data (Nikolay Pavlov, 2016 Sep 4, #1039)

**Comment by brammool** [comment]
> This todo item is no longer relevant:
> 
> > min() and max() spawn lots of error messages if sorted list/dictionary
> > contains invalid data (Nikolay Pavlov, 2016 Sep 4, #1039)

I'll delete it.

-- 
I have to exercise early in the morning before my brain
figures out what I'm doing.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
