### ISSUE TITLE
:set ft=help triggers error in :h syntax.txt (E969)

### ISSUE THREAD

**Issue by habamax** [vim/vim#10409]
### Steps to reproduce

1. `vim -Nu NONE`
2. `:syntax on`
3. `:h cursorlinefold`

UPD:
1. `vim -Nu NONE`
2. `:syntax on`
3. `:h syntax.txt`
4. `:set ft=help`

### Expected behaviour

Help window should be opened without error.

### Version of Vim

8.2.4939

### Environment

Fedora 36, all terminals

**Comment by habamax** [comment]
![image](https://user-images.githubusercontent.com/234774/168017288-2c3a93a2-453e-4c08-8b88-e32e77758a62.png)

**Comment by Shane-XB-Qian** [comment]
```log
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 12 2022 15:21:35)
Included patches: 1-4939
```

no err to me. :-)

**Comment by lacygoill** [comment]
I don't have any error, but this `silent!` should fix the issue:
```diff
diff --git a/runtime/import/dist/vimhelp.vim b/runtime/import/dist/vimhelp.vim
index 1f587251b..7d1e650c2 100644
--- a/runtime/import/dist/vimhelp.vim
+++ b/runtime/import/dist/vimhelp.vim
@@ -9,7 +9,7 @@ export def HighlightGroups()
   while getline(lnum) !~ '===' && lnum < line('$')
     var word: string = getline(lnum)->matchstr('^\w\+\ze\t')
     if word->hlexists()
-      prop_type_add('help-hl-' .. word, {
+      silent! prop_type_add('help-hl-' .. word, {
 	bufnr: buf,
 	highlight: word,
 	combine: false,
```
Alternatively, we could test the existence of the text property before trying to install it:
```diff
diff --git a/runtime/import/dist/vimhelp.vim b/runtime/import/dist/vimhelp.vim
index 1f587251b..9c6cbac5d 100644
--- a/runtime/import/dist/vimhelp.vim
+++ b/runtime/import/dist/vimhelp.vim
@@ -9,11 +9,13 @@ export def HighlightGroups()
   while getline(lnum) !~ '===' && lnum < line('$')
     var word: string = getline(lnum)->matchstr('^\w\+\ze\t')
     if word->hlexists()
-      prop_type_add('help-hl-' .. word, {
-	bufnr: buf,
-	highlight: word,
-	combine: false,
-	})
+      if prop_type_list({bufnr: buf})->index('help-hl-' .. word) == -1
+	prop_type_add('help-hl-' .. word, {
+	  bufnr: buf,
+	  highlight: word,
+	  combine: false,
+	  })
+      endif
       prop_add(lnum, 1, {length: word->strlen(), type: 'help-hl-' .. word})
     endif
     ++lnum
```
BTW, the code could be improved in several ways.  I'll try to open in a PR few days to suggest some of them.

**Comment by habamax** [comment]
I have tried it on gvim (windows) with 8.2.4937 and get the same error.

Looks like my configuration is still involved even though I run it with `gvim -Nu NONE`.

**Comment by habamax** [comment]
So indeed my configuration interferes, I have `~/.vim/ftdetect/rst.vim` that does:

```
autocmd BufNewFile,BufRead *.txt,*.rest set ft=rst
```

And this triggers the error mentioned in the OP.

PS, it doesn't matter what filetype I set, the same happens if I `set ft=text`.

**Comment by lacygoill** [comment]
> autocmd BufNewFile,BufRead *.txt,*.rest set ft=rst

The `:set ft` command must probably cause `Syntax` to be fired a second time, which causes the text property to be installed a second time, which Vim doesn't like.
```vim
vim9script
prop_type_add('type', {highlight: 'ErrorMsg'})
prop_type_add('type', {highlight: 'ErrorMsg'})
```
    E969: Property type type already defined

**Comment by habamax** [comment]
Maybe I should be setting `rst` filetype only for txt files outside of `doc/` dir, but I have my docs in txt files in a `~/doc` dir :)

**Comment by habamax** [comment]
Okay, I think this could be workarounded with the following:

```
autocmd BufNewFile,BufRead *.txt if &buftype != "help" | set ft=rst | endif
```

**Comment by lacygoill** [comment]
Yes, this is definitely a bug.  Either, we should suppress the error with `silent!` or check its existence before trying to install it.  That's what I always do whenever I install a new text property type, because I never care about this error.

**Comment by brammool** [comment]
Using silent!  may hide other errors.  I'll add a check if the type already exists.
