### ISSUE TITLE
text-properties not correctly shifted with 'set autoindent' after inserting a line break

### ISSUE THREAD

**Issue by bfrg** [vim/vim#10417]
### Steps to reproduce

Run `vim --clean -S test.vim`, with
```vim
set autoindent
enew
call setline(1, 'test test test')
call prop_type_add('Test', {'highlight': 'Error'})
call prop_add(1, 6, {'length': 4, 'type': 'Test'})
```

This will highlight the second `test` in line 1 as `Error`:
```
test test test
     ^^^^
```

Now add a line break after the first `test`, for example, by pressing`5|i<cr>`. 

**Result:** The leading white space before the second `test` has been removed but the text-property wasn't adjusted properly:
```
test
test test
 ^^^^
```

### Expected behaviour

Text-properties should be correctly shifted when leading space characters are removed after inserting a line break.

### Version of Vim

8.2.4948

### Environment

Linux

**Comment by lacygoill** [comment]
This looks very similar to https://github.com/vim/vim/issues/7719 , for which there is a [todo item](https://github.com/vim/vim/blob/d881d1598467d88808bafd2fa86982ebbca7dcc1/runtime/doc/todo.txt#L131):

    - Auto-indenting may cause highlighting to shift. (#7719)
