### ISSUE TITLE
feature request: leading "multispace"-like option

### ISSUE THREAD

**Issue by bugsbugsbux** [vim/vim#10411]
hi, the new listchars option 'multispace' is really cool and i use it to show indent levels of space-indented lines, however, it also marks multiple spaces after the first visible character. this may be what the feature was intended to do (#8834), but for my usecase it is slightly annoying.

it would be great to have a similar feature for just the leading spaces. the 'lead' option could take multi-character strings like 'multispace' does, which wouldn't break peoples configs because setting a single-character string would result in the same behaviour as the current 'lead' behaviour (if this is triggered by leading spaces instead of multiple ones).

regards

**Comment by zeertzjq** [comment]
Related comment: <https://github.com/vim/vim/pull/7772#issuecomment-772561146>
> For an indentation guide another field would be more appropriate. You might also want to show it when not showing leading space.

**Comment by zeertzjq** [comment]
This should also be closed by patch 8.2.5066

**Comment by chrisbra** [comment]
closing then. Thanks!

**Comment by marcusatiliusregulus** [comment]
yay! thanks so much!
