### ISSUE TITLE
vimrc.o: file not recognized

### ISSUE THREAD

**Issue by illusorypan** [vim/vim#1041]
Hi all,

This is supposed to be a compilation issue. I am using Cygwin to build gvim.exe with the following command:

> make -f Make_cyg.mak SHELL=bash CC=i686-w64-mingw32-gcc CXX=i686-w64-mingw32-g++ RC=i686-w64-mingw32-windres ARCH=i686 CROSS_COMPILE=x86_64-w64-mingw32- USEDLL=no PYTHON=/cygdrive/c/Python27 PYTHON_VER=27 DYNAMIC_PYTHON=yes PERL=/cygdrive/c/htemp/Perl PERL_VER=516 DYNAMIC_PERL=yes GUI=yes OLE=yes

It ends up with the error:

> gobji686/vimrc.o: file not recognized: File format not recognized
> collect2: error: ld returned 1 exit status
> make: **\* [Make_cyg_ming.mak:829: gvim.exe] Error 1

Thanks!

**Comment by k-takata** [comment]
> CC=i686-w64-mingw32-gcc CXX=i686-w64-mingw32-g++ RC=i686-w64-mingw32-windres ARCH=i686 CROSS_COMPILE=x86_64-w64-mingw32-

You set `CROSS_COMPILE` wrongly. You should set `CROSS_COMPILE=i686-w64-mingw32-`, if you want to use MinGW-w64 for 32-bit target. If `CROSS_COMPILE` is properly set, normally you don't need to set `CC`, `CXX` and `RC`. (And, if you build Vim 7.4.2034 or later, `ARCH` will be also automatically detected.)
