### ISSUE TITLE
Vim9: can't use heredoc in nested functions

### ISSUE THREAD

**Issue by senioria** [vim/vim#10415]
The following code doesn't compile:

```vim
def F(): string
    def G(): string
        perl <<EOF
        print "";
EOF
    return ''
    enddef
    return G()
enddef
defcompile
```

vim complains "missing heredoc end marker: EOF<00>".

What's more, for similar code:

```vim
def F(): string
    def G(): string
        perl <<EOF
EOF
    return ''
    enddef
    return G()
enddef
defcompile
```

vim complains "missing heredoc end marker: EOF<00>EOF".

vim version: 8.2.4922

**Comment by lacygoill** [comment]
Unrelated to the current issue, but I've noticed that the highlighting of the perl heredoc was wrong:

![gif](https://user-images.githubusercontent.com/8505073/168323354-3b606a43-3aea-4b62-ad33-2ea71f1440ab.gif)

So, I fixed it in the [vim9-syntax](https://github.com/lacygoill/vim9-syntax) plugin:

![gif](https://user-images.githubusercontent.com/8505073/168322966-87283325-ae8d-430b-afc0-fce3f3625849.gif)

Inside the `g:vim9_syntax` dictionary, the `fenced_languages` key must be assigned a list containing the `'perl'` string.  For example:
```vim
vim9script
g:vim9_syntax = {
    builtin_functions: true,
    data_types: true,
    fenced_languages: ['perl'],
    errors: {
        event_wrong_case: true,
        octal_missing_o_prefix: true,
        range_missing_space: true,
        range_missing_specifier: true,
        strict_whitespace: true,
    }
}
```
