### ISSUE TITLE
(syntax) m4 does not recognize # comments

### ISSUE THREAD

**Issue by albinahlback** [vim/vim#10424]
As that syntax file has not been touched for a long while, I suppose Claudio Fleiner is no longer the maintainer of it.

Currently, it does not recognize # comments. See https://www.gnu.org/software/m4/manual/html_node/Comments.html.

**Comment by brammool** [comment]
You can send Claudio an email.  He responded last year at least.
The link to his website works, but the version there is older.

**Comment by albinahlback** [comment]
I sent him an email with a simple patch.

**Comment by jamessan** [comment]
This should be fixed by https://github.com/vim/vim/commit/63f32603789d1a27c559fc440325955fd0b8b500#diff-542588287f6cc3dee028c9dab58e9482de6133c10254f94d4461d4e969b00e18
