### ISSUE TITLE
Errors message displayed when invoking help within gvim

### ISSUE THREAD

**Issue by basilisk0315** [vim/vim#10426]
### Steps to reproduce

1. Open a vim source file in gvim (in this case textprop.c).
2. Type :h linenr like this:
![image](https://user-images.githubusercontent.com/54644368/168451523-78e67b22-17a9-4b84-b5ae-c16e22abf7f7.png)
3. After pressing <enter>:
![image](https://user-images.githubusercontent.com/54644368/168451544-5db7c3eb-eb60-464e-b85d-bcd61109a85a.png)

If I resize the window and use the same command I get this:
![image](https://user-images.githubusercontent.com/54644368/168451559-644fc807-9fc4-4643-be65-e24932f8a993.png)

So the error message seems to change depending on what is displayed.

Interestingly, typing other help commands (eg :h normal) gives no error.

Cheers
John

### Expected behaviour

No error message displayed.

### Version of Vim

8.2.4956 (including git pull which included updates to runtime help files)

### Environment

Windows 8.1 x64
gvim was compiled with mingw64 (gcc 11.3.0).

**Comment by habamax** [comment]
duplicate https://github.com/vim/vim/issues/10409

This was fixed.

**Comment by brammool** [comment]
This is a different error.  There is no check if the textprop feature is supported.  I'll add that:
```vim
if has('textprop') && expand('%:p') =~ '[/\\]doc[/\\]syntax.txt'
```

**Comment by chrisbra** [comment]
this seems to be fixed now.
