### ISSUE TITLE
Patch 8.2.4710 causes several problems

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#10420]
1. The `can_si` flag is set to `TRUE` without checking any options. In the other two places (`open_line()` and `op_change()`) where `can_si` is set to `TRUE`, `p_paste`, `b_p_si`, `b_p_cin` and `b_p_inde` are checked.
2. Typing a character that reindents the line when a completion item is selected causes wrong resulting text. For example, this produces `#foo` instead of `foo#` on the second line:
```vim
" Happens without 'smartindent' because "do_si" is set without checking it
" set smartindent
call setline(1, 'foo foot')
call feedkeys("o  f\<C-X>\<C-N>#", 'tx')
```

**Comment by brammool** [comment]
I'll fix it.
I'm wondering if we should graduate FEAT_CINDENT and FEAT_SMARTINDENT.
The only reason to exclude them would be code size.

**Comment by zeertzjq** [comment]
The problem still exists when typing a closing brace:
```vim
set smartindent
call setline(1, 'foo foot')
call feedkeys("o  f\<C-X>\<C-N>}", 'tx')
```

**Comment by brammool** [comment]
> The problem still exists when typing a closing brace:
> ```vim
> set smartindent
> call setline(1, 'foo foot')
> call feedkeys("o  f\<C-X>\<C-N>}", 'tx')
> ```

I can fix it in a similar way.  But I start to wonder why can_si is ever
set when doing completion.  When commenting out that line no test fails.

-- 
hundred-and-one symptoms of being an internet addict:
193. You ask your girlfriend to drive home so you can sit back with
     your PDA and download the information to your laptop

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
