### ISSUE TITLE
strange behavior of cgete ''

### ISSUE THREAD

**Issue by Shane-XB-Qian** [vim/vim#10438]
### Steps to reproduce

```vim
cgete 'foo'
cgete 'bar'
cgete ''
cgete ''
1chistory
cgete ''
cgete ''
```

### Expected behaviour

Result:
```vim
  error list 1 of 3; 1 errors     :cgete 'foo'
  error list 2 of 3; 0 errors     :cgete ''
> error list 3 of 3; 0 errors     :cgete ''
```

Expected:
```vim
  error list 1 of 6; 1 errors     :cgete 'foo'
  error list 2 of 6; 0 errors     :cgete ''
> error list 3 of 6; 0 errors     :cgete ''
  error list 4 of 6; 1 errors     :cgete 'bar'
  error list 5 of 6; 0 errors     :cgete ''
  error list 6 of 6; 0 errors     :cgete ''
```

i think `cgete ''` should just insert an empty qf after that first 'foo' qf,
vs but Not Clean those later ones (e.g that 'bar' qf).

### Version of Vim

v8.2.4972

### Environment

linux

**Comment by lacygoill** [comment]
When `:1 chistory` is executed, the first quickfix list in the stack is made the current list.  This is documented at [`:help :chistory`](https://vimhelp.org/quickfix.txt.html#%3Achistory):

    When [count] is given, then the count'th quickfix
    list is made the current list. Example: >
            " Make the 4th quickfix list current
            :4chistory

Afterward, when `:cgetexpr` is executed, a new quickfix list is added in the stack.  However, it's not added on top of the stack; it overwrites the next quickfix list (and discards all the subsequent lists).  This is documented a little later, below [`:help :lhistory`](https://vimhelp.org/quickfix.txt.html#%3Alhistory):

    When ":colder" has been used and ":make" or ":grep" is used to add a new error
    list, one newer list is overwritten.  This is especially useful if you are
    browsing with ":grep" |grep|.  If you want to keep the more recent error
    lists, use ":cnewer 99" first.

**Comment by Shane-XB-Qian** [comment]
i knew, but i do not agree, and it is not `one newer list is overwritten` but all newer were overwritten.
i think better just insert a new one always, and kept the history really if so.
unless worry about the amount (would be too many?)

**Comment by Shane-XB-Qian** [comment]
i think this is not a 'stack', but simply just was (should be) a 'history' of qf recoreds. :-)
simply just like cmd history or search history..
always insert 'new' (vs 'overwrite') should be more make sense..
// or setqflist() with 'r' flag if really  want to replace it.
unless the amount was a concern..........

**Comment by brammool** [comment]
The current behavior has existed for a long time, it can't be changed without causing trouble.
When making changes, it should not be seen as a list, but as a tree.  When going back and creating a new entry, it should come next to the existing one.  A bit like undo history.  This might be difficult to navigate though.

**Comment by bfrg** [comment]
The current behavior is documented under `:h setqflist-action`.

https://github.com/vim/vim/blob/4748c4bd64610cf943a431d215bb1aad51f8d0b4/runtime/doc/builtin.txt#L7849-L7853

**Comment by Shane-XB-Qian** [comment]
> When making changes, it should not be seen as a list, but as a tree.  When going back and creating a new entry, it should come next to the existing one.
> A bit like undo history. This might be difficult to navigate though.

'chistory' looks just was plainly displayed (sort) by order..
if it was intended, then
it is impossible to navigate after such 'overwritten'.. aha..

but anyway, if cost too much (and it really was not a bug), then let it be..

-- 
shane.xb.qian
