### ISSUE TITLE
Color schemes after 30ab04e16e1e9e6133590181197b3f8e70cb495e are "broken"

### ISSUE THREAD

**Issue by vp1981** [vim/vim#10449]
### Steps to reproduce

1. Get recent vim
2. Get latest alacritty
3. Run alacritty with transparent background (I'm using picom)
4. Open a file in vim editor with "pablo" color scheme
5. There background used to be transparent.

### Expected behaviour

Before the commit 30ab04e16e1e9e6133590181197b3f8e70cb495e the background for some color scheme (I checked only pablo and ron) was tranparent, because that is how my terminal emulator is configured.

### Version of Vim

8.2.4980

### Environment

Archlinux x86_64
alacritty 0.10.1 and qterminal 1.1.0
bash: 5.1.16(1)
TERM:
alacritty:
```
$ env | grep -i term
COLORTERM=truecolor
TERM=alacritty
$ env | grep -i color
COLORTERM=truecolor
GREP_COLORS=mt=01;33
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=00:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.avif=01;35:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:*~=00;90:*#=00;90:*.bak=00;90:*.old=00;90:*.orig=00;90:*.part=00;90:*.rej=00;90:*.swp=00;90:*.tmp=00;90:*.dpkg-dist=00;90:*.dpkg-old=00;90:*.ucf-dist=00;90:*.ucf-new=00;90:*.ucf-old=00;90:*.rpmnew=00;90:*.rpmorig=00;90:*.rpmsave=00;90:
```
qterminal:
```
$ env | grep -i term
COLORTERM=truecolor
TERM=xterm-256color
$ env | grep -i color
COLORTERM=truecolor
GREP_COLORS=mt=01;33
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=00:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.avif=01;35:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:*~=00;90:*#=00;90:*.bak=00;90:*.old=00;90:*.orig=00;90:*.part=00;90:*.rej=00;90:*.swp=00;90:*.tmp=00;90:*.dpkg-dist=00;90:*.dpkg-old=00;90:*.ucf-dist=00;90:*.ucf-new=00;90:*.ucf-old=00;90:*.rpmnew=00;90:*.rpmorig=00;90:*.rpmsave=00;90:                                                                                                                                                 
TERM=xterm-256color
COLORFGBG=15;0
```

Changing TERM in alacritty to xterm-256color doesn't change nothing.

To illustrate the problem, please see the screenshots

[alacritty (with tgc off)](https://disk.yandex.ru/i/u481NLCs5Y_-UA)

[alacritty (with tgc on)](https://disk.yandex.ru/i/DPsEQhx7-2cJig)

[qterminal (with tgc off)](https://disk.yandex.ru/i/vINBgoViPt2JMQ)

[qterminal (with tgc on)](https://disk.yandex.ru/i/JNTnxhL1Xh1kUQ)

**Comment by chrisbra** [comment]
ping @romainl

**Comment by habamax** [comment]
With remade colorschemes all of them now have explicitly defined Normal colors.

There might be several solutions to this:

1. do not define normal colors for `t_Co=16`
2. provide a setting that would prevent defining normal colors
3. explain how change normal colors in user vimrc to have "transparent" background
4. explain where to take legacy colorschemes for those who prefer old ones https://github.com/vim/colorschemes/pull/168

**Comment by brammool** [comment]
Whether the background should be transparent or not is a user choice.  It has a drastic effect, thus we could even duplicate the set of color schemes to make a transparent version of each.  So we would have "pablo" and "pablo-transp".
In the implementation the common parts of the colorscheme can be shared.  The main disadvantage is making the list twice as long.
An alternative is to use a setting or global variable.

**Comment by romainl** [comment]
Some of the originals specify a background while some others don't so, if transparency is a user choice, then that choice is expressed by choosing a colorscheme without a background.

FWIW, these are the original cases:

## Background defined for GUI and TUI via `Normal`
- blue
- darkblue
- evening
- industry
- morning
- murphy
- shine

## Background defined for GUI only (and "true colors" TUI via `ternguicolors`) via `Normal`
- delek
- desert
- elflord
- koehler
- pablo
- peachpuff
- ron
- slate
- torte
- zellner

## Background not defined via `Normal`
[none]

My opinion: forcing a background color for TUIs seems to go against the design of some of the original colorschemes so we should change the offending remakes.

We may have to adjust `check_colors.vim`.

**Comment by habamax** [comment]
> An alternative is to use a setting or global variable.

Another alternative is to use

```
augroup transparent_bg | au!
    au Colorscheme * hi Normal ctermbg=NONE
augroup END
```

in user vimrc

**Comment by chrisbra** [comment]
Yes, I would think this configured by the user by making use of such an autocommand. That's what they are for after all :)

**Comment by sthen** [comment]
It's not just transparency, I don't use that and many schemes now have a light background instead of dark. Exact behaviour depends on the terminal; for xterm I have a fully coloured light background (so it looks reasonably correct though an unwelcome change to before) or for rxvt-unicode I have a mixture of light background where text is printed (e.g. the message displayed when opening vim with no file) and dark (unprinted lines).

![vim-4950-delek](https://user-images.githubusercontent.com/1006726/169285257-8d326744-dd86-4567-9dce-ecace0c3374b.png)
![vim-4980-delek](https://user-images.githubusercontent.com/1006726/169285275-422d6b2e-7080-43c5-afef-582d4d88e52b.png)

**Comment by habamax** [comment]
delek was meant to be a light colorscheme (as well as morning and several others). With current implementation it should look like this:

![image](https://user-images.githubusercontent.com/234774/169287318-e1f1d49e-60a9-4ece-9637-5b13fc6f9052.png)

(The same as GUI version of delek)

Although in your case, it looks wrong indeed.

**Comment by vp1981** [comment]
@habamax ,
your advice with `augroup` works fine with following settings in `vimrc`:
```
augroup transparent_bg | au!
  au Colorscheme * hi Normal ctermbg=NONE
augroup END
color pablo
```

Don't know why (I have some sort of color blindness) but I think that colors are changed (I'm using `pablo`). Is it true or just my perception?

**Comment by romainl** [comment]
@vp1981 The colors have changed, yes.

We spent months remaking the colorschemes shipped with Vim, which implied, among other things, fixing their color palette so that they offer a more consistent experience across environments. In many cases we had to deal with colorschemes being radically different in color terminals and in GUI. In such cases, we favored the GUI colors because they tended to be the most specific and explicit.

In doing so, we knew from the start that some users who would have gotten used to their colorscheme's brokenness over time would be surprised by the changes and, probably, unhappy. But that's how change goes.

If you are not satisfied with the remakes, you can still grab the originals [over there](https://github.com/vim/colorschemes/tree/master/legacy_colors) and put them in your `colors` directory.

**Comment by vp1981** [comment]
@romainl ,
thank you, then it is not my imagination, now the 'pablo' theme in terminal indeed has different colors for "keywords".

> If you are not satisfied with the remakes, you can still grab the originals [over there](https://github.com/vim/colorschemes/tree/master/legacy_colors) and put them in your colors directory.

I appreciate your work, but choosing colors is a pain for me.

Still, do I understand correctly that if I want to play around with colors in terminal (alacritty), say, for the 'pablo' theme, I should look into settings from the line  https://github.com/vim/colorschemes/blob/master/colors/pablo.vim#L20
to the line 88?

**Comment by chrisbra** [comment]
That is understandable and I would say, if you found a reasonably well working (legacy) color scheme that works well enough for you, I would just grab the old version [pablo](https://github.com/vim/colorschemes/blob/master/legacy_colors/pablo.vim) in this case download it into your `~/.vim/colors` directory and then you should have that solved already. 

Note, I believe creating a good working color scheme for color impacted people (I am also one of those), is also a goal of the colorschemes sub-project, but we are not there yet.

**Comment by romainl** [comment]
@vp1981 you have quite a few options:

- Override the new version with an autocommand like the one you already have. See [this gist](https://gist.github.com/romainl/379904f91fa40533175dfaec4c833f2f) for some more on this approach.
- Make your own copy of the new version and adjust it to your liking.
- Use the [actual template](https://github.com/vim/colorschemes/blob/master/colortemplate/pablo.colortemplate) of the new version, which is a lot more fun than doing it all by hand.
- Grab the original version.

**Comment by brammool** [comment]
> @habamax ,
> your advice with `augroup` works fine with following settings in `vimrc`:
> ```
> augroup transparent_bg | au!
>   au Colorscheme * hi Normal ctermbg=NONE
> augroup END
> color pablo
> ```
> 
> Don't know why (I have some sort of color blindness) but I think that
> colors are changed (I'm using `pablo`). Is it true or just my
> perception?

The section in the help for colorschemes dives into details too quickly.
Let me move the :colorscheme command out of the section about
highlighting and add some high level remarks.

-- 
You can tune a file system, but you can't tuna fish
							-- man tunefs

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by romainl** [comment]
@brammool do you mean that you are going to do those changes in the doc or that they should be done?

**Comment by brammool** [comment]
> @brammool do you mean that you are going to do those changes in the
> doc or that they should be done?

I have made some changes, will send them out soon. Then we can further
improve on top of that.

-- 
Marriage isn't a word.  It's a sentence.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by alepinio** [comment]
After the update, the default color scheme is different from the color scheme `default` or it is just me?

At least for me, once the default color scheme is changed, there is no way to get it back unless you run the app again.

**Comment by romainl** [comment]
@alepinio, we didn't touch `default` or any of the low-level things it relies on. Our work was strictly limited to the *other* colorschemes distributed with Vim.

As for `ron`, it was one of the wildest, least consistent, and most broken of the lot. The remake is how `ron` (and this is true for all of them) should have been made to begin with: with care. To be honest, the original colorschemes were all so sloppily written and broken that they shouldn't have been included in the first place. Including them was a mistake, people got used to the various ways in which they were broken and here we are.

The original `ron` only defined GUI colors so it looked wildly different in GUI Vim and in TUI Vim, where it depended entirely on the terminal's palette anyway, which means that `ron` didn't look the same everywhere. Your `ron` wasn't my `ron`. The remake is based on the highest def information we could put our hands on: the GUI colors found in the original to guarantee a better consistency. **What you get is how `ron` was meant to look, not how it broke in your particular setup**, which, we understand it, might be a radical change.

<img width="1920" alt="ron" src="https://user-images.githubusercontent.com/344335/170815263-98b85adc-9b5f-4918-b08f-f13c3ca1b161.png">

If you prefer the original `ron`, feel free to grab it [here](https://github.com/vim/colorschemes/blob/master/legacy_colors) and put it in `~/.vim/colors/`.

**Comment by Shane-XB-Qian** [comment]
@alepinio recently changes tried to fix `termguicolor` with `transparent` issues, and some builtin colo like above said.
but did not change `default` (vs `builtin`) colo (wish so!), 
~~and looks did not try to fix `termguicolor` with `transparent` in some specific terminal or e.g `gnu-screen`.~~
~~// `termguicolor` and `non-transparent` (`hi normal ctermbg=234`) looks still a bit abnormal in `gnu-screen`.~~
// but just a fyi, seems `gnu-screen` users perhaps more like `default` colo plus no `termguicolor` (no good pc screen or at server)

**Comment by vp1981** [comment]
@craigmac, thanks but it doesn't work for me. I have a transparent (`opacity: 0.9`) background in alacritty and though it is sometimes awkward, I'm used to it. I tried your settings, but I lost the transparency. Besides, new pablo color theme (I tested only it) has very "unpleasant" (for me, please note, I have some kind of color blindness) colors for "Special" and "Identifier" (for example, for `([{}])` and others).

I ended up modifying the new `pablo` theme a bit (reverting old colors for "Special" and "Identifier") and I'm using it in vim (vim runs in terminal, `tmux` and `ssh`).

P.S. I tested your settings in tmux running in alacritty and in just alacritty.

**Comment by chrisbra** [comment]
Note: there is also https://github.com/vim/colorschemes/pull/163 which specifically adresses dyslexia, not sure if this is the same as color blindness

**Comment by vp1981** [comment]
I think it is worth to mention in documentation about possible ways to get desire result. I have settled on the following
```
augroup transparent_bg | au!
  au Colorscheme * hi Normal ctermbg=NONE
augroup END
color pablo-t
```
 in `.vimrc`. The colortheme `pablo-t` is almost the same as new `pablo` but with some differences:
```
$ diff -Naur /usr/share/vim/vim82/colors/pablo.vim ~/.local/share/vim/colors/pablo-t.vim
--- /usr/share/vim/vim82/colors/pablo.vim       2022-05-31 07:44:55.000000000 +0800
+++ ~/.local/share/vim/colors/pablo-t.vim  2022-05-23 13:20:03.589564600 +0800
@@ -1,11 +1,11 @@
-" Name:         pablo
+" Name:         pablo-t
 " Author:       Ron Aaron <ron@ronware.org>
-" Maintainer:   Original maintainerRon Aaron <ron@ronware.org>
+" Maintainer:   Original maintainer Ron Aaron <ron@ronware.org>
 " Website:      https://github.com/vim/colorschemes
 " License:      Same as Vim
-" Last Updated: Wed May 11 22:56:41 2022
+" Last Updated: Wed May 23 08:00:00 2022 UTC

-" Generated by Colortemplate v2.2.0
+" Hand-updated

 set background=dark

@@ -98,10 +98,12 @@
   hi Comment ctermfg=244 ctermbg=NONE cterm=NONE
   hi Constant ctermfg=51 ctermbg=NONE cterm=NONE
   hi Identifier ctermfg=37 ctermbg=NONE cterm=NONE
+  " hi Identifier ctermfg=44 ctermbg=NONE cterm=NONE
   hi Statement ctermfg=142 ctermbg=NONE cterm=NONE
   hi PreProc ctermfg=46 ctermbg=NONE cterm=NONE
   hi Type ctermfg=34 ctermbg=NONE cterm=NONE
-  hi Special ctermfg=21 ctermbg=NONE cterm=NONE
+  " hi Special ctermfg=21 ctermbg=NONE cterm=NONE
+  hi Special ctermfg=63 ctermbg=NONE cterm=NONE
   hi Underlined ctermfg=111 ctermbg=NONE cterm=underline
   hi Ignore ctermfg=16 ctermbg=16 cterm=NONE
   hi Error ctermfg=231 ctermbg=196 cterm=NONE
```

**Comment by romainl** [comment]
@vp1981…

> I think it is worth to mention in documentation about possible ways to get desire result.

Bram is on it.

> `Identifier` from 37 to 44

That is a sensible change because 44 (#00d7d7) is closer to the intended #00c0c0 than 37 (#00afaf). You should make a PR in [vim/colorschemes](https://github.com/vim/colorschemes/pulls) using the actual template.

> `Special` from 21 to 63

The intended color is #0000ff so 21 is the correct value. While #5f5fff is closer to the xterm default I think we should keep the intended color.

**Comment by vp1981** [comment]
@brammool , yes, thank you! Brilliant solution, I like it and am using it now.

@romainl , Bram's code makes more sense to me than this
```
augroup my_colors
    autocmd!
    autocmd Colorscheme * highlight Normal ctermbg=NONE
                      \ | higlight Special ctermfg=63
                      \ | highlight Identifier ctermfg=44
augroup END
```
because and I don't understand where this `my_colors` is applied. Nevertheless, I think both do the same thing.

**Comment by michael-o** [comment]
FWIW: OpenBSD ports [now install old color schemes by default](https://github.com/openbsd/ports/commit/3a6f08dc225430915e0caca3a7dba17f98f142ae) since this is too abruptive. I have made the [same request](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=265798) for FreeBSD ports as well. I am totally *not* happy with my beloved `slate`.

**Comment by chrisbra** [comment]
Is this just because of the Normal highlighting group? Or what exactly is the problem?

**Comment by habamax** [comment]
> Is this just because of the Normal highlighting group? Or what exactly is the problem?

Many (all?) legacy colorschemes were using first 16 colors no matter if there is 256 color support in the terminal. This is the reason slate was different to almost everyone. Blue statement was a different blue statement depending on the terminal definition of the blue.
And of course the normal group is now also defined, overriding terminal bg.

**Comment by habamax** [comment]
I believe if @michael-o would put `set t_Co=16` into vimrc, it would be almost identical to legacy slate. Plus of course `hi Normal ctermbg=NONE` in the `Colorscheme` autocommand.

**Comment by michael-o** [comment]
This is now it looks for me:

HP-UX with 8.2.5173:
new slate:
![grafik](https://user-images.githubusercontent.com/573017/184415464-e79e26ba-fa34-4ed6-b69d-26395e268711.png)
legacy slate:
![grafik](https://user-images.githubusercontent.com/573017/184415521-645144d0-ccc7-43f8-9907-22d15e3108f6.png)

FreeBSD with 9.0.16:
new slate:
![grafik](https://user-images.githubusercontent.com/573017/184415643-ab2bbf35-c46f-43a3-8460-a03168cc6c04.png)
legacy slate:
![grafik](https://user-images.githubusercontent.com/573017/184415743-ba859fa4-f6b4-42cc-ab84-2b2f7157a6b5.png)

That's just for C. Java source code is worse.

**Comment by romainl** [comment]
Here is a perfect example of the incoherent mess we had to deal with, taken from legacy slate:

    :hi Comment term=bold ctermfg=11 guifg=grey40

Of note:

- the author chose to use a "lightyellow" for comments in terminals and a dark grey in GUI,
- comments in your "legacy slate" screenshots are not even the designed "lightyellow" to begin with and, in one of them, you even have an inexplicable red background.

Your "beloved slate" didn't even look the same on two machines accessed from the same terminal emulator. It has always been broken. The new slate at least looks the same everywhere, that's quite the improvement

The design choice in the new slate are dictated by the most hi-def "source of trust" we could find: the GUI colors defined in the original slate itself, which inevitably impacts your terminal experience. That is a trade-off we chose to make in the name of consistency.

Reverting new slate to the hot mess that was legacy slate is, IMO, not going to happen. That's why we preserved the legacy colorschemes.

But there are definitely mistakes in new slate, like `PreProc` being magenta instead of red. Those need to be fixed. Could you open a separate issue so that we can fix what can be fixed in new slate?

**Comment by lifepillar** [comment]
@michael-o Are you sure `t_Co` is 256 in your screenshots? Definitely, comments are yellow in my FreeBSD server if I load the legacy slate:

<img width="513" alt="Screenshot 2022-08-13 at 10 22 05" src="https://user-images.githubusercontent.com/1193314/184473597-6e9de64f-e66e-4b6a-a7d2-39857c0e6294.png">

>Both systems are solely accessed by PuTTY on Windows.

This may be the reason.

That said, I agree that the new color schemes are “disruptive”, but in a positive way. I am all for backward compatibility, but insisting on keeping 20th century's broken behavior for the sake of compatibility is silly.

For instance, to test the above, I first loaded legacy slate from my terminal, which has a light background. Of course, the color scheme was unusable, because it was meant to be used with a terminal's dark background.  With the new slate, this is a non-issue. And it is just one of the countless improvements people working on the new color schemes have made.

**Comment by Shane-XB-Qian** [comment]
why not just gave another indicating name?
e.g `slate-256`
// maybe `silly` but people used to that :-)
// though separated to new name, but I guess it is unlike py2 vs py3.

--
shane.xb.qian

**Comment by lifepillar** [comment]
>why not just gave another indicating name?

That would have doubled the number of color schemes and might have been confusing for many users.

>// maybe `silly` but people used to that :-)

Maybe the legacy color schemes could be put in `pack/dist/opt/legacycolors`. You would just need `packadd legacycolors` then.

**Comment by michael-o** [comment]
> Here is a perfect example of the incoherent mess we had to deal with, taken from legacy slate:
> 
> ```
> :hi Comment term=bold ctermfg=11 guifg=grey40
> ```
> 
> Of note:
> 
>     * the author chose to use a "lightyellow" for comments in terminals and a dark grey in GUI,
> 
>     * comments in your "legacy slate" screenshots are not even the designed "lightyellow" to begin with and, in one of them, you even have an inexplicable red background.
> 
> 
> Your "beloved slate" didn't even look the same on two machines accessed from the same terminal emulator. It has always been broken. The new slate at least looks the same everywhere, that's quite the improvement
> 
> The design choice in the new slate are dictated by the most hi-def "source of trust" we could find: the GUI colors defined in the original slate itself, which inevitably impacts your terminal experience. That is a trade-off we chose to make in the name of consistency.
> 
> Reverting new slate to the hot mess that was legacy slate is, IMO, not going to happen. That's why we preserved the legacy colorschemes.
> 
> But there are definitely mistakes in new slate, like `PreProc` being magenta instead of red. Those need to be fixed. Could you open a separate issue so that we can fix what can be fixed in new slate?

I totally appreciate your work, do understand the mess and don't expect to revert. I think it was the right think to do, but should have been done in 9 with accompanying text.

**Comment by michael-o** [comment]
> @michael-o Are you sure `t_Co` is 256 in your screenshots? Definitely, comments are yellow in my FreeBSD server if I load the legacy slate:
> 
> <img alt="Screenshot 2022-08-13 at 10 22 05" width="513" src="https://user-images.githubusercontent.com/1193314/184473597-6e9de64f-e66e-4b6a-a7d2-39857c0e6294.png">
> 
> > Both systems are solely accessed by PuTTY on Windows.
> 
> This may be the reason.
> 
> That said, I agree that the new color schemes are “disruptive”, but in a positive way. I am all for backward compatibility, but insisting on keeping 20th century's broken behavior for the sake of compatibility is silly.
> 
> For instance, to test the above, I first loaded legacy slate from my terminal, which has a light background. Of course, the color scheme was unusable, because it was meant to be used with a terminal's dark background. With the new slate, this is a non-issue. And it is just one of the countless improvements people working on the new color schemes have made.

Well, with PuTTY, both OSes show my t_Co=8. I have then tried from Windows Terminal with PowerShell 7 and OpenSSH 8.9 to connect to both machines. Completely different. FreeBSD is now at t_Co=256 and HP-UX is just black and white because `TERM` is set to xterm-256color which does not exist on HP-UX. I guess it is a combination of multiple factors which leads to inconsistent behavior even with new color schemes since new slate still looks different depending on terminal and OS.

**Comment by neutaaaaan** [comment]
> I totally appreciate your work, do understand the mess and don't expect to revert. I think it was the right think to do, but should have been done in 9 with accompanying text.

This would arguably have been much worse: few people read the documentation, a lot of people have oddball setups, and we'd have drowned under both justified and unjustified bug reports. Later down the line, some linux distributions might have decided to ship vim9.0 with cherry-picked security fixes but none of the runtime updates that would have fixed issues with the colorschemes.

There's no way to do it that doesn't involve some amount of pain, but updating the runtime so that early adopters could report potential issues and give us the opportunity to fix them before a major release was the right call.

**Comment by michael-o** [comment]
> > I totally appreciate your work, do understand the mess and don't expect to revert. I think it was the right think to do, but should have been done in 9 with accompanying text.
> 
> This would arguably have been much worse: few people read the documentation, a lot of people have oddball setups, and we'd have drowned under both justified and unjustified bug reports. Later down the line, some linux distributions might have decided to ship vim9.0 with cherry-picked security fixes but none of the runtime updates that would have fixed issues with the colorschemes.
> 
> There's no way to do it that doesn't involve some amount of pain, but updating the runtime so that early adopters could report potential issues and give us the opportunity to fix them before a major release was the right call.

Right. Whatever you do you do it wrong.

**Comment by habamax** [comment]
@michael-o there is some work going on https://github.com/vim/colorschemes/issues/207

I have aligned as much as I could TUI 8/16 colors between legacy and new slate.
For GUI/256 I will wait until there would be a decision that would make it "proof" of next pack of people asking to make it like it was before.

**Comment by Zemke** [comment]
This made me learn why it’s called peachpuff. Oh dear, the background is peach!
After all one can only commend the fixing of the color schemes. Has definitely ruined peachpuff for me but I knew I was caught in the act of being stubborn when I found the related [xkcd](https://xkcd.com/1172/).
