### ISSUE TITLE
Faster unfiltered tags access

### ISSUE THREAD

**Issue by LucHermitte** [vim/vim#1044]
Sometimes I need to obtain all tags and I don't care to filter them on their name. Sometimes I filter them on the kind, on the visibility, or I may don't even want to filter anything. Thus I do a `taglist('.*')`.

Unfortunately this is very slow on huge tags bases (the one I'm working with has around 100000 entries). And yet a `readfile()` on the tag file, or a `readfile('somepattern')` are really fast..

I don't think I've missed a new feature (I see nothing new in `taglist()` documentation in v7.4-2330.).

Could we have overloads like `taglist()`, (or even `taglist({val -> val.kind == 'f'})` for other use cases)?

**Comment by jamessan** [comment]
Yeah, the delay here is actually the call to [line_breakcheck](https://github.com/vim/vim/blob/1b0c2fcf6e85c9b85c24757ba970061e1f3e4e80/src/tag.c#L1581) in `find_tags`.  For small tag files, it's not noticeable but when you have large tag files, the delay introduced by the call to `select()` really adds up.

Unfortunately, adding a filter to `taglist()` won't help this because the `select()` call is in the code that parse the tags file itself.

I've brought this up before, although in a broader discussion about signal handling.  Thanks for creating a distinct issue to track it.

**Comment by vim-ml** [comment]
Am 2016-09-06 15:32, schrieb James McCoy:

> Yeah, the delay here is actually the call to line_breakcheck [1] in
> find_tags. For small tag files, it's not noticeable but when you have
> large tag files, the delay introduced by the call to select() really
> adds up.
> 
> Unfortunately, adding a filter to taglist() won't help this because
> the select() call is in the code that parse the tags file itself.
> 
> I've brought this up before, although in a broader discussion about
> signal handling. Thanks for creating a distinct issue to track it.

So woudln't fast_breakcheck() at least alleviate the problem then?

Best,
Christian

**Comment by jamessan** [comment]
> So woudln't fast_breakcheck() at least alleviate the problem then?

That's the first thing I tried when I first heard about the issue.  Looking again, though, the line_breakcheck call at the top of the for loop isn't the main problem.  It's the one that handles [deduplicating](https://github.com/vim/vim/blob/1b0c2fcf6e85c9b85c24757ba970061e1f3e4e80/src/tag.c#L2400) the tag matches.

A simple way to reproduce the problem is to build a tags file including all of /usr/include.

``` sh
$ ctags -R /usr/include
$ vim -u NONE -c 'call taglist("a")' -cq
```

Using [gperftools](https://github.com/gperftools/gperftools), here's the CPU profile for running the above on vanilla 7.4.2334.

```
(pprof) top 
Total: 14427 samples
    7822  54.2%  54.2%     7822  54.2% __select
    5154  35.7%  89.9%    14090  97.7% find_tags
     731   5.1%  95.0%     8646  59.9% RealWaitForChar.isra.1
     433   3.0%  98.0%      433   3.0% line_breakcheck
      71   0.5%  98.5%       71   0.5% channel_select_setup
      46   0.3%  98.8%       56   0.4% _init
      37   0.3%  99.1%       37   0.3% channel_fill_wfds
      31   0.2%  99.3%       31   0.2% __nss_passwd_lookup
      31   0.2%  99.5%     8675  60.1% mch_breakcheck
      12   0.1%  99.6%       19   0.1% vim_strchr
```

Changing both line_breakcheck calls to fast_breakcheck makes the profile look like

```
(pprof) top
Total: 6253 samples
    4783  76.5%  76.5%     5999  95.9% find_tags
     850  13.6%  90.1%      850  13.6% __select
     422   6.7%  96.8%      422   6.7% fast_breakcheck
      77   1.2%  98.1%      934  14.9% RealWaitForChar.isra.1
      37   0.6%  98.7%       37   0.6% __nss_passwd_lookup
      14   0.2%  98.9%       14   0.2% __fdelt_warn
       9   0.1%  99.0%       23   0.4% _init
       8   0.1%  99.2%       10   0.2% vim_strchr
       6   0.1%  99.2%        6   0.1% channel_select_setup
       6   0.1%  99.3%        6   0.1% strerror_l
```

That's certainly better, but it still takes a significant amount of time to get the results back.  Using a hashtab_T instead of a garray_T to store the results could help since the cost of deduplication would be much cheaper.

I've tested the use of hashtab_T (PR coming soon) and these are the prof results:

```
(pprof) top
Total: 77 samples
      20  26.0%  26.0%       20  26.0% utfc_ptr2len
      10  13.0%  39.0%       28  36.4% vim_strchr
       6   7.8%  46.8%        6   7.8% tag_hash
       4   5.2%  51.9%       17  22.1% add_tag_field
       4   5.2%  57.1%       10  13.0% skip_regexp
       4   5.2%  62.3%        4   5.2% strerror_l
       3   3.9%  66.2%        3   3.9% hash_lookup
       2   2.6%  68.8%        5   6.5% dict_free_contents
       2   2.6%  71.4%        3   3.9% hash_add
       2   2.6%  74.0%        2   2.6% hash_may_resize
```

**Comment by vim-ml** [comment]
Hi James!

On Di, 06 Sep 2016, James McCoy wrote:

> > So woudln't fast_breakcheck() at least alleviate the problem then?
> 
> That's the first thing I tried when I first heard about the issue.  Looking again, though, the line_breakcheck call at the top of the for loop isn't the main problem.  It's the one that handles [deduplicating] the tag matches.
> 
> A simple way to reproduce the problem is to build a tags file including all of /usr/include.
> 
> ``` sh
> $ ctags -R /usr/include
> $ vim -u NONE -c 'call taglist("a")' -cq
> ```
> 
> Using [gperftools], here's the CPU profile for running the above on vanilla 7.4.2334.
> 
> ```
> (pprof) top 
> Total: 14427 samples
>     7822  54.2%  54.2%     7822  54.2% __select
>     5154  35.7%  89.9%    14090  97.7% find_tags
>      731   5.1%  95.0%     8646  59.9% RealWaitForChar.isra.1
>      433   3.0%  98.0%      433   3.0% line_breakcheck
>       71   0.5%  98.5%       71   0.5% channel_select_setup
>       46   0.3%  98.8%       56   0.4% _init
>       37   0.3%  99.1%       37   0.3% channel_fill_wfds
>       31   0.2%  99.3%       31   0.2% __nss_passwd_lookup
>       31   0.2%  99.5%     8675  60.1% mch_breakcheck
>       12   0.1%  99.6%       19   0.1% vim_strchr
> ```
> 
> Changing both line_breakcheck calls to fast_breakcheck makes the profile look like
> 
> ```
> (pprof) top
> Total: 6253 samples
>     4783  76.5%  76.5%     5999  95.9% find_tags
>      850  13.6%  90.1%      850  13.6% __select
>      422   6.7%  96.8%      422   6.7% fast_breakcheck
>       77   1.2%  98.1%      934  14.9% RealWaitForChar.isra.1
>       37   0.6%  98.7%       37   0.6% __nss_passwd_lookup
>       14   0.2%  98.9%       14   0.2% __fdelt_warn
>        9   0.1%  99.0%       23   0.4% _init
>        8   0.1%  99.2%       10   0.2% vim_strchr
>        6   0.1%  99.2%        6   0.1% channel_select_setup
>        6   0.1%  99.3%        6   0.1% strerror_l
> ```
> 
> That's certainly better, but it still takes a significant amount of time to get the results back.  Using a hashtab_T instead of a garray_T to store the results could help since the cost of deduplication would be much cheaper.
> 
> I've tested the use of hashtab_T (PR coming soon) and these are the prof results:
> 
> ```
> (pprof) top
> Total: 77 samples
>       20  26.0%  26.0%       20  26.0% utfc_ptr2len
>       10  13.0%  39.0%       28  36.4% vim_strchr
>        6   7.8%  46.8%        6   7.8% tag_hash
>        4   5.2%  51.9%       17  22.1% add_tag_field
>        4   5.2%  57.1%       10  13.0% skip_regexp
>        4   5.2%  62.3%        4   5.2% strerror_l
>        3   3.9%  66.2%        3   3.9% hash_lookup
>        2   2.6%  68.8%        5   6.5% dict_free_contents
>        2   2.6%  71.4%        3   3.9% hash_add
>        2   2.6%  74.0%        2   2.6% hash_may_resize
> ```
> 
> [deduplicating]: https://github.com/vim/vim/blob/1b0c2fcf6e85c9b85c24757ba970061e1f3e4e80/src/tag.c#L2400
> [gperftools]: https://github.com/gperftools/gperftools

That indeed looks very promising!

Best,

## Christian

Gott denkt in den Genies, träumt in den Dichtern und schläft in den
übrigen Menschen.
        -- Peter Altenberg

**Comment by LucHermitte** [comment]
Thank you for the quick patch. Unfortunately, this is still quite slow. I guess I'll to wait for jamessan patch.

Instead of 2minutes (IIRC, I'm not 100% certain), it takes now 85seconds. Which is really big compared to the 0.9s I take with:

``` vim
" In this particular use case, I only care for tag names. In others, I need to filter based of fields
function! s:getNames_Emulation(tagfile)
  let lines = readfile(a:tagfile)
  let first_tag = match(lines, '!empty(v:val) && v:val[0]!="!"')
  return map(lines[ : first_tag ], 'v:val[0 : stridx(v:val, "\t")-1]')

  " instead of
  let tags = tagslist('.*')
  let names = map(copy(tags), 'get(v:val, "name")')
endfunction
```
