### ISSUE TITLE
Doubling or trebling of syntax group names in syntax commands

### ISSUE THREAD

**Issue by zzzyxwvut** [vim/vim#10458]
Please shed some light on an undocumented pattern of
doubling or trebling of syntax group names in syntax
commands.

E.g.,
```vim
syn match words "\<hello\>"
syn match words "\<world\>"
syn cluster text add=words,words
```
A handful of instances of similar application could be
collected from the distributed [syntax files](https://github.com/vim/vim/tree/master/runtime/syntax "syntax files") with  
the following [`awk` script](https://gist.github.com/zzzyxwvut/76dc7e7c07a31c2783fa303cdd634afe).

(See the description of the output format in the script's
header.)

**Comment by chrisbra** [comment]
Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. Closing.

**Comment by zzzyxwvut** [comment]
A question relating to this issue had already been [asked](https://vi.stackexchange.com/questions/37507/what-is-the-significance-of-duplicating-syntax-group-name-references)  
and it was advised to try the mailing list or the issue  
tracker; however, the overview page for the [mailing list](https://www.vim.org/maillist.php)  
is reticent about how should one _earn_ an invitation.

Admittedly, the description of this issue may rather seem  
user-oriented, but the intent is to bring to attention  
a recurring pattern that appear in a handful of syntax  
files for which, I believe, there is no documented  
explanation (if so, let's draft one in [syntax.txt](https://vimhelp.org/syntax.txt.html)). On  
the other hand, if this pattern is bogus, well, let's  
make relevant maintainers aware of it.

**Comment by benknoble** [comment]
Agreed; this should be re-opened. It’s not a “use question” unless the answer is “there’s a documented reason X” and I’m not aware of one.

**Comment by brammool** [comment]
There is nothing to document.  This syntax file simply adds "words" to the cluster twice, which has no other effect than adding it once.  Looks like this happens because of the way the syntax file was generated.

**Comment by zzzyxwvut** [comment]
Thank you, Bram, for the definitive clarification.

So, I have e-mailed the relevant maintainers (according to  
the findings of the [`awk` script](https://gist.github.com/zzzyxwvut/76dc7e7c07a31c2783fa303cdd634afe)), inviting each to take  
a look at this conversation and to consider weeding out  
duplicated group-name _references_ from the owned syntax  
files.
