### ISSUE TITLE
Let vim start in Termdebug mode, passing arguments to GDB 

### ISSUE THREAD

**Issue by GitMensch** [vim/vim#10456]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
I've used vim in the past to directly start a debugging session (mostly the "end handling" is missing, see #10301).
This is "bit more" hard than it may should be as you need to specify everything on the command line for vim:

    vim -c'packadd termdebug' -c 'Termdebug vim my.core -ix my_ext.py -ex up-silently -ex bt' -c 'call TermDebugSendCommand("f 0")'

Explanation: The `up-silently`, which can be done during the startup and the `f 0` which needs to be done afterwards are currently necessary to create frame selection note in the communication buffer which is the resolved to the file; if this could be done directly after the start that would be useful (it would help and those two could be dropped).

**Describe the solution you'd like**
A way to directly start vim in Termdebug mode, passing all commands after a command directly to gdb, something like

    vim -c'packadd termdebug' -c 'TermdebugRun' --  vim my.core -ix my_ext.py -ex bt

**Describe alternatives you've considered**
Manual approach as outlined above. Note this does not work with tools that call an "external debugger".
... additional thought: I may could write a wrapper script...

**Additional context**
Tools that start an external debugger like `coredumpctrl dump` execute the debugger, its arguments and then add to those.
Example:

    coredumpctl debug --debugger=vim --debugger-arguments="-c 'packadd termdebug' -c Termdebug -ix my_ext.py -ex up-silently -ex bt"

results in the following call:

    vim -c packadd termdebug -c Termdebug -ix my_ext.py -ex up-silently -ex bt /path/to/my/prog -c /var/tmp/coredump-xWyJAg

**Comment by brammool** [comment]
``Hmm, there would be several ways Termdebug could be started.
For different users there will be different commonly used ways.
What you could do is create a user command that does what you want.
Then you can use ```vim -c "RunTermDebug some `args"```
You could do this in your .vimrc file or in a plugin.
`

**Comment by GitMensch** [comment]
The user command is a good idea which I should tinker with a bit.
That alone won't work for the call from external processes "as gdb" as those pass a bunch of GDB options _after_ all options used, which is the reason for something like "--" that would mean "everything after: attach to GDB starting commands. But that's a very special case and creating a wrapper script for this looks to be not too complicated, I'll give that a go and upload it here, closing the issue because of that.

One thing though: do you have an idea how to position on the actual file directly after Termdebug without those "nasty" calls?
