### ISSUE TITLE
Bad selection when change text of other buffer on select mode

### ISSUE THREAD

**Issue by chemzqm** [vim/vim#10466]
### Steps to reproduce

Create file m.vim
```vim
call setline(1, ['foo', 'bar'])
call feedkeys("j^v2l\<C-G>", 'n')

function! CreateBuffer() abort
  let bufnr = bufadd('')
  call bufload(bufnr)
  call setbufline(bufnr, 1, ['abc'])
endfunction

call timer_start(10, { -> CreateBuffer()})
```
Open vim and `source m.vim`

### Expected behaviour

Only the second line should be selected, but the change makes vim select from the beginning of the file.

Bug happens vim >= 8.2.4969

### Version of Vim

8.2.4991

### Environment

Reproduced on Linux and Macos

**Comment by chrisbra** [comment]
so are you saying, https://github.com/vim/vim/releases/tag/v8.2.4969 is causing this?

**Comment by chemzqm** [comment]
Yes

**Comment by chemzqm** [comment]
> so are you saying, https://github.com/vim/vim/releases/tag/v8.2.4969 is causing this?

Yes
