### ISSUE TITLE
vimdiff ignore diff part after first null byte

### ISSUE THREAD

**Issue by user202729** [vim/vim#10468]
### Steps to reproduce

1. Create file `a` with content

    ```
    1
    2
    3
    4
    5
    6
    ^@
    1
    2
    3
    4
    5
    6
    ```

    and file `b` with content

    ```
    1
    2
    3
    4
    5
    ^@
    1
    2
    3
    4
    5
    ```
    
    (where `^@` is a literal null byte)

2. Run `vimdiff a b` with `diffexpr` empty

### Expected behaviour

The 2 extra lines with `6` in `a` is pointed out. (currently only the first one is)

(there's a workaround by setting the diffexpr equal to the one suggested in the help file that is "almost identical" to the default)

### Version of Vim

8.2.2891

### Environment

Arch Linux, xterm, bash

**Comment by zeertzjq** [comment]
Already fixed by <https://github.com/vim/vim/commit/06f6095623cfcc72da08748c058d13b465652fd4>?
