### ISSUE TITLE
[syntax/cpp.vim] Different scientific notation colornig between 'E' and 'e'

### ISSUE THREAD

**Issue by xvim64** [vim/vim#10470]
### Steps to reproduce

```
#include <stdio.h>
int main()
{
	// Different Colorings bewteen 'E' and 'e'
	double d1 = 19.3E10;
	double d2 = 19.3e10;
	double d3 = 19E10;
	double d4 = 19e10;
	return 0;
}
```

![1](https://user-images.githubusercontent.com/83569599/169738786-8980de9e-6d4f-46cc-afe5-bc9a03cdb86f.png)

'e' to '[eE]' in 'syntax/cpp.vim'
![2](https://user-images.githubusercontent.com/83569599/169738787-7cd4032b-52dd-44f0-8ea4-76fcfa14bcc1.png)
![3](https://user-images.githubusercontent.com/83569599/169738791-72ac2fc1-9533-483a-b0f5-4cc5a9d109be.png)

![4](https://user-images.githubusercontent.com/83569599/169738793-712fe1dc-ef83-4173-8173-5412b0cc6546.png)

### Expected behaviour

the same syntax coloring of 19.3E10 and 19.3e10

### Version of Vim

8.2.5006

### Environment

Windows 10 64bit

**Comment by k-takata** [comment]
Could you create a PR here? https://github.com/vim-jp/vim-cpp

**Comment by chrisbra** [comment]
Ticket created at https://github.com/vim-jp/vim-cpp/issues/62 so let's close it here
