### ISSUE TITLE
Vim exits non-zero in ex mode when there was a (caught) exception

### ISSUE THREAD

**Issue by blueyed** [vim/vim#1048]
TEST CASE:

```
vim -es -u NONE -c 'try | call doesnotexist() | catch | endtry' +q; echo $?
```

This should output 0, but prints 1.

This is unfortunate, since the return status is important when Vim is used to run tests, e.g. using Vader, and `-es` seems to be useful in that regard when run on CI (with regard to not messing with the output).

**Comment by chrisbra** [comment]
Here is your answer:

``` c

      /* When running in Ex mode an error causes us to exit with a non-zero exit
       * code.  POSIX requires this, although it's not 100% clear from the
       * standard. */
      if (exmode_active)
          exitval += ex_exitval;
```

So don't use `-es` then.

**Comment by chrisbra** [comment]
Hm, thinking some more, I think, it may be reasonable to reset ex_exitval.

something like this perhaps:

``` patch
diff --git a/src/ex_docmd.c b/src/ex_docmd.c
index 6802b8b..52140d6 100644
--- a/src/ex_docmd.c
+++ b/src/ex_docmd.c
@@ -1419,6 +1419,8 @@ do_cmdline(
                emsg(p);
                vim_free(p);
            }
+           /* emsg may set ex_exitval, reset here */
+           ex_exitval = 0;
            vim_free(sourcing_name);
            sourcing_name = saved_sourcing_name;
            sourcing_lnum = saved_sourcing_lnum;
```

**Comment by blueyed** [comment]
Fixed by https://github.com/vim/vim/commit/2b7bc567b9238aaac682236cb4f727d0376e1302.
Thanks.

**Comment by wsdjeg** [comment]
@blueyed Hi, thank you for working on this issue, is it possible to avoid this error in old version of vim? currentlly all my test for old vim is failed. https://github.com/SpaceVim/SpaceVim/pull/4636
