### ISSUE TITLE
Repeat `.` not working for `T`operator

### ISSUE THREAD

**Issue by ttytm** [vim/vim#10488]
### Steps to reproduce

E.g., try to repleat a delete `dT<char>`  `.` . Last capital T action won't be triggered when using repeat. 

### Expected behaviour

Repeat works like it does with other operators like  `F`

### Version of Vim

several

### Environment

Linux several

**Comment by habamax** [comment]
FWIW, it is triggered and deletes nothing as cursor stays just before the `<char>` so there is nothing to delete.

**Comment by brammool** [comment]
The repeat does the same again, thus if the cursor is just after <char> then nothing happens.
You need to move the cursor, the the repeat with dot works.
