### ISSUE TITLE
popup-windows: stuck in terminal-popup when 'NONE' is passed to term_start()

### ISSUE THREAD

**Issue by bfrg** [vim/vim#10498]
### Steps to reproduce

1. Run `vim --clean -c 'call term_start("NONE", {"hidden": 1})->popup_create({"border": []})'`.
2. Result: There is no way to get out of the popup window other than with `<c-w>N:qa!`.

### Expected behaviour

It is probably not useful to allow running `NONE` in a popup-terminal and should therefore be disabled.

### Version of Vim

8.2.5037

### Environment

Linux

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> 1. Run `vim --clean -c 'call term_start("NONE", {"hidden": 1})->popup_create({"border": []})'`.
> 2. Result: There is no way to get out of the popup window other than with `<c-w>N:qa!`.
> 
> 
> ### Expected behaviour
> 
> It is probably not useful to allow running `NONE` in a popup-terminal
> and should probably be disabled.

Unless a command is started in that terminal in some way.  Anyway, if
this doesn't work then don't use it...

If this happens accidentally somehow we run into the protection that
most commands are not allowed.  I think we can allow closing the window
if there is no job running.  That would be with CTRL-W :quit CR

-- 
Futility Factor: No experiment is ever a complete failure - it can always
serve as a negative example.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
