### ISSUE TITLE
Static analysis report

### ISSUE THREAD

**Issue by clearissimple** [vim/vim#1049]
[analysisres.zip](https://github.com/vim/vim/files/462328/analysisres.zip)

Attached is the static analysis report produced by the clang static analyzer.
The analysis was run on revision 169ebb0 (HEAD -> master, tag: v7.4.2344)

The report lists 78 potential bugs including possible null pointer dereferencing, dead assignments, and use of possibly uninitialized values. These could be false positives, but someone could take a look on the off chance they are not.

Vim was configured with
`./configure --prefix=/home/local/vim --with-features=huge --enable-fail-if-missing --enable-pythoninterp=yes --enable-python3interp=yes --enable-gui`

**Comment by brammool** [comment]
This is not in a useful format.

**Comment by vim-ml** [comment]
Bram Moolenaar vim-dev-github@256bit.org wrote:

> This is not in a useful format.

The format looks OK to me.  Just unzip the file and open the index.html
file in a browser. I have not had the time to look at the reports yet though,
but I will look later.

Dominique

**Comment by chrisbra** [comment]
How did you create that report?

**Comment by vim-ml** [comment]
Hi Christian,

On Fri, Sep 9, 2016 at 12:08 AM, Christian Brabandt
vim-dev-github@256bit.org wrote:

> How did you create that report?

I use the following steps to run static analysis using the clang
static analyzer (http://clang-analyzer.llvm.org/)

$ scan-build -o /tmp/vim_report ./configure --with-features=huge
$ scan-build -o /tmp/vim_report make
- Yegappan

**Comment by clearissimple** [comment]
Running `configure` through `scan-build` failed for me. I produced the report with this:

```
$ ./configure --prefix=/home/local/vim --with-features=huge --enable-fail-if-missing --enable-pythoninterp=yes --enable-python3interp=yes --enable-gui
$ ~/checker-278/bin/scan-build --use-analyzer /path/to/clang make
```

I used a local clang installation for analysis, as it's more recent than the version provided in the checker zip-file.
