### ISSUE TITLE
[help] proposal for `:h popup-examples`

### ISSUE THREAD

**Issue by matveyt** [vim/vim#10499]
This is my proposal for `:h popup-examples` to include.

The typical problem when using `popup_menu()` is that the caller has to provide a different callback every time. That is, to choose from, say, colorscheme list the caller must implement a callback that checks resulting value; then builds up "colorscheme" command; then executes it. Another one for "buffers" list etc.etc. No code can be reused, as the selection result is only available inside callback function.

So the idea is that the caller can pass instead a string for evaluation by internal lambda (with respect to local variables) and only then execution. This could be implemented either by `substitute(..., '\=eval(submatch(...)', ...)`,  or by new-defined "interpolated strings".

A sketch for help page with code examples follows.

```vimhelp
					*popup_pick-example*
This is an example of how to make |popup-callback| to execute arbitrary
command parameterized by user's choice.

The function accepts both items |List| to display and a command |String| to
execute if user chooses an item. A command will be evaluated before executing
as if being |interp-string| in the context of the callback. This allows for a
caller to reference all locals (including selection index) from outside. >

	" Pick({title} [, {cmd} [, {items} [, {items2lines}]]])
	" let user choose one of {items} and execute {cmd}
	"	{title} is popup title; |String|
	"	{cmd} is a command to execute; |String|
	"	{items} is a list to choose from; |List|
	"	{items2lines} is optional expression to |map()| {items} to
	"		{lines} displayed by popup; useful when {items} are not
	"		strings; |String| or |Funcref|
	func Pick(title,
		\ cmd = '{title} {items[result - 1]}',
		\ items = getcompletion(a:title..' ', 'cmdline'),
		\ i2l = v:none)

		" copy args to locals to access them without prefixing with
		" |variable-scope|
		let [title, cmd, items] = [a:title, a:cmd, a:items]
		let lines = empty(a:i2l) ? items : mapnew(items, a:i2l)

	return lines->popup_menu(#{
		\ title: title->printf('[ %s ]'),
		\ maxheight: &pumheight ?? &lines / 2,
		\ minwidth: &pumwidth,
		\ callback: {id, result -> (1 <= result && result <= len(items)) ?
		\	eval('$'..string(cmd))->execute('') : v:none}
		\ })
	endfunc
<
Some applications for this code:

set new |:colorscheme| >
	call Pick('colorscheme')
<
edit an item from |argument-list| >
	call Pick('args', '{result}argument', argv())
<
edit one of previously sourced scripts |:scriptnames| >
	call Pick('scriptnames', '{result}{title}',
		\ execute('scriptnames')->split("\n"), 'v:val[1:]')
<
edit a buffer from |buffers| list >
	call Pick('buffer', '{title} {items[result - 1].bufnr}', getbufinfo(#{buflisted: 1}),
		\ {_, v -> printf('%2d %s', v.bufnr,
		\	v.name->fnamemodify(':t') ?? gettext('[No Name]'))
		\ })
<
```

**Comment by errael** [comment]
Would using vim9script avoid some of the problems mentioned and/or simplify the example?

**Comment by matveyt** [comment]
@errael All examples from this section are in legacy script anyway. In Vim9Script there's no need for `a:` variable-scope and ugly line-continuations, but otherwise it would make no much difference.

**Comment by lacygoill** [comment]
> Upd. Okay, I admit, I don't know what is the current status/limitations of eval() in vim9script.

When `eval()`, `:eval`, `execute()` or `:execute` is called, Vim can not access items from the function:
```vim
vim9script
def Func()
    var n = '123'
    echomsg eval('n')
enddef
Func()
```
    E121: Undefined variable: n

That's because `n` is compiled, but the code run by `eval()` is not:

   > It is simply not possible to access the compiled code and variables from interpreted code.

[source](https://github.com/vim/vim/issues/7541#issuecomment-751274709)

The closest scope `eval()` can access is the script one:
```vim
vim9script
var n = '123'
def Func()
    echomsg eval('n')
enddef
Func()
```
    no error

One possible workaround would be to make a copy of the variables from the function namespace to the script one, at runtime.  And make sure `eval()` evaluates the latter, not the former.

**Comment by matveyt** [comment]
>The closest scope eval() can access is the script one

Ah, then we'd better avoid porting the code. Perhaps, it makes sense to add also a note that it is a feature of legacy script only to access locals by string evaluation. I see now this is told in `:h vim9.txt` at `/Limitations` but the topic lacks a tag.

**Comment by lacygoill** [comment]
FWIW, here is what I came up with:
```vim
vim9script

var [title: string, cmd: string, items: list<any>, result: number] = ['', '', [], 0]
def Pick(atitle: string,
    acmd = '{title} {items[result - 1]}',
    aitems: list<any> = getcompletion(atitle .. ' ', 'cmdline'),
    i2l = null_function): number

    var lines: list<string> = empty(i2l) ? aitems : mapnew(aitems, i2l)
    return lines->popup_menu({
        title: atitle->printf('[ %s ]'),
        maxheight: &pumheight ?? &lines / 2,
        minwidth: &pumwidth,
        callback: (id: number, res: number) => {
            if 1 <= res && res <= len(aitems)
                [title, cmd, items, result] = [atitle, acmd, aitems, res]
                eval('$' .. string(cmd))->execute('')
            endif
        }
    })
enddef
```
Usage:
```vim
vim9script
Pick('colorscheme')
Pick('args', ':{result}argument', argv())
Pick('scriptnames', ':{result}{title}',
   execute('scriptnames')->split("\n"), (_, name) => name[1 :])
Pick('buffer', '{title} {items[result - 1].bufnr}', getbufinfo({buflisted: true}),
   (_, v) => printf('%2d %s', v.bufnr,
         v.name->fnamemodify(':t') ?? gettext('[No Name]')))
```

**Comment by brammool** [comment]
> @errael All examples from this section are in legacy script anyway. In
> Vim9Script there's no need for `a:` variable-scope and ugly
> line-continuations, but otherwise it would make no much difference.

I do think using Vim9 script makes it nicer.  Especially the lack of
backslashes helps.

Also, we should use lambda's more often to avoid having to pick a name
for the function.  And with Vim9 the types do not need to be specified.

The first example could become:

	popup_dialog('Continue? y/n', {
		 filter: 'popup_filter_yesno',
		 callback: (id, result) => {
				if result == 1
				  echomsg "'y' or 'Y' was pressed"
				else
				  echomsg "'y' or 'Y' was NOT pressed"
				endif
			     },
		 })

-- 
Nothing is impossible for the man who doesn't have to do it.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
Thanks for the suggestions.  I'll include the Vim9 versions of the existing examples.
I find the picker example too complicated to include in the help here.
It functions better as a plugin.
