### ISSUE TITLE
popup-windows: scrollbar thumb sometimes disappears

### ISSUE THREAD

**Issue by bfrg** [vim/vim#10492]
### Steps to reproduce

Run `vim --clean -S test.vim`, with
```vim
vim9script
range(100)
    ->mapnew((_, i: number): string => string(i))
    ->popup_create({
        firstline: 100,
        minheight: 10,
        maxheight: 10,
        minwidth: 50,
        maxwidth: 50,
        scrollbar: true,
        close: 'button',
        border: []
    })
```

**Result:** The thumb of the scrollbar is not visible until we scroll up a few lines.

**Screenshots**
![out](https://user-images.githubusercontent.com/6266600/170764573-1a1fa20d-25ff-4470-8d94-05e2fc5ea25e.png)

### Expected behaviour

Scrollbar thumb should always be visible.

### Version of Vim

8.2.5026

### Environment

Linux

**Comment by Shane-XB-Qian** [comment]
i am more interesting `how to just move the scrollbar (vs content) when/if no mouse or mouse did not kick that scrollbar thumb`
// looks this is my 4th times saying this.. aha...
:-)

**Comment by Shane-XB-Qian** [comment]
i am more interesting `how to just move the scrollbar (vs content) when/if no mouse or mouse did not kick that scrollbar thumb`
// looks this is my 4th times saying this.. aha...
:-)

**Comment by Shane-XB-Qian** [comment]
i am more interesting `how to just move the scrollbar (vs content) when/if no mouse or mouse did not kick that scrollbar thumb`
// looks this is my 4th times saying this.. aha...
:-)

**Comment by bfrg** [comment]
> i am more interesting how to just move the scrollbar (vs content) when/if no mouse or mouse did not kick that scrollbar thumb
// looks this is my 4th times saying this.. aha...
:-)

Are you asking how to scroll the popup window without using the mouse?

**Comment by Shane-XB-Qian** [comment]
> Are you asking how to scroll the popup window without using the mouse?

i am asking how to make popup scrollbar get `focus` and/or be able to move the scrollbar by some hotkeys.
// note: it is trying to move the `scrollbar` not the `content`.

-- 
shane.xb.qian

**Comment by bfrg** [comment]
@Shane-XB-Qian What do you mean with *move the `scrollbar` not the `content`*? 

If I understood you correctly, you're trying to scroll the popup with some keys and not the mouse. In general, popup windows are not focusable. If you want to scroll the popup, you need a popup-filter. See `:h popup-filter`. Unfortunately there's no example that shows how to scroll the content of a popup window. The recommended way to do this is to change the `firstline` entry of a popup window through a popup-filter.

For example, the following popup-filter lets you scroll the popup with `j` (like `CTRL-E` in a regular window), `k` (like `CTRL-Y`), `g` (jump to top of buffer), `G` (jump to bottom of buffer):
```vim
vim9script

def ScrollLine(winid: number, step: number)
    const firstline: number = popup_getpos(winid).firstline
    var newline: number

    if step < 0
        newline = firstline + step > 0 ? firstline + step : 1
    else
        const numlines: number = line('$', winid)
        newline = firstline + step <= numlines ? firstline + step : numlines
    endif

    popup_setoptions(winid, {firstline: newline})
enddef

def Filter(winid: number, key: string): bool
    if key == 'j'
        ScrollLine(winid, 1)
    elseif key == 'k'
        ScrollLine(winid, -1)
    elseif key == 'g'
        popup_setoptions(winid, {firstline: 1})
    elseif key == 'G'
        popup_setoptions(winid, {firstline: -1})
    elseif key == 'q'
        popup_close(winid)
    else
        return false
    endif
    return true
enddef

range(100)
    ->mapnew((_, i: number): string => string(i))
    ->popup_create({
        firstline: 1,
        minheight: 10,
        maxheight: 10,
        minwidth: 50,
        maxwidth: 50,
        scrollbar: true,
        mapping: false,
        filter: Filter,
        border: []
    })
```

An alternative is to use normal-mode commands for scrolling, together with `win_execute()`. For example:
```vim
def Filter(winid: number, key: string): bool
    if key == 'j'
        win_execute(winid, "normal! \<c-e>")
    elseif key == 'k'
        win_execute(winid, "normal! \<c-y>")
    elseif key == 'g'
        win_execute(winid, "normal! gg")
    elseif key == 'G'
        win_execute(winid, "normal! G")
    elseif key == 'q'
        popup_close(winid)
    else
        return false
    endif
    return true
enddef
```

**Comment by Shane-XB-Qian** [comment]
thanks. that's a good example. there was a discussion actually: #7555
and to me i more meant popup menu (completion menu), and seems cannot set completepopup=filter:Filter

**Comment by Shane-XB-Qian** [comment]
1, above

2, @brammool patch 5040 did not fix @bfrg the original issue raised here:
![image](https://user-images.githubusercontent.com/13550529/170953724-615b0eb7-a525-46ef-a7c3-25d63805312d.png)
// if scroll to the end line -the scrollbar thumb still disappeared.

3, #10253 tried to prevent user escaped from popup by win_gotoid(), 
but to *`popup term`* still can escape from it by `n_ctrl-w-w` or `ctrl-w_p` etc.
// example code same like @bfrg opened another ticket: #10497

**Comment by brammool** [comment]
Ah, off-by-one error

**Comment by bfrg** [comment]
Thank you. I think this can be closed. Fixed by https://github.com/vim/vim/commit/89b25585ccecf223ca41ca212df8ebc227fc035a.

> 3, https://github.com/vim/vim/pull/10253 tried to prevent user escaped from popup by win_gotoid(),
but to popup term still can escape from it by n_ctrl-w-w or ctrl-w_p etc.

@Shane-XB-Qian can you post it below #10497 since it has nothing to do with the scrollbar?

**Comment by Shane-XB-Qian** [comment]
1, keys to control scrollbar in *popup menu*, i do wish it can work, but IF felt not worthy, then let it be.

2, patch 5042 fixed this ticket the original issue.

3, ok, but let me post at #10253, these two should be more relevant.
