### ISSUE TITLE
[discuss] Consider a new 8.3 release if vim 9 is still not ready ?

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#10491]
Consider a new 8.3 release if vim 9 is still not ready ?

Enough new features and vim9 script can also be marked as "RC" status.

The "RC" status is good to encourage people switch to the new script and collect feedbacks.

And the final vim9 can be released after it becomes more stable or more powerful (support class or something).

**Comment by chrisbra** [comment]
I think we can close this, as it seems we are coming closer to an actual Vim 9 release: https://groups.google.com/g/vim_dev/c/E37hUdqPBQw/m/bSau2ZfyAQAJ
