### ISSUE TITLE
Why the manual is formatted with tw=78?

### ISSUE THREAD

**Issue by john-cj** [vim/vim#10506]
Bram, what is the reason that the manual is formatted with `tw=78`? And not e.g. `tw=79`, which is the default for `gq`. (This simple question bothered me for years!)

**Comment by vim-ml** [comment]
* John ***@***.***> [220531 21:13]:
> Sorry for using issue tracker to ask a question, but I simply don't
> know how to get an answer from Bram himself.

Typically, sending to the group ***@***.*** (alias
***@***.***) or ***@***.*** (alias ***@***.***) will
accomplish what you wanted, whether or not you explicitly address the
question to Bram.

In the README at github.com/vim/vim under the heading Information you
will find a pointer to a page describing the mailing lists.

...Marvin
