### ISSUE TITLE
Inconsistent timeoutlen behavior between mappings and built-in commands

### ISSUE THREAD

**Issue by andmis** [vim/vim#10503]
### Steps to reproduce

```
set timeout
set timeoutlen=1000
map gx <Cmd>echom "gx"<CR>
map gxy <Cmd>echom "gxy"<CR>

" Press gxy → prints "gxy"
" Press gx → wait 1 second → prints "gx"
" This works as expected.

map g <Cmd>echom "g"<CR>
" Press g → wait 1 second → prints "g"
" Press gg → prints "g" twice, instead of executing the gg built-in.
```

### Expected behaviour

`gg` goes to the first line of the file, rather than printing "g" twice.

### Version of Vim

Latest

### Environment

macOS 12

**Comment by brammool** [comment]
This is working as intended.
Not sure what you were trying to do. If you want "g" to do one thing and "gg" to do something else, you must also map "gg".
And you probably want to use :noremap instead of :map.

**Comment by andmis** [comment]
I want `g` to do something custom, and `gg` to do the default, built-in command after `timeoutlen`, along with every other `g`-prefixed command in `:help g`.

Right now I can `:map g <MyCustomThing>` and `:noremap gg gg`, but then I need to `:noremap g<Key> g<Key>` for every single `g<Key>` command in `:help g`.

**Comment by andmis** [comment]
In case you care, this is to enable a plugin similar to https://github.com/liuchengxu/vim-which-key to work with built-in commands.

The natural way to implement this is to map `g` to show a pop-up, so that the pop-up appears after `timeoutlen`, but if the user completes a command by typing `gg` quickly, then there is no need for the pop-up to appear.

**Comment by brammool** [comment]
The letter "g" is the prefix for many commands, so perhaps it's not a great idea to map it.

**Comment by andmis** [comment]
I agree in general, but in my use case (a plugin that pops up a hint window showing the mappings having the prefix entered so far), the whole reason to map it is that there are commands that start with the letter.

**Comment by zeertzjq** [comment]
This may also be achieved using `getchar()` and `feedkeys()` in the mapping.

**Comment by andmis** [comment]
How can you get the popup to appear when pressing `g` after a timeout without creating a user mapping for `g` and thus disabling the built-ins?

You can emulate all of the built-ins by using `feedkeys` without remap from plugin code, but that really seems like a hack. For example, wouldn't I need to manually forward registers and ranges?

**Comment by zeertzjq** [comment]
That's why I said "this specific purpose". In some other cases it is not very convenient.

**Comment by andmis** [comment]
`KeyTimedOut` would not work, because in `vim --clean`, if you press `g`, the `g` does not "time out", it waits forever. Built-ins don't time out, only user mappings do, and if I add a user mapping for `g` then we are back to the built-ins starting with `g` being disabled.
