### ISSUE TITLE
Runtime files do not include sbt.vim

### ISSUE THREAD

**Issue by Denton-L** [vim/vim#1051]
Inside `runtime/compiler`, a file is missing, `sbt.vim`, which can be found [here](https://github.com/derekwyatt/vim-scala/blob/master/compiler/sbt.vim). This is because [`ftplugin/scala.vim`](https://github.com/derekwyatt/vim-scala/blob/master/ftplugin/scala.vim#L34) requires `sbt` in order to be sourced.

Currently, I am getting this error when I'm loading any `*.scala` files:

```
Error detected while processing /usr/share/vim/vim74/ftplugin/scala.vim:
line   35:
E666: compiler not supported: sbt
```

**Comment by vim-ml** [comment]
On Friday, September 9, 2016 at 9:24:11 AM UTC-4, Denton Liu wrote:

> Inside runtime/compiler, a file is missing, sbt.vim, which can be found here. This is because ftplugin/scala.vim requires sbt in order to be sourced.
> 
> Currently, I am getting this error when I'm loading any *.scala files:
> 
> Error detected while processing /usr/share/vim/vim74/ftplugin/scala.vim:
> line   35:
> E666: compiler not supported: sbt
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub

The scala ftplugin (which was just added to the default runtime in the last month), was updated again 3 days ago to remove the "compiler sbt".

See:
https://github.com/vim/vim/pull/995
https://github.com/vim/vim/pull/1043
https://github.com/vim/vim/commit/64d8e25bf6efe5f18b032563521c3ce278c316ab#diff-15
