### ISSUE TITLE
Got func_unref when redefining a deleted function

### ISSUE THREAD

**Issue by ddickstein** [vim/vim#10515]
### Steps to reproduce

Source a file with these contents:
```
function! I(f)
  let l:F = a:f
  let o = {}
  function o.f(...) closure
    return call(F, a:000)
  endfunction
  return o.f
endfunction

let A = I({ -> 0 })
delfunction A
let A = I({ -> 0 })
```

The following error appears:
```
line   12:
E685: Internal error: func_unref()
```

### Expected behaviour

No error

### Version of Vim

8.1.1602

### Environment

OS: CentOS 7.9
Terminal: xfce4-terminal 0.8.7.4
$TERM: tmux-256color
Shell: Bash 4.2.46

**Comment by arp242** [comment]
In Vim 8.2.5048 I get:

    line   11:
    E475: Invalid argument: A

Which seems reasonable, as `A` is not a declared function; I guess this behaviour changed at some point? 8.1.1602 is almost three years old.

**Comment by lacygoill** [comment]
The internal error disappeared after the patch [8.2.3408](https://github.com/vim/vim/releases/tag/v8.2.3408).

Vim 8.2.5052 gives `E475`, which seems correct because `:delfunction` expects a function name.  But `A` is not the name of a function; it's the name of a variable.

**Comment by brammool** [comment]
This was already fixed, please use a newer version of Vim (Not sure which patch fixed this problem, getting the latest is the best anyway).

**Comment by ddickstein** [comment]
Thanks all; this was the only version I had available at the time on the machine where I was testing. I've since compiled vim from source so I can improve the error reports.
