### ISSUE TITLE
Misinterpreting UTF-8 BOM when doing `!sort`

### ISSUE THREAD

**Issue by kaddkaka** [vim/vim#10525]
### Steps to reproduce

Have a file that starts with a utf-8 Byte Order Marker (BOM), for example with this hex content (as seen by `hd example.txt`):
```
00000000  ef bb bf 43 0d 0a 42 0d  0a 41 0d 0a              |...C..B..A..|
0000000c
```

The leading `ef bb bf` is the BOM in this case.

Open the file in vim, select all lines and sort them with a filter `VG!sort<enter>`. This will input a new BOM marker into the file, making it 3 bytes larger and showing that as `<feff>` in the editor.

### Expected behaviour

Lines sorted without any BOM being duplicated.

- This does not happen with the `:sort` command.
- It does not happen when running unix `sort` directly from command line.

 Not sure if this is a vim or unix_sort issue.

### Version of Vim

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 18 2022 19:26:30) Included patches: 1-3995

### Environment

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04 LTS
Release:        22.04
Codename:       jammy
```

`man sort`: `GNU coreutils 8.32     February 2022`

**Comment by brammool** [comment]
This is a problem with the sort command, it does not recognize the BOM and handles it like any other character.  The result is that the line with the BOM sorts to the end.
You can see it with "sort example.txt >sorted.txt" and use "xxd sorted.txt".

Using a BOM with UTF-8 is pointless, since there is no byte order.  Just make sure to drop it.

**Comment by kaddkaka** [comment]
The strangeness occurs in that the result is different when running sort as a standalone tool and when running it through vims filter (`:!sort`). As seen in the file size, the filtering through unix sort the BOM bytes will follow the first line to it's new sorted location, but vim will also keep the BOM at the top of the file. So now the file is 3 bytes larger. 

```
-rw-rw-r-- 1 david david 12 jun  5 12:30 example.txt
-rw-rw-r-- 1 david david 12 jun  5 13:32 example.unixsort
-rw-rw-r-- 1 david david 12 jun  5 13:34 example.vim_cmd_sort
-rw-rw-r-- 1 david david 15 jun  5 13:33 example.vim_filter_sort
```

Is it reasonable that vim keeps the BOM bytes at the top of the file, while also letting them filter through the external command sort?

**Comment by brammool** [comment]
You get what you ask for...
In Vim you can reset the 'bomb' option.  And for cases like this you probably should.
