### ISSUE TITLE
popup_menu-shortcut-example: Unknown function: MyMenuHandler

### ISSUE THREAD

**Issue by habamax** [vim/vim#10532]
### Steps to reproduce

1. `:h popup_menu-shortcut-example`
2. select the vimscript example and `:'<,'>source`
3. In the popup menu press `Enter`

### Expected behaviour

Example shown should work without errors

![image](https://user-images.githubusercontent.com/234774/172223202-aa97006c-765f-4d94-b926-d1495429c4ca.png)

### Version of Vim

8.2.5056

### Environment

Win, Fedora

**Comment by brammool** [comment]
Yeah, the callback was left to be defined.  We can add a simple one to show how it's done:
```
	func MyMenuHandler(id, result)
	  echo $'Result: {a:result}'
	endfunc
```
