### ISSUE TITLE
Commit for patch 8.2.5066 does not match commit comment.

### ISSUE THREAD

**Issue by paul-ollis** [vim/vim#10533]
### Steps to reproduce

N/A

### Expected behaviour

This commit says it is about timer_create on Macs, but the changes are for something completely different.

### Version of Vim

patch 8.2.5066: 

### Environment

N/A

**Comment by brammool** [comment]
> This commit says it is about timer_create on Macs, but the changes are for something completely different.

Sorry about that.  I had a patch to try out this #ifdef change, but did
not want to send it out yet.  Unfortunately the patch that I did send
out picked up the description of the other patch.  Other than the wrong
description it should be OK.

-- 
       [Autumn changed into Winter ... Winter changed into Spring ...  Spring
       changed back into Autumn and Autumn gave Winter and Spring a miss and
       went straight on into Summer ...  Until one day ...]
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
> >  I had a patch to try out this #ifdef change, 
> 
> Regarding the #ifdef' patch, I am surprised and puzzled. My Mac does
> not have timer_create, so I am surprised that somebody else had a
> problem. Please let me know if I can be of help looking at this.

I have sent out the change that should fix the reported problem.
Configure should run on Mac, I don't know why this extra condition was
there.

-- 
My girlfriend told me I should be more affectionate.
So I got TWO girlfriends.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
