### ISSUE TITLE
test_terminal.vim Failed / ArchLinux PKGBUILD

### ISSUE THREAD

**Issue by pheiduck** [vim/vim#10530]
### Steps to reproduce

use Arch Linux PKGBUILD
build it with makepkg -src or chrootbuild

### Expected behaviour

no test failed like on upstream (here)

### Version of Vim

8.2.5062-1

### Environment

gh Action ubuntu-latest
manjaro-chrootbuild

### Logs and stack traces

```shell
Failures: 
	From test_terminal.vim:
	Found errors in Test_terminal_qall_prompt():
	Run 1:
	command line..script /build/vim/src/vim-8.2.5062/src/testdir/runtest.vim[459]..function RunTheTest[44]..Test_terminal_qall_prompt[6]..WaitForAssert[2]..<SNR>6_WaitForCommon[11]..<lambda>133 line 1: Pattern '\\[running]' does not match '<r@fv-az82-486:/build/vim/src/vim-8.2.5062/src/testdir]  0,0-1          All'
	Run 2:
	command line..script /build/vim/src/vim-8.2.5062/src/testdir/runtest.vim[492]..function RunTheTest[44]..Test_terminal_qall_prompt[6]..WaitForAssert[2]..<SNR>6_WaitForCommon[11]..<lambda>138 line 1: Pattern '\\[running]' does not match '<r@fv-az82-486:/build/vim/src/vim-8.2.5062/src/testdir]  0,0-1          All'
	Run 3:
	command line..script /build/vim/src/vim-8.2.5062/src/testdir/runtest.vim[492]..function RunTheTest[44]..Test_terminal_qall_prompt[6]..WaitForAssert[2]..<SNR>6_WaitForCommon[11]..<lambda>143 line 1: Pattern '\\[running]' does not match '<r@fv-az82-486:/build/vim/src/vim-8.2.5062/src/testdir]  0,0-1          All'
	Run 4:
	command line..script /build/vim/src/vim-8.2.5062/src/testdir/runtest.vim[492]..function RunTheTest[44]..Test_terminal_qall_prompt[6]..WaitForAssert[2]..<SNR>6_WaitForCommon[11]..<lambda>148 line 1: Pattern '\\[running]' does not match '<r@fv-az82-486:/build/vim/src/vim-8.2.5062/src/testdir]  0,0-1          All'
	Run 5:
	command line..script /build/vim/src/vim-8.2.5062/src/testdir/runtest.vim[492]..function RunTheTest[44]..Test_terminal_qall_prompt[6]..WaitForAssert[2]..<SNR>6_WaitForCommon[11]..<lambda>153 line 1: Pattern '\\[running]' does not match '<r@fv-az82-486:/build/vim/src/vim-8.2.5062/src/testdir]  0,0-1          All'
	Flaky test failed too often, giving up
TEST FAILURE
make[2]: Leaving directory '/build/vim/src/vim-8.2.5062/src/testdir'
make[1]: Leaving directory '/build/vim/src/vim-8.2.5062/src'
```

**Comment by pheiduck** [comment]
only possible to build if test is disabled

**Comment by pheiduck** [comment]
happend on 8.2.5055 and up but not on 8.2.5054

**Comment by brammool** [comment]
> happend on 8.2.5055 and up but not on 8.2.5054

The only thing that patch 8.2.5055 does is to make sure the statusline
gets updated.

What is the value of $SHELL when running the tests?
Even when it's a very long string the "[running]" should still show up.
Could you add a "sleep 10" after the point where the test fails, to see
what the screen looks like?

-- 
ARTHUR: Did you say shrubberies?
ROGER:  Yes.  Shrubberies are my trade.  I am a shrubber.  My name is Roger
        the Shrubber.  I arrange, design, and sell shrubberies.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by pheiduck** [comment]
@brammool https://github.com/pheiduck/vim-git/runs/6794225556?check_suite_focus=true

**Comment by pheiduck** [comment]
> What is the value of $SHELL when running the tests?

bash / xterm

**Comment by pheiduck** [comment]
btw, the test is tried 6 times but failed anyway on my Environment

**Comment by brammool** [comment]
> I can reproduce the term status line both inside and outside of a
> chroot. I built vim 8.2.5088 on Arch (with skipped tests) and
> installed the resulting package. `:term` spawns a shell but in the
> middle of the screen there's a green status line saying:
> 
> ```
> !/bin/bash ***@***.***:~/desktop/vim/trunk]                              0,0-1          All
> ```
> 
> If I `cd` to another directory in the spawned shell, the status line
> is updated with the new path.
> 
> After rolling back to 8.2.5046, `:term` gives:
> 
> ```
> !/bin/bash [running]                                                           0,0-1          All
> ```

It appears that the shell itself is setting the window title.  This then
ends up in tl_title and gets displayed instead of the job status.

It should be possible to disable this with:
	test_override('vterm_title', 1)

I'll make a patch for that.  If that doesn't fix the problem, please
reopen the issue.

-- 
A parent can be arrested if his child cannot hold back a burp during a church
service.
		[real standing law in Nebraska, United States of America]

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by pheiduck** [comment]
still present for me: https://github.com/pheiduck/vim-git/runs/6882240944?check_suite_focus=true#step:7:15147

**Comment by brammool** [comment]
> still present for me: https://github.com/pheiduck/vim-git/runs/6882240944?check_suite_focus=true#step:7:15147

I cannot see any reason why this happens.  The only way to get this kind
of status is by setting tl_title, and that has now been made impossible.
Can you run this in a debugger for this environment?

-- 
Beer & pretzels can't be served at the same time in any bar or restaurant.
		[real standing law in North Dakota, United States of America]

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by foutrelis** [comment]
I get the same error when running the test suite (vim version 8.2.5094). However, using `call test_override('vterm_title', 1)` in a regular vim instance makes `:term` show `[running]`. Not sure why it doesn't work for the test though.

**Comment by foutrelis** [comment]
This seems to fix the test but I can't judge its correctness (just copied how `:term` is sent to vim):

```diff
--- src/vim-8.2.5094/src/testdir/test_terminal.vim.orig	2022-06-14 18:14:53.000000000 +0000
+++ src/vim-8.2.5094/src/testdir/test_terminal.vim	2022-06-14 18:14:53.000000000 +0000
@@ -1219,10 +1219,11 @@ endfunc
 func Test_terminal_qall_prompt()
   CheckRunVimInTerminal
 
-  " the shell may set the window title, we don't want that here
-  call test_override('vterm_title', 1)
   let buf = RunVimInTerminal('', {})
 
+  " the shell may set the window title, we don't want that here
+  call term_sendkeys(buf, ":call test_override('vterm_title', 1)\<CR>")
+
   " Open a terminal window and wait for the prompt to appear
   call term_sendkeys(buf, ":term\<CR>")
   call WaitForAssert({-> assert_match('\[running]', term_getline(buf, 10))})
@@ -1236,7 +1237,6 @@ func Test_terminal_qall_prompt()
 
   " close the terminal window where Vim was running
   quit
-  call test_override('ALL', 0)
 endfunc
 
 " Run Vim in a terminal, then start a terminal window with a shell and check
```

**Comment by brammool** [comment]
> I get the same error when running the test suite (vim version
> 8.2.5094). However, using `call test_override('vterm_title', 1)` in a
> regular vim instance makes `:term` show `[running]`. Not sure why it
> doesn't work for the test though.

I think the problem is that the test override is set in the current Vim
instance, but the test is run in another one.  I'll make a patch...

-- 
No man may purchase alcohol without written consent from his wife.
		[real standing law in Pennsylvania, United States of America]

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by foutrelis** [comment]
I think there's an error in https://github.com/vim/vim/commit/99f4b6e0824b339510aaaa0bb81c50f5866f6be1 -- it does `:test_override` instead of `:call test_override`.
