### ISSUE TITLE
Cursorline position jumps between two positions when scrolling down if scrolloff is half the window height

### ISSUE THREAD

**Issue by EtiamNullam** [vim/vim#10545]
### Steps to reproduce

1. Start clean vim: `vim -u NONE`
2. Open any file that is big enough to experience the problem, for example: `:help`
3. (optional) These are useful for diagnose: `:set relativenumber number`
4. `:set scrolloff=3`
5. Set window height to twice of what scrolloff is: `:resize 6`
6. Hold `j` or press it several times
7. Notice the number of lines before cursorline alternates between number of lines set by `scrolloff` and `scrolloff - 1` causing disturbing flicker

#### Example

Visual example in `neovim`, but behavior is exactly the same in `vim`:

https://user-images.githubusercontent.com/10875340/172717956-eaf284c6-645b-4172-b4b5-6347a22a29de.mp4

### Expected behaviour

Cursorline position should always be static and not flicker between two positions when scrolling down.

### Version of Vim

8.2.2824

### Environment

Windows 10

**Comment by zeertzjq** [comment]
I suspect this is a bug in `scroll_cursor_bot()`:
```c
/*
 * Recompute topline to put the cursor at the bottom of the window.
 * Scroll at least "min_scroll" lines.
 * If "set_topbot" is TRUE, set topline and botline first (for "zb").
 * This is messy stuff!!!
 */
    void
scroll_cursor_bot(int min_scroll, int set_topbot)
```

In the example above, `scroll_cursor_bot()` is called every time `j` is pressed in the center of the window, but in half of the times `scrolled` is `0` when control reaches here:
```c
    // curwin->w_empty_rows is larger, no need to scroll
    if (scrolled <= 0)
	line_count = 0;
```

and no scrolling is done. This looks a bit strange, especially considering the comment above.

**Comment by catgoose** [comment]
I think I have an issue related to this.  When setting scrolloff greater than half the screen height and switching windows, the cursor moves up or down, but only within function blocks.  I can post a video if needed.

**Comment by brammool** [comment]
I don't like videos much, it's hard to see what commands are used, and copy/pasting is not possible.
A Vim script to reproduce a problem is much more useful.  With a bit of luck it can be used for a test case.

**Comment by EtiamNullam** [comment]
@brammool 

The only command used throughout the video is `j`, pressed many times and held, it's just an extra to visualize the problem.

I believe the included steps to reproduce already contain the required vimscript, only with the added noise of English. Let me extract it for you:

```vim
" setup
  help
  set scrolloff=3
  resize 6

  " optional
    set relativenumber number

" move away from buffer start
  norm 2j

" NOTE:
  " amount of lines visible above (2) and below (3) the cursorline are not even
  " that's only when you can experience this problem

" from now on every subsequent press of 'j'
" will flip the amount of lines visible above and below the cursorline
  norm j
```

I hope that will be useful. Thank you for such a great editor!
