### ISSUE TITLE
syntax/sh.vim: bad highlight for param transformation, e.g. ${foo@Q}

### ISSUE THREAD

**Issue by jwilk** [vim/vim#10551]
Consider the following bash script:
```bash
#!/bin/bash
bar=${foo@Q}
```
Vim highlights `@Q` as an error, but this is valid syntax since Bash 4.4: it's called "[parameter transformation](https://manpages.debian.org/bullseye/bash/bash.1.en.html#Parameter_Expansion)".

Tested with Vim 8.2.5071.

**Comment by brammool** [comment]
@cecamp

**Comment by chrisbra** [comment]
also seems to be fixed by https://github.com/vim/vim/commit/dd60c365cd2630794be84d63c4fe287124a30b97#diff-650e28e4ad6a5c9241345580a7136ff18b5629f3b4910a5b5a455828bca5e517
