### ISSUE TITLE
After installing 32-bit Vim on DOS, vim.exe cannot be found

### ISSUE THREAD

**Issue by DrewMcArthur** [vim/vim#1055]
For class on computer organization, I'm using 32-bit DOS on a usb drive.  I wanted to install Vim, and so I downloaded the Vim runtime zip and the 32-bit DOS executable zip.  I unzipped both of these, and put the contents of the runtime dir into `/vim/vim73`.  I also unzipped the CWSDPMI in that folder.  

So in the directory `/vim/vim73/`, we have the files from 32-bit DOS Vim, Vim runtime, and CWSDPMI included in the runtime.  I moved the `CWSDPMI.exe` into vim73 also. 
I put this in the root dir of the DOS key, and boot it.  

Navigate to `C:\VIM\VIM73`, and run `install`. Everything goes well, I change the install directory from `C:\TC` to `C:\DOS`, because it appears that's where the commands are stored.  I also changed right clicking to be unix-like and not to use windows style keyboard shortcuts.  

After installing, running VIM (`vim test.txt`) returns the following echo statement: `"C:\VIM\VIM73\vim.exe" not found`.  After looking at `C:\DOS\VIM.BAT`, the following code is what prints that:

`if exist "%VIM_EXE_DIR%\VIM.EXE" goto have vim
echo "%VIM_EXE_DIR%\VIM.EXE" not found
goto eof`

Where `%VIM_EXE_DIR%` is `C:\VIM\VIM73`, evident by the error statement, however `VIM.EXE` _is_ in `C:\VIM\VIM73`.  

If I can't get Vim working, I'll be stuck in Emacs for the semester, which would be unfortunate.

**Comment by DrewMcArthur** [comment]
This is fixed by removing quotes in the line `"%VIM_EXE_DIR%\vim.exe" %VIMARGS%`.

**Comment by chrisbra** [comment]
vim 7.3 is 6 years old. Please try with a recent version.

**Comment by k-takata** [comment]
MS-DOS support was removed in patch 7.4.1399. So this will never be fixed.
