### ISSUE TITLE
parfait static analysis report on 7.4.2364

### ISSUE THREAD

**Issue by dhduvall** [vim/vim#1056]
Here's another static analysis report, this time by the Sun/Solaris/Developer Studio tool, parfait.  It's been a Sun in-house tool for a number of years, and it's LLVM-based, so the results may overlap a great deal with the ones found in issue 1049, but there are at least a few which aren't there.  As with the ones found by the clang static analyzer, many of these may be false positives (when I've looked at some of these before, it seemed like most were), but they may still be worth looking through.  I can upload the browser-based report, too, if that's useful.

(When posting, I botched the version; it should be 7.4.2364, despite the 2290 still in the attached file text.)

[gvim7.4.2290.parfait.txt](https://github.com/vim/vim/files/466294/gvim7.4.2290.parfait.txt)

**Comment by lacygoill** [comment]
The report was probably useful at the time, but four years later, are the info it contains still relevant?

**Comment by dhduvall** [comment]
I doubt it. And I don't have access to the tools to rerun it.
