### ISSUE TITLE
CTRL+key combinations don't work in gvim with alternative input language after 8.2.4807 in Windows

### ISSUE THREAD

**Issue by ladayaroslav** [vim/vim#10579]
OS: Windows 10, Windows 11.
gvim version: 8.2.4807 or newer

The problem is with the keyboard behavior in insert mode in gvim when keyboard layout is switched to another input language (Russian, in my case).

When trying completion while switched to Russian (switching system's keyboard input language, which is left_ALT+SHIFT by default, just in case), C-n just prints т, and C-p prints з. This affects all CTRL+key commands (corresponding letters are printed instead).

Everything works fine in command-line vim. 

Just in case, I tried gvim from https://tuxproject.de/projects/vim/ , as well as the one from https://github.com/vim/vim-win32-installer/releases

Tried to bisect (using installers from https://github.com/vim/vim-win32-installer/releases ), and now I'm pretty sure https://github.com/vim/vim/commit/77fc0b02e53bdc49213900e0055cb6d678ce180d
(patch 8.2.4807: processing key eveints in Win32 GUI is not ideal) is the one that broke it.
I.e. completion (and other CTRL+key combinations) works fine in INSERT mode in https://github.com/vim/vim-win32-installer/releases/tag/v8.2.4803 , but does not in more recent versions.

**Comment by brammool** [comment]
@LemonBoy

**Comment by dantezhu** [comment]
seems they are same problem: [issue10602](https://github.com/vim/vim/issues/10602)
