### ISSUE TITLE
Test Failure in test_listchars.vim

### ISSUE THREAD

**Issue by riesebie** [vim/vim#10576]
### Steps to reproduce

Building 8.2.5096 gives:
`Failures: 
        From test_listchars.vim:
        Found errors in Test_listchars():
        command line..script /source/vim/vim-8.2.5096/src/vim-basic/testdir/runtest.vim[464]..function RunTheTest[44]..Test_listchars line 197: Expected ['.-+*ffffyYzZ$', '.-i iSyYzZgg$', ' hyYzZyYzZyY$', '.-+*.-+*.-j $', '.-+*0yY0yYzZ$', '$'] but got ['.-+*ffffyYzZ$', '.-i iS֫yYzZgg$', ' hyYzZyYzZyY$', '.-+*.-+*.-j $', '.-+*0yY0yYzZ$', '$']`

### Expected behaviour

clean build

### Version of Vim

8.2.5096

### Environment

Linux
tmux
clang-14
zsh

**Comment by riesebie** [comment]
This is a bit confusing, as 'expected' looks equal to 'got'

**Comment by zeertzjq** [comment]
This previously also failed once on GitHub CI: <https://github.com/vim/vim/runs/6852905773?check_suite_focus=true>
```
Failures: 
	From test_listchars.vim:
	Found errors in Test_listchars():
	command line..script /Users/runner/work/vim/vim/src/testdir/runtest.vim[459]..function RunTheTest[44]..Test_listchars line 197: Expected ['.-+*ffffyYzZ$', '.-i iSyYzZgg$', ' hyYzZyYzZyY$', '.-+*.-+*.-j $', '.-+*0yY0yYzZ$', '$'] but got ['.-+*ffffyYzZ$', '.-i iS۠�yYzZgg$', ' hyYzZyYzZyY$', '.-+*.-+*.-j $', '.-+*0yY0yYzZ$', '$']
```

**Comment by brammool** [comment]
I have not seen it fail and I doubt this functionality depends on the platform.
@chrisbra

**Comment by brammool** [comment]
Oh, valgrind complains: "Conditional jump or move depends on uninitialised value(s)".
Apparently ASAN doesn't catch this.
