### ISSUE TITLE
msgfunc - Allow the user to add a custom message sink (e.g. for :echo)

### ISSUE THREAD

**Issue by vimpostor** [vim/vim#10571]
Similar to `thesaurusfunc`, we could have an option `msgfunc` that allows the user to define a custom function that displays messages that are printed with `:echo`, `:echom`, etc...
I think this would also be a good first step to make implementing #940 easier.

A usecase scenario might be that the user wants to see messages in their statusline, or they might want to show them in the corner via the popup api similar to [this plugin](https://github.com/rcarriga/nvim-notify).

[Neovim first came up with this idea](https://github.com/neovim/neovim/pull/16480), but they abandoned it because they want to use a more generic Lua implementation (which doesn't apply to Vim because it doesn't have external UI API).
I for one disagree with their reasoning, and think `msgfunc` would be a good idea.

So before I start writing patches, I wanted to get input whether you all (and especially Bram) agree that this is a good idea.

**Comment by chrisbra** [comment]
I'd like the idea.

**Comment by Shougo** [comment]
notify plugin for Vim is here.

https://github.com/mattn/vim-notification

**Comment by vimpostor** [comment]
> I am the patch author.

Yes, thank you very much for your neovim patch. I am also a fan of your `cmdheight=0` work, I appreciate what you are doing!
I don't want to "steal" your idea, but from the looks of it, neovim rejected the idea of `msgfunc`...

I also assumed that you didn't want to port this to Vim, because you opened the patch in Neovim first whereas usually cross-codebase patches are opened in Vim first and then ported to Neovim.

If my assumption was wrong, and you are interested in adapting your patch to Vim yourself, then of course I will give you the right of way to post the patch!

**Comment by brammool** [comment]
> Similar to `thesaurusfunc`, we could have an option `msgfunc` that
> allows the user to define a custom function that displays messages
> that are printed with `:echo`, `:echom`, etc...
> I think this would also be a good first step to make implementing #940
> easier.
> 
> An usecase scenario might be that the user wants to see messages in
> their statusline, or they might want to show them in the corner via
> the popup api similar to [this
> plugin](https://github.com/rcarriga/nvim-notify).
> 
> [Neovim first came up with this
> idea](https://github.com/neovim/neovim/pull/16480), but they abandoned
> it because they want to use a more generic Lua implementation (which
> doesn't apply to Vim because it doesn't have external UI API).
> I for one disagree with their reasoning, and think `msgfunc` would be
> a good idea.
> 
> So before I start writing patches, I wanted to get input whether you
> all (and especially Bram) agree that this is a good idea.

I'm not sure.  It may be good for some echo commands, but since it works
globally it would apply to everything.  A plugin may use an echo command
for any reason, doing something else with the message is unlikely able
to take care of all the ways echo is used.

Wouldn't it be better to add a command or function that displays a
message in a user-defined way?  E.g. in a popup or a message window.
This would fall back to using :echo.

-- 
bashian roulette:
$ ((RANDOM%6)) || rm -rf ~

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
> > Wouldn't it be better to add a command or function that displays a
> > message in a user-defined way? E.g. in a popup or a message window.
> > This would fall back to using :echo.
> 
> Unfortunately that wouldn't suffice for the usecase. This feature is
> mainly also about allowing stuff like #940 (`cmdheight=0`), that is
> getting rid of the cmdline completely (unless the current `mode()` is
> cmdline mode, in which case the cmdline will be overlayed over the
> last line).
> Getting rid of the `:echo` messages, is currently the only blocker for
> implementing something like `cmdheight=0`, so unfortunately an extra
> user-defined `echo` API wouldn't be enough to deal with this problem.

I think that clearly shows the problem with such a function.  A plugin
or anything that displays a message must have some idea of where and how
it shows up.  If that becomes unpredictable, various things may not go
according to plan.  Especially, when will the message disappear?

Also, the message must show up somewhere.  If not on the command line,
it's likely to go on top of something.  You mention the last line, which
may be where the user is editing, thus that's not a great spot.  A
separate window for messages would work, but it defeats the idea of
making the command line as small as possible.

Keep in mind that it took a very, very long time to get the current
behavior work well, with the 'ruler' and 'showcmd' sharing the space
with a message, keeping the message long enough, avoding the hit-enter
prompt, etc.  It's tricky to get this right. 

-- 
There are only two hard things in programming: Cache invalidation,
naming things and off-by-one errors.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vimpostor** [comment]
> A plugin or anything that displays a message must have some idea of where and how it shows up. If that becomes unpredictable, various things may not go according to plan.

I see, but we can make it clear in the help file to the user that it is important that no messages are lost. After all this would be an optional feature, that the user has to explicitly enable.

> Especially, when will the message disappear? 

Vim could call `msgfunc` with a `clear-message` flag, to tell the user-defined function that it needs to hide the last message. Of course the user-defined function could also decide to hide the message earlier.

> Also, the message must show up somewhere. You mention the last line, which may be where the user is editing, thus that's not a great spot.

Sry I might have explained that badly. I mentioned the last line only in context of `cmdheight=0`, which is a separate issue. To answer your question, as to where it may show up: The user completely decides this, here are some example scenarios, with the first one being what I would consider the most reasonable:

- `msgfunc` displays the message in an unfocusable popup window in the bottom right corner of the screen (this can also easily show multiline messages)
- `msgfunc` displays the message in an extra area of the statusline. Unfortunately, because the statusline is only one line, multi-line messages would need to be merged into one line
- `msgfunc` displays the message via `tmux display-message` in the tmux window (multiline messages need to be merged)
- `msgfunc` displays the message via `tmux display-popup` in the bottom right corner of the entire terminal window (would support multiline messages)
- `msgfunc` displays the message via `notify-send` (very intrusive)
- `msgfunc` displays the message completely external in the statusline of the window manager of the user (e.g. next to something like a system tray) (very intrusive)

The possibilities are endless, and I think telling the user explicitly in the helpfile that they need to be careful to show messages properly would be appropriate with your main concern.

> It's tricky to get this right.

I agree, it's not an easy patch, but it certainly would open a lot of possibilities.

**Comment by Shougo** [comment]
https://github.com/vim/vim/pull/10675#issuecomment-1202333994

The builtin message popup feature is better.

**Comment by Shougo** [comment]
@vimpostor The message popup window feature is already implemented.
The feature is needed?

**Comment by chrisbra** [comment]
let's close it then.

**Comment by vimpostor** [comment]
> @vimpostor The message popup window feature is already implemented. The feature is needed?

Yes, the message popup window feature works for me too. (Although there are still some bugs to be fixed with it, but I can open new tickets for those that I find)
