### ISSUE TITLE
win_move_separator can only work if another window exists to right of current window

### ISSUE THREAD

**Issue by craigmac** [vim/vim#10583]
### Steps to reproduce

1. vim --clean
2. vsp
3. call win_move_separator(winnr(), 10)
4. call win_move_separator(winnr(), -10)

Works fine. Now:

5. wincmd l
6. call win_move_separator(winnr(), 10)
7. call win_move_separator(winnr(), -10)

Neither work because there's no righthand side separator. We are only able to move the separator is there exists one to the 'right' of the current window.

### Expected behaviour

I would expect that when your cursor/active window doesn't have a righthand-side window, we try pushing the left-hand side separator. Otherwise, if you only ever target a right-hand side separator, if we have 2 vertical windows and I move the cursor to the right hand side window none of the commands work because there's no righthand-side separator. A fix I guess would be to jump the cursor *back* to the left hand side and run it there before jumping back to right-hand side again, but it's really unintuitive that it works this way.

Related PR that introduced the command: https://github.com/vim/vim/pull/9486 

### Version of Vim

8.2.5077

### Environment

macOS Monterey 12.4
Alacritty
TERM=alacritty
shell=zsh

**Comment by brammool** [comment]
I'm not sure why you call win_move_separator() when the window does not have a separator on the right.  It's clearly documented that this is what it does.  I don't think handling mistakes of the caller is desired.  Keep in mind that it's a programmatic way to do what dragging the separator with the mouse would do.

**Comment by craigmac** [comment]
Thanks, pointing that out made me realize my mistake and easy fix, when there's a winid found to the left I just use that as the winid to call win_move_separator with, so even though my cursor is in the right hand pane it calls `win_move_separator(winnr('h'), -2)`.
