### ISSUE TITLE
Vim9: Terminates with "SIGSEGV (Address boundary error)" when trying to call Lua function

### ISSUE THREAD

**Issue by ajukraine** [vim/vim#10587]
### Steps to reproduce

1. Create vimrc file (for example, `bug-SIGSEGV.vim`)
```vim
vim9script

def Test(Callback: func())
  Callback()
enddef

lua << EOF
vim.fn.Test(function () print('Hello') end)
EOF

```
2. Open Vim using custom vimrc
```
 ❯ vim -u bug-SIGSEGV.vim
```
3. App immediately crashes with this output
```
Vim: Caught deadly signal SEGV
Vim: Finished.
fish: Job 1, 'vim -u bug-SIGSEGV.vim' terminated by signal SIGSEGV (Address boundary error)
```

### Expected behaviour

Vim9 correctly calls Lua functions like Vim8:
```vim
function Test(Callback)
  return a:Callback()
endfunction

lua << EOF
vim.fn.Test(function () print('Hello') end)
EOF

```

And prints `Hello`.

### Version of Vim

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 13 2022 20:56:28)
macOS version - x86_64
Included patches: 1-4950
Compiled by Homebrew

### Environment

OS: MacOS Big Sure 11.6 (20G165)
Terminal: Kitty
Shell: Fish

**Comment by lacygoill** [comment]
- [backtrace](https://github.com/vim/vim/files/8928705/gdb.txt)
- [valgrind log](https://github.com/vim/vim/files/8928706/valgrind.log)

**Comment by ajukraine** [comment]
@brammool that was fast 🏄‍♂️ thanks a lot!
