### ISSUE TITLE
Optimize HiDPI Screen on GVim Windows

### ISSUE THREAD

**Issue by namoen0301** [vim/vim#1059]
Hello,
![img_20160912_233953](https://cloud.githubusercontent.com/assets/4280572/18442528/c2850210-78d6-11e6-9d54-039b292065ea.jpg)

OS: Windows 10 + DPI 250% Zoom
Vim Version: 8.0
It looks like bad, Gvim window is too small to click it.
HiDPI Device has been used more and more commonly all over the world. I Hope vim can pay more attention on it.

Thank you!

**Comment by k-takata** [comment]
If you enable DirectWrite (DirectX), gvim will be shown better.
See `:help 'renderoptions'`.

**Comment by namoen0301** [comment]
No, The window still small

**Comment by chrisbra** [comment]
Setting the renderoptions, doesn't make the window bigger, but should improve the readability of the font.

**Comment by vim-ml** [comment]
On Wednesday, September 14, 2016 at 1:31:20 PM UTC-4, Christian Brabandt wrote:

> Setting the renderoptions, doesn't make the window bigger, but should improve the readability of the font.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub

Does directx work on the 32 bit version of windows.Adding this:

set encoding=utf-8  
set rop=type:directx,gamma:1.0,contrast:0.5,level:1,geom:1,renmode:4,taamode:1

causes:

**Comment by chrisbra** [comment]
I am not sure, what you are seeing, probably some kind of this: https://github.com/dcpurton/regfont/issues/1

**Comment by vim-ml** [comment]
On Wednesday, September 14, 2016 at 2:41:42 PM UTC-4, nor...@googlegroups.com wrote:

> I am not sure, what you are seeing, probably some kind of this: dcpurton/regfont#1
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub

Yep,was an issue with my font.Fixed thanks

**Comment by k-takata** [comment]
> Setting the renderoptions, doesn't make the window bigger, but should improve the readability of the font.

Our DirectWrite implementation does support High DPI and font scaling. If you look gui_dwrite.cpp, you will find the variables `mDpiScaleX` and `mDpiScaleY` which are used for scaling.
I think we need similar implementation for the traditional GDI renderer, but I don't have the motivation for it.

FYI, the current implementation doesn't support Per-Monitor DPI which is new in Windows 8.1. Maybe we should also support this.

**Comment by k-takata** [comment]
> I think we need similar implementation for the traditional GDI renderer, but I don't have the motivation for it.

Sorry, this is wrong. The traditional GDI renderer already supports font scaling.
The problem is the default font size. On my PC (scale: 150%), the default font size was 6.

@wbsdty331 
You need to set the font size with `'guifont'`.
E.g.:

``` vim
:set gfn=FixedSys:h11
```

or

``` vim
:set gfn=*   " You can also use the font dialog box to select the font.
```

**Comment by dantmnf** [comment]
The problem is the default font is Fixedsys 16px, which is a **bitmap font**.
Can we change it into an outline font?

**Comment by namoen0301** [comment]
I hope:

English: Consolas
Chinese: Microsoft YaHei UI

**DO NOT USE FixedSys**

**Comment by chrisbra** [comment]
@k-takata
would it be possible to fix dcpurton/regfont#1 for the directx 
rendering?

thanks,
Christian

**Comment by k-takata** [comment]
There are (at least?) two problems in the current implementation.
1. The default font size is not scaled.
   Currently, the default font size is 12 pixels. This is 9 points on 100% DPI scaling, but it becomes 6 points on 150% DPI scaling. The font size should be scaled on a High DPI environment. The following patch fixes the problem:
   https://bitbucket.org/k_takata/vim-ktakata-mq/src/34233db2e8ff8ffededb250909dc0af6793d3d54/fix-highdpi.patch?fileviewer=file-view-default
2. The default font is not a true type font.
   Currently, "Fixedsys" is used as the default. Because of this, sometimes unintended size of font is selected. (Of course the quality is worse than true type fonts.)
   The reason why FixedSys is the default might be that the font is the most portable fixed-pitch font on Windows. All versions and all languages of Windows must have FixedSys.
   It would be better if Vim can automatically select a true type font, but no good solutions for now.

**Comment by k-takata** [comment]
@chrisbra 
I haven't used regfont, but when I see the comments, I feel it difficult to fix.
I don't know is there any workaround for that CreateFontFromLOGFONT returns an error.

**Comment by vim-ml** [comment]
K.Takata (Vim Github Repository) wrote:

> If you enable DirectWrite (DirectX), gvim will be shown better.
> See |:help 'renderoptions'|.
> 
> ---
> 
> ???
> I get E149: Sorry, no help for renderoptions (8.0.6 64-bit).

**Comment by chrisbra** [comment]
Am 2016-09-21 10:24, schrieb vim-dev ML:

> K.Takata (Vim Github Repository) wrote:
> 
> > If you enable DirectWrite (DirectX), gvim will be shown better.
> > See |:help 'renderoptions'|.
> > 
> > ---
> > 
> > ???
> > I get E149: Sorry, no help for renderoptions (8.0.6 64-bit).

you need to type literally :h 'renderoptions'
(including the single apostrophes)

Best,
Christian

**Comment by boytom** [comment]
@wbsdty331 Hi，我就直接用简体中文了。你说的问题，英文用Consolas，中文用Microsoft YaHei UI，可以用这种方式实现：
1：自己编译gvim，编译的时候定义宏FEAT_PROPORTIONAL_FONTS，这样会让gvim列举非等宽字体，你就能看到Microsoft YaHei UI了；
2：在gvimrc里添加配置：
set gfn=Consolas:h10 gfw=Microsoft\ YaHei\ UI:h10
不过我不建议你这么做，中英文不能对齐。我一直想做个补丁，实现Visual Studio 那样的效果，可是没有时间。

**Comment by dantmnf** [comment]
@boytom If DirectWrite is enabled, Consolas will fallback to Microsoft Yahei on Simplified Chinese system (maybe displaying language, the first of language list, non-Unicode locale and/or other), and Microsoft Yahei will be scaled to fit the grid.

**Comment by boytom** [comment]
@dantmnf 虽然比GDI好了很多，但不是很完美。汉字在一行中是对齐的，英语字母会上下跳跃（打开文件时，英语字母显示在偏上的位置，用Ctrl+L刷新一下，英语字母就下来了），g q的下边不能显示。

**Comment by namoen0301** [comment]
@boytom 如果这样还不能解决的话我觉得只能上 MacType 单独渲染了

**Comment by dantmnf** [comment]
@boytom @wbsdty331 We can open a new issue to discuss it.

**Comment by chrisbra** [comment]
Am 2016-10-13 06:25, schrieb Liu Yixuan:

> @boytom [1] 如果这样还不能解决的话我觉得只能上
> MacType 单独渲染了

Can you please write english? Thanks.

**Comment by boytom** [comment]
So sorry about my poor English. If DirectWrite is enabled and gfn is Consolas, ASCII character looks like superscript of Chinese character of the same line(align with top) when Consolas fallbacks to Microsoft YaHei. But when you press CTRL-L to  clear and redraw the screen, ASCII character will fall down and  align Chinese character with bottom.

**Comment by joeky888** [comment]
Someone already made a font called "Microsoft YaHei Mono", you can google it.

`set guifont=Microsoft\ YaHei\ Mono:h20`

**Comment by joeky888** [comment]
![](http://i.imgur.com/w8QHdYT.png)

**Comment by askvictor** [comment]
Renderoptions and a sensible font make the editor and menu usable, but the icons are still tiny. Is there any way to embiggen them?

**Comment by k-takata** [comment]
No, currently icons are not scaled.

**Comment by D4D3VD4V3** [comment]
@askvictor The Windows Creators update has resolved this. The icons are fairly big enough now.
![img](https://cloud.githubusercontent.com/assets/16200286/25072335/1033996a-22e9-11e7-953e-8590e739b65a.png)

Oh, and this screenshot is from a 3K display.
To enable this, open the gvim.exe's properties:

![img2](https://cloud.githubusercontent.com/assets/16200286/25072361/cee34734-22e9-11e7-8289-17da1e8c8a79.jpg)

**Comment by chrisbra** [comment]
so this issue can be closed now?

**Comment by askvictor** [comment]
@chrisbra any chance of detecting a hidpi environment and automatically making sane defaults?

**Comment by zeroepoch** [comment]
I just wanted to add my 2 cents.  I have Windows 10 Creators Update as well although I'm not sure that changes anything.  I just installed gvim 8.0 today after updating Windows.  I never tried gvim on this monitor before the update.  I just added `set guifont=Consolas:h10:cANSI:qDRAFT` to _gvimrc and that was all I needed.  I tried to use the compatibility options first as @D4D3VD4V3 mentioned but it didn't work as well.  After reading `:help rop` as others mentioned I realized the problem was it was using GDI just because of the default font.  Switching to Consolas was the only thing I actually needed to do to get a good HiDPI display.  FYI, I have a Samsung 4k 28" display.

**Comment by namoen0301** [comment]
It looks like Windows 10 1703 solved this problem.
I will close this issue.

**Comment by snoopyjc** [comment]
After a recent W10 update, I am having the same problem.  Not only is the font extremely tiny, but the icons are also itty-bitty!

![image](https://user-images.githubusercontent.com/9206213/61156411-50a2ca00-a4c1-11e9-910b-46744e612f1a.png)

**Comment by mcabain** [comment]
Yeah, I just hit this installing GVim 8.2 on Windows 10 Version 10.0.18362 Build 18362

**Comment by k-takata** [comment]
Vim supports PerMonitorV2 since 8.2.4109. The discussions in this issue is now outdated.
Please use a newer version than that.

**Comment by redstreet** [comment]
@k-takata thanks for the pointer!

[vim.org](vim.org) says:

> The current stable version is [gvim_8.2.2825.exe](https://github.com/vim/vim-win32-installer/releases/download/v8.2.2825/gvim_8.2.2825_x86_signed.exe).
An alternative is the [standard self-installing executable](https://ftp.nluug.nl/pub/vim/pc/gvim82.exe), currently version 8.2.2824.

Would you happen to know where I could get 8.2.4109 from? Thanks!
