### ISSUE TITLE
Link error: undefined reference to `ch_log` when using --disable-channel

### ISSUE THREAD

**Issue by dpelle** [vim/vim#10598]
### Steps to reproduce

Vim-8.2.5136 fails to build (link error) when doing:
```
$ cd vim
$ ./configure --with-features=big --enable-gui=none --disable-channel
$ make -j12
...
/usr/local/pkg/gnu/bin/ld: objects/os_unix.o: in function `start_timeout':
/home/dope/sb/vim/src/os_unix.c:8326: undefined reference to `ch_log'
/usr/local/pkg/gnu/bin/ld: objects/regexp.o: in function `nfa_did_time_out':
/home/dope/sb/vim/src/regexp_nfa.c:4252: undefined reference to `ch_log'
/usr/local/pkg/gnu/bin/ld: objects/regexp.o: in function `bt_did_time_out':
/home/dope/sb/vim/src/regexp_bt.c:3167: undefined reference to `ch_log'
/usr/local/pkg/gnu/bin/ld: /home/dope/sb/vim/src/regexp_bt.c:3167: undefined reference to `ch_log'
/usr/local/pkg/gnu/bin/ld: /home/dope/sb/vim/src/regexp_bt.c:3167: undefined reference to `ch_log'
collect2: error: ld returned 1 exit status
link.sh: Linking failed
```

The `ch_log()` is only defined (in `channel.c`) when `FEAT_JOB_CHANNEL` is defined.
We could add `#ifdef FEAT_JOB_CHANNEL` around the call to `ch_log()` at `regexp_bt.c:3167`,
but why does it call this `ch_log()` function anyway?  Regexp code does not look related to channels.

### Expected behaviour

Vim should build successfully

### Version of Vim

Vim-8.2.5136

### Environment

xubuntu-18.04.6

**Comment by lindhobe** [comment]
Same thing with "`./configure --with-features=normal --disable-channel --without-x`".  This is on Debian Testing (bookworm).  My last successful build was on 8.2.5076.  I haven't gotten around to trying a git bisect yet.

**Comment by dpelle** [comment]
@lindhobe wrote:
> I haven't gotten around to trying a git bisect yet.

Git blame shows that the build break was introduced in:
```
tree f832a0c1dbe16fcbd944e4b735829279e75ea49d
parent 5ea38d1e7fd597ffde13b292d43e12747f20e97f
author Bram Moolenaar <Bram@vim.org> Fri Jun 17 15:17:10 2022 +0100
committer Bram Moolenaar <Bram@vim.org> Fri Jun 17 15:17:10 2022 +0100

patch 8.2.5115: search timeout is overrun with some patterns

Problem:    Search timeout is overrun with some patterns.
Solution:   Check for timeout in more places.  Make the flag volatile and
            atomic.  Use assert_inrange() to see what happened.
```

**Comment by dpelle** [comment]
This won't fix the bug, but since the variable `timout_flag` in os_unix.c is modified in a signal handler (`SIGALARM`), it should be `volatile sig_atomic_t` and not `volatile int`. Similarly, variable `alarm_pending`  which is currently an `int`  should be `volatile sig_atomic_t` as it is also changed in a `SIGALARM` handler in `os_unic.c`.

**Comment by brammool** [comment]
> This won't fix the bug, but since the variable `timout_flag` in
> os_unix.c is modified in a signal handler (`SIGALARM`), it should be
> `volatile sig_atomic_t` and not `volatile int`. Similarly, variable
> `alarm_pending`  which is currently an `int`  should be `volatile
> sig_atomic_t` as it is also changed in a `SIGALARM` handler in
> `os_unic.c`.

Can you explain why "volatile" is not enough?  A disadvantage of using
an atomic type is, as far as I know, that it adds overhead to accessing
the variable.  And we intentionally wanted that to be quick, so we can
check for a timeout in many places and not worry about the overhead.
AFAIK adding "volatile" only affects what happens when the value is
changed.  But I could be wrong.

I did some debugging when there was no "volatile" flag, and found that
after the signal handler was called it could take 50 msec before the
flag change was noticed.  I think the timer functions create a new
thread to implement the functionality, and passing a flag between
threads is not instantanious.  After adding "volatile" the flag change
was picked up much quicker.

-- 
It is too bad that the speed of light hasn't kept pace with the
changes in CPU speed and network bandwidth. -- ***@***.***>

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dpelle** [comment]
@brammool  wrote:

> Can you explain why "volatile" is not enough?

For a variable set in a signal handler, `volatile int` is almost fine.  It prevents compilation optimizations, making sure the variable is read/written from/to memory when accessed and not instead stored in a register or optimized in any other ways.  However, in theory `int` may not be atomic on all architectures (in the sense of being one instruction) and that's why we should use `volatile sig_atomic_t` for variable read/set in signal handlers.  For an exotic architecture, `short` may be atomic but not `int` and in such case `sig_atomic_t` could be typedef-ed to `short`.

This is only relevant for variables used in signal handlers. It should not be confused with C++ `std::atomic` which is used with multiple threads, and which has a different semantic, different behavior and different runtime cost than `volatile sig_atomic_t`.

For `alarm_pending`, it's more severe, since it's not even `volatile` in the latest code.

Also, why do we have the variables `Prev_interval`, `Prev_sigaction`, `Timout_flag`,
`Timer_active`, `Timer_handler_active`?   I think we should remove them, they are unsused.

In short, we should do:
```
diff --git a/src/os_unix.c b/src/os_unix.c
index 947f46f85..39bb43c4f 100644
--- a/src/os_unix.c
+++ b/src/os_unix.c
@@ -8251,7 +8251,7 @@ xsmp_close(void)
 /*
  * Implement timeout with timer_create() and timer_settime().
  */
-static volatile int timeout_flag = FALSE;
+static volatile sig_atomic_t timeout_flag = FALSE;
 static timer_t timer_id;
 static int     timer_created = FALSE;
 
@@ -8352,12 +8352,7 @@ delete_timer(void)
 /*
  * Implement timeout with setitimer()
  */
-static struct itimerval prev_interval;
-static struct sigaction prev_sigaction;
-static volatile int    timeout_flag         = FALSE;
-static int             timer_active         = FALSE;
-static int             timer_handler_active = FALSE;
-static int             alarm_pending        = FALSE;
+static volatile sig_atomic_t alarm_pending = FALSE;
 
 /*
  * Handle SIGALRM for a timeout.
```

**Comment by brammool** [comment]
Dominique wrote:

> @brammool  wrote:
> 
> > Can you explain why "volatile" is not enough?
> 
> For a variable set in a signal handler, `volatile int` is almost fine.
> It prevents compilation optimizations, making sure the variable is
> read/written from/to memory when accessed and not instead stored in a
> register or optimized in any other ways.  However, in theory `int` may
> not be atomic on all architectures (in the sense of being one
> instruction) and that's why we should use `volatile sig_atomic_t` for
> variable read/set in signal handlers.  For an exotic architecture,
> `short` may be atomic but not `int` and in such case `sig_atomic_t`
> could be typedef-ed to `short`.
> 
> This is only relevant for variables used in signal handlers. It should
> not be confused with C++ `std::atomic` which is used with multiple
> threads, and which has a different semantic, different behavior and
> different runtime cost than `volatile sig_atomic_t`.

Ah, yes, now I remember.  Thus there is no extra overhead using
sig_atomic_t.

Only risk is that sig_atomic_t will end up in the proto file, if a
system does not have it then it would cause a build error.  It looks
like it was already present in C89, should be OK then.

> For `alarm_pending`, it's more severe, since it's not even `volatile`
> in the latest code.
> 
> Also, why do we have the variables `Prev_interval`, `Prev_sigaction`,
> `Timout_flag`, `Timer_active`, `Timer_handler_active`?   I think we
> should remove them, they are unsused.

Prev_interval is unused, the manual page says we can pass NULL instead.
Prev_sigaction is actually used, the others too.  That is when falling
back to setitimer().

-- 
I have read and understood the above. X________________

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
