### ISSUE TITLE
Vim9: unexpected error when invoking '% delete _'

### ISSUE THREAD

**Issue by heavenshell** [vim/vim#10591]
### Steps to reproduce

Run this shell command:

```
vim -Nu NONE -S <(cat <<'EOF'
vim9script
silent % delete _
EOF
)
```

E1050 is raised:
```
E1050: Colon required before a range: % delete _
```

If not vim9script, it's works fine.
also, deletebufline() works fine.
```
vim -Nu NONE -S <(cat <<'EOF'
vim9script
silent deletebufline('%', 1, '$')
EOF
)
```

### Expected behaviour

No error is raised.

### Version of Vim

8.2.5125

### Environment

Operating system: Ubuntu 20.04
Terminal: Terminal.app(ssh from macOS)
value of $TERM: xterm-256color
shell: bash

### Logs and stack traces

```shell
Error detected while processing command line..script /dev/fd/11:
line    2:
E1050: Colon required before a range: % delete _
```
```

**Comment by bfrg** [comment]
You need to add a colon like the error message indicates:
```vim
silent :%delete _
```
