### ISSUE TITLE
typo in termdebug.vim, let v:swapchoice = '0'

### ISSUE THREAD

**Issue by robertbu** [vim/vim#10605]
### Steps to reproduce

typo

### Expected behaviour

Open source file in read-only mode

### Version of Vim

8.2.5141

### Environment

Linux

### Logs and stack traces

```shell
I think "let v:swapchoice = '0'", should be "let v:swapchoice = 'o'".
```

**Comment by brammool** [comment]
Thanks for noticing.  I'll fix it.
