### ISSUE TITLE
different behavier between vim and gvim, about `<C-_>`

### ISSUE THREAD

**Issue by dantezhu** [vim/vim#10602]
### Steps to reproduce

1. open vim.exe, type `Ctrl` and `-`, wait sometimes, it will show like this:
![image](https://user-images.githubusercontent.com/1105212/174634949-2cc4fe11-12c2-4423-bb37-b59953265afc.png)

2. open gvim.exe, type as before, it will show like this:
![image](https://user-images.githubusercontent.com/1105212/174635040-86c33601-001f-44f8-b5aa-f76b2736feb8.png)

3. The different behavier will make some bugs, such as tcomment.vim use `<c-_><c-_>` to comment line, but now it counld not works well.

### Expected behaviour

gvim should output as vim.
![image](https://user-images.githubusercontent.com/1105212/174634949-2cc4fe11-12c2-4423-bb37-b59953265afc.png)

### Version of Vim

8.2.5136

### Environment

windows 10 x64

**Comment by dantezhu** [comment]
I think this bug start from [v8.2.4807](https://github.com/vim/vim-win32-installer/releases/tag/v8.2.4807)

**Comment by brammool** [comment]
@LemonBoy
