### ISSUE TITLE
Test_signal_TSTP fails after v8.2.5060

### ISSUE THREAD

**Issue by neilhwatson** [vim/vim#10614]
### Steps to reproduce

```bash
   git checkout v8.2.5061
   export TEST_MAY_FAIL=Test_geometry
   ./configure \
      --enable-rubyinterp=yes \
      --enable-python3interp=yes \
      --with-python3-config-dir=$(python3-config --configdir) \
      --enable-perlinterp=yes \
      --enable-gui=gtk3 \
      --enable-cscope \
      --prefix=$HOME

   make -j3
   make test
   make install
```

### Expected behaviour

8.2.5060 builds, tests pass, and it installs.

### Version of Vim

8.2.5061

### Environment

1. Linux Debian 11, AMD64
2. bash 5.1.16
3. TERM = xterm-256color
4. Terminology 1.12.1 (Enlightenment)
5. dwm window manager

### Logs and stack traces

```shell
Executed:  5196 Tests
 Skipped:    58 Tests
  FAILED:     1 Tests


Failures:
	From test_signals.vim:
	Found errors in Test_signal_TSTP():
	Run 1:
	command line..script /home/neil/src/vim/src/testdir/runtest.vim[459]..function RunTheTest[44]..Test_signal_TSTP[40]..StopVimInTerminal[14]..WaitForAssert[2]..<SNR>6_WaitForCommon[11]..<lambda>14 line 1: Expected 'finished' but got 'running'
	Run 2:
	command line..script /home/neil/src/vim/src/testdir/runtest.vim[492]..function RunTheTest[44]..Test_signal_TSTP[40]..StopVimInTerminal[14]..WaitForAssert[2]..<SNR>6_WaitForCommon[11]..<lambda>18 line 1: Expected 'finished' but got 'running'
	Run 3:
	command line..script /home/neil/src/vim/src/testdir/runtest.vim[492]..function RunTheTest[44]..Test_signal_TSTP[40]..StopVimInTerminal[14]..WaitForAssert[2]..<SNR>6_WaitForCommon[11]..<lambda>22 line 1: Expected 'finished' but got 'running'
	Run 4:
	command line..script /home/neil/src/vim/src/testdir/runtest.vim[492]..function RunTheTest[44]..Test_signal_TSTP[40]..StopVimInTerminal[14]..WaitForAssert[2]..<SNR>6_WaitForCommon[11]..<lambda>26 line 1: Expected 'finished' but got 'running'
	Run 5:
	command line..script /home/neil/src/vim/src/testdir/runtest.vim[492]..function RunTheTest[44]..Test_signal_TSTP[40]..StopVimInTerminal[14]..WaitForAssert[2]..<SNR>6_WaitForCommon[11]..<lambda>30 line 1: Expected 'finished' but got 'running'
	Flaky test failed too often, giving up
```
```

**Comment by brammool** [comment]
Neil H Watson wrote:

> ### Steps to reproduce
> 
> ```bash
>    git checkout v8.2.5061
>    export TEST_MAY_FAIL=Test_geometry
>    ./configure \
>       --enable-rubyinterp=yes \
>       --enable-python3interp=yes \
>       --with-python3-config-dir=$(python3-config --configdir) \
>       --enable-perlinterp=yes \
>       --enable-gui=gtk3 \
>       --enable-cscope \
>       --prefix=$HOME
> 
>    make -j3
>    make test
>    make install
> ```
> 
> ### Expected behaviour
> 
> 8.2.5060 builds, tests pass, and it installs.
> 
> ### Version of Vim
> 
> 8.2.5061
> 
> ### Environment
> 
> 1. Linux Debian 11, AMD64
> 2. bash 5.1.16
> 3. TERM = xterm-256color
> 4. Terminology 1.12.1 (Enlightenment)
> 5. dwm window manager
> 
> ### Logs and stack traces
> 
> ```shell
> Executed:  5196 Tests
>  Skipped:    58 Tests
>   FAILED:     1 Tests
> 
> 
> Failures:
> 	From test_signals.vim:
> 	Found errors in Test_signal_TSTP():
> 	Run 1:
> 	command line..script /home/neil/src/vim/src/testdir/runtest.vim[459]..function RunTheTest[44]..Test_signal_TSTP[40]..StopVimInTerminal[14]..WaitForAssert[2]..<SNR>6_WaitForCommon[11]..<lambda>14 line 1: Expected 'finished' but got 'running'

Try changing the sleep time in line 38 from 0.006 to 0.1.

Previously this test was skipped with valgrind, because it was thought
not to work then.  When I change this sleep time it looks like it does
work.  Hopefully that also fixes your problem.

-- 
A consultant is a person who takes your money and annoys your employees while
tirelessly searching for the best way to extend the consulting contract.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
