### ISSUE TITLE
Python file doesn't automatically insert comment leader when pressing Enter.

### ISSUE THREAD

**Issue by hungpham3112** [vim/vim#10625]
### Steps to reproduce

1. vim --clean test.py
2. type "#" to comment a line and press `<Enter>`
3. see the result.

Video:

https://user-images.githubusercontent.com/75968004/175876394-9f64600d-6902-4d8d-8218-1e652df65dd4.mp4

### Expected behaviour

Auto-comment in python.

### Version of Vim

8.2.5151

### Environment

OS: Windows 11.
Term: Windows Terminal
Shell : Powershell 7.2.5

**Comment by dkearns** [comment]
You can add `:setlocal formatoptions+=r` to `~/.vim/after/ftplugin/python.vim` or more commonly to take care of all the usual comment cases `setlocal formatoptions-=t formatoptions+=croql`.

I think this should probably be added to the default ftplugin but it may have been omitted intentionally.

@tpict

**Comment by brammool** [comment]
Some people like to have this, some don't.  Better leave the plugin as it is.  You can set your preference, as Doug explained.
