### ISSUE TITLE
`WinScrolled` not triggered when resizing non-current window

### ISSUE THREAD

**Issue by noscript** [vim/vim#10628]
### Steps to reproduce

1. Run vim:
```sh
vim -g --clean +"autocmd WinScrolled * echo expand('<amatch>') localtime()" +"help" +"split"
```
2. Resize the top window by dragging the split. Window ID will be printed at the bottom.
3. Resize the middle window. Window ID is not printed.

### Expected behavior

Window ID is printed.

https://user-images.githubusercontent.com/717109/176027312-e972deee-edd5-4539-b1ff-1666f4ae41e1.mp4

### Version of Vim

8.2.5169

### Environment

OS: Debian 11
Terminal: GUI

**Comment by dezza** [comment]
Its the same behaviour in neovim where it is adapted from https://github.com/neovim/neovim/issues/18222

But it would be much more useful for visual updates if it was possible to trigger in any window. Otherwise I don't see an easy way to trigger when dragging the statusline/separator.

**Comment by noscript** [comment]
I have a path which I'm currently testing and I plan to submit a PR.

**Comment by dezza** [comment]
@noscript can you share in a repo or snippet, so I can test? :) I tried myself but `may_trigger_winscrolled` triggered only on curwin anyways so figured it needed refactoring.

`|WinScrolled|		after scrolling or resizing a window` 
The ambiguity is strong, both functionally and naming-wise if there were to exist a "global" version. If you don't want to break backwards compatibility with previous plugins a new event is preferred.

What I need is really `AnyWinResized`, it doesn't matter that it triggers when scrolled.

**Comment by noscript** [comment]
Here it is:

```diff
--- src/window.c
+++ src/window.c
@@ -6482,7 +6482,13 @@ win_new_height(win_T *wp, int height)
     // There is no point in adjusting the scroll position when exiting.  Some
     // values might be invalid.
     if (!exiting && *p_spk == 'c')
+    {
 	scroll_to_fraction(wp, prev_height);
+	win_T *old_curwin = curwin;
+	curwin = wp;
+	may_trigger_winscrolled();
+	curwin = old_curwin;
+    }
 }
 
     void
@@ -6625,6 +6631,10 @@ win_new_width(win_T *wp, int width)
 	curs_columns(TRUE);	// validate w_wrow
 	skip_update_topline = FALSE;
     }
+    win_T *old_curwin = curwin;
+    curwin = wp;
+    may_trigger_winscrolled();
+    curwin = old_curwin;
     redraw_win_later(wp, UPD_NOT_VALID);
     wp->w_redr_status = TRUE;
 }
```

>triggered only on curwin anyways 

I'm not 100% sure but from my observation auto-commands always run against current window and buffer, so those have to be set properly.

> What I need is really AnyWinResized

I wouldn't mind to have `WinScrolled` and `WinResized` separated.

**Comment by dezza** [comment]
Thanks, will test it out.

> I wouldn't mind to have `WinScrolled` and `WinResized` separated.
Exactly. I don't think this feature is fully baked, it never was in neovim.. It would indeed make much more sense to have them separate and have a global version of each or a way to make them global.

**Comment by brammool** [comment]
> Here it is:
> 
> ```diff
> --- src/window.c
> +++ src/window.c
> @@ -6482,7 +6482,13 @@ win_new_height(win_T *wp, int height)
>      // There is no point in adjusting the scroll position when exiting.  Some
>      // values might be invalid.
>      if (!exiting && *p_spk == 'c')
> +    {
>  	scroll_to_fraction(wp, prev_height);
> +	win_T *old_curwin = curwin;
> +	curwin = wp;
> +	may_trigger_winscrolled();
> +	curwin = old_curwin;

This is wrong, you must never just change "curwin" before triggering
an autocommand.  For example, "curbuf" will be invalid.  And also
commands like "close window" or "split" will break in various ways.

I would very much prefer to just trigger the WinScrolled event whenever
any window has scrolled (topline has changed) and perhaps also when the
window height has changed (last line in the window changed).  Then
provide information about what changed in some form.  v:event is
probably the place for that.  However, you never know why someone added
a WinScrolled autocmd and what change in the window layout matters for
that.  I would expect the plugin to grab the current situation, possibly
with getwininfo(), wait for the WinScrolled event, and the figure out
what changed since last time to decide what to do.  That also allows for
debouncing and various other efficiency and flicker improvements.

> I'm not 100% sure but from my observation auto-commands always run
> against current window and buffer, so those have to be set properly.

No, that's not true.  There is no strict rule, and it's already quite
confusing and has caused may bugs in the past.  That's why my proposal
is to NOT change the current window or buffer for new behavior (unless
it's really needed, like when there is no valid window to execute
commands in).

> > What I need is really AnyWinResized
> 
> I wouldn't mind to have `WinScrolled` and `WinResized` separated.

Let's try to keep it as simple as possible.  Multiple events mean we
need to decide about ordering, avoid double triggering, etc.  I think
one event that indicates what change is probably best.  If you drag the
status line and both change it's really one user action, triggering two
events may actually make it more complicated for a plugin to decide what
to do.

We may still change some behavior of very recently introduced
functionality, but older stuff needs to keep working as it was to avoid
breaking plugins.  It might also help plugin authors to not divert from
NeoVim unless there is a reason for it.  Just to avoid many if/else
conditions.

-- 
It is hard to understand how a cemetery raised its burial
cost and blamed it on the cost of living.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dezza** [comment]
`v:event` is a good idea. Changing the original `WinScrolled` to trigger everywhere however will force people to adapt to the new behaviour, but it will be a minor change for them if you can simply check against `window`-id provided in `v:event`. I like that solution.

**Comment by k-takata** [comment]
Closing.
