### ISSUE TITLE
How to change the vim title string in vim9script?

### ISSUE THREAD

**Issue by hungpham3112** [vim/vim#10638]
In the legacy vimscript, I used 

```
let &titlestring = "title" 
```

when I change to vim9script

``
var &titlestring = "title"
`` 

it got and error ```E1052: Cannot declare an option: &titlestring = "VIDE"  ```.

How can I modify it? Thanks for your help.

**Comment by bfrg** [comment]
Remove the `var`:
```vim
vim9script

&titlestring = "title"
```

**Comment by brammool** [comment]
Right, "var" is for a declaration, an assignment does not use a command.

**Comment by hungpham3112** [comment]
> Remove the `var` keyword:
> 
> ```viml
> vim9script
> 
> &titlestring = "title"
> ```

Thanks, it worked. So what's about `mapleader`? I remove the var keyword before it but it doesn't work

```
mapleader = " "
```

**Comment by dkearns** [comment]
`g:mapleader = " "`

This is discussed at `:help vim9-namespace`
