### ISSUE TITLE
has('patch-9.0.0') returns zero in vim 9.0.1

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#10640]
### Steps to reproduce

```bash
vim --cmd "echo has('patch-9.0.0')" --cmd "quit"
```

### Expected behaviour

It is supposed to output `1`, but actually vim outputs `0`.

btw: `has('patch-9.0.1')` can output `1` with vim 9.0.1.

### Version of Vim

9.0.1

### Environment

OS: Debian 10
Terminal: Windows Terminal

**Comment by brammool** [comment]
There is no patch 9.0.0, the first patch on 9.0 is 9.0.0001.

**Comment by skywind3000** [comment]
But why 

```bash
vim --cmd "echo has('patch-8.0.0')" --cmd "quit"
```

outputs:

```
1
```

??

**Comment by zeertzjq** [comment]
Because it has a smaller major version number.

**Comment by skywind3000** [comment]
ah, could be.

**Comment by brammool** [comment]
Well, OK, it looks a bit inconsistent, since has('patch-8.1.0') and has('patch-8.2.0') return 1.
Even though those patches didn't actually exist.  It would be a bit strange that when going to Vim 9.1 then has('patch-9.0.0') suddenly returns 1.
