### ISSUE TITLE
Vim 9 timers broken on Solaris

### ISSUE THREAD

**Issue by godlygeek** [vim/vim#10647]
### Steps to reproduce

Run `vim --clean` on a Solaris machine

Observe that an `E1286: Could not set timeout` error occurs.
On some machines I saw `E1286: Could not set timeout: Insufficient privileges`.
On others I got `E1286: Could not set timeout: Not owner` instead.

### Expected behaviour

Vim starts with no error messages.

### Version of Vim

9.0.9

### Environment

Oracle Solaris 11.3 SPARC

### Logs and stack traces

Truss output shows:
```
timer_create(4, 0xFFFFFFFF7FFFBE58, 0x1005C5754) Err#1 EPERM [proc_clock_highres]
```
which indicates that the error is coming from [this line](https://github.com/vim/vim/blob/abd56da30bae4a5c6c20b9363ccae12f7b126026/src/os_unix.c#L8321).

The root cause seems to be that `CLOCK_MONOTONIC` on Solaris is defined as an alias for `CLOCK_HIGHRES`:
```c
sys/time_impl.h:#define CLOCK_MONOTONIC         4       /* high resolution monotonic clock */
sys/time_impl.h:#define CLOCK_HIGHRES           CLOCK_MONOTONIC         /* alternate name */
```

and the `CLOCK_HIGHRES` timer requires superuser privileges with `timer_create`:
```
ERRORS
       The timer_create() function will fail if:
...
       EPERM     The specified clock ID, clock_id, is CLOCK_HIGHRES and the
                 {PRIV_PROC_CLOCK_HIGHRES} is not asserted in the effective
                 set of the calling process.
```

The configure script only attempts to link a program using `timer_create` before deciding to set `HAVE_TIMER_CREATE=1`, so it doesn't notice that it links successfully but fails with a runtime error unless run as a superuser.

We should fall back to using `setitimer` on Solaris instead (or possibly use `timer_create` with a different clock than `CLOCK_HIGHRES`). As a quick hack, this diff gets things working:
```diff
--- a/src/os_unix.c
+++ b/src/os_unix.c
@@ -8248,7 +8248,7 @@
 #endif // USE_XSMP

 #if defined(FEAT_RELTIME) || defined(PROTO)
-# if defined(HAVE_TIMER_CREATE) || defined(PROTO)
+# if (!defined(__sun) && defined(HAVE_TIMER_CREATE)) || defined(PROTO)
 /*
  * Implement timeout with timer_create() and timer_settime().
  */
--- a/src/gui.c
+++ b/src/gui.c
@@ -227,7 +227,7 @@
     int		exit_status;
     pid_t	pid = -1;

-#if defined(FEAT_RELTIME) && defined(HAVE_TIMER_CREATE)
+#if defined(FEAT_RELTIME) && (!defined(__sun) && defined(HAVE_TIMER_CREATE))
     // a timer is not carried forward
     delete_timer();
 #endif
```

though I suspect there's a cleaner solution.

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> Run `vim --clean` on a Solaris machine
> 
> Observe that an `E1286: Could not set timeout` error occurs.
> On some machines I saw `E1286: Could not set timeout: Insufficient privileges`.
> On others I got `E1286: Could not set timeout: Not owner` instead.
> 
> ### Expected behaviour
> 
> Vim starts with no error messages.
> 
> ### Version of Vim
> 
> 9.0.9
> 
> ### Environment
> 
> Oracle Solaris 11.3 SPARC
> 
> ### Logs and stack traces
> 
> ```shell
> Truss output shows:
> 
> timer_create(4, 0xFFFFFFFF7FFFBE58, 0x1005C5754) Err#1 EPERM [proc_clock_highres]
> 
> which indicates that the error is coming from [this line](https://github.com/vim/vim/blob/abd56da30bae4a5c6c20b9363ccae12f7b126026/src/os_unix.c#L8321).

Oh great, another Solaris quirck.  It has timer_create() but it doesn't
work the way one expects.

> The root cause seems to be that `CLOCK_MONOTONIC` on Solaris is defined as an alias for `CLOCK_HIGHRES`:
> ```c
> sys/time_impl.h:#define CLOCK_MONOTONIC         4       /* high resolution monotonic clock */
> sys/time_impl.h:#define CLOCK_HIGHRES           CLOCK_MONOTONIC         /* alternate name */
> ```
> 
> and the `CLOCK_HIGHRES` timer requires superuser privileges with `timer_create`:
> ```
> ERRORS
>        The timer_create() function will fail if:
> ...
>        EPERM     The specified clock ID, clock_id, is CLOCK_HIGHRES and the
>                  {PRIV_PROC_CLOCK_HIGHRES} is not asserted in the effective
>                  set of the calling process.
> ```
> 
> The configure script only attempts to link a program using `timer_create` before deciding to set `HAVE_TIMER_CREATE=1`, so it doesn't notice that it links successfully but fails with a runtime error unless run as a superuser.
> 
> We should fall back to using `setitimer` on Solaris instead (or possibly use `timer_create` with a different clock than `CLOCK_HIGHRES`). As a quick hack, this diff gets things working:
> ```diff
> --- a/src/os_unix.c
> +++ b/src/os_unix.c
> @@ -8248,7 +8248,7 @@
>  #endif // USE_XSMP
> 
>  #if defined(FEAT_RELTIME) || defined(PROTO)
> -# if defined(HAVE_TIMER_CREATE) || defined(PROTO)
> +# if (!defined(__sun) && defined(HAVE_TIMER_CREATE)) || defined(PROTO)
>  /*
>   * Implement timeout with timer_create() and timer_settime().
>   */
> --- a/src/gui.c
> +++ b/src/gui.c
> @@ -227,7 +227,7 @@
>      int		exit_status;
>      pid_t	pid = -1;
> 
> -#if defined(FEAT_RELTIME) && defined(HAVE_TIMER_CREATE)
> +#if defined(FEAT_RELTIME) && (!defined(__sun) && defined(HAVE_TIMER_CREATE))
>      // a timer is not carried forward
>      delete_timer();
>  #endif
> ```
> 
> though I suspect there's a cleaner solution.

We can make the configure check not only link but also run the program.

An alternative is to handle it at runtime: include both the code for
timer_create() and setitimer(), and fall back to the latter when the
first fails.

Since this system should be rare, using the configure check looks like a
better solution.

I'll make a patch, please try it out and reopen the issue if it doesn't
work.  Check src/auto/config.log for what happened then.

-- 
Micro$oft: where do you want to go today?
    Linux: where do you want to go tomorrow?
  FreeBSD: are you guys coming, or what?

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by godlygeek** [comment]
The patch does work. Thanks for the quick fix!

**Comment by Redfoxymoon** [comment]
This change introduces running a test program with autoconf which breaks cross-compilation...

**Comment by brammool** [comment]
> This change introduces running a test program with autoconf which
> breaks cross-compilation...

Can you suggest how to do this?  autoconf syntax is so complicate, it's
very easy to get it wrong.  I suppose it can be done with
AC_CACHE_CHECK().

-- 
Creating the world with Emacs:   M-x let-there-be-light
Creating the world with Vim:     :make world

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Redfoxymoon** [comment]
Considering this is an exception case I think a simple ifdef for solaris would be the better solution, alternatively a --with/--enable-timer-create that overrides the test perhaps?

**Comment by shak5009** [comment]
> Considering this is an exception case I think a simple ifdef for solaris would be the better solution, alternatively a --with/--enable-timer-create that overrides the test perhaps?

I second that.

**Comment by landfillbaby** [comment]
or do it like e.g. vim_cv_getcwd_broken

**Comment by brammool** [comment]
Patch 9.0.0065 should take care of it.
