### ISSUE TITLE
TextYankPost is called after Visual-mode exit

### ISSUE THREAD

**Issue by habamax** [vim/vim#10655]
### Steps to reproduce

1. `vim -Nu NONE`
2. `:au TextYankPost * echom "TextYankPost"`
3. `v<ESC>`
4. `:mess`

### Expected behaviour

There should not be `TextYankPost` message

### Version of Vim

9.0.30

### Environment

OS: Fedora 36
Terminal: Gnome Terminal
$TERM: xterm-256color

**Comment by habamax** [comment]
The `v:event` in this case is:

```
{'regcontents': [''], 'visual': true, 'inclusive': false, 'regname': '*', 'regtype': 'v', 'operator': 'y'}
```

**Comment by habamax** [comment]
Checked source code and it looks like intended behavior for when clipboard has `autoselect`, which is default in linux.

**Comment by Shane-XB-Qian** [comment]
it was a knew incompatible and regression case happened at before, after that, had to remove to 'autoselect' by user for consistent.
