### ISSUE TITLE
The length of `runtimepath` is limited, thus the number of plugins too

### ISSUE THREAD

**Issue by bimlas** [vim/vim#1066]
I think it's related to Vim itself too: https://github.com/junegunn/vim-plug/issues/520

**Comment by k-takata** [comment]
As far as I know, the length of `runtimepath` doesn't have a hard limit, but if you use `:set rtp` to show the value, the output is truncated to `MAXPATHL - 1` bytes (= 1023 bytes on Windows).
Related: https://groups.google.com/d/msg/vim_dev/m_qqHqS3SUw/EtGtMt5uUYoJ

**Comment by bimlas** [comment]
Didn't know about it - `:echo &rtp` shows the full path, thanks!
