### ISSUE TITLE
Wrong documentation about :h filename modifier for empty or single-part path

### ISSUE THREAD

**Issue by ddickstein** [vim/vim#10663]
The documentation for the `:h` filename modifier says the returned result will be empty: https://github.com/vim/vim/blob/b67f0c8e495cfbfc09d6c7ff670b8162faf07b01/runtime/doc/cmdline.txt#L998-L1007

But the returned result is actually `"."` when used with `fnamemodify`, and the documentation for `fnamemodify` doesn't mention any departure from this specification.
https://github.com/vim/vim/blob/b67f0c8e495cfbfc09d6c7ff670b8162faf07b01/runtime/doc/builtin.txt#L2865-L2879

`:echo expand("%:h")` on an unnamed buffer is empty, but `:echo fnamemodify("", ":h")` is `"."`.

**Comment by ddickstein** [comment]
I agree - I think this should just be solved w/ documentation.

**Comment by brammool** [comment]
I have made the change, and it will go out with the next runtime files update soon, so this can be closed. You can reopen it when you don't like the explanation.
