### ISSUE TITLE
Trojan:Script/Wacatac.B!ml found in windows installer

### ISSUE THREAD

**Issue by themizzi** [vim/vim#10666]
Apologies, I am unsure of the conventions for contributing to vim. However, this was reported today on my Windows 11 machine while installing `v9.0.0040` via `winget`.

<img width="381" alt="image" src="https://user-images.githubusercontent.com/1450775/177407960-befcd082-9c30-488c-be5b-c6398f3ab568.png">

**Comment by brammool** [comment]
Well, either that install.exe has actually be poisoned, or it's a false alarm.  Virus scanners work with signatures which can trigger false positives once in a while.
Compare the file (byte by byte) with the one you can download from here: http://ftp.vim.org/pub/vim/pc/vim90w32.zip
it is 190976 bytes long.  If yours has a different size it's likely been tampared with.

**Comment by chrisbra** [comment]
this is most likely a false positive. 

I got the download URLs from [wingets Vim 9.0.0040](https://github.com/microsoft/winget-pkgs/blob/master/manifests/v/vim/vim/9.0.0040/vim.vim.installer.yaml) release and tested them using virustotal:

- [gvim_9.0.0040_x64.exe](https://www.virustotal.com/gui/url/6851373a0e03c1398d9c780e778eaccfc157cf880648658a562327eb53db71ba)
- [gvim_9.0.0040_x86.exe](https://www.virustotal.com/gui/url/a69e7541182f923f4f7fd3f88348be0571ed469157901f5f1a0302491a9461f5)
- [vim90w32.zip](https://www.virustotal.com/gui/url/e5e0af40d39093bd0b230fee91061178753da5393c2f18b851f5e21e1ce127d0)

All clean. Please complain to your AV vendor. 

See also https://github.com/vim/vim-win32-installer/issues/275
