### ISSUE TITLE
`winrestcmd()` sequence is repeated twice

### ISSUE THREAD

**Issue by noscript** [vim/vim#10661]
### Steps to reproduce

1. Run vim
```
 vim -g --clean +'split' +'echo winrestcmd()'
```
2. Sequence of resize commands will be printed:
```vim
1resize 40|vert :1resize 175|:2resize 39|vert :2resize 175|:1resize 40|vert :1resize 175|:2resize 39|vert :2resize 175|
```

### Expected behaviour

```vim
1resize 40|vert :1resize 175|:2resize 39|vert :2resize 175
```

### Version of Vim

9.0.0035

### Environment

OS: Debian 11
Terminal: GUI

**Comment by brammool** [comment]
This is intentional.  I can't remember the example, but in some cases resizing one window cause another window, that was resized already, to change.  Therefore it is done twice.
Besides the longer string, this has no real problems, right?

**Comment by noscript** [comment]
No any real problem. Just an observation.
