### ISSUE TITLE
the emoji show incomplete when set rop=type:directx in gVim

### ISSUE THREAD

**Issue by gVimer** [vim/vim#10665]
### Steps to reproduce

  set gfn=MENLO:h14:b
  set rop=type:directx

emoji:
⚽
🥎
🏀
🏐

### Expected behaviour

![image](https://user-images.githubusercontent.com/6241431/177230222-1415c414-abf3-4fe3-bb05-1a7db98f0c58.png)

### Version of Vim

gVim8.2 gVim9.0

### Environment

Win10

**Comment by brammool** [comment]
I guess in this font those emoji characters are a bit more than double width.
We can't fix that in Vim.

**Comment by gVimer** [comment]
Almost all fonts are like this  When  set rop=type:directx in gVim

**Comment by gVimer** [comment]
I think it's easy to reproduce

**Comment by 4cq2** [comment]
> I guess in this font those emoji characters are a bit more than double width. We can't fix that in Vim.

I dont understand this point of view. At least with the soccer ball U+26BD, its existed since at least 2009:

https://emojipedia.org/soccer-ball

so why cant we support something that is 14 years old?

**Comment by k-takata** [comment]
Vim only supports fix-width fonts, which means that Vim assumes all the characters are single width or double width. However, emojis are often wider than the double-width characters. Changing how Vim renders the characters is not easy at all.
