### ISSUE TITLE
`:append!` doesn't respect 'noexpandtab'

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#10683]
### Steps to reproduce

1. Run `vim --clean`
2. Type `i\<Tab>foo\<Esc>:append!\<CR>bar\<CR>.`
3. The `bar` on the second line is indented using 8 spaces

### Expected behaviour

The `bar` on the second line is indented using a Tab

### Version of Vim

9.0

### Environment

Operating System: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> 1. Run `vim --clean`
> 2. Type `i\<Tab>foo\<Esc>:append!\<CR>bar\<CR>.`
> 3. The `bar` on the second line is indented using 8 spaces
> 
> ### Expected behaviour
> 
> The `bar` on the second line is indented using a Tab

This append command was implemented to be Vi compatible.
I don't expect many users to use it, only those who are used to the old
Vi way of doing things.  This hints at not changing how it already
works.

I haven't tried an old Vi version, but I think it worked the same way.
At least in all these years I haven't heard anybody complain.

Perhaps we can just adjust the documention, mentioning this is a
different kind of auto-indent?

-- 
From "know your smileys":
¯\_(ツ)_/¯   Shrug

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by zeertzjq** [comment]
I also noticed this as a difference between normal Ex mode `Q` and Vim enhanced Ex mode `gQ`.

**Comment by zeertzjq** [comment]
In Vim, `:append!` in `Q` Ex mode does use Tab as indent in this case. It's just `:append!` in `gQ` Vim enhance Ex mode and cmdline mode behaving differently.

**Comment by zeertzjq** [comment]
Oh, the indent doesn't apply to scripts. Then it may indeed be better to keep the current behavior, as doing the indent after the inserting the text can break script, while Tab are shown as `^I` when editing the comment line.
