### ISSUE TITLE
Error message characters are displayed incorrectly

### ISSUE THREAD

**Issue by CNMan** [vim/vim#1068]
v8.0
![2016-09-13_172724](https://cloud.githubusercontent.com/assets/8692234/18470691/5a9f4fe2-79e0-11e6-8de1-8acffee32bde.png)

v7.4
![2016-09-13_183558](https://cloud.githubusercontent.com/assets/8692234/18470803/03927cc8-79e1-11e6-833c-f3374d449e8b.png)

**Comment by CNMan** [comment]
DEL `set encoding=utf-8` from `.vimrc`
![2016-09-13_195203](https://cloud.githubusercontent.com/assets/8692234/18472705/934dff72-79eb-11e6-96f3-88f96a9f389c.png)

**Comment by k-takata** [comment]
Normally `set encoding=utf-8` should be at the top of your `.vimrc`.

**Comment by CNMan** [comment]
@k-takata thanks. it works.
