### ISSUE TITLE
errors suppressed at script level when autoload script sourced to evaluate 'foldexpr'

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#10685]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        var vimdir = '/tmp/.vim'
        &runtimepath = vimdir
        vimdir->delete('rf')
        vimdir->mkdir('p')
        var vimrc = $'{vimdir}/vimrc'
        var lines =<< trim END
            vim9script
            import autoload 'script.vim'
            &foldmethod = 'expr'
            &foldexpr = 'script.Func()'
        END
        lines->writefile(vimrc)
        lines =<< trim END
            vim9script
            eval [][0]
            echomsg 'no error'
        END
        var autodir = $'{vimdir}/autoload'
        autodir->mkdir('p')
        lines->writefile($'{autodir}/script.vim')
        execute $'source {vimrc}'
    EOF
    )

No error is given.  `no error` is echo'ed.

**Expected behavior**

An error is given:

    E684: List index out of range: 0

Because of `eval [][0]`.

**Version of Vim**

9.0 Included patches: 1-48

**Environment**

Operating system: Ubuntu 20.04.4 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: GNU bash, version 5.0.17

**Additional context**

I understand the rationale which explains why we don't give an error when evaluating a fold expression.  Giving an error for every single line in the current file would be too annoying for the user.  And we can set `'debug'` to get the error anyway.  From [`:help fold-expr`](https://vimhelp.org/fold.txt.html#fold-expr):

   > If there is some error in the expression, or the resulting value isn't
   > recognized, there is no error message and the fold level will be zero.
   > For debugging the 'debug' option can be set to "msg", the error messages will
   > be visible then.

But that's for an error inside the expression.
Here, the error is not inside the expression; it's inside the script which defines the function which evaluates the expression.  And the script is only sourced once.  It's not sourced for every single line of the current file.

IMO, we should give an error for mistakes in an autoload script, at the script level (including the compilation of functions).  Because – again – we only source an autoload script once; so we're not going to bother the user for every single line in their file.  Then, later, when the expression is actually evaluated, we do suppress errors (unless `'debug'` is not empty).

If we do not give any error, then at least we should consider documenting this.  As a suggestion, here is a patch:
```diff
diff --git a/runtime/doc/fold.txt b/runtime/doc/fold.txt
index 93efcbb66..f84f09cd3 100644
--- a/runtime/doc/fold.txt
+++ b/runtime/doc/fold.txt
@@ -112,6 +112,8 @@ You can change and restore them if you are careful.
 
 If there is some error in the expression, or the resulting value isn't
 recognized, there is no error message and the fold level will be zero.
+Same thing if the error is in an autoload script which defines a function which
+is referred to in the expression.
 For debugging the 'debug' option can be set to "msg", the error messages will
 be visible then.
 
```

**Comment by lacygoill** [comment]
> IMO, we should give an error for mistakes in an autoload script, at the script level (including the compilation of functions).

One might argue that it's not possible because it would break compatibility with existing scripts.

First, there is a mistake in the autoload script; it's already broken.  I think users would prefer getting an error message telling them what is broken and where; especially if they don't know about `'debug'`.

Second, if some users prefer keeping their legacy autoload script silently broken, then at least we could give an error for a Vim9 script.  Vim9 being less than 2 weeks old, I doubt many users would complain about that change; especially since it would make autoload scripts more reliable.

**Comment by lacygoill** [comment]
> And we can set 'debug' to get the error anyway.

But we won't think about it if the mistake is breaking a feature which has nothing to do with a fold expression.  Consider the possibility that the autoload script is used to implement different features; only one of them being a fold expression.

**Comment by brammool** [comment]
>    > IMO, we should give an error for mistakes in an autoload script, at the script level (including the compilation of functions).
> 
> One might argue that it's not possible because it would break
> compatibility with existing scripts.
> 
> First, there is a mistake in the autoload script; it's already broken.
> I think users would prefer getting an error message telling them what
> is broken and where; especially if they don't know about `'debug'`.
> 
> Second, if some users prefer keeping their legacy autoload script
> silently broken, then at least we could give an error for a Vim9
> script.  Vim9 being less than 2 weeks old, I doubt many users would
> complain about that change; especially since it would make autoload
> scripts more reliable.

This is mainly related to the autoload mechanism for imported Vim9
scripts.  We can give an error for that situation.

There is a tiny chance resetting emsg_off is not right, but it's hard to
know.  Let's see if anybody reports a problem.  If yes, then it's going
to be a bit complicated, it would require another flag to suppress
errors for evaluating an expression (there already are a few flags, I
don't like adding another one).

-- 
Never eat yellow snow.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
