### ISSUE TITLE
:match highlight of NS throws an exception

### ISSUE THREAD

**Issue by haron13-2019** [vim/vim#10690]
### Steps to reproduce

1.   Create shell script with following content (cat ./killer_3mat_ns.sh):   

    # script which defines Todo highlight for non-breakable space
    # and move cursor to opening brace of the braces pair
    echo -e "\n{\na\xc2\xa0b c\n}\n" > ./killer.txt
    echo -e "set nocompatible|syn on|color default\n\nautocmd BufReadPost *\n  \\\ exec \"3mat Todo /\\\xc2\\\xa0/\"" > ./killer_vimrc.vim
    # with that you will need move down one line yourself to expose the bug
    #vim -Nu ./killer_vimrc.vim -c 'normal gg' ./killer.txt
     vim -Nu ./killer_vimrc.vim -c 'normal ggj'  ./killer.txt
    # ^^^ this will move down for you with "j" and trigger the bug

2.  Execute it:

    bash ./killer_3mat_ns.sh

3.  Error message is shown:

    "./killer.txt" 5L, 13B
    Error detected while processing CursorMoved Autocommands for "*"..function <SNR>14_Highlight_Matching_Pair:
    line  148:
    E801: ID already taken: 3
    Press ENTER or type command to continue

### Expected behaviour

There should be no error message

### Version of Vim

9.0.0049 huge with GTK

### Environment

OS: openSUSE_Thumbleweed, cygwin
Terminal: xterm (xterm -v -> Xterm(372))
value of $TERM: xterm-256color
Shell: /bin/bash 5.1.16(1)-releaseOS: openSUSE_Thumbleweed, cygwin
Terminal: xterm (xterm -v -> Xterm(372))
$TERM: xterm-256color
Shell: /bin/bash (5.1.16(1)-release

### Logs and stack traces

```shell
:scriptnames
    1: ~/data/killer_3mat_ns/killer_vimrc.vim
    2: /usr/local/share/vim/vim90/syntax/syntax.vim
    3: /usr/local/share/vim/vim90/syntax/synload.vim
    4: /usr/local/share/vim/vim90/syntax/syncolor.vim
    5: /usr/local/share/vim/vim90/colors/lists/default.vim
    6: /usr/local/share/vim/vim90/filetype.vim
    7: /usr/local/share/vim/vim90/scripts.vim
    8: /usr/local/share/vim/vim90/autoload/dist/script.vim
    9: /usr/local/share/vim/vim90/colors/default.vim
   10: /usr/local/share/vim/vim90/plugin/getscriptPlugin.vim
   11: /usr/local/share/vim/vim90/plugin/gzip.vim
   12: /usr/local/share/vim/vim90/plugin/logiPat.vim
   13: /usr/local/share/vim/vim90/plugin/manpager.vim
   14: /usr/local/share/vim/vim90/plugin/matchparen.vim
   15: /usr/local/share/vim/vim90/plugin/netrwPlugin.vim
   16: /usr/local/share/vim/vim90/plugin/rrhelper.vim
   17: /usr/local/share/vim/vim90/plugin/spellfile.vim
   18: /usr/local/share/vim/vim90/plugin/tarPlugin.vim
   19: /usr/local/share/vim/vim90/plugin/tohtml.vim
   20: /usr/local/share/vim/vim90/plugin/vimballPlugin.vim
   21: /usr/local/share/vim/vim90/plugin/zipPlugin.vim
```

**Comment by chrisbra** [comment]
[:h :3match](https://vimhelp.org/pattern.txt.html#%3A3match) explicitly mentions you should not use it, because it is used by the matchparen plugin.


> :3mat[ch]
>                 Just like [:match](https://vimhelp.org/pattern.txt.html#%3Amatch) [a](https://vimhelp.org/insert.txt.html#a)bove, but set a separ[at](https://vimhelp.org/motion.txt.html#at)e m[at](https://vimhelp.org/motion.txt.html#at)ch.  Thus
>                 there can be three matches active at the same time.  The match
>                 with the lowest number has priority if several match at the
>                 same position.
>                 The "[:3match](https://vimhelp.org/pattern.txt.html#%3A3match)" command [is](https://vimhelp.org/motion.txt.html#is) used by the [matchparen](https://vimhelp.org/pi_paren.txt.html#matchparen) plugin.  You
>                 are suggested to use "[:match](https://vimhelp.org/pattern.txt.html#%3Amatch)" for manual matching and
>                 "[:2match](https://vimhelp.org/pattern.txt.html#%3A2match)" for another plugin.

So this is not a bug. Also, you probably want to use the `matchadd()` vimscript functionalitites for such things, which gives you more flexibility.
