### ISSUE TITLE
[test_netbeans .vim] Test_nb_basic() fails under Python 3

### ISSUE THREAD

**Issue by jonathonf** [vim/vim#1070]
While `test_netbeans.py` initially appears to be compatible with both Python 2 and Python 3 (in a similar way to other tests that complete successfully), Test_nb_basic() reliably fails under Python 3 (on Arch Linux):

```
From test_netbeans.vim:
Found errors in Test_nb_basic():
function RunTheTest[9]..Test_nb_basic[2]..<SNR>5_run_server[1]..RunServer[21]..Nb_basic line 12: Expected 3 but got 49
function RunTheTest[9]..Test_nb_basic[2]..<SNR>5_run_server[1]..RunServer[21]..Nb_basic line 13: Expected 20 but got 3
function RunTheTest[9]..Test_nb_basic[2]..<SNR>5_run_server[1]..RunServer line 23: 'Caught exception: Vim(call):E684: list index out of range: 6'
```

Arch Linux  has set `/usr/bin/python` to point to `/usr/bin/python3`. This is documented in e.g. PEP 394 [1]. The associated Arch task has replication of the issue. [2]

Setting the `python` symlink to point at python2,<s>or editing the `test_netbeans.py` shebang directly,</s> or specifying `python2` instead of `python` on line 14 of testdir/shared.vim, allows the test to complete successfully.

[1] https://www.python.org/dev/peps/pep-0394/
[2] https://bugs.archlinux.org/task/50742

```
Python 3.5.2 (default, Jun 28 2016, 08:46:01) 
[GCC 6.1.1 20160602] on linux
```

**Comment by brammool** [comment]
jonathonf wrote:

> While `test_netbeans.py` initially appears to be compatible with both
> Python 2 and Python 3 (in a similar way to other tests that complete
> successfully), Test_nb_basic() reliably fails under Python 3 (on Arch
> Linux):
> 
> ```
> From test_netbeans.vim:
> Found errors in Test_nb_basic():
> function RunTheTest[9]..Test_nb_basic[2]..<SNR>5_run_server[1]..RunServer[21]..Nb_basic line 12: Expected 3 but got 49
> function RunTheTest[9]..Test_nb_basic[2]..<SNR>5_run_server[1]..RunServer[21]..Nb_basic line 13: Expected 20 but got 3
> function RunTheTest[9]..Test_nb_basic[2]..<SNR>5_run_server[1]..RunServer line 23: 'Caught exception: Vim(call):E684: list index out of range: 6'
> ```
> 
> Arch Linux  has set `/usr/bin/python` to point to `/usr/bin/python3`.
> This is documented in e.g. PEP 394 [1]. The associated Arch task has
> replication of the issue. [2]
> 
> Setting the `python` symlink to point at python2, or editing the
> `test_netbeans.py` shebang directly, allows the test to complete
> successfully.

I can reproduce it if I force using Python 3.

I don't seen an obvious problem.  Any errors from test_netbeans.py?

## 

hundred-and-one symptoms of being an internet addict:
10E. You start counting in hex.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by jonathonf** [comment]
> Any errors from test_netbeans.py?

Not when running it directly (either with the default interpreter or `python3 test_netbeans.py`) - it sits apparently happily at "Listening on port nnnnn".

Output of `python3 -vvv test_netbeans.py`: https://gist.github.com/jonathonf/bca0eaded8fdff135227daffc3cfa189

A couple of attempts running this test by itself (by trying to manually parse the commands in testdir/Makefile) to get some more output. I suspect these are not useful as other tests also fail when I try this:

``` bash
/d/s/v/s/vim-8.0.0003/src/testdir$ VIMRUNTIME="../../runtime" ../vim -V1 -u unix.vim -U NONE -es -S runtest.vim test_netbeans.vim
GetLatestVimScripts is not vi-compatible; not loaded (you need to set nocp)
not found in 'packpath': "pack/*/start/*"
not found in 'packpath': "pack/*/start/*"
not found in 'runtimepath': "plugin/**/*.vim" 
"test_netbeans.vim" 
"test_netbeans.vim" 79 lines, 2100 characters
Executing /dev/shm/vim/src/vim-8.0.0003/src/testdir/test_netbeans.vim
Executing /dev/shm/vim/src/vim-8.0.0003/src/testdir/test_netbeans.vim
Executing Last
Executing Last
Executing Test_nb_basic()
"README.txt" 
"README.txt" 49L, 2235C
Reading viminfo file "viminfo" marks
Executing Test_nb_basic()
"README.txt" 
"README.txt" 49L, 2235C
Executing Test_nb_file_auth()
Executing from
Executing from
Executing set
Executing set
"test.log" 
"test.log" 355L, 25973C
"test.log" 
"test.log" 377L, 27586C written
Executed 11 tests
9 FAILED:
"messages" 
"messages" 1318L, 53202C
"messages" 
"messages" 1354L, 55189C written
```

``` bash
/d/s/v/s/vim-8.0.0003/src/testdir$ VIMRUNTIME="../../runtime" ../vim -V2 -u unix.vim -U NONE -es -S runtest.vim test_netbeans.vim
sourcing "unix.vim"
line 5: sourcing "setup.vim"
finished sourcing setup.vim
continuing in /dev/shm/vim/src/vim-8.0.0003/src/testdir/unix.vim
finished sourcing unix.vim
Searching for "plugin/**/*.vim" in "../../vimfiles,../../runtime,../../vimfiles/after"
sourcing "../../runtime/plugin/getscriptPlugin.vim"
GetLatestVimScripts is not vi-compatible; not loaded (you need to set nocp)
finished sourcing ../../runtime/plugin/getscriptPlugin.vim
sourcing "../../runtime/plugin/gzip.vim"
finished sourcing ../../runtime/plugin/gzip.vim
sourcing "../../runtime/plugin/logiPat.vim"
finished sourcing ../../runtime/plugin/logiPat.vim
sourcing "../../runtime/plugin/manpager.vim"
finished sourcing ../../runtime/plugin/manpager.vim
sourcing "../../runtime/plugin/matchparen.vim"
finished sourcing ../../runtime/plugin/matchparen.vim
sourcing "../../runtime/plugin/netrwPlugin.vim"
finished sourcing ../../runtime/plugin/netrwPlugin.vim
sourcing "../../runtime/plugin/rrhelper.vim"
finished sourcing ../../runtime/plugin/rrhelper.vim
sourcing "../../runtime/plugin/spellfile.vim"
finished sourcing ../../runtime/plugin/spellfile.vim
sourcing "../../runtime/plugin/tarPlugin.vim"
finished sourcing ../../runtime/plugin/tarPlugin.vim
sourcing "../../runtime/plugin/tohtml.vim"
finished sourcing ../../runtime/plugin/tohtml.vim
sourcing "../../runtime/plugin/vimballPlugin.vim"
finished sourcing ../../runtime/plugin/vimballPlugin.vim
sourcing "../../runtime/plugin/zipPlugin.vim"
finished sourcing ../../runtime/plugin/zipPlugin.vim
Searching for "pack/*/start/*" in "../../vimfiles,../../runtime,../../vimfiles/after"
not found in 'packpath': "pack/*/start/*"
Searching for "pack/*/start/*" in "../../vimfiles,../../runtime,../../vimfiles/after"
not found in 'packpath': "pack/*/start/*"
Searching for "plugin/**/*.vim" in "../../vimfiles,../../runtime,../../vimfiles/after"
not found in 'runtimepath': "plugin/**/*.vim" 
"test_netbeans.vim" 
"test_netbeans.vim" 79 lines, 2100 characters
line 0: sourcing "runtest.vim"
line 33: sourcing "small.vim"
finished sourcing small.vim
continuing in /dev/shm/vim/src/vim-8.0.0003/src/testdir/runtest.vim
line 46: sourcing "setup.vim"
finished sourcing setup.vim
continuing in /dev/shm/vim/src/vim-8.0.0003/src/testdir/runtest.vim
line 139: sourcing "test_netbeans.vim"
line 7: sourcing "shared.vim"
finished sourcing shared.vim
continuing in /dev/shm/vim/src/vim-8.0.0003/src/testdir/test_netbeans.vim
finished sourcing test_netbeans.vim
continuing in /dev/shm/vim/src/vim-8.0.0003/src/testdir/runtest.vim
Executing /dev/shm/vim/src/vim-8.0.0003/src/testdir/test_netbeans.vim
Executing /dev/shm/vim/src/vim-8.0.0003/src/testdir/test_netbeans.vim
Executing Last
Executing Last
Executing Test_nb_basic()
"README.txt" 
"README.txt" 49L, 2235C
Reading viminfo file "viminfo" marks
Executing Test_nb_basic()
"README.txt" 
"README.txt" 49L, 2235C
Executing Test_nb_file_auth()
Executing from
Executing from
Executing set
Executing set
"test.log" 
"test.log" 311L, 22747C
"test.log" 
"test.log" 333L, 24360C written
Executed 11 tests
9 FAILED:
"messages" 
"messages" 1246L, 49228C
"messages" 
"messages" 1282L, 51215C written
```

**Comment by brammool** [comment]
jonathonf wrote:

> > Any errors from test_netbeans.py?
> 
> Not when running it directly (either with the default interpreter or `python3 test_netbeans.py`) - it sits apparently happily at "Listening on port nnnnn".
> 
> Output of `python3 -vvv test_netbeans.py`: https://gist.github.com/jonathonf/bca0eaded8fdff135227daffc3cfa189

That's only starting the server.  If something goes wrong with decoding
a message it only happens when running the test.  It should be possible
to start the server and disable starting it in the text, but fill in the
port number.

> A couple of attempts running this test by itself (by trying to
> manually parse the commands in testdir/Makefile) to get some more
> output. I suspect these are not useful as other tests also fail when I
> try this:

On the Vim side it's usually best to use ch_logfile() and ch_log().
It has timestamps that show latency and timeouts.

## 

GALAHAD:   Camelot ...
LAUNCELOT: Camelot ...
GAWAIN:    It's only a model.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by jonathonf** [comment]
I'm not quite sure where to go with this next.

I set the port in `test_netbeans.py` line 71 to a known value, and ran a copy in a terminal.

``` python
if __name__ == "__main__":
    HOST, PORT = "localhost", 41414
```

I commented out line 17 in `test_netbeans.vim` so as not to start another server:

``` vim
func s:run_server(testfunc, ...)
  " call RunServer('test_netbeans.py', a:testfunc, a:000)
endfunc
```

and changed instances of `a:port` to `41414`:

``` vim
func Nb_basic(port)
  call delete("Xnetbeans")
  exe 'nbstart :localhost:' . 41414 . ':bunny'
  call assert_true(has("netbeans_enabled"))
```

I commented out `src/testdir/Makefile` lines 74-103 and edited line 129 to set this single test to run:

``` makefile
test_netbeans.res: test_netbeans.vim
    @echo "$(RUN_VIMTEST)" > vimcmd
    $(RUN_VIMTEST) -U NONE -S runtest.vim $*.vim
    @rm vimcmd
```

`make test` runs but does no actual testing:

``` bash
make[2]: Entering directory `/dev/shm/vim/vim-8.0.0003/src/testdir'
rm -f test.log messages
VIMRUNTIME=../../runtime; export VIMRUNTIME;  ../vim -f  -u unix.vim -U NONE --noplugin --not-a-term -U NONE -S runtest.vim test_netbeans.vim

Test results:
ALL DONE
make[2]: Leaving directory `/dev/shm/vim/vim-8.0.0003/src/testdir'
```

 If I uncomment `call RunServer` it complains it can't run another instance of the server (which of course it can't as I'm already running one on port 41414).

**Comment by brammool** [comment]
jonathon wrote:

> I'm not quite sure where to go with this next.
> 
> I set the port in `test_netbeans.py` line 71 to a known value, and ran a copy in a terminal.
> 
> ``` python
> if __name__ == "__main__":
>     HOST, PORT = "localhost", 41414
> ```
> 
> I commented out line 17 in `test_netbeans.vim` so as not to start another server:
> 
> ``` vim
> func s:run_server(testfunc, ...)
>   " call RunServer('test_netbeans.py', a:testfunc, a:000)
> endfunc
> ```
> 
> and changed instances of `a:port` to `41414`:
> 
> ``` vim
> func Nb_basic(port)
>   call delete("Xnetbeans")
>   exe 'nbstart :localhost:' . 41414 . ':bunny'
>   call assert_true(has("netbeans_enabled"))
> ```
> 
> I commented out `src/testdir/Makefile` lines 74-103 and edited line 129 to set this single test to run:
> 
> ``` makefile
> test_netbeans.res: test_netbeans.vim
>   @echo "$(RUN_VIMTEST)" > vimcmd
>   $(RUN_VIMTEST) -U NONE -S runtest.vim $*.vim
>   @rm vimcmd
> ```
> 
> `make test` runs but does no actual testing:
> 
> ``` bash
> make[2]: Entering directory `/run/shm/jf1077/vim/vim-8.0.0003/src/testdir'
> rm -f test.log messages
> VIMRUNTIME=../../runtime; export VIMRUNTIME;  ../vim -f  -u unix.vim -U NONE --noplugin --not-a-term -U NONE -S runtest.vim test_netbeans.vim
> 
> Test results:
> ALL DONE
> make[2]: Leaving directory `/run/shm/jf1077/vim/vim-8.0.0003/src/testdir'
> ```
> 
>  If I uncomment `call RunServer` it complains it can't run another instance of the server (which of course it can't as I'm already running one on port 41414).

Where you comment-out RunServer() you need to call the function that's
in the argument.  Pass the port as the argument to that function.

## 

```
   We're knights of the round table
   We dance whene'er we're able
   We do routines and chorus scenes
   With footwork impeccable.
   We dine well here in Camelot
   We eat ham and jam and spam a lot.
             "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD
```

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by jonathonf** [comment]
Ah yeah, there we go:

```
=== socket opened ===
received: AUTH bunny
0:version=0 "2.5"
0:startupDone=0

received: 0:fileOpened=0 "/dev/shm/vim/src/vim-8.0.0003/src/testdir/README.txt" T F

----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 43486)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "test_netbeans.py", line 55, in handle
    self.request.sendall(response)
TypeError: a bytes-like object is required, not 'str'
----------------------------------------
```

---

Notes for later reference:

``` vim
func s:run_server(testfunc, ...)
  " call RunServer('test_netbeans.py', a:testfunc, a:000)
  call Nb_basic(41414)
endfunc
```

No need to change a:port in Nb_basic() function body.

**Comment by brammool** [comment]
Jonathonf wrote:

> Ah yeah, there we go:
> 
> ```
> === socket opened ===
> received: AUTH bunny
> 0:version=0 "2.5"
> 0:startupDone=0
> 
> received: 0:fileOpened=0 "/dev/shm/vim/src/vim-8.0.0003/src/testdir/README.txt" T F
> 
> ----------------------------------------
> Exception happened during processing of request from ('127.0.0.1', 43486)
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
>     self.finish_request(request, client_address)
>   File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
>     self.handle()
>   File "test_netbeans.py", line 55, in handle
>     self.request.sendall(response)
> TypeError: a bytes-like object is required, not 'str'
> ----------------------------------------
> ```

Aha.  The this patch hopefully fixes it.  Please let me know whether it
does.

**\* ../vim-8.0.0004/src/testdir/test_netbeans.py    2016-09-09 15:27:58.000000000 +0200
--- src/testdir/test_netbeans.py    2016-09-14 22:22:03.574860055 +0200

---

**\* 52,58 ****
                  return

```
          if len(response) > 0:
```

!                 self.request.sendall(response)
                  # Write the respoinse into the file, so that the test can knows
                  # the command was sent.
                  with open("Xnetbeans", "a") as myfile:
--- 52,58 ----
                  return

```
          if len(response) > 0:
```

!                 self.request.sendall(response.encode('utf-8'))
                  # Write the respoinse into the file, so that the test can knows
                  # the command was sent.
                  with open("Xnetbeans", "a") as myfile:

## 

```
   Bravely bold Sir Robin, rode forth from Camelot,
   He was not afraid to die, Oh Brave Sir Robin,
   He was not at all afraid to be killed in nasty ways
   Brave, brave, brave, brave Sir Robin.
             "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD
```

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by jonathonf** [comment]
Looks good to me, a full build (of 8.0.0004) now completes with either Python 2 or Python 3.

**Comment by anatol** [comment]
Applying patch from https://github.com/vim/vim/issues/1070#issuecomment-247141940 makes tests at Arch Linux happy.
