### ISSUE TITLE
Feature Request: builtin function to test extended file attributes

### ISSUE THREAD

**Issue by matthew-cline** [vim/vim#1073]
There should be builtin functions for testing [extended file attributes](https://en.wikipedia.org/wiki/Extended_file_attributes).  In Linux I can do:

```
let result=system('getfattr -n user.ATTR file')

if !v:shell_error && ...
  ...
endif
```

However:
1. This isn't portable.
2. If I want to test for multiple attributes in a single `if` statement I have to call `system()` multiple times, saving `v:shell_error` each time.

**Comment by chrisbra** [comment]
Am 2016-09-14 10:13, schrieb matthew-cline:

> There should be builtin functions for testing extended file attributes
> [1]. In Linux I can do:
> 
> let result=system('getfattr -n user.ATTR file')
> 
> if !v:shell_error && ...
>   ...
> endif
> 
> However:
> - This isn't portable.
> - If I want to test for multiple attributes in a single if statement
>   I have to call system() multiple times, saving v:shell_error each
>   time.

Isn't this filesystem dependent?
Even if we add something like this to Vim, it won't be portable as well 
(probably).
And since Vim is no operating system (yet), I really doubt the general 
usage.

**Comment by chrisbra** [comment]
i am closing this, as this is obviously out of scope for a text editor
