### ISSUE TITLE
starting vim -c command works sometimes for all windows but sometimes only for the first one

### ISSUE THREAD

**Issue by Anton-Wessel** [vim/vim#10732]
vim version 8.2 (2019 Dec 12, compiled Jan 31 2021 04:47:07)

invoking vim by

vim -c 'set statusline=aaa'  -c 'exec "norm ixxx\<Esc>"' ' -o /tmp/WEx7 /tmp/WEx8 /tmp/WEx9

vim opens three windows. 

the first -c command is applied to all three windows, i.e. all three status lines contain "aaa".

the second -c command is applied only to the first window, only file /tmp/WEx7 gets the content "xxx".

how can I write a workaround in order all three files to get the text "xxx".

Regards

Anton_Wessel@t-online.de

**Comment by nickspoons** [comment]
With [:h :windo](https://vimhelp.org/windows.txt.html#%3Awindo):

```vim
vim -c 'set statusline=aaa' -c 'windo norm! ixxx' -o /tmp/WEx7 /tmp/WEx8 /tmp/WEx9
```

But please note that this is a bug tracker, and is not the right place for asking user questions. Try  the [google mailing list](https://groups.google.com/g/vim_use), the [irc channel](https://www.vi-improved.org/), or [vi.stackexchange.com](https://vi.stackexchange.com/).

**Comment by Anton-Wessel** [comment]
thanks, I learned that is nit a bug but my unknowing, Regards.
