### ISSUE TITLE
Vim 9.0 : cannot use AltGr+Space in gvim.exe

### ISSUE THREAD

**Issue by salsifis** [vim/vim#10753]
Hello
I am using the following version of gVim:

<details><summary>Details of `:ver` output</summary>
<p>

    :ver
    VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jul 16 2022 22:02:38)
    MS-Windows 64-bit GUI version with OLE support
    Included patches: 1-55
    Compiled by appveyor@APPVYR-WIN
    Huge version with GUI.  Features included (+) or not (-):
    +acl                +cindent            +cursorshape        -farsi              +job                +menu               +packages           +reltime            -sun_workshop       -tgetent            +visualextra
    +arabic             +clientserver       +dialog_con_gui     +file_in_path       +jumplist           +mksession          +path_extra         +rightleft          +syntax             +timers             +vreplace
    +autocmd            +clipboard          +diff               +find_in_path       +keymap             +modify_fname       +perl/dyn           +ruby/dyn           +tag_binary         +title              -vtp
    +autochdir          +cmdline_compl      +digraphs           +float              +lambda             +mouse              +persistent_undo    +scrollbind         -tag_old_static     +toolbar            +wildignore
    +autoservername     +cmdline_hist       +directx            +folding            +langmap            +mouseshape         +popupwin           +signs              -tag_any_white      +user_commands      +wildmenu
    +balloon_eval       +cmdline_info       -dnd                -footer             +libcall            +multi_byte_ime/dyn -postscript         +smartindent        -tcl                +vartabs            +windows
    -balloon_eval_term  +comments           -ebcdic             +gettext/dyn        +linebreak          +multi_lang         +printer            +sodium/dyn         -termguicolors      +vertsplit          +writebackup
    +browse             +conceal            +emacs_tags         -hangul_input       +lispindent         +mzscheme/dyn       +profile            +sound              +terminal           +vim9script         -xfontset
    ++builtin_terms     +cryptv             +eval               +iconv/dyn          +listcmds           +netbeans_intg      +python/dyn         +spell              -termresponse       +viminfo            -xim
    +byte_offset        +cscope             +ex_extra           +insert_expand      +localmap           +num64              +python3/dyn        +startuptime        +textobjects        +virtualedit        +xpm_w32
    +channel            +cursorbind         +extra_search       +ipv6               +lua/dyn            +ole                +quickfix           +statusline         +textprop           +visual             -xterm_save
       system vimrc file: "$VIM\vimrc"
         user vimrc file: "$HOME\_vimrc"
     2nd user vimrc file: "$HOME\vimfiles\vimrc"
     3rd user vimrc file: "$VIM\_vimrc"
          user exrc file: "$HOME\_exrc"
      2nd user exrc file: "$VIM\_exrc"
      system gvimrc file: "$VIM\gvimrc"
        user gvimrc file: "$HOME\_gvimrc"
    2nd user gvimrc file: "$HOME\vimfiles\gvimrc"
    3rd user gvimrc file: "$VIM\_gvimrc"
           defaults file: "$VIMRUNTIME\defaults.vim"
        system menu file: "$VIMRUNTIME\menu.vim"
    Compilation: cl -c /W3 /GF /nologo -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_TERMINAL -DFEAT_SOUND -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL -DFEAT_IPV6   -DFEAT_XPM_W32 -DHAVE_SODIUM -DDYNAMIC_SODIUM -DDYNAMIC_SODIUM_DLL=\"lib
    sodium.dll\" /I "C:\libsodium\include" -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 /source-charset:utf-8 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG /Zl /MT /D_CRT_SECURE_NO_DEPRECATE /D_CRT_NONSTDC_NO_DEPRECATE -DFEAT_OLE -DFEAT_MBYTE_IME -DDYNAMIC_IME
     -DFEAT_GUI_MSWIN -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DFEAT_DIRECTX_COLOR_EMOJI -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua54.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -D
    FEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python310.dll\" -DFEAT_MZSCHEME -I "C:\racket\include" -DMZ_PRECISE_GC -DDYNAMIC_MZSCHEME -DDYNAMIC_MZSCH_DLL=\"libracket3m_da32rk.dll\" -DDYNAMIC_MZGC_DLL=\"libracket3m_da32rk.dll\" -D
    FEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl532.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_DLL=\"x64-msvcrt-ruby300.dll\" -DRUBY_VERSION=30 -DFEAT_HUGE /Fd.\ObjGXOULYHRZAMD64/ /Zi
    Linking: link /nologo /opt:ref /LTCG /HIGHENTROPYVA:NO oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib netapi32.lib uuid.lib user32.lib  /machine:AMD64 version.lib  winspool.lib comctl32.lib  libcmt.lib
    oleaut32.lib  /nodefaultlib:lua54.lib  /STACK:8388608  /nodefaultlib:python27.lib /nodefaultlib:python310.lib    winmm.lib WSock32.lib Ws2_32.lib xpm\x64\lib-vc14\libXpm.lib  /PDB:gvim.pdb -debug
</p>
</details>

I also use the [bépo](https://bepo.fr) keyboard layout.
This layout uses AltGr (the right-hand Alt key) as an accessor to many characters. In particular, AltGr+Space is the key combination for the underscore character.

In gVim 8.2, AltGr+Space works correctly.
However, In 9.0, AltGr+Space works in vim.exe, but does not in gvim.exe. It is interpreted as a space (in all modes).

I have launched both versions of gvim with `-u NONE` and can confirm that the problem is therefore not dependent on plugins. It is also not dependent on the environment as I launched both Vim 9.0 and 8.2 in parallel with the same parent process. The problem occurred only on gvim 9.0.

**Comment by brammool** [comment]
@LemonBoy

**Comment by ant0sha** [comment]
@salsifis: how do you install this "[bépo](https://bepo.fr/)" layout in windows? I found nothing in stock windows-10, nor can I add differente behaviour to space bar with std windows layout creator app - it claims "space bar has to result in spacing character in all shifted states" ?

**Comment by Chimrod** [comment]
Hello, I’m also affected, in the same conditions (salsifis described the issue better than I would did)

I’ve installed the driver bepo-1.1rc2-full.exe from https://bepo.fr/wiki/Windows

**Comment by salsifis** [comment]
Thank you, the latest signed build works perfectly :)
