### ISSUE TITLE
Add `out_noscroll` and `err_noscroll` to job options

### ISSUE THREAD

**Issue by noscript** [vim/vim#10750]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

When job output is written to an empty buffer, it will be scrolled. It is impossible to avoid scrolling and moving the cursor.

This behaviors is documented:

>When the buffer written to is displayed in a window and the cursor is in the
first column of the last line, the cursor will be moved to the newly added
line and the window is scrolled up to show the cursor if needed.

**Describe the solution you'd like**
Add `out_noscroll` and `err_noscroll` options.

**Describe alternatives you've considered**
There is no workaround.

**Comment by brammool** [comment]
> **Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
> 
> When job output is written to an empty buffer, it will be scrolled. It is impossible to avoid scrolling and moving the cursor.
> 
> This behaviors is documented:
> 
> >When the buffer written to is displayed in a window and the cursor is in the
> first column of the last line, the cursor will be moved to the newly added
> line and the window is scrolled up to show the cursor if needed.
> 
> **Describe the solution you'd like**
> Add `out_noscroll` and `err_noscroll` options.
> 
> **Describe alternatives you've considered**
> There is no workaround.

I would think the workaround is to move the cursor away from the last
line.  Isn't that working?  If this is really only about starting with
an empty buffer, adding a flag that also changes behavior when the
buffer is not empty is likely to trigger a request for another flag with
slightly different behavior.  I don't think such tweaking is useful
enough.

-- 
I AM THANKFUL...
...for a lawn that needs mowing, windows that need cleaning
and gutters that need fixing because it means I have a home.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bfrg** [comment]
@noscript A workaround is to avoid using `buffer` for the `out_io` and `err_io` options. 

You can always append to a prepared buffer using a `out_cb` (and `err_cb`) function together with `setbufline()` or `appendbufline()`.

Here's an example:
```vim
vim9script

var jobid: job

def Test()
    const bufnr: number = bufadd('job-buffer')
    bufload(bufnr)
    setbufvar(bufnr, '&buflisted', true)
    setbufvar(bufnr, '&buftype', 'nofile')
    silent deletebufline(bufnr, 1, '$')

    if bufnr->win_findbuf()->empty()
        execute 'vertical sbuffer' bufnr
        wincmd p
    endif

    if job_status(jobid) == 'run'
        job_stop(jobid)
    endif

    jobid = job_start([&shell, &shellcmdflag, 'for i in `seq 1 10000`; do echo "$i"; done'], {
        in_io: 'null',
        err_io: 'out',
        out_cb: (ch: channel, msg: string) => setbufline(bufnr, '$', [msg, '']),
        close_cb: (ch: channel) => {
            while ch_status(ch, {part: 'out'}) == 'buffered'
                setbufline(bufnr, '$', [ch_read(ch, {part: 'out'}), ''])
            endwhile
            deletebufline(bufnr, '$')
        }
    })

    if job_status(jobid) == 'fail'
        echohl ErrorMsg
        echomsg 'Failed to run job_start()'
        echohl None
    endif
enddef

command Test Test()
```

In the example above I use `setbufline()` in the `out_cb` function. When the job is done, I end up with an empty line at the very end of the buffer which I delete in the `close_cb` function. Alternatively, you can use `appendbufline(bufnr, 1, msg)`. In that case you will end up with an empty first line which you need to remove. A third option is use `setbufline(bufnr, 1, msg)` the first time the `out_cb` function is called, and afterwards `appendbufline(bufnr, '$', msg)`. In this case you won't end up with an empty line.

**Comment by noscript** [comment]
```vim
out_cb: (ch: channel, msg: string) => setbufline(bufnr, '$', [msg, '']),`
```

I was afraid that appending line-by-line would be slower than `"out_io": "buffer"` but there is no major difference.

>If this is really only about starting with
an empty buffer, adding a flag that also changes behavior when the
buffer is not empty is likely to trigger a request for another flag with
slightly different behavior. 

The flag would keep the scroll position for both empty and not empty buffer cases. I don't think there would be a need for another flag later. But workaround by @bfrg is good enough.

Thank you.
