### ISSUE TITLE
nnoremap expands rhs when it contains <Plug>

### ISSUE THREAD

**Issue by michelesr** [vim/vim#10759]
### Steps to reproduce

Start vim with `vim -u NONE`

```
:set nocompatible
:nnoremap <Plug>(foo) :echo "foo"<CR>
:nnoremap f <Plug>(foo)
```

Now, press `f` -> `foo` is printed

### Expected behaviour

Nothing should have happened, as `nnoremap f` was used instead of `nmap f`.

### Version of Vim

8.2 1-4836 and master (9.0 1-57)

### Environment

Tried on an alpine container:

```
docker run --rm -it alpine:latest
```
The sha of the docker image is `0ac33e5f5afa79e084075e8698a22d574816eea8d7b7d480586835657c3e1c8b`

**Comment by zeertzjq** [comment]
This is intentional behavior. See #9789.
