### ISSUE TITLE
ml_get errors when setting 'laststatus' in BufAdd autocommand while reusing quickfix buffer in nested autocommand

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#10761]
### Steps to reproduce

1. Run `vim --clean`
2. Source the following file:
```vim
set laststatus=0
copen
cclose
call setline(1, ['foo', 'bar', 'baz'])
3
autocmd User foo ++nested copen
autocmd BufAdd * let &laststatus = 2 - &laststatus
doautocmd User foo
```
3. ml_get errors

### Expected behaviour

No ml_get errors

### Version of Vim

9.0

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

**Comment by lacygoill** [comment]
- [backtrace](https://github.com/vim/vim/files/9158745/gdb.txt)
- [valgrind log](https://github.com/vim/vim/files/9158746/valgrind.log)
