### ISSUE TITLE
regression causing NULL pointer when using nested autocmd

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#10775]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        ['()']->writefile('/tmp/file')
        autocmd VimEnter * ++nested edit /tmp/file | split
        autocmd BufReadPost * autocmd SafeState * ++once foldclosed('.')
        autocmd WinEnter * matchadd('ErrorMsg', 'pat')
    EOF
    )

An error is given:

    E1209: Invalid value for a line number: "."

Press Enter; a different error is given:

    E38: Null argument

**Expected behavior**

No error is given, because the code is syntactically correct, and was working fine until recently.

**Version of Vim**

9.0 Included patches: 1-63

**Environment**

Operating system: Ubuntu 20.04.4 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: GNU bash, version 5.0.17

**Additional context**

Regression introduced in patch [9.0.0061](https://github.com/vim/vim/releases/tag/v9.0.0061).

---

According to [`:help E38`](https://vimhelp.org/message.txt.html#E38), something went wrong which resulted in a NULL pointer.

---

- [backtrace](https://github.com/vim/vim/files/9174746/gdb.txt)
- [valgrind log](https://github.com/vim/vim/files/9174747/valgrind.log)

**Comment by brammool** [comment]
> **Steps to reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(tee <<'EOF'
>         vim9script
>         ['()']->writefile('/tmp/file')
>         autocmd VimEnter * ++nested edit /tmp/file | split
>         autocmd BufReadPost * autocmd SafeState * ++once foldclosed('.')
>         autocmd WinEnter * matchadd('ErrorMsg', 'pat')
>     EOF
>     )
> 
> An error is given:
> 
>     E1209: Invalid value for a line number: "."
> 
> Press Enter; a different error is given:
> 
>     E38: Null argument
> 
> **Expected behavior**
> 
> No error is given, because the code is syntactically correct, and was
> working fine until recently.

It looks like the change to fix the cursor position in a nested
autocommand has uncovered an existing problem: Restoring the cursor from
the wrong window, where it was never set.

The simplest solution appears to be to not use a cursor position that
wasn't set.  I can't be sure this will work properly in every situation.

-- 
In a world without fences, who needs Gates and Windows?

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
