### ISSUE TITLE
exported functions call from sort.vim highlight error

### ISSUE THREAD

**Issue by habamax** [vim/vim#10770]
### Steps to reproduce

1. `vim -Nu NONE`
2. `syn on`, `set ft=vim`
3. type `sort.SomeFunc()`

`.` is highlighted in red

![image](https://user-images.githubusercontent.com/234774/180598082-02076985-dd9f-4c10-a355-241f9e2fd5c6.png)

![image](https://user-images.githubusercontent.com/234774/180598089-3ff5dba0-ea80-4022-af07-1522e0463526.png)

### Expected behaviour

Dot should not be highlighted in red.

### Version of Vim

9.0.57

### Environment

windows, fedora, both gvim and terminal

**Comment by brammool** [comment]
@cecamp

**Comment by EgZvor** [comment]
Seems to be working fine now, @habamax .

**Comment by chrisbra** [comment]
closing then
