### ISSUE TITLE
g:terminal_ansi_colors not setting background color of terminal in MacVim

### ISSUE THREAD

**Issue by craigmac** [vim/vim#10785]
### Steps to reproduce

1. MacVim latest (release 173, July 25, based on vim 9.0.065 huge) from [there](https://github.com/macvim-dev/macvim/releases/tag/snapshot-173)
2. Move any vim directory you have like `mv ~/.vim ~/.vim.bak` and/or `~/.vimrc` out of the way so we start with clean slate.
3. Start MacVim via GUI (/Applications/MacVim.app)
4. `:set termguicolors?` returns  `notermguicolors`
5. `:term`
6. `:echo term_getansicolors(bufnr())` returns:
```
['#000000', '#e00000', '#e0e000', '#0000e0', '#e000e0', '#e0e0e0',
'#808080', '#ff4040', '#40ff40', '#ffff40', '#4040ff', '#ff40ff', '#40ffff', '#ffffff']
```
Cannot find where this was set from, `$VIMRUNTIME/colors/macvim.vim` doesn't set `g:terminal_ansi_colors` so I assume it's hardcoded? Anyway for our purposes here in this bug I don't think it's relevant.
7. `:set termguicolors`
8. `:term`
9.  `:echo term_getansicolors(bufnr())` returns same hex colors as before
10. Now let's try explicity defining our own hex colors:
```
:call term_start('bash', { 'ansi_colors':  ['#1c1c1c', '#af5f5f', '#5f875f', '#87875f', '#5f87af', '#5f5f87', '#5f8787', '#6c6c6c', '#444444', '#ff8700', '#87af87', '#ffffaf', '#87afd7', '#8787af', '#5fafaf', '#ffffff']})
```
 These are the `g:terminal_ansi_colors` values from [apprentice](https://github.com/romainl/Apprentice/blob/9942d0bb0a5d82f7a24450b00051c1f2cc008659/colors/apprentice.vim#L19).
11. `:echo term_getansicolors(bufnr())` returns the `ansi_colors` we defined in step 10, but the background color is wrong. 
<img width="1012" alt="Screen Shot 2022-07-25 at 11 08 31 AM" src="https://user-images.githubusercontent.com/7416158/180814026-28de6255-2785-46dd-9e8b-24c2ad34c84d.png">
12. Restart MacVim, we'll try it another way
13. `:set termguicolors`
14. `:let g:terminal_ansi_colors = ['#1c1c1c', '#af5f5f', '#5f875f', '#87875f', '#5f87af', '#5f5f87', '#5f8787', '#6c6c6c', '#444444', '#ff8700', '#87af87', '#ffffaf', '#87afd7', '#8787af', '#5fafaf', '#ffffff']`
15. `:term`
16.  Same result, background color, doesn't apply.

May be related to https://github.com/vim/vim/issues/10347 and to https://github.com/vim/vim/issues/5993. 

### Expected behaviour

We should be able to apply the background color `#262626` to new terminal buffers. In Terminal.app the background of `:term` works just because it's falling back to my terminal emulator color profiles, which is set to the apprentice palette.

### Version of Vim

9.0.0065

### Environment

os: macos monterey 12.4
terminal: n/a (macvim release 173)
$TERM: empty 
shell: /bin/zsh

**Comment by lacygoill** [comment]
> Move any vim directory you have like mv ~/.vim ~/.vim.bak and/or ~/.vimrc out of the way so we start with clean slate.

You can also start with an ad-hoc and empty home:

    $ mkdir /tmp/home/$USER
    $ HOME=/tmp/home/$USER vim ...

---

   > 11. :echo term_getansicolors(bufnr()) returns the ansi_colors we defined in step 10, but the background color is wrong.

But the background color is not controlled by the 16 ANSI colors.  For example, in GNOME terminal, the background color is controlled by a different setting, outside the 16 color palette.  Same thing in Vim; the background is controlled by a different setting, outside [`g:terminal_ansi_colors`](https://vimhelp.org/terminal.txt.html#g%3Aterminal_ansi_colors); the [`Terminal`](https://vimhelp.org/syntax.txt.html#hl-Terminal) highlight group.

---

   > We should be able to apply the background color #262626 to new terminal buffers.

Where does this `#262626` color come from?  It was not present in the previous commands:

   > ['#000000', '#e00000', '#e0e000', '#0000e0', '#e000e0', '#e0e0e0',
   > '#808080', '#ff4040', '#40ff40', '#ffff40', '#4040ff', '#ff40ff', '#40ffff', '#ffffff']

   > :call term_start('bash', { 'ansi_colors':  ['#1c1c1c', '#af5f5f', '#5f875f', '#87875f', '#5f87af', '#5f5f87', '#5f8787', '#6c6c6c', '#444444', '#ff8700', '#87af87', '#ffffaf', '#87afd7', '#8787af', '#5fafaf', '#ffffff']})

   > 14. :let g:terminal_ansi_colors = ['#1c1c1c', '#af5f5f', '#5f875f', '#87875f', '#5f87af', '#5f5f87', '#5f8787', '#6c6c6c', '#444444', '#ff8700', '#87af87', '#ffffaf', '#87afd7', '#8787af', '#5fafaf', '#ffffff']

Anyway, if you want the background to be `#262626`, then you could try to set the `Terminal` highlight group like this:

    :highlight Terminal guibg=#262626

**Comment by craigmac** [comment]
Thank you, yes indeed the guibg setting is what I was after, I thought I would have to do something with `t_AB` or `t_8b` because GUI initialization resets termcap defaults.

**Comment by habamax** [comment]
I would open a separate issue describing actual problem:

Links defined in a colorscheme are cleared for a gui vim if colorscheme is called from `.vimrc` (e.g. `colo desert`).

If a colorscheme is called from .gvimrc all links are ok.
