### ISSUE TITLE
Disable mappings when terminal right-click menu is active

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#10781]
Mappings being applied when right-click menu is active is usually unexpected. If one has `<Up>` or `<Down>` mapped to `<Cmd>` mappings then `<Up>` and `<Down>` cannot be used to select items in terminal right-click menu. Disabling mappings, or only applying `'langmap'` (even in Insert mode), may be the more expected behavior for terminal right-click menu.

**Comment by brammool** [comment]
> Mappings being applied when right-click menu is active is usually
> unexpected. If one has `<Up>` or `<Down>` mapped to `<Cmd>` mappings
> then `<Up>` and `<Down>` cannot be used to select items in terminal
> right-click menu. Disabling mappings, or only applying `'langmap'`
> (even in Insert mode), may be the more expected behavior for terminal
> right-click menu.

Changing this may cause problems for those who rely on the current
behavior.

Generally this would be handled by adding a different mode for mappings.
But this seems to be a corner case.  Is it really worth adding another
mapping mode?  It makes things more complicated, especially when
considering backwards compatibility.

-- 
hundred-and-one symptoms of being an internet addict:
114. You are counting items, you go "0,1,2,3,4,5,6,7,8,9,A,B,C,D...".

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by zeertzjq** [comment]
Then it's better to keep the current behavior.
