### ISSUE TITLE
`setcmdline()`: ability to set the command line contents

### ISSUE THREAD

**Issue by andmis** [vim/vim#10796]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
I would like to be able to set the contents of the command line from Vim script.

**Describe the solution you'd like**
I would like a `setcmdline` function, the partner of the already-existing `setcmdline` function.

**Describe alternatives you've considered**
You can approximate this by using `feedkeys`, but that has many downsides. It is hacky, and it is asynchronous (the keys don't get processed immediately from Vim script).

**Comment by noscript** [comment]
This was implemented in 07ea5f150.
