### ISSUE TITLE
Separate highlighting for quickfix selected line - different than 'Search'

### ISSUE THREAD

**Issue by anishsane** [vim/vim#1080]
Currently quickfix window selected entry is shown with same highlighting as `Search` group.
Because of this, it's difficult to search for something within the quick fix window.
Plus I would rather like the ability to disable the highlighting for that line.

I have created [this patch](https://gist.github.com/anishsane/5125b87ea4cddb43985496abd26a43e7#file-quickfixcurrentline-patch) for vim8.

Also attached here.
[QuickFixCurrentLine.patch.zip](https://github.com/vim/vim/files/476459/QuickFixCurrentLine.patch.zip)

Let me know if this is useful.

**Comment by wincent** [comment]
Could you try submitting this as an actual PR, @anishsane? I'd find this really useful.

**Comment by justinmk** [comment]
This exists in Neovim but it is named `QuickFixLine`. I don't think "Current" qualifier is needed. Would be nice to use the same name.

**Comment by anishsane** [comment]
@wincent,  How do we upstream it? I don't know the process for reviews and submissions. I was told to post it as a suggestion here, with my implementation.

**Comment by wincent** [comment]
@anishsane: I'm referring to [submitting it as an actual pull request](https://help.github.com/articles/creating-a-pull-request/) (fork the repo, make a commit in it against the current `HEAD` of the master branch, push the commit to your fork, actually initiate the pull request).

**Comment by anishsane** [comment]
Sorry. I have never used git so far. So, not much aware of the terminologies.

I created a local commit and getting access denied for git push.

```
$ git push -v
Pushing to https://anishsane@github.com/vim/vim.git
Password for 'https://anishsane@github.com':  ******
remote: Permission to vim/vim.git denied to anishsane.
fatal: unable to access 'https://anishsane@github.com/vim/vim.git/': The requested URL returned error: 403
```

EDIT: I think I missed the forking part.

**Comment by chrisbra** [comment]
yeah, you cannot push to the vim/vim repository for good reasons. You need to push to your own repository. Alternatively, you can simply post the patch (`git log -v -p HEAD~1` or similar) to the vim-dev list or put up a link here to the patch.

**Comment by chrisbra** [comment]
Oh, I see you already created PR https://github.com/vim/vim/pull/1755 for that. So you figured it out for yourself already. However, it would be good to have a test

**Comment by brammool** [comment]
Closing, since there is a pull request.
