### ISSUE TITLE
focuslost/focusgained event is broken

### ISSUE THREAD

**Issue by Shane-XB-Qian** [vim/vim#10803]
### Steps to reproduce

foo.vim
`au focuslost * echom 'lost/' .. 'focus'`
`au focusgained   * echom 'gain/' .. 'focus'`

vim -Nu foo.vim
then switch terminal window once.

output:
lost/focus
gain/focus
lost/focus
gain/focus

### Expected behaviour

lost/focus
gain/focus

should be only `lost` *once* and `gain` again.

### Version of Vim

v9.0.89

### Environment

linux
// xfce-term
// xterm

**Comment by bfrg** [comment]
What is `t_fd` and `t_fe` set to? See `:h xterm-focus-event` for more details.

**Comment by Shane-XB-Qian** [comment]
> What is `t_fd` and `t_fe` set to

here that should be not about those, it default had those value.

here the problem is kicked off `gained` when/after `lost`, and kicked off `lost` when/before `gained`

**Comment by Shane-XB-Qian** [comment]
which should be only one `lost` event when lost, and only `gained` when gained.

**Comment by brammool** [comment]
It works fine for me.  I don't think this is a Vim problem.  Check the windowing system.

**Comment by Shane-XB-Qian** [comment]
ok, some dummy tweak on window manager, seems can workaround it a bit..
// so let it be...
