### ISSUE TITLE
Vim doesn't find ncurses when using `--enable-rubyinterp`

### ISSUE THREAD

**Issue by FredrikAugust** [vim/vim#1081]
Hey, vim fails to compile when I add the `--enable-rubyinterp` flag. It complains that it can't find the ncurses library:

```
checking for tgetent()... configure: error: NOT FOUND!
      You need to install a terminal library; for example ncurses.
      Or specify the name of the library with --with-tlib.
```

I have tried with `--with-tlib=ncurses`, but I still get an error (can't link or something along those lines).

When I compile without ruby it works just fine.

I'm running Fedora 24 x64, python-devel and ruby-devel is installed.

Have googled around, and people say I should reinstall `ncurses-devel`, but that doesn't help. Even recompiled it manually to make sure it was alright.

**Comment by k-takata** [comment]
Do you mean `--enable-rubyinterp`?

**Comment by FredrikAugust** [comment]
I do indeed, my bad

**Comment by mattn** [comment]
@FredrikAugust please close this.

**Comment by FredrikAugust** [comment]
The problem was not that I misspelled enable.

**Comment by FredrikAugust** [comment]
I would change the title but I'm on mobile atm

**Comment by k-takata** [comment]
Then please check the detail log `src/auto/config.log`.

**Comment by FredrikAugust** [comment]
Here: http://sprunge.us/IaOe

**Comment by chrisbra** [comment]
please check your build-environment. It seems to be caused by this error:

```
gcc: error: /usr/lib/rpm/redhat/redhat-hardened-ld: No such file or directory
```

which comes from your $LDFLAGS variable.

**Comment by FredrikAugust** [comment]
`echo $LDFLAGS` doesn't return anything.

**Comment by mattn** [comment]
I'm not sure but http://stackoverflow.com/questions/34624428/g-error-usr-lib-rpm-redhat-redhat-hardened-cc1-no-that-file-and-directory

**Comment by FredrikAugust** [comment]
Installed the package, but I still get the same error, and $LDFLAGS is still empty.

**Comment by FredrikAugust** [comment]
`src/auto/config.log`: http://sprunge.us/FaAA

**Comment by FredrikAugust** [comment]
I found this; might this be the problem? http://askubuntu.com/questions/644677/vim-binary-with-all-libraries-statically-linked

On line 4120 of my `config.log` this does appear. And my term is st, but I've set TERM to `xterm-256color` to satisfy ncurses, as my terminal doesn't work properly when the TERM var is set to `st-256color`.

**Comment by brammool** [comment]
Fredrik Madsen wrote:

> Hey, vim fails to compile when I add the `--include-rubyinterp` flag. It complains that it can't find the ncurses library:
> 
> ```
> checking for tgetent()... configure: error: NOT FOUND!
>       You need to install a terminal library; for example ncurses.
>       Or specify the name of the library with --with-tlib.
> ```
> 
> I have tried with `--with-tlib=ncurses`, but I still get an error (can't link or something along those lines).
> 
> When I compile without ruby it works just fine.
> 
> I'm running Fedora 24 x64, python-devel and ruby-devel is installed.
> 
> Have googled around, and people say I should reinstall `ncurses-devel`, but that doesn't help. Even recompiled it manually to make sure it was alright.

Most likely a bad flag is added when configuring Ruby.  That makes
following configure tests fail.  Check the src/auto/config.log for where
Ruby is configured.

## 

CONCORDE: Message for you, sir.
   He falls forward revealing the arrow with the note.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by FredrikAugust** [comment]
Here are the flags (AFAIK) for configuring ruby:

```
RUBY_CFLAGS='-I/usr/include -I/usr/include -DRUBY_VERSION=23'
RUBY_LIBS='-lruby -lpthread -ldl -lcrypt -lm '
RUBY_OBJ='objects/if_ruby.o'
RUBY_PRO='if_ruby.pro'
RUBY_SRC='if_ruby.c'
```

And here it finds ruby:

```
configure:7057: checking --enable-rubyinterp argument
configure:7066: result: yes
configure:7073: checking --with-ruby-command argument
configure:7082: result: defaulting to ruby
configure:7088: checking for ruby
configure:7106: found /usr/bin/ruby
configure:7118: result: /usr/bin/ruby
configure:7127: checking Ruby version
configure:7130: result: OK
configure:7132: checking Ruby rbconfig
configure:7138: result: RbConfig
configure:7140: checking Ruby header files
configure:7144: result: /usr/include
```

**Comment by nuko8** [comment]
Can you check if the following C program, say `conftest.c`

``` c
char tgetent ();
int main () { return tgetent (); }
```

compiles with "`gcc -o conftest conftest.c -lncurses`" on your machine?

If it compiles, then, try almost the same thing but with another command

```
gcc -o conftest -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector -rdynamic -Wl,-export-dynamic  -L/usr/local/lib conftest.c -lncurses
```

What happens with this?

**Comment by brammool** [comment]
Fredrik Madsen wrote:

> Here are the flags (AFAIK) for configuring ruby:
> 
> ```
> RUBY_CFLAGS='-I/usr/include -I/usr/include -DRUBY_VERSION=23'
> RUBY_LIBS='-lruby -lpthread -ldl -lcrypt -lm '
> RUBY_OBJ='objects/if_ruby.o'
> RUBY_PRO='if_ruby.pro'
> RUBY_SRC='if_ruby.c'
> ```
> 
> And here it finds ruby:
> 
> ```
> configure:7057: checking --enable-rubyinterp argument
> configure:7066: result: yes
> configure:7073: checking --with-ruby-command argument
> configure:7082: result: defaulting to ruby
> configure:7088: checking for ruby
> configure:7106: found /usr/bin/ruby
> configure:7118: result: /usr/bin/ruby
> configure:7127: checking Ruby version
> configure:7130: result: OK
> configure:7132: checking Ruby rbconfig
> configure:7138: result: RbConfig
> configure:7140: checking Ruby header files
> configure:7144: result: /usr/include
> ```

Look at the next compile command after this, compare with the one before
this.

## 

You got to work at a mill?  Lucky!  I got sent back to work in the
acid-mines for my daily crust of stale bread... which not even the
birds would eat.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by drmikehenry** [comment]
I ran into this problem on Fedora 25 (x86_64).  Vim's configure script asks ruby about ``LDFLAGS`` without a corresponding query regarding ``CFLAGS``:
https://github.com/vim/vim/blob/v8.0.0134/src/auto/configure#L7174
```sh
rubyldflags=`$vi_cv_path_ruby -r rbconfig -e "print $ruby_rbconfig::CONFIG['LDFLAGS']"`
```
Since Fedora 23, all RPMs have been "hardened" by default:
https://fedoraproject.org/wiki/Changes/Harden_All_Packages

When an RPM is built, the ``%configure`` macro used in the RPM SPEC file is automatically adjusted to provide ``CFLAGS``, ``LDFLAGS``, and several other environment variables using hardened settings.  When using Fedora's ruby package, the above query using ``rbconfig`` returns hardened linker flags.  Because Vim's configure script doesn't use a corresponding ``rbconfig`` to query ruby's ``CFLAGS``, the compiling and linking flags are mismatched, leading to the error:
```
configure: error: NOT FOUND!
      You need to install a terminal library; for example ncurses.
      Or specify the name of the library with --with-tlib.
```

In ``src/auto/config.log``, this mismatch of flags causes this error:
```
configure:11318: checking for tgetent in -lncurses
configure:11343: gcc -o conftest -g -O2  -L. -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,--enable-new-dtags -Wl,-z,relro    -L/usr/local/lib conftest.c -lncurses   -lselinux  >&5
/usr/bin/ld: /tmp/cckpDslF.o: relocation R_X86_64_PC32 against undefined symbol `tgetent' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
```

I can successfully build with a work-around, but I don't know enough about autoconf to suggest a proper fix to the configure script.  The work-around involves first installing some RPM-related packages:
```sh
sudo dnf install -y rpm-build redhat-rpm-config
```

Next, set these variables at the shell prompt via:
```sh
eval $(rpmbuild --eval '%{configure}' | egrep '^\s*[A-Z]+=')
```
The above uses ``rpmbuild --eval '%{configure}'`` to query the definition of the ``%configure`` macro which begins with a number of environment variable assignments.  This provides the same default compilation environment that is provided in the ``%configure`` macro.  Now running the below invocation succeeds:
```sh
./configure --quiet --with-features=huge --enable-rubyinterp
```

It seems to me that the configure script should set the global ``CFLAGS`` somehow in analogy to the way it's setting the global ``LDFLAGS`` based on ruby's built-in knowledge of how ``CFLAGS`` was set, something like this:
```sh
rubycflags=`$vi_cv_path_ruby -r rbconfig -e "print $ruby_rbconfig::CONFIG['CFLAGS']"`
```

But it's not clear to me where or how the above ``rubycflags`` variable should be incorporated into the global ``CFLAGS``.

**Comment by diptanu** [comment]
I hit the same problem on Fedora 27, can we get the fix @drmikehenry listed above in the source?

**Comment by FredrikAugust** [comment]
Closing as this doesn't appear to be a problem with vim, but rather with fedora.

**Comment by zdohnal** [comment]
Hi everyone!
If someone hits the same problem, the solution is to add:

LDFLAGS="$LDFLAGS -fPIC"

to 'configure' command line invocation. It seems something (probably a tool from autotools - autoconf) does not provide -fPIC into LDFLAGS in Fedora. Because when I manually compile the code (although I need to add <term.h> as include) with -lncurses, it compiles correctly. So either gcc/ld uses -fPIC without my notice, when I use gcc manually, or autoconf does not set it....

**Comment by brammool** [comment]
> Hi everyone!
> If someone hits the same problem, the solution is to add:
> 
> LDFLAGS="$LDFLAGS -fPIC"
> 
> to 'configure' command line invocation. It seems something (probably a
> tool from autotools - autoconf) does not provide -fPIC into LDFLAGS in
> Fedora. Because when I manually compile the code (although I need to
> add <term.h> as include) with -lncurses, it compiles correctly. So
> either gcc/ld uses -fPIC without my notice, when I use gcc manually,
> or autoconf does not set it....

Perhaps someone can make a patch for configure.ac to make this work?

-- 
How To Keep A Healthy Level Of Insanity:
4. Put your garbage can on your desk and label it "in".

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by zdohnal** [comment]
@brammool I can create a patch, sure - I thought it is more Fedora specific issue, not something you would want in project, so I did not create any pull request.

**Comment by brammool** [comment]
> @brammool I can create a patch, sure - I thought it is more Fedora
> specific issue, not something you would want in project, so I did not
> create any pull request.

The whole idea of autoconf is that it figures out system-specific things
for you, no need to manually tweak the compiler flags.


-- 
If Pacman had affected us as kids we'd be running around in dark rooms,
munching pills and listening to repetitive music.
                       -- Marcus Brigstocke

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by zdohnal** [comment]
@brammool Please see the referenced issue - if you want to do in different way, please tell me and I will change it.

**Comment by hasufell** [comment]
This is still an issue. I'm not sure why this ticket is closed or the linked PR abandoned.

**Comment by chrisbra** [comment]
if you can prepare a proper PR for that, please open a PR then. Thanks.
