### ISSUE TITLE
could not build latest version from windows powershell

### ISSUE THREAD

**Issue by prepstarr** [vim/vim#10834]
### Steps to reproduce

1. git clone the vim repository from github
2. use gnu make to try and build it and see your luck
3. well error will come it will say go to src directory to build it there and get the following error:

PS C:\can\vim\src> make
makefile:2204: la cible « tags » apparaît plus d'une fois dans la même règle.
rm -f auto/config.status auto/config.cache config.log auto/config.log
rm -f auto/config.h auto/link.log auto/link.sed auto/config.mk
touch auto/config.h
cp config.mk.dist auto/config.mk
cd testdir; C:/Program Files (x86)/GnuWin32/bin/make -f Makefile clean
/usr/bin/sh: -c: line 0: syntax error near unexpected token `('
/usr/bin/sh: -c: line 0: `cd testdir; C:/Program Files (x86)/GnuWin32/bin/make -f Makefile clean'
make: *** [testclean] Erreur 1

4. cry , sob and fail, do not enjoy the latest version of vim go to github.com and report the bug and pray that there will be a solution quickly.
5. pray and kickback as vim developers bring a happy and peaceful resolution promptly.

### Expected behaviour

vim makes itself and then there is a working version of vim with the latest most up to date version.

### Version of Vim

9, github repository latest build

### Environment

Operating System: Windows 10 regular
Terminal : Powershell 7.2.2

**Comment by prepstarr** [comment]
> Hmm, doesn't look like a problem with Vim but with the tools you are using.
> 
> Perhaps your shell is not set to the right program?

Why can't it build? What do I need to do to be able to make it build?

**Comment by k-takata** [comment]
You are using the wrong command to build. Running `make` doesn't work on Windows. Also, GnuWin32's make may not work.
Please see [src/INSTALLpc.txt](https://github.com/vim/vim/blob/master/src/INSTALLpc.txt) for how to set up the environment and for the build commands.

**Comment by prepstarr** [comment]
Seems like something wrong with makefile 2204 tags occurs more than once on the same rule

**Comment by k-takata** [comment]
Because you're using the wrong Makefile, which is for Unix. You must use `src/Make_ming.mak` instead.
