### ISSUE TITLE
Virtual text with newlines renders incorrectly

### ISSUE THREAD

**Issue by puremourning** [vim/vim#10842]
### Steps to reproduce

test_prop_text.vim:

```viml
" This line
" This should not be overwritten
set signcolumn=yes
silent! call prop_type_delete( "a_test" )
call prop_type_add( "a_test", #{ highlight: 'Error' } )
py3 vim.vars[ 'prop_id' ] = vim.eval( 'prop_add( 1, 12, #{ text: "Some text\nnewline", type: "a_test" } )' )

function! Clear()
  call prop_remove( #{ id: g:prop_id } )
endfunction

```

* `vim --clean -S test_prop_text.vim test_prop_text.vim`
* see the text prop renders the virtual text including the newline (unexpected?)
* move the cursor up/down - redraws over the virtual text
* `ctrl-l` does't clear it
* `:call Clear()` - this resolves it.

<img width="818" alt="Screenshot 2022-08-03 at 21 49 47" src="https://user-images.githubusercontent.com/10584846/182709020-c9e02d50-c5c3-4c62-88ce-617b18a6e70d.png">

I think the solution here is to just not allow newlines in virtual text (for now?) as this seems super hard to get right. Alternatively we could just replace them with a space or something like we do for tab characters.

### Expected behaviour

Either replace the newlines with something like a space, or raise an error.

### Version of Vim

9.0.137

### Environment

macOS

**Comment by brammool** [comment]
I think we need to disallow special characters like Tab and Newline in the text, otherwise it gets too complicated to compute what is displayed.

**Comment by puremourning** [comment]
Yeah I agree.
