### ISSUE TITLE
Multiple lines of `text_align: 'below'` virtual text overlap content

### ISSUE THREAD

**Issue by tpope** [vim/vim#10849]
### Steps to reproduce

1. `vim --clean`
2. `i1<CR>2<CR>3<CR><Esc>`
3.
    ```vim
    :call prop_type_add('test', #{highlight: 'TabLine'})
    :call prop_add(1, 0, #{type: 'test', text_align: 'below', text: 'first'})
    :call prop_add(1, 0, #{type: 'test', text_align: 'below', text: 'second'})
    ```

### Expected behaviour

```
1
first
second
2
3
```

### Version of Vim

9.0.0144

### Environment

Operating system: Ubuntu 22.04
Terminal: xterm
Value of $TERM: `xterm-256color`
Shell: Zsh

**Comment by brammool** [comment]
I do see the expected text, but the cursor is off by a line.

**Comment by tpope** [comment]
I'm seeing this:

```
1
first
second
3
```

The cursor can be positioned on the `1`, `second`, and `3` lines, further suggesting `second` is overlaid on top of the `2`.

Confirmed on 9.0.0146 as well.

**Comment by tpope** [comment]
Can confirm 9.0.0147 fixes it. Thanks!

**Comment by mattn** [comment]
Hmm, I implmented inlay-hints in vim-lsp and recent commits works well (but not perfect) but this change break something.

![screenshot](https://user-images.githubusercontent.com/10111/183254595-b888a52c-a603-4514-90ff-80eb42a52e4a.gif)
.

**Comment by brammool** [comment]
I cannot guess from an animated gif what is going on.

**Comment by mattn** [comment]
My issue was fixed in recent commits after my comment.
