### ISSUE TITLE
strftime() do not work well in win7.

### ISSUE THREAD

**Issue by wsdjeg** [vim/vim#1084]
I just intsall vim from https://github.com/vim/vim-win32-installer, and in win7  `echo strftime('%Y-%m-%dT%TZ')` do not show anything. but I have a vim.exe in PATH installed by git-bash, when I run vim in cmd. and then `echo strftime('%Y-%m-%dT%TZ')` will show me `2016-09-16T20:27:52Z`

**Comment by chrisbra** [comment]
`%T` is not a valid format argument on windows.

**Comment by wsdjeg** [comment]
~~which format should I use in window, I do not see it in doc.~~
I have got it.
