### ISSUE TITLE
virtual text not displayed with 'nowrap' and when 'text_align' is set to 'below

### ISSUE THREAD

**Issue by bfrg** [vim/vim#10851]
### Steps to reproduce

Run `vim --clean -S test.vim`, with
```vim
vim9script
edit foobar
&wrap = false
&showbreak = '+++ '
setline(1, '12345678')
prop_type_add('test', {highlight: 'Special'})
prop_add(1, 0, {
    type: 'test',
    text: 'the quick brown fox jumps over the lazy dog',
    text_align: 'below'
})
```

**Result:** virtual text is not displayed.

**Note:** When `wrap` is enabled, the virtual text is displayed but then the `showbreak` characters are also displayed before the virtual text.

### Expected behaviour

Virtual text should always be displayed.

### Version of Vim

9.0.147

### Environment

Linux

**Comment by brammool** [comment]
These are two separate issues - showing 'showbreak' and using 'nowrap'.

I fixed 'showbreak' for a text property below, I'm not sure what should happen for a wrapping text property.  Currently it does show the 'showbreak' text, and I would think that is OK.

When 'wrap' is off then with a "below" virtual text we break with the certainty that a buffer line always occupies one screen line, that is likely to require changes in various places.
Also, when 'wrap' is off truncating the virtual text should probably not happen.

**Comment by bfrg** [comment]
Thank you for the quick fix.

Unfortunately, now the virtual text is displayed in the sign column when it's enabled. This only happens with `set signcolumn=yes` and `set nowrap`.

Example:
```vim
vim9script
edit foobar
&wrap = false
&signcolumn = 'yes'
setline(1, '12345678')
prop_type_add('test', {highlight: 'Special'})
prop_add(1, 0, {
    type: 'test',
    text: 'the quick brown fox jumps over the lazy dog',
    text_align: 'below'
})
```
