### ISSUE TITLE
Netrw on Windows cannot browse to "root" directories.

### ISSUE THREAD

**Issue by Tumbler** [vim/vim#1085]
When on Windows in Vim8, netrw cannot browse to root directories. i.e. "C:\"

This is caused by the new function s:ComposePath. In it it restricts directories to 
be of the form `^\a:[/\\][^/\\]`.

**Comment by SamuelNewhouse** [comment]
I'm on Windows 10 and have the same problem.

**Comment by k-takata** [comment]
Which version of Netrw do you use?

**Comment by srensamblador** [comment]
Same here, can't move to a different partition either

**Comment by Tumbler** [comment]
This has been fixed in the most recent version of netrw. It is version 166a at time of writing and can be found [here](http://www.drchip.org/astronaut/vim/index.html#NETRW).
