### ISSUE TITLE
no error for using `#{` as the start of a comment

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#10855]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        def Func()
            #{ comment
            eval 0 + 0
        enddef
        Func()
    EOF
    )

No error is given.

**Expected behavior**

An error is given:

    E1170: Cannot use #{ to start a comment

**Version of Vim**

9.0 Included patches: 1-148

**Environment**

Operating system: Ubuntu 20.04.4 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: GNU bash, version 5.0.17

**Additional context**

If we move the comment after a non-commented statement, an error is correctly given:
```vim
vim9script
def Func()
    eval 0 + 0
    #{ comment
enddef
Func()
```
    E1170: Cannot use #{ to start a comment
    E1170: Cannot use #{ to start a comment
    E1170: Cannot use #{ to start a comment
    E1170: Cannot use #{ to start a comment
    E1170: Cannot use #{ to start a comment
    E1170: Cannot use #{ to start a comment
    E1170: Cannot use #{ to start a comment
    E1170: Cannot use #{ to start a comment

Which is expected, but inconsistent with what happens when the comment is written before any statement.
Also, why is the error given 8 times?  Once would be enough.

---

At the script level, no error is ever given, regardless of the position of the comment relative to the adjacent statement:
```vim
vim9script
#{ comment
eval 0 + 0
```
    no error
```vim
vim9script
eval 0 + 0
#{ comment
```
    no error

This is inconsistent with what happens in a function.

**Comment by brammool** [comment]
> **Steps to reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(tee <<'EOF'
>         vim9script
>         def Func()
>             #{ comment
>             eval 0 + 0
>         enddef
>         Func()
>     EOF
>     )
> 
> No error is given.
> 
> **Expected behavior**
> 
> An error is given:
> 
>     E1170: Cannot use #{ to start a comment

The error is expected, it is given to avoid using #{ as the start of a
dictionary.  This might happen when converting a function from legacy to
Vim9 syntax.

I'll make the error mention "in an expression".  

> If we move the comment after a non-commented statement, an error is correctly given:
> ```vim
> vim9script
> def Func()
>     eval 0 + 0
>     #{ comment
> enddef
> Func()
> ```
>     E1170: Cannot use #{ to start a comment
>     E1170: Cannot use #{ to start a comment
>     E1170: Cannot use #{ to start a comment
>     E1170: Cannot use #{ to start a comment
>     E1170: Cannot use #{ to start a comment
>     E1170: Cannot use #{ to start a comment
>     E1170: Cannot use #{ to start a comment
>     E1170: Cannot use #{ to start a comment
> 
> Which is expected, but inconsistent with what happens when the comment is written before any statement.
> Also, why is the error given 8 times?  Once would be enough.

Yeah, it should only give the error once.

> At the script level, no error is ever given, regardless of the position of the comment relative to the adjacent statement:
> ```vim
> vim9script
> #{ comment
> eval 0 + 0
> ```
>     no error
> ```vim
> vim9script
> eval 0 + 0
> #{ comment
> ```
>     no error
> 
> This is inconsistent with what happens in a function.

Yes, we should give the error here too.  Would this cause a problem for
anyone?  That's very unlikely.  And it's easy to fix.

-- 
hundred-and-one symptoms of being an internet addict:
252. You vote for foreign officials.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> The error is expected, it is given to avoid using #{ as the start of a dictionary.

The original issue was not about the presence of an error, but about its absence.  And it can still be reproduced.

Why don't we give an error here:
```vim
vim9script
def Func()
    #{ comment
    eval 0 + 0
enddef
Func()
```
    no error

Nor here:
```vim
vim9script
#{ comment
eval 0 + 0
```
    no error

But we do here:
```vim
vim9script
def Func()
    eval 0 + 0
    #{ comment
enddef
Func()
```
    E1170: Cannot use #{ to start a comment in an expression

And here:
```vim
vim9script
eval 0 + 0
#{ comment
```
    E1170: Cannot use #{ to start a comment in an expression

Why do we wait for a non-commented statement to appear before giving an error?  Even if giving an error is useless, it would make the rule easier to understand.

**Comment by lacygoill** [comment]
OK, I understand, it's because of `eval`.  So, the rule is that the error is only given in the middle of an expression, which is why the error message was changed.

**Comment by lacygoill** [comment]
I still find the rule confusing.

IMO, `#{` should never be allowed at the start of a comment.

Consider this snippet:
```vim
vim9script
 #{ key: 'value'}
    ->keys()
```
    line    3:
    E1050: Colon required before a range: ->keys()

The error is confusing, because:

   - the issue is not on line 3, but on line 2
   - `->` is not a range but a method call

If we disallowed `#{` all the time, even outside an expression, here is the error which would be given:
```vim
vim9script
 #{ key: 'value'}
    ->keys()
```
    line    2:
    E1170: Cannot use #{ to start a comment in an expression

This is more helpful.

**Comment by brammool** [comment]
> I still find the rule confusing.
> 
> IMO, `#{` should never be allowed at the start of a comment.
> 
> Consider this snippet:
> ```vim
> vim9script
>  #{ key: 'value'}
>     ->keys()
> ```
>     line    3:
>     E1050: Colon required before a range: ->keys()
> 
> The error is confusing, because:
> 
>    - the issue is not on line 3, but on line 2
>    - `->` is not a range but a method call
> 
> If we disallowed `#{` all the time, even outside an expression, here is the error which would be given:
> ```vim
> vim9script
>  #{ key: 'value'}
>     ->keys()
> ```
>     line    2:
>     E1170: Cannot use #{ to start a comment in an expression
> 
> This is more helpful.

OK, I suppose it's a bit inconsistent to allow #{ in some places and
not others.

-- 
hundred-and-one symptoms of being an internet addict:
257. Your "hundred-and-one" lists include well over 101 items, since you
     automatically interpret all numbers in hexadecimal notation.
     (hex 101 = decimal 257)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> OK, I suppose it's a bit inconsistent to allow #{ in some places and not others.

Thank you for the fix:
```vim
vim9script
#{ comment
eval 0 + 0
```
    E1170: Cannot use #{ to start a comment: #{ comment

Unfortunately, the issue persists in compiled code:
```vim
vim9script
def Func()
    #{ comment
    eval 0 + 0
enddef
Func()
```
    no error
