### ISSUE TITLE
Crash when joining lines that contain virtual text

### ISSUE THREAD

**Issue by bfrg** [vim/vim#10857]
### Steps to reproduce

1. Run `vim --clean -S test.vim`, with
```vim
vim9script
edit foobar
setline(1, '12')
prop_type_add('test', {highlight: 'Special'})
prop_add(1, 0, {
    type: 'test',
    text: 'the quick brown fox jumps over the lazy dog',
    text_align: 'below'
})
```
2. Move cursor one character to the right and hit enter in order to split the line after the 1.
3. Move cursor back to first line and hit `J` to join the lines.
4. Result:
```
Vim: Caught deadly signal ABRT
Vim: preserving files...
Vim: Finished.
Aborted
```

**Note:** this happens with all `text_align` options.

### Expected behaviour

No crashes.

### Version of Vim

9.0.151

### Environment

Linux

**Comment by lacygoill** [comment]
- [backtrace](https://github.com/vim/vim/files/9275192/gdb.txt)
- [ubsan log](https://github.com/vim/vim/files/9275193/ubsan.log)
- [valgrind log](https://github.com/vim/vim/files/9275194/valgrind.log)
