### ISSUE TITLE
Test_fuzzy_completion_bufname fails if the working directory contains the substring "SF"

### ISSUE THREAD

**Issue by jamessan** [vim/vim#10854]
### Steps to reproduce

Run testsuite when working directory contains `SF` as a substring.

Debian's builds run in a temporary directory, so the path has randomly generated strings.  One of those builds happened to have "SF" in the directory name, and thus failed test_cmdline.vim's Test_fuzzy_completion_bufname test.

### Expected behaviour

Test suite passes.

### Version of Vim

9.0.0135

### Environment

Debian

### Logs and stack traces

```shell
Failures: 
	From test_cmdline.vim:
	Found errors in Test_fuzzy_completion_bufname():
	command line..script /<<PKGBUILDDIR>>/src/vim-gtk3/testdir/runtest.vim[468]..function RunTheTest[44]..Test_fuzzy_completion_bufname line 5: Expected '"b SF' but got '"b /build/vim-RSFt5j/vim-9.0.0135/src/vim-gtk3/testdir/SomeFile.txt'
```

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> Run testsuite when working directory contains `SF` as a substring.
> 
> ### Expected behaviour
> 
> Test suite passes.
> 
> ### Version of Vim
> 
> 9.0.0135
> 
> ### Environment
> 
> Debian
> 
> ### Logs and stack traces
> 
> ```shell
> Debian's builds run in a temporary directory, so the path has randomly
> generated strings.  One of those builds happened to have "SF" in the
> directory name, and thus failed test_cmdline.vim's
> Test_fuzzy_completion_bufname test:
> 
> 
> Failures: 
> 	From test_cmdline.vim:
> 	Found errors in Test_fuzzy_completion_bufname():
> 	command line..script /<<PKGBUILDDIR>>/src/vim-gtk3/testdir/runtest.vim[468]..function RunTheTest[44]..Test_fuzzy_completion_bufname line 5: Expected '"b SF' but got '"b /build/vim-RSFt5j/vim-9.0.0135/src/vim-gtk3/testdir/SomeFile.txt'

Hmm, I think the simplest solution is to use a long file name.  Then the
match will almost never happen.

-- 
hundred-and-one symptoms of being an internet addict:
249. You've forgotten what the outside looks like.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
