### ISSUE TITLE
Vim 9, mouse=a and virtualedit=all does not work properly

### ISSUE THREAD

**Issue by Jack12816** [vim/vim#10868]
### Steps to reproduce

1. `:set mouse=a`
2. `:set ve=all`
3. Add some lines to the buffer

Click anywhere (any col) of an empty row, and see the cursor is place at the end of line.

See: https://s3-eu-west-1.amazonaws.com/jack12816/public/videos/vid-2022-08-08-213516.webm

### Expected behaviour

In Vim 8 (8.2.4827) this places the cursor at the clicked col, after the end of line.

### Version of Vim

9.0 Included patches: 1-135

### Environment

OS: Arch
Terminal: Alacritty + GVim
Value of $TERM: xterm-256color
Shell: Bash

**Comment by lacygoill** [comment]
> In Vim 8 (8.2.4827) this places the cursor at the clicked col, after the end of line.

Here is the list of patches containing "mouse" in their commit messages (after 8.2.4827):

- [8.2.4902](https://github.com/vim/vim/releases/tag/v8.2.4902)  mouse wheel scrolling is inconsistent
- [8.2.4916](https://github.com/vim/vim/releases/tag/v8.2.4916)  mouse in Insert mode test fails
- [8.2.4922](https://github.com/vim/vim/releases/tag/v8.2.4922)  mouse test fails on MS-Windows
- [8.2.4936](https://github.com/vim/vim/releases/tag/v8.2.4936)  MS-Windows: mouse coordinates for scroll event are wrong
- [8.2.4964](https://github.com/vim/vim/releases/tag/v8.2.4964)  MS-Windows GUI: mouse event test is flaky
- [8.2.4965](https://github.com/vim/vim/releases/tag/v8.2.4965)  GUI: testing mouse move event depends on screen cell size
- [8.2.4966](https://github.com/vim/vim/releases/tag/v8.2.4966)  MS-Windows GUI: mouse event test gets extra event
- [8.2.4967](https://github.com/vim/vim/releases/tag/v8.2.4967)  MS-Windows GUI: mouse event test sometimes fails
- [9.0.0048](https://github.com/vim/vim/releases/tag/v9.0.0048)  cursor in wrong column with mouse click after concealed text
- [9.0.0136](https://github.com/vim/vim/releases/tag/v9.0.0136)  after CTRL-Left-mouse click a mouse scroll also has CTRL

Can you bisect the issue to one of them?  9.0.0048 seems the most likely culprit.

**Comment by gdupras** [comment]
>9.0.0048 seems the most likely culprit.

You're right. 9.0.0047 works fine but not 9.0.0048.
