### ISSUE TITLE
`do` in diff mode does not remove manually created folds in replaced area

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#10861]
### Steps to reproduce

1. Run `vim --clean`
2. Source the following file:
```vim
call setline(1, ['a', 'b', 'g', 'h', 'i', 'j', 'k'])
vnew
call setline(1, ['a', 'b', 'c', 'd', 'e', 'f', 'j', 'k'])
windo diffthis
set foldmethod=manual
3,4fold
5
call feedkeys('do', 'tx')
```
3. The fold in now on lines 4,5

### Expected behaviour

The fold is removed

### Version of Vim

9.0.135

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

**Comment by zeertzjq** [comment]
It probably does not make sense to use `foldmethod=manual` in diff mode?

**Comment by brammool** [comment]
Commands like "do" and ":diffget" rely on the foldmethod to be "diff".
When you set it to "manual" you'll have to adjust folds manually.
