### ISSUE TITLE
"-- INSERT --" from showmode never clears with cmdheight=0

### ISSUE THREAD

**Issue by arp242** [vim/vim#10881]
If you set cmdheight to 0, the showmode text never clears:

    % vim --noplugin -u NONE +'cmdheight=0 showmode'

"-- INSERT --" shows, but after leaving insert mode it stays around until you press `:` or `^L`. Same with "-- REPLACE --"; it does seem to clear for "-- VISUAL --" or completions.

If you also disable the statusline:

    % vim --noplugin -u NONE +'cmdheight=0 showmode'

Then you get the same, and the `showmode` text displays "in" the statusline, overwriting your statusline text.

---

According to `:help showmode`, "the option has no effect when 'cmdheight' is zero", so that doesn't seem to work quite right. Personally, I think the behaviour when the statusline is disabled is actually okay (except for the not clearing part), and I can see how it might be okay with a statusline too if people right-align their statusline (although can replicate it easily with a custom statusline too).

Vim 9.0.0181 on Linux

**Comment by arp242** [comment]
FYI @Shougo

**Comment by arp242** [comment]
Another case I found:

    % vim --noplugin -u NONE +'set cmdheight=0 showmode'

and then:

    i<C-x><C-d><C-c>

Will display (while you're back in normal mode):

    -- INSERT --n completion (^D^N^P) E486: Pattern not found

**Comment by arp242** [comment]
And another; press `<C-c>`, which will display:

    Type  :qa  and press <Enter> to exit Vim

And that sticks until you do some command; should probably clear on cursor movement and scrolling? You can actually get some really weird effects with this:

    % vim --noplugin -u NONE +'set cmdheight=0'
    :call append(1, repeat(['x'], 100))
    <C-c><C-d>

Now "Type  :qa!  and press <Enter> to abandon all changes and exit Vim" is in the middle of the screen. Pressing e.g. `<C-l>`, `:`, or doing some normal mode command (e.g. `dd`) will clear it.

**Comment by arp242** [comment]
I guess this issue is a bit misnamed, because it seems *any* message that appears in the "cmdline window" gets stuck like this, for example an `:echo` from a `<silent>` mapping; you need to `:echo` from an expression mapping:

    :fun X()
    :  echo 'XXXX'
    :  return ''
    :endfun
    :nnoremap <silent> <expr> X X()

I found that through some plugins that do that.

---

Also discovered a related issue, I forgot the `<CR>` once while trying out some things to reproduce:

    :nnoremap <silent> X :echo 'XXX'

And the `:echo 'XXX' doesn't show up at all until you press space and then backspace.

**Comment by arp242** [comment]
Using `:!cmd` doubles the command, e.g. with `:!ls` you see:

![cap-2022-08-10T06:55:21](https://user-images.githubusercontent.com/1032692/183818941-703c6d83-075b-426e-adee-c59327b74de7.png)

**Comment by Shougo** [comment]
Reproduced for me.  I will fix it later.

But...

https://github.com/vim/vim/issues/10881#issuecomment-1210084556

It is intended behavior.  Because of `<silent>`.

**Comment by Shougo** [comment]
@arp242 

I have fixed the problems in the PR.
Please test.

**Comment by arp242** [comment]
> Reproduced for me. I will fix it later.
> 
> But...
> 
> [#10881 (comment)](https://github.com/vim/vim/issues/10881#issuecomment-1210084556)
> 
> It is intended behavior. Because of `<silent>`.

Ah right, it behaves like that without cmdline=0 too; bit odd but alright.

I tested your PR and it mostly seems good, but messages still are odd when scrolling, for example on startup vim-lsc shows a message, I press `^D` to scroll down and:

![cap-2022-08-11T13:33:36_border](https://user-images.githubusercontent.com/1032692/184124655-c4c0d7cd-ee8b-4878-8aef-d695d32af9eb.png)

Especially since it's pretty inconsistent; e.g. it does clear if you scroll with j or k, but not with ^D or ^U. In this case the message is highlighted and *kind of okay* I suppose, but without highlighted messages it looks like regular buffer text:

![cap-2022-08-11T13:35:39](https://user-images.githubusercontent.com/1032692/184124884-061d2222-368a-46f3-b729-1fc57fd8dadf.png)

Note the "Already at oldest change" in the centre from pressing `u` when there is nothing to undo.

**Comment by Shougo** [comment]
Please create the minimal vimrc with the reproduce-able instruction.
It is from your environment.

Have you created minimal vimrc with the instruction?
https://github.com/vim/vim/issues/10881#issuecomment-1210063739

**Comment by arp242** [comment]
You get this with any message that displays in the cmdline (`:echo` (from function), `u`, `n` not finding anything, etc.): if something gets displayed in the cmdline window and you scroll down then it gets "stuck". That's just illustrative that it's a problem.

for example:

    vim -Nu NONE +'set cmdheight=0' +'call append(1, repeat(["x"], 200))' +'/asdada'

Press `n` and `<C-d>` and it's stuck. But again, this happens with many messages: not just that particular one.

In your PR you prevented the message on `<C-c>` from appearing, but that's not really a "fix"; it should clear those messages on scroll (and then the `<C-c>` message can appear as usual too).

**Comment by Shougo** [comment]
OK.  It is reproduced.

**Comment by Shougo** [comment]
I have fixed them and simplified the PR.
Please test it.

**Comment by Shougo** [comment]
The problems are already fixed in vim HEAD.

**Comment by arp242** [comment]
Yup, with the new message popup it seems good at a glance.
