### ISSUE TITLE
Virtual text with "text_align: right" applies highlights to buffer text and positions buffer text wrong

### ISSUE THREAD

**Issue by arp242** [vim/vim#10888]
% cat prop
    call prop_type_add('test', #{highlight: 'SpellBad'})
    call setline(1, 'Hello!')
    call prop_add(1, 1, #{text: 'right', type: 'test', text_align: 'right'})

    % vim --noplugin -u NONE +'source prop'

Results in the `Hello` being highlighted, too:

![cap-2022-08-10T18:42:45](https://user-images.githubusercontent.com/1032692/183966338-cb443bbe-42b7-4496-b50a-61e1064c91bf.png)

Also the text is on the second line, rather than the first, and the cursor behaves rather odd, and deleting that line doesn't remove the "virtual text" on the right.

Vim 9.0.187:

	VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Aug 10 2022 16:35:41)
	Included patches: 1-187
	Compiled by martin@x270.arp242.net
	Huge version without GUI.  Features included (+) or not (-):
	+acl               +file_in_path      +mouse_urxvt       -tag_any_white
	-arabic            +find_in_path      +mouse_xterm       -tcl
	+autocmd           +float             +multi_byte        +termguicolors
	+autochdir         +folding           +multi_lang        -terminal
	-autoservername    -footer            -mzscheme          +terminfo
	-balloon_eval      +fork()            -netbeans_intg     +termresponse
	+balloon_eval_term -gettext           +num64             +textobjects
	-browse            -hangul_input      +packages          +textprop
	++builtin_terms    +iconv             +path_extra        +timers
	+byte_offset       +insert_expand     -perl              +title
	+channel           +ipv6              +persistent_undo   -toolbar
	+cindent           +job               +popupwin          +user_commands
	+clientserver      +jumplist          +postscript        +vartabs
	+clipboard         +keymap            +printer           +vertsplit
	+cmdline_compl     +lambda            +profile           +vim9script
	+cmdline_hist      +langmap           -python            +viminfo
	+cmdline_info      +libcall           -python3           +virtualedit
	+comments          +linebreak         +quickfix          +visual
	+conceal           +lispindent        +reltime           +visualextra
	+cryptv            +listcmds          -rightleft         +vreplace
	+cscope            +localmap          -ruby              +wildignore
	+cursorbind        +lua               +scrollbind        +wildmenu
	+cursorshape       +menu              +signs             +windows
	+dialog_con        +mksession         +smartindent       +writebackup
	+diff              +modify_fname      +sodium            +X11
	+digraphs          +mouse             -sound             +xfontset
	-dnd               -mouseshape        +spell             -xim
	-ebcdic            +mouse_dec         +startuptime       -xpm
	+emacs_tags        -mouse_gpm         +statusline        +xsmp_interact
	+eval              -mouse_jsbterm     -sun_workshop      +xterm_clipboard
	+ex_extra          +mouse_netterm     +syntax            -xterm_save
	+extra_search      +mouse_sgr         +tag_binary        
	-farsi             -mouse_sysmouse    -tag_old_static    
	   system vimrc file: "$VIM/vimrc"
		 user vimrc file: "$HOME/.vimrc"
	 2nd user vimrc file: "~/.vim/vimrc"
		  user exrc file: "$HOME/.exrc"
		   defaults file: "$VIMRUNTIME/defaults.vim"
	  fall-back for $VIM: "/usr/share/vim"
	Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -g -static -I/usr/include -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
	Linking: clang -g -static -L/usr/lib -L/usr/local/lib -Wl,--as-needed -o vim -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE -lm -lncurses -lxcb -lXau -lXdmcp -lsodium -L/usr/lib -llua5.4

**Comment by bfrg** [comment]
It works fine if you set the column number in `prop_add()` to zero:
```vim
call prop_type_add('test', #{highlight: 'SpellBad'})
call setline(1, 'Hello!')
call prop_add(1, 0, #{text: 'right', type: 'test', text_align: 'right'})
```

The help on `prop_add()` says that `text_align` applies only when `text` is present and `col` is set to zero. Maybe an error should be given when this is not the case?

**Comment by arp242** [comment]
Ah right, I missed that

> Maybe an error should be given when this is not the case?

Sounds like a reasonable solution! Now it actually works most of the time, except when it doesn't and you get weird effects.

**Comment by brammool** [comment]
The docs say that "text_align" is only used when "when "text" is present and {col} is zero".
That isn't actually checked.  I think we should make this an error to avoid such mistakes.

**Comment by brammool** [comment]
If you find any other problems, please create an issue with a repro case.
