### ISSUE TITLE
can't change runtimepath

### ISSUE THREAD

**Issue by harriott** [vim/vim#10897]
### Steps to reproduce

    set runtimepath+=~/anything
    set runtimepath

### Expected behaviour

`set runtimepath`  should show that  `~/anything`  has been added

### Version of Vim

gVim v9.0.0167

### Environment

`Windows 10 Pro`

**Comment by brammool** [comment]
It works fine for me, ":set rtp" shows "~/anything" at the end.

**Comment by chrisbra** [comment]
Cannot reproduce. Please provide complete steps, starting from `vim --clean` or in your case possibly `gvim --clean`

**Comment by harriott** [comment]
My bad, [options.txt](https://vimhelp.org/options.txt.html):
> If it gets very long then `:set rtp` will be truncated, use `:echo &rtp` to see the full string
