### ISSUE TITLE
hit-enter prompt is off by one for :echo

### ISSUE THREAD

**Issue by arp242** [vim/vim#10894]
When you're :echo-ing a message that is exactly the screen size you get an hit-enter prompt, even though it fits:

    % vim -Nu NONE
    :echo repeat('X', &columns - 1)    " Works, one character free on the right side
    :echo repeat('X', &columns)        " Get the ENTER prompt, even though it all fits

![cap-2022-08-11T18:18:10](https://user-images.githubusercontent.com/1032692/184181352-10ca05e6-409f-4246-bb5c-7d7e2c18ec94.png)

![cap-2022-08-11T18:18:19](https://user-images.githubusercontent.com/1032692/184181357-fcf5e2c9-d0b4-4d97-81ed-9e57383b17fb.png)

I went a bit through the code to try and fix it, but it's a bit confusing how this all works 😅

Vim 9.9.0192, inside terminal. Didn't try GUI.

	VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Aug 11 2022 15:56:13)
	Included patches: 1-192
	Compiled by martin@x270.arp242.net
	Huge version without GUI.  Features included (+) or not (-):
	+acl               -dnd               +listcmds          +postscript        +termresponse
	-arabic            -ebcdic            +localmap          +printer           +textobjects
	+autocmd           +emacs_tags        +lua               +profile           +textprop
	+autochdir         +eval              +menu              -python            +timers
	-autoservername    +ex_extra          +mksession         -python3           +title
	-balloon_eval      +extra_search      +modify_fname      +quickfix          -toolbar
	+balloon_eval_term -farsi             +mouse             +reltime           +user_commands
	-browse            +file_in_path      -mouseshape        -rightleft         +vartabs
	++builtin_terms    +find_in_path      +mouse_dec         -ruby              +vertsplit
	+byte_offset       +float             -mouse_gpm         +scrollbind        +vim9script
	+channel           +folding           -mouse_jsbterm     +signs             +viminfo
	+cindent           -footer            +mouse_netterm     +smartindent       +virtualedit
	+clientserver      +fork()            +mouse_sgr         +sodium            +visual
	+clipboard         -gettext           -mouse_sysmouse    -sound             +visualextra
	+cmdline_compl     -hangul_input      +mouse_urxvt       +spell             +vreplace
	+cmdline_hist      +iconv             +mouse_xterm       +startuptime       +wildignore
	+cmdline_info      +insert_expand     +multi_byte        +statusline        +wildmenu
	+comments          +ipv6              +multi_lang        -sun_workshop      +windows
	+conceal           +job               -mzscheme          +syntax            +writebackup
	+cryptv            +jumplist          -netbeans_intg     +tag_binary        +X11
	+cscope            +keymap            +num64             -tag_old_static    +xfontset
	+cursorbind        +lambda            +packages          -tag_any_white     -xim
	+cursorshape       +langmap           +path_extra        -tcl               -xpm
	+dialog_con        +libcall           -perl              +termguicolors     +xsmp_interact
	+diff              +linebreak         +persistent_undo   -terminal          +xterm_clipboard
	+digraphs          +lispindent        +popupwin          +terminfo          -xterm_save
	system vimrc file: "$VIM/vimrc"
		user vimrc file: "$HOME/.vimrc"
	2nd user vimrc file: "~/.vim/vimrc"
		user exrc file: "$HOME/.exrc"
		defaults file: "$VIMRUNTIME/defaults.vim"
	fall-back for $VIM: "/usr/share/vim"
	Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -g -static -I/usr/include -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
	Linking: clang -g -static -L/usr/lib -L/usr/local/lib -Wl,--as-needed -o vim -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE -lm -lncurses -lxcb -lXau -lXdmcp -lsodium -L/usr/lib -llua5.4

**Comment by brammool** [comment]
This is intentional. Several terminals will scroll the screen up when putting a character in the lower right corner.  That will then require a redraw, thus the hit-enter prompt is needed.
Thus, even though the message fits, the window might scroll.

**Comment by arp242** [comment]
Oh right; is that still relevant with modern terminal emulators? I wrote an "ncurses-like" Go library earlier this year and I never noticed any issues on any terminal emulator I tested, and the application I was working on puts a border on the edge of the entire window. Plus e.g. tmux has been putting stuff there for ages too, with `cmdheight=0` the statusline will draw in the bottom-right corner too.

**Comment by brammool** [comment]
> Oh right; is that still relevant with modern terminal emulators? I
> wrote an "ncurses-like" Go library earlier this year and I never
> noticed any issues on any terminal emulator I tested, and the
> application I was working on puts a border on the edge of the entire
> window. Plus e.g. tmux has been putting stuff there for ages too, with
> `cmdheight=0` the statusline will draw in the bottom-right corner too.

Not everybody uses a modern terminal emulator.  Vim works in many old
environments.

-- 
Back up my hard drive?  I can't find the reverse switch!

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
