### ISSUE TITLE
src/Make_mvc.mak fails for quoted values of SDK_INCLUDE_DIR

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vim/vim#109]
```
using msvs 2012 express for desktop
nmake version 11.00.51106.1

while following the instructions on lines 18-19 of src/Make_mvc.mak causes 
nmake to complain and result in a fatal error. i eventually found putting 
quotes in the var SDK_INCLUDE_DIR to be the culprit.

e:\projects\vim\src>set SDK_INCLUDE_DIR="C:\Program Files (x86)\Microsoft 
SDKs\Windows\v7.1\Include"

removing the quotes enables everything to work fine but feels a little scary. 
an alternative is to make use of nmake's INCLUDE macro:

INCLUDE=$(SDK_INCLUDE_DIR);$(INCLUDE)

then use angle brackets as usual:

!include <Win32.mak>

this works great but the INCLUDE macro will also need to be updated in GvimExt 
Makefile as well if it is desired to build GvimExt on its own and that could 
result in some weirdness since you'll be duplicating the SDK_INCLUDE_DIR in 
nmakes INCLUDE paths.

attached is a diff with these changes to the makefiles and including an 
additional .bat for setting the msvs 2012 environment.
```

Original issue reported on code.google.com by `bland...@gmail.com` on 16 Feb 2013 at 10:30

Attachments:
- [msvs_2012_makefile_updates.diff](https://storage.googleapis.com/google-code-attachments/vim/issue-109/comment-0/msvs_2012_makefile_updates.diff)

**Comment by k-takata** [comment]
> while following the instructions on lines 18-19 of src/Make_mvc.mak causes nmake to complain and result in a fatal error.

Actually, the instructions intended to use it as a parameter of nmake:

    nmake -f Make_mvc.mak SDK_INCLUDE_DIR="C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1\Include"

No need to quote when `set` is used:

    set SDK_INCLUDE_DIR=C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1\Include
    nmake -f Make_mvc.mak

And the following should also work:

    set "SDK_INCLUDE_DIR=C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1\Include"
    nmake -f Make_mvc.mak

Moreover, we don't need to set `SDK_INCLUDE_DIR` anymore if we use Vim 8.0.0881 or later and targeting Windows Vista or later.
So closing.
