### ISSUE TITLE
ml_get error when switching to hidden buffer in Visual mode with virtualedit=all

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#10902]
### Steps to reproduce

1. Run `vim --clean`
2. Source the following file:
```vim
set hidden
set virtualedit=all
call setline(1, 'foo')
let buf = bufnr()
enew
call setline(1, ['', '', '', ''])
call cursor(4, 5)
call feedkeys("\<C-V>3k4h", 'xt')
exe 'buffer' buf
```
3. `ml_get` error

### Expected behaviour

No ml_get error

### Version of Vim

9.0.135

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

**Comment by lacygoill** [comment]
- [backtrace](https://github.com/vim/vim/files/9331431/gdb.txt)
- [valgrind log](https://github.com/vim/vim/files/9331432/valgrind.log)
