### ISSUE TITLE
When 'list' is enabled, the 'eol:c' character is drawn after the virtual text instead of at the end of the actual text line

### ISSUE THREAD

**Issue by bfrg** [vim/vim#10911]
### Steps to reproduce

Run `vim --clean test.vim -S test.vim`, with
```vim
vim9script

colorscheme habamax
set list

prop_type_add('Prop1', {highlight: 'Error'})

prop_add(3, 0, {
    type: 'Prop1',
    text: 'The quick brown fox jumps over the lazy dog',
})
```

Result: The `listchars` option `eol:c` is drawn after the virtual text and not at the end of the text line.

![screenshot-2022-08-13_201721](https://user-images.githubusercontent.com/6266600/184506210-e0a58791-1e7d-44eb-a8f0-7c868a72a55e.png)

### Expected behaviour

The `eol:c` character of the `listchars` option should be drawn before the virtual text when `text_align` is set to `after` or `right` to make it clearer where the text line ends.

### Version of Vim

9.0.199

### Environment

Linux

**Comment by brammool** [comment]
Also fixed with patch 9.0.0210
