### ISSUE TITLE
[virtual text] Vim adds an empty "virtual" line when `wrap` and `list` are enabled, and 'text_align' is set to 'right

### ISSUE THREAD

**Issue by bfrg** [vim/vim#10912]
### Steps to reproduce

Run `vim --clean test.vim -S test.vim`, with

```vim
vim9script

colorscheme habamax
set list

prop_type_add('Prop1', {highlight: 'Error'})

prop_add(3, 0, {
    type: 'Prop1',
    text: 'The quick brown fox jumps over the lazy dog',
    text_align: 'right'
})
```

**Result:** After the 3rd line, a "virtual" line is added when `wrap` and `list` are enabled.

**Screenshot**
![screenshot-2022-08-13_210654](https://user-images.githubusercontent.com/6266600/184507450-d7f7b186-ccdd-411a-8c4d-7dffde341d47.png)

### Expected behaviour

No redundant "virtual" lines.

### Version of Vim

9.0.199

### Environment

Linux

**Comment by brammool** [comment]
Patch 9.0.0210 fixes this as well.
