### ISSUE TITLE
Java text block is not highlighted as string

### ISSUE THREAD

**Issue by andirady** [vim/vim#10910]
### Steps to reproduce

1. Paste the following buffer:
```java
class A {
  String s = """
      The quick brown fox
      jumps over the lazy dog
      """;
}
```
2. Set syntax to java

### Expected behaviour

The text enclosed within two ``"""`` should be highlighted as string.

### Version of Vim

9.0

### Environment

Operating system: Linux
Terminal: GNOME Terminal 3.44.1
Value of $TERM: screen
shell: bash 5.1.16

**Comment by lacygoill** [comment]
The java syntax plugin is maintained [here](https://github.com/fleiner/vim/blob/master/runtime/syntax/java.vim).
The link appears at the top of the file [here](https://github.com/vim/vim/blob/f0ccfa474a5c4940d03bfc6084e896dc8ac2d791/runtime/syntax/java.vim#L4).

---

A naive patch:
```diff
diff --git a/runtime/syntax/java.vim b/runtime/syntax/java.vim
index 00d607194..e0b444164 100644
--- a/runtime/syntax/java.vim
+++ b/runtime/syntax/java.vim
@@ -204,6 +204,7 @@ syn match   javaSpecialError	 contained "\\."
 syn match   javaSpecialCharError contained "[^']"
 syn match   javaSpecialChar	 contained "\\\([4-9]\d\|[0-3]\d\d\|[\"\\'ntbrf]\|u\x\{4\}\)"
 syn region  javaString		start=+"+ end=+"+ end=+$+ contains=javaSpecialChar,javaSpecialError,@Spell
+syn region  javaString		start=+"""+ end=+"""+ contains=javaSpecialChar,javaSpecialError,@Spell
 " next line disabled, it can cause a crash for a long line
 "syn match   javaStringError	  +"\([^"\\]\|\\.\)*$+
 syn match   javaCharacter	 "'[^']*'" contains=javaSpecialChar,javaSpecialCharError
```
CC @fleiner

**Comment by andirady** [comment]
> The java syntax plugin is maintained [here](https://github.com/fleiner/vim/blob/master/runtime/syntax/java.vim).
> The link appears at the top of the file [here](https://github.com/vim/vim/blob/f0ccfa474a5c4940d03bfc6084e896dc8ac2d791/runtime/syntax/java.vim#L4).
> 
> ---
> 
> A naive patch:
> ```diff
> diff --git a/runtime/syntax/java.vim b/runtime/syntax/java.vim
> index 00d607194..e0b444164 100644
> --- a/runtime/syntax/java.vim
> +++ b/runtime/syntax/java.vim
> @@ -204,6 +204,7 @@ syn match   javaSpecialError	 contained "\\."
>  syn match   javaSpecialCharError contained "[^']"
>  syn match   javaSpecialChar	 contained "\\\([4-9]\d\|[0-3]\d\d\|[\"\\'ntbrf]\|u\x\{4\}\)"
>  syn region  javaString		start=+"+ end=+"+ end=+$+ contains=javaSpecialChar,javaSpecialError,@Spell
> +syn region  javaString		start=+"""+ end=+"""+ contains=javaSpecialChar,javaSpecialError,@Spell
>  " next line disabled, it can cause a crash for a long line
>  "syn match   javaStringError	  +"\([^"\\]\|\\.\)*$+
>  syn match   javaCharacter	 "'[^']*'" contains=javaSpecialChar,javaSpecialCharError
> ```
> CC @fleiner
> 

The spec says:
```
TextBlock:
" " " { TextBlockWhiteSpace } LineTerminator { TextBlockCharacter } " " "
TextBlockWhiteSpace:
WhiteSpace but not LineTerminator

TextBlockCharacter:
InputCharacter but not \
EscapeSequence
LineTerminator
```

**Comment by lacygoill** [comment]
> A *naive* patch:

**Comment by zzzyxwvut** [comment]
Try a more general [fix](https://github.com/zzzyxwvut/vim/commit/3ff6f8913480ec202f129290d814e31ba6dacd7c) (part of [PR #8](https://github.com/fleiner/vim/pull/8)).
