### ISSUE TITLE
[virtual text] The 'extends:c' character in 'listchars' is drawn at the wrong position when 'list' is enabled

### ISSUE THREAD

**Issue by bfrg** [vim/vim#10913]
### Steps to reproduce

Run `vim --clean test.vim -S test.vim`, with

```vim
vim9script

colorscheme habamax
set list
set listchars+=extends:»
set nowrap

prop_type_add('Prop1', {highlight: 'Error'})

prop_add(3, 0, {
    type: 'Prop1',
    text: 'The quick brown fox jumps over the lazy dog',
    text_align: 'right'
})
```

**Result:** The `extends:c` character is drawn instead of the last character of the virtual text. In the above example it's drawn on the 'g' of 'dog'.

**Screenshot**
![screenshot-2022-08-13_211351](https://user-images.githubusercontent.com/6266600/184507658-801e4ce8-2b74-4d67-977b-e63e06bbbcfd.png)

### Expected behaviour

In the above example, the `extends:c` character shouldn't been drawn at all. If the buffer line is too long and `wrap` is disabled, it should be drawn on the last visible buffer text and not virtual text.

I don't know what to expect when a line is too long to fit on the screen and `wrap` is disabled. Currently, the `extends:c` character is displayed, and the virtual text is not visible at all. I think this is as expected.

However, when the virtual text is not fully visible, the `extends:c` character is drawn on the virtual text. See the screenshot below. In my opinion, Vim should use the `…` character for the virtual text when it doesn't fit on the screen. This is already done in other cases. The `extends:c` character should be reserved only when the actual buffer text doesn't fit on the screen.

![screenshot-2022-08-13_213333](https://user-images.githubusercontent.com/6266600/184508203-b0accb9a-e72f-480b-adf3-03f344597564.png)

### Version of Vim

9.0.199

### Environment

Linux

**Comment by bfrg** [comment]
> In my opinion, Vim should use the `…` character for the virtual text when it doesn't fit on the screen. This is already done in other cases.

Well, the `…` character is shown only when `wrap` is enabled. It disappears with `nowrap`. Is this intentional?

**Screenshot** 
![screenshot-2022-08-13_215430](https://user-images.githubusercontent.com/6266600/184508841-a98aa21d-a835-4cd7-9383-5e84fe7485ea.png)

Example code in the screenshot:
```vim
vim9script

# This is a very long text line. This is a very long text line. This is a very long text line. 
colorscheme habamax
set nolist
set listchars+=extends:»
set wrap

prop_type_add('Prop1', {highlight: 'Error'})

prop_add(3, 0, {
    type: 'Prop1',
    text: 'The quick brown fox jumps over the lazy dog',
    text_align: 'right'
})
```

**Comment by brammool** [comment]
> > In my opinion, Vim should use the `…` character for the virtual text
> > when it doesn't fit on the screen. This is already done in other
> > cases.
> 
> Well, the `…` character is shown only when `wrap` is enabled. It
> disappears with `nowrap`. Is this intentional?

Yes, with 'nowrap' the text isn't really truncated, it just continues
after the end of the window, just like with normal text.

We can show the "extends" character also for virtual text, so it's clear
there is more to follow.

-- 
"Shoot for the moon. Even if you miss, you'll land among the stars."

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
