### ISSUE TITLE
Add *colorscheme-override* help tag

### ISSUE THREAD

**Issue by habamax** [vim/vim#10924]
It would be really helpful to have *colorscheme-override* help tag to directly point users the doc about colorscheme override:

```                                   
                                     *colorscheme-override*
If a color scheme is almost right, you can add modifications on top of it by
using the |ColorScheme| autocommand.  For example, to remove the background
color (can make it transparent in some terminals): >
	augroup my_colorschemes
	  au!
	  au Colorscheme pablo hi Normal ctermbg=NONE
	augroup END
```

For now it is "`:h colorscheme` then scroll a couple of pages down" 

PS, or any other tag name.

**Comment by habamax** [comment]
One example is https://github.com/vim/colorschemes/issues/207#issuecomment-1216312539

And many more in `#vim` on libera.chat

**Comment by brammool** [comment]
> It would be really helpful to have *colorscheme-override* help tag to
> directly point users the doc about colorscheme override:
> 
> ```                                   *colorscheme-override*
> If a color scheme is almost right, you can add modifications on top of it by
> using the |ColorScheme| autocommand.  For example, to remove the background
> color (can make it transparent in some terminals): >
> 	augroup my_colorschemes
> 	  au!
> 	  au Colorscheme pablo hi Normal ctermbg=NONE
> 	augroup END
> ```
> 
> For now it is "`:h colorscheme` then scroll a couple of pages down" 
> 
> PS, or any other tag name.

I'll add it.  Name sounds good to me.

-- 
Vim is like Emacs without all the typing.  (John "Johann" Spetz)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by matveyt** [comment]
I'd rather not suggest use of autocmd here but instead adviced to create

>~/.vim/colors/pablo.vim

```VimL
source $VIMRUNTIME/colors/<script>:t
hi normal guibg=NONE
```

Looks cleaner to me then (over-)extending vimrc.

**Comment by habamax** [comment]
Thanks for adding.
