### ISSUE TITLE
`vim-git-10985.5e5a98d7d-1` does not build from the AUR

### ISSUE THREAD

**Issue by amtoine** [vim/vim#10925]
### Steps to reproduce

1. `paru -S vim-git`

### Expected behaviour

 Hello there :yum: :wave: 

i'm not sure where to report that and if it's the right place to do it :confused: 

i just tried to compile `vim` with the `clipboard` option, which is not the default in the ArchLinux repos, so i tried to AUR but the install of `vim-git` failed...

cheers :yum: 

### Version of Vim

9.0.1-135

### Environment

```bash
$ uname -a
Linux archasus 5.18.16-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 03 Aug 2022 11:25:04 +0000 x86_64 GNU/Linux
```

```bash
$ alacritty --version
alacritty 0.10.1 ()
```

```bash
$ echo $TERM
xterm-256color
```

### Logs and stack traces

```shell
$ paru -S vim-git
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

:: Conflicts found:
    vim-git: vim

:: Conflicting packages will have to be confirmed manually

Aur (1) vim-git-10985.5e5a98d7d-1

:: Proceed to review? [Y/n]:

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
 nothing new to review
fetching devel info...
error: timed out looking for devel update: git://github.com/vim/vim.git
error: failed to lookup: vim-git:
==> Making package: vim-git 10985.5e5a98d7d-1 (Tue Aug 16 11:20:19 2022)
==> Retrieving sources...
  -> Cloning vim git repo...
Cloning into bare repository '/home/ants/.cache/paru/clone/vim-git/vim'...
fatal: unable to connect to github.com:
github.com[0: 140.82.121.3]: errno=Connection timed out

==> ERROR: Failure while downloading vim git repo

    Aborting...
error: failed to download sources for 'vim-git-10985.5e5a98d7d-1':
```

**Comment by chrisbra** [comment]
> github.com[0: 140.82.121.3]: errno=Connection timed out

You have a networking problem (or perhaps github was down). I don't think this is a vim issue

**Comment by clason** [comment]
> error: timed out looking for devel update: git://github.com/vim/vim.git

Github no longer supports the `git://` protocol, afaik:
https://github.blog/2021-09-01-improving-git-protocol-security-github/

**Comment by amtoine** [comment]
@chrisbra
> You have a networking problem (or perhaps github was down). I don't think this is a vim issue
>
i tried `ssh github.com` and it worked fine :wink: 

@clason 
> Github no longer supports the `git://` protocol, afaik: https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git
>
ooooh that might be it indeed! :open_mouth: 
let me try to fix the URL in the `PKGBUILD` :+1:

**Comment by zeertzjq** [comment]
This has been reported twice in <https://aur.archlinux.org/packages/vim-git>, so this issue can be closed.

**Comment by amtoine** [comment]
> This has been reported twice in https://aur.archlinux.org/packages/vim-git, so this issue can be closed.
>
i've never used the issue tracker on the AUR :confused: 

thanks y'all for the tips :relieved: :star_struck:
