### ISSUE TITLE
autochdir does not respect `No Name` buffers

### ISSUE THREAD

**Issue by ad-chaos** [vim/vim#10923]
### Steps to reproduce

```
vim --clean
:set autochdir
:h h
:pwd (should say the runtime path)
<C-w>j
:pwd (also says the runtime path)
```

### Expected behaviour

When switching windows (from the help window to the `No Name` buffer) the cwd should also be changed

I am not sure if this is a bug or a feature request, because the doc says
```help
			*'autochdir'* *'acd'* *'noautochdir'* *'noacd'*
'autochdir' 'acd'	boolean (default off)
			global
	When on, Vim will change the current working directory whenever you
	open a file, switch buffers, delete a buffer or open/close a window.
	It will change to the directory containing the file which was opened
	or selected.
	Note: When this option is on some plugins may not work.
```
Which mentions:-
> It will change to the directory containing the **file** which was opened or selected.

but then also says:-
> When on, Vim will change the current working directory whenever you open a file, switch **buffers**

So maybe either the docs need updating to be more clear or maybe make the `No Name` buffer also have a `cwd` attached to it :)

### Version of Vim

VIM - Vi IMproved 9.0 (Included patches: 1-200)

### Environment

Operating System: macOs
Terminal: Kitty
$TERM: xterm-kitty
Shell: zsh

**Comment by zeertzjq** [comment]
What do you expect the cwd to be changed to?

**Comment by Kiran-Raj-Dev** [comment]
To the one from which I started `nvim` from

**Comment by brammool** [comment]
A buffer without a name is not associated with any directory.  Thus 'autochdir' doesn't do anything when making such a buffer the current one.  Since when using 'autochdir' you constantly change directory, using the current directory of when the buffer was created, e.g. with ":new", is likely more confusing than helpful.  I'll add a remark in the help about this.
