### ISSUE TITLE
internal error when searching for pattern after adding text property

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#10938]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        ['', '']->setline(1)
        prop_type_add('name', {highlight: 'ErrorMsg'})
        prop_add(1, 1, {length: 1, type: 'name'})
        search('\%>.l\n.*\%<2v', 'nW')
    EOF
    )

An internal error is given:

    E315: ml_get: Invalid lnum: 3

**Expected behavior**

No internal error is given.

**Version of Vim**

9.0 Included patches: 1-226

**Environment**

Operating system: Ubuntu 20.04.4 LTS
Terminal: XTerm(353)
Value of $TERM: xterm-256color
Shell: GNU bash, version 5.0.17

**Logs and stack traces**

- [backtrace](https://github.com/vim/vim/files/9378964/gdb.txt)
- [valgrind log](https://github.com/vim/vim/files/9378965/valgrind.log)

---

Regression introduced in patch [9.0.0067](https://github.com/vim/vim/releases/tag/v9.0.0067)

**Comment by mattn** [comment]
https://github.com/vim/vim/commit/13ed494bb5edc5a02d0ed0feabddb68920f88570 break original behavior.

```
echo matchstr('aaaaaaaaaaaaaaaaaaaa', '.*\%<5v')
```
```
vim -Nu NONE -S xxx.vim
```

Before the 13ed494bb5edc5a02d0ed0feabddb68920f88570, this display `aaa` but after the commit display 'aaaaaaaaaaaaaaaaaaaa'.

**Comment by brammool** [comment]
I cannot reproduce this problem.  For me "aaaaaaaaaaaaaaaaaaaa" is echo'ed

**Comment by brammool** [comment]
Oh, wait, you say it should result in "aaa", I read it the other way around.

**Comment by itchyny** [comment]
Bram, patch 9.0.0407 does not resolve the issue of `matchstr` with virtual column pattern. Following steps does not truncate the string.
```vim
call matchadd('Title', 'Title')
call setline(1, ['', ''])
new
echo matchstr('aaaaaaaaaaaaaaaaaaaa', '.*\%<5v')
```

**Comment by brammool** [comment]
> Bram, patch 9.0.0407 does not resolve the issue of `matchstr` with virtual column pattern. Following steps does not truncate the string.
> ```vim
> call matchadd('Title', 'Title')
> call setline(1, ['', ''])
> new
> echo matchstr('aaaaaaaaaaaaaaaaaaaa', '.*\%<5v')
> ```

Hmm, I thought it worked since the test passed.  But it turns out it is
using the line number from a previous search, it isn't reset.

-- 
How To Keep A Healthy Level Of Insanity:
8. Don't use any punctuation marks.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
