### ISSUE TITLE
cannot use OSC 7 sequence and 'autoshelldir' to synchronize Vim CWD with fish shell CWD

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#10949]
**Steps to reproduce**

Run these shell commands:

    $ rm -rf /tmp/home/user/.config/fish/
    $ mkdir -p /tmp/home/user/.config/fish/

    $ tee >/tmp/home/user/.config/fish/config.fish <<'EOF'
        if test -n "$VIM_TERMINAL"
            function _vim_sync_PWD --on-variable=PWD
                printf '\033]7;file://%s\033\\' "$PWD"
            end
        end
    EOF

    $ rm /tmp/log

    $ XDG_CONFIG_HOME=/tmp/home/user/.config/ vim -Nu NONE --log /tmp/log \
      +'set autoshelldir' \
      +'autocmd TerminalWinOpen * call term_sendkeys("", "cd /tmp\<CR>")' \
      +'terminal fish'

An error is given:

    E1179: Failed to extract PWD from /tmp^[\, check your shell's config related to OSC 7

Next, execute this Ex command to quit Vim:

    :quitall!

Finally, run this shell command to read the `RECV` lines from the logfile:

    $ vim -Nu NONE +'vglobal /RECV/ delete _' /tmp/log

You should see that the OSC 7 sequence has been received in several chunks.  For example:

    RECV on 0(out): '^[]7;fi'
    RECV on 0(out): 'le:///tmp^[\'

**Expected behavior**

No error is given.  The Vim current working directory is synchronized with the one of the shell running in the Vim terminal buffer.

**Version of Vim**

9.0 Included patches: 1-230

**Environment**

Operating system: Ubuntu 20.04.4 LTS
Terminal: XTerm(353)
Value of $TERM: xterm-256color
Shell: fish, version 3.5.1-252-gada925141

**Additional context**

The issue is not deterministic.  You might need to `cd` into several directories to get an error.

---

The issue is specific to the fish shell.  No issue if we use the bash hook in bash, or the zsh hook in zsh.

---

If we send the OSC 7 sequence manually, `'autoshelldir'` works as expected.  No error is given, and Vim's CWD is synchronized with the shell's one.

---

I think the issue comes from the fact that Vim receives the OSC 7 sequence in chunks.  I *guess* fish bufferizes the output of its `printf` builtin (but – for some reason – only when run from a hook).

---

The workaround given at [`:help terminal-autoshelldir`](https://vimhelp.org/terminal.txt.html#terminal-autoshelldir) – which relies on an OSC 51 sequence instead of OSC 7 – works as expected:

    # in a Vim init file
    def g:Tapi_lcd(_, args: path)
        execute $'silent lcd {path}'
    enddef

    # in a fish init file
    if test -n "$VIM_TERMINAL"
        function _vim_sync_PWD --on-variable=PWD
            printf '\033]51;["call", "Tapi_lcd", "%s"]\007' "$PWD"
        end
    end

---

It might be a regression in fish because the code worked fine until [this commit](https://github.com/fish-shell/fish-shell/commit/bcfc54fdaa2f0f76a6d7e20cf7e49677b669a3ff).

However, I open the issue here, because I don't understand the code well enough, and the error is given in Vim.

Is it a bug in fish which should be reported on their bug tracker instead?  Or is there something which could be done on Vim's side to somehow join these meaningless chunks into a complete OSC 7 sequence?

**Comment by lacygoill** [comment]
> Shell: GNU bash, version 5.0.17

Sorry, I meant this shell version:

    fish, version 3.5.1-252-gada925141

**Comment by lacygoill** [comment]
> XDG_CONFIG_HOME=/tmp/home/user/.config/ vim -Nu NONE --log /tmp/log \
   >   +'set autoshelldir' \
   >   +'autocmd TerminalWinOpen * call term_sendkeys("", "cd /tmp\<CR>")' \
   >   +'terminal /home/lgc/VCS/fish/build/fish'

And I meant this shell command:

    XDG_CONFIG_HOME=/tmp/home/user/.config/ vim -Nu NONE --log /tmp/log \
     +'set autoshelldir' \
     +'autocmd TerminalWinOpen * call term_sendkeys("", "cd /tmp\<CR>")' \
     +'terminal fish'

**Comment by lacygoill** [comment]
The fact that no error is given when using an OSC 51 sequence makes me think that somehow fish is confused by the presence of the "file" pattern in the OSC 7 sequence (which is absent from OSC 51).  I *guess* fish thinks that the output is intended to a file, and thus it's OK to bufferize the output of `printf(1)`.  Although no idea why it does that only from a hook.  And I still wonder whether Vim could handle this by re-assembling the chunks.

**Comment by lacygoill** [comment]
Unrelated, but the code given at [`:help terminal-autoshelldir`](https://vimhelp.org/terminal.txt.html#terminal-autoshelldir) could be improved:

    def g:Tapi_lcd(_, args: string)
        execute 'silent lcd ' .. args
    enddef

First, the function is meant to receive a path to a directory, and [`:help :lcd`](https://vimhelp.org/editing.txt.html#%3Alcd) itself names the parameter `{path}`.  So `path` would be a better name than the generic `args`.

Second, we might want to check that the received path is indeed a directory, just to make the code safer; since [security is a concern here](https://github.com/vim/vim/issues/10853#issuecomment-1207381078):

   > g:Tapi_exe() would execute any command the shell sends, that doesn't seem safe.

As a suggestion, here is a patch:
```diff
diff --git a/runtime/doc/terminal.txt b/runtime/doc/terminal.txt
index 56f0dc82d..9e2270262 100644
--- a/runtime/doc/terminal.txt
+++ b/runtime/doc/terminal.txt
@@ -1022,8 +1022,10 @@ create a security problem.
 						*terminal-autoshelldir*
 This can be used to pass the current directory from a shell to Vim.
 Put this in your .vimrc: >
-	def g:Tapi_lcd(_, args: string)
-	    execute 'silent lcd ' .. args
+	def g:Tapi_lcd(_, path: string)
+            if path->isdirectory()
+                execute $'silent lcd {path}'
+            endif
 	enddef
 <
 And, in a bash init file: >
```

**Comment by brammool** [comment]
> Unrelated, but the code given at [`:help terminal-autoshelldir`](https://vimhelp.org/terminal.txt.html#terminal-autoshelldir) could be improved:
> 
>     def g:Tapi_lcd(_, args: string)
>         execute 'silent lcd ' .. args
>     enddef
> 
> First, the function is meant to receive a path to a directory, and [`:help :lcd`](https://vimhelp.org/editing.txt.html#%3Alcd) itself names the parameter `{path}`.  So `path` would be a better name than the generic `args`.
> 
> Second, we might want to check that the received path is indeed a directory, just to make the code safer; since [security is a concern here](https://github.com/vim/vim/issues/10853#issuecomment-1207381078):
> 
>    > g:Tapi_exe() would execute any command the shell sends, that doesn't seem safe.
> 
> As a suggestion, here is a patch:
> ```diff
> diff --git a/runtime/doc/terminal.txt b/runtime/doc/terminal.txt
> index 56f0dc82d..9e2270262 100644
> --- a/runtime/doc/terminal.txt
> +++ b/runtime/doc/terminal.txt
> @@ -1022,8 +1022,10 @@ create a security problem.
>  						*terminal-autoshelldir*
>  This can be used to pass the current directory from a shell to Vim.
>  Put this in your .vimrc: >
> -	def g:Tapi_lcd(_, args: string)
> -	    execute 'silent lcd ' .. args
> +	def g:Tapi_lcd(_, path: string)
> +            if path->isdirectory()
> +                execute $'silent lcd {path}'
> +            endif
>  	enddef
>  <
>  And, in a bash init file: >
> ```

Right.  On top of that fnameescape() should be ued.

-- 
Q: What's orange and sounds like a parrot?
A: A carrot

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
> **Steps to reproduce**
> 
> Run these shell commands:
> 
>     $ rm -rf /tmp/home/user/.config/fish/
>     $ mkdir -p /tmp/home/user/.config/fish/
> 
>     $ tee >/tmp/home/user/.config/fish/config.fish <<'EOF'
>         if test -n "$VIM_TERMINAL"
>             function _vim_sync_PWD --on-variable=PWD
>                 printf '\033]7;file://%s\033\\' "$PWD"
>             end
>         end
>     EOF
> 
>     $ rm /tmp/log
> 
>     $ XDG_CONFIG_HOME=/tmp/home/user/.config/ vim -Nu NONE --log /tmp/log \
>       +'set autoshelldir' \
>       +'autocmd TerminalWinOpen * call term_sendkeys("", "cd /tmp\<CR>")' \
>       +'terminal /home/lgc/VCS/fish/build/fish'
> 
> An error is given:
> 
>     E1179: Failed to extract PWD from /tmp^[\, check your shell's config related to OSC 7
> 
> Next, execute this Ex command to quit Vim:
> 
>     :quitall!
> 
> Finally, run this shell command to read the `RECV` lines from the logfile:
> 
>     $ vim -Nu NONE +'vglobal /RECV/ delete _' /tmp/log
> 
> You should see that the OSC 7 sequence has been received in several chunks.  For example:
> 
>     RECV on 0(out): '^[]7;fi'
>     RECV on 0(out): 'le:///tmp^[\'
> 
> **Expected behavior**
> 
> No error is given.  The Vim current working directory is synchronized
> with the one of the shell running in the Vim terminal buffer.

Can you simulate this without an actual fish shell doing this?
Perhaps the code in parse_osc() that collects a JSON string can also be
used to concatenate fragments of the OSC 7 sequence.  This is in
src/terminal.c, parse_osc().  Currently sync_shell_dir() is called on
the fragment itself, while for OSC 51 we collect them until the final
piece is received.  

I'll make a patch, please try it out.  I haven't added a test, that
takes some puzzling.


-- 
Q: What do you call a fish without an eye?
A: fsh!
Q: What do you call a deer with no eyes?
A: no eye deer.
Q: What do you call a deer with no eyes and no legs?
A: still no eye deer.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> Can you simulate this without an actual fish shell doing this?

Sorry, but that's above my level.  I just stumbled on the issue.

   > I'll make a patch, please try it out.

I can confirm that the patch fixes the issue.  Thank you very much.
