### ISSUE TITLE
E121: Undefined variable: range

### ISSUE THREAD

**Issue by IntoLighter** [vim/vim#10947]
### Steps to reproduce

1. Write script with range function:
```
vim9script
for i in range (1, 4)
    echo "count is {i}"
endfor
```
2. Write it and run:
```
:w
:source %
```

<img width="604" alt="image" src="https://user-images.githubusercontent.com/57671679/185745320-4d3422b0-939d-4e58-b633-29ce2ca110c9.png">

### Expected behaviour

Run and print:
```
count is {1}
count is {2}
count is {3}
```

### Version of Vim

9.0 compiled by Homebrew

### Environment

Operating system: macOS arm64
Terminal: iterm
Value of $TERM: xterm-256color
Shell: zsh

**Comment by dkearns** [comment]
Whitespace isn't allowed between the function name and argument list in Vim9 script.

See `:help E1004`

**Comment by ahnafalnafis** [comment]
> ### Steps to reproduce
> 1. Write script with range function:
> 
> ```
> vim9script
> for i in range (1, 4)
>     echo "count is {i}"
> endfor
> ```
> 
> 2. Write it and run:
> 
> ```
> :w
> :source %
> ```
> 
> <img alt="image" width="604" src="https://user-images.githubusercontent.com/57671679/185745320-4d3422b0-939d-4e58-b633-29ce2ca110c9.png">
> 
> ### Expected behaviour
> Run and print:
> 
> ```
> count is {1}
> count is {2}
> count is {3}
> ```
> 
> ### Version of Vim
> 9.0 compiled by Homebrew
> 
> ### Environment
> Operating system: macOS arm64 Terminal: iterm Value of $TERM: xterm-256color Shell: zsh
> 
> ### Logs and stack traces
> _No response_

You have put a whitespace after `range`, like this `range (1, 4)` which is not allowed. Vim is assuming it as a variable and trying deal with it but fails because you don't have variable `range` declared. Remove the whitespace between `range` and opening parentheses.

Also see `:h e1004`
