### ISSUE TITLE
Vim syntax highlighting is broken for Haskell files

### ISSUE THREAD

**Issue by MangoIV** [vim/vim#10940]
### Steps to reproduce

- create a file `A.hs` containing 
  ```haskell 
  module A where  
  
  data A = B | C
  -- FIXME: bla"
  ```
- `$ nix shell "github:nixos/nixpkgs/e9545762b032559c27d8ec9141ed63ceca1aa1ac"#vim`
- `$ vim --clean A.hs`

### Expected behaviour

- types are highlighted
- `FIXME`s are highlighted

### Version of Vim

8.2

### Environment

- OS: NixOS 22.11.20220816.6c6409e (Raccoon)
- Terminal: kitty 0.25.2 created by Kovid Goyal
- `$TERM`: xterm-kitty
- Shell: zsh 5.9
- Nixpkgs hash: `e9545762b032559c27d8ec9141ed63ceca1aa1ac`

**Comment by brammool** [comment]
Forwarding to Haskell mailing list.

> ### Steps to reproduce
> 
> - create a file `A.hs` containing 
>   ```haskell 
>   module A where  
>   
>   data A = B | C
>   -- FIXME: bla"
>   ```
> - `$ nix shell "github:nixos/nixpkgs/e9545762b032559c27d8ec9141ed63ceca1aa1ac"#vim`
> - `$ vim --clean A.hs`
> 
> ### Expected behaviour
> 
> - types are highlighted
> - `FIXME`s are highlighted
> 
> ### Version of Vim
> 
> 8.2

-- 
FATHER: We are here today to witness the union of two young people in the
        joyful bond of the holy wedlock.  Unfortunately, one of them, my son
        Herbert, has just fallen to his death.
   [Murmurs from CROWD;  the BRIDE smiles with relief, coughs.]
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
Hmm, closed list.  Can you subscribe and let them know about the issue?

**Comment by MangoIV** [comment]
Sure. Thanks for you worries.
