### ISSUE TITLE
Backward `search()` of `x\_.` depends on parity of `x` character 

### ISSUE THREAD

**Issue by echasnovski** [vim/vim#10955]
### Steps to reproduce

1. `vim -u NONE`
2. Set lines `x` and `aaa`.
3. Position cursor on last `a`.
4. Execute `:call search('x\_.', 'b')`. Cursor is on (last) `x` (as expected).
5. Repeat 2-4 with lines `xx` and `aaa`. Cursor is on first `x` (not last).
6. Repeat 2-4 with lines `xxx` and `aaa`. Cursor is on last `x`.

Here is the demo:

https://user-images.githubusercontent.com/24854248/185797288-a2a5c750-c752-41c8-a0ca-513b56c51c0a.mp4

Forward search doesn't have this behavior. When doing similar with `aaa\nx`, `aaa\nxx`, `aaa\nxxx` lines and `:call search('\_.x', 'e')`, cursor always ends up on first `x`.

### Expected behaviour

Cursor is always on last `e`, as it is always the first one matching `e\_.` pattern when going backwards from end of buffer.

### Version of Vim

9.0.135

### Environment

OS: EndeavourOS Linux x86_64 (5.19.2-arch1-1)
Terminal: xfce4-terminal 1.0.4 (Xfce 4.16)
$TERM: xterm-256color
shell: zsh 5.9 (x86_64-pc-linux-gnu)

**Comment by brammool** [comment]
This works a bit unexpected, because a search actually goes forward, and then uses the last match.
Try removing "c" from the 'cpo' option. See ":help cpo-c".

**Comment by echasnovski** [comment]
Yes, this seems to be the case. Thanks. A bit surprising that backward search is done this way, to be honest. At least from the efficiency point of view.

As a side note: using `call search('x\ze\_.', 'b')` also seems to resolve this.
