### ISSUE TITLE
Pager does not behave as described

### ISSUE THREAD

**Issue by clearissimple** [vim/vim#1095]
I have this issue with 8.0.0005 (and earlier versions), configured with
`./configure --prefix=/home/local/vim --with-features=huge --enable-fail-if-missing --enable-pythoninterp=yes --enable-python3interp=yes --enable-gui`

Vim is run in `nocompatible` mode and `more` is set and the expected behavior is described in `:h more`
Running the command `:!cat file` with a file containing more than a screen full of lines, the output does not pause when the screen is filled. There is no more-prompt. The message 

> Press ENTER or type command to continue

appears. Pressing `b/u/k` brings up the more-prompt

> -- More --

Pressing `<S-k>` changes the more-prompt to

> -- More -- SPACE/d/j: screen/page/line down, b/u/k: up, q: quit

but the keys `b/u/k` do not scroll up. They just change the prompt back.

My expectation was that even if the output did not stop once the screen was full, it would be possible to scroll back up.

**Comment by clearissimple** [comment]
https://groups.yahoo.com/neo/groups/vim/conversations/messages/134347

> When Vim executes an internal command, it sends the output through
> its pager. When Vim executes an external command with :!, it gets
> out of the way and releases control of the terminal to that external
> program. [...]
> [U]se Vim's system command to execute `<cmd>`:
> `:echo system('<cmd>')`
> which will use Vim's pager.

**Comment by nuclight** [comment]
No, this is still a bug. See, if you press `K` on some word to get help, then (except of internal Vim help) you get external program running just as with `:!cmd` (e.g. I need it for `man` or `perldoc -f`). But in this case you have no way to do this `system()` trick. Which is, in fact, is still a *workaround* for the **bug** - I've seen some reports on https://stackoverflow.com/questions/27098543/how-to-scroll-up-gvim-terminal-output-of-external-command of people who has `b/u/k` working for external program in 7.4.347/Ubuntu but for others it don't.

So either GUI pty should work for those commands to draw as it is on "real" terminal, OR guipty should allow at least scrolling, with mouse or Shift-PgUp while in hit-enter prompt (and cursor is X), OR output of external command should be captured (may be come option?)

**Comment by woky** [comment]
> https://groups.yahoo.com/neo/groups/vim/conversations/messages/134347
> 
> > When Vim executes an internal command, it sends the output through
> > its pager. When Vim executes an external command with :!, it gets
> > out of the way and releases control of the terminal to that external
> > program. [...]
> > [U]se Vim's system command to execute `<cmd>`:
> > `:echo system('<cmd>')`
> > which will use Vim's pager.

FWIW, I've just tried `!find /etc` in NeoVim and there it's sent into internal pager by default. I get the reasoning described of leaving the terminal to the external program. For instance `!mc` (Midnight Commander) works in Vim but not in NeoVim. Though I suspect it's rare to run ncurses programs directly from Vim.

**Comment by bfrg** [comment]
> FWIW, I've just tried :!find /etc in NeoVim and there it's sent into internal pager by default. I get the reasoning described of leaving the terminal to the external program.

@woky You can achieve the same thing in Vim as well:
```vim
" File: ~/.vim/plugin/altscreen.vim

let g:altscreen_save_t_ti = &t_ti
let g:altscreen_save_t_te = &t_te

function s:unset_alt_screen()
    let &t_ti = substitute(&t_ti, '\e\[?1049[hl]', '', '')
    let &t_te = substitute(&t_te, '\e\[?1049[hl]', '', '')
endfunction

function s:set_alt_screen()
    let &t_ti = g:altscreen_save_t_ti
    let &t_te = g:altscreen_save_t_te
endfunction

augroup altscreen
    autocmd!
    autocmd VimEnter,VimResume  * call s:unset_alt_screen()
    autocmd VimLeave,VimSuspend * call s:set_alt_screen()
augroup END
```

Unfortunately, if you run something like `:!man gcc` and then later close Vim, the screen won't be restored and you're left with the Vim drawings. But apart from that it works fine. I don't know how Neovim does this.

I found the above snippet in [vim-altscreen](https://github.com/fcpg/vim-altscreen). But unlike the plugin, the above version doesn't use any custom `<C-z>` mappings, instead it relies on `VimResume` and `VimSuspend`. Those are need when you minimize Vim with `CTRL-z` and resume with `fg` from your shell.
