### ISSUE TITLE
Virtual text: cursor position incorrect when start_incl=1

### ISSUE THREAD

**Issue by puremourning** [vim/vim#10964]
### Steps to reproduce

```viml
let thecode =<< END
void   _SetErrorCode(int errorCode);

int main()
{
  _SetErrorCode( 10 );
}
END

call prop_type_add( 'Parameter', #{ highlight: 'NonText', start_incl: 1 } )

call prop_add( 6, 18, #{ type: 'Parameter', text: 'errorCode: ' } )
call cursor( 6, 18 )
```

* `vim --clean -S test.vim test.vim`
* `cw` - change the `10` token
* note the cursor position to the left of the virtual text `errorCode: `
* type `test` (or anything else)
* note cursor jumps to the right of the `errorCode: `

---

Note that I found this while trying to find a repro case investigating another issue that I'm really struggling to pin down. The issue is that when editing the last argument in a function where I have inlay hints added, screen drawing goes strange - just draws `@` down the left side and doesn't draw any of the buffer below. Any ideas?!

Initial state:

<img width="602" alt="Screenshot 2022-08-23 at 13 19 18" src="https://user-images.githubusercontent.com/10584846/186156408-f1aa6d6a-8e0a-460a-8bb9-5006cb18c784.png">

After typing `cw` on the `10` token:

<img width="604" alt="Screenshot 2022-08-23 at 13 19 25" src="https://user-images.githubusercontent.com/10584846/186156466-bcfbc546-7f72-43b6-8e82-98b7cd585a80.png">

### Expected behaviour

Cursor is to the right of the hint `errorCode` when changing the word
Cursor doesn't jump when entering text at that position.

### Version of Vim

9.0.124

### Environment

macOS intel

**Comment by brammool** [comment]
Ben Jackson wrote:

> ### Steps to reproduce
> 
> ```viml
> let thecode =<< END
> void   _SetErrorCode(int errorCode);
> 
> int main()
> {
>   _SetErrorCode( 10 );
> }
> END
> 
> call prop_type_add( 'Parameter', #{ highlight: 'NonText', start_incl: 1 } )
> call prop_add( 6, 18, #{ type: 'Parameter', text: 'errorCode: ' } )
> ```
> 
> * `vim --clean -S test.vim test.vim`
> * (note cursor position)

Where is it?

> * type `test`
> * (note cursor jumps)

What do you mean with "type test" ?

> Note that I found this while trying to find a repro case investigating
> another issue that I'm really struggling to pin down. The issue is
> that when editing the last argument in a function where I have inlay
> hints added, screen drawing goes strange - just draws `@` down the
> left side and doesn't draw any of the buffer below. Any ideas?!

I have just submitted a patch that adds padding for virtual text.  As
part of this the code has been refactored.  I might also solve this
problem.  Please try again.


-- 
Lose weight, NEVER Diet again with
                  The "Invisible Weight Loss Patch"
						(spam e-mail)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by puremourning** [comment]
sorry I think the repro case I pasted was broken. 

> Where is it?

The cursor was positioned to the left of the virtual text (rather than the right) when doing `cw` on the `10` token.

> What do you mean with "type test" ?

After `cw`, typing `test` (or anything else), the cursor jumped to the right of the virtual text. 

That said, I can no longer reproduce this particular cursor positioning issue with the above minimal case. 

However, I have found a perhaps related issue, this time the the text is inserted 1 character before the cursor position: 

Steps:

```viml
let thecode =<< END
void   _SetErrorCode(int count, int errorCode);
int main()
{
  _SetErrorCode( 11, 10 );
}
END

call prop_type_add( 'Parameter', #{ highlight: 'Comment', start_incl: 1 } )
call prop_type_add( 'Pad', #{ highlight: 'NonText', start_incl: 1 } )

call prop_add( 5, 18, #{ type: 'Parameter', text: 'id:' } )
call prop_add( 5, 18, #{ type: 'Pad', text: '-' } )
call prop_add( 5, 22, #{ type: 'Parameter', text: 'errorCode:' } )
call prop_add( 5, 22, #{ type: 'Pad', text: '-' } )
call cursor( 5, 22 )
```

* cursor should be on the `10` token
* `cw` enter insert mode
* cursor is just after the `-`
* start typing (e.g. type `test`)
* text is inserted 1 column before the cursor location

recording: https://asciinema.org/a/lseWYEn9auN1XcUIsySoHJjKU


> I have just submitted a patch that adds padding for virtual text.  As
part of this the code has been refactored.  I might also solve this
problem.  Please try again.

I can still reproduce other draw problem with 9.0.249. Sorry I'm still trying to minimise a test case that doesn't involve installing a complex plugin. I commented out all of the plugin's autocmds and mappings and timers, and whatnot and it still happens, but I'm scratching my head as to how to minimise the case. I'll keep trying.

**Comment by puremourning** [comment]
OK I have cracked it - the second problem is with `cursorline` - want me to open a separate issue?

Steps to repro:

```
let thecode =<< END
void   _SetErrorCode(int count, int errorCode);
int main()
{
  _SetErrorCode( 11, 10 );
}
END

set cursorline
call prop_type_add( 'Parameter', #{ highlight: 'Comment', start_incl: 1 } )
call prop_type_add( 'Pad', #{ highlight: 'NonText', start_incl: 1 } )

call prop_add( 5, 18, #{ type: 'Parameter', text: 'id:' } )
call prop_add( 5, 18, #{ type: 'Pad', text: '-' } )
call prop_add( 5, 22, #{ type: 'Parameter', text: 'errorCode:' } )
call prop_add( 5, 22, #{ type: 'Pad', text: '-' } )
call cursor( 5, 22 )
```

* cursor should be on the 10 token
* cw enter insert mode

See that the screen is drawn wrong from the current line to the end.

Recording: https://asciinema.org/a/M9zq08VKwLxaNjAZuuhUDIlGF

**Comment by brammool** [comment]
Ben Jackson wrote:

> sorry I think the repro case I pasted was broken. 
> 
> > Where is it?
> 
> The cursor was positioned to the left of the virtual text (rather than
> the right) when doing `cw` on the `10` token.
> 
> > What do you mean with "type test" ?
> 
> After `cw`, typing `test` (or anything else), the cursor jumped to the
> right of the virtual text. 
> 
> That said, I can no longer reproduce this particular cursor
> positioning issue with the above minimal case. 
> 
> However, I have found a perhaps related issue, this time the the text
> is inserted 1 character before the cursor position: 
> 
> Steps:
> 
> ```viml
> let thecode =<< END
> void   _SetErrorCode(int count, int errorCode);
> int main()
> {
>   _SetErrorCode( 11, 10 );
> }
> END
> 
> call prop_type_add( 'Parameter', #{ highlight: 'Comment', start_incl: 1 } )
> call prop_type_add( 'Pad', #{ highlight: 'NonText', start_incl: 1 } )
> 
> call prop_add( 5, 18, #{ type: 'Parameter', text: 'id:' } )
> call prop_add( 5, 18, #{ type: 'Pad', text: '-' } )
> call prop_add( 5, 22, #{ type: 'Parameter', text: 'errorCode:' } )
> call prop_add( 5, 22, #{ type: 'Pad', text: '-' } )
> call cursor( 5, 22 )
> ```
> 
> * cursor should be on the `10` token
> * `cw` enter insert mode
> * cursor is just after the `-`
> * start typing (e.g. type `test`)
> * text is inserted 1 column before the cursor location

OK, I can reproduce this.  The cursor seems to be in the right place,
but the displayed text is wrong.  I'll look into it tomorrow.

A repro case is needed for things like this, not only to pinpoint the
problem but also to be able to add a regression test.  Adding a display
item like virtual text interferes with every other display item, it will
take a lot of trying out to locate and fix all the problems.

-- 
User:       I'm having problems with my text editor.
Help desk:  Which editor are you using?
User:       I don't know, but it's version VI (pronounced: 6).
Help desk:  Oh, then you should upgrade to version VIM (pronounced: 994).

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by puremourning** [comment]
Thanks, confirmed this is working as expected.

**Comment by brammool** [comment]
> Thanks, confirmed this is working as expected.

The problem with 'cursorline' is also fixed now?
If not, please open a new issue, so it's easier to track.


-- 
Shaw's Principle: Build a system that even a fool can use, and
only a fool will want to use it.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by puremourning** [comment]
> The problem with 'cursorline' is also fixed now?

Yes it's also fixed.
