### ISSUE TITLE
Make statusline window-only.

### ISSUE THREAD

**Issue by ahnafis** [vim/vim#10966]
Hi all,

Vim's statusline is pretty  amazing but I don't like it when it splits up with splits. Like this:
![image](https://user-images.githubusercontent.com/77573476/186201689-1e7ccece-9b27-4e4a-b1c7-9eb91a853c3e.png)
![image](https://user-images.githubusercontent.com/77573476/186202763-2108e179-3568-4490-ac6b-f7b044c6766c.png)

I want statusline to be for current window, even if there's splits but not statusline to be splitted like this:
![image](https://user-images.githubusercontent.com/77573476/186202129-6fc387d3-86f1-431d-b336-c7fc993b11d4.png)

I hope that you'd be kind enough to add this feature.
Thank you!

**Comment by brammool** [comment]
I'm not sure I understand.  When there is a vertical split, you want the statusline for the current window to occupy the width of both windows?
With a horizontal split, how would you be able to see the separation between windows if there is no statusline?

**Comment by Shougo** [comment]
neovim has global statusline feature.
It is your expected?

**Comment by ahnafalnafis** [comment]
>  With a horizontal split, how would you be able to see the separation between windows if there is no statusline?

As we use a fillchar for vertical split like `let &fillchars = 'vert:|'`, we will use `let &fillchars = 'vert:|,hor:-'`

**Comment by ahnafalnafis** [comment]
> neovim has global statusline feature. It is your expected?

this?
![image](https://user-images.githubusercontent.com/77573476/186310703-66cce04d-a4fe-4f5d-b484-418e9799aa9c.png)

**Comment by ahnafalnafis** [comment]
Didn't know that Neovim has that already, nice anyway. Yeah I expected something like that. However, @brammool, could you please add this feature to Vim?

**Comment by brammool** [comment]
I do not like it.  You can't see what is in those windows.  Quite useless.

**Comment by ahnafalnafis** [comment]
https://github.com/neovim/neovim/issues/9342#issue-389223110

> ## What we have right now
> * Every window has its own statusline
> * But: Only one can be active at once
> * Inactive statusline gives no useful information...
> * Any sufficiently sophisticated statusline (powerline, etc) will get truncated in vertical splits
> * Truncation increases visual clutter
> * The default powerline setup easily fills up 80 characters (without plugins):
>   ![image](https://user-images.githubusercontent.com/38919842/49722881-fa895200-fc65-11e8-9ebd-2317b7bd39df.png)
> 
> ## The idea
> Wouldn't it be nice to have a single statusline at the bottom, like in screen or tmux?
> 
> * Statusline is always in the same spot, 'where you expect it to be'
> * We already have a 'global' command line: It's at the bottom!
> * Less visual clutter, nicer window seperators (see below)
> * Might speed up the UI: 'statusline' needs to be evaluated only for the active window, rather than all.
> * Only restricted in size by your Terminal.
> 
> ## How could it be done?
> I'm strongly in favor of a 'laststatus' value of 3 enabling the global statusline, since any value < 0 or > 2 currently doesn't error, and instead behaves like 'laststatus' = 1.
> 
> Currently, only vertical window seperators are used. ('vert' value in 'fillchars') All Terminals I've tried correctly display box drawing characters (tested with tmux), so I think those should be the default. Otherwise, window seperators would probably need their own option:
> 
> 'windowseperators' (default: ─│├┤┬┴┼, for 1-1, 1|1, 1|2, 2|1 1-2, 2-1, and 2*2 layouts respectively).
> 
> Another thing that _could_ be done would be to highlight the window seperators around the active window differently, like tmux does. This could be used to more easily distinguish the active window when the global statusline is enabled, although I don't think that is really necessary.
> 
> ## Costs
> Implementation: medium (Additional options and ui code) Maintainability: minor
> 
> ## A look into the future?
> This mock-up was made with tmux as well as some slight editing: ![nvim-global-statusline-mock](https://user-images.githubusercontent.com/38919842/49723015-3de3c080-fc66-11e8-9a16-71c3cceedf56.png)

This guy ^ explained well what I wanted. Read it please.
~Sorry for copy&pasting it here~

**Comment by chrisbra** [comment]
Doesn't that make it harder to detect which window is the active window?

**Comment by lacygoill** [comment]
> Vim's statusline is pretty amazing but I don't like it when it splits up with splits. Like this:

That's not what you want, but in case it helps, you can reduce the amount of space which is lost when splitting horizontally by setting [`'winminheight'`](https://vimhelp.org/options.txt.html#%27winminheight%27) to 0.

    set winminheight=0

You can also reduce visual clutter coming from all the statuslines by configuring [`'statusline'`](https://vimhelp.org/options.txt.html#%27statusline%27) so that the non-focused windows display less information (or even nothing).  For `'statusline'` to be able to distinguish between the 2 types of windows, you need to inspect `g:statusline_winid` (in a `%!Func()` expression), or `g:actual_curwin` (in a `%{}` item).

FWIW, here is how I do it:
https://github.com/lacygoill/vim-statusline/blob/f45aa31670be3285633c09861bf7f9836731fa5e/plugin/statusline.vim#L437-L448

And here is what it looks like:
![gif](https://user-images.githubusercontent.com/8505073/187019881-acae972d-234a-40e5-8c98-8b9e57629ce8.gif)

Notice that in the non-focused windows, only the filename is displayed, while the active window display more items.

**Comment by ahnafalnafis** [comment]
Great suggestion! Thank you!
