### ISSUE TITLE
Philosophy of Syntax Alignment for JavaScript & TypeScript

### ISSUE THREAD

**Issue by rschristian** [vim/vim#10976]
## Is your feature request about something that is currently impossible or hard to do? Please describe the problem.

TypeScript is a superset of JavaScript. As such, the vast majority of the syntax is exactly the same between the two languages. Despite this close tie, there is a huge disconnect between the highlighting of these two languages in Vim.

[Yats](https://github.com/HerringtonDarkholme/yats.vim), for better or for worse, makes no attempt at all to align with the underlying language (JS). Instead, as its documents plainly state, it wants to provide the most elaborate way to control TS highlighting.

> Exuberant Highlighting. The most elaborate or byzatine syntax highlighting for TypeScript.

This, in my opinion, makes it an issue to rely upon. The TS syntax distributed with Vim is not a superset of the JS syntax, making it far more difficult to configure and create a consistent experience.

Take the following line of code:

```js
import Foo from './foo.js';
```

In a `.js` file, that trailing semicolon is highlighted according to the `jsNoise` group. In a `.ts` file, however, that's according to the `typescriptEndColons` group.

I'm not necessarily debating the merits of what `yats`'s approach, but I am asking about the merits of including something that clearly has no intention of aligning. This makes creating color schemes much more tedious due to the non-aligning syntax grouping standards.

## Describe the solution you'd like

Ideally, as a language superset, the TS syntax should use JS as a base and build off of it.

In the example above, I think the ideal result is both labeled as `jsNoise`. TS-specific constructs would then be the only items bearing the `ts` prefix.

## Describe alternatives you've considered

TS could be kept separate, but with better name alignment.

For example, if in a `.js` file it's `jsNoise`, in a `.ts` is could be `tsNoise`. A bit silly, but much, much more manageable if they're building off common naming patterns.

## Additional context

I respect what `yats` is doing and the power it gives to the users who want to use it. However, as it clearly does not want to align with the JS syntax highlighting that already ships by default, it's not a good pick long-term.

If a language is a superset of another then so should the syntax files be. Either being far more complex and powerful than the other only creates inconsistencies and headaches for end users.

That being said, I do not know if a better option exists at this moment.

**Comment by romainl** [comment]
Vim uses yats because it exists and an existing syntax script is more valuable than one you have to create. If you want an alternative approach you will have to write it yourself and make a convincing PR.

See `:help :syn-include`.

**Comment by rschristian** [comment]
> and make a convincing PR.

Does this mean that there is little interest in alignment? If it was a decision out of convenience as you seem to indicate, surely a PR wouldn't have to be convincing at all. It's quite clearly problematic.

Apologies, but I'm not exactly sure as to your connection to Vim and its direction (GitHub hasn't even given you the 'contributor' label). Is this a maintainer stating I'd have to make a convincing PR, or a community member?

> See :help :syn-include.

I'm well aware, and that has little relevance to the topic at hand which is the philosophy of including syntax scripts that don't align to existing practices.

**Comment by romainl** [comment]
> > and make a convincing PR.

> Does this mean that there is little interest in alignment? If it was a decision out of convenience as you seem to indicate, surely a PR wouldn't have to be convincing at all. It's quite clearly problematic.

Bram discovered yats [by chance](https://github.com/vim/vim/issues/4830#issuecomment-554744936) and added it, plain and simple. There is no "philosophy" to speak of, here.

> Apologies, but I'm not exactly sure as to your connection to Vim and its direction (GitHub hasn't even given you the 'contributor' label). Is this a maintainer stating I'd have to make a convincing PR, or a community member?

I am a community member, just like you, and whenever I wanted something to be added to/changed in Vim (ftplugins/compilers, remade colorschemes, etc.) in the past I made it happen via a PR. As a front-end developer myself I agree with you that the `typescript` syntax should be treated as a superset of the `javascript` syntax but I don't care enough to write a proper syntax script. Since you appear to care a lot about this, the right way forward is for you to actually write that better syntax script and make a PR.
 
> > See :help :syn-include.

> I'm well aware, and that has little relevance to the topic at hand which is the philosophy of including syntax scripts that don't align to existing practices.

It has everything to do with you writing `$VIMRUNTIME/syntax/typescript.vim` the way you want.

**Comment by rschristian** [comment]
> There is no "philosophy" to speak of, here

I imagine there is some, even if you're not privy to it. Does `yats` align with their vision of Vim? Is it a fill in for something better? Is an ad-hoc, "whatever is available when needed then locked in forever" the approach? I don't know, and evidently you don't either. That's what I'm looking for.

> I am a community member, just like you ... the right way forward is for you to actually write that better syntax script and make a PR.

In that case, please excuse me for instead waiting for someone with some actual authority and control over long term plans to weigh in. It would be a fair bit of work and a community member saying "Go for it" provides little assurance it would be worth the effort.

There's also little chance I'd be up for personally maintaining that, which makes the PR route look like a pretty poor option.

> It has everything to do with you writing $VIMRUNTIME/syntax/typescript.vim the way you want.

No, please try to actually read what I've wrote. It's a question of ecosystem, not personal preference. I'm well aware that I could fix this myself.

**Comment by brammool** [comment]
Even though Typescript has become popular, there is only one set of Vim plugins available.  And nobody has stood up and said it needs to be improved and I'll do it.  It's not like there is a philosophy or plan, we just need someone to actually do the work first.  If that someone then asks "should I do it this way or that way" we can have a discussion.  Before that having a discussion just makes it harder to find someone to pick up the work.

**Comment by rschristian** [comment]
No plan or philosophy around official bundled plugins seems... weird, to say the least, but fair enough. Certainly could do with making one in that case if/when future languages are added, to ensure best compatibility and alignment. I'm not referring to just JS & TS here (although they're probably one of the best examples due to how closely they're tied), but syntax development in general.

I also wouldn't personally invest the time without having a discussion on the matter first, and quite frankly, I'm not sure who would. There's no documentation that I can find on all sorts of practices regarding breaking changes, patterns, future alignment plans, etc. Putting forth work despite the lack of direction just doesn't seem sensible for an outside contributor. Up front discussion helps ensure someone doesn't go down a track that'll immediately get rejected for being too off-base.

I'll close this out, as apparently having this discussion makes it harder to find people to make improvements. This is pretty clearly more of an ad-hoc ecosystem than anything with a plan, which isn't something I'm really up for contributing to personally.
