### ISSUE TITLE
ttymouse is not properly recognized for tmux

### ISSUE THREAD

**Issue by WhyNotHugo** [vim/vim#1097]
When `TERM` is set to `tmux` or `tmux-256color`, the mouse won't work as expected inside vim.

Apparently, this is because vim only sets `ttymouse` to `xterm` for certain terminals; from `ttymouse`'s doc:

> This option is automatically set to "xterm", when the 'term' option is set to a name that starts with "xterm", "mlterm", "screen", "st" (full match only), "st-" or "stterm", and 'ttymouse' is not set already.

I guess that the simple fix would be to also set is if `term` start with `tmux` as well.

**Comment by chrisbra** [comment]
fixed by [8.0.30](https://github.com/vim/vim/releases/tag/v8.0.0030)
