### ISSUE TITLE
`bufload` loads file into `nofile` buffer

### ISSUE THREAD

**Issue by cykerway** [vim/vim#10975]
### Steps to reproduce

From `:help 'buftype'`

>   nofile buffer which is not related to a file and will not be written

Literally, "not related to"... However this bash script

    echo "why read me" >> ./foo
    vim -u NONE \
        -c "let n = bufadd('foo')" \
        -c "call setbufvar(n, '&bt', 'nofile')" \
        -c "call bufload(n)" \
        -c "echo getbufline(n, 1, '$')"

Gives

    "foo" 1 line, 12 bytes
    ['why read me']
    Press ENTER or type command to continue

And they are related.

### Expected behaviour

The buffer should be empty.

### Version of Vim

9.0.77

### Environment

Fedora 36

**Comment by habamax** [comment]
Plugins are broken now https://github.com/vim/vim/issues/10983
