### ISSUE TITLE
The .sil filetype was clobbered

### ISSUE THREAD

**Issue by ctrlcctrlv** [vim/vim#10974]
### Steps to reproduce

1. In https://github.com/vim/vim/commit/0d76683e094c6cac2e879601aff3acf1163cbe0b (Jan 22, 2020), @brammool committed a change that added a filetype "*.sil". "Swift Intermediate Language", some Apple something or other.
2. This caused considerable trouble for users of the [SILE project](https://github.com/sile-typesetter/sile). It took us a while to even figure out what happened. @alerque managed to do so four months following my initial report (*quod est* https://github.com/sile-typesetter/vim-sile/issues/4#issue-738235563) in sile-typesetter/vim-sile#7.
3. We need to use a hacky override to overcome the issue. Cf. https://github.com/sile-typesetter/vim-sile/commit/6e98b9c70bf61f3d94f0bb4f4379081cb5f83cca.
4. Vim users, especially on GNU/Linux, are much more likely to be SILE users than to edit an Apple XCode .sil file.
5. **Please consider upstreaming our `sil.vim` officially and making the SWIFT one an opt-in, or OS-gated.**

### Expected behaviour

SILE syntax highlighting to work.

### Version of Vim

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 18 2022 19:26:30)

### Environment

Distributor ID:	Pop
Description:	Pop!_OS 22.04 LTS
Release:	22.04
Codename:	jammy
----
Terminal: kovidgoyal/kitty
Shell: bash
$TERM: `xterm-kitty`

**Comment by brammool** [comment]
So this was patch 8.2.0141 (we don't generally use these crazy git hex codes).
Before that patch *.sil files were not recognized.  Perhaps you had some local custom override?

When there are two or more languages using the same filename extension, we'll have to guess the filetype
from the contents.  Please suggest how to recognize a SILE file.
You may need to study "Swift Intermediate Language" to decide the best way to detect.

**Comment by ctrlcctrlv** [comment]
I studied a bit about the Apple SIL but can't understand well what it is or does. It seems to be an inferior form of LLVM bytecode.

But I actually think SILE is easier to detect.

A valid SILE .sil file grammar may look like:

```lark
sile: sile_line*
sile_line: COMMENT | NON_COMMENT
COMMENT: "%" ~ ANY_COMMENT_BYTE* ~ NL
NON_COMMENT: "\begin" ~ WS? ~ "{" ~ "document" ~ "}"
ANY_COMMENT_BYTE: /[^\n]/
NL: "\n"
WS: /\s+/
```

Right @alerque?

**Comment by alerque** [comment]
That's close. You're missing a match for the possibility of class options on the document declaration. Also for document fragments (not intended to be for primary documents but still *.sil format) we allow the inline variant `\document{}` over `\begin{document}` and also `\sile{}`. Yes I know stricter requirements would be easier to detect, but we're okay with accepting anything we can parse.

I had a bit of a look at Swift Intermediate Language. I'm not sure what tooling we have for this detection process, but a couple quick giveaways

* Comment syntax is different, so detecting comment lines would be a dead giveaway. Swift looks like it can have leading % tokens but probably only inside some kind of structure. Likewise SILE can have leading // but *only* inside some sort of command. Outside of a top level command only comments are allowed.
* `\` at the start of a line (after `WS?` of course) looks like it might be a dead giveaway for SILE.
* A few common keywords like `import` or `sil_stage` at the start of lines prior to any `{` or `}` symbols should be a sign of Swift.

**Comment by ctrlcctrlv** [comment]
```lark
// SILE .sil detector

sile: sile_line*
sile_line: COMMENT | NON_COMMENT
COMMENT: "%" ~ ANY_COMMENT_BYTE* ~ NL
DOC_BEGIN: "\\" ~ ("begin" | "document") ~ WS? ~ ARGS? ~ WS? ~ "{"
ARGS: "[" ~ (ANY* ~ !"]") ~ "]"
ANY_COMMENT_BYTE: /[^\n]/
NL: "\n"
WS: /\s+/
```

How about this?

**Comment by brammool** [comment]
Fredrick Brennan wrote:

> ```lark
> // SILE .sil detector
> 
> sile: sile_line*
> sile_line: COMMENT | NON_COMMENT
> COMMENT: "%" ~ ANY_COMMENT_BYTE* ~ NL
> DOC_BEGIN: "\\" ~ ("begin" | "document") ~ WS? ~ ARGS? ~ WS? ~ "{"
> ARGS: "[" ~ (ANY* ~ !"]") ~ "]"
> ANY_COMMENT_BYTE: /[^\n]/
> NL: "\n"
> WS: /\s+/
> ```
> 
> How about this?

I'm not sure what this is.  The detection needs to be written in Vim
script.  You can find examples in $VIMRUNTIME/autoload/dist/ft.vim

-- 
Permission is granted to read this message out aloud on Kings Cross Road,
London, under the condition that the orator is properly dressed.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by alerque** [comment]
"This" appears to be a bit of EBNF grammar. Quite a useful thing when reasoning about a language or writing a parser for it. If we had an EBNF for Swift-I-L right now it would make our jobs a lot easier.

For this use case I would suggest we don't even need to parse for half of this. We can iterate through a few lines looking for heuristics of things that *cannot* appear in one language or the other. The SILE side is probably the easiest to detect here: iterate over lines ignoring blanks or anything starting with whitespace and a `%`. Then if the first non-whitespace character you hit is a `\` then the file is SILE. If it's a letter it's probably part of a Swift-I-L token.

**Comment by ctrlcctrlv** [comment]
> Fredrick Brennan wrote:
> ```lark // SILE .sil detector sile: sile_line* sile_line: COMMENT | NON_COMMENT COMMENT: "%" ~ ANY_COMMENT_BYTE* ~ NL DOC_BEGIN: "\\" ~ ("begin" | "document") ~ WS? ~ ARGS? ~ WS? ~ "{" ARGS: "[" ~ (ANY* ~ !"]") ~ "]" ANY_COMMENT_BYTE: /[^\n]/ NL: "\n" WS: /\s+/ ``` How about this?
> I'm not sure what this is. The detection needs to be written in Vim script. You can find examples in $VIMRUNTIME/autoload/dist/ft.vim
> […](#)
> -- Permission is granted to read this message out aloud on Kings Cross Road, London, under the condition that the orator is properly dressed. /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net \\\ /// \\\ \\\ sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ /// \\\ help me help AIDS victims -- http://ICCF-Holland.org ///

I understand that very well. But before I take the time to write that, something I've never done, it'd be good to know that my proposed grammar is correct, before I translate it to vimscript. :-)

**Comment by lacygoill** [comment]
How about this:
```diff
diff --git a/runtime/autoload/dist/ft.vim b/runtime/autoload/dist/ft.vim
index 5db68d3cb..3cd04a0b3 100644
--- a/runtime/autoload/dist/ft.vim
+++ b/runtime/autoload/dist/ft.vim
@@ -878,6 +878,18 @@ export def FTsig()
   endif
 enddef
 
+# This function checks the first 25 lines of file extension "sil" to resolve
+# detection between Swift Intermediate Language and SILE
+export def FTsil()
+  for lnum in range(1, [line('$'), 25]->min())
+    if getline(lnum) =~ '^\s*\\'
+      setf sile
+      return
+    endif
+  endfor
+  setf sil
+enddef
+
 export def FTsys()
   if exists("g:filetype_sys")
     exe "setf " .. g:filetype_sys
diff --git a/runtime/filetype.vim b/runtime/filetype.vim
index 797c73a6a..82641ff3a 100644
--- a/runtime/filetype.vim
+++ b/runtime/filetype.vim
@@ -1927,7 +1927,7 @@ au BufNewFile,BufRead *.swift			setf swift
 au BufNewFile,BufRead *.swift.gyb		setf swiftgyb
 
 " Swift Intermediate Language
-au BufNewFile,BufRead *.sil			setf sil
+au BufNewFile,BufRead *.sil			call dist#ft#FTsil()
 
 " Sysctl
 au BufNewFile,BufRead */etc/sysctl.conf,*/etc/sysctl.d/*.conf	setf sysctl
```

**Comment by alerque** [comment]
Swift Intermediate Language appears to use a subset of the [grammar of Swift](https://docs.swift.org/swift-book/ReferenceManual/zzSummaryOfTheGrammar.html). There are no allowed usage of `\` at the start of an expression. It does look like it would be possible to contrive one where an expression started on a previous line could continue starting with a `\`:

```swift
// valid
let protoErasedPathA = \ABCProtocol.a

// also valid
let protoErasedPathA =
	\ABCProtocol.a
```

Searching a few million projects using grep.app for [Swift code with lines like this](https://grep.app/search?q=%5E%5Cw%2A%5C%5C&regexp=true&filter[lang][0]=Swift) I found none at all in the wild.

I would say @lacygoill's attempt would probably be 99.9% accurate in the wild.

To improve it one would need to check for signs of both languages. E.g. look for a line starting `\` as in thatcode and call it SILE, but also check each line to see if it starts with anything other than `\` or `%` and call it Swift-I-L.

**Comment by lacygoill** [comment]
> but also check each line to see if it starts with anything other than \ or % and call it Swift-I-L.

OK, let's try to improve the detection a little:
```diff
diff --git a/runtime/autoload/dist/ft.vim b/runtime/autoload/dist/ft.vim
index 5db68d3cb..f86234e12 100644
--- a/runtime/autoload/dist/ft.vim
+++ b/runtime/autoload/dist/ft.vim
@@ -878,6 +878,21 @@ export def FTsig()
   endif
 enddef
 
+# This function checks the first 25 lines of file extension "sil" to resolve
+# detection between Swift Intermediate Language and SILE
+export def FTsil()
+  for lnum in range(1, [line('$'), 25]->min())
+    var line: string = getline(lnum)
+    if line =~ '^\s*\\'
+      setf sile
+    elseif line =~ '^\s*[^ \t\\%]'
+      setf sil
+      return
+    endif
+  endfor
+  setf sil
+enddef
+
 export def FTsys()
   if exists("g:filetype_sys")
     exe "setf " .. g:filetype_sys
diff --git a/runtime/filetype.vim b/runtime/filetype.vim
index 797c73a6a..6a07c1454 100644
--- a/runtime/filetype.vim
+++ b/runtime/filetype.vim
@@ -1926,8 +1926,8 @@ au BufNewFile,BufRead *.cm			setf voscm
 au BufNewFile,BufRead *.swift			setf swift
 au BufNewFile,BufRead *.swift.gyb		setf swiftgyb
 
-" Swift Intermediate Language
-au BufNewFile,BufRead *.sil			setf sil
+" Swift Intermediate Language (or SILE)
+au BufNewFile,BufRead *.sil			call dist#ft#FTsil()
 
 " Sysctl
 au BufNewFile,BufRead */etc/sysctl.conf,*/etc/sysctl.d/*.conf	setf sysctl
```

**Comment by alerque** [comment]
That looks pretty robust to me. I haven't run it but given what I know of their grammars it should be accurate.

Coding wise I think you need to end early in the first if as well as the elseif, the `return` is missing there. As a nitpick I wight reuse `\s` instead of `[ \t]` and skip the slash detection as the first if should have caught it already, as in:

```viml
elseif line =~ '^\s*[^\s\%]'
```

The only case I can think of it might fail now is more than 25 lines of whitespace in either file type or more than 25 lines of leading comments before the start of a document in a sile file. I assume there is some "sane" threshold for performance reasons to have an arbitrary limit like that so I'll leave it up to you VIM folks to settle that.

**Comment by lacygoill** [comment]
> I think you need to end early in the first if as well as the elseif, the return is missing there.

Right, the `return` statement is missing:
```diff
diff --git a/runtime/autoload/dist/ft.vim b/runtime/autoload/dist/ft.vim
index 5db68d3cb..1baf3fa41 100644
--- a/runtime/autoload/dist/ft.vim
+++ b/runtime/autoload/dist/ft.vim
@@ -878,6 +878,22 @@ export def FTsig()
   endif
 enddef
 
+# This function checks the first 25 lines of file extension "sil" to resolve
+# detection between Swift Intermediate Language and SILE
+export def FTsil()
+  for lnum in range(1, [line('$'), 25]->min())
+    var line: string = getline(lnum)
+    if line =~ '^\s*\\'
+      setf sile
+      return
+    elseif line =~ '^\s*[^ \t%]'
+      setf sil
+      return
+    endif
+  endfor
+  setf sil
+enddef
+
 export def FTsys()
   if exists("g:filetype_sys")
     exe "setf " .. g:filetype_sys
diff --git a/runtime/filetype.vim b/runtime/filetype.vim
index 797c73a6a..6a07c1454 100644
--- a/runtime/filetype.vim
+++ b/runtime/filetype.vim
@@ -1926,8 +1926,8 @@ au BufNewFile,BufRead *.cm			setf voscm
 au BufNewFile,BufRead *.swift			setf swift
 au BufNewFile,BufRead *.swift.gyb		setf swiftgyb
 
-" Swift Intermediate Language
-au BufNewFile,BufRead *.sil			setf sil
+" Swift Intermediate Language (or SILE)
+au BufNewFile,BufRead *.sil			call dist#ft#FTsil()
 
 " Sysctl
 au BufNewFile,BufRead */etc/sysctl.conf,*/etc/sysctl.d/*.conf	setf sysctl
```
---

   > As a nitpick I wight reuse \s instead of [ \t]

That wouldn't work with the Vim regex engine.  Inside a collection, the metacharacters expressing a class of characters (such as `\s`) lose their special meaning.  That is `[\s]` does not match spaces and tabs; it matches backslashes and `s` characters.

   > and skip the slash detection as the first if should have caught it already, as in:

I guess you're right, so I removed the backslash from the collection in the previous diff.

   > I assume there is some "sane" threshold for performance reasons to have an arbitrary limit like that

Indeed, we probably need a limit so that setting the filetype does not take too much time on a file which would have too many lines.

I chose 25 because that's what is used in another function with a similar goal:
<https://github.com/vim/vim/blob/2e6dcbc4450c98bd12faace5d77a65f2afddae44/runtime/autoload/dist/ft.vim#L811-L814>

That being said, if we look for the pattern `range`, we find different limits for different filetypes:

    for lnum in range(1, min([line("$"), 100]))
    for n in range(1, max)
    for n in range(1, max)
    for lnum in range(1, min([line("$"), 20]))
    for lnum in range(1, min([line("$"), 25]))
    for i in range(1, numberOfLines)

Maybe we could settle on some default value which would be applied more consistently.

**Comment by brammool** [comment]
If this looks like it's going to work, it would be good to add a test.
There are examples near the end of src/testdir/test_filetype.vim

-- 
BEDEVERE: How do you know so much about swallows?
ARTHUR:   Well you have to know these things when you're a king, you know.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> If this looks like it's going to work, it would be good to add a test.

This patch adds a test, and increases the number of lines peeked at up to 100:
```diff
diff --git a/runtime/autoload/dist/ft.vim b/runtime/autoload/dist/ft.vim
index 5db68d3cb..4c6c1a6f8 100644
--- a/runtime/autoload/dist/ft.vim
+++ b/runtime/autoload/dist/ft.vim
@@ -878,6 +878,22 @@ export def FTsig()
   endif
 enddef
 
+# This function  checks the first 100  lines of file extension  "sil" to resolve
+# detection between Swift Intermediate Language and SILE
+export def FTsil()
+  for lnum in range(1, [line('$'), 100]->min())
+    var line: string = getline(lnum)
+    if line =~ '^\s*\\'
+      setf sile
+      return
+    elseif line =~ '^\s*[^ \t\\%]'
+      setf sil
+      return
+    endif
+  endfor
+  setf sil
+enddef
+
 export def FTsys()
   if exists("g:filetype_sys")
     exe "setf " .. g:filetype_sys
diff --git a/runtime/filetype.vim b/runtime/filetype.vim
index 797c73a6a..6a07c1454 100644
--- a/runtime/filetype.vim
+++ b/runtime/filetype.vim
@@ -1926,8 +1926,8 @@ au BufNewFile,BufRead *.cm			setf voscm
 au BufNewFile,BufRead *.swift			setf swift
 au BufNewFile,BufRead *.swift.gyb		setf swiftgyb
 
-" Swift Intermediate Language
-au BufNewFile,BufRead *.sil			setf sil
+" Swift Intermediate Language (or SILE)
+au BufNewFile,BufRead *.sil			call dist#ft#FTsil()
 
 " Sysctl
 au BufNewFile,BufRead */etc/sysctl.conf,*/etc/sysctl.d/*.conf	setf sysctl
diff --git a/src/testdir/test_filetype.vim b/src/testdir/test_filetype.vim
index 4e69175d8..164c6b767 100644
--- a/src/testdir/test_filetype.vim
+++ b/src/testdir/test_filetype.vim
@@ -1823,6 +1823,40 @@ func Test_sig_file()
   filetype off
 endfunc
 
+func Test_sil_file()
+  filetype on
+
+  " Test dist#ft#FTsil()
+
+  split Xfile.sil
+  call assert_equal('sil', &filetype)
+  bwipe!
+
+  let lines =<< trim END
+  // valid
+  let protoErasedPathA = \ABCProtocol.a
+
+  // also valid
+  let protoErasedPathA =
+          \ABCProtocol.a
+  END
+  call writefile(lines, 'Xfile.sil')
+
+  split Xfile.sil
+  call assert_equal('sil', &filetype)
+  bwipe!
+
+  " SILE
+
+  call writefile(['\begin[papersize=a6]{document}'], 'Xfile.sil')
+  split Xfile.sil
+  call assert_equal('sile', &filetype)
+  bwipe!
+
+  call delete('Xfile.sil')
+  filetype off
+endfunc
+
 func Test_inc_file()
   filetype on
 
```
I have no idea how reliable/correct it is.

**Comment by alerque** [comment]
Just for grins, lets make the generated test sample files actually valid such that SILE would not complain when parsing it. That means closing the environment you opened:

```diff
- call writefile(['\begin[papersize=a6]{document}'], 'Xfile.sil')
+ call writefile(['\begin[papersize=a6]{document}foo\end{document}'], 'Xfile.sil')
```

For test robustness a file that had leading SILE format comments might be useful too.

**Comment by lacygoill** [comment]
> Just for grins, lets make the generated test sample files actually valid such that SILE would not complain when parsing it. That means closing the environment you opened:

OK, I merged the patch:
```diff
diff --git a/runtime/autoload/dist/ft.vim b/runtime/autoload/dist/ft.vim
index 5db68d3cb..851ca74b5 100644
--- a/runtime/autoload/dist/ft.vim
+++ b/runtime/autoload/dist/ft.vim
@@ -878,6 +878,22 @@ export def FTsig()
   endif
 enddef
 
+# This function  checks the first 100  lines of file extension  "sil" to resolve
+# detection between Swift Intermediate Language and SILE
+export def FTsil()
+  for lnum in range(1, [line('$'), 100]->min())
+    var line: string = getline(lnum)
+    if line =~ '^\s*[\\%]'
+      setf sile
+      return
+    elseif line =~ '^\s*\S'
+      setf sil
+      return
+    endif
+  endfor
+  setf sil
+enddef
+
 export def FTsys()
   if exists("g:filetype_sys")
     exe "setf " .. g:filetype_sys
diff --git a/runtime/filetype.vim b/runtime/filetype.vim
index 797c73a6a..6a07c1454 100644
--- a/runtime/filetype.vim
+++ b/runtime/filetype.vim
@@ -1926,8 +1926,8 @@ au BufNewFile,BufRead *.cm			setf voscm
 au BufNewFile,BufRead *.swift			setf swift
 au BufNewFile,BufRead *.swift.gyb		setf swiftgyb
 
-" Swift Intermediate Language
-au BufNewFile,BufRead *.sil			setf sil
+" Swift Intermediate Language (or SILE)
+au BufNewFile,BufRead *.sil			call dist#ft#FTsil()
 
 " Sysctl
 au BufNewFile,BufRead */etc/sysctl.conf,*/etc/sysctl.d/*.conf	setf sysctl
diff --git a/src/testdir/test_filetype.vim b/src/testdir/test_filetype.vim
index 4e69175d8..d08201142 100644
--- a/src/testdir/test_filetype.vim
+++ b/src/testdir/test_filetype.vim
@@ -1823,6 +1823,45 @@ func Test_sig_file()
   filetype off
 endfunc
 
+func Test_sil_file()
+  filetype on
+
+  " Test dist#ft#FTsil()
+
+  split Xfile.sil
+  call assert_equal('sil', &filetype)
+  bwipe!
+
+  let lines =<< trim END
+  // valid
+  let protoErasedPathA = \ABCProtocol.a
+
+  // also valid
+  let protoErasedPathA =
+          \ABCProtocol.a
+  END
+  call writefile(lines, 'Xfile.sil')
+
+  split Xfile.sil
+  call assert_equal('sil', &filetype)
+  bwipe!
+
+  " SILE
+
+  call writefile(['% some comment'], 'Xfile.sil')
+  split Xfile.sil
+  call assert_equal('sile', &filetype)
+  bwipe!
+
+  call writefile(['\begin[papersize=a6]{document}foo\end{document}'], 'Xfile.sil')
+  split Xfile.sil
+  call assert_equal('sile', &filetype)
+  bwipe!
+
+  call delete('Xfile.sil')
+  filetype off
+endfunc
+
 func Test_inc_file()
   filetype on
 
```
---

   > For test robustness a file that had leading SILE format comments might be useful too.

I added a test, but I noticed that the code did not recognize such a file as SILE, so I also had to tweak the regexes in `FTsil()`.

**Comment by brammool** [comment]
I have included that last suggested patch.  I'll assume this is fixed now.  If not, please reopen.
