### ISSUE TITLE
BufReadCmd is not fired if buftype is set to nofile, acwrite and others

### ISSUE THREAD

**Issue by habamax** [vim/vim#10983]
### Steps to reproduce

1. `vim -Nu NONE`
2. `:au BufReadCmd * echom "BufReadCmd is called"`
3. `:new somefile`
4. `:set buftype=nofile`
5. `:e`

In step 4. buftype could be set to `acwrite` or other types. (NOTE, `help`, `nowrite` are not affected)

### Expected behaviour

In previous versions, at least in 9.0.242 I get the message, In the recent version there is no message, `BufReadCmd` is not fired.

My plugin relies on that autocommand to populate a buffer which has no file representation.

### Version of Vim

9.0.270

### Environment

- OS: Fedora 36
- Terminal: XTerm, Foot, GVim
- `$TERM`: `Xterm-256color` for xterm, `foot` for Foot
- Shell: `bash`

**Comment by lacygoill** [comment]
Regression introduced by patch [9.0.0261](https://github.com/vim/vim/releases/tag/v9.0.0261).

---

The same patch also breaks this shell command:

    vim -Nu NORC +'split ftp://ftp.vim.org/pub/vim/patches/9.0/README'

Before the patch, a split was open displaying a buffer with all the Vim 9.0 patches.  Now that same buffer is empty.

**Comment by habamax** [comment]
git bisect shows it is `[2eddbacd6dc17c84e4bdc41e60e81949a36bb973] patch 9.0.0261: bufload() reads a file even if the name is not a file name`

**Comment by wimstefan** [comment]
> git bisect shows it is `[2eddbacd6dc17c84e4bdc41e60e81949a36bb973] patch 9.0.0261: bufload() reads a file even if the name is not a file name`

I can confirm that. I've bisected neovim where the same problem is playing and bisecting it showed the same commit ...

**Comment by brammool** [comment]
Maxim Kim wrote:

> ### Steps to reproduce
> 
> 1. `vim -Nu NONE`
> 2. `:au BufReadCmd * echom "BufReadCmd is called"
> 3. `:new somefile`
> 4. `:set buftype=nofile`
> 5. `:e`
> 
> In step 4. buftype could be set to `acwrite` or other types. (NOTE, `help`, `nowrite` are not affected)
> 
> ### Expected behaviour
> 
> In previous versions, at least in 9.0.242 I get the message, In the recent version there is no message, `BufReadCmd` is not fired.
> 
> My plugin relies on that autocommand to populate a buffer which has no
> file representation.

One might argue that you can expect ":edit" not to work if the buftype
is "nofile".  But we do want to maintain backwards compatibility.

I guess we can call readfile but bail out before actually reading the
file, no matter if BufReadCmd did something or not.


-- 
Citizens are not allowed to attend a movie house or theater nor ride in a
public streetcar within at least four hours after eating garlic.
		[real standing law in Indiana, United States of America]

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by habamax** [comment]
> One might argue that you can expect ":edit" not to work if the buftype
is "nofile"

I am ok if it would still work with `acwrite` but it broke netrw too

**Comment by habamax** [comment]
Thank you for fixing this, works for me!

**Comment by lacygoill** [comment]
netrw is still broken (see the previous shell command).  I'll try to find a MRE.

**Comment by wimstefan** [comment]
> netrw is still broken (see the previous shell command). I'll try to find a MRE.

I hope this will be fixed as well. I'm using this functionality on a daily basis ...

OT: out of curiosity - what does `MRE` mean? ;)

**Comment by lacygoill** [comment]
> OT: out of curiosity - what does MRE mean? ;)

[Minimal Reproducible Example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)

**Comment by zeertzjq** [comment]
This fix also introduced another regression: #10986

**Comment by brammool** [comment]
> This fix also introduced another regression: #10986

It appears this functionality isn't well tested.  Many corner cases.

-- 
Snoring is prohibited unless all bedroom windows are closed and securely
locked.
		[real standing law in Massachusetts, United States of America]

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Shane-XB-Qian** [comment]
> netrw is still broken (see the previous shell command). I'll try to find a MRE.

should be fixed also now.
// i tried http (vs ftp though)

**Comment by brammool** [comment]
> netrw is still broken (see the previous shell command).  I'll try to
> find a MRE.

It looks like netrw depends on the bug that was fixed.  The file name is
set to the temp file, which contains the fetched remote file.

We could fix netrw, but this hints at other plugins also relying on not
fixing the bug.

It might be sufficient to exclude "acwrite" and "nowrite", since these
don't say the buffer won't be read.  Let's try that first.

-- 
It is illegal to rob a bank and then shoot at the bank teller with a water
pistol.
		[real standing law in Louisana, United States of America]

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
