### ISSUE TITLE
Deprecate mouse visual mode in favor of standard copy paste behavior of the mouse in insert mode

### ISSUE THREAD

**Issue by kulvait** [vim/vim#10984]
When I am trying copy paste something by mouse in vim it just does not work, the reason is that visual mode see also here
https://medium.com/@desfocado/how-to-disable-visual-mode-on-mouse-select-for-vim-dd3b2632a1ae

Now despite it is possible to edit ~/.vimrc I find it so annoying that I prefer editing system wide configuration. Unfortunately it is system specific and when you do it e.g. in /etc/vim/vimrc it is in some systems replaced by later loaded config.

Since I am sure it bugs lot of people that standard copy-pasting that works in most of Linux do not work in vim by default, I propose to change defaults in favor of  set mouse-=a.

**Comment by brammool** [comment]
Was discussed several times before.
