### ISSUE TITLE
cmdline=0 colors origin

### ISSUE THREAD

**Issue by habamax** [vim/vim#11001]
Not a feature request but a question about colors being used for the messages when `cmdheight` is 0.

In the pictures you can see them in red, which might be not very well readable in some colorschemes:

![image](https://user-images.githubusercontent.com/234774/187071814-09de9c75-0978-4fda-8f34-298c5052dc6d.png)

![image](https://user-images.githubusercontent.com/234774/187071912-e5220ad0-1f30-4d47-97fe-aa9d4784cbac.png)

**Comment by habamax** [comment]
Oh, it is a new `MessageWindow` hl group

**Comment by lacygoill** [comment]
We might want to document this new highlight group with a dedicated help tag, along with all the other ones below [`:help highlight-groups`](https://vimhelp.org/syntax.txt.html#highlight-groups):
```diff
diff --git a/runtime/doc/syntax.txt b/runtime/doc/syntax.txt
index 7d6b92da1..596b797cf 100644
--- a/runtime/doc/syntax.txt
+++ b/runtime/doc/syntax.txt
@@ -5368,7 +5368,9 @@ CursorLineFold	Like FoldColumn when 'cursorline' is set for the cursor line.
 							*hl-MatchParen*
 MatchParen	Character under the cursor or just before it, if it
 		is a paired bracket, and its match. |pi_paren.txt|
-
+							*hl-MessageWindow*
+MessageWindow	Text in popup notification which is opened when informative
+		messages need to be displayed and 'cmdheight' is set to 0.
 							*hl-ModeMsg*
 ModeMsg		'showmode' message (e.g., "-- INSERT --").
 							*hl-MoreMsg*
```

**Comment by lifepillar** [comment]
Is [`PopupNotification`](https://github.com/vim/vim/blob/00d4ceeccafb36f1337d133489b3651c11e78c30/src/popupwin.c#L1947) a new highlight group, too? Also, do they have a value in default yet?

**Comment by brammool** [comment]
When MessageWindow is not specified then WarningMsg is used.  you might want to check this is readable before adding a MessageWindow highlight.  PopupNotification is used for a popup window created with popup_notification().  It also falls back to WarningMsg.

**Comment by lacygoill** [comment]
```diff
diff --git a/runtime/doc/syntax.txt b/runtime/doc/syntax.txt
index 7d6b92da1..52c466d3f 100644
--- a/runtime/doc/syntax.txt
+++ b/runtime/doc/syntax.txt
@@ -5368,7 +5368,9 @@ CursorLineFold	Like FoldColumn when 'cursorline' is set for the cursor line.
 							*hl-MatchParen*
 MatchParen	Character under the cursor or just before it, if it
 		is a paired bracket, and its match. |pi_paren.txt|
-
+							*hl-MessageWindow*
+MessageWindow	Text in popup notification which is opened when informative
+		messages need to be displayed and 'cmdheight' is set to 0.
 							*hl-ModeMsg*
 ModeMsg		'showmode' message (e.g., "-- INSERT --").
 							*hl-MoreMsg*
@@ -5388,6 +5390,10 @@ PmenuSel	Popup menu: Selected item.
 PmenuSbar	Popup menu: Scrollbar.
 							*hl-PmenuThumb*
 PmenuThumb	Popup menu: Thumb of the scrollbar.
+							*hl-PopupNotification*
+PopupNotification	Text in popup window created by `popup_notification()`.
+							*hl-PopupSelected*
+PopupSelected	Current line in popup window created by `popup_menu()`.
 							*hl-Question*
 Question	|hit-enter| prompt and yes/no questions.
 							*hl-QuickFixLine*
```
---

These ones are also missing:

   - `hl-lCursor`
   - `hl-ToolbarButton`
   - `hl-ToolbarLine`

Probably a few other ones too.

**Comment by lifepillar** [comment]
>Probably a few other ones too.

From a quick check of mine: apart from the ones you have just documented and the ones you mention, only those under `:help group-name` (`Constant`, `String`, …).
