### ISSUE TITLE
syntax region ends prematurely when nesting escaped newline and 'conceallevel' is non-zero

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#11007]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        syntax on
        syntax region xString start=/"/ end=/"/ contains=EscapedNewline
        syntax match EscapedNewline /\\\n/ contained
        highlight link xString String
        &l:conceallevel = 1
        var lines =<< trim END
            "xxx \
            xxx"
            xxx
            xxx
            xxx
        END
        lines->setline(1)
        feedkeys('jjj', 'nt')
        echomsg synstack('.', col('.'))->map((_, id) => id->synIDattr('name'))
    EOF
    )

This is echoed:

    ['xString']

The `xxx` on the second line is not highligthed.
The three `xxx` lines after the second double quote are highlighted with `String`.

**Expected behavior**

This is echoed:

    []

The `xxx` on the second line is highligthed with `String`.
The three lines after the second double quote are not highlighted.

**Version of Vim**

9.0 Included patches: 1-322

**Environment**

Operating system: Ubuntu 20.04.4 LTS
Terminal: XTerm(353)
Value of $TERM: xterm-256color
Shell: GNU bash, version 5.0.17

**Additional context**

The issue disappears if we let `'conceallevel'` set to 0.

---

If we move the cursor up and down, the syntax alternates between correct (when it's on the first line), and wrong.

Gif to illustrate:

![gif](https://user-images.githubusercontent.com/8505073/187301655-eb0cc429-49b6-44e2-b84a-d2a0581c337c.gif)

---

As a workaround, we need to assert the presence of the newline with a zero-width atom, without including it in the match:

    syntax match EscapedNewline /\\\n\@=/ contained
                                     ^^^

**Comment by lacygoill** [comment]
No need to execute `:syntax on`:
```vim
vim9script
syntax region xString start=/"/ end=/"/ contains=EscapedNewline
syntax match EscapedNewline /\\\n/ contained
highlight link xString Search
&l:conceallevel = 1
var lines =<< trim END
    "xxx \
    xxx"
    xxx
    xxx
    xxx
END
lines->setline(1)
feedkeys('jjj', 'nt')
echomsg synstack('.', col('.'))->map((_, id) => id->synIDattr('name'))
```

**Comment by brammool** [comment]
> **Steps to reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(tee <<'EOF'
>         vim9script
>         syntax on
>         syntax region xString start=/"/ end=/"/ contains=EscapedNewline
>         syntax match EscapedNewline /\\\n/ contained
>         highlight link xString String
>         &l:conceallevel = 1
>         var lines =<< trim END
>             "xxx \
>             xxx"
>             xxx
>             xxx
>             xxx
>         END
>         lines->setline(1)
>         feedkeys('jjj', 'nt')
>         echomsg synstack('.', col('.'))->map((_, id) => id->synIDattr('name'))
>     EOF
>     )
> 
> This is echoed:
> 
>     ['xString']
> 
> The `xxx` on the second line is not highligthed.
> The three `xxx` lines after the second double quote are highlighted with `String`.
> 
> **Expected behavior**
> 
> This is echoed:
> 
>     []
> 
> The `xxx` on the second line is highligthed with `String`.
> The three lines after the second double quote are not highlighted.
> 
> **Version of Vim**
> 
> 9.0 Included patches: 1-322
> 
> **Environment**
> 
> Operating system: Ubuntu 20.04.4 LTS
> Terminal: XTerm(353)
> Value of $TERM: xterm-256color
> Shell: GNU bash, version 5.0.17
> 
> **Additional context**
> 
> The issue disappears if we let `'conceallevel'` set to 0.
> 
> ---
> 
> If we move the cursor up and down, the syntax alternates between correct (when it's on the first line), and wrong.
> 
> Gif to illustrate:
> 
> ![gif](https://user-images.githubusercontent.com/8505073/187301655-eb0cc429-49b6-44e2-b84a-d2a0581c337c.gif)
> 
> ---
> 
> As a workaround, we need to assert the presence of the newline with a zero-width atom, without including it in the match:
> 
>     syntax match EscapedNewline /\\\n\@=/ contained
>                                      ^^^

It indeed is caused by moving the cursor up and down.  And also the
setting that the cursorline is not concealed (which is the default).
Then when moving the cursor code is invoked that will redraw just the
cursor line and the line that the cursor was previously on.  That means
the syntax region is computed from where the redrawing starts, which
doesn't take regions into account that include a line break.

The problem is that your syntax rule crosses lines, but you have not
defined syntax syncing.  You need to add something like:
	syn sync minlines=10

-- 
The problem with political jokes is that they get elected.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
