### ISSUE TITLE
Add `{list}` support to `items()`

### ISSUE THREAD

**Issue by noscript** [vim/vim#11013]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

`items()` allows to iterate dictionaries as key-value pairs, but it cannot be used with lists. There is no convenient way to access item's index and value at the same time, those have to be calculated separately:

```vim
vim9script
var list = ['h', 'e', 'l', 'l', 'o']

# workaround 1:
var index = 0
for val in list
  echom $'{index}: {val}'
  ++index
endfor

# workaround 2:
for idx in list->len()->range()
  var val = list[idx]
  echom $'{idx}: {val}'
endfor
```

**Describe the solution you'd like**
Add `{list}` support to `items()` and return a |List| of `[index, value]` pairs, so it would be possible to iterate them like so:

```vim
vim9script
var list = ['h', 'e', 'l', 'l', 'o']
for [idx, val] in list->items()
  echo $'{idx}: {val}'
endfor
```

**Comment by brammool** [comment]
That is a valid request.  Let's see if it is easy to do.
