### ISSUE TITLE
Command output disappears when cmdheight=0

### ISSUE THREAD

**Issue by EgZvor** [vim/vim#11012]
### Steps to reproduce

```
vim --clean <file> -c 'set cmdheight=0'
```
```vim
:g/pattern
```

### Expected behaviour

The output of the command stays until hitting enter or maybe some other key.

### Version of Vim

9.0.325

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

**Comment by Shougo** [comment]
Hi, I have tested it but I cannot reproduce the behavior.
Please explain the problem clearly.

I think the screencast is needed.

**Comment by bfrg** [comment]
I think what @EgZvor is trying to say is that the output of `:g/pattern` is redirected to the message popup instead of Vim's internal pager when `cmdheight` is set to zero. As a result the output of `:g/pattern` disappears after three seconds. Besides that, the message popup cannot be scrolled, unlike the pager.

**Comment by brammool** [comment]
> I think what @EgZvor is trying to say is that the output of
> `:g/pattern` is redirected to the message popup instead of Vim's
> internal pager when `cmdheight` is set to zero. As a result the output
> of `:g/pattern` disappears after three seconds. Besides that, the
> message popup cannot be scrolled, unlike the pager.

I have been thinking of a way to make the message window stay up longer,
but can't think of what key to use for that.

Anyway, that doesn't solve the problem of paging through results, this
output should not go to the message window.

There are more commands where this applies, but not all.  For some it is
nice you don't have to type Enter before you can continue.  Might have
to decide for each command specifically...

-- 
Kiss me twice.  I'm schizophrenic.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bfrg** [comment]
I think this can be closed now since the feature has been removed.
