### ISSUE TITLE
[bisected] Vim enters infinite loop when displaying highlights with cmdheight=0

### ISSUE THREAD

**Issue by vimpostor** [vim/vim#11014]
### Steps to reproduce

```bash
src/vim --clean -Nu <(cat<<EOF
set cmdheight=0
au VimEnter * hi
EOF
)
```

### Expected behaviour

Vim shows highlights instead of becoming unresponsive.
Alternatively it shows nothing (if this functionality is unsupported with `cmdheight=0`), which is still better than becoming unresponsive.

### Version of Vim

9.0.0325

### Environment

Operating system: Arch Linux
Terminal: wezterm with $TERM=xterm-256color
Shell: zsh

**Comment by Shougo** [comment]
Reproduced.

**Comment by vimpostor** [comment]
I have bisected the bad commit to be 9198de3ae2bd20ac51d580c44f2b43c282c1e773, so it seems the introduction of the popup notification window is the culprit.
