### ISSUE TITLE
A potential bug of NPD

### ISSUE THREAD

**Issue by ash1852** [vim/vim#11020]
### Steps to reproduce

Hi, I found a potential null pointer dereference bug in the project source code of libsndfile, and I have shown the execution sequence of the program that may generate the bug on the graph below. The red text illustrates the steps that generate the bug, the red arrows represent the call relationships,the file path can be seen in the blue framed section.
![image](https://user-images.githubusercontent.com/87304478/187614062-b51203da-95cd-474f-b24e-4ae17a3c9ba6.png)

Although the code shown is for version 4.2.7 but this potential bug is still exist in the current version.
would you can help to check if this bug is true?thank you for your effort and patience!

### Expected behaviour

handle case when allocate failed.

### Version of Vim

8.1.2269

### Environment

OS: ubuntu20.04

**Comment by brammool** [comment]
Well, we could put the use of "gc" in an if statement:
  if (gc != NULL)
    {
	XDrawPoint(gui.dpy, blank_pixmap, gc, 0, 0);
	XFreeGC(gui.dpy, gc);
    }
Not sure if the rest of the code then won't have problems.  Do you know?

**Comment by ash1852** [comment]
> Well, we could put the use of "gc" in an if statement: if (gc != NULL) { XDrawPoint(gui.dpy, blank_pixmap, gc, 0, 0); XFreeGC(gui.dpy, gc); } Not sure if the rest of the code then won't have problems. Do you know?

As far as I know，there is no more derefer site other than these two call statements.
