### ISSUE TITLE
`wincmd =` to respect `eadirection`

### ISSUE THREAD

**Issue by noscript** [vim/vim#11021]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

Most of the time I would like to only equalize windows widths and keep the heights. `wincmd =` always equalizes everything. 

**Describe the solution you'd like**
`wincmd =` would take into account `eadirection`:
- if set to `hor`, then height of windows is not affected 
- if set to `ver`, then width of windows is not affected

**Describe alternatives you've considered**
Not easy but possible solution for locking the height (use `&winfixheight` for locking the widths):
1. Backup `&winfixwidth` for all windows.
2. Set `&winfixwidth` for all windows.
3. Do `wincmd =`.
4. Unset  `&winfixwidth` for all windows.
5. Restore `&winfixwidth` from backup.

**Comment by brammool** [comment]
> **Is your feature request about something that is currently impossible
> or hard to do? Please describe the problem.**
> 
> Most of the time I would like to only equalize windows widths and keep
> the heights. `wincmd =` always equalizes everything. 
> 
> **Describe the solution you'd like**
> `wincmd =` would take into account `eadirection`:
> - if set to `hor`, then height of windows is not affected 
> - if set to `ver`, then width of windows is not affected
> 
> **Describe alternatives you've considered**
> Not easy but possible solution for locking the height (use `&winfixheight` for locking the widths):
> 1. Backup `&winfixwidth` for all windows.
> 2. Set `&winfixwidth` for all windows.
> 3. Do `wincmd =`.
> 4. Unset  `&winfixwidth` for all windows.
> 5. Restore `&winfixwidth` from backup.

It is a valid request to only do equalization horizontally or
vertically.  But the proposed solution is not backwards compatible.
Also, there might be times you do want to equalize in the other
direction, then having to change the option is clumsy.

Adding new commands for this runs into the problem that most CTRL-W
combinations are already used.  I don't see two that are a good match.

How about:
	:vert wincmd =
	:lefta wincmd =

There currently is no :horizontal modifier.  We could add it, but then
we'll get questions what "horizontal vsplit" means...  Not sure if there
is any other good use of a horizontal modifier.


-- 
ARTHUR: Old woman!
DENNIS: Man!
ARTHUR: Man.  I'm sorry.  Old man, What knight live in that castle over there?
DENNIS: I'm thirty-seven.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by noscript** [comment]
>How about:
	:vert wincmd =
	:lefta wincmd =

This is even better and less cumbersome, no need to change `eadirection`.

>There currently is no :horizontal modifier. 

`lefta` vs `horizontal` is a hard question. If using `lefta` modifier, maybe `rightb` should be also supported.

**Comment by noscript** [comment]
This was implemented in 5d09a401e. Thank you!
