### ISSUE TITLE
incorrect cursor movements on lines with virtual text for automatic type inference

### ISSUE THREAD

**Issue by opcoder0** [vim/vim#11036]
### Steps to reproduce

On lines that has an identifier's type inferred (in my case for Rust) Vim shows the inferred type as virtual text.

On lines that have virtual text I cannot -

- hit `b` to move back one word from end of line. The cursor wraps back to the end of line.
- change word msg using `cw`; The cursor jumps to end of line.

![b-cw-commands](https://user-images.githubusercontent.com/110003254/188039327-2867bb47-7534-4897-a2df-5db72689497b.gif)

My .vimrc - [https://github.com/opcoder0/vimrc/blob/main/vimrc](https://github.com/opcoder0/vimrc/blob/main/vimrc)

### Expected behaviour

For the `b` command case - the cursor should move back one word at a time to the beginning of the line.
For the `cw` command case - the cursor should not jump to end of line. I must be able to change the word/variable.

### Version of Vim

9.0; Included patches 1-105

### Environment

OS Ubuntu 20.04
Terminal GNOME Terminal 3.36.2 using VTE 0.60.3 +BIDI +GNUTLS +ICU +SYSTEMD
Value of $TERM: screen
Value of $SHELL: /bin/bash

**Comment by lacygoill** [comment]
> 9.0; Included patches 1-105

The most recent patch is [9.0.0354](https://github.com/vim/vim/releases/tag/v9.0.0354); you're missing 249 patches.  Out of those, 29 deal with issues related to the virtual text feature:

   - [9.0.0116](https://github.com/vim/vim/releases/tag/v9.0.0116)  virtual text not displayed if 'signcolumn' is "yes"
   - [9.0.0121](https://github.com/vim/vim/releases/tag/v9.0.0121)  cannot put virtual text after or below a line
   - [9.0.0125](https://github.com/vim/vim/releases/tag/v9.0.0125)  cursor positioned wrong with virtual text after the line
   - [9.0.0130](https://github.com/vim/vim/releases/tag/v9.0.0130)  cursor position wrong when inserting around virtual text
   - [9.0.0131](https://github.com/vim/vim/releases/tag/v9.0.0131)  virtual text with Tab is not displayed correctly
   - [9.0.0132](https://github.com/vim/vim/releases/tag/v9.0.0132)  multi-byte characters in virtual text not handled correctly
   - [9.0.0133](https://github.com/vim/vim/releases/tag/v9.0.0133)  virtual text after line moves to joined line
   - [9.0.0139](https://github.com/vim/vim/releases/tag/v9.0.0139)  truncating virtual text after a line not implemented
   - [9.0.0142](https://github.com/vim/vim/releases/tag/v9.0.0142)  crash when adding and removing virtual text
   - [9.0.0143](https://github.com/vim/vim/releases/tag/v9.0.0143)  cursor positioned after virtual text in empty line
   - [9.0.0153](https://github.com/vim/vim/releases/tag/v9.0.0153)  no fold and sign column for virtual text with "below" align
   - [9.0.0168](https://github.com/vim/vim/releases/tag/v9.0.0168)  cursor positioned wrong with two virtual text properties
   - [9.0.0177](https://github.com/vim/vim/releases/tag/v9.0.0177)  cursor position wrong with 'virtualedit' and mouse click
   - [9.0.0178](https://github.com/vim/vim/releases/tag/v9.0.0178)  cursor position wrong with virtual text before Tab
   - [9.0.0179](https://github.com/vim/vim/releases/tag/v9.0.0179)  cursor pos wrong with wrapping virtual text in empty line
   - [9.0.0183](https://github.com/vim/vim/releases/tag/v9.0.0183)  extra space after virtual text when 'linebreak' is set
   - [9.0.0184](https://github.com/vim/vim/releases/tag/v9.0.0184)  virtual text prop highlight continues after truncation
   - [9.0.0185](https://github.com/vim/vim/releases/tag/v9.0.0185)  virtual text does not show if text prop at same position
   - [9.0.0186](https://github.com/vim/vim/releases/tag/v9.0.0186)  virtual text without highlighting does not show
   - [9.0.0193](https://github.com/vim/vim/releases/tag/v9.0.0193)  search and match highlight interfere with virtual text
   - [9.0.0199](https://github.com/vim/vim/releases/tag/v9.0.0199)  cursor position wrong with two right-aligned virtual texts
   - [9.0.0201](https://github.com/vim/vim/releases/tag/v9.0.0201)  CursorLine highlight overrules virtual text highlight
   - [9.0.0205](https://github.com/vim/vim/releases/tag/v9.0.0205)  cursor in wrong position when inserting after virtual text
   - [9.0.0208](https://github.com/vim/vim/releases/tag/v9.0.0208)  the override flag has no effect for virtual text
   - [9.0.0210](https://github.com/vim/vim/releases/tag/v9.0.0210)  'list' mode does not work properly with virtual text
   - [9.0.0214](https://github.com/vim/vim/releases/tag/v9.0.0214)  splitting a line may duplicate virtual text
   - [9.0.0247](https://github.com/vim/vim/releases/tag/v9.0.0247)  cannot add padding to virtual text without highlight
   - [9.0.0252](https://github.com/vim/vim/releases/tag/v9.0.0252)  cursor in wrong place after virtual text
   - [9.0.0297](https://github.com/vim/vim/releases/tag/v9.0.0297)  cursor position wrong after right aligned virtual text

Try to reproduce on master, and see whether one of them fixes your issue.

---

   > My .vimrc - https://github.com/opcoder0/vimrc/blob/main/vimrc

Remove as much code as possible (in particular remove all the plugins) to get a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example).

**Comment by opcoder0** [comment]
Thank you. I compiled `vim` on master and tested the same. The issue still persists. 

![vim9-354-b-cw](https://user-images.githubusercontent.com/110003254/188045974-78e79e5a-af3d-4ad7-959d-3e6586b675d0.gif)

I have not yet tried with the minimal reproducible example (without plugins). I suspect if I remove all the plugins the LSP that issues hints for automatic type inference will be absent and this error/case won't be relevant anymore.

```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Sep  2 2022 12:23:24)
Included patches: 1-354
Compiled by opcoder0@sd3vb0x
Huge version without GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
-balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term -gettext           +num64             +textobjects
-browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     -perl              +title
+channel           +ipv6              +persistent_undo   -toolbar
+cindent           +job               +popupwin          +user_commands
-clientserver      +jumplist          +postscript        +vartabs
-clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           -python            +viminfo
+cmdline_info      +libcall           +python3           +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
+cscope            +localmap          -ruby              +wildignore
+cursorbind        -lua               +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con        +mksession         +smartindent       +writebackup
+diff              +modify_fname      -sodium            -X11
+digraphs          +mouse             -sound             -xfontset
-dnd               -mouseshape        +spell             -xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        -mouse_gpm         +statusline        -xsmp
+eval              -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary        
-farsi             -mouse_sysmouse    -tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -g -O2 -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: gcc -L/usr/local/lib -Wl,--as-needed -o vim -lm -ltinfo -lrt -ldl -L/usr/lib/python3.8/config-3.8-x86_64-linux-gnu/ -lpython3.8 -lcrypt -lpthread -ldl -lutil -lm -lm 

```

**Comment by opcoder0** [comment]
Thank you. The issue is not reprodcible on the latest patch level (9.0; Included patches: 1-354) with my vimrc. The issue seemed to have been fixed.
