### ISSUE TITLE
invalid regex in YAML indent plugin

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#11034]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        var lines =<< trim END
            # vim: set ft=yaml sw=2 et :

            # START_INDENT
            map1:
            sub1:
            - list item
            map2:
            - another list
            # END_INDENT

            # START_INDENT
            map: &anchor
            map: val
            # END_INDENT

            # START_INDENT
            map: |
            line1
            line2
            # END_INDENT
        END
        lines->setline(1)
        filetype indent on
        &filetype = 'yaml'
        &debug = 'throw'
        normal! gg=G
    EOF
    )

An error is given:

    E678: Invalid character after %[dxouU]

**Expected behavior**

No error is given.

**Version of Vim**

9.0 Included patches: 1-353

**Environment**

Operating system: Ubuntu 20.04.5 LTS
Terminal: XTerm(353)
Value of $TERM: xterm-256color
Shell: GNU bash, version 5.0.17

**Additional context**

This patch should fix the issue:
```diff
diff --git a/runtime/indent/yaml.vim b/runtime/indent/yaml.vim
index d732c37c0..3ed48ffcd 100644
--- a/runtime/indent/yaml.vim
+++ b/runtime/indent/yaml.vim
@@ -54,7 +54,7 @@ let s:c_ns_anchor_name = s:c_ns_anchor_char .. '+'
 let s:c_ns_anchor_property =  '\v\&' .. s:c_ns_anchor_name
 
 let s:ns_word_char = '\v[[:alnum:]_\-]'
-let s:ns_tag_char  = '\v%(%\x\x|' .. s:ns_word_char .. '|[#/;?:@&=+$.~*''()])'
+let s:ns_tag_char  = '\v%(\x\x|' .. s:ns_word_char .. '|[#/;?:@&=+$.~*''()])'
 let s:c_named_tag_handle     = '\v\!' .. s:ns_word_char .. '+\!'
 let s:c_secondary_tag_handle = '\v\!\!'
 let s:c_primary_tag_handle   = '\v\!'
@@ -63,7 +63,7 @@ let s:c_tag_handle = '\v%(' .. s:c_named_tag_handle.
             \            '|' .. s:c_primary_tag_handle .. ')'
 let s:c_ns_shorthand_tag = '\v' .. s:c_tag_handle .. s:ns_tag_char .. '+'
 let s:c_non_specific_tag = '\v\!'
-let s:ns_uri_char  = '\v%(%\x\x|' .. s:ns_word_char .. '\v|[#/;?:@&=+$,.!~*''()[\]])'
+let s:ns_uri_char  = '\v%(\x\x|' .. s:ns_word_char .. '\v|[#/;?:@&=+$,.!~*''()[\]])'
 let s:c_verbatim_tag = '\v\!\<' .. s:ns_uri_char.. '+\>'
 let s:c_ns_tag_property = '\v' .. s:c_verbatim_tag.
             \               '\v|' .. s:c_ns_shorthand_tag.
```
I don't understand the regex, so I'm not sure it's correct.  However, `\v%\x` is not a valid pattern.  Removing the percent character seems to be the simplest fix, and it makes sense.  Also, the YAML indent tests still pass.

BTW, the tests don't give any error unless we set `'debug'` to `throw`.  I wonder whether that should be the default:
```diff
diff --git a/runtime/indent/testdir/runtest.vim b/runtime/indent/testdir/runtest.vim
index 6bbd33cac..06f948e3b 100644
--- a/runtime/indent/testdir/runtest.vim
+++ b/runtime/indent/testdir/runtest.vim
@@ -11,6 +11,7 @@ syn on
 set nowrapscan
 set report=9999
 set modeline
+set debug=throw
 
 au! SwapExists * call HandleSwapExists()
 func HandleSwapExists()
```
---

I open the issue here because [the maintainer doesn't seem to be active anymore](https://github.com/vim/vim/issues/10730#issuecomment-1194127479).

**Comment by brammool** [comment]
last change was made by @lukas-reineke   any comments?

**Comment by lukas-reineke** [comment]
This looks like the same issue I fixed in #5937 somehow it got reverted?
Patch LGTM

**Comment by brammool** [comment]
Thanks for checking, I'll include it.  I don't see the error when running the tests, even when setting the 'debug' option.

**Comment by lacygoill** [comment]
> I don't see the error when running the tests, even when setting the 'debug' option.

The tests pass no matter what, but at least an error is printed on the terminal:

    $ cd runtime/indent/
    $ make clean; make test
    rm -f testdir/*.fail testdir/*.out
    VIMRUNTIME=.. vim --clean --not-a-term -u testdir/runtest.vim
    ...
    "testdir/yaml.in" 20L, 202BError detected while processing /home/lgc/VCS/vim/runtime/indent/testdir/runtest.vim[88]..function GetYAMLIndent:
    line   71:
    "testdir/yaml.out" "testdir/yaml.out" [New] 20L, 214B written
    Test testdir/yaml.in OK

```diff
--- /tmp/without	2022-09-02 13:33:21.749974313 +0200
+++ /tmp/with	2022-09-02 13:33:03.222033503 +0200
@@ -19,5 +19,7 @@
 Test testdir/vim.in OK
 "testdir/xml.in" 32L, 437B"testdir/xml.out" "testdir/xml.out" [New] 32L, 709B written
 Test testdir/xml.in OK
-"testdir/yaml.in" 20L, 202B"testdir/yaml.out" "testdir/yaml.out" [New] 20L, 214B written
+"testdir/yaml.in" 20L, 202BError detected while processing /home/lgc/VCS/vim/runtime/indent/testdir/runtest.vim[88]..function GetYAMLIndent:
+line   71:
+"testdir/yaml.out" "testdir/yaml.out" [New] 20L, 214B written
 Test testdir/yaml.in OK
```

**Comment by brammool** [comment]
>    > I don't see the error when running the tests, even when setting the 'debug' option.
> 
> The tests pass no matter what, but at least an error is printed on the terminal:
> 
>     $ cd runtime/indent/
>     $ make clean; make test
>     rm -f testdir/*.fail testdir/*.out
>     VIMRUNTIME=.. vim --clean --not-a-term -u testdir/runtest.vim
>     ...
>     "testdir/yaml.in" 20L, 202BError detected while processing /home/lgc/VCS/vim/runtime/indent/testdir/runtest.vim[88]..function GetYAMLIndent:
>     line   71:
>     "testdir/yaml.out" "testdir/yaml.out" [New] 20L, 214B written
>     Test testdir/yaml.in OK
> 
> ```diff
> --- /tmp/without	2022-09-02 13:33:21.749974313 +0200
> +++ /tmp/with	2022-09-02 13:33:03.222033503 +0200
> @@ -19,5 +19,7 @@
>  Test testdir/vim.in OK
>  "testdir/xml.in" 32L, 437B"testdir/xml.out" "testdir/xml.out" [New] 32L, 709B written
>  Test testdir/xml.in OK
> -"testdir/yaml.in" 20L, 202B"testdir/yaml.out" "testdir/yaml.out" [New] 20L, 214B written
> +"testdir/yaml.in" 20L, 202BError detected while processing /home/lgc/VCS/vim/runtime/indent/testdir/runtest.vim[88]..function GetYAMLIndent:
> +line   71:
> +"testdir/yaml.out" "testdir/yaml.out" [New] 20L, 214B written
>  Test testdir/yaml.in OK
> ```

I'll put a try/catch around the indenting in the test script and add the
error to the file, so that it gets noticed.

-- 
The word "leader" is derived from the word "lead", as in the material that
bullets are made out of.  The term "leader" was popularized at about the same
time as the invention of firearms.  It grew out of the observation that the
person in charge of every organization was the person whom everyone wanted to
fill with hot lead.
   I don't recomment this; it's just a point of historical interest.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
