### ISSUE TITLE
cannot repeat mapping in operator-pending mode using `<ScriptCmd>`

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#11049]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        var vimdir = '/tmp/.vim'
        &runtimepath = vimdir
        vimdir->delete('rf')
        vimdir->mkdir('p')

        var lines =<< trim END
            vim9script
            import autoload 'script.vim'
            onoremap <F3> <ScriptCmd>script.Func()<CR>
        END
        $'{vimdir}/plugin/'->mkdir('p')
        lines->writefile($'{vimdir}/plugin/script.vim')

        lines =<< trim END
            vim9script
            export def Func()
                normal! dd
            enddef
        END
        $'{vimdir}/autoload/'->mkdir('p')
        lines->writefile($'{vimdir}/autoload/script.vim')

        ['foo', 'bar']->setline(1)
        nnoremap j j
        $'source {vimdir}/plugin/script.vim'->execute()
        feedkeys("d\<F3>j.", 'xt')
    EOF
    )

The line `foo` is deleted, then an error is given:

    E121: Undefined variable: script

**Expected behavior**

The lines `foo` and `bar` are deleted.  No error is given.

**Version of Vim**

9.0 Included patches: 1-369

**Environment**

Operating system: Ubuntu 20.04.5 LTS
Terminal: XTerm(353)
Value of $TERM: xterm-256color
Shell: GNU bash, version 5.0.17

**Additional context**

The issue disappears if we replace `<ScriptCmd>` with `<Cmd>`:

    # BAD
    onoremap <F3> <ScriptCmd>script.Func()<CR>

    # GOOD
    const Ref = script.Func
    onoremap <F3> <Cmd>call <SID>Ref()<CR>

Test:
```vim
vim9script
var vimdir = '/tmp/.vim'
&runtimepath = vimdir
vimdir->delete('rf')
vimdir->mkdir('p')

var lines =<< trim END
    vim9script
    import autoload 'script.vim'
    const Ref = script.Func
    onoremap <F3> <Cmd>call <SID>Ref()<CR>
END
$'{vimdir}/plugin/'->mkdir('p')
lines->writefile($'{vimdir}/plugin/script.vim')

lines =<< trim END
    vim9script
    export def Func()
        normal! dd
    enddef
END
$'{vimdir}/autoload/'->mkdir('p')
lines->writefile($'{vimdir}/autoload/script.vim')

['foo', 'bar']->setline(1)
nnoremap j j
$'source {vimdir}/plugin/script.vim'->execute()
feedkeys("d\<F3>j.", 'xt')
```
---

The issue disappears if we run the commands of the plugin right from the first sourced script.

Test:
```vim
vim9script
var vimdir = '/tmp/.vim'
&runtimepath = vimdir
vimdir->delete('rf')
vimdir->mkdir('p')

var lines =<< trim END
    vim9script
    export def Func()
        normal! dd
    enddef
END
$'{vimdir}/autoload/'->mkdir('p')
lines->writefile($'{vimdir}/autoload/script.vim')

['foo', 'bar']->setline(1)
nnoremap j j
import autoload 'script.vim'
onoremap <F3> <ScriptCmd>script.Func()<CR>
feedkeys("d\<F3>j.", 'xt')
```
---

The issue disappears if we don't use a mapping between the first execution of the normal command and its repetition with the dot command:

    # BAD
    feedkeys("d\<F3>j.", 'xt')

    # GOOD
    feedkeys("d\<F3>.", 'xt')

Test:
```vim
vim9script
var vimdir = '/tmp/.vim'
&runtimepath = vimdir
vimdir->delete('rf')
vimdir->mkdir('p')

var lines =<< trim END
    vim9script
    import autoload 'script.vim'
    onoremap <F3> <ScriptCmd>script.Func()<CR>
END
$'{vimdir}/plugin/'->mkdir('p')
lines->writefile($'{vimdir}/plugin/script.vim')

lines =<< trim END
    vim9script
    export def Func()
        normal! dd
    enddef
END
$'{vimdir}/autoload/'->mkdir('p')
lines->writefile($'{vimdir}/autoload/script.vim')

['foo', 'bar']->setline(1)
nnoremap j j
$'source {vimdir}/plugin/script.vim'->execute()
feedkeys("d\<F3>.", 'xt')
```

**Comment by brammool** [comment]
> **Steps to reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(tee <<'EOF'
>         vim9script
>         var vimdir = '/tmp/.vim'
>         &runtimepath = vimdir
>         vimdir->delete('rf')
>         vimdir->mkdir('p')
> 
>         var lines =<< trim eval END
>             vim9script
>             import autoload 'script.vim'
>             onoremap <F3> <ScriptCmd>script.Func()<CR>
>         END
>         $'{vimdir}/plugin/'->mkdir('p')
>         lines->writefile($'{vimdir}/plugin/script.vim')
> 
>         lines =<< trim END
>             vim9script
>             export def Func()
>                 normal! dd
>             enddef
>         END
>         $'{vimdir}/autoload/'->mkdir('p')
>         lines->writefile($'{vimdir}/autoload/script.vim')
> 
>         ['foo', 'bar']->setline(1)
>         nnoremap j j
>         $'source {vimdir}/plugin/script.vim'->execute()
>         feedkeys("d\<F3>j.", 'xt')
>     EOF
>     )
> 
> The line `foo` is deleted, then an error is given:
> 
>     E121: Undefined variable: script

I'm not sure what you are intending to do.  You have an onoremap, which
is supposed to be something that is valid in operator-pending mode.
That would be a movement command.  But it ends up deleting a line and I
don't see what the movement would be.  The following "j" perhaps?

Repeating with dot keeps record of the typed characters and executes
them again.  But the intermediate "dd" messes this up.


-- 
A consultant is a person who takes your money and annoys your employees while
tirelessly searching for the best way to extend the consulting contract.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> I'm not sure what you are intending to do.  You have an onoremap, which
   > is supposed to be something that is valid in operator-pending mode.
   > That would be a movement command.  But it ends up deleting a line and I
   > don't see what the movement would be.  The following "j" perhaps?

The original code selects a text-object; a comment, defined as the sequence of commented lines including the current line.  The issue can be reproduced by replacing `dd` with `V`:

    # BEFORE
    export def Func()
        normal! dd
    enddef

    # AFTER
    export def Func()
        normal! V
    enddef

Test:
```vim
vim9script
var vimdir = '/tmp/.vim'
&runtimepath = vimdir
vimdir->delete('rf')
vimdir->mkdir('p')

var lines =<< trim END
    vim9script
    import autoload 'script.vim'
    onoremap <F3> <ScriptCmd>script.Func()<CR>
END
$'{vimdir}/plugin/'->mkdir('p')
lines->writefile($'{vimdir}/plugin/script.vim')

lines =<< trim END
    vim9script
    export def Func()
        normal! V
    enddef
END
$'{vimdir}/autoload/'->mkdir('p')
lines->writefile($'{vimdir}/autoload/script.vim')

['foo', 'bar']->setline(1)
nnoremap j j
$'source {vimdir}/plugin/script.vim'->execute()
feedkeys("d\<F3>j.", 'xt')
```
    E121: Undefined variable: script

Is that better?

If not, I can try to reduce the issue one more time.  This bug breaks [this mapping](https://github.com/lacygoill/vim-comment/blob/7ca30dcae8e51eb3cf240fa8b105320e2b765f13/plugin/comment.vim#L24):

    onoremap <unique> ic <ScriptCmd>object.Main(v:operator == 'c')<CR>

I can delete a comment by pressing `dic`.  And I can delete another comment by pressing `.`.  But only if I don't use any mapping between `dic` and `.`.  I don't think the `object.Main()` function does anything weird.  I think [it just moves the cursor](https://github.com/lacygoill/vim-comment/blob/7ca30dcae8e51eb3cf240fa8b105320e2b765f13/autoload/comment/object.vim#L73):

    # position the cursor on the 1st line of the object
    execute 'normal! ' .. boundaries[0] .. 'G'

    # select the object
    execute 'normal! ' .. (mode() =~ "[vV\<C-V>]" ? 'o' : 'V') .. boundaries[1] .. 'G'

**Comment by lacygoill** [comment]
Actually, there is no need for `Func()` to execute anything.  Even when empty, an error is given.

**Comment by lacygoill** [comment]
> But only if I don't use any mapping between `dic` and `.`.

Which is to be expected if the mapping resets the last operation.  But in my case, the mapping does not do that; it just moves the cursor.  That should not reset `.`.  And even if it did:

   - why would it prevent Vim from finding the pseudo-variable `script`?
   - why only with `<ScriptCmd>`, but not with `<Cmd>`?
   - why only when the code is written in a plugin, but not in the vimrc?

**Comment by lacygoill** [comment]
The same bug breaks [these mappings](https://github.com/lacygoill/vim-column-object/blob/ca0c373d5f71d2fcfe7851a715fe10064bb13cc2/plugin/columnObject.vim#L13-L16):

    onoremap <unique> io <ScriptCmd>columnObject.Main('iw')<CR>
    onoremap <unique> iO <ScriptCmd>columnObject.Main('iW')<CR>
    onoremap <unique> ao <ScriptCmd>columnObject.Main('aw')<CR>
    onoremap <unique> aO <ScriptCmd>columnObject.Main('aW')<CR>

They don't do anything weird either.  [They just select a text-object](https://github.com/lacygoill/vim-column-object/blob/ca0c373d5f71d2fcfe7851a715fe10064bb13cc2/autoload/columnObject.vim#L99-L102):

    execute 'keepjumps normal! '
        .. top_line .. 'G' .. vcol1 .. '|'
        .. "\<C-V>"
        .. bottom_line .. 'G' .. vcol2 .. '|'

**Comment by brammool** [comment]
>    > I'm not sure what you are intending to do.  You have an onoremap, which
>    > is supposed to be something that is valid in operator-pending mode.
>    > That would be a movement command.  But it ends up deleting a line and I
>    > don't see what the movement would be.  The following "j" perhaps?
> 
> The original code selects a text-object; a comment, defined as the
> sequence of commented lines including the current line.  The issue can
> be reproduced by replacing `dd` with `V`:
> 
>     # BEFORE
>     export def Func()
>         normal! dd
>     enddef
> 
>     # AFTER
>     export def Func()
>         normal! V
>     enddef
> 
> Test:
> ```vim
> vim9script
> var vimdir = '/tmp/.vim'
> &runtimepath = vimdir
> vimdir->delete('rf')
> vimdir->mkdir('p')
> 
> var lines =<< trim END
>     vim9script
>     import autoload 'script.vim'
>     onoremap <F3> <ScriptCmd>script.Func()<CR>
> END
> $'{vimdir}/plugin/'->mkdir('p')
> lines->writefile($'{vimdir}/plugin/script.vim')
> 
> lines =<< trim END
>     vim9script
>     export def Func()
>         normal! V
>     enddef
> END
> $'{vimdir}/autoload/'->mkdir('p')
> lines->writefile($'{vimdir}/autoload/script.vim')
> 
> ['foo', 'bar']->setline(1)
> nnoremap j j
> $'source {vimdir}/plugin/script.vim'->execute()
> feedkeys("d\<F3>j.", 'xt')
> ```
>     E121: Undefined variable: script
> 
> Is that better?

Running this through a debugger I can see what happens.  The original
command is put in the redo buffer as "d<ScriptCmd>script.Func()\n".
Now "script" can be found the first time, because expanding <F3> has set
the "last_used_map" variable, and <ScriptCmd> uses that to set the
context and it can find "script".

When repeating, after the "j" has been mapped, the "last_used_map"
variable has been reset and "script" cannot be found.

I suppose we need to put the information about the used mapping in the
redo buffer.

-- 
hundred-and-one symptoms of being an internet addict:
6. You refuse to go to a vacation spot with no electricity and no phone lines.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
