### ISSUE TITLE
Vim9: Error when using an imported function in a lambda

### ISSUE THREAD

**Issue by Raimondi** [vim/vim#11042]
### Steps to reproduce

1. Create these two files:

autoload/a.vim

    vim9script
    export def F(e: any): any
      return e
    enddef

autoload/b.vim

    vim9script
    import './a.vim'
    export def Lambda(): void
      var F = (x) => x->a.F()
    enddef

2. Run `:call b#Lambda()`

### Expected behaviour

No errors are expected.

### Version of Vim

9.0.362

### Environment

OS: macOS 12.5.1
Terminal: iTerm2 3.4.16
TERM: tmux-256color
Shell: fish

### Logs and stack traces

```shell
Error detected while compiling function b#Lambda:
line    1:
E1085: Not a callable type: a.F
Press ENTER or type command to continue
```

**Comment by bfrg** [comment]
If you call the imported function `a.F()` without the method-call syntax, it works:

autoload/b.vim:
```vim
vim9script

import './a.vim'

export def Lambda()
  var F = (x) => a.F(x)
enddef
```

**Comment by bfrg** [comment]
I don't think this has anything to do with imported functions, the method-call syntax just isn't supported yet.

For example, the following doesn't work either:
```vim
vim9script

const math: dict<func> = {
    Sin: function('sin')
}

def Test()
    var F = (x: any) => x->math.Sin()
enddef

Test()
```

Result:
```
Error detected while compiling /tmp/test.vim[11]..function <SNR>151_Test:
line    1:
E1085: Not a callable type: math.Sin
```

Removing the method-call syntax in the lambda will make it work:
```vim
vim9script

const math: dict<func> = {
    Sin: function('sin')
}

def Test()
    var F = (x: any) => math.Sin(x)
enddef

Test()
```
