### ISSUE TITLE
A part of `:h function()` does not work

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#11052]
In `:h function()`:
```
<		The Dictionary is only useful when calling a "dict" function.
		In that case the {dict} is passed in as "self". Example: >
			function Callback() dict
			   echo "called for " .. self.name
			endfunction
			...
			let context = {"name": "example"}
			let Func = function('Callback', context)
			...
			call Func()	" will echo: called for example
<		The use of function() is not needed when there are no extra
		arguments, these two are equivalent: >
			let Func = function('Callback', context)
			let Func = context.Callback
```

However, this gives an error `E716: Key not present in Dictionary: "Callback"`:
```vim
func Callback() dict
  echo 'called for ' .. self.name
endfunc

let context = {'name': 'example'}
let Func = context.Callback
```

The `call context.Callback('one', 500)` below also does not work.

**Comment by matveyt** [comment]
Actually, it does work for `let Func = function('Callback', [], context)`

So the question is if it's Vim bug or example bug?

**Comment by zeertzjq** [comment]
I guess the example needs to mention that the `Callback` needs to be a mention of `context` dictionary for `context.Callback` to work. Not sure how to change the wording.

**Comment by brammool** [comment]
> In `:h function()`:
> ```
> <		The Dictionary is only useful when calling a "dict" function.
> 		In that case the {dict} is passed in as "self". Example: >
> 			function Callback() dict
> 			   echo "called for " .. self.name
> 			endfunction
> 			...
> 			let context = {"name": "example"}
> 			let Func = function('Callback', context)
> 			...
> 			call Func()	" will echo: called for example
> <		The use of function() is not needed when there are no extra
> 		arguments, these two are equivalent: >
> 			let Func = function('Callback', context)
> 			let Func = context.Callback
> ```
> 
> However, this gives an error `E716: Key not present in Dictionary:
> "Callback"`:
> ```vim
> func Callback() dict
>   echo 'called for ' .. self.name
> endfunc
> 
> let context = {'name': 'example'}
> let Func = context.Callback
> ```
> 
> The `call context.Callback('one', 500)` below also does not work.

Yeah, as it's written it looks like the two examples are tightly
related, but the second part requires declaring the function in the
dictionary.  I think we can fix it by actually doing that, even though
it's not needed for the first one:

		The Dictionary is only useful when calling a "dict" function.
		In that case the {dict} is passed in as "self". Example: >
			let context = {"name": "example"}
			function context.Callback() dict
			   echo "called for " .. self.name
			endfunction
			"...
			let Func = function('Callback', context)
			"...
			call Func()	" will echo: called for example

Or does that suggest that defining the function on the dictionary is
required?  that might be confusing.  Perhaps adjusting the comment above
the second part is clearer:

		The use of function() is not needed when there are no extra
		arguments, these two are equivalent, if Callback() is defined
		as context.Callback(): >
			let Func = function('Callback', context)
			let Func = context.Callback


-- 
Q:  What's a light-year?
A:  One-third less calories than a regular year.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by zeertzjq** [comment]
It seems the first one only works if `Callback` is a global function, and the second one only works if `Callback` is define in `dict`.
