### ISSUE TITLE
No "resize increment" in WM_NORMAL_HINTS(WM_SIZE_HINTS) vim 8.2, 9.0

### ISSUE THREAD

**Issue by mmhere** [vim/vim#11055]
### Steps to reproduce

run gvim 8.2 on Linux Mint 21 or Ubunutu 2022.4 as provided in repositories
xprop against the gvim window.
WM_NORMAL_HINTS(WM_SIZE_HINTS):
section does *not* show "resize increment" based on font cell size
presumably this is GTK3 based
9.0 from PPA (see below) has the same problem

### Expected behaviour

resize hints for resize increment constrained by font cell size should be provided.
Instead, window manager is allowed to resize one pixel at a time, which results in the status line (and other things) having unused/empty pixels making for a fat pixel wasting appearance.

### Version of Vim

8,2 from repos;  9.0 from deb http://ppa.launchpad.net/jonathonf/vim/ubuntu jammy main

### Environment

Linux Mint 21, Ubunutu 2022.4
gvim -- not terminal

note that an older gvim (7.4 on Ubunutu 18.04, also Ubuntu 16.04) behaves properly

window manager happens to be MATE marco, but others show the same problem.

I suspect GTK3 shenanigans?  There's no GTK2 on latest versions of those distros, sadly and apparently.

### Logs and stack traces

```shell
no errors reported.  just behaves badly in the window manager
```
xprop for 9.0 running on Linux Mint 21 shows the following info.  Note the `HINTS` sections.  Compare to same info [following] for older gvim
```
_NET_WM_ICON_GEOMETRY(CARDINAL) = 424, 1103, 188, 24
XKLAVIER_STATE(INTEGER) = 0, 643078912
_NET_WM_STATE(ATOM) = 
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_FRAME_EXTENTS(CARDINAL) = 4, 2, 19, 4
_NET_WM_DESKTOP(CARDINAL) = 7
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_SHADE, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW
_NET_WM_VISIBLE_ICON_NAME(UTF8_STRING) = "t (/rd/tmp) - GVIM1 (on minkie)"
_NET_WM_VISIBLE_NAME(UTF8_STRING) = "t (/rd/tmp) - GVIM1 (on minkie)"
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		bitmap id # to use for icon: 0x5c00007
		bitmap id # of mask for icon: 0x5c0000f
		window id # of group leader: 0x5c00001
_GTK_THEME_VARIANT(UTF8_STRING) = 
Vim(STRING) = "9.0"

XdndAware(ATOM) = BITMAP
_NET_WM_OPAQUE_REGION(CARDINAL) = 0, 0, 634, 755
WM_WINDOW_ROLE(STRING) = "vim-41398-1149367634-1662303194"
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 96468997, 96468998
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x5c00004
WM_CLIENT_LEADER(WINDOW): window id # 0x5c00001
_NET_WM_PID(CARDINAL) = 41398
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "minkie"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 76 by 35
		program specified base size: 76 by 35
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST, WM_SAVE_YOURSELF
WM_CLASS(STRING) = "gvim", "Gvim"
WM_ICON_NAME(STRING) = "t (/rd/tmp) - GVIM1"
_NET_WM_ICON_NAME(UTF8_STRING) = "t (/rd/tmp) - GVIM1"
WM_NAME(STRING) = "t (/rd/tmp) - GVIM1"
_NET_WM_NAME(UTF8_STRING) = "t (/rd/tmp) - GVIM1"
```

Here is xprop output for a gvim 7.4 window, same whether running on Ubuntu 16.04 or Ubuntu 18.04.  Note the WM_NORMAL_HINTs section shows: `program specified resize increment: 6 by 13`.

```
_NET_WM_ICON_GEOMETRY(CARDINAL) = 611, 1079, 188, 24
XKLAVIER_STATE(INTEGER) = 0, 643078912
_NET_WM_STATE(ATOM) = 
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_FRAME_EXTENTS(CARDINAL) = 4, 2, 19, 4
_NET_WM_DESKTOP(CARDINAL) = 7
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_SHADE, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		bitmap id # to use for icon: 0x6c00021
		bitmap id # of mask for icon: 0x6c00024
		window id # of group leader: 0x6c00001
XdndAware(ATOM) = BITMAP
_MOTIF_DRAG_RECEIVER_INFO(_MOTIF_DRAG_RECEIVER_INFO) = 0x6c, 0x0, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x10, 0x0, 0x0, 0x0
_TOPMENU_WINDOW(WINDOW): window id # 0x6c00026
Vim(STRING) = "7.4"

WM_WINDOW_ROLE(STRING) = "vim-22064-565118840-1662303207"
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 113246213
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x6c00004
WM_CLIENT_LEADER(WINDOW): window id # 0x6c00001
_NET_WM_PID(CARDINAL) = 22064
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "fiddy"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 76 by 31
		program specified resize increment: 6 by 13
		program specified base size: 4 by 5
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "gvim", "Gvim"
WM_ICON_NAME(STRING) = "t (/rd/tmp) - GVIM3"
_NET_WM_ICON_NAME(UTF8_STRING) = "t (/rd/tmp) - GVIM3"
WM_NAME(STRING) = "t (/rd/tmp) - GVIM3"
_NET_WM_NAME(UTF8_STRING) = "t (/rd/tmp) - GVIM3"
```

Changing the font to other fixed width fonts/sizes for vim 8.2 or vim 9.0 does not help anything.  The errant window pixel-by-pixel resize behaviour is allowed.

Note that on the newer distros (21, 2022.4), things like gnome-terminal and mate-terminal get the "resize increment" hints correct, and resize in font-cell-grid sized jumps as expected for a text program using fixed with fonts.

**Comment by chrisbra** [comment]
so any idea how to provide those hints?

**Comment by mmhere** [comment]
Yeah, that's my question.  How to hint.  Older vims did it fine.  There is xlib documentation on how to set them but I've never entered into the world of vim source code.  Maybe something got dropped.  I think GTK3 changes things [and has caused numerous problems for me] in terms of what APIs are supposed to be used.

**Comment by mmhere** [comment]
Note, my initial posting (logged output from xprop) had the wrong copy/paste for the two versions but is now edited/fixed.

**Comment by mmhere** [comment]
This reference keeps popping up in searches:
https://tronche.com/gui/x/xlib/ICC/client-to-window-manager/wm-normal-hints.html

**Comment by mmhere** [comment]
man, these GTK people.  This does not look encouraging:
https://docs.gtk.org/gtk3/method.Window.resize_to_geometry.html

`resize_to_geometry()` Like `gtk_window_resize()`, but width and height are interpreted in terms of the base size and increment set with `gtk_window_set_geometry_hints()`.

"Deprecated since 3.20.  This function does nothing.  Use `gtk_window_resize()` and compute the geometry yourself."  Well,  thanks.

**Comment by mmhere** [comment]
https://docs.gtk.org/gdk3/struct.Geometry.html
Perhaps that API documentation is what is necessary to set the appropriate hints, assuming gvim is using GTK3, and versions later than 3.0 described at that URL haven't deprecated useful behavior, a thing GTK continually seems to do.

**Comment by brammool** [comment]
In src/gui_gtk_x11.c there is the update_window_manager_hints()
function.  Is that not working or missing something?

-- 
If someone questions your market projections, simply point out that your
target market is "People who are nuts" and "People who will buy any damn
thing".  Nobody is going to tell you there aren't enough of those people
to go around.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mmhere** [comment]
The evidence implies something isn't working.  I do suspect this is GTK3 based, because wasn't vim 7.4 using earlier versions of GTK?  Again, gvim 8.2 and gvim 9.0 on Linux Mint 21 (also Ubuntu 2022.4) show the issue.  As I understand it, GTK3 is the only game in town for present day Ubuntu [and derivatives like Mint 21).

I started to wonder if gtk rc files could be used to coerce this "from the outside" but that investigation leads to a maze of twisty passages, all alike.

**Comment by mmhere** [comment]
That function `update_window_manager_hints()` looks reasonable upon cursory inspection, but I'm no vim source expert, and certainly dunno whether it is doing what https://docs.gtk.org/gdk3/struct.Geometry.html expects, or whether this particular API is even still valid/supported in latest GTKs.  That URL refers to APi version 3.0, so maybe later API versions have broken it?

**Comment by mmhere** [comment]
Apparently this Linux Mint 21 system has gtk 3.24.xx if these are relevant and can be believed:
```
$ gtk-launch --version
3.24.33
pkg-config --modversion gtk+-3.0
3.24.3
```

Not sure those are the  best way to check GTK version, but it's what a brief search revealed.

Perhaps this output would also prove useful.
```
head -99 /etc/issue*;spanner; echo "lsb_release -a"; lsb_release -a;spanner;echo "uname -a"; uname -a;spanner;echo "/etc/debian_version"; cat /etc/debian_version;spanner;echo "/etc/os-release"; cat /etc/os-release 
==> /etc/issue <==
Linux Mint 21 Vanessa \n \l


==> /etc/issue.net <==
Linux Mint 21 Vanessa
=========================================================================================================
lsb_release -a
No LSB modules are available.
Distributor ID: Linuxmint
Description:    Linux Mint 21
Release:        21
Codename:       vanessa
=========================================================================================================
uname -a
Linux minkie 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
=========================================================================================================
/etc/debian_version
bookworm/sid
=========================================================================================================
/etc/os-release
NAME="Linux Mint"
VERSION="21 (Vanessa)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21"
VERSION_ID="21"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=vanessa
UBUNTU_CODENAME=jammy
```

**Comment by chrisbra** [comment]
can you build a gtk 2 build and check if this is any different there?

**Comment by mmhere** [comment]
Are we sure that  in the vim function, it is getting the character cell sizes correct?  Maybe they erroneously end up as zero or something.  If I had a debug build that spewed to stdout or stderr while running gvim I'd be happy to test it.

**Comment by brammool** [comment]
> The evidence implies something isn't working.  I do suspect this is
> GTK3 based, because wasn't vim 7.4 using earlier versions of GTK?
> Again, gvim 8.2 and gvim 9.0 on Linux Mint 21 (also Ubuntu 2022.4)
> show the issue.  As I understand it, GTK3 is the only game in town for
> present day Ubuntu [and derivatives like Mint 21).
> 
> I started to wonder if gtk rc files could be used to coerce this "from
> the outside" but that investigation leads to a maze of twisty
> passages, all alike.

I can build with GTK 2 on Ubuntu 22.04.  Just need to install the gtk 2
dev packages.

I'm not going to try fix this myself, I hope someone who knows about
this API can have a look.

-- 
Never enter the boss's office unless it's absolutely necessary.  Every boss
saves one corner of the desk for useless assignments that are doled out like
Halloween candy to each visitor.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by kstauffer** [comment]
Changing the second argument to `gtk_window_set_geometry_hints` to `NULL` fixes the issue. Which is totally weird, because the documentation for that function says (https://docs.gtk.org/gtk3/method.Window.set_geometry_hints.html):
> Since 3.20 this argument is ignored and GTK behaves as if NULL was set.
The part about "behaves as if NULL was set" is not true, since using an explicit NULL produces different behavior.
