### ISSUE TITLE
Different behavior of key mapping with CTRL between vim.exe and gvim.exe

### ISSUE THREAD

**Issue by mattn** [vim/vim#11057]
### Steps to reproduce

1. start gvim.exe
2. `imap <C-D>t bbb`
3. type `<C-D>` and wait

On vim.exe, any characters are not typed but on gvim.exe, it leave `D` on the buffer.

### Expected behaviour

The character `D` should not be displayed.

### Version of Vim

9.0.356

### Environment

Windows 64bit.

**Comment by k-takata** [comment]
https://github.com/vim/vim/commit/77fc0b02e53bdc49213900e0055cb6d678ce180d
Cc: @LemonBoy

**Comment by zeertzjq** [comment]
This is also reproducible on Linux, and this change seems to fix this on Linux:
```diff
diff --git a/src/getchar.c b/src/getchar.c
index fee9191ba..6632ad965 100644
--- a/src/getchar.c
+++ b/src/getchar.c
@@ -2356,7 +2356,11 @@ check_simplify_modifier(int max_offset)
 	if (offset + 3 >= typebuf.tb_len)
 	    break;
 	tp = typebuf.tb_buf + typebuf.tb_off + offset;
-	if (tp[0] == K_SPECIAL && tp[1] == KS_MODIFIER)
+	if ((tp[0] == K_SPECIAL
+#ifdef FEAT_GUI
+		|| tp[0] == CSI
+#endif
+	    ) && tp[1] == KS_MODIFIER)
 	{
 	    // A modifier was not used for a mapping, apply it to ASCII keys.
 	    // Shift would already have been applied.
```

**Comment by brammool** [comment]
> This is also reproducible on Linux, and this change seems to fix this
> on Linux:
> ```diff
> diff --git a/src/getchar.c b/src/getchar.c
> index fee9191ba..6632ad965 100644
> --- a/src/getchar.c
> +++ b/src/getchar.c
> @@ -2356,7 +2356,11 @@ check_simplify_modifier(int max_offset)
>  	if (offset + 3 >= typebuf.tb_len)
>  	    break;
>  	tp = typebuf.tb_buf + typebuf.tb_off + offset;
> -	if (tp[0] == K_SPECIAL && tp[1] == KS_MODIFIER)
> +	if ((tp[0] == K_SPECIAL
> +#ifdef FEAT_GUI
> +		|| tp[0] == CSI
> +#endif
> +	    ) && tp[1] == KS_MODIFIER)
>  	{
>  	    // A modifier was not used for a mapping, apply it to ASCII keys.
>  	    // Shift would already have been applied.
> ```

Thanks for the fix, I'll include it.  I'm not sure how to write a test
for this, I'll leave that to someone else.

-- 
hundred-and-one symptoms of being an internet addict:
1. You actually wore a blue ribbon to protest the Communications Decency Act.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
