### ISSUE TITLE
Add Jsonnet support

### ISSUE THREAD

**Issue by nawordar** [vim/vim#11073]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
Jsonnet files are currently not recognized and require an extension: [google/vim-jsonnet](https://github.com/google/vim-jsonnet).

**Describe the solution you'd like**
Add Jsonnet support based on the Google plugin in Vim.

I may take a stab at it later, but I worry about license and proper crediting. There is more than one author and the plugin is distributed under the Apache license. I'm not sure how I should apply the license requirements here.

**Comment by clason** [comment]
The filetype detection is so trivial, it requires neither license nor crediting. Just open a PR adding the extensions to `runtime/filetype.vim` and `src/testdir/test_filetype.vim`.

**Comment by clason** [comment]
(The syntax and ftplugin files are a different matter; if you want these added to Vim's runtime files, you should open an issue at the vim-json repo asking for permission.)

**Comment by maxbrunet** [comment]
FYI I have opened PR #11412 for a correction: `s/libjsonnet/libsonnet/` :)
