### ISSUE TITLE
Vim Non Responsive after Ctrl+s key press

### ISSUE THREAD

**Issue by rahuliiitd** [vim/vim#1107]
Vim (version 7.4) becomes non responsive after pressing 'Ctrl+s'. I have found this to happen in the Insert mode and even when no mode is selected.
I use Vim on Ubuntu 16.04.

**Comment by chrisbra** [comment]
in the terminal, this is a special key-code that does not even get send to vim. This is not a vim issue. For an explanation see e.g. [here](http://unix.stackexchange.com/q/12107) For user questions, don't use this issue tracker please. Use the existing vim-use mailinglist or e.g. stackexchange.
