### ISSUE TITLE
Background colour slightly off

### ISSUE THREAD

**Issue by WhyNotHugo** [vim/vim#1108]
If I run `set -g status-bg "#282828"`, capture a screenshot of that, and colour-pick the status bar colour, it's `#262626`. I noticed this mostly because my actual terminal bg is `#282828`.

I'm running urxvt, inside i3wm. No transparency or fancy stuff involved here.

**Comment by nuko8** [comment]
> set -g status-bg "#282828"

It looks to me that this is something can be seen `~/.tmux.conf`.   Could you clarify how this is relevant to vim?

**Comment by WhyNotHugo** [comment]
Apologies, I didn't get any sleep and this resulted in me reporting the issue in the wrong place.

Sorry about this! 😅
