### ISSUE TITLE
Vim renders characters that are not actually there

### ISSUE THREAD

**Issue by GoodBoyNeon** [vim/vim#11098]
### Steps to reproduce

I just get the error while coding some stuff.

### Expected behaviour

I expect NOT to see the bracket there as it's not typed there. Just a rendering issue
![image](https://user-images.githubusercontent.com/93624576/189399490-564b3c33-ff18-48df-b419-4576e47ce947.png)

### Version of Vim

9.0.47

### Environment

Operating System: Windows 10 x86
Terminal: Windows Terminal (latest version)
value of $TERM: None
shell: Powershell

**Comment by lacygoill** [comment]
> I just get the error while coding some stuff.

Here is a word you might have missed on the previous line:

   > Steps to **reproduce**

"Coding some stuff" does not give enough info for other people to reproduce.

---

   > 9.0.47

At the time of writing, [9.0.0429](https://github.com/vim/vim/releases/tag/v9.0.0429) is the latest patch.  You're missing 382 patches.  Try to update your Vim binary to see whether one of those fixes your issue.

**Comment by lacygoill** [comment]
Any update?

**Comment by brammool** [comment]
It looks like something that a plugin adds.  I can't think of any way Vim would do this.
Try disabling plugins.
