### ISSUE TITLE
Should bugs be reported on github or mailin list (documentation)

### ISSUE THREAD

**Issue by aparaatti** [vim/vim#1110]
`:help bugs`

Send bug reports to: Vim Developers vim-dev@vim.org
This is a maillist, you need to become a member first and many people will see
the message. If you don't want that, e.g. because it is a security issue,
send it to bugs@vim.org, this only goes to the Vim maintainer (that's Bram).

but:

[Reporting issues](https://github.com/vim/vim/blob/master/CONTRIBUTING.md#reporting-issues)

We use GitHub issues, but that is not a requirement. Writing to the Vim maillist is also fine.

**Comment by chrisbra** [comment]
you can use either one. Note, please ask questions on the appropriate forums, not here.

**Comment by aparaatti** [comment]
I titled it bad, just the point, that documentation is not inline or up to date(?) with github contributing.md. The github text seems to imply that GitHub issues would be a better place ("not required") to report them. Just a small thing anyways. "Feel free to report even the smallest problem, also typos in the documentation."
