### ISSUE TITLE
cannot read function argument in debug mode after using command-line mode mapping

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#11118]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        cnoremap <expr> <C-H> CH()
        def CH(): string
            return "\<C-H>"
        enddef
        def Func(n: number)
            eval 0 + 0
        enddef
        debug Func(123)
    EOF
    )

At the debug prompt:

   - execute `>s` to step into `Func()`
   - press `<C-H>` (this adds one frame for `CH()` at the top of the call stacktrace)
   - execute `>f` to pop the `CH()` frame out of the callstack
   - execute `>echo n` to ask for the value of `n`

An error is given:

    E121: Undefined variable: n

**Expected behavior**

No error is given.  `123` is echo'ed.  Because `n` *is* defined inside `Func()` (it's one of its arguments).

**Version of Vim**

9.0 Included patches: 1-453

**Environment**

Operating system: Ubuntu 20.04.5 LTS
Terminal: XTerm(353)
Value of $TERM: xterm-256color
Shell: GNU bash, version 5.0.17

**Additional context**

If we don't press `<C-H>`, the issue disappears.  That should not matter if we execute `>f` or `>n` to pop the added frame out of the callstack.

---

Related issue: https://github.com/vim/vim/issues/9612

**Comment by lacygoill** [comment]
> press &lt;C-H> (**this adds one frame for CH() at the top of the call stacktrace**)

I guess it makes sense, but it's still very annoying; that's never what I want nor what I expect.

**Comment by brammool** [comment]
>    > press &lt;C-H> (**this adds one frame for CH() at the top of the call stacktrace**)
> 
> I guess it makes sense, but it's still very annoying; that's never
> what I want nor what I expect.

You mean that a function call invoked from the prompt should not be
debugged?  Typing "CH()" by itself doesn't do this.

Looks like the debug level is reset when executing a command, but not
when entering a command.  I see no reason for that.  I'll make a patch.

-- 
"I simultaneously try to keep my head in the clouds and my feet on the
ground.  Sometimes it's a stretch, though."              -- Larry Wall

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
