### ISSUE TITLE
With 'nosplitscroll', 'scroll' may unexpectedly changed

### ISSUE THREAD

**Issue by k-takata** [vim/vim#11119]
### Steps to reproduce

1. `vim --clean -c "set nosplitscroll"
2. `:set scroll?`
  The shown value will be nearly half of the 'line' option.
3. `:sp`
4. `:set scroll?`
  `0` is shown. (unexpected)
5. `:help`
6. `:set scroll?`
  `1` is shown. (unexpected)

### Expected behaviour

The value of 'scroll' should be nearly half of the current window height.

### Version of Vim

9.0.0453

### Environment

Windows 10 GUI, Cygwin Terminal

**Comment by brammool** [comment]
@luukvbaal

**Comment by chrisbra** [comment]
apparently fixed by https://github.com/vim/vim/commit/470a14140bc06f1653edf26ab0b3c9b801080353
