### ISSUE TITLE
'status line' and 'command line' share the same area at startup

### ISSUE THREAD

**Issue by xvim64** [vim/vim#11125]
### Steps to reproduce

1. gvim.exe -u mini.vim
2. maximize gvim

mini.vim
```
set laststatus=2
set gfn=Consolas:h50
```

![1](https://user-images.githubusercontent.com/83569599/190030024-0ddbc015-9de7-4b2f-8064-67f1e9aa9cd0.jpg)
![2-comment](https://user-images.githubusercontent.com/83569599/190044793-60b442e2-168e-4cf8-8531-fdea742b06f2.jpg)

I think this has something to do with https://github.com/vim/vim/issues/11123  // E341: Internal error: lalloc(0, )

### Expected behaviour

'status line' and 'command line' do not share the same area at startup

### Version of Vim

9.0.0459

### Environment

Windows 10 64bit
gvim 9.0.0459

**Comment by luukvbaal** [comment]
Yes, same issue. Should be fixed by https://github.com/vim/vim/issues/11125.

**Comment by brammool** [comment]
#11125 is an issue, not a PR.  Hmm, patch 9.0.0461 is missing the github reference.

**Comment by brammool** [comment]
Should be #11122 I suppose

**Comment by luukvbaal** [comment]
Indeed, whoops.

**Comment by brammool** [comment]
So, this issue can be closed?

**Comment by luukvbaal** [comment]
I think so, yes. As well as https://github.com/vim/vim/issues/11123 and https://github.com/vim/vim/issues/11119. Can no longer reproduce with https://github.com/vim/vim/commit/470a14140bc06f1653edf26ab0b3c9b801080353.

**Comment by chrisbra** [comment]
so closing
