### ISSUE TITLE
documentation of the visual block put command does not correspond to its behaviour

### ISSUE THREAD

**Issue by MR0205** [vim/vim#11121]
### Steps to reproduce

According to the documentation in change.txt lines 1182-1185:

When you use a blockwise Visual mode command and yank only a single line into
a register, a paste on a visual selected area will paste that single line on
each of the selected lines (thus replacing the blockwise selected region by a
block of the pasted line).

BUG: Though the observed behaviour differs from the documented.

Steps to reproduce the bug are:
1) type text into a buffer:
aaaa
aaaa
aaaa
aaaa
1111

2) visual block select the last line and yank it into a unnamed register with CTRL-V and yank command
3) put the cursor on the first character of the first line and visual block select the first characters of the 4 first lines
4) issue a put command with "p"

5) observe the result:
1111aaa
aaa
aaa
aaa
1111

### Expected behaviour

Expected result:
1111aaa
1111aaa
1111aaa
1111aaa
1111

### Version of Vim

9.0.0453

### Environment

gvim on Windows 10 64bit

**Comment by brammool** [comment]
That text is misleading.  The register should be characterwise and containing only one line, the Visual selection should be blockwise, the put will repeat the register contents in every line.  An example helps to make this clear:
```
When a register contains text from one line (characterwise), using a
blockwise Visual selection, putting that register will paste that text
repeatedly in each of the selected lines, thus replacing the blockwise
selected region by multiple copies of the register text.  For example:
	- yank the word "TEXT" into a register with `yw`
	- select a visual block, marked with "v" in this text:
	    aaavvaaa
	    bbbvvbbb
	    cccvvccc
	- press `p`, results in:
	    aaaTEXTaaa
	    bbbTEXTbbb
	    cccTEXTccc
```

**Comment by MR0205** [comment]
I am sorry to ask for more attention, but I a newbiee with open source projects, is these types of bugs are not welcomed to be reported?

I thought the usual process even for a small bug like a documentation bug would be to fix it?

Again didn't mean to take much time.
Cheers.

**Comment by lacygoill** [comment]
> is these types of bugs are not welcomed to be reported?

Don't worry, it's a valid bug report.

   > I thought the usual process even for a small bug like a documentation bug would be to fix it?

The help seems indeed misleading.  I guess the previously posted example will be included in the next update of the runtime files.  When that happens, I'll let you know.

Note that when a fix for an issue in the runtime files is found, the issue is [usually closed immediately](https://github.com/vim/vim/issues/10942#issuecomment-1227366454).  That doesn't mean that the report was invalid.

   > Again didn't mean to take much time.

No time was wasted.  The report was rather short, to the point, and followed the provided template.  All is good.

**Comment by brammool** [comment]
> I am sorry to ask for more attention, but I a newbiee with open source
> projects, is these types of bugs are not welcomed to be reported?
> 
> I thought the usual process even for a small bug like a documentation
> bug would be to fix it?
> 
> Again didn't mean to take much time.

Bug reports of any kind are always welcome.  Only when it's a usage
issue you might want to find another place first.  Often it is not a bug
or documentation issue but something the user did wrong.

There is no need to create an issue for everything, a message on the
vim-dev maillist should also work.

-- 
hundred-and-one symptoms of being an internet addict:
66. You create a homepage with the impression to cure the afflicted...but
    your hidden agenda is to receive more e-mail.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> When that happens, I'll let you know.

The help was fixed in the [last update of the runtime files](https://github.com/vim/vim/commit/9712ff1288f942736ed76c0dec014909f067eec9):

                                                            *blockwise-put*
    When a register contains text from one line (characterwise), using a
    blockwise Visual selection, putting that register will paste that text
    repeatedly in each of the selected lines, thus replacing the blockwise
    selected region by multiple copies of the register text.  For example:
            - yank the word "TEXT" into a register with `yw`
            - select a visual block, marked with "v" in this text:
                aaavvaaa
                bbbvvbbb
                cccvvccc
            - press `p`, results in:
                aaaTEXTaaa
                bbbTEXTbbb
                cccTEXTccc

The text was also given a dedicated help tag at [`:help blockwise-put`](https://vimhelp.org/change.txt.html#blockwise-put) (the change is too recent for the website to have picked it up yet).

I think the new text is better because it explains that the register must be characterwise (while the selection must be blockwise).
