### ISSUE TITLE
when cscope not found, escaped ANSI control sequences in error message

### ISSUE THREAD

**Issue by Smattr** [vim/vim#11126]
### Steps to reproduce

I'm doing something a bit weird, so this is possibly a PEBKAC. But here are steps to repro:

1. Open a C file in Vim
2. `set csprg=/nonexistent/file`
3. `cs add blah.txt`

Then you get an error message (correct), but the error contains fragments of ANSI escape sequences:

![image](https://user-images.githubusercontent.com/203893/190050434-f40e88b2-5b11-42ae-9086-cd6ec2159300.png)

Text says `E609: Cscope error: [?1002h[?25l[97m[41mcs_create_connection exec failed: No such file or directory`.

`vim --clean` reverts the color scheme/style to default, but the ANSI sequences remain output.

### Expected behaviour

Obviously this is non-critical, but I think the ANSI sequences are either (1) never meant to be appended to the message to begin with or (2) stripped before displaying it in the status bar.

### Version of Vim

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Sep 01 2022 00:00:00) Included patches: 1-348 

### Environment

OS: Fedora 36, `uname -rms` Linux 5.19.8-200.fc36.x86_64 x86_64
Shell: Zsh
Terminal: Gnome Terminal 3.44.1
`$TERM`: tmux-256color

**Comment by brammool** [comment]
I cannot reproduce this, to not get any error.  Did you start with "vim --clean"?

**Comment by Smattr** [comment]
I could have sworn I did, but now that I try to follow the same steps I too cannot reproduce with `--clean`. Apologies for the noise.
