### ISSUE TITLE
cannot access for loop iteration variable from lambda

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#11124]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        var l: list<dict<string>>
        for s in ['a', 'b']
            l += ['c', 'd']->map((_, v) => ({key: $'{v} {s}'}))
        endfor
        echo l
    EOF
    )

An error is given:

    E1001: Variable not found: s

**Expected behavior**

No error is given.  This is echo'ed:

    [{'key': 'c a'}, {'key': 'd a'}, {'key': 'c b'}, {'key': 'd b'}]

**Version of Vim**

9.0 Included patches: 1-459

**Environment**

Operating system: Ubuntu 20.04.5 LTS
Terminal: XTerm(353)
Value of $TERM: xterm-256color
Shell: GNU bash, version 5.0.17

**Additional context**

Regression introduced in patch [9.0.0459](https://github.com/vim/vim/releases/tag/v9.0.0459)

**Comment by lacygoill** [comment]
Since a lambda is compiled, this might be a known issue:

https://github.com/vim/vim/blob/353b68a99189875a8460124d44fc33eae6def74e/src/testdir/test_vim9_script.vim#L2272-L2273

    # FIXME
    # v9.CheckDefAndScriptSuccess(lines)

**Comment by brammool** [comment]
> Since a lambda is compiled, this might be a known issue:
> 
> https://github.com/vim/vim/blob/353b68a99189875a8460124d44fc33eae6def74e/src/testdir/test_vim9_script.vim#L2272-L2273
> 
>     # FIXME
>     # v9.CheckDefAndScriptSuccess(lines)

No, this is something else.  Compilation of the closure happens at the
script level.

Simplified repro:

	vim9script

	for s in ['a', 'b']
	  timer_start(100,  (_) => s)
	endfor

-- 
hundred-and-one symptoms of being an internet addict:
58. You turn on your computer and turn off your wife.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
Fixed by patch [9.0.0460](https://github.com/vim/vim/releases/tag/v9.0.0460)
