### ISSUE TITLE
Vim incorrectly indents plaintext following a line starting with "for" or "while"

### ISSUE THREAD

**Issue by marrs** [vim/vim#11130]
### Steps to reproduce

1. Start vim with an empty buffer.
2. Write `for` (lowercase) or `while` (lowercase) followed by some text.
3. Hit enter to start a new line

The cursor will now be indented according to your tab stop settings.

The same thing will happen if you format a paragraph with `gqip`.  If one of the lines happens to start with `for` or `while`, subsequent lines will be indented.

I presume what is happening is that Vim is detecting these words as programming keywords and is indenting the text accordingly, but this is not code.  Explicitly setting the filetype as plaintext does not help.

### Expected behaviour

When writing plaintext, a newline should not be indented by the editor.

### Version of Vim

7, 8, 9.  This is an old bug!

### Environment

Linux, possibly macOS.  Both gvim and vim.

**Comment by k-takata** [comment]
Don't you enable the `smartindent` option in your .vimrc?

**Comment by chrisbra** [comment]
please try to reproduce using `vim --clean`. If it doesn't happen then, you need to check your configuration file. Check especially the various indent settings `smartindent`, `cindent`, `autoindent`

**Comment by marrs** [comment]
Behaviour is correct with `vim --clean`.  A quick test reveals that `smartindent` is the issue.

**Comment by arp242** [comment]
You typically only want `smartindent` enabled for C and C-like languages.

Filetypes that can take advantage of it typically usually set either `smartindent` or the similar `cindent` automatically. Setting either globally is rarely a good idea.

**Comment by chrisbra** [comment]
closing then

**Comment by marrs** [comment]
Surely it makes more sense for `smartindent` to only work for those languages then?  The word "smart" indicates that it knows what to do without any help from me.

**Comment by arp242** [comment]
> Surely it makes more sense for `smartindent` to only work for those languages then? The word "smart" indicates that it knows what to do without any help from me.

No, not really; `smartindent` is an old feature already present in v1.14 from 1991, way before Vim added flexible indenting with `indentexpr` (in 2001, with v6). It's named a bit unfortunately, but just don't set it and you'll be fine.
