### ISSUE TITLE
[virtual text] text is inserted in-between the buffer line and the virtual-text line

### ISSUE THREAD

**Issue by bfrg** [vim/vim#11131]
### Steps to reproduce

Run `vim --clean test.vim -S test.vim`, with
```vim
vim9script
colorscheme habamax
prop_type_add('test', {highlight: 'ModeMsg'})
prop_add(2, 0, {
    text:  '└─ Virtual text below the 2nd line',
    type: 'test',
    text_align: 'below',
    text_padding_left: 3
})
```

Now move the cursor to the 2nd line, press `A` and then `<CR>`. **Result:** The cursor jumps to the first column of the screen line containing the virtual-text. And the 3rd buffer line is drawn twice:

![screenshot-2022-09-14_193919](https://user-images.githubusercontent.com/6266600/190225424-ce68063f-9141-406a-bc49-f721d0c03c0b.png)

While in insert mode, press some keys. **Result:** Text is inserted above the line containing the virtual text, but should be below it.

![screenshot-2022-09-14_193930](https://user-images.githubusercontent.com/6266600/190225426-aaf0332d-bee9-4129-8eff-ab547f491c36.png)

**Note:** when we move the cursor to the 2nd line and press `o` in normal mode, the text will be correctly inserted below the virtual text.

Go back to normal mode and press `u`. **Result:** The inserted text is removed but the 3rd buffer line is drawn twice again:

![screenshot-2022-09-14_194144](https://user-images.githubusercontent.com/6266600/190225429-a6905a65-a483-4193-ab4c-df8ec6243e44.png)

### Expected behaviour

Text should be added below the virtual text when `<CR>` is pressed in insert mode, just like when `o` is pressed in normal-mode.

### Version of Vim

9.0.465

### Environment

Linux

**Comment by bfrg** [comment]
I just noticed that the virtual text isn't displayed at all when `list` is enabled.

**Comment by bfrg** [comment]
> I just noticed that the virtual text isn't displayed at all when `list` is enabled. If `list` is enabled interactively on the command-line, the virtual text disappears.

If `wrap` is disabled, the virtual text appears again, i.e. `:set list nowrap` works fine, but `:set list wrap` doesn't. Though, in both cases the same issue occurs when `<CR>` pressed at the end of a text line containing virtual text below it.

**Comment by brammool** [comment]
I fixed the obvious problem, but I haven't tried if that also fixes all the other situations.  Please create a new issue if you can still reproduce something.

**Comment by nickspoons** [comment]
`:set list` still hides the virtual text, and it is displayed again with `:set nolist`
