### ISSUE TITLE
[virtual text] highlighting of virtual text displayed 'above' or 'below' a text line is inconsistent

### ISSUE THREAD

**Issue by bfrg** [vim/vim#11138]
### Steps to reproduce

Run `vim --clean test.vim -S test.vim`, with

```vim
vim9script

colorscheme habamax
prop_type_add('test', {highlight: 'ModeMsg'})

prop_add(3, 0, {
    text:  '└─ Virtual text below the 3rd line',
    type: 'test',
    text_align: 'below',
    text_padding_left: 3
})

prop_add(4, 0, {
    text:  '┌─ Virtual text above the 4th line',
    type: 'test',
    text_align: 'above',
    text_padding_left: 3
})
```

Result: The highlighting of the virtual text that is `below` is highlighted correctly. But the highlighting of the virtual text that is displayed `above` seems to be wrong. The highlighting goes to the end of the screen as opposed to only until the end of the text.

Screenshot:

![screenshot-2022-09-15_001540](https://user-images.githubusercontent.com/6266600/190273220-c1db8427-8459-4d42-9cc3-92328cde91fa.png)

When `number` is enabled, both text properties are highlighted incorrectly:

```vim
vim9script
set number
colorscheme habamax
prop_type_add('test', {highlight: 'ModeMsg'})

prop_add(3, 0, {
    text:  '└─ Virtual text below the 3rd line',
    type: 'test',
    text_align: 'below',
    text_padding_left: 3
})

prop_add(4, 0, {
    text:  '┌─ Virtual text above the 4th line',
    type: 'test',
    text_align: 'above',
    text_padding_left: 3
})
```

Screenshot:

![screenshot-2022-09-15_001554](https://user-images.githubusercontent.com/6266600/190273246-82d22049-cb79-4549-b4d4-0058325a0f58.png)

### Expected behaviour

The highlighting of the virtual text that is `below` or `above` a text line shouldn't go beyond the end of the text. Furthermore, when `number` is enabled, the padding in front of the virtual text shouldn't have a highlighting.

### Version of Vim

9.0.467

### Environment

Linux

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> Run `vim --clean test.vim -S test.vim`, with
> 
> ```vim
> vim9script
> 
> colorscheme habamax
> prop_type_add('test', {highlight: 'ModeMsg'})
> 
> prop_add(3, 0, {
>     text:  '└─ Virtual text below the 3rd line',
>     type: 'test',
>     text_align: 'below',
>     text_padding_left: 3
> })
> 
> prop_add(4, 0, {
>     text:  '┌─ Virtual text above the 4th line',
>     type: 'test',
>     text_align: 'above',
>     text_padding_left: 3
> })
> ```
> 
> Result: The highlighting of the virtual text that is `below` is
> highlighted correctly. But the highlighting of the virtual text that
> is displayed `above` seems to be wrong. The highlighting goes to the
> end of the screen as opposed to only until the end of the text.

I have been wondering about that.  The space after the "above" virtual
text doesn't exist in the line.  Highlighting it as virtual text would
make that clear.  But perhaps the text itself is sufficient and users
won't get confused?

Perhaps we should defining highlighting for the "filler" used for
virtual text, could be set to something slightly different than the
normal background color.  That avoids having to define it for every
virtual text item and it does help to see what is a "filler" if you want
to see it.

> ### Expected behaviour
> 
> The highlighting of the virtual text that is `below` or `above` a text
> line shouldn't go beyond the end of the text. Furthermore, when
> `number` is enabled, the padding in front of the virtual text
> shouldn't have a highlighting.

The padding should not change depending on whether 'number' is set or
not.

-- 
From "know your smileys":
 (:-#	Said something he shouldn't have

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bfrg** [comment]
> I have been wondering about that.  The space after the "above" virtual
text doesn't exist in the line.  Highlighting it as virtual text would
make that clear.  But perhaps the text itself is sufficient and users
won't get confused?

I can only speak for myself. For me highlighting only the virtual text is enough. I think it will be clear from line numbers, cursor movement, or visual selection, and of course the context itself what is real text what is virtual text, assuming users use a distinct highlighting for the virtual text.

Example:
![screenshot-2022-09-16_192547](https://user-images.githubusercontent.com/6266600/190696624-4beaaef3-5264-4e42-b9c3-b9760643bb58.png)

But an additional `filler` option or highlighting group sounds like a good idea if it's not too much work to implement.

Maybe some other users could comment.

**Comment by ychin** [comment]
I like the additional highlight group idea. I wonder if a per-prop highlight group (e.g. `highlight_filler`) makes more sense than a global one? I'm not sure though, feel like there is an argument to be made each side.

Regarding being able to tell virtual texts apart, may be unrelated to this issue itself, but is there a way to quickly toggle virtual text on / off? I think right now the only way I know of is to loop through all the prop texts and delete them which seems intrusive.

**Comment by brammool** [comment]
> Regarding being able to tell virtual texts apart, may be unrelated to
> this issue itself, but is there a way to quickly toggle virtual text
> on / off? I think right now the only way I know of is to loop through
> all the prop texts and delete them which seems intrusive.

Hmm, an option to hide virtual text doesn't sound like the right way.
The virtual text will have been added by a plugin, thus the normal
approach would be to tell that plugin to remove them.
You might even have two plugins that add virtual text and want to see
only one of them.  That can't be done with an option.

-- 
From "know your smileys":
 *<|:-)	Santa Claus (Ho Ho Ho)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by nickspoons** [comment]
I agree that a highlight group for the filler is a good idea. Users who want minimal colours can disable it or not set it, while others who want visual aides for virtual lines can enable it.

The per-group suggestion at first seems appealing for configurability, but would there actually be any scenario where some virtual lines should have filler highlighting, but not others? I think it makes more sense as a global highlight group, which can be configured (and overridden) at the colorscheme level.

**Comment by bfrg** [comment]
The padding is still highlighted when `wrap` is disabled and `number` enabled:

```vim
vim9script
set nowrap number
colorscheme habamax
prop_type_add('test', {highlight: 'ModeMsg'})
prop_add(3, 0, {
    text:  '└─ Virtual text below the 3rd line',
    type: 'test',
    text_align: 'below',
    text_padding_left: 3
})
```

Screenshot:
![screenshot-2022-09-20_173549](https://user-images.githubusercontent.com/6266600/191301787-bcf6b653-d110-4b2e-8943-35f2a6897bf9.png)

Similarly, the padding is also highlighted when `signcolumn=yes` or `foldcolumn > 0`:
```vim
vim9script
set nowrap signcolumn=yes
colorscheme habamax
prop_type_add('test', {highlight: 'ModeMsg'})
prop_add(3, 0, {
    text:  '└─ Virtual text below the 3rd line',
    type: 'test',
    text_align: 'below',
    text_padding_left: 3
})
```

Screenshot:
![screenshot-2022-09-20_173754](https://user-images.githubusercontent.com/6266600/191302390-18a3b89d-5e79-44a3-b0c1-27df54c55418.png)
