### ISSUE TITLE
With 'nosplitscroll' the current window is unexpectedly scrolled when 'syntax' is set in a popup window

### ISSUE THREAD

**Issue by bfrg** [vim/vim#11145]
### Steps to reproduce

1. Run`vim --clean -S test.vim`, with
```vim
vim9script

set nosplitscroll

setline(1, range(100)->mapnew((_, i: number): string => i .. repeat(' test', 10)))
normal! G
normal! zz
normal! $

def Test()
    const winid: number = popup_atcursor('// test test test', {})
    setbufvar(winbufnr(winid), '&syntax', 'c')
enddef

nnoremap g<cr> <scriptcmd>Test()<cr>
```

2. While the cursor is located on the last line and centered on the screen, press `g<cr>`.
3. Result: The window scrolls unexpectedly. In some situations the cursor jumps to the beginning of a line (which I haven't been able to reproduce with a minimal example yet).

The scrolling is definitively caused when setting the syntax for the buffer displayed in the popup window:
```vim
setbufvar(winbufnr(winid), '&syntax', 'c')
```

No issues arise when `splitscroll` is enabled.

### Expected behaviour

No scrolling and no cursor jumps when the syntax is set for a buffer displayed in a popup window.

### Version of Vim

9.0.478

**Comment by bfrg** [comment]
cc @luukvbaal

**Comment by luukvbaal** [comment]
I can look into it later today/this weekend probably.

**Comment by luukvbaal** [comment]
Fix is found, I'll write a test and open PR tomorrow.

**Comment by bfrg** [comment]
Fixed by https://github.com/vim/vim/commit/d5bc762dea1fd32fa04342f8149f95ccfc3b9709.
