### ISSUE TITLE
incorrect platform detection in windows 10

### ISSUE THREAD

**Issue by gko** [vim/vim#1115]
Platform windows 10
vim 8.0.2

when running in cmd.exe `:echo has('unix')` results to 1
`:echo has("win32")`
`:echo has("win32s")`
`:echo has('win64')` all result to 0

**Comment by brammool** [comment]
Konstantin Gorodinskii wrote:

> Platform windows 10
> vim 8.0.2
> 
> when running in cmd.exe `:echo has('unix')` results to 1
> `echo has("win32")`
> `echo has("win32s")`
> `echo has('win64')` all result to 0

Not sure what you did, but that is impossible.

## 

PRINCE:    He's come to rescue me, father.
LAUNCELOT: (embarrassed) Well, let's not jump to conclusions ...
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by gko** [comment]
Sorry, that was vim that came with git.
