### ISSUE TITLE
no error for out of block-scope variable in debug mode

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#11156]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        def Func()
            if true
                var n = 123
            endif
            eval 0 + 0
        enddef
        breakadd func 4 Func
        Func()
    EOF
    )

At the debug prompt, execute `echo n`:  `123` is echo'ed.

**Expected behavior**

An error is given:

    E121: Undefined variable: n

Nothing is echo'ed.

Because `n` is set in the scope of the previous `if` block.  And at the time we ask for its value, we're outside the block, hence out of scope.

**Version of Vim**

9.0 Included patches: 1-499

**Environment**

Operating system: Ubuntu 20.04.5 LTS
Terminal: XTerm(353)
Value of $TERM: xterm-256color
Shell: GNU bash, version 5.0.17

**Additional context**

N/A

**Comment by brammool** [comment]
> **Steps to reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(tee <<'EOF'
>         vim9script
>         def Func()
>             if true
>                 var n = 123
>             endif
>             eval 0 + 0
>         enddef
>         breakadd func 4 Func
>         Func()
>     EOF
>     )
> 
> At the debug prompt, execute `echo n`:  `123` is echo'ed.
> 
> **Expected behavior**
> 
> An error is given:
> 
>     E121: Undefined variable: n
> 
> Nothing is echo'ed.
> 
> Because `n` is set in the scope of the previous `if` block.  And at
> the time we ask for its value, we're outside the block, hence out of
> scope.

Strictly speaking the value of "n" is not available here.  But it does
exist, so why not show the last value?

There is a mechanism to avoid showing variables that haven't been
declared yet, thus if you would try to show "n" before line 2 it won't
work.  Adding a mechanism to hide variables after their scope has been
left is quite complicated.  And I don't think it is all that useful.

-- 
hundred-and-one symptoms of being an internet addict:
97. Your mother tells you to remember something, and you look for
    a File/Save command.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> And I don't think it is all that useful.

Understood, closing then.

Something which would be more useful is for the line range to be passed to the debug command so that a multiline statement including a comment is not truncated too early.  It was already discussed [here](https://github.com/vim/vim/issues/8392#issuecomment-863867379).
