### ISSUE TITLE
`:unlet $FOOBAR`

### ISSUE THREAD

**Issue by LucHermitte** [vim/vim#1116]
When an environment variable isn't set, `exists()` return false. We can assign a value to the variable with `:let`, after which point it exists. But we can't revert to an non-existent state (related to `unsetenv (3C)`)

``` vim
call assert_false(exists('$FOOBAR'))
let $FOOBAR = 1
call assert_true(exists('$FOOBAR'))
unlet $FOOBAR
call assert_false(exists('$FOOBAR'))
```

**Comment by brammool** [comment]
It's in the todo list:

Can we make ":unlet $VAR" use unsetenv() to delete the env var?
What for systems that don't have unsetenv()?

**Comment by IwanKaramazow** [comment]
If I would want to implement this, where do I start?

**Comment by mattn** [comment]
As I mentioned in https://github.com/vim/vim/issues/2854, Vim doesn't have a way to revert `$TZ`. So we should implement `unlet $FOOBAR`.

**Comment by lifecrisis** [comment]
It looks like this issue can be closed.  Patch 8.0.1832 took care of this.

**Comment by k-takata** [comment]
closing.
