### ISSUE TITLE
Can't map :normal commands

### ISSUE THREAD

**Issue by habamax** [vim/vim#11165]
### Steps to reproduce

1. `vim -Nu NONE`
2. `:nnoremap <C-a> :exe "normal \<c-w>\<c-w>"<CR>`
3. `:split`
4. press `CTRL-a`

### Expected behaviour

Window should be switched, instead `E471: Argument required: normal` error is echoed.

If you look into `:h :normal`, the last paragraph is:

```
			Example: >
				:exe "normal \<c-w>\<c-w>"
```

Which looks like it should work in a mapping (and I remember it worked in the past, but I might be wrong). 

### Version of Vim

9.0.0500

### Environment

- win10, fedora36
- bash
- gvim, any term

**Comment by zeertzjq** [comment]
Try changing `:` to `<Cmd>`

**Comment by habamax** [comment]
@zeertzjq It works with `<cmd>` as I answered in https://vi.stackexchange.com/a/38584/9333

Still, I "remember" it worked with `:` so not sure if this is a bug or intentional change, which is not documented under `:h :normal`.

**Comment by zeertzjq** [comment]
Try typing the RHS manually:
1. `:exe "normal \` is typed
2. `<c-w>` deletes the last `\`
3. another `\` is typed
4. `<c-w>` deletes the last `\`
5. `"<CR>` is typed

So the typed command is `:exe "normal "`

**Comment by zeertzjq** [comment]
You can also change `<` to `<lt>`, so that `<lt>c-w>` will be typed as five characters `<` `c` `-` `w` `>` instead of a CTRL-W key.

**Comment by habamax** [comment]
Ok, got it. Thanks for clarification!
