### ISSUE TITLE
make [[ and ]] jump to export def in vim files

### ISSUE THREAD

**Issue by habamax** [vim/vim#11176]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

Currently `]]` and `[[` do not jump to `export def` in vim9script.

I can remap bundled with vim mappings to

```
  nnoremap <silent><buffer> [[ m':call search('^\s*\(fu\%[nction]\\|\(export \)\?def\)\>', "bW")<CR>
  vnoremap <silent><buffer> [[ m':<C-U>exe "normal! gv"<Bar>call search('^\s*\(fu\%[nction]\\|\(export \)\?def\)\>', "bW")<CR>
  nnoremap <silent><buffer> ]] m':call search('^\s*\(fu\%[nction]\\|\(export \)\?def\)\>', "W")<CR>
  vnoremap <silent><buffer> ]] m':<C-U>exe "normal! gv"<Bar>call search('^\s*\(fu\%[nction]\\|\(export \)\?def\)\>', "W")<CR>

```

But I guess, vim ftplugin should have it out of the box.

**Comment by brammool** [comment]
Thanks, I'll include this.  With some more flexibility for white space after "export".
