### ISSUE TITLE
vim got stuck if mapping is 0 in popup_create

### ISSUE THREAD

**Issue by Yggdroot** [vim/vim#11172]
### Steps to reproduce

1. test.vim:
```vim
func MyFilter(winid, key)
  return 0
endfunc

let id = popup_create(bufnr('%'),
            \ {'line':0, 'col':0, 'padding': [0, 1, 1, 1],
            \ 'maxwidth':60, 'minheight':7, 'border':[1,1,1,1],
            \ 'mapping': 0,
            \ 'filter': 'MyFilter'})

redraw!

python3 << EOF

import vim
import time


while 1:
    ch = vim.eval("getchar()")
    print(ch)

EOF
```
2.  vim test.vim
3. :so %
4. type `a`, `b`, `c`, then 97, 98, 99 is printed.
5. press Ctrl+Shift+V, 
6. vim got stuck
7. type `a`, `b`, `c`, nothing happen.
8. you have to press ctrl-c

### Expected behaviour

if the value of `mapping`  in `popup_create` is 1 , the behavior will be expected.

### Version of Vim

9.0.213

### Environment

OS: linux
terminal: GNOME Terminal 3.14.3
$TERM: xterm-256color

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> 1. test.vim:
> ```vim
> func MyFilter(winid, key)
>   return 0
> endfunc
> 
> let id = popup_create(bufnr('%'),
>             \ {'line':0, 'col':0, 'padding': [0, 1, 1, 1],
>             \ 'maxwidth':60, 'minheight':7, 'border':[1,1,1,1],
>             \ 'mapping': 0,
>             \ 'filter': 'MyFilter'})
> 
> redraw!
> 
> python3 << EOF
> 
> import vim
> import time
> 
> 
> while 1:
>     ch = vim.eval("getchar()")
>     print(ch)
> 
> EOF
> ```
> 2.  vim test.vim
> 3. :so %
> 4. type `a`, `b`, `c`, then 97, 98, 99 is printed.
> 5. press Ctrl+Shift+V, 
> 6. vim got stuck
> 7. type `a`, `b`, `c`, nothing happen.
> 8. you have to press ctrl-c

What is that Ctrl-Shift-V supposed to do?  Perhaps you have it mapped,
and when mappings are disabled it does something else?  I don't think
Vim recognizes it, only CTRL-V is used to start Visual block mode.  But
the Python command will eat all characters.

-- 
hundred-and-one symptoms of being an internet addict:
104. When people ask about the Presidential Election you ask "Which country?"

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Yggdroot** [comment]
I didn't map Ctrl-Shift-V, Ctrl-Shift-V is the builtin command of GNOME Terminal, it's to paste something from the system clipboard. It has the same functionality as Command-V on Mac OS.
In a normal vim buffer, if Ctrl-Shift-V is pressed, "abc" will be pasted in the buffer, suppose "abc" is in the system clipboard.
In my opinion, it is the same as typing 'a', 'b', 'c' very quickly.

**Comment by brammool** [comment]
Thus it's the terminal that sends something to Vim, which causes Vim to somehow get stuck.

Please add this to the top of the script:  ```call ch_logfile("logfile", "w")```
Then do your reproduction steps and quit Vim.
Now the "logfile" contains information about Vim really received from the terminal.
For me pasting the clipboard (in xterm that is shift-middle-mouse) shows:
```raw key input: "[200~changed[201~"```
Those escape sequence before and after the pasted text should match t_PS and t_PE.
see ":help xterm-bracketed-paste"

**Comment by Yggdroot** [comment]
cat logfile
```
==== start log session Fri Sep 23 09:28:55 2022 ====
  1.861980 : raw key input: "[200~somehow[201~"
  1.862522 : looking for messages on channels
```
:echom &t_PS
`�[200~`
:echom &t_PE
`�[201~`

**Comment by brammool** [comment]
Hmm, I can make it a bit better by making getchar() not handle bracketed paste.
However, this Python loop will fail on any special characters, thus as soon as it gets the bracketed paste key it gives an error and drops out of the loop.

**Comment by Yggdroot** [comment]
Thanks, the issue is fixed.
