### ISSUE TITLE
Deleted augroup issue after vim upgrade

### ISSUE THREAD

**Issue by syml** [vim/vim#1117]
The plugins syml/rust-codefmt and rust-lang/rust.vim are not compatible anymore after I upgraded my vim (7.4 -> 8). Not sure which version of 7.4 I had, sorry.

syml/rust-codefmt are both rust language plugins with a rust ftdetect file containing:
au BufRead,BufNewFile *.rs set filetype=rust

When both plugins are used I now get:
W19: Deleting augroup that is still in use

Each plugin cannot assume another rust plugin is used to set the filetype. Is this a vim issue?

**Comment by chrisbra** [comment]
It's a warning, that doesn't mean the plugins are not compatible anymore. Also that warning helps to prevent error (before, it was not checked). You should discuss this issue with the plugin developers.

**Comment by syml** [comment]
But it opens the message window every time I open a .rs file ...

**Comment by syml** [comment]
If this is not a bug then vim shouldn't show the 'Press enter to continue' window when messages are warnings only.

**Comment by dpelle** [comment]
> If this is not a bug then vim shouldn't show the 'Press enter to continue'
> window when messages are warnings only.

It is a bug, but my understanding is that it is a bug in the plugins, not in Vim.
W19 is a new warning, introduced in Vim-7.4.2117 (Jul 2016) which
detects invalid deletion of autocommands,
