### ISSUE TITLE
getchar() in a loop can only get one character

### ISSUE THREAD

**Issue by Yggdroot** [vim/vim#11173]
### Steps to reproduce

1.  suppose "abc" is in the clipboard.
2. `:while 1 | echom getchar() | endw`
3. press Ctrl+Shift+V
4. only the ascii of the first character `a` is printed.

### Expected behaviour

```
97
98
99
```
is printed.

By the way, Gvim on windows works as expected.

### Version of Vim

9.0.213

### Environment

OS: Linux
terminal: GNOME Terminal 3.14.3

**Comment by Yggdroot** [comment]
Close as the issue is fixed along with #11172.

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> 1.  suppose "abc" is in the clipboard.
> 2. `:while 1 | echom getchar() | endw`
> 3. press Ctrl+Shift+V
> 4. only the ascii of the first character `a` is printed.

What does Ctrl-Shift-V do?  Is that a Gnome terminal thing?
If so, then perhaps bracketed paste is interfering.
 

-- 
A meeting is an event at which the minutes are kept and the hours are lost.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Yggdroot** [comment]
Thanks, the issue has been fixed by [patch 9.0.0575](https://github.com/pheiduck/vim/commit/011b206dd702e5d3334a3f7a48249ff86b3a3ddb)
