### ISSUE TITLE
Cannot tell which part is "buffered" by ch_status()

### ISSUE THREAD

**Issue by haya14busa** [vim/vim#1120]
Hi!
## Problem

`ch_status()` sees stdout and stderr to check channel has buffered message, and
we cannot know which part(stdout/stderr) has the buffered message.

From `:h read-in-close-cb`, we can write following code.
`gcc err_notfound.c` fails and print message to **stderr**.
#### job.vim

``` vim
func! CloseHandler(channel)
  while ch_status(a:channel) == 'buffered'
    echomsg ch_read(a:channel)
  endwhile
endfunc
let job = job_start(['gcc', 'err_notfound.c'], {'close_cb': 'CloseHandler'})
```
### How to Reproduce
- `vim -Nu NONE -S job.vim`

It will be trapped in an infinite loop.

```
Error detected while processing function CloseHandler:
line    2:
E906: not an open channel
E906: not an open channel
E906: not an open channel
E906: not an open channel
...
```

We can read stderr message by `ch_read(a:channel, {'part': 'err'})`, but we
cannot tell which part has buffered messages.
`ch_read()` throws error (E906: not an open channel) if the specified part
doesn't have message, so we cannot write following code as a workaround for example.

``` vim
" this code doesn't handle error!
func! CloseHandler(channel)
  while ch_status(a:channel) == 'buffered'
    echomsg ch_read(a:channel)
    echomsg ch_read(a:channel, {'part': 'err'})
  endwhile
endfunc
```
### Expect behavior

I'm not sure what should Vim do, I tried to fix this in a couple of ways, but
all of them were not perfect.

We might be able to fix this by adding additional option arg to `ch_status()`
to specify `"part"` which is same as the option for `ch_read` to check.
(@h-east's idea )

``` vim
" example
func! CloseHandler(channel)
  while ch_status(a:channel, {'part': 'out'}) == 'buffered'
    echomsg ch_read(a:channel, {'part': 'out'})
  endwhile
  while ch_status(a:channel, {'part': 'err'}) == 'buffered'
    echomsg ch_read(a:channel, {'part': 'err'})
  endwhile
endfunc
let job = job_start(['gcc', 'err_notfound.c'], {'close_cb': 'CloseHandler'})
```

We might be able to modify `ch_status()` to use only stdout by default if option is not given.

Anyway, it depends on the specification of channel associated with job.

What do you think?

**Comment by brammool** [comment]
haya14busa wrote:

> ## Problem
> 
> `ch_status()` sees stdout and stderr to check channel has buffered message, and
> we cannot know which part(stdout/stderr) has the buffered message.
> 
> > From `:h read-in-close-cb`, we can write following code.
> > `gcc err_notfound.c` fails and print message to **stderr**.
> 
> #### job.vim
> 
> ``` vim
> func! CloseHandler(channel)
>   while ch_status(a:channel) == 'buffered'
>     echomsg ch_read(a:channel)
>   endwhile
> endfunc
> let job = job_start(['gcc', 'err_notfound.c'], {'close_cb': 'CloseHandler'})
> ```
> 
> ### How to Reproduce
> - `vim -Nu NONE -S job.vim`
> 
> It will be trapped in an infinite loop.
> 
> ```
> Error detected while processing function CloseHandler:
> line    2:
> E906: not an open channel
> E906: not an open channel
> E906: not an open channel
> E906: not an open channel
> ...
> ```
> 
> We can read stderr message by `ch_read(a:channel, {'part': 'err'})`, but we
> cannot tell which part has buffered messages.
> `ch_read()` throws error (E906: not an open channel) if the specified part
> doesn't have message, so we cannot write following code as a workaround for example.
> 
> ``` vim
> " this code doesn't handle error!
> func! CloseHandler(channel)
>   while ch_status(a:channel) == 'buffered'
>     echomsg ch_read(a:channel)
>     echomsg ch_read(a:channel, {'part': 'err'})
>   endwhile
> endfunc
> ```
> 
> ### Expect behavior
> 
> I'm not sure what should Vim do, I tried to fix this in a couple of ways, but
> all of them were not perfect.
> 
> We might be able to fix this by adding additional option arg to `ch_status()`
> to specify `"part"` which is same as the option for `ch_read` to check.
> (@h-east's idea )
> 
> ``` vim
> " example
> func! CloseHandler(channel)
>   while ch_status(a:channel, {'part': 'out'}) == 'buffered'
>     echomsg ch_read(a:channel, {'part': 'out'})
>   endwhile
>   while ch_status(a:channel, {'part': 'err'}) == 'buffered'
>     echomsg ch_read(a:channel, {'part': 'err'})
>   endwhile
> endfunc
> let job = job_start(['gcc', 'err_notfound.c'], {'close_cb': 'CloseHandler'})
> ```
> 
> We might be able to modify `ch_status()` to use only stdout by default if option is not given.
> 
> Anyway, it depends on the specification of channel associated with job.
> 
> What do you think?

Yeah, there isn't a nice way to do this now.

Another way is to change ch_info() to return the same status as ch_status
for out_status and err_status:

```
       "out_status"   "open", "closed" or "buffered"
       "err_status"   "open", "closed" or "buffered"
```

Then when ch_status() returns "buffered" you can use ch_info() to check
what to read.  Or use ch_info() right away instead of ch_status().

This is slightly incompatible, adding a third possible value for the
status.  But it makes it consistent with ch_status().  The documentation
is actually wrong already, since it mentions "status" as "open" or
"closed", while it can actually be "buffered".

So, I think we should both add the optional argument to ch_status() and
add "buffered" to ch_info().

## 

GUARD #1:  Where'd you get the coconut?
ARTHUR:    We found them.
GUARD #1:  Found them?  In Mercea?  The coconut's tropical!
ARTHUR:    What do you mean?
GUARD #1:  Well, this is a temperate zone.
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by haya14busa** [comment]
Thank you! I confirmed patch 8.0.0015 https://github.com/vim/vim/commit/7ef3810d28b7ab2edbfcafab3fe8ad8bc2c2f138 fixed the problem.

But, the example script in `:h read-in-close-cb` should be fixed too.

``` patch
diff --git a/runtime/doc/channel.txt b/runtime/doc/channel.txt
index 7c286f3..e0a2f72 100644
--- a/runtime/doc/channel.txt
+++ b/runtime/doc/channel.txt
@@ -516,7 +516,7 @@ If the job can take some time and you don't need intermediate results, you can
 add a close callback and read the output there: >

    func! CloseHandler(channel)
-     while ch_status(a:channel) == 'buffered'
+     while ch_status(a:channel, {'part': 'out'}) == 'buffered'
        echomsg ch_read(a:channel)
      endwhile
    endfunc
```

**Comment by brammool** [comment]
Thanks for the correction of the example.
