### ISSUE TITLE
Terminal window accidentially shows up when calling `system` in callback of `job_start` and `!` is in `guioptions`

### ISSUE THREAD

**Issue by senioria** [vim/vim#11202]
# Steps to reproduce

`/tmp/a.vim`:
``` vim
vim9script
set go=!
job_start("echo", { exit_cb: (..._) => system("echo") })
```

Invoke gvim with `gvim --clean -S /tmp/a.vim`, and the statusline appears in the middle of the frame, indicating that vim attempts to show the terminal window.

Meanwhile, the equivalent code in legacy vimscript would only move the cursor to the command line and swallow the next keystroke:

``` vim
set go=!
call job_start("echo", #{ exit_cb: { ... -> system("echo") } })
```

# Expected behavior

Both invocations should be invisible to users.

vim version: 9.0.542

**Comment by lacygoill** [comment]
FWIW, I noticed something similar when using a completion function in issue https://github.com/vim/vim/issues/9759

**Comment by 91khr** [comment]
> FWIW, I noticed something similar when using a completion function in issue #9759

Sorry for didn't find that... However, since `system()` is not intended for users to interact with the subprocess, maybe it shouldn't "leak" the terminal window, just like `job_start()`?
Or, at least, the behavior should be consistent in legacy script and Vim9...?

**Comment by lacygoill** [comment]
> since system() is not intended for users to interact with the subprocess, maybe it shouldn't "leak" the terminal window, just like job_start()?  Or, at least, the behavior should be consistent in legacy script and Vim9...?

Yes, I don't think it's expected for a terminal window to be visible.  And even if it is, the type of syntax (legacy vs Vim9) should not matter here.
