### ISSUE TITLE
Introduce programmatic access in :syn-start patterns

### ISSUE THREAD

**Issue by zzzyxwvut** [vim/vim#11217]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

Various textbook authors concur that it is impractical to
describe _balanced_ tokens with regular expressions.

Aho et al. in _Compilers: Principles, Techniques, and Tools_
(2nd Ed., §4.3.1, p. 210):
> There are no firm guidelines as to what to put into
> the lexical rules, as opposed to the syntactic rules.
> Regular expressions are most useful for describing
> the structure of constructs such as identifiers,
> constants, keywords, and white space. Grammars, on
> the other hand, are most useful for describing nested
> structures such as balanced parentheses, matching
> begin-end’s, corresponding if-then-else’s, and so on.
> These nested structures cannot be described by
> regular expressions.

Sedgewick and Wayne in _Algorithms_ (4th Ed., §5.4, p. 793):
> LIMITATIONS. Not all languages can be specified with
> REs [regular expressions]. A thought-provoking example
> is that no RE can describe the set of all strings that
> specify legal REs. Simpler versions of this example are
> that we cannot use REs to check whether parentheses
> are balanced or to check whether a string has an equal
> number of `A`s and `B`s.

Friedl in _Mastering Regular Expressions_ (2nd Ed., §5,
p. 194):
> The real problem is that on the vast majority of
> systems, _you simply can’t match arbitrarily nested
> constructs with regular expressions_. For a long time,
> this was universally true, but recently, both `Perl` and
> `.NET` offer constructs that make it possible. &nbsp;[. . .]
> But, even without these special constructs, you can
> still build a regex to match things nested _to a certain
> depth_, but not to an _arbitrary level_ of nesting. Just
> one level of [parenthetical] nesting requires [in `Perl`]
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`\([^()]*`*(*`\([^()]*\)[^()]*`*)\**`\)`
> so the thought of having to worry about further levels
> of nesting is frightening.

It is possible to assemble nested balanced definitions with
partial/recursive `:syn-region` definitions, afforded by
the `:syn-contains` and `:syn-nextgroup` arguments. However,
there is no support for the referencing of such definitions
in regexp patterns.

I wonder whether an extension of `:syn-region` could be
entertained with which programmatic access in `:syn-start`
patterns could be brought in and such impractical problems
could be tackled.

**Describe the solution you'd like.**

Consider a PROTOTYPE.

There are already external matches (`:syn-ext-match`) that
lend a `\z(\)` meta-character expression. Let's introduce
another expression after the fashion, e.g. `\y(\)`. (There
are still a few meta-character candidates: `[BEGgJjNQqRTYy]`.)

Now, whenever this expression would be encountered in `start`,
the regexp engine would, as usual, try to match the enclosed
expression and, if successful, it would transfer its control
to a user-defined script-local function whose name must be
advertised with a new `:syn-region` argument, e.g. `yardstick`.
For multiple instances of `\y(\)` in a particular `start`,
either the only function would be used or a comma-separated
list of multiple function names should be provided. Also,
let's take after the way `:syn-matchgroup` arguments bind
to the following `start`.

In order to be accepted, advertised script-local function
declarations would have to match some canonical function
signature, but may bear arbitrary names.

For example,

```vim
def <identifier>(data: blob, start: number, end: number): number
. . .
```

- where the `data` argument is a chunk of contiguous buffer 
  bytes under consideration of the regexp engine (it would
  be up to the regexp engine to decide how much `data` can
  be examined in either direction);
- where the `start` argument is the position value in `data`
  of the leftmost enclosed _character_ of `\y(\)`;
- where the `end` argument is the position value in `data` of
  the rightmost enclosed _character_ of `\y(\)`.

Or a variant of an assigned curried lambda expression,

```vim
const <identifier> = (): func(blob): func(number, number): number => . . .
```

The task of the function implementer would be to discover
and return a positive offset value off the passed `end` value
(zero could be treated as if it were one) where the regexp
engine should resume its execution and examine the leftmost
character, if any, _after_ the whole `\y(\)` expression when
a successful (unexpressed) intermediate match has been made
by this function _and_ further matching would be necessary
(_or_ repeat the `\y(\)` step if the expression is starred or
plussed, etc.); otherwise, to return some negative value or
an out-of-bounds positive value admitting that no match has
been made.

------------------------------------------------------------

Suppose that we wish to recognise the `{@snippet . . .}` [tags](https://openjdk.org/jeps/413),
in the `Java` documentation comments, that may include many
variously-nested balanced braces in their `. . .` enclosed
multi-line expressions. We begin with a function definition
as follows:

```vim
def MatchBalancedCurlies(data: blob, start: number, end: number): number
    const left: number = char2nr('{')
    const right: number = char2nr('}')
    const length: number = len(data) - end

    # Assume the presence of the leftmost brace; or test _start_.
    var curlies: number = 1
    var offset: number = 0

    while (offset < length) && (curlies > 0)
	++offset
	const token: number = get(data, end + offset)
	curlies += (token == right) ? -1 : (token == left) ? 1 : 0
    endwhile

    return (curlies == 0) ? offset : -1
enddef
```

And continue with a following `:syn-region` definition:

```vim
syntax region javaDocSnippetTag contained
    \ yardstick=MatchBalancedCurlies
    \ start="\y({@snippet\s\+\)\z(}\)\@="
    \ end="\z1"
```

where the `start` argument should be parsed as:

* Try to make a match of `{@snippet\s\+` with the regexp
  engine; and if successful,
    + Have `MatchBalancedCurlies` invoked, passing it
      a chunk of contiguous buffer bytes for `data` and
      the `start` index of the leftmost matched `{` in it and
      the `end` index of the rightmost matched `\s` in it;
      then, if an in-range positive offset value has been
      obtained, resume the regexp engine execution that
      many bytes after the rightmost matched `\s` (here
      return the index of the balanced `}` so that it can be
      captured with repeated matching), and
        - Try to make a zero-width lookahead match of
          `}`; and if successful,
            * Capture the match as `\z1`; and, finally,
              accept the whole `start` pattern text match
* Otherwise, reject the whole `start` pattern text match

**Describe alternatives you've considered.**

The current recognition [strategy](https://github.com/zzzyxwvut/vim/commit/74e4fc0c9dcd08c39539f22c29d896b2ba446d72) for the tag is to look for
the `{@snippet\>` pattern in `start` and, after matching `}` in
`end`, continue by looking ahead at the lines after an ‘empty’
line that begin with optional space and either another tag
or a _capital_ letter (maybe, a new sentence).
See, for example, [`java.lang.Double`](https://github.com/openjdk/jdk/blob/jdk-19%2B36/src/java.base/share/classes/java/lang/Double.java#L643-L689) and [`java.lang.Thread`](https://github.com/openjdk/jdk/blob/jdk-19%2B36/src/java.base/share/classes/java/lang/Thread.java#L562-L577).

Unfortunately, such a region must unwittingly extend past
the rightmost balanced `}` whenever the tag is in the middle
of a sentence--if it were checked, it would still remain
undecided, after an ‘empty’ line that is followed by a line
with optional space and a _small_ letter, whether this letter
is inside the tag and forms a keyword _or_ it is outside
the tag and forms a word that continues a sentence.
See, for example, [`java.lang.foreign.MemoryLayout`](https://github.com/openjdk/jdk/blob/jdk-19%2B36/src/java.base/share/classes/java/lang/foreign/MemoryLayout.java#L415-L428) and
[`java.lang.foreign.SequenceLayout`](https://github.com/openjdk/jdk/blob/jdk-19%2B36/src/java.base/share/classes/java/lang/foreign/SequenceLayout.java#L108-L112).

**Comment by brammool** [comment]
Aliaksei Budavei wrote:

> **Is your feature request about something that is currently impossible
> or hard to do? Please describe the problem.**
> 
> Various textbook authors concur that it is impractical to
> describe _balanced_ tokens with regular expressions.
> 
> Aho et al. in _Compilers: Principles, Techniques, and Tools_
> (2nd Ed., §4.3.1, p. 210):
> > There are no firm guidelines as to what to put into
> > the lexical rules, as opposed to the syntactic rules.
> > Regular expressions are most useful for describing
> > the structure of constructs such as identifiers,
> > constants, keywords, and white space. Grammars, on
> > the other hand, are most useful for describing nested
> > structures such as balanced parentheses, matching
> > begin-end’s, corresponding if-then-else’s, and so on.
> > These nested structures cannot be described by
> > regular expressions.

More accurate: "a nested structure cannot be described by a regular
expression".  However, Vim syntax uses nested regions and matches, which
works fine.

> Sedgewick and Wayne in _Algorithms_ (4th Ed., §5.4, p. 793):
> > LIMITATIONS. Not all languages can be specified with
> > REs [regular expressions]. A thought-provoking example
> > is that no RE can describe the set of all strings that
> > specify legal REs. Simpler versions of this example are
> > that we cannot use REs to check whether parentheses
> > are balanced or to check whether a string has an equal
> > number of `A`s and `B`s.

Again, not with one RE, but it works with regions that can contain
regions.  And each region start and end can be described with an RE.
Most languages use EBNF to describe the grammar, which is very similar.

> Friedl in _Mastering Regular Expressions_ (2nd Ed., §5,
> p. 194):
> > The real problem is that on the vast majority of
> > systems, _you simply can’t match arbitrarily nested
> > constructs with regular expressions_. For a long time,
> > this was universally true, but recently, both `Perl` and
> > `.NET` offer constructs that make it possible.  [. . .]
> > But, even without these special constructs, you can
> > still build a regex to match things nested _to a certain
> > depth_, but not to an _arbitrary level_ of nesting. Just
> > one level of [parenthetical] nesting requires [in `Perl`]
> >        `\([^()]*`*(*`\([^()]*\)[^()]*`*)\**`\)`
> > so the thought of having to worry about further levels
> > of nesting is frightening.

Again, using one RE.  Nested REs can do this just fine.

> It is possible to assemble nested balanced definitions with
> partial/recursive `:syn-region` definitions, afforded by
> the `:syn-contains` and `:syn-nextgroup` arguments. However,
> there is no support for the referencing of such definitions
> in regexp patterns.
> 
> I wonder whether an extension of `:syn-region` could be
> entertained with which programmatic access in `:syn-start`
> patterns could be brought in and such impractical problems
> could be tackled.

It's not clear yet what the problems are.  Yes, it would be possible to
add a new RE element that calls a function.  But that's complicated and
needs very good justification.  I would suggest that, instead of diving
into the details of a solution, first clearly describe what items you
are struggling with to match with the current syntax engine.


Besides, there is a discussion about using other ways to define syntax
highlighting, referring to treesitter and TextMate, which also have
their own engine to execute them.  Making the Vim syntax engine more
complex might not be the first next step.  Can other engines parse the
text better than Vim?


I think there is one thing that none of the engines currently can do:
Only accept the start of a region when (after an arbitrary amount of
nested text) the end is also found.  E.g. in HTML only accept <someTag>
if later on </someTag> is found.  But we don't need to call a function
for that, could just be a property on the region.  And then it's going
to be quite lot of work to implement and even more to make it efficient.

[...]

> The task of the function implementer would be to discover
> and return a positive offset value off the passed `end` value
> (zero could be treated as if it were one) where the regexp
> engine should resume its execution and examine the leftmost
> character, if any, _after_ the whole `\y(\)` expression when
> a successful (unexpressed) intermediate match has been made
> by this function _and_ further matching would be necessary
> (_or_ repeat the `\y(\)` step if the expression is starred or
> plussed, etc.); otherwise, to return some negative value or
> an out-of-bounds positive value admitting that no match has
> been made.

Isn't this similar to what is done with "\ze" ?

[...]
> And continue with a following `:syn-region` definition:
> 
> ```vim
> syntax region javaDocSnippetTag contained
>     \ yardstick=MatchBalancedCurlies
>     \ ***@***.***\s\+\)\z(}\)\@="
>     \ end="\z1"
> ```

Not sure why that \z1 is needed, we know the region will end with "}".
We just need to make sure that any nested {} are matched by containing
regions and matches.

> **Describe alternatives you've considered.**
> 
> The current recognition [strategy](https://github.com/zzzyxwvut/vim/commit/74e4fc0c9dcd08c39539f22c29d896b2ba446d72) for the tag is to look for
> the ***@***.***\>` pattern in `start` and, after matching `}` in
> `end`, continue by looking ahead at the lines after an ‘empty’
> line that begin with optional space and either another tag
> or a _capital_ letter (maybe, a new sentence).
> See, for example, [`java.lang.Double`](https://github.com/openjdk/jdk/blob/jdk-19%2B36/src/java.base/share/classes/java/lang/Double.java#L643-L689) and [`java.lang.Thread`](https://github.com/openjdk/jdk/blob/jdk-19%2B36/src/java.base/share/classes/java/lang/Thread.java#L562-L577).
> 
> Unfortunately, such a region must unwittingly extend past
> the rightmost balanced `}` whenever the tag is in the middle
> of a sentence--if it were checked, it would still remain
> undecided, after an ‘empty’ line that is followed by a line
> with optional space and a _small_ letter, whether this letter
> is inside the tag and forms a keyword _or_ it is outside
> the tag and forms a word that continues a sentence.
> See, for example, [`java.lang.foreign.MemoryLayout`](https://github.com/openjdk/jdk/blob/jdk-19%2B36/src/java.base/share/classes/java/lang/foreign/MemoryLayout.java#L415-L428) and
> [`java.lang.foreign.SequenceLayout`](https://github.com/openjdk/jdk/blob/jdk-19%2B36/src/java.base/share/classes/java/lang/foreign/SequenceLayout.java#L108-L112).

Not clear why this is so complicated.  Is it trying to match the right
"}" by looking at what follows?  That doesn't seem right, it should
have a contained region matching {} items.  It looks like we can assume
that contained {} items are balanced.  If not, then that could be
considered an error.

-- 
Apathy Error: Don't bother striking any key.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by zzzyxwvut** [comment]
> It's not clear yet what the problems are.  Yes, it would be possible to
> add a new RE element that calls a function.  But that's complicated and
> needs very good justification.  I would suggest that, instead of diving
> into the details of a solution, first clearly describe what items you
> are struggling with to match with the current syntax engine.

There _was_ a problem with describing a grammar (`:syn-region`)
that would correctly match the outermost balanced braces `{}`
of a `{@snippet . . .}` tag, for it may include other pairs
of balanced braces, which may further nest other pairs. This
tag may span across multiple lines. However, it would send
one on a fool's errand should contained regions be tailored
to _any_ language. Firstly, after all, these snippets may be
written in plain text, or in a non-`Java` language, etc.; and
secondly, by its nature, snippets written in a programming
language tend to be loosely formed, explicitly omitting some
syntactical parts, scattering ellipses here and there, which
would likely be marked as syntax errors and draw attention.
So the goal is to only brush by these nested braces seeking
the outermost right brace and uniformly colour a snippet,
only highlighting its attributes and additional markup tags.

> > The task of the function implementer would be to discover
> > and return a positive offset value off the passed `end` value
> > (zero could be treated as if it were one) where the regexp
> > engine should resume its execution and examine the leftmost
> > character, if any, _after_ the whole `\y(\)` expression when
> > a successful (unexpressed) intermediate match has been made
> > by this function _and_ further matching would be necessary
> > (_or_ repeat the `\y(\)` step if the expression is starred or
> > plussed, etc.); otherwise, to return some negative value or
> > an out-of-bounds positive value admitting that no match has
> > been made.
>
> Isn't this similar to what is done with "\ze" ?

Well, along the lines of the sketched prototype, the matched
balanced (right) token from `:syn-start` would be referenced
in `:syn-end`, so `\z(\)` is it.

> > And continue with a following `:syn-region` definition:
> >
> > ```vim
> > syntax region javaDocSnippetTag contained
> >     \ yardstick=MatchBalancedCurlies
> >     \ start="\y({@snippet\s\+\)\z(}\)\@="
> >     \ end="\z1"
> > ```
>
> Not sure why that \z1 is needed, we know the region will end with "}".
> We just need to make sure that any nested {} are matched by containing
> regions and matches.

With the example definition, given the fact that as long as
we do not care to recognise the nested `{}` pairs, it is not
planned to contain `:syn-region` definitions for them.

> > The current recognition [strategy](https://github.com/zzzyxwvut/vim/commit/74e4fc0c9dcd08c39539f22c29d896b2ba446d72) for the tag is to look for
> > the `{@snippet\>` pattern in `start` etc.
> > [...]
>
> Not clear why this is so complicated.  Is it trying to match the right
> "}" by looking at what follows?  That doesn't seem right, it should
> have a contained region matching {} items.  It looks like we can assume
> that contained {} items are balanced.  If not, then that could be
> considered an error.

That is a nudge in the right direction. The thing that led
me astray into poking about the trailing context of a tag
was that I have overlooked that whether or not the nested `{}`
pairs require recognition, these pairs can still be elbowed
out with an explicit region definition.

These definitions should suffice, without any new extension:
```vim
syntax region javaSkipBlock contained transparent
    \ start="{\%(@snippet\>\)\@!"
    \ end="}"
    \ contains=javaSkipBlock,javaCommentMarkupTag
syntax region javaDocSnippetTag contained
    \ start="{@snippet\>"
    \ end="}"
    \ contains=javaSkipBlock,javaDocSnippetTagAttr,javaCommentMarkupTag
```

**Comment by brammool** [comment]
> > It's not clear yet what the problems are.  Yes, it would be possible to
> > add a new RE element that calls a function.  But that's complicated and
> > needs very good justification.  I would suggest that, instead of diving
> > into the details of a solution, first clearly describe what items you
> > are struggling with to match with the current syntax engine.
> 
> There _was_ a problem with describing a grammar (`:syn-region`)
> that would correctly match the outermost balanced braces `{}`
> of a ***@***.*** . . .}` tag, for it may include other pairs
> of balanced braces, which may further nest other pairs. This
> tag may span across multiple lines. However, it would send
> one on a fool's errand should contained regions be tailored
> to _any_ language. Firstly, after all, these snippets may be
> written in plain text, or in a non-`Java` language, etc.; and
> secondly, by its nature, snippets written in a programming
> language tend to be loosely formed, explicitly omitting some
> syntactical parts, scattering ellipses here and there, which
> would likely be marked as syntax errors and draw attention.
> So the goal is to only brush by these nested braces seeking
> the outermost right brace and uniformly colour a snippet,
> only highlighting its attributes and additional markup tags.

The specification says:

The content of an inline snippet can only contain balanced pairs of
curly-brace characters. The overall inline tag is terminated by the
first right brace that matches the opening brace. This restriction
applies to all inline tags; it is not specific to the @snippet tag.

That's apparently what they wanted to use.  I would have picked
something else, since matching {} is easily done wrong.  Something like
***@***.*** ...  @snippet}.  Previously <pre> ... </pre> was used.

> > Not clear why this is so complicated.  Is it trying to match the right
> > "}" by looking at what follows?  That doesn't seem right, it should
> > have a contained region matching {} items.  It looks like we can assume
> > that contained {} items are balanced.  If not, then that could be
> > considered an error.
> 
> That is a nudge in the right direction. The thing that led
> me astray into poking about the trailing context of a tag
> was that I have overlooked that whether or not the nested `{}`
> pairs require recognition, these pairs can still be elbowed
> out with an explicit region definition.
> 
> These definitions should suffice, without any new extension:
> ```vim
> syntax region javaSkipBlock contained transparent
>     \ ***@***.***\>\)\@!"
>     \ end="}"
>     \ contains=javaSkipBlock,javaCommentMarkupTag
> syntax region javaDocSnippetTag contained
>     \ ***@***.***\>"
>     \ end="}"
>     \ contains=javaSkipBlock,javaDocSnippetTagAttr,javaCommentMarkupTag
> ```

For the region it's sufficient to match pairs of {}, but having some
items highlighted is a bonus.

-- 
hundred-and-one symptoms of being an internet addict:
177. You log off of your system because it's time to go to work.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by egberts** [comment]
Someone mentioned TextMate and Vim in this issue, well ... there it is, a rough go at it (but not by me):  https://github.com/icedman/vim-textmate
