### ISSUE TITLE
Confused about the interaction between `guioptions=a` and the "black hole" register

### ISSUE THREAD

**Issue by matteocoder** [vim/vim#11210]
### Steps to reproduce

Prerequisites: have a `./gvimrc` with just `guioptions=a`, then start gvim with the flags `-u NONE -U ./gvimrc`.
Make sure that your clipboard contains a random string such as "foobar"

1. Open a new file and write
```
not copied
copied
```
2. Visually select the first line, then type `"_d`
3. Visually select the remaining line, then type `d`
4. Check the contents of the registers using `:registers`

### Expected behaviour

According to the manual, the "a" `guioption` forces visually selected text to be copied to the system clipboard when gvim is in visual mode. Currently this option seems to override the insertion into the "black hole" register, thus the "not copied" string is in the `"*` register, even if we do not want it to be there. Is this the intended behaviour?

### Version of Vim

9.0.500

### Environment

Gvim, Windows 10.0.19044

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> Prerequisites: have a `./gvimrc` with just `guioptions=a`, then start gvim with the flags `-u NONE -U ./gvimrc`.
> Make sure that your clipboard contains a random string such as "foobar"
> 
> 1. Open a new file and write
> ```
> not copied
> copied
> ```
> 2. Visually select the first line, then type `"_d`
> 3. Visually select the remaining line, then type `d`
> 4. Check the contents of the registers using `:registers`
> 
> ### Expected behaviour
> 
> According to the manual, the "a" `guioption` forces visually selected
> text to be copied to the system clipboard when gvim is in visual mode.
> Currently this option seems to override the insertion into the "black
> hole" register, thus the "not copied" string is in the `"*` register,
> even if we do not want it to be there. Is this the intended behaviour?

The selection is set when you make the Visual selection.  What operation
you perform with it is irrelevant.

If you don't want the Visual selection change the clipboard or selection
(both exist on X11 systems, not on MS-Windows) then change the "a" flag
in 'guioptions'.  See ":help go-A" for other flags.

For the terminal version the 'clipboard' option is used.

-- 
hundred-and-one symptoms of being an internet addict:
154. You fondle your mouse.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by matteocoder** [comment]
@brammool Thanks for clarifying that, for my intended use the `clipboard` option seems to be the better choice.
