### ISSUE TITLE
`matchaddpos()` increase number of positions from 8 to unlimited

### ISSUE THREAD

**Issue by noscript** [vim/vim#11248]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

Currently `matchaddpos()` accepts maximum 8 positions at once. If a user wants to add more that 8 matches, those has to be split them into groups of 8 and `matchaddpos()` needs to be called for each group. This is inconvenient.

**Describe the solution you'd like**
Allow unlimited number of positions.

**Describe alternatives you've considered**
Using loop to call `matchaddpos()` multiple times.

**Comment by brammool** [comment]
> **Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
> 
> Currently `matchaddpos()` accepts maximum 8 positions at once. If a user wants to add more that 8 matches, those has to be split them into groups of 8 and `matchaddpos()` needs to be called for each group. This is inconvenient.
> 
> **Describe the solution you'd like**
> Allow unlimited number of positions.
> 
> **Describe alternatives you've considered**
> Using loop to call `matchaddpos()` multiple times.

Yeah, that number eight is rather arbitrary.  Let's see if we can
allocated the array.

-- 
hundred-and-one symptoms of being an internet addict:
217. Your sex life has drastically improved...so what if it's only cyber-sex!

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by noscript** [comment]
Thank you!!!
