### ISSUE TITLE
configure: error: failed to compile test program.

### ISSUE THREAD

**Issue by Un1q32** [vim/vim#11246]
wasnt sure where to go for support so if theres a better place like a discord or something lmk

### Steps to reproduce

cross compile

i used [this](https://github.com/tpoechtrager/cctools-port) toolchain

configure command: `vim_cv_toupper_broken="set" vim_cv_terminfo="set" ./configure --host=arm-apple-darwin11 --with-tlib=ncurses`

### Expected behaviour

normal build

### Version of Vim

9.0.0618

### Environment

arch linux under wsl on windows 11
windows terminal
$TERM=xterm-256color
zsh 5.9

### Logs and stack traces

checking what tgetent() returns for an unknown terminal... configure: error: failed to compile test program.

**Comment by lacygoill** [comment]
What's the contents of the file `./src/auto/config.log`?

**Comment by OldWorldOrdr** [comment]
@lacygoill 
[config.log](https://github.com/vim/vim/files/9668316/config.log)

**Comment by lacygoill** [comment]
Issue https://github.com/vim/vim/issues/2058 seems similar.

Does replacing `--with-tlib=ncurses` with `--with-tlib=tinfo` help?

   > I found the same issue when compile the vim as well. Here is my solution:
> --with-tlib=ncurses should replace by --with-tlib=tinfo . libtinfo was generated from ncurses when you add the --with-termlib whilecompiling ncurse

[source](https://github.com/vim/vim/issues/2058#issuecomment-379139527)

---

Alternatively, does setting `vim_cv_tgetent` to `zero` help?

    vim_cv_tgetent=zero

   > I have experienced the same issue while building Vim 8.1 through Yocto/OE recipe as well as for Buildroot. The solution was to add:
   >
   >      vim_cv_tgetent=zero

[source](https://github.com/vim/vim/issues/2058#issuecomment-401863473)

**Comment by OldWorldOrdr** [comment]
vim_cv_tgetent=zero worked

the final configure command was:
`vim_cv_memcpy_handles_overlap=set vim_cv_bcopy_handles_overlap=set vim_cv_memmove_handles_overlap=set vim_cv_stat_ignores_slash=set vim_cv_timer_create=set vim_cv_getcwd_broken=set vim_cv_toupper_broken="set" vim_cv_terminfo="set" vim_cv_tgetent=zero ./configure --host=arm-apple-darwin11 --with-tlib=ncurses`
