### ISSUE TITLE
Programmatic <CR> in command line triggers "HIT RETURN" prompt for lines longer than v:echospace

### ISSUE THREAD

**Issue by resolritter** [vim/vim#11250]
### Steps to reproduce

The following command creates a command line larger than `v:echospace` characters and immediately executes it

`vim --clean -c 'call feedkeys("aa\<esc>:s/a/" . repeat(" ", v:echospace + 1) . "\<CR>")'`

### Expected behaviour

When the command line is executed with `"\<CR>"` from `feedkeys`, the user receives a `Press ENTER or type command to continue` prompt.

If instead of feeding `"\<CR>"` programmatically, instead they input `Return` manually via the keyboard, the `Press ENTER or type command to continue` prompt is not shown.

i.e. the programmatic `"\<CR>"` behaves differently from the manual `Return`, but their behavior should be the same.

### Version of Vim

Compiled from fc06cda8379031890ee8852cdca61eb8af8e1ba2 with `make`

### Environment

```shell
$ lsb_release -a
LSB Version:	n/a
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a

$ uname -a
Linux user 5.19.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 25 Aug 2022 17:31:12 +0000 x86_64 GNU/Linux
```

**Comment by chrisbra** [comment]
have you tried the 't' flag of `feedkeys()`?

**Comment by resolritter** [comment]
> have you tried the 't' flag of `feedkeys()`?

@chrisbra I didn't before opening the issue. The `'t'` flag would solve the problem I'm having with `"\<CR>"`, so thanks a lot.

Still, I don't know if the current behavior is expected. If it is, then feel free to close the issue.

**Comment by brammool** [comment]
This is expected behavior: If the user types the CR then there is no need to wait until the text put on the command line has been read.  If it is not typed then it's like displaying a message, which should be read before overwriting it.
