### ISSUE TITLE
Provides a way to finally set the option, avoid overwritten it by other plugin

### ISSUE THREAD

**Issue by someoneonsmile** [vim/vim#11255]
Provides a way to finally set the option, avoid overwritten it by other plugin

**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
 It is difficult to make config effect when some option overwritten by other plugin or some autocmd

**Describe the solution you'd like**
final set shiftwidth=4 or set$ shiftwidth=4

**Comment by Shougo** [comment]
Well, I know why the feature is needed.
Users don't want to be overwritten options values by plugins.
But it breaks existing plugins.

If plugins want to change the value?
Errors?  or it is ignored?

**Comment by someoneonsmile** [comment]
warning once? probably this shouldn't be provided

**Comment by someoneonsmile** [comment]
another option to control its behavior？set opt_final_overwite='error|ignore'
it may not make sense

**Comment by brammool** [comment]
> Provides a way to finally set the option, avoid overwritten it by other plugin
> 
> **Is your feature request about something that is currently impossible
> or hard to do? Please describe the problem.**
>  It is difficult to make config effect when some option overwritten by
>  other plugin or some autocmd
> 
> **Describe the solution you'd like**
> final set shiftwidth=4 or set$ shiftwidth=4

You do not mention the context. Is this a plugin you install once?  A
filetype plugin?

For a filetype plugin you can provide your own in "after" to override
what a standard filetype plugin has done.

Many plugins provide ways to configure them to your preferences.
Something like 'shiftwidth' is an obvious one.

Unless there is a very clear advantage, I don't think we should make
this more complicated.

-- 
You are Dead.  Do you wish to restart, load, or quit?

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by someoneonsmile** [comment]
sorry, in my case is some options value in my after/ftplugin user config, overwritten by plugin's autocmd

**Comment by someoneonsmile** [comment]
It can be done without this feature, but it's easier with this

**Comment by someoneonsmile** [comment]
another case is i want to change the value of formatoptions but it was set in many default ftplugin files

**Comment by habamax** [comment]
> another case is i want to change the value of formatoptions but it was set in many default ftplugin files

I use this autocmd to override what other ftplugins do:

```
    au Filetype * setl formatoptions-=cro
```

**Comment by someoneonsmile** [comment]
Thanks, that's what I did too, but I think it's more direct

**Comment by someoneonsmile** [comment]
I will turn it off if not necessary

**Comment by habamax** [comment]
I think this is more about ftplugin authors to not set options more than necessary.

**Comment by vim-ml** [comment]
Many vim users, myself included, learn about filetype plugins
and autocommands only in an effort to disable a filetype plugin's
behavior of overriding settings specified in _vimrc.

For example, my _vimrc contains the following autocmd:

autocmd FileType * setlocal iskeyword=@,48-57,_,192-255

Moreover, this autocmd must be the *last thing* done in _vimrc,
because, as I understand it, filetype plugins are themselves run
from autocommands, which means any autocmd defined after
this one could potentially override its intended effect.

It took time and some research to figure out all of this trickery.

The proposal in Issue #11255, or something similar, would have
provided a far simpler solution.

**Comment by ychin** [comment]
> The proposal in Issue #11255, or something similar, would have provided a far simpler solution.

Seems to me the solution should be to write better plugins and have Vim default ones have sensible ways to configure whether these options get set or not. A new feature to completely lock a setting is going to introduce a *lot* of knock-on effects in my opinion and it doesn't seem clear from the proposal what a failure to set an option leads to. It would at least require a new builtin function for plugin to query whether an option is settable or not so the plugin could branch off to do something else instead. There are also some options where a plugin absolutely has to set or it just won't work at all, and now all plugin authors have to think about the dozens of options they set and go through each of them to check whether they are settable or not.

**Comment by someoneonsmile** [comment]
My initial thought was as an escape mechanism when user-set options didn't take effect and it was difficult to track where they were overridden. Give control to the user

**Comment by someoneonsmile** [comment]
I think the feature is a way(choose) conflict is handled rather than caused by, the conflict was handled by overwriting silent before and this is freezing.

When a plugin option conflicts with a user option, failing because the option is frozen by user is the same for the plugin as failing because the option is overwritten by user. I agree that no conflict is better.

**Comment by someoneonsmile** [comment]
What I understand is that a plugin should be a good helper, but the control is yours

For example, renovation workers can renovate any room, but you can lock the rooms you don't want to renovate.

**Comment by chrisbra** [comment]
I believe you can also use an OptionSet autocommand, to enforce your personal options settings
