### ISSUE TITLE
vim.org should redirect to www.vim.org

### ISSUE THREAD

**Issue by ychin** [vim/vim#11259]
Currently, if you navigate to https://vim.org, nothing would show up. Instead, you have to go to https://www.vim.org. It's pretty common practice these days to do a redirect if the "www" version is the canonical one. E.g. if you navigate to https://google.com (or cloudflare.com, netflix.com, apple.com, etc), the raw domain does have a DNS entry, and the server will simply do an HTTP 301 redirect to https://www.google.com.

Probably not a high priority issue, but it could be a little disorienting to people when you just type "vim.org" in the browser and then nothing shows up.

**Comment by ychin** [comment]
Another example of a website that does this is https://gnu.org/software/emacs/ which redirects to https://www.gnu.org/software/emacs/. 😅

**Comment by brammool** [comment]
This has been mentioned several times, but the maintainer of the DNS records says it doesn't work.  I forgot the details.
Fortunately several browsers handle this if you type "vim.org".

**Comment by arp242** [comment]
> This has been mentioned several times, but the maintainer of the DNS records says it doesn't work. I forgot the details.
> Fortunately several browsers handle this if you type "vim.org".

Neither Firefox not Chromium on my system do this.

I'm pretty sure this can be made to work, one way or the other, even if it's just pointing vim.org to a simple HTML page with a meta refresh tag.

**Comment by errael** [comment]
> Neither Firefox not Chromium on my system do this.

Firefox(105) does, Chrome(105) doesn't on my system. Is there an option buried somewhere?

**Comment by ychin** [comment]
Hmm Firefox definitely didn't work for me before and now it seems to work. I have no idea why. I think it may depend on whether you have visited https://www.vim.org before.

**Comment by danawoodman** [comment]
Almost all DNS providers support this. At a minimum a redirect could be setup. This seems a weird thing to have broken for such a hugely popular project
![Screenshot 2023-10-17 at 11 46 08 AM](https://github.com/vim/vim/assets/157695/cb160b9e-c264-42ec-9459-f6f1ec1939d6)

**Comment by vim-ml** [comment]
On Sun, Oct 2, 2022 at 7:52 PM Martin Tournoij ***@***.***>
wrote:

> This has been mentioned several times, but the maintainer of the DNS
> records says it doesn't work. I forgot the details.
> Fortunately several browsers handle this if you type "vim.org".
>
> Neither Firefox not Chromium on my system do this.
>
> I'm pretty sure this can be made to work, one way or the other, even if
> it's just pointing vim.org to a simple HTML page with a meta refresh tag.
>
IIRC, on Firefox and SeaMonkey it is a preference. In SeaMonkey
2.53.18b1pre for Linux64 it is «Edit → Preferences → Browser → Location Bar
→ Unknown Locations → [x] Add "www." and ".com" to the location if a web
page is not found». In Firefox Nightly 120.0a1 I tried to find it but
couldn't; but after typing vim.org followed by <Enter> in the Location bar
it said:

We can’t connect to the server at vim.org. Did you mean to go to www.vim.org
?

so it is just one click to get to the Vim homepage.

Best regards,
Tony.

**Comment by ychin** [comment]
From the vim_dev mailing list, there's an effort to build a new website anyway, so this should hopefully be fixed as part of that effort. This should really be fixed at the DNS / server configuration level instead of relying on browser behaviors.

https://groups.google.com/g/vim_announce/c/cUzmP2xxecM/m/tEht7Pz5HAAJ

**Comment by danawoodman** [comment]
I can recommend DNSimple (not affiliated) as a cheap and flexible provider that supports "alias" records that will handle the redirects for you.
