### ISSUE TITLE
smoothscroll bug: scrolloff=0 causes cursor to jump out of buffer's window

### ISSUE THREAD

**Issue by ychin** [vim/vim#11269]
### Steps to reproduce

1. `vim --clean -c "set smoothscroll" -c "set wrap" -c "set scrolloff=0"`
2. Make 101 long lines of wrapped texts by doing: `100i`, `testing `, `<Esc>`, then `yy100P`.
3. Keep pressing `j` to move cursor down by 1.

Note that the cursor will eventually jump out of the buffer and goes all the way down to where the command line is 

### Expected behaviour

The cursor should stay within bounds of the windows' buffer.

One thing interesting I noticed even for existing Vim behavior without having `smoothscroll` set: seems like `scrolloff=0` doesn't quite work that way I expect when `wrap` is on. Pressing `L` or using `j` to go all the way down always leaves a gap at the bottom when I have `wrap` on. Maybe that discrepancy is why this bug occurs. 

### Version of Vim

9.0.0654

### Environment

macOS 12.6, default Terminal.

**Comment by habamax** [comment]
https://asciinema.org/a/FdyArges52HpQrfonCuCpw0qS

PS, `M` and `L` indeed works unexpectedly, with `M` cursor is not in the middle, and `L` is not on the last line: https://asciinema.org/a/sHs2P6aKVmGQ2scKWEYQTduel
