### ISSUE TITLE
gvim can scroll upwards past line 1

### ISSUE THREAD

**Issue by basilisk0315** [vim/vim#11261]
### Steps to reproduce

1. gvim -Nu NONE
2. Turn on line numbers (this makes the issue easier to see).
3. Enter/paste some text.
![image](https://user-images.githubusercontent.com/54644368/193489341-6db93ab5-c3ad-40e1-baaa-696058ee6a7b.png)

4. With the cursor on line 1, either press ctrl-y (or in gvim scroll the mouse wheel upwards).
![image](https://user-images.githubusercontent.com/54644368/193489413-5d68f3d5-d77b-4c42-97d5-18f8a051d351.png)

5. With continued pressing of ctrl-y or scrolling the mouse wheel upwards, the buffer continues to scroll the view upwards with line 1 being repeated.
![image](https://user-images.githubusercontent.com/54644368/193489441-66da8930-63d8-48cf-b8c9-cd7147cfddf5.png)

### Expected behaviour

The buffer should not scroll because the cursor is on line 1.

### Version of Vim

9.0.0643

### Environment

Windows 8.1 x64
gvim.exe built using mingw64 (gcc 12.2.0)

**Comment by ychin** [comment]
I don't think this is a Gvim bug. I can see this in terminal Vim as well and is caused by the recent `smoothscoll` changes. (This bug happens when the new option `smoothscroll` is not set)

**Comment by brammool** [comment]
John Marriott wrote:

> ### Steps to reproduce
> 
> 1. gvim -Nu NONE
> 2. Turn on line numbers (this makes the issue easier to see).
> 3. Enter/paste some text.
> ![image](https://user-images.githubusercontent.com/54644368/193489341-6db93ab5-c3ad-40e1-baaa-696058ee6a7b.png)
> 
> 4. With the cursor on line 1, either press ctrl-y (or in gvim scroll the mouse wheel upwards).
> ![image](https://user-images.githubusercontent.com/54644368/193489413-5d68f3d5-d77b-4c42-97d5-18f8a051d351.png)
> 
> 5. With continued pressing of ctrl-y or scrolling the mouse wheel upwards, the buffer continues to scroll the view upwards with line 1 being repeated.
> ![image](https://user-images.githubusercontent.com/54644368/193489441-66da8930-63d8-48cf-b8c9-cd7147cfddf5.png)
> 
> 
> ### Expected behaviour
> 
> The buffer should not scroll because the cursor is on line 1.

Apparently there was no test for this.  I'll fix it and add a test.

-- 
If VIM were a woman, I'd marry her.  Slim, organized, helpful
and beautiful; what's not to like?     --David A. Rogers

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
It's sorted now. Thanks😎
