### ISSUE TITLE
Error detected while compiling function SetSyn: Line 8:

### ISSUE THREAD

**Issue by AndrewMarais** [vim/vim#11278]
###GVIM Windows V9.0 64-bit GUI with OLE support

#### This is an issue when clicking on the GUI Menu:
When Clicking on Syntax menu and then show
Then Clicking on Syntax menu again and any Syntax type, you receive an error

Error detected while compiling function SetSyn: 
Line 8:
Missing double quote: " do not replace the filetype but add whitespace on top
Missing double quote: " do not replace the filetype but add whitespace on top

**Comment by brammool** [comment]
> ###GVIM Windows V9.0 64-bit GUI with OLE support
> 
> #### This is an issue when clicking on the GUI Menu:
> When Clicking on Syntax menu and then show
> Then Clicking on Syntax menu again and any Syntax type, you receive an error
> 
> Error detected while compiling function SetSyn: 
> Line 8:
> Missing double quote: " do not replace the filetype but add whitespace on top
> Missing double quote: " do not replace the filetype but add whitespace on top

This must have been broken for three months...
I suppose nobody uses the syntax menu.

-- 
"Time flies like an arrow".  So I put an arrow on my desk, now
awaiting one of these time flies showing up.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by AndrewMarais** [comment]
Or people don't know how to log it in Git or use Git.

I use it when opening 1Gb log files with content ranging from XML, CSV and
JSON in the same file and switch between until I get the most useful
highlight for the information that will solve the problem I'm fixing.

Thanks for fixing,
Much appreciated
