### ISSUE TITLE
Gvim Windows, scroll up bug.

### ISSUE THREAD

**Issue by Stolas** [vim/vim#11289]
### Steps to reproduce

1. Open (lastest) gvim on MS Windows.
2. Add text to the first line.
3. Scroll up, using the mouse wheel.
4. The first line is written again and again and the error `E38: Nul argument` appears. 
5. Note, this did not happen with older versions prior to vim 9.

### Expected behaviour

Stop at the top line of the file.

### Version of Vim

9.0

### Environment

MS-Windows 64-bit GUI version.
Pre-build from github.

### Logs and stack traces

```shell
No errors / exceptions / messages noted when hooking windbg.
```

**Comment by k-takata** [comment]
> Version of Vim
> 9.0

What patch level do you use?

**Comment by brammool** [comment]
This was broken from patch 9.0.0640   until patch 9.0.0645    Is your Vim in that range?

**Comment by Stolas** [comment]
I used 0000
but I was to quick with reporting, latest has this fixed.

Sorry for the confusion.
