### ISSUE TITLE
cursor drawn on command-line when 'smoothscroll' is enabled

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#11288]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        &smoothscroll = true
        &wrap = true
        &lines = 24
        vsplit
        var text: string = 'the quick brown fox jumps over the lazy dog '
        [text->repeat(&columns / text->strcharlen() + 1)]->repeat(&lines)->setline(1)
        feedkeys('j'->repeat(&lines), 'xnt')
    EOF
    )

The cursor is drawn on the command-line, below the statusline .

**Expected behavior**

The cursor is drawn on the last line of the buffer, above the statusline.

**Version of Vim**

9.0 Included patches: 1-662

**Environment**

Operating system: Ubuntu 20.04.5 LTS
Terminal: XTerm(353)
Value of $TERM: xterm-256color
Shell: GNU bash, version 5.0.17

**Gif**

![gif](https://user-images.githubusercontent.com/8505073/193996441-05a66f0e-163e-48e9-abcd-10dc6bbc83dd.gif)

**Additional context**

The issue disappears if we reset `'smoothscroll'`.

---

The issue seems to be influenced by `&lines`.  For example, I can't reproduce when `&lines = 10`; but I can when `&lines = 24`.

**Comment by brammool** [comment]
I tried this and a few variants, but I cannot reproduce.

**Comment by lacygoill** [comment]
I'm on 9.0.669 and I can still reliably reproduce.  But as mentioned earlier, it depends on the number of lines.  For me, it works with 24 lines.

I wonder whether the font size also affects the issue.  I can reproduce in xterm, with no config:

    $ xrdb /dev/null
    $ xterm
    $ HOME=/tmp vim -Nu NONE -i NONE -U NONE -S <(tee <<'EOF'
        vim9script
        &smoothscroll = true
        &wrap = true
        &lines = 24
        vsplit
        var text: string = 'the quick brown fox jumps over the lazy dog '
        [text->repeat(&columns / text->strcharlen() + 1)]->repeat(&lines)->setline(1)
        feedkeys('j'->repeat(&lines), 'xnt')
    EOF
    )

I press `C-X C-E` in xterm to paste the last multiline shell command inside a Vim buffer, then `ZZ` to run it.

**Comment by lacygoill** [comment]
Also, if we maintain `l` pressed, the cursor:

   - moves forward till the vertical bar
   - gets back to the beginning
   - moves forward till the vertical bar again
   - moves 8 cells forward (and stops there)

That's with `&columns = 80`.  With `&columns = 100`, something similar happens; the cursor:

   - moves forward till the vertical bar
   - gets back to the beginning
   - moves forward till the vertical bar again
   - moves 32 cells forward (and stops there)

**Comment by lacygoill** [comment]
![gif](https://user-images.githubusercontent.com/8505073/194184573-b36f1692-ffb9-4370-8d77-88580fa67e9a.gif)

**Comment by brammool** [comment]
I expect this to be fixed by patch 9.0.0671, please check.

**Comment by lacygoill** [comment]
Yes, it is fixed as of Vim 9.0.0676, so closing.
