### ISSUE TITLE
where is command line now?

### ISSUE THREAD

**Issue by Shane-XB-Qian** [vim/vim#11295]
### Steps to reproduce

vim --clean -c 'set ruler'
// pls check the bottom of the window, where is the command line now?

![image](https://user-images.githubusercontent.com/13550529/194218610-88a6025a-0b88-40fd-9b92-c79837be5ead.png)

### Expected behaviour

a regression, the cmd line lost, wish be back soon.

### Version of Vim

v9.0.669

### Environment

linux 
xfce-term

**Comment by zeertzjq** [comment]
What's wrong? Everything seems fine.

**Comment by Shane-XB-Qian** [comment]
cmd line should be under 'ruler' (stl) line when cmdheight is 1 (which is default).
but now it is same line.

**Comment by zeertzjq** [comment]
That depends on the value of `'laststatus'`.

**Comment by habamax** [comment]
> cmd line should be under 'ruler' (stl) line when cmdheight is 1 (which is default). but now it is same line.

`ruler` combines the cmdline and statusline-like info into a single line. So it looks ok for me.

```
... 
If a window has a status line, the
ruler is shown there.  Otherwise it is shown in the last line of the
screen.
...
```

**Comment by Shane-XB-Qian** [comment]
vi --clean -c "set stl=fooooooooooooooooooooo" -c "set ls=2" -c 'set stal=2' -c 'set cmdheight=1'
![image](https://user-images.githubusercontent.com/13550529/194224347-e80bb769-ce8e-44a0-90d4-5d7f9bf5f6c6.png)
