### ISSUE TITLE
timer_start() redraws command line

### ISSUE THREAD

**Issue by noscript** [vim/vim#11299]
### Steps to reproduce

1. Create `~/test.vim`:
```vim
vim9script

def g:MyFunc()
  echo 'hello'
  echo 'world'
  input("Coffee or beer? ")
enddef

timer_start(0, (_) => g:MyFunc())
```
2. Run vim:
`vim -g --clean +'so ~/test.vim'`
3. Vim draws:
![image](https://user-images.githubusercontent.com/717109/194392830-cca41745-848d-4cd5-8afd-05c558f84fe8.png)
echoed lines before `input()` call are not visible.

### Expected behaviour

Expected:
![image](https://user-images.githubusercontent.com/717109/194393069-a88e14cc-96f8-4bd2-81d2-b7fcffd7e997.png)

### Version of Vim

9.0.0659

### Environment

OS: Debian 11
Terminal: GUI

**Comment by lacygoill** [comment]
This looks similar to https://github.com/vim/vim/issues/836 and https://github.com/vim/vim/issues/7451

**Comment by chrisbra** [comment]
I agree, looks like a duplicate of those issues. Can we close it?

**Comment by noscript** [comment]
Yes, it looks like a duplicate.

**Comment by noscript** [comment]
I found a case where I it would not redraw, but it's not a complete workaround as I cannot figure out, how to pass arguments to the function. Nevertheless, I wounder why this works:
```vim
vim9script

def MyFunc(timer_id: number)
  # it is important, that this defined as nested function:
  def F()
    echo 'hello'
    echo 'world'
    input("Coffee or beer? ")
  enddef
  F()
enddef

# timer set to 1 second, to make sure it's an async call and not a fluke
timer_start(1000, MyFunc)

# this however does not work:
#var MyFunc2 = function(MyFunc, [])
#timer_start(1000, MyFunc2)
```

**Comment by lacygoill** [comment]
It doesn't work for me.  OTOH, this does:
```vim
vim9script
def Func(_)
    echowindow 'hello'
    echowindow 'world'
    redraw
    input('Coffee or beer? ')
enddef
timer_start(1'000, Func)
```

**Comment by noscript** [comment]
> It doesn't work for me.

Hm, that's strange.

>OTOH, this does:

`echowindow` in my case is not useful as the message disappears.

**Comment by lacygoill** [comment]
> Hm, that's strange.

At least I can't read "hello", nor "window":

![gif](https://user-images.githubusercontent.com/8505073/194523710-55ff87f1-440b-45cd-acd8-3b81c0932b07.gif)

**Comment by noscript** [comment]
Same for me, it doesn't work in terminal. But it works in GUI Vim.

**Comment by brammool** [comment]
> It doesn't work for me.  OTOH, this does:
> ```vim
> vim9script
> def Func(_)
>     echowindow 'hello'
>     echowindow 'world'
>     redraw
>     input('Coffee or beer? ')
> enddef
> timer_start(1'000, Func)
> ```

This is probably the best solution, using existing functionality instead
of hacking something else.

What is missing here is that the message window popup may disappear too
soon.  I have been thinking of adding a count, indicating the number of
seconds the window should stay up.  Here we could use a large number to
keep it up for a long time.

But then it would stay visible too long, thus we also need a way to hide
it.  Adding a function to get the window ID of the message window is
useful, like we can do this for the preview window.

Then this should work:

 ```vim
 vim9script
 def Func(_)
     echowindow 'hello'
     :999echowindow 'world'
     redraw
     input('Coffee or beer? ')
     popup_hide(popup_findecho())
 enddef
 timer_start(1'000, Func)
 ```

-- 
Eight Megabytes And Continually Swapping.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by noscript** [comment]
`echowindow` does not supports `echohl` so it's not a good workaround.

**Comment by chrisbra** [comment]
It sounds like one want to create your own custom message popup window so?

**Comment by noscript** [comment]
Yes, it's possible to mimic the behavior with popups, however will be a lot of code and not as concise as using a few echos. Especially, if you already rely on`echo` and only want to display a few extra lines.

The problem with `echo` is that it cannot be used asynchronously. If only there was way to block redraw with something like `:redrawstop` / `:redrawcont`.

**Comment by brammool** [comment]
> `echowindow` does not supports `echohl` so it's not a good workaround.

Echo'ing a message from a timer is already a corner case, also requiring
it to be highlighted is turning this in a corner case of a corner case.
You can't have everything...

-- 
   An extraordinary TALL KNIGHT in all black (possibly John with Mike on his
   shoulders) walks out from the dark trees.  He is extremely fierce and
   gruesome countenance.  He walks towards KING ARTHUR and PATSY, who are
   wazzing like mad.  (Salopian slang, meaning very scared.  almost to the
   point of wetting oneself, e.g. before an important football match or
   prior to a postering.  Salopian slang meaning a beating by the school
   praeposters.  Sorry about the Salopian slant to this stage direction - Ed.)
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> I have been thinking of adding a count, indicating the number of
   > seconds the window should stay up.

Sometimes, using `-1` as a count causes the popup to be displayed forever:

    $ vim +'help :echowindow' +':-1 echowindow "test"'
    # the popup stays visible forever

But not always:

    $ vim +'help' +':-1 echowindow "test"'
    # the popup stays visible for 1 second only

---

Sometimes, `-1` gives an unexpected error:

    $ vim +':-1 echowindow "test"'
    E16: Invalid range: :-1 echowindow "test"

---

   > Here we could use a large number to
   > keep it up for a long time.

IMO, we should use `-1` to mean "forever".  Just like we do in the `{repeat: -1}` argument of `timer_start()`.

**Comment by lacygoill** [comment]
Actually, `-1` is subtracted from the current line address.  Maybe we should change the semantics of the range.  Although, I don't see a good fit at [`:help :command-addr`](https://vimhelp.org/map.txt.html#%3Acommand-addr).

**Comment by brammool** [comment]
>    > I have been thinking of adding a count, indicating the number of
>    > seconds the window should stay up.
> 
> Sometimes, using `-1` as a count causes the popup to be displayed forever:
> 
>     $ vim +'help :echowindow' +':-1 echowindow "test"'
>     # the popup stays visible forever
> 
> But not always:
> 
>     $ vim +'help' +':-1 echowindow "test"'
>     # the popup stays visible for 1 second only
> 
> ---
> 
> Sometimes, `-1` gives an unexpected error:
> 
>     $ vim +':-1 echowindow "test"'
>     E16: Invalid range: :-1 echowindow "test"
> 
> ---
> 
>    > Here we could use a large number to
>    > keep it up for a long time.
> 
> IMO, we should use `-1` to mean "forever".  Just like we do in the
> `{repeat: -1}` argument of `timer_start()`.

Currently "-1" means the same as ".-1", current line number minus one.
It would require introducing a new address type to support a -1 count.
That indicates it's rather unusual.

Using ":999echowin" isn't too bad, is it?  Using "-1" is a bit obscure.

-- 
Not too long ago, compress was something you did to garbage...

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
Sergey Vlasov wrote:

> ### Steps to reproduce
> 
> 1. Create `~/test.vim`:
> ```vim
> vim9script
> 
> def g:MyFunc()
>   echo 'hello'
>   echo 'world'
>   input("Coffee or beer? ")
> enddef
> 
> timer_start(0, (_) => g:MyFunc())
> ```
> 2. Run vim:
> `vim -g --clean +'so ~/test.vim'`
> 3. Vim draws:
> ![image](https://user-images.githubusercontent.com/717109/194392830-cca41745-848d-4cd5-8afd-05c558f84fe8.png)
> echoed lines before `input()` call are not visible.
> 
> ### Expected behaviour
> 
> Expected:
> ![image](https://user-images.githubusercontent.com/717109/194393069-a88e14cc-96f8-4bd2-81d2-b7fcffd7e997.png)

Well, a timer callback can be called any moment and output might
interfere with what the user is now doing.  Requesting input is strange,
the user suddenly has to type something else.

What happens is that the messages overwrite each other, and the prompt
for input() as well.  There is no easy way to avoid that.

It would also cause the screen to scroll up.  You can now use :echowin
to avoid that, but the messages then only show after input() returns.
Perhaps that can be changed to show when using input().  It will
disappear after three seconds though.  Would that even be useful?

-- 
A successful man is one who makes more money than his wife can spend.
A successful woman is one who can find such a man.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by noscript** [comment]
> Well, a timer callback can be called any moment and output might
interfere with what the user is now doing.  Requesting input is strange,
the user suddenly has to type something else.

There are plugins that fire a lot messages all the time and those plugins rely on the current behavior that doesn't interrupt user from typing. I understand that removing message overwrite would break backward compatibility.

However, if a developer wants to show multiple messages asynchronously, the new `999echow` solution is not that elegant. There are problems with `echow` when comparing to `echo`:
- popup messages look different (top border + Warning highlight, no way to customize easily)
- they act different (click will hide them, no way to customize easily)
- there is a finite time after which messages will disappear (no way to customize easily)
- it is not possible to have a REPL workflow, where a user is supposed to answer a series of questions, previois `input()` prompts will be overwritten.

Thank you anyway for `999echow` implementation. As I said previously, it is totally possible to re-implement prompts with popups. But it is frustrating to re-implement something that already works, just to be able to call it asynchronously. And there are such cases which cannot be synchronous:
 - when closing a popup dialog
 - when using jobs to receiving a response from a server or external command
