### ISSUE TITLE
Very weird and peculiar cosmetic bug with cursor temporarily jumping away from current position

### ISSUE THREAD

**Issue by Aster89** [vim/vim#11309]
### Steps to reproduce

Sorry but this is a very very very strange bug. On the other hand, it looks like it's just a cosmetic bug that can be ignored.

1. Open a terminal that can fit 125 characters (assuming `bash`, `echo $COLUMNS` has to output 125)
1. Open a new file with `vim -u NONE`;
2. Fill it via <kbd>I</kbd><kbd>Space</kbd><kbd>a</kbd><kbd>Escape</kbd><kbd>2</kbd><kbd>2</kbd><kbd>g</kbd><kbd>I</kbd><kbd>a</kbd><kbd>Escape</kbd><kbd>I</kbd><kbd>Space</kbd><kbd>Escape</kbd><kbd>1</kbd><kbd>1</kbd><kbd>5</kbd><kbd>g</kbd><kbd>I</kbd><kbd>a</kbd><kbd>Escape</kbd>, i.e. the text `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaa a`;
3. apply the following: `set noshowmode`, `set linebreak`, `set showcmd`;
4. Hit <kbd>$</kbd><kbd>v</kbd><kbd>$</kbd><kbd>s</kbd>

Observe the strange cursor position.

Now if you hit, say <kbd>i</kbd>, the cursor will jump to the correct position and the letter will be inserted where it is meant to be.

Below is the screencast:
[![asciicast](https://asciinema.org/a/mJxQqbnAXTEjD2AYbqpqLND7o.svg)](https://asciinema.org/a/mJxQqbnAXTEjD2AYbqpqLND7o)

### Expected behaviour

No strange cursor jump.

### Version of Vim

9.0, patch 1-354

### Environment

Operating system: Archlinux (up-to-date)
Terminal: urxvt
Value of $TERM: rxvt-unicode-256color
Shell: bash

**Comment by lacygoill** [comment]
MRE:
```vim
vim9script
&linebreak = true
&showcmd = true
&showmode = false
('a'->repeat(&columns - 10) .. ' ' .. 'b'->repeat(10) .. ' c')->setline(1)
timer_start(10, (_) => feedkeys('$v$s', 'nt'))
```
Regression introduced in patch [8.2.4707](https://github.com/vim/vim/releases/tag/v8.2.4707)
Cc: @zeertzjq via https://github.com/vim/vim/pull/10105

**Comment by zeertzjq** [comment]
Hmm, it is strange that this only happens with `'showcmd'` enabled.

**Comment by zeertzjq** [comment]
So this fixes the problem:
```diff
diff --git a/src/edit.c b/src/edit.c
index ab268c185..9fd0c9732 100644
--- a/src/edit.c
+++ b/src/edit.c
@@ -3701,9 +3701,8 @@ ins_esc(
 
     State = MODE_NORMAL;
     may_trigger_modechanged();
-    // need to position cursor again when on a TAB
-    if (gchar_cursor() == TAB)
-	curwin->w_valid &= ~(VALID_WROW|VALID_WCOL|VALID_VIRTCOL);
+    // need to position cursor again (e.g. when on a TAB )
+    changed_cline_bef_curs();
 
     setmouse();
 #ifdef CURSOR_SHAPE
```

Not sure why though.

**Comment by zeertzjq** [comment]
I think the actual problem here is that virtcol is not invalidated when `'linebreak'` is restored to its original value in operator code.

**Comment by zeertzjq** [comment]
I think the actual problem here is that virtcol is not invalidated when `'linebreak'` is restored to its original value in operator code. It is only invalidated when `'linebreak'` is temporarily disabled, so `'showcmd'` may validate it and make it a wrong value.

**Comment by zeertzjq** [comment]
I just noticed that changing `'$v$s'` to `"$\<C-V>$I"` can also trigger the issue.

**Comment by zeertzjq** [comment]
Three similar changes in different places are needed for three different cases. I've create a PR #11311 with tests and fixes for three cases.
