### ISSUE TITLE
Closing a popup after stopping all timers causes segmentation fault

### ISSUE THREAD

**Issue by igbanam** [vim/vim#11301]
### Steps to reproduce

1. Save the seg-fault script in an accessible folder. I call mine `segfaulter.vm`
2. run `vim --clean +'so ./segfaulter.vim'`

**segfaulter.vim**
```vim
vim9script

def T1mHandler()
  echom 'Something'
enddef

# start a timer for a minute
var timer_1m = timer_start(60000, 'T1mHandler')

popup_create('Popup', {
  time: 10000
})

# simulate 2s delay
var timer_2s = timer_start(2000, (timer_id) => {
  timer_stopall()
  popup_clear()
})
```

### Expected behaviour

- all `popup` windows close
- all timers are stopped

*…instead…*

We get a seg-fault — **and** you may not be able to click into the terminal afterwards.

### Version of Vim

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Sep 01 2022 15:00:53)

### Environment

Operting system: OS X 12.6 on M1, 2020
Terminal: iTerm
Value of `$TERM`: xterm-256color-italic
Shell: ZSH

### Logs and stack traces

https://user-images.githubusercontent.com/390059/194448125-187a77ac-be03-4d94-bc9f-3a015cd5eb22.mov

**Comment by lacygoill** [comment]
- [backtrace](https://github.com/vim/vim/files/9730130/gdb.txt)
   - [ubsan log](https://github.com/vim/vim/files/9730131/ubsan.log)
   - [valgrind log](https://github.com/vim/vim/files/9730132/valgrind.log)

**Comment by igbanam** [comment]
How did you get this @lacygoill? I adde a video because I did not know how to get the backtrace and all

**Comment by lacygoill** [comment]
See the wiki:

   - [building an asan-enabled Vim](https://github.com/vim/vim/wiki/Debugging-Vim-Bugs#building-an-asan--enabled-vim)
   - [creating a GDB stack trace](https://github.com/vim/vim/wiki/Debugging-Vim-Bugs#creating-a-gdb-stack-trace)

Also, FWIW, here are some [fish shell snippets](https://github.com/lacygoill/config/blob/master/.local/share/navi/cheats/mine/vim.cheat) I use to get logs.
