### ISSUE TITLE
`E1256` occurs if in a function defined with `:def`, passing a sorter function gotten via `get()` to `sort()`

### ISSUE THREAD

**Issue by kg8m** [vim/vim#11316]
### Steps to reproduce

1. Create a sample `vimrc` as following:
   ```vim
   vim9script
   
   const ORIGINAL_LIST = [
     { name: "1" },
     { name: "2" },
     { name: "3" },
   ]
   
   def SorterFunc(lhs: dict<string>, rhs: dict<string>): number
     return lhs.name < rhs.name ? -1 : 1
   enddef
   
   def Run(): void
     final copied_list = copy(ORIGINAL_LIST)
     const Sorter = get({}, "unknown", SorterFunc)
   
     sort(copied_list, Sorter)
   
     echo string(copied_list)
   enddef
   
   Run()
   #=> Expected is [{'name': '1'}, {'name': '2'}, {'name': '3'}]
   #=> Actual is E1256: String or function required for argument 2
   ```
2. `vim --clean -S vimrc`
3. You will see `E1256: String or function required for argument 2`

### Expected behaviour

You will see `[{'name': '1'}, {'name': '2'}, {'name': '3'}]` at the step `3.`.

### Version of Vim

9.0.0700

### Environment

OS: macOS Monterey 12.6
Terminal: iTerm2 3.4.16
Value of $TERM: xterm-256color
Shell: zsh 5.9 (arm-apple-darwin21.3.0)

**Comment by bfrg** [comment]
If you add a type hint where you declare `Sorter` it works:
```vim
def Run(): void
  final copied_list = copy(ORIGINAL_LIST)
  const Sorter: func = get({}, "unknown", SorterFunc)
  sort(copied_list, Sorter)
  echo string(copied_list)
enddef
```

It doesn't have to be `func`. It could also be `any`:
```vim
def Run(): void
  final copied_list = copy(ORIGINAL_LIST)
  const Sorter: any = get({}, "unknown", SorterFunc)
  sort(copied_list, Sorter)
  echo string(copied_list)
enddef
```

**Comment by kg8m** [comment]
@bfrg 
Thanks for the comment. You are right. But I think that in this case the reference to `SorterFunc` should be type inferred and type hints should be optional.

**Comment by kg8m** [comment]
Note: The script works unless `get()` is used.

```vim
def Run(): void
  final copied_list = copy(ORIGINAL_LIST)
  const Sorter = SorterFunc

  sort(copied_list, Sorter)

  echo string(copied_list)
enddef

Run()
#=> [{'name': '1'}, {'name': '2'}, {'name': '3'}]
```

**Comment by kg8m** [comment]
Bram, thanks for the very very quick fix!

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> 1. Create a sample `vimrc` as following:
>    ```vim
>    vim9script
>    
>    const ORIGINAL_LIST = [
>      { name: "1" },
>      { name: "2" },
>      { name: "3" },
>    ]
>    
>    def SorterFunc(lhs: dict<string>, rhs: dict<string>): number
>      return lhs.name <# rhs.name ? -1 : 1
>    enddef
>    
>    def Run(): void
>      final copied_list = copy(ORIGINAL_LIST)
>      const Sorter = get({}, "unknown", SorterFunc)
>    
>      sort(copied_list, Sorter)
>    
>      echo string(copied_list)
>    enddef
>    
>    Run()
>    #=> Expected is [{'name': '1'}, {'name': '2'}, {'name': '3'}]
>    #=> Actual is E1256: String or function required for argument 2
>    ```
> 2. `vim --clean -S vimrc`
> 3. You will see `E1256: String or function required for argument 2`
> 
> ### Expected behaviour
> 
> You will see `[{'name': '1'}, {'name': '2'}, {'name': '3'}]` at the step `3.`.

This is a case of comparing the type with "any", but the actual type is
"const any".  They should be considered equal but they are not.

-- 
Proverb: A nightingale that forgets the lyrics is a hummingbird.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
