### ISSUE TITLE
capture err message when vim exiting

### ISSUE THREAD

**Issue by Shane-XB-Qian** [vim/vim#11317]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
i am trying to capture err message when vim exiting for debug purpose

**Describe the solution you'd like**
what i do currently is:
```vim
au vimleave * call writefile(split(execute('mess'), '\n')
```

**Describe alternatives you've considered**
but looks somehow sometime no all err message would be capture/wrote totally.
// i mean some err message just happening when vim exiting.
// some random err just happened while vim exiting occasionally.

**Additional context**
i am not sure if there were some better ways or if this was a bug..
if not, the feature request wish all err msg can be captured by this way or some others alternative.

**Comment by lacygoill** [comment]
> i am trying to capture err message when vim exiting for debug purpose
   > ...
   > if not, the feature request wish all err msg can be captured by this way or some others alternative.

Try this:

    :debug quitall!
    >step (or >next)

See:

   - [`:help :debug`](https://vimhelp.org/repeat.txt.html#%3Adebug)
   - [`:help >step`](https://vimhelp.org/repeat.txt.html#%3Estep)
   - [`:help >next`](https://vimhelp.org/repeat.txt.html#%3Enext)

**Comment by lacygoill** [comment]
Alternatively, try this:

    :set verbose=2 verbosefile=/tmp/log | quitall!

Then, read `/tmp/log`.  If there is not enough info, you can increase the verbosity level up to 20.

See:

   - [`:help 'verbose'`](https://vimhelp.org/options.txt.html#%27verbose%27)
   - [`:help 'verbosefile'`](https://vimhelp.org/options.txt.html#%27verbosefile%27)

**Comment by Shane-XB-Qian** [comment]
thx. 
but some err message just happening when vim exiting, it happened randomly or occasionally,
which meant it more like `log`, not `debug`. however, seems not all err msg (when exiting) would wrote into `mess` at that timing.

**Comment by lacygoill** [comment]
> it happened randomly or occasionally, which meant it more like log, not debug

Then an autocmd which increases the verbosity level and logs the messages into a file:

    autocmd VimLeavePre set verbose=2 verbosefile=/tmp/log

**Comment by lacygoill** [comment]
Here is an example to test:

    $ vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        delete('/tmp/log')
        autocmd VimLeavePre * set verbose=1 verbosefile=/tmp/log
        autocmd VimLeave * Error()
        def Error()
            silent! eval [][0]
        enddef
        quitall!
    EOF
    )

    $ grep '^E[0-9]\+:' /tmp/log
    E684: List index out of range: 0

Notice that the error was logged even though it was given after the options were set.

**Comment by Shane-XB-Qian** [comment]
ok, let me try `verbose=20` (not sure which value is proper so 20) if can get sth or not.
 

> even though it was given after the options were set.

that's ok, i just want the detail when just vim exiting, besides looks the verbose content would be very large (if 20).

**Comment by brammool** [comment]
> **Is your feature request about something that is currently impossible
> or hard to do? Please describe the problem.**
> i am trying to capture err message when vim exiting for debug purpose
> 
> **Describe the solution you'd like**
> what i do currently is:
> ```vim
> au vimleave * call writefile(split(execute('mess'), '\n')
> ```
> 
> **Describe alternatives you've considered**
> but looks somehow sometime no all err message would be capture/wrote
> totally.
> 
> **Additional context**
> i am not sure if there were some better ways or if this was a bug..
> if not, the feature request wish all err msg can be captured by this
> way or some others alternative.

It depends on why Vim is exiting.  I suppose you can't predict,
otherwise you could give a message there.

Have a look at ch_logfile().  It adds some overhead, but it might work
for your purpose.

-- 
A real patriot is the fellow who gets a parking ticket and rejoices
that the system works.


 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Shane-XB-Qian** [comment]
yes, just trying to find out some unpredictable err msg.
// guess should be good enough, i will try. closing this for now. thx.
