### ISSUE TITLE
setcursorcharpos(0, ...) seems to use byte offset sometimes, but setcursorcharpos(line('.'), ...) works as expected

### ISSUE THREAD

**Issue by hejohns** [vim/vim#11329]
### Steps to reproduce

this is a test
→ λ λyyp → λ λyyp
→ λ λyyp → λ λyyp

as a 3 line file.
On line 2, :call setcursorcharpos(0, 3)
puts the cursor on the first character

if you delete the first line, or replace it with a copy of the second line, it works as expected all of a sudden
(that is, setcursorcharpos(0, ...) behaves differently depending on other lines. I first discovered this bug when on a file I'm working on, setcursorcharpos(0, charcol('.')) would max out at column 61 if I ever went past)

### Expected behaviour

cursor ends up on the lambda, the third character

### Version of Vim

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Sep 30 2022 04:38:50) Included patches: 1-626

### Environment

Debian bookworm/sid
xfce4-terminal 1.0.4 (Xfce 4.16)
xterm-256color
GNU bash, version 5.2.0(1)-rc2 (x86_64-pc-linux-gnu)

**Comment by hejohns** [comment]
This may also be a bug in the documentation.
:help setcursorcharpos
says "same as cursor()"
:help cursor
says {lnum} is used like with getline()
but also says
if {lnum} is zero, the cursor will stay in the current line

but :help getline()
says that {lnum} smaller than 1 will return an empty string

**Comment by zeertzjq** [comment]
This also happens when the cursor is on the second line, and also applies to using a list.

Using two numbers:
```vim
call setline(1, ['this is a test', '→ λ λyyp → λ λyyp'])
normal! G$
call setcursorcharpos(0, 3)
```

Using a list:
```vim
call setline(1, ['this is a test', '→ λ λyyp → λ λyyp'])
normal! G$
call setcursorcharpos([0, 3])
```

**Comment by brammool** [comment]
> This may also be a bug in the documentation.
> :help setcursorcharpos
> says "same as cursor()"
> :help cursor
> says {lnum} is used like with getline()
> but also says
> if {lnum} is zero, the cursor will stay in the current line
> 
> but :help getline()
> says that {lnum} smaller than 1 will return an empty string

That part of the getline() usage of "lnum" does not apply to cursor().
Zero means that the line number doesn't change.
I'll change the help to make that clearer.

-- 
CUSTOMER:     Well, can you hang around a couple of minutes?  He won't be
              long.
MORTICIAN:    Naaah, I got to go on to Robinson's -- they've lost nine today.
CUSTOMER:     Well, when is your next round?
MORTICIAN:    Thursday.
DEAD PERSON:  I think I'll go for a walk.
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
