### ISSUE TITLE
Multiple virtual text `after` are displayed below each other and not in one line as they're supposed to

### ISSUE THREAD

**Issue by bfrg** [vim/vim#11336]
### Steps to reproduce

Run `vim --clean test.vim -S test.vim` with

```vim
vim9script

colorscheme habamax
prop_type_add('test', {highlight: 'Error'})

const opts: dict<any> = {
    type: 'test',
    text: range(50)->join(' '),
    text_align: 'after',
    text_padding_left: 2
}

prop_add(1, 0, opts)
prop_add(1, 0, opts)
prop_add(1, 0, opts)
```

Result:

![screenshot-2022-10-11_004528](https://user-images.githubusercontent.com/6266600/194971293-deb544d9-4767-4470-bf9b-5921b9e947fb.png)

### Expected behaviour

Since all three text-properties have `text_align` set to `after`, they should be displayed in one line.

### Version of Vim

9.0.718

### Environment

Linux

**Comment by brammool** [comment]
The props are displayed in one line, but the line wraps.  They are each truncated to fit in the current screenline.

An alternative would perhaps be to behave like "nowrap", but then some props may not show at all, and there is no way to see them.

Another alternative would be to truncate each shorter, so that they fit together in the one screen line.  However, they might get so short that the text is not useful.  Especially if the text line only leaves few columns for the props.

**Comment by bfrg** [comment]
Thanks for clarifying this. So the `text_wrap` attribute applies to the individual virtual text whereas `wrap` applies to consecutive virtual texts in the same line. Maybe this could be mentioned somewhere in the documentation.

I don't have an issue with the current behavior. But there seems to be a redrawing bug when `list` is enabled and `wrap` disabled.

Run the following code:
```vim
vim9script

colorscheme habamax
set list nowrap
prop_type_delete('test')
prop_type_add('test', {highlight: 'Error'})

const Opts: func = (str: string, length: number): dict<any> => ({
    type: 'test',
    text: $'{repeat(str, length)}',
    text_align: 'after',
    text_padding_left: 2
})

prop_add(1, 0, Opts('AAA', 20))
prop_add(1, 0, Opts('BBB', 10))
prop_add(1, 0, Opts('CCC', 20))
```

1. Append some text to the first line of the buffer. 
2. Result: right before the 2nd virtual text disappears, the text-properties are wrapped even though `nowrap` is set (see first screenshot below).
3. Go back to normal mode and press `u`.
4. Result: the screen is not redrawn after pressing `u`. This becomes more apparent when you keep pressing `u` and `<C-R>` a couple of times. Pressing `<C-L>` will redraw the screen again.

Screenshot:
![screenshot-2022-10-11_200908](https://user-images.githubusercontent.com/6266600/195167352-9b48be39-fb75-4d0b-98eb-3bbfa179d286.png)

Here's a video that demonstrates the above behavior:

https://user-images.githubusercontent.com/6266600/195165973-e3ec0c5b-2324-4a5b-8a03-b97d010948d6.mp4

---

Not directly related to the issue but wouldn't it be more useful to have a global `virtwrap` option (or similar) that changes the wrapping of all virtual text simultaneously, similar to `wrap`? Currently we need to delete all virtual text and then reapply them just for the sake of toggling `text_wrap`. That seems quite cumbersome. And every plugin author will have to go through the same steps to support toggling of virtual-text wrapping.

**Comment by bfrg** [comment]
Fixed in https://github.com/vim/vim/commit/7e017461e21ac534f8a0d59c1165d11358c69d87.
