### ISSUE TITLE
Execution error "function <SNR>13_Set_Backup" by folder with whitespace

### ISSUE THREAD

**Issue by ColiZei** [vim/vim#1133]
Hey!
I have some foldernames with whitespaces.

`vim ~/path/to/my\ example/file.md`

When i try to save a file with `:w` the swp file is not saved.

Vim output the message: 

`Fehler beim Ausführen von "function <SNR>13_Set_Backup":`
`Zeile 3`
`E518: Unbekannte Option: example`

Is there a solution to fix that? 
Is this a known issue?
Thx!

Vim Version:
VIM - Vi IMproved 8.0.13 (2016 Sep 12, compiled Sep 26 2016 10:02:07)

OS:
Linux 4.7.5-1-ARCH

**Comment by chrisbra** [comment]
In your vim session, please execute `:scriptnames` and show the output of number 13

**Comment by ColiZei** [comment]
Output: `13: ~/.vim/plugin/cbackup.vim`

**Comment by chrisbra** [comment]
you must have installed that plugin manually. Please discuss this issue with the author of that plugin. This is no Vim issue.

**Comment by ColiZei** [comment]
Thanks!
