### ISSUE TITLE
build vim with msys2, but can't run it.

### ISSUE THREAD

**Issue by zhucezy** [vim/vim#11331]
I builded vim7.4/8.2 with msys2. But when run it in msys2 console, it will hang up(vim7.4) or prompt "not compatiable with cygwin".
I found official expaination as "you can't execute vim.exe in the MSYS2 console, open a normal Windows console for that." in installPC.txt.
But I'v got an other copy of vim.exe (version 7.4) which can be used both msys2 console and windows cmd console.
How to build an copy like that?

**Comment by chrisbra** [comment]
This has been changed later than 7.4, because this causes more problem than it solves. So the correct way to use it is, for standard Windows builds, run it in a default console window. For Cygwin ones, built it it a cygwin environment. It's no longer possible to run one build in either environment

**Comment by k-takata** [comment]
If you want to build Vim that can run in the msys2 console, you should build it in a similar way as Cygwin using `./configure` and `make`.
If you don't need to build it by yourself, you can simply use `pacman -S vim` to install it.

Another way to run the Win32 version of Vim in the msys2 console is enabling ConPTY by setting the `MSYS` environment variable to `enable_pcon`. (This might have some compatible issues, though.)

**Comment by zhucezy** [comment]
> This has been changed later than 7.4, because this causes more problem than it solves. So the correct way to use it is, for standard Windows builds, run it in a default console window. For Cygwin ones, built it it a cygwin environment. It's no longer possible to run one build in either environment

Thanks a lot. Let me try a 7.3 version.

**Comment by zhucezy** [comment]
> If you want to build Vim that can run in the msys2 console, you should build it in a similar way as Cygwin using `./configure` and `make`.

Thanks for your reply.
I do want compile it by myself, and i failed with Make_cygwin.mak or ./configure & make like below:
./configure --prefix=/usr \
      --build=i686-W64-mingw32 \
      --with-tlib=ncurses \
      --without-x \
      --with-lua-prefix=/usr/local \
      --disable-gui \
      --disable-tclinterp \
      --disable-cscope \
      --enable-luainterp \
      --enable-pythoninterp=dynamic \
      --enable-rubyinterp=dynamic \
      --enable-pythoninterp=dynamic \
      --enable-multibyte
it still can't work in msys2 console.

**Comment by k-takata** [comment]
You are using the wrong version of GCC.
If you use Start Menu, you should use the "MSYS2 MSYS" icon. Or, you can use `C:\msys64\msys.exe` to open the shell. Then, make sure that you are using `/usr/bin/gcc` (or `/usr/bin/x86_64-pc-msys-gcc`).

`Make_cyg.mak` is used for building the Win32 version of Vim on Cygwin, not for building the Cygwin version of Vim.

**Comment by zhucezy** [comment]
> You are using the wrong version of GCC.

Understood. I should install a non-mingw version of GCC.
If I want build a version can be used in msys2, I should use the vim source get from msys2, which include patches.
Thank you very much and I'll close it.

**Comment by k-takata** [comment]
FYI, you can find the build script and patches for MSYS2's vim package here: https://github.com/msys2/MSYS2-packages/tree/master/vim

**Comment by zhucezy** [comment]
Yes, I built vim 8.2 according to it. And I built vim 7.4 too by using it with official vim package. Thank you. @k-takata

**Comment by k-takata** [comment]
Okay, closing then.
