### ISSUE TITLE
Long virtual text `above` not displayed correctly, and Vim crashes when terminal window is resized

### ISSUE THREAD

**Issue by bfrg** [vim/vim#11340]
### Steps to reproduce

Run `vim --clean test.vim -S test.vim`, with

```vim
vim9script

colorscheme habamax
prop_type_add('test', {highlight: 'Error'})

const opts: dict<any> = {
    type: 'test',
    text: range(50)->join(' '),
    text_align: 'above',
    text_padding_left: 2
}

prop_add(1, 0, opts)
```

Screenshot:

![screenshot-2022-10-11_024811](https://user-images.githubusercontent.com/6266600/194973671-70bc121a-2e70-4c28-a2bc-440fe9e44c4a.png)

Issues:

1. Move the cursor to the first line and press `VG`. Result: only the first line of the visual selection has the correct color. All other lines of the visual selection have the wrong color.
2. Resize the terminal window, for example, decrease its width. Result:

```
Vim: Caught deadly signal ABRT
Vim: Finished.
Aborted
```

**Note:**  When `wrap` is disabled, both issues go away. But the virtual text is still not displayed correctly.

### Expected behaviour

Multiple virtual text with `text_align` set to `above` should be displayed correctly. There shouldn't be any color drawing artifacts and no crashes when the terminal window is resized.

### Version of Vim

9.0.718

### Environment

Linux

**Comment by lacygoill** [comment]
- [backtrace](https://github.com/vim/vim/files/9751232/gdb.txt)
   - [ubsan log](https://github.com/vim/vim/files/9751233/ubsan.log)
   - [valgrind log](https://github.com/vim/vim/files/9751234/valgrind.log)
