### ISSUE TITLE
Syntax highlighting sh - single vs. multi-letter alias def

### ISSUE THREAD

**Issue by edrozenberg** [vim/vim#11344]
### Steps to reproduce

1. `$ vim .bashrc.test`
2. Add first line: `alias a='ls'`
3. Add second line: `alias ab='ls -al'`

### Expected behaviour

The equal (`=`) sign should have the same color on both lines. It doesn't currently.

<img width="196" alt="Equal Sign Hi in bashrc" src="https://user-images.githubusercontent.com/2648417/195133466-13b03633-2571-4c93-8c6d-b74a0e514beb.png">

### Version of Vim

9.0.0700

### Environment

Operating system: `MacOS 11.7 (20G817)`
Terminal: `TERM_PROGRAM="Apple_Terminal"`
Value of $TERM: `TERM="xterm-256color"`
Shell: `bash`

**Comment by zzzyxwvut** [comment]
The `alias` syntax region recognises a _two_-letter-or-more
name (a letter or \_, _and_ more letters or digits, etc.);
there is no such restriction in [a specification](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/alias.html#tag_20_02_17):

Try correcting it in `$HOME/.vim/after/syntax/sh.vim`, for
the time being, with a single-letter-or-more-name region
definition:

```vim
if exists("b:is_kornshell") || exists("b:is_bash") || exists("b:is_posix")
 syn match shStatement "\<alias\>"
 syn region shAlias matchgroup=shStatement start="\<alias\>\s\+\%(\h[-._[:alnum:]]*\)\@="  skip="\\$" end="\>\|`"
 syn region shAlias matchgroup=shStatement start="\<alias\>\s\+\%(\h[-._[:alnum:]]*=\)\@=" skip="\\$" end="="
endif
```

**Comment by chrisbra** [comment]
so here is a simple 2-line patch. ping @cecamp 
```diff
diff --git a/runtime/syntax/sh.vim b/runtime/syntax/sh.vim
index 6722d62c8..a18ddd1b8 100644
--- a/runtime/syntax/sh.vim
+++ b/runtime/syntax/sh.vim
@@ -190,8 +190,8 @@ syn region shEmbeddedEcho contained matchgroup=shStatement start="\<print\>" ski
 " =====
 if exists("b:is_kornshell") || exists("b:is_bash") || exists("b:is_posix")
  syn match shStatement "\<alias\>"
- syn region shAlias matchgroup=shStatement start="\<alias\>\s\+\(\h[-._[:alnum:]]\+\)\@="  skip="\\$" end="\>\|`"
- syn region shAlias matchgroup=shStatement start="\<alias\>\s\+\(\h[-._[:alnum:]]\+=\)\@=" skip="\\$" end="="
+ syn region shAlias matchgroup=shStatement start="\<alias\>\s\+\(\h[-._[:alnum:]]*\)\@="  skip="\\$" end="\>\|`"
+ syn region shAlias matchgroup=shStatement start="\<alias\>\s\+\(\h[-._[:alnum:]]*=\)\@=" skip="\\$" end="="

  " Touch: {{{1
  " =====
```

**Comment by chrisbra** [comment]
(basically, change the `\+` quantifier to a `*` quantifier, to make it optional)

**Comment by zzzyxwvut** [comment]
The proposed changes have already been accepted before [v9.0.1275](https://github.com/vim/vim/commit/be4e01637e71c8d5095c33b9861fd70b41476732#diff-650e28e4ad6a5c9241345580a7136ff18b5629f3b4910a5b5a455828bca5e517).

**Comment by cecamp** [comment]
I think this issue is fixed.  Closing...
