### ISSUE TITLE
<c-i><c-o> commands won't leave terminal buffers.

### ISSUE THREAD

**Issue by ubaldot** [vim/vim#11345]
### Steps to reproduce

Open a terminal buffer along to some other buffers, populate the `jumplist `by randomly jumping around (by using `gg `, `H`, `L`, etc. commands). 
Secure that at some point a jump in the terminal buffer is recorded in the `jumplist`. 

Then, start jump around using `<c-o><c-i>`.

If after execution of a `<c-o>` or `<c-i>` the cursor end up in the terminal buffer, further `<c-o>` or `<c-i>` won't let you to jump away from the terminal buffer. 

### Expected behaviour

When in a terminal buffer, a `<c-o>` or `<c-i>` command move the cursor in the previous/next position as reported in the `jumplist`.

### Version of Vim

9.0

### Environment

Windows 10
Gvim

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> Open a terminal buffer along to some other buffers, populate the
> `jumplist `by randomly jumping around (by using `gg `, `H`, `L`, etc.
> commands). 
> Secure that at some point a jump in the terminal buffer is recorded in
> the `jumplist`. 
> 
> Then, start jump around using `<c-o><c-i>`.
> 
> If after execution of a `<c-o>` or `<c-i>` the cursor end up in the
> terminal buffer, further `<c-o>` or `<c-i>` won't let you to jump away
> from the terminal buffer. 

Please give more specific, step-by-step repro steps.

> ### Expected behaviour
> 
> When in a terminal buffer, a `<c-o>` or `<c-i>` command move the
> cursor in the previous/next position as reported in the `jumplist`.

Is the terminal in Terminal-Normal mode?  Otherwise the keys go to the
process running in the terminal, you need to prefix with CTRL-W N then.

-- 
Courtroom Quote #19:
Q:  Doctor, how many autopsies have you performed on dead people?
A:  All my autopsies have been performed on dead people.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ubaldot** [comment]
> Please give more specific, step-by-step repro steps.

1. Open Vim
2. Open a text file with some text
3. `:clearjumps`
4. Hit `L` `M` `H`
5. Open a terminal buffer (in my case I use `:bo terminal powershell`)
8. `<c-w>:bprev` (you should be back in the text buffer)
10. `:bnext` (the focus now should be on the terminal buffer)
11. `<c-w>:bprev` (the focus now should be in the text buffer)
12. `<c-o>`  (you should end up in the terminal buffer)

from this point, further `<c-o>` commands won't make any jump. You are stuck in the terminal buffer.
To make `<c-o> `to work again you must run `<c-w>N` first. 
This is not optimal as it would abruptly interrupt a typical sequence of operations which include the run of  a sequence of "n" of `<c-o>`  followed by e.g.  some code edit and then followed a sequence of "n" `<c-i>` to get back to the original point.  

I think that terminal buffers should never be included in the jumplist, but that won't happens when e.g.   `:bnext ` move the focus on a terminal buffer. 

> Is the terminal in Terminal-Normal mode? Otherwise the keys go to the process running in the terminal, you need to prefix with CTRL-W N then.

Yes, I am aware of that, but that is not a desired behavior when dealing with jumps. 

Hope this clarify a bit. :) 

> […](#)
> -- Courtroom Quote #19: Q: Doctor, how many autopsies have you performed on dead people? A: All my autopsies have been performed on dead people. /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net \\\ /// \\\ \\\ sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ /// \\\ help me help AIDS victims -- http://ICCF-Holland.org ///

**Comment by ubaldot** [comment]
FYI: before approaching here I tried to ask here: https://vi.stackexchange.com/questions/38837/how-to-use-c-ic-o-in-terminal-mode-to-jump-to-from-next-previous-cursor-posi?noredirect=1#comment71115_38837

**Comment by brammool** [comment]
> > Please give more specific, step-by-step repro steps.
> 
> 1. Open Vim
> 2. Open a text file with some text
> 3. `:clearjumps`
> 4. Hit `L` `M` `H`
> 5. Open a terminal buffer (in my case I use `:bo terminal powershell`)
> 8. `<c-w>:bprev` (you should be back in the text buffer)

Here I get "E948: Job still running (add ! to end the job)".
Do you have 'hidden' set perhaps?

> 10. `:bnext` (the focus now should be on the terminal buffer)
> 11. `<c-w>:bprev` (the focus now should be in the text buffer)
> 12. `<c-o>`  (you should end up in the terminal buffer)
> 
> from this point, further `<c-o>` commands won't make any jump. You are
> stuck in the terminal buffer.
> To make `<c-o> `to work again you must run `<c-w>N` first. 
> This is not optimal as it would abruptly interrupt a typical sequence of operations which include the run of  a sequence of "n" of `<c-o>`  followed by e.g.  some code edit and then followed a sequence of "n" `<c-i>` to get back to the original point.  
> 
> I think that terminal buffers should never be included in the
> jumplist, but that won't happens when e.g.   `:bnext ` move the focus
> on a terminal buffer. 
> 
> > Is the terminal in Terminal-Normal mode? Otherwise the keys go to the process running in the terminal, you need to prefix with CTRL-W N then.
> 
> Yes, I am aware of that, but that is not a desired behavior when
> dealing with jumps. 
> 
> Hope this clarify a bit. :) 

-- 
MARTHA'S WAY: Don't throw out all that leftover wine. Freeze into ice cubes
              for future use in casseroles and sauces.
MY WAY:       What leftover wine?

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ubaldot** [comment]
Yes! Sorry for having miss the detail.

**Comment by brammool** [comment]
> > Please give more specific, step-by-step repro steps.
> 
> 1. Open Vim
> 2. Open a text file with some text
> 3. `:clearjumps`

And ":set hidden".

> 4. Hit `L` `M` `H`
> 5. Open a terminal buffer (in my case I use `:bo terminal powershell`)
> 8. `<c-w>:bprev` (you should be back in the text buffer)
> 10. `:bnext` (the focus now should be on the terminal buffer)
> 11. `<c-w>:bprev` (the focus now should be in the text buffer)
> 12. `<c-o>`  (you should end up in the terminal buffer)
> 
> from this point, further `<c-o>` commands won't make any jump. You are
> stuck in the terminal buffer.

This is normal, you are in a mode where typed keys go to the terminal.
If you type "CTRL-W N" to go to Terminal-Normal mode then CTRL-O works.

I do not think this is a bug or something that could be changed.
You could make a mapping for CTRL-O with ":tmap".  It does mean that you
cannot pass CTRL-O to the job in the terminal, thus it's not something
we can do in general.

-- 
5 out of 4 people have trouble with fractions.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ubaldot** [comment]
Ok I see the point of keeping the native terminal behavior with `<c-i>` and `<c-o>` (especially with `<c-i>`). 
One work around could be map two entirely new commands, like for example

```
nnoremap <c-m> <c-o> 
nnoremap <c-n> <c-i> 
inoremap <c-m> <c-o> 
inoremap <c-n> <c-i> 
vnoremap <c-m> <c-o> 
vnoremap <c-n> <c-i> 
tnoremap <c-m> <c-w>N<c-o> 
tnoremap <c-n> <c-w>N<c-i> 
```
Nevertheless, the drawback that I see with this approach is that the terminal buffer will be left in `Normal `mode. 
One should thing to write a function such that in terminal mode the command `<c-o>` sends the sequence `<c-w>N<c-o>` followed by a `i `through a `term_sendkeys() ` in the last used terminal buffer. A bit tricky I must say... 

OR, a nicer solution, would be to prevent jumps into terminal buffers to be appended to the jumplist.
I would personally like the latter more. :)  

What do you think?

**Comment by brammool** [comment]
> Ok I see the point of keeping the native terminal behavior with `<c-i>` and `<c-o>` (especially with `<c-i>`). 
> One work around could be map two entirely new commands, like for example
> 
> ```
> nnoremap <c-m> <c-o> 
> nnoremap <c-n> <c-i> 
> inoremap <c-m> <c-o> 
> inoremap <c-n> <c-i> 
> vnoremap <c-m> <c-o> 
> vnoremap <c-n> <c-i> 
> tnoremap <c-m> <c-w>N<c-o> 
> tnoremap <c-n> <c-w>N<c-i> 
> ```
> Nevertheless, the drawback that I see with this approach is that the terminal buffer will be left in `Normal `mode. 
> One should thing to write a function such that in terminal mode the command `<c-o>` sends the sequence `<c-w>N<c-o>` followed by a `i `through a `term_sendkeys() ` in the last used terminal buffer. A bit tricky I must say... 
> 
> OR, a nicer solution, would be to prevent jumps into terminal buffers to be appended to the jumplist.
> I would personally like the latter more. :)  
> 
> What do you think? 

If the job in the terminal is finished we are in a different situation.
Only dropping some jumps starts getting complicated.
I think we should just leave it as it is, and you'll have to deal with
ending up in a terminal.

-- 
The early bird gets the worm. The second mouse gets the cheese.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ubaldot** [comment]
I see. I’ll map <c-n><c-m> through a/some function(s). Hopefully such a choice of keys won’t backfire at some point 😅

**Comment by chrisbra** [comment]
closing then.
