### ISSUE TITLE
Documentation Typo Breaks Build - os_haiku.txt 

### ISSUE THREAD

**Issue by m12n** [vim/vim#11342]
### Steps to reproduce

1. Install ncurses6 via package manager on Haiku 
2. Run config as stated in os_haiku.txt using --with-tlib=ncurses6
3. Config fails

### Expected behaviour

1. Install ncurses6 via package manager on Haiku 
2. Run config as stated in os_haiku.txt using --with-tlib=ncurses without the 6
3. Config succeeds

No need to use ncurses with a 6 as of the latest Haiku Beta.

### Version of Vim

9.0.719

### Environment

Haiku Beta 3

**Comment by brammool** [comment]
I included the update of the help that explains it.
