### ISSUE TITLE
Virtual text `right` not displayed correctly when `list` enabled

### ISSUE THREAD

**Issue by bfrg** [vim/vim#11341]
### Steps to reproduce

Run `vim --clean test.vim -S test.vim`, with

```vim
vim9script

colorscheme habamax
set list
prop_type_add('test', {highlight: 'Error'})

const opts: dict<any> = {
    type: 'test',
    text: range(5)->join(' '),
    text_align: 'right',
    text_padding_left: 2
}

prop_add(1, 0, opts)
prop_add(1, 0, opts)
prop_add(1, 0, opts)
```

Result: the three virtual text-properties are displayed below each other. Is this intentional to display them below each other or should they be displayed next to each other on the same line? I wasn't quite sure what the right behavior should be.

Screenshot:
![screenshot-2022-10-11_030833](https://user-images.githubusercontent.com/6266600/194975378-a83dc32a-8cb9-4e91-9930-20551fb41f27.png)

1. Now enable `list`. 
2. Result: only one virtual text-property is displayed. 
3. Move the cursor to the bottom of the buffer by pressing `G`.
4. Result: cursor is displayed below the last buffer line.

Screenshot:
![screenshot-2022-10-11_030848](https://user-images.githubusercontent.com/6266600/194975477-a6a3ca04-6a0a-4b43-a76f-c1f29f3e92b0.png)

### Expected behaviour

There shouldn't be a difference in appearance of right-aligned virtual text when `list` is enabled or disabled.

### Version of Vim

9.0.718

### Environment

Linux

**Comment by brammool** [comment]
Every property with "right" alignment is right aligned.  Maybe in some cases it would be OK to put them on the same line, but it's going to be tricky when they don't fit.  I assume in general that there is only one property that is right aligned.  If there are more they should show up, but I don't think it is worth spending effort on making it look better (if putting them in one line is actually better).

**Comment by brammool** [comment]
Oh, and it looks like a recent patch already fixed the problem of properties not showing up with 'list' set.

**Comment by bfrg** [comment]
Yes, I agree having them all below each other and right aligned looks much better.
