### ISSUE TITLE
vim9script: different for-loop behavior at script level and inside a `def` function

### ISSUE THREAD

**Issue by bfrg** [vim/vim#11347]
### Steps to reproduce

This is a continuation of the discussion in https://github.com/vim/vim/issues/11094#issuecomment-1274963516.

The following for-loop works differently at script level vs inside a `def` function:

```vim
vim9script

# Filter out all odd numbers in each sublist
var list: list<list<number>> = [[1], [1, 2], [1, 2, 3], [1, 2, 3, 4], [1, 2, 3, 4, 5]]
for i in list
    filter(i, (_, n: number): bool => n % 2 == 0)
endfor

# [[], [2], [2], [2, 4], [2, 4]]
echo list
```

Everything works as expected. However, inside a `def` function, the above snippet doesn't compile:

```vim
vim9script
def Test()
    var items: list<list<number>> = [[1], [1, 2], [1, 2, 3], [1, 2, 3, 4], [1, 2, 3, 4, 5]]
    for i in items
        filter(i, (_, n: number): bool => n % 2 == 0)
    endfor
    echo items
enddef
Test()
```

Result:
```
Error detected while compiling /tmp/test.vim[34]..function <SNR>22_Test:
line    3:
E1307: Argument 1: Trying to modify a const list<number>
```

What does this mean? Does Vim copy each item inside the list? That would be quite inefficient. The items could be anything.

The following works but looks more complicated:
```vim
def Test()
    var items: list<list<number>> = [[1], [1, 2], [1, 2, 3], [1, 2, 3, 4], [1, 2, 3, 4, 5]]
    for i in items
        var item: list<number> = i
        filter(item, (_, n: number): bool => n % 2 == 0)
    endfor
    echo items
enddef
```

### Expected behaviour

I think there shouldn't be a difference whether the same lines of code are called inside a `def` function or at script level.

### Version of Vim

9.0.723

### Environment

Linux

**Comment by brammool** [comment]
The loop variable is considered a constant, you can't change it.
But if the value is a list, I suppose it is OK the change the contents of that list, as you intend to do here.
It's more like the loop variable is "final".
That means the compiled function does this wrong.
