### ISSUE TITLE
listener_add() documentation errors

### ISSUE THREAD

**Issue by noscript** [vim/vim#11362]
### Steps to reproduce

1. Create `~/listener.vim`:
```vim
vim9script

def Listener(bufnr: number, start: number, end: number, added: number, changes: list<any>)
  echow 'changes ' .. changes->string()
enddef
autocmd VimEnter,BufRead * listener_add(Listener)
```
2. Run vim:
```sh
vim -g -f --clean +'so ~/listener.vim' README.txt
```
3. Go to top line, go to INSERT mode, press Enter:
```vim
:execute "norm! ggi\<CR>"
```
4. Reported changes:
```
changes [{'lnum': 1, 'col': 1, 'added': 1, 'end': 2}]
```

### Expected behaviour

```
changes [{'lnum': 1, 'col': 1, 'added': 1, 'end': 1}]
```
According to `listener_add()` documentation, when lines are inserted,  `end` is equal to `lnum`.

Also, this sentence is not clear, `lnum` needs a better explanation:
```
lnum	line above which the new line is added
```

- Is `lnum` a line that is above inserted line? If so, then it should be equal to `0` in the example above, which is not the case.
- or maybe it is a line that is below the last inserted line, but before insertion was done? If so, it should be also added to the documentation.
- or maybe it is a line that is the first inserted line? If so, then it doesn't quite matches the documentation.

### Version of Vim

9.0.0709

### Environment

OS: Debian 11
Terminal: GUI

**Comment by brammool** [comment]
When using "i<CR>" you are not just inserting a line, your are breaking a line in two.  There could be text before and after where the line break is inserted.
Inserting a line is for example using "p" with a register that contains linewise text.

**Comment by noscript** [comment]
Isn't it still an error in documentation or a bug?
```
		When lines are inserted the values are:
		    lnum	line above which the new line is added
		    end		equal to "lnum"
		    added	number of lines inserted
		    col		1
```

According to
```
changes [{'lnum': 1, 'col': 1, 'added': 1, 'end': 2}]
```
 a line is inserted, but `end` is not equal to `lnum`

**Comment by brammool** [comment]
> Isn't it still an error in documentation or a bug?
> ```
> 		When lines are inserted the values are:
> 		    lnum	line above which the new line is added
> 		    end		equal to "lnum"
> 		    added	number of lines inserted
> 		    col		1
> ```
> 
> According to
> ```
> changes [{'lnum': 1, 'col': 1, 'added': 1, 'end': 2}]
> ```
>  a line is inserted, but `end` is not equal to `lnum`

I thought I already mentioned: by typing CR in Insert mode you are
changing a line, not just inserting one.  I can add a remark:

		When lines are inserted (not when a line is split, e.g. by
		typing CR in Insert mode) the values are:

Does that make it clear?

-- 
       [Autumn changed into Winter ... Winter changed into Spring ...  Spring
       changed back into Autumn and Autumn gave Winter and Spring a miss and
       went straight on into Summer ...  Until one day ...]
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by noscript** [comment]
>
		When lines are inserted (not when a line is split, e.g. by
		typing CR in Insert mode) the values are:
		
Yes, it makes it more clear.

And I think I understood it now, `listener_add()` can combine separate operations such as changing and inserting as one single operation. I though that each operation would be reported separately, this is what confused me.

Should in this case description for `end`  when inserting lines be

```
end             the line below the last changed line
```

then it would apply to both line splitting and not splitting
