### ISSUE TITLE
set output messages to external command (terminal output)

### ISSUE THREAD

**Issue by scila1996** [vim/vim#1136]
HI !!!

How do I set output of VIM command or using
`:python os.system("javac -d . *.java")`

it is show => "test" at bottom statusline , but i want to output it to external command (not using she bang external command)

Purpose : I'm creating java auto compiler , and using "PYTHON MODULE in VIM script " , I want all output are put to external command (without shebang external command)

Thank you !!!!

**Comment by chrisbra** [comment]
I don't understand what you want. Please discuss user questions at vim-use ml or use stackoverflow. This is for issues only.
