### ISSUE TITLE
Open a file at a specific line AND optional character position

### ISSUE THREAD

**Issue by suliveevil** [vim/vim#11367]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

We can open file with Vim at specific line: `vim +12 /path/to/file.md`.

There seems no option for **character position** AFAIK.

**Describe the solution you'd like**

I'm expecting something like this: `vim +12:5 /path/to/file.md`

Just like VSCode's `code --goto /path/to/file.md:12:5`

**Describe alternatives you've considered**

Or how to use `+/{pat}` to achieve the same goal?

I'm grateful if any method can help.

**Additional context**

I'm using Obsidian a lot recently, there is a way to open Obsidian file with external editor like Vim(MacVim) and VSCode:

```shell
# Open with VSCode
/opt/homebrew/bin/code --goto {{file_path:absolute}}:{{caret_position}}

# Open with MacVim
/opt/homebrew/bin/mvim +{{caret_position:line}} {{file_path:absolute}}
```

Powered by Obsidian plugin: 

https://github.com/Taitava/obsidian-shellcommands

**Comment by brammool** [comment]
> **Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
> 
> We can open file with Vim at specific line: `vim +12 /path/to/file.md`.
> 
> There seems no option for **character position** AFAIK.
> 
> **Describe the solution you'd like**
> 
> I'm expecting something like this: `vim +12:5 /path/to/file.md`
> 
> Just like VSCode's `code --goto /path/to/file.md:12:5`
> 
> **Describe alternatives you've considered**
> 
> 
> 
> **Additional context**
> 
> I'm using Obsidian a lot recently, there is a way to open Obsidian
> file with external editor like Vim(MacVim) and VSCode:
> 
> ```shell
> # Open with VSCode
> /opt/homebrew/bin/code --goto {{file_path:absolute}}:{{caret_position}}
> 
> # Open with MacVim
> /opt/homebrew/bin/mvim +{{caret_position:line}} {{file_path:absolute}}
> ```
> 
> Powered by Obsidian plugin: 
> 
> https://github.com/Taitava/obsidian-shellcommands

I thought we had a todo item for this, but I can't find it.

That column number, is that a byte index, character index, or screen
column?

-- 
My girlfriend told me I should be more affectionate.
So I got TWO girlfriends.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by suliveevil** [comment]
It's character index.

https://publish.obsidian.md/shellcommands/Variables/%7B%7Bcaret_position%7D%7D#Variable+caret_position

```
Gives the line number and column position of the current caret position as 'line:column'. Get only the line number using {{caret_position:line}}, and only the column with {{caret_position:column}}. Line and column numbers are 1-indexed.
```

https://code.visualstudio.com/docs/editor/command-line#_core-cli-options

```
When used with file:line{:character}, opens a file at a specific line and optional character position. This argument is provided since some operating systems permit : in a file name.
```

**Comment by suliveevil** [comment]
You may interested in manage roadmap and long-term todo using GitHub Projects:

https://docs.github.com/en/issues/planning-and-tracking-with-projects

**Comment by brammool** [comment]
> You may interested in manage roadmap and long-term todo using GitHub Projects:
> 
> https://docs.github.com/en/issues/planning-and-tracking-with-projects

That is going to waste a lot of time on planning and bookkeeping.
It takes the creativity out of a project.

-- 
If cars evolved at the same rate as computers have, they'd cost five euro, 
run for a year on a couple of liters of petrol, and explode once a day.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by arp242** [comment]
Very similar: #4707

**Comment by suliveevil** [comment]
> Very similar: #4707

This is really helpful! Thank you very much.

I can make MacVim/Neovide works with Obsidian just like VSCode does!


```shell
/opt/homebrew/bin/mvim {{file_path:absolute}} -c 'normal {{caret_position:line}}G{{caret_position:column}}|'
/opt/homebrew/bin/neovide {{file_path:absolute}} -c 'normal {{caret_position:line}}G{{caret_position:column}}|'
```

**Comment by brammool** [comment]
Except that #4707 proposes a byte offset.  I don't know what is most common, but most likely both are used.

**Comment by ychin** [comment]
Also that issue proposes using a colon to act as delimiter internet the filename which I think it’s a pretty bad idea. There are actual files that have “:” in the file name. It’s much better to use a separate option as proposed here to do that (since the option already supports line number)

@suliveevil for what it’s worth since it seems like you are using MacVim, it supports a MacVim-only way to do this by opening a `mvim://` URL on your computer which does accept line and column. I can find the doc for that when I’m at a computer.

**Comment by suliveevil** [comment]
> Also that issue proposes using a colon to act as delimiter for the filename which I think it’s a pretty bad idea. There are actual files that have “:” in the file name. It’s much better to use a separate option as proposed here to do that (since the option already supports line number)

I'm not a programmer but I know simple changes may have hard work behind the scene.
So I'm happy with any workaround just like using `vim -c` mentioned above.
