### ISSUE TITLE
Can't access exported var from within exporting autoload script

### ISSUE THREAD

**Issue by dkearns** [vim/vim#11361]
### Steps to reproduce

Source the following autoload script.

```vim
vim9script
export const FOO = 42
echomsg FOO # => E121: Undefined variable: FOO
```

I actually noticed this when trying to modify an exported dict later in the file.  That can be worked around by building the dict with a temporary variable and then assigning it to the exported variable but I'm not sure if this is intentional.

### Expected behaviour

Output: `42`

Actual Output:
```
Error detected while processing /tmp/foo.vim:
line    3:
E121: Undefined variable: FOO
```

### Version of Vim

9.0.0741

### Environment

Ubuntu 18.04

**Comment by habamax** [comment]
Works for me in `9.0.0739`. I get `42`.

**Comment by dkearns** [comment]
Thanks.  It appears to also need to be in an autoload directory to fail.
