### ISSUE TITLE
 Vim with termguicolors in Windows Terminal outputs wrong color

### ISSUE THREAD

**Issue by 3N4N** [vim/vim#11373]
### Steps to reproduce

```
vim --clean +"set ls=2 tgc"
```

### Expected behaviour

In the old conhost terminal, the colors are output properly. Same thing should happen in Windows Terminal.

[![vim in conhost][1]][1]

[1]: https://i.stack.imgur.com/fUNtg.png

### Actual Behavior

But in Windows Terminal (v1.16.2524.0), the colors with `:h termguicolors` enabled is incorrect.

[![vim in Windows Terminal][2]][2]

  [2]: https://i.stack.imgur.com/G6XAq.png

### Version of Vim

9.0.648

### Environment

Operating system: Windows 11 version 21H2 (OS Build 22000.1098)
Terminal: Windows Terminal v1.16.2642.0 with Solarized Light colorscheme (comes with the terminal by default)
Value of $TERM: nil (also tried with 'xterm-256colors')
Shell: cmd.exe (also tried with powershell)

**Comment by 3N4N** [comment]
@chrisbra sorry for pinging you but if you remember: I opened question in vi.SE about this bug and you confirmed that you could reproduce it. I tried today and the colors are displayed properly now. If you could try it once more to see if it got fixed on your end, too, then this issue can be closed (although what fixed it is unknown).

**Comment by zewpo** [comment]
This is really interesting.   

What you are seeing is the default windows console foreground color, non-intense white, which is MS Windows defaults, however only appropriate for a dark background.    

When Vim goes into tgc,  it requests the appropriate rgb background and foreground colors from the host console api - before applying anything set (if any) from the user configured colorscheme or highlight groups.    

In the old Command Prompt console you can only configure fg and bg colors by selecting from one of the values from the colortable, ie, one of the 16 confgured rgb colors.   However, in the new WT,  fg and bg colors can be configured independantly to any rgb value you want - they don't have to be selected from one of the 16 rgb colors of the colortable. 

The old way of querying which index of the colortable to use for bg and fg, seems to be inappropriate for the new WT.   I'm trying to see how to query the new conpty api for the correct colors, it doesnt seem properly documented in windows api docos - but its all opensource on github, so I'm having a trawl through that. 

![image](https://user-images.githubusercontent.com/10286211/197650459-9ff1be84-bab6-4753-936e-573b497057c8.png)

![image](https://user-images.githubusercontent.com/10286211/197650819-ede67f1e-1c00-410e-9db8-fb1907c9bc98.png)

**Comment by 3N4N** [comment]
> The old way of querying which index of the colortable to use for bg and fg, seems to be inappropriate for the new WT. 

@zewpo could you share where in Vim's source this is being done? I could take a look at it too.

What fascinates me is that no one reported this. Do you think no one uses Vim in Windows Terminal?

**Comment by zewpo** [comment]
@3N4N   I think that most users probably have a default black background anyway, and so dont notice the issue.  And then, even if they do use a white bacground, its still not a problem set a colorscheme which sets the "Normal" text color to something they like.

**Comment by 3N4N** [comment]
Thanks! The problem seems to be, as you said, Vim's assumption of fg/bg being one of the 16-colors:
https://github.com/vim/vim/blob/a4962cd7bac8464d9f8d95d37614ecf595c5487e/src/os_win32.c#L212-L213
https://github.com/vim/vim/blob/a4962cd7bac8464d9f8d95d37614ecf595c5487e/src/os_win32.c#L7884-L7886

Fixing that ^ should fix it. But for now (for anyone else who may be facing this issue), hard-coding a hex value to `default_console_color_fg` in this line should do it:

https://github.com/vim/vim/blob/a4962cd7bac8464d9f8d95d37614ecf595c5487e/src/os_win32.c#L7886

**Comment by zewpo** [comment]
I gotta learn to use github.  I like how you were able to show those lines....

I think its already kind of there, 
https://github.com/vim/vim/blob/a4962cd7bac8464d9f8d95d37614ecf595c5487e/src/os_win32.c#L216-L217

but, consider that it is assuming a black background.   So, it wouldnt look good if we hard coded a dark color there.   Perhaps like a half way - eg 0x858585

**Comment by 3N4N** [comment]
@yegappan sorry for pinging you but since you took care of the last Windows-specific bug and patch I supplied, I figured you could take a look at this. Remember that this is not just Windows Terminal-specific; any terminal emulator (e.g., WezTerm) using VT sequences should be affected by this.

**Comment by zewpo** [comment]
@3N4N   yeah, its not as simple as it should be.    I think a better solution is that vim should never need to read or change the terminals default foreground color.  The escape sequence ESC[0m will just tell the terminal to restore its own default color automatically, and that works as long as vim has not actually changed the defaults in the colortable.    I got more ideas, to explain what I'm thinking, but will have to share later, gotta run some errands right now, be back later today.

**Comment by zewpo** [comment]
So... Vim already avoids the problem for the background, I can make it do the same for the foreground.  will have a patch ready in a few minutes.  
However, I have not checked what it might do in something else, like you say, WezTerm on windows.

**Comment by zewpo** [comment]
check if it works, PR #11431

**Comment by 3N4N** [comment]
PR#11450 fixes this issue, both in Windows Terminal and WezTerm (as is expected).
Thanks for the patch. Hopefully it will get merged soon.
