### ISSUE TITLE
The file's hide attribute is lost after the file is saved by vim on windows platform

### ISSUE THREAD

**Issue by zoumi** [vim/vim#11370]
### Steps to reproduce

1.set a text file attribute to "hide"
2.open the file with vim
3.:wq to save the file

### Expected behaviour

the file's "hide" atrribute should not be changed.

### Version of Vim

9.01701

### Environment

Windows 10 64bit

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> 1.set a text file attribute to "hide"
> 2.open the file with vim
> 3.:wq to save the file

How do you set or see that "hide" attribute?

> ### Expected behaviour
> 
> the file's "hide" atrribute should not be changed.

You can probably make it work by setting 'backupcopy'.
It's not a complete solution, but give it a try.

-- 
MONK: ... and the Lord spake, saying, "First shalt thou take out the Holy Pin,
      then shalt thou count to three, no more, no less.  Three shalt be the
      number thou shalt count, and the number of the counting shalt be three.
      Four shalt thou not count, neither count thou two, excepting that thou
      then proceed to three.  Five is right out.  Once the number three, being
      the third number, be reached, then lobbest thou thy Holy Hand Grenade of
      Antioch towards thou foe, who being naughty in my sight, shall snuff it.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by zoumi** [comment]
I set the "hidden" through windows file atrribute menu.
![https://cdn.mos.cms.futurecdn.net/eYBzUcW5z2NVpzUp4g9uDj-1200-80.jpg.webp]

**Comment by zoumi** [comment]
set backupcopy=yes
will get E212: Can not open file for writing.

**Comment by brammool** [comment]
I thought we did have ACL support on Windows, isn't that hidden flag part of it?

**Comment by k-takata** [comment]
Hidden files on Windows are similar to read-only files. `:w!` should be used to overwrite a hidden file.
The hidden flag is a part of the attributes that are available since MS-DOS. ACL is new from NTFS.
