### ISSUE TITLE
E909: Cannot index a special variable for const dict<any>

### ISSUE THREAD

**Issue by lilydjwg** [vim/vim#11389]
### Steps to reproduce

1. prepare the following files:
s.vim:
```vim
vim9script

export def V(): dict<any>
  return {a: [1, 2], b: 1}
enddef
```
t.vim:
```vim
vim9script

import './s.vim' as s

def Test()
  const v = s.V()
  var b = v.a[1]
enddef

Test()
```
2. source t.vim

### Expected behaviour

It runs without errors.

If the function `V` is defined in the same module, or if `const` is replaced by `var`, it runs fine.

0089ce293f885afc2b77f12aa110f33b2101973a is the first bad commit.

This causes errors with [vim9-stargate](https://github.com/monkoose/vim9-stargate).

### Version of Vim

9.0.695+

### Environment

Arch Linux, GNOME Terminal / GVIM.

**Comment by bfrg** [comment]
Adding a type hint to the constant variable `v` also works:

```vim
vim9script

import './s.vim' as s

def Test()
  const v: dict<any> = s.V()
  var b = v.a[1]
enddef

Test()
```

**Comment by monkoose** [comment]
@lilydjwg author of vim9-stargate here, does this patch fixed it for you? 

Because now instead of `cannot index a special variable` i get `trying to modify a const any` error.

This is the line which causes this, but i can't trace it further.

**Comment by kg8m** [comment]
@monkoose 

> Because now instead of `cannot index a special variable` i get `trying to modify a const any` error.
> 
> This is the line which causes this, but i can't trace it further. https://github.com/monkoose/vim9-stargate/blob/b669d00f66b206d22091b3fe248f0b212e14bf5f/import/stargate/stargates.vim#L156

This new error is caused at #L17 `slice->remove(0)`. And I opened #11490. For your information, https://github.com/kg8m/vim9-stargate/commit/b6bcd367e65f0eb2f3ceff11252c886103fd3198 is a workaround for vim9-stargate (I'm temporarily using patched my fork).

**Comment by lilydjwg** [comment]
@monkoose yes, the same error occurred to me without unmodified code, but I've locally replaced `const ds` with `var ds` and forgotten to revert it after I've updated my local vim to a fixed version and it unexpectedly avoided this error.

**Comment by monkoose** [comment]
@kg8m @lilydjwg Thank you both. Fixed it in main.
