### ISSUE TITLE
listener_add() callback to provide before/after ranges

### ISSUE THREAD

**Issue by noscript** [vim/vim#11385]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

LSP [didChange](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_didChange) request requires two parameters:
* `range` which corresponds to the old state of the buffer
* `text` which corresponds to the new state of the buffer

With `listener_add()` callback it is possible to calculate the line ranges, but column ranges cannot be calculated (or at least it is too hard to do and comes with many edge cases) and therefor it impossible to accurately express changes that span multiple lines.

Edge case 1: add a line with `o` in normal mode vs split a line in insert mode at the last column with `<CR>`. Both cases result in the same final buffer state, however `listener_add()` reports different changes:

* `{'added': 1, 'col': 1, 'end': 11, 'lnum': 11}` when adding a line with `o` in normal
* `{'added': 1, 'col': 1, 'end': 12, 'lnum': 11}` splitting a line in insert mode with `<CR>`

Edge case 2:  split a line in insert mode at the last column with `<CR>`. Then undo with `u` vs  delete the new line with `dd`. Again, both cases result in the same final buffer state, however `listener_add()` reports differently the last change:

* `{'added': -1, 'col': 1, 'end': 7, 'lnum': 5}` when deleting via undo
* `{'added': -1, 'col': 1, 'end': 7, 'lnum': 6}` when deleting via `dd`

There are more edge cases.

It is not trivial (if possible at all) how to process these changes that would result in the same `text` and `range`.

**Describe the solution you'd like**

Add a flag to `listener_add()` that would provide changes to the callback in the following form:
```
{
  before: {
    start: {
      lnum: <lnum>,
      col: <col>
    },
    end: {
      lnum: <lnum>,
      col: <col>
    }
  },
  after: {
    start: {
      lnum: <lnum>,
      col: <col>
    },
    end: {
      lnum: <lnum>,
      col: <col>
    }
  },
}
```

This form precisely represents before and after states, so calculating the parameters for `didChange` becomes very straightforward:
```vim
var range = {
  start: {
    line: change.before.start.lnum - 1,
    character: change.before.start.col - 1
  },
  end: {
    line: change.before.end.lnum - 1,
    character: change.before.end.col - 1
  }
}
var lines = bufline(change.after.start.lnum, change.after.end.lnum)
lines[0] = lines[0][: change.after.start.col - 1]
lines[-1] = lines[-1][change.after.end.col - 1 :]
var text = lines->join("\n")
```

**Describe alternatives you've considered**

Sending the whole buffer to LSP server on every change.

**Comment by brammool** [comment]
> **Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
> LSP [didChange](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_didChange) request requires two parameters:
> * `range` which corresponds to the old state of the buffer
> * `text` which corresponds to the new state of the buffer
> 
> With `listener_add()` callback it is possible to calculate the line
> ranges, but column ranges are impossible to calculate (or at least it
> is too hard to do and comes with many edge cases) and therefor it
> impossible to accurately express changes that span multiple lines.

Column ranges are not always available.  In many cases there are
several changes inside a line.  Undo always works on whole lines.

I thought that others can work with the information provided.  You could
just assume the changes is from the first colum of the first line with a
change to the last column of the last line of the change.
The number of inserted and deleted lines should be accurate (it is also
used to move marks up and down).

> Edge case 1: add a line with `o` in normal mode vs split a line in
> insert mode at the last column with `<CR>`. Both cases result the same
> final buffer state, however `listener_add()` reports different
> changes:
> 
> * `{'added': 1, 'col': 1, 'end': 11, 'lnum': 11}` when adding a line with `o` in normal
> * `{'added': 1, 'col': 1, 'end': 12, 'lnum': 11}` splitting a line in insert mode with `<CR>`

I don't see a problem with this, the change is reported properly.  You
know where it happened and that a line was added.

> Edge case 2:  split a line in insert mode at the last column with
> `<CR>`. Then undo with `u` vs the new delete with `dd`. Again, both
> cases result the same final buffer state, however `listener_add()`
> reports different changes for the line deleting change:
> 
> * `{'added': -1, 'col': 1, 'end': 7, 'lnum': 5}` when deleting via undo
> * `{'added': -1, 'col': 1, 'end': 7, 'lnum': 6}` when deleting via `dd`

It appears you think that these change reporst tell you the final state.
That is not so, they tell you what changed.  And when the number of
lines changes, the column is usually not that relevalt.  As mentioned,
undo will always replace the whole line, no matter what changed inside
the line.

> **Describe the solution you'd like**
> 
> add a flag to `listener_add()` that would provide changes to the callback in the following form of:
> ```
> {
>   before: {
>     start: {
>       lnum: <lnum>,
>       col: <col>
>     },
>     end: {
>       lnum: <lnum>,
>       col: <col>
>     }
>   },
>   after: {
>     start: {
>       lnum: <lnum>,
>       col: <col>
>     },
>     end: {
>       lnum: <lnum>,
>       col: <col>
>     }
>   },
> }
> ```

This information is not available. E.g. re-indent a sequence of lines,
you just get the first and last line that changed.  I would not know
what column to report, perhaps zero?  Or change some test to uppercase.
Would we need to report only the characters that actually changed, or
just the whole area that was operated upon?

-- 
It is illegal for anyone to give lighted cigars to dogs, cats, and other
domesticated animal kept as pets.
		[real standing law in Illinois, United States of America]

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by noscript** [comment]
> I don't see a problem with this, the change is reported properly.  You
know where it happened and that a line was added.

I will try to explain the problem in details:

This is a very simple algorithm I came up with to process the "lines inserted" case:
```vim
var lines = getline(change.lnum, change.lnum + change.added)
var range = {
  start: {lnum: change.lnum, col: 1},
  end:   {lnum: change.end,  col: lines[-1]->len() + 1}
}
```

Let's take this pseudo code (for convenience each lines is prepended with `<lnum>:`):
```
1:var a = 1;
2:var b = 2;
3:var c = 3;
4:var d = 4;
5:var e = 5;
```

Put the cursor on line `3` and create a new line with `o`. Vim buffer will become:

```
1:var a = 1;
2:var b = 2;
3:var c = 3;
4:
5:var d = 4;
6:var e = 5;
```

and Vim will report the following change:
```
{'added': 1, 'lnum': 4, 'col': 1, 'end': 4}
```

Using the code snippet above we calculate the following:
```javascript
var lines = [
  '',
  'var d = 4;'
]

var range = {
  start: {
    lnum: 4, col: 1
  },
  end: {
    lnum: 4, col: 11
  }
}
```

Then we convert it to the format suitable for LSP server (change range from 1-based to 0-based, join the lines) and send it. After applying the changes the server state matches Vim buffer:
```
1:var a = 1;
2:var b = 2;
3:var c = 3;
4:
5:var d = 4;
6:var e = 5;
```

So far so good.

---

Now let's go back to the original pseudo code. Do a split at the start of line `4` with `<CR>`. We get the same Vim buffer state as before:

```
1:var a = 1;
2:var b = 2;
3:var c = 3;
4:
5:var d = 4;
6:var e = 5;
```

However this time Vim reports the change as:
```
{'added': 1, 'lnum': 4, 'col': 1, 'end': 5}
```

Using the same algorithm we calculate this:
```javascript
var lines = [
  '',
  'var d = 4;'
]

var range = {
  start: {
    lnum: 4, col: 1
  },
  end: {
    lnum: 5, col: 11
  }
}
```

Applying this the server will delete the line `5` and the state will become:
```
1:var a = 1;
2:var b = 2;
3:var c = 3;
4:
5:var d = 4;
```

The problem with this example is that depending whether the change is a line split or not, Vim reports it differently without actually telling that it was a line split. Of course it would be possible to include something like `is_split` to the callback data, but then it means more edge cases to cover. For "line change" and "line remove" cases there are different edge cases. Reporting the whole change as a before/after range is would solve everything.

> Column ranges are not always available.

This is fine. We can report the whole lines to LSP server. So something like this would be sufficient:
```
{
  before: {
    start_lnum: <lnum>,
    end_lnum: <lnum>
  },
  after: {
    start_lnum: <lnum>,
    end_lnum: <lnum>
  },
}
```

**Comment by brammool** [comment]
> > I don't see a problem with this, the change is reported properly.  You
> > know where it happened and that a line was added.
> 
> I will try to explain the problem in details:
> 
> This is a very simple algorithm I came up with to process the "lines inserted" case:
> ```vim
> var lines = getline(change.lnum, change.lnum + change.added)
> var range = {
>   start: {lnum: change.lnum, col: 1},
>   end:   {lnum: change.end,  col: lines[-1]->len() + 1}
> }
> ```

You are not using the "end" value here, therefore you may very well be
missing something.

> Let's take this pseudo code (for convenience each lines is prepended
> with `<lnum>:`):
> ```
> 1:var a = 1;
> 2:var b = 2;
> 3:var c = 3;
> 4:var d = 4;
> 5:var e = 5;
> ```

[...]

Another possible change is that lines 2 and 3 are replace by something
else, which takes up one more line:

  1:var a = 1;
  2:var b = 2222;
  3:var x = 3;
  4:var c = 333;
  5:var d = 4;
  6:var e = 5;

Now it will report lines 2-4 changed and one line inserted.  You will
need to be able to handle that as well.  It doesn't say where the line
was inserted, thus you have to assume all three lines are changed.

> Now let's go back to the original pseudo code. Do a split at the start
> of line `4` with `<CR>`. We get the same Vim buffer state as before:
> 
> ```
> 1:var a = 1;
> 2:var b = 2;
> 3:var c = 3;
> 4:
> 5:var d = 4;
> 6:var e = 5;
> ```
> 
> However this time Vim reports the change as:
> ```
> {'added': 1, 'lnum': 4, 'col': 1, 'end': 5}
> ```
> 
> Using the same algorithm we calculate this:
> ```javascript
> var lines = [
>   '',
>   'var d = 4;'
> ]
> 
> var range = {
>   start: {
>     lnum: 4, col: 1
>   },
>   end: {
>     lnum: 5, col: 11
>   }
> }
> ```

What is missing here is the information that a line was added.  It was
present in the report, you haven't used that information.

> Applying this the server will delete the line `5` and the state will become:
> ```
> 1:var a = 1;
> 2:var b = 2;
> 3:var c = 3;
> 4:
> 5:var d = 4;
> ```
> 
> The problem with this example is that depending whether the change is
> a line split or not, Vim reports it differently without actually
> telling that it was a line split. Of course it would be possible to
> include something like `is_split` to the callback data, but then it
> means more edge cases to cover. For "line change" and "line remove"
> cases there are different edge cases. Reporting the whole change as a
> before/after range is would solve everything.

The change reports are not going to change.  You'll have to make sure
you will interpret them correctly.


-- 
Behold the warranty!  The bold print giveth and the fine print taketh.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
so let's close it then.
