### ISSUE TITLE
Command already exists: add ! to replace it: MANPAGER call s:ManPager()

### ISSUE THREAD

**Issue by JaceeDai** [vim/vim#11388]
### Steps to reproduce

When I vim a file, no matter new one or existed one, I will encounter an error:
```
Error detected while processing /usr/share/vim/vim90/plugin/manpager.vim:
line    6:
E174: Command already exists: add ! to replace it: MANPAGER call s:ManPager()
Press ENTER or type command to continue
```

It seems *Apple M1 Max* brings the problem. But how can I fix it?

### Expected behaviour

No more annoying error alert

### Version of Vim

9.0.217

### Environment

macOS Monterey 12.6
Apple M1 Max

**Comment by k-takata** [comment]
What does `:verbose command MANPAGER` show?

**Comment by JaceeDai** [comment]
> 

Name              Args Address Complete    Definition
MANPAGER          0                        call s:ManPager() | delcommand MANPAGER

**Comment by JaceeDai** [comment]
> Did you use `:verbose`? It will show where the `MANPAGER` command is defined.

Sorry. Should it be like this:?

```
    Name              Args Address Complete    Definition
    MANPAGER          0                        call s:ManPager() | delcommand MANPAGER
        Last set from ~/.vim/plugin/manpager.vim line 5
```

**Comment by k-takata** [comment]
> Last set from ~/.vim/plugin/manpager.vim line 5

Okay, so you have installed manpager.vim locally. How about uninstalling it?

**Comment by k-takata** [comment]
BTW, I think that  a guard should be added to manpager.vim:
```diff
--- a/runtime/plugin/manpager.vim
+++ b/runtime/plugin/manpager.vim
@@ -2,6 +2,11 @@
 " Maintainer: Enno Nagel <ennonagel+vim@gmail.com>
 " Last Change: 2022 Sep 30
 
+if exists('g:loaded_manpager_plugin')
+  finish
+endif
+let g:loaded_manpager_plugin = 1
+
 " Set up the current buffer (likely read from stdin) as a manpage
 command MANPAGER call s:ManPager()
 
```

**Comment by JaceeDai** [comment]
> 



> BTW, I think that a guard should be added to manpager.vim:
> 
> ```diff
> --- a/runtime/plugin/manpager.vim
> +++ b/runtime/plugin/manpager.vim
> @@ -2,6 +2,11 @@
>  " Maintainer: Enno Nagel <ennonagel+vim@gmail.com>
>  " Last Change: 2022 Sep 30
>  
> +if exists('g:loaded_manpager_plugin')
> +  finish
> +endif
> +let g:loaded_manpager_plugin = 1
> +
>  " Set up the current buffer (likely read from stdin) as a manpage
>  command MANPAGER call s:ManPager()
>  
> ```

So you mean `~/.vim/plugin/manpager.vim` should be removed instead of the one from `vim90`？

But if it's so, I cannot modify the one in directory `vim90` to add any guard because of lacking root permission.

**Comment by JaceeDai** [comment]
> > Last set from ~/.vim/plugin/manpager.vim line 5
> 
> Okay, so you have installed manpager.vim locally. How about uninstalling it?

Finally I fix this by removing `~/.vim/plugin/manpager.vim`. Thank you!

**Comment by k-takata** [comment]
The above patch should be useful for avoiding this kind of errors in the future. Not necessary for this time.

**Comment by chrisbra** [comment]
closing for #11390
