### ISSUE TITLE
How can I reset g:terminal_ansi_colors to defaults?

### ISSUE THREAD

**Issue by eggbean** [vim/vim#11400]
I absolutely love using vim and gvim and use them on Linux and Windows.

With gvim I use the [PaperColor colour scheme](https://github.com/NLKNguyen/papercolor-theme), which is very nice, but on Windows it messes up the `cmd.exe` terminal colours so my `ls.exe` (port) `LS_COLORS` are all wrong.

There is an [explanation as to why here](https://github.com/NLKNguyen/papercolor-theme/issues/113#issuecomment-394048640), but I don't really understand it.

I tried setting `g:terminal_ansi_colors` but this didn't work, **but** when I accidentally added colours without the #hash signs, I got an error, but the `g:terminal_ansi_colors` were all reset to default and `LS_COLORS` displayed correctly, seemingly without any problem caused with using the theme on normal text buffers.

```
let g:terminal_ansi_colors = [
  \'282C34', 'E06C75', '98C379', 'E5C07B',
  \'61AFEF', 'C678DD', '56B6C2', 'DCDFE4',
  \'E9969D', 'B3D39C', 'EDD4A6', '8FC6F4',
  \'D7A1E7', '7BC6D0', 'F9F9FA', '5A6374' ]
```

The above results in resetting `g:terminal_ansi_colors`, but I get this error message:

```
E254: Cannot allocate colour 282C34
E475: Invalid argument: g:terminal_ansi_colors
```

So it seems to be possible to reset `g:terminal_ansi_colors`, as this error causes it to do that. How can I make gvim reset the terminal colours without causing an error?

I tried `let g:terminal_ansi_colors = []`, but it still came up with `E475: Invalid argument: g:terminal_ansi_colors` when starting the terminal, although it did sort out the `LS_COLORS` issue.

(Instead of resetting to default I would prefer to use the colours I have set above without the hash characters, but defaults would still be better than the messed up colours I get otherwise)

**Comment by chrisbra** [comment]
I may not understand the problem, but if you do not want to set the terminal colors, have you tried to remove/*unlet* the `g:terminal_ansi_colors` variable? That would be `:unlet! g:terminal_ansi_colors` (the bang is there so that vim does not complain in case the variable does not exist)
