### ISSUE TITLE
execute() cannot be used with customlist command completion

### ISSUE THREAD

**Issue by blueyed** [vim/vim#1141]
`execute()` appears to fail when being used in a completion function.

With the following Vim file, `MycommandRedir` will have completion, but `Mycommand` won't.

``` vim
function! MyComplete(ArgLead, ...)
  return [execute('echon 123')]
endfunction
function! MyCompleteRedir(ArgLead, ...)
  redir => r
  silent echon 123
  redir END
  return [r]
endfunction
command! -nargs=* -bar -complete=customlist,MyComplete Mycommand call Foo()
command! -nargs=* -bar -complete=customlist,MyCompleteRedir MycommandRedir call Foo()
```

This is not an issue with Neovim.

**Comment by lacygoill** [comment]
Fixed by https://github.com/vim/vim/commit/2095148277cf1c4e7b3bbaf4e34812b7cfe3011b.

**Comment by lacygoill** [comment]
And [this item](https://github.com/vim/vim/blob/e35a52aee718c881bdfa69a47a1068df6ab6c60a/runtime/doc/todo.txt#L1465-L1466) is no longer relevant.
