### ISSUE TITLE
Buffer with Apache configuration file has wrong commentstring on `filetype plugin on`

### ISSUE THREAD

**Issue by dubgeiser** [vim/vim#11417]
### Steps to reproduce

`set nocompatible`
`filetype plugin on`

In a buffer: `set ft=apache` and then `set commentstring`.
This shows `commentstring=/*%s*/`

Possible fix: https://github.com/dubgeiser/vim/commit/aa6bddb14a2407d8791c001434f9904401d86538

There are commenting-plugins that rely on the value of `commentstring`, for instance https://github.com/numToStr/Comment.nvim/issues/264 or https://github.com/tpope/vim-commentary/blob/master/README.markdown?plain=1#L35

It might be a good thing to include this?

### Expected behaviour

`commentstring=# %s`

### Version of Vim

9.0.217

### Environment

MacOSx
Kitty (xterm-kitty)
Bash 5.2.2(1)-release

**Comment by dubgeiser** [comment]
I can of course open a PR for my commit, but I thought I'd mention it first as per README instructions :)

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> `set nocompatible`
> `filetype plugin on`
> 
> In a buffer: `set ft=apache` and then `set commentstring`.
> This shows `commentstring=/*%s*/`
> 
> Possible fix:
> https://github.com/dubgeiser/vim/commit/aa6bddb14a2407d8791c001434f9904401d86538

This has just one line:

	setlocal commentstring=#\ %s

The file should have a header, like the other ftplugin files.  With the
check for b:did_ftplugin.

Also, "b:undo_ftplugin" should be set to undo the effect.

-- 
The problem with political jokes is that they get elected.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dubgeiser** [comment]
Thank you for taking the time to elaborate.
I'll make a clean PR.
