### ISSUE TITLE
Add Digital Signature for windows version

### ISSUE THREAD

**Issue by namoen0301** [vim/vim#1142]
PuTTY have been add it since 0.67
![sp20161002_111031](https://cloud.githubusercontent.com/assets/4280572/19018372/e1156e26-8890-11e6-95c2-a14b9a5820f1.png)

To help protect against tampering in transit from our website or after downloading, I think it's necessery to add it.

**Comment by namoen0301** [comment]
By the way, about Vim Installer, 
- Use NSIS 3.0 to build instead of 2.51
  Please add `unicode true` in nsi file to enable unicode support.
- Change UI to Modern UI
- MultiLanguage for Installer

**Comment by k-takata** [comment]
Are there any services that provide code signing without charge?

> Use NSIS 3.0 to build instead of 2.51

Vim-win32-installer already uses NSIS 3.0, but what is the merit of Unicode support?
Installing Vim to a directory with Unicode characters might cause troubles.
Or, is it needed for supporting translations of the installer?

**Comment by namoen0301** [comment]
just add `unicode true` in nsi file. 

# About code signing

Globalsign provide free signature for open source project:https://www.globalsign.com/ssl/ssl-open-source/

or https://www.certum.eu/certum/cert,offer_en_open_source_cs.xml

But Vim is a very famous project, You can find Digicert, Thawte Or comodo to get a digital signature

**Comment by chrisbra** [comment]
What problem does `unicode true` solve? About the other two points, could you provide a patch for that?

**Comment by k-takata** [comment]
> just add unicode true in nsi file.

I want ask you the purpose/merits of the setting.
(One obvious demerit would be that the installer won't work on Win9x, but it won't matter.)

> https://www.globalsign.com/en/ssl/ssl-open-source/

Hm, this seems SSL certificate. Maybe we can use this when we support HTTPS on www.vim.org (and this is requested several times, e.g. #671). But not for code signing?

> https://www.certum.eu/certum/cert,offer_en_open_source_cs.xml

Seems good, but this is up to Bram for the official installers.
Not sure we can use it safely on AppVeyor for the vim-win32-installer binaries.

**Comment by k-takata** [comment]
> Change UI to Modern UI

There are at least two versions to use MUI2:
- #279
- https://github.com/gpwen/vim-installer-mui2

(Don't know which is better/newer.)
They are already listed in the todo.txt:
https://github.com/vim/vim/blob/84dbd494dca599ecff05b2c2279d402c12e6d197/runtime/doc/todo.txt#L834-L845

**Comment by namoen0301** [comment]
SSL you can also use `Let's Encrypt` and get a free ssl

About code signing, I mean, Vim is a very famous open-source project, You can find Digicert, Thawte, Comodo... and so on, to get a free code signing certificate.

**Comment by brammool** [comment]
Liu Yixuan wrote:

> SSL you can also use `Let's Encrypt` and get a free ssl
> 
> About code signing, I mean, Vim is a very famous open-source project,
> You can find Digicert, Thawte, Comodo... and so on, to get a free code
> signing certificate.

Vim is still hosted on SourceForge, and they don't support SSL.

Not sure how SSL signing is related to signing a .exe.

## 

ARTHUR:        A scratch?  Your arm's off!
BLACK KNIGHT:  No, it isn't.
ARTHUR:        Well, what's that then?
BLACK KNIGHT:  I've had worse.
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
> https://www.certum.eu/certum/cert,offer_en_open_source_cs.xml

I checked this again. I thought this can be used without charge, but it was wrong. It's €14.00/year, not so expensive, but I suppose Bram wants to use money for Uganda children rather than code signing. ;-)
Don't know about other services.

**Comment by namoen0301** [comment]
## Other CA
- [Digicert](https://www.digicert.com) : admin@digicert.com or sales@digicert.com
- [Comodo](https://www.comodo.com) : sales@comodo.com
- [GlobalSign](https://www.globalsign.com) : sales-us@globalsign.com
- [Thawte](https://www.thawte.com) : support@thawte.com or cs-enterprise@thawte.com

**Comment by chrisbra** [comment]
@wbsdty331 please make clear, if you are talking about ssl encryption of the website or about signing the executable. Note also #671 and the referenced bug at [sourceforge](https://sourceforge.net/p/vimonline/bugs/104/)

**Comment by DemiMarie** [comment]
For the website, [Let's Encrypt](https://letsencrypt.org/) provides free certificates.

**Comment by jones77** [comment]
Think OP means signing the executable.  The SSL related information seems to be a red herring.

I'm behind a corporate firewall where you can't install unsigned, untrusted binaries.  Signing this for Windows would be helpful.

**Comment by stefan-wenig** [comment]
I'm looking for OSS projects that would like to test-drive our code signing service. For free-as-in-freedom projects it's free as in free beer. 

Prerequisites for a free OSS subscription and certificate: FLOSS license, source code on GitHub/Bitbucket/Gitlab, builds on AppVeyor.

How it works: 
1. get a free SignPath.io subscription from me
2. integrate your appveyor build with SignPath.io: https://about.signpath.io/documentation/build-system-integration/#appveyor
3. SignPath Foundation provides a code signing certificate

**Comment by chrisbra** [comment]
@stefan-wenig that sounds very interesting. What other open source projects are using your code signing service already?

@brammool we could test this with the vim/vim-win32-installer repository. I can have a look tomorrow.

**Comment by stefan-wenig** [comment]
So far: GitExtensions.

**Comment by chrisbra** [comment]
@stefan-wenig can you get me a SignPath.io subscription? If I read the documentation correctly, I need to disable the appveyor cache, is this right?

**Comment by stefan-wenig** [comment]
@chrisbra please contact me at stefan.wenig@signpath.io, I need your email address (the one you use for GitHub login)
Yes cache must be disabled so we can make sure that the build is 100% from source. Maybe you can disable cache only for specific builds, branches etc. - would have to check AppVeyor docs

**Comment by chrisbra** [comment]
thanks. I think I have set it up according to your docs. https://github.com/vim/vim-win32-installer/pull/118

**Comment by chrisbra** [comment]
@stefan-wenig BTW: it looks like the sample appveyor hook in the documentation https://about.signpath.io/documentation/build-system-integration/#appveyor has an extra linebreak between `<Organization_ID>` and `/Integrations/...`
I guess, that linebreak should not be there and the `/Integrations` belongs to the URL. At least, that confused me a bit.

**Comment by stefan-wenig** [comment]
I can see you already set up mutual permissions. Allow for a few days for release certificate issuance. You can use the test-signing policy right away.

Next step: Decide what you want to sign.

Simple: sign just the installer exe file. This removes SmartScreen warnings. (The initial default artifact configuration will do this.)

Advanced: Sign all executable files in your build. This is really how it should be done. Installation time signing removes the most visible problem, but security benefits immensely from deep signing.
Just create a ZIP file containing everything that needs to be signed at the end of your build (nested ZIPs are fine). Send a sample ZIP to support@signpath.io, we have a tool that creates the artifact config (not online yet)

However, while this would sign the standalone executables in gvim*.zip, it would not sign the files that your installer extracts. There are two ways to resolve this:
1. Switch to MSI installers. SignPath has native support for MSI deep signing. There are many other advantages to MSI too, mostly from a user perspective, but it's a bit more involved than NSIS for the developer.
2. Split your builds in two steps: build the executables (and sign them), then build the installer (and sign it) in another build configuration using another SignPath artifact configuration. I don't like it, AppVeyor and SignPath don't really support it, but it's possible.

**Comment by stefan-wenig** [comment]
> I guess, that linebreak should not be there and the `/Integrations` belongs to the URL. At least, that confused me a bit.

You're right, I'll have it fixed. Thanks!

**Comment by chrisbra** [comment]
I think I configured it to sign all `*.exe` artifacts. For now this is just to see if this works, so it should sign the installer. BTW: what signing-policy would you recommend? I have for now used test-signing, mainly because `release-signing` is pending (and it should probably only be used for official releases anyhow). 

Another thing, that was not clear to me: For which windows versions is the signature valid (e.g. Windows includes the relevant root CA certificate)? Or does it work out of the box? (I just tried the gitextensions installer and I did not get a warning message, so at least my Win 10 desktop system seems to be fine).

Regarding the installer: Switching the installer is a big step, @k-takata just recently did invest a huge amount of work to overhaul the current installer. I am sure he appreciates it to not do this again at this time ;)

Once the current setup works, we'll see how to make your second alternative work, I see you also provide Powershell scripts to do this, so perhaps this is an alternative.

**Comment by stefan-wenig** [comment]
> I think I configured it to sign all *.exe artifacts. 

Note that the path pattern must match a single artifact. If you want to sign more than one, create a ZIP file.

>I have for now used test-signing, mainly because release-signing is pending (and it should probably only be used for official releases anyhow).

Exactly. 

The test certificate is self-signed. See https://github.com/SignPath/Website/blob/v2/src/documentation/5_test_certificates.md (not yet published)

The release certificate will be from Thawte, accepted everywhere. Note that SmartScreen is different,  there will still be warnings in the first days: https://about.signpath.io/code-signing/windows-platform/#microsoft-smartscreen

> I am sure he appreciates it to not do this again at this time ;)

Understood.

> I see you also provide Powershell scripts to do this, so perhaps this is an alternative.

Only if you bring your own certificate. For OSS projects we provide free certificates under our Name (SignPath Foundation), which means we are the publisher, technically and legally, so you must follow a verifiable process. Our certificate guarantees that the binary was built from source. Currently we only support downloading artifacts from finished AppVeyor builds. 

So for now, if you want deep signing for NSIS installers, you'll have to break up your build. Sorry for the inconvenience.

**Comment by chrisbra** [comment]
thanks for the information.

I merged the PR yesterday, unfortunately, signing the executable [failed](https://ci.appveyor.com/project/chrisbra/vim-win32-installer/build/job/6tqx4ygx2aaq9cj4):

> Error calling webhook https://app.signpath.io/API/v1/47c0047c-0c1d-42b2-a16c-4ea6907dc813/Integrations/AppVeyor?SigningPolicyId=b060c819-3eff-411b-8b86-60d7e0161751: Response status code does not indicate success: 400 (Bad Request).

Perhaps you can have a look.

> So for now, if you want deep signing for NSIS installers, you'll have to break up your build. Sorry for the inconvenience.

Okay, so let me summarize:

1. for signing the executables inside the zip archive, we would send you the zip file, you analyze it and then we can adjust the appveyor configuration to have zip files signed.
2. for signing the executables inside the installer, we would need to break up our build scripts to sign all executables separately before creating the installer (that also needs to be signed). This could be avoided by using MSI installers. 
3. release certificates will come eventually and could then be used to manually sign the builds that e.g. Bram creates whenever he tags a new release.

I guess point 2 and 3 would be nice to have for the future, but for now I would be satisfied with a single signed nsis installer and all the binaries inside the zip file. 

Thanks for providing such a nice service!

**Comment by stefan-wenig** [comment]
> 400 (Bad Request)

Unfortunately, AppVeyor will not display error messages for fear of exposing secrets. We work around that by sending errors per e-mail to the notification address, just set it: https://app.signpath.io/Web/47c0047c-0c1d-42b2-a16c-4ea6907dc813/CIUsers/e3cc379e-2276-4047-89be-388657d688a2/ChangeNotificationEmailAddress

> 1. for signing the executables inside the zip archive, we would send you the zip file, you analyze it and then we can adjust the appveyor configuration to have zip files signed.

correct

> 2. for signing the executables inside the installer, we would need to break up our build scripts to sign all executables separately before creating the installer (that also needs to be signed). This could be avoided by using MSI installers.

correct

> 3, for signing the executables inside the installer, we would need to break up our build scripts to sign all executables separately before creating the installer (that also needs to be signed). This could be avoided by using MSI installers.

You'd just choose the release-signing policy ID for certain branches/tags https://www.appveyor.com/docs/branches/#build-on-tags-github-gitlab-and-bitbucket-only or using AppVeyor conditions (never tried that)

If you don't want to sign a certain build, just don't approve it in signpath.

> I guess point 2 and 3 would be nice to have for the future, but for now I would be satisfied with a single signed nsis installer and all the binaries inside the zip file.

Someone really needs to write a NSIS to WIX/MSI converter ;-)

Yes, siging the installer will solve the most annoying problem, i.e. SmartScreen and UAC installer warnings. But unsinged executables make me sad.

Maybe we can someday provide an easier way. 

> Thanks for providing such a nice service!

You're most welcome, and thanks for testing it!

**Comment by stefan-wenig** [comment]
> Someone really needs to write a NSIS to WIX/MSI converter ;-)

probably not gonna happen though http://lists.wixtoolset.org/pipermail/wix-users-wixtoolset.org/2016-February/001411.html

**Comment by chrisbra** [comment]
>>    400 (Bad Request)

> Unfortunately, AppVeyor will not display error messages for fear of exposing secrets. We work around that by sending errors per e-mail to the notification address, just set it: https://app.signpath.io/Web/47c0047c-0c1d-42b2-a16c-4ea6907dc813/CIUsers/e3cc379e-2276-4047-89be-388657d688a2/ChangeNotificationEmailAddress

Tried that and also verified my mail. But the last build failed again, but I did not receive an error Email 😕

**Comment by stefan-wenig** [comment]
>  I did not receive an error Email 

Will need to investigate that.

However, I found the error in AppInsights. You should be able to work around the problem by making a random change to your AppVeyor settings and saving them, seems we have a bug here for projects that have never been changed.

If this does not resolve the issue, here's some background: We're checking that settings have not been changed between build start and our settings verification. However, it seems that you have never changed your project settings at all, and we're incorrectly assuming settings/updated is always present. If the problem persist, please sign into your AppVeyor account and then mail me the response of https://ci.appveyor.com/api/projects/chrisbra/vim-win32-installer/settings (I don't have the permissions). Thanks!

**Comment by chrisbra** [comment]
thanks. I have made a random change, saved it, undone the change and saved again. Let's see what's happening tonight.

**Comment by chrisbra** [comment]
@stefan-wenig It worked now, well kind-of 😕 

I have enabled this for now only for the installer (`*.exe`). 

Here is the log for the 64bit build:
https://ci.appveyor.com/project/chrisbra/vim-win32-installer/build/job/px03unp2wauhm46m
and here for the 32bit build:
https://ci.appveyor.com/project/chrisbra/vim-win32-installer/build/job/i0a5tp3l4x7yr2qi

Snippet from the log:

> Collecting artifacts...
> Found artifact 'gvim_8.1.1222_x86.exe' matching 'gvim_*_x86.exe' path
> Found artifact 'gvim_8.1.1222_x86.zip' matching 'gvim_*_x86.zip' path
> Found artifact 'gvim_8.1.1222_x86_pdb.zip' matching 'gvim_*_x86_pdb.zip' path
> No artifacts found matching 'gvim_*_x64.zip' path
> No artifacts found matching 'gvim_*_x64_pdb.zip' path
> No artifacts found matching 'gvim_*_x64.exe' path
> Uploading artifacts...
> [1/3] gvim_8.1.1222_x86.exe (9,034,127 bytes)...100%
> [2/3] gvim_8.1.1222_x86.zip (17,756,702 bytes)...100%
> [3/3] gvim_8.1.1222_x86_pdb.zip (7,416,710 bytes)...100%
> for /f "delims=" %%i in (gitlog.txt) do set GITLOG=%%i
> set VIMVER=%APPVEYOR_REPO_TAG_NAME:~1%
> set URL=https://github.com/%APPVEYOR_REPO_NAME%/releases/download
> Deploying using Webhook provider
> Calling webhook https://app.signpath.io/API/v1/47c0047c-0c1d-42b2-a16c-4ea6907dc813/Integrations/AppVeyor?SigningPolicyId=b060c819-3eff-411b-8b86-60d7e0161751...OK
> Deploying using GitHub provider
> Creating "v8.1.1222" release for repository "vim/vim-win32-installer" tag "v8.1.1222" commit "c7400bbb3c7694637dc048deebbf82a56e028df3"...Skipped - release with tag "v8.1.1222" already exists
> Uploading "gvim_8.1.1222_x86.exe" to release assets...OK
> Uploading "gvim_8.1.1222_x86.zip" to release assets...OK
> Uploading "gvim_8.1.1222_x86_pdb.zip" to release assets...OK
> Build success

However, neither the github release page does contain the signed binaries:
https://github.com/vim/vim-win32-installer/releases/tag/v8.1.1222

And neither does the appveyor build artifacts page:
https://ci.appveyor.com/project/chrisbra/vim-win32-installer/build/job/i0a5tp3l4x7yr2qi/artifacts
https://ci.appveyor.com/project/chrisbra/vim-win32-installer/build/job/px03unp2wauhm46m/artifacts

However, I can see the artifacts on the signpath page: https://app.signpath.io/Web/47c0047c-0c1d-42b2-a16c-4ea6907dc813/SigningRequests (I think this page is only visible when logged in).

So is there a way to get these signed binaries back to the github releases page?

**Comment by chrisbra** [comment]
BTW: 
While Windows shows that the binary is signed, it still warns when running the installer. Looking into the details, it seems that Windows is missing a trusted CA certificate. I clicked on import certificate, but it still did not run smoothely :(

![grafik](https://user-images.githubusercontent.com/244927/56860124-2c8c1e00-6993-11e9-8c31-6d12b2298077.png)

(sorry only German, but I think you understand German :))

**Comment by stefan-wenig** [comment]
First, it's important to understand the distinction between test-signing and release-signing. Test-signing serves two purposes: Build and verify the signing process, and verify signatures on dedicated test systems. It uses self-signed certificates that are only accepted if installed. See my reply above

> The test certificate is self-signed. See https://github.com/SignPath/Website/blob/v2/src/documentation/5_test_certificates.md (not yet published)

> The release certificate will be from Thawte, accepted everywhere. Note that SmartScreen is different, there will still be warnings in the first days: https://about.signpath.io/code-signing/windows-platform/#microsoft-smartscreen

Getting release certificates issued takes a few days, including verification calls from the CA. Once we have it, I will install it and you can use it. Windows will accept the certifcate, and SmartScreen after a few days (didn't take long for GitExtensions).

Second, for now you need to manually upload signed releases to GitHub releases (or anywhere else). The reason is our automated verifaction process, which can only verify published AppVeyor artifacts, and AppVeyor does not allow replacing artifacts later.

Did you plan to release-sign every nightly release from master? Usually only (certain) release-branch builds are release-signed.

That said, there are things that AppVeyor could do to improve the situation (allow artifact updates, or chained builds, or a dedicatad SignPath step), and there are things we can do to automate uploads or assist automation, like dedicated Web APIs and Webhooks. Not sure which path we'll take, don't hold your breath just yet.

> (sorry only German, but I think you understand German :))

Ja klar, aber bei einem Issue das mit einem chinesischen Screenshot beginnt darf man ohnehin nicht wählerisch sein ;-)

**Comment by chrisbra** [comment]
> First, it's important to understand the distinction between test-signing and release-signing. Test-signing serves two purposes: Build and verify the signing process, and verify signatures on dedicated test systems. It uses self-signed certificates that are only accepted if installed. See my reply above

I see.

> Did you plan to release-sign every nightly release from master? Usually only (certain) release-branch builds are release-signed.

Yeah, that was my naive plan, yes. The release process for Vim is different than that of other OpenSource projects since every new patch will end up as a new tiny revision. 

The current process makes it sound like we'll need manual interaction and it won't be easily automated unfortunately. Since those test signatures are not really useful, I guess it doesn't make sense to deploy those builds yet. Once we have a release certificate, I'll try to upload the binaries every now and then (depending how time permits and I don't forget :))

> Ja klar, aber bei einem Issue das mit einem chinesischen Screenshot beginnt darf man ohnehin nicht wählerisch sein ;-)

;)

**Comment by stefan-wenig** [comment]
Your release-signing certificate has arrived and is installed. Please note that SmartScreen will still warn users until its clouds heuristics recognize it.

Unfortunately, I was not able to include the project name "Vim" in any part of the certificate. The reason is that Vim has been registered as trademark by several companies, and CAs must follow rules that don't this. (Also that's what took so long.)

To make sure that signatures are clearly attributed to the Vim project anyway, you will need to set the product name attribute of the gvim*.exe installer to "Vim": https://nsis.sourceforge.io/Docs/Chapter4.html#versioninfo
I suggest you also set the product version to the same value as vim.exe and gvim.exe while you're at it, as this will become a requirement in the future (to avoid inadvertently signing files from another build). BTW the product versions of vim.exe and gvim.exe seem to be formatted wrong (comma+space instead of dots).

One more thing: Since SignPath Foundation is the publisher from a code-signing perspective, there have to be some rules for signing. Could you please review this draft of a Code of Conduct for me and tell me if anything in it would be a problem for you? https://github.com/SignPath/Website/blob/v2/src/drafts/oss_policy.md

**Comment by stefan-wenig** [comment]
Unfortuantely your signing requests will keep failing until you set the installer's product name to Vim. Once you do, switch to the signing policy "release-signing" and you'll have your new CA-issued certificate. Or keep the test-signing policy and use release-signing only for certain builds (branches, tags...)

I found another problem: We always sign the first job in each build (currently x64), so you get gvim_*_x64.exe signed twice instead of x86 and x64. We'll implement multi-job support in the next sprint, which is expected to be live end of May.

Until then, you can either try to switch the job order in appveyor.yml (environment matrix) which will give you another environment for each buid, or just ask us to manually sign some builds for you at support@signpath.io

**Comment by stefan-wenig** [comment]
@chrisbra I believe you're just two small changes away from a perfectly signed release: add the product name, change the signing policy ID to release signing. if you need any help, feel free to ask here or at support@signpath.io.

**Comment by chrisbra** [comment]
@stefan-wenig thanks, I don't know how to set the product name for the installer. @k-takata do you know?
I just switched the signing-policy to release.

**Comment by k-takata** [comment]
Is it a version resource of the installer?
This one? https://nsis.sourceforge.io/Reference/VIAddVersionKey

**Comment by stefan-wenig** [comment]
According to the description that would be it, I'm not into NSIS though.

**Comment by chrisbra** [comment]
@k-takata sounds like it. The last signing-request failed I believe of this:

```
 <?xml version="1.0" encoding="utf-8" ?>
 <artifact-configuration xmlns="http://signpath.io/artifact-configuration/v1">
   <!-- Enter a description of what to sign or choose one of the ready to use samples -->
   <pe-file path="gvim*.exe" productName="Vim">
     <authenticode-sign />
   </pe-file>
 </artifact-configuration>
```

**Comment by k-takata** [comment]
So we need to add a patch something like this?

```diff
--- a/nsis/gvim.nsi
+++ b/nsis/gvim.nsi
@@ -87,6 +87,14 @@ RequestExecutionLevel highest
 !endif
 
 ##########################################################
+# Version resources
+
+VIAddVersionKey /LANG=${LANG_ENGLISH} "ProductName" "Vim"
+VIAddVersionKey /LANG=${LANG_ENGLISH} "CompanyName" "Vim Developers"
+VIAddVersionKey /LANG=${LANG_ENGLISH} "LegalTrademarks" "Vim"
+VIAddVersionKey /LANG=${LANG_ENGLISH} "FileDescription" "Vi Improved - A Text Editor"
+
+##########################################################
 # MUI2 settings
 
 !define MUI_ABORTWARNING
```

**Comment by chrisbra** [comment]
looks good. Can we test this in the vim-win32-installer repo?

**Comment by k-takata** [comment]
I think we can use the `patch` directory in vim-win32-installer before including this.
Could you try it?

**Comment by chrisbra** [comment]
Yes, that was what I meant. Will create a PR for that later today, thanks.

**Comment by k-takata** [comment]
Sorry, the patch was wrong. `${LANG_ENGLISH}` was not defined at that point.
I hope this should work:

```diff
diff --git a/nsis/gvim.nsi b/nsis/gvim.nsi
--- a/nsis/gvim.nsi
+++ b/nsis/gvim.nsi
@@ -173,6 +173,14 @@ Page custom SetCustom ValidateCustom
     !include "lang\tradchinese.nsi"
 !endif
 
+##########################################################
+# Version resources
+
+VIAddVersionKey /LANG=${LANG_ENGLISH} "ProductName" "Vim"
+VIAddVersionKey /LANG=${LANG_ENGLISH} "CompanyName" "Vim Developers"
+VIAddVersionKey /LANG=${LANG_ENGLISH} "LegalTrademarks" "Vim"
+VIAddVersionKey /LANG=${LANG_ENGLISH} "FileDescription" "Vi Improved - A Text Editor"
+
 
 # Global variables
 Var vim_dialog
```

**Comment by k-takata** [comment]
Updated again:

```diff
--- a/nsis/gvim.nsi
+++ b/nsis/gvim.nsi
@@ -173,6 +173,17 @@ Page custom SetCustom ValidateCustom
     !include "lang\tradchinese.nsi"
 !endif
 
+##########################################################
+# Version resources
+
+VIAddVersionKey /LANG=${LANG_ENGLISH} "ProductName" "Vim"
+VIAddVersionKey /LANG=${LANG_ENGLISH} "CompanyName" "Vim Developers"
+VIAddVersionKey /LANG=${LANG_ENGLISH} "LegalTrademarks" "Vim"
+VIAddVersionKey /LANG=${LANG_ENGLISH} "LegalCopyright" "Copyright (C) 1996"
+VIAddVersionKey /LANG=${LANG_ENGLISH} "FileDescription" "Vi Improved - A Text Editor"
+VIAddVersionKey /LANG=${LANG_ENGLISH} "FileVersion" "${VER_MAJOR}.${VER_MINOR}.0.0"
+VIProductVersion "${VER_MAJOR}.${VER_MINOR}.0.0"
+
 
 # Global variables
 Var vim_dialog

```

**Comment by chrisbra** [comment]
Finally, signing the daily artifact using release signing happened yesterday successfully. I manually uploaded a signed 64 bit installer to the release section on the vim-win32-installer:
https://github.com/vim/vim-win32-installer/releases/tag/v8.1.1336

@stefan-wenig would it be possible to create stable URLs for downloading the artifacts? So instead of 
https://app.signpath.io/Web/47c0047c-0c1d-42b2-a16c-4ea6907dc813/SigningRequests/1d6db0ad-c662-46d6-9cd1-17eeaaff0b6c/DownloadSignedArtifact

which does not contain the SigningRequest ID as part of the URL but e.g. the binary and Version Number so we could add the link easily to the github release page?

**Comment by stefan-wenig** [comment]
Congratulations! 
We've been thinking about new APIs (e.g. 
build job ID) and/or notification Webhooks that you can react to. Product manager is on a sailing trip though, so non-emergency changes will be a month at least.

**Comment by chrisbra** [comment]
@stefan-wenig thanks there is no hurry. For the time being, I'll upload new signed releases every once in a while. And to get the zip files signed as well, that is still on my personal todo list.

@brammool how about applying this additional patch for the nsis installer so set the version number and name? https://github.com/vim/vim-win32-installer/blob/master/patch/01_nsis_progname.patch

**Comment by brammool** [comment]
> @stefan-wenig thanks there is no hurry. For the time being, I'll upload new signed releases every once in a while. And to get the zip files signed as well, that is still on my personal todo list.
> 
> @brammool how about applying this additional patch for the nsis installer so set the version number and name? https://github.com/vim/vim-win32-installer/blob/master/patch/01_nsis_progname.patch

That looks harmless, I'll include it.

-- 
If you had to identify, in one word, the reason why the
human race has not achieved, and never will achieve, its
full potential, that word would be "meetings."

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by stefan-wenig** [comment]
@chrisbra I manually created a signing request for the x86 version of v8.1.1359
Just tell me when you want to upload a release version, I'll do it again. Multi-job support will be deployed with the next version.

**Comment by chrisbra** [comment]
@stefan-wenig thanks, I have approved and uploaded the artifact to https://github.com/vim/vim-win32-installer/releases/tag/v8.1.1359

**Comment by namoen0301** [comment]
OK It seems works good, But...

![1](https://user-images.githubusercontent.com/4280572/58146414-99d85980-7c88-11e9-8d57-79bf44889f83.png)
* This description is too long, How about change to `VI Improve Installer` ?

**Comment by k-takata** [comment]
@chrisbra 
> Where is that shown?

I can see it at the UAC dialog box.

**Comment by chrisbra** [comment]
ah that seems to come from the certificate. Perhaps @stefan-wenig knows how to adjust that.

**Comment by stefan-wenig** [comment]
It's hard coded. We weren't aware that UAC shows the entire descrtiption. Unfortunately, no two code signing mechanims act the same. We'll shorten it significantly asap.

**Comment by chrisbra** [comment]
@brammool How about including this patch to the nsis installer:
https://github.com/vim/vim-win32-installer/blob/master/patch/01_patchlevel_nsis_installer.patch

It simply adds the Patchlevel to the Productversion of the installer.

**Comment by brammool** [comment]
Christian wrote:

> @brammool How about including this patch to the nsis installer:
> https://github.com/vim/vim-win32-installer/blob/master/patch/01_patchlevel_nsis_installer.patch
> 
> It simply adds the Patchlevel to the Productversion of the installer. 

Yes, that looks fine.

-- 
Have you heard about the new Beowulf cluster? It's so fast, it executes
an infinite loop in 6 seconds.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by stefan-wenig** [comment]
News:

* SignPath now supports multiple jobs per AppVeyor build (fetches both x86 and x64 automatically)
* The UAC string now only shows `gvim_8.1.1432_x64_signed.exe by github.com/vim/vim-win32-installer` (the vim-win32-installer part is not essential, but that was the quick fix)

I'll report back when we provide a mechanism for automatic release uploads.

**Comment by chrisbra** [comment]
I think this can be closed
