### ISSUE TITLE
<Home> key broken when using tmux (regression introduced by patch 9.0.0791)

### ISSUE THREAD

**Issue by dpelle** [vim/vim#11429]
### Steps to reproduce

Starting with Vim-9.0.0791, the \<Home> key no longer works as expected when running Vim in tmux.

Pressing `<Home>` capitallzes the character under the cursor and does not move the cursor instead of moving the cursor to the beginning of the line.

Steps to reproduce:

1. Start tmux
2. In tmux, run vim with:  `vim --clean -c 'norm iaaa'`
3. press the Home key
4. Observe the character `a` under the cursor gets capitalized and the cursor does not move (bug!)

The bug does not happen without tmux.

The patch that introduces the regression is:
```
commit a353282c13287058fde95bb6eb914e342fd4253c (tag: v9.0.0791)
Author: Trygve Aaberge <trygveaa@gmail.com>
Date:   Tue Oct 18 19:22:25 2022 +0100

    patch 9.0.0791: at the hit-Enter prompt the End and Home keys may not work

    Problem:    At the hit-Enter prompt the End and Home keys may not work.
    Solution:   Use the special "@" code for End and Home, like it was done for
                the cursor keys in patch 8.2.2246. (Trygve Aaberge, closes #11396)
```

CC: [trygveaa](https://github.com/trygveaa)

### Expected behaviour

Expected behavior: pressing \<Home> key in normal mode should go to the first character of the line and should not alter the character under the cursor.

### Version of Vim

vim-9.0.0814

### Environment

Operating system: xubuntu-18.04.6 (x86_64) or macOS-12.6 (M1)
tmux: latest from git, SHA1 https://github.com/tmux/tmux/commit/5ce34add77fa3517a01e63b915c5f4e3241af470
terminal: xfce4-terminal-0.8.7.4 on xubuntu or alacritty-0.11.0 on macOS

I don't think the OS, version of tmux or terminal really matter.

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> Starting with Vim-9.0.0791, the <Home> key no longer works as expected when running Vim in tmux.
> 
> Pressing `<Home>` capitallzes the character under the cursor and does not move the cursor instead of moving the cursor to the beginning of the line.
> 
> Steps to reproduce:
> 
> 1. Start tmux
> 2. In tmux, run vim with:  `vim --clean -c 'norm iaaa'`
> 3. press the Home key
> 4. Observe the character `a` under the cursor gets capitalized and the cursor does not move (bug!)
> 
> The bug does not happen without tmux.
> 
> The patch that introduces the regression is:
> ```
> commit a353282c13287058fde95bb6eb914e342fd4253c (tag: v9.0.0791)
> Author: Trygve Aaberge ***@***.***>
> Date:   Tue Oct 18 19:22:25 2022 +0100
> 
>     patch 9.0.0791: at the hit-Enter prompt the End and Home keys may not work
> 
>     Problem:    At the hit-Enter prompt the End and Home keys may not work.
>     Solution:   Use the special "@" code for End and Home, like it was done for
>                 the cursor keys in patch 8.2.2246. (Trygve Aaberge, closes #11396)
> ```
> 
> CC: [trygveaa](https://github.com/trygveaa)
> 
> ### Expected behaviour
> 
> Expected behavior: pressing <Home> key in normal mode should go to the first
> character of the line and should not alter the character under the cursor.

Can you use the channel log to see what the raw key code is that causes a
problem?  I suppose it doesn't change with the patch, but the way it is
interpreted.  Perhaps Trygve can figure out why this happens with tmux only.

-- 
Lower life forms have more fun!

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dpelle** [comment]
The happens not only happens with the `tmux` terminal multiplexer but also with the `screen` terminal multiplexer.
Pressing Home seems to behave as if ~ was pressed which changes case.

I'm not sure whether it's a bug with vim or with tmux & screen.
Somehow the `End` key works but the `Home` key does not after patch 9.0.0791.
For now, I've reverted patch 9.0.0791 locally because it was driving nuts to have the case change when pressing the Home key.

**Comment by dpelle** [comment]
@brammool asked:

> Can you use the channel log to see what the raw key code is that causes a
problem?

Maybe I misunderstand, but this bug is not related to the channel feature,
since the bug happens even if I built vim tiny i.e. without the channel feature.

If I do `:call ch_log('ch_log.txt')`  I don't see such a `ch_log.txt`
being created since channel is not involved reproducing the bug.

Anyway, the following one-line change, found by trial and error, reverts
one line of patch 9.0.0791 and fixes the bug somehow, but I admit
I don't understand it:
```
diff --git a/src/term.c b/src/term.c
index 77ad08bf1..ea08b839c 100644
--- a/src/term.c
+++ b/src/term.c
@@ -877,7 +877,7 @@ static struct builtin_term builtin_termcaps[] =
     {K_KHOME,          "\033[1;*~"},
     {K_XHOME,          "\033O*H"},     // other Home
     {K_ZHOME,          "\033[7;*~"},   // other Home
-    {K_END,            "\033[@;*F"},   // Esc [ F or Esc 1 ; F
+    {K_END,            "\033[1;*F"},
     // {K_S_END,               "\033O2F"},
     // {K_C_END,               "\033O5F"},
     {K_KEND,           "\033[4;*~"},
```

What is strange, is that I revert the line related to `K_END`
and it fixes the Home key. I don't understand, but it appears
to work.  Hopefully @trygveaa can figure it out.

**Comment by trygveaa** [comment]
@dpelle: I can't reproduce with the same tmux version without any tmux config (or with my normal tmux config), in xfce4-terminal 1.0.4 if it matters. Do you have any tmux config? Have you tried without it?

Can you check what vim receives for the Home and End keys? In insert mode in vim in tmux, press Ctrl-v (or Ctrl-q) and then Home and see what appears. Do the same for End.

**Comment by dpelle** [comment]
@trygveaa wrote:

> I can't reproduce with the same tmux version without any tmux config (or with my normal tmux config), in xfce4-terminal 1.0.4 if it matters. Do you have any tmux config? Have you tried without it?

I can reproduce the bug even without a `~/.tmux.conf`, so it's not the cause of the bug.

For me, I can reproduce it on all systems I tried.
* on Linux xubuntu-18.04.6. I tried xterm 330, xfce4-terminal-0.8.7.4, mate-terminal-1.20.0
* on macOS 12.6. I tried with alacritty-0.11.0 and iTerm2-3.4.15.
* I can also reproduce it with either the tmux or screen terminal multiplexer.

I used a USB keyboard (Keychron C1 mechanical keyboard) on both Linux and macOS.
On the macbook, I also tried with the keyboard of the laptop, by pressing Fn + Left Arrow
for the Home key (since the macbook does not have a Home key) and that reproduces the
bug as well.

I can reproduce with no `.tmux.conf`, no `.vimrc`.

It would be interesting to see whether anybody else can reproduce this issue.

I remind the steps to reproduce:

* Start tmux (or screen) terminal multiplexer. The bug does not happen without either tmux or screen.
* In tmux (or screen), run vim with: `vim --clean -c 'norm iaaa'`
* press the `Home` key (on macbook without Home key, you can press Fn + Left Arrow instead) 
* Observe the character `a` under the cursor gets capitalized and the cursor does not move (bug!).
  Pressing Home again, `A` becomes `a`.  So it's as if `~` was pressed instead of `Home`.
  The bug happens in both normal and insert mode.

Changing this line which was modified by patch 9.0.791 fixes it (but my patch may not be correct):
```
diff --git a/src/term.c b/src/term.c
index 77ad08bf1..ea08b839c 100644
--- a/src/term.c
+++ b/src/term.c
@@ -877,7 +877,7 @@ static struct builtin_term builtin_termcaps[] =
     {K_KHOME,          "\033[1;*~"},
     {K_XHOME,          "\033O*H"},     // other Home
     {K_ZHOME,          "\033[7;*~"},   // other Home
-    {K_END,            "\033[@;*F"},   // Esc [ F or Esc 1 ; F
+    {K_END,            "\033[1;*F"},
     // {K_S_END,               "\033O2F"},
     // {K_C_END,               "\033O5F"},
     {K_KEND,           "\033[4;*~"},
```

on macOS (M1), I have:
```
$ screen --version
Screen version 4.00.03 (FAU) 23-Oct-06

$ tmux -V
tmux next-3.4
```

On xubuntu-18.04.6 (x86_64), I have:
```
$ screen --version
Screen version 4.06.02 (GNU) 23-Oct-17

$ tmux -V
tmux next-3.4
```

In all cases, I use the latest Vim 9.0.0820.
Bug happens with Vim huge as well as Vim tiny.

**Comment by trygveaa** [comment]
@dpelle: Please provide what vim received for Home and End as asked:

> Can you check what vim receives for the Home and End keys? In insert mode in vim in tmux, press Ctrl-v (or Ctrl-q) and then Home and see what appears. Do the same for End.

**Comment by dpelle** [comment]
@trygveaa wrote:

> Can you check what vim receives for the Home and End keys?
> In insert mode in vim in tmux, press Ctrl-v (or Ctrl-q) and
> then Home and see what appears. Do the same for End.

Sorry I missed that earlier.  I enter tmux (or screen), start vim with
`vim --clean` then I press `i` to enter insert mode and press
`ctrl-v` `Home` and I see:
```
^[[1~
```

(the first 2 characters ^[ being the 0x1b character according to
the `:ascii` command.

Whereas the same steps without running with tmux or screen,
I get:
```
^[OH
```

I see the same escape key sequence whether I have my 1-line patch
or not (the patch I gave in previous message).

**Comment by dpelle** [comment]
I just found a workaround for tmux by adding those lines
to my `~/.tmux.conf`:

```
# Found at https://stackoverflow.com/questions/18600188/home-end-keys-do-not-work-in-tmux
# This fixes Vim bug https://github.com/vim/vim/issues/11429
bind-key -n Home send Escape "OH"
bind-key -n End send Escape "OF"
```

I'm not sure if there are side effects, but 
so far it seems to be working fine.
But still, it's strange that since patch 9.0.0791,
those 2 lines are needed and were not needed earlier.

That does not fix the Home key when running Vim with
screen, but I normally don't use screen anyway (I use
tmux instead).

**Comment by trygveaa** [comment]
Hm, that's the same as I get. That the patch introduces this bug doesn't make any sense to me. I'll have to look into vim's key handling more in detail. However, I'm very busy the coming week, so it might take a while.

**Comment by trygveaa** [comment]
@dpelle: What is `TERM` set to inside tmux for you? Run `:!echo $TERM` in vim.

**Comment by habamax** [comment]
> Sorry I missed that earlier. I enter tmux (or screen), start vim with `vim --clean` then I press `i` to enter insert mode and press `ctrl-v` `Home` and I see:
> 
> ```
> ^[[1~
> ```

I can't reproduce with the latest vim (820) and tmux.

**Comment by dpelle** [comment]
@trygveaa asked:

> What is TERM set to inside tmux for you? Run :!echo $TERM in vim.

xterm-256color

Bug also happens when TERM is set to `xterm`  (prior to starting `tmux`) but then I don't have 256 colors, neither in tmux, nor in Vim, which does not looks nice.

I also tried with TERM being set to `screen` or `screen-256color`, Home then works, but Vim does not show colors (it's black and white) which is ugly.

I also tried with TERM being `tmux` (which behaves like `screen`).

With `tmux-256color`, I cannot even start tmux on macOS which says:
```
$ echo $TERM
tmux-256color

$ tmux
can't find terminfo database
```
... whereas on Linux, with `tmux-256color` I can start tmux, Home works in Vim, but vim does not show color (ugly).

All this was tried:
* with an empty `.tmux.conf`
* setting TERM in my `~/.bashrc` before starting a new terminal and tmux

Shouldn't Vim support `TERM` being set to screen, screen-256color, tmux or tmux-256color?

What is the value of `TERM` for you and what is your OS?

The only setup that works well for me is TERM being set to xterm-256color
and with the workaround in .tmux.conf:
```
# Found at https://stackoverflow.com/questions/18600188/home-end-keys-do-not-work-in-tmux
# This fixes Vim bug https://github.com/vim/vim/issues/11429
bind-key -n Home send Escape "OH"
bind-key -n End send Escape "OF"
```

I just found https://github.com/vim/vim/issues/3630 which suggest to install
Ubuntu package ncurses-term but it's already installed.

Maybe xubuntu-18.04.6 is too old. I can later today try on xubuntu-20.04 later.
But macOS-12.6 is not old at least.

**Comment by habamax** [comment]
> With `tmux-256color`, I cannot even start tmux on macOS which says:
> 
> ```
> $ echo $TERM
> tmux-256color
> 
> $ tmux
> can't find terminfo database
> ```

Have you tried to set it from within `.tmux.conf`:

```
set -g default-terminal "tmux-256color"
```

I don't have mac to test it and my linux distro is quite recent (fedora 36)

https://asciinema.org/a/W28c1N508W4R4rwN6mHt84JtI

Maybe tmux is old and/or terminfo is outdated

**Comment by trygveaa** [comment]
> xterm-256color
> 
> Bug also happens when TERM is set to `xterm` (prior to starting `tmux`) but then I don't have 256 colors, neither in tmux, nor in Vim, which does not looks nice.

Using any value other than `tmux`, `screen` or derivatives of those in tmux is not supported and will break things like this (not just home/end keys in vim). From the man page of tmux:

> The TERM environment variable must be set to ‘screen’ or ‘tmux’ for all programs running inside tmux.  New windows will automatically have ‘TERM=screen’ added to their environment, but care must be taken not to reset this in shell start-up files or by the -e option.
> 
> default-terminal terminal
>         Set the default terminal for new windows created in this session - the default value of the TERM environment variable. For tmux to work correctly, this must be set to ‘screen’, ‘tmux’ or a derivative of them.

> I also tried with TERM being set to `screen` or `screen-256color`, Home then works, but Vim does not show colors (it's black and white) which is ugly.
> 
> I also tried with TERM being `tmux` (which behaves like `screen`).

If you don't get colors you have most likely enabled `termguicolors` in vim. This only works out of the box in xterm unfortunately.  See `:help xterm-true-color` and `:help tmux-integration`.

Note that screen does not support `termguicolors`, so you'll not get colors at all in screen with this option enabled. But in tmux it should work after setting `t_8f` and `t_8b` as mentioned in those help pages.

> With `tmux-256color`, I cannot even start tmux on macOS which says:
> 
> ```
> $ echo $TERM
> tmux-256color
> 
> $ tmux
> can't find terminfo database
> ```

You should try without setting `TERM` at all, and see what happens on macOS. But if it can't find terminfo for `tmux-256color`, that sounds like a broken tmux installation. `tmux-256color` usually comes from ncurses, which tmux depends on.

> * setting TERM in my `~/.bashrc` before starting a new terminal and tmux

You should never set TERM in `~/.bashrc` or similar files, that will cause problems like this.

> Shouldn't Vim support `TERM` being set to screen, screen-256color, tmux or tmux-256color?

It does, but there are unfortunately some things vim only enables by default for xterm terms, like RGB colors mentioned above.

> What is the value of `TERM` for you and what is your OS?

I don't set TERM anywhere, so I have the defaults which is `tmux-256color` inside tmux, and `screen` inside screen. My OS is Arch Linux.

**Comment by dpelle** [comment]
I'm closing the issue since it happens because I used xterm-256color and with tmux it should be tmux-256color.
My understanding is that my Linux box is too old to have a proper tmux-256color and macOS does not come with tmux-256color in termcap.  For macOS, I found https://gpanders.com/blog/the-definitive-guide-to-using-tmux-256color-on-macos/ but this looks ugly.

Anyway, my 2-line workaround in ~/.tmux.conf works fine so I'm happy enough. 
And when I upgrade Linux, I hopefully don't need that workaround.

**Comment by brammool** [comment]
> @brammool asked:
> 
> > Can you use the channel log to see what the raw key code is that causes a
> > problem?
> 
> Maybe I misunderstand, but this bug is not related to the channel feature,
> since the bug happens even if I built vim tiny i.e. without the channel feature.

The channel log shows the raw key codes.  It's only available with the
+channel feature, but useful also for figuring things out unrelated to
channels and jobs.

> If I do `:call ch_log('ch_log.txt')`  I don't see such a `ch_log.txt`
> being created since channel is not involved reproducing the bug.

The log is started with call ch_logfile('logfile, 'w').

> Anyway, the following one-line change, found by trial and error, reverts
> one line of patch 9.0.0791 and fixes the bug somehow, but I admit
> I don't understand it:

I guess you don't have 'term' set to 'tmux', which will cause problems
like this.  If you care about colors, just set t_Co to 256 and it should
work.  You can also set 'ttymouse' to "sgr" for recent tmux versions.
I have this in my .vimrc:

	" When running inside tmux.
	if &term == "screen" || &term == "tmux"
	  set term=tmux
	  set <t_kb>=
	  fixdel
	  set t_Co=256
	  set ttymouse=sgr
	endif

> ```
> diff --git a/src/term.c b/src/term.c
> index 77ad08bf1..ea08b839c 100644
> --- a/src/term.c
> +++ b/src/term.c
> @@ -877,7 +877,7 @@ static struct builtin_term builtin_termcaps[] =
>      {K_KHOME,          "\033[1;*~"},
>      {K_XHOME,          "\033O*H"},     // other Home
>      {K_ZHOME,          "\033[7;*~"},   // other Home
> -    {K_END,            "\033[@;*F"},   // Esc [ F or Esc 1 ; F
> +    {K_END,            "\033[1;*F"},
>      // {K_S_END,               "\033O2F"},
>      // {K_C_END,               "\033O5F"},
>      {K_KEND,           "\033[4;*~"},
> ```
> 
> What is strange, is that I revert the line related to `K_END`
> and it fixes the Home key. I don't understand, but it appears
> to work.  Hopefully @trygveaa can figure it out.

The "@" is supposed to catch "1" only if a modifier follows, perhaps it
also catches the "1" in the home key?  Above the arrow_modifiers help
there is a short explanation.  It does smell like a bug.

I'll make a patch to check for a following semicolon.  That appears to avoid
the problem.  Please check.  If it works, can you add a test case in
test_termcodes.vim for this?

-- 
hundred-and-one symptoms of being an internet addict:
2. You kiss your girlfriend's home page.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
