### ISSUE TITLE
:set helpfile does nothing

### ISSUE THREAD

**Issue by swetepete** [vim/vim#11430]
### Steps to reproduce

```
vim

:set hf=some_directory

:help
```

If you set it to a directory or file that exists, it has no effect; :help opens the normal help.

### Expected behaviour

Open the specified file or directory as :help

### Version of Vim

8.2 Included patches: 1-3995, 4563, 4646, 4774, 4895, 4899, 4901, 4919

### Environment

Ubuntu 22, Bash, xterm

**Comment by brammool** [comment]
The docs clearly say that the value must be the name of the main help file.  Thus it should end in "doc/help.txt".
Something else is not expected to work.
