### ISSUE TITLE
Syntax highlighting occasionally spills out of comments

### ISSUE THREAD

**Issue by Risto-Stevcev** [vim/vim#1144]
Regardless of the language (JS/CSS/HTML/Purescript/etc), whenever there is a comments section, it occasionally spills out of it's section and everything below that section is highlighted as if it's a comment (even though it shouldn't be).

If I scroll up and down a few times, it returns back to normal, but sometimes if I continue scrolling up and down it will break again

**Comment by chrisbra** [comment]
please describe exact steps on how to trigger it. I think it might be caused by some inefficient syntax rules, but that is usually only a temporary problem and usually goes away after a redraw

**Comment by Risto-Stevcev** [comment]
I don't know exactly what steps trigger it, but it happens often enough that it becomes annoying. It seems to happen almost randomly, but I would say it happens at least a couple of times a week for me. Is there a potential race condition with syntax rules and redraws?

**Comment by chrisbra** [comment]
does it happen with particular filetypes?
If it happens only when actually performing some editing steps, I think this is unavoidable. If it happens with a particular filetype or syntax file while only viewing the file, it might be a bug. You might want to contact the syntax file maintainer. Also perhaps `:h :syn-sync` helps to workaround the problem for certain files.

**Comment by Risto-Stevcev** [comment]
It seems to happen with pretty much any comment type for any kind of language
The situation to make it happen is something like this:
1. I open up the file
2. If I scroll down it will ignore a closed comment, so it will show all of the rest of the code as if it's a comment when it isn't.
3. If I scroll up and down a few times, it might go away and render it properly. If I keep doing that after it renders ok, it reverts back to the bug again.

If the file is open and it isn't happening, it won't be an issue while it's open. If it does happen, it will remain like that until I close it.

**Comment by dpelle** [comment]
I have not seen this bug. I also find it surprising that it would happens on all syntax files.
Which version of vim are you using?
Can you try without any plugins?  i.e.  vim -u NONE --noplugin
It might be a problem with the terminal. Can you try another terminal? (xterm).

**Comment by Risto-Stevcev** [comment]
I'll try turning off plugins since that might be the most likely culprit I think. I'm on xterm so I doubt it's that since it's a pretty common terminal app.

**Comment by jottkaerr** [comment]
I have seen this happening for long comments where the number of lines is larger than the value given with `:syntax sync minlines=n`. If it happens again try this command with a higher value for `n` or execute `:syntax sync fromstart`. If it works and doesn't slow down your computer too much, you might want to put that command into a corresponding after/syntax/<syntaxname>.vim script.

**Comment by vim-ml** [comment]
> I'll try turning off plugins since that might be the most likely
> culprit I think. I'm on xterm so I doubt it's that since it's a pretty
> common terminal app.

I'd also check other sessions/views, for example, fo you have files in
.vim/views ?  (or in &viewdir if you configured it to something else)

If you remove them, does the problem persist?

## 

Mike Grochmal
key ID 0xC840C4F6

**Comment by Risto-Stevcev** [comment]
@jottkaerr Thanks, this happened in a file with a very long comment, and after I did `:syntax sync fromstart` it fixed the issue. I feel like this sort of thing shouldn't happen though, in the sense that the settings or how vim renders this shouldn't allow it to happen. I don't think this necessarily happens with other editors/IDEs, but I'm not 100% sure of that. I'll close the comment, but I think it makes sense to rethink how syntax highlighting is rendered.
