### ISSUE TITLE
What's wrong with Bram?

### ISSUE THREAD

**Issue by RestorerZ** [vim/vim#11443]
### Steps to reproduce

What's wrong with Bram?
The half-finished patch 9.0.0815 has been released for the third day (moreover, without a description), and there is still no reaction from Bram.

Что с Брамом?
Уже третий день как размещено полудоделанное исправление 9.0.0815 (к тому же без описания), а реакции со стороны Брама так и нет.

### Expected behaviour

At least something

Хоть что-то

### Version of Vim

9.0.0815

### Environment

All

**Comment by tonymec** [comment]
He's answered a thread "Strange patch 9.0.815" in the vim_dev mailing list and Google Group twice yesterday, the last time mentioning "…the info i"ll send later when I am back home." I don't know if he's in Switzerland, the Netherlands, Uganda or elsewhere.

Он вчера дважды ответил сообщение о "странном патче 9.0.815" в vim_dev спыске рассылки / Гугль группе, говоря об "информации, которую я позже пошлю, когда я вспять дома". Я не знаю, в Швейцарии ли он, в Нидерландах, в Уганде или где-нуибудь другое.

Best regards, с уважением,
Tony, Тоня.

**Comment by RestorerZ** [comment]
It's good that he's all right.
Then we are waiting for him to return and continue his wonderful work again.
Thank you for the good news.

Хорошо, что с ним всё в порядке.
Тогда ждём, когда он вернётся и вновь продолжит свою чудесную работу.
Спасибо за хорошие вести.

**Comment by bfrg** [comment]
For those who don't follow the official mailing list: https://groups.google.com/g/vim_dev/c/ivkq22t3LQM

**Comment by Shane-XB-Qian** [comment]
for some reason, cannot open that link, wish no something bad..
@brammool wish you keep health and strong, and fat. :-) aha.. and keep maintaining vim.

**Comment by brammool** [comment]
I have fallen ill and need to undergo some tests.  I'm hospital for the time being, they take good care for me here and my friends have managed to get my laptop to me, so I can do some stuff.  I'll slowly work away issues, crashes and other important things first.  Some things might have to wait until I'm back at my desk again, but I should be able to do most things.

The problem with commits had another reason: I changed the shell script setup to only tag a commit when it succeeds, but the script that fills in the text wasn't properly adjusted for that.  Plus a patch with unmatched quotes.  Sorry for that, I didn't notice until it was too late.  We should be back on track now, but a few older commits still need fixing up.

Thanks all for the kind words!  I don't need financial support, that is all covered.  The children in Uganda need that much more than me!
