### ISSUE TITLE
extend() "keep" flag behaves inconsistently for Funcref and Partial

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#11455]
### Steps to reproduce

1. Run `vim --clean`
2. Source the following file:
```vim
let g:bar = 123
call extend(g:, #{bar: { -> 'foo' }}, 'keep')
call extend(g:, #{bar: function('extend')}, 'keep')
```
3. Error on line 3 but not line 2:
```
Error detected while processing /tmp/tmp.vim:
line    3:
E704: Funcref variable name must start with a capital: bar
```

### Expected behaviour

No error on line 3

### Version of Vim

9.0.813

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

**Comment by zeertzjq** [comment]
Related: #1557, https://github.com/neovim/neovim/commit/43e9fad1c8835a3136f4db53c82608e034df2a5e

**Comment by zeertzjq** [comment]
I think this can be fixed by removing this check, which has become redundant after patch 8.2.2920:
```diff
diff --git a/src/dict.c b/src/dict.c
index 63b30e06b..869118669 100644
--- a/src/dict.c
+++ b/src/dict.c
@@ -1105,17 +1105,8 @@ dict_extend(dict_T *d1, dict_T *d2, char_u *action, char *func_name)
 	{
 	    --todo;
 	    di1 = dict_find(d1, hi2->hi_key, -1);
-	    if (d1->dv_scope != 0)
-	    {
-		// Disallow replacing a builtin function in l: and g:.
-		// Check the key to be valid when adding to any scope.
-		if (d1->dv_scope == VAR_DEF_SCOPE
-			&& HI2DI(hi2)->di_tv.v_type == VAR_FUNC
-			&& var_wrong_func_name(hi2->hi_key, di1 == NULL))
-		    break;
-		if (!valid_varname(hi2->hi_key, -1, TRUE))
-		    break;
-	    }
+	    if (d1->dv_scope != 0 && !valid_varname(hi2->hi_key, -1, TRUE))
+		break;
 
 	    if (type != NULL
 		     && check_typval_arg_type(type, &HI2DI(hi2)->di_tv,
```

BTW, this check also seems redundant after patch 8.2.2920:
```diff
diff --git a/src/eval.c b/src/eval.c
index 062fab0ac..2afce8119 100644
--- a/src/eval.c
+++ b/src/eval.c
@@ -1366,7 +1366,6 @@ get_lval(
 	    if (rettv != NULL && lp->ll_dict->dv_scope != 0)
 	    {
 		int prevval;
-		int wrong;
 
 		if (len != -1)
 		{
@@ -1375,17 +1374,8 @@ get_lval(
 		}
 		else
 		    prevval = 0; // avoid compiler warning
-		wrong = (lp->ll_dict->dv_scope == VAR_DEF_SCOPE
-			       && rettv->v_type == VAR_FUNC
-			       && var_wrong_func_name(key, lp->ll_di == NULL))
-			|| !valid_varname(key, -1, TRUE);
 		if (len != -1)
 		    key[len] = prevval;
-		if (wrong)
-		{
-		    clear_tv(&var1);
-		    return NULL;
-		}
 	    }
 
 	    if (lp->ll_valtype != NULL)
```

**Comment by zeertzjq** [comment]
I've created PR #11468 to fix this.

**Comment by brammool** [comment]
> BTW, this check also seems redundant after patch 8.2.2920:
> ```diff
> diff --git a/src/eval.c b/src/eval.c
> index 062fab0ac..2afce8119 100644
> --- a/src/eval.c
> +++ b/src/eval.c
> @@ -1366,7 +1366,6 @@ get_lval(
>  	    if (rettv != NULL && lp->ll_dict->dv_scope != 0)
>  	    {
>  		int prevval;
> -		int wrong;
>  
>  		if (len != -1)
>  		{
> @@ -1375,17 +1374,8 @@ get_lval(
>  		}
>  		else
>  		    prevval = 0; // avoid compiler warning
> -		wrong = (lp->ll_dict->dv_scope == VAR_DEF_SCOPE
> -			       && rettv->v_type == VAR_FUNC
> -			       && var_wrong_func_name(key, lp->ll_di == NULL))
> -			|| !valid_varname(key, -1, TRUE);
>  		if (len != -1)
>  		    key[len] = prevval;
> -		if (wrong)
> -		{
> -		    clear_tv(&var1);
> -		    return NULL;
> -		}
>  	    }
>  
>  	    if (lp->ll_valtype != NULL)
> ```

In the PR this was kept and adjusted, thus I assume the final word is
that we do need this check.  Now that I included the PR I suppose this
is all taken care of.

-- 
10E21 Picolos = 1 Gigolo

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
