### ISSUE TITLE
Syntax highlighting not showing up when a session is restored

### ISSUE THREAD

**Issue by Risto-Stevcev** [vim/vim#1145]
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 26 2016 10:00:18)

Arch Linux (kernel version 4.6.4-1-ARCH)

In this most recent version, restoring an existing session `vim -S session.vim` will not display syntax highlighting on any of the files. Typing in `setfile ...` doesn't change anything

**Comment by grochmal** [comment]
I cannot reproduce on the most recent arch (4.7.5-1-ARCH) with the same Vim (2016 Sep 12, compiled Sep 26 2016 10:00:18).

Remember that, inside the session file Vim does this:

```
if &syntax != 'c'
setlocal syntax=c
endif
```

Therefore if you do not have `syntax on` in `vimrc` (or have an explicit `syntax off` there) the highlighting will not come out.  Unfortunately `:syntax` is not considered an option by `sessionoptions` (it is not a `:set <stuff>`) therefore the value of `syntax on`, `syntax enable` or `syntax off` is not saved in the session.

**Comment by Risto-Stevcev** [comment]
Hmm, this is weird. The sessions I saved don't show syntax highlighting anymore, but new ones I make will. The strange thing is that when I open them up, the code is identical except for the differences in the files and buffers/tabs. Is there some kind of cacheing that vim does that might have messed things up?

**Comment by grochmal** [comment]
I've tried creating a session file with Vim 7.4 and load it into Vim 8.0, but that does not produce the syntax highlighting issue either.  The session file is just a set of Vim instructions so going through it and searching for `syntax` may be good debugging.

The only other thing that I can think of is a `.viminfo` containing something strange (viminfo is a cache of Vim instructions after all).

**Comment by Risto-Stevcev** [comment]
I tried the removing `.viminfo` and `.vimrc` and it had no effect. All of the syntax declarations are identical in both session files:

```
if &syntax != 'javascript'
setlocal syntax=javascript
endif
```

**Comment by lacygoill** [comment]
I have been constantly creating and restoring sessions for the last 3 years (used in various plugins, such as [this one](https://github.com/lacygoill/vim-session)).  I never encountered this issue; the syntax highlighting is always correctly applied in all my buffers.

If you can still reproduce the issue, you need to find a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example).  See this [faq entry](https://github.com/chrisbra/vim_faq/blob/de424bd8e08bcf0e6b1e0563ee49514dfed926ae/vim_faq.txt#L1153-L1228) for more info.

In particular, try to reproduce with no special configuration; i.e. with `--clean`:

    vim --clean -S session.vim

**Comment by lacygoill** [comment]
One thing which might help is to remove the `options` item from the `'sessionoptions'` option.
This makes sure that if you made some experiments and changed some options/mappings before saving a session, those will not be restored later.

**Comment by chrisbra** [comment]
Thanks, closing.
