### ISSUE TITLE
syntax region start cannot exactly match a keyword

### ISSUE THREAD

**Issue by balki** [vim/vim#11453]
### Steps to reproduce

Syntax file:
```vim
❯ cat syntax-foobar.vim 
syntax keyword foobarKeyword beginblock endblock lorem ipsum consequatur ratione

syntax region foobarDesc matchGroup=foobarKeyword start="\<beginblock\>" end="\<endblock\>" contains=NONE

highlight default link foobarKeyword Keyword
highlight default link foobarDesc Comment
```
Example file
```
❯ cat config.foobar            

lorem ipsum

beginblock
    lorem ipsum blah consequatur ratione
endblock

    beginblock
        lorem ipsum blah consequatur ratione
    endblock

consequatur blah blah ratione
```
Starting vim like below:
`❯ vim --clean -S ./syntax-foobar.vim config.foobar`

### Expected behaviour

The line between `beginblock` and `endblock`, should be identified as `foobarDesc`. They should be highlighted as a comment and the keywords within the block should not be highlighted as keywords (it says `contains=NONE`)

### Work around:

1. Prefix `\s*` to `start`

Drawback: Does not work if `beginblock` does not have whitespace before it. (see first block in example)

 ```vim
syntax region foobarDesc matchGroup=foobarKeyword start="\s*\<beginblock\>" end="\<endblock\>" contains=NONE
```
2. Remove `beginblock` as keyword.

Drawback: When `omnifunc=syntaxcomplete#Complete`, then `beginblock` is not completed

```vim
syntax keyword foobarKeyword endblock lorem ipsum consequatur ratione " beginblock
```

### Version of Vim

patch 9.0.0815

### Environment

Ubuntu, Gnome Terminal

**Comment by brammool** [comment]
This is working as intended, keyword matches always have priority.
If you want to use that region you must not use beginblock and endblock as a keyword.
