### ISSUE TITLE
Syntax coloring is broken after fold markers ending with trailing double quote in vimscript files

### ISSUE THREAD

**Issue by Aster89** [vim/vim#11458]
### Steps to reproduce

[![asciicast](https://asciinema.org/a/CPVU68z5rnIfxqYxXI4P9Fyrg.svg)](https://asciinema.org/a/CPVU68z5rnIfxqYxXI4P9Fyrg)

or

1. Run the command `echo -e 'let x = 1\n" folding {{{1\nlet y = 1' > foo.vim` in Bash,
2. open `foo.vim` and check that the syntax coloring is correct,
3. add a trailing `"` to line 2 and verify that the syntax coloring is broken on line 2 and 3.

(Why should I have a trailing `"` on <code>" {{{<i>n</i></code> lines? Honestly I don't remember. But I do remember I added them for a reason. Should it come to mind, I'll give this complementary info too.)

### Expected behaviour

Correct syntax coloring.

### Version of Vim

9.0, patch 1-813

### Environment

Operating system: up-to-date ArchLinux
Terminal: urxvt
Value of $TERM: rxvt-unicode-256color
Shell: bash

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> [![asciicast](https://asciinema.org/a/CPVU68z5rnIfxqYxXI4P9Fyrg.svg)](https://asciinema.org/a/CPVU68z5rnIfxqYxXI4P9Fyrg)
> 
> or
> 
> 1. Run the command `echo -e 'let x = 1\n" folding {{{1\nlet y = 1' > foo.vim` in Bash,
> 2. open `foo.vim` and check that the syntax coloring is correct,
> 3. add a trailing `"` to line 2 and verify that the syntax coloring is broken on line 2 and 3.

Why do you add that extra double quote, it seems out of place.
Just don't do that and it will be fine.

-- 
How To Keep A Healthy Level Of Insanity:
12. Sing along at the opera.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Aster89** [comment]
As I wrote,

> (Why should I have a trailing " on " {{{n lines? Honestly I don't remember. But I do remember I added them for a reason. Should it come to mind, I'll give this complementary info too.)

In the meanwhile, I'll certainly remove it.

**Comment by chrisbra** [comment]
this looks like a minor issue, so let me close it.

**Comment by Aster89** [comment]
It seems fixed now. Not sure when the fix happened, because I have built 9.0 patch 1-813 and run the repro in it, but the issue did not show.
