### ISSUE TITLE
virtual-text do not use background of 'wincolor'

### ISSUE THREAD

**Issue by rcasta74** [vim/vim#11462]
### Steps to reproduce

vim --clean -c "call prop_type_add('Test', {'highlight': 'SpecialKey'}) | echo getwinvar([{'text': 'Some text', 'props': [{'col': 1, 'type': 'Test', 'text': ' + '}]}]->popup_create({'line': 5, 'col': 20, 'maxwidth': 80, 'highlight': 'PMenu', 'border': [], 'borderchars': [' '], 'moved': 'any'}), '&wincolor')"

![image](https://user-images.githubusercontent.com/24571368/198832778-65f01cb6-dd97-4662-93e4-ff1a047046e8.png)

### Expected behaviour

Virtual text should use the value of `wincolor` (`PMenu` in the above example).

### Version of Vim

9.0.818

### Environment

Operating system: gentoo linux
Terminal: konsole
Value of $TERM: xterm-256color
Shell: zsh 5.9

**Comment by bfrg** [comment]
There is no virtual text in your example. What is the output of `:hi SpecialKey`?

And could you please use [fenced code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks)? It's a lot easier to read than tucking everything into one line.

**Comment by rcasta74** [comment]
Sorry, the virtual text is `text: ' + '` defined in the text properties.
In a script it would look like:
``` vim
vim9script
prop_type_add('Test', {'highlight': 'SpecialKey'})
var mytext = [{
  'text': 'Some text',
  'props': [{
    'col': 1,
    'type': 'Test',
    'text': ' + '
  }]
}]
mytext->popup_create({
    'line': 5,
    'col': 20,
    'maxwidth': 80,
    'highlight': 'PMenu',
    'border': [],
    'borderchars': [' '],
    'moved': 'any'
})
```
`getwinvar` was there only to prove that `wincolor` option was set as `PMenu` (but i missed to take it in the screenshot)
`SpecialKey` was just the first default highlight color without bg I took from `:hi` output for the test:
``` vim
:hi SpecialKey                                                                                                                                                                                                             
SpecialKey     xxx term=bold ctermfg=81 guifg=Cyan
```
