### ISSUE TITLE
Question-mark or forward-slash truncates a search-string

### ISSUE THREAD

**Issue by cponder** [vim/vim#11460]
### Steps to reproduce

Create a file with this in it:
```
foo/a
foo/b
foo/bar
foo?bar
Do a search by typing "/foo/bar" or "?foo?bar". It will highlight all occurrences of "foo", not just "foo/bar" or "foo?bar".
Note that "/foo?bar" and "?foo/bar" both work.

### Expected behaviour

I would expect the whole string to have been searched for.
I know that this has been a longstanding issue, and many people  have posted explanations on how to escape the embedded "/" or "?".


### Version of Vim

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 13 2022 09:35:02) Included patches: 1-3995, 4563, 4646, 4774, 4895, 4899, 4901, 4919 Modified by team+vim@tracker.debian.org Compiled by team+vim@tracker.debian.org Huge version without GUI. 

### Environment

Ubuntu 22.04
xterm-256color
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)


### Logs and stack traces

_No response_

**Comment by cponder** [comment]
Ok looking further, I see that there's an oprional "count" argument allowed:
?foo?2
/foo/2
Could you add an option to disable this?

**Comment by cponder** [comment]
And, honestly, why couldn't the syntax have been "2/foo" instead of "/foo/2", which would have allowed for "2/foo/bar" to work?

**Comment by cponder** [comment]
Based on this posting
https://vim.fandom.com/wiki/Searching_for_expressions_which_include_slashes
I tried re-mapping the '/' in my `~/.vimrc`
```
command! -nargs=1 / let @/ = <q-args>|set hlsearch
```
but it didn't work.

**Comment by vim-ml** [comment]
On 2022-10-29, Carl Ponder wrote:
> Based on this posting
> https://vim.fandom.com/wiki/Searching_for_expressions_which_include_slashes
> I tried re-mapping the '/' in my ~/.vimrc
> 
> command! -nargs=1 / let @/ = <q-args>|set hlsearch
> 
> but it didn't work.

That won't work because user-defined commands must begin with an
upper-case letter.  See

    :help user-commands

To remap a command such as /, you must use a mapping, such as this
example:

    :cnoremap <CR> <C-\>eescape(getcmdline(), '/')<CR><CR>:cunmap <lt>CR><CR>

See

    :help map-overview
    :help x_CTRL-\_e
    :help getcmdline()
    :helpgrep \cctrl-\\.\?e

and the mappings in the file

    $VIMRUNTIME/macros/less.vim

That mapping is probably too simple, but it worked in the few test
cases I tried.

HTH,
Gary

**Comment by vim-ml** [comment]
On 2022-10-29, Gary Johnson wrote:
> On 2022-10-29, Carl Ponder wrote:
> > Based on this posting
> > https://vim.fandom.com/wiki/Searching_for_expressions_which_include_slashes
> > I tried re-mapping the '/' in my ~/.vimrc
> > 
> > command! -nargs=1 / let @/ = <q-args>|set hlsearch
> > 
> > but it didn't work.
> 
> That won't work because user-defined commands must begin with an
> upper-case letter.  See
> 
>     :help user-commands
> 
> To remap a command such as /, you must use a mapping, such as this
> example:
> 
>     :cnoremap <CR> <C-\>eescape(getcmdline(), '/')<CR><CR>:cunmap <lt>CR><CR>
> 
> See
> 
>     :help map-overview
>     :help x_CTRL-\_e
>     :help getcmdline()
>     :helpgrep \cctrl-\\.\?e
> 
> and the mappings in the file
> 
>     $VIMRUNTIME/macros/less.vim
> 
> That mapping is probably too simple, but it worked in the few test
> cases I tried.

I got so involved in the problem of mapping <CR> that I forgot about
mapping /.  Here's a better example, again just fleshed out to the
point of working, but closer to a complete solution.

    :nnoremap / :call SlashEscape()<CR>/

    :function SlashEscape()
    :    cnoremap <CR> <C-\>eescape(getcmdline(), '/')<CR><CR>:cunmap <lt>CR><CR>
    :endfunction

Regards,
Gary

**Comment by cponder** [comment]
IUsing the above,  tried to search with the command "/foo/bar" but it gave me the error
```
E486: Pattern not found: foo\\   
```

**Comment by cponder** [comment]
Ok. And adding this seems to take care of the analogous case with ? search:
```
:nnoremap ? :call QuestionEscape()<CR>?
:function QuestionEscape()
:    cnoremap <CR> <C-\>eescape(getcmdline(), '?')<CR><CR>:cunmap <lt>CR><CR>
:endfunction
```
