### ISSUE TITLE
When `shortmess` contains `F` and we run `:cdo`, messages from autocommands are not always printed to the message-history

### ISSUE THREAD

**Issue by bfrg** [vim/vim#11471]
### Steps to reproduce

Run `vim --clean -S test.vim`, with

```vim
vim9script

set shortmess+=F
mkdir('/tmp/vim/', 'p')
writefile(['test'], '/tmp/vim/1')
writefile(['test'], '/tmp/vim/2')
writefile(['test'], '/tmp/vim/3')

augroup test
    autocmd!
    autocmd BufWinEnter * echomsg $'BufWinEnter: {expand('<amatch>')}'
    autocmd BufReadPost * echomsg $'BufReadPost: {expand('<amatch>')}'
augroup END

grep! test /tmp/vim/1 /tmp/vim/2 /tmp/vim/3
cdo! substitute/test/TEST
```

Output:
```
BufWinEnter: /tmp/vim/1
(1 of 3): test
"/tmp/vim/2" 1 line, 5 bytes
BufReadPost: /tmp/vim/2
BufWinEnter: /tmp/vim/2
(2 of 3): test
"/tmp/vim/3" 1 line, 5 bytes
BufReadPost: /tmp/vim/3
BufWinEnter: /tmp/vim/3
(3 of 3): test
```

The current output is inconsistent. Why isn't the `echomsg` from `BufReadPost` for `/tmp/vim/1` written to messages, but `BufWinEnter` is? In my opinion, there are two lines missing in the output:
```
"/tmp/vim/1" 1 line, 5 bytes
BufReadPost: /tmp/vim/1
```

If we remove `set shortmess+=F` and rerun the script, we get exactly that:
```
"/tmp/vim/1" 1L, 5B
BufReadPost: /tmp/vim/1
BufWinEnter: /tmp/vim/1
(1 of 3): test
"/tmp/vim/2" 1 line, 5 bytes
BufReadPost: /tmp/vim/2
BufWinEnter: /tmp/vim/2
(2 of 3): test
"/tmp/vim/3" 1 line, 5 bytes
BufReadPost: /tmp/vim/3
BufWinEnter: /tmp/vim/3
(3 of 3): test
```

Note that if we replace `echomsg` with `popup_notification()` in the script above, in total six autocommands are triggered as one would expect (`BufReadPost` and `BufWinEnter` for all three files that are edited).

### Expected behaviour

When `shortmess` contains the `F` flag, either Vim shouldn't give any file infos at all when running `:cdo`, or it should print them all consistently for every file edited in `:cdo`.

### Version of Vim

9.0.818

### Environment

Linux

**Comment by chrisbra** [comment]
Hm, 
I see the problem. 
We reset 'shortmess' option when jumping to the next error message, but not when loading the very first quickfix match.

This is done on purpose, to avoid, that any possible messages are hidden:

https://github.com/vim/vim/blob/98aeb2100c2759111f93f0f0857e93d98afdc88a/src/ex_cmds2.c#L653-L654


I guess to make it consistent, we should reset `p_shm` also a couple of lines above, like this:

```diff
diff --git a/src/ex_cmds2.c b/src/ex_cmds2.c
index 9c00b80b7..b20d8b572 100644
--- a/src/ex_cmds2.c
+++ b/src/ex_cmds2.c
@@ -541,7 +541,13 @@ ex_listdo(exarg_T *eap)
                buf = NULL;
            else
            {
+               // Clear 'shm' to avoid that the file message overwrites
+               // any output from the command.
+               p_shm_save = vim_strsave(p_shm);
+               set_option_value_give_err((char_u *)"shm", 0L, (char_u *)"", 0);
                ex_cc(eap);
+               set_option_value_give_err((char_u *)"shm", 0L, p_shm_save, 0);
+               vim_free(p_shm_save);

                buf = curbuf;
                i = eap->line1 - 1;
```

**Comment by bfrg** [comment]
Thank you, the patch fixes the above issue.

**Comment by brammool** [comment]
> I see the problem. 
> We reset 'shortmess' option when jumping to the next error message,
> but not when loading the very first quickfix match.
> 
> This is done on purpose, to avoid, that any possible messages are hidden:
> 
> https://github.com/vim/vim/blob/98aeb2100c2759111f93f0f0857e93d98afdc88a/src/ex_cmds2.c#L653-L654
> 
> 
> I guess to make it consistent, we should reset `p_shm` also a couple
> of lines above, like this:
> 
> ```diff
> diff --git a/src/ex_cmds2.c b/src/ex_cmds2.c
> index 9c00b80b7..b20d8b572 100644
> --- a/src/ex_cmds2.c
> +++ b/src/ex_cmds2.c
> @@ -541,7 +541,13 @@ ex_listdo(exarg_T *eap)
>                 buf = NULL;
>             else
>             {
> +               // Clear 'shm' to avoid that the file message overwrites
> +               // any output from the command.
> +               p_shm_save = vim_strsave(p_shm);
> +               set_option_value_give_err((char_u *)"shm", 0L, (char_u *)"", 0);
>                 ex_cc(eap);
> +               set_option_value_give_err((char_u *)"shm", 0L, p_shm_save, 0);
> +               vim_free(p_shm_save);
> 
>                 buf = curbuf;
>                 i = eap->line1 - 1;
> ```

Can you make a PR with this?  And a test for it.

We'll have this change for 'shortmess' four times then, better move it
to a couple of functions.

-- 
GOD: That is your purpose Arthur ... the Quest for the Holy Grail ...
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bfrg** [comment]
Fixed by https://github.com/vim/vim/commit/9aee8ec400fe617f6d82441c46a22d0cef6fa3e6.
