### ISSUE TITLE
VIM highlights valid POSIX shell syntax as errorneous

### ISSUE THREAD

**Issue by andrewshadura** [vim/vim#1147]
As I noted in [[1](/vim/vim/commit/6be7f8733f34333ed75f6e39425d73a6b2644379#commitcomment-19291297)], POSIX specifies both `$(…)` syntax and `$((…))`, see [§2.6.3](http://pubs.opengroup.org/onlinepubs/009604499/utilities/xcu_chap02.html#tag_02_06_03) and [§2.6.4](http://pubs.opengroup.org/onlinepubs/009604499/utilities/xcu_chap02.html#tag_02_06_04).

However, the current VIM version highlights both of those as invalid syntax when `#!/bin/sh` shebang is used.

**Comment by jamessan** [comment]
`:help ft-sh-syntax` describes how to make the sh syntax default to POSIX.

When you see the erroneous highlighting, does `:echo b:is_sh` show 1?  If so, then the auto-detection of whether `/bin/sh` is a POSIX shell didn't get triggered and you don't have `let g:is_posix = 1` in your vimrc, so the highlighting is defaulting to Bourne syntax.

**Comment by chrisbra** [comment]
Closing, as this behaviour is documented. Please ask user questions on the appropriate forums. Thanks.

**Comment by andrewshadura** [comment]
@chrisbra, why have you closed it? It is documented, yet it is wrong, and has to be changed.

**Comment by chrisbra** [comment]
I think it is configurable, so please read the relevant help section `:h ft-sh-syntax`

**Comment by andrewshadura** [comment]
I did read it, it didn’t answer my question. Korn shell isn’t the same as POSIX shell, and it’s 2016, there probably are very few machines having the original Bourne shell as `/bin/sh`. Is it good to still assume `/bin/sh` is non-POSIX-compliant?

**Comment by andrewshadura** [comment]
In any case, the comment in the source code isn’t correct.

**Comment by chrisbra** [comment]
I don't know. You might want to discuss this issue with Charles as maintainer of the file.

**Comment by andrechalella** [comment]
We're in 2025 and this is still infuriating. Does anyone use a `#!/bin/sh` shebang for non-POSIX compliant Bourne shell? "It's documented" is a bad response to this -- it's been decades people are suggesting that the default be made sensible (POSIX).

**Comment by dkearns** [comment]
#16939
