### ISSUE TITLE
`bufwinid({buf})` checks only in current tab page for windows that display `{buf}`

### ISSUE THREAD

**Issue by bfrg** [vim/vim#11478]
### Steps to reproduce

Not sure if that's a bug or intentional. If the current behavior is intentional please consider this an enhancement request.

1. Edit two files in two different tab pages: `vim --clean -p one two`.
2. Run: `:echo bufwinid('two')`
3. Result: `-1`
4. Expected: `1001`

### Expected behaviour

I would have expected `bufwinid()` to check all tab pages and not just the current one. The documentation doesn't say anything about the current behavior either.

I think it would be helpful if all tab pages were checked. Currently, we have to use `getwininfo()` or `getbufinfo()` to obtain the window ID of the window(s) where a buffer is displayed. Both are not very convenient because they return an entire dictionary of information including window variables and buffer variables, respectively, which can be a lot.

### Version of Vim

9.0.818

### Environment

Linux

**Comment by bfrg** [comment]
I completely forgot about `win_findbuf()` which does check in all tab pages. So, maybe the documentation on `bufwinid()` and `bufwinnr()` could mention that the functions check only the current tab page?

**Comment by Shane-XB-Qian** [comment]
```
	Only deals with the current tab page.
```

it said that, at third p near bottom.

**Comment by bfrg** [comment]
Thank you for pointing that out!
