### ISSUE TITLE
CSS syntax coloring - Lack of leading digit in front of decimal dot makes decimal dot syntax group wrong

### ISSUE THREAD

**Issue by Aster89** [vim/vim#11472]
### Steps to reproduce

See the coloring of `.` in the following snippet with and without the `0`.
```css
.some-class {
  --some-var: 0.2s;
}
```
When the `0` is not there, `:echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')` returns

  - for `.`, `['cssDefinition', 'cssAttrRegion']`,
  - for `2`, `['cssDefinition', 'cssAttrRegion', 'cssValueTime']`,
  - for `s`, `['cssDefinition', 'cssAttrRegion', 'cssValueTime', 'cssUnitDecorators']`

whereas if th `0` is there it returns

  - for `0`, `['cssDefinition', 'cssAttrRegion', 'cssValueTime']`,
  - for `.`, `['cssDefinition', 'cssAttrRegion', 'cssValueTime']`,
  - for `2`, `['cssDefinition', 'cssAttrRegion', 'cssValueTime']`,
  - for `s`, `['cssDefinition', 'cssAttrRegion', 'cssValueTime', 'cssUnitDecorators']`

### Expected behaviour

I expect the syntax coloring of `.` to be not dependent on whether there's a leading digit in front of it.

### Version of Vim

9.0, patch 1-813

### Environment

Operating system: up-to-date ArchLinux
Terminal: urxvt
Value of $TERM: rxvt-unicode-256color
Shell: bash

**Comment by chrisbra** [comment]
ping @jsit as runtime file maintainer for css (I hope this is the right person)

**Comment by Aster89** [comment]
@jsit , done.
