### ISSUE TITLE
cannot find -lieee

### ISSUE THREAD

**Issue by ghost** [vim/vim#1148]
I'm building VIM from tag 8.0.0022 with this conf:

./configure --with-features=huge \  
                --enable-pythoninterp \  
                --with-python-config-dir=/usr/lib/python2.7/config \  
                --with-features=huge \  
                -enable-perlinterp \  
                --enable-luainterp \  
                --enable-tclinterp \  
                --enable-rubyinterp \  
                --enable-cscope \  
                -with-tlib=ncursesw  
                 --prefix=/usr 

By making it I I got linking error "cannot find -lieee" whose option causing it?

**Comment by vim-ml** [comment]
Am 2016-10-05 12:44, schrieb peter73421:

> I'm building VIM from tag 8.0.0022 with this conf:
> 
> ./configure --with-features=huge \
> 
> --enable-pythoninterp \
> 
> --with-python-config-dir=/usr/lib/python2.7/config \
> 
> --with-features=huge \
> 
> -enable-perlinterp \
> 
> --enable-luainterp \
> 
> --enable-tclinterp \
> 
> --enable-rubyinterp \
> 
> --enable-cscope \
> 
> -with-tlib=ncursesw
> 
> --prefix=/usr
> 
> By making it I I got linking error "cannot find -lieee" whose option
> causing it?

Please use this forum not for user questions. That is for bugs only.
For user questions, we have vi.stackexchange.com or vim_use mailinglist.

I am going to close this issue.
