### ISSUE TITLE
`E1307` occurs when mutating a sublist of a constant list gotten from other script

### ISSUE THREAD

**Issue by kg8m** [vim/vim#11490]
### Steps to reproduce

1. Create a sample vimrc and a module script as following:
   * `vimrc`
     ```vim
     vim9script
     
     import './module.vim'
     
     def Main(): void
       const list = module.GetList()
       final sliced = list[0 : 1]
     
       add(sliced, 'z')
       echo string(sliced)
     enddef
     
     Main()
     ```
   * `module.vim`
     ```vim
     vim9script
     
     export def GetList(): list<string>
       return ['a', 'b', 'c']
     enddef
     ```
2. `Vim --clean -S vimrc`
3. We will see `E1307: Argument 1: Trying to modify a const any`

### Expected behaviour

We will see `['a', 'b', 'z']` at the step `3.`.

### Version of Vim

9.0.0827

### Environment

OS: macOS Monterey 12.6
Terminal: iTerm2 3.4.16
Value of $TERM: xterm-256color
Shell: zsh 5.9 (arm-apple-darwin21.3.0)

**Comment by bfrg** [comment]
Interestingly, it works when you add a type hint to the `final` variable:

```vim
vim9script

import './module.vim'

def Main(): void
  const list = module.GetList()
  final sliced: list<string> = list[0 : 1]

  add(sliced, 'z')
  echo sliced
enddef

Main()
```

**Comment by kg8m** [comment]
Thanks for the fix, Bram!
