### ISSUE TITLE
Return value of append() is inconsistent in empty buffer for empty list vs non-empty list

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#11498]
### Steps to reproduce

1. Run `vim --clean`
2. Run `:echo append(1, [])`
3. Prints `1`
4. Run `:echo append(1, ['foo'])`
5. Prints `0`

### Expected behaviour

Two calls return the same value

### Version of Vim

9.0.813

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

**Comment by zeertzjq** [comment]
Not sure if changing `lnum` to `lnum_arg` is the best solution:
```diff
diff --git a/src/evalbuffer.c b/src/evalbuffer.c
index e77435b8f..508089da6 100644
--- a/src/evalbuffer.c
+++ b/src/evalbuffer.c
@@ -176,7 +176,7 @@ set_buffer_lines(
 	if (l == NULL || list_len(l) == 0)
 	{
 	    // set proper return code
-	    if (lnum > curbuf->b_ml.ml_line_count)
+	    if (lnum_arg > curbuf->b_ml.ml_line_count)
 		rettv->vval.v_number = 1;	// FAIL
 	    goto done;
 	}
diff --git a/src/testdir/test_functions.vim b/src/testdir/test_functions.vim
index 938a839bf..0f103a4a4 100644
--- a/src/testdir/test_functions.vim
+++ b/src/testdir/test_functions.vim
@@ -939,9 +939,11 @@ endfunc
 func Test_append()
   enew!
   split
-  call append(0, ["foo"])
-  call append(1, [])
-  call append(1, test_null_list())
+  call assert_equal(0, append(1, []))
+  call assert_equal(0, append(1, test_null_list()))
+  call assert_equal(0, append(0, ["foo"]))
+  call assert_equal(0, append(1, []))
+  call assert_equal(0, append(1, test_null_list()))
   call assert_equal(['foo', ''], getline(1, '$'))
   split
   only
```

**Comment by chrisbra** [comment]
Doesn't the difference in the return code indicate, whether the append() call was successfull? So for:
`append(1, [])`, it means appending to the current buffer was not successfull, because of an empty list used?

**Comment by zeertzjq** [comment]
But `append(0, [])` also returns 0.

**Comment by zeertzjq** [comment]
And `append(1, [])` also returns 0 in a non-empty buffer.

**Comment by matveyt** [comment]
>it means appending to the current buffer was not successfull, because of an empty list used?

> Doesn't the difference in the return code indicate, whether the append() call was successfull? So for: `append(1, [])`, it means appending to the current buffer was not successfull, because of an empty list used?

@chrisbra You're perfectly right. But there's another point: `:put =[]` inserts an empty line w/o any error. So we've got a different behaviour and this doesn't look right.

I think that `append(1, [])` is valid and it should just append an empty line and return zero.

**Comment by zeertzjq** [comment]
> I think that `append(1, [])` is valid and it should just append an empty line and return zero.

This may break backward-compatibility.

**Comment by zeertzjq** [comment]
IIUC, `append(1, [])` in an empty buffer should return 0 before patch 8.2.0615. After patch 8.2.0615 it returns 1.

**Comment by zeertzjq** [comment]
And after patch 8.2.0615:
- `append(0, [])` still always returns 0.
- `append(1, ['foo'])` still always returns 0.
- `append(1, [])` still returns 0 in a non-empty buffer, but it return 1 in an empty buffer.

So it is now inconsistent.

**Comment by brammool** [comment]
> >it means appending to the current buffer was not successfull, because of an empty list used?
> 
> > Doesn't the difference in the return code indicate, whether the
> > append() call was successfull? So for: `append(1, [])`, it means
> > appending to the current buffer was not successfull, because of an
> > empty list used?
> 
> @chrisbra You're perfectly right. But there's another point: `:put
> =[]` inserts an empty line w/o any error. So we've got a different
> behaviour and this doesn't look right.

There is no direct relation to the (very old) :put command and a builtin
function.  Quite often we have made builtin functions do something else
than an existing command, exactly because we wanted different behavior.

> I think that `append(1, [])` is valid and it should just append an empty line and return zero.

No, it should not append anything, since the list is empty.  And not
appending anything is successful, thus returning zero makes sense.

-- 
"Making it up?  Why should I want to make anything up?  Life's bad enough
as it is without wanting to invent any more of it."
		-- Marvin, the Paranoid Android in Douglas Adams'
		   "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
