### ISSUE TITLE
builtin function can be shadowed inside a lambda

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#11508]
Consider the following script:
```vim
let Lambda = {abs -> abs(1)}
echo Lambda('')
echo Lambda({n -> n + 1})
```

The first `echo` prints `1`, while the second `echo` prints `2`, because builtin function `abs` is shadowed by the argument `abs` in the lambda.

I guess this behavior should not be changed, as it will break backward-compatibility, and quite easy to avoid. Maybe this should be documented though?

**Comment by brammool** [comment]
> Consider the following script:
> ```vim
> let Lambda = {abs -> abs(1)}
> echo Lambda('')
> echo Lambda({n -> n + 1})
> ```
> 
> The first `echo` prints `1`, while the second `echo` prints `2`, because builtin function `abs` is shadowed by the argument `abs` in the lambda.
> 
> I guess this behavior should not be changed, as it will break backward-compatibility, and quite easy to avoid. Maybe this should be documented though?

Yeah, I don't think we want to change behavior.  It's a local issue,
thus the author can see what happens.  It's not like it is causing
problems in another place where the author might not be aware of this
strange code.  Might also be difficult to decide to give a warning, it
can easily trigger warnings in code that is OK.  And when adding more
builtin function names it's very well possible an existing argument
(which is perfectly valid now) would use that name.

Not sure how to document it though, it's not just simple shadowing, it
depends on how it's done.  For example:

   let Lambda = {abs -> abs(abs)}
   echo Lambda(3)
   3

Now the function is not shadowed and the number three is passed as
expected.  I would have to dive into the code to find out what happens
in other cases.  Broadly speaking the string after "->" is interpreted
as an expression, and "abs" has been set in the context of that
expression.  I think that "abs()" would always be seen as a builtin
function here, no matter if there is an "abs" variable in the context.

-- 
If Pacman had affected us as kids we'd be running around in dark rooms,
munching pills and listening to repetitive music.
                       -- Marcus Brigstocke

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by zeertzjq** [comment]
I guess nothing needs to be done about this issue.
