### ISSUE TITLE
inconsistent virtualedit=onemore vs virtualedit=all in normal mode.

### ISSUE THREAD

**Issue by karoliskoncevicius** [vim/vim#1150]
My use case is that I am trying to yank some word and paste it at the end of line with an added space before the word. Could not do it, found the helpful "virtualedit" setting.

When I set it to "all" - I can move to the newline character (one cursor position after last character in the line) and paste a word - it will be pasted with additional whitespace before it just as I imagined. But when I do the same with "onemore" the same word get's pasted without any whitespace.

I thought that's one of the possible uses of 'virtualedit=onemore", but it does not work. Is this a bug or expected behavior?

**Comment by brammool** [comment]
This is expected behavior. With "all" Vim behaves as if there are spaces where there are not.  With "onemore" you can move the cursor to after the line, but it's not like there is a space there.
