### ISSUE TITLE
virtual text `below` cannot be placed below empty lines

### ISSUE THREAD

**Issue by bfrg** [vim/vim#11520]
### Steps to reproduce

1. Run `vim --clean test.vim -S test.vim`, with

```vim
vim9script

colorscheme habamax
prop_type_delete('test')
prop_type_add('test', {highlight: 'ErrorMsg'})
prop_add(2, 0, {
    type: 'test',
    text: 'The quick brown fox jumps over the lazy dog',
    text_align: 'below',
    text_padding_left: 1,
})
```
2. Result: there's no extra virtual line added below the empty line. In the example above, the virtual text should be placed below the 2nd line.
2. Move the cursor to the bottom by pressing `G`.
3. Result: cursor goes below the last buffer line.

Screenshot:
![screenshot-2022-11-08_031015](https://user-images.githubusercontent.com/6266600/200458333-c35b0a25-b451-4e04-a1a2-af76133ff20f.png)

Same as above but when `number` is enabled:
![screenshot-2022-11-08_031143](https://user-images.githubusercontent.com/6266600/200458338-1078f15d-0f0a-4a58-bccc-6cc072536d5e.png)

Only after text is inserted in the empty line, the virtual text is drawn correctly:
![screenshot-2022-11-08_031213](https://user-images.githubusercontent.com/6266600/200458340-f17c4b1a-0964-4a3e-9de1-f668ea41c780.png)

### Expected behaviour

When virtual text is added below an empty line using the attribute `below`, it should be drawn correctly below that empty line and not on that line.

### Version of Vim

9.0.840

### Environment

Linux

**Comment by porygonisaduck** [comment]
I'm interested in tackling this bug, can I be assigned to this issue?

**Comment by andrewjohnroy** [comment]
"test.vim" 11L, 261B
Error detected while processing command line..script C:\Users\aste9\test.vim:
line    3:
E185: Cannot find color scheme 'habamax'
Press ENTER or type command to continue

**Comment by bfrg** [comment]
@andrewjohnroy The colorscheme `habamax` is shipped with Vim. The error indicates that it's not installed on your system for some reasons. Which version of Vim do you have installed? You can also comment out that line. I added it because the colorscheme doesn't rely on your terminal color settings, so everyone gets the same appearance and it's easier to compare with the screenshots I provided.

**Comment by brammool** [comment]
> I'm interested in tackling this bug, can I be assigned to this issue? 

We don't use the github assignment feature.  Just work on it and let us
know about progress.  I'll make a note in my todo list that you are
associated with this issue.  If you are silent I may fix it once I get
there (but probably ping you first).


-- 
Master: Boy, there is nothing more for you to learn
Student: I didn't know that!

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by porygonisaduck** [comment]
Update: I tracked down the issue to src/drawline.c, specifically variables col_with_padding and padding. I have a version that works properly given the above test but I still need to run the other tests.

**Comment by brammool** [comment]
@porygonisaduck  did you make progress?  Perhaps you can create a PR (using draft mode if still working on it).

**Comment by porygonisaduck** [comment]
The version that worked locally failed some of the test cases so I am working on a different solution, I will create a PR.

**Comment by porygonisaduck** [comment]
I found the issue in the following code to be exact the variable is `before`. The specific problem is that the example above includes no value in line 2, if you had at least one space while writing the script it worked.

Do you have any insight into the code below?

`	    if (before < 0
		    || !(right || below)
		    || (below
			? (col_with_padding <= col_off || !wp->w_p_wrap)
			: (n_used < *n_extra)))
	    {
		if (right && (wrap
			      || (room < PROP_TEXT_MIN_CELLS && wp->w_p_wrap)))
		{
		    // right-align on next line instead of wrapping if possible
		    before = wp->w_width - col_off - strsize + room;
		    if (before < 0)
			before = 0;
		    else
			n_used = *n_extra;
		    skip_add = col_off;
		}
		else
		    before = 0;
	    }
	    else if (below && before > 0)
		// include 'number' column et al.
		skip_add = col_off;
	}`

**Comment by brammool** [comment]
> I found the issue in the following code to be exact the variable is
> `before`. The specific problem is that the example above includes no
> value in line 2, if you had at least one space while writing the
> script it worked.
> 
> Do you have any insight into the code below?

You'll just have to figure out what happens there in various situations.
It's very well possible that the computation of "before" is wrong in one
of those situations.  If you adjust those computations, you'll have to
check it is still correct in all other situations.

This whole process is iterative.  Every time we fix something we add a
test, making sure that test shows the correct results.  Then when fixing
another situation we check that the existing tests don't fail.

There really isn't another way, since there are so many features and
options that interfere with each other.  I was very well aware of this
when starting to add virtual text, which is why this feature is only
added now.  I anticipate quite a few bugs still need to be fixed.  It
will take time.

Anyway, thanks for diving into this.  If you are not sure how to make it
work, you can always just have some half-finished PR and others can try
to take over.

-- 
Support your right to bare arms!  Wear short sleeves!

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by porygonisaduck** [comment]
@brammool How would I create the test dump file?

**Comment by brammool** [comment]
> @brammool How would I create the test dump file?

1. Write the test, there you give the dump file a name.  There are
   plenty of examples around.

2. Run the test.  In the messages (also in testdir/messages) it will
   show a "call term_dumpload()" you can use.  Copy/paste this and check
   that what you see is exactly what the test output should be.

3. If the screendump is exactly right, move it from testdir/failed/ to
   testdir/dumps/  and add it to your PR.

4. Undo the source code change for a moment, run the test and check that
   that the test fails.  It will give you a term_dumpdiff() call to see
   the differences.


-- 
hundred-and-one symptoms of being an internet addict:
137. You decide to stay in college for an additional year or two,
     just so you can have the free Internet access.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
