### ISSUE TITLE
background color isn't painted when scrolling

### ISSUE THREAD

**Issue by mellowcandle** [vim/vim#1152]
Version: Vim 8.0, Arch Linux

example:
:colorscheme monokai

open a large file and keep going down using <j>. when the screen start scrolling the background isn't painted anymore.
Fixed by forcing repaint: <CTRL+L>

Even more weird. when recording it, it appears OK on the recording but not on the screen...
[reproduce animated gif](https://asciinema.org/a/2zpvo4s629joxoled5bd1j173)

**Comment by kamilchm** [comment]
@mellowcandle did you fix it somehow?
