### ISSUE TITLE
`shortmess+=c` not respected by "Pattern not found"

### ISSUE THREAD

**Issue by mawkler** [vim/vim#11530]
### Steps to reproduce

1. `> vim -u NONE`
2. `:set shortmess+=c`
3. `/foobar`
4. Vim prints `E486: Pattern not found: foobar`

### Expected behaviour

Vim doesn't output anything

### Version of Vim

9.0.813

### Environment

Operating system: Manjaro Linux x86_64
Terminal: Alacritty
Value of `$TERM`: tmux-256color
Shell: zsh

**Comment by Shougo** [comment]
It does not work for the search.
The c flag for the completion  messages

**Comment by melkster** [comment]
Aha that makes sense. Is there any plan to support suppressing the "Pattern" message for searches? Perhaps the `S` or `s` flag could include that?

**Comment by brammool** [comment]
Error messages are not to be suppressed by 'shortmess'.  I really see no reason to suppress this error, the user must be notified that no match was found.

**Comment by brammool** [comment]
The suppressed "Pattern not found" is not an error but a normal message.
Anyway, it appears you are not getting this from a typed search but from some script or function, thus you should be able to handle it there.

**Comment by melkster** [comment]
@brammool 

> it appears you are not getting this from a typed search but from some script or function

No, the message appears through a regular typed search without any configuration (`vim -u NONE`) as described in the issue.

> "Pattern not found" is not an error but a normal message

`:help E486` says:

> When no match is found you get the **error**: _E486_ Pattern not found

But regardless of whether you call it an error or a message I don't understand why it shouldn't be suppressible for searches when it already is for ins-completion-menu?

**Comment by zeertzjq** [comment]
I think Bram meant the "Pattern not found" from ins-completion-menu is a normal message.

**Comment by Shougo** [comment]
The `E486: Pattern not found: foobar` is error message.
You can see it in `:help E486`.  So suppress the error message is not `shortmess`'s work.
`shortmess` is just disables verbose normal messages.

**Comment by melkster** [comment]
> I think Bram meant the "Pattern not found" from ins-completion-menu is a normal message.

@zeertzjq I understand, but it isn't though. They are both prepended with `E486` and highlighted as errors by default.

**Comment by Shougo** [comment]
Hm...  It seems Vim's problem.

![2022-11-15_16-11-1668498844](https://user-images.githubusercontent.com/41495/201861139-5b14056f-a320-493b-af80-579c419b1a14.png)

![2022-11-15_16-11-1668498878](https://user-images.githubusercontent.com/41495/201861275-870496e4-49f3-4bfd-8849-539a6b956a7d.png)

neovim does not print `E486`, but Vim prints it.
If it is normal message, `E486` should not print.

**Comment by zeertzjq** [comment]
It was accidentally changed in patch 8.2.3967

**Comment by brammool** [comment]
> @brammool 
> 
> > it appears you are not getting this from a typed search but from some script or function
> 
> No, the message appears through a regular typed search without any
> configuration (`vim -u NONE`) as described in the issue.

Then it is appropriate to give the message.

> > "Pattern not found" is not an error but a normal message
> 
> `:help E486` says:
> 
> > When no match is found you get the **error**: _E486_ Pattern not found
> 
> But regardless of whether you call it an error or a message I don't
> understand why it shouldn't be suppressible for searches when it
> already is for ins-completion-menu?

The text "Pattern not found" is used in multiple places.

We don't suppress errors, because it's too easy for a user to make
mistakes with that.  Or a plugin writer suppresses an error and the user
doesn't know what is going on.

-- 
hundred-and-one symptoms of being an internet addict:
71. You wonder how people walk

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
you can use this to get the proper search stats into your statusline: https://vi.stackexchange.com/a/26304/71

**Comment by brammool** [comment]
> It was accidentally changed in patch 8.2.3967

Thanks for locating that.  I'll change it back.


-- 
hundred-and-one symptoms of being an internet addict:
74. Your most erotic dreams are about cybersex

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
