### ISSUE TITLE
E15: Invalid expression ""foo" ==? "foo"" in "if ... elseif ..."

### ISSUE THREAD

**Issue by xvim64** [vim/vim#11534]
### Steps to reproduce

1. gvim.exe --clean t.vim
2. :set gfn=consolas:h20
3. input "if ... elseif ..."
```
if "foo" ==? "foo"
    echo "first"
elseif "foo" ==? "foo"
    echo "second"
endif
```
4. :w
5. :so %

Why is 'elseif "foo" ==? "foo"' the invalid expression?

![1](https://user-images.githubusercontent.com/83569599/201481537-fb83e42c-b636-4c2d-9bd1-5c0e95cb709f.jpg)
![2](https://user-images.githubusercontent.com/83569599/201481539-06e26558-42f1-41b7-b588-6db0490026b0.jpg)
![3](https://user-images.githubusercontent.com/83569599/201481541-b91da717-3fb4-4a00-b4bc-f7bf292dde29.jpg)
![4](https://user-images.githubusercontent.com/83569599/201481542-02feb616-f089-41bd-be58-d75fa6a6a906.jpg)

### Expected behaviour

No E15 message

### Version of Vim

9.0.0861

### Environment

Windows 10 64bit

**Comment by brammool** [comment]
Steps to reproduce must be text, not screenshots.

**Comment by xvim64** [comment]
> Steps to reproduce must be text, not screenshots.

Added text of 'Steps of reproduce'

**Comment by brammool** [comment]
Thanks, now I can copy/paste and try it out.  I'll make a patch to fix it.
