### ISSUE TITLE
Unable to navigate to directories in netrw after switching to another app and returning

### ISSUE THREAD

**Issue by alistaircolling** [vim/vim#1153]
NVIM 0.1.6-dev
Build type: Debug

Vim 7.4 works as expected
OSX 10.10.5
iTerm 3.0.9

**Actual behaviour**
Open a directory containing other directories
Change to another application in the OS e.g. Chrome
Change back to iTerm
Select directory to open
Directory will not open

![3e1a5c28-80d3-11e6-8a2e-a99070c46f45](https://cloud.githubusercontent.com/assets/111540/19233223/142756f2-8edc-11e6-8fd0-081fc575b01b.gif)

**Expected behaviour**
Open a directory containing other directories
Change to another application in the OS e.g. Chrome
Change back to iTerm
Select directory to open
Directory will open

**Comment by justinmk** [comment]
Did you try with `set mouse=a` to see if this bug is reproducible in Vim? See https://github.com/neovim/neovim/issues/5375#issuecomment-248912693

**Comment by justinmk** [comment]
Also, did you intend to post this to Vim's issue tracker?

**Comment by alistaircolling** [comment]
Hi @justinmk I can't reproduce in vim with `set mouse=a`.

I thought I was in Vim's issue tracker! Is there somewhere else I should be reporting this?

Thanks :)

**Comment by justinmk** [comment]
I think my comment at https://github.com/neovim/neovim/issues/5375#issuecomment-249275732 was confusing. I suggested to report it in Vim's issue tracker, because I assumed it would be reproducible in Vim. Since you cannot reproduce it in Vim there must be some other problem.

**Comment by vim-ml** [comment]
Am 2016-10-11 11:36, schrieb Justin M. Keyes:

> I think my comment at neovim/neovim#5375 (comment) [1] was confusing.
> I suggested to report it in Vim's issue tracker, because I assumed it
> would be reproducible in Vim. Since you cannot reproduce it in Vim
> there must be some other problem.

Can I assume, this ticket can then be closed?

Best,
Christian

**Comment by justinmk** [comment]
I think it can be closed.
