### ISSUE TITLE
fstab highlight for ntfs3

### ISSUE THREAD

**Issue by Firestar-Reimu** [vim/vim#11542]
https://github.com/vim/vim/blob/master/runtime/syntax/fstab.vim

Since Linux 5.15, [ntfs3](https://docs.kernel.org/filesystems/ntfs3.html) provides read and write support for the file system.

ntfs3 requires the file system type to mount.

To be able to mount the file system, specify its type as ntfs3. For example, using [mount(8)](https://man.archlinux.org/man/mount.8)'s `-t/--types` option:

```
# mount -t ntfs3 /dev/sdxY /mnt
```

**Comment by zeertzjq** [comment]
It seems that <https://github.com/rid9/vim-fstab> hasn't had commits for two years.

**Comment by brammool** [comment]
Have you tried contacting Radu?  His email is in the header.

**Comment by chrisbra** [comment]
ping @rid9

**Comment by rid9** [comment]
@chrisbra, thank you for drawing my attention to this thread.

I updated the syntax file to add support for NTFS3, exFAT and a few other filesystems, as well as new options for some existing filesystems.

@Firestar-Reimu, @ObserverOfTime, you can find the updated version at https://github.com/rid9/vim-fstab/releases/tag/1.5.

@brammool, I also sent you an email with the new version.

**Comment by ObserverOfTime** [comment]
Thanks for the update. I noticed it's still missing `lazytime` and the less important [systemd options](https://manned.org/systemd.mount.5#head5).

**Comment by rid9** [comment]
@ObserverOfTime, I made another update to add support for `lazytime` and `systemd`, see https://github.com/rid9/vim-fstab/releases/tag/1.6.

**Comment by chrisbra** [comment]
seems to be included as of 7db29e4b5c3a347d24ca5062ddaa5cf4c4d54b9c so closing now.
