### ISSUE TITLE
cmdheight cannot be set to 0

### ISSUE THREAD

**Issue by wwwangzhou** [vim/vim#11543]
### Steps to reproduce

Add 
```
set cmdheight=0
```
to `.vimrc`

### Expected behaviour

According to https://github.com/vim/vim/commit/f39cfb72629f3e7fefaf578a3faa2619cd0654f8, cmdheight should be allowed to be set to 0.

### Version of Vim

9.0.850

### Environment

MacOS X

**Comment by zeertzjq** [comment]
https://github.com/vim/vim/commit/a2a8973e51a0052bb52e43a2b22e7ecdecc32003

**Comment by Shougo** [comment]
It is already reverted.

**Comment by brammool** [comment]
Yeah, we tried but there were too many problems, thus it was reverted.

**Comment by wwwangzhou** [comment]
Is it possible to bring that commit in by addressing the problems. Supporting `set cmdheight=0` can really help avoid wasted screen section at the very bottom. I believe there are some portion of vim users would love to have this flexibility.

**Comment by Shougo** [comment]
If you really need the feature, you should use neovim instead.
It is not stable feature yet.

The cmdheight feature is not just removes one line. It needs UI refinement.
So it cannot be accepted in Vim.
