### ISSUE TITLE
[request] Add class statement for vim9 please

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#11544]
The `class` feature is currently listed in todo.txt:

> Further Vim9 improvements, possibly after launch:
> - Use Vim9 for more runtime files.
> - implement :type
> - implement :enum
> - implement :class and :interface: See |vim9-classes|
> - Inline call to map() and filter(), better type checking.

Can we elevate the priority of the `class` statement a little bit ?
There are some strong reasons why `class` is essential. 

I want to use TypeScript and Lua to demonstrate how bad it will be when lacking a `class` keyword.

## Class in TypeScript and Lua

It is very straightforward to declare a class in TypeScript:

```typescript
class Person {
    private name: string;
    private age: number;
    private salary: number;

    constructor(name: string, age: number, salary: number) {
        this.name = name;
        this.age = age;
        this.salary = salary;
    }

    toString(): string {
        return `${this.name} ${this.age} ${this.salary}`;
    }
}
```

And also intuition to use it:

```TypeScript
var p = new Person("skywind", 18, 1800)
console.log(p.toString())
```

As a well knowing embedded language, Lua refused to introduce a `class` keyword for years because of the "Less is More" dogma.
And Lua keeps telling you to use some primitive mechanisms to simulate a `class`:

```Lua
Person = {}
Person.__index = Person

function Person:create(name, age, salary)
	local obj = {}
	setmetatable(obj, Person)
	obj.name = name
	obj.age = age
	obj.salary = salary
	return obj
end

function Person:toString()
	return self.name .. ' (' .. self.age .. ') (' .. self.salary .. ')'
end

local p = Person:create('skywind', 18, 1800)
print(p:toString())
```

What do you feel at first glance ? Totally a mess and hard to maintain if your code-base is big in size.
Not only because of the ugly `:` mark but also because it is too trivial to implement. 
You will not even know how you will die if you missed a single `Person.__index = Person` statement.

Many new technologies are invented to solve complexity by ending with introducing new complexity. 
Declaring a `class`, the most simple thing in other languages, is ugly in Lua.

So, some projects invent a `class` wrapper function to allow you to declare a class more easier:

```Lua
Account = class(function(acc,balance)
              acc.balance = balance
           end)

function Account:withdraw(amount)
   self.balance = self.balance - amount
end

-- can create an Account using call notation!
acc = Account(1000)
acc:withdraw(100)
```

Also not elegant, but it takes care of `setmetatable` things for you and prevents disasters if you forget something.

Now we have three methods to create an instance of the `Person` class:

```Lua
p = Person:create("project1", 18, 1800)
p = Person:new("project2", 18, 1800)
p = Person("project3", 18, 1800)
```

Project 1 uses `create` for construction while project 2 chooses `new`,  and project 3 uses `Person` as a constructor function.
The class defined in project 1 can not be constructed by the convention from project 2 and 3. 
The class defined in project 3 can not be inherited by project 1 and 2.

The lacking of a standard for class declaration makes it harder to share code between projects. A piece of code in project 1 is
always hard to be reused without modification in project 2/3. Human knowledge cannot be accumulated and collaborated, 
which leads to a fact: 

Despite that Lua was invented 21 years earlier than TypeScript, Lua has got less than 10k open-source projects in Github while 
TypeScript got 130k projects in Github.

Compared to TypeScript's class definition, it is easy to tell which one is more straightforward, elegant, and maintainable.

The lacking of the class standard also makes Editors/IDEs hard to get enough information to give users necessary coding assistance like hinting, completion, and inspection. You will feel safe and comfortable when writing TypeScript in modern editors:

![图片](https://user-images.githubusercontent.com/3035071/201610762-164b3728-c4f4-4684-a6e1-275bcc0e1f19.png)

More errors/defects can be detected in fly while editing.

This is so-called "Less is More" in Lua: you finally need to pay extra "more" time to deal with lacking (less)  features in Lua.

## Class in vim9

I think I've made my point by comparing TypeScript and Lua.

Introducing `class` in vim9script earlier will make it easier to maintain complex vim9script projects.
and will be helpful for sophisticate plugins in the future.

**Comment by brammool** [comment]
> The `class` feature is currently listed in todo.txt:
> 
> > Further Vim9 improvements, possibly after launch:
> > - Use Vim9 for more runtime files.
> > - implement :type
> > - implement :enum
> > - implement :class and :interface: See |vim9-classes|
> > - Inline call to map() and filter(), better type checking.
> 
> Can we elevate the priority of the `class` statement a little bit ?
> There are some strong reasons why `class` is essential. 

I've been thinking about it, but this is not something that can be added
quickly, it needs to be thought out properly.  Once done we cannnot
change it, only one chance to get it right.

The main goal is to use a class like people know it, no surprises or
inventing new things.  Java is what many people know, we probably won't
divert too much from that (although some Java syntax is awkward and we
want to avoid that).

Main choices are in things like:
- Method overloading: two methods with same name but differently typed
  arguments?  Probably not.
- Inheritance - most likely just single.
- Abstract class - not sure if it's useful.
- Private/protected/etc. handling needs to be defined.
- Using "this" or something else.
- Object and Class (static) members.
- Object and Class (static) methods.
- Interfaces - probably explicitly declared.
- Generics, for class and methods - yes
- Mixins - not sure.

My ideas are indeed similar to TypeScript.  But it will differ in
details, TypeScript has some mechanisms that are not really needed, only
to make the code a bit shorter with the side effect of making it harder
to understand.  This will need to be discussed.

I'm not really interested in comparing with Lua, I rather look at other
languages that do implement classes and provide alternative ways for it.
I do want good type checking, thus no dynamic changes to an object like
some languages allow for.  Let's keep it simple.


-- 
hundred-and-one symptoms of being an internet addict:
61. Your best friends know your e-mail address, but neither your phone number
    nor the address where you live.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by skywind3000** [comment]
maybe implement it as a syntactic sugar of the code below is enough ?'

```VimL
let MyClass = {"foo": "Foo"}
function MyClass.printFoo() dict
    echo self.foo
endfunction
function MyClass.new() 
    return deepcopy(self)
endfunction

let obj = MyClass.new()
call obj.printFoo()
```

**Comment by brammool** [comment]
> maybe implement it as a syntactic sugar of the code below is enough ?'
> 
> ```VimL
> let MyClass = {"foo": "Foo"}
> function MyClass.printFoo() dict
>     echo self.foo
> endfunction
> function MyClass.new() 
>     return deepcopy(self)
> endfunction
> 
> let obj = MyClass.new()
> call obj.printFoo()
> ```

Definitely not for Vim9 script.  A class should be declared, with all of
its interface with types.  Using a dictionary as a kind of an object is
legacy script.

-- 
hundred-and-one symptoms of being an internet addict:
62. If your doorbell rings, you think that new mail has arrived.  And then
    you're disappointed that it's only someone at the door.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
Much of the class implementation has been done.  It's not finished, still some details are missing and a lot of testing and bug fixing is to be done.
Let's close this issue.  If you have suggestions for how to improve the class implementation, please create an issue specifically for that suggestion.

**Comment by skywind3000** [comment]
thank you for adding this feature.
