### ISSUE TITLE
Incorrect indentation when pasting indented text from insert mode with `autoindent` enabled

### ISSUE THREAD

**Issue by mawkler** [vim/vim#11553]
### Steps to reproduce

1. `> vim -u DEFAULTS -c "set autoindent"`
2. Enter insert mode and paste the following with `<C-r>+` (assuming that you have copied it to your clipboard register)

   ```text
   	foo
   	bar
   	baz
   ```

3. Pasted text looks like this:

   ```text
   	foo
   		bar
   			baz
   ```

If I disable `autoindent`, i.e. run `vim -u DEFAULTS`, the text gets pasted with the correct indentation.

### Expected behaviour

Text gets pasted like this:

```text
	foo
	bar
	baz
```

### Version of Vim

9.0

### Environment

Operating system: Manjaro Linux x86_64
Terminal: Alacritty
Value of `$TERM`: tmux-256color
Shell: zsh

**Comment by vim-ml** [comment]
On 2022-11-15, Melker Österberg wrote:
> Steps to reproduce
> 
>  1. > vim -u DEFAULTS -c "set autoindent"
> 
>  2. Enter insert mode and paste the following with <C-r>+ (assuming that you
>     have copied it to your clipboard register)
> 
>             foo
>             bar
>             baz
> 
>  3. Pasted text looks like this:
> 
>             foo
>                     bar
>                             baz
> 
> If I disable autoindent, i.e. run vim -u DEFAULTS, the text gets pasted with
> the correct indentation.
> 
> Expected behaviour
> 
> Text gets pasted like this:
> 
>         foo
>         bar
>         baz

That is expected behavior.  From ":help i_CTRL-R":

    The text is inserted as if you typed it, but mappings and
    abbreviations are not used.  If you have options like
    'textwidth', 'formatoptions', or 'autoindent' set, this will
    influence what will be inserted.  This is different from what
    happens with the "p" command and pasting with the mouse.

To get the behavior you want, use <C-r><C-o>+.  From ":help
i_CTRL-R_CTRL-O":

    Insert the contents of a register literally and don't
    auto-indent.  Does the same as pasting with the mouse
    |<MiddleMouse>|.

Regards,
Gary

**Comment by melkster** [comment]
I didn't know of this distinction, thank you very much!
