### ISSUE TITLE
With `smoothscroll` and `scrolloff=0` the cursor starts moving into another window

### ISSUE THREAD

**Issue by bfrg** [vim/vim#11554]
### Steps to reproduce

1. Run `vim --clean test.vim -S test.vim`, with

```vim
colorscheme habamax
set smoothscroll
set splitright
set number
set scrolloff=0
vnew
call setline(1, repeat('test ', 1000))
```

2. In the right window start scrolling up by keeping `<C-e>` pressed.
3. Result: after pressing `<C-e>` approx. 20x, the cursor eventually starts moving into the left window.

Screenshot:
![screenshot-2022-11-15_180152](https://user-images.githubusercontent.com/6266600/201981089-5e7e3ddb-4ba3-4084-8773-18a4bb3dcfd7.png)

### Expected behaviour

The cursor should never move into another window when scrolling with `<C-e>`.

### Version of Vim

9.0.883

### Environment

Linux

**Comment by bfrg** [comment]
Maybe will be fixed with https://github.com/vim/vim/pull/11492?

**Comment by ychin** [comment]
I think it should be.

I also have other PRs pending review, so if #11492 doesn't work you can try the other ones too (https://github.com/vim/vim/pulls?q=is%3Apr+is%3Aopen+smoothscroll+author%3Aychin)

**Comment by bfrg** [comment]
Fixed by https://github.com/vim/vim/commit/01ee52bab6041450095c53f9469b1b266a7e3d4d. Thank you!
