### ISSUE TITLE
Vim response (diff mode display,  scrolling up/down and general display) is slow on Virtual Machine Vmware Workstation. 

### ISSUE THREAD

**Issue by niva-xx** [vim/vim#11555]

**Comment by brammool** [comment]
I'm not sure if there is anything actionable here.  Please give more context.

**Comment by niva-xx** [comment]
> I'm not sure if there is anything actionable here.  Please give more context.

ViM
------
Vim-Vi Improved 9.0 Gui version with Ole support
Included patches: 1-886
Huge version with GUI.

Features Included All out of
-balloon_eval_term
-dnd
-ebcdic
-farsi
-footer
-hangul_input
-perl
-postscript
-python
-sun_workshop
-tag_old_static
-tag_any_white
-term_response
-tgetent
-vtp
-xfontset
-xim
-xpm_w32
-xterm_save

Compiled with gcc under Msys2 and used as standalone distro. 

Vmware
-------------
Esxi Vmware 6.7 ~ Workstation 14
Vmware Tools v11301


Step to reproduce
----------------------------


Sizing consideration
--------------------------------
Cpp file of 4400 mines code and open tagbar which show 48 functions. 

Step
-------
Launching Vim GUI on Windows 10 64bits virtualized and 
1. open this large cpp file >>> 1 to 3 seconds spent
2. open tagbar list >>> equal, some seconds
3. The test is simple just typing right and down arrow keys of keyboard in gamer mode ;) many time

Right, Down
     Right, Down
         15 times
         Right, Down


   Looking at the cursor, a big lag response is seen.!! Of 1-3 seconds !!! 



Then Launching Visual Studio 2022, same file, same test, no lag. 

Options
------------
My updatetime option is 300. 
I can extract all if needed. 
I can profile with your instructions what to profile 
I can do -None startup. 

_vimrc
----------
Contains 
set rop=type:directx, gamma: 1.0, contrast:1.5, level:0.0, geom:2, renmode:6, taamode:3
set guifont=Iosevka_SS05_Light:h10:W280:cANSI:qDRAFT

:echo $HOME shows c:\users\administrator
:echo $VIM shows c:\Vim
:echo $VIMRUNTIME shows c:\Vim\vim90
:echo $MYVIMRC shows c:\Vim\_vimrc

Thanks.

**Comment by niva-xx** [comment]
> Clear the 'renderoptions' option and try again.

Since i comment my own rop and set rop= in _vimrc, vim response is better in major part. 

Using Tagbar is less slower
Vertical split of source then moving around is less slower
even cmd eg :e /some/long/path/to/something was slow and is now less slower. 

Thank you Jürgen for this workaround.

My own rop, for instant commenté, was:
set rop=type:direct,
                \gamma:1.0,
                \contrast:1.5,
                \level:0.0,
                \geom:2,
                \renmode:6,
                \taamode:3


DirectxDiag
Under this Os Win, dxdiag shows me 
Directx version 12.0
Main Driver version : 10.0.18362.329 
Date: 6/21/2006
DDI Direct3D: 12
Functionality level: 12_1, 12_0, 11_1, 11_0, 10_1, 10_0,9 etc.. 
Driver model: WDDM 1.3

So, slow issue is it due to directx driver or rop ? 

Thank you for your advise Jürgen.
Nicolas.
