### ISSUE TITLE
scroll up is very slow in vim file when scrolloff=0

### ISSUE THREAD

**Issue by rickhowe** [vim/vim#11559]
### Steps to reproduce

gvim --clean -c "set scrolloff=0" $VIMRUNTIME/autoload/python.vim

And continue to press  'j' key. Scroll down is comfortably fast.
Then, continue to press  'k' key. Scroll up is very slow.

### Expected behaviour

Scroll up is as comfortable as scroll down.

### Version of Vim

Probably 9.0.673 or later (9.0.672 has no problem)

### Environment

Windows 10

**Comment by brammool** [comment]
What if you disable syntax highlighting?
You do have 'smoothscroll' off, right?

Could you build Vim with parts of the 9.0.673 patch reversed, and check which one matters?
E.g. you could change this line:
```
	if (curwin->w_topline > 1 || curwin->w_skipcol > 0)
```
Back to:
```
if (curwin->w_topline > 1 )
```

**Comment by rickhowe** [comment]
If the line 2136 is commented out, it becomes fast.

`	    redraw_later(UPD_NOT_VALID);
`

**Comment by rickhowe** [comment]
I tried to change line 1855 but both are still slow. However, when looking at 672 and 673, line 2307  on 9.0.887 looks like what we should check and tried to change the line. Then, UPD_SOME_VALID is still slow but UPD_REDRAW_TOP becomes fast.

**Comment by brammool** [comment]
> I tried to change line 1855 but both are still slow. However, when
> looking at 672 and 673, line 2307  on 9.0.887 looks like what we
> should check and tried to change the line. Then, UPD_SOME_VALID is
> still slow but UPD_REDRAW_TOP becomes fast. 

Please show the diff of the changes you made.


-- 
Ed's Radiator Shop: The Best Place in Town to Take a Leak.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ychin** [comment]
> That is now line 1855. We can't remove it, when w_skipcol is changed a redraw is needed. But we should not need to redraw everything.

I think we can add a check to make sure smoothscroll is active so we don't unnecessarily redraw:

```diff
diff --git a/src/move.c b/src/move.c
index e255bd68e..c8b7316e6 100644
--- a/src/move.c
+++ b/src/move.c
@@ -2301,7 +2301,7 @@ scroll_cursor_top(int min_scroll, int always)
        check_topfill(curwin, FALSE);
 #endif
        // TODO: if the line doesn't fit may optimize w_skipcol
-       if (curwin->w_topline == curwin->w_cursor.lnum)
+       if (curwin->w_topline == curwin->w_cursor.lnum && curwin->w_skipcol != 0)
        {
            curwin->w_skipcol = 0;
            redraw_later(UPD_NOT_VALID);
```

I checked that the tests still pass with this change.

FWIW I think smoothscroll is currently doing a lot of unnecessary redraws with `redraw_later(UPD_NOT_VALID)` so it's worth looking at proper ways to redraw it at a later time (it's on my bucket list to file after the immediate bugs were fixed), but for now I don't think we need to do these redraws at all unless we have smoothscroll active, to avoid causing regressions for people not using this.

**Comment by rickhowe** [comment]
Here is a diff on 9.0.887.

```
*** moveOrig.c	Fri Oct 21 10:47:38 2022
--- move.c	Thu Nov 17 10:15:55 2022
***************
*** 2304,2310 ****
  	if (curwin->w_topline == curwin->w_cursor.lnum)
  	{
  	    curwin->w_skipcol = 0;
! 	    redraw_later(UPD_NOT_VALID);
  	}
  	if (curwin->w_topline != old_topline
  		|| curwin->w_skipcol != old_skipcol
--- 2304,2310 ----
  	if (curwin->w_topline == curwin->w_cursor.lnum)
  	{
  	    curwin->w_skipcol = 0;
! 	    redraw_later(UPD_REDRAW_TOP);
  	}
  	if (curwin->w_topline != old_topline
  		|| curwin->w_skipcol != old_skipcol

```

**Comment by brammool** [comment]
> > That is now line 1855. We can't remove it, when w_skipcol is changed
> > a redraw is needed. But we should not need to redraw everything.
> 
> I think we can add a check to make sure smoothscroll is active so we
> don't unnecessarily redraw:
> 
> ```diff
> diff --git a/src/move.c b/src/move.c
> index e255bd68e..c8b7316e6 100644
> --- a/src/move.c
> +++ b/src/move.c
> @@ -2301,7 +2301,7 @@ scroll_cursor_top(int min_scroll, int always)
>         check_topfill(curwin, FALSE);
>  #endif
>         // TODO: if the line doesn't fit may optimize w_skipcol
> -       if (curwin->w_topline == curwin->w_cursor.lnum)
> +       if (curwin->w_topline == curwin->w_cursor.lnum && curwin->w_skipcol != 0)
>         {
>             curwin->w_skipcol = 0;
>             redraw_later(UPD_NOT_VALID);
> ```

Perhaps this UPD_NOT_VALID could be something else too.

> I checked that the tests still pass with this change.

Updating the display isn't tested much, it would require making a screendump.

> FWIW I think smoothscroll is currently doing a lot of unnecessary
> redraws with `redraw_later(UPD_NOT_VALID)` so it's worth looking at
> proper ways to redraw it at a later time (it's on my bucket list to
> file after the immediate bugs were fixed), but for now I don't think
> we need to do these redraws at all unless we have smoothscroll active,
> to avoid causing regressions for people not using this.

We need to keep it functional and logic.  In this code there is no check
for the 'smoothscroll' value, thus the conditions should not depend on
it.  When w_skipcol changes a redraw is needed, it doesn't matter why
w_skipcol changes.

-- 
hundred-and-one symptoms of being an internet addict:
89. In addition to your e-mail address being on your business
    cards you even have your own domain.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ychin** [comment]
> Updating the display isn't tested much, it would require making a screendump.

The display update is tested by `Test_smoothscroll_wrap_scrolloff_zero`, which is what was added alongside the redraw change as part of v9.0.0673. It does use screen dumps. That's why I had to add the test.

> We need to keep it functional and logic.  In this code there is no check for the 'smoothscroll' value, thus the conditions should not depend on it.  When w_skipcol changes a redraw is needed, it doesn't matter why w_skipcol changes.

If you look at my diff, I just added a `curwin->w_skipcol != 0` check, which is exactly what you mentioned. The previous logic didn't have this check which is why it's doing unnecessary work when smoothscroll is off. I just said "check for smoothscroll" in a casual sense but the logic did only check for whether `curwin->w_skipcol` needs to be updated.

**Comment by brammool** [comment]
> > Updating the display isn't tested much, it would require making a screendump.
> 
> The display update is tested by
> `Test_smoothscroll_wrap_scrolloff_zero`, which is what was added
> alongside the redraw change as part of v9.0.0673. It does use screen
> dumps. That's why I had to add the test.
> 
> > We need to keep it functional and logic.  In this code there is no
> > check for the 'smoothscroll' value, thus the conditions should not
> > depend on it.  When w_skipcol changes a redraw is needed, it doesn't
> > matter why w_skipcol changes.
> 
> If you look at my diff, I just added a `curwin->w_skipcol != 0` check,
> which is exactly what you mentioned. The previous logic didn't have
> this check which is why it's doing unnecessary work when smoothscroll
> is off. I just said "check for smoothscroll" in a casual sense but the
> logic did only check for whether `curwin->w_skipcol` needs to be
> updated.

You seemed to assume that when w_skipcol is non-zero that 'smoothscroll'
must be set.  That's not always true.  Making assumptions like this is
tricky, it might work now, but when other features are added or changed
later it may be wrong to assume the direct relation.  That is why it's
OK to check the value of w_skipcol, but if you would have checked the
value of the 'smoothscroll' option here it would be wrong.  So you did
the right thing in the code, but the explation didn't match with that.

-- 
hundred-and-one symptoms of being an internet addict:
90. Instead of calling you to dinner, your spouse sends e-mail.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
> Here is a diff on 9.0.887.
> 
> ```
> *** moveOrig.c	Fri Oct 21 10:47:38 2022
> --- move.c	Thu Nov 17 10:15:55 2022
> ***************
> *** 2304,2310 ****
>   	if (curwin->w_topline == curwin->w_cursor.lnum)
>   	{
>   	    curwin->w_skipcol = 0;
> ! 	    redraw_later(UPD_NOT_VALID);
>   	}
>   	if (curwin->w_topline != old_topline
>   		|| curwin->w_skipcol != old_skipcol
> --- 2304,2310 ----
>   	if (curwin->w_topline == curwin->w_cursor.lnum)
>   	{
>   	    curwin->w_skipcol = 0;
> ! 	    redraw_later(UPD_REDRAW_TOP);
>   	}
>   	if (curwin->w_topline != old_topline
>   		|| curwin->w_skipcol != old_skipcol
> 
> ```

Well, I suppose we can't really predict if there is a situation where
UPD_REDRAW_TOP is insufficient.  Let me make a patch to use that in all
places where w_skipcol is changed, then you will have to report any
cases where the display is wrong.  With reproduction steps in script
form, so that it will be easy to turn it into a test, please.

-- 
hundred-and-one symptoms of being an internet addict:
91. It's Saturday afternoon in the middle of May and you
    are on computer.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
> > Here is a diff on 9.0.887.
> > 
> > ```
> > *** moveOrig.c	Fri Oct 21 10:47:38 2022
> > --- move.c	Thu Nov 17 10:15:55 2022
> > ***************
> > *** 2304,2310 ****
> >   	if (curwin->w_topline == curwin->w_cursor.lnum)
> >   	{
> >   	    curwin->w_skipcol = 0;
> > ! 	    redraw_later(UPD_NOT_VALID);
> >   	}
> >   	if (curwin->w_topline != old_topline
> >   		|| curwin->w_skipcol != old_skipcol
> > --- 2304,2310 ----
> >   	if (curwin->w_topline == curwin->w_cursor.lnum)
> >   	{
> >   	    curwin->w_skipcol = 0;
> > ! 	    redraw_later(UPD_REDRAW_TOP);
> >   	}
> >   	if (curwin->w_topline != old_topline
> >   		|| curwin->w_skipcol != old_skipcol
> > 
> > ```
> 
> Well, I suppose we can't really predict if there is a situation where
> UPD_REDRAW_TOP is insufficient.  Let me make a patch to use that in all
> places where w_skipcol is changed, then you will have to report any
> cases where the display is wrong.  With reproduction steps in script
> form, so that it will be easy to turn it into a test, please.

I found one case where UPD_REDRAW_TOP was not enough.  This is when the
top line height increases by a screen line, the following lines are then
not redrawn.  Thus I used UPD_SOME_VALID now.

Perhaps UPD_REDRAW_TOP can be made to work, if we can somehow detect
that the topline has changed the number of screen lines it occupies.  We
do already have some information stored for that, but figuring out what
is valid is going to require quite a bit of digging.

Anyway, please check if display updating works faster after patch
9.0.0892 and doesn't cause problems. 

-- 
From "know your smileys":
 ;-0	Can't find shift key
 ,-9	Kann Umschalttaste nicht finden

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by rickhowe** [comment]
Thank you, I checked and it is now comfortably fast.

**Comment by ychin** [comment]
> You seemed to assume that when w_skipcol is non-zero that 'smoothscroll' must be set. That's not always true. Making assumptions like this is tricky, it might work now, but when other features are added or changed later it may be wrong to assume the direct relation. That is why it's OK to check the value of w_skipcol, but if you would have checked the value of the 'smoothscroll' option here it would be wrong. So you did the right thing in the code, but the explation didn't match with that.
> [](#)

That's true. I wasn't being clear. I think the other place I know where `w_skipcol` is nonzero is when we have a super long line that spans more than a window height and we use it to show the current cursor.
