### ISSUE TITLE
Add syntax highlighting for Python's new numeric literals with underscores

### ISSUE THREAD

**Issue by salty-horse** [vim/vim#11551]
Python 3.6 added support for underscores in [numeric literals](https://docs.python.org/3/reference/lexical_analysis.html#integer-literals), usually used as thousands/other separators, e.g. `1_000_000_000_000_000`, `0x_FF_FF_FF_FF`.

The syntax file should be updated to identify these as numbers.

**Comment by k-takata** [comment]
Could you contact the maintainer of the python syntax file?
You can find the maintainer at the top of the file.

https://github.com/vim/vim/blob/698a00f55d60043d51b1c98cbbf3f9fd10badd2f/runtime/syntax/python.vim#L3

**Comment by salty-horse** [comment]
Apologies, this is a duplicate of https://github.com/vim/vim/issues/7923
The issue is closed, but the PR is still pending.
