### ISSUE TITLE
Can someone please explain this weird map() behaviour?

### ISSUE THREAD

**Issue by igbanam** [vim/vim#11569]
Why does `vim9script` treat a list of lists like a dictionary?

```vim
vim9script

var list_o_lists = [['this', 'that'], ['some', 'thing']]

echom list_o_lists->mapnew((_, v) => v[0])
# works 👍🏾 

echom list_o_lists->mapnew((d) => d[0])
# E1106: One argument too many

echom list_o_lists->mapnew(() => v:val[0])
# E1001: Variable not found: val
# E116: Invalid arguments for function mapnew(() => v:val[0])

echom list_o_lists->mapnew( => v:val[0])
# E15: Invalid expression: "=> v:val[0])"
# E116: Invalid arguments for function mapnew( => v:val[0])
```

**Comment by igbanam** [comment]
Matter of fact, it gets even weirder. It seems to treat lists like dictionaries. At this point, I think this could be a bug.

**Comment by igbanam** [comment]
To reproduce…

```vim
vim9script

var fizz = [1, 2, 3, 4, 5]

echom fizz->mapnew((d) => d * 2)
```

- put ☝🏾 in some `weird_behaviour.vim` file
- run Vim with that file only — `vim --clean  +'so path/to/weird_behaviour.vim'

### Expected 

Vim starts with `[2, 4, 6, 8, 10]` printed at the bottom; the "command line"

### Actual

```
Error detected while processing command line..script /Users/igbanam/projects/igbanam/dot
files/mapper.ffs.vim:
line    5:
E1106: One argument too many
```

## System Details

OS X Ventura

### Vim Version

```
:version
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Nov 09 2022 23:55:52)
macOS version - arm64
Included patches: 1-850
```

**Comment by brammool** [comment]
> Why does `vim9script` treat a list of lists like a dictionary?

It doesn't.  No idea why you would think that.

> ```vim
> vim9script
> 
> var list_o_lists = [['this', 'that'], ['some', 'thing']]
> 
> echom list_o_lists->mapnew((_, v) => v[0])
> # works 𐟑𐟏¾ 
> 
> echom list_o_lists->mapnew((d) => d[0])
> # E1106: One argument too many

Correct, the lambda is called with two arguments and it only accepts
one.

> echom list_o_lists->mapnew(() => v:val[0])
> # E1001: Variable not found: val
> # E116: Invalid arguments for function mapnew(() => v:val[0])

You are mixing legacy and Vim9 syntax here.

> echom list_o_lists->mapnew( => v:val[0])
> # E15: Invalid expression: "=> v:val[0])"
> # E116: Invalid arguments for function mapnew( => v:val[0])
> ```

This is wrong in any context.

This looks like an invalid issue.

-- 
% cat /usr/include/long_life.h
long life(double fun);

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bfrg** [comment]
@brammool I think the documentation for `map()` [and `filter()`] could be improved. In legacy vimscript the following is allowed:

```vim
echo ['a', 'b', 'c']->map({i -> i})
```
The parameter `i` in the lambda will contain the current index in the list. So the result is: `[0, 1, 2]`. And similarly for `filter()`.

But in vim9script, the function passed to `map()` always must accept two arguments. This isn't documented anywhere.  The current error is also a little bit misleading:

```vim
echo ['a', 'b', 'c']->map((i) => i)
```

Result:
```
# E1106: One argument too many
```

**Comment by brammool** [comment]
> @brammool I think the documentation for `map()` [and `filter()`] could
> be improved. In legacy vimscript the following is allowed:
> 
> ```vim
> echo ['a', 'b', 'c']->map({i -> i})
> ```
> The parameter `i` in the lambda will contain the current index in the
> list. So the result is: `[0, 1, 2]`. And similarly for `filter()`.
> 
> But in vim9script, the function passed to `map()` always must accept
> two arguments. This isn't documented anywhere.

	:help vim9-lambda-arguments

I can add a hint at the help for map(), but it really applies in many
more places.

> The current error is also a little bit misleading:
> 
> ```vim
> echo ['a', 'b', 'c']->map((i) => i)
> ```
> 
> Result:
> ```
> # E1106: One argument too many
> ```

It is not misleading, but I can see that users would not easily
recognize the reason of the error.  What would work better?

	"E1106: Passing 2 arguments to function that takes only 1 argument"

But when there are optional arguments this isn't right, can't be
specific about the number of arguments accepted.

	"E1106: Passing one argument more than function accepts"

Doesn't really say something more informative.

Keep in mind that the error comes from call_def_function(), which is
used for any compiled function.  Doing something different for map()
would be too specific.


-- 
There's no place like $(HOME)!

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by igbanam** [comment]
I didn't even know that what's passed in the legacy vimscript lambda is the index, not the element itself. I read through the help entry for `vim9-lambda-arguments` — upgraded to the version below — and I see that…

```
[…] In Vim9 script the number of arguments must match.  […]
```

…same thing as in patch `1-850`. This is what led me to think something like 

```vimscript
echo ['a', 'b', 'c']->map((i) => i)
```

…should work, cos I'm thinking `i` should be `a`, `b`, or `c`.

#### Current Vim Version
```
:version
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Nov 18 2022 12:52:50)
macOS version - arm64
Included patches: 1-900
```

**Comment by errael** [comment]
Under `:help map()` there is

```
map({expr1}, {expr2})					*map()*
...
    If {expr2} is a |Funcref| it is called with two arguments:
            1. The key or the index of the current item.
            2. the value of the current item.
    The function must return the new value of the item. Example
...

    Can also be used as a |method|: >
            mylist->map(expr2)
```
