### ISSUE TITLE
"Unknown function: MyQuickfixTextFunc" when running `:CFilter`

### ISSUE THREAD

**Issue by Melandel** [vim/vim#11568]
### Steps to reproduce

1. Create a file, for example:
  ```
foo
foobar
baz
  ```
3.
  ```vim
  :def MyQuickFixTextFunc(info: dict<number>): list<string>
  :  return ['']
  :enddef
  ```
4. `:defcompile MyQuickFixTextFunc`
5. `:set quickfixtextfunc=MyQuickFixTextFunc`
6. `:vim /foo/ %`
7. `:packadd cfilter`
8. `:Cfilter bar`
9. Observe `E117: Unknown function: MyQuickFixTextFunc`

### Expected behaviour

No error, and `MyQuickFixTextFunc` is found when using `Cfilter`

### Version of Vim

9.0 with patch 1-887

### Environment

gvim on Windows 10

**Comment by brammool** [comment]
This is not a Vim issue.  For help on how to do something please use another place, e.g. https://vi.stackexchange.com/

**Comment by Melandel** [comment]
I don't mean to argue the truth in your sentence, but it is my understanding that the steps to reproduce have been working in `vim8` for the past years, and this issue happened when I upgraded to `vim9` - in my understanding, I just used `vim9`'s `def` instead of `vim8`'s `function` and expected it to work.

Can you please help me understand where or why my expectations went wrong?

I'll also post a question on https://vi.stackexchange.com/ to know how to achieve the behavior I want using `vim9`

**Comment by Melandel** [comment]
For anyone looking at this thread, [here](https://vi.stackexchange.com/a/39261/44420)'s the answer.
