### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [vim/vim#11570]

**Comment by d85a6g** [comment]
Installing a dozen of dependencies is a nightmare to us!

**Comment by k-takata** [comment]
Nightly builds are already available.
For Linux: https://github.com/vim/vim-appimage
For Windows: https://github.com/vim/vim-win32-installer

**Comment by d85a6g** [comment]
[AppImage build doesn't work well](https://docs.appimage.org/user-guide/troubleshooting/fuse.html) on some Linux systems, which have not been enabled FUSE by default.

Can we have a static build compressed as `.tar.gz` file? (We don't need GUI support in this case!)
