### ISSUE TITLE
Clarify `WinClosed` event

### ISSUE THREAD

**Issue by echasnovski** [vim/vim#11574]
At the moment, documentation of `WinClosed` event describes it as "After closing a window.".
This might be a bit confusing because it is activated when window to be closed is still present. Example:

1. `au WinClosed * let g:winlayout = winlayout()`
2. Close some window. For example, with `<C-w>v<C-w>c`.
3. `echo g:winlayout` shows layout *with* closed window present.

There are at least these possibilities here:
- Clarify event description. Maybe it should be "Before closing a window"?
- Something is wrong with implementation. At least [this comment](https://github.com/vim/vim/pull/9110#issuecomment-964812384) might suggest that it indeed should be activated **after** closing window.

**Comment by brammool** [comment]
I see no reason to change the implementation.  It would most likely cause trouble in some cases.

I'll adjust the help to say WinClosed is triggered just before a window is removed from the window layout.
That matches what is in the code and the comment make clear this is done intentionally.
