### ISSUE TITLE
help bug and request: setcellwidths() example not working properly and improvement request.

### ISSUE THREAD

**Issue by tsuyoshicho** [vim/vim#11581]
Currently the setcellwidths() example in help does not work properly.
0xad is less than 0x100, so get an E1114 error.

I hope you will take appropriate action on this matter.

**Describe the solution you'd like**

* Fix example
* Refine range

**Describe alternatives you've considered**

Above this.

**Additional context**

Nothing.

**Comment by brammool** [comment]
The help for setcellwidths() is indeed not very clear.  I'll fix that and update the example.
