### ISSUE TITLE
Hardcopy prints incorrect non-English characters if cp1250 code page is used

### ISSUE THREAD

**Issue by igor2x** [vim/vim#1159]
Hi,
from gVim Nightly web page: https://github.com/vim/vim-win32-installer/releases I have downloaded gvim_8.0.0027_x64.zip 
and unzipped gVim 8.0.0027 on Windows 7 SP1 with all of the Windows updates installed.
1. I opened Windows Command Prompt.
2. Changed directory:
   cd <zip_extract_location>vim\vim80\
3. Started Vim without vim config files:
   gvim -u NONE -N
4. Checked encoding:
   set encoding?
   Results: encoding=cp1250
   Most probably this variable is effected by my Windows Regional Settings set to Slovenia. In Slovenia we use Windows-1250 code page which is displayed in Vim as cp1250.
   
   Note: if you get different setting for "encoding", you can manually change setting to "cp1250" with:
   :set encoding=cp1250
5. Checked file encoding:
   set fileencoding?
   Result: fileencoding=
   So empty. From Vim help:
   help fileencoding
   "When 'fileencoding' is empty, the same value as 'encoding' will be used"
6. Type in Slovenian characters:
   šđčćžŠĐČĆŽ
7. Print to printer:
   :hardcopy
8. Windows print dialog opens and selecting printer and Print button.
   Result on printer is:
   šðèæžŠÐÈÆŽ
   
   Note: For testing I also use "virtual printer" CutePDF Writer from: http://www.cutepdf.com/download/CuteWriter.exe This program adds virtual printer. So after :hardcopy and Windows Print window is opened the "CutePDF Writer" printer appears. When selecting this "printer" save dialog opens and just type in some name like test.pdf and save PDF file to disk. The result of "CubePDF Writer" is exactly the same as using real printer. I just let you know about this program, so you don't waste too much paper.
9. From the result fro step 8 it is clear that some of the characters are correctly printed and some are not. I think I know the answer why.
   See Windows-1250 code page web page: https://en.wikipedia.org/wiki/Windows-1250
   Search for "200" number and you will get letter Č (this is one of the characters I would like to pring in step 6).
   Now open Windows-1252 code page (this is default English code page): https://en.wikipedia.org/wiki/Windows-1252
   Search for "200" number and you will get letter È (this is exactly the character that is printed).

Conclusion. When printing from Windows-1250 encoded characters instead of this characters Windows-1252 code page is used for printing.

This problem is not new to Vim 8.0, but it was already in Vim 7.4 in my previous install downloaded from www.vim.org, command: :version reporting "7.4 compiled Aug 10 2013 14:38:33)"

ADDITIONAL TEST:
:enew
:set encoding=utf-8
:set fileencoding=cp1250

Copy characters from step 6
:hardcopy

And characters are CORRECTLY printed! So in step 8 I get correct characters printer exactly as in step 6.

I know I can use above work-around, but I always use only cp1250 code page, so having encoding=utf-8 and fileencoding=cp1250 I non-stop get the annoying "converting" info in Vim.

Regards

**Comment by chrisbra** [comment]
Well, then simply use encoding=utf8 I wouldn't recommend to use any other encoding nowadays.

**Comment by igor2x** [comment]
Hi,
setting "encoding=utf-8" is very good setting if user is using multiple fileencoding (or would like to save file into utf-8 code page itself). In order to Vim work properly internally the "encoding" setting utf-8 is used. If this would not be set then conversions to different non-compatible national code pages is not possible.

But in my case conversions are not needed, I always use cp1250 code page and NEVER change code page. So having encoding=utf-8 and fileencoding=cp1250 it means Vim is going to do conversions non-stop, every time I save buffer to file or similar. This is waste of computer cycles... But like in my case setting encoding=cp1250 and so "fileencoding=" (both have the same setting), there is absolutely no need for converting.

In my case everything is working excellent except hard printing. But as I have documented above, Vim is most probably using something like:
if "encoding=utf-8" then "hardprint use fileencoding" end_if.
if "encoding!=utf-8" then "hardprint ALWAYS use cp1252" end_if.

It may be trivial bug to fix.

Regards,
Igor

**Comment by k-takata** [comment]
Does it work before Vim 7.3.1211?
Since 7.3.1211, Vim supports `:hardcopy` with setting `enc=utf-8` on Windows.
So if `:hardcopy` works properly before that, the patch would have problems.
If not, I have no idea about the cause of this.

BTW, I personally think that Vim should support only `enc=utf-8` in the near future.
It will make the source code simple. However there are several problems when setting `enc=utf-8`
on Windows (e.g. `:make`). They must be fixed if we are going to support only `enc=utf-8`.

**Comment by vim-ml** [comment]
Am 2016-10-13 08:59, schrieb K.Takata:

> BTW, I personally think that Vim should support only enc=utf-8 in the
> near future.

+1 for that goal

Best,
Christian

**Comment by igor2x** [comment]
k-takata, where can I download pre-7.3.1211 version for Window? I am willing to test this.

**Comment by k-takata** [comment]
You can download older versions from here: http://ftp.vim.org/pub/vim/pc/
Maybe you can try gvim73.exe or gvim73_46.exe.

**Comment by igor2x** [comment]
Hi,

TEST 1
1. gvim -u NONE -N
2. :set enc=utf-8
3. set fenc=cp1250
4. i
5. šđčćžŠĐČĆŽ
6. :hardcopy
7. Result completely corrupted: A!Ä‘ Ä Ä‡A3A  Ä ÄOÄ†A1
Note: In 8.0.0027 this works fine.

TEST 2
1. gvim -u NONE -N
2. :set enc=cp1250
3. set fenc=cp1250
4. i
5. šđčćžŠĐČĆŽ
6. :hardcopy
7. Result is wrong, but it is exactly the same as in 8.0.0027:  šðèæžŠÐÈÆŽ

I have tested both version 7.3 and version 7.3.46 and both have exactly the same result.
Regards

**Comment by k-takata** [comment]
Hmm, strange.
About TEST 2 Vim 7.3.46 doesn't do any encoding conversion and it outputs the string as-is.
What about your font settings? What does this show?: `:set gfn? pfn?`
How about setting the character set with `cXX` option? E.g.: `:set pfn=FooBar:h11:cANSI`
You may want to try `cANSI`, `cDEFAULT`, `cOEM`, `cEASTEUROPE`, <del>cRUSSIAN</del> and etc.

**Comment by igor2x** [comment]
**TEST PERFORMED**
I did bellow test with: gvim -u NONE -N
on Vim 7.3.46 on Windows 7.

Default settings:
guifont=
printfont=Courier_New:h10

I did:
:set encoding=cp1250
:set fileencoding=cp1250
:set pfn=FooBar:h11:cANSI
:hardcopy
and selected a printer and error is produced in Vim:
E613: Unknown printer font: FooBar:h11:cANSI

I also tried all other options with Vim 7.3.46 and getting the same error when hardcopy is executed.

I have performed the same tests on Vim 8.0.27 and the same error.

**ADDITIONAL INFO**
In my very humble opinion I am not really convinced this is font problem. You know in Vim 8.0.27 I have the same print and gui font setting for "enc=utf-8 fenc=cp1250" and "enc=cp1250 fenc=cp1250" and first setting hardcopy correctly and second one does not. Just to get one step back if I may. If I type the following characters: šđčćžŠĐČĆŽ save the file and open the file with any editor like Notepad on Windows characters are going to be displayed correctly, because my Windows Regional Settings are set to Slovenia, so Windows uses Windows-1250 code page (cp1250 in Vim) to recognize characters. Now change Windows Regional Settings to e.g. "English UK" (so Windows-1252 is used) and restart Windows and reopen the same! file and you gonna get the following: šðèæžŠÐÈÆŽ
Which is exactly what Vim prints! So having byte to byte exactly the same data are interpreted differently according to code-page used. So for the same bytes used different font characters are used.

Regards

**Comment by k-takata** [comment]
Please replace `FooBar` with the actual fontname.

**Comment by k-takata** [comment]
> You know in Vim 8.0.27 I have the same print and gui font setting for "enc=utf-8 fenc=cp1250" and "enc=cp1250 fenc=cp1250" and first setting hardcopy correctly and second one does not.

This is because Vim 8.0.27 does convert cp1250 to utf-8 then utf-16 and use Unicode APIs to output to a printer with the first setting. This is not affected by your regional settings.
However, with the second setting Vim doesn't convert the encoding and uses ANSI APIs, and they are affected by regional settings, font and its encoding. So the setting of `cXX` is important.

BTW, what does happen when you set gfn as the same as pfn?: `:set gfn=Courier_New:h10`
Or set pfn as the same as gfn?: `:set pfn=`

**Comment by igor2x** [comment]
**STARTING UP GVIM**
gvim -u NONE -N

**THE SAME SETTINGS FOR ALL TESTS**

```
:set encoding=cp1250
:set fileencoding=cp1250
:set guifont=
```

**TEST 1**

```
:set printfont=Courier_New:h10
:hardcopy
```

INCORRECTLY PRINTS: šðèæžŠÐÈÆŽ

**TEST 2**

```
:set printfont=Courier_New:h10:cANSI
:hardcopy
```

INCORRECTLY PRINTS: šðèæžŠÐÈÆŽ

**TEST 3**

```
:set printfont=Courier_New:h10:cDEFAULT
:hardcopy
```

CORRECTLY PRINTS: šđčćžŠĐČĆŽ

**TEST 4**

```
:set printfont=Courier_New:h10:cEASTEUROPE
:hardcopy
```

CORRECTLY PRINTS: šđčćžŠĐČĆŽ

**TEST 5**

```
set printfont=Courier_New:h10:cOEM
:hardcopy
```

INCORRECTLY PRINTS: Ü-ŔŠ×Őđ╚ĂÄ

**TEST 6**

```
set printfont=Courier_New:h10:cRUSSIAN
:hardcopy
```

INCORRECTLY PRINTS: љрижћЉРИЖЋ

Conclusion: Test 3 and test 4 are working correctly. It looks like if no cXX is specified then it is used cANSI. What does really cDEFAULT do? Does it take Windows Regional Settings? If yes, then this should in my humble opinion most probably be default value.

I have now set:
:set printfont=Courier_New:h10:cDEFAULT
in my $MYGVIMRC file and now Vim prints excellent.

Thanks a lot for your help. It may still be a good solution to think if cDEFAULT should be default value...

**Comment by k-takata** [comment]
> now Vim prints excellent.

Glad to hear that.
BTW, I'm not sure that setting cDEFAULT as the default always works on other languages...

**Comment by vim-ml** [comment]
Am 2016-10-18 16:14, schrieb K.Takata:

> > now Vim prints excellent.
> 
> Glad to hear that.
> BTW, I'm not sure that setting cDEFAULT as the default always works on
> other languages...

I assume, this can be closed?

**Comment by k-takata** [comment]
I think it's okay.

**Comment by igor2x** [comment]
@k-takata, thanks a lot for help.
@vim-ml, yes, bug report can be closed.

**Comment by Freed-Wu** [comment]
Can i ask a question?
```{.sh}
vi -u NONE
```

```{.vim}
set nocp
e $VIMRUNTIME/doc/digraph.txt
set printexpr=system(join(['ps2pdf']\ +\ [v:fname_in])).\ delete(v:fname_in)+\ v:shell_error
set printencoding=utf-8
set encoding=utf-8
ha
```

![Screenshot from 2020-09-28 14-46-14](https://user-images.githubusercontent.com/32936898/94399193-818c1f00-0199-11eb-9035-9d209f8c113e.png)

all digraph characters are printed to '¿', a upside down question mark.

i have read `help print.txt`
```{.txt}
When 'encoding' is set to a multi-byte encoding, Vim will try to convert
characters to the printing encoding for printing (if 'printencoding' is empty
then the conversion will be to latin1).  Conversion to a printing encoding
other than latin1 will require Vim to be compiled with the |+iconv| feature.
If no conversion is possible then printing will fail.  Any characters that
cannot be converted will be replaced with upside down question marks.
```
so i believe
```{.vim}
set printencoding=utf-8
set encoding=utf-8
```
is right.

and i
```{.vim}
ec has('iconv')
```
also return 1.

so what should i do to make all digraph characters displayed normally?
thanks!
