### ISSUE TITLE
Mark not set

### ISSUE THREAD

**Issue by wonderful27x** [vim/vim#11603]
### Steps to reproduce

1. mount a disk
2. open a cpp file in the disk with vim
3. mark C
4. open a new terminal and open vim, then type \``C`
5. error shows in command line: `E20: Mark not set`

### Expected behaviour

jump to the right position

### Version of Vim

Included patches: 1-916

### Environment

Ubuntu 20.04LTS

**Comment by brammool** [comment]
I assume you are expecting the mark set in one Vim instance to show up in another.
For that to work it has to go through the viminfo file.  You'll have to make sure it
is written before the other Vim instance is started.
This doesn't sound like a bug but a user error.

**Comment by wonderful27x** [comment]
> I assume you are expecting the mark set in one Vim instance to show up in another. For that to work it has to go through the viminfo file. You'll have to make sure it is written before the other Vim instance is started. This doesn't sound like a bug but a user error.

You are right, I will close this "un-bug"
