### ISSUE TITLE
Mappings with CTRL modifier doesn't work when 'esckeys' option is off on terminals with modifyOtherKeys support

### ISSUE THREAD

**Issue by mityu** [vim/vim#11615]
### Steps to reproduce

1. Prepair a terminal with modifyOtherKeys support.
1. Open Vim with: `vim -u NONE -c "set cpoptions-=< esckeys | inoremap <C-j> @"`
1. Type some key with CTRL modifier and tell Vim that modifyOtherKeys is supported. Check Vim got modifyOtherKeys sequence with `:verbose map`.
1. Type `<C-j>` in insert mode. `@` will be inserted.
1. Make `'esckeys'` option off: `:set noesckeys`
1. Type `<C-j>` in insert mode again. In this time, a new line will be inserted.

### Expected behaviour

`@` is inserted at step 6.

### Version of Vim

9.0.946

### Environment

- OS: macOS Monterey
- Terminals:
  * WezTerm
     -  20221119-145034-49b9839f
     - $TERM: xterm-256color
  * iTerm2
     -  Build 3.4.18
     -  modifyOtherKeys is enabled in preferences
     - $TERM: xterm-256color

**Comment by mityu** [comment]
Note that it seems this bug doesn't happen on terminals without modifyOtherKeys support.
In my environment, this bug didn't happen on these terminals:

- iTerm2 with modifyOtherKeys disabled
- Terminal.app
  * 2.12.7
  * $TERM: xterm-256color
- Alacritty
   * 0.12.0
   * $TERM: xterm-256color

**Comment by brammool** [comment]
This behavior is documented:
```
NOTE: when this option is off then the |modifyOtherKeys| functionality
	is disabled while in Insert mode to avoid ending Insert mode with any
	key that has a modifier.
```

Generally, you should never use 'noesckeys', it breaks things.

**Comment by mityu** [comment]
I know that, but I think it's a bit unkind that available key mappings without modifyOtherKeys are also disabled in insert mode.
Document says Vim disables modifyOtherKeys in insert mode.  Then, is it possible to switch key handling method to non-modifyOtherKeys one while in insert mode?  If can, simple key mappings with CTRL modifier will be able to use even in insert mode.
I don't know how keys or key-mappings are handled internally and what Vim does to get along with modifyOtherKeys.  Sorry if I say absurd things.  Thanks.
