### ISSUE TITLE
matchparen: match highlight remains when switching buffer

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#11626]
### Steps to reproduce

1. Run `vim` without config (`--clean` doesn't work here)
2. Run `:set hidden`
3. Type `i()<Esc>0`
4. Run `:enew`
5. Type `iaa<Esc>0`
6. Type `<C-^>lh<C-^>`
7. The `aa` is highlighted by matchparen

### Expected behaviour

The `aa` is not highlighted by matchparen

### Version of Vim

9.0.910

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

**Comment by zeertzjq** [comment]
Maybe this is enough to fix this issue:
```vim
diff --git a/runtime/plugin/matchparen.vim b/runtime/plugin/matchparen.vim
index ce2225c5f..e075f3890 100644
--- a/runtime/plugin/matchparen.vim
+++ b/runtime/plugin/matchparen.vim
@@ -20,7 +20,7 @@ endif
 augroup matchparen
   " Replace all matchparen autocommands
   autocmd! CursorMoved,CursorMovedI,WinEnter,WinScrolled * call s:Highlight_Matching_Pair()
-  autocmd! WinLeave * call s:Remove_Matches()
+  autocmd! WinLeave,BufLeave * call s:Remove_Matches()
   if exists('##TextChanged')
     autocmd! TextChanged,TextChangedI * call s:Highlight_Matching_Pair()
   endif
```

**Comment by brammool** [comment]
What do you mean with "Run vim without config"?
When using "vim -u NONE" then there is no matchparen highlight at all.

**Comment by zeertzjq** [comment]
It may just mean "run a fresh install of Vim".

**Comment by brammool** [comment]
> It may just mean "run a fresh install of Vim".

I don't have that :-).

Repro steps should work with any installed Vim, so long as it was build
with the required features.  I would expect "vim --clean" to normally be
sufficient.  If more is needed, perhaps "vim -u NONE".  I'm not going to
try all kinds of stuff when someone reports an issue, it should be part
of the repro steps.

-- 
An error has occurred.  Hit any user to continue.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by zeertzjq** [comment]
Oh, running `:source $VIMRUNTIME/plugin/matchparen.vim` after `vim --clean` also works.
