### ISSUE TITLE
highlight seems not right redraw/refresh somewhere when set termguicolors in gnu-screen

### ISSUE THREAD

**Issue by Shane-XB-Qian** [vim/vim#11620]
### Steps to reproduce

1, set t_8f and t_8b
2, set termguicolors

![image](https://user-images.githubusercontent.com/13550529/204067504-f09b7401-18f0-4da5-996a-0370e8af4962.png)

not sure if it was a gnu-screen bug or somewhere vim specific code for gnu-screen should be improved..

### Expected behaviour

no stray highlight

### Version of Vim

v9.0.950

### Environment

linux
xfce-term with gnu-screen (v4.09.00)

**Comment by brammool** [comment]
Set t_8f and t_8b to what?

What is the value of 'term'?
How do you run screen?

Sorry, you really need to give reproduction steps literally, we can't guess what is going on here.

**Comment by Shane-XB-Qian** [comment]
@brammool 
just run `xfce4-terminal` then `screen`
// `screen.xterm-256color`
`vim --clean <(echo -e '# TODO\n# FIXME\n# XXX') -c 'let &t_8f="\eP".&t_8f."\e\\" | let &t_8b="\eP".&t_8b."\e\\" | set termguicolors'`

**Comment by brammool** [comment]
What I get doesn't look like your screen shot at all:
- Only three lines with text.
- All background is yellow
- No line numbers

**Comment by Shane-XB-Qian** [comment]
ohh, it should be same case, the screen cut in first description is when/with my vimrc which had set nu and cursorline etc, the latter you saw I've simplified it and only remained those 3 lines content in that foo.{sh,txt}
the stray highlight actually is not fixed (would not full screen always), you can edit/add some lines then make cursor line (set it) up/down move some, you will see the highlight became randomly stray like first screen cut.

--
shane.xb.qian

**Comment by Shane-XB-Qian** [comment]
let it be.. and i've forgot the issue. closing...
