### ISSUE TITLE
command ` vi icicha.key cat icicha.key icicha.crt > icicha.pem` makes vim hang

### ISSUE THREAD

**Issue by haojue** [vim/vim#11621]
### Steps to reproduce

```
[root@m5404010 ~]# vi icicha.key cat icicha.key icicha.crt > icicha.pem
Vim: Warning: Output is not to a terminal
^CError detected while processing /etc/vimrc:
line    1:
Interrupted
Error detected while processing /usr/share/vim/vim80/defaults.vim:
line    1:
Interrupted
Interrupt: Press ENTER or type command to continue
```

### Expected behaviour

The command does not make vim hang

### Version of Vim

8.0.1763

### Environment

rhel 8.6
[root@m5404010 ~]# uname -a
Linux m5404010 4.18.0-305.el8.s390x #1 SMP Thu Apr 29 09:06:01 EDT 2021 s390x s390x s390x GNU/Linux

Mac iterm

**Comment by Shane-XB-Qian** [comment]
do you see `Vim: Warning: Output is not to a terminal` ?

**Comment by brammool** [comment]
Vim doesn't hang, the output goes to the file you specified.   Working as expected (probably not intended).
