### ISSUE TITLE
`WinScrolled` is triggered when opening a new vertical split or when closing the same split, `<amatch>` depends on `splitright`

### ISSUE THREAD

**Issue by bfrg** [vim/vim#11634]
### Steps to reproduce

1. Run `vim --clean -S test.vim`, with

```vim
augroup test
    autocmd!
    autocmd WinScrolled * call popup_notification($'WinScrolled: <amatch> = {expand('<amatch>')}', {})
augroup END
```

2. Open a vertical split with `<C-w>v`.
3. Result: `WinScrolled` is triggered, with `<amatch>` expanded to 1001 (see popup window).
4. Close the new split with `<C-w>q`.
5. Result: `WinScrolled` is triggered again, this time with `<amatch>` expanded to 1000.

The value of `<amatch>` depends on `splitright`. When `splitright` is enabled, `<amatch>` is expanded the window ID of the window where the split was initiated. In the above example this would be 1000.

### Expected behaviour

I wouldn't have expected `WinScrolled` to be triggered when opening a new vertical split or when closing a vertical split.

### Version of Vim

9.0.962

### Environment

Linux

**Comment by zeertzjq** [comment]
Isn't this what `WinScrolled` is should do? The viewport of the windows have changed.

**Comment by bfrg** [comment]
Not sure why `WinScrolled` should be triggered since nothing was scrolled.

**Comment by brammool** [comment]
> Not sure why `WinScrolled` should be triggered since nothing was
> scrolled.

Read the help:

WinScrolled			After any window in the current tab page
				scrolled the text (horizontally or vertically)
				or changed width or height.  See
				|win-scrolled-resized|.


-- 
hundred-and-one symptoms of being an internet addict:
174. You know what a listserv is.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bfrg** [comment]
IMO this shouldn't be triggered since there's `WinResized` for that.

**Comment by brammool** [comment]
> IMO this shouldn't be triggered since there's `WinResized` for that.

This was discussed before.  WinResized is only triggered on a window
size change, WinScrolled on scroll and size changes.

This is a functional mechanism, don't read too much into what the events
are called.  There is no point in using WinScrolledOrResized now.

-- 
If Microsoft would build a car...
... the oil, water temperature, and alternator warning lights would
all be replaced by a single "General Protection Fault" warning light.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
