### ISSUE TITLE
make line commands use visual lines in softwrap (enhancement)

### ISSUE THREAD

**Issue by yashamon** [vim/vim#1164]
For softwrap. Would it be possible to give an option for line commands to use visual lines (that is lines as they appear on screen, rather than wrapped lines). By line commands I mean any commands having to do with lines like D, dd, go to beginning/end of line, etc. This would make life way better for editing.
 n fact we already have this with J,K but these are the only commands of this type.
Btw, I cannot imagine any reason why this is not default.

**Comment by chrisbra** [comment]
That would be a backward incompatible change. If you really want that, I suggest to use visual mode together with g^, g0 and g$ motions. That would be a nice little vim plugin, perhaps it already exists. I am closing this.

**Comment by yashamon** [comment]
a) How is this an incompatible change if it is an option that could be toggled? I am not saying it should be default, though like I said cannot imagine why it isn't. 
What about D, V command, etc? these behave terribly with wrapped text.

**Comment by vim-ml** [comment]
On Thu, Oct 13, 2016 at 4:00 PM, yashamon vim-dev-github@256bit.org wrote:

> What about D, V command, etc? these behave terribly with wrapped text.
> 
> For the D command, just do dg$.  If you don't like typing three characters,
> make up a mapping.

-Manny

**Comment by yashamon** [comment]
And the V command? And the A command? Why propose a solution which works half the time, is annoying to implement for the end user, when the current default behavior makes no sense what so ever?

**Comment by yashamon** [comment]
To be clear I am not asking for default behavior to be changed, I am just flabbergasted by it. But I would like an option that could be toggled to make it sane.
