### ISSUE TITLE
Error for comment after an indented let=<< 

### ISSUE THREAD

**Issue by Aster89** [vim/vim#11642]
### Steps to reproduce

1. Open a vimscript file and fill it with the following content:
```viml
fun SomeFun()
  let text =<< trim END
  Some text
  END
endf
" a comment
```
2. Observe the syntax coloring of `"`
3. Hit <kbd>Escape</kbd><kbd>G</kbd><kbd>A</kbd><kbd>Enter</kbd><kbd>Enter</kbd>.
4. See the error.

Here's a screencast:

[![asciicast](https://asciinema.org/a/t9eVPrfsP6CAAJwo4AiaLUKkL.svg)](https://asciinema.org/a/t9eVPrfsP6CAAJwo4AiaLUKkL)

---

Note there's nothing after the closing `END` and there's as much space before as before `let`. This is consistent with [`let {var-name} =<< [trim] [eval] {endmarker}`'s documentation](https://vimhelp.org/eval.txt.html#%3Alet%3D%3C%3C), specifically

> The last line should end only with the `{endmarker}` string without any other character.

and
> The marker must line up with "`let`".

### Expected behaviour

Correct syntax coloring and no error.

### Version of Vim

9.0 patch 1-910

### Environment

Operating system: up-to-date Archlinux
Terminal: URxvt
Value of $TERM: rxvt-unicode-256color
Shell: Bash

**Comment by Aster89** [comment]
Well, the issue happens on the last line of the file whatever that is, actually:
![err](https://user-images.githubusercontent.com/20521900/204860188-bf859e0b-32be-4bdf-a8e5-d89e9332e40b.png)

**Comment by chrisbra** [comment]
I cannot reproduce this with gvim 9.0.975 and an older 9.0.895. 

Can you verify this behaviour using `vim --clean`?

**Comment by brammool** [comment]
Since we get too many issues that look like invalid ones, I'm going to close them more quickly.
See https://www.vim.org/issues.php.
For this issue "Not using "--clean"" applies.
