### ISSUE TITLE
setqflist() modifies its argument unexpectedly

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#11653]
### Steps to reproduce

1. Run `vim --clean`
2. Source the following file:
```vim
func s:qftf(_)
endfunc

let d = {'quickfixtextfunc': 's:qftf'}
call setqflist([], 'a', d)
echo d
```
3. `{'quickfixtextfunc': '<SNR>12_qftf'}` is printed: `dict` was modified unexpectedly

### Expected behaviour

`{'quickfixtextfunc': 's:qftf'}` is printed

### Version of Vim

9.0.910

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

**Comment by zeertzjq** [comment]
This is likely a regression from patch 8.2.3889.

**Comment by brammool** [comment]
> This is likely a regression from patch 8.2.3889.

Yes, that is right.  Trying to return a non-allocated string makes this
happen.

-- 
hundred-and-one symptoms of being an internet addict:
203. You're an active member of more than 20 newsgroups.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
