### ISSUE TITLE
vim doesn't answer if macro calls itself

### ISSUE THREAD

**Issue by n10v** [vim/vim#1165]
Hi. If you recorded macro, what calls itself, when vim doesn't answer.
For example, try to type these keys in command mode: `qq@qq@q` and your vim will not answer at all. I think, it should be fixed

**Comment by vim-ml** [comment]
On 13 October 2016, Albert vim-dev-github@256bit.org wrote:

> Hi. If you recorded macro, what calls itself, when vim doesn't answer.
> For example, try to type this keys in command mode: `qm@mq@m`. And your vim will not answer. I think, it should be fixed

```
Congratulations!  You have invented Vim's version of the classic
```

fork bomb!

```
/lcd
```

**Comment by n10v** [comment]
@vim-ml 😅

**Comment by n10v** [comment]
@chrisbra why did you close it? Is it already fixed?

**Comment by n10v** [comment]
:(

**Comment by ZyX-I** [comment]
Fixed what? It is interruptible by `<C-c>` and there is no “fork bomb” at all and this sequence does not even consume memory.

You asked Vim to recursively call a macro without leaving some stop condition (macros execution is stopped on errors) and you are indeed seeing Vim recursively calling a macro. Not a bug, user cannot be forbidden to write an infinite loop of some kind, Vim authors just need to be sure it is interruptible by `<C-c>` and it is.

**Comment by n10v** [comment]
@ZyX-I thanks! I needed some answer
