### ISSUE TITLE
E924 error

### ISSUE THREAD

**Issue by jpmv27** [vim/vim#1167]
When using location lists, multiple tabs, and switchbuf=usetab, I am seeing E924 errors that don't make sense. It seems that I can trigger one simply by selecting an entry in the location bar of one tab that corresponds to a file that is open in a window in another tab.

I don't see the same thing happen when using the quickfix list instead. In quickfix.c, I see that E924 cannot happen for the quickfix list, only for location lists. Why is that?

Any thoughts to explain what I'm seeing?

I can reproduce this as follows:
- Completely empty .vimrc except for "switchbuf=usetab"
- cd to directory with a number of files
- Open a file in tab 1
- Open a different file in tab 2
- From tab 2, use lgrep to search for a string in the first file
- When switching to first tab for a match, E924 error is displayed

This is just a guess, but is it the switching of tabs that is fooling the code into thinking that the window has been closed? Should win_valid() be win_valid_any_tab() instead?

**Comment by chrisbra** [comment]
please use vi.stackexchange.com or vim-use ml for asking user questions. Read the help at :h E924

**Comment by jpmv27** [comment]
Thanks. Was trying to report a bug. Where should I do that?

**Comment by chrisbra** [comment]
Hi Martin!

On Fr, 14 Okt 2016, Martin Vuille wrote:

> Thanks. Was trying to report a bug. Where should I do that?

Why do you think this is a bug?

Best,

## Christian

Teile deine Welt mit anderen. Wenn du dies nicht tust,
wundere dich nicht darüber, daß du einsam bist.
        -- Benjamin Stramke

**Comment by jpmv27** [comment]
Hi Christian,

Is it expected behaviour to get E924 when there are no autocmds running, just by following the procedure I described?

**Comment by chrisbra** [comment]
Not sure, and your steps where not very exact. Please provide exact 
steps, starting from vim -u NONE -N 

Best,

## Christian

Auch für alles Geld der Welt bekommt man nicht, was wirklich zählt.
        -- Hans Menzel

**Comment by jpmv27** [comment]
OK, will do, stay tuned...

**Comment by jpmv27** [comment]
Both terminal vim and GUI vim behave the same way, I am using terminal vim (7.4.1868 and 7.4.2191)
- echo foo > foo
- echo bar > bar
- vim -u NONE -N
- :set switchbuf=usetab
- :e foo
- :tabe bar
- :lgrep foo *

An error E924 is generated when switching back to the 'foo' tab. I believe this is a bug
And I believe the bug is due to using win_valid() instead of win_valid_any_tab() at line 2269 of quickfix.c
Changed win_valid() to win_valid_any_tab() in quickfix.c, the E924 error is no longer seen.

**Comment by chrisbra** [comment]
Thanks, yes that looks like a bug.

**Comment by jpmv27** [comment]
Shall I send a PR? Do you have specific things to include?

**Comment by chrisbra** [comment]
Sure, would be great if you  could also add a test

**Comment by jpmv27** [comment]
Would like to do so as well. But I am unsure how to incorporate the files "foo" and "bar" into the test. I guess that's a question I should ask on the dev list.

**Comment by vim-ml** [comment]
Op 14 okt. 2016 17:21 schreef "Martin Vuille" vim-dev-github@256bit.org:

> But I am unsure how to incorporate the files "foo" and "bar" into the
> test.

You can write them from the test.

Christ van Willegen
