### ISSUE TITLE
Write during insert mode can corrupt undofile

### ISSUE THREAD

**Issue by doubleloop** [vim/vim#11674]
### Steps to reproduce

1. `$ VIMRUNTIME=$PWD/runtime src/vim -u NORC /tmp/testfile.txt`
2. `:set nocompatible undofile`
3. `:imap . <cmd>write<cr>`
4. `:write`
5. `:call feedkeys("Otest.\<cr>boo!!!\<esc>")`
6. `:call feedkeys("u")`

### Expected behaviour

buffer should be empty instead of
```
boo!!!
```

### Version of Vim

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Dec  8 2022 00:16:20) Included patches: 1-1027

### Environment

debian testing
gnome terminal
xterm-256color
zsh 5.9

**Comment by chrisbra** [comment]
hmm, I guess we need:
```diff
diff --git a/src/edit.c b/src/edit.c
index 43f7d9abb..dc27fc31e 100644
--- a/src/edit.c
+++ b/src/edit.c
@@ -1049,6 +1049,7 @@ doESCkey:

        case K_COMMAND:             // <Cmd>command<CR>
        case K_SCRIPT_COMMAND:      // <ScriptCmd>command<CR>
+           start_arrow(&curwin->w_cursor);
            do_cmdkey_command(c, 0);
 #ifdef FEAT_TERMINAL
            if (term_use_loop())
```

This will break the undo sequence before the `<cmd>` so you then need 2 undos to have an empty buffer. Would that make sense?

**Comment by brammool** [comment]
Calling start_arrow() for every <Cmd> mapping doesn't appear needed and may be unexpected.
The problem is that write() syncs undo, the next character typed should save for undo again.

The subject of this issue mentions "corrupt undofile", but I assume that's not actually the problem.
