### ISSUE TITLE
Using setcmdline() in <Cmd> mapping on cmdline triggers CmdlineChanged twice

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#11682]
### Steps to reproduce

1. Run `vim --clean`
2. Source the following file:
```vim
let g:log = []
cnoremap <F1> <Cmd>call setcmdline('ls')<CR>
autocmd CmdlineChanged : let g:log += [getcmdline()]
call feedkeys(":\<F1>", 'xt')
echo g:log
```
3. `['ls', 'ls']` is printed

### Expected behaviour

`['ls']` is printed

### Version of Vim

9.0.910

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

**Comment by zeertzjq** [comment]
I wonder if this `clen == ccline.cmdline` check can just be removed:
```diff
diff --git a/src/ex_getln.c b/src/ex_getln.c
index 44049c761..5b4c66d0c 100644
--- a/src/ex_getln.c
+++ b/src/ex_getln.c
@@ -1790,8 +1790,7 @@ getcmdline_int(
 
 	    if (do_cmdkey_command(c, DOCMD_NOWAIT) == OK)
 	    {
-		if (clen == ccline.cmdlen)
-		    trigger_cmdlinechanged = FALSE;
+		trigger_cmdlinechanged = FALSE;
 		goto cmdline_changed;
 	    }
 	}
```

I don't think a `<Cmd>` mapping can change command line without using `setcmdline()`, and `setcmdline()` already triggers `CmdlineChanged`.

**Comment by brammool** [comment]
> I wonder if this `clen == ccline.cmdline` check can just be removed:
> ```diff
> diff --git a/src/ex_getln.c b/src/ex_getln.c
> index 44049c761..5b4c66d0c 100644
> --- a/src/ex_getln.c
> +++ b/src/ex_getln.c
> @@ -1790,8 +1790,7 @@ getcmdline_int(
>  
>  	    if (do_cmdkey_command(c, DOCMD_NOWAIT) == OK)
>  	    {
> -		if (clen == ccline.cmdlen)
> -		    trigger_cmdlinechanged = FALSE;
> +		trigger_cmdlinechanged = FALSE;
>  		goto cmdline_changed;
>  	    }
>  	}
> ```
> 
> I don't think a `<Cmd>` mapping can change command line without using
> `setcmdline()`, and `setcmdline()` already triggers `CmdlineChanged`.

This still sound like guessing.  We can count the number of times
CmdlineChanged is triggered, and if the count changed then set
trigger_cmdlinechanged.

-- 
GALAHAD:   Camelot ...
LAUNCELOT: Camelot ...
GAWAIN:    It's only a model.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
