### ISSUE TITLE
please support perl regex, perl regex is more prevalent

### ISSUE THREAD

**Issue by Silentdoer** [vim/vim#11680]
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
A clear and concise description of what is hard to do. Ex. It is difficult to [...] when [...]
(If it is related to runtime files, please check their header for where to discuss enhancements.)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chrisbra** [comment]
Such a small request, so much work.

This is basically impossible to do, because the perl regex does not provide all the features that vim provides (e.g. match at certain positions/marks). I think using [\v](https://vimhelp.org/pattern.txt.html#%2F%5Cv) is close enough

Also see #99

**Comment by brammool** [comment]
Hmm, ignoring the instructions would already be enough to just close this issue.

Adding another regex syntax is out of the question.  Perl is not that popular these days anyway.

**Comment by chrisbra** [comment]
> Hmm, ignoring the instructions would already be enough to just close this issue.

Indeed, I thought I give the OP a chance to change it or reply to it. Perhaps I need to be more brave to close tickets.
