### ISSUE TITLE
Bug:  term_start($SHELL, {'term_rows':0} Caught deadly signal ABRT

### ISSUE THREAD

**Issue by dezza** [vim/vim#11697]
### Steps to reproduce

I read in help `term_start()`:

`
		   "term_rows"	     vertical size to use for the terminal,
				     instead of using 'termwinsize'; valid
				     range is from zero to 1000
`

So I decided to try 0, which resulted in crash.

### Expected behaviour

An error message, or a closed terminal buffer, maybe..

### Version of Vim

9.0.1024

### Environment

Operating system: Windows, WSL (Linux/Ubuntu22.04)
Terminal: Windows Terminal
Value of $TERM: xterm-256color
Shell: bash

### Logs and stack traces

```sh
vim --clean -c "+call term_start('/bin/bash', {'term_rows': 0})"
Vim: Caught deadly signal ABRT
Vim: Finished.

Aborted
```

**Comment by brammool** [comment]
This happens somewhere in the libvterm code.  If tails this check and then intentionally crashes:
```
  /* We really expect the cursor position to be set by now */
  if(active && (new_cursor.row == -1 || new_cursor.col == -1)) {
    fprintf(stderr, "screen_resize failed to update cursor position\n");
    abort();
  }
```

Perhapsl @leonerd knows how to fix it.  For now, I'll just set the cursor position to avoid the crash.
