### ISSUE TITLE
consider making visual mode `/\%V` use the visual area user calls the `/\%V` first time

### ISSUE THREAD

**Issue by haolian9** [vim/vim#11695]
**the current behavior**

1. `$ seq 20 | vim -u NONE +'set hlsearch' -`
2. `:1`, `V9j`
3. `/\%V\d<cr>`
4. `n` x3

during repeating `n`, the previous visual area of `\%V` changes dynamically.
`\%V` actually works in line-wise, either the first line of the current visual area or the last line.

**Describe the solution you'd like**

`/\%V` freezes the visual area at the first run of `/\%V`.

**extra**

pressing `<esc>` between 2 and 3 to make `\%V` use `gv` seems to be a solution, but once you something like `nvnn` or `nVnn`, users will still suffer from this line-wise like behavior, and this behavior keeps surprising me, it does take me time to understand why.

**Comment by chrisbra** [comment]
After step 2, you are still in visual mode. Now any search you make, will change (extend or shrink) your visual selection. 

But you rather want to search within the current visual selection. I am not sure this make sense, and this will be a backwards incompatible change. Just type `ESC` to quit the visual selection and it will work as you want. You can then even use `CTRL-G` and `CTRL-T` to move between matches. But you need to be not in visual mode anymore.

**Comment by haolian9** [comment]
Thanks for your replies!

> rather want to search within the current visual selection
yeah, at step 3, I want to apply matches against to the area 1,10 in the ensuing `n`s, and now the area used by `\%V` changes as I pressing `n`.

> this will be a backwards incompatible change.
I'd say I hardly belive someone can found this behavior useful to use. IMHO, if a feature/behavior keeps suprising users so that no one finds it useful, what's the meaning to keep backward compatibility of it.

**Comment by chrisbra** [comment]
well, I regularly use visual mode and then search for some token, which I need to change, e.g. run a `:s` command on it.

**Comment by haolian9** [comment]
ha yeah, thanks for sharing, I prefer that way too, even further do `ctrl_V` + `:s/\%V` sometimes.

I had thought this issue several times, and I actually found no real applications in my daily use for this feature. why should i bother the thing i'll never touch? so i think this issue ought to be closed at now.
