### ISSUE TITLE
Wrong coloring syntax

### ISSUE THREAD

**Issue by flyingdutchman** [vim/vim#11722]
### Steps to reproduce

![image](https://user-images.githubusercontent.com/26379223/208308349-b836c713-8224-48e7-bdc9-020ebad1e8cd.png)

Here it is in written format :
```
#! /bin/bash

arr=()

scanHost()
{
  arr+=("$(hostname)")
  tmpResult=$(hostname)
}

scanHost

eval "$(ssh operator@sasqa_vm_09 "bash -s --" <<EOF
$(typeset -f scanHost)
$(declare -p arr)
scanHost
declare -p arr
declare -p tmpResult
EOF
)"

echo "Local array -> ${arr[@]}"
echo "Local echo  -> $tmpResult"
```

Use the following functional code

### Expected behaviour

The color syntax is wrong starting with the subshell at line 13. The content of the two echo at line 22 and 23 should be yellow for instance

### Version of Vim

VIM - Vi IMproved 6.4 (2005 Oct 15, compiled May  3 2006 12:40:19)

### Environment

- OS : AIX 7.3
- Terminal : Windows Terminal
- TERM : xterm-256color
- SHELL : Bash 5.1.4(1)-release

**Comment by neutaaaaan** [comment]
`VIM - Vi IMproved 6.4 (2005 Oct 15, compiled May 3 2006 12:40:19)`

I don't mean to come across as *overly snarky*, big iron being big iron, but chances are that if there was something to fix, it has been fixed sometimes during the last 17 years. I'm getting slightly different results using vim9 right now.

You could try tossing the current syntax file onto that box, but your best bet is to try and catch up if at all possible.

**Comment by chrisbra** [comment]
wow, that is an old version.

Looks like the latest version available for AIX is 7.4.460 (which is also quite old): http://www.perzl.org/aix/index.php?n=main.vim

BTW: if @flyingdutchman could share the bash snippet it's easier to reproduce and show syntax output.

**Comment by Shane-XB-Qian** [comment]
similar one:

```bash
output="$(
	foo
	sed 's/"//g'
	bar
)"
```

// though perhaps was not a recommend coding style.

**Comment by cecamp** [comment]
I've fixed the problem Shane pointed out, although I have yet to run it through my test suite and see what happens (and fix 'em). The OP's problem I won't touch until I get some code I can work with; I'm pretty busy and don't have the time to type all that in.

**Comment by flyingdutchman** [comment]
Thanks for the quick responses ! 

Here is the code, I also updated the original post to have it
```
#! /bin/bash

arr=()

scanHost()
{
  arr+=("$(hostname)")
  tmpResult=$(hostname)
}

scanHost

eval "$(ssh operator@sasqa_vm_09 "bash -s --" <<EOF
$(typeset -f scanHost)
$(declare -p arr)
scanHost
declare -p arr
declare -p tmpResult
EOF
)"

echo "Local array -> ${arr[@]}"
echo "Local echo  -> $tmpResult"
```

**Comment by chrisbra** [comment]
Hi,
I checked on my local installed version 9.0.975 and it seems to be okay I would say.
![grafik](https://user-images.githubusercontent.com/244927/209078863-12004249-06ad-48b1-8c69-9f79878fa152.png)

@flyingdutchman you may try to update the sh.vim syntax file from @cecamp website http://www.drchip.org/astronaut/vim/index.html#SYNTAX_SH However I am not sure this will work on your old vim version.

**Comment by flyingdutchman** [comment]
Great thanks for the help ! I'll try that :)

Since the issue is only present on old versions, I'll just close this issue.
