### ISSUE TITLE
Vim syntax coloring is broken for short commands

### ISSUE THREAD

**Issue by chdiza** [vim/vim#11721]
### Steps to reproduce

Fire up `vim --clean`, do `se ft=vim`, and just let there be two lines:
```
retu
return
```
Notice that only the full `return` gets colored, while the `retu` is not colored.

### Expected behaviour

This is broken; it used to work.

I can see this wrong coloring with `cal/call` as well.

### Version of Vim

9.0.1065

### Environment

Ubuntu 20.04
kitty

**Comment by chdiza** [comment]
Bisecting with `git` reveals:
```
71b6d3397649fed68ef587aa863fcbdf5fdb057a is the first bad commit
commit 71b6d3397649fed68ef587aa863fcbdf5fdb057a
Author: Bram Moolenaar <Bram@vim.org>
Date:   Sat Sep 10 13:13:14 2022 +0100

    Update runtime files
```

**Comment by chdiza** [comment]
`cal[l]` got wrongly replaced with `call`, and `retu[rn]` got wrongly replaced with `return`.

Examining the differences between the culprit and its predecessor, I can also see that the following got broken as well:

`fu/function` .  `fu[nction]` got wrongly replaced with three different words (`fun`, `func`, and `function`).

`endf/endfunction`.  `endf[unction` got wrongly replaced with three different words (`endfun`, `endfunc`, and `endfunction`).

`delf/delfunction`.  `delf[unction]` got wrongly replaced with plain old `delfunction`.

**Comment by cecamp** [comment]
Looks like the help for the various things you mentioned got moved to a file (userfunc.txt) that hadn't been considered by my script. It is now, and the updated syntax/vim.vim has these fixes incorporated into them. Thanks!

**Comment by brammool** [comment]
> `cal[l]` got wrongly replaced with `call`, and `retu[rn]` got wrongly replaced with `return`.
> 
> Examining the differences between the culprit and its predecessor, I can also see that the following got broken as well:
> 
> `fu/function` .  `fu[nction]` got wrongly replaced with three different words (`fun`, `func`, and `function`).
> 
> `endf/endfunction`.  `endf[unction` got wrongly replaced with three different words (`endfun`, `endfunc`, and `endfunction`).
> 
> `delf/delfunction`.  `delf[unction]` got wrongly replaced with plain old `delfunction`.

I just received an updated Vim syntax file from Charles that appears to
fix this problem.  Will be in the next runtime files update.

-- 
ARTHUR:    Well, it doesn't matter.  Will you go and tell your master that
           Arthur from the Court of Camelot is here.
GUARD #1:  Listen, in order to maintain air-speed velocity, a swallow
           needs to beat its wings 43 times every second, right?
ARTHUR:    Please!
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chdiza** [comment]
Thanks so much for the rapid fix!
