### ISSUE TITLE
Is it possible that vim support php like Python?

### ISSUE THREAD

**Issue by bleakwind** [vim/vim#1172]
Is it possible that vim support php like Python?
So we can write a plugin for vim to use php...

**Comment by chrisbra** [comment]
We already have lua, perl, python 2 and 3 and tcl. While it might be possible to embed php into Vim as well, provided someone creates a patch for it, I personally don't think it is worthwile to have yet another language embedded into Vim.

**Comment by mcepl** [comment]
There is also https://github.com/vim-scripts/if_v8 ... of course, it is completely bitrot right now, but it gives a hope that something like independent plugin could be possible.

**Comment by bleakwind** [comment]
> I personally don't think it is worthwile to have yet another language embedded into Vim.

Then why put lua, perl, python 2 and 3 and tcl in Vim.
Why phper can't have right or fun like them???

As I know, even Vim website use php.
Just let php can use like python in vim.

Phper is very big community, is good for vim and phper.

Hope you can do this for phper! Thanks!

**Comment by mcepl** [comment]
> Then why put lua, perl, python 2 and 3 and tcl in Vim. Why phper can't have right or fun like them???

I agree … we should get rid of TCL, Lua, and Perl support in vim.

In reality I see plugins either in plain VimL, or (when more serious programming language and external libraries are needed) in Python (py2 and py3 is just temporary problem given the situation in the Python world, in few years py2k will be finally gone).

Did anybody see any Perl, Lua, or TCL vim plugin lately?

**Comment by vim-ml** [comment]
> ...
> 
> Did anybody see any Perl, Lua, or TCL vim plugin lately?
> 
> I am a regular use of Vim's Perl interface.

When I last checked, Perl still has features (DBI - database interface, in
this case) which Python just doesn't have.
Python may have created a specification for it, but if no one has
implemented it for the myriad of databases out there, it is essentially
useless.

My 2 cents.
David

**Comment by mcepl** [comment]
> Perl still has features (DBI - database interface, in this case) which Python just doesn't have.

Ehm, https://www.python.org/dev/peps/pep-0249/ ... implemented by all Python DB drivers for all imaginable databases (SQLite is built-in standard Python, all other relational databases have implementations on PyPI). Actually, SQL database standardization is one of the stronger points in the Python toolbox, I would say. So, yes, you can have your vim plugin pulling data from [OracleDB](https://bitbucket.org/clach04/jyjdbc/) ;).

**Comment by bleakwind** [comment]
You don't need put php in vim. just let ous use php like python.

On Win:
-DDYNAMIC_PYTHON_DLL="Python27.dll"
Let ous use php like this:
-DDYNAMIC_PHP_DLL="php7ts.dll"

On Unix Also like python.

If is possible, why not do this?! you got nothing to loss...

**Comment by char101** [comment]
Because there is no one that is willing to implement the PHP binding. Check [if_python.c](https://github.com/vim/vim/blob/master/src/if_python.c), it is 1597 lines, [if_ruby.c](https://github.com/vim/vim/blob/master/src/if_ruby.c) 1609 lines, [if_perl.xs](https://github.com/vim/vim/blob/master/src/if_perl.xs) 1865 lines. It is not a trivial task. Vim is open source, so even though PHP is not officially integrated, you can always compile it yourself, as long as someone writes the implementation.

**Comment by Shougo** [comment]
> Did anybody see any Perl, Lua, or TCL vim plugin lately?

neocomplete and xolox/vim-lua-ftplugin use if_lua.
Perl-Support plugin use if_perl.
I don't know the plugins which uses if_tcl.

**Comment by lcd047** [comment]
> Did anybody see any Perl, Lua, or TCL vim plugin lately?

I'm using `if_perl` for interfacing with several big scientific packages.  If Vim couldn't do that I'd have to switch to Emacs.  Definitely a crucial feature for me.

For Lua you can take a look at Neovim. :smile:

**Comment by bleakwind** [comment]
I write interface use VimScript for Vim, use system() to run php language, and now can write Vim plugins use php language just like python. It doing well...
Thanks everyone...

**Comment by vim-ml** [comment]
Rick Woo wrote：
> I personally don't think it is worthwile to have yet another language embedded into Vim.
> 
> Then why put lua, perl, python 2 and 3 and tcl in Vim.
> Why phper can't have right or fun like them???
> As I know, even Vim website use php.
> Just let php can use like python in vim.
> 
> Phper is very big community, is good for vim and phper.
> Hope you can do this for phper! Thanks!
> 

As a java developer, can I ask why java can't use like python in vim ?
Javaer is the biggest community, is good for vim and javaer.

As a c# developer, can I ask why c# can't use like python in vim ?
CSharper is the 6th biggest community (TIOBE), is good for vim and csharper.

.....

If every body ask to support their favorite language in vim, the code size will bloat and soon will be out of control. Introducing a new feature is cheaper than maintaining it.

Would you please just learn some VimScript ? It is very similar to php. If you want to extend your vim, spending 2-3 days in vimscript is worthy and enough.

Why we need python here ? Python is a general purpose language which has  countless modules/packages. Most of time, we don't need write a DLL/so in C++ like the old days. Now we can use python to achieve same thing, like calling foreign languages/DLLs, threading, networking, databases .....

Why we need lua here ? Lua got a flexible syntax, can use less code to do the samething than vimscript and run faster than python and vimscript, most important thing it is very tiny.

What benefit can vim get if we embed another new language right now ? except making some people who don't want to study new things happy ?

I don't write much python code too, I am not a python developer either. But when I need to extend my vim, I can study python and vimscript as well.

Even if vim support php, nobody can use only php to write plugin without fully understand vimscript.

**Comment by bleakwind** [comment]
I know what you meaning, but as @char101 says: if_python.c, if_ruby.c, if_perl.xs just over 1000 lines, it's not big. And we can choose whether to install these support, do not need to put whole php, python compiled into Vim.

I have learned VimScript, but when I write  a plugin still not as good as php language, if you are python programmer, you will prefer python to write plugin too. 

More people want to find an good editor, not a new language? We use Vim is not to learn new things happily, just want using Vim happily.

We don't want to write a plugin without VimScript, just want to write plugin like python way.

Vim can be used as a glue language, then programmers can write plugin in their favorite language...

**Comment by bleakwind** [comment]
I write interface use VimScript for Vim, use system() to run php language, and now can write Vim plugins use php language just like python. It doing well...

And can Vim add this feature:

Set multiple lines variable:
let myvar = << EOD
... string part one...
... string part two...
EOD;

In Visual mode, getpos is last time position, not current select character position.
    let [l:lnum1, l:col1]   = getpos("'<")
    let [l:lnum2, l:col2]   = getpos("'>")
How can I get current select character in Visual mode, if not Visual mode, do not return me the last time position, just return me [0, 0, 0, 0]. because the function mode() can not return current mode.

**Comment by vim-ml** [comment]
2016-12-25 18:36 GMT+03:00 Rick Woo <vim-dev-github@256bit.org>:
> I know you are meaning, but as @char101 says: if_python.c, if_ruby.c,
> if_perl.xs just over 1000 lines, it's not big. And We can choose whether to
> install these support, do not need to put whole php, python compiled into
> Vim.

if_python*.c files are not enough (they contain only
python-version-specific code), most code is in if_py_both.h and it has
6837 lines (+ 1597 lines of if_python.c or 1682 lines of
if_python3.c). if_ruby.c and if_perl.xs are very bad examples, the API
they provide does not have many features Python has and even Python
API does not have enough features to allow Python developers to avoid
learning VimL in complex cases.

>
> I have learned VimScript, but when I write a plugin still not as good as php
> language, if you are python programmer, you like python write plugin too.

For any more or less complex plugin you can’t write it in Python, only
in Python+VimL. Or find some third-party library which wraps things
for which you need to use VimL and prepare to face leaking
abstractions.

>
> We just want to find an good editor, not a new language? We use Vim is not
> to learn new things happily, just want using Vim happily.
>
> We don't want to write a plugin without VimScript, just want to write plugin
> like python.
>
> Vim can be used as a glue language, then programmers can write plugin in
> their favorite language.

I think that Neovim is following the right path here: Vim just needs
IPC features with normal RPC API (no, channels are way too limited
compared to Neovim API). Add `-heredoc` argument to `:command` there
and you can create wrappers for any external language you like without
changing the core.

**Comment by vim-ml** [comment]
imho the best vim is a vim built with no added interpreters -- lean and
mean and no surprises

any time I want to use another language I build a filter script, send the
relevant lines out to fmt,
or a python or perl or tcl or awk script coded to return those lines with
my beautiful enhancements
