### ISSUE TITLE
[feature-request] vim9-class: support "new ClassName" instead of "ClassName.new" to create instance

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#11739]
I've noticed that vim9-class is working in progress right now. Before everything becomes unchangeable, can I suggest to use
"new ClassName" instead of "ClassName.new" to create an instance ?

According to the description in `vim9class.txt`:

> An object can only be created by a class.  A class provides:
> - A new() method, the constructor, which returns an object for the class.
>   This method is invoked on the class name: MyClass.new().

An object can be created by:

```viml
var pos = TextPosition.new(1, 1)
```

Is it possible to change it to:

```viml
var pos = new TextPosition(1, 1)
```

this makes me feel more nature/familiar.

Since the vim9-class is built from scratch without any backward-compatible problems,
why not choose some intuitive grammars ?

**Comment by chrisbra** [comment]
See also the discussion on the vim-dev list, starting here: https://groups.google.com/g/vim_dev/c/MKbzhgqvSj8/m/CTpMTe5YDQAJ

I recommend to keep the discussion on the mailing list, to have a single space where improvements are discussed

**Comment by lilydjwg** [comment]
> this makes me feel more nature/familiar.

But it makes me feel that I should put a `delete pos` somewhere to avoid resource leakage.

I prefer the suffix version because, well, it makes me feel more nature/familiar as I mostly write in Python & Rust.

**Comment by bfrg** [comment]
I think this can be closed since it's been discussed in the link @chrisbra provided.
