### ISSUE TITLE
messages behavior depends on 'fileformat' of current buffer

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#11735]
### Steps to reproduce

1. Run `vim --clean`
2. Run `:echomsg "\r"`
3. `^M` is printed
4. Run `:messages`
5. `^M` is printed
6. Run `:setlocal fileformat=mac`
7. Run `:messages`
8. `^J` is printed

### Expected behaviour

Changing 'fileformat' of current buffer should not affect messages behavior

### Version of Vim

9.0.1046

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> 1. Run `vim --clean`
> 2. Run `:echomsg "\r"`
> 3. `^M` is printed
> 4. Run `:messages`
> 5. `^M` is printed
> 6. Run `:setlocal fileformat=mac`
> 7. Run `:messages`
> 8. `^J` is printed
> 
> ### Expected behaviour
> 
> Changing 'fileformat' of current buffer should not affect messages behavior

This happens in transchar_nonprint().  There it assumes the text is
coming from the current buffer.

Passing a flag down whether 'fileformat' of curbuf is to be used
requires changing a lot of functions.  A global flag set in
ex_messages() is simpler, bug ugly.

This should be quite rare, low priority.

-- 
WOMAN:   Well, 'ow did you become king then?
ARTHUR:  The Lady of the Lake, [angels sing] her arm clad in the purest
         shimmering samite, held aloft Excalibur from the bosom of the water
         signifying by Divine Providence that I, Arthur, was to carry
         Excalibur.  [singing stops] That is why I am your king!
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
