### ISSUE TITLE
[vim9-class] E1010: Type not recognized when using class types in type hints

### ISSUE THREAD

**Issue by bfrg** [vim/vim#11749]
### Steps to reproduce

Run `vim --clean -S test.vim`, with

```vim
vim9script

class Person
    public this.age: number
endclass

def Test(person: Person)
enddef
```

Result:
```
E1010: Type not recognized: Person
```

Similarly:
```vim
vim9script

class Person
    public this.age: number
endclass

var p1 = Person.new(10)
var p2: Person = p1
```

Result:
```
E1010: Type not recognized: Person = p1
```

### Expected behaviour

No errors

### Version of Vim

9.0.1093

### Environment

Linux

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> Run `vim --clean -S test.vim`, with
> 
> ```vim
> vim9script
> 
> class Person
>     public this.age: number
> endclass
> 
> def Test(person: Person)
> enddef
> ```
> 
> Result:
> ```
> E1010: Type not recognized: Person
> ```

Using a class name as a type is not implemented yet.


-- 
       [Autumn changed into Winter ... Winter changed into Spring ...  Spring
       changed back into Autumn and Autumn gave Winter and Spring a miss and
       went straight on into Summer ...  Until one day ...]
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bfrg** [comment]
Fixed in https://github.com/vim/vim/commit/eca2c5fff6f6ccad0df8824c4b4354d3f410d225.
