### ISSUE TITLE
new line support in virutal text

### ISSUE THREAD

**Issue by coot** [vim/vim#11757]
Some languages provide quite reach well structured compilation errors, for example `GHC` (`Haskell`'s compiler) errors are quite verbose:
```
/tmp/poly.hs:5:22: error:
    • Could not deduce (Enum String)
        arising from the arithmetic sequence ‘1 .. ’
      from the context: Num a
        bound by the type signature for:
                   diffPoly :: forall a. Num a => [a] -> [a]
        at /tmp/poly.hs:4:1-41
    • In the second argument of ‘zipWith’, namely ‘[1 .. ]’
      In the first argument of ‘(.)’, namely ‘zipWith f [1 .. ]’
      In the expression: zipWith f [1 .. ] . tail
  |
5 | diffPoly = zipWith f [1..] . tail
  |                      ^^^^^
```

It would be quite nice to be able to show such errors preserving its format as virtual text.  Currently, neither _virtual text_ nor _quickfix list_ support such error messages.

**Comment by brammool** [comment]
> Some languages provide quite reach well structured compilation errors,
> for example `GHC` (`Haskell`'s compiler) errors are quite verbose:
> ```
> /tmp/poly.hs:5:22: error:
>     • Could not deduce (Enum String)
>         arising from the arithmetic sequence ‘1 .. ’
>       from the context: Num a
>         bound by the type signature for:
>                    diffPoly :: forall a. Num a => [a] -> [a]
>         at /tmp/poly.hs:4:1-41
>     • In the second argument of ‘zipWith’, namely ‘[1 .. ]’
>       In the first argument of ‘(.)’, namely ‘zipWith f [1 .. ]’
>       In the expression: zipWith f [1 .. ] . tail
>   |
> 5 | diffPoly = zipWith f [1..] . tail
>   |                      ^^^^^
> ```
> 
> It would be quite nice to be able to show such errors preserving its
> format as virtual text.  Currently, neither _virtual text_ nor
> _quickfix list_ support such error messages.

I would think an error message like that belongs in a popup window.
It's much too long for virtual text.

The quickfix items already have a "text" field.  Either that can be used
and we need some way to show the text as-is (currently it's formatted
into a single line), or another field would need to be added (but we
have so many fields already...).

I would think of highlighting the location of the error, and when
hovering over that location (or with a command) a popup shows the error.
I would not be surprised there already is something for that.


-- 
John:   When I'm playing tennis with friends I always get carried away
George: You hurt your foot each time?

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bfrg** [comment]
You could split the multi-line error message with `split(text, '\n')` and then add each item in the list using `prop_add()`. For multi-line messages you probably want to align the virtual text `above` or `below` to preserve the formatting of the error text.

**Comment by bfrg** [comment]
This is what it would look like:
![screenshot-2022-12-28_221538](https://user-images.githubusercontent.com/6266600/209873167-35db89ac-faf8-49c3-b1bf-65e9ae7a3898.png)

IMO, having so much virtual text displayed at once is more distracting than useful. Better use a popup window like Bram suggested, and open it up for the error you're interested in. For example:
![screenshot-2022-12-28_221702](https://user-images.githubusercontent.com/6266600/209873255-7a6b6b1c-d7eb-4b48-9165-657c23181522.png)

**Comment by coot** [comment]
Thank you both, using popup is indeed the way to go.
