### ISSUE TITLE
Oversight in `keywordprg` handling.

### ISSUE THREAD

**Issue by romainl** [vim/vim#1175]
When `keywordprg` is set to an Ex command, the argument is quoted as if `keywordprg` was set to an external command. This makes using an arbitrary Ex command for `keywordprg` useless.

Sample file:

```
111 console
aaa
console
  ^ cursor on the first o
```

Commands:

```
:set keywordprg=:psearch
K
```

Expected result: the first line containing `console` is displayed in the preview window.

Actual result:

```
E389: Couldn't find pattern
```

Explanation: the argument seems to be quoted before being given to the Ex command, preventing it to do anything useful.

```
:psearch 'console'
E389: Couldn't find pattern
```

Cause: `kp_ex` is not checked in [this conditional](https://github.com/vim/vim/blob/226630a030c0d41145e1109f09633360fc9c999d/src/normal.c#L5714).

```
if (cmdchar == 'K' && !kp_help)
```

**_VERY NAIVE**_ solution that will probably break other things:

```
if (cmdchar == 'K' && !kp_help && !kp_ex)
```

I unfortunately don't know enough about C and/or the Vim internals to provide an actual patch.

FWIW, `$ git blame` shows that the faulty line didn't change since 7.2-010.

**Comment by ntnn** [comment]
``` c
if (cmdchar == 'K' && (!kp_help || !kp_ex))
```

`kp_ex` is always true when `kp_help` is non-zero, however `kp_help` is
not always true when `kp_ex` is true.

This is likely a bug in neovim as well, since the patch came from there -
unless they handle escaping differently.

**Comment by ntnn** [comment]
Neovim is using just [`kp_ex`](https://github.com/neovim/neovim/blob/master/src/nvim/normal.c#L4760) instead of both `kp_help` and `kp_ex`, and [assert](https://github.com/neovim/neovim/blob/master/src/nvim/normal.c#L4672) that `kp` is not a null pointer instead of default to ':help'.
