### ISSUE TITLE
Vim freezes on builds after patch 9.0.1096.

### ISSUE THREAD

**Issue by mitsugu** [vim/vim#11751]
### Steps to reproduce

1. Open large HTML files
2. Use :%s to repeat string replacement multiple times.
3. Suddenly Vim freezes (process can be killed).

### Expected behaviour

Do not freeze.

### Version of Vim

9.0.1096 and later

### Environment

OS : Xubuntu  22.04.1 LTS
Terminal : gnome-terminal Version 3.44.0 for GNOME 42
Shell : fish Version 3.5.1
Other : tmux 3.3a

**Comment by brammool** [comment]
9.0.1097 fixes a problem introduced by 9.0.1096.  Can you still reproduce this problem?
The reproduction steps are not really reproducible.

**Comment by mitsugu** [comment]
I ran into this issue on 9.0.1097. 9.0.1095 does not have this issue.
Vim would eventually freeze whenever I did multiple string replacements on a wide range of files.

**Comment by brammool** [comment]
> I ran into this issue on 9.0.1097. 9.0.1095 does not have this issue.
> Vim would eventually freeze whenever I did multiple string replacements on a wide range of files.

I noticed the test for Python indent was hanging on some systems.
I eventually managed to reproduce it and found that it's related to the
hashtab change.  I made a fix, this hopefully also solves your problem.

-- 
TIM:    Too late.
ARTHUR: What?
TIM:    There he is!
   [They all turn, and see a large white RABBIT lollop a few yards out of the
   cave.  Accompanied by terrifying chord and jarring metallic monster noise.]
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mitsugu** [comment]
I have confirmed that the problem does not occur with 9.0.1103. Bram, thank you.

**Comment by chrisbra** [comment]
closing then.
