### ISSUE TITLE
Small typo in Slovenian translation of menu for word "Copy"

### ISSUE THREAD

**Issue by igor2x** [vim/vim#1176]
Hi,
I have found out a typo in Slovenian translations for word Copy. There is incorrect string "Kopieraj", correct word is "Kopiraj", so without letter "e".
Here is a proof from Google Translate: https://translate.google.com/#sl/en/Kopiraj

Fix:
1. I have downloaded source code from https://github.com/vim/vim/archive/master.zip
2. Unzipped the file.
3. cd vim-master/runtime/lang/
4. Fix typo with shell command: sed -i -e 's/Kopieraj/Kopiraj/g' menu_sl_si*

Note: The following three files now contain fix:
- menu_sl_si.cp1250.vim
- menu_sl_si.latin2.vim
- menu_sl_si.utf-8.vim

Regards

**Comment by brammool** [comment]
Have you tried contacting the maintainer?

**Comment by igor2x** [comment]
Few minutes ago I have send e-mail to maintainer's e-mail I have found in above three files. Lets see if we get some response back, but we may not, because "Last Change" was made 10 years ago.

**Comment by mojca** [comment]
It's been ages since I last touched the translations (I guess they need an update and perhaps some additional review anyway). I switched to Mac that doesn't use those menu translations, so I no longer have first-hand experience with what I did back then and I almost forgot that I did it at all. (I slightly remember noticing that problem, but then forgot to do anything about it.)

Yes, I would like to confirm the bug. Feel free to fix it yourself, it's just one byte in each of the three files, but I can do a pull request as well if that is what you prefer.

Igor, thanks a lot for submitting a bug report and for reaching to me.

**Comment by igor2x** [comment]
Hi,
I have checked gVim 8.0 in more detail and found four additional small typos and some additional missing strings problem. Note: I haven't spotted them before, because I use gVim with hidden menus, toolbars etc. The only think from GUI I use is right mouse menu where the typo from step 4 is.

Additional typos and fixes for them:
step 5:
`sed -i 's/Popravi\\\ z/Popravi\\\ s/g' menu_sl_si*`

step 6:
`sed -i -e 's/\&Keymap$/Razporeditev\\\ tip\&k/g' menu_sl_si*`

step 7:
`sed -i -e 's/Pretvori\\\ nazaj/Povrni\\\ pretvo\&rbo/g' menu_sl_si*`

step 8:
`sed -i 's/&Orodja/O\&rodja/g' menu_sl_si*`

Please also see attached document, there are some missing strings currently in gVim displayed as "English" text. This strings should be added before translation can be perfomed.

Regards

[suggestions.pdf](https://github.com/vim/vim/files/533274/suggestions.pdf)

**Comment by vim-ml** [comment]
Can you please provide a patch?

**Comment by igor2x** [comment]
Hi,
I have created a patch with all of the changes in my both posts.

Do the following:
1. Download MYPATCH.zip file from this post.
2. Extract archive:
`unzip MYPATCH.zip`
Note: File MYPATCH.patch is unzipped.
3. Copy MYPATCH.patch to Vim's source code directory runtime/lang/
4. Apply patch:
`patch < MYPATCH.patch`
5. Delete patch file MYPATCH.patch because it is not needed anymore:
`rm MYPATCH.patch`

Regards

[MYPATCH.zip](https://github.com/vim/vim/files/534065/MYPATCH.zip)

**Comment by brammool** [comment]
Thanks.  I'll also update the timestamp in the header.
