### ISSUE TITLE
Pasting no longer works correctly on foot terminal

### ISSUE THREAD

**Issue by AN3223** [vim/vim#11766]
### Steps to reproduce

1. Have some text in your clipboard
2. Paste into Vim's insert mode with Ctrl+Shift+V

### Expected behaviour

The contents of the clipboard should paste normally.

Instead an escape seems to be prepended to the clipboard? If the clipboard is "asdf" you will get "Sdf"

Unsetting the TERM environment variable gives the correct behavior.

### Version of Vim

9.0.1107

### Environment

OS: Alpine Linux
Terminal: Foot
TERM=foot
Shell: busybox ash

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> 1. Have some text in your clipboard
> 2. Paste into Vim's insert mode with Ctrl+Shift+V
> 
> ### Expected behaviour
> 
> The contents of the clipboard should paste normally.
> 
> Instead an escape seems to be prepended to the clipboard? If the clipboard is "asdf" you will get "Sdf"
> 
> Unsetting the TERM environment variable gives the correct behavior.
> 
> ### Version of Vim
> 
> 9.0.1107
> 
> ### Environment
> 
> OS: Alpine Linux
> Terminal: Foot
> TERM=foot
> Shell: busybox ash

Perhaps bracketed paste is enabled but not working properly?
See ":help xterm-bracketed-paste".

Check the output of:
	verbose set t_BE t_BD t_PS t_PE

You could try:

	  let &t_BE = ""
	  let &t_BD = "\e[?2004l"
	  exec "set t_PS=\e[200~"
	  exec "set t_PE=\e[201~"
	  !ls

The "!ls" command is get the t_BD code output.

This should disable bracketed paste, but still handle it if gets
switched on elsewhere somehow.

-- 
"Software is like sex... it's better when it's free."
		-- Linus Torvalds, initiator of the free Linux OS
Makes me wonder what FSF stands for...?

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Shane-XB-Qian** [comment]
maybe it related to `keyprotocol` ? the `foot` use `kitty` keyboard protocol by default.

and try vim v9.0.1117 in my case looks it helped bracketed paste issue which existed long time.
// thx bram very much. :-)

or just like bram said, disable it.

**Comment by AN3223** [comment]
Thank you for your quick responses.

> Check the output of: verbose set t_BE t_BD t_PS t_PE

```
  t_BE=^[[?2004h
  t_BD=^[[?2004l
E846: Key code not set: t_PS
```

> You could try: let &t_BE = "" let &t_BD = "\e[?2004l" exec "set t_PS=\e[200~" exec "set t_PE=\e[201~" !ls
> The "!ls" command is get the t_BD code output.
> This should disable bracketed paste, but still handle it if gets switched on elsewhere somehow.

This makes pasting work correctly! The `!ls` doesn't seem to be necessary though? I only point this out because I am putting this in my vimrc.

> maybe it related to `keyprotocol` ? the `foot` use `kitty` keyboard protocol by default.

Setting `keyprotocol=foot:mok2` or `keyprotocol=foot:none` doesn't seem to help?

> and try vim v9.0.1117 in my case looks it helped bracketed paste issue which existed long time. // thx bram very much. :-)

That's good to hear, I'll look out for it when it comes down the Alpine pipeline and I'll be sure to update this issue if the update helps.

**Comment by brammool** [comment]
> Thank you for your quick responses.
> 
> > Check the output of: verbose set t_BE t_BD t_PS t_PE
> 
> ```
>   t_BE=^[[?2004h
>   t_BD=^[[?2004l
> E846: Key code not set: t_PS
> ```

That would explain the trouble: The terminal sends text surrounded by
the bracketed paste escape sequences, but Vim is not setup to recognize
them.

You will have to somehow figure out how it is possible that t_BE and
t_BD are set, but t_PS and t_PE are not.  You can try starting Vim in
different ways, e.g. "vim --clean" and "vim -u NONE".  Or try setting
$TERM to different values.

You mentioned before that $TERM was set to "foot", I wonder where it
gets these termcap entries then.  These codes are only just being added
to the terminfo database (part of ncurses 6.4) and won't be in a
distributed package yet.


> > You could try: let &t_BE = "" let &t_BD = "\e[?2004l" exec "set t_PS=\e[200~" exec "set t_PE=\e[201~" !ls
> > The "!ls" command is get the t_BD code output.
> > This should disable bracketed paste, but still handle it if gets switched on elsewhere somehow.
> 
> This makes pasting work correctly! The `!ls` doesn't seem to be
> necessary though? I only point this out because I am putting this in
> my vimrc.

The "!ls" is only needed if you make changes after starutp.

> > maybe it related to `keyprotocol` ? the `foot` use `kitty` keyboard
> > protocol by default.
> 
> Setting `keyprotocol=foot:mok2` or `keyprotocol=foot:none` doesn't
> seem to help?

I do not see a relation betwen what you report and 'keyprotocol'.

> > and try vim v9.0.1117 in my case looks it helped bracketed paste
> > issue which existed long time. // thx bram very much. :-)
> 
> That's good to hear, I'll look out for it when it comes down the
> Alpine pipeline and I'll be sure to update this issue if the update
> helps.

The update most likely doesn't change anything.  As mentioned above, the
terminfo entries are not expected to exist yet.  But perhaps someone
added them anyway (you can put anything in terminfo entries, there is no
tool to check the values for being valid).

-- 
Living on Earth includes an annual free trip around the Sun.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dnkl** [comment]
If @AN3223 has an ncurses with the 2022-12-24 patch, where the terminfo entry names were incorrect, wouldn't that explain what we're seeing here?

**Comment by dnkl** [comment]
@AN3223 what's the output of ` infocmp -x | grep -E "BD|BE|PS|PE"`?

**Comment by dnkl** [comment]
Maybe also relevant: on vim-9.0.1046 (i.e. pre-9.0.1117), `verbose set t_BE t_BD t_PS t_PE` returns

```
  t_BE=^[[?2004h
  t_BD=^[[?2004l
E846: Key code not set: t_PS 
```
despite the terminfo having all four capabilities:

```sh
infocmp -x | grep -E "BD|BE|PS|PE"
	u9=\E[c, vpa=\E[%i%p1%dd, BD=\E[?2004l, BE=\E[?2004h,
	Ms=\E]52;%p1%s;%p2%s\E\\, PE=\E[201~, PS=\E[200~,
```

**Comment by brammool** [comment]
> Maybe also relevant: on vim-9.0.1046 (i.e. pre-9.0.1117), `verbose set
> t_BE t_BD t_PS t_PE` returns
> 
> ```
>   t_BE=^[[?2004h
>   t_BD=^[[?2004l
> E846: Key code not set: t_PS 
> ```
> despite the terminfo having all four capabilities:
> 
> ```sh
> infocmp -x | grep -E "BD|BE|PS|PE"
> 	u9=\E[c, vpa=\E[%i%p1%dd, BD=\E[?2004l, BE=\E[?2004h,
> 	Ms=\E]52;%p1%s;%p2%s\E\\, PE=\E[201~, PS=\E[200~,
> ```

Well, that was the reason to make that patch, the way the termcap
entries were fetched wasn't exactly right.  The builtin entries worked
though.

I wonder why your terminfo entry has these values, they were not really
supported until yesterday.  If you put random entries in terminfo, you
can't really predict what an application will do with them.  It's
hit-and-miss, there isn't really an official list of terminfo entries
that I know of, the Linux terminfo manpage seems to come closest.  I
also still have to see how the changes in ncurses 6.4 will be picked up
by those who make packages for distributions.

-- 
LETTERS TO THE EDITOR (The Times of London)

Dear Sir,

I am firmly opposed to the spread of microchips either to the home or
to the office.  We have more than enough of them foisted upon us in
public places.  They are a disgusting Americanism, and can only result
in the farmers being forced to grow smaller potatoes, which in turn
will cause massive unemployment in the already severely depressed
agricultural industry.

Yours faithfully,
        Capt. Quinton D'Arcy, J. P.
        Sevenoaks

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dnkl** [comment]
> I wonder why your terminfo entry has these values, they were not really supported until yesterday.

The official terminfo for foot is distributed as part of ncurses. Some distributions keep up-to-date with ncurses patches, meaning it is possible @AN3223 got the new terminfo entries through an ncurses update. This is why I asked him to check the output of `infocmp`.

(There is also an optional terminfo shipped with foot itself. I did add the new terminfo capabilities to it **today**, but before that, id did **not** have any of the bracketed-paste capabilities).

**Comment by dnkl** [comment]
> Some distributions keep up-to-date with ncurses patches, meaning it is possible @AN3223 got the new terminfo entries through an ncurses update.

Alpine linux (which is what @AN3223 is using) seems to be one of those. It's ncurses version is currently **6.4_p20221231-r0**

**Comment by dnkl** [comment]
... and it was updated from 6.3_p20221224 (i.e. the one with the faulty names) **today**.

**Comment by Shane-XB-Qian** [comment]
> > and try vim v9.0.1117 in my case looks it helped bracketed paste
> > issue which existed long time. // thx bram very much. :-)

> The update most likely doesn't change anything. 

interesting... but I suddenly find my case (https://github.com/vim/vim/issues/10632) works today morning anyway, i tried to bisect but failed, not sure why........ :smile: 

my ncurses version: 6.3-2
and no output in infocmp -x | grep -E "BD|BE|PS|PE"

**Comment by brammool** [comment]
> > I wonder why your terminfo entry has these values, they were not
> > really supported until yesterday.
> 
> The official terminfo for foot is distributed as part of ncurses. Some
> distributions keep up-to-date with ncurses patches, meaning it is
> possible @AN3223 got the new terminfo entries through an ncurses
> update. This is why I asked him to check the output of `infocmp`.
> 
> (There is also an optional terminfo shipped with foot itself. I did
> add the new terminfo capabilities to it **today**, but before that, id
> did **not** have any of the bracketed-paste capabilities).

An old Vim version does get the "BE and "BD" entries, thus if terminfo
is updated to have those entries, then the problem might happen.

The "PS" and "PE" entries were obtained before, but in the wrong way.
That is why patch 9.0.1117 is needed.  Thus updating the terminfo entry
without updating Vim would indeed cause this problem.  I had not
anticipated users updating terminfo that quickly.

Since I can't fix an older Vim, and apparently users do use an older Vim
version with the new terminfo entries, we may have to roll back these
terminfo changes.

To avoid the problem we probably need to use different terminfo entry
names instead of "BE" and "BD".  It's not nice, but I can't think of
another way right now.

-- 
ARTHUR: CHARGE!
   [The mighty ARMY charges.  Thundering noise of feet.  Clatter of coconuts.
   Shouts etc.   Suddenly there is a wail of a siren and a couple of police
   cars roar round in front of the charging ARMY and the POLICE leap out and
   stop them.  TWO POLICEMAN and the HISTORIAN'S WIFE.  Black Marias skid up
   behind them.]
HISTORIAN'S WIFE: They're the ones, I'm sure.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dnkl** [comment]
> Since I can't fix an older Vim, and apparently users do use an older Vim version with the new terminfo entries, we may have to roll back these terminfo changes.

My personal view: distributions that use bleeding edge ncurses are typically bleeding edge all around. Including vim itself. For example, Alpine updated vim to 9.0.1128 yesterday. And with that, I think the problem should be gone for @AN3223 ?

Thus, it may be best to just let the distributions catch up with vim, rather than going through a full terminfo rollback.

**Comment by brammool** [comment]
> > Since I can't fix an older Vim, and apparently users do use an older
> > Vim version with the new terminfo entries, we may have to roll back
> > these terminfo changes.
> 
> My personal view: distributions that use bleeding edge ncurses are
> typically bleeding edge all around. Including vim itself. For example,
> Alpine updated vim to 9.0.1128 yesterday. And with that, I think the
> problem should be gone for @AN3223 ?
> 
> Thus, it may be best to just let the distributions catch up with vim,
> rather than going through a full terminfo rollback.

I hope so.  Debian mentioned including the relevant Vim patch.

Another solution than a rollback would be to use different names.  But
that is a workaround (might even call it a hack) that would then remain
distributed for years.  It would also mess up the ncurses rollout.

The Vim patch is small and I don't think it conflicts with other recent
changes.  Relying on including this fix might indeed be the best
solution.

-- 
NEIL INNES PLAYED: THE FIRST SELF-DESTRUCTIVE MONK, ROBIN'S LEAST FAVORITE
                   MINSTREL, THE PAGE CRUSHED BY A RABBIT, THE OWNER OF A DUCK
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by kode54** [comment]
Arch, an allegedly bleeding edge rolling distro, is still on 9.0.1046, which it retrieves directly from the Github releases tags page. It is not applying any patches, and nobody has filed an out of date notice for it.

**Comment by TaQini** [comment]
```bash
vim --version
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Dec 11 2022 13:50:40)
Included patches: 1-1046
Compiled by Arch Linux
```

kitty 0.26.5 
```bash
:set t_BE t_BD t_PS t_PE
  t_BE=^[[?2004h
  t_BD=^[[?2004l
t_PS <PasteStart> ^[[200~
t_PE <PasteEnd>  ^[[201~
```
```bash
infocmp -x | grep -E "BD|BE|PS|PE"
	kBEG=\E[1;2E, kDC=\E[3;2~, kEND=\E[1;2F, kHOM=\E[1;2H,
	Smulx=\E[4:%p1%dm, Sync=\EP=%p1%ds\E\\, kBEG3=\E[1;3E,
	kBEG4=\E[1;4E, kBEG5=\E[1;5E, kBEG6=\E[1;6E,
	kBEG7=\E[1;7E, kDC3=\E[3;3~, kDC4=\E[3;4~, kDC5=\E[3;5~,
```
foot 1.13.1 
```bash
:set t_BE t_BD t_PS t_PE
  t_BE=^[[?2004h
  t_BD=^[[?2004l
E846: Key code not set: t_PS 
```
```bash
infocmp -x | grep -E "BD|BE|PS|PE"
	u9=\E[c, vpa=\E[%i%p1%dd, BD=\E[?2004l, BE=\E[?2004h,
	Ms=\E]52;%p1%s;%p2%s\E\\, PE=\E[201~, PS=\E[200~,
```

**Comment by TaQini** [comment]
> ```shell
> vim --version
> VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Dec 11 2022 13:50:40)
> Included patches: 1-1046
> Compiled by Arch Linux
> ```
> 
> kitty 0.26.5
> 
> ```shell
> :set t_BE t_BD t_PS t_PE
>   t_BE=^[[?2004h
>   t_BD=^[[?2004l
> t_PS <PasteStart> ^[[200~
> t_PE <PasteEnd>  ^[[201~
> ```
> 
> ```shell
> infocmp -x | grep -E "BD|BE|PS|PE"
> 	kBEG=\E[1;2E, kDC=\E[3;2~, kEND=\E[1;2F, kHOM=\E[1;2H,
> 	Smulx=\E[4:%p1%dm, Sync=\EP=%p1%ds\E\\, kBEG3=\E[1;3E,
> 	kBEG4=\E[1;4E, kBEG5=\E[1;5E, kBEG6=\E[1;6E,
> 	kBEG7=\E[1;7E, kDC3=\E[3;3~, kDC4=\E[3;4~, kDC5=\E[3;5~,
> ```
> 
> foot 1.13.1
> 
> ```shell
> :set t_BE t_BD t_PS t_PE
>   t_BE=^[[?2004h
>   t_BD=^[[?2004l
> E846: Key code not set: t_PS 
> ```
> 
> ```shell
> infocmp -x | grep -E "BD|BE|PS|PE"
> 	u9=\E[c, vpa=\E[%i%p1%dd, BD=\E[?2004l, BE=\E[?2004h,
> 	Ms=\E]52;%p1%s;%p2%s\E\\, PE=\E[201~, PS=\E[200~,
> ```



> ```shell
> vim --version
> VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Dec 11 2022 13:50:40)
> Included patches: 1-1046
> Compiled by Arch Linux
> ```
> 
> kitty 0.26.5
> 
> ```shell
> :set t_BE t_BD t_PS t_PE
>   t_BE=^[[?2004h
>   t_BD=^[[?2004l
> t_PS <PasteStart> ^[[200~
> t_PE <PasteEnd>  ^[[201~
> ```
> 
> ```shell
> infocmp -x | grep -E "BD|BE|PS|PE"
> 	kBEG=\E[1;2E, kDC=\E[3;2~, kEND=\E[1;2F, kHOM=\E[1;2H,
> 	Smulx=\E[4:%p1%dm, Sync=\EP=%p1%ds\E\\, kBEG3=\E[1;3E,
> 	kBEG4=\E[1;4E, kBEG5=\E[1;5E, kBEG6=\E[1;6E,
> 	kBEG7=\E[1;7E, kDC3=\E[3;3~, kDC4=\E[3;4~, kDC5=\E[3;5~,
> ```
> 
> foot 1.13.1
> 
> ```shell
> :set t_BE t_BD t_PS t_PE
>   t_BE=^[[?2004h
>   t_BD=^[[?2004l
> E846: Key code not set: t_PS 
> ```
> 
> ```shell
> infocmp -x | grep -E "BD|BE|PS|PE"
> 	u9=\E[c, vpa=\E[%i%p1%dd, BD=\E[?2004l, BE=\E[?2004h,
> 	Ms=\E]52;%p1%s;%p2%s\E\\, PE=\E[201~, PS=\E[200~,
> ```

I tried the latest vim (version 9.0.1153) which has fixed this bug

foot
```
  t_BE=^[[?2004h
  t_BD=^[[?2004l
t_PS <PasteStart> ^[[200~
t_PE <PasteEnd>  ^[[201~
```

**Comment by brammool** [comment]
> ```bash
> vim --version
> VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Dec 11 2022 13:50:40)
> Included patches: 1-1046
> Compiled by Arch Linux
> ```
> 
> kitty 0.26.5 
> ```bash
> :set t_BE t_BD t_PS t_PE
>   t_BE=^[[?2004h
>   t_BD=^[[?2004l
> t_PS <PasteStart> ^[[200~
> t_PE <PasteEnd>  ^[[201~
> ```
> ```bash
> infocmp -x | grep -E "BD|BE|PS|PE"
> 	kBEG=\E[1;2E, kDC=\E[3;2~, kEND=\E[1;2F, kHOM=\E[1;2H,
> 	Smulx=\E[4:%p1%dm, Sync=\EP=%p1%ds\E\\, kBEG3=\E[1;3E,
> 	kBEG4=\E[1;4E, kBEG5=\E[1;5E, kBEG6=\E[1;6E,
> 	kBEG7=\E[1;7E, kDC3=\E[3;3~, kDC4=\E[3;4~, kDC5=\E[3;5~,
> ```

I guess $TERM here is "xterm-kitty".  Since this Vim is older it picks
up the builtin xterm termcap, which defines the bracketed paste entries.
The terminfo doesn't matter.

> foot 1.13.1 
> ```bash
> :set t_BE t_BD t_PS t_PE
>   t_BE=^[[?2004h
>   t_BD=^[[?2004l
> E846: Key code not set: t_PS 
> ```
> ```bash
> infocmp -x | grep -E "BD|BE|PS|PE"
> 	u9=\E[c, vpa=\E[%i%p1%dd, BD=\E[?2004l, BE=\E[?2004h,
> 	Ms=\E]52;%p1%s;%p2%s\E\\, PE=\E[201~, PS=\E[200~,
> ```

I wonder who put these bracketed-paste entries into the foot terminfo
entry?  Does this system have ncurses 6.4 perhaps?

You need patch 9.0.1117 to make this work.

That the terminfo entries for bracketed paste don't work is a very old
problem that nobody noticed until terminfo was updated (with ncurses
6.4).  It was fixed quickly, but an older Vim with new terminfo entries
won't work.  There doesn't appear to be another solution than making
sure Vim has that patch.


-- 
LARGE MAN:   Who's that then?
CART DRIVER: (Grudgingly) I dunno, Must be a king.
LARGE MAN:   Why?
CART DRIVER: He hasn't got shit all over him.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by kode54** [comment]
Just thought I'd add, Arch doesn't have a terminfo built in for foot. You have to install a separate `foot-terminfo` package, which is version matched with the `foot` package.

**Comment by dnkl** [comment]
This isn't entirely true. The default terminfo used by the foot package on Arch is provided by ncurses.

The foot-terminfo package is an optional dependency, providing an alternative terminfo (that defines more capabilities than the one from ncurses). The user has to explicitly configure foot to make use of the alternative terminfo.

**Comment by sdondley** [comment]
I'm having the same issue, running debian bookworm on a docker container. See https://www.reddit.com/r/vim/comments/1063k5p/pasting_takes_me_out_of_insert_mode/ for more details.

**Comment by sdondley** [comment]
OK, so it appears changing $TERM to something more generic fixes the issue. If it's set to `xterm` for example, the problem goes away.

**Comment by AN3223** [comment]
> > Since I can't fix an older Vim, and apparently users do use an older Vim version with the new terminfo entries, we may have to roll back these terminfo changes.
> 
> My personal view: distributions that use bleeding edge ncurses are typically bleeding edge all around. Including vim itself. For example, Alpine updated vim to 9.0.1128 yesterday. And with that, I think the problem should be gone for @AN3223 ?
> 
> Thus, it may be best to just let the distributions catch up with vim, rather than going through a full terminfo rollback.

Yes the problem is gone now after an update. Sorry for the late response, the thread was moving a little fast (not a complaint!) and I had COVID, lol.

I guess I will close this issue now? :)

**Comment by brammool** [comment]
> > > Since I can't fix an older Vim, and apparently users do use an
> > > older Vim version with the new terminfo entries, we may have to
> > > roll back these terminfo changes.
> > 
> > My personal view: distributions that use bleeding edge ncurses are
> > typically bleeding edge all around. Including vim itself. For
> > example, Alpine updated vim to 9.0.1128 yesterday. And with that, I
> > think the problem should be gone for @AN3223 ?
> > 
> > Thus, it may be best to just let the distributions catch up with
> > vim, rather than going through a full terminfo rollback.
> 
> Yes the problem is gone now after an update.

Glad to hear that.  I haven't heard ideas for another solution, thus
we'll leave it at this.

Note that I plan to do a few similar changes to support terminals
automatically, without the need for users to tune their setup.  We
learned from this mistake, the "RV" entry was heading in the same
direction.  We can fix that before it gets released.

So, keep checking new versions for working properly.  Feedback from
users using the latest version of everything is very much appreciated.

> Sorry for the late response, the thread was moving a little fast (not
> a complaint!) and I had COVID, lol.

I hope you recover 100%!

-- 
"You're fired." (1980)
"You're laid off." (1985)
"You're downsized." (1990)
"You're rightsized." (1992)
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
