### ISSUE TITLE
vim9script :unlet can't be used to remove script local variable

### ISSUE THREAD

**Issue by habamax** [vim/vim#11775]
The help for `:unlet` tells that it can remove script-local variables:

```
:unl[et][!] {name} ...			*:unlet* *:unl* *E108* *E795* *E1081*
			Remove the internal variable {name}.  
...
...
<			This is especially useful to clean up used global
			variables and script-local variables (these are not
			deleted when the script ends).  Function-local
			variables are automatically deleted when the function
			ends.

```

But apparently it can't do it in vim9script:
![image](https://user-images.githubusercontent.com/234774/210289875-9173914f-bc20-4d8e-b3ad-5c4625f80448.png)

And this is mentioned somewhere deep in `:h vim9`:
![image](https://user-images.githubusercontent.com/234774/210289921-5dc5c497-8df7-468b-be02-cc9d3405c34f.png)

It probably would be nice to explicitly write in `:h :unlet` that it doesn't work for a script local variables declared with `:var`.

**Comment by brammool** [comment]
I'll add a remark that variables in a function and a Vim9 script cannot be used with ":unlet".
