### ISSUE TITLE
statusline is glitched with non-printable character and highlight

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#11772]
### Steps to reproduce

1. Run `vim --clean`
2. Source the following file:
```vim
set laststatus=2
let &statusline = "\x08\u258e%#TabLine#"
redraw!
```
3. statusline is glitched:
![glitch](https://user-images.githubusercontent.com/35768171/210192741-1c886f09-5248-4316-ae5c-71ad3daca8da.png)

Also, if the Unicode character `\u258e` is changed to multiple ASCII characters:
```vim
set laststatus=2
let &statusline = "\x08abc%#TabLine#"
redraw!
```

Highlight is off by one:
![off](https://user-images.githubusercontent.com/35768171/210192843-430837f2-f01d-4ac2-831a-15665e28a26a.png)

### Expected behaviour

statusline looks normal, for example, changing the `\x08` to literal `^H` above results in
![normal](https://user-images.githubusercontent.com/35768171/210192770-a7081712-4c7e-46bf-a805-73e3015e57b7.png)

### Version of Vim

9.0.1046

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

**Comment by zeertzjq** [comment]
`start` in `hltab` and `tabtab` should need to be adjusted after this `transstr()`:
```c
    // Make all characters printable.
    p = transstr(buf);
    if (p != NULL)
    {
	vim_strncpy(buf, p, sizeof(buf) - 1);
	vim_free(p);
    }
```
Not sure how to do this.

**Comment by brammool** [comment]
> `start` in `hltab` and `tabtab` should need to be adjusted after this
> `transstr()`:
> ```c
>     // Make all characters printable.
>     p = transstr(buf);
>     if (p != NULL)
>     {
> 	vim_strncpy(buf, p, sizeof(buf) - 1);
> 	vim_free(p);
>     }
> ```
> Not sure how to do this.

I do not think this is possible.  The call to transstr() is only there
just in case there is something wrong and unprintable characters would
mess up the screen.

The result of 'statusline' should not contain unprintable characters.
When it does, Vim won't crash but you won't get the status line you
wanted either.

I do not see a good reason why 'statusline' would produce unprintable
characters.  Also, the conversion will change the length, thus any item
in 'statusline' depending on the length would get confused.  The
highlighting example is just one of them.

So, unless you can give a good reason why 'statusline' should contain
unprintable characters, I don't think there is anything to change.

-- 
A disclaimer for the disclaimer:
"and before I get a huge amount of complaints , I have no control over the
disclaimer at the end of this mail :-)" (Timothy Aldrich)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by zeertzjq** [comment]
There isn't really a good reason
