### ISSUE TITLE
Sporadic Test_range test failure

### ISSUE THREAD

**Issue by jamessan** [vim/vim#11771]
### Steps to reproduce

Run test suite.

I can't reliably reproduce it, so haven't been able to add debug info.  This crops up periodically in the Debian builds.

### Expected behaviour

Tests all pass

### Version of Vim

9.0.1000

### Environment

Debian sid

### Logs and stack traces

```shell
Found errors in Test_range():
	Caught exception in Test_range(): Vim(call):E121: Undefined variable: result @ command line..script /builds/vim-team/vim/debian/output/source_dir/src/vim-motif/testdir/runtest.vim[515]..function RunTheTest[52]..Test_range, line 101
```

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> Run test suite.
> 
> I can't reliably reproduce it, so haven't been able to add debug info.  This crops up periodically in the Debian builds.
> 
> ### Expected behaviour
> 
> Tests all pass
> 
> ### Version of Vim
> 
> 9.0.1000
> 
> ### Environment
> 
> Debian sid
> 
> ### Logs and stack traces
> 
> ```shell
> Found errors in Test_range():
> 	Caught exception in Test_range(): Vim(call):E121: Undefined variable: result @ command line..script /builds/vim-team/vim/debian/output/source_dir/src/vim-motif/testdir/runtest.vim[515]..function RunTheTest[52]..Test_range, line 101
> ```

Strange.  Does it always happen with this same error message?

Perhaps there is some typeahead that results in inputlist() failing.
Let's use getchar(0) to avoid that.
And move it to a separate test function, perhaps we get more information
then.

-- 
TERRY GILLIAM PLAYED: PATSY (ARTHUR'S TRUSTY STEED), THE GREEN KNIGHT
                      SOOTHSAYER, BRIDGEKEEPER, SIR GAWAIN (THE FIRST TO BE
                      KILLED BY THE RABBIT)
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by jamessan** [comment]
I don't recall seeing this test failure for awhile, so I'll go ahead and close this.
