### ISSUE TITLE
Question about keyprotocol option

### ISSUE THREAD

**Issue by Tachi107** [vim/vim#11781]
### Steps to reproduce

The `keyprotocol` default value states that if `term` contains `foot`, `kitty` or `wezterm`, then the kitty keyboard protocol is enabled and `t_TE` and `t_TI` are updated accordingly.

Still, if I run `:set t_TI?` on foot, the option seems  to be empty, while on kitty it contains the expected value (`^[[=1;1u`); the same applies to `t_TE`.

### Expected behaviour

`t_TI` and `t_TE` should be consistent between foot and kitty.

### Version of Vim

Debian vim-gtk3 9.0.1000-3 with patches 1-1000, 1087, 1117-1118, 1129

### Environment

Operating system: Debian Testing/Unstable
$TERM: foot, using foot 1.13.1's terminfo files
ncurses version: 6.4

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> The `keyprotocol` default value states that if `term` contains `foot`,
> `kitty` or `wezterm`, then the kitty keyboard protocol is enabled and
> `t_TE` and `t_TI` are updated accordingly.
> 
> Still, if I run `:set t_TI?` on foot, the option seems  to be empty,
> while on kitty it contains the expected value (`^[[=1;1u`); the same
> applies to `t_TE`.
> 
> ### Expected behaviour
> 
> `t_TI` and `t_TE` should be consistent between foot and kitty.
> 
> ### Version of Vim
> 
> Debian vim-gtk3 9.0.1000-3 with patches 1-1000, 1087, 1117-1118, 1129
> 
> ### Environment
> 
> Operating system: Debian Testing/Unstable
> $TERM: foot, using foot 1.13.1's terminfo files
> ncurses version: 6.4

I can't run foot on my system.  If I just set $TERM to foot then it
works as expected.

Are you sure nothing interferes?  You did start Vim with "vim --clean"?
When Vim runs you can see the value of 'keyprotocol' is the default one?

I can't think of a reason why this would not work.


-- 
It might look like I'm doing nothing, but at the cellular level
I'm really quite busy.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Tachi107** [comment]
Il giorno mer 4 gen 2023 alle 05:17:04 -08:00:00, Bram Moolenaar 
***@***.***> ha scritto:
> I can't run foot on my system. If I just set $TERM to foot then it
>  works as expected.
> 

Setting TERM=foot in other terminal emulators does still reproduce the 
bug for me. What terminal emulator are you using?

>  Are you sure nothing interferes? You did start Vim with "vim 
> --clean"?
>  When Vim runs you can see the value of 'keyprotocol' is the default 
> one?
> 

It doesn't work with `vim --clean` either. Here's what I can do to 
reliably reproduce this:

    $ foot # reproducible if using kitty or xterm too
    $ TERM=foot vim --clean
    :set term?
    term=foot
    :set keyprotocol?
    keyprotocol=kitty:kitty,foot:kitty,wezterm:kitty,xterm:mok2
    :set t_TE?
    t_TE=

Forcing TERM=xterm-kitty in foot results in the expected t_TE value, 
but forcing TERM=foot in kitty and xterm results in an empty t_TE.

Oddly enough, setting TERM=xterm-foot, which does not have a 
corresponding terminfo file, results in the correct t_TE value (but 
colors and pretty much everything else is obviously broken). This seems 
to work only for TERM=xterm-foot specifically, and not with other 
random TERM values containing the string "foot".

>  I can't think of a reason why this would not work.

Yeah, this is really odd indeed. Maybe it is related to the terminfo 
files?

**Comment by brammool** [comment]
> I'm seeing very similar behaviour with wezterm.
> 
> VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jan 01 1970 00:00:01)
> Included patches: 1-1073
> 
> Setting TERM to wezterm results in no keyprotocol being used (unexpected):
> 
> TERM=wezterm vim --clean
> :set term?
> term=wezterm
> :set keyprotocol?
> keyprotocol=kitty:kitty,foot:kitty,wezterm:kitty,xterm:mok2
> :set t_TE?
> t_TE=

I cannot reproduce this, I don't have wezterm.  I tried with "foot" and
it works as expected.  I cannot guess why wezterm would be different.

> Setting TERM to xterm-wezterm results in the kitty keyprotocol being
> used (expected, but shouldn't E558 be raised since there is no
> terminfo for that?):

When $TERM starts with "xterm" the builtin xterm termap is used.  This
might be going away though, there are too many side effects.

> TERM=xterm-wezterm vim --clean
> :set term?
> term=xterm-wezterm
> :set keyprotocol?
> keyprotocol=kitty:kitty,foot:kitty,wezterm:kitty,xterm:mok2
> :set t_TE?
> t_TE=^[[>4;m^[[=0;1u
> 
> Just to double check: setting TERM to xterm results in mok2 being used (expected):
> 
> TERM=xterm vim --clean
> :set term?
> term=xterm
> :set keyprotocol?
> keyprotocol=kitty:kitty,foot:kitty,wezterm:kitty,xterm:mok2
> :set t_TE?
> t_TE=^[[>4;m

Perhaps you can use a debugger to find out what happens with "wezterm"?

-- 
Don't Panic!
		-- The Hitchhiker's Guide to the Galaxy

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by promisedlandt** [comment]
When I built the master, it worked for me as well. Using git bisect, I found that commit afa3f1cc7258d34c32a299a3cc6aece89f67fb47 (patch 1080) contains the fix.
This patch is not yet in the version I'm using, and also not in the version string from the orignal bug report.

I'm bad at reading C, but to me it looks like prior to that commit, the keyprotocol option was only applied when using the built-in termcap, which doesn't include foot or wezterm.
When you say it worked for you with "foot", is it possible you were trying with a version > 1080?

Either way, for me this is solved, just need to wait a bit for the package maintainers to catch up :)

**Comment by Tachi107** [comment]
Thanks, @promisedlandt! I can confirm that applying patch 1080 (and 1073) fixed the issue for me. I've submitted a request to the Debian Vim maintainers to apply that patch on top of the current vim 9 package (<https://bugs.debian.org/1029049>)
