### ISSUE TITLE
 Execution of autocmd with `startinsert` while pattern shouldn't trigger it.

### ISSUE THREAD

**Issue by jokesper** [vim/vim#11789]
### Steps to reproduce

```vim
autocmd WinEnter Xa startinsert
edit Xa
new
```

### Expected behaviour

The new window should not be in insert mode as it does not match the pattern of the event.

### Version of Vim

9.0.1046

### Environment

Arch Linux
kitty 0.26.5
xterm-kitty

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> ```vim
> autocmd WinEnter Xa startinsert
> edit Xa
> new
> ```
> 
> ### Expected behaviour
> 
> The new window should not be in insert mode as it does not match the
> pattern of the event.

This is unexpected, but it does match.  The help for WinEnter mentions:

				Note: For split and tabpage commands the
				WinEnter event is triggered after the split
				or tab command but before the file is loaded.

The "new" command can be seen as made up of two commands: "split" and
"edit empty buffer".  The "split" command creates a new window and
enters it, still editing "Xa", thus it triggers the WinEnter event.

You can probably use a timer or something else to only start Insert mode
when you want to.


-- 
ARTHUR: What are you going to do. bleed on me?
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by jkeDev** [comment]
Oh I see. Thank you for the clarification

**Comment by jkeDev** [comment]
If someone runs into this problem in the future I fixed it by having my autocmds set up like this:
```vim
au WinEnter Xa startinsert
au BufLeave * stopinsert
```
it still doesn't go into insert when opening `Xa` but that can be fixed with
```vim
au BufEnter Xa startinsert
```
