### ISSUE TITLE
Pasting inside mapping doesn't work with trying to move cursor off the edge

### ISSUE THREAD

**Issue by echasnovski** [vim/vim#11786]
### Steps to reproduce

1. Create init file (called here 'init_paste-edge.vim') with the following contents:
```vim
nnoremap H xhP
nnoremap J xjP
nnoremap K xkP
nnoremap L xlP
```
2. Open vim with the following command `vim -u init_paste-edge.vim -- init_paste-edge.vim`.
3. Put cursor on `J`.
4. Try moving it with `H`/`J`/`K`/`L` continuously. It works up until the respective edge (one before right edge for `L`, which is expected) and then character disappears. This is not the same as doing those steps manually which is character just staying in place.

Notes:
- It also doesn't work with `p` instead of `P`. Does work if `L` is replaced with `xp`, though.
- It also doesn't work for visual mode mappings. Replace `nnoremap` with `xnoremap` and try moving `J` with `v` + `HJKL`.
- It partially works if `hjkl` movements in mappings are prepended with `count > 1`. Replace them with `100` + `hjkl` and try moving `J` with `HJKL`. It works only in first step for `HL` and doesn't work later; doesn't work for `JK` but in different manner (because with manual execution cursor doesn't move).

### Expected behaviour

Result of applying mapping is always the same as applying its right hand side manually.

### Version of Vim

9.0.1046

### Environment

OS:  EndeavourOS Linux x86_64, 6.1.1-arch1-1
Terminal: st-0.9
`$TERM`: st-256color
Shell: zsh 5.9

**Comment by zeertzjq** [comment]
```
							*map-error*
Note that when an error is encountered (that causes an error message or beep)
the rest of the mapping is not executed.  This is Vi-compatible.
```

**Comment by echasnovski** [comment]
> ```
> 							*map-error*
> Note that when an error is encountered (that causes an error message or beep)
> the rest of the mapping is not executed.  This is Vi-compatible.
> ```

Could you help me understand why is there an error if replicating same steps manually works?

**Comment by zeertzjq** [comment]
If you replicate the same steps manually with `belloff=` you will get a beep.

**Comment by echasnovski** [comment]
> If you replicate the same steps manually with `belloff=` you will get a beep.

I can replicate with `visualbell`.

Does it mean that moving with `hjkl` past the edge is considered an error? Is it reasonable to ask to not treat it that way (at least inside mappings)?

Or maybe stop mapping execution only on actual errors and not beeps?

**Comment by chrisbra** [comment]
The bell is just a indication, that tells you whether an error occured or not. Disabling bellstyle (using visualbell or bell=off) does not make the error go away, rather it prevents Vim to beep at you. 

This is working as intended. You can use `expression-mappings` to check the edge-case and have you mapping return something elase. Please ask for useage question on how to use expression mappings on vi.stackexchange.com or use the vim-use mailinglist.

Thanks.

**Comment by echasnovski** [comment]
> The bell is just a indication, that tells you whether an error occured or not. Disabling bellstyle (using visualbell or bell=off) does not make the error go away, rather it prevents Vim to beep at you.

It was more about slightly ambiguous wording in `*map-error*`: `Note that when an error is encountered (that causes an error message or beep) the rest of the mapping is not executed.`. There is non of these in case of `hjkl` on edge but mapping is still not executed.

**Comment by echasnovski** [comment]
> If you are on the first character in the first line, the `h` will cause an error/abort (because you cannot move to the left of the screen) and therefore the mapping aborts. Try to run you rhs of the mapping in a `vim --clean` and you should clearly hear the beep or see the visual bell. This means the mapping does not succeed.

I know and understand that, thanks. My point now is only about wording in `*map-error*`: it defines conditions for mapping execution stop as "error ... **that causes an error message or beep**". This implies that if there is no error message and no beep, mapping execution should not stop. Yes, this is nit-picking, but I took these words literally during discussions in this issue.

> `feedkeys()` with `t` flag may also be used to achieved the behavior as typed.

`normal! h` seems to work also.
