### ISSUE TITLE
Very strange cursor movement in quickfix window. (vim 8.0.41 linux terminal)

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#1178]
version: 8.0.41
os: debian8 x64 terminal

action:
1. start vim without any plugin
2. `set nocompatible`
3. copen open a quickfix window
4. cexpr add something to it
5. use normal 2G to move to the second row in quickfix window
6. but it go to the 5th row.

it I comment "set nocompatible" everything works fine, it can exactly jump to line #2.
but if I invoke "set nocompatible" it will jump to line #5.

```
vim -u NONE test.vim
:so test.vim
```

source of `test.vim`:

``` VimL
set nocompatible
copen 4
cexpr "1"
caddexpr "2"
caddexpr "3"
caddexpr "4"
caddexpr "5"
set number
normal gg
normal 2G
caddexpr "why cursor in qf moved to line 5 after 2G ?"
```

expect:
cursor move to line #2

result:
cursor move to line #5

**Comment by chrisbra** [comment]
Cannot reproduce. Can you try with `--noplugin` Also make sure to use `normal!` with bang attribute.

**Comment by skywind3000** [comment]
Sure, it can be reproduce in all my three debian 8 vps in linode. even if I do what you tell me:

``` VimL
vim --noplugin -u NONE test.vim
```

test.vim:

``` VimL
set nocompatible
copen 4
cexpr "1"
caddexpr "2"
caddexpr "3"
caddexpr "4"
caddexpr "5"
set number
normal! gg
normal! 2G
caddexpr "why cursor in qf moved to line 5 after 2G ?"
```

and I have confirmed there is no plugin loaded by `:scriptnames`

**Comment by skywind3000** [comment]
sorry, I figure out my self, too many spaces after `normal! 2G` which I haven't noticed.

and that's strange, why not trim tailing spaces in vim ?

``` VimL
":normal h"
":normal h  "
```

it seems they are completely two different commands, too dangerous to write `:normal` command,
easy to get wrong.

**Comment by skywind3000** [comment]
sorry for wasting your time.
