### ISSUE TITLE
Document sequences of autocommand events

### ISSUE THREAD

**Issue by ericbn** [vim/vim#1180]
This was tested with `vim -N -u NONE` under vim 8.0.41.

I wanted to create an autocmd that would lcd to the current file when opening a new tab, so each tab (more precisely every window on a new tab) would have its (local) working directory as the first file opened in each tab. I was thinking of

```
autocmd TabNew * lcd %:p:h
```

but % is being expanded to the "current file" before the tab is opened, not after.

I checked with

```
:autocmd TabNew * echo expand('%')
:set verbose=9
:tabnew ~/.vimrc
```

Console shows that the output of expand('%') is not "~/.vimrc", but the file in the previous tab (or maybe better said, the current file before I issued the :tabnew command).

**Comment by ZyX-I** [comment]
Help says that this event is triggered

> When a tab page was created. A WinEnter event will have been triggered first, TabEnter follows.

which means that you first receive TabNew and only then tab is entered. Though I would expect current file to change at WinEnter, WinEnter help explicitly contains

> If the window is for another buffer, Vim executes the BufEnter autocommands after the WinEnter autocommands.
> 
> Note: When using ":split fname" the WinEnter event is triggered after the split but before the file "fname" is loaded.

and TabEnter help says

> After triggering the WinEnter and before triggering the BufEnter event.

so this is not a bug: when TabNew is triggered new buffer was not yet entered.

**Comment by ericbn** [comment]
Got it. So the sequence is WinEnter > TabNew > TabEnter > BufEnter > BufWinEnter. And "%" will only reflect the "new" current filename starting at BufEnter.

**Comment by vim-ml** [comment]
On 2016-10-19, Eric Nielsen wrote:

> Got it. So the sequence is WinEnter > TabNew > TabEnter > BufEnter >
> BufWinEnter. And "%" will only reflect the "new" current filename starting at
> BufEnter.

"We" ought to document this and the sequences of other events.
Where would be a good place to put that?  In a new section, e.g.
autocmd-sequences, in autocmd.txt?  Maybe something like this?
1. Sequences of autocommand events             _autocmd-sequences_

Most Vim commands initiate a sequence of events, some of which cause
autocommand events (|autocmd-events|) to be generated as they occur.
Which autocommand events are generated in response to Vim events and
the sequence in which they occur can be confusing, yet understanding
them can be critical to getting expected results from using them.
Here are some Vim events and the resulting sequence of autocommand
events.
-  :tabnew myfile
  1.  WinEnter
     % is name of buffer in which :tabnew was executed.
  2.  TabNew
  3.  TabEnter
  4.  BufEnter
     % is name of new buffer, "myfile".
  5.  BufWinEnter

Regards,
Gary

**Comment by ericbn** [comment]
@chrisbra, can we reopen this? Or should we create another issue?

**Comment by chrisbra** [comment]
I cleaned it the documentation up a bit and submitted it separatley to vim-dev.
