### ISSUE TITLE
9.0.1193 causes segfault

### ISSUE THREAD

**Issue by chdiza** [vim/vim#11817]
### Steps to reproduce

Patch 9.0.1193 produces a segfault.   Here is what triggers it for me.

I am editing a .html file like usual, and then I do `:tabe foo.css`.  This causes one of my filetype autocommands to source some mappings for css files from mycssmaps.vim.  (The autocmd does `:runtime mycssmaps.vim`.)  And then vim crashes with "Caught deadly signal SEGV".

This line in mycssmaps.vim is where the segfault gets triggered:
```
imap <buffer> <C-c>r <space>{<CR>}<Esc>O<space><space>
```

### Expected behaviour

I expect this to not happen, since it has never happened until 9.0.1193 arrived.

I can reproduce it using `vim --clean`, if I then manually do `:source mycssmaps.vim`.

### Version of Vim

9.0.1193

### Environment

Ubuntu 20.04
Terminal = kitty 0.26.5

**Comment by chdiza** [comment]
This is kitty-specific, which is what let me to suspect 9.0.1193 in the first place.

**Comment by brammool** [comment]
> This is kitty-specific, which is what let me to suspect 9.0.1193 in
> the first place.

I can indeed get it to crash with the mapping only when using Kitty.
I managed to have it crash in valgrind, I can see the mistake and I'll
make a fix.

-- 
The Feynman problem solving Algorithm:
	1) Write down the problem
	2) Think real hard
	3) Write down the answer

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chdiza** [comment]
Great, thanks!
