### ISSUE TITLE
[vim9] Iterating over the values of a dictionary of objects inside a function raises E715: Dictionary required 

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#11822]
### Steps to reproduce

Source this script:

```vim
vim9script

class Foo
  def Add()
  enddef
endclass

def Process(FooDict: dict<any>)
  for foo in values(FooDict)
    foo.Add()
  endfor
enddef

var D = {'x': Foo.new()}

Process(D)
```

### Expected behaviour

The script should compile and run without errors.

### Version of Vim

9.0.1200

### Environment

macOS 13.1
Apple Terminal
xterm-256color
ZSH 5.8.1

**Comment by lifepillar** [comment]
The error is reported at the line: `foo.Add()`.

**Comment by lifepillar** [comment]
Explicit typing does not help, but it reveals that the problem *may* be that `values()` loses some typing info:

```vim
vim9script

class Foo
  def Add()
  enddef
endclass

def Process(FooDict: dict<Foo>)
  const fooList: list<Foo> = values(FooDict)  # <== E1012: Type mismatch; expected list<object<Foo>> but got list<any>
  for foo in fooList
    foo.Add()
  endfor
enddef

var D: dict<Foo> = {'x': Foo.new()}

Process(D)
```

**Comment by brammool** [comment]
The original problem is not easy to make work: At runtime we get "any" and need to check if it's an object or a dictionary.

The problem with values() not returning a better type can be fixed, I'll make a patch for that.

**Comment by lifepillar** [comment]
This is a potential workaround for the original problem:

```vim
vim9script

class Foo
  def Add()
  enddef
endclass

def AsFoo(obj: Foo): Foo
  return obj
enddef

def Process(FooDict: dict<any>)
  for foo in values(FooDict)
    AsFoo(foo).Add()
  endfor
enddef

var D = {'x': Foo.new()}

Process(D)
```

`AsFoo()` raises if its argument is not a `Foo`, so by catching such exception one may dynamically distinguish an object from a dictionary.

**Comment by lifepillar** [comment]
Or, possibly even better than raising an exception, one may just check that the type is `v:t_object` and “cast” the object with `AsFoo()`:

```vim
def AsFoo(obj: Foo): Foo
  return obj
enddef

def Process(FooDict: dict<any>)
  for foo in values(FooDict)
    if type(foo) == v:t_object
      AsFoo(foo).Add()
    else
      echo foo['a']
    endif
  endfor
enddef

var D = {'x': Foo.new(), 'y': {'a': 42}}

Process(D)
```

This workaround works for my use case. Feel free to close this issue.

**Comment by errael** [comment]
Is there a (or planned) `instanceof` operator? (as in java)
