### ISSUE TITLE
[vim9] Member order confusion during initialization of class implementing interface

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#11825]
### Steps to reproduce

Source this script:

```vim
vim9script

interface Result
  this.label: string
  this.errpos: number
endinterface

class Failure implements Result
  this.errpos: number = 0
  this.label: string = ''
endclass

def Foo(): Result
  return Failure.new()
enddef

def Test()
  const result = Foo()
  assert_true(result.label == '')
enddef

Test()
```

This results in `E1072: Cannot compare number with string`, because the member declared inside `Failure` are not in the same order as in `Result`. In fact, exchanging the order of the two members fixes the error.

### Expected behaviour

I don't think that the order in which the member attributes are declared should matter. Or, if it does, a compile error signaling the problem would be better.

### Version of Vim

Vim 9.0.1202

### Environment

macOS 13.1
Apple Terminal
xterm-256color
ZSH 5.8.1

**Comment by brammool** [comment]
Interesting problem.  Changing the order will make this example work, but if you insert another object member in between the two it will fail again.  This requires rethinking how object members on an interface are being accessed.
