### ISSUE TITLE
Can we allow member variables to be public by default?

### ISSUE THREAD

**Issue by zewpo** [vim/vim#11827]
https://github.com/vim/vim/blob/ae3205aa55741152b0143dbd7d637b35f576793e/runtime/doc/vim9class.txt#L115-L139

In my opinion - the developer ought to know if setting a member variable has side-effects, so it's their responsibility to make it private.  I think that most of the time, you just want the convenience of setting the variable directly - without writing a setter function for it - or needing to remember to make it public.   So, if the default visibility is public, (explicitly writing "public" becomes optional) then that makes it easier most of the time - and I think that any potential risk that brings is something that the developer ought to be aware of.

**Comment by vim-ml** [comment]
On 23/01/15 2:56 PM, Christopher Plewright (Vim Github Repository) wrote:
> the developer ought to know if setting a member variable has 
> side-effects, so it's their responsibility to make it private. I think 
> that most of the time, you just want the convenience of setting the 
> variable directly - without writing a setter function for it - or 
> needing to remember to make it public.

Unless there's a clear reason, I'll usually be conservative and limit 
the scope; most of the time I don't want to set member variables from 
someplace else. If the need arises for public access it's trivial to 
make public. This is particularly good/convenient for code that gets 
looked at after some time; if there's an issue, it forces me to revisit 
what access rules I want.

-ernie

**Comment by zewpo** [comment]
@vim-ml    Yes, there are some good reasons to default private, I'm aware its preferred by a lot of traditional OO programming languages - and being conservative/safe is good.

Actually, my last suggestion on the vim_dev mailing list would make this a mute point.  There would be no ambiguity about what is the default, because it would enforce all member variables to be explicitly public or private, simply by the prefix "." or "_", which has other advantages too - like removing the requirement of the "this." prefix.

ref:  https://groups.google.com/d/msgid/vim_dev/3f966524-130c-4a81-8a68-fc531883cca5n%40googlegroups.com

**Comment by Shane-XB-Qian** [comment]
the default perhaps should be `protect`, neither `public` nor `private`, just available in class and its sub. IMO.
and so called `this` perhaps actually a bit confused..

// anyway, i felt vim script became a bit complex more than a `script`, do we really need class/abstract/extend/interface...?!

**Comment by brammool** [comment]
Also see the "Class implementation" thread in the vim-dev maillist.
Hopefully this link works: https://groups.google.com/g/vim_dev/c/yYpFNUHdRho

**Comment by Shane-XB-Qian** [comment]
@zewpo please check https://github.com/vim/vim/pull/12932 if you still interesting on this, and this ticket can be closed when/if that one had final version.

**Comment by zewpo** [comment]
thanks for considering my feedback.  I'm happy with whatever the community agrees to.
