### ISSUE TITLE
Confusing line in documentation for `clist`

### ISSUE THREAD

**Issue by ddickstein** [vim/vim#11848]
### Steps to reproduce

As far as I'm able to tell from reading and using `clist`, it just displays messages on the screen with items in the quickfix list. That makes this line in its documentation seem misplaced:

> The 'switchbuf' settings are respected when jumping
> to a buffer.

https://github.com/vim/vim/blob/master/runtime/doc/quickfix.txt#L368-L369

### Expected behaviour

The documentation should either remove this line (if its inclusion is unintended) or explain the circumstances under which `clist` will cause a jump to a buffer, since it's not clear from the rest of the text.

### Version of Vim

9.0.1219

### Environment

N/A

**Comment by brammool** [comment]
That lines appears to be misplaced.  Not sure where it should have appeared, I'll remove it.
