### ISSUE TITLE
job_stop cannot kill process tree on windows.

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#1184]
Version:
GVim - 8.0.45 32 bits on Win7 x64

Reproduce:
1. Start a batch file by `myjob = job_start(['cmd.exe', '/C', 'abc.cmd'], ...)`
2. Start a long-time-running command in the batch file.
3. Stop job by `call job_stop(myjob, 'kill')`

Expect:
All the child processes should be killed according to the document.

Result:
Only `cmd.exe` gets killed, all child processes are still running, `close_cb` and `exit_cb` are not invoked.

Channel log:

```
==== start log session ====
  9.211493 : Starting job: C:\Windows\system32\cmd.exe /c C:\Users\Linwei\AppData\Local\Temp\asyncrun.cmd
  9.211862 on 0: Created channel
  9.276309 : looking for messages on channels
  9.377826 RECV on 0: 'Entering dir 'e:/lab/trunk'

python timer 0

'
  9.377837 on 0: Invoking channel callback <SNR>83_AsyncRun_Job_OnCallback
  9.377921 on 0: Invoking channel callback <SNR>83_AsyncRun_Job_OnCallback
  9.393713 : looking for messages on channels
 10.428161 RECV on 0: 'python timer 1

'
 10.428197 on 0: Invoking channel callback <SNR>83_AsyncRun_Job_OnCallback
 10.470649 : looking for messages on channels
 11.432531 RECV on 0: 'python timer 2

(call job_stop, and cmd.exe exit here)

'
 11.432569 on 0: Invoking channel callback <SNR>83_AsyncRun_Job_OnCallback
 11.437469 : looking for messages on channels
 12.220074 on 0: Stopping job with 'kill'
 12.239247 : looking for messages on channels
 12.239365 on 0: Job ended
 12.283459 : looking for messages on channels
 12.409692 RECV on 0: 'python timer 3

(but child process started by cmd.exe is still running) 

'
 12.409729 on 0: Invoking channel callback <SNR>83_AsyncRun_Job_OnCallback
 12.429221 : looking for messages on channels
 13.401916 RECV on 0: 'python timer 4

.............

'
 17.432877 on 0: Invoking channel callback <SNR>83_AsyncRun_Job_OnCallback
 17.453741 : looking for messages on channels
 18.366814 RECV on 0: 'python timer 9

'
 19.374784 on 0: Invoking channel callback <SNR>83_AsyncRun_Job_OnCallback
 19.376939 : looking for messages on channels
 19.390777 ERR on 0: channel_handle_events(): Read error from ch_part[1], closing
 19.390886 : looking for messages on channels
 19.390914 on 0: Closing channel because all readable fds are closed
 19.390935 on 0: Closing channel
 19.390969 on 0: Invoking callbacks before closing
 19.390991 on 0: Invoking close callback <SNR>83_AsyncRun_Job_OnClose
 19.391923 on 0: Freeing job
 19.443185 on 0: Closing channel
 19.443211 on 0: Clearing channel
 19.443219 on 0: Freeing channel
 19.443272 : looking for messages on channels
```

content of `asyncrun.cmd`:

```
@echo off
python timer.py
```

content of `timer.py`:

``` Python
import time, sys
print 'Entering dir \'e:/lab/trunk\''
for i in xrange(10):
    print 'python timer', i
    sys.stdout.flush()
    time.sleep(1)
print 'Leaving dir'
```

Escaping and passing arguments correctly on windows are complex. Most plugins I see, including taglist/tagbar, will use a temporary batch to run commands on windows. In this case, the real job can never be killed if `job_stop` can only stop `cmd.exe`.

Most jobs have more than one process (eg, a building job, piped commands). If I start a complex grep like program on the root of my filesystem by mistake, which will be running for a long time, I can never stop them on windows ?

If I start a group of processes with the wrong parameters (like `tail -f`, `findstr abc`), which continues waiting data from stdin, but `in_io` is unset, they will never get stopped in vim ?

Most piped commands (`dir | grep DIR`) require cmd.exe to interprete the command line on windows, will they also unable to be killed by `job_stop` ?

If a lot of jobs hang in vim, and continue occupying the job slot, we will never able to start a new job until we exit vim and reenter again ?

**Comment by mattn** [comment]
What version of Windows do you use?

**Comment by skywind3000** [comment]
GVim 8.0.45

**Comment by mattn** [comment]
Not vim. Version of Windows.

**Comment by skywind3000** [comment]
sorry, windows 7 x64

**Comment by skywind3000** [comment]
GVim - 8.0.45 32 bits on Win7 x64

**Comment by mattn** [comment]
NP, Thanks. Then, CreateJobObject should work. What commands in your cmd file?

**Comment by skywind3000** [comment]
content of `asyncrun.cmd`:

```
@echo off
python timer.py
```

content of `timer.py`:

``` Python
import time, sys
print 'Entering dir \'e:/lab/trunk\''
for i in xrange(10):
    print 'python timer', i
    sys.stdout.flush()
    time.sleep(1)
print 'Leaving dir'
```

I just saw this: 
http://stackoverflow.com/questions/1173342/terminate-a-process-tree-c-for-windows 

Maybe [CreateToolhelp32Snapshot](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682489%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396) is more useful to compatible xp ?

**Comment by k-takata** [comment]
I think this is a limitation of Win7 or earlier. AssignProcessToJobObject() might fail on Win7.

**Comment by mattn** [comment]
@k-takata docs says Minimum supported client are Windows XP.

**Comment by k-takata** [comment]
@mattn You might remember [the discussion in vim-jp](https://github.com/vim-jp/issues/issues/820#issuecomment-183128981) (in Japanese) when we implemented the job feature.

**Comment by mattn** [comment]
@k-takata  Hmm, right. 

@skywind3000 feel free to implement if you want. ;)

**Comment by skywind3000** [comment]
I tried, but os_win32.c is a little complex for me, I'm afraid I'll screw things up.
Since nobody has the obligation to implement a feature (or fix a bug) I want,
so, to some one who can fix it, I'd like to pay him 1000 USD for appreciation.

**Comment by k-takata** [comment]
Maybe, `TerminateProcess` in [this line](https://github.com/vim/vim/blob/bb09ceb95477ecc271854b3fdd8d2776eca66adf/src/os_win32.c#L5033) might be replaced with the function you referred in your previous message.

**Comment by mattn** [comment]
okay, let's take on this task on vim-jp.

https://github.com/vim-jp/issues/issues/973

**Comment by chrisbra** [comment]
so let me close this issue for now. I guess vim-jp will discuss this issue and provide a patch later :)

**Comment by skywind3000** [comment]
@chrisbra I guess, closing tickets is one of your hobbies ~~~

**Comment by chrisbra** [comment]
@skywind3000  Sometimes I even fix bugs ;)

**Comment by mattn** [comment]
@brammool I wrote a patch to replace this from Windows-JobObject-APIs to use  CreateToolhelp32Snapshot.

https://gist.github.com/mattn/6a048122540cc1c1a4ebd9a373a725d4

**Comment by skywind3000** [comment]
excited

**Comment by skywind3000** [comment]
Thanks everyone, I have a keymap to grep `<cword>` in background, and sometimes I forgot my working directory is `D:\`, which forced me to open the task manager and terminated it. At last, I didn't dare to start a background grep on windows any more. Now I can have another keymap to stop the grep inside vim. This is very convenience.  

Thanks everyone here again.

**Comment by skywind3000** [comment]
@mattn thanks for your patch, could you please tell me how can I make the payment ? 
Wire across banks or paypal donation ?

**Comment by mattn** [comment]
@skywind3000 Thanks. This is. http://www.vim.org/sponsor/
