### ISSUE TITLE
CmdLineEnter/CmdLineLeave/CmdwinEnter/CmdwinLeave for mode ? are triggered when interacting with mode :

### ISSUE THREAD

**Issue by Aster89** [vim/vim#11856]
### Steps to reproduce

Start Vim with `vim -Nu file-below`:
```vim
augroup Foobar
  autocmd!
  autocmd CmdLineEnter ? echom 'CmdLineEnter ?' . localtime()
  autocmd CmdLineLeave ? echom 'CmdLineLeave ?' . localtime()
  autocmd CmdwinEnter ? echom 'CmdwinEnter ?' . localtime()
  autocmd CmdwinLeave ? echom 'CmdwinLeave ?' . localtime()
augroup END
```
and then play with <kbd>q</kbd><kbd>:</kbd>/<kbd>Enter</kbd> and <kbd>:</kbd><kbd>Ctrl-F</kbd>/<kbd>Ctrl-C</kbd>. You'll see that all `autocmd`s above will be triggered, whereas they shouldn't, as they are for backward search command line mode, `?`, not for ex command line mode, `:`.

[![asciicast](https://asciinema.org/a/Lo2pHTQGLwPycbUcqkSYwcoCm.svg)](https://asciinema.org/a/Lo2pHTQGLwPycbUcqkSYwcoCm)

### Expected behaviour

The `autocmd`s in the minimal vimrc above shouldn't be triggered.

### Version of Vim

9.0.1182

### Environment

Operating system: up-to-date ArchLinux
Terminal: urxvt
Value of $TERM: rxvt-unicode-256color
Shell: bash 5.1.16(1)-release

**Comment by zeertzjq** [comment]
`?` matches any single character, and there is no `?` cmdline mode

**Comment by zeertzjq** [comment]
Sorry, there is a `?` cmdline mode, it needs to be matched using `\?`

**Comment by Aster89** [comment]
All of [`CmdlineChanged`](https://vimhelp.org/autocmd.txt.html#CmdlineChanged), [`CmdlineEnter`](https://vimhelp.org/autocmd.txt.html#CmdlineEnter), [`CmdlineLeave`](https://vimhelp.org/autocmd.txt.html#CmdlineLeave), [`CmdwinEnter`](https://vimhelp.org/autocmd.txt.html#CmdwinEnter), [`CmdwinLeave`](https://vimhelp.org/autocmd.txt.html#CmdwinLeave) have this text in the doc:
```
<afile> is set to a single character,
indicating the type of command-line.
|cmdwin-char|
```
and [`cmdwin-char`](https://vimhelp.org/cmdline.txt.html#cmdwin-char) reads:
```
The character used for the pattern indicates the type of command-line:
	:	normal Ex command
	>	debug mode command |debug-mode|
	/	forward search string
	?	backward search string
	=	expression for "= |expr-register|
	@	string for |input()|
	-	text for |:insert| or |:append|
```
Where should I understand `?` needs to be pretended by `\`? Furthermore, the `autocmd`s above are no triggered by <kbd>/</kbd>, for instance.

**Comment by chrisbra** [comment]
Please check `:h file-pattern`, which contains this somewhere below 

> The pattern is interpreted like mostly used in file names:
> 	*	matches any sequence of characters; Unusual: includes path
> 		separators
> 	?	matches any single character
> 	\?	matches a '?'
> 	.	matches a '.'
> 	~	matches a '~'
> 	,	separates patterns
> 	\,	matches a ','
> 	{ }	like \( \) in a |pattern|
> 	,	inside { }: like \| in a |pattern|
> 	\}	literal }
> 	\{	literal {
> 	\\\{n,m\}  like \{n,m} in a |pattern|
> 	\	special meaning like in a |pattern|
> 	[ch]	matches 'c' or 'h'
> 	[^ch]   match any character but 'c' and 'h'
> 
> Note that for all systems the '/' character is used for path separator (even
> for MS-Windows).  This was done because the backslash is difficult to use in a
> pattern and to make the autocommands portable across different systems.


That's why, the example at `:h 'incsearch'` contains these patterns:

> 
> 	If you don't want to turn 'hlsearch' on, but want to highlight all
> 	matches while searching, you can turn on and off 'hlsearch' with
> 	autocmd.  Example: >
> 		augroup vimrc-incsearch-highlight
> 		  autocmd!
> 		  autocmd CmdlineEnter /,\? :set hlsearch
> 		  autocmd CmdlineLeave /,\? :set nohlsearch
> 		augroup END
> 

so if you correct the pattern, does the issue still persist?

**Comment by Aster89** [comment]
Thanks for the explanation!

> so if you correct the pattern, does the issue still persist?

No, the issue is fixes as you foresaw.

However, I have one last question on this topic: if `?` was matching, in my original `autocmd`s, a single character, then why were those `autocmd`s triggered by both <kbd>?</kbd> and <kbd>:</kbd>, **but _not_ by <kbd>/</kbd>**?

**Comment by chrisbra** [comment]
sorry, not sure.
