### ISSUE TITLE
taglist func can not report tag list after upgrade vim 8.0.45

### ISSUE THREAD

**Issue by haolongzhangm** [vim/vim#1185]
vim script eg:
1175         if (cscope_connection() > 0)
1176             let l:list = taglist(a:expr)
1177             let l:len = len(l:list)
1178             call <SID>SrcExpl_WinPrompt(' firtly '. string(a:expr) . string(l:list))
1179             return

always show : 
 firtly '<ignore_suspend>\C'[]

l:list always be empty

**Comment by haolongzhangm** [comment]
cs f g ignore_suspend　have so many result in linux kernel source code, 
so let l:list = taglist(a:expr) show return so may list 

this scipt work fine in vim 7.X

**Comment by chrisbra** [comment]
please provide exact a minimum reproducible example and mention what you expect and what you see. what are your various cscope options?

**Comment by haolongzhangm** [comment]
exact  info about vimscript :  https://github.com/vim-scripts/SrcExpl

issue step : 
1:when use  7.x vim , this vimscript work fine 
2:when upgrade this script , find do not work , after add debug info 

find  vim buildid func 'taglist ' always retrun empty


debug info :  call SrcExpl_WinPrompt(' firtly '. string(a:expr) . string(l:list)) 

print firtly '<ignore_suspend>\C'[]
>>>>> a:expr have the value eg <ignore_suspend>\C , but  l:list is empty []

**Comment by haolongzhangm** [comment]
vimscript link : https://github.com/haolongzhangm/shell_my/blob/master/unexeshell/vim_config/.vim/plugin/srcexpl_base_cscope.vim        
debug info :  line 1178 --line 1180

issue step : 
1:when use 7.x vim , this vimscript work fine 
2:when upgrade this script , find do not work , after add debug info

find vim buildid func 'taglist ' always retrun empty

debug info : call SrcExpl_WinPrompt(' firtly '. string(a:expr) . string(l:list))

print firtly  ignore_suspend []

a:expr have the value eg 'ignore_suspend  , but l:list is empty []

**Comment by haolongzhangm** [comment]
vimscript link : https://github.com/haolongzhangm/shell_my/blob/master/unexeshell/vim_config/.vim/plugin/srcexpl_base_cscope.vim

debug info : line 1178 --line 1180

issue step : 
1:when use 7.x vim , this vimscript work fine 
2:when upgrade vim  , find do not work , after add debug info

find vim buildid func 'taglist ' always retrun empty

debug info : call SrcExpl_WinPrompt(' firtly '. string(a:expr) . string(l:list))

print firtly ignore_suspend []

a:expr have the value eg 'ignore_suspend , but l:list is empty []

**Comment by haolongzhangm** [comment]
vimscript link : https://github.com/haolongzhangm/shell_my/blob/master/unexeshell/vim_config/.vim/plugin/srcexpl_base_cscope.vim

debug info : line 1178 --line 1180

issue step : 
1:when use 7.x vim , this vimscript work fine 
2:when upgrade vim , find do not work , after add debug info

find vim buildin  func 'taglist ' always retrun empty

debug info : call SrcExpl_WinPrompt(' firtly '. string(a:expr) . string(l:list))

print firtly ignore_suspend []

a:expr have the value eg 'ignore_suspend , but l:list is empty []

**Comment by haolongzhangm** [comment]
string  ignore_suspend  has so many define in linux kernel source code tree

**Comment by haolongzhangm** [comment]
Ｄear chrisbra 

any idea about this issue

**Comment by chrisbra** [comment]
@haolongzhangm Please start by answering questions you have been asked. 

I cloned the linux repository. Then what do I have to do? How should I create the cscope database? Then what do I do to trigger the problem? What are your various cscope options?

Please provide an exact and minimum reproducible example and mention what you expect and what you see.

**Comment by vim-ml** [comment]
Hi haolongzhangm!

On Do, 20 Okt 2016, haolongzhangm wrote:

> string  ignore_suspend  has so many define in linux kernel source code tree

And you are using cscope? Does it work interactively in cscope? has the 
database been refreshed? What are your various cscope settings? Can you 
provide a repository with a) the database b) the taglist function and c) 
detailed steps to trigger the problem?

Best,

## Christian

Ein Prozeß, der von der Amöbe zum Menschen geführt hat, schien den
Philosophen augenscheinlichen Fortschritt zu bedeuten - aber ob die
Amöbe dieser Auffassung zustimmen würde, ist nicht bekannt.
        -- Bertrand A. W. Russell

**Comment by haolongzhangm** [comment]
Hi chrisbra and vim-ml 
1: Download kernel src
2:get cscope database at kernel src dir by command: make cscope ARCH=arm64 
3:download  https://github.com/haolongzhangm/shell_my/blob/master/unexeshell/vim_config/.vim/plugin/srcexpl_base_cscope.vim ,
4:download 
https://github.com/vim-scripts/autoload_cscope.vim.git

5: put step3 and step4 file to .vim/plugin

6: vim init/main.c

7: run fuction :SrcExplToggle 

8:put cusror to lockdep_init()



ps : 
1:  infact you can also use ctags , beacuse srcexpl_base_cscope.vim use 
let l:list = taglist(a:expr) to find the tag

you can see ctrl + ] can find the tag , but  taglist will retrun null 

so I think  issue caused by  buildin fuc taglist
2:if you want debug the info , you can open the 
srcexpl_base_cscope.vim , 
line :   1179 and line 1180
you will find taglist api will return  NULL even a:expr have a string , but use ctrl + ] can find the define about the string , eg string = start_kernel

**Comment by haolongzhangm** [comment]
Hi chrisbra and vim-ml 
1: Download kernel src
2:get cscope database at kernel src dir by command: make cscope ARCH=arm64 
3:download https://github.com/haolongzhangm/shell_my/blob/master/unexeshell/vim_config/.vim/plugin/srcexpl_base_cscope.vim ,
4:download 
https://github.com/vim-scripts/autoload_cscope.vim.git

5: put step3 and step4 file to .vim/plugin

6: vim init/main.c

7: run fuction :SrcExplToggle

8:put cusror to lockdep_init()

ps : 
1: infact you can also use ctags , beacuse srcexpl_base_cscope.vim use 
let l:list = taglist(a:expr) to find the tag

you can see ctrl + ] can find the tag , but taglist will retrun null

so I think issue caused by buildin fuc taglist
2:if you want debug the info , you can open the 
srcexpl_base_cscope.vim , 
line : 1179 and line 1180
you will find taglist api will return NULL even a:expr have a string , but use ctrl + ] can find the define about the string , eg string = lockdep_init

**Comment by haolongzhangm** [comment]
Dear chrisbra amd  vim-ml  
any idea for the issue ?

**Comment by chrisbra** [comment]
Hi, I still cannot reproduce. Because after :ScrExplToggle, I get an empty second window that only says "  Source Explorer v5.3" and no more content. Also again, what are your cscope related settings?

**Comment by haolongzhangm** [comment]
Dear chrisbra 

at you env , can you find tags by ctrl + ]  or not ?　after step: 
1: make cscope ARCH=arm64  
2: download 
https://github.com/vim-scripts/autoload_cscope.vim.git　　　, then  
put this plugn to  to .vim/plugin 

> > > > > > if you can find tags by ctrl + ]  , 
> > > > > > then you should open  debug  modify by : 
> > > > > > open srcexpl_base_cscope.vim , 
> > > > > > opne line : 1179 and line 1180
> > > > > > then you will find the API issue ,
> > > > > > 
> > > > > > if you can not find tags by  ctrl + ] , you should fisrtly follow : 
> > > > > > 1: make cscope ARCH=arm64  
> > > > > > 2: download 
> > > > > > https://github.com/vim-scripts/autoload_cscope.vim.git　　　, then  
> > > > > > put this plugn to  to .vim/plugin

**Comment by haolongzhangm** [comment]
Dear chrisbra
any idea?

**Comment by chrisbra** [comment]
it would help, if questions asked would actually get answered.

**Comment by haolongzhangm** [comment]
Dear vim-ml  and chrisbra
Can u repoduce this issue or not?

**Comment by haolongzhangm** [comment]
gdb /home/zhl/vim-master/src/vim
b f_taglist
b get_tags

646     ftrace_init();
647 
648     /* Do the rest non-__init'ed, we're now alive */
649     rest_init();
650 }

1: Ctrl + ]  "rest_init"  will return the define  of rest_init 
2: then use : call taglist("rest_init")

  tagkind = 0x100000000 <error: Cannot access memory at address 0x100000000>, tagkind_end = 0xd2adb0 ""}
is_static = 5359333
(gdb) n
3899	    if (ret == OK && num_matches > 0)
(gdb) n
3975	    return ret;
(gdb) n
3976	}
(gdb) i locals 
num_matches = 0
i = 0
ret = 1
matches = 0x0
p = 0x7fffffffcc90 "\260\314\377\377\377\177"
full_fname = 0x58f454a760 <error: Cannot access memory at address 0x58f454a760>
dict = 0x7fffffffcdb0
tp = {tagname = 0x7fffffffccb0 "\340\314\377\377\377\177", 
  tagname_end = 0x4f3d58 <list_alloc+18> "H\211E\370H\203", <incomplete sequence \370>, fname = 0x919940 <mybuf> "2", fname_end = 0xd2adb0 "", 
  command = 0x7fffffffcce0 "\020\315\377\377\377\177", 
  command_end = 0x4f3dbb <rettv_list_alloc+17> "H\211E\370H\203", <incomplete sequence \370>, 
  tag_fname = 0x7fffffffcce0 "\020\315\377\377\377\177", is_etag = -11712, 
  tagkind = 0x100000000 <error: Cannot access memory at address 0x100000000>, tagkind_end = 0xd2adb0 ""}
is_static = 5359333
(gdb) n
f_taglist (argvars=0x7fffffffd070, rettv=0x7fffffffd240) at evalfunc.c:12304
12304	}
(gdb) i locals 
fname = 0x0
tag_pattern = 0x9672b0 "rest_init"
(gdb) p *(typval_T *)rettv
$1 = {v_type = VAR_LIST, v_lock = 0 '\000', vval = {v_number = 13807024, v_float = 6.8215762297055912e-317, v_string = 0xd2adb0 "", 
    v_list = 0xd2adb0, v_dict = 0xd2adb0, v_partial = 0xd2adb0, v_job = 0xd2adb0, v_channel = 0xd2adb0}}
(gdb) Quit
(gdb) nQuit
(gdb) q



>>>>>>>>issue happened from get_tags()retrun num_matches ---> from find_tags()return err

**Comment by haolongzhangm** [comment]
find_tags call backtrace
(gdb) 
1629		    if (get_it_again)
(gdb) 
1635		    if (state == TS_BINARY)
(gdb) 
1648		    else if (state == TS_SKIP_BACK)
(gdb) 
1663		    if (state == TS_BINARY || state == TS_SKIP_BACK)
(gdb) 
1708			    if (use_cscope)
(gdb) 
1709				eof = cs_fgets(lbuf, LSIZE);
(gdb) 
1713			} while (!eof && vim_isblankline(lbuf));
(gdb) 
1715			if (eof)
(gdb) 
1718			    if (incstack_idx)	/* this was an included file */
(gdb) 
1730				break;			    /* end of file */
(gdb) 
2458		if (line_error)
(gdb)
