### ISSUE TITLE
exists('#TerminalWinOpen') return unexpected 0

### ISSUE THREAD

**Issue by jiz4oh** [vim/vim#11857]
### Steps to reproduce

```vim
echo exists('#TerminalWinOpen') 
" 0
echo exists('#TerminalOpen') 
" 1
```

return 0 even through the 'TerminalWinOpen' even is exists on my vim.

### Expected behaviour

return 1 as same as `echo exists('#TerminalOpen') `

### Version of Vim

9.0.1200

### Environment

OSX,
iterm2,
zsh

**Comment by brammool** [comment]
Please say why this issue was closed.  Perhaps because it works as expected?
```
echo exists('#TerminalWinOpen') 
" results in '0'
au TerminalWinOpen * echo 'open'
echo exists('#TerminalWinOpen') 
" results in '1'
```

**Comment by jiz4oh** [comment]
Hi bram, I'm so sorry for open the issue, it's my fault. I should use below instead

```vim
exists('##TerminalWinOpen') 
```
