### ISSUE TITLE
GVIM: decreasing font size doesn't re-draw pixels on screen.

### ISSUE THREAD

**Issue by fernando-gap** [vim/vim#11854]
### Steps to reproduce

1. `:set guifont=Monospace\ 20` (any number greater than the current)
2. `:set guifont=Monospace\ 15` (any number less than the current)

### Expected behaviour

The screen should be re-draw entirely when the font size decreases making it fit in the screen. Instead the screen presents a blank page at the bottom of the screen.

The color scheme is desert. I changed the default just to highlight in any case.

![gvim-fontsize-bug](https://user-images.githubusercontent.com/63003765/213831423-396bd297-0291-42bb-9cf0-abe293359fa7.jpg)

### Version of Vim

9.0.1182

### Environment

OS: Arch Linux.
I am using the official arch linux gvim package.

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> 1. `:set guifont=Monospace\ 20` (any number greater than the current)
> 2. `:set guifont=Monospace\ 15` (any number less than the current)
> 
> ### Expected behaviour
> 
> The screen should be re-draw entirely when the font size decreases making it fit in the screen. Instead the screen presents a blank page at the bottom of the screen.
> 
> The color scheme is desert. I changed the default just to highlight in any case.
> 
> ![gvim-fontsize-bug](https://user-images.githubusercontent.com/63003765/213831423-396bd297-0291-42bb-9cf0-abe293359fa7.jpg)
> 
> 
> ### Version of Vim
> 
> 9.0.1182
> 
> ### Environment
> 
> OS: Arch Linux.
> I am using the official arch linux gvim package.

Essential information that is missing here: What GUI does this use?
The first four lines of output from :version would be very helpful.

-- 
hundred-and-one symptoms of being an internet addict:
32. You don't know what sex three of your closest friends are, because they
    have neutral nicknames and you never bothered to ask.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by fernando-gap** [comment]
These are the missing lines.

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jan 12 2023 11:41:18)
Included patches: 1-1182
Compiled by Arch Linux

**Comment by chrisbra** [comment]
and what gui?

**Comment by fernando-gap** [comment]
GTK3 GUI

**Comment by brammool** [comment]
> These are the missing lines.
> 
> VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jan 12 2023 11:41:18)
> Included patches: 1-1182
> Compiled by Arch Linux

I did ask for four lines, right?  Should be something like:

Huge version with GTK3 GUI.  Features included (+) or not (-):

I built with GTK3, for me the window resizes just fine.  At least, from
your screenshot I guess that the text gets smaller, but the window
doesn't get smaller.

Do you have the window maximized perhaps?  It can also depend on your
window manager.

-- 
Have you heard about the new Beowulf cluster? It's so fast, it executes
an infinite loop in 6 seconds.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by fernando-gap** [comment]
Yep, you are right, I misread the text.

As you said, apparently it must have something to do with the window
manager as I am using i3, I switched to KDE Plasma and the bug was gone, it
worked perfectly, so it must be a bug probably with i3.


Em sáb., 21 de jan. de 2023 às 17:47, Bram Moolenaar <
***@***.***> escreveu:
