### ISSUE TITLE
Diff mode fails to highlight this difference

### ISSUE THREAD

**Issue by esiegerman** [vim/vim#1186]
(Tested with vim 8.0.42.)

`vimdiff` these three files (there are _no_ whitespace differences):

file-1:

```
111 aaa
111 bbb
```

file-2:

```
111 aaa
222 bbb
```

file-3:

```
222 aaa
111 bbb
```

The highlighting is wrong -- vim doesn't show the difference in the second line:
![diffbug](https://cloud.githubusercontent.com/assets/6914978/19570606/b840bffa-96c8-11e6-9780-de9237ed0331.png)

If you swap the lines in file-3, again the second (screen) line doesn't have its difference highlighted:
![diffbug2](https://cloud.githubusercontent.com/assets/6914978/19570610/bef5b044-96c8-11e6-82c0-5c69eb11031c.png)

Note that (after restoring the original version of file-3), if you swap the lines in either of the other two files, vimdiff shows correct results.  With file-1's lines swapped:
![diffbug3](https://cloud.githubusercontent.com/assets/6914978/19571317/a72eb7f0-96cb-11e6-9d19-41ce3aacd4c7.png)

With file-2's lines swapped:
![diffbug4](https://cloud.githubusercontent.com/assets/6914978/19571323/acd01f5a-96cb-11e6-844a-0f156ad869c9.png)

**Comment by brammool** [comment]
I can reproduce this.

**Comment by chrisbra** [comment]
this seems resolved in the meantime.
