### ISSUE TITLE
Right-click pasting from PuTTY on Windows 10

### ISSUE THREAD

**Issue by pcgeek86** [vim/vim#1188]
Vim 8.0 is pretty rad, and has some incredible new features! Unfortunately, it broke one of my common workflows, when copying and pasting text into a document.
## Typical Scenario

From a Windows 10 Anniversary Update client ...
- Open a web browser, copy / paste some text from a website (eg. GitHub)
- Use PuTTY 0.67 to SSH to a Linux VM (eg. Ubuntu 16 Xenial Xerus)
- Open a file in Vim
- Hit `i` to change into Insert mode
- Right-click to paste the clipboard contents
## Issue Description

Unfortunately, when I right-click in the PuTTY session, rather than pasting clipboard contents, what's actually happening is that Vim is going from `INSERT` mode to `(insert) VISUAL` mode. I don't think I've ever seen anything like this before. Does anyone know why this is happening, and how I can paste my Windows client clipboard into the SSH / Vim session?

![image](https://cloud.githubusercontent.com/assets/466713/19578921/38e09e98-96db-11e6-8925-7268bae2f574.png)

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by k-takata** [comment]
Check your `'mouse'` setting with `:set mouse?`.
If you include `vimrc_example.vim` from your `.vimrc`, the setting of `'mouse'` will be changed after Vim 8.

FYI, `Shift+Ins` might be also used to paste on PuTTY.

**Comment by pcgeek86** [comment]
Thanks @k-takata -- I fixed this problem by using:

```
:set mouse=
```

**Comment by Expire0** [comment]
I am wondering if this is a bug was by design in VIM 8?  The same is happening via Fedora 25.  When right clicking it put you into visual mode.  The only fix is to add set mouse-=a or set mouse= to .vimrc

**Comment by pcgeek86** [comment]
A couple years later ... I ran into this same issue again, and `SHIFT + INSERT` works perfectly as well. Thanks again.

**Comment by Stefan300381** [comment]
this helped me in 2020 ;-) thanks

**Comment by hecko** [comment]
> this helped me in 2020 ;-) thanks

and now me in 2021! :)

**Comment by theGidy** [comment]
and it still helps :)

**Comment by jay-yuan-moodys** [comment]
It still helped me in 2010

**Comment by ThBexx** [comment]
you made my day! Thank you

**Comment by mpolitze** [comment]
cheers from 2023!

**Comment by betrion** [comment]
cheers from 2026. :)
