### ISSUE TITLE
Redrawing of lines below the end of a buffer are much slower than normal lines

### ISSUE THREAD

**Issue by monkoose** [vim/vim#11881]
Could it be improved? 
https://user-images.githubusercontent.com/6261276/214542384-f110e03e-64b5-4376-b1cc-ade687a2e68b.mp4

Steps to reproduce (I have used gvim because it shows cursor position on redrawing, but it is the same in vim)
1. `gvim --clean +"set wd=2"
2. Open some file that span multiple screens and scroll it with `Ctrl-f` and `Ctrl-b`

**Comment by brammool** [comment]
In a normal line the white space after a line can be cleared with t_ce, clear to end-of-line.  A terminal normally optimizes that and it should be quick.
The white space below the text uses the attribute from EndOfBuffer, which may be anything.  Therefore the blank space has to be drawn with spaces, which can take longer.

Try this: ```hi link EndOfBuffer NONE``` and/or ```:hi clear EndOfBuffer```.

We cannot change this without disappointing users that have intentionally set highlighting for this area.

BTW: your recording shows the cursor, that will take extra time and normally doesn't happen.

**Comment by monkoose** [comment]
> Try this: `hi link EndOfBuffer NONE`

Thank You it definitely helped, and now cursor moves only to draw this end of line characters.
