### ISSUE TITLE
Decrementing octal number does not preserve lenght

### ISSUE THREAD

**Issue by Gurran** [vim/vim#11889]
### Steps to reproduce

In normal mode decrement (`Ctrl-X`) the following number
`000000000`
it returns 
`01777777777777777777777`

### Expected behaviour

The result should preserve the length of the number and result in
`017777777` 

### Version of Vim

9.0 1051

### Environment

Ubuntu 22.04.1 LTS
Gnome Terminal
xterm-256color
ZSH

**Comment by Gurran** [comment]
I've recompiled Vim and issue still exists on version 9.0 Included patches: 1-1285

**Comment by brammool** [comment]
Comment from Marvin Renich on the vim-dev list was not included here:

I'm not sure the current behavior is wrong.  Octal numbers are treated
as unsigned, and 64-bit arithmetic is being used.

The help says "Vim preserves the number of characters in the number when
possible."  Note that if you use Ctrl-A on 077 you get 0100.  The result
of Ctrl-X on 0000 is (2*64)-1, which requires more digits to represent.

Bram should determine what he intended here, and what makes most sense,
but I think the current behavior makes more sense and obeys the docs.

**Comment by brammool** [comment]
My comment on the vim-dev list was not included here:

Changing the resulting value is not backwards compatible.  It might
cause problems (although I doubt more than a few users actually use
octal numbers these days).

There are a few alternatives to the current behavior, and I can't say
any of them is really better than the current behavior.  E.g., going to
minus one or considering the change to be an error (disallow wraparound).

We could perhaps make the help a bit clearer.  Any suggestions?

**Comment by chrisbra** [comment]
so I guess you want: `:set nrformat-=octal`

**Comment by Gurran** [comment]
> so I guess you want: `:set nrformat-=octal`

Yes! I didn't know that `nrformat` existed.

Thanks for the help. Sorry to bother you.
