### ISSUE TITLE
Add filename modifier to get absolute, resolved path

### ISSUE THREAD

**Issue by blueyed** [vim/vim#1189]
It would be nice to have a new filename-modifier to get the absolute path, where symlinks are resolved, so that `%:a` would be a shortcut for `resolve(expand('%:p'))`.

**Comment by vim-ml** [comment]
Daniel Hahler (Vim Github Repository) wrote:

> It would be nice to have a new filename-modifier to get the absolute 
> path, where symlinks are resolved, so that |%:a| would be a shortcut 
> for |resolve(expand('%:p'))|.
> 
> ---
> 
> Yes, it would -- but how would you do that?

There is no "backlink" to find out how you got to where you are
at and there could be multiple symlinks to get you to the same
location -- so how would you know?

**Comment by vim-ml** [comment]
Daniel Hahler (Vim Github Repository) wrote:

> It would be nice to have a new filename-modifier to get the absolute 
> path, where symlinks are resolved, so that |%:a| would be a shortcut 
> for |resolve(expand('%:p'))|.
> 
> ---
> 
> Yes, it would -- but how would you do that?

There is no "backlink" to find out how you got to where you are
at and there could be multiple symlinks to get you to the same
location -- so how would you know?

**Comment by ZyX-I** [comment]
Why this was closed?
