### ISSUE TITLE
`test_channel.vim` fails on macOS

### ISSUE THREAD

**Issue by benknoble** [vim/vim#11894]
### Steps to reproduce

1. Clone source (commit `870219c58c0804bdc55419b2e455c06ac715a835`)
2. `make -C the-source/src/testdir test_channel`

### Expected behaviour

The test should pass

### Version of Vim

9.0.1247

### Environment

- macOS 12.6.2
- Alacritty
- `alacritty`, but I set `TERM=xterm` during tests typically to prevent termcap warnings during certain tests
- Zsh

Notably, I can reproduce this only on my work computer; my personal laptop (macOS 11.7) passes just fine.

### Logs and stack traces

```shell
It looks like the connection times out even after resolving localhost to IPv6, but when I run the server with `python3 test_channel.py`, I can `telnet localhost port` or `telnet ::1 port` (though I cannot `telnet 127.0.0.1 port`).

`channellog`:

==== start log session Jeu jan 26 16:27:01 2023 ====
  0.003308 : ch_log(): Test_call()
  0.003426 : Starting job: python3  test_channel.py
  0.003454 on 0: Created channel
  0.004368 : closing logfile channellog
  0.004620 : ui_delay(10)
  0.014844 : looking for messages on channels
  0.015482 : ui_delay(10)
  0.025530 : looking for messages on channels
  0.026006 : ui_delay(10)
  0.036167 : looking for messages on channels
  0.036560 : ui_delay(10)
  0.048605 : looking for messages on channels
  0.049134 : ui_delay(10)
  0.059417 : looking for messages on channels
  0.059858 : ui_delay(10)
  0.070091 : looking for messages on channels
  0.070612 : ui_delay(10)
  0.081568 : looking for messages on channels
  0.082218 on 1: Created channel
  0.082863 on 1: Resolved localhost to ::1
  0.082879 on 1: Trying to connect to ::1 port 58761
  0.088327 on 1: Connecting...
  0.088491 on 1: Waiting for connection (waiting 1 msec)...
  0.089545 ERR on 1: Connection timed out
  0.089574 on 1: Resolved localhost to 127.0.0.1
  0.089584 on 1: Trying to connect to 127.0.0.1 port 58761
  0.096763 on 1: Connecting...
  0.096852 on 1: Waiting for connection (waiting 1 msec)...
  0.096891 ERR on 1: Connection timed out
  0.096980 on 0: Stopping job with ''
  0.097234 on 0: detaching channel from job
  0.098525 on 0: channel_select_check(): Read EOF from ch_part[1], closing
  0.098550 on 0: channel_select_check(): Read EOF from ch_part[2], closing
  0.101687 : ui_delay(20)
  0.126334 : looking for messages on channels
  0.126417 on 1: Closing channel because all readable fds are closed
  0.126442 on 1: Closing channel
  0.126463 on 1: Closing channel
  0.126483 on 1: Clearing channel
  0.126503 on 1: Freeing channel
  0.126526 on 0: Closing channel because all readable fds are closed
  0.126546 on 0: Closing channel
  0.126575 on 0: Closing channel
  0.126595 on 0: Clearing channel
  0.126614 on 0: Freeing channel
  0.126667 : Job ended
  0.126698 : Freeing job
  0.126725 : looking for messages on channels
  0.126748 : ui_delay(1000)
  1.131146 : looking for messages on channels
  1.131221 : ui_delay(971)
  2.105593 : looking for messages on channels
[ repeats for Test_call and other failing tests ]
```
```

**Comment by chrisbra** [comment]
Hm, there were some IPv6 related changes in https://github.com/vim/vim/commit/765d82a657c5e42d5d7c88ae410e53f398c34c43 

Perhaps @jamessan knows about it, since he made the latest change?

**Comment by benknoble** [comment]
_If_ I can get `gdb` working with Vim on both machines, I'll try to debug just the call to `ch_open` while running the Python server.

**Comment by benknoble** [comment]
Personal computer resolving localhost to `[::1]` (start server, debug compiled vim, run `:echo ch_open('localhost:PORT', {})`):
- `channel.c:658` (`ret = connect(…);`) returns `-1`, but the python server prints "socket opened." Then the code jumps through some `select` stuff to finally confirm the socket is really truly open (`channel.c:713` (`ret = select(sd + 1, …)`) returns 1 and `channel.c:745` (`ret = getsockopt(…`) returns 0, so `channel.c:770` (`if (FD_ISSET(sd, …)) break;`) breaks out). Return the socket descriptor `sd` and continue as normal.

Work machine (same steps):
- same return val from `connect`; same return val from `select`; same return val from `getsockopt`; same break. Cannot reproduce failure (?).

Work machine (no debugger; just run `./src/vim` and `:echo ch_open(…)`):
- prints "channel fail"

This suggests it _could_ be a timing issue on the work machine? Since debugging slows things down? How can I test this?

**Comment by benknoble** [comment]
Repro'd on d6e4c75af2d6435794f1a9259141d6d7c1923b4c (latest master); adding `mch_delay(1000, MCH_DELAY_IGNOREINPUT)` as in the following patch did _NOT_ eliminate the problem, so I don't think my experience in the debugger should be chalked up to timing. Thoughts on how to reproduce the problem in the debugger or where else to look?

```patch
diff --git i/src/channel.c w/src/channel.c
index db4568d..c5cc116 100644
--- i/src/channel.c
+++ w/src/channel.c
@@ -655,6 +655,7 @@ channel_connect(
 	// Try connecting to the server.
 	ch_log(channel, "Connecting...");
 
+	mch_delay(1000, MCH_DELAY_IGNOREINPUT);
 	ret = connect(sd, server_addr, server_addrlen);
 	if (ret == 0)
 	    // The connection could be established.
```

**Comment by benknoble** [comment]
> You could try changing "1" to "100" or so.

Anything over 15 was sufficiently non-flaky on the work machine. Feel free to adjust the comment, too:

```patch
diff --git i/src/channel.c w/src/channel.c
index db4568d..bd28eac 100644
--- i/src/channel.c
+++ w/src/channel.c
@@ -980,10 +980,10 @@ channel_open(
 	ch_log(channel, "Trying to connect to %s port %d", dst, port);
 
 	// On Mac and Solaris a zero timeout almost never works.  At least wait
-	// one millisecond.  Let's do it for all systems, because we don't know
+	// 15 milliseconds.  Let's do it for all systems, because we don't know
 	// why this is needed.
 	if (waittime == 0)
-	    waittime = 1;
+	    waittime = 15;
 
 	sd = channel_connect(channel, addr->ai_addr, (int)addr->ai_addrlen,
 								   &waittime);
```
