### ISSUE TITLE
E315 upon tabprevious command

### ISSUE THREAD

**Issue by BioBox** [vim/vim#11907]
### Steps to reproduce

In vim I have two tabs.

* The first tab has a horizontal split.
* The second tab has a one file open.
* It should be noted that each of these three windows has a different lcd.

In this arrangement I often:
* Append some code on the top window of the first tab.
* Use `gt` to move to the second tab to look at docs.
* Use `gT` to go back to where I was.

Upon arriving back at my previous tab I get 
```
E315: ml_get: invalid lnum: 63
E315: ml_get: invalid lnum: 64
E315: ml_get: invalid lnum: 65
```

and so on. Hitting Enter a few times fixes it, but this is obviously a bug

### Expected behaviour

Go back to the previous tab without any errors.

### Version of Vim

9.0 (1-1046)

### Environment

* OS: Manjaro i3
* Terminal: urxvt
* Value of `$TERM`: `xterm-256color`
* Shell: fish 3.5.1

### Logs and stack traces

```shell
If there's a way to get a stacktrace/log of what is happening then please let me know.
```

**Comment by BioBox** [comment]
Upon checking `au TabEnter` it seems that the [taboo plugin](https://github.com/gcmt/taboo.vim) was causing the issue, as disabling it seems to fix it for now. I'll close this issue at the end of the day unless it pops up for me again.

**Comment by dpelle** [comment]
@BioBox wrote:

> I'll close this issue at the end of the day unless it pops up for me again.

I would not close it. Even if it's a plugin that triggers E315, that error is an internal error, so it's always a bug in Vim if you can reproduce it.

I've never used that [taboo plugin](https://github.com/gcmt/taboo.vim) but I'm going to give it a try it I can reproduce the bug with the latest Vim.

**Comment by brammool** [comment]
It would be very helpful to know how to reproduce this problem without a plugin.
Perhaps the context of the error message contains a hint?
Ideally a Vim script executed by "vim --clean" that reproduces the problem (which can be used as a regression test).

**Comment by BioBox** [comment]
I've only been able to recreate the bug with the plugin installed sorry.

**Comment by dpelle** [comment]
I've installed the taboo plugin, but I did not succeed reproducing the E315 bug.
I'm using vim-9.0.1266 on Linux.
I built with `-DABORT_ON_INTERNAL_ERROR` so I can make sure I don't miss internal errors.

To @BioBox : Can you provide detailed steps to reproduce?
Ideally, try to automate reproducing the E315 error with a Vim script, so it's easier to reproduce and less ambiguous.

**Comment by BioBox** [comment]
Sourcing this script reproduces the error on my machine but you may have to adjust the names of the files:
```vim
e pin.py
packadd taboo
split ~/proj/vin/nodes.v
tabnew ~/proj/v/vlib/regex/README.md
tabprevious
```

**Comment by brammool** [comment]
That you do not get the error when using "--clean" indicates that something else in your setup matters.
To find out, there are at least two things that you can do: First put "finish" at the top of your vimrc file (should be the first file listed in the output of :scriptnames).  If that makes a difference, move "finish" to other lines until you find the line that matters.

The second thing is to make your viminfo file empty.  Best is to move it to another location (where Vim won't look for it), so that you can move it back later.  See ":help viminfo-file-name" for the name of the file.

**Comment by Bakudankun** [comment]
I could reproduce very similar error with this script:

```vim
" test.vim
autocmd WinEnter,BufWinEnter * setlocal wincolor=
autocmd WinLeave * setlocal wincolor=Pmenu

set lines=20 columns=80
call setline(1, repeat([''], 25))
$
tabnew
call setline(1, repeat([''], 80))
$
tabNext
```

How to reproduce: `vim --clean -S test.vim`

It will emit five errors:

```
E315: ml_get: Invalid lnum: 26
E315: ml_get: Invalid lnum: 27
E315: ml_get: Invalid lnum: 28
E315: ml_get: Invalid lnum: 29
E315: ml_get: Invalid lnum: 30
```

**Comment by Bakudankun** [comment]
Maybe different problem, but recently I noticed that `G` has an inconsistency from some day.
When editing a bufffer with many lines, I beleave hitting `G` used to set the cursor position to the bottom of the window, but recently it ocasionally sets the cursor to the middle of the window and show some EOB lines.

**Comment by Bakudankun** [comment]
Sorry, the problem about `G` must be unrelated. It is reproduced only when `:set smoothscroll`.

**Comment by zeertzjq** [comment]
It seems that the autocommands are not needed to reproduce this. This is enough:
```vim
set lines=20 columns=80
call setline(1, repeat([''], 25))
$
tabnew
call setline(1, repeat([''], 80))
$
tabNext
```

**Comment by dpelle** [comment]
I can confirm that I can reproduce the internal error E315 using @zeertzjq script.
I could simplify it slightly (one less line than in script from above comment) using:
```
set lines=20 columns=80
call setline(1, repeat([''], 25))
$
tabnew
call setline(1, repeat([''], 80))
tabNext
```

Having those lines in `internal-errors.vim` and using vim-9.0.1354:
```
$ vim --clean -c 'so internal-errors.vim'

vim:r detected while processing command line..script /home/dope/internal-errors
Press ENTER or type command to continue
E315: ml_get: Invalid lnum: 26
E315: ml_get: Invalid lnum: 27
E315: ml_get: Invalid lnum: 28
E315: ml_get: Invalid lnum: 29
E315: ml_get: Invalid lnum: 30
```
