### ISSUE TITLE
Windows Security complains - Trojan:Script/Wacatac.B!ml

### ISSUE THREAD

**Issue by zewpo** [vim/vim#11905]
### Steps to reproduce

1. Download a slightly patched gvim_9.0.1251_x64.exe installer from vim-win32-installer project

https://ci.appveyor.com/project/chrisbra/vim-win32-installer/builds/46072053/job/v77baqvt9yt0ke1x/artifacts

2. Run the installer on Windows 11 [Version 10.0.22621.1194]

Windows Security complains:

```
Trojan:Script/Wacatac.B!ml

Alert level: Severe
Status: Active
Category: Trojan
Details: This program is dangerous and executes commands from an attacker.

Affected items:
  file: C:\Program Files\Vim\vim90\install.exe
```

### Expected behaviour

Windows Security to not complain.

### Version of Vim

https://ci.appveyor.com/api/buildjobs/v77baqvt9yt0ke1x/artifacts/gvim_9.0.1251_x64.exe

### Environment

Note: this package does include a very minor patch to the NSIS install script - to take ownership of the users own $home\vimfiles directory - but this doesn't include any changes to the source code that builds installer.exe - so this came as a surprise.

**Comment by chrisbra** [comment]
This is a known false positive. It's clean according to virustotal https://www.virustotal.com/gui/url/7906ccfbd963fe1940c411233c04fd1f0f5f4681c4e8bc8319b0d9cfde364e52?nocache=1 

I suppose some of the heuristics of Windows security are a bit aggressive, especially for unknown/new files that have just recently been created

**Comment by chrisbra** [comment]
I don't think there is anything the vim project can do to fix that.

**Comment by zewpo** [comment]
@chrisbra   thanks, yeah I thought it was a false-positive.  Just that I've installed it a couple dozen times now, so was surprised to see it - and just wanted to check if others have ever seen it.
