### ISSUE TITLE
Suggestions for release pipeline improvements

### ISSUE THREAD

**Issue by kiminno** [vim/vim#11912]
I would like to make contributions to Vim's release pipeline. As I am new to this repository, I am not familiar with Vim's CICD process. Are there any pain points or concerns regarding the integration, build, deployment, and monitoring processes that I can dive into to start?

**Comment by brammool** [comment]
There isn't really a "release pipeline".  Every patch creates a new version, thus there is a continuous stream of new "micro-releases".  Once in a while there is a release, usually when some large new feature has been implemented. I do not see a good reason to change this.

Anyway, this is not really a Vim issue, therefore closing this.  Discussions can happen on the vim-dev maillist.
