### ISSUE TITLE
Ctrl-o u in insert mode doesn't redraw screen immediately

### ISSUE THREAD

**Issue by barlik** [vim/vim#1191]
After typing some text in insert mode and then typing `Ctrl-o u` to undo it, the screen doesn't redraw immediately, but only after another key press.

Tested with `vim -u NONE -N`

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 26 2016 10:00:18) Included patches: 1-13

**Comment by lacygoill** [comment]
Fixed by https://github.com/vim/vim/commit/e0429681aed5448d1c3b8399d152a2b1a05ea6d7.
