### ISSUE TITLE
Unverified bug report on huntr.dev- heap-buffer-overflow in function utfc_ptr2len and function utf_head_off

### ISSUE THREAD

**Issue by soaarony** [vim/vim#11917]
Hi sir, I have made a bug report on huntr.dev. The report is unverified for past 1 week. May I know if my bug report is valid or require me to edit further? 

link to the bug report: https://huntr.dev/bounties/db7be8d6-6cb7-4ae5-9c4e-805423afa378/

Thank you!

**Comment by brammool** [comment]
> Hi sir, I have made a bug report on huntr.dev. The report is
> unverified for past 1 week. May I know if my bug report is valid or
> require me to edit further? 
> 
> link to the bug report: https://huntr.dev/bounties/db7be8d6-6cb7-4ae5-9c4e-805423afa378/

I'm running a bit behind dealing with issues.  It's on the todo list,
I should get to it in a few days.

-- 
hundred-and-one symptoms of being an internet addict:
66. You create a homepage with the impression to cure the afflicted...but
    your hidden agenda is to receive more e-mail.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by soaarony** [comment]
Thank you very much Sir. Much appreciated! :)

**Comment by brammool** [comment]
Let's not have one issue on huntr also have an issue on github, that creates a confusing exception.
I'll close this one.

**Comment by soaarony** [comment]
Hi Sir, is there any update on this? thank you!!
