### ISSUE TITLE
`gd` fails after curly block

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#11929]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        var lines =<< trim END
            vim9script
            var x = 0

            {
                echo
            }
            var y = x
        END
        lines->setline(1)
        search('x$')
        normal! gd
    EOF
    )

The cursor is still on the assigned `x` on line 7.

**Expected behavior**

The cursor is on the declared `x` on line 2.

**Version of Vim**

9.0 Included patches: 1-1270

**Environment**

Operating system: Ubuntu 20.04.5 LTS
Terminal: XTerm(378)
Value of $TERM: xterm-256color
Shell: GNU bash, version 5.0.17

**Additional context**

The issue disappears if we remove the curly block:
```vim
vim9script
var lines =<< trim END
    vim9script
    var x = 0

    var y = x
END
lines->setline(1)
search('x$')
normal! gd
```
Or just the empty line:
```vim
vim9script
var lines =<< trim END
    vim9script
    var x = 0
    {
        echo
    }
    var y = x
END
lines->setline(1)
search('x$')
normal! gd
```

**Comment by brammool** [comment]
> **Steps to reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(tee <<'EOF'
>         vim9script
>         var lines =<< trim END
>             vim9script
>             var x = 0
> 
>             {
>                 echo
>             }
>             var y = x
>         END
>         lines->setline(1)
>         search('x$')
>         normal! gd
>     EOF
>     )
> 
> The cursor is still on the assigned `x` on line 7.
> 
> **Expected behavior**
> 
> The cursor is on the declared `x` on line 2.

The "gd" command was made to work with C.  It doesn't work well with Vim
script.  Like the help explains, it first finds the start of a function.
In this case it finds the "{" in the first column, and assumes the
function starts there.  Then it searches back for a blank line, which
happens to be just above the "{".  Then it searches for "x", which it
finds where the search started.

If you remove the "{" then it doesn't find the start of a function, and
the search starts in the first line.

If you remove the empty line above "{" the search will start in the
first line and it will find the "var x" line.

I don't think this can be fixed without completely changing how it
works.  And best would be to have a plugin for the filetype, or at least
options that specify what the start of a function and what a declaration
looks like.

-- 
% cat /usr/include/long_life.h
long life(double fun);

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
OK, I'll try to write a wrapper mapping around `gd` to handle this corner case.
