### ISSUE TITLE
Incorrect redraw after undoing first line moves

### ISSUE THREAD

**Issue by yishailerner** [vim/vim#11938]
### Steps to reproduce

1. Open Vim (using `vim --clean`) and write the following contents:
```text
First
Second
Third
```

2. Execute `:m +1` to move the "First" line below the "Second" line.
3. Press `u` to undo the last step.
4. Buffer should contain:
```
First
Second
First
```

### Expected behaviour

Undo should restore buffer contents to:
```
First
Second
Third
```

In fact, triggering a rewrite of the last line (by pressing `v` to create a selection, or by editing it) correctly updates the line to the expected "Third", so it looks like the undo is correct but some part of rewriting is buggy.

The bug only happens when moving the first line, but exists regardless of line count.

### Version of Vim

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jan 12 2023 11:41:18). Included patches: 1-1182

### Environment

Operating system: Arch Linux
Terminal: foot
Value of `$TERM`: foot
Shell: fish

I've verified the bug persists across terminals and shells.

**Comment by chrisbra** [comment]
does it show correcty if your force a `:redraw`?
