### ISSUE TITLE
YAML indent question

### ISSUE THREAD

**Issue by 097115** [vim/vim#11944]
Let's say we have the following YAML file:

    lorem:
      - ipsum: dolor
        sit:
          - amet
          - blandit

Now, let's open it with the command 

    vi -u NONE --clean 

...then place the cursor on the 4th line and press `o`:

![](https://i.imgur.com/Y5bGT9N.png)

...which is a bit disappointing since I have to go two spaces back to insert a new item.

Now let's open it with the command

    vi -u NONE +'filetype plugin indent on' +'set autoindent' +'set smartindent'

...and then repeat the same operation, first `:4`, then `o`:

![](https://i.imgur.com/I0mDUES.png)

And that's something very different now, right? :)

The question is, why?

---

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Feb  3 2023 21:45:15)
Included patches: 1-1276

**Comment by matveyt** [comment]
>The question is, why?

Because `:filetype on` only applies to files that were read **afterwards**.

**Comment by 097115** [comment]
Ah! You are right, @matveyt, thanks. 

So, it just my testing was faulty, and this [additional] indenting when entering list items is OK and suits everybody, I guess?

**Comment by matveyt** [comment]
That's a feature. If you type "minus" the line will be dedented automatically. See `:help indentkeys-format`.

**Comment by 097115** [comment]
Damn! Used auto de-indentation so many times and somehow never thought it will also work here.

Thanks :)
