### ISSUE TITLE
Commit be4e016 broke syntax highlighting in bash scripts

### ISSUE THREAD

**Issue by lindhobe** [vim/vim#11953]
### Steps to reproduce

Updates to runtime/syntax/sh.vim (in commit be4e016) broke syntax highlighting of bash scripts on my system.  The following section of code excerpt is rendered completely in magenta beginning with the "if" statement:

```
#! /usr/bin/bash
# vim: set filetype=bash:

# set paths
export PATH='/usr/local/scripts:/usr/local/bin:/usr/local/sbin'
export PATH="${PATH}:/usr/lib/jvm/default-java/bin:/usr/local/schily/bin"
if [ -L /bin ]; then
  export PATH="${PATH}:/usr/sbin:/usr/bin:/usr/games"
else
  export PATH="${PATH}:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games"
fi
export INFOPATH='/usr/local/share/info:/usr/share/info'
export MANPATH='/usr/local/share/man:/usr/lib/jvm/java-sun/man'
export MANPATH="${MANPATH}:/usr/local/schily/share/man:/usr/share/man"
```

If I delete the blank line between lines 2 and 4, though, it renders correctly.

### Expected behaviour

Correct syntax highlighting for bash files.

### Version of Vim

Runtime updates between 9.0.1274 and 9.0.1275

### Environment

Debian Testing
xterm-378
XTERM=xterm
bash-5.2.15

**Comment by lindhobe** [comment]
Plus a couple of screenshots:

BEFORE:
![before](https://user-images.githubusercontent.com/17262247/216843677-de29959f-2acb-4b38-9a68-3cb592fe8989.png)
AFTER:
![after](https://user-images.githubusercontent.com/17262247/216843724-c86f69c3-af32-4920-b181-558013823f82.png)

**Comment by lindhobe** [comment]
Ah, this is a duplicate of #11937.

**Comment by k-takata** [comment]
Closing as duplicate.
