### ISSUE TITLE
Unverified bug report on huntr.dev (pending since 22 Jan 2023)

### ISSUE THREAD

**Issue by soaarony** [vim/vim#11955]
Hi sir, I have made a bug report on huntr.dev. The report is unverified for the past 2 weeks. May I have a closure on it as I have one more bug report after this? 

link to the unverified bug report: https://huntr.dev/bounties/db7be8d6-6cb7-4ae5-9c4e-805423afa378/

Thank you so much!!

**Comment by dpelle** [comment]
You just need to be patient.  If a bug was reported, it won't be forgotten.
I can't myself access the link, which says "This report is not public".
If it's not a security issue (?) consider making it public, so other developers can investigate it.

**Comment by soaarony** [comment]
I see, my bad. I am afraid my report is forgotten or my report has any issues.  Thank you for replying!!

**Comment by brammool** [comment]
The issue is on my todo list.  I'm very busy at the moment and time is limited.

There is no point in having the issue both on huntr and on github, therefore closing this one.
