### ISSUE TITLE
Window screen gets wrong when a virtual text is placed on 'above' or 'below' on an empty line

### ISSUE THREAD

**Issue by rickhowe** [vim/vim#11959]
### Steps to reproduce

On the following window:

![bb](https://user-images.githubusercontent.com/3096934/217447929-b50fa632-0103-48bf-adb5-517dea2ff38a.png)

Run the following script to place `'---'` above and `'+++'` below on each line:
```
let vt = 'test'
call prop_type_delete(vt)
call prop_type_add(vt, {'highlight': 'ToDo'})
for ln in range(1, line('$'))
  call prop_add(ln, 0, {'type': vt, 'text': '---', 'text_align': 'above'})
  call prop_add(ln, 0, {'type': vt, 'text': '+++', 'text_align': 'below'})
endfor
```

![aa](https://user-images.githubusercontent.com/3096934/217447952-d0e3f80c-33b8-4955-b2d1-66096f5a0d43.png)

The empty lines on both line 2 and 4 are gone. Then the line number appears on the virtual text and the cursor appears out  of last line 5.

### Expected behaviour

The empty lines should be left displayed as well.

### Version of Vim

9.0.1291

### Environment

Windows 10

**Comment by rickhowe** [comment]
Thank you for your immediate fixing, but I still see some problem.

1. When &list is on,  eol ($) does not appear on the empty line but on the "above" virtual lines.

![33](https://user-images.githubusercontent.com/3096934/218292484-0261e3b9-0d8d-4b22-9a2d-8663fb1d0c1c.png)

2. If we do not use "below" but use "above" only, the screen looks OK, but the cursor can not move to line 3, 4, and 5.

![44](https://user-images.githubusercontent.com/3096934/218292487-d43e0ab0-4cd1-43bb-88f0-72ecfc32025a.png)

Then &list is set, the screen gets corrupted.

![55](https://user-images.githubusercontent.com/3096934/218292489-8ee5137b-7a64-4e19-bc5e-6abb536c221a.png)

**Comment by brammool** [comment]
I'll have a look at the other problems when I have time.

Note that this issue is already closed, adding more problems to it is confusing.
Next time please open a new issue, with reproduction steps.

**Comment by brammool** [comment]
Re-opening for the remaining problem mentioned.
