### ISSUE TITLE
Compatibility problems with some file names

### ISSUE THREAD

**Issue by A4-Tacks** [vim/vim#11962]
### Steps to reproduce

# Compatibility problems with some file names
- filename: '1V:0Lz0FEp]x)650x1am{r7$LOewq ~{6`#+ #E`OdfyjT;HJ>_<'\''Ua9F7Ah.{N1B4XEw#'\''[_C^6T3W^F&jE20)dU?LT&Q{dGwh~6E|&ZvA|ZwT*x['\''V,\\6XFSKh2bf-ha*f|L|DPg5-!!h5C dYpXhA~@KpvbOX0;STkFYA4F-m%@ IbU8ZS:bs.J-{"U.py'

### Expected behaviour

save file and save undofile

### Version of Vim

8.2.4919

### Environment

OS: Ubuntu 22.04
Shell: Bash-5.1.16

### Logs and stack traces

```shell
E828: 无法打开并写入撤销文件：/home/lrne/.vim/.undodir/%home%lrne%桌%File%Project%VimScript%MyVimConfig%vimscript%1V:0Lz0FEp]x)650x1am{r7$LOewq ~{6`#+#E`OdfyjT;HJ>_<'Ua9F7Ah.{N1B4XEw#'[_C^6T3W^F&jE20)dU?LT&Q{dGwh~6E|&ZvA|ZwT*x['V,\\6XFSKh2bf-ha*f|L|DPg5-!!h5CdYpXhA~@KpvbOX0;STkFYA4F-m%@ IbU8ZS:bs.J-{"U.py
```

**Comment by brammool** [comment]
The filename shown in github is messed up because it's interpreted as markdown.  Please give the shell command you use to open this file, or the edit command in Vim, literally (using three backticks).

You may also want to upgrade to a more recent version of Vim and try again.  8.2.4919 is quite old.

**Comment by A4-Tacks** [comment]
> The filename shown in github is messed up because it's interpreted as markdown. Please give the shell command you use to open this file, or the edit command in Vim, literally (using three backticks).
> 
> You may also want to upgrade to a more recent version of Vim and try again. 8.2.4919 is quite old.

ok
