### ISSUE TITLE
syntax/bibtex.vim: breaks if for example howpublished = {{ \$  }}

### ISSUE THREAD

**Issue by Konfekt** [vim/vim#1197]
The highlighting stops if an entry contains an escaped `$`, for example

``` tex
@Book{book
  title =        {book},
  year =         {2000},
  author =       {author}
  howpublished = {editor DM 72.00; \$ 34.30 (1981)}
}
```

**Comment by berndf** [comment]
Sorry, I was only now pointed to the correct fix which involves negative lookbehind (thanks @sga001!): https://github.com/neovim/neovim/issues/7324#issuecomment-332297370
I'll submit the pull request now.

**Comment by brammool** [comment]
fix was included
