### ISSUE TITLE
Bash/Sh Confused Syntax Highlighting reading .bashrc file

### ISSUE THREAD

**Issue by pellea72** [vim/vim#11977]
### Steps to reproduce

1. Compile and install latest master from git (as of this bug report).
2. Open .bashrc file (vim ~/.bashrc)
3. 
![image](https://user-images.githubusercontent.com/19319232/218314446-57385ebd-67e9-438f-8962-66ba4722f9f7.png)

### Expected behaviour

The latest version of runtime/sh.vim (https://github.com/vim/vim/commit/be4e01637e71c8d5095c33b9861fd70b41476732) breaks syntax highlighting, particularly with recognizing quoted text. It seems to be confused when quotes begin and end, and ends up treating code as quotes in some portions of the file. The previous version of runtime/sh.vim (https://github.com/vim/vim/commit/86b4816766d976a7ecd4403eca1f8bf6b4105800) works fine as far as I can tell.

I've mainly tested it on a .bashrc file, but it has similar issues in some other bash files.

Edit: Just to be sure, I've tested it in a few different terminal environments with the same result.

### Version of Vim

Master (v 9.0 with patches 1-1303)

### Environment

Linux debian-dell 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

**Comment by cecamp** [comment]
Hmm, perhaps you could rectify some things, too. Please provide a (preferably short) example of the issue, don't send an image -- send text so I can test with it and not have to spend a lot of time re-typing it, and be clear about where the problem is. Thanks!

**Comment by TAforever** [comment]
> Hmm, perhaps you could rectify some things, too. Please provide a (preferably short) example of the issue, don't send an image -- send text so I can test with it and not have to spend a lot of time re-typing it, and be clear about where the problem is. Thanks!


I can also confirm that there was some kind of syntax highlighting bug after updating vim today.

**Comment by agostonbarna** [comment]
I also ran into a similar issue with the last vim update: VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Feb 11 2023 11:15:25)
![image](https://user-images.githubusercontent.com/5561396/218324099-9eda85bf-f353-43a2-aa42-196b99a4a587.png)
This is how it looked with a previous VIM version: VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jan 12 2023 18:55:27)
![image](https://user-images.githubusercontent.com/5561396/218324307-538328cf-7712-47aa-b66e-e3572b710b53.png)

And the example code:
```sh
#!/usr/bin/env bash
# args: since (e.g: 2 months)

set -euo pipefail

worktree=$(git rev-parse --show-toplevel --show-prefix | paste -sd/ -)
cd "$worktree"

git log --format= --name-only --since "${*:-1970}" --relative \
| sort \
| uniq -cd \
| sort -nk1 \
| tail -n 50
```

**Comment by pellea72** [comment]
> Hmm, perhaps you could rectify some things, too. Please provide a (preferably short) example of the issue, don't send an image -- send text so I can test with it and not have to spend a lot of time re-typing it, and be clear about where the problem is. Thanks!

Sure. The file starts out with comments in blue as usual, then when the code starts, almost everything is colored violet regardless of syntax purpose (except for a couple of small bits like punctuation), even through another set of comments, which should have gone back to being blue. But aside from comments later being colored blue in some places, it looks like it mostly disregards syntax rules and colors vast swaths of things violet.

Below I've pasted a portion of the text of the .bashrc file followed by a marked up version showing where colors start and stop using XML style color /color tags.

```
---------------------------------------------
.bashrc snippet:

# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

-----------------------------

.bashrc snippet with <color> </color> tags:

<blue># ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything</blue>
<violet>case $- in
    *i*) <yellow>;;</yellow>
      *) <yellow>return;;</yellow>
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE<yellow>=</yellow><red>1000</red>
HISTFILESIZE<yellow>=</yellow><red>2000</red></violet>

<blue># check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.</blue>
<violet>shopt -s checkwinsize</violet>


```

**Comment by tobinjt** [comment]
Here's another example:

```
#!/bin/bash

set -e -f -u -o pipefail

update_one_dir() {
  if [[ ! -f ".pre-commit-config.yaml" ]]; then
    return
  fi
  pre-commit autoupdate
  if ! git check-local-copy-is-clean; then
    pre-commit run --all-files
    git commit -a -m 'Update hooks version.'
    git push
  fi
}

check-git-repos --pull_and_push "$(pwd)"
update_one_dir
```

Everything from line 9 (`pre-commit autoupdate`) through to line 17 (`update_one_dir`) is violet.  The syntax of each line is `shCmdSubRegion`, whereas in an earlier version it was `shFunctionOne` or empty.  In https://github.com/vim/vim/commit/be4e01637e71c8d5095c33b9861fd70b41476732#diff-650e28e4ad6a5c9241345580a7136ff18b5629f3b4910a5b5a455828bca5e517R338 I see this diff at line 336/338:

```
 syn region shCommandSub matchgroup=shCmdSubRegion start="\$(\ze[^(]"  skip='\\\\\|\\.' end=")"  contains=@shCommandSubList
 syn region shCommandSub matchgroup=shCmdSubRegion start="\$(\ze[^(]\|$"  skip='\\\\\|\\.' end=")"  contains=@shCommandSubList
```

Reverting that line returns highlighting to normal.

**Comment by pellea72** [comment]
> Here's another example:
> 
> ```
> #!/bin/bash
> 
> set -e -f -u -o pipefail
> 
> update_one_dir() {
>   if [[ ! -f ".pre-commit-config.yaml" ]]; then
>     return
>   fi
>   pre-commit autoupdate
>   if ! git check-local-copy-is-clean; then
>     pre-commit run --all-files
>     git commit -a -m 'Update hooks version.'
>     git push
>   fi
> }
> 
> check-git-repos --pull_and_push "$(pwd)"
> update_one_dir
> ```
> 
> Everything from line 9 (`pre-commit autoupdate`) through to line 17 (`update_one_dir`) is violet. The syntax of each line is `shCmdSubRegion`, whereas in an earlier version it was `shFunctionOne` or empty. In [be4e016#diff-650e28e4ad6a5c9241345580a7136ff18b5629f3b4910a5b5a455828bca5e517R338](https://github.com/vim/vim/commit/be4e01637e71c8d5095c33b9861fd70b41476732#diff-650e28e4ad6a5c9241345580a7136ff18b5629f3b4910a5b5a455828bca5e517R338) I see this diff at line 336/338:
> 
> ```
>  syn region shCommandSub matchgroup=shCmdSubRegion start="\$(\ze[^(]"  skip='\\\\\|\\.' end=")"  contains=@shCommandSubList
>  syn region shCommandSub matchgroup=shCmdSubRegion start="\$(\ze[^(]\|$"  skip='\\\\\|\\.' end=")"  contains=@shCommandSubList
> ```
> 
> Reverting that line returns highlighting to normal.

Good find. I meant to try reverting some of the changes, but I got sidetracked with some vimscript tutorials.

**Comment by k-takata** [comment]
Have you tried sh.vim version 207 from @cecamp's [website](http://www.drchip.org/astronaut/vim/index.html#SYNTAX_VIM)?

**Comment by pellea72** [comment]
> Have you tried sh.vim version 207 from @cecamp's [website](http://www.drchip.org/astronaut/vim/index.html#SYNTAX_VIM)?

I haven't tried it. But just putting the previous version of sh.vim into your home directory's .vim/syntax directory fixes the problem. Even doing that with the version of sh.vim that comes with Debian's vim works.

**Comment by KaspervdHeijden** [comment]
A simple script also fails to highlight properly.

```
#!/usr/bin/env sh

var="${1}";

if [ -z "${var}" ]; then
    echo 'empty var';
fi
```

![image](https://user-images.githubusercontent.com/20627978/218433483-257a01ec-0b1d-4e10-8709-8e65362f7c48.png)

**Comment by brammool** [comment]
@pellea72 please answer the question that @k-takata asked, we want to know if version 207 fixes this problem.
It's unlikely we would use a previous version if a newer version exists.

**Comment by h3xx** [comment]
> In [be4e016#diff-650e28e4ad6a5c9241345580a7136ff18b5629f3b4910a5b5a455828bca5e517R338](https://github.com/vim/vim/commit/be4e01637e71c8d5095c33b9861fd70b41476732#diff-650e28e4ad6a5c9241345580a7136ff18b5629f3b4910a5b5a455828bca5e517R338) I see this diff at line 336/338:
> 
> ```
>  syn region shCommandSub matchgroup=shCmdSubRegion start="\$(\ze[^(]"  skip='\\\\\|\\.' end=")"  contains=@shCommandSubList
>  syn region shCommandSub matchgroup=shCmdSubRegion start="\$(\ze[^(]\|$"  skip='\\\\\|\\.' end=")"  contains=@shCommandSubList
> ```
> 
> Reverting that line returns highlighting to normal.

Changing the `start="\$(\ze[^(]\|$"` to `start="\$(\ze[^(]\?"` fixes this issue as well, perhaps better than simply reverting the line.

| With current syntax\* | With line reverted | With my change
| - | - | -
| ![current code](https://user-images.githubusercontent.com/615684/220417393-b15a979c-69c4-4464-a5ed-45349926c192.png) | ![line reverted](https://user-images.githubusercontent.com/615684/220418175-c73209d9-4ae5-408c-92ca-05a92698ce97.png) | ![my change](https://user-images.githubusercontent.com/615684/220418595-ac44f002-85a5-4043-be6c-16de0bf36dea.png)

\*  as of cfce5cf542db20c7beba5b4211c0ae3305a64a43

Perhaps @cecamp would take this simple change instead of a revert.

Aside: Adding `hi def link shCmdSubRegion Error` helped me nail this down.

<details><summary>Here's the text of the script in the image</summary>

```sh
#!/bin/sh

case $- in
    *i*) ;;
    *) return;;
esac

# Comment

VAR=$(subshell)
VAR=$(
    multi-line
)
$( 
    multi-line
)
$(( arith ))
$((
    arith
))
```
</details>

**Comment by pellea72** [comment]
Today's update to runtime/sh.vim fixed it. Thanks for your efforts.
