### ISSUE TITLE
Python syntax don't highlight correctly numbers that includes `_`

### ISSUE THREAD

**Issue by vds2212** [vim/vim#11978]
### Steps to reproduce

1. Edit a python file that includes a number of the kind 1_024
2. The number is not highlighted as a number

### Expected behaviour

The number should be highlighted as a normal number (e.g. 1024)

Since Python 3.6 (23rd December 2016) number literals can includes `_`.
It seems that the Vim syntax highlighting doesn't support it natively.

### Version of Vim

Vim 9.0 trunk

### Environment

Operating System: Windows

**Comment by zvezdan** [comment]
There's already a pending change for this in PR #8033.
