### ISSUE TITLE
Forth/F# filetype detection gives up too early

### ISSUE THREAD

**Issue by jkotlinski** [vim/vim#11988]
Repro: open file "test.fs" with contents

    foo
    : bar ;

The file is incorrectly classified as F#.

It seems the problem is because filetype detection gives up after one line. I think it would make sense if a lot more lines were taken into account.

https://github.com/vim/vim/blob/f1dcd14fc5d4370476cd82895a4479ca2d252e54/runtime/autoload/dist/ft.vim#L310

**Comment by dkearns** [comment]
I have another small related fix I need to push so I'll take this one.

**Comment by jkotlinski** [comment]
That would be great! It is kind of annoying like it is now, because syntax high-lighting only kicks in for about 50% of my Forth files.

**Comment by dkearns** [comment]
@jkotlinski I assume you know how to override the detection and are just reporting the bug but if not see `:help filetype-overrule`.

It was intentionally limited to testing only the first line as the Forth comment and colon words easily match in the other languages of interest.  These matches can also happen early in the file.  E.g., F# is often formatted as

```F#
let square x
  : int = x * x
```

and in fixed source format Fortran `:` is often used as the continuation character

```Fortran
       REAL FOO,
      :     BAR
```

I had a quick look at the Forth files on my system and with the the header comments stripped it's going to take around 50 lines to detect with any reliability using colon definitions.

I'll see what I can come up with this week.

**Comment by jkotlinski** [comment]
I do not know if it helps, but here are the relevant heuristics from
linguist library for reference:

- extensions: ['.fs']
rules:
- language: Forth
pattern: '^(: |new-device)'
- language: 'F#'
pattern: '^\s*(#light|import|let|module|namespace|open|type)'
- language: GLSL
pattern: '^\s*(#version|precision|uniform|varying|vec[234])'
- language: Filterscript
pattern: '#include|#pragma\s+(rs|version)|__attribute__'

sön 19 feb. 2023 kl. 18:32 skrev Doug Kearns ***@***.***>:

**Comment by dkearns** [comment]
@jkotlinski, is it reasonable to assume that `*.fs` files are using the Gforth dialect or is its use more general?

I'm wondering if it's worth testing for SwiftForth and VFX block comments, for example.

**Comment by jkotlinski** [comment]
I would avoid assuming any particular dialect.
The standard words are described in
https://forth-standard.org/

In particular, the CORE wordset should be supported by most Forths.

fre 24 feb. 2023 kl. 18:10 skrev Doug Kearns ***@***.***>:

**Comment by dkearns** [comment]
Sorry I got sidetracked.

I'll post a WIP PR tomorrow when I'm back at the right machine and you can have a look.

**Comment by jkotlinski** [comment]
Does this look all right?

    diff --git a/ft.vim b/ft.vim
    index 01cde46..f590eb5 100644
    --- a/ft.vim
    +++ b/ft.vim
    @@ -277,14 +277,16 @@ export def FTfs()
       if exists("g:filetype_fs")
         exe "setf " .. g:filetype_fs
       else
    -    var line = getline(nextnonblank(1))
    -    # comments and colon definitions
    -    if line =~ '^\s*\.\=( ' || line =~ '^\s*\\G\= ' || line =~ '^\\$'
    -         \ || line =~ '^\s*: \S'
    -      setf forth
    -    else
    -      setf fsharp
    -    endif
    +    var n = 1
    +    while n < 100 && n <= line("$")
    +      # Forth comments and colon definitions
    +      if getline(n) =~ "^[:(\\\\] "
    +       setf forth
    +       return
    +      endif
    +      n += 1
    +    endwhile
    +    setf fsharp
       endif
     enddef

**Comment by dkearns** [comment]
Thanks, I still haven't found the time to dig my way out of my rabbit hole and finalize my effort.  I'd propose just including this now as it's obviously a significant improvement.  

I ran it against my test archive (about 50k files of F# and the same of Forth) and it seems to be missing about 5% of Forth but only picking up a handful of F# in error.

There's quite a lot of low hanging Forth fruit we can catch with a few more patterns. E.g., `:noname`, `include`, `require`, `[defined]`, `variable`, `constant`, `value`, `only forth` and indented colon definitions (with stack effect comments)

I tried a few approaches and was thinking we should test for both filetypes line by line, preferencing F#, and probably default to Forth.  F# is easier to match, as Forth can look like anything, and files that don't match the basic Forth and F# patterns are usually Forth.

E.g., The following incorrectly match as Forth but are easily matched earlier in the file as F#:

https://github.com/B2R2-org/B2R2/blob/master/src/RearEnd/Launcher/Program.fs#L39
https://github.com/fable-compiler/fable-react/blob/master/src/Fable.React/Fable.React.FunctionComponent.fs#L26

I also found that we really need to scan more than 100 lines and skip F#-style block comments.

**Comment by jkotlinski** [comment]
OK, I set up a pull request. Beginner question, any idea why I need to escape the `\` to `\\\\`? That's two more `\` than I expected.

**Comment by jkotlinski** [comment]
About best way to further improvements.
I would be cautious about matching F# patterns to determlne file type.
Since Forth lacks syntax, literally any F# file could be interpeted as
valid Forth.
That’s why feel its probably safer to match typical Forth patterns that do
not appear naturally in F#.

sön 2 apr. 2023 kl. 17:27 skrev Doug Kearns ***@***.***>:

**Comment by dkearns** [comment]
> Beginner question, any idea why I need to escape the `\` to `\\\\`? That's two more `\` than I expected.

The backslash at the end of the character class escapes the closing `]` so it needs to be doubled there to produce a literal backslash and each of those need to be doubled again because they appear in a double quoted string.

If you use single quotes the pattern becomes `'^[:(\\] '`or, if you move the backslash earlier in the character class you can use `'^[\:(] '`.  However, the backlash is used to introduce quite a number of escape sequences in character classes so it doesn't hurt to just double up to be sure, to be sure.
