### ISSUE TITLE
issues with defcompile and class methods

### ISSUE THREAD

**Issue by errael** [vim/vim#11984]
### Steps to reproduce

Source this script, `defcompile` does not compile the methods in `class C`
```
vim9script

class C
    def F(i: number): string
        return i
    enddef
endclass

defcompile

var o = C.new()
# defcompile o.F # <<<<<<<<<<< this works, seems unusual to require creating object
finish

var v = o.F(42) # <<<<<<<<<<<< without finish, compile error
```

### Expected behaviour

`defcompile` in the above script should produce an error.

### Other cases
```
defcompile C.StaticFunc # <<<<< this works
# following to compile all functions/methods in "class C"
defcompile C     # fails with: #1061: Cannot find function C
# following to compile C.F()
defcompile C.F     # fails with: E1337: Class member not found: F; E475: Invalid argument: C.F

```

### Version of Vim

9.0.1296

### Environment

ubuntu

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> Source this script, `defcompile` does not compile the methods in `class C`
> ```
> vim9script
> 
> class C
>     def F(i: number): string
>         return i
>     enddef
> endclass
> 
> defcompile
> 
> var o = C.new()
> # defcompile o.F # <<<<<<<<<<< this works, seems unusual to require creating object
> finish
> 
> var v = o.F(42) # <<<<<<<<<<<< without finish, compile error
> ```
> 
> ### Expected behaviour
> 
> `defcompile` in the above script should produce an error.

I think it is OK for :defcompile to only compile the functions at the
script level.  But there should be a way to compile the
functions/methods in a class.

A similar problem is with :disassemble, it doesn't take an argument for
a class function/method.

I'll at least make it possible to use an argument for a specific
class/method.  Later we can make ":defcompile ClassName" work as well.

> ### Other cases
>
> defcompile C.StaticFunc # <<<<< this works

Also an indication that "defcompile C.F" should work.

> # following to compile all functions/methods in "class C"
> defcompile C     # fails with: #1061: Cannot find function C

I want to make this work later.

> # following to compile C.F()
> defcompile C.F     # fails with: E1337: Class member not found: F; E475: Invalid argument: C.F

This should work after the patch I'm preparing.

-- 
You're as much use as a condom machine at the Vatican.
                  -- Rimmer to Holly in Red Dwarf 'Queeg'

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
