### ISSUE TITLE
The tab character ^I cannot be typed in the markdown file

### ISSUE THREAD

**Issue by scrawld** [vim/vim#11997]
### Steps to reproduce

No configuration file will also appear

1. Create a new markdown file `vim t.md`.
2. show invisible characters `:set list`
3. Enter INSERT mode and press the Tab key to enter a space

https://user-images.githubusercontent.com/48232670/218926089-f251d76a-2fa1-46f0-864b-db1509b8f71a.MOV

### Expected behaviour

Pressing Tab in other types of files is a tab character ^I, and in .md files I hope that the input is a tab character ^I

### Version of Vim

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Feb 14 2023 11:31:04) macOS version - arm64 Included patches: 1-1307 Compiled by xxx@163.com Huge version without GUI.  Features included (+) or not (-): +acl               +cindent           +cursorshape       +file_in_path      +job               +menu              +mouse_urxvt       +popupwin          +signs             -tag_any_white     +user_commands     +windows +arabic            -clientserver      +dialog_con        +find_in_path      +jumplist          +mksession         +mouse_xterm       +postscript        +smartindent       -tcl               +vartabs           +writebackup +autocmd           +clipboard         +diff              +float             +keymap            +modify_fname      +multi_byte        +printer           -sodium            +termguicolors     +vertsplit         -X11 +autochdir         +cmdline_compl     +digraphs          +folding           +lambda            +mouse             +multi_lang        +profile           +sound             +terminal          +vim9script        -xfontset -autoservername    +cmdline_hist      -dnd               -footer            +langmap           -mouseshape        -mzscheme          -python            +spell             +terminfo          +viminfo           -xim -balloon_eval      +cmdline_info      -ebcdic            +fork()            +libcall           +mouse_dec         -netbeans_intg     +python3           +startuptime       +termresponse      +virtualedit       -xpm +balloon_eval_term +comments          +emacs_tags        -gettext           +linebreak         -mouse_gpm         +num64             +quickfix          +statusline        +textobjects       +visual            -xsmp -browse            +conceal           +eval              -hangul_input      +lispindent        -mouse_jsbterm     +packages          +reltime           -sun_workshop      +textprop          +visualextra       -xterm_clipboard ++builtin_terms    +cryptv            +ex_extra          +iconv             +listcmds          +mouse_netterm     +path_extra        +rightleft         +syntax            +timers            +vreplace          -xterm_save +byte_offset       +cscope            +extra_search      +insert_expand     +localmap          +mouse_sgr         -perl              -ruby              +tag_binary        +title             +wildignore +channel           +cursorbind        -farsi             +ipv6              -lua               -mouse_sysmouse    +persistent_undo   +scrollbind        -tag_old_static    -toolbar           +wildmenu    system vimrc file: "$VIM/vimrc"      user vimrc file: "$HOME/.vimrc"  2nd user vimrc file: "~/.vim/vimrc"       user exrc file: "$HOME/.exrc"        defaults file: "$VIMRUNTIME/defaults.vim"   fall-back for $VIM: "/usr/local/share/vim" Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DMACOS_X -DMACOS_X_DARWIN -g -O2 -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 Linking: gcc -L/usr/local/lib -o vim -lm -lncurses -liconv -framework AppKit -L/opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/lib/python3.10/config-3.10-darwin -lpython3.10 -framework CoreFoundation

### Environment

macOS Ventura 13.0.1

It also appears in the linux environment

**Comment by k-takata** [comment]
If the 'expandtab' option is set, tab will be expanded to spaces.
You can use `:verbose set expandtab?` to check where it is set.

**Comment by scrawld** [comment]
expandtab
        Last set from /usr/local/share/vim/vim90/ftplugin/markdown.vim line 26

**Comment by scrawld** [comment]
expandtab  Last set from /usr/local/share/vim/vim90/ftplugin/markdown.vim line 26

But this is not what I set, how can I override this configuration

**Comment by k-takata** [comment]
https://github.com/vim/vim/blob/fdbd14e89207dca95549f298ee468793da852086/runtime/ftplugin/markdown.vim#L25-L27
Adding `let g:markdown_recommended_style = 0` in your .vimrc may disable the setting.

`:help ftplugin-overrule` describes more generic ways to overrule the settings of ftplugins.

**Comment by scrawld** [comment]
ok thanks
