### ISSUE TITLE
Function keys not working properly in kitty terminal

### ISSUE THREAD

**Issue by SolsticeSpectrum** [vim/vim#11998]
### Steps to reproduce

Get kitty terminal and setup some keybinds

```
" NERDTree
nmap <F6> :NERDTreeToggle<CR>

" Tagbar
nmap <F7> :TagbarToggle<CR>

" Minimap
nmap <F8> :MinimapToggle<CR
```

### Expected behaviour

The binded function keys should work, they do in **gvim**
This only applies to F5-F12

I reported this to kitty https://github.com/kovidgoyal/kitty/issues/6020
and was told that this has something to do with the new kitty protocol support in **vim**

### Version of Vim

9.0.1182

### Environment

**Operating system:** Arch
**Terminal:** kitty
**Value of $TERM:** xterm-kitty
**Shell:** bash

**Comment by DarkReaper231** [comment]
It seems to be fixed in latest version, closing
