### ISSUE TITLE
Vim hangs and segfaults with a scratch PHP buffer

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#1200]
I can cause erratic behaviour using terminal Vim 8.0p46 on macOS 10.12.1, as follows:

```
vim -N -u NONE
filetype on
filetype plugin on
vnew +setlocal\ buftype=nofile\ bufhidden=wipe\ noswapfile
set ft=php
```

Then start typing: `i<?php<cr>for<c-x><c-o>` (the first `<` is a literal less-than character). If that is not enough, try typing `<c-n>`, `<c-p>`, and/or `<tab>` a few times, and if that is not enough yet, clear the buffer, `set modifiable` if necessary (for some reason, sometimes the buffer becomes unmodifiable) and repeat. The crash does not seem deterministic, so you may have to try a few times.

Vim sometimes just freezes and some other times hangs with `Vim: Caught deadly signal SEGV`. In both cases, the CPU usage skyrockets and I have to kill the process myself.

Note that I have recompiled Vim after upgrading to macOS 10.12.1, to be sure that the bug does not depend on some library updates in macOS.

Vim version:

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 26 2016 21:07:47)
MacOS X (unix) version
Included patches: 1-46
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +conceal         +file_in_path    +libcall         +mouse_sgr       +profile         +tag_old_static  +viminfo
+arabic          +cryptv          +find_in_path    +linebreak       -mouse_sysmouse  +python          -tag_any_white   +vreplace
+autocmd         +cscope          +float           +lispindent      +mouse_urxvt     -python3         -tcl             +wildignore
-balloon_eval    +cursorbind      +folding         +listcmds        +mouse_xterm     +quickfix        +termguicolors   +wildmenu
-browse          +cursorshape     -footer          +localmap        +multi_byte      +reltime         +terminfo        +windows
++builtin_terms  +dialog_con      +fork()          +lua             +multi_lang      +rightleft       +termresponse    +writebackup
+byte_offset     +diff            -gettext         +menu            -mzscheme        +ruby            +textobjects     -X11
+channel         +digraphs        -hangul_input    +mksession       +netbeans_intg   +scrollbind      +timers          -xfontset
+cindent         -dnd             +iconv           +modify_fname    +num64           +signs           +title           -xim
-clientserver    -ebcdic          +insert_expand   +mouse           +packages        +smartindent     -toolbar         -xpm
+clipboard       +emacs_tags      +job             -mouseshape      +path_extra      +startuptime     +user_commands   -xsmp
+cmdline_compl   +eval            +jumplist        +mouse_dec       +perl            +statusline      +vertsplit       -xterm_clipboard
+cmdline_hist    +ex_extra        +keymap          -mouse_gpm       +persistent_undo -sun_workshop    +virtualedit     -xterm_save
+cmdline_info    +extra_search    +lambda          -mouse_jsbterm   +postscript      +syntax          +visual
+comments        +farsi           +langmap         +mouse_netterm   +printer         +tag_binary      +visualextra
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -L/usr/local/lib  -L/usr/local/lib -o vim        -lm  -lncurses -liconv -framework Cocoa  -pagezero_size 10000 -image_ba
se 100000000 -L/usr/local/lib -lluajit-5.1 -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -F/usr/local
/opt/python/Frameworks -framework Python   -lruby.2.0.0 -lobjc
```

**Comment by lifepillar** [comment]
I've just got a segfault with process termination, so I was able to capture a crash dump: https://gist.github.com/lifepillar/256eb6f63785ad1a656971634f2e259b

**Comment by chrisbra** [comment]
Does that only happen with an unnamed buffer with  `buftype=nofile\ bufhidden=wipe\ noswapfile` set? I can see funny output in that case, which seems to be the content of the preview window leaking through into the scratch buffer. Also this explains why the buffer is suddenly set nomodifiable. A workaround to that problem is, to always set a buffer name.

However, I haven't experienced a hung or a segfault.
Can you check, if this also happens, when you disable preview windows via `:set cot=menu`?
And unfortunately, the Mac OS crash dump does not really look helpful (at least for me)

**Comment by lifepillar** [comment]
I have tried for a few minutes, but all is ok if I either set a buffer name or set `cot=menu`. In a scratch buffer and with preview on, I can typically crash Vim in 10-20 seconds (pressing the `<tab>` key seems especially nefarious).

**Comment by chrisbra** [comment]
If that is really the case, I wonder if we can't just get rid of those lines https://github.com/vim/vim/blob/master/src/popupmnu.c#L585-L593

I could prepare a patch.

**Comment by vim-ml** [comment]
Hi ChrisBra, Lifepillar and list,

2016-10-27(Thu) 5:19:43 UTC+9 Christian Brabandt:

> If that is really the case, I wonder if we can't just get rid of those lines https://github.com/vim/vim/blob/master/src/popupmnu.c#L585-L593
> 
> I could prepare a patch.

## How about an attached patch?

Best regards,Hirohito Higashi (a.k.a. h_east)

**Comment by vim-ml** [comment]
Hirohito Higashi wrote:

> Hi ChrisBra, Lifepillar and list,
> 
> 2016-10-27(Thu) 5:19:43 UTC+9 Christian Brabandt:
> 
> > If that is really the case, I wonder if we can't just get rid of those lines https://github.com/vim/vim/blob/master/src/popupmnu.c#L585-L593

That means we keep adding buffers, even when the current buffer could be
re-used.

> > I could prepare a patch.
> 
> How about an attached patch?

I think we should at least check if prepare_tagpreview() split the
window.  If it did then we should call do_ecmd().

For extra safety we can check if the buffer has only one window.

## 

SECOND SOLDIER: It could be carried by an African swallow!
FIRST SOLDIER:  Oh  yes! An African swallow maybe ... but not a European
                swallow. that's my point.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///
