### ISSUE TITLE
another problem related to 'above' and 'below' virtual text

### ISSUE THREAD

**Issue by rickhowe** [vim/vim#12004]
### Steps to reproduce

I still see another problem, related to: https://github.com/vim/vim/issues/11959#issuecomment-1427589736

1. `cursorline` is displayed on both 'above' and 'below' virtual lines as well as actual one.
2. `colorcolumn` is displayed 'above' virtual line, not on actual one.

![66](https://user-images.githubusercontent.com/3096934/219374484-97b4430c-9fad-4bb6-87be-15b0b5ccf861.png)

3. `number` and `relativenumber` are on and cursor is moved line 5 to line 1, the number is not properly redrawn.

![77](https://user-images.githubusercontent.com/3096934/219378850-40883c6f-6a28-46d2-846e-4b329b243e92.png)

### Expected behaviour

1. `cursorline` is not displayed above and below virtual lines. 
2. `colorcolumn` is not displayed 'above' virtual line.
3.  the number is properly redrawn.

### Version of Vim

9.0.1313

### Environment

Windows 10

**Comment by rickhowe** [comment]
I noticed another problem. When an line includes non-ASCII character and "below" virtual line is drawn, screen looks OK but cursor can not be moved properly.

Left window is "above" and cursor can be moved to all lines. No problem.
Right window is "below" and cursor can NOT be correctly moved to line 2 and 3.
In this case, 0xA9 copyright sign is used but problem happens on other multibyte character as well.

![zz](https://user-images.githubusercontent.com/3096934/219943387-8052ce46-11d7-4009-985d-b581b14812f5.png)

**Comment by brammool** [comment]
Please use a separate issue for each problem.   Otherwise it is very hard to keep track of what has been fixed and what hasn't.

That 'cursorline' also highlights the "above" and "below" lines might be OK.  It also highlights the space after the text.

I'll see how to fix 'colorcolumn'.

**Comment by brammool** [comment]
Problem with multi-byte character fixed with patch 9.0.1327

**Comment by rickhowe** [comment]
Thank you for your quick fix and sorry for your confusion. I found all fixed except one. I will post it on another issue.
