### ISSUE TITLE
Request for more documentation of autocmd's {aupat} field.

### ISSUE THREAD

**Issue by anakimluke** [vim/vim#12011]
There's a behavior of `autocmd` I stumbled upon that is not well documented, specifically the `{aupat}` field when using `CmdLineEnter` as `{event}`.

For example, this autocommand accepts any `cmdwin-char` (`:`, `>`, `/`, `?`, `=`, `@`, `-`) in the `{aupat}` field:
 `autocmd! CmdLineEnter :,/ echo "hello world"`.

It's not clear in the documentation of autocommands, `CmdLineEnter`, `{aupat}` and `<afile>`(referenced in the `CmdLineEnter` documentation) that this feature exists.

In my case, I stumbled upon this feature in a web page and went on to read the manual to see where I'd missed it. I read everything I could about `{aupat}` and `<afile>` but it was only after reading the section for `cmdwin-char` one more time that I also read a bit of the preceding text and found a *similar* example:
```
Two autocommand events are used: CmdwinEnter and CmdwinLeave.  You can use
the Cmdwin events to do settings specifically for the command-line window.
Be careful not to cause side effects!
Example:
    :au CmdwinEnter :  let b:cpt_save = &cpt | set cpt=.
    :au CmdwinLeave :  let &cpt = b:cpt_save
This sets 'complete' to use completion in the current window for i_CTRL-N.
Another example:
    :au CmdwinEnter [/?]  startinsert
This will make Vim start in Insert mode in the command-line window.
```

So, it is rather difficult for a user to learn about this feature by reading the manual.

**Comment by brammool** [comment]
> There's a behavior of `autocmd` I stumbled upon that is not well
> documented, specifically the `{aupat}` field when using `CmdLineEnter`
> as `{event}`.
> 
> For example, this autocommand accepts any `cmdwin-char` (`:`, `>`, `/`, `?`, `=`, `@`, `-`) in the `{aupat}` field:
>  `autocmd! CmdLineEnter :,/ echo "hello world"`.
> 
> It's not clear in the documentation of autocommands, `CmdLineEnter`,
> `{aupat}` and `<afile>`(referenced in the `CmdLineEnter`
> documentation) that this feature exists.

The first paragraph of ":help {aupat}" explains the meaning of a comma.
Your example is equivalent to using these two commands:
   autocmd! CmdLineEnter : echo "hello world
   autocmd  CmdLineEnter / echo "hello world

The help for CmdlineEnter mentions the type of the command line used for
the file name, which is what the pattern is matched against.  Perhaps
this is not clear enough?


-- 
hundred-and-one symptoms of being an internet addict:
136. You decide to stay in a low-paying job teaching just for the
     free Internet access.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by anakimluke** [comment]
Yeah, the comma separation is very clearly explained. The problem really is that the docs don't mention that can use `cmdwin-char`s in the `{aupat}` field. They only mention that `<afile>` will be bound to the corresponding `cmdwin-char` character.  The best description I found is from the Cmd**Win**Enter from the snippet above, and it's a bit tricky to get to.

Following the same phrasing as the docs for the other events, I think adding something like this to `CmdlineEnter`(and family) should suffice.

```
The pattern is matched against the character representing the type of command-line entered.
```

So putting it together would be like:
```
                            CmdlineEnter
CmdlineEnter            After moving the cursor to the command line,
                where the user can type a command or search
                string; including non-interactive use of ":"
                in a mapping, but not when using <Cmd>.
                The pattern is matched against the character
                representing the type of command-line entered.
                <afile> is set to a single character,
                indicating the type of command-line.
                cmdwin-char
```

**Comment by brammool** [comment]
I'll add the remark in the help for CmdlineEnter.
