### ISSUE TITLE
t_Co=256 by default

### ISSUE THREAD

**Issue by lesorubshayan** [vim/vim#12017]
I use to use git mergetool(vim). One thing I annoyed is highlight. Because of it some text was not displayed(turns out it had the same color as foreground). As a workaround I found solution in internet that "disabled" all highlighting making my text white(bold sometimes) and foreground black. Some time ago browsing vim github issues(if I remember right) I saw t_Co=256 in vimrc(maybe) that borned idea in my head that it could solve git mergetool highlighting. Today I tried :set t_Co=256 and it did the trick. That's cool and I can make some explanation why it don't work by default(minimal as possible) but if it would be turned on by default will it hurt old terminals? At least for me I am angry. Because this finding was miracle and I don't want the others to struggle with git mergetool
and also I would be quite happier to not type it everytime I do rebase...
@brammool can you explain why this option is not by default?

**Comment by brammool** [comment]
> I use to use git mergetool(vim). One thing I annoyed is highlight.
> Because of it some text was not displayed(turns out it had the same
> color as foreground). As a workaround I found solution in internet that
> "disabled" all highlighting making my text white(bold sometimes) and
> foreground black.

That should be a problem with the colorscheme.  I have no idea why this
would happen with mergetool, perhaps it depends on how Vim is started
then.  I also wonder how you disable all highlighting.

> Some time ago browsing vim github issues(if I remember
> right) I saw t_Co=256 in vimrc(maybe) that borned idea in my head that
> it could solve git mergetool highlighting. Today I tried :set t_Co=256
> and it did the trick. That's cool and I can make some explanation why it
> don't work by default(minimal as possible) but if it would be turned on
> by default will it hurt old terminals? At least for me I am angry.
> Because this finding was miracle and I don't want the others to struggle
> with git mergetool
> and also I would be quite happier to not type it everytime I do rebase...
> @brammool can you explain why this option is not by default?

I very much doubt the value "256" matters.  Have you tried setting it to
"16"?  Changing the value may trigger reloading the colors and it's very
well possible that fixes the problem you experience.  You could also try
using a :colorscheme command.

-- 
hundred-and-one symptoms of being an internet addict:
144. You eagerly await the update of the "Cool Site of the Day."

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
