### ISSUE TITLE
An :inoremap mapping preventing abbreviation expansion is undocumented

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#12016]
When using the following mapping:
```vim
:inoremap <C-C> <Esc>
```

Pressing `<C-C>` in Insert mode doesn't expand abbreviations, which may be unexpected, and this behavior doesn't seem documented.

It probably isn't worthy to change the current behavior, as the problem can be solved by adding `<C-]>` before the `<Esc>`:
```vim
:inoremap <C-C> <C-]><Esc>
```

I guess this can also be documented somewhere.

**Comment by brammool** [comment]
> When using the following mapping:
> ```vim
> :inoremap <C-C> <Esc>
> ```
> 
> Pressing `<C-C>` in Insert mode doesn't expand abbreviations, which
> may be unexpected, and this behavior doesn't seem documented.

It is, in insert.txt:

CTRL-C		Quit insert mode, go back to Normal mode.  Do not check for
		abbreviations.  Does not trigger the |InsertLeave| autocommand
		event.


> It probably isn't worthy to change the current behavior, as the
> problem can be solved by adding `<C-]>` before the `<Esc>`:
> ```vim
> :inoremap <C-C> <C-]><Esc>
> ```
> 
> I guess this can also be documented somewhere.

The use of CTRL-] to expand an abbreviation is documented.  This
specific combination with a mapping is unusual. I would also not want to
encourage users to use CTRL-C to exit Insert mode.  CTRL-C is really
meant for aborting, having it apply an abbreviation is the opposite of
what I would expect.

-- 
hundred-and-one symptoms of being an internet addict:
142. You dream about creating the world's greatest web site.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by zeertzjq** [comment]
It seems that this behavior came from [patch 6.2.418](https://github.com/vim/vim-history/commit/48c458fc3034f4a94b4d7c4df9abbc53daf1442d)
