### ISSUE TITLE
[vim9script] Access to nested object inside function raises `E715: Dictionary required`

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#12024]
### Steps to reproduce

Possibly related to https://github.com/vim/vim/issues/11822.

Source this script:

```vim
vim9script

class Context
  public this.state: dict<any> = {}
endclass

class Metadata
  this.value = 0
endclass

var ctx = Context.new()
ctx.state["meta"] = Metadata.new(1)

const foo = ctx.state.meta.value  # OK

def F()
  const bar = ctx.state.meta.value
enddef

F() # ERROR: E715
```

I have found two workarounds for the problem above. Either of the following will work:

```vim
def AsMetadata(obj: Metadata): Metadata
  return obj
enddef

def F()
  const bar = AsMetadata(ctx.state.meta).value
  echo bar
enddef

F() # OK
```

Or:

```vim
def F()
  const meta: Metadata = ctx.state.meta
  const bar: number = meta.value
enddef

F() # OK
```

### Expected behaviour

The nested access to an object should work also inside a function.

### Version of Vim

9.0.1322

### Environment

macOS 13.2
Apple Terminal
xterm-256color
ZSH 5.8.1

**Comment by lifepillar** [comment]
In https://github.com/vim/vim/issues/11822 it was mentioned that this is complicated to fix. On a second thought, and considering that the second workaround I have suggested above is perfectly reasonable, I think that raising an error is fine if there is no information on the nested object's type at runtime (although it is a bit puzzling that no error is raised outside of a function).

It would be nice, however, if the error message were more informative. Or, at least, the help file could be expanded to document the circumstances in which type annotations such as above are mandatory.

**Comment by brammool** [comment]
> In https://github.com/vim/vim/issues/11822 it was mentioned that this
> is complicated to fix. On a second thought, and considering that the
> second workaround I have suggested above is perfectly reasonable, I
> think that raising an error is fine if there is no information on the
> nested object's type at runtime (although it is a bit puzzling that no
> error is raised outside of a function).

Why would there be no information at runtime?  The value always includes
the type, see "struct typval_S" in src/structs.h.

> It would be nice, however, if the error message were more informative.
> Or, at least, the help file could be expanded to document the
> circumstances in which type annotations such as above are mandatory.

Hopefully we can make it work as one expects, instead of giving a rather
hard to understand explanation of why it works differently.

-- 
hundred-and-one symptoms of being an internet addict:
21. Your dog has its own home page.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by errael** [comment]
Recently opened #13120 and wondering if it had any relationship to this issue. It doesn't seem to. BUT...

The example point out a regression, 

using 9.0.1910, running the example 
```
line   12:
E18: Unexpected characters in :let
```

which has workaround of
```
var d = ctx.state
d["meta"] = Metadata.new(1)
```

**Comment by errael** [comment]
There's a third workaround to the original problem
```
def F()
  const bar = (<Metadata>ctx.state.meta).value
enddef
```

**Comment by lifepillar** [comment]
>There's a third workaround to the original problem

Is the `<TYPE>` syntax documented anywherre?

**Comment by errael** [comment]
`:help <type-casting>`
