### ISSUE TITLE
[vim9script] Weird `class X not found on interface X` error

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#12023]
### Steps to reproduce

To reproduce, source this script:

```vim
vim9script

class Parent
  public this.value = 0
endclass

def Test_get_parent_member()
  var parent = Parent.new(9)
  assert_equal(9, parent.value)
enddef

class Child extends Parent
endclass

Test_get_parent_member()
```

Running the above script results in `class Parent not found on interface Parent`. If the definition of the `Child` class is removed, then the code runs fine.

### Expected behaviour

The code should run fine and the test should not fail.

### Version of Vim

9.0.1321

### Environment

macOS 13.2
Apple Terminal
xterm-256color
ZSH 5.8.1

**Comment by yegappan** [comment]
I think this issue is fixed by https://github.com/vim/vim/commit/74cc13cc402fa4df9033fbbc0643b1b403525950.  Can you try to reproduce this issue with the latest Vim version?

**Comment by lifepillar** [comment]
Thanks, indeed the issue appears to be fixed!
