### ISSUE TITLE
[vim9script] Reloading autoload script may raise errors

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#12025]
### Steps to reproduce

1. `mkdir -p ~/.vim/pack/test/start/foobar/autoload`
2. `vim --clean ~/.vim/pack/test/start/foobar/autoload/foo.vim`. Put with the following content in the script:

```vim
vim9script
export const x = 1
```

3. Save and source twice:

```vim
:w
:so%
:so%
```

The first time the script is sourced normally, but the second time `E995: Cannot modify existing variable` is raised.

This seems to happen only for scripts in `autoload` directories. 

### Expected behaviour

An autoload script should be sourced repeatedly without errors.

### Version of Vim

9.0.1325

### Environment

macOS 13.2
Apple Terminal
xterm-256color
ZSH 5.8.1

**Comment by brammool** [comment]
autoload scripts are really intended to be loaded only once.  I can understand that when you are developing a plugin you might want to source a script again after making changes, but the effect is largely unpredictable.  And it will most likely work different from when the script is sourced only once.
The current behavior is optimized for normal use, and I think that is the right thing to do.  A plugin developer may have to restart Vim, which is not really a big price to pay.  It is needed anyway to try out what happens for the user.
