### ISSUE TITLE
What is guisp?

### ISSUE THREAD

**Issue by barrientosvctor** [vim/vim#12022]
When I use the `:highlight <highlight_group>` command, I seen that there's a "**guisp**" but I don't know what "**guisp**" modifies in the vim syntax highlighting. I would like to know what is "**guisp**" and what it modifies in the code.

**Comment by bfrg** [comment]
This is explained under `:help highlight-guisp`:

https://github.com/vim/vim/blob/2c1c803c7e0cc356dd55a2cd49fbffbbf7db766e/runtime/doc/syntax.txt#L5279-L5290
