### ISSUE TITLE
cpp syntax highlighting bug

### ISSUE THREAD

**Issue by bfrg** [vim/vim#1202]
When the C++ keywords 'public', 'private', and 'protected' are indented, the syntax highlighting looks different compared to unindented. The highlighting group changes from Statement to Label (see screenshot below).
The following lines (line 399, 400 in `c.vim`) cause this behavior:

``` vim
syn match   cUserCont   display "^\s*\I\i*\s*:$" contains=@cLabelGroup
syn match   cUserCont   display ";\s*\I\i*\s*:$" contains=@cLabelGroup
```

Adding `\zs` to each line seems to solve the problem w/o breaking anything else:

``` vim
syn match   cUserCont   display "^\s*\zs\I\i*\s*:$" contains=@cLabelGroup
syn match   cUserCont   display ";\s*\zs\I\i*\s*:$" contains=@cLabelGroup
```

This behavior is not noticeable with most colorschemes since most colorschemes define the same colors for both Label and Statement.

Colorscheme in screenshot is [Molokai](https://github.com/tomasr/molokai).
![nhpgdk1](https://cloud.githubusercontent.com/assets/6266600/19753929/313e16c4-9c09-11e6-93f6-ff627522ee0a.png)

**Comment by mattn** [comment]
@brammool This is a patch for syntax/c.vim, syntax/cpp.vim.

https://gist.github.com/mattn/5525f936c98decf7560551000db9e7c4

See https://github.com/vim-jp/vim-cpp/pull/40 https://github.com/vim-jp/vim-cpp/pull/39 https://github.com/vim-jp/vim-cpp/issues/41 . And this will close this.
