### ISSUE TITLE
Undocumented (possibly incorrect) behavior for Virtual Replace mode

### ISSUE THREAD

**Issue by pierreganty** [vim/vim#12045]
### Steps to reproduce

Type `gr<C-o>` or `gr<C-g>` from Normal mode. It enters Virtual Replace mode( same as if we had typed `gR`).

### Expected behaviour

I am not claiming the behavior is wrong. However I could not find documentation for the behavior.
Asking on the vim IRC channel I got the following input from @puremourning :
![bug-vim](https://user-images.githubusercontent.com/2111160/220565810-ff3b5b39-f681-475d-8097-2afa4335be39.png)

### Version of Vim

9.0

### Environment

Macs OS 13.2 on terminal.app, zsh

**Comment by puremourning** [comment]
Bram please forgive my flippancy on IRC, I wasn't expecting my comments to be posted here verbatim.

**Comment by pierreganty** [comment]
@puremourning sorry about that.

**Comment by brammool** [comment]
Well, the help for "gr" says that you are supposed to type a character, but you type something that is a command in Insert mode.  I can try to fix it anyway.

**Comment by pierreganty** [comment]
For the record, the patch fixes the case `gr<C-o>` but it does not fix `gr<C-g>` which still allows to get in Virtual Replace Mode.
