### ISSUE TITLE
Feature request: Please provide an AppImage for gVim

### ISSUE THREAD

**Issue by fusion809** [vim/vim#1204]
Hi,

I'd like to request that yas provide an AppImage for gVim. AppImages (https://appimage.org) are a type of cross-distribution packaging format that need no special installed programs to be run. 

Thanks for your time,
Brenton

**Comment by probonopd** [comment]
Would certainly be useful for an application like gVim to be available in a portable format that runs everywhere, without the need for installation, compilation, or complication :+1:

**Comment by probonopd** [comment]
Since the vim project does [continuous builds on Travis CI](https://travis-ci.org/vim/vim) already, it would be especially easy to provide AppImages of these builds:

[Real-world examples](https://github.com/search?utf8=%E2%9C%93&q=%22Package+the+binaries+built+on+Travis-CI+as+an+AppImage%22&type=Code&ref=searchresults)

**Comment by chrisbra** [comment]
If I understand correctly, we would need to package the language libraries together with a vim appimage, right?

**Comment by probonopd** [comment]
@chrisbra first you would need to decide what you target systems are. A reasonable choice imho would be LTS-1 or LTS-2 versions of Ubuntu, Fedora, CentOS, openSUSE and debian (trusty being a pragmatic choice). Then you would need to bundle everything that cannot be expected to be part of these systems and/or subsequent versions of them. In practice, this means to bundle everything **but** [common system libraries](https://github.com/probonopd/AppImages/blob/master/excludelist).

**Comment by fusion809** [comment]
Wouldn't recommend using Fedora as it's only supported for 13 months post-release and tends to include fairly recent packages.

**Comment by probonopd** [comment]
True. The oldest system on which it still builds is the best for compatibility.

**Comment by chrisbra** [comment]
I have created a simple appimage [here](https://github.com/chrisbra/vim/tree/appimage) (Branch appimage). It build a simple image (e.g. this [one](https://transfer.sh/107Fnv/gvim-git689d7ba-glibc2.15-x86-64.appimage)) using the travis-ci scripts as documented [here](https://github.com/probonopd/AppImageKit/wiki/Creating-AppImages).

However gvim does not display any fonts and I don't know how to handle this. @probonopd can you give me some advice here? You seem to know appimage really well, so I hope you know the problem I am running into.

Also I am seeing this warning when starting up:

> /bin/bash: ./lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /bin/bash)

and I don't know how to handle this.

**Comment by probonopd** [comment]
@chrisbra https://bintray.com/fusion809/AppImages/gvim doesn't work as well?

**Comment by chrisbra** [comment]
no that works

**Comment by probonopd** [comment]
Compare the set of files in the working AppImage with the set of files in the non-working AppImage, and experiment until you find the file that breaks it...

**Comment by chrisbra** [comment]
Okay, I removed the libpango and a couple of other libraries and then it worked.
I have a working version [here](https://github.com/chrisbra/vim/tree/appimage2). Actual image can be seen [here](https://transfer.sh/mdBnp/gvim-git9449e8a-glibc2.15-x86-64.appimage) Can you check it please? 

I tried bundling all required libraries like libperl5.14, libpython2.7, libpython3.2, libruby1.9.3 and liblua but that did not work and it made the image really big, so I removed that. I think it now needs those libraries in the host system, if you want to use those features.

**Comment by fusion809** [comment]
Works fine for me. As you're a member of vim I'm guessing you could upload the binary releases to tagged releases of this repo and set up Travis CI to do this automatically with each new release of vim?

**Comment by chrisbra** [comment]
Bram has the final saying. I would go with creating a new sub-project like https://github.com/vim/vim-win32-installer which will run regularly and release the appimage regularly. CC @brammool for comment.

**Comment by fusion809** [comment]
Why `vim-win32-installer`? AppImages aren't Windows 32-bit installers... Why not something like `vim-binaries`? As I'm guessin' the name `vim-win32-installer` refers to the fact you's will also be providing Windows 32-bit installers from the repo.

**Comment by fusion809** [comment]
I hope yas do, sounds fairly simple to do for yas as it's automated using Travis CI so you's will probably only be disrupted (by the need to fix a broken build) like once per year or so when a fluke bug stops the build.

**Comment by vim-ml** [comment]
Op 1 dec. 2016 14:54 schreef "Brenton Horne" <vim-dev-github@256bit.org>:
>
> Why vim-win32-installer?

_Like_ vim-win32-installer...

Christ van Willegen

**Comment by fusion809** [comment]
Yep, I know that's why I deleted that comment.

**Comment by vim-ml** [comment]
Op 1 dec. 2016 15:28 schreef "Brenton Horne" <vim-dev-github@256bit.org>:
>
> Yep, I know that's why I deleted that comment.

Oh, I reacted via the mailing list, I didn't know that! Sorry...

Christ van Willegen

**Comment by brammool** [comment]
Christian Brabandt wrote:

> Bram has the final saying. I would go with creating a new sub-project like https://github.com/vim/vim-win32-installer which will run regularly and release the appimage regularly. CC @brammool for comment.

Making this a sub-project sounds good.  Just make sure there are docs
that explain what it's for, when it is updated, etc.

-- 
hundred-and-one symptoms of being an internet addict:
68. Your cat always puts viruses on your dogs homepage

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by probonopd** [comment]
@chrisbra 
> Okay, I removed the libpango and a couple of other libraries and then it worked.
I have a working version here. Actual image can be seen here Can you check it please?

Works for me on
* CentOS-7-x86_64-LiveGNOME-1511.iso
* elementaryos-0.4-stable-amd64.20160921.iso
* Fedora-Workstation-Live-x86_64-24-1.2.iso
* kubuntu-14.04.4-desktop-amd64.iso 
* maui-2-64bit.iso (/usr/share/icons/gnome/ icons missing)
* neon-useredition-20160901-1018-amd64.iso
* openSUSE-Tumbleweed-GNOME-Live-x86_64-Snapshot20160921-Media.iso
* ubuntu-14.04.1-desktop-amd64.iso
* xubuntu-16.04.1-desktop-amd64.iso

Does not work on 
* debian-live-8.0.0-amd64-xfce-desktop+nonfree.iso `/bin/bash: symbol lookup error: /lib/x86_64-linux-gnu/libncurses.so.5: undefined symbol: _nc_putchar`
* debian-live-8.4.0-amd64-gnome-desktop.iso `/bin/bash: symbol lookup error: /lib/x86_64-linux-gnu/libncurses.so.5: undefined symbol: _nc_putchar`

**Comment by fusion809** [comment]
I've created an AppImage that bundles libncurses5 with it (my Recipe which I modified from @chrisbra's appimage.sh script can be found [here](https://github.com/fusion809/GVim.AppImage/raw/master/Recipe)), and does not get the above error on Debian 8 (and runs fine). I've also tested it on Fedora 24 to see if the addition of libncurses5 would cause problems but it didn't, it ran fine. You can find it [here](https://github.com/fusion809/GVim.AppImage/releases/tag/continuous).

**Comment by chrisbra** [comment]
I think chrisbra/vim-appimage is suitable now for inclusion as subproject

**Comment by probonopd** [comment]
> I think chrisbra/vim-appimage is suitable now for inclusion as subproject

Tried on Ubuntu 16.04, works here. Thank you.

**Comment by chrisbra** [comment]
ping

**Comment by brammool** [comment]
ping what?

**Comment by chrisbra** [comment]
I think it is ready to be included as subproject of Vim (similar to how vim-win32-installer works)

**Comment by chrisbra** [comment]
Thanks Bram.

We have [vim/vim-appimage](https://github.com/vim/vim-appimage/) now. Closing.
