### ISSUE TITLE
vim9class: "return this" required for early return from constructor (inconsistent)

### ISSUE THREAD

**Issue by errael** [vim/vim#12040]
### Steps to reproduce

Source the following
```
vim9script

class C
    this._bufnr: number

    def new(this._bufnr)
        if ! bufexists(this._bufnr)
            this._bufnr = -1
            return # comment this out and things work
        endif
    enddef
endclass

var o = C.new(1234)
echo typename(o)
```
Observe that the `typename(o)` is `number`

### Expected behaviour

Comment out the return and
`typename(o)` is `object<C>`

The following works as expected, but feels inconsistent

```
    def new(this._bufnr): any
        if ! bufexists(this._bufnr)
            this._bufnr = -1
            return this
        endif
    enddef
```

### Version of Vim

9.0.1333

### Environment

ubuntu

**Comment by errael** [comment]
Still fails with 9.0.1754

Looking at the failure modes, to get a feel for the importance. Discovered it behaves differently script level versus `:def`.

Using the same class definition as above. Declare the variable with a type (no type inference) and there's an error at the script level
```
var v1: C
v1 = C.new(1234)
echo typename(v1)
```
ERROR: `E1012: Type mismatch; expected object<C> but got number`

But put this in a :def and there is no compile or runtime error, instead the variable is silently given an impossible value for its declared type because of the bug in the generated constructor code. 

```
def F()
    var v2: C
    v2 = C.new(1234)
    echo typename(v2)
enddef

F()
```
OUTPUT: `number`

---

About the workaround, should it be legal to specify a return type for a constructor?

**Comment by yegappan** [comment]
I have created [this PR](https://github.com/vim/vim/pull/12863) to disallow specifying a return type for the new() constructor.  Please try this out and let me know if it solve these problems and whether you see any new issues.

**Comment by errael** [comment]
It solves the problem, tried a few other cases. I'll install it locally; I'm doing a bunch of vim9class debugging for the new days.
