### ISSUE TITLE
vim9class: class instance members initialized during definition

### ISSUE THREAD

**Issue by errael** [vim/vim#12041]
### Steps to reproduce

Source the following script
```
vim9script

def F(): number
    echo "F() called"
    return 1
enddef

class C
    this._foo = F()
endclass
```
Observe the output: `F() called`

**Note:** `F()` is also called during construction.

### Expected behaviour

There should not be any output.

The function `F()` should not be called during class definition.

Putt the initialization in a constructor and things work as expected.

### Version of Vim

9.0.1333

### Environment

ubuntu

**Comment by errael** [comment]
Still fails with 9.0.1754

The danger with this bug is that there can be side effects in the function that is erroneously called.

**Comment by yegappan** [comment]
The function `F()` is called during the class definition because the type of the member variable `_foo` is not specified. 
To determine the type of `_foo`, the RHS expression of the assignment is evaluated and the resulting type is used for
the member variable.

If you explicitly specify the type of `_foo`, then the RHS expression is not evaluated and the function `F()` is not invoked
during class definition and is invoked during the class instantiation.

For example, try using the following:

```
vim9script

def F(): number
    echo "F() called"
    return 1
enddef

class C
    this._foo: number = F()
endclass
```

**Comment by errael** [comment]
Thank you very much for explaining this and providing a work around.

To be clear I still think this is a bug. The language should never call a function, unless explicitly required. This can also result in improper type inference. Consider
```
class C
    this._foo = F()
endclass
```
If `F()` is of type `any` and returns different types at different times, foo can get the wrong type and there will be problems. I wonder if the intention was simply to check the compile time type of `F()`; and _the bug is that the function is called instead of just getting its declared return type_.

If, for some reason, the type is not available at compile time, then it's **better to get a compilation error** requesting that the class member be explicitly typed because type inference isn't able to determine the function's type. Seems the last thing that should happen is to call a function at an unexpected time and causing who knows what havoc.

**Comment by yegappan** [comment]
I have created [this PR](https://github.com/vim/vim/pull/12868) to set the type of a member during object instantiation instead
of during class definition.  Can you try this out and let me know if it works for you and also it doesn't cause some other
regression?

**Comment by errael** [comment]
> set the type of a member during object instantiation

Cool, that sounds correct. You're right. it is the vim9script way to set the type from the first value assigned to it. 

I'll try to get to building a new vim with this patch later today and take it for a spin.

**Comment by errael** [comment]
The difference between `script level` and `def` is difficult for me to wrap my head around...
Using a vim with this patch gives the same results as before the patch (except that the unwanted function call is gone).
This PR fixes the issue, and I'll continue to use it while working. But I think I'm seeing another bug.

What's very confusing is that how the type of the class instance member is defined doesn't change the results, both
```
this.foo = F1()
```
and typing the member
```
this.foo: number = F1()
```
give the same results; when `F1()` returns a `list`, `this.foo` has type `list`. I would expect the typed declaration to fail when anything but a number is assigned to it. The only thing the type declaration seems to do, is that before this patch a declaration prevented the function call during class definition.

_Should I open a new issue for the member type being ignored?_

Source the following to see some examples of the issues.

```
vim9script

var count = -1

def F1(): any
    #echo "F1() called"
    count = (count + 1) % 4

    if count == 0
        return 777
    elseif count == 1
        return [3]
    elseif count == 2
        return {a: 'b'}
    else
        return "andastring"
    endif
enddef

class C1
    this.foo: number = F1()
endclass

var v1: C1

echo "\n"
echo "TEST: type of class member"

def Loop()
    for i in range(4)
        v1 = C1.new()
        echo typename(v1) v1.foo typename(v1.foo)
    endfor
enddef

Loop()


echo "\n"
echo "TEST: assign to all at script level"
var v: any
count = -1

v = C1.new().foo
echo v typename(v)
v = C1.new().foo
echo v typename(v)

echo "\n"
echo "TEST: assign to all in def"
count = -1
def ToAll()
    v = C1.new().foo
    echo v typename(v)
    v = C1.new().foo
    echo v typename(v)
enddef
ToAll()

echo "\n"
echo "TEST: assign to new var from all var"
count = -1
v = C1.new().foo
var w1 = v
echo w1 typename(w1)
v = C1.new().foo
var w2 = v
echo w2 typename(w2)

echo "\n"
echo "assign to new var from all var in def"
count = -1
def ToNewVar()
    v = C1.new().foo
    var x1 = v
    echo x1 typename(x1)
    v = C1.new().foo
    var x2 = v
    echo x2 typename(x2)
enddef
ToNewVar()
```
Gives the results

```
class def DONE

TEST: type of class member
object<C1> 777 number
object<C1> [3] list<number>
object<C1> {'a': 'b'} dict<string>
object<C1> andastring string

TEST: assign to all at script level
777 number
[3] any

TEST: assign to all in def
777 number
[3] list<number>

TEST: assign to new var from all var
777 number
[3] any

assign to new var from all var in def
777 number
[3] list<number>
```

**Comment by errael** [comment]
> try this out and let me know if it works for you and also it doesn't cause some other
> regression?

Fixed the problem as mentioned in previous comment. Worked with it debugging vim9class code for several hours. No problems observed.

**Comment by yegappan** [comment]
I have updated the PR to add a runtime type check for the member initialization expression.  Can you try using the latest PR?

**Comment by errael** [comment]
I've tried a variety of unit test type stuff, looks good. I'll be running with it today; debugging/cleaning-up some code that makes heavy use of vim9classes. Modified the test script focusing on member initialization, here's some after/before results.

**After** the latest patch
```
TEST: type of class member declared without type
C1: object<C1> 777 number
C1: object<C1> [3] list<number>
C1: object<C1> {'a': 'b'} dict<string>
C1: object<C1> andastring string

TEST: type of class member declared with type
Vim:E1012: Type mismatch; expected dict<string> but got number
Vim:E1012: Type mismatch; expected dict<string> but got list<number>
C2: object<C2> {'a': 'b'} dict<string>
Vim:E1012: Type mismatch; expected dict<string> but got string
```

**Before** the latest patch
```
TEST: type of class member declared without type
C1: object<C1> 777 number
C1: object<C1> [3] list<number>
C1: object<C1> {'a': 'b'} dict<string>
C1: object<C1> andastring string

TEST: type of class member declared with type
C2: object<C2> 777 number
C2: object<C2> [3] list<number>
C2: object<C2> {'a': 'b'} dict<string>
C2: object<C2> andastring string
```

The test script
```
vim9script

var count = -1

def F1(): any
    #echo "F1() called"
    count = (count + 1) % 4

    if count == 0
        return 777
    elseif count == 1
        return [3]
    elseif count == 2
        return {a: 'b'}
    else
        return "andastring"
    endif
enddef

class C1
    this.foo = F1()                 #<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
endclass

class C2
    this.foo: dict<string> = F1()   #<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
endclass

def RunIt(Fu: func)
    try
        Fu()
    catch
        echo v:exception
    endtry
enddef

var v1: C1
var v2: C2

echo "\n"
echo "TEST: type of class member declared without type"

def LoopC1()
    for i in range(4)
        RunIt(() => {
            v1 = C1.new()
            echo "C1:" typename(v1) v1.foo typename(v1.foo)
        })
    endfor
enddef

LoopC1()

echo "\n"
echo "TEST: type of class member declared with type"

def LoopC2()
    for i in range(4)
        RunIt(() => {
            v2 = C2.new()
            echo "C2:" typename(v2) v2.foo typename(v2.foo)
        })
    endfor
enddef

LoopC2()

```

**Comment by errael** [comment]
> looks good. I'll be running with it today;

Still looks good. Haven't noticed anything unusual today. (Ignoring the unrelated lockvar issue).

**Comment by errael** [comment]
This is also fixed/closed by https://github.com/vim/vim/commit/618e47d1cd93954bad26d47e5353b4f1432daa5e
