### ISSUE TITLE
vim9class: "execute 'obj.Method()'" fails when obj defined in function

### ISSUE THREAD

**Issue by errael** [vim/vim#12054]
### Steps to reproduce

Source the following script
```
vim9script

class C
    def M1(s: string)
        echo s
    enddef
endclass

var inScript = C.new()
inScript.M1('script direct')
execute "inScript.M1('script execute')"

def F()
    var inDef = C.new()
    inDef.M1("compiled direct")
    execute "inDef.M1('compiled execute')"   # <<<<<< ERRROR
enddef
F()
```
gives the following
```
script direct
script execute
compiled direct
Error detected while processing command line..script /home/err/play/xxx.vim[18]..function <SNR>31_F:

line    3:
E121: Undefined variable: inDef
```

### Expected behaviour

No error

### Version of Vim

9.0.1341

### Environment

ubuntu

**Comment by errael** [comment]
There's the following workaround, putting the object created in a function into script variable
```
vim9script

var bounce_obj: any
def Bounce(obj: any, method_and_args: string)
    bounce_obj = obj
    execute "bounce_obj." .. method_and_args
enddef

class C
    def M1(s: string)
        echo s
    enddef
endclass

def F()
    var inDef = C.new()
    # run inDef.M1('xxx') where method name is created dynamically
    Bounce(inDef, "M" .. 1 .. "('compiled bounce')")
enddef
F()
```

**Comment by brammool** [comment]
A variable local to a compiled function is not visible to ":execute".  This was done intentionally, as creating a namespace for the function (a dict which in legacy functions is accessed with "l:") adds a lot of overhead, and it is hardly ever needed (or a good idea).  Using a script-local variable or even a global variable is indeed they way to make it work.  It may look a bit clumsy, but it's worth it.  Another way would be to use a legacy function, but that will be much slower.

**Comment by errael** [comment]
> A variable local to a compiled function is not visible to ":execute". This was done intentionally, as creating a namespace for the function (a dict which in legacy functions is accessed with "l:") adds a lot of overhead, and it is hardly ever needed (or a good idea). Using a script-local variable or even a global variable is indeed they way to make it work. It may look a bit clumsy, but it's worth it. Another way would be to use a legacy function, but that will be much slower.

Of course, I knew that about execute (or at least I do now, until I want it again). 

I ended up with a jump table, something like.

```
const dispatch = {
    MethodName: (obj: MyType) => obj.MethodName(),
    ...
}
```
Used something like
```
dispatch->get(methodName, null_function)(obj)
```
