### ISSUE TITLE
sort('n')/sort('N') problems

### ISSUE THREAD

**Issue by errael** [vim/vim#12061]
### Steps to reproduce

I may be misunderstanding the `sort()` doc; or there's a bug and/or `sort()` not updated for `vim9`.

Source the following
```
vim9script

def TestSort(l1: list<string>)
    echo "goal: sort a list numerically: input:" l1
    echo "explicit numerical conversion:" l1->copy()
        ->map((_, i) => str2nr(i))->sort('f')->map((_, i) => string(i))
    echo "sort('n'):" l1->copy()->sort('n')
    echo "sort('N'):" l1->copy()->sort('N')
enddef
TestSort([ '5', '1', '4', '2', '3' ])
```
Observe `sort('n')` appears to do nothing, `sort('N')` gets errors.
```
goal: sort a list numerically: input: ['5', '1', '4', '2', '3']
explicit numerical conversion: ['1', '2', '3', '4', '5']
sort('n'): ['5', '1', '4', '2', '3']
Error detected while processing command line..script /home/err/play/xxx.vim[10]..function <SNR>31_Te
stSort:
line    5:
E1030: Using a String as a Number: "5"
E1030: Using a String as a Number: "1"
E1030: Using a String as a Number: "2"
E1030: Using a String as a Number: "3"
E1030: Using a String as a Number: "4"
E1030: Using a String as a Number: "2"
E1030: Using a String as a Number: "5"
E1030: Using a String as a Number: "4"
E1030: Using a String as a Number: "1"
E1030: Using a String as a Number: "4"
```

### Expected behaviour

Either help doc update or sorting works in these cases.

### Version of Vim

9.0.1341

### Environment

ubuntu

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> I may be misunderstanding the `sort()` doc; or there's a bug and/or `sort()` not updated for `vim9`.
> 
> Source the following
> ```
> vim9script
> 
> def TestSort(l1: list<string>)
>     echo "goal: sort a list numerically: input:" l1
>     echo "explicit numerical conversion:" l1->copy()
>         ->map((_, i) => str2nr(i))->sort('f')->map((_, i) => string(i))
>     echo "sort('n'):" l1->copy()->sort('n')
>     echo "sort('N'):" l1->copy()->sort('N')
> enddef
> TestSort([ '5', '1', '4', '2', '3' ])
> ```
> Observe `sort('n')` appears to do nothing, `sort('N')` gets errors.
> ```
> goal: sort a list numerically: input: ['5', '1', '4', '2', '3']
> explicit numerical conversion: ['1', '2', '3', '4', '5']
> sort('n'): ['5', '1', '4', '2', '3']
> Error detected while processing command line..script /home/err/play/xxx.vim[10]..function <SNR>31_Te
> stSort:
> line    5:
> E1030: Using a String as a Number: "5"
> E1030: Using a String as a Number: "1"
> E1030: Using a String as a Number: "2"
> E1030: Using a String as a Number: "3"
> E1030: Using a String as a Number: "4"
> E1030: Using a String as a Number: "2"
> E1030: Using a String as a Number: "5"
> E1030: Using a String as a Number: "4"
> E1030: Using a String as a Number: "1"
> E1030: Using a String as a Number: "4"
> ```
> 
> ### Expected behaviour
> 
> Either help doc update or sorting works in these cases.

Both the implementation and the help is confusing...

For "n" the help says it uses strtod(), which implies it accepts a
number in a string, which is actually not the case.  It considers
strings (and lists, dicts, etc.) as zero.  The list items must be
numbers for this to work.  I wonder why that remark about strtod() was
added here.

For "N" you would actually expect it to work, but the conversion of a
string with digits to a number fails in Vim9 script.  I would say that's
a bug that needs to be fixed.

-- 
hundred-and-one symptoms of being an internet addict:
252. You vote for foreign officials.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
