### ISSUE TITLE
GVim freezes when changing focus with Alt+` when guioptions doesn't have rL in it.

### ISSUE THREAD

**Issue by MeanEYE** [vim/vim#12070]
### Steps to reproduce

1. Set `guioptions-=rL`;
2. Open two GVim instances and maximize them;
3. Switch between them on Gnome desktop using Alt-` couple of times;
4. After few switches Vim UI will freeze, but application keep running in background.

### Expected behaviour

Not freezing would be preferable.

### Version of Vim

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jan 11 2023 03:16:36) Included patches: 1-1000, 1087, 1117-1118, 1129, 1165

### Environment

Debian Testing

**Comment by MeanEYE** [comment]
For those having the same issue, you can sort of hide scrollbars by editing `~/.config/gtk-3.0/gtk.css` and adding the following content:

```CSS
window#vim-main-window scrollbar {
	opacity: 0;
}
```

This makes right scrollbar invisible, but on the left side gray area remains.

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> 1. Set `guioptions-=rL`;
> 2. Open two GVim instances and switch between them on Gnome desktop
> using Alt-`;

Is that Alt-backtick?  I can't make it switch between the two processes.
Do you see the same problem when using Alt-Tab?

> 3. After few switches Vim UI will freeze, but application keep running
> in background.
> 
> ### Expected behaviour
> 
> Not freezing would be preferable.
> 
> ### Version of Vim
> 
> VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jan 11 2023 03:16:36)
> Included patches: 1-1000, 1087, 1117-1118, 1129, 1165

What GUI?  I'm was using Motif.


-- 
I thought I was eating a crab salad.  It turned out to be a crap salad.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by MeanEYE** [comment]
Yes it is backtick on GTK3 UI. In Gnome desktop environment it's used to switch between instances of same application. Issue appears at various times be it on switching workspace or Alt+Tab, however it's easiest to reproduce with Alt+Backtick.

Also even if the option to show/hide toolbars is set it doesn't eliminate the issue completely but it makes it a lot less frequent. Issue doesn't appear almost at all when windows are not maximized or full-screen. So my hypothesis is that it has something to do with geometry calculation that makes UI freeze. Vim itself doesn't freeze, just UI. I can still issue commands like save and quit.

Starting GVim with `-u NONE` does eliminate the issue. I have however went through all of my configuration and commented out everything until I have reached `guioptions` which I saw caused the issue. If I remove `guioptions` from my config file I am unable to reproduce the issue. So it might not be toolbar related, just that it reduces chances of it happening.

Am running Vim GTK3 on latest Gnome with Wayland compositor. Not sure if that matters but I've had Wayland specific issues with my own programs, even though GUI library should handle both equally.

**Comment by brammool** [comment]
> Yes it is backtick on GTK3 UI. In Gnome desktop environment it's used
> to switch between instances of same application. Issue appears at
> various times be it on switching workspace or Alt+Tab, however it's
> easiest to reproduce with Alt+Backtick.

I build Vim with GTK.  When I use Alt-backtick it shows only the current
process, not the other one.  Same when I try in an xterm (while I have
several running).

> Also even if the option to show/hide toolbars is set it doesn't
> eliminate the issue completely but it makes it a lot less frequent.
> Issue doesn't appear almost at all when windows are not maximized or
> full-screen. So my hypothesis is that it has something to do with
> geometry calculation that makes UI freeze. Vim itself doesn't freeze,
> just UI. I can still issue commands like save and quit.
> 
> Starting GVim with `-u NONE` does eliminate the issue. I have however
> went through all of my configuration and commented out everything
> until I have reached `guioptions` which I saw caused the issue. If I
> remove `guioptions` from my config file I am unable to reproduce the
> issue. So it might not be toolbar related, just that it reduces
> chances of it happening.
> 
> Am running Vim GTK3 on latest Gnome with Wayland compositor. Not sure
> if that matters but I've had Wayland specific issues with my own
> programs, even though GUI library should handle both equally.

I don't have Wayland.  Perhaps my video card or driver doesn't support
it.

Can you find out where Vim hangs?  If you compile with debug symbols
(usually adding the -g compilation flag) and don't strip the binary,
then attaching to it with gdb should work:  gdb ./vim {process-id}

-- 
hundred-and-one symptoms of being an internet addict:
197. Your desk collapses under the weight of your computer peripherals.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by MeanEYE** [comment]
I'll try to get it done as soon as possible. It's quite possible this is caused by Wayland as I had issues with shortcuts on my own software which worked just fine on X.org. I'll try and update this issue once I have more info to share.

**Comment by voxik** [comment]
@MeanEYE is it possible that my #12671 is duplicate of your ticket?

**Comment by MeanEYE** [comment]
@voxik it does seem so. I generally have only one, maybe two windows per workspace so I don't alt-tab as much as I switch workspaces. But behavior does seem same, where mouse cursor will change, underlying Vim session keeps working but interface is frozen.

**Comment by MeanEYE** [comment]
Duplicate.
