### ISSUE TITLE
Request option to limit pmenu display area to current window boundaries

### ISSUE THREAD

**Issue by craigmac** [vim/vim#12086]
**Describe the solution you'd like**

Related to #10901

Use case:
Often I'll have vertical split with a help buffer open, and I'm typing in one side while trying to read the documentation on the right hand-side. The pmenu can get in the way because it is only "nudged back" (docs wording) when it reaches the end of the screen, but not the edge of a window. I'd like to be able to tell the pmenu to never overlap another window and to treat the window split edge the same way it treats the screen edge, that way I can always read the docs and use <C-n/p> without worry of it hiding the documentation. Picture attached below. 

**Describe alternatives you've considered**
`'pumwidth'`: I thought might be able to pass it a function or something to determine how to calculate the pumwidth.

**Additional context**

<img width="1920" alt="Screen Shot 2023-02-28 at 12 32 46 PM" src="https://user-images.githubusercontent.com/7416158/221932026-8ddcf50f-b1df-4f2b-a7e9-c676a338f4af.png">

**Comment by brammool** [comment]
Why not swap the position of the two windows?

**Comment by craigmac** [comment]
Well...good point! easier to do than complicated logic on your end to figure out this request. Thanks, closing this.
