### ISSUE TITLE
TabLeave and TabEnter are triggered unnecessary number of times

### ISSUE THREAD

**Issue by przepompownia** [vim/vim#12087]
### Steps to reproduce

- run 
```sh
vim -u NONE --clean \
     --cmd 'autocmd! TabLeave * echom "Tab " . tabpagenr() . " left"' \
     --cmd 'autocmd! TabEnter * echom "Tab " . tabpagenr() . " entered"' \
     -p f1 f2 f3
```
- inside Vim run `messages clear` and `tab drop f1`
- see 
```
Tab 1 left
Tab 2 entered
Tab 2 left
Tab 3 entered
Tab 3 left
Tab 1 entered
Press ENTER or type command to continue
```

It's almost a copy of https://github.com/neovim/neovim/issues/14567

### Expected behaviour

TabLeave and TabEnter are not triggered redundantly.

### Version of Vim

9.0.1365

### Environment

OS: Debian Sid
Terminal: Kitty + tmux
TERM: `tmux-256color`
shell: bash

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> - run 
> ```sh
> - vim -u NONE --clean \
>      --cmd 'autocmd! TabLeave * echom "Tab " . tabpagenr() . " left"' \
>      --cmd 'autocmd! TabEnter * echom "Tab " . tabpagenr() . " entered"' \
>      -p f1 f2 f3
> ```
> - inside Vim run `messages clear` and `tab drop f1`
> - see 
> ```
> Tab 1 left
> Tab 2 entered
> Tab 2 left
> Tab 3 entered
> Tab 3 left
> Tab 1 entered
> Press ENTER or type command to continue
> ```
> 
> It's almost a copy of https://github.com/neovim/neovim/issues/14567
> 
> ### Expected behaviour
> 
> TabLeave and TabEnter are not triggered redundantly.

"redundantly" is not the right word.  What happens is that Vim goes over
all the windows and might close some, those that are not in the updated
argument list.

With the specific example no windows are actually closed, but Vim still
goes over all the tab pages and all windows inside each tab.  No window
actually gets closed, thus triggering the autocommand events most likely
is not useful.  However, if we would leave out the autocommands in this
specific situation, and still trigger them for the "tab all" command, it
gets inconsistent.

Unless the current behavior causes a problem, other than some overhead,
I would rather leave it alone.  Making it more complicated by skipping
some autocommand events in specific situations is not an improvement.


-- 
LAUNCELOT: Isn't there a St. Aaaaarrrrrrggghhh's in Cornwall?
ARTHUR:    No, that's Saint Ives.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by przepompownia** [comment]
@brammool thanks for response. I can convert the above example to something more practical:
```
- run 
```sh
vim -u NONE --clean \
     --cmd 'autocmd! TabLeave * echom "Tab " . tabpagenr() . " left"' \
     --cmd 'autocmd! TabEnter * echom "Tab " . tabpagenr() . " entered"' \
     -p f1 f2 f3
```
- inside Vim run `messages clear` and `tab drop f3`
- see messages 
```
Tab 1 left
Tab 2 entered
Tab 2 left
Tab 3 entered
```
- run `g<TAB>`. Note that the current tab is `f2` - not expected `f1`. 

In practice, we can imagine that `f1` contains a reference to a definition located in `f3`. 

While it's not fixed. I use some (probably buggy) workarounds to simulate `tab drop` without the effect described above.

**Comment by przepompownia** [comment]
@brammool thanks for the workaround. 

I was hoping 8281a16 would solve the practical part but it fails with another simple test. In the above example please run `tab drop f4` and type `g<Tab>`. For me, the last used tab contains `f3`, not expected `f1`.
