### ISSUE TITLE
the /etc/vimrc configuration of vim9.0 and vim8.2 are different.

### ISSUE THREAD

**Issue by TheStoryEnd** [vim/vim#12091]
### Steps to reproduce

1. :scriptnames  
![image](https://user-images.githubusercontent.com/84452375/222663365-6c6f5834-5cbc-428f-8444-95682408c5a7.png)

vim9.0 /etc/vimrc  is not applied.

2. :scriptnames 
![image](https://user-images.githubusercontent.com/84452375/222663717-6452cb88-8f15-4dd5-b30b-0a95679104e6.png)

vim8.2 /etc/vimrc  is applied.

### Expected behaviour

the /etc/vimrc configuration of vim9.0 and vim8.2 are identical.

### Version of Vim
vim8.2.0000
vim9.0.0000

### Environment

OS[openEuler22.03]
shell[bash5.0]

vim-9.0:
https://build.openeuler.openatom.cn/package/binary/download/openEuler:22.03:LTS/vim/standard_aarch64/aarch64/vim-enhanced-9.0-9.oe2203.aarch64.rpm

vim-8.2:
https://117.78.1.88/package/binaries/Temp:openEuler:20.03:LTS:SP2/vim/standard_aarch64

**Comment by TheStoryEnd** [comment]
This difference will result in the following:
 After the ~/.vimrc is added in vim9.0,  backspace= 
 After the ~/.vimrc is added in vim8.2,  backspace=indent,eol,start  in the following:

**Comment by chrisbra** [comment]
can you please show full version output of both Vims?

**Comment by brammool** [comment]
I suspect the two Vim binaries were compiled in a different way.  Or some environment variable differs.
You can see the steps taken with ":help startup".

**Comment by TheStoryEnd** [comment]
> can you please show full version output of both Vims?
ok,I forgot to add the vim-8.2.

vim-8.2:
https://117.78.1.88/package/binaries/Temp:openEuler:20.03:LTS:SP2/vim/standard_aarch64

**Comment by chrisbra** [comment]
_"You are not authorized to perform the action"_

Please show the version output of both versions. My guess is, that one version was compiled with a system vimrc pointing to `/etc/vimrc` (this is sometimes done by distribution specific patches)

**Comment by TheStoryEnd** [comment]
> _"You are not authorized to perform the action"_
> 
> Please show the version output of both versions. My guess is, that one version was compiled with a system vimrc pointing to `/etc/vimrc` (this is sometimes done by distribution specific patches)
but we only fix CVE on vim8.2.0000/vim9.0.0000，No customized patch exists.

**Comment by TheStoryEnd** [comment]
but we only fix CVE on vim8.2.0000/vim9.0.0000，no customized patch exists.

**Comment by TheStoryEnd** [comment]
[https://src.fedoraproject.org/rpms/vim/c/405468dc2e544dab9e2bac783065c512c68d5f1e?branch=rawhide](https://gitee.com/link?target=https%3A%2F%2Fsrc.fedoraproject.org%2Frpms%2Fvim%2Fc%2F405468dc2e544dab9e2bac783065c512c68d5f1e%3Fbranch%3Drawhide)

**Comment by TheStoryEnd** [comment]
Problem solved.
