### ISSUE TITLE
[xxd] Little-endian (-e) with 'weird' cols causes missing characters

### ISSUE THREAD

**Issue by aapo** [vim/vim#12097]
### Steps to reproduce

    echo -n "ABCDEF" | xxd  -c6 -e
    00000000: 44434241     4645CDEF

And

    echo -n "ABCDEFGHI" | xxd  -c9 -e
    00000000: 44434241 48474645     AB49EFGHI

### Expected behaviour

I expected that using -e for little-endian will not cause missing characters.

Expected output:

    00000000: 44434241     4645  ABCDEF

Or

    00000000: 44434241 4645  ABCDEF

### Version of Vim

From v7.4.652 to patch 9.0.1373

### Environment

Ubuntu, not relating terminal/shell.

**Comment by aapo** [comment]
-c3 still misses space

    echo -n "ABCDEFGHI" | ./xxd  -c3 -e
    00000000: 43  41 42ABC
    00000003: 46  44 45DEF
    00000006: 49  47 48GHI

**Comment by brammool** [comment]
> -c3 still misses space
> 
>     echo -n "ABCDEFGHI" | ./xxd  -c3 -e
>     00000000: 43  41 42ABC
>     00000003: 46  44 45DEF
>     00000006: 49  47 48GHI

Little-endian only works properly with a multiple of four octets.
With three octets I would not know what to display.

-- 
If you're sending someone Styrofoam, what do you pack it in?

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
