### ISSUE TITLE
ballooneval conflicts with the completion menu in insert mode

### ISSUE THREAD

**Issue by Shuangcheng-Ni** [vim/vim#12092]
### Steps to reproduce

1. Create `minvimrc` (`balloonexpr` is optional):
```viml
source $VIMRUNTIME/defaults.vim
set number
set ballooneval balloonevalterm balloonexpr=F()
func! F()
    return 'abcdef'
endfunc
```
2. Start vim by `vim -u minvimrc`.
3. Enter insert mode and type some words. Press `<C-n>` to trigger the completion menu. Then move the mouse, and the completion menu will disappear.

[demo](https://user-images.githubusercontent.com/110970449/222412911-2194fa69-0ecd-426b-950c-a5bae3ff76fa.mp4)

### Expected behaviour

The completion menu **should not** disappear when I move the mouse in insert mode.

### Version of Vim

9.0.1016

### Environment

Operating system: Linux (`uname -a` output: `Linux user 5.4.0-131-generic #147-Ubuntu SMP Fri Oct 14 17:09:03 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux`; `lsb_release -a` output: `... Description:    Ubuntu 20.04.5 LTS ...`)
Terminal: xfce4
Value of $TERM: xterm-256color
Shell: bash 5.0.17(1)-release (aarch64-unknown-linux-gnu)

**Comment by zeertzjq** [comment]
I've created a PR #12094 to fix this.

**Comment by Shuangcheng-Ni** [comment]
Great! Thanks a lot for the immediate fix.
