### ISSUE TITLE
[feature-request] API to get buffer update event

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#12100]
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

I am looking for a new way to integrate tree-sitter into vim without modifying vim's C code.

And I found it is possible to implement in python with `+python3` feature, because tree-sitter
has got a python wrapper: https://github.com/tree-sitter/py-tree-sitter

and it is very easy to generate an AST for a piece of code in python:

```python
from tree_sitter import Language, Parser

PY_LANGUAGE = Language('build/my-languages.so', 'python')

parser = Parser()
parser.set_language(PY_LANGUAGE)

tree = parser.parse(bytes("""
def foo():
    if bar:
        baz()
""", "utf8"))

import pprint
pprint.pprint(tree.root_node.sexp())
```

output AST:

```
('(module (function_definition name: (identifier) parameters: (parameters) '
 'body: (block (if_statement condition: (identifier) consequence: (block '
 '(expression_statement (call function: (identifier) arguments: '
 '(argument_list))))))))')
```

Very straight-forward for python to load a tree-sitter parser dynamic library and generate 
an AST for some code. and Vim has got text props which allows me highlight certain text area.

One last thing I need is a way to listen on buffer changes.

Vim provides some API to get buffer content, and a `b:changedtick` to indicate buffer version.

But it is still not enough for tree-sitter, in order to utilize tree-sitter's incremental parsing mode,
I need to feed tree-sitter buffer diffs for every `b:changedtick`, instead of send the whole buffer
to tree-sitter every time I press a key.

**Describe the solution you'd like**

something similar to NeoVim's two functions:

- nvim_buf_attach(): register a callback to certain buffer

  https://github.com/neovim/neovim/blob/fbaf5bde55d42869ed6d9e9fc072110ac9976c66/runtime/doc/api.txt#L2029

  ![image](https://user-images.githubusercontent.com/3035071/222744756-9f0576f6-dd84-4058-a1aa-20a7c56d82c4.png)

- nvim_buf_detach(): remove a callback 

  https://github.com/neovim/neovim/blob/fbaf5bde55d42869ed6d9e9fc072110ac9976c66/runtime/doc/api.txt#L2173 

  ![image](https://user-images.githubusercontent.com/3035071/222745001-c88dae5d-493c-4525-b2ad-41706d826dfb.png)

**Comment by zeertzjq** [comment]
Does `listener_add()` work?

**Comment by skywind3000** [comment]
Oh, yeah, that's what I need.
