### ISSUE TITLE
<S-Tab> doesn't work when pmenu open in command-line window

### ISSUE THREAD

**Issue by craigmac** [vim/vim#12116]
### Steps to reproduce

1. `vim --clean`
2. `q:`
3. `i`
4. `h <Tab>`
5. `<S-Tab>`

### Expected behaviour

The first selected pmenu entry should be un-selected and nothing inserted into the command-line window, this is how it works in the command-line (`:h c_<S-Tab>`) and that works fine for me, so it's not terminal emulator keybinding issue (tried several to rule that out).

### Version of Vim

9.0.1341

### Environment

OS: macOS `12.6.3`
Terminal: `WezTerm ﻿﻿﻿﻿﻿20230212
$TERM: `wezterm` (tried on others as well, same issue)
Shell: `zsh`

**Comment by brammool** [comment]
If I try this literally then the "h" in the third step beeps.  Did you mean ":h" instead?
When I use ":h <Tab>" and then "<S-Tab>" nothing strange happens.
What other terminals did you try?

**Comment by habamax** [comment]
With `vim -Nu NONE` you have to get into insert mode first, before start typing. Or just press `<tab><s-tab>`.

https://asciinema.org/a/3Fk1sp3KvgGTPvHaX4QbRbVG8

**Comment by habamax** [comment]
So the minimal steps to repro:

1. `vim -Nu NONE`
2. `q:`
3. `<tab>`
4. `<s-tab>`

https://asciinema.org/a/cI9e3zeyMWlTWbeXDfJKa2vTX
