### ISSUE TITLE
`'viewdir'` is set to non-writable directory in Windows

### ISSUE THREAD

**Issue by timsu92** [vim/vim#12119]
### Steps to reproduce

1. Open vim in any way, eg. `vim --noplugin`
2. (optional) See the variable `'viewdir'` is set to `C:\Program Files (x86)\Vim/vimfiles/view` by executing `:echo &viewdir`
3. (optional) run `:mkview` and we can see that it can't write there

### Expected behaviour

Save the files to user directory just like all the plugins. Maybe `C:\Users\<username>\vimfiles\view` will be a good place. Otherwise, writing to `C:\Program Files (x86)` requires elevated privilege.
Furthermore, backslash and forwardslash is mixed used. I'm not sure whether it will create other problems.

A discussion is here: https://github.com/zhimsel/vim-stay/issues/37

### Version of Vim

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jun 28 2022 12:30:17) MS-Windows 32 Bit console version (there's no patch level shown😢)

### Environment

Operating system: Windows 11 64-bit
Terminal: Windows Terminal 1.16.10262.0
value of $TERM: \<empty>
value of $term: `win32` by `:echo $term`
Shell: Windows PowerShell 5.1.22621.963 (included in system)
Which Vim: Vim in shell and not gvim

**Comment by timsu92** [comment]
Sorry for the late reply😢

>As mentioned in the referred issue, the value of 'viewdir' is most
likely set using the value of $VIM.  Can you check that this matches?

I've reinstalled x64 version of Vim back in Windows, and `:echo $VIM` gives me `C:\Program Files\Vim` while `:echo &viewdir` gives me `C:\Program Files\Vim/vimfiles/view`. So, I guess this is right.

> You can also use this to check if the 'viewdir' option was set after
initialization:
>
>	:verbose set viewdir?

This returns `viewdir=C:\Program Files\Vim/vimfiles/view`

**Comment by tonymec** [comment]
Does the view directory exist on your system? I see the following:
```
:set viewdir?
   viewdir=~/.vim/view
:!ls -l ~/.vim/view
ls: cannot access '/root/.vim/view': No such file or directory

shell returned 2
```

Best regards,
Tony.

**Comment by chrisbra** [comment]
Vim creates the view directory if it does not exist

**Comment by brammool** [comment]
> Sorry for the late reply
> 
> >As mentioned in the referred issue, the value of 'viewdir' is most
> >likely set using the value of $VIM.  Can you check that this matches?
> 
> I've reinstalled x64 version of Vim back in Windows, and `:echo $VIM`
> gives me `C:\Program Files\Vim` while `:echo &viewdir` gives me
> `C:\Program Files\Vim/vimfiles/view`. So, I guess this is right.

The value of $VIM is figured out at runtime.  See ":help $VIM".
There appears to be a mismatch between intending $VIM to be the
system-wide directory where the Vim files are, and the user-specific
directory.

Other uses of $VIM in src/os_dos.h show this.  For a few both
$VIM/dir/file and $HOME/dir/file are tried, indicating $VIM is different
from $HOME.  While the help mentions that $VIM is used to locate user
files.  CLEAN_RUNTIMEPATH should not include directories with user
files, yet it does use $VIM.  That might be wrong.  At least it is
confusing.

Before we make any changes, we first have to decide what $VIM was
actually intended to be.  Keeping in mind we prefer to keep it backwards
compatible.  Although it looks like it was originally made for a
one-user system (MSDOS) where it didn't matter much.

-- 
hundred-and-one symptoms of being an internet addict:
216. Your pet rock leaves home.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by timsu92** [comment]
I think we shouldn't change the value of `$VIM`.
The above information was tested on Windows 11 x64. In Ubuntu 22.04, `:echo $VIM` returns `/usr/share/vim`, which is the vim installation as well. However, `:set viewdir?` returns `  viewdir=~/.vim/view`.
Hence, I guess there's something different between resolving on Windows and Ubuntu

---

@tonymec May I wonder what's your OS? I can't reproduce the value of viewdir on Ubuntu 22.04

**Comment by timsu92** [comment]
> so, perhaps we just need this patch here?
> 
> ```diff
> $ git diff os_dos.h
> diff --git a/src/os_dos.h b/src/os_dos.h
> index f1fcbe6b7..7988230e3 100644
> --- a/src/os_dos.h
> +++ b/src/os_dos.h
> @@ -97,7 +97,7 @@
>  #endif
> 
>  #ifndef DFLT_VDIR
> -# define DFLT_VDIR     "$VIM/vimfiles/view"    // default for 'viewdir'
> +# define DFLT_VDIR     "$HOME/vimfiles/view"   // default for 'viewdir'
>  #endif
> 
>  #ifndef DFLT_DIR
> ```

I can confirm that `$HOME` is working on Windows 11 x64 and `$HOME/vimfiles/view` looks to be resolved to a good place.
However, `:echo $HOME . "/vimfiles/view"` returns `C:\Users\<username>/vimfiles/view`, which contains forward-slash and backward-slash. I'm not sure whether this is going to produce any problem

**Comment by brammool** [comment]
> > so, perhaps we just need this patch here?
> > 
> > ```diff
> > $ git diff os_dos.h
> > diff --git a/src/os_dos.h b/src/os_dos.h
> > index f1fcbe6b7..7988230e3 100644
> > --- a/src/os_dos.h
> > +++ b/src/os_dos.h
> > @@ -97,7 +97,7 @@
> >  #endif
> > 
> >  #ifndef DFLT_VDIR
> > -# define DFLT_VDIR     "$VIM/vimfiles/view"    // default for 'viewdir'
> > +# define DFLT_VDIR     "$HOME/vimfiles/view"   // default for 'viewdir'
> >  #endif
> > 
> >  #ifndef DFLT_DIR
> > ```
> 
> I can confirm that `$HOME` is working on Windows 11 x64 and
> `$HOME/vimfiles/view` looks to be resolved to a good place.

I don't like the mixup of how $VIM is used on different systems.
However, changing that now probably causes more problems than it solves.
Only changing the DFLT_VDIR value as suggested looks like a lower risk
solution.

> However, `:echo $HOME . "/vimfiles/view"` returns
> `C:\Users\<username>/vimfiles/view`, which contains forward-slash and
> backward-slash. I'm not sure whether this is going to produce any
> problem

It should be resolved when figuring out the option defaults, $HOME should
be expanded and slashes handled when 'shellslash' is applied.  I haven't
tried it though.

-- 
hundred-and-one symptoms of being an internet addict:
217. Your sex life has drastically improved...so what if it's only cyber-sex!

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
I had created #12576 for this. Perhaps you want to take the test from there then? (and possibly the change for Amiga as well?)

**Comment by brammool** [comment]
Christian wrote:

> I had created #12576 for this. Perhaps you want to take the test from
> there then? (and possibly the change for Amiga as well?)

Yes, that PR is still useful.

For the Amiga using "home:" is more appropriate.

For the test assert_match() works better, since it shows the value used.
Otherwise we just get "-1" without a hint what the problem is.

-- 
hundred-and-one symptoms of being an internet addict:
219. Your spouse has his or her lawyer deliver the divorce papers...
     via e-mail.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
