### ISSUE TITLE
BufPostDelete event

### ISSUE THREAD

**Issue by cassepipe** [vim/vim#12125]
I would like to run `:!mksession` each time I open a new buffer or remove one to keep my session updated to when I last left it

When I add a new buffer, I can just listen for a `BufAdd` event but `BufDelete` happens *before* the buffer list is updated.

Would it be possible/easy to implement a *BufPostDelete* event ?

Thanks for making great software

**Comment by matveyt** [comment]
> I would like to run `:!mksession` each time I open a new buffer or remove one to keep my session updated to when I last left it

Is there any good reason for this? Why not saving a session only before exiting?

**Comment by cassepipe** [comment]
You're right. I just didn't think about it.
