### ISSUE TITLE
The email bware@mines.colorado.edu couldn't be found

### ISSUE THREAD

**Issue by raimonomiar** [vim/vim#12138]
### Steps to reproduce

Write mail to bware@mines.colorado.edu

### Expected behaviour

mail should be sent successfully (not really a bug) 
Thanks for the awesome tool :)

### Version of Vim

9.0

### Environment

linux

**Comment by brammool** [comment]
I do not see that email in the distributed plugins.  Or is it in an unexpected place?

**Comment by raimonomiar** [comment]
Its in the vimtutor doc https://github.com/vim/vim/blob/c54f347d63bcca97ead673d01ac6b59914bb04e5/runtime/doc/vimtutor.man

**Comment by brammool** [comment]
> Its in the vimtutor doc https://github.com/vim/vim/blob/c54f347d63bcca97ead673d01ac6b59914bb04e5/runtime/doc/vimtutor.man

Aha.  I'll add a remark that it is now invalid.

-- 
XML is a nice language for computers.  Not for humans.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
