### ISSUE TITLE
Wrong cursor position when leaving Insert mode after typing ":" at hit enter prompt caused by inserting register

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#12137]
### Steps to reproduce

1. Run `vim --clean`
2. Press `i<C-R>={}<CR>:<Esc>`
3. Cursor is at bottom-left corner

### Expected behaviour

Cursor is at top-left corner

### Version of Vim

9.0.1337

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

**Comment by brammool** [comment]
After the ```<CR>``` you see an error message, right?

What I see is that the cursor is beyond the end of the line, after the ":".  It should be on the ":".

**Comment by zeertzjq** [comment]
In xterm the cursor is beyond the end of the line, while in kitty and gvim the cursor is at bottom-left corner.
