### ISSUE TITLE
scrollbind: windows sometimes are not in sync

### ISSUE THREAD

**Issue by vitaly-zdanevich** [vim/vim#12130]
### Steps to reproduce

1. Install https://github.com/tpope/vim-fugitive
2. `:G blame` when on some git repo
3. Try to scroll left part (with blame), right part (with your code)

### Expected behaviour

Left and right windows are in sync.

### Version of Vim

9.0.1157

### Environment

Gentoo Linux
$TERM: xterm-kitty

### Logs and stack traces

See related issue https://github.com/tpope/vim-fugitive/issues/2125

Video about this defect:

https://user-images.githubusercontent.com/3514015/224417425-d785d549-7066-4382-b0c5-86622d052011.mp4

**Comment by chrisbra** [comment]
you don't need fugitive for that. A standard diff window shows this behaviour as well.

I thought that 'scrollfocus' option would allow to customize this behaviour at least on windows. But even on windows, it seems it doesn't make any difference ? That's strange.

**Comment by chrisbra** [comment]
ah, seems only the trackpoint doesn't work (which seems is issue #5274)

**Comment by dstein64** [comment]
This sounds related to #5752. @brammool mentioned there that the current behavior is intentional.
https://github.com/vim/vim/issues/5752#issuecomment-596633233

**Comment by brammool** [comment]
So this issue is a duplicated of #5752 ?

**Comment by vitaly-zdanevich** [comment]
Yes.

**Comment by chrisbra** [comment]
closing then
