### ISSUE TITLE
Appending to prompt buffer enters insert mode

### ISSUE THREAD

**Issue by t-troebst** [vim/vim#12147]
### Steps to reproduce

Run the following script:

```vim
new prompt
set buftype=prompt
set bufhidden=hide
startinsert
close
call appendbufline("prompt", "$", "Test")
```
Now hit any key and we are in insert mode.

### Expected behaviour

I would expect to still be in normal mode.

### Version of Vim

9.0.1403

### Environment

OS: Manjaro 22.0.4
Terminal: kitty 0.27.1
$TERM: xterm-kitty
shell: fish 3.6.0

**Comment by t-troebst** [comment]
I'm not very familiar with the codebase but I think the problem appears to be that `aucmd_restbuf` is not calling `leaving_window` when it returns from the window with the prompt buffer. That's where insert mode would normally stopped. I'll try to make a fix for this and see if it works.

**Comment by brammool** [comment]
Note this text in the help for the ":startinsert" command:
"Note that when using this command in a function or script, the insertion only starts after the function or script is finished."
It looks like this works as can be expected.  I also don't understand the reference to "aucmd_restbuf", since there doesn't appear an autocommand in the script.

**Comment by t-troebst** [comment]
Hm, okay but entering insert mode at the end of this does not happen because of startinsert. Here is a test that doesn't use it:

```
new prompt
set buftype=prompt
set bufhidden=hide
func s:TextEntered(text)
    if a:text == 'exit'
        close
    endif
endfunc
call prompt_setcallaback(bufnr(), function('s:TextEntered'))
```

Source this script. That opens a prompt buffer. Now enter insert mode and type "exit" to close the prompt buffer. Finally, various commands that interact with this prompt buffer will now drop you into insert mode automatically. For example, via `:call appendbufline("prompt", "$", "Test")` or `:call setbufvar("prompt", "&sw", "4")`. 

The issue is that some commands internally switch to the prompt buffer and then switch back by using "aucmd_prepbuf" and "aucmd_restbuf". But "aucmd_restbuf" does not restore normal mode properly when leaving a prompt buffer. This is used all over the codebase so there should be many ways to trigger this behavior.

**Comment by brammool** [comment]
OK, after starting Insert mode and using ":close" this problem appears.

I wonder why Insert mode is not automatically started when 'buftype' has been set to "prompt".  Oh well, can't change that now without causing trouble.
