### ISSUE TITLE
Terminal inside Vim sets $LINES environment variable globally instead of locally?

### ISSUE THREAD

**Issue by user202729** [vim/vim#12160]
I'm not sure if this is a bug or not.

Basically, if we use bash, then the subprocesses does not inherit the values of $LINES environment variable...

```
$ echo $LINES
100
$ bash -c 'echo $LINES'

$ bash -ic 'echo $LINES'
100
$
```

here, in the second invocation, $LINES environment variable is not inherited from the parent bash process.

However, in vim, $LINES are set globally -- if you execute the same commands in a `:term` inside vim,
the second line will also print out the number.

(note: I think https://stackoverflow.com/q/1780483/ says that these variables should be set "locally" only, but
it doesn't explain why.)

This is a problem because when I run `:term` in vim, then run `ipython` (now in vim/term `os.environ["LINES"]`
is a fixed value, while in xterm/bash it's not set), then run `less` from it, the LINES is fixed regardless of changes
to the environment variable. Unsetting `LINES` in ipython works as a workaround.

**Comment by user202729** [comment]
I think the code responsible for that is https://github.com/vim/vim/blob/67578e5bcf7404d40d42876b738b72e68add1a3e/src/os_unix.c#L4285

Maybe it's better to not set the environment variables instead, and let the subprocess e.g. bash detect it itself? Does it break anything?

**Comment by vim-ml** [comment]
On 2023-03-15, user202729 wrote:
> I'm not sure if this is a bug or not.
> 
> Basically, if we use bash, then the subprocesses does not inherit the values of
> $LINES environment variable...
> 
> $ echo $LINES
> 100
> $ bash -c 'echo $LINES'
> 
> $ bash -ic 'echo $LINES'
> 100
> $
> 
> here, in the second invocation, $LINES environment variable is not inherited
> from the parent bash process.
> 
> However, in vim, $LINES are set globally -- if you execute the same commands in
> a :term inside vim,
> the second line will also print out the number.
> 
> (note: I think https://stackoverflow.com/q/1780483/ says that these variables
> should be set "locally" only, but
> it doesn't explain why.)

I didn't get from that article that LINES _should_ not be exported,
just that it wasn't.

This never made sense to me.  Several programs use LINES and COLUMNS
to know how large a display they have to work with, so I would think
that they would always be exported.  Many years ago, I put the
following in my ~/.bashrc and haven't had any related problems
since.

    export LINES
    export COLUMNS
    shopt -s checkwinsize

> This is a problem because when I run :term in vim, then run ipython (now in vim
> /term os.environ["LINES"]
> is a fixed value, while in xterm/bash it's not set), then run less from it, the
> LINES is fixed regardless of changes
> to the environment variable. Unsetting LINES in ipython works as a workaround.

Your problem seems to be not that LINES is exported but that it
sometimes has the wrong value.  I don't understand what you mean
when you say it is "fixed regardless of changes".  It sounds like
you are setting LINES in one process and expecting to affect
another, already-running process.  You might have a look at this
article:

    https://help.ubuntu.com/community/EnvironmentVariables

It would help us to solve this issue if you provided more details,
such as exactly what you do to observe the problem and what the
problem is.

user202729 later wrote:
> I think the code responsible for that is https://github.com/vim/vim/blob/
> 67578e5bcf7404d40d42876b738b72e68add1a3e/src/os_unix.c#L4285
> 
> Maybe it's better to not set the environment variables instead, and let the
> subprocess e.g. bash detect it itself? Does it break anything?

I am not aware of a specification that says what a program _should_
or _must_ do with environment variables when it forks a child, but
I like that vim does what it does; it avoids problems from programs
that expect to have LINES and COLUMNS set when they are run.
Changing it would probably break some users' scripts.  Moreover,
I don't see how it should break anything the way it is now.

Regards,
Gary

**Comment by user202729** [comment]
I put a concrete use case which gets broken by vim's setting of environment variable.

> This is a problem because when I run `:term` in vim, then run `ipython` (now in vim/term `os.environ["LINES"]`
is a fixed value, while in xterm/bash it's not set), then run `less` from it, the LINES is fixed regardless of changes
to the environment variable. Unsetting `LINES` in ipython works as a workaround.

To clarify, I do this:

* In vim `:term`.
* In the newly opened terminal, run `ipython`.
* Inside `ipython`, run `import sys`.
* run `sys?`. The `less` window is displayed correctly.
* resize `vim`.
* Run `sys?` again. The `less` window is garbled.

**Comment by chrisbra** [comment]
Oh, I always thought it's the terminals responsibility to set the `$LINES` and `$COLUMNS` at least initially. 

Now it may be fine for bash to automatically set the `$LINES` and `$COLUMNS` for the scripts it runs, 
but keep in mind, you can also run the terminal like this `:term script` where no shell is involved and that called process
may still expect `$LINES` to be available (and not able to automatically determine `$LINES`) (e.g. running `:term vim`)

So I don't think removing `LINES` from the environment is a solution.

**Comment by chrisbra** [comment]
That comes back to what Gary said above. Several programs seem to require it, so it makes sense to export it.

**Comment by brammool** [comment]
> I put a concrete use case which gets broken by vim's setting of
> environment variable.
> 
> > This is a problem because when I run `:term` in vim, then run
> > `ipython` (now in vim/term `os.environ["LINES"]` is a fixed value,
> > while in xterm/bash it's not set), then run `less` from it, the
> > LINES is fixed regardless of changes to the environment variable.
> > Unsetting `LINES` in ipython works as a workaround.
> 
> To clarify, I do this:
> 
> * In vim `:term`.
> * In the newly opened terminal, run `ipython`.
> * Inside `ipython`, run `import sys`.
> * run `sys?`. The `less` window is displayed correctly.
> * resize `vim`.
> * Run `sys?` again. The `less` window is garbled.

This is normal.  The environment variable $LINES (or the exported shell
variable) is passed to the child process when it's created.  Changing
the value when the terminal is resized is the job of the child process.
This normally uses the SIGWINCH signal.

Not setting $LINES is a bad idea, many programs depend on it.

-- 
Facepalm statement #7: "Last week I almost got pregnant!"

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
> > (note: I think https://stackoverflow.com/q/1780483/ says that these variables
> > should be set "locally" only, but
> > it doesn't explain why.)
> 
> I didn't get from that article that LINES _should_ not be exported,
> just that it wasn't.
> 
> This never made sense to me.  Several programs use LINES and COLUMNS
> to know how large a display they have to work with, so I would think
> that they would always be exported.  Many years ago, I put the
> following in my ~/.bashrc and haven't had any related problems
> since.
> 
>     export LINES
>     export COLUMNS
>     shopt -s checkwinsize

In processes there is a separate space for environment variables.
Unfortunately, shells have messed this up by throwing environment
variables and shell variables into the same namespace.  Then using the
"export" mechanism to change what variables mean.  And there is no
simple way to check if a variable is exported or not.  You can use:

	 declare -p LINES

Which then has the mysterious output:

	declare -x LINES="100"

Apparently the "-x" indicates the variable is exported.  The bash manual
page doesn't mention whether LINES is exported or not...

The "-i" argument to bash is poorly documented.  It says it means
"interactive", but then what "interactive" means is spread out in the
manual page.  I guess that omitting "-i", thus a non-interactive shell,
doesn't use SIGWINCH.  Searching for "SIGWINCH" indeed finds this in the
manual page (it's very hard to find unless you know what to search for).

-- 
Facepalm statement #8: "Drive faster, the petrol is running out"

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
I don't think this is a bug and therefore this is not going to change. let me close this therefore.
