### ISSUE TITLE
"defaults file" shadows "system vimrc file" - why? Suggested work around?

### ISSUE THREAD

**Issue by hansfn** [vim/vim#1217]
Running Vim 8.0 (with patches: 1-19) on FreeBSD with the following settings for configurations files (excerpt):

```
   system vimrc file: "/usr/local/etc/vim/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
                [...]
       defaults file: "$VIMRUNTIME/defaults.vim"

```

To my big surprise settings in the system vimrc file can be shadowed/overwritten by settings in the defaults file. This isn't very nice on a multi user system where the system vimrc file is used to create a common Vim setup. Each user can avoid this problem by creating a user .vimrc file. You can also avoid it by setting "skip_defaults_vim" in the system vimrc file. 

I might be incorrect, but normally the defaults are loaded first. I assume this isn't considered a bug, but a feature. Can some one explain why this choice was made for Vim 8?

If I like the defaults, but don't want them to overwrite my system settings, the workaround is to source defaults.vim in the system vimrc file, add the (few) settings I need and end with setting "skip_defaults_vim"? 

PS! The default enabling of the mouse triggered this report. I wanted to keep it disabled as a default until I explained the changes to my users.

**Comment by brammool** [comment]
It appears you have answered your own question.

Loading defaults.vim first does not allow for disabling that, that's a catch 22.
