### ISSUE TITLE
:help iccf does not work :-( 

### ISSUE THREAD

**Issue by adgsenpai** [vim/vim#12186]
### Steps to reproduce

**Run** 

```
:help iccf
```

### Expected behaviour

Well maybe show the iccf information? Or open a web page?

![image](https://user-images.githubusercontent.com/45560312/226708355-4979af5f-b2e3-4591-a86b-42bfbb456788.png)

But returns this error

### Version of Vim

8.2.4919

### Environment

adgsenpai@adgpc:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

**Comment by k-takata** [comment]
Maybe, you have only installed `vim-tiny` package and not installed `vim-runtime` package?
Installing `vim` package should also install `vim-runtime` package as the dependency.

**Comment by adgsenpai** [comment]
> Maybe, you have only installed `vim-tiny` package and not installed `vim-runtime` package?
> Installing `vim` package should also install `vim-runtime` package as the dependency.

I never install anything it came in the base installation of Ubuntu.

**Comment by k-takata** [comment]
Then, the help files are not installed.

**Comment by chrisbra** [comment]
does no help file work? What happens if you just use `:help`?

**Comment by adgsenpai** [comment]
> does no help file work? What happens if you just use `:help`?

It works

**Comment by chrisbra** [comment]
Looks like some distribution/package problem?

**Comment by k-takata** [comment]
When I uninstalled `vim-runtime` on Ubuntu, `:help` shows the following help:

```
*help.txt*      For Vim version 7.4.  Last change: 2016 Sep 07

                  VIM - fake help file for vim-tiny

The Vim online help is not installed on this Debian GNU/Linux system.

WHY ?

Because only the "vim-tiny" package is installed, whose sole purpose is to
provide the vi command for base installations.  As such, it contains a minimal
version of Vim compiled with no graphical user interface and a small subset of
features, in order to keep the package size small.

Since the "vim-runtime" package is rather huge when compared to "vim-tiny",
installing the latter does not automatically install the former.

HOW TO GET A BETTER VIM

To get a more featureful Vim binary (and a vim command, rather than just vi),
install one of the following packages: vim, vim-nox, vim-athena, vim-gtk, or
```

**Comment by chrisbra** [comment]
oh I have never noticed that

**Comment by adgsenpai** [comment]
> Could you show the screenshot of `:help`?

![image](https://user-images.githubusercontent.com/45560312/226888231-8aa785f3-1d5c-4b0d-ada6-f7f6e54acaee.png)

**Comment by k-takata** [comment]
Okay, it is the same with the above case.
So, please install vim, vim-nox, vim-gtk or other Vim package as the help says.

**Comment by adgsenpai** [comment]
> Okay, it is the same with the above case. So, please install vim, vim-nox, vim-gtk or other Vim package as the help says.

Okay makes sense from the pure `vim` command it works in `vi` does not work.

Strange how `Canonical` does not ship the pure vim with their distro.

Thanks again, it works on the vim command which i installed.

Maybe in the vi remove that :help for `:help iccf` in `vi` or add that `uganda.txt` for the `vi`

Its quite interesting 

```
Vim means 'vi improved'. Vim commands and their syntax are fully compatible with vi. 
```

**Comment by chrisbra** [comment]
> Maybe in the vi remove that :help for :help iccf in vi or add that uganda.txt for the vi

That's something for Ubuntus or Debians Bugtracker. 

> Vim means 'vi improved'. Vim commands and their syntax are fully compatible with vi. 

Yes in the sense, that the vim follows the syntax give by vi (e.g. `"` denotes a quote character) etc

**Comment by brammool** [comment]
Hmm, this means the Vim license is not included.  That's not good, it might actually be breaking some rules.
What would be the best place to bring this up?

**Comment by jamessan** [comment]
> Maybe in the vi remove that :help for `:help iccf` in `vi` or add that `uganda.txt` for the `vi`

Whether the information in the intro screen is accurate or not depends on which packages are installed, so I'd rather not patch out that information.  I could look into shipping some additional files in vim-common to ensure the intro screen text is always relevant, but that's also not static text if I recall correctly.

> Hmm, this means the Vim license is not included.

The license is included, just not accessible via the `:help`.  Every package ships with `/usr/share/doc/<package>/copyright`, documenting the license(s) for the package.

**Comment by chrisbra** [comment]
Hm, is there a reason, the tiny vim cannot ship just the runtime/docs folder? I suppose that shouldn't be too much space-wise?

**Comment by k-takata** [comment]
It seems that it is described in the above fake help file:

> Since the "vim-runtime" package is rather huge when compared to "vim-tiny",
> installing the latter does not automatically install the former.

**Comment by brammool** [comment]
> It seems that it is described in the above fake help file:
> 
> > Since the "vim-runtime" package is rather huge when compared to "vim-tiny",
> > installing the latter does not automatically install the former.

"vim-runtime" includes lots of plugin files.  I guess installing just
the help, without having duplicate files, would require another package,
possibly called "vim-help".  The help files would then be removed from
"vim-runtime" and "vim-runtime" would depend on "vim-help".

-- 
Not too long ago, cut and paste was done with scissors and glue...

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
I downloaded the `vim-runtime` Debian bullseye [package ](https://packages.debian.org/bullseye/all/vim-runtime/download). It is compressed of size 6MB. uncompressed 35MB. 
`/usr/share/vim/vim82/doc` alone has 8.6MB.
I then removed everything except for `/usr/share/doc` and `/usr/share/vim/vim82/doc`, and packaged it back as tar.xz package (which seems to be used by the Debian package internally). The new archive was then 2MB.  

That does not seem too bad, also I am still surprised it is that much documentation.

In comparison, the vim-tiny package is 700K, the `vim-tiny` binary has 1.4MB. Okay that is still significant less than just the hypothetical vim-help package, so maybe not such a good idea after all.

**Comment by jamessan** [comment]
FYI, I've recently uploaded changes to address this to Debian.  The relevant help files (sponsor.txt, uganda.txt, and version9.txt) were moved to the vim-common package, which all vim variants (including vim-tiny) use.

vim-tiny's help tags are also updated to reflect these files.
