### ISSUE TITLE
DTD syntax highlighting problem (file `syntax/dtd.vim`)

### ISSUE THREAD

**Issue by tin-pot** [vim/vim#1218]
An unbalanced LEFT PARENTHESIS in a parameter literal messes up syntax highlighting.

Example:

~~~
<!-- `bug.dtd` - Demonstrate problem in `dtd.vim` -->

<!ENTITY % nice-grp "(a|b|c)" >

<!-- At this point, highlighting is fine. -->

<!ENTITY gotcha "(" >

<!-- From here on, highlighting is botched.
     But all is nice again if the LEFT PARENTHESIS in `gotcha`

     -   is either replaced with LEFT SQUARE BRACKET for example, or
     -   is given as a character reference `&#40;`, or
     -   is balanced out with a following RIGHT PARENTHESIS.         -->

<!ELEMENT look-bad (foo,bar,%nice-grp;*) >
~~~

I was able to "fix" this problem for me by removing the `dtdEnum` item from the `contains` list in each of these [two lines][L100] in `dtd.vim`:

~~~
" Strings are between quotes
syn region dtdString    start=+"+ skip=+\\\\\|\\"+  end=+"+ contains=dtdAttrDef,dtdAttrType,dtdEnum,dtdParamEntityInst,dtdEntity,dtdCard
syn region dtdString    start=+'+ skip=+\\\\\|\\'+  end=+'+ contains=dtdAttrDef,dtdAttrType,dtdEnum,dtdParamEntityInst,dtdEntity,dtdCard
~~~

This was - of course - more guesswork than engineering, as I am really not an expert at Vim's syntax highlighting internals. So far however, I have not seen glaring side-effects of this hack.

Maybe some *actual* syntax highlighting expert could take a look and find a proper fix?

[L100]: https://github.com/vim/vim/blob/master/runtime/syntax/dtd.vim#L100

**Comment by chrisbra** [comment]
have you contacted the maintainer?

**Comment by tin-pot** [comment]
>  have you contacted the maintainer?

Um - not yet. This would be Johannes Zellner, but given that his last modification notice in `dtd.vim` dates from 2004-04-27 and the only other revisions (visible in the GitHub repo) are by @brammool himself, I was reluctant to do so.

But if that's the proper way, I'll certainly give it a try. Thanks for the hint. (This is my first Vim issue report ...)

**Comment by chrisbra** [comment]
Am 2016-11-01 00:55, schrieb Martin Hofmann:

> > have you contacted the maintainer?
> 
> Um - not yet. This would be Johannes Zellner, but given that his last
> modification notice in dtd.vim dates from 2004-04-27 and the only
> other revisions (visible in the GitHub repo) are by @brammool [1]
> himself, I was reluctant to do so.
> 
> But if that's the proper way, I'll certainly give it a try. Thanks for
> the hint. (This is my first Vim issue report ...)

Well, at least try. If we don't get any answer, perhaps someone else can
figure out the correct fix (or even wants to become a new maintainer).

Thanks.

**Comment by tin-pot** [comment]
FYI: Yesterday I contacted the maintainer via mail. I'll report back here what answer I might receive.

For the time being, I guess we probably should just leave this issue "open" then?

Thanks again for your advice.

**Comment by dkearns** [comment]
@chrisbra I see you've taken over maintenance of this file so I just thought I'd remind you of this bug in case it was lost in the long forgotten regions of the issues list.

**Comment by chrisbra** [comment]
I included this as of https://github.com/chrisbra/vim-xml-runtime/commit/5f72c8f0affb6cec55c45f609bf27dad02a95c73 
but I don't really if this may cause problems. 

I guess it's time to send new runtime files to Bram. Will do soon.

**Comment by dkearns** [comment]
Thank you.
