### ISSUE TITLE
Systemverilog indentation broken

### ISSUE THREAD

**Issue by adibis** [vim/vim#1219]
Hi, 

The keyword forever is missing from the systemverilog.vim indent file. 
I have tried to contact the maintainer of the file but the last update was back in 2013.

I already have the patch and I submitted the pull request over at neovim.
Let me know if I can submit the PR here too in case I don't her back from the maintainer (and after how long). 

https://github.com/neovim/neovim/pull/5549

**Comment by adibis** [comment]
Let me know if it is okay to submit the patch. I have not heard back from the original maintainer.

**Comment by lacygoill** [comment]
Fixed by https://github.com/vim/vim/commit/5be4ceecea5520265066eac972460ebb1cdf05e7.
