### ISSUE TITLE
Problems around 'smoothscroll'

### ISSUE THREAD

**Issue by Bakudankun** [vim/vim#12199]
### Steps to reproduce

1. `vim --clean`
2. `:set lines=20 columns=80 smoothscroll`
3. `:call setline(1, repeat([''], 100))`
4. Hit `G`
5. See the cursor is at the middle of the window, not the bottom, and EOB lines are shown. It is inconsistent with the usual behavior of `G`
6. `:call setline(82, repeat('a', 100))`
7. Hit `<C-B>G`
8. See the cursor is misplaced at the command line

### Expected behaviour

Cursor is at the bottom of the window at step 5 and 8.
At step 8., next thing is shown at the top of the screen:
```
<<<aaaaaaaaaaaaaaaaa
```

### Version of Vim

9.0.1428

### Environment

OS: Windows / Ubuntu (WSL)
Terminal: Windows Terminal / GUI

**Comment by ychin** [comment]
I confirmed that this seems to be caused by #11764, which itself was to fix some issues with smoothscroll but I guess may have introduced some subtle bugs as well. I could take a look.
