### ISSUE TITLE
Vim incorrectly highlighted initializer list as error inside subscript in C++

### ISSUE THREAD

**Issue by jifbt** [vim/vim#12195]
### Steps to reproduce

For example, write the following C++ code in Vim:

```
std::map<std::pair<int, int>, int> m;
m[{1, 2}] = 42;
```

### Expected behaviour

The braces are displayed in red as error. However, in this case it's actually ok to use braces inside subscript as an initializer list.

### Version of Vim

8.2.4919

### Environment

Ubuntu 22.04.1

**Comment by bfrg** [comment]
This can be disabled by setting `let g:c_no_curly_error = 1` in your `vimrc`. See `:h c_no_curly_error`, there are a few more options that you can set for C/C++.

**Comment by bfrg** [comment]
This has been discussed multiple times in the past. There are already a few issues:
https://github.com/vim/vim/issues?q=is%3Aissue+c_no_curly_error

I think it can be closed.
