### ISSUE TITLE
omap i

### ISSUE THREAD

**Issue by lesorubshayan** [vim/vim#12208]
### Steps to reproduce

omap i to something
then it is impossible to use i( for example

### Expected behaviour

delay

### Version of Vim

last

### Environment

gvim

**Comment by brammool** [comment]
If you use ```omap i 2l``` then obviously other movements starting with "i" cannot be used.
I would say this works as can be expected.  I don't see how you can expect "delay".
That would only apply if you map at least two characters.

**Comment by chrisbra** [comment]
this seems to work as expected, so closing
