### ISSUE TITLE
Completion popup is way off when using virtual text

### ISSUE THREAD

**Issue by techntools** [vim/vim#12210]
### Steps to reproduce

![Screenshot from 2023-03-30 21-26-59](https://user-images.githubusercontent.com/71767293/228898758-7a36470f-d59d-4de0-b0c7-9e04ccb67007.png)

I am using [lsp](https://github.com/yegappan/lsp).

That is virtual text in light gray.

Popup appears in wrong position after pressing C-N when using virtual text.

### Expected behaviour

Popup should be under the cursor.

### Version of Vim

 I am using latest vim compiled from source on Ubuntu 22.04.

### Environment

Ubuntu 22.04

Terminal is Kitty

$TERM is tmux-256color

Shell is bash

**Comment by chrisbra** [comment]
can you please give correct reproduction steps?

**Comment by techntools** [comment]
Pardon if I can not create steps through script

But what I did is just

1. Enable diagnostics with virtual text.

2. Edit the line which has virtual text.

3. To get keword suggestions, press ctrl + n.

**Comment by bfrg** [comment]
Here's a minimal test case:

```vim
vim9script
set nowrap
prop_type_add('test', {highlight: 'Error'})
prop_add(3, 0, {
    text_align: 'above',
    text: 'The quick brown fox jumps over the lazy dog',
    type: 'test'
})
```

**To reproduce:**
1. Run `vim --clean test.vim -S test.vim`.
2. Move the cursor to the 3rd line (the line below the virtual text), then press `A`, and in insert mode press `<C-n>`.
3. Result: The insert-completion popup menu is displayed at the wrong position.

**Screenshot**
![screenshot-2023-03-31_124605](https://user-images.githubusercontent.com/6266600/229101463-701e55a2-8207-48b5-a5e3-58a459e926cb.png)

**Comment by bfrg** [comment]
I forgot to mention, it only happens with `nowrap`.

**Comment by techntools** [comment]
@bfrg Thanks for reproducing with script lines.

And yes I do have ```set nowrap``` in my vimrc.
