### ISSUE TITLE
Missing redraw when a session script makes changes to the buffer

### ISSUE THREAD

**Issue by mgedmin** [vim/vim#12212]
### Steps to reproduce

I was trying to write a script to reproduce a different bug when I noticed this one.

1. Write a `repro.vim` like this:

```
40vsplit
0put ='here is some text more text even more:'
put ='  more text!'
put ='  more text!'
put ='  more text!'
put ='  more text!'
```

2. Run `vim --clean -S repro.vim`

You end up with this:

![paveikslas](https://user-images.githubusercontent.com/159967/229102242-4ba28425-2741-4646-8fd9-e83220fb88e0.png)

### Expected behaviour

I expect the two vsplits to show the same content.

If I press Ctrl-L, the screen is redrawn and I do see the two vsplits with the same content.

### Version of Vim

9.0.1392

### Environment

OS: Ubuntu 22.10

Terminal: GNOME Terminal 3.46.2 (VTE 0.70.0)

$TERM: xterm-256color

Shell: bash 5.2.2(1)-release

**Comment by brammool** [comment]
Strange that even CTRL-L doesn't show the text...   Ah, it's because the text is all scrolled up.  Entering the window recomputes this.  I can fix it, hopefully without undesired side effects.
