### ISSUE TITLE
Errors in test

### ISSUE THREAD

**Issue by plitter** [vim/vim#1221]
Was building 8.0.0055 and got errors in the test.

Executed 220 tests

From test_channel.vim:
Found errors in Test_pipe_through_sort_all():
function RunTheTest[9]..Test_pipe_through_sort_all[2]..Run_pipe_through_sort line 30: Expected ['aaa', 'bbb', 'ccc', 'ddd', 'eee'] but got ['bbb', 'ccc', 'ddd', 'eee', 'aaa']
Found errors in Test_pipe_through_sort_feed():
function RunTheTest[9]..Test_pipe_through_sort_feed[2]..Run_pipe_through_sort line 30: Expected ['aaa', 'bbb', 'ccc', 'ddd', 'eee'] but got ['bbb', 'ccc', 'ddd', 'eee', 'aaa']
Found errors in Test_pipe_through_sort_some():
function RunTheTest[9]..Test_pipe_through_sort_some[2]..Run_pipe_through_sort line 32: Expected ['aaa', 'bbb', 'ddd'] but got ['bbb', 'ddd', 'aaa']

Test results:

From test_channel.vim:
Found errors in Test_pipe_through_sort_all():
function RunTheTest[9]..Test_pipe_through_sort_all[2]..Run_pipe_through_sort line 30: Expected ['aaa', 'bbb', 'ccc', 'ddd', 'eee'] but got ['bbb', 'ccc', 'ddd', 'eee', 'aaa']
Found errors in Test_pipe_through_sort_feed():
function RunTheTest[9]..Test_pipe_through_sort_feed[2]..Run_pipe_through_sort line 30: Expected ['aaa', 'bbb', 'ccc', 'ddd', 'eee'] but got ['bbb', 'ccc', 'ddd', 'eee', 'aaa']
Found errors in Test_pipe_through_sort_some():
function RunTheTest[9]..Test_pipe_through_sort_some[2]..Run_pipe_through_sort line 32: Expected ['aaa', 'bbb', 'ddd'] but got ['bbb', 'ddd', 'aaa']
TEST FAILURE
make[2]: Leaving directory '/home/plitter/.build/vim/repos/extra-x86_64/src/vim-8.0.0055/src/testdir'
make[1]: Leaving directory '/home/plitter/.build/vim/repos/extra-x86_64/src/vim-8.0.0055/src'

**Comment by chrisbra** [comment]
Am 2016-10-31 23:48, schrieb plitter:

> Was building 8.0.0055 and got errors in the test.
> 
> Executed 220 tests
> 
> From test_channel.vim:
> Found errors in Test_pipe_through_sort_all():
> function
> RunTheTest[9]..Test_pipe_through_sort_all[2]..Run_pipe_through_sort
> line 30: Expected ['aaa', 'bbb', 'ccc', 'ddd', 'eee'] but got ['bbb',
> 'ccc', 'ddd', 'eee', 'aaa']
> Found errors in Test_pipe_through_sort_feed():
> function
> RunTheTest[9]..Test_pipe_through_sort_feed[2]..Run_pipe_through_sort
> line 30: Expected ['aaa', 'bbb', 'ccc', 'ddd', 'eee'] but got ['bbb',
> 'ccc', 'ddd', 'eee', 'aaa']
> Found errors in Test_pipe_through_sort_some():
> function
> RunTheTest[9]..Test_pipe_through_sort_some[2]..Run_pipe_through_sort
> line 32: Expected ['aaa', 'bbb', 'ddd'] but got ['bbb', 'ddd', 'aaa']
> 
> Test results:
> 
> From test_channel.vim:
> Found errors in Test_pipe_through_sort_all():
> function
> RunTheTest[9]..Test_pipe_through_sort_all[2]..Run_pipe_through_sort
> line 30: Expected ['aaa', 'bbb', 'ccc', 'ddd', 'eee'] but got ['bbb',
> 'ccc', 'ddd', 'eee', 'aaa']
> Found errors in Test_pipe_through_sort_feed():
> function
> RunTheTest[9]..Test_pipe_through_sort_feed[2]..Run_pipe_through_sort
> line 30: Expected ['aaa', 'bbb', 'ccc', 'ddd', 'eee'] but got ['bbb',
> 'ccc', 'ddd', 'eee', 'aaa']
> Found errors in Test_pipe_through_sort_some():
> function
> RunTheTest[9]..Test_pipe_through_sort_some[2]..Run_pipe_through_sort
> line 32: Expected ['aaa', 'bbb', 'ddd'] but got ['bbb', 'ddd', 'aaa']
> TEST FAILURE
> make[2]: Leaving directory
> '/home/plitter/.build/vim/repos/extra-x86_64/src/vim-8.0.0055/src/testdir'
> make[1]: Leaving directory
> '/home/plitter/.build/vim/repos/extra-x86_64/src/vim-8.0.0055/src'

Can you figure out, why it fails for you?
