### ISSUE TITLE
gvim in windows  fails to  open blowfish3 encrypted file more than 1.2MB

### ISSUE THREAD

**Issue by leejie123** [vim/vim#12226]
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
A clear and concise description of what is hard to do. Ex. It is difficult to [...] when [...]
(If it is related to runtime files, please check their header for where to discuss enhancements.)
I am using gvim in windows to open an encrypted file, it's about 1.25MB and encryped in blowfish3.
Normally, gvim should notify me to enter the password to decrypted the file,but it not response.

**Describe the solution you'd like**
I'd like to feed back this problem and I'm trying another way to decrypt the blowfish3 file. But I'm not good at doing this. Maybe you can help to deal with the problem.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/15863698/229848304-91a00dba-f402-423b-b9c9-e2c7d44c0f84.png)

**Comment by k-takata** [comment]
Vim doesn't have "blowfish3" method. Are you talking about blowfish2?
What does `:set cryptmethod?` show?

And, which version of Vim are you using? Could you show the result of `:ver`?

**Comment by k-takata** [comment]
And, does it occur when you run gvim with the `--clean` option?

**Comment by brammool** [comment]
Please follow the instructions: "Instructions: Replace the template text and remove irrelevant text (including this line)".

How did you create the file?  Only files encrypted by Vim are supported.

**Comment by chrisbra** [comment]
Missing feedback, so closing

**Comment by leejie123** [comment]
> Vim doesn't have "blowfish3" method. Are you talking about blowfish2? What does `:set cryptmethod?` show?
> 
> And, which version of Vim are you using? Could you show the result of `:ver`?

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 12 2019 13:30:17)
MS-Windows 32

**Comment by leejie123** [comment]
> :set cryptmethod

:set cryptmethod
![image](https://github.com/vim/vim/assets/15863698/72ff0f7c-5630-4d73-99a5-cdf9cbfe28d4)

**Comment by leejie123** [comment]
> And, does it occur when you run gvim with the `--clean` option?

Run gvim without --clearn

**Comment by leejie123** [comment]
> And, does it occur when you run gvim with the `--clean` option?

My computer :
windows x64 with RAM 12GB
gvim version:
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 12 2019 13:30:17)
MS-Windows 32

**Comment by k-takata** [comment]
> VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 12 2019 13:30:17)

It is almost 4 years old. Please try with the latest version.
https://github.com/vim/vim-win32-installer/releases

> Run gvim without --clearn

Then, please try with the `--clean` option.

If possible, please also share the encrypted file that causes the issue.
