### ISSUE TITLE
vim resets user defined xattr

### ISSUE THREAD

**Issue by noureddine-taleb** [vim/vim#12229]
### Steps to reproduce

1. first install python-xattr or any program that allow xattr manipulation
2. set a user attribute e.g: `xattr -w user.checksum value filename`
3. run vim on the file and modify the content
4. re-consulte the xattr of the file, you won't find them, vim removes them.

### Expected behaviour

conserve xattr

### Version of Vim

9.0.354

### Environment

Archlinux
St
TERM=st-256-color
zsh

**Comment by chrisbra** [comment]
Yes, this is a known bug (duplicate of #306). Workaround is to `:set backupcopy=yes` IIRC.

**Comment by chrisbra** [comment]
closing as duplicate
