### ISSUE TITLE
Segfault with `setcmdline(''[: -1])`

### ISSUE THREAD

**Issue by andlrc** [vim/vim#12227]
### Steps to reproduce

1. Save the following content to "segfault.vim":
```
cnoremap A <Cmd>call setcmdline(''[: -1])<Cr>
```
2. Start vim with `./vim --clean +'so segfault.vim'`
3. Press `:A`
4. Watch vim crashing `zsh: segmentation fault  ./vim --clean +'so segfault.vim'`

### Expected behaviour

Vim should not crash.

### Version of Vim

Latest version I think:

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Apr  4 2023 22:54:51)
macOS version - arm64
Included patches: 1-1439

<details>
<pre><code>:version
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Apr  4 2023 22:54:51)
macOS version - arm64
Included patches: 1-1439
Compiled by and@MacBook-Pro.webspeed.dk
Huge version without GUI.  Features included (+) or not (-):
+acl               -clientserver      +diff              +folding           +langmap           +mouse_dec         +num64             +reltime           +syntax            +title             +wildmenu
+arabic            +clipboard         +digraphs          -footer            +libcall           -mouse_gpm         +packages          +rightleft         +tag_binary        -toolbar           +windows
+autocmd           +cmdline_compl     -dnd               +fork()            +linebreak         -mouse_jsbterm     +path_extra        -ruby              -tag_old_static    +user_commands     +writebackup
+autochdir         +cmdline_hist      -ebcdic            -gettext           +lispindent        +mouse_netterm     -perl              +scrollbind        -tag_any_white     +vartabs           -X11
-autoservername    +cmdline_info      +emacs_tags        -hangul_input      +listcmds          +mouse_sgr         +persistent_undo   +signs             -tcl               +vertsplit         -xfontset
-balloon_eval      +comments          +eval              +iconv             +localmap          -mouse_sysmouse    +popupwin          +smartindent       +termguicolors     +vim9script        -xim
+balloon_eval_term +conceal           +ex_extra          +insert_expand     -lua               +mouse_urxvt       +postscript        +sodium            +terminal          +viminfo           -xpm
-browse            +cryptv            +extra_search      +ipv6              +menu              +mouse_xterm       +printer           +sound             +terminfo          +virtualedit       -xsmp
++builtin_terms    -cscope            -farsi             +job               +mksession         +multi_byte        +profile           +spell             +termresponse      +visual            -xterm_clipboard
+byte_offset       +cursorbind        +file_in_path      +jumplist          +modify_fname      +multi_lang        -python            +startuptime       +textobjects       +visualextra       -xterm_save
+channel           +cursorshape       +find_in_path      +keymap            +mouse             -mzscheme          -python3           +statusline        +textprop          +vreplace
+cindent           +dialog_con        +float             +lambda            -mouseshape        +netbeans_intg     +quickfix          -sun_workshop      +timers            +wildignore
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/Users/and/git/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DMACOS_X -DMACOS_X_DARWIN -DMACOS_X -DMACOS_X_DARWIN -DMACOS_X -DMACOS_X_DARWIN -DMACOS_X -DMACOS_X_DARWIN -DMACOS_X -DMACOS_X_DARWIN -DMACOS_X -DMACOS_X_DARWIN
-DMACOS_X -DMACOS_X_DARWIN -DMACOS_X -DMACOS_X_DARWIN -DMACOS_X -DMACOS_X_DARWIN -DMACOS_X -DMACOS_X_DARWIN -DMACOS_X -DMACOS_X_DARWIN -DMACOS_X -DMACOS_X_DARWIN -DMACOS_X -DMACOS_X_DARWIN -DMACOS_X -DMACOS_X_D
ARWIN -DMACOS_X -DMACOS_X_DARWIN -g -O2 -I/usr/local/Cellar/libsodium/1.0.18_1/include -D_REENTRANT -I/opt/homebrew/Cellar/libsodium/1.0.18_1/include -I/opt/homebrew/Cellar/libsodium/1.0.18_1/include -I/opt/hom
ebrew/Cellar/libsodium/1.0.18_1/include -I/opt/homebrew/Cellar/libsodium/1.0.18_1/include -I/opt/homebrew/Cellar/libsodium/1.0.18_1/include -I/opt/homebrew/Cellar/libsodium/1.0.18_1/include -I/opt/homebrew/Cell
ar/libsodium/1.0.18_1/include -I/opt/homebrew/Cellar/libsodium/1.0.18_1/include -I/opt/homebrew/Cellar/libsodium/1.0.18_1/include -I/opt/homebrew/Cellar/libsodium/1.0.18_1/include -I/opt/homebrew/Cellar/libsodi
um/1.0.18_1/include -I/opt/homebrew/Cellar/libsodium/1.0.18_1/include -I/opt/homebrew/Cellar/libsodium/1.0.18_1/include -I/opt/homebrew/Cellar/libsodium/1.0.18_1/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc -L/usr/local/lib -o vim -lm -lncurses -L/opt/homebrew/Cellar/libsodium/1.0.18_1/lib -lsodium -liconv -framework AppKit
</code></pre>
</details>

### Environment

OS: macOS version - arm64
Term: Terminal.App `XTERM=xterm-256color` 
Shell: `SHELL=/bin/zsh`.

**Comment by zeertzjq** [comment]
I've created a PR #12231 to fix this.
