### ISSUE TITLE
"search hit TOP, continuing at BOTTOM" message can appear with shortmess-=S

### ISSUE THREAD

**Issue by ddickstein** [vim/vim#12222]
### Steps to reproduce

1. `set shortmess-=S`
2. Insert "test"
3. Press `*`
4. Press `N`

### Expected behaviour

Expected:
```
?\<test\>                      [1/1]
```

Actual:
```
search hit TOP, continuing at BOTTOM
```

### Version of Vim

9.0.1439

### Environment

CentOS 7.9, xfce4-terminal 1.0.4, tmux-256color

**Comment by tonymec** [comment]
What is `cmdheight` set to?
If it is 1, then maybe one message overwrote the other. In that case,
```vim
:set ch+=1
```
ought to fix it.

Otherwise,
```vim
:set shm+=s
```
(with a lowercase s) ought to suppress the message "Search hit TOP, continuing at BOTTOM" so you could see anything it might have overwritten.

Best regards,
Tony.

**Comment by ddickstein** [comment]
This is a bug in Vim's behavior. This message should not appear when `shortmess` is missing `S`. You're right that it also won't appear when you add `s`, but that's just obscuring the bug. Messages are not being overwritten and `cmdheight` does not affect it.

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> 1. `set shortmess-=S`
> 2. Insert "test"
> 3. Press `*`
> 4. Press `N`
> 
> ### Expected behaviour
> 
> Expected:
> ```
> ?\<test\>                      [1/1]
> ```
> 
> Actual:
> ```
> search hit TOP, continuing at BOTTOM
> ```

The reproduction steps remove the "S" flag from 'shortmess', didn't you
mean to add it?

Also, the message is suppressed by the lower case "s" flag, the firstt
step should probably be:

   set shortmess+=s


-- 
MONK: ... and the Lord spake, saying, "First shalt thou take out the Holy Pin,
      then shalt thou count to three, no more, no less.  Three shalt be the
      number thou shalt count, and the number of the counting shalt be three.
      Four shalt thou not count, neither count thou two, excepting that thou
      then proceed to three.  Five is right out.  Once the number three, being
      the third number, be reached, then lobbest thou thy Holy Hand Grenade of
      Antioch towards thou foe, who being naughty in my sight, shall snuff it.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Shougo** [comment]
@ddickstein Have you read `:help 'shortmess'` ?

```
	  s	don't give "search hit BOTTOM, continuing at TOP" or	*shm-s*
		"search hit TOP, continuing at BOTTOM" messages; when using
		the search count do not show "W" after the count message (see
		S below)
```

**Comment by ddickstein** [comment]
I've read the `shortmess` help, and this bug report is not related to the `s` option, which suppresses wrapping messages when present. When `s` is absent, which is the default for Vim and is the case I'm discussing here, we expect wrapping messages to appear. What that wrapping message looks like is determined by the `S` flag -- if `S` is present, we expect the "search hit BOTTOM, continuing at TOP" message. If `S` is absent, we expect a "W" beside the search count. The bug is that we see that message even when `S` is absent, following the repro steps I provided.

**Comment by Shougo** [comment]
Hm...  Understand.  It seems strange behaivior.
The message seems overwritten.

**Comment by brammool** [comment]
Ah, you actually want the "W" before the search count, thus the expected behaviour would be:
```
?\<test\>                     W  [1/1]
```

Strange that "n" works differently than "N".  Also, when "test" appears twice it's different.

**Comment by chrisbra** [comment]
It seems, the `search hit TOP` message is always drawn, but immediately overwritten by the search stat message (I can see this flickering in putty). This comes from the fact, that `searchit()` hits this code here: 

https://github.com/vim/vim/blob/657b31fa3bda2089fef18c30fc706abe5d57e865/src/search.c#L1101-L1103

So it will always gives the warning message , even when it is later overwritten by the search stats message and therefore not neccessary. 

When fixing this, there is one remaining problem in `update_search_stat`, which is that the `cur` position can become there, in which case the search count is no longer displayed. So I think we need the following patch:

```patch
diff --git a/src/option.h b/src/option.h
index 487d87c31..1dc9d51f8 100644
--- a/src/option.h
+++ b/src/option.h
@@ -268,7 +268,7 @@ typedef enum {
 #define SHM_COMPLETIONSCAN  'C'                // completion scanning messages
 #define SHM_RECORDING  'q'             // short recording message
 #define SHM_FILEINFO   'F'             // no file info messages
-#define SHM_SEARCHCOUNT  'S'           // search stats: '[1/10]'
+#define SHM_SEARCHCOUNT  'S'           // no search stats: '[1/10]'
 #define SHM_POSIX       "AS"           // POSIX value
 #define SHM_ALL                "rmfixlnwaWtToOsAIcCqFS" // all possible flags for 'shm'
 #define SHM_LEN                30              // max length of all flags together
diff --git a/src/search.c b/src/search.c
index 74ca8fefb..cd785a2ec 100644
--- a/src/search.c
+++ b/src/search.c
@@ -1089,7 +1089,9 @@ searchit(

            /*
             * If 'wrapscan' is set we continue at the other end of the file.
-            * If 'shortmess' does not contain 's', we give a message.
+            * If 'shortmess' does not contain 's', we give a message, but
+            * only, if we won't show the search stat later anyhow,
+            * (so SEARCH_COUNT must be absent).
             * This message is also remembered in keep_msg for when the screen
             * is redrawn. The keep_msg is cleared whenever another message is
             * written.
@@ -1098,7 +1100,9 @@ searchit(
                lnum = buf->b_ml.ml_line_count;
            else
                lnum = 1;
-           if (!shortmess(SHM_SEARCH) && (options & SEARCH_MSG))
+           if (!shortmess(SHM_SEARCH)
+                   && shortmess(SHM_SEARCHCOUNT)
+                   && (options & SEARCH_MSG))
                give_warning((char_u *)_(dir == BACKWARD
                                          ? top_bot_msg : bot_top_msg), TRUE);
            if (extra_arg != NULL)
@@ -3237,8 +3241,10 @@ update_search_stat(
        lbuf = curbuf;
     }

+    // when searching backwards and having jumped to the first occurrence,
+    // cur must remain greater than 1, else it won't be shown
     if (EQUAL_POS(lastpos, *cursor_pos) && !wraparound
-               && (dirc == 0 || dirc == '/' ? cur < cnt : cur > 0))
+               && (dirc == 0 || dirc == '/' ? cur < cnt : cur > 1))
        cur += dirc == 0 ? 0 : dirc == '/' ? 1 : -1;
     else
     {
```

**Comment by brammool** [comment]
Christian wrote:

> It seems, the `search hit TOP` message is always drawn, but
> immediately overwritten by the search stat message (I can see this
> flickering in putty). This comes from the fact, that `searchit()` hits
> this code here: 
> 
> https://github.com/vim/vim/blob/657b31fa3bda2089fef18c30fc706abe5d57e865/src/search.c#L1101-L1103
> 
> So it will always gives the warning message , even when it is later
> overwritten by the search stats message and therefore not neccessary. 
> 
> When fixing this, there is one remaining problem in
> `update_search_stat`, which is that the `cur` position can become
> there, in which case the search count is no longer displayed. So I
> think we need the following patch:

Thanks for looking into this.

I had also made half a fix:

--- ../../git/vim90/src/search.c	2023-03-07 17:45:07.216247886 +0000
+++ search.c	2023-04-14 20:12:16.742477071 +0100
@@ -664,6 +664,7 @@
     linenr_T	stop_lnum = 0;	// stop after this line number when != 0
     int		unused_timeout_flag = FALSE;
     int		*timed_out = &unused_timeout_flag;  // set when timed out.
+    int		did_msg = FALSE;
 
     if (search_regcomp(pat, NULL, RE_SEARCH, pat_use,
 		   (options & (SEARCH_HIS + SEARCH_KEEP)), &regmatch) == FAIL)
@@ -1099,8 +1100,11 @@
 	    else
 		lnum = 1;
 	    if (!shortmess(SHM_SEARCH) && (options & SEARCH_MSG))
+	    {
 		give_warning((char_u *)_(dir == BACKWARD
 					  ? top_bot_msg : bot_top_msg), TRUE);
+		did_msg = TRUE;
+	    }
 	    if (extra_arg != NULL)
 		extra_arg->sa_wrapped = TRUE;
 	}
@@ -1113,6 +1117,11 @@
     }
     while (--count > 0 && found);   // stop after count matches or no match
 
+    if (did_msg && !shortmess(SHM_SEARCHCOUNT))
+	// Do not repeat the top_bot_msg/bot_top_msg when search count is
+	// showing.
+	VIM_CLEAR(keep_msg);
+
 #ifdef FEAT_RELTIME
     if (extra_arg != NULL && extra_arg->sa_tm > 0)
 	disable_regexp_timeout();


Maybe this won't be needed after your fix.  It doesn't work as a fix by
itself anyway.

Would be good to have a test for this.

-- 
ARTHUR: What are you going to do. bleed on me?
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
I'll create a PR with test in a bit

**Comment by ddickstein** [comment]
These are separate from this bug report, but while this code is being reread / revisited I thought it might be helpful to link this [bug report](https://github.com/vim/vim/issues/5280) and this [feature request](https://github.com/vim/vim/issues/12316) in case they affect how the changes here are approached.
