### ISSUE TITLE
scp add an extra '@' in front of user name.

### ISSUE THREAD

**Issue by xyzith** [vim/vim#1222]
let g:netrw_scp_cmd = "pscp -q -i ".$HOME."\\aaa.ppk
let g:netrw_list_cmd = "plink -i ".$HOME."\\aaa.ppk HOSTNAME ls -Fa "
execute "e! scp://username@xxx.xxx.xxx.xxx/workspace/"

When I tried to  scp file, vim add an '@' to my username. So the username became "@username", and I unable to login or remote edit any file.

-----------
win 7
gvim80 (gvim74 if fine for me.)

**Comment by cecamp** [comment]
Please look at :help netrw-debug and get a debugging trace of your issue and send a copy to me (my email is in the help section -- you'll need to remove the embedded NOSPAM).

**Comment by xyzith** [comment]
Finally, I found what's going wrong.
My username contain '.' (ex: taylor.tang) that cause this issue.
Add a slash could fix this.

**Comment by xyzith** [comment]
I found what's going wrong.
My userame contain '.' cause this issue.
I replace the regex in fun s:RemotePathAnalysis in netrw.vim.
```vim
"  let dirpat  = '^\(\w\{-}\)://\(\(\w\+\)@\)\=\([^/:#]\+\)\%([:#]\(\d\+\)\)\=/\(.*\)$'
  let dirpat  = '^\(\w\{-}\)://\(\([^@]\+\)@\)\=\([^/:#]\+\)\%([:#]\(\d\+\)\)\=/\(.*\)$'
```

It works for me now.
