### ISSUE TITLE
Appending to hidden prompt buffer stops Insert mode unexpectedly

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#12237]
### Steps to reproduce

1. Make the following change to `Test_prompt_appending_while_hidden()` and run that test:
```diff
diff --git a/src/testdir/test_prompt_buffer.vim b/src/testdir/test_prompt_buffer.vim
index 28e0d765f..5609fc8f1 100644
--- a/src/testdir/test_prompt_buffer.vim
+++ b/src/testdir/test_prompt_buffer.vim
@@ -270,6 +270,7 @@ func Test_prompt_appending_while_hidden()
 
       func DoAppend()
         call appendbufline('prompt', '$', 'Test')
+        return ''
       endfunc
   END
   call writefile(script, 'XpromptBuffer', 'D')
@@ -282,11 +283,19 @@ func Test_prompt_appending_while_hidden()
 
   call term_sendkeys(buf, "exit\<CR>")
   call TermWait(buf)
+  call assert_notmatch('-- INSERT --', term_getline(buf, 10))
 
   call term_sendkeys(buf, ":call DoAppend()\<CR>")
   call TermWait(buf)
   call assert_notmatch('-- INSERT --', term_getline(buf, 10))
 
+  call term_sendkeys(buf, "i")
+  call TermWait(buf)
+  call assert_match('-- INSERT --', term_getline(buf, 10))
+  call term_sendkeys(buf, "\<C-R>=DoAppend()\<CR>")
+  call TermWait(buf)
+  call assert_match('-- INSERT --', term_getline(buf, 10))
+
   call StopVimInTerminal(buf)
 endfunc
 
```
2. The last assertion fails, which means that appending to hidden prompt buffer stops Insert mode unexpectedly.

### Expected behaviour

Append to hidden prompt buffer keeps Insert mode

### Version of Vim

9.0.1441

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> 1. Make the following change to `Test_prompt_appending_while_hidden()` and run that test:
> ```vim
> diff --git a/src/testdir/test_prompt_buffer.vim b/src/testdir/test_prompt_buffer.vim
> index 28e0d765f..5609fc8f1 100644
> --- a/src/testdir/test_prompt_buffer.vim
> +++ b/src/testdir/test_prompt_buffer.vim
> @@ -270,6 +270,7 @@ func Test_prompt_appending_while_hidden()
>  
>        func DoAppend()
>          call appendbufline('prompt', '$', 'Test')
> +        return ''
>        endfunc
>    END
>    call writefile(script, 'XpromptBuffer', 'D')
> @@ -282,11 +283,19 @@ func Test_prompt_appending_while_hidden()
>  
>    call term_sendkeys(buf, "exit\<CR>")
>    call TermWait(buf)
> +  call assert_notmatch('-- INSERT --', term_getline(buf, 10))
>  
>    call term_sendkeys(buf, ":call DoAppend()\<CR>")
>    call TermWait(buf)
>    call assert_notmatch('-- INSERT --', term_getline(buf, 10))
>  
> +  call term_sendkeys(buf, "i")
> +  call TermWait(buf)
> +  call assert_match('-- INSERT --', term_getline(buf, 10))
> +  call term_sendkeys(buf, "\<C-R>=DoAppend()\<CR>")
> +  call TermWait(buf)
> +  call assert_match('-- INSERT --', term_getline(buf, 10))
> +
>    call StopVimInTerminal(buf)
>  endfunc
>  
> ```
> 2. The last assertion fails, which means that appending to hidden
> prompt buffer stops Insert mode unexpectedly.
> 
> ### Expected behaviour
> 
> Append to hidden prompt buffer keeps Insert mode

Thanks for the test.  I can fix it, hopefully without introducing new
side effects.


-- 
It's not hard to meet expenses, they're everywhere.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by puremourning** [comment]
> > I can fix it, hopefully without introducing new side effects.
> 
> heh, unfortunately, this appears to have caused a problem in my plugin. ([ycm-core/YouCompleteMe#4148](https://github.com/ycm-core/YouCompleteMe/issues/4148)).
> 
> I will try to isolate a minimal reproducer, but the short version is that I have a prompt buffer open (active) and a popup. In the popup's close handler, I call `stopinsert` and close the prompt buffer/window (via `bwipe`). This seems to inconsistently leave the user in insert mode.

Did a little debugging. It is actually to do with setting the quickfix list from the popup close handler (or something). This should help minimise the repro. I'll try to get to that soon.
