### ISSUE TITLE
Autoformat with gqgq is broken inside tex environments

### ISSUE THREAD

**Issue by Coacher** [vim/vim#1223]
Hello.

Consider the following file:
```
\begin{env}
xxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
\end{env}
```

Open it like this: `vim -N -u NONE -c 'filetype plugin indent on' -c 'set ft=tex' <filename>`
Place the cursor at the beginning of the second line.
In Normal mode type 'gqgq' to format it.

Actual results:
```
\begin{env}
xxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
	xxxxxxxxxxxxxxxxxxxx
	xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
\end{env}
```

Expected results:
```
\begin{env}
xxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
\end{env}
```

vim version is 8.0.0055.

So vim tries to tell me that if I write an abstract or a proof I should indent everything but the first line?
I actually don't know a tex environment that would benefit from such indentation.
I have the same results if I do 'set autoindent', so this also contradicts docs:
```When autoindent is on, formatting uses the indentation of the first line.```

Please fix.

**Comment by chrisbra** [comment]
please further discuss here: https://groups.google.com/d/msg/vim_dev/fH_mFBwSs9k/3En8BB28AgAJ

**Comment by vim-ml** [comment]
On 2 November 2016 at 16:51, Coacher wrote:

> [...] Consider the following file:
> 
> \begin{env}
> xxxxxxxxxxxxxxxxxxxx
> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> xxxxxxxxxxxxxxxxxxxx
> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> \end{env}
> 
> Open it like this: vim -N -u NONE -c 'filetype plugin indent on' -c
> 'set ft=tex' <filename>
> Place the cursor at the beginning of the second line.
> In Normal mode type 'gqgq' to format it.
> 
> Actual results:
> 
> \begin{env}
> xxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> xxxxxxxxxxxxxxxxxxxx
> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> \end{env}
> Expected results:
> 
> \begin{env}
> xxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> xxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> \end{env}
> 
> [...]

That's because 'o' in 'indentkeys' is causing new lines to be
indented according to 'indentexpr'. If you hit '==' to indent before
reflowing the second line, you get:

```
\begin{env}
        xxxxxxxxxxxxxxxxxxxx
        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        xxxxxxxxxxxxxxxxxxxx
        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
\end{env}
```

This seems reasonable to me. --Antony

**Comment by vim-ml** [comment]
On Friday, 4 November 2016 14:36:12 UTC+3, Antony Scriven  wrote:

> That's because 'o' in 'indentkeys' is causing new lines to be
> indented according to 'indentexpr'.

Indeed, after 'set indentkeys-=o' gqgq works as expected in the case described above.
gqgq works as expected in non-tex files even with the default 'indentkeys' setting, which includes 'o'.

**Comment by Coacher** [comment]
Vim tex maintainer was CC'ed in the related vim_dev thread about a month ago.
There is no response since. Please reopen this issue as it isn't fixed.

**Comment by chrisbra** [comment]
I don't see the problem. A solution has been posted. What exactly is your problem?

**Comment by Coacher** [comment]
My problem is stated in the first message.
If by solution you mean fiddling manually with 'indentkeys' or remembering to press '==',
then I must say it's a workaround for a bug that should be fixed, not a solution.
Altering user's interaction that works in non-tex files is not a solution of any kind.
