### ISSUE TITLE
On vim start: Check existence of directory upon searching for home path

### ISSUE THREAD

**Issue by an-dr-eas-k** [vim/vim#12235]
### Steps to reproduce

1. use win 10
2. Configure $HOMEDRIVE and $HOMEPATH to a path that is not existing
3. start vim

### Expected behaviour

The docs state, upon startup, the following directories are checked to search vimfiles
$HOME, $HOMEDRIVE$HOMEPATH, SHGetSpecialFolderPath(NULL, lpzsPath, CSIDL_APPDATA, FALSE);, $USERPROFILE, SHGetSpecialFolderPath(NULL, lpzsPath, CSIDL_COMMON_APPDATA, FALSE);, $ALLUSERSPROFILE, $SYSTEMDRIVE\, C:\

Apparently, vim only checks if the environment variables contain values. It should also check, if the content of the variables makes sense (and the directory really exists) and continue with the next fallback, if not.

Somehow, my IT department configured the variables $HOMEDRIVE and $HOMEPATH to a location that does not exist and I cannot change it permanently (it is overridden by group policy). This does not make problems anywhere, except when starting vi, which does not find the user profile.

My workaround is, to add another environment variable $HOME with the correct user dir.

### Version of Vim

9.0.1395

### Environment

Windows 10

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> 1. use win 10
> 2. Configure $HOMEDRIVE and $HOMEPATH to a path that is not existing
> 3. start vim
> 
> ### Expected behaviour
> 
> The docs state, upon startup, the following directories are checked to search vimfiles
> $HOME, $HOMEDRIVE$HOMEPATH, SHGetSpecialFolderPath(NULL, lpzsPath, CSIDL_APPDATA, FALSE);, $USERPROFILE, SHGetSpecialFolderPath(NULL, lpzsPath, CSIDL_COMMON_APPDATA, FALSE);, $ALLUSERSPROFILE, $SYSTEMDRIVE\, C:\
> 
> Apparently, vim only the checks if the environment variables contain
> values. It should also check, if the content of the variables makes
> sense (and the directory really exists) and continue with the next
> fallback, if not.

I disagree.  If the value is non-empty it should be used.  If the
directory does not exist that is an error in the environment, or perhaps
the directory wasn't created yet.  I don't think it is up to Vim to work
around this situation, it is better to do what was asked for, which in
this case means it cannot figure out what the actual home directory is.
E.g., imagine the directory is on a network drive that failed to mount,
then using some other value leads to unpredictable behavior (and hard to
debug if you don't realize what is happening).

> Somehow, my IT department configured the variables $HOMEDRIVE and
> $HOMEPATH to a location that does not exist and I cannot change it
> permanently (it is overridden by group policy). This does not make
> problems anywhere, except when starting vi, which does not find the
> user profile.

I cannot imagine intentionally setting $HOMEDRIVE and $HOMEPATH to
invalid values without having any effect.  Either it is a mistake or
there was an intention.

> My workaround is, to add another environment variable $HOME with the
> correct user dir.

I'm glad you have a workaround.  That means we don't really have to
change how Vim works for this unusual situation.

-- 
If "R" is Reverse, how come "D" is FORWARD?

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
I agree and I am closing this.
