### ISSUE TITLE
ctrl-c in insert mode in *.sql files wouldn't issue exit of the insert mode

### ISSUE THREAD

**Issue by MR0205** [vim/vim#12248]
### Steps to reproduce

1. gvim --clean
2. :set filetype=sql
3. enter insert mode
4. press ctrl-c

### Expected behaviour

exit insert mode like it happens for other filetypes

### Version of Vim

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jun 28 2022 13:09:53) MS-Windows 32-bit GUI version with OLE support Compiled by appveyor@APPVYR-WIN

### Environment

OS:          Windows 10 64 bit
terminal: not applied
$term:     not applied
shell:       not applied

**Comment by chrisbra** [comment]
cc @dfishburn

**Comment by brammool** [comment]
The choice of CTRL-C as the default completly key was unfortunate.  We can't change it now without upsetting users who have gotten used to it.  You can change it by setting a variable, see ":help sql-completion-static".

**Comment by vim-ml** [comment]
> The choice of CTRL-C as the default complete key was unfortunate. We
can't change it now without upsetting users who have gotten used to it. You
can change it by setting a variable, see ":help sql-completion-static".

Agreed Bram.

So many of the keys are already taken in Vim for various functions, I chose
this as primarily a Windows user, which worked just fine.

But as you point out, I made it as an option to be overridden by the user.

:help sql-completion-static".

The use of "<C-C>" can be user chosen by using the following in your
|.vimrc|
as it may not work properly on all platforms: >
    let g:ftplugin_sql_omni_key = '<C-C>'

David

**Comment by chrisbra** [comment]
closing then.
