### ISSUE TITLE
loading dll on windows doesn't start gui vim

### ISSUE THREAD

**Issue by prabirshrestha** [vim/vim#12243]
### Steps to reproduce

1. Download [extism](https://github.com/extism/extism/releases/tag/v0.3.0) https://github.com/extism/extism/releases/download/v0.3.0/libextism-x86_64-pc-windows-msvc-v0.3.0.tar.gz
2. Extract the tar file
3. In vimrc add the following line.

```vimrc
let s:ctx = libcall(expand("c:/path_to_dll/extism.dll"), "extism_context_new", '')
```
4. Start gvim. 

Gvim starts but no ui is loaded the process can still found be found running in task manager.

### Expected behaviour

Should load the dll.

### Version of Vim

9.0.1425

### Environment

Windows GVIM

### Logs and stack traces

```shell
N/A
```

**Comment by chrisbra** [comment]
Hm, it seems this works as expected. The [help libcall](https://github.com/vim/vim/blob/7e5fe38efc105721400048a2ffdeddbe1b9c0650/runtime/doc/builtin.txt#L5269-L5278) states this:

> For Win32, the functions you write must be placed in a DLL
> and use the normal C calling convention (NOT Pascal which is
> used in Windows System DLLs).  The function must take exactly
> one parameter, either a character pointer or a long integer,
> and **must return a character pointer or NULL**.  The character
> pointer returned must point to memory that will remain valid
> after the function has returned (e.g. in static data in the
> DLL).  If it points to allocated memory, that memory will
> leak away.  Using a static buffer in the function should work,
> it's then freed when the DLL is unloaded.

That doesn't seem to be the case according to the projects documentation: https://extism.org/docs/concepts/runtime-apis#extism_context_new

I guess you rather are interested in #12255 

So I am inclined to close this.

**Comment by brammool** [comment]
I think what Christian points out is that extism_context_new() returns a struct pointer, not a string pointer.  That won't work.
