### ISSUE TITLE
netrw :Rexplore overwrites the 'plus' register

### ISSUE THREAD

**Issue by jpmv27** [vim/vim#1227]
I have 'unnamedplus' in my 'clipboard' setting.

I find that :Rexplore changes the value of the 'plus' register.

While :Explore has code to save/restore some registers, I did not see (may have missed it) any code in :Rexplore to do the same

**Comment by jpmv27** [comment]
Not exactly sure what is the purpose of `netrw_starkeep`, it seems to be used for saving/restoring the star register, similar to `keepregstar`.
I don't know whether it is related to this problem, but shouldn't the same be done with the plus register?

**Comment by cecamp** [comment]
Yes -- please try v162d of netrw (http://www.drchip.org/astronaut/vim/index.html#NETRW

**Comment by jpmv27** [comment]
Fixed in v162d
