### ISSUE TITLE
Add more languages (PT_BR) to /usr/share/vim/vim90/keymap/

### ISSUE THREAD

**Issue by wypimentel** [vim/vim#12270]
### Steps to reproduce

I use KDE, the truth, I have problem with neovide which bound to vim.
Using the normal Konsole and vim I use my system's keyboard, which here is "Keyboard Portuguese (Brasil) - IBM / Lenovo ThinkPad", this one has a keymap better there normal abnt2.
It's easy to find it on images on internet, just type: portuguese (brazilian abnt2) keyboard layout.
The problem is when I use neovide, I just want to go to my init.vim and type there set keymap="portuguese-br".
I tried to create my own modified file but vim couldn't find it.
Is it possible to create a Keymap file for Portuguese_BR speakers? Thanks in advance

### Expected behaviour

I just to use the keyboard without trying to find the key and retyping all the time.
I just want to go to my init.vim and type there set keymap="portuguese-br".

### Version of Vim

9.0.1420

### Environment

Garuda Linux x86_64
Terminal: konsole 22.12.3
Value of $TERM: xterm-256color
Shell: fish 3.6.1

**Comment by chrisbra** [comment]
I am not sure, this is a bug for Vim. You may want to ask user questions on vi.stackexchange.com (e.g. how to properly create keymaps).

This is a bug tracker for vim, we cannot provide individual help here.

**Comment by brammool** [comment]
This doesn't look like a Vim bug, as the label would suggest.  It's definitely possible to add your own keymap.  If you have problems with that, you can find help elsewhere.  If you are looking for an existing keymap, I'm not sure where to ask, perhaps there is a Brazilian Vim user group?
Anyway, this is not an issue we can fix, so let's close it.
