### ISSUE TITLE
mode() not returning "vs", "Vs", or "<ctrl-v>s"

### ISSUE THREAD

**Issue by dstein64** [vim/vim#12285]
### Steps to reproduce

Add the following lines to a file to add the current mode as a key in a dictionary every 100 milliseconds.
```vim
let g:modes = {}

let interval = 100
call timer_start(interval,
      \ {-> execute('let g:modes["' .. mode() .. '"] = 1', '')},
      \ {'repeat': -1})
```

Source the file:
```
:source %
```

Press `V` to enter visual line mode, `<ctrl-g>` to enter select line mode, then `<ctrl-o>` to temporarily enter visual line mode for one key press.

Stay in that mode for over 100 milliseconds so its `mode()` would get recorded then press `<esc>`.

Inspect the value of `g:modes` and look for a `Vs` key, which is not present.

```vim
echo g:modes
```

### Expected behaviour

"Vs" would be one of the keys in `g:modes`, as mentioned in `:help mode()` (from PR #8640).

### Version of Vim

9.0.242

### Environment

OS: Kubuntu 22.10
Terminal: Konsole 22.08.2
$TERM: xterm-256color
Shell: Bash 5.2.2(1)-release

**Comment by berggeist** [comment]
```
:h mode()
```
gives:

> mode([expr])	Return a string that indicates the current mode.
		If [expr] is supplied and it evaluates to a non-zero Number or
		a non-empty String (|non-zero-arg|), then the full mode is
		returned, otherwise **only the first letter** is returned.

This tells you that you should use something like ```mode(1)``` in your script. I.e.:

```
let g:modes = {}

let interval = 100
call timer_start(interval,
      \ {-> execute('let g:modes["' .. mode(v:true) .. '"] = 1', '')},
      \ {'repeat': -1})
```

This results in my test in:
```
{'c': 1, 'Vs': 1, 'S': 1, 'v': 1, 'V': 1, 'n': 1}
```
That is the entry ```Vs``` is contained. Is that you would have expected?

**Comment by dstein64** [comment]
Thanks @berggeist! I'll close this issue.
