### ISSUE TITLE
Allow spellcheck to work with CamelCase in addition to snake_case

### ISSUE THREAD

**Issue by DanielSiepmann** [vim/vim#12283]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
Many languages use lowerCamelCase and upperCamelCase conventions in contrast to snake_case conventions.
Vim already allows to spell check snake_case properly. But it lacks support for spell checking CamelCase versions. So `someValidWord` will always be false while `some_valid_word` is okay.

**Describe the solution you'd like**
I'd like to see native spell checking to work for CamelCase variants as well.

**Describe alternatives you've considered**
I've searched the internet, issues, pull requests and couldn't find a plugin or anything in that regard.

**Additional context**
The following screenshot demonstrates the current situation within PHP files:
![image](https://user-images.githubusercontent.com/354250/233354197-3b2461d2-8d31-4906-8de2-4cd7d0959dbb.png)

I'm fine and happy if someone can point me into the right direction, e.g. to a working plugin, polyfill, etc.

**Comment by zeertzjq** [comment]
Does `:set spelloptions+=camel` work as intended?

**Comment by DanielSiepmann** [comment]
Thanks @zeertzjq that was an easy one. Will close the issue. It might help to reference `spelloptions` from `WORDS` section within `spell.txt`?

I skipped the end of quick start which as a reference, as it looked like there are only keyboard shortcuts and commands to add words. But it's my own fault in the end.
