### ISSUE TITLE
[feature] An option to deal long filename in tabline

### ISSUE THREAD

**Issue by taro-k** [vim/vim#1229]
When opening some files with the long file name under tab function, the tails are shown. Then, in some cases like ruby on rails, the tabline looks defunct like:
> 2 NERD_tree_1  _controller.rb  _controller.rb  _controller.rb  _controller.rb X

If it's GUI, the following vim script in .vimrc may be solution but I want an setting option to show the file names from the beginning for CUI.

    function! GuiTabLabel()
        let label = expand("%:t")
        if strlen(label) > 10
          let label = strpart(label, 0, 10) . ".."
        endif
        return label
    endfunction
    
    set guitablabel=%{GuiTabLabel()}

**Comment by chrisbra** [comment]
I don't understand the problem but note, that you can set the tabline in CUI mode as well.

**Comment by taro-k** [comment]
The problem is, in the case above, we cannot distinguish opened files from the file names in tabline.

> that you can set the tabline in CUI mode as well.

Yes, but in my understanding, we have to write longer vim script to emulate displaying all file names in tabline.

In contrast, it's simple if we implement new option to choose:
- Show a longer file name from the tail. (default)
- Show a longer file name from the beginning.

**Comment by chrisbra** [comment]
I don't think this warrant a new option. Closing.
