### ISSUE TITLE
[netrw] windows local file copy command failing, out of place single quotes in the command line

### ISSUE THREAD

**Issue by AlainVimmer** [vim/vim#12290]
### Steps to reproduce

Mark local file for copy (mf command)
Mark target directory (mt command)
Launch copy command (mc command)

**error** (netrw) tried using g:netrw_localcopycmd<C:\WINDOWS\system32\cmd.exe>; it doesn't work!

### Expected behaviour

File should be copied without error

### Version of Vim

9.0.1474

### Environment

OS: Windows 10 VM on Linux Box

### Logs and stack traces

```shell
I echoed the command launched: 
C:\WINDOWS\system32\cmd.exe /c copy '"c:\temp\\test.c"' '"c:\temp\check\"' 

Obviously the single quotes get in the way.
So I removed them at line 7250 of netrw.vim and it worked fine (but not tested on other O.S.)
	call system(copycmd.g:netrw_localcopycmdopt." ".args." ".tgt)

Also note that there are double backlashes in the generated command (\\test.c), it is not normal but seems to be ignored by windows
```

**Comment by Invarianz** [comment]
I experience exactly the same error on Windows 10 & Windows 11 with gVim version 9.0.2056

**Comment by chrisbra** [comment]
hm, not sure if the single quotes can be removed without side effects on different systems (non-windows basically).

**Comment by Invarianz** [comment]
I'm not sure if it is worth opening a new issue for this. However, the same error occurs (with an empty vimrc) for the move command, with some additional errors:
```
Error detected while processing function <SNR>16_NetrwMarkFileMove:
line   40:
E121: Undefined variable: movecmd
E116: Invalid arguments for function netrw#WinPath(movecmd)
line   60:
E121: Undefined variable: movecmd
E116: Invalid arguments for function system(movecmd.g:netrw_localmovecmdopt." ".s:ShellEscape(fname)." ".tgt)
```

**Comment by MiguelBarro** [comment]
When https://github.com/vim/vim/pull/13823 was merged I assure it was working for me.

**Comment by turkishfilms** [comment]
my mc doesnt work

**Comment by chrisbra** [comment]
closing as fixed by #13823 then

**Comment by lesorubshayan** [comment]
@chrisbra It is not working for me. Using windows gvim downloaded from github releases several days ago.
I am talking about the original issue. Not move issue that was mentioned here in comments.

**Comment by lesorubshayan** [comment]
Verified fix of removing ' works.
Can this be fixed?
Maybe 'if statement' that will check it is windows and don't use single quotes?

**Comment by chrisbra** [comment]
Should be fixe now with [a2d87ba](https://github.com/vim/vim/commit/a2d87ba615f15956116f43f7c70f1b315d679cb4)
