### ISSUE TITLE
README.txt.info  "The file you opened has some invalid characters. If you continue editing this file you could corrupt this document. You can also choose another character encoding and try again."

### ISSUE THREAD

**Issue by ParadigmPacket** [vim/vim#12294]
### Steps to reproduce

[Recorded issue with READMEdir.webm](https://user-images.githubusercontent.com/119883899/233899987-ae79c957-ae8a-48f8-9b9a-0044a332edf2.webm)

[Recorded issue with READMEdir(CLI).webm](https://user-images.githubusercontent.com/119883899/233901024-b52f9db1-e990-42ad-9931-2b120eb160f3.webm)

1. Navigate inside the vim directory.
2. Open the READMEdir directory.
3. Open the README.txt.info file.

     **Result:** 

![README txt info(issue)](https://user-images.githubusercontent.com/119883899/233900384-1b0db45e-7546-4075-a985-377c3d9ebf1e.png)
ME.txt.info file

### Expected behaviour

My initial expectation was to see standard alphanumerical characters in the file. However the issue pictured below is always shown.
![README txt info(issue)](https://user-images.githubusercontent.com/119883899/234162723-01d38c26-c9b9-434b-8d89-ea25c94ca629.png)

### Version of Vim

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 18 2023 11:40:57) Included patches: 1-3995, 4563, 4646, 4774, 4895, 4899, 4901, 4919

### Environment

Operating system: Ubuntu 22.04.2 LTS
Terminal: GNOME Terminal Version 3.44.0 for GNOME 42
Value of $TERM: xterm-256color
Shell: GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)

![ubuntu_screenshot_version](https://user-images.githubusercontent.com/119883899/234167127-c0816271-6c13-4c1a-b67b-4dada75e7639.png)

![terminal_version](https://user-images.githubusercontent.com/119883899/234167154-937f2b97-16c4-4939-b7bd-bfd44a623dea.png)

![value_of_$TERM](https://user-images.githubusercontent.com/119883899/234168352-68c9b707-9a16-477c-9eb0-5d70612353e3.png)

![shell_version](https://user-images.githubusercontent.com/119883899/234167262-7a46cb3b-92c4-48bf-be48-bf24f2a632c3.png)

**Comment by k-takata** [comment]
The `*.txt.info` files are binary files. They are not intended to be opened by text editors.

**Comment by chrisbra** [comment]
closing then

**Comment by brammool** [comment]
Right, this is a binary file.  You can edit it with Vim, but making changes is likely to corrupt it.

In "3.  Open the README.txt.info file."  It is not clear how you open the file.  I don't see anything in the screenshot indicating the program used.  It's not Vim, thus this problem isn't about Vim anyway.

**Comment by cadmusbashlog** [comment]
> Right, this is a binary file. You can edit it with Vim, but making changes is likely to corrupt it.
> 
> In "3. Open the README.txt.info file." It is not clear how you open the file. I don't see anything in the screenshot indicating the program used. It's not Vim, thus this problem isn't about Vim anyway.

I encourage any developers who may have read this far in the thread to review my posted _screencasts_ above for clarity with why this issue was posted.

Some of my last thoughts with this instance: 
- I did not consider that it was a binary file while navigating VIM directories.
- I was unaware that vim doubled as a binary editor/reader since it is labeled as a script editor and not a hex editor.

Thank you everyone for taking time out of your day to discuss this topic.
