### ISSUE TITLE
Unable to `source` Chinese name scripts,

### ISSUE THREAD

**Issue by fqbqrr9** [vim/vim#12303]
### Steps to reproduce

 In the  `_Vimrc`, `source  中文名.vim`, and an error was reported stating that the file cannot be opened.

### Expected behaviour

should source it.

### Version of Vim

Latest version :`'9.0.1488'`

### Environment

Os:`win64`.

**Comment by brammool** [comment]
Check the encoding of your _vimrc file: when you edit it, use ```set fenc?```.
Also check the value of the 'encoding' option.  These days it defaults to "utf-8".
Perhaps your 8.2 version used something else?  Conversion should work though.

**Comment by fqbqrr9** [comment]
: brammool

I found that there are two patch issues with `Patch 8.2.0249 `and `Patch 8.2.2912`. How can I `reverse` them?
I have always used the `gbk(cp936)` encoding.
I want to upgrade vim8 to vim9, which is the biggest obstacle.
My scripts are all `gbk`, and I don't want to change them either.

**Comment by fqbqrr9** [comment]
: brammool

I found that there are two patch issues with `Patch 8.2.0249 `and `Patch 8.2.2912`. How can I `reverse` them?
I have always used the `gbk(cp936)` encoding.
I want to upgrade vim8 to vim9, which is the biggest obstacle.
My scripts are all `gbk`, and I don't want to change them either.

**Comment by fqbqrr9** [comment]
I am adding `set encoding=gbk` to both ends of `_vimrc`, I feel like it'll becomes OK.

**Comment by k-takata** [comment]
The default encoding has been changed to utf-8 on Windows.
If you want to use multibyte characters in your script, I recommend adding the `scriptencoding` line in your scripts.

**Comment by tonymec** [comment]
Vim with UTF-8 'encoding' can edit and source anything if the proper steps are taken.

If you often edit files in GBK encoding, try adding that name near the middle of your 'fileencodings' (plural) setting, like this:
```vim
set fencs=ucs-bom,utf-8,gbk,latin1
```
or, IIUC, it would do no harm to replace gbk there by gb18030 (a superset of it, capable of representing any Unicode character).

I believe that this would recognize GBK files as such, but if this doesn't work, you can _edit_ a GBK file by typing (for example)
```vim
:new ++enc=gbk 中文名.vim
```
To make source that a GBK _vim script_ is executed correctly when used in a :script statement, use (as has been said before)
```vim
scriptencoding gbk
```
(written in 7-bit us-ascii) at the very top of that script.

Best regards,
Tony.

**Comment by tonymec** [comment]
…oops…
To make __sure__ that a GBK _vim script_ is…

**Comment by fqbqrr9** [comment]
Thank you for your reply, as I have upgraded from `vim8` to `vim9` , and my `set encoding=gbk` line is in the `_Vimrc`is in the `sub file` below, so it is interpreted incorrectly according to`utf8`.
Then, I add `set encoding=gbk`directly to the `_Vimrc`inside, then everything is OK.
Mine has always been like this:.
```vim
set fencs=ucs-bom,gbk,utf-8,latin1
```
Of course, there are many files in `utf8`, so I'll transcode them first.
Thank you for the following tips:.
```vim
:new ++enc=gbk 中文名.vim
scriptencoding gbk
```

**Comment by chrisbra** [comment]
closing this
