### ISSUE TITLE
[Help Requested] Anyway to listen before ":w" take effects?

### ISSUE THREAD

**Issue by Pairman** [vim/vim#12309]
### Description
Hello there. Recently I'm working on a project which requires me to preserve a file's xattr information when the file's content is not modified in vim, otherwise don't preserve xattrs. Since vim doesn't preserve file xattrs when saving by default, I need to manually ```set backupcopy=yes``` before a save happens, and ```set backupcopy=no``` after a save finished ( this is an oversimplified description by me, not taking modification detection into account) . 

### Problem
I tried to use autocommands to listen for  BufwritePre and BufWritePost. The vimscript in ```~/.vimrc``` works since I can see their echo outputs. But when I check the file's xattrs, they're lost after I saved using ":w".

### Solution Requested 
Unfortunately I can't google anything helpful, therefore I'm there asking for solutions. Is there anyway to really ```set backupcopy=yes``` before ":w" really happens so that the xattrs can be preserved? Thanks in advance.

My ```~/.vimrc```:
```
set backupcopy=no

function! Vorsave()
        set backupcopy=yes
        echo "==save triggered=="
endfunction

function! Nachsave()
        set backupcopy=no
        echo "==save passed =="
endfunction

augroup SaveControl
        au!
        au BufWritePre * call Vorsave()
        au BufWritePost * call Nachsave()
augroup end
```

The xattrs before modifying using vim:
```
ubuntu@VM-0-5-ubuntu:~/tmp$ setfattr -n user.test -v "test" test. sh
ubuntu@VM-0-5-ubuntu:~/tmp$ xattr -slz test.sh
user.test: test
ubuntu@VM-0-5-ubuntu:~/tmp$
```

The xattrs after modification (not preserved):
```
ubuntu@VM-0-5-ubuntu:~/tmp$ xattr -slz test.sh
ubuntu@VM-0-5-ubuntu:~/tmp$
```

**Comment by chrisbra** [comment]
why not simply just set `:set backupcopy=yes`? Why do you need to reset it afterwards?

**Comment by Pairman** [comment]
> why not simply just set `:set backupcopy=yes`? Why do you need to reset it afterwards?

Thanks for replying. The code is oversimplified. What I plan to do is check whether the file is modified and decide whether preserve xattrs or not, which requires me to set backupcopy to its corresponding value in vimrc.

**Comment by chrisbra** [comment]
Hm, in this case, it might be better to make use of custom `BufWriteCmd` autocommand which gives you complete functionality about what to write and custom actions that you need and take care of all of this yourself.
You may want to check how the [tar.vim](https://github.com/vim/vim/blob/master/runtime/plugin/tarPlugin.vim) or [zip.vim](https://github.com/vim/vim/blob/master/runtime/plugin/zipPlugin.vim) plugins do this:

https://github.com/vim/vim/blob/bf1b7132021bac0fccefebb4a1c24a5f372bae4f/runtime/autoload/zip.vim#L260-L372

https://github.com/vim/vim/blob/bf1b7132021bac0fccefebb4a1c24a5f372bae4f/runtime/autoload/tar.vim#L380-L561

**Comment by Pairman** [comment]
> 

Thank you! I'm looking into this now

**Comment by Pairman** [comment]
The "BufWriteCmd" method works, just have to manually "write" after that. Thanks a lot. I'm closing this issue now.
