### ISSUE TITLE
Vex is broken in latest build

### ISSUE THREAD

**Issue by DanielViberg** [vim/vim#12304]
### Steps to reproduce

1. Start vim
2. :Vex
3. :q
4. :Vex
5. Observe two explorer windows

### Expected behaviour

Only one explorer window was the earlier behaviour

### Version of Vim

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Apr 26 2023 08:28:40) Included patches: 1-1488

### Environment

Ubuntu 23.04
Gnome-terminal
xterm-256color: command not found
Gnome

**Comment by k-takata** [comment]
Cc: @cecamp

**Comment by chrisbra** [comment]
Looks like there is a typo in netrws `s:NetrwEditBuf()` function. This patch fixes it:

```patch
diff --git a/runtime/autoload/netrw.vim b/runtime/autoload/netrw.vim
index 1372de4df..7bb131042 100644
--- a/runtime/autoload/netrw.vim
+++ b/runtime/autoload/netrw.vim
@@ -5734,7 +5734,7 @@ fun! s:NetrwEditBuf(bufnum)
    exe "sil! NetrwKeepj keepalt noswapfile b ".fnameescape(a:bufnum)
   else
 "   call Decho("exe sil! NetrwKeepj noswapfile b ".fnameescape(a:bufnum))
-   exe "sil! NetrwKeepj noswapfile b ".fnameescape(a:bufnume)
+   exe "sil! NetrwKeepj noswapfile b ".fnameescape(a:bufnum)
   endif
 "  call Dret("s:NetrwEditBuf")
 endfun
```

**Comment by DanielViberg** [comment]
Can confirm, @chrisbra  has solved this issue.

**Comment by cecamp** [comment]
Thank you, Christian -- I was attending a wedding without a computer and so couldn't address this.

**Comment by DKurilo** [comment]
Is it closed because PR created?
I mean I can apply it locally, but I don't want to do it each time after update. :)

**Comment by cederom** [comment]
Thank you for the fix! :-)
