### ISSUE TITLE
:Man for any manpage opens an empty window

### ISSUE THREAD

**Issue by kalmanza** [vim/vim#12301]
### Steps to reproduce

```
1. export MANPAGER=vim +MANPAGER --not-a-term -
2. man man
3. Vim opens with the man page for 'man'
4. :Man ls
```

https://user-images.githubusercontent.com/2244241/234430818-33932dae-747d-41c5-8ab0-bfd0bc7cb7a4.mov

### Expected behaviour

It should open a new empty buffer in the same window and read in the manpage for `ls`

I've printed out the command that is being executed and did some debugging:
`env -u MANPAGER GROFF_NO_SGR=1 man 'ls' | col -b`
1. removing silent shows "shell returned 1"
2. removing `| col -b` and reading the command in displays the contents of the man page for `ls`

### Version of Vim

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Apr 24 2023 18:31:22) Included patches: 1-1486

### Environment

```
Linux 5.15.102-1-pve #1 SMP PVE 5.15.102-1 (2023-03-14T13:48Z) x86_64 GNU/Linux
$SHELL = zsh 5.8 (x86_64-debian-linux-gnu)
Terminal = iTerm2
$TERM = screen-256color
```

> VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Apr 24 2023 18:31:22)
Included patches: 1-1486
Compiled by tart@lemontart
Huge version without GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
-balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term -gettext           +num64             +textobjects
-browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     -perl              +title
+channel           +ipv6              +persistent_undo   -toolbar
+cindent           +job               +popupwin          +user_commands
-clientserver      +jumplist          +postscript        +vartabs
-clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           -python            +viminfo
+cmdline_info      +libcall           -python3           +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
+cscope            +localmap          -ruby              +wildignore
+cursorbind        -lua               +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con        +mksession         +smartindent       +writebackup
+diff              +modify_fname      -sodium            -X11
+digraphs          +mouse             -sound             -xfontset
-dnd               -mouseshape        +spell             -xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        -mouse_gpm         +statusline        -xsmp
+eval              -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary
-farsi             -mouse_sysmouse    -tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -O2 -fno-strength-reduce -Wall -Wno-deprecated-declarations -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc -L/usr/local/lib -Wl,--as-needed -o vim -lm -ltinfo -lrt -ldl

**Comment by chrisbra** [comment]
hm,
If I run the command manually:
```
:set shellredir=>%s
:r! env -u MANPAGER GROFF_NO_SGR=1 man 'ls' | col -b
```
I see a "Permission denied error":
```
col: write error: Permission deniedan 'ls' | col -b

shell returned 1

Press ENTER or type command to continue
```

I don't know why this would happen. And interestingly, it starts to work, if I disable `:set noshelltemp`.

**Comment by brammool** [comment]
For me it fails at the very first step:
```
$ export MANPAGER=vim +MANPAGER --not-a-term -
bash: export: `+MANPAGER': not a valid identifier
bash: export: `--not-a-term': not a valid identifier
bash: export: `-': not a valid identifier
```
Adding quotes helps:
```
export MANPAGER="vim +MANPAGER --not-a-term -"
```

I suspect the problem is caused by Vim being started to read from stdin.

I wonder why we get "shell returned 1", is there a way to see the error?
The output file gets deleted before I get a chance to open it.
This needs some more debugging.

**Comment by chrisbra** [comment]
>I wonder why we get "shell returned 1", is there a way to see the error?

Yeah you see it, if you set  `shellredir=>%s` (so omiting redirecting stderr `2>&1`).

But even then, I only got to see the *Permission Denied error* which is not really helpful. I suspect this is somehow related to the redirection from stdin and using a pipe. Not sure. 

I actually went into a debugger, but failed to jump into the child process (after the `fork()`).

**Comment by zzzyxwvut** [comment]
It seems like [`AppArmor`](https://gitlab.com/apparmor/apparmor/-/wikis/Documentation)'s paranoia towards `col`:
```shell
sudo aa-status | grep man
```
```
  /usr/bin/man
  man_filter
  man_groff
  # man processes, if any
```
```shell
grep col /etc/apparmor.d/usr.bin.man
```
```
  /usr/bin/col rmCx -> &man_filter,
  /usr/bin/col rm,
```


Remove the `usr.bin.man` definitions from the Linux kernel:
```shell
sudo apparmor_parser -R /etc/apparmor.d/usr.bin.man
```

Try reading manual pages:
```
MANPAGER="vim +MANPAGER --not-a-term -" man man
:Man ls
```

Add the `usr.bin.man` definitions to the Linux kernel:
```shell
sudo apparmor_parser -a /etc/apparmor.d/usr.bin.man
```

Otherwise, substituting `tac` (_not_ in the `usr.bin.man`
definitions) for `col -b` should work.

----------------------------------------------------------------------

Some data about child processes can be collected with
[`strace`](https://man7.org/linux/man-pages/man1/strace.1.html). Run in terminal A:
```shell
MANPAGER="vim +MANPAGER --not-a-term -" man man
```

Run in terminal B:
```shell
mkdir /tmp/traces
strace -q -v -ff -y -s 1024 -o /tmp/traces/vim -p $(pgrep --newest vim)
```

Now, in `Vim` (A):
```vim
:Man ls
:q
```

Then in B:
```shell
cd /tmp/traces

## Look for the files with "Permission denied" entries:
grep --color -n -C1 EACCES -R .

vim +set\ ft=strace vim.PID
```

Also, denied access may be logged in `/var/log/messages`.

**Comment by chrisbra** [comment]
that's a good hint and reminds me of the similar issue #8991

So this is caused by app-armor. So the behaviour can be "fixed" by running `sudo aa-complain /etc/apparmor.d/usr.bin.man` and then it works again. 

So this is not a bug of vim.

**Comment by zzzyxwvut** [comment]
In [`plugin/manpager.vim`](https://github.com/vim/vim/blob/v9.0.1503/runtime/plugin/manpager.vim#L32-L33), there is a `:substitute` command
annotated with a comment that claims emulation of `col -b`
(without tab replacement):

```vim
  " Emulate 'col -b'
  silent! keepj keepp %s/\v(.)\b\ze\1?//ge
```

If this emulation is good enough to be brought in and tab
replacement is introduced:

```vim
  setl ts& et&
  keepj keepp %retab!
```

the `| col -b` command may be retired.

**Comment by chrisbra** [comment]
Hm,
indeed, this seems to fix it:

ping @lifecrisis (I hope he is the right maintainer)


```patch
diff --git a/runtime/autoload/dist/man.vim b/runtime/autoload/dist/man.vim
index cd584aa71..975b4f906 100644
--- a/runtime/autoload/dist/man.vim
+++ b/runtime/autoload/dist/man.vim
@@ -154,8 +154,10 @@ func dist#man#GetPage(cmdmods, ...)
   endif
   let env_cmd = s:env_has_u ? 'env -u MANPAGER' : 'env MANPAGER=cat'
   let env_cmd .= ' GROFF_NO_SGR=1'
-  let man_cmd = env_cmd . ' man ' . s:GetCmdArg(sect, page) . ' | col -b'
+  let man_cmd = env_cmd . ' man ' . s:GetCmdArg(sect, page)
   silent exec "r !" . man_cmd
+  " emulate col -b, see issue #12301
+  silent! keepj keepp %s/\v(.)\b\ze\1?//ge

   if unsetwidth
     let $MANWIDTH = ''
```

**Comment by brammool** [comment]
> >I wonder why we get "shell returned 1", is there a way to see the error?
> 
> Yeah you see it, if you set  `shellredir=>%s` (so omiting redirecting stderr `2>&1`).
> 
> But even then, I only got to see the *Permission Denied error* which
> is not really helpful. I suspect this is somehow related to the
> redirection from stdin and using a pipe. Not sure. 
> 
> I actually went into a debugger, but failed to jump into the child
> process (after the `fork()`). 

I have run into this problem in the past also, and don't know a nice
solution.  Perhaps somehow halting the process, run a separate gdb
attach to the already running process and continue?

The clumsy solution (but simple and works) is to add logging statements.
Or just printf(stderr) and perror().  Inside Vim ch_log() is quite a
nice solution.

-- 
Sometimes you can protect millions of dollars in your budget simply by buying
a bag of cookies, dropping it on the budget anylyst's desk, and saying
something deeply personal such as "How was your weekend, big guy?"
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> So this is caused by app-armor. So the behaviour can be "fixed" by running sudo aa-complain /etc/apparmor.d/usr.bin.man and then it works again.

This AppArmor profile causes other issues.  For example, I remember it broke my `gx` mapping.  It might help to give a warning to the user:
```diff
diff --git a/runtime/plugin/manpager.vim b/runtime/plugin/manpager.vim
index 1738dc943..cb368a373 100644
--- a/runtime/plugin/manpager.vim
+++ b/runtime/plugin/manpager.vim
@@ -7,6 +7,18 @@ if exists('g:loaded_manpager_plugin')
 endif
 let g:loaded_manpager_plugin = 1
 
+if v:argv->index('+MANPAGER') >= 0
+        \ && filereadable('/etc/apparmor.d/usr.bin.man')
+        \ && readfile('/etc/apparmor.d/usr.bin.man')->match('\<complain\>\C') == -1
+    let s:warning =<< trim END
+        Found an AppArmor profile for the man command set in enforce mode.
+        It might prevent Vim from working as expected when invoked as a man pager.
+        Consider re-setting the profile to complain mode instead:
+        $ sudo aa-complain /etc/apparmor.d/usr.bin.man
+    END
+    autocmd VimEnter * ++once for s:line in s:warning | echomsg s:line | endfor | unlet! s:line s:warning
+endif
+
 " Set up the current buffer (likely read from stdin) as a manpage
 command MANPAGER call s:ManPager()
 
```
No idea how reliable the suggested code is though.

**Comment by zzzyxwvut** [comment]
Unfortunately, it takes *root* to discover with certainty
whether there is the `/usr/bin/man` profile:
```shell
## mount | grep securityfs
## findmnt --type securityfs
sudo grep /usr/bin/man /sys/kernel/security/apparmor/profiles
```
```
/usr/bin/man (enforce)
```

The loaded `usr.bin.man` definitions can later be unloaded:
```shell
sudo apparmor_parser -R /etc/apparmor.d/usr.bin.man
sudo grep /usr/bin/man /sys/kernel/security/apparmor/profiles || echo unloaded
```

Similar definitions can be loaded from some other path:
```shell
cp -t /tmp/ /etc/apparmor.d/usr.bin.man
sudo apparmor_parser -a /tmp/usr.bin.man
sudo grep /usr/bin/man /sys/kernel/security/apparmor/profiles || echo unloaded
```

------------------------------------------------------------

It can be observed that the `/usr/bin/man` profile is not
constraining _at large_.

(1) Make `Man` beget `Vim` (and use temporary files):
```shell
MANPAGER="vim +MANPAGER --not-a-term -" man man
```
```vim
:set shelltemp

:new
:r! env -u MANPAGER GROFF_NO_SGR=1 man 'ls' | col -b
" OR
:Man ls
```

(2) Make `Man` beget `Vim` (and use pipes):
```shell
MANPAGER="vim +MANPAGER --not-a-term -" man man
```
```vim
:set noshelltemp

:new
:r! env -u MANPAGER GROFF_NO_SGR=1 man 'ls' | col -b
" OR
:Man ls
```

(3) Make an interactive shell (`Bash`) beget `Vim`:
```shell
vim --clean
```
```vim
" Vim v8.2.5137- (s:GetPage):
:runtime ftplugin/man.vim
" Vim v8.2.5137+ (s:GetPage):
:runtime autoload/man.vim

:r! env -u MANPAGER GROFF_NO_SGR=1 man 'ls' | col -b
" OR
:Man ls
```

(4) Make an interactive shell (`Bash`) beget the pipeline
of processes:
```shell
env -u MANPAGER GROFF_NO_SGR=1 man ls | col -b | vim +MANPAGER --not-a-term -
```

All but (1) currently succeed under `AppArmor`.

Furthermore, `man` itself, unless `MAN_KEEP_FORMATTING` is
defined, may [call](https://gitlab.com/man-db/man-db/-/blob/e2805ed80fe47b7579a8f4ee71979081af8db566/src/man.c#L1643-L1653) `col -bpx`, if installed, without a snag.
It's `man`'s [sandbox](https://gitlab.com/man-db/man-db/-/blob/e2805ed80fe47b7579a8f4ee71979081af8db566/lib/sandbox.c#L577-L594), where the `MANPAGER` command is placed,
that imposes certain [constraints](https://gitlab.com/man-db/man-db/-/blob/e2805ed80fe47b7579a8f4ee71979081af8db566/FAQ#L31-L42).

**Comment by lifecrisis** [comment]
Greetings,

I have just pushed up a pull request that will resolve this issue.

Thanks to @chrisbra and @zzzyxwvut for the very impressive investigative work.

Best,
lifecrisis
