### ISSUE TITLE
tag format for execute() and win_execute() etc is incorrect

### ISSUE THREAD

**Issue by Shane-XB-Qian** [vim/vim#12347]
### Steps to reproduce

the help doc of 'execute()' and 'win_execute()' (introduced each other)
the tag format should be '|execute()|' not '\`execute()\`', same to win_execute()

### Expected behaviour

n/a

### Version of Vim

v9.0.1507

### Environment

linux

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> the help doc of 'execute()' and 'win_execute()' (introduced each other)
> the tag format should '|execute()|' not '`execute()`', same to win_execute()

At some point the use of backticks was introduced to highlight commands
and other Vim script as examples.  That makes them look different from
regular tags, which can refer to sections, options, etc.

This has so far been done in a few places.  The question is: should we
continue doing this, or go back to making all tags the same color?

I tend to think that highlighting a command differently, like a script
example, is useful.  Doing to same for an expression, which includes
functions, is less obvious.  It does match colors when mentioning a
function and then an example using that function.  E.g.:

		To get a list of lines use `split()` on the result: >
			execute('args')->split("\n")


Before making lots of changes it would be good to hear opinions.

-- 
hundred-and-one symptoms of being an internet addict:
3. Your bookmark takes 15 minutes to scroll from top to bottom.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Shane-XB-Qian** [comment]
> That makes them look different from regular tags, which can refer to sections, options, etc.

but problem is seems '\`foo()\`' kind tag was not really gen tag, but just highlight;
i think it can keep using that for *expression* IF like, but to *function*, perhaps should go back to original way.

**Comment by brammool** [comment]
> > That makes them look different from regular tags, which can refer to
> > sections, options, etc.
> 
> but problem is seems '\`foo()\`' kind tag was not really gen tag, but
> just highlight;

I don't understand this remark.  You can use CTRL-] on just about any
word in the help to lookup that word as a tag.  This works for any
command, option, function, etc.  Only when the word boundaries are not
detected it might fail.

> i think it can keep using that for *expression* IF like, but to
> *function*, perhaps should go back to original way.

Motivation?  I would like to have a good reason to go either way before
we make changes all over the help text.

-- 
The Feynman problem solving Algorithm:
	1) Write down the problem
	2) Think real hard
	3) Write down the answer

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Shane-XB-Qian** [comment]
> I don't understand this remark. You can use CTRL-] on just about any word in the help to lookup that word as a tag.

e.g this content from execute() doc:
```doc
		It is not possible to use `:redir` anywhere in {command}.

		To get a list of lines use |split()| on the result: >
			execute('args')->split("\n")

<		To execute a command in another window than the current one
		use `win_execute()`.
```

1, put cursor on 'redir', and echo expand('\<cword\>'), the output is '\`:redir\`'
2, put cursor on 'command', and echo expand('\<cword\>'), the output is '{command}.'  (note: it included '{}' and '.')
3, put cursor on 'win_execute', and echo expand('\<cword\>'), the output is '\`win_execute()\`.'  (note: it included '\`\`' and '.')

ctrl-] should have handle those extra chars smartly, but command or highlight from user side looks would be confused or broken by those extra chars.

this is my motivation, since the original way `||` even it is `|foo()|.` (note a dot) still recognized as foo() without extra chars.

**Comment by brammool** [comment]
> > I don't understand this remark. You can use CTRL-] on just about any word in the help to lookup that word as a tag.
> 
> e.g this content from execute() doc:
> ```doc
> 		It is not possible to use `:redir` anywhere in {command}.
> 
> 		To get a list of lines use |split()| on the result: >
> 			execute('args')->split("\n")
> 
> <		To execute a command in another window than the current one
> 		use `win_execute()`.
> ```
> 
> 1, put cursor on 'redir', and echo expand('<cword>'), the output is '\`:redir\`'
> 2, put cursor on 'command', and echo expand('<cword>'), the output is '{command}.'  (note: it included '{}' and '.')
> 3, put cursor on 'win_execute', and echo expand('<cword>'), the output is '\`win_execute()\`.'  (note: it included '\`\`' and '.')
> 
> ctrl-] should have handle those extra chars smartly, but command or highlight from user side looks would be confused or broken by those extra chars.
> 
> this is my motivation, since the original way `||` even it is
> `|foo()|.` (note a dot) still recognized as foo() without extra chars.

So this is not about using help tags but about a custom plugin that is
used for the help text.  Well, I think it's much more important to have
the help text work nicely for the common user than to support some
unknown plugin.  Just like CTRL-] it won't be too difficult for that
plugin to figure out what it wants from the text under the cursor.

What CTRL-] does in help text differs from expanding <cword>.  This
happens in nv_ident() and handles quite a few different things.  If it's
really useful enough we could have another item besides <cword> to
expand the way that CTRL-] does.  But since performance can't be all
that important for a command that the user types, doing this in the
plugin itself is likely good enough.

-- 
hundred-and-one symptoms of being an internet addict:
20. When looking at a pageful of someone else's links, you notice all of them
    are already highlighted in purple.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Shane-XB-Qian** [comment]
> So this is not about using help tags but about a custom plugin that is used for the help text. Well, I think it's much more important to have the help text work nicely for the common user than to support some unknown plugin. Just like CTRL-] it won't be too difficult for that plugin to figure out what it wants from the text under the cursor.

what i said about 'user side' did not mean 'custom plugin' always, but just tried to express user may try something else other than 'ctrl-]', which that could be a command or highlight, e.g native 'ptag', it cannot recoginize '``' style tag, to such command that was not a correct tagname (so not work).



> What CTRL-] does in help text differs from expanding <cword>. This happens in nv_ident() and handles quite a few different things. If it's really useful enough we could have another item besides <cword> to expand the way that CTRL-] does. 

i think it's a good idea to offer it IF ok.


> But since performance can't be all that important for a command that the user types, doing this in the plugin itself is likely good enough.

but most users or command or highlight usually use `<cword>`, it would make it work consistently or easy.
e.g emit '*' hotkey on `{command}.` to search, but NOTE it included a dot with it, so it Can Not search {command} (which is one of execute() parameters) at that place to check, then how's that useful/helpful?


so i think IF it can not change the special expanding (not same like `<cword>`) in help doc, then at least make *function* tag go back to the original `||` way.

**Comment by Shane-XB-Qian** [comment]
let it be. closing..
