### ISSUE TITLE
Building 9.0.1520 there is a test failure

### ISSUE THREAD

**Issue by riesebie** [vim/vim#12355]
### Steps to reproduce

Just build 9.0.1520

### Expected behaviour

Failures: 
        From test_timers.vim:
        Found errors in Test_timer_using_win_execute_undo_sync():
        command line..script /source/vim/vim-9.0.1520/src/vim-nox/testdir/runtest.vim[569]..function RunTheTest[52]..Test_timer_using_win_execute_undo_sync line 15: Expected ['aaaa', 'bbbb', 'test'] but got ['aaaa', 'test', 'bbbb']

### Version of Vim

9.0.1520

### Environment

Devuan GNU/Linux 5 (daedalus/ceres)
tmux
zsh 5.9
clang version 15.0.7

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> Just build 9.0.1520
> 
> ### Expected behaviour
> 
> Failures: 
>         From test_timers.vim:
>         Found errors in Test_timer_using_win_execute_undo_sync():
>         command line..script /source/vim/vim-9.0.1520/src/vim-nox/testdir/runtest.vim[569]..function RunTheTest[52]..Test_timer_using_win_execute_undo_sync line 15: Expected ['aaaa', 'bbbb', 'test'] but got ['aaaa', 'test', 'bbbb']

I do not see this failure locally and I also don't see it on CI runs.

The test is timing sensitive, it was also reported to fail on Mac
systems using M1.  I don't see a way to make it more reliable (other
than making the times a lot bigger).  I tried making the time shorter,
but it still doesn't fail.

You can add this line near the start of
Test_timer_using_win_execute_undo_sync() to at least make it retry:

	 let g:test_is_flaky = 1


-- 
hundred-and-one symptoms of being an internet addict:
8. You spend half of the plane trip with your laptop on your lap...and your
   child in the overhead compartment.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
are we fine with closing this because it seems system specific in this case?

**Comment by brammool** [comment]
The only thing we can do is set the flaky flag for all the timer tests.  I'll make a patch for that.
