### ISSUE TITLE
<f-args> expects args when it shouldn't?

### ISSUE THREAD

**Issue by igbanam** [vim/vim#12365]
### Steps to reproduce

Define `./script.vim` as…

```vim
vim9script

def TheFunction(some: list<string>)
  echom some
enddef

command -nargs=* TheCommand :call TheFunction(<f-args>)

execute "TheCommand"
```

Run Vim with 

```sh
vim --clean +'so ./script.vim'
```

### Expected behaviour

I expect `TheFunction` to get an empty list,

…because `h :command-nargs` has
```
        -nargs=*    Any number of arguments are allowed (0, 1, or many),
                    separated by white space
```

…and because `h <f-args>` has
>If no arguments are given <f-args> is removed.

Instead, I get an error saying

```
Error detected while processing command line..script /path/to/script.vim:
line    9:
E119: Not enough arguments for function: <SNR>9_TheFunction
Press ENTER or type command to continue
```

_p.s: This is the same experience if_ `TheFunction` _parameter is defined as_ `some: any`

### Version of Vim

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Apr 30 2023 14:29:56) macOS version - arm64 Included patches: 1-1500

### Environment

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Apr 30 2023 14:29:56)
macOS version - arm64
Included patches: 1-1500

Terminal: iTerm
`$TERM`: xterm-256color
`$SHELL`: ZSH

**Comment by bfrg** [comment]
You need to use _variable arguments_ for your function:

```vim
vim9script

def TheFunction(...some: list<string>)
    echomsg some
enddef

command -nargs=* TheCommand TheFunction(<f-args>)

# Output: []
TheCommand

# Output: ['1', '2', '3']
TheCommand 1 2 3
```

This is explained under `:h vim9-variable-arguments`.
