### ISSUE TITLE
"You discovered command-line window!..." message cannot be translated

### ISSUE THREAD

**Issue by eevan78** [vim/vim#12371]
I have seen that the mesage shown after q: command cannot be translated.
Is it possible to make it translatable?

**Comment by brammool** [comment]
> I have seen that the mesage shown after q: command cannot be translated.
> Is it possible to make it translatable?

This text is found in the defaults.vim script, not in source code.  But
yes, it is possible to get it translated.  I'll add the changes, we then
have to wait for translators to pick it up and add the translation.

-- 
How To Keep A Healthy Level Of Insanity:
1. At lunch time, sit in your parked car with sunglasses on and point
   a hair dryer at passing cars. See if they slow down.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
