### ISSUE TITLE
'set enc=utf-8(latin1)' adds one more vim's installed path to $path

### ISSUE THREAD

**Issue by xvim64** [vim/vim#12372]
### Steps to reproduce

1. > gvim --clean
2. > :set clipboard=unnamed
3. > :let @+ = $path
4. (paste)
5. > :set enc=utf-8
6. > :let @+ = $path
7. (paste)
8. > :set enc=latin1
9. > :let @+ = $path
10. (paste)

![002](https://github.com/vim/vim/assets/83569599/c34bdb8b-9256-4c4a-a7d9-f3520843de9b)

### Expected behaviour

no duplicates in $path

### Version of Vim

9.0.1536

### Environment

Windows 11 x64 22H2

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> 1. > gvim --clean
> 2. > :set clipboard=unnamed
> 3. > :let @+ = $path
> 4. (paste)
> 5. > :set enc=utf-8
> 6. > :let @+ = $path
> 7. (paste)
> 
> ![001](https://github.com/vim/vim/assets/83569599/e8884ffa-3945-414c-8713-46cc37953e49)

This happens in mch_get_exe_name(), when changing 'encoding' non-ascii
characters in the path may become invalid.  We could add a check if the
added path is already there to catch the most common case.  A more
complicated solution would be to remember what was added before and
remove that before adding the updated value.

Anyone wants to make a PR for this?

-- 
How To Keep A Healthy Level Of Insanity:
14. Put mosquito netting around your work area. Play a tape of jungle
    sounds all day.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
> Anyone wants to make a PR for this?

I've created #12400.
