### ISSUE TITLE
“Buffer contents equals file contents.” … then delete it!

### ISSUE THREAD

**Issue by FGasper** [vim/vim#1237]
I frequently work with vim via a network connection and oftentimes have to close the laptop or some such without “gracefully” shutting down VPN etc.

This means that when I reopen the files I was editing, I get the warning about a pre-existing swap file.

More often than not, if I click “recover”, it tells me that the buffer contents equal the file contents. It then tells me to delete the swap file.

It would be SUPER convenient if it just detected this and blew away the old swap file for me rather than making me find it and delete it.

**Comment by hvhaugwitz** [comment]
I second this feature request. Please consider to add an option to both recover and delete the swap file afterwards.

**Comment by chrisbra** [comment]
you might want to check out [Recover.vim](https://github.com/chrisbra/Recover.vim)

**Comment by FGasper** [comment]
A plugin is a nice thing, but this seems relevant as core functionality rather than something that has to be installed and maintained separately. I personally probably use about 10+ copies of vim; it would be awkward to maintain a plugin installation on them all.

**Comment by k-takata** [comment]
If the buffer contents is equal, I often do `:e` to reopen the file, then type `d` to delete the swap file.
But I agree that it would be nice if there is an option that if it detect this then delete it automatically.

**Comment by chrisbra** [comment]
I am not sure, what you mean with **maintain the plugin**. I am maintaining it. Also note, that if it can be implemented in a plugin it is easier available, allows faster implementation and vim script is significant easier to maintain than to write C code which is likely to introduce bugs.

**Comment by nuko8** [comment]
If I understand correctly, @FGasper's concerns -- having to install the plugin for each Vim on every machine he is working with, and keep updating all of them afterwards -- would all disappear if it were a default plugin like netrw.  Personally, I do think the plugin helps people more appreciate the role of `*.swp` files and, to some extent, stop comparing them to stuff from one's back end :)

**Comment by sigvaldm** [comment]
I couldn't agree more with with @FGasper.

**Comment by schveiguy** [comment]
Awesome! Just installed latest vim and my mac froze had to be restarted, and this is working perfectly! Thanks @brammool

**Comment by sigvaldm** [comment]
Haven't tested yet, but thanks!
