### ISSUE TITLE
ExitPre not triggered on `:wqa`

### ISSUE THREAD

**Issue by bartlibert** [vim/vim#12374]
### Steps to reproduce

1. Create a minimal vimrc with the following content (e.g. in `/tmp/vimrc`)
```
autocmd ExitPre * echo input('ExitPre')
```
2.  Start vim with this vimrc file: 
```
vim -u /tmp/vimrc
```
3. Type `:wqa`

### Expected behaviour

I would expect to see the input prompt `ExitPre` shown. Instead, vim just quits without the prompt.
When using `:qa` or `:wq`, the prompt is shown, `:wqa` is the exepction.

### Version of Vim

9.0.1506

### Environment

Operating system: arch linux
Terminal: wezterm
Shell: bash
$TERM: wezterm (but also reproducible with TERM=xterm)

**Comment by chrisbra** [comment]
I tried something silly:
```viml
autocmd ExitPre * :!touch /tmp/exit_vim
```

That seems to be triggered on `:wqa`, so I guess it might be too late for the `input()` call to get some interactive information from the user?

**Comment by bartlibert** [comment]
@chrisbra When I put this in my test setup, it does not work either. The file is not created on `:wqa`, but it is on `:qa` for example

**Comment by chrisbra** [comment]
oh, you are right, I must have messed up my test.
