### ISSUE TITLE
Problems when moving the cursor with 'smoothscroll' and 'virtualedit'

### ISSUE THREAD

**Issue by luukvbaal** [vim/vim#12386]
### Steps to reproduce

1. Run `vim --clean`
2. Source the following file:
```vim
set smoothscroll scrolloff=0 lines=14 columns=80 virtualedit=all
call setline(1, [ 'aaaaa'->repeat(150), 'bbbbb '->repeat(7) .. 'ccccc '->repeat(7) .. 'ddddd '->repeat(7) ])
```
3. Press <kbd>9\<C-E\>gk</kbd>
4. Move the cursor to the start of the wrapped line and note that it disappears under the <<< smoothscroll marker. Pressing <kbd>h</kbd> repeatedly or <kbd>g0</kbd> both show this problem.
5. Press <kbd>h</kbd> one more time which should bring the cursor one wrapped line up, note we still don't scroll up and the drawn cursor position is invalid.

### Expected behaviour

4. Should decrement `w_skipcol` when the cursor is moved under the smoothscroll marker, this happens correctly when `'virtualedit' == "none"` but not when it is `"all"`.
5. Ditto.

### Version of Vim

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled May 12 2023 12:27:39) Included patches: 1-1544

### Environment

Operating system: Arch Linux
Terminal: st
Value of $TERM: st-256color
Shell: zsh

**Comment by luukvbaal** [comment]
Actually the problem in step 4. when pressing `<kbd>g0</kbd>` is also present without `'virtualedit'`.

**Comment by luukvbaal** [comment]
> Actually the problem in step 4. when pressing g0 is also present without `'virtualedit'`.

This is easily fixed with:
```diff
diff --git a/src/normal.c b/src/normal.c
index 2f3d12a41..07201341a 100644
--- a/src/normal.c
+++ b/src/normal.c
@@ -5762,6 +5762,7 @@ nv_g_home_m_cmd(cmdarg_T *cap)
        curwin->w_valid &= ~VALID_WCOL;
     }
     curwin->w_set_curswant = TRUE;
+    adjust_skipcol();
 }

 /*
```

**Comment by brammool** [comment]
It looks like the patch fixes this.  Or is there a remaining problem?
The original repro steps don't work exactly as listed, the cursor is on the first character in the first line.  Moving it down with "gj" and using CTRL-E is needed before being able to reproduce the original problem.

**Comment by luukvbaal** [comment]
> It looks like the patch fixes this. Or is there a remaining problem?

No I don't think so, the patch covers both problems. Closing.

> The original repro steps don't work exactly as listed, the cursor is on the first character in the first line. Moving it down with "gj" and using CTRL-E is needed before being able to reproduce the original problem.

Indeed.

**Comment by luukvbaal** [comment]
>> The original repro steps don't work exactly as listed, the cursor is on the first character in the first line. Moving it down with "gj" and using CTRL-E is needed before being able to reproduce the original problem.

> Indeed.

Oh it was an issue with GitHub formatting, the steps include `<C-E>` but are hidden because I wrapped it in `<kbd>`...
