### ISSUE TITLE
<ESC> and <LEFT> can't be recognized in vimrc

### ISSUE THREAD

**Issue by suiyuan2009** [vim/vim#1239]
I'm using vim8.0, version 8.0.23.
this is my [vimrc](https://gist.github.com/suiyuan2009/4ad739f20d71940043e79eb24ac5181e) file in ~/.vimrc.
I find these lines not working,
```
:map <C-j> <ESC>:tabp<CR>
:map <C-k> <ESC>:tabn<CR>
inoremap { {}<LEFT>
inoremap ( ()<LEFT>
inoremap [ []<LEFT>
```
and when I type `{`, I just get `{}<LEFT>` in insert mode.

**Comment by vim-ml** [comment]
Hi Ziming,

2016-11-8(Tue) 13:36:28 UTC+9 Ziming Dong:

> I'm using vim8.0, version 8.0.23.
> 
> this is my vimrc file in ~/.vimrc.
> 
> I find these lines not working,
> :map <C-j> <ESC>:tabp<CR>
> :map <C-k> <ESC>:tabn<CR>
> inoremap { {}<LEFT>
> inoremap ( ()<LEFT>
> inoremap [ []<LEFT>
> 
> and when I type {, I just get {}<LEFT> in insert mode.

Perhaps the mapping command is do in vi-compatible mode.

Let's confirm!
Please add below two lines just before `:map <C-j> <ESC>:tabp<CR>` in your .vimrc and start Vim.
And tell me the result of :messages

echom 'compatible:' &cp
echom 'cpoptions:' &cpo

## 

Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by suiyuan2009** [comment]
@vim-ml 

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
compatible: 0
cpoptions: aAbBcCdDeEfFgHiIjJkKlLmMnoOpPqrRsStuvwWxXyZ$!%*-+<>;
```

**Comment by mattn** [comment]
Please try this:

```
:verbose inoremap {
```

**Comment by vim-ml** [comment]
Hi Ziming,

2016-11-8(Tue) 15:46:44 UTC+9 Ziming Dong:

> @vim-ml 
> 
> Messages maintainer: Bram Moolenaar Br...@vim.org
> compatible: 0
> cpoptions: aAbBcCdDeEfFgHiIjJkKlLmMnoOpPqrRsStuvwWxXyZ$!%*-+<>;

If `<` is included in `cpoptions` option, You can see the behavior you reported.
Have you changed this option in debian.vim or /etc/vim/vimrc.local?

Tentatively, I think that setting the mapping command later than line of `set nocompatible` will fix the problem.

## 

Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by suiyuan2009** [comment]
@vim-ml thank you, it works. I'm sorry to ask help in the issue list.

**Comment by suiyuan2009** [comment]
I'm using [this guide](https://github.com/Valloric/YouCompleteMe/wiki/Building-Vim-from-source) to upgrade vim7.4 to vim8.0 on ubuntu14.04, I haven't changed `debian.vim`, and there is no `vimrc.local` in `/etc/vim/`, only `vimrc.tiny`.

**Comment by chrisbra** [comment]
please ask user questions on vim-use ml. This is not the correct place to ask user questions here. thanks.
