### ISSUE TITLE
E520: Not allowed in a modeline: viminfo=""

### ISSUE THREAD

**Issue by ucomru** [vim/vim#12404]
Good day!

I'v put last line to the txt file:
```
vim:noswf:noudf:viminfo="":ft=markdown:cole=2:cc=80:ts=2:sw=2
```

all commands in the `modeline` work correctly, but command `vi=""` or `viminfo=""` raise error:

```
Error detected while processing modelines:
E520: Not allowed in a modeline: viminfo=""
```

It would be very useful to use a feature `vi=""` in the `modeline` for special files, for example for the crypted files, etc.

**Comment by chrisbra** [comment]
as mentioned in the documentation [:h 'viminfo'](https://vimhelp.org/options.txt.html#%27viminfo%27):
> This option cannot be set from modeline or in the sandbox for security reasons.

So this doesn't seem to be a good idea.

**Comment by brammool** [comment]
> I'v put last line to the txt file:
> ```
> vim:noswf:noudf:viminfo="":ft=markdown:cole=2:cc=80:ts=2:sw=2
> ```
> 
> all commands in the `modeline` work correctly, but command `vi=""` or `viminfo=""` raise error:
> 
> ```
> Error detected while processing modelines:
> E520: Not allowed in a modeline: viminfo=""
> ```
> 
> It would be very useful to use a feature `vi=""` in the `modeline` for
> special files, for example for the crypted files, etc.

As Christian mentioned, changing 'viminfo' from a modeline has the risk
that editing a file that someone else created changes this option value
in a way that can be abused.  E.g. by setting another name for the
viminfo file.

Also, 'viminfo' is a global option, used for all the files.  Setting a
different value for one specific file does not make sense.

-- 
On the other hand, you have different fingers.
                                      -- Steven Wright

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
closing this.
