### ISSUE TITLE
Display moves up and down with 'incsearch' and 'smoothscroll'

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#12409]
### Steps to reproduce

1. Run `vim --clean`
2. Source the following file:
```vim
set incsearch
7split
50vnew
setlocal number scrolloff=0 smoothscroll
call setline(1, repeat([''], 20))
call setline(11, repeat('a', 100))
call setline(14, 'bbbb')
```
3. Type `/bbbb`, and display moves up and down on every `b` keystroke

### Expected behaviour

Display doesn't move up and down when the highlighted match's position is the same

### Version of Vim

9.0.1563

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

**Comment by zeertzjq** [comment]
Bisected to [patch 9.0.1525](https://github.com/vim/vim/commit/3ce8c389155fc1257082cdb0cef7801b49f6aaf9)

**Comment by luukvbaal** [comment]
So before patch 9.0.1525 the cursor was scrolled half-way but w_skipcol was immediately reset (thus not placing the cursor halfway). After the patch it is placed in the middle each time but the reset is alternated due to the new `curwin->w_skipcol == old_skipcol` condition on `reset_skipcol()` which is still incorrect apparently.

**Comment by zeertzjq** [comment]
Yes this `curwin->w_skipcol == old_skipcol` looks unreliable.

**Comment by luukvbaal** [comment]
TBH I think we don't need to reset skipcol at all anymore there. This results in failing tests which is why I added this condition instead last time. I think we can adjusts the tests instead.

**Comment by brammool** [comment]
> TBH I think we don't need to reset skipcol at all anymore there. This
> results in failing tests which is why I added this condition instead
> last time. I think we can adjusts the tests instead.

Are you going to make a PR for this?

-- 
The 50-50-90 rule: Anytime you have a 50-50 chance of getting
something right, there's a 90% probability you'll get it wrong.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
