### ISSUE TITLE
setqflist, setloclist with action " " (new list) overrides &l:statusline, window ID is the same

### ISSUE THREAD

**Issue by lbrayner** [vim/vim#12414]
### Steps to reproduce

1. `vim --clean`
2. `call setloclist(0, [], " ", {"title": "hello"})`
3. `:lopen`
4. `:echo win_getid()`
5. `:setlocal &stl=%f`
6. `:wincmd w`
7. `:call append(0, "abcd")`
8. `:lgrep /abcd/`
9. `:wincmd w`
10. `:echo win_getid()`

### Expected behaviour

Local variable 'statusline' is not overridden with the default value and stays `%f`.

### Version of Vim

8.2.2434

### Environment

Ubuntu 20.04
st
st-256color
zsh

**Comment by lacygoill** [comment]
Add this line to your vimrc:

    let g:qf_disable_statusline = 1

See [`:help ft-qf-plugin`](https://vimhelp.org/filetype.txt.html#ft-qf-plugin).

**Comment by lbrayner** [comment]
Yes, @lacygoill, that worked! Thank you!
