### ISSUE TITLE
Popup menu does not default to below the cursor

### ISSUE THREAD

**Issue by matt-gardner** [vim/vim#1241]
A [recent patch](https://github.com/vim/vim/commit/91e44a3305ef6bf2d43496c351dcff0a45c6bfb8#diff-d21807d1e6c9ea7784b05e18791acca5R106) introduced a bug that removed `pum_height` from the consideration of where to put the popup menu.  After that patch, the popup menu always shows up above the cursor when the cursor is in the bottom half of the screen, even when there is plenty of space below the cursor for the popup menu to be displayed.  This behavior is pretty obviously seen in the line of code that I linked, and pretty obviously not desirable, based on the comment directly above that line.

**Comment by matt-gardner** [comment]
Here are a couple of screenshots that demonstrate the problem:

![screen shot 2016-11-08 at 8 21 18 am 2](https://cloud.githubusercontent.com/assets/3291951/20107240/9b5c7668-a58c-11e6-889b-960160d7e899.png)

![screen shot 2016-11-08 at 8 21 07 am 2](https://cloud.githubusercontent.com/assets/3291951/20107260/af5b961c-a58c-11e6-87d6-d49e20217f49.png)

The second one has a very long popup menu, but it still should show up on the bottom, clipped, because there is plenty of space below (and this was the behavior prior to the Nov. 4th patch).

**Comment by matt-gardner** [comment]
For comparison, here are the same screenshots using the commit just prior to that patch:

![screen shot 2016-11-08 at 8 28 11 am 2](https://cloud.githubusercontent.com/assets/3291951/20107434/605e077e-a58d-11e6-876a-2c9f98120900.png)
![screen shot 2016-11-08 at 8 28 15 am 2](https://cloud.githubusercontent.com/assets/3291951/20107441/63b6233e-a58d-11e6-842e-ca22b05b71d7.png)

**Comment by vim-ml** [comment]
Hi Matt and list,

2016-11-9(Wed) 1:29:38 UTC+9 Matt Gardner:

> For comparison, here are the same screenshots using the commit just prior to that patch:

Oh, sorry.
I wrote a patch that respects the original behavior.
Please confirming this.

## Thanks for the reporting and suggestions!

Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by matt-gardner** [comment]
I applied the patch and tested it in a few situations, and it looks to me like it fixed the problem.  Thanks!

**Comment by vim-ml** [comment]
Hi Matt, Bram and list!

2016-11-9(Wed) 6:00:50 UTC+9 Matt Gardner:

> I applied the patch and tested it in a few situations, and it looks to me like it fixed the problem.  Thanks!

Thanks for confirming my patch.

Bram>
Are there concerns about my patch?
(I feel somehow you are busy now :-)

## 

Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by brammool** [comment]
Hirohito Higashi wrote:

> Hi Matt, Bram and list!
> 
> 2016-11-9(Wed) 6:00:50 UTC+9 Matt Gardner:
> 
> > I applied the patch and tested it in a few situations, and it looks to me like it fixed the problem.  Thanks!
> 
> Thanks for confirming my patch.
> 
> Bram>
> Are there concerns about my patch?
> (I feel somehow you are busy now :-)

It's near the top of the todo list.

Yeah, busy.  Still send out a couple of patches each day.  Crashes have
priority.  And wasted time on trying to figure out this problem:

Test_help_complete sometimes fails on MS-Windows:
function RunTheTest[9]..Test_help_complete line 22: Expected ['h test-char@ab',
'h test-char@en', 'h test-col@ab', 'h test-col@en'] but got ['h test-char@en', '
h test-char@en\t', 'h test-col@ab', 'h test-col@en']
Appears to be related to calling feedkeys() with exactly 8 characters.

Only happens in console version.  My MSVC debugger stopped working, it's
a bit difficult to figure this out without a debugger...

## 

How To Keep A Healthy Level Of Insanity:
15. Five days in advance, tell your friends you can't attend their
    party because you're not in the mood.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
Hi Bram,

2016-11-16(Wed) 6:01:31 UTC+9 Bram Moolenaar:

> Hirohito Higashi wrote:
> 
> > Hi Matt, Bram and list!
> > 
> > 2016-11-9(Wed) 6:00:50 UTC+9 Matt Gardner:
> > 
> > > I applied the patch and tested it in a few situations, and it looks to me like it fixed the problem.  Thanks!
> > 
> > Thanks for confirming my patch.
> > 
> > Bram>
> > 
> > Are there concerns about my patch?
> > 
> > (I feel somehow you are busy now :-)
> 
> It's near the top of the todo list.
> 
> Yeah, busy.  Still send out a couple of patches each day.  Crashes have

Please keep your good health. ( ˘ω˘)

> priority.  And wasted time on trying to figure out this problem:
> 
> Test_help_complete sometimes fails on MS-Windows:
> 
> function RunTheTest[9]..Test_help_complete line 22: Expected ['h test-char@ab',
> 
> 'h test-char@en', 'h test-col@ab', 'h test-col@en'] but got ['h test-char@en', '
> 
> h test-char@en\t', 'h test-col@ab', 'h test-col@en']
> 
> Appears to be related to calling feedkeys() with exactly 8 characters.
> 
> Only happens in console version.  My MSVC debugger stopped working, it's
> 
> a bit difficult to figure this out without a debugger...

I can't reproduce it on my environment.
However, I am happy if you can adopt one of the following three patch.

Patch 1: I heard from Taro Muraoka ...
"It seems to be stable if you insert `sleep 100m` before s:get_cmd_compl_list()."

diff --git a/src/testdir/test_help_tagjump.vim b/src/testdir/test_help_tagjump.vim
index 778bd9c..2fe57ef 100644
--- a/src/testdir/test_help_tagjump.vim
+++ b/src/testdir/test_help_tagjump.vim
@@ -111,6 +111,7 @@ func Test_help_complete()
       " 'helplang=' and help file lang is 'en' and 'ab'
       set rtp+=Xdir1/doc-ab
       set helplang=
-      sleep 100m
     let list = s:get_cmd_compl_list(":h test")
     call assert_equal(sort(['h test-col@en', 'h test-col@ab',
           \             'h test-char@en', 'h test-char@ab']), sort(list))

```
Patch 2: Use `c_CTRL-A` instead of loops and `c_CTRL-B`.
Attached patch: p2_maybe_fix_help_complete_problem.patch

```

Patch 3: Use getcompletion() function.
Attached patch: p3_maybe_fix_help_complete_problem.patch

## 

Best regards,
Hirohito Higashi (a.k.a. h_east)
