### ISSUE TITLE
SpellCap highlight not shown if blank line above is folded

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#12420]
### Steps to reproduce

1. Run `vim --clean`
2. Source the following file:
```vim
call setline(1, ['hello', 'world', '', 'hello', 'world'])
set spell
```
3. The `hello` on lines 1 and 4 are highlighted
4. Run `1,3fold`
5. The `hello` on line 4 is no longer highlighted

### Expected behaviour

The `hello` on line 4 is still highlighted

### Version of Vim

9.0.1506

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

**Comment by luukvbaal** [comment]
I also notice that when inserting an empty line before a non-capitalized word, the spellcap highlight is not added until a redrawn on that line is forced. Would it be reasonable to force a redraw for the current and next line when editing and 'spell' is enabled?

In any case, I will write a testcase and raise a PR for the fold issue.

**Comment by brammool** [comment]
> I also notice that when inserting an empty line before a
> non-capitalized word, the spellcap highlight is not added until a
> redrawn on that line is forced. Would it be reasonable to force a
> redraw for the current and next line when editing and 'spell' is
> enabled?

Of course it's nicer when the display is always up-to-date.  In general,
if spell checking is enabled and text at the end of a line is changed
then the SpellCap highlight of the next line may need to be updated.  To
keep it simple, always updating one more line might be good enough, I
doubt it becomes noticable slower.  The logic in win_update() is
complicated though, it doesn't look like just incrementing "mid_end"
will work.  Perhaps it works to increment "mod_bot".

> In any case, I will write a testcase and raise a PR for the fold issue.

That is welcomed.

-- 
hundred-and-one symptoms of being an internet addict:
60. As your car crashes through the guardrail on a mountain road, your first
    instinct is to search for the "back" button.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
