### ISSUE TITLE
system() seems to pass an empty {input} regardless

### ISSUE THREAD

**Issue by peterwu** [vim/vim#12435]
### Steps to reproduce

test-read-stdin.sh
```
#!/bin/bash

printf 'content of file on stdin: %s\n' "$(</dev/stdin)"
```

test-ignore-stdin.sh
```
#!/bin/bash

printf 'ignoring stdin\n'
```

vimscript:
```
nnoremap <leader>s :echo system('/home/peter/test-ignore-stdin.sh')<CR>
nnoremap <leader>t :echo system('/home/peter/test-read-stdin.sh')<CR>
```

steps to reproduce:
1. `$ test-ignore-stdin.sh` # print as expected
2. `$ test-ignore-stdin.sh <<< "test"`  # print as expected
3. `$ test-read-stdin.sh` # hang as it awaits stdin
4. `$ test-read-stdin.sh <<< "test"` # print as expected
5. launch vim
6. invoke `<leader>s` and vim echos correctly
7. invoke `<leader>t` and vim echos as if an empty string was passed as {input} to system()

### Expected behaviour

`:help system()` says:

```
system({expr} [, {input}])				*system()* *E677*
		Get the output of the shell command {expr} as a |String|.  See
		|systemlist()| to get the output as a |List|.

		When {input} is given and is a |String| this string is written
		to a file and passed as stdin to the command.  The string is
		written as-is, you need to take care of using the correct line
		separators yourself.
```

The interpretation is that if {input} is NOT passed, then there will be nothing being passed to {expr}. However, based on the tests above, it seems that vim will generate a file with an empty string and pass it as stdin to the command. I don't think this is the intended behavior of system().

### Version of Vim

9.0.1563

### Environment

OS: Fedora 38
Terminal: kitty 0.28.1
$TERM: xterm-kitty
Shell: bash

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> test-read-stdin.sh
> ```
> #!/bin/bash
> 
> printf 'content of file on stdin: %s\n' "$(</dev/stdin)"
> ```
> 
> test-ignore-stdin.sh
> ```
> #!/bin/bash
> 
> printf 'ignoring stdin\n'
> ```
> 
> vimscript:
> ```
> nnoremap <leader>s :echo system('/home/peter/test-ignore-stdin.sh')<CR>
> nnoremap <leader>t :echo system('/home/peter/test-read-stdin.sh')<CR>
> ```
> 
> steps to reproduce:
> 1. `$ test-ignore-stdin.sh` # print as expected
> 2. `$ test-ignore-stdin.sh <<< "test"`  # print as expected
> 3. `$ test-read-stdin.sh` # hang as it awaits stdin
> 4. `$ test-read-stdin.sh <<< "test"` # print as expected
> 5. launch vim
> 6. invoke `<leader>s` and vim echos correctly
> 7. invoke `<leader>t` and vim echos as if an empty string was passed as {input} to system()
> 
> ### Expected behaviour
> 
> `:help system()` says:
> 
> ```
> system({expr} [, {input}])				*system()* *E677*
> 		Get the output of the shell command {expr} as a |String|.  See
> 		|systemlist()| to get the output as a |List|.
> 
> 		When {input} is given and is a |String| this string is written
> 		to a file and passed as stdin to the command.  The string is
> 		written as-is, you need to take care of using the correct line
> 		separators yourself.
> ```
> 
> The interpretation is that if {input} is NOT passed, then there will
> be nothing being passed to {expr}. However, based on the tests above,
> it seems that vim will generate a file with an empty string and pass
> it as stdin to the command. I don't think this is the intended
> behavior of system().

What brings you to the observation that Vim generates an empty file?  I
can't find anything pointing in that direction.  Isn't it that the shell
script is trying to read stdin, but it's unreadable and just ends up
reading nothing, as if reading /dev/null.  It might have something to do
with how /dev/stdin behaves.


-- 
UPS - Unknown Package Status

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
