### ISSUE TITLE
illegal font cause gvim for win32 to crash

### ISSUE THREAD

**Issue by HenryHu** [vim/vim#1243]
set guifont=Consolas\ for\ Powerline\ FixedD\ 11
and gvim crashes. I don't have this font.
set guifont=Consolas\ for\ Powerline\ FixedD
Seems to be fine. It just says "invalid font".

**Comment by HenryHu** [comment]
It seems like that
set guifont=AAAAAAAAAAAAAAAAAAAAAAAAA
(replace everything with A)
would also crash. Only the length matters.

**Comment by tonymec** [comment]
You seem to be using a GTK2/GTK3 'guifont' value in a Windows gvim.

See http://vim.wikia.com/wiki/Setting_the_font_in_the_GUI or ":help setting-guifont" for examples of how to write a platform-independent vimrc to set 'guifont' appropriately for whichever OS you happen to be running on.

OTOH, the code should not crash, even if (like here) the user gives nonsensical commands.

Best regards,
Tony.

**Comment by k-takata** [comment]
Please try this:

``` patch
--- a/src/os_mswin.c
+++ b/src/os_mswin.c
@@ -2920,7 +2920,7 @@ get_logfont(
      */
     for (p = name; *p && *p != ':'; p++)
     {
-   if (p - name + 1 > LF_FACESIZE)
+   if (p - name + 1 >= LF_FACESIZE)
        goto theend;            /* Name too long */
    lf->lfFaceName[p - name] = *p;
     }
```

Font name must not exceed LF_FACESIZE (32) characters including the last NUL.
