### ISSUE TITLE
The libxt-dev depends should be checked with the configure script.

### ISSUE THREAD

**Issue by ziggy1030** [vim/vim#12439]
### Steps to reproduce

1.run "./configure" without installing "libxt-dev" and related depends.
2.Configuring finished and got no error.
3.After compling,"/usr/bin/" got no "gvim"
4.Launch "vim --version" with the terminal, noticed that the "vim" does  not support gui feature.
5.Compile again,got the same error.
6. I found it probably depends "libxt-dev" head files.
7. After installing that,I compile vim again,and it supports gui feature this time.

### Expected behaviour

It should check the "libxt" head files with the configure script.

### Version of Vim

9.0.1572

### Environment

Operating System:deepin V20.9

**Comment by chrisbra** [comment]
shouldn't you use `--enable-gui=gtk3 --fail-if-missing` ?

**Comment by AppJ-GS** [comment]
> shouldn't you use `--enable-gui=gtk3 --fail-if-missing` ?

Thanks,I will try this way next version

**Comment by AppJ-GS** [comment]
> You can build Vim without GUI, so this is just fine. If you look at the configure output you can see why it decided to not build the GUI version. You can use that as hint for what package might be needed.
> 
> What packages you would need to install depends on what GUI you want and what those packages are called on your specific system. The number of combinations is huge, and it constantly changes, therefore trying to provide instructions in the Vim distribution is close to impossible. Just use your favorite search engine to find hints, or use pre-build Vim packages for your system.

I see,but I need to compile the GUI version and upload as simple gui apps.I will try the way by @chrisbra
