### ISSUE TITLE
Incorrect encoding of the text "Open in Vim" in the system context menu with the value enc=utf-8

### ISSUE THREAD

**Issue by RestorerZ** [vim/vim#12431]
### Steps to reproduce

1. To check, open the Windows Explorer window and open the system context menu by right‐clicking on some text file.
The translated menu item "Open in Vim" is displayed correctly, as can be seen in the screenshot.

![explorer_cntx_menu858cbd81969955e8.png](https://imgbb.su/images/2023/05/23/explorer_cntx_menu858cbd81969955e8.png)

2. Run the program `gvim -u NONE --noplugin -c "set enc=utf-8"`
3. Enter the command `:browse confirm e` (or menu File -> Open). On the same text file, open the system context menu by clicking the right mouse button.
The translated menu item "Open in Vim" is displayed incorrectly, as seen in the screenshot.

![vim_utf8-cntx_menu15adaa7778db9a0f2.png](https://imgbb.su/images/2023/05/23/vim_utf8-cntx_menu15adaa7778db9a0f2.png)

Closing the program gVim.
4. Run the program `gvim -u NONE --noplugin -c "set enc=cp1251"`
5. Enter the command `:browse confirm e` (or menu File -> Open). On the same text file, open the system context menu by clicking the right mouse button.
The translated menu item "Open in Vim" is displayed correctly, as seen in the screenshot.

![vim_cp1251-cntx_menu1b379f8a0d42fd250.png](https://imgbb.su/images/2023/05/23/vim_cp1251-cntx_menu1b379f8a0d42fd250.png)

### Expected behaviour

Correct display of the system context menu items in conformance with the encoding used in the program Vim.

### Version of Vim

9.0.1572

### Environment

WindowsNT 6.1

**Comment by brammool** [comment]
> ### Steps to reproduce

I assume your system is set to use another language and encoding, looks
like Russian to me.

You appear to use the system context menu, something that Vim has no
control over.  Vim uses the functions GetSaveFileNameW() and
GetOpenFileNameW(), what happens in there is hidden.  The argument
passed does not appear to include a field for encoding.

First thoughts are that this is not a Vim problem but something in the
system using the wrong encoding.  No idea how the encoding set inside
Vim can even influence this.

I'm not going to spend time on this, but perhaps there is someone who
knows MS-Windows stuff and can guess what to try to make this work
better.

-- 
hundred-and-one symptoms of being an internet addict:
64. The remote to the T.V. is missing...and you don't even care.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by tonymec** [comment]
Hm.
1. Try the following:
```
gvim --clean
:set enc?
:lang cty
```
What is the answer to each of the two ex-commands above?

2. Save your vimrc somewhere safe under a different name and replace it by the following:
```vim
scriptencoding utf-8
if &tenc == ""
    let &tenc = &enc
endif
if &enc !~? '^u'
    set enc=utf-8
endif
set fencs=ucs-bom,utf-8,cp1251
```
Is the result better when you try the testcase in your post above? If it is, try merging the missing lines near the top of your vimrc while bringing the latter back.

Best regards,
Tony.

**Comment by tonymec** [comment]
P.S. @brammool :
* "Открыть в программе Vim" is Russian for "Open in Vim";
* "Открыть в работающей программе Vim [Безыменный] - GVIM" is Russian for "Open in existing Vim [No Name] - GVIM".

**Comment by k-takata** [comment]
In the current implementation, GvimExt uses the current code page to get the translated strings via gettext.

However, when the context menu is opened inside `:browse confirm e`, GvimExt is loaded inside the Vim process and gettext in the same process is used for GvimExt. So, gettext returns the translated strings in UTF-8.

We might need to set the encoding via `bind_textdomain_codeset()` when getting the translated strings for GvimExt and restore the encoding after it is finished.

(And/or modify GvimExt to always use UTF-8 instead of the current code page.)

**Comment by RestorerZ** [comment]
@k-takata

> In the current implementation, GvimExt uses the current code page to get the translated strings via gettext.
> 
> However, when the context menu is opened inside `:browse confirm e`, GvimExt is loaded inside the Vim process and gettext in the same process is used for GvimExt. So, gettext returns the translated strings in UTF-8.

Thank you for the explanation. Now it is clear why this is happening.


> (And/or modify GvimExt to always use UTF-8 instead of the current code page.)

This is probably a good way, but what happens if the CP1251 encoding is used in Vim?
Will there be the same unreadable text in the context menu again? There may not be many cases when CP1251 is used as an internal Vim encoding, but it can't be excluded either.


> We might need to set the encoding via `bind_textdomain_codeset()` when getting the translated strings for GvimExt and restore the encoding after it is finished.

If you have such an occasion, then try to do it.
This error is not critical. And few people call the system context menu inside Vim, but it would be good if there were no such shortcomings.

**Comment by brammool** [comment]
> @k-takata
> 
> > In the current implementation, GvimExt uses the current code page to get the translated strings via gettext.
> > 
> > However, when the context menu is opened inside `:browse confirm e`, GvimExt is loaded inside the Vim process and gettext in the same process is used for GvimExt. So, gettext returns the translated strings in UTF-8.
> 
> Thank you for the explanation. Now it is clear why this is happening.
> 
> 
> > (And/or modify GvimExt to always use UTF-8 instead of the current code page.)
> 
> This is probably a good way, but what happens if the CP1251 encoding is used in Vim?
> Will there be the same unreadable text in the context menu again? There may not be many cases when CP1251 is used as an internal Vim encoding, but it can't be excluded either.
> 
> 
> > We might need to set the encoding via `bind_textdomain_codeset()` when getting the translated strings for GvimExt and restore the encoding after it is finished.
> 
> If you have such an occasion, then try to do it.
> This error is not critical. And few people call the system context menu inside Vim, but it would be good if there were no such shortcomings.

MS-Windows uses "wide" functions in most places, which is using UTF-16.
Then it doesn't depend on the current code page, right?  Perhaps we can
use "wide" functions in GvimExt?

-- 
"Thou shalt not follow the Null Pointer, for at its end Chaos and
Madness lie."

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
