### ISSUE TITLE
python buffer.append behaves strangely (compared to vimL append).

### ISSUE THREAD

**Issue by hardenedapple** [vim/vim#12432]
### Steps to reproduce

CAVEAT:  I'm not certain this is a bug, but it seemed strange enough to report in case it's not on purpose.

1. Open test file with below text in it.
```
line1
line2
line3
```
2. Move to line 3 (with `G`).
3. `:python3 vim.buffers[1].append(['hello', 'world'], 2)`

Observation is that cursor ends up at start of `hello` on third line.
```
line1
line2
[h]ello
world
line3
```

### Expected behaviour

I would have expected that the text is inserted, and cursor stays on the text `line3`.

```
line1
line2
hello
world
[l]ine3
```

This is what happens when calling vimL `append(2, ['hello', 'world'])`, and also happens to be what neovim does with the `python3` command above.
I *thought* it was what happened on earlier vim versions -- but have not checked that so could be misremembering.

### Version of Vim

8.2.4919

### Environment

Multiple environments.

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> CAVEAT:  I'm not certain this is a bug, but it seemed strange enough to report in case it's not on purpose.
> 
> 1. Open test file with below text in it.
> ```
> line1
> line2
> line3
> ```
> 2. Move to line 3 (with `G`).
> 3. `:python3 vim.buffers[1].append(['hello', 'world'], 2)`
> 
> Observation is that cursor ends up at start of `hello` on third line.
> ```
> line1
> line2
> [h]ello
> world
> line3
> ```
> 
> ### Expected behaviour
> 
> I would have expected that the text is inserted, and cursor stays on the text `line3`.
> 
> ```
> line1
> line2
> hello
> world
> [l]ine3
> ```
> 
> This is what happens when calling vimL `append(2, ['hello',
> 'world'])`, and also happens to be what neovim does with the `python3`
> command above.
> I *thought* it was what happened on earlier vim versions -- but have
> not checked that so could be misremembering.

I do not recall changes in this area, it must always have worked this
way.

Whether the cursor is moved when lines are inserted is a choice.
There is something to say for moving it or not moving it.  I can't say
that either is "right" or "wrong".  In cases like this it's better to
just leave it like it is, as changing it can only cause trouble.

Note that if marks are set at the lines, the marks do get moved.

-- 
hundred-and-one symptoms of being an internet addict:
67. Your hard drive crashes. You haven't logged in for two hours.  You start
    to twitch. You pick up the phone and manually dial your ISP's access
    number. You try to hum to communicate with the modem.  You succeed.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
so can we close it and live with the current behaviour?
