### ISSUE TITLE
Error messages E1106 and E1190 are not marked as plural

### ISSUE THREAD

**Issue by RestorerZ** [vim/vim#12443]
### Steps to reproduce

1. Run Vim -u NONE --noplugin
2. Type the following lines:
```
vim9script
echo map([1, 2, 3], () => 1)
```
3. Enter the command `:%so`
An error message will be displayed `E1106: One argument too many`
And it should be `E1106: 2 arguments too many` according to the logic of the map() function, which returns two arguments (index and value), and the test [task](https://github.com/vim/vim/blob/2ac6497f0ef186f0e3ba67d7f0a485bfb612bb08/src/testdir/test_vim9_func.vim#L4267) in the test_vim9_func.vim file.

The situation is similar for the test [task](https://github.com/vim/vim/blob/2ac6497f0ef186f0e3ba67d7f0a485bfb612bb08/src/testdir/test_vim9_import.vim#L1619) in the test_vim9_import.vim file
The same discrepancy is present for error E1190 and the corresponding test tasks in the [test_vim9_builtin.vim](https://github.com/vim/vim/blob/2ac6497f0ef186f0e3ba67d7f0a485bfb612bb08/src/testdir/test_vim9_builtin.vim#L2603) file and the [test_vim9_import.vim](https://github.com/vim/vim/blob/2ac6497f0ef186f0e3ba67d7f0a485bfb612bb08/src/testdir/test_vim9_import.vim#L1667) file

The bug most likely occurred in patch 9.0.0004 (#10606 ). Since build [9.0.0001](https://github.com/vim/vim-win32-installer/releases/tag/v9.0.0001) works correctly.

Also, in my opinion, the [description](https://vim-jp.org/vimdoc-en/vim9.html#E1106) of the E1106 error in the documentation is not entirely correct.

### Expected behaviour

Correct display of the message in accordance with the error conditions.

### Version of Vim

9.0.1572

### Environment

Windows NT6.1

**Comment by brammool** [comment]
I cannot reproduce the problem, the example script does give "2 arguments too many".

I tried on Linux.  Could this be platform dependent? NGETTEXT() has three different implementations, but
I would think they all work the same way.  What does your ":version" output show for "gettext"?

**Comment by RestorerZ** [comment]
Bram, and you will not reproduce it, since the problem turned out to be in a completely different place.
The fact is that in the errors.h file, this error message is split into two separate messages:
```
EXTERN char e_one_argument_too_many[]
	INIT(= N_("E1106: One argument too many"));
EXTERN char e_nr_arguments_too_many[]
	INIT(= N_("E1106: %d arguments too many"));
```
And, accordingly, xgettext puts them in a .po file with two separate msgid, without marking it as msgid_plural:
```
msgid "E1106: One argument too many"
msgstr ""
#, c-format
msgid "E1106: %d arguments too many"
msgstr ""
```
As a consequence, the gettext() function takes the first msgid and returns it.

This problem will be in almost all localized versions of the program.
(For example, this is for Italian:
```
msgid "E1106: One argument too many"
msgstr "E1106: Un argomento di troppo"
msgid "E1106: %d arguments too many"
msgstr "E1106: %d argomenti di troppo"
```
)

With the exception of the translation into Russian from @matveyt , who proposed this patch, and in his [translation](https://github.com/vim/vim/blob/9f3afe7a70d50447424b8d7404aae0d641cd827c/src/po/ru.po#L7665) he simply forcibly combined these lines into msgid_plural:

```
#, no-c-format
msgid "E1106: One argument too many"
msgid_plural "E1106: %d arguments too many"
msgstr[0] "E1106: Один лишний параметр"
msgstr[1] "E1106: %d лишних параметра"
msgstr[2] "E1106: %d лишних параметров"
```
The same applies to the error message E1190.

So somehow it turns out that way.

P. S. Bram, and yet maybe somehow you can improve the description of this error in the documentation.

**Comment by matveyt** [comment]
Yes, I can reproduce it.

```
$ LANG=de_DE vim
:vim9 echo map([1], () => 1)

E1106: Ein Argument zu viel
```

Apparently many translations are missing `msgid_plural` for only the messages of `E1106` and `E1190` (because the source code was previously missing that `ngettext()` call either).

I could make such patch, as it looks like simple machine substitution mostly. Besides, many translations are outdated and don't have new messages translated at all. So there are only twelve to revise: Catalan, German, Esperanto, Spanish, Finnish, Irish, Italian, Japanese, Serbian, Turkish, Ukrainian and Chinese (simplified).

**Comment by brammool** [comment]
> Bram, and you will not reproduce it, since the problem turned out to
> be in a completely different place.
> The fact is that in the errors.h file, this error message is split
> into two separate messages:
> ```
> EXTERN char e_one_argument_too_many[]
> 	INIT(= N_("E1106: One argument too many"));
> EXTERN char e_nr_arguments_too_many[]
> 	INIT(= N_("E1106: %d arguments too many"));
> ```
> And, accordingly, xgettext puts them in a .po file with two separate
> msgid, without marking it as msgid_plural:
> ```
> msgid "E1106: One argument too many"
> msgstr ""
> #, c-format
> msgid "E1106: %d arguments too many"
> msgstr ""
> ```
> As a consequence, the gettext() function takes the first msgid and
> returns it.

That would be ngettext().  It apparently depends on the library used, on
my Linux system it works without msgid_plural.

I can make this work by using a new macro.  Like NGETTEXT() it can be
recognized by xgettext and then will generate msgid_plural in vim.pot.
It is a bit ugly, but it works when I try it.

I found one more: E173.  I'll make a patch, please check if we need to
do this for any other messages.

-- 
hundred-and-one symptoms of being an internet addict:
89. In addition to your e-mail address being on your business
    cards you even have your own domain.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by RestorerZ** [comment]
@brammool 
Bram, I have not found any other messages in the plural.
But another thing came out.
When checking the translation with the script "check.vim" errors appear:
```
Mismatching % in line 13561
msgid:
msgid %d
Mismatching % in line 13562
msgid: %d
msgstr:
```
As I understand it, this is due to the fact that in the message where the singular number is specified, the format output "%d" is not used.
This can be corrected or by adding a comment "no-c-format", as @matveyt did in his translation. Or do as in the error message E173, specifying "%d", which in my opinion is better.

**Comment by brammool** [comment]
> @brammool 
> Bram, I have not found any other messages in the plural.
> But another thing came out.
> When checking the translation with the script "check.vim" errors appear:
> ```
> Mismatching % in line 13561
> msgid:
> msgid %d
> Mismatching % in line 13562
> msgid: %d
> msgstr:
> ```
> As I understand it, this is due to the fact that in the message where
> the singular number is specified, the format output "%d" is not used.
> This can be corrected or by adding a comment "no-c-format", as
> @matveyt did in his translation. Or do as in the error message E173,
> specifying "%d", which in my opinion is better.

Without translation using "one" instead of "1" is easier to read.

At least the GNU docs mention:

	In the English singular case, the number – always 1 – can be
	replaced with "one":

	printf (ngettext ("One file removed", "%d files removed", n), n);

It also mentions that even when using "%d" in the first argument, the
translator may decide to put in a word instead.  printf() will discard
the argument provided.

We better adjust the check script to not give warnings for these
messages.  It should not be too difficult to skip it.  Best we could do
is to check the "%" item in msgid_plural matches any "%" item in
msgstr[] items.  I'll make a patch for that, please check it out.

-- 
From "know your smileys":
 :-O>-o   Smiley American tourist (note big mouth and camera)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by RestorerZ** [comment]
@brammool


> Without translation using "one" instead of "1" is easier to read.

In Russian, too, it is often easier to read when the number is specified in words, not in numerals.

Yes, everything works fine. Thanks!
