### ISSUE TITLE
pi_paren doesn't update highlights of other windows

### ISSUE THREAD

**Issue by yyny** [vim/vim#1244]
Not sure where to report, as it is _not_ reproducible with `vim -N -u NONE` (as mentioned in [CONTRIBUTING.md](./CONTRIBUTING.md)), but _does_ occur with a fresh vim installation.

## Steps to reproduce:

1. Open vim
2. Put the cursor on a parenthesis so it is highlighted (by `pi_paren`)
3. Split the screen (e.g. `:vsp`)
4. Add some lines to scroll the buffer

## Example

![matchparen-bug](https://cloud.githubusercontent.com/assets/6576327/20176342/a471e6d6-a747-11e6-9184-1edf0fbbc8a9.gif)

**Comment by lacygoill** [comment]
Rather than updating the matches, wouldn't it make more sense to remove them?  The purpose of the plugin is to highlight the token under the cursor plus the matching one; but when you leave the right window, the latter does not contain the cursor anymore, so there's no matching token to highlight.

Incidentally, that's what [`vim-matchup`](https://github.com/andymass/vim-matchup) does:

    cd /tmp; git clone https://github.com/andymass/vim-matchup

    cat >/tmp/test.c <<'EOF'
        // This is a example C file
        #include <stdio.h>

        int main(void)

        { // < Pay attention to the highlighting
                printf("Hello, world!!\n");
                return 0;
        }
    EOF

    vim -Nu NORC --cmd 'set rtp^=/tmp/vim-matchup rtp+=/tmp/vim-matchup/after' -S <(cat <<'EOF'
        vs
        wincmd l
        norm! 6G5|
        set ut=100 | au CursorHold * ++once ++nested wincmd h
    EOF
    ) /tmp/test.c

If so, maybe this patch would fix the issue:

```diff
diff --git a/runtime/plugin/matchparen.vim b/runtime/plugin/matchparen.vim
index 59d33f4d4..73f319b70 100644
--- a/runtime/plugin/matchparen.vim
+++ b/runtime/plugin/matchparen.vim
@@ -21,6 +21,7 @@ endif
 augroup matchparen
   " Replace all matchparen autocommands
   autocmd! CursorMoved,CursorMovedI,WinEnter * call s:Highlight_Matching_Pair()
+  autocmd! WinLeave * call s:Remove_Previous_Match()
   if exists('##TextChanged')
     autocmd! TextChanged,TextChangedI * call s:Highlight_Matching_Pair()
   endif
@@ -37,11 +38,7 @@ set cpo-=C
 " The function that is invoked (very often) to define a ":match" highlighting
 " for any matching paren.
 func s:Highlight_Matching_Pair()
-  " Remove any previous match.
-  if exists('w:paren_hl_on') && w:paren_hl_on
-    silent! call matchdelete(3)
-    let w:paren_hl_on = 0
-  endif
+  call s:Remove_Previous_Match()
 
   " Avoid that we remove the popup menu.
   " Return when there are no colors (looks like the cursor jumps).
@@ -195,6 +192,13 @@ func s:Highlight_Matching_Pair()
   endif
 endfunction
 
+func s:Remove_Previous_Match()
+  if exists('w:paren_hl_on') && w:paren_hl_on
+    silent! call matchdelete(3)
+    let w:paren_hl_on = 0
+  endif
+endfunc
+
 " Define commands that will disable and enable the plugin.
 command DoMatchParen call s:DoMatchParen()
 command NoMatchParen call s:NoMatchParen()
```

**Comment by brammool** [comment]
Thanks for the patch.  I think it's the best solution (that isn't a lot of work).  It's also symmetric, since the matches are updated on the WinEnter autocommand.  So let me include this.
