### ISSUE TITLE
Cannot set the type of the previous Visual selection

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#12445]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

It is not possible to set the type of the previous Visual selection (`curbuf->b_visual.vi_mode`), while its starting and ending positions can both be set using `setpos()`.

**Describe the solution you'd like**
It can be another argument to the `visualmode()` function that actually changes `curbuf->b_visual.vi_mode` instead of just changing `curbuf->b_visual_mode_eval` (which is only used by the `visualmode()` function itself).

**Describe alternatives you've considered**
None

**Comment by brammool** [comment]
> It is not possible to set the type of the previous Visual selection
> (`curbuf->b_visual.vi_mode`), while it starting and ending position
> can both be set using `setpos()`.

I wonder what this would be needed for.

> **Describe the solution you'd like**
> It can be another argument to the `visualmode()` function that
> actually changes `curbuf->b_visual.vi_mode` instead of just changing
> `curbuf->b_visual_mode_eval` (which is only used by the `visualmode()`
> function itself).

It can work using "gv", then setting the mode to the desired value, and
Esc to end Visual mode.  It's a bit more work, but if this is hardly
ever used that isn't much of a problem.

Using visualmode() to set the mode is a bit confusing.  The existing
argument (which is weird anyway) gets in the way of just setting the
mode.  I suppose you could use "visualmode(1, 'v')" if needed.

-- 
If your nose runs, and your feet smell, you might be upside down.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
for what its worth, that's exactly how I store the last visual selection for my NarrowRegion plugin: https://github.com/chrisbra/NrrwRgn/blob/e027db9d94f94947153cd7b5ac9abd04371ab2b0/autoload/nrrwrgn.vim#L1338-L1342

Simply set the mode and press `ESC`.
