### ISSUE TITLE
Ctrl-X in visual mode deletes text on Windows Console Host

### ISSUE THREAD

**Issue by 3N4N** [vim/vim#12451]
### Steps to reproduce

```
Write-Output "1`n2`n3" | vim --clean -
Ctrl-V
j
Ctrl-X
```
The numbers will be deleted.  If I map `:xnoremap <C-X> <C-X>`, the numbers decrement as expected.

### Expected behaviour

The numbers are decremented.

### Version of Vim

9.0.1472 (reproducible with 8.2.5171, too)

### Environment

OS: Windows 11 (ver: 10.0.22621.1702)
Terminal: Windows Console Host
$TERM: xterm-256colors, nil
Shell: PowerShell 7, Command Prompt, Git for Windows bash

**Comment by k-takata** [comment]
This is documented behavior. See `:h dos-standard-mappings`.

**Comment by 3N4N** [comment]
So it is.  (Weird choice, but not a bug, so) Closing.
