### ISSUE TITLE
Consider restoring runtime/rgb.txt

### ISSUE THREAD

**Issue by ctrlcctrlv** [vim/vim#12453]
or at least referencing https://github.com/ctrlcctrlv/rgb.txt

see https://github.com/ofavre/vimcat/issues/13

**Comment by brammool** [comment]
Ehm, why?

**Comment by ctrlcctrlv** [comment]
So vimcat will build again w/o my hacks.

**Comment by k-takata** [comment]
I don't know about vimcat, but what is rgb.txt used for?

**Comment by tonymec** [comment]
@k-takata : See `:help rgb.txt` which also says why this file is no longer used.

Best regards,
Tony.

**Comment by k-takata** [comment]
@tonymec 
I'd like to know the reason why vimcat requires rgb.txt.

**Comment by tonymec** [comment]
P.S. By reading `:h rgb.txt` and continuing at `:h v:colornames` I conclude from a paragraph at the end of the latter that the desired result can be achieved by a Vim script named one (or more) of
```
~/.vim/colors/lists/default.vim
$HOME/colors/lists/default.vim
$VIM/vimfiles/colors/lists/default.vim
$VIM/vimfiles/after/colors/lists/default.vim
$HOME/vimfiles/after/colors/lists/default.vim
~/.vim/after/colors/lists/default.vim
```
some of which depend on the OS gvim (or Console Vim with either `+termguicolors` or some plugin such as CSApprox or similar) is running on. See `:help 'runtimepath` to and including `:help after-directory` for an explanation of which one(s) of these directories to use in which circumstances.

**Comment by tonymec** [comment]
Oops: in my previous post, the second pathfilename ought to be `$HOME/vimfiles/colors/lists/default.vim` not `$HOME/colors/` etc.

Best regards,
Tony.

**Comment by tonymec** [comment]
@k-takata : I don't know what vimcat is, or is about. Maybe after reading the help pages I mentioned @ctrlcctrlv can tell us that (as I believe) rgb.txt is not needed after all, or why it is.

**Comment by ofavre** [comment]
Hi, I'm the author of vimcat.

I read vim's code as to why this file was deleted and end up using `v:colornames` instead of processing `runtime/rgb.txt` at package build time. So vimcat no longer needs this file either.

Thanks @ctrlcctrlv, but you can close this issue.

**Comment by k-takata** [comment]
Closing then.

**Comment by ctrlcctrlv** [comment]
Thanks for the patch @ofavre :innocent:
