### ISSUE TITLE
+command, -c command is executed after VimEnter

### ISSUE THREAD

**Issue by lbrayner** [vim/vim#12464]
### Steps to reproduce

1. `for n in {1..1001}; do { < /dev/urandom tr -dc A-Za-z0-9 | head -c30; echo; } ; done > /var/tmp/thousand_one_lines.txt`
2. `vim --clean -u /var/tmp/WinEnter.vim -c "vsplit" /var/tmp/thousand_one_lines.txt`

`/var/tmp/WinEnter.vim` is:

```vim
set nocompatible
set number
set relativenumber

function! s:Number()
    set number
    set relativenumber
    " setting nonumber if length of line count is greater than 3
    if len(line("$"))>3
        set nonumber
    endif
endfun

augroup Number
    autocmd!
    autocmd VimEnter * autocmd Number
                \ BufRead,BufEnter,BufWritePost * call s:Number()
    autocmd VimEnter * call s:Number()
    " Triggered at window creation on startup, disabled after
    autocmd WinEnter * call s:Number()
    autocmd VimEnter * autocmd! Number WinEnter
augroup END
if v:vim_did_enter
    doautocmd Number VimEnter
endif
```

### Expected behaviour

Both windows have 'number' set to false, i.e, the WinEnter autocmd was triggered.

### Version of Vim

8.2.2434

### Environment

Ubuntu 20.04
st
st-256color
zsh

**Comment by chrisbra** [comment]
I only see that `relativenumber` is set and not `number` with 9.0.1569. Can you please try with an uptodate vim?
