### ISSUE TITLE
cursor in wrong position when putting long register

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#12465]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        &laststatus = 2
        autocmd CursorMoved * eval [line('w0'), line('w$')]
        @a = 'x'->repeat(&columns * 2)
        ['']->repeat(&lines)->setline(1)
        feedkeys('G"ap')
    EOF
    )

The cursor is in the status line, and the `xxx...` line is not visible.

**Expected behavior**

The cursor is in the buffer, and the `xxx...` line is visible.

**Version of Vim**

9.0 Included patches: 1-1591

**Environment**

Operating system: Ubuntu 20.04.6 LTS
Terminal: XTerm(378)
Value of $TERM: xterm-256color
Shell: GNU bash, version 5.0.17

**Additional context**

The issue is triggered by the `CursorMoved` autocmd which evaluates `line('w0')` and `line('w$')`.

---

A similar issue was fixed in patch [8.2.4915](https://github.com/vim/vim/releases/tag/v8.2.4915)

**Comment by brammool** [comment]
> **Steps to reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(tee <<'EOF'
>         vim9script
>         &laststatus = 2
>         autocmd CursorMoved * eval [line('w0'), line('w$')]
>         @a = 'x'->repeat(&columns * 2)
>         ['']->repeat(&lines)->setline(1)
>         feedkeys('G"ap')
>     EOF
>     )
> 
> The cursor is in the status line, and the `xxx...` line is not visible.
> 
> **Expected behavior**
> 
> The cursor is in the buffer, and the `xxx...` line is visible.
> 
> **Version of Vim**
> 
> 9.0 Included patches: 1-1591
> 
> **Environment**
> 
> Operating system: Ubuntu 20.04.6 LTS
> Terminal: XTerm(378)
> Value of $TERM: xterm-256color
> Shell: GNU bash, version 5.0.17
> 
> **Additional context**
> 
> The issue is triggered by the `CursorMoved` autocmd which evaluates
> `line('w0')` and `line('w$')`.

Interesting.  After removing "line('w0')" it still happens.  It's the
"line('w$')" expression that triggers the problem.

I can also remove setting 'statusline', the cursor then shows in the
command line, which is just as wrong.

Changing the feedkeys() call by adding "$" fixes the problem.  Other
commands after the put that move the cursor also fix the problem.  Thus
it appears the put command is not setting the flags for recomputing the
scroll position correctly.

While debugging this I found a few things that were wrong, but the
essential fix is to mark w_botline as invalid when the cursor line is
changed.  It may no longer fit in the window and a scroll up is needed.
I'll make a patch for that.

-- 
From "know your smileys":
 :-E	Has major dental problems

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
