### ISSUE TITLE
screenpos() returns wrong result for wrapped line

### ISSUE THREAD

**Issue by tomtomjhj** [vim/vim#12476]
### Steps to reproduce

```
vim --clean
```
```
call setline(1, 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet')
exe "normal! z1\<CR>$"
echo screenpos(0, line('.'), col('.'))
```
The result is all zeros:
![image](https://github.com/vim/vim/assets/19489738/78947cc5-ff20-4f52-a1ca-9623787fd952)

### Expected behaviour

Should return something non-zero, because the position is visible.

Related: [8.2.3193](https://github.com/vim/vim/commit/189663bdac1156237c49925f77bd197c1bdea12c)

### Version of Vim

9.0.1558

### Environment

Ubuntu 22.04

**Comment by zeertzjq** [comment]
I've create a PR #12486 to fix this.
