### ISSUE TITLE
screenpos() wrongly counts invisible diff filler lines

### ISSUE THREAD

**Issue by rickhowe** [vim/vim#12484]
### Steps to reproduce

This is related to https://github.com/vim/vim/issues/11658#issue-1475306451, closed on Patch 9.0.1016.

If diff filler lines are invisible above screen, screenpos() still counts them as they are visible.

```
call setline(1, ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'])
vnew
call setline(1, ['a', 'b', 'c', 'g', 'h', 'i'])
windo diffthis
```
then
`echo screenpos(0, 4, 1)` correctly returns 7 as row.

but after
`exe 'normal 4z+'`
`echo screenpos(0, 4, 1)` wrongly returns 4 as row, which includes invisible diff filler lines.

### Expected behaviour

should return 1 as row.

### Version of Vim

9.0.1599

### Environment

Windows 10

**Comment by zeertzjq** [comment]
I think a `wincmd w` is missing from steps to reproduce.

**Comment by zeertzjq** [comment]
I've created a PR #12485 to fix this.
