### ISSUE TITLE
tree-sitter syntax highlight in vim like what it is in neovim.

### ISSUE THREAD

**Issue by sloppydevil** [vim/vim#12508]
the only reason I change temporarily to neovim is tree-sitter syntax highlight.

Can there be an incremental syntax highlight there, so that I can see updated highlight in time?

thx so much.

**Comment by chrisbra** [comment]
I think this is part of the larger proposal discussed at #9087

**Comment by brammool** [comment]
> the only reason I change temporarily to neovim is tree-sitter syntax
> highlight.

Can you be specific about this?  Is highlighting not supported for some
filetype?  Does it work better for some filetype?  If yes, then in what
way (faster, accuracy)?

> Can there be a incremental syntax highlight there, so that I can see
> updated highlight in time?

I suppose that's a question for Neovim.

-- 
hundred-and-one symptoms of being an internet addict:
138. You develop a liking for cold coffee.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by sloppydevil** [comment]
I'm editing typescript files, and there are currently about 10 files. one file if of code lines about 600. and my default color theme is dracula.

When I entered vim, sometimes head lines are not highlighted, e.g. the function names; and if i directly go to end of file pressing "G", the function names, keywords are for sure not highlighted.

I manually source $MYVIMRC, then the functions are highlighted; then scroll down, upcoming functions are highlighted too; but if I directly goto bottom of file, the functions are not highlighted.

I did similar thing for "yolo v5" repo, and went to "train.py" which also has about 600 lines' code, everything is good.

so it seems that this rendering lag exists in typescript?

**Comment by brammool** [comment]
> I'm editing typescript files, and there are currently about 10 files.
> one file if of code lines about 600. and my default color theme is
> dracula.
> 
> When I entered vim, sometimes head lines are not highlighted, e.g. the
> function names; and if i directly go to end of file pressing "G", the
> function names, keywords are for sure not highlighted.
> 
> I manually source $MYVIMRC, then the functions are highlighted; then
> scroll down, upcoming functions are highlighted too; but if I directly
> goto bottom of file, the functions are not highlighted.
> 
> I did similar thing for "yolo v5" repo, and went to "train.py" which
> also has about 600 lines' code, everything is good.
> 
> so it seems that this rendering lag exists in typescript?

Most likely.  If I understand you correctly, the typescript syntax in
Vim doesn't sync properly, while the treesitter implementation works
better.  I believe treesitter parses the file from the start, thus that
would explain it.

You could force Vim to sync from the start:

   :syntax sync fromstart

Give that a try.

-- 
hundred-and-one symptoms of being an internet addict:
145. You e-mail your boss, informing him you'll be late.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
closing as dup of #9087
