### ISSUE TITLE
:copen opens quickfix window below `lastwin` instead of `curwin` 

### ISSUE THREAD

**Issue by MunifTanjim** [vim/vim#12501]
### Steps to reproduce

1. Create a new split on the right
2. Jump to the left window
3. `:copen`
4. Quickfix window is opened below the right split

### Expected behaviour

`:copen` should open the window below current window as it says here: https://github.com/vim/vim/blob/cdb7b4c50826df254d2e5ba8abd211e49b7a9784/src/quickfix.c#L4274

### Version of Vim

VIM - Vi IMproved 8.1

### Environment

N/A

**Comment by MunifTanjim** [comment]
Might be that I'm misunderstanding the expected behavior.

If it's not supposed to be opened under `curwin`, would it be possible to change the default behavior to open with `WSP_BOT` (instead of `WSP_BELOW`)?

**Comment by brammool** [comment]
The help states:
```
Normally the quickfix window is at the bottom of the screen.  If there are
vertical splits, it's at the bottom of the rightmost column of windows.
```
Is that not what is happening?  A comment in the code can easily be changed,  I
rather not change the actual behavior unless there is a good reason.

**Comment by tonymec** [comment]
Yeah, that's what the OP is describing.

IOW: "T'ain't a bug, it's a feature."

**Comment by MunifTanjim** [comment]
> Is that not what is happening?

Ah yes. The behavior is following the help text.

Makes sense.

> I rather not change the actual behavior unless there is a good reason.

Opening qf window at the bottom right corner, by default, makes it seem like the quickfix list is somehow related to the window at bottom right corner. So opening it at the bottom of the editor seems more intuitive to me.

But it's your call... if this change is not desired, the issue can be closed.

Thanks.

**Comment by chrisbra** [comment]
You may want to use the locationlist window instead,  I think it should be opened below the currently active window instead.

**Comment by MunifTanjim** [comment]
Yeah, but locationlist is bound to a specific window.

If we want list that contains locations from various files across the codebase, quickfix list is the appropriate feature, right?

And since it's not bound to any specific window, (to me) it feels like bottom-of-the-editor would be better suited place to open it by default. Many plugins I use explicity executes `:botright copen` because of that. Would've been nice if `:copen` did that by default.

But again, it's the maintainers' call. If you think this shouldn't be changed, the issue can be closed.

**Comment by chrisbra** [comment]
> If we want list that contains locations from various files across the codebase, quickfix list is the appropriate feature, right?

What has that to do with the other? I tend to use the locationlist, because it is more flexible and you can have more than one. But it doesn't depend on whether I want to visit files across the codebase.

But as has been said, I think changing the existing behaviour may surprise a lot of users, let's leave it as it. Also it should be possible to move the window around to a certain extend afterwards. So let's close it then.

**Comment by vim-ml** [comment]
On 2023-06-07, Munif Tanjim wrote:
> Might be that I'm misunderstanding the expected behavior.
> 
> If it's not supposed to be opened under curwin, would it be possible to change
> the default behavior to open with WSP_BOT (instead of WSP_BELOW)?

I didn't like the default behavior, either, so I added this to my
~/.vim/after/ftplugin/qf.vim.

    " The following is taken from the QFEnter.vim plugin,
    " http://vim.sourceforge.net/scripts/script.php?script_id=4778,
    " by yssl.  I extracted and simplified the part I needed:  When
    " jumping to items from the quickfix window, open them in the
    " previous window instead of the window above the quickfix
    " window.

    nnoremap <buffer> <silent> <CR> :call QfEnter()<CR>
    let b:undo_ftplugin .= "| nunmap <buffer> <CR>"

    function! QfEnter()
        let l:lnum = line('.')
        wincmd p
        try
            exe 'cc' l:lnum
            normal! zv
        catch /E37/
            if &errorbells
                normal \<Esc>               " Generate a bell
            endif
            echohl ErrorMsg
            echo matchstr(v:exception, ':\zs.*')
            echohl None
        endtry
    endfunction

HTH,
Gary

**Comment by vim-ml** [comment]
On Sun, 25 Jun 2023 12:16:58 -0700
Gary Johnson ***@***.***> wrote:
> On 2023-06-07, Munif Tanjim wrote:
> > Might be that I'm misunderstanding the expected behavior.
> > 
> > If it's not supposed to be opened under curwin, would it be possible to change
> > the default behavior to open with WSP_BOT (instead of WSP_BELOW)?  
> 
> I didn't like the default behavior, either, so I added this to my
> ~/.vim/after/ftplugin/qf.vim.
> 
>     " The following is taken from the QFEnter.vim plugin,
>     " http://vim.sourceforge.net/scripts/script.php?script_id=4778,
>     " by yssl.  I extracted and simplified the part I needed:  When
>     " jumping to items from the quickfix window, open them in the
>     " previous window instead of the window above the quickfix
>     " window.
> 
>     nnoremap <buffer> <silent> <CR> :call QfEnter()<CR>
>     let b:undo_ftplugin .= "| nunmap <buffer> <CR>"
> 
>     function! QfEnter()
>         let l:lnum = line('.')
>         wincmd p
>         try
>             exe 'cc' l:lnum
>             normal! zv
>         catch /E37/
>             if &errorbells
>                 normal \<Esc>               " Generate a bell
>             endif
>             echohl ErrorMsg
>             echo matchstr(v:exception, ':\zs.*')
>             echohl None
>         endtry
>     endfunction
> 
> HTH,
> Gary
> 

Thank you for this.  It sometime annoys me when pressing Enter on QF
window opens the file in a different window than the one I previously
accessed.

But out of curiosity, this isn't what OP was after, is it?  Munif was
looking to change the default QF behavior by opening the QF window under
the current window.  Your function, Gary, opens the file in QF entry in
the previous window.  They are different asks, AFAI can tell.

-- 
Enan

**Comment by MunifTanjim** [comment]
> Munif was looking to change the default QF behavior by opening the QF window under
the current window.

Just a small correction... not _under the current window_, but _under the whole editor_.

So, if there are existing windows A, B and C, I wanted `:copen` to do this by default:

```
---------
|   | B |
| A |---|
|   | C | 
---------
|  QF   |
---------
```

**Comment by MunifTanjim** [comment]
> Munif was looking to change the default QF behavior by opening the QF window under
the current window.

Yeah, I wanted it to open under current window initially (when creating the issue).

But later thought that _under the whole editor_ makes more sense... so, if there are existing windows A, B and C, it makes more sense for `:copen` to do this by default:

```
---------
|   | B |
| A |---|
|   | C | 
---------
|  QF   |
---------
```
