### ISSUE TITLE
Internal error: class not found on interface

### ISSUE THREAD

**Issue by Raimondi** [vim/vim#12500]
### Steps to reproduce

Source the following script:

````vim
vim9script

interface H
endinterface

class A
  def Method(): void
  enddef
endclass

class B extends A
endclass

(() => A.new().Method())()
````

### Expected behaviour

Not an error, but we get the following error:

````
Error detected while processing command line..script {...}/vim/test.vim[14]..function <lambda>1:
line    1:
E340: Internal error; if you can reproduce please report a bug
class A not found on interface A
Press ENTER or type command to continue
````

Notice that the interface is named H, but the error mentions interface A, the same name as class A. Also, class B must be defined for the issue to appear.

### Version of Vim

9.0.1614

### Environment

OS: MacOS 13.1
Terminal: iTerm 3.4.19
$TERM: xterm-256color
Shell: Fish 3.6.1

**Comment by yegappan** [comment]
This issue is fixed in the recent versions of Vim.  Can you try to reproduce this with the latest version of Vim?

**Comment by Raimondi** [comment]
I can't reproduce it anymore. I'll close the the issue now.

Cheers!
