### ISSUE TITLE
[vim9] `super` became a keyword only word

### ISSUE THREAD

**Issue by Shane-XB-Qian** [vim/vim#12515]
### Steps to reproduce

E1356: "super" must be followed by a dot
E1105: Cannot convert class to string

```vim
vim9script

def Foo(super: bool)
	echom 'foo: ' .. super
enddef

defcompile
```

### Expected behaviour

expected no err

### Version of Vim

v9.0.1623

### Environment

linux

**Comment by brammool** [comment]
"super" is a reserved word now.  It's commonly used in languages using inheritance.
Not using it would cause greater problems.  The error messages could be clearer though.

**Comment by Shane-XB-Qian** [comment]
> "super" is a reserved word now.  It's commonly used in languages using inheritance.
> Not using it would cause greater problems.  The error messages could be clearer though.

but it would not raise err if using 'this/silent/class'
// though we can try to avoid using keyword in script..

-- 
shane.xb.qian

**Comment by Shane-XB-Qian** [comment]
now (your last patch) i saw 'this' and 'super' became a real keyword (e1034) now. :smile: 
// ok, if this is the best choice for now.
