### ISSUE TITLE
[vim9script] Error when function argument is created at invocation time

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#12525]
### Steps to reproduce

Source this script:

```vim
vim9script

class Widget
endclass

def F(widget: Widget, lnum: number)
enddef

def G(lnum: number, widget: Widget)
enddef

def H(w1: Widget, w2: Widget)
enddef

def Draw()
  var foo = Widget.new()
  F(foo, 1)                      # OK
  G(1, foo)                      # OK
  H(foo, foo)                    # OK
  F(Widget.new(), 1)             # OK
  G(1, Widget.new())             # ERROR
  H(Widget.new(), Widget.new())  # ERROR
enddef

Draw()
```

The last two function invocations inside `Draw()` fail with:

    E1013: Argument 1: type mismatch, expected number but got class<Widget>

and

    E1013: Argument 1: type mismatch, expected object<Widget> but got class<Widget>

respectively.

### Expected behaviour

It should be possible to create objects inside function arguments under all circumstances.

### Version of Vim

9.0.1626

### Environment

macOS 13.4
Apple Terminal
xterm-256color
ZSH 5.9

**Comment by mg979** [comment]
Possibly related:

this works
```vim
vim9script

class Test
	this._name = ""

	def new(this._name)
	enddef

	def GetName(): string
		return this._name
	enddef
endclass

var t = Test.new("testname")
setreg('"', t.GetName())
```

this doesn't (same `E1013` error)
```vim
vim9script

class Test
	this._name = ""

	def new(this._name)
	enddef

	def GetName(): string
		return this._name
	enddef
endclass

var t = Test.new("testname")

def Setreg()
	setreg('"', t.GetName())
enddef

Setreg()
```

This works again:
```vim
vim9script

class Test
	this._name = ""

	def new(this._name)
	enddef

	def GetName(): string
		return this._name
	enddef
endclass

var t = Test.new("testname")

def Setreg()
	var n = t.GetName()
	setreg('"', n)
enddef

Setreg()
```

So it's not possible to invoke a class method in functions, directly as arguments in function calls, but it works if you assign it to a variable and then pass the variable.

**Comment by errael** [comment]
> So it's not possible to invoke a class method in functions, directly as arguments in function calls

Reported in #12081 

This is probably a duplicate

**Comment by chrisbra** [comment]
closing as duplicate then
