### ISSUE TITLE
vim 9.0.1503 file dialogs bug

### ISSUE THREAD

**Issue by cederom** [vim/vim#12527]
### Steps to reproduce

1. Open vim 9.0.1503 in terminal (this is the current package on FreeBSD).
2. Create subwindows with `Ctrl+W S`, `Ctrl+W V`. Go to new subwindows with `Ctrl+W W`.
3. Open file selection dialog with `:E`.
4. See that file browsing dialog shows up not only in currently selected subwindow but also other subwindows overriding their contents.
5. Note that opening file in the current subwindow does not close dialog in other subwindows.

### Expected behaviour

As before file browser dialog should only show in currently selected subwindow and not in other subwindows overriding their contents.

### Version of Vim

9.0.1503

### Environment

OS: `13.2-RELEASE FreeBSD`.
TERMINAL: `Terminology-1.13.0_1`.
$TERM: `xterm`.
SHELL: `zsh`.

**Comment by trdenton** [comment]
I am unable to reproduce - I have tried reproducing this on 13.2-RELEASE by using the version in ports.  I have tried in a terminal emulator as well as the console, and terminology.  I have also tried with tag v9.0.1503 from git directly (i.e. not in ports)

Not sure what difference our system might have, what does ldd /usr/local/bin/vim look like for you?  this is what I get

[23:50:34] trdenton:vim $ ldd ./work-console/vim-9.0.1503/src/vim
./work-console/vim-9.0.1503/src/vim:
	libm.so.5 => /lib/libm.so.5 (0x1a79bc539000)
	libncursesw.so.9 => /lib/libncursesw.so.9 (0x1a79bc583000)
	librt.so.1 => /usr/lib/librt.so.1 (0x1a79bd3c6000)
	libintl.so.8 => /usr/local/lib/libintl.so.8 (0x1a79be69a000)
	libpython3.9.so.1.0 => /usr/local/lib/libpython3.9.so.1.0 (0x1a79bfe66000)
	libdl.so.1 => /usr/lib/libdl.so.1 (0x1a79be083000)
	libthr.so.3 => /lib/libthr.so.3 (0x1a79bedf4000)
	libc.so.7 => /lib/libc.so.7 (0x1a79c09d9000)
	libcrypt.so.5 => /lib/libcrypt.so.5 (0x1a79bf61f000)
	libutil.so.9 => /lib/libutil.so.9 (0x1a79c0e8e000)
	[vdso] (0x7ffffffff5d0)

**Comment by chrisbra** [comment]
sounds like https://github.com/vim/vim/issues/12304 please update your runtime files

**Comment by cederom** [comment]
Thanks @chrisbra this was it! Thank you for the fix!! :-)
