### ISSUE TITLE
`make clean` is broken in 9.0.1627

### ISSUE THREAD

**Issue by chdiza** [vim/vim#12526]
### Steps to reproduce

Do the ./configure, make, make install, make clean routine.

### Expected behaviour

I see this at the end:
```
rm -f LINGUAS vim.desktop gvim.desktop tmp_*desktop
rm -f testdir/*.fail testdir/*.out
/bin/sh: line 0: cd: runtime/syntax: No such file or directory
make: *** [clean] Error 1
```
That's not supposed to happen.  The patch that did this is 9.0.1627 itself, which bisecting proved.

### Version of Vim

9.0.1627

### Environment

macOS Monterey
Terminal: iTerm2
shell: bash

**Comment by wbpayne22902** [comment]
It looks like there is a pull request #12536 that will fix this problem when approved, also you can avoid the issue by doing a `cd src` before running `make clean`
