### ISSUE TITLE
screenpos() wrong with smoothscroll

### ISSUE THREAD

**Issue by tomtomjhj** [vim/vim#12547]
### Steps to reproduce

Assuming width 80 terminal,
```
vim --clean -S <(tee << 'EOF'
    set smoothscroll
    call setline(1, 'Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.')
    call setline(2, '')
    exe "normal! G\<C-e>"
    echo screenpos(0, line('.'), col('.'))
EOF
)
```

Result
```
{'col': 1, 'row': 3, 'endcol': 1, 'curscol': 1}
```
![image](https://github.com/vim/vim/assets/19489738/6a8594b7-5be7-4e0d-bfe7-a03b8e5ba9aa)

### Expected behaviour

'row' should be 2

### Version of Vim

9.0.1636

### Environment

ubuntu 22.04

**Comment by zeertzjq** [comment]
Fixed by patch 9.0.1729
