### ISSUE TITLE
bug in persistent undo -- `:earlier 100d` undoes one change instead of all

### ISSUE THREAD

**Issue by pavoljuhas** [vim/vim#1254]
It seems that with some older changes in a persistent undo file the `:earlier` command with a time offset stops at the Vim startup time.  Here is an example for a new file `t.txt` which does not have any undo file yet.  Vim needs to be run twice - first to generate the undo file and then to test the `:earlier` command.

```VimL
$ vim -u NONE -i NONE -N --cmd 'set undofile' t.txt
ione<Esc>otwo<Esc>othree<Esc>
" The buffer contains 3 lines "one", "two", "three".
" There are 3 changes in the undolist.
:undolist
number changes  when               saved
     3       3  4 seconds ago
:x
```

Here the current directory has a new file `t.txt` and its persistent undo in `.t.txt.un~`. 

```VimL
$ vim -u NONE -i NONE -N --cmd 'set undofile' t.txt
:earlier 100d
" this should undo all 3 changes back to an empty buffer.  Instead
" only the last change, i.e., one before the Vim startup time, is undone.
:%#
  1 one
  2 two
:echo undotree()['seq_cur']
2
```

I see this behavior in Vim 8.0.85 and it has probably been like that for a while.
The `:earlier` command works OK with a plain *changes* or *saves* arguments.

**Comment by brammool** [comment]
Pavol Juhas wrote:

> It seems that with some older changes in a persistent undo file the
> `:earlier` command with a time offset stops at the Vim startup time.
> Here is an example for a new file `t.txt` which does not have any undo
> file yet.  Vim needs to be run twice - first to generate the undo file
> and then to test the `:earlier` command.
> 
> ``` VimL
> $ vim -u NONE -i NONE -N --cmd 'set undofile' t.txt
> ione<Esc>otwo<Esc>othree<Esc>
> " The buffer contains 3 lines "one", "two", "three".
> " There are 3 changes in the undolist.
> :undolist
> number changes  when               saved
>      3       3  4 seconds ago
> :x
> ```
> 
> Here the current directory has a new file `t.txt` and its persistent undo in `.t.txt.un~`. 
> 
> ``` VimL
> $ vim -u NONE -i NONE -N --cmd 'set undofile' t.txt
> :earlier 100d
> " this should undo all 3 changes back to an empty buffer.  Instead
> " only the last change, i.e., one before the Vim startup time, is undone.
> :%#
>   1 one
>   2 two
> :echo undotree()['seq_cur']
> 2
> ```
> 
> I see this behavior in Vim 8.0.85 and it has probably been like that for a while.
> The `:earlier` command works OK with a plain _changes_ or _saves_ arguments.

I can reproduce it.  Strange, the undo info is there, using :earlier
repetively does go back in time. Thus it's the mechanism to find the
change matching the time that appears to be wrong.

## 

How To Keep A Healthy Level Of Insanity:
13. Go to a poetry recital and ask why the poems don't rhyme.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
I am quite sure it happens here in undo.c

```
2390             if (dosec)
2391                 val = (long)(uhp->uh_time - starttime);
```

val will get a negative value, because starttime is less than the time of the undo header. Then this condition here will only get hit once:

```
2403              if ((step < 0 ? uhp->uh_seq <= curbuf->b_u_seq_cur
2404                               : uhp->uh_seq > curbuf->b_u_seq_cur)
2405                         && ((dosec && val == closest)
2406                             ? (step < 0
2407                                 ? uhp->uh_seq < closest_seq
2408                                 : uhp->uh_seq > closest_seq)
2409                             : closest == closest_start
2410                                 || (val > target
2411                                     ? (closest > target
2412                                         ? val - target <= closest - target
2413                                         : val - target <= target - closest)
2414                                     : (closest > target
2415                                         ? target - val <= closest - target
2416                                         : target - val <= target - closest))))
2417                 {
2418                     closest = val;
2419                     closest_seq = uhp->uh_seq;
2420                 }
```

This will only hit the first time, because only at the beginning closest == closest_start, but after the next iteration, it will never hit again.

I think this patch will fix it, but I am not sure:

``` patch
diff --git a/src/undo.c b/src/undo.c
index 57c3c20..07c5d3c 100644
--- a/src/undo.c
+++ b/src/undo.c
@@ -2406,7 +2406,7 @@ undo_time(
                            ? (step < 0
                                ? uhp->uh_seq < closest_seq
                                : uhp->uh_seq > closest_seq)
-                           : closest == closest_start
+                           : closest == closest_start || closest < 0
                                || (val > target
                                    ? (closest > target
                                        ? val - target <= closest - target
```

That condition is really hard to understand, I stared on it for about an hour and even now I am not quite sure I completly understand it.

**Comment by brammool** [comment]
Christian Brabandt wrote:

> I am quite sure it happens here in undo.c
> 
> ```
> 2390             if (dosec)
> 2391                 val = (long)(uhp->uh_time - starttime);
> ```
> 
> val will get a negative value, because starttime is less than the time of the undo header. Then this condition here will only get hit once:
> 
> ```
> 2403              if ((step < 0 ? uhp->uh_seq <= curbuf->b_u_seq_cur
> 2404                               : uhp->uh_seq > curbuf->b_u_seq_cur)
> 2405                         && ((dosec && val == closest)
> 2406                             ? (step < 0
> 2407                                 ? uhp->uh_seq < closest_seq
> 2408                                 : uhp->uh_seq > closest_seq)
> 2409                             : closest == closest_start
> 2410                                 || (val > target
> 2411                                     ? (closest > target
> 2412                                         ? val - target <= closest - target
> 2413                                         : val - target <= target - closest)
> 2414                                     : (closest > target
> 2415                                         ? target - val <= closest - target
> 2416                                         : target - val <= target - closest))))
> 2417                 {
> 2418                     closest = val;
> 2419                     closest_seq = uhp->uh_seq;
> 2420                 }
> ```
> 
> This will only hit the first time, because only at the beginning closest == closest_start, but after the next iteration, it will never hit again.
> 
> I think this patch will fix it, but I am not sure:
> 
> ``` patch
> diff --git a/src/undo.c b/src/undo.c
> index 57c3c20..07c5d3c 100644
> --- a/src/undo.c
> +++ b/src/undo.c
> @@ -2406,7 +2406,7 @@ undo_time(
>                             ? (step < 0
>                                 ? uhp->uh_seq < closest_seq
>                                 : uhp->uh_seq > closest_seq)
> -                           : closest == closest_start
> +                           : closest == closest_start || closest < 0
>                                 || (val > target
>                                     ? (closest > target
>                                         ? val - target <= closest - target
> ```
> 
> That condition is really hard to understand, I stared on it for about
> an hour and even now I am not quite sure I completly understand it.

I tried to write a test for this, but it passes without the fix:

func Test_undofile_earlier()
  " Issue #1254
  new Xfile
  call feedkeys("ione<Esc>", 'xt')
  set ul=100
  call feedkeys("otwo<Esc>", 'xt')
  set ul=100
  call feedkeys("othree<Esc>", 'xt')
  set ul=100
  w
  wundo Xundofile
  bwipe!
  new Xfile
  rundo Xundofile
  earlier 1m
  call assert_equal('', getline(1))
  bwipe!
  call delete('Xfile')
  call delete('Xundofile')
endfunc

And indeed, if I try the reproduce steps without exiting Vim then it
works as expected.  So it seems that something gets reset when
restarting Vim, but not when reading the undo file.

## 

`The Guide says there is an art to flying,' said Ford,`or at least a
knack. The knack lies in learning how to throw yourself at the ground
and miss.' He smiled weakly.
        -- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
Yes that is exepected. You need to restart Vim in between, because only then will starttime be smaller than the timestamp in the undo header branch

**Comment by chrisbra** [comment]
perhaps it works creating the undofile in one test and reading it in another testfile works. Since Vim restarts between test invocations, that should work (at least if some timespan pass betwenn the  two invocations.)

**Comment by brammool** [comment]
Christian Brabandt wrote:

> Yes that is exepected. You need to restart Vim in between, because
> only then will starttime be smaller than the timestamp in the undo
> header branch

Ah, the global starttime.  I suppose we need a way to set that from a
test to properly test undo.  Like we have test_settime() we can have
test_setstarttime().

> perhaps it works creating the undofile in one test and reading it in
> another testfile works. Since Vim restarts between test invocations,
> that should work (at least if some timespan pass betwenn the  two
> invocations.)

Not a nice solution...

## 

Apparently, 1 in 5 people in the world are Chinese.  And there are 5
people in my family, so it must be one of them.  It's either my mum
or my dad.  Or my older brother Colin.  Or my younger brother
Ho-Cha-Chu.  But I think it's Colin.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by pavoljuhas** [comment]
> func Test_undofile_earlier()
>   " Issue #1254
>   new Xfile
>   call feedkeys("ione<Esc>", 'xt')
>   set ul=100
>   call feedkeys("otwo<Esc>", 'xt')
>   set ul=100

I tried something similar, but the bug would not show even in a restarted Vim.  I think it is because undo nodes generated in a script have the same timestamp.  The bug shows after inserting `sleep 1` in front of each `feedkeys` call.

**Comment by brammool** [comment]
Pavol Juhas wrote:

> > func Test_undofile_earlier()
> >   " Issue #1254
> >   new Xfile
> >   call feedkeys("ione<Esc>", 'xt')
> >   set ul=100
> >   call feedkeys("otwo<Esc>", 'xt')
> >   set ul=100
> 
> I tried something similar, but the bug would not show even in a restarted Vim.  I think it is because undo nodes generated in a script have the same timestamp.  The bug shows after inserting `sleep 1` in front of each `feedkeys` call.

A sleep slows down the test.  test_settime() can be used.

## 

'Well, here's something to occupy you and keep your mind off things.'
'It won't work, I have an exceptionally large mind.'
        -- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by pavoljuhas** [comment]
Here is my take on the test function - b07dd20a39cc9fd3d0167c2b817d9d3830ac7f28, [patch](https://github.com/vim/vim/commit/b07dd20a39cc9fd3d0167c2b817d9d3830ac7f28.patch).

It uses `test_settime` to pretend changes in undofile are few seconds old, then it runs the `earlier` command in a second vim instance, and finally reopens the Xundo file to check its content.

**Comment by pavoljuhas** [comment]
The undofile-earlier test can be also done without running Vim twice
https://github.com/vim/vim/compare/master...pavoljuhas:test-undofile-earlier

**Comment by vim-ml** [comment]
2016-11-17 16:49 GMT+03:00 Bram Moolenaar <vim-dev-github@256bit.org>:
>
> Christian Brabandt wrote:
>
>> I am quite sure it happens here in undo.c
>>
>> 2390 if (dosec)
>> 2391 val = (long)(uhp->uh_time - starttime);
>>
>> val will get a negative value, because starttime is less than the time of
>> the undo header. Then this condition here will only get hit once:
>>
>>
>> 2403 if ((step < 0 ? uhp->uh_seq <= curbuf->b_u_seq_cur
>> 2404 : uhp->uh_seq > curbuf->b_u_seq_cur)
>> 2405 && ((dosec && val == closest)
>> 2406 ? (step < 0
>> 2407 ? uhp->uh_seq < closest_seq
>> 2408 : uhp->uh_seq > closest_seq)
>> 2409 : closest == closest_start
>> 2410 || (val > target
>> 2411 ? (closest > target
>> 2412 ? val - target <= closest - target
>> 2413 : val - target <= target - closest)
>> 2414 : (closest > target
>> 2415 ? target - val <= closest - target
>> 2416 : target - val <= target - closest))))
>> 2417 {
>> 2418 closest = val;
>> 2419 closest_seq = uhp->uh_seq;
>> 2420 }
>>
>> This will only hit the first time, because only at the beginning closest
>> == closest_start, but after the next iteration, it will never hit again.
>>
>> I think this patch will fix it, but I am not sure:
>>
>> ```patch
>> diff --git a/src/undo.c b/src/undo.c
>> index 57c3c20..07c5d3c 100644
>> --- a/src/undo.c
>> +++ b/src/undo.c
>> @@ -2406,7 +2406,7 @@ undo_time(
>> ? (step < 0
>> ? uhp->uh_seq < closest_seq
>> : uhp->uh_seq > closest_seq)
>> - : closest == closest_start
>> + : closest == closest_start || closest < 0
>> || (val > target
>> ? (closest > target
>> ? val - target <= closest - target
>> ```
>>
>> That condition is really hard to understand, I stared on it for about
>> an hour and even now I am not quite sure I completly understand it.
>
> I tried to write a test for this, but it passes without the fix:
>
> func Test_undofile_earlier()
> " Issue #1254
> new Xfile
> call feedkeys("ione\<Esc>", 'xt')
> set ul=100
> call feedkeys("otwo\<Esc>", 'xt')
> set ul=100
> call feedkeys("othree\<Esc>", 'xt')
> set ul=100
> w
> wundo Xundofile
> bwipe!
> new Xfile
> rundo Xundofile
> earlier 1m
> call assert_equal('', getline(1))
> bwipe!
> call delete('Xfile')
> call delete('Xundofile')
> endfunc
>
> And indeed, if I try the reproduce steps without exiting Vim then it
> works as expected. So it seems that something gets reset when
> restarting Vim, but not when reading the undo file.

This is one of the reasons Neovim tests prefer to restart Neovim
another time even during a single test rather then try to smash more
then one test (note: not even a test module) in a single Neovim
instance: you never know which state that is significant to the test
was left from the previous test, additionally state may be just
impossible to restore. Even if this makes tests an order of magnitude
faster this is not worth the chance that dirty state will make the
tests incorrect (also Neovim test suite does not require “sleep to
avoid the xterm title being messed up”).
