### ISSUE TITLE
vim9 patches list missing in help

### ISSUE THREAD

**Issue by balki** [vim/vim#12545]
### Steps to reproduce

```
:version
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jun 14 2023 00:27:53)
Included patches: 1-1628
Compiled by Arch Linux
```
Above vim should have all vim9 patches from 1 to 1628. However in help, only 8.2 patches are listed.
vim command run: `:help patches-9`

```
PATCHES                                         patches-9 bug-fixes-9        
                                                patches-after-8.2            
                                                                             
The list of patches that got included since 8.2.0.  This includes all the new
features, but does not include runtime file changes (syntax, indent, help,   
etc.)                                                                        
                                                                             
Patch 8.2.0001                                                               
Problem:    #endif comments do not reflect corresponding #ifdef.             
Solution:   Update the comments. (Rene Nyffenegger, closes #5351)            
Files:      src/ui.c                                                         
                                                                             
Patch 8.2.0002                                                               
Problem:    "dj" only deletes first line of closed fold.                     
Solution:   Adjust last line of operator for linewise motion. (closes #5354) 
Files:      src/ops.c, src/testdir/test_fold.vim                             

...

Patch 8.2.5172                                                      
Problem:    "make menu" still uses legacy script.                   
Solution:   make menu generation script use Vim9 script, fix errors.
Files:      runtime/makemenu.vim                                    
                                                                    
                                                                    
 vim:tw=78:ts=8:noet:ft=help:norl:
```
Same in online help too. https://vimhelp.org/version9.txt.html#patches-9

### Expected behaviour

There should be a way to see vim9 patches in help.

### Version of Vim

vim 9.0

### Environment

Archlinux

**Comment by chrisbra** [comment]
that list is usually only created shortly before the next release.

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> ```
> :version
> VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jun 14 2023 00:27:53)
> Included patches: 1-1628
> Compiled by Arch Linux
> ```
> Above vim should have all vim9 patches from 1 to 1628. However in help, only 8.2 patches are listed.

The list of patches is only updated once in a while.  I'll make an
update once I find some time.


-- 
panic("Foooooooood fight!");
	-- In the kernel source aha1542.c, after detecting a bad segment list

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
