### ISSUE TITLE
Error for missing libwinpthread-1.dll after building on Windows using Cygwin/Mingw cross compiler

### ISSUE THREAD

**Issue by jmmerz** [vim/vim#1255]
Ran into this problem using the newest MinGW toolchain on Cygwin. Versions are:

- mingw64-x86_64-gcc: 5.4.0-3
- mingw64 headers/runtime/winpthreads 5.0.0-1

Building using code:

``` bash
make -f Make_cyg_ming.mak CC=/bin/x86_64-w64-mingw32-gcc \
                     CROSS=yes \
                     CROSS_COMPILE=/bin/x86_64-w64-mingw32- \
                     STATIC_STDCPLUS=yes \
                     GUI=yes \
                     OLE=yes \
                     ARCH=native \
                     USEDLL=no \
                     FEATURES=BIG \
                     CSCOPE=no \
                     NETBEANS=yes \
                     WINVER=0x0500 \
                     XPM=xpm/x64

```

It appears something has added a dynamic dependency on libwinpthread-1.dll. When I run the GVim executable, I get an error message:

> The program can't start because libwinpthread-1.dll is missing from your computer. Try reinstalling the program to fix this problem.

I have a potential fix to add a variable to allow static linking of winpthread, though I'm not 100% sure it's the right thing to do. I'll create a pull request with the fix.

**Comment by k-takata** [comment]
It seems that this happens when it is built for x86_64.
X86 build doesn't have a dependency on winpthread.

**Comment by basilisk0315** [comment]
I have just noticed this issue on 9.0.0752 (64-bit build on Windows 8.1 x64 using mingw64, gcc 12.2.0). Here is my make command for gvim (note I have STATIC_STDCPLUS=yes):
`
make --directory=/D/Users/John/Documents/software/Utility/Vim/git/vim/src FEATURES=NORMAL OPTIMIZE=MAXSPEED DIRECTX=no ICONV= GETTEXT= IME=no DYNAMIC_IME=no POSTSCRIPT=no OLE=no WINVER=0x0603 CSCOPE=no NETBEANS=no CHANNEL=no TERMINAL=no SOUND=no ARCH=native XPM=no STATIC_STDCPLUS=yes GUI=yes CFLAGS=-I. -Iproto -DWIN32 -DWINVER=0x0603 -D_WIN32_WINNT=0x0603 -DHAVE_PATHDEF -DFEAT_NORMAL -DHAVE_STDINT_H -D__USE_MINGW_ANSI_STDIO -pipe -march=native -Wall -O3 -fomit-frame-pointer -freg-struct-return -fpie -fPIE -DFEAT_GUI_MSWIN -DFEAT_CLIPBOARD LFLAGS=-Wl,-nxcompat,-dynamicbase -municode -s -mwindows --environment-overrides --jobs=9 --keep-going --output-sync --no-print-directory --makefile=Make_ming.mak gvim.exe
gcc -I. -Iproto -DWIN32 -DWINVER=0x0603 -D_WIN32_WINNT=0x0603 -DHAVE_PATHDEF -DFEAT_NORMAL -DHAVE_STDINT_H -D__USE_MINGW_ANSI_STDIO -pipe -march=native -Wall -O3 -fomit-frame-pointer -freg-struct-return -fpie -fPIE -DFEAT_GUI_MSWIN -DFEAT_CLIPBOARD -Wl,-nxcompat,-dynamicbase -municode -s -mwindows -o gvim.exe gobjnative/alloc.o gobjnative/arabic.o gobjnative/arglist.o gobjnative/autocmd.o gobjnative/beval.o gobjnative/blob.o gobjnative/blowfish.o gobjnative/buffer.o gobjnative/bufwrite.o gobjnative/change.o gobjnative/charset.o gobjnative/cindent.o gobjnative/clientserver.o gobjnative/clipboard.o gobjnative/cmdexpand.o gobjnative/cmdhist.o gobjnative/crypt.o gobjnative/crypt_zip.o gobjnative/debugger.o gobjnative/dict.o gobjnative/diff.o gobjnative/digraph.o gobjnative/drawline.o gobjnative/drawscreen.o gobjnative/edit.o gobjnative/eval.o gobjnative/evalbuffer.o gobjnative/evalfunc.o gobjnative/evalvars.o gobjnative/evalwindow.o gobjnative/ex_cmds.o gobjnative/ex_cmds2.o gobjnative/ex_docmd.o gobjnative/ex_eval.o gobjnative/ex_getln.o gobjnative/fileio.o gobjnative/filepath.o gobjnative/findfile.o gobjnative/float.o gobjnative/fold.o gobjnative/getchar.o gobjnative/gui_xim.o gobjnative/hardcopy.o gobjnative/hashtab.o gobjnative/help.o gobjnative/highlight.o gobjnative/if_cscope.o gobjnative/indent.o gobjnative/insexpand.o gobjnative/json.o gobjnative/list.o gobjnative/locale.o gobjnative/main.o gobjnative/map.o gobjnative/mark.o gobjnative/match.o gobjnative/memfile.o gobjnative/memline.o gobjnative/menu.o gobjnative/message.o gobjnative/misc1.o gobjnative/misc2.o gobjnative/mouse.o gobjnative/move.o gobjnative/mbyte.o gobjnative/normal.o gobjnative/ops.o gobjnative/option.o gobjnative/optionstr.o gobjnative/os_mswin.o gobjnative/os_win32.o gobjnative/pathdef.o gobjnative/popupmenu.o gobjnative/popupwin.o gobjnative/profiler.o gobjnative/quickfix.o gobjnative/regexp.o gobjnative/register.o gobjnative/scriptfile.o gobjnative/screen.o gobjnative/search.o gobjnative/session.o gobjnative/sha256.o gobjnative/sign.o gobjnative/spell.o gobjnative/spellfile.o gobjnative/spellsuggest.o gobjnative/strings.o gobjnative/syntax.o gobjnative/tag.o gobjnative/term.o gobjnative/testing.o gobjnative/textformat.o gobjnative/textobject.o gobjnative/textprop.o gobjnative/time.o gobjnative/typval.o gobjnative/ui.o gobjnative/undo.o gobjnative/usercmd.o gobjnative/userfunc.o gobjnative/version.o gobjnative/vim9cmds.o gobjnative/vim9compile.o gobjnative/vim9execute.o gobjnative/vim9expr.o gobjnative/vim9instr.o gobjnative/vim9script.o gobjnative/vim9type.o gobjnative/viminfo.o gobjnative/winclip.o gobjnative/window.o gobjnative/os_w32exe.o gobjnative/vimres.o gobjnative/xdiffi.o gobjnative/xemit.o gobjnative/xprepare.o gobjnative/xutils.o gobjnative/xhistogram.o gobjnative/xpatience.o gobjnative/gui.o gobjnative/gui_w32.o gobjnative/gui_beval.o -lkernel32 -luser32 -lgdi32 -ladvapi32 -lcomdlg32 -lcomctl32 -lnetapi32 -lversion -lgcc_eh -Wl,-Bstatic -lwinpthread -Wl,-Bdynamic -lole32 -luuid
`

Here is a patch that seems to fix the problem but I'm not sure if it is the best fix.
[Make_cyg_ming.mak.9.0.0752.patch.txt](https://github.com/vim/vim/files/9790708/Make_cyg_ming.mak.9.0.0752.patch.txt)

Note line 1069 is commented out in favour of line 1070. Should it be?

Cheers
John

**Comment by k-takata** [comment]
You are setting `ARCH=native`, but it is unexpected.
`ARCH` is normally detected automatically. If you want to set it explicitly, you should set it to `x86-64` for 64-bit builds and `i686` for 32-bit builds. (Not sure it is related to this issue, though.)

I use mingw-w64 gcc 12.2.0 from MSYS2, and it doesn't have this issue.

**Comment by basilisk0315** [comment]
Hi @k-takata,

I am using mingw64 gcc 12.2.0 from winlibs. Also tried lhmouse's mingw64 with the same result.

I changed my build command to remove the ARCH specification (so it will be auto-detected) as per your suggestion. After rebuilding from scratch, I have the same error.

For me changing the line in Make_cyg_ming.mak (as per my patch) fixes the problem. Although I have slightly refined it to replace this line (#1080):
`LIB += -Wl,-Bstatic -lwinpthread -Wl,-Bdynamic`
with this:
`LIB += -Wl,-Bstatic -lwinpthread -Wl,-Bstatic`

Cheers
John

**Comment by vim-ml** [comment]
On 16-Oct-2022 06:33, John Marriott (Vim Github Repository) wrote:
>
> Hi @k-takata <https://github.com/k-takata>,
>
> I am using mingw64 gcc 12.2.0 from winlibs. Also tried lhmouse's 
> mingw64 with the same result.
>
> I changed my build command to remove the ARCH specification (so it 
> will be auto-detected) as per your suggestion. After rebuilding from 
> scratch, I have the same error.
>
> For me changing the line in Make_cyg_ming.mak (as per my patch) fixes 
> the problem. Although I have slightly refined it to replace this line 
> (#1080 <https://github.com/vim/vim/issues/1080>):
> |LIB += -Wl,-Bstatic -lwinpthread -Wl,-Bdynamic|
> with this:
> |LIB += -Wl,-Bstatic -lwinpthread -Wl,-Bstatic|
>
> Cheers
> John
>
>
Hi @k-takata,

Since moving from gcc to clang (from msys2) this problem has gone away 
for me.

Cheers
John
