### ISSUE TITLE
vim display ?4m

### ISSUE THREAD

**Issue by Shaco-Ma** [vim/vim#12561]
### Steps to reproduce

1.complier vim by myself
2.use commit c9fbd2560f24180d2efa40028ed68427341d2d99
3. complier use python3
4. open file and sometime display unreadable char like ?4m

### Expected behaviour

no display unreadable char like ?4m

### Version of Vim

VIM - Vi IMproved 9.0 (2022 Jun 28, 编译于 May 30 2023 14:50:30) 包含补丁: 1-1591

### Environment

ubuntu 18.04lts
GNOME Shell 3.28.4
$TERM:$TERM
bash:4.4.20(1)-release

**Comment by chrisbra** [comment]
Hm, if I read this correctly, Vim is querying the [modifyOtherKeys state of your terminal](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h4-Functions-using-CSI-_-ordered-by-the-final-character-lparen-s-rparen:CSI-?-Pp-m.1D16) and it looks like your terminal does not understand that. 

Perhaps you may want to try to [disable modifyOtherKeys](https://vimhelp.org/map.txt.html#modifyOtherKeys) or try setting `:set t_RK=` 

In any case, ubuntu 18.04 lts is reaching end of life, you may want to consider upgrading. Perhaps in an updated ubuntu version your terminal (which ever it may be, you unfortunately did not tell us) supports this correctly.

**Comment by Shaco-Ma** [comment]
> Hm, if I read this correctly, Vim is querying the [modifyOtherKeys state of your terminal](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h4-Functions-using-CSI-_-ordered-by-the-final-character-lparen-s-rparen:CSI-?-Pp-m.1D16) and it looks like your terminal does not understand that.
> 
> Perhaps you may want to try to [disable modifyOtherKeys](https://vimhelp.org/map.txt.html#modifyOtherKeys) or try setting `:set t_RK=`
> 
> In any case, ubuntu 18.04 lts is reaching end of life, you may want to consider upgrading. Perhaps in an updated ubuntu version your terminal (which ever it may be, you unfortunately did not tell us) supports this correctly.

find I use gnome shell,and set TERM xterm-256color,in my bashrc,set TERM use gnome-256color is OK,sorry to trouble U
