### ISSUE TITLE
Test_uncrypt_xchacha20v2 and _custom fail on big-endian systems

### ISSUE THREAD

**Issue by jamessan** [vim/vim#12586]
### Steps to reproduce

1. Run test suite on big endian system

### Expected behaviour

Tests are either skipped if the environment isn't supported or pass

### Version of Vim

9.0.1658

### Environment

Debian sid big-endian systems

### Logs and stack traces

```shell
Found errors in Test_uncrypt_xchacha20v2():
command line..script /home/jamessan/vim_sid_s390x/vim-9.0.1658/src/testdir/runtest.vim[573]..function RunTheTest[52]..Test_uncrypt_xchacha20v2[16]..Uncrypt_stable_xxd line 9: Expected ['abcdefghijklmnopqrstuvwxyzäöü', 'ZZZ_äüöÄÜÖ_!@#$%^&*()_+=-`~"'] but got ['©|/\n\x0b\x19ë\x1d\x1e¥?"ÁyK>', 'ë\x19ccø"-µÑ<s{åÕGêDÌl%x?ÕØ6Ç\n\x01"»0zY±*èçÛ\x11:÷2z4\x133Ü\x14Q g¹\x0f:µl\x1fS°$\x16 ZL_ÞM¬&\x11H$ðº\nÁ`']
Found errors in Test_uncrypt_xchacha20v2_custom():
command line..script /home/jamessan/vim_sid_s390x/vim-9.0.1658/src/testdir/runtest.vim[573]..function RunTheTest[52]..Test_uncrypt_xchacha20v2_custom[13]..Uncrypt_stable_xxd line 9: Expected ['', 'foo', 'bar', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10'] but got ['¹s_3éTü\x13º>\x04k15·w^¬\x7fã\fÒ\x14ßíuKec\x05\x03\\ì¤Ï3Òu\x07ì8ºb£''hØ­&\x07?¦ù]~¨ùH \f']
```

**Comment by jamessan** [comment]
I tried changing `Uncrypt_stable_xxd` to use `xxd -e -r`, but that still fails:

```
Found errors in Test_uncrypt_xchacha20v2():
command line..script /home/jamessan/vim_sid_s390x/vim-9.0.1658/src/testdir/runtest.vim[573]..function RunTheTest[52]..Test_uncrypt_xchacha20v2[16]..Uncrypt_stable_xxd line 9: Expected ['abcdefghijklmnopqrstuvwxyz�', 'ZZZ_�Ąܜ֖_!@#$%^&*()_+=-`~"'] but got ['', '1234']
Found errors in Test_uncrypt_xchacha20v2_custom():
command line..script /home/jamessan/vim_sid_s390x/vim-9.0.1658/src/testdir/runtest.vim[573]..function RunTheTest[52]..Test_uncrypt_xchacha20v2_custom[13]..Uncrypt_stable_xxd line 9: Expected ['', 'foo', 'bar', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10'] but got ['', 'bar', '']
command line..script /home/jamessan/vim_sid_s390x/vim-9.0.1658/src/testdir/runtest.vim[573]..function RunTheTest[52]..Test_uncrypt_xchacha20v2_custom line 14: Pattern 'xchacha20v2: using custom \\w\\+ "\\d\\+" for Key derivation.' does not match '\n"test_crypt.vim" 395 lines, 13204 bytes\n"Xtest.txt" 0L, 0B\nNote: Encryption of swapfile not supported, disabling swap file\n"Xcrypt_sodium_v2.txt" [New][xchacha20v2] 4000L, 18893B written\nNeed encryption key for "Xcrypt_sodium_v2.txt"\nNote: Encryption of swapfile not supported, disabling swap file\nxchacha20v2: using default opslimit "2" for Key derivation.\nxchacha20v2: using default memlimit "67108864" for Key derivation.\nxchacha20v2: using default algorithm "2" for Key derivation.\n"Xcrypt_sodium_v2.txt" [xchacha20v2] 4000L, 18893B\nReading viminfo file "viminfo" marks FAILED\n"Xcrypt_sodium_v2.txt" 4000L, 18893B written\n"Xtest.txt" 0L, 0B\nReading viminfo file "viminfo" marks FAILED'
```

**Comment by chrisbra** [comment]
so does encryption work at all on big-ending systems? hm, didn't we used to have a s390 CI system?

**Comment by jamessan** [comment]
> hm, didn't we used to have a s390 CI system?

Travis did.  It would require using something like qemu to do that in GitHub actions.

> so does encryption work at all on big-ending systems?

I can save a file with 'cm=xchacha20v2' and then open it again.  Note that `Test_uncrypt_xchacha20` works.  It's just `Test_uncrypt_xchacha20v2_custom` and `Test_uncrypt_xchacha20v2` that don't.

**Comment by jamessan** [comment]
However, encrypting a file on a little endian system and then trying to read it on a big endian system does not work.

**Comment by chrisbra** [comment]
> Note that `Test_uncrypt_xchacha20` works

not surprising, this uses the hard-coded library values and does not store them in the file. 

> Test_uncrypt_xchacha20v2_custom line

This uses custom Key derivation parameters. 

> nxchacha20v2: using default opslimit "2" for Key derivation.\nxchacha20v2: using default memlimit "67108864" for Key derivation.\nxchacha20v2: using default algorithm "2" for Key derivation

But vim does not detect to use those custom parameters here :/ 

> However, encrypting a file on a little endian system and then trying to read it on a big endian system does not work.

Yeah, looks like the encrypted files are not portable. I guess we need to make sure, the file always uses little endian encoding for the parameters? But I don't know how to do this.

> Travis did. It would require using something like qemu to do that in GitHub actions.

too bad.

**Comment by brammool** [comment]
> > Note that `Test_uncrypt_xchacha20` works
> 
> not surprising, this uses the hard-coded library values and does not
> store them in the file. 
> 
> > Test_uncrypt_xchacha20v2_custom line
> 
> This uses custom Key derivation parameters. 
> 
> > nxchacha20v2: using default opslimit "2" for Key derivation.\nxchacha20v2: using default memlimit "67108864" for Key derivation.\nxchacha20v2: using default algorithm "2" for Key derivation
> 
> But vim does not detect to use those custom parameters here :/ 

The messages may be a bit misleading: they say "default" when the
default value is being used.  It doesn't make a difference whether that
value comes from the file or is using the default value from the
library.  We could mention that for completeness.

> > However, encrypting a file on a little endian system and then trying
> > to read it on a big endian system does not work.
> 
> Yeah, looks like the encrypted files are not portable. I guess we need
> to make sure, the file always uses little endian encoding for the
> parameters? But I don't know how to do this.

Is it the encoded bytes that are not portable?  Or is this only about
the parameters?  I see that the parameters are copied with memcpy(),
thus byte order matters.

There are some examples in memline.c, where the byte order also matters.
E.g. the use of long_to_char() and char_to_long().  Although you would
need "long long" for "opslimit"/"memlinit" and "int" for "alg".

Can we assume most machines use little endian?  Then we can just use
that, and already existing crypted files still work.  Otherwise we would
have to add another crypt method "xchacha20v3".  That only helps for a
file encrypted by a future Vim and opened by an older Vim version
though.  Probably not worth it.

It would be good to test with a big-endian architecture, you never know
what we might find!

-- 
hundred-and-one symptoms of being an internet addict:
241. You try to look for Net Search even when you're in File Manager.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
yep, I think byte order matters here. I also hope that little endian is used mostly, so that we don't have to invent yet another version. 

Let me check with memline.c

> It would be good to test with a big-endian architecture, you never know
what we might find!

I may as well explore that using qemu (but that will be for a separate PR)

**Comment by chrisbra** [comment]
@jamessan can you please check #12655 ?
