### ISSUE TITLE
searchpair and searchpairpos returns wrong position when match is at the column 1

### ISSUE THREAD

**Issue by alexaschee** [vim/vim#12624]
### Steps to reproduce

Codes like:

```
x = 0
if true
    x = 1
else
    x = 2
```

1. Cursor on `else`
2. `:echo searchpairpos('\<if\>', '.*', '\<else\>', 'Wbc')`
3. Returns `[1, 5]`

but 

```
x = 0
 if true # Space before if
    x = 1
else
    x = 2
```

returns `[2, 1]`. (This is fine by me, as I just need the line number)

### Expected behaviour

Returns the right line number.

### Version of Vim

9.0.1668

### Environment

Win 10 (64bit)

**Comment by chrisbra** [comment]
I found the first result surprising `[1,5]`. But anyway, way are you setting the middle pattern to `.*` , which would match everywhere?

**Comment by alexaschee** [comment]
Because setting middle pattern to `''` would match nowhere.

**Comment by dkearns** [comment]
An empty middle pattern isn't tested.

It's matching [1, 5] as the middle match of a possibly enclosing pair.

**Comment by chrisbra** [comment]
so what problem are you trying to actually solve? I cannot imageine, how a search pattern that matches does any good.

**Comment by alexaschee** [comment]
Actually, I'm just trying to write an indent script. I'd like `else` have the same indentation as its matched `if`. So I use `searchpairpos('\<if\>', '.*', '\<else\>', 'Wbc')` to get the said indentation. That's when I found the cursor position is always at the column before the matched `if`. And when `if` starts a line, the cursor moves to the end of previous line. When `if` is on the first line, the cursor has nowhere to go.

If this is not a bug, please close this thread. I'll look for some workaround for my purpose; it's fun too.

**Comment by dkearns** [comment]
There's lots of examples of this in the distributed indent scripts.  It's normally used to match brackets.

You generally don't need to do this for an if-else statement.  You can indent one level if the previous line was an `if`, continue with that indent for the block statement and then deindent if the current line is `else`.

However, you probably want `searchpairpos('\<if\>', '', '\<else\>\zs', 'bnW')`.  See `:help searchpair()` for an explanation of the `\zs`.
