### ISSUE TITLE
Command-line mode "Delete word after the cursor"

### ISSUE THREAD

**Issue by lbrayner** [vim/vim#12623]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

I tend to favor commands instead of mappings, so I do a lot of command line editing, and I believe the Command-line window, while very useful in some use cases, is very slow when compared to Command-line editing. Currently, it is possible to delete a word before the cursor, but not after the cursor, like `Alt-D` on _bash_. The ability to do this would greatly improve the experience.

**Describe the solution you'd like**

There should a Command-line mode mapping to delete characters ahead of the cursor until the next word (like `normal! cw` or `normal! ce`, I'm not sure).

**Additional context**

I also use _vim-fugitive_ extensively and am always editing the command-line.

**Comment by lbrayner** [comment]
Thanks, @lacygoill , that might be just what I need.

**Comment by lbrayner** [comment]
@lacygoill vim-rsi does not provide this: https://github.com/tpope/vim-rsi/blob/45540637ead22f011e8215f1c90142e49d946a54/plugin/rsi.vim#L72

`M-d` only does a `<S-Right><C-W>`, which is not what I need.

**Comment by chrisbra** [comment]
So `M-d` according to [vim-rsi](https://github.com/tpope/vim-rsi) [does](https://github.com/tpope/vim-rsi/blob/45540637ead22f011e8215f1c90142e49d946a54/doc/rsi.txt#L53):

> Delete forwards one word.

Isn't that exactly what you asked for? 

Note: if you are okay with custom mappings and the feature does not need to be builtin into Vim (in which case I'd tend to close this issue), you can create custom maps, similar to what vim-rsi does (or you can ask @tpope for whatever mapping you find missing).
