### ISSUE TITLE
Bash Syntax Highlight wrong with bitwise shift

### ISSUE THREAD

**Issue by A4-Tacks** [vim/vim#12622]
## Open `bash` script `test.sh`
```bash
#!/usr/bin/bash
# `i))`
#!/usr/bin/bash
# `i))`
#for ((i=0; i<10; ++i)); do
#    ((num = 1 << i))
#i))
#    echo foo
#done

for ((i=0; i<10; ++i)); do
    ((num = 1 << i))
    echo foo
done
```

## vimrc
```vimscript
scriptencoding utf-8
set nocompatible
syntax on
set number
set relativenumber
set t_Co=16
```

## image
![Screenshot_20230701_234514](https://github.com/vim/vim/assets/102709083/636d3435-9853-480d-9633-090888a5db30)

### Expected behaviour

Do not process left shift `<<` symbols in `ARITHMETIC EVALUATION` `(())` as `Here Documents`

### Version of Vim

vim-9.0.1628

### Environment

OS: `ArchLinux`
Shell: `Bash-5.1.16(1)-release`
`$TERM` Value: `xterm-256color`

**Comment by chrisbra** [comment]
looks like it is recognized as redirection by vim. But if you remove the spaces between the `<<` it seems to work:
```
for ((i=0; i<10; ++i)); do
    ((num = 1<<i))
    echo foo
done
```

ping @cecamp

**Comment by zzzyxwvut** [comment]
Try containing the `shDblParen` region in the `shDo` region:
https://github.com/vim/vim/blob/d392a74c5a8af8271a33a20d37ae1a8ea422cb4b/runtime/syntax/sh.vim#L269

Append to `$HOME/.vim/after/syntax/sh.vim`:
```vim
if exists("b:is_kornshell") || exists("b:is_bash")
  if has("folding") && exists("g:sh_fold_enabled") && g:sh_fold_enabled =~ '\<[4567]\>'
    syn region shDo	transparent	matchgroup=shConditional start="\<do\>" matchgroup=shConditional end="\<done\>"			contains=@shLoopList,shDblParen fold
  else
    syn region shDo	transparent	matchgroup=shConditional start="\<do\>" matchgroup=shConditional end="\<done\>"			contains=@shLoopList,shDblParen
  endif
endif
```

There is also plenty of alternative arithmetic syntax, e.g.:
```bash
num=$((1 << i))
: $((num = 1 << i))
let num\ =\ '1 << i'
let "num = 1 << i"
let num=1\<\<i
```

**Comment by brammool** [comment]
Is the file correctly recognized as "bash"?  Do:
```
     :echo &filetype
     :echo b:is_bash
```

**Comment by cecamp** [comment]
Try [syntax/sh.vim](http://www.drchip.org/astronaut/vim/index.html#SYNTAX_SH) version 209 ; it seems to address the immediate issue but I haven't gone through the entire test database with it yet.

**Comment by A4-Tacks** [comment]
> Try [syntax/sh.vim](http://www.drchip.org/astronaut/vim/index.html#SYNTAX_SH) version 209 ; it seems to address the immediate issue but I haven't gone through the entire test database with it yet.

Thank you very much. It works very well.
