### ISSUE TITLE
popup_close() wipes out cmdline contents

### ISSUE THREAD

**Issue by girishji** [vim/vim#12634]
### Steps to reproduce

Easy to reproduce:

1) Use this script to start Vim:
```
vim -Nu NONE -S <(cat <<EOF                                                               1 :(
    " vim:ts=4:ft=vim
    vim9script
    var wid = -1
    def PShow()
        wid = popup_menu([], {hidden: true, pos: 'botleft', line: &lines - &cmdheight })
    enddef

    def PHide()
        # wid->popup_move({ pos: 'center' })
        wid->popup_close()
    enddef

    au CmdlineEnter : PShow()
    au CmdlineLeave : PHide()
EOF
)
```

2) Type `:echo 'foo'` and hit `<CR>`. String `foo` gets wiped out from cmdline.

3) To fix this problem uncomment the line above `popup_close()` and repeat the experiment. `foo` remains on the cmdline. Moving the popup to `center` somehow fixes this.

4) Problem is coming from where popup window is positioned, even through it is hidden. You could change position to `line: &lines - &cmdheight - 1` and the problem goes away.

### Expected behaviour

`popup_close()` should not remove output of `echo` present on cmdline.

### Version of Vim

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jun 03 2023 16:11:47)

### Environment

MacOS
xterm-256 (iTerm2)
zsh

**Comment by LemonBoy** [comment]
I cannot reproduce the problem on Windows using the latest git revision.

**Comment by girishji** [comment]
Confirmed, problem seems to have gone away in latest release.

**Comment by chrisbra** [comment]
then please close the ticket if it no longer active
