### ISSUE TITLE
unable to update `.tar.zst`

### ISSUE THREAD

**Issue by e-kwsm** [vim/vim#12639]
### Steps to reproduce

```console
$ echo foo > a.dat
$ tar -acf a.tar.zst a.dat
```

`vim -u NORC -N a.tar.zst`, select a.dat, `:s/foo/bar/`, `:wq` (`tarfile::a.dat`), and `:q` (`a.tar.zst`).
However, `a.tar.zst` is not updated, and `a.tar` is created with the updated content:

```console
$ tar -xOf a.tar.zst
foo
$ tar -xOf a.tar
bar
```

### Expected behaviour

`a.tar.zst` is updated and `a.tar` does not exist.

### Version of Vim

9.0.1672 (#12637 is applied)

### Environment

- OS: Debian 12.0
- terminal: GNOME Terminal 3.46.8 using VTE 0.70.3 +BIDI +GNUTLS +ICU +SYSTEMD
- $TERM: xterm-256color

**Comment by fiction3** [comment]
I have this problem also. Any updates on this bug
