### ISSUE TITLE
The interface becomes unresponsive after mousewheel up to the first (or last) line

### ISSUE THREAD

**Issue by bugdanov** [vim/vim#1264]
To reproduce:
- open or create an empty document with vim in gnome-terminal (I can not try with other terminals)
- while the cursor is already on the first line, try to scroll up with the mouse wheel a few times

Now you can continue to drink your coffee, start to learn how to use EMACS (or whatever) before the interface becomes responsive again.

Looks like mouse wheel events are converted to cursor key events and buffered.

It would be a great user experience if those mouse wheel events were ignored when the cursor is already at the top/bottom of the document ;-)

I could not find a way to implement it right away, hope somebody does.

**Comment by brammool** [comment]
Rurik Bugdanov wrote:

> To reproduce:
> - open or create an empty document with vim in gnome-terminal (I can not try with other terminals)
> - while the cursor is already on the first line, try to scroll up with the mouse wheel a few times
> 
> Now you can continue to drink your coffee, start to learn how to use EMACS (or whatever) before the interface becomes responsive again.
> 
> Looks like mouse wheel events are converted to cursor key events and buffered.
> 
> It would be a great user experience if those mouse wheel events were ignored when the cursor is already at the top/bottom of the document ;-)
> 
> I could not find a way to implement it right away, hope somebody does.

I cannot reproduce the problem, works fine for me.  Tried xterm and
gnome-terminal 3.20.2

## 

Portable Computer:  A device invented to force businessmen
to work at home, on vacation, and on business trips.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bugdanov** [comment]
Oh, it's only when vim is run within a screen session (eg with "screen vim ...").

So it looks more a "screen" related issue.

I never had the idea to test without "screen" before your answer (I use a script named "vi" to run screen transparently, and to re-attach automatically to an existing vim session) 

Thanks.
