### ISSUE TITLE
forced restricted mode based on $SHELL astonishes

### ISSUE THREAD

**Issue by salewski** [vim/vim#12656]
Please consider reverting the change applied to `vim` in patch 8.2.4282, in which the value of the `SHELL` environment variable is inspected and used to cause `vim` to enter "restricted" mode (a la `rvim` or the `-Z` command line option).

In the presence of a `SHELL` environment variable that has been placed in the environment (e.g., via `sudo`, rather than explicitly set by the user in a shell startup script, or similar) and happens to have an unfortunate value ending in `false` or `nologin`, the behavior of `vim` acting as `rvim` is unexpected, confusing, and breaks basic job control usage in which `vim` can be suspended via `CTRL-z`.

**EDITED:** I have a tested patch in PR #12657 which basically reverses the changes from patch 8.2.4282. ~~I'll create a PR for it shortly.~~

### Steps to reproduce the issue:

(since [patch 8.2.4282](https://github.com/vim/vim/commit/adbb1bf21dad5697cd82d46d9dd9e8e8d0f647e6)):
```sh
    $ SHELL=/usr/bin/nologin /path/to/vim
```
OR:
```sh
    $ SHELL=/la/la/la/false /path/to/vim
```
OR similar...

Once inside `vim`, press `CTRL-z` to attempt to suspend the `vim` process (standard *nix job control). Rather than `vim` being suspended, an error is shown:
```
    E145: Shell commands and some functionality not allowed in rvim
```

Having `$SHELL` set (intentionally or otherwise) to any value that ends with either `nologin` or `false` prevents `vim` from being suspended.

**WORKAROUND:** Prior to invoking `vim`, either `unset SHELL` or ensure `$SHELL` is set to some value that will not trigger this behavior:
```sh
    $ unset SHELL
    $ /path/to/vim
```
OR
```sh
    $ SHELL=/bin/sh /path/to/vim
```

See also:
   * [patch 8.2.4282](https://github.com/vim/vim/commit/adbb1bf21dad5697cd82d46d9dd9e8e8d0f647e6)
   * #9681 

### Expected behaviour

I was expecting `vim` to be suspended when I pressed `CTRL-z`, per normal Unix job control behavior, and per long-standing `vim` behavior.

### Version of Vim

```tty
    $ /usr/bin/vim --version | head -n 4
    VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Apr 15 2023 04:26:05)
    macOS version - x86_64
    Included patches: 1-1424
    Compiled by root@apple.com
```

### Environment

Operating system: macOS 13.4.1 ("Ventura")
```tty
    $ /usr/bin/sw_vers
    ProductName:            macOS
    ProductVersion:         13.4.1
    BuildVersion:           22F82
```

Terminal: XTerm (running on GNU/Linux; access to the macOS machine is over ssh)
Value of $TERM: `xterm-256color`
Shell: Bash 5.2.15(1)-release (from MacPorts)

### Logs and stack traces

Here's what the session looked like that led me to this issue:
```shell
    $ /usr/bin/sudo /opt/local/bin/bash
    Password:

    # whoami
    root

    # /usr/bin/vim /etc/whatever

    <Edit a bunch of changes (not yet written)>
    <Attempt to suspend vim via CTRL-z to check on something>
    <trip over "vim behaving as rvim" behavior>
```

The above is a common flow for any administrator. I happened to trip over the restricted behavior because our company MDM push forced an OS update on me (macOS 11.x ("Big Sur") to macOS 13.x ("Ventura")) and changed the `root` user's login shell to `/usr/bin/false` in the macOS Directory Services. That caused `sudo` to use that value to set the `SHELL` environment variable in the newly created Bash shell for the `root` user.

While the issue can be easily worked around once you know the root cause, the root cause is hardly apparent to the user. And the user should not need to do that. The behavior is [astonishing](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) because it breaks an important decades-old, legit usage pattern. Also, the purpose of the `SHELL` environment variable is to allow a user to indicate a preference for a particular shell to applications (such as `vim`) that allow the user to "shell out" and similar; imposing 'restricted' semantics of the user's `vim` session based on the value of `$SHELL` is overloading the semantics and is confusing to the user.

Here's [what POSIX says about environment variables](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html) in general:

> If the variables in the following two sections are present in the
> environment during the execution of an application or utility, they
> shall be given the meaning described below. Some are placed into the
> environment by the implementation at the time the user logs in; all
> can be added or changed by the user or any ancestor of the current
> process. The implementation adds or changes environment variables
> named in POSIX.1-2017 only as specified in POSIX.1-2017. If they are
> defined in the application's environment, the utilities in the Shell
> and Utilities volume of POSIX.1-2017 and the functions in the System
> Interfaces volume of POSIX.1-2017 assume they have the specified
> meaning. Conforming applications shall not set these environment
> variables to have meanings other than as described.

and the `SHELL` environment variable in particular:

> SHELL
>     This variable shall represent a pathname of the user's preferred
>     command language interpreter. If this interpreter does not conform
>     to the Shell Command Language in XCU Shell Command Language,
>     utilities may behave differently from those described in
>     POSIX.1-2017.

**Comment by chrisbra** [comment]
I am not sure. I tend to think that if `$SHELL` does contain `false` or `nologin` setting restricted mode may actually make sense.

**Comment by salewski** [comment]
> I am not sure. I tend to think that if `$SHELL` does contain `false` or `nologin` setting restricted mode may actually make sense.

Why is that? `$SHELL` is a user-setable variable, not a security mechanism.

**Comment by chrisbra** [comment]
> Why is that? $SHELL is a user-setable variable, not a security mechanism.

Correct, but I would say the problem is that something is setting your SHELL to `false`. I don't think Vim should try to work-around this. $SHELL has been set to indicate that you do not have a valid shell to execute commands, so let's not try to run shell commands anyhow.

**Comment by salewski** [comment]
> > Why is that? $SHELL is a user-setable variable, not a security mechanism.
> 
> Correct, but I would say the problem is that something is setting your SHELL to `false`. I don't think Vim should try to work-around this. $SHELL has been set to indicate that you do not have a valid shell to execute commands, so let's not try to run shell commands anyhow.

I appreciate what you are saying, @chrisbra , but this is not about invoking a new shell subprocess. It is just trying to suspend vim via CTRL-Z to get back to the parent process shell from which vim was invoked. Enforcing "restricted" mode in this scenario is preventing the user from getting back to the interactive parent shell process that the user was already using.
