### ISSUE TITLE
Possible SEGV (null pointer dereference) in handle_viminfo_register()

### ISSUE THREAD

**Issue by GJDuck** [vim/vim#12652]
### Steps to reproduce

1. Copy the attached file to `~/.viminfo`
2. Run `vim`

Attachment: [viminfo.txt](https://github.com/vim/vim/files/11997840/viminfo.txt)

### Expected behaviour

The attached file is corrupt.  However, `vim` should handle it gracefully rather than crashing.

### Version of Vim

9.0 (tested both github HEAD and ubuntu distro version)

### Environment

Operating system: `Ubuntu 23.04`
Term: `xterm-256color`
Shell: `bash-5.2.15`

**Comment by Pierre-Colin** [comment]
I did some debugging. The crash seems to come from the loop at [src/viminfo.c:1800](https://github.com/vim/vim/blob/4112acae0816e3f64c082b1e773dd5f4a100685e/src/viminfo.c#L1800). It assumes `vp[i + 6].bv_type == BVAL_STRING`. The crash occurs at the line `|3,1,1,1,1,0,71489,,"125"`. The empty entry breaks the assertion.

I don’t know how to best handle that, for `handle_viminfo_register` can’t return errors.

I tried inserting the following at the beginning of the loop body. Vim does diagnose an error in `.viminfo` around where that line is. However, it still segfaults when quitting.
```c
        if (vp[i + 6].bv_type != BVAL_STRING)
            continue;
```

**Comment by chrisbra** [comment]
Hm, I guess this patch is needed then:
```
diff --git a/src/viminfo.c b/src/viminfo.c
index b772fc8f3..5e40974a4 100644
--- a/src/viminfo.c
+++ b/src/viminfo.c
@@ -1804,6 +1804,8 @@ handle_viminfo_register(garray_T *values, int force)
            y_ptr->y_array[i] = vp[i + 6].bv_string;
            vp[i + 6].bv_string = NULL;
        }
+       else if (vp[i + 6].bv_type == BVAL_EMPTY)
+           y_ptr->y_array = NULL;
        else
            y_ptr->y_array[i] = vim_strsave(vp[i + 6].bv_string);
     }
```

**Comment by Pierre-Colin** [comment]
I don’t think so. The array `vp` can have more than 7 elements. @GJDuck’s example yields one of size 8, and the code parsing that line supports arbitrary lengths.

@chrisbra’s patch still segfaults for `BVAL_NR`, and it also leaks memory. I have addressed both issues and am putting together a PR.

**Comment by chrisbra** [comment]
Thanks, Can you please create a test for it?Am 18.08.2023 um 18:29 schrieb Pierre Colin ***@***.***>:﻿
I don’t think so. The array vp can have more than 7 elements. @GJDuck’s example yields one of size 8, and the code parsing that line supports arbitrary lengths.
@chrisbra’s patch still segfaults for BVAL_NR, and it also leaks memory. I have addressed both issues and am putting together a PR.

**Comment by Pierre-Colin** [comment]
I tried the following test.
```diff
diff --git a/src/testdir/test_viminfo.vim b/src/testdir/test_viminfo.vim
index 0551ea1..1136b41 100644
--- a/src/testdir/test_viminfo.vim
+++ b/src/testdir/test_viminfo.vim
@@ -1279,4 +1279,15 @@ func Test_viminfo_merge_old_jumplist()
   bw!
 endfunc
 
+" Test for invalid register
+func Test_viminfo_invalid_register()
+  let lines = [
+       \ '"',
+       \ '|3,1,1,1,1,0,71489,,"125"',
+       \ '"',
+       \ ]
+  call writefile(lines, 'Xviminfo', 'D')
+  rviminfo! Xviminfo
+endfunc
+
 " vim: shiftwidth=2 sts=2 expandtab
```
It fails, but without reporting `SEGV`. Calling `rviminfo!` manually on a file with that content does crash Vim. The `make test_viminfo` command then reports `cat: messages: No such file or directory`.

Are there tests expecting a crash I could draw from?

**Comment by mattn** [comment]
Seems to be null dereference.

```diff
diff --git a/src/viminfo.c b/src/viminfo.c
index b772fc8f3..61be63baf 100644
--- a/src/viminfo.c
+++ b/src/viminfo.c
@@ -1804,7 +1804,7 @@ handle_viminfo_register(garray_T *values, int force)
 	    y_ptr->y_array[i] = vp[i + 6].bv_string;
 	    vp[i + 6].bv_string = NULL;
 	}
-	else
+	else if (vp[i + 6].bv_string)
 	    y_ptr->y_array[i] = vim_strsave(vp[i + 6].bv_string);
     }
 }
```

**Comment by mattn** [comment]
I may have better to set NULL when else case.

**Comment by yegappan** [comment]
I have added a test for this in the https://github.com/vim/vim/pull/12845 PR.
