### ISSUE TITLE
E924: Current window was closed

### ISSUE THREAD

**Issue by btwe** [vim/vim#1267]
I am not sure if the following is an issue with vim or my plugin. But the issue came up between vim 7.4 and 7.9/8.0.

### Reproduce:

Create a location list with lgrep while having a file opened in a buffer window.
```vimscript
  let l:grepprg_bak=&grepprg
  let l:grepformat_bak=&grepformat
  try
    let &grepprg="./td_vimwiki.py -o D
    let &grepformat="%f:%l %m"
    silent lgrep!
    redraw!
    lopen 30
  finally
    let &grepprg=l:grepprg_bak
    let &grepformat=l:grepformat_bak
  endtry

```

### Symptom: 

- In v7.4 it works as expected. The location list shows up in split window, pressing Enter on an entry opens the file containing the target and positions the pointer there.
- In 7.9/8.0 Pressing Enter on an entry, first prints an error message: `E924: Current window was closed`. After that the target file is opened in a new buffer, but the pointer is placed at line 1 col 1. Creating the location list again and selecting the target of the currently opened buffer works again as expected. 

Because, I do not know if I did something wrong in my plugin, or a small bug made it into vim during the releases, I opened this issue and also kindly ask for help if the problem is on my side.

Thanks,

**Comment by chrisbra** [comment]
Can you please include the exact version information for 8.0, when this 
happened?

**Comment by btwe** [comment]
IIRC, this behavior sneaked in after upgrading vim from
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 19 2015 15:43:00)
Included patches: 1-738
```
to
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 27 2016 15:06:11)
Included patches: 1-1795
```
and is still there in 
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 16 2016 15:01:39)
Included patches: 1-86
```

Sorry for confusing with 7.9 in the issue opening.

The vim out of current debian stable also works as expected
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 31 2015 23:36:03)
Included patches: 1-488, 576
```

But do you think, the plugin part is relatively sane?

Many thanks,

**Comment by vim-ml** [comment]
Hi,

On Tue, Nov 22, 2016 at 3:52 AM, btwe <vim-dev-github@256bit.org> wrote:
> I am not sure if the following is an issue with vim or my plugin. But the
> issue came up between vim 7.4 and 7.9/8.0.
>
> Reproduce:
>

Can you try to reproduce this problem after starting Vim with
"vim -N -u NONE"?

I tried to reproduce this problem using a simple location list grep
(as I don't have the td_vimwiki.py script) and couldn't reproduce
the problem.

>
> Create a location list with lgrep while having a file opened in a buffer
> window.
>
>   let l:grepprg_bak=&grepprg
>   let l:grepformat_bak=&grepformat
>   try
>     let &grepprg="./td_vimwiki.py -o D
>     let &grepformat="%f:%l %m"
>     silent lgrep!
>     redraw!
>     lopen 30
>   finally
>     let &grepprg=l:grepprg_bak
>     let &grepformat=l:grepformat_bak
>   endtry
>
> Symptom:
>
> In v7.4 it works as expected. The location list shows up in split window,
> pressing Enter on an entry opens the file containing the target and
> positions the pointer there.
> In 7.9/8.0 Pressing Enter on an entry, first prints an error message: E924:
> Current window was closed. After that the target file is opened in a new
> buffer, but the pointer is placed at line 1 col 1. Creating the location
> list again and selecting the target of the currently opened buffer works
> again as expected.
>
> Because, I do not know if I did something wrong in my plugin, or a small bug
> made it into vim during the releases, I opened this issue and also kindly
> ask for help if the problem is on my side.
>

Are you using any autocmds/plugins that alter the windows when opening
a file?

- Yegappan

**Comment by btwe** [comment]
> Can you try to reproduce this problem after starting Vim with "vim -N -u NONE"? 

The error could also be reproduced with a simple lvimgrep with my configuration:
```vimscript
:lvimgrep /pattern/ ./**/*.txt
:lopen
"select a by now unopened file
```
I failed to reproduce it with `vim -N -u NONE`. I disabled my pathogen plugins one after another. The faulty plugin was `syntastic` which I had in an aged version in my bundle. I also tested to run with only that one enabled which also hit that error.
I fetched a newer version of `syntastic` from the repo and the error is now gone.

Sorry for bothering you with my faulty config. At least I learned to use `vim -N -u NONE`. Next I'll head towards debugging.

Please close.
Cheers,
