### ISSUE TITLE
Garbled output on serial terminals with XON/XOFF flow control after patch 8.2.0852

### ISSUE THREAD

**Issue by jtsiomb** [vim/vim#12674]
### Steps to reproduce

1. Login over a serial terminal, in this case a DEC VT420 which only supports XON/XOFF flow control, and not CTS/RTS.
2. run vim.
3. encounter severe screen corruption, especially on large redraws, and even spurious inputs.

I tracked down the problem to a regression introduced with patch 8.2.0852, referencing bug report #6166. Removing IXON from the bitmask inversion at `src/os_unix.c:3670`, fixes the issue.

While it's not unreasonable to want the ability to bind ctrl-s to something, the solution cannot be to make vim unusable over serial lines relying on software flow control. At the very least this should be made an option.

### Expected behaviour

I expected vim to be usable on a common DEC serial terminal.

### Version of Vim

9.0.1672

### Environment

Operating System: Debian GNU/Linux
Terminal: DEC VT420
$TERM: vt420
shell: bash 5.2.15

The critical factor is that the terminal relies on XON/XOFF flow control. All other details are irrelevant.

**Comment by jtsiomb** [comment]
Many things have changed since I posted this bug report, namely the unfortunate demise of Bram, so I guess this has fallen by the wayside. Is there any interest in fixing this issue? Does anyone want to discuss options and maybe give me the big picture of how this could be made into a configuration option if that's the consensus on how this should be handled?

Currently I'm just reversing that patch I mentioned, and building vim for my own use. I don't care about being able to bind ctrl-s to anything, so that works for me. I don't have a huge incentive driving me to dig deep into how vim handles configuration, and how to change something that seems to be happening on init once into something that can be toggled on and off. But ideally I'd like to see this resolved, so if there's anyone willing to discuss what's the best way to do this, and point me to the right direction in the source code, I could try to make the necessary changes myself and submit a pull request.

**Comment by chrisbra** [comment]
It hasn't fallen by. it's just that nobody is working on that. I am afraid that simply reversing that patch isn't an option however. Open for suggestions.

**Comment by jtsiomb** [comment]
That's what I said. I think probably the best thing to do is to make it a configuration option. "do you want to be able to bind ctrl-s" or "do you need XON/XOFF to work"?

**Comment by ant0sha** [comment]
What about vim automatically recognizes it, based on presence of "xo" terminfo entry? Following sample program report xo=y only if TERM=vt420 but not if TERM=xterm for example.

```
#include <stdio.h>
#include <stdlib.h>
#  include <termcap.h>

int main(int argc, char**argv)
{
  char termbuf[1024];
  if (tgetent(termbuf, getenv("TERM")) != 1)
    printf("E: no termcap\n");
  if (tgetflag("xo") > 0)
    printf("xo=y\n");
}
```

**Comment by jtsiomb** [comment]
That sounds great!

**Comment by ant0sha** [comment]
> That sounds great!

Could you perhaps test PR #14542 with real vt420 hardware?

**Comment by jtsiomb** [comment]
> Could you perhaps test PR #14542 with real vt420 hardware?

Yeap, just tested on the vt420 and it seems to work perfectly.
