### ISSUE TITLE
Can't cycle popup entries, can we?

### ISSUE THREAD

**Issue by 097115** [vim/vim#12689]
Let's say that we have a popup defined, something like this:

    :call popup_menu(['aaa', 'bbb', 'ccc', 'ddd'], #{filter: 'Filter_function', callback: 'Callback_function'})

![](https://i.imgur.com/ZyQRP6t.png)

And if the cursor is on `aaa`, then pressing `k`, `<C-p>`, or `<Up>` doesn't move the cursor to `ddd`, right? Would be an UI enhancement, though, what do you think? :)

**Comment by chrisbra** [comment]
Please ask usage questions on vi.stackexchange.com or use the vim_use mailinglist. I don't know popups very well, so I am not the best to answer those questions. Thanks.

**Comment by 097115** [comment]
I'm just saying, it seems to me that such basic functionality belongs more to a lower level, like being implemented in Vim itself, not in user-defined functions.

**Comment by chrisbra** [comment]
It is in the form of `popup_menu_filter()`. I think the topic of being able to focus popup windows and how those should receive keyboard input has been discussed here various times and was discarded more or less.

**Comment by 097115** [comment]
Except it's not anywhere close completed but whatever...

**Comment by chrisbra** [comment]
You can cycle popup entries, can't you?

**Comment by 097115** [comment]
No, I can't.

**Comment by bfrg** [comment]
@chrisbra I think what @097115 wants is to jump from the very first entry directly to the last one, and vice versa. Currently this is not possible with `popup_filter_menu()`.

@097115 You're right, it is a little bit low-level. I use something like the following all the time and it works pretty well. The only thing that looks weird are the `win_execute()` calls.

```vim
vim9script

def Popup_filter(winid: number, key: string): bool
    if key == 'j' || key == "\<Down>" || key == "\<C-n>" || key == "\<Tab>"
        win_execute(winid, line('.', winid) == line('$', winid) ? ':1' : 'normal! +')
    elseif key == 'k' || key == "\<Up>" || key == "\<C-p>" || key == "\<S-Tab>"
        win_execute(winid, line('.', winid) == 1 ? ':$' : 'normal! -')
    elseif key == 'g' || key == "\<Home>"
        win_execute(winid, ':1')
    elseif key == 'G' || key == "\<End>"
        win_execute(winid, ':$')
    elseif key == 'q'
        popup_close(winid, -1)
    elseif key == "\<Cr>" || key == "\<Space>"
        popup_close(winid, line('.', winid))
    endif
    return true
enddef

const text: list<string> = ['aaa', 'bbb', 'ccc', 'ddd', 'eee', 'fff']

popup_menu(text, {
    filtermode: 'n',
    filter: Popup_filter,
    callback: (winid: number, result: number) => {
        if result > 0
            echomsg text[result - 1]
        endif
    }
})
```

**Comment by 097115** [comment]
@bfrg 

Thanks!

(And, I'd say, that's a good illustration how a user has to pollute their functions with a crutch for that shouldn't have been broken in the first place.)

**Comment by chrisbra** [comment]
Ah, I indeed missed that this is just about the wrapping around in the `popup_filter_menu()` function. The following patch should fix it:

```patch
diff --git a/src/popupwin.c b/src/popupwin.c
index a0d33fd0b..afbc52f23 100644
--- a/src/popupwin.c
+++ b/src/popupwin.c
@@ -2560,12 +2560,20 @@ f_popup_filter_menu(typval_T *argvars, typval_T *rettv)
     res.v_type = VAR_NUMBER;

     old_lnum = wp->w_cursor.lnum;
-    if ((c == 'k' || c == 'K' || c == K_UP || c == Ctrl_P)
-                                                     && wp->w_cursor.lnum > 1)
-       --wp->w_cursor.lnum;
-    if ((c == 'j' || c == 'J' || c == K_DOWN || c == Ctrl_N)
-                      && wp->w_cursor.lnum < wp->w_buffer->b_ml.ml_line_count)
-       ++wp->w_cursor.lnum;
+    if (c == 'k' || c == 'K' || c == K_UP || c == Ctrl_P)
+    {
+       if (wp->w_cursor.lnum > 1)
+           --wp->w_cursor.lnum;
+       else
+           wp->w_cursor.lnum = wp->w_buffer->b_ml.ml_line_count;
+    }
+    if (c == 'j' || c == 'J' || c == K_DOWN || c == Ctrl_N)
+    {
+       if (wp->w_cursor.lnum < wp->w_buffer->b_ml.ml_line_count)
+           ++wp->w_cursor.lnum;
+       else
+           wp->w_cursor.lnum = 1;
+    }
     if (old_lnum != wp->w_cursor.lnum)
     {
        // caller will call popup_highlight_curline()
```

**Comment by 097115** [comment]
@chrisbra Thanks!

After some initial testing, it looks good.

**Comment by Shane-XB-Qian** [comment]
@Christian ***@***.***> what if someone not like the wrap? and it's just a preference specially it should be not too complex to implement it by itself, so I think it's not a good start, sooner or later there others customerized requiement, I agreed your original answer: this mostly just a  *question*, not a bug.

--
shane.xb.qian
