### ISSUE TITLE
Highlight shebang for all filetypes

### ISSUE THREAD

**Issue by Freed-Wu** [vim/vim#12683]
All *nix supports shebang. Why not highlight shebang for all filetypes?

There are some filetypes support highlight shebangs:

```shell
$ rg -F '\%^#!'
syntax/dtrace.vim:26:syn match dtraceComment "\%^#!.*-s.*"
syntax/euphoria3.vim:87:syn match   euphoria3Comment    "\%^#!.*$"
syntax/lua.vim:123:syn match luaComment "\%^#!.*"
syntax/racket.vim:606:syntax match racketSharpBang "\%^#![ /].*" display
syntax/rust.vim:184:syn match rustShebang /\%^#![^[].*/
syntax/raku.vim:1107:syn match rakuShebang display "\%^#!.*"
syntax/scala.vim:190:syn match scalaShebang "\%^#!.*" display
syntax/ruby.vim:434:syn match   rubySharpBang    "\%^#!.*" display
syntax/j.vim:117:syntax match jSharpBang /\%^#!.*$/
syntax/expect.vim:78:syn match   expectSharpBang        "\%^#!.*"
syntax/falcon.vim:65:syn match falconSharpBang "\%^#!.*" display
syntax/euphoria4.vim:188:syn match   euphoria4Comment   "\%^#!.*$"
syntax/d.vim:145:syn match dSharpBang "\%^#!.*"     display
syntax/cs.vim:165:  syn match   csShebang       "\%^#!.*" display
```

**Describe the solution you'd like**

Use a same syntax vim to highlight shebang for all filetypes, not create `syn match XXXshebang` for every filetyps.

**Comment by chrisbra** [comment]
Well, a shebang does not make sense for various filetypes. Like `html`, `markdown`, `java`, `c` etc. Highlighting it there would be wrong. And apparently, when looking at the above output, there is a slight difference on what is allowed as shebang for dtrace, rust and racket

**Comment by Freed-Wu** [comment]
Although it doesn't make sense for some filetypes, *nix still treat shebang as a special element so highlight it to let people know this file can be executed should make sense.

**Comment by chrisbra** [comment]
are you talking about nix OS? Or what do you mean with `*nix`?

**Comment by DominiquePelle-TomTom** [comment]
@Freed-Wu wrote:

> Although it doesn't make sense for some filetypes, *nix still treat shebang as a special element so highlight it to let people know this file can be executed should make sense.

I don't think that's the case, do you have some link to support this claim?
AFAIK, shebang is only for executable scripts, so let's not use it for anything else.
I would rather reject the ticket.

**Comment by Freed-Wu** [comment]
Or provide a unified function to highlight shebang not to let every `syntax/*.vim` write similar code to do this job?

```
$ rg -F '\%^#!'
syntax/dtrace.vim:26:syn match dtraceComment "\%^#!.*-s.*"
syntax/euphoria3.vim:87:syn match   euphoria3Comment    "\%^#!.*$"
syntax/lua.vim:123:syn match luaComment "\%^#!.*"
syntax/racket.vim:606:syntax match racketSharpBang "\%^#![ /].*" display
syntax/rust.vim:184:syn match rustShebang /\%^#![^[].*/
syntax/raku.vim:1107:syn match rakuShebang display "\%^#!.*"
syntax/scala.vim:190:syn match scalaShebang "\%^#!.*" display
syntax/ruby.vim:434:syn match   rubySharpBang    "\%^#!.*" display
syntax/j.vim:117:syntax match jSharpBang /\%^#!.*$/
syntax/expect.vim:78:syn match   expectSharpBang        "\%^#!.*"
syntax/falcon.vim:65:syn match falconSharpBang "\%^#!.*" display
syntax/euphoria4.vim:188:syn match   euphoria4Comment   "\%^#!.*$"
syntax/d.vim:145:syn match dSharpBang "\%^#!.*"     display
syntax/cs.vim:165:  syn match   csShebang       "\%^#!.*" display
```

**Comment by chrisbra** [comment]
that is 14 syntax files (and as mentioned, at least for dtrace and rust and racket, they use slighty different regex to highlight, this might be intetionally) out of [several hundreds syntax files](https://github.com/vim/vim/tree/master/runtime/syntax)  (if I counted correctly that was 686 in my `runtime/syntax` directory).

**Comment by Freed-Wu** [comment]
I doubt filetypes can be executed by shebang should be very many. The languages using `#` as comment usually can be executed by shebang. The number should be much larger than 14.

**Comment by chrisbra** [comment]
so if it aren't that many (and the shebang is not valid in a lot of other filetypes) I am tending to close this, because that single line 

```
syn match SheBang "\%^#!.*"
```

doesn't seem too bad to write

**Comment by Freed-Wu** [comment]
> so if it aren't that many

Not sure. Now close this until someone can give an accurate answer.

**Comment by k-takata** [comment]
* dtrace: It requires `-s` option to specify the script file from command line.
* Rust: The shebang must start with `#!`, but must not be followed by `[`.
  https://doc.rust-lang.org/reference/crates-and-source-files.html#shebang
* Racket: The shebang must start with `#!` and the next character must be a space or `/`.
  https://docs.racket-lang.org/guide/scripts.html

The shebang may depend on the type of the script.
