### ISSUE TITLE
different behavior between <C-v> and <C-q>

### ISSUE THREAD

**Issue by Madeleine12** [vim/vim#12684]
### Steps to reproduce

With `<C-v>`
1. `r` (replace mode)
2. `<C-v>` `xff` (replace the char under the cursor with ÿ)

With `<C-q>`
1. `r`
2. `<C-q>` `xff` (does not replace char under the cursor with ÿ)

### Expected behaviour

It should be possible to replace the character under the cursor by ÿ in both cases, with `<C-v>` and also with `<C-q>`.

### Version of Vim

8.2.4919

### Environment

OS : Ubuntu 22.04.2 LTS
Terminal : GNOME Terminal 3.44.0 Using VTE version 0.68.0 +BIDI +GNUTLS +ICU +SYSTEMD
Value of $TERM : xterm-256color
Shell : bash

**Comment by pierreganty** [comment]
@chrisbra your patch fixes the issue as described. However, if you replace `r` with `gr` at step 1 the issue is still there and the patch does not fix it.

**Comment by chrisbra** [comment]
fixed it

**Comment by pierreganty** [comment]
Tested.  It works. Thank you @chrisbra .
