### ISSUE TITLE
[vim9script] Type mismatch in new() not caught when exception is checked inside a function

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#12701]
### Steps to reproduce

Source this script:

```vim
vim9script

class C
  def new(x: number) # NOTE: this bug depends on new() having a typed parameter
  enddef
endclass

def Check()
  try
    C.new('abc')
  catch
    echo $'OK! This exception was caught: {v:exception}'
  endtry
enddef

try
  C.new('abc')
catch
  echo $'OK! This exception was caught: {v:exception}'
endtry

Check() # Fails with E1013
```

The exception is caught correctly by the try-catch block at the script level, but E1013 is raised when executing `Check()`. Note that this bug shows up only when `new()`'s arguments are typed, as in the snippet above: if `new()`'s arguments are members, then the code works as one would expect. That is, all exceptions are caught if the definition of the class is changed as follows:

```vim
class C
  this.x: number
  def new(this.x)
  enddef
endclass
```

### Expected behaviour

An type mismatch exception should be caught also when checking for the exception happens inside a function.

### Version of Vim

9.0.1677

### Environment

macOS 13.4.1
Apple Terminal
xterm-256color
ZSH 5.9

**Comment by LemonBoy** [comment]
Not sure this is a bug, `Check` is a function and is thus being bytecode-compiled on first use, the error you're seeing is not caught because it's not happening at runtime. Script-level statements, on the other hand, are not compiled making the type error/exception a runtime event.

**Comment by h-east** [comment]
About the matter of a title, it is a specification.  Not a bug.
Please see `:help :def`.
```
                        The function will be compiled into instructions when
                        called, or when :disassemble or :defcompile is
                        used.  Syntax and type errors will be produced at that
                        time.
```


---

And actually, it is a bug that an exception occurs in the following code.
(Since it is a type error, it should be an error at compile time.)

> if new()'s arguments are members, then the code works as one would expect. That is, all exceptions are caught if the definition of the class is changed as follows:
```vim
class C
  this.x: number
  def new(this.x)
  enddef
endclass
```

When I investigated the Vim source code, I found that the type check was not performed when the formal argument was the object member ("this.~").

A patch has been created to fix this. I'll make a PR after adding the test.
Please wait.

**Comment by errael** [comment]
IIUC, the behavior has changed from the initial description. 9.0.1922
