### ISSUE TITLE
line number no taken into account when wrapping in MANPAGER  mode

### ISSUE THREAD

**Issue by nkh** [vim/vim#12703]
### Steps to reproduce

MANPAGER="vim -c 'set nospell' +MANPAGER -"

my vimrc settings:
```set nocompatible

filetype plugin on
syntax on

set backspace=indent,eol,start
set breakindent
set clipboard^=unnamed,unnamedplus
set dictionary+=/usr/share/dict/words
set encoding=utf-8
set foldcolumn=0
set formatoptions-=cro
set hidden
set hlsearch
set incsearch
set ignorecase
set smartcase
set linebreak
set number relativenumber
set paste
set ruler
set scroll=1
set spell
set splitbelow
set splitright
set thesaurus+="$META_HOME/config/mthesaur.txt" 
set viminfo=%,<800,'10,/50,:100,h,f1,n~/.vim/cache/viminfo
set virtualedit=block
set wildmenu

set smartindent
set autoindent
```

### Expected behaviour

unexpected:
![screenshot_2023-07-24_12-29-53](https://github.com/vim/vim/assets/45409/5d6eb678-5b1e-4be4-a6d0-948c1c1f3dd7)

expected:
![screenshot_2023-07-24_12-30-16](https://github.com/vim/vim/assets/45409/d6821e18-d0dd-47a8-964a-e5c7a6972a9c)

 
 Note that to copy the expected text I had to make my terminal larger while in reality the text would be slightly different if the wrapping width was correct.

### Version of Vim

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun 22 2023 04:08:04) Included patches: 1-3995, 4563, 4646, 4774, 4895, 4899, 4901, 4919

### Environment

linux, tmux, xterm-256color, bash

**Comment by chrisbra** [comment]
I tried to reproduce but for me [manpager.vim](https://github.com/vim/vim/blob/4c0089d696b8d1d5dc40568f25ea5738fa5bbffb/runtime/plugin/manpager.vim#L27)  already disables the 'number' column.

So please try to see if this is still a problem with an updated vim.

**Comment by nkh** [comment]
@chrisbra thank you for looking into it, I think I may have explained my case in a confusing way; I want the line numbers to be there, or at least till I decide I don't want the.

using a newer version wouldn't fix my problem I believe.

I can't find manpager.vim om my machine, does it get "built in" and how can I override it? I can have my own that I can hack on. Is it possible to have a separate manpager.vim?

To give some more background, I get the manpage with line numbers even if manpager.vim computes wrapping without. I ran a try where I set MANPAGER="vim -c 'set noline' -c 'set relativenumber!' ..." , the output is then fine but as soon as I use a plugin to search, the line numbers appear again.

I see two difficulties here:
- relativenumber can't be set, it's toggled, and if set on it's own it it ignores set number
- when the buffer is reloaded, it seems that the vimrc  values for number and relativenumber are also "re-loaded"

I'm happy to make a short video to show the problem if I am not clear enough.

**Comment by chrisbra** [comment]
I don't have a good answer. The line numbering takes away a couple of columns for, well, displaying the number column. You could possibly reformat the manpage, but not sure how well this will work.  Most likely it will mess it up, honestly, I don't think this is worth it 🤷 just for the number column.

> I can't find manpager.vim om my machine, does it get "built in" and how can I override it? I can have my own that I can hack on. Is it possible to have a separate manpager.vim?

It's included with your Vim installation. From within Vim, check `:echo $VIMRUNTIME` from that path, you should find it by appending `plugin/manpager.vim` to it. You can also use your own version, in that case simply copy it to your `~/.vim/plugin/manpager.vim` (create non-existing directories).

> the output is then fine but as soon as I use a plugin to search, the line numbers appear again.

I don't understand this part. The number column shouldn't magically appear. Try `:verbose set nu?` to find out where it was last enabled.

> relativenumber can't be set, it's toggled, and if set on it's own it it ignores set number

You can enable both options, `:set number relativenumber` See `:h number_relativenumber`.

> when the buffer is reloaded, it seems that the vimrc values for number and relativenumber are also "re-loaded"

how is this reloaded?

**Comment by chrisbra** [comment]
as mentioned, please use `:verbose set nu?` to find out, where it was last set.

> I also notice that the manpage wrapping is not dynamic, other text would re-wrap if the size of the terminal change, the manpage rendering is static.

Not sure what you mean here. But note that the manpage is basically copied into a new vim scratch buffer. There shouldn't happen any on the fly dynamic wrapping.

Note, I think you have more or less usage questions, that are more suitable on vi.stackexchange.com or the vim-use ml. I cannot provide individual support here, the existing number of tickets is barely manageable for us.

**Comment by nkh** [comment]
I understand that this is a low priority problem but you've put me on some tracks and I will work on my own viewer an report with a patch if it's anything worth sharing.

:verbose set nu? did help but :verbose ser relative? pointed to a changed in an augroup I have defined.
