### ISSUE TITLE
Wrong language

### ISSUE THREAD

**Issue by th** [vim/vim#12716]
### Steps to reproduce

1. Download gvim_9.0.1677_x64_signed.exe from www.vim.org
2. Install with everything left at default settings
3. Open gVim
4. See foreign language: "Fitxer", "Edita", "Eines".
 
![grafik](https://github.com/vim/vim/assets/153996/96993a62-5d0b-47da-8224-b29deee138cb)

### Expected behaviour

English or German language.

### Version of Vim

9.0.1677

### Environment

Windows 11

Windows display language in Settings is "English (United Kingdom)"

Preferred languages are English and German.

Country/Region is Germany.

**Comment by th** [comment]
Also happening with Vim 9.0.0

**Comment by k-takata** [comment]
What does `:lang` show?

**Comment by th** [comment]
Current language: "LC_COLLATE=German_Germany.1252;"

LC_CTYPE, LC_MONETARY, LC_NUMERIC and LC_TIME with the same value.

**Comment by k-takata** [comment]
Does it occur when you execute gvim with the `--clean` option?

**Comment by th** [comment]
Yes, also Catalan language.

**Comment by chrisbra** [comment]
hm, I cannot reproduce this

**Comment by ant0sha** [comment]
may be you have some environment variable defined ?

For example, if in dos prompt (my gvim is in current folder, modify as appropriate):

```
   set LANG=ca_ES
   .\gvim.exe --clean
```

then menu are shown in Catalan for me as well. Check your environment variables, pay attention to anything like *LANG* or LC* may be this is the reason?

**Comment by ant0sha** [comment]
And also check in gvim following:

```
echo v:lang
```

In case of my experiment with env.var set output differs from what :lang command shows

**Comment by th** [comment]
Apologies for not replying earlier. I had to move to another PC for unrelated reasons and cannot reproduce anymore. Since I cannot, we might just as well close the issue, unless someone else sees similar problems.

Thank you!
