### ISSUE TITLE
get back into browser window after closing a file opened via the vim browser

### ISSUE THREAD

**Issue by dulhaver** [vim/vim#12710]
vim is able to open directories (and then browse in them). This is great!

```
vim ./roles/webservices/tasks/
```
```
" ============================================================================
" Netrw Directory Listing                                        (netrw v156)
"   /home/gwagner/repos/automation_postgres/roles/webservices/tasks
"   Sorted by      name
"   Sort sequence: [\/]$,\<core\%(\.\d\+\)\=\>,\.h$,\.c$,\.cpp$,\~\=\*$,*,\.o$,\.obj$,\.info$,\.swp$,\.bak$,\~$
"   Quick Help: <F1>:help  -:go up dir  D:delete  R:rename  s:sort-by  x:special
" ==============================================================================
../
./
download_file.yml
main.yml
post_data.yml
post_du.yml
```
When you open/edit a file through this and then close it (`:wq`, `:q`) you are thrown back into the initial bash window at the starting point though.

**Describe the solution you'd like**
There should be a way to exit a file and land back into the browser window where you started vim in (`/roles/webservices/tasks/
` in my example`) additionally. As far as I understand the matter this is not possible yet.

**Comment by vrms** [comment]
`:Explore` seems to do this.
