### ISSUE TITLE
Support .sbt syntax highlighting

### ISSUE THREAD

**Issue by joeky888** [vim/vim#1271]
Which can be found here [https://github.com/derekwyatt/vim-sbt/blob/master/syntax/sbt.vim](https://github.com/derekwyatt/vim-sbt/blob/master/syntax/sbt.vim)

see also #995

**Comment by brammool** [comment]
Please ask the author to send the file to me for inclusion in the distribution.
That takes care of copyright issues.

**Comment by joeky888** [comment]
He did not reply.
