### ISSUE TITLE
Reuse existing tab or create new one after :make

### ISSUE THREAD

**Issue by radlyeel** [vim/vim#12724]
This may be a PBCAK,; if so, please explain how I can get the desired effect.

In my C/C++ development I use multiple tabs and the :make command A LOT.  When I get a complier error and press Enter to fix the first error, Vim opens the file with that error in the tab that I was using when I ran :make, even if that tab was open on another file and another tab is open on the file in question, leaving me with two tabs open on the same file and one file no longer visible (yes, I can get it back with :buffer).  In a more perfect world, Vim would see if the file were already open and switch to that tab instead.

Since I sometimes have multiple errors in a file, I switch to the problem file's tab before running :make.  But often that's inconvenient, and always suboptimal.

**Comment by yegappan** [comment]
This is already supported. You can set the `switchbuf` option to `usetab` to achieve this.  For more information about this option, refer to the [help](https://vimhelp.org/options.txt.html#%27switchbuf%27).

**Comment by chrisbra** [comment]
closing then.
