### ISSUE TITLE
Vim's future

### ISSUE THREAD

**Issue by spinets** [vim/vim#12728]
Given the [tragic news](https://groups.google.com/g/vim_announce/c/tWahca9zkt4) about @brammool, is there anyone here with the commit access to the repository?

**Comment by pistasjis** [comment]
There are two others in the Vim organization, they probably have commit access

**Comment by nyngwang** [comment]
Now who can manifest the quality of Vim?

**Comment by ebits21** [comment]
I sincerely hope the 'benevolent dictator' model is revised and vim re-organizes its development.

RIP Bram.

**Comment by FHU-yezi** [comment]
If he already set the successor feature in GitHub, someone he chosed can move this repo to he/she's account or make it public archived.

About this: https://docs.github.com/en/enterprise-cloud@latest/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/maintaining-ownership-continuity-of-your-personal-accounts-repositories

**Comment by xaizek** [comment]
Hope Vim's future will be no less impactful on IT sphere than its past.  Vim has some great co-maintainers, so I don't think it's too much to expect.

**Comment by wbpayne22902** [comment]
I imagine that the two others who are in the vim organization will step up and things will be more or less the same after a period of grieving over Bram's loss.  I was so sad to hear of Bram's passing myself after having used Vim myself for years, he will be sorely missed, that is certain.  RIP Bram, I'm sure you are programming something amazing in the afterlife.

**Comment by tonymec** [comment]
> Given the [tragic news](https://groups.google.com/g/vim_announce/c/tWahca9zkt4) about @brammool, is there anyone here with the commit access to the repository?

I don't know, but it can certainly be arranged; and in any case, if nothing else avails, the "master" repository can be moved to http://hg.256bit.org/vim i.e. the Mercurial clone maintained by @chrisbra which is already up to patchlevel 9.0.1677. The next patch exists, but only AFAIK as an email version: it can be brought in without too much hassle. For the rest, a solution shall be found, $DEITY willing.

**Comment by mikl** [comment]
I’m sure it’ll work out, but it might take a little time for everything to get settled. Have a little patience.

**Comment by Dawei-Simayi** [comment]
And is there something that we should consider? With the older generation contributor older, should we let the younger generation contributor participate in maintaining the open source repo?

**Comment by Dawei-Simayi** [comment]
And is there something that we should consider? With the older generation contributor getting older, should we let the younger generation contributor participate in maintaining the open source repo?

**Comment by Shane-XB-Qian** [comment]
this is NOT the good timing to discuss this, please show your respect!
