### ISSUE TITLE
`-expansion always errors

### ISSUE THREAD

**Issue by monkoose** [vim/vim#12721]
### Steps to reproduce

1. `vim --clean`
2.  ``:args `ls` `` or any other command in backticks results in `E79: Cannot expand wildcards`

### Expected behaviour

Backtick expansion should work as described in ``:h `-expansion ``

### Version of Vim

9.0 with a patch 1-1677

### Environment

TERM: st (tested in xterm also)
SHELL: fish (tested in bash also)

**Comment by wrecklass** [comment]
Which OS(es) did you test this on? I'm guessing st was on Arch Linux.
I just tested and this worked on Windows 11 (Cygwin and PowerShell). And on Ubuntu 22.04. Vim 1677. I specifically built vim from source on Ubuntu and Cygwin. Windows is from the released download. 

Except for PowerShell on Windows, shell was bash.

Also, what was the error code/message?

**Comment by monkoose** [comment]
I'm on Arch Linux.
Tested in neovim and it works as expected.

> Also, what was the error code/message?

It is already in main post.

**Comment by chrisbra** [comment]
I cannot reproduce. Please use `:set verbose=5` and check what shell command vim executes. Then please verify you have correct shell settings.

**Comment by monkoose** [comment]
@chrisbra with verbose=5 it returns only 

```
Calling shell to execute: "(ls)>/tmp/v076GvC/4"
E79: Cannot expand wildcards
```

Is it any help?

**Comment by monkoose** [comment]
Yes, this expansion works correct with fish shell, but maybe there are some other issues I haven't face yet.

**Comment by brianhuster** [comment]
I think the reason is that Fish shell really doesn't support backtick expansion https://fishshell.com/docs/current/fish_for_bash_users.html#command-substitutions

So you can try running this is a terminal emulator running Bash shell
```sh
echo `ls`
echo $(ls)
```
Both of them work and print list of files

But when running those commands in Fish shell, only the latter (`echo $(ls)` work).
