### ISSUE TITLE
Should :wall report an error if there are unnamed buffers?

### ISSUE THREAD

**Issue by the42** [vim/vim#1272]
The documentation of :wall of Vim8 says:

    Write all changed buffers.  Buffers without a file
    name or which are readonly are not written.

However, a :wall with a new buffer fails with an error message

    E141: No file name for buffer

Is this correct? If not I think this qualifies as a bug

**Comment by brammool** [comment]
Johann Höchtl wrote:

> The documentation of :wall of Vim8 says:
> 
>     Write all changed buffers.  Buffers without a file
>     name or which are readonly are not written.
> 
> However, a :wall with a new buffer fails with an error message
> 
>     E141: No file name for buffer
> 
> Is this correct? If not I think this qualifies as a bug

It is correct, the docs don't mention the error message but it indeed
means the buffer isn't written.

-- 
I started out with nothing, and I still have most of it.
                                -- Michael Davis -- "Tonight Show"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
