### ISSUE TITLE
Virtual text using text_wrap 'wrap' while "list" is enabled will not show wrapped lines correctly

### ISSUE THREAD

**Issue by BigPeet** [vim/vim#12725]
### Steps to reproduce

1. Save the following as test.vim:
 ```vim
 vim9script
:80vsplit
# A
# B 40 * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
# C
# D
set list

prop_type_add('test', {highlight: 'Error'})
prop_add(4, 0, {
  'text': ' > 40 * bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
  'type': 'test',
  'text_wrap': 'wrap',
})
 ```
2. Execute `vim --clean test.vim -S test.vim`
3. Move cursor to line 4 and move down (`4Gj`)

### Expected behaviour

The text+virtual text in line 4 is longer than 80 characters and should wrap to the next (visual) line. The cursor should be on line 5 (C).

I.e. it shoud look something like this (I've taken this screenshot with `nolist`):
![expected](https://github.com/vim/vim/assets/1740244/4dba8cac-e817-432e-a4cd-7744fbed25df)

The actual behavior looks like this:
![actual](https://github.com/vim/vim/assets/1740244/de6e7161-b311-4c7d-84c8-436edcabf47d)

1. The virtual text is obviously not wrapped.
2. If you step over this line with the cursor, the cursor seems to skip the following line (C) and seems to be on (D) instead. This is only visually, though. If you enter Insert mode, it will be on line 5, as expected.

### Version of Vim

9.0.1677

### Environment

OS: Linux Mint 21.2
Terminal: gnome-terminal 3.44
Value of $TERM: xterm-256color
Shell: bash 5.1.16

**Comment by BigPeet** [comment]
Might be related to #11959

**Comment by dylanahsmith** [comment]
I found the relevant condition in the code:

https://github.com/vim/vim/blob/ffc712780fb3ba3f028a1bd4241bf1692d5172fd/src/drawline.c#L4136-L4150

where `lcs_eol_one == -1` will be true after the end of line character has been added to the screen line.  So it seems like that is where the bug is and it is just a matter of figuring out what the code should be.
