### ISSUE TITLE
Kitty - Pressing enter prints `ˊ`

### ISSUE THREAD

**Issue by Sharkitty** [vim/vim#12731]
### Steps to reproduce

1. Open vim in kitty terminal (This only happens in kitty).
2. Use insert mode or press `:` to enter a command.
3. Press the enter key.
4. The `ˊ` should be printed.

This bug might be exclusive to French AZERTY keyboard layout.

### Expected behaviour

The enter key should make a new line in insert mode, or executed the command prompted by the user.

### Version of Vim

9.0.1632-2.1

### Environment

OS: OpenSUSE Tumbleweed
Terminal: kitty 0.29.2
$TERM: `xterm-kitty`
Shell: Fish, same behavior on Bash.
Keyboard layout: French AZERTY (Might be relevant to the issue).
My Vim is completely default.

I have also posted an issue about it on kitty git, and the maintainer indicated me that this must be an issue with how the Kitty Keyboard Protocol is implemented in Vim.
[Kitty issue #6527](https://github.com/kovidgoyal/kitty/issues/6527)

**Comment by dharmit009** [comment]
When I press enter it is switching from insert mode to escape mode. I turned off num lock after that it started to work fine.

**Comment by zeertzjq** [comment]
There may be a bug in the keyboard itself. Although the same thing should happen when pressing the keypad Enter key on a full keyboard.

**Comment by Sharkitty** [comment]
Greetings, for a bit of extra context on this issue, I also have another issue opened over on neovim with a different behaviour: [Neovim issue #24577](https://github.com/neovim/neovim/issues/24577), where a workaround has been found using a simple remap.

I haven't tested yet to do the same on regular vim, but I think this should be a good workaround on vim as well. I'll try to do that after work.

@zeertzjq Made me perform the same test in GVim, which resulted in the same behavior as neovim.

Since then I encounter yet another situation where that key cause issue, using one of kitty's default keybindings (`ctrl+shift+enter` to open a new tiled window), which was also solvable with a remap. All that leads me to think that as @zeertzjq suggests, a keyboard bug is the most likely cause, but I don't know how to fully confirm this.

**Comment by chrisbra** [comment]
okay, let me close it for now then. Thanks!

**Comment by Sharkitty** [comment]
Hello again, I can confirm that using a remap as a workaround. This is what I used in my `vimrc` in case anyone encounters the same issue:
```
nmap  <Enter>
vmap  <Enter>
imap  <Enter>
cmap  <Enter>
```
I thank everyone for their time. Positive thoughts for Bram, all Vim contributors and his loved ones.
