### ISSUE TITLE
I'm sad to hear the news.

### ISSUE THREAD

**Issue by gfsc59** [vim/vim#12730]
Moolenaar was a marvelous computer scientist who contributed immensely to the industry throughout his life, and ordinary people outside the industry indirectly benefited from Moolenaar.

It is very sad to learn of his death in his 60s. Wish him a blessed life in the next. I hope that the vim community can carry on his legacy and spirit, so that he can continue to live among us, and together we can make vim better and better.

But, I still feel sad.

---
Moolenaar是一位了不起的计算机科学家，一生对业界做出了巨大的贡献，业界外的普通人也间接受益于Moolenaar。

得知他60多岁就去世的消息，让人非常的难过。祝福他来生有福报。希望vim社区能继承他的遗志，发扬他的精神，让他继续活在我们之间，一起让vim变得越来越好。

但，我还是感到很悲伤。

---
ムールネールは生涯を通じてこの業界に多大な貢献をした素晴らしいコンピューター科学者であり、業界外の一般人も間接的にムールネールの恩恵を受けていた。

彼が60代で亡くなったことを知り、とても悲しい。 来世での彼の人生が祝福されたものであることを祈ります。 ヴィーム・コミュニティが彼の遺産と精神を受け継ぎ、彼が私たちの中で生き続け、共にヴィームをより良いものにしていけることを願っています。

でも、やっぱり寂しい。

---
Moolenaar war ein hervorragender Informatiker, der sein Leben lang einen enormen Beitrag zur Industrie geleistet hat, und auch der einfache Mann außerhalb der Industrie hat indirekt von Moolenaar profitiert.

Es ist sehr traurig zu erfahren, dass er im Alter von 60 Jahren verstorben ist. Ich wünsche ihm ein gesegnetes Leben im nächsten Leben. Ich hoffe, dass die Vim-Gemeinschaft sein Erbe und seinen Geist weiterführen kann, so dass er weiterhin unter uns leben kann und wir gemeinsam Vim besser und besser machen können.

Aber ich bin immer noch traurig.

---
Moolenaar était un merveilleux informaticien qui a apporté une immense contribution à l'industrie tout au long de sa vie et l'homme de la rue, en dehors de l'industrie, a bénéficié indirectement de Moolenaar.

Il est très triste d'apprendre qu'il est décédé à l'âge de 60 ans. Je lui souhaite une vie bénie dans l'au-delà. J'espère que la communauté vim pourra perpétuer son héritage et son esprit, afin qu'il puisse continuer à vivre parmi nous et qu'ensemble, nous puissions rendre vim de plus en plus performant.

Mais je me sens toujours triste.

---
Муленаар был замечательным ученым-компьютерщиком, который на протяжении всей своей жизни вносил огромный вклад в развитие отрасли, а обычные люди, не связанные с отраслью, получали от него косвенную пользу.

Очень печально узнать, что он ушел из жизни в возрасте 60 лет. Я желаю ему благословенной жизни в следующей жизни. Я надеюсь, что сообщество vim сможет продолжить его наследие и дух, чтобы он продолжал жить среди нас, и вместе мы могли бы сделать vim все лучше и лучше.

Но мне все равно грустно.

**Comment by pheiduck** [comment]
Er war ein sehr netter Open source maintainer es war immer ein Vergnügen PRs zu versenden ebenfalls immer die schnelle Rückmeldung seiner Seits und der Community.

**Comment by minexo79** [comment]
RIP

**Comment by charleschetty** [comment]
RIP

**Comment by GyouzaRu** [comment]
RIP

**Comment by surmish** [comment]
A terrible loss of a great legend. Thank you for everything, Bram. 🙏

**Comment by vim-ml** [comment]
I'm not sure what to say, or think, or feel. It's a great loss for Vim, the
community, and the people who, directly or indirectly, use Vim.

He will be missed by his family, friends, colleagues, and us.

I hope the best for the future, and that we keep his legacy alive, and in
good shape.

Christ van Willegen

**Comment by Tolgon** [comment]
Rest in Peace Bram. Your hard work has helped so many developers find new ways to interact with their work. And your commitment on helping Uganda has affected so many lives for the better.

We lost a good one today.

**Comment by ssxwcz** [comment]
RIP

**Comment by tomiis4** [comment]
RIP

**Comment by soryu-ryouji** [comment]
It is so sad......

**Comment by xzl01** [comment]
RIP

**Comment by 0Delta** [comment]
I'm sad too

I feel the need to add some condolences to dear Bram somewhere in the Vim docs and code.

**Comment by Acpear** [comment]
I was saddened to hear of his passing.VIM is one of the most commonly used text editors in non-graphical interfaces, and its birth, updates and development have advanced the entire field of computing. With deep gratitude, I will always remember the great developer: Moolenaar.

**Comment by ruppde** [comment]
Not just a great developer but also redirecting money to help children in Uganda since ages:

https://www.vim.org/sponsor/index.php

**Comment by EarthMessenger** [comment]
:wq

RIP Bram. Thank you for your awesome VIM.

**Comment by drkknigt** [comment]
"The song is ended, but the melody lingers on." 
Thank you bram. RIP king...

**Comment by AlexVagrant** [comment]
RIP

**Comment by hszzz** [comment]
R.I.P

**Comment by yzwdroid** [comment]
R.I.P

**Comment by rovo98** [comment]
R.I.P

**Comment by ithewei** [comment]
Thank you，Bram Moolenaar.
R.I.P

**Comment by rwali1** [comment]
R.I.P

**Comment by koron** [comment]
Very sad. I am proud to have been associated with you and your Vim. Bram, please rest in peace.

---

とても悲しいよ。あなたと、あなたのVimに関われたことは私の誇りだよ。Bram、どうか安らかに。

**Comment by StudentWeis** [comment]
R.I.P.

**Comment by Caesar6666666** [comment]
vim helps me a lot. thank you Bram.
R.I.P

**Comment by MoetaYuko** [comment]
R.I.P.

**Comment by ru-wang** [comment]
RIP

**Comment by noscript** [comment]
R.I.P. Bram

**Comment by ColonelBucket8** [comment]
Thank you Bram 
RIP

**Comment by scarlehoff** [comment]
RIP Bram, and thanks.

**Comment by NOVBobLee** [comment]
Thank you, Bram

**Comment by idm1try** [comment]
:q RIP Thank you, Bram for your amazing work

**Comment by vimpostor** [comment]
RIP Bram, it has always been a pleasant experience when contributing patches to vim. Hearing this sad news truly shocked me. :(

**Comment by Esentries** [comment]
RIP Bram. You will forever be in our hearts.

**Comment by motorailgun** [comment]
Let me leave my condolences here. RIP Bram, your software has saved me for countless times.

**Comment by salewski** [comment]
RIP @brammool, and thank you for vim. My condolences to your family and loved ones.

**Comment by Username-Adrian** [comment]
Thank you，Bram Moolenaar.
R.I.P.
:wq

**Comment by rootex-** [comment]
RIP Bram, thank you for improving our lives with your amazing work of art 🙌

**Comment by JimmyHuang454** [comment]
Thank you Bram.
R.I.P.

**Comment by Kiotlin** [comment]
Thank you Bram
RIP

**Comment by ndavd** [comment]
RIP

**Comment by CKboss** [comment]
R.I.P.
:wq

**Comment by NobootRecord** [comment]
It is very sad to hear these news. I have opened this so wonderful instrument for myself and started practicing it in coding about a year ago - and I really enjoyed it.

**Bram Moolenaar, thank you for your work. Rest in peace.**
*The world has lost one of his most genius programmers. My condolences to Bram's relatives and friends.*

```
:sav /dev/heart
:q
```

**Comment by nctuming** [comment]
Bram:

I was using Vim until 5 hours ago :(

You're a LEGEND :)

Thank you!

**Comment by TortitasT** [comment]
Thank you Bram. RIP

**Comment by renxzen** [comment]
Good bye Bram. Thank you for everything.

**Comment by RestorerZ** [comment]
Покойся с миром!
Светлая память!

**Comment by stsewd** [comment]
Gracias por todo Bram, descansa en paz, :wq

**Comment by pesarkhobeee** [comment]
ازت ممنونیم بخاطر نگاهت به زندگی و ارزشی که خلق کردی، روحت قرین آرامش.

**Comment by Eclips4** [comment]
Thank you for your hard work.
RIP.

**Comment by Melandel** [comment]
Thank you for your impact in my daily craft.
RIP.

**Comment by alekseishaklov** [comment]
RIP. Thanks for everything 😢

**Comment by wbpayne22902** [comment]
RIP Bram, you will be missed around here.  Thanks for creating Vim and I'm sure the community will do its utmost to carry on your vision.

**Comment by Tohrusky** [comment]
RIP, Bram
:wq

**Comment by guiltiest-gear** [comment]
RIP, Bram
You'll be surely missed
Goodnight sweet prince
:wq

**Comment by bitigchi** [comment]
Işıklar içinde uyu. Özleyeceğiz.
Rest in peace. You'll be missed.

**Comment by tcx4c70** [comment]
R.I.P.

**Comment by dawnaliens** [comment]
R.I.P

**Comment by tonymec** [comment]
May Bram rest in peace, and may Vim and ICCF/Kibaale both find someone to step into his footsteps — it won't be easy, but Bram wouldn't want all his life's work to go to nought between one toll of the bell and the next.

Sincere condolences,
Tony.

**Comment by xiangzhai** [comment]
RIP

**Comment by Nauxscript** [comment]
RIP

**Comment by AinzLimuru** [comment]
R.I.P

**Comment by qingshuizheng** [comment]
RIP, Bram. 
:wq

**Comment by larrasket** [comment]
RIP.

**Comment by butdraw** [comment]
Thank you for your great work!
R.I.P.

**Comment by unrooot** [comment]
RIP

**Comment by qyl27** [comment]
Thank you, Bram,  
R.I.P  
`:wq`

**Comment by lwd-temp** [comment]
Sorry to hear that.
RIP.

**Comment by astroshot** [comment]
R.I.P
Thank you, Bram.

**Comment by forealmy** [comment]
谢谢你，Bram。
:wq

**Comment by jku1995** [comment]
RIP Bram.

**Comment by oneroyalace** [comment]
RIP brother

**Comment by NewComer00** [comment]
“编辑器之神”的创造者回到了神的身边。
Thank you, Bram.

R.I.P.

**Comment by dierbei** [comment]
Thank you for your contribution to the progress of the world.

**Comment by leo-fp** [comment]
Thank you, Bram. R.I.P.

**Comment by aKuoHsing** [comment]
R.I.P.
:wq

**Comment by kaiwu** [comment]
RIP，老大再见了，感谢所有，一路顺风。

**Comment by CrackTC** [comment]
RIP, Bram

**Comment by yamsu** [comment]
Thank you for all your work Bram, RIP!

**Comment by zuxfoucault** [comment]
rip

**Comment by mlmdflr** [comment]
rip

**Comment by coder109** [comment]
RIP

**Comment by yuekcc** [comment]
R.I.P

**Comment by zsh2401** [comment]
rip
:wq

**Comment by yuanronghhh** [comment]
RIP.

**Comment by pudding0503** [comment]
R.I.P
:wq

**Comment by Pmaru-top** [comment]
RIP

**Comment by Rinoahu** [comment]
R.I.P, my hero

**Comment by jingyuexing** [comment]
R.I.P my hero,
maybe it's back to God to write vim for him

**Comment by wangdong** [comment]
R.I.P.
:x

**Comment by Leiyi548** [comment]
RIP

**Comment by RRadon086** [comment]
R.I.P.
Vim is my first text editor when learning C.

**Comment by rxwen** [comment]
R.I.P.

**Comment by fakecore** [comment]
R.I.P.
:(

**Comment by alongw** [comment]
I may not be able to leave vim for the rest of my life, I have to use it
Thank you，Bram Moolenaar.
R.I.P

**Comment by SquakinKakas** [comment]
RIP :(

**Comment by grepsuzette** [comment]
Rest in peace, blessed One.
I feel very sad, but your legacy will stay on and on.
Bram Moolenaar lives forever in our hearts.

**Comment by Antidington** [comment]
R.I.P.

**Comment by Jackiexiao** [comment]
R.I.P thx for developing vim, I use vim every day, thank you! Bram Moolenaar!

**Comment by binarycode01** [comment]
R.I.P

**Comment by ValKmjolnir** [comment]
R.I.P. Thank you for creating vim Moolenaar!

**Comment by Molmin** [comment]
RIP

**Comment by jiaoshijie** [comment]
RIP

**Comment by HCY-ASLEEP** [comment]
RIP

**Comment by mike820324** [comment]
RIP

**Comment by Slijeff** [comment]
RIP

**Comment by Dawei-Simayi** [comment]
R.I.P

**Comment by juouyang** [comment]
R.I.P

**Comment by marklai1998** [comment]
RIP

**Comment by zalois** [comment]
RIP

**Comment by Mr-LLLLL** [comment]
R.I.P
thank Bram for VIM

**Comment by LinHeMa** [comment]
RIP Bram
Thanks for what you built and gave me so much fun.

**Comment by warr99** [comment]
R.I.P
thank Bram for VIM

**Comment by pilgrimlyieu** [comment]
R.I.P Bram

**Comment by nightravem** [comment]
R.I.P

**Comment by iTruth** [comment]
R.I.P

**Comment by Errant404** [comment]
R.I.P

**Comment by hexuben** [comment]
……I'm so sad. Stand in silent tribute to him.

**Comment by LittleLittleCloud** [comment]
R.I.P

**Comment by cubxxw** [comment]
R.I.P 😭

**Comment by suckerSlayer** [comment]
RIP Thanks

**Comment by fwx5618177** [comment]
R.I.P

Sven Guckes is waitting for you. We would love all in Vim all the time.

**Comment by xindoo** [comment]
R.I.P.

**Comment by zxc7528064** [comment]
R.I.P .

**Comment by WildfootW** [comment]
:wpa!

**Comment by neilwangweili** [comment]
R.I.P

**Comment by tonghs** [comment]
他将永远活在我们的肌肉记忆里。

**Comment by ProbiusOfficial** [comment]
R.I.P

**Comment by linzhanyu** [comment]
R.I.P.

**Comment by nullchilly** [comment]
o7

**Comment by TeknosQuet** [comment]
:(

**Comment by javareact** [comment]
R.I.P

**Comment by sawyer523** [comment]
R.I.P

**Comment by kmvan** [comment]
My first text editor on Linux.
Thank you your work, Moolenaar.

**Comment by khatibomar** [comment]
RIP

**Comment by UPON-2021** [comment]
RIP

**Comment by GaoNeng-wWw** [comment]
🕯

**Comment by zzhirong** [comment]
Ever since I learned Vim, it has permeated every aspect of my life and work, from browsing the web to writing code in Vim/IDEs, taking notes, and operating my computer. Learning it has significantly enhanced my efficiency. Thank you, Bram, for creating such an exceptional program. Rest in peace.

**Comment by ant0sha** [comment]
Thanks for all, Bram
R.I.P.
Светлая память
:wqa

**Comment by llxlr** [comment]
R.I.P

**Comment by 454270186** [comment]
R.I.P 🫡

**Comment by HzRr** [comment]
R.I.P

**Comment by Boshugege** [comment]
R.I.P
一路走好。

**Comment by skanehira** [comment]
R.I.P

**Comment by LeeChSien** [comment]
RIP

**Comment by lunrs** [comment]
R.I.P

**Comment by OctHe** [comment]
R.I.P.

**Comment by Josephbhr** [comment]
R.I.P.

**Comment by Canace22** [comment]
R.I.P

**Comment by wangrunlin** [comment]
R.I.P.

**Comment by amixsty** [comment]
Rest in peace...

**Comment by epheien** [comment]
R.I.P.

**Comment by TyrantLucifer** [comment]
R.I.P.

**Comment by LiuYi98** [comment]
I'm so sorry to hear your passing, thanks for all you have done to make this world better, R.I.P. Bram.

**Comment by blackheaven** [comment]
I'm so sad and shocked he passed away, using ViM from my teenage years, he played a role on my development style which now is my work and even more.

I'm grateful for his contributions to the world and the influence it has on me.

R.I.P.

**Comment by infinitewhileloop** [comment]
R.I.P.

**Comment by aidancz** [comment]
R.I.P.

**Comment by s12321** [comment]
R.I.P.

**Comment by JuniperSling** [comment]
Thank You Bram

**Comment by jakio6** [comment]
R.I.P

**Comment by RainStar7981** [comment]
RIP

**Comment by kvzl** [comment]
R.I.P.

**Comment by yizhilong28** [comment]
RIP

**Comment by dsyq** [comment]
R.I.P

Esc

:wq

**Comment by gitzhangzhao** [comment]
R.I.P

**Comment by 45230** [comment]
R.I.P
:wq

**Comment by drdh** [comment]
R.I.P
:wq

**Comment by vlada79** [comment]
Thank you for an amazing editor. R.I.P.

:wqa

**Comment by lcd047** [comment]
R.I.P

**Comment by k-takata** [comment]
I'm going to covert this to a discussion.
