### ISSUE TITLE
Shouldn't have taken the vax

### ISSUE THREAD

**Issue by mcg-anon** [vim/vim#12739]
This guy seriously thought that the vaccine provides immunity.

![Screenshot_20230806_182914](https://github.com/vim/vim/assets/96922124/bba94287-c585-4933-8c10-393da597b4d1)

**Comment by deickhoff** [comment]
This is really disgusting. You don't have to agree on certain decisions people make but stay respectful. Besides that, your opinion on the VIM GitHub page is also irrelevant. Shame on you.

**Comment by damianeickhoff** [comment]
This is really disgusting. You don't have to agree on certain decisions people make but stay respectful. Besides that, your opinion on the VIM GitHub page is also irrelevant. Shame on you.

**Comment by mcg-anon** [comment]
> This is really disgusting. You don't have to agree on certain decisions people make but stay respectful. Besides that, your opinion on the VIM GitHub page is also irrelevant. Shame on you.

If only certain people would have stayed respectful and accepted the decisions of others who did not take the vax and who did not believe that the shot provides immunity (and as it later turned out, were right).
