### ISSUE TITLE
Undercurl not working anywhere

### ISSUE THREAD

**Issue by simonmandlik** [vim/vim#12744]
### Steps to reproduce

I cannot get undercurl to work. I tested all of the "mainstream" terminal emulators — `iTerm2`, `kitty`, and `alacritty`, with `zsh`. Undercurl works in all terminals, but not in `vim`. 

I tested this by firing up vim and checking the `SpellBad` highlight group:

1. `vim`
2. `:hi SpellBad`

iTerm2 shell:
<img width="370" alt="image" src="https://github.com/neovim/neovim/assets/16707112/a4fa396e-aa84-4d62-a4bf-4f3b9d26adae">

iTerm2 `vim`:
<img width="659" alt="image" src="https://github.com/vim/vim/assets/16707112/be45328e-78fa-4d97-a7f6-c97f0ad22c70">

kitty shell:
<img width="507" alt="image" src="https://github.com/neovim/neovim/assets/16707112/45dcf549-acc0-46e3-bcec-361a485198b3">

kitty `vim`:
<img width="945" alt="image" src="https://github.com/vim/vim/assets/16707112/f4d53261-a113-4f3d-bc3e-149098f551b1">

alacrity shell:
<img width="470" alt="image" src="https://github.com/neovim/neovim/assets/16707112/44fcf452-567f-4b3f-b579-05c66988de34">

alacritty `vim`:
<img width="872" alt="image" src="https://github.com/vim/vim/assets/16707112/cde9f3c1-bd21-455e-a4da-308342d430dc">

### Expected behaviour

Undercurl line showing up

### Version of Vim

9.0.1424

### Environment

MacOS 13.4.1
iterm2
xterm-256color
zsh

**Comment by simonmandlik** [comment]
Thank you, that helped!

**Comment by sukima** [comment]
```vim
let &t_Cs=“\<Esc>[4:3m”
```

Thank you, this fixed it for me as well. Is this something we should put in our **global** vimrc? As in this is a universal setting all terminals should have? Or is this a setting only affecting specific terminals and should only be enabled on a per machine basis?
