### ISSUE TITLE
An unexpected fold is started when "<2" is specified in "foldexpr"

### ISSUE THREAD

**Issue by emonkak** [vim/vim#12768]
### Steps to reproduce

In `'foldexpr'`, "<2" indicates the end of a level 2 fold. However, if no fold has been started yet, it starts a level 1 fold instead.

This behavior is unexpected and looks like a bug. But, fixing it may break the existing `'foldexpr'` settings.

This issue can be reproduced by sourcing the following script using `:source:`.

```
new
setlocal foldmethod=expr
let &l:foldexpr = 'v:lnum == 1 ? "<2" : "="'
call setline(1, range(1, 10))
echo map(range(1, 10)), 'foldlevel(v:val)')
```

Expected: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Actual: [0, 1, 1, 1, 1, 1, 1, 1, 1, 1]

### Expected behaviour

Never start a new fold when ending a fold with "<1" or "<2".

I found the code that is causing this issue. Surprisingly, this code has not been modified since 19 years ago. I believe that the following change will fix this issue:

```diff
--- a/src/fold.c
+++ b/src/fold.c
@@ -3362,7 +3362,7 @@ foldlevelExpr(fline_T *flp)
          break;

    // "<1", "<2", .. : end a fold with a certain level
-   case '<': flp->lvl_next = n - 1;
+   case '<': flp->lvl_next = MIN(flp->lvl, n - 1);
          flp->end = n;
          break;
```

https://github.com/vim/vim/blob/81b8bf5b4a33552c610dc2ea743ac2698a16aef7/src/fold.c#L3365

### Version of Vim

9.0.1695

### Environment

OS: Gentoo Linux
Terminal: alacritty
$TERM: xterm-256color
shell: zsh

**Comment by chrisbra** [comment]
can you please create a PR with a test for it?
