### ISSUE TITLE
bug of 'virtcol2col'

### ISSUE THREAD

**Issue by hyaray** [vim/vim#12786]
### Steps to reproduce

vim text is 'a✅✅✅'
use cmd `echom printf('vc:%d c:%d vc2c:%d', virtcol('.'),col('.'),virtcol2col(0,line('.'),virtcol('.')))` to show info with cursor at `1-4`
result is:
```vim
vc:1 c:1 vc2c:1
vc:3 c:2 vc2c:4
vc:5 c:5 vc2c:7
vc:7 c:8 vc2c:10
```

### Expected behaviour

`vc2c` should = `c`
may use code below to fix result
```vim
let vcs = virtcol('.', 1)
let vc2c = virtcol2col(0, line('.'), vcs)
if (vcs[0] != vcs[1])
    let vc2c -= 2
endif
```
### Version of Vim

9.0.1607

### Environment

window 10

**Comment by chrisbra** [comment]
hm, seems to be a general problem with multibyte characters. For `ä`, it is off by 1.

**Comment by chrisbra** [comment]
ideas @yegappan ?

**Comment by chrisbra** [comment]
could it be, `virtcol2col()` returns the end of the byte column for the character under the cursor? So one would need to substract the bytelen of the character -1 (so only for multi-byte characters) from `virtcol2col()`?

**Comment by hyaray** [comment]
`col()` return the first col, so `virtcol2col` should be consistently.

**Comment by yegappan** [comment]
>
> could it be, `virtcol2col()` returns the end of the byte column for the character under the cursor? 
> So one would need to subtract the bytelen of the character -1 (so only for multi-byte characters) from `virtcol2col()`?
>

Yes.  The virtcol2col() function returns the last byte index of a multibyte character.
The col() function returns the first byte index of a multibyte character.
We should change virtcol2col() to be consistent with the col() function.
