### ISSUE TITLE
Upstreaming syntax files

### ISSUE THREAD

**Issue by peterhoeg** [vim/vim#12806]
I have a [repository](https://github.com/peterhoeg/vim-qml/) with syntax files for QML and was wondering if you are interested in getting it merged into vim upstream?

I no longer use vim, but it looks like quite a few people are using the plugin, so for the benefit of the project, I think it would make sense to get it included properly.

I must admit, I'm not sure how to do this while minimizing the impact for people using the plugin, so if anyone could send a link to somewhere this is described, I'll gladly do up the PR with the required changes to get this going.

**Comment by yegappan** [comment]
Can you open a PR with the runtime files for QML?  You also need to update the src/testdir/test_filetype.vim file with a test for the new filetype.

**Comment by dkearns** [comment]
This can be closed.  The files were added in https://github.com/vim/vim/commit/bedc69f9d67b117ab05aa735c701cd3899d1ae2d
