### ISSUE TITLE
Docs are unclear about when buffer-local option values are cleared (deletion vs. wipeout)

### ISSUE THREAD

**Issue by ddickstein** [vim/vim#12809]
### Steps to reproduce

The description of `:bdelete` says:
https://github.com/vim/vim/blob/5b0889b8bf25b0793b1949ec965c94b623900aba/runtime/doc/windows.txt#L1200-L1203

The description of `:bwipeout` says:
https://github.com/vim/vim/blob/5b0889b8bf25b0793b1949ec965c94b623900aba/runtime/doc/windows.txt#L1226-L1228

Both of these mention clearing option settings. So - when are option settings actually cleared - on `:bdelete`, or only on `:bwipeout` when the buffer is "really" deleted? Does it depend on the setting?

### Expected behaviour

Clearer documentation for what information is cleared on `bdelete` vs `bwipeout`.

### Version of Vim

9.0.1712

**Comment by yegappan** [comment]
The buffer-local options are cleared for both the ":bdelete" and the ":bwipeout" commands.  Note that you can wipeout a buffer using the ":bwipeout" command without first deleting the buffer using the ":bdelete" command.  You can also use the ":bdelete" command to delete a buffer without wiping out the buffer.  In both cases, the buffer-local options will be cleared.

Refer to the following code:
https://github.com/vim/vim/blob/master/src/buffer.c#L940
https://github.com/vim/vim/blob/master/src/buffer.c#L786
https://github.com/vim/vim/blob/master/src/buffer.c#L778

**Comment by chrisbra** [comment]
so this can be closed?

**Comment by chrisbra** [comment]
but both commands are clearing out buffer-local options. Isn't that clear? Do you have a doc improvement?

**Comment by ddickstein** [comment]
This `:bwipeout` text is contrasting it with what `:bdelete` does. It's "like `:bdelete`", but also does <examples>. So it's misleading to include something in that list that `:bdelete` also does. As I said above, a different example should be chosen, e.g., buffer-local autocmds being cleared.

**Comment by chrisbra** [comment]
I don't read that as contrasting:

https://github.com/vim/vim/blob/544b209a2d4b10e0a4874c925036def30d33d708/runtime/doc/windows.txt#L1226-L1229

_Like *bdelete*, but really delete the buffer._ so everything is lost. And then come examples of what all will be lost (but that does not relate or contrast to what *:bd* does but are just examples of what all will be lost when using *bwipeout*). Yes, *bdelete* may also delete part of that, but that is not the point here.

**Comment by chrisbra** [comment]
FWIW: I wrote the previous comment, *after* I started looking at the help file and was trying to clarify the docs as part of #12790 

But I don't think this is required. So let me close this. Thanks.
