### ISSUE TITLE
Make BufDelete only fire in response to `bdelete` command (or `bwipeout`)

### ISSUE THREAD

**Issue by ddickstein** [vim/vim#12817]
Buffer deletion is an ambiguous concept in Vim. Most people think of deletion as "what happens when you `bdelete` a buffer," which is unloading, unlisting, and clearing some buffer-specific settings. The `BufDelete` event, by contrast, fires specifically when a buffer is unlisted - the buffer can still be present in a window when this happens. The documentation is clear about the current semantics - it does say that BufDelete means "Before deleting a buffer from the buffer list," and it's distinct from BufUnload. But I think what people probably want to be saying when they register events on BufDelete is "run this when `bdelete` happens," not "run this when the buffer is unlisted." I think the event should specifically be tied to this command, as well as run on `bwipeout` prior to BufWipeout.

**Comment by ddickstein** [comment]
And to support plugins that depend on the existing semantics, maybe create `BufUnlisted` that they can use instead.

**Comment by chrisbra** [comment]
I am not a big fan of changing the semantics for an autocommand that has been working like this for [25 years](https://github.com/vim/vim-history/commit/cdb313b5e89dc78e96efbaf1) and which also breaks backward-compatibility. So I am slightly negative to it.

**Comment by ddickstein** [comment]
I think in practice it won't be noticed. Specifically -- the only circumstance in which this would be noticed *and* people would be sad about the change (as opposed to them noticing broken behavior now working properly) is when the following are true:

1. A plugin is specifically interested in knowing when a buffer has been removed from the buffer list and does something interesting if the buffer is still valid when that happens.
2. A user (or that plugin) unlists a buffer that they do not otherwise delete, triggering that behavior. The user doing this themselves is I think quite unusual -- and if they do explicitly unlist a buffer it's not likely that they're doing that with the expectation of some plugin having special behavior around this.

So mayyybe some sort of buffer list management plugin that exists somewhere cares about this?

This stands in contrast to the likely hundreds of vim plugins that are currently actually have subtle bugs today because their authors didn't think deeply about what BufDelete means and took it at face value. This would be a fix to bring behavior in line with those expectations.

**Comment by chrisbra** [comment]
I am not going to change the existing behaviour.
