### ISSUE TITLE
Prompt buffer - Ctrl-Shift-W doesn't delete the word

### ISSUE THREAD

**Issue by stonebrakert6** [vim/vim#12815]
### Steps to reproduce

`:h prompt-buffer`. The documentation says
> The CTRL-W key can be used to start a window command, such as CTRL-W w to
switch to the next window.  This also works in Insert mode (**use Shift-CTRL-W
to delete a word**). When leaving the window Insert mode will be stopped.  When
coming back to the prompt window Insert mode will be restored.

Here is how to reproduce
1. vim
2. `:new | set buftype=prompt | startinsert`
3. Type any word and then try to use `Ctrl-Shift-W` to delete it(while being in the **insert mode**)
This doesn't delete the previous word

### Expected behaviour

It should delete the previous word, but it doesn't. Pressing `Ctrl-Shift-W` twice switches the window.
So essentially `Ctrl-Shift-W` is behaving exactly like `Ctrl-W`

### Version of Vim

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Aug  5 2023 11:23:13) Included patches: 1-1677

### Environment

Ubuntu `22.04.3`
GNOME Terminal -` Version 3.44.0 for GNOME 42`
bash - `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
echo $TERM
`screen-256color`

### Logs and stack traces

```shell
N/A
```

**Comment by zeertzjq** [comment]
GNONE Terminal doesn't support Ctrl-Shift-W

**Comment by chrisbra** [comment]
can you plese verify, if this works in xterm or the gui version?

**Comment by stonebrakert6** [comment]
@chrisbra I can confirm that this works with xterm. Couldn't check on gvim, since I don't have it installed(and no root access to install it either)

I think we can close this?

**Comment by ant0sha** [comment]
> GNONE Terminal doesn't support Ctrl-Shift-W

Not only that, but as well judging by the value of TERM environment variable it all happens under gnu-screen terminal multiplexer - and gnu-screen in between would not allow vim to interact even with xterm on such a level that <kbd>CTRL+SHIFT+W</kbd> can be distinguished from <kbd>CTRL+W</kbd>.
