### ISSUE TITLE
getcompletion() failes for command-modifiers

### ISSUE THREAD

**Issue by 4513ECHO** [vim/vim#12812]
### Steps to reproduce

```vim
command! -nargs=* -complete=command UserDefinedCommand echo <q-args>
let g:ret1 = getcompletion('', 'cmdline')
" This is fixed in 9.0.1708
let g:ret2 = getcompletion('UserDefinedCommand ', 'cmdline')
" :command-modifiers does not working
let g:ret3 = getcompletion('vertical ', 'cmdline')
" but this works
let g:ret4 = getcompletion('UserDefinedCommand vertical ', 'cmdline')
```

### Expected behaviour

All of contents of `g:ret1`, `g:ret2`, `g:ret3` and `g:ret4` should be same.
In reality, however, only `g:ret3` is empty.

### Version of Vim

9.0.1712

### Environment

- OS: macOS Ventura 13.4.1 (c)
- Terminal: iTerm2 3.4.20
- `$TERM`: `xterm-256color`
- Shell: Zsh 5.9

**Comment by zeertzjq** [comment]
Fixed by patch 9.0.1718

**Comment by zeertzjq** [comment]
Sorry, it was patch 9.0.1714

**Comment by 4513ECHO** [comment]
I verified. Thanks!
