### ISSUE TITLE
"vim -e -s" doesn't exit properly

### ISSUE THREAD

**Issue by bzzrak** [vim/vim#12822]
### Steps to reproduce

1. run Vim with the `-e -s` arguments, and exit it. (for example: `vim.exe -e -s -c q`)
2. The screen won't show the previous history, and you will not be able to scroll upwards, as if Vim was still running.

Notice the greyed out scrollbar on this screenshot.
<img width="400" alt="image" src="https://github.com/vim/vim/assets/77467869/2f445762-aba5-4afa-ad7c-18171551b320">

### Expected behaviour

Vim exits, and your previous command history is shown again and you can scroll up too. This is what happens if you run Vim with just the `-e` argument, without `-s` (for example: `vim.exe -e -c q`)

<img width="400" alt="image" src="https://github.com/vim/vim/assets/77467869/3ebd9111-9863-4b71-a99e-30f27c359c9d">

### Version of Vim

9.0.1712, also 9.0.1636.

### Environment

OS: Windows 11 22h2
Terminal and shell: doesn't make a difference

**Comment by nir9** [comment]
Looking into this, seems to only happen on Windows (on Ubuntu works fine)

**Comment by bzzrak** [comment]
I confirm the issue is fixed. Thanks
