### ISSUE TITLE
Text regarding Bram Moolenaar in the runtime docs

### ISSUE THREAD

**Issue by jdjohnston** [vim/vim#12821]
NB. Line numbers are as of 16 August 2023

1) `runtime/doc/intro.txt`, line `187`, still has his email address `Bram@vim.org`
2) `runtime/doc/version9.txt`, line `47`: The text describing his passing exceeds the textwidth

I just heard the news today. I'm not sure if I'm more shocked or saddened. Condolences to all who will miss him.

Would it be better to make the next release Vim 10.0 and make an emphasis that it's in honor of Bram? Using a minor release seems to make it more "minor" than it should be.

Thanks to all who are keeping his wonderful Vim a working memorial.

**Comment by tonymec** [comment]
With all due respect to Bram, who by the way was interred yesterday (Wednesday) in presence of (among others) Christian and me, IMHO release 9 is hardly begun, I think there aren't yet enough new features after release 9 to justify increasing the major release number. Even all that to-do about increasing the *minor* release number: what is new between 9.0.0 and 9.0.1721 except making the features announced for release 9 work as they ought to? I'm not even sure that increasing the minor release version is the right way to honor Bram's memory — there are other ways to do it, for instance keep the "by Bram Moolenaar et al." line on the intro screen, keep the "Help poor children in Uganda" line and the `*iccf*` help tag, and go on developing Vim in the spirit of Bram, including for instance documenting every single little feature of it.

**Comment by chrisbra** [comment]
Hm,
1) not sure I should remove his address.
2) I'll address as part of https://github.com/vim/vim/pull/12790/

**Comment by errael** [comment]
> Bram ... was interred yesterday (Wednesday) in presence of (among others) Christian and me

Thank you for sharing that. Through this sad time, knowing that two respected members of this community were present gives me a good feeling.

**Comment by chrisbra** [comment]
closing this.
