### ISSUE TITLE
Using --enable-perlinterp=dynamic still tries to link against -lperl

### ISSUE THREAD

**Issue by evelikov** [vim/vim#12827]
### Steps to reproduce

1. configure a vim build with --enable-perlinterp=dynamic
2. observe the link command line used - it has `-lperl` even though we explicitly asked for dynamic (aka dlopen/dlsym) linking
3. alternatively, make sure you're using perl 5.36 (aka https://github.com/vim/vim/issues/10512)

Note: the other "--enable-FOOinterpt=dynamic` switches might also suffer from similar issues

### Expected behaviour

1. `-lperl` isn't on the command line, and
2. issues like https://github.com/vim/vim/issues/10512 fails during build/link time

### Version of Vim

9.0.1678, and many other versions across the years

### Environment

Arch Linux x86_64

**Comment by k-takata** [comment]
Does it still occur after 9.0.1700?
