### ISSUE TITLE
Incorrect highlighting when using angle brackets in a comment

### ISSUE THREAD

**Issue by MariaSolOs** [vim/vim#12831]
### Steps to reproduce

Given the following snippet of TypeScript code:

```ts
enum Foo {
    A = 1 << 11, // A comment with "(" and ")"
    B = 2 << 12, // A comment with "<" and ">"
    C = 3 << 13, // A comment with "[" and "]"
}
```

This is the highlighting I obtain:
<img width="439" alt="image" src="https://github.com/HerringtonDarkholme/yats.vim/assets/62502207/58ec5f45-e532-4939-b6c0-5648ff597a1e">

If I remove the comment after `12`, then the highlighting is correct:
<img width="415" alt="image" src="https://github.com/HerringtonDarkholme/yats.vim/assets/62502207/ae11e1f3-b53a-4147-800c-b4ee4dd85613">

I'm using Neovim BTW. I have Treesitter highlighting disabled though. I had originally created the issue in [`yats`](https://github.com/HerringtonDarkholme/yats.vim/issues/268) because I was told this is where the syntax files for TS come from, but the maintainer cannot reproduce the issue with the latest version, and so it seems like the files here are out of date.

### Expected behaviour

For highlighting to not break when using angle brackets in a TypeScript comment.

### Version of Vim

9.0.1544

### Environment

OS: macOS Ventura 13.5
Terminal: kitty
Shell: `/bin/zsh`

**Comment by chrisbra** [comment]
Hm, that is tricky, because the `<<` and the closing `>` makes it match by the `TypeCast` group.

This patch would fix it by asserting that the `<` cannot be followed by either `[ "<]` but not sure this is correct:

```diff
diff --git a/runtime/syntax/typescript.vim b/runtime/syntax/typescript.vim
index af71938a8..14c101305 100644
--- a/runtime/syntax/typescript.vim
+++ b/runtime/syntax/typescript.vim
@@ -27,7 +27,7 @@ set cpo&vim
 " this region is NOT used in TypeScriptReact
 " nextgroup doesn't contain objectLiteral, let outer region contains it
 syntax region typescriptTypeCast matchgroup=typescriptTypeBrackets
-  \ start=/< \@!/ end=/>/
+  \ start=/<[ <"]\@!/ end=/>/
   \ contains=@typescriptType
   \ nextgroup=@typescriptExpression
   \ contained skipwhite oneline
```

**Comment by MariaSolOs** [comment]
@chrisbra FWIW it seems like the issue has already been fixed in `yats.vim`, so wouldn't updating the files here be enough...?

**Comment by chrisbra** [comment]
not sure on the maintainer. It used to be Bram, and `yats.vim` and the files distributed by Vim seem to have diverged quite a bit. So don't know

**Comment by HerringtonDarkholme** [comment]
@MariaSolOs you can try in yats.vim and run `node merge.js`.
It will give you an all-in-one syntax file. But I have no idea how it digress from vim's official repo.
