### ISSUE TITLE
passing -1 to undotree() causes SEGV

### ISSUE THREAD

**Issue by sph432** [vim/vim#12830]
### Steps to reproduce

Since 9.0 patch 1686, it is possible to specify a buf id for undotree(), to select undo histories other than the currently used buffer, which is great.

However if one, (quite likely by inputting a non-matching string into bufnr()) passes -1 to undotree(), vim segfaults.

1. :echom undotree(-1)

### Expected behaviour

An empty undo dictionary like for an unmodified buffer: `{'seq_last': 0, 'entries': [], 'time_cur': 0, 
 save_last': 0, 'synced': 1, 'save_cur': 0, 'seq_cur': 0}` was expected.

I'd prefer having an error thrown at the user.

### Version of Vim

9.0.1721

### Environment

likely irrelevant

### Logs and stack traces

```shell
will provide strace in a few hours
```

**Comment by zeertzjq** [comment]
I think this should be an error instead.

**Comment by chrisbra** [comment]
I guess this should do it:
```diff
diff --git a/src/errors.h b/src/errors.h
index 1c1b146c9..e6cc5f3d1 100644
--- a/src/errors.h
+++ b/src/errors.h
@@ -3478,6 +3478,8 @@ EXTERN char e_incomplete_type[]
 #endif
 EXTERN char e_warning_pointer_block_corrupted[]
        INIT(= N_("E1364: Warning: Pointer block corrupted"));
+EXTERN char e_buffer_nr_invalid[]
+       INIT(= N_("E1365: invalid buffer number"));
 EXTERN char e_cannot_mix_positional_and_non_positional_str[]
        INIT(= N_("E1400: Cannot mix positional and non-positional arguments: %s"));
 EXTERN char e_fmt_arg_nr_unused_str[]
@@ -3491,4 +3493,4 @@ EXTERN char e_positional_arg_num_type_inconsistent_str_str[]
 EXTERN char e_invalid_format_specifier_str[]
        INIT(= N_("E1405: Invalid format specifier: %s"));

-// E1365 - E1399 unused
+// E1366 - E1399 unused
diff --git a/src/undo.c b/src/undo.c
index 85c46707e..730073793 100644
--- a/src/undo.c
+++ b/src/undo.c
@@ -3739,6 +3739,12 @@ f_undotree(typval_T *argvars UNUSED, typval_T *rettv)
     else
        buf = tv_get_buf_from_arg(tv);

+    if (buf == NULL)
+    {
+       semsg(_(e_buffer_nr_invalid));
+       return;
+    }
+
     if (rettv_dict_alloc(rettv) == FAIL)
        return;

```

**Comment by zeertzjq** [comment]
I think it should just be `E158: Invalid buffer name: `, because `{buf}` can also be a String.
