### ISSUE TITLE
Jump to motions not work for Julia files (works in neovim)

### ISSUE THREAD

**Issue by ufdup89** [vim/vim#12849]
### Steps to reproduce

Crete a file with extension `.jl` containing the following snippet:

~~~
for i=1:100
    x[i] = 100
end
~~~

Open in vim and make sure the syntax is set to `julia`. Place the cursor on top of `for` and press `%`. Nothing happens.

### Expected behaviour

In neovim I can use `%` to jump between blocks end and beginning. E.g., placing the cursor on `for` or `end` and pressing `%` would jump back and forth. Same holds for other blocks like `if`, `while` and etc..

Is there a particular reason why this is not supported in vim for julia files?

### Version of Vim

9.01677

### Environment

macOS 13.4.1
iTerm2
xterm-256color
bash

**Comment by dkearns** [comment]
WFM.

Vim doesn't load the matchit plugin by default but it appears that Neovim does.  To load it in Vim see `:help matchit-activate`.

**Comment by ufdup89** [comment]
There was indeed a note in `https://github.com/JuliaEditorSupport/julia-vim` about that. It suggested to run `runtime macros/matchit.vim` in order to activate it, but this did not do the job for me.

What works is to add `packadd! matchit` to my `~/.vimrc`. It works now.

Thanks @dkearns
