### ISSUE TITLE
add tests for termdebug

### ISSUE THREAD

**Issue by GitMensch** [vim/vim#12878]
> Currently there is no test coverage for the termdebug plugin.  But it will be good to add some test coverage though.

_Originally posted by @yegappan in https://github.com/vim/vim/issues/12511#issuecomment-1686498745_

**Comment by yegappan** [comment]
A few tests for the termdebug plugin are added in https://github.com/vim/vim/commit/58f39d89a8adff51ab04893d1fd28e3767979f9f.

**Comment by GitMensch** [comment]
Cool! How can I execute that outside of the complete vim source tree?
Is there a way to get coverage of the Termdebug plugin when running the tests for it?
