### ISSUE TITLE
interpolated-string can't handle an object

### ISSUE THREAD

**Issue by errael** [vim/vim#12872]
### Steps to reproduce

Source the following script
```
vim9script

class C
endclass

var o = C.new()

echo printf("(printf) Object: %s", o)
echo $"(interp)Object: {o}"
```
Observe the error
```
(printf) Object: object of C {}
Error detected while processing command line..script /tmp/xxx:
line    9:
E1324: Using an object as a String
(interp)Object:
```

### Expected behaviour

No error.

### Version of Vim

9.0.1774

### Environment

linux

**Comment by errael** [comment]
In a `:def` you get
```
Error detected while compiling command line..script /tmp/xxx[17]..function <SNR>34_Foo:
line    4:
E1105: Cannot convert object to string
```

**Comment by yegappan** [comment]
String interpolation expects the result of evaluating the expression in `{}` to be a string.  So this is an expected behavior.  You can use the string() function to convert the expression to a string.  You can try using `echo $"(interp)Object: {o->string()}"`

**Comment by errael** [comment]
OK, I'll close it later. But note that the docs say

> Any expression returning a value can be enclosed between curly braces.  The value is converted to a string.

Which seems to contradict the statement

> expects the result of evaluating the expression in {} to be a string

I wouldn't expect 
```
vim9script

var v = 777
echo $"int: {v}"
```
to work since `v` is not a string. But it does.

**Comment by yegappan** [comment]
Only some types can be automatically converted to a string.  Refer to the [may_generate_2STRING()](https://github.com/vim/vim/blob/master/src/vim9instr.c#L196) function.

**Comment by errael** [comment]
Got it, thanks for the reference. Closing `not a bug`
