### ISSUE TITLE
Cursor Settings of Calling Terminal Overwritten

### ISSUE THREAD

**Issue by NoSuck** [vim/vim#1288]
The cursor may be hidden, for example (from XTerm):

```bash
printf '\e[25l'
vim -u NONE -N
```

After exiting vim, the cursor is no longer hidden.

**Comment by brammool** [comment]
That's an insane setting, and Vim resets the terminal to sane settings when it exits.

Oh, and I think there is no way in Xterm to get the current state of the cursor.

**Comment by NoSuck** [comment]
The setting works well with vimpager and vimdiff, so I would not call it insane.  Color settings are also affected:

```bash
printf '\e]12;#D00D00\x7' 
vim -u NONE -N
```
