### ISSUE TITLE
[gvim] The comment symbol `#` of python code block in markdown file is recorgnized as title

### ISSUE THREAD

**Issue by draftman9** [vim/vim#12905]
### Steps to reproduce

1. download the test.md file
2. open it with gvim and press `zM` to collapse all the title

[test.md](https://github.com/vim/vim/files/12424924/test.md)

### Expected behaviour

The comment symbol `#` of python code block in markdown file should be recorgnized a normal comment 
 instead of a title

### Version of gVim

8.2.2824

### Environment

Operating system: Microsoft Windows [Version 10.0.17763.4252]

**Comment by chrisbra** [comment]
as far as I can see, the markdown syntax file does not support folding. So please verify using `vim --clean`.

> 8.2.2824

Oh and please before reporting issues, test with latest Vim

**Comment by draftman9** [comment]
> verify using `vim --clean`.

Then the folding function dispeared totally.

> test with latest Vim

Maybe later because I am not very familiar to gvim configuration and I am afraid that the gvim does work after immigrating to vim 9.xx.

> Not sure, but I suspect the OP uses the folding provided by the markdown filetype plugin; maybe by setting `g:markdown_folding`:
> 
> ```
> let g:markdown_folding = 1
> ```
> 
> If so, the issue is fixed [upstream](https://github.com/tpope/vim-markdown/commit/f2b82b7884a3d8bde0c5de7793b27e07030eb2bc).

I will list the plugins I have installed:

```
call plug#begin('~/vimfiles/plugged')
Plug 'itchyny/lightline.vim'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'henrik/vim-indexed-search'
Plug 'junegunn/vim-peekaboo'
Plug 'machakann/vim-highlightedyank'
Plug 'jiangmiao/auto-pairs'

Plug 'godlygeek/tabular'
Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app && yarn install'  }
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
Plug 'lervag/vimtex'
Plug 'KeitaNakamura/tex-conceal.vim'

Plug 'preservim/nerdtree'
Plug 'TroyDanielFZ/vim-easymotion'

Plug 'JuliaEditorSupport/julia-vim'

Plug 'sheerun/vim-polyglot'
Plug 'ycm-core/YouCompleteMe'
Plug 'skywind3000/vim-dict'
Plug 'autozimu/LanguageClient-neovim', {'branch': 'next', 'do': 'powershell -executionpolicy bypass -File install.ps1'}

Plug 'jpalardy/vim-slime'
Plug 'hanschen/vim-ipython-cell'
Plug 'skywind3000/asyncrun.vim'

Plug 'tpope/vim-commentary'

call plug#end()
```

And I also tried to install the vim-markdown from you provided. But the problem still existed.

**Comment by chrisbra** [comment]
can you show a screenshot?

what about the output of `:scriptnames`

**Comment by draftman9** [comment]
> But if a fix is found in Vim, you'll need to upgrade to benefit from it. If you're afraid of the process, there are various channels to get support:
> 

Great advice! I will try vim 9 later. This issue does not affect my workflow much so I will close it.
