### ISSUE TITLE
<C-\><C-O> must be entered twice to take effect in Visual-block Insert mode

### ISSUE THREAD

**Issue by Coacher** [vim/vim#1290]
Hello.

Steps to reproduce:
1. Start vim: `vim -N -u NONE`
2. Hit `<C-V>I` to enter Visual-block Insert mode
3. Hit `<C-\><C-O>`

Expected results:
vim starts Normal mode for one command only

Actual results:
vim is still in Insert mode

Additional info:
Hitting `<C-\><C-O>` twice successfully starts Normal mode when in Visual-block Insert mode.
`<C-\><C-O>` works as expected in regular Insert mode.

vim is 8.0.0104.

Please fix.

**Comment by Coacher** [comment]
Still reproducible in 8.0.0273.

**Comment by chrisbra** [comment]
That is because after pressing `<c-o>` or `<c-\><c-o>` does effectively end edit() function from op_insert() and then falls through the main_loop back to edit() in normal_cmd(). We can effectively fix this, by this patch:
```patch
diff --git a/src/normal.c b/src/normal.c
index 2b867bb19..7bae34ed2 100644
--- a/src/normal.c
+++ b/src/normal.c
@@ -2041,6 +2041,8 @@ do_pending_operator(cmdarg_T *cap, int old_col, int gui_yank)

                if (restart_edit == 0)
                    restart_edit = restart_edit_save;
+               else
+                   cap->retval |= CA_COMMAND_BUSY;
            }
 #else
            vim_beep(BO_OPER);
diff --git a/src/ops.c b/src/ops.c
index 7d656a631..0a489126c 100644
--- a/src/ops.c
+++ b/src/ops.c
@@ -2571,7 +2571,8 @@ op_insert(oparg_T *oap, long count1)
     }

     t1 = oap->start;
-    edit(NUL, FALSE, (linenr_T)count1);
+    if (edit(NUL, FALSE, (linenr_T)count1))
+       return;

     /* When a tab was inserted, and the characters in front of the tab
      * have been converted to a tab as well, the column of the cursor
```
Note however, this still aborts op_insert() function. To correctly fix it, one would need to restart edit() function from op_insert. However I have no clue how to do that and I fear that would mean a larger refactor of the source code.

**Comment by brammool** [comment]
Christian Brabandt wrote:

> That is because after pressing `<c-o>` or `<c-\><c-o>` does
> effectively end edit() function from op_insert() and then falls
> through the main_loop back to edit() in normal_cmd(). We can
> effectively fix this, by this patch:

Thanks.  Perhaps we can have a test for this?

> Note however, this still aborts op_insert() function. To correctly fix
> it, one would need to restart edit() function from op_insert. However
> I have no clue how to do that and I fear that would mean a larger
> refactor of the source code.

Yeah, this use of layering modes is complicated.  I wonder what useful
command one would type after CTRL-O anyway.


-- 
BROTHER MAYNARD: Armaments Chapter Two Verses Nine to Twenty One.
ANOTHER MONK:    And St.  Attila raised his hand grenade up on high saying "O
                 Lord bless this thy hand grenade that with it thou mayest
                 blow thine enemies to tiny bits, in thy mercy. "and the Lord
                 did grin and people did feast upon the lambs and sloths and
                 carp and anchovies and orang-utans and breakfast cereals and
                 fruit bats and...
BROTHER MAYNARD: Skip a bit brother ...
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Coacher** [comment]
`:w`

**Comment by vim-ml** [comment]
On Mi, 01 Feb 2017, Bram Moolenaar wrote:

> Thanks.  Perhaps we can have a test for this?

I thought about it, but wasn't sure if you are actually are going to 
include this workaround., so I intentionally did not write a test yet. 
Will do and send an update later.

**Comment by Coacher** [comment]
I can confirm the problem is no longer reproducible with vim-8.0.0282.
Thank you very much!

**Comment by chrisbra** [comment]
I think, the patch is wrong. It returns early from op_insert() when it shouldn't. So I make the test such that it expects the old behaviour of adding all changes to the visual block but correctly go into temporary normal mode, e.g. "(insert)". Please check this patch:
```patch
diff --git a/src/ops.c b/src/ops.c
index 0a489126c..1c0276d8d 100644
--- a/src/ops.c
+++ b/src/ops.c
@@ -2571,8 +2571,7 @@ op_insert(oparg_T *oap, long count1)
     }

     t1 = oap->start;
-    if (edit(NUL, FALSE, (linenr_T)count1))
-       return;
+    (void)edit(NUL, FALSE, (linenr_T)count1);

     /* When a tab was inserted, and the characters in front of the tab
      * have been converted to a tab as well, the column of the cursor
diff --git a/src/testdir/test_visual.vim b/src/testdir/test_visual.vim
index d84a14062..5809dd44d 100644
--- a/src/testdir/test_visual.vim
+++ b/src/testdir/test_visual.vim
@@ -23,3 +23,13 @@ func Test_dotregister_paste()
   call assert_equal('hello world world', getline(1))
   q!
 endfunc
+
+func Test_Visual_ctrl_o()
+  new
+  call setline(1, ['one', 'two', 'three'])
+  call cursor(1,2)
+  call feedkeys("\<c-v>jjlIa\<c-\>\<c-o>:set nu\<cr>\<esc>", 'tx')
+  call assert_equal(['oane', 'tawo', 'tahree'], getline(1,3))
+  call assert_true(&nu)
+  bw!
+endfu
```

**Comment by chrisbra** [comment]
that should fail on pre 8.0.282 as well as on 8.0.282

**Comment by brammool** [comment]
The test isn't right, the "a" in block Visual mode should probably be an "A".
Even when fixing that, it waits for two seconds, not sure why.

**Comment by chrisbra** [comment]
No the a is correct. It's the character that is inserted after entering insert mode with 'I' I have also noticed the wait. Don't know why this happens.

**Comment by brammool** [comment]
Christian Brabandt wrote;

> No the a is correct. It's the character that is inserted after
> entering insert mode with 'I' I have also noticed the wait. Don't know
> why this happens.

Ah, when trying it out I read the "I" as a second "l".

I can avoid the wait by resetting 'showmode'.

BTW: Please don't copy/paste patches into github, either make a pull
request or sent it attached to an email.  Otherwise white space gets
messed up and I can't use patch.

-- 
BEDEVERE: Look!  It's the old man from scene 24 - what's he Doing here?
ARTHUR:   He is the keeper of the Bridge.  He asks each traveler five
          questions ...
GALAHAD:  Three questions.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
sorry, will do.
