### ISSUE TITLE
Default font choosen for Windows gvim 9.0 too small

### ISSUE THREAD

**Issue by clach04** [vim/vim#12919]
### Steps to reproduce

1. Get Windows 10
2. Get latest (as of 2023-08-25) vim/gvim (9.0)
3. Either ensure no vim config set or launch `gvim --clean`

gvim 9.0 is defaulting to Fixedsys, Regular, 4

Font is unreadable on a 4k display (I don't have another display to check, but even a non-4k display the choosen font is too small).

## Screen shot of main window on desktop

![image](https://github.com/vim/vim/assets/424032/f8258bb9-4d65-4fcd-841e-a25a8e6eba4d)

![image](https://github.com/vim/vim/assets/424032/0070480c-70fc-4ee5-b46a-aaf6fd6dbde3)

## Screen shot of font settings (from Edit->Select Font...)

![image](https://github.com/vim/vim/assets/424032/9e3391f8-3dfd-4145-8147-c53a5d87c9d2)

This appears to be https://github.com/vim/vim/issues/1059 and https://github.com/vim/vim/issues/4375.
NOTE #1059 was closed with comment https://github.com/vim/vim/issues/1059#issuecomment-306402092  "It looks like Windows 10 1703 solved this problem.", later comments appear to indicate later Windows 10 releases have similar issues. One suggested workaround in that thread is to make use of a Windows option to change the way Windows handles DPI https://github.com/vim/vim/issues/1059#issuecomment-294358464 this has **no** impact for me.

Selecting a reasonable font size (Consolas, Regular, 12) works for me (icons are not great but readable, I'm about to turn them off in my config ;-))

![image](https://github.com/vim/vim/assets/424032/650fa49f-53d3-4da7-9e0d-e7aed4a52845)

![image](https://github.com/vim/vim/assets/424032/38fc847f-4d17-4ae1-bbb2-819608705d32)

### Expected behaviour

To be able to read text when gvim opens.

### Version of Vim

9.0

### Environment

	C:\>cmd.exe /c ver

	Microsoft Windows [Version 10.0.19042.2965]

	C:\>vim --version
	VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jun 28 2022 13:10:49)
	MS-Windows 32-bit console version
	Compiled by appveyor@APPVYR-WIN
	Huge version without GUI.  Features included (+) or not (-):
	+acl                +ex_extra           +multi_lang         -tag_any_white
	+arabic             +extra_search       +mzscheme/dyn       -tcl
	+autocmd            -farsi              -netbeans_intg      +termguicolors
	+autochdir          +file_in_path       +num64              +terminal
	+autoservername     +find_in_path       +packages           -termresponse
	-balloon_eval       +float              +path_extra         +textobjects
	+balloon_eval_term  +folding            +perl/dyn           +textprop
	-browse             -footer             +persistent_undo    -tgetent
	++builtin_terms     +gettext/dyn        +popupwin           +timers
	+byte_offset        -hangul_input       -postscript         +title
	+channel            +iconv/dyn          +printer            -toolbar
	+cindent            +insert_expand      +profile            +user_commands
	+clientserver       +ipv6               +python/dyn         +vartabs
	+clipboard          +job                +python3/dyn        +vertsplit
	+cmdline_compl      +jumplist           +quickfix           +vim9script
	+cmdline_hist       +keymap             +reltime            +viminfo
	+cmdline_info       +lambda             +rightleft          +virtualedit
	+comments           +langmap            +ruby/dyn           +visual
	+conceal            +libcall            +scrollbind         +visualextra
	+cryptv             +linebreak          +signs              +vreplace
	+cscope             +lispindent         +smartindent        +vtp
	+cursorbind         +listcmds           +sodium/dyn         +wildignore
	+cursorshape        +localmap           +sound              +wildmenu
	+dialog_con         +lua/dyn            +spell              +windows
	+diff               +menu               +startuptime        +writebackup
	+digraphs           +mksession          +statusline         -xfontset
	-dnd                +modify_fname       -sun_workshop       -xim
	-ebcdic             +mouse              +syntax             -xpm_w32
	+emacs_tags         -mouseshape         +tag_binary         -xterm_save
	+eval               +multi_byte_ime/dyn -tag_old_static
	   system vimrc file: "$VIM\vimrc"
	     user vimrc file: "$HOME\_vimrc"
	 2nd user vimrc file: "$HOME\vimfiles\vimrc"
	 3rd user vimrc file: "$VIM\_vimrc"
	      user exrc file: "$HOME\_exrc"
	  2nd user exrc file: "$VIM\_exrc"
	       defaults file: "$VIMRUNTIME\defaults.vim"
	Compilation: cl -c /W3 /GF /nologo -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_TERMINAL -DFEAT_SOUND  -DFEAT_JOB_CHANNEL -DFEAT_IPV6    -DHAVE_SODIUM -DDYNAMIC_SODIUM -DDYNAMIC_SODIUM_DLL=\"libsodium.dll\" /I "C:\libsodium\include" -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 /source-charset:utf-8 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG /arch:IA32 /Zl /MT /D_CRT_SECURE_NO_DEPRECATE /D_CRT_NONSTDC_NO_DEPRECATE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua54.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python310.dll\" -DFEAT_MZSCHEME -I "C:\racket\include" -DMZ_PRECISE_GC -DDYNAMIC_MZSCHEME -DDYNAMIC_MZSCH_DLL=\"libracket3m_da32rk.dll\" -DDYNAMIC_MZGC_DLL=\"libracket3m_da32rk.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl532.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_DLL=\"msvcrt-ruby300.dll\" -DRUBY_VERSION=30 -DFEAT_HUGE /Fd.\ObjCULYHRZi386/ /Zi
	Linking: link /nologo /opt:ref /LTCG oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib netapi32.lib uuid.lib user32.lib  /machine:i386   libcmt.lib   /nodefaultlib:lua54.lib  /STACK:8388608  /nodefaultlib:python27.lib /nodefaultlib:python310.lib    winmm.lib WSock32.lib Ws2_32.lib   /PDB:vim.pdb -debug

### Logs and stack traces

```shell
N/A
```

**Comment by acc987** [comment]
I'm not a maintainer and do not know whether there are any particular reasons for using Fixedsys, but I want to contribute the following: Going by https://support.microsoft.com/en-us/topic/microsoft-supplied-monospaced-truetype-fonts-93aa7a47-2149-be09-31a9-c22df598c952, Courier New is the only TrueType that is available on all Win32 releases. What I cannot judge is whether or not the type looks decent enough to be an alternative to Fixedsys in the first place.

**Comment by clach04** [comment]
@acc987 interesting. For me personally, I don't need to worry about Windows 3.1 😉, looks like oldest claimed support is XP based on https://www.vim.org/download.php#pc (but I've not tested this out)

Extract from my config:

    if has('win32')
        " Windows 10 with 4k/HiDPI display issues. Use a decent (builtin) font with reasonable size
        "set guifont=Consolas:h10:cANSI:qDRAFT  " from https://github.com/vim/vim/issues/1059#issuecomment-299682371
        set guifont=Courier\ New:h10:cANSI:qDRAFT  " from https://github.com/vim/vim/issues/1059#issuecomment-299682371
    endif

Screen shots from Windows 10

## Courier New

![image](https://github.com/vim/vim/assets/424032/062f50a2-842b-40c1-80b9-9b4fc3906b57)


## Consolas

![image](https://github.com/vim/vim/assets/424032/58084330-d0bd-4ca7-87c5-75a85923a56a)

https://learn.microsoft.com/en-us/typography/font-list/consolas

Available for XP via MS Office?

**Comment by k-takata** [comment]
The reason why Fixedsys is selected as the default font is that it is the only font localized for every language, I think.
E.g. Japanese version of Windows includes an localized version of Fixedsys that includes Japanese glyphs.

Nowadays, Windows has the font fallback feature. So, even Courier New or Consolas doesn't include Japanese glyphs, Japanese characters can be shown.
Changing the default font from Fixedsys to Courier New or Consolas might be acceptable.

Another idea is to make it possible to change the font via gettext. It would be good if translators can select the default font for each language.

**Comment by k-takata** [comment]
See #13266

**Comment by clach04** [comment]
Thank you @k-takata and @chrisbra! Happy New Year to you both 🎉
