### ISSUE TITLE
add support for typed properties to omnicomplete for PHP

### ISSUE THREAD

**Issue by levigutt** [vim/vim#12924]
I am unable to get omnicomplete to show typed properties for php classes. it works for methods, and untyped properties, but not typed properties. 

typed properties has been in php since v7.4 (2019), so it's kind of overdue to support this.

I've used ctags to make a `tags` file and it still doesn't work, even though the typed property is present in the tags file.

I've considered using a plugin, but I really prefer using only what is built in to vim. Most plugins also seem like abandonware, or they require alot of setup. 
I work across SSH and on new machines often, so I prefer to have a simple and portable setup. 

**example of issue:**

```php
class Thing {
    public $a;
    public $b;
    public string $c;
}
$thing = new Thing();
$thing->
```

with the cursor placed after the arrow `$thing->` doing `c-x` `c-o` shows the omnicomplete menu, but property `c` is missing:

![image](https://github.com/vim/vim/assets/16719598/209e0a95-09c8-4eed-9afb-7ab20f836a00)

**Comment by chrisbra** [comment]
php omni completion is provided by the [phpcomplete.vim](https://github.com/vim/vim/blob/master/runtime/autoload/phpcomplete.vim)  plugin, that is provided by Vim. You may want to check either the upstream project: https://github.com/shawncplus/phpcomplete.vim or check directly with the maintainer, if the plugin supports typed properties.

> typed properties has been in php since v7.4 (2019), so it's kind of overdue to support this.

Well, someone has to do the work to make it support and contribute back.

**Comment by Shougo** [comment]
You can add the feature if needed.  Because it is open source.

**Comment by levigutt** [comment]
Sure thing. I'm just a little surprised that this is missing when types has been out for so long. I would have though that someone had raised and resolved the issue by now. Maybe there aren't that many PHP coders using vim? 
I'll check out shawncplus/phpcomplete :+1:

**Comment by chrisbra** [comment]
let me ping @shawncplus to remind him to send back further improvements for the upcoming release ;) and perhaps he can also comment on the typed properties thing :)

**Comment by levigutt** [comment]
this is now fixed upstream: https://github.com/shawncplus/phpcomplete.vim/commit/8a233da5b6118b05d8d6ba9ff7529f1b154cb492

**Comment by chrisbra** [comment]
I am closing this and awaiting an updated phpcomplete.vim script
