### ISSUE TITLE
Wrong cursor position when breakindent and linebreak are both enabled

### ISSUE THREAD

**Issue by julio-b** [vim/vim#12937]
### Steps to reproduce

```bash
vim --clean +'set bri lbr' - +40vsp <<END
	a aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa*aaaaaaa!bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb*bbbbbbb!ccccccccccccccccccccccccccccccc*ccccccc!dddd
	aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa*aaaaaaa!bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb*bbbbbbb!ccccccccccccccccccccccccccccccc*ccccccc!dddd
END
```
feed keys: `f*lll<C-V>llrQ`

![2023-08-28-001649_1121x736_scrot](https://github.com/vim/vim/assets/16379308/b0c5e8a8-5e69-464f-b5a6-648bbe95cdba)

As you can see the cursor goes over some virtual whitespace after the first '*'.

First bad commit is b557f4898

### Expected behaviour

Cursor should not be positioned over the virtual whitespace.

### Version of Vim

latest master @ 9.0.1811

### Environment

Operating system: ArchLinux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: Bash

**Comment by zeertzjq** [comment]
Hmm, the position of the whitespace also looks a bit strange.

**Comment by julio-b** [comment]
Yeah that's what i thought. It's a bit tricky to reproduce this, it happens when the word just the right size, so len(showbreak)+len(word) == width(window).
