### ISSUE TITLE
small delete register behaviour different when using ctrl-R

### ISSUE THREAD

**Issue by balki** [vim/vim#12947]
### Steps to reproduce

Consider below text
```
foo bar foobar
```
With cursor one the first character, I type `ciw'<Ctrl-R>"'`, I get `'foo'`. The value in register `@.` is `'foo'`.
But when I type `ciw'<Ctrl-R>-'`, I get the same `'foo'`. But the value in register `@.` is `'^R-'`.

This different behavior allows to use the `.` command to repeat the change. 

Is this intentional or a bug? I don't see this behavior documented. (I couldn't find it)

https://vimhelp.org/change.txt.html#quote-
https://vimhelp.org/insert.txt.html#i_CTRL-R

### Expected behaviour

Documentation for the different behavior

### Version of Vim

9.0.1736

### Environment

arch linux

**Comment by chrisbra** [comment]
That is intentionally there since https://github.com/vim/vim/releases/tag/v8.2.2189

How about this doc patch then:
```diff
diff --git a/runtime/doc/insert.txt b/runtime/doc/insert.txt
index ccf5178a8..8696e912f 100644
--- a/runtime/doc/insert.txt
+++ b/runtime/doc/insert.txt
@@ -127,7 +127,11 @@ CTRL-R {register}                          *i_CTRL-R*
                        '/'     the last search pattern
                        ':'     the last command-line
                        '.'     the last inserted text
+                                                       *i_CTRL-R_-*
                        '-'     the last small (less than a line) delete
+                               register. This is repeatable using |.| since
+                               it remembers the register to put instead of
+                               the literal text to insert.
                                                        *i_CTRL-R_=*
                        '='     the expression register: you are prompted to
                                enter an expression (see |expression|)
```

**Comment by balki** [comment]
Thank you for clarifying. doc patch looks good.
