### ISSUE TITLE
Missing helptags for editorconfig

### ISSUE THREAD

**Issue by bennyyip** [vim/vim#12941]
### Steps to reproduce

:help editorconfig.txt

Currently there are only two packages under `pack/dist` have document, `matchit` and `editorconfig`. `matchit` has helptags(https://github.com/vim/vim/blob/master/runtime/pack/dist/opt/matchit/doc/tags), but `editorconfig` doesn't.

### Expected behaviour

Open https://github.com/vim/vim/blob/master/runtime/pack/dist/opt/editorconfig/doc/editorconfig.txt

### Version of Vim

9.0.1811

### Environment

Doesn't matter

**Comment by chrisbra** [comment]
did you enable the plugin? then the help files should be available

**Comment by bennyyip** [comment]
@chrisbra I enabled it. But I installed vim as a system package and have no permission to generate tags  in `/usr/share/vim/vim90/pack/dist/opt/editorconfig/doc`. 
Like `matchit`, the helptags should come with the package.

**Comment by chrisbra** [comment]
ah, I need to generate a separate tags file for the editorconfig. Will be done later today.
