### ISSUE TITLE
The keytrans is not returning the correct value for <C-s>, <C-b>, <C-f>, <C-n> and <C-p>

### ISSUE THREAD

**Issue by vds2212** [vim/vim#12964]
### Steps to reproduce

1. Record a macro containing <C-s>: `qa<C-s>q`
2. Translate the content `:echo keytrans(@a)`
3. It returns `<9b><fc><C-D>S` instead of `<C-s>`

Remark: `:echo @a` is `<9b><fc>^DS` instead of `<80><fc>^DS`

The same kind of behavior is observed for `<C-b>`,  `<C-f>`, `<C-n>` and `<C-p>`

### Expected behaviour

It should return `<C-s>`

### Version of Vim

9.1811

### Environment

Operating System: Windows 10
Version of Vim: gVim

**Comment by zeertzjq** [comment]
I think the fix should be like this (similar `#ifdef` to the ones `mb_unescape()`):
```diff
diff --git a/src/message.c b/src/message.c
index a258e788b..98a362411 100644
--- a/src/message.c
+++ b/src/message.c
@@ -1842,7 +1842,11 @@ str2special(
     }
 
     c = *str;
-    if (c == K_SPECIAL && str[1] != NUL && str[2] != NUL)
+    if ((c == K_SPECIAL
+#ifdef FEAT_GUI
+		|| c == CSI
+#endif
+	) && str[1] != NUL && str[2] != NUL)
     {
 	if (str[1] == KS_MODIFIER)
 	{
@@ -1850,7 +1854,11 @@ str2special(
 	    str += 3;
 	    c = *str;
 	}
-	if (c == K_SPECIAL && str[1] != NUL && str[2] != NUL)
+	if ((c == K_SPECIAL
+#ifdef FEAT_GUI
+		    || c == CSI
+#endif
+	    ) && str[1] != NUL && str[2] != NUL)
 	{
 	    c = TO_SPECIAL(str[1], str[2]);
 	    str += 2;
```
But I'm not sure if this will cause problems.

**Comment by chrisbra** [comment]
@vds2212 can you please check #12966 ?

**Comment by vds2212** [comment]
It seems to work like a charm :-)

Thanks you very much!

**Comment by chrisbra** [comment]
thanks both ;)
