### ISSUE TITLE
vim9script: "var F: func = obj.Method" or similar is missing

### ISSUE THREAD

**Issue by errael** [vim/vim#12960]
### Steps to reproduce

There's considerable discussion, with comments about it from Bram, start around https://github.com/vim/vim/issues/12081#issuecomment-1555978215 but that issue was not about this topic and has been closed.

### Expected behaviour

Should be a way to do that.

Often times
```
var F: func = () => obj.Method()
```
is a workaround. But doesn't play with varargs and/or `call()` according to comments.

### Version of Vim

9.1

### Environment

9.1

**Comment by chrisbra** [comment]
closed by 29bb67f1beefc7fd393dbfd9ee77d92f1db3a3c0
