### ISSUE TITLE
Methods are covariant in their parameter and return types

### ISSUE THREAD

**Issue by dkearns** [vim/vim#12965]
### Steps to reproduce

```vim
vim9script
    
class A
endclass

class B extends A
endclass

class C extends B
endclass
  
class Foo
  def Doit(p: B): B
    return B.new()
  enddef
endclass

class Bar extends Foo
  def Doit(p: C): C
    return C.new()
  enddef
endclass
```

### Expected behaviour

This should not compile.  There should be type errors for both the parameter and return type as the help says:

> Object methods of the base class can be overruled.  The signature (arguments,
> argument types and return type) must be exactly the same. 

However, ideally the current implementation should just be changed to make the methods contravariant in their parameter types.  The existing covariance of return types is correct.

As there's no complications with regard to overloaded methods,which are not supported, is there a reason not to relax the restriction as stated in the help?

So, the following would compile - contravariant parameter types and covariant return types.

```vim
class Baz extends Foo
  def Doit(p: A): C
    return C.new()
  enddef
endclass
```

Irrespective, covariant parameter types should obviously not be allowed.

I don't have time to experiment further at the moment but will attempt to in the near future.

### Version of Vim

9.0.182

### Environment

Ubuntu 20.04

**Comment by yegappan** [comment]
I have created the PR #13221 to support this.  Please try it out and let me know if you see any issues.

**Comment by dkearns** [comment]
Thanks @yegappan.  I probably won't get to it until tomorrow.
