### ISSUE TITLE
[vim9script] variable used as a class incomplete

### ISSUE THREAD

**Issue by errael** [vim/vim#12961]
### Steps to reproduce

Consider the following which works OK
```
vim9script

class C
    def CF()
        echo "Boo"
    enddef
endclass

def F()
    var c = C
    var o = c.new()
    o.CF()
enddef
F()
```
If you add `o = null_class` as the last line of `F` you get an error.

This was (is?) mentioned in the todo list, but didn't make it to the list of known vim9script issues that was recently posted to the dev forum. Opening this so it's not lost.

### Expected behaviour

- `o = null_class` should work
 - There is no way to type a variable to alias a class. 
 - comparison against null/null_class should work for an object typed as null.

### Version of Vim

9.1

### Environment

9.1

**Comment by mg979** [comment]
https://github.com/vim/vim/blob/1bed993c01c4b5e4c6ab55e80e2410ba87de487c/runtime/doc/vim9.txt#L1030-L1043

Tbh I think it's nonsense, `null` should be good enough for all of them.

**Comment by dkearns** [comment]
`o` is an object. 

`o = null_object` works as does `C = null_class`.

`c = null_class` doesn't work.

We seem to have another fan of the family of null thingamebobs. :)

**Comment by errael** [comment]
> It seems as though more of the class type is implemented than is not.

Now that `:type` is implemented, there's a possibility that `vim9script` will not allow a type to be used as a variable or value. This seems related to `:help todo`
> When "Meta" is a class, is "const MetaAlias = Meta" allowed?  It should
> either work or given an error. Possibly give an error now and implement it
> later (using a typedef).  #12006

And #13450 is also related.

**Comment by errael** [comment]
The recent "type can not be a value" PRs resolve this.
