### ISSUE TITLE
Toggling options resets information about previous column for j/k

### ISSUE THREAD

**Issue by blueyed** [vim/vim#1297]
Normally `j`/`k` will go to the previous column, even when it is greater than the current one.
But when toggling `cursorline` this information gets lost.
It also happens for toggling `wrap` though, too - so it is a more general issue?!

Running the following file using `vim -u t-cursorline-resets-column.vim` shows:

```
[2, 3]
[1, 1]
[2, 3]
[1, 1]
[2, 1]
```

```
set nocp
" set cursorline

norm ofoo
norm l
echo getpos(".")[1:2]
norm k
echo getpos(".")[1:2]
norm j
echo getpos(".")[1:2]
norm k
echo getpos(".")[1:2]

" Toggling cursorline resets information about previous column.
set cursorline!
norm j
echo getpos(".")[1:2]
q!
```

The last output should be `[2, 3]`.

I am using the following to toggle the cursorline setting dynamically, that's when I've noticed this behavior:
```vim
" Manage cursorline setting: disable it when moving the cursor, because it
" causes a ridiculous amount of CPU.
let s:cursorline_last_line = 0
function! MySetupCursorLine(on)
  if &cursorline != a:on
    if a:on
      if exists('s:cursorline_orig_updatetime')
        let &updatetime = s:cursorline_orig_updatetime
        unlet s:cursorline_orig_updatetime
      endif
    else
      " Keep cursorline on when moving in the same line (through CursorMoved).
      let line = line('.')
      if s:cursorline_last_line == line
        return
      endif
      let s:cursorline_last_line = line
      if !exists('s:cursorline_orig_updatetime')
        let s:cursorline_orig_updatetime = &updatetime
        let &updatetime = 1500
      endif
    endif
    let &cursorline = a:on
  endif
  " Setup autocommand to toggle state.
  let toggle_au = a:on ? 'CursorMoved' : 'InsertLeave,CursorHold'
  augroup vimrc_cursorline_toggle
    au!
    exe 'autocmd' toggle_au '* call MySetupCursorLine(' !a:on ')'
  augroup END
endfunction
call MySetupCursorLine(1)
```

**Comment by chrisbra** [comment]
Hm, I see the problem. It is in set_bool_option:
```c
      if (curwin->w_curswant != MAXCOL
                       && (options[opt_idx].flags & (P_CURSWANT | P_RALL)) != 0)                                                                                                                                                              curwin->w_set_curswant = TRUE;
```
However the cursorline option only has the flags P_BOOL | P_VI_DEF | P_RWIN

However, because of P_RWIN it this condition is true. I am not sure this is correct or even what the intention of this condition is.

**Comment by blueyed** [comment]
The comment above might be important:
```
/* in case 'ruler' or 'showcmd' changed */
```

Ref: https://github.com/vim/vim/blob/99c5eb4fd755853a134471a63174cec71becbca7/src/option.c#L8486-L8489

**Comment by chrisbra** [comment]
I believe this comment is about comp_col() and not about the next statement.

**Comment by brammool** [comment]
Christian Brabandt wrote:

> Hm, I see the problem. It is in set_bool_option:
> ```c
>       if (curwin->w_curswant != MAXCOL
>                        && (options[opt_idx].flags & (P_CURSWANT | P_RALL)) != 0)                                                                                                                                                              curwin->w_set_curswant = TRUE;
> ```
> However the cursorline option only has the flags P_BOOL | P_VI_DEF | P_RWIN
> 
> However, because of P_RWIN it this condition is true. I am not sure
> this is correct or even what the intention of this condition is.

For the 'cursorline' option only a redraw is needed, the text won't
move.  Howver, the flag to redraw the window is also used for options
that change how text is displayed, so more things are recomputed.
Fixing this would require another flag that really only means redrawing
the window.

I'll make a patch for 'cursorline'.  Let me know if there are other
options for which this applies.

-- 
hundred-and-one symptoms of being an internet addict:
85. Choice between paying Compuserve bill and paying for kids education
    is a no brainer -- although a bit painful for your kids.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by blueyed** [comment]
@chrisbra 
Thanks for the quick fix!

> I'll make a patch for 'cursorline'. Let me know if there are other options for which this applies.

As mentioned in the issue, `wrap` is behaving in the same way - and that was just another option that came to mind when I was filing this issue.
For my use case it's fixed, but I think it needs a more thorough fix - if possible.

**Comment by brammool** [comment]
> @chrisbra 
> Thanks for the quick fix!
> 
> > I'll make a patch for 'cursorline'. Let me know if there are other options for which this applies.
> 
> As mentioned in the issue, `wrap` is behaving in the same way - and
> that was just another option that came to mind when I was filing this
> issue.  For my use case it's fixed, but I think it needs a more
> thorough fix - if possible.

The 'wrap' option does change text positioning, thus the column needs to
be updated when changing it.

-- 
From "know your smileys":
 |-P	Reaction to unusually ugly C code

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
