### ISSUE TITLE
Can't use vim8 job_star with some formats of output

### ISSUE THREAD

**Issue by eugen0329** [vim/vim#1298]
**Steps to reproduce**

On linux/macos
```bash
cd /tmp
mkdir test_dir/

cat << EOF > test_dir/a.txt
aaa
bbb
aaa
ccca
EOF

function! Out(job, data)
  call add(g:data, a:data)
endfunction


cat << EOF > test.vim
heredoc> function! Out(job, data)
  call add(g:data, a:data)
endfunction
let g:data = []
let job =  job_start(['sh', '-c', 'ag --literal --ignore-case  --nogroup --nocolor --column  -- a /tmp/test_dir/'], { 'callback': function('Out'), 'mode': 'raw'})
EOF

vim -N -u NONE test.vim
```
Than inside of vim

```viml
:so %
:echo g:data
```

**Expected**
g:data contains the same output as command `ag --literal --ignore-case  --nogroup --nocolor --column  -- a /tmp/test_dir`, executed in a terminal, i.e.:

```
/tmp/test_dir/a.txt:1:1:aaa
/tmp/test_dir/a.txt:3:1:aaa
/tmp/test_dir/a.txt:4:4:ccca
```

**Got**
```vim
['1:aaa
1:aaa
4:ccca
']
```

Suppose, vim8 job control consider `/tmp/test_dir/a.txt:1:` as a channel's `URI:port:` instead of `filename:linenumber:`.

**Comment by ichizok** [comment]
`ag` doesn't output filename (as with `--nofilename`) when stdin is pipe, and job stdin is pipe by default.
To output filename, give `'in_io': 'null'` to job option.

**Comment by eugen0329** [comment]
It helped me. Thanks!
