### ISSUE TITLE
Virtual text displays wrongly with wrap & showbreak

### ISSUE THREAD

**Issue by tcx4c70** [vim/vim#12999]
### Steps to reproduce

1. Save the following script as a file (e.g., `repro.vim`):
``` vim
set linebreak
set breakindent
set breakindentopt+=shift:2
set showbreak=+

call append(0, ["a", "  b c"])

call prop_type_add( 'Normal' , {'highlight': 'Normal', 'combine': 1} )
" '1' should be aligned with 'b'
call prop_add( 2 ,  0 ,  {'text_wrap': 'truncate', 'type': 'Normal', 'text': '  123', 'text_align': 'above'} )
```

2. Run `vim --clean`
3. `:source repro.vim`

### Expected behaviour

`1` should be aligned with `b`, like:
```
a
  123
  b c
```

### Version of Vim

9.0.1833

### Environment

OS: Fedora 38
Terminal: Windows Terminal (using ssh to connect to the Fedora)
Value of $TERM: xterm-256color
Shell: zsh 5.9

**Comment by tcx4c70** [comment]
I don't do `bisect` for this example since it can be reproduced with vim 9.0.0438, which intruduces the above virtual text.

**Comment by tcx4c70** [comment]
After @zeertzjq's fix in #12998, the script can't reproduce the issue.

The new script which can reproduce:
``` vim
set linebreak
set breakindent
set breakindentopt+=shift:2
set showbreak=+

call append(0, ["a", "  b c"])

call prop_type_add( 'Normal' , {'highlight': 'Normal'} )
" '1' should be aligned with 'b'
call prop_add( 2 ,  0 ,  {'type': 'Normal', 'text': '  123', 'text_align': 'above'} )
call prop_add( 2 ,  4 ,  {'type': 'Normal', 'text': ': 456'} )
```

The content should be:
```
a
  123
  b: 456 c
```
but actually it is:
![image](https://github.com/vim/vim/assets/16728230/c0918369-d7c2-41ae-9e22-c2c86d5dccd7)

**Comment by zeertzjq** [comment]
Without 'linebreak' the cursor position is also incorrect.

**Comment by tcx4c70** [comment]
Hi @zeertzjq , thanks for your work! I have confirmed your branch fixes the 2 issues for both the repro scripts and a real project.

**Comment by chrisbra** [comment]
should be fixed by https://github.com/vim/vim/commit/ce53e3ea55d12d222a73510d772e786b7ae29c8d
