### ISSUE TITLE
Starstar and {} expansion do not work together

### ISSUE THREAD

**Issue by malykhin-yuri** [vim/vim#13002]
### Steps to reproduce

Starstar (**) expansion does not work when combined with {} enumeration.
Suppose we want to run vimgrep on *.h and *.cpp files in the directory my_project and its subdirectories:
```
:vimgrep iostream my_project/**/*.{h,cpp}
```
This does not work as expected, no files are found.
Here is the files tree:
```
$ find
.
./my_project
./my_project/my_lib
./my_project/my_lib/backend
./my_project/my_lib/backend/a.h
./my_project/my_lib/backend/a.cpp
```

### Expected behaviour

I expect that the search in my_project/**/*.{h,cpp} will work as in shell e.g.
```
$ ls my_project/**/*.{h,cpp}
my_project/my_lib/backend/a.cpp  my_project/my_lib/backend/a.h
```

### Version of Vim

8.1 (Included patches: 1-2269, 3612, 3625, 3669, 3741)

### Environment

OS: Ubuntu 20.04
Terminal: Gnome Terminal 3.36.2
Shell: GNU bash, version 5.0.17(1)-release

**Comment by chrisbra** [comment]
can you please check with an uptodate vim? Also, what does `echo glob2regpat()` for your pattern expand?

**Comment by malykhin-yuri** [comment]
> can you please check with an uptodate vim?

I clone github repo and build vim:
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Sep  1 2023 19:43:33)

The same effect:
```
:vimgrep iostream my_project/**/*.{h,cpp}
```
leads to 
```
"my_project/**/*.cpp" [New DIRECTORY]                                                                                                     
"my_project/**/*.h" [New DIRECTORY]
Cannot open file "my_project/**/*.h"
```
But
```
:vimgrep iostream my_project/**/*.h
```
works fine.

> Also, what does `echo glob2regpat()` for your pattern expand?
```
:echo glob2regpat("my_project/**/*.{h,cpp}")
```
results to
```
^my_project/.*/.*\.\(h\|cpp\)$                                                                                                            
```

**Comment by chrisbra** [comment]
okay, I tried the following:
```
mkdir -p ~/temp/myproject/backend/
cd $_
touch a.{sh,cpp,h}
vim --clean
:vimgrep /^/ ~/temp/**/*.{h,cpp}
```

This did result in `vimgrep` finding the files: `~/temp/myproject/backend/a.cpp` and `~/temp/myproject/backend/a.h` but ignoring `~/temp/myproject/backend/a.sh`

Can you please verify?

**Comment by fritzophrenic** [comment]
I've been seeing this issue for a while also and have never been able to track down the cause.

Using your test case, it's actually worse than normal. I get an error:

```
"~/temp/**/*.cpp" [New DIRECTORY]
"~/temp/**/*.h" [New DIRECTORY]
Cannot open file "/home/ben/temp/**/*.h"
E480: No match: ^
Press ENTER or type command to continue
```

I've never seen that one before...

```$ vim --version
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Sep  2 2023 15:34:32)
Included patches: 1-1853
```

Using ~/temp/**/*.cpp in the vimgrep command finds the match in the expected file.

**Comment by chrisbra** [comment]
hm, perhaps it dpeends on your shell setting?  I am using `zsh`

**Comment by fritzophrenic** [comment]
I installed zsh to give it a go.

If I run vim --clean and set the 'sh' option to /usr/bin/zsh, the vimgrep command works as expected, it does not try accessing literal '**' directories.

```
  shell=/usr/bin/zsh
  shellredir=>%s 2>&1
  shellcmdflag=-c
  shellpipe=2>&1| tee
  shellquote=
  shellxquote=
  shellxescape=
```

Broken config:
```
  shell=/bin/bash
  shellredir=>%s 2>&1
  shellcmdflag=-c
  shellpipe=2>&1| tee
  shellxquote=
  shellquote=
  shellxescape=
```

Same result whether Vim was launched from bash, zsh, or a gvim shortcut.

I have seen a similar issue on Windows (but don't get the errors for non-existent directory) as well. I have trained myself to give each extension individually and use absolute paths on Windows when using "**".

**Comment by chrisbra** [comment]
BTW: Since this pattern works in bash only with the `globstar` setting set, I would think that `:set shellcmdflag=-ic` could also fix it (because it should read your bash configuration file)

**Comment by malykhin-yuri** [comment]
Dear Christian Brabandt!

I forgot to mention that ** in vim works well without {}, e.g.
```
:vimgrep /^/ ~/temp/**
```
correctly finds all files in temp dir. And with ```set shellcmdflag=-ic``` is works very strangely, goes out of vim...

**Comment by chrisbra** [comment]
You don't need the '**' here. Try it with some more deeply expansions please.Am 23.09.2023 um 12:53 schrieb malykhin-yuri ***@***.***>:﻿
Dear Christian Brabandt!
I forgot to mention that ** in vim works well without {}, e.g.
:vimgrep /^/ ~/temp/**

correctly finds all files in temp dir. And with set shellcmdflag=-ic is works very strangely, goes out of vim...

**Comment by malykhin-yuri** [comment]
Wow, not it works as expected, thanks a lot!
