### ISSUE TITLE
breakindent doesn't take effect in a line with virtual text

### ISSUE THREAD

**Issue by tcx4c70** [vim/vim#13008]
### Steps to reproduce

1. Save the following script as a file (e.g., `repro.vim`):
``` vim
set wrap
set linebreak
set breakindent
set breakindentopt+=shift:4

" increase the length to make sure that it can't be showed in one line
call setline(1, "a a_very_very_very_log_line a_very_very_very_log_line a_very_very_very_log_line a_very_very_very_log_line a_very_very_very_log_line a_very_very_very_log_line")

call prop_type_add( 'Normal' , {'highlight': 'Normal'}  )
call prop_add( 1 ,  2 ,  {'type': 'Normal', 'text': ':123'}  )
normal! $
```
2. Run `vim --clean`
3. `:source repro.vim`

### Expected behaviour

4 "virtual spaces" should be showed in the wrapped line and the cursor should be in the last `e`.

### Version of Vim

9.0.1839

### Environment

OS: Fedora 38
Terminal: Windows Terminal (using ssh to connect to the Fedora)
Value of $TERM: xterm-256color
Shell: zsh 5.9

**Comment by tcx4c70** [comment]
The actual content I get:
<img width="1056" alt="image" src="https://github.com/vim/vim/assets/16728230/44143bd6-ca3e-4207-9637-29e7917935b6">

I'm not sure but it looks like the cursor is in the correct position if breakindent takes effect.

**Comment by tcx4c70** [comment]
And everythin is OK if I remove `prop_add`:
<img width="1055" alt="image" src="https://github.com/vim/vim/assets/16728230/fc42ef1b-2110-4908-8353-a5ca440d146d">

**Comment by zeertzjq** [comment]
It seems to work if you add `'text_wrap': 'wrap'` to the text prop.

**Comment by tcx4c70** [comment]
> It seems to work if you add 'text_wrap': 'wrap' to the text prop.

Yes, it works. Is it expected?

According to the doc:
>                    text_wrap    when "text" is present and {col} is zero,
>                                specifies what happens if the text doesn't
>                                fit:
>                                   wrap      wrap the text to the next line
>                                   truncate  truncate the text to make it fit
>                                When omitted "truncate" is used.
>                                Note that this applies to the individual text
>                                property, the 'wrap' option sets the overall
>                                behavior

I used to think it's only affect the virtual text when col is zero. But from the test, it looks that it will take effect even if col is not zero and it affects not only the virtual text but also the whole line which contains the virtual text.

**Comment by zeertzjq** [comment]
Related: #12769

**Comment by tcx4c70** [comment]
After some bisect, it seems that 73c3842fa54a ("patch 9.0.0162: text property "below" gets indent if 'breakindent' is set") intruduces the issue.
