### ISSUE TITLE
mode(1) returns 't' when entering the command line from Terminal-job mode

### ISSUE THREAD

**Issue by iranoan** [vim/vim#13017]
## Instructions

For Example:

``` vim
vim -u NONE +'cnoremap <expr> : mode(1)' +terminal
```

When `<C-W>:` is typed return 't'.
From Terminal-normal mode, return 'c'

## Suggestion
In command line mode, we want to include 'c' in the return value of mode(1).

mode() return 'c'
mode(1) return 'ct'

### Counterproposal (for compatibility)

mode() return 't'
mode(1) return 'tc'

## Related
[vim-jp#1425](https://github.com/vim-jp/issues/issues/1425)

**Comment by h-east** [comment]
I think it makes sense for mode() to return 'c' while staying in command-line mode, whether via terminal mode or not.
In other words, I think the current behavior is a bug and should be fixed.

BTW, the current test did not have code to check mode() for command-line mode via Terminal-Job mode and Terminal-Normal mode.

I'm going to put out this PR, so please wait a moment.
