### ISSUE TITLE
Add support for files and directory fuzzy matching

### ISSUE THREAD

**Issue by mortezadadgar** [vim/vim#13035]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
it's not impossible there is a `matchfuzzy()` 

**Describe the solution you'd like**
commands like `:find` would benefits from having fuzzy completions

**Describe alternatives you've considered**
nothing I'm aware except using external plugins

**Additional context**
none

**Comment by mortezadadgar** [comment]
cc @yegappan

**Comment by chrisbra** [comment]
isn't that something that a plugin should provide?

**Comment by mortezadadgar** [comment]
`matchfuzzy()` can be used anywhere right why not takes advantages of built-in vim features?

**Comment by chrisbra** [comment]
Well, every feature comes with a cost. And correct me if I am wrong, A plugin can already receive the list of existing files and filter them according to the `matchfuzzy()` results, right? So I would think this is a good opportunity for a plugin.

**Comment by mortezadadgar** [comment]
yea I assume a plugin can takes advantages of this api, what do you think about having a `fuzzy` option for completeopt? i think that make more sense to be implemented as a feature

**Comment by glepnir** [comment]
@chrisbra  can close now.

**Comment by zeertzjq** [comment]
I don't think there is any fuzzy matching that applies to `:find`
