### ISSUE TITLE
Go to next method odd behavior in Python

### ISSUE THREAD

**Issue by vds2212** [vim/vim#13048]
### Steps to reproduce

1. position the cursor at the first line (the definition of foo)

```python
def foo():
    foo = "foo"
    print(f"'{foo}'")

def bar():
    print("bar")
```
2. hit `]`
3. wait 1 second
4. hit `m`

the cursor position in at `{foo}` instead of at `def bar`

If you hit `]m` or wait less than one second between `]` and `m` the cursor get correctly positioned.

### Expected behaviour

The cursor should be positioned at `def bar`

### Version of Vim

gVim 9.0.1811 or Vim 9.0.1811

### Environment

Operating System: Windows 10 or WSL

### Remarks:

It seems that:
- If we wait 1 second between `]` and `m` vim search for a `{` instead of a `def`.
- If we wait 1 second between `[` and `m` vim search for a `}` instead of a `def`.

It seems that if we wait Vim assume Java or C language instead of Python.

PS: The problem occurs also in Neovim (not sure how much it help to know that).

**Comment by k-takata** [comment]
The 'timeout' option is set by default, which causes 1-second timeout for key mappings.
If you type `]m` within a second, the mapping defined in `ftplugin/python.vim` is executed.
If you wait a second, timeout occurs and the default `]m` command is executed.

**Comment by vds2212** [comment]
I understand the `ftplugin/python.vim` introduces a custom mapping that is executed if and only if the `timeoutlen` is not exceeded.

Thanks you very much for your support (I'll increase the `timeoutlen` ;-) ).
