### ISSUE TITLE
Cannot declare abstract methods

### ISSUE THREAD

**Issue by dkearns** [vim/vim#13044]
### Steps to reproduce

There's currently no way to declare abstract methods in an abstract class.

This topic doesn't appear to be mentioned in the help, TODO, source or Vim-9.1 milestone issues.

Abstract classes without the ability to declare abstract methods don't seem very useful.

### Expected behaviour

There should be a mechanism to mark a method declaration as abstract.  This should presumably use the same syntax as declarations in interfaces but also be prefixed with the `abstract` modifier.

### Version of Vim

9.0.1876

### Environment

Ubuntu 20.04

**Comment by yegappan** [comment]
Should we support abstract class methods in Vim9?  It looks like some languages don't support it:

Java:
https://stackoverflow.com/questions/370962/why-cant-static-methods-be-abstract-in-java
https://docs.oracle.com/javase/specs/jls/se9/html/jls-8.html#jls-8.4.3
https://docs.oracle.com/javase/tutorial/java/IandI/abstract.html

C#:
https://stackoverflow.com/questions/3284/why-cant-i-have-abstract-static-methods-in-c

Typescript:
https://www.typescriptlang.org/docs/handbook/2/classes.html#abstract-classes-and-members

**Comment by yegappan** [comment]
With the changes in PR #13046, abstract class methods are supported.  If this is not needed, then changes are needed to
detect this at compile time and fail.
