### ISSUE TITLE
t_Cs and t_Ce for undercurl in terminal dont seem to work

### ISSUE THREAD

**Issue by kovidgoyal** [vim/vim#1306]
Accoring to the vim documentation t_Cs and t_Ce can be set to for undercurl start/end respectively. However, doing that in .vimrc seems to have no effect when used in a highlighting style, in terminal vim. 

Minimal vimrc
```
let &t_Cs = "\e[6m"
let &t_Ce = "\e[24m"
hi SpellBad     gui=undercurl guisp=red term=undercurl cterm=undercurl
```

However, the bad spelling highlighting still uses underlines, despite the above settings. I assume this is because somewhere undercurl is hard coded to be GUI only. Can this be changed, please? I have created a terminal that allows undercurl highlighting. https://github.com/kovidgoyal/kitty

Also, guisp will need to be passed to the terminal as well, so probably there needs to be another termcap setting, maybe t_8u that will work like the existing t_8f and t_8b settings.

**Comment by kovidgoyal** [comment]
See also #819 and https://groups.google.com/forum/?nomobile=true#!topic/vim_dev/GqQeZjpgIOY

**Comment by egmontkob** [comment]
If vim implements this, this would be a good reason for us to add support to VTE too, which I'd be happy to do :) See https://bugzilla.gnome.org/show_bug.cgi?id=721761 comments 16-18. There'd be disagreements about the escape sequence though, see there.

**Comment by kovidgoyal** [comment]
@brammool Thank you very much :)

**Comment by avernan** [comment]
I've implemented some code to manage underline colors in terminal Vim. See #2405

**Comment by egmontkob** [comment]
Just for the record, the escape sequences have recently been changed, so here's the updated version of the minimal vimrc from the original report:

    let &t_Cs = "\e[4:3m"
    let &t_Ce = "\e[4:0m"
    hi SpellBad     gui=undercurl guisp=red term=undercurl cterm=undercurl

VTE (GNOME Terminal) now also supports this in git.
