### ISSUE TITLE
www.vim.org website certificate expired

### ISSUE THREAD

**Issue by taladar** [vim/vim#13079]
### Steps to reproduce

Go to https://www.vim.org
See certificate error

### Expected behaviour

Valid certificate

### Version of Vim

N/A

### Environment

N/A

### Logs and stack traces

```shell
Certificate expiry section of the Let's Encrypt certificate, presumably the ACME-client didn't manage to get a new one

Not Before Sat, 10 Jun 2023 04:38:43 GMT
Not After Fri, 08 Sep 2023 04:38:42 GMT
```

**Comment by chrisbra** [comment]
yeah, something strange is going on. If you reload the page, chances are, you get to the site and the cert is also valid 🤷 

See also discussed here: https://groups.google.com/g/vim_dev/c/YAy0EbfpjD0/m/pdlsrWaNEQAJ

I suspect something wrong with OSDN or such. Not sure how to fix it, other than finally moving vim.org homepage.

**Comment by chrisbra** [comment]
I have opened a ticket with support about this.

**Comment by stefanos82** [comment]
Works on my side via Firefox-ESR 115.2.0esr (64-bit):

```
Not Before Sat, 26 Aug 2023 23:34:41 GMT
Not After  Fri, 24 Nov 2023 23:34:40 GMT
```

Seems like the Apache settings are a bit messed up...

```
stefanos@debian:~ $ curl -IL vim.org
curl: (6) Could not resolve host: vim.org

stefanos@debian:~ $ curl -IL www.vim.org
HTTP/1.1 302 Found
Date: Tue, 12 Sep 2023 22:10:38 GMT
Server: Apache/2.4.10 (Debian)
Location: https://www.vim.org/
Content-Type: text/html; charset=iso-8859-1

curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

stefanos@debian:~ $ curl -IL http://www.vim.org
HTTP/1.1 302 Found
Date: Tue, 12 Sep 2023 22:10:47 GMT
Server: Apache/2.4.10 (Debian)
Location: https://www.vim.org/
Content-Type: text/html; charset=iso-8859-1

curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

stefanos@debian:~ $ curl -IL https://vim.org
curl: (6) Could not resolve host: vim.org

stefanos@debian:~ $ curl -IL https://www.vim.org
HTTP/1.1 200 OK
Date: Tue, 12 Sep 2023 22:11:03 GMT
Server: Apache/2.4.10 (Debian)
Content-Type: text/html
Content-Language: ja
```

**Comment by stefanos82** [comment]
Could it be a missing domain setting via `certbot` that system admin forgot to add, so the necessary certificate would have gotten generated the first place, via `certbot -d vim.org -d www.vim.org`?

That's a plausible scenario... :thinking:

**Comment by Shane-XB-Qian** [comment]
now it is totally not working
```log
Firefox detected an issue and did not continue to www.vim.org. The website is either misconfigured or your computer clock is set to the wrong time.
```

**Comment by stefanos82** [comment]
I have just tested it via `elinks` and this is what I get from http://www.vim.org

![image](https://github.com/vim/vim/assets/1777466/c1342c38-ae76-4811-90cd-54a27d6714e7)

So, as you can see, there's a database problem being reported.

**Comment by chrisbra** [comment]
yes, working on getting a better hosting soon: https://groups.google.com/g/vim_announce/c/itcFF4DNj4A

**Comment by Shane-XB-Qian** [comment]
i donot understand how's this related to db, seems you are using http.

**Comment by chrisbra** [comment]
even if you are lucky enough and connect to `http://www.vim.org` you won't be able to login, because then the database has another issue :(

**Comment by Shane-XB-Qian** [comment]
> even if you are lucky enough and connect to `http://www.vim.org` you won't be able to login, because then the database has another issue :( 

ok, from current/above information, it cannot tell the db what happened..
// if gave me access, i may help to check :lol:

-- 
shane.xb.qian

**Comment by Shane-XB-Qian** [comment]
googlemail also blocked my mail to maillist, repaste here:
```txt
was that ok if just renew the cert?
not sure who's in charge of oschina, if that required some admin from there,
perhaps just call them, i may help if gave me a their admin contact num, :-)
// i can speak Chinese (Mandarin) :lol:
```

**Comment by Shane-XB-Qian** [comment]
```log
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;vim.org.			IN	A

;; AUTHORITY SECTION:
vim.org.		187	IN	SOA	ns.42.org. sec.42.org. 2023072100 28800 3600 864000 57600

;; Query time: 8 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Thu Sep 21 21:38:49 HKT 2023
;; MSG SIZE  rcvd: 82
```

SOA looks stands for `service out available`? 
currently vim.org is a unreachable domain.

**Comment by taladar** [comment]
No SOA stands for State of Authority which is the central record type with the metadata for every DNS zone.

**Comment by Shane-XB-Qian** [comment]
ok, ping and curl saying it is service out available.

**Comment by clayjar** [comment]
A Japanese user is reporting that instabilities have been observed with OSDN-hosted sites after the OSChina took over OSDN, and that many projects are moving over to SourceForge (or GitHub). I don't think SourceForge offers a type of hosting service that OSDN had offered(VPS?), but I guess we'll see.  Aren't there other options besides SourceForge or GitHub for dedicated hosting?

Ref: https://forest.watch.impress.co.jp/docs/serial/yajiuma/1520801.html

**Comment by chrisbra** [comment]
This should be fixed now since we have been moved to a new hosting provider. See the announcements on the [vim_announce](https://groups.google.com/g/vim_announce/c/itcFF4DNj4A) list

the ssl cert should also work now. 

so I am closing this now.
