### ISSUE TITLE
Editorconfig plugin visibility

### ISSUE THREAD

**Issue by chrisbra** [vim/vim#13078]
Hi, I just noticed this new plugin in Vim source code and saw this thread. I'm sorry to resurface the discussion but it seemed like some folks were making the argument for enabling this by default, with the basic assumption that EditorConfig is enabled by most editors other than Vim. However, I just tried VSCode (the most popular text editor in the world) and it doesn't seem to be the case? The [EditorConfig extension](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) doesn't seem to be installed by default and you have to manually do it yourself as a user. FWIW I think this is the desired behavior. I think users who want to use it can just add a one liner in their vimrc to enable it and most of the times you are working on a project long-term and it's literally a one-time thing. I personally would prefer my text editor not scan all the parent folders of all text files I edit. Vim is not designed as a "no config" text editor. (Neovim does enable it by default though)

That said, I wonder if we can do a better job documenting the bundled packages? Right now, this is quite undiscoverable. The only bundled optional package that I can find documentation on is "matchit", and it's kind of in a weird location. I think it would be nice to list all optional Vim packages/components that can be loaded on demand. For example, I think typing `:h editorconfig` should show… something. Bundled packages *are* part of Vim because we have essentially stamped our seal of approval, and therefore the documentation should reflect that. For example if you do `:h filetype` you will see documentation for misc bundled file types like `if-rust`.

There are also odd balls like the ones in `$VIMRUNTIME/tools/emoji_list.vim` but maybe that's out of scope for this.

_Originally posted by @ychin in https://github.com/vim/vim/issues/2286#issuecomment-1714675869_

**Comment by chrisbra** [comment]
may be somewhere close to where currently `matchit` is mentioned?

https://github.com/vim/vim/blob/596ad66d1ddb742ef349e98eb06b8e4052f68f51/runtime/doc/usr_05.txt#L394-L430

**Comment by bfrg** [comment]
Currently, there are a few older plugins (netrw etc.) that are not packages. These were added before Vim's package-feature existed and are located in `$VIMRUNTIME/plugin/`. I think, we should put all plugins under `pack/dist/`, either under `opt` or `start`. Then we can list them all under a dedicated "bundled packages/plugins" help section.

**Comment by ychin** [comment]
I do wonder if that will just mean a lot of loose folders in `pack`. If they are enabled by default then placing them under autoload/plugin isn't *too* bad, but it does make it messy. I do like the general idea of a centralized "here are the list of bundled extensions and these are enabled, those are optional" documentation page. Just helps to keep it in one place and easy to understand.

I personally also don't understand why `ftplugin/man.vim` (for `:Man`) and misc files under `syntax` (e.g. colortest.vim, 2html.vim) are where they are as they seem kind of out of place but maybe it's out of scope.

**Comment by fritzophrenic** [comment]
> I do wonder if that will just mean a lot of loose folders in `pack`. If they are enabled by default then placing them under autoload/plugin isn't _too_ bad, but it does make it messy. I do like the general idea of a centralized "here are the list of bundled extensions and these are enabled, those are optional" documentation page. Just helps to keep it in one place and easy to understand.
> 
> I personally also don't understand why `ftplugin/man.vim` (for `:Man`) and misc files under `syntax` (e.g. colortest.vim, 2html.vim) are where they are as they seem kind of out of place but maybe it's out of scope.

2html.vim in particular mostly is where it is for backwards compatibility. Some people (notably in the past, Bram) have scripts and tooling that just source the script with a runtime command rather than loading and running the command defined in the plugin file. I personally have no objections to refactoring it and moving to a more logical place, I feel like I suggested that to Bram once upon a time but he wanted to keep the ability to source it the old way.

That said, one of Vim's big strengths is the expectation that something you make that works today is mostly expected to continue working whenever you upgrade.
