### ISSUE TITLE
Opening `.fth` files results in an error message: No such variable: "s:matchit_patterns"

### ISSUE THREAD

**Issue by Liorst4** [vim/vim#13089]
### Steps to reproduce

1. `git clone https://github.com/vim/vim.git` (commit id at the time of making: `6ffcc58be32aa1b337bc839cfe173b68cfde7085`)
2. `./configure --prefix=$(pwd)/build --with-x=no --disable-gui`
3. `make`
4. `make install`
5. `cd build/bin`
6. `./vim thing.fth`

### Expected behaviour

Opening `.fth` files should not result in an error message

### Version of Vim

9.0

### Environment

Operating system: alpine
Terminal: SSH
Value of $TERM: xterm-256color
Shell: /bin/ash

### Logs and stack traces

```shell
"thing.fth" [New]
Error detected while processing BufNewFile Autocommands for "*.fth"..FileType Autocommands for "*"..function <SNR>3_LoadFTPlugin[18]..script /home/.../src/vim/build/share/vim/vim90/ftplugin/forth.vim:
line   71:
E108: No such variable: "s:matchit_patterns"
Press ENTER or type command to continue
```
```

**Comment by chrisbra** [comment]
Looks like this:

https://github.com/vim/vim/blob/6ffcc58be32aa1b337bc839cfe173b68cfde7085/runtime/ftplugin/forth.vim#L71

should be a `:let!` with (bang)

ping @dkearns
