### ISSUE TITLE
test command has no "==" operator

### ISSUE THREAD

**Issue by Rhialto** [vim/vim#13095]
### Steps to reproduce

Build 9.0.1899 in pkgsrc.

### Expected behaviour

A clean configure step.

Unfortunately, on line `7048 of src/auto/configure`, originating from line 1514 in `src/configure.ac`, there is
```
if test "X$vi_cv_var_python3_stable_abi_hex" == "X"; then
```
This should be `=` instead of `==`. See detailed explanation below, as produced by pkgsrc's portability checker.

### Version of Vim

9.0.1899

### Environment

pkgsrc on NetBSD

### Logs and stack traces

```shell
=> Checking for portability problems in extracted files
ERROR: [check-portability.awk] => Found test ... == ...:
ERROR: [check-portability.awk] auto/configure:7048:         if test "X$vi_cv_var_python3_stable_abi_hex" == "X"; then

Explanation:
===========================================================================
The "test" command, as well as the "[" command, are not required to know
the "==" operator. Only a few implementations like bash and some
versions of ksh support it.

When you run "test foo == foo" on a platform that does not support the
"==" operator, the result will be "false" instead of "true". This can
lead to unexpected behavior.

There are two ways to fix this error message. If the file that contains
the "test ==" is needed for building the package, you should create a
patch for it, replacing the "==" operator with "=". If the file is not
needed, add its name to the CHECK_PORTABILITY_SKIP variable in the
package Makefile.
===========================================================================
```

**Comment by ychin** [comment]
This was my bad. I'll submit a fix.

Btw how did you get message that to show? Did you manually run a validator on it or something?

**Comment by Rhialto** [comment]
Thanks! I saw the message because I'm a committer to [pkgsrc](http://pkgsrc.org/), and I wanted to update the vim package. One of the checks it does (maybe only if you set some "I'm a pkgsrc developer" variable) is for common portability issues. I think this one is actually by far the most common one; without checking I wouldn't know what other things are checked.
