### ISSUE TITLE
[Feature Request] option to set magic to verymagic

### ISSUE THREAD

**Issue by balki** [vim/vim#13098]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
When searching for patterns many grouping `()` and alternatives `|` it becomes tedious to escape with backslash `\`. Most of the time, I prefix the search string with `/\v`. It would be good to have an option to make that automatic. 

**Describe the solution you'd like**
`set magic=very` 
if existing option cannot be modified, new option like 
`set magiclevel=very`
Ideally the option should only affect below interactive use
1. search with / or ?
2. commands that take pattern, e.g. `s//`, `g//`, `sort`
For use within functions in vimrc, existing behavior should be kept. Also recommend to deprecate usage of pattern in functions without prefixing `\v`, `\m`, `\M` or `\V`.

**Describe alternatives you've considered**
```
nmap / /\v
nmap ? ?\v
```
Above works for common cases but not for commands. Not sure if they have any unexpected side effects.

**Comment by chrisbra** [comment]
This has been discussed before and decided against. In general, such options cause more troubles than expected, especially for plugins, that may not be aware of such changes.
