### ISSUE TITLE
Display bug -- foldcolumn + non-ASCII-expansion

### ISSUE THREAD

**Issue by esiegerman** [vim/vim#1310]
(Tested with Vim 8.0.124)

A nonzero foldcolumn interacts badly with expanded (e.g. non-ASCII) characters to produce incorrect screen display.

To reproduce, using test file [demo.txt](https://github.com/vim/vim/files/632968/demo.txt):

```
  % vim
  :vsp demo.txt
  :set foldcolumn=2
  :vert resize 100
```

All good so far.  But now do:

```
  :vert resize 105
```

Result:
  - the first screen line is still displayed correctly
  - but the second screen line has disappeared
  - If you type `$`, the cursor goes to somewhere that looks way off in never-never land -- but in fact it's just where it should be, i.e. where the final "t" in "output" would be if it were visible

Additional notes:
  - The bug manifests if the line wraps after either the "<" or "8" of the "<82>" expansion.
      - If you use `^W<` and `^W>` to play with the window's width, you'll see that second line blinking in and out of visibility as the wrap point scans across the characters of the "<82>" expansion
      - With `foldcolumn=2` as described until now, wrapping after the "2" displays correctly, but if you `:set foldcolumn=3`, then readjust to wrap after the "2", the problem recurs

  - If I replace the 0x82 character in the buffer with a literal string "<82>", the bug no longer manifests.  It's expanding one buffer character into several screen characters, not the specific screen characters chosen, that seems to matter

  - This does not seem to be a termcap/terminfo problem:
      - It's *not* the case that the missing text is output by vim but not displayed by the terminal; rather, vim doesn't output it at all.  Proof:
        - `demo.txt` contains exactly one instance each of "!", "#", and "%"
        - I've reproduced the bug under script(1), and verified that the captured output does not contain any "!", "#", or "%" characters; ergo, vim didn't write them to stdout
        - N.B.: The recipe shown above won't allow such a simple test, since the file is displayed correctly on first loading, but the variant that's attached as [bug-script.txt](https://github.com/vim/vim/files/632989/bug-script.txt) will do so -- it postpones loading the file until the window has been adjusted to a "bad" configuration
      - in fact, the problem occurs in gvim too

**Comment by chrisbra** [comment]
I cannot reproduce this problem. It works as expected. Try running with vim -u NONE -N --noplugin Also see the [faq](https://vimhelp.appspot.com/vim_faq.txt.html#faq-2.5)

**Comment by esiegerman** [comment]
I hadn't tried that; should have done; thanks for the reminder.  (BTW, the FAQ doesn't mention `--noplugin`, but does suggest a couple of other options.  So I tested with the union of them:
`vim -u NONE -U NONE -N -i NONE --noplugin`.)

Testing that way, I _do_ still see the problem, in both text and graphic modes.

This is on Ubuntu 12.04 LTS, btw; with vim 8.0.124 compiled from source.

**Comment by esiegerman** [comment]
Since it's not trivially reproducible, I'll dig deeper -- I have a couple of VMs I can try it on (Ubuntu 16.04; FreeBSD 11.0).  I'll get to that this afternoon.

Also, [bugreport-1204.txt](https://github.com/vim/vim/files/634560/bugrep-1204.txt) contains the bugreport.vim output for the already-tested 12.04 system.

**Comment by esiegerman** [comment]
So, I was afraid I might have done something embarrassingly dumb re. encodings.  I'm now pretty sure that's not the case -- but convincing myself of that took quite a while...

Suffice to say (and since you're the FAQ's author, I doubt I'm telling you anything new, but I'll say it anyway):
- The _demo.txt_ file I've provided is in UTF-8, so obviously vim needs to be convinced to treat it as such
- The bug only manifests if Vim's internal encoding is UTF-8, i.e. `:set encoding=utf-8`; if instead you set it to ISO 8859-1, the file's U+0082 gets converted to a single-byte 0x82 in the buffer, which gets displayed as `~B`, which vim handles perfectly

(This digression means I haven't done the cross-platform tests I mentioned.  If they'd still be helpful, please let me know.)

**Comment by chrisbra** [comment]
ah yes I can reproduce it. Will look into it. thanks.

**Comment by chrisbra** [comment]
posted a patch [here](https://groups.google.com/forum/#!topic/vim_dev/iGUdoO0qKgQ)

**Comment by esiegerman** [comment]
That fixes it.  (Plus, the test passes :) )

Danke schön.
