### ISSUE TITLE
Tests fails on builds with disabled terminal feature

### ISSUE THREAD

**Issue by lazypingu** [vim/vim#13109]
### Steps to reproduce

1. disable the terminal feature (`./configure --enable-terminal=no`)
2. `make`
3. `make test`

### Expected behaviour

An execution of `make test` will also run the syntaxtests. Since the syntaxtest seems to require the terminal feature to be enabled, these tests will report an error if this feature is disabled.
Would it make sense to skip those tests if the terminal flag is disabled, rather than showing an error?

### Version of Vim

9.0.1901

### Environment

OS: Gentoo
Terminal: st
TERM=xtern (set for the tests)
Shell: dash

### Logs and stack traces

```shell
This will be shown after executing the tests:


...
".../vim-9.0.1901/runtime/syntax/testdir/messages" [New File]
".../vim-9.0.1901/runtime/syntax/testdir/messages" ".../vim-9.0.1901/runtime/syntax/testdir/messages" [New File] 4 lines, 176 bytes written
Error detected while processing .../vim-normal/vim-9.0.1901/runtime/syntax/testdir/runtest.vim[64]..function Fatal:
line    1:
Cannot make screendumps, aborting
"testdir/messages" 4 lines, 176 bytes

"testdir/messages" "testdir/messages" 6 lines, 211 bytes written
...
```
```

**Comment by chrisbra** [comment]
syntax tests require the screendump feature, which requires the terminal. As far as I can see, this is not an error so everything is fine.

**Comment by lazypingu** [comment]
Maybe I get this wrong, but if I disable the terminal feature these tests cannot work right?
Since these tests are executed on a normal make test, it will fail.

Is this expected and I rather should skip these tests when the terminal feature is disabled?

**Comment by chrisbra** [comment]
yes, this is required. But it doesn't fail. It just outputs that the screendump feature is required. But Make should succeed.

**Comment by lazypingu** [comment]
Yes, you right! Sorry mz fault!I just mislead myself a bit, regarding the fatal message!
Now I got it! Thanks and sorry for the noise!
