### ISSUE TITLE
[vim9script] inaccurate error message

### ISSUE THREAD

**Issue by errael** [vim/vim#13118]
### Steps to reproduce

The following produces the error
```
line   28:
E1335: Member is not writable: inner2
```
In a `:def`, the correct error is produced
```
E46: Cannot change read-only variable "value"
```

```
vim9script

class Inner
    this.value: number = 0
endclass

class Outer
    this.inner: Inner
endclass

class Outer2
    this.inner2: Outer
endclass

def F(outer: Outer)
    outer.inner.value = 1
enddef

def G(outer: Outer2)
    outer.inner2.inner.value = 1
enddef

var innerScript = Inner.new(3)
var outerScript = Outer.new(innerScript)
var outer2Script = Outer2.new(outerScript)
#outerScript.inner.value = 1     # <<<<< error message confusing
echo outer2Script.inner2.inner.value
outer2Script.inner2.inner.value = 1     # <<<<< error message confusing

#F(outerScript)
G(outer2Script)```

### Expected behaviour

Same/similar error as given in a `:def`

### Version of Vim

9.0.1909

### Environment

ubuntu

### Logs and stack traces

_No response_

**Comment by yegappan** [comment]
The error message "E1335: Member is not writable: inner2" is more accurate than "E46: Cannot change read-only variable "value"
".

In the expression "outer2Script.inner2.inner.value", the "inner2" member variable of "Outer2" cannot be used in a LHS (as it is readonly).

**Comment by errael** [comment]
> In the expression "outer2Script.inner2.inner.value", the "inner2" member variable of "Outer2" 
> cannot be used in a LHS (as it is readonly).

This doesn't make sense to me; are you saying that from outside the class that a read-only var is like `lockvar!`. Is seems the accessibility of what is being written is what should be checked. Consider the following. Why does it magically become accessible. No one will understand what's going on.

In this case Inner's val is public
```
vim9script

class Inner
  public this.val = 13
endclass

class Outer
    this.inner = Inner.new()
endclass

var o1 = Outer.new()

echo o1.inner.val

# TRY-1
var y1 = o1.inner
y1.val = 5           # <<<<< OK to write
echo o1.inner.val

# TRY-2
o1.inner.var = 3    # <<<<< can't write
echo o1.inner.val
```

And if you put the same code in a `:def`, then both the assignments work OK (as I believe they should).  But the echo needs a cast to avoid the "E715: Dictionary required", but we know that's just the way it is for now.
```
vim9script

class Inner
  public this.val = 13
endclass

class Outer
    this.inner = Inner.new()
endclass

var o1 = Outer.new()

echo o1.inner.val

def F(o: Outer)
    var y = o.inner
    y.val = 5
    echo (<Inner>o.inner).val

    o.inner.val = 3
    echo (<Inner>o.inner).val
enddef
F(o1)
```

**Comment by errael** [comment]
I guess I don't understand the rules about how something gets a type, and how that process differs depending on context.
```
Outer.F() this.inner: object<Inner>
Outer.F() this.inner: number
x: object<Inner>
Error detected while processing :source buffer=1:
line   23:
E1012: Type mismatch; expected object<Inner> but got number
```

```
vim9script

class Inner
  public this.val = 77
endclass

class Outer
    this.inner = Inner.new()

    def F()
        echo "Outer.F() this.inner:" typename(this.inner)
        this.inner = 13                               # <<<<< this doesn't get an error
        echo "Outer.F() this.inner:" typename(this.inner)
    enddef
endclass

var o = Outer.new()

o.F()

var x = Inner.new()
echo "x:" typename(x)
x = 13             # runtime error
```

**Comment by errael** [comment]
> > In the expression "outer2Script.inner2.inner.value", the "inner2" member variable of "Outer2"
> > cannot be used in a LHS (as it is readonly).
> 
> This doesn't make sense to me; are you saying that from outside the class that a read-only var is like `lockvar!`.

I guess there are two ways to look at read only variables.
```
vim9script
class A
    this.val: dict<any>    # is this like const or final?
endclass
```
Treating it like `final` seems much easier to understand (and, as a nice side effect, implement); if the programmer wants `const` behavior they can do do `lockvar`. If you treat it like `const` then to be consistent, when you do
```
var a = A.new()
var d = a.val
```
`d` should not be writable; and implementing that kind of behavior can have all kinds of weird issues.

I occurs to me if you want to punt on this issue, only allow simple types for now for read-only: number, float, bool, string, maybe others, but definitely not aggregates `list` or `dict` or `class`.

**Comment by yegappan** [comment]
> > In the expression "outer2Script.inner2.inner.value", the "inner2" member variable of "Outer2"
> > cannot be used in a LHS (as it is readonly).
> 
> This doesn't make sense to me; are you saying that from outside the class that a read-only var is like `lockvar!`. Is seems the accessibility of what is being written is what should be checked. Consider the following. Why does it magically become accessible. No one will understand what's going on.
> 

Yes.  I didn't consider the case where a read-only object variable with a complex type like
Dict or List or object can be assigned to a local variable and then modified.  This will take
some time to fix.

>
> In this case Inner's val is public
> 
> ```
> vim9script
> 
> class Inner
>   public this.val = 13
> endclass
> 
> class Outer
>     this.inner = Inner.new()
> endclass
> 
> var o1 = Outer.new()
> 
> echo o1.inner.val
> 
> # TRY-1
> var y1 = o1.inner
> y1.val = 5           # <<<<< OK to write
> echo o1.inner.val
> 
> # TRY-2
> o1.inner.var = 3    # <<<<< can't write
> echo o1.inner.val
> ```
>

**Comment by errael** [comment]
> > > In the expression "outer2Script.inner2.inner.value", the "inner2" member variable of "Outer2"
> > > cannot be used in a LHS (as it is readonly).
> > 
> > 
> > This doesn't make sense to me; are you saying that from outside the class that a read-only var is like `lockvar!`. Is seems the accessibility of what is being written is what should be checked. Consider the following. Why does it magically become accessible. No one will understand what's going on.
> 
> Yes. I didn't consider the case where a read-only object variable with a complex type like Dict or List or object can be assigned to a local variable and then modified. This will take some time to fix.

One nice thing about treating read only as `final` instead of `const`, is that the programmer can chose the semantics they want; they can convert `final` to `const` by the application of `lockvar!`; but not the other way around. If const is the way it is, I suggest only primitive types be allowed (at least for now). It might be useful to delineate the behavior in various situations and solicit feedback, perhaps in a discussion. 

I was surprised by `const` rather than `final`, I could be in the minority. As much as I try to read between the lines of the spec, there's little about the semantics of read only as a point of consideration.

**Comment by yegappan** [comment]
> > > > In the expression "outer2Script.inner2.inner.value", the "inner2" member variable of "Outer2"
> > > > cannot be used in a LHS (as it is readonly).
> > > 
> > > 
> > > This doesn't make sense to me; are you saying that from outside the class that a read-only var is like `lockvar!`. Is seems the accessibility of what is being written is what should be checked. Consider the following. Why does it magically become accessible. No one will understand what's going on.
> > 
> > 
> > Yes. I didn't consider the case where a read-only object variable with a complex type like Dict or List or object can be assigned to a local variable and then modified. This will take some time to fix.
> 
> One nice thing about treating read only as `final` instead of `const`, is that the programmer can chose the semantics they want; they can convert `final` to `const` by the application of `lockvar!`; but not the other way around. If const is the way it is, I suggest only primitive types be allowed (at least for now). It might be useful to delineate the behavior in various situations and solicit feedback, perhaps in a discussion.
> 
> I was surprised by `const` rather than `final`, I could be in the minority. As much as I try to read between the lines of the spec, there's little about the semantics of read only as a point of consideration.

In the current implementation the read-only object variable behaves like a "final" variable.
The documentation needs to be updated to reflect this.  It is simpler to support the "final" model
with complex types as object variables than trying to make them really read-only.

**Comment by errael** [comment]
Closed by recent commits. See #13135 and  #13136 for following up about error messages.
