### ISSUE TITLE
Exiting completion menu results in unexpected change

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#1312]
Hello,

If I write the following in `/tmp/vimrc.vim`:
```
setlocal tw=78 cc=78
"                                                        zzz
" zzzyyyyyyyyyyyyyyyyyyy
```

Then I launch Vim from the shell like this:

    vim -Nu /tmp/vimrc.vim /tmp/vimrc.vim

Finally, in insert mode I position the cursor after `zzz` on the second line, hit `<C-x><C-n>` to open the completion menu in which the only suggestion is `zzzyyyyyyyyyyyyyyyyyyy`, hit `<C-e>` to exit, here's the result:

```
setlocal tw=78 cc=78
"
zzzyyyyyyyyyyyyyyyyyyyzzz
" zzzyyyyyyyyyyyyyyyyyyy
```

I expected the buffer to not change since I exited the menu. Besides `zzz` is inserted twice.

I'm using Vim version 8.0 (patches 1-124 included) in linux, and xfce4-terminal.

**Comment by vim-ml** [comment]
Hi lacygoill,

2016-12-7(Wed) 13:26:25 UTC+9 lacygoill:
> Hello,
> 
> If I write the following in /tmp/vimrc.vim:
> 
> setlocal tw=78
> setlocal cc=78
> 
> "                                                        zzz
> " zzzyyyyyyyyyyyyyyyyyyy
> 
> 
> 
> Then I launch Vim from the shell like this:
> vim -Nu /tmp/vimrc.vim /tmp/vimrc.vim
> 
> 
> Finally, in insert mode I position the cursor after zzz, hit <C-x><C-n> to open the completion menu, hit and <C-e> to exit, here's the result:
> setlocal tw=78
> setlocal cc=78
> 
> "
> zzzyyyyyyyyyyyyyyyyyyyzzz
> " zzzyyyyyyyyyyyyyyyyyyy
> 
> 
> I expected the buffer to not change since I exited the menu. Besides zzz is inserted twice.

I can reproduce it.
Please confirm attached patch.
When confirming is okay, I'll write a test later.  (Maybe write on the weekend :-)

Thanks for the reporting.
--
Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by lacygoill** [comment]
Thank you very much for the answer! I'm sorry I don't know much about git and programming. I don't know where to find the patch and how to apply it. I just found this bug and wanted to report it to you. Again sorry for my lack of knowledge, and thank you very much for your work on Vim!

**Comment by vim-ml** [comment]
Hi lacygoill,

2016-12-8(Thu) 1:03:00 UTC+9 lacygoill:
> Thank you very much for the answer! I'm sorry I don't know much about git and programming. I don't know where to find the patch and how to apply it.. I just found this bug and wanted to report it to you. Again sorry for my lack of knowledge, and thank you very much for your work on Vim!

Do not mind.😊
I think my patch is correct. Maybe :-)
And, Bram and other developers will judge the validity of this patch.

--
Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by vim-ml** [comment]
Op 7 dec. 2016 17:03 schreef "lacygoill" <vim-dev-github@256bit.org>:

I don't know where to find the patch and how to apply it..

If it's correct, it will be applied by Bram Moolenaar and distributed in an
official version. You'll just have to wait...

Christ van Willegen

**Comment by brammool** [comment]
> If I write the following in `/tmp/vimrc.vim`:
> ```
> 
> setlocal tw=78
> setlocal cc=78
> 
> "                                                        zzz
> " zzzyyyyyyyyyyyyyyyyyyy
> 
> ```
> 
> Then I launch Vim from the shell like this:
> 
>     vim -Nu /tmp/vimrc.vim /tmp/vimrc.vim
> 
> Finally, in insert mode I position the cursor after `zzz`, hit `<C-x><C-n>` to open the completion menu, hit and `<C-e>` to exit, here's the result:
> 
> ```
> setlocal tw=78
> setlocal cc=78
> 
> "
> zzzyyyyyyyyyyyyyyyyyyyzzz
> " zzzyyyyyyyyyyyyyyyyyyy
> ```
> 
> I expected the buffer to not change since I exited the menu. Besides
> `zzz` is inserted twice.

Looks like a bug.

-- 
Where do you want to crash today?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
Hi Bram and all,

2016-12-8(Thu) 7:08:32 UTC+9 Bram Moolenaar:
> > If I write the following in `/tmp/vimrc.vim`:
> 
> > ```
> 
> > 
> 
> > setlocal tw=78
> 
> > setlocal cc=78
> 
> > 
> 
> > "                                                        zzz
> 
> > " zzzyyyyyyyyyyyyyyyyyyy
> 
> > 
> 
> > ```
> 
> > 
> 
> > Then I launch Vim from the shell like this:
> 
> > 
> 
> >     vim -Nu /tmp/vimrc.vim /tmp/vimrc.vim
> 
> > 
> 
> > Finally, in insert mode I position the cursor after `zzz`, hit `<C-x><C-n>` to open the completion menu, hit and `<C-e>` to exit, here's the result:
> 
> > 
> 
> > ```
> 
> > setlocal tw=78
> 
> > setlocal cc=78
> 
> > 
> 
> > "
> 
> > zzzyyyyyyyyyyyyyyyyyyyzzz
> 
> > " zzzyyyyyyyyyyyyyyyyyyy
> 
> > ```
> 
> > 
> 
> > I expected the buffer to not change since I exited the menu. Besides
> 
> > `zzz` is inserted twice.
> 
> 
> 
> Looks like a bug.

I update a patch.
Added a test.
I checked that it's okay with patch, and fail without patch👍
Check it please.

--
Best regards,
Hirohito Higashi (a.k.a. h_east)
