### ISSUE TITLE
meaning of ' "tiling.js" 5114L, 155880C written' 

### ISSUE THREAD

**Issue by nelsonleemax** [vim/vim#13139]
For at least 20 years I have assumed that text like the line

"tiling.js" 5114L, 155880C written

at the bottom line of my vi screen meant that the most recent changes had been written to a file, but today I finally realized that this line disappears only when the bottom line is used for another purpose, like for a search string.

**Describe the solution you'd like**

I would like this line to disappear when any changes are made to the file being edited

**Describe alternatives you've considered**

In my personal case, I now know that my assumption was incorrect. But in case other people make the same assumption, I think it would still be a good idea to remove this line when changes have been made to the edited text.

**Additional context**

**Comment by chrisbra** [comment]
the simple solution is to e.g. set `:set showmode`, which will make the message disappear once you change the mode (which typically happens when you change your file again).

**Comment by nelsonleemax** [comment]
Thanks for the quick reply. Yes, that worked. You answered my question.
Please close/delete this case.
