### ISSUE TITLE
git commit --amend cat't delete text

### ISSUE THREAD

**Issue by VarusHsu** [vim/vim#13143]
### Steps to reproduce

I use `git commit --amend`, then terminal auto open vim
   
<img width="483" alt="image" src="https://github.com/vim/vim/assets/85171099/3294f561-39b6-44b7-9b63-7cc928780d7e">
I switch to INSERT mode, but I can't delete previous text by use keyboard 'delete'.
But `dd` cant delete it;

### Expected behaviour

INSERT mode text should can be delete.

### Version of Vim

9.0.1544

### Environment

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jun 23 2023 22:12:29)
macOS version - arm64

**Comment by chrisbra** [comment]
Make sure you are in non-compatible mode

**Comment by k-takata** [comment]
Use `:verbose set backspace?` to see if 'backspace' is correctly set or not.

Anyway, I think this is the issue of your settings, not the issue of Vim. 
Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. Closing.
