### ISSUE TITLE
test_crypt.vim:  assert_match() doesn't work properly with double-quote string

### ISSUE THREAD

**Issue by svardew** [vim/vim#13150]
### Steps to reproduce

./configure --enable-libsodium
make
cd src/testdir/
make test_crypt.res TEST_FILTER=Test_uncrypt_xchacha20

### Expected behaviour

Test_uncrypt_xchacha20_2, L258 assert_match() intend to check if messages contain [xchacha20] after write buffer.
But pattern "\[xchacha20\]" is dboule-quoted, `\[` is not escaped,
so pattern parsed to /[achx02]/ character collection, assertion is not correct.
this pattern matches `disabling swap file` message line.
For literally match, single-quoted `'\[xchacha20v2\]'` is better.
https://github.com/vim/vim/blob/ceee7a808ce82b0c6bd84e0b6fc1dfb0475c99aa/src/testdir/test_crypt.vim#L251-L259

Test_uncrypt_xchacha20v2_2, L291 assert_match() ditto.
And pattern string may [xchacha20v2].
For literally match, single-quoted `'\[xchacha20v2\]'` is better.
https://github.com/vim/vim/blob/ceee7a808ce82b0c6bd84e0b6fc1dfb0475c99aa/src/testdir/test_crypt.vim#L280-L292

### Version of Vim

v9.0.1910

### Environment

OS: ubuntu 16.04
Terminal: gnome-terminal 3.18.3
$TERM: xterm-256color
Shell: bash 4.3.48

**Comment by chrisbra** [comment]
can you create a PR please?

**Comment by svardew** [comment]
@chrisbra 
PR https://github.com/vim/vim/pull/13151

**Comment by zeertzjq** [comment]
This has been fixed by patch 9.0.1936
