### ISSUE TITLE
Initializing formal parameters are available to all methods

### ISSUE THREAD

**Issue by dkearns** [vim/vim#13152]
### Steps to reproduce

Is it intended that this works?

```vim
vim9script

class Foo
  this.foo: number
  def SetFoo(this.foo)
  enddef
  def GetFoo(): number
    return this.foo
  enddef
endclass

var f = Foo.new()
f.SetFoo(42)
echomsg f.GetFoo()
```

### Expected behaviour

I don't feel strongly about it one way or the other but allowing this feature is normally (from a brief survey of other languages) only available in constructors.

### Version of Vim

9.0.1927

### Environment

Ubuntu 20.04

**Comment by dkearns** [comment]
I just noticed that @h-east has also mentioned this in #13113.  Fluke or burning issue requiring immediate attention?

**Comment by errael** [comment]
>  Fluke or burning issue requiring immediate attention?

Both?
