### ISSUE TITLE
E108: No such variable: "s:matchit_patterns"

### ISSUE THREAD

**Issue by goblinrieur** [vim/vim#13162]
### Steps to reproduce

1.  get vim 9.0 
![image](https://github.com/vim/vim/assets/89040636/1940a296-1cb4-49cf-947f-c5333483bf42)
2. kept .vimrc unchanged form a 8.* vim version 
![image](https://github.com/vim/vim/assets/89040636/50bac773-adb8-4360-94f8-eea769ef676f)
4.  open an existing  gnu-forth script file, sould be a .fs file 
5. get error 
![image](https://github.com/vim/vim/assets/89040636/abefe5f8-6247-4d36-bc69-59e28974a3cf)
6. press enter then opens vim 

### Expected behaviour

This message should not exist and just open files with options from viwrc as syntax on and so on 
previously it was just opened files properly  _(while using 8 version I guess)_ even those files

### Version of Vim

 version 9.0.1894

### Environment

Debian GNU/Linux trixie/sid x86_64
GNU bash, version 5.2.15(1)-release
term :  xterm-256color  _(same behavor on any xterm & tmux too)_
vim: 
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Sep 11 2023 13:22:50)
Included patches: 1-1894
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
-balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +gettext           +num64             +textobjects
-browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     -perl              +title
+channel           +ipv6              +persistent_undo   -toolbar
+cindent           +job               +popupwin          +user_commands
-clientserver      +jumplist          +postscript        +vartabs
-clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           -python            +viminfo
+cmdline_info      +libcall           -python3           +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
+cscope            +localmap          -ruby              +wildignore
+cursorbind        -lua               +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con        +mksession         +smartindent       +writebackup
+diff              +modify_fname      +sodium            -X11
+digraphs          +mouse             -sound             -xfontset
-dnd               -mouseshape        +spell             -xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        +mouse_gpm         +statusline        -xsmp
+eval              -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary        
-farsi             -mouse_sysmouse    -tag_old_static    
   system vimrc file: "/etc/vim/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -Wdate-time -g -O2 -ffile-prefix-map=/build/reproducible-path/vim-9.0.1894=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -DSYS_VIMRC_FILE=\"/etc/vim/vimrc\" -DSYS_GVIMRC_FILE=\"/etc/vim/gvimrc\" -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: gcc -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim -lm -ltinfo -lselinux -lsodium -lacl -lattr -lgpm

**Comment by dkearns** [comment]
That was fixed in c1f8bb37c6a8e0babc2a41f16860763b57c23fa1

Sorry for the irritation.

**Comment by goblinrieur** [comment]
I confirm that was the point 
now its ok  after update to version 9.0.1927
