### ISSUE TITLE
public modifier allowed in static but not object method declarations

### ISSUE THREAD

**Issue by dkearns** [vim/vim#13184]
### Steps to reproduce

```vim
class A
  def Foo()
  enddef
  public def Bar()
  enddef
endclass
```

Executing this script results in an error: `E1331: Public must be followed by "this" or "static"`

```vim
class A
  static def Foo()
  enddef
  public static def Bar()
  enddef
endclass
```
No error is output.

### Expected behaviour

Class and object method declarations should exhibit the same behaviour with regard to the `public` modifier's presence or absence.

### Version of Vim

9.0.1941

### Environment

Ubuntu 20.04

**Comment by yegappan** [comment]
This issue should be addressed in the latest Vim.  Can you try the latest version?

**Comment by yegappan** [comment]
This issue should be fixed now.  Can you try the latest version and close this issue?

**Comment by dkearns** [comment]
Sorry, I missed your comment last week. 

In 9.0.2018 I see `E1331: Public must be followed by "this" or "static"` for object methods and `E1388: Public keyword not supported for a method` for class methods.

Shouldn't they be the same error message, or at least very similar?  I think `Public` should also be lower case.
