### ISSUE TITLE
List of implemented interfaces does not require whitespace like other lists

### ISSUE THREAD

**Issue by dkearns** [vim/vim#13185]
### Steps to reproduce

```vim
interface I
endinterface
interface J
endinterface

class A implements I,J
endclass
```

### Expected behaviour

An error message: `E1069: White space required after ',': ,J`

Vim9 requires strict whitespace separation of list items so this should also be required for a list of implemented interfaces.

### Version of Vim

9.0.1941

### Environment

Ubuntu 20.04

**Comment by chrisbra** [comment]
fixed by 2dede3dbfa3cb52f464f942d46d3ec0f66e3e354
