### ISSUE TITLE
typescript syntax highlight broken

### ISSUE THREAD

**Issue by eyebrowkang** [vim/vim#13199]
### Steps to reproduce

1. download this file: [codemirror.ts](https://raw.githubusercontent.com/codemirror/basic-setup/main/src/codemirror.ts)
2. run `echo 'filetype on\nsyntax enable' > .vimrc`
3. put the `.vimrc` file to right place(normally home directory)
4. open the `codemirror.ts` file
5. press `G` to the end of file

### Expected behaviour

The file should be highlight, and the process jump to the end should be smooth.

### Version of Vim

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jun 23 2023 22:11:46)

### Environment

macOS version - x86_64
Included patches: 1-1544
Compiled by root@apple.com
Terminal iTerm2 Build 3.4.20

**Comment by chrisbra** [comment]
cannot reproduce. BTW: you can simply use `vim --clean codemirror.ts`. Can you please check with an updated Vim version?
