### ISSUE TITLE
vim9script: Error with import autoload

### ISSUE THREAD

**Issue by Raimondi** [vim/vim#13198]
### Steps to reproduce

Create the following files:

autoload/a.vim
```` vim
vim9script
````
autoload/b.vim
````vim
vim9script
import './a.vim'
export def F(): void
enddef
````
plugin/p.vim
````vim
vim9script
import autoload 'a.vim'
import autoload 'b.vim'
````

run this command:
````sh
vim -u NONE -i NONE --cmd "set rtp=$PWD" -c 'runtime plugin/p.vim' -c 'call b#F()'
````

### Expected behaviour

Should not get an error, but get the following:
````
Error detected while processing command line..script /Users/israel/Source/vim/local/autoload/b.vim:
line    2:
E1053: Could not import "./a.vim"
Error detected while processing command line:
E117: Unknown function: b#F
Press ENTER or type command to continue
````
if I replace line 2 of p.vim with
````vim
import '../autoload/a.vim'
````
I get no errors.

### Version of Vim

9.0.1943

### Environment

Operating system: macOS 13.1
Terminal iTerm2 3.4.20
Value of $TERM: tmux-256color
Shell:  Fish 3.6.1

**Comment by Raimondi** [comment]
It would be nice for the error to give any details about why vim couldn't import the script.

**Comment by errael** [comment]
@Raimondi @chrisbra @yegappan I didn't try this before recent changes (which shouldn't have had any affect on this). But in any event this works now AFAICT.

**Comment by chrisbra** [comment]
closing then, thanks!
