### ISSUE TITLE
The ability to search in VIM using Python regex

### ISSUE THREAD

**Issue by Remiol** [vim/vim#13194]
For a long time I was unsure about what to focus on in vim; vimscript or python.
Because I have been using Python for years, and find it very user-friendly, I chose to code any additional functions primarily in Python.

```
python << eol
import vim
Python code
eol
```

What someone wrote on the internet is true. VIM and Python is a match made in heaven.
Thank you very much for this opportunity.

In my opinion, something is still missing to integrate the two even better: The ability to search in Vim using Python Regex.
Is it possible in the future to add the option to search in Vim using Python Regex?

**Comment by chrisbra** [comment]
That is hardly possible, as the Vim regexes contain stuff, that python regexes have no equivalent for (think of marks, cursor position, different engine, etc). But perhaps you just want to use `very magic` patterns using the `\v` regex atom? But there will always be differences.

**Comment by Remiol** [comment]
Thank you for your reply.

That's true but sometimes these options are not necessary. Perhaps Python regex can be separated from Vimscript so they can both be used.
E.g. 
`/vim search regex`
`/py python search regex` 

Or even an option in settings to disable the vim search regex completely and enable the python search regex.

I have been using vim for many years but am still more at ease with Python regex than Vim regex.

I am aware that a number of possibilities will be lost, but perhaps it will be an incentive for a number of people who do not yet use Vim to use Vim. I think many people are actually put off by vimscript (as did I in the beginning). It has a steep learning curve mainly because people do not know vimscript and do not want to learn another programming language.

**Comment by chrisbra** [comment]
If you are using `:set number` you are already using vimscript. There is nothing to be afraid of. I also personally am not convinced, that adding yet another regex engine will help but rather lead to much more subtle and hard to reproduce bugs. 

I really invite you, to please have a look at `:h pattern.txt` and skim over the various regex atoms. They are not so hard to learn, memorize (or even lookup).

**Comment by chrisbra** [comment]
I am closing this, as this is potentially a lot of effort, introduces incompatibilities and I am not sure it is worth the gain here.

**Comment by k-takata** [comment]
Maybe you can use https://github.com/othree/eregex.vim or some other plugins?
Anyway, closing.
