### ISSUE TITLE
Can we fix `Could not resolve host: vim.org`?

### ISSUE THREAD

**Issue by stefanos82** [vim/vim#13202]
Works on my side via Firefox-ESR 115.2.0esr (64-bit):

```
Not Before Sat, 26 Aug 2023 23:34:41 GMT
Not After  Fri, 24 Nov 2023 23:34:40 GMT
```

Seems like the Apache settings are a bit messed up...

```
stefanos@debian:~ $ curl -IL vim.org
curl: (6) Could not resolve host: vim.org

stefanos@debian:~ $ curl -IL www.vim.org
HTTP/1.1 302 Found
Date: Tue, 12 Sep 2023 22:10:38 GMT
Server: Apache/2.4.10 (Debian)
Location: https://www.vim.org/
Content-Type: text/html; charset=iso-8859-1

curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

stefanos@debian:~ $ curl -IL http://www.vim.org
HTTP/1.1 302 Found
Date: Tue, 12 Sep 2023 22:10:47 GMT
Server: Apache/2.4.10 (Debian)
Location: https://www.vim.org/
Content-Type: text/html; charset=iso-8859-1

curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

stefanos@debian:~ $ curl -IL https://vim.org
curl: (6) Could not resolve host: vim.org

stefanos@debian:~ $ curl -IL https://www.vim.org
HTTP/1.1 200 OK
Date: Tue, 12 Sep 2023 22:11:03 GMT
Server: Apache/2.4.10 (Debian)
Content-Type: text/html
Content-Language: ja
```

_Originally posted by @stefanos82 in https://github.com/vim/vim/issues/13079#issuecomment-1716585425_

**Comment by chrisbra** [comment]
This has been discussed before. It's currently not being done and it has been workign like this for a very long time. Usually browser redirect to `www.vim.org` automatically nowadays anyway so I don't consider this a big problem.

**Comment by stefanos82** [comment]
You mean this type of redirection?

![image](https://github.com/vim/vim/assets/1777466/9df7244d-615b-49d8-b59a-f6be17741f57)

**Comment by stefanos82** [comment]
Interesting...my version is `115.2.1esr (64-bit)` if it helps. I'm using GNU / Linux Debian testing 64-bit.

`curl` complains too:

![image](https://github.com/vim/vim/assets/1777466/7a07056c-f3b2-40b3-a85b-f51f24f8d7a7)

`elinks` the same:

![image](https://github.com/vim/vim/assets/1777466/dc0a39a9-d97b-4f94-80b5-46e82ec29271)

**Comment by stefanos82** [comment]
...OK...seems like there's no interest in fixing such issue.
