### ISSUE TITLE
Scrolling inactive window with 'cursorbind' is inconsistent

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#13210]
### Case 1
1. Run `vim --clean` with two splits and 'cursorbind', 'noscrollbind', and non-zero 'scrolloff':
```vim
call setline(1, range(1, 8))
vnew
call setline(1, range(1, 8))
windo set cursorbind noscrollbind scrolloff=1
```
2. Scroll the left split using mouse
3. Nothing happens

### Case 2
1. Run `vim --clean` with two splits and 'cursorbind', 'noscrollbind', and zero 'scrolloff':
```vim
call setline(1, range(1, 8))
vnew
call setline(1, range(1, 8))
windo set cursorbind noscrollbind scrolloff=0
```
2. Scroll the left split using mouse
3. The left split scrolls, while its cursor doesn't move (and is therefore out of screen)

### Case 3
1. Run `vim --clean` with two splits and 'cursorbind', 'scrollbind', and non-zero 'scrolloff':
```vim
call setline(1, range(1, 8))
vnew
call setline(1, range(1, 8))
windo set cursorbind scrollbind scrolloff=1
```
2. Scroll the left split using mouse
3. The left split scrolls, while its cursor doesn't move (and is therefore out of screen)

### Case 4
1. Run `vim --clean` with two splits and 'cursorbind', 'scrollbind', and zero 'scrolloff':
```vim
call setline(1, range(1, 8))
vnew
call setline(1, range(1, 8))
windo set cursorbind scrollbind scrolloff=0
```
2. Scroll the left split using mouse
3. The left split scrolls, while its cursor doesn't move (and is therefore out of screen)

### Expected behaviour

The behavior in the four cases should be the same

### Version of Vim

9.0.1882

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

**Comment by zeertzjq** [comment]
This happens because:
- When 'scrollbind' is set, `do_check_cursorbind()` moves back the left split's cursor but doesn't call `validate_cursor()`, so it doesn't scroll the left split back to its original position.
- When 'scrollbind' is not set, `do_check_cursorbind()` calls `validate_cursor()`, and
  - When 'scrolloff' is zero, `scroll_redraw()` doesn't call `cursor_correct()` (and `validate_cursor()`) when scrolling using mouse, so `w_valid_cursor` has the cursor position before scrolling with mouse, and `validate_cursor()` doesn't scroll back when `do_check_cursorbind()` moves back the left split's cursor.
  - When 'scrolloff' is non-zero, `scroll_redraw()` calls `cursor_correct()` (and `validate_cursor()`) when scrolling using mouse, so `w_valid_cursor` has the cursor position after scrolling with mouse, and `validate_cursor()` scroll back when `do_check_cursorbind()` moves back the left split's cursor.

**Comment by zeertzjq** [comment]
OTOH, the help for 'cursorbind' doesn't mention what should happen when the another cursorbound window's cursor moves while the current window's cursor doesn't move, so another possible behavior is that the left split scrolls and moves its cursor so that it's not out of screen. This is similar to `:h scrolling-quickadj` but for 'cursorbind'.

**Comment by zeertzjq** [comment]
On the other hand, the help for 'cursorbind' doesn't mention what should happen when the another cursorbound window's cursor moves while the current window's cursor doesn't move.
```
			*'cursorbind'* *'crb'* *'nocursorbind'* *'nocrb'*
'cursorbind' 'crb'	boolean  (default off)
			local to window
	When this option is set, as the cursor in the current
	window moves other cursorbound windows (windows that also have
	this option set) move their cursors to the corresponding line and
	column.  This option is useful for viewing the
	differences between two versions of a file (see 'diff'); in diff mode,
	inserted and deleted lines (though not characters within a line) are
	taken into account.
```
So another possible behavior is that the left split scrolls and moves its cursor so that it's not out of screen. This is similar to `:h scrolling-quickadj` but for 'cursorbind'.

**Comment by zeertzjq** [comment]
So another possible behavior is that the left split scrolls and moves its cursor so that it's not out of screen.

This can be achieved by avoiding moving cursor for 'cursorbind' if current window and cursor didn't change:
```diff
diff --git a/src/move.c b/src/move.c
index 9c025d42b..168497e3c 100644
--- a/src/move.c
+++ b/src/move.c
@@ -3570,6 +3570,14 @@ halfpage(int flag, linenr_T Prenum)
     void
 do_check_cursorbind(void)
 {
+    static win_T *prev_curwin = NULL;
+    static pos_T prev_cursor = {0, 0, 0};
+
+    if (curwin == prev_curwin && EQUAL_POS(curwin->w_cursor, prev_cursor))
+	return;
+    prev_curwin = curwin;
+    prev_cursor = curwin->w_cursor;
+
     linenr_T	line = curwin->w_cursor.lnum;
     colnr_T	col = curwin->w_cursor.col;
     colnr_T	coladd = curwin->w_cursor.coladd;
@@ -3587,7 +3595,7 @@ do_check_cursorbind(void)
     FOR_ALL_WINDOWS(curwin)
     {
 	curbuf = curwin->w_buffer;
-	// skip original window  and windows with 'noscrollbind'
+	// skip original window and windows with 'nocursorbind'
 	if (curwin != old_curwin && curwin->w_p_crb)
 	{
 # ifdef FEAT_DIFF
```

**Comment by zeertzjq** [comment]
> So another possible behavior is that the left split scrolls and moves its cursor so that it's not out of screen.

This seems to be the behavior of GUI vertical scrollbar.

**Comment by chrisbra** [comment]
so I tested your 4 in guiy and terminal. So basically except for the first example, the others behave the same and consistent, right?

And your patch makes example 1 behave similar and consistent to the other 3 examples? At least that's what it seems to me after testing this out.

**Comment by zeertzjq** [comment]
Actually there is a slight difference: #13219 keeps the cursor in the inactive window on screen instead of moving it off screen for 'cursorbind', whereas in the other three examples the cursor in the inactive window is moved off screen without scrolling the window. That's why I'm not sure about it, but I also think moving cursor off screen without scrolling the window will be hacky.

**Comment by zeertzjq** [comment]
The behavior is also different when using GUI vertical scrollbar: after scrolling the inactive window using vertical scrollbar the behavior is similar to the one in #13219, but pressing any key afterwards moves cursor and viewport back.

**Comment by zeertzjq** [comment]
Actually there is another problem in the three other cases: cursor in the inactive window remain off screen when cursor in the current window moves in the same line. If cursor moves to another line then the other window scrolls back. #13219 fixes this for case 2, but not for cases 3 and 4 where 'scrollbind' is more important.

**Comment by chrisbra** [comment]
I still don't understand fully. Your patch seems to fix issue 1, which is the most serious one. But what do you mean with the cursor moves out of the window? I mean, the cursor is not visible in the inactive window, so not sure I understand. I tried withe `:set cursorline` but the cursorline always remains visible, so I might still be missing something

**Comment by zeertzjq** [comment]
Here I mean that the cursor position shown in the 'ruler' of the inactive window (and the one that can be obtained use `getcurpos()`) is above the topline of the window.

**Comment by chrisbra** [comment]
Ah I see. I think in this case your patch makes sense and the other minor issues are more or less okay and can be explained by the 'scrollbind' setting.
