### ISSUE TITLE
Extra line break visible after indent when settings `wrap`, `linebreak` and `breakindent` are enabled

### ISSUE THREAD

**Issue by EtiamNullam** [vim/vim#13228]
### Steps to reproduce

```vim
vim -u NONE
:set wrap linebreak breakindent
ia<Esc>
1000.
V>
```

It looks like this (screenshot comes from neovim, but behavior is the same):

![image](https://github.com/vim/vim/assets/10875340/9ed47777-0956-48f4-bc0d-baacd7fc87c9)

As you can see text starts in the second line, but it might as well start in the first one.

### Expected behaviour

There should be no line break between whitespaces and the text and it should look just like linebreak is disabled in this case.

It should look like this:

![image](https://github.com/vim/vim/assets/10875340/c28b7d28-140e-4e80-b4cc-9683f2164f6b)

### Version of Vim

9.0

### Environment

Operating system: Windows 10
Terminal: cmder 1.3.21
Shell: cmd, powershell

### Logs and stack traces

```shell
N/A
```

**Comment by chrisbra** [comment]
Well, the linebreak setting tells Vim to break at the white space. And there is no whitespace once the `a`s start.

**Comment by EtiamNullam** [comment]
I'm sorry if I didn't describe the problem well.

I understand that a long `word` without whitespaces or `breakat` characters will have to fallback to just wrapping anywhere but that's not the point.

The problem is that a virtual line break appears between a sequence of whitespaces characters and text, even if it won't give any extra space to the text due to `breakindent`.

Consider this example, where I've set `list` and `listchars` to display spaces as `+`:

![image](https://github.com/vim/vim/assets/10875340/feebc94f-92ac-462d-9c53-92e66e42ea88)

Cursor is positioned at the last whitespace that precede the long text. The long text begins one column to the right and one row down (which is just one character to the right). It could simply start in the same row. Wrapping in this case is unnecessary.

**Comment by chrisbra** [comment]
I understand what you are pointing out, but you are seeing correct behaviour. In short what `linebreak` option does is, it sees some whitespace. Vim then checks, if the next consequitive list of characters (that are not in `breakat`, so lets just call them letters for now) fits into the rest of the screen line. If it does, those letters will be printed on the line and on the next whitespace or `breakat` characters, it will perform the check again. 

In your case, the rest of following letters does not fit into the rest of the screen line, so it needs to wrap at the space right now. And that's what Vim does. So if you don't want that behaviour, then do not set the `linebreak` option in the first place.
