### ISSUE TITLE
The GUI executables available on the Vim website, do NOT have the syntax directory

### ISSUE THREAD

**Issue by aks2161989** [vim/vim#13233]
The zip files of the GUI and GUI OLE executables on the Vim website (not the installer or the .zip files of the entire Vim distribution) are missing the syntax directory. So I keep getting an error when launching gvim that it cannot find syntax.vim (because it isn't there).

ALSO, any `:h` command fails because the help files seem to be missing too

**Comment by chrisbra** [comment]
You mean those?
![image](https://github.com/vim/vim/assets/244927/58cbb274-638b-4aa4-892c-0a66a47db9bf)

As the website mentions, this only contains the *executable* it misses the whole runtime directory. You should rather go with the installation from [vim-win32-installer repository](https://github.com/vim/vim-win32-installer)

**Comment by chrisbra** [comment]
See also this one, just right above the screenshot:
![image](https://github.com/vim/vim/assets/244927/5d1f6f79-e700-4395-993b-49b94fedd1e4)


So you need to get the runtime files **in addition** to the binary files you already downloaded.

**Comment by aks2161989** [comment]
@chrisbra Oh I see. Thank you
