### ISSUE TITLE
Python 3: subprocess is broken on Windows

### ISSUE THREAD

**Issue by AlexMasterov** [vim/vim#1324]
What a strange behavior of..?

### Example
* Windows 10 (14986)
* Python 3.5.2
* (g)Vim 8 (1-109)
* grep and grep-like tool: [rg](https://github.com/BurntSushi/ripgrep), [ag](https://github.com/ggreer/the_silver_searcher) and etc.

**grep.js**
```javascript
const message = 'grepme';
```

**proc.py**
```python
import subprocess
import os

class Process():
    def __init__(self, commands):
        cwd = None
        startupinfo = None
        if os.name == 'nt':
            startupinfo = subprocess.STARTUPINFO()
            startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
        proc = subprocess.Popen(commands,
                                stdout=subprocess.PIPE,
                                stderr=subprocess.PIPE,
                                startupinfo=startupinfo,
                                cwd=cwd)
        print(proc.communicate())

Process(['rg', '--version'])
Process(['rg', '--vimgrep', '--no-heading', '--', 'grepme'])
```

### Output

**cmd**
```cmd
python proc.py
(b'ripgrep 0.3.2\n', b'')
(b"grep.js:1:18:const message = 'grepme';\nproc.py:57:52:Process(['rg', '--vimgrep', '--no-heading', '--', 'grepme'] )\n", b'')
```
**Vim**
```viml
:py3file proc.py<CR>
(b'ripgrep 0.3.2\n', b'')
(b'', b'')
```

**Comment by chrisbra** [comment]
is this only broken on Windows?

**Comment by AlexMasterov** [comment]
@chrisbra currently tested only on Windows.

Which is odd, this case does not work only in Vim version for GUI.
Vim version for console works fine on Windows and Linux.

**Comment by char101** [comment]
Works for me. You need to chdir to where grep.js is located first.

**Comment by AlexMasterov** [comment]
@char101 please describe more details.

What's your Windows environment and GVim version?

**Comment by char101** [comment]
Gvim 8.0.124, Windows 7, Python 3.5.2, compiled with VS 2015

![gvim](https://cloud.githubusercontent.com/assets/71255/21285335/222c48ae-c468-11e6-8588-607138daf8c8.png)

**Comment by char101** [comment]
Oh, I can actually reproduce that when the filename is omitted. But it works when the filename is given on the command line, e.g.

`Process(['rg', '--vimgrep', '--no-heading', '--', 'grepme', 'grep.js', 'proc.py'])`

**Comment by AlexMasterov** [comment]
I have tested. It works when specifying the directory.

@char101 thank you.

**Comment by char101** [comment]
So I run process monitor and it seems that rg looks for '-' when the file is not specifed. Maybe rg can detect that it was being piped when run from vim/python but instead of reading from stdin it treats - as the filename.

![rg2](https://cloud.githubusercontent.com/assets/71255/21285425/865d4f10-c46a-11e6-8579-a1ff9811203c.png)

**Comment by AlexMasterov** [comment]
Actually I knew that on Windows for such tools need to specify a directory ([dot as current directory](https://github.com/Shougo/denite.nvim/issues/98#issuecomment-264646889)). 
But grep.. 

Thanks for the hint.
