### ISSUE TITLE
 Highlight Group `Folded` Highlighting is Inconsistent With Regards To wincolor

### ISSUE THREAD

**Issue by incbin** [vim/vim#13245]
### Steps to reproduce

gVim invoked from cmd.exe
`echo Warning\n{{{\ncontents\n}}}\n | gvim.exe - --clean -c "%s/\\n/\r/g | set foldmethod=marker | hi! Normal ctermfg=White ctermbg=DarkGray guifg=White guibg=DarkGray | syn keyword Warning Warning | hi Warning ctermfg=Red guifg=Red | hi clear Folded | hi! Folded ctermfg=Red guifg=Red | vsplit | wincmd l | hi! WinColorNormal ctermfg=White ctermbg=DarkBlue guifg=White guibg=DarkBlue | set wincolor=WinColorNormal"`

Vim invoked from bash
`echo "Warning\n{{{\ncontents\n}}}\n" | vim - --clean -c "%s/\\\\n/\\r/g | set foldmethod=marker | hi! Normal ctermfg=White ctermbg=DarkGray guifg=White guibg=DarkGray | syn keyword Warning Warning | hi Warning ctermfg=Red guifg=Red | hi clear Folded | hi! Folded ctermfg=Red guifg=Red | vsplit | wincmd l | hi! WinColorNormal ctermfg=White ctermbg=DarkBlue guifg=White guibg=DarkBlue | set wincolor=WinColorNormal"`

![image](https://github.com/vim/vim/assets/79929299/ca121ce2-7885-4608-95d3-fb0fca01d628)

![image](https://github.com/vim/vim/assets/79929299/c7862ad0-1f28-4de5-904a-f72f7bcf58f8)

Also observed in gVim / Vim when Folded highlighting is set via:
`hi clear Folded | hi! link Folded Warning`

And in gVim when Folded highlighting is set via:
`hi clear Folded | hi! Folded guifg=foreground guibg=background`

### Expected behaviour

I believe the fold text on the right side split should be red text on a blue background since it has the same highlighting as the Warning text above it.

### Version of Vim

9.0.1966

### Environment

GVIM: 
    OS: Windows 11
    Terminal: NA
    Value of $TERM: NA
    Shell: NA

VIM: 
    OS: Windows 11 WSL | 4.4.0-22621-Microsoft Kernel | Debian 12.1
    Terminal: cmd.exe
    Value of $TERM: xterm-256color
    Shell: GNU bash version 5.2.15

**Comment by chrisbra** [comment]
I reviewed it. You are using 
```
 hi! Folded ctermfg=Red guifg=Red
```
Which will only change the existing foreground colors for the folded highlighting group, but **not** remove the *background* attributes. Since this is initialized with a default background color, this command wouldn't change it: 

https://github.com/vim/vim/blob/563e6440bf00f2f52de8412d4f967ea224467053/src/highlight.c#L214-L215

However, you are right, that the current highlighting code does not take the 'wincolor' setting into account. For that, one would need a patch similar to the following:
````patch
diff --git a/src/drawscreen.c b/src/drawscreen.c
index a2f60a64f..c4f8c373c 100644
--- a/src/drawscreen.c
+++ b/src/drawscreen.c
@@ -1075,6 +1075,7 @@ fold_line(
     int                txtcol;
     int                off = (int)(current_ScreenLine - ScreenLines);
     int                ri;
+    int                hlf = HL_ATTR(HLF_FL);

     // Build the fold line:
     // 1. Add the cmdwin_type for the command-line window
@@ -1160,10 +1161,13 @@ fold_line(
        RL_MEMSET(col, HL_ATTR(HLF_FC), fdc);
        col += fdc;
     }
+    if (*wp->w_p_wcr != NUL)
+       hlf = hl_combine_attr(HL_ATTR(HLF_FL), get_wcr_attr(wp));
+

     // Set all attributes of the 'number' or 'relativenumber' column and the
     // text
-    RL_MEMSET(col, HL_ATTR(HLF_FL), wp->w_width - col);
+    RL_MEMSET(col, hlf, wp->w_width - col);

 #ifdef FEAT_SIGNS
     // If signs are being displayed, add two spaces.
@@ -1178,10 +1182,10 @@ fold_line(
            if (wp->w_p_rl)
                // the line number isn't reversed
                copy_text_attr(off + wp->w_width - len - col,
-                                       (char_u *)"  ", len, HL_ATTR(HLF_FL));
+                                       (char_u *)"  ", len, hlf);
            else
 # endif
-               copy_text_attr(off + col, (char_u *)"  ", len, HL_ATTR(HLF_FL));
+               copy_text_attr(off + col, (char_u *)"  ", len, hlf);
            col += len;
        }
     }
@@ -1220,11 +1224,10 @@ fold_line(
 #ifdef FEAT_RIGHTLEFT
            if (wp->w_p_rl)
                // the line number isn't reversed
-               copy_text_attr(off + wp->w_width - len - col, buf, len,
-                                                            HL_ATTR(HLF_FL));
+               copy_text_attr(off + wp->w_width - len - col, buf, len, hlf);
            else
 #endif
-               copy_text_attr(off + col, buf, len, HL_ATTR(HLF_FL));
+               copy_text_attr(off + col, buf, len, hlf);
            col += len;
        }
     }
```

However, this introduces an interesting question. Since the 'wincolor' highlighting is window only, the `:hi Folded` wouldn't show the wincolor specific highlighting for a window. Not sure if the `:hi` line should consider the 'wincolor' option from the window where it was run from or not. Either one isn't great. But not showing how 'wincolor' changes things is also not great.

**Comment by chrisbra** [comment]
current behaviour seems to be okay. So closing.
