### ISSUE TITLE
[vim9script] Cannot assign to an indexed function call,  F()[1] = 123

### ISSUE THREAD

**Issue by errael** [vim/vim#13253]
### Steps to reproduce

The following script produces error
```
2
Error detected while processing :source buffer=1:
line    8:
E488: Trailing characters: = 123
```

```
vim9script

var l = [ 1, 2, 3]
def F(): list<number>
    return l
enddef
echo F()[1]
F()[1] = 123
```
Returning a dictionary has the same issue
```
vim9script

var d = {a: 1, b: 2}
def F(): dict<number>
    return d
enddef
echo F().a
F().a = 123
```

### Expected behaviour

No error

### Version of Vim

9.0.1958

### Environment

ubuntu

**Comment by errael** [comment]
In the dictionary example `F().a = 123` fails. Here's a workaround
```
F()->extend({a: 123})
```

Can't find a builtin function that could be used with a list. Suggest a new builtin, `set({list-dict-blob}, idx, val)`. Then for the list can do
```
F()->set(1, 777)
``

**Comment by yegappan** [comment]
Using the return value of a function in the LHS of an assignment was not supported in legacy Vimscript also:

```
let g:l = [ 1, 2, 3]
func F()
    return g:l
endfunc
echo F()[1]
let F()[1] = 123
```

An obvious workaround for this problem is to store the return value of the function in a local variable and then index it.

**Comment by errael** [comment]
> Using the return value of a function in the LHS of an assignment was not supported in legacy Vimscript also:

Yeah. But it feels weird that `F()[1]` works on the RHS but not the LHS.
> 
> An obvious workaround for this problem is to store the return value of the function in a local variable and then index it.

Right, it breaks the flow but that's the best way to do it. Having something like a `set()` looks good, but a function call is too expensive.

**Comment by errael** [comment]
Assuming won't fix.
