### ISSUE TITLE
Inconsistency between version names in documentation and current status

### ISSUE THREAD

**Issue by RestorerZ** [vim/vim#13259]
### Steps to reproduce

If I understand correctly, based on this PR (#11268 ) and this PR (#11283 ) and the [definition](https://github.com/vim/vim/blob/b74ebfc6bf343ed825b111157261a8d99da6d670/src/version.c#L4979) in `version.c`, there is a clear discrepancy with the specified version name in the documentation. Section [*version*](https://github.com/vim/vim/blob/6ee7b521fa7531ef356ececc8be7575c3800f872/runtime/doc/various.txt#L309) and [*+feature-list*](https://github.com/vim/vim/blob/6ee7b521fa7531ef356ececc8be7575c3800f872/runtime/doc/various.txt#L333)

>The first column shows the smallest version in which they are included:
                           T    tiny (always)
                           S    small
                           N    normal
                           B    big
                           H    huge

### Expected behaviour

The features correspond to the current state of the versions.

### Version of Vim

Vim 9.0.1976

### Environment

All

**Comment by chrisbra** [comment]
I don't understand. Where exactly do you see a discrepancy? Or is this about the *feature-list*? (there used to be small and big builds, but those are gone nowadays I believe).

**Comment by RestorerZ** [comment]
@chrisbra 
I mean the description in the `version` section.
As I understand it, it should be something like this:
```
The first column shows the smallest version in which they are included:
			   T	tiny (always)
			   N	normal
			   H	huge
			   m	manually enabled or depends on other features
			   -    never, feature was removed
			 (none) system dependent
Thus if a feature is marked with "N", it is included in the normal and huge versions of Vim.
```
The `feature-list` section is fine now, sorry.

**Comment by RestorerZ** [comment]
I'll do a PR later tonight.
There are some more documentation files that also mention `small` or `big` versions (starting.txt, testing.txt, usr_90.txt).
