### ISSUE TITLE
xxd: make -R configurable by environment

### ISSUE THREAD

**Issue by melak** [vim/vim#13257]
It's a bit of a fine line whether this is a feature request or a bug report.

xxd had recently introduced colorized output which appears to be defaulting to 'auto', presumably decided by whether or not the output is a tty.

May I please ask for a way to set `-R` by an environment variable? If there is some sort of an established (semi-)standard or convention for this sort of thing (which there does not seem to be, AFAICT), following that would be nice. If not, whatever sensible environment variable works.

The point here is to be able to disable color output "globally" in one fell swoop without having to resort to aliases or wrappers or functions or whatnot.

**Comment by melak** [comment]
Indeed it does, thank you very much.
Dropping a note in the manual would be nice though :).

**Comment by chrisbra** [comment]
I have done so now. Thanks.
