### ISSUE TITLE
termdebug test failure

### ISSUE THREAD

**Issue by benknoble** [vim/vim#13269]
### Steps to reproduce

1. Compile
2. `make test`

### Expected behaviour

All tests pass

### Version of Vim

9.0.1976

### Environment

macOS 11.7
Zsh 5.9
Alacritty 0.12.1
alacritty

### Logs and stack traces

```shell
Failures:
	From test_termdebug.vim:
	Found errors in Test_termdebug_basic():
	command line..script /Users/Knoble/.vim-source/src/testdir/runtest.vim[601]..function RunTheTest[54]..Test_termdebug_basic[44]..WaitForAssert[2]..<SNR>4_WaitForCommon[11]..<lambda>3 line 1: Expected [{'lnum': 9, 'id': 12, 'name': 'debugPC', 'priority': 110, 'group': 'TermDebug'}, {'lnum': 9, 'id': 1014, 'name': 'debugBreakpoint1.0', 'priority': 110, 'group': 'TermDebug'}] but got [{'lnum': 9, 'id': 1014, 'name': 'debugBreakpoint1.0', 'priority': 110, 'group': 'TermDebug'}]
	command line..script /Users/Knoble/.vim-source/src/testdir/runtest.vim[601]..function RunTheTest[54]..Test_termdebug_basic[53]..WaitForAssert[2]..<SNR>4_WaitForCommon[11]..<lambda>4 line 1: Expected [{'lnum': 9, 'id': 1014, 'name': 'debugBreakpoint1.0', 'priority': 110, 'group': 'TermDebug'}, {'lnum': 20, 'id': 12, 'name': 'debugPC', 'priority': 110, 'group': 'TermDebug'}] but got [{'lnum': 9, 'id': 1014, 'name': 'debugBreakpoint1.0', 'priority': 110, 'group': 'TermDebug'}]
```

**Comment by chrisbra** [comment]
you may need to manually step through the test to see why certain signs are not getting placed for you. It's a rather basic test, shouldn't take much effort:

https://github.com/vim/vim/blob/master/src/testdir/test_termdebug.vim

**Comment by benknoble** [comment]
Yeah, will add to my todos :)

**Comment by benknoble** [comment]
Seems to be an issue with GDB (_e.g._, https://sourceware.org/bugzilla/show_bug.cgi?id=24069, https://apple.stackexchange.com/q/420492/293074, etc.). Switching to GNU gcc didn't fix it for me, so I'm trying the patched domq/gdb now and will try lldb next.

Ironically, if I do `gdb P` again after killing it once, it works fine for that program (but not others, still).

Anyway, might need a way to skip this test on broken configurations :(

**Comment by benknoble** [comment]
It seems native LLDB works on my system, so I've uninstalled gdb completely (which should disabled that test). I'll report the bug as still being a problem, though.
