### ISSUE TITLE
Type annotations allowed outside declarations

### ISSUE THREAD

**Issue by dkearns** [vim/vim#13267]
### Steps to reproduce

```vim
vim9script
var x: number
x: number = 42
echomsg x
```

This runs without error outputting 42.

If you change the annotation on line 3 to `string` or the assigned value to a string, or both, a type mismatch error is emitted.

### Expected behaviour

An error message, presumably "E488: Trailing characters: : number" based on comparable incorrect usage.

This may be a remnant partial implementation allowing type annotations to appear outside declarations.  That would be useful, particularly if it could be applied to arbitrary expressions.

### Version of Vim

9.0.1976

### Environment

Ubuntu 20.04

**Comment by errael** [comment]
> ... allowing type annotations to appear outside declarations.
>  That would be useful, particularly if it could be applied to arbitrary expressions.

I don't understand what this means. Is the idea similar to the current casting construct `<SomeTyp>var1`?

**Comment by dkearns** [comment]
No, an assertion not a cast.

`(1 + 1): number`

**Comment by yegappan** [comment]
I don't think this is by design.  There is code to support specifying a type for the loop variable
in a "for" loop.   I think, this by accident, caused the above case.  I will create a PR to emit an
error for this case.
