### ISSUE TITLE
Covariant parameter types allowed when assigning functions

### ISSUE THREAD

**Issue by dkearns** [vim/vim#13299]
### Steps to reproduce

```vim
vim9script

class A
endclass
class B extends A
endclass

def Foo(p: B): B
  return B.new()
enddef

var Bar: func(A): A = Foo
```

### Expected behaviour

An error message should be output:
`"E1012: Type mismatch; expected func(object<A>): object<A> but got func(object<B>): object<B>"`

I'm a bit surprised these checks are handled separately.

### Version of Vim

9.0.1999

### Environment

Ubuntu 20.04

**Comment by yegappan** [comment]
This is the expected behavior.  Otherwise how will you extend a class but still use methods from the base class using the extended class?

**Comment by errael** [comment]
> This is the expected behavior. Otherwise how will you ...

Could you clarify this. (an example perhaps)

Doing the following, starting with the original example, gets a run-time error even though it compiles OK, and note that `any` _is not used as a type anywhere_. I didn't think that was possible.

```
def F()
    echo Bar(A.new())
enddef
F()
```
```
Error detected while processing :source buffer=2[17]..function <SNR>38_F:
line    1:
E1013: Argument 1: type mismatch, expected object<B> but got object<A>
```
This may be allowing something whose resolution should be part of a next version type system.

**Comment by errael** [comment]
One could argue whether this is a "covariant" or "contravariant" problem, or one caused by the other.

**Comment by dkearns** [comment]
> This is the expected behavior. Otherwise how will you extend a class but still use methods from the base class using the extended class?

Sorry, I don't understand your comment.

This has nothing to do with classes and methods, which you recently changed to address this very issue, but assignment compatibility of function types. The same variance rules apply - contravariance in the parameter type.

**Comment by yegappan** [comment]
I have created PR #13307  to address this.  But I am wondering are there any other cases where this will not work or might break existing functionality.

**Comment by errael** [comment]
> I have created PR #13307 to address this. But I am wondering are there any other cases where this will not work or might break existing functionality.

I wonder about that myself.

I'm less worried about "break existing functionality". It shouldn't be too much of a problem if using `any` fixes any compilation errors (and there might be a run time error) if that's really what the programmer wants. It's encouraging that _all the tests pass_. (but then, I'm easily encouraged)

Places where `type invariant` is quietly violated and allows run time errors; that's all kinds of trouble.

**Comment by dkearns** [comment]
> I have created PR https://github.com/vim/vim/pull/13307 to address this.

I assume the invariance is intentional?  I'd really prefer that the type system was sophisticated enough to handle these reasonably basic cases.

This is now inconsistent with the method implementation, is that also intentional?  They don't have to match but it might be a better starting point if they did.

>  But I am wondering are there any other cases where this will not work or might break existing Vim9 class functionality.

Do you mean in the compiler implementation or at a language level?  I can't see how the latter is affected.

**Comment by yegappan** [comment]
> > I have created PR #13307 to address this.
> 
> I assume the invariance is intentional? I'd really prefer that the type system was sophisticated enough to handle these reasonably basic cases.
> 
> This is now inconsistent with the method implementation, is that also intentional? They don't have to match but it might be a better starting point if they did.

Are you referring to the return type? The argument types are invariant but the return type can be 
a covariant.  This is same as the method implementation.  Are you referring to some other inconsistency?

> 
> > But I am wondering are there any other cases where this will not work or might break existing Vim9 class functionality.
> 
> Do you mean in the compiler implementation or at a language level? I can't see how the latter is affected.
>

I am referring to the compiler implementation.  All the existing tests are passing.  Need to see
whether some other problem crops up.

**Comment by dkearns** [comment]
> Are you referring to the return type? The argument types are invariant but the return type can be a covariant. This is same as the method implementation. Are you referring to some other inconsistency?

Sorry, I was commenting based on the commit message, "Enforce invariant type check for arguments and return value...". 

I'll see if I can find any problems, thanks.
