### ISSUE TITLE
test_crash 8 is missing test file

### ISSUE THREAD

**Issue by jamessan** [vim/vim#13305]
https://github.com/vim/vim/blob/7879bc5c13311c1fb6497776ed7804400852460a/src/testdir/test_crash.vim#L71-L72

The test is supposed to source `crash/vim_msg_trunc_poc` but that file doesn't exist.  The test is "passing" because the command is using `|| echo` instead of `&& echo`.

**Comment by chrisbra** [comment]
darn, I missed that one. The test is using `||` because I did not find a way to force Vim to quit with zero exit value. 

Thanks, I fix this in a second.
