### ISSUE TITLE
colorscheme koehler lost readability in update vim 8.x -> 9.0.x

### ISSUE THREAD

**Issue by jeanluc2020** [vim/vim#13317]
### Steps to reproduce

1. Open any file in later vim-9 versions
2. :colorscheme koehler
3. Look at the colors - comments are almost unreadable
4. Example how things look now is after TOhtml: http://gott-gehabt.de/800_wer_wir_sind/thomas/Homepage/Computer/perl/theweeklychallenge-238-1.html

### Expected behaviour

Everything looks more readable under ":colorscheme koehler" - I wrote the colorscheme for readability in the first place.
Example how things looked back in vim-8 after TOhtml: http://gott-gehabt.de/800_wer_wir_sind/thomas/Homepage/Computer/perl/theweeklychallenge-238-1.html
1. the background is black, not kind of dark-grey
2. comments are cyan and therefore better readable on black background
3. function and variable names also have different colors

### Version of Vim

Vi IMproved 9.0, Included patches: 1-1378, 1499

### Environment

Operating System: Debian 12.2 (just updated from 11.x)
terminal: xterm
value of $TERM: screen
shell: zsh-5.9

**Comment by chrisbra** [comment]
I suppose this is essentially the same as #10449 which mentions several alternatives/solutions/work-arounds

**Comment by chrisbra** [comment]
btw: you mentioned two times the same link

**Comment by lifepillar** [comment]
My Linux xterm has `$TERM` set to `xterm`. Is `screen` correct for your setup?

What is the output of `:set t_Co?`

**Comment by ychin** [comment]
The colors look correct for me (black background, etc). Is this some terminal issues?

**Comment by jeanluc2020** [comment]
My mistake, I meant to use http://gott-gehabt.de/800_wer_wir_sind/thomas/Homepage/Computer/perl/theweeklychallenge-237-1.html as the "good" example.

**Comment by jeanluc2020** [comment]
> My Linux xterm has $TERM set to xterm. Is screen correct for your setup?

Since I'm running screen inside of xterm, yes this is correct / expected.

**Comment by jeanluc2020** [comment]
> I suppose this is essentially the same as https://github.com/vim/vim/issues/10449 which mentions several alternatives/solutions/work-arounds

Yeah, downloading the original koehler.vim into ~/.vim/colors solves it for me.

**Comment by jeanluc2020** [comment]
> What is the output of `:set t_Co`?

`t_Co=8`

**Comment by jeanluc2020** [comment]
> The colors look correct for me (black background, cyan comments, etc). Is this some terminal issues?

I don't know exactly what is in play here, but with TERM=xterm-256colors or TERM=xterm I also get no cyan comments if I don't use the legacy colorscheme.

**Comment by chrisbra** [comment]
> t_Co=8

While that is correct for a plain old xterm, I suppose you rather want to use `xterm-256color`  (without the *s*)  to have at least 256 colors available (which xterm supports for a very long time). I haven't seen a terminal that only supports 8 colors in years.

If you want to keep `TERM=xterm` for whathever reasons, you can also just set `:set t_Co=256` in your `.vimrc` to force to use 256 colors.

**Comment by chrisbra** [comment]
I supposed this can be closed now.

**Comment by benknoble** [comment]
More appropriate is to make sure TERM makes sense and that the corresponding terminfo entry reports appropriate values. For example, with tmux I create a tmux-256color terminfo and use it for TERM inside tmux (forcibly assuming that the underlying terminal also supports it). I even enable some special things conditionally, including  resetting Vim’s 'term': https://github.com/benknoble/Dotfiles/blob/42e735921210a6bc6da3932c0d88d54db613693e/links/vim/vimrc#L370 Arguably getting this right for tmux/screen is hard, because their info depends more on the combination of underlying term and the program itself.
