### ISSUE TITLE
netrw bug: If toggle banner (hit 'I') is done at the same time the cursor is on the line "Showing/Hiding", the "normal/hiding/show" status is also toggled.

### ISSUE THREAD

**Issue by xc1427** [vim/vim#1333]
I am using gvim 8.0.45 64bit on windows 10.
To reproduce this bug:
Providing that we set `banner` is visible and `g:netrw_list_hide=^\.\.\=/\=$` to be able to toggle the display of `./` and `../`. And we are on the `Hiding` state as shown in the fig.1.
![capture1](https://cloud.githubusercontent.com/assets/5611770/21298350/69c8ee28-c590-11e6-85ba-294e1a140eb5.PNG)
(fig.1)

Now put the cursor on the line `Hiding` then press `I`. Banner is gone as expected as in fig.2.
![capture2](https://cloud.githubusercontent.com/assets/5611770/21298442/8b8bb972-c591-11e6-89af-f289892bd56e.PNG)
(fig.2)

Now press `I` again. Banner comes back **BUT** the `showing` state is on. So nothing but only `./` and `../` is visible as shown below.
![capture3](https://cloud.githubusercontent.com/assets/5611770/21298466/f166e348-c591-11e6-9d2c-d14171c8f4bd.PNG)
(fig.3)

**Remark**:
This can even be reproduced starting from the fig2, which means we already set banner invisible. i.e., we press `I` on the **6th** line `node_modules`, then nothing is shown but `./` and `../`. The 6th line corresponds "Hiding/Showing" line number which is also 6.

**Comment by cecamp** [comment]
Please try v162h of netrw which I believe fixes this.  You can get it from http://www.drchip.org/astronaut/vim/index.html#NETRW.  Thank you for reporting this.

**Comment by vim-ml** [comment]
cecamp wrote：
> Please try v162h of netrw which I believe fixes this.  You can get it from http://www.drchip.org/astronaut/vim/index.html#NETRW.  Thank you for reporting this.
> 

I love netrw more and more after reading this:
http://vimcasts.org/blog/2013/01/oil-and-vinegar-split-windows-and-project-drawer/

@Bram, could you please update the built-in netrw to the latest version ?
many bugs have been fixed.

**Comment by xc1427** [comment]
> Please try v162h of netrw which I believe fixes this. You can get it from http://www.drchip.org/astronaut/vim/index.html#NETRW. Thank you for reporting this.

Yes. This new version solves the problem.
