### ISSUE TITLE
[vim9script/vim9class] incorrect argument type checking involving varargs

### ISSUE THREAD

**Issue by errael** [vim/vim#13343]
### Steps to reproduce

This problem shows up in
- vim9script funcref assignment, this first example
- vim9class function overriding, the example in the first comment

The statement `Func = F2` in the following should produce an error since the arguments types are not the same.
Some of the problems that arise from this are demonstrated in the examples that follow.
```
vim9script

def F(...stuff: list<string>)
    echo stuff
enddef

var Func: func(list<string>)

Func = F            # <<< expect an error

def Test1()
    F('one')
    # Func('two')   # <<< compilation error
enddef

def Test2()
    Func(['two'])
    #F(['one'])      # <<< compilation error
enddef

Test1()
Test2()             # <<< runtime error
```

### Expected behaviour

See comments above

### Version of Vim

9.0.2026

### Environment

ubuntu

**Comment by errael** [comment]
A similar problem shows up in `vim9class` overriding methods.
```
vim9script

class B
    this._val: string
    def F(...xxx: list<string>)
    enddef
endclass
class C extends B
    def F(xxx: list<string>)        # <<< expect compile error
    enddef
endclass

def F(o: B)
    o.F('a')
enddef

F(B.new())
F(C.new())          # <<< runtime error
```

**Comment by errael** [comment]
@yegappan This seems to fix the problem (at least the ones in this report). But I'm not sure what other exposure there might be.

```
$ hg diff
diff --git a/src/vim9type.c b/src/vim9type.c
--- a/src/vim9type.c
+++ b/src/vim9type.c
@@ -884,6 +884,9 @@
                else
                    ret = MAYBE;
            }
+           if (ret != FAIL && (expected->tt_flags & TTFLAG_VARARGS)
+                                   != (actual->tt_flags & TTFLAG_VARARGS))
+               ret = FAIL;
            if (ret != FAIL && expected->tt_argcount != -1
                    && actual->tt_min_argcount != -1
                    && (actual->tt_argcount == -1
```

**Comment by errael** [comment]
Oh, and the message is like:
```
E1383: Method "F": type mismatch, expected func(...list<string>) but got func(list<string>)
```

**Comment by errael** [comment]
This change causes
```
Found errors in Test_varargs_mismatch():
```
It's not clear to me what that test is testing. The check might want to be less restrictive is `any` is involved, but matching varargs with non-varargs signature feels wrong.

The "right thing" is ??? 

I'm done for the evening if anyone wants to pick this up (hint, hint).

**Comment by errael** [comment]
> It's not clear to me what that test is testing

Oh. I guess it's saying a funcref assignment target with an argument list of `...any` matches any source argument specification. Idiomatic.

**Comment by yegappan** [comment]
The following diff seems to pass all the above tests:

```
+           if (ret != FAIL
+                   && ((expected->tt_flags & TTFLAG_VARARGS)
+                       != (actual->tt_flags & TTFLAG_VARARGS))
+                   && ((expected->tt_flags & TTFLAG_VARARGS) == 0
+                       || expected->tt_args[expected->tt_argcount -1]->tt_type != VAR_ANY))
+               ret = FAIL;
```

**Comment by errael** [comment]
I guess there's a missing test.  With the suggestion the following no longer works.
```
vim9script

var FuncUnk: func: number
FuncUnk = (...v1): number => 333
```
```
E1012: Type mismatch; expected func(...): number but got func(...list<any>): number
```

**Comment by errael** [comment]
Here's some results before any changes are made.

In the following, with `FuncAnyVA`, why does `ONE` work and `TWO` doesn't?
It really looks like both `FuncAnyVA` `ONE` and `TWO` should fail.
`FuncAnyVA-ONE` is like test_vim9_func::Test_varargs_mismatch.
It feels to me like that is missing a TODO, because it should fail.

I think the right way to match any argument list is by not specifying one,
as in `FuncUnknown`.

`FuncAnyVA-TWO` fails with
```
E1012: Type mismatch; expected func(...any): number but got func(any, any): number
```

Note that `FuncUnknown` works in all cases (as expected).

```
vim9script

var FuncAnyVA: func(...any): number
var FuncUnknown: func: number

FuncAnyVA = (v): number => v                # <<<<< ONE
#FuncAnyVA = (v1, v2): number => v1 + v2     # <<<<< TWO

FuncUnknown = (v): number => v
FuncUnknown = (v1, v2): number => v1 + v2
FuncUnknown = (...v1): number => 333
```

**Comment by errael** [comment]
Considering the previous post, I believe the right thing is
```
	    if (ret != FAIL
		    && ((expected->tt_flags & TTFLAG_VARARGS)
			!= (actual->tt_flags & TTFLAG_VARARGS))
		    && expected->tt_argcount != -1)
		ret = FAIL;
```
Then, in the example from the previous post, both `FuncAnyVA` fail and all of `FuncUnknown` pass.

`def Test_varargs_mismatch()` also fails, but it should, IMHO. That behavior is a weirdness that should be dropped. If dropping it causes a problem in some existing code, then it can be handled later.

BTW, in the previous,
`var FuncAnyVA: func(...any): number` and `var FuncAnyVA: func(any): number` behave the same in the current version.

**Comment by errael** [comment]
Closed via https://github.com/vim/vim/commit/96952b2e98cb5f05bc3b3adfb0029056f39cffef
