### ISSUE TITLE
[wish-list] Built-in support for popup tips (require for comment)

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#1335]
A popup tips is very useful to display function prototypes, especially working in a new project or reading code:

See that:

![neovim](https://cloud.githubusercontent.com/assets/3035071/21447379/ef868490-c90e-11e6-98dd-daa372234487.gif)

https://github.com/extr0py/oni

I have noticed that jedi-vim has a fancy magic, with g:jedi#show_call_signatures option enabled,

![1a5f7f34-c831-11e6-8771-f4b66078bac2](https://cloud.githubusercontent.com/assets/3035071/21447424/6f9f56e8-c90f-11e6-9a3c-05b50bc6ed23.png)

jedi-vim can show the function prototype by temporary changing the text of the above line, this is a fancy magic.

I havn't take a deep look into the plugin, yet, but I belive it's not a clean implementation. For example, even if I don't change any text, the change symbol will be on after the signature is shown, and even after the tip is hidden. And this feature has some other wierd issues.

I think it would be a good choice to have built-in support for this kind of tips (another auto-complete popup like tips is enough). Then it would be easy for other plugins to have the same feature without any magic.

Does anybody think it is nice to have something like this ?

**Comment by brammool** [comment]
This already exists, see  :help balloon-eval

**Comment by skywind3000** [comment]
Balloon-eval can popup only if the mouse is pointing at a symbol.

The popup tips can display anytime, for example (jedi-vim), when someone type "(" the function prototype  and a simple help document can be displayed right above the cursor. 

Is there any way to get the cursor position in pixel coordinate in GVim ? 
At least , I can write a DLL and use Layered Window to do this .

**Comment by chrisbra** [comment]
Well the basic functionality is there, however it would be great, if we can trigger displaying the balloon using some keys, so that one does not have to use the mouse.

**Comment by skywind3000** [comment]
That would be great.

Finally, I figure out my self. The cursor position could be calculated:

1. Get the HWND of gvim.exe, find a child window whose `ClassName` is `VimTextArea`
2. Get the rectangle of the child window `VimTextArea` in pixel.
3. Calculate gui.char_width = width(VimTextArea) / (&columns)
4. Calculate gui.char_height = height(VimTextArea) / (&lines)
5. Get current cursor position X = left(VimTextArea) + gui.char_width * wincol()
6. Get current cursor position Y = top(VimTextArea) + gui.char_height * winline()

-----
done !

At last, it would be better to prevent Layered Window overlapping the autocomplete window if pumvisible() returns 1.

**Comment by skywind3000** [comment]
Sadly, it only works if there is one one window.

**Comment by skywind3000** [comment]
Haha, found it, the wincol() and winline() could be replaced by screencol() and screenline() .
Every thing is fine.
