### ISSUE TITLE
Distinguish a parenthesised expression from a function invocation in legacy syntax

### ISSUE THREAD

**Issue by zzzyxwvut** [vim/vim#13350]
### Steps to reproduce

A parenthesised expression delimited with space, and written  
in legacy syntax, can be accepted as a function invocation  
and would fail (`E1085`):

```vim
echo v:numbermin (1 << 63)
legacy echo v:numbermin (1 << 63)
```

unless there is a function proper to match it:

```vim
echo abs (1 << 63)
legacy echo abs (1 << 63)

echo strlen ('hello world')
legacy echo strlen ('hello world')
```

or there is no ambiguity about the expression:

```vim
echo (1 << 63)
legacy echo (1 << 63)
```

In Vim9 syntax, no space is tolerated between the function  
name and its left paren (`E121`):

```vim
vim9cmd echo abs (1 << 63)
vim9cmd echo strlen ('hello world')
```

and expressions are accepted as such:

```vim
vim9cmd echo v:numbermin (1 << 63)
vim9cmd echo 'abs' (1 << 63)
vim9cmd echo 'strlen' ('hello world')
```

### Expected behaviour

Try harder at parsing the input for legacy syntax.

### Version of Vim

Vim 9.0 (v9.0.2032)

### Environment

Debian GNU/Linux (testing/trixie)

**Comment by yegappan** [comment]
Using optional space characters between a name and the opening parenthesis "(" is a valid syntax in legacy Vim scripts.
So this cannot be changed without breaking backward compatibility.

**Comment by zzzyxwvut** [comment]
I see.  Fortunately, such function look-ups can be worked  
around by explicitly concatenating expressions:
```vim
echo v:numbermin '' .. (1 << 63)
echo v:numbermin .. '' (1 << 63)
```
