### ISSUE TITLE
`Test_cq_zero_exmode` fails when vim configured without channel feature

### ISSUE THREAD

**Issue by dpelle** [vim/vim#13365]
### Steps to reproduce

`Test_cq_zero_exmode` fails when vim-9.0.2034 is configured as follows without the channel feature:
```
$ cd vim
$ ./configure  --with-features=huge --enable-gui=no  --disable-channel
$ cd src/testdir
$ make test_startup
...snip...
Executed 59 tests                        in   4.390440 seconds
1 FAILED:
Found errors in Test_cq_zero_exmode():
Caught exception in Test_cq_zero_exmode(): Vim(call):E684: List index out of range: 0 @ command line..script /home/dope/sb/vim/src/testdir/runtest.vim[601]..function RunTheTest[54]..Test_cq_zero_exmode, line 5
...snip...
```
The same test passes when configured with the channel fearture i.e. without the `--disable-channel` option.

This patch fixes the test, but I'm not sure it's ideal:
```
diff --git a/src/testdir/test_startup.vim b/src/testdir/test_startup.vim
index 6780205a2..1a81318f3 100644
--- a/src/testdir/test_startup.vim
+++ b/src/testdir/test_startup.vim
@@ -1353,6 +1353,8 @@ endfunc

 " Test that -cq works as expected
 func Test_cq_zero_exmode()
+  CheckFeature channel
+
   let logfile = 'Xcq_log.txt'
   let out = system(GetVimCommand() .. ' --clean --log ' .. logfile .. ' -es -X -c "argdelete foobar" -c"7cq"')
   call assert_equal(8, v:shell_error)
```

I see the test starts vim with the `--log` option which apparently does not work without the channel feature.
I'm not sure if this is intentional. It's at least not clearly explained in the `:help --log`:
```
--log {filename}                                        --log
                Start logging and write entries to {filename}.
                This works like calling ch_logfile({filename}, 'ao') very
                early during startup.
                {only available with the +eval feature}
```
Note that the doc says:
* "**works like calling ch_logfile(...)"** but that seems to be an implementation detail.
* **"only available with the +eval feature"** but that is not true, since it requires the channel feature

### Expected behaviour

I'd expect that all tests should pass.

### Version of Vim

vim-9.0.2034

### Environment

Operating systems: macOS-13.6 (M1) or Ubuntu-22.04.3
Terminal: Alacritty-0.12.3 (1) (unlikely to be relevant for this bug)
$ TERM: xterm-256color
shell: bash-5.1.16(1)

**Comment by dpelle** [comment]
The error message when this happens also does not point to reason why it fails since see:
```
Found errors in Test_cq_zero_exmode():
Caught exception in Test_cq_zero_exmode(): Vim(call):E684: List index out of range: 0 @ command line..script /home/dope/sb/vim/src/testdir/runtest.vim[601]..function RunTheTest[54]..Test_cq_zero_exmode, line 5
```
... which says nothing about the `+channel` feature being required for this test to pass or for the `--log` command line option to work.

**Comment by chrisbra** [comment]
yeah thanks, I only included the `--log` to be able to check the error case, it's not per se required for testing the `+cq` feature. But I included your patch. Thanks.
