### ISSUE TITLE
None of `TextChanged` or `TextChangedI` is triggered after either `o` or `O`

### ISSUE THREAD

**Issue by echasnovski** [vim/vim#13367]
### Steps to reproduce

1. Create a config file with the following content:
```vim
let g:n = 0
au TextChanged,TextChangedI * let g:n = g:n + 1
```
2. Start `vim` with that config.
3. Press `o<Esc>` several times. Then press `O<Esc>` several times.
4. Execute `:echo g:n`. It shows 0.

### Expected behaviour

Either `TextChanged` or `TextChangedI` should be triggered after both `o` and `O`.

Judging by their help description ("Begin a new line below/above the cursor and insert text"), I'd say that this is equivalent to making change in Normal mode and then starting Insert mode on target line. So `TextChanged` here seems to be more suitable.

On the other hand, the final state is Insert mode, so maybe `TextChangedI` is more suitable.

**Note**: Executing `A<CR>` instead of `o` works as expected.

------

This is most likely a regression after #13338.

### Version of Vim

9.0.2040

### Environment

Operating system: EndeavourOS Linux x86_64 (6.5.7-arch1-1)
Terminal: st-0.9
Value of $TERM: st-256color
Shell: zsh 5.9

**Comment by echasnovski** [comment]
@chrisbra, I've found that this is also true for other keys that combine Normal and Insert mode operations: `C`, `cc`.

**Comment by chrisbra** [comment]
can you check which other keys please?

**Comment by echasnovski** [comment]
My guess would be all others which mix Normal mode and Insert mode.

I've also just remembered about `S` and `s`. Tested, and they also don't work.

I can't think about any other such keys (or commands) right now.

**Comment by chrisbra** [comment]
can you please check #13375 ?

**Comment by echasnovski** [comment]
Thank you, Christian!
