### ISSUE TITLE
Is Vim have or add multiple lines variable 

### ISSUE THREAD

**Issue by bleakwind** [vim/vim#1337]
Set multiple lines variable:
let myvar = << EOD
... string part one...
... string part two...
EOD;

**Comment by fritzophrenic** [comment]
This issue tracker is for bug reports. Please do not use it to ask questions. Ask questions on the vim_use mailing list: https://groups.google.com/forum/#!forum/vim_use

**Comment by chrisbra** [comment]
it's a valid request, also I personally think it is not really that useful and there are more important things to do

**Comment by ZyX-I** [comment]
<<EOF-style multiline strings are uncommon across languages and not convenient in my opinion. But I constantly use multiline strings like `'''string'''` in Python or `[[string]]` in lua (as well as their even more common ability to wrap lines without placing special characters on regular expressions) and find this very useful. E.g. sometimes I need to supply big expression to `:execute`, sometimes it is just something like a template I do not wish to move to a separate file (especially if “multiline string” contains only two or three lines, but still is too long for being single line).

Note that multiline strings were added to ES6 (template literals). Having some kind of multiline string is very common across most popular dynamic languages. Vim has only hacks like

    let multiline_string = "
        \start\n
        \middle\n
        \end"

, but this has problems:

1. May only be placed in file (can’t supply these lines to `:execute` or type manually).
2. Still requires explicit `\n`.
3. Also requires continuation character.
4. And last, but not least: syntax/vim.vim again does the great job of misleading user by not highlighting this as a string. (Not really surprising after lots of incorrect highlightings like `i` highlighted like `:i` (command) in `let foo=i`.) (Actually syntax/vim.vim does not properly support continuation at all.)

**Comment by chrisbra** [comment]
Yes, I don't particular like HERE strings either. I usually use printf() calls or simple lists for multiline strings.

**Comment by lacygoill** [comment]
May be fixed by https://github.com/vim/vim/commit/f5842c5a533346c4ff41ff666e465c85f1de35d5.

You can now write:

    let myvar =<< EOD
    ... string part one...
    ... string part two...
    EOD

Although, the result is not a string, but a list of strings.  You can get a string by invoking `join()`:

    let myvar =<< EOD
    ... string part one...
    ... string part two...
    EOD
    let myvar = join(myvar, "\n")

**Comment by chrisbra** [comment]
closing then. Thanks.
