### ISSUE TITLE
[vim9script] Returning `this` from method loses typing information

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#13406]
### Steps to reproduce

Source this script:

```vim
vim9script

class C
  def F(): any  # <== Return type cannot be C (known issue, I think)
    return this
  enddef
endclass

class R
  this.C1 = C.new().F()

  def new()
    this.C1.F()
  enddef
endclass

const c1 = C.new().F()
c1.F()  # OK

var r = R.new()  # E715 when calling this.C1.F()
```

Vim raises `E715: Dictionary required` when instantiating `R`. Is it expected behavior? It did not happen before patch 1780 (618e47d1cd93954bad26d47e5353b4f1432daa5e). Now, it is necessary to provide the type of member explicitly—that is, this fixes the code above:

```vim
this.C1: C = C.new().F()
```

Note that the issue seems to be restricted to object members.

### Expected behaviour

A method should be able to return `this` without loss of type information.

### Version of Vim

9.0.2059

### Environment

macOS 14.0
Apple Terminal
xterm-256color
ZSH 5.9

**Comment by errael** [comment]
```
def F(): any  # <== Return type cannot be C (known issue, I think)
```
#12369 and `:help todo`

**Comment by lifepillar** [comment]
Closing as duplicate of https://github.com/vim/vim/issues/12369.

**Comment by errael** [comment]
> Closing as duplicate of #12369.

My bad. I don't think this issue is a duplicate. I think this issue is a legitimate regression.

I only meant to provide the issue for the problem you pointed out
```
Return type cannot be C (known issue, I think)
```

**Comment by yegappan** [comment]
When using a variable of class type, the class type should be explicitly specified in the declaration to use optimized member/method lookups.  Otherwise the Vim9 compiler needs to use a run time type check (not supported yet) to distinguish between Dict and Object member access.  This will be slow.  I am planning to add a runtime type check to support this.  But this will be slow.

**Comment by errael** [comment]
> the class type should be explicitly specified

That's impossible in some cases, #12369.

I guess it's a big deal to fix it? I've wondered if taking a second pass to scan class again if the class name is used in the class. 

Or maybe `:type` could be part of a solution? If the type info isn't needed until methods in the class are compiled...
