### ISSUE TITLE
[vim9script] Regression: E1180: Variable arguments type must be a list: any

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#13403]
### Steps to reproduce

Source this script:

```vim
vim9script

def F(X: func(...any): any)
enddef
```

This results in E1180. It used to compile before 3ec6c1fe3bb1b366b710d3e7226f7eed3be1801a.

### Expected behaviour

Vararg function with type `any` should compile.

### Version of Vim

9.0.2059

### Environment

macOS 14.0
Apple Terminal
xterm-256color
ZSH 5.9

**Comment by errael** [comment]
> Vararg function with type any should compile.

I agree. AFAICT, the proper syntax is
```
def F(X: func(...list<any>): any)
```
The PR you mention is a bug fix, incorrect syntax was not detected. Could you take a look at https://github.com/vim/vim/pull/13397#issue-1955273280 and comment with that in mind.

**Comment by errael** [comment]
A key comment there might be

> Since no other tests failed with this change; I'm assuming that in a `funcref`
> `...string` is not magic shorthand for something.

**Comment by errael** [comment]
At the end of `:help type-checking` in a release with this PR, there's an example of declaring a func that accepts any arguments.

**Comment by chrisbra** [comment]
> def F(X: func(...any): any)
> enddef

Is this acutally valid? According to the [help](https://vimhelp.org/vim9.txt.html#vim9-variable-arguments), we will always require a list-type: 

```
Variable arguments are defined as the last argument, with a name and have a
list type, similar to TypeScript.  For example, a list of numbers: >
	def MyFunc(...itemlist: list<number>)
	   for item in itemlist
```

**Comment by lifepillar** [comment]
I see now that I was relying on the looser type checking in one of my libraries. I had typed a function as:

    def F(G: func(...any): any)

and it was accepting both `F1(...list<any>): any` *and* `F2(any): any`. Now, after fixing the type signature, the latter are not compatible any longer and I obviously need to update their argument's type.

Thanks for clarifying! You may close this. Just one thing: maybe, in `:h vim9-func-declaration` the following two type declarations:

    func(...{type})
    func({type}, ?{type}, ...{type}: {type}

should be changed to:

    func(...list<{type}>)
    func({type}, ?{type}, ...list<{type}>: {type}

?

**Comment by errael** [comment]
> maybe, in `:h vim9-func-declaration` the following two type declarations:
> 
> ```
> func(...{type})
> func({type}, ?{type}, ...{type}): {type}
> ```
> 
> should be changed to:
> 
> ```
> func(...list<{type}>)
> func({type}, ?{type}, ...list<{type}>): {type}
> ```

I was wondering about that myself. I think I had a crazy thought that `{type}` is what the code in the function sees (type would be `list<{type}>`) but that reasoning is convoluted.

The description says
```
- type of variable number of arguments
```
How about
```
- type of list for variable number of arguments
```
(seems better than `type of variable number of arguments' list)

Please comment on what is easiest to read/understand. And I'll make some changes if there are no objections.

**Comment by chrisbra** [comment]
`typoe of list` sounds good, but to make it really clear, I'd also change it to this here (so confirm to @lifepillar opinions)
```
func(...list<{type}>)
func({type}, ?{type}, ...list<{type}>): {type}
```
