### ISSUE TITLE
Pressing Esc in Insert mode removes trailing spaces

### ISSUE THREAD

**Issue by lkintact** [vim/vim#13411]
### Steps to reproduce

1. Run `gvim -u NONE`
2. Execute `:filetype plugin indent on`
3. Execute `:set filetype=python`
4. Type `def f():` in the buffer and press <kbd>Enter</kbd>. gVim moves to the next line, indenting it.
5. Press <kbd>Esc</kbd>. Instead of just switching to Normal mode, gVim removes the trailing spaces at the beginning of the line.

### Expected behaviour

gVim should not remove the trailing spaces.

### Version of Vim

9.0.2026

### Environment

OS: Windows 10 Home
Terminal: GUI.

**Comment by chrisbra** [comment]
that is default behaviour and is how vim always has behaved. IIRC there was a trick  to just enter a key and deleteing it at the same time to keep the indent

**Comment by lkintact** [comment]
Thanks, I'm closing the issue.
