### ISSUE TITLE
xxd -b -r corrupts files

### ISSUE THREAD

**Issue by Un1q32** [vim/vim#13410]
### Steps to reproduce

simple test script:
```sh
#!/bin/sh
dd status=none if=/dev/urandom of=testfile1 bs=1k count=10
xxd -b testfile1 > testfile1.hex
xxd -b -r testfile1.hex > testfile2
if cmp -s testfile1 testfile2; then
    echo "Files are identical"
else
    echo "Files are different"
fi
rm testfile1 testfile1.hex testfile2
```

### Expected behaviour

test script should say "Files are identical" like it does with not using -b

### Version of Vim

9.0.2059 (latest commit as of writing)

### Environment

OS: fedora 38
Terminal: kitty
$TERM: xterm-kitty
shell: zsh 5.9

tested with xxd from fedora repos, as well as compiling latest [xxd.c](https://raw.githubusercontent.com/vim/vim/0ab500dede4edd8d5aee7ddc63444537be527871/src/xxd/xxd.c) from with `cc -O2 -DUNIX xxd.c -o xxd`

**Comment by Shane-XB-Qian** [comment]
testfile1 is a bin already, is that ok to bin again?

**Comment by OldWorldOrdr** [comment]
> testfile1 is a bin already, is that ok to bin again?

Is there a typo here or am I just too tired to understand?

testfile1 is a file with random data, testfile2 should have exactly the same data as testfile1 if things worked correctly but it doesn't because of a bug in xxd.

**Comment by Shane-XB-Qian** [comment]
> > testfile1 is a bin already, is that ok to bin again?
> 
> Is there a typo here or am I just too tired to understand?
> testfile1 is a file with random data, testfile2 should have exactly the same data as testfile1 if things worked correctly but it doesn't because of a bug in xxd.

i donot know if this is bug or not, i meant testfile1 is binary file already,
even you open it in vim then save and -r, then it probably different.
only as i know ascii file it should be -r complete same.

-- 
shane.xb.qian

**Comment by chrisbra** [comment]
is this reproducible for you? With an old xxd version from the Ubuntu distributed xxd, I only get:
```
xxd: sorry, cannot revert this type of hexdump
```

**Comment by chrisbra** [comment]
ah, this comes from commit https://github.com/vim/vim/commit/85f4521808dd9a587c00f9a2927e84217721cfca

ping @tristhaus then

**Comment by chrisbra** [comment]
BTW: the test uses `-g1` to reverse the hexdump, you may try this one as well please.

**Comment by Shane-XB-Qian** [comment]
> is this reproducible for you? With an old xxd version from the Ubuntu distributed xxd, I only get:
> ```
> xxd: sorry, cannot revert this type of hexdump
> ```

yes, it was not able to revert this type :-)

-- 
shane.xb.qian

**Comment by OldWorldOrdr** [comment]
> i donot know if this is bug or not, i meant testfile1 is binary file already, even you open it in vim then save and -r, then it probably different. only as i know ascii file it should be -r complete same.

It also corrupts ASCII files, here's a similar script that does the same for an ascii file
```sh
#!/bin/sh
i=0
while [ $i -lt 100 ]; do
    echo abcdefghijklmnopqrstuvwxyz >> testfile1
    i=$((i+1))
done
xxd -b testfile1 > testfile1.hex
xxd -b -r testfile1.hex > testfile2
if cmp -s testfile1 testfile2; then
    echo "Files are identical"
else
    echo "Files are different"
fi
rm testfile1 testfile1.hex testfile2
```

It seems to corrupt in exactly the same way every time, this new script doesn't have any randomness to it, so by putting a sha256sum command before the rm command you can see the same hash is generated for the corrupted file every time.

**Comment by Shane-XB-Qian** [comment]
it was not allowed to revert from bin, but that just changed recently,
so i am not sure it's bug or mistake, or whatever perhaps need to revert change?

-- 
shane.xb.qian

**Comment by tristhaus** [comment]
> It also corrupts ASCII files, here's a similar script that does the same for an ascii file
> [code snipped]
> It seems to corrupt in exactly the same way every time, this new script doesn't have any randomness to it, so by putting a sha256sum command before the rm command you can see the same hash is generated for the corrupted file every time.

There is a length dependence, one line of a-z works fine. I will have a closer look later.

**Comment by OldWorldOrdr** [comment]
> it was not allowed to revert from bin, but that just changed recently, so i am not sure it's bug or mistake, or whatever perhaps need to revert change?

I don't think the change should be reverted, it should just be made to work correctly.

**Comment by vim-ml** [comment]
> it was not allowed to revert from bin, but that just changed recently,
> so i am not sure it's bug or mistake, or whatever perhaps need to revert change?

BTW: hex (vs -b) is ok

-- 
shane.xb.qian

**Comment by chrisbra** [comment]
```
#!/bin/sh
i=0
while [ $i -lt 100 ]; do
    echo abcdefghijklmnopqrstuvwxyz >> testfile1
    i=$((i+1))
done
xxd -b testfile1 > testfile1.hex
xxd -b -r testfile1.hex > testfile2
if cmp -s testfile1 testfile2; then
    echo "Files are identical"
else
    echo "Files are different"
fi
rm testfile1 testfile1.hex testfile2
```
hm, it seems to fail already after the second iteration.

**Comment by OldWorldOrdr** [comment]
new script where the first command line argument controls how many bytes long the file is
seems to start breaking at 37 bytes, 36 and under work though

```sh
#!/bin/sh
[ "$1" -eq "$1" ] 2>/dev/null || { echo "Usage: $0 <number of bytes>"; exit 1; }
[ "$1" -le 0 ] && { echo "number must be greater than 0"; exit 1; }
i=0
while [ $i -lt "$1" ]; do
    printf a >> testfile1
    i=$((i+1))
done
xxd -b testfile1 > testfile1.hex
xxd -b -r testfile1.hex > testfile2
if cmp -s testfile1 testfile2; then
    echo "Files are identical"
else
    echo "Files are different"
fi
rm testfile1 testfile1.hex testfile2
```

**Comment by k-takata** [comment]
How about this?

```diff
diff --git a/src/xxd/xxd.c b/src/xxd/xxd.c
--- a/src/xxd/xxd.c
+++ b/src/xxd/xxd.c
@@ -418,19 +418,13 @@ huntype(
             }
           else /* HEX_BITS */
             {
-              n1 = parse_hex_digit(c);
-              if (n1 >= 0)
-                {
-                  want_off = (want_off << 4) | n1;
-                }
-
-              if (bt < 0)
-                {
-                  p = 0;
+	      if (n1 < 0)
+	        {
+	          p = 0;
                   bcnt = 0;
-                  b = 0;
-                  continue;
-                }
+	          continue;
+	        }
+	      want_off = (want_off << 4) | n1;
             }
           continue;
         }
```

**Comment by OldWorldOrdr** [comment]
@k-takata that seems to work

**Comment by tristhaus** [comment]
I suggest an additional roundtrip test that is large enough to trip the length dependence observed by @OldWorldOrdr:

```diff
diff --git a/src/testdir/test_xxd.vim b/src/testdir/test_xxd.vim
--- a/src/testdir/test_xxd.vim
+++ b/src/testdir/test_xxd.vim
@@ -373,6 +373,13 @@ func Test_xxd_revert_bit_dump()
   bwipe!
 endfunc

+func Test_xxd_roundtrip_large_bit_dump()
+  new
+  exe 'r! printf "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789" | ' . s:xxd_cmd . ' -b | ' . s:xxd_cmd . ' -r -b'
+  call assert_match('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ012345678', join(getline(1, 3)))
+  bwipe!
+endfunc
+
 func Test_xxd_version()
   new
   exe 'r! ' . s:xxd_cmd . ' -v'

```

**Comment by chrisbra** [comment]
can you turn all this into a PR please?

**Comment by k-takata** [comment]
I'm going to hand over my patch.
@tristhaus Could you create a PR?

**Comment by tristhaus** [comment]
> I'm going to hand over my patch. @tristhaus Could you create a PR?

I will do so later, in about 12 hours.

**Comment by OldWorldOrdr** [comment]
ill just do it myself if you're currently unavailible

**Comment by tristhaus** [comment]
> ill just do it myself if you're currently unavailible

Go ahead.
