### ISSUE TITLE
`instanceof()` takes a list of classes

### ISSUE THREAD

**Issue by errael** [vim/vim#13421]
### Steps to reproduce

@LemonBoy @lifepillar @dkearns @yegappan, and any others, please review

Issue #13404 prevents non-value items from being used as values. _It does allow non-value items to be used as arguments to builtin functions_.

This interferes with the way that `instanceof` currently works. Note that in many languages instanceof is built into the language/compiler; `vim9script` uses a function.

Without a messy carve out for handling `instanceof` here are some options

Assuming "Base1", "Base2", "Intf" are classes or interfaces
1. This is the current function interface, something like this needs to work
    `instanceof(b3, [Base1, Base2, Intf1])`
2. Use varargs with the builtin
    `instanceof(b3, Base1, Base2, Intf1)`
3. Pass in classes by name (as strings)
    `instanceof(b3, ["Base1", "Base2", "Intf1"])`

Please weigh in on (2.) or (3.) or propose other suggestions.

And certainly bring up any related issues or considerations.

[1] #12867 introduced `instanceof()`

### Expected behaviour

(2.) above seem minimally disruptive.

### Version of Vim

9.0.2059

### Environment

ubuntu

**Comment by lifepillar** [comment]
Thanks for asking for my opinion, but I am not an expert in designing programming languages, so take my comments for what they are: impressions from a user's standpoint.

I am not sure I understand the issue. What would be an example of interference? And why is `isinstance()` special? For example, isn't `index([Base1, Base2, Intf1], b3)` in the same league?

>It does allow non-value items to be used as arguments to builtin functions.

That difference between built-in functions, which can accept classes as arguments, and user-defined functions, which cannot because there is no “class” type (but yes they can, because an argument can have type `any`) feels to me suspect—if not a potential source of issues (I cannot describe one off the top of my head), at least a potential source of confusion.

In any case, between (2) and (3), I would definitely rule out (3). But, again, I am not sure why (1) is not ok.

**Comment by errael** [comment]
> impressions from a user's standpoint.

A user experienced in vim9script programming.

> I am not sure I understand the issue. What would be an example of interference? And why is `isinstance()` special? For example, isn't `index([Base1, Base2, Intf1], b3)` in the same league?

#13404 prevents a `class` from being a value. So cannot create a list as
```
var l = [Base1, Base2, Intf1]
```
gives an error. Similarly, `index([Base1, Base2, Intf1], b3)` gives an error. So the interference is that you can not create the list to pass to `instanceof()`.

> > It does allow non-value items to be used as arguments to builtin functions.
> 
> That difference between built-in functions, which can accept classes as arguments, and user-defined functions, which cannot because there is no “class” type (but yes they can, because an argument can have type `any`) feels to me suspect—if not a potential source of issues (I cannot describe one off the top of my head), at least a potential source of confusion.

The difference is that some builtin functions are actually part of the language, `instanceof()` is the prime example. With #13404, any builtin function, by default, will give an error if an argument is a non-value. Only `typename()`, `instanceof()`, and maybe a few others, will accept a non-value.

> In any case, between (2) and (3), I would definitely rule out (3). But, again, I am not sure why (1) is not ok.

**Comment by errael** [comment]
> But, again, I am not sure why (1) is not ok.

There are a few experiments in https://github.com/yegappan/vim/pull/2. One of which allows a class to be put into a list, with the idea that it could not be extracted from the list as a value by vim9script, only by a builtin function. If this is implemented, it would allow (1) to continue to work and this could be closed as not a problem.

**Comment by dkearns** [comment]
I think if classes aren't values then they should never be accepted as such, certainly not by functions, and (3) is the reasonable version.

Are these workarounds really easier than implementing whatever is missing?  I'm not entirely clear on what's motivating the sidestep when much of this already works.

**Comment by errael** [comment]
> I think if classes aren't values then they should never be accepted as such

Does that mean they should never be added to a list. But, IMHO, the underlying problem is that certain builtin functions are really part of the language; maybe they should be incorporated into the language.

As you said elsewhere:

> Indeed. I wouldn't like to see it sent out into the world in its current state even with assignment 
> disabled without some sort of reasonable narrative.

You can take a look at #13454 and help clarify things. I've tried to lay out various options/possibilities, this specific topic is discussed. I'd like to see a solution that both feels natural and doesn't twist the language too much.
