### ISSUE TITLE
[netrw] Netrw on Windows does not find cmd.exe when wildignore is set to ignore *.exe

### ISSUE THREAD

**Issue by invarianz** [vim/vim#13426]
### Steps to reproduce

1. Empty vimrc
2. `set wildignore=*.exe`

Going with netrw into a directory and trying to copy a file (`mt`, `mf`, `mc`) then results in
```
**error** (netrw) g:netrw_localcopycmd<> not executable on your system, aborting
```
This is an additional bug to [#12290](/vim/vim/issues/12290) where the copy command will also not execute even though the above wildignore setting is not set. However, the error message changes.

Rational: I'm setting the wildignore setting to use `vimgrep` reliably in a Windows environment.

### Expected behaviour

The file should be copied to the target directory.

### Version of Vim

gVim 9.0.2043

### Environment

Windows 10
Windows 11

**Comment by chrisbra** [comment]
can you please test #13542 ?
