### ISSUE TITLE
`typename()` for typealias of class looks wrong

### ISSUE THREAD

**Issue by errael** [vim/vim#13434]
### Steps to reproduce

This output
```
C: class<C>
OldStyleMyC: class<C>
MyC: typealias<object<C>>
```
generated by following script
```
vim9script

class C
endclass

echo 'C:' typename(C)
const OldStyleMyC = C
echo 'OldStyleMyC:' typename(OldStyleMyC)
type MyC = C
echo 'MyC:' typename(MyC)
```

### Expected behaviour

Note the 3rd line of
```
C: class<C>
OldStyleMyC: class<C>
MyC: typealias<class<C>>
```

### Version of Vim

9.0.2077

### Environment

ubuntu

**Comment by dkearns** [comment]
I'd expect the output of line 3 to be: `MyC: class<C>`

I don't understand the special handling of type aliases that seems to be emerging.  They're just another name for the same thing, they're not a wrapper of some description.

I can hardly guess at what `typealias<class<C>>` means.  It reads like `typealias` is a type parameterised by a currently undefined metaclass-like type.

**Comment by errael** [comment]
> I'd expect the output of line 3 to be: `MyC: class<C>`
> 
> I don't understand the special handling of type aliases that seems to be emerging. They're just another name for the same thing, they're not a wrapper of some description.
> 
> I can hardly guess at what `typealias<class<C>>` means. It reads like `typealias` is a type parameterised by a currently undefined metaclass-like type.

@dkearns I tend to agree with you. Take a look at https://github.com/vim/vim/pull/13441#discussion_r1375147202 where it becomes clear that `:type MyType = SomeClass` does not mean that `MyType` can be used anywhere `SomeClass` can be used.

**Comment by errael** [comment]
> I'd expect the output of line 3 to be: `MyC: class<C>`

Oh, I should mention that since `const MyOldStyleType = SomeClass` may go away soon, it's actually a **functional regression**. To put a fine point on it, after doing `type MyType = SomeClass`, MyType.new(), or any use of MyType to access class members/methods, gives an error message. For examples see, in https://github.com/vim/vim/pull/13404#issuecomment-1783465412, the bullet point at the end "The typealias can not be used as a class type in all situations".

**Comment by yegappan** [comment]
> > I'd expect the output of line 3 to be: `MyC: class<C>`
> 
> Oh, I should mention that since `const MyOldStyleType = SomeClass` may go away soon, it's actually a **functional regression**. To put a fine point on it, after doing `type MyType = SomeClass`, MyType.new(), or any use of MyType to access class members/methods, gives an error message. For examples see, in [#13404 (comment)](https://github.com/vim/vim/pull/13404#issuecomment-1783465412), the bullet point at the end "The typealias can not be used as a class type in all situations".

The latest PR https://github.com/vim/vim/pull/13441 should address this issue.
