### ISSUE TITLE
gvim renders ligatures despite them being disabled

### ISSUE THREAD

**Issue by dzwdz** [vim/vim#13435]
### Steps to reproduce

1. Get a font with ligatures - I know this is reproducible with Iosevka, dunno about others.
2. `gvim -u NONE -c "set guifont=Iosevka\\ 14" -c "hi Stuff gui=italic" -c "match Stuff /it.*/"`
3. Type this into a buffer:
```
no<=
it<=
```

### Expected behaviour

I expect both lines to render `<=` as two separate glyphs. The non-italics one is fine, but the one in italics renders `<=` as a ligature.
![image](https://github.com/vim/vim/assets/21179077/5915311b-5d90-42d9-a4ab-d2ea51b9d7e7)

Moving the cursor over the glyph also looks glitchy.

### Version of Vim

9.0, included patches: 1-1378, 1499

### Environment

Debian 12 (bookworm), X11, GTK3 gui

### Logs and stack traces

```shell
I think the bug is around here:
https://github.com/vim/vim/blob/87ca5e86fa0ef305f3d39cc4261b622f21417f7f/src/gui_gtk_x11.c#L5986

Non-italics text gets rendered without pango, which correctly ignores ligatures. Italics are forced to go through pango, which seems to always render ligatures, when possible.

:set guiligatures=t< prevents the ligature from being rendered, which I think confirms that theory (the string is split up so pango doesn't see the entire ligature at once).
```

**Comment by chrisbra** [comment]
hm, interesting. Can you make it work, by setting the guiligatures option setting?

**Comment by dzwdz** [comment]
I'm not sure what you mean. The screenshot was made with the default setting of an empty string - which should disable ligatures.

The `:set guiligatures=t<` example only "fixes" it for text of the form `t<=` because (I think) it splits up the string that's sent to pango, but it's definitely not a general solution.

`:set guiligatures=<=` makes the ligature render on both lines, and fixes the glitchy rendering of the ligature in the comment - but there's nothing I can do to prevent ligatures in italic text from being drawn, apart from switching to a font without ligatures.

**Comment by chrisbra** [comment]
ah, when skimming over the option description, I thought one needs to includes characters that should not be combined to ligatures. 

Unfortunately, it seems one cannot disable ligatures using pango API, so the only other option is to use a font without ligatures then (or try to disable them using the [font configuration](https://wiki.archlinux.org/title/Font_configuration/Examples#Disable_ligatures_for_monospaced_fonts))
