### ISSUE TITLE
Adding and subtracting a-z characters in visual mode

### ISSUE THREAD

**Issue by Reso44** [vim/vim#13443]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
When using Vim for alphabetized lists and switch/case statements, it is a minor inconvenience to change single characters manually.

**Describe the solution you'd like**
It would be cool if, in *visual mode only*, you could highlight a character and use v_CTRL+a and v_CTRL+x to increment and decrement (respectively) the highlighted character. 

**Describe alternatives you've considered**
I have considered making a plugin to support this, but decided against it. Instead, due to the granular specificity of my idea, I have chosen to issue a feature request.  

**Additional context**
If this were implemented, I think it would be logical to follow the way that Excel works with incrementing and decrementing characters. For example:

 * Incrementing the letter z would turn into A
 * increment the letter Z would turn into AA
 * and so on...

**Comment by chrisbra** [comment]
I don't think this is something for Vim core. Theres @tpope [vim-speeddating](https://github.com/tpope/vim-speeddating) that already does this (I believe).

**Comment by Reso44** [comment]
> I don't think this is something for Vim core. Theres @tpope [vim-speeddating](https://github.com/tpope/vim-speeddating) that already does this (I believe).

Hey Chris, thanks for your reply,
I was thinking I had an original idea, but the plugin community doesn't disappoint!
