### ISSUE TITLE
When using vim as iterm, can't properly recognize the file containing the following cpp code.

### ISSUE THREAD

**Issue by Tastypotato245** [vim/vim#13444]
### Steps to reproduce

In addition, there is a problem that the term is turned off when you move the cursor to the corresponding string.

```
#include "inf_int.h"
#include <iostream>
#include <string.h>
#include <stdlib.h>
#include <stdlib.h>

using namespace std;

int main()
{
	inf_int a, e;
	inf_int b(100);
	inf_int c("321111111111122222222222233333333333444444444445555555555");
	inf_int d("123451987651234572749499923455022211");
	inf_int f=d;
	inf_int g(f);

	// cin >> g ;   // not required

	a=b*c;
	// e=g/f;       // not required

	b=c-d;


	if (f==d) {
		cout << "a : " << a << endl;
		cout << "b : " << b << endl;
		cout << "c : " << c << endl;
		cout << "d : " << d << endl;
		// cout << "e : " << e << endl;
		cout << "f : " << f << endl;
		// cout << "g : " << g << endl;
	}

	return 0;
}
```

```
    inf_int c("321111111111122222222222233333333333444444444445555555555");
```

When open this file, theme is not applied. even though normal theme. (basic)

When I move my cursor to 'c', Iterm is stopped.

P.S. Sorry for my poor English skill

### Expected behaviour

theme color application and program behavior

### Version of Vim

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun  6 2022 20:23:58)

### Environment

macOS version - x86_64
macOS Sonoma : 14.1
Iterm2 : 3.4.20

**Comment by chrisbra** [comment]
Please try to give a reproducible example. Save the above file in a file call `my_test.cpp`. Then run `vim --clean my_test.cpp` Does it work? Does it not work? Also, please try with latest vim.

**Comment by Tastypotato245** [comment]
In another macOS (macbook air M1), same problem.
version : VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Aug  5 2023 07:08:40)

and "vim my_test.cpp" has same problem but "vim --clean my_test.cpp" is fine.

thanks for comment

**Comment by chrisbra** [comment]
> "vim --clean my_test.cpp" is fine.

If vim --clean is fine, you need to debug your vimrc. See https://vimhelp.org/vim_faq.txt.html#faq-2.5 and https://vi.stackexchange.com/questions/2003/how-do-i-debug-my-vimrc-file
