### ISSUE TITLE
Increment from 07 is 010 instead of 08

### ISSUE THREAD

**Issue by callalilychen** [vim/vim#1345]
When I try to increase 07 to 08 using ctrl+a, the result is always 010. When I then decrease 010 using ctrl+x, I get 007.

How to reproduce (tested with vim version 8.0.86):
- open vim
- write 07 in insert mode
- goto normal mode and press ctrl+a
- Now you will see 010
- press ctrl+x
- Now 010 is changed to 007

What is the problem here?

**Comment by oni-link** [comment]
`07` is interpreted as a number in base 8 (octal) because of the leading `0`, try `:set nf=` and see
`:help 'nf'`.

**Comment by chrisbra** [comment]
please ask user questions on the appropriate forums.
