### ISSUE TITLE
`complete_info()` returns empty items list for some completion modes with active `noselect`

### ISSUE THREAD

**Issue by echasnovski** [vim/vim#13451]
### Steps to reproduce

1. Create init file with the following content:
```vim
set nocompatible
set completeopt=menu,noselect
inoremap <C-b> <Cmd>let g:complete_info=complete_info()<CR>
```
2. Open `vim` with `vim -u <path-to-config>`.
3. Start Insert mode with `i` and type `aa\nbb\n` creating two lines and ending on third.
4. Press `<C-x><C-l>` (or `<C-p>`). This should open completion menu.
5. Press `<C-b>` to save output of `complete_info()`.
6. Escape to Normal mode and type `:echo g:complete_info`. This shows `{'pum_visible': 1, 'mode': 'whole_line', 'selected': -1, 'items': []}`.

### Expected behaviour

Output of `complete_info()` always shows up to date information, i.e. `{'pum_visible': 1, 'mode': 'whole_line', 'selected': -1, 'items': [{'word': 'aa', 'menu': '', 'user_data': '', 'info': '', 'kind': '', 'abbr': ''}, {'word': 'bb', 'menu': '', 'user_data': '', 'i
nfo': '', 'kind': '', 'abbr': ''}]}`

This happens in the following cases:
- When completion is activated with `<C-n>` or `<C-x><C-n>`.
- When `noselect` is not part of `completeopt`.
- When built on 650dcfc8d12e68aa05a358301ec15f9e6dbd03ba indicating that daef8c74375141974d61b85199b383017644978c introduced the issue.

### Version of Vim

9.0.2081

### Environment

Operating system: EndeavourOS Linux x86_64 (6.5.9-arch2-1)
Terminal: st-0.9
Value of $TERM: st-256color
Shell: zsh 5.9

**Comment by chrisbra** [comment]
hm, I see the problem

**Comment by echasnovski** [comment]
Thank you, Christian!
