### ISSUE TITLE
abstract keyword allowed when declaring interface features

### ISSUE THREAD

**Issue by dkearns** [vim/vim#13456]
### Steps to reproduce

```vim
interface A
  abstract foo: number
  abstract def Bar()
endinterface
```
This compiles without error.

### Expected behaviour

An error indicating that `abstract` is not allowed when defining interface features.

### Version of Vim

9.0.2078

### Environment

Ubuntu 20.04

**Comment by yegappan** [comment]
All the methods in an interface are abstract.  If the "abstract" keyword is specified for a method, then it is ignored.  I see that it also applies to variables.  I can fix that.

**Comment by dkearns** [comment]
I know I just assumed that it would be disallowed because it's redundant and I recalled a similar issue clarifying the use of static with new*() (not quite the same, I know).

It seems it's not uncommon to allow it.  The Java spec says, "It is permitted, but discouraged as a matter of style, to redundantly specify the abstract modifier for such a method declaration."  C#, I think, used to disallow it but had to add it to disable default implementations.

As we enforce these sorts of style rules in other contexts it _might_ be worth disallowing it.

I'm not sure about the distinction you're drawing between methods and variables here.  They're really behaving more like properties in this context, the same point I was making in https://github.com/vim/vim/discussions/13085.
