### ISSUE TITLE
Error messages capitalise keywords at start of message

### ISSUE THREAD

**Issue by dkearns** [vim/vim#13463]
### Steps to reproduce

Some error messages capitilise keywords when used at the start of the message.  E.g.,

`E1368: Static cannot be followed by \"this\" in a variable name`

### Expected behaviour

These should be lowercase and match the keyword. 

I can track them down if it's agreed this correction is needed.

### Version of Vim

9.0.2078

### Environment

Ubuntu 20.04

**Comment by yegappan** [comment]
The error message convention is to start the message with a capital letter.  See the following commits:

https://github.com/vim/vim/commit/7707228aace9aff16434edf5377a354c6ad07316
https://github.com/vim/vim/commit/cf030578b26460643dca4a40e7f2e3bc19c749aa
https://github.com/vim/vim/commit/df6e0e46c55c9c6d788f94482a8858c0f31391f4
https://github.com/vim/vim/commit/7ece036d72cf639b05d3936183220bec7179bf63

**Comment by dkearns** [comment]
OK, I think lowercase or quoted might be better in this case but sorry for wasting your time as it seems it's been decided.

Thanks for the detailed reply.
