### ISSUE TITLE
<C-s> hangs vim

### ISSUE THREAD

**Issue by mayanksuman** [vim/vim#1346]
Way to reproduce
In ZSH issue command `vim -u NONE file_to_edit`
Press <C-s> in vim. The program will hang and will not respond to any movement key.

**Comment by chrisbra** [comment]
It's no vim issue, but flow control from your terminal. Please configure it correctly.

**Comment by tonymec** [comment]
It is indeed flow control from the terminal, and it is mentioned somewhere in the Vim help.

Hint: Ctrl-Q will get you going again. Or else, use gvim and you won't get into that problem anymore.

**Comment by mayanksuman** [comment]
@chrisbra I don't think it is a issue with my terminal. I have tried to reproduce the same error in nvim (using same terminal ZSH, configuration and file being edited) but nvim do not hang.

**Comment by mayanksuman** [comment]
Thanks @chrisbra and @tonymec. The suggestion from @tonymec worked.

**Comment by arp242** [comment]
You can also use `stty -ixon` to just disable the `<C-s>` and `<C-q>` mappings, as they're not all that useful.
