### ISSUE TITLE
ft_ada in insert mode : unwanted call to funtions

### ISSUE THREAD

**Issue by Mathiasb17** [vim/vim#1347]
Hello,

I am programming in ada with vim, and when i type "al" or "aj" in insert mode, it switches back to normal mode with the following command calls (respectively) in the command line :

```
:call ada#List_Tag ()
```

and

```
:call ada#Jump_Tag ()
```

I find it extremely annoying as i have to type variables name with such character successions in my project... I could not find anything related to disable in :help ada. Is there a way to remove this ?

Thanks,

Mathiasb17

**Comment by k-takata** [comment]
I haven't tried ada plugin and just read the code.
It seems that the mappings are set up at here: https://github.com/vim/vim/blob/c4bfedabe057c05f09a455a5851089e177fa9c00/runtime/ftplugin/ada.vim#L163-L170 ,
then this part is called: https://github.com/vim/vim/blob/c4bfedabe057c05f09a455a5851089e177fa9c00/runtime/autoload/ada.vim#L576-L593 .
IIUC, if a global variable `mapleader` is set to empty, it might happen.

Do you set `mapleader` (or `g:mapleader`) in your `.vimrc` or somewhere else?
What does `:echo g:mapleader` show?

**Comment by Mathiasb17** [comment]
Thanks for your answer,

In my vimrc i got ```let mapleader = "\<Space>"```

```:echo g:mapleader``` displays a space.

**Comment by k-takata** [comment]
It seems that autoload/ada.vim does something wrong.
Does this patch solve the problem? (I haven't tested it at all, though.)

```diff
--- a/runtime/autoload/ada.vim
+++ b/runtime/autoload/ada.vim
@@ -585,11 +585,11 @@ function ada#Map_Menu (Text, Keys, Comma
 	\ " :"	  . a:Command . "<CR>"
       execute
 	\ "nnoremap <buffer>" .
-	\ escape(l:leader . "a" . a:Keys , '\') .
+	\ " <Leader>a" . a:Keys .
 	\" :" . a:Command
       execute
 	\ "inoremap <buffer>" .
-	\ escape(l:leader . "a" . a:Keys , '\') .
+	\ " <Learder>a" . a:Keys .
 	\" <C-O>:" . a:Command
    endif
    return
```

Could you contact the maintainer(s)?
https://github.com/vim/vim/blob/c4bfedabe057c05f09a455a5851089e177fa9c00/runtime/autoload/ada.vim#L5-L8
Updated plugin files must be sent from the maintainer to Bram by mail.

**Comment by Mathiasb17** [comment]
It works perfectly with this patch, thanks a lot, i contacted the maintainers.

**Comment by Mathiasb17** [comment]
Almost one month since i contacted the maintainers, got no answer yet. Anything that could be done to get this fixed ?

**Comment by vim-ml** [comment]
Hi Mathias!

On Sa, 28 Jan 2017, Mathias Brousset wrote:

> Almost one month since i contacted the maintainers, got no answer yet.
> Anything that could be done to get this fixed ?

Would you consider maintaining that file?

Best,
Christian
-- 
Stilblüten aus Polizeiberichten und Gerichtsverhandlungen:
Mein Mann ist sehr heimtückisch. Hohes Gericht, was mehrere Zeugen
beschwören können, weil er mir immer dann die Zunge herausstreckte,
wenn ich meine Brille putzte.

**Comment by Mathiasb17** [comment]
Hi !

Yes, this would be a pleasure !

Regards,
Mathias

**Comment by chrisbra** [comment]
Please go ahead and submit new runtime files to Bram. Please send complete files, add your name and a license and make a note of the previous maintainer.

**Comment by chrisbra** [comment]
I would rather think, the autoload/ada.vim file should respect the `g:no_plugin_maps` and `g:no_ada_maps` so that users can set either of those variables and those mappings shouldn't be set. 

It's fairly standard to have those variables to prevent mappings in other runtime files as well.

**Comment by TamaMcGlinn** [comment]
Ah, I didn't know about g:no_ada_maps - I take it that exists for all filetypes? g:no_plugin_maps would also change the behaviour of other plugins.

I have a PR ready to remove the mappings altogether; does anybody using Ada actually want these fairly useless functions mapped?

**Comment by TamaMcGlinn** [comment]
It would also be really good to have these mappings disabled without configuration - since it's pretty unintuitive that in Ada files you wouldn't be able to type `<leader>aj` and `<leader>al`, if we add these mappings at all, they should be triggered by an explicit user settings, like `g:ada_leader_mappings`

**Comment by dkearns** [comment]
The project is clearly still being maintained at https://github.com/krischik/vim-ada and although the relevant issue is marked as closed the [commentary](https://github.com/krischik/vim-ada/issues/13#issuecomment-1301845239) suggests it's still being considered.

Sometimes runtime file maintenance is slow, it's the nature of the beast.

**Comment by dkearns** [comment]
> I would rather think, the autoload/ada.vim file should respect the `g:no_plugin_maps` and `g:no_ada_maps` so that users can set either of those variables and those mappings shouldn't be set.

That has been added to the maintenance repo but hasn't been released yet.
