### ISSUE TITLE
Can't backspace over newline during insert/append

### ISSUE THREAD

**Issue by git1776** [vim/vim#13478]
### Steps to reproduce

insert new text with 'i' such as "**abc**<_newline_>**d**" then start backspacing.  The "**d**" is removed but I can't remove the <_newline_> or the "**abc**".  I just can't backspace over just-inputted newlines anymore.  This has always worked fine up now.  I wish I hadn't moved from ubuntu 18.04 to 22.04 but LTS had ended for 18.04.

### Expected behaviour

Should be able to backspace over newlines entered as part of i(nsert) or a(ppend) text etc

### Version of Vim

8.2.1847

### Environment

ubuntu 22.04 in csh

**Comment by zeertzjq** [comment]
Check the value of the 'backspace' option.

**Comment by git1776** [comment]
I added '**set backspace=indent,eol,start**' to my .vimrc (which wasn't needed before) and that fixed it.  Thanks.
