### ISSUE TITLE
strace ft not always detected

### ISSUE THREAD

**Issue by jirislaby** [vim/vim#13481]
Could this line:
https://github.com/vim/vim/blob/33c1da7ff49c3ccdce3a6d98bd620e324c5cd6ff/runtime/autoload/dist/script.vim#L372
be made:
```vim
  elseif (line1 =~ 'execve(' && line1 =~ '^[0-9:. ]*execve(')
```
because strace output, depending on parameters (`-ttf` this time) can dump both times and pid:
```strace
1038  07:14:20.959262 execve("./e.py", ["./e.py"], 0x7ffca1422840 /* 51 vars */) = 0 <0.000150>
```

**Comment by chrisbra** [comment]
-> PR please :)
