### ISSUE TITLE
Em dash digraph not working while unicode does work

### ISSUE THREAD

**Issue by TonyBarganski** [vim/vim#13483]
### Steps to reproduce

method 1. DIGRAPH:  insert Ctrl, k, --
(produces a hyphen)

method 2. UNICODE: insert Ctrl+v u2014
(produces an em dash)

### Expected behaviour

Expected behaviour is that the documented digraph (method 1) should produce an em dash character; instead, it produces a hyphen character.

The documented unicode method of inserting an em dash character, does produce the em dash; but takes a lot more keystrokes to achieve.

### Version of Vim

9.0.1550

### Environment

macOS
xterm-256color
BASH 5.2.15(1)-release  (aarch64-apple-darwin22.1.0)

### Logs and stack traces
Here's the vim log attached.
[myVimLog.txt](https://github.com/vim/vim/files/13250550/myVimLog.txt)

**Comment by zeertzjq** [comment]
The documented digraph is `-M`.

**Comment by TonyBarganski** [comment]
#### :digraph menu
When viewing ```:digraph``` on a bigger screen, I can see that @zeertzjq—you are correct!  

![image](https://github.com/vim/vim/assets/46673133/b1f3c240-d9c4-4a9f-981c-21c3ce1abd4d)

### ChatGPT
![image](https://github.com/vim/vim/assets/46673133/ad4ececc-c80e-4749-a1f3-d6be4b0396c9)

Seems that [ChatGPT](https://chat.openai.com/) has been giving me inaccurate data.

**Comment by chrisbra** [comment]
seriously, you asked ChatGPT? What about reading the documentation?

**Comment by TonyBarganski** [comment]
That's a valid question @chrisbra although I feel you may have meant it as rhetorical.
Firstly, why not ask ChatGPT?
Secondly, if you try and search for "dash" in the vim documentation, there is nothing about the digraph em dash.
Lastly, its very difficult to se is from the `:digraph` bitmap that is printed, particularly on a laptop screen. 

One may have the greatest features and product in the world, but if no one knows it, they won't use it! IMHO

**Comment by zeertzjq** [comment]
The digraph list has capitalized descriptions.

**Comment by chrisbra** [comment]
First of all, digraphs are documented in the help document: [digraph.txt](https://github.com/vim/vim/blob/master/runtime/doc/digraph.txt) so `:h digraph.txt` has all information you need (including a listing of all digraphs).

Or you can search using the `:helpgrep` command: `:helpgrep em.dash\c` (I added the `\c` to make sure we ignore case when searching). Then it is the first match.

**Comment by k-takata** [comment]
To know how to see the help, `:h 02.8` will help.

https://github.com/vim/vim/blob/2a94e9879283c55b162cf4e6d9ac7e0b0c35bc97/runtime/doc/usr_02.txt#L406-L413
We may need to mention ChatGPT here ;-)

**Comment by tonymec** [comment]
With Vim, the built-in help system covers everything, it is never (or extremely rarely) out-of-date, and in addition there are even two whole helpfiles dedicated to how to find info in the documentation:
```vim
:help " (or F1)
:help helphelp
```
To look into the whole help system for the string "em dash" (the \c is there to force caseless search):
```vim
:helpgrep em dash\c
```
There is one match, and it tells us that -M is the desired digraph.
Or
```vim
:h digraph.txt
```
will bring you to the helpfile about digraphs, then
```vim
/em dash
```
will bring you to the correct line (if `'ignorecase'` is set then \c is not necessary here, but you can still add it to force caseless search regardless of the `'ignorecase'` setting).

Or the first help item of the `digraph.txt` helpfile tells us that
```vim
:digraphs!
```
(which you may shorten to `:dig!`) displays all available digraphs (the `!` adds subtitles to make it easier to find what you need), then on the first line below **Punctuation** (with my screen size and `'guifont'` setting it is about one screen down from the top) the digraph you want is described as
```
-M —  8212
```
meaning that the digraph `-M` is the one for the em dash character, i.e. `—` or 8212 decimal. Of course, to enter that in Insert mode you would type `Ctrl-K -M`, as the help item `:h i_digraph` (the first one under `:h digraphs-use`) tells us.

All the above tells us that the official Vim help, installed with the program, has the correct desired info, and that ChatGPT, which is not affiliated with Vim, is in this case incorrect or at least misleading.

Best regards,
Tony.
