### ISSUE TITLE
Changelist not saved

### ISSUE THREAD

**Issue by git1776** [vim/vim#13484]
### Steps to reproduce

1. Edit a file and make a change
2. Save and exit
3. Edit the same file again
4. Command `g;` used to return to the position of the last change.  Now I get `E664: changelist is empty,` so the changelist is apparently no longer saved by default

### Expected behaviour

With the vim on  my previous ubuntu 18.04 installation, the changelist was stored somewhere after changing/saving a file so that when the same file was edited again`g;` returned to the location of the last edit.  Is this something in `.vimrc` I need to enable now?

How can I add a question like this if I'm not sure it's a bug?  (It may be a change in default behavior that just needs a config update)

### Version of Vim

8.2.1847

### Environment

Ubuntu 22.04, csh (xterm)

**Comment by chrisbra** [comment]
Please verify your viminfo setting: https://vimhelp.org/options.txt.html#viminfo-%27

Also this may happen, if you wiped your viminfo in between.

**Comment by git1776** [comment]
My `.vimrc` has `set viminfo='100,<100,:20,%,n~/.viminfo`

```
% ls -l ~/.viminfo
-rw-r--r-- 1 ian ian 28303 Oct 21 19:32 /home/ian/.viminfo
```

I haven't changed any of this.  I just backed up my old home dir and put it on the new system (after wiping the disk).  The `.viminfo` is full of old stuff like always-- definitely not wiped.

**Comment by chrisbra** [comment]
well, check your viminfo, if it contains entries for the changes.

**Comment by git1776** [comment]
I saved a copy of `.viminfo` then edited a file, appended a line, wrote it out and quit.  After that the current `.viminfo` was identical to the saved copy (according to `cmp`).
```% ls -l .viminfo*
-rw-r--r-- 1 ian ian 28303 Oct 21 19:32 .viminfo
-rw-r--r-- 1 ian ian 28303 Nov  4 09:46 .viminfo_old
```
The active `.viminfo` has an old date, hmm.  I added a comment and wrote it out no problem and can see the date was updated to  today so it's definitely writable:
```
% ls -l .viminfo*
-rw-r--r-- 1 ian ian 28309 Nov  4 09:59 .viminfo
```
I changed the mode to 0666 but it made no difference.

I notice when saving that console messages like this appear:

```
Nov  4 10:07:18 spunky dbus-daemon[1150]: [session uid=1000 pid=1150] Activating via systemd: service name='org.freedesktop.Tracker3.Miner.Extract' unit='tracker-extract-3.service' requested by ':1.10' (uid=1000 pid=1217 comm="/usr/libexec/tracker-miner-fs-3 " label="unconfined")
Nov  4 10:07:18 spunky systemd[1113]: Starting Tracker metadata extractor...
Nov  4 10:07:18 spunky dbus-daemon[1150]: [session uid=1000 pid=1150] Successfully activated service 'org.freedesktop.Tracker3.Miner.Extract'
Nov  4 10:07:18 spunky systemd[1113]: Started Tracker metadata extractor.
Nov  4 10:07:19 spunky kernel: [ 8148.014179] audit: type=1400 audit(1699117639.918:160): apparmor="DENIED" operation="open" class="file" profile="firefox" name="/proc/2338/oom_score_adj" pid=1544 comm="firefox" requested_mask="w" denied_mask="w" fsuid=1000 ouid=1000
Nov  4 10:07:21 spunky kernel: [ 8150.015949] audit: type=1400 audit(1699117641.918:161): apparmor="DENIED" operation="open" class="file" profile="firefox" name="/proc/2338/oom_score_adj" pid=1544 comm="firefox" requested_mask="w" denied_mask="w" fsuid=1000 ouid=1000
```
No idea what any of that's about, but thought I'd include it just in case there's a clue.

**Comment by chrisbra** [comment]
those messages are unrelated. Can you try using `:wviminfo` or `:rviminfo`. Is your changelist loaded after `:rviminfo`? If not, does your viminfo contain the changelist entries?
You may also use `:verbose :readviminfo` to see if any errors come up.

**Comment by git1776** [comment]
```
:wviminfo
E319: Sorry, the command is not available in this version
:rviminfo
E319: Sorry, the command is not available in this version
```

**Comment by yegappan** [comment]
It looks like you are using the tiny or small version of Vim with a minimal feature set.  Can you try using the normal or huge version of Vim?  What is the output of the `:version` command?

**Comment by git1776** [comment]
I was using the vim that came with my ubuntu 22.04, but I checked to see if I had the latest.  Looks like not:
```
% sudo apt-get install vim
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libid3tag0 libimlib2 libjpeg-progs libjpeg9 yudit-common
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  vim-runtime
Suggested packages:
  ctags vim-doc vim-scripts
The following NEW packages will be installed:
  vim vim-runtime
0 upgraded, 2 newly installed, 0 to remove and 15 not upgraded.
Need to get 8,568 kB of archives.
After this operation, 37.6 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
```
It's still vim 8.2.1847 but it's different and now it knows how to update the `.viminfo` and is working properly.  This doesn't make much sense since vim came with the installation, yet `The following NEW packages will be installed:   vim vim-runtime`

Also, I had to set backspace options before since that was not working like it used to; I commented that out of my `.vimrc` and got my original backspace behavior too.

Thank you for your help.  There's nothing on the vim startup screen that indicated the old version was minimal-features.  Maybe there should be.

**Comment by chrisbra** [comment]
That's what the `:version` command is for. I suppose it is fixed then, so closing.

**Comment by git1776** [comment]
I _had_ chosen the minimal installation of ubuntu 22.04, not the full install, but I was thinking I would get fewer utilities that way and save space, not that I'd get reduced-size/reduced-features versions of basic utils liike vi.
