### ISSUE TITLE
Matching parenthesis highlights are not updated when completion popup is visible

### ISSUE THREAD

**Issue by echasnovski** [vim/vim#13493]
### Steps to reproduce

1. Create an 'init.vim' file with the following content:
```vim
set nocompatible
```
2. Open Vim with that init file and 'matchparen' plugin loaded. For example, for local build I used `VIMRUNTIME=./runtime src/vim --clean -u init-matchparen.vim`.
3. Enter Insert mode and add lines `aa`, `aaa`, and `(a)`. Exit Insert mode.
4. Put cursor on the closing bracket in last line. This should highlight matching brackets.
5. Enter Insert mode with `i` and press `<C-n>`. This should open completion popup and select first `aa` entry. The highlight of the right bracket did not change and now over the second `a`. Pressing `<C-n>` again changes inserted text to `aaa` but highlight is still at the same place.

### Expected behaviour

Matched parenthesis are always highlighted even if completion popup is visible.

------

I've bisected the history, and it was the #13393 that introduced the issue. My guess would be because `s:Highlight_MatchingPair()` is called on `CursorMovedI` and `TextChangedI`, both not triggered if popup menu is visible. Adding `TextChangedP` [here](https://github.com/vim/vim/blob/2a94e9879283c55b162cf4e6d9ac7e0b0c35bc97/runtime/plugin/matchparen.vim#L28) fixes the issue, but I am not sure if this is a good solution here. Also not sure why it had worked before, but started to show only after #13393.

### Version of Vim

9.0.2092

### Environment

Operating system: EndeavourOS Linux x86_64 (6.5.9-arch2-1)
Terminal: st-0.9
Value of $TERM: st-256color
Shell: zsh 5.9

**Comment by zeertzjq** [comment]
I think this is because `:3match none` no longer works.

**Comment by chrisbra** [comment]
hm, don't get it. Where was `:3match none` used before?

**Comment by echasnovski** [comment]
> hm, don't get it. Where was `:3match none` used before?

Might be [this one](https://github.com/vim/vim/blob/2a94e9879283c55b162cf4e6d9ac7e0b0c35bc97/src/insexpand.c#L1335).

**Comment by chrisbra** [comment]
oh that is probably right

**Comment by chrisbra** [comment]
Hm, I would think it should be fine, to just stop highlighting in case of insert mode completion. Please check https://github.com/vim/vim/pull/13524

**Comment by echasnovski** [comment]
@chrisbra, yes, it does fix the issue.

**Comment by echasnovski** [comment]
Thanks, Christian!
