### ISSUE TITLE
Format option "n" doesn't work as described

### ISSUE THREAD

**Issue by lkintact** [vim/vim#13503]
### Steps to reproduce

1. Run `gvim -u NONE`
2. Execute `:set autoindent`
3. Execute `:set formatoptions+=n`
4. Enter Insert mode and type `1. the first item`. Press <kbd>Enter</kbd> and type `wraps`.
You get the following text in the buffer:
```
1. the first item
wraps
```

### Expected behaviour

You should get the following text:
```
1. the first item
   wraps

```
as described at `:help fo-n`.

### Version of Vim

gVim version 9.0.2073

### Environment

OS: Windows 10 Home
Terminal: GUI.

**Comment by chrisbra** [comment]
hm, it seems to work using `gq` or auto-wrapping (and when the textwidht is e.g. 15 for your example), but not when manually pressing enter. Strange

**Comment by chrisbra** [comment]
I checked it. Note how the documentation mentions: "when **formatting** text", so this only applies, if you are actually formatting text:

```
n	When formatting text, recognize numbered lists.  This actually uses
	the 'formatlistpat' option, thus any kind of list can be used.  The
	indent of the text after the number is used for the next line.  The
	default is to find a number, optionally followed by '.', ':', ')',
	']' or '}'.  Note that 'autoindent' must be set too.  Doesn't work
	well together with "2".
```

Pressing Enter in insert mode, **does not** format text, unless you have the *auto-format* [:set fo+=a](https://vimhelp.org/change.txt.html#fo-a) option enabled.

**Comment by lkintact** [comment]
Got it, thanks for explaining.
