### ISSUE TITLE
[vim9class] `_` description does not conform to common meaning

### ISSUE THREAD

**Issue by errael** [vim/vim#13504]
### Steps to reproduce

This issue comes from #13457, it's the only thing in that discussion that has general agreement.

Note: this issue is only about documentation; no code changes are implied/suggested. Read #13457 for the broader discussion.

The following table is summary, taken from https://en.wikipedia.org/wiki/Access_modifiers,

| Keyword | maximal access |
| -------- | ------ |
| private   | class |
| protected | derived classes |

shows two widely used access methods and how they are named.

Vim uses `_` for what most OOP languages call protected, OK; the problem is that it describes `_` as private. This causes confusion and is contrary to accepted nomenclature.

Additionally, if there is ever work to extend/update the access model, for example
- hiding variables from derived classes (commonly called private)
- accessible from within the file defining the class

then using "private" in the docs, when "protected" is the common meaning, likely complicates future changes.

@yegappan, @chrisbra If there's agreement to change the docs from private to protected, and no one wants to address the issue, then I can take a first cut at it and it can be wordsmithed and cleaned up in PR review.
(AFAIK, no response is not agreement)

### Expected behaviour

`_` is documented as "protected"

### Version of Vim

9.0.2092

### Environment

ubuntu

**Comment by chrisbra** [comment]
fine with me. @yegappan what do you think?

**Comment by yegappan** [comment]
Sounds good to me.

**Comment by Shane-XB-Qian** [comment]
@yegappan so there actually not really a  'private' class var existed? what's the different between _foo and _Foo? seems for now it would not raise err for that.

--
shane.xb.qian

**Comment by Shane-XB-Qian** [comment]
I mean you maybe can make _foo (lower case) work as a real private class var.
OOP language generally had that, tho in vim script not sure if it had to.

--
shane.xb.qian

**Comment by yegappan** [comment]
> Sounds good to me.

Can you hold on making these changes?

I am wondering whether we should change the access from protected to private for these variables?
Bram originally intended only for private variables and not for protected variables.  The changes
introduced in 9.0.1804 (inside_class_hierarchy() function) changed this.

**Comment by yegappan** [comment]
> > Sounds good to me.
> 
> Can you hold on making these changes?
> 
> I am wondering whether we should change the access from protected to private for these variables? Bram originally intended only for private variables and not for protected variables. The changes introduced in 9.0.1804 (inside_class_hierarchy() function) changed this.

If we go with the current implementation, then in the future, if we need to support private
variables, then we need to either introduce the "private" keyword or find some other way.
As private variables will be more common than protected variables, we can special case
protected variables.

**Comment by Shane-XB-Qian** [comment]
yea, I think it is too late to change that (or adding that 'private' keyword) which had have a very loooong discussion at #12932 since you already made that decision: no 'private' keyword and using _underscore, and the default is 'readonly'.
// tho I may prefer that's not the default, and had a keyword 'private', but just too late to change it back, or change that decision again.


--
shane.xb.qian

**Comment by errael** [comment]
> > Sounds good to me.
> 
> Can you hold on making these changes?
> 
> I am wondering whether we should change the access from protected to private for these variables? Bram originally intended only for private variables and not for protected variables. 

I don't see that. In Bram's last commit of vim9class.txt
```
Sat Apr 22 22:40:14 2023 +0100
Update runtime files
```
 it says: note the use of `(and [in]sub-classes)`

https://github.com/vim/vim/blob/f39d9e9dca443e42920066be3a98fd9780e4ed33/runtime/doc/vim9class.txt#L840-L850

> The changes introduced in 9.0.1804 (inside_class_hierarchy() function) changed this.

My recollection is that the access model implementation didn't meet spec in several ways.

**Comment by yegappan** [comment]
> > > Sounds good to me.
> > 
> > 
> > Can you hold on making these changes?
> > I am wondering whether we should change the access from protected to private for these variables? Bram originally intended only for private variables and not for protected variables.
> 
> I don't see that. In Bram's last commit of vim9class.txt
> 

You are correct.  I built Vim using the last commit from Bram.  In this image,
the child object methods are able to access the private variables in the parent class.
So this is not caused by 9.0.1804.

Interestingly the "No protected object members" section in vim9class.txt states that
only private members are supported.  But the behavior is that of protected members.

Please go ahead with the PR for updating the help text.

> ```
> Sat Apr 22 22:40:14 2023 +0100
> Update runtime files
> ```
> 
> it says: note the use of `(and [in]sub-classes)`
> 
> https://github.com/vim/vim/blob/f39d9e9dca443e42920066be3a98fd9780e4ed33/runtime/doc/vim9class.txt#L840-L850
> 
> > The changes introduced in 9.0.1804 (inside_class_hierarchy() function) changed this.
> 
> My recollection is that the access model implementation didn't meet spec in several ways.

**Comment by Shane-XB-Qian** [comment]
> Interestingly the "No protected object members" section in vim9class.txt states that
only private members are supported. But the behavior is that of protected members.

so conclusion is what? it's really no private class var, and what previously argued the  term 'private' actually not existed and no plan to implement it? or would make _foo work it as it?

--
shane.xb.qian

**Comment by yegappan** [comment]
>> Interestingly the "No protected object members" section in vim9class.txt states that
>> only private members are supported. But the behavior is that of protected members.
>
> so conclusion is what? it's really no private class var, and what previously argued the term 'private' actually not existed and no plan to implement it? or would make _foo work it as it?

In the current implementation only protected object variables are supported and private object variables are not supported.

**Comment by Shane-XB-Qian** [comment]
so how about make _foo (lower case) work as private class var? the prefix _ underscore looked like a mark, since already designed like that and vim's tradition usually it should be upper case, then how about make _foo (lower case) work for real private class var?
// dunder __foo and __Foo maybe need to limit to latter one only too.
// though personally I don't like such underscore.

--
shane.xb.qian

**Comment by Shane-XB-Qian** [comment]
note this just is a question, since the 'protect' actually was I recommend (#11827) to Bram,
but/and the 'private' and _underscore was there a lot argu (#12932), so/but now turn out dramatically this is the end?
ok, if yes, I think we can live with it (for now).

--
shane.xb.qian

**Comment by errael** [comment]
It looks like Bram intended `_` to mean protected behavior all along, see https://groups.google.com/g/vim_dev/c/yYpFNUHdRho. 

But for whatever reason, he decided to call it "private", contrary to the accepted meaning of "private" in a class hierarchy. #13520 changes documentation only.
