### ISSUE TITLE
go error highlighting should be disabled by default

### ISSUE THREAD

**Issue by nhooyr** [vim/vim#1351]
I find it incredibly annoying that it keeps highlighting things as errors as I am typing. It doesn't make much sense and it isn't very useful.

https://github.com/vim/vim/blob/master/runtime/syntax/go.vim#L31-L45

It should be disabled by default. It isn't something vim normally does for any other language, it's usually deferred to a plugin.

**Comment by nhooyr** [comment]
Watch https://asciinema.org/a/1pakyg673na373820djkl0b1q for what I mean

**Comment by chrisbra** [comment]
Please contact the maintainer of the file.

**Comment by nhooyr** [comment]
Forgot about that, thanks!

**Comment by nhooyr** [comment]
Should be merged soon at google/vim-ft-go#3

**Comment by chrisbra** [comment]
closing this then. You might want to ask google/vim-ft-go to send an updated syntax file to Bram, once this has been resolved.
