### ISSUE TITLE
Inconsistent behavior for visual selection of inner 'block' text-objects when block is empty i( i[ i{

### ISSUE THREAD

**Issue by laurentalacoque** [vim/vim#13514]
### Steps to reproduce

1. run vim and paste the following examples into a buffer
2. position the cursor as indicated by the highlight (e.g. the cursor is here ->`.`)
3. type `vib` to extend the selection to the inner part of the parenthesis
4. check the hightlighted range and compare it to what it's expected to be.

### Expected behaviour

**Problem**
In the context of multiple parentheses groups chain (e.g. '`(text)()`'), when visually selecting the inner part of _empty_ parentheses using `vib` with the cursor positionned on the opening parenthesis, the block selected is actually the previous one.

Moreover, if the preceding group is also empty, the pair of parentheses of the _previous_ group is selected despite it being an 'inner' selection (see Example3)

In these contexts, I would expect a fail of the text-object, hence leading to only the character at the current position being visually selected.

In the examples below, `highlighted range` represent 
- the cursor position in the starting position (nothing selected)
- visually selected range in the resulting/expected position

______________________________________________________________________
**Example1**
start:
> (text)`(`)

command:
>vib

result:
> (`text`)()

expectation:
>(text)`(`)
________________________________________________________________________
**Example2**
start:
> (text)`(`
> )

command:
>vib

result:
> (`text`)(
> )

expectation:
> (text)`(`
> )
________________________________________________________________________
**Example3**
start:
> ()`(`)

command:
>vib

result:
> `()`()

expectation:
> ()`(`)
________________________________________________________________________
**Final note**
Same behavior applies to other 'block' text-objects such as `i[` and `i{`

### Version of Vim

:version VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Mar  8 2023 17:49:58) Included patches: 1-1393 

### Environment

Operating system : Linux 3.10.0-1160.53.1.el7.x86_64 (scientific linux 7)
Shell: tcsh 6.18.01
Term: xterm version XTerm(327)
$TERM: xterm-256color

**Comment by benknoble** [comment]
Related: https://vi.stackexchange.com/q/43470/10604

**Comment by laurentalacoque** [comment]
> Related: https://vi.stackexchange.com/q/43470/10604

Indeed, same poster 😉

**Comment by habamax** [comment]
It kind of breaks my usual workflow now:

Before this I was able to `cib` while my cursor was before `()` and start adding parameters in `def SumFunc()`. Now I can't.

Can we revert this?

**Comment by benknoble** [comment]
@habamax that seems unrelated to the reported issue, unless I'm misreading the cases in the issue and your workflow (which I also use). If so, it seems the patch changed behavior it didn't mean to?

**Comment by habamax** [comment]
> If so, it seems the patch changed behavior it didn't mean to?

I believe so.

**Comment by habamax** [comment]
So far it affects `()`, `{}` and `[]` -- I can't use `cib/ciB/ci[` to edit empty parens.

At the same time it still works for `""`, `''` and empty backquotes.

**Comment by chrisbra** [comment]
So is this only relevant for `Change` operations?

How about this then:
```diff
diff --git a/src/textobject.c b/src/textobject.c
index af94d06bc..675367829 100644
--- a/src/textobject.c
+++ b/src/textobject.c
@@ -1131,9 +1131,10 @@ current_block(
                break;
        }

-       if (EQUAL_POS(start_pos, *end_pos))
-           // empty block like this: ()
-           // there is no inner block to select, abort
+       // empty block like this: ()
+       // there is no inner block to select, abort
+       // but allow this for OP_CHANGE
+       if (EQUAL_POS(start_pos, *end_pos) && oap->op_type != OP_CHANGE)
            return FAIL;

        /*
```

**Comment by habamax** [comment]
It fixes `cib`/`ciB`/`ci{` but introduces another issue with visual blocks (`vib` here):

https://asciinema.org/a/oQnkgR2GoGfA7KrIjiA5fZsN5

**Comment by habamax** [comment]
This change works, it stays on the same position if there was empty block:

```
	if (EQUAL_POS(start_pos, *end_pos) && VIsual_active)
	{
	    // empty block like this: ()
	    // there is no inner block to select, abort
	    curwin->w_cursor = old_pos;
	    return FAIL;
	}

```

https://asciinema.org/a/fRHpbKlZhlx8MLACuS6Jo9kHD

**Comment by habamax** [comment]
let me create a separate PR
