### ISSUE TITLE
Icon in TaskBar is repeated instead of shared

### ISSUE THREAD

**Issue by errael** [vim/vim#13527]
### Steps to reproduce

This started happening sometime over the last few weeks; before then there was a single vim icon as seen with the FireFox icon. In the attached image FirFox has 3 windows.

I have no idea if this is a Vim dependent issue. Even if it is, it may be related to some change in the window manager, some library or other OS thing; I regularly update my system's software. And I regularly build/update vim. Note I start gvim from a login shell

I have a build of vim9.0 and it has the problem, but it was recently built; this would seem to narrow the problem down to some recent update of the system's software. But it doesn't preclude some vim setting that may have changed, inadvertently or otherwise, or that may now be required due to a recent change in the system's software.

Looking here first in case it rings a bell...

### Expected behaviour

Single Vim icon for multiple vim processes.

### Version of Vim

9.0.2100

### Environment
```
Linux harmony 6.5.6-76060506-generic #202310061235~1697396945~22.04~9283e32
SMP PREEMPT_DYNAMIC Sun O x86_64 x86_64 x86_64 GNU/Linux
```
```
$ env|grep XDG
XDG_CONFIG_DIRS=/etc/xdg/xdg-pop:/etc/xdg
XDG_MENU_PREFIX=gnome-
XDG_SESSION_DESKTOP=pop
XDG_SESSION_TYPE=x11
XDG_CURRENT_DESKTOP=pop:GNOME
XDG_SESSION_CLASS=user
XDG_RUNTIME_DIR=/run/user/1000
XDG_DATA_DIRS=/usr/share/pop:/usr/share/gnome:/home/err/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
```
![TaskBar](https://github.com/vim/vim/assets/20450427/6f6d6ccd-5e0c-4e4e-af36-665a7b91137d)

**Comment by chrisbra** [comment]
I don't think this is a bug of Vim. We haven't touched the gui code in a while.

**Comment by errael** [comment]
Closing. Opened a ticket with System76.

**Comment by tonymec** [comment]
I can't reproduce this with gvim 9.0.2103 (Huge, GTK3) on openSUSE Tumbleweed. I'm not sure which window manager I am using: I think it is Gnome but it might be KDE.
I have one instance of gvim already running (started from an xterm), I started a second gvim from a konsole tab, and then I pressed the Windows key to see the taskbar and there was only one Vim icon, with (as in your screenshot) a dot under it. I have two konsole windows and three xterms but in each case there is only one dot under the icon.

Best regards,
Tony.

**Comment by tonymec** [comment]
P.S.
```
linux-tuxedo:~ # env|grep XDG
XDG_CONFIG_DIRS=/etc/xdg:/usr/local/etc/xdg:/usr/etc/xdg
XDG_MENU_PREFIX=gnome-
XDG_SESSION_DESKTOP=default
XDG_SESSION_TYPE=x11
XDG_CURRENT_DESKTOP=GNOME
XDG_ACTIVATION_TOKEN=gnome-shell/Konsole/4211-7-linux-tuxedo_TIME826426
XDG_SESSION_CLASS=user
XDG_RUNTIME_DIR=/run/user/0
XDG_DATA_DIRS=/root/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
linux-tuxedo:~ # 
```
Best regards,
Tony.

**Comment by errael** [comment]
@tonymec Thanks for taking a look.

> in each case there is only one dot under the icon

I don't know if the TaskBar is considered part of the window manager; the difference in the number of "white dot"s is interesting.

The problem is fixed now. I did `sudo apt install vim-gtk3`, ran that vim. Since then things are back to normal, one icon and one "white dot" per instance of vim (up to 4). Perhaps doing the installation changed a setting somewhere; or running the "stock" ubuntu gvim image changed something.
