### ISSUE TITLE
opening a directory in a new tab from within a try block

### ISSUE THREAD

**Issue by nhooyr** [vim/vim#1353]
`try | tab split /bin | endtry` doesn't work.

See junegunn/fzf.vim#102 and https://groups.google.com/forum/#!msg/vim_use/EeQM4EWP7IY/yFrhedMDWCAJ

**Comment by vim-ml** [comment]
On Jan 5, 2017 07:04, "Anmol Sethi" <vim-dev-github@256bit.org> wrote:
>
> No idea why, but try | tab split /bin | endtry doesn't work.
>
> See junegunn/fzf.vim#102 and
https://groups.google.com/forum/#!msg/vim_use/EeQM4EWP7IY/yFrhedMDWCAJ

Because a directory is considered an error. I really wonder about the
purpose of that, and if it could be made not an error.

---
Justin M. Keyes

**Comment by pavoljuhas** [comment]
> `try | tab split /bin | endtry doesn't work.`

What do you want to happen if the `/bin` directory did not exist?
As it stands, vim would open a new file `/bin` in a new tab, but that does not seem very predictable.

Perhaps an `if` block is more appropriate here than the `try` one:

```VimL
if isdirectory('/bin')
    tab split /bin
endif
```

**Comment by nhooyr** [comment]
@pavoljuhas that's not the point of the issue. The snippet doesn't open the directory even if it exists is the problem.

**Comment by justinmk** [comment]
Patch here: https://github.com/neovim/neovim/pull/5933

**Comment by brammool** [comment]
Just Keyes wrote:

> Patch here: https://github.com/neovim/neovim/pull/5933

Perhaps someone can turn this in a Vim patch?  Most of the diff is
reformatting which we don't want in Vim.


-- 
Place mark here ->[ ]<- if you want a dirty monitor.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by justinmk** [comment]
I'll post a vim patch shortly. (done: #1375)
