### ISSUE TITLE
Broken match highlighting of multiline patterns

### ISSUE THREAD

**Issue by pcapriotti** [vim/vim#13536]
### Steps to reproduce

In `vim --clean`:
Create a buffer with the text
```
a
b





a
b
```

Scroll with Ctrl-E, so that the first `b` is at the top of the window. Run `:set hlsearch`. Move to an empty line and search with `/a\nb`. Only the second match is highlighted. After scrolling up, the `a` on the first match is highlighted, but not the `b`.

### Expected behaviour

Partially visible matches at the top of the window should be highlighted.

### Version of Vim

9.0. Included patches: 1-2070.

### Environment

OS: arch linux
Terminal: alacritty

**Comment by chrisbra** [comment]
is this a regression?

**Comment by chrisbra** [comment]
it's an drawing optimization. Basically Vim only checks for the visible lines whether the search pattern matches. After scrolling the first matching line out of the window viewport, the second line can no longer match the search pattern and therefore no highlighting is applied.
For the other issue, when scrolling the line with the start of the pattern back into the viewport, will will redraw that line, but skip looping over the rest of the lines again for performance reasons. 

I don't want to change this, we have had many complaints in the past about redrawing being slow and this seems such a minor problem, which is just a `Ctrl-L` away from being fixed. I think it is okay if we leave it like this.
