### ISSUE TITLE
Missing Rust syntax highlighting - regression

### ISSUE THREAD

**Issue by zdohnal** [vim/vim#1354]
Hi,
I have discovered that rust  syntax highlighting disappeared in vim-8.0 (current patch level 142). It was ok with vim-7.4, but now it's gone. I checked runtime/syntax files, but I did not find any file in 7.4 version, which was for rust syntax. Was it included in some other file or what happened?

**Comment by chrisbra** [comment]
Hm, it looks like in vim 7.4 *.rs files were detected as filetype hercules. Now with Vim 8 we detect this as filetype rust, however there is no syntax script for rust. I have just created https://github.com/rust-lang/rust.vim/issues/134 to have them submit it to Vim. Closing therefore.
