### ISSUE TITLE
When doing configure, errors are silently ignored, leaving the user confused

### ISSUE THREAD

**Issue by ethouris** [vim/vim#13558]
### Steps to reproduce

Run the build, while having no gtk3-devel package installed in the system (for example):
1. Type ./configure --enable-gui=gtk3
2. Configure step is successful
3. Run make
4. Run `vim -g` from `src/` directory, as freshly compiled
Error: GUI not enabled at compile time.

### Expected behaviour

If the user has specified `--enable-gui=gtk3` it simply means that they WANT GUI to be compiled in, and if appropriate libraries are not available, `configure` should interrupt with error. This exactly thing happens when you don't have, for example, `ncurses-devel` installed while you specified `--enable-terminal`.

### Version of Vim

9.0.2122

### Environment

Centos 7.9.2009

### Logs and stack traces

```shell
checking for xmkmf... no
checking for X... (cached) no
checking if X11 header files can be found... no
checking --enable-gui argument... no GUI support
checking for pkg-config... (cached) /usr/bin/pkg-config
checking for X11/SM/SMlib.h... (cached) no
no GUI selected; xim has been disabled
checking for /proc link to executable... /proc/self/exe
```

**Comment by chrisbra** [comment]
Please use the `--fail-if-missing` in addition

**Comment by tonymec** [comment]
Unless `--fail-if-missing` is used, configure will do a "best effort", configuring with what you have installed.
For instance, if you use `--enable-gui=GTK3` but there is no GTK3 "development" package, you will probably end up with a Vim without GUI.
In that case you must find, depending on your distribution, the appropriate `-devel` or `-dev` packages for everything you haven't got and want, install them, make sure you have the appropriate environment variables set for the configure arguments you want, and run `make reconfig`.

The reason to set your configure arguments by means of environment variables is twofold:
* this way you don't need to edit the Makefile so when there are changes in it you won't have problems with them
* sometimes Make decides to run configure as part of a normal `make` run: in that case it will pick up your configure settings from the environment and use your preferred configuration.

Here is a script I use in a bash shell to set the environment for a "maximum" Vim considering what I have installed; if you use it you will have to make changes in it, at least in the last line, and possibly elsewhere depending on your configuration preferences. One caveat is that such a script must be **sourced**, not **executed**, by the shell. I compile several Vims with different configuration arguments, each of them in its own separate "shadow directory", with its own name, its own configure arguments and in its own separate shell; if you compile only one Vim you will probably prefer to omit the second-last line (or replace it with its default, `export CONF_ARGS2='with-vim-name=vim'`):
```bash
# configure parameters for a maximum Vim
export CONF_OPT_GUI='--enable-gui=gtk3'
export CONF_OPT_PERL='--enable-perlinterp'
export CONF_OPT_PYTHON='--enable-pythoninterp'
export CONF_OPT_PYTHON3='--disable-python3interp'
export CONF_OPT_TCL='--enable-tclinterp'
# /usr/bin/tclsh (softlink) is correctly set
export CONF_OPT_RUBY='--enable-rubyinterp'
export CONF_OPT_LUA='--enable-luainterp'
export CONF_OPT_MZSCHEME='--disable-mzschemeinterp'
#export CONF_OPT_PLTHOME='--with-plthome=/usr/local/plt'
export CONF_OPT_CSCOPE='--enable-cscope'
export CONF_OPT_MULTIBYTE='--enable-multibyte'
export CONF_OPT_TERMINAL='--enable-terminal'
export CONF_OPT_AUTOSERVE='--enable-autoservername'
export CONF_OPT_FEAT='--with-features=huge'
export CONF_ARGS2='--with-vim-name=vim-huge'
export CONF_OPT_COMPBY='"--with-compiledby=antoine.mechelynck@gmail.com"'
```
Best regards,
Tony.
