### ISSUE TITLE
Empty list returned by range() with stride segfaults upon access

### ISSUE THREAD

**Issue by tpope** [vim/vim#13557]
### Steps to reproduce

With `vim --clean`:

```vim
:echo get(range(1, 0, 2), 0)
```

### Expected behaviour

Expecting to see the default `get()` return value of 0.

The requirements to reproduce this issue seem to be that the range is empty, and the stride is greater than 1.

Workaround is to pass the range to `copy()`.

Bonus: here's a less fatal variant that is exclusive to Vim9 Script:

```vim
def RangeTest()
  const range = range(1, 0, 2)
  for i in range
    echo i
  endfor
enddef

call RangeTest()
```

This script should produce no output, but instead, it echoes `1`.

### Version of Vim

[8.2.0159](https://github.com/vim/vim/commit/50985eb1f0bd3c73ce727f9bbd66c839c92ef0da) and newer (bisected)

### Environment

Reproduced on Ubuntu 22.04

**Comment by chrisbra** [comment]
that part of the patch 8.2.0159 seems strange:
```
@@ -5322,7 +5333,7 @@ f_range(typval_T *argvars, typval_T *rettv)
        list->lv_start = start;
        list->lv_end = end;
        list->lv_stride = stride;
-       list->lv_len = (end - start + 1) / stride;
+       list->lv_len = (end - start) / stride + 1;
     }
 }
```

and changing it back to this seems to fix this issue for me, but I need to verify this further

**Comment by chrisbra** [comment]
ah, that doesn't fix it
