### ISSUE TITLE
A couple expression overflow

### ISSUE THREAD

**Issue by errael** [vim/vim#13554]
### Steps to reproduce

```
echo foobar > xxx
gvim xxx
:set sw=0x180000000
<<
```
This results in
```
E342: Out of memory!  (allocating 18446744071562067974 bytes)
```
Not sure there is a bug here. I found two undetected overflows on the way to the out of memory error. I recently saw some error handing that was added to prevent overflow; in those cases the overflow didn't necessarily result in a bad memory access but it was detected by "Code scanning / CodeQL".

### Expected behaviour

It's unclear to me what error handling is **required** to do (other than prevent accessing memory that's not yours). Are overflows OK if they don't cause memory access errors? I guess they're not OK if a reliability tool flags them.

This report might be more about getting clarification; __closed as not planned__ seems OK. _Maybe this should be a discussion._

With the above setting of `sw`, upon entry to `shift_line()` there's
```
sw_val = (int)get_sw_value_indent(curbuf)
```
with values as seen by the debugger
```
p get_sw_value_indent(curbuf)           : $6 = 6442450944
p (int)get_sw_value_indent(curbuf)      : $7 = -2147483648
```
that demonstrates a negative `sw_val` from overflow.

At the end of `shift_line()` there's a call to `set_indent()` with count `INT_MAX`.
And then in `set_indent()` around line 681 there's
```
newline = alloc(ind_len + line_len)
```
the addition overflows
```
(gdb) p/x ind_len               : $12 = 0x7fffffff
(gdb) p line_len                : $13 = 13
(gdb) p/x ind_len + line_len    : $14 = 0x8000000c     ***OVERFLOW***
```
And at entry to lalloc, the negative number is sign extended into a size_t
```
(gdb) p/x size                  : $15 = 0xffffffff8000000c
```
Which is the value reported by the `Out of memory`

### Version of Vim

9.0.2116

### Environment

ubuntu

**Comment by chrisbra** [comment]
I would think this qualifies as a bug even so for me it does not error out with `Out of memory`.

I don't know why sw_val was casted down to `(int)`, potentially Bram wanted to prevent an overflow in the calculation of the amount of indent. 

I guess we need this patch then:
```patch
diff --git a/src/ops.c b/src/ops.c
index 9e8ea8616..7cb82b89f 100644
--- a/src/ops.c
+++ b/src/ops.c
@@ -230,8 +230,8 @@ shift_line(
     int call_changed_bytes)    // call changed_bytes()
 {
     long long  count;
-    int                i, j;
-    int                sw_val = (int)get_sw_value_indent(curbuf);
+    long       i, j;
+    long       sw_val = get_sw_value_indent(curbuf);

     count = (long long)get_indent();   // get current indent

```

**Comment by errael** [comment]
> I would think this qualifies as a bug even so for me it does not error out with `Out of memory`.

I tried it with `gvim -U NONE -u NONE` and did not get the memory overflow (but still, it was not a nice experience).

**Comment by errael** [comment]
> I don't know why sw_val was casted down to `(int)`

I wonder why `sw` option, and I suppose there are others, are `long` instead of `int`. I understand that 20 years ago things were very different (how big should things be?); but needing a `long` for indent seems way past what might be needed for this century.

**Comment by errael** [comment]
There's also an overflow identified in this issue in `set_indent()`. Since it is called with size `INT_MAX` in some cases, it's real easy to overflow and call alloc with a sign extended int. But since that should get `Out of memory`, probably nothing needs to be done. Does that sound right?

**Comment by chrisbra** [comment]
Arg, sometimes it feels touching one point of the code to fix a specific issue, causes 3 other issues to appear 🙈

**Comment by errael** [comment]
>  touching one point of the code to fix a specific issue, causes 3 other issues to appear

That reminds me of stories about OS360. Had 3 known bugs, tried to fix them, couldn't get the OS to stabilize, just left the bugs in.
