### ISSUE TITLE
CI: Test_terminal_resize() times out

### ISSUE THREAD

**Issue by chrisbra** [vim/vim#13566]
### Steps to reproduce

I don't know what exactly changed, but I noticed that Test_terminal_resize() seems to consistently time out in Github Action Runners. I don't know why (I tested it locally and the test worked fine) and it's quite strange, since the test-suite sets up a timer to kill Vim after 30 seconds, so I am wondering if it is waiting in some kind of user dialog, but who knows.

It only seems to happen with the ` linux (huge, gcc, uchar, testgui, true, dynamic)` test, but I am a bit hestitant to skip this test in the GUI on linux, as this may cause the CI to become green but doesn't fix the underlying problem.

So not sure what to do, but if anybody has an idea, please let me know.

### Expected behaviour

test should succeed of coures

### Version of Vim

v9.0.2120

### Environment

Github CI

### Logs and stack traces

```shell
See e.g. here: https://github.com/vim/vim/actions/runs/6973799374/job/18978429699


05:03 Executing Test_terminal_resize()
Error: The action has timed out.
```
```

**Comment by Shane-XB-Qian** [comment]
i do not know if it's about 'resize' or why, but some test cases cost a bit long, 
// e.g test_termdebug_basic() may take ~~5 mins (somehow in CI but not in local),~~
// Update: sorry it should be not meant 5mins, but just maybe a bit longer than normal.
so simply giving it a bit more budget (#13572), or maybe you can skip ~~e.g termdebug_basic()~~ in GUI.

**Comment by Shane-XB-Qian** [comment]
or i felt it looked like hang on something, i tried different timeout, it is a flaky result!
e.g https://github.com/Shane-XB-Qian/vim/actions/runs/6982679790 this worked, previously 25 and 35mins failed.

**Comment by chrisbra** [comment]
and now it is timing out in `test_terminal_resize2()` 🤦 https://github.com/vim/vim/actions/runs/7063506935/job/19229655246

**Comment by Shane-XB-Qian** [comment]
> and now it is timing out in `test_terminal_resize2()` 🤦 https://github.com/vim/vim/actions/runs/7063506935/job/19229655246

then do the same, or maybe can setup a timer to kill *that* test/task,
but still felt somehow something made it hang, that's a problem anyway.

-- 
shane.xb.qian
