### ISSUE TITLE
statusline filename modifier for relative to current window directory

### ISSUE THREAD

**Issue by nhooyr** [vim/vim#1357]
`expand(%:.)` prints the filename relative to the current global directory. We could add a new modifier or perhaps we could also just change it to print the filename relative to the current window directory and if that is not set, only then use the global directory.

**Comment by nhooyr** [comment]
Seems like this is a statusline only problem. See neovim/neovim#5891.

**Comment by ZyX-I** [comment]
I would name this “process current directory”: Vim already takes window and (neovim) tab directories into account as well as global directory, but this only means “when switching to some window change process cwd if needed”, so obviously this does not work for status lines where real switching is not done (internally some global pointers are adjusted, but this is just a hack used to make functions like `winnr()` work). I cannot remember any way to evaluate expressions in context of non-current window other then statuslines, so this may be named a “statusline only problem”.

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.
