### ISSUE TITLE
A research for generating PR checklists in Pull Request Template

### ISSUE THREAD

**Issue by chenkun1029** [vim/vim#13570]
Dear maintainers:
Our team is currently developing a tool for automatically generating PR checklists in Pull Request Template. The tool generates a set of PR rules based on the contribution guidelines in your project, which external contributors may be expected to adhere to. Below are the results of our generation:

**Test**: Add a test of triggering the Continuous Integration test.
**cla**: No CLA to sign.

Also, we suggest you add some checklist notes about **Documentation**, **Style**, **Branch**, **Title**, **Description**, **commit message**, and **contributing** which are also important for submitting PRs according to our analysis.

We hope you and your team can provide feedback on our generated output.
Best regards.

**Comment by chrisbra** [comment]
I am not sure what you want us to do here?

**Comment by chrisbra** [comment]
If your tool is "automatically generating PR checklists", please create a proper PR for this one so we can review. In the current form, I see this as not actionable, because it is not clear to me, what exactly you are missing and where should this be placed
