### ISSUE TITLE
Incorrect type reported for list<any> variable assigned an empty list

### ISSUE THREAD

**Issue by dkearns** [vim/vim#13582]
### Steps to reproduce

```vim
vim9script

var la: list<any> = []
echomsg typename(la)

var ln: list<number> = []
echomsg typename(ln)
```

Output: 

```
list<unknown>
list<number>
```

### Expected behaviour

Output: 

```
list<any>
list<number>
```

### Version of Vim

9.0.2130

### Environment

Ubuntu 20.04

**Comment by Shane-XB-Qian** [comment]
it maybe ok if 'any' is alias to 'unknown', but 'any' is 'number' seems definitely wrong:

```vim
var la: list<any>
echom typename(la)  # list<unknown>

var a: any
echom typename(a)  # number
```

**Comment by Nickwiz** [comment]
Just a note:

```vim
var x: list<any> = []
echom typename(x)  # list<unknown>

x[0] = 123
echom typename(x)  # list<any>

remove(x, 0)
echom typename(x)  # list<unknown>

```

So only unknown when empty. Not sure if it ever can change from `<any>` to say `<number>` once defined.

In regards to `any` being zero:

```vim
var a: any
echom typename(a) .. ' "' .. a .. '"'  # number "0"
var s: string
echom typename(s) .. ' "' .. s .. '"'  # string  ""
var n: number
echom typename(n) .. ' "' .. n .. '"'  # number "0"
var f: float
echom typename(n) .. ' "' .. f .. '"'  # float  "0.0"
var b: bool
echom typename(b) .. ' "' .. b .. '"'  # bool   "false"
```

> E1134
>
>Declaring a variable with a type but without an initializer will initialize to
>false (for bool), empty (for string, list, dict, etc.) or zero (for number,
>any, etc.).  This matters especially when using the "any" type, the value will
>default to the number zero.

**Comment by Shane-XB-Qian** [comment]
yes, i agreed it is ok if 'any' alias to 'unknown', but:
```vim
var a: any
echom typename(a)  # number
```
this is default to 'number' seems odd, but if that's intended, then let it be~

@yegappan FYI, i saw you opened #13625

**Comment by Shane-XB-Qian** [comment]
> > this is default to 'number' seems odd, but if that's intended, then let it be~
> 
> It can be anything. As it is _initialized to zero_ upon definition it is zero, which is a number.

no, the 'default' here meant *when* it is un-inited,
it is Not 'can be anything', so the 'default' is 'number' is odd.


> ```vim
> a = [1, 2, 3]
> echom typename(a) .. ' "' .. string(a) .. '"'  # any            "[1,2,3]"
> ```

this looks is odd too, why it is a 'any'?

**Comment by Nickwiz** [comment]
> no, the 'default' here meant _when_ it is un-inited,

Sure in perl etc, but here there is no such thing as an uninitialized  variable. Declaring it _**also initializes it**_ (if one want or not).

```
				*E1022* *E1103* *E1130* *E1131* *E1133*
				*E1134*
Declaring a variable with a type but without an initializer will initialize to
false (for bool), empty (for string, list, dict, etc.) or zero (for number,
any, etc.).  This matters especially when using the "any" type, the value will
default to the number zero.  For example, when declaring a list, items can be
added: >
	var myList: list<number>
	myList->add(7)

Initializing a variable to a null value, e.g. `null_list`, differs from not
initializing the variable.  This throws an error: >
	var myList = null_list
	myList->add(7)  # E1130: Cannot add to null list

```
***– will initialize***

---

>it is Not 'can be anything', so the 'default' is 'number' is odd.

But `any` can. It could also be string `''`, bool `false`, float `0.0`, special `null`, special `v:none` etc. But *any* of those would be *any*. Meaning in practice an `any` would less often, I would argue, be useful. I.e. Even `undefined` would be *anything*.

Say one use an `any` variable named `x` - now depending on *what type* that `x` is one want to do different things.

```
IF x IS NUMBER
	y = y × x
ELSE IF x IS STRING
	PRINT x
ELSE
	Throw error
END IF
```

An IF saying:

```
IF x IS ANYTHING <-- Moot check
	Do anything
END IF
```

That is at least the rationale I suspect behind it.

When it comes to:

```vim
a = [1, 2, 3]
echom typename(a) .. ' "' .. string(a) .. '"'  # any            "[1,2,3]"
``` 

Yes, that is harder to grasp. The one are back to the IF example above. There is likely a differentiation between simple and complex types …

The ` type` check is fine though:

```vim
echom type(a) == type([])	# true
echom type(a) == v:t_list	# true
```

**Comment by yegappan** [comment]
> Just a note:
> 
> ```viml
> var x: list<any> = []
> echom typename(x)  # list<unknown>
> 
> x[0] = 123
> echom typename(x)  # list<any>
> 
> remove(x, 0)
> echom typename(x)  # list<unknown>
> ```
> 
> So only unknown when empty. Not sure if it ever can change from `<any>` to say `<number>` once defined.
> 

With this PR, all the above three cases will echo `list<any>`

**Comment by Shane-XB-Qian** [comment]
um.. you may should read my another comment in that upstream ticket, here null and null_<type> is different things, that 'null' I think it actually (looked like) init nothing.

but anyway, since @chrisbra had mergerred this, so supposed it meant it was intended (designed like that), so let it be.

but just to me: assign to null to these and using typename() func to those, now the result is odd and much easier to be confused.
// I can live with that anyway, just not sure if it was a good idea.
// but at least seems now all well-known big issues on vim9script were all set, just good or bad may need more people to use, specially when if it still had chance to change.

--
shane.xb.qian
