### ISSUE TITLE
Single quotes break :!start ?

### ISSUE THREAD

**Issue by CrispyDrone** [vim/vim#13583]
### Steps to reproduce

Minimal reproducible example:

1. Execute `:!start 'https://www.google.com'`
2. E371: Command not found

I discovered this because I have disabled netrw and defined a function to open a URL:

```vimscript
function! HandleURL()                                           " Since we disable netrw gx will not work any more. Create a function for it
  let s:uri = matchstr(getline("."), '[a-z]*:\/\/[^ >,;()]*')
  "let s:uri = shellescape(s:uri, 1) 				" Shellslash breaks this. Not sure why! It adds single quotes somehow
    if s:uri != ""
      echom s:uri
      exec "!start " . s:uri
      redraw!
    else
      echo "No URI found in line."
    endif
endfunction
```

This worked fine until I added `set shellslash` on my system because I am using bash on windows. Now, it adds single quotes around the URL and breaks this function. Removing the `shellescape` invocation fixes the issue.

### Expected behaviour

Should open the default browser and browse to `https://www.google.com`.

### Version of Vim

8.2.3249

### Environment

OS: Windows 10
Shell: Git bash
$TERM: xterm

**Comment by k-takata** [comment]
So, did you set the 'shell' option to bash? What does `:set shell?` show?

**Comment by chrisbra** [comment]
Use `:set verbose=5` and show the output of the command that Vim runs.

**Comment by CrispyDrone** [comment]
> So, did you set the 'shell' option to bash? What does `:set shell?` show?

shell="C:\Program Files\Git\bin\bash.exe"

> Use `:set verbose=5` and show the output of the command that Vim runs.

![image](https://github.com/vim/vim/assets/37639058/5cecb1bc-2139-415d-976a-a6cad8c9d968)

**Comment by chrisbra** [comment]
please don't post images. 

Is 'start' actually a valid command for `git-bash`?

**Comment by CrispyDrone** [comment]
It's located at `C:\Program Files\Git\usr\bin\start` on my system. I can do `start 'https://www.google.com'` in `git-bash` without issues.

**Comment by CrispyDrone** [comment]
When `cmd` is set as the shell, using single quotes also doesn't work for me. Does work with double quotes or no quotes.

I also noticed that when I started gvim from bash with `gvim -u NONE -U NONE`, the shell was still set to `git-bash`. When I started gvim from `cmd` instead with the exact same arguments, it was set to `cmd`. This seems like it's intended, but still confused me for a second.

**Comment by k-takata** [comment]
Oh, sorry. I forgot that `!start` was special in Windows. It is not passed to the shell. See `:!start`.
Not sure what is the best way to solve this, but you might be able to use `:! start` instead of `:!start`.

> I also noticed that when I started gvim from bash with `gvim -u NONE -U NONE`, the shell was still set to `git-bash`. When I started gvim from `cmd` instead with the exact same arguments, it was set to `cmd`.

This is because (g)vim sets the 'shell' option based on the $SHELL environment variable.

**Comment by CrispyDrone** [comment]
> Oh, sorry. I forgot that `!start` was special in Windows. It is not passed to the shell. See `:!start`. Not sure what is the best way to solve this, but you might be able to use `:! start` instead of `:!start`.

This "works", but a cmd window is spawned that you _have_ to close to be able to interact with vim.

**Comment by chrisbra** [comment]
try using `:set guioptions+=!`

**Comment by chrisbra** [comment]
I added a reference to 'go-!' inside `:h !start`. I suppose this is fine then and this can be closed.
