### ISSUE TITLE
Question - Does syn match respect \zs \ze ?

### ISSUE THREAD

**Issue by marcotrosi** [vim/vim#13590]
Hello Reader,

I'm trying to create a custom syntax file.

The lines I'm matching are structured like this ...
`<filepath>:<linenumber>:<columnnumber>: <classification>: <message> [<affected entitiy>] (<violated rule>)`
example ...
`work/path/to/file.c:135:44: advisory: Pointer arithmetic not allowed [-] (Rule 18.4)`

**all good with that, no issues with the regex, they all work on their own and the correct parts get highlighted as expected.**

my strategy is to describe the whole line and use `\zs` and `\ze` to mark the start and end of the parts to be highlighted.
here the important lines ...
```
hi AXV_FILE    guifg=#458588
hi AXV_LINE    guifg=#B8BB26
hi AXV_COL     guifg=#FABD2F
hi AXV_CLASS   guifg=#D79921
hi AXV_MESSAGE guifg=#EBDBB2
hi AXV_ENTITY  guifg=#FB4934
hi AXV_RULE    guifg=#B16286
 
sy match AXV_FILE    /^\zs[^:]\+\ze:\d\+:\d\+: \w\+: .\+ \[.\+\] (.\+)$/
sy match AXV_LINE    /^[^:]\+:\zs\d\+\ze:\d\+: \w\+: .\+ \[.\+\] (.\+)$/
sy match AXV_COL     /^[^:]\+:\d\+:\zs\d\+\ze: \w\+: .\+ \[.\+\] (.\+)$/
sy match AXV_CLASS   /^[^:]\+:\d\+:\d\+: \zs\w\+\ze: .\+ \[.\+\] (.\+)$/
sy match AXV_MESSAGE /^[^:]\+:\d\+:\d\+: \w\+: \zs.\+\ze \[.\+\] (.\+)$/
sy match AXV_ENTITY  /^[^:]\+:\d\+:\d\+: \w\+: .\+ \[\zs.\+\ze\] (.\+)$/
sy match AXV_RULE    /^[^:]\+:\d\+:\d\+: \w\+: .\+ \[.\+\] (\zs.\+\ze)$/
```

But when I execute all `sy` lines, then only the first one works in the sense that only the filename/path gets highlighted.

So I did some investigations and I read `:h :syn-priority` and I have the feeling that's the part of the documenation that explains why the `sy` regexs work on their own but not when all have been executed.

The manual does not state if `\zs` and `\ze` are considered or not. Or in other words - are these regex pattern starting at the same column or not? From the highlighting I can tell they are definitely considered, but I dont know if these columns are also used for the priority check.

In my opinion Vim should recognize that they are covering different parts of a matching line and should respect `\zs` and `\ze`, and therefore there is no overlapping of "regions".

- Do you know how this has been implemented at the moment?
- Am I missing something like an option that solves my problem?
    - I also tried playing with `contains`/`contained` but has the regions are not actually overlapping, no nesting, if `\zs` and `\ze` would be considered 
- Can Vim in the future consider `\zs` and `\ze` to mark the start and end of a matching pattern correctly?

Thanks for your support

marco

**Comment by zzzyxwvut** [comment]
Instead of examining whole lines with every `:syn-match`, try  
claiming the line once, and then looking for submatches in  
it for decoration, e.g.:

```vim
" <filepath>:<line_number>:<column_number>: <classification>: <message> [<affected entity>] (<violated rule>)
sy match AXV_SPAN transparent contains=CONTAINED
	\ /^.\{-1,}:\d\+:\d\+: \w\+: .\+ \[.\{-1,}\] (.\{-1,})$/
sy match AXV_FILE	contained /^\zs.\{-1,}\ze:/
sy match AXV_LINE	contained /:\zs\d\+\ze:\d\+:/
sy match AXV_COL	contained /:\zs\d\+\ze: \w\+:/
" Define a more general match pattern for <message> before...
sy match AXV_MESSAGE	contained /: \zs.\+\ze \[.\{-1,}\] (.\{-1,})$/
" ...a less general match pattern for <classification>.
sy match AXV_CLASS	contained /: \zs\w\+\ze: .\+ \[.\{-1,}\] (.\{-1,})$/
sy match AXV_ENTITY	contained /\[\zs.\{-1,}\ze\] (.\{-1,})$/
sy match AXV_RULE	contained /(\zs.\{-1,}\ze)$/

hi def link AXV_FILE	PreProc
hi def link AXV_LINE	Comment
hi def link AXV_COL	Identifier
hi def link AXV_CLASS	Type
hi def link AXV_MESSAGE	Constant
hi def link AXV_ENTITY	Todo
hi def link AXV_RULE	Error
```

**Comment by marcotrosi** [comment]
thank you @zzzyxwvut 
I was able to make it work

**Comment by chrisbra** [comment]
note, there is also `:h syn-nextgroup`
