### ISSUE TITLE
carbled code when use the other colorschema

### ISSUE THREAD

**Issue by auqf** [vim/vim#13602]
### Steps to reproduce

![image](https://github.com/vim/vim/assets/8895540/b72217c3-3584-4457-b65b-712c45b55770)

### Expected behaviour

how to fix the error?

### Version of Vim

IM - Vi IMproved 9.0 (2022 Jun 28, compiled Nov 28 2023 10:04:37)

### Environment

centos8.0

### Logs and stack traces

```shell
when I setup the colorschema in the .vimrc by colorschema monokai, and I open anyone file, the firstline is carbled code like the above pictures. But after I open the file, and I reset the colorschema by the vim command mode, it's ok.
```

**Comment by k-takata** [comment]
What terminal emulator do you use? What is the setting of `$TERM`?
Could you show detail Vim version (including patch number)?

**Comment by auqf** [comment]
![image](https://github.com/vim/vim/assets/8895540/083fe5d7-e1ea-409c-a187-686cbdc79f57)
![image](https://github.com/vim/vim/assets/8895540/02b74c42-d384-4751-b4c7-49d871d1ee5a)

I use  the latest version from the github.

**Comment by dpelle** [comment]
To @auqf : you forgot to answer this important question:

> What terminal emulator do you use?

**Comment by auqf** [comment]
I have tried the gnome terminal and windTerm, the result is the same.

**Comment by chrisbra** [comment]
well, you term is not really an xterm, is it? Looks like it comes from `:set t_TI?` or `:set t_RK?`

I think those might be for requesting modify-Other Keys status, see `:h modifyOtherKeys`

**Comment by chrisbra** [comment]
also what versions of those terminal emulators are you using?

**Comment by chrisbra** [comment]
so then it is solved and we can close it right?

**Comment by auqf** [comment]
Yes, if the vim version is 8.0, and it's not need to change the variable TERM, it's ok
