### ISSUE TITLE
Different behaviour at EOL for insert mode mappings with `<Cmd>` and `<C-o><Cmd>` / `<C-o>:`

### ISSUE THREAD

**Issue by bagohart** [vim/vim#13606]
### Steps to reproduce

1. Start vim via `vim -u NONE`
2. Add text: `atest<Esc>`
3. Create first mapping: `:inoremap <C-d> <C-o><Cmd>normal! <C-l><CR>` (then `<CR>` to confirm)
4. Create second mapping: `:inoremap <C-t> <Cmd>normal! <C-l><CR>` (then `<CR>` to confirm)
5. Create third mapping: `:inoremap <C-r> <C-o>:normal! <C-l><CR>` (then `<CR>` to confirm)
6. Go to end of text: `ggA`
7. Use both mappings `<C-t><C-d>` or `<C-t><C-r>` to have cursor jump between last position and second to last position in the line. There seems to be no difference between using `<C-o><Cmd>` and `<C-o>:`.

### Expected behaviour

According to `:help <Cmd>`, there should be no difference between using `inoremap <C-o>:` and `inoremap <Cmd>`.
The three commands should have identical behaviour, and the cursor should always stay in its place.

### Version of Vim

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Nov 22 2023 21:16:40) Included patches: 1-2121

### Environment

OS: current Manjaro
terminal: Kitty
$TERM: xterm-kitty
shell: fish, version 3.6.1

**Comment by chrisbra** [comment]
> :inoremap <C-t> <Cmd>normal! <C-l><CR>

That seems strange, you are going explicitly to normal mode and that seems to cause changing the cursor position.. Use `<cmd>:redraw!<cr>` to redraw and it doesn't change the cursor position.

**Comment by bagohart** [comment]
`:h <Cmd>` says `Where you might use ":...<CR>" in the {rhs} of a mapping, you can instead use "<Cmd>...<CR>"`.
To me that sounds like `<Cmd>` is supposed to be a drop-in replacement for the old way of doing `<C-o>:` If that's not the case, maybe the help should mention that?

**Comment by bagohart** [comment]
> > `:inoremap <C-t> <Cmd>normal! <C-l><CR>`
> 
> That seems strange, you are going explicitly to normal mode and that seems to cause changing the cursor position.. Use `<cmd>:redraw!<cr>` to redraw and it doesn't change the cursor position.

Yes, the mapping was not supposed to be reasonable on its own. I originally stumbled on this as part of a larger mapping, and then tried to construct a minimal working example.
If the difference in behaviour at the end of line (and one character before that) does not bother anyone, feel free to close this issue.

**Comment by chrisbra** [comment]
I checked it. It's the `:norm!` that causes the cursor to move, because we are now in Normal mode and the cursor is not allowed to be after the end of the line in Normal mode. So this is not a bug. You can use `:set virtualedit+=onemore` to fix this if this annoys you.
