### ISSUE TITLE
Case-insensitive omni completion does not behave like keyword completion

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#1361]
With `set ignorecase`, completion is supposed to be case-insensitive. Keyword completion and omni completion behave differently, though. To see why, open a buffer and set the filetype to, say, JavaScript (the specific filetype is not important as long as it provides omni completion), then type:

```
fu<c-x><c-o>
```

Vim suggests `Function` and `function`. If you now type `n`, the menu choices get restricted to `function` only (all lowercase). Compare with keyword completion:

```
function
Function
fu<c-x><c-n>n
```

Even after typing `n`, both choices are still there. I think that this is the correct behaviour. Is there any reason why omni completion should not behave in the same way?

**Edit:** you'd better set `completeopt=menuone,noselect` for the test above.

**Comment by lifepillar** [comment]
I see that JavaScript's completion function (or any other omni function I have tried) does not use `'refresh': 'always'`.  Could that be the reason for the different behaviour?

**Comment by lifepillar** [comment]
Sorry, I have just realized that, to reproduce my issue with the example above, you must also set `noinfercase`, otherwise keyword completion proposes only one match instead of two.  But the problem, I'd like to stress, is not `infercase`. The problem is that the matches proposed by omni-completion are filtered out if the user keeps typing and the case does not match, even if `ignorecase` is set. Source this:

```vim
set ignorecase
set omnifunc=MyComplete

fun! MyComplete(findstart, base)
  if a:findstart
    return match(getline('.'), '\S\+\%'.col('.').'c')
  else
    return filter(split("January Jane Janus Jank Janitor"), { i,v -> v =~ '^'.a:base })
endfun
```

then type `j<c-x><c-o>a` (in Insert mode) to see what I mean.

**Comment by markonm** [comment]
Case-insensitive omni completion depends on `icase` property which must be set for every element of matching list. For example:

```vim
set ignorecase
set omnifunc=MyComplete

fun! MyComplete(findstart, base)
  if a:findstart
    return match(getline('.'), '\S\+\%'.col('.').'c')
  else
    return  map(filter(split("January Jane Janus Jank Janitor"),
          \ { i,v -> v =~ '^'.a:base }), "{'word': v:val, 'icase': 1}")
endfun

```

**Comment by chrisbra** [comment]
closing then.
