### ISSUE TITLE
command modifiers should accept a range

### ISSUE THREAD

**Issue by nhooyr** [vim/vim#1362]
Commands now accept modifiers. However, if there is a command that accepts a modifier but also a range, because command modifiers do not accept ranges, you cannot use a range on that command.

See neovim/neovim#4449

**Comment by ZyX-I** [comment]
It should not, there is `v:count` and `:execute`. I would actually expect `N vertical split` to vertically split N’th window in place of the current one, not pass count somewhere.

**Comment by nhooyr** [comment]
@ZyX-I but `:split` accepts a count for the window size. however, `:vertical split` does not, which is the problem. if you think split should take a count to split the N'th window, then you just have to redefine how `:split` uses the count, `:vertical` should still pass it to `:split`.

**Comment by ZyX-I** [comment]
@nhooyr `:vertical 2split` works. `:2vertical 2split` should split the second window, making it have width 2.

**Comment by ZyX-I** [comment]
@nhooyr And it is not a problem, just instead of relying on `{count}:` results construct command using `:execute` and `v:count`.

**Comment by brammool** [comment]
The range goes on the command, thus after the modifier.

**Comment by nhooyr** [comment]
@brammool @ZyX-I but what about a mapping, neither `v:count` nor `:execute` help there. How about a way to tell vim which command takes the count?

**Comment by ZyX-I** [comment]
@nhooyr Did you actually try?

    nnoremap K :<C-u>execute 'vertical' (v:count ? v:count : '') 'Man'<CR>

**Comment by nhooyr** [comment]
Ah, ok, thanks!

**Comment by dumblob** [comment]
@ZyX-I @nhooyr thank you, the `nnoremap` with `v:count` checking is a perfect solution.

**Comment by nhooyr** [comment]
@dumblob i just realized that all you had to actually do was 

```vim
nnoremap <silent> K :<C-U>vertical Man<CR>
autocmd! FileType man nnoremap <silent> <buffer> K :<C-U>vertical Man<CR>
```

**Comment by ZyX-I** [comment]
@nhooyr `:Man` checks `v:count` itself? Guess something required to process `v:count` when using `&keywordprg`.
