### ISSUE TITLE
What's the minimum version of GCC required to build the latest Vim? Are there any patches to allow one to build it with even older versions of GCC?

### ISSUE THREAD

**Issue by fusion809** [vim/vim#1363]
Hi,

I maintain Vim packages in my Open Build Service home project, for example here are the packaging files I use to build it for CentOS/Fedora/Scientific Linux https://build.opensuse.org/package/show/home:fusion809/vim-redhat. I would like to build Vim for CentOS 5 and 6, but I cannot presently do this, because the build fails and I think the reason why is that GCC is too old. So I am here to ask what's the minimum version of GCC required to build the latest Vim (so 8.0) and are there any ways to build Vim with an older GCC? 

Thanks for your time,
Brenton

**Comment by vim-ml** [comment]
2017-01-08 16:50 GMT+03:00 Brenton Horne <vim-dev-github@256bit.org>:
> Hi,
>
> I maintain Vim packages in my Open Build Service home project, for example
> here are the packaging files I use to build it for CentOS/Fedora/Scientific
> Linux https://build.opensuse.org/package/show/home:fusion809/vim-redhat. I
> would like to build Vim for CentOS 5 and 6, but I cannot presently do this,
> because the build fails and I think the reason why is that GCC is too old.
> So I am here to ask what's the minimum version of GCC required to build the
> latest Vim (so 8.0) and are there any ways to build Vim with an older GCC?

Can you show the failing log? It may be some bug in Vim.

BTW, maybe there are some other C compilers available?

**Comment by fusion809** [comment]
I was surprised to learn that the log has been saved [here](https://build.opensuse.org/package/live_build_log/home:fusion809/vim/CentOS_6/x86_64) it is.

**Comment by fusion809** [comment]
A more detailed log can be found [here](https://build.opensuse.org/build/home:fusion809/CentOS_6/x86_64/vim/_log).

**Comment by brammool** [comment]
Please don't use an issue to ask a question.

**Comment by fusion809** [comment]
Where should I ask them? If I knew of where I should ask them I would ask them there. Googling Vim forums doesn't return any real usable results, there's one Google group for Vim users but I think this might be better suited for developers.

**Comment by fusion809** [comment]
Nvm I found the mailing lists.
