### ISSUE TITLE
NetRW: File rename raises an error with `g:netrw_fastbrowse=2`

### ISSUE THREAD

**Issue by KSR-Yasuda** [vim/vim#13640]
### Steps to reproduce

Do below:

```vim
:let g:netrw_fastbrowse=2
:vsplit SOME_DIRECTORY/

" NetRW hotkey for file rename
R
```

Then it raises an error below:

```diff
Error detected while processing function <SNR>128_NetrwLocalRename:
line   63:
E121: Undefined variable: w:netrw_bannercnt
```

If `g:netrw_fastbrowse` is not `2`, it doesn't happen.

Probably it comes the line https://github.com/vim/vim/blob/6863084d3bd044700973e6180ccb1a044566ec46/runtime/autoload/netrw.vim#L11337 in `s:NetrwLocalRename()`
without `w:netrw_bannercnt` being set, in case of `g:netrw_fastbrowse = 2`.

### Expected behaviour

It works successfully.

### Version of Vim

9.0.2121

### Environment

* Operationg system: Microsoft Windows [Version 10.0.19045.3693] (Windows 10 Pro 22H2)
    * MSYS2 env
* Terminal: mintty 3.7.0 (x86_64-pc-msys)
* Value of `$TERM`: `xterm-256color`
* Shell: bash

**Comment by chrisbra** [comment]
can you please send a PR ?

**Comment by KSR-Yasuda** [comment]
It's ad hoc, though.

**Comment by KSR-Yasuda** [comment]
Thank you for merging!
