### ISSUE TITLE
why some vim src recogized as cpp?

### ISSUE THREAD

**Issue by Shane-XB-Qian** [vim/vim#13641]
### Steps to reproduce

i am curious to ask why e.g 'src/vim.h' (its ft) is 'cpp'?
as i knew vim is running on C90 or something, not C++, right?
// not sure since when it was recognized like that. :smile:
// what's the benefit to recoginze '.h' as 'cpp' vs not 'c'?

### Expected behaviour

should be 'c'

### Version of Vim

v9.0.2153

### Environment

linux

**Comment by Shane-XB-Qian** [comment]
i knew there is 'g:c_syntax_for_h' in ft.vim, but why it was Not default as to 'C'?
since .hh and .H and .cpp etc was generally to 'cpp', vs '.h' and '.c' seems should be default to 'C' was more make sense.

**Comment by tonymec** [comment]
Why not default to C ? Well, IIUC C syntax is a subset of CPP syntax, so there is less risk in evaluating C as being CPP than there is in evaluating CPP as being C.

Anyway, .h headers are used for both C and CPP so they lie in a sort of "grey area" between both, and for 100% correct evaluation of their syntax, Vim needs help by the user. A `|modeline|` might sometimes be useful.

Best regards,
Tony.

**Comment by Shane-XB-Qian** [comment]
> IIUC C syntax is a subset of CPP syntax

yes, i agree, but '.h' default to 'C' seems more accurate.
// but anyway, seems it was like that long time ago, not sure if should change that.

---
however, even set `g:c_syntax_for_h`, e.g 'vim.h' still maybe recognized as 'cpp',
opened PR #13642 for that.

**Comment by Shane-XB-Qian** [comment]
> I still believe that when meeting some unknown .h file

i guess it was some old project c++ code, nowdays i supposed most people would name it as '.hh' etc.
'.h' to be 'C' ft which make it be accurate maybe important, e.g lsp, it's not only about syntax highlight.

anyway, user can set g:c_syntax_for_h to change, tho it is not the default,
// and currently ft.vim still may recognize '.h' (lowercase) as 'cpp' *after set it, opened PR https://github.com/vim/vim/pull/13642 for that

**Comment by laburnumT** [comment]
For syntax highlighting I can think of the `restrict` keyword which
should not highlight under c++, but should under c.

Other changes I can come up with off the top of my head apply more to
the lsp/linter.

**Comment by zeertzjq** [comment]
The C++ syntax file includes the C syntax file, so all C keywords are highlighted.

**Comment by laburnumT** [comment]
That might be a bug then. Because for me `restrict` highlights in c files, but not c++

**Comment by zeertzjq** [comment]
Oh, actually highlighting of `restrict` is disabled in C++:
```vim
if !exists("c_no_c99") && !s:in_cpp_family
  syn keyword	cStorageClass	inline restrict
endif
```

**Comment by Shane-XB-Qian** [comment]
> Interestingly enough it doesn't highlight in a .h file that is set to ft=c using a modeline either.

not sure if your  #13650 was the answer your/this question,
but here after set g:c_syntax_for_h, that `restrict` in '.h' will be highlighted.
// anyway, i maybe more interested the ft was correct, not only the syntax hl.

**Comment by laburnumT** [comment]
> but here after set g:c_syntax_for_h, that restrict in '.h' will be highlighted.

Yes that works too. But I'd like for it to work with `set ft=c` too.

**Comment by laburnumT** [comment]
> I expect that will work if you add unlet b:_in_cpp_family to the
> b:undo_ftplugin command string in the cpp ftplugin.

That appears to be commented out in that file:

```vim
" Disabled, because it gives an error for typing an unmatched ">".
" set matchpairs+=<:>
" let b:undo_ftplugin ..= ' | setl matchpairs<'
```

**Comment by chrisbra** [comment]
It's been like that forever, Is there any problem with the current setup?

**Comment by Shane-XB-Qian** [comment]
> It's been like that forever, Is there any problem with the current setup?

i think at least one of the reason is: 
not everyone was a fan of c++, many of them may want to get accurate c or cpp ft, and its syntax etc also.
// i am neither of them, but just found it's weird, so trying to correct it.

**Comment by Shane-XB-Qian** [comment]
to c/cpp (fname_case) 'fic' issue is fixed now via above PR.
// BTW: no offense to c++ :smiling_face_with_tear: but just was trying to get accurate c or cpp ft which it should be.
