### ISSUE TITLE
syntax=python: smartindent: line folding into tw inserts udesired whitespace

### ISSUE THREAD

**Issue by sdaoden** [vim/vim#13651]
### Steps to reproduce

22:11 -!- Irssi: Join to #vim was synced in 12 secs
22:12 < stenur> Hello!  I use vim for over twenty years, but unfortunately have forgotten almost anything on the configuration ;}
22:13 < stenur> I see a bug, but dunno what it belongs to.
22:14 < stenur> The thing is, if i have an overlong line that exceeds "tw", and i add another character, the line is split automatically into several that adhere to "tw".
22:15 < stenur> The new problem i see in 9.0.2130 (likely: compared to 9.0.2095, but i cannot swear),
22:16 < stenur> is that *if* that superlong line shows some whitespace in column 0 of a "visual followup line",
22:17 < stenur> then vim will add superficial whitespace ("masses of tabulators beyond any logic") for that line, after the auto-split.
22:17 < stenur> Can anyone make any sense out of that?
22:18 < stenur> Thank you.

### Expected behaviour

Simply break that single line to fit in tw, leaving the embedded whitespace intact.

### Version of Vim

9.0.2130

### Environment

CRUX Linux (rolling release, updated once a week).

**Comment by chrisbra** [comment]
What is this? Are you reporting an issue, that you think is not seriously enough that you cannot write a clean and reproducible bug description? Sorry, but then I won't even try to understand what this is all about. Please give precise clean and reproducible bug descriptions.

**Comment by sdaoden** [comment]
Hah.  Funnily i remembered.
I copied via firefox-bin as compiled by Mozilla itself a paragraph from
https://en.wikipedia.org/wiki/Deterministic_acyclic_finite_state_automaton.
The one which starts "A DAFSA",  but the one starting with "In computer science" also works.
So with my vim, if i ":read!cat" and paste the paragraph, then go at the end of the line and type a character, vim does it.

**Comment by sdaoden** [comment]
Hello dkearns!  Thank you!
Bad bug report, i apologise.
Yes, you are absolutely correct, i do have smartindent, and i can reproduce the problem with "vim --clean FILE.py" plus "set tw=78 smartindent" ('hope i have forgotten nothing) and adding another character.  A follow line gets folded-inserted to match an open parenthesis on a former line.
I have never seen such smartindent "mess" before?

Btw the line as such is as follows (as a single long line in a file).

A DAFSA is a special case of a finite state recognizer that takes the form of a directed acyclic graph with a single source vertex (a vertex with no incoming edges), in which each edge of the graph is labeled by a letter or symbol, and in which each vertex has at most one outgoing edge for each possible letter or symbol. The strings represented by the DAFSA are formed by the symbols on paths in the graph from the source vertex to any sink vertex (a vertex with no outgoing edges). In fact, a deterministic finite state automaton is acyclic if and only if it recognizes
a finite set of strings.[1]

**Comment by sdaoden** [comment]
(I have smartindent in "forever" (that could be the 22 or 23 years i use vim), on the global level.  And use vim daily for C, C++, perl, awk, sh, roff, email, earlier quite some other languages.)
