### ISSUE TITLE
Rust syntax file highlighting error in macro repeat definition

### ISSUE THREAD

**Issue by A4-Tacks** [vim/vim#13662]
### Steps to reproduce

example code:
```rust
macro_rules! foo {
    (a $(b)?) => { };
}
macro_rules! bar {
    ($(:)hello*) => {};
    ($(:)<-*) => {};
    ($(:)impl*) => {};
    ($(:)$*) => {};
    ($(:)-*) => {};
    ($(:)...*) => {};
    ($(:)*=*) => {};
    ($(:)#*) => {};
    ($(:)||*) => {};
}

foo!(a);
foo!(a b);

bar!(: hello : hello :);
bar!(: $ : $ :);
bar!(: *= : *= :);
bar!(: ... : ... :);
bar!(: # : # :);
bar!(: || : || :);
```

### Expected behaviour

diff of /usr/share/vim/vim90/syntax/rust.vim:
```diff
70c70
< syn region rustMacroRepeat matchgroup=rustMacroRepeatDelimiters start="$(" end="),\=[*+]" contains=TOP
---
> syn region rustMacroRepeat matchgroup=rustMacroRepeatDelimiters start="$(" end=")\(?\|\(&\|&&\|&=\|@\|\^\|\^=\|:\|,\|\$\|\.\|\.\.\|\.\.\.\|\.\.=\|=\|==\|=>\|>=\|>\|<[-=]\=\|-\|-=\|!=\|!\||\||=\|||\|::\|%\|%=\|+=\|#\|->\|;\|<<\|<<=\|>>\|>>=\|/\|/=\|\*=\|\~\|_\|\(r#\)\=\w\+\)\=[*+]\)" contains=TOP
```

`?`, optional group
`+` or `*`, use any token separate, token list from `syn` crate

char str and other tokens are not commonly used and have more complex rules, so ignore them

### Version of Vim

9.0.2143

### Environment

OS: ArchLinux
terminal: xfce4-terminal
Value of $TERM: xterm-256color
shell: bash 5.2.21

### Logs and stack traces

```shell
pass
```

**Comment by chrisbra** [comment]
Please contact the maintainer of the file as mentioned here: 

https://github.com/vim/vim/blob/ca7c9b1b59263938eea8dd5a197ca8312ffa91ac/runtime/syntax/rust.vim#L7
