### ISSUE TITLE
Cannot use imported interface

### ISSUE THREAD

**Issue by igbanam** [vim/vim#13661]
### Steps to reproduce

https://github.com/vim/vim/assets/390059/4322e21e-9458-4987-b6e6-cb64d5438869

I may be doing something wrong here, but it seems when an interface is imported from another file, it cannot be implemented. 

### Expected behaviour

Should be able to use the imported after the interface has been exported properly from some library file.

### Version of Vim

9.0

### Environment

Mac OS, iTerm, xterm-256color-italic, ZSH

**Comment by chrisbra** [comment]
please post those files to be able to better reproduce this issue.

**Comment by monkoose** [comment]
> You currently have to use :type to alias the qualified interface to an unqualified name. Support for implementing and extending with qualified names hasn't been implemented yet.
> 
> `type HasSurface iLib.HasSurface`

You have missed `=` in type aliasing.
I was using variable declaration for this `const HasSurface = iLib.HasSurface` previously and it works too.
