### ISSUE TITLE
syntax/dosbatch.vim should not flag colon comments as errors by default

### ISSUE THREAD

**Issue by mike-clark-8192** [vim/vim#13666]
Repro

1) Do a clean install of latest nightly build of vim (tested with 9.0.2103)
2) Use above vim to open `$VIMRUNTIME/vimtutor.bat` (on Windows), or open the file from the vim git repo (*nix).
3) Notice the `::` comments are flagged as errors (must have :syntax on, etc.)

Blame:
https://github.com/vim/vim/blame/a40e1687e757ea4aa41e84006c739f575db75703/runtime/syntax/dosbatch.vim#L95

My 2 cents:
`syntax/dosbatch.vim` default behavior should be to NOT show `::` comments as errors. This type of comment is [very common](https://github.com/search?q=%2F%5E%3A%3A%2F%20path%3A*.bat&type=code).

~~`syntax/dosbatch.vim` should consider using `g:` variables for its configurable behavior.~~
~~`exists("dosbatch_cmdextversion")` ==> `exists("g:dosbatch_cmdextversion")`~~
~~`exists("dosbatch_colons_comment")` ==> `exists("g:dosbatch_colons_comment")`~~

**Comment by chrisbra** [comment]
1) This was discussed in this PR: https://github.com/vim/vim/pull/11980 

2) using non-scoped variable names is fine, since they will be `g:`-scoped by default.

**Comment by mike-clark-8192** [comment]
Thanks. I am sorry that I wasn't able to find that issue. I did try to search.  :)

That issue is closed.  Should I try to discuss there, or here? I don't know the etiquette.

Even Microsoft themselves use colon comments in their most modern software:
VSCode's CLI launcher: https://github.com/microsoft/vscode/blob/main/scripts/code.bat

Vim itself uses colon comments in bat files.

They're just everywhere. I don't know any IDE or syntax-highlighting text editor that flags them as an error.  Yes, they can break scripts [when used inside a FOR loops](https://www.robvanderwoude.com/comments.php), but these problems are obvious if you test the batch file. 

I think that's about all I can say on this.

`:: text here` is not a syntax error in dosbatch, and I think it's an overreach to flag it as such. If you would like to colorize it in something that makes people raise their eyebrows, great, but I really don't fancy reading .bat files from bug-free shipping software with red squiggles everywhere. Yes, I know I can customize vim, but the out-of-the-box experience is important to discuss too, right?

**Comment by chrisbra** [comment]
let me ping the maintainer here: @mrdubya

**Comment by mrdubya** [comment]
Sorry for the late follow up, a combination of holidays and succumbing to the bad cold that is doing the rounds.

I have researched more discussion on the history and behaviour of `::` for comments and got a reasonable collection of examples to work with. I'll see if I can improve the detection of when they are likely to cause problems and should be flagged as an error.

It may take me a little while.

**Comment by mevanlc** [comment]
@mrdubya I'm also looking into how to flag problematic `::` comments in `syntax/dosbatch.vim` as a learning exercise, and also, hopefully, to help out a little.

In the meantime, though, I'd ask that we set the default of `dosbatch_colons_comment` to "on" (set). This has been the default behavior of dosbatch.vim for ~20 years.  With the new default setting, dosbatch.vim is flagging non-errors as errors in working, shipping software, including vim itself ( https://github.com/vim/vim/blob/master/vimtutor.bat ). This does not seem good to me.

What are your thoughts?

**Comment by mrdubya** [comment]
Hi @mevanlc It seems the one issue with `::` comments is when they are used within code blocks as the last thing in that code block. Command code blocks were new with the Windows NT command processor so highlighting `::` comments as errors outside of a code block is overkill.

The problem then becomes improving the highlighting of command blocks which is more complicated. I have not worked on syntax files in anger for a long time so I am having to do some revision. I hope to have a first attempt here soon.

**Comment by mrdubya** [comment]
Can you try out this change and see if the various dosbatch comment styles are working as you expect.  Thanks.

**Comment by mevanlc** [comment]
@mrdubya Looks good to me. I tested on a few files and reviewed your code changes to dosbatch.vim. Thanks for going after this!
