### ISSUE TITLE
autocmd! TabEnter * :tabmove - cause cpu to occupy 100%

### ISSUE THREAD

**Issue by yu3s** [vim/vim#13676]
### Steps to reproduce

i want to dynamically adjust the order of tabs, test function have issue 
reproduce:
1、cat 1.vim
vim9script
autocmd! TabEnter * :tabmove -
2、touch 2.vim
3、vim --clean -c "so ./1.vim" 1.vim
4、:$tab drop 2.vim
executing step four twice resulted in 100% CPU usage and vim can't responds
if autocmd add ++once or use :$tabnew 2.vim replace :$tab drop 2.vim, incomplete functionality

### Expected behaviour

Vim responds normally

### Version of Vim

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Dec 13 2023 08:38:15) Included patches: 1-2160

### Environment

os: ubuntu18.04
terminal: alacritty
$TERM: xterm-256color
shell: bash4.4.20

**Comment by chrisbra** [comment]
What exactly to you mean by `incomplete functionality`? 

> if autocmd add ++once or use :$tabnew 2.vim replace :$tab drop 2.vim, incomplete functionality

?

**Comment by chrisbra** [comment]
As mentioned by [:h :drop](https://vimhelp.org/windows.txt.html#%3Adrop):

> Windows that are not in the argument list or are not full width will be closed if possible.

It seems what is happening is the following:
Vim is iterating over all tabpages (which triggers the `TabEnter` autocommand), to clean up buffers not in the argument list.
However, since the `TabEnter` autocommand triggers, this will confuse Vim and it will keep on iterating over the argument list. 

`Ctrl-C` breaks it however. Note also that `:tabmove -` will cause an error for the very first tab, since you cannot move it to before the first tab.

**Comment by chrisbra** [comment]
I guess we need to block TabEnter autocommands for `arg_all_close_unused_windows()`

**Comment by yu3s** [comment]
> What exactly to you mean by `incomplete functionality`?
> 
> > if autocmd add ++once or use :$tabnew 2.vim replace :$tab drop 2.vim, incomplete functionality
> 
> ?

if i add ++once,  when i try to switch tabpage , it can't adjust the order of tabpage all the time
if i use tabnew,  can't use the same tab for the same file
in addition,  step 4 use :$tab drop 1.vim, repeated execution works normally

**Comment by yu3s** [comment]
> As mentioned by [:h :drop](https://vimhelp.org/windows.txt.html#%3Adrop):
> 
> > Windows that are not in the argument list or are not full width will be closed if possible.
> 
> It seems what is happening is the following: Vim is iterating over all tabpages (which triggers the `TabEnter` autocommand), to clean up buffers not in the argument list. However, since the `TabEnter` autocommand triggers, this will confuse Vim and it will keep on iterating over the argument list.
> 
> `Ctrl-C` breaks it however. Note also that `:tabmove -` will cause an error for the very first tab, since you cannot move it to before the first tab.

i try to check the first tab, but the results are the same. to simplify the results, I removed the judgment limitations

```
export def TabSort(): void
	var nr: number = tabpagenr()

	if nr > 1 && !CheckBashTab(nr - 1)
		:tabmove -
	endif
enddef
```

**Comment by yu3s** [comment]
> I'll create a PR to fix this soon.

i merge and test, found that if i use `:tab drop `open four different file, then  use `:tab drop`  + second or third file name, it will move the tab page to the left, but the last file(fourth) file name can't move left, i don't know if it is a feature

**Comment by chrisbra** [comment]
not sure what you mean. please give exact reproduction steps and say exactly what you expect and what (instead) you see

**Comment by yu3s** [comment]
> not sure what you mean. please give exact reproduction steps and say exactly what you expect and what (instead) you see

https://github.com/vim/vim/assets/86161857/b1c9ce18-cbcc-4e4c-bf2f-dfa8387c2dcb
