### ISSUE TITLE
netrw v171 from Cygwin: Pressing "x" on folder name doesn't launch Windows Explorer

### ISSUE THREAD

**Issue by NotNormallyAGitUser** [vim/vim#13687]
### Steps to reproduce

1. Start `netrw` by issuing `:e /Some/Folder/Path` or placing the cursor on some text representing a folder path and pressing `gf`.
2. Go to line 3, which normally contains text representing the folder path, and press `x`.

### Expected behaviour

Since `g:netrw_browsex_viewer` is set to `cygstart`, it *should* open the folder in Windows Explorer.  Instead, it merely moves the cursor down to the first-listed item in `netrw` buffer.  I originally reported this on [Stack Exchange](https://vi.stackexchange.com/questions/43666).  Commentor *romainl* suggested reporting it here.

### Version of Vim

8.2.4372

### Environment

OS: Cygwin on Windows 10
Terminal: Gvim
Value of $TERM: `xterm-direct` from `:echo $TERM`
Shell: Bash

**Comment by k-takata** [comment]
`g:netrw_browsex_viewer` is used when opening a file.
If the cursor is on a directory, *it is opened by netrw and I think this is the expected behavior.

**Comment by chrisbra** [comment]
Please show what `x` is mapped to. Then try to manually execute those steps and see what it does

**Comment by NotNormallyAGitUser** [comment]
> `g:netrw_browsex_viewer` is used when opening a file. If the cursor is on a directory, it is opened by netrw and I think this is the expected behavior.

I agree that if the directory is in the list of folder items, that is the expected behaviour.  When the folder path is on line 3, it is the title of the buffer.  I recall that in past versions of `netrw,` pressing `x` there opened the folder in Windows Explorer.

**Comment by NotNormallyAGitUser** [comment]
> Please show what `x` is mapped to. Then try to manually execute those steps and see what it does

I captured the following using `:redir` and `:map`.

    n  x           *@:<C-U>call netrw#BrowseX(<SNR>37_NetrwBrowseChgDir(1,<SNR>37_NetrwGetWord(),0),0)"<CR>
    x  gx            <Plug>NetrwBrowseXVis
    x  <Plug>NetrwBrowseXVis * :<C-U>call netrw#BrowseXVis()<CR>

I have only used old vi's simple mapping in the past, so I need to do some reading to understand these mappings.

A key function seems to be `NetrwBrowseXVis`.  This doesn't appear in `pi_netrw.txt`, which is the file pulled up when `F1` (help) is pressed within `netrw`.

If I take the second column as the "hot key" for the mapping, then only the first mapping above applies, which contains `NetrwBrowseChgDir`.  The help file `pi_netrw.txt` doesn't contain this string either.  However, my educated guess is that changes the directory -- within `netrw` -- rather than launching Windows Explorer.  It makes sense that a function whose name includes `NetrwGetWord` is invoked to generate the argument for the function whose name includes `NetrwBrowseChgDir`.

I'm hardly savvy with how Vim or its plugins works under the hood, but it seems to me that *not* launching Windows Explorer is how `netrw` is coded, which differs from how it is documented, e.g., `:help netrw-x` yields: *"if `g:netrw_browsex_viewer` exists, then it will be used to attempt to view files"* and `:echo g:netrw_browsex_viewer` yields `cygstart`, which launches Windows Explorer for a folder path argument.

**Comment by chrisbra** [comment]
does that fix this issue? @NotNormallyAGitUser can you confirm please?

**Comment by Konfekt** [comment]
@NotNormallyAGitUser Maybe you could weigh in on https://github.com/vim/vim/pull/15721 ? While WSL / Git Bash / MSYS2 are covered, a special handling for `cygstart` has not been added, as I assumed that their implementation of `start` would serve the same purpose.

**Comment by NotNormallyAGitUser** [comment]
> I found that netrw v167 changed the behavior: [9135901#diff-39baf27d8f62071617bbef12f874cce31c0ebd02ec99e7b119474ca870c636a3R5223](https://github.com/vim/vim/commit/91359014b359cf816bf943fe2c7d492996263def#diff-39baf27d8f62071617bbef12f874cce31c0ebd02ec99e7b119474ca870c636a3R5223) `netrw#BrowseX()` returns immediately after executing `norm! gf` (or `exe "e ".a:fname`). I'm not sure if this is the intended change.
> 
> The following patch should restore the old behavior:
> 
> ```diff
> --- a/runtime/autoload/netrw.vim
> +++ b/runtime/autoload/netrw.vim
> @@ -5303,8 +5303,6 @@ fun! netrw#BrowseX(fname,remote)
>  "   call Decho("remote≡0 and a:fname<".a:fname."> ".(isdirectory(a:fname)? "is a directory" : "is not a directory"),'~'.expand("<slnum>"))
>  "   call Decho("..appears to be a local directory; using e ".a:fname." instead",'~'.expand("<slnum>"))
>     exe "e ".a:fname
> -"   call Dret("netrw#BrowseX")
> -   return
>    elseif a:remote == 1 && a:fname !~ '^https\=:' && a:fname =~ '/$'
>     " remote directory, not a webpage access, looks like an attempt to do a directory listing
>  "   call Decho("remote≡1 and a:fname<".a:fname.">",'~'.expand("<slnum>"))
> @@ -5312,8 +5310,6 @@ fun! netrw#BrowseX(fname,remote)
>  "   call Decho("..and fname ".((a:fname =~ '/$')?        'matches' : 'does not match').' /$','~'.expand("<slnum>"))
>  "   call Decho("..appears to be a remote directory listing request; using gf instead",'~'.expand("<slnum>"))
>     norm! gf
> -"   call Dret("netrw#BrowseX")
> -   return
>    endif
>  "  call Decho("not a local file nor a webpage request",'~'.expand("<slnum>"))
>  
> ```

**Comment by NotNormallyAGitUser** [comment]
> I found that netrw v167 changed the behavior: [9135901#diff-39baf27d8f62071617bbef12f874cce31c0ebd02ec99e7b119474ca870c636a3R5223](https://github.com/vim/vim/commit/91359014b359cf816bf943fe2c7d492996263def#diff-39baf27d8f62071617bbef12f874cce31c0ebd02ec99e7b119474ca870c636a3R5223) `netrw#BrowseX()` returns immediately after executing `norm! gf` (or `exe "e ".a:fname`). I'm not sure if this is the intended change.
> 
> The following patch should restore the old behavior:
> 
> ```diff
> --- a/runtime/autoload/netrw.vim
> +++ b/runtime/autoload/netrw.vim
> @@ -5303,8 +5303,6 @@ fun! netrw#BrowseX(fname,remote)
>  "   call Decho("remote≡0 and a:fname<".a:fname."> ".(isdirectory(a:fname)? "is a directory" : "is not a directory"),'~'.expand("<slnum>"))
>  "   call Decho("..appears to be a local directory; using e ".a:fname." instead",'~'.expand("<slnum>"))
>     exe "e ".a:fname
> -"   call Dret("netrw#BrowseX")
> -   return
>    elseif a:remote == 1 && a:fname !~ '^https\=:' && a:fname =~ '/$'
>     " remote directory, not a webpage access, looks like an attempt to do a directory listing
>  "   call Decho("remote≡1 and a:fname<".a:fname.">",'~'.expand("<slnum>"))
> @@ -5312,8 +5310,6 @@ fun! netrw#BrowseX(fname,remote)
>  "   call Decho("..and fname ".((a:fname =~ '/$')?        'matches' : 'does not match').' /$','~'.expand("<slnum>"))
>  "   call Decho("..appears to be a remote directory listing request; using gf instead",'~'.expand("<slnum>"))
>     norm! gf
> -"   call Dret("netrw#BrowseX")
> -   return
>    endif
>  "  call Decho("not a local file nor a webpage request",'~'.expand("<slnum>"))
>  
> ```

Sorry for the late reply.  I am not a coder, developer, or computer scientist.  I needed to find a free workday afternoon to learn about autoloading, patching, and then fight the corporate firewall issues in installing the patch utility.  The patch works as advertised.  Here what I did:

Navigate to /usr/share/vim/vim82/autoload
Dump you patch code into a file "netrw.patch"
Issue this command: patch netrw.vim netrw.patch

**Comment by NotNormallyAGitUser** [comment]
> @NotNormallyAGitUser Maybe you could weigh in on #15721 ? While WSL / Git Bash / MSYS2 are covered, a special handling for `cygstart` has not been added, as I assumed that their implementation of `start` would serve the same purpose.

I'm really out of my depth when delving into VimScript.  I confirmed that k-takata's solution works.  Does that shed some light on #15721?

In case it helps,  my understanding of "cygstart" is that it passes the argument(s) to the Cygwin's POSIX emulation layer.  So it's like shelling out to a command.  I don't use the Windows "Start" command, but I suspect that "cygstart" allows users to issue invoke Windows executables in the same way as "Start", except that it may do a few things so that the execution process isn't broken by the fact that the invocation is done from a Cygwin Bash shell instead of a CMD prompt.  I'm guessing that at least one of the things it does is to ensure that the differences in environmental variables don't break the execution process.

**Comment by Konfekt** [comment]
Dear @NotNormallyAGitUser You should give #15721 a try as [`2aa82f9` (#15721)](https://github.com/vim/vim/pull/15721/commits/2aa82f971dae590c8209f66efe4ce457892bc34d) brought a check for cygwin

**Comment by chrisbra** [comment]
I have just merged #15721 so you can try latest master.

**Comment by NotNormallyAGitUser** [comment]
I would like to give it a spin, but not being a developer, I'm am completely out of my depth on GitHub.  Is #15721 for "netrw"?  Is it possible to provide a link to the page containing the VimScript source file?

P.S. On a separate note, I often issue ":let netrw_maxfilenamelen=35" (or some other numerical width) based on the length of filenames in the folder.  I don't suppose that "netrw" can automatically determine the right width based on the filenames in a particular folder?

**Comment by chrisbra** [comment]
That would be: https://github.com/vim/vim/blob/master/runtime/plugin/netrwPlugin.vim and https://github.com/vim/vim/blob/master/runtime/autoload/netrw.vim

**Comment by NotNormallyAGitUser** [comment]
Sorry, those files didn't seem to work.  I downloaded the files to a laptop with Vim 9.0:

   C:\cygwin64\usr\share\vim\vim90\plugin\netrwPlugin.vim
   C:\cygwin64\usr\share\vim\vim90\syntax\netrw.vim

I ran a new GVim and issued ":e /path/to/a/folder".  The syntax colouring all disappeared.  I placed the cursor on the folder path (line 3 of the buffer) and pressed "x".  The cursor simply moved to the first file in the folder.  If "x" was working as expected, I would see a Windows Explorer window open up, showing the folder.

I then reverted back to the old two files, containing _k-takata's_ patch above.  In a newly launched GVim, the syntax colouring returned and pressing "x" *anywhere* on line 3 (containing the folder path) caused a Windows Explorer window to open, as expected.

**Comment by chrisbra** [comment]
You should not replace the `syntax` script. I suggest to download a complete Vim from here: https://github.com/vim/vim-win32-installer/releases and then checking again. Note those releases won't work on cygwin (at least I think so).

**Comment by NotNormallyAGitUser** [comment]
Execution of the installer is blocked by either the AV or lack of administrator privileges.  However, I did refetch "netrw.vim" and "netrwPlugin.vim".  This time, I installed them to the following locations, respesctively:

c:/cygwin64/usr/share/vim/vim90/autoload/netrw.vim
c:/cygwin64/usr/share/vim/vim90/plugin/netrwPlugin.vim

While the syntax colours did not go away this time, pressing "x" still did not launch a Windows Explorer window.  All it did was move the cursor to the first file in the file list.

**Comment by Konfekt** [comment]
> I found that netrw v167 changed the behavior: [9135901#diff-39baf27d8f62071617bbef12f874cce31c0ebd02ec99e7b119474ca870c636a3R5223](https://github.com/vim/vim/commit/91359014b359cf816bf943fe2c7d492996263def#diff-39baf27d8f62071617bbef12f874cce31c0ebd02ec99e7b119474ca870c636a3R5223) `netrw#BrowseX()` returns immediately after executing `norm! gf` (or `exe "e ".a:fname`). I'm not sure if this is the intended change.

Since the added code has a comment saying

```
if its really just a local directory, then do a "gf" instead
```

it seems intended, though I don't see a point since there are already many ways to do `gf` (say hitting `<cr>`) but now none to do `gx`.

The latest changes to `gx` therefore did not change anything in this regard @NotNormallyAGitUser and @k-takata 's patch is still needed

**Comment by chrisbra** [comment]
I just included @k-takata patch. Thanks all

**Comment by Konfekt** [comment]
This now opens the folder with the OS handler and also enters it in Netrw. Wouldn't it be more consistent to omit entering (as happen when hitting `x` on files instead of folders)?
