### ISSUE TITLE
Selecting item from history doesn't work

### ISSUE THREAD

**Issue by andrey-starodubtsev** [vim/vim#1370]
Selection item from search history window doesn't change search register, i.e. following testcase is broken:

```
function Test_History_Window()
  execute ':new'
  execute "normal ia\<CR>b\<CR>a\<CR>b\<CR>\<Esc>"
  execute "normal gg/a\<CR>"
  call assert_equal('a', getline('.'))
  execute "normal gg/b\<CR>"
  call assert_equal('b', getline('.'))
  normal gg
  call feedkeys("q/kk\<CR>")
  call assert_equal('a', getline('.')) " current line is b instead of a
  call assert_equal('a', @/) " search register contains b instead of a
endfunction
```

Same for command history window, selecting item does nothing at the moment.
Also, if one opens command history window via `q:`, enters some command, for example `r !echo abc` and presses `Enter`, command isn't executed.

All these seems got broken after

```
commit c695cec4698b41d7b9555efdd47dda9b1945d3ae
Author: Bram Moolenaar <Bram@vim.org>
Date:   Sun Jan 8 20:00:04 2017 +0100

    patch 8.0.0159: crash on startup when updating tabline
    
    Problem:    Using a NULL pointer when using feedkeys() to trigger drawing a
                tabline.
    Solution:   Skip drawing a tabline if TabPageIdxs is NULL. (Dominique Pelle)
                Also fix recursing into getcmdline() from the cmd window.
```

**Comment by brammool** [comment]
Andrey Starodubtsev wrote:

> Selection item from search history window doesn't change search
> register, i.e. following testcase is broken:
> 
> ```
> function Test_History_Window()
>   execute ':new'
>   execute "normal ia\<CR>b\<CR>a\<CR>b\<CR>\<Esc>"
>   execute "normal gg/a\<CR>"
>   call assert_equal('a', getline('.'))
>   execute "normal gg/b\<CR>"
>   call assert_equal('b', getline('.'))
>   normal gg
>   call feedkeys("q/kk\<CR>")
>   call assert_equal('a', getline('.')) " current line is b instead of a
>   call assert_equal('a', @/) " search register contains b instead of a
> endfunction
> ```

This test won't work because the feedkeys() does not the commands to be
executed.  Still, when doing the same commands manually it also doesn't
work, thus the bug is there.

> Same for command history window, selecting item does nothing at the
> moment.
> Also, if one opens command history window via `q:`, enters some command, for example `r !echo abc` and presses `Enter`, command isn't executed.
> 
> All these seems got broken after
> 
> ```
> commit c695cec4698b41d7b9555efdd47dda9b1945d3ae
> Author: Bram Moolenaar <Bram@vim.org>
> Date:   Sun Jan 8 20:00:04 2017 +0100
> 
>     patch 8.0.0159: crash on startup when updating tabline
>     
>     Problem:    Using a NULL pointer when using feedkeys() to trigger drawing a
>                 tabline.
>     Solution:   Skip drawing a tabline if TabPageIdxs is NULL. (Dominique Pelle)
>                 Also fix recursing into getcmdline() from the cmd window.

Right, this was the wrong solution.  I'll look into fixing this.

-- 
hundred-and-one symptoms of being an internet addict:
250. You've given up the search for the "perfect woman" and instead,
     sit in front of the PC until you're just too tired to care.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
