### ISSUE TITLE
can't pass "<CR>" or "\<CR>" as a function parameter in <scriptcmd> context

### ISSUE THREAD

**Issue by habamax** [vim/vim#13701]
### Steps to reproduce

1. `vim -Nu NONE`
2. Add following vim9script:

```
vim9script

def g:FuncWithString(str: string)
    echom str
enddef


g:FuncWithString("hello")


# all of them fail
# nnoremap <CR> <scriptcmd>g:FuncWithString("<CR>")<CR>
# nnoremap <CR> <scriptcmd>g:FuncWithString("\<CR>")<CR>
# nnoremap <CR> <scriptcmd>g:FuncWithString('\<CR>')<CR>
nnoremap <CR> <scriptcmd>g:FuncWithString('<CR>')<CR>
```
3. `:source`
4. press Enter

result is
- `E115: missing single quote`
- `E116: invalid arguments for function g:FuncWithString('

![image](https://github.com/vim/vim/assets/234774/1e2872eb-1590-49d7-b45b-cd549742f49e)

### Expected behaviour

Not sure if this is a known limitation or not, but logically, in scriptcmd context I would assume function parameters should not be mixed with the `<CR>` that closes scriptcmd.

### Version of Vim

9.0.2167

### Environment

Debian, terminal st, bash

**Comment by zeertzjq** [comment]
You change just change the opening `<` to `<lt>`.

**Comment by habamax** [comment]
> You change just change the opening < to <lt>.

Oh, didn't think about it. Was lurking `:h <cmd>` and `:h <scriptcmd>`, I guess adding a note there might be useful.
