### ISSUE TITLE
Broken mouse selection when cursor overlaps another window

### ISSUE THREAD

**Issue by noscript** [vim/vim#13705]
### Steps to reproduce

1. Run GVim: `gvim --clean +'set nowrap virtualedit=all columns=80 | h | only | vsplit | h vim'`
2. Go to the right window and start selecting with mouse from the middle of a line towards start of the line, so that the mouse goes a little over the left window.

### Expected behaviour

Cursor stops at the column 1.

https://github.com/vim/vim/assets/717109/90ecc6ba-967d-4cac-a9b1-16edd5de5cbb

**Actual behavior**

Cursor jumps to the last column and continues moving towards column 1. 

https://github.com/vim/vim/assets/717109/a7d6af74-c2f5-4ca2-a6e5-3da68f9f6b23

Introduced in e500ae8e29ad921378085f5d70ee5c0c537be1ba

### Version of Vim

9.0.2173

### Environment

Debian 12
Terminal: GUI

**Comment by chrisbra** [comment]
ping  @zeertzjq

**Comment by chrisbra** [comment]
fixed as of v9.0.2177
