### ISSUE TITLE
Did someone intend to skip patch number 2171 in src/version.c?

### ISSUE THREAD

**Issue by thegavaguy** [vim/vim#13714]
### Steps to reproduce

I just obtained the most recent build of vim from the the vim\vim-win32-installer repo which reports it as being at patch level 2173.  After installing I always run `vim --version` to be sure I obtained the intended files and that they were successfully installed.  This is what I see:

```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Dec 16 2023 23:07:45)
MS-Windows 64-bit console version
Included patches: 1-2170, 2172-2173
Compiled by appveyor@APPVEYOR-VM
. . .
```

I omitted the rest of the output.

### Expected behaviour

I expected to see

```
Included patches: 1-2173
```

### Version of Vim

9.0.2173  [but with patch 2171 missing] from https://github.com/vim/vim-win32-installer/releases

### Environment

Windows 11 Home
Command Prompt session (using ConHost) and cmd.exe as the shell.
(The output is not dependent on the session type or shell.)

### Logs and stack traces

```shell
git show v9.0.2171..v9.0.2172 has this:

diff --git a/src/version.c b/src/version.c
index de90fcec5..213a0e7c2 100644
--- a/src/version.c
+++ b/src/version.c
@@ -705,7 +705,7 @@ static char *(features[]) =
 static int included_patches[] =
 {   /* Add new patch number below this line */
 /**/
-    2171,
+    2172,
 /**/
     2170,
 /**/



I am guessing that deleting 2171 was an editing mistake as I do not see anything that reverses the patch.
```

**Comment by chrisbra** [comment]
oh, I broke it. I'll fix it soon
