### ISSUE TITLE
strange hang up when input `o<esc>O` sequentially

### ISSUE THREAD

**Issue by ZSaberLv0** [vim/vim#13721]
### Steps to reproduce

1. use a `.vimrc` with empty contents
2. launch vim, quickly input: `o` `<esc>` `O`

the issue:
* can not reproduce when `vim -u NONE` or `vim --clean`
* can not reproduce when no `.vimrc` exists
* `O` hangs looks like some `imap Oxx xxx` was made
    * `verbose map O` prints nothing
    * when `set notimeout` and `set nottimeout`, `O` hangs forever until input new char
    * when `O` hangs:
        * input `j` would result to `*`
        * input `k` would result to `+`
        * other input seems result to normal (for example, input `a` result to `a` as expected)

### Expected behaviour

input without lag

### Version of Vim

9.0.2150

### Environment

OS : MacOS 13.4.1
Terminal : builtin iTerm 2.13 (447)
$TERM : xterm-256color
Shell : builtin shell, GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin22)

**Comment by zeertzjq** [comment]
Is this also not reproducible with `vim --clean`?

**Comment by ZSaberLv0** [comment]
> Is this also not reproducible with `vim --clean`?

yes, not reproducible with `vim --clean`

**Comment by monkoose** [comment]
Then I have bad news for you.

**Comment by ZSaberLv0** [comment]
`verbose map` :

```
x  gx            <Plug>NetrwBrowseXVis
        Last set from /usr/local/Cellar/vim/9.0.2150/share/vim/vim90/plugin/netrwPlugin.vim line 88
n  gx            <Plug>NetrwBrowseX
        Last set from /usr/local/Cellar/vim/9.0.2150/share/vim/vim90/plugin/netrwPlugin.vim line 82
x  <Plug>NetrwBrowseXVis * :<C-U>call netrw#BrowseXVis()<CR>
        Last set from /usr/local/Cellar/vim/9.0.2150/share/vim/vim90/plugin/netrwPlugin.vim line 90
n  <Plug>NetrwBrowseX * :call netrw#BrowseX(netrw#GX(),netrw#CheckIfRemote(netrw#GX()))<CR>
        Last set from /usr/local/Cellar/vim/9.0.2150/share/vim/vim90/plugin/netrwPlugin.vim line 84
v  <BS>          "-d
v  <D-x>         "*d
v  <D-c>         "*y
v  <D-v>         "-d"*P
n  <D-v>         "*P
```

---

`verbose imap` :

```
!  <D-v>         <C-R>*
```

**Comment by chrisbra** [comment]
so are those mappings active when the issue occurs or when it not occurs?

**Comment by chrisbra** [comment]
Perhaps you want to tweak your 'timeout' and 'ttimeout' settings? Also, since it doesn't occur with `vim --clean` please debug your .vimrc which setting is causing your issue

**Comment by ZSaberLv0** [comment]
> so are those mappings active when the issue occurs or when it not occurs?

those are mappings when the issue occur

---

after some struggle, i have found that:
simply use a `.vimrc` with empty contents would cause the issue
remove the `.vimrc`, the issue won't occur

**Comment by chrisbra** [comment]
I guess it's this one then: 
https://github.com/vim/vim/blob/2afe381a35912519182e0fd6c302c97c4f90f120/runtime/defaults.vim#L44-L45

So you may want to configure those timeout settings in your .vimrc file then

**Comment by ZSaberLv0** [comment]
i don't think it's related to my config since:
* the issue occurs with an empty content `.vimrc`
* the issue occurs only after i upgrade vim via `brew upgrade`, the prior version does not occur (can't remember the old version)
* the issue does not occur with MacVim 9.0.1897
* the issue does not occur with neovim 0.9.4

it looks like comes from vim runtime's builtin scripts, since `vim --clean` won't occur, and vim/MacVim/neovim use different runtime scripts

**Comment by ZSaberLv0** [comment]
vim 9.0.2150 :

```
:scriptnames
  1: ~/.vimrc
  2: /usr/local/Cellar/vim/9.0.2150/share/vim/vim90/plugin/getscriptPlugin.vim
  3: /usr/local/Cellar/vim/9.0.2150/share/vim/vim90/plugin/gzip.vim
  4: /usr/local/Cellar/vim/9.0.2150/share/vim/vim90/plugin/logiPat.vim
  5: /usr/local/Cellar/vim/9.0.2150/share/vim/vim90/plugin/manpager.vim
  6: /usr/local/Cellar/vim/9.0.2150/share/vim/vim90/plugin/matchparen.vim
  7: /usr/local/Cellar/vim/9.0.2150/share/vim/vim90/plugin/netrwPlugin.vim
  8: /usr/local/Cellar/vim/9.0.2150/share/vim/vim90/plugin/rrhelper.vim
  9: /usr/local/Cellar/vim/9.0.2150/share/vim/vim90/plugin/spellfile.vim
 10: /usr/local/Cellar/vim/9.0.2150/share/vim/vim90/plugin/tarPlugin.vim
 11: /usr/local/Cellar/vim/9.0.2150/share/vim/vim90/plugin/tohtml.vim
 12: /usr/local/Cellar/vim/9.0.2150/share/vim/vim90/plugin/vimballPlugin.vim
 13: /usr/local/Cellar/vim/9.0.2150/share/vim/vim90/plugin/zipPlugin.vim
```

---

MacVim 9.0.1897 :

```
:scriptnames
 1: /Applications/MacVim.app/Contents/Resources/vim/vimrc
 2: ~/.vimrc
 3: /Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/getscriptPlugin.vim
 4: /Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/gzip.vim
 5: /Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/logiPat.vim
 6: /Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/manpager.vim
 7: /Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/matchparen.vim
 8: /Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/netrwPlugin.vim
 9: /Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/rrhelper.vim
10: /Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/spellfile.vim
11: /Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/tarPlugin.vim
12: /Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/tohtml.vim
13: /Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/vimballPlugin.vim
14: /Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/zipPlugin.vim
15: /Applications/MacVim.app/Contents/Resources/vim/runtime/menu.vim
16: /Applications/MacVim.app/Contents/Resources/vim/runtime/autoload/paste.vim
17: /Applications/MacVim.app/Contents/Resources/vim/gvimrc
18: /Applications/MacVim.app/Contents/Resources/vim/runtime/syntax/syntax.vim
19: /Applications/MacVim.app/Contents/Resources/vim/runtime/syntax/synload.vim
20: /Applications/MacVim.app/Contents/Resources/vim/runtime/syntax/syncolor.vim
21: /Applications/MacVim.app/Contents/Resources/vim/runtime/filetype.vim
22: /Applications/MacVim.app/Contents/Resources/vim/runtime/scripts.vim
23: /Applications/MacVim.app/Contents/Resources/vim/runtime/autoload/dist/script.vim
24: /Applications/MacVim.app/Contents/Resources/vim/runtime/colors/lists/default.vim
25: /Applications/MacVim.app/Contents/Resources/vim/runtime/colors/macvim.vim
```

**Comment by chrisbra** [comment]
Need more information. Please try to debug this yourself

**Comment by mgedmin** [comment]
It is worth mentioning that `<esc>O` is the beginning of the escape sequence that most terminals use to report arrow keys: e.g. `<esc>OA` is `<Up>`, `<esc>OB`  is `<Down>`.  I have little doubt that `<esc>Oj` is `<kMultiply>` (the numpad `*`).

If you `:set notimeout nottimeout`, you should be able to make `<esc>O` in insert mode hang forever waiting for the next keypress even with `vim --clean`.  (I could do it with Vim 9.0.2158.)

**Comment by ZSaberLv0** [comment]
after `rm -rf /usr/local/Cellar/vim/9.0.2150/share/vim/vim90` :
* `vim` with empty `.vimrc` : `:scriptnames` only prints `~/.vimrc`, but the issue still occur
* `vim --clean` : still can not reproduce the issue, `:scriptnames` prints nothing

no idea what to debug next

**Comment by ZSaberLv0** [comment]
> It is worth mentioning that `<esc>O` is the beginning of the escape sequence that most terminals use to report arrow keys: e.g. `<esc>OA` is `<Up>`, `<esc>OB` is `<Down>`. I have little doubt that `<esc>Oj` is `<kMultiply>` (the numpad `*`).
> 
> If you `:set notimeout nottimeout`, you should be able to make `<esc>O` in insert mode hang forever waiting for the next keypress even with `vim --clean`. (I could do it with Vim 9.0.2158.)

it did, `:set notimeout nottimeout` and `vim --clean` would also reproduce
however, MacVim and neovim still can not reproduce

**Comment by chrisbra** [comment]
I am not sure I follow.  `vim --clean` will setup `ttimeout` and `timeout` options, as shown [above](https://github.com/vim/vim/issues/13721#issuecomment-1862385614). If you use of course set those options afterwards, well, then what do you expect... ?

So just configure it in your startup files correctly. Not sure what you expect here now.

Also, Neovim and MacVim have similar options so configure it in their configuration files.

**Comment by ZSaberLv0** [comment]
`set ttimeout=50` did solve the issue, so close for now

PS:
it now makes sense that MacVim can not reproduce, since it is GUI app
however, neovim with same config of vim (mainly `set ttimeout=-1`), run in the same terminal, still can not reproduce
