### ISSUE TITLE
Segmentation fault with :defer and lambda

### ISSUE THREAD

**Issue by habamax** [vim/vim#13727]
### Steps to reproduce

1. `vim -Nu NONE`
2. `:set hidden`
3. paste following vim9script
```
vim9script
def Test()
    var DelBuf = (bufnr) => {
        exe $"bd {bufnr}"
    }
    if empty(bufname()) || !empty(&buftype)
        defer DelBuf(bufnr())
    endif
    :edit other file
enddef
command! Test Test()
```
4. `:source`
5. `:Test`

### Expected behaviour

No segmentation fault.

![image](https://github.com/vim/vim/assets/234774/7036d7e1-923d-478d-b66b-1f3b06223515)

### Version of Vim

9.0.2175

### Environment

Debian, st (simple terminal), bash

**Comment by habamax** [comment]
While preparing a minimal steps I couldn't come up with the original error I have:

![image](https://github.com/vim/vim/assets/234774/0ff25f2d-875a-4955-b0d3-9cef01b0ee57)

Hopefully the root cause is the same for both.

**Comment by chrisbra** [comment]
Hm, I don't see the crash with vim 9.0.2175
```
gdb -args ./vim -u NONE -N -c ':set hidden' -c 'so crash_vim9.vim'
```
and then calling ':Test'

Can you get a gdb backtrace and/or an ASAN stack trace please?

**Comment by habamax** [comment]
> Can you get a gdb backtrace and/or an ASAN stack trace please?

I can't reproduce it on WSL, will check other terminals on proper linux machine when home.

**Comment by habamax** [comment]
How ASAN is properly enabled?

I uncommented in `src/Makefile`

```
SANITIZER_CFLAGS = -g -O0 -fsanitize-recover=all \
		   -fsanitize=address -fsanitize=undefined \
		   -fno-omit-frame-pointer
```

and with that -- I don't have segmentation fault.

If I comment it back and rebuild -- segfault is there again.

**Comment by habamax** [comment]
And in `gdb` it also works. `gdb -args src/vim -Nu NONE` and then all those steps -- no segfault. Without gdb -- segfault.

Interesting.
