### ISSUE TITLE
GVIM not reporting correct byte offsets

### ISSUE THREAD

**Issue by 3052** [vim/vim#13731]
### Steps to reproduce

using this file (inside, not the zip):

<https://github.com/vim/vim/files/13720982/index_video_5_0_1.zip>

If I open the same file in GVIM and enter `/mdat`, `enter`, `g`, `ctrl+g` I get:

~~~
Byte 2785
~~~

### Expected behaviour

if I run this Go program:

~~~go
package main

import (
   "bytes"
   "os"
)

func main() {
   b, err := os.ReadFile("index_video_5_0_1.mp4")
   if err != nil {
      panic(err)
   }
   i := bytes.Index(b, []byte("mdat"))
   println(i)
}
~~~

I get 2578. why is Vim off by over 200 bytes?

### Version of Vim

https://github.com/vim/vim-win32-installer/releases/tag/v9.0.2175

### Environment

https://github.com/vim/vim-win32-installer/releases/tag/v9.0.2175

**Comment by zeertzjq** [comment]
You need to edit the file with `vim -b` or `:edit ++bin`, otherwise Vim will convert the file encoding and the line endings.

**Comment by 3052** [comment]
if I use your option I get 2579, which is OK since Vim starts with 1. thank you!

**Comment by vim-ml** [comment]
On 2023-12-19, 3052 wrote:
> Steps to reproduce
> 
> using this file (inside, not the zip):
> 
> https://github.com/vim/vim/files/13720982/index_video_5_0_1.zip
> 
> If I open the same file in GVIM and enter /mdat, enter, g, ctrl+g I get:
> 
> Byte 2785
> 
> Expected behaviour
> 
> if I run this Go program:
> 
> package main
> 
> import (
>    "bytes"
>    "os"
> )
> 
> func main() {
>    b, err := os.ReadFile("index_video_5_0_1.mp4")
>    if err != nil {
>       panic(err)
>    }
>    i := bytes.Index(b, []byte("mdat"))
>    println(i)
> }
> 
> I get 2578. why is Vim off by over 200 bytes?
> 
> Version of Vim
> 
> https://github.com/vim/vim-win32-installer/releases/tag/v9.0.2175
> 
> Environment
> 
> https://github.com/vim/vim-win32-installer/releases/tag/v9.0.2175

I can replicate it with vim 9.0.2130 on Ubuntu 20.04, but I can't
explain it.  Rather than use a custom program to count the bytes,
I just used hexdump.  The full output of g Ctrl-G in vim is this:

    Col 551-983 of 1063-1559; Line 8 of 4914; Word 713 of 35890; Char 2579 of 1282363; Byte 2785 of 1920490

Note that it reports "Char 2579", which should be byte 2579.

Regards,
Gary

**Comment by 3052** [comment]
I think I agree with the previous user. the byte offset is 2578 (or 2579 in VIM), so its should not be possible for VIM to be returning any higher number such as 2785. so I would consider that an error. the byte is the smallest "unit of measurement", so it should always be the highest quantity. reopening this.

**Comment by zeertzjq** [comment]
As I said in the previous comment, if 'binary' is not set, Vim converts the line endings of a file to be LF, CR or CRLF.

**Comment by 3052** [comment]
that does explain the increased count. can you please clarify?

**Comment by zeertzjq** [comment]
And, some bytes in the file correspond to a multibyte char in latin-1 encoding, so such a byte counts as two bytes.

**Comment by 3052** [comment]
OK that makes sense. just wanted a proper reason, sorry for the noise

**Comment by zeertzjq** [comment]
To be clearer, in Vim, 'encoding' is set to `utf-8` by default, while the file is recognized as a `latin1` file. `g_CTRL-G` returns the byte count in Vim's current 'encoding', and some bytes in the file correspond to a single-byte char in Latin-1, but a multi-byte char in UTF-8.

Therefore, this will also not happen if you run Vim with `--cmd 'set encoding=latin1'`.

**Comment by vim-ml** [comment]
On 2023-12-20, zeertzjq wrote:
> And, some bytes in the file correspond to a multibyte char in latin-1 encoding,
> so such a byte counts as two bytes.

I didn't understand that statement at first, but now I do.  Thanks.

When Vim's 'encoding' is utf-8 and it reads a file it sees as having
a 'fileencoding' of latin1, it expands the latin1-encoded characters
into utf-8-encoded characters in the buffer.  Latin1-encoding uses
1 byte per character while UTF-8 uses 1, 2, 3 or 4 bytes per
character.  So the number of bytes in Vim's buffer may exceed the
number of bytes in the file, as it does in the OP's case.

If that's a problem, you can fix it by forcing Vim to use latin1
internally:

    $ vim --cmd 'set enc=latin1 nofixeol' index_video_5_0_1.mp4

or set binary mode:

    $ vim -b --cmd 'set noeol' index_video_5_0_1.mp4

Regards,
Gary
