### ISSUE TITLE
`Command too recursive` when using minpac to install plugins

### ISSUE THREAD

**Issue by bennyyip** [vim/vim#13732]
### Steps to reproduce

1. Use https://github.com/k-takata/minpac to manage plugins.
2. Run `call minpac#update()`

### Expected behaviour

Plugins are successfully installed. Instead vim show errors `Command too recursive`.
This is because it use a lot of recursive callbacks and https://github.com/vim/vim/commit/2076463e383901cef44685aaf4b63e4306444f9e (9.0.2103) set `MAX_CALLBACK_DEPTH` from 100 to 20.
Maybe provide an option to set its value instead of a hard-coded value?

### Version of Vim

9.0.2103

### Environment

doesn't matter

### Logs and stack traces

```shell
Error detected while processing function <SNR>201_start_job[2]..<SNR>201_start_job[2]..<SNR>201_start_job[2]..<SNR>201_start_jo
]..<SNR>201_start_job[2]..<SNR>201_start_job[2]..<SNR>201_start_job[2]..<SNR>201_start_job[2]..<SNR>201_start_job[2]..<SNR>201_
rt_job[2]..<SNR>201_start_job[2]..<SNR>201_start_job[2]..<SNR>201_start_job[2]..<SNR>201_start_job[2]..<SNR>201_start_job[2]..<
>201_start_job[2]..<SNR>201_start_job[2]..<SNR>201_start_job[2]..<SNR>201_start_job[2]..<SNR>201_start_job[2]..<SNR>201_start_j

line    2:
E169: Command too recursive
Press ENTER or type command to continue
E169: Command too recursive
Press ENTER or type command to continue
E169: Command too recursive
Press ENTER or type command to continue
```

**Comment by jamessan** [comment]
> This is because it use a lot of recursive callbacks and [2076463](https://github.com/vim/vim/commit/2076463e383901cef44685aaf4b63e4306444f9e) (9.0.2103) set `MAX_CALLBACK_DEPTH` from 100 to 20.

That patch can be reverted since the problem was root caused to something else, however it's probably still worth looking at making minipac not so recursive, if feasible.

**Comment by bennyyip** [comment]
@k-takata 

> > This is because it use a lot of recursive callbacks and [2076463](https://github.com/vim/vim/commit/2076463e383901cef44685aaf4b63e4306444f9e) (9.0.2103) set `MAX_CALLBACK_DEPTH` from 100 to 20.
> 
> That patch can be reverted since the problem was root caused to something else, however it's probably still worth looking at making minipac not so recursive, if feasible.

**Comment by k-takata** [comment]
I'm now updating minpac not to use recursive calls. https://github.com/k-takata/minpac/pull/153

For Vim, it might be better to loosen the limit?

**Comment by chrisbra** [comment]
Yeah, since the problem patch 9.0.2103 wanted to fix was wrong, we may instead revert it (or instead increase reverse the callback function limit). What limit would be right for minpac then? 50? Or shall we go with 'maxfuncdepth'  again?
Would you like to create a PR for that?

**Comment by k-takata** [comment]
Current implementation of minpac calls `timer_start()` inside from the timer callback and the depth of the recursive call may depend on the number of the plugins to be updated. So, I cannot tell the maximum depth.
Back to 'maxfuncdepth' should be okay.
