### ISSUE TITLE
Feature Request: Real-Time Collaboration Functionality Similar to VS Code Live Share

### ISSUE THREAD

**Issue by KevinGIRAULT** [vim/vim#13744]
Quality peer programming is currently difficult if not impossible with Vim. 

A modern editor must have such a solution, with good integration. Allowing everyone to work on the same code with their own configuration is what Vim needs. Ideally, this would be something compatible with other IDEs (to be developed in collaboration with VSCodium, which doesn't have Live Share?) with a clear standard.

Under these conditions, using Tmux is not a really satisfactory solution. As far as I can tell from the Internet, Floobits once existed, but has long since been discontinued:
https://github.com/Floobits/floobits-vim
The same goes for duckly/ducky, whose integration was probably not ideal. 

Extensions are too easily abandoned, and should be integrated into Vim.

**Comment by TheMagicNacho** [comment]
I have thought this would be useful previously as well. 

To play devils advocate, this feature may be out of scope for vim. If it is out of scope terminal applications like Terminus offer terminal sharing which could offer a collaboration method.

If this were a feature in scope with vim, the feature would need to include encryption, user authentication, host authentication, collaboration endpoints, host access control, remote editing capabilities, remote file browsing capabilities.

**Comment by romainl** [comment]
Fun fact: the whole Neovim debacle started with the exact same request and appeal to "modernity". You should check out if they actually delivered on that front.

**Comment by chrisbra** [comment]
I personally think this is too much a nice use case (I would have only used it about a couple of times within the last 20 years) and there are enough work-arounds (using tmux/screen), that I don't think this belongs into Vim. And as mentioned, this would complicate the whole code base already quite a bit (including we are adding a whole new level of security considerations here, including being able to target Vim from a remote host). 

Honestly, I don't want Vim to become like this.
