### ISSUE TITLE
doc for libcall()

### ISSUE THREAD

**Issue by habamax** [vim/vim#13740]
Not a native english speaker but following sentence doesn't sound right to me:

```It is NOT a means to call...```

https://github.com/vim/vim/blob/5e133157785dd2fdcfaaecd4822f2793e28b466d/runtime/doc/builtin.txt#L5329-L5330

Should it be `It is NOT meant to call...`?

**Comment by zeertzjq** [comment]
"a means" means "a way"

**Comment by habamax** [comment]
Oh, ok.
