### ISSUE TITLE
Update default links for `diffAdded` and `diffRemoved`

### ISSUE THREAD

**Issue by echasnovski** [vim/vim#13759]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

Right now highlight groups for `diff` filetype (used in patches) `diffAdded` and `diffRemoved` highlight groups are by default linked to [`Identifier`](https://github.com/vim/vim/blob/6b9492e299c0b4ea76062160c4daf3985897f0b8/runtime/syntax/diff.vim#L383) and [`Special`](https://github.com/vim/vim/blob/6b9492e299c0b4ea76062160c4daf3985897f0b8/runtime/syntax/diff.vim#L381). With time these choices seem to outgrow themselves as `diffAdded` is usually associated with green color while `diffRemoved` - with red, while current choices are rarely associated with these colors.

Another point for the change is that some of bundled color schemes override current default links with something a bit more green and red:
- [`blue`](https://github.com/vim/vim/blob/6b9492e299c0b4ea76062160c4daf3985897f0b8/runtime/colors/blue.vim#L79-L80), [`darkblue`](https://github.com/vim/vim/blob/6b9492e299c0b4ea76062160c4daf3985897f0b8/runtime/colors/darkblue.vim#L57-L58), and [`evening`](https://github.com/vim/vim/blob/6b9492e299c0b4ea76062160c4daf3985897f0b8/runtime/colors/evening.vim#L31-L32) use `String` and `WarningMsg` as targets. While the first one has more chance of being "green" in any given color scheme, the second one is usually orange or yellow (`ErrorMsg` is usually red, though).
- [`habamax`](https://github.com/vim/vim/blob/6b9492e299c0b4ea76062160c4daf3985897f0b8/runtime/colors/habamax.vim#L109-L110), [`lunaperche`](https://github.com/vim/vim/blob/6b9492e299c0b4ea76062160c4daf3985897f0b8/runtime/colors/lunaperche.vim#L167-L168), and [`wildcharm`](https://github.com/vim/vim/blob/6b9492e299c0b4ea76062160c4daf3985897f0b8/runtime/colors/wildcharm.vim#L96-L97) directly override groups to be directly green and red-ish.

**Describe the solution you'd like**

Update default links:
- For `diffAdded` to link to a group with higher chance of being "green". Possible candidates: `String`, `DiffAdd`.
- For `diffRemoved` to link to a group with higher chance of being "red". Possible candidates: `ErrorMsg`, `DiffDelete`.

**Comment by chrisbra** [comment]
Yeah, I think it probably makes sense to link them to `DiffAdd` for `diffAdded` and `DiffDelete` for `diffDelete`. Can you please prepare a PR?

**Comment by echasnovski** [comment]
> Yeah, I think it probably makes sense to link them to `DiffAdd` for `diffAdded` and `DiffDelete` for `diffDelete`. Can you please prepare a PR?

Thanks for consideration.

Sure thing, I'll make a PR. Hopefully, tomorrow.

**Comment by tomtomjhj** [comment]
> Yeah, I think it probably makes sense to link them to DiffAdd for diffAdded and DiffDelete for diffDelete. Can you please prepare a PR?

I think linking `diffAdded` to `DiffAdd` would be a bit confusing when diff-ing diff files. Not sure if that case is worth considering, though.

**Comment by clason** [comment]
> I think linking diffAdded to DiffAdd would be a bit confusing when diff-ing diff files. Not sure if that case is worth considering, though.

It's just the default, you can still customize these groups to your heart's content.
