### ISSUE TITLE
Match ex-command does not work with visual or visual block selection

### ISSUE THREAD

**Issue by asmodeus812** [vim/vim#13758]
### Steps to reproduce

1. vim -u NONE
2. enter arbitrary multi line text sample in the buffer
3. visual select or visual block select some text
4. type `:'<,'>match Search /existing-valid-pattern/`
5. command produces invalid range error e16

### Expected behaviour

Visual match must also be supported. Note that normal range match works just fine, like that `1,2match Group /pattern/` - which respects the match range correctly

### Version of Vim

9.0

### Environment

Ubuntu / WSL

### Logs and stack traces

```shell
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jun 23 2023 15:15:13)
Included patches: 1-1650
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
-balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +gettext           +num64             +textobjects
-browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     +perl              +title
+channel           +ipv6              +persistent_undo   -toolbar
+cindent           +job               +popupwin          +user_commands
-clientserver      +jumplist          +postscript        +vartabs
-clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           -python            +viminfo
+cmdline_info      +libcall           +python3           +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
+cscope            +localmap          +ruby              +wildignore
+cursorbind        +lua               +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con        +mksession         +smartindent       +writebackup
+diff              +modify_fname      +sodium            -X11
+digraphs          +mouse             -sound             -xfontset
-dnd               -mouseshape        +spell             -xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        -mouse_gpm         +statusline        -xsmp
+eval              -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary
-farsi             -mouse_sysmouse    -tag_old_static
```

**Comment by chrisbra** [comment]
> :'<,'>match Search /existing-valid-pattern/

There is nothing in the help, that indicates that the match ex command accepts valid range. Besides, what exactly should the range specify? Match by itself does not work on the current line, but finds the next search pattern (anywhere in the buffer) and highlights so restricting it by a range doesn't really make sense.

**Comment by asmodeus812** [comment]
Yeah, seems like even with regular line numbers the range does apply over the entire buffer, i had misunderstood the match command then, having expected us to be able to restrict the matching scope. Are there any alternatives to doing that? What i am trying to do is implement a substitute like interactive highlight of a pattern within a range.

**Comment by asmodeus812** [comment]
Seems like i have misinterpreted what match is supposed to do. What i was trying to do was to incrementally match a pattern in the buffer bit to constrain it to a specific region, not the entire buffer. I'm looking for an alternative, but what i wanted to do is something like how the incremental highlight works in `:substitute`, for example.

**Comment by chrisbra** [comment]
You mean like the `incsearch` setting? You should be able to limit the matches using the [`\%l` regexp pattern](https://github.com/vim/vim/blob/master/runtime/doc/pattern.txt#L938-L957). So you could limit it to only the current viewport.

In general you probably want to use `matchadd()`- family of functions instead of using the `match` ex commands, since it is more flexible.

**Comment by asmodeus812** [comment]
Yeah like inc search, for my use case even realized that there was a use case where i would have to use matchaddpos, and pull the range / lines i want to highlight loop over them and use match and matchend, to pull the start/end of the match and then matchaddpos. But yes matchadd and match* family are indeed the way to go.
