### ISSUE TITLE
vim --version (for branch master, v9.0.2185) gives the text message 'VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 05 2023 17:58:57)'

### ISSUE THREAD

**Issue by federerfanatic** [vim/vim#13770]
### Steps to reproduce

0. git branch yields:
  * master
     v9.0.2185

1. ./configure \
  --prefix=$HOME/.local/stow/vim9 \
  --enable-luainterp=yes      \
  --enable-mzschemeinterp      \
  --enable-perlinterp=yes     \
  --enable-pythoninterp=yes   \
  --enable-python3interp=yes  \
  --enable-pythoninterp=yes  \
  --enable-tclinterp=yes      \
  --enable-rubyinterp=yes     \
  --enable-cscope      \
  --enable-multibyte    \
  --enable-fontset       \
  --enable-gui=auto       

2. make -j6
3. make install 
4. run install vim with --version option or enter ex mode and run :version
 

### Expected behaviour

I did a git clone of the current master branch and compiled. The configure script and version.h clearly have 9 mentioned in the code and yet the toplevel out of the message mentions 8.2. Perhap I misunderstanding something :-)

### Version of Vim

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 05 2023 17:58:57) Included patches: 1-579, 1969, 580-1848, 4975, 5016, 5023, 5072, 2068, 1849-1854, 1857, 1855-1857, 1331, 1858, 1858-1859, 1873, 1860-1969, 1992, 1970-1992, 2010, 1993-2068, 2106,  2069-2106, 2108, 2107-2109, 2109-3995, 4563, 46

### Environment

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
$BASH_VERSION 
5.1.16(1)-release: command not found

**Comment by zeertzjq** [comment]
I don't think you are running the Vim version you installed with `make install`. Maybe `make install` failed? Try `sudo make install`.

**Comment by federerfanatic** [comment]
I may not be checking out the correct branch?

I gather if one does:
$ git branch it spits out the current version of the master branch hence
the output is:

* master
  v9.0.2185

implies the current master branch is v9.0.2185?
I hope I am understanding git usage correctly?

Does vim load some kind of file which contains the versioning information
that it provides?. I do still have the
vendor supplied vim installed. Or is it indeed compiled into the code.
version.h seems to imply this.


--------------------------------------------------------------
 Roger Federer Fanatic Extraordinaire :-)

**Comment by zeertzjq** [comment]
`git branch` doesn't show the current version of the master branch. It shows the name of all branches, and here it show that the current branch is `master` branch, and you have another branch named `v9.0.2185`.

**Comment by k-takata** [comment]
What does `git log` show?

**Comment by chrisbra** [comment]
> $HOME/.local/stow/vim9

Is that actually in your path? Please show:
```
echo $PATH
type vim
which vim
```

Then from within Vim, please also show:
```
echo v:progpath
```
And finally, please show the full `:version` output

**Comment by federerfanatic** [comment]
Forget this. There is no problem. I removed the download and did a clone from scratch. It now gives correct version.

**Comment by errael** [comment]
> Forget this. ...

Closing this might be the best way.
