### ISSUE TITLE
Behavior of `]m` differs from documentation (`:h ]m`)

### ISSUE THREAD

**Issue by JJCUBER** [vim/vim#13777]
### Steps to reproduce

1. Have a code block of any form similar to this (struct can be class, namespace, etc; only the `{ ... }` is important):
```cpp
struct S
{
    void test() {
        // ...
    }
};
```
2. Use `]m` while on/past the opening `{` for `test()`.
3. Notice that the cursor moves to the closing `}` of the struct.

### Expected behaviour

According to the documentation (`:h [m`), this should be an error ("When no '{' is found after the cursor, this is an error"), which presumably means no movement would occur.

### Version of Vim

9.0.0000

### Environment

Windows 10
gvim (also occurs in vim)

### Logs and stack traces

```shell
N/A
```

**Comment by chrisbra** [comment]
Hm, the doc states this:

https://github.com/vim/vim/blob/cea3dac76e42c9a33dccbd2f10ef011f0be5c292/runtime/doc/motion.txt#L1317-L1318

> When **not before the end of a method**, jump to the start or end of the class.

And that seems to be what is happening.

However, that seems quite contradictory to

> When **no '}' is found after the cursor**, this is an error. 

So not sure if this is a bug.

**Comment by JJCUBER** [comment]
@chrisbra you are right; I may have poorly worded my issue report (I was trying to point out how the documentation says two different things for the proper "behavior" of `]m`).

**Comment by chrisbra** [comment]
So, a doc patch like this should be fine?
```patch
diff --git a/runtime/doc/motion.txt b/runtime/doc/motion.txt
index 403ef4f30..d8e4201ac 100644
--- a/runtime/doc/motion.txt
+++ b/runtime/doc/motion.txt
@@ -1,4 +1,4 @@
-*motion.txt*    For Vim version 9.0.  Last change: 2023 Sep 28
+*motion.txt*    For Vim version 9.0.  Last change: 2023 Dec 27


                  VIM REFERENCE MANUAL    by Bram Moolenaar
@@ -1308,16 +1308,14 @@ bring you back to the switch statement.

                                                *]m*
 ]m                     Go to [count] next start of a method (for Java or
-                       similar structured language).  When not before the
+                       similar structured language).  When after the
                        start of a method, jump to the start or end of the
-                       class.  When no '{' is found after the cursor, this is
-                       an error.  |exclusive| motion.
+                       class.  |exclusive| motion.
                                                *]M*
 ]M                     Go to [count] next end of a method (for Java or
-                       similar structured language).  When not before the end
+                       similar structured language).  When after the end
                        of a method, jump to the start or end of the class.
-                       When no '}' is found after the cursor, this is an
-                       error. |exclusive| motion.
+                       |exclusive| motion.
                                                *[m*
 [m                     Go to [count] previous start of a method (for Java or
                        similar structured language).  When not after the
```

**Comment by JJCUBER** [comment]
> So, a doc patch like this should be fine?

Yes, this looks good, though the new wording for
```diff
 ]m                     Go to [count] next start of a method (for Java or
-                       similar structured language).  When not before the
+                       similar structured language).  When after the
                        start of a method, jump to the start or end of the
```
might be confusing, since additional method starts between the cursor and the end of the class are prioritized.  Maybe the wording should be changed to mention how this jumps to the closest next occurrence of any of
- start of method
- end of class (actually, any scope/`{ ... }` from what I can tell, though nested classes/scopes are just jumped past)
- start of class

**Comment by chrisbra** [comment]
I changed that, because I found the double negation to be hard to grasp. If you have a better suggestions, please show.

**Comment by JJCUBER** [comment]
I was thinking maybe
```diff
                                                *]m*
 ]m                     Go to [count] next start of a method (for Java or
-                       similar structured language).  When not before the
-                       start of a method, jump to the start or end of the
-                       class.  When no '{' is found after the cursor, this is
-                       an error.  |exclusive| motion.
+                       similar structured language).  When there are no
+                       methods left before the next start or end of a class,
+                       jump to said start or end of the class.
+                       |exclusive| motion.
```
or
```diff
- ]m                    Go to [count] next start of a method (for Java or
-                       similar structured language).  When not before the
-                       start of a method, jump to the start or end of the
-                       class.  When no '{' is found after the cursor, this is
-                       an error.  |exclusive| motion.
+ ]m                    Go to [count] next start of a method, start of a class,
+                       or end of a class (for Java or similar structured
+                       language).  |exclusive| motion.
```
though I am not that good at wording things.  Your change might ultimately still be better than my proposed ones above.

**Comment by chrisbra** [comment]
please create a doc PR for it. I have now reverted that thing for now (except for mentioning the error).
