### ISSUE TITLE
v:null =~ '\l' return true

### ISSUE THREAD

**Issue by yu3s** [vim/vim#13781]
### Steps to reproduce

1. `vim --clean -c "echo v:null =~ '\l'"` return 1
2. `vim --clean -c "echo v:null =~ 'a'"` return 0
3. `vim --clean -c "echo v:null =~ 'z'"` return 0

### Expected behaviour

`vim --clean -c "echo v:null =~ '\l'"` return 0

### Version of Vim

9.0.2185

### Environment

os: ubuntu18.04
terminal: alacritty
$TERM: xterm-256color
shell: bash4.4.20

**Comment by zeertzjq** [comment]
`\l` matches any lowercase character, and `v:null` is converted to the string `"v:null"`, so it matches.

**Comment by yu3s** [comment]
> `\l` matches any lowercase character, and `v:null` is converted to the string `"v:null"`, so it matches.

thanks
