### ISSUE TITLE
After adding vim-airline

### ISSUE THREAD

**Issue by CoryAlbrecht** [vim/vim#13786]
### Steps to reproduce

1. do `git clone https://github.com/vim-airline/vim-airline ~/.vim/pack/dist/start/vim-airline` as per instructions at https://github.com/vim-airline/vim-airline
2. start gvim
3. get error dialog requiring you to press OK
4. exit gvim
5. remove vim-airline from ~/.vim/pack
6. still get error dialog

![image](https://github.com/vim/vim/assets/8172909/e88ce16f-5464-460c-a342-1cb0cfeba459)

### Expected behaviour

That gvim starts without error

### Version of Vim

8.2

### Environment

Operating system: Ubuntu 22.04

$TERM: xterm-256color in GNOME terminal 3.44.0 for GNOME 42

Shell: bash

### Logs and stack traces

[bugreport.txt](https://github.com/vim/vim/files/13783592/bugreport.txt)

**Comment by CoryAlbrecht** [comment]
bugreport.txt
[bugreport.txt](https://github.com/vim/vim/files/13783592/bugreport.txt)

**Comment by chrisbra** [comment]
please check for a stray `:set` command in your vimrc files. I don't think it has anything to do with airline.

**Comment by CoryAlbrecht** [comment]
That was it. Thanks.

**Comment by chrisbra** [comment]
please close the issue, if it is solved then.
