### ISSUE TITLE
netrw doesn't decode multibyte percent-encoding filename correctly

### ISSUE THREAD

**Issue by lilydjwg** [vim/vim#13787]
### Steps to reproduce

1. `touch 中文`
2. `vim file:///...../%e4%b8%ad%e6%96%87` (the `file://` url to the file just created)
3. Vim edits a file called "ä¸­æ<96><87>"

### Expected behaviour

Vim should edit the file named `中文`.

### Version of Vim

9.0.2173

### Environment

Arch Linux, UTF-8 locale.

**Comment by chrisbra** [comment]
Hm, netrw uses this function to decode the percent hex codes: 

https://github.com/vim/vim/blob/7e4f62a2575e8ce9ebb842d4246288138b11dff3/runtime/autoload/netrw.vim#L11587-L11593

But, this assumes, the characters are encoded using the codepoints, not the actual bytes. So we would need to decode those `%XX` as actual byte values and then read those bytes as Unicode byte stream. I don't know if this is currently possible using Vim Script (perhaps using `iconv()`? ) or we would need to use a separate external script.

**Comment by k-takata** [comment]
This is tricky but seems to work:
```vim
let fname = escape(iconv(substitute(fname,'%\(\x\x\)','\=nr2char("0x".submatch(1))','ge'),'utf-8','latin1')," \t")
```

**Comment by k-takata** [comment]
This uses iconv() to convert 'utf-8' to 'latin1', then the result becomes a decoded utf-8 string.

**Comment by k-takata** [comment]
Using `printf("%c")` should be better.

```vim
let fname = escape(substitute(a:fname,'%\(\x\x\)','\=printf("%c","0x".submatch(1))','ge')," \t")
```

**Comment by chrisbra** [comment]
indeed this looks even better
