### ISSUE TITLE
<C-]> issue using Portuguese-Brazil keyboard layout

### ISSUE THREAD

**Issue by ecsousa** [vim/vim#1378]
When I'm using a portuguese keyboard layout, and I press `<C-]>`, vim identifies it as `<C-\>`, which makes me unable to navigate help files using this kind of keyboards.

I was able to have a work around using this command on my vimrc:

```
silent! nnoremap <C-\> <C-]>
```

Note: I get this issue using Windows, with either console vim and gvim.

**Comment by vim-ml** [comment]
On Fri, Jan 13, 2017 at 6:31 PM, Eduardo Sousa
<vim-dev-github@256bit.org> wrote:
> When I'm using a portuguese keyboard layout, and I press <C-]>, vim
> identifies it as <C-\>, which makes me unable to navigate help files using
> this kind of keyboards

Finding a specific control key for a nonalphabetic character on a
keyboard for a language other than English is not always obvious.
Hitting Ctrl together with whatever it is that you hit to get ] will
not necessarily get you the 0x1D byte which means Ctrl-] for Vim. For
instance, on my Belgian keyboard, ] is AltGr-$ and Ctrl-] is not
Ctrl-$ but Ctrl-AltGr-$

But even if you don't know what to hit to get something that Vim will
interpret as Ctrl-], there is an easy workaround, as follows:

      map <F9> <C-]>
      map! <F9> <C-]>

By adding the above two lines to your vimrc then restarting Vim,
hitting F9 will give you what Ctrl-] is supposed to do, i.e., follow a
help link or find a tag in Normal mode, and teminate an abbreviation
in Insert or Command-line mode. (Of course if F9 is already taken you
can use any other key, preferably some F or Shift-F key.)


Best regards,
Tony.
