### ISSUE TITLE
Use ssh to connecting Linux, mapped shortcut keys in "mswin.vim" to operate the clipboard is not working.

### ISSUE THREAD

**Issue by znsoooo** [vim/vim#13809]
### Steps to reproduce

1. Use Moba software to connect to Linux development board by ssh.
2. Open vim and enter ":source $VIMRUNTIME/mswin.vim"
3. I can't use the Ctrl-C / Ctrl-X / Ctrl-V hotkeys for clipboard operation. But the Ctrl-Z and Ctrl-Y hotkeys is working.

### Expected behaviour

Use the Ctrl-C / Ctrl-X / Ctrl-V shortcut keys for clipboard operation while I'am using "mswin.vim" script.

### Version of Vim

9.1.0

### Environment

Ubuntu 18.04.6 LTS

**Comment by znsoooo** [comment]
And I an already fixed this bug: https://github.com/vim/vim/commit/1d9f46bfb718c0e67a77a06138df412ad462f820

**Comment by chrisbra** [comment]
You can create a pull request, but using the unnamed register is something very different then using the (system) wide clipboard.

**Comment by znsoooo** [comment]
> You can create a pull request, but using the unnamed register is something very different then using the (system) wide clipboard.

Yes, so it only takes effect when the system clipboard is not available.

**Comment by ciupicri** [comment]
The patch breaks gvim (vim-X11-9.1.158-1.fc39.x86_64) when running under X11 (XFCE) on Fedora Linux. The keyboard shortcuts don't work anymore.

**Comment by chrisbra** [comment]
what exactly does not work?

**Comment by ciupicri** [comment]
For example if I select some text in gvim and press <kbd>Control</kbd>+<kbd>C</kbd> , then <kbd>Control</kbd>+<kbd>V</kbd> in say Firefox the old content of the clipboard gets pasted. This means that the copy operation didn't put something new into the clipboard, i.e. it doesn't work.

On the other hand, select, right click →  **Copy** works fine.

---

```console
$ cat ~/.vim/vimrc
source $VIMRUNTIME/mswin.vim
```

**Comment by chrisbra** [comment]
Please give more information. 
So you are visual selecting anything and press `<c-c>`? What does `:vnoremap <c-c>` give you? What about `:echo has("clipboard_working")`?

If you change line 27 from:
```
if has("clipboard_working")
```
to 
```
if has("clipboard")
```

Does it start working?

**Comment by ciupicri** [comment]
> So you are visual selecting anything and press `<c-c>`?

Yes. Either with the mouse or the keyboard by pressing <kbd>Shift</kbd>.

> What does `:vnoremap <c-c>` give you?

```
v  <C-C>       * y
```

> What about `:echo has("clipboard_working")`?

```
1
```
 
> If you change line 27 […] does it start working?

Yes.

```diff
--- /usr/share/vim/vim91/mswin.vim	2024-03-08 02:00:00.000000000 +0200
+++ mswin.vim	2024-03-13 15:56:52.316998206 +0200
@@ -24,7 +24,7 @@
 " backspace in Visual mode deletes selection
 vnoremap <BS> d
 
-if has("clipboard_working")
+if has("clipboard")
     " CTRL-X and SHIFT-Del are Cut
     vnoremap <C-X> "+x
     vnoremap <S-Del> "+x
```

**Comment by ciupicri** [comment]
P.S. Pressing <kbd>Control</kbd>+<kbd>V</kbd> outputs `^` and then vim waits for another key press.

The **Paste** from the right click menu works fine.

**Comment by chrisbra** [comment]
> v  <C-C>       * y

Wait what? Where does that come from? Do you have this in your runtime file? Please show the output of `:verbose :vmap <c-c>` 

```
:echo has("clipboard_working")
1
```

Hm, perhaps clipboard is not yet working when sourcing `mswin.vim` ? Maybe this should be defered until the gui has started up? 


> P.S. Pressing Control+V outputs ^ and then vim waits for another key press.

That is expected. See `:h i_CTRL_V` (this also works similar in other modes).

**Comment by chrisbra** [comment]
I reverted back the check. Please next time create a new issue
