### ISSUE TITLE
Feature:  Have formatprg respect setlocal

### ISSUE THREAD

**Issue by fingermark** [vim/vim#1380]
If you search this repository or others for `setlocal formatprg`, you'll see that so many people assume `formatprg` respects this.  Unfortunately, `formatprg` is always global, which means that any plugin setting my `formatprg` for a certain language will cause unexpected results when I try to format my text in a different buffer with a different filetype (that has not set formatprg, such as a new buffer).

Please make formatprg local too.

There is formatexpr, but I can't figure out how to make it behave like formatprg without a lot of vimscript (and even then, it still doesn't work on gqap).

**Comment by guns** [comment]
cf. https://groups.google.com/forum/#!msg/vim_dev/cFK1UjstyAk/mreb2H4VCtoJ
