### ISSUE TITLE
Command line disappears if 'cmdheight' is changed when in Command-line mode

### ISSUE THREAD

**Issue by markonm** [vim/vim#13822]
### Steps to reproduce

Run `vim --clean -S reproduce.vim`

```
" reproduce.vim
set laststatus=2
function! Function_name() abort
  set columns=80
  call feedkeys(":"..repeat('x', 80), 'x')
  let &cmdheight=2
  let &cmdheight=1
  redraw
endfunction
call Function_name()
```

### Expected behaviour

Command line should not disappear. 

### Version of Vim

9.1

### Environment

Windows 10

**Comment by markonm** [comment]
The bug was Introduced with patch 9.0.0190. https://github.com/vim/vim/commit/f797e309caff48f7a56c73b16e62ff67c4dcbdd6

**Comment by chrisbra** [comment]
Interesting. That Commit was reverted as part of 9.0.0340 https://github.com/vim/vim/commit/a2a8973e51a0052bb52e43a2b22e7ecdecc32003

So shouldn't matter

**Comment by markonm** [comment]
It looks like it wasn't reverted completely.

This seems to fix the problem. I haven't run the tests though.

```diff
diff --git a/src/window.c b/src/window.c
index 54e17be2d..9eb8f17ce 100644
--- a/src/window.c
+++ b/src/window.c
@@ -6663,7 +6663,7 @@ win_drag_status_line(win_T *dragwin, int offset)
     row = win_comp_pos();
     screen_fill(row, cmdline_row, 0, (int)Columns, ' ', ' ', 0);
     cmdline_row = row;
-    p_ch = MAX(Rows - cmdline_row, 1);
+    p_ch = MAX(Rows - cmdline_row, 0);
     curtab->tp_ch_used = p_ch;

     win_fix_scroll(TRUE);
@@ -7129,11 +7129,6 @@ command_height(void)
     // p_ch was changed in another tab page.
     curtab->tp_ch_used = p_ch;

-    // If the space for the command line is already more than 'cmdheight' there
-    // is nothing to do (window size must have decreased).
-    if (p_ch > old_p_ch && cmdline_row <= Rows - p_ch)
-       return;
-
     // Update cmdline_row to what it should be: just below the last window.
     cmdline_row = topframe->fr_height + tabline_height();
```

**Comment by chrisbra** [comment]
Thanks.
```patch
+    p_ch = MAX(Rows - cmdline_row, 0);
```

That part is wrong. Command line height should not be possible to become 0.

```patch
-    // If the space for the command line is already more than 'cmdheight' there
-    // is nothing to do (window size must have decreased).
-    if (p_ch > old_p_ch && cmdline_row <= Rows - p_ch)
-       return;
```

That seems to be right however.

**Comment by markonm** [comment]
The bug persists if only the first part of the diff is applied.

**Comment by chrisbra** [comment]
That's what I am was trying to guess :)

**Comment by chrisbra** [comment]
Hm, this doesn't work properly. It fails the tests that were introduced with patch 9.0.0190. I think we need to make sure to always re-calculate `old_p_ch` always, since it can be unreliable after the early return.
