### ISSUE TITLE
Vim help files in HTML format are missing from the ftp server 

### ISSUE THREAD

**Issue by arpadffy** [vim/vim#13820]
### Steps to reproduce

1. go to http://ftp.vim.org/vim/doc/
2. search for the vim91html.zip file

### Expected behaviour

The html version of the Vim help exists in the ftp server.
In this case the http://ftp.vim.org/vim/doc/vim91html.zip is expected to exist.

### Version of Vim

9.1

### Environment

It is not environment dependent.

**Comment by chrisbra** [comment]
Quoting from the [release announcement](https://www.vim.org/vim-9.1-released.php)

>The Vim FTP Server has been retired. It is no longer used to distribute artifacts to users. If you used it in the past, please update to using the git repository instead

The HTML Zip file archive is available here: https://www.vim.org/downloads/vim91html.zip (reachable from https://www.vim.org/download.php)
