### ISSUE TITLE
'columns' is limited by physical screen width

### ISSUE THREAD

**Issue by terminatorul** [vim/vim#13834]
### Steps to reproduce

Setup up multiple monitors for test computer, at least 2 of them
Resize Vim window to exceed the width of a single monitor
Vsplit the current window in Vim (can be an empty window) with &lt;C-w&gt;v
Open a new tab with :tabnew
Switch between the two tabs with gt or &lt;C-PgDn&gt;

Notice the size of the Vim window shrinks to fit a sigle monitor whenever the multi-window tab is activated. This really breaks multi-monitor setups in Vim

Trying to manually :set columns, to a larger value then a single monitor can fit, will have no effect.

### Expected behaviour

Size of the entire vim window (on the system desktop) should not change even if Vim window spans multiple physical displays. Command to :set columns should allow values larger then a single monitor, if multiple monitors are present 

### Version of Vim

9.0

### Environment

Linux, GUI

 (I believe Windows has the same behavior, but at least on Windows I can sometimes use Eyefinity / Surround / Combine monitors) to make a single monitor out of 2 or 3 physical displays.

**Comment by chrisbra** [comment]
Please try `:set guioptions+=k`

**Comment by terminatorul** [comment]
That seems to fix it

**Comment by chrisbra** [comment]
closing then.
