### ISSUE TITLE
comments in .vimrc are parsed as user input

### ISSUE THREAD

**Issue by Passw** [vim/vim#13838]
### Steps to reproduce

- do key mapping
```.vimrc
nnoremap <Leader>b :buffers<CR>:buffer<Space>    " go to buffer N
```

- execute `<Leader>+b`

- `" go to buffer N` show up in command line buffer
![bug-vim](https://github.com/vim/vim/assets/5151456/6f331c50-89d9-4947-9ceb-b02d5d6fb953)

### Expected behaviour

comments `"go to buffer N` should not show up

### Version of Vim

build from repo

### Environment

OS: Windows

**Comment by zeertzjq** [comment]
This is documented at `:h map-trailing-white`
