### ISSUE TITLE
E40: Can't open errorfile C:/Users/Administrator/AppData/Local/Temp/VHP18E3.tmp on Windows 10 when use gVim 9.1 x64

### ISSUE THREAD

**Issue by VimIcewind** [vim/vim#13840]
### Steps to reproduce

I use a function to compile hi.c file on Windows 10
func! CompileC()
    exec "update"
    set makeprg=gcc\ -g\ -Wall\ -o\ %<\ %
    exec "make"
    set makeprg=make
endfunc

and I map gc to call fuction CompileC when I use vim to edit hi.c
gVim 9.1 x64 generate this error
E40: Can't open errorfile C:/Users/Administrator/AppData/Local/Temp/VHP18E3.tmp on Windows 10

### Expected behaviour

It work's on gVim 9.1 x86 when I do this

### Version of Vim

9.1.0

### Environment

Windows 10  gVim9.1 x64 C:\Windows\System32\bash.exe
### Logs and stack traces

```shell
:!gcc -g -Wall -o hi hi.c > C:/Users/Administrator/AppData/Local/Temp/VHP18E3.tmp 2>&1
E40: Can't open errorfile C:/Users/Administrator/AppData/Local/Temp/VHP18E3.tmp
```

**Comment by chrisbra** [comment]
you need to debug this. It smells like a permission problem.

**Comment by VimIcewind** [comment]
I found the reason. I set env SHELL to bash，but the “C:\Windows\System32\bash.exe” which bash provide by MS doesn't support "C:/". I set shell to cmd on Windows in my .vimrc or I use git bash instead  MS bash it solves.

**Comment by VimIcewind** [comment]
I found the reason. I set env SHELL to bash，but the “C:\Windows\System32\bash.exe” which bash provide by MS doesn't support "C:/". I set shell to cmd on Windows in my .vimrc or I use git bash instead MS bash it solves.

> you need to debug this. It smells like a permission problem.
