### ISSUE TITLE
YAML: Extra indentation when writing key: value lines

### ISSUE THREAD

**Issue by stove-panini** [vim/vim#13845]
### Steps to reproduce

1. Set the following vimrc:
```
filetype plugin indent on
autocmd! FileType yaml setlocal autoindent smartindent expandtab sw=2 ts=2 sts=2
```
2. Edit a yaml file and write a key: value, then press enter to move to the next line.
3. The cursor is indented an extra level. (`|` is cursor)
```
key: val
  |
```

### Expected behaviour

The cursor maintains the correct level of indentation.
```
key: val
|
```

PR https://github.com/vim/vim/pull/10328 describes this exact behavior, which was closed in favor of commit https://github.com/vim/vim/commit/f4f579b46b27f5e1689912a3e84c6a2a96efd143. This was back in 2022. However, I've experienced this behavior for a few years... I only just now decided to try and get to the bottom of it.

I want to note that the new line will automatically indent itself properly once you finish the new key name with `:`, but this will prevent autocomplete from working if using something like ansible-language-server or yaml-language-server with a schema.

### Version of Vim

9.1.016

### Environment

OS: Fedora 39
Terminal: GNOME Terminal 3.50.1
$TERM:  xterm-256color

This is a completely clean installation of F39. I also see the same behavior in Debian 12, openSUSE Tumbleweed, etc

**Comment by chrisbra** [comment]
that is surprising. If I see that correctly, this search pattern: `\v%(%\x\x)` (ignoring the rest of the line) would cause a syntax error.

**Comment by chrisbra** [comment]
Reverting the diff is definitly wrong. The diff from `v9.0.0379` fixes a syntax error. Try and search for it, you will get the following error:  `/\v%(%\x\x)` : `E678: Invalid character after %[dxouU]`. 
Guessing from the yaml.vim indent script, where it goes wrong it is this one here: 
https://github.com/vim/vim/blob/02d7a6c6cfceb3faf9c98fcb7c458760cd50d269/runtime/indent/yaml.vim#L145-L151

As mentioned in the comment below, this is trying to match the following item:
```
Mapping with: value
        that is multiline scalar
```

which is what is happening in your case (and seems to be correct).

I think this is intentionally, and once you type `:` the cursor position will jump back to the beginning of the line. So I think the current behaviour is right.

So it seems there is just a misunderstanding about whether or not the `yaml.vim` indent script should try to match a multiline scalar or whether it shouldn't. But given the work-around, that `:` dedents the line again, I would think the current behaviour is okay just perhaps a bit unexpected. 


Having said all that, I haven't heard from @ZyX-I in a long time. So if anybody wants to volunteer to maintain this, please stand up :) 

But be warned, that are some crazy Vim regexes here.

**Comment by liutaurasa** [comment]
I want to disable that smart multiline indentation. I want my cursor to be on the same level as previous line. It is driving me crazy.

**Comment by chrisbra** [comment]
remove those two lines from your copy then

**Comment by stove-panini** [comment]
Frightening regexes for sure! My two cents is that writing multiline scalars is less common than writing consecutive key-value pairs, so it seems odd to indent for them as the default behavior.

Either way, good to know what exactly is going on behind the scenes and which lines to modify.

**Comment by chrisbra** [comment]
Let me add a configure switch for people to opt-in into the multiline detection and include it.
