### ISSUE TITLE
ftplugin/man.vim does not work on AIX

### ISSUE THREAD

**Issue by XSven** [vim/vim#13847]
### Steps to reproduce

This

```
runtime ftplugin/man.vim
let g:ft_man_open_mode = 'vert'
let g:ft_man_folding_enable = 1
set keywordprg=:Man
```

is a part of my _.vimrc_ configuration. I have opened a C source code file. I have tried to open the man page of the **fgets** function typing **K**. I am getting

`man.vim: no manual entry for "fgets"`

### Expected behaviour

The man page of the **fgets** function should be displayed in a vertically splitted window.

### Version of Vim

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jul  7 2023 01:12:41) Included patches: 1-1649

### Environment

OS: AIX 7300-01-02-2320
TERM: putty-256color
SHELL: /usr/bin/ksh93

### Logs and stack traces

```shell
Although this is not really my expertise I have debugged the issue. From my perspective the problem is in the file autoload/dist/man.vim. The AIX man command does not understand the man option

let s:man_find_arg = "-w"

man: illegal option -- w
Usage: man [[[-ct] [section]] | [-f | -k]] [-F | -a] [-m] [-M path] [-r] name...
```

**Comment by chrisbra** [comment]
Please contact the maintainer of `autoload/dist/man.vim` and mention what argument AIX man command would need instead?

**Comment by XSven** [comment]
I would have done that but I do not know how?! It is not about the AIX **man** command it is about the default option that is passed to the fixed **man** command. I am using **man** on AIX without any option. Maybe **s:man_find_arg** should be replaced with a global configuration option to avoid additional operating system specific scripting.

**Comment by Konfekt** [comment]
Maybe @goweol knows more.

**Comment by XSven** [comment]
Maybe you (@Jason-Franklin) can have a look at this issue. Thanks.

**Comment by chrisbra** [comment]
so what is `$OSTYPE` on your AIX?

**Comment by XSven** [comment]
The variable `$OSTYPE` is **not an environment variable** and it **depends on the shell** in use.

If am using `ksh93` it is not set. If I am using `bash` its value is **aix7.3.0.0** but still it is not part of the environment:

`export | grep OSTYPE`

returns nothing.

`:echo $OSTYPE`

in `vim` returns nothing too.

**Comment by chrisbra** [comment]
yes, it is bash specific, don't know if other shells make this available. And to make this available within vim, you would have to export this variable. So we can at least make it work using:
```diff
diff --git a/runtime/autoload/dist/man.vim b/runtime/autoload/dist/man.vim
index 7f7d13711..b133c1243 100644
--- a/runtime/autoload/dist/man.vim
+++ b/runtime/autoload/dist/man.vim
@@ -16,6 +16,9 @@ try
   if !has("win32") && $OSTYPE !~ 'cygwin\|linux' && system('uname -s') =~ "SunOS" && system('uname -r') =~ "^5"
     let s:man_sect_arg = "-s"
     let s:man_find_arg = "-l"
+       elseif $OSTRYPE =~ 'aix'
+    let s:man_sect_arg = ""
+    let s:man_find_arg = ""
   endif
 catch /E145:/
   " Ignore the error in restricted mode
```

perhaps also show the output of `uname -s`

**Comment by XSven** [comment]
> So we can at least make it work using:
> ...

No we cannot. Please read my previous comment carefully again. `$OSTYPE` is bash specific variable. It is **not** part of the environment. Therefore **vim does not know it** and any plugin that is using it will not work properly.

> yes, it is bash specific, don't know if other shells make this available.

Other shells shouldn't make this available at least if they want to avoid **bashism** and try to be POSIX compliant to a certain extent.

**Comment by chrisbra** [comment]
> No we cannot. Please read my previous comment carefully again. $OSTYPE is bash specific variable. It is not part of the environment. Therefore vim does not know it and any plugin that is using it will not work properly.

I have read it. Please read my comment carefully again. Even if this is bash specific, we can make it work, **if you export the OSTYPE** variable in your bash shell.

> Other shells shouldn't make this available at least if they want to avoid bashism and try to be POSIX compliant to a certain extent.

It's not clear to me, `$OSTYPE` is a **bashism**. But again, I am trying to make work-arounds to make it work for **you**. Open for other suggestions.

**Comment by k-takata** [comment]
Just checking `uname -s` is enough? (untested)
```diff
--- a/runtime/autoload/dist/man.vim
+++ b/runtime/autoload/dist/man.vim
@@ -13,9 +13,14 @@ let s:man_tag_depth = 0
 let s:man_sect_arg = ""
 let s:man_find_arg = "-w"
 try
-  if !has("win32") && $OSTYPE !~ 'cygwin\|linux' && system('uname -s') =~ "SunOS" && system('uname -r') =~ "^5"
-    let s:man_sect_arg = "-s"
-    let s:man_find_arg = "-l"
+  if !has("win32") && $OSTYPE !~ 'cygwin\|linux'
+    if system('uname -s') =~ "SunOS" && system('uname -r') =~ "^5"
+      let s:man_sect_arg = "-s"
+      let s:man_find_arg = "-l"
+    elseif system('uname -s') =~ "AIX"
+      let s:man_sect_arg = ""
+      let s:man_find_arg = ""
+    endif
   endif
 catch /E145:/
   " Ignore the error in restricted mode
```

**Comment by chrisbra** [comment]
probably, that's why I asked for `uname -s` output above

**Comment by XSven** [comment]
Yes `uname -s` on AIX returns **AIX**.

I have tested the @k-takata patch on AIX and it works! I appreciate the non-proprietary (not based on `$OSTYPE`) patch. 

How is this patch now released? Could I install a plugin (`man.vim`) specific patch separate from an official vim release?
