### ISSUE TITLE
Setting synax for a popup, from a window that has `scrollbind` set, causes scrolling of the said window

### ISSUE THREAD

**Issue by bstaletic** [vim/vim#13863]
### Steps to reproduce

This was first seen by a [YCM user](https://github.com/ycm-core/YouCompleteMe/issues/4184) and then by me.

1. Create a file with enough lines to not be able to see the whole file in a buffer.
2. `vim --clean test_file`
3. `:set scrollbind`
4. `G` - go to the last line.
5. `:call setbufvar( winbufnr( popup_atcursor(['asd'], {}) ), '&syntax', 'python' )` - spawn the popup and set its syntax.
6. Observe that the window shifts.

### Expected behaviour

After step 5 above, the window from which the popup has been spawned should not shift.
This is especially problematic in `vimdiff` view, because only one window will shift.

### Version of Vim

9.0.2167 and 9.0.749

### Environment

My system:
- OS: Gentoo linux
- Terminal: st 0.9
- `$TERM`: xterm-256color
- Shell: zsh 5.9

The user's system:
- OS: Ubuntu 22.04.3 LTS

**Comment by chrisbra** [comment]
Hm, I guess, since `scrollbind` is an option local to the current window, it get's inherited when creating the popup window and since the cursor moves to the first line, the original window also scrolls up. 
This following minimal patch makes sure to keep the `topline` value the same. Hopefully this doesn't brake any tests.
```diff
diff --git a/src/evalvars.c b/src/evalvars.c
index 8e42c5a30..4ceb0a102 100644
--- a/src/evalvars.c
+++ b/src/evalvars.c
@@ -4924,6 +4924,7 @@ f_setbufvar(typval_T *argvars, typval_T *rettv UNUSED)
     if (*varname == '&')
     {
        aco_save_T      aco;
+       linenr_T        old_topline = curwin->w_topline;

        // Set curbuf to be our buf, temporarily.
        aucmd_prepbuf(&aco, buf);
@@ -4935,6 +4936,7 @@ f_setbufvar(typval_T *argvars, typval_T *rettv UNUSED)
            // reset notion of buffer
            aucmd_restbuf(&aco);
        }
+       curwin->w_topline = old_topline;
     }
     else
     {
```

**Comment by bstaletic** [comment]
Just to make sure we're on the same page, just spawning a popup will not make the original window scroll. Only after setting `&syntax` for the popup does the original window scroll.

I have also attempted to explicitly set `&scrollbind` to 0 for the popup, but that did not work.

**Comment by chrisbra** [comment]
> Only after setting &syntax for the popup does the original window scroll

I suppose this also happens with other options however?

> I have also attempted to explicitly set &scrollbind to 0 for the popup, but that did not work.

I suppose that might have been too late. It may work by temporarily disabling scrollbind in the original window before creating the popup window.

**Comment by bstaletic** [comment]
> I suppose this also happens with other options however?

That's right. I've tried with a few other options.

> I suppose that might have been too late. It may work by temporarily disabling scrollbind in the original window before creating the popup window.

That was interesting. I have tried two scenarios:

#### Scenario 1

1. Save current `scrollbind`
2. Set current `scrollbind` to 0
3. Open popup
4. Restore old `scrollbind` value.
5. Set popup syntax

That still caused the original window to shift.

#### Scenario 2

1. Save current `scrollbind`
2. Set current `scrollbind` to 0
3. Spawn the popup.
4. Set the popup syntax.
5. Restore old `scrollbind` value.

In this case the issue was avoided.

And just in case you missed my edit above, your branch also avoids the problem.
