### ISSUE TITLE
[netrw v162h] gx does not bring up the url in a browser

### ISSUE THREAD

**Issue by xc1427** [vim/vim#1386]
**Environment:**
gvim 8.0.45 64bit on windows 10 or windows 7.
netrw v162h

**Bug description:**
 gx (|netrw-gx|) executed on an URL downloads the URL as a file.
I didn't set g:netrw_gx and g:netrw_browsex_viewer variable.

**Expected behavior:**
gx brings up the URL in a browser.

**Comment by cecamp** [comment]
Please try the directions in :help netrw-debug.  I don't have a windows 10 system myself to work with.

**Comment by xc1427** [comment]
> cecamp commented 7 hours ago
Please try the directions in :help netrw-debug. I don't have a windows 10 system myself to work with.

FYI, I also tested on a windows 7 PC, which shows the same problem. I will try the debug later.

**Comment by xc1427** [comment]
@cecamp Disable all the other plugin does not solve the problem. So I activated Decho and I found the problem is from netrw.
**Actually, gx in visual mode did bring up the url in browser**. Then I compared the debug information between gx in normal mode and visual mode.

**In visual mode:**
`netrw#BrowseXVis` calls `netrw#CheckIfRemote` without parameter, letting `remote=0`. As a result, `fname` is assigned by `a:fname`, which is the URL. 

**In normal mode:**
On the contrary, `netrw#CheckIfRemote` is called with parameter, letting `remote=1`. In consequence, `netrw#BrowseX` creates a local copy (netrw.vim 162j :5087), making `fname` renamed by a tmp file.

\****Solution***\*
The simple solution is to remove the parameter passed into the function `CheckIfRemote` at line 84 in the file `vimfiles/plugin/netrwPlugin.vim`. So this line should be:
```
  nno <silent> <Plug>NetrwBrowseX :call netrw#BrowseX(netrw#GX(),netrw#CheckIfRemote())<cr>
```
An URL is indeed a _remote_ resource. But here it should be treated as a local one as in `gx-visual`.

**Debug info**
I paste below the debug information when url [http://chez-syl.fr/2012/03/bonnes-pratiques-jquery/](http://chez-syl.fr/2012/03/bonnes-pratiques-jquery/) is operated by gx.

- Debug normal gx
``` vim
 netrw#CheckIfRemote() a:0=1 {
|curfile<http://chez-syl.fr/2012/03/bonnes-pratiques-jquery/>
|return netrw#CheckIfRemote 1 }
netrw#BrowseX(fname<http://chez-syl.fr/2012/03/bonnes-pratiques-jquery/> remote=1) {
|remote: a:remote=1: create a local copy of <http://chez-syl.fr/2012/03/bonnes-pratiques-jquery/> ~53
|basename<chez-syl> ~59
|newname <C:/Users/cxi/AppData/Local/Temp/chez-syl.tmp> ~60
|newname=C:/Users/cxi/AppData/Local/Temp/chez-syl.tmp
|fname<C:/Users/cxi/AppData/Local/Temp/chez-syl.tmp> ~79
|exten<fr/2012/03/bonnes-pratiques-jquery/> netrwFileHandlers#NFH_fr/2012/03/bonnes-pratiques-jquery/():exists=0 ~80
|windows ~134
|return netrw#BrowseX }
```
- Debug visual gx
``` vim
netrw#BrowseXVis() {
|@@<http://chez-syl.fr/2012/03/bonnes-pratiques-jquery/> ~4
|netrw#CheckIfRemote() a:0=0 {
||curfile<Git_repo/tabcdn_simulmo/README.md>
||return netrw#CheckIfRemote 0 }
|netrw#BrowseX(fname<http://chez-syl.fr/2012/03/bonnes-pratiques-jquery/> remote=0) {
||fname<http://chez-syl.fr/2012/03/bonnes-pratiques-jquery/> ~79
||exten<fr/2012/03/bonnes-pratiques-jquery/> netrwFileHandlers#NFH_fr/2012/03/bonnes-pratiques-jquery/():exists=0 ~80
||windows ~134
||return netrw#BrowseX }
|return netrw#BrowseXVis }
```

**Comment by xc1427** [comment]
**News on version v162k:**
gx(visual) now works the same way as gx(normal). So gx(visual) ***does not either*** bring up the URL in a browser if you highlights an URL like _http://www.free.fr_ and do `gx`. 

This is because the function `netrw#BrowseXVis`, which is executed by gx(visual), is slightly modified in v162k:
``` vim
" See file vimfiles/autoload/netrw.vim:5327
call netrw#BrowseX(@@,netrw#CheckIfRemote(@@))
```

which was called ***without checking if remote*** in previous version:
``` vim
call netrw#BrowseX(@@,netrw#CheckIfRemote())
```

**Remarks on the unified `gx` behavior:**
When we do `gx` (either visual or normal) on a string having a pattern as _xxx://_, `netrw` considers it as a _remote_ file. However on windows this string should be consider as a _local_ file if you want a browser to open it.
So if you want to open a URL without modifying the source code of netrw, visual select an URL excluding the _http://_ part, then use `gx` to open it. The fault with this solution is that it cannot handle the URL which can only be opened by _https_ protocol.

**Comment by cecamp** [comment]
Chen XI wrote:
>
> *News on version v162k:*
> gx(visual) now works the same way as gx(normal). So gx(visual) *does 
> not either* bring URL in a browser if your highlight an URL like 
> /http://xxx/.
>
> This is because the function |netrw#BrowseXVis|, which is executed by 
> gx(visual), is slightly modified in v162k:
>
> " See file vimfiles/autoload/netrw.vim:5327
> call  netrw#BrowseX(@@,netrw#CheckIfRemote(@@))
>
> which was called *without parameter* in previous version:
>
> call  netrw#BrowseX(@@,netrw#CheckIfRemote())
>
That's because the "without parameter" call was incorrect.

gx is intended to handle urls like http://xxx.whatever/  (note that 
trailing slash), and it needs to know whether the call is local or remote.
You should get a message: ***error*** not a netrw-style url; netrw uses 
protocol://[user@]hostname[:port]/[path])

Chip Campbell

**Comment by xc1427** [comment]
> That's because the "without parameter" call was incorrect.

I agree with you.  And I think gx is meant to handler other url-like string such as ftp, scp, etc as well.

> You should get a message: ***error*** not a netrw-style url; netrw uses
> protocol://[user@]hostname[:port]/[path])

I didn't get this error message but some bizarre split window behavior . This is another story about netrw#ErrorMsg() not working correctly. Nevertheless, this message should have been printed.

> gx is intended to handle urls like http://xxx.whatever/  (note that
> trailing slash), and it needs to know whether the call is local or remote.

The question is how `netrw` should handle a _http(s)://_ string. The actual behavior on win10 is that it considers _http(s)://_ a remote call, then downloads the web page, renames it as xxxx.tmp and tries to open this tmp file. But this behavior does not make any sense. While, if http(s):// is seen as local, then it can be directly handled by a browser and I think that makes sense. 

I think some finer condition test should be written inside the `netrw#BrowseX` function.

**Comment by astyagun** [comment]
I see the problem on macOS as well:

![netrw](https://user-images.githubusercontent.com/158815/33214202-f4006ca8-d13b-11e7-866f-e2061ec151b7.gif)

**Environment**:

* macOS High Sierra 10.13.1 (17B48)
* MacVim 8.0.1272 (142)
* netRW v162: Sep 19, 2016

**Comment by mmikeww** [comment]
in Gvim7.4 on Windows, pressing gx over a URL would successfully open Chrome. First I would get a quick cmd window that would disappear and then the browser would open

in Gvim8, I'm seeing the cmd window open and close, and then quickly seeing this error in the Vim command line:

"NetrwMessage" --No lines in buffer--

and then the error disappears and it opens up a horizontal split

**Comment by k-takata** [comment]
I personally use [open-browser.vim](https://github.com/tyru/open-browser.vim) for this purpose.
I think it is stable and tested well. Moreover, it works on many platforms including macOS, Linux, Windows, etc.

**Comment by pinggit** [comment]
is there a fix to this issue yet?
I just tested the fresh new cygwin install that contains vim8. seem issue and no luck.
will have to try the open-browser.vim plugin...

**Comment by jsatk** [comment]
I'm still getting this issue. I'd love to not have to not install yet another plugin. 

I'm willing to help diagnose and code to help fix the issue.

**Comment by cecamp** [comment]
Jesse Atkinson wrote:
>
> I'm still getting this issue. I'd love to not have to not install yet 
> another plugin.
>
> I'm willing to help diagnose and code to help fix the issue.
>
>
I don't see this problem, but then I don't have windows 10.

May I suggest you look at :help netrw-debug for directions on how to 
debug netrw.

Regards,
C Campbell

**Comment by ankit-jha** [comment]
Is there any work around for this other than installing some plugin ?
May be some flag value set in .vimrc

**Comment by cecamp** [comment]
It would help if a volunteer would take the advice in  :help netrw-debug .  I don't have a Mac and so can't really debug this without such help.

**Comment by jsatk** [comment]
I am still getting this issue. `gx` does not *always* open links in the browser. Seems dependent on what file type I'm in.

**Comment by chrisbra** [comment]
@jsatk if you want this fixed, follow the advice from https://github.com/vim/vim/issues/1386#issuecomment-520963550

**Comment by chrisbra** [comment]
closing this in favor of #4738 (which seems to be a duplicate).
