### ISSUE TITLE
duplicate help tags?

### ISSUE THREAD

**Issue by habamax** [vim/vim#13860]
### Steps to reproduce

1. `vim -Nu NONE`
2. `:helptags ALL`

### Expected behaviour

![image](https://github.com/vim/vim/assets/234774/6d986c2b-61c5-4802-b9ea-dbb0366200db)

### Version of Vim

9.1.0027

### Environment

debian, simple terminal, bash

**Comment by habamax** [comment]
the issue is in newish `foreach`:

https://github.com/vim/vim/blob/master/runtime/doc/builtin.txt#L3004-L3004

that clashes with what is in `eval.txt`:

https://github.com/vim/vim/blob/master/runtime/doc/eval.txt#L3088-L3088

**Comment by habamax** [comment]
@errael fyi

**Comment by errael** [comment]
Oops, thanks, I'll take a look. Did I miss a failing test result?

**Comment by errael** [comment]
At first I thought the error was due to more than one error using the same error number. But that's OK to do.

**Comment by chrisbra** [comment]
Thanks. 

#13865 should take care of it in the future by performing some checks for the help tags. See e.g. result here:

https://github.com/chrisbra/vim/actions/runs/7519686167/job/20468520785

**Comment by errael** [comment]
It's interesting that in the results you mention for `vimtags`, after doing
```
./doctags arabic.txt autocmd.txt builtin.txt ....
```
there's
```
uniq -d -2 tags
E741	builtin.txt	/*E741*
```

**Comment by chrisbra** [comment]
oh yeah it's there. It just doesn't generate an error...
