### ISSUE TITLE
vim file displays `[s` `(s` syntax exception

### ISSUE THREAD

**Issue by yu3s** [vim/vim#13883]
### Steps to reproduce

1. cat 1.vim
```vim
vim9script

        str[s]
        str(s)

def Test()
        str[s]
        str(s)
enddef
```
2. `vim --clean 1.vim -c 'set nu'`
![step](https://github.com/vim/vim/assets/86161857/d67cc7b2-a961-4103-a8aa-d1c650383b83)

L3 and L4 is fine
L7 and L8 is wrong

### Expected behaviour

Syntax consistent

### Version of Vim

9.1.41

### Environment

os: ubuntu18.04
terminal: windows terminal
$TERM: xterm-256color
shell: bash4.4.20

**Comment by chrisbra** [comment]
Thanks, we may need someone who is willing to take over the vim syntax script.
