### ISSUE TITLE
E340 & E440 by specific procedure in quickfix window

### ISSUE THREAD

**Issue by kawarimidoll** [vim/vim#13905]
### Steps to reproduce

I got E340 and E440 in quickfix window.

I think this is minimal reproduce code:

```vim
" create quickfix list (at least 2 lines to move line)
vimgrep /u/j %

" enter quickfix window
cwindow

" set modifiable
setlocal modifiable

" set autocmd to clear quickfix list
autocmd! TextChanged <buffer> call setqflist([])

" move line
move+1
```

1. save this
1. open by `vim --clean`
1. run `source`
1. press a key
1. display errors

here is demo:

https://github.com/vim/vim/assets/8146876/9198b8b5-b4ae-43b5-bf2a-a96b72427fab

### Expected behaviour

handle these errors

### Version of Vim

Vim 9.1.0 (Compiled by Homebrew)

### Environment

OS: macOS Sonoma 14.2.1
Terminal: wezterm 20230712-072601-f4abf8fd
value of $TERM: xterm-256color
Shell: zsh 5.9 (arm-apple-darwin21.3.0)

### Logs and stack traces

```shell
E340: Internal error; if you can reproduce please report a bug
E440: Undo line missing
Press ENTER or type command to continue
```

**Comment by chrisbra** [comment]
That is a very nasty TextChanged autocommand

**Comment by kawarimidoll** [comment]
In fact, I was not trying to set an autocmd to clear list from the beginning.
At first I just wanted to parse the quickfix list and update it.
Then I discovered this problem when the parsing failed and the list became empty.
