### ISSUE TITLE
QML indent doesn't handle shiftwidth=0

### ISSUE THREAD

**Issue by versusvoid** [vim/vim#13907]
### Steps to reproduce

1. `set shiftwidth=0`
2. indent a .qml file
3. any indent is erased

### Expected behaviour

Correctly indented file (using value of `tabstop`)

### Version of Vim

9.1

### Environment

Archlinux
alacritty
fish shell 3.7.0

**Comment by chrisbra** [comment]
I think you want to discuss with the maintainer of the indent file: https://github.com/vim/vim/blob/459867b6313c85a891074eedbb20e1e3b44e93c7/runtime/indent/qml.vim#L3

Please also be more precise. How do you indent? What do you mean by that.
