### ISSUE TITLE
VIM uses wrong encoding - but only in status messages

### ISSUE THREAD

**Issue by hron84** [vim/vim#13900]
### Steps to reproduce

1. Set default language as Hungarian
2. Open Vim
3. Enter into Insert mode
4. See the issue

### Expected behaviour

Accented characters appear normal

### Version of Vim

VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Jan 02 2024 18:36:25)

### Environment

Operating System: Arch Linux
Terminal: Mate Terminal 1.27.1
Value of $TERM: xterm-256color
Shell: ZSH

### Logs and stack traces

Original issue is here: https://superuser.com/questions/1825655/vim-uses-wrong-encoding-but-only-in-status-messages

**Comment by chrisbra** [comment]
since you seem to be hungarian speeking, you should either reach out to the maintainer of the file, or see if you can fix the encoding issue and propose a PR to fix this.

**Comment by RestorerZ** [comment]
@hron84 ,
In the "hu.po" file, the text [encoding is set](https://github.com/vim/vim/blame/459867b6313c85a891074eedbb20e1e3b44e93c7/src/po/hu.po#L19) as ISO-8859-1.
And you are using UTF-8 encoding.
You need to change the encoding to UTF-8 in the original PO file and re-create the MO file. If the translation language requires ISO-8859-1 text encoding, you need to add a corresponding MOCONVERTED entry to the Make_all.mak file. 
But it is better to contact the maintainer of this translation @arpadffy .
Or use ISO-8859-1 encoding in Vim.

**Comment by k-takata** [comment]
Cc @arpadffy

**Comment by k-takata** [comment]
It looks like hu.po is saved in UTF-8. So, changing the line 19 to UTF-8 is enough?

**Comment by RestorerZ** [comment]
@k-takata ,
honestly, I don't know why the author chose to encode the text as `ISO-8859-1`. Based on this [information](https://en.wikipedia.org/wiki/ISO/IEC_8859-1#Languages_with_incomplete_coverage), it seems that `ISO-8859-1` is not fully compatible with Hungarian. And for Hungarian, `ISO-8859-2` or `Windows-1250` would be better suited.
Yes, you can just change the "`charset`" field to `UTF-8`, save the changes and recreate the MO file.
It will look something like this:
![hu-po-correct](https://github.com/vim/vim/assets/69863286/ded24c31-556a-463e-854a-9fe8d5bdf640)


---------------------------------------------------------------------------
Perhaps what would be possible would be to do a check in the "`check.vim`" file from the "`po`" directory to check for a match between the file encoding (value '`fenc`') and the "`charset`" field. But there are "pitfalls" there, as I remember, related to the '`fencs`' parameter. So it probably won't work.

**Comment by arpadffy** [comment]
Thank you @hron84 and @k-takata for nailing this issue.
It was a copy/paste mistake.
I have corrected the bug in the pull request #13902

Thanks,
Z

**Comment by tonymec** [comment]
ISO 8859-1 hasn't got the double-acute-accented vowels peculiar to Hungarian AFAICT. Maybe some other ISO 8859 encoding has them (ISO 8859-2 maybe ?), but why reinvent the wheel ? UTF-8 has **every**thing.

**Comment by hron84** [comment]
Thanks guys!
