### ISSUE TITLE
Fortran syntax highlighting broken

### ISSUE THREAD

**Issue by MarDiehl** [vim/vim#13911]
### Steps to reproduce

1. open a Fortran file (*.f90 extension)
1. run `:set syntax=fortran`

fractions of word that contain certain keywords are highlighted, e.g.
-  `type` in `datatype`
- `select` in `IEEE_selected_real_kind`

### Expected behaviour

keywords that are parts of other words should not be highlighed

### Version of Vim

9.1

### Environment

Arch Linux, Gnome Terminal 3.50.1, `TERM=xterm-256color`, zsh

### Logs and stack traces

```shell
program test
  use, intrinsic :: IEEE_arithmetic

  implicit none

  integer :: memtype
  integer, parameter :: p = IEEE_selected_real_kind(15,307)

end program test
```

**Comment by habamax** [comment]
can't reproduce it

![image](https://github.com/vim/vim/assets/234774/026b99e2-a25f-4a38-bdb9-2388c31a76b6)

**Comment by chrisbra** [comment]
Latest fortran syntax script was updated in ef79c5783782d12bdc6c40cf24d578cc6a1f2a8c

You did not show the complete version output, please try with latest Vim with updated runtime files.

**Comment by MarDiehl** [comment]
@habamax and @chrisbra  thanks for the quick reply

It works with the current `fortran.vim`
