### ISSUE TITLE
Suddenly broken autocommands

### ISSUE THREAD

**Issue by chdiza** [vim/vim#13913]
### Steps to reproduce

Start vim and set &ft to `mail`.  Observe:
```
Error detected while processing FileType Autocommands for "*"..Syntax Autocommands for
 "*"..Syntax Autocommands for "*"..function <SNR>4_SynSet[25]..script /pathtovimruntime/share/vim/vim91/syntax/mail.vim:
line   67:
E945: Range too large in character class
Press ENTER or type command to continue
```

### Expected behaviour

I expect that not to happen.  This just started after a fresh build, so the bad commit happened within the last couple of days.  I'm at work and don't have time to bisect right now.

### Version of Vim

9.1.50

### Environment

Linux Mint 21.something

**Comment by chdiza** [comment]
Have to be away from machine for a while, but I've discovered that having `se re=1` in my vimrc is a necessary condition of this happening.

**Comment by chrisbra** [comment]
Yeah, it comes from this commit: 36e2c0f29332bd430f03c007be56fc6894f49923 I'll ping the maintainer to add `\%#=2` at the beginning of that particular syntax match. (although I am not really sure, that the DFA regex engine can handle such a large range in a collation).

**Comment by chdiza** [comment]
OK, thanks.  That is indeed the commit.  I tested your suggested fix and it seems to work.

Separately, it's not clear to me why that commit messed with so many of the `:hi` colors.  Is there a good reason for this?

**Comment by gi1242** [comment]
I'll send a pull request with the fix shortly. I changed the default groups because I (finally) moved to newer color schemes. Most of them seem to dim comments, so it made more sense to highlight signatures as comments instead of quoted texts.
