### ISSUE TITLE
mapping of <C-=> and <C-0> failure from patch 9.1.0050 on Windows

### ISSUE THREAD

**Issue by Passw** [vim/vim#13927]
### Steps to reproduce

`:map <C-=> :echo "hi"<CR>`
`:map <C-0> :echo "hi2"<CR>`

when press <kbd>C-=</kbd> and <kbd>C-0</kbd>, no prints

### Expected behaviour

press <kbd>C-=</kbd> to print `hi`
press <kbd>C-0</kbd> to print `hi2`

### Version of Vim

from patch 9.1.0050

### Environment

OS: Windows GVIM

### Logs and stack traces

It's confirmed that this commit https://github.com/vim/vim/commit/68d9472c65ec75725a0b431048bebe036921331c caused this issue

**Comment by chrisbra** [comment]
Have you read the mentioned documentation?

**Comment by chrisbra** [comment]
yeah, I should have mentioned it's a breaking change. Sorry for that
