### ISSUE TITLE
Error detected while processing WinEnter Autocommands for "*"..function <SNR>38_HandleOnlyWindow[13]..<SNR>38_CloseWindow

### ISSUE THREAD

**Issue by lijh8** [vim/vim#13949]
### Steps to reproduce

Hi, i'm using vim with nerdtree and tagbar. 
with both nerdtree and tagbar toggled on, when i quit editing my last c++ source file, there's this error.

```
Error detected while processing WinEnter Autocommands for "*"..function <SNR>38_HandleOnlyWindow[13]..<SNR>38_CloseWindow:
line   21:
E1312: Not allowed to change the window layout in this autocmd

```

---

this is ~/.vimrc:

```

set expandtab
set hlsearch
set nowrapscan
set shiftwidth=4
set smartindent
set tabstop=4
syntax off

" NERDTree
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif
autocmd BufEnter * if winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif
autocmd VimEnter * NERDTree
let g:NERDTreeNodeDelimiter = "\u00a0"
nnoremap <leader>n :NERDTreeFocus<CR> " \ - n
nnoremap <C-n> :NERDTree<CR>          " Ctrl - n
nnoremap <C-t> :NERDTreeToggle<CR>    " Ctrl - t
nnoremap <C-f> :NERDTreeFind<CR>

" tagbar
filetype on            " Tagbar: Filetype detection is turned off, skipping plugin
let g:tagbar_sort = 0  " order of position
nmap <F8> :TagbarToggle<CR>

```

![Screen Shot 2024-02-01 at 22 33 58](https://github.com/vim/vim/assets/9011764/5746daa7-6fb9-41f6-9b1d-9005fa358156)
![Screen Shot 2024-02-01 at 22 34 04](https://github.com/vim/vim/assets/9011764/007ac58e-b69c-4d06-9762-40d30f8f0b5d)

### Expected behaviour

Do not know whether it's related to nerdtree, tagbar, or vim.

https://github.com/preservim/nerdtree , 
https://github.com/preservim/tagbar ,

### Version of Vim

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Oct 27 2023 01:00:56)

### Environment

OS: macOS 12.7.3 (21H1015)

$ uname -a
Darwin ljhs-Mac.local 21.6.0 Darwin Kernel Version 21.6.0: Sun Dec 17 22:55:27 PST 2023; root:xnu-8020.240.18.706.2~1/RELEASE_X86_64 x86_64

$ echo $TERM
xterm-256color

$ echo $SHELL
/bin/zsh
$

**Comment by chrisbra** [comment]
Check the output of `:scriptnames`. Nr 38. that is where you should report this issue

**Comment by Bobik3310** [comment]
Use :qall/:wall instead of :q/:w
