### ISSUE TITLE
DarkBlue display error in Windows Console

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#13956]
### Steps to reproduce

1. On Windows, start vim.exe and enable syntax
2. download colorscheme "borland" from https://www.vim.org/scripts/script.php?script_id=92
3. put borland.vim in ~/.vim/colors
4. execute ":color borland"

you will found every highlight group contains "ctermbg=DarkBlue" or "ctermbg=4" will display as red:

![图片](https://github.com/vim/vim/assets/3035071/5b200523-e764-4c87-891b-4c2010b050b6)

show the detail of `Normal`:

```VimL
:hi Normal
```

![图片](https://github.com/vim/vim/assets/3035071/8d5122f6-94d0-4452-916d-d60c5ccb9d59)

The ctermbg is `4` which is DarkBlue in the terminal mode, but it displayed as red.

But `ctermbg=4` in `NonText` works as expected:

```VimL
:hi NonText
```

![图片](https://github.com/vim/vim/assets/3035071/e96651af-17b2-448e-895a-d166e39c3b14)

Every colorscheme contains DarkBlue in its background will encounter this error, including: 

1) borland
2) ibmedit
3) turbo

etc...

### Expected behaviour

Should display like this (mintty, linux):

![图片](https://github.com/vim/vim/assets/3035071/4a099434-224a-4736-b614-853a5022ff2a)

### Version of Vim

9.1.61

### Environment

OS: Windows 10
Terminal: cmd.exe
$TERM: unset

**Comment by chrisbra** [comment]
can you please try `:set t_ut=` and the force a redraw?

**Comment by skywind3000** [comment]
@chrisbra `:set t_ut=` can fix this:

![图片](https://github.com/vim/vim/assets/3035071/8d40e050-9abf-405c-a064-1b166fa226e0)

according to the docs:

> t_ut	clearing uses the current background color	

What is the current background color ? why it is RED ? how to change this ?

**Comment by chrisbra** [comment]
I think it is for the so called feature *background color erase*, which is a feature of your terminal. I think when it is enabled, Vim will not color the background of "empty content" but assume the terminal will do it. But when the terminal has a different idea of what your terminal background should look like than you see those funny artifacts. If you disable it `:set t_ut=` then Vim will color the whole screen using the Normal highlighting.

It also has some rendering performance implications and it may differ between the old and new windows terminal.
