### ISSUE TITLE
Black box appears on vim

### ISSUE THREAD

**Issue by cMerd** [vim/vim#13951]
### Steps to reproduce

1. Run vim without changing terminal size
There will be an annoying little black box on screen:
![vim_error](https://github.com/vim/vim/assets/158254121/b24862d9-3ea7-481e-b55a-767be0e099e6)

### Expected behaviour

VIM to open with a new file window

### Version of Vim

VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Jan 02 2024 18:36:25)

### Environment

OS: Arch linux (6.7.2-arch1-1)
Terminal emulator: Konsole
Shell: ZSH
Value of $TERM: xterm-256color

### Note

Little black box disappears when changing terminal font size or relaunching vim (without closing terminal emulator)
Same error does not happen on kitty terminal emulator.

**Comment by chrisbra** [comment]
> VIM to open with a new file window

What do you mean with this?

**Comment by cMerd** [comment]
> > VIM to open with a new file window
> 
> What do you mean with this?

I mean when you don't insert a file name it just opens like I gave in screenshot writing "Vi IMproved" in center. Empty. But There's a black glitch on top left of screen.

**Comment by chrisbra** [comment]
That is default behavious of the intro screen. It's always there. See also `:h shm-I`

**Comment by cMerd** [comment]
You got it wrong, my problem is not intro message. The problem is black color on screen: 
![20240201-205403](https://github.com/vim/vim/assets/158254121/3e46429d-cffc-44ee-bba8-2345ad6a4018)

**Comment by chrisbra** [comment]
seems like an issue with specifying ` $TERM: xterm-256color` when your term is not really xterm compatible

**Comment by cMerd** [comment]
> seems like an issue with specifying ` $TERM: xterm-256color` when your term is not really xterm compatible

What value do i need to write to TERM?

**Comment by chrisbra** [comment]
For Konsole? I don't know, try : `konsole-256color` or `konsole-direct` according to this [wiki](https://wiki.archlinux.org/title/Konsole)

**Comment by cMerd** [comment]
Same error does not happen on kitty terminal emulator: 
![20240201-212330](https://github.com/vim/vim/assets/158254121/67dbe2a0-bef9-4a54-9b55-2c46da5e7446)

**Comment by chrisbra** [comment]
It's terminal related, yes. Vim sends an ansi escape sequence that your terminal does not understand and shows it instead. Perhaps try updating your konsole. Or use `--log` to capture what has been sent to the terminal try to figure out which escape sequence causes issues. Or try some of the builtin terminal definitions: `:set term=xxx` (to see which ones are available). If I would have to guess, I would think it might be either `:set t_u7?` or `:set t_RV?` or `t_RF?` or `t_RB?`
