### ISSUE TITLE
`.luaurc` filetype detection

### ISSUE THREAD

**Issue by lopi-py** [vim/vim#13960]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
Vim currently doesn't set a filetype for `.luaurc` file ([Luau](https://luau-lang.org/)'s analysis [config file](https://rfcs.luau-lang.org/config-luaurc.html))

**Describe the solution you'd like**
Set `jsonc` filetype when entering a file with name `.luaurc`

**Comment by chrisbra** [comment]
How about a patch then?
