### ISSUE TITLE
Feature Request: mode() returns Insert sub-mode

### ISSUE THREAD

**Issue by zhen-huan-hu** [vim/vim#1397]
Please make mode() return i_CTRL-X sub mode. Currently there seems to be no way to determine this. It would be very helpful for writing completion plugins.

**Comment by vim-ml** [comment]
Hi,

On Thu, Jan 19, 2017 at 8:39 AM, Zhen-Huan (Kenny) Hu
<vim-dev-github@256bit.org> wrote:
> Please make mode() return i_CTRL-X sub mode. Currently there seems to be no
> way to determine this. It would be very helpful for writing completion
> plugins.
>

Can you try the attached diff? The mode() function will return
'x' in i_CTRL-X sub mode. Need to test this under different insert mode
conditions where CTRL-X can be pressed.

- Yegappan

diff --git a/src/evalfunc.c b/src/evalfunc.c
index 4b6bfaa..69a36e0 100644
--- a/src/evalfunc.c
+++ b/src/evalfunc.c
@@ -7757,6 +7757,11 @@ f_mode(typval_T *argvars, typval_T *rettv)
 	buf[0] = '!';
     else if (State & INSERT)
     {
+#ifdef FEAT_INS_EXPAND
+	if (ctrl_x_mode != 0)
+	    buf[0] = 'x';
+	else
+#endif
 #ifdef FEAT_VREPLACE
 	if (State & VREPLACE_FLAG)
 	{

**Comment by brammool** [comment]
Since it's a sub mode of insert it should be "ix".

**Comment by chrisbra** [comment]
but mode() only returns one letter without argument.

**Comment by zhen-huan-hu** [comment]
>```
> #ifdef FEAT_INS_EXPAND
> 	if (ctrl_x_mode != 0)
> 	    buf[0] = 'x';
> 	else
> #endif
> ```

I tested the code. `mode()` all returns `x` as expected when pressing `<C-x>` alone, or combined with `<C-d>`, `<C-f>`, `<C-i>`, `<C-v>`, `<C-l>`, `<C-s>`, `<C-o>`, as well as `<C-e>`, `<C-y>`

Pressing `<C-x><C-n>` or `<C-x><C-p>`, `mode()` returns `i` (which is correct).

I agree it should be `ix` since it's a sub-mode.

**Comment by vim-ml** [comment]
Hi Bram,

On Thu, Jan 19, 2017 at 1:43 PM, Bram Moolenaar
<vim-dev-github@256bit.org> wrote:
> Since it's a sub mode of insert it should be "ix".
>

The CTRL-X key can be used in Replace mode also. So it
is either 'ix' or 'Rx'.

- Yegappan

**Comment by vim-ml** [comment]
Hi,

On Thu, Jan 19, 2017 at 3:56 PM, Zhen-Huan (Kenny) Hu
<vim-dev-github@256bit.org> wrote:
> #ifdef FEAT_INS_EXPAND
> if (ctrl_x_mode != 0)
>    buf[0] = 'x';
> else
> #endif
>
> I tested the code. mode() all returns x as expected when pressing <C-x>
> alone, or combined with <C-d>, <C-f>, <C-i>, <C-v>, <C-l>, <C-s>, <C-o>, as
> well as <C-e>, <C-y>
>
> Pressing <C-x><C-n> or <C-x><C-p>, mode() returns i.
>
> I agree it should be ix since it's a sub-mode.
>

An updated patch to return either "ix" or "Rx" is attached.

- Yegappan

diff --git a/src/evalfunc.c b/src/evalfunc.c
index 4b6bfaa..1f3164f 100644
--- a/src/evalfunc.c
+++ b/src/evalfunc.c
@@ -7765,10 +7765,16 @@ f_mode(typval_T *argvars, typval_T *rettv)
 	}
 	else
 #endif
-	if (State & REPLACE_FLAG)
-	    buf[0] = 'R';
-	else
-	    buf[0] = 'i';
+	{
+	    if (State & REPLACE_FLAG)
+		buf[0] = 'R';
+	    else
+		buf[0] = 'i';
+#ifdef FEAT_INS_EXPAND
+	    if (ctrl_x_mode != 0)
+		buf[1] = 'x';
+#endif
+	}
     }
     else if (State & CMDLINE)
     {

**Comment by vim-ml** [comment]
Hi Bram, Yegappan, Zhen and Vim developers,

2017-1-20(Fri) 12:44:50 UTC+9 vim-dev ML:
> Hi,
> 
> 
> 
> On Thu, Jan 19, 2017 at 3:56 PM, Zhen-Huan (Kenny) Hu
> 
> <vim-dev...@256bit.org> wrote:
> 
> > #ifdef FEAT_INS_EXPAND
> 
> > if (ctrl_x_mode != 0)
> 
> >    buf[0] = 'x';
> 
> > else
> 
> > #endif
> 
> >
> 
> > I tested the code. mode() all returns x as expected when pressing <C-x>
> 
> > alone, or combined with <C-d>, <C-f>, <C-i>, <C-v>, <C-l>, <C-s>, <C-o>, as
> 
> > well as <C-e>, <C-y>
> 
> >
> 
> > Pressing <C-x><C-n> or <C-x><C-p>, mode() returns i.
> 
> >
> 
> > I agree it should be ix since it's a sub-mode.
> 
> >
> 
> 
> 
> An updated patch to return either "ix" or "Rx" is attached.
[...]

How about attached patch?
--
Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by vim-ml** [comment]
Hi Hirohito,

On Fri, Jan 20, 2017 at 7:44 AM, h_east <h.east.727@gmail.com> wrote:
> Hi Bram, Yegappan, Zhen and Vim developers,
>
> 2017-1-20(Fri) 12:44:50 UTC+9 vim-dev ML:
>> Hi,
>>
>>
>>
>> On Thu, Jan 19, 2017 at 3:56 PM, Zhen-Huan (Kenny) Hu
>>
>> <vim-dev...@256bit.org> wrote:
>>
>> > #ifdef FEAT_INS_EXPAND
>>
>> > if (ctrl_x_mode != 0)
>>
>> >    buf[0] = 'x';
>>
>> > else
>>
>> > #endif
>>
>> >
>>
>> > I tested the code. mode() all returns x as expected when pressing <C-x>
>>
>> > alone, or combined with <C-d>, <C-f>, <C-i>, <C-v>, <C-l>, <C-s>, <C-o>, as
>>
>> > well as <C-e>, <C-y>
>>
>> >
>>
>> > Pressing <C-x><C-n> or <C-x><C-p>, mode() returns i.
>>
>> >
>>
>> > I agree it should be ix since it's a sub-mode.
>>
>> >
>>
>>
>>
>> An updated patch to return either "ix" or "Rx" is attached.
> [...]
>
> How about attached patch?
>

Note that Ctrl-X can be pressed in replace mode also. For example, you
can press 'R' to enter replace mode and then invoke completion using
CTRL-X. This diff handles only the insert mode case.

- Yegappan

> --
> Best regards,
> Hirohito Higashi (a.k.a. h_east)
>

**Comment by zhen-huan-hu** [comment]
> ```
> diff --git a/src/evalfunc.c b/src/evalfunc.c
> index 4b6bfaa..1f3164f 100644
> --- a/src/evalfunc.c
> +++ b/src/evalfunc.c
> @@ -7765,10 +7765,16 @@ f_mode(typval_T *argvars, typval_T *rettv)
>  	}
>  	else
>  #endif
> -	if (State & REPLACE_FLAG)
> -	    buf[0] = 'R';
> -	else
> -	    buf[0] = 'i';
> +	{
> +	    if (State & REPLACE_FLAG)
> +		buf[0] = 'R';
> +	    else
> +		buf[0] = 'i';
> +#ifdef FEAT_INS_EXPAND
> +	    if (ctrl_x_mode != 0)
> +		buf[1] = 'x';
> +#endif
> +	}
>      }
>      else if (State & CMDLINE)
>      {
> ```

I tested CTRL-X under both replace mode and insert mode. Under replace mode, `mode(1)` returns `Rx` and under insert mode, it returns `ix`.

As a side note, why CTRL-N/P and CTRL-X + CTRL-N/P behave differently than CTRL-X + others. It seems if CTRL-N/P cannot find a match, it will automatically return to the insert mode. If CTRL-X + others cannot find a match, it will stay under CTRL-X mode?

**Comment by vim-ml** [comment]
Hi Yegappan,

2017-1-21(Sat) 4:20:02 UTC+9 yega...@gmail.com:
> Hi Hirohito,
> 
> On Fri, Jan 20, 2017 at 7:44 AM, h_east <h.east.727@gmail.com> wrote:
> > Hi Bram, Yegappan, Zhen and Vim developers,
> >
> > 2017-1-20(Fri) 12:44:50 UTC+9 vim-dev ML:
> >> Hi,
> >>
> >>
> >>
> >> On Thu, Jan 19, 2017 at 3:56 PM, Zhen-Huan (Kenny) Hu
> >>
> >> <vim-dev...@256bit.org> wrote:
> >>
> >> > #ifdef FEAT_INS_EXPAND
> >>
> >> > if (ctrl_x_mode != 0)
> >>
> >> >    buf[0] = 'x';
> >>
> >> > else
> >>
> >> > #endif
> >>
> >> >
> >>
> >> > I tested the code. mode() all returns x as expected when pressing <C-x>
> >>
> >> > alone, or combined with <C-d>, <C-f>, <C-i>, <C-v>, <C-l>, <C-s>, <C-o>, as
> >>
> >> > well as <C-e>, <C-y>
> >>
> >> >
> >>
> >> > Pressing <C-x><C-n> or <C-x><C-p>, mode() returns i.
> >>
> >> >
> >>
> >> > I agree it should be ix since it's a sub-mode.
> >>
> >> >
> >>
> >>
> >>
> >> An updated patch to return either "ix" or "Rx" is attached.
> > [...]
> >
> > How about attached patch?
> >
> 
> Note that Ctrl-X can be pressed in replace mode also. For example, you
> can press 'R' to enter replace mode and then invoke completion using
> CTRL-X. This diff handles only the insert mode case.

That's right. Also, Virtual Replace is the same.
Unfortunately, Two letters are not enough for CTRL-X mode on Virtual Replace mode.
For example, how do we represent it in the following cases?

  Type: gR<C-X>
  Represent: Rvx ??


Thanks for many advice.
--
Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by vim-ml** [comment]
Hi,

On Fri, Jan 20, 2017 at 12:35 PM, Zhen-Huan (Kenny) Hu
<vim-dev-github@256bit.org> wrote:
> diff --git a/src/evalfunc.c b/src/evalfunc.c
> index 4b6bfaa..1f3164f 100644
> --- a/src/evalfunc.c
> +++ b/src/evalfunc.c
> @@ -7765,10 +7765,16 @@ f_mode(typval_T *argvars, typval_T *rettv)
>   }
>   else
>  #endif
> - if (State & REPLACE_FLAG)
> -    buf[0] = 'R';
> - else
> -    buf[0] = 'i';
> + {
> +    if (State & REPLACE_FLAG)
> + buf[0] = 'R';
> +    else
> + buf[0] = 'i';
> +#ifdef FEAT_INS_EXPAND
> +    if (ctrl_x_mode != 0)
> + buf[1] = 'x';
> +#endif
> + }
>      }
>      else if (State & CMDLINE)
>      {
>
> I tested CTRL-X under both replace mode and insert mode. Under replace mode,
> mode(1) returns Rx and under insert mode, it returns ix.
>
> As a side note, why CTRL-N/P and CTRL-X + CTRL-N/P behave differently than
> CTRL-X + others. It seems if CTRL-N/P cannot find a match, it will
> automatically return to the insert mode. If CTRL-X + others cannot find a
> match, it will stay under CTRL-X mode?
>

Based on the patch from Hirohito, I have adjusted the patch to handle
this case. Try using the attached patch.

- Yegappan

diff --git a/src/evalfunc.c b/src/evalfunc.c
index 4b6bfaa..76d36f7 100644
--- a/src/evalfunc.c
+++ b/src/evalfunc.c
@@ -7765,10 +7765,18 @@ f_mode(typval_T *argvars, typval_T *rettv)
 	}
 	else
 #endif
-	if (State & REPLACE_FLAG)
-	    buf[0] = 'R';
-	else
-	    buf[0] = 'i';
+	{
+	    if (State & REPLACE_FLAG)
+		buf[0] = 'R';
+	    else
+		buf[0] = 'i';
+#ifdef FEAT_INS_EXPAND
+	    if (ctrl_x_mode != 0)
+		buf[1] = 'x';
+	    else if (ins_compl_active())
+		buf[1] = pum_visible() ? 'C' : 'c';
+#endif
+	}
     }
     else if (State & CMDLINE)
     {

**Comment by vim-ml** [comment]
Hi Hirohito,

On Fri, Jan 20, 2017 at 4:23 PM, h_east <h.east.727@gmail.com> wrote:
> Hi Yegappan,
>
> 2017-1-21(Sat) 4:20:02 UTC+9 yega...@gmail.com:
>> Hi Hirohito,
>>
>> On Fri, Jan 20, 2017 at 7:44 AM, h_east <h.east.727@gmail.com> wrote:
>> > Hi Bram, Yegappan, Zhen and Vim developers,
>> >
>> > 2017-1-20(Fri) 12:44:50 UTC+9 vim-dev ML:
>> >> Hi,
>> >>
>> >>
>> >>
>> >> On Thu, Jan 19, 2017 at 3:56 PM, Zhen-Huan (Kenny) Hu
>> >>
>> >> <vim-dev...@256bit.org> wrote:
>> >>
>> >> > #ifdef FEAT_INS_EXPAND
>> >>
>> >> > if (ctrl_x_mode != 0)
>> >>
>> >> >    buf[0] = 'x';
>> >>
>> >> > else
>> >>
>> >> > #endif
>> >>
>> >> >
>> >>
>> >> > I tested the code. mode() all returns x as expected when pressing <C-x>
>> >>
>> >> > alone, or combined with <C-d>, <C-f>, <C-i>, <C-v>, <C-l>, <C-s>, <C-o>, as
>> >>
>> >> > well as <C-e>, <C-y>
>> >>
>> >> >
>> >>
>> >> > Pressing <C-x><C-n> or <C-x><C-p>, mode() returns i.
>> >>
>> >> >
>> >>
>> >> > I agree it should be ix since it's a sub-mode.
>> >>
>> >> >
>> >>
>> >>
>> >>
>> >> An updated patch to return either "ix" or "Rx" is attached.
>> > [...]
>> >
>> > How about attached patch?
>> >
>>
>> Note that Ctrl-X can be pressed in replace mode also. For example, you
>> can press 'R' to enter replace mode and then invoke completion using
>> CTRL-X. This diff handles only the insert mode case.
>
> That's right. Also, Virtual Replace is the same.
> Unfortunately, Two letters are not enough for CTRL-X mode on Virtual Replace mode.
> For example, how do we represent it in the following cases?
>
>   Type: gR<C-X>
>   Represent: Rvx ??
>

I think, in this case three letters can be used.

Regards,
Yegappan

>
>
> Thanks for many advice.
> --
> Best regards,
> Hirohito Higashi (a.k.a. h_east)
>

**Comment by vim-ml** [comment]
Hi Yegappan,

2017-1-23(Mon) 2:40:48 UTC+9 yega...@gmail.com:
> Hi,
> 
> On Fri, Jan 20, 2017 at 12:35 PM, Zhen-Huan (Kenny) Hu
> <vim-dev-github@256bit.org> wrote:
> > diff --git a/src/evalfunc.c b/src/evalfunc.c
> > index 4b6bfaa..1f3164f 100644
> > --- a/src/evalfunc.c
> > +++ b/src/evalfunc.c
> > @@ -7765,10 +7765,16 @@ f_mode(typval_T *argvars, typval_T *rettv)
> >   }
> >   else
> >  #endif
> > - if (State & REPLACE_FLAG)
> > -    buf[0] = 'R';
> > - else
> > -    buf[0] = 'i';
> > + {
> > +    if (State & REPLACE_FLAG)
> > + buf[0] = 'R';
> > +    else
> > + buf[0] = 'i';
> > +#ifdef FEAT_INS_EXPAND
> > +    if (ctrl_x_mode != 0)
> > + buf[1] = 'x';
> > +#endif
> > + }
> >      }
> >      else if (State & CMDLINE)
> >      {
> >
> > I tested CTRL-X under both replace mode and insert mode. Under replace mode,
> > mode(1) returns Rx and under insert mode, it returns ix.
> >
> > As a side note, why CTRL-N/P and CTRL-X + CTRL-N/P behave differently than
> > CTRL-X + others. It seems if CTRL-N/P cannot find a match, it will
> > automatically return to the insert mode. If CTRL-X + others cannot find a
> > match, it will stay under CTRL-X mode?
> >
> 
> Based on the patch from Hirohito, I have adjusted the patch to handle
> this case. Try using the attached patch.

`ins_compl_active()` should be referenced before referring to `ctrl_x_mode`.
My patch's 'x' means "wait for CTRL-X mode selection".
That is, when the following text is displayed on the last line.
-- ^X mode (^]^D^E^F^I^K^L^N^O^Ps^U^V^Y)

Thanks.
--
Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by zhen-huan-hu** [comment]
> +	    else if (ins_compl_active())
> +		buf[1] = pum_visible() ? 'C' : 'c';

Does this 'C' vs. 'c' mean whether a completion was successful? I don't think pum_visible() alone is able to determine this accurately since it depends on whether the user have completeopt=menuone to have a menu if there is only one match. I'd rather not distinguish it in mode() and let it return 'ic' if `ins_compl_active()` no matther whether `pum_visible()`.

**Comment by vim-ml** [comment]
Hi All,

2017-1-24(Tue) 2:03:05 UTC+9 Zhen-Huan (Kenny) Hu:
> else if (ins_compl_active())
> 
> 
> 
> buf[1] = pum_visible() ? 'C' : 'c';
> 
> 
> 
> 
> 
> Does this 'C' vs. 'c' mean whether a completion was successful? I don't think pum_visible() alone is able to determine this accurately since it depends on whether the user have completeopt=menuone to have a menu if there is only one match. I'd rather not distinguish it in mode() and let it return 'ic' if ins_compl_active() no matther whether pum_visible().


I was also thinking somewhat similar.

It's a idea level proposal.
Adding completion info built-in function ...

completion_info()
    Returns a Dictionary with information about insert mode completion:
    "active"                When completion is active, set to 1.
    "matches"               Numner of matches.
    "Searching_match_done"  Searching match done.
    "popupmenued"           Popup menu displayed.
    "inserted"              Insert a match from the menu.
    "selected"              Select a match in the menu.
    "ctrl_x_selecting"      Waiting for the ctrl-x mode selection.
    ...

--
Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by vim-ml** [comment]
Hi,

On Mon, Jan 23, 2017 at 9:02 AM, Zhen-Huan (Kenny) Hu
<vim-dev-github@256bit.org> wrote:
> else if (ins_compl_active())
>
> buf[1] = pum_visible() ? 'C' : 'c';
>
> Does this 'C' vs. 'c' mean whether a completion was successful? I don't
> think pum_visible() alone is able to determine this accurately since it
> depends on whether the user have completeopt=menuone to have a menu if there
> is only one match. I'd rather not distinguish it in mode() and let it return
> 'ic' if ins_compl_active() no matther whether pum_visible().
>

I am attaching a patch to the mode() function that returns 'ic' or 'ix'
or 'Rc' or 'Rx' depending on the insert completion mode. I have also
added a test for the mode() function.

The idea from Hirohito to add a separate function to get more
information about the insert mode completion can be addressed in a
separate patch.

- Yegappan

diff --git a/runtime/doc/eval.txt b/runtime/doc/eval.txt
index 58a61f2..40e8a79 100644
--- a/runtime/doc/eval.txt
+++ b/runtime/doc/eval.txt
@@ -5848,8 +5848,12 @@ mode([expr])	Return a string that indicates the current mode.
 			S	Select by line
 			CTRL-S	Select blockwise
 			i	Insert
+			ic	Insert mode completion |compl-generic|
+			ix	Insert mode |i_CTRL-X| completion
 			R	Replace |R|
+			Rc	Replace mode completion |compl-generic|
 			Rv	Virtual Replace |gR|
+			Rx	Replace mode |i_CTRL-X| completion
 			c	Command-line
 			cv	Vim Ex mode |gQ|
 			ce	Normal Ex mode |Q|
diff --git a/src/evalfunc.c b/src/evalfunc.c
index 7f433a5..8f90fc1 100644
--- a/src/evalfunc.c
+++ b/src/evalfunc.c
@@ -7783,10 +7783,18 @@ f_mode(typval_T *argvars, typval_T *rettv)
 	}
 	else
 #endif
-	if (State & REPLACE_FLAG)
-	    buf[0] = 'R';
-	else
-	    buf[0] = 'i';
+	{
+	    if (State & REPLACE_FLAG)
+		buf[0] = 'R';
+	    else
+		buf[0] = 'i';
+#ifdef FEAT_INS_EXPAND
+	    if (ins_compl_active())
+		buf[1] = 'c';
+	    else if (ctrl_x_mode == 1)
+		buf[1] = 'x';
+#endif
+	}
     }
     else if (State & CMDLINE)
     {
diff --git a/src/testdir/test_functions.vim b/src/testdir/test_functions.vim
index 38f7723..e12bc6c 100644
--- a/src/testdir/test_functions.vim
+++ b/src/testdir/test_functions.vim
@@ -304,4 +304,42 @@ func Test_toupper()
   call assert_equal("Ⱥ Ⱦ", toupper("ⱥ ⱦ"))
 endfunc
 
+" Tests for the mode() function
+let saved_modes = ''
+func! Save_mode()
+  let g:saved_modes .= mode(1) . " "
+  return ''
+endfunc
 
+func! Test_mode()
+  new
+  call append(0, ["Blue Ball Black", "Brown Band Bowl", ""])
+
+  inoremap <F2> <C-R>=Save_mode()<CR>
+
+  normal! 3G
+  exe "normal i\<F2>\<Esc>"
+  exe "normal i\<C-G>uBa\<C-P>\<F2>\<Esc>u"
+  exe "normal iBro\<C-P>\<F2>\<Esc>u"
+  exe "normal iBa\<C-X>\<F2>\<Esc>u"
+  exe "normal iBa\<C-X>\<C-P>\<F2>\<Esc>u"
+  exe "normal iBro\<C-X>\<C-P>\<F2>\<Esc>u"
+  exe "normal iBro\<C-X>\<C-P>\<C-P>\<F2>\<Esc>u"
+  exe "normal iCom\<C-P>\<F2>\<Esc>u"
+  exe "normal iCom\<C-X>\<C-P>\<F2>\<Esc>u"
+
+  exe "normal RBa\<C-P>\<F2>\<Esc>u"
+  exe "normal RBro\<C-P>\<F2>\<Esc>u"
+  exe "normal RBa\<C-X>\<F2>\<Esc>u"
+  exe "normal RBa\<C-X>\<C-P>\<F2>\<Esc>u"
+  exe "normal RBro\<C-X>\<C-P>\<F2>\<Esc>u"
+  exe "normal RBro\<C-X>\<C-P>\<C-P>\<F2>\<Esc>u"
+  exe "normal RCom\<C-P>\<F2>\<Esc>u"
+  exe "normal RCom\<C-X>\<C-P>\<F2>\<Esc>u"
+
+  call assert_equal("i ic ic ix ic ic ic ic ic Rc Rc Rx Rc Rc Rc Rc Rc ",
+		  \ g:saved_modes)
+
+  enew! | close
+  iunmap <F2>
+endfunc
