### ISSUE TITLE
:set wildoptions+=tagfile and completion

### ISSUE THREAD

**Issue by desjardinsm** [vim/vim#1399]
When "set wildoptions=tagfile" it actually changes the way the ":h tag-regexp" for completion works.  With the default wildoptions of course a ":tag /<c-d>" will work as the help describes.  But with wildoptions set, ":tag /<c-d>" only lists tags starting with "/".

This occurs with "vim -Nu NONE" as well, after setting 'wop'.

This also only affects its completion.  The actual command uses the "/" as expected.

**Comment by chrisbra** [comment]
patch posted [here](https://groups.google.com/forum/#!topic/vim_dev/NUB_lHQmdjY)
