### ISSUE TITLE
X11 wheel scroll size changes unexpectedly

### ISSUE THREAD

**Issue by errael** [vim/vim#13994]
### Steps to reproduce

This is a follow on problem after #13991; with that PR, after startup the conditions are now as expected
- `scroll lines == 3` which is expected/usual on my system.
- response to wheel feels consistent (previously it stuttered as described in #13987)

But doing `"*Y` (yanking some text into the primary clipboard) the scroll size changes.
- `scroll lines == 6`

Interestingly, before #13991, a yank to the primary clipboard was a workaround to get things to work. Now it breaks things.

### Expected behaviour

Doing `"*Y` should not change the number of lines scrolled by mouse wheel "click".

As an experiment, I put the following into my vim rc.
```
map <ScrollWheelUp> <C-Y>
map <ScrollWheelDown> <C-E>
```
on startup it scrolled one line per wheel tick, after `"*Y` it scrolled two lines per tick.

### Version of Vim

9.1.0083

### Environment

ubuntu, gtk

**Comment by errael** [comment]
Ooops, forgot: ping @lilydjwg

**Comment by lilydjwg** [comment]
I've sent another patch to fix this weird bug (and two other bugs).
