### ISSUE TITLE
New compiler warning

### ISSUE THREAD

**Issue by chdiza** [vim/vim#14005]
### Steps to reproduce

Build vim from the git repo, v9.1.0090.  Observe the following, which was not present several patches ago:
```
gui_gtk_x11.c: In function ‘scroll_event’:
gui_gtk_x11.c:2068:12: warning: type defaults to ‘int’ in declaration of ‘display_type’ [-Wimplicit-int]
 2068 |     static display_type;
      |            ^~~~~~~~~~~~
```

### Expected behaviour

I don't have time to bisect, but I'm almost positive this wasn't there when I built 9.1.0083.

### Version of Vim

9.1.0090

### Environment

Linux Mint 21.1
Terminal: kitty

**Comment by chrisbra** [comment]
thanks, I fixed it.
