### ISSUE TITLE
Terminal does not close automatically when opened from netrw

### ISSUE THREAD

**Issue by xudongzheng** [vim/vim#14000]
### Steps to reproduce

1. Open a directory with netrw with `vim /etc`.
2. Open terminal with `:terminal`
3. Press `Ctrl-D` to exit terminal.
4. A blank buffer remains open.

If the same process is repeated with a file (ie `vim /etc/hosts`), this does not happen.

### Expected behaviour

Terminal closes like it does when `:terminal` is run with a file open.

### Version of Vim

9.1.83

### Environment

Debian 12, Vim built from source

**Comment by chrisbra** [comment]
That happens, because the netrw window sets 'nobuflisted' option, so Vim creates a new Window when closing the term. You can do `:set buflisted` and then it works as expected.

**Comment by xudongzheng** [comment]
Thank you for the suggestion. I ended up removing `nobl` from `g:netrw_bufsettings` to resolve the issue.
