### ISSUE TITLE
Reduce number of calls to STRLEN()

### ISSUE THREAD

**Issue by basilisk0315** [vim/vim#14002]
There are numerous of calls to STRLEN() throughout the tree and I think that a lot of them can be avoided. This is especially true when calling the ml_get*() functions because the buf_T struct has a member (ml_line_len) which contains the length of the line.

To demonstrate one way it could be done I have put together the following patches.

Any feedback would be welcomed. If this is something that people believe is worth pursuing I am happy to keep working on it.

Cheers
John

[normal.c.9.1.0089.patch](https://github.com/vim/vim/files/14226474/normal.c.9.1.0089.patch)
[memline.pro.9.1.0089.patch](https://github.com/vim/vim/files/14226475/memline.pro.9.1.0089.patch)
[memline.c.9.1.0089.patch](https://github.com/vim/vim/files/14226476/memline.c.9.1.0089.patch)

**Comment by chrisbra** [comment]
Thanks. I think this makes sense.

I had a quick look at the patch:
```diff
@@ -5192,15 +5242,15 @@
 		    {
 			char_u	*name;
 			int	dialog_result;
+			size_t  len = STRLEN(_("Swap file \""));
 
 			name = alloc(STRLEN(fname)
-				+ STRLEN(_("Swap file \""))
+				+ len
 				+ STRLEN(_("\" already exists!")) + 5);
 			if (name != NULL)
 			{
 			    STRCPY(name, _("Swap file \""));
-			    home_replace(NULL, fname, name + STRLEN(name),
-								  1000, TRUE);
+			    home_replace(NULL, fname, name + len, 1000, TRUE);
 			    STRCAT(name, _("\" already exists!"));
 			}
 			dialog_result = do_dialog(VIM_WARNING,
```

I think here it is wrong. `name + STRLEN(name)` is not the same as `name + len`. It's missing the `STRLEN(_("\" already exists!")) + 5` part.

**Comment by basilisk0315** [comment]
Here are some more patches.

[eval.c.9.1.0095.patch](https://github.com/vim/vim/files/14230466/eval.c.9.1.0095.patch)
[search.c.9.1.0095.patch](https://github.com/vim/vim/files/14230467/search.c.9.1.0095.patch)
[edit.c.9.1.0095.patch](https://github.com/vim/vim/files/14230489/edit.c.9.1.0095.patch)
[drawline.c.9.1.0095.patch](https://github.com/vim/vim/files/14230490/drawline.c.9.1.0095.patch)

**Comment by chrisbra** [comment]
can you make a PR for this please?

**Comment by chrisbra** [comment]
closing in favor of #14052
