### ISSUE TITLE
Commands typed in normal mode get printed on buffer

### ISSUE THREAD

**Issue by miguel-dev** [vim/vim#14001]
### Steps to reproduce

1. Open a file with some text, or create it.
2. Move all the way up with k.
4. See three consecutive ks.

I managed to improve this somewhat by including set belloff=all in .vimrc, however the letter under the cursor still gets overwritten by the command, but gets fixed when the cursor moves. Also, when disabling set showcmd it stops blinking randomly.

However, when scrolling all the way up with the mouse, a series of Ctrl commands start filling the screen.

### Expected behaviour

Commands typed in normal mode should not be written in the buffer like in insert mode.

### Version of Vim

9.1

### Environment

MacOS, Alacritty, alacritty.

**Comment by chrisbra** [comment]
What is your `$TERM`  setting?  Does it happen with `vim --clean` ? Have you tried other terminals?

**Comment by miguel-dev** [comment]
$TERM is alacritty, with vim --clean I can't reproduce the problem, not even scrolling up with the mouse showed garbled output. I tried the standard Mac terminal and saw the same problem.

**Comment by chrisbra** [comment]
Then please check your plugins and configuration files.

**Comment by miguel-dev** [comment]
I only have three plugins, two by tpope: repeat and surround. And the emmet plugin. I don't think that's the problem. My .vimrc is not that complicated neither, do you want me to copy it here?

**Comment by chrisbra** [comment]
```
function! GitBranch()
  return system("git rev-parse --abbrev-ref HEAD 2>/dev/null | tr -d '\n'")
endfunction

function! StatuslineGit()
  let l:branchname = GitBranch()
  return strlen(l:branchname) > 0?'  '.l:branchname.' ':''
endfunction
```

This seems to be your problem. This is expansive to shelling out each time the statusline is re-evaluated.

**Comment by miguel-dev** [comment]
I commented it and indeed it solves the issue. Any idea of how to improve that code so it works well?

**Comment by chrisbra** [comment]
Make use of caching. Please ask user questions using appropriate forums. Thanks.
