### ISSUE TITLE
Cannot allocate color none

### ISSUE THREAD

**Issue by dimaqq** [vim/vim#1400]
I'm running 8.0.172 (MacVim Snapshot 121)

A patch has been proposed in the forum:

http://www.linuxquestions.org/questions/slackware-14/vim-7-4-1938-e254-cannot-allocate-color-'none'-4175582317/

```
:version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 12 2017 03:04:35)
MacOS X (unix) version
Included patches: 1-172
Compiled by travis@Traviss-Mac-592.local
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +clientserver    +cursorbind      +ex_extra        +fullscreen      +langmap         +modify_fname    +mouse_urxvt     +path_extra      +reltime         +syntax          +timers          +viminfo         -xpm
+arabic          +clipboard       +cursorshape     +extra_search    -gettext         +libcall         +mouse           +mouse_xterm     +perl/dyn        +rightleft       +tag_binary      +title           +vreplace        -xsmp
+autocmd         +cmdline_compl   +dialog_con_gui  +farsi           -hangul_input    +linebreak       +mouseshape      +multi_byte      +persistent_undo +ruby/dyn        +tag_old_static  +toolbar         +wildignore      -xterm_clipboard
+balloon_eval    +cmdline_hist    +diff            +file_in_path    +iconv           +lispindent      +mouse_dec       +multi_lang      +postscript      +scrollbind      -tag_any_white   +transparency    +wildmenu        -xterm_save
+browse          +cmdline_info    +digraphs        +find_in_path    +insert_expand   +listcmds        -mouse_gpm       -mzscheme        +printer         +signs           -tcl             +user_commands   +windows
++builtin_terms  +comments        +dnd             +float           +job             +localmap        -mouse_jsbterm   +netbeans_intg   +profile         +smartindent     +termguicolors   +vertsplit       +writebackup
+byte_offset     +conceal         -ebcdic          +folding         +jumplist        +lua/dyn         +mouse_netterm   +num64           +python/dyn      +startuptime     +terminfo        +virtualedit     -X11
+channel         +cryptv          +emacs_tags      -footer          +keymap          +menu            +mouse_sgr       +odbeditor       +python3/dyn     +statusline      +termresponse    +visual          -xfontset
+cindent         +cscope          +eval            +fork()          +lambda          +mksession       -mouse_sysmouse  +packages        +quickfix        -sun_workshop    +textobjects     +visualextra     +xim
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib  -L. -fstack-protector -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib
-L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib   -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.16/darwin-thread-multi-2lev
el/CORE
```

**Comment by brammool** [comment]
Dima Tisnek wrote:

> I'm running 8.0.172 (MacVim Snapshot 121)
> 
> A patch has been proposed in the forum:
> 
> http://www.linuxquestions.org/questions/slackware-14/vim-7-4-1938-e254-cannot-allocate-color-'none'-4175582317/

I can't remember "none" ever working.  What patch would have changed
that?  The help clearly says "NONE".

-- 
Experience is what you get when you don't get what you want.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dimaqq** [comment]
The patch made "NONE" comparison case-insensitive...

I guess I should go through my settings, bundles, themes, syntax, etc., and find what uses wrong capitalisation.

**Comment by chrisbra** [comment]
I thought so too, but apparently:
```
chrisbra@256bit:~/code/vim$ grep NONE runtime/colors/* |wc -l
52
chrisbra@256bit:~/code/vim$ grep none runtime/colors/* |wc -l
31
```
However, I don't remember having seen the error message.

**Comment by dimaqq** [comment]
Turns out that "highlight.vim" plugin was the culprit.

It hasn't been updated in 5 years, so I just deleted it in my installation.
Perhaps it's time to mark it "bad/obsolete/whatever" on vim.org/scripts

**Comment by brammool** [comment]
Christian wrote:

> I thought so too, but apparently:
> ```
> chrisbra@256bit:~/code/vim$ grep NONE runtime/colors/* |wc -l
> 52
> chrisbra@256bit:~/code/vim$ grep none runtime/colors/* |wc -l
> 31
> ```
> However, I don't remember having seen the error message.

You can use "none" for gui and cterm.  Those are attributes, not colors.
I have a script to check for obvious errors in runtime files, it does
catch this one.

-- 
   An extraordinary TALL KNIGHT in all black (possibly John with Mike on his
   shoulders) walks out from the dark trees.  He is extremely fierce and
   gruesome countenance.  He walks towards KING ARTHUR and PATSY, who are
   wazzing like mad.  (Salopian slang, meaning very scared.  almost to the
   point of wetting oneself, e.g. before an important football match or
   prior to a postering.  Salopian slang meaning a beating by the school
   praeposters.  Sorry about the Salopian slant to this stage direction - Ed.)
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
ah okay. That is inconsistent however.

**Comment by anakimluke** [comment]
I think this issue should be reopened.

I tested on the latest commit from master and I get error 254 when trying to do `highlight Normal guifg=none`. Using `ctermfg` works as usual.

**Comment by brammool** [comment]
@anakimluke - what makes you think "none" would work?  It should be "NONE".

**Comment by anakimluke** [comment]
As @chrisbra mentioned, this is inconsistent behavior. Lowercase `none` works normally when using `cterm*=`. I was really confused when my highlight settings would "randomly" stop working. Many colorschemes also use the lowercase version, including ones shipped with vim.

**Comment by anakimluke** [comment]
If you think only uppercase NONE should be accepted, that's fine too. Then the bug would be that sometimes lowercase none is accepted; plus it'd break backgrounds compatibility with colorschemes.

**Comment by brammool** [comment]
> As @chrisbra mentioned, this is inconsistent behavior. Lowercase
> `none` works normally when using `cterm*=`.

The problem is actually that "none" should give an error here too.
But we can't change that without breaking things.

> I was really confused when
> my highlight settings would "randomly" stop working. Many colorschemes
> also use the lowercase version, including ones shipped with vim.

I cannot spot any one.  Where do you see it?

-- 
hundred-and-one symptoms of being an internet addict:
135. You cut classes or miss work so you can stay home and browse the web.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by anakimluke** [comment]
> I cannot spot any one.  Where do you see it?

Oh sorry, I misread it. It's only set to `cterm` and it's in an older version of vim.

> The problem is actually that "none" should give an error here too.
> But we can't change that without breaking things.

What are the potential problems of making it case-insensitive?

I did a manual search on the (roughly) top 16 colorschemes in a [site](https://vimcolorschemes.com). Only 2 of them used lowercase `none` bound to ctermfg/bg ([1](https://github.com/tomasr/molokai/blob/c67bdfcdb31415aa0ade7f8c003261700a885476/colors/molokai.vim#L206), [2](https://github.com/rakr/vim-one/blob/187f5c85b682c1933f8780d4d419c55d26a82e24/colors/one.vim#L364)) and 1 mentioned it in their documentation([3](https://github.com/nanotech/jellybeans.vim/blob/ef83bf4dc8b3eacffc97bf5c96ab2581b415c9fa/README.markdown?plain=1#L95))

**Comment by brammool** [comment]
> > The problem is actually that "none" should give an error here too.
> > But we can't change that without breaking things.
> 
> What are the potential problems of making it case-insensitive?

It is a special value, making it all-caps makes sure it's easy to
notice.  Using "none" doesn't stand out from "green" or other short
names.

> I did a manual search on the (roughly) top 16 colorschemes in a [site](https://vimcolorschemes.com). Only 2 of them used lowercase `none` bound to ctermfg/bg ([1](https://github.com/tomasr/molokai/blob/c67bdfcdb31415aa0ade7f8c003261700a885476/colors/molokai.vim#L206), [2](https://github.com/rakr/vim-one/blob/187f5c85b682c1933f8780d4d419c55d26a82e24/colors/one.vim#L364)) and 1 mentioned it in their documentation([3](https://github.com/nanotech/jellybeans.vim/blob/ef83bf4dc8b3eacffc97bf5c96ab2581b415c9fa/README.markdown?plain=1#L95))

Is this an indication that it would be OK to give an error for using
"none"?  It won't work, colorschemes have been written by lots of people
and then used by many others, who don't know what the commands mean.
They would just get an error with the next Vim version on startup and
then have to solve the puzzle of why that error shows up and how to fix
it...  Avoiding that is much more important than a small inconsistency.

-- 
hundred-and-one symptoms of being an internet addict:
140. You'd rather catch a score on the web than watch the game as
     it is being played on tv.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by anakimluke** [comment]
> Is this an indication that it would be OK to give an error for using
"none"?

I didn't mean to support one point or another; I meant to just through some rough stats in the conversation.

My reasoning is that the inconsistent behavior should be considered a bug. Then either mark it to be fixed with case-insensitiveness or as a won't fix.

In my opinion, the annoyance of encountering the behavior is more important than the capitalizing of the word to make it look different. Also, it's specially hard for beginners to fix the problem, since the error is not too descriptive and there is no abundant info on the internet.

I will also take the opportunity to thank you for your work in vim!! :) I love this piece of software :3

**Comment by Shane-XB-Qian** [comment]
hi normal guifg=NONE                       <-- ok
hi normal guifg=none                                   <-- E254
hi normal guifg=green                       <-- ok
hi normal ctermfg=green                  <-- ok
hi normal ctermfg=none                   <-- ok

**Comment by dimaqq** [comment]
Since I've started this issue ages ago, my vote would be to make all colors and lack of colors case-insensitive.

Or, if that's too much, use `none` everywhere.
