### ISSUE TITLE
vim fails to compile on RHEL 9 with clang: file format not recognized

### ISSUE THREAD

**Issue by zgtoth** [vim/vim#14012]
### Steps to reproduce

Here are the steps that I am using to build vim.  They worked recently on RHEL 7.9 and RHEL 8.4.  However on RHEL 9.2 `make -j8` fails with `objects/option.o: file not recognized: file format not recognized`.

```
sudo mkdir /opt/vim
sudo chown $USER /opt/vim
cd /opt/vim
wget https://github.com/vim/vim/archive/master.zip
unzip master.zip
rm master.zip
cd ./vim-master/src

CC=clang CXX=clang++ CFLAGS= LD=clang LDFLAGS=-rdynamic \
   ./configure --enable-cscope \
               --enable-fail-if-missing \
               --enable-perlinterp=yes \
               --enable-python3interp=yes \
               --enable-terminal \
               --with-python3-command=python3.8

make -j8 # This is the step that fails
sudo make install
```

### Expected behaviour

`make` completes successfully

### Version of Vim

9.1.285 (BCD=0x11d; DATE_ONLY="2024 Jan 02")

### Environment

```
Operating System: Red Hat Enterprise Linux 9.2 (Plow)
Terminal: XTerm(366) via PuTTY
$TERM: xterm
shell:  ksh
$KSH_VERSION:  Version AJM 93u+m/1.0.0-beta.1 2021-05-10
```

### Logs and stack traces

```shell
I believe that these are the most relevant portions of the output from `make`:


clang -c -I.  -D_REENTRANT -D_GNU_SOURCE -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches     -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fwrapv  -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -I/usr/lib64/perl5/CORE   -I/home/ztoth/.pyenv/versions/3.8.18/include/python3.8 -pthread -fPIE   -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MOTIF     -g -O2 -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1              -o objects/option.o option.c

...

  clang   -Wl,--enable-new-dtags -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1   -rdynamic -L/usr/local/lib       -o vim objects/alloc.o objects/arabic.o objects/arglist.o objects/autocmd.o objects/beval.o objects/buffer.o objects/change.o objects/blob.o objects/blowfish.o objects/cindent.o objects/clientserver.o objects/clipboard.o objects/cmdexpand.o objects/cmdhist.o objects/crypt.o objects/crypt_zip.o objects/debugger.o objects/dict.o objects/diff.o objects/digraph.o objects/drawline.o objects/drawscreen.o objects/edit.o objects/eval.o objects/evalbuffer.o objects/evalfunc.o objects/evalvars.o objects/evalwindow.o objects/ex_cmds.o objects/ex_cmds2.o objects/ex_docmd.o objects/ex_eval.o objects/ex_getln.o objects/fileio.o objects/filepath.o objects/findfile.o objects/float.o objects/fold.o objects/getchar.o objects/gui_xim.o objects/hardcopy.o objects/hashtab.o objects/help.o objects/highlight.o objects/if_cscope.o objects/if_xcmdsrv.o objects/indent.o objects/insexpand.o objects/list.o objects/locale.o objects/logfile.o objects/map.o objects/mark.o objects/match.o objects/mbyte.o objects/memline.o objects/menu.o objects/misc1.o objects/misc2.o objects/mouse.o objects/move.o objects/normal.o objects/ops.o objects/option.o objects/optionstr.o objects/os_unix.o objects/pathdef.o objects/popupmenu.o objects/popupwin.o objects/profiler.o objects/pty.o objects/quickfix.o objects/regexp.o objects/register.o objects/screen.o objects/scriptfile.o objects/search.o objects/session.o objects/sha256.o objects/sign.o objects/sound.o objects/spell.o objects/spellfile.o objects/spellsuggest.o objects/strings.o objects/syntax.o objects/tag.o objects/term.o objects/terminal.o objects/testing.o objects/textformat.o objects/textobject.o objects/textprop.o objects/time.o objects/typval.o objects/ui.o objects/undo.o objects/usercmd.o objects/userfunc.o objects/version.o objects/vim9class.o objects/vim9cmds.o objects/vim9compile.o objects/vim9execute.o objects/vim9expr.o objects/vim9instr.o objects/vim9script.o objects/vim9type.o objects/viminfo.o objects/window.o objects/bufwrite.o objects/gui.o objects/gui_motif.o objects/gui_x11.o objects/gui_beval.o objects/gui_xmdlg.o objects/gui_xmebw.o objects/vterm_encoding.o objects/vterm_keyboard.o objects/vterm_mouse.o objects/vterm_parser.o objects/vterm_pen.o objects/vterm_screen.o objects/vterm_state.o objects/vterm_unicode.o objects/vterm_vterm.o   objects/if_perl.o objects/if_perlsfio.o  objects/if_python3.o    objects/netbeans.o objects/job.o objects/channel.o objects/xdiffi.o objects/xemit.o objects/xprepare.o objects/xutils.o objects/xhistogram.o objects/xpatience.o  objects/charset.o objects/json.o objects/main.o objects/memfile.o objects/message.o  -lXp -lXmu -lXext -lXm -lXt -lSM -lICE -lXt -lX11 -lSM -lICE -ldl  -lm -ltinfo -lelf  -lselinux    -Wl,--enable-new-dtags -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib64/perl5/CORE -lperl -lpthread -lresolv -ldl -lm -lcrypt -lutil -lc  -L/home/ztoth/.pyenv/versions/3.8.18/lib/python3.8/config-3.8-x86_64-linux-gnu -lpython3.8 -lcrypt -ldl -L/home/ztoth/.pyenv/versions/3.8.18/lib -Wl,-rpath,/home/ztoth/.pyenv/versions/3.8.18/lib -lm -lm

clang-16: warning: argument unused during compilation: '-specs=/usr/lib/rpm/redhat/redhat-hardened-ld' [-Wunused-command-line-argument]
clang-16: warning: argument unused during compilation: '-specs=/usr/lib/rpm/redhat/redhat-annobin-cc1' [-Wunused-command-line-argument]
clang-16: warning: argument unused during compilation: '-specs=/usr/lib/rpm/redhat/redhat-hardened-ld' [-Wunused-command-line-argument]
clang-16: warning: argument unused during compilation: '-specs=/usr/lib/rpm/redhat/redhat-annobin-cc1' [-Wunused-command-line-argument]
clang-16: warning: argument unused during compilation: '-specs=/usr/lib/rpm/redhat/redhat-hardened-ld' [-Wunused-command-line-argument]
clang-16: warning: argument unused during compilation: '-specs=/usr/lib/rpm/redhat/redhat-annobin-cc1' [-Wunused-command-line-argument]
objects/option.o: file not recognized: file format not recognized

clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
link.sh: Linking failed
make: *** [Makefile:2058: vim] Error 1
```
```

**Comment by chrisbra** [comment]
that error is strange. Have you tried running `make clean && make` and see if this reproduces? I am also wondering about those warnings. Where does the `-specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -specs=/usr/lib/rpm/redhat/redhat-hardened-ld` come from?

**Comment by zgtoth** [comment]
Thanks for taking a look.

> that error is strange. Have you tried running `make clean && make` and see if this reproduces?

I have tried it now, and yes it reproduces.

> I am also wondering about those warnings. Where does the `-specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -specs=/usr/lib/rpm/redhat/redhat-hardened-ld` come from?

I'm not sure.  The `CFLAGS` and `LDFLAGS` I used are shown in the `configure` command.  When I call `make -j8`, my `CFLAGS` and `LDFLAGS` environment variables are unset.  I checked `env | grep redhat` and I don't see any references to it in any environment variable.

The first reference to them comes early in the output of `make -j8`:

```
/bin/sh install-sh -c -d objects
CC="clang -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MOTIF       " srcdir=. sh ./osdef.sh
creating auto/pathdef.c
/usr/bin/perl -e 'unless ( $] >= 5.005 ) { for (qw(na defgv errgv)) { print "#define PL_$_ $_\n" }}' > auto/if_perl.c
cd xxd; CC="clang" CFLAGS=" -O2   -Wall -Wno-deprecated-declarations -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1" LDFLAGS="-Wl,--enable-new-dtags -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1   -rdynamic -L/usr/local/lib" \
        make -f Makefile
```

**Comment by chrisbra** [comment]
Can you please share the complete log? Another question: Does this only happen with clang? Have you tried gcc? Or a different clang?

**Comment by zgtoth** [comment]
> Can you please share the complete log?

I assume by the log you mean the standard output and standard error from the configure and make commands.  I've attached them to this comment.

[configure.out.txt](https://github.com/vim/vim/files/14248510/configure.out.txt)
[make.out.txt](https://github.com/vim/vim/files/14248511/make.out.txt)

**Comment by zgtoth** [comment]
> Does this only happen with clang? Have you tried gcc? Or a different clang?

Using `gcc`, the `configure` command fails with errors that I am not sure how to easily resolve.  And I don't know how to install a different version of `clang` on RHEL.  I apologize for my ineptitude.

**Comment by chrisbra** [comment]
I see this behaviour, when using `-lto` together with `clang-17`. So please try to disable `link-time-optimization`. Not sure where this comes from, but it should be possible to set `CFLAGS` with some sane defaults (or set them directly in the Makefile).
Also it may be a good idea to compile sequentially (no `-j` ) when seeing such strange errors, just in case some dependency is slightly wrong.

**Comment by zgtoth** [comment]
I wasn't sure how to disable `link-time-optimization`, as I wasn't setting them in the first place.  I don't see a `-flto=no` option. 
 Passing `CFLAGS=-emit-llvm` to `configure` results in `configure` failing with:

```
checking for gcc... clang
checking whether the C compiler works... no
configure: error: in `/opt/vim/vim-master/src':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

Where `config.log` shows:

```
configure:3454: checking whether the C compiler works
configure:3476: clang -emit-llvm  -rdynamic conftest.c  >&5
clang-16: error: -emit-llvm cannot be used when linking
```

I then tried passing `CFLAGS="-O2 -Wall -Wno-deprecated-declarations -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1"` to `configure` and I'm back to seeing `-flto=auto` getting set.

The next thing I tried finally worked.

**Comment by zgtoth** [comment]
Here is what worked around the problem for me:

I tried just running `configure`, then checking which files have `flto` in them, in the hope of replacing them.  I found these:

```
/opt/vim/vim-master/src/auto/config.log
/opt/vim/vim-master/src/auto/config.mk
/opt/vim/vim-master/src/auto/config.status
```

`config.mk` had a line:

```
PERL_CFLAGS     =  -D_REENTRANT -D_GNU_SOURCE -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches     -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fwrapv  -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -I/usr/lib64/perl5/CORE
```

I removed `-flto=auto` and then run `make -j8` and `sudo make install`.  This did the trick.

Thanks for your help @chrisbra .  It is much appreciated.

**Comment by chrisbra** [comment]
Thanks, I guess this comes from:
```
perl -Mlib=$srcdir -MExtUtils::Embed -e 'ccflags;perl_inc;print"\n"'
```

Not sure if we should filter out `-flto=auto` or not

**Comment by errael** [comment]
> I wasn't sure how to disable `link-time-optimization`, as I wasn't setting them in the first place

@chrisbra I only glanced at the change, thought it looked to affects only perl. I ask because I played around with link time optimization and saw on average around 10% performance improvement in some micro-benchmarking: https://github.com/vim/vim/discussions/13565#discussioncomment-7663365

**Comment by chrisbra** [comment]
Ah yes I remember. However the problem here seems to be, that because of enabling the Perl Interface the PERL_CFLAGS which includes the `-lto` argument, leaks into compilation for the option.c and optionstr.c files. Which then apparently are no longer detected as valid object files when linking it to the Vim binary. So apparently you cannot have part of the object files compiled with `-lto` and other parts without it, so I filter it now out in the configure script (which is what patch 2f9aef4 above does).

On a related note, I tested the `-lto` when compiling, but I have an old development laptop. The linking step takes forever then, so I found it more annoying than actually helpful.

**Comment by errael** [comment]
> On a related note, I tested the `-lto` when compiling, but I have an old development laptop. The linking step takes forever then, so I found it more annoying than actually helpful.

The first time I tried it, "forever" is a good description. I just looked at the referenced comment, and in the notes there's

> Using `-flto=auto` makes a huge difference in link time.
> Did not use `-fwhole-program` or a linker plugin (AFAICT).

Excerpt from the gcc docs https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html

```
Use -flto=auto to use GNU make’s job server, if available, or otherwise fall back 
to autodetection of the number of CPU threads present in your system. 
```

There's a lengthy section about `-flto[=n]`.

Never tried clang.

There's an interesting comment in the gcc docs
```
If LTO encounters objects with C linkage declared with incompatible types in 
separate translation units to be linked together (undefined behavior according 
to ISO C99 6.2.7), a non-fatal diagnostic may be issued.
```
No idea if this has anything to do with this issue and/or how clang may handle these things.

**Comment by chrisbra** [comment]
>  (undefined behavior according to ISO C99 6.2.7), a non-fatal diagnostic may be issued.

That is funny, it shall be non-fatal, even so it is undefined behaviour 🤷

**Comment by errael** [comment]
> > (undefined behavior according to ISO C99 6.2.7), a non-fatal diagnostic may be issued.
> 
> That is funny, it shall be non-fatal, even so it is undefined behaviour 🤷

Yep. Guessing that gcc decided to define it, maybe clang doesn't?

**Comment by eli-schwartz** [comment]
> So apparently you cannot have part of the object files compiled with `-lto` and other parts without it, so I filter it now out in the configure script (which is what patch [2f9aef4](https://github.com/vim/vim/commit/2f9aef42af94f6d68f37f6e9b8cb878e88ed12bf) above does).

If you compile even some objects with LTO compiler flags, it is advisable to link with the same flags as well. Normally, that's the job of people injecting -flto into their $CFLAGS and $LDFLAGS environment variables before running configure. Perl is leaky -- its Extutils will print various junk based on what perl was configured with rather than just printing what you want, which is the required interface flags for compiling against the perl headers and linking to the perl library.

Compilers *may* choose to detect that an object was built with LTO, and activate linking with LTO even when you didn't tell it to.

> Yep. Guessing that gcc decided to define it, maybe clang doesn't?

Absolutely not, GCC has not *defined* anything.

The C programming language doesn't require you to warn or error when Undefined Behavior exists, but compilers may choose to do so in order to be helpful. That is not *defining* the behavior to do a specific thing, that is telling you that the *trigger condition* exists for your code to behave in unpredictable ways.

Incompatible types is a trigger condition. It is "illegal code". You can detect illegal code. The undefined behavior is what machine code it results in -- GCC makes *zero* definition about what (incorrect) machine code will be produced.
