### ISSUE TITLE
highlight CursorLine and CursorColumn

### ISSUE THREAD

**Issue by We-unite** [vim/vim#14027]
### Steps to reproduce

- Compile vim as follows:
```bash
python_version=$(python3 -V 2>&1 | awk '{print $2}' | awk -F '.' '{print $1"."$2}')
./configure \
    --with-features=huge \
    --enable-multibyte \
    --enable-rubyinterp=dynamic \
    --with-ruby-command=/usr/bin/ruby \
    --enable-luainterp\
    --enable-python3interp=dynamic \
    --with-python3-command=$(which python$python_version) \
    --with-python3-config-dir=$(python$python_version-config --configdir) \
    --enable-perlinterp=dynamic \
    --enable-largefile \
    --enable-cscope \
    --with-compiledby="An Ordinary People" \
    --enable-fail-if-missing \
    --disable-gui \
    --prefix=/usr
make
sudo make install
```
- Set in system vimrc file:
```vimscript
syntax on
set cul
set cuc
colorscheme industry                      " set color scheme
set list                                              " show tab and space
set listchars=tab:>-,trail:-	                " set ways to show tab and space
hi CursorLine cterm=NONE ctermbg=darkblue ctermfg=NONE guibg=darkblue guifg=NONE
hi CursorColumn cterm=NONE ctermbg=darkblue ctermfg=NONE guibg=darkblue guifg=NONE
```
- Start vim, then **it's expected to show cursor line and column as dark blue**, but it **actually shows gray**
![1](https://github.com/vim/vim/assets/107343968/481a95b0-2f17-442c-9b8c-e79ffa217436)
- Then **source the system vimrc again manually**, it turns to blue, which I want to show
![2](https://github.com/vim/vim/assets/107343968/b4682d19-a7c6-4db2-9939-4406d97cccb8)

### Expected behaviour

After set color scheme and cursor line/colomn in order in system vimrc file, **it should behave as set by highlight cursor line/column when starting vim, rather than sourcing vimrc manually.**

### Version of Vim

VIM - Vi IMproved 9.1 Included patches: 1-104 Huge version without GUI

### Environment

- VMWare + Ubuntu 22.04 LTS

**Comment by chrisbra** [comment]
I find those transparent windows hard to read. In any case, can you please show the output of `:verbose hi CursorLine` once it shows the wrong color?

**Comment by We-unite** [comment]
> I find those transparent windows hard to read. In any case, can you please show the output of `:verbose hi CursorLine` once it shows the wrong color?

The output of `:verbose hi CursoeLine` is as follows:
```plaintext
:verbose hi CursorLine
CursorLine     xxx term=underline ctermbg=242 guibg=#6c6c6c
        Last set from /usr/share/vim/vim91/colors/industry.vim line 115
```
![Steam-2024-02-14-00-33-28](https://github.com/vim/vim/assets/107343968/55370873-ecaa-4571-b888-6cd1ffd63505)

and the context in `industry.vim`:
```vimscript
if s:t_Co >= 256
  " some other color set here...
  hi CursorLine ctermfg=NONE ctermbg=242 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=242 cterm=NONE
  hi CursorLineNr ctermfg=226 ctermbg=NONE cterm=bold
  hi ColorColumn ctermfg=NONE ctermbg=238 cterm=NONE
  " some other color set here...
  hi! link Terminal Normal
  hi! link LineNrAbove LineNr
  hi! link LineNrBelow LineNr
  hi! link CurSearch Search
  hi! link CursorLineFold CursorLine
  hi! link CursorLineSign CursorLine
  hi! link MessageWindow Pmenu
  hi! link PopupNotification Todo
  hi DiffAdd ctermfg=231 ctermbg=65 cterm=NONE
  hi DiffChange ctermfg=231 ctermbg=67 cterm=NONE
  hi DiffText ctermfg=16 ctermbg=251 cterm=NONE
  hi DiffDelete ctermfg=231 ctermbg=133 cterm=NONE
  unlet s:t_Co
  finish
endif
```
If cursor line is set in `industry.vim`, why it changes after `:source $VIM/vimrc`?

**Comment by chrisbra** [comment]
Not sure, potentially Vim delays this until is has fully started up. You may want to wrap those settings into a `VimEnter` autocommand

**Comment by We-unite** [comment]
> Not sure, potentially Vim delays this until is has fully started up. You may want to wrap those settings into a `VimEnter` autocommand

Sorry, I don't get what you mean.

When vim is started, it would read from vimrc, then encounters the color scheme and my highlight set, **theoretically it would load in order**(my settings override the color scheme settings), but **vim may dalays the color scheme until fully started**(color settings override my settings), right? And then when `:cource $VIM/vimrc`, vim gets that the same color scheme has been used, it wouldn't load color scheme again, just set highlight?

**Comment by chrisbra** [comment]
No,
I basically mean this:
```
syntax on
set cul
set cuc
colorscheme industry
set list
set listchars=tab:>-,trail:-
augroup VimStartup
au!
au VimEnter * hi CursorLine cterm=NONE ctermbg=darkblue ctermfg=NONE guibg=darkblue guifg=NONE | hi CursorColumn cterm=NONE ctermbg=darkblue ctermfg=NONE guibg=darkblue guifg=NONE
augroup END
```

Actually, it might be even better to set those highlighting groups in an ColorScheme autocommand instead. 

In any case, this is a usage question. Please use vi.stackexchange.com or use the vim-use mailinglist for usage questions. Considering the amount of issues here, we cannot provide individual support here.

**Comment by We-unite** [comment]
I've understand your solution and tried, it really works. Thanks very much. Close the issue please.

**Comment by We-unite** [comment]
Thanks a lot. So sorry to burther and ask on usage in issues...
