### ISSUE TITLE
Vim beeps when opening a file using the CtrlP plugin

### ISSUE THREAD

**Issue by sfsam** [vim/vim#14047]
### Steps to reproduce

1. Open Vim.
2. Use CtrlP to open a file.

### Expected behaviour

Vim beeps when opening the file. It should open the file without the beep. I checked `:messages` but saw nothing there.

I think the commit that triggers this behavior is bf44b69d1f91d9778ae1887128c63d35d9a3d19b. I used `git bisect`, but I've never built Vim before nor used `bisect` before so I might be mistaken.

### Version of Vim

9.1.76

### Environment

macOS 14.3.1

**Comment by seandewar** [comment]
> I think the commit that triggers this behavior is https://github.com/vim/vim/commit/bf44b69d1f91d9778ae1887128c63d35d9a3d19b.

If that's indeed the commit, it _may_ not indicate a bug in Vim; `:wincmd p` beeping when there's no previous window is normal.

However, before that commit, there was a case (seemingly the only such possible) where both the current and previous windows could refer to the same window if closing a different window resulted in Vim choosing the previous as the new current window. That may have resulted in `:wincmd p` not beeping previously, but still having no effect.

**Comment by sfsam** [comment]
Thanks for the reply. I've been using CtrlP to open files like this for a while and this is the first time I've ever experienced this beeping behavior. CtrlP opens a window at the bottom of the screen from which you can select or fuzzy-find a file to open. When you select your file, it opens and the CtrlP window at the bottom closes. Any idea how to proceed? Is this a Vim issue or a CtrlP issue? Of course, I can still use CtrlP, but I'd much prefer it not beep every single time I open a file.

**Comment by seandewar** [comment]
> Any idea how to proceed? Is this a Vim issue or a CtrlP issue?

If things are happening as I assume, I'd consider the old behaviour a bug (and the lack of beeping prior to the patch). Plugins using `:wincmd p` should consider using `:silent!` or check `winnr('#') != 0` if they don't want potential beeps. Though if the patch causes too much fallout in plugins, maybe reverting it and documenting the old behaviour could be preferable.

I don't use CtrlP, so can't provide specific help, but from looking at the source, maybe [this line](https://github.com/ctrlpvim/ctrlp.vim/blob/7c972cb19c8544c681ca345c64ec39e04f4651cc/autoload/ctrlp.vim#L1064) is responsible for the beeping? You can try adding `sil!` to the start of that line in your local copy of the file and see if the beeping goes away (other uses of `winc p` in the file are already protected by `sil!`).

**Comment by sfsam** [comment]
Indeed, I have made the change to my local copy of CtrlP and the beep doesn't happen. Thank you.

**Comment by seandewar** [comment]
After considering the issue more, my opinion changed, and I decided reverting v9.1.0001 was best, which Chris accepted; instead the possibility of `winnr() == winnr('#')` has been documented.

Therefore this issue should no longer affect CtrlP after v9.1.0170.  Apologies for the inconvenience!

My decision mostly boils down to more cases of `curwin == prevwin` being possible than I originally thought, and some cases of it even being accounted for by scripts in the wild; but if you're interested in the specific details, [see here](https://github.com/vim/vim/commit/d64801e913314d2e19dbb38f60e6d285238debff).

**Comment by sfsam** [comment]
Thank you for investigating further even after the patch you provided me for CtrlP solved my problem.
