### ISSUE TITLE
Please add hotkeys list to title page

### ISSUE THREAD

**Issue by tyler-suard-parker** [vim/vim#14058]
It would go a long way to making vim more user-friendly if the commands were on the front page.  For example, right now when vim opens it shows how to quit, but it would be nice to include the following:

i: Insert mode
A: Append mode
esc: Exit a mode
: :command mode
:w : save changes to file

Etc.

**Comment by tyler-suard-parker** [comment]
Related: PR #14059

**Comment by chrisbra** [comment]
I am not sure. Keep in mind, the intro screen is not meant as a tutorial for users, but merely should show them where to find **help** (and in case you were thrown into it and have no idea what this black thing is, how to exit it). Adding more lines to it, will probably make it harder to find the right line, and we must ensure it fits into a default terminal size of `80x20` without looking too crowded.

**Comment by tyler-suard-parker** [comment]
@chrisbra @zzzyxwvut I understand, I used Nano for years, despite Vim being the vastly superior editor, because Nano has the hotkeys right there on the screen, which makes it way easier to use.  I know we can't do that with Vim, but just having some of the essential commands right there on the main screen would go a long way to making Vim more user-friendly for beginners and more popular.  Also, it is not clear that on-line help will show what the keystrokes are, or how to use Vim.  When I read on-line help, I think of talking to a tech support representative, who might tell me that Vim is working but would not tell me how to use it.

**Comment by tyler-suard-parker** [comment]
@chrisbra @zzzyxwvut another alternative would be to display a link to a youtube video tutorial on how to use Vim.

**Comment by vim-ml** [comment]
On 2024-02-20, tyler-suard-parker wrote:
> @chrisbra @zzzyxwvut I understand, I used Nano for years, despite Vim being the
> vastly superior editor, because Nano has the hotkeys right there on the screen,
> which makes it way easier to use. I know we can't do that with Vim, but just
> having some of the essential commands right there on the main screen would go a
> long way to making Vim more user-friendly for beginners and more popular. Also,
> it is not clear that on-line help will show what the keystrokes are, or how to
> use Vim. When I read on-line help, I think of talking to a tech support
> representative, who might tell me that Vim is working but would not tell me how
> to use it.

Except that that intro screen is there only until the user makes
some change to the buffer, then it's gone.  At that point, the user
is not going to remember a long list of commands, but they may
remember a very short list telling them how to exit and how to find
help.  I think that showing them more information than is already
there would actually be _less_ helpful.

Vim's built-in help _does_ show what the important keystrokes are as
well as directing the user to more topics.  It is probably the best
help system you will find in any editor.  In fact, if a new user
learns only one thing from the intro screen, it should be to type
":help".  That will show them how to quit.

If you think that there should be an easier way for the user to find
the list of commands you suggested, putting them in an easy-to-
discover place under :help would be better than on the intro screen.

Regards,
Gary

**Comment by Tylersuard** [comment]
@vim-ml Thanks for the feedback. Totally get the concern about clutter. How about we add just one line to the intro: "Hit :help basics for key commands"? Keeps it clean and nudges newbies gently towards the goldmine of info in :help.

Nano's got its shortcuts upfront, and it's a hit for ease of use. We're not Nano, but that one line could make Vim feel a bit more welcoming without sacrificing our minimalist vibe. Plus, it directly addresses the "how do I even start?" question in a super succinct way.

Thoughts?

**Comment by chrisbra** [comment]
the `type  :help<Enter>  or  <F1>  for on-line help` is not enough? 

Also, I am pretty sure, one could create a plugin for nano like help banner using popup windows or similar. But that probably belongs to its own plugin.

**Comment by chrisbra** [comment]
let's not do it then.
