### ISSUE TITLE
echo expand('%') shows !/bin/zsh after :term 

### ISSUE THREAD

**Issue by Konfekt** [vim/vim#14069]
### Steps to reproduce

1. run `vim --clean` in zsh
2. type`:term<cr>`
3. type `<c-w>:echo expand('%')<cr>`
4. output is `!/bin/zsh`

### Expected behaviour

According to `:help expand()` 

```
		When using '%' or '#', and the current or alternate file name
		is not defined, an empty string is used.  Using "%:p" in a
		buffer with no name, results in the current directory, with a
		'/' added.
```

so rather an empty string or current work dir is expected.

### Version of Vim

Vim 9.0.2013

### Environment

Opensuse 15.5 under ZSH 5.6

**Comment by chrisbra** [comment]
that is correct however. Internally the terminal is a buffer with a name starting with `!` +  `shell name`

**Comment by Konfekt** [comment]
Okay, reading

```
When using '%' or '#', and the current or alternate file name
		is not defined, an empty string is used
```

I suspected that the buffer does not have a current file name. Maybe clarify in the Vim doc what a file name is.

**Comment by chrisbra** [comment]
it seems it is documented here: https://github.com/vim/vim/blob/3f905ab3c4f66562f4a224bf00f49d98a0b0da91/runtime/doc/terminal.txt#L211-L215 I'll add a reference to it

**Comment by chrisbra** [comment]
A buffer is a view into a file typically. So a buffer name is typically also the file name. So that is correct.
