### ISSUE TITLE
When pasting to :ex or / <PasteStart> and <PasteEnd> is pasted, literally

### ISSUE THREAD

**Issue by mianos** [vim/vim#1407]
This commit:
https://github.com/vim/vim/commit/ec2da36ca48b40c0654b32a8d2c9f52e796daa5e
Breaks normal terminal paste in OSX in iterm and iterm2 in :ex or / or ?

**Comment by dkarter** [comment]
I believe this is related to: https://github.com/vim/vim/issues/1404 see my workaround there.

**Comment by mianos** [comment]
No. This is different. The commit is creating and interpreting `` <pastestart>.``

**Comment by chrisbra** [comment]
duplicate

**Comment by mianos** [comment]
OK, I see :set t_BE= also fixes this. OK

**Comment by mgedmin** [comment]
@chrisbra duplicate of which issue?  #1404 is different (although both bugs are in the new bracketed paste support code).

**Comment by mgedmin** [comment]
Anyway this should be fixed by patch 8.0.0228.

**Comment by chrisbra** [comment]
has been reported on the mailinglist

**Comment by kyleterry** [comment]
@chrisbra then can you give us a reference to the issue?

**Comment by chrisbra** [comment]
the issue has been fixed. search vim_dev mailinglist for PasteStart. There have been many discussions about that, you should find it easily.
