### ISSUE TITLE
The cursor is not at the right position on some situations.

### ISSUE THREAD

**Issue by anliting** [vim/vim#1408]
One of the ways to reproduce the problem:

0. Open a terminal emulator with the width of 80 and the height of 24.
1. Open vim with "vim -N -u NONE"
2. Insert a line with 2 English letters.
3. Repeat this for at least 24 times: Append 77 English letters and one Chinese character to the line.
4. Append some text to the line in Insert mode, and you will see the cursor is not at the right position.

![screenshot_20170124_143533](https://cloud.githubusercontent.com/assets/7554825/22236726/789a8f5a-e242-11e6-8c53-836fde61f23a.png)
![screenshot_20170124_143550](https://cloud.githubusercontent.com/assets/7554825/22236735/815dd3b8-e242-11e6-924a-36e32d1ca9bb.png)

Vim version: 8.0.170

Here are some Chinese characters if you need it: 中文是個麻煩的語言

**Comment by chrisbra** [comment]
I can confirm.

**Comment by chrisbra** [comment]
I think this patch fixes it:
```patch
diff --git a/src/screen.c b/src/screen.c
index e37bf4838..b11aab303 100644
--- a/src/screen.c
+++ b/src/screen.c
@@ -2916,7 +2916,7 @@ win_line(
     int                endrow,
     int                nochange UNUSED)        /* not updating for changed text */
 {
-    int                col;                    /* visual column on screen */
+    int                col = 0;                /* visual column on screen */
     unsigned   off;                    /* offset in ScreenLines/ScreenAttrs */
     int                c = 0;                  /* init for GCC */
     long       vcol = 0;               /* virtual column (for tabs) */
@@ -3442,7 +3442,11 @@ win_line(
 #else
            --ptr;
 #endif
-           n_skip = v - vcol;
+#ifdef FEAT_MBYTE
+           /* character fits on the screen, don't need to skip it */
+           if ((*mb_ptr2cells)(ptr) >= c && col == 0)
+#endif
+               n_skip = v - vcol;
        }

        /*
```

**Comment by anliting** [comment]
Thank you for your great work! Vim is the best text editor I've ever used.
