### ISSUE TITLE
`$VIMRUNTIME` is changed if `:set helpfile` is done

### ISSUE THREAD

**Issue by brianjmurrell** [vim/vim#14110]
### Steps to reproduce

1. `vim --clean`
2. `:echo $VIMRUNTIME`
3. Observe it's value, in my case it was `/usr/share/vim/vim91`
4. `:set helpfile=$VIM/doc/help.txt`
5. `:echo $VIMRUNTIME`
6. Observe it's value, in my case it was `/usr/share/vim`

### Expected behaviour

`:set helpfile` should not alter the value of `$VIMRUNTIME`

### Version of Vim

9.1.113

### Environment

OS: Fedora 39
Terminal: GNOME Terminal3.50.1
TERM: xterm-256color
Shell: bash 5.2.26

**Comment by chrisbra** [comment]
This is explained at [:h $VIM](https://vimhelp.org/starting.txt.html#%24VIM):

Vim basically uses the 'helpfile' option to determine the `$VIM` and then the `$VIMRUNTIME` variables. So this is working as expected.
