### ISSUE TITLE
vimindent variable is not defined

### ISSUE THREAD

**Issue by physixcat** [vim/vim#14111]
### Steps to reproduce

1. `vim --clean test.vim`
2. `:set indentexpr?`
this returns `vimindent.Expr()`
3. `:echo vimindent.Expr()`
this returns `E121: Undefined variable: vimindent`

### Expected behaviour

`vimindent` should be defined

This can be temporarily sidestepped by using the old(?) function
`:set indentexpr=GetVimIndent()`
once inside the session. Trying to do it with an autocommand Filetype or modeline will not work, because then `GetVimIndent` won't be defined.

### Version of Vim

9.1.16

### Environment

OS: Debian Sid
terminal: st
$TERM: tmux-256color
shell: 5.2.21

**Comment by chrisbra** [comment]
This is vim9 script. That is currenntly only valid when evaluating from within vim9 script context. I think it was discussed before, that one cannot easily call exported vim9 functions.

**Comment by physixcat** [comment]
I see. Thank you for clarifying. Problem seems to be that when older plugins check indentexpr for a vim filetype, they will run into the same undefined var issue.

Example: https://github.com/Thyrum/vim-stabs

If you load this plugin, edit a *.vim file, and toggle on autoindent, you get the same error

So the function is being called outside of the vim9 script context all the time

**Comment by monkoose** [comment]
To prevent described error, I guess instead of https://github.com/vim/vim/blob/13a014452a7a020a119ac555a690c65b41f3126d/runtime/indent/vim.vim#L17-L19

`setlocal indentexpr=dist#vimindent#Expr()` should be used.

**Comment by chrisbra** [comment]
Fixed by cb7928812e0dffac2750c9b0513915e17dfa116f
