### ISSUE TITLE
Sometimes, I need to type <c-n>/<c-p> twice to select a menu entry

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#1411]
Under some circumstances, I need to type `<c-n>` or `<c-p>` twice to have a menu entry selected. That happens when I first try keyword completion without obtaining any result, and then I call my own completion function with `<c-r>=MyComplete()`.

More specifically, you may reproduce the problem by running `vim -u NONE -N`, then setting:

```vim
set completeopt+=noselect
```

then sourcing this function:

```vim
fun! MyComplete()
  call complete(1, ['Hello', 'World'])
  return ''
endf
```

and finally entering Insert mode and typing: `abc<c-n><c-r>MyComplete()<cr><c-n><c-n>`. This is what I see:

1. `abc<c-n>` correctly results in `Pattern not found`;
2. `<c-r>MyComplete()<cr>` correctly opens a menu with two entries, none of which is selected;
3. `<c-n>` does nothing;
4.  a second `<c-n>` selects the first entry.

You may also notice that, if you continue moving around with `<c-n>/<c-p>`,  every time you return to the originally typed text you need to type the key twice to select an entry again. This is true independent of the presence of `noinsert` or `noselect` in `completeopt`.

**Comment by Shougo** [comment]
Same issue with this.

https://github.com/vim/vim/issues/1316#issuecomment-266295465
https://github.com/vim/vim/issues/1316#issuecomment-266303030

`completeopt` is `menu,preview,noselect`.
So the first candidate is not displayed.

**Comment by lifepillar** [comment]
That doesn't look like it's the same issue to me. As I have said, sometimes it is necessary to press `<c-n>` or `<c-p>` twice no matter what the settings of 'completeopt' are. If you repeat the steps above without setting `completeopt` (so its value is `menu,preview`), you still have the problem if you type `abc<c-n><c-r>MyComplete()<cr><c-p><c-p>` (now, I realize that I could have explained the problem more simply…).

This issue is specifically about invoking a custom completion immediately after keyword completion has failed.

**Comment by chrisbra** [comment]
I am confused. Are you talking about `<c-r>=MyComplete()`  Else it does not seem to make much sense. What are you seeing with default `:set completeopt` and when do you see that <c-n> does not work?

**Comment by lifepillar** [comment]
Ok, I'll try again: run `vim -N -u NONE` (leave `completeopt` to its default) and source this function (or any similar function that sets the matches for Insert mode completion):

```vim
fun! MyComplete()
  call complete(1, ['Hello', 'World'])
  return ''
endf
```

Enter Insert mode and type `xxx<c-n>`, which makes keyword completion fail with `Pattern not found`. Immediately after that, type `<c-r>=MyComplete()<cr><c-p>` (that's ctrl-r = MyComplete() enter ctrl-p). The pop-up menu appears as expected, but `<c-p>` does not select the last entry as I would expect. I have to press `<c-p>` once more to have it selected. Now,  with the last entry selected, press `<c-n>` to return to the original text, then press `<c-n>` again: I would expect the first entry to be selected, but that does not happen. I have to press `<c-n>` once more to have the first entry selected.

Edit: fixed some typos

**Comment by chrisbra** [comment]
Okay, that's what I thought. This happens, because after the keyword completion the list of candidates is not cleared and when `ins_compl_add` is called from `set_completion` it adds as first item the original text again. So we have those candidates: xxx->xxx->Hello->World.

There is a test add `ins_compl_add` to prevent adding duplicates, however, it does not work in this case, because match->cp_flags has ORIGINAL_TEXT flag already set, so it adds the original text again. I think, that condition can safely be removed, something like this patch should do it:
```patch
diff --git a/src/edit.c b/src/edit.c
index 2e1aa2bea..60ee8badf 100644
--- a/src/edit.c
+++ b/src/edit.c
@@ -2561,8 +2561,7 @@ ins_compl_add(
        match = compl_first_match;
        do
        {
-           if (    !(match->cp_flags & ORIGINAL_TEXT)
-                   && STRNCMP(match->cp_str, str, len) == 0
+           if (STRNCMP(match->cp_str, str, len) == 0
                    && match->cp_str[len] == NUL)
                return NOTDONE;
            match = match->cp_next;
@@ -2829,10 +2828,11 @@ set_completion(colnr_T startcol, list_T *list)
     compl_length = (int)curwin->w_cursor.col - (int)startcol;
     /* compl_pattern doesn't need to be set */
     compl_orig_text = vim_strnsave(ml_get_curline() + compl_col, compl_length);
-    if (compl_orig_text == NULL || ins_compl_add(compl_orig_text,
-                       -1, p_ic, NULL, NULL, 0, ORIGINAL_TEXT, FALSE) != OK)
+    if (compl_orig_text == NULL)
        return;

+    (void)ins_compl_add(compl_orig_text, -1, p_ic, NULL, NULL, 0, ORIGINAL_TEXT, FALSE);
+
     ctrl_x_mode = CTRL_X_EVAL;

     ins_compl_add_list(list);
```

**Comment by lifepillar** [comment]
There's still something not ok, I believe. Try to put some spaces before `xxx`, then, when the menu appears, repeatedly type `<c-n>`. I see Hello->World->xxx->    xxx.

```
<spc><spc><spc>xxx<c-n><c-r>=MyComplete()<cr><c-n><c-n><c-n><c-n>
```

**Comment by chrisbra** [comment]
okay, so perhaps it's better to always clear the list of completion candidates when calling complete() function:

```
diff --git a/src/edit.c b/src/edit.c
index 2e1aa2bea..135e02dc5 100644
--- a/src/edit.c
+++ b/src/edit.c
@@ -2821,6 +2821,7 @@ set_completion(colnr_T startcol, list_T *list)
     if (ctrl_x_mode != 0)
        ins_compl_prep(' ');
     ins_compl_clear();
+    ins_compl_free();

     compl_direction = FORWARD;
     if (startcol > curwin->w_cursor.col)
```

**Comment by lifepillar** [comment]
This looks good to me. Thanks!
