### ISSUE TITLE
Spanish translation for vimtutor is subpar

### ISSUE THREAD

**Issue by miguel-dev** [vim/vim#14130]
After doing Vimtutor once in English, as a native Spanish speaker I tried a second time in Spanish and was dismayed at the errors and general low quality of the translation. Is there anything that can be done?

It's not that everything has to be rewritten, but at least it should get a quality check and some mistakes be fixed.

**Comment by WhyNotHugo** [comment]
Feel free to submit patches / PRs.

**Comment by chrisbra** [comment]
Please feel free to send patches against: https://github.com/vim/vim/blob/master/runtime/tutor/tutor.es

**Comment by miguel-dev** [comment]
Thanks, will look into it.
