### ISSUE TITLE
Question: problem with word boundary in help buffer

### ISSUE THREAD

**Issue by lijh8** [vim/vim#14139]
### Steps to reproduce

When I ` :help autocmd ` and place cursor on the text ` autocmd_add ` ,
then use star ` * ` command, the whole ` autocmd_add({replace: ` will
be highlighted. It's same to ` autocmd_add(#{replace: `.

But when I directly open the file
```
$ vi /usr/share/vim/vim90/doc/autocmd.txt
```
then press ` * ` on the text ` autocmd_add `, only ` autocmd_add ` is
highlighted. It's same to ` autocmd_add(#{replace: `.

It is the builtin star ` * `, i do not do any shortcut map.

Because of this, I had to turn off my script to highlight cursor word in `:help` buffer.

```
"autocmd CursorMoved,CursorMovedI * execute 'match Visual' (getline('.')[col('.')-1] =~# '\w' ? '/\<' . escape(expand('<cword>'), '/\.*$^~[]') . '\>/' : '//')

autocmd CursorMoved,CursorMovedI * if &filetype != 'help' | execute 'match Visual' (getline('.')[col('.')-1] =~# '\w' ? '/\<' . escape(expand('<cword>'), '/\.*$^~[]') . '\>/' : '//') | endif
```

### Expected behaviour

Word boundary should be respected in `:help` buffer.

### Version of Vim

9.0 (2022 Jun 28, compiled Oct 27 2023 01:00:56)

### Environment

OS: macOS 12.7.3 (21H1015),
Terminal: macOS builtin Terminal Version 2.12.7 (445.1),
TERM: xterm-256color,

![Screen Shot 2024-03-04 at 22 26 05](https://github.com/vim/vim/assets/9011764/9e7f6763-b227-4837-be2d-50987d6d1789)
![Screen Shot 2024-03-04 at 22 26 10](https://github.com/vim/vim/assets/9011764/716ab671-ac02-498c-ab5f-b1583555c1c8)

**Comment by chrisbra** [comment]
Help files use hard-coded values for the `isk` setting. I strongly recommend not to try to mess with those

**Comment by lijh8** [comment]
> Help files use hard-coded values for the `isk` setting. I strongly recommend not to try to mess with those

Hi Chris, 

It does not mean my script is wrong and this difference is acceptable, right?

The purpose of the script is to highlight occurrences of a word when cursor is inside the word, and cancel highlight when cursor is outside the word.

```
autocmd CursorMoved,CursorMovedI * execute 'match Visual' (getline('.')[col('.')-1] =~# '\w' ? '/\<' . escape(expand('<cword>'), '/\.*$^~[]') . '\>/' : '//')
```

Thanks

**Comment by chrisbra** [comment]
You can get fancy and save and restore the `isk` option value before/after you call the `expand(<cword>)`  thing. 
But usage questions belong rather to vi.stackexchange.com or reddit or the vim-use ml.

**Comment by lijh8** [comment]
It's better now. 
Thanks.

```
let save_isk=&isk | set isk=@,48-57,_,192-255 |
  \ autocmd CursorMoved,CursorMovedI * execute 'match Visual'
  \ (getline('.')[col('.')-1] =~# '\w' ?
  \ '/\<' . escape(expand('<cword>'), '/\.*$^~[]') . '\>/' : '//') |
  \ let &isk=save_isk

```

**Comment by chrisbra** [comment]
let's close it then.
