### ISSUE TITLE
:edit <filename with spaces> should not require escaping

### ISSUE THREAD

**Issue by justinmk** [vim/vim#1414]
`:edit` in unix Vim requires whitespace in a filename to be escaped. Windows Vim does not. That makes the `:edit` command less convenient on unix without any benefit that I can see. What is the purpose?

In expand_filename():

https://github.com/vim/vim/blob/master/src/ex_docmd.c#L5080-L5101

```
#ifdef UNIX
		/*
		 * Only for Unix we check for more than one file name.
		 * For other systems spaces are considered to be part
		 * of the file name.
		 * Only check here if there is no wildcard, otherwise
		 * ExpandOne() will check for errors. This allows
		 * ":e `ls ve*.c`" on Unix.
		 */
		if (!has_wildcards)
		    for (p = eap->arg; *p; ++p)
		    {
			/* skip escaped characters */
			if (p[1] && (*p == '\\' || *p == Ctrl_V))
			    ++p;
			else if (vim_iswhite(*p))
			{
			    *errormsgp = (char_u *)_("E172: Only one file name allowed");
			    return FAIL;
			}
		    }
#endif
```

**Comment by MaikoID** [comment]
Totally agree, it's a total bummer not be able to copy a file url from Nautilus for example that contains spaces.

**Comment by justinmk** [comment]
@MaikoID It works in Neovim.

**Comment by justinmk** [comment]
Fixed by https://github.com/vim/vim/commit/6047e2c722347ae9443c2632c6e061918ccef9c6

Best way to get something done in Vim is to do it first in Neovim :)

**Comment by micbou** [comment]
You mean like terminal support on Windows? Oh wait.

**Comment by chrisbra** [comment]
please be kind. Thanks.
