### ISSUE TITLE
GVim redraw issue -- some text disappears

### ISSUE THREAD

**Issue by habamax** [vim/vim#14156]
### Steps to reproduce

I am not sure about exact steps to be frank:

1. Run gvim with wayland enabled
2. open `buffer.c` from vim `src` dir
3. enable `yegappan/lsp` plugin to show diagnostics in `virtualtext` on the right side
4. vertically split windows and make guifont big enough some virtual text is hidden (off the window on the right side)
5. scroll window until part of the text disappears.

[Screencast from 2024-03-07 20-06-42.webm](https://github.com/vim/vim/assets/234774/e670aca8-c20f-41ae-a55b-6cceac3aa64e)

### Expected behaviour

no text should disappear

### Version of Vim

9.1.151

### Environment

debian 12, gvim with wayland enabled

**Comment by zeertzjq** [comment]
Maybe you can bisect to find which commit caused the bug?

**Comment by habamax** [comment]
> Maybe you can bisect to find which commit caused the bug?

Yep, will try to figure it out plus maybe try it without wayland.

For now if I turn off diganositcs (`:LspDiag highlight disable` -- there is no virtual text) no issues.

And if I change font size (bigger or smaller) there is no issue as well.

**Comment by chrisbra** [comment]
similar/duplicate of #14028 ?

**Comment by habamax** [comment]
@chrisbra indeed, looks quite similar. And I can reproduce it with quite an old commits. Maybe I shouldn't go to far into history.

**Comment by DanielViberg** [comment]
Is this still reproducible? Similar issue is marked as closed: https://github.com/vim/vim/issues/14028

**Comment by habamax** [comment]
let's close for now
