### ISSUE TITLE
Feature Request: Make :g/pattern/"ay work

### ISSUE THREAD

**Issue by glacambre** [vim/vim#1416]
While doing `:g/pattern/y` works (for each line matching `pattern`, the default register is replaced with the matched line), `:g/pattern/"ay` (copying the last line matching the pattern in the register "a") and `:g/pattern/"Ay` (appending each line matching the pattern to the register "a") do not. I think having some kind of symmetry between copying in normal mode and copying using `:g` would be nice and I can't think of any other `:g` command it would conflict with.
Does this idea seem worth implementing?

**Comment by vim-ml** [comment]
2017-01-28 17:26 GMT+03:00 glacambre <vim-dev-github@256bit.org>:
> While doing :g/pattern/y works (for each line matching pattern, the default
> register is replaced with the matched line), :g/pattern/"ay (copying the
> last line matching the pattern in the register "a") and :g/pattern/"Ay
> (appending each line matching the pattern to the register "a") do not. I
> think having some kind of symmetry between copying in normal mode and
> copying using :g would be nice and I can't think of any other :g command it
> would conflict with.

It would conflict with comments: `"` starts comments. And :yank
already accepts register argument: `:yank a` and `:yank A`.

> Does this idea seem worth implementing?

It is inconsistent and does not add any new features.

**Comment by chrisbra** [comment]
please ask user questions on the appropriate forums.

**Comment by ZyX-I** [comment]
@chrisbra This is not a user question, this is request to extend `:yank` syntax.
