### ISSUE TITLE
Update the documentation for `runtime/syntax/markdown.vim`

### ISSUE THREAD

**Issue by zzzyxwvut** [vim/vim#14168]
### Steps to reproduce

The help for this syntax file (`:help ft-markdown-syntax`)  
only mentions [`g:markdown_minlines`](https://github.com/vim/vim/blob/35b867b685cedbcbba9d44695077ecc9a6995f4c/runtime/doc/syntax.txt#L2241), whereas there are two  
more API variables discoverable in the `master` version of  
`syntax/markdown.vim`and the upstream [`README.markdown`](https://github.com/tpope/vim-markdown/blob/f2b82b7884a3d8bde0c5de7793b27e07030eb2bc/README.markdown?plain=1#L7-L14):   
[`g:markdown_fenced_languages`](https://github.com/vim/vim/blob/35b867b685cedbcbba9d44695077ecc9a6995f4c/runtime/syntax/markdown.vim#L24) and [`g:markdown_syntax_conceal`](https://github.com/vim/vim/blob/35b867b685cedbcbba9d44695077ecc9a6995f4c/runtime/syntax/markdown.vim#L110).

The `runtime/doc/syntax.txt` file is not tracked upstream so  
I'm filing it here.

@tpope?

### Expected behaviour

An up-to-date documentation for the syntax file.

### Version of Vim

Vim (v9.1.0160)

### Environment

Any.

**Comment by tpope** [comment]
> The `runtime/doc/syntax.txt` file is not tracked upstream so I'm filing it here.
> 
> [@tpope](https://github.com/tpope)?

I'm fine with documentation being added directly to Vim, without involvement of the upstream repo.

**Comment by chrisbra** [comment]
can either of you please open a doc PR to fix this please? Thanks

**Comment by zzzyxwvut** [comment]
I defer the honours to the maintainer. :)

**Comment by chrisbra** [comment]
alright then.
