### ISSUE TITLE
`import autoload` causes can't `import`

### ISSUE THREAD

**Issue by Song-Tianxiang** [vim/vim#14171]
### Steps to reproduce

1. create files:
```
# autoload/hello.vim
vim9script

echom "hello"

export def H()
        echom "hello frome H()"
enddef
```
```
# autoload/world.vim
vim9script

import "./hello.vim"

echom "world"

export def W()
        echom "world from W()"
enddef
```

```
# plugin/main.vim
vim9script

import autoload '../autoload/hello.vim'
import autoload '../autoload/world.vim'

command HELLO hello.H()
command WORLD world.W()
```

2. restart vim and do `:WORLD<CR>`
3. what I get:
```
hello
Error detected while processing /Users/donotreason/.vim/autoload/world.vim:
line    3:
E1053: Could not import "./hello.vim"
E1048: Item not found in script: W
```

### Expected behaviour

`:WORLD` can correctly import `hello.vim`

### Version of Vim

9.1.150

### Environment

macOS 13.6.1

**Comment by chrisbra** [comment]
Interesting,  it works, if one first calls `:HELLO` and then `:WORLD`.

**Comment by Song-Tianxiang** [comment]
I think it works because `:HELLO` make `hello.vim` compiled.
The line `import autoload '../autoload/hello.vim'` make vim knows that "ok, I will compile hello.vim if you call hello.* stuff". So if you call `:HELLO` first, vim will compile `hello.vim` correctly.
But if you call `:WORLD` first, what vim knows is:

1. vim compile plugin/main.vim ,`import autoload '../autoload/hello.vim'` so vim will compile `hello.vim` if you late call something exported from hello.vim
2. you call `:WORLD`, vim compile `autoload/world.vim` line `import "./hello.vim"` so vim go to compile `autoload/hello.vim`
3. if you put some echo line in start and end of `hello.vim`, you will find vim accutaly loaded `autoload/hello.vim`. but becasue of step 1, vim think we have compiled `hello.vim`(actually we have not), and want to return the compiled code but get nothing.
4. error, you can't import `hello.vim`

I dont know how vim works, above is just my guess.

**Comment by yegappan** [comment]
I found the issue.  I will open a PR with a fix for this issue.
