### ISSUE TITLE
firefox 51.0.1 + vimperator 3.15.0, ubuntu 16.04.

### ISSUE THREAD

**Issue by mimooh** [vim/vim#1418]
Somethin's wrong. Somethin's not quite right. I've used it for years, but just today I noticed strange behaviour (perhaps due to autoupdate of either firefox or vimperator). Suddenly :tabopen results in "Not a vimperator command: tabopen". Also f displays "Follow link" but my html content doesn't get tagged with numbers at all! Looks like fundamentaly broken behaviour. On the other end, hjkl work, gh works, :open works. I haven't inspect stuff deeper, as this should be sufficient for this report. I reinstalled vimperator, restarted ff and the behaviour is still simply broken.

**Comment by dpelle** [comment]
vimperator is not vim, so it's the wrong place to create a bug.

**Comment by mimooh** [comment]
Haha! Wrong repo! Surely I find the distinction between these two favourites of mine :) Sorry guys!
