### ISSUE TITLE
mswin.vim: Control+V does not work under X11

### ISSUE THREAD

**Issue by ciupicri** [vim/vim#14195]
### Steps to reproduce

1. Download `mswin.vim` from commit 760f664213dea9a300454992ba1589f4601d622f

2. Use it in vimrc:
```sh
cat > ~/.vim/vimrc << 'EOF'
source $HOME/.vim/mswin.vim
EOF
```

3. Copy some text from another application, e.g. Firefox.

4. Start `gvim`.

5. Enter _insert mode_ and press <kbd>Control</kbd>+<kbd>V</kbd>.

### Expected behaviour

The text from the other application should be pasted in gvim.

### Version of Vim

9.1.158-1.fc39.x86_64

### Environment

X11, XFCE, Fedora Linux 39

#### `:verbose :vmap <c-v>`
```
Seen modifyOtherKeys: true
   <C-V>         "+gP
        Last set from ~/.vim/mswin.vim line 40
```

#### `:verbose :map <c-v>`
```
Seen modifyOtherKeys: true
   <C-V>         "+gP
        Last set from ~/.vim/mswin.vim line 40
```

---

P.S. `^` is inserted and gvim waits for another key press.

P.P.S. <kbd>Control</kbd>+<kbd>V</kbd> works fine in _command mode_.

**Comment by tonymec** [comment]
Neither `:map` nor `:vmap` apply in Insert mode.

After being started as above, what does gvim answer to
```vim
:verbose map! <C-V>
```
?
(The exclamation mark requests Insert and Command-line mode mappings, while without it you'll get Normal, Visual and Operator-pending mode mappings)

BTW, I don't recommend using mswin.vim. Instead, use register + (or, in gvim, Edit→Copy, Edit→Cut, Edit→Paste) for the clipboard, or register * for the "X11 selection" (which can be pasted into other applications by means of a middle-click).

Best regards,
Tony.

**Comment by tonymec** [comment]
P.S. As defined at lines 27 to 62 of mswin.vim, the Ctrl-V (Paste) command is meant to be used in Normal mode, not in Insert mode. I believe that this is as expected.

If you want to use it in Insert mode anyway, try prefixing with Ctrl-O which means "go temporarily to Normal mode for one command".

Best regards,
Tony.

**Comment by tonymec** [comment]
P.P.S. After examining mswin.vim a little more attentively, I see that it defines mappings for Ctrl-V and Shift-Insert in Command-line mode but not Insert mode when the `+clipboard` feature is found present, but the opposite when it is absent. This could be a bug after all. I'm notifying Christian on the vim-dev list.

Best regards,
Tony.

**Comment by chrisbra** [comment]
same issue as with 760f664213dea9a300454992ba1589f4601d622f it missed to revert another test from `clipboard_working` to `clipboard`.

I'll fix it. But note, mswin.vim is already bending the idea of using Vim and keys in different modes quite a bit. I'd recommend to start learning the native vim keybindings, as those will work, whether you work on a remote server, or on a plain console with clipboard support or not.
