### ISSUE TITLE
winfixbuf: Error message E1513 is misleading.

### ISSUE THREAD

**Issue by cthoma** [vim/vim#14193]
Thank you for delivering this feature, I very much appreciate that contribution.

### Steps to reproduce

1. `$ vim --clean`
2. `:set winfixbuf`
3. `:edit`
4. Error messages appears: `E1513: Cannot edit buffer. 'winfixbuf' is enabled`

I'm very much aware of what winfixbuf does, but I think the current wording poorly communicates what the error cause is. I'm still able to edit the contents of the buffer the usual way -- insert mode, then typing some garbage -- but 'Cannot edit buffer' tells me otherwise.

### Expected behaviour

Somehow it should communicate that the window in question is tied / locked / fixed to one specific buffer and is not allowed to be the viewport to another buffer.

Proposal:
`E1513: Cannot switch buffer. 'winfixbuf' is enabled`

### Version of Vim

All versions that support 'winfixbuf'.

### Environment

Not relevant.

**Comment by chrisbra** [comment]
fixed by 0a32b8854b52381fd17a6fcc5e38a3b9e77c8923
