### ISSUE TITLE
Interactive terminal window does not close after use if all buffers are nobuflisted

### ISSUE THREAD

**Issue by EdwinChan** [vim/vim#14207]
### Steps to reproduce

This issue could be related to #2029. When an interactive `:terminal` session ends and all buffers in all tab pages are `:set nobuflisted`, the terminal window does not close automatically. For example:

1. Run `vim -u NONE -c 'set nobuflisted | terminal'`.
2. End the terminal session inside vim, e.g., by pressing <kbd>Ctrl</kbd>+<kbd>D</kbd>.

### Expected behaviour

The terminal window should close, but instead remains open and loads a new buffer.

### Version of Vim

9.1 (patches 1-181)

### Environment

Operating system: RHEL 8.9 (ssh from WSL2 Ubuntu 22.04 on Windows 11 Home)
Terminal: Windows Terminal 1.19.10573.0
Value of $TERM: xterm-256color
Shell: GNU bash, version 4.4.20(1)-release

**Comment by chrisbra** [comment]
That is essentially the  same as #14000 and this is done intentionally done. I wouldn't consider this a bug.

**Comment by EdwinChan** [comment]
Sorry, I didn't see #14000 because I only searched for open issues.

I defer to your decision to close the issue. However, it would be helpful to explain somewhere why this is the expected behavior: It is not intuitive that the behavior of one window depends on other buffers, and it is unclear what advantage is gained by keeping the window open (i.e., vim would not be in an invalid state after closing the window). Moreover, it creates another edge case scripts may need to take care of.

Note that #14000 does not exactly describe vim's behavior: The window is retained, but vim creates a new buffer to fill the window (i.e., `getwininfo()` shows the same `winid` but different `bufnr`).

**Comment by chrisbra** [comment]
I'll add a note to the documentatoin below `:h terminal-close`.
