### ISSUE TITLE
In client/server communication, gvim now complains when asked to reopen a modified file

### ISSUE THREAD

**Issue by EB2000** [vim/vim#14219]
### Steps to reproduce

This is a regression; the following works in vim 9.0.1927:
1. Open a file and act as a server:
`gvim --servername BUG bug.tex`
2. Modify the file, but do not save
3. Try to remotely reopen the file and change line number
`gvim --servername BUG --remote +2 bug.tex`

### Expected behaviour

The point of that last command is of course to move to line 2 of file bug.tex. This works whether one is in insert mode or command mode. This used to work whether the file was modified or not. I am using this functionality to be able to click on my pdf reader so that the source moves to the corresponding line.

As I said, this used to work perfectly in vim 9.0.1927. But in the newer vim 9.1.181, this only works if there are no unsaved modifications. If there are unsaved modifications, the gvim editing the file gives an error message:

`E37: No write since last change (add ! to override)`
`Press ENTER or type command to continue`

First, I don't know how to  'add a ! to override' in a remote command, but more importantly, there is no reason behind this error. With the older version, reopening the file would not lead to any information loss; it would simply exit insert mode (if not already in command mode), and move to the given line.

### Version of Vim

Working: 9.0.1927. Non-working: 9.1.181

### Environment

This is an uptodate fedora linux 39.

**Comment by chrisbra** [comment]
ah yes, sorry, I see the problem. #14220 should fix it

**Comment by EB2000** [comment]
I confirm this is working again as expected with the latest fedora update, which brought me version 9.1.309.
Thanks!
