### ISSUE TITLE
ml_get: invalid lnum when using luado

### ISSUE THREAD

**Issue by ZyX-I** [vim/vim#1421]
Consider the following code:

```Shell
vim -u NONE -i NONE -N --cmd 'set hidden' <(seq 3) <(echo 4) <(echo 5) -c 'luado vim.command("buffer " .. linenr) return linenr * 100'
```

: this code switches buffers when doing luado and buffers switched to do not have enough lines. This results in `ml_get: invalid lnum`.

**Comment by ZyX-I** [comment]
Same bug if code in `luado` changes number of lines: replace `"buffer " .. linenr` with `"%delete_"`.

**Comment by ZyX-I** [comment]
`:pydo` is also affected:

```Shell
vim -u NONE -i NONE -N --cmd 'set hidden|py import vim' =(seq 3) =(echo 4) =(echo 5) -c 'pydo vim.command("%d_")'
```

. I guess this applies to all `:*do` commands.

**Comment by brammool** [comment]
I don't think the code is shared, but probably copied.  I'll check the Python one first.
