### ISSUE TITLE
Incorrect comment reformatting in DNS zonefile

### ISSUE THREAD

**Issue by rpdprd** [vim/vim#14222]
### Steps to reproduce

Create `test.zone` with content

```
$ORIGIN example.com.

; example really long line example really long line example really long line example really long line example really long line
```

With cursor on the last line, press `gqq` to reformat the comment. 

### Expected behaviour

Expecting:

```
; example really long line example really long line example really long line
; example really long line example really long line
```

Current result - comment line not prefexed with `; `

```
; example really long line example really long line example really long line
example really long line example really long line
```

This is with `formatoptions=tcq`.

### Version of Vim

9.0.1499

### Environment

Debian 12 stock Vim

**Comment by chrisbra** [comment]
Well, there are several problems here. 
1) Vim does not yet detect `.zone` files as bind config files. It currently uses various patterns, see here: https://github.com/vim/vim/blob/0e17f7e97290f81ff55743ab5cdc69ef118be080/runtime/filetype.vim (search for bindzone).

2) Even if it did detect bind files correctly we don't have a proper filetype plugin for bind config files. I assume a file should look like this:

```
" Vim filetype plugin file
" Language:             bind zone file
" Maintainer:           <your_name_and_email_here>
" Last Change:          2024 Mar 17

if exists("b:did_ftplugin")
  finish
endif
let b:did_ftplugin = 1

setlocal comments=b:;
setlocal commentstring=;%s
setlocal formatoptions-=t
setlocal formatoptions+=crq

let b:undo_ftplugin = "setlocal com< cms< fo<"
```

Would you like to make those changes and become a maintainer of such a filetype plugin?

**Comment by pipelight** [comment]
Here is a tested quick fix to set filetype based on your preferred file extension:

```vim
au BufNewFile,BufRead *.zone setf bindzone
```
```nvim
vim.cmd "au BufNewFile,BufRead *.zone setf bindzone"
```

Based on @chrisbra very helpful debugging.
