### ISSUE TITLE
'winfixbuf' should allow :edit without args

### ISSUE THREAD

**Issue by justinmk** [vim/vim#14237]
## Problem

Raised by @tpope at https://github.com/tpope/vim-fugitive/issues/2272#issuecomment-2004992176 : 

> This option may be too aggressive. It prevents reloading the window by calling `:e` with no arguments. That doesn't change what buffer the window points to, but it is nonetheless blocked.

## Expected behavior

'winfixbuf' should not show an error if `:edit` is used without args to reload the buffer (which may be application-defined for non-file buffers).

cc @ColinKennedy

**Comment by ColinKennedy** [comment]
True, forgot about this case. It's late my time, I can fix it soon unless someone beats me to it. I'm blanking on if there's any other commands which also use the current buffer when empty but I'll double check the full list later.
