### ISSUE TITLE
gvim 9.1: resizing the window create transparent rows and columns

### ISSUE THREAD

**Issue by vstinner** [vim/vim#14233]
### Steps to reproduce

1. Open a text file which is larger than the window
2. Edit the text, if possible near the bottom-right (or at least near the center)
3. Then resize the window to marge it larger. If possible, larger than the open dialog (see step 3, it's just make the bug easier to spot)
4. Click on the File menu > Open -- or any other action which changes the background to dark while the dialog is open
5. See that some rows and lines are transparents

### Expected behaviour

Text is renderer properly

### Version of Vim

vim-X11-9.1.158-1.fc39.x86_64

### Environment

* OS: Fedora 39
* Terminal: GNOME Terminal 3.50.1 (but I'm using gvim)
* Value of $TERM: xterm-256color
* Shell: bash-5.2.26-1.fc39.x86_64
* Xwayland: xorg-x11-server-Xwayland-23.2.4-1.fc39.x86_64
* Gtk: gtk3-3.24.41-1.fc39.x86_64 (gvim is linked to /lib64/libgtk-3.so.0)

**Comment by chrisbra** [comment]
can you please share a screen shot of the issue?

**Comment by vstinner** [comment]
Screenshot showing light rows and columns which are in fact my GNOME background since the gvim windows became partially transparent!

![Capture d’écran du 2024-03-19 16-54-05](https://github.com/vim/vim/assets/194129/003ff665-8454-4f1d-82b8-969d7031a0db)

After a few edits + resize, gvim becomes completely unusuable, I cannot read text anymore :-(

![Capture d’écran du 2024-03-19 16-55-38](https://github.com/vim/vim/assets/194129/e8100ce0-3638-492a-b7c1-6f93d6c7d487)

Note: on my screen, it's rendered differently. Photo with my phone camera:

![screen](https://github.com/vim/vim/assets/194129/2bb92770-9bc0-4305-b3b6-9fe0314b0065)

Sorry for the bad photo quality. It's just to show that it's very different on screen than using GNOME screenshot tool.

**Comment by chrisbra** [comment]
Is this wayland or X11 environment?

**Comment by vstinner** [comment]
> Is this wayland or X11 environment? Does it happen in the other one?

gvim is using X11, GNOME and all other applications are using Wayland. That's why I mentioned Xwayland which is started to run gvim.

Is there a way to run gvim with Wayland?

---

I started to have this issue after a Fedora update, but I don't know when exactly. "In February". I know for sure that I had this issue at February 20, 2024 since I posted my [bug on my Mastodon profile](https://mamot.fr/@vstinner/111963904966596678) :-)

**Comment by vstinner** [comment]
Oh, to check if gvim or another app is used X11 or not, I run `import screenshot` in a terminal: if the mouse cursor changes on an app, it uses X11, since `import` is a X11 app :-)

**Comment by vstinner** [comment]
Sorry, the bug is not in gvim but somewhere lower, such as Mesa.

* If I run vim with `GVIM_ENABLE_WAYLAND=1`, I cannot reproduce the bug anymore (gvim using Wayland).
* If I put `XWAYLAND_NO_GLAMOR=1` in `/etc/environment`, I cannot reproduce the bug anymore (gvim using X11, Xwayland no longer uses hardware optimizations).

I downgraded my Linux kernel from 6.7.9-200.fc39.x86_64 to kernel-6.7.1-200.fc39.x86_64, I can still reproduce the bug. So the kernel should not be in the kernel driver on my "Intel Comet Lake GT2" GPU (IGP?).

It may be a Mesa regression. Anyway, I close this vim bug report.

**Comment by ofourdan** [comment]
See https://gitlab.freedesktop.org/xorg/xserver/-/issues/1655

**Comment by vstinner** [comment]
Workarounds:
* Run gvim with `GVIM_ENABLE_WAYLAND=1` environmenet variable.
* or: Put `XWAYLAND_NO_GLAMOR=1` in `/etc/environment`.

**Comment by chrisbra** [comment]
thansk for updating here!

**Comment by vineetgarc** [comment]
> Run gvim with GVIM_ENABLE_WAYLAND=1 environmenet variable.
Unfortunately this doesn't help.

**Comment by egroeper** [comment]
I suppose `GVIM_ENABLE_WAYLAND=1` doesn't work with Ubuntu 24.04, since it was introduced with 9.1.0064 and Ubuntu 24.04 ships with 9.1.0016 (9.1.0016-1ubuntu7.7).

**Comment by chrisbra** [comment]
well, compile your own version then

**Comment by vineetgarc** [comment]
I tried building vim - making it build for gui is a reckoning of its own. Even if you figure out the magic incantations, there's a high change installing the various X dev packages will hose your existing working desktop env which is what exactly happened to me. Perhaps need to do this in a sandbox.

**Comment by fausterix** [comment]
Hi!
Any workaround?
I'm on Ubuntu 24.04.3 LTS and XDG_SESSION_TYPE=wayland

<img width="1386" height="752" alt="Image" src="https://github.com/user-attachments/assets/6eb51b9a-593f-43ba-a930-6e31288fe227" />
