### ISSUE TITLE
Scheme highlighting is not R7RS-compliant

### ISSUE THREAD

**Issue by kozross** [vim/vim#1424]
Most notably, there is a lack of support for block comments and s-expression comments, which are described in Section 2.2 of R7RS, available [as a PDF online][2]. To demonstrate the exact problem, the following will not be highlighted correctly using the syntax highlighting for Scheme currently provided:

```
#| This should all be a comment,
but currently, it won't look like one |#
#; (this should be too) (but not this)
(+ #; (+ 5 2) 2 4) ;; this will register as a comment - the previous thing will evaluate to 6, not 13
```

I'm actually a Neovim user, and I first reported the issue to them. However, they [sent me here instead][1]. I also got in touch with the maintainer of the syntax file for Scheme, but he basically told me that he's not used Scheme for a while, and thus will only review patches or hand over maintenance. As I'm new to (Neo)vim, I'm hoping someone else might be able to solve this.

[1]: https://github.com/neovim/neovim/issues/6018
[2]: http://trac.sacrideo.us/wg/raw-attachment/wiki/WikiStart/r7rs.pdf

**Comment by kozross** [comment]
Of note is that [this work has already been done][1] (for all R7RS compatibility). Given that R7RS is the most current Scheme standard, it makes sense to have this incorporated.

[1]: http://foldling.org/git/vim-scheme.git/

**Comment by chrisbra** [comment]
If the current maintainer is okay with handling over maintainership, you can go ahead and submit new runtime files to Bram. Please send complete files, add your name and a license and make a note of the previous maintainer. Alternatively, you might want to ask the people at the given git repository(?) to submit their files, with those annotations. However, I  could not browse their repository online and could not look inside it and it looks kind of suspicious (unknown website, not able to browse their repository, no names given).

**Comment by kozross** [comment]
@chrisbra In terms of the files I linked - I can confirm they work (I just tested them yesterday, and I've had zero trouble). Admittedly, I was a bit suspicious myself, so your concern is understandable.

I have emailed the author of those files, with a link to this issue; I'd rather they submitted these, not me, as this work is a) not mine, and b) far in advance of what I understand about vim.

**Comment by vim-ml** [comment]
Hi Chris and Koz,

I'm the author of that plugin and owner of the mysterious website, and
just wanted to say I'd be happy to submit the files. I will want to take
some time to clean them up and make sure they work on a stock Vim first,
but once that's done I assume I can simply post them to this list, is
that right?

My one concern is about maintenance. I've chipped away at the plugin
over time and tweak it as I find things that aren't quite right, and I'm
sure I'll find more in the future. Are you happy for periodical updates
to be posted as well?

Cheers,

Evan

**Comment by ararslan** [comment]
Hi folks, sorry for the noise, but I just wanted to ask whether there's been any progress on this front?

**Comment by kozross** [comment]
@ararslan Near-as-I-can tell, no, since this is the first I've heard from this issue in an eternity.

**Comment by chrisbra** [comment]
a message about this issue was just posted at vim-dev https://groups.google.com/d/msg/vim_dev/x9ks3mVCF9Q/HHefx1rXAAAJ

**Comment by evhan** [comment]
Hey folks, this has been submitted and it looks like Bram committed the updates last week, so I think this issue can probably be closed. I'll be supporting the Scheme files now, too, so if you run into any trouble please let me know.

Thanks for your patience @kozross and all.

**Comment by chrisbra** [comment]
thanks for noticing me
