### ISSUE TITLE
There is a memory leak defect at line 2096 in the file /vim/src/misc1.c.

### ISSUE THREAD

**Issue by LuMingYinDetect** [vim/vim#14250]
### Steps to reproduce

1.At line 2089 in the file /vim/src/misc1.c, a pointer variable named 'user_copy' is defined. When the pointer 'user' is not NULL and 'need_copy' is not zero, the program calls vim_strsave(user) to allocate a block of dynamic memory for the pointer 'user_copy', as shown in the diagram below:
https://github.com/LuMingYinDetect/vim_defects/blob/main/vim_9.png

2.The function vim_strsave is designed to create a dynamic memory region to store a backup of the memory space pointed to by a certain pointer. At line 23 of the vim_strsave function, a pointer named 'p' is defined. This pointer is allocated a block of dynamic memory by the function 'alloc' at line 27. Then, at line 29, the content of the original pointer is copied to the pointer 'p' using the function mch_memmove. Finally, at line 30, the pointer 'p' is returned, as shown in the diagram below:
https://github.com/LuMingYinDetect/vim_defects/blob/main/vim_10.png

3.After the execution of vim_strsave, the pointer user_copy points to a newly allocated dynamic memory region. When the third condition in the if statement at line 2092 (with the first two conditions being false) evaluates to true, the program only frees the dynamic memory region pointed to by user at line 2095 without releasing the dynamic memory region pointed to by user_copy. Subsequently, the program returns at line 2096. Since the program returns at line 2096, the usage of the variable user_copy at line 2098 will not be executed. During this process, the dynamic memory region pointed to by user_copy is neither utilized nor released, thereby resulting in a memory leak defect, as illustrated in the diagram below:
https://github.com/LuMingYinDetect/vim_defects/blob/main/vim_11.png

### Expected behaviour

If this memory leak defect is true, it is advisable to fix this defect.

### Version of Vim

9.1.0192

### Environment

Ubuntu 22.04

**Comment by chrisbra** [comment]
Thanks, it rather seems like a copy-paste error and it should have freed `user_copy` instead. I don't think we should free the `user` pointer actually.
