### ISSUE TITLE
[vim9script] Unexpected results for `!false || !false` and `!true && !true` in `:def` style function

### ISSUE THREAD

**Issue by lxhillwind** [vim/vim#14265]
### Steps to reproduce

For these 2 statements (`!false || !false` and `!true && !true`):
- If each statement's second operator is enclosed in `()`, the results are as expected (returning true / false respectively);
- If executed at the vim9script level (outside of def functions), the results are also as expected;
- If executed within a legacy function, the results are as expected as well.

Let me express it in a vim9script:

```vim
vim9script

# Function F() serves as a demonstration of the bug;
# the other parts are provided for reference only (to illustrate that in other cases, the behavior is as expected)

def F()
    echo 'unexpected behavior:'
    echo 'echo !false || !false'
    echo !false || !false
    echo 'echo !true && !true'
    echo !true && !true
enddef
F()

echo '---'

echo 'expect true'
echo !false || !false
echo !false || (!false)
echo 'expect false'
echo !true && !true
echo !true && (!true)

def F2()
    echo 'expect true'
    echo !false || (!false)
    echo 'expect false'
    echo !true && (!true)
enddef
F2()

legacy function! s:F3()
    echo 'expect true'
    echo !v:false || !v:false
    echo !v:false || (!v:false)
    echo 'expect false'
    echo !v:true && !v:true
    echo !v:true && (!v:true)
endfunction
legacy call s:F3()
```

### Expected behaviour

`!false || !false` always returns true; `!true && !true` always returns false.

### Version of Vim

9.1.178

### Environment

Verified on linux (alpine linux) and macos.

**Comment by lxhillwind** [comment]
I seem to have discovered a pattern:

- In `expr-&&`, if the first operator evaluates to false (regardless of whether it is enclosed in `()`), and the second operator is not enclosed in `()` (regardless of whether it evaluates to true or false), the result is true.
- In `expr-||`, if the first operator evaluates to true (regardless of whether it is enclosed in `()`), and the second operator is not enclosed in `()` (regardless of whether it evaluates to true or false), the result is false.

**Comment by lxhillwind** [comment]
A more compact example:

```vim
vim9script

def F()
    # expect false
    echo 0 && !0
    # expect true
    echo 1 || !1
enddef

F()
```

**Comment by habamax** [comment]
This is quite unexpected.

Works just fine outside the `F()`.
