### ISSUE TITLE
Strange behavior of fnamemodify on Windows

### ISSUE THREAD

**Issue by zoumi** [vim/vim#14279]
### Steps to reproduce

cd D:/my_note/
echomsg fnamemodify('D:',':p')
"output: D:\\my_note\\
echomsg fnamemodify('C:',':p')
"output: C:\\
cd C:/Windows
echomsg fnamemodify('C:',':p')
"output: C:\\Windows\\

### Expected behaviour

the ouput of echomsg fnamemodify('D:',':p') should be "D:\\"

### Version of Vim

Gvim 9.1 64bit

### Environment

Window 7 64bit

**Comment by k-takata** [comment]
I think that this is the expected behavior.
Each drive has each current directory on Windows.
'C:' means current directory of C drive.
'D:' means current directory of D drive.

**Comment by Shane-XB-Qian** [comment]
> I think that this is the expected behavior.
> Each drive has each current directory on Windows.
> 'C:' means current directory of C drive.
> 'D:' means current directory of D drive.

the point of OD perhaps was the cur dir changed the fnamemodify result/behavior.

-- 
shane.xb.qian

**Comment by chrisbra** [comment]
okay, so expected behaviour. Closing then.

**Comment by Shane-XB-Qian** [comment]
```
cd D:/my_note/
echomsg fnamemodify('D:',':p')
"output: D:/my_note
```
tho I do not use Window, but this output should not be `D:/` ? :shrug:

--
shane.xb.qian

**Comment by k-takata** [comment]
`D:` means the current directory of drive D.
So, it should return `D:\my_note\`.

**Comment by yegappan** [comment]
More information about this is available in the following pages;

https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file
https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats

**Comment by Shane-XB-Qian** [comment]
ahhhhhh~ ok, if say so... thanks.
