### ISSUE TITLE
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.

### ISSUE THREAD

**Issue by JefriReynaldi** [vim/vim#14270]
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

_Originally posted by @JefriReynaldi in https://github.com/vim/vim/issues/14262#issuecomment-2015366258_

**Comment by chrisbra** [comment]
Sorry, I don't follow. About what component are you talking?

**Comment by chrisbra** [comment]
seems invalid, closing

**Comment by clason** [comment]
These are bot spams; Github is plagued by those (some repos more than others). Best you can do is close these quickly and block the accounts for good measure; then the bots will move on to other targets. (No one knows what they are supposed to gain from this. Nature, in her infinite wisdom, is presumably working on it.)

**Comment by Shane-XB-Qian** [comment]
AD, leading you to check its AD. that's its purpose, including this reply then you were into its list.
that would hurt people who just wish to get good bandwidth/entering which (s)he like sites, 
wish some xxx mgr kept wisdom which to attack just those crazy, but kept general people access.

**Comment by chrisbra** [comment]
Thanks, I have now in addition blocked that bot from the vim organization.
