### ISSUE TITLE
Virtual text affects `gq` format behavior.

### ISSUE THREAD

**Issue by jiangyinzuo** [vim/vim#14276]
### Steps to reproduce

1. minimal vimrc and text file

prop.vim
```vim
call prop_type_add('exampleType', #{highlight: 'Comment'})
call prop_add(1, 1, #{type: 'exampleType', id: 1, text: 'I am Virtual!'})

set textwidth=30
set colorcolumn=30
set conceallevel=2
```

a simple `input.md` file
```
apple orange banana watermelon

apple orange banana watermelon

**apple orange banana watermelon**
```

2. start vim `vim --clean -S prop.vim input.md`

![image](https://github.com/vim/vim/assets/40995042/ac9f5c6b-653f-47a7-9925-8862e8b97c46)

3. type `gqG` to format the whole text file

### Expected behaviour

`input.md` is expected to be formatted as
```
apple orange banana watermelon

apple orange banana watermelon

**apple orange banana
watermelon**
```
![image](https://github.com/vim/vim/assets/40995042/4e45cc78-3777-47b8-b209-8cc03eb9b72a)

But actually, it is formatted as
```
apple orange
banana watermelon

apple orange banana watermelon

**apple orange banana
watermelon**
```
![image](https://github.com/vim/vim/assets/40995042/1ee7a894-a9f0-40a1-8352-84266100881c)

I also tested concealed text. It works as expected.

I think the virtual text should not affect `gq` format. When a text with virtual text is formatted, its behavior should remain consistent with the original text. But I'm not sure if formatting together with virtual text could be considered a feature, or if it's needed in some scenarios.

### Version of Vim

9.1.199

### Environment

Ubuntu 24.04 WSL2

**Comment by jiangyinzuo** [comment]
If someone truly needs to bypass the issue, they can set `formatprg` to use external formatter tools such as `fmt` or `par`.

**Comment by chrisbra** [comment]
I guess this depends. I actually find the current behaviour better, because re-formatting takes the virtual text into account and makes sure, that the whole line, including the virtual text does stay within the specified width.

**Comment by jiangyinzuo** [comment]
OK, I have no more questions about this issue. Some one can use external format tool if they want to ignore virtual text.
