### ISSUE TITLE
Unicode character ſ is matched as itself and as 's.'

### ISSUE THREAD

**Issue by diffsetter** [vim/vim#14294]
### Steps to reproduce

1. Open a utf8 encoded file in vim containing the line "Die Gleichheit fordert das Nachdenken heraus durch Fragen, die ſich daran knüpfen und nicht ganz leicht zu beantworten ſind."
2. use `:set ignorecase`
3. replace the character ſ by s using `:%s/\%u017F/s/g`

### Expected behaviour

The two occurrences of 'ſ' will be replaced by 's' resulting in "Die Gleichheit fordert das Nachdenken heraus durch Fragen, die sich daran knüpfen und nicht ganz leicht zu beantworten sind." However, the actual result is "Die Gleichheit fordert dasNachdenken herausdurch Fragen, die sich daran knüpfen und nicht ganz leicht zu beantworten sind.", i.e., the two original s characters **together with the following character** are also replaced by 's' as if I had used the command `:%s/s./s/g`. See also [this discussion](https://stackoverflow.com/questions/78214264).

### Version of Vim

9.1.151 but also older like 8.0

### Environment

system: x86_64 GNU/Linux
terminal: konsole, linux
$TERM: linux, xterm-256color
$LANG: de_DE.UTF-8, en_GB.UTF-8, C.UTF-8

**Comment by chrisbra** [comment]
hm, it works with `:set regexpengine=1`

**Comment by diffsetter** [comment]
> hm, it works with `:set regexpengine=1`

Indeed, it does. But does that mean it's not a bug? I didn't know that option. The help file says: "Note that when using the NFA engine [the one that must have been chosen by vim automatically in this case] and the pattern contains something that is not supported **the pattern will not match**…" But here something is matched that shouldn't have been matched.

**Comment by RestorerZ** [comment]
It kind of reminds me of this. issues [#12579](https://github.com/vim/vim/issues/12579)

**Comment by chrisbra** [comment]
yes and also related: https://github.com/vim/vim/issues/13682

**Comment by chrisbra** [comment]
I checked it and I think I found the issue. However, I have a question. Can I assume correctly, that `'ſ'` **should** match the lower case 's' if ignoring case?

**Comment by chrisbra** [comment]
that was closed unexpectedly. Let's re-oopen
