### ISSUE TITLE
v:event.regname blank for +, *, ", etc in TextYankPost in WSL

### ISSUE THREAD

**Issue by rcmosher** [vim/vim#14304]
### Steps to reproduce

1. Install Vim in WSL and run with -u NONE.
2. `:autocmd TextYankPost * echomsg v:event.regname`
3. `"qyy`
4. The register name "q" is echoed.
5. `"+yy`
6. No register name is echoed'

### Expected behaviour

"+" should be echoed when using the "+" register with that autocmd

This works as expected on a actual Linux build (not WSL) with the exact same output from `vim --version` and in gVim directly on Windows. It appears to be WSL specific

### Version of Vim

9.0 patches 1-749

### Environment

Operating system: Ubuntu 20.04.6 running in WSL 1
terminal: alacritty 0.11.0
$TERM: screen-256color
shell: bash 5.0.17

**Comment by chrisbra** [comment]
Does gvim with clipboard actually work on WSL?

**Comment by rcmosher** [comment]
I've not run gvim on WSL so I can't. I haven't ever configured running GUI applications from WSL.

As for CLI Vim, that's what I'm using `TextYankPost` to accomplish. It passes the regcontents on to a Windows executable to make them available outside WSL. + or * seemed like fitting registers to link this behavior too. I want to restrict when that happens as the command is painfully slow.

Is that what is going on? + and * aren't really valid in this context?

**Comment by chrisbra** [comment]
Well, first of all, you did not show the output of `:version`. Check if it contains `+clipboard` support. But even then it most probably won't work, because essentially the clipboard feature is a feature provided by your operating system. On Linux/Unix this usually requires a running X-Server. 

However, I seem to remember that clipboard feature worked for me with WSL2 on Windows 11 using the MS Terminal. I don't don't know if this was something special with WSL2 or Windows or the MS Terminal.

**Comment by rcmosher** [comment]
Version is below and contains `+clipboard` support.
I'm on WSL1 as I also use Omnisharp-Vim which has had problems with WSL2. So maybe a no go for now. I'm also on Windows 10. I tried Windows Terminal and that made no difference.

I may just do something like `map "+ "g` if in WSL so I have a register I can get the name of to limit the functionality to but keep the muscle memory of copying to the clipboard.

---

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled May 10 2022 08:40:37)
Included patches: 1-749
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       +tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
+balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +gettext           +num64             +textobjects
+browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     +perl              +title
+channel           +ipv6              +persistent_undo   +toolbar
+cindent           +job               +popupwin          +user_commands
+clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           -python            +viminfo
+cmdline_info      +libcall           +python3           +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
+cscope            +localmap          +ruby              +wildignore
+cursorbind        +lua               +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con_gui    +mksession         +smartindent       +writebackup
+diff              +modify_fname      +sodium            +X11
+digraphs          +mouse             +sound             -xfontset
+dnd               +mouseshape        +spell             +xim
-ebcdic            +mouse_dec         +startuptime       +xpm
+emacs_tags        +mouse_gpm         +statusline        +xsmp_interact
+eval              -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary
-farsi             -mouse_sysmouse    -tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wdate-time -g -O2 -fdebug-prefix-map=/build/vim-s9rYnH/vim-9.0.0749=. -fstack-protector-strong -Wformat -Werror=format-security -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE -lm -ltinfo -lselinux -lcanberra -lsodium -lrt -lacl -lattr -lgpm -ldl -L/usr/lib -llua5.2 -Wl,-E -fstack-protector-strong -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu/perl/5.30/CORE -lperl -ldl -lm -lpthread -lcrypt -L/usr/lib/python3.8/config-3.8-x86_64-linux-gnu -lpython3.8 -lcrypt -lpthread -ldl -lutil -lm -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm -lruby-2.7 -lm -L/usr/lib

**Comment by chrisbra** [comment]
Let me close this here as not a Vim bug. It doesn't really sound like a Vim bug, but rather a limitation of your specific environment.

**Comment by k-takata** [comment]
You may need to use some kind of X server. (VcXsrv, WSLg, ...)
