### ISSUE TITLE
Clear text file gets automatically encrypted without explicitly executing encrypt command if clear text begins exactly like text in encrypted Vim file

### ISSUE THREAD

**Issue by igor2x** [vim/vim#1430]
Hi,
I installed Vim nightly on Ubuntu 16.04. Vim version is: 8.0.267. My humble opinion is problem in this ticket relates to issue https://github.com/vim/vim/issues/1096 reported by me few months ago. But I am reporting a new problem, because I have a new reproduce case.

General idea. I am having a cleartext file that has got the same content first few characters like it would be encrypted file.

1. I opened empty file from bash shell: vim -u NONE -N test.txt
2. Type letter I to enter insert mode.
3. Type in the following text: VimCrypt~03!abc
4. Save and quit: :wq
5. Open file: vim -u NONE -N test.txt
6. Need encryption key for "test.txt" message appears. Don't forget this was a cleartext file with the same starting few bytes as encrypted file. Type in what ever, I typed: dummy
7. File is opened with clear text which if fine, but additional burden if you look at the status bar there is written [readonly].
8. You can make some changes to the buffer if you like, but it is not required. Just save the read only file: :w!
   Not look at the status bar. Text appears: [blowfish2]. It looks like my file got encrypted. Remember I have started with step 3 with clear text file and now after saving my file got encrypted. THE PROBLEM.
9. Exit vim: :q
10. Open a file: vim -u NONE -N test.txt
11. Need encryption key message appears. Type in what ever, but not "dummy" (password from test 6).
12. You really get encrypted file. Close the vim: :q!
13. Open file: vim -u NONE -N test.txt
14. Type in: dummy (password from step 6) and file gets correctly decrypted.

Steps from 9 to 14 is a proof file really gets encrypted without me explicitly use command to encrypt the file.

Actually if I am picky there are three problems:
a) Step 6 when opening clear text file passwrod is required for clear text file. This probably is hard to avoid, because Vim probably checks for first few bytes if text VimCrypt~0X! appears. This is minor problem, probably difficult/impossible to avoid.
b) Step 7 when opening file, buffer gets into [readonly] state. In my humble opinion it should be read/write. Still not big problem.
c) Step 8 file gets encrypted without any command was given to encrypt the file and it gets encrypted with dummy password. This is the biggest problem of all of this three problems.

I know this is not highly important problem. Ordinary user would probably never ever get into this problem at all, but I still think this should be fixed. I have hard time trusting encryption tools if they appear to be somehow broken.

Regards

**Comment by brammool** [comment]
If you don't want encryption, then don't type a key.  Then the problem does not happen (except 'readonly' being set, but that's easy to fix).
Typing a key makes the text show up garbled, I don't see how a user would get the idea to write the file like that.
Otherwise, it's a corner case and very, very unlikely to happen in real life.  It's not worth being incompatible with previous versions for this (which would break opening previously encrypted files).
The only thing we could do is, if a new encryption method is added, add some random bytes to avoid plain text to be recognized as the encryption header.  Unfortunately, nobody has taken on this task yet.

**Comment by skywind3000** [comment]
maybe we can add an invisible characters in the encryption header in the future releases ? like "\0" , this will distinguish easily from normal text .
