### ISSUE TITLE
Conflict between perl and ncurses

### ISSUE THREAD

**Issue by szp24** [vim/vim#14315]
### Steps to reproduce

My configuration is with --enable-luainterp --enable-perlinterp --enable-python3interp --enable-rubyinterp --enable-cscope --with-features=huge and CONF_TERM_LIB = --with-tlib=ncurses. When configuring, error occurs:

checking for tgetent()... configure: error: NOT FOUND!
      You need to install a terminal library; for example ncurses.
      On Linux that would be the libncurses-dev package.
      Or specify the name of the library with --with-tlib.

But I have installed any package of ncurses that I can install:

ncurses-base-6.2-10.20210508.el9.noarch
ncurses-libs-6.2-10.20210508.el9.x86_64
ncurses-libs-6.2-10.20210508.el9.i686
ncurses-6.2-10.20210508.el9.x86_64
ncurses-c++-libs-6.2-10.20210508.el9.x86_64
ncurses-devel-6.2-10.20210508.el9.x86_64
ncurses-term-6.2-10.20210508.el9.noarch
ncurses-compat-libs-6.2-8.20210508.1.el9.x86_64

But if I remove  --enable-perlinterp, no error occurs. So it seems that there is conflict between perl and ncurses. How can I compile vim with perl interface? I install perl through  "dnf install perl --enablerepo=devel".

### Expected behaviour

I expect to compile vim with perl interface. How to fix the error?

### Version of Vim

9.1.0211

### Environment

My operating system is Rockylinux 9.2. TERM is xterm-256color.

**Comment by chrisbra** [comment]
Well, you'll need to figure out, why [this configure check](https://github.com/vim/vim/blob/aed6554b46bbba39bcb22e49cc731176cd75789b/src/configure.ac#L3522-L3531) fails.

**Comment by szppp** [comment]
> Well, you'll need to figure out, why [this configure check](https://github.com/vim/vim/blob/aed6554b46bbba39bcb22e49cc731176cd75789b/src/configure.ac#L3522-L3531) fails.

All I can tell from this configure is that it's used to test whether tgetent() exists. But I think the key problem is why enabling perl interface prevent tgetent() to be found, and I can't know it from the configure.

**Comment by k-takata** [comment]
Please check and/or share the log file (`src/auto/config.log`).

**Comment by szppp** [comment]
> Please check and/or share the log file (`src/auto/config.log`).

[config.log](https://github.com/vim/vim/files/14789371/config.log)

**Comment by k-takata** [comment]
From your log, `PERL_LIBS` is:
```
PERL_LIBS='-Wl,--enable-new-dtags -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib64/perl5/CORE -lperl -lpthread -lresolv -ldl -lm -lcrypt -lutil -lc'
```

And the error is:
```
configure:12828: checking for tgetent()
configure:12841: gcc -o conftest -O2 -fno-strength-reduce -Wall -Wno-deprecated-declarations  -Wl,--enable-new-dtags -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1    -L/usr/local/lib conftest.c  -lselinux  -lncurses >&5
conftest.c: In function 'main':
conftest.c:92:20: warning: unused variable 'res' [-Wunused-variable]
   92 | char s[10000]; int res = tgetent(s, "thisterminaldoesnotexist");
      |                    ^~~
/usr/bin/ld: /tmp/cck9Hcj1.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
collect2: error: ld returned 1 exit status
```

So, some of the linker flags coming from Perl causes the PIE error.
You may want to debug which linker flag caused it.

**Comment by szppp** [comment]
> So, some of the linker flags coming from Perl causes the PIE error.
> You may want to debug which linker flag caused it.

Sorry, but I don't really know how to do it. Could you please provide some advice?

**Comment by chrisbra** [comment]
Check auto/config.mk, there should be a line `PERL_LIBS=` I guess it's the `-Wl,-z,relro [...] -Wl,-z,now` flags? I am not sure how to get around this, possibly like this?

I am just guessing here, perhaps this patch:
```patch
diff --git a/src/auto/configure b/src/auto/configure
index 9712104cd..3a0c3e2c9 100755
--- a/src/auto/configure
+++ b/src/auto/configure
@@ -6503,8 +6503,12 @@ printf "%s\n" "$vi_cv_perl_xsubpp" >&6; }
                -e 's/-W[^ ]*//g' \
                -e 's/-D_FORTIFY_SOURCE=.//g'`
             perllibs=`cd $srcdir; $vi_cv_path_perl -MExtUtils::Embed -e 'ldopts' | \
-               sed -e '/Warning/d' -e '/Note (probably harmless)/d' \
-                       -e 's/-bE:perl.exp//' -e 's/-lc //'`
+               sed -e '/Warning/d' \
+                   -e '/Note (probably harmless)/d' \
+                   -e 's/-bE:perl.exp//' \
+                   -e 's/-lc //' \
+                   -e 's/-Wl,-z,relro//' \
+                   -e 's/-Wl,-z,now//'`
                   perlldflags=`cd $srcdir; $vi_cv_path_perl -MExtUtils::Embed \
                -e 'ccdlflags' | sed -e 's/-bE:perl.exp//'`

diff --git a/src/configure.ac b/src/configure.ac
index 6311269e1..1691db9f5 100644
--- a/src/configure.ac
+++ b/src/configure.ac
@@ -1174,8 +1174,12 @@ if test "$enable_perlinterp" = "yes" -o "$enable_perlinterp" = "dynamic"; then
                -e 's/-D_FORTIFY_SOURCE=.//g'`
       dnl Remove "-lc", it breaks on FreeBSD when using "-pthread".
       perllibs=`cd $srcdir; $vi_cv_path_perl -MExtUtils::Embed -e 'ldopts' | \
-               sed -e '/Warning/d' -e '/Note (probably harmless)/d' \
-                       -e 's/-bE:perl.exp//' -e 's/-lc //'`
+               sed -e '/Warning/d' \
+                   -e '/Note (probably harmless)/d' \
+                   -e 's/-bE:perl.exp//' \
+                   -e 's/-lc //' \
+                   -e 's/-Wl,-z,relro//' \
+                   -e 's/-Wl,-z,now//'`
       dnl Don't add perl lib to $LIBS: if it's not in LD_LIBRARY_PATH
       dnl a test in configure may fail because of that.
       perlldflags=`cd $srcdir; $vi_cv_path_perl -MExtUtils::Embed \
```

**Comment by szppp** [comment]
The problem has solved with adding "CFLAGS = -fPIE" into src/Makefile.
