### ISSUE TITLE
When translating, the error E877 is marked as obsolete

### ISSUE THREAD

**Issue by RestorerZ** [vim/vim#14333]
### Steps to reproduce

When updating PO files, the error E877 (e_nfa_regexp_invalid_character_class_nr) is marked with a comment #~, i.e. as obsolete.

https://github.com/vim/vim/blob/ad493ef3ea9ef7f2b0badcd2298883b5ab6e4ef4/src/regexp_nfa.c#L1400

https://github.com/vim/vim/blob/ad493ef3ea9ef7f2b0badcd2298883b5ab6e4ef4/src/regexp_nfa.c#L5153
The gettext macro is missing in the second error assignment.
Most likely due to the fact that the error assignment is used as an internal error.

### Expected behaviour

It should not be marked as obsolete.

### Version of Vim

Vim 9.1.225

### Environment

All

**Comment by chrisbra** [comment]
Hm, I don't see `#~` marked for the few po files that define `E877`. For some reason, `E877` is not in all po files. For example, it's not in de.po (even when I create a completely new de.po file)

So where do you see the `#~` marker?

**Comment by RestorerZ** [comment]
For reproduction `#~` marker:
```
nmake.exe -f Make_mvc.mak ca da eo es fi fr ko ko.UTF-8 pt_br zh_cn.UTF-8 zh_cn.cp936
```
For example, `da.po`:

> #, c-format
> #~ msgid "E877: (NFA regexp) Invalid character class: %ld"
> #~ msgstr "E877: (NFA regexp) Ugyldig tegnklasse: %ld"  



> For some reason, `E877` is not in all po files.

That's the point. And this should be in all PO files.
Apparently, according to my translations, there was still this error in version 9.0.1583. And in version 9.0.1596 it is no longer there.

Try to do `nmake.exe -f Make_mvc.mak vim.pot`
This error will not be in `Vim.pot`.
When the PO files are updated, the lines are marked as obsolete and when the files are cleaned, "cleanup.vim" deletes these lines.

As I said above, this error does not get into Vim.pot due to the fact that the gettext macro is missing when assigning this error in line 5153 the "regexp.nfa.c" file.
