### ISSUE TITLE
test_termcode fails in Alacritty

### ISSUE THREAD

**Issue by benknoble** [vim/vim#14341]
### Steps to reproduce

See #14325 for some initial steps.
In alacritty, after `make distclean`, `./configure …`, `make`, I normally run `make test`. This failed; I've narrowed it to `make -C src/testdir test_termcodes` consistently failing:

```
[snip]
00:00 Executing Test_ignore_dec_mouse()

E558: Terminal entry not found in terminfo
'alacritty' not known. Available builtin terminals are:
    builtin_ansi
    builtin_vt320
    builtin_vt52
    builtin_xterm
    builtin_iris-ansi
    builtin_pcansi
    builtin_win32
    builtin_amiga
    builtin_dumb
    builtin_debug
00:01 Executing Test_insert_literal()
[snip]
Executed 66 tests                        in  15.539443 seconds
1 FAILED:
Found errors in Test_ignore_dec_mouse():
Caught exception in Test_ignore_dec_mouse(): Vim(let):E522: Not found in termcap @ command line..script /Users/BZT230/.vim-source/src/testdir/runtest.vim[607]..function RunTheTest[57]..Test_ignore_dec_mouse, line 20
```

In a different build (I think there are slightly different configure options?), I consistently get instead (with `Test_ignore_dec_mouse` not showing any odd behavior):
```
[snip]
00:12 Executing Test_mouse_alt_leftclick()

E558: Terminal entry not found in terminfo
'alacritty' not known. Available builtin terminals are:
    builtin_ansi
    builtin_vt320
    builtin_vt52
    builtin_xterm
    builtin_iris-ansi
    builtin_pcansi
    builtin_win32
    builtin_amiga
    builtin_dumb
    builtin_debug
00:12 Executing Test_mouse_cmdwin_resize()
[snip]
Executed 66 tests                        in  15.585377 seconds
1 FAILED:
Found errors in Test_mouse_alt_leftclick():
Caught exception in Test_mouse_alt_leftclick(): Vim(let):E522: Not found in termcap @ command line..script /Users/BZT230/code/vim/src/testdir/runtest.vim[607]..function RunTheTest[57]..Test_mouse_alt_leftclick, line 29
```

### Expected behaviour

I'm not sure what these tests are doing, and I don't think they're likely to actually block my use of that built Vim. But it would be nice if they passed.

### Version of Vim

v9.1.0228-1-g4fa06bb17

### Environment

Same as #14325 

### Logs and stack traces

```shell
Build script for ignore_dec_mouse failure:
---
#! /usr/bin/env bash

set -euo pipefail

: "${VIM_SOURCE:="$HOME"/.vim-source}"

log() {
  printf '%s: ' "$0"
  printf '%s\n' "$@"
} >&2

install_deps() {
  if ! command -v brew >/dev/null 2>/dev/null; then
    log 'missing brew'
    return 1
  fi
  local deps
  readarray -t deps < <(brew deps --1 --include-build --include-optional vim | grep -v 'lua\|perl\|ruby')
  brew install "${deps[@]}"
}

clone_vim() {
  if ! [[ -d "${VIM_SOURCE}" ]]; then
    git clone --depth=1 --no-tags https://github.com/vim/vim "${VIM_SOURCE}"
  else
    git -C "${VIM_SOURCE}" fetch --depth=1
    git -C "${VIM_SOURCE}" reset --hard HEAD@'{upstream}'
  fi
}

build_and_install_vim() (
  pushd "${VIM_SOURCE}"
  unset SDKROOT PYTHONPATH
  local python python_path
  python=$(brew deps --1 --include-build --include-optional vim | grep python | head -n 1)
  python_path="$(brew --prefix "$python")/bin"
  PATH="$python_path:$PATH"
  local configure_args=(
    --with-tlib=ncurses
    --with-compiledby=benknoble
    --enable-cscope
    --enable-terminal
    --enable-python3interp
    --enable-gui=no
    --without-x
  )
  time ./configure "${configure_args[@]}"
  time make -j "$(nproc)"
  time make test
  time make install STRIP="$(command -v true)"
)

main() {
  install_deps
  clone_vim
  time build_and_install_vim
}

main
---

Script for the mouse_alt_leftclick failure:
---
#!/bin/bash
set -xeuo pipefail

unset SDKROOT PYTHONPATH
python=$(brew deps --1 --include-build --include-optional vim | grep python | head -n 1)
python_path="$(brew --prefix "$python")/bin"
PATH="$python_path:$PATH"
configure_args=(
  --enable-multibyte
  --with-tlib=ncurses
  --with-compiledby=benknoble
  --enable-cscope
  --enable-terminal
  --enable-python3interp
  --enable-gui=no
  --without-x
)
./configure "${configure_args[@]}" || exit 125
make -j "$(nproc)" || exit 125

make -C src/testdir/ test_termcodes
---

(The latter can be used to bisect; looking at them again, they aren't so much different that I would expect a consistently different error here. I'll try to bisect.)
```

**Comment by benknoble** [comment]
Bad news: I got this failure while bisecting `master v9.1.0`, so this is either a new-ish thing from Alacritty or a longer-standing issue with the test. Oddly, in the "bisect" (dev) repo using that second script, I _consistently_ got the failure in mouse_alt_leftclick. In my ~/.vim-source repo, where I do a shallow checkout just for compile/install, I seem to consistently get the other failure about ignore_dec_mouse.

**Comment by benknoble** [comment]
Since this might be related to `ttymouse`, I've been using `ttymouse=sgr` since February of 2020 (and Alacritty since about the same time).

**Comment by chrisbra** [comment]
Both of the failures, happen when restoring the terminal setting after having temporarly set it to `:set term=xterm` or `:set term=gnome`:

https://github.com/vim/vim/blob/cbb92b5ceb6a8169b6eddceec3837aac02f21e3b/src/testdir/test_termcodes.vim#L1050

https://github.com/vim/vim/blob/cbb92b5ceb6a8169b6eddceec3837aac02f21e3b/src/testdir/test_termcodes.vim#L2223

I have no idea, why `:set term=alacritty` would fail for you. Do you have it in your terminfo database? Can you reproduce this failure manually (e.g. `:set term=xterm| :set term=alacritty`)?

**Comment by benknoble** [comment]
Yes, alacritty exists in the terminfo database (it's files are installed automatically by Homebrew, for example).

Running the command you gave in both my working 9.1 and my built 9.1.228 whose tests error gives a small screen flicker and that's all. There's nothing in a verbose=16 log either that would indicate an issue.

**Comment by chrisbra** [comment]
> Yes, alacritty exists in the terminfo database (its files are installed automatically by Homebrew, for example).

I suppose this is set in your `$HOME/.terminfo` ?  I believe the tests specifically set `$HOME` to some random value, to not mess with your home directory (see [here](https://github.com/vim/vim/blob/cc7597c1edf478ad912d45b27f17175236f9791e/src/testdir/setup.vim#L33-L43)). 

Perhaps you need to export $TERMINFO environment to point it explicitly?

**Comment by benknoble** [comment]
It does indeed that exporting `TERMINFO=~/.terminfo` worked; for future reference, there's also `TERMINFO_DIRS` with works like `PATH` and can use a blank entry (written `::`) to include the "default" system location (_e.g._, `/usr/share/terminfo`).
