### ISSUE TITLE
comand :args does not correctly show what file user is on after using comand Ctrl-^

### ISSUE THREAD

**Issue by ayrapetovai** [vim/vim#14375]
### Steps to reproduce

Open 3 files
```shell
vim file1 file2 file3
```

Execute commands inside vim
```text
:next
3<Ctrl-^>
:args
```

Where 3<Ctrl-^> means - press key 3, than holding Control and Shift press key 6.

### Expected behaviour

Expected: command `:args` shows that user is on the file3,
```text
file1    file2   [file3]
```

But instead of that command `:args` shows that user is on the file2.
```text
file1   [file2]   file3
```
what i consider to be a bug.

### Version of Vim

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Mar 14 2024 13:39:48) Included patches: 1-1672, 1729, 1747, 2107, 1840, 1846-1848, 1857-1858, 1873, 1969, 1992, 2010, 2068, 2106, 2108-2112, 2121 Modified by team+vim@tracker.debian.org Compiled by team+vim@tracker.debian.org

### Environment

TERM: `xterm-256color`
SHELL: `GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu)`
OS: `Linux 6.5.0-26-generic #26-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar  5 21:19:28 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by chrisbra** [comment]
`3<Ctrl-^>` **does not** change the argument list, instead it moves around in the buffer-list. Both lists are independent of each other, so I think this is not a bug. See also [:h arglist](https://vimhelp.org/editing.txt.html#arglist) (and check the second paragraph).

**Comment by ayrapetovai** [comment]
Thanks for the explanation.
Did you meant this by the second paragraph?
```
Do not confuse this with the buffer list, which you can see with the :buffers command.
The argument list was already present in Vi, the buffer list is new in Vim.
Every file name in the argument list will also be present in the buffer list
(unless it was deleted with :bdel or :bwipe).
But it's common that names in the buffer list are not in the argument list.
```
Now i see that vi behaves the same way, btw no buffer switching mentiond, only presence of buffers in list.
It still confusing that one switching command does move marks [] to the other buffer in :args while the other switching command does not...

Pardon for disturbance!

**Comment by Shane-XB-Qian** [comment]
> It still confusing that one switching command does move marks [] to the other buffer in :args while the other switching command does not...

tho you emit `next` it would still stay that `ctrl-^` one, however `[]` moved, if that would make you understand..
// 'ctrl-^' did not change args

-- 
shane.xb.qian
