### ISSUE TITLE
[RFC]: &comments option in $VIMRUNTIME/ftplugin/{make,zimbu,sh}.vim

### ISSUE THREAD

**Issue by floand** [vim/vim#1439]
Hello,

provided that I understand Vim’s help about format of comments (`:help format-comments`) correct, the mentioned ftplugin-files in the title needs some adjustments — related to the `&comments`-option — in my opinion. As the manual said: 

> “A three-piece comment must always be given as start,middle,end, with no other parts in between.”

But currently `$VIMRUNTIME/ftplugin/{make,zimbu}.vim` defines for:
```
make.vim   -> setlocal com=sO:#\ -,mO:#\ \ ,b:#
zimbu.vim  -> setlocal comments=sO:#\ -,mO:#\ \ ,:#=,:#-,:#%,:#
```
while `$VIMRUNTIME/ftplugin/sh.vim` completely lacks a `&comments`-declaration and therefore, the less specific default will be used instead.

Remarks:

- AFAIK, Makefiles/Zimbu doesn’t support three-piece comments, see [1][2]. This is a little bit confusing to me but less important here. 
- Both files (`make.vim/zimbu.vim`) starts a three-piece comment but missing the end flag which seems to be mandatory according to the manual. This is different from all other ftplugin-files I saw.
- As in [2] mentioned, Zimbu supports some kind of in-line/stream comment. Shouldn’t this not also be reflected in `&comments`-option? 
- The ftplugin-file `sh.vim` provides settings for a very common file type and sometimes serve as a basis to other ‘pseudo’ file types by `:runtime! ftplugin/sh.vim`, see [3]. I think it should define a `&comments`-option.

Proposals:
```
make.vim   -> setlocal comments=sO:#\ -,mO:#\ \ ,exO:#/,b:#
zimbu.vim  -> setlocal comments=sO:#\ -,mO:#\ \ ,exO:#/,s:/*,m:\ ,ex:*/,:#=,:#-,:#%,:#
sh.vim     -> setlocal comments=:#
```
I’m able to handle it via personal `:help after-directory` or the FileType autocmd-event but wanted to raise it upstream and maybe reading if I’m wrong about that. 

Best regards and thanks for Vim.

References:
[1] <https://www.gnu.org/software/make/manual/html_node/Makefile-Contents.html>
[2] <http://moolenaar.net/z/zimbu/spec/zimbu.html#White%32Space%32and%32Comments_Comments>
[3] <https://github.com/gentoo/gentoo-syntax>

**Comment by brammool** [comment]
The suggested changes have been included (pending a runtime files udpate).
