### ISSUE TITLE
bracketed paste can't work in tmux

### ISSUE THREAD

**Issue by lilydjwg** [vim/vim#1441]
It works in xfce4-terminal, but doesn't in tmux in xfce4-terminal. zsh works in both situations so that it isn't tmux's fault.

According to the help, I've set the following options since it's not set by default inside tmux:
```
if &term =~ '^screen\|^tmux' && exists('&t_PS')
  let &t_BE = "\033[?2004h"
  let &t_BD = "\033[?2004l"
  let &t_PS = "\033[200~"
  let &t_PE = "\033[201~"
endif
```

Vim doesn't have `t_PS` and `t_PE` as options as the doc says. I've patched it so they are options. But it still doesn't work. Bracketed paste mode is enabled and bracketed text is sent to vim (confirmed by strace), but vim doesn't recognize, behaving like there's no bracketed mode.

My test command is:
```
src/vim -N -u .../vimrc
```

My Vim's patch level is 300.

The patch I added is:
```
diff --git a/src/option.c b/src/option.c
index b90d5fdfa..1256ae3cf 100644
--- a/src/option.c
+++ b/src/option.c
@@ -3061,6 +3061,8 @@ static struct vimoption options[] =
     p_term("t_8b", T_8B)
     p_term("t_BE", T_BE)
     p_term("t_BD", T_BD)
+    p_term("t_PS", T_PS)
+    p_term("t_PE", T_PE)

 /* terminal key codes are not in here */

```

**Comment by k-takata** [comment]
Vim has two kind of terminal options: output code options and key code options.
Currently "let &" cannot be used for key code options.
https://groups.google.com/d/msg/vim_dev/LK_EYUOGI6s/60x9RQskCwAJ

**Comment by lilydjwg** [comment]
Oh thanks! I switched to `exec` + `set` and it worked!

Key code options seem to be very special and it's not easy to notice they are different ones (both can start with `t_`).
