### ISSUE TITLE
Add Roc language filetype

### ISSUE THREAD

**Issue by nat-418** [vim/vim#14415]
[Roc](https://www.roc-lang.org/) is a fast, friendly, functional language.
Roc uses the `.roc` extension for its files. I am attempting to help make
the experience of developing Roc better by adding support for it in
various tools, and I think having Roc be automatically detected in Vim
would be useful.

**Comment by chrisbra** [comment]
No need to create a separate issue if you are going for a PR anyhow. So let me close this here in favor of #14416
