### ISSUE TITLE
Bash syntax coloring goes completely wrong if using escaped backticks like this \` in a string

### ISSUE THREAD

**Issue by burianvlastimil** [vim/vim#14428]
### Bash syntax coloring goes completely wrong if using escaped backticks like this \\` in a string

1. I open `gnome-terminal`. _Whatever way._
2. I don't know if that is relevant, so better, like me, use Bash shell _(You can run `ps` to make sure)_.
3. I create a new file with `vim` _as normal user_ (if that matters) named e.g. `test` in any directory.
4. I copy the following _problematic_ snippet from here and paste it to the file to possibly see what I am seeing below **in the expected behavior** section (low left corner on the screenshot):

```bash
#!/bin/bash

# This function coloring feels completely wrong in VIM 8.2.2121 (almost the whole function has syntax wrong)
function TestSyntax() {

    # Forbid running as root
    if [ "$(id -u)" -eq 0 ]; then
        printf >&2 '%s\n' "Please run \`alias-edit-code\` as a standard user, not as root."
        return 1
    fi

    # Forbid accepting arguments
    if [ "$#" -gt 0 ]; then
        printf >&2 '%s\n' "\`alias-edit-code\` does not accept arguments."
        return 1
    fi

    # Open Bash alias file in VS Code and wait till closes file
    code -w "$aliases_file"

    # Re-load Bash alias file to apply changes
    alias-load

}
```

### Expected behaviour

For the (Bash function) syntax to look _normal_, examples are on the following screenshot `nano` and `subl` are both Ok, `code` is a little off, but `vim` is, well, see for yourself:

![bash-aliases----OK--nano-subl--BAD-vim-code](https://github.com/vim/vim/assets/14146682/9605a795-e650-4fba-9cff-2f585b5db620)

### Version of Vim

:version  VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 14 2024 09:05:11) Included patches: 1-579, 1969, 580-1848, 4975, 5016, 5023, 5072, 2068, 1849-1854, 1857, 1855-1857, 1331, 1858, 1858-1859, 1873, 1860-1969, 1992, 1970-1992, 2010, 1993-2068, 2106, 2069-2106, 2108, 2107-2109, 2109 -3995, 4563, 4646, 4774, 4895, 4899, 4901, 4919, 213, 1840, 1846-1847, 2110-2112, 2121 Modified by team+vim@tracker.debian.org Compiled by team+vim@tracker.debian.org Huge version with GTK3 GUI.  Features included (+) or not (-): +acl               +clientserver      +diff              +folding           +langmap           +mouse_dec         +num64             +reltime           +syntax            +title             +wildmenu +arabic            +clipboard         +digraphs          -footer            +libcall           +mouse_gpm         +packages          +rightleft         +tag_binary        +toolbar           +windows +autocmd           +cmdline_compl     +dnd               +fork()            +linebreak         -mouse_jsbterm     +path_extra        +ruby              -tag_old_static    +user_commands     +writebackup +autochdir         +cmdline_hist      -ebcdic            +gettext           +lispindent        +mouse_netterm     +perl              +scrollbind        -tag_any_white     +vartabs           +X11 -autoservername    +cmdline_info      +emacs_tags        -hangul_input      +listcmds          +mouse_sgr         +persistent_undo   +signs             +tcl               +vertsplit         -xfontset +balloon_eval      +comments          +eval              +iconv             +localmap          -mouse_sysmouse    +popupwin          +smartindent       +termguicolors     +vim9script        +xim +balloon_eval_term +conceal           +ex_extra          +insert_expand     +lua               +mouse_urxvt       +postscript        +sodium            +terminal          +viminfo           +xpm +browse            +cryptv            +extra_search      +ipv6              +menu              +mouse_xterm       +printer           +sound             +terminfo          +virtualedit       +xsmp_interact ++builtin_terms    +cscope            -farsi             +job               +mksession         +multi_byte        +profile           +spell             +termresponse      +visual            +xterm_clipboard +byte_offset       +cursorbind        +file_in_path      +jumplist          +modify_fname      +multi_lang        -python            +startuptime       +textobjects       +visualextra       -xterm_save +channel           +cursorshape       +find_in_path      +keymap            +mouse             -mzscheme          +python3           +statusline        +textprop          +vreplace +cindent           +dialog_con_gui    +float             +lambda            +mouseshape        +netbeans_intg     +quickfix          -sun_workshop      +timers            +wildignore    system vimrc file: "$VIM/vimrc"      user vimrc file: "$HOME/.vimrc"  2nd user vimrc file: "~/.vim/vimrc"       user exrc file: "$HOME/.exrc"   system gvimrc file: "$VIM/gvimrc"     user gvimrc file: "$HOME/.gvimrc" 2nd user gvimrc file: "~/.vim/gvimrc"        defaults file: "$VIMRUNTIME/defaults.vim"     system menu file: "$VIMRUNTIME/menu.vim"   fall-back for $VIM: "/usr/share/vim" Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1. 0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/i nclude/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/x86_64-linux-gnu -I/usr/include/libmo unt -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wdate-time -g -O2 -ffile-prefix-map=/build/vim-RPNH56/vim-8.2.3995=. -flto=auto -ffat-lto-objects -flto=auto -ffat-l to-objects -fstack-protector-strong -Wformat -Werror=format-security -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 Linking: gcc -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -Wl,- z,now -Wl,--as-needed -o vim -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM  -lICE -lm -ltinfo -lselinux -lcanberra -lsodium -lacl -lattr -lgpm -L/usr/lib -llua5.2 -Wl,-E -fstack-protector-strong -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu/perl/5.34/CORE -lperl -ldl -lm -lpthread -lcry pt -L/usr/lib/python3.10/config-3.10-x86_64-linux-gnu -lpython3.10 -lcrypt -ldl -lm -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm -lruby-3.0 -lm -L/usr/lib

### Environment

System   = Linux Mint 21.3 64-bit (based on Ubuntu 22.04)
Terminal = gnome-terminal 3.44.0
$TERM    = xterm-256color
Shell    = bash 5.1.16

### Logs and stack traces

```shell
No logs are necessary IMHO in this case.
```

**Comment by burianvlastimil** [comment]
I have downloaded the linked file, and I am in the process of updating it on my system. Please give me a moment. Will update this post shortly. Thank you!

**Comment by chrisbra** [comment]
closing then.
