### ISSUE TITLE
typst syntax

### ISSUE THREAD

**Issue by 3052** [vim/vim#14469]
https://typst.app/docs/reference/syntax/

**Comment by 3052** [comment]
I have a start here:

~~~vim
syntax match typ_func /#\?\w\+(\@=/
highlight typ_func guifg=#4b69c6 gui=bold

syntax region typ_heading start=/^= / end=/$/
highlight typ_heading guifg=#19181f gui=bold

syntax match typ_num /\d\+%\?/
highlight typ_num guifg=#b60157

syntax region typ_raw start=/```/ end=/```/
highlight typ_raw guifg=#818181

syntax region typ_str start=/"/ end=/"/
highlight typ_str guifg=#298e0d
~~~

**Comment by chrisbra** [comment]
What kind of an issue is that?

**Comment by 3052** [comment]
I am wanting to add Typst syntax here:
https://github.com/vim/vim/tree/master/runtime/syntax

**Comment by Shane-XB-Qian** [comment]
> are you planning to remove the syntax folder?

please check #14381 there is an existing typst PR;
and check 'contribute.md' or 'https://github.com/vim/vim/discussions/13087' for the runtime files.

-- 
shane.xb.qian

**Comment by chrisbra** [comment]
> are you planning to remove the syntax folder?

No, but you still haven't explained why that would qualify as an issue of Vim. Since @kaarmu mentioned to send a pull request for typst syntax anyhow, I am closing this issue here.
