### ISSUE TITLE
:scriptencoding utf-8 gvim win32 does not work

### ISSUE THREAD

**Issue by Grueslayer** [vim/vim#1446]
Using UTF8 characters in "_vimrc" does not work under 32 bit Windows systems.

using a _vimrc like this, saved with "fileencoding=utf-8" and "bomb" enabled (the file is saved in the correct encoding and with the correct bom)

~~~vim
scriptencoding utf-8
set encoding=utf-8
set fileencodings=utf-8
set guifont=Consolas:h10
set list
set listchars=eol:↲
~~~

does not work, you'll see a reversed question mark instead of the down-left-arrow.

Using Unicode escaped chars work like a charm:

~~~vim
scriptencoding utf-8
set encoding=utf-8
set fileencodings=utf-8
set guifont=Consolas:h10
set list
let &listchars="eol:\u21b2" 
~~~

**Comment by k-takata** [comment]
`scriptencoding utf-8` must be after `set encoding=utf-8`.
This is easy to mistake.

**Comment by chrisbra** [comment]
That doesn't help unfortunately: Here is an example screenshot, after adding :scriptencoding after the set encoding line:
![screenshot](http://i.imgur.com/TSWySIu.png)
(the left side is starting from vim -u NONE -N -u vimrc.vim vimrc.vim, the right side is taking my normal customized Vim and sourcing that file.)

**Comment by k-takata** [comment]
Maybe, Consolas doesn't have a glyph for '↲'?
Vim can show '↲' when I enable DirectWrite, but cannot show it when disable DirectWrite.

**Comment by tonymec** [comment]
Which Vim version? Is it compiled with +multi_byte (as shown by :version)?

Under Linux (L64 and L32 before that), it works for me, and that's been a long time (since gvim 6.1 IIRC, and at that time I used W32/L32 double-boot).

The very first line in my .vimrc is

    scriptencoding utf-8

but I suppose it doesn't make much of a difference since my system locale sets LC_CTYPE=en_US.UTF-8
A little later I have

    if has('multi_byte')
      if &enc !~? '^u'
        if &tenc == ''
          let &tenc = &enc
        endif
        set enc=utf-8
      endif
      set fencs='ucs-bom,utf-8,latin1'
      setg fenc=utf-8 bomb
      " beware: setting bomb is "wrong" on any script starting with a #! shebang  
    endif

and much lower down

    if exists('+list')
      set list
      if exists('+listchars')
        set lcs=eol:¶,tab:\|_,extends:>,precedes:<,conceal:*,nbsp:·
      endif
    endif

The Pilcrow sign is U+00B6 and the raised dot is U+00B7, both of which are two-byte UTF-8 strings (hex C2 B6 and C2 B7 respectively), and that's what I see for ends-of-lines and no-break spaces respectively. My .vimrc is encoded as UTF-8 without BOM, BTW.

I think that what is important is to set 'encoding' first and 'listchars' (and any option including any codepoint above U+007F) only afterwards.

Best regards,
Tony.

**Comment by k-takata** [comment]
> The very first line in my .vimrc is

It works only if the default 'encoding' value is 'utf-8'.
On Windows, the default value depends on the current code page and it is not 'utf-8'.
`:scriptencoding` converts the script to 'encoding', so the script will be converted wrongly to the current code page.

**Comment by k-takata** [comment]
I think this should be mentioned in the help like this:

```diff
--- a/runtime/doc/repeat.txt
+++ b/runtime/doc/repeat.txt
@@ -305,6 +305,11 @@ For writing a Vim script, see chapter 41
 			Mark) in utf-8 format Vim will recognize it, no need
 			to use ":scriptencoding utf-8" then.
 
+			If you set the 'encoding' option in your |.vimrc|,
+			`:scriptencoding` must be placed after that. E.g.: >
+				set encoding=utf-8
+				scriptencoding utf-8
+<
 			When compiled without the |+multi_byte| feature this
 			command is ignored.
 			{not in Vi}
```

**Comment by chrisbra** [comment]
I think you are right, it's renderoptions that makes the difference.

**Comment by Grueslayer** [comment]
Okay... rereading the manual after your comments helps.... file will be converted to the current encoding (for windows on the current codepage for non unicode apps). The content is not "processed" in the current encoding, it is really "converted" and everything not available is lost. Changing "encoding" converts it to the given encoding (with information still lost). BUT there must be somewhere the original version in memory, because setting encoding first and scriptencoding second everything seems fine.

**Comment by tonymec** [comment]
Notice the following:

 			When conversion isn't supported by the system, there
			is no error message and no conversion is done.  When a
			line can't be converted there is no error and the
			original line is kept.

    [...]

			When a sourced script starts with a BOM (Byte Order
			Mark) in utf-8 format Vim will recognize it, no need
			to use ":scriptencoding utf-8" then.

So:
- What cannot be converted is not lost, it is kept unchanged;
- If there is a BOM (which necessarily comes before everything else) there is no need for a :scriptencoding statement.

My guess is that (a) :scriptencoding and/or BOM, and (b) :set encoding=utf-8, can appear in any order as long as they are both before the first use (other than in a comment or as the BOM itself) of a codepoint higher than U+007F. Call it an educated guess. If I'm mistaken, I hope that Bram will correct me.

Best regards,
Tony.

**Comment by k-takata** [comment]
No, the order of (a) and (b) really matters (especially on Windows).
For example, on Japanese Windows the default encoding is `cp932`, so:

```vim
scriptencoding utf-8   " This sets up conversion from utf-8 to cp932.
                       " (The script will be coverted line by line.)

set encoding=utf-8     " This doesn't change the setting of conversion.
                       " The rest of the lines will be still converted from
		       " utf-8 to cp932.

set listchars=eol:↲    " Using a character higher than U+007F here. '↲' is
                       " converted from utf-8 to cp932, but cp932 cannot
		       " represent the character. So it is converted to '?'.
		       " Then the converted line will be interpreted as utf-8.
```

Using BOM has the same effect as putting the line `scriptencoding utf-8` on
the top of the file. So using BOM on `.vimrc` is useless.
Once 'encoding' is set in `.vimrc`, BOMs and `scriptencoding` will work as
expected.

**Comment by chrisbra** [comment]
i think the documentation change from Ken has been included. Closing.
