### ISSUE TITLE
 There is a memory leak defect at line 3409 in the file /vim/src/autocmd.c.

### ISSUE THREAD

**Issue by LuMingYinDetect** [vim/vim#14474]
### Steps to reproduce

1.A pointer named pat is defined at line 3307 in the file /vim/src/autocmd.c. This pointer is assigned the return value of the function dict_get_string at line 3372, as shown in the following illustration:
https://github.com/LuMingYinDetect/vim_defects/blob/main/vim_20.png

2.A pointer named s is defined at line 690 in the function dict_get_string. This pointer is assigned the return value of the function vim_strsave at line 697 and returned at line 698, as shown in the following illustration:
https://github.com/LuMingYinDetect/vim_defects/blob/main/vim_21.png

3.Dynamic memory allocation is performed using the alloc function at line 27 in the vim_strsave function. This allocated memory block is then returned at line 30, as depicted in the following illustration:
https://github.com/LuMingYinDetect/vim_defects/blob/main/vim_22.png

4.After the execution of the dict_get_string function, pat is assigned a dynamically allocated memory block. When the if statement at line 3373 returns false, it confirms that the allocation of the dynamic memory block pointed to by pat was successful. However, when the if statement at line 3407 returns true, the program returns at line 3409, thus skipping the release operation of the dynamic memory block pointed to by the pat pointer at line 3429. This situation constitutes a memory leak, as illustrated in the following diagram:
https://github.com/LuMingYinDetect/vim_defects/blob/main/vim_23.png

5.The if statement at line 3411 also suffers from the same issue.

### Expected behaviour

If the memory leak is not a false positive, it is advisable to fix it.

### Version of Vim

9.1.0296

### Environment

Ubuntu 20.04

**Comment by chrisbra** [comment]
I think this was fixed
