### ISSUE TITLE
9.1.0296 completely breaks syntax highlighting of &ft=mail

### ISSUE THREAD

**Issue by chdiza** [vim/vim#14487]
### Steps to reproduce

Build 9.1.0296 from source.  Open a file with &ft=mail that has some header lines in it.  E.g., start composing a mail in `mutt`, or open a blank file, set the &ft, and write:
```
From: someaddress
To: someotheraddress
```

Observe that nothing in the buffer is highlighted except for email addresses and email-quoted text.  This is wrong; on 9.1.0295 and earlier, the header names are highlighted.

If I put the cursor on the "From:" and do this:
```
echo synIDattr(synID(line("."), col("."), 1), "name")
```
I get nothing at all in 9.1.0296, but it shows `mailHeaderKey` in 9.1.0295 and earlier.

Depending on which email message I'm looking at, I can also see that highlighting of quoted-printable blocks that are being "> "-quoting is also broken.

### Expected behaviour

I expect mail highlighting to not be such as to highlight nearly no text at all.

### Version of Vim

9.1.0296

### Environment

Linut Mint 21.x
Terminal: Kitty

**Comment by Shane-XB-Qian** [comment]
um.. interesting, is it related to locale or encoding something? i replied some mail today, why i did not face same problem, :sweat_smile:

**Comment by chdiza** [comment]
I have limited time to hunt down details today, but the problem at least partly disappears if I set `&re=2`.

I have also identified that with &re=1, the `:g` command is broken.  E.g., this type of thing `doesn't` work anymore even though it did one patchlevel earlier:
```
:g/\cSIZ/d
```

No unicode characters there, or in the file in which I try to make that deletion.
