### ISSUE TITLE
--prefix dont work

### ISSUE THREAD

**Issue by nda-cunh** [vim/vim#14494]
### Steps to reproduce
/!\ pkgdir is not empty it is equal to 
/nfs/homes/nda-cunh/Desktop/script-suprapack/vim/pkg
```
i download `https://github.com/vim/vim/archive/refs/tags/v9.1.0304.tar.gz`
make distclean
./configure --prefix=$pkgdir/usr --bindir=bin --libdir=lib
make -j
make install
```

### Expected behaviour

all workd but
```
cp vim /usr/local/bin
cp: cannot create regular file '/usr/local/bin/vim': Permission denied
```
force install to /usr/local/bin

### Version of Vim

9.1.0304

### Environment

zsh linux 86_64 ubuntu 22

**Comment by k-takata** [comment]
Normally you need to use `sudo` to run `make install` (i.e. `sudo make install`).

**Comment by chrisbra** [comment]
closing as not a Vim issue.

**Comment by k-takata** [comment]
Hmm, did I misunderstand this?
Did you specify `--prefix` with a directory other than `/usr/local/` but vim is installed to `/usr/local/`?

**Comment by k-takata** [comment]
> `./configure --prefix=$pkgdir/usr --bindir=bin --libdir=lib`

This command shows an error:
```
configure: error: expected an absolute directory name for --bindir: bin
```
