### ISSUE TITLE
VIM9: vimrc in vim9script gives E1072 for "&t_Co > 2"

### ISSUE THREAD

**Issue by stipplehatch** [vim/vim#14493]
### Steps to reproduce

For a new VIM installation (else replace `~/.vimrc`).
1. Edit `vimrc_example.vim` found in `$VIMRUNTIME` to use vim9script:
   a. Add `vim9script` as the first  line.
   b. Change comments—replace `"` with `#`.
   c. Include whitespace where needed, e.g. for "=" in ` textwidth = 78`
2. Write/save to `~\.vimrc`
3. Exit and start vim from the shell. Or start a new instance in another terminal window:

```
$ vim
Error detected while processing /home/debnoob/.vimrc:
line   26:
E1072: Cannot compare string with number
Press ENTER or type command to continue
``` 
Line 26 in vimrc_example and the new, modified vimrc:
```
26 if &t_Co > 2 || has("gui_running")
27  # Switch on highlighting the last used search pattern.
28  set hlsearch
29 endif
```
4. Removing `if &t_Co > 2 || ` eliminates the problem, and VIM starts without error.

### Expected behaviour

VIM starts without errors, as before, when the exact same vimrc was used with the default/older vim-script syntax.

### Version of Vim

9.0.1499

### Environment

OS: Debian 12 stable
Terminal: Konsole
`$TERM`: `xterm-256color`
Shell: Bash

**Comment by errael** [comment]
Note the error you are getting
```
E1072: Cannot compare string with number
```
You can do
```
if str2nr(&t_Co) > 2
```
I don't see what the textwidth issue is about.

**Comment by RestorerZ** [comment]
I also checked this on my Vim 9.1.0296 build.
And the data types for both "&t_Co > 2" and "has("gui_running")" are numbers.
```
:echo type(&t_Co > 2)
```
```
:echo type(has("gui_running"))
```
It is possible that an old version of Vim is to blame, as I remember there were several fixes for data types.

**Comment by errael** [comment]
The type of "&t_Co" is string

```
vim9script

var x = &t_Co
echo typename(x)

if x > 2
endif
```
```
string
E1072: Cannot compare string with number
```

**Comment by stipplehatch** [comment]
> Note the error you are getting
> 
> ```
> E1072: Cannot compare string with number
> ```
> 
> You can do
> 
> ```
> if str2nr(&t_Co) > 2
> ```
> 
> I don't see what the textwidth issue is about.

Fixed with str2nr().
There was no textwidth issue. Had added spaces around the "=" as per the changes in the manual.
Thanks a lot!

**Comment by RestorerZ** [comment]
> string
> E1072: Cannot compare string with number

Oh, yeah, that's right!
And I was checking the expression "&t_Co > 2"..... But there is a comparison operation here too.
I'll be more careful.
