### ISSUE TITLE
command-block limitations 

### ISSUE THREAD

**Issue by balki** [vim/vim#14491]
### Steps to reproduce

Found below limitations when translating functions to command-block

1. No return statement allowed. E.g.
```
command Foo {
if someCond() | return | endif
// do something 
}
```

2. let-heredoc are not allowed.
```
command Foo {             
    const abc =<< trim END
        hello world       
        blah blah         
    END                   
    echo abc              
}                         
Foo
# E488: Trailing characters:         hello world^@       ...
```

### Expected behaviour

Fix the limitations or add the limitations to docs. 

### Version of Vim

9.1.252

### Environment

ArchLinux

**Comment by benknoble** [comment]
What should return do? It wouldn’t be valid in a normal command block.

It would probably be nice to support heredocs though.

**Comment by chrisbra** [comment]
yeah, return is strange. commands are basically nice and simple ways to execute functions. Thus I would argue the desired logic belongs into a function.

**Comment by balki** [comment]
return does not have to return anything to called. But useful as a control flow to stop the command execution to avoid nesting. Creating a wrapper function is not bad but it is unnecessary boiler plate if the function is called in only once which is in the command definition. I think the behavior should at-least be documented.

**Comment by chrisbra** [comment]
`:return` does not make sense in an interactive session (which is basically the same what `:com` does). I also think there is nothing to document at least not for the `:return` case.

And btw: you can always negate the condition.

**Comment by chrisbra** [comment]
Yes, let's leave this ticket for the missing heredoc functionality.
