### ISSUE TITLE
syntax highlighting does not work after the 3000th column in a line of all languages

### ISSUE THREAD

**Issue by ghost** [vim/vim#1450]
On windows(maybe others do so), for any file in any language, if one line has more than 3000 character(text inserted or open an exists file), then the chars after 3000th column will not be syntax highlighting although they have to be. Such as writing a large const integer array in C or Python, the numbers inside are highlighting before 3000th col but after it everything is not highlighting.

Here is the version info

	VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov  6 2016 17:20:44)
	MS-Windows 32 bit图形界面版本 带 OLE 支持
	Included patches: 1-69
	Compiled by mool@tororo
	Huge version 带图形界面。  Features included (+) or not (-):
	+acl                +cmdline_hist       -dnd                +gettext/dyn        +listcmds           +num64              +reltime            -tag_any_white      +visual
	+arabic             +cmdline_info       -ebcdic             -hangul_input       +localmap           +ole                +rightleft          +tcl/dyn            +visualextra
	+autocmd            +comments           +emacs_tags         +iconv/dyn          -lua                +packages           +ruby/dyn           -termguicolors      +viminfo
	+balloon_eval       +conceal            +eval               +insert_expand      +menu               +path_extra         +scrollbind         -tgetent            +vreplace
	+browse             +cryptv             +ex_extra           +job                +mksession          +perl/dyn           +signs              -termresponse       +wildignore
	++builtin_terms     +cscope             +extra_search       +jumplist           +modify_fname       +persistent_undo    +smartindent        +textobjects        +wildmenu
	+byte_offset        +cursorbind         +farsi              +keymap             +mouse              -postscript         +startuptime        +timers             +windows
	+channel            +cursorshape        +file_in_path       +lambda             +mouseshape         +printer            +statusline         +title              +writebackup
	+cindent            +dialog_con_gui     +find_in_path       +langmap            +multi_byte_ime/dyn +profile            -sun_workshop       +toolbar            -xfontset
	+clientserver       +diff               +float              +libcall            +multi_lang         +python/dyn         +syntax             +user_commands      -xim
	+clipboard          +digraphs           +folding            +linebreak          -mzscheme           +python3/dyn        +tag_binary         +vertsplit          +xpm_w32
	+cmdline_compl      +directx            -footer             +lispindent         +netbeans_intg      +quickfix           +tag_old_static     +virtualedit        -xterm_save
	     system vimrc file: "$VIM\vimrc"
	     user vimrc file: "$HOME\_vimrc"
	 2nd user vimrc file: "$HOME\vimfiles\vimrc"
	 3rd user vimrc file: "$VIM\_vimrc"
	      user exrc file: "$HOME\_exrc"
	  2nd user exrc file: "$VIM\_exrc"
	    system gvimrc file: "$VIM\gvimrc"
	    user gvimrc file: "$HOME\_gvimrc"
	2nd user gvimrc file: "$HOME\vimfiles\gvimrc"
	3rd user gvimrc file: "$VIM\_gvimrc"
	       defaults file: "$VIMRUNTIME\defaults.vim"
	        system menu file: "$VIMRUNTIME\menu.vim"
	Compilation: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL   -DFEAT_XPM_W32   -DWINVER=0x0501 -D_WIN32_WINNT=0x0501  /Fo.\ObjGXOLYHTRi386/ /Ox /GL -DNDEBUG  /Zl /MT -DFEAT_OLE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DFEAT_GUI_W32 -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl86.dll\" -DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python35.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl524.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_VER=22 -DDYNAMIC_RUBY_DLL=\"msvcrt-ruby220.dll\" -DFEAT_HUGE /Fd.\ObjGXOLYHTRi386/ /Zi
	Linking: link /RELEASE /nologo /subsystem:windows /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib uuid.lib /machine:i386 gdi32.lib version.lib   winspool.lib comctl32.lib advapi32.lib shell32.lib  /machine:i386 /nodefaultlib libcmt.lib oleaut32.lib user32.lib     /nodefaultlib:python27.lib /nodefaultlib:python35.lib   "E:\tcl\lib\tclstub86.lib" WSock32.lib xpm\x86\lib\libXpm.lib /PDB:gvim.pdb -debug

**Comment by chrisbra** [comment]
`:h 'synmaxcol'`. Please ask user questions on the appropriate forums. Thanks

**Comment by atav32** [comment]
@chrisbra which forums do you recommend?

**Comment by chrisbra** [comment]
vi.stackexchange.com or vim-use mailinglist.

**Comment by tonymec** [comment]
This question belongs indeed on the vim_use mailing list.

I'll drop a hint, however: `:help 'synmaxcol'`

Best regards,
Tony.
