### ISSUE TITLE
E340 + E341 Internal Error

### ISSUE THREAD

**Issue by rickhowe** [vim/vim#14525]
### Steps to reproduce

`vim --clean`
`:echo matchaddpos('Error', [])`

Then:

```
E340: Internal error; if you can reproduce please report a bug
E341: Internal error; lalloc(0, )
```

### Expected behaviour

echo a match id.

### Version of Vim

9.1 and latest 9.1.0309, but works well on 9.0.

### Environment

Windows 10

**Comment by k-takata** [comment]
[v9.0.0620](https://github.com/vim/vim/commit/50faf02f43d7f1a56ec2023028fca7c72dbce83e) might be related?
Not sure if specifying an empty array is a valid usage, though.

**Comment by zeertzjq** [comment]
A NULL list is handled, so maybe it makes sense for an empty list to behave like a NULL list.

**Comment by zeertzjq** [comment]
Meanwhile:
- `matchaddpos('Error', test_null_list())` returns `-1`.
- Before patch 9.0.0620, `matchaddpos('Error', [])` returned a match ID.

**Comment by chrisbra** [comment]
probably something like this:
```diff
diff --git a/src/match.c b/src/match.c
index f59c2066a..bc50757b3 100644
--- a/src/match.c
+++ b/src/match.c
@@ -87,7 +87,7 @@ match_add(
     m = ALLOC_CLEAR_ONE(matchitem_T);
     if (m == NULL)
        return -1;
-    if (pos_list != NULL)
+    if (pos_list != NULL && pos_list->lv_len > 0)
     {
        m->mit_pos_array = ALLOC_CLEAR_MULT(llpos_T, pos_list->lv_len);
        if (m->mit_pos_array == NULL)
@@ -1294,7 +1294,7 @@ f_matchaddpos(typval_T *argvars UNUSED, typval_T *rettv UNUSED)
        return;
     }
     l = argvars[1].vval.v_list;
-    if (l == NULL)
+    if (l == NULL || l->lv_len == 0)
        return;

     if (argvars[2].v_type != VAR_UNKNOWN)
```
