### ISSUE TITLE
.astro file extension is not recognised

### ISSUE THREAD

**Issue by pheiduck** [vim/vim#14558]
### Steps to reproduce

1. open any file which ends with **.astro**
2. see, no syntax highlighting

### Expected behaviour

**.astro** files are recognised by vim.
I found a Plugin but upstream support would be nicer:
https://github.com/wuelnerdotexe/vim-astro

### Version of Vim

9.1.0300

### Environment

- macos 14.4.1
- iTerm
- xterm-256color
- zsh 5.9

**Comment by chrisbra** [comment]
closing this for #14561
