### ISSUE TITLE
gvimrc is not sourced from `~/.config/vim/`

### ISSUE THREAD

**Issue by habamax** [vim/vim#14567]
### Steps to reproduce

1. have ~/.config/vim/gvimrc with setting of guifont
2. run `gvim`

### Expected behaviour

Font settings should be applied.

Looks like `gvimrc` is not sourced at all.

![image](https://github.com/vim/vim/assets/234774/1663195e-3e74-443e-ac23-0f61bf51f734)

### Version of Vim

9.1.336

### Environment

debian 12

**Comment by habamax** [comment]
if I copy `cp -r ~/.config/vim ~/.vim` then `gvimrc` is sourced:

![image](https://github.com/vim/vim/assets/234774/df8e67af-366c-4371-9d68-c0a2d2a27e37)

otherwise, nope:

![image](https://github.com/vim/vim/assets/234774/475e92e5-4e02-4cd1-a64a-5d9f3040a1f3)

**Comment by chrisbra** [comment]
Yes, it seems we need to define a `USR_GVIMRC_FILE5` and then use it here: https://github.com/vim/vim/blob/2da68c8b61286ed347076718b66028f7251c8cdf/src/gui.c#L571-L588
