### ISSUE TITLE
One issue with XDG_CONFIG_HOME/vim/vimrc after merging, using symlinks #14182

### ISSUE THREAD

**Issue by michalsieron** [vim/vim#14597]
### Steps to reproduce

Preparation:
1. Have ~/.config/vim/vimrc with content
    ```vim
   call foo#hello()
   ```
1. Make a symlink at ~/.vimrc pointing to ~/.config/vim/vimrc
1. Define `foo#hello()` in `~/.vim/autoload/foo.vim`
   ```vim
   function foo#hello()
       echo "hello :)"
   endfunction
   ```

Now, what I managed to find about the bug:
1. Vim is not able to autoload `foo.vim` as it is in XDG mode (or whatever it is called).
2. However, it doesn't come from the file being a symlink.
3. It is because https://github.com/saccarosium/vim/blob/a2a413e2b51a28cb07c3ab7d538e29c3561a4db8/src/option.c#L387 doesn't actually expand `$HOME/.vimrc`. It stays unexpanded.
4. Because of that, https://github.com/saccarosium/vim/blob/a2a413e2b51a28cb07c3ab7d538e29c3561a4db8/src/option.c#L399, says the file is unreadable and because the XDG path is readable it selects the latter.
5. So if the symlink was pointing to any other location, I would not encounter this bug.
6. Now, what if `~/.vimrc` is not a symlink? Then it works correctly. But why?
7. Even though here `expand_env_save` fails to expand the variable, for some reason it succeeds later when called by `do_source` in https://github.com/saccarosium/vim/blob/a2a413e2b51a28cb07c3ab7d538e29c3561a4db8/src/main.c#L3273.

### Expected behaviour

Vim sees `~/.vimrc` before `~/.config/vim/vimrc` and even when the former is a symlink to the latter, it doesn't enter XDG mode.

### Version of Vim

v9.1.0356

### Environment

OS: Arch Linux

**Comment by michalsieron** [comment]
Let me mention #14182 so GitHub links it

**Comment by michalsieron** [comment]
I also forgot to mention that this change "fixes" the first bug: https://github.com/vim/vim/pull/14182/files#r1530804014

For some reason, in such case it does get expanded.

**Comment by chrisbra** [comment]
Wait for the second problem, I don't get this. `concat_fnames()` allocates memory. That memory is then pointed to by `vimrc_xdg`, which is always being freed at the end label. So how would the leak happen then?

For the first point, I'll have a look later in more detail.

**Comment by michalsieron** [comment]
@chrisbra you are right. It seems I somehow mixed variable names and thought that `xdg_dir` and `vimrc_xdg` are the same. And on top of that, I missed that they both have corresponding free at the end.

I will edit the issue text, so only description of the first problem remains.

**Comment by michalsieron** [comment]
Ok, I here are updated steps for reproducing the bug:

### Steps to reproduce

For debugging purposes, I used good old `printf`:
```diff
diff --git a/src/misc1.c b/src/misc1.c
index c5a0c3852..03ef88f53 100644
--- a/src/misc1.c
+++ b/src/misc1.c
@@ -1372,8 +1372,10 @@ expand_env_save_opt(char_u *src, int one)
     char_u	*p;
 
     p = alloc(MAXPATHL);
+    printf("BEFORE: %s\n", src);
     if (p != NULL)
 	expand_env_esc(src, p, MAXPATHL, FALSE, one, NULL);
+    printf("AFTER: %s\n", p);
     return p;
 }
 
diff --git a/src/option.c b/src/option.c
index 1bb9e29ba..c0cd8772a 100644
--- a/src/option.c
+++ b/src/option.c
@@ -397,8 +397,12 @@ set_init_xdg_rtp(void)
     vimrc_xdg = concat_fnames(xdg_dir, (char_u *)"vim/vimrc", TRUE);
 
     if (file_is_readable(vimrc1) || file_is_readable(vimrc2) ||
-	    !file_is_readable(vimrc_xdg))
+	    !file_is_readable(vimrc_xdg)) {
+	printf("Non-XDG mode\n");
 	goto theend;
+    }
+
+    printf("XDG mode\n");
 
     xdg_rtp = has_xdg_env ? (char_u *)XDG_RUNTIMEPATH
 	: (char_u *)XDG_RUNTIMEPATH_FB;
```

1. Compile vim with the patch above and **with `XDG_CONFIG_HOME` unset**!
1. Have `~/.config/vim/vimrc` with content
    ```vim
   echo "XDG"
   ```
1. Have `~/.vimrc` with content
    ```vim
   echo "home"
   ```
1. Now if you run your freshly compiled vim, you should see something like this
   ```
    $ ./src/vim
    BEFORE: $HOME/.vimrc
    AFTER: $HOME/.vimrc
    BEFORE: ~/.vim/vimrc
    AFTER: /home/michal/.vim/vimrc
    BEFORE: ~/.config
    AFTER: /home/michal/.config
    XDG mode
    BEFORE: $VIM/vimrc
    AFTER: /usr/local/share/vim/vimrc
    BEFORE: $HOME/.vimrc
    AFTER: /home/michal/.vimrc
    home
    Press ENTER or type command to continue
   ```
1. If you now press enter and run `:set runtimepath?` you will see it was altered for XDG mode.


So the issue is really about Vim's `runtimepath` not matching `vimrc` that was actually loaded.

**Comment by chrisbra** [comment]
Okay I see what is happening. `expand_env_esc()` depends on `didset_options()` which initializes `init_chartab()`. This is required for `expand_env_esc()` to work properly, because it detemines environment variables by using the 'isident' option value, which currently at the time of `expand_env_save()` inside `set_init_xdg_rtp()` does not work yet.

So we may need something like this:
```diff
diff --git a/src/option.c b/src/option.c
index 1bb9e29ba..dbc627141 100644
--- a/src/option.c
+++ b/src/option.c
@@ -383,7 +383,14 @@ set_init_xdg_rtp(void)
     char_u     *xdg_dir = NULL;
     char_u     *xdg_rtp = NULL;
     char_u     *vimrc_xdg = NULL;
+    static int  init_charset = FALSE;

+    if (!init_charset)
+    {
+       // required to expand $HOME
+       (void)init_chartab();
+       init_charset = TRUE;
+    }
```

**Comment by michalsieron** [comment]
@chrisbra I can confirm it does work with your patch applied
