### ISSUE TITLE
Test_let_termcap failure since 8.0.0302

### ISSUE THREAD

**Issue by mbakke** [vim/vim#1459]
`make test` fails on GNU Guix since e353c402e63b9b0a0bc06acf390e352d9e7eeaeb. This was fixed in 8.0.0304 (1fb0d49803b4f57025ed6a43b1f5b9eb91524645) for Travis CI, but the problem persists in Guix.

Excerpt from build log:

```
Found errors in Test_let_termcap():
Caught exception in Test_let_termcap(): Vim(let):E113: Unknown option: t_k1 @ function RunTheTest[21]..Test_let_termcap, line 9
```

**Comment by chrisbra** [comment]
what terminal is this? Perhaps it doesn't know the f1 key? Can you try this patch:
```patch
diff --git a/src/testdir/test_assign.vim b/src/testdir/test_assign.vim
index 4a4c644cf..f40ff6b35 100644
--- a/src/testdir/test_assign.vim
+++ b/src/testdir/test_assign.vim
@@ -15,7 +15,7 @@ func Test_let_termcap()
   call assert_match('t_te.*^[[yes;', execute("set termcap"))
   let &t_te = old_t_te

-  if !has('gui_running')
+  if exists("+t_k1")
     " Key code
     let old_t_k1 = &t_k1
     let &t_k1 = "that"
```

**Comment by mbakke** [comment]
That patch indeed makes the tests pass in the Guix build environment.

The test suite is run non-interactively with no controlling `TERM` or terminfo/termcap files.

It succeeds when I run it interactively from an X11 environment through `runtest.vim`.

**Comment by chrisbra** [comment]
posted a proper patch [here](https://groups.google.com/d/msg/vim_dev/cE98pnuPEdM/dWQgl6XmDQAJ)
