### ISSUE TITLE
err: Test_terminal_vt420

### ISSUE THREAD

**Issue by Shane-XB-Qian** [vim/vim#14595]
### Steps to reproduce

Q:
```
Test_terminal_vt420[10]..WaitForAssert[2]..<SNR>4_WaitForCommon[11]..<lambda>152 line 1: Pattern 't_xo=y' does not match
```

A:
```log
'vt420' not known. Available builtin terminals are:
    builtin_ansi
    builtin_vt320
    builtin_vt52
    builtin_xterm
    builtin_iris-ansi
    builtin_pcansi
    builtin_win32
    builtin_amiga
    builtin_dumb
    builtin_debug
```

#14542 @ant0sha

### Expected behaviour

no err

### Version of Vim

9.1.354

### Environment

linux

**Comment by zeertzjq** [comment]
The error message in the `Q:` part seem incomplete.

**Comment by Shane-XB-Qian** [comment]
> The error message in the `Q:` part seem incomplete.

no, just `Not found in termcap: term=vt420`

-- 
shane.xb.qian

**Comment by chrisbra** [comment]
So where is your terminfo? do you have vt420 in there?

**Comment by jamessan** [comment]
You may need to install an additional package to get the vt420 term definition (e.g., in Debian it's the ncurses-term package).

**Comment by Shane-XB-Qian** [comment]
> You may need to install an additional package to get the vt420 term definition (e.g., in Debian it's the ncurses-term package).

oh, thanks, yes, but the point was the test may need to check vt420 if was there, which made it be more robust, it would be ran not only at current CI.
// this was a message to author of https://github.com/vim/vim/pull/14542 @ant0sha

-- 
shane.xb.qian

**Comment by chrisbra** [comment]
Hm, but `ncurses-term` depends on `ncurses-base` which is an essential package. So I would think one can expect it to be there. In any case, I don't think it makes sense to keep this issue open.

**Comment by Shane-XB-Qian** [comment]
> Hm, but `ncurses-term` depends on `ncurses-base` which is an essential package. So I would think one can expect it to be there. In any case, I don't think it makes sense to keep this issue open.

`ncurses-base` was an essential package, but `ncurses-term` looks not,
so this test potentially would be failed, specially the test specifically was for vt420.

-- 
shane.xb.qian

**Comment by chrisbra** [comment]
yes, but it depends on an essential package. Unless you mess with the dependencies, you should have it. In any case, it seems like an issue with that particular environment

**Comment by Shane-XB-Qian** [comment]
as James said it is an additional package in debain, it should be same as Ubuntu, which default it did not have vt420.
so if that code of that test would check if it had vt420 there firstly should be more robust.
// or you had to assume everyone would install nucurs-term.

--
shane.xb.qian

**Comment by jamessan** [comment]
> yes, but it depends on an essential package. Unless you mess with the dependencies, you should have it.

You have it reversed.  ncurses-base is essential, so it will be installed. ncurses-term provides additional, less frequently needed definitions, so it may not be installed.

Not sure if there's a better way to check for the term definition (or how portable it is, especially on the BSDs), but one possibility is to only run the test if `infocmp vt420` has a successful exit status.

**Comment by chrisbra** [comment]
> You have it reversed.

Indeed. 

So I guess we need something along those lines here:
```diff
diff --git a/src/testdir/test_terminal3.vim b/src/testdir/test_terminal3.vim
index 223bcc537..588a9e010 100644
--- a/src/testdir/test_terminal3.vim
+++ b/src/testdir/test_terminal3.vim
@@ -935,6 +935,12 @@ func Test_terminal_vt420()
   CheckRunVimInTerminal
   " For Termcap
   CheckUnix
+  let a = system('infocmp vt420')
+  if v:shell_error
+    throw 'Skipped: vt420 terminfo not available'
+    " reset v:shell_error
+    let a=system('true')
+  endif
   let rows=15
   call writefile([':set term=vt420'], 'Xterm420', 'D')

```

**Comment by Shane-XB-Qian** [comment]
thanks very much.
// just not sure if BSD had `infocmp`, otherwise seems good.

--
shane.xb.qian
