### ISSUE TITLE
Test_getcmdtype() fails with --enable-gui since 8.0.0314

### ISSUE THREAD

**Issue by mbakke** [vim/vim#1460]
Since commit 65189a1294307abf007faab7385dc0145ba72b06, `make test` fails on GNU Guix when using `--enable-gui`.

```
From test_cmdline.vim:
Found errors in Test_getcmdtype():
function RunTheTest[21]..Test_getcmdtype[15]..Check_cmdline line 1: Expected 'MyCmd a' but got ''
function RunTheTest[21]..Test_getcmdtype[15]..Check_cmdline line 2: Expected 8 but got 0
function RunTheTest[21]..Test_getcmdtype[15]..Check_cmdline line 3: Expected '@' but got ''
```

**Comment by vim-ml** [comment]
Hi,

On Thu, Feb 9, 2017 at 12:43 PM, Marius Bakke <vim-dev-github@256bit.org> wrote:
> Since commit 65189a1, make test fails on GNU Guix when using --enable-gui.
>
> From test_cmdline.vim:
> Found errors in Test_getcmdtype():
> function RunTheTest[21]..Test_getcmdtype[15]..Check_cmdline line 1: Expected
> 'MyCmd a' but got ''
> function RunTheTest[21]..Test_getcmdtype[15]..Check_cmdline line 2: Expected
> 8 but got 0
> function RunTheTest[21]..Test_getcmdtype[15]..Check_cmdline line 3: Expected
> '@' but got ''
>

The test related to the input() function is failing. Are you using GUI
Vim or terminal Vim?
Can you try manually running the following command in Vim?

   :call input("Answer? ")

Do you get the input prompt?  If you get the input prompt, can you
press <CTRL-R>=
and then enter the "getcmdtype()" expression and press <CR>. Do you see "@"
after doing the above?

Thanks,
Yegappan

**Comment by mbakke** [comment]
> Can you try manually running the following command in Vim?
> 
>   :call input("Answer? ")
> 
> Do you get the input prompt?  If you get the input prompt, can you
> press <CTRL-R>=
> and then enter the "getcmdtype()" expression and press <CR>. Do you see "@"
> after doing the above?

Hi Yegappan,

Thanks for the detailed response. The "@" symbol is inserted after doing the above steps in both `vim` and `gvim` version 8.0.0324. Strangely the test failure only occurs when built with most optional features and dependencies, not the minimal set (default configure flags).

**Comment by jonathonf** [comment]
Just to confirm the issue, I'm getting the same failure building for Ubuntu (14.04&16.04).

Most recent failed build log: https://launchpad.net/~jonathonf/+archive/ubuntu/vim-staging/+build/11994612/+files/buildlog_ubuntu-xenial-amd64.vim_2%3A8.0.0325-0york1~16.04_BUILDING.txt.gz

All failed build logs: https://launchpad.net/~jonathonf/+archive/ubuntu/vim-staging/+builds?build_text=&build_state=failed

No issues with Arch's enabled features, though (https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/vim).

**Comment by vim-ml** [comment]
Hi Marius,

On Fri, Feb 10, 2017 at 2:22 PM, Marius Bakke <vim-dev-github@256bit.org> wrote:
> Can you try manually running the following command in Vim?
>
> :call input("Answer? ")
>
> Do you get the input prompt? If you get the input prompt, can you
> press =
> and then enter the "getcmdtype()" expression and press . Do you see "@"
> after doing the above?
>
> Hi Yegappan,
>
> Thanks for the detailed response. The "@" symbol is inserted after doing the
> above steps in both vim and gvim version 8.0.0324. Strangely the test
> failure only occurs when built with most optional features and dependencies,
> not the minimal set (default configure flags).
>

Which optional Vim features are you enabling?

Thanks,
Yegappan

**Comment by mbakke** [comment]
> Which optional Vim features are you enabling?

We're using these configure flags:

             "--with-features=huge"
             "--enable-python3interp=yes"
             "--enable-perlinterp=yes"
             "--enable-rubyinterp=yes"
             "--enable-tclinterp=yes"
             "--enable-luainterp=yes"
             "--enable-cscope"
             "--enable-multibyte"
             "--enable-xim"
             "--disable-selinux"
             "--enable-gui"

I've tried toggling different options and narrowed it down to `--enable-gui` (gtk2).

**Comment by mbakke** [comment]
@jonathonf What is your build environment like? Do you know if Arch has proper isolation from the host system? I wonder if we're missing something in the build chroot.

But then, these tests pass when not building for GTK.

**Comment by jonathonf** [comment]
Using [Manjaro's build tools](https://github.com/manjaro/manjaro-tools) I get a nice clean chroot with only the necessary build packages, similar to the pbuilder (?) chroot Launchpad uses for Ubuntu packaging.

I'll have to dig through the Ubuntu packaging files and cross-reference to the build log; the package builds with a number of variant configurations to provide a variety of packages:

**vim** Vi IMproved - enhanced vi editor
**vim-athena** Vi IMproved - enhanced vi editor - with Athena GUI
**vim-athena-py2** Vi IMproved - enhanced vi editor - with Athena GUI (Python2)
**vim-common** Vi IMproved - Common files
**vim-doc** Vi IMproved - HTML documentation
**vim-gnome** Vi IMproved - enhanced vi editor (dummy package)
**vim-gtk** Vi IMproved - enhanced vi editor - with GTK2 GUI
**vim-gtk-py2** Vi IMproved - enhanced vi editor - with GTK2 GUI (Python2)
**vim-gtk3** Vi IMproved - enhanced vi editor - with GTK3 GUI
**vim-gtk3-py2** Vi IMproved - enhanced vi editor - with GTK3 GUI (Python2)
**vim-gui-common** Vi IMproved - Common GUI files
**vim-nox** Vi IMproved - enhanced vi editor - with scripting languages support
**vim-nox-py2** Vi IMproved - enhanced vi editor - with scripting languages support (Python2)
**vim-runtime** Vi IMproved - Runtime files
**vim-tiny** Vi IMproved - enhanced vi editor - compact version
**xxd** tool to make (or reverse) a hex dump

**Comment by jonathonf** [comment]
Sorry for the delay.

These are the flags for the variant that failed in the previously linked build log:

```
CFGFLAGS_vim-athena:=$(CFGFLAGS) $(OPTFLAGS) $(GUIFLAGS) $(ATHENAFLAGS) $(ALLINTERPFLAGS)

CFGFLAGS := --prefix=/usr --mandir='$${prefix}'/share/man --without-local-dir
CFGFLAGS += --with-modified-by="$(BUILDER)"
CFGFLAGS += --with-compiledby="$(BUILDER)"
CFGFLAGS += --enable-fail-if-missing

OPTFLAGS:=--enable-cscope
OPTFLAGS+=--enable-gpm
OPTFLAGS+=--enable-selinux --disable-smack
OPTFLAGS+=--with-features=huge
OPTFLAGS+=--enable-multibyte
OPTFLAGS+=--enable-acl

GUIFLAGS:=--with-x
GUIFLAGS+=--enable-xim

ATHENAFLAGS:=--enable-gui=athena
ATHENAFLAGS+=--disable-gtk2-check
ATHENAFLAGS+=--disable-gtk3-check
ATHENAFLAGS+=--disable-gnome-check
ATHENAFLAGS+=--disable-motif-check
ATHENAFLAGS+=--enable-athena-check
ATHENAFLAGS+=--enable-fontset

ALLINTERPFLAGS:=--enable-luainterp
ALLINTERPFLAGS+=--disable-mzschemeinterp
ALLINTERPFLAGS+=--enable-perlinterp
ALLINTERPFLAGS+=--enable-python3interp --with-python3-config-dir=$(shell python3-config --configdir)
ALLINTERPFLAGS+=--disable-pythoninterp
ALLINTERPFLAGS+=--enable-rubyinterp
ALLINTERPFLAGS+=--enable-tclinterp
ALLINTERPFLAGS+=--with-tclsh=/usr/bin/tclsh
```

**Comment by brammool** [comment]
Jonathonf wrote:

> Sorry for the delay.
> 
> These are the flags for the variant that failed in the previously linked build log:
> 
> ```
> CFGFLAGS_vim-athena:=$(CFGFLAGS) $(OPTFLAGS) $(GUIFLAGS) $(ATHENAFLAGS) $(ALLINTERPFLAGS)
> 
> CFGFLAGS := --prefix=/usr --mandir='$${prefix}'/share/man --without-local-dir
> CFGFLAGS += --with-modified-by="$(BUILDER)"
> CFGFLAGS += --with-compiledby="$(BUILDER)"
> CFGFLAGS += --enable-fail-if-missing
> 
> OPTFLAGS:=--enable-cscope
> OPTFLAGS+=--enable-gpm
> OPTFLAGS+=--enable-selinux --disable-smack
> OPTFLAGS+=--with-features=huge
> OPTFLAGS+=--enable-multibyte
> OPTFLAGS+=--enable-acl
> 
> GUIFLAGS:=--with-x
> GUIFLAGS+=--enable-xim
> 
> ATHENAFLAGS:=--enable-gui=athena
> ATHENAFLAGS+=--disable-gtk2-check
> ATHENAFLAGS+=--disable-gtk3-check
> ATHENAFLAGS+=--disable-gnome-check
> ATHENAFLAGS+=--disable-motif-check
> ATHENAFLAGS+=--enable-athena-check
> ATHENAFLAGS+=--enable-fontset
> 
> ALLINTERPFLAGS:=--enable-luainterp
> ALLINTERPFLAGS+=--disable-mzschemeinterp
> ALLINTERPFLAGS+=--enable-perlinterp
> ALLINTERPFLAGS+=--enable-python3interp --with-python3-config-dir=$(shell python3-config --configdir)
> ALLINTERPFLAGS+=--disable-pythoninterp
> ALLINTERPFLAGS+=--enable-rubyinterp
> ALLINTERPFLAGS+=--enable-tclinterp
> ALLINTERPFLAGS+=--with-tclsh=/usr/bin/tclsh
> ```

I built with Athena and most of these options, but the test still
passes.

Could you perhaps run the test while debugging Vim, to see what happens?

-- 
The word "leader" is derived from the word "lead", as in the material that
bullets are made out of.  The term "leader" was popularized at about the same
time as the invention of firearms.  It grew out of the observation that the
person in charge of every organization was the person whom everyone wanted to
fill with hot lead.
   I don't recomment this; it's just a point of historical interest.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mbakke** [comment]
> Could you perhaps run the test while debugging Vim, to see what happens?

I am not able to reproduce the failure while running the test interactively in a graphical terminal. This failure only occurs in the isolated build chroot during `make test`.

**Comment by brammool** [comment]
Marius Bakke wrote:

> > Could you perhaps run the test while debugging Vim, to see what happens?
> 
> I am not able to reproduce the failure while running the test
> interactively in a graphical terminal. This failure only occurs in the
> isolated build chroot during `make test`.

Weird.  I'm afraid I have no clue how to fix this, since I don't know
what is to be fixed.


-- 
Everybody wants to go to heaven, but nobody wants to die.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by jonathonf** [comment]
It's an odd one - it must be related to some configuration within the chroot setups. Launchpad only fails with patch 314 (on several variants now, not just `athena`), but a local `pbuilder` chroot fails earlier on to_upper and to_lower tests.

I'll try an `sbuild` chroot at some point and see if that has the same failures; I think Launchpad is pbuilder, Debian use either sbuild or cowbuilder.

**Comment by mbakke** [comment]
Following the code, all three tests have in common that `get_ccline_ptr()` returns NULL in these environments. This is the function from `src/ex_getln.c:6046`:

```
    static struct cmdline_info *
get_ccline_ptr(void)
{
    if ((State & CMDLINE) == 0)
	return NULL;
    if (ccline.cmdbuff != NULL)
	return &ccline;
    if (prev_ccline_used && prev_ccline.cmdbuff != NULL)
	return &prev_ccline;
    return NULL;
}
```

I'm still trying to wrap my head around that file, but my first thought is that `FEAT_GUI` or related macros enables some code that interacts badly with the build environment, which doesn't have xorg and stdin is /dev/null. Any tips for further troubleshooting?

**Comment by vim-ml** [comment]
* Bram Moolenaar <vim-dev-github@256bit.org> [2017-02-17 14:02 -0800]:

> 
> Jonathonf wrote:
> 
> > Sorry for the delay.
> > 
> > These are the flags for the variant that failed in the previously linked build log:
> > 
> > ```
> > CFGFLAGS_vim-athena:=$(CFGFLAGS) $(OPTFLAGS) $(GUIFLAGS) $(ATHENAFLAGS) $(ALLINTERPFLAGS)
> > 
> > CFGFLAGS := --prefix=/usr --mandir='$${prefix}'/share/man --without-local-dir
> > CFGFLAGS += --with-modified-by="$(BUILDER)"
> > CFGFLAGS += --with-compiledby="$(BUILDER)"
> > CFGFLAGS += --enable-fail-if-missing
> > 
> > OPTFLAGS:=--enable-cscope
> > OPTFLAGS+=--enable-gpm
> > OPTFLAGS+=--enable-selinux --disable-smack
> > OPTFLAGS+=--with-features=huge
> > OPTFLAGS+=--enable-multibyte
> > OPTFLAGS+=--enable-acl
> > 
> > GUIFLAGS:=--with-x
> > GUIFLAGS+=--enable-xim
> > 
> > ATHENAFLAGS:=--enable-gui=athena
> > ATHENAFLAGS+=--disable-gtk2-check
> > ATHENAFLAGS+=--disable-gtk3-check
> > ATHENAFLAGS+=--disable-gnome-check
> > ATHENAFLAGS+=--disable-motif-check
> > ATHENAFLAGS+=--enable-athena-check
> > ATHENAFLAGS+=--enable-fontset
> > 
> > ALLINTERPFLAGS:=--enable-luainterp
> > ALLINTERPFLAGS+=--disable-mzschemeinterp
> > ALLINTERPFLAGS+=--enable-perlinterp
> > ALLINTERPFLAGS+=--enable-python3interp --with-python3-config-dir=$(shell python3-config --configdir)
> > ALLINTERPFLAGS+=--disable-pythoninterp
> > ALLINTERPFLAGS+=--enable-rubyinterp
> > ALLINTERPFLAGS+=--enable-tclinterp
> > ALLINTERPFLAGS+=--with-tclsh=/usr/bin/tclsh
> > ```
> 
> I built with Athena and most of these options, but the test still
> passes.

It seems that the failures come up only from a build in a shadowdir
like the Debian-flavours build their packages...

Elimar
-- 
  Alles was viel bedacht wird ist bedenklich!;-)
         Friedrich Nietzsche

**Comment by brammool** [comment]
Jonathonf wrote:

> > > Sorry for the delay.
> > > 
> > > These are the flags for the variant that failed in the previously linked build log:
> > > 
> > > ```
> > > CFGFLAGS_vim-athena:=$(CFGFLAGS) $(OPTFLAGS) $(GUIFLAGS) $(ATHENAFLAGS) $(ALLINTERPFLAGS)
> > > 
> > > CFGFLAGS := --prefix=/usr --mandir='$${prefix}'/share/man --without-local-dir
> > > CFGFLAGS += --with-modified-by="$(BUILDER)"
> > > CFGFLAGS += --with-compiledby="$(BUILDER)"
> > > CFGFLAGS += --enable-fail-if-missing
> > > 
> > > OPTFLAGS:=--enable-cscope
> > > OPTFLAGS+=--enable-gpm
> > > OPTFLAGS+=--enable-selinux --disable-smack
> > > OPTFLAGS+=--with-features=huge
> > > OPTFLAGS+=--enable-multibyte
> > > OPTFLAGS+=--enable-acl
> > > 
> > > GUIFLAGS:=--with-x
> > > GUIFLAGS+=--enable-xim
> > > 
> > > ATHENAFLAGS:=--enable-gui=athena
> > > ATHENAFLAGS+=--disable-gtk2-check
> > > ATHENAFLAGS+=--disable-gtk3-check
> > > ATHENAFLAGS+=--disable-gnome-check
> > > ATHENAFLAGS+=--disable-motif-check
> > > ATHENAFLAGS+=--enable-athena-check
> > > ATHENAFLAGS+=--enable-fontset
> > > 
> > > ALLINTERPFLAGS:=--enable-luainterp
> > > ALLINTERPFLAGS+=--disable-mzschemeinterp
> > > ALLINTERPFLAGS+=--enable-perlinterp
> > > ALLINTERPFLAGS+=--enable-python3interp --with-python3-config-dir=$(shell python3-config --configdir)
> > > ALLINTERPFLAGS+=--disable-pythoninterp
> > > ALLINTERPFLAGS+=--enable-rubyinterp
> > > ALLINTERPFLAGS+=--enable-tclinterp
> > > ALLINTERPFLAGS+=--with-tclsh=/usr/bin/tclsh
> > > ```
> > 
> > I built with Athena and most of these options, but the test still
> > passes.
> 
> It seems that the failures come up only from a build in a shadowdir
> like the Debian-flavours build their packages...

I tried running the tests in a shadow directory.  Works fine for me.

-- 
I wonder how much deeper the ocean would be without sponges.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by jamessan** [comment]
I've posted the root cause of the issue and a proposed patch on [vim-dev](https://groups.google.com/d/msg/vim_dev/_a9DYXDuZ1I/Mb2c3lUbBgAJ).

> Any tips for further troubleshooting?

FWIW, I had been encountering this building in sbuild.  I ensured that gdbserver would be installed during the build and then made this change to debian/rules:

```diff
--- a/debian/rules
+++ b/debian/rules
@@ -291,7 +291,7 @@ build-stamp-%: configure-stamp-%
        @echo "*** DEBIAN *** BUILDING VARIANT $*"
        $(MAKE) -C src/$(SHADOWDIR)
        # Ensure $TERM is set to a sane value for testing
-       [ $(MAKETEST) != "yes" ] || flock debian env TERM=xterm $(MAKE) -j1 -C src/$(SHADOWDIR) test
+       [ $(MAKETEST) != "yes" ] || [ "$*" != "vim-gtk3" ] || flock debian env TERM=xterm $(MAKE) -j1 -C src/$(SHADOWDIR)/testdir test_cmdline.res VALGRIND="gdbserver localhost:7000"
        touch $@
 
 install: install-stamp-xxd $(foreach v,$(VARIANTS),install-stamp-$(v))
```

Once the build got to the test, I then ran gdb from another terminal and had it connect to the build's gdbserver.

```gdb
(gdb) set sysroot /run/schroot/mount/...
(gdb) target remote localhost:7000
(gdb) b f_input
(gdb) c
```
