### ISSUE TITLE
Wrong DisplayVersion registry key written in Windows 11

### ISSUE THREAD

**Issue by jonathan-b-wiebe** [vim/vim#14629]
### Steps to reproduce

1. Open a terminal and install vim using the command 'winget install vim.vim'. As of today Vim 9.1.0312_x64.exe is downloaded and installed.
2. Type the command 'winget upgrade'. The results will show that version 9.1.0 is installed and 9.1.0312 is available.
3. Open vim. This will show that installed version is indeed 9.1.0312.
4. Open the registry editor and go to the key: Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Vim 9.1
5. Note that the DisplayVersion is set t0 9.1.0. This is also the source of the version shown in Settings -> Apps -> Installed Apps.
6. Manually installing the latest version from the vim-win32-installer site (9.1.0368) will update the registry key to 9.1.0000, which is still incorrect.

### Expected behaviour

1. Winget should show that version 9.1.0312 is installed and not show that an update is available.
2. Settings -> Apps -> Installed Apps should show version 9.1.312 is installed.
3. The registry key should be set to 9.1.0312.

### Version of Vim

9.1.0312

### Environment

Windows 11-23H2

**Comment by chrisbra** [comment]
Isn't that a problem with winget then, if it works when manually installing?

**Comment by jonathan-b-wiebe** [comment]
Manually installing the latest version from the vim-win32-installer site (9.1.0368) will update the registry key to 9.1.0000, which is still incorrect. The registry key should be set to 9.1.0312.

**Comment by chrisbra** [comment]
I don't think this is true, here on my current system (Win10), it shows the correct version:
![grafik](https://github.com/vim/vim/assets/244927/20b17f15-28ca-4afb-872c-613a05b992ae)
![grafik](https://github.com/vim/vim/assets/244927/861b34e0-1358-405d-981e-a7e032e6d59d)

**Comment by jonathan-b-wiebe** [comment]
I have re-installed using the same version you are running (9.1.0136) and it indeed works correctly.
I will uninstall and reinstall with newer versions to determine when this behavour started.
Thanks for your help!

**Comment by jonathan-b-wiebe** [comment]
I can now confirm that this behaviour started somewhere between version 9.1.0282 and 9.1.0296. I cannot get move exact then this because these are two consecutive released on the vim-win32-installer site and I am not set up to compile vim in order to test the intermediate versions between these.
Installing version 9.1.0282 shows the following in the registry:
![image](https://github.com/vim/vim/assets/25091878/9a93563e-d464-411d-9eb8-a45ebb2a6229)
Installing version 9.1.0296 shows the following:
![image](https://github.com/vim/vim/assets/25091878/62850456-684a-4eef-b832-f69a8c81ad92)
Re-installing version 9.1.0282 returns the key to the correct value.

**Comment by RestorerZ** [comment]
@jonathan-b-wiebe 
And can you please install the latest version with “vim-win32-install” and see what you get in your registry?
https://github.com/vim/vim-win32-installer/releases/tag/v9.1.0368

**Comment by chrisbra** [comment]
Hm, I don't see any potential changes between v9.1.282 and v9.1.296 that could cause this.

**Comment by chrisbra** [comment]
I guess this one here: https://github.com/vim/vim-win32-installer/commit/672d8c5e594cb76d79e8217fef350e1a88f7bdfe ?

**Comment by jonathan-b-wiebe** [comment]
Installing gvim_9.1.0368_x64.exe results in the following registry key:
![image](https://github.com/vim/vim/assets/25091878/94fce221-f29e-4ef1-a967-afda4680b1e7)

**Comment by RestorerZ** [comment]
I'm afraid it has to do with this pull request #338 and #14471

**Comment by RestorerZ** [comment]
> Installing gvim_9.1.0368_x64.exe results in the following registry key:

Thank you. I'll check it out now.

**Comment by RestorerZ** [comment]
Yeah, everything seems to be working as it should.
![prg-vim-inst-ptchlvl](https://github.com/vim/vim/assets/69863286/c1c25a34-a6df-478a-99c7-032874d5bd1a)
![reg-vim-inst-ptchlvl](https://github.com/vim/vim/assets/69863286/36edb4b2-a76b-472e-9b86-161abaa59818)
