### ISSUE TITLE
 Wrong handling of folder symbolic link in tree view

### ISSUE THREAD

**Issue by kuator** [vim/vim#14623]
### Steps to reproduce

1. Download latest vim appimage.
2. `mv Vim-v9.1.0366.glibc2.29-x86_64.AppImage vim`
3. `mkdir /tmp/test`
4. `mv vim /tmp/test && chmod u+x /tmp/test/vim`
5. `cd /tmp/test && mkdir first && echo 'text' >> first/file.txt`
6. `ln -sv /tmp/test/first /tmp/test/second`
7. `./vim -c 'let g:netrw_liststyle=3'`
8. Try to open `second` folder which is a symlink. For some reason `netrw` added extra `second` to it's path, and turned it into `/tmp/test/second/second`, when it should have been `/tmp/test/second`

https://github.com/vim/vim/assets/25168308/527c75df-110c-4894-a12f-153edef872f1

### Expected behaviour

Open a symbolic link

### Version of Vim

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 14 2024 09:05:11)

### Environment

Ubuntu 22.04.4 LTS jammy
GNOME Terminal 3.44.0 using VTE 0.68.0 +BIDI +GNUTLS +ICU +SYSTEMD
xterm-256color
zsh 5.8.1 (x86_64-ubuntu-linux-gnu)

**Comment by chrisbra** [comment]
can you try that with a local installation please? I cannot seem to reproduce with latest vim and netrw

**Comment by kuator** [comment]
> can you try that with a local installation please? I cannot seem to reproduce with latest vim and netrw

I built the latest vim version locally. `VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Apr 25 2024 11:57:05)`. No difference. 

https://github.com/vim/vim/assets/25168308/d90583a6-bbee-46d0-b68d-a9e8dc06926a

**Comment by chrisbra** [comment]
This is 9.1.0? Please try latest master. In particular there was commit 56b7da3c051fe1a5fd7653499 that should have fixed the issue.

**Comment by kuator** [comment]
> This is 9.1.0? Please try latest master. In particular there was commit [56b7da3](https://github.com/vim/vim/commit/56b7da3c051fe1a5fd76534998c17b22d83c0899) that should have fixed the issue.

I built from latest master: `9.1.369`, the vim splash screen in the video above show `9.1.369` as well

**Comment by chrisbra** [comment]
I cannot reproduce this. Here is what I did as a new user:
```
cb@debian:~$ cat <<'EOF' > .vimrc
unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim
let g:netrw_liststyle=3
EOF
rm -rf /tmp/test;
mkdir -p /tmp/test &&
echo "first" > /tmp/test/first &&
ln -sfn /tmp/test/first /tmp/test/second
```

fresh compiled Vim 9.1.373
Can you check with :scriptnames what netrw was loaded?

**Comment by chrisbra** [comment]
Screen capture:
https://github.com/vim/vim/assets/244927/927be012-3a4b-4413-a011-8bf6087f2bb9

**Comment by kuator** [comment]
> I cannot reproduce this. Here is what I did as a new user:
> 
> ```
> cb@debian:~$ cat <<'EOF' > .vimrc
> unlet! skip_defaults_vim
> source $VIMRUNTIME/defaults.vim
> let g:netrw_liststyle=3
> EOF
> rm -rf /tmp/test;
> mkdir -p /tmp/test &&
> echo "first" > /tmp/test/first &&
> ln -sfn /tmp/test/first /tmp/test/second
> ```
> 
> fresh compiled Vim 9.1.373 Can you check with :scriptnames what netrw was loaded?

This example also works in my case, because in your example `second` and `first` are files. But in my original example above, `first` and `second` are folders.

**Comment by ronin49** [comment]
@chrisbra good morning
how i use gdb for vim? it says operation not permitted

**Comment by chrisbra** [comment]
with:
```
drwxr-xr-x 2 chrisbra chrisbra 4096 Apr 30 20:55 first
lrwxrwxrwx 1 chrisbra chrisbra   15 Apr 30 20:49 second -> /tmp/test/first
```
`:Explore /tmp/test`

Then selecting `second` and pressing enter updates the netrw window with the content of `/tmpt/test/first` (so it  follows the symlink) and selecting then a file in the `first/` directory opens it just fine for me.
