### ISSUE TITLE
Toggle comments in code

### ISSUE THREAD

**Issue by girishji** [vim/vim#14626]
This is a RFC. The proposal is to include a script in `autoload/` that provides a utility function to toggle comments in code. Something along the lines of https://github.com/habamax/.vim/blob/master/autoload/comment.vim (or tpope's vim-commentary, although I prefer habamax's vim9 solution).

**Comment by chrisbra** [comment]
That sounds useful. @habamax would you be okay with this?

**Comment by habamax** [comment]
sure, will prepare PR
