### ISSUE TITLE
Ubuntu: Insert mode, backspace cannot delete

### ISSUE THREAD

**Issue by HiddenTesla** [vim/vim#1463]
**System:** Linux, Ubuntu 16.04, 64 bit, 
**Vim version:** `
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb  6 2017 05:46:08)
Included patches: 1-311
`,
_(compiled and installed by myself using `make` and `sudo make install`)_
**Plugins installed:** Taglist, nerdtree

**Reproduce procedure:**
- Using vim, create a new file and type anything, or open any existing non-empty file;
- Move cursor to middle of end of the file;
- Switch to insert mode by pressing any of `A`/`a`, `I`/`i`, etc.;
- Press `backspace`, see if characters before the cursor can be deleted.

**Result:**
`backspace` cannot delete what exists before this switching to insert mode. Those are newly entered after insert mode, however, can be deleted.
For example, suppose cursor is at a line

> #include <uinstd.h>

And I press `A` then `backspace`,  it is expected to become

> #include <uinstd.h

with the tailing `>` deleted. The actual result is, `backspace` cannot delete it. But if I type something and then `backspace', then these newly typed will be deleted.

Oddly, this issue is not found if vim is built and installed on an RHEL system, nor does it occur on the binary from Ubuntu software center. 
I guess something is wrong when I make?
At first, the make fails, saying that one lib is missing. I googled it and install a lib (forget the name). Then make and make install works. Later, further use reveals the problem.

Thanks!

**Comment by k-takata** [comment]
This is not a bug. See `:help 'backspace'`.

**Comment by chrisbra** [comment]
set the backspace option correct. Please ask user questions on the appropriate forums.
