### ISSUE TITLE
vim is too slow when editing *.ass file.

### ISSUE THREAD

**Issue by xvim64** [vim/vim#14653]
### Steps to reproduce

1. download an ass file.
https://github.com/EugeneLiu/translationCSAPP/blob/master/subtitle/translation/Lecture%2001%20%20course_overview.ass

2. open the ass file with vim.

3. move the cursor using h, j, k, and l in vim.
--> too slow

There is a same issue in neovim.
https://github.com/neovim/neovim/issues/25950

It seems that the "syntax/ssa.vim" is not efficient.

Also, "(g)vim --clean test.ass" is too slow.

### Expected behaviour

no delay when editing *.ass.

### Version of Vim

9.1.0377

### Environment

Windows 11 23H2 (64bit)

**Comment by chrisbra** [comment]
a few things to check: Is it slow when turning off syntax highlighting? If yes, please use `:syntime` to find the slow pattern and check with the maintainer of the syntax file if he has an idea how to improve that particular pattern

**Comment by chrisbra** [comment]
Here is a very simple patch to improve the performance:
```patch
diff --git a/runtime/syntax/ssa.vim b/runtime/syntax/ssa.vim
index a5dbf37c3..e7e76aa2b 100644
--- a/runtime/syntax/ssa.vim
+++ b/runtime/syntax/ssa.vim
@@ -29,7 +29,7 @@ syn match ssaTime /\d:\d\d:\d\d\.\d\d/ contained skipwhite nextgroup=ssaDelimite
 syn match ssaDelimiter /,/ contained skipwhite nextgroup=ssaField,ssaTime,ssaText

 " Text
-syn match ssaText /\(^Dialogue:\(.*,\)\{9}\)\@<=.*$/ contained contains=@ssaTags,@Spell
+syn match ssaText /\(^Dialogue:\([^,]*,\)\{9}\)\@100<=.*$/ contained contains=@ssaTags,@Spell
 syn cluster ssaTags contains=ssaOverrideTag,ssaEscapeChar,ssaTextComment,ssaItalics,ssaBold,ssaUnderline,ssaStrikeout

 " Override tags
```

ping @ObserverOfTime

**Comment by xvim64** [comment]
> Here is a very simple patch to improve the performance:
> 
> +syn match ssaText /\(^Dialogue:\([^,]*,\)\{9}\)\@100<=.*$/ contained contains=@ssaTags,@Spell
> 
> ping @ObserverOfTime

Thank you!
This patch works really well.
