### ISSUE TITLE
High CPU usage on Fedora 40

### ISSUE THREAD

**Issue by zhscn** [vim/vim#14650]
### Steps to reproduce

1. Open one log file, here is an example of mine, the complete file size is about 250M
[log.txt](https://github.com/vim/vim/files/15136953/log.txt)
2. Press Ctrl-D to continue scrolling down.
3. CPU usage reaches 100%
![Screenshot from 2024-04-27 11-02-12](https://github.com/vim/vim/assets/45552541/52b57924-d6cb-409b-b003-098feace9ee7)

flamegraph:
![flamegraph](https://github.com/vim/vim/assets/45552541/caa69c5d-1aa6-47bf-a8b6-99e0d54fb3eb)

### Expected behaviour

CPU usage should be at a low level.

### Version of Vim

9.1.309

### Environment

OS: fedora 40
terminal: gnome-terminal-3.50.1-6.fc40.x86_64
$TERM: xterm-256color

**Comment by zhscn** [comment]
git bisect shows that 9148ba8a46baa3934c44164989cdcdec5d01d9e3 caused this problem.

**Comment by chrisbra** [comment]
ping @luukvbaal

**Comment by zzzyxwvut** [comment]
Vim with `--clean` and the LargeFile plugin (available from  
[here](https://web.archive.org/web/20240407153314/http://www.drchip.org/astronaut/vim/#LARGEFILE) and [here](https://www.vim.org/scripts/script.php?script_id=1506)) may also help:

```sh
vim --clean -Nu NONE '+set pp=~/.vim rtp=~/.vim' log.log
```

**Comment by luukvbaal** [comment]
Hmm almost missed this despite the ping because of the nondescript issue title.
We just spend a lot of cycles in `plines_m_win()` with `limit_winheight == FALSE`. We need to count until `w_height + count` so `limit_winheight == TRUE` doesn't work. Could add a new argument to `plimes_m_win()` to that end.
