### ISSUE TITLE
serbian input

### ISSUE THREAD

**Issue by lesorubshayan** [vim/vim#14668]
### Steps to reproduce

vim runtime/lang/menu_sr_rs.utf-8.vim
try to make a search or go to insert mode and try to type
text will be recognized as serbian even if you have english keyboard on

### Expected behaviour

normal input

### Version of Vim

source

### Environment

arch

**Comment by ronin49** [comment]
it is because of keymap=serbian in the end i will remove it in my next pr

**Comment by zeertzjq** [comment]
`:setlocal keymap&`
