### ISSUE TITLE
gvim menu inconsistencies

### ISSUE THREAD

**Issue by lesorubshayan** [vim/vim#14672]
### Steps to reproduce

open up gvim (lang doesn't matter)
click on edit button from ui pane(second button)
watch last 2 fields
after some seconds they will change

### Expected behaviour

consistency

### Version of Vim

source

### Environment

arch

**Comment by k-takata** [comment]
This behavior is intentional to reduce the startup time.
If you don't want this behavior, add `let do_no_lazyload_menus = 1` in your vimrc.
See `:help menu.vim` for details.

@chrisbra
I think we should add tags about this variable:
```diff
--- a/runtime/doc/gui.txt
+++ b/runtime/doc/gui.txt
@@ -503,7 +503,7 @@ The first item in the Syntax menu can be
 in the menu (which can take a bit of time to load).  If you want to have all
 filetypes already present at startup, add: >
 	:let do_syntax_sel_menu = 1
-
+<					*menu-lazyload* *do_no_lazyload_menus*
 The following menuitems show all available color schemes, keymaps and compiler
 settings:
 	Edit > Color Scheme ~
```

**Comment by ronin49** [comment]
@k-takata it didn't work
