### ISSUE TITLE
Is 'backup' supposed to be off by default?

### ISSUE THREAD

**Issue by thecliguy** [vim/vim#1468]
I am running the following version of Vim on Windows 10:

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov  6 2016 17:05:36)
MS-Windows 32-bit console version
Included patches: 1-69
```

I have observed that upon editing a file and writing the changes, an additional file is created, the name of which is the same as the original but with `~` appended to it. This additional file contains the content prior to the write and remains even after having closed Vim.

I wanted to know whether it is the expected behaviour that the backup file remains even once Vim has been closed, I therefore consulted the help...

The help topic `backup-table` refers to two settings (`backup` and `writebackup`) which are responsible for the circumstances under which a backup file is created.

Although my user vimrc file (`$HOME\_vimrc`) doesn't directly contain a reference to either `backup` and/or `writebackup`, the first line in the file is `source $VIMRUNTIME/vimrc_example.vim`, which does contain such a reference. According to the logic within `$VIMRUNTIME/vimrc_example.vim`, `backup` is enabled for any operating system other than 'VMS':
```
if has("vms")
  set nobackup		" do not keep a backup file, use versions instead
else
  set backup		" keep a backup file (restore to previous version)
  if has('persistent_undo')
    set undofile	" keep an undo file (undo changes after closing)
  endif
endif
```

Whilst consulting the help, I discovered another topic `backup-changed`, which suggests that the `backup` option used to be on by default (in previous versions of Vim) but is now off by default:
```
The default value for 'backup' used to be on.  This resulted in a backup file
being made when the original file was overwritten.

Now the default for 'backup' is off.  As soon as the writing of the file has
successfully finished, the backup file is deleted.  If you want to keep the
backup file, set 'backup' on in your vimrc.  The reason for this change is
that many people complained that leaving a backup file behind is not
Vi-compatible.
```

So my question is, why does `$VIMRUNTIME/vimrc_example.vim` enable `backup` in contradiction to the `backup-changed` help topic which states that it is supposed to be off by default?

**Comment by vim-ml** [comment]
2017-02-12 7:17 GMT+03:00 thecliguy <vim-dev-github@256bit.org>:
> I am running the following version of Vim on Windows 10:
>
> VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov  6 2016 17:05:36)
> MS-Windows 32-bit console version
> Included patches: 1-69
>
> I have observed that upon editing a file and writing the changes, an
> additional file is created, the name of which is the same as the original
> but with ~ appended to it. This additional file contains the content prior
> to the write and remains even after having closed Vim.
>
> I wanted to know whether it is the expected behaviour that the backup file
> remains even once Vim has been closed, I therefore consulted the help...
>
> The help topic backup-table refers to two settings (backup and writebackup)
> which are responsible for the circumstances under which a backup file is
> created.
>
> Although my user vimrc file ($HOME\_vimrc) doesn't directly contain a
> reference to either backup and/or writebackup, the first line in the file is
> source $VIMRUNTIME/vimrc_example.vim, which does contain such a reference.
> According to the logic within $VIMRUNTIME/vimrc_example.vim, backup is
> enabled for any operating system other than 'VMS':
>
> if has("vms")
>   set nobackup " do not keep a backup file, use versions instead
> else
>   set backup " keep a backup file (restore to previous version)
>   if has('persistent_undo')
>     set undofile " keep an undo file (undo changes after closing)
>   endif
> endif
>
> Whilst consulting the help, I discovered another topic backup-changed, which
> suggests that the backup option used to be on by default (in previous
> versions of Vim) but is now off by default:
>
> The default value for 'backup' used to be on.  This resulted in a backup
> file
> being made when the original file was overwritten.
>
> Now the default for 'backup' is off.  As soon as the writing of the file has
> successfully finished, the backup file is deleted.  If you want to keep the
> backup file, set 'backup' on in your vimrc.  The reason for this change is
> that many people complained that leaving a backup file behind is not
> Vi-compatible.
>
> So my question is, why does $VIMRUNTIME/vimrc_example.vim enable backup in
> contradiction to the backup-changed help topic which states that it is
> supposed to be off by default?

Why it should not? vimrc_example.vim is an example of vimrc file, it
is *not* a collection of default values and neither it is in any way
required to be used by the user.

**Comment by chrisbra** [comment]
I think that is a question that is better asked on the vim_use ml. Closing, as this is no real issue.

**Comment by thecliguy** [comment]
I now realise that 'default' refers to the implicit value. EG, if you don't explicitly supply a value for 'backup', it'll implicitly be set to 'off'.

I had originally interpreted 'default' to mean behaviour that's exhibited without the end user having made any modifications to vim. For example, if a user has never used vim before, then they won't have a 'user' vimrc file, consequently vim will refer to the 'system' vimrc. As a result, the default behaviour experienced by the user is that 'backup' is set to on.

Now that I understand what's happening, I agree that there is no defect, Vim is behaving as expected. However, I do wonder whether this deserves a mention in the documentation? Anyhow, that is a decision for the project maintainers...

**Comment by k-takata** [comment]
Current Windows installer creates ~~a system vimrc~~ `$VIM/_vimrc` which includes vimrc_example.vim, but it is not documented as far as I know.
Now Vim 8.0 has defaults.vim and it is well documented. Maybe the Windows installer should create a system vimrc which includes defaults.vim instead of vimrc_example.vim. (Or the installer should stop creating a system vimrc?)

**Comment by vim-ml** [comment]
On Sun, Feb 12, 2017 at 1:56 PM, K.Takata <vim-dev-github@256bit.org> wrote:
> Current Windows installer creates a system vimrc which includes
> vimrc_example.vim, but it is not documented as far as I know.
> Now Vim 8.0 has defaults.vim and it is well documented. Maybe the Windows
> installer should create a system vimrc which includes defaults.vim instead
> of vimrc_example.vim. (Or the installer should stop creating a system
> vimrc?)
>
In recent versions of vim, if no vimrc is found, Vim will source
$VIMRUNTIME/defaults.vim which in turn sources
$VIMRUNTIME/vimrc_example.vim which sets a lot of useful settings,
starting with 'nocompatible'. This is however a very recent
development (Vim 8.0, see ":help incompatible-8"); before that, there
was no defaults.vim, vimrc_example.vim was not sourced automatically
(but of course your vimrc could do it), and if you had no vimrc you
started in 'compatible' mode, while if a vimrc was found it was
sourced in 'nocompatible' mode (and if an exrc was found it was
sourced in 'compatible' mode for compatibility with ex and legacy vi).

If you have a vimrc, defaults.vim and vimrc_example.vim won't be
automatically sourced, but I still recommend to source the
vimrc_example.vim because IMHO most of the settings it sets are
useful. The few that I don't like I reset after coming back from it,
e.g.

    runtime vimrc_example.vim
    filetype indent off

(the example vimrc sets ":filetype plugin indent on" but I don't like
the way Vim does filetype-dependent indentation in the kinds of files
I write).


Best regards,
Tony.

**Comment by vim-ml** [comment]
On Sun, Feb 12, 2017 at 5:17 AM, thecliguy <vim-dev-github@256bit.org> wrote:
> I am running the following version of Vim on Windows 10:
>
> VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov  6 2016 17:05:36)
> MS-Windows 32-bit console version
> Included patches: 1-69

Note that the latest bleeding-edge patchlevel is 8.0.326, or 8.0.324
if you don't count "tests-only" fixes. The latte was released this
past Thursday.
>
> I have observed that upon editing a file and writing the changes, an
> additional file is created, the name of which is the same as the original
> but with ~ appended to it. This additional file contains the content prior
> to the write and remains even after having closed Vim.
>
> I wanted to know whether it is the expected behaviour that the backup file
> remains even once Vim has been closed, I therefore consulted the help...
>
> The help topic backup-table refers to two settings (backup and writebackup)
> which are responsible for the circumstances under which a backup file is
> created.
>
> Although my user vimrc file ($HOME\_vimrc) doesn't directly contain a
> reference to either backup and/or writebackup, the first line in the file is
> source $VIMRUNTIME/vimrc_example.vim, which does contain such a reference.
> According to the logic within $VIMRUNTIME/vimrc_example.vim, backup is
> enabled for any operating system other than 'VMS':
>
> if has("vms")
>   set nobackup " do not keep a backup file, use versions instead
> else
>   set backup " keep a backup file (restore to previous version)
>   if has('persistent_undo')
>     set undofile " keep an undo file (undo changes after closing)
>   endif
> endif
>
> Whilst consulting the help, I discovered another topic backup-changed, which
> suggests that the backup option used to be on by default (in previous
> versions of Vim) but is now off by default:
>
> The default value for 'backup' used to be on.  This resulted in a backup
> file
> being made when the original file was overwritten.
>
> Now the default for 'backup' is off.  As soon as the writing of the file has
> successfully finished, the backup file is deleted.  If you want to keep the
> backup file, set 'backup' on in your vimrc.  The reason for this change is
> that many people complained that leaving a backup file behind is not
> Vi-compatible.
>
> So my question is, why does $VIMRUNTIME/vimrc_example.vim enable backup in
> contradiction to the backup-changed help topic which states that it is
> supposed to be off by default?

The recommended setting for "medium" and larger builds, which are
compiled with +writebackup, is

    set nobackup writebackup

This way, Vim will create a temporary backup file just before
overwriting your editfile, erase it once (and if) the write is found
to have been successful, and leave no backups lying around. If you
still want to leave sleeping backups on your disks, you can, see

    :help 'backup'
    :help 'backupext'

and, in  fact, all the options whose name start with 'backup (plus
'writebackup' mentioned above).


Best regards,
Tony.

**Comment by tonymec** [comment]
I found the exact changeset where defaults.vim was added, it was at patchlevel 7.4.2111, near the end of the 7.4 cycle.

Best regards,
Tony.

**Comment by k-takata** [comment]
Hi Tony,

> In recent versions of vim, if no vimrc is found, Vim will source $VIMRUNTIME/defaults.vim

It's not true for the official Windows installer.
The official Windows installer creates `$VIM/_vimrc` which sources `$VIMRUNTIME/vimrc_example.vim` (and also `$VIMRUNTIME/mswin.vim`). So, if a user doesn't have a user vimrc, `vimrc_example.vim` is sourced instead of `defaults.vim`. It is different from other environments.

**Comment by thecliguy** [comment]
> It's not true for the official Windows installer.
The official Windows installer creates $VIM/_vimrc which sources $VIMRUNTIME/vimrc_example.vim (and also $VIMRUNTIME/mswin.vim). So, if a user doesn't have a user vimrc, vimrc_example.vim is sourced instead of defaults.vim. It is different from other environments.

 k-takata, I have the same understanding as you. If no user vimrc is present then vim resorts to using the system vimrc `$VIM/_vimrc`. The system vimrc sources `$VIMRUNTIME/vimrc_example.vim`, which sources `$VIMRUNTIME/vimrc_example.vim` and `$VIMRUNTIME/mswin.vim`.

But in addition to what you have said, `$VIMRUNTIME/vimrc_example.vim` sources `$VIMRUNTIME/defaults.vim`.

**Comment by thecliguy** [comment]
Disregard my last message, I should have said:

k-takata, I have the same understanding as you. If no user vimrc is present then vim resorts to using the system vimrc `$VIM/_vimrc`. The system vimrc sources `$VIMRUNTIME/vimrc_example.vim` and `$VIMRUNTIME/mswin.vim`.

But in addition to what you have said, `$VIMRUNTIME/vimrc_example.vim` sources `$VIMRUNTIME/defaults.vim`.
