### ISSUE TITLE
Can't add {silent} argument to execute()

### ISSUE THREAD

**Issue by alizeegagnon** [vim/vim#14717]
### Steps to reproduce

1. Start vim with `vim -u NONE`
2. Insert any text in the first line and come back to normal mode (ex. `ithis is text<ESC>`)
3. Type `:execute('1d', 'silent')`

### Expected behaviour

The first line gets deleted (silently)
I expect this command to succeed because `:help execute()` suggests the `{silent}` option.

### Version of Vim

8.2.2121

### Environment

OS: Ubuntu 22.04.4 LTS
Terminal: GNOME Terminal 3.44.0
$TERM: xterm-256color
Shell: GNU bash, version 5.1.16(1)
Window manager: i3wm version 4.20.1
[Full vim version, patches, features, flags](https://github.com/vim/vim/files/15205453/vimversion.txt)

### Logs and stack traces

```shell
E110: Missing ')'
```

**Comment by zeertzjq** [comment]
`:call execute('1d', 'silent')`

**Comment by alizeegagnon** [comment]
That was it, thanks!!
