### ISSUE TITLE
gdb

### ISSUE THREAD

**Issue by lesorubshayan** [vim/vim#14714]
### Steps to reproduce

gdb says no member but it is actually there
![image](https://github.com/vim/vim/assets/49647614/68941bec-b519-4705-ac55-37aa9b6b2778)

### Expected behaviour

print member

### Version of Vim

master

### Environment

arch

**Comment by zeertzjq** [comment]
It's not. It's a macro
https://github.com/vim/vim/blob/5bf7446ba2b2eab36685176379a642472891ff88/src/structs.h#L307
