### ISSUE TITLE
auto-complete preload words list based on filetype

### ISSUE THREAD

**Issue by petaflot** [vim/vim#14719]
# Problem

when starting a new document (typically openscad, in the example), I like to autocomplete standard function names such as `difference`, `intersection`, `import`, `include`, etc. However, this only works if the word already exists in the current document (or another one that is opened).

# Workaround

for each filetype, the user makes a document with the required words and opens it alongside the new document. requires more work and is visually an issue because of the space that extra text file takes on the display, and even more work to make it smaller (typically one-line high)

# Solution

auto-load a list of words that are likely to be auto-completed based on the filetype when a syntax highlighting is selected

**Comment by chrisbra** [comment]
That is already possible using ['completefunc'](https://vimhelp.org/insert.txt.html#compl-function) and [omni-completion](https://vimhelp.org/insert.txt.html#compl-omni). You just need to find a plugin for your filetype

**Comment by petaflot** [comment]
ok... I tried with python, python3, but could not get it to work.

I took a look at the files in `/usr/share/vim/vim90/autoload/*complete.vim` and TBH it's quite obscure to me (although I do see there's much more to it than I expected, which is good)

**Comment by gdupras** [comment]
setlocal omnifunc=syntaxcomplete#Complete

See `:help ft-syntax-omni` and `:help compl-omni`.
