### ISSUE TITLE
gdb

### ISSUE THREAD

**Issue by lesorubshayan** [vim/vim#14713]
### Steps to reproduce

cannot put a breakpoint on func in gdb
![image](https://github.com/vim/vim/assets/49647614/7ba45c43-eac3-4640-beb9-1e2de2949ebf)

### Expected behaviour

put a breakpoint on func in gdb

### Version of Vim

master

### Environment

arch

**Comment by zeertzjq** [comment]
`make distclean && ./configure CFLAGS='-g -DDEBUG -Wall -Wshadow -Wmissing-prototypes'`

**Comment by ronin49** [comment]
didn't worked

**Comment by ronin49** [comment]
worked
