### ISSUE TITLE
Incomplete link: Wikipedia link for vi is wrong/incomplete in REAME.md

### ISSUE THREAD

**Issue by shamblonaut** [vim/vim#14725]
Under the [**What is Vim?**](https://github.com/vim/vim#what-is-vim) section in README.md, there is a [link](https://en.wikipedia.org/wiki/Vi) to the Wikipedia page for Vi, but it leads to the common references page for Vi on Wikipedia.

Expected: It should lead to the [vi (text editor)](https://en.wikipedia.org/wiki/Vi_(text_editor)) page.

**Comment by chrisbra** [comment]
thanks, I am fixing it now.
