### ISSUE TITLE
Vi takes very long time(~ 20-30 sec ) to highlight codes on larger files.

### ISSUE THREAD

**Issue by pkgodara** [vim/vim#1472]
[MySqlInstaller.php.zip](https://github.com/vim/vim/files/770092/MySqlInstaller.php.zip)

Open this file for example , it takes very long time but gedit highlights it instantly.

**Comment by chrisbra** [comment]
this depends on the syntax rules used. Best to talk to the syntax file maintainer about this. Check the output of `:syntime start` (scroll a bit) and `:syntime report`
