### ISSUE TITLE
open grep result directly

### ISSUE THREAD

**Issue by wasphin** [vim/vim#1473]
grep with line number outputs has format:
```
foo.txt:100:  bar
```
what about add an option to open file ``foo.txt`` and goto line 100 directly by:
```
vim foo.txt:100:
``` 
or
```
vim foo.txt:100
```
rather than:
```
vim foo.txt +100
```

**Comment by wasphin** [comment]
```
vim $(echo "$1" | sed -e 's/^\([^:]*\):\([0-9]\+\):\?$/\1 +\2/g')
```

**Comment by chrisbra** [comment]
that already works if you use the quickfix/location list.

**Comment by wasphin** [comment]
Thanks @chrisbra, I did not even hear of ``quickfix/location``, I need some more googling and reading.

I used to:
1. ``git grep -n foo``
1. no results found or not what I expect, then ``git grep -n bar``
1. use ``vim`` for a quick view on a certain line

It seems that ``quickfix/location`` requires an already opened vim buffer?
And how to jump to, for example, the 5th(and most of time it's hard to tell ``vim`` the number) result? Or, if no one expected, how can I just close it?

```
$ vim -c ":grep blabla *.log"

grep.log:1:1 blabla
grep.log:2:2 blabla
grep.log:3:3 blabla
grep.log:4:4 blabla
grep.log:5:5 blabla
grep.log:6:6 blabla
grep.log:7:7 blabla
grep.log:8:8 blabla
grep.log:9:9 blabla
grep.log:10:10 blabla

Press ENTER or type command to continue

```

**Comment by chrisbra** [comment]
sorry, I cannot provide user support, there are way to many tickets to provide individual support. So please ask your question on appropriate forums, e.g. vim_use ml or vi.stackexchange.com Thanks.

**Comment by brammool** [comment]
It's possible in various ways, but still requires the user to add a mapping or autocommand.
Problem is always that a file name could actually end in :{number}.

I also wanted to make "gf" jump to the right line number, very useful when looking in the output of a compilation command (and not using quickfix for whatever reason).  That should be possible, so long as the : character is not in 'isfname'.

**Comment by vim-ml** [comment]
Hi Bram,

On Mon, Feb 13, 2017 at 3:22 PM, Bram Moolenaar
<vim-dev-github@256bit.org> wrote:
> It's possible in various ways, but still requires the user to add a mapping
> or autocommand.
> Problem is always that a file name could actually end in :{number}.
>
> I also wanted to make "gf" jump to the right line number, very useful when
> looking in the output of a compilation command (and not using quickfix for
> whatever reason). That should be possible, so long as the : character is not
> in 'isfname'.
>

The "gF" command jumps to the line number following the file name.

- Yegappan

**Comment by vim-ml** [comment]
Hi,

On Mon, Feb 13, 2017 at 2:13 AM, was4444 <vim-dev-github@256bit.org> wrote:
> Thanks @chrisbra, I did not even hear of quickfix/location, I need some more
> googling and reading.
>
> I used to:
>
> git grep -n foo
> no results found or not what I expect, then git grep -n bar
> use vim for a quick view on a certain line
>
> It seems that quickfix/location requires an already opened vim buffer?
>

Different quickfix/location list commands are available to process the
output from a command. Some of them are listed below:

1. Redirect the output from a command to a file and pass it onto Vim.

      $ grep -Hn abc *.log > output.txt
      $ vim -q output.txt

2. Run the command directly from Vim and populate the quickfix list.

     $ vim
     :cexpr system('grep -Hn abc *.log')

3. Read the output of the command into a Vim buffer (or paste the
    output of the command into a buffer) and populate the quickfix list.
    Note that you can use an unnamed/scratch buffer for this.

    $ vim
    :r! grep -Hn abc *.log
    :cgetbuffer

    The above 'cgetbuffer' command processes the entire buffer. You can
    also process only selected lines by passing a range to the command.

4. Use the ":grep" command to invoke an external command
     set in the 'grepprg' option.

     $ vim
     :grep -Hn abc *.log

5. Use the internal ":vimgrep" command:

     $ vim
      :vimgrep abc *.log

Once the quickfix list is populated, you can use the various quickfix commands
to browse the result.

There are also similar commands available for using the location list.

- Yegappan

> And how to jump to, for example, the 5th(and most of time it's hard to tell
> vim the number) result? Or, if no one expected, how can I just close it?
>
> $ vim -c ":grep blabla *.log"
>
> grep.log:1:1 blabla
> grep.log:2:2 blabla
> grep.log:3:3 blabla
> grep.log:4:4 blabla
> grep.log:5:5 blabla
> grep.log:6:6 blabla
> grep.log:7:7 blabla
> grep.log:8:8 blabla
> grep.log:9:9 blabla
> grep.log:10:10 blabla
>
> Press ENTER or type command to continue
>

**Comment by pavoljuhas** [comment]
Would it be too much trouble to have `-q -` read the quickfix errors from stdin?
For example, to jump over all instances of "VimL" in a git repository one could do
```sh
git grep -nw VimL | vim -q -
```

**Comment by vim-ml** [comment]
Yegappan Lakshmanan wrote:

> On Mon, Feb 13, 2017 at 3:22 PM, Bram Moolenaar
> <vim-dev-github@256bit.org> wrote:
> > It's possible in various ways, but still requires the user to add a mapping
> > or autocommand.
> > Problem is always that a file name could actually end in :{number}.
> >
> > I also wanted to make "gf" jump to the right line number, very useful when
> > looking in the output of a compilation command (and not using quickfix for
> > whatever reason). That should be possible, so long as the : character is not
> > in 'isfname'.
> >
> 
> The "gF" command jumps to the line number following the file name.

I guess I should read the help (instead of just writing it :-).

-- 
BLACK KNIGHT: I'm invincible!
ARTHUR:       You're a looney.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
Hi Bram,

On Tue, Feb 14, 2017 at 2:50 PM, Bram Moolenaar <Bram@moolenaar.net> wrote:
>
> Yegappan Lakshmanan wrote:
>
>> On Mon, Feb 13, 2017 at 3:22 PM, Bram Moolenaar
>> <vim-dev-github@256bit.org> wrote:
>> > It's possible in various ways, but still requires the user to add a mapping
>> > or autocommand.
>> > Problem is always that a file name could actually end in :{number}.
>> >
>> > I also wanted to make "gf" jump to the right line number, very useful when
>> > looking in the output of a compilation command (and not using quickfix for
>> > whatever reason). That should be possible, so long as the : character is not
>> > in 'isfname'.
>> >
>>
>> The "gF" command jumps to the line number following the file name.
>
> I guess I should read the help (instead of just writing it :-).
>

:-). This feature was added for the Vim7 release and some more related
commands are:

CTRL-W F - Open the file in a new window and jump to the line number
following the file name.
CTRL-W gF - Open the file in a new tab page and jump to the line number
following the file name.

- Yegappan

**Comment by blueyed** [comment]
btw: https://github.com/kopischke/vim-fetch is a nice plugin for this.
