### ISSUE TITLE
Using cinoptions+=#1 will persist even when cinoptions is reset to defaults

### ISSUE THREAD

**Issue by idbrii** [vim/vim#1475]
I work with lots of scripts that use `#` for comments, so I put `set cinoptions+=#1` in my vimrc and have `setlocal cinoptions&` in ftplugin/cpp.vim (et al).

When I edit a cpp file, `set cinoptions?` returns `cinoptions=`. However, when I edit a cpp file, add a new line after an `#include`, and type `#`, it is indented one space.

If I remove `set cinoptions+=#1` from my vimrc, `#` is not indented.
If instead, I add `cinoptions+=#0` to my ftplugin/cpp.vim, `#` is not indented.

It seems that the setting for  `set cinoptions+=#1` is not correctly wiped when resetting cinoptions. Perhaps partly due to the ambiguity of this option (it's clearly defined how cindent should behave with `#1` and `#0`, but not when neither is set).

(I don't entirely understand why it's indented one space since my shiftwidth is 8.)

----

I can reproduce this with a basic vimrc:

    filetype plugin indent on
    set cinoptions+=#1
    autocmd FileType cpp setlocal cinoptions&

Editing this cpp file:

    #include <iostream>
    #include <cstring>

And trying to add a new include after iostream demonstrates the problem:

    #include <iomanip>

But setting this option demonstrates proper behavior:

    :set cinoptions+=#0

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Included patches: 1-1689
Extra patches: 8.0.0056
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version with GTK2-GNOME GUI.  Features included (+) or not (-):

**Comment by vim-ml** [comment]
On Mo, 13 Feb 2017, David Briscoe wrote:

> I work with lots of scripts that use `#` for comments, so I put `set
> cinoptions+=#1` in my vimrc and have `setlocal cinoptions&` in
> ftplugin/cpp.vim (et al).
> 
> When I edit a cpp file, `set cinoptions?` returns `cinoptions=`.
> However, when I edit a cpp file, add a new line after an `#include`,
> and type `#`, it is indented one space.

Yeah, curbuf->b_ind_hash_comment is not correctly reset.

This patch fixes it.

Best,
Christian
-- 
Es kann nicht jeder um Ablaß gen Rom ziehen.
		-- Deutsches Sprichwort
