### ISSUE TITLE
Broken syntax highlighting (swayconfig)

### ISSUE THREAD

**Issue by diegoviola** [vim/vim#14752]
### Steps to reproduce

Just open `/etc/sway/config` in vim and notice that some commands (e.g. `bindsym` ones) have broken syntax highlighting.

Here's a screenshot of what it currently looks like:

![20240511_15h35m47s_grim](https://github.com/vim/vim/assets/4371/8bc647b7-346b-403a-8a3e-48d988d35aca)

### Expected behaviour

Syntax highlighting is properly applied to all commands.

### Version of Vim

9.1.405

### Environment

Operating system: Arch Linux
Terminal: foot
Value of $TERM: foot
Shell: /usr/bin/bash

**Comment by diegoviola** [comment]
I did some research on this and looks like commit https://github.com/vim/vim/commit/dd83b63eb5b7884c1c882eb984778492f6951ed7 replaced the following line:

    syn region i3ConfigBlockOrphan start=/^\s\+\S/ skip=/^\s\|^$/ end=/^}\?/ contains=swayConfigBindBlockCombo,i3ConfigCriteria,i3ConfigAction,i3ConfigSeparator,i3ConfigActionKeyword,i3ConfigOption,i3ConfigString,i3ConfigNumber,i3ConfigVariable,i3ConfigBoolean,i3ConfigComment,i3ConfigParen keepend extend

With this:

    syn region swayConfigBlockOrphan start=/^\s\+\(--[a-z-]\+ \)*[$a-zA-Z0-9_+]\+ [a-z[]/ skip=/\\$\|$\n^\s*}$/ end=/$/ contains=i3ConfigBindArgument,i3ConfigBindCombo,i3ConfigParen keepend extend

When the lines are reverted and changed to `swayConfigBlockOrphan` the problem goes away, so it must be some regex thing?

Cc @JosefLitos @chrisbra.

**Comment by chrisbra** [comment]
ping @jamespeapen

**Comment by jamespeapen** [comment]
Thanks for the report - I can replicate the issue and will open a PR with a fix. Its not just the `bindsym` that's affected - any keywords with leading spaces are considered errors if they're not surrounded by `{}` in a multiline block.

**Comment by diegoviola** [comment]
@jamespeapen amazing, thanks a lot!

**Comment by JosefLitos** [comment]
Interesting, I would've thought that `skipwhite` would skip whitespace. Apparently it doesn't work like that with match like `/^/`.

I will make a different PR, since the changes required to solve this for all commands would be quite different.

**Comment by diegoviola** [comment]
@JosefLitos thank you!

**Comment by diegoviola** [comment]
@jamespeapen @JosefLitos I tried both of your solutions, took the `swayconfig.vim` from your PRs, put them into ~/.vim/syntax to override the ones from vim.

For some reason the same lines are still being displayed as red, not sure whether I'm doing something wrong or not.

**Comment by diegoviola** [comment]
Ah, ignore my previous comment please, looks like I needed `i3config.vim` as well, it's fine now.
