### ISSUE TITLE
Some text in filetype.vim is incorrectly highlighted

### ISSUE THREAD

**Issue by lkintact** [vim/vim#14765]
### Steps to reproduce

In $VIMRUNTIME\filetype.vim the text `augroup END` in lines 2738 and 3008 is highlighted in `vimAugroupError`, which seems to be incorrect.

### Expected behaviour

.

### Version of Vim

9.1.296

### Environment

.

**Comment by chrisbra** [comment]
That is probably because the list of autocommands is so huge. I think a `:syn sync fromstart` fixes it.

**Comment by chrisbra** [comment]
I am closing this as not a bug.
