### ISSUE TITLE
Multiple delete line statements don't work on the last line

### ISSUE THREAD

**Issue by V1K1NGbg** [vim/vim#14769]
### Steps to reproduce

1. Create any file with more than one line. for ex.:
```
line 1
line 2
line 3
```
2. Go anywhere on the last line:
```
line 1
line 2
line 3| <- cursor
```
3. Type `{n}dd` where `n` is any number above 1
4. Nothing happens

### Expected behaviour

The last line should be deleted.
we can see that if we do just `dd` or `1dd`

Another reason why I think this is incorrect bechavious is because in this example:

```
line 1
line 2
line 3| <- cursor
line 4
```

when you type like `6dd` the outcome is:

```
line 1
line 2
```

### Version of Vim

Tested on both the apt version: `v8.2.2121` and on the latest `v9.1.0412`

### Environment

I don't think it matters, but:
OS: `Pop!_OS 22.04 LTS x86_64 `
DE: `GNOME 42.9`
TERM: `xterm-256color`
SHELL: `bash 5.1.16`

**Comment by chrisbra** [comment]
That is not how the normal `d` command is supposed to work. [Posix states](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/vi.html#tag_20_152_13_51): 
> 2. If there are less than count -1 lines after the current line in the edit buffer, it shall be an error.

**Comment by k-takata** [comment]
> 2\. If there are less than count -1 lines after the current line in the edit buffer, it shall be an error.

Then, the following behavior doesn't follow POSIX?

> Another reason why I think this is incorrect bechavious is because in this example:
> 
> ```
> line 1
> line 2
> line 3| <- cursor
> line 4
> ```
> when you type like `6dd` the outcome is:
> 
> ```
> line 1
> line 2
> ```

**Comment by k-takata** [comment]
> Then, the following behavior doesn't follow POSIX?

Ah, when `:set compatible`, `6dd` doesn't delete the last two lines.

**Comment by itchyny** [comment]
In `compatible` mode (especially when `cpo` includes `-`), both cases do not delete the lines. In `nocompatible` mode, as the original intention of this report, I think it is more consistent to delete the last line when the cursor is at the last line. However, as we can tell from the fact this behavior is related to `cpo--`, it seems to be related to the beep alarmed when we try to move down from the last line. I'm not sure we can only change the behavior of `[count]dd` at the last line without messing the common code.

**Comment by V1K1NGbg** [comment]
Yes, that makes sense when in `compatible` mode but in `nocompatible` mode even considering everything, I still don't understand how this is not a bug.

**Comment by V1K1NGbg** [comment]
> That is not how the normal `d` command is supposed to work. [Posix states](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/vi.html#tag_20_152_13_51):
> 
> > 2. If there are less than count -1 lines after the current line in the edit buffer, it shall be an error.

can you give more of an explenation on why it is that way

**Comment by chrisbra** [comment]
> can you give more of an explenation on why it is that way

You should ask this the authors of POSIX :) 

In any case, I don't think changing this behaviour will be even considered, since this would be a backward incompatible change and is probably how original vi behaves.

**Comment by itchyny** [comment]
We're talking about non-POSIX behavior of Vim, because `6dd` at `:$-2` in `nocompatible` mode deletes the lines in contrary to the POSIX statements. Should `6dd` at `:$` behave like how it already works with `6dd` at `:$-2`, or not? But this raises another question to the opener, should `dj` at `:$`, and `dk` at `:1` delete the current line?

**Comment by chrisbra** [comment]
Yes, my comment was directed directly at the OP, which questioned the POSIX behaviour. Regarding the `dd` behaviour it may seem inconsistent, but I'd prefer not to change it now, because for one, this is backwards incompatible change and secondly, it raises other questions as mentioned already.
