### ISSUE TITLE
Add commentstring for dart filetypes

### ISSUE THREAD

**Issue by RobertBrunhage** [vim/vim#14793]
Missing commentstring for dart filetypes

here is the documentation for comments in Dart https://dart.dev/language/comments

---

I am not familiar with contributing to Vim as I was directed here from NeoVim but I would assume it would be similar to this https://github.com/vim/vim/pull/13921/files and this is from the dart-vim-plugin https://github.com/dart-lang/dart-vim-plugin/blob/master/ftplugin/dart.vim

Here is the reference from NeoVim https://github.com/neovim/neovim/issues/28812

**Comment by chrisbra** [comment]
so, would you like to contribute the Dart filetype plugin?

**Comment by RobertBrunhage** [comment]
I am probably not the best for the contribution as I have no clue the setup of vim and how to test locally etc.

If I could get guidence regarding that then I could potentially take a look at it during the weekend.
