### ISSUE TITLE
has('gui') == 1 even in terminal vim

### ISSUE THREAD

**Issue by rafaeln** [vim/vim#1481]
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 14 2017 17:39:54)
Included patches: 1-329

has('gui') == 1 even in terminal vim, and therefore plugins can't tell whether they are being run in gvim or terminal vim

**Comment by chrisbra** [comment]
this works as intended. The `has("gui")` checks, whether support for a gui has been compiled into the current binary. If you want to know, whether a gui is running, use `has("gui_running")`

**Comment by frogtile** [comment]
where is `gui_running` documented?

**Comment by gdupras** [comment]
In a few places. You can find them with `:helpgrep gui_running`.

**Comment by dpelle** [comment]
> You can find them with `:helpgrep gui_running`.

Yes, followed by `:copen` to see all places.

**Comment by tonymec** [comment]
The help for `has()` says (among others) `See |feature-list| below.` Follow that hotlink and you'll see `gui_running` at its alphabetical place.
