### ISSUE TITLE
listchars: trailmultispace to easily identify the number of trailing spaces

### ISSUE THREAD

**Issue by rcmosher** [vim/vim#14819]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
Markdown files uses two trailing spaces to insert a line break. Trailing spaces can be hard to spot in a file.

**Describe the solution you'd like**
Add a `trailmultispace:c...` setting to listchars. This should be like `leadmultispace:c...` but for trailing spaces.

**Describe alternatives you've considered**
Use `set listchars=trail:c`. This is an okay solution, but it can be difficult to quickly notice if there are exactly two trailing spaces.

Creating a syntax highlight for trailing spaces. This can match the exact number of characters making it easy to spot the number of trailing spaces. However, highlighting empty space can be a little loud.

**Comment by rcmosher** [comment]
I don't like `set listchars=trail:•,eol:¶` as then you have a paragraph sign at the end of every line. The idea is to only draw attention to lines where there are two spaces at the end. That way, for markdown, you can quickly identify if a line break has been added or not.

`:set hls` is good but only lasts until the search pattern changes. I'd like to be able to notice a missing or unintended line break in the process of editing. Of course a search is fine to do a focused check.

I'll look into concealing. That seems like it may be a good option.

**Comment by rcmosher** [comment]
I like how conceal works. I opted for this:
`syntax match Noraml '\s\{2}$' conceal cchar=⏎`
`setlocal conceallevel=2`

**Comment by rcmosher** [comment]
I'll add that vim includes `markdownLineBreak` in it's default syntax files. It matches 2 or more trailing spaces, and appears to be unused for highlighting, at least in my setup. Though I prefer calling out the last 2 spaces separately from any additional spaces so it's clear if there are more spaces then needed.

**Comment by chrisbra** [comment]
That's a decision for @tpope (syntax file maintainer for markdown) to be done.

**Comment by tpope** [comment]
> I'll add that vim includes `markdownLineBreak` in it's default syntax files. It matches 2 or more trailing spaces, and appears to be unused for highlighting, at least in my setup. Though I prefer calling out the last 2 spaces separately from any additional spaces so it's clear if there are more spaces then needed.

It's off by default, but can be assigned highlighting by users that desire it.

> I like how conceal works. I opted for this:
> `syntax match Normal '\s\{2}$' conceal cchar=⏎`
> `setlocal conceallevel=2`

I'd note that markdown.vim makes heavy use of `conceal` to _hide_ syntax, so this would be a confusing and counterproductive behavior to add upstream. But as a local addition to your Vim config it should work great.
