### ISSUE TITLE
Minor syntax highlighting issue with swayconfig files

### ISSUE THREAD

**Issue by diegoviola** [vim/vim#14826]
### Steps to reproduce

This is a continuation of https://github.com/vim/vim/issues/14752, syntax highlighting improved a lot but there is still a minor issue with the following config:

    floating_modifier $mod normal

The "normal" string shows up as red.

Here's a screenshot of what it currently looks like:

![20240522_15h22m56s_grim](https://github.com/vim/vim/assets/4371/7584d1f5-c2d2-43c1-9246-edfa047a0f3f)

### Expected behaviour

Syntax highlighting is properly applied to all commands.

### Version of Vim

9.1.429

### Environment

Operating system: Arch Linux
Terminal: foot
Value of $TERM: foot
Shell: /usr/bin/bash

**Comment by diegoviola** [comment]
Should have been labelled as bug, and not enhancement. Anyway, @JosefLitos @jamespeapen (ping).

**Comment by jamespeapen** [comment]
I can replicate this. It looks like `contained` was introduced in 679f5abb9 to `floating_modifier` in `swayconfig.vim` which seems to conflict with the i3 `floating_modifier`. 

```diff
-syn match i3ConfigKeyword /^floating_modifier [$a-zA-Z0-9+]\+ \(normal\|inverse\)$/ contains=i3ConfigVariable,i3ConfigBindModkey,swayConfigFloatingModifierOpts
+syn match i3ConfigKeyword /floating_modifier [$a-zA-Z0-9+]\+ \(normal\|inverse\)$/ contained contains=i3ConfigVariable,i3ConfigBindModkey,swayConfigFloatingModifierOpts
```

Removing this fixes this problem. However, on checking the docs, it looks like `floating_modifier none` is a valid option that the syntax does not currently cover so I'll send a fix with both.

**Comment by diegoviola** [comment]
@jamespeapen Thanks a lot again for your amazing work!
