### ISSUE TITLE
no help for comment.txt for the newly introduced comment.vim plugin 

### ISSUE THREAD

**Issue by peterwu** [vim/vim#14829]
### Steps to reproduce

1. install a version later than 9.1.0375 (the version that introduced the comment.vim plugin)
2. launch vim
3. `:packadd comment`
4. `:help comment.txt`
5. `E149: Sorry, no help for comment.txt`

The comment.txt does exist at `runtime/pack/dist/opt/comment/doc/comment.txt` but not made available to vim help.

### Expected behaviour

comment.txt should be displayed

### Version of Vim

9.1.0375 or higher

### Environment

Fedora 40 / MacOS Darwin 23.5.0

**Comment by chrisbra** [comment]
This seems to work for me.

**Comment by k-takata** [comment]
`runtime/pack/dist/opt/comment/doc/tags` is missing in our repository.

**Comment by chrisbra** [comment]
Ah, I created it and I thought I commited it, but it seems I forgot and because of gitignoring the tags file, I did not notice.
