### ISSUE TITLE
Msys vim's executable() can't find programs despite them being add in the PATH

### ISSUE THREAD

**Issue by ykhan21** [vim/vim#14823]
### Steps to reproduce

1. On Windows, install msys (https://www.msys2.org/).
3. Install the scoop package manager (https://scoop.sh/) on Windows (not in an msys environment).
4. Install fzf with scoop (`scoop install fzf`) on Windows (not in an msys environment).
5. Open an msys ucrt terminal by typing ucrt in the Windows search bar. This will start bash.
6. Use pacman to upgrade vim.
7. Open another terminal with regular Windows cmd.exe.
8. Observer that fzf is found in cmd but not bash.
9. Add `~/scoop/shims` to the PATH variable in ~/.bashrc (in the ucrt terminal). Source the ~/.bashrc file in bash.
10. Observe that you can now find fzf in bash. `which fzf` should return `/c/Users/KhanY_z23jg7i/scoop/shims/fzf`.
11. Start vim in bash.
12. Run `:echo executable('fzf')`. Observer that vim can't find fzf despite it being added to the path.
13. Add `set rtp+=~/scoop/shims' to the .vimrc and source it.
14. Observe that `:echo executable('fzf')` still can't find fzf.

### Expected behaviour

Vim in msys should be able to find executables present in the PATH environment variable or in the vim runtimepath.

This is strange because Git Bash's vim can find fzf from the PATH variable (without it being added to the runtimepath).

Git Bash's (https://git-scm.com/download/win) vim version: 9.1.264
Msys's vim version: 9.1.380

### Version of Vim

9.1.380

### Environment

OS: Windows
Environment: msys
TERM: xterm
Shell: bash

**Comment by Konfekt** [comment]
Fzf can be found in Vim in Git Bash so that I wonder what the difference to MSYS2 vim is.
Confusingly, at the end Git Bash's vim is mentioned, but MSYS(2) has to be installed.
Would it not help to have the outputs of `%PATH%` respectively `$PATH`, in particular in Vim?

**Comment by Konfekt** [comment]
> Vim in msys should be able to find executables present in the PATH environment variable

Or does this imply that `$PATH` in Vim in MSYS(2) was checked to be the same as in Vim in Git Bash?

**Comment by Konfekt** [comment]
There's a some conversion to include`%PATH%` into `$PATH`, so maybe that's where the difference lies. Git Bash Vim is a more common setup than MSYS Vim, so perhaps some path in `%PATH%` is amiss?

**Comment by Konfekt** [comment]
You might have better chances with `export PATH=$PATH:"$USERPROFILE/scoop/shims"` in `~/.bashrc` (or `$HOME`).
If neither `$USERPROFILE`, nor `$HOME`, then `/c/Users/username`.
Maybe `let $BASH_ENV = $HOME.'/.bashrc' is needed as well. 
By the way, I thought rather `~/.bash_profile` than `~/.bashrc` to be read by Git Bash MSYS2, so maybe also MSYS2 itself?

**Comment by ykhan21** [comment]
When I add the export ~/.bashrc, MSYS picks it up fine as evidenced by `which fzf` in MSYS. However, MSYS vim's executable() function does not pick it up.

I will try the other PATH recommendations and report back later.

**Comment by benknoble** [comment]
It looks like tilde-expansion was not performed in the broken case; compare `~/scoops/shim` with `c:/users/username/scoops/shim`

**Comment by Konfekt** [comment]
Yes, in terms of robustness: `/c/Users/username` > `$HOME/USERPROFILE` > `~/`, from experience.

**Comment by ykhan21** [comment]
Thanks. /c/users/username, $HOME, and $USERPROFILE worked as opposed to the ~.
