### ISSUE TITLE
\r is autoreplaced with \r\n in regexp replacements

### ISSUE THREAD

**Issue by vx0** [vim/vim#1484]
I had to produce a text file with \r\r\n line breaks from a file with dos linebreak. So I tried the obvious way
`:e ++ff=unix file.txt`
`%s/\r/\r\r/g`
And Vim autoreplaced every \r with \n. This is obviously not the intended behaviour.

 `%s/^V^M/^V^M^V^M/g` acts the same way, btw

**Comment by chrisbra** [comment]
that is explained in the docs. Please ask user questions on the appropriate forums.

**Comment by chrisbra** [comment]
In retrospect, the answer might have sound to harsh and I apologize for that. Please note, that the behaviour you are seeing is described in the help at `:h sub-replace-special`. so internally a `\r` is always handled as adding a newline when used in the replacement part of the `:s` command.
