### ISSUE TITLE
Bracketed paste does not ignore autoindent

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#1485]
With `autoindent` and bracketed paste mode on, pasted text gets indented. I would expect it to work as with `paste` on, that is, the text is inserted literally without reformatting. Is there a reason for such a difference, or is it a bug?

I am pasting from macOS clipboard using CTRL-V, if that matters, using Vim 8.0.237.

**Comment by k-takata** [comment]
Already fixed in 8.0.0238.

**Comment by chrisbra** [comment]
fixed in https://github.com/vim/vim/releases/tag/v8.0.0238
