### ISSUE TITLE
[''] and [{}] behave differently as repeat function parameter

### ISSUE THREAD

**Issue by yu3s** [vim/vim#14856]
### Steps to reproduce

1. cat test.vim
```vim
vim9script

var a1 = repeat([''], 2)
var a2 = ['', '']
var b1 = repeat([{}], 2)
var b2 = [{}, {}]

echomsg a1
echomsg a2
echomsg b1
echomsg b2

a1[0] = '0'
a1[1] = '1'
a2[0] = '0'
a2[1] = '1'

b1[0]['0'] = 0
b1[1]['1'] = 1
b2[0]['0'] = 0
b2[1]['1'] = 1

echomsg a1
echomsg a2
echomsg b1
echomsg b2
```
2. vim --clean -c "so ./test.vim"

output

```vim
['', '']
['', '']
[{}, {}]
[{}, {}]
['0', '1']
['0', '1']
[{'0': 0, '1': 1}, {'0': 0, '1': 1}]
[{'0': 0}, {'1': 1}]
```

### Expected behaviour

b1 and b2 are the same

### Version of Vim

9.1.446

### Environment

os: ubuntu18.04
terminal: windows terminal
$TERM: xterm-256color
shell: bash4.4.20

**Comment by girishji** [comment]
I think I this is not a bug. When you do `var b1 = repeat([{}], 2)`, the 2 copies of dict are references to the same space in memory. It is the same dict backing the two references. I think this is how it works in python also. In the first case (a1), things are assigned by value (not reference).

**Comment by yu3s** [comment]
> I think this is not a bug. When you do `var b1 = repeat([{}], 2)`, the 2 copies of dict are references to the same space in memory. It is the same dict backing the two references. This is how it works in python also. In the first case (a1), things are assigned by value (not reference).

Thanks, I'm not good at python
