### ISSUE TITLE
Vim syntax bug

### ISSUE THREAD

**Issue by matveyt** [vim/vim#14858]
### Steps to reproduce

```
:syntax enable
:edit newfile.vim
:put='echohl ErrorMsg'

" ErrorMsg text above gets concealed

```

### Expected behaviour

The problem is here
https://github.com/vim/vim/blob/ef73374dc3e4bf8104ba31d5b22517f8028b467a/runtime/syntax/vim.vim#L101

`Conceal` is an option and cannot be used as keyword (also mentioned at `:h :syn-keyword`). Therefore, we must switch to syn-match:

```VimL
syn match vimHLGroup contained /\<Conceal\>/
```

As `syntax/vim.vim` is a generated file, `runtime/syntax/generator/gen_syntax_vim.vim` should be fixed instead.

### Version of Vim

9.1.115

### Environment

Windows GVim

**Comment by chrisbra** [comment]
ping @h-east for the required generator changes

**Comment by h-east** [comment]
I can't reproduce it. (`ErrorMsg` is not concealed)

**Comment by matveyt** [comment]
@h-east 

Need also to set `concealcursor=n` and `conceallevel` greater than zero to see any visual effect.

Also note that output of `:syn list vimHLGroup` does not show "conceal" as one of the matches. So `echohl Conceal` is _not_ highlighted.
