### ISSUE TITLE
Update syntax/markdown.vim: Don't allow space between link text and URL

### ISSUE THREAD

**Issue by VimWei** [vim/vim#14855]
### Steps to reproduce

Detail:
https://github.com/tpope/vim-markdown/issues/212

### Expected behaviour

Don't allow space between link text and URL

https://github.com/tpope/vim-markdown/commit/f405b47fd8774ecd5e808e6de9c85d9029da251c

### Version of Vim

9.1.0429

### Environment

Win 10 pro 22H2
gvim_9.1.0429_x64_signed.exe

**Comment by chrisbra** [comment]
Typically, maintainers send update once they think a new version should be distributed with Vim. So please ask @tpope to send an update.

**Comment by tpope** [comment]
That change could have a negative impact for some users, so it's not something I will be rushing into Vim proper.
