### ISSUE TITLE
No indentation of HTML tags in PHP files

### ISSUE THREAD

**Issue by lkintact** [vim/vim#14850]
### Steps to reproduce

1. Run `gvim.exe --clean`
2. Put the following code into the buffer:
```
<html>
<body>

<?php
echo "in PHP";
?>

<div>
<span>
in span
</span>
</div> 
</body>
</html>
```
3. Execute `:set filetype=php`
4. Type <kbd>=G</kbd> to indent the code. No indentation happens.

### Expected behaviour

The code should be indented like this:
```
<html>
<body>

<?php
echo "in PHP";
?>

<div>
	<span>
		in span
	</span>
</div> 
</body>
</html>
```

### Version of Vim

9.1.443

### Environment

OS: Windows 10 Home
Terminal: GUI

**Comment by chrisbra** [comment]
well, this seems a bit strange, to expect that the php filetype does HTML indenting. Perhaps the PHP indent script can check the syntax and return the HTML indent for HTML parts in php files. Assuming the php syntax script does already detect HTML within a php filetype (which I didn't check). I think the HTML indent script does something similar for JS indenting, so perhaps this could be an example on how to do it.

https://github.com/vim/vim/blob/0076ddc07dc1d97afcf3252fd361885abbaf23d5/runtime/indent/php.vim#L1-L7

You may want to report over there and check with the maintainer if this is feasable.

**Comment by lkintact** [comment]
Thank you, turns out [here](https://github.com/2072/PHP-Indenting-for-VIm/issues/2) the maintainer explicitly says he won't support HTML indenting, explains why and links a solution.
I guess the issue can be closed.
