### ISSUE TITLE
BufWinEnter event cannot be triggered when open directory

### ISSUE THREAD

**Issue by yu3s** [vim/vim#14865]
### Steps to reproduce

1. cat test.vim
```vim
augroup Test
        autocmd!
        autocmd! BufWinEnter * echomsg 'BufWinEnter'
        autocmd! BufWinLeave * echomsg 'BufWinLeave'
augroup END
```
2. vim  -c "so ./test.vim | tabnew . | tabclose"

message output

```
BufWinLeave
```

### Expected behaviour

Trigger BufWinEnter event

### Version of Vim

9.1.447

### Environment

os: ubuntu18.04
terminal: windows terminal
$TERM: xterm-256color
shell: bash4.4.20

**Comment by matveyt** [comment]
This has nothing to do with `tabnew`. It's Netrw. You don't get BufWinEnter with it and I've no idea why.

**Comment by yu3s** [comment]
> This has nothing to do with `tabnew`. It's Netrw. You don't get BufWinEnter with it and I've no idea why.

You are right, I found that `vnew` works, but `vnew .` doesn't.

**Comment by chrisbra** [comment]
I guess you may need `nested`

**Comment by yu3s** [comment]
> I guess you may need `nested`

https://github.com/vim/vim/blob/8904d672befb496cf224f01bc042683bb6120e81/src/buffer.c#L370

**Comment by yu3s** [comment]
1. It's nothing to do with netrw, it's still the same if it's not executed
https://github.com/vim/vim/blob/8904d672befb496cf224f01bc042683bb6120e81/runtime/plugin/netrwPlugin.vim#L38

2. The reason for the problem
https://github.com/vim/vim/blob/8904d672befb496cf224f01bc042683bb6120e81/src/buffer.c#L370

I don't need to solve it
