### ISSUE TITLE
set realtivenumber clips the buffer when scrolling fast

### ISSUE THREAD

**Issue by DanielViberg** [vim/vim#14877]
### Steps to reproduce

1. Make a file with lots of vertical text
2. vim -u NONE test.txt -c 'set colorcolumn=50 | set relativenumber'
3. Hold ctrl+d 
4. Observe clipping 

### Expected behaviour

No clipping

### Version of Vim

VIM - Vi IMproved 9.1 (2024 Jan 02, compiled May 30 2024 08:19:22) Included patches: 1-450

### Environment

Ubuntu 22.04, xterm-256color
![bug](https://github.com/vim/vim/assets/27137435/593e89b0-fdea-482d-b5f7-600a2cabf680)

**Comment by zeertzjq** [comment]
What do you mean by "clipping"? It's hard to see what's wrong from the video.

**Comment by DanielViberg** [comment]
Around 00:24 in the video, if looking at the frames, one instance of the buffer looks like this:
![image](https://github.com/vim/vim/assets/27137435/1b47b2fb-41d1-4691-b9ab-0ca4e14db03b)
This is during a Ctrl+u

**Comment by chrisbra** [comment]
Well, relativenumber and colorcolumn require additional redraws, which may explain what you are seeing. It has been improved quite a bit with patch 8.1.374 but the effect cannot be completely avoided.

**Comment by DanielViberg** [comment]
Cant replicate on other machine, closing for now.
