### ISSUE TITLE
vsplit does not honor size when Vim GUI window is maximized

### ISSUE THREAD

**Issue by zhen-huan-hu** [vim/vim#1487]
In Windows, when Vim GUI window is maximized, `vsplit` command would not honor the size such as `30vsplit`. The new window is always half the size of the entire GUI window. When the GUI window is not maximized, `30vplit` works properly.

**Comment by duianto** [comment]
It works fine for me, it vsplits by the specified number, when GVIM is maximized or restored (un-maximized).
Vim version 8.0.339
Windows 10 Version 1607 (OS Build 14393.693)

**Comment by chrisbra** [comment]
cannot reproduce. Please give a reproducible example starting from gvim -u NONE -N --noplugins

**Comment by zhen-huan-hu** [comment]
It seems to be working properly under 'gvim -u NONE -N --noplugins'

But if I run 'gvim --noplugins', the issue persists. Any reason of that?

**Comment by akanosora** [comment]
I found that it is this line in my gvimrc that causes the behavior

```
set guioptions-=T lines=60 columns=150
```

But why?

**Comment by zhen-huan-hu** [comment]
Please ignore my post above. It is these statements cause the issue:
```
augroup UserInterface
  autocmd!
  autocmd VimResized * exe "normal \<C-w>="
augroup END
```

**Comment by zhen-huan-hu** [comment]
@chrisbra Why is VimResized triggered after the window has already been resized though? And why is it only triggered when Vim GUI window is maximized but not otherwise?

**Comment by chrisbra** [comment]
I think VimResized is issued because a second scrollbar needs to be added. That is a famous particularity.

**Comment by zhen-huan-hu** [comment]
But why is it not triggered when Vim GUI is not maximized even though the second scrollbar is added?

**Comment by chrisbra** [comment]
> But why is it not triggered when Vim GUI is not maximized even though
> the second scrollbar is added?

My guess would be, when Vim is maximized, it has to to resize the window 
to make room for the scrollbar (e.g. it has to adjust the 'lines' and 
'columns' options, effectively shrinking the visible screen size), while 
when Vim is not maximized, it can grow the main Vim window and keep 
'lines' and 'columns' constant.
