### ISSUE TITLE
triggering bufwinenter event causes duplicate buffer

### ISSUE THREAD

**Issue by yu3s** [vim/vim#14870]
### Steps to reproduce

1. cat test.vim
```vim
vim9script

def Test()
        echomsg tabpagebuflist(1)
enddef

augroup Test
        autocmd!
        autocmd! BufWinEnter * Test()
augroup END
```
2. vim --clean ./test.vim  -c "so ./test.vim | call term_start('ls', {'hidden': v:true, 'term_finish': 'close'})"

messages output
[1, 1]

---
1. vim --clean ./test.vim -c "call term_start('ls', {'hidden': v:true, 'term_finish': 'close'})|echomsg tabpagebuflist(1)"

messages output

[1]

### Expected behaviour

output [1]

### Version of Vim

9.1.447

### Environment

os: ubuntu18.04
terminal: windows terminal
$TERM: xterm-256color
shell: bash4.4.20

**Comment by yu3s** [comment]
vim --clean -p 1.txt 2.txt -c "so ./test.vim | call term_start('ls', {'hidden': v:true, 'term_finish': 'close'})"
output [2, 1]
however, bufname(2) is "2.txt"

**Comment by chrisbra** [comment]
no this patch isn't correct. The problem is, Vim may temporarily open a new window for the hidden buffer in order to process some messages and/or close the terminal buffer and this triggers the autocommand here.

**Comment by yu3s** [comment]
> no this patch isn't correct. The problem is, Vim may temporarily open a new window for the hidden buffer in order to process some messages and/or close the terminal buffer and this triggers the autocommand here.

If it is normal, is there a way to check and then exit?
```vim
def TabSort()
	var idx: number
	var nr = tabpagenr()
	var nrs = tabpagenr('$')
	var str: string
	var tmpstr: string
	var strlist: list<string>

	if nrs == 1 || &ft == '' || tabpagewinnr(nr) != 1
		return
	endif

	str = bufname()
	for i in range(1, nrs)
		idx = tabpagebuflist(i)[0]
		tmpstr = bufname(idx)

		if i == nr || getbufvar(idx, "&filetype") == ''
			continue
		elseif tmpstr == str
			execute($"tabnext {i} | tabclose {nr}")
			break
		elseif strlist->index(tmpstr) != -1
			execute($"tabclose {i}")
			break
		endif

		strlist->add(tmpstr)
	endfor
enddef

augroup line_vim
	autocmd!
	autocmd! BufWinEnter * TabSort()
augroup END
```

**Comment by zeertzjq** [comment]
Maybe you can check if `win_gettype()` returns `autocmd` for a window.

**Comment by yu3s** [comment]
> Maybe you can check if `win_gettype()` returns `autocmd` for a window.

Thanks, it works well
