### ISSUE TITLE
disable status line

### ISSUE THREAD

**Issue by lesorubshayan** [vim/vim#14882]
the bottommost line which shows current mode, current line and part of file(All,top,bot)

i want to disable it

set laststatus=0 didn't worked and aucommand BufNew,BufEnter * set laststatus=0 also

in tmux for example there is special option for it

i know it can sound strange cause knowing current mode is vague, but i want to try without this info

**Comment by chrisbra** [comment]
I guess you want `:set noruler`.

Also please note, there will always be a status line if there more than one window.

**Comment by bfrg** [comment]
Vim doesn't support a global status line (yet). There's already an open issue for that: https://github.com/vim/vim/issues/10153

**Comment by chrisbra** [comment]
For user questions, either open a new discussion thread or use vi.stackexchange.com or use the mailinglist. Closing
