### ISSUE TITLE
setqflist() does not understand vim9script lambda

### ISSUE THREAD

**Issue by peterwu** [vim/vim#14896]
### Steps to reproduce

1. save the following vim9script code as test.vim
```
vim9script

def QfGetOldFiles(): list<dict<string>>
    return ['/tmp/f1', '/tmp/f2', '/tmp/f3']->map((_, v) => {
        return { 'filename': v }
    })
enddef

# 1: this works
nnoremap <silent> f1 <Cmd>call setqflist([], ' ',
            \ {
            \   'items': <SID>QfGetOldFiles()
            \ })<Bar>copen<CR>

# 2: this uses legacy lambda style and it works
nnoremap <silent> f2 <Cmd>call setqflist([], ' ',
            \ {
            \   'items': ['/tmp/f1', '/tmp/f2', '/tmp/f3']
            \            ->map({ -> { 'filename': v:val }})
            \ })<Bar>copen<CR>

# 3: this uses vim9 lambda style and it does NOT work
nnoremap <silent> f3 <Cmd>call setqflist([], ' ',
            \ {
            \   'items': ['/tmp/f1', '/tmp/f2', '/tmp/f3']
            \            ->map((_, v) => {
            \     return { 'filename': v }
            \   })
            \ })<Bar>copen<CR>
```

2. vim -u NONE test.vim
3. :source %
4. press f1, and the 3 files are correctly displayed in quickfix window
5. press f2, and the 3 files are correctly displayed in quickfix window
6. press f3, vim gives an error complaining `E121: Undefined variable _`

Note: 
Snippet #3  uses the same vim9script lambda as in QfGetOldFiles() function. 

### Expected behaviour

The sample code snippet #3 should also work with vim9 style lambda when vim9script is specified for the entire file.

### Version of Vim

9.1.393

### Environment

Fedora 40
foot: v1.17.2
bash: v5.2.26

**Comment by guojinyu12** [comment]
this may not be a `setqfilst` bug, the error complaining is misleading. the lambda is not in vim9scipt syntax when runing.
```
vim9script
# 4: this uses vim9 lambda style and it does work（Parentheses must exist when returning a dict in lambda )
nnoremap <silent> f4 <Cmd>vim9 call setqflist([], ' ',
            \ {
            \   'items': ['/tmp/f1', '/tmp/f2', '/tmp/f3']
            \            ->map((_, v) => ({ 'filename': v }))
            \ })<Bar>copen<CR>

# 5: this uses vim9 lambda style and it does work
nnoremap <silent> f5 <ScriptCmd>call setqflist([], ' ',
            \ {
            \   'items': ['/tmp/f1', '/tmp/f2', '/tmp/f3']
            \            ->map((_, v) => ({ 'filename': v }))
            \ })<Bar>copen<CR>
```
ps: the lambda leaking <CR> after `->map((_, v) => {` and  `return { 'filename': v }` at code snippet # 3.

**Comment by peterwu** [comment]
Yes, I figured it had something to do with vim using legacy script when invoking :ex commands by default. <ScriptCmd> solves the problem. I'm closing this bug. Thanks.
