### ISSUE TITLE
`set gdefault` causes find/replace to skip words

### ISSUE THREAD

**Issue by dkarter** [vim/vim#1489]
Not sure if this is intended behavior but after enabling `gdefault` find/replace operations started skipping words if multiple matches exist in the same line. It will basically just try to replace the first instance of the word instead of every occurrence.

See gif below for example:
![](http://g.recordit.co/UWOMFOo6o2.gif)

In this example I was trying to find and replace the word `set` with the word `get` for demo purposes. I used `gc` and selected `n` for each match.

I tested on two different machines with different dotfiles.

Can anyone confirm this issue?

**Comment by chrisbra** [comment]
If you use the 'g' flag while gdefault has been set, this effectively reverts the behaviour and does only replace the **first** occurance per line.

**Comment by dkarter** [comment]
Oh ok thanks for clarifying that.
