### ISSUE TITLE
Disable undo when running complete()

### ISSUE THREAD

**Issue by Shougo** [vim/vim#1490]
I can undo the input in omnifunc, but I cannot undo the input in `complete()`.

Related issue: https://github.com/vim/vim/pull/1174

The minimal vimrc:

```vim
set nocompatible
set completeopt+=noinsert,noselect
set completeopt+=noinsert
set noshowmode
set shortmess+=c

function! s:complete() abort
  call complete(1, Omni(0, ''))
  return ''
endfunction

function! Omni(findstart, base) abort
  if a:findstart == 1
    return 1
  endif
  return ['January', 'February', 'March',
        \ 'April', 'May', 'June', 'July', 'August', 'September',
        \ 'October', 'November', 'December']
endfunction

set omnifunc=Omni

inoremap <right> <c-r>=<sid>complete()<cr>
```

The reproduce ways:

* Press `i` and `<Left>`
* The popup menu is displayed by `complete()`
* Press `a` in the popup menu
* Press `<Esc>u`
* I cannot undo!

* Restart Vim
* Press `i` and `<C-x><C-o>`
* The popup menu is displayed by `omnifunc`
* Press `a` in the popup menu
* Press `<Esc>u`
* I can undo!

**Comment by Shougo** [comment]
Note: I have tested the problem in Vim 8.0.339

**Comment by brammool** [comment]
Shougo wrote:

> I can undo the input in omnifunc, but I cannot undo the input in `complete()`.
> 
> Related issue: https://github.com/vim/vim/pull/1174
> 
> The minimal vimrc:
> 
> ```vim
> set nocompatible
> set completeopt+=noinsert,noselect
> set completeopt+=noinsert
> set noshowmode
> set shortmess+=c
> 
> function! s:complete() abort
>   call complete(1, Omni(0, ''))
>   return ''
> endfunction
> 
> function! Omni(findstart, base) abort
>   if a:findstart == 1
>     return 1
>   endif
>   return ['January', 'February', 'March',
>         \ 'April', 'May', 'June', 'July', 'August', 'September',
>         \ 'October', 'November', 'December']
> endfunction
> 
> set omnifunc=Omni
> 
> inoremap <right> <c-r>=<sid>complete()<cr>
> ```
> 
> The reproduce ways:
> 
> * Press `i` and `<Left>`

You press <Right> here.

> * The popup menu is displayed by `complete()`
> * Press `a` in the popup menu
> * Press `<Esc>u`
> * I cannot undo!
> 
> * Restart Vim
> * Press `i` and `<C-x><C-o>`
> * The popup menu is displayed by `omnifunc`
> * Press `a` in the popup menu
> * Press `<Esc>u`
> * I can undo!

Thanks for the clear explanation.  The undo is saved only after the "a"
was inserted.  I'll fix it.  I can use your example for a test.

-- 
The budget process was invented by an alien race of sadistic beings who
resemble large cats.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
fixed in https://github.com/vim/vim/releases/tag/v8.0.0341

**Comment by Shougo** [comment]
> You press <Right> here.

Sorry, it is my mistake.

> fixed in https://github.com/vim/vim/releases/tag/v8.0.0341

Yes, I have confirmed that it is fixed.
Thank you!
