### ISSUE TITLE
Just a typo in the docs

### ISSUE THREAD

**Issue by lkintact** [vim/vim#14901]
### Steps to reproduce

In `$VIMRUNTIME/pack/dist/opt/matchit/doc/matchit.txt`, line `177`, `hat been loaded` should be changed to `has been loaded`.

### Expected behaviour

.

### Version of Vim

9.1.443

### Environment

.

**Comment by ubaldot** [comment]
I plan to send a PR for improving the docs of `:h typename()` soon. I could fix this as well if you all agree.

**Comment by chrisbra** [comment]
this issue belongs to https://github.com/chrisbra/matchit/
