### ISSUE TITLE
Escape sequences in python block

### ISSUE THREAD

**Issue by plitter** [vim/vim#14914]
### Steps to reproduce

1. Use vimrc with 
```
py3 << eof
foo = '\s'
eof
```
2. See error:
```
Error detected while processing .../vimrc:
line    3:
<string>:1: SyntaxWarning: invalid escape sequence '\s'
Press ENTER or type command to continue
```

### Expected behaviour

Python block should either be ignored or vim would need to be able to parse python or parsed with python, maybe?

### Version of Vim

VIM - Vi IMproved 9.1 Included patches: 1-429

### Environment

OS: Arch Linux
Terminal: foot version: 1.17.2 
TERM: foot
Shell: GNU bash, version 5.2.26(1)-release (x86_64-pc-linux-gnu)

### Logs and stack traces

```shell
Error detected while processing .../vimrc:
line    3:
<string>:1: SyntaxWarning: invalid escape sequence '\s'
Press ENTER or type command to continue
```

**Comment by zeertzjq** [comment]
The same happens with Python interpreter:
```
>>> foo = '\s'
<stdin>:1: SyntaxWarning: invalid escape sequence '\s'
```
So I don't think this is a bug.

**Comment by chrisbra** [comment]
closing then.

**Comment by plitter** [comment]
@zeertzjq your right. I don't know why I started getting the error then. But I fixed it using the raw strings in python. Thanks for the help!
