### ISSUE TITLE
--log flag isn't in the man page

### ISSUE THREAD

**Issue by chdiza** [vim/vim#14916]
### Steps to reproduce

Run `man vim`.

### Expected behaviour

On the vim_dev mailing list @chrisbra mentioned starting with `--log`.  I didn't recall knowing about this, so I went to `man vim` expecting it to be listed there.  But it isn't.

I tried to made this note on the googlegroup web page, but that page absurdly claimed I don't have permission to make a post.  I'm subscribed to the vim_dev mailing list, and I've made posts using the google groups webpage before.

### Version of Vim

9.1.465

### Environment

Linux Mint 21

**Comment by errael** [comment]
FYI, `vim --help`
```
...
   --log <file>         Start logging to <file> early
...
```

**Comment by chrisbra** [comment]
you should use `:h --log`  :)

**Comment by errael** [comment]
In the interest of compromise, there's `vim -c ':he --log`

**Comment by chdiza** [comment]
I know I can (and did) find it in the vim help, but it should also be in the man page.  Thanks for putting it there!
