### ISSUE TITLE
Incorrect syntax highlighting for debsources files

### ISSUE THREAD

**Issue by 4wk-** [vim/vim#14913]
### Steps to reproduce

1. Open a new file
2. Past the text `deb https://packages.sury.org/php/ bullseye main`
3. Type the command `:set syn=debsources` to turn color on
![vimOK](https://github.com/vim/vim/assets/1439550/f2bca12e-2f42-4a99-b6a3-791bdff2b445)

4. Change the word `bullseyes` to `nodistro` and notice the word is not colored in green anymore
![vimKO](https://github.com/vim/vim/assets/1439550/65c5f1e9-6718-41b9-90c0-d8eb159b8154)

### Expected behaviour

`nodistro` should be (?) a valid [distrib name](https://github.com/nodesource/distributions?tab=readme-ov-file#new-update-%EF%B8%8F) in `debsourcesDistrKeyword` syntax.

![vimHI](https://github.com/vim/vim/assets/1439550/7aaa4751-420d-4442-a98b-a329e04fb36d)

### Version of Vim

VIM - Vi IMproved 8.2

### Environment

Debian 11.8
Windows Terminal
xterm-256color
Bash  5.1.4

**Comment by chrisbra** [comment]
Please report to the Debian team, that are maintaining the list of valid distribution names https://github.com/vim/vim/blob/master/runtime/syntax/shared/debversions.vim

In any case, you want to verify this with the latest Vim version and not Vim 8.2 which is already quite old.

**Comment by 4wk-** [comment]
Thanks for the quick reply! Ok, so I should report my issue [here](https://salsa.debian.org/vim-team/vim-debian)? (not familiar with what's outside of Github, sorry)
I know I can report bugs through the Debian mailing list, but I feel it might be overkill x)

(Vim 8.2 because Debian, but I plan to upgrade soon! Hope one day we will have an apt `.deb` repo for Vim too! 🙏)

**Comment by chrisbra** [comment]
You are using Debian, so you can simply use reportbug command. It will end up with @jamessan and I suppose he will take care of it. BTW:  I am not sure `nodistro` is a valid distro for Debian/Ubuntu, perhaps it's a no-issue after all.

**Comment by jamessan** [comment]
Yeah, this is behaving as intended. Only known releases are highlighted.
