### ISSUE TITLE
comment package and C++ (and folds...)

### ISSUE THREAD

**Issue by LucHermitte** [vim/vim#14911]
When using the _comment_ package in C++, lines are commented with `'commentstring'` which defaults to `/*%s*/`. 

In a ideal world, they should be commented with `// %s`. But given `'commentstring'` is already used for another purpose (i.e. to create marker based folds), I'm not at ease to change the default used so far -- even if it seems to make more sense when I think about it.

**My feature request is:**

Ideally, it would be nice if _comment_ package had a way to read another option that would override `'commentstring'` value for those cases. It could be something like `b:commentstring` / `g:{&ft}_commentstring` (global filetype based overrides could be enough).

**Other open question:**

Shouldn't `'commentstring`' be `// %s` in C++?

**Context:** Vim [v9.1.0465](https://github.com/vim/vim/releases/tag/v9.1.0465)

**Comment by clason** [comment]
Quite a few filetypes derive their commentstring (previously implicitly, now explicitly since #14843) from C even though that may not be the "default" single-line commentstring for them -- besides C++, this is C#, ObjC, and D. Now that these ftplugins set the commentstring explicitly, that could be changed more easily.

(Neovim has recently done so -- in fact, for C as well since we use C99 and `// %s` comments in our own codebase, but that's not the case for Vim of course.)

**Comment by chrisbra** [comment]
>  lines are commented with 'commentstring' which defaults to /*%s*/.

Which should be valid in C++, right? 

Why not simply set the commentstring option for cpp filetypes then? 

> g:{&ft}_commentstring (global filetype based overrides could be enough).

is that something you'd like to contribute then?

**Comment by LucHermitte** [comment]
> Which should be valid in C++, right?

`/* %s */` is valid in C++, but definitively not what "we" use usually. 

> Why not simply set the commentstring option for cpp filetypes then?

I can indeed. But it doesn't feel natural as `'commentstring'` is documented to be used for folding: the same variable serves two purposes. Also, there is the question whether C++ default for `commentstring` will be upgraded to `// %s` -- in that case this is no longer required.

> > g:{&ft}_commentstring (global filetype based overrides could be enough).
>
> is that something you'd like to contribute then?

If you think it makes sense, I can.

**Comment by clason** [comment]
> Also, there is the question whether C++ default for commentstring will be upgraded to // %s -- in that case this is no longer required.

For the record, that is exactly what I suggested in my earlier comment -- no need to introduce a second mechanism if the first one can be made to work with a minor change.

**Comment by chrisbra** [comment]
let's just keep it simple for now and prepare the change to ftplugin/cpp.vim. Do you want to give this a try @LucHermitte ?

**Comment by LucHermitte** [comment]
> let's just keep it simple for now and prepare the change to ftplugin/cpp.vim. Do you want to give this a try @LucHermitte ?

OK. I can give a try. 

But then, what about clason's other suggestions?

- Changing the default for the other filetypes listed (which I don't use => I can't confirm whether this is a good idea)?
- Harmonizing with neovim that have upgraded C default value for `commentstring` to C99 comments?

Also aren't there any risk of regression/change of behaviour for people currently relying on the current `/* %s */` in C++? (and in C if we do the upgrade)

**Comment by clason** [comment]
For the record, I am _not_ suggesting changing the default/C commentstring (since Vim uses `/* %s */` comments in its own codebase).

**Comment by chrisbra** [comment]
Let's just change it in cpp.vim and leave the others away. People who complain have then to override their prefered commenting style in the ftplugin in an after directory. 

FWIW: we tend to use `//` commenting now in C in Vim. We just haven't changed the style of all old comments.

**Comment by LucHermitte** [comment]
Thanks!
