### ISSUE TITLE
Fuzzy-matching support for insert-completion not working (as expected)

### ISSUE THREAD

**Issue by vbd** [vim/vim#14921]
### Steps to reproduce

Function of patch 9.1.0463

Buffer (not saved, no filetype) contains:
```
one
two
three
```

Typing `o` followed by `CTRL+N` only offers `one` for selection.

`:echo &completeopt` returns `longest,menuone,popup,noinsert,fuzzy`

### Expected behaviour

At least I expected to offer `one` and `two` in the selection.

### Version of Vim

9.1.0465

### Environment

OS: Windows 11
gVim

**Comment by habamax** [comment]
It might be different to the linked issue
