### ISSUE TITLE
Type mismatch error in ccomplete#Complete

### ISSUE THREAD

**Issue by kyllingstad** [vim/vim#14927]
### Steps to reproduce

1. Start `vim --clean path/to/source.cpp` in a C/C++ project directory that contains a ctags file (e.g. `./tags`)
2. Enter the name of a `struct` variable followed by a dot (e.g. `myobject.`) and press `<c-x><c-o>`.

For me, this produces the error:
```
Error detected while processing function ccomplete#Complete:
line  200:
E1013: Argument 2: type mismatch, expected dict<string> but got dict<any>
```
I suspect that the line number is slightly misleading and that it has to do with the difference in `dict` types between [lines 211 and 213](https://github.com/vim/vim/blob/ae4641d68e2c01ee4847395bdb78a8c9c52394c7/runtime/autoload/ccomplete.vim#L211) in `runtime/autoload/ccomplete.vim`.

### Expected behaviour

Completion should succeed (or fail cleanly).

### Version of Vim

9.1.1-445

### Environment

* Operating system: Arch Linux on WSL
* Terminal: tmux in Windows Terminal
* Value of `$TERM`: `screen-256color`
* Shell: Zsh 5.9

**Comment by kyllingstad** [comment]
I checked, and changing `dict<string>` to `dict<any>` in [line 213](https://github.com/vim/vim/blob/ae4641d68e2c01ee4847395bdb78a8c9c52394c7/runtime/autoload/ccomplete.vim#L213) appears to fix the problem.

**Comment by chrisbra** [comment]
can you please create a PR for that one then?

**Comment by kyllingstad** [comment]
I'll be happy to do that. But please note that my vimscript expertise and insight into the Vim runtime are very limited, so I don't know whether this little change will have unintended consequences.

**Comment by chrisbra** [comment]
Yes understood. But  I think it makes sense. `taglist()` returns a list of dicts and each dict can contain either strings (all fields except for `static`) or number (`static`) values . So I think `dict<any>` is correct here.

**Comment by yegappan** [comment]
Yes.  It is correct to change the type from dict<string> to dict<any> in this case.

**Comment by chrisbra** [comment]
@yegappan do you think it makes sense to start documenting return types for all internal functions, e.g. `taglist()` returns `list<dict<any>>`?

**Comment by yegappan** [comment]
Yes.  It will be helpful to document the return type of the builtin functions.  May we can add a `Return type: ....` line to the description of each builtin function?
