### ISSUE TITLE
Inconsistency between macvim and vim in :redir result

### ISSUE THREAD

**Issue by nv-quan** [vim/vim#14929]
### Steps to reproduce

`touch a.txt && echo "Some text" > a.txt`

In VIM
2. vim -u NONE
3. :redir > result.txt
4. :!cat a.txt
5. redir end

In MacVim
2. New clean window
3. - 5. Similar steps

### Expected behaviour

Content of a.txt should appear in result.txt in both MacVim and Vim. But it only appear when I tried with MacVim.
I expect vim to redir the command output as well which it doesn't. I'm not sure if this is a bug so please let me know, I will close the ticket if it's not.

### Version of Vim

Vim 9.1 with 1-457 patch. MacVim r179 (Vim 9.1.0)

### Environment

MacOS, iterm2, zsh

**Comment by chrisbra** [comment]
Not sure, this might be a bug or not, but `:redir` is really meant to redirect VIM messages, not whatever you echo on your terminal. In addition, the terminal might be switching screens which could matter here (although I still see the same issue when disabling it) and of course the various shell options. 

However, you should use a proper method to get shell output, not `:redir`, use `systeml()`, `systemlist()`, or use shell redirection properly.

**Comment by nv-quan** [comment]
Thanks! Indeed redir is not a right command for this. Closing this for now.
