### ISSUE TITLE
Remaining &shiftwidth references in indent plugins

### ISSUE THREAD

**Issue by tyru** [vim/vim#1493]
From vim_dev:
[Remaining &shiftwidth references in indent plugins - Google Groups](https://groups.google.com/forum/#!topic/vim_dev/BcDThxEkwNA)

I open this issue because changes are too large and vim_dev is not suitable for tracking the changes.
for example: https://github.com/derekwyatt/vim-scala/pull/136
GH issue is useful to see the links to the issues / pull requests.

I also created Google spreadsheet to track the changes (**see the sheet "2nd"**):
[The List of Vim indent plugin maintainers - Google spreadsheet](https://docs.google.com/spreadsheets/d/1-HeWlsLC-tJDfuXQjtkZmY5UwXakAuYg83z9nz7nl2w/edit?usp=sharing)

**Comment by tyru** [comment]
@brammool Would you like to include my patch of vim-scala?
because @derekwyatt (the author of vim-scala) says:

> The plugin is now part of the standard vim distribution. You should be making pull requests there instead.
> https://github.com/derekwyatt/vim-scala/pull/136

**Comment by brammool** [comment]
Takuya Fujiwara wrote:

> @brammool Would you like to include my patch of vim-scala?
> because @derekwyatt (the author of vim-scala) says:
> 
> > The plugin is now part of the standard vim distribution. You should
> > be making pull requests there instead.

That only works if the pull request was made by the maintainer.
It's the maintainer that needs to integrate any changes and then send
them to me for inclusion in the distribution.

-- 
Engineers understand that their appearance only bothers other people and
therefore it is not worth optimizing.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Shougo** [comment]
> That only works if the pull request was made by the maintainer.

So I think the pull request must be reviewed and confirmed it works in github.
If possible by the maintainer.

**Comment by tyru** [comment]
Just for information: old discussion was #578

**Comment by derekwyatt** [comment]
Sorry Takuya. I'll try to get to this soon.

**Comment by tyru** [comment]
@derekwyatt Thanks!

**Comment by chrisbra** [comment]
I think this can be closed as of 036986f1507d223549d11

**Comment by tyru** [comment]
@chrisbra No.
There are lots of (40 files!) unfixed indent plugins.
I updated the column "Has Bram included?".
Please see this.

[The List of Vim indent plugin maintainers - Google spreadsheet](https://docs.google.com/spreadsheets/d/1-HeWlsLC-tJDfuXQjtkZmY5UwXakAuYg83z9nz7nl2w/edit?usp=sharing)

**Comment by chrisbra** [comment]
oh okay. Sorry.

**Comment by tyru** [comment]
This seems to be fixed at https://github.com/vim/vim/commit/3ec574f2b549f456f664f689d6da36dc5719aeb9 .
Thanks!
