### ISSUE TITLE
c_space_errors = 1 breaks proper comment termination

### ISSUE THREAD

**Issue by klement** [vim/vim#1494]
having .vimrc containing

```
set nocompatible

filetype plugin indent on

let c_space_errors=1
```

and running `vim x.c`

then typing `o/*<CR><CR>/`

results in 

```
/*
 * 
 * /
```

instead of 

```
/*
 *
 */
```

two issues:

1.) extra spaces following `*`
2.) comment block was not properly terminated `* /` instead of `*/`

**Comment by chrisbra** [comment]
cannot reproduce. Neither with a separatre vimrc:
```
~$ cat /tmp/vimrc
set nocompatible
filetype plugin indent on
let c_space_errors=1
~$ cat -A foobar.c
cat: foobar.c: No such file or directory
~$ vim -u /tmp/vimrc --cmd 'call feedkeys("o/*\n\n/\e:wq\n", "t")' foobar.c
~$ cat -A foobar.c
$
/*$
 *$
 */$
~$
```

Please provide minimal steps to reproduce.

**Comment by chrisbra** [comment]
Also
```
~$ vim -u NONE -N --cmd ':filetype plugin indent on' --cmd ':let c_space_errors=1' --cmd  'call feedkeys("o/*\n\n/\e:wq\n", "t")' foobar.c
~$ cat -A foobar.c
$
/*$
 *$
 */$
~$
```
does not show that behaviour.

**Comment by klement** [comment]
Hmm, strange, multiple people were able to see this issue when discussed in
ycm bug I reported. Should be linked in this thread. I actually see the
issue with the config I mentioned.

**Comment by chrisbra** [comment]
try disabling all plugins. See the [faq](http://vimhelp.appspot.com/vim_faq.txt.html#faq-2.5)

**Comment by chrisbra** [comment]
BTW: what vim version?

**Comment by klement** [comment]
I did. I used vim -Nu <above-vimrc> x.c to reproduce.
I'll post the vim version tomorrow, it's on a different machine. Built from
git about 3days ago..

**Comment by chrisbra** [comment]
Try using `--noplugins` switch. However the other report at the ycm repository looks like it was about completing? However, I am not sure, how a syntax configuration should matter when inserting text.

**Comment by klement** [comment]
Yes, I originally thought that the problem is caused by YCM plugin, but
that didn't turn out to be the case. If you read the latest posts in the
YCM bug report, you'll see a few configs which show the issue without any
plugins loaded. The minimal test case is the one provided here, which
manifests in my instance too.

**Comment by micbou** [comment]
The completefunc needs to be called before typing the last `/` so the way to reproduce the issue is:
```
~$ vim -u NONE -N --cmd ':filetype plugin indent on' --cmd  'call feedkeys("o/*\n\n\<C-X>\<C-U>/\e:wq\n", "t")' foobar.c
~$ cat -A foobar.c
$
/*$
 *$
 * /$
```
Note that the `c_space_errors` option doesn't need to be set to reproduce it.

**Comment by klement** [comment]
I actually don't need to call completefunc and can reproduce it by just
typing per OP with OP vimrc..

**Comment by chrisbra** [comment]
@micbou thanks, now I can reprocude it. I have posted a patch [here](https://groups.google.com/d/msg/vim_dev/W37eODi2QZ8/moTkainmDQAJ)
@klement I really don't know, why it happens for you, please try the mentioned patch. I suspect however that either a global plugin is remapping the 'o' key or something similar. So please try with the `--noplugin` switch and additionaly also add the 'n' flag to the `feedkeys()` call. That should make sure, that no mappings interfere.
