### ISSUE TITLE
Netrw incorrectly handles folders containing [] in their names

### ISSUE THREAD

**Issue by lkintact** [vim/vim#14952]
### Steps to reproduce

1. Create a folder named `[test]` and put a file inside it
2. Run `gvim.exe ./`, a directory listing is shown
3. Select `[test]` from the listing and press `Enter`. gVim shows nothing.

### Expected behaviour

gVim should show the contents of `[test]`

### Version of Vim

9.1.466

### Environment

OS: Windows 10 Home
Terminal: GUI

**Comment by chrisbra** [comment]
ah, one of the famous differences between how filenames are handled differently on Windows and Unix :/

**Comment by chrisbra** [comment]
Hm, there seems to be a bug in how wildcards are expanded on Windows. This does not seem to work:
```
echo len(glob('c:\temp\[test]\*', 0,1,1))
0
```

If I replace either side of the brackets `[]` by `?` it starts working:
```
echo len(glob('c:\temp\[test?\*', 0,1,1))
1
echo len(glob('c:\temp\?test]\*', 0,1,1))
1
```
It seems like vim handles a sequence of `[...]` on Windows specifically and handles it as globs, without checking whether those are expanded. So the only way to make this work is to replace those `[]` by `?` instead. Using the following patch seems to work:
```
diff --git a/runtime/autoload/netrw.vim b/runtime/autoload/netrw.vim
index 300729eba..e8495c37a 100644
--- a/runtime/autoload/netrw.vim
+++ b/runtime/autoload/netrw.vim
@@ -5799,7 +5799,12 @@ fun! s:NetrwGlob(direntry,expr,pare)
    endif
    let w:netrw_liststyle= keep_liststyle
   elseif v:version > 704 || (v:version == 704 && has("patch656"))
-   let filelist= glob(s:ComposePath(fnameescape(a:direntry),a:expr),0,1,1)
+   let path= s:ComposePath(fnameescape(a:direntry),a:expr)
+   if has("win64")
+     " glob fails for paths like 'c:\temp\[test]\*'
+     let path=substitute(path, '[][]', '?', 'g')
+   endif
+   let filelist= glob(path, 0, 1, 1)
    if a:pare
     let filelist= map(filelist,'substitute(v:val, "^.*/", "", "")')
    endif
```
Note: I am only patching the v:version > 704, because Vim 7.4 is very old now. Also, I think fnameescape() should not be used for `glob()` but only when used for commands that expect a filename. But who knows what breaks if we take this out ...

**Comment by chrisbra** [comment]
So while I was there, I went down the rabbit hole and the following patch fixed `glob()` behaviour on windows. not sure of any unwanted side-effects:
```diff
diff --git a/src/charset.c b/src/charset.c
index 470698f0e..42c5ed0ca 100644
--- a/src/charset.c
+++ b/src/charset.c
@@ -2462,7 +2462,10 @@ rem_backslash(char_u *str)
                || (str[1] != NUL
                    && str[1] != '*'
                    && str[1] != '?'
-                   && !vim_isfilec(str[1]))));
+                   && !vim_isfilec(str[1]))
+               || (str[1] != NUL
+                   && (str[1] == '[' ||
+                       str[1] == ']'))));
 #else
     return (str[0] == '\\' && str[1] != NUL);
 #endif
```

**Comment by chrisbra** [comment]
Actually, the current behaviour is documented, see `:h wildcard`. So I think we will need the first patch or a slightly similar one:
```vim
   if has("win64")
    " escape [ so it is not used as wildcard character, see :h wildcard
    let path= substitute(path, '[', '[[]', 'g')
```

**Comment by lkintact** [comment]
FWIW, opening `[testfile]` from a Netrw listing if `[testfile]` is a file works just fine. Also, perhaps #5059 is relevant.

**Comment by chrisbra** [comment]
Yes, that's because it doesn't use globbing to get the contents of the directory.
