### ISSUE TITLE
CI: Test_ColonEight_MultiByte() fails with the latest GHA image

### ISSUE THREAD

**Issue by k-takata** [vim/vim#14954]
### Steps to reproduce

Run Test_ColonEight_MultiByte() on the latest GitHub Actions image ([20240603.1](https://github.com/actions/runner-images/releases/tag/win22%2F20240603.1)).

You can see the following errors:
> 	command line..script D:/a/vim-kt/vim-kt/vim/src/testdir/runtest.vim[607]..function RunTheTest[57]..Test_ColonEight_MultiByte line 11: Expected not equal to 'Xtest/日��本��語��の��フ��ァ��イ��ル��.txt'
>	command line..script D:/a/vim-kt/vim-kt/vim/src/testdir/runtest.vim[607]..function RunTheTest[57]..Test_ColonEight_MultiByte line 12: Pattern '\\~' does not match 'Xtest/日��本��語��の��フ��ァ��イ��ル��.txt'

### Expected behaviour

Test_ColonEight_MultiByte() doesn't fail.

### Version of Vim

9.1.0470

### Environment

OS: Windows Server 2022 https://github.com/actions/runner-images/releases/tag/win22%2F20240603.1

**Comment by k-takata** [comment]
This is because the 8.3 names are disabled in the D: drive in the latest GHA image:
![image](https://github.com/vim/vim/assets/840186/d81b8072-d669-4d25-a789-ad8615c23eb4)

To enable 8.3 names again, we can use the command `fsutil 8dot3name set D: 0` before running the test.
Another way is to check the status of 8dot3name before running the test and skip the test if 8.3 names are disabled. However, the result of the fsutil command will be localized. It might not easy to check the status of 8dot3name.

**Comment by chrisbra** [comment]
Thanks, I thought it must have been a change on the CI infrastructure then. 
I suppose we can use `C` drive then, similar to what is done for `Test_ColonEight()`?
