### ISSUE TITLE
Support for syntax highlighting of `jinja` files

### ISSUE THREAD

**Issue by psss** [vim/vim#14964]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
Currently the syntax for `jinja` files is not provided and such files are hard to read.

**Describe the solution you'd like**
The `jinja.vim` included among supported syntax files.

**Describe alternatives you've considered**
Download and store syntax file in user's home directory.

**Additional context**
Syntax file found here: https://www.vim.org/scripts/script.php?script_id=1856

**Comment by chrisbra** [comment]
If you want this to be included with Vim, please reach out to the maintainer and ask him to submit it here for distribution with Vim.
