### ISSUE TITLE
PMenuMatch has no effect for initial list of candidates

### ISSUE THREAD

**Issue by habamax** [vim/vim#14968]
### Steps to reproduce

1. `vim -Nu NONE`
2. `:set completeopt+=fuzzy,menuone`
3. `:hi PMenuMatch ctermfg=red`
4. add some text, e.g. `hello helion help`
5. on the new line type `h<C-n>`

### Expected behaviour

`h` should be highlighted right away.

[![asciicast](https://asciinema.org/a/4mr42ejiOHcoFEtWi2N3a7yjT.svg)](https://asciinema.org/a/4mr42ejiOHcoFEtWi2N3a7yjT)

### Version of Vim

9.1.477

### Environment

Debian12, bash

**Comment by chrisbra** [comment]
Hm, this might be expected. The match completes only what you have typed *after the completion menu has been displayed* to reduce the number of candidates. So to see the effect, this works better: `:set completeopt+=noinsert`
