### ISSUE TITLE
b:changedtick can be “unlocked”

### ISSUE THREAD

**Issue by ZyX-I** [vim/vim#1496]
Under vim-8.0.342 consider the following code:

```VimL
echo islocked('b:changedtick')
unlockvar b:changedtick
echo islocked('b:changedtick')
```

This will yield `1` then `0`. This still will not make one able to edit or delete this variable though. Previously trying to unlock b:changedtick was an error.

**Comment by brammool** [comment]
Nikolai Pavlov wrote:

> Under vim-8.0.342 consider the following code:
> 
> ```VimL
> echo islocked('b:changedtick')
> unlockvar b:changedtick
> echo islocked('b:changedtick')
> ```
> 
> This will yield `1` then `0`. This still will not make one able to
> edit or delete this variable though. Previously trying to unlock
> b:changedtick was an error.

Yeah, previously it didn't work at all.  It's the same for some other
builtin variables. Might as well give a nice error message.

-- 
An alien life briefly visits earth.  Just before departing it leaves a
message in the dust on the back of a white van.  The world is shocked
and wants to know what it means.  After months of studies the worlds
best linguistic scientists are able to decipher the message: "Wash me!".

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
