### ISSUE TITLE
Esc is always interpreted as Enter in command-line

### ISSUE THREAD

**Issue by shiqf** [vim/vim#14977]
### Steps to reproduce

1. Run vim --clean -u  test.vim
only one line
```vim
" test.vim
vim9script
```
2. `:tab h<Esc>`
3. Result: open a help file

### Expected behaviour

exit the command line back to the normal mode

### Version of Vim

9.1.477

### Environment

archlinux

**Comment by yegappan** [comment]
This is not a bug.  See https://vimhelp.org/options.txt.html#cpo-x.

**Comment by GuestSneezeOSDev** [comment]
why not fork it and implement it in your version of `vim`?
