### ISSUE TITLE
Some wrong return types specified in help

### ISSUE THREAD

**Issue by errael** [vim/vim#14982]
### Steps to reproduce

- `job_info` with no arg return `list<job>` not `list<any>`
- `job_start` returns `job` not `number`
- `job_status` returns `string` not `job`
- `job_stop` seems more like a boolean, but I guess for builtins number is specified?

### Expected behaviour

See above

### Version of Vim

9.1.478

### Environment

linux/gtk3

**Comment by errael** [comment]
Oh, I just came across `Return type: |vim9-boolean|` for something. So for `job_stop`?

**Comment by chrisbra** [comment]
I tested most of those:
```
typename(job_info())
list<any>
typename(job_stop(job))
number
```

The other two will be fixed in 2 minutes.

**Comment by errael** [comment]
> ```
> typename(job_info())
> list<any>
> ```

@chrisbra The above test is incomplete and encounters #13433, because of the empty list. If there's a job things are different.
```
vim9script

var v0 = job_info()
echo printf("v0: %s '%s'", typename(v0), v0)

var v1: list<job> = job_info()      # NOTE: no type error
echo printf("v1: %s '%s'", typename(v1), v1)

var j = job_start('cat < /dev/null')

var v2 = job_info()
echo printf("v2: %s '%s'", typename(v2), v2)
```
Produces the output
```
v0: list<any> '[]'
v1: list<job> '[]'
v2: list<job> '['process 1614380 run']'
```
`list<job>` seems the correct Return type. (to end this long story)

---

> ```
> typename(job_stop(job))
> number
> ```

The help for `job_stop` says
```
The result is a Number: 1 if the operation could be executed,
0 if "how" is not supported on the system.
```
which is boolean. There's a variety of functions scattered around that say `Return type: vim9-boolean`.  I had incorrectly assumed that meant it returns a number but should be treated as a boolean (and maybe there was some legacy script implications mixed in). I just tested `digraph_set` and it reports boolean; I was wrong.

Probably the right thing is to fix `job_stop` like `digraph_set`, but hardly worth it; if there was a concerted effort to fix all cases where legacy returns a `bool` as a `number`, that would be another thing.

**Comment by chrisbra** [comment]
alright, I'll update job_info() as well
