### ISSUE TITLE
statusline: Restoring a highlight inside an item group causes the whole item group to disappear

### ISSUE THREAD

**Issue by antoineco** [vim/vim#14993]
### Problem

Inside a statusline, an item group disappears whenever it contains a highlight restore item, i.e. either `%*`, `%0*` or `%##`.
However, the same item group gets rendered if a `%N*` or `%#Name#` item is positioned _before the item group_.

### Steps to reproduce

```vim
:hi User1 guifg=Red
```
```vim
:hi User2 guifg=Blue
```

1. Inner segment highlighted with `User1`, no other user highlight in the statusline:
    ```vim
    :set statusline=--%(x%1*MyFunc%*x%)--
    ```

    statusline is rendered without the item group, neither the colored text nor the inner 'x's are printed:
    ![image](https://github.com/neovim/neovim/assets/3299086/2bd2391a-9754-422b-a458-32ad06b3f409)

2. Item group prefixed with another user highlight (it doesn't matter which one):
    ```vim
    :set statusline=--%2*%(x%1*MyFunc%*x%)--
    ```

    statusline is rendered with the item group, but not with the desired appearance due to workarounds:
    ![image](https://github.com/neovim/neovim/assets/3299086/1fda9cc9-cb33-4e1b-81bd-7bedd614ed9b)

    Here the item group no longer disappears, but having to prefix it with a named or `User{N}` highlight is a hack that results in visual glitches, and possibly other side effects.

### Expected behaviour

In the first case above, the statusline should have been rendered with the text "MyFunc" highlighted in red, with all surrounding characters highlighted according to the built-in `StatusLine` highlight group:
![image](https://github.com/neovim/neovim/assets/3299086/370b8960-fe92-478e-814f-a4c5185f0436)

### Version of Vim

9.0.1499

### Environment

_Operating system:_ Debian 12 inside WSL2
_Terminal:_ wezterm
_Shell:_ zsh 5.9

### Logs and stack traces

N/A

xref. neovim/neovim#29306

**Comment by zeertzjq** [comment]
This seems to work if a `minwid` is added to the group item:
```vim
:set statusline=--%1(x%1*MyFunc%*x%)--
```

From the source code, it seems that the special behavior when `minwid` is omitted is intentional, but it's not clear what the reason for such behavior is.

**Comment by antoineco** [comment]
@zeertzjq correct, this is intentional and documented in the help section for 'statusline'.

It does indeed work, but for my use case it is undesirable. For more context: I want that group to only appear if it contains information (LSP diagnostics), and a minid would defeat that purpose.

**Comment by chrisbra** [comment]
Hm, I wonder what the fallout would be if we change this. Does it only happen with custom user highlighting and not with custom highlighting groups?

**Comment by antoineco** [comment]
This seems to happen only with `User{N}` highlights yes. As far as I understand, based on the Vim help, these highlights are treated differently:

- They can be restored (to `StatusLine`) with `%*`, unlike "named" highlight groups. 
- The `StatusLineNC` background color is applied automatically in non active windows.

Both of these properties make it really easy to craft minimal, plugin-less status bars.

My current workaround is to replace the `User2 fg=blue` in the example above with a `fg` and `bg` which match `StatusLine` exactly. This is how I captured the screenshot under "Expected behavior".
While this hack works, it defeats the purpose of leveraging `User {N}` highlight groups. 

To me the observed behavior isn't the intended one: since the text inside the item group isn't an _empty string_ (ref. 'statusline' help) there is no reason for it to disappear.

**Comment by zeertzjq** [comment]
This does happen with custom highlight groups. E.g. using `Search`:
```vim
:set statusline=--%(x%#Search#MyFunc%##%)--
```

**Comment by antoineco** [comment]
TIL about `%##`. Previous comment edited, thanks!

**Comment by chrisbra** [comment]
I see thanks. We had previous discussions on the statusline and how sometimes empty sections are hidden when they shouldn't been but this would always be a backwards incompatible change and I am sure someone would complain, if we change the existing behaviour. 

I think the best work-around is to use a custom function `%{%MyFunc()%}` and your function you can test if you want to return anything, then use the minwidth item so it is displayed correctly or return an empty string to hide this section. Would this work for you?

**Comment by antoineco** [comment]
> sometimes empty sections are hidden **when they shouldn't be** but this would always be a backwards incompatible change and I am sure someone would complain

If the behavior is known to be _wrong_ I can't say I agree with the statement, but I respect the decision.
At the very least let's consider fixing the docs.

This thread now contains two workarounds, so I'm closing the issue. Thanks for chiming in!
