### ISSUE TITLE
Why is ~/.vim/vimrc read before ./defaults.vim?

### ISSUE THREAD

**Issue by git-madresc** [vim/vim#15000]
For me, this question is in no way new, vim does this as long as I remember. However, some distributions have defaults defined, that I do not want. like 'set mouse=a'. And I can not disable this behavior in my ~/.vim/vimrc.

So, my questions would be:
- Is there any good reason, why ~/.vim/vimrc is not processed last?
- Is there any way, this order could change at some point in the future?

**Comment by chrisbra** [comment]
If you have a custom vimrc, defaults.vim should not be read. If it still is, this must be configured in your environment specifically.
