### ISSUE TITLE
highlight groups PmenuMatch and PmenuMatchSel some buggy

### ISSUE THREAD

**Issue by Shane-XB-Qian** [vim/vim#15021]
### Steps to reproduce

1. did not expect icase of match:
![image](https://github.com/vim/vim/assets/13550529/2855c3c1-a6fa-4eab-adac-da79d67ba25f)

2. did not reflect the change of base:
// os.if -> the `if` highlighted -> changed to os.i which backspace the `f` -> the `i` highlight missed.
![image](https://github.com/vim/vim/assets/13550529/d3332900-7103-4351-a0d5-57469f5aed5d)

### Expected behaviour

work.

### Version of Vim

v9.1.493

### Environment

linux

### Logs and stack traces

#14694

**Comment by Shane-XB-Qian** [comment]
if ok, let me know _if_ was intended to design like that, then let it be..

**Comment by Shane-XB-Qian** [comment]
@glepnir if ok, let me know _if_ was intended to design like that, then let it be..

**Comment by Shane-XB-Qian** [comment]
and @chrisbra what do you think? 
i supposed this two hl groups fit for genenral compl, not regarding to fuzzy or something as seems you said somewhere.

**Comment by glepnir** [comment]
emm a simple reprodcue script will be useful

**Comment by Shane-XB-Qian** [comment]
and @chrisbra what do you think? 
i supposed this two hl groups fit for any compl, and not regarding to fuzzy or something, as seems you said somewhere.

**Comment by glepnir** [comment]
```C
diff --git a/src/insexpand.c b/src/insexpand.c
index 28e4d344e..c673df927 100644
--- a/src/insexpand.c
+++ b/src/insexpand.c
@@ -1448,7 +1448,7 @@ ins_compl_show_pum(void)
     char_u *
 ins_compl_leader(void)
 {
-    return compl_leader;
+    return compl_leader != NULL ? compl_leader : compl_orig_text;
 }

 /*
```

could you try this patch.

**Comment by Shane-XB-Qian** [comment]
and @chrisbra what do you think? 
i supposed this two hl groups fit for any compl, and not regarding to fuzzy or something, as seems you said somewhere.

**Comment by glepnir** [comment]
you publish duplicate comments.

**Comment by Shane-XB-Qian** [comment]
> you publish duplicate comments.

yea~ sry, we are living in the great cn, sry for the wonderful network~ :sweat_smile:

**Comment by Shane-XB-Qian** [comment]
> could you try this patch.

yes, the item 2 seems worked after this patch
// item 1 remained.

**Comment by zeertzjq** [comment]
It may be necessary to store the start and the end of the matched position when using non-fuzzy completion, so that highlighting of matched text works when using 'ignorecase', but I'm not entirely sure about that. That'll also be required to highlight matched text for cmdline non-fuzzy completion, as in cmdline completion the pattern can contain wildcards.

Speaking of that, should matched text be highlighted for cmdline completion as well?

**Comment by glepnir** [comment]
okay good to knwo. I am still finding a way to reproduce the peoblem 1.. could you provide more information about problem 1

**Comment by Shane-XB-Qian** [comment]
i have not tried to use `fuzzy` of completeopt yet, but generally fuzzy should be same like the case ignored.
// it is not the `caseignore`, but the icase of compl items attribute.

**Comment by glepnir** [comment]
ins_compl_bs then invoke ins_compl_free it free leader like currently  leader is `cl` both freed. so when bs a leader the ins_compl_leader get a null pointer then nothing highlighted. but the `compl_orig_text` keep the original value.

**Comment by glepnir** [comment]
> i have not tried to use `fuzzy` of completeopt yet, but generally fuzzy should be same like the case ignored. // it is not the `caseignore`, but the icase of compl items attribute.

you mean the problem 1 is run with the completeopt no fuzzy right ?

**Comment by Shane-XB-Qian** [comment]
no, it is not regarding to fuzzy of completeopt option, or to `fuzzy` as common sense usually its case was not matter.
icase is a complete_item attribute.
// not sure pum in cmdline, it maybe no icase attribute.

**Comment by glepnir** [comment]
could you please provide a reproduce step with a mininal config ..

**Comment by glepnir** [comment]
reproduced.

**Comment by glepnir** [comment]
> Speaking of that, should matched text be highlighted for cmdline completion as well?

should be :)

**Comment by Shane-XB-Qian** [comment]
> Speaking of that, should matched text be highlighted for cmdline completion as well?

i donot know, i am not a fan of pum in cli, i usually like its behavior as in bash cli.
// but as i know @yegappan impl it as different way like insert-compl, it should be some different?
