### ISSUE TITLE
auto nohlsearch

### ISSUE THREAD

**Issue by habamax** [vim/vim#15039]
'hlsearch' is very useful but at the same time too intrusive.

Help topic states specifically that `:nohlsearch` doesn't work in autocommand (actually it also doesn't work in timer callbacks) so there is no obvious way to make it auto turned off.

There is vim-cool plugin by @romainl and the essense of it might be the following snippet I am currently using:

```
# turn off hlsearch after:
# - doing nothing for 'updatetime'
# - getting into insert mode
augroup auto_nohlsearch | au!
    set updatetime=2000
    noremap <Plug>(nohlsearch) <cmd>nohlsearch<cr>
    noremap! <expr> <Plug>(nohlsearch) execute('nohlsearch')[-1]
    au CursorHold * call feedkeys("\<Plug>(nohlsearch)", 'm')
    au InsertEnter * call feedkeys("\<Plug>(nohlsearch)", 'm')
augroup END
```

Should we add this example, even though it is "hackish", to the help topic right after `:h :nohlsearch` or maybe even a simple plugin in the same way `comment` was added?

[![asciicast](https://asciinema.org/a/vBRE7DeuLuxGtQIIaq2WWuxu9.svg)](https://asciinema.org/a/vBRE7DeuLuxGtQIIaq2WWuxu9)

**Comment by romainl** [comment]
The doc is riddled with "hackish" examples like this so why not one more? I find the idea of adding a small plugin better, though. MacVim releases are lagging a bit so I didn't have a chance to play with your commenting plugin yet but it definitely looks like the way to go.

FWIW, [vim-cool](https://github.com/romainl/vim-cool) was a pretty successful attempt to solve *one* of my pet peeves with `hlsearch`: that it lingers on after it stopped being relevant. Whether it is through a built-in plugin, a snippet in the doc, a third-party plugin, or in the core, the problem can be considered solved at this point and, as such, doesn't deserve much attention.

But that still leaves the other one: that the highlighting affects all windows, for which there is no workaround AFAIK. If some effort can be made to improve `hlsearch`, I think that's where it would be most useful.

**Comment by chrisbra** [comment]
There is an entry in todo.txt to make 'hlsearch' global/local option. I remember I spent some time several years ago looking into it (but at least back then it wasn't that simple, but I forgot details).

Regarding @habamax request, does it make sense to add this (and possibly also the highlight-yank implementation from the help page) into the [vim-scripts library](https://github.com/vim/vim/blob/master/runtime/autoload/dist/vim.vim). Not sure if we would be littering the library and if this is a particular good idea or rather a bad one 🤷

**Comment by romainl** [comment]
> (mostly for Neovim compatability)

_Sigh…_

**Comment by chrisbra** [comment]
alright then can you make this a real PR then please? Please don't forget a bit of documentation and also please leave adjusting 'updatetime' option value alone.

**Comment by girishji** [comment]
I have something similar in my config, but I prefer 10 sec delay, and also have <esc> do `nohls` in addition. Maybe you can make the timeout configurable by using `autocmd CursorHold * timer_start(timeout - &ut, (_) => feedkeys("\<plug>(nohlsearch)", 'm'))`. 
I also prefer keeping highlights in insert mode as I replace some highlighted fragments (for instance).

**Comment by benknoble** [comment]
One other note: if hlsearch is made global/local, I’d prefer the default to stay as is (it’s remarkably useful when looking at commit diffs + an open buffer to quickly highlight long function names in all windows, for example).

**Comment by habamax** [comment]
> Maybe you can make the timeout configurable by using `autocmd CursorHold * timer_start(timeout - &ut, (_) => feedkeys("\<plug>(nohlsearch)", 'm'))`.

Wouldn't it trigger if after updatetime but before additional timeout there would be cursor movement? And what if at that time I will search for another thing? Say if there is 6 seconds of additional timeout, I theoretically can do another search which would be "unhighlighted" almost right away. Not sure though.

**Comment by girishji** [comment]
> Wouldn't it trigger if after updatetime but before additional timeout there would be cursor movement? And what if at that time I will search for another thing? Say if there is 6 seconds of additional timeout, I theoretically can do another search which would be "unhighlighted" almost right away. Not sure though.

Correct, there is no good solution. Although I set `updatetime` to 10 seconds in my profile, it has an undesired effect: the swap file is not written soon enough. Ideally, there should be an independent `hlsearchtimeout` variable implemented in the core.

**Comment by mmrwoods** [comment]
Hi, this is an issue which has always bugged me and it's great to see a simple opt-in solution added to the vim distribution.

Would it be possible to add something to make it easier to detect whether this has been enabled though? Perhaps just following the common pattern of setting a global variable when the plugin is loaded, e.g.

```
if exists("g:loaded_nohlsearch")
  finish
endif
let g:loaded_nohlsearch= 1
```

Why bother with this? Well, for years I've settled on a variation of the suggestion in the help for `incsearch` to only highlight search matches while the search cmdline is active, which I've also included in a plugin I wrote to help colleagues getting started with vim (https://github.com/mmrwoods/vim-friendly). I'd like to automatically detect vim-cool and this new optional nohlsearch package and disable the similar feature in my plugin if someone has opted to use some other solution.

At the moment I have this experimental code, which is pretty darn fugly because I have to catch an exception trying to check if the `auto_nohlsearch` autocmd group exists. I guess I could check &rtp, but that wouldn't be great either.

```
" Disable friendly hlsearch if vim-cool or nohlsearch plugin installed
" See https://github.com/romainl/vim-cool
" And https://github.com/vim/vim/pull/15042
function! friendly#compat#hlsearch()
  try
    if exists("g:loaded_cool") || !empty(autocmd_get({'group' : 'auto_nohlsearch'}))
      augroup friendly_hlsearch | au! | augroup END
    endif
  catch /E367:/
    " ignore errors re auto_nohlsearch autocmd group not found
  endtry
endfunction
```

**Comment by habamax** [comment]
@mmrwoods https://github.com/vim/vim/pull/15402

**Comment by mmrwoods** [comment]
Wow, that was fast! And I was just going to say that using &rtp doesn't seem all that bad...

```
function! friendly#compat#hlsearch()
  if exists("g:loaded_cool") || !empty(findfile('plugin/nohlsearch.vim', &rtp))
    augroup friendly_hlsearch | au! | augroup END
  endif
endfunction
```

But `exists('g:loaded_nohlsearch')` would definitely be nicer again, thanks!
