### ISSUE TITLE
Better handling of numbers when using Ctrl-A and Ctrl-X

### ISSUE THREAD

**Issue by tuzz** [vim/vim#15033]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

Currently, pressing `Ctrl-A` or `Ctrl-X` on a really big number, e.g. `99999999999999999999999` causes it to be set to `2^64-1` (or similar) rather than the expected value `100000000000000000000000`. This is surprising and could be the source of bugs if used in a macro, for example. The exact value varies between Vim and Neovim but both exhibit the same issue.

Secondly, I have regularly been caught out (and so have others I have spoken to) by Vim treating words such as `article-123` as negative and therefore incrementing to `article-122`, which seems counterintuitive, rather than `article-124`. The intended meaning of `-` is probably a delimiter in this case, rather than unary negation so `article-124` seems more correct. I know you can set `nrformats+=unsigned` to treat all numbers as positive but I still want Ctrl-A on `-123` to become `-122`.

Another common occurrence of this counterintuitive behaviour is when (informally) writing a range as `3-5`. If the cursor is on `-` or `5` and `Ctrl-A` is pressed, I would expect `3-6` but the result is `3-4`. Again, `5` is treated as negative.

**Describe the solution you'd like**
1. Would it be possible for Vim to support big numbers for Ctrl-A and Ctrl-X, or are we limited to 64-bit integers?

2. Would it be possible to introduce a new setting, perhaps `nrformats+=contextual` to make Vim first check if there's a space immediately preceding the hyphen (i.e. ` -123`) before treating it as negative number? Otherwise, it would be treated as positive. I suppose `unsigned` and `contextual` would be mutually exclusive settings, in that case.

3. Perhaps `nrformats+=contextual` could be set by default?

**Describe alternatives you've considered**

If we decide to keep the behaviour the same, perhaps we could document these quirks in Ctrl-A, Ctrl-X, nrformats.

**Comment by distobs** [comment]
Got the "contextual" format to work with the normal and visual modes. Would like to know chrisbra's take on this issue before sending a PR!
