### ISSUE TITLE
has("python") and has("python3") can only return 1 (true) on one of them and :python or :python3 breaks when used after each other

### ISSUE THREAD

**Issue by dezza** [vim/vim#1504]
Opening vim with `vim -u NONE` and typing

```vim
echo has('python')
``` 
or 
```vim
echo has('python3')
``` 
**returns only 1 depending on which was run first.**

So if python was first it returns 1, if python3 was first it returns 1 - but when it is executed once it will stay in that state.

I guess there's something wrong since also executing first:

```vim
:python print('foo')
```

and then 

```vim
:python3 print('foo')
```

**return**
`E263: Sorry, this command is disabled, the Python library could not be loaded.`

As if toggling between the two interpreters is broken.

Self-compiled vim with :version
`:version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 22 2017 20:30:09)
Included patches: 1-347
Compiled by root@ADRAFINIL
Normal version with GTK2 GUI.  Features included (+) or not (-):
+acl             +clipboard       +dialog_con_gui  +file_in_path    +job             +lua             -mouse_sgr       +path_extra      -rightleft       +tag_old_static  +user_commands   +writebackup
-arabic          +cmdline_compl   +diff            +find_in_path    +jumplist        +menu            -mouse_sysmouse  +perl            +ruby            -tag_any_white   +vertsplit       +X11
+autocmd         +cmdline_hist    +digraphs        +float           -keymap          +mksession       -mouse_urxvt     +persistent_undo +scrollbind      -tcl             +virtualedit     -xfontset
+balloon_eval    +cmdline_info    +dnd             +folding         +lambda          +modify_fname    +mouse_xterm     +postscript      -signs           -termguicolors   +visual          +xim
+browse          +comments        -ebcdic          -footer          -langmap         +mouse           +multi_byte      +printer         +smartindent     +terminfo        +visualextra     +xpm
+builtin_terms   -conceal         -emacs_tags      +fork()          +libcall         +mouseshape      +multi_lang      -profile         +startuptime     +termresponse    +viminfo         -xsmp
+byte_offset     +cryptv          +eval            -gettext         +linebreak       -mouse_dec       -mzscheme        +python/dyn      +statusline      +textobjects     +vreplace        +xterm_clipboard
+channel         +cscope          +ex_extra        -hangul_input    +lispindent      -mouse_gpm       -netbeans_intg   +python3/dyn     -sun_workshop    +timers          +wildignore      -xterm_save
+cindent         +cursorbind      +extra_search    +iconv           +listcmds        -mouse_jsbterm   +num64           +quickfix        +syntax          +title           +wildmenu
+clientserver    +cursorshape     -farsi           +insert_expand   +localmap        -mouse_netterm   +packages        +reltime         +tag_binary      +toolbar         +windows
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2
.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/inclu
de/harfbuzz     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -L/build/buildd/ruby1.9.1-1.9.3.484/debian/lib -rdynamic -Wl,-export-dynamic -Wl,-E   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.
0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfontconfig -lgobject-2.0 -lglib-2.0 -lfreetype   -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -l
selinux   -ldl  -L/usr/lib -llua5.1 -Wl,-E  -fstack-protector -L/usr/local/lib  -L/usr/lib/perl/5.18/CORE -lperl -ldl -lm -lpthread -lcrypt    -lruby-1.9.1 -lpthread -lrt -ldl -lcrypt -lm  -L/usr/lib
`

**Comment by chrisbra** [comment]
I believe that is a consequence how the python libraries are loaded into Vim and to prevent crashes, only one of them can be loaded into the same process. The whole story is explained at `:h python-2-and-3` and can also be read at [vi.stackexchange.com](http://vi.stackexchange.com/q/779/71)
(I don't know the situation for Windows, but guess it is similar).

**Comment by k-takata** [comment]
> (I don't know the situation for Windows, but guess it is similar).

It is different on Windows. Both python 2 and 3 can be loaded into the same process.

**Comment by dezza** [comment]
@chrisbra I read the help-page and will now compile only with python3 I guess - BUT just to finalize this issue:

quoting the `:h python-2-and-3`
```
Here Vim's behavior depends on the system in which it was configured.  In a
system where both versions of Python were configured with --enable-shared,
both versions of Python will be activated at the same time.  There will still
be problems with other third party libraries that were not linked to
libPython.
```

Enable shared is on both Python versions; so from my reading I expect it to work with both `:python` and `:python3` and `has('python')` and `has('python')` ...
```
$ ~ python -c 'import sysconfig; print(sysconfig.get_config_vars())' | grep -o '\-\-enable-shared'
--enable-shared
$ ~ python3 -c 'import sysconfig; print(sysconfig.get_config_vars())' | grep -o '\-\-enable-shared'
--enable-shared
```

**Comment by k-takata** [comment]
> Enable shared is on both Python versions; so from my reading I expect it to work with both :python and :python3 and has('python') and has('python') ...

I don't know the technical detail, but it seems that Python 2/3 on Debian/Ubuntu are actually not `--enable-shared`.
More precisely, the `python` command itself is `--enable-shared`, but python modules are not `--enable-shared`.

If you build Python 2/3 (including all modules) by yourself with `--enable-shared` and build Vim with them, both `:python` and `:python3` would work.

**Comment by k-takata** [comment]
E.g.
If `temios` module is compiled without `--enable-shared`, it doesn't need `libpython*.so.*`:

```
$ objdump -p /usr/lib/python2.7/lib-dynload/termios.x86_64-linux-gnu.so | grep -e NEEDED
  NEEDED               libpthread.so.0
  NEEDED               libc.so.6
  NEEDED               libgcc_s.so.1
```

If it is compiled with `--enable-shared`, the output would be:

```
  NEEDED               libpython2.7.so.1.0
  NEEDED               libpthread.so.0
  NEEDED               libc.so.6
  NEEDED               libgcc_s.so.1
```

It needs `libpython*.so.*`.

**Comment by jamessan** [comment]
> I don't know the technical detail, but it seems that Python 2/3 on Debian/Ubuntu are actually not --enable-shared.
> More precisely, the python command itself is --enable-shared, but python modules are not --enable-shared.

[According] to Debian/Ubuntu's Python maintainer:

> The python extensions are not linked against libpython to avoid                                                                                                                                  dependencies on more than one Python version when we have more than one                                                                                                                               Python3.x version in the archive. 

[According]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=729924#50

**Comment by rgdgr8** [comment]
how to turn off --enable-shared for python and keep it on only for python3?

**Comment by chrisbra** [comment]
if i remember correctly, `--enabled-shared` was a flag for when compiling python.  Meaning you would need to compile your own python.
