### ISSUE TITLE
fuzzycollect "hanging" scanning tags

### ISSUE THREAD

**Issue by habamax** [vim/vim#15052]
### Steps to reproduce

1. `vim -Nu NONE`
2. `set completeopt=menuone,popup,fuzzy,fuzzycollect,noselect completepopup=highlight:Pmenu`
3. add 2 words, e.g. `hello world`
4. in the new line goto insert mode and press `Ctrl-n`

### Expected behaviour

Words `hello` and `world` should be suggested for completion.

I can see "Scanning tags." and vim is not responing unless `Ctrl-c` is pressed.

[![asciicast](https://asciinema.org/a/mUcEfRfagz1m0a7q1Hk0oxr8q.svg)](https://asciinema.org/a/mUcEfRfagz1m0a7q1Hk0oxr8q)

### Version of Vim

9.1.505

### Environment

debian12, bash

**Comment by habamax** [comment]
@glepnir fyi

**Comment by glepnir** [comment]
can be close because fuzzycollect is removed
