### ISSUE TITLE
:Termdebug returns "E117: Unknown function: StartDebug"

### ISSUE THREAD

**Issue by physixcat** [vim/vim#15058]
### Steps to reproduce

1. Have the line `packadd termdebug` in ~/.vimrc and make sure it's sourced
2. Enter command `:Termdebug`
3. Returns error `E117: Unknown function: StartDebug`

### Expected behaviour

Expected Termdebug to open after entering its command

Since my Debian Sid version seems to be based on the release from 3 days ago, I compiled the latest version from git. The problem persisted

Another interesting to note: 
`[termdebug] Termdebug already loaded.` appears on startup, even if `packadd termdebug` is only in .vimrc once. If removed, then Termdebug isn't loaded. The message would seem to imply that you don't need to packadd because it's already included by default.

### Version of Vim

9.1.0505 (self-compile) and 2:9.1.0496-1 (Debian Sid release)

### Environment

OS: Debian Sid
Terminal: st
$TERM: tmux-256color
Shell: bash 5.2.21-2.1

**Comment by chrisbra** [comment]
Hm, I cannot seem to reproduce this. A few things to try, try running `vim --clean -c 'packadd termdebug'` and then see if it still fails. Check the output of `:scriptnames` which plugin it is loading. Make sure you are using the latest master version please.

**Comment by physixcat** [comment]
Thank you for the tip. `vim --clean -c 'packadd termdebug'` does make :Termdebug succeed again on latest master version.
Here is the output of :scriptnames when ran like this
```
:scriptnames
  1: ~/vim_latest/share/vim/vim91/defaults.vim
  2: ~/vim_latest/share/vim/vim91/filetype.vim
  3: ~/vim_latest/share/vim/vim91/ftplugin.vim
  4: ~/vim_latest/share/vim/vim91/indent.vim
  5: ~/vim_latest/share/vim/vim91/syntax/syntax.vim
  6: ~/vim_latest/share/vim/vim91/syntax/synload.vim
  7: ~/vim_latest/share/vim/vim91/syntax/syncolor.vim
  8: ~/vim_latest/share/vim/vim91/colors/lists/default.vim
  9: ~/vim_latest/share/vim/vim91/pack/dist/opt/termdebug/plugin/termdebug.vim
```
Here is the output of :scriptnames when I run it normally (_without_ clean). I made sure to disable Vundle and my plugins. but it still exhibits the problem I described
```
:scriptnames
  1: ~/.vimrc
  2: ~/vim_latest/share/vim/vim91/ftoff.vim
  3: ~/vim_latest/share/vim/vim91/pack/dist/opt/termdebug/plugin/termdebug.vim
  4: ~/vim_latest/share/vim/vim91/autoload/netrw_gitignore.vim
  5: ~/vim_latest/share/vim/vim91/filetype.vim
  6: ~/vim_latest/share/vim/vim91/ftplugin.vim
  7: ~/vim_latest/share/vim/vim91/indent.vim
  8: ~/vim_latest/share/vim/vim91/colors/lists/default.vim
  9: ~/vim_latest/share/vim/vim91/syntax/syntax.vim
 10: ~/vim_latest/share/vim/vim91/syntax/synload.vim
 11: ~/vim_latest/share/vim/vim91/syntax/syncolor.vim
 12: ~/vim_latest/share/vim/vim91/plugin/getscriptPlugin.vim
 13: ~/vim_latest/share/vim/vim91/plugin/gzip.vim
 14: ~/vim_latest/share/vim/vim91/plugin/logiPat.vim
 15: ~/vim_latest/share/vim/vim91/plugin/manpager.vim
 16: ~/vim_latest/share/vim/vim91/plugin/matchparen.vim
 17: ~/vim_latest/share/vim/vim91/plugin/netrwPlugin.vim
 18: ~/vim_latest/share/vim/vim91/plugin/rrhelper.vim
 19: ~/vim_latest/share/vim/vim91/plugin/spellfile.vim
 20: ~/vim_latest/share/vim/vim91/plugin/tarPlugin.vim
 21: ~/vim_latest/share/vim/vim91/plugin/tohtml.vim
 22: ~/vim_latest/share/vim/vim91/plugin/vimballPlugin.vim
 23: ~/vim_latest/share/vim/vim91/plugin/zipPlugin.vim
 24: ~/vim_latest/share/vim/vim91/scripts.vim
 25: ~/vim_latest/share/vim/vim91/autoload/dist/script.vim
 26: ~/vim_latest/share/vim/vim91/ftplugin/vim.vim
 27: ~/vim_latest/share/vim/vim91/indent/vim.vim
 28 A: ~/vim_latest/share/vim/vim91/autoload/dist/vimindent.vim
 29: ~/vim_latest/share/vim/vim91/syntax/vim.vim
```
What other info could I provide to help track down the problem?

**Comment by physixcat** [comment]
Ah! Interesting. If I remove `packadd termdebug` from my ~/.vimrc , and then simply do
`./vim -c 'packadd termdebug'`
The problem vanishes.

So the issue has to do with Termdebug somehow being sensitive to load order. It seems to want to load last?

**Comment by d-k-c** [comment]
Facing same issues with vim 9.1.500 on MacOS, installed via Homebrew

**Comment by physixcat** [comment]
I can confirm `packadd! termdebug` in my ~/.vimrc solves the problem. It puts termdebug right at the end of the queue, except for an autoload from a plugin (peekaboo.vim)
