### ISSUE TITLE
fuzzycollect internal error lalloc

### ISSUE THREAD

**Issue by habamax** [vim/vim#15051]
### Steps to reproduce

1. `vim -Nu NONE`
2. `set completeopt=menuone,popup,fuzzy,fuzzycollect,noselect completepopup=highlight:Pmenu`
3. `hi PmenuMatch guifg=#ffaf5f guibg=#3a3a3a gui=NONE cterm=NONE`
4. `hi PmenuMatchSel guifg=#af5f00 guibg=#afaf87 gui=NONE cterm=NONE`
5. `:h fuzzy`
6. switch to previous window
7. type `omp` and `c-p` `c-p`

### Expected behaviour

There should be no errors.

![image](https://github.com/vim/vim/assets/234774/2a8eaff9-0214-4191-bf4c-033e5f3a2875)

[![asciicast](https://asciinema.org/a/ODnO5rMO0Z4bkIiDRSq6EnFUv.svg)](https://asciinema.org/a/ODnO5rMO0Z4bkIiDRSq6EnFUv)

### Version of Vim

9.1.505

### Environment

debian 12, bash

**Comment by habamax** [comment]
@glepnir fyi

**Comment by glepnir** [comment]
can be close because fuzzycollect is removed
