### ISSUE TITLE
cursormovedc didnot work when c-w or c-u

### ISSUE THREAD

**Issue by Shane-XB-Qian** [vim/vim#15069]
### Steps to reproduce

1. vim -clean
2. setup cursormovedc au
3. :foo bar wee 
4. c-w

### Expected behaviour

work

### Version of Vim

v9.1.512

### Environment

linux

**Comment by Shane-XB-Qian** [comment]
@Shougo @zeertzjq was it intended to design like that?

**Comment by Shane-XB-Qian** [comment]
c-w maybe should work, but c-u not sure.........

**Comment by zeertzjq** [comment]
It already triggers CmdlineChanged, and when the cmdline text changes the definition of "cursor movement" is not clear.

**Comment by Shane-XB-Qian** [comment]
um... but after c-w, the cursor was moved also...
anyway, so it is intended?

**Comment by zeertzjq** [comment]
I don't know, @Shougo ?

**Comment by Shane-XB-Qian** [comment]
if yes, then the event name maybe should be `CmdLineCursorMoved` :sweat_smile:

**Comment by Shane-XB-Qian** [comment]
if yes, then the event name maybe should be called `CmdLineCursorMoved` :sweat_smile:

-- 
shane.xb.qian

**Comment by Shane-XB-Qian** [comment]
um... let it be, maybe i mis-understood the name meaning.

**Comment by Shane-XB-Qian** [comment]
um... let it be, maybe i mis-understood the name meaning.

**Comment by Shane-XB-Qian** [comment]
when i read #15040 it was not such description about 'text changed' in cursormovedc event help, but #15064 added it.
so if you thought it was a bug or something, then maybe should rephrase the description of that event help also.

**Comment by Shougo** [comment]
> @Shougo @zeertzjq was it intended to design like that?

> It already triggers CmdlineChanged, and when the cmdline text changes the definition of "cursor movement" is not clear.

Yes.  So I intended `CursorMovedC` does not fire when `CmdlineChanged`.

**Comment by Shougo** [comment]
> if yes, then the event name maybe should be called `CmdLineCursorMoved`

The event was named `CmdlineMoved`.
It is renamed to `CursorMovedC` to adjust other event naming.
I don't think the rename resolve the confusion.

**Comment by chrisbra** [comment]
It seems a bit too specific, if it only fires when the command line did not change. I would think it should always fire and you would need to figure out in your plugin if the command line changed or not. 

> The event was named CmdlineMoved.
> It is renamed to CursorMovedC to adjust other event naming.

Correct, because the Command-line is not moved, but the cursor moved in the command-line

**Comment by Shane-XB-Qian** [comment]
> > if yes, then the event name maybe should be called `CmdLineCursorMoved`
> 
> The event was named `CmdlineMoved`. It is renamed to `CursorMovedC` to adjust other event naming. I don't think the rename resolve the confusion.

_if_ it was `cmdlineCursorMoved`, i may think it was just the cursor moved,
_but_ if it is cursormovedc, then compared to cursormovedi, it should be kick-ed when text-changed.

**Comment by Shane-XB-Qian** [comment]
> > if yes, then the event name maybe should be called `CmdLineCursorMoved`
> 
> The event was named `CmdlineMoved`.
> It is renamed to `CursorMovedC` to adjust other event naming.
> I don't think the rename resolve the confusion.

if it was `cmdlineCursorMoved`, i may think it was just the cursor moved,
but if it is cursormovedc, then compared to cursormovedi, it should be kick-ed when text-changed too.

-- 
shane.xb.qian

**Comment by chrisbra** [comment]
I'd really prefer, if we trigger this on all cursor moved events, so it's a generic CursorMoved event. Would that cause any issues for your plugin @Shougo ?

**Comment by Shougo** [comment]
No problem.
