### ISSUE TITLE
:Termdebug returns E1012: Type mismatch (expected string got list<string>) if g:termdebugger set

### ISSUE THREAD

**Issue by accellarando** [vim/vim#15061]
### Steps to reproduce

1. `let g:termdebugger=["debug", "-ex", "options"]` - for example, my vimrc has `let g:termdebugger=["arm-none-eabi-gdb",  "-ex", "target remote :2331"]`
2. `packadd! termdebug`
3. `:Termdebug`
4. For me, this reports 
```
Error detected while processing function <SNR>29_StartDebug[3]..<SNR>29_StartDebug_internal[5]..<SNR>29_GetCommand:
line    6:
E1012: Type mismatch; expected string but got list<string>
```

### Expected behaviour

Termdebug should open with the specified debugger and the passed command-line options for the debugger. 

### Version of Vim

9.1.1-496

### Environment

:version:

```
:version                                                                                                                                                                                        
VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Jun 17 2024 22:29:09)
Included patches: 1-496
Compiled by Arch Linux
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               +clientserver      +diff              +folding           +langmap           +mouse_dec         +num64             +reltime           +syntax            +title             +wildmenu
+arabic            +clipboard         +digraphs          -footer            +libcall           +mouse_gpm         +packages          +rightleft         +tag_binary        +toolbar           +windows
+autocmd           +cmdline_compl     +dnd               +fork()            +linebreak         -mouse_jsbterm     +path_extra        +ruby/dyn          -tag_old_static    +user_commands     +writebackup
+autochdir         +cmdline_hist      -ebcdic            +gettext           +lispindent        +mouse_netterm     +perl/dyn          +scrollbind        -tag_any_white     +vartabs           +X11
-autoservername    +cmdline_info      +emacs_tags        -hangul_input      +listcmds          +mouse_sgr         +persistent_undo   +signs             +tcl/dyn           +vertsplit         +xattr
+balloon_eval      +comments          +eval              +iconv             +localmap          -mouse_sysmouse    +popupwin          +smartindent       +termguicolors     +vim9script        -xfontset
+balloon_eval_term +conceal           +ex_extra          +insert_expand     +lua/dyn           +mouse_urxvt       +postscript        -sodium            +terminal          +viminfo           +xim
+browse            +cryptv            +extra_search      +ipv6              +menu              +mouse_xterm       +printer           +sound             +terminfo          +virtualedit       -xpm
++builtin_terms    +cscope            -farsi             +job               +mksession         +multi_byte        +profile           +spell             +termresponse      +visual            +xsmp_interact
+byte_offset       +cursorbind        +file_in_path      +jumplist          +modify_fname      +multi_lang        -python            +startuptime       +textobjects       +visualextra       +xterm_clipboard
+channel           +cursorshape       +find_in_path      +keymap            +mouse             -mzscheme          +python3/dyn       +statusline        +textprop          +vreplace          -xterm_save
+cindent           +dialog_con_gui    +float             +lambda            +mouseshape        +netbeans_intg     +quickfix          -sun_workshop      +timers            +wildignore
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
 3rd user vimrc file: "~/.config/vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
3rd user gvimrc file: "~/.config/vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/atk-1.0 -I/usr/include/freetype2
-I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/libpng16 -I/usr/include/pixman-1 -I/usr/include/cloudproviders -I/usr/incl
ude/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/fribidi -I/usr/include/sysprof-6 -pthread -I/usr/include/gio-unix-2.0 -march=x86-64 -mtune=generi
c -O2 -pipe -fno-plt -fexceptions -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -g -ffile-prefix-map=/build/vim/src=/usr/src/debu
g/vim -flto=auto -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.38/core_perl/CORE -Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-z,pack-relative-relocs -flto=auto -L/usr/local/lib -o vim -lgtk-3 -lgdk-3
 -lz -lharfbuzz -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo -lcairo-gobject -lgdk_pixbuf-2.0 -lgio-2.0 -lglib-2.0 -lgobject-2.0 -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE -lm -ltinfo -lcanberra -lacl -lattr -l
gpm -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm
```

$TERM: `xterm-256color`

/etc/os-release: 
```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```

**Comment by accellarando** [comment]
Just wrote a quick fix for myself, I have not tested what happens if g:termdebug_config is set though.

```
# Get the command to execute the debugger as a list, defaults to ["gdb"].
def GetCommand(): list<string>
  var cmd = ['gdb']
  if exists('g:termdebug_config')
    cmd = get(g:termdebug_config, 'command', ['gdb'])
  elseif exists('g:termdebugger')
    cmd = g:termdebugger
  endif

  return type(cmd) == v:t_list ? copy(cmd) : [cmd]
enddef
```

**Comment by chrisbra** [comment]
Hm, I think this patch should do it, no?

```patch
diff --git a/runtime/pack/dist/opt/termdebug/plugin/termdebug.vim b/runtime/pack/dist/opt/termdebug/plugin/termdebug.vim
index d00cdded2..8f2e331ef 100644
--- a/runtime/pack/dist/opt/termdebug/plugin/termdebug.vim
+++ b/runtime/pack/dist/opt/termdebug/plugin/termdebug.vim
@@ -248,11 +248,13 @@ enddef

 # Get the command to execute the debugger as a list, defaults to ["gdb"].
 def GetCommand(): list<string>
-  var cmd = 'gdb'
+  var cmd: any
   if exists('g:termdebug_config')
     cmd = get(g:termdebug_config, 'command', 'gdb')
   elseif exists('g:termdebugger')
     cmd = g:termdebugger
+  else
+    cmd = 'gdb'
   endif

   return type(cmd) == v:t_list ? copy(cmd) : [cmd]
```

@ubaldot please :)

**Comment by errael** [comment]
Only loosely related. I wonder if it's work copying **all** plain config globals, like
```vim
if exists('g:termdebugger')
    g:termdebug_config.command = g:termdebugger
endif
```
during startup, and then only use `g:termdebug_config` in the mainline code.

**Comment by ubaldot** [comment]
> Hm, I think this patch should do it, no?
> 
> ```diff
> diff --git a/runtime/pack/dist/opt/termdebug/plugin/termdebug.vim b/runtime/pack/dist/opt/termdebug/plugin/termdebug.vim
> index d00cdded2..8f2e331ef 100644
> --- a/runtime/pack/dist/opt/termdebug/plugin/termdebug.vim
> +++ b/runtime/pack/dist/opt/termdebug/plugin/termdebug.vim
> @@ -248,11 +248,13 @@ enddef
> 
>  # Get the command to execute the debugger as a list, defaults to ["gdb"].
>  def GetCommand(): list<string>
> -  var cmd = 'gdb'
> +  var cmd: any
>    if exists('g:termdebug_config')
>      cmd = get(g:termdebug_config, 'command', 'gdb')
>    elseif exists('g:termdebugger')
>      cmd = g:termdebugger
> +  else
> +    cmd = 'gdb'
>    endif
> 
>    return type(cmd) == v:t_list ? copy(cmd) : [cmd]
> ```
> 
> @ubaldot please :)

Thanks, I am going to add it in https://github.com/vim/vim/pull/15057#pullrequestreview-2131078111

**Comment by ubaldot** [comment]
> Only loosely related. I wonder if it's work copying **all** plain config globals, like
> 
> ```viml
> if exists('g:termdebugger')
>     g:termdebug_config.command = g:termdebugger
> endif
> ```
> 
> during startup, and then only use `g:termdebug_config` in the mainline code.

This is indeed very elegant, I personally like it. :) 

TBH 100% honest, I would add a deprecation warning saying that configuring variables of the form `g:termdebugger` will be ditched at some point in the future, inviting the user to read the `:h termdebug` to get guidance on how to update their configurations. That would clean up the code. But I don't know if this is inline with Vim vision. :)

**Comment by errael** [comment]
> TBH 100% honest, I would add a deprecation warning saying that configuring variables of the form `g:termdebugger` will be ditched at some point in the future, inviting the user to read the `:h termdebug` to get guidance on how to update their configurations. That would clean up the code. But I don't know if this is inline with Vim vision. :)

I'm in enough trouble without commenting on this. ;)

**Comment by chrisbra** [comment]
>  But I don't know if this is inline with Vim vision. :)

We don't usually do this. But we can try it out in a plugin and see how people react 🙈. It's not something I'd recommend for core Vim, but for a plugin it should be fine. We should still support the deprecated version for half a year at least.

**Comment by ubaldot** [comment]
> > But I don't know if this is inline with Vim vision. :)
> 
> We don't usually do this. But we can try it out in a plugin and see how people react 🙈. It's not something I'd recommend for core Vim, but for a plugin it should be fine. We should still support the deprecated version for half a year at least.

I was actually thinking exactly the same thing: for the core I am pretty sure it is a no-no, but perhaps for a plugin it may be allowed. I was also thinking exactly the same: 6-12 months as time window for keeping the deprecation warning before deprecating it. 

We may try with termdebug for like six months and see how many people will complain. We won't remove anything, just display a warning message. The sanity-check function looks like a good place to add such a warning. I may work on it during next week. 

Loosely related: it would be great if we manage to separate the "frontend" and the "backend" of termdebug but it may be hard and time consuming. At the moment as "backend" we only have gdb, but it would be nice to be able to use also other debuggers (lldb, debugpy, etc.) or implement DAP. Well, food for thoughts...
