### ISSUE TITLE
The `ps` output is truncated in the terminal

### ISSUE THREAD

**Issue by yu3s** [vim/vim#15092]
### Steps to reproduce

1. `vim --clean -c "0tab term"`
2. `ps aux |grep dbus |head -n 1`

---
- vim
![image](https://github.com/vim/vim/assets/86161857/d6462fa8-7b3b-4b19-a48c-ed12393a2d14)

- neovim 0.9.5
![image](https://github.com/vim/vim/assets/86161857/5cd7d01a-a0b9-4966-91e0-f5e26866068f)

### Expected behaviour

Same behavior as neovim

### Version of Vim

9.1.516

### Environment

os: ubuntu18.04
terminal: windows terminal
$TERM: xterm-256color
shell: bash4.4.20

**Comment by ghgary** [comment]
This looks like a bug in neovim.  Run your command in a terminal such as xterm or in vim as ":r!ps aux |grep dbus |head -n 1" and you'll see that the output is truncated to the width of the screen. That's the way ps works.

**Comment by zeertzjq** [comment]
It seems that this depends on the `COLUMNS` environment variable. If you unset it by using `COLUMNS= ps aux | grep dbus`, it won't be truncated.

**Comment by zeertzjq** [comment]
Vim sets `LINES` and `COLUMNS` environment variables for child processes:
```c
    sprintf((char *)envbuf, "%ld", rows);
    setenv("LINES", (char *)envbuf, 1);
    sprintf((char *)envbuf, "%ld", columns);
    setenv("COLUMNS", (char *)envbuf, 1);
```
This behavior seems to date back to Vim 5.0.

However, in terminal emulators (e.g. XTerm), these two are not set as environment variables (which appear in the output of `env` command), but by the shell as shell variables (which do not appear in the output of `env` command).
- In XTerm: `env | grep LINES=` or `env | grep COLUMNS=` don't return anything.
- In Vim terminal: `env | grep LINES=` and `env | grep COLUMNS=` returns the height and width of the terminal.

**Comment by yu3s** [comment]
> Vim sets `LINES` and `COLUMNS` environment variables for child processes:
> 
> ```c
>     sprintf((char *)envbuf, "%ld", rows);
>     setenv("LINES", (char *)envbuf, 1);
>     sprintf((char *)envbuf, "%ld", columns);
>     setenv("COLUMNS", (char *)envbuf, 1);
> ```
> 
> This is not limited to terminal processes. This behavior seems to date back to Vim 5.0.
> 
> However, in terminal emulators (e.g. XTerm), these two are not set as environment variables (which appear in the output of `env` command), but by the shell as shell variables (which do not appear in the output of `env` command).
> 
> * In XTerm: `env | grep LINES=` or `env | grep COLUMNS=` don't return anything.
> * In Vim terminal: `env | grep LINES=` and `env | grep COLUMNS=` return the height and width of the terminal.

Thanks
![Screenshot from 2024-06-25 00-26-42](https://github.com/vim/vim/assets/86161857/80a359df-eec8-4b16-9a38-016fea16513c)
![Screenshot from 2024-06-25 00-25-21](https://github.com/vim/vim/assets/86161857/89d01eff-81ad-42b0-8b30-119bcdccb7dd)
