### ISSUE TITLE
xxd.exe is detected by an awful lot of virus scanners

### ISSUE THREAD

**Issue by HenkPoley** [vim/vim#15093]
### Steps to reproduce

Maybe a false positive, but:

1. Run Windows
2. Download installer from: https://github.com/vim/vim-win32-installer/releases/download/v9.1.0512/gvim_9.1.0512_x64.exe
3. `C:\Program Files\Vim\vim91\xxd.exe` is probably detected by your virusscanner (e.g. Windows Defender does).

See on VirusTotal: 

* xxd.exe (17/74) https://www.virustotal.com/gui/file/b6660cf54ac304336411b9a6ee9f2eaf7f6c5fe124efab42a3cc0e62d20b7b13/community
 * Intezer scan of xxd.exe doesn't see anything in particular: https://analyze.intezer.com/analyses/dbee94ef-d430-4081-93c5-460da2e4bf96/genetic-analysis
* Vim installer (3/73): https://www.virustotal.com/gui/file/e76d8747e5cb7f651b9157d0ca2ecb0104b9e13ee191c9b357347c94bda77d7f/community
* GitHub download (0/95): https://www.virustotal.com/gui/url/69b17b49fc38dae354935273140f99d6c4ae0efe15b5094bb687c759b652042f

### Expected behaviour

No virus detection.

### Version of Vim

Windows gvim 9.1.0512

### Environment

Windows 11 23H2

**Comment by HenkPoley** [comment]
Should I (re)post this at vim/vim-win32-installer? E.g. https://github.com/vim/vim-win32-installer/issues

**Comment by k-takata** [comment]
Please see this FAQ: https://github.com/vim/vim-win32-installer/wiki
There is not much we can do about it. If you don't mind helping us, please inform it to each anti-virus vendor.

**Comment by HenkPoley** [comment]
Yeah, but it's not really detecting the Nullsoft installer (very much, only by some obscure scanners).

I'll try contacting Microsoft, Bitdefender and TrendMicro. I think the most legitimate from the bunch.

**Comment by HenkPoley** [comment]
Just for reference, increase in detections on VirusTotal seems to have started with gvim 9.1.0466 from 5 June 2024.

**Comment by HenkPoley** [comment]
I've submitted a false positive review to Bitdefender and Microsoft.

Locally Bitdefender no longer detects and removes xxd.exe 9.1.0514

On VirusTotal those both still detect xxd.exe 🤷‍♂️. I suppose most of the other scanners just "went along with the big guys".
