### ISSUE TITLE
Fuzzy completion does not allow cycle back to original, wrong highlight, and Ctrl-P Ctrl-N issues

### ISSUE THREAD

**Issue by nv-quan** [vim/vim#15095]
### Steps to reproduce

1. `vim -Nu NONE`
2. `:set completeopt+=fuzzy`
3.  type "hello helio hero" in the first line
4. type "he" in the second line, and then press `<C-X><C-P>`
This happens: 
<img width="655" alt="image" src="https://github.com/vim/vim/assets/32443337/b60b74fc-c038-4841-ab71-3ee5d81dcb41">

### There are 3 separate issues:

1. the menu highlight is at "hello" but the completion is "hero"
2. repeatedly pressing `<C-P>` gets stuck at the first selection and does not cycle back
3. repeatedly pressing `<C-N>` does cycle back to the first option but does not cycle back to the original. In other word, this screen never happens:
<img width="651" alt="image" src="https://github.com/vim/vim/assets/32443337/410c9730-00f8-4d3f-86d0-48e253125efc">

### Expected behaviour

1, 2, 3 should work as if `fuzzy` is not set

### Version of Vim

Vim 9.1 patch 1-516

### Environment

MacOS, Iterm2, Tmux

**Comment by chrisbra** [comment]
@glepnir please
