### ISSUE TITLE
file management (copy/move) is broken on windows (netrw)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vim/vim#151]
```
You need to find commands on your system that will copy and move files.  cmd /c 
copy  -and- cmd /c move  worked under windows xp.  Just set 
g:netrw_localcopycmd and g:netrw_localmovecmd to whatever works for you.
```

Original issue reported on code.google.com by `roblovski@gmail.com` on 16 Jul 2013 at 10:09

**Comment by TamaMcGlinn** [comment]
[This google groups forum thread](https://groups.google.com/forum/#!msg/vim_dev/UISg0p2Malw/sMH64ojcBAAJ) has some information on the problem.

**Comment by chrisbra** [comment]
please describe clearly what your problem is. I don't see a problem here.

**Comment by chrisbra** [comment]
I don't think there is anything to be done for this ticket. Closing.
