### ISSUE TITLE
Clarification on expected behavior of <S-CR>

### ISSUE THREAD

**Issue by mikesmithgh** [vim/vim#15107]
### Steps to reproduce

1. Open a file
2. Press `<S-CR>` or enter the command `call feedkeys("\<S-CR>")`

I couldn't find any documentation around the expected behavior of `<S-CR>`. I was using this keymap for a plugin, but it appears this also performs a `<PageDown>` operation.

I was looking at the code and referenced https://github.com/vim/vim/blob/master/src/nv_cmds.h, PageDown also occurs for:
```vim
call feedkeys("\<S-NL>")
call feedkeys("\<S-C-N>")
call feedkeys("\<S-+>")
call feedkeys("\<S-Down>")
```

It looks like this occurs for anything that triggers `nv_down` while holding shift. https://github.com/vim/vim/blob/f0837ba0b9dba9d30e3dc2626d4f690a2d51103e/src/normal.c#L4002

### Expected behaviour

I'm not sure, this issue to understand if this is the correct behavior of `<S-CR>`

### Version of Vim

version 9.1.500 

### Environment

Operation System: MacOS 14.5 (23F79)
Terminal: Kitty 0.35.2 
Shell: Fish 3.7.1

**Comment by chrisbra** [comment]
Yeah, seems this is just not documented. Fixed in 6a4afb1ef
