### ISSUE TITLE
mousemodel=popup not working properly with many items on PopUp menu

### ISSUE THREAD

**Issue by dstein64** [vim/vim#15101]
### Steps to reproduce

Create a script that turns mouse functionality on, sets `mousemodel` to `popup`, and adds many items to the `PopUp` menu.

```vim
" example.vim

set mouse=a
set mousemodel=popup

silent! unmenu PopUp
for i in range(1000)
  execute 'menu PopUp.' .. i .. ' <nop>'
endfor
```

Run Vim and source the script.

```vim
vim -clean
:source example.vim
```

Then right-click somewhere towards the top of the running Vim.

### Expected behaviour

The menu pops up briefly and then goes away. Holding down the right mouse button results in the menu staying open, but the menu doesn't expand down, even though there is more room for the menu in that direction.

I expected for the menu to popup the same way as it would if there were fewer items (staying open), perhaps with a scrollbar (similar to what the insert completion menu has when there are too many items to fit on screen), and/or expanding in the direction with more room (down in the running example).

### Version of Vim

9.1

### Environment

Operating system: Kubuntu 24.04
Terminal: Konsole 23.08.5
$TERM: xterm-256color
Shell: bash 5.2.21(1)

**Comment by zeertzjq** [comment]
This seems to fix the clicking problem:
```diff
diff --git a/src/popupmenu.c b/src/popupmenu.c
index 6e9d82647..3a062e9dc 100644
--- a/src/popupmenu.c
+++ b/src/popupmenu.c
@@ -1633,7 +1633,7 @@ pum_select_mouse_pos(void)
 {
     int idx = mouse_row - pum_row;
 
-    if (idx < 0 || idx >= pum_size)
+    if (idx < 0 || idx >= pum_height)
 	pum_selected = -1;
     else if (*pum_array[idx].pum_text != NUL)
 	pum_selected = idx;
```
