### ISSUE TITLE
Vim freeze suddenly and the usage of cpu is 100% .

### ISSUE THREAD

**Issue by arthur2016** [vim/vim#1511]
today I use vim to write my Python program 
and suddenly the vim freeze and one of the cpu core usage is 100%,
anybody else meet this situation?

**Comment by k-takata** [comment]
What is your Vim version? What is your OS?
What plugins do you use? What is the minimal .vimrc setting?
What is the minimal Python program that cause freezing?

If you report a bug, please provide enough information.
For a user question, please post to [vim_use](https://groups.google.com/forum/?fromgroups=#!forum/vim_use) or somewhere else. This is not a place for it.

**Comment by chrisbra** [comment]
First we need a lot more information, as @k-takata  has already pointed out. Also you need to figure out, if this is not a plugin causing this, see the [faq](https://vimhelp.appspot.com/vim_faq.txt.html#faq-2.5)

**Comment by chrisbra** [comment]
I am closing this, as no more information have been provided.
