### ISSUE TITLE
incsearch option to highlight matches without moving the cursor

### ISSUE THREAD

**Issue by jrmd54** [vim/vim#15115]
Hello,

Is it possible to add an option to the incsearch feature of vim, to highlight matched strings but without moving the cursor?
It would make it easier to build a regex/search pattern matching a pattern visible on screen, without having the screen jump to another position on a typo / bad expression when building the regex (while still benefiting from the highlight feature).

Currently my workflow is the following:
- have 'set noincsearch' by default
- when wanting to build an elaborate regex:
   -   open a new buffer, copy an example line in it
   -   use 'set incsearch'
   -   build regex (this time without the cursor changing position because the buffer contains only 1 line)
   -   close buffer
   -   apply regex on regular file

(which is not very practical)

Thank you very much

**Comment by zzzyxwvut** [comment]
A possible match can be peeked at, with `&incsearch` set, by  
typing `<Esc>` (`<C-[>`, `<C-c>`) _not_ `<Enter>` to finish  a `/` or  
a `?` command.  Once you're happy with the composed regexp and  
do want to move the cursor to a match, type `/` or `?`, followed  
by `<C-p>` to bring up the last pattern, and press `<Enter>`.

**Comment by jrmd54** [comment]
Hello, 

Thank you for your answer.
Hum this does not really fix my use case, mainly because i often work on huge json dumps (>500mo), having the cursor move out of screen really impacts the performance and is the key point of the improvement i wished.

I came up with the following block that i added to my .vimrc:

```
set noincsearch
function! ToggleDisableIncSearchAutoGroup()
    if !exists('#DisableIncSearch#CmdlineLeave')
        augroup DisableIncSearch
            au CmdlineLeave * set noincsearch
        augroup END
    else
        augroup DisableIncSearch
            autocmd!
        augroup END
    endif
endfunction
call ToggleDisableIncSearchAutoGroup()
nmap <leader>I :call ToggleDisableIncSearchAutoGroup()<CR>:set incsearch<CR>:call ToggleDisableIncSearchAutoGroup()<CR>\X
nnoremap <expr> <leader>X ':'.expand(line('w0')).','.expand(line('w$')).'s/'
```

I.e. incsearch is disabled by default, i can do my regular searches without the screen jumping in an out as i type my regex.
And i have \I command to start a substitute command with incsearch enabled only for the duration of the substitute, and only on the visible lines. This way i can build complex regexes while seeing the actual captured strings but without the screen changing position.

**Comment by jrmd54** [comment]
Found a suitable workaround

**Comment by zzzyxwvut** [comment]
Toggling syntax highlighting (`:syn clear`, `:syn enable`) for  
a buffer while you're busy trying a regexp pattern can also  
improve the performance.
