### ISSUE TITLE
Sudo vi/vim read-only files can be edited and forcibly saved! How to disable forced savings.

### ISSUE THREAD

**Issue by wangchao732** [vim/vim#15126]
### Steps to reproduce

sudo vim  /etc/sudoers   
wq!
 

### Expected behaviour

sudo cat /etc/sudoers|grep prometheus
prometheus ALL=(ALL)  NOPASSWD: ALL,!/*/su,!/*/bash,!/usr/sbin/visudo
[prometheus@cdh6-slave3 ~]$ cat /etc/sudoers
cat: /etc/sudoers: 权限不够

sudo vim /etc/sudoers   save: wq!

### Version of Vim

 7.4 

### Environment

CentOS Linux release 7.9.2009 (Core)

**Comment by RestorerZ** [comment]
I don't know how much this will help you, but check out the documentation on [`-R`](https://vimhelp.org/starting.txt.html#-R) and [`-M`](https://vimhelp.org/starting.txt.html#-M), and [`-m`](https://vimhelp.org/starting.txt.html#-m) command line parameters.   
Also, don't forget that whoever has more rights may pay less attention to conventions.

**Comment by zzzyxwvut** [comment]
```shell
sudo head -8 /etc/sudoers
```
> \#
> \# This file MUST be edited with the 'visudo' command as root.
> \#
> \# Please consider adding local content in /etc/sudoers.d/ instead of
> \# directly modifying this file.
> \#
> \# See the man page for details on how to write a sudoers file.
> \#

**Comment by RestorerZ** [comment]
And here, however, is the answer.
At the very top it says that you don't need to edit this file manually, you need to use the visudo utility to edit it.

**Comment by wangchao732** [comment]
> And here, however, is the answer. At the very top it says that you don't need to edit this file manually, you need to use the visudo utility to edit it.

Tks,  I found a new way to solve the problem, thank you for your help and have fun.
