### ISSUE TITLE
"Whole words" mode for fuzzy-searching for more than one word

### ISSUE THREAD

**Issue by lkintact** [vim/vim#15131]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
I wanted to find the beginning of the `at, on and in: time` chapter in an English grammar book I use, but couldn't remember the order in which the prepositions went, so I tried fuzzy-searching with `:lvimgrep /in at on time/f %`. Vim found the line I wanted, but it was lost among several thousands of other, non-relevant lines that were also found.

**Describe the solution you'd like**
It would perhaps be useful to have a flag for whole words fuzzy-searching for cases like that.

**Describe alternatives you've considered**
`/\v(<in>.*)@<=(<at>.*)@<=(<on>.*)@<=time` did the trick, but it worked very, very slowly.

OS: Windows 10 Home
Terminal: GUI
gVim: 9.1.466.

**Comment by lkintact** [comment]
I think I should clarify what I meant by "whole words" mode: if characters are consecutive in the search string, they should be 
consecutive in the result string too.

**Comment by chrisbra** [comment]
> /\v(<in>.*)@<=(<at>.*)@<=(<on>.*)@<=time

Have a look at `:h /\&`. There is also the [logipag plugin](https://github.com/vim/vim/blob/master/runtime/plugin/logiPat.vim), which you can use: `LPE "at" && "in" && "on" && "time"`

**Comment by lkintact** [comment]
Thank you! I guess the issue can be closed.
