### ISSUE TITLE
`g:markdown_md` variable has no effect

### ISSUE THREAD

**Issue by 0x0003** [vim/vim#15141]
### Steps to reproduce

```vim
" min.vim
filetype plugin indent on
let g:markdown_md = 'pandoc'
```

1. `$ vim --clean -u min.vim`
2. `:e file.md`
3. `:set ft?` " returns 'markdown'
4. `:let g:markdown_md` " returns 'pandoc', confirming the variable is set correctly

### Expected behaviour

Filetype of any opened markdown file should be automatically set to "pandoc" according to `:h ft-pandoc-syntax`, among other things.
```vimhelp
PANDOC						*ft-pandoc-syntax*

By default, markdown files will be detected as filetype "markdown".
Alternatively, you may want them to be detected as filetype "pandoc" instead.
To do so, set the following: >

	:let g:markdown_md = 'pandoc'
```

### Version of Vim

9.1.1-496

### Environment

OS: Arch Linux
Terminal: Alacritty 0.13.2
$TERM: xterm-256color
Shell: bash 5.2.26

**Comment by chrisbra** [comment]
I'll rename it soon, thanks for pinging me
