### ISSUE TITLE
<C-b> does not overlap two lines when starting from all the way at the bottom of the buffer

### ISSUE THREAD

**Issue by Asheq** [vim/vim#15146]
### Steps to reproduce

vim
:help
:only
:set nowrap scrolloff=0 number
`G`
`zt`
`<C-b>`

#### Before `<C-b>`
<img width="639" alt="image" src="https://github.com/vim/vim/assets/4657140/49f6452e-cfb1-475c-b807-558388f96177">

#### After `<C-b>`
<img width="639" alt="image" src="https://github.com/vim/vim/assets/4657140/f554d888-94b5-41ff-8bcb-77f4924c0b35">

#### After `<C-b>`

<img width="639" alt="image" src="https://github.com/vim/vim/assets/4657140/b26e6752-c158-4319-8171-106969f3c9ec">

Two lines from before should overlap with the after. In this case line 254 and one "~" line.

### Version of Vim

9.1.516

### Environment

Operating System: macOS 14.5
Terminal: kitty
$TERM: xterm-kitty
Shell: bash

**Comment by luukvbaal** [comment]
> Two lines from before should overlap with the after. In this case line 254 and one "~" line.

Is this "overlap" behavior documented anywhere? Before working on this code I was not aware there even was any "overlap". There is a brief docstring for `get_scroll_overlap()` but the overlap amounts are not motivated either.

In any case, on Vim versions before the recent pagescroll changes (i.e. v9.1.0210), I see the same result (i.e. [no overlap](https://private-user-images.githubusercontent.com/4657140/345647339-f554d888-94b5-41ff-8bcb-77f4924c0b35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNTUyMTgsIm5iZiI6MTcyMDA1NDkxOCwicGF0aCI6Ii80NjU3MTQwLzM0NTY0NzMzOS1mNTU0ZDg4OC05NGI1LTQxZmYtOGJjYi03N2Y0OTI0YzBiMzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDRUMDEwMTU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDdkYzM4NjNmM2M0ODg2ODY1NzFjM2M3NTc3ZmJlZGE0ZDU2MDdiNmNjNThlMWNhOTdiYzM2NDBjYjlhN2M5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Uag2J2NWL-GMaHt4xAgOqWIf2TunUW6uGeZ1v15ETI8)). So what makes the behavior you propose "expected"?

**Comment by Asheq** [comment]
Thanks for looking into this @luukvbaal.

We'll probably want to discuss this proposed change and get some consensus before doing anything, but I currently feel pretty strongly in the logic of the change.

> Is this "overlap" behavior documented anywhere?

Not that I'm aware of

> but the overlap amounts are not motivated either

I don't know when or why 2 was chosen as the overlap amount. Personally, I would have chosen 1 (or even 0). But since 2 was chosen, I would expect it to be 2 everywhere for predictability. It saves a precious half second of cognitive friction every time you scroll if you know exactly where it'll go relative to your current view before you do it.

> I see the same result (i.e. [no overlap](https://private-user-images.githubusercontent.com/4657140/345647339-f554d888-94b5-41ff-8bcb-77f4924c0b35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNTUyMTgsIm5iZiI6MTcyMDA1NDkxOCwicGF0aCI6Ii80NjU3MTQwLzM0NTY0NzMzOS1mNTU0ZDg4OC05NGI1LTQxZmYtOGJjYi03N2Y0OTI0YzBiMzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDRUMDEwMTU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDdkYzM4NjNmM2M0ODg2ODY1NzFjM2M3NTc3ZmJlZGE0ZDU2MDdiNmNjNThlMWNhOTdiYzM2NDBjYjlhN2M5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Uag2J2NWL-GMaHt4xAgOqWIf2TunUW6uGeZ1v15ETI8))

I can't see this link, but I'll take your word for it that this "bug" (or inconsistency rather) existed for a long time.

> So why do yo think the behavior you propose is "expected"

Because if you scroll using `<C-b>` from any other place within the buffer there is a 2-line overlap. I would expect this to be true at the very bottom of the buffer as well.

(Aside: The only exception I am willing to tolerate is when the window is already near the top of the buffer, vim currently chooses not to scroll past the top of the buffer. Technically we could indeed scroll past the top of the buffer and show `~` characters like we do at the bottom. This would make `<C-b>` even more predictable, but I will refrain from actually suggesting this change because I know it would be super contentious)

**Comment by Asheq** [comment]
I also noticed that when you use `<C-f>` from the last page (as far down as possible without showing `~` chars), it doesn't do a 2 line overlap either, but does a 1 line overlap instead.

### Steps to reproduce

vim
:help
:only
:set nowrap scrolloff=0 number
`G`
`<C-f>`

#### Before `<C-f>`
<img width="638" alt="image" src="https://github.com/vim/vim/assets/4657140/0eba4806-f335-4af5-8d76-69980df8ca52">

### After `<C-f>`

<img width="638" alt="image" src="https://github.com/vim/vim/assets/4657140/1fe76315-54f0-4f09-9737-b66544a41ea9">

### Expected behavior

#### After `<C-f>`

<img width="638" alt="image" src="https://github.com/vim/vim/assets/4657140/a34f5b8b-de38-4182-baa8-0c68a079e61d">

**Comment by luukvbaal** [comment]
OK, not a bug then indeed but an enhancement. But like I said, and as can be seen [here](https://github.com/vim/vim/blob/898b3740c7f9fa544c82c9ae6927617aad9a6463/src/move.c#L4), the different overlap amounts are clearly intended, even if undocumented.

As was established before, there are many inconsistencies with and between the various page-scroll keys. The project seems unwilling to change that for the sake of backwards compatibility. In which case I think this may be closed @chrisbra.

**Comment by chrisbra** [comment]
Can anybody please suggest a doc patch then? And has someone checked how e.g. nvi behaves (or what POSIX says)?

**Comment by luukvbaal** [comment]
POSIX vi defines a static overlap of 2, which we use as well in the common case. `get_scroll_overlap()` only produces a different result in the presence of wrapped/folded/filler lines, and at the end of the buffer, which is handled specifically for whatever reason.

I'm not sure I could suggest a meaningful doc patch without knowing the original reasoning behind the current logic.
