### ISSUE TITLE
FocusGained / FocusLost not triggered with Alacritty

### ISSUE THREAD

**Issue by sol** [vim/vim#15157]
### Steps to reproduce

```
$ vim --clean
```
```
:autocmd FocusGained * set number
:autocmd FocusLost * set nonumber
```

### Expected behaviour

Doing this with `xterm`, line numbers are toggled on/off when the corresponding window gains / looses focus.

With Alacritty I would expect the same behavior, however, nothing happens when the corresponding window gains / looses focus.

### Workaround

```vim
if &term =~ "alacritty"
  let &t_fe = "\<Esc>[?1004h"
  let &t_fd = "\<Esc>[?1004l"
endif
```

### Version of Vim

9.1 / patch level 1-496

### Environment

```
$ alacritty --version
alacritty 0.13.2 (bb8ea18e)
```
```
$ echo $TERM
alacritty
```
```
$ bash --version
... 5.2.26 ...
```
```
$ uname -a
Linux x200 6.9.5-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Sun, 16 Jun 2024 19:06:18 +0000 x86_64 GNU/Linux
```

**Comment by jamessan** [comment]
See `:help xterm-focus-event`

**Comment by chrisbra** [comment]
Thanks @jamessan, I just wanted to post this one ;) 
In addition, check your $TERM variable and the `:set t_fe?` setting. Does alacritty actually support this?

**Comment by jamessan** [comment]
Yes, it does. Looks like it's been there since 2017 - https://github.com/alacritty/alacritty/commit/0321f3dcfb576763625a74392332e627ad5ece1b

**Comment by sol** [comment]
Thanks @jamessan @chrisbra, I added the "workaround" to the issue description.

1. Would  it makes sense to reference [`:help xterm-focus-event`](https://vimhelp.org/term.txt.html#xterm-focus-event) from [`:help FocusGained`](https://vimhelp.org/autocmd.txt.html#FocusGained) / [`:help FocusLost`](https://vimhelp.org/autocmd.txt.html#FocusLost)?
2. Should this be re-labeled as a feature request?

**Comment by chrisbra** [comment]
Those focus-tracking events do not seem to be part of Termcap, at least I did not find it. For xterm, we have some hard-coded termcap values included, but not for other terminals. 
I'll add some references to those auto commands in the documentation.
