### ISSUE TITLE
CSV syntax highlighting is off after a substitution

### ISSUE THREAD

**Issue by lkintact** [vim/vim#15161]
### Steps to reproduce

1. Run `gvim.exe --clean customers-100.csv` ([customers-100.csv](https://github.com/user-attachments/files/16116916/customers-100.csv)). gVim opens the file and colors the buffer, as expected.
2. Execute `:%s/,/\t/g`. Syntax highlighting seems to be off.

### Expected behaviour

Syntax highlighting shouldn't be off at step 2.

### Version of Vim

9.1.512

### Environment

OS: Windows 10 Home
Terminal: GUI.

**Comment by chrisbra** [comment]
try to reload it. If you change the delimiter, you can expect problems.

**Comment by lkintact** [comment]
Thank you, I did notice saving and reloading the buffer turns colors back on. That behavior, however, seems to be so peculiar that is looks like a bug.

**Comment by chrisbra** [comment]
Correction, you'll need to unlet the buffer-local variable `b:csv_delimiter` then save and reload the file. 
```vim
:w
:unlet b:csv_delimiter
:e
```

I'll adjust the documentation for this part.

**Comment by lkintact** [comment]
> I'll adjust the documentation for this part.

Perhaps the `:w` and `:e` in lines `1284-1285` of `doc/syntax.txt` should be replaced with their full forms (`:write` and `:edit`, respectively), as throughout the docs full forms of commands are used in examples.
