### ISSUE TITLE
deleted text is stored in PRIMARY even when clipboard=unnamedplus

### ISSUE THREAD

**Issue by tertium** [vim/vim#1516]
I would like to configure vim to only store the yanked/deleted text in CLIPBOARD and never touch PRIMARY, unless maybe via modeless selection. I would expect that "set clipboard=unnamedplus" or "set clipboard=unnamedplus,autoselectml" would provide the desired configuration, since neither "unnamed" nor "autoselect" are included in the option. However, this does not work as vim modifies both registers '*' and '+' when I delete text using d, x, s, c, etc.

A probably related issue is that deletion still modifies both registers when I set clipboard=unnamed,unnamedplus. This contradicts the documentation for "clipboard-unnamedplus" which says the following: «When "unnamed" is also included to the option, yank operations (but not delete, change or put) will additionally copy the text into register '*'.»

This is observed in Vim 8.0.322 as distributed in Debian's vim-gtk (huge version).

**Comment by makmanalp** [comment]
Possibly related? https://github.com/vim/vim/issues/264

**Comment by nuko8** [comment]
Reason?  I'm afraid it has nothing to do with #264.

**Comment by makmanalp** [comment]
@nuko8 My fault!

**Comment by inkarkat** [comment]
I just stumbled across this issue. It's still reproducible in Vim 8.2.2560. It gets triggered when the `a` (_autoselect_) option is removed from `'guioptions'`:

###### good: Both yanks and deletes only affect the clipboard, but not the primary selection.

```
vim -g --clean --cmd 'set clipboard=unnamedplus' -c 'let @*="" | let @+="" | call append(0, [1, 2])'
:1yank
:reg *+
Type Name Content
  c  "*
  l  "+   1^J
:2delete
Type Name Content
  c  "*
  l  "+   2^J
```

###### bad: Yanks still only affect the clipboard, but the primary selection is updated on deletes or changes.

```
vim -g --clean --cmd 'set clipboard=unnamedplus,guioptions-=a' -c 'let @*="" | let @+="" | call append(0, [1, 2])'
:1yank
:reg *+
Type Name Content
  c  "*
  l  "+   1^J
:2delete
Type Name Content
  l  "*   2^J
  l  "+   2^J
```

So, after `:set guioptions-=a`, the documented behavior of `:set clipboard=unnamedplus` is broken. Likewise, with `:set clipboard=unnamed,unnamedplus`, the **following** is violated:

> When "unnamed" is also included to the option, yank operations **(but not delete, change or put)** will additionally copy the text into register '*'.
