### ISSUE TITLE
YAML syntax issue: everything before the last colon in a line seems to be treated as a key

### ISSUE THREAD

**Issue by moronizzz** [vim/vim#15196]
### Steps to reproduce

To open a yaml file with the example content, the `value:` seems to be highlighted:

```yaml
some_key: value:value
some_list:
- value:value
```

![24070901](https://github.com/vim/vim/assets/13842146/3cd78cdd-666c-4b81-9004-47b652635d49)
[](url)

### Expected behaviour

To not highlight values containing colons.

### Version of Vim

9.1

### Environment

OS: Manjaro Linux
Terminal: Konsole 24.05.1
Shell: bash 5.2.26

**Comment by chrisbra** [comment]
Unfortunately, the Yaml syntax file is currently unmaintained and uses hardly to ready black magic regexes, so I cannot guess how to fix this.

**Comment by moronizzz** [comment]
As I understand it was recently updated, not sure if the bug is introduced with this commit: https://github.com/vim/vim/commit/cc7597c1edf478ad912d45b27f17175236f9791e

I just took previous version of the syntax file as a workaround for now. I agree it is pretty hard to understand how it works.

**Comment by chrisbra** [comment]
ah, so it comes from #14354 ping @itchyny perhaps he has an idea

**Comment by itchyny** [comment]
I'll take a look this weekend.

**Comment by moronizzz** [comment]
Just one more note, as I presume we can miss it while fixing this issue. As I understand the keys also can contain colons, so it might be worth to check this case against possible changes in the syntax file as well e.g.

```yaml
aws:cdk:path: some/path
```
