### ISSUE TITLE
line indents change on their own when typing

### ISSUE THREAD

**Issue by kale1d0code** [vim/vim#15203]
### Steps to reproduce

1 Open a file
2 enter insert mode
3 press enter

### Expected behaviour

a single new line character should be printed.
nothing else should happen

### Version of Vim

8.2.2637

### Environment

OS: AlmaLinux 9.4 (Seafoam Ocelot)
Terminal: not sure
$TERM: xterm-256color
Shell bash 5.1.8(1)-release

**Comment by chrisbra** [comment]
Sorry don't understand what the issue is. Can you show a screenshot? Can you reproduce using `vim --clean` and also a much newer Vim please?
