### ISSUE TITLE
[vim9script] `dict` corruption using `items()` return value

### ISSUE THREAD

**Issue by errael** [vim/vim#15208]
### Steps to reproduce

```vim
vim9script

var d: dict<list<number>> = {a: [1], b: [2]}
var item = d->items()[0]
item[1][0] = 'abc'
echo typename(d)
echo d
```
outputs
```
dict<list<number>>
{'a': ['abc'], 'b': [2]}
```
Observe one of the values is a `list<string>`

### Expected behaviour

Should be an exception when executing `item[1][0] = 'abc'`.

### Version of Vim

9.1.554

### Environment

ubuntu/gtk3

**Comment by lirenlin** [comment]
```viml
vim9script

var d: dict<list<number>> = {a: [1], b: [2]}
echo typename(d->items()) # list<list<any>>
var item = d->items()[0]
echo typename(item) # list<any>
echo typename(item[1]) # list<number>
echo typename(item[1][0]) #number
item[1][0] = 'abc'
echo typename(item[1][0]) # string
var tmp = item[1][0]
echo typename(item) # number
tmp = 'abc' # this will give error: E1012: Type mismatch; expected number but got string
```
the return value type of `items()` is `list<list<any>>` or `list<any>`, and documented here.
https://vimhelp.org/builtin.txt.html#items%28%29

it seems variable declaration will also trigger type inference, which figures out the real type behind `any`
this is the case for the `tmp` var in the example. `typename` seems also figures out the type.

it seem for complicated expression with 'any' type, the logic is not trying hard to figure out the type and check it unless explicitly requested (call `typename` on it, or define a variable)

**Comment by lifepillar** [comment]
>it seem for complicated expression with 'any' type, the logic is not trying hard to figure out the type and check it unless explicitly requested (call typename on it, or define a variable)

That seems spot on. When something returns `any` and you want tighter type checking, you need to be more explicit than you'd like. Try to split into simpler expressions:

```vim
vim9script

var d: dict<list<number>> = {a: [1], b: [2]}
var item = d->items()[0]
var i1 = item[1] # list<number>
i1[0] = 3 # OK
i1[0] = 'abc' # E1012, type mismatch
```
If the rhs of the last assignment were not obvious (e.g., the argument of a loosely typed function or the value of a dictionary), a type cast, as @errael [has taught me](https://github.com/vim/vim/issues/12024#issuecomment-1724527052) ;-) would catch a type error. For example:

```vim
vim9script

var d: dict<list<number>> = {a: [1], b: [2]}
var item = d->items()[0]
var s = getchar()
item[1][0] = <number>s
```

The above would result in a type mismatch if `s` is a string (say, if you press an arrow key).

The behaviour that @errael is expecting is desirable. Until then, one needs to be a bit careful.

**Comment by yegappan** [comment]
I have created the PR https://github.com/vim/vim/pull/16274 to address this issue.  Try this out and let me know if you see any type check related issues or some other regression.

**Comment by lirenlin** [comment]
To me, it is less about missing type checking there. But more about the return type of `items()` builtin.
https://vimhelp.org/builtin.txt.html#items%28%29

`any`type indicates, it could hold any concrete type. The value and type can be change later.
At any point of time, there is a concrete type holding inside the any.

When `typename` is applied to `any`, it will tell us the concrete type store there.

the following will give you the type error since the type of `d['a'][0]` is `Number`, not a number in `any`.
```viml
vim9script

var d: dict<list<number>> = {a: [1], b: [2]}
d['a'][0] = "string" #E1012: Type mismatch; expected number but got string
```


On the other hand, there is no error in the following code.

```viml
vim9script

var l = ['a', [1, 2, 3]]
echom typename(l) #list<any>
echom typename(l[0]) #string
echom typename(l[1]) #list<number>
l[1][0] = "string" # no error
echom typename(l[1]) #list<any>
```

There probably are many cases 'any' is returned when more concrete type could be deduced and apply type checking.
https://vimhelp.org/builtin.txt.html#builtin-function-list

While, there are many cases 'any' type is useful and intended to contain any type of data, we can extent it to contain a flag to allow type change or not. When type is not allowed to change, type checking could be applied. This could reduce the backward breakage.

**Comment by lirenlin** [comment]
> I have created the PR #16274 to address this issue. Try this out and let me know if you see any type check related issues or some other regression.

@yegappan I am really new to vim source code, I would like to learn more from your PR.

**Comment by yegappan** [comment]
> To me, it is less about missing type checking there. But more about the return type of `items()` builtin. https://vimhelp.org/builtin.txt.html#items%28%29
> 
> `any` type indicates, it could hold any concrete type. The value and type can be change later. At any point of time, there is a concrete type holding inside the any.
> 
> When `typename` is applied to `any`, it will tell us the concrete type store there.
> 
> the following will give you the type error since the type of `d['a'][0]` is `Number`, not a number in `any`.
> 
> ```viml
> vim9script
> 
> var d: dict<list<number>> = {a: [1], b: [2]}
> d['a'][0] = "string" #E1012: Type mismatch; expected number but got string
> ```
> 
> On the other hand, there is no error in the following code.
> 

With this PR, the following code will produce the "E1012" error as the type check will be properly performed.

> ```viml
> vim9script
> 
> var l = ['a', [1, 2, 3]]
> echom typename(l) #list<any>
> echom typename(l[0]) #string
> echom typename(l[1]) #list<number>
> l[1][0] = "string" # no error
> echom typename(l[1]) #list<any>
> ```
> 
> There probably are many cases 'any' is returned when more concrete type could be deduced and apply type checking. https://vimhelp.org/builtin.txt.html#builtin-function-list
> 
> While, there are many cases 'any' type is useful and intended to contain any type of data, we can extent it to contain a flag to allow type change or not. When type is not allowed to change, type checking could be applied. This could reduce the backward breakage.

If the type of a variable is explicitly declared as "any", then there is no need to perform any type checks.
As discussed earlier in this thread, to take advantage of the type checks, the variable type should be
explicitly declared.
