### ISSUE TITLE
wildmode longest doesn't seem to work

### ISSUE THREAD

**Issue by segevfiner** [vim/vim#15219]
### Steps to reproduce

1. Set:
    ```vim
    set wildmenu
    set wildmode=longest,full
    ```
2. Type a command and press `tab`, e.g. `:bu<Tab>`.
3. It immediately goes to `full` and opens the wildmenui

### Expected behaviour

It should first complete to the longest match, and only go to `full` on the second tab press.

### Version of Vim

9.0.2141 (macOS 14.5 pre-installed)

### Environment

OS: macOS 14.5
Terminal: iTerm2 3.5.3
$TERM: xterm-256color
Shell: Zsh 5.9

### Logs and stack traces

```shell
vimrc:

call plug#begin()

Plug 'tomtom/tcomment_vim'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'

call plug#end()

packadd! matchit

unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

set hlsearch
set ignorecase
set smartcase

set nostartofline
set laststatus=2
set confirm
set number

set autoindent
set shiftwidth=4
set softtabstop=4
set expandtab

set wildmode=longest,full

nnoremap <C-L> :nohl<CR><C-L>
noremap <silent> <C-P> :Files<CR>


```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Apr 13 2024 12:28:29)
macOS version - arm64
Included patches: 1-2136, 2142
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
-arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
-balloon_eval      +fork()            +netbeans_intg     +termresponse
-balloon_eval_term -gettext           +num64             +textobjects
-browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     -perl              +title
+channel           +ipv6              +persistent_undo   -toolbar
+cindent           +job               +popupwin          +user_commands
-clientserver      +jumplist          +postscript        -vartabs
+clipboard         -keymap            +printer           +vertsplit
+cmdline_compl     +lambda            -profile           +vim9script
+cmdline_hist      -langmap           -python            +viminfo
+cmdline_info      +libcall           -python3           +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          -rightleft         +vreplace
+cscope            +localmap          -ruby              +wildignore
+cursorbind        -lua               +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con        +mksession         +smartindent       +writebackup
+diff              +modify_fname      -sodium            -X11
+digraphs          +mouse             -sound             -xattr
-dnd               -mouseshape        +spell             -xfontset
-ebcdic            +mouse_dec         +startuptime       -xim
-emacs_tags        -mouse_gpm         +statusline        -xpm
+eval              -mouse_jsbterm     -sun_workshop      -xsmp
+ex_extra          +mouse_netterm     +syntax            -xterm_clipboard
+extra_search      +mouse_sgr         +tag_binary        -xterm_save
-farsi             -mouse_sysmouse    -tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L/usr/local/lib -o vim        -lm -lncurses  -liconv -framework Cocoa
```
```

**Comment by zeertzjq** [comment]
This is working as intended:
```
	"longest"	Complete till longest common string.  If this doesn't
			result in a longer string, use the next part.
```

**Comment by segevfiner** [comment]
But it doesn't... I expected it to first complete to e.g. `:buf` which is a longer string, and open the menu only on the second press, but it immediately completes to the first full match, not to the longest prefix. @zeertzjq

**Comment by zeertzjq** [comment]
`:buf` is not a common prefix because there is a `:bunload` command.

**Comment by segevfiner** [comment]
I guess I misunderstood how it works when compared to Zsh. Guess I need `longest:list` or `longest:full`. Sorry for the trouble.
