### ISSUE TITLE
javaConceptKind should not link to the NonText highlight group

### ISSUE THREAD

**Issue by dexgs** [vim/vim#15237]
### Steps to reproduce

Introduced by this commit: https://github.com/vim/vim/commit/9ecf02cd5f5feabe096f66cd5f503a822c78793f#diff-0fddd2a7f1b39c711eb9cf31da1cd6e9ca133ed96213fedf4ae46521f1796d37R353

Open a java source file with syntax highlighting on where the `final` keyword is used

### Expected behaviour

From `:help highlight`, the NonText highlight group is for "characters that do not really exist in the text (e.g., ">" displayed when a double-wide character doesn't fit at the end of the line).

Linking javaConceptKind to NonText seems very wrong given this definition, and in practice it also causes problems because NonText is often set to a fainter, less visible colour.

I would expect javaConceptKind to link to Type, or a similar highlight group as that seems far more appropriate.

### Version of Vim

9.1.0407

### Environment

Operating system: Void Linux, Terminal: xterm, Shell: bash

**Comment by zzzyxwvut** [comment]
Let us remember that default highlighting group *names* are  
foremost tailored for the C language.  So `Function` and any  
of `PreProc`, `Include`, etc.; `Typedef` are not meaningful for  
Java.  And there are a handful of Java groups accumulated  
over more than 25 years of API exposure, e.g. `javaTypedef`,  
`javaAnnotation`, `javaExternal`, `javaFuncDef` (which should  
have been named `javaMethodDef`), etc. _and_ linked to C groups.

Now, `NonText` and `EndOfBuffer` are the only _default_ groups of  
blue-colour-on-background for the `--clean` color-scheme, and  
this is the color-scheme I try colour palette for.  Before  
the introduction of `javaConceptKind` there were no items of  
this colour combination.

Here are screenshots of `javaConceptKind` items in Xterm  
(`xterm-256color`) for a Vim instance launched with the  
`--clean` option passed.

Current:
![concepts_b](https://github.com/user-attachments/assets/fe49e257-a100-4437-be8b-da315aab8ea3)

Proposed:
![concepts_a](https://github.com/user-attachments/assets/f7db80cd-45b1-4a73-9ddf-8179f6b0f6f6)

(In [#14403](https://github.com/vim/vim/pull/14403/commits/099831933213e847605b6934ee5b824e520f51fe), the current grouping for `javaConceptKind` was
fleshed out; see its commit message.)

If for an undisclosed color-scheme (`g:colors_name`) `NonText`  
is useless (or possibly you don't care for the distinction  
`javaConceptKind` offers for the modifiers), adjust it as you  
see fit in `~/.vim/after/syntax/java.vim`.

**Comment by dexgs** [comment]
I'm not going to pretend like I know the correct answer with 100% certainty, but personally i vastly prefer the proposed highlighting. I find the blue-on-black does not have enough contrast.

Also, highlighting all those keywords the same (as in the proposed highlighting) is consistent with Java-focused editors such as IntelliJ:
![image](https://github.com/user-attachments/assets/08b0bc4f-d7ed-4273-bd77-be6294e0e933)

**Comment by zzzyxwvut** [comment]
Okay, so you want `abstract`, `final`, etc. to be of the same  
colour with other modifiers by default, right?  And adding  

```vim
hi link javaConceptKind javaStorageClass
```

to `~/.vim/after/syntax/java.vim` doesn't work for you.

**Comment by dexgs** [comment]
I've already applied such a change locally, my reason for opening this issue is that given the description of NonText, linking a highlight group to it which comprises keywords which are part of the explicit text of a file seems incorrect, not just a matter of preference.

Many of the built-in colourschemes assume NonText will only be used for characters like visible EOL characters, etc. and consequently set it to a colour that is quite faint.

I understand that it's fine with the default colourscheme, but this is not true of all the included colourschemes.

Here are some examples:
shine:
![image](https://github.com/user-attachments/assets/99f56a6a-3208-49db-9a76-93311517b7ec)

peachpuff:
![image](https://github.com/user-attachments/assets/88595a86-a65d-40a4-9953-16fbcad04eaa)

sorbet:
![image](https://github.com/user-attachments/assets/a02bcbde-f840-4559-8364-54dc88023643)

elflord:
![image](https://github.com/user-attachments/assets/4c795010-3f52-49d2-bdd4-35a7fa632d5d)

delek:
![image](https://github.com/user-attachments/assets/ab47803e-488d-4ddb-9f4d-48fdf5b13078)

I understand that it's fine for the default colourscheme and many others, but I believe that enough of the colourschemes shipped with vim clearly assume that anything highlighted as NonText will be "characters that do not really exist in the text" to make the case that assigning keywords like `final` should not be assigned to NonText.

I understand that the default highlight groups were not intended for Java specifically. Nevertheless, I think the description of NonText, "characters that do not really exist in the text (e.g., ">" displayed when a double-wide character doesn't fit at the end of the line)" is pretty clear and implies that it's not to be used for any keywords typed explicitly into the file.

**Comment by zzzyxwvut** [comment]
Well, I'm not hung up on the default choice of colour; but I  
can't think of some other recourse to make known that there  
is a highlighting group for (almost) incompatible modifiers  
by way of linking it to a non-`StorageClass` group (with the  
usual default option).  (And it'll be wasteful to introduce  
another API variable to opt-in/out just for that.)

The problem, as always, there are just a handful of default  
groups and even less colours.

Aside: does `native` likewise blend in in IntelliJ?

**Comment by dexgs** [comment]
I'm not committed to any one solution either, I opened this issue as well as my PR because I am pretty confident that NonText is the wrong highlight group to use, but far less confident that just using a StorageClass group is the right answer.

> does `native` likewise blend in in IntelliJ?
I don't have it installed right now to check for sure, but I believe it does and a look at some screenshots suggests the same.

**Comment by zzzyxwvut** [comment]
`NonText` was the best choice for its rather abstract name and  
unique colour among other `:help hl-<Tab>` candidates at the  
time, so there is hardly an alternative to shop for now.

I guess, we can make do with the proposed change with a few
minor touches (see another comment in the PR thread).

**Comment by Shane-XB-Qian** [comment]
> `NonText` was the best choice for its rather abstract name and  
> unique colour among other `:help hl-<Tab>` candidates at the  
> time, so there is hardly an alternative to shop for now.
> 
> I guess, we can make do with the proposed change with a few
> minor touches (see another comment in the PR thread).

rare syntax would 'nontext' as color, i do noticed this was odd in java code.
// in some cases, 'NonText' equals 'no color', in my view, nearly cannot read.

-- 
shane.xb.qian

**Comment by benknoble** [comment]
I'd also like to support making this change: NonText does not seem like the right semantic thing here, and it was shocking to see `final` fade into the background recently.
