### ISSUE TITLE
Segmentation fault on Mac after `set window&`

### ISSUE THREAD

**Issue by hardenedapple** [vim/vim#15233]
### Steps to reproduce

On Mac m1 air.
Using default installed `vim`.
- Open via the symbolic link named `vi`, with no user config.
- `:set window&`
- `:echo system('ls')`
Segmentation fault.

Alternatively, open using the name `vim`, run `:set window&`, then either insert the character `§` into a buffer or resize the window -- both these actions also trigger a segmentation fault.

### Expected behaviour

Does not crash.

### Version of Vim

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Mar  4 2023 14:02:05)    macOS version - arm64 Included patches: 1-1313 Compiled by root@apple.com Normal version without GUI.

### Environment

macOS Ventura 13.3.1 (22E261)
Apple M1
Stock terminal app with `$TERM = xterm-256color`
```
asoneth@Matthews-MacBook-Air ~ % /bin/zsh --version
zsh 5.9 (x86_64-apple-darwin22.0)
```
Default installed vim.

### Logs and stack traces

```shell
N.b. various interesting things:
- crash does not happen when save and restore `&window` around the `set &window`.
- When opening vim I see very large values for `set window?`.  These values are different each time I start vim -- e.g. recent values I've seen are 5765073715964411904 and 6341455303430635520.
```

**Comment by chrisbra** [comment]
please verify using latest master and if you can, please create a [stack trace](https://github.com/vim/vim/wiki/Debugging-Vim-Bugs)

**Comment by hardenedapple** [comment]
It's not latest master -- I should have been clear I couldn't reproduce with anything other than the provided vim on the system.
Am not sure whether that means the bug has gone or some particular build options were necessary.
Can't provide meaningful stack trace on the system vim because the binary is stripped.

**Comment by chrisbra** [comment]
I see. I think it should probably report to Apple then. At the very least they should be made aware of the issue and they should then in the optimal case analyze it (or at least update their Vim). So let me close it then as not actionable for us.
