### ISSUE TITLE
Please update the contact for reporting bugs in netrw's help

### ISSUE THREAD

**Issue by venthur** [vim/vim#15242]
https://github.com/vim/vim/blob/c25a7084e9ae1f78c28ddcbe1fa23374cfdf1e03/runtime/doc/pi_netrw.txt#L3866
https://github.com/vim/vim/blob/c25a7084e9ae1f78c28ddcbe1fa23374cfdf1e03/runtime/doc/pi_netrw.txt#L6

Any maybe other places as well. I contacted Charles recently regarding a bug and he told me that he retired from netrw maintenance and @chrisbra is pretty much the new maintainer.

**Comment by chrisbra** [comment]
The author should be fine of course. But let me add a note for bug reports.
