### ISSUE TITLE
Netrw: CTRL-^ broken when treeview is enabled

### ISSUE THREAD

**Issue by venthur** [vim/vim#15243]
### Steps to reproduce

I've discovered a problem with netrw and CTRL-^ to switch back to the previous buffer: When opening netrw (via :Ex), and opening a file with it, it should be possible to switch back to netrw via CTRL-^. In fact, with the default, clean configuration it works, however, if you 

1. enable the treeview via `let g:netrw_liststyle=3` in the vim config, it does not work anymore. 
2. Whenever you press CTRL-^ to get back to netrw, you'll find an empty "NetrwTreeListing" buffer instead.

### Expected behaviour

Switch back and forth between netrw and the file

### Version of Vim

This bug is reproducible with the latest neovim and vim versions. 

### Environment

Debian

**Comment by chrisbra** [comment]
I think this is essentially the same as #15054 So closing as duplicate.

**Comment by venthur** [comment]
Are you sure? Because this seems to happen only if you use treeview. Wit the default view, CTRL-^ works as expected.
