### ISSUE TITLE
On macOS, scrolling mouse not working as expected after a given column with at least 2 vertical windows

### ISSUE THREAD

**Issue by MathPlayer** [vim/vim#1525]
I'm using the mouse in vim using `set mouse=a`, mainly for scrolling. When opening at least 2 vertical windows and trying to scroll with the mouse in the second buffer after a certain column, the first buffer is scrolled. Counting from the left margin, the column is around 222-223.
This seems related to #47.

Steps to reproduce:
  - open vim with two split files where scrolling is visible
  - `set mouse=a`
  - scroll in the second buffer next to the right margin of the window

Other information which might be useful:

    $ uname -a
    Darwin bpopescu 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64

    $ vim --version
    VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 18 2017 07:44:45)

    $ bash --version
    GNU bash, version 4.4.5(1)-release (x86_64-apple-darwin16.3.0)

The same behaviour can be seen using iTerm2 and Terminal.app applications.

**Comment by k-takata** [comment]
What is the ttymouse setting? (`:set ttymouse?`)
See: `:help sgr-mouse` and `:help urxvt-mouse`

**Comment by MathPlayer** [comment]
Oh, setting the ttymouse to sgr solved my problem. Thank you.

LE:
Interesting enough, I found information regarding this even on the [iTerm2 FAQ](https://www.iterm2.com/faq.html), excerpt from there:

**Q: Mouse reporting in vim doesn't work for some rows/columns in a big terminal window.**
A: Older mouse reporting protocols didn't work in large terminals. Recent versions of vim (at least 7.4) support the "SGR" protocol, which does not have any practical limits on terminal size. To enable it in vim, add this to your .vimrc:

    if has('mouse_sgr')
      set ttymouse=sgr
    endif
