### ISSUE TITLE
TermdebugCommand E1023

### ISSUE THREAD

**Issue by step-** [vim/vim#15254]
In version 9.1.0391 starting the debugger in the following way worked:

    :TermdebugCommand /path/to/program arg args </dev/null

but version 9.1.580 throws and error (then the debugger starts):

Error detected while processing function <SNR>257_StartDebugCommand[2]..<SNR>257_StartDebug_internal[43]..<SNR>257_StartDebug_term[16]..<SNR>257_CreateGdbConsole:
line    74:
E1023: Using a Number as a Bool: 3

**Comment by chrisbra** [comment]
@ubaldot please

**Comment by ubaldot** [comment]
> @ubaldot please

I'll look into it later on today. I'll also add the patch you suggested regarding the whitespaces in filenames.

**Comment by step-** [comment]
@ubaldot, thanks for porting termdebug to vim9 script. I use the old version a lot, and it has its own issues. I'm looking forward to your additions to termdebug.

**Comment by ubaldot** [comment]
It should be fixed with Implemented in https://github.com/vim/vim/pull/15261. Please, double check and confirm so we can close the issue.

**Comment by step-** [comment]
Fix working, confirmed. Thanks @ubaldot
