### ISSUE TITLE
message "[termdebug] Termdebug already loaded."

### ISSUE THREAD

**Issue by step-** [vim/vim#15256]
I think the following paragraph establishes the point that vim 9.1.0580 doesn't automatically load the termdebug plugin, consistently with prior versions and withe help file.

> Start with an empty vimrc file in an otherwise empty ~/.vimrc configuration directory.  The `:Termdebug` command can't be found until you type `:packadd termdebug` in the vim command line.

Now exit vim and append the following line to the otherwise empty ~/.vim/vimrc file:

	packadd termdebug

and run vim. A new error message temporarily holds vim startup:

	[termdebug] Termdebug already loaded.
	Press ENTER or type command to continue

(Side note: perhaps this message is useful but it's certainly annoying).
So why is the plugin already loaded if we established that vim doesn't load it automatically? How can I load the termdebug plugin from vimrc without errors?

**Comment by step-** [comment]
Following the "already loaded" message, if I then execute `:Termdebug` vim shows the following error message:

    E117: Unknown function: StartDebug

and does not start the debugger.

**Comment by ubaldot** [comment]
Thanks for reporting. I will look into that asap.

**Comment by chrisbra** [comment]
as mentioned in a [different issue](15058), you need to use `packadd! termdebug` inside your vimrc file

**Comment by step-** [comment]
Thank you. I can confirm that it works OK with `packadd!`. If this is the final solution, may I suggest to mention the remedy in `help termdebug-starting`.

**Comment by ubaldot** [comment]
> as mentioned in a [different issue](15058), you need to use `packadd! termdebug` inside your vimrc file 

@chrisbra the link does not seem to work. I would be genuinely curious why the ! is needed :)

**Comment by step-** [comment]
@ubaldot does this link work for you? https://github.com/vim/vim/issues/15058

**Comment by chrisbra** [comment]
> @chrisbra the link does not seem to work. I would be genuinely curious why the ! is needed :)

It's documented at `:h packadd` ;)
