### ISSUE TITLE
TSV runtime files are missing

### ISSUE THREAD

**Issue by e-kwsm** [vim/vim#15271]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

CSV and TSV filetypes were introduced by #10680; #15038 implements CSV runtime files but those of TSV are missing.

**Describe the solution you'd like**

runtime/ftplugin/tsv.vim:

```vim
if exists('b:did_ftplugin')
  finish
endif

let b:csv_delimiter = '\t'  " enforce tab delimiter
runtime! ftplugin/csv.vim
```

runtime/syntax/tsv.vim:

```vim
if exists('b:current_syntax')
  finish
endif

let b:csv_delimiter = '\t'  " enforce tab delimiter
runtime! syntax/csv.vim
let b:current_syntax = 'tsv'
```

**Describe alternatives you've considered**

runtime/filetype.vim:

```diff
-au BufNewFile,BufRead *.tsv	setf tsv
+au BufNewFile,BufRead *.tsv	setf csv
```

**Additional context**

**Comment by chrisbra** [comment]
Thanks. I think we only need syntax script. The csv ftplugin does not do anything useful, besides trying to determine the delimiter and the change of the filetype from tsv to csv is not required. So I left those two changes out.
