### ISSUE TITLE
Syntax: Mermaid-JS: Comment settings

### ISSUE THREAD

**Issue by KSR-Yasuda** [vim/vim#15279]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

Could you merge the fix for the mermaid-js syntax below?
https://github.com/craigmac/vim-mermaid/issues/3

[vim-mermaid]: https://github.com/craigmac/vim-mermaid

It had been suggested to the [vim-mermaid][] repo,
but the repo has been frozen before merging it.

**Describe the solution you'd like**

The patch in the issue above is merged.

**Describe alternatives you've considered**

**Additional context**

**Comment by KSR-Yasuda** [comment]
As the original repo has been closed, there is no place to discuss detail.
How should I do?

At least, `comments` and `commentstring` setting of `#` should be fixed since they're clearly mistakes:
[Mermaid comments begin with `%%`.][mermaid_comment]

[mermaid_comment]: https://mermaid.js.org/syntax/flowchart.html#comments

Although [the syntax][mermaid_syntax_comment] is defined for the correct `%%` comments,
`commentstring` has been left wrong anyway.

[mermaid_syntax_comment]: https://github.com/vim/vim/blob/e7a4523b020def00127e9b00e5afd49834792bd0/runtime/syntax/mermaid.vim#L117

**Comment by chrisbra** [comment]
Okay I see. So how about this then:
```diff
diff --git a/runtime/ftplugin/mermaid.vim b/runtime/ftplugin/mermaid.vim
index fe84ab37c..683b3b428 100644
--- a/runtime/ftplugin/mermaid.vim
+++ b/runtime/ftplugin/mermaid.vim
@@ -2,6 +2,7 @@
 " Language:     Mermaid
 " Maintainer:   Craig MacEachern <https://github.com/craigmac/vim-mermaid>
 " Last Change:  2022 Oct 13
+" 2024 Jul 18 by Vim Project (adjust comments)

 if exists("b:did_ftplugin")
   finish
@@ -16,9 +17,8 @@ setlocal shiftwidth=2
 setlocal softtabstop=-1
 setlocal tabstop=4

-" TODO: comments, formatlist stuff, based on what?
-setlocal comments=b:#,fb:-
-setlocal commentstring=#\ %s
+setlocal comments=:%%
+setlocal commentstring=%%\ %s
 setlocal formatoptions+=tcqln formatoptions-=r formatoptions-=o
 setlocal formatlistpat=^\\s*\\d\\+\\.\\s\\+\\\|^\\s*[-*+]\\s\\+\\\|^\\[^\\ze[^\\]]\\+\\]:\\&^.\\{4\\}
```

**Comment by KSR-Yasuda** [comment]
Okay, but could you leave the TODO comment for formatlist?

```diff
@@ -16,9 +17,9 @@ setlocal shiftwidth=2
 setlocal softtabstop=-1
 setlocal tabstop=4

-" TODO: comments, formatlist stuff, based on what?
-setlocal comments=b:#,fb:-
-setlocal commentstring=#\ %s
+setlocal comments=:%%
+setlocal commentstring=%%\ %s
 setlocal formatoptions+=tcqln formatoptions-=r formatoptions-=o
+" TODO: formatlist stuff, based on what?
 setlocal formatlistpat=^\\s*\\d\\+\\.\\s\\+\\\|^\\s*[-*+]\\s\\+\\\|^\\[^\\ze[^\\]]\\+\\]:\\&^.\\{4\\}
```

**Comment by KSR-Yasuda** [comment]
Thank you for merging!

**Comment by ss-raicangu** [comment]
Have just noticed this issue. Extending another thanks for raising here and fixing 🙌 !
