### ISSUE TITLE
Missing separator 

### ISSUE THREAD

**Issue by WillBeFruity** [vim/vim#15275]
https://github.com/vim/vim/blob/22105fd1fe0dcfe993b5c04c6ebe017a626116e3/src/po/Makefile#L320

**Comment by chrisbra** [comment]
sorry, don't get it. What exactly you mean? Or even better, please create a PR

**Comment by ed-barberis** [comment]
Compile error for **RHEL 7-based OS** systems:

```
./configure --with-features=huge --enable-multibyte --enable-rubyinterp --enable-python3interp --enable-perlinterp
.make
Starting make in the src directory.
If there are problems, cd to the src directory and run make there
cd src && make first
make[1]: Entering directory `/usr/local/src/vim/src'
/bin/sh install-sh -c -d objects
...
...
make[2]: Entering directory `/usr/local/src/vim/src/po'
Makefile:317: *** missing separator.  Stop.
make[2]: Leaving directory `/usr/local/src/vim/src/po'
make[1]: *** [languages] Error 2
make[1]: Leaving directory `/usr/local/src/vim/src'
make: *** [first] Error 2
```

Build fails.

**Comment by ed-barberis** [comment]
Since **v9.1.0558**.

**Comment by chrisbra** [comment]
Hm, that line 
```make
POT_PLUGPACKAGE_PATH != pwd
```
doesn't make sense. I suppose this is what was meant:
```patch
diff --git a/src/po/Makefile b/src/po/Makefile
index 0f7f85dd1..a1d942a51 100644
--- a/src/po/Makefile
+++ b/src/po/Makefile
@@ -314,7 +314,7 @@ $(LANGUAGES):
 #######

 # Preparing the POT file of the plug-in package
-POT_PLUGPACKAGE_PATH != pwd
+POT_PLUGPACKAGE_PATH = $(shell pwd)
 $(PLUGPACKAGE).pot: $(PO_PLUG_INPUTLIST)
        $(VIMPROG) -u NONE --not-a-term -S tojavascript.vim \
                $(PLUGPACKAGE).pot $?
@@ -327,7 +327,7 @@ $(PLUGPACKAGE).pot: $(PO_PLUG_INPUTLIST)
        rm -f *.js ./vim_to_js

 # Converting the PO file of the plug-in package to the binary format of the MO
-MO_PLUGPACKAGE_PATH != pwd
+POT_PLUGPACKAGE_PATH = $(shell pwd)
 $(PLUGPACKAGE).mo: $(PO_PLUGPACKAGE)
        $(MSGFMTCMD) -o $(MO_PLUGPACKAGE_PATH)/$@ $<
```

@RestorerZ what do you think? @ed-barberis does this patch fix it?

**Comment by RestorerZ** [comment]
@chrisbra , I'm watching this right now.
I'm afraid your option doesn't quite fit.
`POT_PLUGPACKAGE_PATH = $(shell pwd)`
This will not work on FreeBSD.  

I just don't understand what's wrong with this record `POT_PLUGPACKAGE_PATH != pwd`.

According to the documentation, the result of the command should be assigned to a variable.
This is from GNU Make:
> The shell assignment operator ‘!=’ can be used to execute a shell script and set a variable to its output. This operator first evaluates the right-hand side, then passes that result to the shell for execution. If the result of the execution ends in a newline, that one newline is removed; all other newlines are replaced by spaces. The resulting string is then placed into the named recursively-expanded variable. 

This is from FreeBSD:
>  !=      Expand the value	and pass it to the shell for execution and as-
	       sign  the  result  to the variable.  Any	newlines in the	result
	       are replaced with spaces.

I'm not very good at UNIX-like commands.

**Comment by chrisbra** [comment]
ah, it's a shell assignment, I did not find the `!=` assignment operator when looking this up :/ Then this should be fine I guess. May be we can move it directly into the rule below?

**Comment by RestorerZ** [comment]
Actually, this record can be thrown away altogether. Or is it better to simplify it to such an entry:
`POT_PLUGPACKAGE_PATH = ./`
As I understand it, this is to assign the current directory to a variable. And we are currently in "src/po", which is exactly what was required.

**Comment by k-takata** [comment]
How about using `$(PWD)`? Or, simply `.`?

**Comment by ed-barberis** [comment]
Replacing ```!= pwd``` with ```= ${PWD}``` on lines **317** and **330** in ```./vim/src/po/Makefile``` worked for me. (So far, I've only tested on Amazon Linux 2.)
