### ISSUE TITLE
segfault accessing list item coming from getregionpos in TextYankPost

### ISSUE THREAD

**Issue by habamax** [vim/vim#15272]
### Steps to reproduce

1. `vim -Nu NONE`
2. copy following vimscript to the buffer
```
vim9script

def HighlightedYank(hlgroup = 'Pmenu', duration = 250)
    var type = v:event.regtype ?? 'v'
    var pos = getregionpos(getpos("'["), getpos("']"), {type: type})
    for p in pos
        echo p[0]
    endfor
enddef

augroup hlyank | au!
    autocmd TextYankPost * HighlightedYank()
augroup END

```
3. `:so`
4. `yy` any line

### Expected behaviour

It shoud not segfault.

[![asciicast](https://asciinema.org/a/BWJZnIwUpPCCNupteMxSTrg7U.svg)](https://asciinema.org/a/BWJZnIwUpPCCNupteMxSTrg7U)

### Version of Vim

9.1.589

### Environment

windows, debian

**Comment by zeertzjq** [comment]
In the documentation the return type of `getregionpos()` is wrong as well. It says it returns:
```
		Return type: list<string>
```
but that's the return type of `getregion()` (which doesn't have its return type documented), and the correct return type is `list<list<list<number>>>`.
