### ISSUE TITLE
A couple of minor corrections to the docs

### ISSUE THREAD

**Issue by lkintact** [vim/vim#15278]
### Steps to reproduce

1. In `doc/mbyte.txt`, line `496`, `in a xterm` should be replaced with `in an xterm`.
2. In the same file, line `1382`, `UTF-8.` should not be colored `helpHeadline`.

### Expected behaviour

.

### Version of Vim

9.1.512.

### Environment

.

**Comment by chrisbra** [comment]
as far as I know, `an` is only used for words that start with a `vowel` or a silenced `h`. Since this is not the case here, `a` should be correct. I fix the other issue.

**Comment by lkintact** [comment]
I'm not a native English speaker either, but as far as I understand, `xterm` is pronounced as  `eks-term`, so the first sound is a vowel, so `an` should be used.
Also, `:lh an xterm` yields 64 results whle `:lh a xterm` only yields this one.

**Comment by chrisbra** [comment]
alright, let me make this change then as well. Thanks!

**Comment by zzzyxwvut** [comment]
I would argue that XTerm is [a proper noun](https://en.wikipedia.org/wiki/Proper_noun) like Vim, and as  
such, its name should be capitalised (unless the context  
suggests its binary, i.e. `xterm`) and take no article in  
general.  But seeing a few stray instances of `an xterm` in  
its manual page (patch `#392`), `an X terminal` is likely  
implied there and locally.
