### ISSUE TITLE
Can't get '] boundary of some yanked text

### ISSUE THREAD

**Issue by habamax** [vim/vim#15276]
### Steps to reproduce

1. `vim -Nu NONE`
2. paste following vimscript
```
vim9script

def HighlightedYank(hlgroup = 'Pmenu', duration = 250)
    var type = v:event.regtype ?? 'v'
    var pos = getregionpos(getpos("'["), getpos("']"), {type: type})
    echow pos
enddef

augroup hlyank | au!
    autocmd TextYankPost * HighlightedYank()
augroup END
```
4. `:so`
3. goto line with `enddef` and do `vj` to select 2 lines: enddef and empty line
4. `y` to yank selected text

### Expected behaviour

Result of getregionpos is printed, where I would expect data for 2 rows, instead there are 3 rows:

```
[[[7, 7, 1, 0], [7, 7, 6, 0]], [[7, 8, 0, 0], [7, 8, 0, 0]], [[7, 9, 1, 0], [7, 9, 1, 0]]]
```

Basically it means `getpos("']")` returns position of the first character of the non-yanked line.

Currently it prevents proper implementation of highlight yank functionality for this edge case.

[![asciicast](https://asciinema.org/a/YSjYVGLopMMhSl1zOf5jm0jgo.svg)](https://asciinema.org/a/YSjYVGLopMMhSl1zOf5jm0jgo)

### Version of Vim

9.1.589

### Environment

debian, windows, tui, gui

**Comment by habamax** [comment]
Oh, I should be better at reading docs.

Thanks a ton, @zeertzjq!

**Comment by zeertzjq** [comment]
Hmm, it seems that after #16772 it's no longer necessary to add this `exclusive` argument?

**Comment by habamax** [comment]
> Hmm, it seems that after [#16772](https://github.com/vim/vim/pull/16772) it's no longer necessary to add this `exclusive` argument?

Indeed, just tried it and now it doesn't need exclusive arg. Idk if this is a bug(fix) or should have been like this in the first place.

**Comment by JimZhouZZY** [comment]
Previously 'yank' operation didn't consider the situation when 'oap->inclusive' is `false`, hence the marks needs are 1 position ahead of where it should be. I think the snippet adapted the wrongly set marks by using difference offsets.

So I think we should first remove the offsets.

Also, as the offset is removed, when `set selection=exclusive`, if we pass no related argument to `getregionpos()`,  the function will adapt with `selection=exclusive`, this will cause the return value 1 position behind of where it should be.

Hence, I think we should pass `exclusive: false` to `getregionpos()`

**Comment by habamax** [comment]
> Hence, I think we should pass `exclusive: false` to `getregionpos()`

It works now without passing anything:


```
vim9script

def HighlightedYank(hlgroup = 'Pmenu', duration = 250)
    if v:event.operator !=? 'y' | return | endif
    # if clipboard has autoselect (default on linux) exiting from Visual with ESC
    # generates bogus event and this highlights previous yank
    if v:event.regname == "*" && v:event.visual | return | endif

    var type = v:event.regtype ?? 'v'
    var pos = getregionpos(getpos("'["), getpos("']"), {type: type})
    var hlpos = pos
        ->filter((_, v) => v[0][2] != 0)
        ->mapnew((_, v) => {
            var col_beg = v[0][2] + v[0][3]
            var col_end = v[1][2] + v[1][3]
            return [v[0][1], col_beg, col_end - col_beg + 1]
        })
    if hlpos->len() > 0
        var m = matchaddpos(hlgroup, hlpos)
        timer_start(duration, (_) => m->matchdelete(win_getid()))
    endif
enddef

augroup hlyank | au!
    autocmd TextYankPost * HighlightedYank()
augroup END
```

[![asciicast](https://asciinema.org/a/yQ20DvR32hf89yIooHpocDVBj.svg)](https://asciinema.org/a/yQ20DvR32hf89yIooHpocDVBj)

**Comment by JimZhouZZY** [comment]
It is incorrect when `selection=exclusive` is set, isn't it?

https://github.com/user-attachments/assets/aa6712f4-e83f-4625-8562-0ea2f3686903

**Comment by habamax** [comment]
oh, indeed.
