### ISSUE TITLE
Internal error with file completion with fuzzy

### ISSUE THREAD

**Issue by techntools** [vim/vim#15287]
### Steps to reproduce

1. Started vim with vim -u NONE
2. Pressed ```C-X``` ```C-F```

![Screenshot from 2024-07-18 11-11-49](https://github.com/user-attachments/assets/d8488bc2-6edf-41bd-a26e-43d88b7b59fb)

### Expected behaviour

There should not be error

### Version of Vim

Latest vim compiled from source

### Environment

OS: Ubuntu 20

Terminal: Kitty

$TERM: tmux-256color

Shell: bash

**Comment by techntools** [comment]
@glepnir

**Comment by glepnir** [comment]
the root dir is what and how many files on this dir.

**Comment by glepnir** [comment]
reproduced.

**Comment by glepnir** [comment]
@techntools  could you check this . because leader can include path.. i dont't handle it..

```diff
diff --git a/src/insexpand.c b/src/insexpand.c
index fa4ac7dd3..63ab1252d 100644
--- a/src/insexpand.c
+++ b/src/insexpand.c
@@ -3538,7 +3538,7 @@ get_next_filename_completion(void)
     char_u     **sorted_matches;
     int                *fuzzy_indices_data;

-    if (in_fuzzy)
+    if (in_fuzzy && (vim_strchr(leader, '/') == NULL && vim_strchr(leader, '\\') == NULL))
     {
        vim_free(compl_pattern);
        compl_pattern = vim_strsave((char_u *)"*");
```

**Comment by techntools** [comment]
@glepnir Error is gone. File completion is working.

**Comment by glepnir** [comment]
thanks for your feedback and test 👍
