### ISSUE TITLE
`vim` appears to hang with "Press ENTER or type command to continue"

### ISSUE THREAD

**Issue by errael** [vim/vim#15300]
### Steps to reproduce

There's a problematic interaction between `popup_dialog`/`popup_filter_yesno` and `Press ENTER ...`

Start vim with
```
gvim -u NONE -U NONE
```
then source
```
vim9script
echo 'one'
echo 'two'
popup_dialog('y/n?', {filter: 'popup_filter_yesno'})
```
See the message
```
Press ENTER or type command to continue
```
Press ENTER and nothing happens. `Ctlr-C` or a very few other keys get out, but **the `popup_dialog` is never seen**.

### Expected behaviour

The most obvious is to handle `ENTER` and then display the popup.

### Version of Vim

9.1.586

### Environment

ubuntu/gtk3

**Comment by errael** [comment]
There was a post to vim dev, that asked about this issue
https://groups.google.com/d/msgid/vim_dev/3af9de4f-bbfa-47bd-8a7d-761f17cb581c%40raelity.com

**Comment by Shane-XB-Qian** [comment]
Why your PR is only changed for `c == CAR` when 'need_wait_return'?

Supposed:
- either it should be nothing (kept it as it was though looked weird)
- or like general cases for 'need_wait_return' e.g emit some dummy ':' cmd

-- 
shane.xb.qian

**Comment by errael** [comment]
> Why your PR is only changed for `c == CAR` when 'need_wait_return'? 

With the current situation when you run the failing example 
1. **the popup is never seen, and there is no way to see it**.
2. `vim` seems to hang

IMHO, both seem like a serious bugs. This PR address those bugs while still keeping the spirit of `popup_filter_yesno`. 

With `popup_filter_yesno` **nothing should be run** until the popup is read and dismissed, allowing `:cmd` would violate that contract.

> Supposed: - either it should be nothing (kept it as it was though looked weird) - or like general cases for 'need_wait_return' e.g emit some dummy ':' cmd
> […](#)
> -- shane.xb.qian

**Comment by Shane-XB-Qian** [comment]
Why 'Press ENTER' is OK to you,
but 'type command' is not OK?
Those are all general ways for/when prompt: 'Press ENTER or type command to continue'

why impl half?
or why just kept it as it was, or impl completely?

-- 
shane.xb.qian

**Comment by errael** [comment]
> Why 'Press ENTER' is OK to you, but 'type command' is not OK? 

I've answered this already. I repeat
- allowing :cmd would violate the `popup_filter_yesno` contract
- doing nothing leaves some bad bugs

This PR is a **compromise**.

1. open a PR if there's something better
2. I'm done answering the same question; here's a chance to get the last word

> Those are all general ways for/when prompt: 'Press ENTER or type command to continue' why impl half? or why just kept it as it was, or impl completely?
> […](#)
> -- shane.xb.qian

**Comment by Shane-XB-Qian** [comment]
funny answer~ :lol:
if it can partially impl, then was there some harm to use ctrl-c to stop such 'hang' ?
// why such PR was accepted or needed~ aha~

--
shane.xb.qian

**Comment by errael** [comment]
> was there some harm to use ctrl-c to stop such 'hang' ?

The popup is never displayed, which is stated in the "OriginalPost". If you run the test in OP and use `ctrl-c`, the popup is never display which is a serious problem for a popup that describes an error.

**Comment by Shane-XB-Qian** [comment]
i do not see there problem, it is ctrl-c for.

--
shane.xb.qian

**Comment by errael** [comment]
> i do not see there problem, it is ctrl-c for.

https://en.wiktionary.org/wiki/there_are_none_so_blind_as_those_who_will_not_see

**Comment by Shane-XB-Qian** [comment]
what is in that link? or what you were trying to say?
what I am saying is: damn, how the quality is.

--
shane.xb.qian
