### ISSUE TITLE
Regression: exists(':keepalt') (and 5 more) return 0 instead of 2 (since Vim 9.1.352)

### ISSUE THREAD

**Issue by inkarkat** [vim/vim#15305]
### Steps to reproduce

`exists(':keepalt')` returns `0` instead of `2` even though `:keepalt` (even on its own) is a valid built-in command.

### Expected behaviour

Scripts need a reliable way to query whether a command exists.

My [ingo-library plugin](http://www.vim.org/scripts/script.php?script_id=4433) uses a [a check](https://github.com/inkarkat/vim-ingo-library/blob/5321e59c5a2628b4567cb4fc2b629dbc60a7a30a/autoload/ingo/compat/commands.vim?plain=1#L27) to return an emulation of the `:keeppatterns` command for older Vim versions that don't have it. That emulation had scoping side-effects that triggered a bug in one of my plugins. So this was a very subtle problem ;-)

### Version of Vim

9.1.352 .. 9.1.602

### Environment

Vim on Ubuntu 20.04 LTS (shouldn't matter)

I've bisected the problem to https://github.com/vim/vim/commit/ed908f760d9fe933690745bac91aedb698bbd48f / v9.1.0352

A total of 6 commands (ignoring the `:{`, see below) are affected.

```
:echo filter(getcompletion('', 'command'), 'exists(":" . v:val) == 0')
['*', '++', '--', 'keepalt', 'keepjumps', 'keeppatterns', '{']
```
---

Furthermore, `:{` isn't an actual command, so it's a bit problematic that both `:{` and `:}` are in the list of completions, and `:echo exists(':}')` actually returns `2`, but `:}` gives `E1128: } without {: }` But that's a separate issue.

**Comment by chrisbra** [comment]
@basilisk0315 can you please check it?

**Comment by inkarkat** [comment]
The problem might have something to do with the `:k` command, which is a command on its own but also the common prefix of the `:keep...` commands.

Interestingly, `exists(':k')` returns `1` (match with start of a command), but it's both that and `2` (full match with a command) - I would have expected `2` here. (But then again the whole `:k` is not supported in Vim9 script any longer.)

**Comment by chrisbra** [comment]
I see the issue.

What about those:
```
:echo filter(getcompletion('', 'command'), 'exists(":" . v:val) == 0')
['*', '++', '--', 'keepalt', 'keepjumps', 'keeppatterns', '{']
```
Let's ignore the `:keep*` for a second, I can fix those. 
`:*` is only valid, when you do `:set cpo+=*`. I think that is fine.
`:++` and `:--` is only valid in vim9 context, I think that is fine.

And I can ignore the `:{` and `:}` when completing the items. I think this should be fine then?

**Comment by inkarkat** [comment]
Yeah, I also think that `:{` and `:}` shouldn't be offered by completion, and `:*`, `:++` and `:--` are too obscure to bother. :+1:
