### ISSUE TITLE
Shift+Insert does not paste from the clipboard in Windows console

### ISSUE THREAD

**Issue by nickspoons** [vim/vim#15326]
### Steps to reproduce

In Windows 10 or 11, launch the console with e.g. `Win+R` -> `cmd.exe`
Start vim with `vim --clean`, enter insert mode, and hit `Shift+Insert`. Instead of inserting the contents of the clipboard, the mode switches to "replace" mode, and back to "insert" after another `Shift+Insert`, as if `Insert` was being typed without `Shift`.

### Expected behaviour

The contents of the clipboard (visible next to `"*` in `:registers` output) should be inserted.

### Version of Vim

9.0.1146 and later

### Environment

Tested in Windows10 and Windows11. This only occurs in the default windows console (`cmd.exe`), not powershell terminals or Windows Terminal.

After bisecting by installing Windows releases from https://github.com/vim/vim-win32-installer, this behaviour begins in 9.0.1148 and did not occur in 9.0.1140 (the previous release). This release includes 8 patches, the obvious culprit is [9.0.1146 MS-Windows: various special keys and modifiers are not mappable](https://github.com/vim/vim/commit/c8b204952f0452fe1276d30ae6a5d38a3f421b95), introduced in #11768

**Comment by chrisbra** [comment]
Hm, I didn't notice this, because for me `cmd.exe` always starts in the Windows terminal

**Comment by nickspoons** [comment]
Tagging @zewpo, as the author of #11768

**Comment by zewpo** [comment]
ahh, just saw this, will have a look
