### ISSUE TITLE
In vim9script, char2nr() does not return correct values for UTF8 characters

### ISSUE THREAD

**Issue by kennypete** [vim/vim#15324]
### Steps to reproduce

The following vimscript will produce correct output for the UTF8 character Ā:

```vim
function g:BytesUTF8()
  echo char2nr("Ā"[0], 0) .. ' ' .. char2nr("Ā"[1], 0)
  echo char2nr("Ā"[0], 1) .. ' ' .. char2nr("Ā"[1], 1)
endfunction
```

Output echoed:
```
196 128
196 128
```

The following vim9script should do the same thing:

```vim
vim9script
def g:BytesUTF8vim9()
  echo char2nr("Ā"[0], 0) .. ' ' .. char2nr("Ā"[1], 0)
  echo char2nr("Ā"[0], 1) .. ' ' .. char2nr("Ā"[1], 1)
enddef
```

It doesn't. Its echoed output is:

```
256 0
256 0
```

In the vim9script function, what's being returned is the Unicode code point and a zero, not what should be returned, i.e., the UTF8 bytes, like the _identical_ lines do in vimscript.

### Expected behaviour

The output of `char2nr()` should be the same, regardless of whether the script is vimscript or vim9script. Also note, `:echo char2nr("Ā"[0]) .. ' ' .. char2nr("Ā"[1])` in cmdline mode similarly produces correct `196 128` output.

### Version of Vim

9.1.90

### Environment

The same result happens in Windows 11 (GUI or console) or WSL Debian. It also happens back to (at least) 8.2.1584, whether run using `vim --clean`, etc.

**Comment by errael** [comment]
I don't know if this is relevant to the issue you're experiencing, but indexing a string is different between `legacy` and `vim9script`.

`:he vim9-string-index` says
```
Indexing a string with [idx] or taking a slice with [idx : idx] uses character
indexes instead of byte indexes.  Composing characters are included.
```

**Comment by zeertzjq** [comment]
And instead you can use `strpart()` for by indexing:
```vim
vim9script
def g:BytesUTF8vim9()
  echo char2nr("Ā"->strpart(0, 1), 0) .. ' ' .. char2nr("Ā"->strpart(1, 1), 0)
  echo char2nr("Ā"->strpart(0, 1), 1) .. ' ' .. char2nr("Ā"->strpart(1, 1), 1)
enddef
```
