### ISSUE TITLE
E340 & E341 completeopt+=fuzzy and i_CTRL-X_CTRL-F

### ISSUE THREAD

**Issue by kawarimidoll** [vim/vim#15331]
### Steps to reproduce

1. `set completeopt+=fuzzy`
2. enter insert mode and write some path
3. type `<c-x><c-f>`
4. E340 & E341

This demo shows:
1. it works correctly with `vim --clean`
2. the error occurs once the option is set

https://github.com/user-attachments/assets/8612303a-8312-4a03-ba7f-27581ae7ebd8

### Expected behaviour

handle these errors

### Version of Vim

VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Jul 18 2024 18:4 0:28) macOS version - arm64 Included patches: 1-600 Compiled by Homebrew Huge version without GUI.

### Environment

OS: macOS Sonoma 14.5
Terminal: wezterm 20240203-110809-5046fc22
value of $TERM: xterm-256color
Shell: zsh 5.9 (arm-apple-darwin23.0.0)

### Logs and stack traces

```shell
E340: Internal error; if you can reproduce please report a bug
E341: Internal error: lalloc(0, )
```

**Comment by habamax** [comment]
duplicate https://github.com/vim/vim/issues/15287

**Comment by chrisbra** [comment]
closing then as duplicate
