### ISSUE TITLE
Support of Wayland on Linux

### ISSUE THREAD

**Issue by liumingedwin** [vim/vim#15343]
Wayland Protocol has been for a long time. It is certain that Vim as well as GVim needs to migrate to Wayland. GVim's backend GTK3 supports Wayland already, so the migration should be much easier. After migration, GVim will run much faster.

**Comment by chrisbra** [comment]
You don't specify what currently isn't working. Wayland support has landed as of patch [v9.1.0064](https://github.com/vim/vim/releases/tag/v9.1.0064).

Currently missing is proper clipboard support. But this is rather a matter of a developer with the proper knowledge to add the support to it. Which we apparently do not have.

**Comment by chrisbra** [comment]
okay, no more comment? Closing then. Clipboard support is covered by this issue: #5157

**Comment by liumingedwin** [comment]
Oh sorry for my ignorance. I didn't look through the changelogs before so i missed the Wayland flag mentioned in it. (>﹏<)
So how long will it take to enable Wayland supports by default? 🤔

**Comment by chrisbra** [comment]
what do you mean by default? It's already there.

**Comment by liumingedwin** [comment]
Enable by default
It should be easy after the fix of clipboard
