### ISSUE TITLE
[Termdebug] balloon display evaluation of variable under mouse doesn't work

### ISSUE THREAD

**Issue by errael** [vim/vim#15359]
### Steps to reproduce

- `gvim -c "packadd termdebug" -c "Termdebug" ...`
- set a breakpoint then run
- At breakpoint hover the mouse over a variable in the breakpointed function
- nothing happens

### Expected behaviour

Staring up with Termdebug8, using the same version of vim, and things work as expected.

### Version of Vim

9.1.618

### Environment

ubuntu gtk3

**Comment by errael** [comment]
@ubaldot ping

**Comment by ubaldot** [comment]
Hello! I am on vacation right now and I won't have access to my laptop for (at least) the next 10 days. 

If someone wants to take it in the meantime is welcome!

**Comment by errael** [comment]
> on vacation right now

Europe knows how to do vacations.
