### ISSUE TITLE
Unable to use drop on git rebase

### ISSUE THREAD

**Issue by kirbyfern** [vim/vim#1535]
<img width="377" alt="screen shot 2017-03-05 at 6 45 11 pm" src="https://cloud.githubusercontent.com/assets/20747057/23595099/1535edb8-01d4-11e7-8b36-00ce45721cf1.png">

drop/d is not working on the command 

### git rebase -i <SHA id>

notice drop is not color highlighted , how do I fix this issue ?

**Comment by k-takata** [comment]
Support for "drop" has been already added with this: https://github.com/vim/vim/commit/89bcfda6834aba724d12554a34b9ed49f5789fd5#diff-95ef9c7e347c1206aec3c51522f5a517R21
Please make sure that you are using runtime files newer than this.

**Comment by kirbyfern** [comment]
@k-takata thanks I will go through this asap , and try to close the issue thanks
