### ISSUE TITLE
Add superhtml and ziggy filetype 

### ISSUE THREAD

**Issue by EliSauder** [vim/vim#15355]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
I guess technically it is currently impossible to do? I am working on adding superhtml support to the Neovim ecosystem (will be followed by ziggy), one of the things that is needed is adding the file type support.

**Describe the solution you'd like**
Ideally, the `superhtml` file type would be added using the `.shtml` file extension as described [here](https://github.com/kristoff-it/superhtml/issues/20#issuecomment-2248214586) by the creator of superhtml and then the `ziggy` file type would be added using the `.ziggy` and `.ziggy-schema` file extensions as described [here](https://ziggy-lang.io/).

**Additional context**
As these are simple changes, I am willing to do the leg work of the changes (though I am unfamiliar with vimscript atm). However, since `.shtml` is currently mapped and this is my first time being involved with the project I wanted to open an issue for discussion.

**Comment by chrisbra** [comment]
`.shtml` is typically used for server-side includes, that would mean you would need to detect the filetype programatically by inspecting the file content. Check the function `FThtml()` in the file `runtime/autoload/dist/ft.vim` 

Please don't forget to add a test into testdir/test_filetype.vim file.

You can also have a look at the various commits from the past, that add new filetype protection, you can check from git by running `git log -v -p --grep 'filetype:'`
