### ISSUE TITLE
Unmatched candidates are displayed on i_CTRL-X_CTRL-F & completeopt+=fuzzy

### ISSUE THREAD

**Issue by kawarimidoll** [vim/vim#15357]
### Steps to reproduce

1. `vim --clean`
2. `set completeopt=menuone,noselect,fuzzy`
3. insert path like `/qqq` that does not exist
4. type `<c-x><c-f>` to start files completion
5. files or directories don't have 'qqq' in their name, but they are displayed

<img width="720" alt="fuzzy-path-completion" src="https://github.com/user-attachments/assets/caa4c3d4-95a2-40a3-bd44-9b45e71a553e">

### Expected behaviour

Only candidates with a match (in the example above, files containing 'q' three times) are displayed.
If there are no matching files, nothing is displayed. 

### Version of Vim

9.1.618

### Environment

OS: macOS Sonoma 14.5
Terminal: wezterm 20240203-110809-5046fc22
value of $TERM: xterm-256color
Shell: zsh 5.9 (arm-apple-darwin23.0.0)

**Comment by techntools** [comment]
@glepnir
