### ISSUE TITLE
VIM installation failed on Ubuntu 24.04

### ISSUE THREAD

**Issue by luuqh** [vim/vim#15356]
### Steps to reproduce

1. Install Ubuntu 24.04
2. Allow is to update packages
3. sudo apt install vim

### Expected behaviour

The installation should be succesful. 

<img width="1003" alt="Screenshot 2024-07-26 at 9 44 59 PM" src="https://github.com/user-attachments/assets/c64e09c5-dc0f-4adb-9526-c3df39f0ad75">

### Version of Vim

2:9.1.0016-1ubuntu7

### Environment

- OS: Ubuntu 24.04 fresh installation as of today 26 July 2024

### Logs and stack traces

```shell
> sudo apt install vim
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 vim : Depends: vim-common (= 2:9.1.0016-1ubuntu7) but 2:9.1.0016-1ubuntu7.1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by chrisbra** [comment]
that is an Ubuntu question, not a real Vim issue, sorry we cannot answer this here.
