### ISSUE TITLE
runtime/syntax/indent.vim missing options

### ISSUE THREAD

**Issue by systemmonkey42** [vim/vim#1536]
The option '--indent-label N' is missing from the "indent" syntax file.  As a result valid options
are highlighted as errors.

Thanks

**Comment by systemmonkey42** [comment]
Sorry, I take that back, its more broken than that, and is probably a holdover from an earlier version of indent.

Eg,

> syn match indentOptions '-i\|--indentation-level\|-il\|--indent-level'

should be 

> syn match indentOptions '-i\|--indent-level\|-il\|--indent-label'

This seems to be enough to fix the issue.

(Note, this is in the 'if !exists(indent_is_bsd) block,.  Indent is in fact GNU indent 2.2.11 on Linux)

**Comment by chrisbra** [comment]
have you contacted the maintainer?

**Comment by systemmonkey42** [comment]
My apologies, I didn't even look at the maintainer details.

I'll email them directly, sorry for the noise.

**Comment by dkearns** [comment]
This was fixed by 88a4205f1cfbdc328e987ab00521fc8a22447fc3

**Comment by k-takata** [comment]
Closing then.
