### ISSUE TITLE
Insert-mode completion no longer scans other buffers, regardless of &complete

### ISSUE THREAD

**Issue by jessepav** [vim/vim#15370]
### Steps to reproduce

1. `set complete=.,w,b,u completeopt&`
2. `set hidden`
3. Insert text in buffer: `identifier1`
4. `enew`
5. Insert `iden` and hit `Ctrl-P` to activate completion. No suggestions are given.

### Expected behaviour

The identifier from the other buffer should have been found.

### Version of Vim

9.1.0631

### Environment

Ubuntu 22.04

**Comment by zeertzjq** [comment]
Cannot reproduce

**Comment by jessepav** [comment]
A `git bisect` shows that for me the issue begins with commit 8159fb18a92e9a9f5e35201bd92bf651f4d5835c:

> patch 9.1.0598: fuzzy completion does not work with default completion

Any ideas for what could trigger the bug for me? `vim -u NONE` shows the same behavior.

**Comment by razimantv** [comment]
I am facing the same issue on Arch. With version 9.1.532, insert completion checks other buffers correctly. With version 9.1.611 it does not.

**Comment by habamax** [comment]
There were series of patches wrt to fuzzy completeopt, some of them had regressions.
Looks like latest master doesn't have that issue.

**Comment by chrisbra** [comment]
There was someone one the vim-dev mailinglist also posting about this, but specifically only for using Ctrl-P.

**Comment by chrisbra** [comment]
I also cannot reproduce this

**Comment by jessepav** [comment]
> There was someone one the vim-dev mailinglist also posting about this, but specifically only for using Ctrl-P.

You're right -- it only occurs for Ctrl-P:  Ctrl-N works properly for me.

Also, if I `set completeopt+=fuzzy`, then Ctrl-P starts working for me too!

I'm running a freshly compiled `master`

**Comment by jessepav** [comment]
It's this part of patch v9.1.0598 that causes the problem:

```patch
-    st.cur_match_pos = (compl_dir_forward())
-                               ? &st.last_match_pos : &st.first_match_pos;
+    if (in_fuzzy)
+       st.cur_match_pos = (compl_dir_forward())
+                                   ? &st.last_match_pos : &st.first_match_pos;
+    else
+       st.cur_match_pos = &st.last_match_pos;
```

**Comment by chrisbra** [comment]
so if you reverse that part of the patch, it works again?

**Comment by jessepav** [comment]
Yes - if I revert that part of the patch, it works for me, both `Ctrl-P` and `Ctrl-N`.

**Comment by chrisbra** [comment]
Yeah, it looks wrong. Let me see if I can create a PR with a test for this
