### ISSUE TITLE
Weird characters inserted when holding down 'asd'

### ISSUE THREAD

**Issue by VTrngNghia** [vim/vim#1537]
I was just testing my newly installed Vim when I found out this very weird behaviour: In insert mode, if I keep my fingers on `a`, `s`, and `d`, then `k`, `l`, `;`, `[`, or `=`, Vim will automatically insert some weird characters after `asd` sos that the result for each case would look like this:
`asdj<F6>kl`
`asd<F6>l=`
`asd<F6>;4`
`asd<F6>[`
`asd<F6>=[`
Throwing in modifier keys like Ctrl, Alt or Shift will give even more weird result.
Is this a bug or a feature? If feature, then what does it serve?

**Comment by systemmonkey42** [comment]
While most terminals allow you to press combinations of keys like control/shift/etc, I'm not sure 'asd' is a valid key combination.  What terminal are you using? Have you mapped that combination to CTRL or META or its ilk?

> The patient says, "Doctor, it hurts when I do this." "Then don't do that!"

**Comment by chrisbra** [comment]
You might see some internal keys when pressing several other keys. Not sure.let's close that as invalid.
