### ISSUE TITLE
Pattern matching for tmux syntax is incorrect

### ISSUE THREAD

**Issue by ericpruitt** [vim/vim#1538]
My filename pattern matching in https://github.com/vim/vim/pull/1529 was modified when it was merged without consulting with me, and the change effectively makes the syntax file useless in the common case of running `vim ~/.tmux.conf`. Please fix the glob so that it _also_ matches ".tmux.conf" (the default path is `$HOME/.tmux.conf`) instead of just "tmux.conf" or remove my name from the files; I don't want people reporting a bug to me that I did not introduce since Vim's own guidelines state "If you find a problem with one of these files or have a suggestion for improvement, please first try to contact the maintainer directly. Look in the header of the file for the name and email address."

**Comment by chrisbra** [comment]
fixed as of 036986f1507d223549d11
