### ISSUE TITLE
[vim9script] `call({string_name}, args)` doesn't work with imported function

### ISSUE THREAD

**Issue by errael** [vim/vim#15381]
### Steps to reproduce

With the following two files in the same directory, do
```
vim -c ':source call_string.vim'
```
and observe the output
```
Error detected while processing command line..script /src/tools/vim/src/call_string.vim:
line    6:
E117: Unknown function: ImportedFoo
```
**call_string.vim**
```
vim9script
import './imported_call_string.vim' as i_imp
const ImportedFoo = i_imp.ImportedFoo

call('ImportedFoo', ['call as string through local importedFoo'])
```

**imported_call_string.vim**
```
vim9script

export def ImportedFoo(arg: any)
    echo 'In Imported Foo:' arg
enddef
```

### Expected behaviour

Expect the function to execute.

I'm putting together a PR, but it's not clear to me that it's the best (or even a good) fix. So this issue is opened in case that PR should be closed without merge.

### Version of Vim

9.1.621

### Environment

ubuntu gtk3

**Comment by errael** [comment]
It's interesting to note that if **call_string.vim** has the lines
```

def LocalFoo(arg: any)
    echo 'In Local Foo:' arg
enddef

call('LocalFoo', ['local'])

echo typename(ImportedFoo)
echo typename(LocalFoo)
```
there's the output
```
In Local Foo: local
typename(ImportedFoo) func(any)
typename(LocalFoo) func(any)
```

**Comment by chrisbra** [comment]
> call('ImportedFoo', ['call as string through local importedFoo'])

ImportedFoo is a funcref, right? Is there a reason why you don't call it as such but rather as a `String`? Although I think it should also work as String

**Comment by errael** [comment]
> > call('ImportedFoo', ['call as string through local importedFoo'])
> 
> ImportedFoo is a funcref, right? Is there a reason why you don't call it as such but rather as a `String`? Although I think it should also work as String

Yes, it is a `funcref`. The issue is that I've got several, similarly named, imported functions. A string is calculated, and the idea is that the string named function is called. Currently I'm working around the problem with a `dict<func>` to get the correct funcref. It's ugly. It's workable in this situation because it's not an autoload script so the dict can be loaded with `func` values before the values are needed.

The autoload situation has no simple workaround. In this case doing `call('i_imp.FuncName', [])` is what's needed to avoid processing the script before the `func` value is required.
