### ISSUE TITLE
[feat] autocmd event after creating a new file

### ISSUE THREAD

**Issue by mazunki** [vim/vim#15393]
I have the following configuration to automatically set up some shellscripts:
```vim
augroup scripts
    autocmd BufNewFile * call AutodetectFiletype()
    autocmd BufNewFile * call SetShebang()
    autocmd BufNewFile filetype sh,python call SetExecutable()
augroup END
```
The issue is that `chmod +x %:p` doesn't actually work before the file already exists. Currently, I see two solutions to this problems, none of which I believe are great:
- The first is to simply  `touch` the file immediately on starting the buffer. This may leave stray files if I typo'd the filename or something
- The second is something like the following augroup
```vim
augroup deferred_newfile
    autocmd BufNewFile * let b:new_file = 1
    autocmd BufWritePost filetype sh,python if exists("b:new_file") | call SetExecutable() | endif
    autocmd BufWritePost * unlet b:new_file
augroup END
```

Ideally, I would like to simply `autocmd BufWriteNew filetype sh,python call SetExecutable()`, and not worry about keeping track of it myself. Initially, I thought to look for `BufNewFilePost`, but after second thought that reads like something happening immediately after loading the buffer for a new file.

Do we want `BufWriteNew` as an autocommand event?

If so, I believe the following sequence would make sense: **`BufWriteNewPre`** => `BufWritePre` => **`BufWriteNew`** => `BufWritePost` => **`BufWriteNewPost`**. My thinking about putting `BufWriteNew` after `BufWrite` is that I expect the file to already be done writing when I run my autocommand, and my understanding is that `Pre` and `Post` commands should, ideally, come in pairs (the latter clearing up whatever the prior may have littered).

Of course, if this is possible already, please let me know. :) Otherwise, I'd be happy to attempt to implement it.

**Comment by chrisbra** [comment]
Is there a reason you cannot `call SetExecutable()` on `BufWritePost()` optionally only doing it if the file has no executable bits set yet?

**Comment by mazunki** [comment]
I don't really want the behaviour to occur on all files. I sometimes have explicitly disabled execution of some files, and I wouldn't want opening them in vim to make other "unexpected" changes to them.

The reason I have the autocommand in the first place is mainly to avoid exiting vim just to chmod +x (I find it quicker than `:!chmod +x %` usually), and reopen vim again after the fact while I'm developing the script.

**Comment by chrisbra** [comment]
Yes, so you could use `BufWritePost *.sh,*.py call SetExecutable()` and inside the `SetExecutable()` function, check if the file has the exectuable bit set. You don't even need to use `:!chmod`, you can use a combination of `system()`, `stat` and `chmod`.

**Comment by mazunki** [comment]
I might be explaining myself poorly. The issue with using `BufWritePost` is that it will /always/ set the executable bit when I save a file. I only want this to happen if vim is the one creating the file. If the file already existed, I don't want my file modes to be touched at all.

The following script does exactly what I want:
```vim
  autocmd BufNewFile * let b:new_file = 1
  autocmd BufWritePost *.py,*.sh if exists('b:new_file') |
    call SetExecutable() |
  endif
  autocmd BufWritePost if exists('b:new_file') | unlet b:new_file | endif
```

but I would like to simplify it to this single line:
```vim
  autocmd BufWriteNew *.py,*.sh call SetExecutable()
```

**Comment by chrisbra** [comment]
Thanks for clarification, I see now. However honestly, I think this sounds very much like a too much niche use case

**Comment by mazunki** [comment]
It may be. I feel like more use cases than just this one may exist, although I guess there is some point to keeping the codebase small if it's something which is rarely going to be used by most users.

Can custom autocommand events be added by the user?

**Comment by chrisbra** [comment]
closing, as too niche use case.
