### ISSUE TITLE
completeopt+=fuzzy does not honor completeslash=slash (Windows)

### ISSUE THREAD

**Issue by egesip** [vim/vim#15392]
### Steps to reproduce

1. set completeopt+=fuzzy
2. set completeslash=slash
3. Type C:/ and trigger file completion, the match list is empty (non fuzzy complete would give matches).
4. Type C:\ and trigger file completion, matches are found, but text is completed with foward slashes, making any follow-up completion impossible.

### Expected behaviour

Expecting fuzzy file completion to behave the same as non-fuzzy file completion when it comes to matching slashes (backward or forward).
Thanks a lot!

### Version of Vim

9.1.636

### Environment

Operating System: Windows

**Comment by habamax** [comment]
@glepnir fyi

**Comment by glepnir** [comment]
hello thanks for report. I haven't used Windows for many years so some options related to Windows are automatically ignored by my mind. Can you try this diff? if not works.. i may need find a windows env for fix.

```diff
diff --git a/src/insexpand.c b/src/insexpand.c
index 3a168848f..95b4f24d9 100644
--- a/src/insexpand.c
+++ b/src/insexpand.c
@@ -3552,9 +3552,15 @@ get_next_filename_completion(void)
     size_t     path_with_wildcard_len;
     char_u     *path_with_wildcard;

+#ifdef BACKSLASH_IN_FILENAME
+    char       pathsep = curbuf->b_p_csl[0] == 's' ? '/' : '\\';
+#else
+    char       pathsep = '/';
+#endif
+
     if (in_fuzzy)
     {
-       last_sep = vim_strrchr(leader, PATHSEP);
+       last_sep = vim_strrchr(leader, pathsep);
        if (last_sep == NULL)
        {
            // No path separator or separator is the last character,
```

**Comment by habamax** [comment]
I think it should use value of `completeslash` option to decide on pathsep

**Comment by glepnir** [comment]
in diff it already use

**Comment by habamax** [comment]
> in diff it already use

Oh, true, sorry missed it.

**Comment by egesip** [comment]
The patch works for me! Thanks!
There is still a slight difference in behavior with non-fuzzy matching though, but it is probably an evil edge case:
with non-fuzzy matching, even with `set completeslash=slash`, if I type in a `\` and `<c-x><c-f>`, vim will happily find matches, and even fix my initial `\` into a `/`.  
This does not happen with fuzzy completion, it doesn't find any match with an initial `\`.

**Comment by glepnir** [comment]
aha thanks !  good to know this bahavior :) and i create a new diff for this. could you try it sry for asking you to help me with the test 

```diff
diff --git a/src/insexpand.c b/src/insexpand.c
index 3a168848f..49848a32d 100644
--- a/src/insexpand.c
+++ b/src/insexpand.c
@@ -3552,9 +3552,25 @@ get_next_filename_completion(void)
     size_t     path_with_wildcard_len;
     char_u     *path_with_wildcard;

+#ifdef BACKSLASH_IN_FILENAME
+    char       pathsep = curbuf->b_p_csl[0] == 's' ? '/' : '\\';
+#else
+    char       pathsep = '/';
+#endif
+
     if (in_fuzzy)
     {
-       last_sep = vim_strrchr(leader, PATHSEP);
+#ifdef BACKSLASH_IN_FILENAME
+       if (curbuf->b_p_csl[0] == 's')
+       {
+           for (i = 0; i < leader_len; i++)
+           {
+               if (leader[i] == '\\')
+                   leader[i] = '/';
+           }
+        }
+#endif
+       last_sep = vim_strrchr(leader, pathsep);
        if (last_sep == NULL)
        {
            // No path separator or separator is the last character,
````

**Comment by egesip** [comment]
Seems to be all good now!
Many thanks!

**Comment by glepnir** [comment]
aha good to know :) but I will submit a PR the day after tomorrow to make sure you don't run into other edge cases. If there are any, I can try to fix them here in time.

**Comment by egesip** [comment]
Thank you so much @glepnir for working on fuzzy completion. So far so good with file completion. I found another unrelated issue with fuzzy and the "adding keyword completion" mode, so I opened a new issue: #15412.

**Comment by glepnir** [comment]
thanks i ran into that issue now  and will open pr for this issue fix.
