### ISSUE TITLE
Adding keyword completion not working with fuzzy completion

### ISSUE THREAD

**Issue by egesip** [vim/vim#15412]
### Steps to reproduce

Deactivate fuzzy completion if needed `:set completeopt-=fuzzy`.
In insert mode, type in `alpha bravo charlie`, then `<enter>`, and on the new line type `al<c-n><c-x><c-n>`.
The first `<c-n>` completes `al` into `alpha`, then the `<c-x><c-n>` enters the _adding keyword completion_ mode, and inserts `bravo` (the only match). Another `<c-x><c-n>` would insert `charlie`.

If you try to do this with `set completopt+=fuzzy`, `alpha` is inserted on `<c-n>` but the chained completion is not triggered on `<c-x><c-n>`, and `bravo` is not inserted.

### Expected behaviour

See the **Steps to reproduce**.
Thanks again for bringing fuzzy completion to Vim!

### Version of Vim

9.1.636

### Environment

Tested on Windows (but would suspect the issue is the same on other OSes)

**Comment by glepnir** [comment]
self-assignment

**Comment by egesip** [comment]
It is as you say, but the important point is about the `<c-x><c-n>` afterwards (which triggers the "adding-keyword-completion" mode):

- When fuzzy is off, I type `al`, vim inserts `alpha` as the only match, **then** I type `<c-x><c-n>` and I get `bravo` **automatically** inserted (the message line says `-- Adding Keyword Completion (^N^P) The only match`.

- When fuzzy is on, I type `al`, vim shows the popup menu with `alpha` and `charlie` (as expected) and inserts `alpha`. So far so good. But **then** if I type `<c-x><c-n>`, nothing happens. Yet the message line shows the same message as when fuzzy is off: `-- Adding Keyword Completion (^N^P) The only match`. But `bravo` is **not** inserted.

**Comment by egesip** [comment]
Sorry, maybe I am not clear at all, when I say I type `<c-x><c-n>`, I mean I type the keys ctrl-x then ctrl-n.

**Comment by glepnir** [comment]
@egesip  could your check pr #15424
