### ISSUE TITLE
ex_diffpatch: improper shell escaping

### ISSUE THREAD

**Issue by eti1** [vim/vim#1543]
rvim or vim -Z disallow shell commands
an improper shell arguments escaping in diffpatch command allows bypassing this restriction.
in diff.c:ex_diffpatch

ie.: ":diffpatch $(sh <&2 >&2)" will give you a shell.

regards,

Etienne

**Comment by brammool** [comment]
Etienne wrote:

> rvim or vim -Z disallow shell commands
> an improper shell arguments escaping in diffpatch command allows bypassing this restriction.
> in diff.c:ex_diffpatch
> 
> ie.: ":diffpatch $(sh <&2 >&2)" will give you a shell.

Thanks for reporting.  It's not su much releated to restricted mode.
I think using single quotes helps.  Not sure if that is the final
solution, but at least fixes it for this example.

-- 
From "know your smileys":
 2B|^2B	  Message from Shakespeare

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by jamessan** [comment]
Why not use `vim_strsave_shellescape` here instead of guessing at how to escape the name?

**Comment by eti1** [comment]
Indeed, just using single quotes won't work, look:
:diffpatch ';sh <&2 >&2;'

Thanks for pointing vim_strsave_shellescape out, jamessan. 
Here is a proper patch making use of it. 
[vim_diffpatch.patch.txt](https://github.com/vim/vim/files/835645/vim_diffpatch.patch.txt)

**Comment by brammool** [comment]
Yes, that's a better solution.  Thanks.
