### ISSUE TITLE
manual fold doubles comment string

### ISSUE THREAD

**Issue by teto** [vim/vim#1544]
When joining 2 commenteds lines, the joined line removes the prepending commentstring.
I wonder if we could do the same when creating a manual fold ?
In vimscript with the cursor on the first line, I have:
```
" comment
test
test2
```
If I run `zf2j` I end up with
```
" comment"{{{
test
test2"}}}
```
I would rather have the first line become `" comment{{{` (i.e., without the second `"`)

**Comment by chrisbra** [comment]
Fixed by [8.0.0453](https://github.com/vim/vim/releases/tag/v8.0.0453)
