### ISSUE TITLE
Zip plugin does not handle inner file name contain glob character

### ISSUE THREAD

**Issue by user202729** [vim/vim#15445]
e.g. if you create a zip file that contains a file with name `[a].txt` then the unzip command will look like

```bash
unzip -p -- a.zip \[a\].txt
```

to which `unzip` command will see its argument as `[a].txt` and perform another level of glob matching, resulting in no match.

In my version, it suffices to escape the characters `\[?*`. Escaping `]` appears to be unnecessary but I see no harm either.

```diff
--- a/runtime/autoload/zip.vim
+++ b/runtime/autoload/zip.vim
@@ -234,7 +234,7 @@ fun! zip#Read(fname,mode)
   " but allows zipfile://... entries in quickfix lists
   let temp = tempname()
   let fn   = expand('%:p')
-  exe "sil! !".g:zip_unzipcmd." -p -- ".s:Escape(zipfile,1)." ".s:Escape(fname,1).' > '.temp
+  exe "sil! !".g:zip_unzipcmd." -p -- ".s:Escape(zipfile,1)." ".s:Escape(escape(fname, '\?*[]'),1).' > '.temp
   sil exe 'keepalt file '.temp
   sil keepj e!
   sil exe 'keepalt file '.fnameescape(fn)
```

Not sure if it works on Windows/other platforms/implementations of `unzip`.

A small Python script for testing  [a.zip](https://github.com/user-attachments/files/16530612/a.zip)

**Comment by zeertzjq** [comment]
Please follow the bug report template and test with the latest commit.
