### ISSUE TITLE
[vim9class] Methods with a `super` call get lost in method dispatch

### ISSUE THREAD

**Issue by zzzyxwvut** [vim/vim#15449]
### Steps to reproduce

In the following examples, method dispatch on `super` fails to  
invoke the expected methods.

#### (1)

```
vim9script

class A
    def _ToString(): string
        return 'A'
    enddef
endclass

abstract class B extends A
    abstract def _ToString(): string

    def string(): string
##### The effect is as if it were written thus:
##      return this._ToString()
        return super._ToString()
    enddef
endclass

class C extends B
    def _ToString(): string
        return super.string()
    enddef

#   def string(): string
#       return this._ToString()
#   enddef
endclass

echo 'A' == C.new().string()
```

#### (2)

```
vim9script

class A
    def string(): string
        return 'A'
    enddef
endclass

class B extends A
    def string(): string
        return super.string()
    enddef
endclass

abstract class C extends B
    abstract def string(): string

    def _ToString(): string
#### This ‘fix’ won't mind looking for implementation elsewhere:
##      return this.string()
        return super.string()
    enddef
endclass

class D extends C
    def string(): string
        return super._ToString()
    enddef
endclass

echo 'A' == D.new().string()
```

### Expected behaviour

Proper method dispatch should be performed:
* In (1), the call chain should be:
  `C.new()` -> `B.string()` -> `A._ToString()`.

* In (2), the call chain should be:
   `D.new()` -> `D.string()` -> `C._ToString()` ->
     `B.string()` -> `A.string()`.

### Version of Vim

v9.1.0659

### Environment

GNU/Linux Debian (testing/trixie)

**Comment by errael** [comment]
In **(1)** I'm surprised that `abstract def _ToString(): string` in `class B` doesn't generate an error. (but I'm not sure why). 
I guess the infinite recursion makes sense when using `return this._ToString()`.

**(2)** With the "missing return" patch I'm seeing something particularly weird
```
Error detected while processing /tmp/g.vim[31]..function <SNR>46_D.string[1]..<SNR>46_D._ToString:
line    3:
E119: Not enough arguments for function: string
```

**Comment by zzzyxwvut** [comment]
> In (1) I'm surprised that `abstract def _ToString(): string` in `class B` doesn't generate an error. (but I'm not sure why).

Docs are silent on the matter, but having `abstract` methods  
overriding instance methods supported can be useful when  
inherited method implementations are not good enough and  
_must be_ overridden elsewhere (e.g. `string()`).

> I guess the infinite recursion makes sense when using return this.\_ToString().

Yes, but `super` must not degenerate into `this`.

> (2) With the "missing return" patch I'm seeing something particularly weird

Apparently, `C.string()` is picked up, as if it were written  
`this.string()`.  But, if you go and uncomment that line in  
`C._ToString()` and comment out its current `super.string()`, it  
will recurse.

I can reproduce `E119` with this hierarchy:

```
vim9script

interface I
    def string(): string
endinterface

abstract class A implements I
    abstract def string(): string
endclass

class B extends A implements I
    def string(): string
        return super.string()
    enddef
endclass

echo B.new().string()
```

I would rather see it say  
`E1373: Abstract method "string" is not implemented` here.

**Comment by errael** [comment]
Looking a **(1)**  the error is coming from a failing ISN_UFUNC. But if I disassemble there is no ISN_UFUNC. And UFUNC is for a user defined function, **not** a method. So definitely something bad going on. BTW, I took the `string()` definition out of that example; using `Xstring()` to keep builtins out of the equation.

Maybe multiple issue...

**Comment by errael** [comment]
> > In (1) I'm surprised that `abstract def _ToString(): string` in `class B` doesn't generate an error. (but I'm not sure why).
> 
> Docs are silent on the matter, but having `abstract` methods overriding instance methods supported can be useful when inherited method implementations are not good enough and _must be_ overridden elsewhere (e.g. `string()`).

I was just wondering out loud; I agree this must be permitted.

**Comment by zzzyxwvut** [comment]
For (1), after substituting `Xstring()` for every `string()`...

With patch `f958a72ab` from #15441 and `disassemble C.Xstring`:
- `1 DCALL _ToString(argc 0)` for the _inherited_ `C.Xstring()`.
- `1 DCALL _ToString(argc 0)` for the uncommented `C.Xstring()`.

With patch `4be245a76` from #15441 and `disassemble C.Xstring`:
- `1 UCALL _ToString(argc 0)` for the _inherited_ `C.Xstring()`.
- `1 DCALL _ToString(argc 0)` for the uncommented `C.Xstring()`.

Another subtle change by the newer patch.

**Comment by errael** [comment]
Thanks for that.  I was looking at
```
Error detected while processing /tmp/g.vim[35]..function <SNR>46_F[1]..<SNR>46_C.Xstring:
line    3:
E117: Unknown function: _ToString
```
and only saw the `Xstring`, not the `C` part of it. There is no explicit `C.Xstring`. I guess the compiler generates one. I was looking at the disassembly for `B.Xstring`. Doh!

**Comment by errael** [comment]
@zzzyxwvut Could you check these examples. Looks like they work now.

```
true
['B._ToString', 'A._ToString']
true
['D.string', 'C._ToString', 'B.string', 'A.string']
```

**Comment by errael** [comment]
BTW, This is the issue associated with
```
(1) abstract method overrides concrete method
```
from #15463. Are there any issues associated with that anymore?

**Comment by zzzyxwvut** [comment]
Good job!
