### ISSUE TITLE
[vim9class] Non-overridden methods with a `super` call recurse

### ISSUE THREAD

**Issue by zzzyxwvut** [vim/vim#15448]
### Steps to reproduce

The overridden methods that invoke `super` methods recurse  
when another derived type does not override the same methods  
in turn.

```
vim9script

class A
    def string(): string
        return 'A'
    enddef
endclass

class B extends A
    def string(): string
        return super.string()
    enddef
endclass

class C extends B
#### Fix it with an implementation without 'super'.
#   def string(): string
#       return 'C'
#   enddef
endclass

echo C.new().string()
```

### Expected behaviour

There is no reason for any recursion as written.

### Version of Vim

v9.1.0661

### Environment

GNU/Linux Debian (testing/trixie)

**Comment by errael** [comment]
While cleaning up #15463 I re-discovered this issue. I'm guessing the source of this issue, #15448, is in the discussion as

(2) super.method may not execute in context of defining class.

Do you agree?

**Comment by zzzyxwvut** [comment]
I agree.  In hindsight, the above example could have been  
another example, say (3), in #15449.  What made me unsure  
about its inclusion in #15449 at the time was that those two  
examples deal with `abstract` types whereas this one doesn't.  
But, as you have pointed out, the source of these failures  
may be common.
