### ISSUE TITLE
Vim Python3 plugin does not work with Python 3.13 unstable ABI

### ISSUE THREAD

**Issue by zdohnal** [vim/vim#15457]
### Steps to reproduce

0. Install python 3.13 - https://www.python.org/downloads/release/python-3130rc1/
1. ./configure --with-features=huge --enable-python3interp=dynamic --enable-gui=no
2. make
3. ./src/vim -c 'py3 print(sys.version)'

Error message is shown:
Error detected while processing command line:
E448: Could not load library function _PyObject_NextNotImplemented
E263: Sorry, this command is disabled, the Python library could not be loaded.

The mentioned function symbol was part of earlier Python3 versions, but it is not present anymore in 3.13.

### Expected behaviour

Python 3 plugin works.

### Version of Vim

9.1.660

### Environment

OS: Discovered in Fedora 41, since it includes Python 3.13 already, but it can be reproduced on any Linux system if the provided steps are followed.

**Comment by k-takata** [comment]
Does it work when you configure with the `--with-python3-stable-abi` option?

**Comment by zdohnal** [comment]
Hi @k-takata ,

unfortunately it ends with error during configure:

```
hecking --with-python3-stable-abi argument... yes
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    major_minor='yes'.split('.'); print('0x{0:X}'.format( (int(major_minor.__getitem__(0))<<24) + (int(major_minor.__getitem__(1))<<16) ))
                                                           ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'yes'
configure: error: can't parse Python 3 stable ABI version. It should be "<major>.<minor>"
```

**Comment by zdohnal** [comment]
Ok, different errors has shown up - 
[error.txt](https://github.com/user-attachments/files/16559044/error.txt) .

**Comment by k-takata** [comment]
How about with `--with-python3-stable-abi=3.8`?

**Comment by zdohnal** [comment]
Python 3.8 is long gone from Fedora - Fedora 39, the oldest stable, has Python 3.12.4. I would prefer the version which is on the machine.

If I remove the function which Vim complains about at the start, Python 3 plugin works normally as before, so maybe the function should be used for older versions?

But I'll try ABI for 3.8, out of curiosity as well.

**Comment by k-takata** [comment]
This option means that Vim uses the ABI for 3.8 regardless of the current Python version. Python 3.13 should also support 3.8 ABI.

**Comment by zdohnal** [comment]
I was able to track which stable ABI introduces the changes - Py_TYPE and Py_INCREF started to accept only PyObject pointer with 3.11, which caused the errors. However once I fixed those errors (the fix was to convert argument to PyObject*), a new linker errors appeared:

```
/usr/bin/ld: objects/if_python3.o: in function `Py_INCREF':
/usr/include/python3.13/object.h:796:(.text+0xeb8): undefined reference to `_Py_IncRef'
/usr/bin/ld: /usr/include/python3.13/object.h:796:(.text+0xed5): undefined reference to `_Py_IncRef'
/usr/bin/ld: objects/if_python3.o: in function `AlwaysFalse':
/var/tmp/tmt/run-002/default/plan/tree/vim/src/if_py_both.h:758:(.text+0xff7): undefined reference to `Py_GetConstantBorrowed'
```

which repeat through the code where the functions are called.

I'll compile Vim RPM with ABI 3.10, since it is the last stable ABI which works, but it would be great if unstable ABI and stable ABI 3.11+ was as well fixed.

Let's make this issue as report for unstable ABI, and I'll file an issue for ABI 3.11+ separately.

**Comment by zdohnal** [comment]
#15460

**Comment by k-takata** [comment]
I'm wondering if we need to follow the latest unstable ABI.
Using the stable ABI should be enough and making `--with-python3-stable-abi=3.8` the default might be okay.
(Python 3.8 is still maintained at this moment: https://en.wikipedia.org/wiki/History_of_Python#Table_of_versions)

**Comment by k-takata** [comment]
If `--with-python3-stable-abi` is not specified or if `--with-python3-stable-abi` (without argument) is specified, defaults to Stable ABI 3.8.
If `--with-python3-stable-abi=VER` is specified, set it to Stable ABI _VER_.
If `--with-python3-stable-abi=no` or `--without-python3-stable-abi` is specified, don't use Stable ABI.

```diff
--- a/src/configure.ac
+++ b/src/configure.ac
@@ -1539,12 +1539,21 @@ if test "$enable_python3interp" = "yes" 
       AC_MSG_RESULT(yep)
 
       dnl -- get the stable ABI version if passed in
+      python3_stable_abi_default=3.8
       AC_MSG_CHECKING(--with-python3-stable-abi argument)
       AC_SUBST(vi_cv_var_python3_stable_abi)
-      AC_ARG_WITH(python3-stable-abi, [  --with-python3-stable-abi=VERSION  stable ABI version to target (e.g. 3.8)],
-        vi_cv_var_python3_stable_abi="$withval"; AC_MSG_RESULT($vi_cv_var_python3_stable_abi),
-        AC_MSG_RESULT(no))
-      if test "X$vi_cv_var_python3_stable_abi" != "X"; then
+      AC_ARG_WITH(python3-stable-abi, [  --with-python3-stable-abi=VERSION  stable ABI version to target (default: 3.8)],
+        [
+	 if test "X$withval" = "Xyes"; then
+	   vi_cv_var_python3_stable_abi=$python3_stable_abi_default
+	 else
+	   vi_cv_var_python3_stable_abi="$withval"
+	 fi
+	 AC_MSG_RESULT($vi_cv_var_python3_stable_abi)],
+        [
+	 vi_cv_var_python3_stable_abi=$python3_stable_abi_default
+	 AC_MSG_RESULT(no. defaults to $python3_stable_abi_default.)])
+      if test "X$vi_cv_var_python3_stable_abi" != "Xno"; then
         AC_CACHE_VAL(vi_cv_var_python3_stable_abi_hex,
         [
          vi_cv_var_python3_stable_abi_hex=`
```

**Comment by chrisbra** [comment]
can you create a PR for that one please?

**Comment by ychin** [comment]
This issue is because of #13260, which added a dependency to a private API `_PyObject_NextNotImplemented`.

@k-takata why was `_PyObject_NextNotImplemented` added as an API? In general I think we should be careful to avoid just fixing things up for the current version of Python by pulling / duplicating whatever private APIs we can find to fix the current build issues, because we eventually run into the current situation that the next version of Python isn't obligated to respect the private API the same way. Can we remove that? If I just remove that API it would resolve this issue, but from your comment in #13260 it implies that this is a Windows-only issue?

**Comment by ychin** [comment]
FWIW (sorry for a bit of an opinion piece here), I don't understand why the problem solving process was to simply turn on stable ABI by default. It's simply sweeping the problem under the rug. This is a problem we specifically created by linking to a symbol (`_PyObject_NextNotImplemented`) rather than anything in Python itself.

**Comment by k-takata** [comment]
> why was `_PyObject_NextNotImplemented` added as an API?

No, I removed the dependency on it because it is not a part of Stable ABI.

**Comment by ychin** [comment]
> No, I removed the dependency on it because it is not a part of Stable ABI.

Oh wait you are right. Sorry about that. My Git blame was only showing one level deep at the time.

My guess is Python simply removed dependency on that private API. Let me take a look. This was added in v7.3.569 it seems which was a while ago…

**Comment by ychin** [comment]
Filed #15649 which should fix this.

**Comment by chrisbra** [comment]
Thanks!
