### ISSUE TITLE
Marker folds break when text just after its start gets cut/deleted and an undo for it occurs

### ISSUE THREAD

**Issue by yousef8192** [vim/vim#15455]
### Steps to reproduce

1. Open vim without configurations.
2. Run the following commands:
```
:set foldmethod=marker
:set foldmarker={{{,}}} 
```
3. Type the following text:
```
{{{

This is a Line

This is a Line

}}}
```
4. In visual mode select any of the following (empty lines are considered in the mentioned numbering) :
    - the first empty line directly after the start of the fold.
    - the first empty line and the second line after the fold.
    - the first 3 lines after the start of the fold.
    - the first 4 lines after the start of the fold.
    - everything inside the fold.
    - the second and third lines.
5. Delete/Cut the selection.
6. press u to undo.

### Expected behaviour

Honestly I couldn't understand what exactly makes this issue occur. However the following is noticed :

1. If a single line is selected (except for the first empty line directly after the start of the fold) the issue doesn't occur.
2. If the last two lines are selected the issue doesn't occur.
3. If we added three extra empty lines directly after the start of the fold (thus there is total 4 empty lines after the start of the fold), then applying the same steps for the same lines from before doesn't cause the issue. However it happens most of the time if one of the three extra empty lines is included within the selection.  

The issue also occurs if some editing happened after the selection was cut/deleted and a series of undos followed, in this case the fold will break in the undo responsible for the cut/deletion of the selection.

I am not sure if this issue exists with other fold methods other than marker, I didn't try them all.
If there are further information needed that I didn't provide please let me know.
Thanks a lot in advance for your time and help!

### Version of Vim

version: 9.1, patch level: 1-665

### Environment

Operating system: Linux
Terminal: Terminator
Value of $TERM: screen-256color
Shell: Bash

**Comment by chrisbra** [comment]
I don't follow. I tried `vim --clean -c ':set fdm=marker'` -c ':2' 
with a file like your example.
Then I tried:
- `:norm! Vdu`
- `:norm! Vjdu`
- `:norm! V2jdu`
- `:norm! V3jdu`
- `:norm! V4jdu`

Nothing unexpected happen. What exactly should happen?

**Comment by yousef8192** [comment]
Actually the issue doesn't happen when cutting/deleting from Visual Line mode, rather it happens when cutting/deleting in Visual mode.

By "fold break" I mean that vim doesn't recognize that fold anymore and it can't be opened/closed/toggled unless the file is reloaded or the folds are refreshed with zx.

**Comment by yousef8192** [comment]
> I don't follow. I tried `vim --clean -c ':set fdm=marker' -c ':2' ` with a file like your example. Then I tried:
> 
> * `:norm! Vdu`
> * `:norm! Vjdu`
> * `:norm! V2jdu`
> * `:norm! V3jdu`
> * `:norm! V4jdu`
> 
> Nothing unexpected happen. What exactly should happen?

Actually the issue doesn't happen when cutting/deleting from Visual Line mode, rather it happens when cutting/deleting in Visual mode.

By "fold break" I mean that vim doesn't recognize that fold anymore and it can't be opened/closed/toggled unless the file is reloaded or the folds are refreshed with zx.
