### ISSUE TITLE
htmlangular filetype no longer has syntax highlighting

### ISSUE THREAD

**Issue by Algorithmus** [vim/vim#15459]
### Steps to reproduce

Open any angular html file.
`:set filetype?` returns `htmlangular` and not `html.angular`

### Expected behaviour

File should have syntax highlighting, but there are no colors at all.

Is `htmlangular` now `html.angular`? I applied this patch and now it works.

```
diff --git a/runtime/autoload/dist/ft.vim b/runtime/autoload/dist/ft.vim
index c8942eb3d..522492953 100644
--- a/runtime/autoload/dist/ft.vim
+++ b/runtime/autoload/dist/ft.vim
@@ -418,7 +418,7 @@ export def FThtml()
   while n < 40 && n <= line("$")
     # Check for Angular
     if getline(n) =~ '@\(if\|for\|defer\|switch\)\|\*\(ngIf\|ngFor\|ngSwitch\|ngTemplateOutlet\)\|ng-template\|ng-content\|{{.*}}'
-      setf htmlangular
+      setf html.angular
       return
     endif
     # Check for XHTML
```

### Version of Vim

9.1.0611 or higher

### Environment

Artixlinux, alacritty

**Comment by chrisbra** [comment]
this part has been disabled for the reasons mentioned here: https://github.com/vim/vim/pull/13594#issuecomment-1834465890 Please try latest Vim before reporting issues.

**Comment by chrisbra** [comment]
ah oh wait, wrong I missed it.

**Comment by chrisbra** [comment]
The reason for this change it mentioned in this PR: https://github.com/vim/vim/pull/15190

**Comment by Algorithmus** [comment]
Okay, so then we should be setting filetype to `html.angular` and not `htmlangular`.

**Comment by clason** [comment]
No, that would be setting _two_ filetypes, first html and then angular, which would break external tooling. The filetype is and should be `htmlangular`. If you want syntax highlighting out of the box, contribute a simple syntax file that just sources `syntax/html.vim`.

**Comment by chrisbra** [comment]
It's mentioned in #15190 that we need to use a new filetype, because the new angular is no longer valid html.

**Comment by dlvandenberg** [comment]
I will see if I can also add specific highlighting for angular.
