### ISSUE TITLE
:for can bypass lock on variable

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#15450]
### Steps to reproduce

1. Run `vim --clean`
2. Source the following file:
```vim
const g:constvar = 10
for g:constvar in range(5)
endfor
```
3. No error is given and the value of `g:constvar` changes to 4. This also happens for Vim9 script (adding a `vim9script` line at the top).

### Expected behaviour

A `E741: Value is locked: g:constvar` error is given and the value of `g:constvar` remains 10. This was the behavior before patch 8.2.3511.
For `v:` variables this was fixed in patch 9.0.1611, but the problem still exists for locked (const) variables.

### Version of Vim

9.1.648

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

**Comment by zeertzjq** [comment]
This also happens for Vim9 script (adding a `vim9script` line at the top).

**Comment by errael** [comment]
Just to note, it behaves correctly inside a vim9script compiled function. The instruction that saves the loop variable
```
   5 STOREG g:for_constvar
```
checks for a locked variable.

```vim
vim9script

if exists('g:for_constvar')
    unlet g:for_constvar
endif
const g:for_constvar = 77

def F()
    try
        for g:for_constvar in range(3)
        endfor
    catch
        echo v:exception
    endtry
enddef
F()
echo g:for_constvar
```
