### ISSUE TITLE
Screen `escape ^Gg` produces strange chars `:0000/0000/0000`

### ISSUE THREAD

**Issue by duleorlovic** [vim/vim#15458]
### Steps to reproduce

1. Configure escape char to be CTRL+G (instead of default Ctrl+A): `echo "escape ^gg" > .screenrc`
2. Start screen session: `screen`
3. Start vim without any configuration in .vimrc: `vim`

Strange chars `:0000/0000/0000` occurs as shown

[![asciicast](https://asciinema.org/a/92AiOhrAdgOaz9BNQ8gmGPo1H.svg)](https://asciinema.org/a/92AiOhrAdgOaz9BNQ8gmGPo1H)

### Expected behaviour

It should start vim normally, without `:0000/0000/0000`.
When I run `vim -u NONE` the issue does not happen.
Also, it does not happen when I use some other screen escape char eg `escape ^ff`.
 
It would be nice if there is something I can put in `.vimrc` to prevent this issue with `escape ^gg`.

### Version of Vim

8.1, 8.2, 9.0

### Environment

Ubuntu under screen session.
```
echo $TERM
screen.xterm-256color
```

**Comment by zeertzjq** [comment]
What terminal is screen running inside?

**Comment by duleorlovic** [comment]
> What terminal emulator is screen running in?

It is `term-256color`

**Comment by zeertzjq** [comment]
I think you are using GNOME terminal, and I can reproduce this issue using it. It seems that putting
```vim
set t_RB=
```
in your vimrc will solve this problem.

**Comment by chrisbra** [comment]
Issue with your terminal, claiming to be xterm compatible, when it really isn't.
