### ISSUE TITLE
argdelete throws for empty argument list

### ISSUE THREAD

**Issue by pavoljuhas** [vim/vim#1546]
Using vim 8.0.329:

```
$ vim -N -u NONE -i NONE
:argdelete *
E480: No match: *

:%argdelete
E474: Invalid argument
```

I feel the raised errors are unnecessary as in both cases the intent is to clear the argument list.  It would be useful to let that work regardless if the initial argument list is empty or not.

**Comment by brammool** [comment]
Pavol Juhas wrote:

> Using vim 8.0.329:
> 
> ```
> $ vim -N -u NONE -i NONE
> :argdelete *
> E480: No match: *
> 
> :%argdelete
> E474: Invalid argument
> ```
> 
> I feel the raised errors are unnecessary as in both cases the intent
> is to clear the argument list.  It would be useful to let that work
> regardless if the initial argument list is empty or not.

If you want to clear the argument list use :%argdelete.  I agree that
there is no point in giving an error when it's already empty.  And the
error is confusing anyway.

I think it's appropriate that when a pattern does not match you get an
error message.

-- 
From "know your smileys":
 ...---...   SOS

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
