### ISSUE TITLE
VIm doesn't compile with --with-python3-stable-abi=3.11 and newer

### ISSUE THREAD

**Issue by zdohnal** [vim/vim#15460]
### Steps to reproduce

(the same happens with --with-python3-stable-abi=3.12 and --with-python3-stable-abi=3.13)
1. ./configure --with-features=huge --enable-python3interp=dynamic --enable-gui=no --with-python3-stable-abi=3.11
2. make

[error.txt](https://github.com/user-attachments/files/16560230/error.txt)

The errors can be fixed by converting the argument to PyObject*, however then linker errors shows up - 
[linker-error.txt](https://github.com/user-attachments/files/16560244/linker-error.txt)

### Expected behaviour

Vim compiles with the latest Python stable ABI

### Version of Vim

9.1.660

### Environment

OS Fedora 41, but IMO effective on any OS with the mentioned Python and VIm versions

**Comment by chrisbra** [comment]
Hm, cannot reproduce. I see a few warnings with `./configure --with-features=huge --enable-python3interp=dynamic` and `./configure --with-features=hug --with-python3-stable-abi=3.12` (both of them seem to be the similar). But those are just warnings, no errors. Anyways, this patch seems to fix it:
```diff
diff --git a/src/if_py_both.h b/src/if_py_both.h
index d09b14c75..7258ddd47 100644
--- a/src/if_py_both.h
+++ b/src/if_py_both.h
@@ -3083,7 +3083,7 @@ ListConcatInPlace(ListObject *self, PyObject *obj)
     }
     Py_DECREF(lookup_dict);

-    Py_INCREF(self);
+    Py_INCREF((PyObject *)self);
     return (PyObject *)(self);
 }

@@ -4012,7 +4012,7 @@ TabPageNew(tabpage_T *tab)
     if (TAB_PYTHON_REF(tab))
     {
        self = TAB_PYTHON_REF(tab);
-       Py_INCREF(self);
+       Py_INCREF((PyObject *)self);
     }
     else
     {
@@ -4206,7 +4206,7 @@ WindowNew(win_T *win, tabpage_T *tab)
     if (WIN_PYTHON_REF(win))
     {
        self = WIN_PYTHON_REF(win);
-       Py_INCREF(self);
+       Py_INCREF((PyObject *)self);
     }
     else
     {
@@ -4334,7 +4334,7 @@ WindowAttr(WindowObject *self, char *name)
     }
     else if (strcmp(name, "tabpage") == 0)
     {
-       Py_INCREF(self->tabObject);
+       Py_INCREF((PyObject *)self->tabObject);
        return (PyObject *)(self->tabObject);
     }
     else if (strcmp(name, "__members__") == 0)
@@ -4488,7 +4488,7 @@ WinListNew(TabPageObject *tabObject)

     self = PyObject_NEW(WinListObject, WinListTypePtr);
     self->tabObject = tabObject;
-    Py_INCREF(tabObject);
+    Py_INCREF((PyObject *)tabObject);

     return (PyObject *)(self);
 }
@@ -5383,7 +5383,7 @@ RangeNew(buf_T *buf, PyInt start, PyInt end)
        Py_DECREF(self);
        return NULL;
     }
-    Py_INCREF(bufr);
+    Py_INCREF((PyObject*)bufr);

     self->buf = bufr;
     self->start = start;
@@ -5512,7 +5512,7 @@ BufferNew(buf_T *buf)
     if (BUF_PYTHON_REF(buf) != NULL)
     {
        self = BUF_PYTHON_REF(buf);
-       Py_INCREF(self);
+       Py_INCREF((PyObject *)self);
     }
     else
     {
diff --git a/src/if_python3.c b/src/if_python3.c
index 96c949771..47ecc0c8e 100644
--- a/src/if_python3.c
+++ b/src/if_python3.c
@@ -1079,7 +1079,7 @@ static int python_end_called = FALSE;

 #ifdef USE_LIMITED_API
 # define DESTRUCTOR_FINISH(self) \
-    ((freefunc)PyType_GetSlot(Py_TYPE(self), Py_tp_free))((PyObject*)self)
+    ((freefunc)PyType_GetSlot(Py_TYPE((PyObject*)self), Py_tp_free))((PyObject*)self)
 #else
 # define DESTRUCTOR_FINISH(self) Py_TYPE(self)->tp_free((PyObject*)self)
 #endif
```

I only have python3.12.4 on debian testing and python3.13 has not yet been released yet, so did not test. Anyhow, can you show the complete log please?

**Comment by k-takata** [comment]
@chrisbra 
It seems that your patch is not enough when `--enable-python3interp=dynamic --with-python3-stable-abi=3.12`.
Here is the updated patch:
https://gist.github.com/k-takata/79ae97339898ee12cc012ace1ec7922e
(I tested only on Windows with Python 3.12.)

> But those are just warnings, no errors.

They might be matter if `-Werror` is used.

**Comment by chrisbra** [comment]
Thanks, let me include this.
