### ISSUE TITLE
Gvim application grouping under Gnome

### ISSUE THREAD

**Issue by martinoischia** [vim/vim#15461]
### Steps to reproduce

Build Gvim under GTK3. 
`./configure --with-features=huge --enable-gui=auto`
`make`
Using Gnome.

### Expected behaviour

Hello dears! First time here, I'm reporting this bug, I wanted to try fix it myself but as I did a bit of research it is getting more complicated than expected...

So I have built Gvim, it says it used GTK3. Gnome groups multiple instances of the same application under a  single group, so that alt-tab show only the groups, and alt ` scrolls along a single group. Multiple Gvims aren't grouped together. _edit_: not just on Wayland, also on xorg

Doing a bit of research I have found out: by default, Gvim runs under XWayland. The same effect I have found out by using the (unfinished) pure Wayland implementation, by exporting GVIM_ENABLE_WAYLAND (by the way, I have noticed that this variant gives an icon in the alt tab menu that is not the classic gvim icon, but a vim-unrelated one, I believe).
Now I assume I am right in claiming that this is a bug, I have compared a couple of apps I have found on my system: 
- firefox, also running XWayland, in this case the multiple windows are spawned under the same process;
- drracket, in this case he would like to keep only one window due to some single instance setting, but launching another process in the background from the terminal still opens me a new window and it is grouped properly. (In this case it is running under pure Wayland).
So I would say that we need a fix for this in both handling the XWayland default case, and the (still under development) Wayland case.
Thanks for the support ;)

### Version of Vim

9.1 (2024 Jan 02, compiled Jul 29 2024 21:20:07) Included patches: 1-636 

### Environment

Debian 12, _edit_, sorry:Gnome 43.9

**Comment by martinoischia** [comment]
As of patch 1-954, it is working as expected! Thanks to whatever fixed that :)

**Comment by chrisbra** [comment]
That is ... surprising. Thre was no patch, that attempted to fix this behaviour.

**Comment by martinoischia** [comment]
But I can confirm! On this branch (v9.1.0636) I have the issue (after uninstalling the new branch, otherwise it is bundled correctly with new gvim applications), on the new not.. on the old gvim, when I alt tab, I see the png icon, on the new one I see the svg (but checking the artifacts I see the svg file is there also in the old version). Anyway, if you want me dig further, I could spend some time on it, with like a git bisect ;)

**Comment by chrisbra** [comment]
no worries. Let's assume this is fixed and if you notice an issue, create a new issue please.
