### ISSUE TITLE
Setting `'commentstring'` resets the "remembered" column

### ISSUE THREAD

**Issue by sodapopcan** [vim/vim#15462]
### Steps to reproduce

With the following buffer:

```
1 here
2   is
3     s\%#ome
4
5     more
6   indented
7 text
```

with `\%#` being your cursor, move it up and down works as expected, remembering the column.  Now move your cursor to line 4 and issue `:setlocal commentstring=#\ %s`.  The cursor is now glued to column 1.

Apologies if this is intended behaviour but I couldn't find an issue about it.

Here's a video:

https://github.com/user-attachments/assets/61798724-263d-4e54-b48d-144bfe632a3a

### Expected behaviour

It remembers the cursor column after setting `'commentstring'`.

Thank you all for your continued work on Vim.  It's much appreciated!

### Version of Vim

9.1, included patches 1-500

### Environment

MacOS
Kitty
xterm-kitty
zsh

**Comment by chrisbra** [comment]
cannot reproduce. Does it happen with `vim --clean`?

**Comment by sodapopcan** [comment]
Hi Christian, thanks for your response!

It still happens for me with `vim --clean`.  I tested using `vim -N`/`vim -u NONE` as well as with and without the somewhat common settings of `compatible`, `syntax on`, and `filetype indent on` (as well as my own massive vimrc, of course).

**Comment by chrisbra** [comment]
can you please show the output of `vim --version`?

**Comment by sodapopcan** [comment]
```
VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Jun 18 2024 19:01:23)
macOS version - arm64
Included patches: 1-500
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
-balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +gettext           +num64             +textobjects
-browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     +perl              +title
+channel           +ipv6              +persistent_undo   -toolbar
+cindent           +job               +popupwin          +user_commands
-clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           -python            +viminfo
+cmdline_info      +libcall           +python3           +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
+cscope            +localmap          +ruby              +wildignore
+cursorbind        +lua               +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con        +mksession         +smartindent       +writebackup
+diff              +modify_fname      +sodium            -X11
+digraphs          +mouse             +sound             -xattr
-dnd               -mouseshape        +spell             -xfontset
-ebcdic            +mouse_dec         +startuptime       -xim
+emacs_tags        -mouse_gpm         +statusline        -xpm
+eval              -mouse_jsbterm     -sun_workshop      -xsmp
+ex_extra          +mouse_netterm     +syntax            -xterm_clipboard
+extra_search      +mouse_sgr         +tag_binary        -xterm_save
-farsi             -mouse_sysmouse    -tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
 3rd user vimrc file: "~/.config/vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/opt/homebrew/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DMACOS_X -DMACOS_X_DARWIN -g -O2 -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: clang -o vim -lm -lncurses -lsodium -liconv -lintl -framework AppKit -L/opt/homebrew/opt/lua/lib -llua5.4 -mmacosx-version-min=14.2 -fstack-protector-strong -L/opt/homebrew/opt/perl/lib/perl5/5.38/darwin-thread-multi-2level/CORE -lperl -L/opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/lib/python3.12/config-3.12-darwin -lpython3.12 -framework CoreFoundation -lruby.3.3 -L/opt/homebrew/Cellar/ruby/3.3.3/lib
```

**Comment by chrisbra** [comment]
do you use some commone filetype for your example file?

**Comment by sodapopcan** [comment]
Filetype was actually unset for the video I made and the tests I did beforehand, though I noticed it in an Elixir file.  I just tried a few others (javascript, ruby, c) with the same result.

My use case is that Elixir has embedded html (akin to JSX) so I want to be able to set `commentstring` on `CursorHold`.  So long as I move quick enough it's fine, but I happened to stop on a blank line several times and noticed it.

**Comment by sodapopcan** [comment]
I just tried in Terminal.app instead of Kitty (with `vim -u NONE`) and still see the issue.

**Comment by chrisbra** [comment]
Hm, just to be sure, was the auto command active while you tested?

**Comment by sodapopcan** [comment]
When I first noticed yes, but all additional testing was done with `vim -N`/`vim --clean` etc with no more than the settings I mentioned above (and without).  I even dowloaded nvim and tried there and still happens 😅  Must be an OS things?

**Comment by chrisbra** [comment]
I doubt it, but I have no idea. weird

**Comment by sodapopcan** [comment]
Ya, for sure.  I just ssh'd to a Linux vm on AWS and same thing.  Just to be extra clear (though I'm sure you know), it specifically happens when your cursor is on a blank line.  Obviously this isn't a high-priority issue, though,  so thank you for your engagement on it.

**Comment by sodapopcan** [comment]
Just adding, it's actually happening to me any time I call `:set` anything.  Sorry for not thinking to try that before.

**Comment by zeertzjq** [comment]
Does it still happen if you apply this patch?
```diff
diff --git a/src/optiondefs.h b/src/optiondefs.h
index b5446193d..01c8c71a4 100644
--- a/src/optiondefs.h
+++ b/src/optiondefs.h
@@ -627,7 +627,7 @@ static struct vimoption options[] =
 			    {(char_u *)"s1:/*,mb:*,ex:*/,://,b:#,:%,:XCOMM,n:>,fb:-",
 				(char_u *)0L}
 			    SCTX_INIT},
-    {"commentstring", "cms", P_STRING|P_ALLOCED|P_VI_DEF|P_CURSWANT,
+    {"commentstring", "cms", P_STRING|P_ALLOCED|P_VI_DEF,
 #ifdef FEAT_FOLDING
 			    (char_u *)&p_cms, PV_CMS, did_set_commentstring, NULL,
 			    {(char_u *)"/* %s */", (char_u *)0L}
```

**Comment by sodapopcan** [comment]
Assuming I did this right, it does!

--------

As a homebrew-using web developer, this is actually the first time I've ever built Vim from source so thanks for the opportunity to push myself out of my comfort zone... not that typing `make` was too hard, lol.

**Comment by sodapopcan** [comment]
Oh man, I'm so sorry, I misread the phrasing of your message, I meant that it does solve the problem!!

**Comment by zeertzjq** [comment]
I almost forgot what my question was if you didn't remind me :)

**Comment by sodapopcan** [comment]
Ha!  Fair enough :)

Thanks again to you both for your attention to this issue and to all involved in keeping this project alive <3
