### ISSUE TITLE
comment in ex command in mapping

### ISSUE THREAD

**Issue by bounceme** [vim/vim#1547]
consider this map:
`nnoremap <Leader>cp :let @* = expand("%")"<cr>`
Maybe this is intentional, but should this work?:
`nnoremap <lEADER>cp :let @* = expand("%")"<cr> asdasdasdasd`

**Comment by chrisbra** [comment]
I am not sure I understand the question. I think this is intentional and documented at `:h map-comments` Please ask user questions on the mailinglist or vi.stackexchange.com

**Comment by bounceme** [comment]
try this one: `nnoremap <lEADER>cp :let @* = expand("%")"<cr> asdasdasdasd`

does seem a little strange to me

**Comment by bounceme** [comment]
and then this doesn't work? `map lkj :echom 1 "<cr>`

**Comment by bounceme** [comment]
oh, sorry, that is normal
