### ISSUE TITLE
Incorrect syntax highlighting for debsources files in deb822 format

### ISSUE THREAD

**Issue by 4wk-** [vim/vim#15492]
### Steps to reproduce

1. Open default `/etc/apt/sources.list.d/debian.sources` file after a standard Debian 12 (Bookworm) installation
2. Notice `deb` being colored even in a path (it shouldn't be)

![Wrong syntax highlighting](https://github.com/user-attachments/assets/233cdf77-0236-4643-be3f-1ce45f54ad24)

Starting with Bookworm, it's recommended to write apt sources file in `deb822` format.
- https://manpages.debian.org/bookworm/apt/sources.list.5.en.html#DEB822-STYLE_FORMAT
- https://repolib.readthedocs.io/en/latest/deb822-format.html (RepoLib is Python-related, but I think it's still interesting)

### Expected behaviour

`deb` keyword should be colored only when it is a "word", not if it's part of a path.

### Version of Vim

9.0

### Environment

```
Debian 12.6
Windows Terminal
xterm-256color
Bash 5.2.15(1)-release
```

**Comment by chrisbra** [comment]
This should go to the upstream maintainer. ping @jamessan

**Comment by jamessan** [comment]
Already fixed by https://github.com/vim/vim/pull/14098.

**Comment by chrisbra** [comment]
closing then.

**Comment by 4wk-** [comment]
I did use the search function before posting, sorry I didn't find it. Thank you for the fix!
