### ISSUE TITLE
Zip plugin does not handle inner file name contain glob character

### ISSUE THREAD

**Issue by user202729** [vim/vim#15505]
### Steps to reproduce

1. Create a zip file `a.zip` using the following bash commands

```bash
rm a.zip
echo 123 > "[a].txt"
zip a.zip "[a].txt"
```

alternatively download at [a.zip](https://github.com/user-attachments/files/16632182/a.zip)

2. open the zip file in vim, make sure zip.vim plugin is enabled

```
" zip.vim version v33
" Browsing zipfile /tmp/a.zip
" Select a file with cursor and press ENTER

[a].txt
```

3. try to open the text file
4. see empty file

### Expected behaviour

should see the text ("123") instead

### Version of Vim

9.1.648

### Environment

Linux

--------

Reposting https://github.com/vim/vim/issues/15445 . 

Suggested patch (works on my machine (Linux), not sure about Windows and Mac/other operating systems)

```diff
--- a/runtime/autoload/zip.vim
+++ b/runtime/autoload/zip.vim
@@ -234,7 +234,7 @@ fun! zip#Read(fname,mode)
   " but allows zipfile://... entries in quickfix lists
   let temp = tempname()
   let fn   = expand('%:p')
-  exe "sil! !".g:zip_unzipcmd." -p -- ".s:Escape(zipfile,1)." ".s:Escape(fname,1).' > '.temp
+  exe "sil! !".g:zip_unzipcmd." -p -- ".s:Escape(zipfile,1)." ".s:Escape(escape(fname, '\?*[]'),1).' > '.temp
   sil exe 'keepalt file '.temp
   sil keepj e!
   sil exe 'keepalt file '.fnameescape(fn)
```

**Comment by zeertzjq** [comment]
Please test with the latest commit.

**Comment by chrisbra** [comment]
Thanks for being persistent with this issue.

Now I see. It's an error for the 'zip#Extract' function, becaues one needs to escape the '[' in a filename by '[[]' according to the manpage of the unzip command. I have created #15519 for this and a few other minor issues I found. Can you please verify?

**Comment by user202729** [comment]
@chrisbra In my testing you also need to escape `\`, `?` and `*`. Although these 3 characters are illegal in Windows, so it might be hard to test if you're on Windows.

Here's a test file.
[a.zip](https://github.com/user-attachments/files/16646954/a.zip)

The expected content should be
```
a[a].txt:file with square bracket
aa.txt:file named aa
a*.txt:file with star
a?.txt:file with question mark
a\.txt:file with backslash
a\\.txt:file with double backslash
```

------


Okay, I see the glob behavior is documented in the manpage --- good to know (then it should be portable).

----------

Maybe you should update "Date", "Version", "Last Change" at the top of the file too.

--------

I tested the change, it works with the square bracket, but the star, question mark and backslash still give unexpected behavior.
