### ISSUE TITLE
Using a skeleton file with `autocmd BufNewFile` and then calling `*CTRL-^* *CTRL-6*` open skeleton file in a new buffer

### ISSUE THREAD

**Issue by epilys** [vim/vim#15513]
### Steps to reproduce

First, configure an `autocmd` that uses a skeleton template file when opening a file that matches a specific glob:

```vim
if has("autocmd")
  augroup templates
    autocmd BufNewFile *.myformat 0r /tmp/skeleton.myformat
  augroup END
endif
```

Reload the configuration. Then open a new file that matches that glob, e.g. `_.myformat`. This will autopopulate the buffer with the contents of `/tmp/skeleton.myformat` as expected. If you at any point use the "go to previous buffer" shortcut, `C-^`, **without** first switching to another buffer manually (by name or number), a new buffer will be made visible, that of the skeleton file.

### Expected behaviour

Skeleton file should not ever appear in the buffer list.

### Version of Vim

9.1.496

### Environment

Debian trixie/testing

**Comment by chrisbra** [comment]
That is intentionally. See `:h cpo-a`
