### ISSUE TITLE
Completion is performed upon pressing enter even though nothing has been selected

### ISSUE THREAD

**Issue by Futarimiti** [vim/vim#15526]
### Steps to reproduce

1. Write the following into a txt file
```
vim:cot=fuzzy,menuone,noselect,noinsert
Text
ToText
```
2. Edit the file with `vim --clean`, then start a newline at the bottom and insert `Te`
```
vim:cot=fuzzy,menuone,noselect,noinsert
Text
ToText
Te|
```
3. Still in insert mode, press `<C-N>`. A menu should popup with option `Text` and `ToText` but neither should be selected.
4. Type `x`. Popup menu should be visible still with no entry selected.
5. Press `<CR>`. This would produce a newline and `ToText` should be completed nevertheless.

### Expected behaviour

Completion should not be done as no entry has been selected, leaving `Tex` on the last line.

### Version of Vim

9.1

### Environment

macOS Sonoma 14.4.1, iTerm2 3.5.2, `xterm-256color`, zsh 5.9

**Comment by zeertzjq** [comment]
> 9.1

What's the "Included patches" line in `:version`?

**Comment by Futarimiti** [comment]
1-650

**Comment by habamax** [comment]
@glepnir maybe?

**Comment by glepnir** [comment]
I dont think expect behavior is correct press x then CR  even no fuzzy the vim behavior is not insert newline.

**Comment by Futarimiti** [comment]
> I dont think expect behavior is correct press x then CR even no fuzzy the vim behavior is not insert newline.

You're right, edited
