### ISSUE TITLE
make install does not install .desktop files by default on Ubuntu

### ISSUE THREAD

**Issue by jmdevin** [vim/vim#15528]
### Steps to reproduce

1. `make` and `make install` vim on Ubuntu 24.04
2. See that the `vim.desktop` and `gvim.desktop` files are not installed in `/usr/share/applications/`, or elsewhere

### Expected behaviour

I'm not sure that this is a bug, or just unsupported; however, installing after doing `./configure --prefix="$HOME/.local/"` _does_ install .desktop files in `$HOME/.local/share/applications` with no other configuration, so I believe installing them is expected.

This has actually been in the `todo.txt` file for a while: ([link](https://github.com/vim/vim/blob/3840d2feaf1454c934f71a97aae7a56a5ceccef9/runtime/doc/todo.txt#L1493)):

> Installation of .desktop files does not work everywhere.
It's now fixed, but the target directory probably isn't right.
Add configure check?
Should use /usr/local/share/applications or /usr/share/applications.
Or use $XDG_DATA_DIRS.
Also need to run update-desktop-database (Kuriyama Kazunobu, 2015 Nov 4)

It seems `make install` only checks for `/usr/local/share/applications` and not `/usr/share/applications`. Ubuntu 24.04 doesn't have `/usr/local/share/applications`, so the .desktop files aren't installed (I did upgrade from 20.04 though, so if a fresh install is different I'll close this).

### Version of Vim

9.1.0682

### Environment

OS: Ubuntu 24.04

**Comment by chrisbra** [comment]
So the question is, if you create a directory `/usr/local/share/applications/` and copy the gvim.desktop files into it, does your desktop environment pick it up from there or not? If applications do not bother to look into `/usr/local/share/applications` for those desktop files, then it does not make sense to install those desktop files there, no?

**Comment by chrisbra** [comment]
Ah, I see the issue. `$DESTDIR` is usually not defined and as such the directory is not created. Can you try the following patch please?

```diff
diff --git a/src/Makefile b/src/Makefile
index 2da0c6f4a..a23d9822c 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -2624,7 +2624,7 @@ ICONTHEMEPATH = $(DATADIR)/icons/hicolor
 DESKTOPPATH = $(DESTDIR)$(DATADIR)/applications
 KDEPATH = $(HOME)/.kde/share/icons
 install-icons:
-       if test -n "$(DESTDIR)"; then \
+       if test -n "$(DESTDIR)$(DATADIR)"; then \
                $(MKDIR_P) $(ICON48PATH) $(ICON32PATH) \
                $(ICON16PATH) $(DESKTOPPATH); \
        fi
```

**Comment by jmdevin** [comment]
Just tried it; it works.

**Comment by chrisbra** [comment]
thanks, created #15546 to fix this
