### ISSUE TITLE
Broken mapping in man.vim ftplugin

### ISSUE THREAD

**Issue by jmdevin** [vim/vim#15538]
### Steps to reproduce

There's a mapping in the man.vim ftplugin ([link](https://github.com/vim/vim/blob/7790ea0c680a9f951a86066e5940ec16b2333c9a/runtime/ftplugin/man.vim#L39)) that looks like this:
```vim
nnoremap <buffer> <Plug>ManBS :%s/.\b//g<CR>:setl nomod<CR>''
```
For your convenience, I'll summarize: it finds any single character followed by a backspace and removes them both, then sets the buffer to `nomodified`.

The problem is, a buffer with a filetype `man` is set to `nomodifiable` by default, so if use it all that happens is `E21: Cannot make changes, 'modifiable' is off`.

### Expected behaviour

That's an easy fix, and I'll make the pull request if that's all, but I wanted to check: is this mapping useful? Should `man.vim` just be removing backspaces anyway? I don't understand why this is manual, but I know that because my understanding is limited.

### Version of Vim

9.1.0682

### Environment

Ubuntu 24.04

**Comment by jmdevin** [comment]
Thanks @saccarosium, but just to be clear, @chrisbra, did you want the mapping fixed or removed? I couldn't tell

**Comment by chrisbra** [comment]
no, I would like to have the mapping fixed. Don't want to remove it, as some users may rely on it. Thanks

**Comment by saccarosium** [comment]
Ops, I misunderstood.

**Comment by saccarosium** [comment]
Ok should be done

**Comment by jmdevin** [comment]
I added a comment for review.

**Comment by chrisbra** [comment]
What comment?

**Comment by zzzyxwvut** [comment]
Curiously, both the automatic [filtering out of backspaces](https://man7.org/linux/man-pages/man1/col.1.html#OPTIONS)  
with `col -b`:

https://github.com/vim/vim/blob/cacb6693c10bb19f28a50eca47bc4bc33eccbae3/runtime/autoload/dist/man.vim#L212-L214

and the manual command `ManBS` have been available from at  
least [`vim-6-0i`](https://github.com/vim/vim-history/blob/vim-6-0i/runtime/ftplugin/man/default.vim) (Oct 2000).

Despite the effect of `col -b` (or its emulation), the syntax  
file for `man.vim` has been taking pains to recognise  
(absent?) backspaces:

https://github.com/vim/vim/blob/cacb6693c10bb19f28a50eca47bc4bc33eccbae3/runtime/syntax/man.vim#L18-L19

https://github.com/vim/vim/blob/cacb6693c10bb19f28a50eca47bc4bc33eccbae3/runtime/syntax/ctrlh.vim#L9-L16

**Comment by jmdevin** [comment]
@chrisbra I added it onto the pull request itself: #15547. Sorry, not totally familiar with the best workflow to contribute

**Comment by chrisbra** [comment]
I don't see any comment in #15547 ? What happened for me in the past was, that I added review comments on PRs, but never pushed the "submit" review button, so they were never seen for other people. Check if your comment is marked as pending or similar.

**Comment by chrisbra** [comment]
@zzzyxwvut interesting, so you are trying to say, since we are filtering out the backspaces, we can skip sourcing the `ctrlh.vim` syntax script?

**Comment by jmdevin** [comment]
🤦🏼 yep, that was it. It should appear now

**Comment by zzzyxwvut** [comment]
@chrisbra.

Well, with `col -b`, it is possible to run into some kind of  
failure (not installed, not found in `PATH`, etc.), but the  
error message is all you get from the pipe.

But then you can just run `:r !man ls` and _then_ load the  
plugin, but as I recall it from #12301, `col -b ...` will be  
invoked on behalf of `man` itself (you should be able to  
verify it with `strace`, see in that [issue](https://github.com/vim/vim/issues/12301#issuecomment-1528953852)).

So, I imagine, there can be a case when you _need_ to load 
a `*roff` file and then by hand repeat what `man` does out  
of box.  I guess only then both the syntax support and the  
command are indeed valuable. (I haven't done it myself.)

**Comment by zzzyxwvut** [comment]
Yep, with Vim launched in one terminal and Strace invoked in  
another terminal as follows:

```shell
mkdir /tmp/traces
strace -q -v -ff -tt -y -s 1024 -o /tmp/traces/vim -p $(pgrep --newest vim)
```

after executing `:r !man ls`, followed by `:q!`, and some  
further massaging:

```shell
cd /tmp/traces
strace-log-merge vim > vim.cat
strace-graph vim.cat
```

`col -b -p -x` can be discovered:

```
 [1.07] 27637-4736.281809 (anon)
  `-- [0.10] 27644-4737.966683 bash(/bin/bash) -c (man ls)>/tmp/v8UUCbb/0 2>&1
       `-- [0.09] 27645-4737.986156 man ls
            +-- [0.00] 27646-4738.118236 (anon)
            +-- [0.02] 27647-4738.130915 (anon)
            |    `-- [0.01] 27652-4738.161715 (anon)
            +-- [0.02] 27648-4738.131858 (anon)
            |    `-- [0.01] 27653-4738.162252 (anon)
            +-- [0.02] 27649-4738.133261 preconv -e UTF-8
            +-- [0.02] 27650-4738.13665 tbl
            +-- [0.04] 27651-4738.154619 nroff -mandoc -rLL=69n -rLT=69n -Tutf8
            |    `-- [0.03] 27656-4738.206984 groff -Tutf8 -mtty-char -mandoc -rLL=69n -rLT=69n
            |         +-- [0.02] 27657-4738.216122 troff -mtty-char -mandoc -rLL=69n -rLT=69n -Tutf8
            |         `-- [0.02] 27658-4738.216663 grotty
            +-- [0.04] 27654-4738.163707 col -b -p -x
            `-- [0.04] 27655-4738.16702 (anon)
```
