### ISSUE TITLE
[vim9class] naming methods in non PascalCase 

### ISSUE THREAD

**Issue by saccarosium** [vim/vim#15548]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

Currently it is impossible to name methods in non pascal case.

**Describe the solution you'd like**

While I don't mind this naming convention for functions and classes, I really can't stand it for methods. Since the main reason PascalCase is enforced is so names do clashes with internal ones (#14873) and methods are already namespaced by the class. I think that it is no much point in enforce it.

**Comment by zzzyxwvut** [comment]
It will be challenging to maintain your own `class`es etc.  
with non-`PascalCased` methods:

* Class methods (aka `static`) do not require qualification  
  in instance methods of their own type, e.g.

    ```
    vim9script

    class Name
        const name: string

        def new(this.name)
        enddef

        def string(): string
            # Clash with :help id().
            return Id(this.name)
        enddef

        static def Id(name: string): string
            return str2list(name, 1)->join('.')
        enddef
    endclass

    echo Name.new('hello')
    ```

  Now, to avoid clashes with current or future Vim functions,  
  you will have to either qualify each class method _or_ pick   
  `camelCased` names and hope no new `hlID()`, `synID()` and  
  friends, will be introduced.

* Methods not supported now as `:help builtin-object-methods`  
  may qualify later, provided their signatures match, e.g.

    ```
    vim9script

    class Name
        const name: string

        def new(this.name)
        enddef

        # Potentially override :help simplify().
        def Simplify(pattern: string): string
            return matchstr(this.name, pattern)
        enddef
    endclass

    echo Name.new('hello').Simplify('....$')
    ```

  Again, to avoid the same name-and-signature clashes, you  
  will have to invent some common prefix (likely the type  
  name) for all (?) instance methods.

**Comment by chrisbra** [comment]
I don't intend to change this.
