### ISSUE TITLE
dict_add_list and dict_add_dict may free dictionaries they do not own

### ISSUE THREAD

**Issue by ZyX-I** [vim/vim#1555]
Both these functions populate newly allocated dictionary item with list or dictionary, without incrementing reference count before actually adding this new item to a dictionary. Then, if addition fails, `dictitem_free` cares about decrementing reference count which was not incremented. So, something like

    d = dict_alloc();
    l = list_alloc();
    dict_add_list(d, "test", l);
    dict_add_list(d, "test", l);
    dict_add_list(d, "test", l);

will successfully crash Vim: first `dict_add_list` will set reference count to 1, second will fail and decrement it to zero and free list even though list is still referenced and third will crash Vim (as well as any access to the list inside `d`) because list was already freed.

The issue does not cause any bugs because I do not actually see a case where `dict_add_{list,dict}` may fail to add a new key: they are used to populate dictionaries created a few lines before and `if (dict_add(…) == FAIL)` may as well be `assert(dict_add(…) != FAIL)` (well, with some adjustments to the case when asserts are disabled). I found it only because I am creating unit tests for various functions originating from eval.c.

**Comment by brammool** [comment]
Nikolai Pavlov wrote:

> Both these functions populate newly allocated dictionary item with
> list or dictionary, without incrementing reference count before
> actually adding this new item to a dictionary. Then, if addition
> fails, `dictitem_free` cares about decrementing reference count which
> was not incremented. So, something like
> 
>     d = dict_alloc();
>     l = list_alloc();
>     dict_add_list(d, "test", l);
>     dict_add_list(d, "test", l);
>     dict_add_list(d, "test", l);
> 
> will successfully crash Vim: first `dict_add_list` will set reference
> count to 1, second will fail and decrement it to zero and free list
> even though list is still referenced and third will crash Vim (as well
> as any access to the list inside `d`) because list was already freed.
> 
> The issue does not cause any bugs because I do not actually see a case
> where `dict_add_{list,dict}` may fail to add a new key: they are used
> to populate dictionaries created a few lines before and `if
> (dict_add(…) == FAIL)` may as well be `assert(dict_add(…) != FAIL)`
> (well, with some adjustments to the case when asserts are disabled). I
> found it only because I am creating unit tests for various functions
> originating from eval.c.

I suppose this could become a real problem if someone uses the functions
in another way.  Do you have a suggestion how to fix it?

-- 
An actual excerpt from a classified section of a city newspaper:
"Illiterate?  Write today for free help!"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ZyX-I** [comment]
I simply moved the reference counting increment before the `if…==FAIL`.
