### ISSUE TITLE
Problem with color when using eza tool in gVim terminal in Windows.

### ISSUE THREAD

**Issue by TayTTo** [vim/vim#15553]
### Steps to reproduce

1. Install the tool eza for better listing file in Windows PowerShell.
2. When type eza in gVim terminal, it shows the ANSI color code insteadof the color.
![image](https://github.com/user-attachments/assets/5c8c346c-59ba-43c4-85fa-08b033e1a4ac)
3. In the normal terminal, it looks like this.
![image](https://github.com/user-attachments/assets/099e35a5-148d-4796-9454-43a384ec60c9)

### Expected behaviour

I think when I use eza tool it should show the right color not the ANSI code.

### Version of Vim

9.1.682

### Environment

Operating system: Windows 11 Pro 23H2
terminal: pwsh 7.4.5

**Comment by k-takata** [comment]
Do you use winpty or conpty? (See `:help 'termwintype'`)

**Comment by TayTTo** [comment]
@k-takata what are they, I don't understannd.

**Comment by k-takata** [comment]
Refer the help here:
https://github.com/vim/vim/blob/4a0dc29e5fb4f59712f6f336b88bf1f18d846858/runtime/doc/options.txt#L8471-L8488

Also you can try `:term ++type=conpty` and `:term ++type=winpty` when opening a terminal. (See `:help :terminal` for detail.)
https://github.com/vim/vim/blob/4a0dc29e5fb4f59712f6f336b88bf1f18d846858/runtime/doc/terminal.txt#L191-L192
https://github.com/vim/vim/blob/4a0dc29e5fb4f59712f6f336b88bf1f18d846858/runtime/doc/terminal.txt#L270-L272

**Comment by chrisbra** [comment]
As mentioned before, I don't think this is supported. The proper way is to configure the eza tool to not output ANSI escape sequences

**Comment by TayTTo** [comment]
@chrisbra oh wow, you saw my post on Reddit :))).

**Comment by TayTTo** [comment]
@chrisbra, have you try to solve the problem, I saw some guys don't have the problem with older version of Vim.
https://github.com/eza-community/eza/issues/1052#issuecomment-2318210137

**Comment by k-takata** [comment]
I've just downloaded [eza v0.19.2](https://github.com/eza-community/eza/releases/download/v0.19.2/eza.exe_x86_64-pc-windows-gnu.zip) and run on Command Prompt and I see that ANSI sequences are shown as is:
![image](https://github.com/user-attachments/assets/a4c97d05-1373-425f-863d-20ec9ac2593c)

To make this work on Command Prompt, eza should set the `ENABLE_PROCESSED_OUTPUT` flag and the `ENABLE_VIRTUAL_TERMINAL_PROCESSING` flag via [SetConsoleMode()](https://learn.microsoft.com/en-us/windows/console/setconsolemode).
If these flags are set, ANSI sequences should work both on winpty and ConPTY. (winpty supports only 16-color mode, though.)

**Comment by k-takata** [comment]
I also confirmed that ANSI colors are shown correctly when ConPTY is used.
(Open a terminal via `:term ++type=conpty`, then run `eza -l`.)

**Comment by TayTTo** [comment]
@k-takata sorry, I'm noob, how to set the flag via SetConsoleMode() function, as I searched, it's windows API, do I need to edit some file?

**Comment by k-takata** [comment]
1. Forget about SetConsoleMode() and use the `:term ++type=conpty` command to open the terminal window. Or,
2. Wait https://github.com/eza-community/eza/pull/1097 to be merged.
  It uses SetConsoleMode() function, so you don't need to edit the source code by yourself.

**Comment by TayTTo** [comment]
Oh it's worked, how can I set the terminal to conpty for permanently by editing the vimrc file? I love how you guys contribute to the tool, it's amazing.

**Comment by TayTTo** [comment]
@k-takata can I ask one more question, when the commit is merge, is there any announcement or there will be another version of the tool for installing.

**Comment by k-takata** [comment]
> how can I set the terminal to conpty for permanently by editing the vimrc file?

```vim
set termwintype=conpty
```
See the help for details as I wrote in my comment: https://github.com/vim/vim/issues/15553#issuecomment-2304424372

> when the commit is merge,

I don't know. It's not related to Vim at all. Please ask the eza community.

**Comment by zewpo** [comment]
Hi @TayTTo      FYI, it wasnt a bug in "vim" per se.  It was a regression in eza just a little while ago.  The fix will be released in a new version of eza, very soon I believe - because they've indicated that will accept my fix for it.  Maybe just a few days I expect.   But, if you really need a solution sooner, you can use the temporary work-around that @k-takata  has shared above.

**Comment by TayTTo** [comment]
@zewpo Now there are 2 updated version, and my eza still have the same problem with winpty, for some reasons, I cannot use conpty. I just want to remind you, not requiring anything.

**Comment by chrisbra** [comment]
as you can see, the PR at the eza repo is still open and hasn't been merged yet: https://github.com/eza-community/eza/pull/1097 
so don't expect it to be working until it is merged

**Comment by TayTTo** [comment]
@zewpo  it's okay now, I love you bro. Hahha.
