### ISSUE TITLE
Cursorline caused text wrapping on line with stacked unicode char

### ISSUE THREAD

**Issue by S1xZ** [vim/vim#15562]
### Steps to reproduce

echo "
สิ่งที่ต้องทดสอบอีกรอบ
THIS IS A NORMAL TEXT
mủt̉ả̉̉̉t̉ẻd̉W̉ỏ̉r̉̉d̉̉
THIS IS A NORMAL TEXT
" > test.txt
vim --clean -c "set cursorline" test.txt

![image](https://github.com/user-attachments/assets/c43f2f5c-3879-4368-a99a-60e9a6564276)

Moving from line with "THIS IS A NORMAL TEXT" up to line with the stacked unicode character caused the "THIS IS A NORMAL TEXT" to wrap up to the line with stacked unicode character

### Expected behaviour

No wrapping occuring

### Version of Vim

VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Aug 23 2024 17:17:40)

### Environment

Os: Ubuntu-22.04 on wsl 2.2.4.0
terminal: wezterm 20240203-110809-5046fc22
value of $TERM: xterm-256color
shell : zsh 5.8.1

**Comment by zeertzjq** [comment]
Cannot reproduce on Arch Linux with the same WezTerm version and Vim 9.1.689

**Comment by S1xZ** [comment]
Got similiar results in windows terminal, but overflowing instead. Might not be relevance cause windows terminal can't render my font properly
![image](https://github.com/user-attachments/assets/dde2729b-6282-4e1b-882a-3ff76668b845)

I'm using a monofont for the first unicode line, but for the second one I'm just copying it from the a stackover flow question about unicode lenght.
It seems to me that the cursorline are rendering N time less where N is the unicode char that stacks up on top of the normal char.

**Comment by chrisbra** [comment]
In a terminal, this is tricky, because Vim, the terminal and the underlying library functions all need to agree on the unicode characteristics.

**Comment by S1xZ** [comment]
Yeah, I understand🥲, I can see that the root cause might lies else where. I'll experiment with other OSes and If it doesn't work then i'll just fallback to electron based editor for project that require Thai for now, Thanks for the support.
