### ISSUE TITLE
Terminal freezes when running vim

### ISSUE THREAD

**Issue by IndiumInLCD** [vim/vim#15571]
### Steps to reproduce

1. Open terminal.
2. Type and run 'vim' or call it from an external process (vim --clean does not work).
3. The terminal freezes, only way to close it is by killing it.

Note : the --help command still works, and gvim works fine.

### Expected behaviour

Vim should open normally in the terminal.

### Version of Vim

VIM - Vi IMproved 9.1 (2024 Jan 02, compilé Aug 22 2024 20:12:11) Rustines incluses : 1-689 Compilé par Arch Linux Énorme version avec interface graphique GTK3.   Fonctionnalités incluses (+) ou non (-) : +acl                +file_in_path       +mouse_urxvt        -tag_any_white +arabic             +find_in_path       +mouse_xterm        +tcl/dyn +autocmd            +float              +multi_byte         +termguicolors +autochdir          +folding            +multi_lang         +terminal -autoservername     -footer             -mzscheme           +terminfo +balloon_eval       +fork()             +netbeans_intg      +termresponse +balloon_eval_term  +gettext            +num64              +textobjects +browse             -hangul_input       +packages           +textprop ++builtin_terms     +iconv              +path_extra         +timers +byte_offset        +insert_expand      +perl/dyn           +title +channel            +ipv6               +persistent_undo    +toolbar +cindent            +job                +popupwin           +user_commands +clientserver       +jumplist           +postscript         +vartabs +clipboard          +keymap             +printer            +vertsplit +cmdline_compl      +lambda             +profile            +vim9script +cmdline_hist       +langmap            -python             +viminfo +cmdline_info       +libcall            +python3/dyn-stable +virtualedit +comments           +linebreak          +quickfix           +visual +conceal            +lispindent         +reltime            +visualextra +cryptv             +listcmds           +rightleft          +vreplace +cscope             +localmap           +ruby/dyn           +wildignore +cursorbind         +lua/dyn            +scrollbind         +wildmenu +cursorshape        +menu               +signs              +windows +dialog_con_gui     +mksession          +smartindent        +writebackup +diff               +modify_fname       -sodium             +X11 +digraphs           +mouse              +sound              +xattr +dnd                +mouseshape         +spell              -xfontset -ebcdic             +mouse_dec          +startuptime        +xim +emacs_tags         +mouse_gpm          +statusline         -xpm +eval               -mouse_jsbterm      -sun_workshop       +xsmp_interact +ex_extra           +mouse_netterm      +syntax             +xterm_clipboard +extra_search       +mouse_sgr          +tag_binary         -xterm_save -farsi              -mouse_sysmouse     -tag_old_static          fichier vimrc système : "/etc/vimrc"      fichier vimrc utilisateur : "$HOME/.vimrc"   2e fichier vimrc utilisateur : "~/.vim/vimrc"   3e fichier vimrc utilisateur : "~/.config/vim/vimrc"       fichier exrc utilisateur : "$HOME/.exrc"         fichier gvimrc système : "/etc/gvimrc"     fichier gvimrc utilisateur : "$HOME/.gvimrc"  2e fichier gvimrc utilisateur : "~/.vim/gvimrc"  3e fichier gvimrc utilisateur : "~/.config/vim/gvimrc"  fichier de valeurs par défaut : "$VIMRUNTIME/defaults.vim"           fichier menu système : "$VIMRUNTIME/menu.vim"                $VIM par défaut : "/usr/share/vim" Compilation : gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/atk-1.0 -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/libpng16 -I/usr/include/pixman-1 -I/usr/include/cloudproviders -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/fribidi -I/usr/include/sysprof-6 -pthread -I/usr/include/gio-unix-2.0 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -g -ffile-prefix-map=/build/vim/src=/usr/src/debug/vim -flto=auto -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 Édition de liens : gcc -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.38/core_perl/CORE -Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-z,pack-relative-relocs -flto=auto -L/usr/local/lib -o vim -lgtk-3 -lgdk-3 -lz -lharfbuzz -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo -lcairo-gobject -lgdk_pixbuf-2.0 -lgio-2.0 -lglib-2.0 -lgobject-2.0 -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE -lm -ltinfo -lcanberra -lacl -lattr -lgpm -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm

### Environment

OS: Arch Linux
Terminal : foot, alacritty
$TERM=alacritty
Shell: GNU bash, version 5.2.32(1)-release (x86_64-pc-linux-gnu)
WM:  Hyprland v0.42.0

Note : vim was also called by a terminal file manager, yazi, to edit a file and yielded the same result.

**Comment by chrisbra** [comment]
Cannot reproduce. Please try `vim --clean`.
Note: Our CI test suite makes extensive use of running vim inside a vim terminal and it works fine. 

There must be some problem on your environment.

**Comment by IndiumInLCD** [comment]
As stated above, this has been tried and did not work.
My vim install seems to function for now.
However,  I'd rebooted twice before and had the same problem.
Will close for now, thank you for the time you took to answer.
