### ISSUE TITLE
Partials allow ignoring E704 and E705 checks

### ISSUE THREAD

**Issue by ZyX-I** [vim/vim#1557]
Consider the following code:

    let g:F = function('tr', [1])
    call extend(g:, {'string': g:F})
    let g:.input = g:F

If you remove second argument from `function()` call both following lines will error out with E704. But in this places Vim only checks for VAR_FUNC, but not VAR_PARTIAL, so the above lines work fine.

**Comment by ZyX-I** [comment]
I would also suggest to inspect places matching `VAR_FUNC.*\(\n.*\)\?VAR_PARTIAL` and do the same thing as I did in the linked commit. This will not find any errors, but will make code cleaner.

**Comment by ZyX-I** [comment]
And it appears that the reverse (VAR_PARTIAL before VAR_FUNC) should also be checked.

**Comment by zeertzjq** [comment]
This seems fixed after patch 8.2.2920.

**Comment by k-takata** [comment]
Closing then.
