### ISSUE TITLE
Patch 446 mentioned twice in version.c

### ISSUE THREAD

**Issue by mgedmin** [vim/vim#1558]
[version.c](https://github.com/vim/vim/blob/master/src/version.c#L783-L786) includes patch 446 twice, which makes `:version` display

```
Included patches: 1-446, 446-454
```

**Comment by vim-ml** [comment]
On Mon, Mar 13, 2017 at 2:45 PM, Marius Gedminas
<vim-dev-github@256bit.org> wrote:
> version.c includes patch 446 twice, which makes :version display
>
> Included patches: 1-446, 446-454
>

I confirm the problem. AFAICT, there is only one patch 446, however,
so the attached patch ought to fix it.

# HG changeset patch
# Parent  1cb437e354391b01fd4b65b95bea6f5353d3b428

diff --git a/src/version.c b/src/version.c
--- a/src/version.c
+++ b/src/version.c
@@ -778,18 +778,16 @@ static int included_patches[] =
     449,
 /**/
     448,
 /**/
     447,
 /**/
     446,
 /**/
-    446,
-/**/
     445,
 /**/
     444,
 /**/
     443,
 /**/
     442,
 /**/
