### ISSUE TITLE
zip.vim can not extract file - shell not defined

### ISSUE THREAD

**Issue by philippseith** [vim/vim#15585]
### Steps to reproduce

1. run vim some.zip
2. select a file in the zip
3. hit x to extract the file
4. Error occurs:
Error detected while processing function zip#Extract:
line   24:
E121: Undefined variable: shell
E116: Invalid arguments for function shellescape(shell))
E116: Invalid arguments for function system
***error*** attempted to extract <somefile> but it doesn't appear to be present!

### Expected behaviour

the selected file gets extracted from the zip

### Version of Vim

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jun 29 2024 05:34:37) macOS version - arm64 Included patches: 1-2136, 2142

### Environment

OS: macOS 14.6.1
$TERM: xterm-256color
Shell: both fish and bash

**Comment by chrisbra** [comment]
that is an old version. Can you please try with latest version?

**Comment by philippseith** [comment]
it works with 
```
VIM - Vi IMproved 9.1 (2024 Jan 02 kompiliert am Aug 01 2024 20:48:53)
MacOS Version - arm64
Inklusive der Patches: 1-650
```
but it fails the same way with 
```
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1724512491
```
which is the latest one. I know that here is not the nvim repo, but they seem to use the same zip.vim as vim. What have been the changes to fix the behavior in vim?

**Comment by chrisbra** [comment]
Well, you can compare the [runtime/plugin/zipPlugin.vim](https://github.com/vim/vim/blob/master/runtime/plugin/zipPlugin.vim) and [runtime/autoload/zip.vim](https://github.com/vim/vim/blob/master/runtime/autoload/zip.vim) for both repos. Or run
```
git log -- runtime/plugin/zipPlugin.vim runtime/autoload/zip.vim
```
in the top level of this repository.
