### ISSUE TITLE
Unbundle xxd

### ISSUE THREAD

**Issue by xyproto** [vim/vim#15589]
Hi,

Arch Linux package maintainer here.

`xxd` is often used as a built-time dependency for Arch Linux packages, but then ViM also needs to be installed (including its dependencies: `acl`, `gawk`, `git`, `glibc`, `gpm`, `gtk3`, `libcanberra`, `libgcrypt`, `libxt`, `lua`, `perl`, `python`, `ruby`, `tcl`, `vim-runtime` and `zlib`).

Since `xxd` can simply be built from a single `xxd.c` file, this feels sub-optimal.

Distros like NixOS and also HaikuOS also seems intrigued by the idea of unbundling `xxd` from ViM.

Have you considered removing `xxd` from ViM, letting it live on as a separate/forked project instead, and would it be feasible?

Best regards,
Alexander F. Rødseth

**Comment by xyproto** [comment]
Oh, and I have created a handy little fork of `xxd` here: https://github.com/xyproto/tinyxxd

**Comment by habamax** [comment]
Not opposing xxd in a separate repo, but you can build vim without at least half of those dependencies.

**Comment by k-takata** [comment]
Is it difficult to create two separate packages (vim w/o xxd, and xxd) from the single repository?

**Comment by xyproto** [comment]
@habamax Sure, but the main point was not the exact number of dependencies, but that there are several dependencies required by `vim` that are not required by `xxd`.

@k-takata No, not particularly. I do think that `vim` and `xxd` is different and independent enough that it would make sense to have them in two different projects / repos, though.

**Comment by Shane-XB-Qian** [comment]
seems it is not much difficult to build a minimal vim with xxd in it.
// BTW: to a distr package maker, i may suggest improve some packages or update it timely~
// (i know it is not talking to Arch :smile:) e.g:
// 1. gnu-screen, i remember it required some extra config, which maybe not easy to un-familiar.
// 2. weechat, i remember it required quite dependencies which not easy to get to un-developer.

-- 
shane.xb.qian

**Comment by xyproto** [comment]
@chrisbra Many distros depend on vim, including all the dependencies, when they only really need xxd as a build-time dependency. I fully agree that it does not have to be this way, though.

But my main question if the ViM project would be positive to splitting out `xxd` as a separate project.

**Comment by tonymec** [comment]
Why split them ? The Vim source contains a lot of stuff which I never use (tests, for instance, or anything needed only by Windows or by EBCDIC) but I don't gripe about that — I download that part of the sources together with the rest, I just don't use it; or maybe I build those files, but with the Windows-only and EBCDIC-only parts ifdeffed out.

If you want xxd but don't need Vim, then you can either pull the Vim repo and build only xxd (in which case you don't need the additional packages required by Vim but not by xxd) or (IIUC) you can even fork a copy of the src/xxd/ subdirectory and run "make" there.

I don't have a problem with people getting a copy of the xxd source and compiling only that; but I'd like to continue building xxd from the Vim repository without having to fetch it from elsewhere.

Best regards,
Tony.

**Comment by chrisbra** [comment]
> However, my main question is if the ViM project would be positive to splitting out xxd as a separate project, or not.

I wouldn't mind, but splitting it out has a few implications. The current test require a non-tiny Vim to be run. Adding more tests is harder when splitting out the repository and adding a dependency on xxd to Vim just for running the test suite sounds excessive :)

Also if we remove it, could potentially submodule or subtree it here at the current location, but this adds complexity, which I am not sure is worth it.

An alternative would be a sparse checkout:
```bash
~/code$ git clone -n --depth=1 --filter=tree:0  https://github.com/vim/vim vim-sparse
~/code$ cd vim-sparse
~/code/vim-sparse$ git sparse-checkout set --no-cone src/xxd runtime/doc
~/code/vim-sparse$ git checkout
~/code/vim-sparse$ ls
runtime  src
~/code/vim-sparse$ cd src/xxd && make
cc    -DUNIX -o xxd xxd.c
~/code/vim-sparse/src/xxd$ ls
Make_amiga.mak  Make_ming.mak  Make_mvc.mak  Make_vms.mms  Makefile  xxd  xxd.c
```
Would that approach be worth it?

Before I decide, I'd like to hear from other maintainers. @jamessan @zdohnal any opinion?

**Comment by jamessan** [comment]
In Debian, we produce a standalone xxd binary package from the source vim package. This works fine. I don't see the need to split xxd out to its own source package, especially since Vim is already a key package in Debian (providing the vi binary for base installs).

**Comment by xyproto** [comment]
Possibly related discussion about `xxd` in connection with NixOS: https://github.com/NixOS/nixpkgs/pull/335277

**Comment by chrisbra** [comment]
Seems like you already have your own tinyxxd fork. I still don't understand why you would need all those (vim built-) dependencies, if you only want to build xxd. So let's not do this for now.
