### ISSUE TITLE
Vim does not detect ZIP files appended to ELF

### ISSUE THREAD

**Issue by vadimkantorov** [vim/vim#15597]
### Steps to reproduce

```shell
echo a > a.txt
zip -0 a.zip a.txt
cat /usr/bin/cat a.zip > foo
chmod +x foo
vim foo
```

unfortunately I don't have access to a newer vim, as upgrade from Ubuntu 22.04 to Ubuntu 24.04 failed on my machine: https://github.com/microsoft/WSL/issues/11982

### Expected behaviour

ZIP appended to ELF makes both valid ELF and ZIP (and this feature is used e.g. by cosmo libc to bundle a files in a ZIP into an executable). Typically unzip programs would seek to the end to detect a ZIP footer which contains meta information about the archive and then seek back to access the files.

On vim 8.2 it just opens this ELF in the text mode. I expected vim to show the ZIP contents. At the very least, I expected vim to parse the ELF (and e.g. show info about ELF sections and so forth). Unfortunately, it just opened ELF file in the text mode.

I'll try 

### Version of Vim

8.2

### Environment

WSLv1, Ubuntu 24.04.1

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 03 2024 02:37:51)
Included patches: 1-579, 1969, 580-1848, 4975, 5016, 5023, 5072, 2068, 1849-1854, 1857, 1855-1857, 1331, 1858, 1858-1859, 1873, 1860-1969, 1992, 1970-1992, 2010, 1993-2068, 2106, 2069-2106, 2108, 2107-2109, 2109-3995, 4563, 4646, 4774, 4895, 4899, 4901, 4919, 213, 1840, 1846-1847, 2110-2112, 2121

**Comment by chrisbra** [comment]
Well, that looks like a hack. First of all, you are removing the `zip` extension, so Vim doesn't even consider to handle this as a zip archive. But even if you fix this, the [zip plugin](https://github.com/vim/vim/blob/c9bfed2fda8c23cc02325b1a7a6d84dc62bbea4b/runtime/autoload/zip.vim#L94-L100) verifies that it can handle the archive by checking for the magic header 'PK'. You successfully moved the header to the back. So it's not surprising that Vim does not handle this. Also even `file` does not detect that this is a zip archive:

```bash
chrisbra@debian /tmp/zip % file foo
foo: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=53587dafd2356ccd0e26919acb716e9131362712, for GNU/Linux 3.2.0, stripped
```

I would think what happens here is expected and this is not a bug and I don't even want to support such a hack.

**Comment by vadimkantorov** [comment]
> First of all, you are removing the `zip` extension


> But even if you fix this, the [zip plugin](https://github.com/vim/vim/blob/c9bfed2fda8c23cc02325b1a7a6d84dc62bbea4b/runtime/autoload/zip.vim#L94-L100) verifies that it can handle the archive by checking for the magic header 'PK'.

I also tried with the `.zip` extension (for `.zip` extension of explicit `set filetype=zip`

I hoped that in these conditions vim just delegates the check to some zip-reading libraries which typically support such files as they are seeking to the end to detect `end-of-central-directory signature` anyway, and then opening such files just works (supported by libarchive, 7zip, Windows ZIP opener - if you have the .zip extension etc)

If vim relies on magic checks even if the extension/explicit filetype is set to zip, then yes, it's not reasonable to ask.
