### ISSUE TITLE
popup_hide cannot hide cmdline location content

### ISSUE THREAD

**Issue by yu3s** [vim/vim#15608]
### Steps to reproduce

1. `cat popup.vim`
```vim
vim9script

var id: number

def Filter(winid: number, key: string): bool
        if key == 'q'
                #popup_close(winid)
                popup_hide(winid)
        else
                return false
        endif

        return true
enddef

id = popup_create(1, {
        col: 1,
        minwidth: &columns,
        maxwidth: &columns,
        #minheight: &lines - 1,
        #maxheight: &lines - 1,
        minheight: &lines,
        maxheight: &lines,
        filter: Filter,
})
```
2. `cd vim;vim --clean -p src/main.c popup.vim  -c "tabnext|so %"`
3. `q`
![Screenshot from 2024-09-02 14-42-11](https://github.com/user-attachments/assets/df4f2910-e826-4bda-8dd3-e0cc67d4d3b8)

### Expected behaviour

same as popup_close

### Version of Vim

9.1.708

### Environment

os: ubuntu24.04
terminal: alacritty
$TERM: xterm-256color
shell: bash5.2.21

**Comment by chrisbra** [comment]
sorry, I don't get it. What exactly do you expect?

**Comment by yu3s** [comment]
> sorry, I don't get it. What exactly do you expect?

When the popup_hide function is called, the bottom line of content still exists
When the popup_close function is called, all content will be hidden

**Comment by yu3s** [comment]
![Screenshot from 2024-09-02 15-41-36](https://github.com/user-attachments/assets/d9614012-cd91-4b76-a6ad-e2583cbdacda)
![Screenshot from 2024-09-02 15-41-20](https://github.com/user-attachments/assets/83b78ed7-99ca-491b-9a68-e476551aa426)

**Comment by chrisbra** [comment]
You are talking about the statusline? Which one of those two screenshots is which?

**Comment by habamax** [comment]
I assume cmdline area contains popup contents after `popup_hide()`.

**Comment by yu3s** [comment]
> You are talking about the statusline? Which one of those two screenshots is which?

`vim -p src/main.c popup.vim -c "tabnext | so %"`
![Screenshot from 2024-09-02 15-46-20](https://github.com/user-attachments/assets/d145c89b-9cb7-4f2d-bfc5-94e247c5f2d4)

**Comment by habamax** [comment]
As usual `ctrl-l` helps, clearing popup leftover.

**Comment by yu3s** [comment]
> As usual `ctrl-l` helps, clearing popup leftover.

`popup_close()` behaves normally, I want to confirm

**Comment by chrisbra** [comment]
Hm, this seems to fix it:
```diff
diff --git a/src/popupwin.c b/src/popupwin.c
index 0ff57fb4b..29df2edfb 100644
--- a/src/popupwin.c
+++ b/src/popupwin.c
@@ -2758,6 +2758,7 @@ popup_hide(win_T *wp)

     wp->w_popup_flags |= POPF_HIDDEN;
     // Do not decrement b_nwindows, we still reference the buffer.
+    clear_cmdline = TRUE;
     redraw_all_later(UPD_NOT_VALID);
     popup_mask_refresh = TRUE;
 }
```

**Comment by yu3s** [comment]
Thanks!

**Comment by chrisbra** [comment]
have you tried the PR?

**Comment by yu3s** [comment]
> have you tried the PR?

I have patched

**Comment by yu3s** [comment]
1. `cat complete.vim`
```vim
vim9script

def Complete()
	var list = [
		{"word": "one", "info": "one\ntwo\nthree\nfour\nfive"},
		{"word": "two", "info": "one\ntwo\nthree\nfour\nfive"},
		{"word": "three", "info": "one\ntwo\nthree\nfour\nfive"},
		{"word": "four", "info": "one\ntwo\nthree\nfour\nfive"},
		{"word": "five", "info": "one\ntwo\nthree\nfour\nfive"},
	]
	complete(col('.'), list)
enddef

setline(1, repeat(['foobar one two three'], &lines))

inoremap <C-n>  <ScriptCmd>Complete()<CR>
```
2. `vim  -c "so complete.vim|normal G"`
3. `o`
4. `<C-n>`
![Screenshot from 2024-09-03 08-45-21](https://github.com/user-attachments/assets/f246419e-b28b-4620-bbb3-00276210ea73)
5. `<Esc>`
![Screenshot from 2024-09-03 08-45-39](https://github.com/user-attachments/assets/8fef2dfd-8696-46fb-84e1-b10ca047e4e8)

**Comment by chrisbra** [comment]
that is a separate issue with the completion popup. Please create a new issue for that.

**Comment by Shane-XB-Qian** [comment]
and this one: https://github.com/vim/vim/issues/14212 seems same or dup issue.

**Comment by Shane-XB-Qian** [comment]
"same"   I meant:
1-the OP popup_create,  #15608
2-that complete popup,  #14212 
3-that that text property.  #13955 
all would be possible not clean the command line.

--
shane.xb.qian

**Comment by Shane-XB-Qian** [comment]
@yu3s please open that ticket you mentioned for completion popup, (since #14212 had been closed as dup), or reopen #14212

**Comment by yu3s** [comment]
I think we can reopen it

**Comment by chrisbra** [comment]
No, please create a new one. The `popup_hide()` issue has been fixed.
