### ISSUE TITLE
cterm attr affects termguicolor highlights

### ISSUE THREAD

**Issue by tomtomjhj** [vim/vim#15600]
### Steps to reproduce

```
vim --clean
```
```vim
set termguicolors
hi Group cterm=underline guifg=red
hi Group
```
`Group` is red and underlined:
![image](https://github.com/user-attachments/assets/c3b1ec13-db65-4273-8f25-0d6b12a97453)

### Expected behaviour

No underline

### Version of Vim

9.1.703

### Environment

Ubuntu 22.04
GNOME Terminal 3.44.0 using VTE 0.68.0 +BIDI +GNUTLS +ICU +SYSTEMD
xterm-256color

**Comment by habamax** [comment]
This is expected for `termguicolors` and mentioned in help topic regarding it.

**Comment by chrisbra** [comment]
correct. This is working as expected

**Comment by tomtomjhj** [comment]
duplicate of https://github.com/vim/vim/issues/1740
