### ISSUE TITLE
9.1.0709 breaks colors

### ISSUE THREAD

**Issue by chdiza** [vim/vim#15617]
### Steps to reproduce

9.1.0709 breaks coloring.

With `vim --clean`, make sure to set &tgc and then try `hi normal guifg=gray40`.

### Expected behaviour

The text should be a dark gray, but it is in fact a pretty light gray.

Reverting to the commit before that immediately fixes the issue.

It's not a terminal probelm because it also happens in gvim.  I can reproduce it in uxterm and kitty, too.

### Version of Vim

9.1.0709

### Environment

Debian 12.6 or Linux Mint 21.3 both show it.
Shell: bash

**Comment by chdiza** [comment]
Not only that, but changing to `guifg=gray55` doesn't even change it to a different gray!

**Comment by chrisbra** [comment]
can you please check #15619 ?

**Comment by chdiza** [comment]
That seems, upon initial testing, to have fixed it.

Side note: for some reason, Vim recognizes the [diff of that PR](https://patch-diff.githubusercontent.com/raw/vim/vim/pull/15619.diff), saved with filename extension `.diff`, as having a &filetype of "c"!  An unrelated bug?

**Comment by zeertzjq** [comment]
It's because of the modeline:
```
/* vim: set ft=c : */
```

**Comment by adah1972** [comment]
> can you please check #15619 ?

I encountered this problem, and this PR did fix it.
