### ISSUE TITLE
iskeyword weird.

### ISSUE THREAD

**Issue by spavlovich001** [vim/vim#1562]
Ok, iskeyword really weird options.
default value: iskeyword=@,48-57,_,192-255 
If I add value to this option:
`autocmd BufNewFile,BufRead *.py setlocal iskeyword+=a-z`

in result(press w in normal mode):
```
|CamelCaseWord zzzz aaa
CamelCaseWord |zzzz aaa
CamelCaseWord zzzz |aaa
```

But, if I set:
`autocmd BufNewFile,BufRead *.py setlocal iskeyword=a-z`

in result(press w in normal mode):
```
|CamelCaseWord zzzz aaa
C|amelCaseWord |zzzz aaa
Camel|CaseWord zzzz aaa
CamelC|aseWord zzzz aaa
CamelCase|Word zzzz aaa
CamelCaseW|ord zzzz aaa
CamelCaseWord |zzzz aaa
CamelCaseWord zzzz |aaa
```

But, if I set:
`autocmd BufNewFile,BufRead *.py setlocal iskeyword=.,:,;,(,),[,],{,},\',\"`

and result(press w in normal mode):
```
|return {'con': con, 'cur': cur}
return |{'con': con, 'cur': cur}
return {'|con': con, 'cur': cur}
return {'con|': con, 'cur': cur}
return {'con': |con, 'cur': cur}
return {'con': con, |'cur': cur}
return {'con': con, '|cur': cur}
return {'con': con, 'cur|': cur}
return {'con': con, 'cur': |cur}
return {'con': con, 'cur': cur}|
```

logically I need get this result:
```
|return {'con': con, 'cur': cur}
return |{'con': con, 'cur': cur}
return {|'con': con, 'cur': cur}
return {'|con': con, 'cur': cur}
return {'con|': con, 'cur': cur}
...
```

Many language need customization jumping(python dot symbol, javascript CamelCase). But iskeyword is not a complete control over jumping. Why ?

**Comment by ZyX-I** [comment]
A sequence of non-keywords without whitespaces is always one word, as well as a sequence of keywords. Changing `&iskeyword` in any fashion will not alter this. How do you imagine an option with meaning “defines what is a keyword character” to alter this? This is making no sense.

**Comment by chrisbra** [comment]
closing then.
