### ISSUE TITLE
Conflict with bufnr when using it as a cache key

### ISSUE THREAD

**Issue by cposture** [vim/vim#15636]
### Steps to reproduce

**Description**:
While developing a plugin, I encountered an issue with caching, where I use `bufnr` as the cache key. The problem arises in the following scenario:

When I open a new blank "No Name" window using a Vim command, the `:buffers` list shows a buffer with `bufnr 1`. However, when I use `:e test.txt` to open a local file in that window, I notice that `test.txt` reuses `bufnr 1`. This `bufnr` reuse creates a conflict in my caching system, as I expect `bufnr` to be unique.

So far, I’ve only noticed this issue in such cases where `bufnr` gets reused. Is this the expected behavior? Could this be adjusted so that `bufnr` remains unique throughout a Vim session? Alternatively, is there a recommended way to avoid this conflict?

**Steps to Reproduce**:
1. Open Vim
2. Use `:new` to open a new blank window, at which point `:buffers` shows a "No Name" buffer with `bufnr 1`
3. In the same window, use `:e test.txt` to open the file `test.txt`
4. Notice that `test.txt` reuses `bufnr 1`

### Expected behaviour

Each buffer should be assigned a unique `bufnr` to avoid reuse and potential cache conflicts.

### Version of Vim

9.1

### Environment

macOS version - arm64

**Comment by chrisbra** [comment]
Yes, that is a special case. When a new buffer is active, and it has not been modified, the buffer number will be re-used. That is not a bug but expected behaviour.
