### ISSUE TITLE
Make menus available to scripts

### ISSUE THREAD

**Issue by teto** [vim/vim#1563]
I like sublime palette a lot:
 ![Sublime palette](https://camo.githubusercontent.com/8570e1aedbad098b0ea7599c321d1b089b47dd4c/687474703a2f2f646f63732e7375626c696d65746578742e696e666f2f656e2f6c61746573742f5f696d61!6765732f636f6d6d616e642d70616c657474652d303030312e706e67)

It makes the editor configuration easy as you can change settings without knowing their exact name.
For vim there is https://github.com/dbeecham/ctrlp-commandpalette.vim but commands are manually defined. I would like to leverage the different (g)vim menus already existing and load them in the palette.
I wonder if vim could propose an API for plugins to retrieve the menus. As there is already json utilities, I though it could go to json (or vimL dict). Sthg like:
```
{
    [ {"lastentry": "&File", command:"", priority: 10, children: 
         [ {entry: "Open", command: ":e", priority: 500, children: []},
           {entry: "Split Open", command: "sp", priority: 500, children: []},
         ]
   ]
}
```
Is that sthg that can be considered ?
cheers

**Comment by teto** [comment]
Here is my attempt at writing such a feature for neovim https://github.com/neovim/neovim/pull/6322

**Comment by brammool** [comment]
Matthieu Coudron wrote:

>Here is my attempt at writing such a feature for neovim https://github.com/neovim/neovim/pull/6322

Please first write the text for the help file.  Then we can discuss how
it works, before implenting it (and throwing away half of it when there
is a bitter API).

-- 
hundred-and-one symptoms of being an internet addict:
179. You wonder why your household garbage can doesn't have an
     "empty recycle bin" button.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by teto** [comment]
Objectives:
- let neovim UIs be able to retrieve the menus so that they can display menus like gvim does
- let vim scripts retrieve defined menus (for use like the aforementioned "palette").

Proposition:
I propose an expression `export_menus("path to menu")` that returns a list of recursive (dict) entries. 

Output for the following menus I've defined in my vimrc:
```
menu Spell.EN_US :setlocal spell spelllang=en_us \| call histadd('cmd', 'setlocal spell spelllang=en_us')<CR>
menu Spell.FR :setlocal spell spelllang=fr_fr<CR>
```
is:
```
[
    {
        "children": [
            {
                "hidden": 0,
                "name": "EN_US",
                "ncommand": ":setlocal spell spelllang=en_us | call histadd('cmd', 'setlocal spell spelllang=en_us')\r",
                "ocommand": ":setlocal spell spelllang=en_us | call histadd('cmd', 'setlocal spell spelllang=en_us')\r",
                "priority": 500,
                "scommand": ":setlocal spell spelllang=en_us | call histadd('cmd', 'setlocal spell spelllang=en_us')\r",
                "vcommand": ":setlocal spell spelllang=en_us | call histadd('cmd', 'setlocal spell spelllang=en_us')\r"
            },
            {
                "hidden": 0,
                "name": "FR",
                "ncommand": ":setlocal spell spelllang=fr_fr\r",
                "ocommand": ":setlocal spell spelllang=fr_fr\r",
                "priority": 500,
                "scommand": ":setlocal spell spelllang=fr_fr\r",
                "vcommand": ":setlocal spell spelllang=fr_fr\r"
            }
        ],
        "hidden": 0,
        "name": "Spell",
        "priority": 500
    },
```
I am open to any suggestion as Ideally I would like to end up with a common api between neovim/vim.

**Comment by brammool** [comment]
Matthieu Coudron wrote:

> Objectives:
> - let neovim UIs be able to retrieve the menus so that they can display menus like gvim does
> - let vim scripts retrieve defined menus (for use like the aforementioned "palette").
> 
> Proposition:
> I propose an expression `export_menus("path to menu")` that returns a list of recursive (dict) entries. 
> 
> Output for the following menus I've defined in my vimrc:
> ```
> menu Spell.EN_US :setlocal spell spelllang=en_us \| call histadd('cmd', 'setlocal spell spelllang=en_us')<CR>
> menu Spell.FR :setlocal spell spelllang=fr_fr<CR>
> ```
> is:
> ```
> [
>     {
>         "children": [
>             {
>                 "hidden": 0,
>                 "name": "EN_US",
>                 "ncommand": ":setlocal spell spelllang=en_us | call histadd('cmd', 'setlocal spell spelllang=en_us')\r",
>                 "ocommand": ":setlocal spell spelllang=en_us | call histadd('cmd', 'setlocal spell spelllang=en_us')\r",
>                 "priority": 500,
>                 "scommand": ":setlocal spell spelllang=en_us | call histadd('cmd', 'setlocal spell spelllang=en_us')\r",
>                 "vcommand": ":setlocal spell spelllang=en_us | call histadd('cmd', 'setlocal spell spelllang=en_us')\r"
>             },
>             {
>                 "hidden": 0,
>                 "name": "FR",
>                 "ncommand": ":setlocal spell spelllang=fr_fr\r",
>                 "ocommand": ":setlocal spell spelllang=fr_fr\r",
>                 "priority": 500,
>                 "scommand": ":setlocal spell spelllang=fr_fr\r",
>                 "vcommand": ":setlocal spell spelllang=fr_fr\r"
>             }
>         ],
>         "hidden": 0,
>         "name": "Spell",
>         "priority": 500
>     },
> ```
> I am open to any suggestion as Ideally I would like to end up with a common api between neovim/vim.

Thanks.  I can see it's useful.  Currently the values could be obtained
with a :menu command, but parsing the output is quite complicated.

Once a script has obtained the values, does it get any help in using the
information?  Or does it need to do everything with the existing :menu
commands, such as :unmenu?  That should be possible, if care is taken to
escape special characters.

-- 
hundred-and-one symptoms of being an internet addict:
182. You may not know what is happening in the world, but you know
     every bit of net-gossip there is.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by teto** [comment]
> I can see it's useful. Currently the values could be obtained with a :menu command, but parsing the output is quite complicated.

correct. Just dumping the menus is enough for the scenariis I have in mind so I've nothing else to propose, script can keep using :menu and/or :unmenu.

Here is what the help could look like, I am not sure what would be a typical `vim` name for the function (exportmenu ? dumpmenu ? menu2dict :D )
```
dump_menu({path}, {modes})      *dump_menu()*
		Returns a |Dictionary| with all the submenu of {path} (set to 
		an empty string to match all menus). Only the commands matching {modes} are 
		returned ('a' for all, 'i' for insert see |creating-menus|).
```

**Comment by justinmk** [comment]
`getmenu()` or `menuget()`

**Comment by vim-ml** [comment]
2017-03-31 17:58 GMT+03:00 Matthieu Coudron <vim-dev-github@256bit.org>:
> I can see it's useful. Currently the values could be obtained with a :menu
> command, but parsing the output is quite complicated.
>
> correct. Just dumping the menus is enough for the scenariis I have in mind
> so I've nothing else to propose, script can keep using :menu and/or :unmenu.
>
> Here is what the help could look like, I am not sure what would be a typical
> vim name for the function (exportmenu ? dumpmenu ? menu2dict :D )

getsmth. Though more recent functions do use underscore, so the result
may be get_menu().

I would also suggest that get_menu() output (values describing the
menu) should share some keys with maparg(,,, 1) output: make it
dictionary with items

   name: entry name.
   priority: menu priority.
   icon: path to icon (string), may be missing.
   enabled: 0 or 1 (see `:h disable-menus`).
   tooltip: string (see `:h :tmenu`), may be missing.
   hint: menu hint (what you place after `<Tab>` when defining menu),
may be missing.
   shortcut: shortcut key, may be missing.
   hidden: 0 or 1 (`1` in the example, see `:h hidden-menus`).

   children: children menus. One entry may have either children or
implementations+hint.
   implementations: entry implementations, one per mode. One
dictionary may have either children or implementations, not both.

And here implementations values are partially shared with maparg(,,, 1):

   silent: 1 if <silent> modifier was used, 0 otherwise.
   noremap: 2 if <script> modifier was used, 1 if noremenu was used, 0
otherwise.
   sid: script ID.
   rhs: string, right-hand side.

So the result will look something like

{'Plugin': {
  'name': 'Plugin',
  'hidden': 0,
  'shortcut': 'P',
  'children': {
    'comment': {
      'name': 'comment',
      'priority': 500,
      'enabled': 1,
      'shortcut': 'c',
      'children': {
        'Comment': {
          'name': 'Comment',
          'priority': 500,
          'enabled': 1,
          'hint': '\cc',
          'implementations': {
            'n': {'noremap': 2, 'sid': 1, 'rhs':
'<Plug>NERDCommenterComment'}, 'silent': 1},
            'v': {'noremap': 2, 'sid': 1, 'rhs':
'<Plug>NERDCommenterComment'}, 'silent': 1},
          },
        }
      }
    }
  }
}}

Note: no lists, but `name` allows working with `values()` and ignore `keys()`.

And do not keep compatibility with maparg() regarding `noremap`: `menu
<script>` and `noremenu` must be distinguishable.

**Comment by brammool** [comment]
Matthieu Coudron wrote:

> > I can see it's useful. Currently the values could be obtained with a
> > :menu command, but parsing the output is quite complicated.
> 
> correct. Just dumping the menus is enough for the scenariis I have in mind so I've nothing else to propose, script can keep using :menu and/or :unmenu.
> 
> Here is what the help could look like, I am not sure what would be a typical `vim` name for the function (exportmenu ? dumpmenu ? menu2dict :D )
> ```
> dump_menu({path}, {modes})      *dump_menu()*
> 		Returns a |Dictionary| with all the submenu of {path} (set to 
> 		an empty string to match all menus). Only the commands matching {modes} are 
> 		returned ('a' for all, 'i' for insert see |creating-menus|).
> ```

OK.  But I'm sure someone else will start asking for the remaining info.
We should return the data that ":menu" returns.  Also including the
priority.  Can you give an example of the dictionary, so we can see
this?

-- 
Eagles may soar, but weasels don't get sucked into jet engines.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
Nikolay Pavlov wrote:

> 2017-03-31 17:58 GMT+03:00 Matthieu Coudron <vim-dev-github@256bit.org>:
> > I can see it's useful. Currently the values could be obtained with a :menu
> > command, but parsing the output is quite complicated.
> >
> > correct. Just dumping the menus is enough for the scenariis I have in mind
> > so I've nothing else to propose, script can keep using :menu and/or :unmenu.
> >
> > Here is what the help could look like, I am not sure what would be a typical
> > vim name for the function (exportmenu ? dumpmenu ? menu2dict :D )
> 
> getsmth. Though more recent functions do use underscore, so the result
> may be get_menu().

I've started grouping functions in a way that makes them easier to find.
Grouping by "get" is not very useful.  Thus I would prefer menu_get().
Later we could add more menu_xyz() functions (if there are any).

> I would also suggest that get_menu() output (values describing the
> menu) should share some keys with maparg(,,, 1) output: make it
> dictionary with items
> 
>    name: entry name.
>    priority: menu priority.
>    icon: path to icon (string), may be missing.
>    enabled: 0 or 1 (see `:h disable-menus`).
>    tooltip: string (see `:h :tmenu`), may be missing.
>    hint: menu hint (what you place after `<Tab>` when defining menu),
> may be missing.
>    shortcut: shortcut key, may be missing.
>    hidden: 0 or 1 (`1` in the example, see `:h hidden-menus`).
> 
>    children: children menus. One entry may have either children or
> implementations+hint.
>    implementations: entry implementations, one per mode. One
> dictionary may have either children or implementations, not both.
> 
> And here implementations values are partially shared with maparg(,,, 1):
> 
>    silent: 1 if <silent> modifier was used, 0 otherwise.
>    noremap: 2 if <script> modifier was used, 1 if noremenu was used, 0
> otherwise.
>    sid: script ID.
>    rhs: string, right-hand side.
> 
> So the result will look something like
> 
> {'Plugin': {
>   'name': 'Plugin',
>   'hidden': 0,
>   'shortcut': 'P',
>   'children': {
>     'comment': {
>       'name': 'comment',
>       'priority': 500,
>       'enabled': 1,
>       'shortcut': 'c',
>       'children': {
>         'Comment': {
>           'name': 'Comment',
>           'priority': 500,
>           'enabled': 1,
>           'hint': '\cc',
>           'implementations': {
>             'n': {'noremap': 2, 'sid': 1, 'rhs':
> '<Plug>NERDCommenterComment'}, 'silent': 1},
>             'v': {'noremap': 2, 'sid': 1, 'rhs':
> '<Plug>NERDCommenterComment'}, 'silent': 1},
>           },
>         }
>       }
>     }
>   }
> }}
> 
> Note: no lists, but `name` allows working with `values()` and ignore `keys()`.
> 
> And do not keep compatibility with maparg() regarding `noremap`: `menu
> <script>` and `noremenu` must be distinguishable.

Looks OK.  Sometimes a list is easier to deal with.  But it should be
possible to create the list from the dict, using the priority.  An
example in the docs would be very helpful.

-- 
"After a few years of marriage a man can look right at a woman
without seeing her and a woman can see right through a man
without looking at him."
 - Helen Rowland

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by teto** [comment]
Ok for menu_get.
How to retrieve the hint information ? can't find it.

Also - but that might be a neovim thing @ZyX-I  - when I export for instance `menu Trans.FR :te trans :fr <cword><CR>` with `tv_dict_add_str(impl, S_LEN("rhs"), (char *)menu->strings[bit]);` it appears as `                         ":te trans :fr <cword>\r"`

**Comment by ZyX-I** [comment]
https://github.com/vim/vim/issues/1563#issuecomment-290821247 looks like my comment because Bram is quoting me, but this is from Bram. Something is wrong with @vim-ml.

**Comment by vim-ml** [comment]
Hi,

2017-4-4(Tue) 14:12:36 UTC+9 Nikolai Aleksandrovich Pavlov:
> #1563 (comment) looks like my comment because Bram is quoting me, but this is from Bram. Something is wrong with @vim-ml.

This is a bug of google groups that happens often before. maybe.
https://groups.google.com/d/topic/vim_dev/Ih7PQP8ssbc/discussion

It is not quite fixed...

--
Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by teto** [comment]
closing since I mostly use neovim.

**Comment by yegappan** [comment]
Patch 8.2.0385 introduced the menu_info() function that returns information about a menu item including the list of submenus.

**Comment by teto** [comment]
cool thanks !
