### ISSUE TITLE
Error callback is not being called by terminal

### ISSUE THREAD

**Issue by darkseid-is** [vim/vim#15665]
### Steps to reproduce

```
func OutCall(channel, msg)
    echom 'out| ' .. string(a:msg)
endfunc

func ErrCall(channel, msg)
    echom 'err| ' .. string(a:msg)
endfunc

func Create()
    let vim_cmd = "sh"
    let buf = term_start(vim_cmd, #{term_finish: 'close', out_cb: 'OutCall', err_cb: 'ErrCall'})
endfunc

call Create()
```

1. Source the above script 
2. In the created terminal write a non existing command 
3. The stderr is not read 

### Expected behaviour

The callback specified in `err_cb` should be called

### Version of Vim

9.1.675

### Environment

OS: Kali Linux
Terminal: Alacritty
$TERM: xterm-256color
shell: zsh

**Comment by chrisbra** [comment]
Hm, this seems intentionally. For terminal jobs a 'pty' is used and in that case, the error filedescriptor is not used (setting up the pipe is skipped because `pty_master_fd > 0`:  https://github.com/vim/vim/blob/be551dacb87a0542afd8b5c17b89e6749f2dc355/src/os_unix.c#L5766-L5767   (so there is no pipe setup for the error case).

There is also this comment here: https://github.com/vim/vim/blob/be551dacb87a0542afd8b5c17b89e6749f2dc355/src/os_unix.c#L5982-L5990

**Comment by chrisbra** [comment]
Having said that, we could setup the pipe for the error file descriptor when an error callback has been defined:
```diff
diff --git a/src/os_unix.c b/src/os_unix.c
index e77a4b23c..0aa6f3ca1 100644
--- a/src/os_unix.c
+++ b/src/os_unix.c
@@ -5763,8 +5763,11 @@ mch_job_start(char **argv, job_T *job, jobopt_T *options, int is_terminal)
            goto failed;
        }
     }
+    // only create a pipe for the error fd, when either a callback has been setup
+    // or pty is not used (e.g. terminal uses pty by default)
     else if (!use_out_for_err && !use_null_for_err
-                                     && pty_master_fd < 0 && pipe(fd_err) < 0)
+               && (pty_master_fd < 0 || (options->jo_set & JO_ERR_CALLBACK))
+                           && pipe(fd_err) < 0)
        goto failed;

     if (!use_null_for_in || !use_null_for_out || !use_null_for_err)
```

I tried that one out, interestingly, it seems the shell by default prints `$PS1` on stderr, so you would get the shell prompt for the error callback. 

I am not sure we should change it...
