### ISSUE TITLE
Vim9: setreg('+', "foo") results in E354: Invalid register name: '+'     

### ISSUE THREAD

**Issue by ubaldot** [vim/vim#15676]
### Steps to reproduce

To reproduce the issue is straightforward:

```
vim9script
setreg('+', "foo")
```

### Expected behaviour

Text is copied on `+` register.

### Version of Vim

1-516

### Environment

WSL2

**Comment by tonymec** [comment]
Hm.
The output of the `:version` command might be interesting. 
See `:help :redir` about how to get that output into a file without needing to paste it to the clipboard.

Best regards,
Tony.

**Comment by ubaldot** [comment]
Mmmm I am on the tram now and I cannot check the version, but I am 100% that version doesn't have the clipboard. 

Does it mean that + is also gone? Can't that be used as a generic register?

**Comment by vim-ml** [comment]
Please verify that you have actually a working clipboard support first

Thanks
Chris

Am 2024-09-12 20:17, schrieb ubaldot:

**Comment by k-takata** [comment]
> Does it mean that + is also gone? Can't that be used as a generic register? If so, then the issue can be closed. :)

Yes, the `+` register is available only when the clipboard feature is enabled.
You may want to use something like this: `setreg(has('clipboard_working') ? '+' : '"', "foo")`
Closing.
