### ISSUE TITLE
File confirmation operations in netrw accept arbitrary suffixes

### ISSUE THREAD

**Issue by Jamesbarford** [vim/vim#15680]
### Steps to reproduce

- `touch file.txt`
- open netrw
- move the selection to `file.txt`
- hit `d`
- type `y` followed by an arbitrary set of characters for example; `y not?`
- file gets deleted

(same logic applies for `n`, `q`)

### Expected behaviour

Expectation is that, given the instance of confirmation, only `y` or `yes` is acceptable, else nothing happens. Same logic applicable for `n` `q`

### Version of Vim

9.1.636

### Environment

OS: 22.04.3-Ubuntu
terminal: alacritty
term: xterm-256color
shell: 5.1.16

**Comment by Jamesbarford** [comment]
I'd be happy to look at this if this is undesirable behaviour

**Comment by chrisbra** [comment]
Thanks, I think I have fixed that specific behaviour for `D` (to delete). If you find other similar behaviour, a PR would be very welcome.
