### ISSUE TITLE
A correction to syntax/lyrics.vim

### ISSUE THREAD

**Issue by lkintact** [vim/vim#15703]
### Steps to reproduce

(I tried e-mailing the maintainer with this, but (s)he doesn't answer, so I'm opening an issue here).

Sometimes lyrics files contain more than one timestamp in a line, like in the following extract:
```
[01:08.31][01:51.75][02:05.76][02:59.94][03:14.29]Goodness
[01:09.91][01:53.06][02:07.63][03:02.31][03:16.72]I've tried
[01:12.31][01:55.49][02:09.83][03:04.18][03:18.84]You're such a puzzle
```
Currently  only the first timestamp in the line is highlighted.

To change this and have all the timestamps highlighted, in `lyrics.vim` the line
`syn match lrcLyricTime /^\s*\[\d\d:\d\d\.\d\d\]/`
should be changed to
`syn match lrcLyricTime /^\s*\(\[\d\d:\d\d\.\d\d\]\)\{1,}/`.

### Expected behaviour

.

### Version of Vim

9.1.682

### Environment

.

**Comment by ObserverOfTime** [comment]
You gotta give the maintainer more than a single day to respond, if it's not urgent. Especially when it's a weekday. :)
