### ISSUE TITLE
Mouse mode feature is not working in Vim 9.1.736

### ISSUE THREAD

**Issue by shadevacc** [vim/vim#15706]
### Steps to reproduce

- `set mouse=a` and open any file, for example open `vim ~/.vimrc`
- Click on alternative lines to see if it selects that line.
- Try to select a text using mouse mode on.
- Try to scroll up and down using your mouse.
- Complete mouse feature is broke in vim9.1.736 while it works perfectly fine in vim8.2.5170.
- Attaching demo gif on VIM 9.1.736.
![vim9 1 736_GIF](https://github.com/user-attachments/assets/b8e79efb-3243-4a84-a9bc-202f90a7e5c4)

### Expected behaviour

- When we `set mouse=a`, expecting all features of mouse to work.
- Scroll up & down inside any file should move lines up and down.
- Selecting text should work without any problem.
- It works fine in VIM 8.2.5170 and attached a demo GIF.
![vim8 2 5170_GIF](https://github.com/user-attachments/assets/39b84365-d466-4549-b1a1-d83e38299692)
 

### Version of Vim

9.1.736

### Environment

- Operating `System: Ubuntu 22.04.4 LTS`
- Terminal: `Terminator 2.1.4`
- $TERM: `xterm-256color`
- $SHELL: `/bin/bash`
- Bash version: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`

### Logs and stack traces

```shell
Attached GIF's for reference.
```

**Comment by k-takata** [comment]
What does `:verbose set ttymouse?` show?
Is it the same on 8.2.5170?

**Comment by shadevacc** [comment]
> What does `:verbose set ttymouse?` show? Is it the same on 8.2.5170?
- It is set to `xterm2` in both `Vim 8.2.5170` and `Vim 9.1.736`
  ```
  .vim/vimrc                                                                                      1,1            Top
    ttymouse=xterm2
          Last set from ~/data/.vim/vimrc line 10
  Press ENTER or type command to continue
  
  ```

**Comment by shadevacc** [comment]
Thank you @k-takata , after your question on `ttymouse` setting, i have tried to change `ttymouse` value to :
`xterm`,
`xterm2`,
`dec`,
`netterm`,
`jsbterm`,
`pterm`,
`urxvt`,
`sgr`
and found that it completely works fine when i change it's value to `sgr`.
```vim
" vim ~/.vim/vimrc
set ttymouse=sgr
```
May be this prob is related to terminal because it doesn't work with any other setting.

> Changing the configuration alone worked here. It is not an issue with Vim v9.1.736 i guess

**Comment by shadevacc** [comment]
Closing the issue, as the problem faced is related to `terminal`, `vim configuration` and not `vim itself`. Thanks.
