### ISSUE TITLE
"perl not found in $PATH" message on opening Perl files

### ISSUE THREAD

**Issue by lkintact** [vim/vim#15705]
### Steps to reproduce

Whenever I open a file with the `pl` extension, gVim emits a "perl not found in $PATH" message. Indeed, I don't have Perl installed, but checking for it just to open a Perl file seems wrong. 

### Expected behaviour

gVim shouldn't emit the message.

### Version of Vim

9.1.682

### Environment

OS: Windows 10
Terminal: GUI

**Comment by tonymec** [comment]
Have you tried without syntax checking ? Or with a version of gvim compiled without Perl support ?

**Comment by lkintact** [comment]
> Have you tried without syntax checking ?

Just tried with:
1. Run `gvim.exe --clean`
2. Execute `:syntax off`
3. Execute `:edit example.pl`,

gVim still emits the message.

> Or with a version of gvim compiled without Perl support ?

Can't check that, sorry - I use per-compiled gVim from https://github.com/vim/vim-win32-installer.

**Comment by habamax** [comment]
Issue is in 

- https://github.com/vim/vim/blob/master/runtime/ftplugin/perl.vim#L62-L62
- https://github.com/vim/vim/blob/master/runtime/autoload/dist/vim.vim#L22-L22
