### ISSUE TITLE
Empty command after `:global/some-text/p` jumps to the last match

### ISSUE THREAD

**Issue by manasthakur** [vim/vim#1571]
When we do not enter any command after printing matching lines using `:global`, and simply press `<Esc>` or `<Enter>`, the cursor jumps to the last match shown. This is annoying.

~~Is there a rationale behind this?~~
I think this happens because the `print` command is performed on each match, and it ends with the last one.

Can the behaviour be changed such that the location is maintained on not entering any command?

**Comment by chrisbra** [comment]
That is specified [posix behaviour](http://pubs.opengroup.org/onlinepubs/009695399/utilities/ex.html)

> Current line: If no commands executed, set to the last marked line. Otherwise, as specified for the executed ex commands.)

**Comment by manasthakur** [comment]
Oh okay. That's fair then.
