### ISSUE TITLE
Microsoft Windows 10 CMD Italic t_ZH do not display, instead see bright yellow background

### ISSUE THREAD

**Issue by clach04** [vim/vim#15723]
### Steps to reproduce

1. Create file vim_issue_7834.vim (based on test case from Mac issue 7834)

        " This is some comment that should be in italics in vim 
        " sample usage
        "       vim --noplugin -u vim_issue_7834.vim vim_issue_7834.vim
        " based on https://github.com/vim/vim/issues/7834
    
        set nocompatible
        set encoding=utf-8
        set noswapfile nobackup
        syntax enable
    
        augroup italisizecomment
            autocmd!
            autocmd VimEnter * nested hi Comment cterm=italic
        augroup END
        "" Alternatively:
        "hi Comment cterm=italic

2. use file in demo:

        vim --clean --noplugin -N -u vim_issue_7834.vim vim_issue_7834.vim

### Expected behaviour

I was not expecting bright Yellow.

I wasn't sure if italics are supported in vim + Windows CMD.exe

![image](https://github.com/user-attachments/assets/6c050c43-2938-4c52-b3e4-4bebe37c6c8c)

### Version of Vim

VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Jan  2 2024 23:53:44)

### Environment

    C:\Users\clach04>ver

    Microsoft Windows [Version 10.0.19045.4780]

    C:\>vim --version
    VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Jan  2 2024 23:53:44)
    MS-Windows 64-bit console version
    Compiled by appveyor@APPVEYOR-VM
    Huge version without GUI.  Features included (+) or not (-):
    +acl                +ex_extra           +multi_lang         -tag_any_white
    +arabic             +extra_search       +mzscheme/dyn       -tcl
    +autocmd            -farsi              -netbeans_intg      +termguicolors
    +autochdir          +file_in_path       +num64              +terminal
    +autoservername     +find_in_path       +packages           -termresponse
    -balloon_eval       +float              +path_extra         +textobjects
    +balloon_eval_term  +folding            +perl/dyn           +textprop
    -browse             -footer             +persistent_undo    -tgetent
    ++builtin_terms     +gettext/dyn        +popupwin           +timers
    +byte_offset        -hangul_input       -postscript         +title
    +channel            +iconv/dyn          +printer            -toolbar
    +cindent            +insert_expand      +profile            +user_commands
    +clientserver       +ipv6               +python/dyn         +vartabs
    +clipboard          +job                +python3/dyn-stable +vertsplit
    +cmdline_compl      +jumplist           +quickfix           +vim9script
    +cmdline_hist       +keymap             +reltime            +viminfo
    +cmdline_info       +lambda             +rightleft          +virtualedit
    +comments           +langmap            +ruby/dyn           +visual
    +conceal            +libcall            +scrollbind         +visualextra
    +cryptv             +linebreak          +signs              +vreplace
    +cscope             +lispindent         +smartindent        +vtp
    +cursorbind         +listcmds           +sodium/dyn         +wildignore
    +cursorshape        +localmap           +sound              +wildmenu
    +dialog_con         +lua/dyn            +spell              +windows
    +diff               +menu               +startuptime        +writebackup
    +digraphs           +mksession          +statusline         -xattr
    -dnd                +modify_fname       -sun_workshop       -xfontset
    -ebcdic             +mouse              +syntax             -xim
    +emacs_tags         -mouseshape         +tag_binary         -xpm_w32
    +eval               +multi_byte_ime/dyn -tag_old_static     -xterm_save
       system vimrc file: "$VIM\vimrc"
         user vimrc file: "$HOME\_vimrc"
     2nd user vimrc file: "$HOME\vimfiles\vimrc"
     3rd user vimrc file: "$VIM\_vimrc"
          user exrc file: "$HOME\_exrc"
      2nd user exrc file: "$VIM\_exrc"
           defaults file: "$VIMRUNTIME\defaults.vim"
    Compilation: cl -c /W3 /GF /nologo -I. -Iproto -DHAVE_PATHDEF -DWIN32 -DHAVE_STDINT_H  -DFEAT_CSCOPE -DFEAT_TERMINAL -DFEAT_SOUND  -DFEAT_JOB_CHANNEL -DFEAT_IPV6 -DHAVE_INET_NTOP    -DHAVE_SODIUM -DDYNAMIC_SODIUM -DDYNAMIC_SODIUM_DLL=\"libsodium.dll\" /I "C:\projects\vim-win32-installer\dependencies\libsodium\include" -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 /source-charset:utf-8 /MP /Ox /GL -DNDEBUG /Zl /MT /D_CRT_SECURE_NO_DEPRECATE /D_CRT_NONSTDC_NO_DEPRECATE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua54.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python3.dll\" -DDYNAMIC_PYTHON3_STABLE_ABI -DFEAT_MZSCHEME -I "C:\projects\vim-win32-installer\dependencies\racket\include" -DMZ_PRECISE_GC -DDYNAMIC_MZSCHEME -DDYNAMIC_MZSCH_DLL=\"libracket3m_dcgt6o.dll\" -DDYNAMIC_MZGC_DLL=\"libracket3m_dcgt6o.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl532.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_DLL=\"x64-ucrt-ruby320.dll\" -DRUBY_VERSION=32 -DFEAT_HUGE /Fd.\ObjCULYHRZAMD64/ /Zi
    Linking: link /nologo /opt:ref /LTCG oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib netapi32.lib uuid.lib user32.lib  /machine:AMD64  libcmt.lib   /nodefaultlib:lua54.lib  /STACK:8388608  /nodefaultlib:python27.lib /nodefaultlib:python3.lib    winmm.lib Ws2_32.lib   /PDB:vim.pdb -debug

### Logs and stack traces

```shell
N/A
```

**Comment by clach04** [comment]
For now my workaround is to disable italicc:

     autocmd VimEnter * nested hi Comment cterm=NONE

Seeing the same issue in mintty as well.

**Comment by ynkdir** [comment]
Try :set termguicolors or :set t_Co=256.

**Comment by chrisbra** [comment]
closing then.

**Comment by clach04** [comment]
> I don't think `t_ZH` is actually supported in cmd. See the comment here:
> 
> https://github.com/vim/vim/blob/be551dacb87a0542afd8b5c17b89e6749f2dc355/src/term.c#L883

Thanks @chrisbra ! That explains why my source search for `t_ZH` didn't come up with anything. It's clearly a deliberate decision.

It looks like at least win32 and vt52 have the same behavior (and have for a long time, introduced 20 years ago for vim 7 in change https://github.com/vim/vim/commit/071d4279d6ab81b7187b48f3a0fc61e587b6db6c).

Is this worth documenting? If so how/where? Is 
https://github.com/vim/vim/blob/6908428560a0d6ae27bf7af6fcb6dc362e31926c/runtime/doc/term.txt#L449

an appropriate place to add a comment? I would have not figured any of this out without your very specific pointer :-) I'd guessed/assumed it wasn't supported but had no idea where the yellow was coming from 😆

**Comment by chrisbra** [comment]
It seems those are documented here: https://github.com/vim/vim/blob/6908428560a0d6ae27bf7af6fcb6dc362e31926c/runtime/doc/os_dos.txt#L138-L205

Although is uses `t_czh` instead of `t_ZH` and `t_czr` instead of `t_ZR`
