### ISSUE TITLE
comment on non-linewise text objects

### ISSUE THREAD

**Issue by Konfekt** [vim/vim#15727]
### Problem

Inline commenting is not uncommon, for example, `grep -E '\S\s+"\s*[a-zA-Z ]+$'  $VIMRUNTIME/*/*.vim | wc -l` yields 625 matches. Neither `gc$` nor a visual selection from the cursor to the end of the line and typing `gc` comments the intended part but the complete line

### Expected behavior

`gc` comments the given text-object

**Comment by zeertzjq** [comment]
This will require an option separate from 'commentstring', since inline comments may have different syntax than linewise comments, and not all languages support inline comments.

**Comment by Konfekt** [comment]
So why not set gC in ftplugin whenever commentstring is applicable in-line? That's not too rare.

**Comment by chrisbra** [comment]
Honestly, I don't think we should support this. A non-linewise comment, may have other semantics, you may need an end comment marker as well. What about when it is already in a commented line, sometimes those are not valid inside commented out regions (thinking of xml `<!--` comment marker). 

It might be a nice VimScript side-project, but I would prefer if we keep the builtin commenting feature simple.

**Comment by Konfekt** [comment]
@chrisbra I am sorry, I read this while finishing my PR; but it does not seem such a big story if restricted to those `&commentstrings` supporting inline comments which are quite common.
If yours do not, say by choice `/* ... */` in C instead of `// ...`, then `gC` is synonym to `gcc`. 
Let me not map it at all and just document it instead, so that no harm should be done.
