### ISSUE TITLE
vim help file syntax: command blocks not getting highlighted at the end of a sentence

### ISSUE THREAD

**Issue by returnDanilo** [vim/vim#15745]
### Steps to reproduce

Run the command:

```
echo -e "This `block` in the middle of a sencente gets highlighted corretly.\nThis `multiword block` in the middle of a sencente ALSO gets highlighted corretly.\nSingle-word blocks at end of sentences are good `too`.\nBut multiword blocks at the end of sentences `are not`." | /bin/vim -c "setfiletype help" -c "syntax on" -u NONE --not-a-term -
```

You'll see something like this:

![image](https://github.com/user-attachments/assets/c385fc6b-d71d-4f77-bde9-8e7d7beb3416)

You can also use

    :helpgrep `[^`,]\+ [^`,]\+`\.

to see examples this syntax in the vim documentation with the broken highlighting.

[The fix I tried](https://github.com/returnDanilo/vim/commit/b6f2dabcb327b1aaeb1625abdb91df6b3e153d60) managed to correct the "multiword at the end of sentence" case, but it broke the highlighting for when documenting the backtick behavior: See usr_07.txt match of the helpgrep command above.

### Expected behaviour

Expected for all the backtick blocks in the example to be highlighted.

### Version of Vim

9.1 patches 1-741

### Environment

N/A

**Comment by chrisbra** [comment]
Hm, maybe we should just reformat that section in usr_07.txt and make sure to add a line-break between the <code>`"</code> and the <code>`.</code>?

**Comment by chrisbra** [comment]
I think I have fixed it now. Please check it.

**Comment by returnDanilo** [comment]
> Please check it.

It's working as expected! Cheers! ;)
