### ISSUE TITLE
E_STRICT is deprecated in "soon" to be released PHP 8.4

### ISSUE THREAD

**Issue by jpbion** [vim/vim#15750]
### Steps to reproduce

Try to use E_STRICT in a PHP source file while running PHP 8.4

### Expected behaviour

No problem

### Version of Vim

9.1.X

### Environment

Any with PHP 8.4

### Logs and stack traces

```shell
This is a courtesy notice of PHP 8.4's upcoming deprecation. I am not sure if VIM 'uses' E_STRICT in any running PHP code, or just in auto-complete helpers. Here is the information about E_STRICT:

https://github.com/php/php-src/blob/php-8.4.0RC1/UPGRADING
```

**Comment by zeertzjq** [comment]
So what's the problem?

**Comment by jpbion** [comment]
My goal in submitting this bug report was to offer a courtesy notice concerning this. I looked at the packages my Linux system uses for references to E_STRICT and noticed vim had a few. So, as a courtesy, I let you know of this. On Sep 27, 2024, at 4:05 AM, zeertzjq ***@***.***> wrote:﻿
So what's the problem?

**Comment by chrisbra** [comment]
please report to the upstream php runtime file repository: https://github.com/TysonAndre/php-vim-syntax
