### ISSUE TITLE
Replace :wq with :x in vimtutor

### ISSUE THREAD

**Issue by datamuc** [vim/vim#15781]
https://github.com/vim/vim/blob/6a89c94a9eeee53481ced1a1260a177bffde4c0f/runtime/tutor/tutor#L142

I think all occurences of `:wq` should be replaced with `:x`. `:wq` is harmful, it writes the file no matter if it was changed, resulting in updates in modification time. `:x` only writes when there were changes.

**Comment by chrisbra** [comment]
I think `:wq` is essentially fine to learn Vim. If you are more proficient in Vim, you can read all the details about `:w` vs `:x` to write and quit, but as a beginner guide to make sure the file is saved and the editor is quit this is fine as is. And it least from my personal experience watching people using vim, `:wq` is much more known than `:x`.
