### ISSUE TITLE
Syntax highlighting for Bash always takes `[[` for a conditional instead of a POSIX pattern class

### ISSUE THREAD

**Issue by Reylak** [vim/vim#15799]
### Steps to reproduce

Open this `test.sh` file with `vim --clean`:

```bash
#! /bin/bash

ls [[:alpha:]]
# bad highlighting (like syntax error?)
```

See screenshot:

![image](https://github.com/user-attachments/assets/5ce68a97-3685-46dc-97f5-20ec47e6d53f)

### Expected behaviour

Correct syntax highlighting after the pattern `[[:alpha:]]`

### Version of Vim

9.1.0707

### Environment

OS: ArchLinux
TERM=alacritty
SHELL=zsh

**Comment by chrisbra** [comment]
You need to be patient here. We don't have a shell syntax maintainer currently

**Comment by zzzyxwvut** [comment]
The `start` argument of `shDblBrace` can try not to match any  
`:` that follows `\[\[` (the `[[` conditional command).  (The  
`true` command apparently needs whitespace around it, i.e.  
`[[ : ]]`.)  On the other hand, the Bash manpage clearly uses  
whitespace around an expression, i.e. `[[ expression ]]`, so  
`start="\[\[\s\@="` should be valid as well.

For now, try adding to your `~/.vim/after/syntax/sh.vim`:

```vim
if exists("b:is_kornshell") || exists("b:is_bash")
 syn clear   shDblBrace
 syn region  shDblBrace matchgroup=Delimiter start="\[\[:\@!"	skip=+\%(\\\\\)*\\$+ end="\]\]"	contains=@shTestList,shAstQuote,shNoQuote,shComment
endif
```

**Comment by Reylak** [comment]
Well, I don't _expect_ you to fix the problems immediately :)

Thank you @zzzyxwvut for this quick fix, it seems to work (both what you posted, and you other suggestion with `start="\[\[\s\@="`).

Note that the example in Bash's manual for conditional, worked correctly, even without this fix:

```sh
[[ $line =~ [[:space:]]*(a)?b ]]
```

But maybe another approach should be that conditionals should only be matched where commands are expected?

**Comment by zzzyxwvut** [comment]
Upon further examination, the initial patches are bad in  
that they fail to address evident misidentification of   
pattern bracket expressions (`shOperator`), e.g. `[a-z]`, with    
`[` or `[[` utilities (`shExpr`).  Here's another attempt at it:

```vim
syn clear   shOperator
syn match   shOperator	"<<\|>>"		contained
syn match   shOperator	"[!&;|]"		contained

"" XXX: Replace "[[", "[^" ("[!" ?), "[:", "]]" ...
"syn match   shOperator	"\[[[^:]\|\]]"		contained
"" XXX: ... with a general bracket expression, and look for
"" a non-whitespace character to follow before claiming a match.
syn region  shOperator	matchgroup=Delimiter start="\[\S\@=" end="\]"	contains=shCharClass,shCollSymb,shEquivClass

syn match   shOperator	"[-=/*+%]\=="		skipwhite nextgroup=shPattern

syn clear   shExpr
syn region  shExpr	transparent matchgroup=shExprRegion  start="{" end="}"		contains=@shExprList2 nextgroup=shSpecialNxt
"" For "[" (aka "test"), look for a whitespace character to follow
"" before claiming a match.
syn region  shExpr	matchgroup=shRange start="\[\s\@=" skip=+\\\\\|\\$\|\[+ end="\]" contains=@shTestList,shSpecial

"" Allow for character classes etc. in POSIX shells as well.
syn clear   shCaseRange
syn region  shCaseRange	matchgroup=Delimiter start=+\[+ skip=+\\\\+ end=+\]+	contained	contains=shCharClass,shCollSymb,shEquivClass

"" Match collating symbols and equivalence classes.
syn match   shCollSymb	'\[\..\+\.\]'	contained
syn match   shEquivClass	'\[=.\+=\]'	contained

if exists("b:is_bash")
  hi def link shCollSymb	shSpecial
  hi def link shEquivClass	shSpecial
else
  hi def link shCollSymb	Identifier
  hi def link shEquivClass	Identifier
endif
```

And a more thorough test case:

```bash
#!/bin/bash
# VIM_TEST_SETUP highlight link shRange Error

set +e +f
[ "$#" -gt 0 ] || exit 100
cd /tmp || exit 101
: > a

case "$1" in
[\ a-z]*)
    echo [!\ A-Z]
    ls [\ a-z]
    ls [!\ A-Z]
    ls [\ a-z]
    ls [" "[.a.]]
    ls [' '[=a=]]
    echo [a-z]
    ls [a-z]
    ;;
# Whitespace will be matched in the above branch.
[\ [:alnum:]]*)
    echo [\ [:alnum:]]
    ls [\ [:alnum:]]
    echo [[:alnum:]]
    ls [[:alnum:]]
    ;;
esac

echo [!\ A-Z]
ls [\ a-z]
ls [!\ A-Z]
ls [\ a-z]
ls [" "[.a.]]
ls [' '[=a=]]
echo [\ [:alnum:]]
ls [\ [:alnum:]]
echo [[:alnum:]]
ls [[:alnum:]]

:
```

**Comment by zzzyxwvut** [comment]
There is now a [PR](https://github.com/vim/vim/pull/15941) drafted for it.
