### ISSUE TITLE
Filetype sh.vim , ft-bash-syntax . Bad highlighting

### ISSUE THREAD

**Issue by freddieventura** [vim/vim#15793]
### Steps to reproduce

There is a conflictive line in the file below, the syntax highlighting seems to be breaking as the file executes with no errors, yet syntax show as if there was errors.
See the file as an example.

`./sh-highlighting-issue.sh`
Once you have it locally , call it the following way to see the output.
`./sh-highlighting-issue.sh -w "-c fakuve@192.168.43.241:22 -p /home/fakuve/files/downloads -d files" -w "-c fakuve@10.20.10.200:80 -p /home/fakuve/downloads -d /dev/vda1"`

Note the conflictive line is line **64** `read -r WORKER_CONNECTION_STRING WORKER_PATH WORKER_DISK <<< "$OUTPUT"`

```
#!/bin/bash
# ./sh-highlighting-issue.sh -w "-c fakuve@192.168.43.241:22 -p /home/fakuve/files/downloads -d files" -w "-c fakuve@10.20.10.200:80 -p /home/fakuve/downloads -d /dev/vda1"


while getopts "l:w:" opt; do
    case $opt in
        l)  # Byte limit
            BYTE_LIMIT=${OPTARG}
            ;;
        w)
            # Parse the worker parameters
            WORKER_PARAMS_ARRAY+=("$OPTARG")
            ;;
        *)  # Invalid option
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
    esac
done
OPTIND=1


parse_worker_params() {
    ## PARSING ARGUMENTS ---------------------------------
    ## ---------------------------------------------------
    local OPTIND=1
    # Initialize variables
    local WORKER_CONNECTION_STRING=""
    local WORKER_PATH=""
    local WORKER_DISK=""

    while getopts "c:p:d:" opt; do
        case "${opt}" in
            c) WORKER_CONNECTION_STRING="${OPTARG}" ;;
            p) WORKER_PATH="${OPTARG}" ;;
            d) WORKER_DISK="${OPTARG}" ;;
            *)
                echo "Usage: parse_worker_params -c WORKER_CONNECTION_STRING -p WORKER_PATH -d WORKER_DISK" >&2
                echo "Example: parse_worker_params -c WORKER_CONNECTION_STRING -p WORKER_PATH -d WORKER_DISK" >&2
                return 1
                ;;
        esac
    done
    # Variable check
    if [[ -z "${WORKER_CONNECTION_STRING}" || -z "${WORKER_PATH}" || -z "${WORKER_DISK}" ]]; then
        echo "Error: parse_worker_params requires -c WORKER_CONNECTION_STRING -p WORKER_PATH -d WORKER_DISK" >&2
        return 1
    fi
    ## PARSING ARGUMENTS ---------------------------------
    ## EOF EOF EOF EOF------------------------------------

    echo "${WORKER_CONNECTION_STRING} ${WORKER_PATH} ${WORKER_DISK}"
}

declare -a WORKER_CONNECTION_STRING_ARRAY
declare -a WORKER_PATH_ARRAY
declare -a WORKER_DISK_ARRAY

for WORKER_PARAMS in "${WORKER_PARAMS_ARRAY[@]}"; do
    # Capture the output in a temporary variable
    OUTPUT=$(parse_worker_params ${WORKER_PARAMS})

    # Read the output into the arrays
    read -r WORKER_CONNECTION_STRING WORKER_PATH WORKER_DISK <<< "$OUTPUT"

    # Append to the arrays
    WORKER_CONNECTION_STRING_ARRAY+=("$WORKER_CONNECTION_STRING")
    WORKER_PATH_ARRAY+=("$WORKER_PATH")
    WORKER_DISK_ARRAY+=("$WORKER_DISK")
done


# Print the captured arrays
for i in "${!WORKER_CONNECTION_STRING_ARRAY[@]}"; do
    echo "Worker Connection String: ${WORKER_CONNECTION_STRING_ARRAY[i]}"
    echo "Worker Path: ${WORKER_PATH_ARRAY[i]}"
    echo "Worker Disk: ${WORKER_DISK_ARRAY[i]}"
    echo "-------------------------"
done

```

### Expected behaviour

Characters shouldnt turn red right after that line

### Version of Vim

VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Sep 21 2024 15:03:13) Included patches: 1-709 Modified by team+vim@tracker.debian.org Compiled by team+vim@tracker.debian.org Huge version without GUI.  Features included (+) or not (-): +acl               +file_in_path      +mouse_urxvt       -tag_any_white +arabic            +find_in_path      +mouse_xterm       +tcl +autocmd           +float             +multi_byte        +termguicolors +autochdir         +folding           +multi_lang        +terminal -autoservername    -footer            -mzscheme          +terminfo -balloon_eval      +fork()            +netbeans_intg     +termresponse +balloon_eval_term +gettext           +num64             +textobjects -browse            -hangul_input      +packages          +textprop ++builtin_terms    +iconv             +path_extra        +timers +byte_offset       +insert_expand     +perl              +title +channel           +ipv6              +persistent_undo   -toolbar +cindent           +job               +popupwin          +user_commands -clientserver      +jumplist          +postscript        +vartabs -clipboard         +keymap            +printer           +vertsplit +cmdline_compl     +lambda            +profile           +vim9script +cmdline_hist      +langmap           -python            +viminfo +cmdline_info      +libcall           +python3           +virtualedit +comments          +linebreak         +quickfix          +visual +conceal           +lispindent        +reltime           +visualextra +cryptv            +listcmds          +rightleft         +vreplace +cscope            +localmap          +ruby              +wildignore +cursorbind        +lua               +scrollbind        +wildmenu +cursorshape       +menu              +signs             +windows +dialog_con        +mksession         +smartindent       +writebackup +diff              +modify_fname      +sodium            -X11 +digraphs          +mouse             -sound             +xattr -dnd               -mouseshape        +spell             -xfontset -ebcdic            +mouse_dec         +startuptime       -xim +emacs_tags        +mouse_gpm         +statusline        -xpm +eval              -mouse_jsbterm     -sun_workshop      -xsmp +ex_extra          +mouse_netterm     +syntax            -xterm_clipboard +extra_search      +mouse_sgr         +tag_binary        -xterm_save -farsi             -mouse_sysmouse    -tag_old_static    system vimrc file: "/etc/vim/vimrc"      user vimrc file: "$HOME/.vimrc"  2nd user vimrc file: "~/.vim/vimrc"  3rd user vimrc file: "~/.config/vim/vimrc"       user exrc file: "$HOME/.exrc"        defaults file: "$VIMRUNTIME/defaults.vim"   fall-back for $VIM: "/usr/share/vim" Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -Wdate-time -g -O2 -Werror=implicit-function-declaration -ffile-prefix-map=/build/reproducible-path/vim-9.1.0709=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -DSYS_VIMRC_FILE=\"/etc/vim/vimrc\" -DSYS_GVIMRC_FILE=\"/etc/vim/gvimrc\" -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 Linking: gcc -Wl,-E -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim -lm -ltinfo -lselinux -lsodium -lacl -lattr -lgpm -L/usr/lib -llua5.1 -Wl,-E -fstack-protector-strong -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu/perl/5.38/CORE -lperl -ldl -lm -lpthread -lcrypt -L/usr/lib/python3.12/config-3.12-x86_64-linux-gnu -lpython3.12 -ldl -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm -lruby-3.1 -lm -L/usr/lib

### Environment

5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 GNU/Linux

Debian Trixie

echo $TERM : tmux-256color

On 
Windows Terminal

/bin/bash
GNU bash, version 5.2.32(1)-release (x86_64-pc-linux-gnu)

**Comment by chrisbra** [comment]
can anybody replicate this with `vim --clean`?

**Comment by zzzyxwvut** [comment]
When the example is copy-pasted into *a new buffer*:

```sh
rm -f /tmp/sh-highlighting-issue.sh
vim --clean /tmp/sh-highlighting-issue.sh
```

`b:current` is set to `posix`, and `b:is_dash` and `b:is_posix`  
are defined, and the remainder of the file past the line:

```bash
    read -r WORKER_CONNECTION_STRING WORKER_PATH WORKER_DISK <<< "$OUTPUT"
```

is interpreted as a runaway here-document (no red colours).

HOWEVER, when the buffer is saved and `:edit`'d again (or  
re-opened), `b:current` is set to `bash`, and `b:is_bash` is  
defined, and there are no issues with `--clean` and without  
it for the Debian-packaged Vim version (`9.1.0709`).

On the other hand, there are no problems to begin with for:

```sh
rm -f /tmp/sh-highlighting-issue.bash
vim --clean /tmp/sh-highlighting-issue.bash
```
OR:

```
rm -f /tmp/sh-highlighting-issue
vim --clean /tmp/sh-highlighting-issue

# :setlocal ft=sh
```

Why did you name it `sh-highlighting-issue.sh` and neither    
`sh-highlighting-issue.bash` or `sh-highlighting-issue`?
The first line says Bash, yet the file extension implies _any  
shell_ script.
