### ISSUE TITLE
`nostartofline` option is ignored on some operators

### ISSUE THREAD

**Issue by lsvmello** [vim/vim#15794]
### Steps to reproduce

1. vim -u NONE
2. :set nostartofline
3. insert: "this line is a test"
4. Go to normal mode, position the cursor at the caracter "a"
5. press gUU

### Expected behaviour

The whole line should be captilized but the cursor position should remain the same.
There are some operators that considers `startofline` option and others that don't.

From the list of `:h operator` I noticed that:
- `dd` uses `nostartofline`
- `>>` uses `nostartofline`
- `<<` uses `nostartofline`
- `==` uses `nostartofline`
- `g~~` **does not** use `nostartofline`
- `guu` **does not** use `nostartofline`
- `gUU` **does not** use `nostartofline`
- `gqq` **does not** use `nostartofline`

### Version of Vim

VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Oct  1 2024 22:16:04)

### Environment

MS-Windows 64-bit GUI/console version with OLE support

### Logs and stack traces

_Not applicable_

**Comment by echasnovski** [comment]
There is also `g??`.

Most of this seems to be [intentional and documented](https://github.com/vim/vim/blob/075ab5ab3b8abc55baddce7105e22b6fa1b2e032/runtime/doc/motion.txt#L72-L74).

**Comment by chrisbra** [comment]
I have no intention to change this. So let's just clarify the current behaviour a bit better.
