### ISSUE TITLE
Support for Extended Globbing in Vim

### ISSUE THREAD

**Issue by girishji** [vim/vim#15791]
In `zsh` (for example), the `extendedglob` option allows for advanced file pattern matching, such as selectively excluding files or directories using patterns like `**/foo*~bar` (where `~` or `^` is used for exclusion). I attempted to enable this in Vim by setting `set shell=/bin/zsh\ -o\ extendedglob`, but it had no effect.

It seems Vim relies on the shell to resolve glob patterns, so I expected `zsh`'s extended globbing to work. However, this doesn't seem to be the case. For instance, while `find` supports recursive globbing with `**`, it doesn't recognize exclusion patterns like `**/foo*~bar`.

**Comment by chrisbra** [comment]
Try this one:
```diff
diff --git a/src/filepath.c b/src/filepath.c
index d514aaf8e..bbcb0c969 100644
--- a/src/filepath.c
+++ b/src/filepath.c
@@ -4012,7 +4012,7 @@ gen_expand_wildcards(
      * call the machine specific expansion function, if possible.  Otherwise,
      * return FAIL.
      */
-    if (recursive)
+    if (recursive || p_shxp)
 #ifdef SPECIAL_WILDCHAR
        return mch_expand_wildcards(num_pat, pat, num_file, file, flags);
 #else
diff --git a/src/option.h b/src/option.h
index ef39031aa..b0b029370 100644
--- a/src/option.h
+++ b/src/option.h
@@ -898,6 +898,7 @@ EXTERN unsigned     ssop_flags;
 #endif
 EXTERN char_u  *p_sh;          // 'shell'
 EXTERN char_u  *p_shcf;        // 'shellcmdflag'
+EXTERN int     p_shxp;         // 'shellexpand'
 #ifdef FEAT_QUICKFIX
 EXTERN char_u  *p_sp;          // 'shellpipe'
 #endif
diff --git a/src/optiondefs.h b/src/optiondefs.h
index 4a5bd638c..0f69251df 100644
--- a/src/optiondefs.h
+++ b/src/optiondefs.h
@@ -2218,6 +2218,9 @@ static struct vimoption options[] =
                            (char_u *)"-c",
 #endif
                                (char_u *)0L} SCTX_INIT},
+    {"shellexpand","shxp",  P_BOOL|P_VI_DEF|P_SECURE,
+                           (char_u *)&p_shxp, PV_NONE, NULL, NULL,
+                           {(char_u *)FALSE, (char_u *)0L} SCTX_INIT},
     {"shellpipe",   "sp",   P_STRING|P_VI_DEF|P_SECURE,
 #ifdef FEAT_QUICKFIX
                            (char_u *)&p_sp, PV_NONE, NULL, NULL,
```

And the set `:set shellexpand shellcmdflag=-c\ -o\ extendedglob`

**Comment by girishji** [comment]
Thank you for your suggestion! I found that `:find **/*~bar` works as expected, but that’s about the only success I’ve had. Features like `**/*~bar(.)` (for listing only files), `**/*~(foo|bar)`, the `^` operator, and other extended globbing options in zsh don’t seem to work. I’ve already set `shell=/bin/zsh`, so I anticipated that zsh would handle glob wildcard expansion, but that doesn’t appear to be the case.

Additionally, after measuring the performance, I noticed a significant slowdown with recursive glob expansion (`**`). For example, in the Vim source repository, there’s about a 1-second delay when listing files using `:find **/*`, whereas running the `find` program directly (outside of Vim) returns results almost instantaneously—within 30 milliseconds. I found similar type of performance gap when using `**` with `ls` or `zargs`. So, this is not a Vim issue.

Given the performance gap and limited functionality of extended globbing, I’m indifferent to adding this specific enhancement to Vim.

**Comment by benknoble** [comment]
> It seems Vim relies on the shell to resolve glob patterns, so I expected `zsh`'s extended globbing to work. However, this doesn't seem to be the case. For instance, while `find` supports recursive globbing with `**`, it doesn't recognize exclusion patterns like `**/foo*~bar`.

I don’t know that I think this is true; at least, I don’t think it uses `'shell'`, since then Zsh with `extendedglob` or similar options would enable more advanced globbing. I think (from memory, not code or docs) that the glob language supported by Vim is similar to (if not a small extension of) the one supported by the system `glob()` call.

**Comment by chrisbra** [comment]
let's close it then.

**Comment by bfrg** [comment]
Maybe the most flexible approach would be to add a new option `findprg`, similar to `makeprg` and `grepprg`, that is invoked when executing `:find`. This wouldn't require constant changes to the source code. Users could set it to default `find`, `fd`, `git ls-files`, etc.

**Comment by girishji** [comment]
> Maybe the most flexible approach would be to add a new option `findprg`, similar to `makeprg` and `grepprg`, that is invoked when executing `:find`. This wouldn't require constant changes to the source code. Users could set it to default `find`, `fd`, `git ls-files`, etc.

While I agree that the `findprg` option is an improvement, we already have the ability to use custom arguments with `find` or `fd` via `:h :command-completion-custom`. Personally, I prefer gathering all files once (using a separate job) and then applying fuzzy matching. This approach works smoothly even in large repositories. I've been exploring some of these techniques with [vimsuggest](https://github.com/girishji/vimsuggest), and it's been very effective.

**Comment by yegappan** [comment]
> Maybe the most flexible approach would be to add a new option `findprg`, similar to `makeprg` and `grepprg`, that is invoked when executing `:find`. This wouldn't require constant changes to the source code. Users could set it to default `find`, `fd`, `git ls-files`, etc.

Created the PR https://github.com/vim/vim/pull/15901 to add support for 'findprg'.
