### ISSUE TITLE
Comment toggling does not work correctly in files that use mixed tab and space indentation

### ISSUE THREAD

**Issue by julio-b** [vim/vim#15797]
### Steps to reproduce

1. `vim --clean -c 'packadd comment'`
2. Edit the following c file:
```c
int main(void) {
    if (1) {
	int q;
	printf("");
	return q;
    }
}
```
3. Jump to line 4 : `4G`
4. `gca{`

Result:
```c
int main(void) {
    /* if (1) { */
    /*  q; */
    /* ntf(""); */
    /* urn q; */
    /* } */
}
```

Notice how lines 3,5 are now messed up.

### Expected behaviour

Comment toggling should not change the indentation or modify the code in any way.
```c
int main(void) {
    /* if (1) { */
	/* int q; */
	/* printf(""); */
	/* return q; */
    /* } */
}
```

### Version of Vim

v9.1.0757

### Environment

OS: Archlinux
Shell: `bash 5.2.32`
Terminal: `kitty`
$TERM: `xterm-kitty`

**Comment by chrisbra** [comment]
oh, that is nasty. @habamax ?

**Comment by habamax** [comment]
Will have a look next week. 

This is quite strange, I have used it quite a lot with vim’s source code which has mixed indentation and it never did this.

**Comment by habamax** [comment]
While I am away, could anyone check with the original comment pack before it was changed by @Konfekt ?

**Comment by Konfekt** [comment]
Since these are surrounding comment markers, the added if-block is not entered:

https://github.com/vim/vim/blob/40c6babc1789aceb241b23bab76eea16da37e33d/runtime/pack/dist/opt/comment/autoload/comment.vim#L26

However, `strlen()` in

```vim
# pack/dist/opt/comment/autoload/comment.vim (lines 62-63)
line = printf(indent_start .. substitute(cms, '%s\@!', '%%', 'g'),
        strpart(getline(lnum), strlen(indent_start)))
```

is too aggressive here as for`2gcc` on line 2  we've `strlen(indent_start) = 4` by the initial indent of 4 spaces, but in the following line there are only two tab characters.
Here's a try to remove only one tab for every multiple of `&tabstop` many spaces:

```vim
                line = getline(lnum)
                var ind_len = strlen(matchstr(line, '^\s*'))
                line = printf(indent_start .. substitute(cms, '%s\@!', '%%', 'g'),
                        strpart(line, (line[0 : strlen(indent_start) - 1] =~ '\t' ? ind_len / &tabstop : ind_len)))
```

**Comment by habamax** [comment]
thx @Konfekt !

**Comment by chrisbra** [comment]
Actually, it would be good, if we could create some test cases for the comment plugin :)

**Comment by habamax** [comment]
Yes, it makes sense. Will look into it.

**Comment by habamax** [comment]
It now has another issue with tabs

https://asciinema.org/a/HV9Jor5lkAnaVJKaUIEyRHhmW

```
func _unhandled_key_input(event):
	if event.is_action_pressed("toggle_fullscreen"):
		OS.window_fullscreen = !OS.window_fullscreen
	elif event.is_action_pressed("quit"):
		Status.save_game()
		get_tree().quit()
```

toggle comment on `OS.window_fullscree = ...` line where filetype is `gdscript`.
