### ISSUE TITLE
Unexpected `Using a Number as a Bool: 2` raised

### ISSUE THREAD

**Issue by heavenshell** [vim/vim#15806]
### Steps to reproduce

1. Starup with following vimrc
```vim
vim9script

set nocompatible

language message C
language time C

def g:Mapping(): string
  if search('^abc', 'bcn', line('.'))
    return "\<SPACE>def"
  endif

  return "\<SPACE>"
enddef

inoremap <silent> <buffer> <space> <C-R>=g:Mapping()<CR>
```
2. type `abc<SPACE>` and ` def` will automatically insert.
3. Moving on to the second line
4. type `abc<SPACE>` raise following error
```
Error detected while processing function Mapping:
line    1:
E1023: Using a Number as a Bool: 2
```

https://github.com/user-attachments/assets/58073ef6-fcac-431e-a5d8-be76b05c4e70

### Expected behaviour

If I use legacy Vim script, it works(The same result is executed for the second line).
```vim
set nocompatible

language message C
language time C

function! g:Mapping()
  if search('^abc', 'bcn', line('.'))
    return "\<SPACE>def"
  endif
    
  return "\<SPACE>"
endfunction
  
inoremap <silent> <buffer> <space> <C-R>=g:Mapping()<CR>
```

https://github.com/user-attachments/assets/ebbd6f31-9619-42fe-85a3-c3bd757a3538

### Version of Vim

9.1.758

### Environment

OS: macOS
terminal: Terminal.app
value of $TERM: xterm-256color
shell: zsh 5.9 (arm-apple-darwin21.3.0)

**Comment by zeertzjq** [comment]
See `:h vim9-boolean`
```
vim9script

set nocompatible

language message C
language time C

def g:Mapping(): string
  if search('^abc', 'bcn', line('.'))
    return "\<SPACE>def"
  endif

  return "\<SPACE>"
enddef

inoremap <silent> <buffer> <space> <C-R>=g:Mapping()<CR>
```

`search()` returns a line number, so you need to use `search('^abc', 'bcn', line('.')) > 0` as the condition.

**Comment by heavenshell** [comment]
@zeertzjq Thank you!
ah, I Understoot. But Why isn't the first line an error?

**Comment by zeertzjq** [comment]
On the first line it returns `1`, which is allowed.

**Comment by heavenshell** [comment]
Ah, totally understood. Thank you so much!
