### ISSUE TITLE
Sometimes `{` in insert mode triggers normal mode

### ISSUE THREAD

**Issue by gveezz** [vim/vim#15822]
### Steps to reproduce

From insert mode, sometimes `{` is interpreted as `^[``, thus triggering normal mode.

### Expected behaviour

From insert mode, `{` should insert `{`, always.

### Version of Vim

9.1.0764

### Environment

Linux

**Comment by chrisbra** [comment]
Well that doesn't give much details. What keyboard layout? Is this terminal or GUI? what happens if you type in insert mode `<C-S-V>{`? does it happen with `vim --clean`?

**Comment by simo-zz** [comment]
> Well that doesn't give much details. What keyboard layout? Is this terminal or GUI? what happens if you type in insert mode `<C-S-V>{`? does it happen with `vim --clean`?

It happens also with `vim --clean`

In vim (no GUI), with `<C-S-V>{` it pasts the content of what I had in the clipboard and inserts `}`.
In insert mode, `<C-v>{` sometimes inserts `}`, sometimes it shows `^[`.

Keyboard layout screenshot:
![image](https://github.com/user-attachments/assets/8b1daef2-7234-4ba0-9e90-ccf483a2ebbc)
