### ISSUE TITLE
verymagic (`\v`) affects start-of-word and end-of-word atoms `\<` and `\>`

### ISSUE THREAD

**Issue by intelfx** [vim/vim#15831]
### Steps to reproduce

Expression                                  | Output
-------------------------------------------:|:------
`:echo 'thing is foobar' =~ '\<foobar\>'`   | `1`
`:echo 'thing is foobar' =~ '\v\<foobar\>'` | `0`
`:echo 'thing is foobar' =~ '\v<foobar>'`   | `1`

### Expected behaviour

Expression                                  | Output
-------------------------------------------:|:------
`:echo 'thing is foobar' =~ '\<foobar\>'`   | `1`
`:echo 'thing is foobar' =~ '\v\<foobar\>'` | `1`
`:echo 'thing is foobar' =~ '\v<foobar>'`   | `0`

### Version of Vim

VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Sep 22 2024 18:40:20) Included patches: 1-740

### Environment

Operating system: Arch Linux

### Clarification

[`:help /ordinary-atom`](https://vimhelp.org/pattern.txt.html#%2Fordinary-atom) draws no distinction between magic levels for the `\<` and `\>` atoms, yet verymagic seems to change `\<` and `\>` into `<` and `>`.

**Comment by k-takata** [comment]
This is the expected behavior. See `:help /\v`.
The "/ordinary-atom" table shows magic (`\m`) and nomagic (`\M`), not about very (no)magic.
