### ISSUE TITLE
Extraneous character shown in editor

### ISSUE THREAD

**Issue by DarkTyger** [vim/vim#15849]
### Steps to reproduce

1. Save the following as "index.html":
```
ss*=language-]{color:#ccc;background:0 0;font-family:Consolas,Monaco,'Andale Mono','Ubuntu Mono',monospace;font-size:1em;text-align:left;white-space:pre;word-spacing:normal;word-break:normal;word-wrap:normal;line-height:1.5;-moz-tab-size:4;-o-tab-size:4;tab-size:4;-webkit-hyphens:none;-moz-hyphens:none;-ms-hyphens:none;hyphens:none}pre[class*=language-]{color:#ccc;font-family:Consolas,Monaco,'Andale Mono','Ubuntu Mono',monospace;font-size:1em;text-align:left;white-space:pre;word-spacing:normal;word-break:normal;word-wrap:normal;line-height:1.5;-moz-tab-size:4;-o-tab-size:4;tab-size:4;-webkit-hyphens:none;-moz-hyphens:none;-ms-hyphens:none;hyphens:none;padding:1em;margin:.5em 0;overflow:auto}:not(pre)>code[class*=language-],pre[class*=language-]{background:#2d2d2d}:not(pre)>code[class*=language-]{padding:.1em;border-radius:.3em;white-space:normal}.token.block-comment,.token.cdata,.token.comment,.token.doctype,.token.prolog{color:#999}.token.punctuation{color:#ccc}.token.attr-name,.token.deleted,.token.namespace,.token.tag{color:#e2777a}.token.function-name{color:#6196cc}.token.boolean,.token.function,.token.number{color:#f08d49}.token.class-name,.token.constant,.token.property,.token.symbol{color:#f8c555}.token.atrule,.token.builtin,.token.important,.token.keyword,.token.selector{color:#cc99cd}.token.attr-value,.token.char,.token.regex,.token.string,.token.variable{color:#7ec699}.token.entity,.token.operator,.token.url{color:#67cdcc}.token.bold,.token.important{font-weight:700}.token.italic{font-style:italic}.token.entity{cursor:help}.token.inserted{color:green}a.rss>img{float:left;border:none!important;outline:none!important;height:1.25em;line-height:1.25em;margin-right:.25em}  </style><link type="application/rss+xml" rel="alternate" href="/dave/news/blog.rss" title="RSS Blog"><link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16.png"><link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32.png"><link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon.png"><link rel="manifest" href="/images/site.webmanifest"><meta name="msapplication-TileColor" content="#da532c"><meta name="theme-color" content="#ffffff"></head><body><main><header><nav><ul><li><a href="/">Home</a></li><li><a href="/blog">Blog</a></li><li class="toc"><button class="toc" aria-label="Contents">☰ Contents</button><nav class='toc'></nav>
```
2. Edit the file in vim using a terminal window set to 80x50.
3. Note the output.

Output contains, erroneously:

`<nav class='toc'></navv>`

Output looks like, erroneously:

![vim-index](https://github.com/user-attachments/assets/511e39a0-4219-464d-abab-ffa414174005)

### Expected behaviour

The file is shown ending with `</nav>`, not `</navv>`.

Note that the `</navv>` is copyable, too, despite the file not having `navv` anywhere in its contents.

### Version of Vim

VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Sep 22 2024 18:40:20)

### Environment

$ uname -a
Linux hostname 6.10.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 12 Sep 2024 17:21:02 +0000 x86_64 GNU/Linux

**Comment by zeertzjq** [comment]
`:call setcellwidths([[0x2630, 0x2630, 1]])` seems to solve the problem.

**Comment by zeertzjq** [comment]
Characters `0x2630` to `0x2637` have just been changed from single-width to double-width in Unicode 0.16.0.

> Changed 2630..2637, 268A..268F, 4DC0..4DFF, 1D300..1D356, and 1D360..1D376 from N to W to better align with actual use in font implementations.

Vim is using 0.16.0, so Vim treats these characters as double-width. Many terminals may be using an older Unicode version.

**Comment by DarkTyger** [comment]
https://docs.xfce.org/apps/terminal/

Xfce Terminal Emulator v1.1.3

**Comment by chrisbra** [comment]
Well, this means that XFCE and possibly gnome related libraries are involved and may contradict with what Vim thinks of those characters. This is generally complicated since all libraries should ideally have the same understanding of the Unicode Properties, which seems like we have some contradiction here. Please use the work around mentioned  [abvoe](https://github.com/vim/vim/issues/15849#issuecomment-2406396157).

Thanks, closing as not being actionable here for Vim.
