### ISSUE TITLE
Invalid syntax highlighting inside string literals - it detects /* as a starting line for a comment

### ISSUE THREAD

**Issue by simoncpu** [vim/vim#1584]
![examplejs](https://cloud.githubusercontent.com/assets/128593/24188811/b74f1c68-0f1d-11e7-856c-2c1f19b44564.png)

Copy-pasteable:

    const init_env =` 
        for i in \`ls ${process.env['LAMBDA_TASK_ROOT']}/bin/*\`; do
            echo $i
        done
    `;

**Comment by chrisbra** [comment]
I guess this can then also be closed.

**Comment by vim-ml** [comment]
On Wed, Mar 29, 2017 at 4:07 PM, Charles E Campbell
<drchip@campbellfamily.biz> wrote:
> Simon Cornelius P. Umacob wrote:
>>
>> examplejs
>> <https://cloud.githubusercontent.com/assets/128593/24188811/b74f1c68-0f1d-11e7-856c-2c1f19b44564.png>
>>
>> Copy-pasteable:
>>
>> |const init_env =` for i in \`ls
>> ${process.env['LAMBDA_TASK_ROOT']}/bin/*\`; do echo $i done `; |
>>
> Hello:
>
> Some questions for you...
>
>  * what language is this for?
>  * I don't even see a /* in the example, so I don't see how that could
> be affecting the highlighting

There is /*\ at the end of the backtick-quoted text, but AFAICT it is
not within single- or double-quoted text. That /*\ and everything
following it are highlighted in blue.

>  * have you tried contacting the maintainer of the syntax highlighting
> supporting whatever language you're using?  (look into the syntax
> highlighting file, you'll likely find a "Maintainer" comment therein)
>
> Regards,
> Chip Campbell
>
Best regards,
Tony.
