### ISSUE TITLE
Comments for Gleam language

### ISSUE THREAD

**Issue by trilowy** [vim/vim#15864]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
In a *.gleam file, it is not possible to comment lines.

**Describe the solution you'd like**
I want to be able to comment one or multiple lines with `//` at the start of the line, as described in the [language doc](https://tour.gleam.run/functions/documentation-comments/).

**Describe alternatives you've considered**
@lampewebdev tried to add it in a [Neovim PR](https://github.com/neovim/neovim/pull/30691) but it has been recommended to add it in vim directly. I’ll open a PR as soon as I get familiar with how to contribute to vim.

**Comment by chrisbra** [comment]
If you are going to create a PR anyhow, there is no reason for a separate issue really.
