### ISSUE TITLE
Cannot some mapping on Linux CUI vim.

### ISSUE THREAD

**Issue by mikoto2000** [vim/vim#15860]
### Steps to reproduce

1. curl -L https://github.com/vim/vim-appimage/releases/download/v9.1.0777/Vim-v9.1.0777.glibc2.29-x86_64.AppImage -O
2. chmod +x Vim-v9.1.0777.glibc2.29-x86_64.AppImage
3. ./Vim-v9.1.0777.glibc2.29-x86_64.AppImage --appimage-extract-and-run -u NONE -N
4. execute command `:nnoremap <A-S-f> :echo "aaa"<Enter>`
5. put key `<A-S-f>` but no effect
    *  † but, execute `nnoremap`, found `<M-F>` mapping.

### Expected behaviour

Can mapping `<A-*>`

### Version of Vim

9.1.0777 (vim/vim-appimage)

### Environment

OS: Ubuntu 24.04(on WSL2)
Terminal: Windows Terminal, mintty
$TERM: xterm-256color
SHELL: bash 5.2.21

OS: Ubuntu 24.04(on Hyper-V)
Terminal: GNOME Terminal
$TERM: xterm-256color
SHELL: bash 5.2.21

### Logs and stack traces

```shell
no stack traces
```

**Comment by mikoto2000** [comment]
vim-win32-installer's vim(GUI and CUI) is available `<A-S-f>` mapping.

**Comment by mikoto2000** [comment]
The same issue occurred with v9.1.0.

**Comment by mikoto2000** [comment]
The same thing happened with `<C-.>`.

**Comment by chrisbra** [comment]
That typically depends on the capabilities of your terminal. With xterm you can make use of xterm-modifier-keys and with kitty you can make use of the kitty protocol. But note that such key combinations tend not to be universally portable across different systems.

**Comment by mikoto2000** [comment]
@chrisbra 
Thank you for your comment.
I understand that the problem is caused by the terminal application.
I will try to find a working terminal.
