### ISSUE TITLE
Feature request: syntax highlighting for hyprland.conf and for hyprlang in general

### ISSUE THREAD

**Issue by TAforever** [vim/vim#15875]
It would be nice if someone would add syntax highlighting for hyprland  configuration files. Hyprland is a popular tiling wayland compositor
https://github.com/hyprwm/Hyprland

**Comment by chrisbra** [comment]
Here is your chance to contribute :)

**Comment by TAforever** [comment]
> Here is your chance to contribute :)

I'd love to contribute, but unfortunately I'm not good at it
