### ISSUE TITLE
Feature Request: Add command/function to termdebug which opens popup window with evaluation result of <cword>

### ISSUE THREAD

**Issue by BigPeet** [vim/vim#15877]
When debugging and evaluating variables, I want to see a nice view of structs and their fields.
Moving the cursor over an expression and executing ":Evaluate" will get me the information I need, but it gets truncated if it does not fit into a single line.
To get the full information, you need to check ":messages".

Termdebug already supports opening a "balloon" window, when hovering with the mouse over expressions.
In that balloon window, the output is formatted nicely.
But as far as I can tell, there is no easy way to configure a balloon or popup window using the regular cursor, e.g. via a CursorHold event.

I thought this could be achieved by simply calling `popup_atcursor(execute(':Evaluate ' . expand('<cword>')))` or something similar. But `:Evaluate` will actually perform the request async, and the callback's output with the evaluation result will not be caught by `execute()`.

I'm mostly using the keyboard for navigating and it would be nice, if there was better support for it.

What I would like is a command (or function) which

1. Evaluates `<cword>` (or an argument)
2. Takes the response from GDB and write it into a popup_atcursor() window, similar to how the balloon already does it.

Alternative approaches (which would also work for me):

* The command/function takes a user-provided callback which takes GDB's (formatted) response as parameter.
   This would be more flexible, but less "out-of-the-box".
* Instead of adding a new command, this behavior is simply added to termdebug. I.e. an autocmd is added which on CursorHold will perform the actions described above to open a popup window. This can be activated/deactivated with an option. This would involve less tinkering for users, but also offers less flexibility.

If this is deemed a good addition and it is clear which approach makes the most sense, I could likely provide a PR for this feature myself (with some input and feedback provided).

**Comment by ubaldot** [comment]
It sounds like a good addition. However, I would just show the popup once user explicitly call :Evaluate. 

In his/her .vimrc user can run this command in a CursorHold auto-command I think as a first step, so we don't spoil old users experience, unless there is a large request for embedding such a CursorHold autocmd in Termdebug which is activated through a config item, see next. 

g:termdebug_config should have an additional key to show the evaluation result as it is now or in the popup. Something like g:termdebug_config['evaluate_in_popup'] (feel free to pick a more coincise name).  This could also enable the CursorHold autocmd as discussed above. 

@chrisbra what do you think?

**Comment by chrisbra** [comment]
Sure, sounds like a nice addition.

**Comment by ubaldot** [comment]
@BigPeet Would you mind to send a PR and mention me there, please?

**Comment by BigPeet** [comment]
@ubaldot I will do that.
