### ISSUE TITLE
Allow jinja syntax to be used as a secondary filetype

### ISSUE THREAD

**Issue by stasjok** [vim/vim#15880]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
Jinja syntax doesn't work for dotted filetypes like `conf.jinja`, `sshconfig.jinja`, `nginx.jinja` etc. Probably because of this piece of code:

```vim
if exists('b:current_syntax')
    finish
endif
```

Is there a workaround for this case?

**Describe the solution you'd like**
Allow jinja syntax to be sourced as a secondary filetype (even when `b:current_syntax` is already defined).

**Additional context**
Jinja usually is used as a template engine, so it's natural to set dotted filetypes for it. Jinja syntax was added recently in #15689.

**Comment by chrisbra** [comment]
ping @gpanders

**Comment by chrisbra** [comment]
fixed by 5e53fca76fd991d64d83429d74b573cc73116d66
