### ISSUE TITLE
Test suite failing with Vim 9.1.0738

### ISSUE THREAD

**Issue by ChaseKnowlden** [vim/vim#15909]
### Steps to reproduce

1. Run ./configure --prefix=/usr
2. Run make
3. Run make test
4. The test suite fails

### Expected behaviour

All tests pass

### Version of Vim

9.1.0738

### Environment

Operating System: Linux from scratch
Terminal: Konsole
TERM: xterm-256color
Shell: Bash

### Logs and stack traces
[vim-test.log](https://github.com/user-attachments/files/17467803/vim-test.log)

**Comment by zeertzjq** [comment]
Try running `:echo has('fname_case')` in Vim. What does it print?

**Comment by zeertzjq** [comment]
Oh wait, this has already been fixed. Please use a newer version.
