### ISSUE TITLE
shellescape() should not always precede newlines with a backslash

### ISSUE THREAD

**Issue by HarmtH** [vim/vim#1590]
If we create a variable with a newline:
```
let var="a\nb"
```
Then ```shellescape(var)``` will return the following:
```
'a\
b'
```
When used together with ```system()```, this backslash will be seen by the command that is ran with ```system()```, which seems incorrect.

For example:
```
touch a$'\n'b
vim
:let var="a\nb"
:echo system('ls -l '.shellescape(var))
>> ls: cannot access 'a\'$'\n''b': No such file or directory
```
When used with ```!``` instead of ```system()```, it works correctly:
```
:exe '!ls -l' shellescape(var)
>> -rw-r--r-- 1 harmth harmth 0 mrt 22 22:06 a?b
```

If I understand correctly ```shellescape(x)``` should be used for ```system()```, while ```shellescape(x,1)``` should be used for ```!```, so I guess the prepending of the backslash before a newline should be moved to the ```shellescape(x,1)``` part of the code.

The documentation does describe current behaviour as correct, so if this isn't a bug, can somebody please enlighten me why the current behaviour is preferred.

**Comment by HarmtH** [comment]
Tested with ```GNU bash, version 4.3.46(1)-release``` and with ```zsh 5.2``` on ```vim 8.0.502```

**Comment by chrisbra** [comment]
Hm, so when I read the code correctly and I understand your problem correctly, the newline should only be escaped when using `{special}`?
So [this patch](https://gist.github.com/chrisbra/2ab6f18365c6e7d4f291c6a0a49b82f2) should fix it, right?

**Comment by HarmtH** [comment]
The patch indeed seems to fix the issue for me with zsh and bash. Thanks! I don't know how it will behave in other shells.

**Comment by HarmtH** [comment]
Just noticed that the documentation (https://github.com/vim/vim/blob/f085f4266e07b36279c56d43fd0d73ed080046ae/runtime/doc/eval.txt#L7107) still describes the old behaviour. Can this be fixed as well?

**Comment by brammool** [comment]
Harm te Hennepe wrote:

> Just noticed that the documentation (https://github.com/vim/vim/blob/f085f4266e07b36279c56d43fd0d73ed080046ae/runtime/doc/eval.txt#L7107) still describes the old behaviour. Can this be fixed as well?

Will be in the next runtime file update.

-- 
Don't Panic!
		-- The Hitchhiker's Guide to the Galaxy

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
