### ISSUE TITLE
`wrapscan` is NOT ignored for `complete=.` if `completeopt` contains `fuzzy`

### ISSUE THREAD

**Issue by phouchg42** [vim/vim#15937]
### Steps to reproduce

Help for `complete` option `.` notes *“scan the current buffer ('wrapscan' is ignored)”* but `wrapscan` is not ignored when you have `nowrapscan` **and** `completeopt+=fuzzy`

1. `:set nowrapscan completeopt+=fuzzy`
2. insert `abcd`
3. on next line insert `ab` and press `<C-N>`
4. nothing happened

### Expected behaviour

Should be completed to `abcd`.

If you `:set wrapscan` **or** `:set completeopt-=fuzzy` everything is fine.

### Version of Vim

9.1.785

### Environment

OS: Arch Linux
Terminal: GNOME Console 47.1

**Comment by chrisbra** [comment]
ping @glepnir

**Comment by glepnir** [comment]
reproduced thanks for report

**Comment by phouchg42** [comment]
After that go to Insert mode and press `<C-N>`: `ab` should complete to `abcd` but it’s not.

Sorry. Maybe I wasn’t clear. *“Scan the current buffer ('wrapscan' is ignored)”* in Help means you can complete a word with already existing word in your file, above or below the cursor. With `nowrapscan` **and** `completeopt+=fuzzy` you can complete only with a word **below.** Remove `completeopt+=fuzzy` and everything works as expected. So *“'wrapscan' is ignored”* is NOT ignored for `fuzzy`.

**Comment by phouchg42** [comment]
Found! I have `set complete-=i`. Without it everything is fine.

**Comment by phouchg42** [comment]
But it is still a bug, right?

`wrapscan` is ignored for `cpt` option `.` if
```
set nowrapscan
set complete-=i
```
or
```
set complete-=i
set completeopt+=fuzzy
```
but not ignored if
```
set nowrapscan
set complete-=i
set completeopt+=fuzzy
```

**Comment by glepnir** [comment]
i feel like it is. but I need to be away for a few days and will be back in front of the computer on the 29th. sry please wait few days ...

**Comment by glepnir** [comment]
I have fixed it in my new pr that use new option to control the fuzzy collection of default completion mode.  after finished i will create it and mark as fix this issue .

**Comment by W3W-EdU** [comment]
> ### Steps to reproduce
> Help for `complete` option `.` notes _“scan the current buffer ('wrapscan' is ignored)”_ but `wrapscan` is not ignored when you have `nowrapscan` **and** `completeopt+=fuzzy`
> 
> 1. `:set nowrapscan completeopt+=fuzzy`
> 2. insert `abcd`
> 3. on next line insert `ab` and press `<C-N>`
> 4. nothing happened
> 
> ### Expected behaviour
> Should be completed to `abcd`.
> 
> If you `:set wrapscan` **or** `:set completeopt-=fuzzy` everything is fine.
> 
> ### Version of Vim
> 9.1.785
> 
> ### Environment
> OS: Arch Linux Terminal: GNOME Console 47.1
> 
> ### Logs and stack traces
> _No response_

transmission

**Comment by glepnir** [comment]
duplicate #15296
