### ISSUE TITLE
Query on test Test_visual_getregion in test_visual.vim

### ISSUE THREAD

**Issue by basilisk0315** [vim/vim#15943]
Hi all,

When running the above test I am getting this result:
`From test_visual.vim:
Found errors in Test_visual_getregion():
command line..script /home/john/vim_dev/linux/vim/src/testdir/runtest.vim[607]..function RunTheTest[57]..Test_visual_getregion[387]..<SNR>10_CheckLegacyAndVim9Success[1]..<SNR>10_CheckTransLegacySuccess[10]..<SNR>10_CheckLegacySuccess[7]..Func line 233: Expected [[[56, 1, 3, 0], [56, 1, 4, 0]], [[56, 2, 1, 0], [56, 2, 4, 0]], [[56, 3, 1, 0], [56, 3, 6, 2]]] but got [[[56, 1, 3, 0], [56, 1, 3, 0]], [[56, 2, 1, 0], [56, 2, 3, 0]], [[56, 3, 1, 0], [56, 3, 6, 2]]]
command line..script /home/john/vim_dev/linux/vim/src/testdir/runtest.vim[607]..function RunTheTest[57]..Test_visual_getregion[387]..<SNR>10_CheckLegacyAndVim9Success[1]..<SNR>10_CheckTransLegacySuccess[10]..<SNR>10_CheckLegacySuccess[7]..Func line 245: Expected [[[56, 1, 0, 0], [56, 1, 0, 0]], [[56, 2, 1, 0], [56, 2, 3, 0]], [[56, 3, 1, 0], [56, 3, 5, 0]]] but got [[[56, 1, 0, 0], [56, 1, 3, 0]], [[56, 2, 1, 0], [56, 2, 3, 0]], [[56, 3, 1, 0], [56, 3, 5, 0]]]
command line..script /home/john/vim_dev/linux/vim/src/testdir/runtest.vim[607]..function RunTheTest[57]..Test_visual_getregion[387]..<SNR>10_CheckLegacyAndVim9Success[1]..<SNR>10_CheckTransLegacySuccess[10]..<SNR>10_CheckLegacySuccess[7]..Func line 251: Expected [[[56, 1, 4, 0], [56, 1, 4, 0]], [[56, 2, 1, 0], [56, 2, 4, 0]], [[56, 3, 1, 0], [56, 3, 6, 2]]] but got [[[56, 1, 4, 0], [56, 1, 3, 0]], [[56, 2, 1, 0], [56, 2, 3, 0]], [[56, 3, 1, 0], [56, 3, 6, 2]]]
command line..script /home/john/vim_dev/linux/vim/src/testdir/runtest.vim[607]..function RunTheTest[57]..Test_visual_getregion[387]..<SNR>10_CheckLegacyAndVim9Success[2]..<SNR>10_CheckTransDefSuccess[1]..<SNR>10_CheckDefSuccess[7]..Func line 233: Expected [[[58, 1, 3, 0], [58, 1, 4, 0]], [[58, 2, 1, 0], [58, 2, 4, 0]], [[58, 3, 1, 0], [58, 3, 6, 2]]] but got [[[58, 1, 3, 0], [58, 1, 3, 0]], [[58, 2, 1, 0], [58, 2, 3, 0]], [[58, 3, 1, 0], [58, 3, 6, 2]]]
command line..script /home/john/vim_dev/linux/vim/src/testdir/runtest.vim[607]..function RunTheTest[57]..Test_visual_getregion[387]..<SNR>10_CheckLegacyAndVim9Success[2]..<SNR>10_CheckTransDefSuccess[1]..<SNR>10_CheckDefSuccess[7]..Func line 245: Expected [[[58, 1, 0, 0], [58, 1, 0, 0]], [[58, 2, 1, 0], [58, 2, 3, 0]], [[58, 3, 1, 0], [58, 3, 5, 0]]] but got [[[58, 1, 0, 0], [58, 1, 3, 0]], [[58, 2, 1, 0], [58, 2, 3, 0]], [[58, 3, 1, 0], [58, 3, 5, 0]]]
command line..script /home/john/vim_dev/linux/vim/src/testdir/runtest.vim[607]..function RunTheTest[57]..Test_visual_getregion[387]..<SNR>10_CheckLegacyAndVim9Success[2]..<SNR>10_CheckTransDefSuccess[1]..<SNR>10_CheckDefSuccess[7]..Func line 251: Expected [[[58, 1, 4, 0], [58, 1, 4, 0]], [[58, 2, 1, 0], [58, 2, 4, 0]], [[58, 3, 1, 0], [58, 3, 6, 2]]] but got [[[58, 1, 4, 0], [58, 1, 3, 0]], [[58, 2, 1, 0], [58, 2, 3, 0]], [[58, 3, 1, 0], [58, 3, 6, 2]]]
command line..script /home/john/vim_dev/linux/vim/src/testdir/runtest.vim[607]..function RunTheTest[57]..Test_visual_getregion[387]..<SNR>10_CheckLegacyAndVim9Success[3]..<SNR>10_CheckTransVim9Success[1]..<SNR>10_CheckScriptSuccess[6]..script /home/john/vim_dev/linux/vim/src/testdir/XScriptSuccess3 line 234: Expected [[[60, 1, 3, 0], [60, 1, 4, 0]], [[60, 2, 1, 0], [60, 2, 4, 0]], [[60, 3, 1, 0], [60, 3, 6, 2]]] but got [[[60, 1, 3, 0], [60, 1, 3, 0]], [[60, 2, 1, 0], [60, 2, 3, 0]], [[60, 3, 1, 0], [60, 3, 6, 2]]]
command line..script /home/john/vim_dev/linux/vim/src/testdir/runtest.vim[607]..function RunTheTest[57]..Test_visual_getregion[387]..<SNR>10_CheckLegacyAndVim9Success[3]..<SNR>10_CheckTransVim9Success[1]..<SNR>10_CheckScriptSuccess[6]..script /home/john/vim_dev/linux/vim/src/testdir/XScriptSuccess3 line 246: Expected [[[60, 1, 0, 0], [60, 1, 0, 0]], [[60, 2, 1, 0], [60, 2, 3, 0]], [[60, 3, 1, 0], [60, 3, 5, 0]]] but got [[[60, 1, 0, 0], [60, 1, 3, 0]], [[60, 2, 1, 0], [60, 2, 3, 0]], [[60, 3, 1, 0], [60, 3, 5, 0]]]
command line..script /home/john/vim_dev/linux/vim/src/testdir/runtest.vim[607]..function RunTheTest[57]..Test_visual_getregion[387]..<SNR>10_CheckLegacyAndVim9Success[3]..<SNR>10_CheckTransVim9Success[1]..<SNR>10_CheckScriptSuccess[6]..script /home/john/vim_dev/linux/vim/src/testdir/XScriptSuccess3 line 252: Expected [[[60, 1, 4, 0], [60, 1, 4, 0]], [[60, 2, 1, 0], [60, 2, 4, 0]], [[60, 3, 1, 0], [60, 3, 6, 2]]] but got [[[60, 1, 4, 0], [60, 1, 3, 0]], [[60, 2, 1, 0], [60, 2, 3, 0]], [[60, 3, 1, 0], [60, 3, 6, 2]]]`

Does anyone know what the numbers mean?
I think they are text lengths but I am hoping that someone can confirm that.

Thanks
John

**Comment by zeertzjq** [comment]
See `:h getregionpos()`

**Comment by basilisk0315** [comment]
Ah of course! Stupid me.

Thanks!
