### ISSUE TITLE
Color column shifted when multibyte virtual text

### ISSUE THREAD

**Issue by matrdr** [vim/vim#15946]
### Steps to reproduce

I use lsp for Vim 9 (https://github.com/yegappan/lsp) and use the virtual text to display errors and warnings. The default option is that these messages are shown above the affected line. To signify that the lsp, by default, uses the characters `┌─`.

This shifts the color column two characters to the right as you see in this screenshot:

![image](https://github.com/user-attachments/assets/c6a67f1b-16d3-4322-9bd8-9bce07bb127a)

When these characters (or other multi byte characters) are encountered in normal (non-virtual) text, the color column seems to behave correctly.

I cannot say that this is 100% vim's fault, it could also be a mistake in the implementation of lsp. But as I assume lsp just uses vim's API to show virtual text the bug could very well also be inside vim.

### Expected behaviour

I would expect the color column to remain in the correct place no matter the characters used in the line. Alternatively, the color column could also just be deactivated for lines that only contain virtual text.

### Version of Vim

9.1.813

### Environment

I tired the version from APT on Ubuntu 24.04 (vim 9.1) as well as the newest available build available for Windows. On Windows I had the same issue in the terminal as well as in gvim.

**Comment by zeertzjq** [comment]
Is it "above" virtual text?

**Comment by matrdr** [comment]
Yes! That was quick! 😮
