### ISSUE TITLE
Repeat buffer gets overwritten when using SCP in netrw

### ISSUE THREAD

**Issue by dctucker** [vim/vim#15958]
### Steps to reproduce

1. Load a file via SCP
2. `:Vex` and select another file and then press `<CR>`. **Notice no syntax highlighting.**
3. `Vyp` to duplicate current line.
4. `.` to duplicate current line again. **Notice user is sent to `:` command mode with the SCP URL and paste buffer preloaded.**

This appears to be a regression of https://github.com/vim/vim/issues/12990 despite no change to the line of code that was intended to resolve this previous issue.

### Expected behaviour

1. Initial file is loaded via SCP.
2. Split, browse, second file loads with syntax highlighting enabled.
3. Current line is duplicated.
4. Repeat command duplicates the line again.

### Version of Vim

9.1.727

### Environment

OS: Mac OS Sonoma 14.7
Terminal: MacVim
TERM: xterm-256color
Shell: /bin/bash

**Comment by chrisbra** [comment]
cannot seem to reproduce

**Comment by dctucker** [comment]
I've narrowed it down to plugin behavior, so if we need to close this one and open one in the plugin's repo I'd totally understand.

I use [vim-vinegar](https://github.com/tpope/vim-vinegar) and have been for several years. This behavior is new though. If I disable this plugin the behavior goes away and returns to normal.

Sorry for the noise.

**Comment by chrisbra** [comment]
let's close it then.
