### ISSUE TITLE
Not possible to call netrw#BrowseX() directly after 3d7e567ea

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#15959]
### Steps to reproduce

1. Execute `vim -N -u vimrc` where `vimrc` has this content:

```vim
filetype plugin on
g:loaded_netrwPlugin = 1
nnoremap gx :call netrw#BrowseX(expand((exists("g:netrw_gx")? g:netrw_gx : '<cfile>')),netrw#CheckIfRemote())<cr>
```

2. Paste a URL in a buffer.
3. Go over the URL with the cursor.
4. Type `gx`.

This used to work before commit https://github.com/vim/vim/commit/3d7e567ea7392e43a90a6ffb3cd49b71a7b59d1a, but now produces:

```
Error detected while processing function netrw#BrowseX:
line  135:
E492: Not an editor command: Open <URL>
```

My suggestion would be to avoid calling plugin's commands from an autoload script (an autoload script should not depend on its plugin's commands, because the latter depend on the autoload script). Could the functionality supported by `s:Open()` be moved into the autoload script to make it self-contained? Note that netrw has `g:loaded_netrwPlugin` to control loading the plugin script, and `g:loaded_netrw` to control loading the autoload script. I only disable the former.

My use case is as follows: I don't want to load netrw (I use an alternative way to browse files), but I'd still like to make use of the ability to open certain paths/URIs in an external program.

### Expected behaviour

The URL in the buffer should open in an external browser.

### Version of Vim

9.1.819

### Environment

macOS
Apple Terminal
ZSH

**Comment by Konfekt** [comment]
Let's condense the various plugin commands into a single autoload function.
