### ISSUE TITLE
charclass() sometimes returns 2 for punctuation

### ISSUE THREAD

**Issue by kennypete** [vim/vim#15965]
### Steps to reproduce

1. In a new buffer, source:
```
for c in range(32, 48, 8)
  echo nr2char(c) .. ' charclass=' .. nr2char(c)->charclass()
endfor
```

Echos (correctly):
```
  charclass=0
( charclass=1
0 charclass=2  
```

2. In a help buffer, `set ma` to make it modifiable, then put the same for loop and source it:

Echos:
```
  charclass=0
( charclass=2
0 charclass=2  
```

Screenshots to illustrate:

![image](https://github.com/user-attachments/assets/daa6fea3-47fb-4674-a40b-75a6c13123c6)

### Expected behaviour

`charclass()` should always return 1 for the left parenthesis (and any punctuation character):

`builtin.txt` help:
```
charclass({string})					charclass()
		Return the character class of the first character in {string}.
		The character class is one of:
			0	blank
			1	punctuation
			2	word character
			3	emoji
			other	specific Unicode class
```

The same thing happens for all punctuation characters, returning 2 instead of 1.

### Version of Vim

9.1.90

### Environment

Same result in Win11 gvim, Debian WSL Huge GTK3 GUI.

_Also happens in Neovim 0.10.2, incidentally, just to see whether the same thing happens in it, and it does (not that I care particularly)_.

**Comment by chrisbra** [comment]
That is most likely because Vims helpfiles set custom 'iskeyword' settings.

**Comment by kennypete** [comment]
> That is most likely because Vims helpfiles set custom 'iskeyword' settings.

Okay, thanks. Since it's an internal Vim thing (and not, e.g., returning a value of a Unicode field), the only thing needed is to cover that distinction in the help? I'm in the process of updating a couple of help files, so will add that caveat.

**The 'bug' label should be removed and 'enhancement' added?** (i.e., enhancing the documentation)

It's kind of ironic, if you provide a working example of using `charclass()` in help file itself, that some/common punctuation characters return 2, though, aye 😉:
```
vim9script
var pop: list<string>
var eg: list<string> = [' ', '՛', '!', 'a', '♥', '가']
for i in range(0, len(eg) - 1)
  add(pop, eg[i] .. ': ' .. eg[i]->charclass())
endfor
popup_notification(pop, {title: "charclass()", time: 4000})
```
![image](https://github.com/user-attachments/assets/a1c3cffb-21da-485d-8dfa-b609e7691e88)
