### ISSUE TITLE
Filetype not detected when browsing into a file using netrw over SCP

### ISSUE THREAD

**Issue by dctucker** [vim/vim#15961]
### Steps to reproduce

1. Load a file via SCP
2. `:Vex` and select another file and then press `<CR>`. No syntax highlighting.
3. `:set ft` shows `filetype=netrw`.

This appears to be a regression of https://github.com/vim/vim/issues/12990 despite no change to the line of code that was intended to resolve this previous issue. Behavior is present even with empty .vim and .vimrc.

[This closed issue](https://github.com/vim/vim/issues/15958) captured the problem described here as well as odd plugin behavior which has been captured in [an issue on the plugin's repository](https://github.com/tpope/vim-vinegar/issues/140#issuecomment-2442801459).

### Expected behaviour

1. Initial file is loaded via SCP.
2. Split, browse, second file loads with syntax highlighting enabled.
3. `:set ft` shows `filetype=` followed by actual type of loaded file.

### Version of Vim

9.1.727

### Environment

OS: Mac OS Sonoma 14.7
Terminal: MacVim or iTerm2, doesn't seem to matter
TERM: xterm-256color
Shell: /bin/bash

**Comment by Konfekt** [comment]
Version 9.1.727 excludes any relation to the latest code changes (aimed at `gx` handling). At a similar occasion, missing syntax highlighting was due to an autocmd missing the `++nested` flag to enable it.

**Comment by chrisbra** [comment]
can you please try this patch? 
```diff
diff --git a/runtime/autoload/netrw.vim b/runtime/autoload/netrw.vim
index e09716de1..2a94e231e 100644
--- a/runtime/autoload/netrw.vim
+++ b/runtime/autoload/netrw.vim
@@ -1795,7 +1795,7 @@ fun! s:NetrwOptionsRestore(vt)
 "   call Decho("case ".a:vt."netrw_optionsave : doesn't exist",'~'.expand("<slnum>"))

    " filereadable() returns zero for remote files (e.g. scp://localhost//etc/fstab)
-   if filereadable(expand("%")) || expand("%") =~# '^\w\+://\f\+/'
+   if filereadable(expand("%")) || expand("%") =~# '^\w\+://\f\+'
 "    call Decho("..doing filetype detect anyway")
     filetype detect
 "    call Decho("..settings buf#".bufnr("%")."<".bufname("%").">: ".((&l:ma == 0)? "no" : "")."ma ".((&l:mod == 0)? "no" : "")."mod ".((&l:bl == 0)? "no" : "")."bl ".((&l:ro == 0)? "no" : "")."ro fo=".&l:fo." a:vt=".a:vt,'~'.expand("<slnum>"))
```

for me this is because I have an `@` in the remote filename and `@` is not part of the `'isfname'` setting, but it is on Windows (where the above works).

**Comment by dctucker** [comment]
Without compiling a new app bundle, I'm unable to simply run a modified MacVim.app.
However, I can confirm `echo expand("%") =~# '^\w\+://\f\+/'` shows `0` while `echo expand("%") =~# '^\w\+://\f\+'` shows `1`.

**Comment by dctucker** [comment]
Just compiled a bundle (after jumping through the latest xcodeselect hoops). This indeed seems to resolve the syntax highlighting issue, as well as the breakage in vim-vinegar.
