### ISSUE TITLE
/etc/named.conf is recognized as 'bindzone' filetype when using sudoedit

### ISSUE THREAD

**Issue by zdohnal** [vim/vim#1597]
Hi, 

I encountered an issue with syntax highlighting, when I opened /etc/named.conf with sudoedit, when vim is set as editor. Steps to reproduce in Fedora are:

1) $ sudo dnf install vim bind
2) $ export EDITOR=vim
3) sudoedit /etc/named.conf

Because of sudoedit, which copies original file into /var and name it as namedXXX.conf, vim cannot recognize it as named.conf, because name in filetype.vim in regexp is hardcoded, so it falls into scripts.vim, where filetype 'bindzone' is assigned badly because of contents of first four lines.
I saw it is common issue with VIM and sudoedit, but solved only as workaround on local machine. Is there any reason, why these fixes cannot be added into VIM by default (the easiest fix can be editing named.conf to named*.conf)?

**Comment by chrisbra** [comment]
fixed as of e0720cbf63eb3045be8d965
