### ISSUE TITLE
syntax=zsh colorizes incorrectly

### ISSUE THREAD

**Issue by psprint** [vim/vim#1598]
Following code isn't highlighted correctly, when opened from `test.zsh` file:

```zsh
#!/bin/zsh
call ZUI[my_select_data] 'ZUI[my_host_data]='
if (( 1 )); then
    :
fi
```
It looks like following: [Asciinema](https://asciinema.org/a/87wlyoz4gsqgmone1jupjbaaj), [Imgur](http://imgur.com/a/pWrT8) – the `if (( ...` is higlighted as if it was inside a string.

**Comment by chrisbra** [comment]
please create issues in the official [vim-zsh-runtime files repository](https://github.com/chrisbra/vim-zsh/issues)
