### ISSUE TITLE
Problem with parsing Vimscript boolean variable to if_lua interface (`v:true` becomes `1` instead of `true`, `v:false` becomes 0 instead of `false`)

### ISSUE THREAD

**Issue by brianhuster** [vim/vim#15994]
### Steps to reproduce

Test 1
1. A Vim >= 8.2 with `has('lua')` returns 1
2. `:let g:t1 = v:false`
3.  `:lua print(vim.g.t1)` => returns `0` instead of `false`

Test 2
4. `:lua vim.g.t2 = false`
5. `:lua print(vim.g.t2)` => returns `0` instead of `false`, even though it was declared as `false`

### Expected behaviour

The line 3 should returns `false` instead of `0`
The line 5 should returns `false` instead of `0`

Given that `luaeval` successfully convert Lua boolean to Vimscript boolean, I don't understand why `vim.eval` can't do the same. 

Also, this problem doesn't happen in Neovim

### Version of Vim

VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Sep 25 2024 10:13:04) Included patches: 1-16, 647, 678, 697

### Environment

Kubuntu 24.04.1

**Comment by chrisbra** [comment]
That seems like an implementation detail (and a seems just like a cosmetic issue). For a long time, Vimscript did not have true boolean types so used `1` and `0` and you can still observe it sometimes. Does it work differently when using Vim9 script? 

> Given that luaeval successfully convert Lua boolean to Vimscript boolean, I don't understand why vim.eval can't do the same

I think the lua interface predates the creation of boolean vimscript values. However having said that, a PR to fix this would certainly be appreciated.

**Comment by brianhuster** [comment]
> Does it work differently when using Vim9 script?
Yes, if I declare a global variable in Vim9script
```vim
vim9script
g:some_bool = v:false
```

Then I source the Vim file and call the variable in Lua
```vim
:lua print(vim.g.some_bool)`
```
It still returns `0` instead of `false`

>  PR to fix this would certainly be appreciated.

Thank you, I would love to, I will relearn C and research the file `if_lua.c` next weekend

**Comment by chrisbra** [comment]
> Thank you, I would love to, I will relearn C and research the file if_lua.c next weekend

That is great that you are offering help here. But just as a quick warning: those interface definitions are typically not the easiest to start working with, if you don't have much C experience yet.

**Comment by zeertzjq** [comment]
I haven't checked if it works, but it may be a simple one-line change:
```diff
diff --git a/src/if_lua.c b/src/if_lua.c
index 4d19c3ef5..d01b9f96a 100644
--- a/src/if_lua.c
+++ b/src/if_lua.c
@@ -595,7 +595,7 @@ luaV_pushtypval(lua_State *L, typval_T *tv)
 	case VAR_BOOL:
 	case VAR_SPECIAL:
 	    if (tv->vval.v_number <= VVAL_TRUE)
-		lua_pushinteger(L, (int) tv->vval.v_number);
+		lua_pushboolean(L, (int) tv->vval.v_number);
 	    else
 		lua_pushnil(L);
 	    break;
```

**Comment by chrisbra** [comment]
have you tested the patch?

**Comment by brianhuster** [comment]
Do you mean Vim 0.9.847? Sorry, the problem still persists with `if_lua` interface, `lua print(vim.eval("v:false"))` still output `0` instead of `false`

Btw, the problem doesn't exist in `if_python` interface, `python3 print(vim.eval("v:false"))` outputs `False` instead of `0`

**Comment by brianhuster** [comment]
Do you mean Vim 9.1.847? Sorry, the problem still persists with `if_lua` interface, `lua print(vim.eval("v:false"))` still output `0` instead of `false`

Btw, the problem doesn't exist in `if_python` interface, `python3 print(vim.eval("v:false"))` outputs `False` instead of `0`
