### ISSUE TITLE
request: increase minor version after fixing vulnerabilities

### ISSUE THREAD

**Issue by hexcoder-** [vim/vim#15990]
I am not sure if this belongs to the win32-installer repo or here (see [#359](https://github.com/vim/vim-win32-installer/issues/359), sorry for the duplication).

**Problem**
In my company installed software (eg vim) is scanned regularly. For the installed version of each software component a lookup with known vulnerabilities is done, and in case of any findings the user is urged to update.

For version 9.1.0000 there were 4 known CVEs, that were fixed soon afterwards (thanks!).
When I upgraded to the latest vim version the following scans kept reporting those 4 CVEs, since the windows registry only names 9.1 as the vim version, but not eg 9.1.0837.
So the scanner is not able to differentiate between the fixed and the vulnerable version. Of course the scanning is automated and will mercilessly escalate this (informing my boss about it).

**Describe the solution you'd like**
If the release policy could be changed to increase the minor version after fixing of CVEs, that would very certainly help.

**Alternative**
If the installer could be changed to put the patchlevel part also in the version as seen in the registry, that maybe might help.

Thanks!

**Comment by chrisbra** [comment]
Each change of the C source core, increments the patch number. I am not planning to increase the minor number, just because a vulnerability has been reported, sorry. As mentioned in the other issue, the patchlevel is already part of the version number inside the registry.
