### ISSUE TITLE
E274 gives an incorrect error message

### ISSUE THREAD

**Issue by atitcreate** [vim/vim#16008]
### Steps to reproduce

```bash
vim --clean -S <(
	cat <<- 'EOF'

		" Command 1,2
		echo string('a') -> substitute('a', "b", "")
		echo string('a') -> {x -> substitute(x, 'a', "b", "")}()
		" E274: No white space allowed before parenthesis

		" Command 3,4
		echo string('a')-> substitute('a', "b", "")
		echo string('a')-> {x -> substitute(x, 'a', "b", "")}()
		" E274: No white space allowed before parenthesis

		" Command 5,6
		echo string('a')->substitute('a', "No error", "")
		echo string('a')->{x -> substitute(x, 'a', "No error", "")}()
		" No error

		" Command 7,8
		echo string('a') ->substitute('a', "No error", "")
		echo string('a') ->{x -> substitute(x, 'a', "No error", "")}()
		" No error

	EOF
)

```

### Expected behaviour

Error messages of Command 1-4 should be `E274: No white space allowed after "->" `

### Version of Vim

9.1.0845

### Environment

bash

**Comment by zzzyxwvut** [comment]
The current wording of `E274` is correct.  Pay attention to  
the first sentence under `:help E274`:

> "->name(" must not contain white space. 

When the `name` is a lambda expression, then look for a paren  
after the rightmost `}` (or the grouping `)`).

For example,

```vim
echo 'a' ->({ x -> { _ -> x } }( 'b' ) )( )
"""""""""" [(+++++ name ++++++)++++++++]

let ConstB = { x -> { _ -> x } }( 'b' )
echo 'a ' ->ConstB( )
""""""""""" [name]
```

where `[... name ...]` in a comment is a `name`.

So no whitespace characters are allowed to the left or to  
the right of a `name` (_before parenthesis_).

See also [Bram's comment](https://github.com/vim/vim/issues/7725#issuecomment-766032439).

**Comment by chrisbra** [comment]
closing then.
