### ISSUE TITLE
Test_set_ttytype from test_options.vim fails

### ISSUE THREAD

**Issue by marv** [vim/vim#1601]
While upgrading vim on Exherbo (Linux, x86_64) from 8.0.0160 to 8.0.0515 I run into the following test failure:

> From test_options.vim:
> Found errors in Test_set_ttytype():
> function RunTheTest[24]..Test_set_ttytype line 13: command did not fail: set ttytype=xxx
> TEST FAILURE

`:set ttytype=xxx` succeeds while it should fail. In fact with the currently installed version (which didn't have a test for this behaviour) I can issue `:set ttytype=xxx` and `:set ttytype?` returns `ttytype=xxx`

  Any pointers what might cause this?

**Comment by nuko8** [comment]
Weird.  I built 8.0.0515 and couldn't reproduce the issue with it.

Hmm, will you tell us what happens with the command below on a terminal under the same environment with which you ran the test?:
```
$ infocmp xxx
```

**Comment by marv** [comment]
Running `infocmp xxx` in the build environment outputs
> infocmp: couldn't open terminfo file /usr/share/terminfo/x/xxx.

as you would expect

**Comment by nuko8** [comment]
OK.., then what happens with this?:
```
$ TERM=xxx /path/to/vim -u NONE --noplugin
```

**Comment by chrisbra** [comment]
can you please also show the output of `:version`

**Comment by marv** [comment]
In order to get the output of those commands in the non-interactive test environment,
I did run it like this `TERM=xxx "${WORK}"/src/vim -e -u NONE --noplugin -c "qall"`, where ${WORK} points to the directory we just built vim in. The output is:
> E437: terminal capability "cm" required

The output of `:version` is:
> VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 31 2017 09:37:02)
Included patches: 1-515
Modified by Exherbo-8.0.0515
Compiled by marv@pythagoras
Huge version without GUI.  Features included (+) or not (-):
+acl             +cmdline_hist    -ebcdic          +gettext         +listcmds        +mouse_sgr       +persistent_undo +smartindent     +textobjects     +wildmenu
+arabic          +cmdline_info    +emacs_tags      -hangul_input    +localmap        -mouse_sysmouse  +postscript      +startuptime     +timers          +windows
+autocmd         +comments        +eval            +iconv           +lua             +mouse_urxvt     +printer         +statusline      +title           +writebackup
-balloon_eval    +conceal         +ex_extra        +insert_expand   +menu            +mouse_xterm     +profile         -sun_workshop    -toolbar         -X11
-browse          +cryptv          +extra_search    +job             +mksession       +multi_byte      -python          +syntax          +user_commands   -xfontset
++builtin_terms  +cscope          +farsi           +jumplist        +modify_fname    +multi_lang      +python3         +tag_binary      +vertsplit       -xim
+byte_offset     +cursorbind      +file_in_path    +keymap          +mouse           -mzscheme        +quickfix        +tag_old_static  +virtualedit     -xpm
+channel         +cursorshape     +find_in_path    +lambda          -mouseshape      +netbeans_intg   +reltime         -tag_any_white   +visual          -xsmp
+cindent         +dialog_con      +float           +langmap         +mouse_dec       +num64           +rightleft       -tcl             +visualextra     -xterm_clipboard
-clientserver    +diff            +folding         +libcall         -mouse_gpm       +packages        +ruby            +termguicolors   +viminfo         -xterm_save
-clipboard       +digraphs        -footer          +linebreak       -mouse_jsbterm   +path_extra      +scrollbind      +terminfo        +vreplace
+cmdline_compl   -dnd             +fork()          +lispindent      +mouse_netterm   -perl            +signs           +termresponse    +wildignore
   system vimrc file: "/etc/vim/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation:
x86_64-pc-linux-gnu-cc -c -I. -Iproto -DHAVE_CONFIG_H   -pipe -O2 -mtune=generic -march=x86-64  -pipe -O2 -mtune=generic -march=x86-64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: x86_64-pc-linux-gnu-cc   -L. -fstack-protector -rdynamic -Wl,-export-dynamic  -L/usr/local/lib -Wl,--as-needed -o vim        -lm -lelf -lnsl   -lcurses -ldl  -L/usr/lib -llua
5.2   -L/usr/x86_64-pc-linux-gnu/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -lpthread -ldl -lutil -lm  -Wl,-R/usr/x86_64-pc-linux-gnu/lib -L/usr/x86_64-pc-linux-gnu/lib -l
ruby-2.4 -lpthread -lgmp -ldl -lcrypt -lm

**Comment by brammool** [comment]
Marvin Schmidt wrote:

> In order to get the output of those commands in the non-interactive test environment,
> I did run it like this `TERM=xxx "${WORK}"/src/vim -e -u NONE --noplugin -c "qall"`, where ${WORK} points to the directory we just built vim in. The output is:
> > E437: terminal capability "cm" required

Looks like "xxx" is an actual termcap entry name.  Can you try something
else?


-- 
Ten bugs in the hand is better than one as yet undetected.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by marv** [comment]
Nope, it's not an actual termcap entry as far as I can see. Running it under `strace` shows that it's not found:
> [snip]
stat("/usr/share/terminfo", {st_dev=makedev(253, 0), st_ino=139393, st_mode=S_IFDIR|0755, st_nlink=44, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=8, st_size=4096, st_atime=2017-04-08T14:01:35+0200.526921454, st_mtime=2012-11-15T21:02:25+0100, st_ctime=2012-11-29T20:57:23+0100}) = 0
stat("/etc/termcap", 0x1f6c0e0)         = -1 ENOENT (No such file or directory)
stat("/usr/share/misc/termcap", 0x1f6c0e0) = -1 ENOENT (No such file or directory)
stat("/usr/share/terminfo", {st_dev=makedev(253, 0), st_ino=139393, st_mode=S_IFDIR|0755, st_nlink=44, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=8, st_size=4096, st_atime=2017-04-08T14:01:35+0200.526921454, st_mtime=2012-11-15T21:02:25+0100, st_ctime=2012-11-29T20:57:23+0100}) = 0
access("/usr/share/terminfo/x/xxx", R_OK) = -1 ENOENT (No such file or directory)
ioctl(0, TCGETS, {c_iflags=0x4500, c_oflags=0x5, c_cflags=0xbf, c_lflags=0x8a3b, c_line=0, c_cc="\x03\x1c\x7f\x15\x04\x00\x01\x00\x11\x13\x1a\x00\x12\x0f\x17\x16\x00\x00\x00"}) = 0
write(2, "E", 1E)                        = 1
write(2, "4", 14)                        = 1
write(2, "3", 13)                        = 1
write(2, "7", 17)                        = 1
write(2, ":", 1:)                        = 1
write(2, " ", 1 )                        = 1

It's the same behaviour when I try with `TERM=foobar`. What else could have influence on that? Where in the codebase is that handled?

**Comment by brammool** [comment]
Marvin Schmidt wrote:

> Nope, it's not an actual termcap entry as far as I can see. Running it under `strace` shows that it's not found:
> > [snip]
> stat("/usr/share/terminfo", {st_dev=makedev(253, 0), st_ino=139393, st_mode=S_IFDIR|0755, st_nlink=44, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=8, st_size=4096, st_atime=2017-04-08T14:01:35+0200.526921454, st_mtime=2012-11-15T21:02:25+0100, st_ctime=2012-11-29T20:57:23+0100}) = 0
> stat("/etc/termcap", 0x1f6c0e0)         = -1 ENOENT (No such file or directory)
> stat("/usr/share/misc/termcap", 0x1f6c0e0) = -1 ENOENT (No such file or directory)
> stat("/usr/share/terminfo", {st_dev=makedev(253, 0), st_ino=139393, st_mode=S_IFDIR|0755, st_nlink=44, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=8, st_size=4096, st_atime=2017-04-08T14:01:35+0200.526921454, st_mtime=2012-11-15T21:02:25+0100, st_ctime=2012-11-29T20:57:23+0100}) = 0
> access("/usr/share/terminfo/x/xxx", R_OK) = -1 ENOENT (No such file or directory)
> ioctl(0, TCGETS, {c_iflags=0x4500, c_oflags=0x5, c_cflags=0xbf, c_lflags=0x8a3b, c_line=0, c_cc="\x03\x1c\x7f\x15\x04\x00\x01\x00\x11\x13\x1a\x00\x12\x0f\x17\x16\x00\x00\x00"}) = 0
> write(2, "E", 1E)                        = 1
> write(2, "4", 14)                        = 1
> write(2, "3", 13)                        = 1
> write(2, "7", 17)                        = 1
> write(2, ":", 1:)                        = 1
> write(2, " ", 1 )                        = 1
> 
> It's the same behaviour when I try with `TERM=foobar`. What else could have influence on that? Where in the codebase is that handled? 

It looks like the library falls back to an empty set of values, instead
of returning an error.  We can catch the error for the missing 'cm'
entry instead.  Let's see if that works.

-- 
"Never be afraid to tell the world who you are."
                                        -- Anonymous

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
