### ISSUE TITLE
 Wrong handling of folder symbolic link in tree view (2)

### ISSUE THREAD

**Issue by kuator** [vim/vim#16020]
I noticed that the original issue https://github.com/vim/vim/issues/14623 got closed with https://github.com/vim/vim/pull/15996 but the problem still persists.

### Steps to reproduce

1. Build latest vim as of November 9th, 2024 (vim 9.1.847).
3. `mkdir -p /tmp/test/original_folder && echo 'text' >> /tmp/test/original_folder/gyatt.txt`
6. `cd /tmp/test/ && ln -sv /tmp/test/original_folder /tmp/test/folder_symlink`
7. `vim -c 'let g:netrw_liststyle=3'`
8. `:Explore`
9. Try to open `folder_symlink`. `netrw` should show content of the `original_folder` which in this case is `gyatt.txt`, but instead `netrw` is trying to open `/tmp/test/original_folder/folder_symlink` which is completely wrong. 

https://github.com/user-attachments/assets/9a79bd64-276c-4fc5-b5b5-904c9c8e9e81

### Expected behaviour

`netrw` shows `gyatt.txt` as content for `folder_symlink`

### Version of Vim

9.1.847

### Environment

Ubuntu 24.04.4 LTS noble
GNOME Terminal 3.44.0 using VTE 0.68.0 +BIDI +GNUTLS +ICU +SYSTEMD
xterm-256color
zsh 5.8.1 (x86_64-ubuntu-linux-gnu)

**Comment by chrisbra** [comment]
Please try this patch:
```diff
diff --git a/runtime/autoload/netrw.vim b/runtime/autoload/netrw.vim
index 6799a3444..5a995e4c1 100644
--- a/runtime/autoload/netrw.vim
+++ b/runtime/autoload/netrw.vim
@@ -4585,6 +4585,11 @@ fun! s:NetrwBrowseChgDir(islocal,newdir,cursor,...)
   if a:cursor && exists("w:netrw_liststyle") && w:netrw_liststyle == s:TREELIST && exists("w:netrw_treetop")
    " dirname is the path to the word under the cursor
    let dirname = s:NetrwTreePath(w:netrw_treetop)
+   " newdir resolves to a directory
+   if a:islocal && fnamemodify(dirname, ':t') == newdir && isdirectory(resolve(dirname)) && resolve(dirname) == resolve(newdir)
+    let dirname = fnamemodify(resolve(dirname), ':p:h:h')
+    let newdir = fnamemodify(resolve(newdir), ':t')
+   endif
    " Remove trailing "/"
    let dirname = substitute(dirname, "/$", "", "")

```

**Comment by kuator** [comment]
> Please try this patch:
> 
> ```diff
> diff --git a/runtime/autoload/netrw.vim b/runtime/autoload/netrw.vim
> index 6799a3444..5a995e4c1 100644
> --- a/runtime/autoload/netrw.vim
> +++ b/runtime/autoload/netrw.vim
> @@ -4585,6 +4585,11 @@ fun! s:NetrwBrowseChgDir(islocal,newdir,cursor,...)
>    if a:cursor && exists("w:netrw_liststyle") && w:netrw_liststyle == s:TREELIST && exists("w:netrw_treetop")
>     " dirname is the path to the word under the cursor
>     let dirname = s:NetrwTreePath(w:netrw_treetop)
> +   " newdir resolves to a directory
> +   if a:islocal && fnamemodify(dirname, ':t') == newdir && isdirectory(resolve(dirname)) && resolve(dirname) == resolve(newdir)
> +    let dirname = fnamemodify(resolve(dirname), ':p:h:h')
> +    let newdir = fnamemodify(resolve(newdir), ':t')
> +   endif
>     " Remove trailing "/"
>     let dirname = substitute(dirname, "/$", "", "")
> ```

After applying the patch, it started working correctly
