### ISSUE TITLE
Question about  tcl.vim

### ISSUE THREAD

**Issue by avl42** [vim/vim#16028]
https://github.com/vim/vim/blame/7724d621f21ff6599ba49f11401ddb45ff321099/runtime/syntax/tcl.vim#L130

This and the following line seem to be there for already 20years, but only now I found them, and don't understand them.

In particular, they spoil the highlighting for Tcl-scripts few lines below any occurrence of command "variable".

Tcl-command "variable" just takes a list of arguments being variable names and initialization values alternately.
e.g.:  variable foo "forty two" bar 42 snafu ;#  all get linked to namespace; foo and bar also get overwritten, snafu not.

I commented them out in my local installation of vim, and all seems fine, now I'd like to know what could have been the original reason for them...   I'm not yet claiming they're wrong, but maybe someone still remembers the motives for adding.

**Comment by chrisbra** [comment]
you really should try to check back with the actual maintainer of the file.
