### ISSUE TITLE
Doc: :!cmd in various.txt is duplicated as :range! in change.txt

### ISSUE THREAD

**Issue by hseg** [vim/vim#16044]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
Filtering through an external command is documented in three locations
- Narratively in `10.9`
- As a filter in `change.txt` (see `:range!`)
- As a way to invoke a command in `various.txt` (see `:!cmd` = `:!`)

This duplication is confusing -- I expected the fact that `:!` accepts a range to be documented at the tag `:!`, and it's only due to a search three links deep that I could find that fact documented anywhere (I was looking for a reference to share elsewhere, so this is not necessarily an indictment against the discoverability of this feature).

**Describe the solution you'd like**
Either merge `:range!` and `:!cmd` to have a single source of truth (possibly difficult, and the current situation has the nicety of being able to focus on the two different aspects of `:!` in their own contexts), or have them point to each other so readers know there might be some features discussed elsewhere.

**Describe alternatives you've considered**
Document that `:!` accepts a range under `:!cmd` -- but this runs the risk of desynchronization in the future.

**Comment by chrisbra** [comment]
> As a filter in change.txt (see :range!)
As a way to invoke a command in various.txt (see :!cmd = :!)

But those are fundamentally different things. If you use `:!` with a range, it will act as filter, while whithout a range, it will simply run an external command. 

Try the difference between: `:!nl` and `1,$!nl` to see this. The former waits some input on stdin and hangs until it receives some. So this is not duplicated.

**Comment by hseg** [comment]
Fair enough. Do you at least accept that the `:!` tag is ambiguous in re whether it refers to the filter or the command invocation? At least I attempted to look up the filter by invoking `:h :!` without realizing `:range!` existed. A pointer to the effect that
> (This command also exists as a filter, see |:range!|)
would be enough for this

**Comment by chrisbra** [comment]
Sure, that makes sense. Let me add this.
