### ISSUE TITLE
The help page for netrw-handler shows buggy examples

### ISSUE THREAD

**Issue by mgedmin** [vim/vim#16043]
### Steps to reproduce

1. :help netrw-handler
2. copy/paste the example functions into your .vimrc
3. maybe modify the functions
4. source your .vimrc
5. try `gx`, wonder why it doesn't work

### Expected behaviour

The examples do not have a `return ''` in the `finally` block that overwrites any actual URL the code inside the `try` block found and was trying to return.

### Version of Vim

9.1.847

### Environment

n/a

### Logs and stack traces

```shell
n/a
```

**Comment by chrisbra** [comment]
Hm? Am I missing something? There is this:

https://github.com/vim/vim/blob/210c49bbe8b2edf15fd4fbbc089ec128e4c9c0c9/runtime/doc/pi_netrw.txt#L1510

and 

https://github.com/vim/vim/blob/210c49bbe8b2edf15fd4fbbc089ec128e4c9c0c9/runtime/doc/pi_netrw.txt#L1525

**Comment by mgedmin** [comment]
Well, to be honest I filed this issue hoping to learn what the best solution would be, since I don't consider myself a vimscript expert.  From what I see your patch should work.   Maybe a simpler solution would be to move the `return ''` right above the `finally` instead?
