### ISSUE TITLE
How do I auto save any file after 1 sec  in vim 8.0?

### ISSUE THREAD

**Issue by ghost** [vim/vim#1605]
Saving file is very headache   ":" then "w " then compile the program back to vim "i" for insert haaaaaa.
Instead, I want to save my file at every second in 'INSERT' and 'NoInsert mode.

**Comment by chrisbra** [comment]
please ask user questions on the vim-use mailinglist or vi.stackexchange.com

**Comment by ghost** [comment]
Ooops sorry.
