### ISSUE TITLE
filetype=confini syntax highlighting issue

### ISSUE THREAD

**Issue by diegoviola** [vim/vim#16051]
### Steps to reproduce

1. open up a confini file (in my case, /etc/pacman.conf on Arch Linux).
2. write down a configuration file similar to the one in the screenshot attached and observe the syntax issue around the `Server = https://` line.

![20241114_04h34m39s_grim](https://github.com/user-attachments/assets/a3f87859-6125-4299-89fb-55cf3a00d279)

### Expected behaviour

The syntax highlighting should work correctly.

### Version of Vim

9.1.785

### Environment

Operating system: Arch Linux
Terminal: foot 1.19.0-1
Value of $TERM: foot
Shell: bash

**Comment by chrisbra** [comment]
That happens because `//` is considered to be a comment, see here: https://github.com/vim/vim/blob/dbf231a4b7fba235fa9ccc8798b37c0b4a4943ae/runtime/syntax/cfg.vim#L33

Not sure if this is correct for *confini*  or the *cfg* filetype.

**Comment by diegoviola** [comment]
@chrisbra Interesting, I'm not sure if confini is supposed to be the same as INI files, but the Wikipedia article for INI files only mentions `#` and `;` for comments: https://en.wikipedia.org/wiki/INI_file#Comments

Kakoune also only interprets `#` and `;` for INI files, so I'm also not sure if what Vim doing with `//` is correct.

**Comment by chrisbra** [comment]
This is used for generic `*.cfg` files. However I haven't found an example where `//` is used as comment, so perhaps we can get rid of it? Nowadays it seems much more likely to use a URL (which has a //) in it then to use `//` as comment. 

It's also used for `.hgrc` file, where this would be wrong as well. Let me change it to leading `//` markers.
