### ISSUE TITLE
The GUI version of Vim is launched when you run the console version of Vim with the -y option.

### ISSUE THREAD

**Issue by jlionhan** [vim/vim#16053]
### Steps to reproduce

1. run console version vim with -y option. 
2. gui verison vim launched

### Expected behaviour

The console version of Vim needs to be executed.

### Version of Vim

9.1.857

### Environment

windows 11 24h2
powershell 7.4.5
windows terminal 1.21.2911.0

**Comment by chrisbra** [comment]
yes, because Vim will try to behave like a "classical" gui editor, that means like menu bars and requires a GUI. I'll make it a bit more clear in the help.

**Comment by zeertzjq** [comment]
Isn't this working as intended?
```
							*-y* *easy*
-y		Easy mode.  Implied for |evim| and |eview|.  Starts with
		'insertmode' set and behaves like a click-and-type editor.
		This sources the script $VIMRUNTIME/evim.vim.  Mappings are
		set up to work like most click-and-type editors, see
		|evim-keys|.  The GUI is started when available.
```

**Comment by chrisbra** [comment]
ah, yes, it's right there. Thanks I looked at this help and somehow missed the last sentence
