### ISSUE TITLE
Allow users to pass an argument to `set` command

### ISSUE THREAD

**Issue by brianhuster** [vim/vim#16060]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
Let's take the installation of Python support for Vim as an example

> In Vim, set pythonthreedll=libpython3.10.so or similar (use the shell command sudo ldconfig -p | grep libpython3 to find the library name). See :help +python3/dyn-stable.

The problem here is that I can't make this automatic. If I try to run this
```vim
let g:pythonthreedll = systemlist('ldconfig -p | grep libpython3')[0]
set pythonthreedll=g:pythonthreedll

" Test with a Hello world program
python3 print('Hello world')
```
It will throw an error
```error
E370: Could not load library g:pythonthreedll: g:pythonthreedll: cannot open shared object file: No such file or directory
E263: Sorry, this command is disabled, the Python library could not be loaded.
```

So Vim thinks `g:pythonthreedll` is a string while I want it to be a variable

**Describe the solution you'd like**

Allow passing a variable to an option. Something like this 
```vim
set pythonthreedll = g:pythonthreedll  " g:pythonthreedll is a variable
set pythonthreedll=g:pythonthreedll " g:pythonthreedll is string 'g:pythonthreedll'
```

**Describe alternatives you've considered**
In Neovim, you can set an option using Nvim API `nvim_set_option_value({name}, {value}, {opts})`. So if Vim support Nvim API, I will rewrite the code above like this
```vim
call nvim_set_option_value(pythonthreedll, systemlist('ldconfig -p | grep libpython3')[0], {})
```

**Comment by zeertzjq** [comment]
`:h :let-option`
