### ISSUE TITLE
~/.config/vim doesn't work with Gvim, only with Vim

### ISSUE THREAD

**Issue by brianhuster** [vim/vim#16073]
### Steps to reproduce

1. Add this line to `~/.config/vim/vimrc`
```vim
let g:test = v:true
```
2. Open `vim` and run
```vim
echo g:test
```
The output is `v:true`

3. Open `gvim` and run
```vim
echo g:test
```
The output is `Error : g:test is not defined`

4. Run in shell `mv ~/.config/vim ~/.vim`
Then open gvim and run 
```vim
echo g:test
```
The output is `v:true`

### Expected behaviour

So it turns out that while TUI Vim support `$XDG_CONFIG_HOME`, Gvim doesn't support that and only support the traditional `~/.vimrc` and `~/.vim/vimrc`. Gvim should also support `$XDG_CONFIG_HOME` like TUI Vim does

### Version of Vim

9.1.0861

### Environment

OS : Kubuntu 24.04.1
Terminal : Konsole
$TERM : xterm-256color

**Comment by chrisbra** [comment]
Cannot reproduce. Please verify using `:scriptnames`
![grafik](https://github.com/user-attachments/assets/7b8e1d1c-0f57-4c6a-b34c-358df76d0d3e)

**Comment by brianhuster** [comment]
I have solved this by `sudo rm /usr/bin/gvim`, then `cp /usr/local/bin/vim /usr/local/bin/gvim`. So I'll close this

**Comment by chrisbra** [comment]
Setting `$PATH` was too easy?
