### ISSUE TITLE
shellescaping of :! versus :term

### ISSUE THREAD

**Issue by Konfekt** [vim/vim#16071]
If a file path `path` is passed to `:!cmd` then `shellescape(path)` is needed, whereas `:term cmd path` is fine. How's this documented in `:help :!` respectively `:help :term` ?
As an aside, when is the special argument for `:help shellescape()` needed?

**Comment by matveyt** [comment]
There are two kinds of substitutions: on Vim side and on application (shell) side. Vim stuff depends on command used, and so it's documented (probably, not enough?) at `:h :!`.

First, Vim replaces own specials, such as `%, #, !` etc. This is why one might need to escape them (manually, or by calling `shellescape(cmd, 1)` before passing to `:!`.

Next, Vim applies a set of options, such as `:h 'shellxquote'` or `:h 'shellxescape'`.

Next, Vim executes the command using `shell` and `shellcmdflag`. So `:!foo` becomes `bash -c foo` or whatever.

And finally, the external application (`:h 'shell'`) applies the set of rules of its own.

But if using `:term cmd` all the stuff is simply passed directly. Then it depends only upon `cmd` itself if it knows something about wildcards, etc.

**Comment by Konfekt** [comment]
Thank you! 

Good to know that `:!cmd` rather corresponds to `:term $SHELL -c 'cmd'` with `-c` an example of `&shellcmdflag` and `cmd` in `'cmd'` surrounded by `&shellxquote` and escaped by `&shellxescape`. This requires a lot more escaping than firing them off in the shell itself. 

> First, Vim replaces own specials, such as %, #, ! etc. This is why one might need to escape them (manually, or by calling shellescape(cmd, 1) before passing to :!.

That's also how I interpreted `shellescape(..., 1)`, but somehow

https://github.com/vim/vim/blob/deda23f850ae384706f3f071366e5849498e6a76/runtime/autoload/netrw.vim#L5162

had little effect on these

https://github.com/vim/vim/blob/deda23f850ae384706f3f071366e5849498e6a76/runtime/autoload/netrw.vim#L5075

Any idea why?

**Comment by matveyt** [comment]
Few years ago I tried to make some sense of netrw. But eventually I gave up and made a file browser plugin of my own. Even though I'm probably the only person who ever makes use of it I believe it's a terrific time investment as I don't have to look into that netrw nightmare anymore.

And, no, the code above definitely has some effect. It results in double escaping of `%` and `#`.

**Comment by Konfekt** [comment]
I'd add something like this to :help :!` and `:help :term`:

```
NOTE: `:!<cmd>` is similar to :term $SHELL -c '<cmd>' where `&shellcmdflag='-c'` and `&shellxquote='%s'`; additional escaping inside `<cmd>` determined by `&shellxescape.  This escaping is no longer necessary if the command is run directly by :term`.  

To replicate the behavior `:!<cmd>`, use `:term <cmd> ++close ++curwin` if <cmd> expects user input; `:term ++close  ++hidden` otherwise.  
```

**Comment by Konfekt** [comment]
I'd await @matveyt 's likely more detailed proposal before imposing mine with a PR

**Comment by matveyt** [comment]
I'll write PR tomorrow then.

**Comment by Konfekt** [comment]
Sounds good now that mine is out. The latter two lines are also extending a hand towards Neovim users wondering about how their `:term` might [replicate the abandoned `:!`](https://gist.github.com/Konfekt/8e484af2955a0c7bfe82114df683ce0f) for interactive commands.

**Comment by matveyt** [comment]
If you have any suggestions or improvements for PR, please, let me know.

**Comment by Konfekt** [comment]
I wouldn't have minded something along the lines of

```
`:!<cmd>` runs  `$SHELL -c '<cmd>' where `&shellcmdflag='-c'` and `&shellxquote="'%s'"`; 
additional escaping inside `<cmd>` is determined by `&shellxescape.
```

somewhere to understand what `:!` does under the hood

**Comment by matveyt** [comment]
Done.
