### ISSUE TITLE
autocmd BufWinEnter * ++once not firing on help files

### ISSUE THREAD

**Issue by Konfekt** [vim/vim#16085]
### Steps to reproduce

1. add  `autocmd BufWinEnter * ++once echoerr 1` to `~/.viminrc`
2. vim --clean -u ~/.~viminrc
3. :help mode
 

### Expected behaviour

error message reading `1` since without `++once` it does

### Version of Vim

9.1.842

### Environment

OS: Ubuntu 22.04, terminal: Urxvt 9.30, ZSH 5.81.

**Comment by zeertzjq** [comment]
Isn't it already triggered for the initial empty buffer?

**Comment by zeertzjq** [comment]
Isn't it already trigger for the initial empty buffer? So with `++once` it won't be triggered for another buffer.

**Comment by Konfekt** [comment]
Oh, I thought since `:help` opens a new buffer in a new window, it would fire again; while the 'done' marker is set per buffer (and window!?). In fact, it is not so clear what 'done' means here.

**Comment by zeertzjq** [comment]
It's per autocommand:
```
							*autocmd-once*
			If [++once] is supplied the command is executed once,
			then removed ("one shot").
```

**Comment by Konfekt** [comment]
Okay, I must have had something like `autocmd BufNew,BufRead * autocmd BufWinEnter <buffer> ++once` in mind.
