### ISSUE TITLE
Netrw's `g:netrw_decompress` does not work with extensions which have numbers in them

### ISSUE THREAD

**Issue by 00-kat** [vim/vim#16099]
### Steps to reproduce

Note: if you don't have 7-zip/p7zip installed, you could just change `7z x` to `bunzip2 -k` (or any other compression format you like) in the vimrc, and make the archive with `bzip2 test -c >test.7z`.
1. Put some text in a file `test`: `echo 'Hello, world!' >test`
2. Make a 7-zip archive with `7z a test.7z test`
3. Copy it to a couple other file names, for this demonstration of the bug: `for e in mz 8z m7z z7; do cp test.7z test.$e; done`
4. Delete the file `test`: `rm test`
5. Open vim at that directory (e.g.: `vim .`) with the following in `.vimrc`:
    ```vim
    vim9 g:netrw_decompress = {
        '.mz': '7z x',   # no numbers
        '.7z': '7z x',   # starting with number
        '.8z': '7z x',   # different number
        '.m7z': '7z x',  # number in middle
        '.z7': '7z x',   # number at end
    }
    ```
    (apologies for the syntax highlighting; I couldn't figure out how to have comments in dictionaries in vimscript)
6. Go through each one of the files created earlier, pressing `mfmz`.  Observe how every file with a number in its extension is compressed into `test.<extension>.gz`

### Expected behaviour

`test.7z` is extracted to `test`, similar to what happens with `test.mz`, instead of being compressed again into `test.7z.gz`

### Version of Vim

9.1.0866

### Environment

Operating system: Arch Linux (rolling release)
Terminal: Ghostty (also tried with kitty, as Ghostty isn't open source yet)
Value of `$TERM`: `xterm-ghostty` (and in kitty: `xterm-kitty`)
Shell: fish 3.7.1
Value of `$LANG`: `en_AU.UTF-8`

**Comment by Konfekt** [comment]
Funny, as `bz2` is included by default. The issue is with `\a` in

```vim
" runtime/autoload/netrw.vim (line 6541)
let sfx= substitute(fname,'^.\{-}\(\.\a\+\)$','\1','')
```

Something like `[[:alnum:]]` would work; likely there's no official file extension format, though

**Comment by Konfekt** [comment]
Maybe @00-kat you could test that replacement and let us know if it works for the better?

**Comment by Konfekt** [comment]
While at it, how about  updating the defaults to include something like

```vim
vim9 g:netrw_decompress = {
    '.mz': '7z x',   # no numbers
    '.7z': '7z x',   # starting with number
    '.8z': '7z x',   # different number
    '.m7z': '7z x',  # number in middle
    '.z7': '7z x',   # number at end
}
```

**Comment by Konfekt** [comment]
At least `.7s` seems common enough, and `.zstd` is also getting popular

**Comment by Konfekt** [comment]
Here are some suggestions from https://github.com/zimfw/archive/blob/master/functions/unarchive

```vim
vim9 g:netrw_decompress = {
  '.mz':       '7z x',
  '.7z':       '7z x',
  '.8z':       '7z x',
  '.m7z':      '7z x',
  '.z7':       '7z x',
  # '.7z':       '7za x',
  '.001':      '7za x',
  '.tar.bz':   'tar -xvjf',
  '.tar.bz2':  'tar -xvjf',
  '.tbz':      'tar -xvjf',
  '.tbz2':     'tar -xvjf',
  '.tar.gz':   'tar -xvzf',
  '.tgz':      'tar -xvzf',
  '.tar.zst':  'XZ_OPT=-T0 tar --use-compress-program=unzstd -xvf',
  '.tzst':     'XZ_OPT=-T0 tar --use-compress-program=unzstd -xvf',
  '.tar':      'tar -xvf',
  '.zip':      'unzip;;',
  '.bz':       'bunzip2',
  '.bz2':      'bunzip2',
  '.gz':       'gunzip',
  '.lzma':     'unlzma -T0',
  '.xz':       'unxz -T0',
  '.zst':      'zstd -T0 -d',
  '.Z':        'uncompress',
  # '.rar':      'unrar x -ad ${1} || rar x -ad ${1}',
  # '.tar.lzma': 'tar --lzma --help &>/dev/null && XZ_OPT=-T0 tar --lzma -xvf ${1} || lzcat ${1} | tar -xvf -',
  # '.tlz':      'tar --lzma --help &>/dev/null && XZ_OPT=-T0 tar --lzma -xvf ${1} || lzcat ${1} | tar -xvf -',
  # '.tar.xz':   'tar -J --help &>/dev/null && XZ_OPT=-T0 tar -xvJf ${1} || xzcat ${1} | tar -xvf -',
  # '.txz':      'tar -J --help &>/dev/null && XZ_OPT=-T0 tar -xvJf ${1} || xzcat ${1} | tar -xvf -',
}
```

Regarding the commented lines, there are two options; maybe others can decide.

**Comment by 00-kat** [comment]
> Funny, as bz2 is included by default

Oh yeah, `.bz2` doesn't work either, lol.

> how about updating the defaults to include something like

Most of those extensions aren't actually real, I made them up just to demo the bug.  Only `.7z` is actually a real extension.

(I'll try out that change in a minute)

**Comment by Konfekt** [comment]
Okay, removed them from above list

**Comment by 00-kat** [comment]
> Something like `[[:alnum:]]` would work

Yep, it works with `[[:alnum:]]`.

**Comment by 00-kat** [comment]
> Here are some suggestions

A few more:
```vim
'.lz4': 'lz4 -d',
'.lzo': 'lzop -d',
'.lz': 'lzip -d',
```

Also, some of those keep the archive file, while others remove them, which may be weird behaviour.

**Comment by Konfekt** [comment]
Oh, could you change those removing the archive to keep it? This is not intended.

**Comment by 00-kat** [comment]
I think this should happen in a PR instead, but
```vim
let g:netrw_decompress = {
            \   '.lz4':      'lz4 -d',
            \   '.lzo':      'lzop -d',
            \   '.lz':       'lzip -dk',
            \   '.7z':       '7za x',
            \   '.001':      '7za x',
            \   '.tar.bz':   'tar -xvjf',
            \   '.tar.bz2':  'tar -xvjf',
            \   '.tbz':      'tar -xvjf',
            \   '.tbz2':     'tar -xvjf',
            \   '.tar.gz':   'tar -xvzf',
            \   '.tgz':      'tar -xvzf',
            \   '.tar.zst':  'XZ_OPT=-T0 tar --use-compress-program=unzstd -xvf',
            \   '.tzst':     'XZ_OPT=-T0 tar --use-compress-program=unzstd -xvf',
            \   '.tar':      'tar -xvf',
            \   '.zip':      'unzip',
            \   '.bz':       'bunzip2 -k',
            \   '.bz2':      'bunzip2 -k',
            \   '.gz':       'gunzip -k',
            \   '.lzma':     'unlzma -T0 -k',
            \   '.xz':       'unxz -T0 -k',
            \   '.zst':      'zstd -T0 -d',
            \   '.Z':        'uncompress -k',
            \ }
          " \   '.rar':      'unrar x -ad ${1} || rar x -ad ${1}',
          " \   '.tar.lzma': 'tar --lzma --help &>/dev/null && XZ_OPT=-T0 tar --lzma -xvf ${1} || lzcat ${1} | tar -xvf -',
          " \   '.tlz':      'tar --lzma --help &>/dev/null && XZ_OPT=-T0 tar --lzma -xvf ${1} || lzcat ${1} | tar -xvf -',
          " \   '.tar.xz':   'tar -J --help &>/dev/null && XZ_OPT=-T0 tar -xvJf ${1} || xzcat ${1} | tar -xvf -',
          " \   '.txz':      'tar -J --help &>/dev/null && XZ_OPT=-T0 tar -xvJf ${1} || xzcat ${1} | tar -xvf -',
```
(I also converted it to vimscript, as there are no comments in there anymore.  That indentation is just whatever Vim decided was appropriate.)

**Comment by 00-kat** [comment]
The docs for `g:netrw_decompress` should probably be updated to show the new default too.
