### ISSUE TITLE
Wrong highlight after `Q='` sequence in the radare2 Makefile

### ISSUE THREAD

**Issue by XVilka** [vim/vim#1610]
When opening this [Makefile from radare2](https://github.com/radare/radare2/blob/master/Makefile) project, it stops to show the valid highlight after `Q='`. I understand this one is a bit tricky, but may be there is a way to continue normal highlight even after this sequence.
![vim_makefile_highlight_bug](https://cloud.githubusercontent.com/assets/203261/24574770/29f75164-16ca-11e7-9584-bbdd6cedbaa4.png)

**Comment by lacygoill** [comment]
Fixed by https://github.com/vim/vim/commit/9834b96820bec95d6858229d6fb256310365efff.

**Comment by chrisbra** [comment]
closing then.
