### ISSUE TITLE
Highlighting issue of gettext po file

### ISSUE THREAD

**Issue by e-kwsm** [vim/vim#16120]
### Steps to reproduce

A gettext po file looks like:

```po
msgid ""
msgstr ""
"Project-Id-Version: MWE\n"
"Content-Type: text/plain; charset=UTF-8\n"

#: /path/to/source:42
#, fuzzy
#| msgid ""
#| "old text →"
#| msgctxt "old context →"
msgid ""
"new text"
msgstr ""
"old translation"
```

Here the untranslated text is changed, thus the entry is marked as fuzzy, and the previous information is stored in the lines starting with `#|`.

Open the file, and notice that `"`&rsquo;s at the end of `#|`-lines are colored differently, say `poCommentDiff` vs `poDiffNew`.

![Screenshot From 2024-11-25 19-45-20](https://github.com/user-attachments/assets/7139245b-49cd-4c25-8491-d52a3d0b2ae3)
colorscheme is set to slate for easiness of comparison.

### Expected behaviour

Quotation mark `"` at the end of a line is not colored differently.

---

https://github.com/vim/vim/blob/ea49002acacd4467d7d68f605ebe5c0e85ec973b/runtime/syntax/po.vim#L52-L54

I cannot find diff specification in <https://www.gnu.org/software/gettext/#documentation>; anyway the regexps seem inaccurate.

### Version of Vim

9.1.866

### Environment

- OS: EndeavourOS
- terminal: GNOME Terminal 3.54.1 using VTE 0.78.1 +BIDI +GNUTLS +ICU +SYSTEMD
- `$TERM`: xterm-256color

**Comment by chrisbra** [comment]
Yeah, that looks wrong. It seems this patch would fix it:
```diff
diff --git a/runtime/syntax/po.vim b/runtime/syntax/po.vim
index 08d6baec2..dfc9fce2e 100644
--- a/runtime/syntax/po.vim
+++ b/runtime/syntax/po.vim
@@ -49,8 +49,8 @@ syn match     poCommentTranslator "^# .*$" contains=poCopyrightUnset
 syn match     poCommentAutomatic "^#\..*$"
 syn match     poCommentSources "^#:.*$"
 syn match     poCommentFlags "^#,.*$" contains=poFlagFuzzy
-syn match     poDiffOld '\(^#| "[^{]*+}\|{+[^}]*+}\|{+[^}]*\|"$\)' contained
-syn match     poDiffNew '\(^#| "[^{]*-}\|{-[^}]*-}\|{-[^}]*\|"$\)' contained
+syn match     poDiffOld '\(^#| "[^{]*+}\|{+[^}]*+}\|{+[^}]*\)' contained
+syn match     poDiffNew '\(^#| "[^{]*-}\|{-[^}]*-}\|{-[^}]*\)' contained
 syn match     poCommentDiff "^#|.*$" contains=poDiffOld,poDiffNew

 " Translations (also includes header fields as they appear in a translation msgstr)
```

It @dwaynebailey hopefully the right maintainer?

**Comment by e-kwsm** [comment]
The patterns seem to want to match something like below

```po
#| msgid "{- old -}"

#| msgid "{+ new"
#| "+}"
```

but GNU gettext does not yield them.

So I think they can be removed.

**Comment by chrisbra** [comment]
so you are saying, we can remove those entirely?
