### ISSUE TITLE
Symlinks in .vim/... don't seem to work in Windows. 

### ISSUE THREAD

**Issue by ubaldot** [vim/vim#16123]
### Steps to reproduce

Create a symlink e.g. with

`New-Item -ItemType SymbolicLink -Path "$env:USERPROFILE\.vim\after\ftplugin\rst.vim" -Target "$env:USERPROFILE\dotfiles\.vim\after\ftplugin\rst.vim"`

so that you have a symlink from` ~\.vim\after\ftplugin\rst.vim -> ~\dotfiles\.vim\after\ftplugin\rst.vim`

In `~\dotfiles\.vim\after\ftplugin\rst.vim` add something like the following:

`&l:formaprg="foo"`

Open any` rst` filetype file and run `:set formatprg?`. You should see `formatpgr=` instead of `formatpgr=foo`. 

Nevertheless, if I `gvim ~\.vim\after\ftplugin\rst.vim` then the linked file is correctly opened.

### Expected behaviour

I would expect  `formatpgr=foo`. 

### Version of Vim

9.1-695

### Environment

Windows 10.

**Comment by k-takata** [comment]
The Windows version of Vim doesn't use the `$HOME/.vim/` directory. It uses `$HOME/vimfiles/` instead.
