### ISSUE TITLE
No equivalent `isfile` like with `isdirectory`

### ISSUE THREAD

**Issue by dundargoc** [vim/vim#16138]
Right now there is no `isfile` like with `isdirectory` which is confusing. There is `filereadable` but that checks if a file is readable or not instead of an existence check. It makes sense to me to add a simple file existence check as there does not seem to exists one. I can create PR if wanted.

**Comment by zeertzjq** [comment]
Why can't you use `getftype()`

**Comment by dundargoc** [comment]
Never heard of it
