### ISSUE TITLE
Colorscheme incorrectly displayed on Windows 11 terminal

### ISSUE THREAD

**Issue by sgwzq** [vim/vim#16133]
### Steps to reproduce

Hello everyone, I am using Windows 11 23H2 and I want to configure my vim on terminal. 
I first opened cmd (not PowerShell !).
When I `:set termguicolors` or `:set t_Co=256` , then `:colo default`.The colorsheme shows unexpectedly incorrect. The background is black which I looks very uncomfortable, like this:
![image](https://github.com/user-attachments/assets/cd5abc9b-52e4-4e98-b011-6330ed3a73a7)
I tried `:set bg=light`,but the background not changed, still black.
I was thinking my colorscheme file may be somewhere incorrect. For the reason that my cmd line is not black normally but changes black just as I enter vim,I think this may be vim's reason(maybe).
I searched everywhere for that but got nothing useful.
Suddenly, I found that, when I open a powershell in the same window the cmd in with different tabs, the same commands resulted in the correct colors! Just the same as gui!! Like this:
![image](https://github.com/user-attachments/assets/61bd593d-8a68-49c6-91d2-8b0ac3dcd717)

In the same window I opened the third tab, this time cmd again. When I typed vim and enter, what i saw made me surprised that this time the color was correct! Like this:
![image](https://github.com/user-attachments/assets/4fe7b123-b711-4fc1-b4c5-e283969c6d25)

I tried to repeat the same phenomenon.I first pushed these commands in vimrc like these

```vimscript
set termguicolors
colorscheme default
set background=light
```

Then I opened in the same order:
1.Win+R to cmd, enter vim ->black
2.In the same window open a new PowerShell tab enter vim -> light
3.The same window then open a new cmd enter vim -> light

Why? Windows' bug or Vim's?

### Expected behaviour

I expect the Correct color in the first go in cmd, as the third picture.

### Version of Vim

9.1.882

### Environment

OS Windows 11 23H2
Terminal: Windows cmd and PowerShell
vimrc

```vimscript
set termguicolors
colorscheme default
set background=light
```

**Comment by chrisbra** [comment]
Honestly, I can't tell a difference between screenshot 2 and 3. Also, please verify using  `vim --clean` there is at least vim-airline into play, let verify using a minimum vim config first.

**Comment by sgwzq** [comment]
> Honestly, I can't tell a difference between screenshot 2 and 3. Also, please verify using `vim --clean` there is at least vim-airline into play, let verify using a minimum vim config first.

Look at the top of every screenshots.

2 is PowerShell and 3 is cmd, which I described in my narrative words (I am not native Eng speaker so there might be some errors in grammar. I'm Sorry for that)

Also I'm sorry for not providing the `vim --clean` test screenshot. 
I verified, and got the same result.

Win+R to cmd
The First Tab cmd---
vim --clean
:set termguicolors
---Black---

then open The Second Tab PowerShell---
(the same steps)
---Light---

then The Third Tab cmd---
（the same steps)
---Light---

**Comment by lifepillar** [comment]
A way to confirm that it's not a Vim issue would be to repeat the experiment with another program (e.g., another command-line editor) that uses the terminal's background.

**Comment by sgwzq** [comment]
> A way to confirm that it's not a Vim issue would be to repeat the experiment with another program (e.g., another command-line editor) that uses the terminal's background.
You got the same phenomenon? So, can you give some information about what probably caused that? 
I'm fresh in programming, and this is my first issue. I don't know whether it was the issue of my terminal or vim, so my assumption may be wrong. I'm sorry for that.

**Comment by sgwzq** [comment]
> A way to confirm that it's not a Vim issue would be to repeat the experiment with another program (e.g., another command-line editor) that uses the terminal's background.

You got the same phenomenon? So, can you give some information about what probably caused that? 
I'm fresh in programming, and this is my first issue. I don't know whether it was the issue of my terminal or vim, so my assumption may be wrong. I'm sorry for that.

**Comment by habamax** [comment]
I wonder why there is the expectation that vim.exe should have white(or light) background. With default windows terminal settings it should be dark:

vim --clean:

![image](https://github.com/user-attachments/assets/19f4ff84-2845-42e3-a15d-9156b7b3c409)

Default gui and default terminal colorscheme -- 2 completely different beasts.

**Comment by sgwzq** [comment]
> I wonder why there is the expectation that vim.exe should have white(or light) background. With default windows terminal settings it should be dark:
> 
> vim --clean:
> 
> ![image](https://private-user-images.githubusercontent.com/234774/390973148-19f4ff84-2845-42e3-a15d-9156b7b3c409.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NzYwOTEsIm5iZiI6MTczMjg3NTc5MSwicGF0aCI6Ii8yMzQ3NzQvMzkwOTczMTQ4LTE5ZjRmZjg0LTI4NDUtNDJlMy1hMTVkLTkxNTZiN2IzYzQwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOVQxMDIzMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MWQ1NGY2ZTMwNDgyNzJkZDM2NjQyMTE2OTAzMzIwODVlZjRkZGJhZDI5M2RhN2Q4Mzc5MTRmODJiNTlmNjRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pakLCFuxMWrk8hoVXjpCA9036OqKJZ062ks2TfQ5y70)
> 
> Default gui and default terminal colorscheme -- 2 completely different beasts.

The default terminal and vim is black for sure, but
I was used to `:set cursorline`, but when i turn that on, I found it difficult to read the word covered. (to test, I opened help document using the terminal's default colorscheme and `vim --clean`, and one can easily see the low color contrast made it hard to read)
![image](https://github.com/user-attachments/assets/3904a132-2838-4e10-afb1-0db952d09e0f)

So I am trying to make the color grey and transparent just as the gVim.
I entered these in my vimrc:

```vimscript
set termguicolors
colorscheme default
set background=light
```

I got customed to the bright style. I set the terminal color theme following the system(light), and the terminal colorscheme a light one 
![image](https://github.com/user-attachments/assets/d990b524-dfed-4779-a599-4827a4767efc)
![image](https://github.com/user-attachments/assets/ca289e72-58b5-4f9e-b84e-965d3de0db66)

(Sorry for not using English, but u may be able to understand that.)

After these sets, vim terminal should have been to gVim white style (on Windows 11 with 256 Colors), but it did not completely. The first tab black, but surprisingly the second White! ?!

**Comment by habamax** [comment]
Okay, so terminal background is set to be light. And probably "transparent" normal highlight group doesn't play well with cmd.exe, I don't know.

However as a workaround you can define `Normal` to be the same color as your terminal:

```
set termguicolors
set background=light
hi Normal guibg=#FFFFFF guifg=#000000
```
