### ISSUE TITLE
Postscript files always have Portrait orientation

### ISSUE THREAD

**Issue by mx518** [vim/vim#16156]
### Steps to reproduce

echo test > test.txt
vim -c "set printoptions=portrait:n | ha > lan.ps | q" test.txt && ps2pdf lan.ps
vim -c "set printoptions=portrait:y | ha > por.ps | q" test.txt && ps2pdf por.ps

### Expected behaviour

Expectingt that the .ps files have different orientations,
however both show: `%%Orientation: Portrait`
pdf also only rotates the text, not the page.
![image](https://github.com/user-attachments/assets/86aae77e-2422-43b7-a542-fbd4e7beac92)

### Version of Vim

9.0-1-1378, 1499

### Environment

WSL

**Comment by chrisbra** [comment]
Hm, can you test the following change please?
```diff
diff --git a/src/hardcopy.c b/src/hardcopy.c
index 8abfff210..785a3f554 100644
--- a/src/hardcopy.c
+++ b/src/hardcopy.c
@@ -2742,7 +2742,7 @@ mch_print_begin(prt_settings_T *psettings)

     prt_dsc_textline("CreationDate", get_ctime(time(NULL), FALSE));
     prt_dsc_textline("DocumentData", "Clean8Bit");
-    prt_dsc_textline("Orientation", "Portrait");
+    prt_dsc_textline("Orientation", prt_portrait ? "Portrait" : "Landscape");
     prt_dsc_atend("Pages");
     prt_dsc_textline("PageOrder", "Ascend");
     // The bbox does not change with orientation - it is always in the default
```

**Comment by mx518** [comment]
Thanks, LGTM!

![image](https://github.com/user-attachments/assets/e6ba8453-58e4-45ec-823e-fff4ed07a172)
