### ISSUE TITLE
Cannot echo from nested function

### ISSUE THREAD

**Issue by igbanam** [vim/vim#16179]
### Steps to reproduce

```vim
vim9script

def Outer()
  var foo: string = "foo"
  echo foo
  def Inner()
    var bar: string = "bar"
    echo foo .. bar
  enddef
enddef

Outer()
```

1. Save ☝🏽 as some-script.vim
1. vim --clean -S some-script.vim

### Expected behaviour

```
foo
foobar
```
…should be printed on screen. Instead, we only get the first `foo`

### Version of Vim

VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Nov 11 2024 19:01:06) macOS version - arm64 Included patches: 1-850 Compiled by Homebrew

### Environment

OS X Sequoia
iTerm
xterm-256color-italic
zsh

**Comment by zeertzjq** [comment]
You never called the inner function.
