### ISSUE TITLE
Increase default font size for GVim

### ISSUE THREAD

**Issue by matveyt** [vim/vim#16172]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
GVim has different default font size in Windows and Gtk builds (9pt and 10pt respectively). Both looking very small on modern monitors.

**Describe the solution you'd like**
Increase default font size. I believe 12pt is a safe choice.

**Describe alternatives you've considered**
Currently any GUI user is almost forced to have vimrc/gvimrc setting guifont option. Also, when running vimtutor script everything gets reset to the defaults, so the beginner tutorial is practically unreadable until user sets new font by menu.

**Additional context**
The choice of font size does not seem to be documented, so it's not really a breaking change. Fairly easy to do too: [just single define](https://github.com/vim/vim/blob/1c5a120a701fcf558617c4e70b5a447778f0e51d/src/os_mswin.c#L2733) for Windows build and [another one](https://github.com/vim/vim/blob/1c5a120a701fcf558617c4e70b5a447778f0e51d/src/gui_gtk_x11.c#L163) for Gtk (plus a few tests).

**Comment by chrisbra** [comment]
Are you up for a PR then?

**Comment by matveyt** [comment]
@chrisbra Sure, I'll make it tomorrow.

**Comment by chrisbra** [comment]
Thanks!
