### ISSUE TITLE
extra random text inserts when using Ctrl-c and ctrl-v between windows

### ISSUE THREAD

**Issue by msaine** [vim/vim#16188]
### Steps to reproduce

It's hard to reproduce because it is random. I have been using cut and paste between windows for years (between several instances of gvim widows opened on various files). I have recently upgraded to Windows 11 pro on a couple of machines and things have gone to hell. What happens is when I copy and paste a block or line of code from one file to another and then save and recompile the target file and all of a sudden I can have random insertions of the line in random places in my code. They can happen at it seems any random point. It also doesn't happen every time. I have noticed if I copy like a link to paste in a browser and later edit a file with vim, that link is the text that gets randomly inserted, so it appears that the last thing in the windows clip board might be what is inserted.

[vimrc.txt](https://github.com/user-attachments/files/18050474/vimrc.txt)

Here is my _vimrc file renamed so your system would take it. I have done this type cut and paste for years and was real surprised about this not working. Needless to say this is highly annoying and can corrupt files. Vi has been my primary editor for 4 decades and I would really like to find out what is wrong. I still have a couple of win 10 pro machines that don't experience this problem.

I did uninstall vim 9.1 and install a copy of vim 9.0 and it also does it so I am guessing Microsuck has changed something in win 11?? 

### Expected behaviour

one and only one copy of the pasted text at the cursor, not additional random places thru out the file

### Version of Vim

does this on both vim 9.0 and vim 9.1

### Environment

Windows 11 pro on a dell optiplex, don't have model number in front of me as I am typing this on a AZUZ laptop (also running windows 11 pro) . The mswin.vim file is one with the distribution.

**Comment by chrisbra** [comment]
That is not really helpful unfortunately. In any case I would recommend to use non-windows keybindings and instead learn to use native Vim keybindings.

**Comment by h-east** [comment]
Are you using a mouse with a wheel?
By default, pressing the wheel pastes the clipboard contents at the cursor position.
I add the following to my _vimrc to stop this from happening accidentally:

```vim
noremap <MiddleMouse> <Nop>
noremap! <MiddleMouse> <Nop>
noremap <2-MiddleMouse> <Nop>
noremap! <2-MiddleMouse> <Nop>
noremap <3-MiddleMouse> <Nop>
noremap! <3-MiddleMouse> <Nop>
noremap <4-MiddleMouse> <Nop>
noremap! <4-MiddleMouse> <Nop>
```

**Comment by msaine** [comment]
Not trying to be obtuse, but what VIM keystrokes allow copying from one instance of vim to another? This is not a case of split windows under vim it is two or more files open in vim and copying text between.

________________________________

**Comment by msaine** [comment]
Never thought about that, I will look into it.

________________________________

**Comment by msaine** [comment]
h-east

You might have hit on it. I added the lines you suggested and will watch to see if it solves the problem,

wouldn't be first time these old fat fingers got me into trouble.

Thanks

**Comment by chrisbra** [comment]
> Not trying to be obtuse, but what VIM keystrokes allow copying from one instance of vim to another? 

To access the clipboard you would use the `+` or `*` register. See `:h quoteplus`.

**Comment by chrisbra** [comment]
I am closing this as not actionable.
