### ISSUE TITLE
g:netrw_browsex_viewer no longer breaks string into args

### ISSUE THREAD

**Issue by smemsh** [vim/vim#16185]
### Steps to reproduce

1. `let g:netrw_browsex_viewer = 'program arg1 arg2'`
2. edit a file with sole content: `https://www.google.com/`
3. hover cursor over char 1
4. enter `gx` key sequence

Prior to 8b0fa7a565 this worked.  Upon trace, the problem is that it's trying to stat/exec the whole `program arg1 arg2` as the executable name (argv[0]).  This is a regression for me as I need to pass args.  It worked fine with the old runtime files, prior to mentioned commit.

### Expected behaviour

break the string up into the argument vector

### Version of Vim

9.1.0906

### Environment

linux/st-256color/bash

**Comment by chrisbra** [comment]
thanks. Can you please test the following patch?
```diff
diff --git a/runtime/autoload/netrw.vim b/runtime/autoload/netrw.vim
index 9650f6dff..10a42bf61 100644
--- a/runtime/autoload/netrw.vim
+++ b/runtime/autoload/netrw.vim
@@ -5076,7 +5076,9 @@ elseif executable('open')
 endif

 fun! s:viewer()
-  if exists('g:netrw_browsex_viewer') && executable(g:netrw_browsex_viewer)
+  " g:netrw_browsex_viewer could be a string of program + its arguments,
+  " test if first argument is executable
+  if exists('g:netrw_browsex_viewer') && executable(split(g:netrw_browsex_viewer)[0])
     " extract any viewing options.  Assumes that they're set apart by spaces.
     "   call Decho("extract any viewing options from g:netrw_browsex_viewer<".g:netrw_browsex_viewer.">",'~'.expand("<slnum>"))
     if g:netrw_browsex_viewer =~ '\s'
```

**Comment by smemsh** [comment]
@chrisbra Confirmed, it works for my use case, thanks.  However, we might also consider:
```
'program "arg with spaces"'
```
Maybe it should check the type of `g:netrw_browsex_viewer` and, if a list, use those strings to make the argument vector directy.  However the above fix might be good enough for most use cases...

**Comment by chrisbra** [comment]
I think this may still work, as this should be done using the original netrw logic. However the only thing that might break is if you use `'C:\Program Files\Google\chrome.exe'` or similar things which are not in the path. Not sure if we need to try to make this work as well.
