### ISSUE TITLE
Vim's map function sometimes does not report error E1012 (vim9script)

### ISSUE THREAD

**Issue by msoyka2024** [vim/vim#16191]
### Steps to reproduce

Using the code below, call Using_Fctn_Arg()

```
    vim9script
    def g:Using_Fctn_Arg()
	var lNumber: list<number>
	lNumber = map(range(1, 4), 'NbrToStr(v:val)')
    enddef
    def NbrToStr(n: number): string
	return printf('%3s', n)
    enddef
```

The call generates the following runtime error:

```
    Error detected while processing function Using_Fctn_Arg:
    line 2:
    E1012: Type mismatch; expected list<number> but got list<string>
```

The range function is documented to return `list<number>` and so map() should also return `list<number>` but apparently returns `list<string>`.

If the range() call is replaced by a variable of type `list<number>`:

```
    def g:Using_Var_Arg()
	var lNumber: list<number>
	var mapIn = range(1, 4)
	lNumber = map(mapIn, 'NbrToStr(v:val)')
    enddef
```

Vim correctly generates the following error:

```
    Error detected while processing function Using_Var_Arg:
    line 3:
    E1012: Type mismatch; expected number but got string in map()
```

### Expected behaviour

Invoking Using_Fctn_Arg() should generate error E1012 as Using_Var_arg() does.

### Version of Vim

9.1.901

### Environment

windows 10

**Comment by zzzyxwvut** [comment]
> The range function is documented to return `list<number>` and so map() should also return `list<number>` but apparently returns `list<string>`.

According to `map()`'s documentation entry,

https://github.com/vim/vim/blob/e7ea4ba723a2ab2bc49baa07d1dec54a197fb64b/runtime/doc/builtin.txt#L6590-L6591

If you want a list of *numbers* from `map()`, use a function  
for `{expr2}` whose return type is `number`:

```vim
vim9script

def g:Using_To_Number_Lambda_Expr()
    var lNumber: list<number>
    lNumber = map(range(1, 4), (_, n: number): number => type(n))
    echo lNumber
enddef

def g:Using_To_Number_Lambda_Expr_()
    var lNumber: list<number>
    var lRange: list<number> = range(1, 4)
    lNumber = mapnew(lRange, (_, n: number): number => type(n))
    echo lNumber
enddef

g:Using_To_Number_Lambda_Expr()
g:Using_To_Number_Lambda_Expr_()
```

If you want a list of *strings* from `map()`, use a function  
for `{expr2}` whose return type is `string`:

```vim
vim9script

def NbrToStr(n: number): string
    return printf('%3s', n)
enddef

def g:Using_To_String_Lambda_Expr()
    var lText: list<string>
    lText = map(range(1, 4), (_, n: number): string => NbrToStr(n))
    echo lText
enddef

def g:Using_To_String_Lambda_Expr_()
    var lText: list<string>
    var lRange: list<number> = range(1, 4)
    lText = mapnew(lRange, (_, n: number): string => NbrToStr(n))
    echo lText
enddef

g:Using_To_String_Lambda_Expr()
g:Using_To_String_Lambda_Expr_()
```

Each of your examples raises `E1012`.

**Comment by chrisbra** [comment]
closing
