### ISSUE TITLE
Re-selecting block selection with [count]v in "exclusive" is incorrect

### ISSUE THREAD

**Issue by citizenmatt** [vim/vim#16202]
### Steps to reproduce

1. `:set selection=exclusive`
1. Select a block of text with `<C-V>`, such as both instances of the word `ipsum` (`w`, `<C-V>`, `j`, `e`)

        ```
        Lorem ipsum
        Lorem ipsum
        ```

1. Perform a Visual operation, e.g. `d`, then undo `u`
2. Move the caret to the start of the first line and reselect the Visual with `1v`

### Expected behaviour

Both instances of the word `Lorem` should be selected with block selection. Instead, only the first four characters in each word are selected. Contrast with character-wise selection of the word `ipsum`. This will correctly reselect the entire word.

### Version of Vim

9.1.727

### Environment

MacOS 15.1.1. MacVim 9.1.727

**Comment by chrisbra** [comment]
Hm, I was looking into it and noticed something funny. It seems the normal mode `e` command moves in visual mode one character further than expected, e.g. it places the cursor on the space *after* the word, not on the last character in the word. It makes sense, since this means the last character of the word will be selected, but it is still a bit unexpected. And I cannot seem to find this behaviour documented.

**Comment by citizenmatt** [comment]
I think all inclusive motions are adjusted when `'selection'` is "exclusive", so the selection remains the same, but the caret position is different. You can see it with `g_` too. Have a text line with trailing space and `vg_` in "inclusive" will place the caret on the last non-whitespace character in the line. With "exclusive", `vg_` will act like the motion is exclusive, and put the caret _after_ the last non-whitespace character. Same with `vt{char}` and `vf{char}`.

Exclusive motions aren't adjusted. The final caret location is the same, meaning the selection is now one character shorter (see `vw`).

I can't find any documentation for it either, but it is intuitive. Looks like all appropriate inclusive motions (everything apart from `$` and friends, which it wouldn't affect) call `adjust_for_sel`, which will increment the caret.

https://github.com/vim/vim/blob/6cc3027e544e4389bd665140511a3d347490b102/src/normal.c#L6690-L6705

**Comment by chrisbra** [comment]
hm, thanks. I'll add some documentation to it. I created #16219 to fix this issue
