### ISSUE TITLE
getcurpos() buffer number is always 0

### ISSUE THREAD

**Issue by bimlas** [vim/vim#1621]
I thought `getcurpos()` would return the buffer number of the cursor (as the first element in the list), but it's always 0. Note, that this is not tested at all (the buffer number is never watched): https://github.com/vim/vim/blob/37175409d766ce67f2548dffa6d73451379b5737/src/testdir/test_cursor_func.vim

As [romainl said](https://www.reddit.com/r/vim/comments/63ypyo/buffer_number_of_getcurpos_is_allways_0/dfy33yq/) on [Reddit](https://www.reddit.com/r/vim/comments/63ypyo/buffer_number_of_getcurpos_is_allways_0/):
> The doc doesn't say if bufnr is supposed to be an actual buffer number or not so it looks like a case of incomplete documentation and undefined behavior.

### Steps to reproduce

- Open up Vim
- `:help getcurpos()`
- `:echo getcurpos()` -> [**0**, 4377, 8, 0, 57]
- `:echo bufnr('.')` -> **1**

### Version

Vim 8.0.0543 (x86) on Windows 7 (x64)

**Comment by jottkaerr** [comment]
From `:help getcurpos()`:
```
getcurpos()	Get the position of the cursor.  This is like getpos('.'), but
		includes an extra item in the list:
		    [bufnum, lnum, col, off, curswant] ~
		The "curswant" number is the preferred column when moving the
		cursor vertically.
```
And from `:help getpos()`:
```
getpos({expr})	Get the position for {expr}.  For possible values of {expr}
		see |line()|.  For getting the cursor position see
		|getcurpos()|.
		The result is a |List| with four numbers:
		    [bufnum, lnum, col, off]
		"bufnum" is zero, unless a mark like '0 or 'A is used, then it
		is the buffer number of the mark.
```

**Comment by bimlas** [comment]
The truncated part of `:help getcurpos()`:

```
		This can be used to save and restore the cursor position:
			let save_cursor = getcurpos()
			MoveTheCursorAround
			call setpos('.', save_cursor)
```

If `MoveTheCursorAround` jumps to another buffer, then `setpos()` will not work as expected, just moves the cursor only in the current buffer. This isn't documented in `getcurpos()` nor `setpos()` and it's an inconsistent behavior.

**Comment by brammool** [comment]
That is correct, you can't use setpos() to move to another window or buffer, you can only move inside the current window.  I'll add a remark about that.
