### ISSUE TITLE
`set selection=exclusive` and inclusive motion behavior

### ISSUE THREAD

**Issue by aidancz** [vim/vim#16235]
### Steps to reproduce

1. prepare files:

`a.txt`:

```
(abc abc)
```

`minimal.vim`:

```
set selection=exclusive
```

2. `vim --clean -u minimal.vim a.txt`
3. move cursor to first `a`
4. press `ve`

### Expected behaviour

cursor should be placed on the first `c` instead of the space

If this is to make the behavior of `ved` the same as `de`, then when `selection=inclusive`, please make the behavior of `vld` the same as `dl`.

### Version of Vim

9.1

### Environment

6.12.4-arch1-1

**Comment by chrisbra** [comment]
That is expected behaviour to make sure the selected region is correct. This behaviour was just documented here: https://vimhelp.org/motion.txt.html#inclusive-motion-selection-exclusive

**Comment by aidancz** [comment]
> That is expected behaviour to make sure the selected region is correct. This behaviour was just documented here: https://vimhelp.org/motion.txt.html#inclusive-motion-selection-exclusive

I would argue that if this behavior is expected, the corresponding one should also exist:

When 'selection' is "inclusive", Visual mode is active and an exclusive
motion has been used, the cursor position will be adjusted by another
character to the left

**Comment by aidancz** [comment]
After some consideration, I believe the current behavior is reasonable.

What is truly missing is an option to make motions behave the same way in normal mode and visual mode.

As a workaround, I have a series of mappings like this:

```vim
nnoremap e ve<esc>
```
