### ISSUE TITLE
Statusline of gvim 8 dosen't behave what it should be.

### ISSUE THREAD

**Issue by chenzhihuai1990** [vim/vim#1623]
The vim documents says:

> When all items in a group becomes an empty string (i.e. flags that are not set) and a minwid is not set for > the group, the whole group will become empty.

But it doesn't work in vim8.0 if I set highlight group. e.g
`let &stl='%(%#Keyword#ccc%{""}ccc%)'`
It should show nothing, but it still shows 'cccccc' in statusline.

It works as expectation if there are no highlight group in them. BTW, it works in vim7.4.1023 (indeed, all the previous version work).

**Comment by chrisbra** [comment]
The group is not empty, so it behaves as expected. This has been caused because of this [bug report](https://groups.google.com/d/msg/vim_dev/sb1jmVirXPU/mPhvDnZ-CwAJ) and has been fixed in patch [7.4.1511](https://groups.google.com/d/msg/vim_dev/PtCKHRjZ8hU/Ek6ckoEkFgAJ)
