### ISSUE TITLE
Swedish "kind file" message translation wrong

### ISSUE THREAD

**Issue by oljemark** [vim/vim#16237]
At https://github.com/vim/vim/blob/master/src/po/sv.po#L1437 you have " snäll fil", a file that is being kind (not mean), whereas cross-comparing the Spanish and Finnish translations I think you meant " -filtyp", file type?

**Describe the solution you'd like**
A correct translation

**Comment by chrisbra** [comment]
Can you please create a PR?

**Comment by k-takata** [comment]
This message can be shown when doing the following steps:
1. Create a tags file with the ctags command in a source code directory. E.g. `ctags -R`
2. `:set wop=tagfile`
3. Type `:tselect `, then type Ctrl-D to show the completion list.

Here is a sample screenshot:
![image](https://github.com/user-attachments/assets/4efb5d75-de2c-4367-a9a6-a44f3ed44806)

As you may see, "kind" and "file" are used for the headers of each column.
So, "kind" and "file" should be translated as separate words. And "kind" here means type.
