### ISSUE TITLE
`set selection=exclusive` can't select empty region

### ISSUE THREAD

**Issue by aidancz** [vim/vim#16234]
### Steps to reproduce

1. prepare files:

`a.txt`:

```
(a)
```

`minimal.vim`:

```
set selection=exclusive
```

2. `vim --clean -u minimal.vim a.txt`
3. move cursor on `a`
4. press `vd`

### Expected behaviour

delete nothing

### Version of Vim

9.1

### Environment

6.12.4-arch1-1

**Comment by chrisbra** [comment]
you cannot really select nothing in visual mode. I would think this behaviour is therefore expected.

**Comment by aidancz** [comment]
> you cannot really select nothing in visual mode

Please consider making it possible

The current behavior is logically incorrect

Selecting empty areas is useful, as it makes mapping in operator-pending mode more convenient.
