### ISSUE TITLE
netrw: Opening a URI-encoded URL by `gx` will open corrupted URL

### ISSUE THREAD

**Issue by KSR-Yasuda** [vim/vim#16252]
### Steps to reproduce

1. Write some URL-encoded URL such as `https://www.example.com/#:~:text=%E3%81%82` in some buffer.
2. Put cursor on the URL, and run `gx` shortcut (= `NetrwBrowseX`) in normal mode.
3. It tries to open the target URL in the web browser, but the opening page URL is corrupted  
   like `https://www.example.com/#:~:text=/%E3/%81/%82`.

[Here](https://github.com/vim/vim/blob/21c37d7f695077efe6df57806ff35da79adce1d5/runtime/autoload/netrw.vim#L5202) it is calling extra `escape()` that causes this.
Due to this, it would fails with paths including `#` or `%`, the characters escaped here.

The comment for it says they've added the `escape()` since [`shellescape(..., 1)` in `netrw#Open()`](https://github.com/vim/vim/blob/21c37d7f695077efe6df57806ff35da79adce1d5/runtime/autoload/netrw.vim#L5114) is insufficient.

Is the `escape()` really required now?

### Expected behaviour

It opens the correct URL.

### Version of Vim

9.1.866

### Environment

* Operating system: Windows 11 Pro 64bit 24H2 (Version 10.0.26100.2605)
    * MSYS2 (msys2-runtime 3.5.4-8)
* Terminal: mintty '3.7.6' 2024-09-24_05:10 (x86_64-pc-msys)
    * Value of `$TERM`: xterm-256color
    * Shell: GNU bash, version 5.2.37(1)-release (x86_64-pc-msys)

* Vim `g:netrw_browsex_viewer` value: `start`

* Browser: Google Chrome v131.0.6778.140

**Comment by chrisbra** [comment]
I remember when that comment was made, I wondered myself about it whether this is true. At least I cannot reproduce it:
```
:exe '!echo ' .. shellescape('one#two%three four',1)
```
seems to work just fine. So perhaps we can just get rid of the double escape here? @Konfekt

**Comment by Konfekt** [comment]
> I wondered myself about it whether this is true

Everybody is wondering about what's happening.

Testing was not exhaustive, but it made common URLs with hashes such as`https://github.com/vim/vim/issues/16252/#issue-2749168683` work, so I assumed `%` (current buffer) needed similar treatment to `#` (alternate buffer).
On Ubuntu 22.04 with Vim 9.1.919, removing that escaping of `#` breaks it.

It may be that only `#` is causing trouble, as with

```vim
" runtime/autoload/netrw.vim (line 5202)
call netrw#Open(escape(fname, '#'))
```

`gx` opens the URL https://www.example.com/#:~:text=%E3%81%82 fine.

What's curious is that @KSR-Yasuda 's URL is escaped with forward instead of backward slashes, though: `https://www.example.com/#:~:text=/%E3/%81/%82`.
On Ubuntu 22.04 with Vim 9.1.919 backward slashes are added at `%` but a forward slash at `#`: `https://www.example.com//#:~:text=\%E3\%81\%82`.

**Comment by Konfekt** [comment]
Since @KSR-Yasuda uses MSYS on Microsoft Windows, it also looks like `[shellescape(..., 1)](https://github.com/vim/vim/blob/21c37d7f695077efe6df57806ff35da79adce1d5/runtime/autoload/netrw.vim#L5114)` does not work as intended here? Maybe there are two issues at play.

**Comment by KSR-Yasuda** [comment]
> What's curious is that @KSR-Yasuda 's URL is escaped with forward instead of backward slashes, though: `https://www.example.com/#:~:text=/%E3/%81/%82`. On Ubuntu 22.04 with Vim 9.1.919 backward slashes are added at `%` but a forward slash at `#`: `https://www.example.com//#:~:text=\%E3\%81\%82`.

Probably it is because of path conversion of MSYS2 env.

Manually executing `start 'https://www.example.com/\#:~:text=\%E3\%81\%82'` opens
`https://www.example.com//#:~:text=/%E3/%81/%82`.
Every `\` chars are replaced with `/`.

Even if you drop `%`-escape, `#`-escape may cause the problem in MSYS2.
For `https://www.example.com/#:~:text=%E3%81%82#a`,
it opens the URL `https://www.example.com/#:~:text=%E3%81%82/#a` (extra `/` for the latter `#`).

**Comment by Konfekt** [comment]
> Even if you drop %-escape, #-escape may cause the problem in MSYS2.

Maybe ` "" //b` are not required here if you use the Git Bash version of MSYS2

```vim
" autoload/netrw.vim (line 5032)
exe 'silent !start "" //b' a:args s:redir() | redraw!
```

or `cygpath` is installed in MSYS2 

> Probably it is because of path conversion of MSYS2 env.

One could prepend `MSYS_NO_PATHCONV=1`on Git Bash according to https://github.com/git-for-windows/build-extra/blob/main/ReleaseNotes.md#known-issues or `MSYS2_ARG_CONV_EXCL='*'` on MSYS2 according to https://www.msys2.org/docs/filesystem-paths/ 

I wonder if the authors @vim-jp of https://github.com/vim-jp/vital.vim maybe already worked out all the edge cases long ago and could give definite replies.

**Comment by Konfekt** [comment]
@KSR-Yasuda If you could find a combination of above knobs that suits you?

**Comment by KSR-Yasuda** [comment]
> > [shellescape(..., 1)](https://github.com/vim/vim/blob/21c37d7f695077efe6df57806ff35da79adce1d5/runtime/autoload/netrw.vim#L5114)
> 
> Since @KSR-Yasuda uses MSYS on Microsoft Windows, it also looks like [shellescape(..., 1)](https://github.com/vim/vim/blob/21c37d7f695077efe6df57806ff35da79adce1d5/runtime/autoload/netrw.vim#L5114) does not work as intended here?

`shellescape(..., 1)` itself looks fine in MSYS2 env.

```vim
shellescape('https://www.example.com#:~:text=%E3%81%82#a', 1)

" => 'https://www.example.com\#:~:text=\%E3\%81\%82\#a'
```

Probably it runs
the vim command like `:exe 'silent !start ' . 'https://www.example.com\#:~:text=\%E3\%81\%82\#a'`,
that implies the bash command `start https://www.example.com#:~:text=%E3%81%82#a`.

Rather Ubuntu env. is exceptional to need extra `escape()`, isn't it?

[There defines `netrw#Launch()` for each env](https://github.com/vim/vim/blob/21c37d7f695077efe6df57806ff35da79adce1d5/runtime/autoload/netrw.vim#L5018).
If still extra `escape()` is needed, shouldn't you call it there?
(The one for Ubuntu would be [this](https://github.com/vim/vim/blob/21c37d7f695077efe6df57806ff35da79adce1d5/runtime/autoload/netrw.vim#L5051)?)

Otherwise, instead of `escape()`, you might had better quote the path.

> > Even if you drop %-escape, #-escape may cause the problem in MSYS2.
> 
> Maybe ` "" //b` are not required here if you use the Git Bash version of MSYS2
> 
> ```viml
> " autoload/netrw.vim (line 5032)
> exe 'silent !start "" //b' a:args s:redir() | redraw!
> ```

No, without  ` "" //b`, it opened command prompt... (`start` command would have went wrong.)

My env is [pure MSYS2](https://www.msys2.org/), if you mean Git for Windows.

**Comment by Konfekt** [comment]
> Rather Ubuntu env. is exceptional to need extra escape(), isn't it?
...  If still extra escape() is needed, shouldn't you call it there?

Not so sure how special an issue of Ubuntu that is. Same phenomenon on Debian 12 and thus likely its forks such as Linux Mint and others.

> No, without  "" //b, it opened command prompt... 

Thank you, that's good to know.

> My env is [pure MSYS2](https://www.msys2.org/)

Okay, does it come with cygpath? The above link  https://www.msys2.org/docs/filesystem-paths/ claimed so, but I think mine didn't. So you are using the `start` script?

**Comment by Konfekt** [comment]
> so I assume we can get rid of the double escape() ?

Strange, but we can try and time will tell

> The path converstion thingy is tricky however. Not sure we should try to open that can of worms.

One could prepend MSYS_NO_PATHCONV=1on Git Bash according to [git-for-windows/build-extra@main/ReleaseNotes.md#known-issues](https://github.com/git-for-windows/build-extra/blob/main/ReleaseNotes.md?rgh-link-date=2024-12-19T08%3A53%3A59Z#known-issues) or MSYS2_ARG_CONV_EXCL='*' on MSYS2 according to [msys2.org/docs/filesystem-paths](https://www.msys2.org/docs/filesystem-paths/)

If @KSR-Yasuda has success with either of them, why not? Git Bash and MSYS2 can be distinguished by environment variables

**Comment by KSR-Yasuda** [comment]
> One could prepend MSYS_NO_PATHCONV=1on Git Bash according to [git-for-windows/build-extra@main/ReleaseNotes.md#known-issues](https://github.com/git-for-windows/build-extra/blob/main/ReleaseNotes.md?rgh-link-date=2024-12-19T08%3A53%3A59Z#known-issues) or MSYS2_ARG_CONV_EXCL='*' on MSYS2 according to [msys2.org/docs/filesystem-paths](https://www.msys2.org/docs/filesystem-paths/)
> 
> If @KSR-Yasuda has success with either of them, why not? Git Bash and MSYS2 can be distinguished by environment variables

Anyway, I think it is not the point.
Appearance of extra `/` or `\` itself would be wrong already.

`MSYS_NO_PATHCONV` is just an option to stop path separator conversion, isn't it?

> Even if you drop `%`-escape, `#`-escape may cause the problem in MSYS2. For `https://www.example.com/#:~:text=%E3%81%82#a`, it opens the URL `https://www.example.com/#:~:text=%E3%81%82/#a` (extra `/` for the latter `#`).

As I said, even `escape(fname, '#')` introduces extra `/` before `#`.

For the first `#`, it does not make a problem.
But the latter `#`, the anchor part `#ANCHOR#a` and `#ANCHOR/#a` are completely different things.

**Comment by Konfekt** [comment]
> Anyway, I think it is not the point.
Appearance of extra / or \ itself would be wrong already.
MSYS_NO_PATHCONV is just an option to stop path separator conversion, isn't it?

Yes, that's the second issue, that eventually should also be fixed if additional escaping has to be done.

I think what caused confusion is that despite

```vim
" autoload/netrw.vim (lines 5112-5114)
fun! netrw#Open(file) abort
  call netrw#Launch(s:viewer() .. ' ' .. shellescape(a:file, 1))
endf
```

`:Open https://github.com/vim/vim/issues/16252#issuecomment-2556009926` still does not work, but requires escaping `#`. However, Itt's better to force the user to escape it if this causes issues elsewhere.

**Comment by KSR-Yasuda** [comment]
> `:Open https://github.com/vim/vim/issues/16252#issuecomment-2556009926` still does not work, but requires escaping `#`. However, Itt's better to force the user to escape it if this causes issues elsewhere.

So, you've checked via `:Open` command?
Isn't it an issue of vim command execution, that `#` is replaced with alternate file name,
as `:e https://github.com/vim/vim/issues/16252#issuecomment-2556009926` behaves the same.


Then, if you need to fix the `:Open` case, shouldn't you change [its command definition](https://github.com/vim/vim/blob/af0fed598889cbc2fbf286c1e282c27b92215e8d/runtime/plugin/netrwPlugin.vim#L40)?

But I'm not sure if they might want to call `:Open` for the alternate file by `#`.

**Comment by Konfekt** [comment]
> Isn't it an issue of vim command execution, that # is replaced with alternate file name

Yes, that's what supposedly `1` is for in above

> shellescape(a:file, 1))

**Comment by Shougo** [comment]
> :Open https://github.com/vim/vim/issues/16252#issuecomment-2556009926 still does not work, but requires escaping #. However, Itt's better to force the user to escape it if this causes issues elsewhere.

OK.  It is reproduced.  `#` seems considered alternate file.

**Comment by Shougo** [comment]
Hm...  `gx` with `https://github.com/vim/vim/issues/16252#issuecomment-2556009926` works in current code.

**Comment by Shougo** [comment]
I have removed https://github.com/vim/vim/blob/21c37d7f695077efe6df57806ff35da79adce1d5/runtime/autoload/netrw.vim#L5202 's `escape()` and it work for me.

Please provide the failed example?

**Comment by Konfekt** [comment]
As above, I vaguely remember it was somewhat inscrutably the only place where `:Open` would accept `#` as well while keeping `gx` working. Alas, this is not the case using MSYS2 on Windows, so I agree that breaking `:Open` is preferable to breaking `gx`, as the user can fix the latter and is less likely to use it (hitting `gx` on a URL is more common than pasting/writing a URL in the command-line)

**Comment by Shougo** [comment]
OK.  So the escape should be removed.

`:Open` may be broken in some cases, but users can escape it manually.

**Comment by Shougo** [comment]
Can you create the PR?  If not, I can create it instead.
