### ISSUE TITLE
why the return type of `py3 vim.current.buffer.options["filetype"]` is bytes but not string?

### ISSUE THREAD

**Issue by Yggdroot** [vim/vim#1625]
For example, `py3 print( repr(vim.current.buffer.options["filetype"]) )` will print `b'cpp'` but not `'cpp'`, while neovim will return a string.
I think it's not reasonable to return a bytes.

**Comment by vim-ml** [comment]
2017-04-10 5:54 GMT+03:00 Yggdroot <vim-dev-github@256bit.org>:
> For example, py3 print( repr(vim.current.buffer.options["filetype"]) ) will
> print b'cpp' but not 'cpp',
> while neovim will return a string.
> I think it's not reasonable to return a bytes.

Most Vim strings are not guaranteed to contain valid &encoding-encoded
values, unlike another option (using surrogateescape for invalid
characters) this forces you to think about handling possible
conversion errors right away, before you run into related bugs.

Also Python 2 has used bytes() always.

**Comment by chrisbra** [comment]
closing then.

**Comment by k-takata** [comment]
Related: neovim/neovim#5768

If someone wants to use `str` instead of `bytes`, maybe a workaround like the following can be used:

```python
filetype = vim.current.buffer.options['filetype']
if isinstance(filetype, bytes):
    filetype = filetype.decode(vim.options['enc'].decode())
```

(If the option string contains invalid unicode character, this will fail.)

**Comment by Yggdroot** [comment]
@k-takata Thanks. Currently, my workaround is:
```python
filetype = vim.eval("getbufvar(%d, '&filetype')" % vim.current.buffer.number)
```

**Comment by k-takata** [comment]
In that case, you can use:

```python
filetype = vim.eval("getbufvar('%', '&filetype')")
```

**Comment by Yggdroot** [comment]
It's just a example, there are scenarios that I want to get other buffers' filetype, not just the current one.
