### ISSUE TITLE
split up autoload/netrw.vim

### ISSUE THREAD

**Issue by Konfekt** [vim/vim#16254]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
It is hard to load `autoload/netrw.vim` on a slow single-core computer and maneuver it afterwards due to its size.

**Describe the solution you'd like**
split it up sensibly, maybe starting by moving some of the level one fold marker sections into separate files where the `Shared Browsing Support` section needs to be split up according to the other sections' dependencies.

**Describe alternatives you've considered**
make netrw optional, replace it by some other Vim file manager plug-in using more intuitive Vim UI similar to oil.vim / https://github.com/qpkorr/vim-renamer or completely rewrite it in more modern syntax.
The last option seems Herculean (and maybe this requested task already is); 
the former two would throw away much functionality people have grown accustomed to. 

**Additional context**
The pull request https://github.com/vim/vim/pull/16248 reformats its indents and observed thatin  legacy viml the function names bound to the file name was only a convention, ... so moving some netrw#... functions in another file it should be fine.

**Comment by chrisbra** [comment]
I don't like this. How will splitting things up into additional files speed up loading files on a slow single-core pc? In contrast, splitting up into several files may hurt loading performance, especially if this is on a shared drive and a potential anti-virus is called several times. I have seen exactly this issue with vim-airline.

**Comment by Konfekt** [comment]
The idea is that one usually looks at an exerpt. I just found that I am almost unwilling to open this file due to its delay on loading.
