### ISSUE TITLE
filetype.vim works on any buffer

### ISSUE THREAD

**Issue by hoofcushion** [vim/vim#16261]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
filetype.vim uses BufRead,BufNewFile,StdinReadPost events to detect filetype, which wouldn't triggers on every buffer, this may causing many werid behavior of some buffer can't get filetype detected.

**Describe the solution you'd like**
Just use "VimEnter" and "BufAdd" instead, that make filetype detect works on every buffer.

**Describe alternatives you've considered**
pass

**Additional context**
pass

**Comment by chrisbra** [comment]
I am not going to change anything because it "may cause weird behaviour", without any specifics. Such a change has a huge potential for introducing regressions, so let's keep it like it is currently.

**Comment by hoofcushion** [comment]
I want to define a directory filetype for file explorer plugin but filetypedetect doesn't trigger on directory buffer, that is the problem I met. So I wonder why not let detect every buffer filetype equally when it been add?

**Comment by hoofcushion** [comment]
Directory is just a file, vim attach file in buffer, why treat them different than other buffer, shouldn't there be a builtin directory filetype? for syntax highlight and many filetype specific plugin, vim use filetype option, shouldn't file explorer be the same?

**Comment by chrisbra** [comment]
you can create your own new filetypes already and you can manually run `:filetype detec` as well.
