### ISSUE TITLE
Vim sends last character of line twice when running in xterm.js

### ISSUE THREAD

**Issue by LucianBuzzo** [vim/vim#1626]
I'm working on a new feature for xterm.js that allows line reflow.
https://github.com/sourcelair/xterm.js/pull/609
I've found that when vim wraps a line that is too long, it sends the last character of the line twice.
Here is an example of the string data sent at 26 cols:
```
[m[H[2J[1;1Hlorem ipsum dolor sit amet[2;1H[1m[34m~                         [3;1H~
```
Then if I resize to 25 cols I get this:
```
[m[H[2J[1;1Hlorem ipsum dolor sit amee[2;1Ht
[1m[34m~ 
```
As you can see the `e` in `amet` is duplicated and vim sends a line with a length of 26 characters, even though the terminal width is set to 25 cols.

If I reduce the size by 1 column again, I get this:
```
[m[H[2J[1;1Hlorem ipsum dolor sit amm[2;1Het
[1m[34m~           
```
This time the `m` is duplicated, as it's the last character on that row.

I've found that this is happening when the terminal is `xterm-color` and `vt100`.

I'm not sure why this is happening and I was hoping the the Vim community could shed some light on this issue.

**Comment by brammool** [comment]
Lucian Buzzo wrote:

> I'm working on a new feature for xterm.js that allows line reflow.
> https://github.com/sourcelair/xterm.js/pull/609
> I've found that when vim wraps a line that is too long, it sends the last character of the line twice.
> Here is an example of the string data sent at 26 cols:
> ```
> [m[H[2J[1;1Hlorem ipsum dolor sit amet[2;1H[1m[34m~                         [3;1H~
> ```
> Then if I resize to 25 cols I get this:
> ```
> [m[H[2J[1;1Hlorem ipsum dolor sit amee[2;1Ht
> [1m[34m~ 
> ```
> As you can see the `e` in `amet` is duplicated and vim sends a line with a length of 26 characters, even though the terminal width is set to 25 cols.
> 
> If I reduce the size by 1 column again, I get this:
> ```
> [m[H[2J[1;1Hlorem ipsum dolor sit amm[2;1Het
> [1m[34m~           
> ```
> This time the `m` is duplicated, as it's the last character on that row.
> 
> I've found that this is happening when the terminal is `xterm-color` and `vt100`.
> 
> I'm not sure why this is happening and I was hoping the the Vim
> community could shed some light on this issue.

This is intentional.  It's used to signal that the line continues,
instead of has a line break.  See src/screen.c, around line 5710.

xterm.js should replicate the behavior.

-- 
Yah, well, we had to carve our electrons out of driftwood we'd
find.  In the winter.  Uphill.  Both ways.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by LucianBuzzo** [comment]
@brammool Thanks for the response!
What do you mean by "xterm.js should replicate the behavior" ? Perhaps I am being dense, but I don't understand what you mean 😄 

*update*: I believe this [SO answer](http://stackoverflow.com/questions/31360385/an-obscure-one-documented-vt100-soft-wrap-escape-sequence#answer-31361979) Describes the behaviour referring to?

**Comment by brammool** [comment]
Lucian Buzzo wrote:

> @brammool Thanks for the response!
> What do you mean by "xterm.js should replicate the behavior" ? Perhaps
> I am being dense, but I don't understand what you mean 𐟘„ 

If xterm.js is to be compatible with xterm, it should handle this
sequence of characters in the same way.  Assuming you support
copy&paste.

-- 
Not too long ago, unzipping in public was illegal...

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by LucianBuzzo** [comment]
@brammool Thanks for your help, I think this issue can be closed.

**Comment by thecrazzymouse** [comment]
This issue is still present in xterm.js
