### ISSUE TITLE
(gvim:17432): Gtk-WARNING **: 22:20:02.014: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node tab owner GtkNotebook)

### ISSUE THREAD

**Issue by twjobs2005** [vim/vim#16277]
### Steps to reproduce

run gvim on fedora silverblue, in the terminal, I see loads of these warnings:

```
(gvim:17432): Gtk-WARNING **: 22:20:02.014: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node tab owner GtkNotebook)
```

### Expected behaviour

no warnings in terminal

### Version of Vim

VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Nov 15 2024 00:00:00) Included patches: 1-866 Modified by <bugzilla@redhat.com> Compiled by <bugzilla@redhat.com> Huge version with GTK3 GUI.  Features included (+) or not (-): +acl                +cryptv             +fork()             +modify_fname       +persistent_undo    -sun_workshop       +viminfo +arabic             +cscope             +gettext            +mouse              +popupwin           +syntax             +virtualedit +autocmd            +cursorbind         -hangul_input       +mouseshape         +postscript         +tag_binary         +visual +autochdir          +cursorshape        +iconv              +mouse_dec          +printer            -tag_old_static     +visualextra -autoservername     +dialog_con_gui     +insert_expand      +mouse_gpm          +profile            -tag_any_white      +vreplace +balloon_eval       +diff               +ipv6               -mouse_jsbterm      -python             -tcl                +wildignore +balloon_eval_term  +digraphs           +job                +mouse_netterm      +python3/dyn-stable +termguicolors      +wildmenu +browse             +dnd                +jumplist           +mouse_sgr          +quickfix           +terminal           +windows ++builtin_terms     -ebcdic             +keymap             -mouse_sysmouse     +reltime            +terminfo           +writebackup +byte_offset        +emacs_tags         +lambda             +mouse_urxvt        +rightleft          +termresponse       +X11 +channel            +eval               +langmap            +mouse_xterm        +ruby/dyn           +textobjects        +xattr +cindent            +ex_extra           +libcall            +multi_byte         +scrollbind         +textprop           -xfontset +clientserver       +extra_search       +linebreak          +multi_lang         +signs              +timers             +xim +clipboard          -farsi              +lispindent         -mzscheme           +smartindent        +title              +xpm +cmdline_compl      +file_in_path       +listcmds           +netbeans_intg      +sodium             +toolbar            +xsmp_interact +cmdline_hist       +find_in_path       +localmap           +num64              +sound              +user_commands      +xterm_clipboard +cmdline_info       +float              +lua/dyn            +packages           +spell              +vartabs            -xterm_save +comments           +folding            +menu               +path_extra         +startuptime        +vertsplit +conceal            -footer             +mksession          +perl/dyn           +statusline         +vim9script    system vimrc file: "/etc/vimrc"      user vimrc file: "$HOME/.vimrc"  2nd user vimrc file: "~/.vim/vimrc"  3rd user vimrc file: "~/.config/vim/vimrc"       user exrc file: "$HOME/.exrc"   system gvimrc file: "$VIM/gvimrc"     user gvimrc file: "$HOME/.gvimrc" 2nd user gvimrc file: "~/.vim/gvimrc" 3rd user gvimrc file: "~/.config/vim/gvimrc"        defaults file: "$VIMRUNTIME/defaults.vim"     system menu file: "$VIMRUNTIME/menu.vim"   fall-back for $VIM: "/usr/share/vim" Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf- 2.0 -I/usr/include/atk-1.0 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/cloudprovider s -I/usr/include/webp -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/fribidi -I /usr/include/libxml2 -I/usr/include/pixman-1 -I/usr/include/libpng16 -I/usr/include/gio-unix-2.0 -DWITH_GZFILEOP -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/sysprof-6 -pthread -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wno-complain-wrong-lang -Werror=format-s ecurity -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 - march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -D_GNU_ SOURCE -D_FILE_OFFSET_BITS=64 -DSYS_VIMRC_FILE=/etc/vimrc -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 Linking: gcc -Wl,--enable-new-dtags -Wl,-z,relro -Wl,--as-needed -Wl,-z,pack-relative-relocs -Wl,-z,now -Wl,--build-id=sha1 -Wl,-z,relro -Wl,--as-needed -Wl,- z,pack-relative-relocs -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -Wl,--build-id=sha1 -specs=/usr/ lib/rpm/redhat/redhat-package-notes -L/usr/local/lib -o vim -lgtk-3 -lgdk-3 -lz -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgd k_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lSM -lICE -lm -lselinux -lncurses -lcanberra -lsodium -lrt -lacl -lattr -lgpm

### Environment

Linux fedora 6.11.8-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Nov 14 20:38:18 UTC 2024 x86_64 GNU/Linux

$ echo $TERM
xterm-256color

GNOME Terminal
Version 3.50.1 for GNOME 45
A terminal emulator for the GNOME desktop
Using VTE version 0.76.4 +BIDI +GNUTLS +ICU +SYSTEMD

**Comment by chrisbra** [comment]
that is a known problem, that the GTK libraries are a bit chatty. This has been discussed several times already. 
If you know how to fix those warnings, feel free to create a PR, otherwise this is non-actionable issue here.
