### ISSUE TITLE
Password recovery needs some attention.

### ISSUE THREAD

**Issue by codingismycraft** [vim/vim#16282]
This is how the screen reads when asking for password recovery:

![image](https://github.com/user-attachments/assets/d473f96a-074c-4f33-9aa1-6240ffd86f57)

Needs some attention, either it should fixed somehow or simply removed.

**Comment by chrisbra** [comment]
What is wrong with this please? Instead of Bram, you can ask me

**Comment by codingismycraft** [comment]
don't you think that you should change the names and also add your name / email there?

**Comment by codingismycraft** [comment]
Anyway, i managed to create a new account which i will use later... thank you.

**Comment by chrisbra** [comment]
Thanks, I managed to update the page. Please next time, provide the URL of the page you noticed and not just a screen shot.
