### ISSUE TITLE
The enum indentation is wrong in Vim9 script

### ISSUE THREAD

**Issue by h-east** [vim/vim#16289]
### Steps to reproduce

1. Prepare the following file (e.vim).
```vim
vim9script

enum Color
White,
Red,
Black
endenum

var co: Color = Color.Black
echo "co: " .. string(co)

# vim:ts=4 sw=0
```
2. Run Vim.
```bash
$ vim --clean e.vim
```
3. Format(re-indent) the entire file.
```vim
ggVG=
```

Result:
```vim
vim9script

enum Color
    White,
        Red,             <--- Wrong
        Black            <--- Wrong
endenum

var co: Color = Color.Black
echo "co: " .. string(co)

# vim:et ts=4 sw=0
```

### Expected behaviour

```vim
vim9script

enum Color
    White,
    Red,
    Black
endenum

var co: Color = Color.Black
echo "co: " .. string(co)

# vim:et ts=4 sw=0
```

### Version of Vim

9.1.0955

### Environment

Ubuntu 22.04.5 LTS

### Logs and stack traces

```shell
none
```

**Comment by JimZhouZZY** [comment]
> But that is a different issue, since indentation is filetype specific

The `python` issue wasn't an issue. It's my fault. I compiled and ran vim in macOS without noticing that defaults.vim is stored at different directory. I'm sorry for the misleading.
