### ISSUE TITLE
Make :center work on visual selections

### ISSUE THREAD

**Issue by myarcana** [vim/vim#16295]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
Yes it's very hard to center text selections in vim at the moment

**Describe the solution you'd like**

```
                       w  h sa sb sl sr ....
             width |  |  1  0  0  0 -1 -1  0  0 |
            height |  |  0  1 -1 -1  0  0  0  0 |
       space_above |  |  0  0  0  0  0  0  0  0 |
       space_below |  |  0  0  0  0  0  0  0  0 |
        space_left |  |  0  0  0  0  0  0  0  0 |  
       space_right |  |  0  0  0  0  0  0  0  0 |
               ... |  |  0  0  0  0  0  0  0  0 |
```

`CTRL-V` selecting the first column and entering the command `:'<,'>center` should center the column not the lines

**Describe alternatives you've considered**
- Writing my own centering function in Vim
- writing my own script to center lines and putting it in my path

Neither of these solutions are trivial sadly. I think basic text manipulation like this should be part of Vim in the first place.

Vim provides `:center`, it just doesn't center anything except lines, even if you've made a visual selection.

**Comment by chrisbra** [comment]
ex commands always work linewise. There is already an issue for, to make it work column wise using e.g. `` `<`` marker value. But so far, this does not exist. It's part of the todo list and there is an issue about it already (sorry don't find it currently), so I am closing this as duplicate

**Comment by chrisbra** [comment]
Here it is: #3292
