### ISSUE TITLE
Cannot edit my script upload to fix some data

### ISSUE THREAD

**Issue by codingismycraft** [vim/vim#16294]
Have just uploaded this script:

https://www.vim.org/scripts/script.php?script_id=6143

![image](https://github.com/user-attachments/assets/79f2ed64-fece-45c9-9e0e-4f8baf6c599c)

I need to change the description and the details as well but i cannot find the way how to do it.  The plugin repo is https://github.com/codingismycraft/VimMyTools

Please advice.. Thank you.

**Comment by chrisbra** [comment]
When logging into www.vim.org, you see a list of all your plugins. You need to click on Edit Details, e.g. for my scripts, it would be here:
![grafik](https://github.com/user-attachments/assets/a38babc2-08ee-41de-b1bd-bc85bd5140cd)

**Comment by adaptaware** [comment]
This solves my issue! Thank you.
