### ISSUE TITLE
add base64enc() and base64dec() to vim's builtin functions

### ISSUE THREAD

**Issue by networkhermit** [vim/vim#16291]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

If vim plan to [add OSC 52 clipboard support](https://github.com/vim/vim/issues/14995) in the future, I think adding the base64 encoding and decoding functions is a good start.

Base64 is a ubiquitous but simple encoding scheme, it is not hard to implement. It's funny that base64 encoding and decoding functions are in the TODO list for Vim since 13 years ago:

https://github.com/vim/vim/blob/f07c10d7bb770547ab88cf479621b06a16c09b55/runtime/doc/todo.txt#L4201-L4202

**Describe the solution you'd like**
Add base64enc() and base64dec() to vim's builtin functions, possibly with configurable line wrap like base64 in GNU Coreutils:

```text
       -w, --wrap=COLS
              wrap encoded lines after COLS character (default 76).  Use 0 to disable line wrapping
```

**Describe alternatives you've considered**

1. Use system specific base64 command
```text
if gnu_linux
    call system('base64 -aaa')
else if musl_linux
    call system('base64 -bbb')
else if freebsd
    call system('base64 -ccc')
else if  openbsd
    call system('base64 -ddd')
else if darwin
    call system('base64 -eee')
else if win64
    call system('base64 -fff')
end
```
2. Use a vim plugin implemented base64 encoding from scratch, or just DIY

https://github.com/equal-l2/vim-base64/blob/670ecd29f7fd0cd48ef7172b298f1c49bcc8344a/autoload/vital/_base64/Data/Base64.vim#L30-L34

**Additional context**

Both Neovim and Emacs have these builtins:

https://neovim.io/doc/user/lua.html#_vim.base64

https://www.gnu.org/software/emacs/manual/html_node/elisp/Base-64.html

**Comment by Tachi107** [comment]
Please keep in mind that doing base64 properly is not as trivial as it seems, due to flexibility of the base64 standard. To whoever wants to implement this, be sure to have a look at the “Base64 Malleability in Practice” paper: <https://eprint.iacr.org/2022/361.pdf>
