### ISSUE TITLE
Vim does not restore terminal cursor correctly

### ISSUE THREAD

**Issue by mario-grgic** [vim/vim#1630]
I am using Vim 8.0.559 on macOS 10.12.4 and iTerm 2 version 3.0.15. If I clear the terminal screen and enter and immediately exit vim, the terminal cursor is scrolled to the bottom of the terminal window with a screen full of empty lines. 

I have managed to trace this down to the following change in runtime/defaults.vim

```
" When the +eval feature is missing, the set command above will be skipped.
" Use a trick to reset compatible only when the +eval feature is missing.
if 1
  nnoremap : :"
endif
silent normal :set nocompatible
if 1
  nunmap :
endif
```

If I comment these lines out in runtime/defaults.vim, everything is back to normal and when vim exits, the terminal cursor is returned on the next line after vim invocation. 

My Vim version info:

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2017 08:58:49)
MacOS X (unix) version
Included patches: 1-559
Compiled by Mario Grgic
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +cursorbind      +fullscreen      +modify_fname    +path_extra      +syntax          +viminfo
+arabic          +cursorshape     -gettext         +mouse           +perl            +tag_binary      +vreplace
+autocmd         +dialog_con_gui  -hangul_input    +mouseshape      +persistent_undo +tag_old_static  +wildignore
+balloon_eval    +diff            +iconv           +mouse_dec       +postscript      -tag_any_white   +wildmenu
+browse          +digraphs        +insert_expand   -mouse_gpm       +printer         -tcl             +windows
++builtin_terms  +dnd             +job             -mouse_jsbterm   +profile         +termguicolors   +writebackup
+byte_offset     -ebcdic          +jumplist        +mouse_netterm   +python/dyn      +terminfo        -X11
+channel         +emacs_tags      +keymap          +mouse_sgr       +python3/dyn     +termresponse    -xfontset
+cindent         +eval            +lambda          -mouse_sysmouse  +quickfix        +textobjects     +xim
+clientserver    +ex_extra        +langmap         +mouse_urxvt     +reltime         +timers          -xpm
+clipboard       +extra_search    +libcall         +mouse_xterm     +rightleft       +title           -xsmp
+cmdline_compl   +farsi           +linebreak       +multi_byte      +ruby            +toolbar         -xterm_clipboard
+cmdline_hist    +file_in_path    +lispindent      +multi_lang      +scrollbind      +transparency    -xterm_save
+cmdline_info    +find_in_path    +listcmds        -mzscheme        +signs           +user_commands   
+comments        +float           +localmap        +netbeans_intg   +smartindent     +vertsplit       
+conceal         +folding         -lua             +num64           +startuptime     +virtualedit     
+cryptv          -footer          +menu            +odbeditor       +statusline      +visual          
+cscope          +fork()          +mksession       +packages        -sun_workshop    +visualextra     
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -L/usr/local/lib -L. -L/usr/local/lib  -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm -lncurses  -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl    -framework Ruby    
```

**Comment by chrisbra** [comment]
I cannot reproduce in neither putty nor gnome-terminal.
What does this output: `:set term? t_ti? t_te?`

**Comment by mario-grgic** [comment]
This is what I got as output:

```
term=xterm-256color
t_ti=^[[?1049h
t_te=^[[?1049l
```

**Comment by chrisbra** [comment]
sorry, scratch that, I just could successfully reproduce this.

**Comment by chrisbra** [comment]
It's the :silent command modifier, that breaks it. I think it happens because internally, Vim goes to the last line and echoes the (commented out command).

**Comment by chrisbra** [comment]
How about the following hack:
```patch
diff --git a/runtime/defaults.vim b/runtime/defaults.vim
index f4d22bde4..83da2d9be 100644
--- a/runtime/defaults.vim
+++ b/runtime/defaults.vim
@@ -28,13 +28,9 @@ endif

 " When the +eval feature is missing, the set command above will be skipped.
 " Use a trick to reset compatible only when the +eval feature is missing.
-if 1
-  nnoremap : :"
-endif
-silent normal :set nocompatible
-if 1
-  nunmap :
-endif
+silent! while 0
+set nocompatible
+silent! endwhile

 " Allow backspacing over everything in insert mode.
 set backspace=indent,eol,start
```

This works for a huge and small build. However, this looks hacky, perhaps my previous mentioned [solution](https://github.com/vim/vim/issues/1604#issuecomment-290638359) is better suited?

**Comment by mario-grgic** [comment]
The above patch works, however I can't comment if it is the best or most elegant way to set nocompatible if eval is not present.

**Comment by brammool** [comment]
Christian Brabandt wrote:

> How about the following hack:
> ```patch
> diff --git a/runtime/defaults.vim b/runtime/defaults.vim
> index f4d22bde4..83da2d9be 100644
> --- a/runtime/defaults.vim
> +++ b/runtime/defaults.vim
> @@ -28,13 +28,9 @@ endif
> 
>  " When the +eval feature is missing, the set command above will be skipped.
>  " Use a trick to reset compatible only when the +eval feature is missing.
> -if 1
> -  nnoremap : :"
> -endif
> -silent normal :set nocompatible
> -if 1
> -  nunmap :
> -endif
> +silent! while 0
> +set nocompatible
> +silent! endwhile
> 
>  " Allow backspacing over everything in insert mode.
>  set backspace=indent,eol,start
> ```
> 
> This works for a huge and small build. However, this looks hacky, perhaps my previous mentioned [solution](https://github.com/vim/vim/issues/1604#issuecomment-290638359) is better suited?

It appears to work.  I wonder if ignoring the error has any side effect.
Nothing comes to mind.

-- 
You were lucky to have a LAKE! There were a hundred and sixty of
us living in a small shoebox in the middle of the road.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
Are `:while` and `:endwhile` just ignored in a small build? If so, isn't it enough to use `:while 0`?

```vim
while 0
set nocompatible
endwhile
```

**Comment by chrisbra** [comment]
This will throw an error on small and tiny builds, as they do not understand the `:while|:endwhile` commands. Therefore I silenced those errors with `:silent!`

**Comment by k-takata** [comment]
I tried with v8.0.0525 small build on Cygwin, and neither `:while` nor `:endwhile` throws errors.
It seems that they are silently ignored.

**Comment by chrisbra** [comment]
Oh really? I see this:
```shell
Error detected while processing /home/chrisbra/local/share/vim/vim80/defaults.vim:
line   31:
E319: Sorry, the command is not available in this version: while 0
line   33:
E319: Sorry, the command is not available in this version: endwhile
Press ENTER or type command to continue
```

This is:
```
:version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2017 21:37:18)
Included patches: 1-559
Compiled by chrisbra@debian
Small version without GUI.  Features included (+) or not (-):
[...]
```

**Comment by k-takata** [comment]
Hmm, E319 is set at here: https://github.com/vim/vim/blob/ea588154d00aec288e48b344b2685e46bea99cd6/src/ex_docmd.c#L4807
And `ex_while` is defined to `ex_ni` when '-eval': https://github.com/vim/vim/blob/ea588154d00aec288e48b344b2685e46bea99cd6/src/ex_docmd.c#L376

Then, someone set `eap->skip` to `TRUE` in my environment?

**Comment by chrisbra** [comment]
well, perhaps it would be a general good idea to set `ea->skip=TRUE` for non-eval builds, so that one can use:
```
while 0
" do something only in non-eval builds
endwhile
```

**Comment by brammool** [comment]
Christian Brabandt wrote:

> well, perhaps it would be a general good idea to set `ea->skip=TRUE` for non-eval builds, so that one can use:
> ```
> while 0
> " do something only in non-eval builds
> endwhile
> ```

This may lead to surprises if the user expects an error message in the
tiny version.  The script may do something weird without any hint why.

-- 
Not too long ago, cut and paste was done with scissors and glue...

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
alternatively use 
```
if 0
" do something in tiny mode
endif
```
That would be symmetric to the current `if 1` trick and that one is widely used already.
I don't even know if the `if 1` trick, is currently documented.

BTW: I don't think anybody would rely or expect an error message in that case in the small or tiny builds (but the part between the `while/endwhile` would already be evaluated).

**Comment by brammool** [comment]
Christian Brabandt wrote:

> alternatively use 
> ```
> if 0
> " do something in tiny mode
> endif
> ```
> That would be symmetric to the current `if 1` trick and that one is
> widely used already.  I don't even know if the `if 1` trick, is
> currently documented.

This is documented:

	From Vim version 4.5 until 5.0, every Ex command in
	between the ":if" and ":endif" is ignored.  These two
	commands were just to allow for future expansions in a
	backward compatible way.  Nesting was allowed.  Note
	that any ":else" or ":elseif" was ignored, the "else"
	part was not executed either.

Also see :help no-eval-feature

> BTW: I don't think anybody would rely or expect an error message in
> that case in the small or tiny builds (but the part between the
> `while/endwhile` would already be evaluated).

-- 
Apologies for taking up the bandwidth with the apology.  Anything else I
can apologise for ...... er no can't think of anything, sorry about that.
		Andy Hunt (Member of British Olympic Apology Squad)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
