### ISSUE TITLE
Compilation with mingw does not work

### ISSUE THREAD

**Issue by avorop** [vim/vim#16301]
### Steps to reproduce

1. Obtained vim from github
2. cd vim\src
3. Run "mingw32-make -f Make_ming.mak ARCH=x86_64 gvim.exe"
4. At the end following error is displayed:
g++ -I. -Iproto -DWIN32 -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 -DHAVE_PATHDEF -DFEAT_HUGE -DHAVE_STDINT_H -DHAVE_GETTEXT -DHAVE_LOCALE_H -DDYNAMIC_GETTEXT -DFEAT_CSCOPE -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL -DFEAT_IPV6 -DFEAT_TERMINAL -DFEAT_SOUND -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DFEAT_DIRECTX_COLOR_EMOJI -DFEAT_GUI_MSWIN -DFEAT_CLIPBOARD -DFEAT_MBYTE_IME -DDYNAMIC_IME -DDYNAMIC_ICONV -pipe -march=x86-64 -Wall -DFEAT_XPM_W32 -I xpm/x64/include -I xpm/x64/../include -O3 -fomit-frame-pointer -freg-struct-return -ffunction-sections -fno-asynchronous-unwind-tables -s -municode -mwindows -Wl,--gc-sections -o gvim.exe gobjx86-64/alloc.o gobjx86-64/arabic.o gobjx86-64/arglist.o gobjx86-64/autocmd.o gobjx86-64/beval.o gobjx86-64/blob.o gobjx86-64/blowfish.o gobjx86-64/buffer.o gobjx86-64/bufwrite.o gobjx86-64/change.o gobjx86-64/charset.o gobjx86-64/cindent.o gobjx86-64/clientserver.o gobjx86-64/clipboard.o gobjx86-64/cmdexpand.o gobjx86-64/cmdhist.o gobjx86-64/crypt.o gobjx86-64/crypt_zip.o gobjx86-64/debugger.o gobjx86-64/dict.o gobjx86-64/diff.o gobjx86-64/digraph.o gobjx86-64/drawline.o gobjx86-64/drawscreen.o gobjx86-64/edit.o gobjx86-64/eval.o gobjx86-64/evalbuffer.o gobjx86-64/evalfunc.o gobjx86-64/evalvars.o gobjx86-64/evalwindow.o gobjx86-64/ex_cmds.o gobjx86-64/ex_cmds2.o gobjx86-64/ex_docmd.o gobjx86-64/ex_eval.o gobjx86-64/ex_getln.o gobjx86-64/fileio.o gobjx86-64/filepath.o gobjx86-64/findfile.o gobjx86-64/float.o gobjx86-64/fold.o gobjx86-64/getchar.o gobjx86-64/gc.o gobjx86-64/gui_xim.o gobjx86-64/hardcopy.o gobjx86-64/hashtab.o gobjx86-64/help.o gobjx86-64/highlight.o gobjx86-64/if_cscope.o gobjx86-64/indent.o gobjx86-64/insexpand.o gobjx86-64/json.o gobjx86-64/list.o gobjx86-64/locale.o gobjx86-64/logfile.o gobjx86-64/main.o gobjx86-64/map.o gobjx86-64/mark.o gobjx86-64/match.o gobjx86-64/memfile.o gobjx86-64/memline.o gobjx86-64/menu.o gobjx86-64/message.o gobjx86-64/misc1.o gobjx86-64/misc2.o gobjx86-64/mouse.o gobjx86-64/move.o gobjx86-64/mbyte.o gobjx86-64/normal.o gobjx86-64/ops.o gobjx86-64/option.o gobjx86-64/optionstr.o gobjx86-64/os_mswin.o gobjx86-64/os_win32.o gobjx86-64/pathdef.o gobjx86-64/popupmenu.o gobjx86-64/popupwin.o gobjx86-64/profiler.o gobjx86-64/quickfix.o gobjx86-64/regexp.o gobjx86-64/register.o gobjx86-64/scriptfile.o gobjx86-64/screen.o gobjx86-64/search.o gobjx86-64/session.o gobjx86-64/sha256.o gobjx86-64/sign.o gobjx86-64/spell.o gobjx86-64/spellfile.o gobjx86-64/spellsuggest.o gobjx86-64/strings.o gobjx86-64/syntax.o gobjx86-64/tag.o gobjx86-64/term.o gobjx86-64/testing.o gobjx86-64/textformat.o gobjx86-64/textobject.o gobjx86-64/textprop.o gobjx86-64/time.o gobjx86-64/typval.o gobjx86-64/ui.o gobjx86-64/undo.o gobjx86-64/usercmd.o gobjx86-64/userfunc.o gobjx86-64/version.o gobjx86-64/vim9class.o gobjx86-64/vim9cmds.o gobjx86-64/vim9compile.o gobjx86-64/vim9execute.o gobjx86-64/vim9expr.o gobjx86-64/vim9instr.o gobjx86-64/vim9script.o gobjx86-64/vim9type.o gobjx86-64/viminfo.o gobjx86-64/winclip.o gobjx86-64/window.o gobjx86-64/os_w32exe.o gobjx86-64/vimres.o gobjx86-64/netbeans.o gobjx86-64/job.o gobjx86-64/channel.o gobjx86-64/gui_dwrite.o gobjx86-64/xpm_w32.o gobjx86-64/terminal.o gobjx86-64/vterm_encoding.o gobjx86-64/vterm_keyboard.o gobjx86-64/vterm_mouse.o gobjx86-64/vterm_parser.o gobjx86-64/vterm_pen.o gobjx86-64/vterm_screen.o gobjx86-64/vterm_state.o gobjx86-64/vterm_unicode.o gobjx86-64/vterm_vterm.o gobjx86-64/sound.o gobjx86-64/xdiffi.o gobjx86-64/xemit.o gobjx86-64/xprepare.o gobjx86-64/xutils.o gobjx86-64/xhistogram.o gobjx86-64/xpatience.o gobjx86-64/gui.o gobjx86-64/gui_w32.o gobjx86-64/gui_beval.o -lkernel32 -luser32 -lgdi32 -ladvapi32 -lcomdlg32 -lcomctl32 -lnetapi32 -lversion -lws2_32 -ld2d1 -ldwrite -Lxpm/x64/lib -lXpm -lwinmm -lole32 -luuid
C:/Users/voropaev.andrey/StrawberryPerl/c/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: xpm/x64/lib/libXpm.a(RdFToI.o):RdFToI.c:(.text+0xf2): undefined reference to `__imp___iob_func'
C:/Users/voropaev.andrey/StrawberryPerl/c/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: xpm/x64/lib/libXpm.a(RdFToI.o):RdFToI.c:(.text+0x12f): undefined reference to `__imp___iob_func'
collect2.exe: error: ld returned 1 exit status
gmake: *** [Make_cyg_ming.mak:1169: gvim.exe] Error 1

### Expected behaviour

I hoped to get gvim.exe as described in INSTALLpc.txt

### Version of Vim

Latest sources

### Environment

Windows 11 (cmd.exe)
gcc --version
gcc (MinGW-W64 x86_64-ucrt-posix-seh, built by Brecht Sanders, r8) 13.2.0

This MinGW is part of StrawberryPerl-5.40. But I've tried it also with latest MinGW (14.2) obtained from winlibs.com, the outcome was the same.

**Comment by chrisbra** [comment]
Did this work before? What patch broke it? Try to disable xpm support

**Comment by avorop** [comment]
Well, some years ago I compiled version 9.0 with mingw in
StrawberryPerl-5.32. Possibly, this is connected to the change of C-library
under Windows. I'll try to get  mingw with support for old library

**Comment by avorop** [comment]
Exactly, I should have thought about it earlier. Now I've used

gcc --version
gcc (MinGW-W64 x86_64-msvcrt-posix-seh, built by Brecht Sanders, r2) 14.2.0

This version uses old msvcrt library instead of new ucrt. Now compilation was successful. And I've looked at documentation for libXpm.a at http://gnuwin32.sf.net. They mention it explicitly there, that the version is compiled against msvcrt.

Now, to compile gvim with perl I'll have to use version of gcc that comes with perl. Let's see if it works without support for Xpm.

**Comment by chrisbra** [comment]
There seems to be an issue with the distributed libXpm.a file. It seems like `__imp___iob_func` is no longer defined. I don't know how to fix this, but you should be able to build using `mingw32-make -f Make_ming.mak ARCH=x86_64 XPM=no gvim.exe`

Ah, I just see your newer message. Can you please suggest a change for `INSTALLpc.txt` to clarify this please?

**Comment by avorop** [comment]
You mean, I should push a patch for INSTALLpc.txt? Or some text in this thread would be enough?

**Comment by chrisbra** [comment]
Yes some doc patch for INSTALLpc.txt mentioning that msvcrt runtime is required for XPM support

**Comment by avorop** [comment]
Ok, I've created pull-request. Hopefully I did it correctly, github always gives me headache :)

I close this issue, since I could compile gvim with support for Perl and I don't need support for XPM. Maybe in the future it would be possible to get libXpm.a for both C-Libraries, since UCRT is considered to be better than MSVCRT.
