### ISSUE TITLE
Kitty Keyboard Protocol not used by default in Ghostty

### ISSUE THREAD

**Issue by 00-kat** [vim/vim#16318]
### Steps to reproduce

1. Download Ghostty (see https://ghostty.org/download).
2. Launch Vim in Ghostty and run `:verbose map`.
3. Note how `Kitty keyboard protocol: On` doesn't show up.
4. Set `keyprotocol` to `kitty:kitty,foot:kitty,ghostty:kitty,wezterm:kitty,xterm:mok2` in the `vimrc`, then restart vim.
5. Repeat step two and note how `Kitty keyboard protocol: On` now shows up.

### Expected behaviour

The Kitty Keyboard protocol to be enabled by default since Ghostty supports it; i.e. the value of `keyprotocol` to be `kitty:kitty,foot:kitty,ghostty:kitty,wezterm:kitty,xterm:mok2` by default.

I would open a PR but I don't know how to change the default values of options.

(Note: it would also be nice if Vim were able to [query for support](https://sw.kovidgoyal.net/kitty/keyboard-protocol/#detection-of-support-for-this-protocol) instead of hardcoding `$TERM` patterns.)

### Version of Vim

9.1.0954

### Environment

Operating System: Arch Linux (rolling)
Terminal: Ghostty 1.0.1-main+35b9ceee
Value of `$TERM`: `xterm-ghostty`
Shell: Fish 3.7.1

**Comment by dezza** [comment]
hey as new ghostty user do you have settings to share? I get some stray chars in buffer sometimes.

**Comment by 00-kat** [comment]
Not sure what that means, and that's probably off-topic to this issue, but I've never seen anything of that form; the only interesting settings I have are [this hunk of text](https://sw.kovidgoyal.net/kitty/faq/#using-a-color-theme-with-a-background-color-does-not-work-well-in-vim) (minus the background color erase one).

**Comment by dezza** [comment]
Weird. I get it quite often. Maybe its because I use https://github.com/akinomyoga/ble.sh

`let &t_ut = ''`

Might try that, just wanted to ask as you're the only one I saw mention and I didn't know if this kitty protocol was related to the issue.

Its not just one seq, several also generic ones.

**Comment by 00-kat** [comment]
Ghostty supports BCE so that one wouldn't help. We should probably move to some other forum though (I'm not too familiar with vim's policies so not sure where however).

**Comment by dezza** [comment]
Since the issue is closed I doubt anyone cares, but I'm on `#vim` on libera, dza there. 

https://github.com/ghostty-org/ghostty/discussions/11680

Seems this is related.
