### ISSUE TITLE
Stabby functions don't work in string interpolation

### ISSUE THREAD

**Issue by igbanam** [vim/vim#16317]
### Steps to reproduce

Store the following script as `issue.vim`

```vim
vim9script

class Foo
  def Cost(nums: list<number>): number
    # This is the same if nums->typename() is any other type
    return nums[0] * nums[1]
  enddef

  def ShowCost()
    var g = [4, 5]
    # echo $"Cost is: {this.Cost(g)}"
    echo $"Cost is: {g->this.Cost()}"
  enddef
endclass

var d = Foo.new()
d.ShowCost()
```

Then open Vim with

```
vim --clean -S issue.vim
```

### Expected behaviour

Expected this to run the script as expected, since — I assume — string interpolation should evaluate what's within the `{` braces `}` as string. For some reason, this doesn't work with stabby function calls. I expected the stabby function call interpolation to be equivalent to the commented line above.

**Expected**

```
Cost is: 20
```

**Got**

```
Error detected while compiling command line..script /path/to/test.vim[17]..function <SNR>10_Foo.ShowCost:
line    3:
E1028: Compiling :def function failed
Press ENTER or type command to continue
```

### Version of Vim

VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Dec 20 2024 18:45:06) macOS version - arm64 Included patches: 1-950 Compiled by Homebrew

### Environment

OS X
iTerm
xterm-256color-italic
zsh

**Comment by bfrg** [comment]
The error only shows up when the function is a class method. When `Cost()` is a free function, it works:

```vim
vim9script

def Cost(nums: list<number>): number
    return nums[0] * nums[1]
enddef

class Foo
    def ShowCost()
        var g = [4, 5]
        echo $"Cost is: {g->Cost()}"
    enddef
endclass

var d = Foo.new()
d.ShowCost()
```
