### ISSUE TITLE
Segfault moving selection up after scrolling in omnifunc list

### ISSUE THREAD

**Issue by snyman** [vim/vim#16329]
### Steps to reproduce

1. `/usr/bin/vim --clean`
2. Paste into buffer:
```vimscript
function s:test_omnifunc(findstart, base)
    if a:findstart
        return 0
    else
        return mapnew(range(100), '"item " .. v:val')
    endif
endfunction

set omnifunc=s:test_omnifunc
```
3. `:so`
4. `i<C-x><C-o>`
5. Move selection in omnifunc list down until it scrolls, using down arrow
6. Try to move selection back up to the top, using up arrow

### Expected behaviour

It shouldn't segfault, it should let me move the selection all the way back to the top of the list.

### Version of Vim

9.1.954

### Environment

OS: Arch Linux
Terminal: Alacritty and urxvt
Value of $TERM: `alacritty` and `rxvt-unicode-256color` respectively
Shell: bash

### Logs and stack traces

```shell
Vim: Caught deadly signal SEGV
Vim: preserving files...
Vim: Finished.
Segmentation fault (core dumped)
```

**Comment by chrisbra** [comment]
I think this has already been fixed, please try latest master

**Comment by snyman** [comment]
Yup, fixed in master, my bad.
