### ISSUE TITLE
job_stop(some_job, "int") closes the channel even if process does not quit

### ISSUE THREAD

**Issue by martingms** [vim/vim#1632]
I'm not sure whether this is intended or not, but it seems like there currently is no way of sending SIGINT to a job through the jobs api without also closing the channel. My usecase is using the PostgreSQL-client `psql` that uses SIGINT to cancel a query, for example.

To reproduce:

```
let job = job_start("psql", {"mode": "raw"})
call job_stop(job, "int")
call ch_sendraw(job_getchannel(job), "select * from test_table;\n")
```
Errors with `E906: not an open channel`

I see in [channel.c](https://github.com/vim/vim/blob/master/src/channel.c#L5156) that SIGHUP is special cased to avoid this.

Vim version 8.0.329

I'd be happy to submit a patch if this is something that the project wants to be possible.

**Comment by brammool** [comment]
Martin Gammelsæter wrote:

> I'm not sure whether this is intended or not, but it seems like there
> currently is no way of sending SIGINT to a job through the jobs api
> without also closing the channel.
> 
> To reproduce:
> 
> ```
> let job = job_start("bash", {"mode": "raw"})
> call job_stop(job, "int")
> call ch_sendraw(job_getchannel(job), "ls\n")
> ```
> Errors with `E906: not an open channel`
> 
> Vim version 8.0.329

Currently we only check for "hup".  We should probably do it the other
way around, only assume a job gets killed by "term" and "kill".

-- 
Q:  Why do ducks have flat feet?
A:  To stamp out forest fires.

Q:  Why do elephants have flat feet?
A:  To stamp out flaming ducks.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
2017-04-11 23:43 GMT+03:00 Bram Moolenaar <vim-dev-github@256bit.org>:
>
> Martin Gammelsæter wrote:
>
>> I'm not sure whether this is intended or not, but it seems like there
>> currently is no way of sending SIGINT to a job through the jobs api
>> without also closing the channel.
>>
>> To reproduce:
>>
>> ```
>> let job = job_start("bash", {"mode": "raw"})
>> call job_stop(job, "int")
>> call ch_sendraw(job_getchannel(job), "ls\n")
>> ```
>> Errors with `E906: not an open channel`
>>
>> Vim version 8.0.329
>
> Currently we only check for "hup". We should probably do it the other
> way around, only assume a job gets killed by "term" and "kill".

SIGTERM may be ignored. Also provoke doing something (including
writing to the channel) before exiting. I do not know how second
variant is going to be handled, but first definitely implies that
`term` needs not close a channel.

And I would rather go explicit: *no* signals close the channel at all,
channel should only be closed explicitly or when corresponding file
descriptor is closed by the child (or by its death).

---

BTW, I found in `:h job_stop()` “The status of the job isn't checked,
the operation will even be done when Vim thinks the job isn't
running.” Does this mean that Vim will kill random process which
happened to take former jobs PID if job happened to die and be
collected (as opposed to leaving a zombie) in this case?

**Comment by martingms** [comment]
>  And I would rather go explicit: *no* signals close the channel at all, channel should only be closed explicitly or when corresponding file descriptor is closed by the child (or by its death).

This seems like what I'd expect, atleast. As you mention, SIGTERM might be ignored as well.

**Comment by vim-ml** [comment]
Nikolay Pavlov wrote:

> 2017-04-11 23:43 GMT+03:00 Bram Moolenaar <vim-dev-github@256bit.org>:
> >
> > Martin Gammelsæter wrote:
> >
> >> I'm not sure whether this is intended or not, but it seems like there
> >> currently is no way of sending SIGINT to a job through the jobs api
> >> without also closing the channel.
> >>
> >> To reproduce:
> >>
> >> ```
> >> let job = job_start("bash", {"mode": "raw"})
> >> call job_stop(job, "int")
> >> call ch_sendraw(job_getchannel(job), "ls\n")
> >> ```
> >> Errors with `E906: not an open channel`
> >>
> >> Vim version 8.0.329
> >
> > Currently we only check for "hup". We should probably do it the other
> > way around, only assume a job gets killed by "term" and "kill".
> 
> SIGTERM may be ignored. Also provoke doing something (including
> writing to the channel) before exiting. I do not know how second
> variant is going to be handled, but first definitely implies that
> `term` needs not close a channel.
> 
> And I would rather go explicit: *no* signals close the channel at all,
> channel should only be closed explicitly or when corresponding file
> descriptor is closed by the child (or by its death).

It's possible.  Although I would think that after killing a job the
channel should not be used, that smells like wrong behavior.

> BTW, I found in `:h job_stop()` “The status of the job isn't checked,
> the operation will even be done when Vim thinks the job isn't
> running.” Does this mean that Vim will kill random process which
> happened to take former jobs PID if job happened to die and be
> collected (as opposed to leaving a zombie) in this case?

Even when we would check if the job exists, it could still be another
one.  Perhaps using waitpid() might work.  We could check
job->jv_status.

-- 
Why doesn't Tarzan have a beard?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by martingms** [comment]
> It's possible. Although I would think that after killing a job the channel should not be used, that smells like wrong behavior.

Well, we could simply reverse the special-casing, and close the channel on SIGKILL but leave it alone for the rest if that is important.
