### ISSUE TITLE
VIm fails to build in OBS on Test_set_ttytype

### ISSUE THREAD

**Issue by ghost** [vim/vim#1634]
Hello,

When building vim-8.0-0563 (or master) in the Open Build Service, I obtain a ttytype related error during tests.
I would like to add that I have seen bug [#1601](https://github.com/vim/vim/issues/1601) and that I have checked that the code I want to build includes the patch mentionned in that bug report.
Test checks failed with the following output:
`[  310s] From test_options.vim:`
`[  310s] Found errors in Test_set_ttytype():`
`[  310s] function RunTheTest[24]..Test_set_ttytype line 22: set ttype=xxx did not fail`
`[  310s] `
`[  310s] From test_startup.vim:`
`[  310s] Found errors in Test_default_term():`
`[  310s] function RunTheTest[24]..Test_default_term line 9: Pattern 'defaulting to ''ansi''' does not match 'E437: terminal capability "cm" required\r\nPress ENTER or type command to continue\r\r\n'`
As vim is built in a virtual machine, the spec file adds the following to set the TERM:
`export TERM=linux`

Any idea about what's causing this even with the appropriate patch ?
Regards.

**Comment by brammool** [comment]
sogalboogalsky wrote:

> When building vim-8.0-0563 (or master) in the Open Build Service, I obtain a ttytype related error during tests.
> I would like to add that I have seen bug [#1601](https://github.com/vim/vim/issues/1601) and that I have checked that the code I want to build includes the patch mentionned in that bug report.
> Test checks failed with the following output:
> `[  310s] From test_options.vim:`
> `[  310s] Found errors in Test_set_ttytype():`
> `[  310s] function RunTheTest[24]..Test_set_ttytype line 22: set ttype=xxx did not fail`
> `[  310s] `
> `[  310s] From test_startup.vim:`
> `[  310s] Found errors in Test_default_term():`
> `[  310s] function RunTheTest[24]..Test_default_term line 9: Pattern 'defaulting to ''ansi''' does not match 'E437: terminal capability "cm" required\r\nPress ENTER or type command to continue\r\r\n'`
> As vim is built in a virtual machine, the spec file adds the following to set the TERM:
> `export TERM=linux`
> 
> Any idea about what's causing this even with the appropriate patch ?

Can you check if src/auto/config.h contains:

	#define TGETENT_ZERO_ERR 0

Also check auto/config.log for hints around the tgetent() test.
For Linux it should be:

configure:11510: checking what tgetent() returns for an unknown terminal
configure:11536: gcc -o conftest -g -Wall -Wextra -Wshadow -Wmissing-prototypes -Wunreachable-code -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1  -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E   -L/usr/local/lib conftest.c -ltinfo -lnsl  -lselinux   >&5
conftest.c:84:1: warning: return type defaults to 'int' [-Wimplicit-int]
 main()
 ^~~~
configure:11536: $? = 0
configure:11536: ./conftest
configure:11536: $? = 0
configure:11551: result: zero


-- 
What the word 'politics' means: 'Poli' in Latin meaning 'many' and 'tics'
meaning 'bloodsucking creatures'.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ghost** [comment]
> Can you check if src/auto/config.h contains: #define TGETENT_ZERO_ERR 0 

Indeed, this declaration was absent when I try to build the .rpm for the distribution (but Ok when compiling directly from source).

Thank a lot for pointing that out, that lead me understand what caused this errors: 
the way the .spec file calls _./configure_ with option `--with-tlib=`

Thanks again.
