### ISSUE TITLE
Arrow keys not working

### ISSUE THREAD

**Issue by BeeBreeze** [vim/vim#1636]
Hi,
   Thanks for vim.
   Usually,  I control my office PC by ssh.  For convenience, I use tmux to run cmd.
   The issue is that if I use vim in a window of tmux in xshell5 for a very long time, like 8 h, and sometimes
I may pause vim with C+z, the arrow keys do not work. In this case, if I press arrow key under normal
mode, vim gets into insert mode and a character, for example, D, appears above the current line. And also, some shortcuts I set don't work. 
    I hope the information I provide may help.
   Thanks.

**Comment by chrisbra** [comment]
does resetting `:set nocp` help? Please ask user questions von vi.stackexchange.com or the vim-use mailinglist.
