### ISSUE TITLE
1gd/1gD may hangs up forever ...... Bug?

### ISSUE THREAD

**Issue by cs86661** [vim/vim#1643]
```c
int main()
{
  char *a = "NOT NULL";
  if(a)
  {
    char *b = a;
    printf("%s\n", b);
  }
  else
  {
    char *b = "NULL";
    printf("%s\n", b);
  }

  return 0;
}
```
When I input "1gd" or "1gD" on "b" variable inside the else block, gVim will hanging up until input Ctrl+C ... :(

**Comment by chrisbra** [comment]
Yeah, it is a bug, Vim keeps searching and finding the same position and does not return.
I think [this commit](https://github.com/chrisbra/vim/commit/b676cc6177942f58c77a04fcc140490c40f19133) fixes it. (Note: The test will not finish, if run on an unpatched vim)

**Comment by vim-ml** [comment]
Hi ChrisBra, cs86661 and list,

2017-4-20(Thr) 1:03:04 UTC+9 Christian Brabandt:
> Yeah, it is a bug, Vim keeps searching and finding the same position and does not return.
> 
> I think this commit fixes it. (Note: The test will not finish, if run on an unpatched vim)

I think below patch is better.
When `t` is not FAIL, add len to curwin->w_cursor.col simply.

diff --git a/src/normal.c b/src/normal.c
index 53bda6c..754aa5d 100644
--- a/src/normal.c
+++ b/src/normal.c
@@ -4371,7 +4371,10 @@ find_decl(
 	    if ((pos = findmatchlimit(NULL, '}', FM_FORWARD,
 		     (int)(old_pos.lnum - curwin->w_cursor.lnum + 1))) != NULL
 		    && pos->lnum < old_pos.lnum)
+	    {
+		curwin->w_cursor.col += len;
 		continue;
+	    }
 	}
 
 	if (t == FAIL)

--
Best regards,
Hirohito Higashi (h_east)

**Comment by cs86661** [comment]
It works! thanks everyone. :)

**Comment by vim-ml** [comment]
Hirohito Higashi wrote:

> Hi ChrisBra, cs86661 and list,
> 
> 2017-4-20(Thr) 1:03:04 UTC+9 Christian Brabandt:
> > Yeah, it is a bug, Vim keeps searching and finding the same position and does not return.
> > 
> > I think this commit fixes it. (Note: The test will not finish, if run on an unpatched vim)
> 
> I think below patch is better.
> When `t` is not FAIL, add len to curwin->w_cursor.col simply.
> 
> diff --git a/src/normal.c b/src/normal.c
> index 53bda6c..754aa5d 100644
> --- a/src/normal.c
> +++ b/src/normal.c
> @@ -4371,7 +4371,10 @@ find_decl(
>  	    if ((pos = findmatchlimit(NULL, '}', FM_FORWARD,
>  		     (int)(old_pos.lnum - curwin->w_cursor.lnum + 1))) != NULL
>  		    && pos->lnum < old_pos.lnum)
> +	    {
> +		curwin->w_cursor.col += len;
>  		continue;
> +	    }
>  	}
>  
>  	if (t == FAIL)

The value of "len" is the length of the pattern.  It may move the cursor
beyond the end of the line.

Hmm, there can't really be a valid match before the end of the block.
Thus we might as well move the cursor to "pos".

-- 
There are 2 kinds of people in my world: those who know Unix, Perl, Vim, GNU,
Linux, etc, and those who know COBOL.  It gets very difficult for me at
parties, not knowing which group to socialise with :-)
						Sitaram Chamarty

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
