### ISSUE TITLE
In <silent> mapping, the cursor is not hidden

### ISSUE THREAD

**Issue by AlexMasterov** [vim/vim#1644]
@Shougo [found some bug](https://github.com/Shougo/denite.nvim/issues/249#issuecomment-294648432) in GVim.

In `<silent>` mapping, the cursor is not hidden.
```vim
function! Test() abort
  while 1
    redraw
    echo getchar(0)
    sleep 10m
  endwhile
endfunction

nnoremap <silent> ss  :<C-u>call Test()<CR>
nnoremap sg  :<C-u>call Test()<CR>
```

If you press `ss`, the cursor not hidden.
But you press `sg`, the cursor is hidden.

It is reproduced on Windows 10 and Linux in GVim.

The problem may be related to #1637.

**Comment by chrisbra** [comment]
`<silent>` in mappings is about echoing the mapping in the command line. Since the cursor does not move to the command line, it remains where it belongs. So this is expected behaviour.
I don't see, how this should be related to #1637
