### ISSUE TITLE
Characters deleted on completion after enter

### ISSUE THREAD

**Issue by vimeitor** [vim/vim#1645]
This was reported by @tjharman on the vim-mucomplete repo, and I'm basically pasting @lifepillar's message on how to reproduce the issue:

Run `vim -Nn --noplugin -u NONE` and execute `:set completeopt+=menuone,noinsert,noselect`. Then type:
```
Port
Po<c-x><c-p>rt<cr>
```
and you will remain with `Po` instead of `Port`.

**Comment by chrisbra** [comment]
The example can be simplified to `vim -u NONE -N -c 'call setline(1, ["Post", "Port", "Po"])'` and then press `<C-X><C-P>` in the last line after entering insert mode. Note, this does not happen if one uses `<C-X><C-N>`.

I traced this a bit in edit.c. This seems to be caused by ` ins_compl_set_original_text()` returning early, because `compl_first_match->cp_flags` is not set to `ORIGINAL_TEXT`. Looking further, I can see, that compl_first_match will be always set to the current match in `ins_compl_add()`, so the original compl_first_match will be further down in the list of completion matches.

The problem seems to come from those lines in `ins_compl_add()`:
```c
      /*
       * Link the new match structure in the list of matches.
       */
      if (compl_first_match == NULL)
          match->cp_next = match->cp_prev = NULL;
      else if (dir == FORWARD)
      {
          match->cp_next = compl_curr_match->cp_next;
          match->cp_prev = compl_curr_match;
      }
      else        /* BACKWARD */
      {
          match->cp_next = compl_curr_match;
          match->cp_prev = compl_curr_match->cp_prev;
      }
      if (match->cp_next)
          match->cp_next->cp_prev = match;
      if (match->cp_prev)
          match->cp_prev->cp_next = match;
      else        /* if there's nothing before, it is the first match */
          compl_first_match = match;
      compl_curr_match = match;
```

If `(dir == BACKWARDS)` then `match->cp_prev` will be set to `compl_curr_match->cp_prev` and then the test further down in line 2645 `if (match->cp_prev)` will return false, because `compl_curr_match->cp_prev` is NULL, which will then effectively set compl_first_match to the current match which seems wrong.

I am trying to think, how to change the condition to correctly set compl_first_match, but i am not sure. Hopefully this analysis help fixing it.

**Comment by lifepillar** [comment]
>The example can be simplified

Note the `completeopt` must still contain `noselect`.

**Comment by chrisbra** [comment]
No, it does not.

**Comment by lifepillar** [comment]
Using your example (or mine) without adding `noselect` to `completeopt`, I cannot reproduce the bug (Vim 8.0.567).

**Comment by chrisbra** [comment]
well, you have to press C-P several times, until no match is selected (forgot to mention that).

**Comment by lifepillar** [comment]
I see. I stand corrected.

**Comment by lifepillar** [comment]
If I may cast my vote, would it be possible to push this further before 8.1 or soon after?

**Comment by chrisbra** [comment]
That analysis of mine is not quite correct.  I am not quite sure, why sometimes the last item in the completion popup list has the ORIGINAL_TEXT flag set and sometimes the first item (even when completing backwards both times). But I am too tired now to further dig through the code, so here is a patch that fixes the issue and adds a test:

```patch
diff --git a/src/edit.c b/src/edit.c
index 21941cb3d..c19eccbad 100644
--- a/src/edit.c
+++ b/src/edit.c
@@ -3657,6 +3657,8 @@ ins_compl_set_original_text(char_u *str)
     char_u     *p;

     /* Replace the original text entry. */
+    /* The ORIGINAL_TEXT flag is either at the first item or might possibly be
+     * at the last item for backward completion */
     if (compl_first_match->cp_flags & ORIGINAL_TEXT)   /* safety check */
     {
        p = vim_strsave(str);
@@ -3666,6 +3668,17 @@ ins_compl_set_original_text(char_u *str)
            compl_first_match->cp_str = p;
        }
     }
+    else if (compl_direction == BACKWARD &&
+           compl_first_match->cp_prev != NULL &&
+           compl_first_match->cp_prev->cp_flags & ORIGINAL_TEXT)
+    {
+       p = vim_strsave(str);
+       if (p != NULL)
+       {
+           vim_free(compl_first_match->cp_prev->cp_str);
+           compl_first_match->cp_prev->cp_str = p;
+       }
+    }
 }

 /*
diff --git a/src/testdir/test_popup.vim b/src/testdir/test_popup.vim
index 8294febe6..c41d9666b 100644
--- a/src/testdir/test_popup.vim
+++ b/src/testdir/test_popup.vim
@@ -814,5 +814,15 @@ func Test_popup_command()
   call delete('Xtest')
 endfunc

+func Test_popup_complete_backwards()
+  new
+  call setline(1, ['Post', 'Port', 'Po'])
+  let expected=['Post', 'Port', 'Port']
+  call cursor(3,2)
+  call feedkeys("A\<C-X>". repeat("\<C-P>", 3). "rt\<cr>", 'tx')
+  call assert_equal(expected, getline(1,'$'))
+  bwipe!
+endfunc
+

 " vim: shiftwidth=2 sts=2 expandtab
```

**Comment by lifepillar** [comment]
Thanks for coming back on this!

I have tried your patch against the current master: it appears to fix the issue for `<c-x><c-p>`, but not for `<c-p>` completion. This test still fails:

```vim
func Test_popup_complete_backwards_ctrl_p()
  new
  call setline(1, ['Post', 'Port', 'Po'])
  let expected=['Post', 'Port', 'Port']
  call cursor(3,2)
  call feedkeys("A\<C-P>\<C-N>rt\<cr>", 'tx')
  call assert_equal(expected, getline(1,'$'))
  bwipe!
endfunc
```

**Comment by chrisbra** [comment]
Hm, perhaps the condition was too strict. Try removing the first condition: `compl_direction == BACKWARD &&`

**Comment by lifepillar** [comment]
I can confirm that after removing that condition the issues is fixed. Thanks!

**Comment by chrisbra** [comment]
Grmml, you was trying to submit a new patch, including the test from lifepillar https://github.com/vim/vim/issues/1645#issuecomment-381868363

So can you please in addition add that test as well? Thanks.
