### ISSUE TITLE
Cgn bug

### ISSUE THREAD

**Issue by xahon** [vim/vim#1646]
I describe my [problem](https://github.com/Valloric/YouCompleteMe/issues/2622) here. Doesn't `cgn` repeat control keys like arrows, switching modes, etc..?

**Comment by chrisbra** [comment]
sorry, did not follow. Please describe the problem clearly and reproducible.

**Comment by xahon** [comment]
First of all you need to install `YouCompleteMe` plugin that allows vim to have autocomplete like in IDEs. Then declare a variable and repeat it some times. `YCM` must be right configured to be able to autocomplete this variable. Then try to refactor variable (For example try to change second letter or first, nevermind), press `cgn` and use autocompletion of this variable, after `ycm` insert that variable name (That should be changed) switch to normal mode and move cursor with left arrow or `h` and change needed letter. After that press `.` and you will see that `cgn` working not well. Later i'll capture a gif and upload it here to show what i mean

**Comment by chrisbra** [comment]
Sorry, please provide a minimal working example without installing such a heavy plugin like YouCompleteMe

**Comment by chrisbra** [comment]
Ah, I think I understand the problem. Take this text:
```
lastTimeht
lastTimeht
lastTimeht
```
search for `h`, then press cgn move the cursor to the left with the cursor key enter a new character and press `esc`. Then you cannot redo the command using `.` (including the movement of the cursor keys).

This is no bug of `cgn` and that is not how `.` is supposed to work. Pressing cursor keys in insert mode breaks the redo sequence. You might be able to use `<C-G>U<Left>` instead, but I am not sure, this is correct. 

Anyway I am closing this as no issue.
