### ISSUE TITLE
Control F started opening the "Find in files" dialog

### ISSUE THREAD

**Issue by ZenToad** [vim/vim#1654]
I cannot figure out what I did, but Control-F and Control-B have always moved the cursor forward or back.  Somehow Control-F now opens the "Find in Files" dialog and I cannot disable it.  Had to switch back to 7.

Any ideas?

**Comment by chrisbra** [comment]
Are you by any chance loading mswin.vim? It has been recently changed to include a map for Ctrl-F to open the search dialog

**Comment by ZenToad** [comment]
Yes.  I just updated to vim 8 and do load that.  I figured it was something silly but also that I'm not the only one to have this problem.  Thanks for the quick response.

**Comment by chrisbra** [comment]
In that case, simple `:nunmap <c-f>` , `iunmap <c-f>` and `cunmap <c-f>` and possibly also for `<c-h>`

**Comment by ZenToad** [comment]
Yep, updating the mswin.vim fixed it

**Comment by ZenToad** [comment]
Although probably just unmapping them in my .vimrc would be the better option for the next upgrade.
