### ISSUE TITLE
`vim -c "startinsert"` as GIT_EDITOR causes screen corruption on `git commit`

### ISSUE THREAD

**Issue by romellem** [vim/vim#1658]
I am running macOS 10.12.3 with [OhMyZsh](http://ohmyz.sh/) for my terminal (with [Dracula](https://draculatheme.com/) theme), and vim installed via [homebrew](https://brew.sh/).

In my **.zshrc** config file, I have the following set:

    export GIT_EDITOR='vim -c "startinsert"'

However, it looks that from:  

vim version **8.0.0566** to **8.0.0567**  

something changed and now when I run `git commit`, I see a weird `~@ý` bit of text written to the screen after I run `git commit` on any repository.

If I commit a short response, the `~@ý` text is not saved to my git log, so it looks to be only screen corruption.

----

Here is what I'm doing to reproduce:

## Good (8.0.0566)
```
$ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 17 2017 22:34:24)
MacOS X (unix) version
Included patches: 1-566
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     -gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
-clientserver    +insert_expand   +packages        -toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python          +vreplace
+cscope          +lispindent      -python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      -lua             +rightleft       +writebackup
+diff            +menu            +ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      -mouseshape      +startuptime     -xsmp
+eval            +mouse_dec       +statusline      -xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework Cocoa   -mmacosx-version-min=10.12 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.24.1/lib/perl5/5.24.1/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc -F/usr/local/opt/python/Frameworks -framework Python   -lruby.2.4.1 -lobjc    

$ git commit
```

Produces the following expected output:
![gitcommit-good](https://cloud.githubusercontent.com/assets/8504000/25397200/08352a24-29ad-11e7-90f1-2195b082c85c.png)

## Bad (8.0.0567)
```
$ brew switch vim 8.0.0567
Cleaning /usr/local/Cellar/vim/8.0.0566
Cleaning /usr/local/Cellar/vim/8.0.0567
Cleaning /usr/local/Cellar/vim/8.0.0586
18 links created for /usr/local/Cellar/vim/8.0.0567
$ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 19 2017 09:58:36)
MacOS X (unix) version
Included patches: 1-567
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     -gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
-clientserver    +insert_expand   +packages        -toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python          +vreplace
+cscope          +lispindent      -python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      -lua             +rightleft       +writebackup
+diff            +menu            +ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      -mouseshape      +startuptime     -xsmp
+eval            +mouse_dec       +statusline      -xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework Cocoa   -mmacosx-version-min=10.12 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.24.1/lib/perl5/5.24.1/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc -F/usr/local/opt/python/Frameworks -framework Python   -lruby.2.4.1 -lobjc    

$ git commit
```

Produces the following **wrong** output:
![gitcommit-bad](https://cloud.githubusercontent.com/assets/8504000/25397413/d65330cc-29ad-11e7-9a2a-ea99e160f14c.png)

---

If I remove the `-c "startinsert"` argument from my **.zshrc** file and instead just have

    export GIT_EDITOR='vim'

I do not see the screen corruption.

This first started in **8.0.0567** but I currently see it all the way up to **8.0.0586** as well.

**Comment by brammool** [comment]
Romellem wrote:

> I am running macOS 10.12.3 with [OhMyZsh](http://ohmyz.sh/) for my terminal (with [Dracula](https://draculatheme.com/) theme), and vim installed via [homebrew](https://brew.sh/).
> 
> In my **.zshrc** config file, I have the following set:
> 
>     export GIT_EDITOR='vim -c "startinsert"'
> 
> However, it looks that from:  
> 
> vim version **8.0.0566** to **8.0.0567**  
> 
> something changed and now when I run `git commit`, I see a weird `~@ý` bit of text written to the screen after I run `git commit` on any repository.
> 
> If I commit a short response, the `~@ý` text is not saved to my git log, so it looks to be only screen corruption.
> 
> ----
> 
> Here is what I'm doing to reproduce:
> 
> ## Good (8.0.0566)
> ```
> $ vim --version
> VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 17 2017 22:34:24)
> MacOS X (unix) version
> Included patches: 1-566
> Compiled by Homebrew
> Huge version without GUI.  Features included (+) or not (-):
> +acl             +file_in_path    +mouse_sgr       +tag_old_static
> +arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
> +autocmd         +float           +mouse_urxvt     -tcl
> -balloon_eval    +folding         +mouse_xterm     +termguicolors
> -browse          -footer          +multi_byte      +terminfo
> ++builtin_terms  +fork()          +multi_lang      +termresponse
> +byte_offset     -gettext         -mzscheme        +textobjects
> +channel         -hangul_input    +netbeans_intg   +timers
> +cindent         +iconv           +num64           +title
> -clientserver    +insert_expand   +packages        -toolbar
> +clipboard       +job             +path_extra      +user_commands
> +cmdline_compl   +jumplist        +perl            +vertsplit
> +cmdline_hist    +keymap          +persistent_undo +virtualedit
> +cmdline_info    +lambda          +postscript      +visual
> +comments        +langmap         +printer         +visualextra
> +conceal         +libcall         +profile         +viminfo
> +cryptv          +linebreak       +python          +vreplace
> +cscope          +lispindent      -python3         +wildignore
> +cursorbind      +listcmds        +quickfix        +wildmenu
> +cursorshape     +localmap        +reltime         +windows
> +dialog_con      -lua             +rightleft       +writebackup
> +diff            +menu            +ruby            -X11
> +digraphs        +mksession       +scrollbind      -xfontset
> -dnd             +modify_fname    +signs           -xim
> -ebcdic          +mouse           +smartindent     -xpm
> +emacs_tags      -mouseshape      +startuptime     -xsmp
> +eval            +mouse_dec       +statusline      -xterm_clipboard
> +ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
> +extra_search    -mouse_jsbterm   +syntax          
> +farsi           +mouse_netterm   +tag_binary      
>    system vimrc file: "$VIM/vimrc"
>      user vimrc file: "$HOME/.vimrc"
>  2nd user vimrc file: "~/.vim/vimrc"
>       user exrc file: "$HOME/.exrc"
>        defaults file: "$VIMRUNTIME/defaults.vim"
>   fall-back for $VIM: "/usr/local/share/vim"
> Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
> Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework Cocoa   -mmacosx-version-min=10.12 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.24.1/lib/perl5/5.24.1/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc -F/usr/local/opt/python/Frameworks -framework Python   -lruby.2.4.1 -lobjc    
> 
> $ git commit
> ```
> 
> Produces the following expected output:
> ![gitcommit-good](https://cloud.githubusercontent.com/assets/8504000/25397200/08352a24-29ad-11e7-90f1-2195b082c85c.png)
> 
> ## Bad (8.0.0567)
> ```
> $ brew switch vim 8.0.0567
> Cleaning /usr/local/Cellar/vim/8.0.0566
> Cleaning /usr/local/Cellar/vim/8.0.0567
> Cleaning /usr/local/Cellar/vim/8.0.0586
> 18 links created for /usr/local/Cellar/vim/8.0.0567
> $ vim --version
> VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 19 2017 09:58:36)
> MacOS X (unix) version
> Included patches: 1-567
> Compiled by Homebrew
> Huge version without GUI.  Features included (+) or not (-):
> +acl             +file_in_path    +mouse_sgr       +tag_old_static
> +arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
> +autocmd         +float           +mouse_urxvt     -tcl
> -balloon_eval    +folding         +mouse_xterm     +termguicolors
> -browse          -footer          +multi_byte      +terminfo
> ++builtin_terms  +fork()          +multi_lang      +termresponse
> +byte_offset     -gettext         -mzscheme        +textobjects
> +channel         -hangul_input    +netbeans_intg   +timers
> +cindent         +iconv           +num64           +title
> -clientserver    +insert_expand   +packages        -toolbar
> +clipboard       +job             +path_extra      +user_commands
> +cmdline_compl   +jumplist        +perl            +vertsplit
> +cmdline_hist    +keymap          +persistent_undo +virtualedit
> +cmdline_info    +lambda          +postscript      +visual
> +comments        +langmap         +printer         +visualextra
> +conceal         +libcall         +profile         +viminfo
> +cryptv          +linebreak       +python          +vreplace
> +cscope          +lispindent      -python3         +wildignore
> +cursorbind      +listcmds        +quickfix        +wildmenu
> +cursorshape     +localmap        +reltime         +windows
> +dialog_con      -lua             +rightleft       +writebackup
> +diff            +menu            +ruby            -X11
> +digraphs        +mksession       +scrollbind      -xfontset
> -dnd             +modify_fname    +signs           -xim
> -ebcdic          +mouse           +smartindent     -xpm
> +emacs_tags      -mouseshape      +startuptime     -xsmp
> +eval            +mouse_dec       +statusline      -xterm_clipboard
> +ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
> +extra_search    -mouse_jsbterm   +syntax          
> +farsi           +mouse_netterm   +tag_binary      
>    system vimrc file: "$VIM/vimrc"
>      user vimrc file: "$HOME/.vimrc"
>  2nd user vimrc file: "~/.vim/vimrc"
>       user exrc file: "$HOME/.exrc"
>        defaults file: "$VIMRUNTIME/defaults.vim"
>   fall-back for $VIM: "/usr/local/share/vim"
> Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
> Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework Cocoa   -mmacosx-version-min=10.12 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.24.1/lib/perl5/5.24.1/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc -F/usr/local/opt/python/Frameworks -framework Python   -lruby.2.4.1 -lobjc    
> 
> $ git commit
> ```
> 
> Produces the following **wrong** output:
> ![gitcommit-bad](https://cloud.githubusercontent.com/assets/8504000/25397413/d65330cc-29ad-11e7-9a2a-ea99e160f14c.png)
> 
> ---
> 
> If I remove the `-c "startinsert"` argument from my **.zshrc** file and instead just have
> 
>     export GIT_EDITOR='vim'
> 
> I do not see the screen corruption.
> 
> This first started in **8.0.0567** but I currently see it all the way up to **8.0.0586** as well.

In patch 8.0.0567 the request for the color and ambiwidth were fixed.
Before the requests were not send, now they are.

I cannot guess why the "startinsert" command makes any difference.  It
does now happen before requesting the color and ambiwidth.  But the
responses should be handled in Insert mode the same way.

I haven't been able to reproduce the problem.  Does it also happen when
running Vim like that from the shell?  Check your 'term' option in both
cases.

-- 
Q: What do you call a fish without an eye?
A: fsh!
Q: What do you call a deer with no eyes?
A: no eye deer.
Q: What do you call a deer with no eyes and no legs?
A: still no eye deer.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
I cannot reproduce the problem with vim 8.0.586. I tried with various combinations of `GIT_EDITOR="vim -c 'startinsert' -u NONE -N --noplugins"`  `GIT_EDITOR="vim -c 'startinsert'` and  `GIT_EDITOR="vim -c 'startinsert' -u NONE -N"`

**Comment by cs86661** [comment]
```
vi -u NONE --noplugin -c :q
```
The copy/paste function will working abnormally after input above command on Gnome terminal ... (use mouse select any words then paste it.)

**Comment by romellem** [comment]
FYI, I had been using **vim 8.0.0566** for a while because of this bug, but recently had to upgrade for other reasons.

I am now using **vim 8.0.1650_1** along with **git 2.17.0**, and am no longer seeing the original issue.

I can't remember if I ever tested this with plain `vim -c 'startinsert'` commands, or if this issue was only present when triggered via a `git commit`, but somewhere along the way something got fixed that resolved this issue.
