### ISSUE TITLE
:tab drop does not fire BufEnter or TabEnter

### ISSUE THREAD

**Issue by airblade** [vim/vim#1660]
Hello!

I would expect `:tab drop file`, where `file` is any file on the file system, to fire both `TabEnter` and `BufEnter`.  However it doesn't:

```
$ vim -N -u NONE -c 'au BufEnter * echom "BufEnter"' -c 'au TabEnter * echom "TabEnter"'

[inside vim]
:tab drop file
:messages
```

In the messages I would expect to see (assuming `file` has 42 lines and 153 characters):

```
TabEnter
"file" 42L, 153C
BufEnter
```

I actually see:

```
"file" 42L, 153C
```

`:tabedit file` behaves as expected (as above), and `:drop file` behaves as expected (as above without the `TabEnter`).

I'm on Vim 8.0.525.  I also found a report of what appears to be the same bug from 2011: [BUG with autocmd BufEnter and 'tab drop'](https://groups.google.com/forum/#!topic/vim_dev/INkmgxJdaxE/discussion).

**Comment by brammool** [comment]
Andy Stewart wrote:

> I would expect `:tab drop file`, where `file` is any file on the file system, to fire both `TabEnter` and `BufEnter`.  However it doesn't:
> 
> ```
> $ vim -N -u NONE -c 'au BufEnter * echom "BufEnter"' -c 'au TabEnter * echom "TabEnter"'
> 
> [inside vim]
> :tab drop file
> :messages
> ```
> 
> In the messages I would expect to see (assuming `file` has 42 lines and 153 characters):
> 
> ```
> TabEnter
> "file" 42L, 153C
> BufEnter
> ```
> 
> I actually see:
> 
> ```
> "file" 42L, 153C
> ```
> 
> `:tabedit file` behaves as expected (as above), and `:drop file` behaves as expected (as above without the `TabEnter`).
> 
> I'm on Vim 8.0.525.  I also found a report of what appears to be the same bug from 2011: [BUG with autocmd BufEnter and 'tab drop'](https://groups.google.com/forum/#!topic/vim_dev/INkmgxJdaxE/discussion).

I'll add it to the todo list.

-- 
TIM: To the north there lies a cave,  the cave of Caerbannog, wherein, carved
     in mystic runes, upon the very living rock, the last words of Olfin
     Bedwere of Rheged make plain the last resting place of the most Holy
     Grail.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by airblade** [comment]
Thank you.

**Comment by LemonBoy** [comment]
Looks like it is intentional [1] and dates back to vim 7.1 at least

[1] https://github.com/vim/vim/blob/master/src/buffer.c#L5010,L5012

**Comment by insidewhy** [comment]
If it was intentional, is it a good idea? Without these events plugins can't know about files that are opened via `:tab drop`. For anyone who needs a `:tab drop` that produces these events [I wrote a plugin](https://github.com/ohjames/tabdrop).

**Comment by airblade** [comment]
Thank you!
