### ISSUE TITLE
":/" should take a range

### ISSUE THREAD

**Issue by justinmk** [vim/vim#1663]
:/ should work like :substitute, i.e. `:'<,'>/foo` should restrict the search to within the specified range. Currently it treats the end of the range as the starting point.

**Comment by jamessan** [comment]
`:/` isn't a command.  It's an address, and is behaving as expected.  See `:help cmdline-ranges`.

```
	/{pattern}[/]	the next line where {pattern} matches	  *:/*
...
The "/" and "?" may be preceded with another address.  The search starts from
there.  The difference from using ';' is that the cursor isn't moved.
Examples: >
	/pat1//pat2/	Find line containing "pat2" after line containing
			"pat1", without moving the cursor.
	7;/pat2/	Find line containing "pat2", after line 7, leaving
			the cursor in line 7.
```

Since your entire command is just a range, the cursor is moved to the end of the range.

**Comment by justinmk** [comment]
Thanks.
