### ISSUE TITLE
quickfix: might use incorrect buffer through qf_last_bufname after bwipeout

### ISSUE THREAD

**Issue by blueyed** [vim/vim#1676]
I've found an issue where Vim might use a re-cycled buffer for a quickfix entry, that should not be used.

I could not create a more simple test case that worked reliably, but it is caused by using `bwipe` and `new`, where the buffer before the wiping gets the same `%d` representation (through `fprintf(stderr, "buf: %d\n")`).

The following is a Vader test, but should work in general - except for that it might not trigger it.
I have noticed that even adding a new line between `bwipe` and `new` might change it..

Also commenting the `free_buffer` in `close_buffer`, or rather the `vim_free(buf)` at the end works around it.
It seems like without it the `new` buffer will (more likely) get the same address as the previous one, where `qf_last_bufref.br_buf` points at then still?!

```vim
Execute (qf_last_bufname):
  new
  file myfile
"   edit myfile
  let &errorformat = '%f:%m'
  cgetexpr 'myfile:msg1'
  cgetexpr 'myfile:msg1'
  redir => ls
  ls!
  redir END
  Log ls
  echom string(getqflist())
  call assert_equal(getqflist()[0].bufnr, bufnr('myfile'))
  call assert_equal(bufnr('%'), bufnr('myfile'))
  AssertEqual getqflist()[0].bufnr, bufnr('myfile')
  AssertEqual bufnr('%'), bufnr('myfile')

  bwipe
  new
  cgetexpr 'myfile:msg2'
  AssertNotEqual -1, bufnr('myfile')
  call assert_notequal(-1, bufnr('myfile'))
  call assert_equal(getqflist()[0].bufnr, bufnr('myfile'))
  call assert_notequal(bufnr('%'), bufnr('myfile'))
```

A fix, but it might also have to compare `b_ffname`, and in the end `qf_last_bufname`/`qf_last_bufref` should be handled instead when a buffer is wiped?!

```c
diff --git c/src/quickfix.c i/src/quickfix.c
index 7b07f9358..91f5259fd 100644
--- c/src/quickfix.c
+++ i/src/quickfix.c
@@ -1713,7 +1713,9 @@ qf_get_fnum(qf_info_T *qi, char_u *directory, char_u *fname)
        bufname = fname;
 
     if (qf_last_bufname != NULL && STRCMP(bufname, qf_last_bufname) == 0
-           && bufref_valid(&qf_last_bufref))
+           && bufref_valid(&qf_last_bufref)
+           && qf_last_bufref.br_buf->b_sfname
+           && STRCMP(qf_last_bufref.br_buf->b_sfname, bufname) == 0)
     {
        buf = qf_last_bufref.br_buf;
        vim_free(ptr);
```

**Comment by blueyed** [comment]
Initially bisected to commit 8240433f4 (tag: v7.4.2017):

    Date:   Sun Jul 10 17:00:38 2016 +0200

    patch 7.4.2017
    Problem:    When there are many errors adding them to the quickfix list takes
                a long time.
    Solution:   Add BLN_NOOPT.  Don't call buf_valid() in buf_copy_options().
                Remember the last file name used.  When going through the buffer
                list start from the end of the list.  Only call buf_valid() when
                autocommands were executed.

**Comment by blueyed** [comment]
The following smaller test case reproduces it in Neovim at least (where I also initially bisected it to https://github.com/neovim/neovim/commit/951dd1571 (where Vim patch 7.4.2017 was applied)):
```vim
new
file myfile
let &errorformat = '%f:%m'
cgetexpr 'myfile:msg1'
bwipe
sleep 10m
new
cgetexpr 'myfile:msg2'
echoerr bufnr('myfile')
```

It will output `-1`, but needs the sleep to trigger it.

**Comment by vim-ml** [comment]
Hi Daniel,

On Wed, May 3, 2017 at 10:03 AM, Daniel Hahler
<vim-dev-github@256bit.org> wrote:
> I've found an issue where Vim might use a re-cycled buffer for a quickfix
> entry, that should not be used.
>
> I could not create a more simple test case that worked reliably, but it is
> caused by using bwipe and new, where the buffer before the wiping gets the
> same %d representation (through fprintf(stderr, "buf: %d\n")).
>
> The following is a Vader test, but should work in general - except for that
> it might not trigger it.
> I have noticed that even adding a new line between bwipe and new might
> change it..
>
> Also commenting the free_buffer in close_buffer, or rather the vim_free(buf)
> at the end works around it.
> It seems like without it the new buffer will (more likely) get the same
> address as the previous one, where qf_last_bufref.br_buf points at then
> still?!
>
>

I am able to reproduce this problem using the commands you have listed
in your last e-mail.

>
> A fix, but it might also have to compare b_ffname, and in the end
> qf_last_bufname/qf_last_bufref should be handled instead when a buffer is
> wiped?!
>

I am not sure whether this is the right fix. We should wait for comments
from Bram.

- Yegappan


> diff --git c/src/quickfix.c i/src/quickfix.c
> index 7b07f9358..91f5259fd 100644
> --- c/src/quickfix.c
> +++ i/src/quickfix.c
> @@ -1713,7 +1713,9 @@ qf_get_fnum(qf_info_T *qi, char_u *directory, char_u
> *fname)
>         bufname = fname;
>
>      if (qf_last_bufname != NULL && STRCMP(bufname, qf_last_bufname) == 0
> -           && bufref_valid(&qf_last_bufref))
> +           && bufref_valid(&qf_last_bufref)
> +           && qf_last_bufref.br_buf->b_sfname
> +           && STRCMP(qf_last_bufref.br_buf->b_sfname, bufname) == 0)
>      {
>         buf = qf_last_bufref.br_buf;
>         vim_free(ptr);
>

**Comment by brammool** [comment]
Daniel Hahler wrote:

> I've found an issue where Vim might use a re-cycled buffer for a quickfix entry, that should not be used.
> 
> I could not create a more simple test case that worked reliably, but it is caused by using `bwipe` and `new`, where the buffer before the wiping gets the same `%d` representation (through `fprintf(stderr, "buf: %d\n")`).
> 
> The following is a Vader test, but should work in general - except for that it might not trigger it.
> I have noticed that even adding a new line between `bwipe` and `new` might change it..
> 
> Also commenting the `free_buffer` in `close_buffer`, or rather the `vim_free(buf)` at the end works around it.
> It seems like without it the `new` buffer will (more likely) get the same address as the previous one, where `qf_last_bufref.br_buf` points at then still?!
> 
> ```vim
> Execute (qf_last_bufname):
>   new
>   file myfile
> "   edit myfile
>   let &errorformat = '%f:%m'
>   cgetexpr 'myfile:msg1'
>   cgetexpr 'myfile:msg1'
>   redir => ls
>   ls!
>   redir END
>   Log ls
>   echom string(getqflist())
>   call assert_equal(getqflist()[0].bufnr, bufnr('myfile'))
>   call assert_equal(bufnr('%'), bufnr('myfile'))
>   AssertEqual getqflist()[0].bufnr, bufnr('myfile')
>   AssertEqual bufnr('%'), bufnr('myfile')
> 
>   bwipe
>   new
>   cgetexpr 'myfile:msg2'
>   AssertNotEqual -1, bufnr('myfile')
>   call assert_notequal(-1, bufnr('myfile'))
>   call assert_equal(getqflist()[0].bufnr, bufnr('myfile'))
>   call assert_notequal(bufnr('%'), bufnr('myfile'))
> ```
> 
> A fix, but it might also have to compare `b_ffname`, and in the end `qf_last_bufname`/`qf_last_bufref` should be handled instead when a buffer is wiped?!

The bufref_valid() only makes the buf_valid faster, it doesn't have a check
that the buffer was wiped out in between.  Comparing the file name is clumsy.
Better would be to actually clear the bufref, instead of going through the list
of known buffers.  Clearing the bufref creates a new slowness, since we would
need to go through the list of bufrefs.

Perhaps the best solution is to clear qf_last_bufref at the end of a
quickfix command where it was set?  Or at the start of the next one.


-- 
NEIL INNES PLAYED: THE FIRST SELF-DESTRUCTIVE MONK, ROBIN'S LEAST FAVORITE
                   MINSTREL, THE PAGE CRUSHED BY A RABBIT, THE OWNER OF A DUCK
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by blueyed** [comment]
> Perhaps the best solution is to clear qf_last_bufref at the end of a quickfix command where it was set?

Yes, sounds like it.. it's also what I am using as a workaround now: https://github.com/neomake/neomake/blob/9dc3cfc67679c4e4c1a1a2cfad604abfbfef73b8/tests/include/setup.vader#L26-L32
