### ISSUE TITLE
Unexpected behavior of gn with nowrapscan

### ISSUE THREAD

**Issue by tckmn** [vim/vim#1683]
Steps to reproduce:

1. Set the `nowrapscan` option.
2. Insert the text `foo bar baz` and move the cursor to the beginning of the line.
3. `/bar/e`
4. `gn`

The expected behavior is that `bar` is selected, which happens if `wrapscan` is set. However, the observed behavior is that only the `b` in `bar` is selected.

The bug only occurs on the last instance of the pattern in the file. It happens if the cursor is anywhere within the last instance except at the beginning, in which case behavior is as expected.

vim 8.0 with patches 1-586 on Arch Linux.

**Comment by chrisbra** [comment]
thanks for the clear explanation, this [commit](https://github.com/chrisbra/vim/commit/985721db156782c1dd7f7174ef8ecf361ac28c23) fixes it, but it needs to be applied by Bram (commit includes test)

**Comment by KeyboardFire** [comment]
The patch does not implement the expected behavior—it seems to cause the `gn` command to simply fail. As per `:h gn`, the command should select the match if it is currently on the match. (Furthermore, the patch introduces inconsistent behavior in that `gn` with pattern `bar` and text `foo bar| baz bar` with cursor at `|` selects the first `bar`, but without the last word it fails under the patch.)

**Comment by tckmn** [comment]
@chrisbra The patch does not implement the expected behavior—it seems to cause the `gn` command to simply fail. As per `:h gn`, the command should select the match if it is currently on the match. (Furthermore, the patch introduces inconsistent behavior in that `gn` with pattern `bar` and text `foo bar| baz bar` with cursor at `|` selects the first `bar`, but without the last word it fails under the patch.)

**Comment by chrisbra** [comment]
It fails, because nowrapscan is set. I would say this is expected behaviour.

**Comment by chrisbra** [comment]
Sorry, I misunderstood. I think you are right. Please check [this patch](https://github.com/chrisbra/vim/commit/81aa25cad0c9f4157162eb10fc48f211a82e7674)

**Comment by tckmn** [comment]
The new patch does result in the expected behavior, thanks!
