### ISSUE TITLE
Quoted text not selected

### ISSUE THREAD

**Issue by guraga** [vim/vim#1687]
vim 8.0 with patches 1-596.

Steps to reproduce.

1. Run commands:

```bash

echo 'a "bcde" f' |
vim \
   -u NONE \
   -U NONE \
   -i NONE \
   -n \
   -N \
   --noplugin \
   -c 'set selection=exclusive' \
   -
```

2. Press "fd" to place cursor to character "d".

3. Press "vh" to select character "c".

4. Press "i" and double quote to select quoted text.

Expected result: select text "bcde".
Actual result: selected text is "bcd" (last quoted character ("e") not selected).

**Comment by chrisbra** [comment]
thanks. I think [this commit](https://github.com/chrisbra/vim/commit/3d0be0843d4a9965a75fd4f3d7a2dcba5122f364) fixes it. It contains a test but needs to be applied by Bram.

**Comment by chrisbra** [comment]
(amended commit, correct commit link is https://github.com/chrisbra/vim/commit/3d0be0843d4a9965a75fd4f3d7a2dcba5122f364)

**Comment by guraga** [comment]
Thank you. This worked, but cursor placed at the end of quoted text.
Expectation: place cursor at first quoted character (at character "b").

Compare:

Commit | &selection | Cursor at character
-|-|-
Before commit | inclusive | "b"
Before commit | exclusive | "b"
After commit | inclusive | "e"
After commit | exclusive | Closed double quote

**Comment by vim-ml** [comment]
On Mo, 08 Mai 2017, guraga wrote:

> Thank you. This worked, but cursor placed at the end of quoted text.
> Expectation: place cursor at first quoted character (at character "b").
> 
> Compare:
> 
> Commit | &selection | Cursor at character
> -|-|-
> Before commit | inclusive | "b"
> Before commit | exclusive | "b"
> After commit | inclusive | "e"
> After commit | exclusive | Closed double quote

I thought it is more reasonable to have the cursor always at the 
position further down the selection. I can change that however.

Best,
Christian
-- 
Komisches nehmen die Menschen nicht ernst. Als wäre ein Toter, mit
einer Lachgaspistole totgeschlagen, nicht tot.
		-- Stanislaw Jerzy Lec (eig. S. J. de Tusch-Letz)

**Comment by guraga** [comment]
Cursor position chosen at step 3:
* to place cursor at the end of quoted text press "vl";
* to place cursor at the begin of quoted text press "vh".

Compare:

Commit | &selection | Step 3 | Cursor at character
-|-|-|-
Before commit | inclusive | "vh" | "b"
Before commit | inclusive | "vl" | "e"
Before commit | exclusive | "vh" | "b"
Before commit | exclusive | "vl" | Closed double quote
After commit | inclusive | "vh" | "e" (expected "b")
After commit | inclusive | "vl" | "e"
After commit | exclusive | "vh" | Closed double quote (expected "b")
After commit | exclusive | "vl" | Closed double quote

Expecting the same behavior before and after commit.
