### ISSUE TITLE
TextChangedI when pumvisible

### ISSUE THREAD

**Issue by prabirshrestha** [vim/vim#1691]
Currently `TextChangedI` isn't triggered when the popup menu is visible. This means all autocomplete plugins have to use timer based hacks.
Would it be possible to have a new event something like `TextChangedIEx` which is triggered regardless of popup menu being visible or not? This way I could use timer as fallback instead in [asyncomplete.vim](https://github.com/prabirshrestha/asyncomplete.vim). All other async completion plugins - [completor.vim](https://github.com/maralla/completor.vim), [deoplete](https://github.com/Shougo/deoplete.nvim), [ncm](https://github.com/roxma/nvim-completion-manager) also seems to use timer based hacks.
I'm also writing a [language server plugin for vim](https://github.com/prabirshrestha/vim-lsp) and see a use case here to detect text document changes.

https://groups.google.com/forum/#!topic/vim_dev/DrDYKWUeHVY

**Comment by lifepillar** [comment]
>Currently TextChangedI isn't triggered when the popup menu is visible. This means all autocomplete plugins have to use timer based hacks.

In MUcomplete, I use the following pattern:

```vim
autocmd InsertCharPre * let s:insertcharpre = 1
autocmd TextChangedI * call s:check_changes()

fun! s:check_changes()
  if s:insertcharpre
    let s:insertcharpre = 0
    " Process pressed char
  end
endf
```

This snippet uses the fact that `InsertCharPre` is triggered even when the pop-up menu is visible. It is not triggered on non-printable characters such as backspace, however; depending on your use case, this may or may not be what you want.

**Edit:** fix typos and add quoted text.

**Comment by prabirshrestha** [comment]
While the `InsertCharPre` is a smaller way to detect char pressed when `pumvisible()`, I would still consider it a hack that is similar to timer based. I do need to support backspace so that I can re-rerun the fuzzy match and sorting again.

**Comment by prabirshrestha** [comment]
I think adding a new event could be fairly simple here. Not familiar with vim build tools and code so if someone wants to pick it up that would be great.

```c
#ifdef FEAT_AUTOCMD
    /* Trigger TextChangedI if b_changedtick differs. */
    if (ready && has_textchangedI()
	    && last_changedtick != CHANGEDTICK(curbuf)
# ifdef FEAT_INS_EXPAND
	    && !pum_visible()
# endif
	    )
    {
	if (last_changedtick_buf == curbuf)
	    apply_autocmds(EVENT_TEXTCHANGEDI, NULL, NULL, FALSE, curbuf);
	last_changedtick_buf = curbuf;
	last_changedtick = CHANGEDTICK(curbuf);
    }
#endif
```

**Comment by LemonBoy** [comment]
When #2333 is merged the new global variable named `v:global` may be used to provide more information without adding a whole new autocmd.

**Comment by prabirshrestha** [comment]
@LemonBoy Based on the PR seems like I would still need to create a new event. If I don't and reuse the `TextChangedI` event with `v:event` containing the details it could break existing plugins.
