### ISSUE TITLE
system() function doesn't support Unicode user name

### ISSUE THREAD

**Issue by gqqnbig** [vim/vim#1698]
I type
`:let a=system('ls')`

and VIM gives me error "Can't open file C:\Users\..."

![default](https://cloud.githubusercontent.com/assets/614159/25983066/c4c45d90-3696-11e7-8d2e-83a615e682f7.jpg)

My user name is in Unicode.

![2](https://cloud.githubusercontent.com/assets/614159/25983104/061bd804-3697-11e7-9282-9fc9475a1500.JPG)

**Comment by k-takata** [comment]
What is your `encoding` setting? (`:set enc?`)
Please also show the version of Vim and Windows.

**Comment by gqqnbig** [comment]
encoding=utf-8

GVIM 8.0.69

Windows 10 version 1703

**Comment by mattn** [comment]
@gqqnbig Could you please try this? https://github.com/vim/vim/pull/3520

**Comment by gqqnbig** [comment]
@mattn I know my feadback is important, but I don't have a system that can compile Vim. If you have a Windows exe, I'm willing to test it.

**Comment by GreenCourt** [comment]
Same issue here.
The output of `system()` is not encoded correctly when `enc=utf-8`.
If I set `enc=cp932`, the problem doesn't happen, but I cannot use unicode texts.

I can't use some plugins that uses `system()` because of this.
Is it hard to fix?

**Comment by k-takata** [comment]
@itouen It's a totally different issue. The encodings of external commands are normally the current codepage, however, it's not always true. Some commands have options to change the output encoding to UTF-8. So, users who use `system()` always need to care about the output encoding by themselves.
E.g.: `let output = iconv(system('foo'), 'char', &enc)`
(`'char'` encoding means the current codepage.)

**Comment by GreenCourt** [comment]
@k-takata Thanks for the reply.
I understand that there are no general-way to solve my problem and I have to send pull-request to each plugin author.
