### ISSUE TITLE
Colon (:) get captured by * in normal mode.

### ISSUE THREAD

**Issue by zanculmarktum** [vim/vim#1699]
I have something like this:
`dummy:`
when I press `*` on it, it search for `\<dummy:\>` instead of `\<dummy\>`.

Please delete if this isn't a bug or if the issue was already submitted.
Thanks in advance.

**Comment by chrisbra** [comment]
I believe the setting `:h 'iskeyword'` is responsible for that. Also, next time, if you are not sure, whether this is a bug, ask on vi.stackexchange.com or use the vim-use ml. thanks.

**Comment by vim-ml** [comment]
Hi, 

2017-5-12(Fri) 15:10:49 UTC+9 zanculmarktum:
> I have something like this:
> 
> dummy:
> 
> when I press * on it, it search for \<dummy:\> instead of \<dummy\>.
> 
> Please delete if this isn't a bug or if the issue was already submitted.
> 
> Thanks in advance.

`*` depends on the setting of option 'iskeyword'.
See document. (`:help *`)

--
Best regards,
Hirohito Higashi (h_east)
