### ISSUE TITLE
cursor dissapeares while moving with showcmd or ruler On, Windows 10 console

### ISSUE THREAD

**Issue by eugensk** [vim/vim#1702]
When I open a text file in console vim on Windows 10, then press and keep down \<Space\> button to make cursor move, cursor is visible for the span of 10-15 characters, then disappears for the next span, then shows again and so on. When stopped, it is shown, but while it hides to see where it is going to stop is not easy.
On another computer (Windows 8) it never happens.
Cursor blink rate in Windows Control Panel does not change anything. 
There was no .vimrc
:set noshowcmd fixes it, but it is supposed to fix slow terminals, not my local console.
[vim-version.txt](https://github.com/vim/vim/files/996126/vim-version.txt)

**Comment by lifepillar** [comment]
Does `:set nolazyredraw` help?

**Comment by eugensk** [comment]
I had nolazyredraw by default, but no, lazyredraw or nolazyredraw - cursor disappears.

**Comment by eugensk00** [comment]
Also I think I should see my last keystroke in echo area, when :set showcmd, but it is never shown. Only current mode and visual selection ( number of lines or block size).

**Comment by eugensk** [comment]
I run vimtutor -console, and run cursor back and forth with \<Space\> and \<Del\> till it start disappearing
and captured calls to

_SetConsoleCursorInfo()_
_SetConsoleCursorPosition()_
_WriteConsoleOutputCharacter()_

with [api monitor v2 alpha](http://www.rohitab.com/apimonitor)

[vim.zip](https://github.com/vim/vim/files/997440/vim.zip)

It shows that cursor hides on each keystroke, but briefly. All remaining time it is shown. So it must be  this particular Windows fault.

**Comment by eugensk00** [comment]
Cannot use `:set ruler` either, cursor disappears.
