### ISSUE TITLE
Update syntax highlighting for HTML & CSS

### ISSUE THREAD

**Issue by jhpratt** [vim/vim#1705]
There are some new features out that just need some more keywords. I haven't dug into the repo at all, although I may do so in around a week.

Just some things I noticed when editing one of my files (version 8.0, I doubt the patch matters)

HTML
--------
`<dialog>`

CSS
--------
`display: grid` and `display: flex` - presumably things like `inline-grid`, `subgrid`, `inline-flex`, etc. are also missing.

Native variables - matching the following regex: `--.*:.*` and `var(--.*)`

To go along with grid and flex, similar selectors:
`align-items`
`justify-content`
`grid-.*` - tons of things here, not listing them all. Obviously not a generic selector.
`dialog::backdrop` pseudoselector (for `dialog` HTML element)

**Comment by chrisbra** [comment]
please contact the maintainer of the responsible syntax files (e.g. look at the header in syntax/css.vim and syntax/html.vim). thanks!

**Comment by JulesWang** [comment]
or @  me in the issue :-)

I will handle these issues

**Comment by enigmata** [comment]
@JulesWang  Mostly I miss the `flex` box CSS properties as called out by @jhpratt . But here are a couple more:

```css
font-variant: small-caps; /* `-caps` not highlighted */
margin: 10%;  /* the `%` suffix is not highlighted anywhere from what I can see */
```

Finally, I notice that sometimes when I page down the entire screen's worth of CSS is not highlighted. I will then page back and then forward again and it will paint properly. I do not recall seeing this in any other language that I use, so feel it may be specific to the CSS syntax rules. 

Thx so much for your help, @JulesWang !

**Comment by JulesWang** [comment]
> Finally, I notice that sometimes when I page down the entire screen's worth of CSS is not highlighted. I will then page back and then forward again and it will paint properly. I do not recall seeing this in any other language that I use, so feel it may be specific to the CSS syntax rules.

Yes, I also noticed this issue, and I failed to fix it , any ideas?

**Comment by enigmata** [comment]
@JulesWang Unfortunately, this is an area about which I know little. I don't mind pitching in and learning to debug such a problem when I get a chance. But others may have ready insight into this problem and can help to resolve it quicker. So, I decided to create a new issue, #1775 , not only to get help from others, but also because it is not directly related to this issue where we're filling in the CSS syntax highlighting gaps.

**Comment by enigmata** [comment]
@JulesWang How is this progressing? Close to a PR?

**Comment by JulesWang** [comment]
#1764  is not merged yet.  @brammool

**Comment by brammool** [comment]
Jules Wang wrote:

> #1764  is not merged yet.  @brammool 

Since HTML is used a lot, I am awaiting comments from users for this
change.  Both positive and negative.  Please try it out.

-- 
hundred-and-one symptoms of being an internet addict:
185. You order fast food over the Internet

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by tonymec** [comment]
About not painting the whole page when syntax constructs go back too far: see ":help :syn-sync". There are 4 possibilities described there. The only foolproof one, but also the slowest, is ":syn sync fromstart" which will backtrack from the start of the file in order to determine how to highlight the text visible in the current window.

AFAICT, it seems that syncing starts 10 lines before top of screen in CSS, 40 lines in help, no less than 10 and no more than 100 in HTML. Depending on how complex your syntax is, it might or might not be enough; if it isn't, then an after-plugin (e.g. ~/.vim/after/syntax/html.vim and ~/.vim/after/syntax/css.vim) could set a higher limit.

Best regards,
Tony.

**Comment by jhpratt** [comment]
@JulesWang Just found another one, this time with JS. Check out template strings. There's zero support for them, which actually causes issues when it comes to "comments".

The specific example that's causing issues for me:

```js
`${config.dir}/*.scss`
```

Currently, it's being parsed as a comment starting with `/*`, but it's actually a template string (via the backticks).

**Comment by JulesWang** [comment]
@jhpratt  pls show me more code with context

Besides, Neither scss files, nor css in js files could be highlighted by css.vim

**Comment by jhpratt** [comment]
Whoops, wasn't thinking of that. I just assumed you were the same one that maintained both of the files.

**Comment by hexadecatrienoic** [comment]
Don't know if this should be a separate issue, I can create one if need be.

Media queries in scss files aren't highlighted, even though they are in css files. In the line `@media (max-width:1023px)`, only `@media` is highlighted, while the entire query is in css.

**Comment by JulesWang** [comment]
@hexadecatrienoic,  this line of css ```@media (max-width:1023px) ``` is highlighted correctly by vim 7.4.8056

**Comment by hexadecatrienoic** [comment]
I'm using vim 8.0.0987-1. Yes, it highlights fine when `syntax=css` is set. With `syntax=scss` set, it comes out like so: ![image](https://user-images.githubusercontent.com/15036323/29723751-ad9f5836-897a-11e7-8b14-83d957f2d175.png), and with `syntax=css`: ![image](https://user-images.githubusercontent.com/15036323/29723932-5c1aeca4-897b-11e7-8ebe-8d8fe59a8ed4.png)

**Comment by JulesWang** [comment]
@hexadecatrienoic, I find a solution to your issue,  but  I'm not a scss/sass expert,  so I need you help me check and test it :-) , the solution is:  comment out line 61, 62, 89 and 90 of syntax/sass.vim
```
syn region sassMediaQuery matchgroup=sassMedia start="@media" end="[{};]\@=\|$" contains=sassMediaOperators
syn keyword sassMediaOperators and not only contained
```
```
hi def link sassMedia                   PreProc
hi def link sassMediaOperators          PreProc
```

media keywords are handled properly in css.vim, so above four lines could be deleted safely IMO.

**Comment by hexadecatrienoic** [comment]
@JulesWang, this works, but it also mangles highlighting in media query blocks. Test code to replicate the issue:
```
$blue: #00f;
@media (max-width: 1023px) {
    header {
        text-align: center;
        position: fixed;
        top: 0;
        height: 7em;
        transition: top 150ms;
    }
    header > h1 {
        color: $blue;
        margin-bottom: 0;
    }
    #nav {
        width: 80%;
        margin: 0 auto;
    }
    #content {
        margin-top: 7em;
    }
}
```
Not commented | Commented
---|---
![image](https://user-images.githubusercontent.com/15036323/29844427-158ff008-8cc4-11e7-9bac-796adcb77bfd.png) | ![image](https://user-images.githubusercontent.com/15036323/29844484-4c60983a-8cc4-11e7-864a-7486ee0035e2.png)

**Comment by JulesWang** [comment]
@hexadecatrienoic  hmm.. code in css.vim and scss.vim are messed up. This problem is not as easy as I think. It will be great if maintainer of scss.vim @tpope is in this thread. Anyway, thanks for your testing.  :-)

**Comment by PurpleVsGreen** [comment]
If it's okay for me to chime in on this issue, it appears vim doesn't recognize the ``@supports`` rule from the [CSS Conditional Rules Module Level 3](https://www.w3.org/TR/css3-conditional/#at-supports) specification. There's also ``@viewport`` from the [CSS Device Adaptation Module Level 1](https://www.w3.org/TR/css-device-adapt/#atviewport-rule) specification (and the vendor-specific ``@-ms-viewport``), however that one doesn't break the highlighting quite as much as ``@supports``. I've looked at css.vim but unfortunately have no idea how to add it in. (Using 8.0 with "Included patches: 1-1427".)

For example:
```
@supports (-webkit-perspective: 20px) and (not (perspective: 20px)) and (not (display: grid)) {
  /* pretty much anything just like a media query */
}
```

TYVM :)

**Comment by JulesWang** [comment]
Pls stop adding new issue here.

@PurpleVsGreen  Thanks for your detailed issue report, it will be perfect if it is a new thread.

I'm already working on it, pls notify me on the new thread :-)

**Comment by JulesWang** [comment]
@hexadecatrienoic  I will work on your issue based on PR #2637 after it is merged.  Pls open a new thread and mention me there.

I'm going to close this issue, but #1764  is not merged yet. @brammool

**Comment by lacygoill** [comment]
> I'm going to close this issue, but #1764 is not merged yet.

Now that #1764 has been merged, is the issue fixed?
