### ISSUE TITLE
Markdown syntax highlighting doesn't work well

### ISSUE THREAD

**Issue by sivaraam** [vim/vim#1706]
The syntax highlighter for markdown files seems to be having some issues. 

- [ ] Italicization is done spuriously

- [ ] Second level nested lists aren't highlighted correctly

**Comment by sivaraam** [comment]
If this involves _regex_ (I guess it does) and if I am pointed to the correct files that specifies the rules, I probably may be of help.

**Comment by chrisbra** [comment]
please discuss with the syntax file maintainer. Look at the header of the file $VIMRUNTIME/syntax/markdown.vim  Oh and check, that no plugin is interfering (check running  vim -u NONE -N)

**Comment by lacygoill** [comment]
The markdown syntax plugin is maintained on github.  Here is the [link of the repository](https://github.com/tpope/vim-markdown).

> Italicization is done spuriously

Without a specific example of what's wrong, it's hard to fix the issue.
On the repository mentioned earlier, there are currently [3 issues](https://github.com/tpope/vim-markdown/search?q=is%3Aissue+is%3Aopen+in%3Atitle+italic&unscoped_q=is%3Aissue+is%3Aopen+in%3Atitle+italic&type=Issues) where the keyword `italic` is mentioned in the title:

- [Inappropriate Italic](https://github.com/tpope/vim-markdown/issues/60)
- [Ending an italic section with an escaped asterisk isn't parsed properly](https://github.com/tpope/vim-markdown/issues/27)
- [Embedded HTML should not italic text between underscores](https://github.com/tpope/vim-markdown/issues/39)

> Second level nested lists aren't highlighted correctly

Again, without a specific example, it's hard to fix the issue.
On the repository mentioned earlier, there are currently [2 issues](https://github.com/tpope/vim-markdown/search?q=is%3Aissue+is%3Aopen+in%3Atitle+nested+list&unscoped_q=is%3Aissue+is%3Aopen+in%3Atitle+nested+list&type=Issues) where the keywords `nested list` are mentioned in the title:

- [Link in Nested List](https://github.com/tpope/vim-markdown/issues/4)
- [Missing conceal for code block in nested list](https://github.com/tpope/vim-markdown/issues/110)

**Comment by sivaraam** [comment]
Ok. Thanks for all the great information! It's been so long now and I don't particularly remember the reason I opened this myself as things have changed. I'll just close this now and open specific issues in the appropriate repo if I see any issues in future. Thanks :)
