### ISSUE TITLE
:set equalalways not respected anymore.

### ISSUE THREAD

**Issue by glacambre** [vim/vim#1707]
As described in https://github.com/neovim/neovim/issues/6748 `:set equalalways` doesn't work anymore. Here's how to reproduce the bug:
```
vim -c "set equalalways | vs | windo sp" -c "sp | wincmd J | close" 
```

**Comment by brammool** [comment]
Glacambre wrote:

Nothing changed in this area.  Please give a reproducible example.

-- 
Did Adam and Eve have navels?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by glacambre** [comment]
Sorry, I added a reproducible example by editing the issue instead of creating a new message, I forgot github didn't mail issue modifications.
Here's how the bug can be reproduced on Vim 8.0.567:
```
vim -c "set equalalways | vs | windo sp" -c "sp | wincmd J | close"
```

**Comment by chrisbra** [comment]
I tried Vim 7.3.0, Vim 7.4.0, Vim 8.0 and Vim 8.0.596 and all behave the same.

**Comment by glacambre** [comment]
@chrisbra This is odd, the issue can be reproduced in vim according to @justinmk in this issue: https://github.com/neovim/neovim/issues/6748

**Comment by chrisbra** [comment]
I am not saying Vim is doing it right, I am just commenting to your 

> doesn't work anymore

And I cannot see, that this behaviour changed recently. It might still be wrong, however. It would help, if you clearly state what you expect and what you see.

**Comment by glacambre** [comment]
Oh, sorry, I misunderstood your message.
When vim has the following window layout:
```
---------
¦ a ¦ b ¦
---------
¦ c ¦ d ¦
---------
¦   e   ¦
---------
```
I'm 90% certain that closing the 'e' window used to result in the following layout:
```
---------
¦ a ¦ b ¦
---------
¦ c ¦ d ¦
---------
```
However, with current vim, closing 'e' results in the following layout:
```
---------
¦ a ¦ b ¦
¦   ¦----
----¦   ¦
¦ c ¦ d ¦
---------
```
I think this behaviour changed within the last 3 months. I think it's a bug because according to the "equalalways" doc closing a window should resize all windows to the same size.

**Comment by brammool** [comment]
Glacambre wrote:

> Oh, sorry, I misunderstood your message.
> When vim has the following window layout:
> ```
> ---------
> ¦ a ¦ b ¦
> ---------
> ¦ c ¦ d ¦
> ---------
> ¦   e   ¦
> ---------
> ```
> I'm 90% certain that closing the 'e' window used to result in the following layout:
> ```
> ---------
> ¦ a ¦ b ¦
> ---------
> ¦ c ¦ d ¦
> ---------
> ```
> However, with current vim, closing 'e' results in the following layout:
> ```
> ---------
> ¦ a ¦ b ¦
> ¦   ¦----
> ----¦   ¦
> ¦ c ¦ d ¦
> ---------
> ```
> I think this behaviour changed within the last 3 months. I think it's a bug because according to the "equalalways" doc closing a window should resize all windows to the same size after closing a window.

I can reproduce it with this example.  Indeed seems wrong.

-- 
An SQL statement walks into a bar.  He approaches two tables
and says, "Mind if I join you?"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
that must have been there for a very long time. From your command, I see the same behaviour with older Vims as well

**Comment by ichizok** [comment]
Right after 'e' is closed;

```
     Frames
-----------------
|   A   |   B   |
| ----- | ----- |
| | a | | | c | |
| ----- | ----- |
| | b | | | d | |
| ----- | ----- |
-----------------

top-frame - A - [a, b]
          \ B - [c, d]
```

* 'A' is a parent frame of 'a' and 'b' frames
* 'B' is a parent frame of 'c' and 'd' frames
* a, b, c, d have each window


sequence:

```
win_close
-> win_equal
   -> win_equal_rec
```

https://github.com/vim/vim/blob/06f1ed2f78c5c03af95054fc3a8665df39dec362/src/window.c#L1956-L1958

When try to adjust 'B' frame (`fr` is 'B'), above condition is false:

* `!current` is false
* `dir` is `'v'`
* `topfr->fr_parent` is `NULL`
* `new_size` is equal to `fr->fr_width`
* `next_curwin` is 'a', so `frame_has_win(...)` is false ('a' is a child of 'A')

so only 'A' and its childs are adjusted, not 'B'.

### proposal of fix

Adjustment all frames always:

```diff
--- a/src/window.c
+++ b/src/window.c
@@ -2459,7 +2459,7 @@ win_close(win_T *win, int free_buf)
        check_cursor();
     }
     if (p_ea && (*p_ead == 'b' || *p_ead == dir))
-       win_equal(curwin, TRUE, dir);
+       win_equal(curwin, FALSE, dir);
     else
        win_comp_pos();
     if (close_curwin)
```

**Comment by vim-ml** [comment]
2017-05-16 9:14 GMT+03:00 Christian Brabandt <vim-dev-github@256bit.org>:
> I tried Vim 7.3.0, Vim 7.4.0, Vim 8.0 and Vim 8.0.569 and all behave the
> same.

I have a working vim-7.0.112 at my disposal and it does behave the same as well.
