### ISSUE TITLE
TOhtml ignores termguicolors

### ISSUE THREAD

**Issue by ingelres** [vim/vim#1708]
Hi,

I removed the terminal color scheme from my .vimrc since termguicolors was introduced, so I only have colors defined for the GUI which are used for the terminal as well.

However, TOhtml ignores termguicolors and uses the default terminal colors when exporting from the terminal instead of the GUI colors. It works fine when exporting from the GUI.

**Comment by LemonBoy** [comment]
I believe it's just a matter of changing [this](https://github.com/vim/vim/blob/master/runtime/syntax/2html.vim#L74) line to
```viml
if &termguicolors || exists('gui_running')
```

**Comment by fritzophrenic** [comment]
Thanks, I've created an issue for it in the project for TOhtml: https://bitbucket.org/fritzophrenic/vim-tohtml/issues/10/should-use-gui-colors-instead-of-old-style

I'm pretty busy this month, but I plan to finally start attacking the list of TOhtml issues this summer.

**Comment by lacygoill** [comment]
Probably fixed by https://github.com/vim/vim/commit/0c0734d527a132edfb4089be48486586424b3f41 since the aforementioned line was added in this commit.

**Comment by k-takata** [comment]
Closing then.
