### ISSUE TITLE
calling complete() flickers if popup menu is already open

### ISSUE THREAD

**Issue by prabirshrestha** [vim/vim#1713]
While working on implementing fuzzy match (https://github.com/prabirshrestha/asyncomplete.vim/pull/16) for [asyncomplete.vim](https://github.com/prabirshrestha/asyncomplete.vim), I noticed that calling `call complete(startcol, candidates)` if popup menu is already open on every keypress causes the autocomplete menu to flicker.

Here is the minimal vimrc. Typing `J`, `a`, `n` and so on causes flickering of the popup menu.
(I'm using timer to mimic `TextChangedI` when popup menu is visible - https://github.com/vim/vim/issues/1691)

```vim
" save this as complete_flicker.vim
" vim -u complete_flicker.vim -c "startinsert"

let s:months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']

let s:last_tick = []

function! s:current_tick()
    return [b:changedtick, getcurpos()]
endfunction

function! s:check_changes(...)
    let l:current_tick = s:current_tick()
    if s:last_tick != l:current_tick
        let s:last_tick = l:current_tick
        call s:on_changed()
    endif
endfunction

function! s:start_check_changes_timer()
    let s:last_tick = []
    let s:check_change_timer = timer_start(30, function('s:check_changes'), {'repeat': -1})
endfunction

function! s:stop_check_changes_timer()
    if exists('s:check_change_timer')
        call timer_stop(s:check_change_timer)
        unlet s:check_change_timer
    endif
endfunction

function! s:on_changed()
    if mode() != 'i'
        return
    endif
    setlocal completeopt-=longest
    setlocal completeopt+=menuone
    setlocal completeopt-=menu
    setlocal completeopt+=noselect
    call complete(1, s:months)
endfunction

autocmd TextChangedI * call s:check_changes()
autocmd InsertEnter * call s:start_check_changes_timer()
autocmd InsertLeave * call s:stop_check_changes_timer()
```

Apparently the autocomplete plugins (completor.vim, deoplete, neovim-completion-manager) seems to get around this problem by using `completefunc` or `omnifuc` to remove flickering.

Would it be possible to fix the bug so that calling `complete()` when a popup menu is visible doesn't hide and reopen the popup menu? This way the behavior would be similar to `completefunc` and `omnifunc`?

//cc @roxma

**Comment by roxma** [comment]
-- deleted unrelated comment --

**Comment by prabirshrestha** [comment]
Any update on this? Would like to know if the behavior of `complete` function could be changed or whether I should use the `omnifunc` and `completefunc` hack.

**Comment by prabirshrestha** [comment]
Looking at the PRs I'm wondering if this has something related to flickering issue PRs.

VIM commit: https://github.com/vim/vim/commit/8aefbe0ad5d05ee7225b20024b0f3023286ebd0f
Neovim PRs: https://github.com/neovim/neovim/pull/4315 https://github.com/neovim/neovim/pull/4036 

I'm not familiar with vim code but the original authors - @Shougo @justinmk might have some idea. Especially given `ins_compl_del_pum()` is followed by `ins_compl_show_pum()`. Wondering whether this is actually causing the flickering issue.

```diff
+    static void
+show_pum(int save_w_wrow)
+{
+  /* RedrawingDisabled may be set when invoked through complete(). */
+  int n = RedrawingDisabled;
+
+  RedrawingDisabled = 0;
+
+  /* If the cursor moved we need to remove the pum first. */
+  setcursor();
+  if (save_w_wrow != curwin->w_wrow)
+      ins_compl_del_pum();
+
+  ins_compl_show_pum();
+  setcursor();
+  RedrawingDisabled = n;
+}
```

**Comment by justinmk** [comment]
@prabirshrestha It would be weird if those PRs caused this issue, but you could try reverting them...

**Comment by Shougo** [comment]
>  Especially given ins_compl_del_pum() is followed by ins_compl_show_pum(). Wondering whether this is actually causing the flickering issue.

This is not my patch related problem.  Because it is already implemented before my patch.
I have just move the code.  I don't know why `ins_compl_del_pum()` is needed.

**Comment by Shougo** [comment]
`set_completion()` calls `ins_compl_add()`.
It calls `ins_compl_del_pum()`.

**Comment by prabirshrestha** [comment]
I'm not familiar with vim source and don't see instructions on how to build vim on windows. Can someone point me to those instructions? Then I would try to revert changes and see if it works.

**Comment by k-takata** [comment]
> Can someone point me to those instructions?

See [src/INSTALLpc.txt](https://github.com/vim/vim/blob/master/src/INSTALLpc.txt).
If you have any questions, please let us know. Maybe we can improve the instructions.

**Comment by prabirshrestha** [comment]
I didn't see that instruction before. Installing Win 7 SDK doesn't seem easy on Win 10. Would it be possible enabling compiling vim by using Visual C++ build tools. It makes it very easy to install MS VC++ compilers and WinSdks without installing Visual Studio. http://landinghub.visualstudio.com/visual-cpp-build-tools.
Compiling Node/Rust/Python native c/c++ libraries and modules is straight forward after installing the VC++ build tools. I was expecting to have similar experience something like `build_msvc.cmd`. Might be should create a new issue?

**Comment by k-takata** [comment]
IIRC, recent versions of Visual Studio (e.g. 2015) will also install Windows SDK 7.1A in `C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A`. So you can specify `SDK_INCLUDE_DIR=C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Include` when you execute `nmake`.
(I don't know whether Visual C++ 2015 Build Tools installs it.)

Actually, Windows SDK 7.x is needed just for `win32.mak`. I think it would be better if we can build vim without it, so that we don't need older WinSDKs.

**Comment by k-takata** [comment]
> Actually, Windows SDK 7.x is needed just for win32.mak. I think it would be better if we can build vim without it, so that we don't need older WinSDKs.

FYI, this is fixed by 8.0.0881. Now we don't need win32.mak anymore.

**Comment by roxma** [comment]
@prabirshrestha 

This probably is not a vim issue.

VIm will auto close the popup when the word doesn't match the completion items' prefix

And I have Just found a simple trick to supress the flicker, timer for tracking changes should be eliminated.

```vim
" save this as complete_flicker.vim
" vim -u complete_flicker.vim -c "startinsert"

set nocompatible
syntax on
filetype plugin indent on
set encoding=utf-8 fileencodings=ucs-bom,utf-8,gbk,gb18030,latin1 termencoding=utf-8

set completeopt=menuone,noselect,noinsert

let s:months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']

func! CompleteStart()

    " keep the old popup menu to supress flickering
    " try comment this line to see the effect
    call complete(1, s:months)

    " now assume the filtering process takes 30ms
    call timer_start(30, {_ -> feedkeys("\<Plug>(Refresh)")})

    return ''
endfunc

func! Refresh()
    call complete(1, s:months)
    return ''
endfunc

inoremap <silent> <Plug>(Complete) <C-r>=CompleteStart()<cr>
inoremap <silent> <Plug>(Refresh) <C-r>=Refresh()<cr>

" for InsertCharPre event, the v:char is not yet available when reading the buffer
" use feedkeys trick here
autocmd InsertCharPre * call feedkeys("\<Plug>(Complete)", "m")
```

**Comment by Shougo** [comment]
It works.  But it does not work if I use timer before `complete()`.
It is very hacky.

So I think `complete_update()` like API is better.

**Comment by mattn** [comment]
I looked this about why prabirshrestha's script causes flickering.

```
diff --git a/src/edit.c b/src/edit.c
index bd840d147..3ba54c177 100644
--- a/src/edit.c
+++ b/src/edit.c
@@ -3109,7 +3109,7 @@ ins_compl_show_pum(void)
 #endif
 
     /* Update the screen before drawing the popup menu over it. */
-    update_screen(0);
+    //update_screen(0);
 
     if (compl_match_array == NULL)
     {
```

### before

![terminal5](https://user-images.githubusercontent.com/10111/51149989-c4b03c80-18a7-11e9-8d7b-b95218755e60.gif)

### after

![terminal6](https://user-images.githubusercontent.com/10111/51149995-cbd74a80-18a7-11e9-81d8-be1016d70917.gif)

Vim seem calling update_screen(0) many times.

**Comment by brammool** [comment]
> I looked this about why prabirshrestha's script causes flickering.
> 
> ```
> diff --git a/src/edit.c b/src/edit.c
> index bd840d147..3ba54c177 100644
> --- a/src/edit.c
> +++ b/src/edit.c
> @@ -3109,7 +3109,7 @@ ins_compl_show_pum(void)
>  #endif
>  
>      /* Update the screen before drawing the popup menu over it. */
> -    update_screen(0);
> +    //update_screen(0);
>  
>      if (compl_match_array == NULL)
>      {
> ```
> 
> ### before
> 
> ![terminal5](https://user-images.githubusercontent.com/10111/51149989-c4b03c80-18a7-11e9-8d7b-b95218755e60.gif)
> 
> ### after
> 
> ![terminal6](https://user-images.githubusercontent.com/10111/51149995-cbd74a80-18a7-11e9-81d8-be1016d70917.gif)
> 
> Vim seem calling update_screen(0) many times.

But then what happens if the popup menu becomes smaller?
Both shorter (fewer entries) and narrower.

When coming from ins_compl_new_leader() there already was a call to
update_screen(), but then the second one should not do anything, since
must_redraw is zero.  Is there some other reason an actual update
happens?

I did a bit of debugging, and can only see the redraw happens after
pum_undisplay(), which is called from the start of
ins_compl_new_leader().  That is intentional.

-- 
hundred-and-one symptoms of being an internet addict:
213. Your kids start referring to you as "that guy in front of the monitor."

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Shougo** [comment]
Another example:

If the completion window size is changed, it will be flicker.
You can test it in the gist.

https://gist.github.com/Shougo/315af3b60882eaa30bffce2fbf42445a

**Comment by Shougo** [comment]
The original issue is fixed in Vim 8.1.0768.
It should be closed.

https://github.com/vim/vim/commit/ae654385dfb2ae4c1d70789d1dce3676dba4dfbc

**Comment by brammool** [comment]
The example using a timer will always flicker, because the popup menu is removed when a character is typed, and it is opened again a bit later when the timer triggers and calls complete().  Vim cannot predict if or when the popup menu will be shown again.
I believe the other cases are covered, thus closing.  If you have a reproducible example of flicker, other that what I just mentioned, please file a new issue.

**Comment by mattn** [comment]
@brammool After patch 8.1.0768, it seems that the cursor moves are delayed while selecting item on popup. I'm checking this on Windows GUI. I can't reproduce this on vim.exe.

![terminal6](https://user-images.githubusercontent.com/10111/51587089-ee5e0900-1f22-11e9-9823-9a1959c49006.gif)

**Comment by prabirshrestha** [comment]
If timer causes flicker would it be possible to have some sort of `next_tick` similar to nodejs `process.nextTick` and JS's `setImmediate` which queues the function in the next event loop. Or we could also treat `0` in timer_start as special case that does the next tick though it could sounds like a hack.

In this case `s:sort_and_rank_candidates` could be expensive so we would like to delay the computation as much as possible.

```
function s:buffer_completor() 
    call s:complete(['a1'])
endfunction

function s:dict_completor()
    call s:complete(['a2'])
endfunction

function s:omni_completor()
    call s:complete(['a3'])
endfunction

let s:candidates = []
function s:complete(items)
    call add(s:candidates, items)
    if exists('s:timer_id')
        call timer_stop(s:timer_id)
    endif
    let s:timer_id = timer_start(0, function('s:show_popup'))
endfunction

function! s:show_popup()
    let l:candidates = s:sort_and_rank_candidates(s:candidates)
    call complete(col('.'), l:candidates)
endfunction

call s:buffer_complete()
call s:dict_complete()
call s:omni_complete()
```

This solves the cases when `s:sort_and_rank_candidates` is sync, but if that is moved to some other thread or job (since computing this is very heavy in vimscript), we still have issues with flickering. So my thought is we still need someway to make sure the popup has the least amount of flicker.
