### ISSUE TITLE
"\<BS>" =~# '[[:backspace:]]' returns 0

### ISSUE THREAD

**Issue by justinmk** [vim/vim#1716]
Steps:

    vim -N -u NONE +"echo \"\\<BS>\" =~# '[[:backspace:]]'"

Tested on 8.0.567.

Same result if one uses `<C-V><BS>` to compare a literal backspace instead of `"\<BS>"`.

**Comment by chrisbra** [comment]
yeah, it looks like `[[:backspace:]]` matches `C-H`

**Comment by brammool** [comment]
The "\<BS>" string uses the key sequence that the terminal sends for Backspace.  If you want a backspace character use "\b".

**Comment by ZyX-I** [comment]
@brammool The `"\<BS>"` string uses internal Vim representation of a backspace (`"\x80kb"`), not what terminal sends.
