### ISSUE TITLE
Can we do something about "How to exit the Vim editor?"

### ISSUE THREAD

**Issue by thanatos** [vim/vim#1719]
See [this SO question](https://stackoverflow.com/questions/11828270/how-to-exit-the-vim-editor) for reference.

The questioner is not asking a very well formed question here, to begin with, which makes things hard. First, he seems to be seeing the prompt (but misquotes it), which strongly implies he's in normal mode, where following the prompt would work. But then we wouldn't be on SO. The remainder of the question implies that he ends up in insert mode somehow, prior to attempting to follow the directions in the prompt. The questioner fails to describe _exactly_ what gets inserted, which could also help.

The best guess I have comes from a co-worker: the questioner misinterprets the `:` as being not part of the directions, i.e., the prompt is interpreted as "Type: `quit<Enter>` to exit Vim".

Would perhaps coloring the keystrokes to offset them from the prompt help?

I know [where the prompt is in the source](https://github.com/vim/vim/blob/545cb79da586be3333a0a55616046f94b01f6b1a/src/normal.c#L8989), but I don't know how to do color at that point. Also, note that the message is internationalized, so that makes it a bit trickier. It seems that the typesetting is not very consistent either — some locales use less space, some use more, some use different amounts on either side of the prompt, ES and EO even use quotes, the word "Enter" is sometimes i18n'd, but mostly not…

**Comment by colinmcintosh** [comment]
Could we consider replacing the text with `Type  <Escape>:quit<Enter>  to exit Vim` ? I think it would make it more clear that the user needs to exit insert mode and resolves the issue of the `:` character being misinterpreted as part of the `Type` prompt.

**Comment by alburthoffman** [comment]
I agree with` Type <Escape>:quit<Enter> to exit Vim`

especially for newbies, it wont make them misunderstand.

**Comment by vim-ml** [comment]
On Tue, May 23, 2017 at 8:31 PM, Roy Wellington Ⅳ
<vim-dev-github@256bit.org> wrote:
> See this SO question for reference.
>
> The questioner is not asking a very well formed question here, to begin
> with, which makes things hard. First, he seems to be seeing the prompt (but
> misquotes it), which strongly implies he's in normal mode, where following
> the prompt would work. But then we wouldn't be on SO. The remainder of the
> question implies that he ends up in insert mode somehow, prior to attempting
> to follow the directions in the prompt. The questioner fails to describe
> exactly what gets inserted, which could also help.
>
> The best guess comes from a co-worker: the questioner misinterprets the : as
> being not part of the directions, i.e., the prompt is interpreted as "Type:
> quit<Enter> to exit Vim".
>
> Would perhaps coloring the keystrokes to offset them from the prompt help?
>
> I know where the prompt is in the source, but I don't know how to do color
> at that point. Also, note that the message is internationalized, so that
> makes it a bit trickier. It seems that the typesetting is not very
> consistent either — some locales use less space, some use more, some use
> different amounts on either side of the prompt, ES and EO even use quotes,
> the word "Enter" is sometimes i18n'd, but mostly not…

The attached screenshot is what I see, with two spaces left of the
colon and none right of it. It never came to my mind that to leave Vim
I was to type anything other than a colon followed by the letter q
then the Enter key.

Best regards,
Tony.

**Comment by brammool** [comment]
> I agree with` Type <Escape>:quit<Enter> to exit Vim`
> 
> especially for newbies, it wont make them misunderstand.

The message only shows when pressing CTRL-C in Normal mode.
In Insert mode CTRL-C goes to Normal mode.  Thus typing CTRL-C twice
also works to get the message.

-- 
ARTHUR: Old woman!
DENNIS: Man!
ARTHUR: Man.  I'm sorry.  Old man, What knight live in that castle over there?
DENNIS: I'm thirty-seven.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by thanatos** [comment]
(Hopefully I can reply to you Tony from GitHub…)

> The attached screenshot is what I see

My impression was that the SO post was discussing the message that appears if you hit ^C (SIGINT) while in normal mode. (Or, if you hit it twice while in insert mode; the first taking you back to normal mode.) I had forgotten about the one on the introduction screen; the SO post's wording is closer to the ^C one, however.

**Comment by chrisbra** [comment]
fixed as of (8.0.0609)[https://github.com/vim/vim/releases/tag/v8.0.0609]
