### ISSUE TITLE
PayPal link in documentation doesn't work

### ISSUE THREAD

**Issue by h3xx** [vim/vim#1724]
I have a PayPal account, and even though I've signed in, visiting the link specified in the documentation (`:h send-money`) just takes me to my account overview.

The link specified is this: https://www.paypal.com/en_US/mrb/pal=XAC62PML3GF8Q

**Comment by brammool** [comment]
Dan Church wrote:

> I have a PayPal account, and even though I've signed in, visiting the link specified in the documentation (`:h send-money`) just takes me to my account overview.
> 
> The link specified is this: https://www.paypal.com/en_US/mrb/pal=XAC62PML3GF8Q

That link is for getting information about PayPal.
The email address mentioned below it is for making payments.

-- 
ARTHUR: I've said I'm sorry about the old woman, but from the behind you
        looked ...
DENNIS: What I object to is that you automatically treat me like an inferior...
ARTHUR: Well ... I AM king.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by h3xx** [comment]
> That link is for getting information about PayPal.

Why isn't the link to https://www.paypal.com, or to https://en.wikipedia.org/wiki/PayPal
