### ISSUE TITLE
There may be memory leak in python-buffer.

### ISSUE THREAD

**Issue by Yggdroot** [vim/vim#1726]
```python
function! Test()
python << EOF

import vim
import time
b = vim.current.buffer
aaa = ["aaaaaa"*1000]*50000
start = time.time()
b[:] = aaa
print(time.time() - start)

EOF
endfunction
```
In an empty buffer, execute this function for several times, it takes longer and longer.
At last, it run out of memory.

**Comment by brammool** [comment]
> ```python
> function! Test()
> python << EOF
> 
> import vim
> import time
> b = vim.current.buffer
> aaa = ["aaaaaa"*1000]*50000
> start = time.time()
> b[:] = aaa
> print(time.time() - start)
> 
> EOF
> endfunction
> ```
> In an empty buffer, execute this function for several times, it takes longer and longer.
> At last, it run out of memory.

Why do you think it is a leak?  Perhaps it's just using lots of memory.
E.g. try makig "aaa" empty.
Also try disabling undo.

-- 
ARTHUR:    Be quiet!  I order you to shut up.
OLD WOMAN: Order, eh -- who does he think he is?
ARTHUR:    I am your king!
OLD WOMAN: Well, I didn't vote for you.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Yggdroot** [comment]
Thank you. 
After `setlocal undolevels=-1`, the result gets back to normal as expected.

**Comment by Yggdroot** [comment]
There is another issue.
```python
python << EOF

import vim
import time
with open("aaa.txt", 'r+') as f:
    aaa = f.readlines()

vim.command("vsp test.txt | setlocal ul=-1")
b = vim.current.buffer
vim.command("hide")

EOF

function! Test()

python << EOF

del b[:] # there is an issue here

vim.command("vsp test.txt")

start = time.time()
b[:] = aaa
print(time.time() - start)

EOF
endfunction

map <F5> :call Test()<CR>
```
aaa.txt can be found [here](https://github.com/Yggdroot/sample/blob/master/aaa.txt), source the code, then run test by press `<F5>` for several times, close the test.txt buffer every time before press `<F5>`, you will find it takes longer and longer time to set the buffer with `b[:] = aaa`, I want to know why this happened.
If `del b[:]` is removed, everything works well. I think there is a bug here.
