### ISSUE TITLE
make_mvc.mak AVX/AVX2 support

### ISSUE THREAD

**Issue by Taverius** [vim/vim#1731]
Since SSE2 is supported as a compilation flag, I figure we might as well add in AVX/AVX2.

I've had it on my own tree for a while, I figure I could clean it up and send a pull.

Couple of questions:

* should I keep the "intel name" style for the `CPUNR` options? Ie, calling them `sandybridge` and `haswell`, or should I just name them `AVX` & `AVX2`.
* `/arch:AVX2` is supported from VC 2013 Update 2 onwards. To detect it that finely requires a few extra lines as I need to check `_MSC_FULL_VER`, which is not currently used. Currently it only checks `_MSC_VER` which is `1800` for all 2013 versions. Is that an issue? Elsewise I can make it a 2015 and up option.

Thoughts?

**Comment by Taverius** [comment]
I also noticed that we're not currently building correctly for non-SSE2 on recent MSVC.

`/arch:SSE2` is the default on recent compilaers, and we don't set it to `/arch:IA32` for `i686` and under targets.

I'll fix that, along with adding support for `/arch:SSE` which is missing.

This however brings up another question.

Can we even still run on Windows 2000/NT4?

The minimum WINVER in the makefile is 0x0501, which is Windows XP. If that's the oldest Windows OS Vim8 will run on, we can pull all the code to support processors below a pentium (i586).

Even if NT4 is supported, there's no reason to support building for i386 as NT4 is 486 and up.

**Comment by vim-ml** [comment]
On Sunday, 28 May 2017 23:59:03 UTC+2, Leonardo Valeri Manera  wrote:
> Since SSE2 is supported as a compilation flag, I figure we might as well add in AVX/AVX2.
> 
> I've had it on my own tree for a while, I figure I could clean it up and send a pull.
> 
> Couple of questions:
> 
> should I keep the "intel name" style for the CPUNR options? Ie, calling them sandybridge and haswell, or should I just name them AVX & AVX2.
> /arch:AVX2 is supported from VC 2013 Update 2 onwards. To detect it that finely requires a few extra lines as I need to check _MSC_FULL_VER, which is not currently used. Currently it only checks _MSC_VER which is 1800 for all 2013 versions. Is that an issue? Elsewise I can make it a 2015 and up option.
> 
> 
> Thoughts?
> 
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub

Taking a deeper look, I have many questions, and found some issues.

Also, I'm not understanding how integration with github issues works, given how my comment on the issue did not get duplicated here. Please excuse.

Questions:


* i386 is not actually a valid target, because NT4 requires a 486 at minimum. Is it worth supporting someone who wants to build for NT4 but also for a processor that can't actually run NT4?

* Will Vim8 even compile for NT4? Does anyone have a VC++ install old enough to test, and an NT4 VM to test the build in? The Makefile is ambiguous, but suggests XP (i586 and up) is the minimum. Recent Windows SDKs have a Windows XP floor.

* What would the preferred behaviour be when specifying AVX/AVX2 architecture on a compiler that doesn't support it? The current behaviour is to go to defaults, maybe it would be better to fall back to the arch below? Ie, if you ask for AVX2 but you're building on VC10 you get AVX. Or should we spit an error and stop?


Bugs:


* The makefile says it defaults to i386, but it doesn't. It defaults to no architecture optimization for VC<8, and leaves the defaults to the compiler for VC>8. This varies depending on the compiler. For VS 2015 and up at least, that means SSE2 was the default. This means that with recent compilers you cannot, currently, build for SSE or IA32/x87fp processors.

* There is actually no support for SSE (Pentium3) architecture at all, on any VC version.

**Comment by k-takata** [comment]
Vim 8.0.0029 dropped support for Windows older than Win XP. We don't need to care about Win 2k/NT.

**Comment by chrisbra** [comment]
> Also, I'm not understanding how integration with github issues works, given how my comment on the issue did not get duplicated here. Please excuse.

I noticed that too. It looks like we missed some notifications since yesterday or monday.
I think, we accidentally removed the mirror-script from sending to the vim-dev list. Not sure. I'll have to check whether this still works correctly

**Comment by Taverius** [comment]
That makes things simpler, I would remove i386 and i486 as targets, unless there's a good reason to keep it - it just adds meaningless complexity.

My main question then is how to handle failure modes, where one specifies an architecture not supported by the compiler, with these options I guess:

1. Ignore it, setting the argument desired and having the compilation fail.
2. Print a message and error out.
3. Print a message and fall back to the closest applicable, AVX2->AVX, down to ->SSE2 for x86.
4. Print a message and fall back to defaults, going by the original intention of the Makefile, i586/nothing for x86/x64.
5. Print a message and fall back to defaults, with the current behaviour, often SSE2/nothing for x86/x64 but depending on the compiler.

Currently the behaviour is to silently use undefined compiler defaults, which is the worst of all.

**Comment by vim-ml** [comment]
Here is a patch for testing, with the following changes:


* AXV targeting is supported, with CPUNR=avx
* AVX2 targeting is supported, with CPUNR=avx2
* SSE targeting is supported, with CPUNR=sse
* SSE2 targeting now uses CPUNR=sse2.
* CPUNR=pentium4 is supported (with a warning), so as not to break existing scripts. Internally is is aliased to sse2.

Rationale here, AMD exists, and it doesn't make sense to call instruction set targeting after a nebulous intel marketing name, or revision. Not all "Sandy Bridge" CPUs support AVX, for example, and there are probably more SSE2 Athlons/Opterons around than there are Pentium 4s.

In view of that, it makes more sense to name the options after the instruction set, where possible.

As for 'pentium4' printing a deprecation warning, I figure if we start now, by 2042 when Vim 9 comes out and we all want to compile it for our autopiloted flying cars so we can code on the way to work, we'll be able to remove it.


* untargeted is now specifically available via CPUNR=any, as well as being the (intended) default as before.

Previously, the behaviour depended on the compiler defaults, which gave untargeted code for VC10 and earlier, and SSE2 code for VC12 and later, where the /arch:IA32 option appears for generating fp87 code.

Also, the makefile *said* i386 was the default, but actually untargeted was.

This can be changed to i586 being the default for VC < 8, though the actual effect of the current Makefile seems better.


* i586, i686, properly generates fp87 code for VC11 and up.

Currently, it generates SSE2 code, as that is the default.


* Support for targeting the i386 and i486 architectures is removed.

Patch 8.0.0029 drops support for Windows NT4 and Windows 2000, and the minimum requirements for Windows XP is an i586 processor. I can add this back if its really necessary, of course, but it doesn't seem sensible.


* Visual C++ 15 is supported.

Thanks to MS always being a special snowflake, VC15 reports an _MSC_VER of 1910, which yields a compiler version of 14.1 (should be 15) and VC Runtime version of 141 (should be 140). So, it has special handling, sadly.


* Invalid target architecture values error out.

This seems a saner behaviour than the current "silently use compiler defaults".


* Target architecture values unsupported by the compiler gracefully downgrade to the next available one, and print a warning.

The path is AVX2->AVX->SSE/nothing, depending on VC's version and x86/x64.

This is currently only for VC >= 8, though its trivial to add for VC < 8 if desired.



Still to do is checking the GVimExt and VisVim makefiles, to see if they properly generate fp87 code with CPUNR=(i586|i686|any) under VC11 and up.

**Comment by Taverius** [comment]
I've checked the GVimExt and found that, indeed, when used with VC>=11 it was generating SSE2 x86 code even if the user specified fp87 via CPUNR=i(3-6)86, as it was ignoring the the architecture target set by the main Makefile.

Have that fixed now by passing the generated `CPUARG` to it from the main one and including it in the `cflags` used by the GVimExt Makefile.

I noticed that it the GVimExt Makefile has a default APPVER of 5.0, which equals to Windows 2000.

Since we don't support it, I have it switched to a default of 5.01 (XP), but I also noticed that [vim-win32-installer](https://github.com/vim/vim-win32-installer) uses WINVER=0x500 (2000).

@k-takata, @chrisbra since you're building the installer binaries targeting Windows 2000, why? Should I leave the default for GVimExt to Win 2000?

There's a deeper issue here of relying on Win32.mak which is unsustainable in the long run, but that's a discussion for another time ...

**Comment by k-takata** [comment]
When we implemented Jobs and some other new features for Vim 8, we used some APIs newly added in Win XP. So we set the default WINVER to 0x0501 for (g)vim.exe. However GVimExt doesn't use such APIs. Therefore the setting is just left as it is.
There's no need to change the version, but it might be okay to change it for consistency.

> There's a deeper issue here of relying on Win32.mak which is unsustainable in the long run,

Yes, I think we should stop using Win32.mak sooner or later.

**Comment by vim-ml** [comment]
> There's no need to change the version, but it might be okay to change it
for consistency.

I believe SDK 8 and up will quietly complain, since they can't build code
for NT/2000; I've changed it, for sanity's sake.

Attached patch correctly builds with VC15, and correctly builds fp87 x86
code by default for both Vim and GVimExt with VC11 and above.

Also fixes various issues in my logic I missed with the earlier patch.

**Comment by Taverius** [comment]
One final question before I make a pull, regarding the GvimExt Makefile:

Currently, it has no provision for setting the right `/arch:` flag on its own.

With my changes, it sets the right flags **if** it is called from the main Make_mvc.mak with the `GvimExt/gvimext.dll` target.

However, looking at a few build scripts, including [vim/vim-win32-installer](https://github.com/vim/vim-win32-installer), its often called directly, thus again the issue of generating code targeting the default processor instruction set for that VC version.

Should I leave it as-is, and assume people know, or copy over the logic for `CPUNR`?
