### ISSUE TITLE
In help documents, we should unify the spelling “Vim” or ”VIM".

### ISSUE THREAD

**Issue by Tatsuki-I** [vim/vim#1732]
There are 2 kinds spelling, “Vim” and “VIM” in the help documents.
For example, arabic.txt unified by “VIM"(but only L230 spelled "Vim”).
But autocmd.txt unified by “VIM”.
I think we should unify the spelling. But I don’t know which spelling should be chosen.

**Comment by vim-ml** [comment]
On Monday, May 29, 2017 at 7:03:51 PM UTC+10, Tatsuki wrote:
> There are 2 kinds spelling, “Vim” and “VIM” in the help documents.
> 
> For example, arabic.txt unified by “VIM"(but only L230 spelled "Vim”).
> 
> But autocmd.txt unified by “VIM”.
> 
> I think we should unify the spelling. But I don’t know which spelling should be chosen.

Yes please! The documentation has evolved over many years and the style of how Vim/VIM/vim appears should be cleaned up. Also, let's fix gvim/Gvim/GVim/GVIM/gVim.

At the sadly neglected Vim wiki, we chose "Vim" and "gvim" despite the inconsistency. The "Vim" spelling fits modern usage such as in "Python" and many other packages. But then "Gvim" is rather weird, and "gVim" is very weird.

It would be nice to clean up the text shown by :version which starts with:

VIM - Vi IMproved 8.0

That might be better as:

Vim - vi improved 8.0.123

The patch level should be included. The above would mean patches 1 to 123 inclusive have been applied.

John

**Comment by Tatsuki-I** [comment]
All right.
I will fix it to "Vim" and "gvim" style.

**Comment by Tatsuki-I** [comment]
I have a question.
Should I change "VIM REFERENCE MANUAL" to " Vim REFERENCE MANUAL" or others?

**Comment by vim-ml** [comment]
IMHO, if it's in all caps it should stay in all caps. So, either "Vim
Reference Manual" or its all-caps variant, "VIM REFERENCE MANUAL",
whichever is closer to what already exists, and if both versions exist
in different files, let's standardize to which of the two occurs more
often.

Best regards,
Tony.

**Comment by chrisbra** [comment]
fixed as of 6aa8cea46d4179b2617daae034
