### ISSUE TITLE
vim.error: Vim:E315: ml_get: invalid lnum: 16

### ISSUE THREAD

**Issue by Yggdroot** [vim/vim#1737]
```python
python << EOF

import vim
import time

vim.command("vsp test.txt")
b = vim.current.buffer
vim.command("hide")

EOF

function! Test()

python << EOF

b[:] = ['test']

EOF
endfunction

map <F5> :call Test()<CR>
```
Windows 10, vim8.0.92
Linux, vim 8.0.559

Source the code, and then press `<F5>`, the error occurs.

**Comment by brammool** [comment]
Yggdroot wrote:

> ```python
> python << EOF
> 
> import vim
> import time
> 
> vim.command("vsp test.txt")
> b = vim.current.buffer
> vim.command("hide")
> 
> EOF
> 
> function! Test()
> 
> python << EOF
> 
> b[:] = ['test']
> 
> EOF
> endfunction
> 
> map <F5> :call Test()<CR>
> ```
> Windows 10, vim8.0.92
> Source the code, and then press `<F5>`, the error occurs.

I cannot reproduce this on Linux.

-- 
At some point in the project somebody will start whining about the need to
determine the project "requirements".  This involves interviewing people who
don't know what they want but, curiously, know exactly when they need it.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Yggdroot** [comment]
Please use this instead and have a try.
```python
python << EOF

import vim
import time

vim.command("vsp test.txt")
b = vim.current.buffer
vim.command("hide")

EOF

function! Test()

python << EOF

b[:] = []

EOF
endfunction

map <F5> :call Test()<CR>
```

**Comment by LemonBoy** [comment]
I've been able to reproduce this with `-u NONE`, open the test case, put the cursor on one of the last few lines and then `so % | cal Test()`.
Here's the stack trace:

- `SetBufferLineList`
- `py_fix_cursor` with args `(lo=1, hi=2, extra=-1)`

The cursor position isn't properly adjusted in the last function, `curwin->w_buffer` points to `test.txt` and `curwin->w_cursor` is the same as when the `Test()` function is called.

**Comment by Yggdroot** [comment]
@brammool Any updates? Could you please fix this bug?

**Comment by bendoh** [comment]
This also occurs with the python3-enabled vim build: Just update the sample above to use `python3` 

```
python3 << EOF

import vim
import time

vim.command("vsp test.txt")
b = vim.current.buffer
vim.command("hide")

EOF

function! Test()

python3 << EOF

b[:] = ['more', 'lines', 'than', 'youd', 'think']

EOF
endfunction

nnoremap <F5> :call Test()<CR>
```

source, then `F5`, and i get the following:

```
Error detected while processing function Test:
line    6:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
vim.error: Vim:E315: ml_get: invalid lnum: 21
```

**Comment by k-takata** [comment]
Reproduced with a simpler example (on Win32 and Cygwin)

```vim
python3 << EOF

import vim

vim.command("vsp test.txt")
b = vim.current.buffer
vim.command("hide")

b[:] = []

EOF
```

Open this file and type `G` to goto the last line (11th line), then `:so %`:

```
"test.txt" [Modified][New file] --No lines in buffer--
Error detected while processing /tmp/test-1737.vim:
line   11:
Traceback (most recent call last):
  File "<string>", line 8, in <module>
vim.error: Vim:E315: ml_get: invalid lnum: 10
```

After this, the cursor jumps to the 10th line.
If the cursor is in the 1st or 2nd line before `:so %`, this doesn't happen.

If I comment out the line `vim.command("hide")`, this doesn't also happen.

**Comment by alexgenco** [comment]
Not sure if this is the exact same problem, but I can reproduce this error with just `vim -u NORC +'sleep 10ms' +'split | call append(0, ["foo"]) | split'` (the sleep is required).

I ran a bisect and I think it was introduced here https://github.com/vim/vim/commit/ca851593a660f08aba5c134f90c238d4a3e983e6

Edit: Also reproduced with `-u NONE` .

**Comment by lacygoill** [comment]
Since the issue has been fixed, then this whole block in the todo list is no longer relevant:

https://github.com/vim/vim/blob/21829c5f2c86cd525c8468121b4fc54c5d75bf6e/runtime/doc/todo.txt#L909-L912

**Comment by brammool** [comment]
> Since the issue has been fixed, then this whole block in the todo list
> is no longer relevant:
> 
> https://github.com/vim/vim/blob/21829c5f2c86cd525c8468121b4fc54c5d75bf6e/runtime/doc/todo.txt#L909-L912

I appreciate the remark, but please quote the text, the line numbers
change quite often.  Hmm, looks like the patch you sent includes this.

-- 
Vi is clearly superior to emacs, since "vi" has only two characters
(and two keystrokes), while "emacs" has five.  (Randy C. Ford)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
