### ISSUE TITLE
Vim vs swp files on Windows -- timing / time stamp issue?

### ISSUE THREAD

**Issue by kwizzz** [vim/vim#1741]
I am having troubles with vim (8.0.586 and 7.4 downloaded from www.vim.org) on Windows 7.

There seems to be a time stamp issue with swap files where swap files will not
get removed after closing vim with swap files being 1 second newer than saved
file; when trying to edit the file later, vim will complain with swap exists.

Steps to reproduce behaviour:
- open a file (it does not matter if it exists or not) => vim will create
  corresponding swp file
- do a short editing session (only a few (~4) seconds, not too long) and
  immediately save and close it => swp file stays in file system in about 10%
  (with a higher chance if `hidden` is set)

Behaviour can be reproduced with a higher probability, if you open vim with a
file, do a `:vimgrep/./*` over about 20 or more text files in the folder,
randomly navigate through the findings (`:cn` & co) and close vim => some
opened (sometimes even simply grepped) files leave swap files.

Tried `vim -u NONE` with same behaviour.

Please let me know what to do to provide more information to you, as I am
somewhat lost here...

**Comment by vim-ml** [comment]
On Friday, June 2, 2017 at 3:36:40 PM UTC-5, kwizzz wrote:
> I am having troubles with vim (8.0.586 and 7.4 downloaded from www.vim.org) on Windows 7.
> 
> There seems to be a time stamp issue with swap files where swap files will not
> 
> get removed after closing vim with swap files being 1 second newer than saved
> 
> file; when trying to edit the file later, vim will complain with swap exists.
> 
> Steps to reproduce behaviour:
> 
> open a file (it does not matter if it exists or not) => vim will create
> 
> corresponding swp file
> do a short editing session (only a few (~4) seconds, not too long) and
> 
> immediately save and close it => swp file stays in file system in about 10%
> 
> (with a higher chance if hidden is set)
> 
> 
> Behaviour can be reproduced with a higher probability, if you open vim with a
> 
> file, do a :vimgrep/./* over about 20 or more text files in the folder,
> 
> randomly navigate through the findings (:cn & co) and close vim => some
> 
> opened (sometimes even simply grepped) files leave swap files.
> 
> Tried vim -u NONE with same behaviour.
> 
> Please let me know what to do to provide more information to you, as I am
> 
> somewhat lost here...
> 

It could be a virus scanner preventing Vim from deleting the file if it has it open for scanning.

It also could be a problem with a network share (you didn't say if any particular location is affected).

You could try experimenting with the 'directory' option to place all your swap files in a different local folder, especially if you can put that folder in a virus scanner whitelist.

**Comment by vim-ml** [comment]
Ben Fritz wrote:

> On Friday, June 2, 2017 at 3:36:40 PM UTC-5, kwizzz wrote:
> > I am having troubles with vim (8.0.586 and 7.4 downloaded from www.vim.org) on Windows 7.
> > 
> > There seems to be a time stamp issue with swap files where swap files will not
> > 
> > get removed after closing vim with swap files being 1 second newer than saved
> > 
> > file; when trying to edit the file later, vim will complain with swap exists.
> > 
> > Steps to reproduce behaviour:
> > 
> > open a file (it does not matter if it exists or not) => vim will create
> > 
> > corresponding swp file
> > do a short editing session (only a few (~4) seconds, not too long) and
> > 
> > immediately save and close it => swp file stays in file system in about 10%
> > 
> > (with a higher chance if hidden is set)
> > 
> > 
> > Behaviour can be reproduced with a higher probability, if you open vim with a
> > 
> > file, do a :vimgrep/./* over about 20 or more text files in the folder,
> > 
> > randomly navigate through the findings (:cn & co) and close vim => some
> > 
> > opened (sometimes even simply grepped) files leave swap files.
> > 
> > Tried vim -u NONE with same behaviour.
> > 
> > Please let me know what to do to provide more information to you, as I am
> > 
> > somewhat lost here...
> > 
> 
> It could be a virus scanner preventing Vim from deleting the file if it has it open for scanning.
> 
> It also could be a problem with a network share (you didn't say if any particular location is affected).
> 
> You could try experimenting with the 'directory' option to place all your swap files in a different local folder, especially if you can put that folder in a virus scanner whitelist.

If you are using a FAT file system (quite old now, but still exists on
some media): It has a write timestamp resolution of 2 seconds.  The
round-off error can cause problems.

-- 
hundred-and-one symptoms of being an internet addict:
18. Your wife drapes a blond wig over your monitor to remind you of what she
    looks like.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by kwizzz** [comment]
It's local NTFS.  I guess I need to see if I can disable the virus scanner, but as this is my work laptop, I don't have the rights to do this.

I was hoping that this is not file system or virus scanner related as my problem is getting worse if I have `:hidden` turned on?

As this is a corporate laptop, maybe other services might also cause a delay?  I have SafeGuard LANCrypt for encrypting content of folders, but not on the folders where vim behaves as described above.  I will try to deinstall it to see if situation is getting better.

In any way, in the end I cannot deinstall my virus scanner nor SafeGuard LANCrypt, so I guess I have to live with this.  There is no setting besides disabling swap files completely in vim, right?  This means that no backup when vim crashes (would be acceptable) and no lock against accidental editing the same file.

**Comment by k-takata** [comment]
> There is no setting besides disabling swap files completely in vim, right?

Have you tried `set noswapfile`?

**Comment by kwizzz** [comment]
Of course, but this means that there is no backup when vim crashes and no lock against accidental editing the same file, if I am not mistaken.

**Comment by vim-ml** [comment]
On Wednesday, June 7, 2017 at 1:55:14 PM UTC-5, kwizzz wrote:
> 
> As this is a corporate laptop...in the end I cannot deinstall my virus scanner
> 

I suggest asking IT if there is a whitelist folder pre-configured for the virus scanner. If you're a software shop at least, it's useful to have a place the developers can run the programs they themselves create. :-) Plus AV often interferes with version control.

**Comment by kwizzz** [comment]
Had the chance to disable virus scanner (TrendMicro OfficeScan) and the effect could not be reproduced in a half-day editing session.
Need to check for folder whitelisting.  But that means that I have to keep all my swap files in one place instead in the folder of the currently edited file.
So only solution is to disable swap, loosing the chance of a backup if vim crashes and risking editing the same file in two different vim instances, right?

**Comment by k-takata** [comment]
> But that means that I have to keep all my swap files in one place instead in the folder of the currently edited file.

As already pointed out, you can do this by setting the `'directory'` option.

**Comment by fritzophrenic** [comment]
> Had the chance to disable virus scanner (TrendMicro OfficeScan) and the effect could not be reproduced in a half-day editing session.

Since it seems to be the virus scanner, I assume the problem occurs when you write the swap file triggering a virus scan. So I wonder if you first write, then wait 5 seconds or so, and then quit, whether the issue can be avoided.

If that does avoid the issue, then I wonder if you could work around the problem by adding a timed wait before allowing Vim to exit. Something like:

`autocmd VimLeave * sleep 7`

**Comment by chrisbra** [comment]
closing, as this seems not to be a direct Vim bug.
