### ISSUE TITLE
JavaScript syntax highlight broke by the slash.

### ISSUE THREAD

**Issue by arlendotcn** [vim/vim#1742]
Testing code:
```javascript
var a = [
    '<div class="main">',
        'The result is:<strong>', iTotal/iParts, '</strong>.'
    '</div>'
].join('');
```
The syntax highlight broke by the `/`.

![js_issue](https://cloud.githubusercontent.com/assets/6712608/26751269/f0d52076-4867-11e7-8f96-d6712273a4ba.PNG)

**Comment by brammool** [comment]
I do not see this problem.  The header of the syntax file says it was last updated 2013 Jun 12

**Comment by chrisbra** [comment]
please report to the syntax file maintainer.
