### ISSUE TITLE
Shell commands containing "|" get input redirection inserted before "|" on Windows

### ISSUE THREAD

**Issue by johannes-riecken** [vim/vim#1743]
If I execute the ex command `%!perl -lpE "s/a|b/c/"` in a freshly installed Vim 8.0.586 under Windows 10, a command line opens with the generated command
`C:\WINDOWS\system32\cmd.exe /c (perl -lpE ^"s/a ^<C:\Users\Jo\AppData\Local\Temp\VIi83B6.tmp ^|b/c/^" ^>C:\Users\Jo\AppData\Local\Temp\VIo83B7.tmp 2^>^&1)`
which inserts the input redirection incorrectly before the vertical bar character.

**Comment by Houl** [comment]
As a workaround, try not using temp files: `:set noshelltemp`.
