### ISSUE TITLE
Plate shifting when using windows10 command prompt connect to AWS EC2.

### ISSUE THREAD

**Issue by EasonWang01** [vim/vim#1758]
![asd](https://user-images.githubusercontent.com/11001914/26958589-23a3d19c-4cfe-11e7-9e02-802e8510b39c.png)

But looks good when connected by putty.

**Comment by k-takata** [comment]
> But looks good when connected by putty.

Then it's a problem of Windows command prompt, not Vim.
Recently KB4020102 (OS build number 15063.332) was released and it includes some fixes of command prompt. I'm not sure it solves the problem.

**Comment by chrisbra** [comment]
closing then.
