### ISSUE TITLE
Recursive use of :global

### ISSUE THREAD

**Issue by MilesCranmer** [vim/vim#1760]
Hi, I was wondering why the recursive use of `:global` is disabled? It seems like it is quite elegant to chain them together, e.g.:
```
:g/foo/v/bar/s/^/\/\//g
```
Which is an intuitive way to comment out (with //) all lines containing foo but not bar.
This prints out (upon matching foo): `E147: Cannot do :global recursive`. 

I'm wondering if this is a safety thing or something about how the functionality is structured.

Cheers,
Miles

**Comment by brammool** [comment]
Miles Cranmer wrote:

> Hi, I was wondering why the recursive use of `:global` is disabled? It seems like it is quite elegant to chain them together, e.g.:
> ```
> :g/foo/v/bar/s/^/\/\//g
> ```
> Which is an intuitive way to comment out (with //) all lines
> containing foo but not bar.  This prints out (upon matching foo):
> `E147: Cannot do :global recursive`. 
>
> I'm wondering if this is a safety thing or something about how the
> functionality is structured.

The :g and :v commands use a mark on each line.  There is only one flag,
thus the nested command would clear the flags.

Perhaps we could make an exception if the nested command has a range of
one line.  It's indeed not easy to do something when a pattern does not
match.  Hmm, let me have a go at that...


-- 
How To Keep A Healthy Level Of Insanity:
8. Don't use any punctuation marks.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
