### ISSUE TITLE
Incorrect syntax highlighting

### ISSUE THREAD

**Issue by rieje** [vim/vim#1761]
- Vim (version: 8.0.628)
- Operating system/version: Arch Linux
- Terminal name/version:
- `$TERM`: xterm-termite

### Actual behaviour

Open a file with the following contents:

    #!/usr/bin/env bash

    pactl list sink-inputs | while read -r line; do
        [[ $line == "Sink Input #"* ]] && sink="${line#*#}"
        [[ $line == *'application.name = "mpv Media Player"' ]] && pactl set-sink-input-mute "$sink" toggle
    done

Incorrect syntax highlighting in the line containing the second pair of `[[ ... ]]`. You can see [here](https://ptpb.pw/ALRFYOUtbddiJd9TH84c98Vz6G6i.png).

### Expected behaviour
Correct syntax highlighting.

**Comment by lacygoill** [comment]
Fixed by https://github.com/vim/vim/commit/b0d45e7f5354375edd02afafde3bd37dac1515ff.
