### ISSUE TITLE
Can not start Electron on Windows 10 from Vim 8.0 Release

### ISSUE THREAD

**Issue by htzh** [vim/vim#1762]
I tested using the following functions:
```
function! s:OnOutput(channel, text)
    echom a:text
endfunction

function! eview#AsyncRun(cmd)
    let l:options = {}
	let l:options['out_io'] = 'pipe'
	let l:options['err_io'] = 'out'
	let l:options['in_io'] = 'null'
	let l:options['out_mode'] = 'nl'
	let l:options['err_mode'] = 'nl'
	let l:options['stoponexit'] = 'term'
    let l:options['callback'] = function('s:OnOutput')
    call job_start(a:cmd, l:options)
endfunction
```
I can do the following successfully:
```
call eview#AsyncRun(["node", "--version"])
call eview#AsyncRun(["where", "electron"])
```
But it does not work with Electron itself:
```
call eview#AsyncRun(["electron", "--version"])
```
I think ```:start! electron myapp``` does not work either. However shell out does work:
```
:!electron --version
```
Vim is vanilla official release 32 bit exe for Windows 10. Any idea on what the issue is here?

**Comment by mattn** [comment]
It should work with `call eview#AsyncRun(["electron.cmd", "--version"])`. you should have `electron` and `electron.cmd` both in your PATH.

**Comment by htzh** [comment]
Thanks! You are indeed right. So the ```.cmd``` extension is not necessary in a cmd console but required as a subprocess.
