### ISSUE TITLE
Vim lost file when E513 occurs

### ISSUE THREAD

**Issue by luochen1990** [vim/vim#1765]
reproduce steps:

1. `:set enc=utf8`
2. open a file named `hello.txt` and `:set fenc=ascii`
3. add a line "hello"
4. add a line "你好"
5. `:w` and find that E513 occurs
6. `:q!` to force exit Vim
7. open the file again and find that file `hello.txt` is empty now.

I think Vim should at least keep the old version of the file no matter what error occurs.

PS:  no matter whether there is a `:w` operation between step 3 and step 4 or not, the file will always become empty at last.

I'm using Windows 10 64-bit  and GVim 8.0

**Comment by brammool** [comment]
Vim clearly warns you for that:

"hello.txt" E513: write error, conversion failed (make 'fenc' empty to override)

WARNING: Original file may be lost or damaged
don't quit the editor until the file is successfully written!

**Comment by chrisbra** [comment]
I think this is the same problem as reported [a couple of years ago](https://groups.google.com/d/msg/vim_dev/AasG5Q8bcD8/mRQLnqdZCowJ)
I even made a patch back then, I think it was [this one](https://github.com/chrisbra/vim-mq-patches/blob/master/conversion_error)

**Comment by luochen1990** [comment]
@brammool. Yes, there is a warning. But I think a warning is not a good enough solution, the "clear and write" action should be atomic, if there is some error, the whole action should be reverted, not just stop and warning.  Please consider my suggestion since Vim is too important to a lot of people.

**Comment by grochmal** [comment]
I have no clue what you are calling "clear and write".  But had Vim quit on `:q` (instead of `:q!`), which it does not, what you propose would be a bug.

If you quit with `:q!` it does not matter whether you forgot to write the file or the write failed, you simply do not get checking whether the file was written (because that is the purpose of `:q!`).  `:q` prints a warning too (and do not quit Vim) in your case.

**Comment by k-takata** [comment]
> I think Vim should at least keep the old version of the file no matter what error occurs.

Vim does exactly what you expected, I think.

1. `:set enc=utf8`
2. create a file named `hello.txt` and `:set fenc=ascii`
3. add a line "hello"
4. `:w`
5. add a line "你好"
6. `:w` and find that E513 occurs
7. `:q!` to force exit Vim
8. open the file again. You will see "hello".

**Comment by luochen1990** [comment]
@k-takata actually, not true, I indeed did a `:w` between adding "hello" and "你好", but "hello" is still missing at last,  did you tried?

PS:  I'm using Windows 10 and GVim 8.0, the version info of my GVim is following:

> VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 21 2017 22:02:21)
> MS-Windows 64-bit GUI version 带 OLE 支持
> 包含补丁: 1-577

**Comment by luochen1990** [comment]
@grochmal  I think I missed some important step in my initial post, actually, no matter whether there is a :w operation between step 3 and step 4 or not, the file will always become empty at last,  this is exactly the wield thing, and it looks like Vim clears the file before it try to translate the file encoding, and write it after the translation, so I call it  "clear and write",  but when there occurs some error, the file is cleared without write anymore.
@brammool   Hope you consider it again, thx.

**Comment by grochmal** [comment]
I did try your extended/updated step and it still performs what I expect it to.  Outline:

1. `[~]$ vim -u NONE --noplugin yay.txt`
2. `:set enc=utf-8`
3. `ihello<esc>`
4. `:w`
5. `ocoração<esc>` (that's portuguese)
6. `:w`(E513 occurs)
7. `:q!`
8. `[~]$ cat yay.txt`
9.  produces `hello`

I'd blame your behaviour on filesystem caching combined with (misguided) OS security features.  I'm on Linux 4.11, ext4, Vim 8.0.628

**Comment by k-takata** [comment]
Okay, I can reproduce the problem when I do `set nowritebackup nobackup`.
In this case, the following messages are shown (as already pointed out by @brammool) and the file becomes empty:

```
"hello.txt" E513: write error, conversion failed (make 'fenc' empty to override)
WARNING: Original file may be lost or damaged
don't quit the editor until the file is successfully written!
```

If do `set writebackup` (this is the default) and/or `set backup`, the message is different and the file doesn't become emtpy:

```
"hello.txt" E513: write error, conversion failed (make 'fenc' empty to override)
```

@luochen1990
If this is the case, the problem will be solved by @chrisbra's patch, however I strongly recommend you to stop using the setting.
If not the case, please report more detail.

**Comment by chrisbra** [comment]
note however, that `'backup'`  defaults to off and `'writebackup'` will be off by default whenever you write something in places that match the `'backupskip'` option, so you could trigger the codepath, when writing e.g. into $TMP or /tmp (which kind of makes sense, since the data is then probably relatively unimportant).

**Comment by luochen1990** [comment]
@k-takata  You are right, it will be ok when `:set backup`.  I disabled backup because I used to use web-drive to backup my file, and the template vim backup files will pollute my web-drive space ...

Thanks every one here :)

**Comment by luochen1990** [comment]
But I'm still wondering why I have to lost my file in this case, is there any other solution which can solve it ?  Maybe translate the encoding in memory and write it back to drive after the traslation is completed correctly.  or write the traslating result to a temp file if the file is too large to keep it in memory ...
