### ISSUE TITLE
Behaviour change suggestion: /g substitute always global even if gdefault set

### ISSUE THREAD

**Issue by bluz71** [vim/vim#1767]
Hello Vim team,

I wrote a blog [post](https://bluz71.github.io/2017/05/15/vim-tips-tricks.html) recommending that Vim users enable `gdefault` and posted it to [reddit](https://www.reddit.com/r/vim/comments/6gk6tb/vim_tips_tricks).

When `gdefault` is set substitutions will always be global unless one tacks on `/g` which then **inverts** to only do first match substitution.

chrisbra10, on reddit, noted that `gdefault`, when set, potentially breaks *some* plugins and he produced this list:

- [csv.vim](https://github.com/chrisbra/csv.vim/commit/1580aacc16438db36a621fe777707b4f5aba4a3a)
- [man.vim](https://github.com/neovim/neovim/pull/5182)
- [quicktex.vim](https://github.com/brennier/quicktex/pull/5)
- [unite-spell-suggest](https://github.com/kopischke/unite-spell-suggest/issues/3)
- [vim-over](https://github.com/osyo-manga/vim-over/issues/30)
- [vim-table-mode](https://github.com/dhruvasagar/vim-table-mode/issues/20)
- [neocomplcache](https://github.com/Shougo/neocomplcache.vim/issues/120)
- [vim-html-escape](https://github.com/skwp/vim-html-escape/issues/2)
- [vim-markdown](https://github.com/plasticboy/vim-markdown/pull/225)

It looks like most of the above were fixed, hence users who set `gdefault` are  most likely not going to encounter issues. However, that does not mean no issues will ever be encountered with some plugins.

My question is, why does `/g` invert when `gdefault` is set? Vi compatibility?

`/g` means global, as in potentially global **always** no matter whether `gdefault` is set or not? Blog posts like mine might mean that more users may set `gdefault`. The current toggling behaviour of `/g` appears to cause problems as listed above, and whilst `gdefault` exists it may get worse.

Side note, please don't get rid of `gdefault`, users like myself who set it *want it*.

Maybe a new `/v` (for vglobal) flag should exist to force first only substitution for users who set `gdefault` and currently use `/g` to invert? Note, I doubt many folk fall into that camp. 

I leave it to you to figure out whether this is worth doing or closing. Just a suggestion.

Thanks.

**Comment by chrisbra** [comment]
The toggling was probably done to have a way for users to not replace globally, but don't know for sure.
I think changing the meaning for `&gdefault` is out of the question, since this breaks backwards compatibility. I would rather say, dont't change anything  in this area, it will break assumptions for existing scripts. Rather, strongly discourage the use of that option and better make a way to have scripts run with sane options (as dicussed previously on vim-dev)

**Comment by brammool** [comment]
The 'gdefault' option is a very old one, and it works in a confusing way.
In my opinion it's better to recommend against using it.
It's easy enough to type /g when you need it (just like you would prepend % to work on the whole buffer).
Typing this automatically is a lot better than trying to remember what 'gdefault' was set to and then deciding whether to add it or not.
