### ISSUE TITLE
Timer breaks Ex command completion

### ISSUE THREAD

**Issue by dpelle** [vim/vim#1768]
Timer breaks Ex command completion.

Steps to reproduce:
```
$ cat bug.vim
function! Test(...)
endfunction
call timer_start( 100, 'Test', {'repeat': -1} ) 
```
```
$ vim -u NONE -S bug.vim
```
Then in Vim press:

```
:e bu<CTRL-D>
```
I would expect it to complete file name "bug.vim" but the completion
shows up only for a fraction of a second before is disappears.

When commenting the line "call timestart(..." in bug.vim, then
Ex completion works fine.

It's not just the Ex completion that is broken, I also see that the
output of the   :ts some_tag    command also disappears. 

My vim version:
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 13 2017 20:48:37)
Included patches: 1-642
Compiled by pel@pel-cirrus7
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
+balloon_eval    +folding         +mouse_xterm     +termguicolors
+browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
+clientserver    +insert_expand   +packages        +toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        -perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  -lua             +rightleft       +writebackup
+diff            +menu            -ruby            +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     +xpm
+emacs_tags      +mouseshape      +startuptime     +xsmp_interact
+eval            +mouse_dec       +statusline      +xterm_clipboard
+ex_extra        +mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax
+farsi           +mouse_netterm   +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
```
I'm using xubuntu-16.04 on Linux.

This issue was initially reported in this Vim plugin https://github.com/Valloric/YouCompleteMe/issues/2683 and it was then found to be a bug in Vim rather than in the plugin.

**Comment by micbou** [comment]
This is a regression from commit https://github.com/vim/vim/commit/29ae377ea7039874337bc79ace9ab2b37b9056e5. I can reproduce the issue in 8.0.0592 but not in 8.0.0591.

**Comment by dpelle** [comment]
If I replace the line...
```
call timer_start( 100, 'Test', {'repeat': -1} )
```
... in bug.vim with:
```
call timer_start( 5000, 'Test', {'repeat': -1} )
```
... then it's clearer that the Ex completion output disappears after 5 seconds when the timer kicks in.

**Comment by brammool** [comment]
micbou wrote:

> This is a regression from commit https://github.com/vim/vim/commit/29ae377ea7039874337bc79ace9ab2b37b9056e5. I can reproduce the issue in 8.0.0592 but not in 8.0.0591.

Thanks, that is useful.

Perhaps we need to have a counter for displaying messages.  When the
count didn't change while invoking the callback then a redraw is not
needed.

-- 
hundred-and-one symptoms of being an internet addict:
34. You laugh at people with a 10 Mbit connection.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by haolongzhangm** [comment]
brammool  and micbou 
yes 
try to revert 29ae377 issue is gone!

**Comment by prabirshrestha** [comment]
I believe this also breaks [asyncomplete.vim](https://github.com/prabirshrestha/asyncomplete.vim) which relies on timer.

With latest vim when I'm typing `import` it types `imort` usually always removing the third character.

I went back to vim 8 path 589 and don't seem to have this problem.

**Comment by chrisbra** [comment]
This happens, because in redraw_after_callback() cmdline_row is reset to the first of the scrolled lines. I am not sure why this has been added, because that means, we are drawing the cmdline beginning at the first scrolled line and that sounds wrong. I think this patch fixes it:
```patch
diff --git a/src/screen.c b/src/screen.c
index 617645391..b7b36251b 100644
--- a/src/screen.c
+++ b/src/screen.c
@@ -451,15 +451,9 @@ redraw_after_callback(void)
            compute_cmdrow();
        }
        else
-       {
            /* Redraw in the same position, so that the user can continue
             * editing the command. */
            compute_cmdrow();
-           if (cmdline_row > msg_scrolled)
-               cmdline_row -= msg_scrolled;
-           else
-               cmdline_row = 0;
-       }
        redrawcmdline_ex(FALSE);
     }
     else if (State & (NORMAL | INSERT))
```
If we do not reset cmdline_row, it should start redrawing at the current line where the cmdline is before the timer has been triggered.

**Comment by chrisbra** [comment]
Even simpler:
```patch
diff --git a/src/screen.c b/src/screen.c
index b7b36251b..11f003673 100644
--- a/src/screen.c
+++ b/src/screen.c
@@ -446,14 +446,10 @@ redraw_after_callback(void)
     {
        /* Redrawing only works when the screen didn't scroll. */
        if (msg_scrolled == 0)
-       {
            update_screen(0);
-           compute_cmdrow();
-       }
-       else
-           /* Redraw in the same position, so that the user can continue
-            * editing the command. */
-           compute_cmdrow();
+       /* Redraw in the same position, so that the user can continue
+        * editing the command. */
+       compute_cmdrow();
        redrawcmdline_ex(FALSE);
     }
     else if (State & (NORMAL | INSERT))
```

**Comment by brammool** [comment]
Christian Brabandt wrote:

>  Even simpler:

That's not going to work when editing a command line that wraps.
Every timer call would then cause the screen to scroll.
In this specific situation, we probably should not call compute_cmdrow()
at all, since we want to draw the command line in-place, without
clearing what was displayed above it.
If the timer caused some output then the command line might overwrite
it.  I think that's OK, since you do want to keep editing the command
line.  Some text above it may then be a mix of what was there before (in
this case the text that was echo'ed) and whatever the timer put there.


-- 
I'm writing a book.  I've got the page numbers done.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bstaletic** [comment]
After Vim 8.0.0710 I can't reproduce the issue described here. Did that commit solve thi?

**Comment by prabirshrestha** [comment]
Doesn't seem to fix asyncomplete. (Let me know if this is a separate issue)

Here is how it looks in 589.

![good](https://user-images.githubusercontent.com/287744/28224707-0303e02e-6885-11e7-9013-af13b508b810.gif)

Here is how it looks in 711. In both cases I'm trying to type as fast as I can but notice how 589+ swallows the third character i.e. `this` is typed as `ths`.

![bad](https://user-images.githubusercontent.com/287744/28224724-0d36a388-6885-11e7-9d88-97f5e8be96b2.gif)

**Comment by brammool** [comment]
8.0.0710 only solves the command line completion.
I'm still looking for simple ways to reproduce the other problems.
Loading a complicated plugin isn't that simple...

**Comment by markonm** [comment]
I also noticed related issue. If timer is present and I type `<C-r>` in command line than `"` is not displayed (or it is hidden after timer kicks in). It's still present after 8.0.0710.

![s](https://user-images.githubusercontent.com/16160229/28235284-ff66a63c-690a-11e7-8f60-85e273d99b5e.gif)

**Comment by brammool** [comment]
The original problem should be fixed now.
I can't reproduce the asyncomplete bug, and it's a different problem.
Please report it separately and give an easy to reproduce example.
