### ISSUE TITLE
Vim crashes with sigsev when setting encoding 

### ISSUE THREAD

**Issue by bmurauer** [vim/vim#1770]
I have a file containing some ill-encoded text (see attachment). I tried to set the encoding using `:set encoding=8bit-cp1252`, at which point vim crashes. 

vim: v.8.0
Included patches: 1-628
I'm running arch linux and all packages are up-to-date. 
[example.txt](https://github.com/vim/vim/files/1074329/example.txt)

**Comment by bmurauer** [comment]
I'm very sorry for opening this ticket too soon, turns out that the problem was somehow related to the nerd-fonts package, not with vim. This can be deleted, but I can't figure out how.

**Comment by tonymec** [comment]
I don't think the ticket can be *deleted* but it can be *closed* — something you did yourself, a little less than half an hour ago.

**Comment by chrisbra** [comment]
For whatever Reason, Vim shouldn't crash. So a gdb backtrace is still appreciated in order to handle this error gracefully (if possible)

**Comment by ZyX-I** [comment]
The `&encoding` option is not supposed to be set ever after starting Vim: it immediately invalidates all non-ASCII strings present in Vim memory. I am not surprised this finally resulted in a crash (and would not be surprised to know that there are many more such crashes in the archives, but can’t remember anything now). Neovim which before deciding to force `&encoding` to be utf-8 always had been restricting setting this option after startup looks like using a better approach. It still allows maintaining some related features Neovim is not interested in (specifically dropping multibyte support with some other FEAT_… for decreased size of binary). (Patch was made in neovim/neovim#2929.)

**Comment by chrisbra** [comment]
What makes you think, that this is caused by making &encoding changeable?

**Comment by jamessan** [comment]
It's hard to know whether this specific issue is caused by &encoding changing after startup without more details.  However, it's a known issue that doing so can cause crashes.  I brought this [up] over 8 years ago when I floated the idea of always using UTF-8 for &encoding.

[up]: https://groups.google.com/d/msg/vim_dev/up1KslPRGzk/9xwHeIb6WWgJ

**Comment by chrisbra** [comment]
I remember that discussion and would be very much in favor of such a change, especially since this would clean up all those nasty ifdefs, that often cause problems when changing only one or the other part of the ifdef.
