### ISSUE TITLE
gvim silent install fail - ask question

### ISSUE THREAD

**Issue by allburov** [vim/vim#1771]
When I try to install gvim with silent mode by **gvim.exe /S**, I see popup message "This will install Vim 8.0 on your computer. Continue?"

*Expected behavior* - Run install without any user interaction

I want install vim to windows-docker container, it's have not any GUI.

**Comment by allburov** [comment]
**.onInit** should not have **MessageBox**

**Comment by chrisbra** [comment]
okay, since you made a PR #1772, closing this then.
