### ISSUE TITLE
Illegal backreference hangs in NFA

### ISSUE THREAD

**Issue by urticadioica** [vim/vim#1774]
To make this example work, you need at least one `a` in your buffer.

The simplest offending regex I've found is `\v(a|\1)*`. Under `:set regexpengine=1` this just errors with `E65: Illegal back reference`, but with `:set regexpengine=2` it hangs Vim (with rapidly growing memory usage) and forces a `kill -9`.

The fact that the NFA engine should give more E65 errors [isn't new](https://github.com/vim/vim/blob/master/runtime/doc/todo.txt#L104), though this example can cause lost work, so it's less innocent.

**Comment by LemonBoy** [comment]
I think it's just a matter of porting [this](https://github.com/vim/vim/blob/master/src/regexp.c#L2101,L2121) snippet [here](https://github.com/vim/vim/blob/master/src/regexp_nfa.c#L1449).

**Comment by brammool** [comment]
urticadioica wrote:

> To make this example work, you need at least one `a` in your buffer.
> 
> The simplest offending regex I've found is `\v(a|\1)*`. Under `:set
> regexpengine=1` this just errors with `E65: Illegal back reference`,
> but with `:set regexpengine=2` it hangs Vim (with rapidly growing
> memory usage) and forces a `kill -9`.
> 
> The fact that the NFA engine should give more E65 errors [isn't
> new](https://github.com/vim/vim/blob/master/runtime/doc/todo.txt#L104),
> though this example can cause lost work, so it's less innocent.

In this case the timeout and pressing CTRL-C doesn't help to get out of
the pattern matching code.  That's quite nasty.  Even when I make it
work to have CTRL-C quit searching, with 'hlsearch' set Vim is hardly
useable.

I'm not sure if the problem with the pattern is worth fixing.  I don't
get that Error though.

-- 
Latest survey shows that 3 out of 4 people make up 75% of the
world's population.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
