### ISSUE TITLE
What you think about merging statusline with commandline in some way?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [vim/vim#1779]
![screen shot 2017-06-19 at 8 14 28 am](https://user-images.githubusercontent.com/3514015/27270516-5e478f16-54c7-11e7-8dae-6ae52c340ca2.png)

Usually I have enough of space to see `-- INSERT --` in the statusline.

I was looking for the solution and found [only this question](https://stackoverflow.com/questions/20698197/how-to-merge-vim-commandline-and-statusline).

**Comment by chrisbra** [comment]
That is already partly possible. In your statusline, you can put the mode into it by making use of a function. Then you can disable 'showmode'

**Comment by vitaly-zdanevich** [comment]
But `set noshowmode` do not hide the empty line - this is the purpose to merge them.

**Comment by chrisbra** [comment]
the empty line is for entering commands. There is 'cmdheight' setting, but it does not allow to be set to zero. Duplicate of #940
