### ISSUE TITLE
Default values for `QuickFixLine` make the selected entry in a quickfix window unreadable for many colorschemes

### ISSUE THREAD

**Issue by manasthakur** [vim/vim#1780]
It seems that in [this commit](https://github.com/vim/vim/commit/2102035488e80ef6fd5038ed15d21672712ba0f6), a new highlight-group called the `QuickFixLine` has been added, along with some default values (`src/syntax.c` in the mentioned commit).

This actually breaks many colorschemes, which rely on the `Search` group for the same. Can this please be resolved soon? I think it would be better to just keep `QuickFixLine` linked to `Search` instead of giving any default colors.

**Comment by manasthakur** [comment]
In fact, the place from where this idea seems to be originated (based on [this PR](https://github.com/vim/vim/pull/1755), Neovim), actually keeps `QuickFixLine` linked to `Search`. Can you please do the same?

**Comment by brammool** [comment]
Manas Thakur wrote:

> In fact, the place from where this idea seems to be originated (based on [this PR](https://github.com/vim/vim/pull/1755), Neovim), actually keeps `QuickFixLine` linked to `Search`. Can you please do the same?

That indeed would avoid trouble.

-- 
The real
trick is
this: to
keep the
lines as
short as
possible
and keep
the size
the same
yet free
from the
need for
hyphena-
Dammit!!  (Matthew Winn)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by manasthakur** [comment]
Right. I assume we will get it in one of the next patches then! Thanks :)

**Comment by justrajdeep** [comment]
Hi 

I think this might have broken the some colorschemes also. I am using `peachpuff`. If the line is too long I go to the end of the line and come back the syntax highlight goes off.

Thanks

**Comment by vim-ml** [comment]
On Tue, Jun 20, 2017 at 6:26 PM, justrajdeep <vim-dev-github@256bit.org> wrote:
> Hi
>
> I think this might have broken the some colorschemes also. I am using
> peachpuff. If the line is too long I go to the end of the line and come back
> the syntax highlight goes off.
>
> Thanks

Maybe the 'synmaxcol' setting is relevant.

Best regards,
Tony.

**Comment by justrajdeep** [comment]
It might be something to do with `synmaxcol`. I am manually setting it to 10000 but it stops the syntax highlight even with 399 columns(my file has 399 columns). 

I tried to not set it manually, it defaults to 3000, even then I see the same behavior.

when I return back to col 0, should it not  enable the syntax highlight again. I have to manually press C-L to refresh and get it back.
