### ISSUE TITLE
:oldfiles is broken after file open and wviminfo and rviminfo!

### ISSUE THREAD

**Issue by Shougo** [vim/vim#1781]
It is intended behavior?

Reproduce ways:

* `$ vim -Nu NONE`: Launch new Vim.

* `:oldfiles`: You can see some files that you have editted.

* `:edit foo`: Open some file

* `wviminfo | rviminfo!`: Save and load v:oldfiles

* `:oldfiles`: You can see the only one list(`foo`)

* If you restart your Vim, `:oldfiles` works properly.

I have tested it in Vim 8.0.647

**Comment by chemzqm** [comment]
@Shougo looks like that's desired behaviour, see `:h :rv`

**Comment by brammool** [comment]
Shougo wrote:

> It is intended behavior?
> 
> Reproduce ways:
> 
> * `$ vim -u NONE`: Launch new Vim.
> 
> * `:oldfiles`: You can see some files that you have editted.
> 
> * `:edit foo`: Open some file
> 
> * `wviminfo | rviminfo!`: Save and load v:oldfiles
> 
> * `:oldfiles`: You can see the only one list(`foo`)
> 
> * If you restart your Vim, `:oldfiles` works properly.
> 
> I have tested it in Vim 8.0.647

It appears :wviminfo does not store the marks that Vim knows about.
It relies on merging them with an existing file, but here you are
writing a new file.

-- 
hundred-and-one symptoms of being an internet addict:
48. You get a tatoo that says "This body best viewed with Netscape 3.1 or
    higher."

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Shougo** [comment]
> @Shougo looks like that's desired behaviour, see :h :rv

I have read the documentation.  But I don't understand the behavior.

I just want to update `v:oldfiles` without restarting Vim.
What are the right commands?

**Comment by Shougo** [comment]
I and @koron have found the reason.

https://github.com/vim/vim/blob/a853089479b60b829bab1c4a0a737a073415f8a7/src/viminfo.c#L2451

If I remove the `break`, fixes the behavior.

And the `break` is from Vim 8.1.1736.
https://github.com/vim/vim/commit/c3328169d5566b97a6a6921067017e4369dd7cd6#diff-652732b65cd7592110a09573dfb12c2ea79b8a8ed4702449413855b2f68d3d1cR2389

I don't know why the `break` is needed.

**Comment by Shougo** [comment]
Test case:

Below test will fails.  You can test it by `source %`.

```vim
func Test_viminfo_oldfiles()
  let v:oldfiles = []
  let lines = [
	\ '# comment line',
	\ '*encoding=utf-8',
	\ '',
	\ ':h viminfo',
	\ '?/session',
	\ '=myvar',
	\ '@123',
	\ '',
	\ "'E  2  0  /tmp/nothing",
	\ '',
	\ "> /tmp/file_one.txt",
	\ "\t\"\t11\t0",
	\ "",
	\ "> /tmp/file_two.txt",
	\ "\t\"\t11\t0",
	\ "",
	\ "> /tmp/another.txt",
	\ "\t\"\t11\t0",
	\ "",
	\ ]
  call writefile(lines, 'Xviminfo')
  delmark E
  edit /tmp/file_two.txt
  rviminfo! Xviminfo
  call delete('Xviminfo')

  call assert_equal('h viminfo', histget(':'))
  call assert_equal('session', histget('/'))
  call assert_equal('myvar', histget('='))
  call assert_equal('123', histget('@'))
  call assert_equal(2, line("'E"))
  call assert_equal(['1: /tmp/file_one.txt', '2: /tmp/file_two.txt', '3: /tmp/another.txt'], filter(split(execute('oldfiles'), "\n"), {i, v -> v =~ '/tmp/'}))
  call assert_equal(['1: /tmp/file_one.txt', '2: /tmp/file_two.txt'], filter(split(execute('filter file_ oldfiles'), "\n"), {i, v -> v =~ '/tmp/'}))
  call assert_equal(['3: /tmp/another.txt'], filter(split(execute('filter /another/ oldfiles'), "\n"), {i, v -> v =~ '/tmp/'}))
  echomsg v:errors
endfunction

call Test_viminfo_oldfiles()
```

Note: If you execute `rviminfo!` with buffer listed file, it will be broken.

**Comment by Shougo** [comment]
If you remove ` edit /tmp/file_two.txt` line, it will success.

**Comment by koron** [comment]
The problem is `:rviminfo!` will stop to read `oldfiles` (marks) when it includes a same entry with current buffer.

It looks like that be caused by https://github.com/vim/vim/blob/a853089479b60b829bab1c4a0a737a073415f8a7/src/viminfo.c#L2307-L2314 and https://github.com/vim/vim/blob/a853089479b60b829bab1c4a0a737a073415f8a7/src/viminfo.c#L2440-L2451
`load_mark` is set at first block, then it `break` loop to read marks at second block.

**Comment by brammool** [comment]
This break is intentional for when only reading marks for the current buffer.  However, it is also used for ":rviminfo", which probably should not.  This patch should help:
```diff
*** ../src/viminfo.c	2020-09-02 10:25:41.871436944 +0200
--- viminfo.c	2021-02-09 18:58:23.822860182 +0100
***************
*** 3340,3346 ****
  	p_viminfo = (char_u *)"'100";
      if (eap->cmdidx == CMD_rviminfo)
      {
! 	if (read_viminfo(eap->arg, VIF_WANT_INFO | VIF_WANT_MARKS
  				  | (eap->forceit ? VIF_FORCEIT : 0)) == FAIL)
  	    emsg(_("E195: Cannot open viminfo file for reading"));
      }
--- 3340,3346 ----
  	p_viminfo = (char_u *)"'100";
      if (eap->cmdidx == CMD_rviminfo)
      {
! 	if (read_viminfo(eap->arg, VIF_WANT_INFO
  				  | (eap->forceit ? VIF_FORCEIT : 0)) == FAIL)
  	    emsg(_("E195: Cannot open viminfo file for reading"));
      }
```

But then :rviminfo does not update the marks for the current buffer.  I wonder if it should update marks for all loaded buffers.

**Comment by Shougo** [comment]
>  I wonder if it should update marks for all loaded buffers.

I think it is not needed.

**Comment by Shougo** [comment]
Thank you for the fix!
