### ISSUE TITLE
Text Plugins Override Help Options

### ISSUE THREAD

**Issue by joshklod** [vim/vim#1782]
When loading a help file via `:help`, some default options (`'isk'`, `'fdm'`)
can be negated in a plain text filetype plugin.  
These options are hardcoded into Vim (see `prepare_help_buffer()` in
`ex_cmds.c`) and are set when a help file is loaded. They are not set from a
filetype plugin script, and so do not follow the usual hierarchy.

From a quick glance at the source code, it seems the process of loading help
files is a bit contorted:

1. The buffer is opened and hardcoded options are set
2. Normal filetype detection occurs
    - filetypedetect autocommands are triggered
    - The default `filetype.vim` assigns `setf text`
3. FileType autocommands are triggered
    - `ftplugin/text.vim`, etc. are sourced
    - Hardcoded options are overridden by text plugins
4. Modeline sets `ft=help`
5. FileType autocommands are triggered again
    - If `b:undo_ftplugin` is set for text, it is executed
        - Options are reset to their *global* values, not the ones hardcoded
          for help files
    - `ftplugin/help.vim`, etc. are sourced

The issue can be worked around (if compiled with `+quickfix`) with a few lines
at the top of all plain text plugin files:

    if &buftype == "help"
        finish
    endif

Personally, I don't see why Vim help files have to be an exception. If they
were just listed in the default `filetype.vim` file, instead of requiring that
each one set the filetype in a modeline, it would avoid being detected as a
plain text file. And rather than hardcode certain options in the Vim source,
they could just as easily be set from `ftplugin/help.vim`, which is already
used to set other options.  
But I'll leave that up to you brilliant Vim developers.

[bugreport.txt](https://github.com/vim/vim/files/1085253/bugreport.txt)

**Comment by brammool** [comment]
joshklod wrote:

> When loading a help file via `:help`, some default options (`'isk'`, `'fdm'`)
> can be negated in a plain text filetype plugin.  
> These options are hardcoded into Vim (see `prepare_help_buffer()` in
> `ex_cmds.c`) and are set when a help file is loaded. They are not set from a
> filetype plugin script, and so do not follow the usual hierarchy.
> 
> >From a quick glance at the source code, it seems the process of loading help
> files is a bit contorted:
> 
> 1. The buffer is opened and hardcoded options are set
> 2. Normal filetype detection occurs
>     - filetypedetect autocommands are triggered
>     - The default `filetype.vim` assigns `setf text`
> 3. FileType autocommands are triggered
>     - `ftplugin/text.vim`, etc. are sourced
>     - Hardcoded options are overridden by text plugins
> 4. Modeline sets `ft=help`
> 5. FileType autocommands are triggered again
>     - If `b:undo_ftplugin` is set for text, it is executed
>         - Options are reset to their *global* values, not the ones hardcoded
>           for help files
>     - `ftplugin/help.vim`, etc. are sourced
> 
> The issue can be worked around

What is "The issue"?  Can you give an example of what actually goes
wrong?

> (if compiled with `+quickfix`) with a few lines
> at the top of all plain text plugin files:
> 
>     if &buftype == "help"
>         finish
>     endif
> 
> Personally, I don't see why Vim help files have to be an exception. If they
> were just listed in the default `filetype.vim` file, instead of requiring that
> each one set the filetype in a modeline, it would avoid being detected as a
> plain text file. And rather than hardcode certain options in the Vim source,
> they could just as easily be set from `ftplugin/help.vim`, which is already
> used to set other options.  
> But I'll leave that up to you brilliant Vim developers.

-- 
hundred-and-one symptoms of being an internet addict:
49. You never have to deal with busy signals when calling your ISP...because
    you never log off.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by joshklod** [comment]
In my case, I set `iskeyword` from `after/ftplugin/text.vim`. Then I could
no longer jump to some tags in help files, because `iskeyword` had been
reset to the Vim default.

**Comment by chrisbra** [comment]
please give reproducible steps here. I don't understand what your filetype text plugin changes and how this is related to the help buffer.

**Comment by joshklod** [comment]
> please give reproducible steps here. I don't understand what your filetype text plugin changes and how this is related to the help buffer.

It *should* have nothing to do with the help buffer, that's the problem.

### Steps to Reproduce:

1. Demonstrate correct behavior:

       :h options " Note: help.txt sets isk from a modeline, so
                  "       we need to specify a different page
       :set isk?
         iskeyword=!-~,^*,^|,^",192-255

2. Add the following line to `~/.vim/ftplugin/text.vim`:

       setl isk=@,48-57,'

3. Restart Vim
4. Repeat above test--`iskeyword` has now changed

       :h options
       :set isk?
         iskeyword=@,48-57,'

5. Move the cursor to `set-option` and press `CTRL-]`--Vim jumps to the wrong subject

**Comment by brammool** [comment]
joshklod wrote:

> > please give reproducible steps here. I don't understand what your filetype text plugin changes and how this is related to the help buffer.
> 
> It *should* have nothing to do with the help buffer, that's the problem.
> 
> ### Steps to Reproduce:
> 
> 1. Demonstrate correct behavior:
> 
>        :h options " Note: help.txt sets isk from a modeline, so
>                   "       we need to specify a different page
>        :set isk?
>          iskeyword=!-~,^*,^|,^"
> 
> 2. Add the following line to `~/.vim/ftplugin/text.vim`:
> 
>        setl isk=@,48-57,'

You are missing the command to set "b:undo_ftplugin".  But I suppose
that's not uncommon.

It might work to add this line to $VIMRUNTIME/filetype.vim:

	" Vim help file
	au BufNewFile,BufRead $VIMRUNTIME/doc/*.txt	setf help


It still sets the filetype twice, when using the  modeline there should
be a check whether 'filetype' is set to the same value.

-- 
hundred-and-one symptoms of being an internet addict:
54. You start tilting your head sideways to smile. :-)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by joshklod** [comment]
> You are missing the command to set "b:undo_ftplugin".  But I suppose
> that's not uncommon.

My real plugin has this, of course. :)
Note that calling `set isk<` does not solve the problem, because the global value is also incorrect.

**Comment by joshklod** [comment]
> It might work to add this line to $VIMRUNTIME/filetype.vim:
> 
> 	" Vim help file
> 	au BufNewFile,BufRead $VIMRUNTIME/doc/*.txt	setf help

This works for distributed help files, but not for user plugin documentation outside of `$VIMRUNTIME`.
