### ISSUE TITLE
matchparen.vim incorrectly assumes hl id 3 is available

### ISSUE THREAD

**Issue by justinmk** [vim/vim#1785]
Sometimes when moving quickly through some code after saving or swapping buffers, this error occurs:

```
Error detected while processing function <SNR>29_Highlight_Matching_Pair: 
line  140: 
E801: ID already taken: 3
```

In `runtime/plugin/matchparen.vim`, `s:Highlight_Matching_Pair()`  calls `matchdelete(3)` at the start of that function but that is skipped under certain conditions. 

Some other plugin may call `matachadd(..., 3)` or `:3match`, and then matchparen.vim tries to use that hl id anyway.

This could be fixed by storing the next available hl id in `w:paren_hl_on` instead of always using 3, then `matchdelete(w:paren_hl_on)`.

**Comment by jamessan** [comment]
@benjifisher should be notified about this.  I notice there is a [repo](https://github.com/benjifisher/matchit.zip) on GitHub for matchit.

**Comment by k-takata** [comment]
@jamessan 
It is matchit, not matchparen.

**Comment by chrisbra** [comment]
Actually, the current behaviour is documented.  It strongly discourages the use of id 3
` :h matchadd()`

                ...
                message will appear and the match will not be added.  An ID
                is specified as a positive integer (zero excluded).  IDs 1, 2
                and 3 are reserved for :match, :2match and :3match,
                respectively.  

and then later at `:h 3match`

                Just like :match above, but set a separate match.  Thus
                there can be three matches active at the same time.  The match
                with the lowest number has priority if several match at the
                same position.
                The ":3match" command is used by the matchparen plugin.  You
                are suggested to use ":match" for manual matching and
                ":2match" for another plugin.

(just pointing out the obvious, I am not against changing matchparen and taking the next free id.)

**Comment by brammool** [comment]
Right, id 3 is reserved for matchparen, always has been.
Can you find out what the offending plugin is?

**Comment by chrisbra** [comment]
closing. This was an issue with [w0rp/ale plugin](https://github.com/w0rp/ale/issues/539) which has been fixed since then.
