### ISSUE TITLE
sh syntax highlighting bug (complex SH quoting)

### ISSUE THREAD

**Issue by PeterBinney** [vim/vim#1786]
I have a a particularly nasty bit of shell quoting that breaks the highlighting.

The attached (renamed file - sh-syntax.sh renamed to allow upload here) shows the problem.
[sh-syntax.txt](https://github.com/vim/vim/files/1095742/sh-syntax.txt)

I am using the latest GVIM (7.4) and have just updated to no avail to the latest syntax/sh.vim :
" Last Change:		Jun 12, 2017
" Version:		170	ASTRO-ONLY

Please let me know if I should report this anywhere more appropriate.

**Comment by PeterBinney** [comment]
I've worked out a work-around, which is to add a redundant backslash on the line 7 of the attachment.

Changing from:
`s/^\(,title:\)'"'\([^']*\)'$/\1\2/"`
to:
`s/^\(,title:\)'"'\\([^']*\\)'$/\1\2/"`

Hope that helps fix it!

**Comment by lacygoill** [comment]
Fixed by https://github.com/vim/vim/commit/d2855f5454c5c6c5f786b228c5b67757edfefcb1.
