### ISSUE TITLE
Visual-block insert does not support DEL

### ISSUE THREAD

**Issue by jeosadn** [vim/vim#1787]
When inserting in visual block mode, deleting a forward character with DELETE will erase the next character for the first line, but not the ones after.
Is this a bug or intentional behavior?
Example:
```
abcde
abcde
abcde
```
with the cursor on (0,0):
`<C-v>GItest<DEL><ESC>`
yields:
```
testbcde
testabcde
testabcde
```
instead of the expected:
```
testbcde
testbcde
testbcde
```

**Comment by brammool** [comment]
The Visual-block mode insert repeats the insertion, not any other changes.
Maybe there could be another command to record the keystrokes and repeat them on the Visual range.
