### ISSUE TITLE
Vim yank to system clipboard not working

### ISSUE THREAD

**Issue by cjappl** [vim/vim#1798]
Hello,

System details:
Mac Sierra 10.12.5
Vim --version
`
> vim --version                                                                                                        
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 24 2017 12:45:56)                                                     
MacOS X (unix) version                                                                                                 
Included patches: 1-666                                                                                                
Compiled by Homebrew                                                                                                   
Huge version without GUI.  Features included (+) or not (-):                                                           
+acl             +file_in_path    +mouse_sgr       +tag_old_static                                                     
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white                                                      
+autocmd         +float           +mouse_urxvt     -tcl                                                                
-balloon_eval    +folding         +mouse_xterm     +termguicolors                                                      
-browse          -footer          +multi_byte      +terminfo                                                           
++builtin_terms  +fork()          +multi_lang      +termresponse                                                       
+byte_offset     -gettext         -mzscheme        +textobjects                                                        
+channel         -hangul_input    +netbeans_intg   +timers                                                             
+cindent         +iconv           +num64           +title                                                              
-clientserver    +insert_expand   +packages        -toolbar
+clipboard       +job             +path_extra      +user_commands                                                      
+cmdline_compl   +jumplist        +perl            +vertsplit                                                          
+cmdline_hist    +keymap          +persistent_undo +virtualedit                                                        
+cmdline_info    +lambda          +postscript      +visual 
+comments        +langmap         +printer         +visualextra                                                        
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python          +vreplace                                                           
+cscope          +lispindent      -python3         +wildignore                                                         
+cursorbind      +listcmds        +quickfix        +wildmenu                                                           
+cursorshape     +localmap        +reltime         +windows
+dialog_con      -lua             +rightleft       +writebackup                                                        
+diff            +menu            +ruby            -X11    
+digraphs        +mksession       +scrollbind      -xfontset                                                           
-dnd             +modify_fname    +signs           -xim    
-ebcdic          +mouse           +smartindent     -xpm    
+emacs_tags      -mouseshape      +startuptime     -xsmp
+eval            +mouse_dec       +statusline      -xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax
+farsi           +mouse_netterm   +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework Cocoa   -mmacosx-version-min=10.1
2 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.26.0/lib/perl5/5.26.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc -F/usr/local/opt/python/Frameworks -framework Python   -lruby.2.4.1 -lobjc`

Seeing an issue where the command `"*Y` / `"*y` is no longer copying to the system clipboard. I was using this option before I upgraded my operating system from OSX 10.10, but it stopped working after the upgrade.

Through some searching online, I tried adding the line `set clipboard=unnamed` to my .vimrc, but that didn't fix the issue either.

I am happy to provide more details! Thanks for all your hard work.

**Comment by chrisbra** [comment]
Does `"+y` work?

**Comment by cjappl** [comment]
No luck!

**Comment by nuko8** [comment]
@cjappl 

I've just done a clean installation of macOS 10.12.5 on my Mac, and then built and tested Vim 8.0.0684 as follows:
```
$ git clone https://github.com/vim/vim.git
$ cd vim/src
$ ./configure && make test
```
The build was done successfully, and the tests including `testdir/test_quotestar.vim` were all passed. 

After that, I did `$ VIMRUNTIME=../runtime ./vim` on `Terminal.app` and tried yanking and pasting to and fro between that vim instance and another `Terminal.app` instance, and found no issue with that.  Just to make sure, I also examined the content of the system clipboard with `pbcopy` and `pbpaste` and confirmed that data transfer between Vim and the system clipboard had no issue.

So, @cjappl , would you tell us more specifically how you were convinced that "Vim yank to system clipboard not working"?  Since the investigation here was done with the factory default Vim, this could be helpful for you to find out the cause of the yank failure by comparing the build configuration and the runtime settings here with yours.

**Comment by cjappl** [comment]
@nuko8 

Interesting, I am following the same steps and getting the following report. Seems to point exactly to the problem!

```
From test_quotestar.vim:
Found errors in Test_quotestar():
First run:
function RunTheTest[24]..Test_quotestar[6]..Do_test_quotestar_for_macunix line 12: Expected 'text from pasteboard to vim via quotestar' but got ''
function RunTheTest[24]..Test_quotestar[6]..Do_test_quotestar_for_macunix line 19: Expected 'text from vim to pasteboard via quotestar' but got ''
Second run:
function RunTheTest[24]..Test_quotestar[6]..Do_test_quotestar_for_macunix line 12: Expected 'text from pasteboard to vim via quotestar' but got ''
function RunTheTest[24]..Test_quotestar[6]..Do_test_quotestar_for_macunix line 19: Expected 'text from vim to pasteboard via quotestar' but got ''

Test results:
test_eval FAILED

From test_quotestar.vim:
Found errors in Test_quotestar():
First run:
function RunTheTest[24]..Test_quotestar[6]..Do_test_quotestar_for_macunix line 12: Expected 'text from pasteboard to vim via quotestar' but got ''
function RunTheTest[24]..Test_quotestar[6]..Do_test_quotestar_for_macunix line 19: Expected 'text from vim to pasteboard via quotestar' but got ''
Second run:
function RunTheTest[24]..Test_quotestar[6]..Do_test_quotestar_for_macunix line 12: Expected 'text from pasteboard to vim via quotestar' but got ''
function RunTheTest[24]..Test_quotestar[6]..Do_test_quotestar_for_macunix line 19: Expected 'text from vim to pasteboard via quotestar' but got ''
TEST FAILURE
make[1]: *** [report] Error 1
make: *** [scripttests] Error 2

```

Does this mean there is a problem in my vimrc potentially? What can I do to further debug this issue?

I'm not sure, does this VIMRUNTIME respect a .vimrc stored at ~/.vimrc?

**Comment by cjappl** [comment]
As a secondary step, I tried:

`mv ~/.vimrc ~/vimrc`

To "hide" my vimrc, same error occured.

**Comment by nuko8** [comment]
> Does this mean there is a problem in my vimrc potentially?

It rather looks like the problem exists on the system side, too...  On a terminal, what do you have when you run the following sequence of commands?

```
$ echo 'test' | pbcopy && pbpaste
```

Also, I've been a bit concerned about this statement in your first post:

> Seeing an issue where the command "*Y / "*y is no longer copying to the system clipboard. I was using this option before I upgraded my operating system from OSX 10.10, but it stopped working after the upgrade.

Since I've never heard of such an issue, I can't make out exactly what you were talking about and hence don't understand what option you were referring to.  After all, were you able to use "*Y/"*y on 10.10 using "this option"? What was that "this option"?  How did you yank with that?  Anyway, that statement sounds to me that the *-register has already failed to work on your Mac since 10.10, which probably matters much more than "this option"'s stopping working this time.

In conjunction with that, will you try this?: Open Vim and type `:reg *` and press <kbd>return</kbd>.  Then what does Vim say?

> As a secondary step, I tried:
>
> mv ~/.vimrc ~/vimrc
> 
> To "hide" my vimrc, same error occured.

Since the test suite is written not to depend on user settings, the result is anticipated...

**Comment by cjappl** [comment]
Ah, interesting! This seems to be an issue with TMUX. Thanks for helping me discover the problem.

So to answer your question, the echo test wasn't working, which means it was on pbcopy's side of things.

It turns out there is an issue introduced in sierra:
https://github.com/tmux/tmux/issues/543

The solution was to follow the steps in joshuamcginnis's answer. Now it's working perfectly.

Closing, thanks again for the help

**Comment by nuko8** [comment]
Oh, that's it!  Thank you for the nice follow-up.  I should have thought of tmux first but somehow I had been missing it.  Hopefully, this thread could be helpful for those who face the same trouble.

**Comment by cjappl** [comment]
Yep, that was an important piece of the puzzle I didn't even realize!

**Comment by ge** [comment]
On MacOS 12.2 I suddenly cannot yank a line with the Y command or the yy command. I copy and past lines constantly and this is a real pain.

It's been a long time since the above conversation.  Do people think I have to compile vim myself?  It's been a long time since I've done that sort of thing (I'm 79).

**Comment by chrisbra** [comment]
Missing a lot of details. It might be better to ask on the vim-use mailinglist or use vi.stackexchange.com for help on how to setup vim correctly. You need to provide at least the output of `:version` including all compile options (check for `+clipboard`) and say what exactly does not work. Certainly yanking should work by default. You can check using the `:reg` command, whether it worked. If you are talking about the system clipboard and you do have `+clipboard` it may depend on your system and I don't know for MacOS. Also try without any additional complexities like terminal multiplexer (tmux, screen) or ssh sessions first and start with a pristine configuration like using `vim --clean`.
