### ISSUE TITLE
change shift+space to underscore typing

### ISSUE THREAD

**Issue by ohhmm** [vim/vim#1800]
change shift+space to underscore typing
it is currently same as right or l
underscore is widely used in various variables naming
its much easier and faster to type underscore by shift+space with left hand then shift+- with right hand
what do you think?

**Comment by chrisbra** [comment]
I don't think it can be distinguished by Vim (at least in the terminal). Gvim however can distinguish it from space. So you can already do `imap <s-space> _`, no?

**Comment by brammool** [comment]
Either you can already map shift-space or it won't work.

**Comment by mangelozzi** [comment]
Not exactly the same but you can map CTRL+Space to be an underscore with:
```
inoremap <C-SPACE> _
```
