### ISSUE TITLE
Yanking into register could have a better notification message

### ISSUE THREAD

**Issue by kafeltz** [vim/vim#1803]
I suggest when notifying how many lines were yanked, notifying also in what register it was made.

`7yy` says in status: `7 lines yanked`
`"x7yy` say in status: `7 lines yanked` but it could be: `7 lines yanked into register 'x'`

Why this? Because I always have to check `:registers` to make sure it was really yanked in the register because I don't always trust the `"x` prefix in my keyboard.

Note: In Portuguese Keyboard Layout, you must type: `"<space>` because the OS wait the user to input accent, example: `"a` gives you `ä`. Of course I could change the layout to American per application, but it confuses my brain when using other apps.

Well, it just a suggestion.

**Comment by LemonBoy** [comment]
Here's [1] a rough patch implementing this nice suggestion.

[1] https://ptpb.pw/AJJpscgEsOtOus8fZNSl7g_DUDN7

**Comment by LemonBoy** [comment]
The compiler warnings are due to the roughness of the patch heh, I'll send a proper PR soon.

> Also, I think that when no register is specified it should not be
mentioned.

That'd overly complicate the maze of `if` expressions that handle the singular/plural/block/notblock case.

> How about leaving out the quotes?  Using "a would be better:

That's definitely more consistent with how the register names are printed elsewhere.
