### ISSUE TITLE
Can not set gvim as default app to open a file on Windows.

### ISSUE THREAD

**Issue by Yggdroot** [vim/vim#1805]
gvim7.4 can be set as default app to open a file, but gvim8.0 can not.

**Comment by chrisbra** [comment]
what do you mean, it cannot?
I remember there was one problem, if you previously used e.g. vim 7.4 as default app it wasn't possible to set the gvim8 as the new default. Reason was, if I recall correctly, that the path to vim74 was still there somewhere in the registry and one had to fix it manually.

**Comment by Yggdroot** [comment]
Thank you for the explanation. I'll have a try.

**Comment by Yggdroot** [comment]
Fixed, thank you again.

**Comment by vim-ml** [comment]
On 2017-06-30, Christian Brabandt wrote:
> what do you mean, it cannot?
> I remember there was one problem, if you previously used e.g. vim 7.4 as
> default app it wasn't possible to set the gvim8 as the new default. Reason was,
> if I recall correctly, that the path to vim74 was still there somewhere in the
> registry and one had to fix it manually.

I had the same problem when moving from 7.4 to 8.0 on my Windows
7 box at work.  I found a program, Default Programs Editor, that
really helped.  I supposed I could have just used the registry
editor, but editing the registry directly has always scared me.

Regards,
Gary
