### ISSUE TITLE
help file ftplugin broken between 0676 and 0677 [E788: Not allowed to edit another buffer now]

### ISSUE THREAD

**Issue by Snaptags** [vim/vim#1806]
I am using a help.vim ftplugin containing
`wincmd L` 
to open the help in a vertical split

This does not work any more using the most recent patch version 0691, instead vim reports "E788: Not allowed to edit another buffer now".

This happens in a self-compiled version using Windows 10 AND when I copy the gvim.exe to its default location _c:\Program Files (x86)\Vim\vim80\gvim.exe_
My previous version was 0647 and did not have that error.

**Comment by Snaptags** [comment]
Actually 1814183b8 seems to be the commit that broke the help for me.

**Comment by inkarkat** [comment]
There was the same issue with `:resize`; patch 8.0.0688 fixed that one. With `:wincmd`, I fear it's more difficult, because some variants of the command do switch to another window.

**Comment by Snaptags** [comment]
Workaround, in case anyone else has the problem right now:

- delete flplugin/help.vim
- put this in vimrc:
```
augroup vimrc_help
  autocmd!
  autocmd BufEnter *.txt if &buftype == 'help' | wincmd L | endif
augroup END
```

**Comment by mckellyln** [comment]
Perhaps also see comments in https://github.com/vim/vim/pull/1804
