### ISSUE TITLE
ex-mode tab complete do not work when there is a ~/.vimrc in home directory

### ISSUE THREAD

**Issue by hanqing0521** [vim/vim#1814]
# when i run `vim` ex-mode tab does not show a select option only change command.
i try sudo vim it show me a nice feature about ex-mode complete that i can see the complement items and select by arrow keys.
## example 
:sp(tab) -> spelldump -> spellgood ->spellinfo .... but do not show a popup
##  when i delete  `$HOME/.vimrc` everything  is ok
firstly i even make a new linux account, vim work normally, but when i generate a configuration file .vimrc, issure appeared, even .vimrc doesn't add anything.

**Comment by k-takata** [comment]
See `:help defaults.vim`.

> i try sudo vim it show me a nice feature about ex-mode complete that i can see the complement items and select by arrow keys.

This is because the `'wildmenu'` option is set by `defaults.vim`.
