### ISSUE TITLE
matchit: match_words in ftplugin/vb.vim

### ISSUE THREAD

**Issue by rcmosher** [vim/vim#1815]
Matchwords won't work for vb when an "if" has an in-line comment. This is due to the \s*$ at the end of the regex matching "if ... then ...". 
```
let b:match_words=
    \ '\%(^\s*\)\@<=\<if\>.*\<then\>\s*$:\%(^\s*\)\@<=\<else\>:\%(^\s*\)\@<=\<elseif\>:\%(^\s*\)\@<=\<end\>\s\+\<if\>,' .
```

A possible replacement would be the following to allow zero or more comments, if the end-of-line really needs to be matched:
`\s*\%(''.*\)*$`

**Comment by chrisbra** [comment]
did you contact the maintainer of the file?

**Comment by rcmosher** [comment]
Just did.
