### ISSUE TITLE
getchar() documentation is incorrect

### ISSUE THREAD

**Issue by ZyX-I** [vim/vim#1818]
Acorrding to the documentation, `getchar()` returns number if input is “8-bit character”, otherwise it returns string. But actually for e.g. ≠ (U+2260, represented as `"\xE2\x89\xA0"`) it returns number as well and U+2260 by no means is a “8-bit character”. It looks like fix would be just “remove ‘8-bit’ word from the documentation”, yielding text “If it is a character, the result is a number.”.

**Comment by brammool** [comment]
Yes, it is supposed to be "if it is a single character".
I'll change it.
