### ISSUE TITLE
echo message while auto scroll to disappear

### ISSUE THREAD

**Issue by haolongzhangm** [vim/vim#1820]
echo message from plugn: https://github.com/haolongzhangm/auto_update_cscope_ctags_database/blob/master/plugin/auto_update_cscope_ctags.vim     line: 133-135
-------------------------------------------------------------------------------------------------------
        echo "For example, if you just care ARM64 platform code, just need input arm64"
        echo "if input 'normal', means: do not build a especially arch, but we do not suggest at a kernel tree"
        let g:arch_str = input("please input a ARCH: ")
-----------------------------------------------------------------------------------------------------
after a second vim will just show message 'please input a ARCH' 

ps: old vim is ok (will show all message), but after pull vim code, rebuild it , issue happened

**Comment by haolongzhangm** [comment]
ok mesage show screenshot 
![ok](https://user-images.githubusercontent.com/10891471/27845896-a1bd3aa2-6165-11e7-8495-a936d49a65c7.png)


issue message show screenshot
![error](https://user-images.githubusercontent.com/10891471/27845899-a7feec62-6165-11e7-936f-c7e0ca9b59ab.png)

**Comment by chrisbra** [comment]
How to reproduce? What terminal or gui version? Does it happen if you start vim with  `-u NONE -N`?
What is your current Vim version where it happens and in which version did it not happen? Can you bisect the offending commit?

**Comment by chrisbra** [comment]
Do you have a timer running? Can you show the output of `:echo timer_info()`

**Comment by haolongzhangm** [comment]
Dear chrisbra 
1: echo timer_info() 
[{'id': 2, 'repeat': -1, 'remaining': 736, 'time': 4000, 'paused': 0, 'callback': function('Cscope_reset_detect_timer_func')}]

2:both same OS env ,ubuntu 16.04, in my pc , I have two version vim src, the lastest ,which have this issue is : 
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul  5 2017 09:26:23)
包含补丁: 1-692
编译者 zhl@pc
巨型版本 带 GTK2 图形界面。
  可使用(+)与不可使用(-)的功能:
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     +tcl
+balloon_eval    +folding         +mouse_xterm     +termguicolors
+browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
+clientserver    +insert_expand   +packages        +toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python          +vreplace
+cscope          +lispindent      -python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  -lua             +rightleft       +writebackup
+diff            +menu            +ruby            +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      +mouseshape      +startuptime     +xsmp_interact
+eval            +mouse_dec       +statusline      +xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          
+farsi           +mouse_netterm   +tag_binary      

then I build old vim src is ok , which version is : 
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul  5 2017 15:02:13)
包含补丁: 1-147
编译者 zhl@pc
巨型版本 带 GTK2 图形界面。
  可使用(+)与不可使用(-)的功能:
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     +tcl
+balloon_eval    +folding         +mouse_xterm     +termguicolors
+browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
+clientserver    +insert_expand   +packages        +toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python          +vreplace
+cscope          +lispindent      -python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  -lua             +rightleft       +writebackup
+diff            +menu            +ruby            +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      +mouseshape      +startuptime     +xsmp_interact
+eval            +mouse_dec       +statusline      +xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          
+farsi           +mouse_netterm   +tag_binary      


ps  :  I use the same build config : 

./configure  -with-features=huge --enable-rubyinterp --enable-perlinterp=yes --enable-tclinterp=yes --enable-pythoninterp=yes   --with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu/

**Comment by haolongzhangm** [comment]
Dear chrisbra
reproduce step : 
1:plugn vim plugn:   https://github.com/haolongzhangm/auto_update_cscope_ctags_database
2:try to input command :  Createtag   
3:then U will find the echo msg auto scroll off

**Comment by chrisbra** [comment]
Let me guess, if you disable the timer, the redraw issue is gone, right?

**Comment by haolongzhangm** [comment]
Dear  chrisbra 
yes , try add below modify, issue is gone, why old vim do not found this issue, it`s vim-timer issue or plugn wrong use timer API issue ?

diff --git a/plugin/auto_update_cscope_ctags.vim b/plugin/auto_update_cscope_ctags.vim
index 20bb135..b58dfe6 100755
--- a/plugin/auto_update_cscope_ctags.vim
+++ b/plugin/auto_update_cscope_ctags.vim
@@ -762,8 +762,8 @@ function! Cscope_reset_detect_timer_func(cscope_reset_detect_timer_vim)
     call <SID>Auto_update_cscope_ctags(2)
 endfunction
 
-if has('timers')
-    let cscope_reset_detect_timer_vim = timer_start(4000, 'Cscope_reset_detect_timer_func', {'repeat': -1})
-    let g:cscope_reset_detect_timer = cscope_reset_detect_timer_vim
-    let g:vim_has_timers = 1
-endif
+"if has('timers')
+"    let cscope_reset_detect_timer_vim = timer_start(4000, 'Cscope_reset_detect_timer_func', {'repeat': -1})
+"    let g:cscope_reset_detect_timer = cscope_reset_detect_timer_vim
+"    let g:vim_has_timers = 1
+"endif

**Comment by chrisbra** [comment]
There was a patch, that changed redrawing when the Timer was triggered, and the cursor was waiting for the user to input something. But I am not sure which one this was.

**Comment by micbou** [comment]
This is the same issue as https://github.com/vim/vim/issues/1768. The commit in question is https://github.com/vim/vim/commit/29ae377ea7039874337bc79ace9ab2b37b9056e5.

**Comment by haolongzhangm** [comment]
brammool and micbou
yes
try to revert 29ae377 issue is gone!

**Comment by brammool** [comment]
Recent patches fixed this problem.
