### ISSUE TITLE
<C-H> conflicts with <BS> on Windows console version (vim.exe)

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#1823]
Platform: Windows Console
Version: 8.0.636 

After binding `<C-H>` to some function in vim.exe, the functionality of `<BS>` has been changed too.
Then I realize that `<C-h>` and `<BS>` have been treated as the same key in vim.exe ? For example: if I bind
`<C-H>` to the `<Left>`, `<BS>` will become `<LEFT>` too:

```VimL
noremap <c-h> <left>
inoremap <c-h> <left>
```

This is very weird, and never happen in GVim, terminal vim or MacVim but only in windows console vim.

Even if using Vim from a terminal, all the modern terminal emulators (SecureCRT, iTerm2, XShell, Putty) will send `<BS>` as key code ASCII - 127 (CTRL+?) by default, instead of sending vt100's old `^H`.

Can `<BS>` be distinct with `^H` in vim.exe ??

**Comment by chrisbra** [comment]
in ascii `<c-h>` is traditionally the same keycode as backspace, it just happened that you have two different possibilities/keys to generate it. So this is expected.

**Comment by skywind3000** [comment]
@chrisbra `<bs>` is `^H` It's an old story in the vt100.

Now, `<bs>` is ASCII 127 by default in all the terminal emulators, you can verify that in your iTerm or SecureCRT.

Why do they still have the same keycode in windows console ?

**Comment by chrisbra** [comment]
I don't have iTerm and don't even know what SecureCRT is. However in the terminal emulators I use, `<bs>` is the same as `<c-h>`. Now you can of course ask why, but it has always been the case and has worked flawlessly for me. So why bother?

**Comment by skywind3000** [comment]
SecureCRT is a popular terminal software on Windows, just like iTerm on Mac OS X.

I don't know what emulator are you using, I have checked all the emulators I known and came to the 
conclusion that `<BS>` is totally `ASCII 127` (can also be refered as `^?`) by default today:

**XShell's default setting**:

![vim_mapch_1](https://user-images.githubusercontent.com/3035071/27914187-fbf229c6-6294-11e7-8265-dc3415a8d426.png)

**SecureCRT's default setting**:

![vim_mapch_2](https://user-images.githubusercontent.com/3035071/27914306-50875ede-6295-11e7-8420-2e8bf1f946db.png)

**Putty's default setting**:

![vim_mapch_3](https://user-images.githubusercontent.com/3035071/27914316-54e480b0-6295-11e7-99d1-edd6ecb1b034.png)

**Terminal.app's default setting**:

![vim_mapch_4](https://user-images.githubusercontent.com/3035071/27914326-58b2f8e8-6295-11e7-9765-406b668694f6.jpg)

**iTerm's default setting**:

![vim_mapch_5](https://user-images.githubusercontent.com/3035071/27914330-5b9684e4-6295-11e7-9b9a-936e10217a92.png)

I have even tested in gnome-terminal and xterm on ubuntu and found that both of them send `ASCII 127` (`^?`) for `<BS>`.

Both of `<BS>` and `^H` can delete a previous character on all the platforms, but they have different key code, so we can bind `<c-h>` to a new function without modifying the behavior of `<BS>`  in Vim, eg:

```VimL
inoremap <c-h> <left>
inoremap <c-j> <down>
inoremap <c-k> <up>
inoremap <c-l> <right>
```

These key mappings work fine in all the platform except windows console. Because `^H - ASCII 8` and `^? - ASCII 127`  behave exactly the same way -- deleting the previous character, in vim or shell.

If we remap `^H` to something new in vim, we can still use `^?` (modern keycode for `<BS>`) to delete the last character, so remapping `<c-h>` works fine.

But remapping `<c-h>` in windows console will destroy `<BS>`. That definitely matters a lot if you want to remap your `<c-h>`.

Finally, the limitation of VT100 has already gone away today, why are we still confine people to remap their `<c-h>` on windows console ? Can I bind it to something else I like without destroying my `<BS>` on windows console ? just like what I do in GVim or terminal vim.

**Comment by vim-ml** [comment]
2017-07-06 17:37 GMT+03:00 Linwei <vim-dev-github@256bit.org>:

> SecureCRT is a popular terminal software on Windows, just like iTerm on
> Mac OS X.
>
> I don't know what emulator are you using, I have checked all the emulators
> I known and came to the
> conclusion that <BS> is totally ASCII 127 (can also be refered as ^?) by
> default today:
>
> XShell:
> [image: vim_mapch_1]
> <https://user-images.githubusercontent.com/3035071/27914187-fbf229c6-6294-11e7-8265-dc3415a8d426.png>
>
> SecureCRT:
> [image: vim_mapch_2]
> <https://user-images.githubusercontent.com/3035071/27914306-50875ede-6295-11e7-8420-2e8bf1f946db.png>
>
> Putty:
> [image: vim_mapch_3]
> <https://user-images.githubusercontent.com/3035071/27914316-54e480b0-6295-11e7-99d1-edd6ecb1b034.png>
>
> Terminal on Mac OS X:
> [image: vim_mapch_4]
> <https://user-images.githubusercontent.com/3035071/27914326-58b2f8e8-6295-11e7-9765-406b668694f6.jpg>
>
> iTerm on Mac OS X:
> [image: vim_mapch_5]
> <https://user-images.githubusercontent.com/3035071/27914330-5b9684e4-6295-11e7-9b9a-936e10217a92.png>
>
> I have even tested in gnome-terminal and xterm on ubuntu and found that
> both of them send ASCII 127 (^?) for <BS>.
>
> Both of <BS> and ^H can delete a previous character on all the platforms,
> but they have different key code, so we can bind <c-h> to a new function
> without modifying the behavior of <BS> in Vim, eg:
>
> inoremap <c-h> <left>inoremap <c-j> <down>inoremap <c-k> <up>inoremap <c-l> <right>
>
> These key mappings work fine in all the platform except windows console.
> Because ^H - ASCII 8 and ^? - ASCII 127 behave exactly the same way --
> deleting the previous character, in vim or shell.
>
> If we remap ^H to something new in vim, we can still use ^? (modern
> keycode for <BS>) to delete the last character, so remapping <c-h> works
> fine.
>
> But remapping <c-h> in windows console will destroy <BS>.
>
> That definitely matters a lot if you want to remap your <c-h>.
>

What do you want to do, exactly? Controlling what terminal sends is out of
Vim responsibility most of time, not possible sometimes. And as you have
shown above what <BS> sends is a *setting* on most terminals, Vim would not
adjust even those ​terminals’ settings you mentioned for various reasons,
starting from “it is hard to impossible (latter over ssh) to determine
which terminal emulator is being used” (not the case for Windows console),
proceeding to “adjusting such setting may mean breaking other applications,
so just assume user knows how to configure his terminal”.

**Comment by skywind3000** [comment]
> Controlling what terminal sends is out of Vim responsibility most of time, not possible sometimes.

I can control the terminal emulator to send `<BS>` as `^?`, for the purpose of remapping `<c-h>` to something new in vim, and after the remapping I can still use `<BS>` to delete last character.

In short:

**All the other platforms**
If I remap `<c-h>` to `<left>`, my `<BS>` is not changed, I can still use `<BS>` to delete last character.

**Windows console (vim.exe):**
If I remap `<c-h>` to `<left>`, my `<BS>` become `<left>` too. I **can't** use my `<bs>` to delete last character now.

And `<BS>` and `<c-h>` is totally under Vim's control on windows console. And confusing these two keys on windows is exactly Vim's responsibility .

The limitation of VT100 has already gone away today, why are we still confine people to remap their `<c-h>` on windows console ? Can I bind it to something else I like without destroying my `<BS>` on windows console ? just like what I do in GVim or terminal vim.

**Comment by vim-ml** [comment]
2017-07-06 18:02 GMT+03:00 Linwei <vim-dev-github@256bit.org>:
> Controlling what terminal sends is out of Vim responsibility most of time,
> not possible sometimes.
>
> I can control the terminal emulator to send <BS> as ^?, for the purpose of
> remapping <c-h> to something new in vim, and after the remapping I can still
> use <BS> to delete last character.
>
> In short:
>
> All the other platforms
> If I remap <c-h> to <left>, my <BS> is not changed, I can still use <BS> to
> delete last character.
>
> Windows console (vim.exe):
> If I remap <c-h> to <left>, my <BS> become <left> too. I can't use my <bs>
> to delete last character now.
>
> And <BS> and <c-h> is totally under Vim's control on windows console. And
> confusing these two keys on windows is exactly Vim's responsibility .

`vim.exe` does not have any embedded terminal emulator, it uses
system’s so it is not a Vim’s responsibitily unless you want to tell
(with MSDN link) that there actually *is* a way to do what you
request.

In any case I would suggest to just install cygwin and use Vim from there.

**Comment by skywind3000** [comment]
Definitely, I can tell the difference of `Control + H` and `BackSpace` on Windows easily:
I even wrote a test to demostrate that:

```C
#include <windows.h>
#include <stdio.h>

int main(void)
{
    while ((GetKeyState(VK_ESCAPE) & 0x8000) == 0) {
        int keycode;
        printf("Key Down: ");

        if (GetKeyState(VK_LCONTROL) & 0x8000) printf("<Ctrl-L> ");
        if (GetKeyState(VK_RCONTROL) & 0x8000) printf("<Ctrl-R> ");
        if (GetKeyState(VK_LSHIFT) & 0x8000) printf("<SHIFT-L> ");
        if (GetKeyState(VK_RSHIFT) & 0x8000) printf("<SHIFT-R> ");
        if (GetKeyState(VK_SPACE) & 0x8000) printf("<SPACE> ");
        if (GetKeyState(VK_BACK) & 0x8000) printf("<BS> ");

        for (keycode = 0x21; keycode < 127; keycode++) {
            if (GetKeyState(keycode) & 0x8000) {
                printf("%c ", (char)keycode);
            }
        }
        printf("\n");
        fflush(stdout);

        Sleep(100);
    }

    printf("\n");

    return 0;
}
```

Try to press `Control+H` and `BackSpace` in this demo, they have completely different key codes on windows.

You can use the Win32 APIs below or Win32 Messages to check that:

[GetKeyState](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646301(v=vs.85).aspx)
[GetAsyncKeyState](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646293(v=vs.85).aspx)
[GetKeyboardState](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646299(v=vs.85).aspx)
[GetMessage](https://msdn.microsoft.com/en-us/library/windows/desktop/ms644936(v=vs.85).aspx)

`vim.exe` does not need a embedded terminal emulator on windows, totally different mechanism,
from these APIs above, `vim.exe` can easily tell the difference of `Control+H` and `BackSpace`.
But `vim.exe` still confuse them.

That's why I said "it's vim's responsibility".

**Comment by chrisbra** [comment]
so, how about a patch then?

**Comment by skywind3000** [comment]
OK, talk is cheap, I am going to work on it, let me figure out how to build a vim.exe at first.

**Comment by skywind3000** [comment]
And the patch is ready, as simply as possible, just two lines:

```diff
diff --git a/src/os_win32.c b/src/os_win32.c
index f2fd808e9..323bdcd7c 100644
--- a/src/os_win32.c
+++ b/src/os_win32.c
@@ -807,6 +807,7 @@ static const struct
     { VK_NEXT,	TRUE,	'Q',	'\322',	'v',	    '\323', }, /*PgDn*/
     { VK_INSERT,TRUE,	'R',	'\324',	'\325',	    '\326', },
     { VK_DELETE,TRUE,	'S',	'\327',	'\330',	    '\331', },
+    { VK_BACK, TRUE,	'\x7f',	0,	0,	    0, },
 
     { VK_SNAPSHOT,TRUE,	0,	0,	0,	    'r', }, /*PrtScrn*/
 
diff --git a/src/term.c b/src/term.c
index 989d6b7af..ffc15b506 100644
--- a/src/term.c
+++ b/src/term.c
@@ -633,6 +633,7 @@ static struct builtin_term builtin_termcaps[] =
     {K_K7,		"\316\366"},
     {K_K8,		"\316\372"},
     {K_K9,		"\316\376"},
+    {K_BS,		"\316\x7f"},
 # endif
 
 # if defined(VMS) || defined(ALL_BUILTIN_TCAPS)
```

https://gist.github.com/skywind3000/4efdb6975821b180310174a2e7dc9581

And I can remap `<C-h>` now in the console vim.exe, @brammool , would you please include 
this patch in the feature version ??

**Comment by skywind3000** [comment]
@chrisbra, you suggested me to write this patch, I spent a lot of time reading term.c, and tried to fix it with minimal modification. At last, only two lines were inserted.

But do you know why it hasn't been adopted yet ? what's wrong with that ?

**Comment by chrisbra** [comment]
Yes and writing patches is appreciated. However I am not in the position to merge it. I think your patch is in the todo list, you just need to be patient. Also see the tips mentioned here:
https://vim.sourceforge.io/mercurial.php

**Comment by k-takata** [comment]
I close this, because you created the PR #1833.
