### ISSUE TITLE
Are blowfish2 encrypted vim files supposed to be compatible with bcrypt 1.1?

### ISSUE THREAD

**Issue by wsanders** [vim/vim#1825]
I appears I can't decrypt blowfish2-encrypted file with bcrypt 1.1 (the ancient version at http://bcrypt.sourceforge.net/) not can I open bcrypt-1.1-encoded files with vim.

This is my "VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr  4 2017 18:14:54)" that is packaged with MacOS Sierra.

Is this the expected behavior?
Thanks,
-w

**Comment by brammool** [comment]
W Sanders wrote:

> I appears I can't decrypt blowfish2-encrypted file with bcrypt 1.1
> (the ancient version at http://bcrypt.sourceforge.net/) not can I open
> bcrypt-1.1-encoded files with vim.
> 
> This is my "VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr  4 2017
> 18:14:54)" that is packaged with MacOS Sierra.
> 
> Is this the expected behavior?

Files encrypted by Vim can only be decrypted by Vim.
I'm making sure all files ever encrypted can still be decrypted, thus it
should work with any new version of Vim.

Files encrypted with other tools can only be opened by reading the file
through a filter (making sure not to use a temp file for the output).

-- 
Two percent of zero is almost nothing.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
