### ISSUE TITLE
E518: "nos" and "noswapfile"

### ISSUE THREAD

**Issue by Chinggis6** [vim/vim#1826]
`:help nos` says nos[wapfile]

but `set nos` issues E518:

    E518: Unknown option: nos

rendering the option shorthandless and having to fully set as `noswapfile`.

The short option is useful for the following one-liner if you don't like/want additional files:

    set nobk nowb nos " nobackup nowritebackup noswapfile

Is it a bug?

---

Version 8.0.586 on Arch Linux

---

Update:

The option was `noswf`.

**Comment by jamessan** [comment]
You're reading the help for the _command_ `:nos[wapfile]`.  `:nos` works just fine.

**Comment by vim-ml** [comment]
2017-07-08 20:40 GMT+03:00 Chinggis Tenger <vim-dev-github@256bit.org>:
> :help nos says nos[wapfile]
>
> but set nos issues E518:
>
> E518: Unknown option: nos
>
> rendering the option shorthandless and having to fully set as noswapfile.


:nos is a *command*. Options are almost never abbreviated as
nos\%[wapfile], they have two alternatives: long and short. When
checking options help do use quotes: `:h 'nos<Tab>` will not lead you
to non-existent `:h 'nos'`.
