### ISSUE TITLE
maparg() ignores composing characters in rhs

### ISSUE THREAD

**Issue by ZyX-I** [vim/vim#1827]
Given vim-8.0.698 consider the following script:

```
vim -u NONE -i NONE -N --cmd $'map x y\u0301' --cmd 'echo maparg("x")' --cmd cq
```

. It is expected to print “ý” (LATIN SMALL LETTER Y with U+0301 COMBINING ACUTE ACCENT), but instead it prints only “y” (LATIN SMALL LETTER Y). The reason is that `mb_ptr2len` used in `str2special` gives length of the whole cluster (base character + all combining characters), but `mb_ptr2char` used below only takes one character. There should also be something else because just replacing that with `utf_ptr2len` in neovim/neovim#6947 led to neovim/neovim#6985 (i.e. a crash when calling maparg()).

**Comment by ZyX-I** [comment]
Looks like “something else” is just an error when I was renaming variables when refactoring mb_unescape. Should not touch Vim because I did not refactor it.

**Comment by zeertzjq** [comment]
This issue seems no longer reproducible after patch 8.2.4924, although there may still be a underlying bug.

**Comment by chrisbra** [comment]
closing then
