### ISSUE TITLE
findfile() returns invalid path

### ISSUE THREAD

**Issue by mhinz** [vim/vim#1832]
**The problem:**

```vim
:echo findfile('foo', '://')
```

I would expect this to return an empty string, but it's `://foo` instead.

**Use case:**

I found this when I used netrw to edit a HTTP resource and an autocmd ran on `BufRead` that tried to source the invalid path returned by `findfile()`.

The code could use `filereadable()` to check the validity, but I think `findfile()` should only return valid paths in the first place.

**Comment by brammool** [comment]
When the file name looks like a URL, then Vim assumes it's remote and it cannot check if it exists.

**Comment by mhinz** [comment]
But is there any use case to ever return an URL? I mean, without prior knowledge, I'd assume a function called `findfile()` to always return a valid path.

Maybe something like this:

```diff
diff --git i/src/misc2.c w/src/misc2.c
index 7014e1648..90c786600 100644
--- i/src/misc2.c
+++ w/src/misc2.c
@@ -4837,2 +4837,5 @@ vim_findfile(void *search_ctx_arg)
-                               if (!path_with_url(file_path))
-                                   simplify_filename(file_path);
+                               if (path_with_url(file_path)) {
+                                   *file_path = NUL;
+                                   return file_path;
+                               }
+                               simplify_filename(file_path);
```

**Comment by mhinz** [comment]
> When the file name looks like a URL, then Vim assumes it's remote and it cannot check if it exists.

@brammool I'm not sure I understand. Do you mean that Vim somewhere relies on the current behaviour that I want to change? Is anything speaking against the patch?

**Comment by brammool** [comment]
Marco Hinz wrote:

> > When the file name looks like a URL, then Vim assumes it's remote
> > and it cannot check if it exists.
> 
> I'm not sure I understand. Do you mean that Vim somewhere relies on
> the current behaviour that I want to change? Is anything speaking
> against the patch?

The current behavior is that findfile() expands URLs as if they always
exist.  Changing that might cause trouble, it was intentionally made
this way.


-- 
Mrs Abbott: I'm a paediatrician.
     Basil: Feet?
Mrs Abbott: Children.
     Sybil: Oh, Basil!
     Basil: Well, children have feet, don't they? That's how they move
            around, my dear. You must take a look next time, it's most
            interesting.                               (Fawlty Towers)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mhinz** [comment]
Okay, I guess the benefit doesn't outweigh the cost in this case. Closing.
