### ISSUE TITLE
Increase b:changedtick for changes to quickfix / location list windows

### ISSUE THREAD

**Issue by blueyed** [vim/vim#1838]
Using `:laddexpr` or calling `setloclist()` should increase `b:changedtick` for the quickfix / location list, if the list was modified.

This way it could be used to invalidate a cache etc.

**Comment by vim-ml** [comment]
Hi,

On Wed, Jul 12, 2017 at 11:09 AM, Daniel Hahler
<vim-dev-github@256bit.org> wrote:
> Using :laddexpr or calling setloclist() should increase b:changedtick for
> the quickfix / location list, if the list was modified.
>
> This way it could be used to invalidate a cache etc.
>

Can you try the attached patch? If there are no issues, I will send out
a patch with tests and doc update.

- Yegappan

diff --git a/src/quickfix.c b/src/quickfix.c
index 3889a9565..76e068044 100644
--- a/src/quickfix.c
+++ b/src/quickfix.c
@@ -3088,6 +3088,7 @@ ex_copen(exarg_T *eap)
      * Fill the buffer with the quickfix list.
      */
     qf_fill_buffer(qi, curbuf, NULL);
+    CHANGEDTICK(curbuf) = 1;
 
     curwin->w_cursor.lnum = qi->qf_lists[qi->qf_curlist].qf_index;
     curwin->w_cursor.col = 0;
@@ -3289,6 +3290,7 @@ qf_update_buffer(qf_info_T *qi, qfline_T *old_last)
 	qf_update_win_titlevar(qi);
 
 	qf_fill_buffer(qi, buf, old_last);
+	++CHANGEDTICK(buf);
 
 	if (old_last == NULL)
 	{

**Comment by lcd047** [comment]
> Using  `:laddexpr`  or calling `setloclist()` should increase `b:changedtick` for the quickfix / location list, if the list was modified.

Sorry, I disagree.  The way I understand it, `b:changedtick` was meant to keep track of undoable changes to the _buffer_, not to the `loclist` / `quickfix` list.  Making `setloclist()` update `b:changedtick` would break at least syntastic, which uses it to avoid unnecessarily running linters if the buffer hasn't changed since the last run.  Perhaps you can do your own bookkeeping based on `b:changedtick` and a `QuickFixCmdPost`?  Trying to manipulate `loclist`s outside the standard stack is already a pain as it is, please don't make it even more so.

**Comment by ZyX-I** [comment]
@lcd047 `b:changedtick` has nothing to do with undo, it is meant to keep track of *changes* to the buffer, without the “undoable” adjective. And if I understand what patch is doing and what @blueyed is suggesting then it increases `b:changedtick` *for the buffer which shows the quickfix/location list*, not for a buffer which happened to be current when `:laddexpr` was run. If syntastic has any problems with this (I really doubt so) it is utterly broken.

**Comment by lcd047** [comment]
> `b:changedtick` has nothing to do with undo

Whatever.  What I said stands regardless.

> And if I understand what patch is doing and what @blueyed is suggesting then it increases `b:changedtick` _for the buffer which shows the quickfix/location list_, not for a buffer which happened to be current when `:laddexpr` was run.

Apples and oranges.  I don't particularly care about `:laddexpr`.  I have a problem with changing `b:changedtick` from `setloclist()`, particularly because there is currently no way to parse errors with `errorformat` while leaving the `loclist` stack alone.  I need to do that because I need to munge the resulting `loclist` before showing it to the user.  `setloclist()` needs to be called before displaying the final `loclist`.  It can be called multiple times, because the user may decide to close the error window, then re-open it (I'm simplifying here; there's a messy bookkeeping involved to work around various unwanted interactions between `autocmd`s).  Calling `setloclist()` shouldn't ever imply a buffer has changed.

> If syntastic has any problems with this (I really doubt so) it is utterly broken.

Oh, there's nothing quite like the smell of an arrogant blanket statement like this in the morning.

**Comment by vim-ml** [comment]
Hi,

On Wed, Jul 12, 2017 at 9:45 PM, LCD 047 <vim-dev-github@256bit.org> wrote:
> Using :laddexpr or calling setloclist() should increase b:changedtick for
> the quickfix / location list, if the list was modified.
>
> Sorry, I disagree. The way I understand it, b:changedtick was meant to keep
> track of undoable changed to the buffer, not to the loclist / quickfix list.
>

If the buffer displayed in the quickfix/loclist window is changed, then
the b:changedtick variable is updated.  This behavior seems logical
as the buffer contents are changed. Note that this changes only the
b:changedtick variable of the buffer displayed in the quickfix/loclist
window and not for any other buffer displayed in other windows.

If you close the quickfix window and reopen it, then the b:changedtick
variable will be reset.

>
> Making setloclist() update b:changedtick would break at least syntastic,
> which uses it to avoid unnecessarily running linters if the buffer hasn't
> changed since the last run.
>

I am assuming that the syntastic plugin checks the b:changedtick
variable for the non-quickfix buffers. So this change should not
affect the syntastic plugin.

- Yegappan

>
> Perhaps you can do your own bookkeeping based on
> b:changedtick and a QuickFixCmdPost? Trying to manipulate loclists outside
> the standard stack is already a pain as it is, please don't make it even
> more so.
>

**Comment by lcd047** [comment]
> Note that this changes only the b:changedtick variable of the buffer displayed in the quickfix/loclist window and not for any other buffer displayed in other windows.

Ah, I missed that, sorry.  But then `b:changedtick` for this buffer seems to be the wrong thing to monitor for detecting `loclist` changes, because:

> If you close the quickfix window and reopen it, then the b:changedtick variable will be reset.

So you can potentially get both false negatives and false positives.

**Comment by vim-ml** [comment]
Hi,

On Wed, Jul 12, 2017 at 11:29 PM, LCD 047 <vim-dev-github@256bit.org> wrote:
>> Note that this changes only the b:changedtick variable of the buffer
>> displayed in the quickfix/loclist window and not for any other buffer
>> displayed in other windows.
>
> Ah, I missed that, sorry. But then b:changedtick for this buffer seems to be
> the wrong thing to monitor for detecting loclist changes, because:
>
>> If you close the quickfix window and reopen it, then the b:changedtick
>> variable will be reset.
>
> So you can potentially get both false negatives and false positives.
>

The b:changedtick variable for the quickfix buffer indicates how many
times the buffer has been changed/updated after it was displayed in
the quickfix window. For example, after executing the following series
of commands:

     cexpr ""
     cexpr ""
     cexpr ""
     copen
     colder
     colder
     cnewer
     cnewer

The b:changedtick variable will be set to 6. In the above case the
quickfix list itself is not changing, only the buffer showing the quickifx
list is getting updated.

- Yegappan

**Comment by blueyed** [comment]
Thank you, Yegappan.

My use case is displaying info in the statusline, e.g. the count of items - and I've noticed that it makes sense to cache it, since `getloclist()` seems to be rather slow on large (2k items) lists.

There should probably be a better way, e.g. an API to get just the count of items (instead of using `len(getloclist(0))`, but this simple patch is good to have already.

**Comment by lcd047** [comment]
> There should probably be a better way, e.g. an API to get just the count of items (instead of using `len(getloclist(0))`, but this simple patch is good to have already.

Or just add functions that work on `loclist`s in memory, detached from the stack, and use the stack only when you need to show said `loclist`s in a window.  Then `len(getloclist(0))` becomes `len(loclist)`.

**Comment by blueyed** [comment]
@lcd047 
Agreed, but that is considered to be a separate issue - managing b:changedtick still makes sense.

**Comment by vim-ml** [comment]
Hi all,

On Thu, Jul 13, 2017 at 7:30 AM, Daniel Hahler
<vim-dev-github@256bit.org> wrote:
> Thank you, Yegappan.
>
> My use case is displaying info in the statusline, e.g. the count of items -
> and I've noticed that it makes sense to cache it, since getloclist() seems
> to be rather slow on large (2k items) lists.
>
> There should probably be a better way, e.g. an API to get just the count of
> items (instead of using len(getloclist(0)), but this simple patch is good to
> have already.
>

I am attaching a patch that implements this along with doc update and
a test.

- Yegappan

diff --git a/runtime/doc/quickfix.txt b/runtime/doc/quickfix.txt
index 0ca52aa06..e555451b5 100644
--- a/runtime/doc/quickfix.txt
+++ b/runtime/doc/quickfix.txt
@@ -425,7 +425,9 @@ EXECUTE A COMMAND IN ALL THE BUFFERS IN QUICKFIX OR LOCATION LIST:
 			which will indicate the command that produced the
 			quickfix list. This can be used to compose a custom
 			status line if the value of 'statusline' is adjusted
-			properly.
+			properly. Whenever this buffer is modified by a
+			quickfix command or function, the |b:changedtick|
+			variable is incremented.
 
 							*:lop* *:lopen*
 :lop[en] [height]	Open a window to show the location list for the
diff --git a/src/quickfix.c b/src/quickfix.c
index 3889a9565..320d46ea6 100644
--- a/src/quickfix.c
+++ b/src/quickfix.c
@@ -3289,6 +3289,7 @@ qf_update_buffer(qf_info_T *qi, qfline_T *old_last)
 	qf_update_win_titlevar(qi);
 
 	qf_fill_buffer(qi, buf, old_last);
+	++CHANGEDTICK(buf);
 
 	if (old_last == NULL)
 	{
diff --git a/src/testdir/test_quickfix.vim b/src/testdir/test_quickfix.vim
index b3cc6891a..4dbb64e6e 100644
--- a/src/testdir/test_quickfix.vim
+++ b/src/testdir/test_quickfix.vim
@@ -2263,3 +2263,28 @@ func Test_resize_from_copen()
 	augroup! QF_Test
     endtry
 endfunc
+
+" Tests for the quickfix buffer b:changedtick variable
+func Xchangedtick_tests(cchar)
+  call s:setup_commands(a:cchar)
+
+  new | only
+
+  Xexpr "" | Xexpr "" | Xexpr ""
+
+  Xopen
+  Xolder
+  Xolder
+  Xaddexpr "F1:10:Line10"
+  Xaddexpr "F2:20:Line20"
+  call g:Xsetlist([{"filename":"F3", "lnum":30, "text":"Line30"}], 'a')
+  call g:Xsetlist([], 'f')
+  let cur_count = getbufvar('%', 'changedtick')
+  call assert_equal(8, cur_count)
+  Xclose
+endfunc
+
+func Test_changedtick()
+    call Xchangedtick_tests('c')
+    call Xchangedtick_tests('l')
+endfunc

**Comment by lcd047** [comment]
> managing b:changedtick still makes sense.

I'm not convinced it does.  You're attaching a meaning to something that has no other reason to exist, and it doesn't even solve the problem you're trying to solve in all possible cases.  This looks like a hack at best.  Why is `b:changedtick` better than setting a dirty flag from an `autocmd` on `QuickFixCmdPost` and recomputting the statusline when this flag is set?

**Comment by lcd047** [comment]
> Why is `b:changedtick` better than setting a dirty flag from an `autocmd` on `QuickFixCmdPost` and recomputting the statusline when this flag is set?

Actually `autocmd`s on `QuickFixCmdPost` don't solve the problem either, since loclist commands can be run with `silent`.

Rather than updating `b:changedtick`, perhaps the solution is to add a generation number to loclists and quickfix lists.  This number would be increased by `:laddexpr` and friends, and the user would be able to query it with `getloclist()`.  Unlike `b:changedtick` however, it wouldn't be tied to a buffer.

**Comment by lcd047** [comment]
> Rather than updating `b:changedtick`, perhaps the solution is to add a generation number to loclists and quickfix lists.  This number would be increased by `:laddexpr` and friends, and the user would be able to query it with `getloclist()`.  Unlike `b:changedtick` however, it wouldn't be tied to a buffer.

A better implementation: there would be a global `unsigned long` number, let's call it a generation seed.  Whenever any `loclist` is created or changed the seed would be increased, then it would be copied to the generation number of the changed `loclist`.  `getloclist()` would still retrieve the generation number from the `loclist` (not the seed).

This is better than the previous idea because `loclist`s would be different if and only if their generation numbers are different.  In turn this would have many other uses.

**Comment by chrisbra** [comment]
closed by [8.0.0735](https://github.com/vim/vim/releases/tag/v8.0.0735)
