### ISSUE TITLE
Patch v8.0.0677 breaks wincmd usage in FileType autocommands

### ISSUE THREAD

**Issue by blueyed** [vim/vim#1839]
`wincmd` does not work anymore in a `FileType` autocmd with https://github.com/vim/vim/commit/1814183b865059679f6ee526ec23fc575e536e66.

I am not sure if this is really intentionally?

A test case:

```vim
augroup test
  au!
  autocmd FileType * wincmd p
augroup END

cgetexpr 'init'
copen
```

```
% vim -Nu t-wincmd-in-FileType.vim
Error detected while processing FileType Auto commands for "*":
E788: Not allowed to edit another buffer now
```

I am using `wincmd` in https://github.com/blueyed/vim-qf_resize/ to look at the
windows above the quickfix window.

**Comment by chrisbra** [comment]
You are no longer supposed to change windows or buffers on FileType autocommands, because that has in the past lead to many nasty bugs and segfaults. Therefore this error is now expected.

**Comment by Shougo** [comment]
> I am not sure if this is really intentionally?

I have read the patch and it seems intentional change.
The script cannot change window in FileType autocommand.

**Comment by blueyed** [comment]
Hopefully I can use another auto command then.

**Comment by brammool** [comment]
Daniel Hahler wrote:

> Horsefly I can use another auto command then.

It might work to use the QuickFixCmdPost event and check if &filetype ==
'qf'


-- 
hundred-and-one symptoms of being an internet addict:
150. You find yourself counting emoticons to get to sleep.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by blueyed** [comment]
> It might work to use the QuickFixCmdPost event and check if &filetype == 'qf'

I am interested in appearing quickfix windows.
`BufWinEnter` seems to be affected in the same way: Vim(wincmd):E788: Not allowed to edit another buffer now.
I might use `OptionSet` and check `v:option_new ==# 'quickfix'`, for newer Vims.

1. What about allowing `wincmd` movements still with `noautocmd` (what I am using already), and enforce/check if it returns to the window/buffer after the autocmd (what I am doing already)?

2. After all I am only doing the `wincmd k` dance to get the windows above - so there could be an API to get those more easily instead?

**Comment by vim-ml** [comment]
On Friday, July 14, 2017 at 12:09:42 PM UTC-5, Bram Moolenaar wrote:
> Daniel Hahler wrote:
> 
> 
> 
> > Horsefly I can use another auto command then.
> 
> 
> 
> It might work to use the QuickFixCmdPost event and check if &filetype ==
> 
> 'qf'
> 

Not if you're trying to respond to a ":copen" command.

I have autocmds using window-related commands in a "au Filetype qf" to:

1. detect if it's a location list or a quickfix list (by using :copen and checking if the window changed)
2. resize the quickfix window based on the number of entries

These are currently failing because of this change and I don't think there is a good way to accomplish these things anymore.

**Comment by blueyed** [comment]
That should still be possible if you're no changing windows/buffers?!
Are you doing the same as https://github.com/blueyed/vim-qf_resize/ in this regard then?

Do you have an example test case for your issue(s)?

**Comment by ZyX-I** [comment]
I used to workaround some similar issue by using `feedkeys()`: if you need to do something forbidden, you do not do it just when it is forbidden, but run something like `:call feedkeys("\<Plug>(MyPluginWorkaround)")` where `"<Plug>(MyPluginWorkaround)"` is mapped in all modes to something which will do what you want. If you have a solid idea what mode will it be (note that with e.g. `<C-o><C-w>n` you may switch to another window from insert mode so that you will be in insert mode when it is entered) or you know for sure that any mode other then normal makes no sense in your case then using a mapping proxy is not needed, just do something like `:call feedkeys("\<C-\>\<C-n>:call ForbiddenFunction()\n", 'n')`.

**Comment by vim-ml** [comment]
Ben Fritz wrote:

> On Friday, July 14, 2017 at 12:09:42 PM UTC-5, Bram Moolenaar wrote:
> > Daniel Hahler wrote:
> > 
> > 
> > 
> > > Horsefly I can use another auto command then.
> > 
> > 
> > 
> > It might work to use the QuickFixCmdPost event and check if &filetype ==
> > 
> > 'qf'
> > 
> 
> Not if you're trying to respond to a ":copen" command.
> 
> I have autocmds using window-related commands in a "au Filetype qf" to:
> 
> 1. detect if it's a location list or a quickfix list (by using :copen and checking if the window changed)
> 2. resize the quickfix window based on the number of entries
> 
> These are currently failing because of this change and I don't think there is a good way to accomplish these things anymore.

The resizing should work since 8.0.0688.

If you have remaining problems, please give a reproducible example.

-- 
hundred-and-one symptoms of being an internet addict:
156. You forget your friend's name but not her e-mail address.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
On Saturday, July 15, 2017 at 6:27:27 AM UTC-5, Bram Moolenaar wrote:
> Ben Fritz wrote:
> 
> > On Friday, July 14, 2017 at 12:09:42 PM UTC-5, Bram Moolenaar wrote:
> > > Daniel Hahler wrote:
> > > 
> > > 
> > > 
> > > > Horsefly I can use another auto command then.
> > > 
> > > 
> > > 
> > > It might work to use the QuickFixCmdPost event and check if &filetype ==
> > > 
> > > 'qf'
> > > 
> > 
> > Not if you're trying to respond to a ":copen" command.
> > 
> > I have autocmds using window-related commands in a "au Filetype qf" to:
> > 
> > 1. detect if it's a location list or a quickfix list (by using :copen and checking if the window changed)
> > 2. resize the quickfix window based on the number of entries
> > 
> > These are currently failing because of this change and I don't think there is a good way to accomplish these things anymore.
> 
> The resizing should work since 8.0.0688.
> 
> If you have remaining problems, please give a reproducible example.
> 

For resizing, if I use "exe 'resize' sizevar", it works.

If I use "exe sizevar 'wincmd _'" instead, it does not work, I get "E788: Not allowed to edit another buffer now"

For determining whether a quickfix window is a location list or a quickfix list, is there a different way to do that besides attempting a ":copen" command? I get the same error for that command, even if I'm already in the quickfix list and therefore it doesn't even need to switch buffers.

**Comment by vim-ml** [comment]
Ben Fritz wrote:

> On Saturday, July 15, 2017 at 6:27:27 AM UTC-5, Bram Moolenaar wrote:
> > Ben Fritz wrote:
> > 
> > > On Friday, July 14, 2017 at 12:09:42 PM UTC-5, Bram Moolenaar wrote:
> > > > Daniel Hahler wrote:
> > > > 
> > > > 
> > > > 
> > > > > Horsefly I can use another auto command then.
> > > > 
> > > > 
> > > > 
> > > > It might work to use the QuickFixCmdPost event and check if &filetype ==
> > > > 
> > > > 'qf'
> > > > 
> > > 
> > > Not if you're trying to respond to a ":copen" command.
> > > 
> > > I have autocmds using window-related commands in a "au Filetype qf" to:
> > > 
> > > 1. detect if it's a location list or a quickfix list (by using :copen and checking if the window changed)
> > > 2. resize the quickfix window based on the number of entries
> > > 
> > > These are currently failing because of this change and I don't think there is a good way to accomplish these things anymore.
> > 
> > The resizing should work since 8.0.0688.
> > 
> > If you have remaining problems, please give a reproducible example.
> > 
> 
> For resizing, if I use "exe 'resize' sizevar", it works.
> 
> If I use "exe sizevar 'wincmd _'" instead, it does not work, I get "E788: Not allowed to edit another buffer now"
> 
> For determining whether a quickfix window is a location list or a quickfix list, is there a different way to do that besides attempting a ":copen" command? I get the same error for that command, even if I'm already in the quickfix list and therefore it doesn't even need to switch buffers.

Not sure what you are doing, but this works:

	au FileType qf 20wincmd _


-- 
"The question of whether computers can think is just like the question
of whether submarines can swim."      -- Edsger W. Dijkstra

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
> On Sun, Jul 16, 2017 at 10:08 AM, Bram Moolenaar <Bram@moolenaar.net>
wrote:
> > > >
> > > > The resizing should work since 8.0.0688.
> > > >
> > > > If you have remaining problems, please give a reproducible example.
> > > >
> > >
> > > For resizing, if I use "exe 'resize' sizevar", it works.
> > >
> > > If I use "exe sizevar 'wincmd _'" instead, it does not work, I get
> > > "E788: Not allowed to edit another buffer now"
> > >
> > > For determining whether a quickfix window is a location list or a
> > > quickfix list, is there a different way to do that besides
> > > attempting a ":copen" command? I get the same error for that
> > > command, even if I'm already in the quickfix list and therefore it
> > > doesn't even need to switch buffers.
> >
> > Not sure what you are doing, but this works:
> >
> >         au FileType qf 20wincmd _
> >
> >
>
>
> I tried that exact command in version 8.0.692 and I get an E788
> message, after starting with "gvim -N -u NONE -i NONE" on Windows 7
> (64-bit).
>
> I will try compiling the latest version to see if that helps, but if
> it's fixed, it isn't version 688 that did it.

I build version 8.0.724 and the behavior of "wincmd _" is now fixed, but
I don't see any patch description that seems to apply between 692 and
724. Any ideas which patch actually fixed it? I'm trying to decide
whether I'm curious enough to try a bisect.

**Comment by vim-ml** [comment]
Ben Fritz wrote:

> > On Sun, Jul 16, 2017 at 10:08 AM, Bram Moolenaar <Bram@moolenaar.net>
> wrote:
> > > > >
> > > > > The resizing should work since 8.0.0688.
> > > > >
> > > > > If you have remaining problems, please give a reproducible example.
> > > > >
> > > >
> > > > For resizing, if I use "exe 'resize' sizevar", it works.
> > > >
> > > > If I use "exe sizevar 'wincmd _'" instead, it does not work, I get
> > > > "E788: Not allowed to edit another buffer now"
> > > >
> > > > For determining whether a quickfix window is a location list or a
> > > > quickfix list, is there a different way to do that besides
> > > > attempting a ":copen" command? I get the same error for that
> > > > command, even if I'm already in the quickfix list and therefore it
> > > > doesn't even need to switch buffers.
> > >
> > > Not sure what you are doing, but this works:
> > >
> > >         au FileType qf 20wincmd _
> > >
> > >
> >
> >
> > I tried that exact command in version 8.0.692 and I get an E788
> > message, after starting with "gvim -N -u NONE -i NONE" on Windows 7
> > (64-bit).
> >
> > I will try compiling the latest version to see if that helps, but if
> > it's fixed, it isn't version 688 that did it.
> 
> I build version 8.0.724 and the behavior of "wincmd _" is now fixed, but
> I don't see any patch description that seems to apply between 692 and
> 724. Any ideas which patch actually fixed it? I'm trying to decide
> whether I'm curious enough to try a bisect.

I do think that 8.0.0688 fixed this.  Perhaps the change didn't get
picked up when rebuilding?  ex_cmds.h is included in ex_docmd.c, the
dependency is in Make_cyg_ming.mak and Make_mvc.mak.

-- 
Did you ever see a "Hit any key to continue" message in a music piece?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
On Sunday, July 16, 2017 at 1:53:54 PM UTC-5, Bram Moolenaar wrote:
> Ben Fritz wrote:
> > 
> > I build version 8.0.724 and the behavior of "wincmd _" is now fixed, but
> > I don't see any patch description that seems to apply between 692 and
> > 724. Any ideas which patch actually fixed it? I'm trying to decide
> > whether I'm curious enough to try a bisect.
> 
> I do think that 8.0.0688 fixed this.  Perhaps the change didn't get
> picked up when rebuilding?  ex_cmds.h is included in ex_docmd.c, the
> dependency is in Make_cyg_ming.mak and Make_mvc.mak.
> 

It's not just me, this person saw it in patch 702: https://groups.google.com/d/msg/vim_dev/YBIjU974Zw0/TJd3t-moBgAJ

I'm doing something *very* similar (same function name, even).

**Comment by blueyed** [comment]
@ZyX-I 
Using `feedkeys()` to work around this seems to be not that trivial, and causes flicker - since the qf window gets drawn with a height of 10 already, and only later gets resized.
It also causes issues when being invoked while `i_CTRL-O` is used (it ends it).  Is there some way to detect this btw? (`mode(1)` is `n` for it)

My use case for it is to get information about the window(s) above a given / the current one, and it seems like `wincmd k` is the only way to do so in Vim.
As for Neovim there is `nvim_win_get_position` that can be used to query the screen cell for the window (row/col).
I've looked at `screenrow()` and `winline()`, but it seems to not be very reliable.

The basic problem is that I can just decrement `winnr` to get to previous window(s), but I want to only handle windows above (the ones being affected when resizing the height of the current one).

**Comment by ZyX-I** [comment]
@blueyed Neovim has that function primary because it is needed for Python, and it is needed for Python because I thought this kind of data could be useful. For some reason nobody bothered to create a trivial patch which will create a function doing the equivalent of `pyeval('vim.windows[{number}].row')` (and `….col')`), so if +python or +python3 is available you can use that now, otherwise the only thing I am aware of is that under certain layouts you may successfully guess without moving the cursor using the knowledge that if M > N then window M may only be either to the right of window N, below window N or both. Under other layouts like

```
+-+-+
|1|b|
+-+-+
|c|4|
+-+-+
```

it is impossible though: all windows have equal dimensions, but whether b or c is a second window depends on how exactly you do splitting; screencol()/screenrow() may secure guessing if you are in b or c, but not if you are in 4 or 1.

You may also try to temporary set lazyredraw.

There is also another extremely hacky solution: use `:mksession` to a temporary location and parse session file. Not sure how reliable this would be though.

**Comment by blueyed** [comment]
@ZyX-I 
Thanks for the Python idea / reference - I am trying to avoid this though / it should work without it.

I think I will try something like
1. get the `winheight()` of all windows where the number is lower than the qf one
2. do the resize on the qf window
3. check which windows have changed their height, and revert in case it is != 2

This might happen with something like the following, when the qf window has the full height already.
```
+-+-+
|1|q|
+-+-|
|2+ |
+-+-+

(but would also need a special case for two windows then)

> :mksession

I've looked at `winrestcmd()` already, but that seems to be not easy to parse..

**Comment by blueyed** [comment]
Since this patch also landed in Neovim by now, I've looked into the feedkeys workaround again, but the following appears to be flaky, i.e. it causes random issues, e.g. stuff being pasted/repeated - so it is likely that my mappings are not OK:

```vim
function! s:qf_resize_via_feedkeys() abort
  let win = s:has_win_getid ? win_getid() : winnr()
  call add(s:feedkeys_stack, win)
  call feedkeys("\<Plug>(qf_resize_via_feedkeys)", 't')
endfunction

" Use a stack for the winnr.
let s:feedkeys_stack = []
function! qf_resize#feedkeys_map(mode) abort
  let win = remove(s:feedkeys_stack, 0)
  echom printf('qf_resize#feedkeys_map: %s (mode(1)=%s, pos=%s, win=%d)', a:mode, mode(1), getcurpos(), win)
  call qf_resize#adjust_window_height(win)
endfunction
"
" TODO: incomplete/buggy?
nnoremap <Plug>(qf_resize_via_feedkeys) :<C-U>call qf_resize#feedkeys_map('n')<CR>
inoremap <Plug>(qf_resize_via_feedkeys) <C-\><C-O>:<C-U>call qf_resize#feedkeys_map('i')<CR>
vnoremap <Plug>(qf_resize_via_feedkeys) :<C-U>call qf_resize#feedkeys_map('v')<CR>gv

augroup qf_resize
  au!
  if g:qf_resize_use_feedkeys
    " Workaround: E788: Not allowed to edit another buffer now
    au FileType   qf call s:qf_resize_via_feedkeys()
  endif
augroup END
```

Do the mappings look OK?

**Comment by chrisbra** [comment]
please clearly state what your problem is.

**Comment by blueyed** [comment]
@chrisbra 
My problem is that this patch broke the plugin (vim-qf_resize) and that there is no easy way to work around this for Vim - Neovim has `nvim_win_get_position` at least.

I have now tried the feedkeys approach, but it appears to be buggy.

Therefore the question from my above comment is if the mappings look sane.
This however has been asked in the comment above already, so I cannot say much more.
