### ISSUE TITLE
Seeking Help - Plugin Conflict with Hexmode

### ISSUE THREAD

**Issue by fidian** [vim/vim#1841]
First off, I apologize for my lack of VimScript knowledge. I have adopted a plugin that will allow users to edit files in hex when using `vim -b` and it has the possibility of automatically editing files based on extensions or by detecting high characters in a file. Editing the hex and saving the file will automatically convert the hex back into binary. Pretty useful for data files of various types.

The goal of this issue is to gain further understanding of VimScript and why the plugin is conflicting with gzip. Hopefully people here are smarter than me and can educate me in what I did wrong and how to avoid the issue.

A user of [this plugin](https://github.com/fidian/hexmode) reported [a problem](https://github.com/fidian/hexmode/issues/27) when loading a compressed help file. These compressed help files are automatically excluded from being edited by a check against the filename in my `s:IsBinary` function, which is called on `BufReadPost`.

    au BufReadPost *
        \ let &l:binary = s:IsBinary() |
        \ if &l:binary |
        \   Hexmode |
        \ endif

When editing a compressed help file, the following is displayed in vim:

    Error detected while processing function gzip#read:
    line 44:
    Error: Could not read uncompressed file
    E434: Can't find tag pattern

I can even change `s:IsBinary` to simply do nothing and `return 0` and the problem is still triggered. Commenting out the `BufReadPost` commands allow the file to be loaded and viewed (as text) correctly.

So, my question is revolving around my inability to understand why those commands are triggering problems in the gzip plugin. Can anyone shed some light on my plight?

**Comment by vim-ml** [comment]
On Friday, July 14, 2017 at 7:55:31 AM UTC-5, Tyler Akins wrote:
> First off, I apologize for my lack of VimScript knowledge. I have adopted a plugin that will allow users to edit files in hex when using vim -b and it has the possibility of automatically editing files based on extensions or by detecting high characters in a file. Editing the hex and saving the file will automatically convert the hex back into binary. Pretty useful for data files of various types.
> 
> The goal of this issue is to gain further understanding of VimScript and why the plugin is conflicting with gzip. Hopefully people here are smarter than me and can educate me in what I did wrong and how to avoid the issue.
> 
> A user of this plugin reported [a problem](https://github.com/fidian/hexmode/issues/27] when loading a compressed help file. These compressed help files are automatically excluded from being edited by a check against the filename in my s:IsBinary function, which is called on BufReadPost.
> au BufReadPost *
>     \ let &l:binary = s:IsBinary() |
>     \ if &l:binary |
>     \   Hexmode |
>     \ endif
> 
> 
> When editing a compressed help file, the following is displayed in vim:
> Error detected while processing function gzip#read:
> line 44:
> Error: Could not read uncompressed file
> E434: Can't find tag pattern
> 
> 
> I can even change s:IsBinary to simply do nothing and return 0 and the problem is still triggered. Commenting out the BufReadPost commands allow the file to be loaded and viewed (as text) correctly.
> 
> So, my question is revolving around my inability to understand why those commands are triggering problems in the gzip plugin. Can anyone shed some light on my plight?
> 
> 

Is your Hexmode command defined to allow a | to separate it from another command? I.e. did you use "command -bar Hexmode ..." to define it?

If you did not specify the "-bar" option, then the "| endif" is seen as an argument to the Hexmode command, and your "if" in unclosed. That could in theory prevent other BufReadPost autocmds from doing anything.

**Comment by fidian** [comment]
> Is your Hexmode command defined to allow a | to separate it from another command? I.e. did you use "command -bar Hexmode ..." to define it?

That's very interesting, and I'm glad that I asked. Yes, the command was already defined like how you suggest. https://github.com/fidian/hexmode/blob/master/plugin/hexmode.vim#L21

    command -bar Hexmode call ToggleHex()

Do you have any other suggestions for why this could be misbehaving?

**Comment by vim-ml** [comment]
On Monday, July 17, 2017 at 8:34:39 AM UTC-5, Tyler Akins wrote:
> /quote Is your Hexmode command defined to allow a | to separate it from another command? I.e. did you use "command -bar Hexmode ..." to define it?
> 
> That's very interesting, and I'm glad that I asked. Yes, the command was already defined like how you suggest. https://github.com/fidian/hexmode/blob/master/plugin/hexmode.vim#L21
> command -bar Hexmode call ToggleHex()
> 
> 
> Do you have any other suggestions for why this could be misbehaving?
> 

It looks like $VIMRUNTIME/plugin/gzip.vim sets 'binary' *before* reading files with extension .gz, .bz2, etc. Then a BufReadPost autocmd calls gzip#read().

I assume the code in gzip#read() was written assuming binary is still set, in fact it *may* depend on that fact (speculation).

Either way, your code will turn *off* the 'binary' option to skip HexMode. It will still be off when the gzip plugin goes to read the file.

I suggest modifying your code to not process the files processed by gzip at all. Don't change the 'binary' option for these files but also don't call HexMode. Perhaps add another autocmd to set a flag for the gzip file extension list, or based on the previous value of 'binary'.

**Comment by fidian** [comment]
Thank you for the suggestions and for working with me to find an answer!
