### ISSUE TITLE
Now make new line without a tab?

### ISSUE THREAD

**Issue by gHashTag** [vim/vim#1842]
I click on `o` transfers to a new line with a tab, how to configure to transfer but without the tab?
![vim mov](https://user-images.githubusercontent.com/6774813/28216304-c8d1f4d8-68b9-11e7-8d9e-0502f9e85df5.gif)

**Comment by chrisbra** [comment]
`:set expandtab`. Please note, this is a bug tracker for vim, not for user questions. Use vi.stackexchange.com or use vim_use mailinglist.
