### ISSUE TITLE
Asynchronous code can mess with inputlist

### ISSUE THREAD

**Issue by w0rp** [vim/vim#1843]
This is kind of a strange issue, and it arises out of situations that weren't possible before support for running code asynchronously was available. Because you can now execute VimL code after a delay, it's possible to execute some code that messes with the display of `inputlist()` after `inputlist()` has been executed, and before the user has typed an answer.

You can see the issue arising here: https://github.com/Galooshi/vim-import-js/issues/17

My plugin ALE checks for problems after a short delay, and can display some results after checks have been made, which can come after the `inputlist` prompt is open. After some experimentation, it appears that calling an empty function with `timer_start`, which ticks when the list is open, can move the user's cursor, and could potentially cause other issues.

After a little bit of thinking, I have the following suggestions for improvements to Vim:

1. Prevent whatever causes the cursor to move when a timer function ticks.
2. Re-render the `inputlist` prompt after changes to highlights, signs, or anything which could potentially break it.
3. Consider not displaying the results of `:echo` or `:echomsg` at all while the inputlist prompt is open. We could consider still displaying the results of `:echoerr` or `throw`.

Let me know what you think.

**Comment by brammool** [comment]
An asynchronous callback should never display a message to the user at the command line.  It will interfere with what the user is doing.  You can open a small window to put any status or messages.
I'll fix that the prompt of inputlist() is messed up by the redraw after a callback is invoked.

**Comment by w0rp** [comment]
Cheers, Bram!
