### ISSUE TITLE
job_start's callback doesn't redraw screen properly

### ISSUE THREAD

**Issue by markonm** [vim/vim#1845]
This issue happens on gVim 8 on Windows 10. Second example happens also on cmd's Vim.

## Minimal vimrc
```vim
set guicursor=a:blinkon0

function! Handler(ch, msg) 
  echom a:msg 
endfunction
let job = job_start('cmd /c dir /s/b c:', { 'callback': 'Handler' })
```

To reproduce, run Vim with minimal vimrc in folder with many  (c. 10000) files.

## Examples

1. redraw is blocked after several seconds, I can move cursor to force redraw

![1111](https://user-images.githubusercontent.com/16160229/28251082-18750454-6a76-11e7-8a29-3b5851dd3be6.gif)

2. with cursor blinking enabled, redraw is not blocked but it's delayed
![22222](https://user-images.githubusercontent.com/16160229/28251083-1878d606-6a76-11e7-8c2f-b306f7acc0e9.gif)

3. with timer set to 1 ms, redraw is not blocked at all
![33333](https://user-images.githubusercontent.com/16160229/28251084-187d0532-6a76-11e7-99d0-1f80325e935c.gif)

## Related issues
https://github.com/w0rp/ale/issues/515
https://github.com/roxma/nvim-completion-manager/issues/47

## Version
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 15 2017 22:02:21)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-717
Compiled by appveyor@APPVYR-WIN
Huge version with GUI.  Features included (+) or not (-):
+acl                +ex_extra           +multi_byte_ime/dyn -tag_any_white
+arabic             +extra_search       +multi_lang         +tcl/dyn
+autocmd            +farsi              +mzscheme/dyn       -termguicolors
+balloon_eval       +file_in_path       +netbeans_intg      -terminal
+browse             +find_in_path       +num64              -tgetent
++builtin_terms     +float              +ole                -termresponse
+byte_offset        +folding            +packages           +textobjects
+channel            -footer             +path_extra         +timers
+cindent            +gettext/dyn        +perl/dyn           +title
+clientserver       -hangul_input       +persistent_undo    +toolbar
+clipboard          +iconv/dyn          -postscript         +user_commands
+cmdline_compl      +insert_expand      +printer            +vertsplit
+cmdline_hist       +job                +profile            +virtualedit
+cmdline_info       +jumplist           +python/dyn         +visual
+comments           +keymap             +python3/dyn        +visualextra
+conceal            +lambda             +quickfix           +viminfo
+cryptv             +langmap            +reltime            +vreplace
+cscope             +libcall            +rightleft          +wildignore
+cursorbind         +linebreak          +ruby/dyn           +wildmenu
+cursorshape        +lispindent         +scrollbind         +windows
+dialog_con_gui     +listcmds           +signs              +writebackup
+diff               +localmap           +smartindent        -xfontset
+digraphs           +lua/dyn            +startuptime        -xim
+directx            +menu               +statusline         +xpm_w32
-dnd                +mksession          -sun_workshop       -xterm_save
-ebcdic             +modify_fname       +syntax             
+emacs_tags         +mouse              +tag_binary         
+eval               +mouseshape         +tag_old_static     
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
  system gvimrc file: "$VIM\gvimrc"
    user gvimrc file: "$HOME\_gvimrc"
2nd user gvimrc file: "$HOME\vimfiles\gvimrc"
3rd user gvimrc file: "$VIM\_gvimrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
    system menu file: "$VIMRUNTIME\menu.vim"
Compilation: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL   -DFEAT_XPM_W32   -DWINVER=0x500 -D_WIN32_WINNT=0x500  /Fo.\ObjGXOULYHTRZAMD64/ /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG  /Zl /MT -DFEAT_OLE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DFEAT_MBYTE -DFEAT_GUI_W32 -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl86.dll\" -DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua53.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python35.dll\" -DFEAT_MZSCHEME -I "C:\Program Files\Racket\include" -DMZ_PRECISE_GC -DDYNAMIC_MZSCHEME -DDYNAMIC_MZSCH_DLL=\"libracket3m_a0solc.dll\" -DDYNAMIC_MZGC_DLL=\"libracket3m_a0solc.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl524.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_VER=22 -DDYNAMIC_RUBY_DLL=\"x64-msvcrt-ruby220.dll\" -DFEAT_HUGE /Fd.\ObjGXOULYHTRZAMD64/ /Zi
Linking: link /RELEASE /nologo /subsystem:windows /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib uuid.lib /machine:AMD64 gdi32.lib version.lib   winspool.lib comctl32.lib advapi32.lib shell32.lib  /machine:AMD64 /nodefaultlib libcmt.lib oleaut32.lib user32.lib  /nodefaultlib:lua53.lib  /STACK:8388608  /nodefaultlib:python27.lib /nodefaultlib:python35.lib   "C:\Tcl\lib\tclstub86.lib" WSock32.lib xpm\x64\lib\libXpm.lib /PDB:gvim.pdb -debug
```

**Comment by brammool** [comment]
> This issue happens on gVim 8 on Windows 10. Second example happens also on cmd's Vim.
> 
> ### Minimal vimrc
> ```vim
> set guicursor=a:blinkon0
> 
> function! Handler(ch, msg) 
>   echom a:msg 
> endfunction
> let job = job_start('cmd /c dir /s/b c:', { 'callback': 'Handler' })
> ```

It does not appear to be very useful to flood Vim with messages.  What
are you actually trying to do?


-- 
hundred-and-one symptoms of being an internet addict:
169. You hire a housekeeper for your home page.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by markonm** [comment]
I just wanted to provide easily reproducible steps for the problem. I encountered this bug in plugins. For example, in [ALE ](https://github.com/w0rp/ale/issues/515 )linter messages are delayed for a couple of seconds and in [NCM ](https://github.com/roxma/nvim-completion-manager/issues/47) autocomplete suggestions are also delayed for a couple of seconds if I disable cursor blinking. The same behaviour happens in [Neomake ](https://github.com/neomake/neomake) also.

The problem doesn't happen in VIM on WSL or on Linux.

**Comment by brammool** [comment]
> I just wanted to provide easily reproducible steps for the problem. I encountered this bug in plugins. For example, in [ALE ](https://github.com/w0rp/ale/issues/515 )linter messages are delayed for a couple of seconds and in [NCM ](https://github.com/roxma/nvim-completion-manager/issues/47) autocomplete suggestions are also delayed for a couple of seconds if I disable cursor blinking.

If messages are to be displayed asynchronously, they will interfere with
whatever the user is doing.  This is going to be a problem sooner or
later.  It's much better to open a (small) window to display the
messages there.  That's also a much better way to look back in previous
messages than using :messages (which will mix output of all kinds of
stuff).  E.g. you can search back.

-- 
If Microsoft would build a car...
... Occasionally your car would die on the freeway for no
reason. You would have to pull over to the side of the road,
close all of the car windows, shut it off, restart it, and
reopen the windows before you could continue. For some reason
you would simply accept this.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by markonm** [comment]
I made an issue only because I found it strange that whether cursor is blinking or not is influencing job_start behavior. And it only happens on one platform (Windows). Is this is an intended behavior?

**Comment by l04m33** [comment]
I've seen this behavior too. But it's a plain channel, no job involved. And I'm running Vim on a Linux box.

My plugin used a separate window to display messages from a server. A callback is registered to the channel for appending server messages to that window, but sometimes new messages just stopped showing up, until I move the cursor, or type another command.

My channel callback may also create new windows, but sometimes the new window will not show up until I move the cursor, or type another command.

I don't think it's a big usability issue once you have realized it. But this behavior do incur bad user experience.

**Comment by brammool** [comment]
> I've seen this behavior too. But it's a plain channel, no job
> involved. And I'm running Vim on a Linux box.
> 
> My plugin used a separate window to display messages from a server. A
> callback is registered to the channel for appending server messages to
> that window, but sometimes new messages just stopped showing up, until
> I move the cursor, or type another command.
> 
> My channel callback may also create new windows, but sometimes the new
> window will not show up until I move the cursor, or type another
> command.
> 
> I don't think it's a big usability issue once you have realized it.
> But this behavior do incur bad user experience.

It can happen that Vim is not checking for messages on the channel, or
doesn't find the end of a message.
Any input would then cause exiting the wait and start the loop again,
then the message is found.
It can be difficult to figure out why this happens.  Even using a
debugger might not work, since the code is asynchronous.  Adding ch_log
calls in the code would help, after opening a log file you can see what
happens, and inspect the time stamps.  This does require rebuilding Vim.

-- 
Wizards had always known that the act of observation changed the thing that
was observed, and sometimes forgot that it also changed the observer too.
			Terry Pratchett  -  Interesting times

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by markonm** [comment]
I get the same issue with new `:terminal` command.

## Examples
With cursor blinking disabled
![11](https://user-images.githubusercontent.com/16160229/28852253-28de764a-7728-11e7-9cdc-e9a78b870b39.gif)
With cursor blinking enabled
![22](https://user-images.githubusercontent.com/16160229/28852255-290f88ac-7728-11e7-89b5-6fb385b90b04.gif)

Should I report it separately?

**Comment by mattn** [comment]
@xtal8 it is different issue from this. could you please file new issue?

**Comment by markonm** [comment]
I can't reproduce delays anymore. I'm not sure which patch solved the issue but I'm certain  https://github.com/vim/vim/commit/62426e168ef29fb941d1bd91a112fa09445322a5  fixed the [issue ](https://github.com/w0rp/ale/issues/515) I had with ale.
