### ISSUE TITLE
Powerline statusline loses its colours when `:w` is used

### ISSUE THREAD

**Issue by rst-ack** [vim/vim#1855]
`vim --version` output:
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Included patches: 1-1689
Extra patches: 8.0.0056
```
Using the powerline theme for vim, here is how the theme is called:
```
set rtp+=$HOME/.local/lib/python2.7/site-packages/powerline/bindings/vim/
set laststatus=2
```

Each time I use `:w` to write to a file, my powerline statusline goes from looking like this:
![image](https://user-images.githubusercontent.com/29816026/28464049-ddabd66e-6e66-11e7-89af-9efa9a9713fc.png)

...to looking like this: 
![image](https://user-images.githubusercontent.com/29816026/28464067-f9577080-6e66-11e7-96f3-c037ffa8232f.png)

If I use `so %` to re-source the .vimrc file in the same session, the statusline colours return as normal (until `:w` is used again)

Doing some research, if I use `:verbose set statusline?`, it outputs `statusline=%!py3eval('powerline.statusline(1)')`. Seems like somewhere the powerline theme is calling to set the `statusline` param to `1`, as opposed to the value of `2` like it should be to have it persist. 

I realise this may not be a Vim issue, so please close if necessary (I have also posted this in the powerline issues thread)

**Comment by chrisbra** [comment]
so seems like a powerline issue then.

**Comment by BBagTP** [comment]
I just realised that my `verbose set statusline?` is useless, as it's not investigating the parameter that we're interested in. 
Instead, if I use `verbose set laststatus?`, the output is `Last set from ~/.vimrc`. 

This tells me the issue must be somewhere in my vim config, hence my re-opening of the issue.
