### ISSUE TITLE
man filetype q quits

### ISSUE THREAD

**Issue by dylnmc** [vim/vim#1862]
You cannot `nnoremap q normal! q` when filetype is set to `man`

try it...

1. `vim`

2. `:set ft=man`

3. `q`

_**--OR--**_

1. `vim`

2. `:runtime ftplugin/man.vim`

3. `:Man vim`

4. `q`

---

`:verbose nmap q` yields:

    n  q           *@:q<CR>
            Last set from /usr/share/vim/vim80/ftplugin/man.vim

`q` should not quit, and if it "should," then you should be able to remap it back to `normal! q`

**Comment by ilmoeuro** [comment]
Workaround: can be overridden by setting `no_man_maps` (see `:h no_plugin_maps`, just different option name) before opening man files. The problematic line is https://github.com/vim/vim/blob/master/runtime/ftplugin/man.vim#L36 .

**Comment by dylnmc** [comment]
Yes I just solved this with help of someone on irc (probably you :stuck_out_tongue_closed_eyes:)

Thanks!
