### ISSUE TITLE
'foldcolumn' auto option (like 'signcolumn')

### ISSUE THREAD

**Issue by benknoble** [vim/vim#1866]
**Current behavior**

With `'foldcolumn'` set to a positive integer, display a foldcolumn no matter what.

**Desired behavior**

With `'foldcolumn'` set to `auto`, display a foldcolumn if folds are presents; otherwise, display no foldcolumn.

*Thoughts*

This would of course require Vim to be able to detect if folds are present in a file (based on fold method, or just searching around for them?). There would also need to be a discussion of how *wide* the auto-foldcolumn could be.

*Current workaround*

I found this somewhere, StackOverflow I think, that achieves the result but isn't perfect (I get a Terminal bell on almost all BufLoads because of the way folds are detected).

```vim
" Detects if folds present, sets foldcolumn to 2 if true or 0 if false
" From http://stackoverflow.com/questions/8757168/gvim-automatic-show-foldcolumn-when-there-are-folds-in-a-file
function! HasFolds()
    "Attempt to move between folds, checking line numbers to see if it worked.
    "If it did, there are folds.

    function! HasFoldsInner()
        let origline=line('.')
        :norm zk
        if origline==line('.')
            :norm zj
            if origline==line('.')
                return 0
            else
                return 1
            endif
        else
            return 1
        endif
        return 0
    endfunction

    let l:winview=winsaveview() "save window and cursor position
    let foldsexist=HasFoldsInner()
    if foldsexist
        set foldcolumn=2
    else
        "Move to the end of the current fold and check again in case the
        "cursor was on the sole fold in the file when we checked
        if line('.')!=1
            :norm [z
            :norm k
        else
            :norm ]z
            :norm j
        endif
        let foldsexist=HasFoldsInner()
        if foldsexist
            set foldcolumn=2
        else
            set foldcolumn=0
        endif
    end
    call winrestview(l:winview) "restore window/cursor position
endfunction

" Automatically add foldcolumn if folds present
 au BufWinEnter ?* call HasFolds()
```

**Comment by benknoble** [comment]
I took this and created the plugin [AutoOrigami](https://github.com/benknoble/vim-auto-origami), so I'll close this issue, but I would still have rather seen Vim support this natively.

**Comment by teto** [comment]
available in neovim master https://github.com/neovim/neovim/pull/11716
