### ISSUE TITLE
[terminal] cannot send ^w into terminal

### ISSUE THREAD

**Issue by mattn** [vim/vim#1874]
When start vim on termianl and split window, we can't send Ctrl_w into the vim.

**Comment by mkarpoff** [comment]
This is probably because Ctrl + W is mapped to be the prefix for switching splits. I haven't found a way to us remapping in the vim 8 terminal yet.

**Comment by mattn** [comment]
@mkarpoff Yes, I understand why this caused. I want to discuss people about how to send the prefix key it self into terminal. For example. tmux send prefix-key with double types of prefix-key.

**Comment by mkarpoff** [comment]
Ah I see, sorry for the confusion. In that case it might be also a good idea to talk about how to remap the terminal keys as well while we're at it as I suspect the solution will involve that problem as well.

**Comment by mattn** [comment]
Thanks your suggestion. BTW, I don't use neovim but I heard neovim have tmap/tnoremap? to remap terminal keys.

**Comment by brammool** [comment]
Yasuhiro Matsumoto wrote:

> When start vim on termianl and split window, we can't send Ctrl_w into
> the vim.

Yes, we need something for that. Doubling CTRL-W conflicts with moving
to the next window, which is very common.

Perhap we can use CTRL-W .  With the idea that dot means the current
window (like it means the current line).

Mappings are less important, let's first make most other things work.

-- 
hundred-and-one symptoms of being an internet addict:
250. You've given up the search for the "perfect woman" and instead,
     sit in front of the PC until you're just too tired to care.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
2017-07-25 18:00 GMT+03:00 mattn <vim-dev-github@256bit.org>:
> Thanks your suggestion. BTW, I don't use neovim but I heard neovim have
> tmap/tnoremap? to remap terminal keys.

Neovim has separate terminal mode, with separate commands for mapping
(:tmap/:tnoremap). So `<C-w>`, as well as everything else is sending
input directly to terminal as-is, with `<C-\><C-n>` and `<C-\><C-\>`
being an exceptions for consistency reasons. As expected, if you are
not satisfied with a way to exit terminal mode you just tnoremap
something to `<C-\><C-n>` and tnoremap `<C-\><C-n>` to something if
needed.

**Comment by mgedmin** [comment]
This was fixed in 8.0.0787 (Ctrl-W . sends a ^W).
