### ISSUE TITLE
Search: Unexpected behaviour on repeated patterns

### ISSUE THREAD

**Issue by ghost** [vim/vim#1877]
When searching for a repeated pattern, if the cursor is inside a matched element, the search ignores that element.
I know it's not very clear, so here is how to reproduce this issue:

    vim -N -u NONE
    iNoNoNo<esc>
    0
    /NoNo<CR>

now the cursor is positioned here:

    [N]oNoNo

instead of here:

    No[N]oNo
the search looped around because the first 'No' after the cursor was ignored.

**Comment by brammool** [comment]
Works as intended.   see  :help cpo-c
