### ISSUE TITLE
[Terminal] Cursor in :terminal window is invisible

### ISSUE THREAD

**Issue by bstaletic** [vim/vim#1879]
I tried vim 8.0.0776 `:terminal` and immediately noticed that the cursor is invisible. I tried two terminal emulators ([st](http://st.suckless.org/) and xterm), as well as running in a tty directly. I also tried running inside a tmux pane. And finally with both white and black background in terminal. Result was always the same, cursor was white on white terminal background and black on black background.

There is a point where the cursor becomes visible. After I press `<C-w>` and vim begins to wait for the next key press it displays the cursor properly. Even blinking cursor is working in tty as long as vim is waiting for that second key press.

Here's the output of `:version`:
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 26 2017 00:30:01)
Included patches: 1-776
Compiled by Arch Linux
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminal
++builtin_terms  +fork()          +multi_lang      +terminfo
+byte_offset     +gettext         -mzscheme        +termresponse
+channel         -hangul_input    +netbeans_intg   +textobjects
+cindent         +iconv           +num64           +timers
+clientserver    +insert_expand   +packages        +title
+clipboard       +job             +path_extra      -toolbar
+cmdline_compl   +jumplist        -perl            +user_commands
+cmdline_hist    +keymap          +persistent_undo +vertsplit
+cmdline_info    +lambda          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       -python          +viminfo
+cscope          +lispindent      +python3/dyn     +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      +X11
-dnd             +modify_fname    +signs           +xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      +startuptime     -xpm
+eval            +mouse_dec       +statusline      +xsmp_interact
+ex_extra        +mouse_gpm       -sun_workshop    +xterm_clipboard
+extra_search    -mouse_jsbterm   +syntax          -xterm_save
+farsi           +mouse_netterm   +tag_binary
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim    -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -lncurses -lelf -lnsl   -lacl -lattr -lgpm -ldl
```

Note: It does say `Compiled by Arch Linux`, but this is a custom build I've done.

**Comment by mattn** [comment]
Now @ichizok is working on this.

https://groups.google.com/forum/#!topic/vim_dev/HhczoxAdcWE

@bstaletic Could you please try this patch?

https://gist.github.com/ichizok/9dafd126bb6f6d5f79878a18f5665e6f

**Comment by bstaletic** [comment]
> Could you please try this patch?

Gladly. Give me a few minutes.

**Comment by bstaletic** [comment]
I've done some testing. 

Good news: Cursor is visible

Bad news: If the terminal spawned by `:terminal` opens a tmux pane inside it backspace gets broken.

In case I wasn't clear enough, with this patch cursor is visible but here's how to reproduce the backspace issue:

- Run vim
- `:terminal`
- Run `tmux new-session`
- Write *anything*
- Press backspace

**Comment by mattn** [comment]
@bstaletic Could you please try one more patch?

```diff
diff --git a/src/terminal.c b/src/terminal.c
index 0532d01..3e2412e 100644
--- a/src/terminal.c
+++ b/src/terminal.c
@@ -368,7 +368,7 @@ term_convert_key(int c, char *buf)
        case CAR:               key = VTERM_KEY_ENTER; break;
        case ESC:               key = VTERM_KEY_ESCAPE; break;
                                /* VTERM_KEY_BACKSPACE becomes 0x7f DEL */
-       case K_BS:              c = BS; break;
+       case K_BS:              key = VTERM_KEY_BACKSPACE; break;
        case K_DEL:             key = VTERM_KEY_DEL; break;
        case K_DOWN:            key = VTERM_KEY_DOWN; break;
        case K_END:             key = VTERM_KEY_END; break;
```

**Comment by bstaletic** [comment]
I tried the patch and the immediate issue is resolved, but i didn't have the tme to test it for any possible breakage.

**Comment by bstaletic** [comment]
@mattn I tested the ptch a bit more and it doesn't break anything I tried.

**Comment by mattn** [comment]
@bstaletic thank you!

**Comment by brammool** [comment]
Yasuhiro Matsumoto wrote:

> @bstaletic Could you please try one more patch?
> 
> ```diff
> diff --git a/src/terminal.c b/src/terminal.c
> index 0532d01..3e2412e 100644
> --- a/src/terminal.c
> +++ b/src/terminal.c
> @@ -368,7 +368,7 @@ term_convert_key(int c, char *buf)
>         case CAR:               key = VTERM_KEY_ENTER; break;
>         case ESC:               key = VTERM_KEY_ESCAPE; break;
>                                 /* VTERM_KEY_BACKSPACE becomes 0x7f DEL */
> -       case K_BS:              c = BS; break;
> +       case K_BS:              key = VTERM_KEY_BACKSPACE; break;
>         case K_DEL:             key = VTERM_KEY_DEL; break;
>         case K_DOWN:            key = VTERM_KEY_DOWN; break;
>         case K_END:             key = VTERM_KEY_END; break;
> ```

That is not a solution, as it makes it impossible to send a real
backspace to the job.  Everything is turned into 0x7f (which is Delete).

-- 
hundred-and-one symptoms of being an internet addict:
269. You receive an e-mail from the wife of a deceased president, offering
     to send you twenty million dollar, and you are not even surprised.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mgedmin** [comment]
With current vim 8.0.779 inside a :terminal window both Ctrl-H and Backspace send a ^H, which means programs like `cat` do not interpret it as a backspace.  For the record, `stty -a` shows `erase = ^?` both inside a vim's :terminal, and in a regular gnome-terminal.

With @mattn's patch Ctrl-H correctly sends ^H and Backspace correctly sends a ^? (aka DEL).

I don't have a terminal set up where Backspace normally sends a ^H, so I cannot check whether it would incorrectly convert that ^H to a ^? or not.

Perhaps vim should check `t_kb` and do one thing when it's set to `^H` and a different thing when it's set to `^?`?

**Comment by brammool** [comment]
Marius Gedminas wrote:

> With current vim 8.0.779 inside a :terminal window both Ctrl-H and
> Backspace send a ^H, which means programs like `cat` do not interpret
> it as a backspace.  For the record, `stty -a` shows `erase = ^?` both
> inside a vim's :terminal, and in a regular gnome-terminal.
> 
> With @mattn's patch Ctrl-H correctly sends ^H and Backspace correctly
> sends a ^? (aka DEL).
> 
> I don't have a terminal set up where Backspace normally sends a ^H, so
> I cannot check whether it would incorrectly convert that ^H to a ^? or
> not.
> 
> Perhaps vim should check `t_kb` and do one thing when it's set to `^H`
> and a different thing when it's set to `^?`?

It doesn't depend on Vim but on the command you run.  For me "csh" uses
erase ^H whild bash has ^?.

It's quite stupid that some commands think that the Backspace key sends
a delete character.  Read the label!

If I make the change to have K_BS produce VTERM_KEY_BACKSPACE then in
cat I get ^[[3~, so that doesn't work either.  In fact, in this
situation all three keys produce that.


-- 
Ten bugs in the hand is better than one as yet undetected.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
Cursor problem is fixed, thus this issue can be closed.
I'll look into the erase problem.
