### ISSUE TITLE
The error message of vim.error is not complete.

### ISSUE THREAD

**Issue by Yggdroot** [vim/vim#1887]
If I run the command `:py printfff`, there will be an error message:
```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      NameError: name 'printfff' is not defined
```
I can get the root cause from the message.
But if I run the following commands:
```
:py import vim
:py vim.command("py printfff")
```
the error message is:
```
Error detected while processing :
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      vim.error: Vim(python):Traceback (most recent call last):
```
I think this error messge is not complete, I can not get the root cause from the message.

**Comment by lacygoill** [comment]
Fixed by https://github.com/vim/vim/commit/7f3a28490abb7c495239fc438825e3d1aaafa76d.
