### ISSUE TITLE
:Lex opens twice

### ISSUE THREAD

**Issue by juancolacelli** [vim/vim#1892]
If I don't use any external plugin and I put on top of my vimrc:
```
let g:netrw_liststyle=3
:finish
```

And I execute:
```
vim junk
:Lex
s (in Netrw split)
:Lex
```

Netrw opens twice.

When I try to quit that new buffer (with :q) it says:

> E37: No write since last change
> E162: No write since last change for buffer "NetrwTreeListing 1"

**Comment by chrisbra** [comment]
please verify with the latest netrw version from [Dr. Chips page](http://www.drchip.org/astronaut/vim/#NETRW)

**Comment by bstaletic** [comment]
This was an annoying bug, but I can't reproduce with the latest netrw version.
