### ISSUE TITLE
Signs can be drawn on top of console messages

### ISSUE THREAD

**Issue by w0rp** [vim/vim#1907]
Consider the following scenario.

1. A timer function used used for displaying errors with signs later on.
2. You run a command with `!`, which shows some output.
3. Signs are set while the console output is still open.

When this happens, signs are drawn on top of console output. The bug can be repeated with the following Vim script.

```vim
:call setline(1, range(200))
:sign define SomeError text=x texthl=error linehl=error

:function! ShowSigns(...) abort
    let l:buffer = bufnr('')

    for l:i in range(1, 200)
        let l:sign_code = printf('sign place %d line=%d name=SomeError buffer=%s', l:i, l:i, l:buffer)
        execute l:sign_code
    endfor
endfunction

:call timer_start(1000, 'ShowSigns')
:!echo 'foo'
```

Save the Vim script above as `test.vim`, and run it with `vim -u NONE -s test.vim`, and don't press anything. You will see the output of `echo` from the console, and then the signs will be drawn on top of the console output around a second later.

**Comment by brammool** [comment]
What Vim version are you using?

**Comment by w0rp** [comment]
The above example repeats the bug on my desktop. Here is the top of the `:version` output from my desktop version of Vim.

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 28 2017 11:49:08)
Included patches: 1-313, 315-786
```

My laptop version which I tested this on originally only included patches `1-3`, and that's a version I compiled myself on `Sep 14 2016`.

**Comment by w0rp** [comment]
I'll grab a more recent version with more patches and I'll see if the bug can be repeated with the latest version.

**Comment by w0rp** [comment]
I can confirm that I see the same results with patches `1-826`.

**Comment by chrisbra** [comment]
I can confirm. This patch fixes it:
```
diff --git a/src/screen.c b/src/screen.c
index 648c6d866..b0f0eb74e 100644
--- a/src/screen.c
+++ b/src/screen.c
@@ -996,6 +996,12 @@ update_debug_sign(buf_T *buf, linenr_T lnum)
 # ifdef FEAT_FOLDING
     win_foldinfo.fi_level = 0;
 # endif
+    if (State == ASKMORE || State == HITRETURN)
+    {
+       redraw_win_later(curwin, VALID);
+       return;
+    }
+

     /* update/delete a specific mark */
     FOR_ALL_WINDOWS(wp)
```

**Comment by w0rp** [comment]
It's worth noting that the same issue will likely exist for highlights with `matchaddpos()`.

**Comment by chrisbra** [comment]
i think, a simple return would also work

**Comment by chrisbra** [comment]
I cannot reproduce with a single `:call matchaddpos(..:)` command. However, I think this patch is even better:
```
diff --git a/src/screen.c b/src/screen.c
index 648c6d866..6fe30afeb 100644
--- a/src/screen.c
+++ b/src/screen.c
@@ -1014,7 +1014,7 @@ update_debug_sign(buf_T *buf, linenr_T lnum)
        }
        else
            redraw_win_later(wp, VALID);
-       if (wp->w_redr_type != 0)
+       if (State != ASKMORE && State != HITRETURN && wp->w_redr_type != 0)
            doit = TRUE;
     }
```

**Comment by brammool** [comment]
Christian Brabandt wrote:

> I cannot reproduce with a single `:call matchaddpos(..:)` command.
> However, I think this patch is even better:
> ```
> diff --git a/src/screen.c b/src/screen.c
> index 648c6d866..6fe30afeb 100644
> --- a/src/screen.c
> +++ b/src/screen.c
> @@ -1014,7 +1014,7 @@ update_debug_sign(buf_T *buf, linenr_T lnum)
>         }
>         else
>             redraw_win_later(wp, VALID);
> -       if (wp->w_redr_type != 0)
> +       if (State != ASKMORE && State != HITRETURN && wp->w_redr_type != 0)
>             doit = TRUE;
>      }
> ```

Thanks.  I think we should also check msg_scrolled.

-- 
MORTICIAN:    Bring out your dead!
              [clang]
              Bring out your dead!
              [clang]
              Bring out your dead!
CUSTOMER:     Here's one -- nine pence.
DEAD PERSON:  I'm not dead!
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by w0rp** [comment]
Thanks a bunch. :+1:
