### ISSUE TITLE
Feature request: Terminal env var set to `v:servername`

### ISSUE THREAD

**Issue by jakalope** [vim/vim#1908]
As a simple way to allow vim terminals to communicate with their owners, you could set an environment variable such as `VIM_SERVERNAME` in the terminal's shell when it is created. Then users can open files for editing in alternate buffers from within their vim terminal with a command such as follows.

```
vim --servername $VIM_SERVERNAME --remote some_file.c
```

Then one could write a script that, for example, opens all files listed as the result of a job.

**Comment by brammool** [comment]
jakalope wrote:

> As a simple way to allow vim terminals to communicate with their
> owners, you could set an environment variable such as `VIM_SERVERNAME`
> in the terminal's shell when it is created. Then users can open files
> for editing in alternate buffers from within their vim terminal with a
> command such as follows.
> 
> ```
> vim --servername $VIM_SERVERNAME --remote some_file.c
> ```
> 
> Then one could write a script that, for example, opens all files
> listed as the result of a job.

Interesting idea.  It's simple to implement.  At least for Unix, on
MS-Windows we currently do not pass environment variables.

-- 
Veni, Vidi, Video -- I came, I saw, I taped what I saw.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
