### ISSUE TITLE
[terminal] no CTRL-C/interrupt possible

### ISSUE THREAD

**Issue by leahneukirchen** [vim/vim#1910]
First, thanks for the new terminal mode, it will be very useful.

I noticed CTRL-C doesn't work in :terminal windows, and there was no mention in the TODO, nor explicit sigint handling in terminal.c, so I decided to file an issue.

`stty` says `-brkint`, but merely enabling it doesn't help. Pressing CTRL-C in a terminal buffer will simply print `^C`, but it neither triggers a SIGINT, nor does it end up as input to the pty, so I guess some integration is missing there.

(Same for CTRL-\ and SIGQUIT btw.)

**Comment by mattn** [comment]
What your OS? I don't reproduce it on my Linux and Windows both.

```go
package main

import (
        "fmt"
        "os"
        "os/signal"
)

func main() {
        sc := make(chan os.Signal, 1)
        signal.Notify(sc, os.Interrupt)
        go func() {
                fmt.Println(<-sc)
                os.Exit(1)
        }()
        <-(chan struct{})(nil)
}
```
![fa40315929c65bd6](https://user-images.githubusercontent.com/10111/28830532-f3de69a2-7711-11e7-8ba1-f96be8043ac1.png)

**Comment by leahneukirchen** [comment]
Interesting. I use Void Linux (x86_64 glibc), and vim inside tmux inside mosh.  Let me try some other configurations...

`:term /bin/dash` results in `can't access tty; job control turned off`...

When I run `setsid -c /bin/sh`, the controlling terminal is set and CTRL-C and CTRL-\ work properly.
pty.c seems to use O_NOCTTY for opening the pty, but I think the terminal layer needs to define a controling terminal at some point, so should it use TIOCSCTTY?

`ps -p$$ o tty,comm` confirms a plain `:term /bin/sh` doesn't have a controlling TTY set... what does it print for you?

**Comment by mattn** [comment]
What output from `stty`? If `isig` is not included, SIGINT will be generated by ^C.

**Comment by leahneukirchen** [comment]
`stty` contains `isig` in both cases.

**Comment by leahneukirchen** [comment]
It looks like bash acquires the controlling tty by itself. Can you try executing a different shell? (or /bin/cat directly...)

**Comment by brammool** [comment]
Leаh Neukirchen wrote:

> First, thanks for the new terminal mode, it will be very useful.
> 
> I noticed CTRL-C doesn't work in :terminal windows, and there was no
> mention in the TODO, nor explicit sigint handling in terminal.c, so I
> decided to file an issue.
> 
> `stty` says `-brkint`, but merely enabling it doesn't help. Pressing
> CTRL-C in a terminal buffer will simply print `^C`, but it neither
> triggers a SIGINT, nor does it end up as input to the pty, so I guess
> some integration is missing there.
> 
> (Same for CTRL-\ and SIGQUIT btw.)

It depends on the circumstances.  Running bash appears to work fine,
thus at least Vim is sending the CTRL-C to the job.  But when running a
simple command such as "cat" it doesn't work.

Also need to do something about whether BS or DEL works as the erase
key.

These tty settings are complicated, I hope someone can figure out what
to do to make most commands work.

-- 
GUARD #2:  It could be carried by an African swallow!
GUARD #1:  Oh, yeah, an African swallow maybe, but not a European swallow,
           that's my point.
GUARD #2:  Oh, yeah, I agree with that...
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by leahneukirchen** [comment]
I think a `ioctl(slave_fd, TIOCSCTTY, NULL)` before exec'ing should do it.

**Comment by brammool** [comment]
Leаh Neukirchen wrote:

> I think a `ioctl(slave_fd, TIOCSCTTY, NULL)` before exec'ing should do it.

Thanks, but it's not sufficient to kill ":term cat".
I'll use the code that we already have to send SIGINT.
Seems to work.

-- 
You know you use Vim too much when you have this alias in your
~/.bashrc file: alias :e=/bin/vim             (Eljay Love-Jensen)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
