### ISSUE TITLE
:terminal redraw delayed if cursor blinking is disabled

### ISSUE THREAD

**Issue by markonm** [vim/vim#1915]
After running command inside terminal redraw is sometimes delayed. It can be forced by moving cursor. It happens on Windows 10 with gGvim 8.0.0823

Steps to reproduce:

1. `gvim --clean "+set guicursor=a:blinkon0"`
2.  `:terminal`
3. `vim`

It doesn't happen always, repeat step three until it happens.

## Examples
With cursor blinking disabled
![11](https://user-images.githubusercontent.com/16160229/28852253-28de764a-7728-11e7-9cdc-e9a78b870b39.gif)
With cursor blinking enabled
![22](https://user-images.githubusercontent.com/16160229/28852255-290f88ac-7728-11e7-89b5-6fb385b90b04.gif)

## Version
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 31 2017 20:16:37)
MS-Windows 32-bit GUI version with OLE support
Included patches: 1-823
Compiled by hp@HP-PC
Huge version with GUI.  Features included (+) or not (-):
+acl                +ex_extra           +multi_byte_ime/dyn -tag_any_white
+arabic             +extra_search       +multi_lang         +tcl/dyn
+autocmd            +farsi              +mzscheme/dyn       -termguicolors
+balloon_eval       +file_in_path       +netbeans_intg      +terminal
+browse             +find_in_path       +num64              -tgetent
++builtin_terms     +float              +ole                -termresponse
+byte_offset        +folding            +packages           +textobjects
+channel            -footer             +path_extra         +timers
+cindent            +gettext/dyn        +perl/dyn           +title
+clientserver       -hangul_input       +persistent_undo    +toolbar
+clipboard          +iconv/dyn          -postscript         +user_commands
+cmdline_compl      +insert_expand      +printer            +vertsplit
+cmdline_hist       +job                +profile            +virtualedit
+cmdline_info       +jumplist           +python/dyn         +visual
+comments           +keymap             +python3/dyn        +visualextra
+conceal            +lambda             +quickfix           +viminfo
+cryptv             +langmap            +reltime            +vreplace
+cscope             +libcall            +rightleft          +wildignore
+cursorbind         +linebreak          +ruby/dyn           +wildmenu
+cursorshape        +lispindent         +scrollbind         +windows
+dialog_con_gui     +listcmds           +signs              +writebackup
+diff               +localmap           +smartindent        -xfontset
+digraphs           +lua/dyn            +startuptime        -xim
+directx            +menu               +statusline         +xpm_w32
-dnd                +mksession          -sun_workshop       -xterm_save
-ebcdic             +modify_fname       +syntax             
+emacs_tags         +mouse              +tag_binary         
+eval               +mouseshape         +tag_old_static     
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
  system gvimrc file: "$VIM\gvimrc"
    user gvimrc file: "$HOME\_gvimrc"
2nd user gvimrc file: "$HOME\vimfiles\gvimrc"
3rd user gvimrc file: "$VIM\_gvimrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
    system menu file: "$VIMRUNTIME\menu.vim"
Compilation: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_TERMINAL -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL   -DFEAT_XPM_W32   -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG /arch:IA32 /MD -DFEAT_OLE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DGLOBAL_IME -DFEAT_MBYTE -DFEAT_GUI_W32 -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl86.dll\" -DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua53.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python36.dll\" -DFEAT_MZSCHEME -I "C:\Users\hp\Desktop\racket-x86\include" -DDYNAMIC_MZSCHEME -DDYNAMIC_MZSCH_DLL=\"libracketxxxxxxx.dll\" -DDYNAMIC_MZGC_DLL=\"libmzgcxxxxxxx.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl526.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_VER=24 -DDYNAMIC_RUBY_DLL=\"msvcrt-ruby240.dll\" -DFEAT_HUGE /Fd.\ObjGXOULYHTRZi386/ /Zi
Linking: link /RELEASE /nologo /subsystem:windows /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib uuid.lib /machine:i386 gdi32.lib version.lib   winspool.lib comctl32.lib advapi32.lib shell32.lib  /machine:i386  msvcrt.lib oleaut32.lib user32.lib  /nodefaultlib:lua53.lib  /STACK:8388608  /nodefaultlib:python27.lib /nodefaultlib:python36.lib   "C:\TCL_x86\lib\tclstub86.lib" WSock32.lib .\xpm\x86\lib-vc14\libXpm.lib /PDB:gvim.pdb -debug

```

**Comment by brammool** [comment]
xtal8 wrote:

> After running command inside terminal redraw is sometimes delayed. It
> can be forced by moving cursor. It happens on Windows 10 with gGvim
> 8.0.0823
> 
> Steps to reproduce:
> 
> 1. `gvim --clean "+set guicursor=a:blinkon0"`
> 2.  `:terminal`
> 3. `vim`
> 
> It doesn't happen always, repeat step three until it happens.

Delayed by how much?  In the gif it seems to be quite long, perhaps
related to 'updatetime'?


-- 
    [clop clop]
ARTHUR:  Old woman!
DENNIS:  Man!
ARTHUR:  Man, sorry.  What knight lives in that castle over there?
DENNIS:  I'm thirty seven.
ARTHUR:  What?
DENNIS:  I'm thirty seven -- I'm not old!
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by markonm** [comment]
Delay is about 4 seconds. It is shorter if I reduce `updatetime` and longer if I increase it.

**Comment by brammool** [comment]
xtal8 wrote:

> Delay is about 4 seconds. It is lower if I reduce `updatetime` and
> higher if I increase it.

I suspect the Win32 GUI implementation of gui_mch_wait_for_chars() does
not do the screen update.  It does call parse_queued_messages() though.

-- 
WOMAN:   King of the who?
ARTHUR:  The Britons.
WOMAN:   Who are the Britons?
ARTHUR:  Well, we all are. we're all Britons and I am your king.
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mattn** [comment]
@xtal8 Could you please try to start `vim -u none -N` in the terminal?

**Comment by markonm** [comment]
With `vim -u NONE -N` I can't reproduce entering delay, but exiting delay is still sometimes present.
![44](https://user-images.githubusercontent.com/16160229/28914461-0888776e-783c-11e7-95cd-30f5cd5a4644.gif)

**Comment by markonm** [comment]
After many tries, I've been able to reproduce starting delay also. It happens much less frequently, though.
![55](https://user-images.githubusercontent.com/16160229/28915277-e661c12e-783e-11e7-9e9e-9acc90c2c0fe.gif)

**Comment by brammool** [comment]
Yasuhiro Matsumoto wrote:

> @xtal8 Could you please try to start `vim -u none -N` in the terminal?

With a recent Vim "vim --clean" works better.


-- 
The question is:  What do you do with your life?
The wrong answer is: Become the richest guy in the graveyard.
				(billionaire and Oracle founder Larry Ellison)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
Does this problem still happen?  There were some recent pages to make redrawing work better.

**Comment by markonm** [comment]
I tried 8.0.0871. It's still happening.

**Comment by markonm** [comment]
Now it happens much more frequently if I start vim inside `:terminal` with `--clean` option than without it. With  8.0.0823 it was other way around.

**Comment by mattn** [comment]
@xtal8 Could you please try this patch?

```diff
diff --git a/src/gui_w32.c b/src/gui_w32.c
index 863975c7f..df4abd418 100644
--- a/src/gui_w32.c
+++ b/src/gui_w32.c
@@ -2080,13 +2080,15 @@ gui_mch_wait_for_chars(int wtime)
 
 	    parse_queued_messages();
 
-	    if (pPeekMessage(&msg, NULL, 0, 0, PM_NOREMOVE)
-		|| MsgWaitForMultipleObjects(0, NULL, FALSE, 100, QS_ALLINPUT)
-								!= WAIT_TIMEOUT)
+	    if (pPeekMessage(&msg, NULL, 0, 0, PM_NOREMOVE))
+	    {
+		process_message();
+		break;
+	    } else if (MsgWaitForMultipleObjects(0, NULL, FALSE, 100,
+			QS_ALLINPUT) != WAIT_TIMEOUT)
 		break;
 	}
-#endif
-
+#else
 	/*
 	 * Don't use gui_mch_update() because then we will spin-lock until a
 	 * char arrives, instead we use GetMessage() to hang until an
@@ -2094,6 +2096,7 @@ gui_mch_wait_for_chars(int wtime)
 	 * returning as soon as it contains a single char -- webb
 	 */
 	process_message();
+#endif
 
 	if (input_available())
 	{
```

**Comment by brammool** [comment]
Yasuhiro wrote:

> @xtal8 Could you please try this patch?

This patch only changes the GUI, but I also see a problem in a terminal.
Please check if this change is also needed after including patch 8.0.0924.


-- 
Living on Earth includes an annual free trip around the Sun.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mattn** [comment]
patch 8.0.0924 doesn't fix this issue.

![shoei](https://user-images.githubusercontent.com/10111/29250072-cde7993a-8076-11e7-9207-766ed9495c8c.gif)

The cause of this issue is the calling GetMessage even though PeekMessage return false.

**Comment by brammool** [comment]
Included the patch, looks like it is fixed now.

**Comment by markonm** [comment]
Thank you @mattn, it works great now.
