### ISSUE TITLE
Search becomes very slow with this config

### ISSUE THREAD

**Issue by codable** [vim/vim#1935]
It very strange, config the same thing with the follow line makes search(i.e. type `n` in display mode) very slow.
```vim
nmap nd :!cscope -Rqb<CR>:!ctags -R --c++-kinds=+p --fields=+iaS --extra=+q .<CR>
```
However, with the following configure, it won't slow searching.
```vim
nmap <C-\>m :!cscope -Rqb<CR>:!ctags -R --c++-kinds=+p --fields=+iaS --extra=+q .<CR>
```

**Comment by chrisbra** [comment]
this is a user question. Please use either vim_use mailinglist or vi.stackexchange.com before creating a ticket here. The reason is: you mapped your command to a keycombination what starts with n. So Vim waits to decide, whether more characters are comming or only a single <kbd>n</kbd>
