### ISSUE TITLE
[RFC] unset HOME environment variable when spawn new process on Windows

### ISSUE THREAD

**Issue by mattn** [vim/vim#1946]
Current implementation of Windows version set HOME enviroment variable to USERPROFILE if $HOME is not set on start-up. But there are some applications what doesn't expect this behavior. For example, msys2/cygwin is that. They have own $HOME environment variable and the place of $HOME not same to USERPROFILE. When we want to spawn new process from vim, it make problems. So I suggest to solve this issue.

## 1. don't set HOME

The most desirable fix is this to me.

## 2. unset HOME before spawning new processes.

But this is only when we have not set HOME before starting vim. If we have set HOME before starting vim, it should be passed into the new process.

I want to hear opinions from users and plugin developers.

**Comment by brammool** [comment]
Yasuhiro Matsumoto wrote:

> Current implementation of Windows version set HOME enviroment variable
> to USERPROFILE if $HOME is not set on start-up. But there are some
> applications what doesn't expect this behavior. For example,
> msys2/cygwin is that. They have own $HOME environment variable and the
> place of $HOME not same to USERPROFILE. When we want to spawn new
> process from vim, it make problems. So I suggest to solve this issue.
> 
> ## 1. don't set HOME
> 
> The most desirable fix is this to me.
> 
> ## 2. unset HOME before spawning new processes.
> 
> But this is only when we have not set HOME before starting vim. If we
> have set HOME before starting vim, it should be passed into the new
> process.
> 
> I want to hear opinions from users and plugin developers.

Vim doesn't actually use USERPROFILE, what happens is that when $HOME
has the value "%USERPROFILE%" then it expands the contents.  We do need
to keep doing that to avoid trouble.

If Vim has set $HOME, we could restore it before passing the environment
to an external program.  It should then run just like it would when run
outside of Vim.  We can keep the old value before setting $HOME.
It's probably only in init_homedir().

-- 
My girlfriend told me I should be more affectionate.
So I got TWO girlfriends.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mattn** [comment]
>If Vim has set $HOME, we could restore it before passing the environment to an external program.  It should then run just like it would when run outside of Vim.  We can keep the old value before setting $HOME. It's probably only in init_homedir().

Yes, vim set %HOME% to %USERPROFILE% if user doesn't set %HOME% at init_homedir.

https://github.com/vim/vim/blob/master/src/misc1.c#L3778

This behavior has been implemented long ago, so I don't know why it was implemented like this. But I think that this should be fixed to restore (unset %HOME%) before run external processes.

**Comment by brammool** [comment]
Yasuhiro Matsumoto wrote:

> >If Vim has set $HOME, we could restore it before passing the environment to an external program.  It should then run just like it would when run outside of Vim.  We can keep the old value before setting $HOME. It's probably only in init_homedir().
> 
> Yes, vim set %HOME% to %USERPROFILE% if user doesn't set %HOME% at
> init_homedir.

It doesn't actually do anything with USERPROFILE, it's just that when
$HOME has a value that looks like an unexpanded environment variable, it
expands it.

> https://github.com/vim/vim/blob/master/src/misc1.c#L3778
> 
> This behavior has been implemented long ago, so I don't know why it
> was implemented like this. But I think that this should be fixed to
> restore (unset %HOME%) before run external processes.

Maybe it's actually using $HOMEDRIVE and $HOMEPATH that is the problem?
That is more likely to happen.

-- 
A hamburger walks into a bar, and the bartender says: "I'm sorry,
but we don't serve food here."

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mattn** [comment]
>Maybe it's actually using $HOMEDRIVE and $HOMEPATH that is the problem? That is more likely to happen.

Right, my mistake. However, updating %HOME% is a real problem. Maybe, this is used for expanding `~/`. But this is possible to do with variable instead of environment variable.

**Comment by mattn** [comment]
@brammool So do you think we can remove set `%HOME%` ?

**Comment by brammool** [comment]
Inside Vim $HOME should be present, otherwise things like ~/.vim don't work.
When running a job we could not pass on $HOME if it was generated internally, so that the job gets the environment that Vim got.  I still wonder if that solves more problems than it creates.  e.g. a simple "ls $HOME" would fail, even though ":echo $HOME" works.

**Comment by k-takata** [comment]
Fixed by #2013.
