### ISSUE TITLE
Render artifacts in vte terminals

### ISSUE THREAD

**Issue by sserbin** [vim/vim#1952]
This is somewhat intermittent and appears while scrolling the content. 

Reproducible in gnome-terminal and terminator. 
Looks properly in terminology and xterm (both non-vte)

I was tempted to open a bug against vte but then it seems that it's only vim having this issue (other ncurses-based applications, including nvim, renders properly)

Steps to reproduce:
1. `env | vim -u NONE -`
2. `:colorscheme evening` (just so the vim background is different from terminal one)
3. pgUp/pgDown (somewhat randomly)

Vim version: 
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 25 2017 19:20:34)
Included patches: 1-313, 315-771
```
Vte version: libvte-2.91-0 0.44.2-1ubuntu 0.44.2-1ubuntu
term env var: xterm or xterm-256color

Screenshot - http://i.imgur.com/i086cv9.png

Please let me know if there's any other information I can provide.

**Comment by lacygoill** [comment]
I can't reproduce.  I tested by opening gnome-terminal with this command (from the whisker menu in xfce4):

    gnome-terminal -x bash --norc --noprofile

Then I started Vim with this command:

    env | TERM=xterm-256color vim -u NONE +'colo evening' -

After scrolling with pgUp and pgDown, I can't see any artefacts.

---

> VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 25 2017 19:20:34)
> Included patches: 1-313, 315-771

I also tested on 8.0.313 with this shell command:

    env | TERM=xterm-256color ~/Vcs/vim/src/vim -u /tmp/.vimrc -

And this minimal vimrc:

    set rtp^=/home/user/Vcs/vim/runtime
    let $VIMRUNTIME = '/home/user/Vcs/vim/runtime'
    let $VIM = $VIMRUNTIME
    colo evening

Same result.  Just a guess, but if you can still reproduce, maybe the terminfo description of your terminal needs to be updated?  If so, you can try this:

    curl -LO http://invisible-island.net/datafiles/current/terminfo.src.gz
    gunzip terminfo.src.gz
    tic -sx -e $TERM terminfo.src

**Comment by sserbin** [comment]
nah, I don't think I've seen this in a while now :) gonna close this issue
