### ISSUE TITLE
scrolling in terminal make flicker

### ISSUE THREAD

**Issue by mattn** [vim/vim#1982]
after [patch 8.0.0938](https://github.com/vim/vim/commit/6bb18a878cc4cc79cdca4b7497367e59a90125e7)

## master/HEAD
![terminal](https://user-images.githubusercontent.com/10111/29391742-4ce6b864-8334-11e7-9afb-07f5c4eae18d.gif)

## without 8.0.0938
![terminal1](https://user-images.githubusercontent.com/10111/29391744-504ab2c6-8334-11e7-9872-ab8506272836.gif)

```diff
diff --git a/src/terminal.c b/src/terminal.c
index 799c656b0..ee5be4433 100644
--- a/src/terminal.c
+++ b/src/terminal.c
@@ -1500,6 +1500,7 @@ handle_moverect(VTermRect dest, VTermRect src, void *user)
     term_T	*term = (term_T *)user;
     win_T	*wp;
 
+#if 0
     if (dest.start_col == src.start_col
 	    && dest.end_col == src.end_col
 	    && dest.start_row < src.start_row)
@@ -1510,6 +1511,7 @@ handle_moverect(VTermRect dest, VTermRect src, void *user)
 		win_del_lines(wp, dest.start_row,
 				 src.start_row - dest.start_row, FALSE, FALSE);
 	}
+#endif
     redraw_buf_later(term->tl_buffer, NOT_VALID);
     return 1;
 }
```

**Comment by k-takata** [comment]
Fixed by 8.0.1797 (https://github.com/vim/vim/commit/6eddadff13164b98fe8198153cc656897b2cbcb3).
