### ISSUE TITLE
Vim 8.0.0918 make cursor blinks in urxvt

### ISSUE THREAD

**Issue by fff7d1bc** [vim/vim#1986]
The changes in commit 3cd43ccccb03b2e68df9c8a344a87e51c007c656 broke the cursor. Once one opens vim in urxvt, the cursor starts blinking, and blinks even outside vim. No option in vim or urxvt seems to affect it. Downgrade to 8.0.0917 fixes the problem.

**Comment by fff7d1bc** [comment]
cc @brammool

**Comment by brammool** [comment]
What is the output of   :set t_SH

**Comment by fff7d1bc** [comment]
`E846: Key code not set: t_SH` in working version
`  t_SH=^[[%p1%d q` in the 8.0.0918

**Comment by dandersson** [comment]
I am seeing the same issue in Debian Sid using

* rxvt-unicode 9.22-1+b3 (`TERM=rxvt-256color`, but `TERM` does not seem to matter)
* Vim 8.0.0946-1

An additional observation is that it does not seem to happen if I run Vim from within tmux (`TERM=screen-256color`, but it does not seem to matter here either). Within tmux, `:set t_SH` yields just `t_SH=`.

If I issue

    :!printf '\033[?12l'

(from https://unix.stackexchange.com/a/3769) within Vim, then the blinking stops.

---

A curiosity: if I start Vim to make the cursor blink and then

1. issue `:term`
2. issue `:!printf '\033[?12l'` in a regular buffer

the blinking does _not_ stop. If I however instead

1. issue `:term`
2. issue `printf '\033[?12l'` within the newly opened terminal (this step in itself does not stop the cursor blinking)
3. issue `:!printf '\033[?12l'` in a regular buffer

the blinking _does_ stop. This can be repeated within the same session: the cursor starts blinking again every time I issue `:term`.

**Comment by brammool** [comment]
> I am seeing the same issue in Debian Sid using
> 
> * rxvt-unicode 9.22-1+b3 (`TERM=rxvt-256color`, but `TERM` does not seem to matter)
> * Vim 8.0.0946-1
> 
> An additional observation is that it does not seem to happen if I run Vim from within tmux (`TERM=screen-256color`, but it does not seem to matter here either). Within tmux, `:set t_SH` yields just `t_SH=`.
> 
> If I issue
> 
>     :!printf '\033[?12l'
> 
> (from https://unix.stackexchange.com/a/3769) within Vim, then the blinking stops.
> 
> ---
> 
> A curiosity: if I start Vim to make the cursor blink and then
> 
> 1. issue `:term`
> 2. issue `:!printf '\033[?12l'` in a regular buffer
> 
> the blinking does _not_ stop. If I however instead
> 
> 1. issue `:term`
> 2. issue `printf '\033[?12l'` within the newly opened terminal (this step in itself does not stop the cursor blinking)
> 3. issue `:!printf '\033[?12l'` in a regular buffer
> 
> the blinking _does_ stop. This can be repeated within the same session: the cursor starts blinking again every time I issue `:term`.


I can reproduce this if I reset t_SI, t_SR and t_EI.
I'll have to request the cursor shape on startup, so that it can be
restored.

-- 
BEDEVERE:        And what do you burn, apart from witches?
FOURTH VILLAGER: ... Wood?
BEDEVERE:        So why do witches burn?
SECOND VILLAGER: (pianissimo) ... Because they're made of wood...?
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
Seeing same thing on Fedora 25, with $TERM=xterm-256color, and t_SH=^[[%p1%d q . Version is 8.0.946. Cursor is blinking even after its setting off with `:set guicursor+=a:blinkon0` .

**Comment by nuko8** [comment]
The fix has already been given with Patches 8.0.0967 and 8.0.0973 (93c92eff2 and ce1c32780, respectively).   Would you try 8.0.0973 or later to see if the issue is fixed for you?

> Cursor is blinking even after its setting off with `:set guicursor+=a:blinkon0` .

`'guicursor'` is used only when GUI is running, so it has no effect on the cursor of Vim on urxvt.

**Comment by fff7d1bc** [comment]
I can confirm that v8.0.0973 works as it should.

**Comment by vim-ml** [comment]
Cursor is working fine, thank you for the patch!
