### ISSUE TITLE
gvim cursorline would override diff background color

### ISSUE THREAD

**Issue by xyzith** [vim/vim#1987]
'set cursorline' would override diff background color.
The texts is hard to see.
![image](https://user-images.githubusercontent.com/7781656/29444082-4e1a13d0-840f-11e7-8ea5-d817b8258d8f.png)

**Comment by nuko8** [comment]
What color scheme do you use with the example?

**Comment by brammool** [comment]
This is intentional.  If we do it the other way around and there are large diffs, the cursor can't be seen.
If you prefer to see the diff highlighting, switch off 'cursorline' or move the cursor somewhere else.

**Comment by xyzith** [comment]
@nuko8 It just pure text, highligh didn't apply yet. My colorscheme is candycode anyway.
@brammool I have already swtched off cursorline.  Thx.
But it seems gvim 74 don't have this issue.

**Comment by nuko8** [comment]
@xyzith 

> But it seems gvim 74 don't have this issue.

The way of highlighting the cursor line in diff-mode has been changed since e0f148270 (Patch 7.4.391).
