### ISSUE TITLE
Vim segfault when executing feedkeys("\<C-w>N") at WinEnter

### ISSUE THREAD

**Issue by tyru** [vim/vim#1989]
## Steps to reproduce

1. `vim --clean -S {below script}`
1. `:terminal` (Open 1st terminal window)
1. `<C-w>:terminal` (Open 2nd terminal window)
    * No output like shell prompt appears here
1. Enter terminal-job mode by `i` or `a`
1. Segfault

```vim
function! s:term_winenter() abort
  if &buftype ==# 'terminal' &&
  \   term_getstatus(bufnr('')) !~# 'normal'
    call feedkeys("\<C-w>N", 'n')
  endif
endfunction

autocmd WinEnter * call s:term_winenter()
```

**Comment by brammool** [comment]
Looks like this was fixed by 8.0.0968
