### ISSUE TITLE
Gvim window content occasionally drawn offset from frame

### ISSUE THREAD

**Issue by mechalynx** [vim/vim#1990]
This is what happens: 

![gvim window](http://i.imgur.com/WPyK9rB.png)

(_clarification: this is exactly what gvim looks like, it's not a composite image - outside of the obfuscation, it's a straight screenshot of the window. The obfuscation is because the file contents are irrelevant and somewhat private - and yes I couldn't get a better screenshot due to reasons I explain below._)

(_edit - [better screenshot](http://i.imgur.com/fCxKkP0.png)_)
(_edit 2 - [another one](http://i.imgur.com/YKr5BsF.png)_)

The window's content will occasionally be redrawn offset, as you can see by the two status bars. If I keep typing, new characters appear at the correct location on screen. This does not seem to be in response to user input, _but_ I have a stupid mouse wheel so I can't say for sure. If I resize the window, it redraws properly. Sometimes a similar thing will happen, where redrawing will not occur at all, making vim seem like it's frozen, but if I resize it fixes itself again. I am under the impression this bug occurs with long files (that span far more than the height of the window), while the apparent freezing (no redraw) happens with files shorter than the window length, but _this is just my impression_.

The offset is not always the same and unless something triggers a full redraw (like resizing), the glitch remains, as would be expected.

Unfortunately, although this has been happening for a while now (months, a few times per day), I have not figured out any pattern to it or any way to consistently reproduce it. I decided to report it anyway, in case someone has a hunch or others are having the same issue - I gave up trying to figure out a pattern to it. So I took the opportunity with a file I had to obfuscate instead of using a better and clearer sample. If I get more examples I'll add links to the screenshots.

I'm running the x64 windows build from [tuxproject](https://tuxproject.de/projects/vim/) (patches 1-955) under windows 7 with an amd gpu and up-to-date drivers (if that matters). Here is my [vim dotfiles](https://gist.github.com/MechaLynx/79dd040a851517b0a00a180d67cb8411) and a screenshot of the [:version output](http://i.imgur.com/ZnGIiKP.png). `lazyredraw` is _not_ set.

**Comment by nuko8** [comment]
> So I took the opportunity with a file I had to obfuscate instead of using a better and clearer sample.

Aside from the obfuscation, is the picture a screenshot which exactly represents the same thing that you really saw on the screen, or a sort of a composite photograph in order to illustrate the issue easier?  I'm asking because I'm wondering why the title bar isn't overlaid.  Just to make sure, not that I want to dismiss the issue.

**Comment by mechalynx** [comment]
@nuko8 Yeah that's exactly what gvim looks like, sans the obfuscation - it's a screenshot of the window taken with Greenshot, which can do that, so it's not even cropped from a fullscreen image or anything. Looking at it now, I realize it looks like a comparison image or something, but it's not, that's coincidental. What you see is the actual issue.

I'm not sure what you mean by the title bar not being overlaid. I use a windows classic theme (so no aero styling) and if you mean gvim's titlebar, I've removed all that through the configuration since I don't use it. I like gvim to be consistent with the terminal version. If you mean the tab bar, it's drawn over by the misdrawn window contents.

**Comment by nuko8** [comment]
I see.

> I'm not sure what you mean by the title bar not being overlaid. 

I mean the strip with maroon background color at the top of the picture, which is supposed to be added to the main window of the application by the windowing system to decorate it with something like `Filename - GVIM`   (I know little about Windows, so let me allow to talk about that in terms of other OS's).

So, what

> The window's content will occasionally be redrawn offset

means is, not that the whole application window is repositioned and redrawn, but that some part of the main window is redrawn offset on and within that window, nothing outside of it, right?

**Comment by mechalynx** [comment]
@nuko8 Ah I see what's confusing. Yes the window decoration is fine, it's just the window content that's offset. To be precise, it's the entire content of the window that's redrawn offset from where it should be. The decoration (the border) is the OS's windowing manager's responsibility so gvim isn't involved there anyway. The title is as expected, just obfuscated because of the path.

**Comment by nuko8** [comment]
Thank you for the clarification.  Sounds like the issue is what we need to address.

**Comment by mechalynx** [comment]
@nuko8 Well, that's assuming it's not just on my end. I haven't figured out how to reproduce so it could just be my drivers messing up. I opened this issue just in case others like me are hesitant because it's not mentioned.

I don't think this can be worked on as it is, but if I manage to eliminate possibilities I'll edit the issue.

**Comment by nuko8** [comment]
OK, we'll wait for follow-ups by you and others.

**Comment by mechalynx** [comment]
I'm starting to think this is a GPU driver issue or something like that. I've had Evince and VLC experience the occasional hiccup like Vim, with redraws being messed up. Could be a GUI framework issue as well.  Vim experiences this far more than anything else, but I also use it far more than anything else, so that may just be my impression.

I'm closing this issue for now as there's no lead as to what's causing it or confirmation it's possible to fix it on Vim's side. I'll re-open if there's any clues.
