### ISSUE TITLE
Tests for 8.0.957 fail on macOS

### ISSUE THREAD

**Issue by chdiza** [vim/vim#1991]
The tests fail on macOS 10.12.6 when building Vim 8.0.957.  Here is the error:

```
From test_terminal.vim:
Found errors in Test_terminal_noblock():
function RunTheTest[24]..Test_terminal_noblock[8]..Stop_shell_in_terminal line 3: Expected 'dead' but got 'run'
Caught exception in Test_terminal_noblock(): Vim(bwipeout):E89: No write since last change for buffer 22 (add ! to override) @ function RunTheTest[24]..Test_terminal_noblock, line 10
TEST FAILURE
make[2]: *** [report] Error 1
make[1]: *** [scripttests] Error 2
make: *** [test] Error 2
```

**Comment by kafeltz** [comment]
How did you run the test? `make test`?

**Comment by vim-ml** [comment]
2017-08-19 4:15 GMT+09:00 chdiza <vim-dev-github@256bit.org>:

> The tests fail on macOS 10.12.6 when building Vim 8.0.957. Here is the
> error:
>
> From test_terminal.vim:
> Found errors in Test_terminal_noblock():
> function RunTheTest[24]..Test_terminal_noblock[8]..Stop_shell_in_terminal line 3: Expected 'dead' but got 'run'
> Caught exception in Test_terminal_noblock(): Vim(bwipeout):E89: No write since last change for buffer 22 (add ! to override) @ function RunTheTest[24]..Test_terminal_noblock, line 10
> TEST FAILURE
> make[2]: *** [report] Error 1
> make[1]: *** [scripttests] Error 2
> make: *** [test] Error 2
>
> I also got the same error.

Although I cannot convince myself that this is a correct solution, the
following modification works for me to make the test pass.

diff --git a/src/testdir/test_terminal.vim b/src/testdir/test_terminal.vim
index 64104abeb..ec8c47a2b 100644
--- a/src/testdir/test_terminal.vim
+++ b/src/testdir/test_terminal.vim
@@ -455,7 +455,11 @@ func Test_terminal_noblock()
   let buf = term_start(&shell)

   for c in ['a','b','c','d','e','f','g','h','i','j','k']
-    call term_sendkeys(buf, 'echo ' . repeat(c, 5000) . "\<cr>")
+    if has('osx')
+      call term_sendkeys(buf, 'echo ' . repeat(c, 1018) . "\<cr>")
+    else
+      call term_sendkeys(buf, 'echo ' . repeat(c, 5000) . "\<cr>")
+    endif
   endfor

   let g:job = term_getjob(buf)

It appears that macOS won't accept more than 1024 bytes at once by any
means; if 1018 is replaced with 1019 or more, then the test fails.

Hopefully, this could help us understand the issue further and lead to a
correct solution.

Best regards,
Kazunobu

**Comment by chdiza** [comment]
> How did you run the test? make test?

Yes.

**Comment by vim-ml** [comment]
2017-08-19 5:12 GMT+09:00 Kazunobu Kuriyama <kazunobu.kuriyama@gmail.com>:

> 2017-08-19 4:15 GMT+09:00 chdiza <vim-dev-github@256bit.org>:
>
>> The tests fail on macOS 10.12.6 when building Vim 8.0.957. Here is the
>> error:
>>
>> From test_terminal.vim:
>> Found errors in Test_terminal_noblock():
>> function RunTheTest[24]..Test_terminal_noblock[8]..Stop_shell_in_terminal line 3: Expected 'dead' but got 'run'
>> Caught exception in Test_terminal_noblock(): Vim(bwipeout):E89: No write since last change for buffer 22 (add ! to override) @ function RunTheTest[24]..Test_terminal_noblock, line 10
>> TEST FAILURE
>> make[2]: *** [report] Error 1
>> make[1]: *** [scripttests] Error 2
>> make: *** [test] Error 2
>>
>> I also got the same error.
>
> Although I cannot convince myself that this is a correct solution, the
> following modification works for me to make the test pass.
>
> diff --git a/src/testdir/test_terminal.vim b/src/testdir/test_terminal.vim
> index 64104abeb..ec8c47a2b 100644
> --- a/src/testdir/test_terminal.vim
> +++ b/src/testdir/test_terminal.vim
> @@ -455,7 +455,11 @@ func Test_terminal_noblock()
>    let buf = term_start(&shell)
>
>    for c in ['a','b','c','d','e','f','g','h','i','j','k']
> -    call term_sendkeys(buf, 'echo ' . repeat(c, 5000) . "\<cr>")
> +    if has('osx')
> +      call term_sendkeys(buf, 'echo ' . repeat(c, 1018) . "\<cr>")
> +    else
> +      call term_sendkeys(buf, 'echo ' . repeat(c, 5000) . "\<cr>")
> +    endif
>    endfor
>
>    let g:job = term_getjob(buf)
>
> It appears that macOS won't accept more than 1024 bytes at once by any
> means; if 1018 is replaced with 1019 or more, then the test fails.
>
> Hopefully, this could help us understand the issue further and lead to a
> correct solution.
>
> Best regards,
> Kazunobu
>

Somehow I forgot to write the reason why I don't think the modification I
gave is a correct solution.

On macOS, we have

$ getconf ARG_MAX
262144

So the number 1024 should not be an actual limitation of the OS.  It is no
surprise at all if the OS works with 5000 just like Linux.

Side Note: For the record, I often referred to the number 1024 in the
previous discussion on the issue, but that was the value of PATH_MAX, and I
think the latter number happens to be the same as the (apparent) maximum
upper bound to make the test pass for some reason.

**Comment by chdiza** [comment]
Tests are still failing, in a different way:
```
From test_terminal.vim:
Found errors in Test_terminal_noblock():
function RunTheTest[24]..Test_terminal_noblock line 9: Pattern 'done' does not match 'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecho eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee'
function RunTheTest[24]..Test_terminal_noblock[12]..Stop_shell_in_terminal line 3: Expected 'dead' but got 'run'
Caught exception in Test_terminal_noblock(): Vim(bwipeout):E89: No write since last change for buffer 22 (add ! to override) @ function RunTheTest[24]..Test_terminal_noblock, line 17
TEST FAILURE
make[2]: *** [report] Error 1
make[1]: *** [scripttests] Error 2
make: *** [test] Error 2
```

**Comment by chdiza** [comment]
If it helps, I ran it again and this time what 'done' isn't matching is:

 'ccccccccecho cccccccccccccccccccccccccccccccccccecho ccccccccccccccccccccccccccc'

**Comment by nuko8** [comment]
I confirm that this part of "Test results:"
```
function RunTheTest[24]..Test_terminal_noblock line 9: Pattern 'done' does not match 'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecho eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee'
```
often varies from test to test.   For example, I have another three different results:
```
function RunTheTest[24]..Test_terminal_noblock line 9: Pattern 'done' does not match 'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee'
function RunTheTest[24]..Test_terminal_noblock line 9: Pattern 'done' does not match 'ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd'
function RunTheTest[24]..Test_terminal_noblock line 9: Pattern 'done' does not match 'ddddddddddddddddddddddddddddddddddddddddddddecho dddddddddddddddddddddddddddddddddd'

```

**Comment by vim-ml** [comment]
Kazunobu Kuriyama wrote:

> 2017-08-19 4:15 GMT+09:00 chdiza <vim-dev-github@256bit.org>:
> 
> > The tests fail on macOS 10.12.6 when building Vim 8.0.957. Here is the
> > error:
> >
> > From test_terminal.vim:
> > Found errors in Test_terminal_noblock():
> > function RunTheTest[24]..Test_terminal_noblock[8]..Stop_shell_in_terminal line 3: Expected 'dead' but got 'run'
> > Caught exception in Test_terminal_noblock(): Vim(bwipeout):E89: No write since last change for buffer 22 (add ! to override) @ function RunTheTest[24]..Test_terminal_noblock, line 10
> > TEST FAILURE
> > make[2]: *** [report] Error 1
> > make[1]: *** [scripttests] Error 2
> > make: *** [test] Error 2
> >
> > I also got the same error.
> 
> Although I cannot convince myself that this is a correct solution, the
> following modification works for me to make the test pass.
> 
> diff --git a/src/testdir/test_terminal.vim b/src/testdir/test_terminal.vim
> index 64104abeb..ec8c47a2b 100644
> --- a/src/testdir/test_terminal.vim
> +++ b/src/testdir/test_terminal.vim
> @@ -455,7 +455,11 @@ func Test_terminal_noblock()
>    let buf = term_start(&shell)
> 
>    for c in ['a','b','c','d','e','f','g','h','i','j','k']
> -    call term_sendkeys(buf, 'echo ' . repeat(c, 5000) . "\<cr>")
> +    if has('osx')
> +      call term_sendkeys(buf, 'echo ' . repeat(c, 1018) . "\<cr>")
> +    else
> +      call term_sendkeys(buf, 'echo ' . repeat(c, 5000) . "\<cr>")
> +    endif
>    endfor
> 
>    let g:job = term_getjob(buf)
> 
> It appears that macOS won't accept more than 1024 bytes at once by any
> means; if 1018 is replaced with 1019 or more, then the test fails.
> 
> Hopefully, this could help us understand the issue further and lead to a
> correct solution.

It should be possible to use 5000.  I suspect that going over the 1024
bytes makes it slow, because characters get buffered and Vim only checks
once in a while if the socket is ready for writing.

I'll add an explicit wait in the test.  Please re-open the issue if it's
not fixed by the patch.

Hmm, perhaps MacOS is using poll()?  I had not done that part yet.

-- 
This computer is so slow, it takes forever to execute and endless loop!

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chdiza** [comment]
Just FYI this test still fails on 8.0.1048 on macOS.
