### ISSUE TITLE
Value of 'background' changed after loading a color scheme!

### ISSUE THREAD

**Issue by netjune** [vim/vim#1995]
Saving the following code to test.vim:

```
hi clear

if exists("syntax_on")
  syntax reset
endif

let g:colors_name = expand("<sfile>:t:r")

if &background=='light' 
elseif &background=='dark' 

  if &t_Co==8 || &t_Co==16
  elseif &t_Co==256
    hi Normal       ctermfg=252 ctermbg=234 cterm=NONE

  endif " t_Co

endif
```

Start vim and run the following:
```
set background=dark
source test.vim
set background?
```

The value of 'background' becomes light.

**Comment by ZyX-I** [comment]
You must include Vim version in the issue. Up to 8.0.616 this is intentional, `hi Normal` should alter the background. Starting from 8.0.616 it is a bug.

**Comment by netjune** [comment]
I'm using vim in macOS。Version is 7.4。Then this is not a bug。
