### ISSUE TITLE
Enter key not working in tig when run inside a terminal window

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#1998]
When I run `:terminal tig status`, then select a file and press Enter, instead of seeing the diff for the selected file, I get the message `Unknown key, press h for help`. All other keys appear to work. If I perform an action, such as:

- resize the Vim window, or
- call `term_wait()` on the terminal buffer, or
- execute a `<c-w>` command like `<c-w><c-w>` or `<c-w>Na`,

then Enter starts to work. Which makes me believe that Vim for some reason does not send the correct key code until an event like the above happens.

I can reproduce the above with Vim 8.0.979 under macOS and with MacVim 8.0.972.

For reference, tig is a text-mode Git interface: https://github.com/jonas/tig.

**Comment by mgedmin** [comment]
I can reproduce with Vim 8.0.979 on Linux.

Experiments show that `tig` interprets ^M as Enter and rejects ^J as an unknown key.

Curiously, if I run `vim` inside `:term` and then press ^V Enter in insert mode, I see ^M and not ^J.  (If I run `xxd` inside `:term`, I see 0x0a, which is ^J).

**Comment by brammool** [comment]
Marius Gedminas wrote:

> I can reproduce with Vim 8.0.979 on Linux.
> 
> Experiments show that `tig` interprets ^M as Enter and rejects ^J as
> an unknown key.
> 
> Curiously, if I run `vim` inside `:term` and then press ^V Enter in
> insert mode, I see ^M and not ^J.  (If I run `xxd` inside `:term`, I
> see 0x0a, which is ^J).

Unfortunately this is a bit complex.  There are several layers:

	We use a pty, which has controls about what the enter key is
	We use libvterm, which VTERM_KEY_ENTER, which means CR
	The job running in the pty may use ioctl() to change the key

I have added code in the terminal handling to obtain the keys used by
the pty:

	 /* Get the current backspace and enter characters of the pty. */
	    if (get_tty_info(fd, &info) == OK)
	    {
		term_backspace_char = info.backspace;
		term_enter_char = info.enter;
		term_nl_does_cr = info.nl_does_cr;
	    }

Not sure how well this works, since we have the master handle of the
pty, while the job is using the slave handle.

In Vim it's different, because it runs the terminal in raw mode.  Many
other programs run in echo mode.

libvterm also has a "newline" mode, where the Enter key gets turned into
both CR and NL.  Not sure when we should use that.

I hope someone has more knowledge about how all this is supposed to
work.

-- 
Bad fashion can discourage normal people from interacting with the engineer
and talking about the cute things their children do.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lilydjwg** [comment]
I have met the same problem: I've configured my zsh to use ^M to run commands, so I can use ^J to do other things. It breaks in Vim's terminal.

**Comment by brammool** [comment]
For the original problem: what ioctl calls does tig do to change the terminal behavior?
You may have to run it in a shell to make it work.

**Comment by lifepillar** [comment]
>For the original problem: what ioctl calls does tig do to change the terminal behavior?

I am not familiar with tig's codebase, so I'm afraid I can't help here.

>You may have to run it in a shell to make it work.

If you mean starting it with `term_start(['/bin/sh', '-c', 'tig'])`, that still has the same problem.

**Comment by chrisbra** [comment]
I can reproduce it. Here is the [log](https://gist.github.com/chrisbra/f00e1e31f0f74720b748e0b58cb2a111) running `strace -e trace=ioctl tig` however nothing relevant stood out. 

Tig does use internally the readline library. I wonder if this causes a problem here. BTW: here is a simple patch for rig to make the Enter work in vims terminal:
```patch
diff --git a/src/display.c b/src/display.c
index 3bc1a52..db0e9ea 100644
--- a/src/display.c
+++ b/src/display.c
@@ -813,6 +813,8 @@ get_input(int prompt_position, struct key *key)
                        input_mode = false;
                        if (key_value == erasechar())
                                key_value = KEY_BACKSPACE;
+                       if (key_value == '\n')
+                               key_value = KEY_RETURN;

                        /*
                         * Ctrl-<key> values are represented using a 0x1F
```

Perhaps @jonas (author of tig) can comment here?

**Comment by lifepillar** [comment]
I don't think tig is to blame here. I can reproduce the issue using only Vim. Here's how:

1. `vim --clean`
2. `:terminal`
3. In terminal, run `vim --clean`.
3. Within the inner Vim, define `:map <enter> :echo "Yep!"<cr>`

Press Enter and nothing will happen. Switch to the first window and back to the terminal window, and pressing Enter will print "Yep!".

**Comment by lifepillar** [comment]
…and if you add some empty lines to the buffer and put the cursor at the beginning, you will see the Enter is interpreted as CTRL-J before switching windows.

**Comment by chrisbra** [comment]
that is probably true and I agree that Vim is to be blamed and needs to be fixed. However I wonder if e.g. tig shouldn't by default handle `\n` just like `\r`. IIRC, Vim does it also that way.

**Comment by jonas** [comment]
I'm open to add special handling of  `\n` in Tig.

**Comment by chrisbra** [comment]
@jonas okay, created a PR. 

But does tig do something special with regard to ioctls regarding enter handling?

**Comment by lilydjwg** [comment]
My zsh still sees ^J, although I can't reproduce the issues with tig / vim mentioned in this thread. My vim version is 8.0.1274.

**Comment by k-takata** [comment]
The zsh problem is also discussed at #2278 and #2294.
