### ISSUE TITLE
With :terminal, arguments with spaces cannot be escaped

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#1999]
Using Vim 8.0.979, escaping with backslashes or single quotes does not work, i.e., the following commands fail:

```vim
:terminal ls dir\ with\ spaces
:terminal ls 'dir with spaces'
```

Double-quoted arguments seem to cause the text between and after the quotes to be ignored, e.g.:

```vim
:terminal cat "a b.txt" cd.txt
```

is the same as `:terminal cat`. I had not luck with `shellescape()`/`fnamescape()` either.

**Comment by dkrieger** [comment]
double quotes works now, but single quotes still fail, and there is no obvious way to pass them as literals.

**Comment by brammool** [comment]
Put the single quote inside double quotes:  :term echo "single'quote"

**Comment by dkrieger** [comment]
@brammool sorry, I could have explained that better. What I meant is that the following would fail:

`:term grep 'alice says "hello"'`

I believe it's being sent like (or equivalent to):

`grep "'alice says \"hello\"'"`

On the other hand, `:!grep 'alice says "hello"'` behaves as intended.
