### ISSUE TITLE
Important Git information seemingly missing from INSTALL files

### ISSUE THREAD

**Issue by BeyondTheHorizon** [vim/vim#2001]
After cleaning my PATH, I was really struggling to build Vim. After much frustration I eventually discovered that both Git's bin and usr\bin directories need to be in the PATH along with the path to Mingw. This is pretty important, but I've looked in the INSTALL files in Vim's src directory and I think it's nowhere to be found. Am I missing something?

**Comment by chrisbra** [comment]
What do you mean with git's bin and usr\bin directory? `/usr/bin` should always be in your path, if not you'll encounter various other problems, of which building Vim is probably the most uninteresting. I mean, binaries you are using should always be in the path, whether it be `/bin`, `/usr/bin` or even `/usr/local/bin` or `/opt/bin`. I don't think this is essentially a Vim problem you are seeing here.

**Comment by BeyondTheHorizon** [comment]
Understood. I just thought it would be worthwhile to note, but sorry if I wasted your time.

**Comment by chrisbra** [comment]
Okay. However, improvements to the documentation is always appreciated. So if you have concrete examples, what needs to be improved, let us know.

**Comment by BeyondTheHorizon** [comment]
Thanks. I just thought that if somebody did what I did and decided to clean their PATH (there were many non-existent directories there), it would be helpful. After all, I was able to successfully build Vim once I added both Git directories back to the path.
