### ISSUE TITLE
Copy/paste issue aftrer patch 8.0.0962

### ISSUE THREAD

**Issue by zdm** [vim/vim#2015]
Hello.
Patch 8.0.0962 brings new issue with copy / paste under windows.
When I paste text in insert mode, it shift cursor position to the 1 char. to the left.
Eg. if I paste string "12345", i expected, that after paste cursor will be after "5", but if appears after "4".

**Comment by brammool** [comment]
> Patch 8.0.0962 brings new issue with copy / paste under windows.
> When I paste text in insert mode, it shift cursor position to the 1
> char. to the left.
> Eg. if I paste string "12345", i expected, that after paste cursor
> will be after "5", but if appears after "4".

Please provide more information.  Did you start with "vim --clean"?
How exactly do you paste?

-- 
hundred-and-one symptoms of being an internet addict:
4. Your eyeglasses have a web site burned in on them.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
Reproduced after seeing your comment at here: https://github.com/vim/vim/commit/9aa156912867c05e0a6480925afe11c590378f09#commitcomment-23834209

Execute gvim with `gvim --clean -c "runtime mswin.vim"`, move the cursor to the end of an line, go to insert mode with `a` and type `Ctrl-V`.
It doesn't happen when the cursor is in the middle of an line.

**Comment by k-takata** [comment]
The behavior of `:normal! "+gP` is changed by 8.0.0962 when `set virtualedit=all`.
Before the patch, the cursor goes to next column of the last character after pasting by `:normal! "+gP`.
After the patch, the cursor goes on the last character (not next of it) after pasting.
If `"+gP` is used, both behave the same (go to next of the last char).

**Comment by zdm** [comment]
is this issue fixable?

**Comment by boytom** [comment]
@zdm Not yet. But the issue goes away when I remove the line `source $VIMRUNTIME/mswin.vim`  from _vimrc.

**Comment by zdm** [comment]
@boytom this is not an options, i need behave mswin

**Comment by chrisbra** [comment]
please give an easy reproducible example

**Comment by k-takata** [comment]
Put some text into the clipboard. e.g. `456`
Then,

```
$ vim --clean
:set ve=all
i123<Esc>  " Input some text
A<Ctrl-O>:normal! "+gP<Enter>
```
(These steps simulate `paste#Paste()` in `autoload/paste.vim` which is used from `mswin.vim`.)

The result is:
Before 8.0.0962: `123456`
After 8.0.0962: `124563`

It seems that my previous example was not enough.
Executing `:normal! "+gP` from the insert mode via Ctrl-O seems to cause the difference.
Interestingly, `A<Ctrl-O>"+gP` doesn't cause the difference.

**Comment by chrisbra** [comment]
That script is from 2006. It looks like it needs to be reworked. To keep the changes small, here is a patch that works for me. 
```patch
diff --git a/runtime/autoload/paste.vim b/runtime/autoload/paste.vim
index fcf06ecdf..705e58dcb 100644
--- a/runtime/autoload/paste.vim
+++ b/runtime/autoload/paste.vim
@@ -12,7 +12,7 @@
 if has("virtualedit")
   let paste#paste_cmd = {'n': ":call paste#Paste()<CR>"}
   let paste#paste_cmd['v'] = '"-c<Esc>' . paste#paste_cmd['n']
-  let paste#paste_cmd['i'] = 'x<BS><Esc>' . paste#paste_cmd['n'] . 'gi'
+  let paste#paste_cmd['i'] = "\<c-\>\<c-o>\"+gP"
 
   func! paste#Paste()
     let ove = &ve
```
