### ISSUE TITLE
Typing lag inside :terminal on gVim on Windows

### ISSUE THREAD

**Issue by markonm** [vim/vim#2016]
OS: Windows 10
gVim: 8.0.0987

Input latency inside :terminal is very long compared to regular input in non-:terminal windows.
I measured the following:
```
          | Min, ms | Max, ms | Avg, ms |
----------------------------------------
gvim      | 14.8    | 16.7    | 16. 3   |
:terminal | 114.9   | 116.7   | 116.3   |
```
It's more than 7 times slower to input letter in :terminal compared to non-terminal window.

**Comment by mattn** [comment]
please explain way to reproduce.

**Comment by markonm** [comment]
1. `vim --clean`
2. start insert mode
3. measure typing latency with program of choice (I used [typometer](https://github.com/pavelfatin/typometer))
4. open `:terminal` window
5. repeat third step
6. compare typing latency results from third and fifth step

I just realized typing lag is not specific to gVim, it also happens in CMD's Vim.

**Comment by markonm** [comment]
I can reduce lag to some extent with high frequency timer, described below, but then the cursor either stops blinking or blinks with extremely high frequency.

```vim
func! g:Foo(...)
    " do nothing
endfunc
call timer_start(1,function('g:Foo'),{'repeat':-1})
```

**Comment by markonm** [comment]
Fixed by https://github.com/vim/vim/commit/032f40afb88b24043f96655aa248267a4f54faa8
