### ISSUE TITLE
Cursor inside terminal doesn't respect 'guicursor' value

### ISSUE THREAD

**Issue by markonm** [vim/vim#2018]
OS: Windows 10
gVim: 8.0.0987

Right now if I set `guicursor=a:blinkon0` to disable cursor blinking, cursor will still blink when inside terminal.

**Comment by brammool** [comment]
> OS: Windows 10
> Version: 8.0.0987
> 
> Right now if I set `guicursor=a:blinkon0` to disable cursor blinking, cursor will still blink when inside terminal.

That is intentional, the cursor belongs to the terminal, thus behaves
like it's a terminal.

-- 
hundred-and-one symptoms of being an internet addict:
7. You finally do take that vacation, but only after buying a cellular modem
   and a laptop.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by markonm** [comment]
I have cursor blinking disabled in my Command Prompt too, shouldn't gVim's terminal respect that setting?

Currently if I open terminal in CMD's Vim, cursor will not blink.

**Comment by k-takata** [comment]
How do you disable cursor blinking in Command Prompt?

AFAIK, Windows doesn't provide an API to enable/disable cursor blinking:
https://docs.microsoft.com/en-us/windows/console/setconsolecursorinfo
https://docs.microsoft.com/en-us/windows/console/getconsolecursorinfo

**Comment by markonm** [comment]
I disabled it in Keyboard Properties. It's disabled in every application.

![untitled](https://user-images.githubusercontent.com/16160229/29646630-ee3a10e4-8884-11e7-899c-2e652d8952c0.jpg)

**Comment by markonm** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/ms648401(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/windows/desktop/ms648404(v=vs.85).aspx

Here you can change and retrieve blink rate.

**Comment by k-takata** [comment]
Ah, okay. How about this patch?

```diff
--- a/src/terminal.c
+++ b/src/terminal.c
@@ -2307,10 +2307,12 @@ create_vterm(term_T *term, int rows, int
 
     /* For unix do not use a blinking cursor.  In an xterm this causes the
      * cursor to blink if it's blinking in the xterm.
-     * We do want a blinking cursor by default on Windows, since that's what
-     * the default is for a console. */
+     * For Windows we respect the system wide setting. */
 #ifdef WIN3264
-    value.boolean = 1;
+    if (GetCaretBlinkTime() == INFINITE)
+	value.boolean = 0;
+    else
+	value.boolean = 1;
 #else
     value.boolean = 0;
 #endif
```

**Comment by markonm** [comment]
It works for me. I would be very glad if that patch got merged.

**Comment by markonm** [comment]
Fixed by https://github.com/vim/vim/commit/be0b72977f1f1de14f231b5879d5c600ba72c6a6

Thank you!

**Comment by bohrshaw** [comment]
It should be better if there's a `'termcursor'` option to custom.
