### ISSUE TITLE
Expression Register Bug

### ISSUE THREAD

**Issue by ghost** [vim/vim#2021]
I've discovered a bug that looks like a sort of integer overflow, though I'm not sure.

To reproduce:
* Enter Insert mode
* Press CTRL-R then = to bring up the expression register
* Add two random enormous numbers together and hit <CR>

An example:
`=143780283479018479034137280943781927801492387091342+4390124321890541897051289051328905213890`
gives a result of -2.

**Comment by fritzophrenic** [comment]
Indeed, Vim "Number" types only support 64-bit integers, and then only if compiled with 64-bit support (otherwise they're 32-bit).

What did you expect to happen instead for numbers that are too big to fit? I agree it's not documented very well, the best I could find was at ":help Number".

**Comment by ghost** [comment]
Hmm, I suppose this is more of a feature than a bug. Eh, Vim isn't supposed to be a calculator anyways 🙂
