### ISSUE TITLE
Provide a way to use TAB instead of C-G in incremental search

### ISSUE THREAD

**Issue by purpleP** [vim/vim#2022]
Seems like there's no way to do that except `cnoremap <TAB> <C-G>` which would broke `<TAB>` in command line mode. If there would be some indication that user is currently in incremental search this would be possible with `<silent><expr>` mapping.

**Comment by markonm** [comment]
You can use:
```vim
cnoremap <expr> <tab> <sid>Search_next()

function! s:Search_next()
  if getcmdtype() == '/'
    call feedkeys("\<C-g>", "tn")
    return ''
  elseif getcmdtype() == '?'
    call feedkeys("\<C-t>", "tn")
    return ''
  else
    call feedkeys("\<Tab>", 'tn')
    return ''
  endif
endfunction

```

**Comment by purpleP** [comment]
@xtal8 Wow, thanks a lot, this is working!

**Comment by ZyX-I** [comment]
@xtal8 Wondering why you are using `feedkeys()` and not just `return`?

    cnoremap <expr> <Tab> get({'/': '<C-g>', '?': '<C-t>'}, getcmdtype(), "\t")

works fine.

**Comment by markonm** [comment]
@ZyX-I  Sorry, I don't remember, I made that mapping a long time ago. Probably my poor VimL skills.

**Comment by purpleP** [comment]
@ZyX-I Um, it's not working for me. It works in incremental search, but tab completion now inserts `^I` which is how terminal sees tab. Seems we need to use  `feedkeys` to imitate tab press, otherwise it tries to literally insert tab.

**Comment by ZyX-I** [comment]
@purpleP You need to set `&wildcharm` to `<Tab>` as well:

> 	'wildcharm' works exactly like 'wildchar', except that it is
>	recognized when used inside a macro.  You can find "spare" command-line
>	keys suitable for this option by looking at |ex-edit-index|.  Normally
>	you'll never actually type 'wildcharm', just use it in mappings that
>	automatically invoke completion mode, e.g.:  
>	```VimL
>	:set wcm=<C-Z>
>	:cnoremap ss so $vim/sessions/*.vim<C-Z>
>	```
> 	Then after typing :ss you can use CTRL-P & CTRL-N.

I have it set in my vimrc for years to avoid discrepancy between mappings and typed characters, so it worked for me.

**Comment by purpleP** [comment]
@ZyX-I Yes, it works with `set wildcharm=<TAB>` thanks!

**Comment by ZyX-I** [comment]
So the code should be something like

```VimL
function s:CmdlineTab() abort
    let ret = get({'/': "\<C-g>", '?': "\<C-t>"}, getcmdtype(), nr2char(&wildcharm))
    if empty(ret)  " nr2char(0) is empty string
        throw "'wildcharm' not set, tab completion will not work"
    endif
    return ret
endfunction
cnoremap <expr> <Tab> <SID>CmdlineTab()
```

I have no idea why these two options (&wildchar and &wildcharm) exist in first place though, having them is inconsistent with how other bindings are configured (almost nothing is configured this way: Vim just has default key functions and mappings in case somebody is not satisfied with defaults), makes creating mappings harder (see how code above was expanded? And some other mappings that are otherwise expressable without `<expr>` will need `<expr>` or rely on `&wildcharm` not changing) and creates a difference between mappings and user input for unknown reason.

**Comment by ZyX-I** [comment]
(For those reading from ML: I made some edits to the code so it should work now.)
