### ISSUE TITLE
Timer hides visual selection when entering command-line mode

### ISSUE THREAD

**Issue by markonm** [vim/vim#2023]
OS: Windows
vim: 8.0.0994

I can reproduce it on Windows and WSL in gVim and Vim.

Steps to reproduce:

1. `vim --clean -S test.vim`
2. visually select some text
3. enter command-line mode
4. visual selection disappears

```vim
" test.vim
func! g:Foo(...)
  " do nothing
endfunc
call timer_start(40,function('g:Foo'),{'repeat':-1})
```

![55](https://user-images.githubusercontent.com/16160229/29737513-0178d196-8a0f-11e7-8eaa-ba516aa8bdf3.gif)

**Comment by brammool** [comment]
xtal8 wrote:

> OS: Windows
> vim: 8.0.0994
> 
> I can reproduce it on Windows and WSL in gVim and Vim.
> 
> Steps to reproduce:
> 
> 1. `vim --clean -S test.vim`
> 2. visually select some text
> 3. enter command-line mode
> 4. visual selection disappears
> 
> ```vim
> " test.vim
> func! g:Foo(...)
>   " do nothing
> endfunc
> call timer_start(40,function('g:Foo'),{'repeat':-1})
> ```
> 
> ![55](https://user-images.githubusercontent.com/16160229/29737513-0178d196-8a0f-11e7-8eaa-ba516aa8bdf3.gif)

I'll fix it.

-- 
How To Keep A Healthy Level Of Insanity:
3. Every time someone asks you to do something, ask if they want fries
   with that.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by markonm** [comment]
Fixed by https://github.com/vim/vim/commit/02e177d3e85e089ebdfba1a7d937150cffcb287a
Thank you.
