### ISSUE TITLE
guifontwide and WideCharToMultiByte

### ISSUE THREAD

**Issue by boytom** [vim/vim#2024]
I have searched the issues, but I haven't found such an issue about `guifontwide` and `WideCharToMultiByte` so I create an new issue. It's a strange problem.I have been using gvim for many years and suddenly gvim told me  yesterday that guifontwide was invalid and reported an error E231. So I traced into gvim source code and I found that there is something wrong with `WideCharToMultiByte`. I use gvim heavily on MS windows. And now I am using windows server 2016 and vim 8.0.0994. I have tested that from vim 8.0 to vim 8.0.0994, all the vim have such problem.
This is my `fenc`, `enc`, `gfn` and `gfw` in _vimrc :
```
set enc=utf-16LE
set fenc=chinese
set gfn=Consolas:h9 gfw=冬青黑体简体中文\ W3:h10
set linespace=0
```
I added some code to `enc_to_acp`, `get_logfont` and `gui_mch_get_font`, and I got the following log:
```
in gui_get_wide_font call gui_mch_get_font_name with font name = 冬青黑体简体中文 W3:h10...
in gui_mch_get_font
font name = 冬青黑体简体中文 W3:h10
=======
in enc_to_acp:before convert to utf16 [冬青黑体简体中文 W3:h10]
in enc_to_acp:after convert to utf16 [冬青黑体简体中文 W3:h10]
in enc_to_acp:after convert to acp [???àoúì??òì??D?? W3:h10][28]
=======
in get_logfont:
enc_codepage = 0, GetACP() = 936, acpname = ???àoúì??òì??D?? W3:h10, font_name = [???àoúì??òì??D?? W3:h10]
in gui_get_wide_font call gui_mch_get_font_name with font name = 冬青黑体简体中文 W3:h10 failed
```
After some researching, I located the problem. The Windows API `WideCharToMultiByte` does not work correctly. I wrote a piece of code and save it to `test.c` with text encoding in `utf8`:
```
#include <windows.h>
#include <stdio.h>
#include <tchar.h>
#include <wchar.h>
#include <stdlib.h>
#include <string.h>
#include <locale.h>

/*
 * Call WideCharToMultiByte() and allocate memory for the result.
 * Returns the result in "*out[*outlen]" with an extra NUL appended.
 */
    void
WideCharToMultiByte_alloc(UINT cp, DWORD flags,
	LPCWSTR in, int inlen,
	LPSTR *out, int *outlen,
	LPCSTR def, LPBOOL useddef)
{
    *outlen = WideCharToMultiByte(cp, flags, in, inlen, NULL, 0, def, useddef);
    /* Add one one byte to avoid a zero-length alloc(). */
    *out = (LPSTR)malloc((unsigned)*outlen + 1);
    if (*out != NULL)
    {
	WideCharToMultiByte(cp, flags, in, inlen, *out, *outlen, def, useddef);
	(*out)[*outlen] = 0;
    }
}
int main(int argc, char *argv[])
{
  const wchar_t *widestr = L"冬青黑体简体中文 W3:h10";
  int len = wcslen(widestr);

  unsigned char *out;
  int outlen;

  WideCharToMultiByte_alloc(GetACP(), 0, widestr, len,
      (LPSTR *)&out, &outlen, 0, 0);

	FILE *fp;
	fp = fopen("D:\\temp\\ac.txt", "wt");
  fprintf(fp, "[%s][%d]\n", out, outlen);
	fclose(fp);

  free(out);
  return EXIT_SUCCESS;
}
```
and compile  it with cl.exe:
```
cl -source-charset:utf-8 test.c
```
or complie it with gcc
```
gcc -o test.exe test.c
```
And `WideCharToMultiByte` works perfectly. Why?

**Comment by k-takata** [comment]
> set enc=utf-16LE

This is wrong. If you want to use Unicode on Vim, you should set enc to utf-8.
Not sure why your setting worked before.

**Comment by boytom** [comment]
I have tested when I `set enc=utf-8` and E231 occured too. But I didn't trace into the source code when `enc` was set to `utf-8`.

**Comment by boytom** [comment]
@k-takata I have tested when I set `enc` to `utf-8` and `E231` occured too. But I didn't trace into the source code when `enc` was set to `utf-8`.

**Comment by k-takata** [comment]
What does GetACP() return on your environment? Are you using Chinese Windows?

**Comment by boytom** [comment]
@k-takata  GetACP() returns `936` on my environment. Yes, I am using  Simplified Chinese Windows.

**Comment by boytom** [comment]
I guess I solve this issue now. Although I don't know why, but it works after I patch `winclip.c` with the following patch:
```
--- "vim\\src\\winclip.c"	2017-08-26 15:04:23.274356700 +0800
+++ "vim.debuging\\src\\winclip.c"	2017-08-26 14:45:01.307608500 +0800
@@ -179,6 +179,41 @@
     }
 }
 
+static char *
+wcstr_to_mbstr(const wchar_t *const src,
+    int length_in_wchars,
+    int *length_in_chars)
+{
+  if (src == NULL)
+    return NULL;
+
+  size_t bytes_required;
+
+  if (wcstombs_s(&bytes_required, NULL, 0u, src, 0u) != 0)
+    return NULL;
+
+  char *dest = (char *)alloc(bytes_required);
+
+  if (dest == NULL)
+    return NULL;
+
+  memset(dest, 0, bytes_required);
+
+  size_t chars_converted;
+
+  if (wcstombs_s(&chars_converted,
+        dest, bytes_required,
+        src, bytes_required - 1) != 0
+      || chars_converted != bytes_required) {
+    vim_free(dest);
+    return NULL;
+  }
+  assert(chars_converted == bytes_required);
+  if (length_in_chars != NULL)
+    *length_in_chars = chars_converted;
+  return dest;
+}
+
 #endif /* FEAT_MBYTE */
 
 #ifdef FEAT_CLIPBOARD
@@ -806,8 +841,11 @@
     widestr = (WCHAR *)enc_to_utf16(str, &len);
     if (widestr != NULL)
     {
+#if 0
 	WideCharToMultiByte_alloc(GetACP(), 0, widestr, len,
 						(LPSTR *)out, outlen, 0, 0);
+#endif
+	*out = (char_u *)wcstr_to_mbstr(widestr, len, outlen);
 	vim_free(widestr);
     }
 }
```
The function `wcstr_to_mbstr` in the patch is copyed from one of my projects.What I do is just replace `WideCharToMultiByte` with `wcstombs_s` and link gvim.exe with vc2013 C runtime(`msvcr120.dll`).
The log prints by my tracing code:
```
In function enc_to_acp: before convert to utf-16 [Consolas:h9][11]
In function enc_to_acp: after convert to utf-16 [Consolas:h9][11]
In function enc_to_acp: after convert to acp [Consolas:h9][12]
In function enc_to_acp: before convert to utf-16 [冬青黑体简体中文 W3:h10][23]
In function enc_to_acp: after convert to utf-16 [冬青黑体简体中文 W3:h10][23]
In function enc_to_acp: after convert to acp [冬青黑体简体中文 W3:h10][24]
```
It's right.

**Comment by boytom** [comment]
PS: Some software that ported from Linux to Windows like `gnu make`, `umbrello` and `git` have  issue about character encoding.For example, `gnu make` sometimes can not deal with Makefiles that contain Simplified Chinese comment; The UI language of umbrello inexplicably changes from Simplified Chinese to English; `git` sometimes can not deal with logs that contain Simplified Chinese character that encoded in utf-8. And I have found the solution too. Just clear all values under the reigistry key:
```
HKEY_CLASSES_ROOT\Local Settings\Software\Microsoft\Windows\Shell\MuiCache
```
But clear all values under the reigistry key does not solve the issue in gvim.

**Comment by tonymec** [comment]
Vim can indeed not use UCS-2, UTF-16 or UCS-4/UTF-32 internally because they contain null bytes and Vim uses (null-terminated) C strings.

However, Vim (when compiled with +multi_byte, of course) is not stupid. The relevant sentence can be found near the end of the help for `'encoding'`:

	When "unicode", "ucs-2" or "ucs-4" is used, Vim internally uses utf-8.

Though not mentioned explicitly, I suppose that the same applies to UTF-16 (which is an extension of UCS-2, using high-low surrogate pairs to represent codepoints U+10000 to U+10FFFF) and UTF-32 (which is a later synonym for UCS-4).

Best regards,
Tony.

**Comment by boytom** [comment]
The difference between `WideCharToMultiByte` and `wcstombs_s` may be the cause of the issue.

**Comment by k-takata** [comment]
If the test.c in your first comment works fine, but vim doesn't work, then somehow `GetACP()` returns different value on your environment?
Actually `wcstombs_s` uses `WideCharToMultiByte` internally.

**Comment by boytom** [comment]
I find out the difference between `WideCharToMultiByte` and `wcstombs_s`. When gvim runs it sets the locale to "C" and then `wcstombs_s`  does not call `WideCharToMultiByte`. The following is the code of `wcstombs_s` that deal with locale "C":
```
            while(count < n)
            {
                if (static_cast<uint16_t>(*pwcs) > 0xFF)  /* validate high byte */
                {
                    errno = EILSEQ;
                    return (size_t)-1;  /* error */
                }
                s[count] = (char) *pwcs;
                if (*pwcs++ == L'\0')
                    return count;
                count++;
            }
            return count;
```
And the utf-16le encode of "冬青黑体简体中文 W3:h10" in gvim is:
```
B6 00 AC 00 C7 00 E0 00 BA 00 DA 00 CC 00 E5 00 
BC 00 F2 00 CC 00 E5 00 D6 00 D0 00 CE 00 C4 00 
20 00 57 00 33 00 3A 00 68 00 31 00 30 00
```
Obviously it is wrong.

**Comment by k-takata** [comment]
What is the encoding of your `.vimrc`?
Please try the following `.vimrc`. It should be stored in utf-8.

```vim
set enc=utf-8
scriptencoding utf-8
set fenc=chinese
set gfn=Consolas:h9 gfw=冬青黑体简体中文\ W3:h10
set linespace=0
```

The important point is the use of `scriptencoding` which should be placed after the setting of `enc`.
See `:help :scriptencoding` for detail.

**Comment by boytom** [comment]
@k-takata My .vimrc is stored in cp936 now. I changed the encoding of .vimrc to cp936 during the debuging of gvim, just for testing and debuging.In the daily work, the encoding of .vimrc have always been utf-8. I was sure that  the encoding of .vimrc was utf-8 when I encountered such an issue. And now after I change the encoding of .vimrc back to utf-8, the issue go away. This drives me crazy just like my coding job. By the way, I cleaned some fonts which are not necessary in my system, Besides, I didn't do anything.

**Comment by mattn** [comment]
@boytom do you have `scriptencoding cp936` ? If your vimrc have multi-byte strings, you need to put this line. And if you change encoding in your vimrc, `set gfn=` should be written in the new encoding.

**Comment by boytom** [comment]
@mattn No, before  I encountered such an issue, the enoding have always been utf-8.

**Comment by k-takata** [comment]
Didn't you update Vim from 7.4?
Before Vim 7.4.202 `guifont` and `guifontwide` didn't respect `enc` setting, which was wrong.
Now they respect `enc`, so you should set them with the right encoding.

If you use multibyte characters in your script, you should always write the correct `scriptencoding` setting. Without that, the script can be parsed with a wrong encoding.

**Comment by boytom** [comment]
@k-takata Thank you for your clarification.  The problem now is that I can't reproduce the issue. It drives me crazy.

**Comment by k-takata** [comment]
> The problem now is that I can't reproduce the issue.

Okay, I'm closing this.
