### ISSUE TITLE
crashed by <C-s>

### ISSUE THREAD

**Issue by sclei** [vim/vim#2025]

**Comment by chrisbra** [comment]
please describe your problem.

**Comment by vyp** [comment]
Are you in a terminal? If so, this would be expected because `ctrl-s` is a terminal control character to stop character output. Try pressing `ctrl-q`.

**Comment by mgedmin** [comment]
I never understood why Vim doesn't use the terminal ioctls to disable ctrl-s/ctrl-q handling like it does for ctrl-c and ctrl-backslash.

**Comment by brammool** [comment]
ctrl-s / ctrl-q is set by the terminal.  It's not Vim specific.  If you don't want them, disable them in the terminal.  This probably works:  stty -ixon
