### ISSUE TITLE
Nothing in register * problem (vim+tmux or vim+screen )

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vim/vim#203]
```
What steps will reproduce the problem?
1. tmux (or screen)
2. vim
3. Detach from tmux (or screen)
4. Kill X11 server
5. Attach tmux(or screen)
6. Try to copy and paste using yy and p

What is the expected output? What do you see instead?
After copy and paste. It should paste but an error E353: Nothing in register * 
happens.

What version of the product are you using? On what operating system?

VIM - Vi IMproved 7.4
-arabic          +file_in_path    -mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
+balloon_eval    +float           -mouse_urxvt     -tag_any_white
+browse          +folding         +mouse_xterm     -tcl
+builtin_terms   -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
+clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      +toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    -keymap          +postscript      +virtualedit
+comments        -langmap         +printer         +visual
-conceal         +libcall         -profile         +visualextra
+cryptv          +linebreak       -python          +viminfo
-cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  -lua             -rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      +X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
-emacs_tags      +mouseshape      -sniff           +xsmp_interact
+eval            -mouse_dec       +startuptime     +xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop
-farsi           -mouse_netterm   +syntax

OS: Scientific Linux 5.8

Please provide any additional information below.
The way I am currently using to avoid this problem is to (Inside screen or tmux)
1. :mks!
2. exit vim
3. vim -S Session.vim
Then everything works well again.
Another way to avoid this problem is to
1. :gui
Then I can yank and paste using yy and p inside the newly opened gvim.

I think the problem is happening because vim lost the connection to the X11 
server after killing the X11 server. Would it be possible to make a command 
that makes a new connection to a X11 server inside vim? Or before yanking check 
if a connection to a X11 server is open and if not make a new connection to a 
X11 server?
```

Original issue reported on code.google.com by `fusion...@gmail.com` on 6 Mar 2014 at 1:06

**Comment by aleprovencio** [comment]
Alright folks I stopped running into this issue with `clipboard=unnamed` which is enought for my case but it still happens on `clipboard=unnamedplus`. This is Vim 7.4-1089, tmux 2.1 on Arch.

**Comment by aleprovencio** [comment]
ops not good yet, same issue, sorry folks.

**Comment by chrisbra** [comment]
Am 2016-02-04 11:34, schrieb aleprovencio:

> ops not good yet, same issue, sorry folks.

Please explain exactly what you did, what you expect and what you 
noticed.

Thanks!

**Comment by aleprovencio** [comment]
Hello @chrisbra,
I have vim with "clipboard=unnamed" running on a tmux and i3wm environment. By the time I restart i3wm, the clipboard in vim stops working giving this "nothing in register *" message.

**Comment by AntonOfTheWoods** [comment]
pb still present using Ubuntu 16.04 std packages.

**Comment by chrisbra** [comment]
Sorry, I don't neither know what packages are in ubuntu 16.04 nor which of the different vim flavors you installed. at a minimun, you should mention your `:version` output and clearly state what you did and what you expect and what you see.

**Comment by AntonOfTheWoods** [comment]
Hi,

Sorry for the delay. I am unfortunately unable to find a way to regularly reproduce the issue - it still happens after 1-2 hours of work pretty much every time but I can't reproduce at will. That said, I can report that:
- It appears to only happen when vim is run inside tmux (2.1)
- the '*' and '+' registers appear to disappear altogether from the given vim process (other vim processes, even inside the tmux are not affected). If I run :reg then the registers are simply not there anymore - whether I set clipboard=unnamed or unnamedplus, they both disappear.

I also have a couple of tmux plugins (tmux-yank, etc) related to copy/paste that I will deactivate to try and see if that helps.

Below are the package versions I have currently, I'll try with one of the daily ppas available to see if more recent versions fix the issue. The version I use mainly is vim-gnome.

ii  vim                                  2:7.4.1689-3ubuntu1.1                    amd64        Vi IMproved - enhanced vi editor
ii  vim-common                           2:7.4.1689-3ubuntu1.1                    amd64        Vi IMproved - Common files
ii  vim-gnome                            2:7.4.1689-3ubuntu1.1                    amd64        Vi IMproved - enhanced vi editor - with GNOME2 GUI
ii  vim-gnome-py2                        2:7.4.1689-3ubuntu1.1                    amd64        Vi IMproved - enhanced vi editor - with GNOME2 GUI (Python2)
ii  vim-gui-common                       2:7.4.1689-3ubuntu1.1                    all          Vi IMproved - Common GUI files
ii  vim-runtime                          2:7.4.1689-3ubuntu1.1                    all          Vi IMproved - Runtime files
ii  vim-tiny                             2:7.4.1689-3ubuntu1.1                    amd64        Vi IMproved - enhanced vi editor - compact version

`VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 16 2016 10:50:38)
Included patches: 1-1689
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version with GTK2-GNOME GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
+balloon_eval    +float           +mouse_urxvt     +tcl
+browse          +folding         +mouse_xterm     +terminfo
++builtin_terms  -footer          +multi_byte      +termresponse
+byte_offset     +fork()          +multi_lang      +textobjects
+channel         +gettext         -mzscheme        +timers
+cindent         -hangul_input    +netbeans_intg   +title
+clientserver    +iconv           +packages        +toolbar
+clipboard       +insert_expand   +path_extra      +user_commands
+cmdline_compl   +job             +perl            +vertsplit
+cmdline_hist    +jumplist        +persistent_undo +virtualedit
+cmdline_info    +keymap          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  +lua             +rightleft       +writebackup
+diff            +menu            +ruby            +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     +xsmp_interact
+emacs_tags      +mouseshape      +startuptime     +xterm_clipboard
+eval            +mouse_dec       +statusline      -xterm_save
+ex_extra        +mouse_gpm       -sun_workshop    +xpm
+extra_search    -mouse_jsbterm   +syntax          
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -D_REENTRANT -DORBIT2=1 -pthread -I/usr/include/libgnomeui-2.0 -I/usr/include/gnome-keyring-1 -I/usr/include/libbonoboui-2.0 -I/usr/include/libxml2 -I/usr/include/libgnome-2.0 -I/usr/include/libbonobo-2.0 -I/usr/include/bonobo-activation-2.0 -I/usr/include/orbit-2.0 -I/usr/include/libgnomecanvas-2.0 -I/usr/include/gail-1.0 -I/usr/include/libart-2.0 -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/gnome-vfs-2.0 -I/usr/lib/x86_64-linux-gnu/gnome-vfs-2.0/include -I/usr/include/gconf/2 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype  -lgnomeui-2 -lSM -lICE -lbonoboui-2 -lgnome-2 -lpopt -lbonobo-2 -lbonobo-activation -lORBit-2 -lgnomecanvas-2 -lart_lgpl_2 -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lfontconfig -lfreetype -lgdk_pixbuf-2.0 -lgnomevfs-2 -lgconf-2 -lgthread-2.0 -lgmodule-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.22/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-2.3 -lpthread -lgmp -ldl -lcrypt -lm`

**Comment by AntonOfTheWoods** [comment]
I can confirm that disabling the tmux plugins has no effect - the + and \* registers still disappear after a few hours of vim work with a given process.
