### ISSUE TITLE
Feature request: post-abbreviations in command mode

### ISSUE THREAD

**Issue by AvianY** [vim/vim#2033]
The way abbreviations work at the moment is, that after you type out the abbreviation mapping and press space, it gets expanded immediately.

My suggestion would be to add a new 'type' of abbreviation in command mode, such that when typed out, it wouldn't get expanded right away, but only *after* you pressed enter. 

The application for this would be for example to define a 'regular expression pattern'.
The ones built in, are ok, such as \<, \x, \u, ... etc, but it would be really useful to define your own, such as \(\<\S\+\>\s*\), which would match a WORD, followed by any number of spaces.
The problem is, that it's tedious to type it out, and even if you make an abbreviation or mapping, it gets expanded immediately, so the regex in the line becomes too long and unreadable...

**Comment by chrisbra** [comment]
I can see, how this could be useful to some, but doubt the general usefulness. 
Also once such a thing is implemented, there will probably be users, complaining Vim is executing something different than expected.
You can use the cmdline window to better edit command lines. 
Also you can create your own kind of abbreviations that are evaluated later using e.g. [c_CTRL-\_e](http://vimhelp.appspot.com/cmdline.txt.html#c_CTRL-\\_e)

so closing. Sorry.
