### ISSUE TITLE
[test failure][macOS] Test_terminal_noblock on 8.0.1013

### ISSUE THREAD

**Issue by splhack** [vim/vim#2035]
It's flaky, sometimes passed, sometimes failed

[Test_terminal_noblock.log.zip](https://github.com/vim/vim/files/1262292/Test_terminal_noblock.log.zip)
[Test_terminal_noblock.2.log.zip](https://github.com/vim/vim/files/1262293/Test_terminal_noblock.2.log.zip)

**Comment by splhack** [comment]
From travis ci log, macOS huge build, https://travis-ci.org/vim/vim/jobs/269839473

    Found errors in Test_terminal_noblock():
    function RunTheTest[24]..Test_terminal_noblock line 21: Pattern 'done' does not match 'iiiiiiecho iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii'
    function RunTheTest[24]..Test_terminal_noblock[24]..Stop_shell_in_terminal line 3: Expected 'dead' but got 'run'
    Caught exception in Test_terminal_noblock(): Vim(bwipeout):E89: No write since last change for buffer 17 (add ! to override) @ function RunTheTest[24]..Test_terminal_noblock, line 29

**Comment by brammool** [comment]
Kazuki Sakamoto wrote:

> From travis ci log, macOS huge build, https://travis-ci.org/vim/vim/jobs/269839473
> 
>     Found errors in Test_terminal_noblock():
>     function RunTheTest[24]..Test_terminal_noblock line 21: Pattern 'done' does not match 'iiiiiiecho iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii'
>     function RunTheTest[24]..Test_terminal_noblock[24]..Stop_shell_in_terminal line 3: Expected 'dead' but got 'run'
>     Caught exception in Test_terminal_noblock(): Vim(bwipeout):E89: No write since last change for buffer 17 (add ! to override) @ function RunTheTest[24]..Test_terminal_noblock, line 29

You can try increasing the wait time:


--- a/src/testdir/test_terminal.vim	2017-08-30 13:31:45.972512907 +0200
+++ b/src/testdir/test_terminal.vim	2017-08-30 19:36:45.661576797 +0200
@@ -464,7 +464,7 @@
     if has('mac')
       " TODO: this should not be needed, but without it sending keys blocks
       " after 8000 chars or so.
-      sleep 100m
+      sleep 200m
     endif
   endfor
   call term_sendkeys(g:buf, "echo done\<cr>")

However, we should find the cause of the problem, this is just a
temporary workaround.

-- 
Everyone has a photographic memory. Some don't have film.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by splhack** [comment]
Apparently 200ms is not still enough...

https://github.com/vim/vim/pull/2038/commits/5583f4efe088c2f4881eb02c872c1165de8d8509
https://travis-ci.org/vim/vim/jobs/270205101

    From test_terminal.vim:
    Found errors in Test_terminal_noblock():
    function RunTheTest[24]..Test_terminal_noblock line 21: Pattern 'done' does not match 'jjjjjjecho jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj'
    function RunTheTest[24]..Test_terminal_noblock[24]..Stop_shell_in_terminal line 3: Expected 'dead' but got 'run'
    Caught exception in Test_terminal_noblock(): Vim(bwipeout):E89: No write since last change for buffer 22 (add ! to override) @ function RunTheTest[24]..Test_terminal_noblock, line 29

**Comment by brammool** [comment]
Kazuki Sakamoto wrote:

> Apparently 200ms is not still enough...
> 
> https://github.com/vim/vim/pull/2038/commits/5583f4efe088c2f4881eb02c872c1165de8d8509
> https://travis-ci.org/vim/vim/jobs/270205101
> 
>     From test_terminal.vim:
>     Found errors in Test_terminal_noblock():
>     function RunTheTest[24]..Test_terminal_noblock line 21: Pattern 'done' does not match 'jjjjjjecho jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj'
>     function RunTheTest[24]..Test_terminal_noblock[24]..Stop_shell_in_terminal line 3: Expected 'dead' but got 'run'
>     Caught exception in Test_terminal_noblock(): Vim(bwipeout):E89: No write since last change for buffer 22 (add ! to override) @ function RunTheTest[24]..Test_terminal_noblock, line 29

I hope someone can take the time to find out what happens and how to fix
it properly.

-- 
It was recently discovered that research causes cancer in rats.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by splhack** [comment]
Can we use Python script instead of /bin/bash for the test? The issue might happen only with /bin/bash.

**Comment by splhack** [comment]
Fixed in 8.0.1049
