### ISSUE TITLE
[test failure][macOS] Test_terminal_hide_buffer on 8.0.1013

### ISSUE THREAD

**Issue by splhack** [vim/vim#2037]
[Test_terminal_hide_buffer.log.zip](https://github.com/vim/vim/files/1262303/Test_terminal_hide_buffer.log.zip)

**Comment by chrisbra** [comment]
can you please also show the output from the tests? And if you can reproduce the problem locally, can you show what is actually failing in the test? I find it hard from downloading some zip file and guessing what could be wrong.

**Comment by chrisbra** [comment]
BTW: are those the failures from #2038 on travis CI?

**Comment by splhack** [comment]
Sorry, I should have pasted the out as well. I can repro it locally, and travis CI caught the same errors as well. Anyway It was fixed in 8.0.1015.

    Found errors in Test_terminal_hide_buffer():
    Caught exception in Test_terminal_hide_buffer(): Vim(quit):E948: Job still running (add ! to end the job) @ function RunTheTest[24]..Test_terminal_hide_buffer, line 2
