### ISSUE TITLE
:terminal NONE on Windows

### ISSUE THREAD

**Issue by mattn** [vim/vim#2045]
UNIX implementation of `:terminal NONE` open termianl can open pty and possible to write strings into the pty using `system("echo 1 > " . pty)`. but on Windows, the named-pipe is guard to write from external process. it should be spawned on the window-station which is created from winpty.

Maybe it is possible to read output if the `system("echo 1 > " . pty)` is spawned from same window-station. For example, new command like `term_system(buf, cmd)`.

**Comment by mattn** [comment]
Below is a patch to create pty on Windows. But no way to access the pty. (without spawning process from winpty's API)

```diff
diff --git a/src/terminal.c b/src/terminal.c
index 1bcf8d92d..08032c9e1 100644
--- a/src/terminal.c
+++ b/src/terminal.c
@@ -3150,9 +3150,75 @@ failed:
 }
 
     static int
-create_pty_only(term_T *term, jobopt_T *opt)
+create_pty_only(term_T *term, jobopt_T *options)
 {
-    /* TODO: implement this */
+    channel_T	    *channel = NULL;
+    void	    *winpty_err;
+
+    if (dyn_winpty_init(TRUE) == FAIL)
+	return FAIL;
+
+    term->tl_winpty_config = winpty_config_new(3, &winpty_err);
+    if (term->tl_winpty_config == NULL)
+	goto failed;
+
+    winpty_config_set_initial_size(term->tl_winpty_config,
+						 term->tl_cols, term->tl_rows);
+    term->tl_winpty = winpty_open(term->tl_winpty_config, &winpty_err);
+    if (term->tl_winpty == NULL)
+	goto failed;
+
+    create_vterm(term, term->tl_rows, term->tl_cols);
+
+    term->tl_job = job_alloc();
+    if (term->tl_job == NULL)
+	goto failed;
+    ++term->tl_job->jv_refcount;
+
+    /* behave like the job is already finished */
+    term->tl_job->jv_status = JOB_FINISHED;
+
+    channel = add_channel();
+    if (channel == NULL)
+	goto failed;
+    term->tl_job->jv_channel = channel;
+    channel->ch_keep_open = TRUE;
+
+    channel_set_pipes(channel,
+	(sock_T)CreateFileW(
+	    winpty_conin_name(term->tl_winpty),
+	    GENERIC_WRITE, 0, NULL,
+	    OPEN_EXISTING, 0, NULL),
+	(sock_T)CreateFileW(
+	    winpty_conout_name(term->tl_winpty),
+	    GENERIC_READ, 0, NULL,
+	    OPEN_EXISTING, 0, NULL),
+	(sock_T)CreateFileW(
+	    winpty_conerr_name(term->tl_winpty),
+	    GENERIC_READ, 0, NULL,
+	    OPEN_EXISTING, 0, NULL));
+
+    channel_set_job(channel, term->tl_job, options);
+    term->tl_job->jv_tty_name =
+	utf16_to_enc((short_u *) winpty_conin_name(term->tl_winpty), NULL);
+
+    return OK;
+
+failed:
+    if (term->tl_winpty != NULL)
+	winpty_free(term->tl_winpty);
+    term->tl_winpty = NULL;
+    if (term->tl_winpty_config != NULL)
+	winpty_config_free(term->tl_winpty_config);
+    term->tl_winpty_config = NULL;
+    if (winpty_err != NULL)
+    {
+	char_u *msg = utf16_to_enc(
+				(short_u *)winpty_error_msg(winpty_err), NULL);
+
+	EMSG(msg);
+	winpty_error_free(winpty_err);
+    }
     return FAIL;
 }
 
diff --git a/src/testdir/test_terminal.vim b/src/testdir/test_terminal.vim
index 573db1e01..d299c7613 100644
--- a/src/testdir/test_terminal.vim
+++ b/src/testdir/test_terminal.vim
@@ -512,10 +512,6 @@ func Test_terminal_write_stdin()
 endfunc
 
 func Test_terminal_no_cmd()
-  " Todo: make this work on all systems.
-  if !has('unix')
-    return
-  endif
   " Todo: make this work in the GUI
   if !has('gui_running')
     return
@@ -525,8 +521,13 @@ func Test_terminal_no_cmd()
 
   let pty = job_info(term_getjob(buf))['tty']
   call assert_notequal('', pty)
-  call system('echo "look here" > ' . pty)
-  call term_wait(buf)
-  call assert_equal('look here', term_getline(buf, 1))
+  if has('win32')
+    call assert_true(filereadable(pty))
+  else
+    call system('echo "look here" > ' . pty)
+    call term_wait(buf)
+    call assert_equal('look here', term_getline(buf, 1))
+  endif
   bwipe!
 endfunc
```

Note that filereadable() return 0 since it can't access the pipe.

**Comment by mattn** [comment]
@brammool If you have plan to spawn new process on the terminal NONE, we will have to make pty using winpty like above. Or you want to use the pty as just screen for input/output, I can implement this with using named pipe.

**Comment by brammool** [comment]
Yasuhiro wrote:

> @brammool If you have plan to spawn new process on the terminal NONE,
> we will have to make pty using winpty like above. Or you want to use
> the pty as just screen for input/output, I can implement this with
> using named pipe.

The idea is that it should be possible to use the debugger plugin.
It's not doing much yet, but on Unix you can at least start gdb, using
the other terminal window to run the program in.  Try:

	packadd termdebug
	:Termdebug

You'll have to see how this works on MS-Windows: "gdb -pty {pty name}".

Keep in mind that on Unix a pty works in both directions.  On MS-Windows
it might be that stdin goes one way only and stdout the other way.

Of course the real test is to debug Vim!  If that works with a named
pipe that would be fine.  But you'll have to check if Vim works with
that.

For ":{range} term {command}" a named pipe should be fine.

-- 
Everybody lies, but it doesn't matter since nobody listens.
                                -- Lieberman's Law

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
AFAIK, windows named pipe can't behave master and slave. Do you mind
change key 'tty' to separated 'tty_in' and 'tty_out'? On UNIX, it
should be same value.

On 9/1/17, Bram Moolenaar <vim-dev-github@256bit.org> wrote:
>
> Yasuhiro wrote:
>
>> @brammool If you have plan to spawn new process on the terminal NONE,
>> we will have to make pty using winpty like above. Or you want to use
>> the pty as just screen for input/output, I can implement this with
>> using named pipe.
>
> The idea is that it should be possible to use the debugger plugin.
> It's not doing much yet, but on Unix you can at least start gdb, using
> the other terminal window to run the program in.  Try:
>
> 	packadd termdebug
> 	:Termdebug
>
> You'll have to see how this works on MS-Windows: "gdb -pty {pty name}".
>
> Keep in mind that on Unix a pty works in both directions.  On MS-Windows
> it might be that stdin goes one way only and stdout the other way.
>
> Of course the real test is to debug Vim!  If that works with a named
> pipe that would be fine.  But you'll have to check if Vim works with
> that.
>
> For ":{range} term {command}" a named pipe should be fine.
>
> --
> Everybody lies, but it doesn't matter since nobody listens.
>                                 -- Lieberman's Law
>
>  /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
> ///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/
> \\\
> \\\  an exciting new programming language -- http://www.Zimbu.org
> ///
>  \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
>
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/vim/vim/issues/2045#issuecomment-326559718
>
> --
> --
> You received this message from the "vim_dev" maillist.
> Do not top-post! Type your reply below the text you are replying to.
> For more information, visit http://www.vim.org/maillist.php
>
> ---
> You received this message because you are subscribed to the Google Groups
> "vim_dev" group.
> To unsubscribe from this group and stop receiving emails from it, send an
> email to vim_dev+unsubscribe@googlegroups.com.
> For more options, visit https://groups.google.com/d/optout.
>


-- 
- Yasuhiro Matsumoto

**Comment by brammool** [comment]
> AFAIK, windows named pipe can't behave master and slave. Do you mind
> change key 'tty' to separated 'tty_in' and 'tty_out'? On UNIX, it
> should be same value.

Hmm, I found this about the gdb "tty" command:

	This command is only supported on Linux. A similar command under
	Windows is set new-console

However, new-console means it will open a new console, thus it can't use
an existing one.


-- 
"Oh, no!  NOT the Spanish Inquisition!"
"NOBODY expects the Spanish Inquisition!!!"
				-- Monty Python sketch --
"Oh, no!  NOT another option!"
"EVERYBODY expects another option!!!"
				-- Discussion in vim-dev mailing list --

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
Yasuhiro Matsumoto wrote:

> AFAIK, windows named pipe can't behave master and slave. Do you mind
> change key 'tty' to separated 'tty_in' and 'tty_out'? On UNIX, it
> should be same value.

If we can make it more portable, that is always welcome.

But it might be difficult (impossible?) to connect a command to an
already opened console.  At least gdb apparently doesn't do it.
It can open a new console, so perhaps we can make winpty use that
console instead of creating its own.

-- 
hundred-and-one symptoms of being an internet addict:
44. Your friends no longer send you e-mail...they just log on to your IRC
    channel.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
