### ISSUE TITLE
vim ^[ ghosting

### ISSUE THREAD

**Issue by hongliang5316** [vim/vim#2047]
hello
   When i use vim, there sometimes appear '^[' ghosting, i did not know how to fix this.
   Any one can help me? this is very annoying.
  
![image](https://user-images.githubusercontent.com/13626322/29965199-50165b22-8f3f-11e7-80f9-fa7f2ce15de5.png)

 I use vim solarized  dark colorscheme  and putty.
 TERM: xterm-256color

**Comment by chrisbra** [comment]
what vim version?

**Comment by hongliang5316** [comment]
@chrisbra 
vim version:  7.4.160
Centos7

**Comment by chrisbra** [comment]
that is a very old version. Can you please check out a newer version?

**Comment by hongliang5316** [comment]
@chrisbra

**Comment by hongliang5316** [comment]
@chrisbra 
Okay, i'll try. i use `yum` command to install vim.
Do you have any suggestion to upgrade vim by `yum` or another way?
Thanks!

**Comment by tonymec** [comment]
On a Unix-like OS like yours seems to be, you can compile your own Vim from the latest sources; it is not even hard once you have all the necessary compiler and "development" packages installed.

See
- http://vim.wikia.com/wiki/Getting_the_Vim_source_with_Mercurial
- http://users.skynet.be/antoine.mechelynck/vim/compunix.htm

Best regards,
Tony.

**Comment by hongliang5316** [comment]
@tonymec 
Thanks for your answer, i have upgrated vim to v8.0.1030.

**Comment by chrisbra** [comment]
And is this solved?

**Comment by hongliang5316** [comment]
@chrisbra 
I'm not sure, it never appeared again. i will continue to observe for some time.
Thanks!

**Comment by hongliang5316** [comment]
@chrisbra  @tonymec 
A few days have passed, everything seems to be fine. i will close this issure.
Many thanks. 
Vim is a very nice editor 👍 .
