### ISSUE TITLE
E363: pattern uses more memory than 'maxmempattern'

### ISSUE THREAD

**Issue by ghost** [vim/vim#2049]
Hello!
there is an error when I open this file with vim:
https://raw.githubusercontent.com/gpjt/webgl-lessons/master/lesson16/macbook.json

Error detected while processing function <SNR>12_Highlight_Matching_Pair:
line   78:
E363: pattern uses more memory than 'maxmempattern'
Press ENTER or type command to continue

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)

**Comment by chrisbra** [comment]
where is your cursor, when this happens?

**Comment by tonymec** [comment]
1. Vim 7.4 is getting a little long in the teeth. The current state-of-the art Vim is 8.0.1097 as of this writing, and the original 8.0 release (8.0.0, so to speak) was published on 12-Sep-2016, precisely one year ago today, and more than two months **before** your Vim 7.4 was compiled.

2. What does Vim answer to

       :verbose set mm? mmt? mmp?
?

Best regards,
Tony.

**Comment by chrisbra** [comment]
I can reproduce it. There is an issue with the corresponding file and the json syntax rule and the matchit and matchparen plugin.
How about this [patch](https://gist.github.com/chrisbra/61f11802c2da69ba3f35665ccc44f108)

Note, even with this patch, Vim throws `E363` when initially loading the file. This happens because the call to `get_syntax_attr()` from the `win_line()` function also causes this error. (which basically means, Vim will disable syntax highlighting). I am a bit unsure, if Vim should throw this error message or not or perhaps we should simply give a better error message in that case, so that the user knows that syntax highlighting will be disabled.

**Comment by tonymec** [comment]
That 1266822-byte file (i.e. more than 1 MiB, which would be 1048576 bytes) consists of a single line. I don't see your error message in Vim 8.0.1097 for Linux64 (:mess doesn't show it), and json highlight groups are defined for the file, but when I hit `End` to put the cursor at the end of the line, Vim got hung and I had to kill it.

**Comment by krmayankk** [comment]
what is the solution to this ? i am getting this on mac with vim 
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 30 2018 07:37:16)
macOS version
Included patches: 1-1650
```

**Comment by chrisbra** [comment]
please share more details, what have you been doing? Have you been using a special expensive search pattern?

**Comment by krmayankk** [comment]
i am using vim-go plugin with the following .vimrc mostly copied from somewhere, not an expert in this area
```
call plug#begin()
Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
call plug#end()

let mapleader=","
execute pathogen#infect()
syntax enable  
filetype plugin indent on  
set number  
let g:go_disable_autoinstall = 0
let g:go_highlight_functions = 1  
let g:go_highlight_methods = 1  
let g:go_highlight_structs = 1  
let g:go_highlight_operators = 1  
let g:go_highlight_interfaces = 1
let g:go_highlight_build_constraints = 1  
filetype plugin indent on
syntax on
set expandtab
set shiftwidth=4
set tabstop=4
colorscheme molokai
map <C-n> :NERDTreeToggle<CR>
let g:tagbar_type_go = {  
    \ 'ctagstype' : 'go',
    \ 'kinds'     : [
        \ 'p:package',
        \ 'i:imports:1',
        \ 'c:constants',
        \ 'v:variables',
        \ 't:types',
        \ 'n:interfaces',
        \ 'w:fields',
        \ 'e:embedded',
        \ 'm:methods',
        \ 'r:constructor',
        \ 'f:functions'
    \ ],
    \ 'sro' : '.',
    \ 'kind2scope' : {
        \ 't' : 'ctype',
        \ 'n' : 'ntype'
    \ },
    \ 'scope2kind' : {
        \ 'ctype' : 't',
        \ 'ntype' : 'n'
    \ },
    \ 'ctagsbin'  : 'gotags',
    \ 'ctagsargs' : '-sort -silent'
    \ }

nmap <F8> :TagbarToggle<CR>
au FileType go nmap gd <Plug>(go-def)
au FileType go nmap <Leader>i <Plug>(go-info)
au FileType go nmap <Leader>gd <Plug>(go-doc)
au FileType go nmap <Leader>gv <Plug>(go-doc-vertical)
au FileType go nmap <Leader>gb <Plug>(go-doc-browser)
au FileType go nmap <leader>r <Plug>(go-run)
au FileType go nmap <leader>b <Plug>(go-build)
au FileType go nmap <leader>t <Plug>(go-test)
au FileType go nmap <Leader>ds <Plug>(go-def-split)
au FileType go nmap <Leader>dv <Plug>(go-def-vertical)
au FileType go nmap <Leader>dt <Plug>(go-def-tab)
let g:golang_goroot = "/usr/local/go"
let g:golang_onwrite = 0
```

**Comment by chrisbra** [comment]
and when exactly do you experience that error?

**Comment by krmayankk** [comment]
@chrisbra when saving a file using `w` command

**Comment by chrisbra** [comment]
what kind of a file? do you have an autocommand on `:w`? Can you reproduce starting with vim --clean? I suppose a plugin (vim-go) is doing something strange here.

**Comment by diogokiss** [comment]
I'm facing a similar issue when using `<SHIFT> + g` to go to the end of a regular YAML file.
The file has 193 lines and 42 KB.

![screen shot 2018-11-23 at 11 10 48 am](https://user-images.githubusercontent.com/779938/48938102-75d1d080-ef10-11e8-9928-cb71b50f7c1a.png)

**Comment by chrisbra** [comment]
Can you please provide a reproducible example?

**Comment by etanjoco** [comment]
I'm seeing the same message when doing a search through a yaml file with long lines ie. base64 encoded certificate definitions.  The error seems to go away if I turn syntax highlighting off in my .vimrc. I'm running vim 8.0.1283 on mac and am able to see the error on either iterm2 or the regular mac terminal.  Attached is a sample file.  You may have to rename it to test.yaml to get the syntax highlighting to do its thing.

[test.txt](https://github.com/vim/vim/files/2659107/test.txt)

**Comment by chrisbra** [comment]
well, check if using a different regexpengine makes a different. If the pattern is complicated, you might want to think about increasing the limit for 'maxmempattern'

**Comment by etanjoco** [comment]
The expression that I am using is pretty simple.  Just looking for "tls"
would trigger it when using the full file.  In the file I attached, just
opening the file would trigger the error, so I think it has to do with
rendering the string in the window with syntax highlighting on.

**Comment by chrisbra** [comment]
I don't see the problem on my windows system, Vim 8.1.374. However, there the `'maxmemtot'` value is `16472536` and `maxmempattern` is 1000. 
As said before, since you are working with a complex file (base64 encoding inside a regular file), it might make sense to increase your 'maxmempattern'  value. Also you should try with an updated Vim just so that you got the latest runtime files and latest patches.

**Comment by kschaab** [comment]
I encountered this issue using go-vim as did another user.  I was using Vim 8.0 patch level 1-1401.  In my circumstance I doubt that it was a bug as the file was large and setting maxmempattern (was at 1000) to a higher level fixed the issue.

**Comment by chrisbra** [comment]
I think the runtime file updates have been included. I am closing this. If this happens again, please create a new issue and try to answer all questions mentioned here. Thanks.

**Comment by sentientmachine** [comment]
I've reproduced this error on a brand new 2 day old apple macbook pro laptop, on pre-installed vanilla vim with no configuration.  To reproduce, make a new file `stuff.txt` with 3 lines containing exactly this:

    fun{
    #asdf
    }

Reopen the above `stuff.txt` using `vim -u NONE stuff.txt`

Run these two commands in the vim editor:

    :hi somecolor ctermfg=999 ctermbg=24
    :call matchadd("somecolor", 'fun{\(\n\s*\|\s*\)*}', -1)

Immediately after the matchadd line you get an error: `E363: pattern uses more memory than 'maxmempattern'`.

If you increase maxmempattern, it just consumes that much memory before the E363.  The two tokens that fix the problem if removed are the grouped zero or more spaces, and the group asterisk wildcard.

The problem appears to be the regex engine doesn't detect an infinite loop in the zero or more instances of zero or more spaces.  So it goes full throttle counting instances of "zero spaces" until it runs out of memory and presents the E363.

**Clues:**

OS: `macOS Mojave 10.14.4 2.9GHz Intel Core i9 32GB 2400 MHz DDR4`

Vim version, default that comes preinstalled: 

    VIM - VI IMproved 8.0 (2016 Sep 12, compiled Feb 22 2019 18:22:38)
    Included patches: 1-503, 505-680, 682-1283
    Compiled by root@apple.com

I've been using macs forever and it looks like apple employees are adding regressions into vim regex engine in their patches to nudge people into using Xcode that steers you toward micro payments.  My other mac laptop `VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Aug  4 2017 11:53:34)` doesn't have this problem and processes this regex just fine, and its regex engine doesn't blow the stack looking for an infinite number of zero length objects.

**workaround 1**: remove the offending regexes or don't use a zero or more space wildcard inside a group that is matched zero or more times.  As soon as the apple vim regex engine encounters that it will infinite loop until memory is exhausted.

**workaround 2**:  Install vim from source and exclude apple's latest shitty vim-patches that break the editor.  

**workaround 3**:  Apple is aware of their regression and have pushed a patch for the bad patch.  Apply palm to forehead and make sure you've got the latest vim:

    brew install vim
    vim --version
        VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 23 2019 20:00:52)
        macOS version Included patches 1-1200

**Comment by chrisbra** [comment]
Thanks for the clear example.

> VIM - VI IMproved 8.0 (2016 Sep 12, compiled Feb 22 2019 18:22:38)
> Included patches: 1-503, 505-680, 682-1283
> Compiled by root@apple.com

Hm, missing patch [8.0.0504](https://github.com/vim/vim/releases/tag/v8.0.0504) and [8.0.681](https://github.com/vim/vim/releases/tag/v8.0.0681). I wonder why they left that out. 

In any case, since 8.0.1283 until 8.1.1248 from yesterday it's about 1874 patches, so assuming your workaround 2 is correct this means, that this problem has been solved.

>  Install vim from source and exclude apple's latest shitty vim-patches that break the editor.

Are there any additional patches from Apple, that are not upstream? Can you please also complain about that problem in an official apple forum, so they get feedback and can fix their own builds? Thanks.

**Comment by sentientmachine** [comment]
@chrisbra  Will do on complaining to apple for their regex engine vim regression patches.

It turns out Apple is aware of this regression, and has already pushed a patch.

**So I was able to fix everything** by telling homebrew to get the very latest vim with: 

    brew install vim

Now I have version:

    vim --version
    VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 23 2019 20:00:52)
    macOS version Included patches 1-1200

So now all is well:  No more infinite loop, no memory exhaustion, the `E363` message does not appear and the regex performs to specification.

**Comment by weaming** [comment]
> 1. Vim 7.4 is getting a little long in the teeth. The current state-of-the art Vim is 8.0.1097 as of this writing, and the original 8.0 release (8.0.0, so to speak) was published on 12-Sep-2016, precisely one year ago today, and more than two months **before** your Vim 7.4 was compiled.
> 2. What does Vim answer to
>    ```
>    :verbose set mm? mmt? mmp?
>    ```
> 
> ?
> 
> Best regards,
> Tony.

`set mmp=5000` helped me (original value is 1000. using neovim).

**Comment by benthorner** [comment]
I've been getting this when editing markdown files, after typing `[` (to add a link). I don't get the error if I do `vim -u NONE` before editing the file. I also can't reproduce the error as described in https://github.com/vim/vim/issues/2049#issuecomment-488864100. 

Vim version is:

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 22 2021 19:39:30)
macOS version - x86_64
Included patches: 1-2800
```

Anecdotally, this only seems to happen in large files - in this case, I was editing a long README file with lots of JSON examples in it. Fortunately, the `set mmp=5000` workaround fixes the issue.

**Comment by chrisbra** [comment]
is this with any plugins that map `[` to something? Also could you share the file for inspection?

**Comment by benthorner** [comment]
@chrisbra sure:

- I've checked the output of `:map` and it doesn't contain a `[` character.
- For reference, the plugins I have are [here](https://github.com/benthorner/vim-rc/blob/master/vimrc#L39-L46) (+ `glench/vim-jinja2-syntax`)
- The file I was editing is [here](https://github.com/alphagov/mapit/blob/7f3cbe975d1e376b26f449eccd98d29c21cab15e/README.md). Any insertion of `[` seems to trigger it.

I did some more investigation. With an empty `.vimrc`, the following combo triggers it for me:

```
:set re=1
:syntax enable
```

Then if I type a `[` character I get the same error. Do you get the same thing?

**Comment by chrisbra** [comment]
It happens in insert mode, right? So please check the output of `:imap [`  or `imap <buffer> [`.

With that example file, I cannot reproduce this using `vim -u NONE -N -c 'set re=1' -c 'syntax enable' README.md`

**Comment by benthorner** [comment]
Yes, that's right. I just tried the following, and still get the error:

```
# in zsh on my Mac
vim -u NONE -N -c 'set re=1' -c 'syntax enable' README.md

# in insert mode
...
[
...
```

Running those two Vim commands in this context both give: `No mapping found`.

Could it be something to do with the version or OS?

**Comment by dpelle** [comment]
I can reproduce the E363 error with the latest vim-8.2.2818 (huge) on Linux x86_64. 
I completely automated how to reproduce, so you only need to copy paste:
```
$ wget -O /tmp/README.md https://raw.githubusercontent.com/alphagov/mapit/7f3cbe975d1e376b26f449eccd98d29c21cab15e/README.md
$ vim --clean -c'set re=1' -c'syntax enable' -c'call feedkeys("i[")' /tmp/README.md
E363: pattern uses more memory than 'maxmempattern'
```

**Comment by chrisbra** [comment]
Hm, I notice this happens sometimes for me and sometimes it doesn't. Anyways, it looks like this pattern is to blame:

    0.001580   407    49      0.000047    0.000004  markdownLinkText   !\=\[\%(\%(\_[^][]\|\[\_[^][]*\]\)*]\%( \=[[(]\)\)\@=

**Comment by brammool** [comment]
Dominique wrote:

> I can reproduce the E363 error with the latest vim-8.2.2818 (huge) on Linux x86_64. 
> I completely automated how to reproduce, so you only need to copy paste:
> ```
> $ wget -O /tmp/README.md https://raw.githubusercontent.com/alphagov/mapit/7f3cbe975d1e376b26f449eccd98d29c21cab15e/README.md
> $ vim --clean -c'set re=1' -c'syntax enable' -c'call feedkeys("i[")' /tmp/README.md
> E363: pattern uses more memory than 'maxmempattern'
> ```

Thanks.  The pattern causing this trouble is markdownLinkText:

"!\=\[\%(\%(\_[^][]\|\[\_[^][]*\]\)*]\%( \=[[(]\)\)\@="

Which is indeed quite nasty.

-- 
hundred-and-one symptoms of being an internet addict:
198. You read all the quotes at Netaholics Anonymous and keep thinking
     "What's wrong with that?"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by tpope** [comment]
In https://github.com/vim/vim/issues/6777#issuecomment-684776825 I was given a workaround for this, which I've applied upstream. It will be included the next time I submit updated runtime files.

**Comment by benthorner** [comment]
Nice debugging! And it's great to hear a fix might be coming soon 🎉  

How often do the runtime files get submitted?

**Comment by daweth** [comment]
Anyone using mac should update their vim version as advised. This fixes the issue.

**Comment by shashinvision** [comment]
> 

Fix my problem :D Thanks

**Comment by mirageglobe** [comment]
i have set mmp to 5000 and it works for < vim 9.0. after upgrade, this comes back. just headsup if anyone is getting similar too.

**Comment by peppy** [comment]
It was never fixed for me, even in newer versions. I'm still using the workaround.

**Comment by tpope** [comment]
I failed to submit the updated Markdown runtime files in time for Vim 9.0. I'll take care of it in the next week or two.
