### ISSUE TITLE
Undo file broken

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vim/vim#205]
```
Vim 7.4 on Windows 8/8.1

If I set undofile, after some operations the edited file and undofile both are 
broken, edited file beceomes one long line only contains ^@(<C-Q><C-@>); also 
get error that undofile is not correct.

This problem never happend if I use Windows 7 in the past.

```

Original issue reported on code.google.com by `rickywu1...@gmail.com` on 12 Mar 2014 at 1:11

**Comment by chrisbra** [comment]
Considering that this ticket is open for more than 4 years and we haven't heard any more breakage problems, I suppose this is fixed. Also the problem description isn't very clear. So Closing.
