### ISSUE TITLE
can't move to the last character in common mode

### ISSUE THREAD

**Issue by zhang-zhenyu** [vim/vim#2051]
When I change the cursor from block to line, the cursor can't move to the last character of per line in common mode. That can be an import bug to conquer!

**Comment by nuko8** [comment]
> When I change the cursor from block to line, the cursor can't move to the last character of per line in common mode. 

Can you make sure of that again?  The behavior should be independent of cursor shape.

> That can be an import bug to conquer!

Read `:h virtualedit` and try
```
:set virtualedit=onemore
```
Does this fix the "bug" for you?

**Comment by zhang-zhenyu** [comment]
Thank you very much! I have solved the problem. So the "$" and "End" just move the cursor to the last character, but not pass it to be the last as i thought.
If what I think is right, i doubt why not using a shortcut key to move it to "the truth end", but bothered moving the cursor right after moving it to the end by "$".

**Comment by tonymec** [comment]
Hitting A (i.e. Shift-a) in Normal mode will put you in Insert mode just after the end of the line, see `:help A`.

Best regards,
Tony.
