### ISSUE TITLE
matchadd() fails to highlight blank line if cursor is on the same line

### ISSUE THREAD

**Issue by markonm** [vim/vim#2055]
Version: 8.0.0995
Reproducible on gVim and Vim on Windows and Linux.

Steps to reproduce:
1. `vim --clean -S test.vim`
2. call `AddMatch()` on blank lines

```vim
" test.vim
function! AddMatch() abort
  call matchadd('Search', '\m\%' . getpos('.')[1] . 'l', 100)
  redraw
  return ''
endfunction

```
![55](https://user-images.githubusercontent.com/16160229/30008798-2450e01c-9123-11e7-9e5e-1f9b2554136a.gif)

**Comment by tonymec** [comment]
What does Vim answer to

        :verbose set cul?

? (The question mark after the option name is important).

Best regards,
Tony.

**Comment by markonm** [comment]
It responds with `nocursorline`. I tested with `--clean` option so default settings are being used.

**Comment by chrisbra** [comment]
could this be some kind of optimization, because Vim knows that this particular part does not need to be colored because the cursor will overwrite it? I have been looking into this but couldn't find the root cause for this, it certainly does not seem to be the `win_line` function.

**Comment by markonm** [comment]
If it's an optimization, I think the behavior should be changed. I find it useful to highlight blank lines even if the cursor is currently virtually on top of them. For example, in a plugin I've been writing, I'm highlighting patterns and ranges with matchadd().

![55](https://user-images.githubusercontent.com/16160229/30140032-e7838da0-9371-11e7-9a4d-4a420a6c0951.gif)

You can see how the last blank line is sometimes highlighted and sometimes not, depending on the position of the cursor.

**Comment by markonm** [comment]
This is not an issue anymore. I don't know what patch fixed the issue. Thanks!
