### ISSUE TITLE
hi StatusLineNC... - reversed in gvim

### ISSUE THREAD

**Issue by EvgeniyUS** [vim/vim#2061]
guifg = guibg and guibg = guifg

is it a feature?

**Comment by chrisbra** [comment]
[that](https://github.com/vim/vim/blob/master/src/syntax.c#L6887-L6888) is how StatuslineNC is initialized. However colorschemes can define it as they want. 
However, I don't think this is an actual issue. Please use vim-use ml or vi.stackexchange.com to ask user questions.
