### ISSUE TITLE
autocmd BufEnter * if &buftype=="terminal" | echom "not work" | endif

### ISSUE THREAD

**Issue by tracyone** [vim/vim#2062]
**Not work when enter terminal  for the first time**

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep  3 2017 16:01:39)
MacOS X (unix) version
Included patches: 1-1043
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +comments        +extra_search    +keymap          +mouse_dec       +path_extra      +smartindent     +timers          -X11
+arabic          +conceal         +farsi           +lambda          -mouse_gpm       +perl            +startuptime     +title           -xfontset
+autocmd         +cryptv          +file_in_path    +langmap         -mouse_jsbterm   +persistent_undo +statusline      -toolbar         -xim
-balloon_eval    +cscope          +find_in_path    +libcall         +mouse_netterm   +postscript      -sun_workshop    +user_commands   -xpm
-browse          +cursorbind      +float           +linebreak       +mouse_sgr       +printer         +syntax          +vertsplit       -xsmp
++builtin_terms  +cursorshape     +folding         +lispindent      -mouse_sysmouse  +profile         +tag_binary      +virtualedit     -xterm_clipboard
+byte_offset     +dialog_con      -footer          +listcmds        +mouse_urxvt     +python          +tag_old_static  +visual          -xterm_save
+channel         +diff            +fork()          +localmap        +mouse_xterm     -python3         -tag_any_white   +visualextra     
+cindent         +digraphs        -gettext         -lua             +multi_byte      +quickfix        -tcl             +viminfo         
-clientserver    -dnd             -hangul_input    +menu            +multi_lang      +reltime         +termguicolors   +vreplace        
+clipboard       -ebcdic          +iconv           +mksession       -mzscheme        +rightleft       +terminal        +wildignore      
+cmdline_compl   +emacs_tags      +insert_expand   +modify_fname    +netbeans_intg   +ruby            +terminfo        +wildmenu        
+cmdline_hist    +eval            +job             +mouse           +num64           +scrollbind      +termresponse    +windows         
+cmdline_info    +ex_extra        +jumplist        -mouseshape      +packages        +signs           +textobjects     +writebackup     
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework Cocoa   -mmacosx-version-min=10.12 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.26.0/lib/perl5/5.26.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc -F/usr/local/opt/python/Frameworks -framework Python   -lruby.2.4.1 -lobjc

**Comment by chrisbra** [comment]
currently discussed at https://groups.google.com/d/msg/vim_dev/q0A2My9IhGI/GmzKQYKCDAAJ

**Comment by mattn** [comment]
I want to keep this open since still not merged

**Comment by chrisbra** [comment]
agree.

**Comment by guilala** [comment]
When i use vim8's term, and i :wa in another buffer i get "E676: No matching autocommands for acwrite buffer", i suppose since the terminal buffer can not :w . Is that related to this issue? Or is there another way to avoid acwrite on vim terminals?

**Comment by chrisbra** [comment]
you are actually running into #2190. This one is about the bufenter autocomand not working as expected for terminal mode (at least the first time). Note however, that at least BufWinEnter works now (as given in the documentation).

**Comment by guilala** [comment]
Thanks @chrisbra , 'll use @mattn 's patch in the meantime.

**Comment by chrisbra** [comment]
closing for #2487
