### ISSUE TITLE
Vim installer doesn't seem to create certain subfolders and files in $VIMRUNTIME\macros

### ISSUE THREAD

**Issue by lkintact** [vim/vim#2065]
I installed gvim 8.0.1008 on Windows (with the default set of checkboxes) and found the README.txt file in $VIMRUNTIME\macros that begins with: "The macros in the maze, hanoi and urm directories can be used to test Vim for vi compatibility". 
However there are no such directories anywhere within the $VIM folder (and, consequently, no macro files inside them).
There are hanoi.info, maze.info, urm.info and hanoi.info and README.txt.info files though, but it's not quite clear how to use them.

**Comment by chrisbra** [comment]
I do have those files below $VIMRUNTIME/macros. What installer did you use to install? Where did you install?

**Comment by k-takata** [comment]
It can happen with the official installer and vim-win32-installer.
The folders under the macros folder are missing from the install script:
https://github.com/vim/vim/blob/1b9f9d315f137cc883c7aecd39f3df329b7f9085/nsis/gvim.nsi#L220-L221
The installer installs `macros\*.*`, but it doesn't install `macros\{hanoi,life,maze,urm}\*.*`.

**Comment by lkintact** [comment]
**chrisbra**: I downloaded and run this file: https://github.com/vim/vim-win32-installer/releases/download/v8.0.1008/gvim_8.0.1008_x86.exe, chose the default type of install, which is "Typical" and the default Desination Folder, which is "C:\Program Files\Vim".
I run Windows 7 SP1.

**Comment by chrisbra** [comment]
I see, its about the installer not the zip file version.
