### ISSUE TITLE
Handled errors stop timer

### ISSUE THREAD

**Issue by markonm** [vim/vim#2066]
Version: 8.0.0995
Reproducible on Windows and Linux

Steps to reproduce:
1. `vim --clean -S test.vim`

```vim
" test.vim
let s:count = 1
function! s:foobar(...) abort
  echom s:count
  let s:count += 1
  try
    " produce error
    let baz = search('\{')
  catch
    " do nothing
  endtry
endfunction
if exists('s:timer')
  call timer_stop(s:timer)
  unlet s:timer
endif
let s:timer = timer_start(1000, function('s:foobar'), {'repeat':-1})

```

Even though error message is not displayed, exception is always propagated to timer and as a result timer stops repeating itself after third error.

I'm sorry for the noise if this is intended behavior.

**Comment by mattn** [comment]
it's possible to avoid endless timer like below.

```vim
" test.vim
let s:count = 1
function! s:foobar(...) abort
  echom s:count
  let s:count += 1
  try
    " produce error
    let baz = search('\{')
    let s:timer = timer_start(1000, function('s:foobar'))
  catch
    " do nothing
  endtry
endfunction
if exists('s:timer')
  call timer_stop(s:timer)
  unlet s:timer
endif
let s:timer = timer_start(1000, function('s:foobar'))
```

**Comment by chrisbra** [comment]
that is intended behaviour and documented https://github.com/vim/vim/releases/tag/v8.0.0702

**Comment by brammool** [comment]
The example catches the exception, that should be OK.  I guess some flag is set that isn't cleared in the "catch" block.

**Comment by chrisbra** [comment]
ah I missed that the try/catch should prevent the error.

**Comment by markonm** [comment]
Fixed by https://github.com/vim/vim/commit/e723c42836d971180d1bf9f98916966c5543fff1
Thank you!
