### ISSUE TITLE
arabic.obj was created with an older compiler than other objects

### ISSUE THREAD

**Issue by jiangjianshan** [vim/vim#2078]
Hello,

    I was using VC 2008 x64 compiler inside Windows SDK v7.0 to compile Vim 8.0. But got three errors as follwing:
![1](https://user-images.githubusercontent.com/20179047/30281866-2b5b487e-9746-11e7-8671-7805b0fb3cb7.png)
    The build script I'm using is below. Anything doing wrong when compile Vim 8.0 with latest patch using VC 2008 x64 compiler?

--------------------------------begin ---------------------------------------
@echo off
@rem to build big Vim with OLE, Perl, Python, Ruby and Tcl

set INCLUDE=D:\GnuWin64\include;D:\Lua\include;D:\Ruby\include;%INCLUDE%
set LIB=D:\GnuWin64\lib;D:\Lua\lib;D:\Ruby\lib;%LIB%
set TOOLDIR=D:\
set INSTALL_DIR=D:\Vim
set VIM_SRC_DIR=E:\Gits\vim
set PLUG_MGR=D:\Vim\vimfiles\autoload\plug.vim
::set SDK_INCLUDE_DIR=C:\Program Files\Microsoft SDKs\Windows\v7.0\Include

cd /d %~dp0

@rem uninstall previous version if it exist
if exist %INSTALL_DIR%\Vim80 (
    cd /d %INSTALL_DIR%\Vim80
    uninstal
)

if exist %VIM_SRC_DIR% (
  cd /d %VIM_SRC_DIR%
  git fetch --all
  git reset --hard origin/master
) else (
  echo "Downloading Vim ..."
  git clone https://github.com/vim/vim.git E:\Gits\vim
)

cd /d %VIM_SRC_DIR%\src

if exist .\ObjCULYHTRAMD64 rmdir /s /q .\ObjCULYHTRAMD64
if exist .\ObjGOULYHTRAMD64 rmdir /s /q .\ObjGOULYHTRAMD64

@rem build for no-GUI version
nmake -f Make_mvc.mak CPU=AMD64 FEATURES=HUGE debug=no GUI=no MBYTE=yes IME=yes DYNAMIC_IME=yes GIME=yes CSCOPE=yes ICONV=yes GETTEXT=yes NETBEANS=yes OPTIMIZE=MAXSPEED SNIFF=yes POSCRIPT=yes PERL=%TOOLDIR%Perl DYNAMIC_PERL=yes PERL_VER=524 PYTHON=%TOOLDIR%python27 DYNAMIC_PYTHON=yes PYTHON_VER=27 PYTHON3=%TOOLDIR%python35 DYNAMIC_PYTHON3=yes PYTHON3_VER=35 LUA=%TOOLDIR%Lua DYNAMIC_LUA=yes LUA_VER=53 RUBY=%TOOLDIR%Ruby DYNAMIC_RUBY=yes RUBY_VER=24 RUBY_VER_LONG=2.4.0 RUBY_PLATFORM=x64-mswin64_90 TCL=%TOOLDIR%Tcl TCL_VER=86 TCL_VER_LONG=8.6 DYNAMIC_TCL=yes %1

@rem build for GUI version
nmake -f Make_mvc.mak CPU=AMD64 FEATURES=HUGE debug=no GUI=yes OLE=yes MBYTE=yes IME=yes DYNAMIC_IME=yes GIME=yes CSCOPE=yes ICONV=yes GETTEXT=yes NETBEANS=yes OPTIMIZE=MAXSPEED SNIFF=yes POSCRIPT=yes PERL=%TOOLDIR%Perl DYNAMIC_PERL=yes PERL_VER=524 PYTHON=%TOOLDIR%python27 DYNAMIC_PYTHON=yes PYTHON_VER=27 PYTHON3=%TOOLDIR%python35 DYNAMIC_PYTHON3=yes PYTHON3_VER=35  LUA=%TOOLDIR%Lua DYNAMIC_LUA=yes LUA_VER=53 RUBY=%TOOLDIR%Ruby DYNAMIC_RUBY=yes RUBY_VER=24 RUBY_VER_LONG=2.4.0 RUBY_PLATFORM=x64-mswin64_90 TCL=%TOOLDIR%Tcl TCL_VER=86 TCL_VER_LONG=8.6 DYNAMIC_TCL=yes %1

@rem Copy the "runtime" files into "Vim80"
xcopy /I /Y /F /E ..\.\runtime\* %INSTALL_DIR%\Vim80

@rem Copy the new binaries into the "Vim80" directory
xcopy /I /Y /F *.exe %INSTALL_DIR%\Vim80
xcopy /I /Y /F vimtbar.dll %INSTALL_DIR%\Vim80
xcopy /I /Y /F .\GvimExt\gvimext.dll %INSTALL_DIR%\Vim80
xcopy /I /Y /F .\xxd\xxd.exe %INSTALL_DIR%\Vim80

@rem Copy vimtutor into "Vim80"
xcopy /I /Y /F ..\vimtutor.* %INSTALL_DIR%\Vim80

@rem install vim
cd /d %INSTALL_DIR%\Vim80
::install -install-popup -install-openwith -add-start-menu -install-icons -create-directories vim -register-OLE
::del /F /S /Q "C:\Users\public\Desktop\gVim Easy 8.0.lnk"
::del /F /S /Q "C:\Users\public\Desktop\gVim Read only 8.0.lnk"

install

xcopy /F /Y E:\Releases\_vimrc %INSTALL_DIR%
xcopy /F /Y E:\Releases\.ycm_extra_conf.py %INSTALL_DIR%

@rem Update the plugins

if exist %PLUG_MGR% (
   vim +PlugUpgrade +qall
   vim +PlugUpdate +qall
) else (
   curl -fLo %INSTALL_DIR%\vimfiles\autoload\plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
   vim +PlugInstall +qall
)

cd /d %~dp0
--------------------------------------- end -----------------------------------

**Comment by k-takata** [comment]
Which version of Tcl do you use?
Recently I tried to use ActiveTcl 8.6.6 with VC2010, and faced the same error message. Actually the message was really confusing, because the cause was that the Tcl library (tclstub86.lib) was built by VC2015, not arabic.obj was built by an old compiler.

If this is the case, there are (at least) two options:

1. Disable Tcl, or
2. Use VC2015 or later.

**Comment by jiangjianshan** [comment]
@k-takata , The issue is not exist if I use VC2010 x64 compiler which is inside Windows SDK 7.1. Thanks for your hint. I have just recompiled the Tcl library using VC2008 x64 compiler which is inside Windows SDK 7.0.   After compare the different from the previous Tcl library and the current new one. I have found the previous one is compiled by VC2010. So now I use the new Tcl library which compiled by VC2008. The issue has been solved. Thanks very much again.

**Comment by brammool** [comment]
Ken Takata wrote:

> Which version of Tcl do you use?
> Recently I tried to use ActiveTcl 8.6.6 with VC2010, and faced the same error message. Actually the message was really confusing, because the cause was that the Tcl library (tclstub86.lib) was built by VC2015, not arabic.obj was built by an old compiler.
> 
> If this is the case, there are (at least) two options:
> 
> 1. Disable Tcl, or
> 2. Use VC2015 or later.

I am still using the VC2008 setup, which was needed when we still
supported Windows 95/98.  Now that the oldest we support is Windows XP,
a newer compiler should work.  What is the most reliable version which
still fully supports Windows XP?  

-- 
hundred-and-one symptoms of being an internet addict:
104. When people ask about the Presidential Election you ask "Which country?"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
VC2010 is the easiest version (if we don't need if_tcl). I had tested by
myself that the binary built by VC2010 could work on XP.

After VC2012, we need some extra settings for targeting XP as it is written in
src/INSTALLpc.txt:
https://github.com/vim/vim/blob/b984b80cd835a483bdca1928bc50eb09b071f373/src/INSTALLpc.txt#L120-L141

Recently, I have updated vim-win32-installer to use VC2015 with these settings,
because ActiveTcl 8.6.6 requires VC2015, however I haven't tested whether the
binary actually works on XP.

(BTW, I think VC2005 is the latest version which supports targeting Windows 95/98.)

**Comment by brammool** [comment]
Ken Takata wrote:

> VC2010 is the easiest version (if we don't need if_tcl). I had tested by
> myself that the binary built by VC2010 could work on XP.
> 
> After VC2012, we need some extra settings for targeting XP as it is written in
> src/INSTALLpc.txt:
> https://github.com/vim/vim/blob/b984b80cd835a483bdca1928bc50eb09b071f373/src/INSTALLpc.txt#L120-L141
> 
> Recently, I have updated vim-win32-installer to use VC2015 with these settings,
> because ActiveTcl 8.6.6 requires VC2015, however I haven't tested whether the
> binary actually works on XP.
> 
> (BTW, I think VC2005 is the latest version which supports targeting
> Windows 95/98.)

I didn't have a machine to check, but I thought 2008 also worked.

Anyway, let's aim for using VC2015.  It appears VC2012 requires the same
changes and is just older.

Can you make patch for the MSVC build file to use VC2015 by default?
I suppose the extra arguments don't work for MSVC before 2012, thus we
should make that an option.  "OLD_MSVC=yes"?

-- 
hundred-and-one symptoms of being an internet addict:
111. You and your friends get together regularly on IRC, even though
     all of you live in the same city.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
I think that such kind of setting should be done in `src/msvc2015.bat` or `src/bigvim(64).bat` (should be `hugevim` instead of `bigvim` now?).
Do we still need a patch for `src/Make_mvc.mak`?

**Comment by brammool** [comment]
Ken Takata wrote:

> I think that such kind of setting should be done in `src/msvc2015.bat`
> or `src/bigvim(64).bat` (should be `hugevim` instead of `bigvim`
> now?).
> Do we still need a patch for `src/Make_mvc.mak`?

Not sure.  So can you make a version of msvc2008.bat for VS2015?
I wonder if we need separate ones for 32 bit or 64 Windows.
Or 32 and 64 bit builds.

The default should still be to build a 32 bit executable for Windows XP.
AFAIK that should run just about everywhere.

-- 
hundred-and-one symptoms of being an internet addict:
128. You can access the Net -- via your portable and cellular phone.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
