### ISSUE TITLE
noautocmd does not work with CursorMoved and wincmd

### ISSUE THREAD

**Issue by airblade** [vim/vim#2084]
Steps to reproduce:

```
[1]  $ vim -u NONE -N -c "autocmd CursorMoved * echo 'buf '.bufnr('')" -o file1 file2
[2]  :wincmd j
[3]  j
[4]  :wincmd p
[5]  :noautocmd wincmd p
```

1. Open vim with two existing files.
2. Jump to lower window.
3. Move cursor (so `CursorMoved` is fired when we jump back to previous window). `buf 2` is echoed.
4. Jump to previous window. `buf 1` is echoed.
5. Jump to previous window.  Expected: nothing echoed.  Actual: `buf 2` is echoed.

I'm using MacVim 8.0.586 via Homebrew.

**Comment by airblade** [comment]
(As an aside, step 3 above surprises me: I expected `CursorMoved` to fire only when the cursor is moved within a window.  Evidently though `CursorMoved` is fired when either the line number or column number changes, regardless of which window you are in.)

**Comment by Olical** [comment]
I'm hitting this issue in Neovim for https://github.com/Olical/conjure too, not sure if there's a workaround or not.

**Comment by andymass** [comment]
Unlike many other autocmds, CursorMoved is triggered inside vim's main loop.  This means in particular, that noautocmd has already "gone out of scope" by the time CursorMoved happens.  Additionally, the code indeed does not check which window you are in, it only looks at lnum and col.

@Olical , if you need to reliably know when the cursor switches between windows, you should use WinEnter.  Regarding noautocmd, you'll have to implement your own ignore logic.

**Comment by airblade** [comment]
@andymass Thanks for the info.
