### ISSUE TITLE
Vim changes modeline automatically

### ISSUE THREAD

**Issue by PtkP** [vim/vim#2094]
Hi,

I have recently installed vim version 8.0.1107.
I work with modeline feature. 
Example:

# vim: set tabstop=4 shiftwidth=4 expandtab filetype=perl

Let's say I will open the file with vim, it automatically changes the line to:
# vim: set tabstop=3 shiftwidth=4 expandtab filetype=perl

If I save the file and open it again it changes to:
# vim: set tabstop=2 shiftwidth=4 expandtab filetype=perl

And so on, Any idea?

Thank You,
Patrick Pereira

**Comment by chrisbra** [comment]
sounds like a misbehaving plugin. Does it happen if you start from `vim --clean`?

**Comment by PtkP** [comment]
Yes. it happens.

**Comment by k-takata** [comment]
Looks like something similar with #2003 happens.
Which terminal emulator do you use? What is the result of `:echo v:termresponse`?

**Comment by mattn** [comment]
@chrisbra Is this related on https://github.com/vim/vim/issues/2003 ?

**Comment by mattn** [comment]
Oh, I lost the race.

**Comment by PtkP** [comment]
The result of ":echo v:termresponse" is : ^[[>0;253;0c
I use bash

**Comment by mattn** [comment]
@PtkP What terminal do you use? and `echo $TERM` ?

**Comment by PtkP** [comment]
$TERM=xterm-256color

**Comment by mattn** [comment]
What terminal?

**Comment by PtkP** [comment]
Sorry, missed the question.
I use xterm.

**Comment by chrisbra** [comment]
can you bisect which commit causes this?

**Comment by PtkP** [comment]
I have updated vim version yesterday.
I have this one right now: "patch 8.0.1107: terminal debugger jumps to non-existing file"
Previously I had   version 7.4.1830 

I can try, but it is not an easy task to do. I need to do like a try and error. install a previous version and try.

Best Regards,
Patrick Pereira

**Comment by chrisbra** [comment]
you might want to specifically check 
patch 8.0.1069: still get CTRL-X sometimes
patch 8.0.0993: sometimes an xterm sends an extra CTRL-X

**Comment by chrisbra** [comment]
please check, if https://github.com/vim/vim/releases/tag/v8.0.1128 fixes your problem

**Comment by PtkP** [comment]
Hi all,

I have tested the https://github.com/vim/vim/releases/tag/v8.0.1128.
It works perfectly.

Thanks,
Patrick Pereira
