### ISSUE TITLE
apache_version does not exist anymore, update documentation

### ISSUE THREAD

**Issue by ashemedai** [vim/vim#2100]
In `vim/runtime/doc/syntax.txt` there's a reference to apache_version and it mentions 1.3, the current syntax/apache.vim does not have the variable anymore and it does not support 1.x versions anymore.

My suggestion would be to delete the entire block in the syntax,txt file.

**Comment by chrisbra** [comment]
have you contacted the syntax file maintainer?

**Comment by ashemedai** [comment]
@chrisbra Nope, did not seem relevant at all for this case to be honest.

**Comment by chrisbra** [comment]
ah, this is only about the documentation? Then Bram, can you please include this doc patch:
```patch
diff --git a/runtime/doc/syntax.txt b/runtime/doc/syntax.txt
index 8f887c428..93112c244 100644
--- a/runtime/doc/syntax.txt
+++ b/runtime/doc/syntax.txt
@@ -810,12 +810,8 @@ See |mysyntaxfile-add| for installing script languages permanently.

 APACHE                                         *apache.vim* *ft-apache-syntax*

-The apache syntax file provides syntax highlighting depending on Apache HTTP
-server version, by default for 1.3.x.  Set "apache_version" to Apache version
-(as a string) to get highlighting for another version. Example: >
-
-       :let apache_version = "2.0"
-<
+The apache syntax file provides syntax highlighting for Apache HTTP server
+version 2.2.3.

                *asm.vim* *asmh8300.vim* *nasm.vim* *masm.vim* *asm68k*
 ASSEMBLY       *ft-asm-syntax* *ft-asmh8300-syntax* *ft-nasm-syntax*
`patch

**Comment by chrisbra** [comment]
according to the runtime syntax file, only apache version 2.2.3 is supported. But since the information is quite terse, feel free to remove the whole section, since there does not seem to be any configuration needed for apache anymore.

**Comment by brammool** [comment]
Christian wrote:

> ah, this is only about the documentation? Then Bram, can you please
> include this doc patch:

Thanks!

-- 
The term "free software" is defined by Richard M. Stallman as
being software that isn't necessarily for free.  Confusing?
Let's call it "Stallman software" then!
				-- Bram Moolenaar

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
fixed by https://github.com/vim/vim/commit/01164a6546b4c635daf96a1f17d1cb2d07f32a66
