### ISSUE TITLE
No profile information for first line in file / generate coverage reports

### ISSUE THREAD

**Issue by blueyed** [vim/vim#2103]
Given `t.vim`:
```vim
let foo = 1
let bar = 2
```

Running `vim -N --noplugin --cmd 'profile start prof.out' --cmd 'profile! file **' -u t.vim` results in this `prof.out` file:
```
SCRIPT  /path/to/t.vim
Sourced 1 time
Total time:   0.000009
 Self time:   0.000009

count  total (s)   self (s)
                            let foo = 1
    1              0.000002 let bar = 2

```

The first line should also have profiling information (e.g. a count of 1).

btw: I am looking into using the profiling output to generate coverage reports.
I could not find existing tools / ways to do this already.
Are there any?  Or is there maybe interest to provide this from Vim itself?
I am mostly interested in finding lines that are not executed, so that I can tell if tests for a Vim plugin cover everything.

**Comment by LemonBoy** [comment]
That happens because vim reads the first line of the script before a `SID` is assigned to it, here's a [patch](https://gist.github.com/LemonBoy/d14bb45bfc1f5ff41d4884457120fdfd) that solves the problem.
