### ISSUE TITLE
vim.vim syntax highlighting doesn't seem to properly handle dictionary definition syntax

### ISSUE THREAD

**Issue by suewonjp** [vim/vim#2109]
```
let l:mappings = [
        . . .
        \ { 'lhs':'<leader>{)', 'rhs':' <ESC>A {<CR>}<ESC>A);<ESC>O', },  "  @@@@@
        \ { 'lhs':'<leader>??', 'rhs':' <C-r>=<SID>PasteFromSlashRegister(0)<CR>', },
        \ ]
```

Look at the code above marked with **@@@@@**

**All code above that line is correctly highlighted, but all code below it goes crazy.** 

Some code below the line is correctly highlighted, (e.g., strings or variables). But others such as keywords, comments are not properly colorized.

Commenting that line made everything look all right.

As you noticed, that line contains literal { and }  in value strings inside the dictionary item definition.

I think literal braces in those string values should be ignored, but it looks like the current version of vim.vim (**Last Change:	Jan 19, 2017**) can't ignore them.

**Comment by Hacklin** [comment]
Workaround:
Use a space after the ':' as in:
`{ 'key': 'value' }`

**Comment by suewonjp** [comment]
@Hacklin Thanks. It works

**Comment by Hacklin** [comment]
The vim.vim syntax deliberately checks for a `:` immediately before a literal string
(`:'string'` and `:"string"`) to _not_ do vimString highlighting on the string.

To fix this for a dictionary item you need to make an exception for dictionaries.
So don't expect to get this fixed anytime soon, if ever.

Note that all dictionary documentation uses a space after the `:`.

**Comment by cecamp** [comment]
Hacklin wrote:
>
> The vim.vim syntax deliberately checks for a |:| immediately before a 
> literal string
> (|:'string'| and |:"string"|) to /not/ do vimString highlighting on 
> the string.
>
> To fix this for a dictionary item you need to make an exception for 
> dictionaries.
> So don't expect to get this fixed anytime soon, if ever.
>
> Note that all dictionary documentation uses a space after the |:|.
>
>
On the other hand, you could try out the latest (albeit still 
in-development) version of vim.vim (8.0-03) which addresses this.

Regards,
Chip Campbell

P.S. http://www.drchip.org/astronaut/vim/index.html#SYNTAX_VIM

**Comment by Hacklin** [comment]
I do.
I use Vim master from git (https://github.com/vim/vim.git).

**Comment by chrisbra** [comment]
that's why you should try the upstream version of the vim syntax script available at http://www.drchip.org/astronaut/vim/index.html#SYNTAX_VIM as @cecamp mentioned.

**Comment by chrisbra** [comment]
I think this has been fixed in the meantime. So closing.
