### ISSUE TITLE
Windows (Conhost) - Typographical Emphasis

### ISSUE THREAD

**Issue by thecliguy** [vim/vim#2113]
VT escape sequence support for conhost was introduced in the Windows 10 Anniversary Update:
https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences
Consequently it is now possible manipulate background colour, foreground colour and typographical emphasis (bold and underline), see: https://gist.github.com/thecliguy/c0dbf2eba75c9ecd193de5e871ea216b

The Vim build for Windows appears not to take advantage of this new capability.

The specific feature that I would like to see support for is the ability to highlight text on the current line by underlining it:

&nbsp;&nbsp;&nbsp;&nbsp;Enable highlighting of the line on which the cursor is located:
&nbsp;&nbsp;&nbsp;&nbsp;```:set cursorline```

&nbsp;&nbsp;&nbsp;&nbsp;Clear any existing highlight style:
&nbsp;&nbsp;&nbsp;&nbsp;```:highlight clear CursorLine```

&nbsp;&nbsp;&nbsp;&nbsp;Explicitly set the style of the highlight to underline:
&nbsp;&nbsp;&nbsp;&nbsp;```:highlight CursorLine cterm=underline```

When the example above is run in latest stable build (8.0 with patches 1-586) and the latest nightly build (8.0 with patches 1-1118) of Vim for Windows it changes the background colour instead of underlining.

The example does work as expected when using the [Windows Subsystem for Linux](https://msdn.microsoft.com/en-gb/commandline/wsl/about) (Ubuntu 16.04.2 LTS with Vim  7.4), which serves to demonstrate that conhost is capable of interpreting the VT escape sequence for underlined text and rendering it correctly.

Can support for VT escape sequences be added to a future Windows build? Or at a minimum, can support be added for underlining text on the current line as per the example I provided?

**Comment by k-takata** [comment]
See #2060. @ntak is working on this.
I'm not sure it already supports underline, though.

**Comment by thecliguy** [comment]
@k-takata Thank you. I reviewed #2060 and can see that there is a lot of work related to virtual terminal support. But I was also unable to determine whether this would specifically address the issue of underlined text.

Hopefully someone involved with those changes can comment.

**Comment by thecliguy** [comment]
@k-takata Sorry to disturb you. Do you know when #2060 will be in added to a nightly build? Is it just waiting for the Vim maintainer to accept the pull request?

**Comment by k-takata** [comment]
Yes, I'm just waiting it.

**Comment by thecliguy** [comment]
Closing this issue as the feature has been implemented in [patch 8.0.1531](https://github.com/vim/vim/commit/cafafb381a04e33f3ce9cd15dd9f94b73226831f) which is available in Vim 8.1.

**NB:** Requires `:set termguicolors`
