### ISSUE TITLE
startinsert! leaves cursor at column 1

### ISSUE THREAD

**Issue by wes1138** [vim/vim#2117]
To reproduce:

`$ echo 'asdfasdfasdf' > file`
`$ vim -c 'startinsert!' file`

Then observe that cursor is at column 1, contrary to the documentation (and prior behavior).
This happens with vim built from git yesterday, but also the current version in the Arch Linux repos (8.0.1092).

**Comment by chrisbra** [comment]
can you bisect which commit introduced this behaviour?

**Comment by wes1138** [comment]
Seems to be 6de5e126018b6f92526. Here are the results:
```
6de5e126018b6f92526795cc06b1d73fac965db1 is the first bad commit
commit 6de5e126018b6f92526795cc06b1d73fac965db1
Author: Bram Moolenaar <Bram@vim.org>
Date:   Thu Apr 20 21:55:44 2017 +0200

    patch 8.0.0572: building the command table requires Perl

    Problem:    Building the command table requires Perl.
    Solution:   Use a Vim script solution. (Dominique Pelle, closes #1641)

:100644 100644 5d2b8313ce682118fdc42bd9c654af1f15260763 6d8e2e889623fab45f76f4a4df62ed6abde35a48 M      Filelist
:040000 040000 5e98e7539d7c33ef050ccf581fb0656ca3c6cb77 a92fa51c029081f725be0e3ac8656509b91ddfee M      src

```
*EDIT:* put hash outside of code block for auto link.

**Comment by wes1138** [comment]
I took a look at the diff, but thought maybe @dpelle would be able to figure it out with a lot less effort?

**Comment by chrisbra** [comment]
This was caused by the unrelated change in ex_docmd.c. Posted a patch https://groups.google.com/d/msg/vim_dev/-R-S16N3d9U/CGskQQgBCAAJ
