### ISSUE TITLE
confused rST highlighting

### ISSUE THREAD

**Issue by mcepl** [vim/vim#2118]
Hi,

writing a book in vim using rST as my file format. It seems to me that unfortunately highlighting of *emphasized text* is very easily broken by just a little bit more weird characters. See the attached screenshot:

![highlighting](https://user-images.githubusercontent.com/198999/30533809-8c9d5d24-9c5b-11e7-97b5-515af6adcf8e.png)

It is vim ``8.0.1111`` on RHEL-7 using Gtk3 GUI.

**Comment by chrisbra** [comment]
did you contact the syntax file maintainer?

**Comment by mcepl** [comment]
Right. @marshallward, any thoughts?

**Comment by marshallward** [comment]
Can you repost this at [vim-restructuredtext](https://github.com/marshallward/vim-restructuredtext) repository, with the included text (rather than a screenshot)?  Is the issue just non-ASCII characters in emphasis?  There's a chance that this has already been fixed but has not yet been sent to Bram.

**Comment by mcepl** [comment]
> (rather than a screenshot)

??? How can I show in text that highlighting doesn't work. It doesn't make sense. The point is that the second emphasis (“Médecins Sans Frontières”) are highlighted in different way than the first one (“Magiciens sans frontières”), although they should be same, IMHO.

Hmm, it is even more weird on in xterm-emulator:
![xterm_highlight](https://user-images.githubusercontent.com/198999/30566191-4ec4c9a4-9ccb-11e7-94b3-0338604bb717.png)

Example text which I can use to reproduce the bug, 
[14_godric_hollow.rst.txt](https://github.com/vim/vim/files/1312383/14_godric_hollow.rst.txt)

**Comment by mcepl** [comment]
I can reproduce the same issue even if I install ``vim-restructuredtext`` repository to ``~/.vim/pack/thirdparty/start/vim-restructuredtext/`` among other plugins. However, I am not sure which syntax file gets precedence: the one from ``/usr/share/vim/vim80/syntax`` or the other one? Hmm, so I can reproduce even when rename ``/usr/share/vim/vim80/syntax/rst.vim`` to ``rst.vim.orig``.

**Comment by marshallward** [comment]
In the future, it's probably better to keep this discussion in the syntax file repo, rather than the main Vim repo.  But hopefully we can resolve this quickly.

There's something unusual about your whitespace.  If I replace the leading space-like character with a normal whitespace, then it works fine.  So I wonder if you are using a non-ASCII space character?  Is this possible?

**Comment by marshallward** [comment]
Regarding your second point, the vim-restructuredtext version is newer than the version bundled with Vim.  

Currently I send updates to Bram when the changes seem significant, but the schedule for updates is inconsistent and the threshhold for "significant" is not well-defined.  This probably needs to be cleared up.

I don't know what the `.vim/pack` directory is for, but `.vim` generally has precedence over `/usr/share/vim`.

**Comment by marshallward** [comment]
Updating my previous comment:
Most of your spaces are standard ASCII (20) spaces, but a few, particularly those prior to the emphasis, are ISO-8859 non-breaking spaces (A0), presumably some word processing thing to prevent line breaks around emphasised words.

I'm not sure if this is something reST should support or not, I need to check the standard.  I don't see a problem with it, but I also don't know how difficult it is to support these characters in vimL.

Let's summarise this and move it to the other issue on vim-restructuredtext?

**Comment by chrisbra** [comment]
closig then.

**Comment by mcepl** [comment]
> I don't know what the .vim/pack directory is for,

@marshallward  https://shapeshed.com/vim-packages/ … vim8 has native replacement for Pathogen et al.
