### ISSUE TITLE
patch 8.0.1073 break redrawing

### ISSUE THREAD

**Issue by mattn** [vim/vim#2120]
[patch 8.0.1073](https://github.com/vim/vim/commit/ba2929b6afd2fc20479912a8dec789be26a38244) breaks redrawing.

min_vimrc
```vim
let s:s = 1
function! Sample()
    highlight StatusLine cterm=NONE gui=NONE ctermfg=Black guifg=Black ctermbg=Magenta guibg=Magenta
    let s:s += 1
    return s:s
endfunction
set statusline=%{Sample()}
```

test.txt
```
1
12
123
1234
12345
123456
1234567
12345678
123456789
1234567890
1
12
123
1234
12345
123456
1234567
12345678
123456789
1234567890
1
12
123
1234
12345
123456
1234567
12345678
123456789
1234567890
```

```
$ vim -Nu min_vimrc test.txt
```

And type below.
```
L$:vs<C-w><C-w>j<C-w><C-w>j
```

![shoei](https://user-images.githubusercontent.com/10111/30542760-8e044a96-9cbb-11e7-967d-2797d706bf56.gif)

**Comment by mattn** [comment]
I think we should save only w_redr_type.

```diff
diff --git a/src/buffer.c b/src/buffer.c
index 7040bb100..dc1db5a49 100644
--- a/src/buffer.c
+++ b/src/buffer.c
@@ -3908,9 +3908,7 @@ build_stl_str_hl(
     char_u	tmp[TMPLEN];
     char_u	*usefmt = fmt;
     struct stl_hlrec *sp;
-    int		save_must_redraw = must_redraw;
     int		save_redr_type = curwin->w_redr_type;
-    int		save_highlight_shcnaged = need_highlight_changed;
 
 #ifdef FEAT_EVAL
     /*
@@ -4686,9 +4684,7 @@ build_stl_str_hl(
     /* We do not want redrawing a stausline, ruler, title, etc. to trigger
      * another redraw, it may cause an endless loop.  This happens when a
      * statusline changes a highlight group. */
-    must_redraw = save_must_redraw;
     curwin->w_redr_type = save_redr_type;
-    need_highlight_changed = save_highlight_shcnaged;
 
     return width;
 }
```

**Comment by brammool** [comment]
Yasuhiro wrote:

> [patch 8.0.1073](https://github.com/vim/vim/commit/ba2929b6afd2fc20479912a8dec789be26a38244) breaks redrawing.
> 
> min_vimrc
> ```vim
> let s:s = 1
> function! Sample()
>     highlight StatusLine cterm=NONE gui=NONE ctermfg=Black guifg=Black ctermbg=Magenta guibg=Magenta
>     let s:s += 1
>     return s:s
> endfunction
> set statusline=%{Sample()}
> ```
> 
> test.txt
> ```
> 1
> 12
> 123
> 1234
> 12345
> 123456
> 1234567
> 12345678
> 123456789
> 1234567890
> 1
> 12
> 123
> 1234
> 12345
> 123456
> 1234567
> 12345678
> 123456789
> 1234567890
> 1
> 12
> 123
> 1234
> 12345
> 123456
> 1234567
> 12345678
> 123456789
> 1234567890
> ```
> 
> ```
> $ vim -Nu min_vimrc test.txt
> ```
> 
> And type below.
> ```
> L$:vs<C-w><C-w>j<C-w><C-w>j
> ```
> 
> ![shoei](https://user-images.githubusercontent.com/10111/30542760-8e044a96-9cbb-11e7-967d-2797d706bf56.gif)

I cannot reproduce it.  Anything else that matters?

-- 
hundred-and-one symptoms of being an internet addict:
157. You fum through a magazine, you first check to see if it has a web
     address.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ichizok** [comment]
@brammool You can probably reproduce using this patch.

```diff
--- a/src/syntax.c
+++ b/src/syntax.c
@@ -7982,11 +7982,12 @@ do_highlight(
                {
                    HL_TABLE()[idx].sg_gui_fg = i;
 # endif
-                   vim_free(HL_TABLE()[idx].sg_gui_fg_name);
+                   p = HL_TABLE()[idx].sg_gui_fg_name;
                    if (STRCMP(arg, "NONE") != 0)
                        HL_TABLE()[idx].sg_gui_fg_name = vim_strsave(arg);
                    else
                        HL_TABLE()[idx].sg_gui_fg_name = NULL;
+                   vim_free(p);
 # if defined(FEAT_GUI) || defined(FEAT_TERMGUICOLORS)
 #  ifdef FEAT_GUI_X11
                    if (is_menu_group)
```

This patch intends to allocate new address differed from freed address.
Because, as far as I confirmed;

```c
vim_free(HL_TABLE()[idx].sg_gui_fg_name);  // (1): freed address
if (STRCMP(arg, "NONE") != 0)
    HL_TABLE()[idx].sg_gui_fg_name = vim_strsave(arg); // (2): new allocated address
```

Even if new arg is same as old one, `HL_TABLE()[idx].sg_gui_fg_name` will freed and allocated,

on macOS: (1) != (2) 
on Ubuntu: (1) == (2)

When (1) != (2),  https://github.com/vim/vim/blob/0b05e49/src/syntax.c#L8231-L8239

```c
    if (memcmp(&HL_TABLE()[idx], &item_before, sizeof(item_before)) != 0
#if defined(FEAT_GUI) || defined(FEAT_TERMGUICOLORS)
            && !did_highlight_changed
#endif
       )
    {
        redraw_all_later(NOT_VALID);
        need_highlight_changed = TRUE;
    }
```

this `memcmp != 0` so `curwin->w_lines_valid` is set to 0 in `redraw_all_later`, but `must_redraw` is restored to `save_must_redraw` later.
Therefore necessary screen-redrawn is not done.

I think:

* do not update (free and alloc) value when new arg == old arg
* do freeing after allocation in order to allocate different address when new arg != old arg
* do not save and restore `must_redraw` and `need_highlight_changed`

**Comment by brammool** [comment]
Ozaki Kiichi wrote:

> @brammool You can probably reproduce using this patch.
> 
> ```diff
> --- a/src/syntax.c
> +++ b/src/syntax.c
> @@ -7982,11 +7982,12 @@ do_highlight(
>                 {
>                     HL_TABLE()[idx].sg_gui_fg = i;
>  # endif
> -                   vim_free(HL_TABLE()[idx].sg_gui_fg_name);
> +                   p = HL_TABLE()[idx].sg_gui_fg_name;
>                     if (STRCMP(arg, "NONE") != 0)
>                         HL_TABLE()[idx].sg_gui_fg_name = vim_strsave(arg);
>                     else
>                         HL_TABLE()[idx].sg_gui_fg_name = NULL;
> +                   vim_free(p);
>  # if defined(FEAT_GUI) || defined(FEAT_TERMGUICOLORS)
>  #  ifdef FEAT_GUI_X11
>                     if (is_menu_group)
> ```
> 
> This patch intends to allocate new address differed from freed address.
> Because, as far as I confirmed;
> 
> ```c
> vim_free(HL_TABLE()[idx].sg_gui_fg_name);  // (1): freed address
> if (STRCMP(arg, "NONE") != 0)
>     HL_TABLE()[idx].sg_gui_fg_name = vim_strsave(arg); // (2): new allocated address
> ```
> 
> Even if new arg is same as old one, `HL_TABLE()[idx].sg_gui_fg_name` will freed and allocated,
> 
> on macOS: (1) != (2) 
> on Ubuntu: (1) == (2)
> 
> When (1) != (2),  https://github.com/vim/vim/blob/0b05e49/src/syntax.c#L8231-L8239
> 
> ```c
>     if (memcmp(&HL_TABLE()[idx], &item_before, sizeof(item_before)) != 0
> #if defined(FEAT_GUI) || defined(FEAT_TERMGUICOLORS)
>             && !did_highlight_changed
> #endif
>        )
>     {
>         redraw_all_later(NOT_VALID);
>         need_highlight_changed = TRUE;
>     }
> ```
> 
> this `memcmp != 0` so `curwin->w_lines_valid` is set to 0 in `redraw_all_later`, but `must_redraw` is restored to `save_must_redraw` later.
> Therefore necessary screen-redrawn is not done.
> 
> I think:
> 
> * do not update (free and alloc) value when new arg == old arg
> * do freeing after allocation in order to allocate different address when new arg != old arg
> * do not save and restore `must_redraw` and `need_highlight_changed`

Yeah, we should check if the name actually changed before saving and
making a new copy.

-- 
Some of the well known MS-Windows errors:
	ESLEEP		Operator fell asleep
	ENOERR		No error yet
	EDOLLAR		OS too expensive
	EWINDOWS	MS-Windows loaded, system in danger

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ichizok** [comment]
Thank you, but this is not enough fix.
When highlight changes from last-statusline, screen doesn't update. 

min_vimrc:

```vim
let s:s = 0
function! Sample()
  if s:s % 2 == 0
    highlight StatusLine cterm=NONE gui=NONE ctermfg=Black guifg=Black ctermbg=Magenta guibg=Magenta
  else
    highlight StatusLine cterm=NONE gui=NONE ctermfg=Black guifg=Black ctermbg=Cyan guibg=Cyan
  endif
  let s:s += 1
  return s:s
endfunction
set statusline=%{Sample()}
```

expected (8.0.1072)

![issue2120-1](https://user-images.githubusercontent.com/943423/31036494-659a21a8-a5a7-11e7-8313-864a3e5c666b.gif)

actual (8.0.1146)

![issue2120](https://user-images.githubusercontent.com/943423/31036500-6e893178-a5a7-11e7-96aa-28c4a47ca007.gif)

**Comment by brammool** [comment]
Ozaki Kiichi wrote:

> Thank you, but this is not enough fix.
> When highlight changes from last-statusline, screen doesn't update. 
> 
> min_vimrc:
> 
> ```vim
> let s:s = 0
> function! Sample()
>   if s:s % 2 == 0
>     highlight StatusLine cterm=NONE gui=NONE ctermfg=Black guifg=Black ctermbg=Magenta guibg=Magenta
>   else
>     highlight StatusLine cterm=NONE gui=NONE ctermfg=Black guifg=Black ctermbg=Cyan guibg=Cyan
>   endif
>   let s:s += 1
>   return s:s
> endfunction
> set statusline=%{Sample()}
> ```
> 
> expected (8.0.1072)
> 
> ![issue2120-1](https://user-images.githubusercontent.com/943423/31036494-659a21a8-a5a7-11e7-8313-864a3e5c666b.gif)
> 
> actual (8.0.1146)
> 
> ![issue2120](https://user-images.githubusercontent.com/943423/31036500-6e893178-a5a7-11e7-96aa-28c4a47ca007.gif)

Works fine for me.

Please keep in mind that changing highlighting inside 'statusline' is a
bad hack, we avoid a hang but I don't really care much if it doesn't
work well.

-- 
hundred-and-one symptoms of being an internet addict:
237. You tattoo your email address on your forehead.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ichizok** [comment]
> Please keep in mind that changing highlighting inside 'statusline' is a
> bad hack, we avoid a hang but I don't really care much if it doesn't
> work well.

I understand. Thank you.
