### ISSUE TITLE
ruby syntax highlight failure for large files on macOS terminal vim but not on GVim

### ISSUE THREAD

**Issue by JESii** [vim/vim#2123]
I'm running macOS Sierra and use both GVim and terminal vim
Gvim version 
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 13 2017 04:07:30)
MacOS X (unix) version
Included patches: 1-1098  
```
Terminal version:
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 14 2017 18:28:18)
MacOS X (unix) version via HomeBrew
Included patches: 1-1100
```
For large files (one example is 1071 lines long, another 1564 lines), 
* syntax highlighting is completely lost when using 'G' to goto to the bottom of the file form the first line
* If CTRL-F through the file from beginning to end, syntax highlighting is maintained
* If CTRL-F from beginning to end, then 'gg', and 'G', syntax highlighting is USUALLY maintained, although sometimes it stops part-way through

The default syntax setting is:
`syncing starts 500 lines before top line`

The bad behavior persists, even when I set:
`syntax sync fromstart`

**Comment by chrisbra** [comment]
please contact the syntax file maintainer, IIRC this is https://github.com/vim-ruby/vim-ruby

**Comment by JESii** [comment]
K; thanks!
