### ISSUE TITLE
Windows: vimgrep stops throwing exceptions despite no match

### ISSUE THREAD

**Issue by FocusedWolf** [vim/vim#2125]
I tested my .vimrc on Linux gVim and found no issue, but Windows gVim behaves strangely :)
# Steps to recreate issue:
    1. Create a .vimrc that consists only of the two functions listed at the bottom of this post.
       One function is a workaround (i found that disabling the outtermost try-catch allowed the function to work as expected, but its still strange because if the outtermost catch is catching the exception then why isn't the catch block being executed... Anyway like i said, this issue affects Windows gVim but not Linux gVim, so insanity follows.

    2. Open any text file.

    3. Run the following functions:
       :call TestBug()
       :call TestWorks()
# Output which i received:
## gVim Windows output:
        :call TestBug()

        inner: Vim(lvimgrep):E480: No match: asdf1234
        match 0
        match 1
        match 1

        :call TestWorks()

        inner: Vim(lvimgrep):E480: No match: asdf1234
        match 0
        inner: Vim(lvimgrep):E480: No match: asdf1234
        match 0
        inner: Vim(lvimgrep):E480: No match: asdf1234
        match 0
## gVim Linux output:
        :call TestBug()

        inner: Vim(lvimgrep):E480: No match: asdf1234
        match: 0
        inner: Vim(lvimgrep):E480: No match: asdf1234
        match: 0
        inner: Vim(lvimgrep):E480: No match: asdf1234
        match: 0

        :call TestWorks()

        inner: Vim(lvimgrep):E480: No match: asdf1234
        match: 0
        inner: Vim(lvimgrep):E480: No match: asdf1234
        match: 0
        inner: Vim(lvimgrep):E480: No match: asdf1234
        match: 0
## My .vimrc:
    function! TestBug()
        let pattern = 'asdf1234'
        let str = 'lvimgrep /' . pattern . '/g ' . fnameescape(bufname("%"))

        try
            let i = 0
            while i < 3
                let i = i+1

                " NOTE: On Windows, this next try-catch only works when the outside try-catch is disabled,
                "       but on Linux, this same code works.

                let match = 1
                try
                    execute(str)
                catch /.*/
                    let match = 0
                    echomsg 'inner: ' . v:exception
                endtry

                echomsg 'match: ' . match
            endwhile
        catch /.*/
            echomsg 'outter: ' . v:exception
        endtry
    endfunction

    function! TestWorks()
        let pattern = 'asdf1234'
        let str = 'lvimgrep /' . pattern . '/g ' . fnameescape(bufname("%"))

        " NOTE: On Windows this try-catch has to be disabled for the inner try-catch to work,
        "       but disabling this is not needed for this to work on Linux.

        "try
            let i = 0
            while i < 3
                let i = i+1

                let match = 1
                try
                    execute(str)
                catch /.*/
                    let match = 0
                    echomsg 'inner: ' . v:exception
                endtry

                echomsg 'match: ' . match
            endwhile
        "catch /.*/
        "    echomsg 'outter: ' . v:exception
        "endtry
    endfunction

**Comment by vim-ml** [comment]
2017-09-19 3:19 GMT+03:00 FocusedWolf <vim-dev-github@256bit.org>:
> I tested my .vimrc on Linux gVim and found no issue, but Windows gVim
> behaves strangely :)

With the nature of the issue it is highly unlikely that linux/Windows
makes any difference in this regard. What are versions in both cases?

**Comment by FocusedWolf** [comment]
Windows:
    VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 12 2016 18:25:27)
Linux:
    VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 31 2017 10:00:16)

When i tested on another machine with latest vim i noticed the issue went away, so i guess this bug was already fixed (doh). Anyway it works on Windows build - VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 23 2017 20:01:28). Vim needs auto update :D
