### ISSUE TITLE
cannot open input file 'C:\ActiveTcl\lib\tcl86vc.lib' on vs 2017

### ISSUE THREAD

**Issue by kuh3h3** [vim/vim#2128]
maybe activetcl have no tcl86vc.lib? there is tcl86t.lib

        link  /nologo /subsystem:console /LTCG:STATUS -out:vim.exe .\ObjCXOLYHTAMD64\arabic.obj  .\ObjCXOLYHTAMD64\blowfish.obj  .\ObjCXOLYHTAMD64\buffer.obj  .\ObjCXOLYHTAMD64\charset.obj  .\ObjCXOLYHTAMD64\crypt.obj  .\ObjCXOLYHTAMD64\crypt_zip.obj  .\ObjCXOLYHTAMD64\dict.obj  .\ObjCXOLYHTAMD64\diff.obj  .\ObjCXOLYHTAMD64\digraph.obj  .\ObjCXOLYHTAMD64\edit.obj  .\ObjCXOLYHTAMD64\eval.obj  .\ObjCXOLYHTAMD64\evalfunc.obj  .\ObjCXOLYHTAMD64\ex_cmds.obj  .\ObjCXOLYHTAMD64\ex_cmds2.obj  .\ObjCXOLYHTAMD64\ex_docmd.obj  .\ObjCXOLYHTAMD64\ex_eval.obj  .\ObjCXOLYHTAMD64\ex_getln.obj  .\ObjCXOLYHTAMD64\farsi.obj  .\ObjCXOLYHTAMD64\fileio.obj  .\ObjCXOLYHTAMD64\fold.obj  .\ObjCXOLYHTAMD64\getchar.obj  .\ObjCXOLYHTAMD64\hardcopy.obj  .\ObjCXOLYHTAMD64\hashtab.obj  .\ObjCXOLYHTAMD64\json.obj  .\ObjCXOLYHTAMD64\list.obj  .\ObjCXOLYHTAMD64\main.obj  .\ObjCXOLYHTAMD64\mark.obj  .\ObjCXOLYHTAMD64\mbyte.obj  .\ObjCXOLYHTAMD64\memfile.obj  .\ObjCXOLYHTAMD64\memline.obj  .\ObjCXOLYHTAMD64\menu.obj  .\ObjCXOLYHTAMD64\message.obj  .\ObjCXOLYHTAMD64\misc1.obj  .\ObjCXOLYHTAMD64\misc2.obj  .\ObjCXOLYHTAMD64\move.obj  .\ObjCXOLYHTAMD64\normal.obj  .\ObjCXOLYHTAMD64\ops.obj  .\ObjCXOLYHTAMD64\option.obj  .\ObjCXOLYHTAMD64\os_mswin.obj  .\ObjCXOLYHTAMD64\winclip.obj  .\ObjCXOLYHTAMD64\os_win32.obj  .\ObjCXOLYHTAMD64\pathdef.obj  .\ObjCXOLYHTAMD64\popupmnu.obj  .\ObjCXOLYHTAMD64\quickfix.obj  .\ObjCXOLYHTAMD64\regexp.obj  .\ObjCXOLYHTAMD64\screen.obj  .\ObjCXOLYHTAMD64\search.obj  .\ObjCXOLYHTAMD64\sha256.obj  .\ObjCXOLYHTAMD64\spell.obj  .\ObjCXOLYHTAMD64\spellfile.obj  .\ObjCXOLYHTAMD64\syntax.obj  .\ObjCXOLYHTAMD64\tag.obj  .\ObjCXOLYHTAMD64\term.obj  .\ObjCXOLYHTAMD64\ui.obj  .\ObjCXOLYHTAMD64\undo.obj  .\ObjCXOLYHTAMD64\userfunc.obj  .\ObjCXOLYHTAMD64\window.obj  .\ObjCXOLYHTAMD64\vim.res .\ObjCXOLYHTAMD64\dimm_i.obj .\ObjCXOLYHTAMD64\glbl_ime.obj  .\ObjCXOLYHTAMD64\iscygpty.obj .\ObjCXOLYHTAMD64\if_ole.obj    .\ObjCXOLYHTAMD64\if_perl.obj .\ObjCXOLYHTAMD64\if_perlsfio.obj .\ObjCXOLYHTAMD64\if_python.obj .\ObjCXOLYHTAMD64\if_python3.obj   .\ObjCXOLYHTAMD64\if_tcl.obj .\ObjCXOLYHTAMD64/if_cscope.obj .\ObjCXOLYHTAMD64/terminal.obj  .\ObjCXOLYHTAMD64/term_encoding.obj  .\ObjCXOLYHTAMD64/term_keyboard.obj  .\ObjCXOLYHTAMD64/term_mouse.obj  .\ObjCXOLYHTAMD64/term_parser.obj  .\ObjCXOLYHTAMD64/term_pen.obj  .\ObjCXOLYHTAMD64/term_screen.obj  .\ObjCXOLYHTAMD64/term_state.obj  .\ObjCXOLYHTAMD64/term_unicode.obj  .\ObjCXOLYHTAMD64/term_vterm.obj  .\ObjCXOLYHTAMD64/channel.obj   .\ObjCXOLYHTAMD64\version.obj oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib uuid.lib /machine:AMD64   libcmt.lib oleaut32.lib user32.lib    C:\perl64\Lib\Core\libperl524.a /nodefaultlib:python27.lib /nodefaultlib:python36.lib   C:\ActiveTcl\lib\tcl86vc.lib WSock32.lib  /PDB:vim.pdb -debug
LINK : fatal error LNK1181: cannot open input file 'C:\ActiveTcl\lib\tcl86vc.lib'
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.11.25503\bin\HostX64\x64\link.EXE"' : return code '0x49d'
Stop.

**Comment by k-takata** [comment]
Building with `DYNAMIC_TCL=no` might not be maintained recently.
Please try with `DYNAMIC_TCL=yes`.

**Comment by kuh3h3** [comment]
thanks
