### ISSUE TITLE
setlocal hi CursorLineNr guibg and guifg

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vim/vim#213]
```
It would be nice to have CursorLineNr local to a buffer.

The use case is having the color based on the position in current buffer. 
Example:
  Green begin in buffer, red at end...

https://bitbucket.org/xgo/dotvim/src/a7dd606e72cdac1b9b1b310fa34c194a7893950b/_v
imrc?at=default#cl-212

```

Original issue reported on code.google.com by `dusan.sm...@gmail.com` on 3 Apr 2014 at 12:16

**Comment by chrisbra** [comment]
I think this can be achieved by using a CursorMoved autocommand. For buffer/window local highlighting groups, see https://github.com/vim/vim/issues/3576
