### ISSUE TITLE
Vim 8.0.1129 fails to compile: make[1]: *** No rule to make target 'terminal.c', needed by 'objects/terminal.o'.  Stop.

### ISSUE THREAD

**Issue by fusion809** [vim/vim#2131]
Hi,

On Arch Linux and Gentoo Linux Vim fails to compile with the error:

```bash
make[1]: *** No rule to make target 'terminal.c', needed by 'objects/terminal.o'.  Stop.
```
full log is [here](https://github.com/vim/vim/files/1315796/build-log.txt). Vim 8.0.1127 built fine, however.

Thanks for your time

**Comment by yowcow** [comment]
https://github.com/vim/vim/commit/37c64c78fd87e086b5a945ad7032787c274e2dcb#diff-f83301fc7928a73575f006ec59a872b6

It seems like terminal.c has disappeared in v8.0.1129

**Comment by ahuang05** [comment]
Concur with yowcow.

**Comment by fusion809** [comment]
So how do I get Vim to build?

**Comment by chrisbra** [comment]
this was just fixed.

**Comment by fusion809** [comment]
Oh good.

**Comment by chrisbra** [comment]
BTW: in the meantime you could have done something like this.

checkout terminal.c from the previous commit (do that in the src directory):
```git show v8.0.1128:src/terminal.c > terminal.c```

You could even put that in your Makefile (I did so to fix this termporary):
```patch
diff --git a/src/Makefile b/src/Makefile
index db9e72508..abf4d257c 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -1523,6 +1523,9 @@ DEST_MAN_RU_U = $(DEST_MAN_TOP)/ru.UTF-8$(MAN1DIR)

 TAGS_INCL = *.h

+terminal.c:
+       git show v8.0.1128\:src/terminal.c > terminal.c
+
 BASIC_SRC = \
        arabic.c \
        blowfish.c \
```

**Comment by fusion809** [comment]
I build Vim from the source tarballs so this solution wouldn't be quite so easy to implement, I'd have to tweak my ebuilds and PKGBUILDs quite a bit.
