### ISSUE TITLE
Tests ask me: "gzip: Xtestfile already exists; do you wish to overwrite (y or n)?"

### ISSUE THREAD

**Issue by chdiza** [vim/vim#2134]
Just tried building  2e6ab18729a634f3223a92be3, and succeeded, but now the `make test` phase is all weird.  In the middle of the tests, I'm asked:
```
gzip: Xtestfile already exists; do you wish to overwrite (y or n)?
```

This is macOS 10.12.6 with the new Xcode 9.

**Comment by chdiza** [comment]
Some screen context:
```
:!gzip -d 'Xtestfile.gz'
dyld: lazy symbol binding failed: Symbol not found: _futimens
  Referenced from: /usr/local/bin/gzip
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _futimens
  Referenced from: /usr/local/bin/gzip
  Expected in: /usr/lib/libSystem.B.dylib
"Xtestfile.gz" 11 lines, 357 characters
:!gzip 'Xtestfile'dyld: lazy symbol binding failed: Symbol not found: _futimens
  Referenced from: /usr/local/bin/gzip
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _futimens
  Referenced from: /usr/local/bin/gzip
  Expected in: /usr/lib/libSystem.B.dylib



Command terminated
caught FileChangedShell
"test.out" 11 lines, 357 characters appended
:!cat Xtest.c >>test.out

:set shelltemp                  " need temp files here
start of testfile
start of testfile
start of testfile
startstart
start of testfile
line 2  Abcdefghijklmnopqrstuvwxyz
line 3  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
startstart
start of testfile
line 2  Abcdefghijklmnopqrstuvwxyz
line 3  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
line 4  Abcdefghijklmnopqrstuvwxyz
line 5  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
line 6  Abcdefghijklmnopqrstuvwxyz
line 7  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
line 8  Abcdefghijklmnopqrstuvwxyz
line 9  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
line 10 Abcdefghijklmnopqrstuvwxyz
end of testfile

start of test.c
/*
 * Here is a new .c file
 */
end of test.c
start of testfile
line 2  Abcdefghijklmnopqrstuvwxyz
line 3  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
line 4  Abcdefghijklmnopqrstuvwxyz
linE 5  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
linE 6  AbcdefghijklmnopqrstuvwXyz
linE 7  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
linE 8  AbcdefghijklmnopqrstuvwXyz
linE 9  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
linE 10 AbcdefghijklmnopqrstuvwXyz
End of testfile

/*
 * HEre is a NEW .c file
 */
/*
 * HEre is a new .c file
 */
start of tEstfile
linE 2  AbcdefghijklmnopqrstuvwXyz
linE 3  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
linE 4  AbcdefghijklmnopqrstuvwXyz
linE 5  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
linE 6  AbcdefghijklmnopqrstuvwXyz
linE 7  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
linE 8  AbcdefghijklmnopqrstuvwXyz
linE 9  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
linE 10 AbcdefghijklmnopqrstuvwXyz
End of testfile
/*
 * HEre is a new .c file
 */
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
gzip: Xtestfile already exists; do you wish to overwrite (y or n)?
```

The missing thing sounds like a problem that Xcode 9 is causing for all kinds of software.  I don't know what to do about it.

**Comment by nuko8** [comment]
> The missing thing sounds like a problem that Xcode 9 is causing for all kinds of software. I don't know what to do about it.

I've just dowloaded gzip-1.8 tarball, and done `./configure && make && make check` all successfully.

According to `lib/config.h`,
```
/* Define to 1 if you have the `futimens' function. */
/* #undef HAVE_FUTIMENS */
```
This strongly indicates that macOS has no such a library function called `futimens` natively.  Also, I checked the symbols of `libSystem.B.dylib` and dylib's in `/usr/lib/system/`, but couldn't find a symbol of that name.

So, the problem is why your gzip, `/usr/local/bin/gzip`, was trying to bind to `_futimens` (In object files, names are prefixed with a single underscore, so `_futimens` stands for the same as `futimens` in the source code):

>:!gzip -d 'Xtestfile.gz'
>dyld: lazy symbol binding failed: Symbol not found: _futimens
> Referenced from: /usr/local/bin/gzip
> Expected in: /usr/lib/libSystem.B.dylib

I'm wondering if the binary was truly compiled for macOS.  It looks to me that the binary was made by passing `-undefined dynamic_lookup` to the linker only to compile in appearance (Such a binary won't work unless all undefined symbols are resolved at runtime).

Since macOS has `/usr/bin/gzip` natively, how about using it instead of `/usr/local/bin/gzip`?  Say, tweaking `$PATH` so that `/usr/bin/gzip` will be picked up first...

**Comment by chdiza** [comment]
This is an Xcode 9 bug (IMO).  It only comes with the 10.13 SDK, which means that things built against it expect some stuff that is not found on macOS 10.12.  It's combining Xcode 9 with macOS 10.12 Sierra that's the problem.  Apple should've just made Xcode 9 be for High Sierra and up, but they get too much enjoyment out of  breaking things.

> Since macOS has /usr/bin/gzip natively, how about using it instead of /usr/local/bin/gzip? Say, tweaking $PATH so that /usr/bin/gzip will be picked up first...

That's an awfully invasive workaround.  I'd rather just not run `make test` than do that, or revert to Xcode 8.3.3.  The built-in `gzip` on macOS is an Apple patched version of a BSD gzip.  It's worse than the GNU version, which is why I have the GNU version in /usr/local.

This problem with `futimens` is not limited to Vim, and Homebrew even have a dedicated issues tag for it, to collect the reports that have already started to come in.

**Comment by chdiza** [comment]
Homebrew have made an initial attempt to prevent stuff like this [here](https://github.com/Homebrew/brew/pull/3182/commits/733d485065e55ad1cf159eec89927c4990bbdfaf).

**Comment by nuko8** [comment]
Then, isn't that an issue of Homebrew?

FWIW, I switched to macOS 10.12.6 and had Xcode 9 installed.  Then, having downloaded gzip-1.8.tar.gz, unarchived it, and, after checking that I was using Xcode 9:
```
$ sudo xcode-select -r
4 xcode-select -p
/Applications/Xcode.app/Contents/Developer
```
I did
```
$ cd gzip-1.8
$ ./configure
$ make
$ make check
```
This test gave me all green.  So,
```
$ sudo make install
```
This installed gzip with the default prefix `/usr/local`:
```
$ which -a gzip
/usr/local/bin/gzip
/usr/bin/gzip
```
Then I went to my Vim local repository,
```
$ ./configure
$ make
$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
$ which gzip
/usr/local/bin/gzip
$ make test
```
I got no error.  So I don't see anything wrong with our build system and Xcode 9.  Did you run `make autoconf` or something else to change the configure script?  That might make all bets off, but otherwise, things are working as expected.

**Comment by chdiza** [comment]
It is Xcode 9's fault when it is used on macOS Sierra.  Homebrew has already [taken steps](https://github.com/Homebrew/brew/pull/3182#issue-259455105) to work around this bug.

My /usr/local/bin/gzip was built by Homebrew before they had put the workaround in place, which means (apparently) that Vim's tests were invoking a broken gzip.  (At that time, I didn't yet know that it was Xcode 9's fault, and there've been so many bizarre Vim test failures lately that I was overly eager to raise an issue here.)   I rebuilt my gzip in Homebrew *with* their workaround, and now Vim's tests are passing fine.

The cause of the broken gzip was Xcode 9, which likes to tell autoconf and friends that the Sierra machine has capabilities or configurations that it actually doesn't, such as `futimens` and `utimensat`.   *High Sierra* has them, though, which is why there will be no problem for users on High Sierra.

No, I didn't `make autoconf` or otherwise screw with `gzip`.  Xcode 9 is screwing a lot of software.  I've run into problems (both for tests and for real runtime) with `rsync`, `wget`, `patch`, and others.

Your /usr/local/bin/gzip was not built by Homebrew, and this Xcode 9 bug sometimes bites non-Homebrew builds and sometimes doesn't.  Sometimes it fails to bite program P when P was built outside Homebrew but bites a Homebrew-built P.  Sometimes it bites a non-Homebrew P but fails to bite a Homebrew P.  It looks as though your /usr/local/bin/gzip was not affected by the Xcode 9 bug,  which is the case for some but not all non-Homebrew-built software.

Either way, none of this is Vim's fault, so I'm going to close the issue.

**Comment by nuko8** [comment]
FYI, on macOS 10.12.6 having Xcode 9, if you compare the output of
```
$ clang -v -E - < /dev/null
```
with that of
```
$ xcrun --sdk macosx10.13 clang -v -E - < /dev/null
```
(Basically, the former shows the search paths of header files and their search order when the compiler is invoked standalone, the latter as a tool of Xcode.)

then, you'll find the remarkable difference is:

The former,
```
 /usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
```

The latter,
```
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks (framework directory)
End of search list.
```
Further, if you compare `sys/stat.h` in the first path of the former with that corresponding to the latter, you'll see that, while the former `stat.h` has neither `futimens()` nor `utimensat()`, the latter has both.

I'm not sure how Homebrew invokes the compiler, but I think that would explain well why some Homebrew builds suffered from the bug while mine remained intact: I guess the way of invoking the compiler made a difference, standalone or Xcode.   That said, that still can't explain why your gzip behaved as if it were a loadable module...
