### ISSUE TITLE
vterm.c  line 133.44: 1506-294 (S) Syntax error in expression on #if directive

### ISSUE THREAD

**Issue by zuloloxi** [vim/vim#2136]
Hello,
Tried to compile vim 8.0.1130 for Aix 7.1 with  XL C/C++ for AIX, V11.1 compiler, using this config :
   ./configure --with-features=huge --enable-gui=no --enable-terminal
 but have the error:
        cc -qlanglvl=extc89 -c -I. -Ilibvterm/include -Iproto -DHAVE_CONFIG_H     -g        -DINLINE=""  -DVSNPRINTF=vim_vsnprintf  -DIS_COMBINING_FUNCTION=utf_iscomposing_uint  -DWCWIDTH_FUNCTION=utf_uint2cells -o objects/term_vterm.o libvterm/src/vterm.c
"libvterm/src/vterm.c", line 133.44: 1506-294 (S) Syntax error in expression on #if directive.
make: The error code from the last command is 1.

Changed the line 133 in vterm.c file from :
  #if _XOPEN_SOURCE >= 500 || _ISOC99_SOURCE || _BSD_SOURCE
to : 
   #if _XOPEN_SOURCE >= 500 || defined(_ISOC99_SOURCE) || defined(_BSD_SOURCE)
 and now the compiling is ok.

Is this modification correct ? Could you change the vim code source to work with Aix compiler ? Thanks in advance.

**Comment by tonymec** [comment]
IIUC, for at least some compilers, the first form is equivalent to

    #if _XOPEN_SOURCE >= 500 || _ISOC99_SOURCE != 0 || _BSD_SOURCE != 0

which, assuming short-circuit evaluation, would be a syntax error if `(_XOPEN_SOURCE < 500 && !defined(_ISOC99_SOURCE))` or `(_XOPEN_SOURCE < 500 && _ISOC99_SOURCE != 0 && !defined(_BSD_SOURCE))`

The second form only tests the latter two macros for being defined rather than nonzero, it cannot give a syntax error unless `_XOPEN_SOURCE` is undefined. I **think** it is correct insofar as `_ISOC99_SOURCE` and `_BSD_SOURCE` would each be either undefined or defined as 1.

**Comment by brammool** [comment]
Zuloloxi wrote:

> Tried to compile vim 8.0.1130 for Aix 7.1 with  XL C/C++ for AIX, V11.1 compiler, using this config :
>    ./configure --with-features=huge --enable-gui=no --enable-terminal
>  but have the error:
>         cc -qlanglvl=extc89 -c -I. -Ilibvterm/include -Iproto -DHAVE_CONFIG_H     -g        -DINLINE=""  -DVSNPRINTF=vim_vsnprintf  -DIS_COMBINING_FUNCTION=utf_iscomposing_uint  -DWCWIDTH_FUNCTION=utf_uint2cells -o objects/term_vterm.o libvterm/src/vterm.c
> "libvterm/src/vterm.c", line 133.44: 1506-294 (S) Syntax error in expression on #if directive.
> make: The error code from the last command is 1.
> 
> Changed the line 133 in vterm.c file from :
>   #if _XOPEN_SOURCE >= 500 || _ISOC99_SOURCE || _BSD_SOURCE
> to : 
>    #if _XOPEN_SOURCE >= 500 || defined(_ISOC99_SOURCE) || defined(_BSD_SOURCE)
>  and now the compile is ok.
> 
> Is this modification correct ? Could you change the vim code source to
> work with Aix compiler ? Thanks in advance. 

Looks OK to me.  We should probably also check if _XOPEN_SOURCE is
defined before using the value.

-- 
Living in Hollywood is like living in a bowl of granola.  What ain't
fruits and nuts is flakes.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
