### ISSUE TITLE
gN doesn't work with 'nowrapscan' when cursor is after last instance

### ISSUE THREAD

**Issue by fcpg** [vim/vim#2137]
- Create new file:
foo
bar
foo
baz

- search for 'foo':
  gg*

- move to last line:
G

- type gN with wrapscan; it works correctly (foo on 3rd line is visually selected)
set wrapscan
gN

- unset wrapscan, move back to last line and type gN; cursor doesn't move, nothing is selected;
set nowrapscan
G
gN

**Comment by chrisbra** [comment]
I'll have a look

**Comment by chrisbra** [comment]
posted a patch https://groups.google.com/d/msg/vim_dev/mUAC1Iy3mQw/UieNp_kACAAJ

**Comment by chrisbra** [comment]
fixed https://github.com/vim/vim/releases/tag/v8.0.1148
