### ISSUE TITLE
Netrw's Lexplore! throwing E16

### ISSUE THREAD

**Issue by vdumitraskovic** [vim/vim#2146]
Lexplore! on gvim/vim in Windows 10 (vim-tux build 8.0.1088) is throwing E16 error.

Steps to reproduce:
1. Open vim.
2. Type `:Lexplore!`
3. After netrw is opened type `:Lexplore!` again
4. Error is thrown (`E16: Invalid range: 2wincmd w`)

**Comment by chrisbra** [comment]
please test with the latest netrw file from Charles [page](http://www.drchip.org/astronaut/vim/#NETRW%20)

**Comment by vdumitraskovic** [comment]
@chrisbra Tested with latest netrw file. I'm getting same error.

**Comment by cecamp** [comment]
Just put v162n onto my website which addresses this issue (http://www.drchip.org/astronaut/vim/index.html#NETRW).  Please test!

**Comment by vdumitraskovic** [comment]
@cecamp It works :)
Thank you!

**Comment by lacygoill** [comment]
I can confirm the issue has been fixed; I cannot reproduce it on master.
