### ISSUE TITLE
Vim no longer de-indents shell script code

### ISSUE THREAD

**Issue by mario-grgic** [vim/vim#2151]
This seems to be recent regression. When typing bash code vim would de-indent `then`, `else` and `fi`. In current build 8.0. patch level 1142 this is no longer the case, so the code ends up looking like this:

```
if [ $# == 3 ]
    then
	echo ""
	fi
```

but it used to correctly get formatted as you type as follows:

```
if [ $# == 3 ]
then
    echo ""
fi
```

I am on macOS 10.12.6 and vim:

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 24 2017 08:48:00)
MacOS X (unix) version
Included patches: 1-1142
Compiled by Mario Grgic
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminal
++builtin_terms  +fork()          +multi_lang      +terminfo
+byte_offset     -gettext         -mzscheme        +termresponse
+channel         -hangul_input    +netbeans_intg   +textobjects
+cindent         +iconv           +num64           +timers
-clientserver    +insert_expand   +packages        +title
+clipboard       +job             +path_extra      -toolbar
+cmdline_compl   +jumplist        +perl            +user_commands
+cmdline_hist    +keymap          +persistent_undo +vertsplit
+cmdline_info    +lambda          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      +startuptime     -xpm
+eval            +mouse_dec       +statusline      -xsmp
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_clipboard
+extra_search    -mouse_jsbterm   +syntax          -xterm_save
+farsi           +mouse_netterm   +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -F/System/Library/Frameworks -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -L/usr/local/lib -I/System/Library/Frameworks/lib/python2.7/config -F/System/Library/Frameworks -L/usr/local/lib -o vim        -lm -lncurses  -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -framework Python   -lruby.2.0.0 -lobjc
```

**Comment by chrisbra** [comment]
I suppose you are using the sh indent plugin? (Check with `:set indentexpr?`). If so, it might a problem with my [vim-sh-indent plugin](https://github.com/chrisbra/vim-sh-indent) (and it does behave like you explain here), however it doesn't look like a recent regression, it seems to have always behaved that way. So I would appreciate, if you could bisect when this behaviour did not happen.

**Comment by mario-grgic** [comment]
I don't have any extra indent plugins for shell, so yes I am using the default. I have bisected this problem and it looks like it got broken in patch 1041

```e2e69e481 (tag: v8.0.1041, v8.0.1041) (3 weeks ago) patch 8.0.1041: bogus characters when indenting during visual-block append [Bram Moolenaar]```

It works fine in patch 1040.

**Comment by chrisbra** [comment]
what are your indenting settings? How to reproduce starting with `vim -u NONE -N`?

**Comment by mario-grgic** [comment]
I have autoindent, smartindent set:

```
--- Options ---
  autoindent          exrc                langmenu=none       pumheight=15        smartcase           ttymouse=xterm2
  background=dark     filetype=sh         langnoremap         ruler               smarttab            wildmenu
  backup              helplang=en       nolangremap           scroll=47           syntax=sh
  commentstring=#%s   history=200         mouse=a             secure              title
  cscopeverbose       hlsearch            mousemodel=extend   shiftwidth=4        ttimeout
  cursorline          ignorecase          nrformats=bin,hex   showcmd             ttimeoutlen=100
  display=truncate    incsearch           number              showmatch           ttyfast
  backspace=indent,eol,start
  cryptmethod=blowfish2
  cscopeprg=/usr/local/bin/cscope
  diffopt=filler,iwhite
  fileencodings=ucs-bom,utf-8,default,latin1
  grepprg=/usr/local/bin/grep -n $* /dev/null
  indentexpr=GetShIndent()
  indentkeys=0{,0},!^F,o,O,e,0=then,0=do,0=else,0=elif,0=fi,0=esac,0=done,0=end,),0=;;,0=;&,0=fin,0=fil,0=fip,0=fir,0=fix
  listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<
  makeprg=/usr/local/bin/shellcheck \--format=gcc
  pythonthreedll=/Library/Frameworks/Python.framework/Versions/3.5/Python
  pythonthreehome=/Library/Frameworks/Python.framework/Versions/3.5
  runtimepath=~/.vim,/Applications/MacVim.app/Contents/Resources/vim/vimfiles,/Applications/MacVim.app/Contents/Resources/vim/runtime,/Applications/MacVim.app/Contents/Resources/vim/runtime/pack/dist/opt/matchit,/Applications/MacVim.app/Contents/Resources/vim/vimfiles/after,~/.vim/after
  shortmess=filnxtToOI
```

**Comment by vim-ml** [comment]
On 2017-09-25, Christian Brabandt wrote:
> what are your indenting settings? How to reproduce starting with vim -u NONE
> -N?

I've noticed this problem, too, since recently updating from 8.0.691
to 8.0.1127.  Here is a demonstration.

    $ vim -N -u NONE -i NONE -c 'so $VIMRUNTIME/indent/sh.vim'

Enter the following text, letting Vim do all the indenting.

if [ $this ]; then
        that
        fi

Note that "fi" is not unindented.  As another example, enter this
text.

if [ $this ]
        then
                that
                fi

Note here that not only is "fi" not unindented, but that "then" is
indented, which it should not be.

Regards,
Gary

**Comment by vim-ml** [comment]
On Mo, 25 Sep 2017, Gary Johnson wrote:

> I've noticed this problem, too, since recently updating from 8.0.691
> to 8.0.1127.  Here is a demonstration.
> 
>     $ vim -N -u NONE -i NONE -c 'so $VIMRUNTIME/indent/sh.vim'
> 
> Enter the following text, letting Vim do all the indenting.
> 
> if [ $this ]; then
>         that
>         fi
> 
> Note that "fi" is not unindented.  As another example, enter this
> text.
> 
> if [ $this ]
>         then
>                 that
>                 fi
> 
> Note here that not only is "fi" not unindented, but that "then" is
> indented, which it should not be.

It was a bit tricky, but finally found the problem. Patch 8.0.1041 had 
one small typo, which forgot to obtain the line pointer in insert mode 
again once the indentkeys 0=word kicked in.

I initially searched the error in the block editing mode, which 
obviously was not involved here, so that confused me a bit.

Attached patch fixes the problem and contains a test.

Christian
-- 
Begriff ist Summe, Idee Resultat der Erfahrung; jene zu ziehen, 
wird Verstand, dieses zu erfassen, Vernunft erfordert.
		-- Goethe, Maximen und Reflektionen, Nr. 1061

**Comment by vim-ml** [comment]
On 2017-09-25, Christian Brabandt wrote:

> Attached patch fixes the problem and contains a test.

That fixed it for me.  (Not that I doubted it would.)  Thanks!

Regards,
Gary

**Comment by mario-grgic** [comment]
I can also confirm the patch fixes the issue.
