### ISSUE TITLE
:term doesn't work on mac OS High Sierra

### ISSUE THREAD

**Issue by Azakur4** [vim/vim#2162]
When i run :term in vim only get a black window

![screen shot 2017-09-27 at 14 14 20](https://user-images.githubusercontent.com/1726914/30927225-2e9899d4-a38e-11e7-9114-ec32cb60fdd3.png)

the prompt never appear, im running vim 8.0.1150

**Comment by chrisbra** [comment]
When did it break? What is your 'shell' setting? and what happens when you use `:term bash`?

**Comment by lifepillar** [comment]
It works in macOS 10.12, it breaks in macOS 10.13 (tested with Terminal.app and iTerm2). The `'shell'` option is set to `shell` in both cases. A command like `:term bash` behaves as described by the OP in 10.13, it works in 10.12. Good luck figuring out what Apple has changed!

**Comment by lifepillar** [comment]
I can reproduce the issue on macOS 10.13 with Vim as old as v0.997 (I haven't tried older versions). No problems with macOS 10.12.

**Comment by chrisbra** [comment]
I guess someone with a recent mac needs to debug this then.

**Comment by ichizok** [comment]
On 10.13,  trying to open `/dev/ptyXY` fails `EAGAIN` error.
I think need to open `/dev/ptmx`, or use `posix_openpt` instead of `open`.

Could you try this patch? (but this is just workaround)

```diff
--- a/src/pty.c
+++ b/src/pty.c
@@ -267,7 +267,7 @@ OpenPTY(char **ttyn)
 }
 #endif

-#if defined(HAVE_SVR4_PTYS) && !defined(PTY_DONE) && !defined(hpux) && !defined(MACOS_X)
+#if defined(HAVE_SVR4_PTYS) && !defined(PTY_DONE) && !defined(hpux)

 /* NOTE: Even though HPUX can have /dev/ptmx, the code below doesn't work!
  * Same for Mac OS X Leopard. */
```

**Comment by chrisbra** [comment]
shouldn't we perhaps also get an error, if openpty fails?

**Comment by lifepillar** [comment]
Yup, the patch appears to fix it.

**Comment by Azakur4** [comment]
sorry for my ignorance but how i can apply ur patch @ichizok do u know some site i can read about that?

Or i have to fork the vim repository make the changes and compile again?

**Comment by nuko8** [comment]
I agree to @ichizok .

Recently, I've been working on overhauling macOS part of the build system,  and I came across a similar problem regarding `/dev/ptmx` just a few days ago --- even on El Capitan (10.12), `:term` hangs against the Athena and Motif GUIs on XQuartz.

But my solution is a bit conservative in comparison with his:
```diff
diff --git a/src/pty.c b/src/pty.c
index 9b0361222..cc1c39a43 100644
--- a/src/pty.c
+++ b/src/pty.c
@@ -267,10 +267,11 @@ OpenPTY(char **ttyn)
 }
 #endif

-#if defined(HAVE_SVR4_PTYS) && !defined(PTY_DONE) && !defined(hpux) && !defined(MACOS_X)
+#if defined(HAVE_SVR4_PTYS) && !defined(PTY_DONE) && !defined(hpux) \
+                    && !(defined(MACOS_X) && !defined(MAC_OS_X_VERSION_10_6))

 /* NOTE: Even though HPUX can have /dev/ptmx, the code below doesn't work!
- * Same for Mac OS X Leopard. */
+ * Same for Mac OS X Leopard (10.5). */
 #define PTY_DONE
     int
 OpenPTY(char **ttyn)
```
This is because of the comment on Leopard (10.5), and that, when googling, I came across a question at SO  in which [a Tiger (10.4) user asked about `/dev/ptmx` last March](https://stackoverflow.com/questions/43956208/does-mac-os-x-have-the-dev-ptmx-file).

**Comment by tracyone** [comment]
Same issue.

**Comment by daleworley** [comment]
You likely ran into the same problem I had on High Sierra with Emacs shell windows (https://stackoverflow.com/questions/53531777/cannot-open-pty-under-mac-os-high-sierra/53581958#53581958) -- High Sierra uses a different mechanism for allocating pty's than earlier Mac OS X releases, so if your code isn't reconfigured for it, it will fail to allocate a pty.
