### ISSUE TITLE
[Termdebug] After resizing of a window, program and source window overlap

### ISSUE THREAD

**Issue by bstaletic** [vim/vim#2164]
#### Details

When `:Termdebug` opens the three windows with `set splitbelow`, after resizing the "program" window's first line overlaps the "source" window's statusline.

#### Steps to reproduce

Given `test.c`:
```c
#include <stdio.h>

int main(void) {
    puts("foo");
    return 0;
}
```

Do the following:

- `gcc -Og -ggdb3 test.c`
- `vim -Nu NONE`
- `:set splitbelow`
- `:packadd termdebug`
- `:Termdebug`
- In gdb window, `file a.out`
- `b main`
- `r`
- `c`
  - The previous three steps are there to make source visible, as it doesn't get shown if we only run the program from start to finish, but it is not necessary for this bug's reproduction steps.
- At this point everything should look fine. Now let's get to resizing.

- `<C-w>k<C-w>k` to get to the source window.
- `<C-w>-` to make it smaller.
- The "foo" string just dissapeared.
- `<C-w>j` to get to the program window.
- If "foo" doesn't appear, type anything except `<C-w>`.
- The "foo" string is visible, but the source window's status has now dissapeared.

**Comment by brammool** [comment]
Boris Staletic wrote:

> ###Details
> 
> When `:Termdebug` opens the three windows with `set splitbelow`, after resizing the "program" window's first line overlaps the "source" window's statusline.
> 
> ###Steps to reproduce
> 
> Given `test.c`:
> ```c
> #include <stdio.h>
> 
> int main(void) {
>     puts("foo");
>     return 0;
> }
> ```
> 
> Do the following:
> 
> - `gcc -Og -ggdb3 test.c`
> - `vim -Nu NONE`
> - `:set splitbelow`
> - `:packadd termdebug`
> - `:Termdebug`
> - In gdb window, `file a.out`
> - `b main`
> - `r`
> - `c`
>   - The previous three steps are there to make source visible, as it doesn't get shown if we only run the program from start to finish, but it is not necessary for this bug's reproduction steps.
> - At this point everything should look fine. Now let's get to resizing.
> 
> - `<C-w>k<C-w>k` to get to the source window.
> - `<C-w>-` to make it smaller.
> - The "foo" string just dissapeared.
> - `<C-w>j` to get to the program window.
> - If "foo" doesn't appear, type anything except `<C-w>`.
> - The "foo" string is visible, but the source window's status has now dissapeared.

I can reproduce it.

-- 
hundred-and-one symptoms of being an internet addict:
218. Your spouse hands you a gift wrapped magnet with your PC's name
     on it and you accuse him or her of genocide.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
I can no longer reproduce the problem, must have been fixed already.
If you still see it, please reopen and tell us the system and other things that might matter.

**Comment by bstaletic** [comment]
I can't reproduce the problem either. Thanks for looking into this.
