### ISSUE TITLE
Global mark lost after executing a `:vimgrep` command

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#2166]
- `vim --version`: 8.0 patches up to 1159
- Operating system/version: Linux, Ubuntu 16.04
- Terminal name/version: xfce4-terminal
- `$TERM`: xterm-256color

Sometimes, one of the global marks I set on a file is lost, or changed to another file.
I think it happens after executing a `:vimgrep` command.

Here's a way to reproduce.

Create a temporary file:

    $ touch /tmp/file

Start Vim to edit this file and set the global mark `Z` on it:

    $ vim /tmp/file
    mZ
    :q 

Start a new Vim session without any custom configuration, and load the file by pressing `'Z` to check the global mark has been correctly set and saved in `~/.viminfo`:

    $ vim -Nu NONE
    'Z
    :q 

It should work as expected. Now, restart a new Vim session, again with no custom configuration. Don't load the `/tmp/file`, and execute `:vimgrep` to search for a random pattern inside the `/tmp` directory.

    $ vim -Nu NONE
    :vimgrep /random_pattern/ /tmp/**/*

You will probably get the error `E480` (`No match: random_pattern`), which is expected. But now, if you try to load the `/tmp/file` by pressing `'Z`, instead of loading the file, Vim displays the error `E92` (`Buffer 2 not found`). And if you execute `:marks`, you should see that the global `Z` mark is not set anymore.

It seems that Vim loaded `/tmp/file` to look for `random_pattern`, didn't find it, and thus wiped the buffer. And by wiping the buffer, the global mark is deleted.

Would it possible for `:vimgrep` to not wipe a buffer for which a global mark exists, and instead only delete it with `:bdelete`?

**Comment by LemonBoy** [comment]
That's exactly what happens, if there are no matches in the buffer it is `:bwipeout`'d away [here](https://github.com/vim/vim/blob/d371bbe0ab4b07dd3aa8d0f77905d222f6c5fd7e/src/quickfix.c#L4415).

**Comment by chrisbra** [comment]
sounds familiar:
https://groups.google.com/d/msg/vim_dev/Z85RljTZOtw/6i7HM2e-gRgJ
reported by me and includes a patch to fix this behaviour. Back then the reaction was to declare this as a feature. Patch is still available [here](https://github.com/chrisbra/vim-mq-patches/blob/master/save_marks_on_bufwipe), don't know if it still applies and the test should be converted to a new style test.

**Comment by lacygoill** [comment]
@chrisbra Yes I agree with you. I would like to consider global marks as associated to file paths and not buffers. Like bookmarks in a web browser are associated to urls and not html files. So, I would prefer that `:bwipe` leaves global marks untouched, and hope that your patch will be merged.

But at the very least, a `:vimgrep` command, or any command other than `:bwipe` (& maybe commands closely related to it), should not delete a global mark. `:vimgrep` has nothing to do with `:bwipe`. The fact that the latter can be used by the former is just a detail of implementation. Imo a user shouldn't wonder whether their global marks are going to persist after every command they may execute.

**Comment by lacygoill** [comment]
As a workaround, I'm experimenting a modified version of this : 

<details><summary>code</summary><p>

    set viminfo^=!

    fu! s:global_mark_set(char) abort
        try
            exe 'norm! m'.a:char
            let g:GLOBAL_MARK_{a:char} = { 'fpath': expand('%:p'), 'pos': getpos('.')[1:2] }
        catch
            return 'echoerr '.string(v:exception)
        endtry
        return ''
    endfu

    fu! s:global_mark_go(char) abort
        if !exists('g:GLOBAL_MARK_'.a:char)
            let info = get(filter(split(execute('marks'), '\n'), 'v:val =~# "^\\s*'.a:char.'"'), 0 , '')
            if !empty(info)
                let fpath = matchstr(info, '^\s*'.a:char.'\s\+\d\+\s\+\d\+\s\+\zs.*')
                let pos   = split(matchstr(info, '^\s*'.a:char.'\s\+\zs\d\+\s\+\d\+'))
                let g:GLOBAL_MARK_{a:char} = { 'fpath': fpath, 'pos': pos }
            else
                return ''
            endif
        endif

        try
            exe 'e '.fnameescape(g:GLOBAL_MARK_{a:char}.fpath)
            call cursor(g:GLOBAL_MARK_{a:char}.pos)
            redraw
            exe 'norm! m'.a:char
        catch
            return 'echoerr '.string(v:exception)
        endtry

        return ''
    endfu

    fu! s:global_mark_mappings() abort
        for upper in map(range(char2nr('A'),char2nr('Z')), 'nr2char(v:val)')
            sil! exe "nno <silent> '".upper.' :<c-u>exe <sid>global_mark_go("'.upper.'")<cr>'
            sil! exe 'nno <silent> m'.upper.' :<c-u>exe <sid>global_mark_set("'.upper.'")<cr>'
        endfor
    endfu

    fu! s:global_marks(key) abort
        call s:global_mark_mappings()
        unmap '
        unmap m
        let keys = a:key.nr2char(getchar())
        call feedkeys(keys, 'it')
        return ''
    endfu

    nno <expr> <silent> ' <sid>global_marks("'")
    nno <expr> <silent> m <sid>global_marks('m')

</p></details>

<br>

It installs wrapper mappings around all `'A`, ..., `'Z`, `mA`, ..., `mZ` commands, and saves / uses information about the marks in the viminfo file.

I would be tempted to merge all variables in a single dictionary, but I'm concerned that if some filepaths are long, and the dictionary becomes too big, it wouldn't be read back correctly. Because according to `:h viminfo-!`:

    Nested List and Dict items may not be read back correctly, you end up with an empty item.
