### ISSUE TITLE
Feature Request: add an option to make the current position in the changelist local to the buffer

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#2173]
_I asked almost the same question on [stackoverflow](https://stackoverflow.com/questions/45174667/in-vim-how-to-make-the-position-in-the-changelist-local-to-the-buffer-instead-o) a few months ago._

I'm often using `g,` and `g;` to traverse the changelist, but I have noticed that the current position inside the latter changes when I edit 2 buffers in the same window.

For example, if I start Vim with a minimum of initializations, to edit 2 existing files:

    vim -Nu NORC file1 file2

Then make sure that I'm at the end of the changelist in both of them, by typing:

    99g,
    :next
    99g,
    C-^

Finally, if I move at the beginning of the changelist in `file1` (`99g;`), and go back to `file2` (`C-^`), I'm no longer at the end of the changelist but at the beginning. It seems the current position in the changelist of `file1` has been copied to the changelist of `file2`, which I've checked by executing the `:changes` command, and looking at the prefix `>`.

Since the lines contained in the changelist are local to a buffer, I expected the position in the changelist to also be local to a buffer.

For the moment, I'm experimenting these 2 autocmds:

    augroup my_changelist
        au!
        au BufWinLeave * call s:get_change_position()
        au BufWinEnter * call s:restore_change_position()
    augroup END

    fu! s:get_change_position() abort
        let changelist = split(execute('changes'), '\n')
        let b:my_change_position = {
                                \ 'idx':  index(changelist, matchstr(changelist, '^>')),
                                \ 'view': winsaveview(),
                                \ }
        if b:my_change_position.idx == -1
            let b:my_change_position.idx = 100
        endif
    endfu

    fu! s:restore_change_position() abort
        if exists('b:my_change_position.idx') && exists('b:my_change_position.view')
            sil! exe 'norm! 99g;'. (b:my_change_position.idx - 1) .'g,'
            call winrestview(b:my_change_position.view)
        endif
    endfu

Sometimes it works, but sometimes it seems that the current position in the changelist of a buffer is not as it was the last time I worked in it.

Would it possible to add an option allowing the user to make their current position in the changelist local to a buffer instead of a window?

**Comment by brammool** [comment]
lacygoill wrote:

> _I asked almost the same question on [stackoverflow](https://stackoverflow.com/questions/45174667/in-vim-how-to-make-the-position-in-the-changelist-local-to-the-buffer-instead-o) a few months ago._
> 
> In Vim, I'm often using `g,` and `g;` to traverse the changelist, but
> I have noticed that the current position inside the latter changes
> when I edit 2 buffers in the same window.
> 
> For example, if I start Vim with a minimum of initializations, to edit
> 2 existing files:
> 
>     vim -Nu NORC file1 file2
> 
> Then make sure that I'm at the end of the changelist in both of them,
> by typing:
> 
>     99g,
>     :next
>     99g,
>     C-^
> 
> Finally, if I move at the beginning of the changelist in `file1`
> (`99g;`), and go back to `file2` (`C-^`), I'm no longer at the end of
> the changelist but at the beginning. It seems the current position in
> the changelist of `file1` has been copied to the changelist of
> `file2`, which I've checked by executing the `:changes` command, and
> looking at the prefix `>`.
> 
> Since the lines contained in the changelist are local to a buffer, I
> expected the position in the changelist to also be local to a buffer.
> 
> For the moment, I'm experimenting these 2 autocmds:
> 
>     augroup my_changelist
>         au!
>         au BufWinLeave * call s:get_change_position()
>         au BufWinEnter * call s:restore_change_position()
>     augroup END
> 
>     fu! s:get_change_position() abort
>         let changelist = split(execute('changes'), '\n')
>         let b:my_change_position = {
>                                 \ 'idx':  index(changelist, matchstr(changelist, '^>')),
>                                 \ 'view': winsaveview(),
>                                 \ }
>         if b:my_change_position.idx == -1
>             let b:my_change_position.idx = 100
>         endif
>     endfu
> 
>     fu! s:restore_change_position() abort
>         if exists('b:my_change_position.idx') && exists('b:my_change_position.view')
>             sil! exe 'norm! 99g;'. (b:my_change_position.idx - 1) .'g,'
>             call winrestview(b:my_change_position.view)
>         endif
>     endfu
> 
> Sometimes it works, but sometimes it seems that the current position
> in a buffer is not as it was the last time I worked in it.
> 
> Would it possible to add an option allowing the user to make their
> current position in the changelist local to a buffer instead of a
> window?

The field used is w_changelistidx, which is local to a window.  It
indeed doesn't make sense to use the same index for different buffers,
since their list of changes will be different.

This can be made to work to put an extra field in wininfo_S, which is
the per-window information of a buffer.  Perhaps someone can implement
that.

-- 
hundred-and-one symptoms of being an internet addict:
233. You start dreaming about web pages...in html.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
In `runtime/doc/todo.txt`, from line 885 to 886, the todo item is no longer relevant:
https://github.com/vim/vim/blob/d1f8fd59074d9c8b4d00ccdea77726a9195e0be4/runtime/doc/todo.txt#L885-L886

**Comment by brammool** [comment]
I'll remove the todo item.
