### ISSUE TITLE
Acronis Active Protection causes problems with vim editing (SOLVED)

### ISSUE THREAD

**Issue by plbowers** [vim/vim#2176]
Vim has a feature which checks whether the current file has been modified by someone else before it saves (thus preventing 2 people editing the same file and "stepping on each other").

When this error condition occurs, vim provides error #w11 which reads "warning: the file has been changed since reading it."

When Acronis Active Protection (a feature of an external backup program) is turned on, it somehow makes vim think this has happened so that whenever you save a file in vim (every time after the first time!), vim thinks that the file was modified by someone else.

I was able to consistently stop the behavior by turning Active Protection off. Eventually I registered the editor (gvim.exe) as a trusted service/application and that solved the problem.

I'm documenting the issue here so others can benefit from my frustration. Currently all google searches point to the daylight savings time, but this was clearly not the issue because it is September. I want to make sure there is something that someone else can find if they run into this issue and are running Acronis Active Protection.

(To be clear this is NOT an issue with vim - it is a an issue caused by the interaction of these 2 programs. I *believe* (although I have not tested it) that the timestamp is actually being changed by Acronis, and so vim's behavior is as expected. This issue can be marked as closed)

**Comment by chrisbra** [comment]
closing
