### ISSUE TITLE
File with DOS line breaks may show no empty line at end of files in vim, while in Windows editors it will

### ISSUE THREAD

**Issue by ghost** [vim/vim#2183]
File with DOS line breaks may show no empty line at end of files in vim, while in Windows editors it will.

Here is the file in exact byte contents of an affected test file:

```
e@cyberman:~$ hexdump -b test.txt
0000000 141 142 143 015 012 144 145 146 015 012                        
000000a
```

This shows up in Windows Notepad like this:

![notepad](https://user-images.githubusercontent.com/1573352/31132949-67ae2106-a85e-11e7-9813-c2a40ce9da85.png)

However, in vim the file is clearly indicated to have dos line breaks but will show up with no empty line at the end:

![vim](https://user-images.githubusercontent.com/1573352/31133008-8ef017f6-a85e-11e7-83eb-bbe58183f9fc.png)

The cause appears to be that POSIX suggests `\n` terminates the previous line (instead of always indicating a line break with a line following) such that ignoring a trailing `\n` is correct, but no such convention exists on Microsoft Windows and therefore a trailing `\r\n` should probably be treated always as starting a new line even if no bytes follow - as seen in Notepad. VIM however seems to apply the POSIX interpretation even to DOS line breaks which leads to the unintuitive display difference.

**Comment by chrisbra** [comment]
Yes, that is one convention that vim adheres to. This has been discussed in great detail in the past, which you may read up on at the vim_use or vim_dev mailinglist. Changing this would make other people complain or be inconsistent between platforms. So it is unlikely that this will happen.

**Comment by ghost** [comment]
For what it's worth, isn't the current behavior inconsistent between platforms? (After all, a common editor on Windows would show this differently) I suppose this is the wrong place for this discussion, but I think the current behavior is inconsistent with the expected interpretation of DOS line breaks..

**Comment by k-takata** [comment]
It is consistent between platforms and fileformats (from the Vim's point of view).
A line is always ended with an EOL in Vim.
EOL is `\n` when ff=unix, `\r\n` when ff=dos, and `\r` when ff=mac.

And, if you don't want to add the last EOL, do `:set nofixeol eol`.
See `:help 'fixeol'` and `:help 'eol'` for detail.

**Comment by ghost** [comment]
This assumes `\r\n` is similar to `\n` semantically an end of line character, while actually the usual interpretation by Windows programs of `\r\n` appears to be that it always starts a new line (which is not the same as POSIX's EOL `\n` which just ends the previous line). So I don't think that view makes a lot of sense for DOS line breaks.. but it might be hard to fix this with such an underlying assumption baked into the editor.

**Comment by vim-ml** [comment]
On Sat, Oct 7, 2017 at 3:55 AM, Jonas Thiem <vim-dev-github@256bit.org> wrote:
> However, this assumes \r\n is similar to \n semantically an end of line
> character, while actually the common interpretation of Windows seems to be
> it always starts a new line. So I don't think that view makes a lot of sense
> for DOS line breaks.. but I suppose it is hard to fix this with such an
> underlying assumption baked in.

Well, it all comes from a difference of point of view. To Vim, an
end-of-line character or sequence "ends" a line and even the last line
in a file is "improperly constructed" if it lacks one. To some Windows
programs, the same sequence "separates" lines and the last line in a
file doesn't need one — indeed, if a file ends in such a sequence,
they assume there is an empty line at the end. Such a supposed "empty
line" is usually harmless and AFAIK it never makes the DOS/Windows
editor, compiler, etc. issue any message so I go with Vim in this
respect and everyone is happy, except maybe the nitpicking Windows
_user_ who finds that two extra bytes ("extra" from his point of view)
at the end of a long file are too much.

The Vim convention isn't groundless: if you concatenate two or more
files, and each of them ends in an end-of-line, there will still be a
line break between successive component files. If one of them (other
than the last) lacks a proper EOL at the end, the "cat" (concatenate)
Unix program, or (I suppose) the "copy a.txt+b.txt+c.txt abc.txt"
Dos/Windows operation will "run it in" with the first line of the next
file as a single line. "Programs don't think, they do exactly what you
tell them to do, even if it isn't what you meant."

Best regards,
Tony.

**Comment by JonasT** [comment]
> To some Windows programs

Do you know some originally windows-native programs that don't treat it as line separator? (excluding all cross-platform ones or those using non-native toolkits like wxWidgets or Qt)

> The Vim convention isn't groundless:

It isn't, I just think an editor should stick to the platform convention of the platform the line breaks originate from. While the concatenation is neat, this problem exists on Windows too and itself alone is IMHO not a good enough reason to change the meaning of line breaks. But that's just my opinion.

> "Programs don't think, they do exactly what you tell them to do, even if it isn't what you meant."

Very true. Programs doing something you didn't mean to do happens more often though if conventions are broken, especially if there isn't a particularly good reason for it.. (other than "well POSIX line breaks work that way and we kinda forgot to treat this differently, and now we're considering it a feature and don't want to alienate people relying on it" which is how that sounds like to me)

But then again it's just line breaks, I should probably just get over this. :wink:

**Comment by chrisbra** [comment]
>  I should probably just get over this. 😉

Indeed. Doesn't make much sense to argue against or for it, it has been the cause of some flamewars on the vim list, so I suggest getting used to it :)

**Comment by brammool** [comment]
Vim is doing this correctly.  The other editors are wrong.  Eventually they will be fixed.
It's a common thing that MS-Windows made a decision to do something different from Unix, and later realize that Unix was right after all.  BTW: Most MS-Windows programs do support Unix line endings.  As they do forward slashes in path names.  Probably we'll never get rid of drive names though...

**Comment by ghost** [comment]
So basically you're saying Windows is doing Windows line breaks wrong? :wink: Alrighty then
