### ISSUE TITLE
Filename breaks doing ":w #-A<enter>" result looses the "-"

### ISSUE THREAD

**Issue by stucki-at-home** [vim/vim#2184]
I after noticing it, I recompiled the current git (commit 19a3d68b2cd4beb1ee1d97a84ad4e860ffe0cbb2)
with gui on ubuntu and without gui on a freshly updates debian stretch, then tested the same on
an older win-8.1 'gvim' -- always with the same result.  How to reproduce (i want to split a file):

- make file 'foo' with two lines in it.
- open file (e.g. with: "vim foo")
- delete the second line
- open new nameless window with ":n<return>"
- put line from buffer in, by 'p'
NOW try to write to the derived name:
- try ":w #-A"
I assumed this to create "foo-A"
BUT it creates "fooA" missing the "-"

Yours 'Stucki'  (C. v. Stuckrad)

**Comment by chrisbra** [comment]
Hm, it looks like the problem is in getdigits():
https://github.com/vim/vim/blob/712549e04eddd6687c4b7654ec9af6da6c365603/src/charset.c#L1819-L1823
Note, that the pointer is incremented, if a '-' is found. Changing Unfortunately, `getdigits()` is called all over the place. Changing it here, might have unexpected effects, so perhaps it is advisable to change the caller:
```patch
diff --git a/src/ex_docmd.c b/src/ex_docmd.c
index e2dfd9225..01dded6d6 100644
--- a/src/ex_docmd.c
+++ b/src/ex_docmd.c
@@ -10732,6 +10732,8 @@ eval_vars(
                if (*s == '<')          /* "#<99" uses v:oldfiles */
                    ++s;
                i = (int)getdigits(&s);
+               if (!i && *(s-1) == '-')
+                   s--;
                *usedlen = (int)(s - src); /* length of what we expand */

                if (src[1] == '<')
```

**Comment by brammool** [comment]
Christian wrote:

> Hm, it looks like the problem is in getdigits():
> https://github.com/vim/vim/blob/712549e04eddd6687c4b7654ec9af6da6c365603/src/charset.c#L1819-L1823
> Note, that the pointer is incremented, if a '-' is found. Changing Unfortunately, `getdigits()` is called all over the place. Changing it here, might have unexpected effects, so perhaps it is advisable to change the caller:

Thanks for the fix.  How about a test?


-- 
hundred-and-one symptoms of being an internet addict:
264. You turn to the teletext page "surfing report" and are surprised that it
     is about sizes of waves and a weather forecast for seaside resorts.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by stucki-at-home** [comment]
I simply
(1)"git pull"ed to compare latest, then
(2)added the two lines and recompiled.

Error is gone on Debian and UBUNTU.
"make test" still passes both.
(Sorry, can not compile/recheck on Win*)

Stucki

**Comment by chrisbra** [comment]
Sure here is a [patch](https://github.com/chrisbra/vim/commit/6fd9c97c0511d671ad5e0ffe287b5131c51d34ba)

Note, it also fixes a bug, that `:w #<` did not work as expected (and returned the empty string).
