### ISSUE TITLE
And vimtutor.bat again

### ISSUE THREAD

**Issue by a-kubik** [vim/vim#2188]
Add-on to #2105
-------------------
Now if run  vimtutor.bat (from folder %WINDIR%) or other path
start vimtutor.bat(folder $VIMRUNTIME) and next 
start gwim.bat (folder %WINDIR%) and next
run gwim.exe 
(step 4 very long and an additional unnecessary CMD is started which freeze waits for the EXIT command)
I suggest in  vimtutor.bat(folder $VIMRUNTIME)
change
start "dummy" /b /w gvim 
 to
"%~dp0gvim"

because gvim.exe and vim.exe placed in same folder with vimtutor.bat(folder $VIMRUNTIME)
PS
may be best way for issue #2105 too
for call vim use "%~dp0vim"

**Comment by k-takata** [comment]
Can you create a patch or a PR (to avoid misunderstanding)?

> (step 4 very long and an additional unnecessary CMD is started which freeze waits for the EXIT command)

Do you mean that vimtutor.bat doesn't return until gvim finishes? It is needed for cleaning up a temporary file.

**Comment by a-kubik** [comment]
no, the gvim does not start until you write in window CMD  <exit> and press Enter... 
test it (ON w10; Win32)
with key -console work now vim.exe(fix in #2105) add-on about gvim.exe
and start vimtutor.bat from command prompt

([a patch](https://github.com/a-kubik/vim/commit/b6e1bd430186dc50a591b59152e14987cda74f61?diff=split))

**Comment by k-takata** [comment]
Ah, okay. Now I understand what is happening.
The help of the "start" command (`start /?`) says that a batch file is executed via `cmd /k`, so `start "dummy" /b /w gvim` waits a user typing `exit` when `gvim` is actually a batch file.
However, if it is replaced with `"%~dp0gvim"`,  vimtutor.bat won't wait the end of gvim.exe.
I think it's better to keep `call vim` for CUI, so that it can fall back when gvim.exe fails to execute.
So my proposal is:

```diff
--- a/vimtutor.bat
+++ b/vimtutor.bat
@@ -37,11 +37,11 @@ start /w gvim -u NONE -c "set nocp" %TUT
 GOTO end
 
 :ntaction
-start "dummy" /b /w gvim -u NONE -c "so $VIMRUNTIME/tutor/tutor.vim"
+start "dummy" /b /w "%~dp0gvim.exe" -u NONE -c "so $VIMRUNTIME/tutor/tutor.vim"
 IF ERRORLEVEL 1 GOTO use_vim
 
 :: Start gvim without any .vimrc, set 'nocompatible'
-start "dummy" /b /w gvim -u NONE -c "set nocp" %TUTORCOPY%
+start "dummy" /b /w "%~dp0gvim.exe" -u NONE -c "set nocp" %TUTORCOPY%
 
 GOTO end
 
```

@a-kubik Does this work for you?

**Comment by k-takata** [comment]
Fixed by https://github.com/vim/vim/commit/37f471df6ee422beb4d08ee4ccda35f8279e3bb7.
