### ISSUE TITLE
Inconsistent behavior of <underscore> motion in conjunction with c/d commands.

### ISSUE THREAD

**Issue by alexbriskin** [vim/vim#2189]
This is not a new issue. I've experienced it it Vim 7.4 / Vim 8 and NeoVim.
d_ - deletes current line
c_ - deletes current line and leaves the editor in insert mode.

<underscore> motion takes the cursor to the first non-empty character in the  current line.
So, if the cursor is pointing to some white-space at the beginning of line, using this motion moves the cursor to the first character. If the cursor is somewhere in the middle of the line, using this motion moves the cursor to the first character.

It stands to (my) reason that this motion in conjunction with "d" command will delete all the characters between current cursor location and the first character in line. "c" command should do the same as "d" and finish in insert mode.

**Comment by jottkaerr** [comment]
`_` is a linewise movement (I guess because of VI compatibility). All commands (like `d` or `c`) that are combined with a linewise movement affect whole lines.
You can make the movement (in combination with a command) characterwise by prefixing it with `v`. So `cv_` and `dv_` should do what you want.

**Comment by alexbriskin** [comment]
Found inside the source code a comment:
 * "_" is is a strange motion command that helps make operators more logical.
 * It is actually implemented, but not documented in the real Vi.  This motion
 * command actually refers to "the current line".  Commands like "dd" and "yy"
 * are really an alternate form of "d_" and "y_".  It does accept a count, so
 * "d3_" works to delete 3 lines.


Thanks for the cv_ dv_ tip.
