### ISSUE TITLE
Active terminal causes :wall to fail with E676: No matching autocommands for acwrite buffer

### ISSUE THREAD

**Issue by mgedmin** [vim/vim#2190]
Steps to reproduce:

1. `vim -u NONE`
2. `:term`
3. `<C-W>:wall<CR>`

What happens:

- `E676: No matching autocommands for acwrite buffer` flashes briefly

What I expect

- no confusing error message

Note that if the terminal is no longer active (e.g you exit the shell), `:wall` doesn't complain.

**Comment by vim-ml** [comment]
On 13:18 Thu 05 Oct     , Marius Gedminas wrote:
> Steps to reproduce:
> 
> 1. `vim -u NONE`
> 2. `:term`
> 3. `<C-W>:wall<CR>`
> 
> What happens:
> 
> - `E676: No matching autocommands for acwrite buffer` flashes briefly
> 
> What I expect
> 
> - no confusing error message
> 
> Note that if the terminal is no longer active (e.g you exit the shell), `:wall` doesn't complain.

I see this regularly, when using vim-fugitive :Gcommit command.

Regards,
Marcin

**Comment by gbarta** [comment]
This also happens to me all the time when I have a terminal open and try to use fzf for opening a buffer.

I think this should be fixed in vim itself although I am uncertain of the implementation details, but in the meantime I use the following workaround in my vimrc:
```
fun! s:workaroundIssue2190()
    " see https://github.com/vim/vim/issues/2190
    if &buftype=='terminal' && !exists('b:workaround_issue_2190')
        autocmd BufWriteCmd <buffer> echo 'workaround 2190'
        let b:workaround_issue_2190=1
    endif
endfun
aug workaroundIssue2190
    autocmd! BufWinEnter * call s:workaroundIssue2190()
aug END
```

**Comment by mattn** [comment]
Or add ignoring for write if buftype is nowrite or terminal.

```diff
diff --git a/src/ex_cmds.c b/src/ex_cmds.c
index b4351b23d..79dc01314 100644
--- a/src/ex_cmds.c
+++ b/src/ex_cmds.c
@@ -3414,6 +3414,12 @@ do_wqall(exarg_T *eap)
 		++error;
 		break;
 	    }
+
+	    if (bt_dontwrite(buf))
+	    {
+		continue;
+	    }
+
 #ifdef FEAT_BROWSE
 	    /* ":browse wall": ask for file name if there isn't one */
 	    if (buf->b_ffname == NULL && cmdmod.browse)
```

**Comment by chrisbra** [comment]
+1 for the patch  ignoring not-writable buffers.
