### ISSUE TITLE
Suppress term_start() messages

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#2191]
A command like:

```vim
 call term_start("sleep 1", { "term_finish": "close"})
```
prints `1 buffer wiped out`, even when it is prepended by `silent`. Would it be possible to make `silent` suppress such messages?

**Comment by brammool** [comment]
Lifepillar wrote:

> A command like:
> 
> ```vim
>  call term_start("sleep 1", { "term_finish": "close"})
> ```
> prints `1 buffer wiped out`, even when it is prepended by `silent`. Would it be possible to make `silent` suppress such messages?

I do not see that message.

-- 
hundred-and-one symptoms of being an internet addict:
10E. You start counting in hex.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lifepillar** [comment]
Ah right, it depends on my `vimrc` setting `report` to `0`. To reproduce:

```
vim --clean
:set report=0
:call term_start("sleep 1", { "term_finish": "close"})
```

I guess that this is intended behaviour then.
