### ISSUE TITLE
setline() should accept a buffer argument

### ISSUE THREAD

**Issue by mitermayer** [vim/vim#2193]
Now that we have async job, I wonder if we could make setline also accept a buffer name as an argument.

To give a bit more context on a example use case that this could solve:

*** 

**Formatting plugin example**

Imagine a viml plugin that formats the buffer upon file save by triggering the async job API to gather format output from a CLI tool:

1. User saves the the buffer A
2. User quickly switches to buffer B

**Expected outcome:**

Buffer A gets formatted, or no formatting happens

**Outcome:**

Buffer B gets formatted as if it was  buffer A

**Comment by k-takata** [comment]
Try `setbufline()` in [v8.0.1039](https://github.com/vim/vim/commit/b31cf2bb0be95d106bd8eef93cc07550591c1d0d).
