### ISSUE TITLE
Buffer tab-completion doesn't work when buffer name contains backslash

### ISSUE THREAD

**Issue by markonm** [vim/vim#2201]
Vim: v8.0.1184 x64
Os: Windows 10 x64

Steps to reproduce
1. `mkdir test`
2. `vim --clean`
3. `:e test\foobar`
4. `:b test\fo<tab>`
5. completions are not provided

If backslash is replaced with forward slash, completions also don't show up. On linux completions are always provided when forward slash in present inside buffer name.

**Comment by idbrii** [comment]
Dupe of #1274.

**Comment by chrisbra** [comment]
closing then.
