### ISSUE TITLE
Utilize labels

### ISSUE THREAD

**Issue by k-takata** [vim/vim#2202]
GitHub issues has labels, but we haven't utilized them. I think they are really useful.
We used labels when we used Google Code, so I think it's better to use labels based on them.

Currently, the following labels are defined.  Some of them are migrated from Google Code and others are defined by GitHub by default, so some of them are duplicated.

	auto-migrated
	bug
	duplicate
	enhancement
	help wanted
	invalid
	OpSys-Linux
	patch
	Priority-Medium
	question
	Runtime
	Type-Defect
	Type-Enhancement
	Type-Patch
	wontfix

My current proposal is as follows:

* Types:
  - defect (old: bug, Type-Defect)
  - enhancement (old: enhancement, Type-Enhancement) (including feature requests)
  - discuss

* Specific issues:
  - runtime (old: Runtime)
    - plugin-netrw
  - documentation
  - i18n (about multibyte, encoding, etc.)
    - translation (src/po/, runtime/lang/, etc.)
  - installer
  - testing
  - feature-terminal
  - feature-regex
  - (feature-channel-job)
  - (feature-packages)
  - if_lua
  - if_mzscheme
  - if_perl
  - if_python (both 2 and 3)
  - if_ruby
  - if_tcl

* Platforms:
  - platform-windows
  - (platform-unix)
    - platform-linux (old: OpSys-Linux)
    - platform-mac
    - (platform-bsd)
    - platform-cygwin

* Closed reasons:
  - duplicate
  - invalid
  - wontfix

* Others:
  - auto-migrated
  - patch (old: patch, Type-Patch)
  - question
  - help wanted
  - needs feedback

@brammool @chrisbra What do you think?

**Comment by chrisbra** [comment]
I used to use labels on the google code repository, but I am not sure it actually helped anybody. On the other hand, having a way to classify issues sounds certainly useful. So I would be fine with using new labels.

**Comment by brammool** [comment]
Ken Takata wrote:

> GitHub issues has labels, but we haven't utilized them. I think they are really useful.
> We used labels when we used Google Code, so I think it's better to use labels based on them.
> 
> Currently, the following labels are defined.  Some of them are migrated from Google Code and others are defined by GitHub by default, so some of them are duplicated.
> 
> 	auto-migrated
> 	bug
> 	duplicate
> 	enhancement
> 	help wanted
> 	invalid
> 	OpSys-Linux
> 	patch
> 	Priority-Medium
> 	question
> 	Runtime
> 	Type-Defect
> 	Type-Enhancement
> 	Type-Patch
> 	wontfix
> 
> My current proposal is as follows:
> 
> * Types:
>   - defect (old: bug, Type-Defect)
>   - enhancement (old: enhancement, Type-Enhancement)
> 
> * Specific issues:
>   - runtime (old: Runtime)
>     - plugin-netrw
>   - documentation
>   - i18n (translation, multibyte, encoding, etc.)
>   - installer
>   - testing
> 
> * Platforms:
>   - platform-windows
>   - (platform-unix)
>     - platform-linux (old: OpSys-Linux)
>     - platform-mac
>     - (platform-bsd)
>     - (platform-cygwin)
> 
> * Closed reasons:
>   - duplicate
>   - invalid
>   - wontfix
> 
> * Others:
>   - auto-migrated
>   - patch (old: patch, Type-Patch)
>   - question
>   - help wanted
>   - (needs feedback)
> 
> @brammool @chrisbra What do you think?

I don't have a preference, feel free to use labels.

-- 
You cannot propel yourself forward by patting yourself on the back.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
Thanks.
I have set the labels. I will also wait feedback from other peoples.

**Comment by k-takata** [comment]
Two months have passed and I feel this works quite well.
For example, I can easily find issues and PRs related to the terminal feature by:
https://github.com/vim/vim/labels/feature-terminal

I close this for now.

**Comment by MrScriptMaster** [comment]
Ваш отчет успешно принят и ожидает проверки.

**Comment by k-takata** [comment]
About a month ago, I created a new label "waiting feedback", but I had already created "needs feedback".
I totally forgot about that.
I deleted "waiting feedback" and changed to "needs feedback".

**Comment by MrScriptMaster** [comment]
Ваш отчет успешно принят и ожидает проверки.
