### ISSUE TITLE
Statusline is not drawn for some file-types when `lazyredraw` is set

### ISSUE THREAD

**Issue by manasthakur** [vim/vim#2211]
Since a last few months, when I have `lazyredraw` set, the `statusline` doesn't get drawn on opening some files in the beginning (a `CTRL-L` needs to be done).

This issue happens only for certain file types (e.g., my vimrc and bashrc), and does not happen for certain others (e.g., java files).

#1928 could also be related.

**Comment by chrisbra** [comment]
could you bisect the offending commit?

**Comment by manasthakur** [comment]
I don't remember exactly at which version did it start happening. However, if #1928 is related, for that complaint the Vim version included patches 1-728 (compiled July 18th). So some time before that patch, and definitely after May (based on what I remember regarding the current issue for myself).

**Comment by lacygoill** [comment]
Can you check whether https://github.com/vim/vim/commit/e7ddf4e3372fad375038ad8771c6d1a7df49c34c fixed your issue?

**Comment by lacygoill** [comment]
> Can you check whether e7ddf4e fixed your issue?

Any update?

**Comment by chrisbra** [comment]
Let's assume [v8.2.202](https://github.com/vim/vim/releases/tag/v8.2.0202) fixed that issue.
