### ISSUE TITLE
Right way to delete terminal buffers

### ISSUE THREAD

**Issue by manasthakur** [vim/vim#2215]
If I try to quit vim with an active terminal buffer, it asks me whether I want to save any changes to it. Selecting none of the options (Yes/No/Cancel) helps. Exiting from the terminal (using `exit` or `CTRL+d`), however, helps.

If I save a session before quitting and try to source it upon restart, and if the session contained an empty terminal buffer (from which I had exited using `exit` or `CTRL+d`), the empty buffer stays hovering and is of no use.

Are these bugs or am I not using terminals correctly?

**Comment by brammool** [comment]
Manas Thakur wrote:

> If I try to quit vim with an active terminal buffer, it asks me
> whether I want to save any changes to it. Selecting none of the
> options (Yes/No/Cancel) helps. Exiting from the terminal (using `exit`
> or `CTRL+d`), however, helps.
> 
> If I save a session before quitting and try to source it upon restart,
> and if the session contained an empty terminal buffer (from which I
> had exited using `exit` or `CTRL+d`), the empty buffer stays hovering
> and is of no use.
> 
> Are these bugs or am I not using terminals correctly?

First one is a bug.  The dialog should not suggest saving a terminal buffer.

Not sure yet what to do with terminal windows in the session file.
If we can detect it's a shell waiting at the prompt, we could restore
that.  But if it's another running program we probably should not.
Perhaps we should store the terminal window in the session in a way that
it won't start the command right away but only after telling Vim to do
that.


-- 
    [clop clop]
ARTHUR:  Old woman!
DENNIS:  Man!
ARTHUR:  Man, sorry.  What knight lives in that castle over there?
DENNIS:  I'm thirty seven.
ARTHUR:  What?
DENNIS:  I'm thirty seven -- I'm not old!
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ghost** [comment]
Exit terminal also need to kill its buffer, not just type exit in terminal and some plugins that base on terminal has #2215 behavior.

**Comment by brammool** [comment]
the dialog has been fixed, now asks you if you want to kill the job.
It is now possible to specify that a terminal be killed when exiting Vim.
I assume that fixes this issue.

**Comment by ghost** [comment]
It works now, `exit` on cmd terminal now close its buffer.
