### ISSUE TITLE
No "Open With Vim" on the popup menu for the right mouse button

### ISSUE THREAD

**Issue by jiangjianshan** [vim/vim#2218]
Hello, 

    I'm using Windows SDK v7.0 x64 to build the latest version of Vim. But I have found there is no "Open With Vim" on the popup menu for the right mouse button.

![vim_version](https://user-images.githubusercontent.com/20179047/31720015-f2163f5a-b447-11e7-8f79-2a2f610f884c.png)

**Comment by k-takata** [comment]
You need to install gvimext.dll.
Additionally, the directory structure for gvimext.dll was recently changed. See #2144 for detail.

**Comment by jiangjianshan** [comment]
@k-takata, thanks for your hint. Now it work.
