### ISSUE TITLE
Some words in doc/insert.txt seem to be incorrectly highlighted

### ISSUE THREAD

**Issue by lkintact** [vim/vim#2219]
There is a table of items in the insert.txt file, after "In the table is an explanation for some of the items.  The others are self explanatory.  Using the long or the short version depends on the 'shortmess' option."

The items [readonly], {RO}, [fifo], [socket], [converted] and [crypted] there are highlighted. However pressing Ctrl-] on them either yeilds a E149 error ({RO}), or takes you to unrelated places in the manual (the rest of the list).

I installed Vim with the https://github.com/vim/vim-win32-installer/releases/download/v8.0.1203/gvim_8.0.1203_x86.exe file.

**Comment by chrisbra** [comment]
those are no links that can be followed using `<c-]>`

**Comment by lkintact** [comment]
> those are no links that can be followed using <c-]>

The problem is [readonly], [fifo], [socket], [converted] and [crypted] can, they just take you to weird places...

**Comment by chrisbra** [comment]
what do you mean with `they can`? There is no helptag for those. For `readonly` we have only a helptag for `'readonly'`, all others have no tag name defined. I am not sure what you expect?

**Comment by k-takata** [comment]
When I tried them, `[readonly]` jumped to `e`, `[fifo]` to `o`, `[socket]` to `t`, `[converted]` to `r`, and `[crypted]` to `y`. It seems that they are parsed as regexps (or something). Not sure this behavior is intended.

**Comment by k-takata** [comment]
`:help CTRL-]` says 'Same as ":tag {ident}", where {ident} is the keyword under or after cursor.'
And `:help :tag` says '{ident} can be a regexp pattern'.

**Comment by lkintact** [comment]
>what do you mean with they can?

I meant what **k-takata** said, but `[readonly]` jumps to _`n`_, `[socket]` to _`s`_,` [converted]` to _`d`_ and `[crypted]` to _`c`_  for me. (`[fifo]` jumps to `o` too). Sorry for not making it clear.

**Comment by chrisbra** [comment]
yes, this is expected. See also the help:
https://github.com/vim/vim/blob/master/runtime/doc/helphelp.txt#L34-L54

closing.
