### ISSUE TITLE
Save changes to "!C:\WINDOWS\system32\cmd.exe"?

### ISSUE THREAD

**Issue by mattn** [vim/vim#2223]
When closing gvim.exe with [X] button on Window, this confirm dialog is shown. But this is strange message. Bram, do you have ideas to correct this?

**Comment by brammool** [comment]
I wrote down this problem but haven't worked on a solution yet.  Should at least not suggest to save changes for a terminal window.

**Comment by brammool** [comment]
Also see #2215

**Comment by brammool** [comment]
Fixed now.
