### ISSUE TITLE
commentstring incorrect for filetype 'gdb'

### ISSUE THREAD

**Issue by xeyownt** [vim/vim#2225]
For gdb file (like `.gdbinit`), `commentstring` is left to the default value `/*%s*/`, where the correct value should be `#%s`.

The following line must be added to `./runtime/ftplugin/gdb.vim`:

``` vim
" Vim filetype plugin file
" Language:	gdb

if exists("b:did_ftplugin") | finish | endif
let b:did_ftplugin = 1

setlocal commentstring=#%s

" Undo the stuff we changed.
let b:undo_ftplugin = "setlocal cms<"
```

**Comment by xeyownt** [comment]
Note that this can be easily fixed by creating a file `.vim/ftplugin/gdb.vim` with content:

``` vim
setlocal commentstring=#%s
```

**Comment by chrisbra** [comment]
perhaps you would like to contribute and become maintainer of the ftplugin/gdb.vim file?

**Comment by chrisbra** [comment]
btw: this really does not belong in the syntax script.

**Comment by xeyownt** [comment]
Oups sorry, that was a typo. Indeed, it must be in ftplugin. I edited the first post.

**Comment by brammool** [comment]
Included the ftplugin.
