### ISSUE TITLE
Please update bindzone.vim

### ISSUE THREAD

**Issue by zdohnal** [vim/vim#2226]
Hi,

I see Vim is using older version of bindzone.vim. bindzone.vim from this project https://github.com/Absolight/vim-bind is newer and highlighting is better - would you mind adding it into the project?

**Comment by chrisbra** [comment]
you should check with the repository owner, if he would like to have his script distributed with vim (also this makes sure, we are allowed to distribute it). But then you should also check what problems the current bindzone.vim has and reach out for its maintainer to have it checked

**Comment by chrisbra** [comment]
closing, as there is not really much to do here for Vim
