### ISSUE TITLE
Empty statusline group not removed if it contains highlighting changes

### ISSUE THREAD

**Issue by mgedmin** [vim/vim#2227]
I'm trying to have my status line show

- filename
- space
- all the standard flags ([+], [RO] etc.) and some non-standard flags (e.g. Syntastic error count)
- space
- name of the function that my cursor is in

![example statusline screenshot](https://user-images.githubusercontent.com/159967/31830957-798e4b0c-b5ca-11e7-8b11-969db3eea7db.png)

When there are no flags, I would like to see a single space between the filename and the function name.
To do that, I'm wrapping the space and the flags inside a `%(...%)` group.

This doesn't work if I change the highlighting group of my custom flags using `%1*` or `%#error#`: the group is not considered to be empty, and I end up with two consecutive spaces.

## Steps to reproduce

I'll illustrate with a simplified example, that replaces my custom `%{FunctionCalls()}` with a constant empty string expression:

- `:set statusline=[%(\ %{''})]`
- it will be rendered as `[]` because the empty group gets collapsed, as documented
- now `:set statusline=[%(\ %1*%{''}%*)]`

## Expected behavior

- same as before, i.e. rendering as `[]`

## Actual behavior

- this shows up as `[ ]`

This bug was introduced in Vim patch 7.4.1511 (commit af6e36ff16736106a1bc63bb4d01f51fdfeb29a2).

**Comment by chrisbra** [comment]
closing for #2228
