### ISSUE TITLE
Error while parsing commas preceded by space in function definitions

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#2235]
To reproduce:

```
cd ~/.vim
mkdir -p pack/somewhere/start/{foo,foo/autoload/foo}
vim --clean pack/somewhere/start/foo/autoload/foo/bar.vim
```

Write the following content inside `bar.vim` and save the file:

```vim
fun! foo#bar#xyz(a ,b)
endf
```

Then, `:source %`. You should get the following error:

```
Error detected while processing /Users/me/.vim/pack/somewhere/start/foo/autoload/foo/bar.vim:
line    1:
E475: Invalid argument: a ,b)
line    2:
E193: :endfunction not inside a function
```

If you remove the space before comma everything goes fine.

**Comment by ZyX-I** [comment]
This is not related to autoload at all, just any function definition will show this problem. So neither you need any files for the test: `echo execute(['function Foo(a , b)', 'endfunction'])`.

**Comment by lifepillar** [comment]
Thanks, I have updated the subject accordingly.

**Comment by vim-ml** [comment]
On Mo, 23 Okt 2017, Lifepillar wrote:

> Thanks, I have updated the title accordingly.

https://groups.google.com/d/msg/vim_dev/avHBxP-_coc/RPRR_syQxh4J

Christian
-- 
Zeichnen ist Sprache für die Augen, Sprache ist Malerei für das Ohr.
		-- Joseph Joubert

**Comment by ZyX-I** [comment]
By the way, issue also applies to lambdas, though it gives more confusing error message (like E121: Undefined variable). I like allowing whitespace more because it is allowed in other places where comma is present: lists and dictionaries.

**Comment by lacygoill** [comment]
The issue persists in Vim9 script:
```vim
vim9script
def Func(a: any , b: any)
enddef
```
    E475: Invalid argument: a: any , b: any)
```vim
vim9script
var Ref = (a , b) => 0
```
    E121: Undefined variable: a

`E1059` would be much easier to understand in both cases.  Just like in these snippets:
```vim
vim9script
def Func(a : any)
enddef
```
    E1059: No white space allowed before colon: a
```vim
vim9script
var Ref = (a : any) => 0
```
    E1059: No white space allowed before colon: a : any) => 0
    E1059: No white space allowed before colon: a

Also, it's a bit weird for `E1059` to be raised twice in the last one.

**Comment by lacygoill** [comment]
> Also, it's a bit weird for E1059 to be raised twice in the last one.

Actually, the first message is better than the second one, because it gives more context.  So, right now, we have:

    :def function
    ┌────────────────────────┬────────────────────────────────┐
    │ extra wsp before comma │ extra wsp before colon         │
    ├────────────────────────┼────────────────────────────────┤
    │ E475 (confusing)       │ E1059 (without enough context) │
    └────────────────────────┴────────────────────────────────┘

    lambda
    ┌────────────────────────┬────────────────────────────────┐
    │ extra wsp before comma │ extra wsp before colon         │
    ├────────────────────────┼────────────────────────────────┤
    │ E121 (confusing)       │ E1059 (with enough context)    │
    │                        │ E1059 (without enough context) │
    └────────────────────────┴────────────────────────────────┘

It would be better if we had:

    :def function
    ┌─────────────────────────────┬─────────────────────────────┐
    │ extra wsp before comma      │ extra wsp before colon      │
    ├─────────────────────────────┼─────────────────────────────┤
    │ E1059 (with enough context) │ E1059 (with enough context) │
    └─────────────────────────────┴─────────────────────────────┘

    lambda
    ┌─────────────────────────────┬─────────────────────────────┐
    │ extra wsp before comma      │ extra wsp before colon      │
    ├─────────────────────────────┼─────────────────────────────┤
    │ E1059 (with enough context) │ E1059 (with enough context) │
    └─────────────────────────────┴─────────────────────────────┘
