### ISSUE TITLE
No access to context from remote

### ISSUE THREAD

**Issue by albfan** [vim/vim#2237]
Say I define a function

```
function Foo(arg1, arg2)
  let b = a:arg1.' '.a:arg2
  let c = 5
endfunction
```

you source it

    gg"zyG
    :exec @z

and define a breakpoint on it

    breaka func Foo

after run it

    call Foo('Hello', 'World')

when you are debugging line 2 (next) `let c=`

you can ask about `b` value

    echo b
    Hello World

but if you run vim with `--servername myserver`

calling from another vim instance

    echo remote_expr('MYSERVER', 'b')

returns

    E449 Invalid expression

this is because when calling remote_expr local context is not loaded

https://github.com/vim/vim/blob/2a6a6c3014e728cd01c750b0f60484d4eaf22a8c/src/eval.c#L7429

meanwhile from local debug session it is loaded

Is this on purpose? can local var mapping be populated for remote execution.

I feel this is changing from vim 7.4. My plan is to compile vim 7.4 and check if that works then (I guess because I have a plugin for remote debug that use to work)

**Comment by albfan** [comment]
Confirmed: Using vim 7.4 I can ask from remote about every variable:

    echo remote_expr('MYSERVER', 'a:arg1')
    echo remote_expr('MYSERVER', 'a:arg2')
    echo remote_expr('MYSERVER', 'b')

@chrisbra (sorry to ping) is this unexpected? is on purpose?

**Comment by chrisbra** [comment]
I would say this is unexpected. Can you find which commit broke it or even better propose a patch?

**Comment by brammool** [comment]
Alberto Fanjul wrote:

> Say I define a function
> 
> ```
> function Foo(arg1, arg2)
>   let b = a:arg1.' '.a:arg2
>   let c = 5
> endfunction
> ```
> 
> you source it
> 
>     gg"zyG
>     :exec @z
> 
> and define a breakpoint on it
> 
>     breaka func Foo
> 
> after run it
> 
>     call Foo('Hello', 'World')
> 
> when you are debugging line 2 (next) `let c=`
> 
> you can ask about `b` value
> 
> echo b
> Hello World
> 
> but if you run vim with `--servername myserver`
> 
> calling from another vim instance
> 
>     call remote_expr('MYSERVER', 'echo b')
> 
> returns
> 
>     E449 Invalid expression
> 
> this is because when calling remote_expr local context is not loaded
> 
> https://github.com/vim/vim/blob/2a6a6c3014e728cd01c750b0f60484d4eaf22a8c/src/eval.c#L7429
> 
> meanwhile from local debug session it is loaded
> 
> Is this on purpose? can local var mapping be populated for remote execution.
> 
> I feel this is changing from vim 7.4. My plan is to compile vim 7.4
> and check if that works then (I guess because I have a plugin for
> remote debug that use to work)

It has been like this for a while.  Evaluating function-local variables
was considered a bug. eval_client_expr_to_string() calls
clear_current_funccal().

Debugging is a special case that was not considered.  Perhaps in debug
state clear_current_funccal() could be skipped.

-- 
BLACK KNIGHT:  I move for no man.
ARTHUR:        So be it!
    [hah] [parry thrust]
    [ARTHUR chops the BLACK KNIGHT's left arm off]
ARTHUR:        Now stand aside, worthy adversary.
BLACK KNIGHT:  'Tis but a scratch.
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by albfan** [comment]
comparing last v7.4 tag (v7.4.2367) with master I found that function free_all_functions() adds a loop

https://github.com/vim/vim/blob/master/src/userfunc.c#L1166

```
@@ -1120,10 +1156,47 @@ free_all_functions(void)
     hashitem_T *hi;
     ufunc_T    *fp;
     long_u     skipped = 0;
-    long_u     todo;
+    long_u     todo = 1;
+    long_u     used;
+
+    /* Clean up the call stack. */
+    while (current_funccal != NULL)
+    {
+       clear_tv(current_funccal->rettv);
+       cleanup_function_call(current_funccal);
+    }
```
that ends with current_funccal as NULL

I guess that's the change that modifies the behaviour. Should I provide a PR with check around it if there's an ongoing debug session? Don't know if it is that simple

**Comment by chrisbra** [comment]
> Should I provide a PR with check around it if there's an ongoing debug session? Don't know if it is that simple

Sure, patches are appreciated, especially if they contain a test case.

**Comment by albfan** [comment]
I think I can add something to https://github.com/vim/vim/blob/master/src/testdir/test_clientserver.vim

Is the only use case I now about this

**Comment by albfan** [comment]
Is there any recommended way to compile for debug? I don't have debug symbols and don't know if it is from package manager or from compilation itself

I use this instructions 

configure https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/vim#n68
make https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/vim#n86
make install https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/vim#n192

I added options=(debug !strip) to avoid stripping and keep debug symbols (specific for arch linux distro)
 
I know I can add CFLAGS='-ggdb -O0' but if is there any configure option or recommended make option please let me know

**Comment by chrisbra** [comment]
I am using those switches:
https://github.com/chrisbra/vim/commit/78740807655cece3b0ee62495d9b23d6fc8fdb56

**Comment by albfan** [comment]
Ok, I have an initial patch.

plese review, I don't feel comfortable with the if else logic

Working on test case, (use case described here) maybe today later. Is ok to add to clientserver test or is better in a new one

**Comment by albfan** [comment]
I was editing comments, because some commands were wrong

I have reworked the use case

```
function! Bar(argBar1, argBar2)
  let c = 6
  return a:argBar1.' '.a:argBar2
endfunction

function! Foo(argFoo1, argFoo2)
  let c = 5
  let b = Bar(a:argFoo1, a:argFoo2)
  echo b.' '.c
endfunction
```

Stopping on

    breakadd func 2 Bar

it works correctly with `up` and `down` backtrace commands. `c` var shows 5 and 6 correctly

So I will add that to test case and submit a PR
