### ISSUE TITLE
Patch for /src/Make_mvc.mak

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vim/vim#224]
```
Use _MSC_VER to achieve cl.exe version. 
```

Original issue reported on code.google.com by `nobu.nak...@gmail.com` on 13 May 2014 at 4:29

Attachments:
- [Make_mvc.mak.patch](https://storage.googleapis.com/google-code-attachments/vim/issue-224/comment-0/Make_mvc.mak.patch)

**Comment by k-takata** [comment]
Fixed with 7.4.960.
Now we can close #496, #509 and this.

@raymond-w-ko @nanis Thank you for testing this patch.

**Comment by nanis** [comment]
You are welcome. 7.4.960 built with no problems on Windows 10 with VS2015.1. Thank you.
