### ISSUE TITLE
Should an omnifunc change the cursor position?

### ISSUE THREAD

**Issue by casr** [vim/vim#2240]
Over at [yami-beta/asyncomplete-omni.vim#4](https://github.com/yami-beta/asyncomplete-omni.vim/issues/4) I noticed that the cursor would jump around because that plugin would repeatedly call the `omnifunc` to find new potential completions. Ordinarily that is not a problem but in the case of HTML the cursor is actually moved by it.

So I wanted to open discussion about whether this appropriate for an `omnifunc` to manage. Have a look at the [HTML `omnifunc` to see it in more detail](https://github.com/vim/vim/blob/master/runtime/autoload/htmlcomplete.vim#L97).

**Comment by chrisbra** [comment]
So this is actually a question, whether a omni-completion function is allowed to move the cursor?

**Comment by casr** [comment]
Yes, loosely. I wasn't necessarily thinking that it should be enforceably banned but perhaps considered poor form and therefore removed from the base distribution. I can see how the title is misleading so I will change that.

However, having written precisely zero `omnifunc`s in my life, I am not exactly the pillar of knowledge on this topic.

So, more directly, should `omnifunc`s be using `call cursor(...)` at all? Or perhaps it is a nuanced thing were in some cases it is appropriate and other not?

**Comment by chrisbra** [comment]
I think this is okay. According to the [documentation](http://vimhelp.appspot.com/insert.txt.html#E840):

> The function is allowed to move the cursor, it is restored afterwards.
> The function is not allowed to move to another window or delete text.

Other then that terse statement, I would not say that setting the cursor is considered poor form, but might actually be necessary to analyze the current buffer, so does depend on the actually requirement for the omni function. 

I am closing this. Feel free to ask at the vim-dev or vim-use mailinglist to get more opinions from other users.

**Comment by casr** [comment]
Okay, makes sense. Thanks for the information!
