### ISSUE TITLE
shift exponent -1 is negative in spell_read_wordfile()

### ISSUE THREAD

**Issue by geeknik** [vim/vim#2252]
Triggered in `67435d9`, compiled with clang 6.0.0-trunk and `-fsanitize=address,undefined`.

./vim -u NONE -X -Z -e -s -S test028 ':qa!'

```
spellfile.c:4286:23: runtime error: shift exponent -1 is negative
    #0 0x1080f99 in spell_read_wordfile /root/vim/src/spellfile.c:4286:23
    #1 0x1080f99 in mkspell /root/vim/src/spellfile.c:6123
    #2 0x10aafee in spell_add_word /root/vim/src/spellfile.c:6390:2
    #3 0x7d4058 in do_one_cmd /root/vim/src/ex_docmd.c:2908:2
    #4 0x7bc866 in do_cmdline /root/vim/src/ex_docmd.c:1071:17
    #5 0x7ae076 in do_source /root/vim/src/ex_cmds2.c:4355:5
    #6 0x7ab31c in cmd_source /root/vim/src/ex_cmds2.c:3968:14
    #7 0x7ab31c in ex_source /root/vim/src/ex_cmds2.c:3943
    #8 0x7d4058 in do_one_cmd /root/vim/src/ex_docmd.c:2908:2
    #9 0x7bc866 in do_cmdline /root/vim/src/ex_docmd.c:1071:17
    #10 0x13f138f in exe_commands /root/vim/src/main.c:2954:2
    #11 0x13f138f in vim_main2 /root/vim/src/main.c:799
    #12 0x13e5d3d in main /root/vim/src/main.c:415:12
    #13 0x7f1d961853f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)
    #14 0x41bba9 in _start (/root/vim/src/vim+0x41bba9)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior spellfile.c:4286:23
```
[test028.gz](https://github.com/vim/vim/files/1418767/test028.gz)

**Comment by brammool** [comment]
geeknik wrote:

> Triggered in `67435d9`, compiled with clang 6.0.0-trunk and `-fsanitize=address,undefined`.
> 
> ./vim -u NONE -X -Z -e -s -S test028 ':qa!'
> 
> ```
> spellfile.c:4286:23: runtime error: shift exponent -1 is negative
>     #0 0x1080f99 in spell_read_wordfile /root/vim/src/spellfile.c:4286:23
>     #1 0x1080f99 in mkspell /root/vim/src/spellfile.c:6123
>     #2 0x10aafee in spell_add_word /root/vim/src/spellfile.c:6390:2
>     #3 0x7d4058 in do_one_cmd /root/vim/src/ex_docmd.c:2908:2
>     #4 0x7bc866 in do_cmdline /root/vim/src/ex_docmd.c:1071:17
>     #5 0x7ae076 in do_source /root/vim/src/ex_cmds2.c:4355:5
>     #6 0x7ab31c in cmd_source /root/vim/src/ex_cmds2.c:3968:14
>     #7 0x7ab31c in ex_source /root/vim/src/ex_cmds2.c:3943
>     #8 0x7d4058 in do_one_cmd /root/vim/src/ex_docmd.c:2908:2
>     #9 0x7bc866 in do_cmdline /root/vim/src/ex_docmd.c:1071:17
>     #10 0x13f138f in exe_commands /root/vim/src/main.c:2954:2
>     #11 0x13f138f in vim_main2 /root/vim/src/main.c:799
>     #12 0x13e5d3d in main /root/vim/src/main.c:415:12
>     #13 0x7f1d961853f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)
>     #14 0x41bba9 in _start (/root/vim/src/vim+0x41bba9)
> 
> SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior spellfile.c:4286:23
> ```
> [test028.gz](https://github.com/vim/vim/files/1418767/test028.gz)

Thanks for reporting.  There was a check for the region being too high,
but not for it being zero.  I'll add that.

-- 
Time flies like an arrow.
Fruit flies like a banana.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
