### ISSUE TITLE
How to compile 64-bit vim in Windows

### ISSUE THREAD

**Issue by ghost** [vim/vim#2257]
I am in Windows and platform is amd64.
I used this command:
`nmake -f Make_mvc.mak CPU=AMD64 GUI=yes OLE=yes PYTHON3=C:\Programs\Miniconda3 DYNAMIC_PYTHON3=yes PYTHON3_VER=36 LUA=C:\Programs\LUA\DLL DYNAMIC_LUA=yes LUA_VER=53 IME=yes CSCOPE=yes`
And I use
`gvim +version`
It shows this:

> VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 27 2017 19:57:04)
MS-Windows 32-bit GUI version with OLE support
Included patches: 1-1226
Compiled by vize_@LOCALPC
Huge version with GUI.  Features included (+) or not (-):
+acl                +ex_extra           +multi_byte_ime/dyn -tag_any_white
+arabic             +extra_search       +multi_lang         -tcl
+autocmd            +farsi              -mzscheme           -termguicolors
+balloon_eval       +file_in_path       +netbeans_intg      +terminal
+browse             +find_in_path       +num64              -tgetent
++builtin_terms     +float              +ole                -termresponse
+byte_offset        +folding            +packages           +textobjects
+channel            -footer             +path_extra         +timers
+cindent            +gettext/dyn        -perl               +title
+clientserver       -hangul_input       +persistent_undo    +toolbar
+clipboard          +iconv/dyn          -postscript         +user_commands
+cmdline_compl      +insert_expand      +printer            +vertsplit
+cmdline_hist       +job                +profile            +virtualedit
+cmdline_info       +jumplist           -python             +visual
+comments           +keymap             +python3/dyn        +visualextra
+conceal            +lambda             +quickfix           +viminfo
+cryptv             +langmap            +reltime            +vreplace
+cscope             +libcall            +rightleft          +wildignore

So how can I compile a 64-bit vim with gui in Windows (VisualStudio)?

**Comment by chrisbra** [comment]
please have a look at https://github.com/vim/vim/blob/master/src/INSTALLpc.txt
and https://github.com/vim/vim/blob/master/src/msvc2015.bat

**Comment by ghost** [comment]
Thanks. I've recompiled it without OLE support and used VS x64 Native Tools, and it works properly.
