### ISSUE TITLE
Condition is always true in vim_str2nr

### ISSUE THREAD

**Issue by ZyX-I** [vim/vim#2259]
vim_str2nr has the following code to detect octal numbers:

```C
	    /* decimal or octal, default is decimal */
	    pre = 0;
	    if (what & STR2NR_OCT)
	    {
		/* Don't interpret "0", "08" or "0129" as octal. */
		for (n = 1; VIM_ISDIGIT(ptr[n]); ++n)
		{
		    if (ptr[n] > '7')
		    {
			pre = 0;	/* can't be octal */
			break;
		    }
		    if (ptr[n] >= '0')
			pre = '0';	/* assume octal */
		    if (n == maxlen)
			break;
		}
	    }

```

you may see here a line `if (ptr[n] >= '0')` while `n` does not change in a cycle body and cycle condition is `VIM_ISDIGIT(ptr[n])`, so this condition should always be true and cannot actually do what intended (what, BTW?).

**Comment by brammool** [comment]
Nikolai Pavlov wrote:

> vim_str2nr has the following code to detect octal numbers:
> 
> ```C
> 	    /* decimal or octal, default is decimal */
> 	    pre = 0;
> 	    if (what & STR2NR_OCT)
> 	    {
> 		/* Don't interpret "0", "08" or "0129" as octal. */
> 		for (n = 1; VIM_ISDIGIT(ptr[n]); ++n)
> 		{
> 		    if (ptr[n] > '7')
> 		    {
> 			pre = 0;	/* can't be octal */
> 			break;
> 		    }
> 		    if (ptr[n] >= '0')
> 			pre = '0';	/* assume octal */
> 		    if (n == maxlen)
> 			break;
> 		}
> 	    }
> 
> ```
> 
> you may see here a line `if (ptr[n] >= '0')` while `n` does not change
> in a cycle body and cycle condition is `VIM_ISDIGIT(ptr[n])`, so this
> condition should always be true and cannot actually do what intended
> (what, BTW?).

I believe that:
 		    if (ptr[n] >= '0')
Should be:
 		    if (ptr[n] >= '1')
Then it does what the comment states: "0", "00", etc. are not recognized
as octal.

However, this changes how CTRL-X works.  Before "00" would go to
"01777777777777777777777", now it goes to -1.  There has been a lot of
discussion about the existing behavior, I rather not change how it
works.  Most users will want to remove "octal" from 'nrformats' anyway.
So removing the condition that is always true is the best solution.



-- 
TIM: To the north there lies a cave,  the cave of Caerbannog, wherein, carved
     in mystic runes, upon the very living rock, the last words of Olfin
     Bedwere of Rheged make plain the last resting place of the most Holy
     Grail.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
