### ISSUE TITLE
cfg has no setting for commentstring

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vim/vim#226]
```
What steps will reproduce the problem?
1. open a file which happens vim happens to pick as [cfg], ~/.hgrc happens to 
be such a file
2. attempt to comment lines using any commenting plugin; for instance, 
vim-commentary
3. be greeted with c-style comments

What is the expected output? What do you see instead?
The lines

[extensions]
pager =

when commented, should be

# [extensions]
# pager =

not

/* [extensions] */
/* pager = */

I'm not aware of a generic config file that benefits from cms=/*%s*/

What version of the product are you using? On what operating system?
7.4-307

Please provide any additional information below.

This could be fixed by including an `ftplugin/cfg.vim` adapted from 
`ftplugin/conf.vim` or perhaps some other way.


```

Original issue reported on code.google.com by `muffinpo...@gmail.com` on 31 May 2014 at 3:47

**Comment by marciomazza** [comment]
+1

**Comment by chrisbra** [comment]
Did your +1 mean, you volunteer to maintain that file?

**Comment by chrisbra** [comment]
Here is a patch:
```patch
+" Vim filetype plugin file
+" Language:             Configuration File
+" Previous Maintainer:  Christian Brabandt <cb@256bit.org>
+" Latest Revision:      2018-12-24
+
+if exists("b:did_ftplugin")
+  finish
+endif
+let b:did_ftplugin = 1
+
+let s:cpo_save = &cpo
+set cpo&vim
+
+let b:undo_ftplugin = "setl cms< fo<"
+
+setlocal commentstring=#\ %s formatoptions-=t formatoptions+=croql
+
+let &cpo = s:cpo_save
+unlet s:cpo_save
```

@brammool feel free to add this file to the $VIMRUNTIME/ftplugin and leave me as maintainer.

**Comment by brammool** [comment]
Christian Brabandt wrote:

> Here is a patch:
> ```patch
> +" Vim filetype plugin file
> +" Language:             Configuration File
> +" Previous Maintainer:  Christian Brabandt <cb@256bit.org>

Not sure why you put "Previous" here, I'll assume it's a leftover from
copy&paste.

> @brammool feel free to add this file to the $VIMRUNTIME/ftplugin and leave me as maintainer. 

Thanks, I'll include it.

-- 
Light travels faster than sound.  This is why some people
appear bright until you hear them speak

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
> Not sure why you put "Previous" here, I'll assume it's a leftover from copy&paste.

indeed, sorry for that.

> Thanks, I'll include it.

closing then.
