### ISSUE TITLE
Fatal Python error: Py_Initialize: unable to load the file system codec

### ISSUE THREAD

**Issue by ghost** [vim/vim#2261]
I've compiled vim with 
`nmake -f Make_mvc.mak CPU=AMD64 GUI=no TERMINAL=yes PYTHON3=C:\Programs\Miniconda3 DYNAMIC_PYTHON3=yes PYTHON3_VER=36 LUA=C:\Programs\LUA\DLL DYNAMIC_LUA=yes LUA_VER=53 IME=yes CSCOPE=yes` on Windows(amd64)
And uses Miniconda as a Python Environment.
It's similar to [#1550](https://github.com/vim/vim/issues/1550) issue.
And I've tried to use the plugin:
`Plug 'cjrh/vim-conda'`
When I run vim, it shows

> Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'
Current thread 0x0000023c (most recent call first):

And it exited.
I used `vim -N -u NONE`
When I entered`:py3 import sys`
It shows

> Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: '
Current thread 0x):

So how to solve the problem?

**Comment by chrisbra** [comment]
> ModuleNotFoundError: No module named 'encodings'

And do you have that module? In general, I am not sure, we support anything other then the normal python installation for the reasons explained in #1550.

**Comment by vize-xpft** [comment]
@chrisbra 
I have that module.

> Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 12:30:02) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
\>>> import encodings

And no exceptions appeared.

**Comment by ghost** [comment]
It seemed like my conda has some problem. I've reinstalled it and it works right.
