### ISSUE TITLE
Double enter to open a file in terminal

### ISSUE THREAD

**Issue by ghost** [vim/vim#2262]
This behavior comes with fzf. I use fzf.vim, it's based on terminal to display output through terminal, and I have to double to open a file. Trigger fzf, gvim's title become `!cmd.exe` --> choose file, still `!cmd.exe`, first enter--> still `!cmd.exe`, need to make another enter here to exit cmd and enter normal mode on file.  

I think this problem caused by terminal itself, not fzf. Hope this is on your radar.

Gvim/windows 10

**Comment by chrisbra** [comment]
please give exact reproduction steps.

**Comment by ghost** [comment]
I run this command `C:\Users\YYYYY>gvim.exe -u NONE --cmd "set nocp | set rtp+=C:\Users\YYYYY\vimfiles\pack\plugins\start\fzf | runtime! plugin/fzf.vim"`, please refer to [this video](https://drive.google.com/file/d/0BzNBUeqn5ZK5YVZYYndZd056S3c/view?usp=sharing) to see the result.

**Comment by chrisbra** [comment]
and then? what do you do with fzf?

**Comment by ghost** [comment]
If I understand right, the command will load only fzf plugin without vimrc. It's pure fzf plugin to run in gvim that use terminal.  
Hmm, now I'm not sure this issue from terminal itself, but what I can tell? The expected behavior should be choose file from fzf, press enter, open the file and ready to use in normal mode, the extra enter to bring the file to normal mode is not expected.

**Comment by k-takata** [comment]
Maybe related to #1998.

**Comment by chrisbra** [comment]
please give simple reproducible steps starting from `vim --clean`. I am sorry, I can't hardly understand you.

**Comment by ghost** [comment]
Sorry, this issue happens when use vim with fzf.
