### ISSUE TITLE
'set showcmd' messes up mappings when the {rhs} is longer than the screen width

### ISSUE THREAD

**Issue by marcelpaulo** [vim/vim#2268]
Just to give some context to how I bumped into this issue: before adding a classical music CD to my mp3 collection, I usually edit the track titles with vim. Certain pieces have movements, for instance:

> String Quartet in F major, Op 12: Moderato alla breve
> String Quartet in F major, Op 12: Andante moderato
> String Quartet in F major, Op 12: Scherzo: Allegretto vivace
> String Quartet in F major, Op 12: Finale: Allegro con spirito

Instead of numbering the movements manually, I wrote a rudimentary vimscript function that numbers the movements within a visually selected area. In the example above, this should be the result:

> String Quartet in F major, Op 12: 1. Moderato alla breve
> String Quartet in F major, Op 12: 2. Andante moderato
> String Quartet in F major, Op 12: 3. Scherzo: Allegretto vivace
> String Quartet in F major, Op 12: 4. Finale: Allegro con spirito

Here's the function and the corresponding mapping:

```
function! NumberClassical(area)
    let lines = split(a:area, "\n")
    let result = ''
    let n = 1
    for line in lines
	let result = result . substitute(line, '\(^[^:]\+: \)\@<=', n . '. ', '') . "\n"
	let n = n + 1
    endfor
    return result
endfunction
vnoremap \n y:call setreg('', NumberClassical(getreg('')), getregtype(''))<CR>gvp

```
I set the width of gvim instances to **80 columns**, in _.gvimrc_. If I visually select those songs and run the mapping by pressing _\n_, this is the result:

> String Quartet in F major, Op 12: 1. Moderato alla breve
> String Quartet in F major, Op 12: 2. Andante moderato
> String Quartet in F major, Op 12: 3. Scherzo: Allegretto vivace
> String Quartet in F major, Op 12: 4. Finale: Allegro con spirito
> tring Quartet in F major, Op 12: Moderato alla breve
> String Quartet in F major, Op 12: Andante moderato
> String Quartet in F major, Op 12: Scherzo: Allegretto vivace
> String Quartet in F major, Op 12: Finale: Allegro con spirito

It is as if **_v_** were executed instead of **_gv_**, selecting the first **S** in the first line and replacing it with the unnamed register. If I enlarge the gvim instance to, let's say, 100 columns, and run _\n_ again, it works correctly, with this result:

> String Quartet in F major, Op 12: 1. Moderato alla breve
> String Quartet in F major, Op 12: 2. Andante moderato
> String Quartet in F major, Op 12: 3. Scherzo: Allegretto vivace
> String Quartet in F major, Op 12: 4. Finale: Allegro con spirito

If I remove `set showcmd`, it works correctly irrespective of screen width.

The whole `vnoremap` command has 81 characters, and the mapping only works correctly, when `showcmd` is on, if the screen width is slightly larger than these 81 characters. So, the minimal steps to reproduce the issue:

1. Create a _.gvimrc_ file with this line:
`set columns=80`

2. Create a _.vimrc_ file with these lines:
```
set showcmd
function! NumberClassical(area)
    let lines = split(a:area, "\n")
    let result = ''
    let n = 1
    for line in lines
	let result = result . substitute(line, '\(^[^:]\+: \)\@<=', n . '. ', '') . "\n"
	let n = n + 1
    endfor
    return result
endfunction
vnoremap \n y:call setreg('', NumberClassical(getreg('')), getregtype(''))<CR>gvp
```
3. Edit a file with these lines:
```
String Quartet in F major, Op 12: Moderato alla breve
String Quartet in F major, Op 12: Andante moderato
String Quartet in F major, Op 12: Scherzo: Allegretto vivace
String Quartet in F major, Op 12: Finale: Allegro con spirito
```
4. Visually linewise select the 4 lines, and run the mapping, pressing \n. It will produce the wrong result:
```
String Quartet in F major, Op 12: 1. Moderato alla breve
String Quartet in F major, Op 12: 2. Andante moderato
String Quartet in F major, Op 12: 3. Scherzo: Allegretto vivace
String Quartet in F major, Op 12: 4. Finale: Allegro con spirito
tring Quartet in F major, Op 12: Moderato alla breve
String Quartet in F major, Op 12: Andante moderato
String Quartet in F major, Op 12: Scherzo: Allegretto vivace
String Quartet in F major, Op 12: Finale: Allegro con spirito
```
5. Undo these changes

6. Remove this line from _.vimrc_, save and resource it:
`set showcmd`

7. Repeat **(4)**. This time, the correct and expected results will be shown:
```
String Quartet in F major, Op 12: 1. Moderato alla breve
String Quartet in F major, Op 12: 2. Andante moderato
String Quartet in F major, Op 12: 3. Scherzo: Allegretto vivace
String Quartet in F major, Op 12: 4. Finale: Allegro con spirito
```
Apologies if this was too much long-winded. Please let me know how I can help to get to the root cause of this issue.

**EDIT:** I'm running **gvim 8.0.0197-4ubuntu5** (from package **vim-gtk3**) on Xubuntu 17.10. I tried the GTK2 version (package **vim-gtk**) but the results were the same.

**Comment by chrisbra** [comment]
I cannot seem to reproduce this on  8.0.1238 , neither with gtk3 gui nor with the terminal version. Can you check with a more recent version? Also can you show the output of `:vmap \n`?  after sourcing your vimrc?

**Comment by marcelpaulo** [comment]
Hey, @chrisbra , thanks for the swift response !

Here's the output of :vmap \n

![screenshot_2017-10-31_12-04-57](https://user-images.githubusercontent.com/10074769/32227977-fccc7cde-be33-11e7-8dad-e9737b08b224.png)

I hadn't tested with the terminal version, have just done it now, and it behaves likewise, I mean, the issue is also there.

I'll try with a more recent version and let you know.

**Comment by marcelpaulo** [comment]
@chrisbra, I've just built and tried **8.0.1240**: the issue is still there, both with the gtk gui and the terminal version :-(

I didn't mention before, but all I have under _~/.vim_ is _~/.vim/after/ftplugin/sh.vim_:
`setlocal formatoptions+=croq`

**Comment by chrisbra** [comment]
strange. The after file should not interfer. Is this on windows or on unix? I cannot reproduce it. Can you run it under valgrind?

**Comment by marcelpaulo** [comment]
> Is this on windows or on unix?

Xubuntu 17.10

> Can you run it under valgrind?

Will do it and post back the results.

Thanks, @chrisbra 

**EDIT:** Any particular things you want me to check with valgrind ?

**Comment by marcelpaulo** [comment]
Can't get debugging info into the executables. Changed this in _src/Makefile_:
```
CFLAGS = -g
LEAK_CFLAGS = -DEXITFREE
```
then run `make reconfigure`. Reinstalled and then run valgrind:

`valgrind -tool=callgrind --trace-children=yes /usr/local/bin/gvim -f ~/data/rimsky-korsakov_tracks`

Selected the 4 lines, run \n, then quit. Peeked at the call tree with `kcachegrind` but no source code info is included. Just in case, here's the [callgrind.out file](https://1drv.ms/u/s!AlsiEMDuBseItDA2jhIjPMiAYbpw).

Pardom my lack of experience. If I'm not abusing, could you give me some pointers on how to get the info you need from valgrind ?

**Comment by chrisbra** [comment]
Okay, could finally reproduce it. This is really a subtle bug popping up. This happens, because when executing your function, the command will be put on the commandline, which causes a scroll. Vim then get's into the hit-enter prompt and expects a character from the user. Now by coincidence the next character in the typebuf is `g` which is a character that is accepted by the hit-enter prompt and thus that character will be consumed and not available for the normal mode command `gv` anymore. 

I think using the `<silent>` flag should work around it, I think. 

Here is a patch, that basically skips putting the character on the commandline, if they come from a mapping. I think we do not need to put the characters to be executed on the commandline if they come from a mapping (which should also save a redraw).

```patch
diff --git a/src/ex_getln.c b/src/ex_getln.c
index 027047728..c5d20f2d5 100644
--- a/src/ex_getln.c
+++ b/src/ex_getln.c
@@ -1889,24 +1889,29 @@ getcmdline(
            goto cmdline_changed;

        /*
-        * put the character in the command line
+        * put the character in the command line, if they do not result from a mapping.
+        * Careful, if the command line causes a scroll, the hit-enter prompt might be shown,
+        * expecting a character from the typebuf
         */
-       if (IS_SPECIAL(c) || mod_mask != 0)
-           put_on_cmdline(get_special_key_name(c, mod_mask), -1, TRUE);
-       else
+       if (typebuf_typed())
        {
-#ifdef FEAT_MBYTE
-           if (has_mbyte)
-           {
-               j = (*mb_char2bytes)(c, IObuff);
-               IObuff[j] = NUL;        /* exclude composing chars */
-               put_on_cmdline(IObuff, j, TRUE);
-           }
+           if (IS_SPECIAL(c) || mod_mask != 0)
+               put_on_cmdline(get_special_key_name(c, mod_mask), -1, TRUE);
            else
-#endif
            {
-               IObuff[0] = c;
-               put_on_cmdline(IObuff, 1, TRUE);
+#ifdef FEAT_MBYTE
+               if (has_mbyte)
+               {
+                   j = (*mb_char2bytes)(c, IObuff);
+                   IObuff[j] = NUL;    /* exclude composing chars */
+                   put_on_cmdline(IObuff, j, TRUE);
+               }
+               else
+#endif
+               {
+                   IObuff[0] = c;
+                   put_on_cmdline(IObuff, 1, TRUE);
+               }
            }
        }
        goto cmdline_changed;
```

(this patch looks messy, it basically just puts the `put_on_cmdline()` inside a new condition `if (typebuf_typed())` (e.g. ignoring whitespaces, it would look like this:
```patch
diff --git a/src/ex_getln.c b/src/ex_getln.c
index 027047728..c5d20f2d5 100644
--- a/src/ex_getln.c
+++ b/src/ex_getln.c
@@ -1889,8 +1889,12 @@ getcmdline(
            goto cmdline_changed;

        /*
-        * put the character in the command line
+        * put the character in the command line, if they do not result from a mapping.
+        * Careful, if the command line causes a scroll, the hit-enter prompt might be shown,
+        * expecting a character from the typebuf
         */
+       if (typebuf_typed())
+       {
            if (IS_SPECIAL(c) || mod_mask != 0)
                put_on_cmdline(get_special_key_name(c, mod_mask), -1, TRUE);
            else
@@ -1909,6 +1913,7 @@ getcmdline(
                    put_on_cmdline(IObuff, 1, TRUE);
                }
            }
+       }
        goto cmdline_changed;

 /*
```

I thought about creating a test, but since this bug actually depends on the window size, I couldn't not think of making this so that it will always happen.

**Comment by vim-ml** [comment]
On Thu, Nov 2, 2017 at 9:54 AM, Christian Brabandt
<vim-dev-github@256bit.org> wrote:
> Okay, could finally reproduce it. This is really a subtle bug popping up.
> This happens, because when executing your function, the command will be put
> on the commandline, which causes a scroll. Vim then get's into the hit-enter
> prompt and expects a character from the user. Now by coincidence the next
> character in the typebuf is g which is a character that is accepted by the
> hit-enter prompt and thus that character will be consumed and not available
> for the normal mode command gv anymore.
>
> I think using the <silent> flag should work around it, I think.
>
> Here is a patch, that basically skips putting the character on the
> commandline, if they come from a mapping. I think we do not need to put the
> characters to be executed on the commandline if they come from a mapping
> (which should also save a redraw).

Isn't ":silent" enough? Or maybe a slight increase in 'cmdheight'? I
have several mappings which execute short ex-commands, and I _like_
seeing them echoed on the command-line.

Best regards,
Tony.

**Comment by marcelpaulo** [comment]
@chrisbra, `<silent>` indeed does work around the issue, I've just tried it. Also tried your patch (without `<silent>`) and it works ! Many thanks for seeing this through !
