### ISSUE TITLE
set termguicolors breaks patch 8.0.1238 incremental search

### ISSUE THREAD

**Issue by mcprentiss** [vim/vim#2270]
Running vim patch 8.0.1240  with no plugins (vim -u NONE)
with
set incsearch 
set hlsearch
set termguicolors
disables the incremental search behavior.

**Comment by chrisbra** [comment]
this is more likely to be an issue with termguicolors resetting how the coloring works. Please read `:h xterm-true-color` and set those t_8f and t_8b terminal options accordingly.

**Comment by mcprentiss** [comment]
I am using rxvt-unicode-9.22, and  TERM is set to screen-256color-bce, fwiw.

I checked this by changing the TERM to xterm-true-color, and vim +'set incsearch hlsearch termguicolors' <file> functions as it should.  t_8f and t_8b maybe the solution.  thanks.

**Comment by chrisbra** [comment]
i am closing this.
