### ISSUE TITLE
Need to unlet ctrl to quit term

### ISSUE THREAD

**Issue by 0matgal0** [vim/vim#2283]
Case:

Ctrl-d
:term exit
still holding ctrl
ctrl-w-c

need to unlet ctrl
then can quit

**Comment by chrisbra** [comment]
I am sorry, I can hardly understand. Please give precise steps to reproduce the issue.

**Comment by vim-ml** [comment]
Op 4 nov. 2017 11:49 schreef "Christian Brabandt" <vim-dev-github@256bit.org
>:

I am sorry, I can hardly understand. Please give precise steps to reproduce
the issue.


He means not letting go of the Ctrl key, but holding it all the time.

Christ van Willegen

**Comment by nuko8** [comment]
Note that `:help CTRL-W_CTRL-C` says
```
CTRL-W CTRL-C                                           CTRL-W_CTRL-C
              You might have expected that CTRL-W CTRL-C closes the current
              window, but that does not work, because the CTRL-C cancels the
              command.
```
So, if

> still holding ctrl
> ctrl-w-c

means `CTRL-W_CTRL-C`, "unlet ctrl" is rather a necessary action to close the window.

**Comment by chrisbra** [comment]
closing then.

**Comment by 0matgal0** [comment]
I'm sorry for all involved (and my foul language), I was drunk when I posted this issue.
