### ISSUE TITLE
Executing custom User autocmd commands can cause folds to close

### ISSUE THREAD

**Issue by w0rp** [vim/vim#2287]
Create the following files somewhere on your filesystem.

```vim
" Save this file as setup.vim
set nocompatible
filetype plugin indent on
syntax on

autocmd User Anything let x=3
autocmd TextChanged * doautocmd User Anything
```

```text
" Save this file as test.txt
"" vim:ft=vim:foldmethod=marker:foldlevel=0

" Open the fold below, then delete this line with dd

" This is a fold {{{
This is some folded text
More folded text
And another line
" }}}
```

Run `vim -u setup.vim test.txt`, open the fold below, and delete the line indicated. The fold will be closed. If you edit `setup.vim`, remove the `autocmd User Anything let x=3` line, and try the same again, the fold will remain open. It seems like executing custom `autocmd` commands can cause folds to be closed.

**Comment by chrisbra** [comment]
You need the <nomodeline> flag, if you don't want the modelines to be re-evalutated.

**Comment by w0rp** [comment]
Which flag is that?

**Comment by w0rp** [comment]
Oh, it appeared in the email from GitHub, but not the comment here, due to Markdown wizardry.

**Comment by chrisbra** [comment]
Hm, `<nomodeline>` Github markdown swallowed it.

**Comment by w0rp** [comment]
Okay, I'll add that flag. Thanks for the info! I didn't know it was connected to folding.
