### ISSUE TITLE
c_CTRL-G works incorrectly with backwards search

### ISSUE THREAD

**Issue by waivek** [vim/vim#2291]
After running `set incsearch` on a vanilla gvim configuration, run a backwards search by using `?<search_term>`. Pressing `CTRL-G` searches forwards instead of the expected backwards behaviour.

**Comment by chrisbra** [comment]
yes, `CTRL-G` always moves to the next (further down) search location and `CTRL-T` to the previous backward location.

**Comment by waivek** [comment]
Shouldn't it behave more like `n` and `N`? If not, then I'll post a workaround and close this issue.

**Comment by chrisbra** [comment]
I hope not and that was not how I like those keys to behave (to have them work consistently)
