### ISSUE TITLE
C-j and C-m are indistinguishable in a zsh completion menu

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#2294]
- `vim --version`: VIM - Vi IMproved 8.0  Included patches: 1-1257
 - Operating system/version: Ubuntu 16.04.3 LTS
 - Terminal name/version: rxvt-unicode 9.22
 - Terminal multiplexer name/version: tmux 2.3
 - Shell name/version: zsh 5.3.1
 - `$TERM`: screen-256color

I have a key binding in `~/.zshrc`, using the key `C-j`, which makes `zsh` select the entry below the current one, when a completion menu is open:

    bindkey -M menuselect '^J' down-line-or-history

It works in a regular terminal. But in a Vim's terminal buffer, if this key binding is sourced, I can't use `C-m` to validate the currently selected entry anymore. Instead of validating the current entry, the shell selects the one below. Maybe Vim has translated `C-m` into `C-j`, and so the shell applies the key binding.

In a regular terminal, I can source this key binding to customize the behaviour of `C-j` while a completion menu is open, without changing the behaviour of `C-m`.

Here's a minimal `zshrc` to reproduce:

    autoload -Uz compinit
    compinit
    zstyle ':completion:*' menu select
    zmodload zsh/complist
    bindkey -M menuselect '^J' down-line-or-history

Write this code in a temporary file, `/tmp/zshrc`, then in your `~/.zshrc`, write at the very top:

    source /tmp/zshrc
    return

Start Vim with a clean configuration:

    vim --clean

Open a terminal buffer:

    :term

Type the shell command `echo`, add a space then press `Tab` to open a completion menu displaying the file entries in the working directory. Finally, press `C-j` to move the cursor to the entry below, and `C-m` or `Enter` to try to validate.

**Comment by k-takata** [comment]
See #2278.

**Comment by lacygoill** [comment]
I closed the issue thinking that the patch [8.0.1261](https://github.com/vim/vim/commit/1232624ae5b56c167c5982a2620f736c4bbc19ef) had fixed it, but I can still reproduce after upgrading Vim to `8.0.1272`.

**Comment by lacygoill** [comment]
After upgrading to [8.0.1277](https://github.com/vim/vim/releases/tag/v8.0.1277), I can no longer reproduce, so it seems the [PR #2278](https://github.com/vim/vim/pull/2278) has fixed the issue.
