### ISSUE TITLE
Stop using "." current directory for swap (set directory)

### ISSUE THREAD

**Issue by dezza** [vim/vim#2295]
Almost everyone unsets this from defaults. Unless argued very well I hope this could become a new default in vim.

Also:
https://groups.google.com/forum/#!msg/vim_dev/sRT9BtjLWMk/5wmCdI3rBgAJ;context-place=topic/vim_dev/a5py-Q6iKVE

**Comment by chrisbra** [comment]
Not sure if this is done by everyone and note, there is a drawback when storing swapfiles in a local .vim directory. Other users won't be notified when editing a file. Also this might be problematic for file shares or similar, but I think this is currently discussed in the mentioned vim-dev thread (with all the drawbacks mentioned), so it makes sense to continue the discussion in one place, please.

**Comment by ZyX-I** [comment]
@chrisbra This is much more trouble then it is worth. Neovim changed the default location to use a directory under $XDG_DATA_HOME, reasoning at neovim/neovim#4481. And, BTW, there I had enough reasons to remove dot from defaults even before that thread pointing out security problems.
