### ISSUE TITLE
How do I quit after another command finishes?

### ISSUE THREAD

**Issue by tobiassjosten** [vim/vim#2297]
Before Vim 8 I used to be able to run something like:

    $ vim +somecommand +qall

… and Vim would execute `somecommand`, wait for it to finish, and then quit. It won't work after updating to Vim 8 though and I'm guessing it has to do with the new concurrency feature?

Is there a way I could replicate the old behaviour with Vim 8?

**Comment by k-takata** [comment]
What is the actual command you executed? This does quit as expected:

```
$ vim '+echo "foo"' +qall
```

If you have any unsaved changes and if you want to abandon them, you should use `+qall!` instead of `+qall`.

**Comment by tobiassjosten** [comment]
Thanks for getting back to me, @k-takata!

The actual command is `vim "+call minpac#update()" +qall` – it's to have your own [minpac](https://github.com/k-takata/minpac) update its packages, as part of a dotfiles installation. It didn't update/install any packages until left the `+qall` part out.

**Comment by k-takata** [comment]
Aha!
`minpac#update()` invokes jobs asynchronously, and executing `:qall` terminates all jobs even if they are still running.
You need to use hooks for this. See: https://github.com/k-takata/minpac#finish-update-hooks
`vim "+call minpac#update('', {'do': 'quit'})"` should work.

This is not the right place for discussing about my plugin. So, closing.
If you still have any question about this, feel free to create an issue on the minpac's repository.

**Comment by tobiassjosten** [comment]
Thanks, that works perfectly!
