### ISSUE TITLE
Remapping :cn breaks foldopen=quickfix

### ISSUE THREAD

**Issue by waivek** [vim/vim#2306]
# Steps to reproduce

Use a vimrc with the following lines

```
set foldmethod=marker
set foldopen=quickfix
nnoremap <TAB> :cn<CR>
```

Open a file `name.txt` with the following lines

```
Hello

{{{
key
key
key
}}}
```

Run the following command -
`    vimgrep key %`

Close all folds. If you press `:cn` it opens the fold to the match, but if you press `<TAB>`, it does not.

# Version Info

- Platform - Windows
- Type - gvim
- Version Number: 8.01241

**Comment by chrisbra** [comment]
I think this is covered by the ['foldopen'](https://vimhelp.appspot.com/options.txt.html#%27foldopen%27) option. Note this paragraph:

>  NOTE: When the command is part of a mapping this option is not used.
>  Add the zv command to the mapping to get the same effect.
>  (rationale: the mapping may want to control opening folds itself)
