### ISSUE TITLE
Mouse not working past the 223rd Column

### ISSUE THREAD

**Issue by llimllib** [vim/vim#2309]
Steps to reproduce:

1. Open a terminal >223 columns wide
2. Open vim with `vim -N -u NONE`
3. Open a text file with long lines, or use splits until you have text past the 223rd column of the window
4. `:set mouse=a`
5. Note that you can select a character in the 223rd column, but not in the 224th

Vim 8.0.1250 compiled by homebrew ([full version info](https://gist.github.com/llimllib/ac6c8e2b73eee4e35ceaacb98e9ee5ef)), Mac OS X 10.13.1, reproduced in both iTerm 2 3.1.5 and Terminal.app 2.8

I was not able to reproduce the bug in neovim.

**Comment by chrisbra** [comment]
Please read the help at ['ttymouse'](https://vimhelp.appspot.com/options.txt.html#%27ttymouse%27)

**Comment by llimllib** [comment]
Thank you for the quick response, and sorry for the spurious report

**Comment by llimllib** [comment]
For anyone who gets here by search, this is solved by adding this to add this to my `.vimrc`:

```
if has("mouse_sgr")
    set ttymouse=sgr
else
    set ttymouse=xterm2
end
```

**Comment by brammool** [comment]
Bill Mill wrote:

> Steps to reproduce:
> 
> 1. Open a terminal >223 columns wide
> 2. Open vim with `vim -N -u NONE`
> 3. Open a text file with long lines, or use splits until you have text past the 223rd column of the window
> 4. `:set mouse=a`
> 5. Note that you can select a character in the 223rd column, but not in the 224th
> 
> Vim 8.0.1250 compiled by homebrew ([full version info](https://gist.github.com/llimllib/ac6c8e2b73eee4e35ceaacb98e9ee5ef)), Mac OS X 10.13.1, reproduced in both iTerm 2 3.1.5 and Terminal.app 2.8

What is the output of:
	:set term?
	:set ttymouse?
	:echo has('mouse_sgr')


-- 
"Beware of bugs in the above code; I have only proved
it correct, not tried it." -- Donald Knuth

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by llimllib** [comment]
> What is the output of:
> 	:set term?
> 	:set ttymouse?
>	:echo has('mouse_sgr')

Now that I've fixed it by forcing sgr mode in my vimrc, it's:

> term=xterm-256color
> ttymouse=sgr
> 1

When I run vim without my vimrc, I get the same except `ttymouse=xterm2`

-Bill

**Comment by brammool** [comment]
Bill Mill wrote:

> > What is the output of:
> > 	:set term?
> > 	:set ttymouse?
> >	:echo has('mouse_sgr')
> 
> Now that I've fixed it by forcing sgr mode in my vimrc, it's:
> 
> > term=xterm-256color
> > ttymouse=sgr
> > 1
> 
> When I run vim without my vimrc, I get the same except `ttymouse=xterm2`

So Vim doesn't recognize your terminal.  You call it "xterm-256color",
but it's probably something else. What does this give you:

	echo v:termresponse

-- 
   A village.  Sound of chanting of Latin canon, punctuated by short, sharp
   cracks.  It comes nearer.  We see it is a line of MONKS ala SEVENTH SEAL
   flagellation scene, chanting and banging themselves on the foreheads with
   wooden boards.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by llimllib** [comment]
> So Vim doesn't recognize your terminal.  You call it "xterm-256color",
but it's probably something else. What does this give you:

> 	echo v:termresponse

I get:

^[[>0;95;0c

-Bill

**Comment by brammool** [comment]
Bill Mill wrote:

> > So Vim doesn't recognize your terminal.  You call it "xterm-256color",
> > but it's probably something else. What does this give you:
> 
> > 	echo v:termresponse
> 
> I get:
> 
> ^[[>0;95;0c

Hmm, that's similar but not the same as what Mac Terminal.app sends.
What is the terminal called?
How do we know this terminal supports SGR?

-- 
If you had to identify, in one word, the reason why the
human race has not achieved, and never will achieve, its
full potential, that word would be "meetings."

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
On Sun, Nov 12, 2017 at 11:05 PM, Bram Moolenaar
<vim-dev-github@256bit.org> wrote:
>
> Bill Mill wrote:
>
>> > So Vim doesn't recognize your terminal. You call it "xterm-256color",
>> > but it's probably something else. What does this give you:
>>
>> > echo v:termresponse
>>
>> I get:
>>
>> ^[[>0;95;0c
>
> Hmm, that's similar but not the same as what Mac Terminal.app sends.
> What is the terminal called?
> How do we know this terminal supports SGR?

IIUC, this terminal advertises the bare minimum version for an
automatically detected xterm2 (though the help for 'ttymouse' has
conflicting info: at versions 88 to 94, the terminal might accept
xterm2 codes but Vim won't bet on it). If the terminal supports SGR,
it ought to report version 277 or higher, rather than "only" 95.

Best regards,
Tony.

**Comment by llimllib** [comment]
> Hmm, that's similar but not the same as what Mac Terminal.app sends.

I get the exact same string form Mac Terminal.app

> What is the terminal called?

iTerm2 version 3.1.5

> How do we know this terminal supports SGR?

It says so in the docs: https://iterm2.com/faq.html and actually includes the snippet to enable sgr in vim. (If you mean how do we, vim, know it supports SGR, I have no idea)

Thanks so much for looking into this.

-Bill

**Comment by llimllib** [comment]
Update: I get `^[[>1;95;0c` (terminal.app) rather than `^[[>0;95;0c` (iterm2). My bad, sorry for that.

-Bill

**Comment by llimllib** [comment]
Actually, here's the source for that response: https://github.com/gnachman/iTerm2/blob/469d65f3e1521504b96d707c0f272eb285589ca2/sources/VT100Output.m#L92

Which I'll copy here (it's short):
> // TODO: When xterm compatibility is reached, change 95 to 314 or later. Even 277 would be an
> // improvement as it would let vim use ttym=sgr rather than xterm2, which passes through luit.
> // However, it must return three arguments (at the very least) to keep vim happy. For more, see
> // check_termcode() in vim's term.c.
> #define REPORT_SDA           "\033[>0;95;0c"

-Bill

**Comment by brammool** [comment]
Bill Mill wrote:

> Update: I get `^[[>1;95;0c` (terminal.app) rather than `^[[>0;95;0c`
> (iterm2). My bad, sorry for that.

OK, we could use that to enable SGR.  Perhaps it also works for
Terminal.app?
Need to check what happens if we enable SGR for a terminal that doesn't
support it, might be OK.

-- 
Back off man, I'm a scientist.
              -- Peter, Ghostbusters

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by llimllib** [comment]
> OK, we could use that to enable SGR.  Perhaps it also works for Terminal.app?

SGR does work on terminal.app as well
