### ISSUE TITLE
netrw silently closing buffers on its own

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vim/vim#231]
```
After upgrading macvim from 7.3 to 7.4, netrw is closing buffers on its own.

What steps will reproduce the problem?
1. :Explore, navigate directories, open a file
2. :Explore, open another file
3. Buffer opened in step 1 will be closed.

What is the expected output? What do you see instead?

I expect both buffers to exist, but only the last one does.

What version of the product are you using? On what operating system?

Macvim 7.4 snapshot 73 for Moutain Lion. netrw v153i (noticed the same behavior 
with v151 so I upgraded to latest netrw)

Please provide any additional information below.

Not a problem with macvim 7.3.
```

Original issue reported on code.google.com by `johnston...@gmail.com` on 12 Jun 2014 at 6:20

**Comment by theunraveler** [comment]
Also experiencing this issue, as noted in https://github.com/macvim-dev/macvim/issues/255. It appears to have _started_ happening for me some time between patch 7.4.1362 and the current HEAD.

I'll try to do a `git bisect` in the next few days to determine the exact commit that (re-?)introduced the issue.

**Comment by k-takata** [comment]
DrChip's reply doesn't seem to be redirected here (vim/vim#231).
https://groups.google.com/d/msg/vim_dev/1TKfXBi0pEc/SJVAUud1GgAJ

> Before you go to the trouble of bisecting -- why not try the latest
> netrw, which you can get from my website:
> http://www.drchip.org/astronaut/vim/index.html#NETRW .

**Comment by vim-ml** [comment]
Updating to the latest netrw fixes the issue. Thanks!
