### ISSUE TITLE
:make command is buggy if Makefile's compile command has a colon in it

### ISSUE THREAD

**Issue by nakuldhotre** [vim/vim#2311]
I have the following test

Makefile
```
all:
        cc program.c -DBUILD_TIME="10:30:1"
```

program.c
```
#include <stdio.h>
int main(int argc, char *argv[])
{
        printf("build time %s!\n", BUILD_TIME);
        return 0;
}
```

If run :make from vim, it takes me to a window that tries to open file named "cc program.c -DBUILD_TIME="\"10 program.c"

I think this happens because of parsing issue if the compile command has colons.

**Comment by k-takata** [comment]
The output of the `:make` command is parsed using the `'errorformat'` option. See `:help errorformat`.
The default setting of the option should work for most cases but it is not perfect (like your case).
I don't know whether we can support your case without breaking other existing cases.

**Comment by chrisbra** [comment]
I think this is a configuration issue and no actual bug. Please ask user questions at vi.stackexchange.com or the vim-use mailinglist. Closing.

**Comment by nakuldhotre** [comment]
Thanks. I'll look into it. I agree that this is a corner case scenario and I fixed it by creating a separate file with the required #define instead of passing it via cc -D
