### ISSUE TITLE
One letter abbreviations do not expand after non keyword character

### ISSUE THREAD

**Issue by Konfekt** [vim/vim#2320]
Under 
```vim
VIM - Vi IMproved 8.0 (2016 Sep 12)
Included patches: 1-627
```
enter `:cabb s sub<cr>`.
Then `:s<space>` results in `:sub `, but, for example `:'<,'>s<space>` stays `:'<,'>s<space>`, even though `>` is a non-keyword character.

If however `:cabb su sub<cr>`.
Then `:su<space>` results in `:sub `, and, for example `:'<,'>su<space>` becomes `:'<,'>sub `.

**Comment by chrisbra** [comment]
this happens, because the given address is considered to be part of the commandline.

Here is a patch (copy pasting here verbosely, because I am sitting in a train here and Germany is an Internet developing country which does not provide mobile internet in trains besides the fast intercity express trains not even in smaller trainstations and now I am having a delay and don't even know when the train will continue. Sorry for the rant)

```patch
From a78f96bf0b062030a68ed4c63fd485ed8c8b510a Mon Sep 17 00:00:00 2001
From: Christian Brabandt <cb@256bit.org>
Date: Mon, 13 Nov 2017 11:54:52 +0100
Subject: [PATCH] expand cabbrev correctly

When defining a commandline abbreviation, do not consider the address
given as part of the possible commandline

fixes #2320
---
 src/ex_getln.c               | 17 ++++++++++++++++-
 src/testdir/test_mapping.vim | 16 ++++++++++++++++
 2 files changed, 32 insertions(+), 1 deletion(-)

diff --git a/src/ex_getln.c b/src/ex_getln.c
index 027047728..5589cd82a 100644
--- a/src/ex_getln.c
+++ b/src/ex_getln.c
@@ -3548,10 +3548,25 @@ gotocmdline(int clr)
     static int
 ccheck_abbr(int c)
 {
+    int spos = 0;
     if (p_paste || no_abbr)	    /* no abbreviations or in paste mode */
 	return FALSE;
 
-    return check_abbr(c, ccline.cmdbuff, ccline.cmdpos, 0);
+    /* do not consider '<,'> be part of the mapping, skip leading whitespace */
+    if ((int)ccline.cmdlen > 5)
+    {
+	while (VIM_ISWHITE(ccline.cmdbuff[spos]) && spos < ccline.cmdlen)
+	    spos++;
+
+	if (ccline.cmdbuff[spos] == '\'' &&
+	    ccline.cmdbuff[spos + 2] == ',' &&
+	    ccline.cmdbuff[spos + 3] == '\'')
+	    spos += 5;
+	else
+	    /* check abbreviation from the beginning of the commandline */
+	    spos = 0;
+    }
+    return check_abbr(c, ccline.cmdbuff, ccline.cmdpos, spos);
 }
 
 #if defined(FEAT_CMDL_COMPL) || defined(PROTO)
diff --git a/src/testdir/test_mapping.vim b/src/testdir/test_mapping.vim
index 5026d6b2b..58195d493 100644
--- a/src/testdir/test_mapping.vim
+++ b/src/testdir/test_mapping.vim
@@ -198,3 +198,19 @@ func Test_map_timeout()
   set timeoutlen&
   delfunc ExitInsert
 endfunc
+
+func Test_cabbr_visual_mode()
+  cabbr s su
+  call feedkeys(":s \<c-B>\"\<CR>", 'itx')
+  call assert_equal('"su ', getreg(':'))
+  call feedkeys(":'<,'>s \<c-B>\"\<CR>", 'itx')
+  let expected='"'. "'<,'>su "
+  call assert_equal(expected, getreg(':'))
+  call feedkeys(":  '<,'>s \<c-B>\"\<CR>", 'itx')
+  let expected='"  '. "'<,'>su "
+  call assert_equal(expected, getreg(':'))
+  call feedkeys(":'a,'bs \<c-B>\"\<CR>", 'itx')
+  let expected='"'. "'a,'bsu "
+  call assert_equal(expected, getreg(':'))
+  cunabbr s
+endfunc
-- 
2.14.1

```

**Comment by tonymec** [comment]
IIUC, the problem arises because the chosen abbreviation was a single letter:

```
The characters before the cursor must match the abbreviation.  Each type has
an additional rule:

full-id	  In front of the match is a non-keyword character, or this is where
	  the line or insertion starts.  Exception: When the abbreviation is
	  only one character, it is not recognized if there is a non-keyword
	  character in front of it, other than a space or a tab.
...
```
@Konfekt : Try using `ss` instead of `s` as your `{lhs}`, or else add a space immediately after the range, it might work out of the box, even without @chrisbra 's patch.

Best regards,
Tony.

**Comment by Konfekt** [comment]
Yes @tonymec , this is what the issue is about, if there is a space before the abbreviation, or if the abbreviation has more than one letter, then it expands, but otherwise not.

**Comment by tonymec** [comment]
Well, this restriction is documented, so there must have been a reason for it.

**Comment by chrisbra** [comment]
It is at least unexepcted, that the entered address is taken into account before expanding abbreviations.

**Comment by Konfekt** [comment]
The question is if there is a good reason. Perhaps it is given in the message of the commit that  documents this exception in the help.

**Comment by Konfekt** [comment]
Thanks! Maybe this happens separately, but with this commit the exception documented at

https://github.com/vim/vim/issues/2320#issuecomment-343948780

should be removed from Vim's documentation, too.

**Comment by brammool** [comment]
> Thanks! Maybe this happens separately, but with this commit the
> exception documented at
> 
> https://github.com/vim/vim/issues/2320#issuecomment-343948780
> 
> should be removed from Vim's documentation, too. 

It can't be removed, only some specific address with marks is handled.
I have added a remark about that.

-- 
Every person is responsible for the choices he makes.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Konfekt** [comment]
That check is very specific. For example, `%s` would still not be expanded.
How about replacing this check by one for the regular expression
```vim
let s:range_pattern =  '\v(%('
      \ . '%(\%|[`''][.\^''"{}()<>[\][:alnum:]]|[.$]|\d+|\\[/?&]|/.+/?|\?.+\??)%([+\-]\d*)*'
      \ . '%(\s*[,;]\s*%([`''][.\^''"(){}<>[\][:alnum:]]|[.$]|\d+|\\[/?&]|/.+/|/?.+/?)%([+\-]\d*)*)*'
      \ . ')|)\s*'
```
that matches if the string is a range in the Vim command-line.
(The regex is fromhttps://github.com/Konfekt/vim-alias/blob/2e5883c67815b785afcdfc52461f6a63191fa89d/plugin/cmdalias.vim#L29)

**Comment by Konfekt** [comment]
This suggestion has become https://github.com/vim/vim/issues/2912 .

**Comment by brammool** [comment]
> That check is very specific. For example, `%s` would still not be expanded.

The patch was not aimed at fixing it when TYPING the command, but only
when pressing ":" in Visual mode, where '<,'> is inserted automatically,
so the user really only types the one character.

OK, so it's not doing exactly that, but it should be good enough for
most cases.

> How about replacing this check by one the regular expression
> ```vim
> let range_regex = '\%(\%([.$]\|\d\+\)\%([,;]\%([.$]\|\d\+\)\)*\)\?\s*'
> ```
> that matches if the string is a range in the Vim command-line.
> (The regex is from https://github.com/Konfekt/vim-alias#configuration)

Attempting to catch all ranges is bound to fail often.  e.g.:
	/pattern/,/pattern/cmd
You can't skip over a regexp with a regexp :-).

-- 
Why don't cannibals eat clowns?
Because they taste funny.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Houl** [comment]
Thus the patch should aim at the automatically inserted ranges:

- (Visual mode) `:` which becomes `:'<,'>`
- (Normal mode) `4:` which becomes `:.,.+3` (for any number)
- (Normal mode) `1:` which becomes `:.`
- more ... ?

It should not attempt to work for anything else (no `:'m,'n`, no `:%`, etc.).

**Comment by brammool** [comment]
> Thus the patch should aim at the automatically inserted ranges:
> 
> - (Visual mode) `:` which becomes `:'<,'>`
> - (Normal mode) `4:` which becomes `:.,.+3` (for any number)
> - (Normal mode) `1:` which becomes `:.`
> - more ... ?
> 
> It should not attempt to work for anything else (no `:'m,'n`, no `:%`, etc.).

That sounds about right to me.


-- 
So when I saw the post to comp.editors, I rushed over to the FTP site to
grab it.  So I yank apart the tarball, light x candles, where x= the
vim version multiplied by the md5sum of the source divided by the MAC of
my NIC (8A3FA78155A8A1D346C3C4A), put on black robes, dim the lights,
wave a dead chicken over the hard drive, and summon the power of GNU GCC
with the magic words "make config ; make!".
		[Jason Spence, compiling Vim 5.0]

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Konfekt** [comment]
Again, just as in https://github.com/vim/vim/commit/5e3423d192bfa502c6704f731fa2ec6821f9a2f0#r28972842, then, for example, with `cabbrev 3 three` and `cabbrev 33 threee`, the input `:.,.+33` obtained by typing `3:` and `3` expands (upon hitting`<space>`) to `:.,.+3three` and not `:.,.+threee`. 

Therefore the patch should only apply to `:'<,'>` and `:.`, which consist of non-keyword letters.
