### ISSUE TITLE
C: indentation: incorrect with '*' immediately after '*/'

### ISSUE THREAD

**Issue by jbowler** [vim/vim#2321]
~jbowler/vimrc:
set exrc
set secure
set highlight=lb
set shiftwidth=4
set softtabstop=-1
set expandtab
set undofile
filetype plugin on
filetype indent on

directory .vimrc:
set textwidth=80

file (test.c):
{
    first line;
    second/*bug*/*line;
}

'o' on the second line.  Insert a space between the */ and the * and 'o' indents correctly.

Gentoo:

 * Searching for vim ...
[IP-] [  ] app-editors/vim-8.0.1188:0

I think that's all you need; jbowler long term resident acm.org for more info.

**Comment by jbowler** [comment]
Oh, the lines on the test file do need to be indented.  They were in the text I c'n'p'ed but some HTML gurfuss decided the indentation wasn't required.

**Comment by brammool** [comment]
John Bowler wrote:

> Oh, the lines on the test file do need to be indented.  They were in the text
> I c'n'p'ed but some HTML gurfuss decided the indentation wasn't required.

I see the problem I'll make a fix.

-- 
            |

Ceci n'est pas une pipe.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
