### ISSUE TITLE
Please provide a QA/unittest script for colorschemes.

### ISSUE THREAD

**Issue by venthur** [vim/vim#2325]
After some discussions in #2307 and #1665 it turned out that we should have some automated quality assurance script for colorschemes. I propose a QA script that would check a colorscheme for things like:

* respecting the value of background or setting
* are all highlight groups defined
* support for the various color modes (gui, `termguicolors`, 265, 16, ...)
* common errors and pitfalls
* etc

And returns errors and warnings.

This script could be used:
* as a tool for developers of new colorschemes to validate
* to unittest all existing colorschemes shipped with vim during the test pipeline so we automatically update them when for example a new highlight group was introduced.

**Comment by chrisbra** [comment]
I might look into it. Can you be a bit more specific what exactly needs to be checked? I suppose all those highlighting groups mentioned at `:h highlight-groups` need to be defined, right? What exactly means, respecting `background setting`?  What are other `common errors and pitfalls`?

Sorry, I did not follow the complete discussion here and the related issues.

**Comment by venthur** [comment]
The most important check is probably if all highlight groups are defined and if the colorscheme works with the various color modes of a terminal. If vim introduces a new highlight group, we'd only have to update that test and it will be obvious that all colorschemes need to be updated.

The background check was Bram's idea: https://github.com/vim/vim/pull/2307#issuecomment-343679634, with common errors and pitfalls I mean, that we could include tests for things that are not allowed in colorscheme definitions.

**Comment by nuko8** [comment]
As a guy who is working for the GUIs, I'd highly appreciate it if every colorscheme would be made sure that it's free from this issue: [Vim colorscheme leaves a wake of destruction when switching away](https://github.com/altercation/solarized/issues/102).  That would absolutely help people who have to manually test several gvim's, colorschemes or various permutations of both to see if each of them works properly for its own.  Quick switching from colorscheme to colorscheme definitely matters to them.  Also, that would be welcome by the users who frequently switch their colorscheme for a change.

**Comment by lifepillar** [comment]
This is [the advice](https://github.com/lifepillar/vim-colortemplate/blob/master/doc/colortemplate.txt) I give in the help of my plugin to avoid wreaking havoc when switching colorschemes:

>Avoid defining filetype-specific highlight groups as much as possible. They
>override ftplugin definitions causing highlighting to be messed up after
>switching colorschemes. For example, suppose that the Vim filetype defines
>vimCommand to be a link to Statement. If your colorscheme sets vimCommand's
>attributes, after switching away from your colorscheme vimCommand will be
>cleared, and not restored to a link to Statement as you might expect. Even
>resetting the filetype will not fix that. If you link vimCommand instead, the
>linking will persist after switching to another colorscheme (so, again, the
>default link will not be restored), which will likely result in a different
>highlighting than expected. If you absolutely need filetype-specific highlight
>group definitions in your colorscheme, define an option that allows the user to
>turn them on/off (the default should be off)

I'd like to hear if you have better ideas.

**Comment by brammool** [comment]
Christian wrote:

> I might look into it. Can you be a bit more specific what exactly
> needs to be checked? I suppose all those highlighting groups mentioned
> at `:h highlight-groups` need to be defined, right? What exactly
> means, respecting `background setting`?  What are other `common errors
> and pitfalls`?

Mainly that all important highlight groups are defined, including diff
mode, status line, etc.  And for each that both cterm and gui properties
are set.

It would be good if we have a start, we can make further improvements if
we find a colorscheme that's doing something wrong.

> Sorry, I did not follow the complete discussion here and the related
> issues.

Blame it on the train?  Considered moving to Switzerland?

-- 
Sometimes you can protect millions of dollars in your budget simply by buying
a bag of cookies, dropping it on the budget anylyst's desk, and saying
something deeply personal such as "How was your weekend, big guy?"
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
I am sitting in a train again (and no, moving to Switzerland is no alternative):
How about the following check script: https://gist.github.com/chrisbra/5c6fae340dbae1471f281258fee110fa

**Comment by lifepillar** [comment]
Nice! I had a quick try, and I have some issues:

1. I get `Should not issue :syn on`, although my colorschemes do not use `syn on`. The snippet in my colorschemes is:

```vim
if exists('syntax_on')
  syntax reset
endif
```

2. I get `init: No initialization`: what does that mean?

3. I get `t_Co: Does not check terminal for capable colors`, although my colorschemes do check `t_Co`. This is the snippet I use in my colorschemes:

```vim
if !(has('termguicolors') && &termguicolors) && !has('gui_running')
      \ && (!exists('&t_Co') || &t_Co < 256)
  echoerr '[Dark] There are not enough colors.'
  finish
endif
```

4. I get `No highlight group definition for…` for all the highlight groups checked by the script, although they are all defined.

5. I get `Normal: Missing background color for Normal`, although `Normal` has a defined background color. RE this point, a colorscheme may use a transparent background, possibly conditional to a user's setting. E.g., in my colorschemes you find:

```vim
if !has('gui_running') && get(g:, 'dark_transp_bg', 0) " Do not define a background color
  hi Normal ctermfg=255 ctermbg=NONE guifg=#ebebeb guibg=NONE guisp=NONE cterm=NONE gui=NONE
  " Possibly other highlight groups with ctermbg and guibg set to NONE
else
  hi Normal ctermfg=255 ctermbg=16 guifg=#ebebeb guibg=#000000 guisp=NONE cterm=NONE gui=NONE
  " ...
endif
```

**Comment by brammool** [comment]
Christian wrote:

> I am sitting in a train again (and no, moving to Switzerland is no
> alternative):
> How about the following check script:
> https://gist.github.com/chrisbra/5c6fae340dbae1471f281258fee110fa

Thanks for getting this started.

A header is missing, I suppose we can figure out later how to use this
script.  For now I assume it's to be sourced when editing a color
scheme.

It warns for setting 'background', but that is OK, so long as it's
before any highlight commands.  The rule is that the script either sets
'background' (when it defines the Normal background color) or respects
it (contains a check for the 'background' value).

  LineNr: Missing background color for LineNr

I don't think it is needed to check for setting background. Using the
default background should be OK.  When ctermbg is used there should
probably also be a guibg entry.  Not sure about the other way around.

There will be some warnings that are known to happen.  E.g. checking
default.vim most groups are missing. Perhaps we can supporess known
warnings?  We could do:

	finish

	" @suppress Visual: No highlight definition for Visual
	" @suppress Title: No highlight definition for Title

This avoids having to check the output for new errors/warnings.

-- 
hundred-and-one symptoms of being an internet addict:
84. Books in your bookcase bear the names Bongo, WinSock and Inside OLE

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by venthur** [comment]
I suggest to run this test in the testsuite for all color schemes  in `runtime/colors` -- this way we'll get automatic checking when someone provides a [pull request](https://github.com/vim/vim/pull/2307) for a new color scheme.

**Comment by chrisbra** [comment]
>    I get Should not issue :syn on, although my colorschemes do not use syn on. The snippet in my colorschemes is:

The script [searches](https://gist.github.com/chrisbra/5c6fae340dbae1471f281258fee110fa#file-check_colors-vim-L72) for:  `syn\%[tax]\s\+on` Do you have that somewhere perhaps in a comment?

> if exists('syntax_on')
>   syntax reset
> endif

shouldn't match

>    I get init: No initialization: what does that mean?

It means you are missing this block https://gist.github.com/chrisbra/5c6fae340dbae1471f281258fee110fa#file-check_colors-vim-L61-L65:
```
hi clear
if exists("syntax_on")
  syntax reset
 endif
```

    I get t_Co: Does not check terminal for capable colors, although my colorschemes do check t_Co. This is the snippet I use in my colorschemes:

> if !(has('termguicolors') && &termguicolors) && !has('gui_running')
>       \ && (!exists('&t_Co') || &t_Co < 256)
>   echoerr '[Dark] There are not enough colors.'
>   finish
> endif

Yeah, this is an error. It only checks for `&t_Co >=`  https://gist.github.com/chrisbra/5c6fae340dbae1471f281258fee110fa#file-check_colors-vim-L56
I should loosen that one. 

>    I get No highlight group definition for… for all the highlight groups checked by the script, although they are all defined.

Can you share the script?

>    I get Normal: Missing background color for Normal, although Normal has a defined background color. RE this point, a colorscheme may use a transparent background, possibly conditional to a user's setting. E.g., in my colorschemes you find:

Yes, I thought, if it would make sense to check for the background color. Bram has mentioned a similar point. So perhaps we should remove it.

> if !has('gui_running') && get(g:, 'dark_transp_bg', 0) " Do not define a background color
  hi Normal ctermfg=255 ctermbg=NONE guifg=#ebebeb guibg=NONE guisp=NONE cterm=NONE gui=NONE

I'd like to have a check for variables that should be documented somewhere. However I don't know how to check that.

**Comment by chrisbra** [comment]
Bram wrote:

> A header is missing, I suppose we can figure out later how to use this
> script.  For now I assume it's to be sourced when editing a color
> scheme.

correct.


> It warns for setting 'background', but that is OK, so long as it's
> before any highlight commands.  The rule is that the script either sets
> 'background' (when it defines the Normal background color) or respects
> it (contains a check for the 'background' value).

I'll add a check that no `:hi ` command comes before the `:set bg` line, not sure how to test the second part (contains a check for background value).

> 
>   LineNr: Missing background color for LineNr
> 
> I don't think it is needed to check for setting background. Using the
> default background should be OK.  When ctermbg is used there should
> probably also be a guibg entry.  Not sure about the other way around.

okay, will change it.

> 
> There will be some warnings that are known to happen.  E.g. checking
> default.vim most groups are missing. Perhaps we can supporess known
> warnings?  We could do:
> 
> 	finish
> 
> 	" @suppress Visual: No highlight definition for Visual
> 	" @suppress Title: No highlight definition for Title
> 
> This avoids having to check the output for new errors/warnings.

Not sure what you are suggest here, you mean skip the check, if a line `@suppress group` is present?

**Comment by chrisbra** [comment]
> I suggest to run this test in the testsuite for all color schemes in runtime/colors -- this way we'll get automatic checking when someone provides a pull request for a new color scheme.

Makes sense. However lets first get the check script into shape so that it is actually usable for any colorscheme.

**Comment by chrisbra** [comment]
Okay version 2 of the script: https://gist.github.com/chrisbra/5c6fae340dbae1471f281258fee110fa

Changes:
- short header on how to use the script
- check that when a background color is given it should be available for gui and terminal
- checks only for a defined foreground color for selected groups
- check that there is no `:hi ` command before a `:set bg` command (except for `:hi clear`) 
- check for `t_Co [<>=] number`
- Skip checks for `@suppress groupname`

**Comment by lifepillar** [comment]
>The script searches for: syn\%[tax]\s\+on Do you have that somewhere perhaps in a comment?

Mmh, no.

>Can you share the script?

[Solarized 8](https://github.com/lifepillar/vim-solarized8/blob/master/colors/solarized8.vim) is a relatively complex one (dark and light background, ANSI and 256 colors, in the same file). It is generated by my Colortemplate plugin. Other examples are in the [colors](https://github.com/lifepillar/vim-colortemplate/tree/master/templates/colors) folder of that plugin.

**Comment by lifepillar** [comment]
This line:

```vim
if search('hi \U\w\+\s\+\S', 'cbnW')
```

matches a line of the form `License: This file is placed in the public domain`.

**Comment by lifepillar** [comment]
Sorry, forget that. I need some sleep.

**Comment by chrisbra** [comment]
> Solarized 8 is a relatively complex one (dark and light background, ANSI and 256 colors, in the same file).

I do not get the output `Should not issue :syn on` Other then that, I only get the error about not checking `t_Co` (where the test is questionable) and that some filetype specific highlighting groups are defined like `vimCommand` which shouldn't be defined I thought.

**Comment by chrisbra** [comment]
I made some slight changes to the script again (e.g. skipping the `if`  for the `&t_Co` test).

**Comment by lifepillar** [comment]
>I do not get the output Should not issue :syn on

I was doing a pretty stupid thing (lack of sleep, you know): opening my colorscheme in a split window, but sourcing your script while the active buffer was… your script. So, I was in effect parsing your script.

>Other then that, I only get the error about not checking t_Co (where the test is questionable)

Perhaps it is enough to check for `'[&]t_Co\s*[<>=]=\?'` without matching numbers.

>and that some filetype specific highlighting groups are defined like vimCommand which shouldn't be defined I thought.

Same here, good. Would it make sense to get the list of filetypes from `$VIMRUNTIME` instead of hard-coding them? Or would the risk of false positives be too high?

**Comment by brammool** [comment]
Christian wrote:

> > There will be some warnings that are known to happen.  E.g. checking
> > default.vim most groups are missing. Perhaps we can supporess known
> > warnings?  We could do:
> > 
> > 	finish
> > 
> > 	" @suppress Visual: No highlight definition for Visual
> > 	" @suppress Title: No highlight definition for Title
> > 
> > This avoids having to check the output for new errors/warnings.
> 
> Not sure what you are suggest here, you mean skip the check, if a line
> `@suppress group` is present? 

You would first create a list with all the error messages.  And along
the way also collect messages after @suppress.  Then in the end, before
producing the list of warnings and errors, filter out the suppressed
messages.

So when I write a color script, run the check script, see the errors and
think "that's OK", then I can suppress those warnings.  So the next time
I check I only see new warnings, not the ones that I deemed are OK.

For others, they can see what warnings will be ignored.  Eventually it
would be possible to run the check script over the distributed color
schemes.

-- 
From "know your smileys":
¯\_(ツ)_/¯   Shrug

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
closed by https://github.com/vim/vim/releases/tag/v8.0.1395 https://github.com/vim/vim/blob/master/runtime/colors/tools/check_colors.vim

**Comment by venthur** [comment]
Awsome! Could you show quickly how you can use this in a unitest? E.g. I have this pending [PR](https://github.com/vim/vim/pull/2307) for a color scheme and already [tried to run it within the test suite](https://github.com/flix-tech/vim/blob/0e54733177ed5ac6006feadc20da575aae54b7eb/src/testdir/test_solarized.vim).

**Comment by chrisbra** [comment]
open your color scheme, then `:source $VIMRUNTIME/colors/tools/check_colors.vim` It currently prints the issues it found. You can suppress individual issues if you put a comment in your colorscheme something like  `"@suppress Visual` (See also the source)

Capturing the result is currently a bit clunky, you have to use something like this:
```viml
redir @a | sil source c:\temp\color_check.vim|redir end
enew
$put a
```
Or similar.

I guess we can always improve the script, now that we have it to include more tests or add a better interface to it (but that would be part of another patch).

**Comment by lifepillar** [comment]
Has `check_colors.vim` been removed from Vim? The file `$VIMRUNTIME/colors/Readme.txt` still mentions it, but I do not seem able to find it.

**Comment by chrisbra** [comment]
@lifepillar it has been moved to the tools subdirectory:
(check_colors.vim)[https://github.com/vim/vim/blob/master/runtime/colors/tools/check_colors.vim]

**Comment by lifepillar** [comment]
So, maybe it depends on my Vim version (8.0.1750, installed with Homebrew in macOS), because it's not there.

**Comment by chdiza** [comment]
I can confirm that it's not present in Homebrew's "bottle" for vim; in fact, it's missing the "tools" subdirectory of `colors` altogether.  That's a bug in Homebrew, and they should be notified.

**Comment by chrisbra** [comment]
It is actually not being installed at all. Not sure where to put the check script, something like this perhaps:
```patch
diff --git a/src/Makefile b/src/Makefile
index d15a2dc76..04c5a2840 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -2485,6 +2485,7 @@ installrtbase: $(HELPSOURCE)/vim.1 $(DEST_VIM) $(DEST_RT) \
        cd $(DEST_PRINT); chmod $(FILEMOD) *.ps
 # install the colorscheme files
        cd $(COLSOURCE); $(INSTALL_DATA) *.vim README.txt $(DEST_COL)
+       cd $(COLSOURCE); $(INSTALL_DATA) tools/*.vim $(DEST_TOOLS)
        cd $(DEST_COL); chmod $(HELPMOD) *.vim README.txt
 # install the syntax files
        cd $(SYNSOURCE); $(INSTALL_DATA) *.vim README.txt $(DEST_SYN)
```

That would install below $VIMRUNTIME/tools.

**Comment by chrisbra** [comment]
(patch was slightly wrong, re-edited the previous comment)

**Comment by chrisbra** [comment]
Alternatively, we could install it into the colorscheme directory directly:
```patch
diff --git a/src/Makefile b/src/Makefile
index d15a2dc76..f40f31ce7 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -2484,7 +2484,7 @@ installrtbase: $(HELPSOURCE)/vim.1 $(DEST_VIM) $(DEST_RT) \
        cd $(PRINTSOURCE); $(INSTALL_DATA) *.ps $(DEST_PRINT)
        cd $(DEST_PRINT); chmod $(FILEMOD) *.ps
 # install the colorscheme files
-       cd $(COLSOURCE); $(INSTALL_DATA) *.vim README.txt $(DEST_COL)
+       cd $(COLSOURCE); $(INSTALL_DATA_R) *.vim tools README.txt $(DEST_COL)
        cd $(DEST_COL); chmod $(HELPMOD) *.vim README.txt
 # install the syntax files
        cd $(SYNSOURCE); $(INSTALL_DATA) *.vim README.txt $(DEST_SYN)
```

**Comment by chdiza** [comment]
As long as the script itself doesn't go directly in `colors`.
