### ISSUE TITLE
Netrw cannot write remote files (E382)

### ISSUE THREAD

**Issue by BoltsJ** [vim/vim#2329]
When editing a remote file using `:e scp://user@host/file`, netrw sets `buftype=nofile` which causes error E382 to be raised when trying to write changes. According to `:h buftype`, instead of using `bt=nofile`, netrw should use `bt=acwrite`.

I can replicate the issue with a fresh built version of vim isolated from the system runtime launched with `/opt/vim/bin/vim -u NORC --cmd 'set nocompatible'` and an empty `~/.vim`. The exact steps to reproduce are as follows:
1. `vim scp://<user>@<host>/<filepath>` or `:edit scp://<user>@<host>/<filepath>`
2. `:write`
3. "E382: Cannot write, 'buftype' option is set"

A temporary workaround I have found is to manually `:set bt=acwrite` before any write or to write using `:Nwrite`. Note, that netrw will reset to `bt=nofile` as part of every write.

**Comment by hoelzro** [comment]
I encountered this myself as well - it seems the culprit commit is b0d45e7f5, which bumped up the netrw runtime files.

**Comment by tagwint** [comment]
As a permanent workaround 
autocmd BufRead scp://* :set bt=acwrite
can be added to vimrc

**Comment by mawkler** [comment]
@tagwint 
> autocmd BufRead scp://* :set bt=acwrite
> can be added to vimrc

To me this only solves it for the first write, after that the same problem appears again.

**Comment by protist** [comment]
FWIW this workaround works indefinitely for me.

**Comment by hoelzro** [comment]
I've been using `set bt=` with the `BufWritePost` event and that's worked for me.

**Comment by gmackey** [comment]
For me it took the combination of using `set bt=` with both the `BufRead` and `BufWritePost` events.  The `BufRead` takes care of when the file is opened and first read.  The `BufWritePost` takes care of all writes.

**Comment by mawkler** [comment]
@gmackey 
> For me it took the combination of using set bt= with both the BufRead and BufWritePost events.

This did it for me, however the buffer closes after `:w` (which it also did before), which is sort of annoying.

**Comment by lilydjwg** [comment]
I encountered this too, and lost my edit. (I did `:xa` but the remote file wasn't saved like before.)

**Comment by yipu3** [comment]
Encountered this too while editing files under a samba directory.

**Comment by ThomasGHenry** [comment]
+1

**Comment by tony** [comment]
This has been driving me nuts. Though it's not happening for me when writing to files, it's happening to me when when I select files via `:LAg` (i think it's a location list?).

I will report back if I have more information (and possibly create a separate issue if I get enough to show they're definitely different). Same error, it's just not manifesting itself through remote files.

**Comment by chrisbra** [comment]
try to get the most recent netrw version from Charles page http://www.drchip.org/astronaut/vim/index.html#NETRW

If this still happens, have a look at `:h netrw-debug`

**Comment by k-takata** [comment]
I think this was a bug of Netrw v162 and it had many troubles. So Bram reverted it and now v156 is included in the vim repository. (I'm not sure this is fixed in v163b.)

**Comment by anoxic** [comment]
v165b seems to be working fine for me. I had some issues with the version packaged with vim 8.0.1283

**Comment by chrisbra** [comment]
Okay, since this problem seems to be fixed upstream, I'll go ahead and close it. I suppose Charles will send an update soon, since netrw hasn't been updated in a while.

**Comment by imambungo** [comment]
I face this problem when trying to save particular local files. If you are like me, you might only need to run `:set bt=` or `:set buftype=` command in vim to solve the problem once and for all for that particular file.

**Comment by chrisbra** [comment]
@imambungo 
have you updated your netrw version and tested with that? http://www.drchip.org/astronaut/vim/index.html#NETRW

**Comment by imambungo** [comment]
@chrisbra I never updated netrw manually, but I do update vim regularly. My vim version:  
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 01 2020 17:17:52)

**Comment by chrisbra** [comment]
so please try with the latest development version, to provide feedback to the author @cecamp.

**Comment by imambungo** [comment]
I've tried the latest development version, nothing happens. I think in my case the problem wasn't caused by netrw. For your information, I encountered the error (E382) when trying to save `.vimrc` and `.bachrc`, just these 2 files. I guess it was caused when I try to install some plugin, I don't know.

**Comment by imambungo** [comment]
> I face this problem when trying to save particular local files. If you are like me, you might only need to run `:set bt=` or `:set buftype=` command in vim to solve the problem once and for all for that particular file.

I think I just found the cause, it's related to #4738.

How to reproduce:
1. Open a file that has some URLs in it.
2. Try to save the file (it should work).
3. Try to open a URL with `gx`, encounter [this behavior](https://github.com/vim/vim/issues/4738#issuecomment-519269918).
4. Open the file again, try to save it, encounter error E382.
5. Fix the error with `:set bt=`.
6. Repeat.
