### ISSUE TITLE
[feature request] Option to make :terminal open existed terminal

### ISSUE THREAD

**Issue by UncleBill** [vim/vim#2335]
Provide an option, like `set term_open_existed` (default no).
With this switch on, `:terminal` opens existed terminal rather than creating new one.

🙇  Thanks!

**Comment by brammool** [comment]
unclebill wrote:

> Provide an option, like `set term_open_existed` (default no).
> With this switch on, `:terminal` opens existed terminal rather than
> creating new one.

I don't see how an option is useful for that.  It would block opening a
second terminal.

I can see how you would want to get an existing terminal in a window,
but you can already do that, if you know the buffer number.  use:
	:ls
to see the buffer number and use ":buf N" to get it into the current
window or ":sbuf N" to get it in a new window.

-- 
If the Universe is constantly expanding, why can't I ever find a parking space?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
On 22:20 Tue 14 Nov     , Bram Moolenaar wrote:
> 
> unclebill wrote:
> 
> > Provide an option, like `set term_open_existed` (default no).
> > With this switch on, `:terminal` opens existed terminal rather than
> > creating new one.
> 
> I don't see how an option is useful for that.  It would block opening a
> second terminal.
> 
> I can see how you would want to get an existing terminal in a window,
> but you can already do that, if you know the buffer number.  use:
> 	:ls
> to see the buffer number and use ":buf N" to get it into the current
> window or ":sbuf N" to get it in a new window.
> 
> -- 
> If the Universe is constantly expanding, why can't I ever find a parking space?
> 
>  /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
> ///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
> \\\  an exciting new programming language -- http://www.Zimbu.org        ///
>  \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

I have `:Term` command for that, and as Bram noted, sometimes `:term`
is useful to just open another terminal.  Then `Term` lets you choose
which terminal to re-open.  Below is the command.

Cheers,
Marcin

fun! Term()
  let bufs = TermBufs()
  if empty(bufs)
    term
    return
  elseif len(bufs) == 1
    let bnr = bufs[0].bufnr
  else
    for buf in bufs
      echo buf.name
    endfor
    let choice = confirm("Choose term: ", "&" . join(range(1, len(bufs)), "\n&"), 0)
    if choice == 0
      return
    else
      let bnr = bufs[choice-1].bufnr
    endif
  endif
  exe "sb " . bnr
endfun
com! Term call Term()

**Comment by chrisbra** [comment]
closing then.
