### ISSUE TITLE
Remove bottom bar of terminal when invoke built-in terminal

### ISSUE THREAD

**Issue by ghost** [vim/vim#2338]
Refer the issue [here](https://github.com/junegunn/fzf/issues/1143) and [here](https://github.com/junegunn/fzf/issues/1142).

**Comment by chrisbra** [comment]
please add relevant information here. Thanks.

**Comment by ghost** [comment]
When I use fzf that invokes builtin-terminal of vim8, terminal will preserve a bottom bar for itsself like this [pic](https://imgur.com/a/d3jQZ). The expected behavior works perfect in vim on linux [here](http://tilvim.com/img/fzffiles.gif)

**Comment by chrisbra** [comment]
I still don't follow. What kind of bottom bar are you talking about? Please make clear what exactly you expect. If possible, try to reduce the problem without having us to install some plugin which we possibly do not know (or understand what it does).

Also I am confused by this sentence:

> The expected behavior works perfect in vim on linux here

So it works on linux and does not work in Windows? What exactly?

**Comment by ghost** [comment]
Yes, I can produce this issue without fzf involved. Run `gvim -u NONE`.
[Here](https://imgur.com/a/iVlHR) is what I expect. Problem seems happen only on windows. I'd like to disable/hide statusline that contains `!C:\WINDOWS\system32\cmd.exe [running]`

**Comment by chrisbra** [comment]
So you want to disable the statusline. That is not possible at least if you have several windows and I think this is good to be able to distinguish where a window starts and ends. However you should be able to set the statusline to an empty string to make it more prettier.

I think this is a duplicate of #940 or another one which I currently do not find.

**Comment by ghost** [comment]
Yes, possible but in terminal case, if we can disable it completely, it'll help other plugins that work base on it.

**Comment by k-takata** [comment]
> The expected behavior works perfect in vim on linux here

I still have a question about this.
I think the behavior is the same both on Windows and Linux. Did you have some special settings on Linux?

**Comment by ghost** [comment]
My mistake, on linux fzf plugin will call external terminal so it does not has statusline like this [pic](http://tilvim.com/img/fzffiles.gif). Anything that stick with builtin terminal has to bear with that bar.

**Comment by brammool** [comment]
> Yes, I can produce this issue without fzf involved. Run `gvim -u NONE`.
> [Here](https://imgur.com/a/iVlHR) is what I expect. Problem seems happen only on windows. I'd like to disable/hide statusline that contains `!C:\WINDOWS\system32\cmd.exe [running]`

If it's the last window you can do:
	set laststatus=0


-- 
An alien life briefly visits earth.  Just before departing it leaves a
message in the dust on the back of a white van.  The world is shocked
and wants to know what it means.  After months of studies the worlds
best linguistic scientists are able to decipher the message: "Wash me!".

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
closing as invalid.
