### ISSUE TITLE
E16: Invalid range error during BufWinLeave of closing :terminal

### ISSUE THREAD

**Issue by gbarta** [vim/vim#2339]
Invoking the following file with vim -N -u should reproduce the problem:
```
fun! Nop()
endfun

fun! Reproduce()
    new
    exe "normal Aone\<CR>two"
    term ++close python -c "import time;time.sleep(3)"
    wincmd p
endfun

aug repro
    au!
    au BufWinLeave * call Nop()
    au VimEnter * call Reproduce()
aug END
```
I find it gives me the following error messages:
```
Error detected while processing BufWinLeave Auto commands for "*":
E16: Invalid range: call Nop()
```
It seems that the autocmd is being invoked somehow with a range context on the two-line buffer which is not the terminal.

**Comment by chrisbra** [comment]
Yeah, I can see that this is confusing. The problem is:
https://github.com/vim/vim/blob/5df95ea9ef34b5a898141ddc7134e4a7de713ba5/src/terminal.c#L2177-L2178
curbuf will be set to the (to be closed terminal window), but curwin->w_buffer isn't yet. However `do_bufdel()` will eventually call the BufLeave autocommands. Later on on invocation of the BufWinLeave autocommand, we determine the range for the `call` command:
https://github.com/vim/vim/blob/5df95ea9ef34b5a898141ddc7134e4a7de713ba5/src/ex_docmd.c#L2080-L2088
Note this checks curwin->w_cursor which points to the 2 line buffer, so we end up with `ea.line1=2` and `ea.line2=2` and even further, when doing the `invalid_range()` check, Vim again checks `curbuf` for containing enough lines to have valid addresses: 
https://github.com/vim/vim/blob/5df95ea9ef34b5a898141ddc7134e4a7de713ba5/src/ex_docmd.c#L4748-L4755
However here we are determining whether the address is correct in the 2 line buffer by checking the number in the terminal buffer. 

Perhaps all that is needed would be this patch:
```patch
diff --git a/src/ex_docmd.c b/src/ex_docmd.c
index 84a72e112..b895915b5 100644
--- a/src/ex_docmd.c
+++ b/src/ex_docmd.c
@@ -4747,7 +4747,7 @@ invalid_range(exarg_T *eap)
        {
            case ADDR_LINES:
                if (!(eap->argt & NOTADR)
-                       && eap->line2 > curbuf->b_ml.ml_line_count
+                       && eap->line2 > curwin->w_buffer->b_ml.ml_line_count
 #ifdef FEAT_DIFF
                            + (eap->cmdidx == CMD_diffget)
 #endif
```

**Comment by brammool** [comment]
Christian wrote:

> Yeah, I can see that this is confusing. The problem is:
> https://github.com/vim/vim/blob/5df95ea9ef34b5a898141ddc7134e4a7de713ba5/src/terminal.c#L2177-L2178
> curbuf will be set to the (to be closed terminal window), but curwin->w_buffer isn't yet. However `do_bufdel()` will eventually call the BufLeave autocommands. Later on on invocation of the BufWinLeave autocommand, we determine the range for the `call` command:
> https://github.com/vim/vim/blob/5df95ea9ef34b5a898141ddc7134e4a7de713ba5/src/ex_docmd.c#L2080-L2088
> Note this checks curwin->w_cursor which points to the 2 line buffer, so we end up with `ea.line1=2` and `ea.line2=2` and even further, when doing the `invalid_range()` check, Vim again checks `curbuf` for containing enough lines to have valid addresses: 
> https://github.com/vim/vim/blob/5df95ea9ef34b5a898141ddc7134e4a7de713ba5/src/ex_docmd.c#L4748-L4755
> However here we are determining whether the address is correct in the 2 line buffer by checking the number in the terminal buffer. 
> 
> Perhaps all that is needed would be this patch:
> ```patch
> diff --git a/src/ex_docmd.c b/src/ex_docmd.c
> index 84a72e112..b895915b5 100644
> --- a/src/ex_docmd.c
> +++ b/src/ex_docmd.c
> @@ -4747,7 +4747,7 @@ invalid_range(exarg_T *eap)
>         {
>             case ADDR_LINES:
>                 if (!(eap->argt & NOTADR)
> -                       && eap->line2 > curbuf->b_ml.ml_line_count
> +                       && eap->line2 > curwin->w_buffer->b_ml.ml_line_count
>  #ifdef FEAT_DIFF
>                             + (eap->cmdidx == CMD_diffget)
>  #endif
> ```

I'm sure there will be another problem popping up when
curwin->w_buffer != curbuf.  In general, executing arbitrary commands on
a buffer that is not in a window is going to break at some point.

You can see with the example that the window with the modified buffer is
closed, that shouldn't happen.

We need to use aucmd_prepbuf() and aucmd_restbuf().  I'll make a patch,
please check that it works well after that.

-- 
Bypasses are devices that allow some people to dash from point A to
point B very fast while other people dash from point B to point A very
fast.  People living at point C, being a point directly in between, are
often given to wonder what's so great about point A that so many people
from point B are so keen to get there and what's so great about point B
that so many people from point A are so keen to get there.  They often
wish that people would just once and for all work out where the hell
they wanted to be.
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
