### ISSUE TITLE
stty: 'standard input': Inappropriate ioctl for device

### ISSUE THREAD

**Issue by kenorb** [vim/vim#2343]
The following warning message appears when using Vim with the following syntax:

```
$ echo Hello | vim -
stty: 'standard input': Inappropriate ioctl for device
```

Is above warning message necessary?

**Comment by jamessan** [comment]
That message is not generated by vim. You probably have something in your vimrc that is either directly executing stty or you're running a shell command and your shell's init is executing stty.

**Comment by kenorb** [comment]
You're correct, executing Vim with `-u NONE` doesn't generate that error.

```
$ echo Hello | vim -u NONE -
Vim: Reading from stdin...
```
