### ISSUE TITLE
8.0.1312 breaks vim on macOS

### ISSUE THREAD

**Issue by chdiza** [vim/vim#2348]
Vim 8.0.1312 barely starts building before it craps out:

```
cc -c -I. -Ilibvterm/include -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -DINLINE="" -DVSNPRINTF=vim_vsnprintf -DIS_COMBINING_FUNCTION=utf_iscomposing_uint -DWCWIDTH_FUNCTION=utf_uint2cells -o objects/term_encoding.o libvterm/src/encoding.c
In file included from beval.c:11:
In file included from ./vim.h:1819:
./beval.h:46:5: error: unknown type name 'Widget'
    Widget              target;         /* widget we are monitoring */
    ^
./beval.h:47:5: error: unknown type name 'Widget'
    Widget              balloonShell;
    ^
```

**Comment by chdiza** [comment]
8.0.1313 merely moved the location of the failure.  Now it's here:

```
gcc -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/os_macosx.o os_macosx.m
In file included from os_macosx.m:19:
In file included from ./vim.h:1819:
./beval.h:46:5: error: unknown type name 'Widget'
    Widget              target;         /* widget we are monitoring */
    ^
```

**Comment by brammool** [comment]
Chdiza wrote:

> Vim 8.0.1312 barely starts building before it craps out:
> 
> ```
> cc -c -I. -Ilibvterm/include -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -DINLINE="" -DVSNPRINTF=vim_vsnprintf -DIS_COMBINING_FUNCTION=utf_iscomposing_uint -DWCWIDTH_FUNCTION=utf_uint2cells -o objects/term_encoding.o libvterm/src/encoding.c
> In file included from beval.c:11:
> In file included from ./vim.h:1819:
> ./beval.h:46:5: error: unknown type name 'Widget'
>     Widget              target;         /* widget we are monitoring */
>     ^
> ./beval.h:47:5: error: unknown type name 'Widget'
>     Widget              balloonShell;
>     ^
> ```

I suppose we need to wrap those fields in #ifdef FEAT_BEVAL_GUI.

-- 
hundred-and-one symptoms of being an internet addict:
4. Your eyeglasses have a web site burned in on them.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chdiza** [comment]
8.0.1314 again just shifts the failure:

```
gcc -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/os_macosx.o os_macosx.m
In file included from os_macosx.m:19:
In file included from ./vim.h:1819:
./beval.h:76:2: error: expected ';' after struct
} BalloonEval;
 ^
 ;
./beval.h:33:1: warning: typedef requires a name [-Wmissing-declarations]
typedef struct BalloonEvalStruct
^~~~~~~
./beval.h:76:3: warning: declaration does not declare anything [-Wmissing-declarations]
} BalloonEval;
  ^~~~~~~~~~~
```

**Comment by chdiza** [comment]
8.0.1315 is getting closer, but not there yet:

```
gcc -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/channel.o channel.c
In file included from os_mac_conv.c:19:
In file included from ./vim.h:1819:
./beval.h:76:3: error: typedef redefinition with different types ('struct BalloonEvalStruct' vs 'int')
} BalloonEval;
  ^
os_mac_conv.c:17:13: note: previous definition is here
typedef int BalloonEval;    /* used in header files */
            ^
1 error generated.
```

**Comment by chdiza** [comment]
Works now.  Cheers!
