### ISSUE TITLE
Status line disappears/get duplicated when window toolbar (WinBar) is present

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#2356]
To reproduce, after `vim --clean`:

```
:se splitbelow
:nnoremenu 1.10 WinBar.Next :bn<cr>
:split
```

I could not reproduce the duplicated status line with `--clean`, but in my setup, adding a window toolbar messes up things quite a bit. It's better seen through a screencast:

[![asciicast](https://asciinema.org/a/148504.png)](https://asciinema.org/a/148504)

You may also see how repeatedly entering and exiting the CtrlP plugin raises the status line each time.

**Comment by brammool** [comment]
Lifepillar wrote:

> To reproduce, after `vim --clean`:
> 
> ```
> :se splitbelow
> :nnoremenu 1.10 WinBar.Next :bn<cr>
> :split
> ```
> 
> I could not reproduce the duplicated status line with `--clean`, but
> in my setup, adding a window toolbar messes up things quite a bit.
> It's better seen through a screencast:
> 
> [![asciicast](https://asciinema.org/a/148504.png)](https://asciinema.org/a/148504)
> 
> You may also see how repeatedly entering and exiting the CtrlP plugin
> raises the status line each time.

I can't guess what settings in your setup matter.  Please try to make a
script that shows the failure with --clean.

The WinBar support is new, there are likely some drawing problems.
It does require a way to reproduce the problem, otherwise it's close to
impossible to fix.


-- 
How To Keep A Healthy Level Of Insanity:
2. Page yourself over the intercom. Don't disguise your voice.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lifepillar** [comment]
Ok,  I'll try to come up with a reproducible test for the duplicated bar.

>The WinBar support is new

I see. Somehow I thought it was an old feature that I had always missed :)

**Comment by lifepillar** [comment]
Ok, so this shows the problem better:

```
vim --clean -c 'set laststatus=2'
:se splitbelow
:nnoremenu 1.10 WinBar.Next :bn<cr>
:split
```

You should see that (a) the inactive status line is not drawn, and (b) the active status line is duplicated.

**Comment by brammool** [comment]
Lifepillar wrote:

> Ok,  I'll try to come up with a reproducible test for the duplicated bar.
> 
> >The WinBar support is new
> 
> I see. Somehow I thought it was an old feature that I had always missed :)

I added it for the terminal debugger.  Clicking "Next" is just so much
quicker than typing :Over.  And avoids having to change keyboard focus.
I'm sure it will be useful for other plugins as well.

It changes the window layout in a different way, thus there may be some
situations in which it doesn't work properly yet.

-- 
How To Keep A Healthy Level Of Insanity:
7. Finish all your sentences with "in accordance with the prophecy".

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
Lifepillar wrote:

> Ok, so this show the problem better:
> 
> ```
> vim --clean -c 'set laststatus=2'
> :se splitbelow
> :nnoremenu 1.10 WinBar.Next :bn<cr>
> :split
> ```
> 
> You should see that (a) the inactive status line is not drawn, and (b)
> the active status line is duplicated.

Thanks, I can reproduce it. Looks like the two windows overlap.

-- 
How To Keep A Healthy Level Of Insanity:
8. Don't use any punctuation marks.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
does 3167c3e7010ac7e2fd7d3 fix it?

**Comment by lifepillar** [comment]
Sure it does, thanks!

**Comment by lifepillar** [comment]
I still have some issues when I open CtrlP, though: the inactive status line in a split screen still disappears. I'll try to find some way to reproduce in a clean env.

**Comment by lifepillar** [comment]
Here you go:

```vim
:se splitbelow
:nnoremenu 1.10 WinBar.Next :bn<cr>
:split
```

Now, maximize a window with `<c-w>_`. Move between the two windows. It appears as if resizing doesn't take into account the WinBar properly.
