### ISSUE TITLE
Unable to avoid scrolling when switching buffers

### ISSUE THREAD

**Issue by Asheq** [vim/vim#2358]
By default, vim will purposefully try to vertically center the line that the cursor was on most recently when coming back to a buffer (e.g. with `Ctrl-^` or `:edit` if the buffer is already loaded).

I  find this disorienting. I would rather have my window and cursor position stay exactly how I left it. The script here does exactly that: http://vim.wikia.com/wiki/Avoid_scrolling_when_switch_buffers

That script seems to work _almost_ always. However, there is one odd case where it does not work because of perhaps a small bug in Vim:

**Scenario Where the Above Script Does Not Restore Window**: 

I start with a buffer (with a lot of lines relative to the height of the window) scrolled _all the way to the top_ (line 1 at the top of the window). I then move my cursor to anywhere in the bottom half of the window (.e.g with `L`). Line 1 of the buffer should still be visible at the top of the window. 

When I switch to another buffer (e.g. with `Ctrl-^`) and then back again, the window is not restored as expected. Instead, the line that I was on is in the center.

I'd appreciate any help here!

**:version**
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 10 2017 18:06:39)
macOS version
Included patches: 1-1250
Compiled by Homebrew

**Comment by chrisbra** [comment]
questions regarding customizing Vim and VimScript are more suitable on the vim-use mailinglist and vi.stackexchange.com. This here is about actual issues in Vim.

**Comment by Asheq** [comment]
Thanks for the response, Christian!

I'm not necessarily looking for help on the VimScript; I'm trying to address a potential bug in Vim itself, one that is causing the VimScript to not work as it should.

**Comment by Asheq** [comment]
I'm going to close this and post another issue that better explains the problem later.
