### ISSUE TITLE
No transparent background in terminal windows (in Terminal mode)

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#2361]
With these definitions:

```vim
hi Normal ctermfg=255 ctermbg=NONE guifg=#ffffff guibg=NONE guisp=NONE cterm=NONE gui=NONE
hi Terminal ctermfg=255 ctermbg=NONE guifg=#ffffff guibg=NONE guisp=NONE cterm=NONE gui=NONE
```

I get a transparent background in all windows as expected. I also get a transparent background in terminal windows when they are in Normal mode, but not when they are in Terminal mode. Shouldn't the background be transparent also in Terminal mode?

**Edit:** this happens only when `termguicolors` is set. With `notermguicolors`, the background is transparent also in Terminal mode, as expected. In fact, a minimal example to reproduce this issue is the following:

```
vim --clean
:set termguicolors
:terminal
<C-\>N
```

**Comment by brammool** [comment]
Lifepillar wrote:

> With these definitions:
> 
> ```vim
> hi Normal ctermfg=255 ctermbg=NONE guifg=#ffffff guibg=NONE guisp=NONE cterm=NONE gui=NONE
> hi Terminal ctermfg=255 ctermbg=NONE guifg=#ffffff guibg=NONE guisp=NONE cterm=NONE gui=NONE
> ```
> 
> I get a transparent background in all windows as expected. I also get
> a transparent background in terminal windows when they are in Normal
> mode, but not when they are in Terminal mode. Shouldn't the background
> be transparent also in Terminal mode? 

Is this with Vim in a terminal (then what terminal?) or in the GUI?
How do you set a transparent background anyway?

-- 
How To Keep A Healthy Level Of Insanity:
1. At lunch time, sit in your parked car with sunglasses on and point
   a hair dryer at passing cars. See if they slow down.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lifepillar** [comment]
That's Vim in a terminal. I have tried Terminal.app, iTerm2 and [Hyper](https://hyper.is), in macOS.

>How do you set a transparent background anyway?

The colorschemes I am using define `ctermbg=NONE guibg=NONE` for `Normal` and other highlight groups that should appear as having a transparent background. I am not doing anything special in my (OS) terminal settings, apart possibly setting a background image.

This is how a Vim terminal window looks in Normal mode and Terminal mode, respectively, with the `default` colorscheme (screenshots from iTerm2):

 
<img width="640" alt="terminal-normal" src="https://user-images.githubusercontent.com/1193314/33123751-4b37b188-cf7b-11e7-9268-873fe7f3d37f.png">

<img width="640" alt="default-terminal" src="https://user-images.githubusercontent.com/1193314/33123681-19efcdf4-cf7b-11e7-9c63-f849a9c63a51.png">

**Comment by brammool** [comment]
Lifepillar wrote:

> That's Vim in a terminal. I have tried Terminal.app, iTerm2 and [Hyper](https://hyper.is), in macOS.
> 
> >How do you set a transparent background anyway?
> 
> The colorschemes I am using define `ctermbg=NONE guibg=NONE` for `Normal` and other highlight groups that should appear as having a transparent background. I am not doing anything special in my (OS) terminal settings, apart possibly setting a background image.
> 
> This is how a Vim terminal window looks in Normal mode and Terminal mode, respectively, with the `default` colorscheme (screenshots from iTerm2):
> 
>  
> <img width="640" alt="terminal-normal" src="https://user-images.githubusercontent.com/1193314/33123751-4b37b188-cf7b-11e7-9268-873fe7f3d37f.png">
> 
> <img width="640" alt="default-terminal" src="https://user-images.githubusercontent.com/1193314/33123681-19efcdf4-cf7b-11e7-9c63-f849a9c63a51.png">

Please check the output of these commands:
	set t_RB t_RF t_Co
	echo v:termrbgresp
	echo v:termrfgresp

It also somehow depends on whether 'compatible is set or not, not sure
which side effect of that matters.  Hmm, seems t_Co is set to 8 in
'compatible' mode.

-- 
If Pacman had affected us as kids we'd be running around in dark rooms,
munching pills and listening to repetitive music.
                       -- Marcus Brigstocke

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lifepillar** [comment]
In both the terminals I have tried (Terminal.app and iTerm2) I get the following:

- `t_Co=256`
- `t_RB=^[]11;?^G`
- `t_RF=^[]10;?^G`
- `v:termrbgresp` and `v:termrfgresp` are empty.

**Comment by lifepillar** [comment]
AFAIC, this issue is solved for me. Terminal appearance is perfect. Thanks for your great job!

**Comment by joshuarubin** [comment]
This is still an issue for me with `termguicolors`. There's no way that I can find to prevent vim from filling the terminal background with a solid color. Switching the terminal to normal mode does fix it in places that there is no terminal output yet, but not for the whole window.

**Comment by lifepillar** [comment]
@joshuarubin, you are right. Which terminal are you using? In iTerm2, with `notermguicolors` everything is ok, but with `termguicolors` set I still have this issue. Contrary to my post on Nov 22, 2017, now in iTerm2 (v3.2.6) I get non-empty values for `v:termrbgresp` and `v:termrfgresp`:

```
v:termrbgresp          ^[]11;rgb:29/2c/36^G
v:termrfgresp          ^[]10;rgb:ff/ff/ff^G
```

**Comment by joshuarubin** [comment]
I'm using alacritty

**Comment by joshuarubin** [comment]
So how can we get this reopened?

**Comment by owlsome2501** [comment]
I can reproduce the issue under urxvt+tmux, termite+tmux and bare termite with `termguicolors`.

**Comment by matt1003** [comment]
I am able to reproduce this issue using terminator with `termguicolors`.

**Comment by gregory** [comment]
this did the trick for me: 
```
set notermguicolors
hi Terminal ctermbg=none
```

**Comment by lifepillar** [comment]
@gregory The problem is specifically for when `termguicolors` is set. This was not clear to me when I originally opened this issue: my apologies for the confusion my lack of clarity may have generated. I have edited my original post to better explain how to reproduce the issue.

**Comment by 00dani** [comment]
Experiencing exactly the same issue with kovidgoyal/kitty and the recently-released Vim 8.2. Terminal windows have a solid black background if `termguicolors` is set, but immediately become transparent as intended if I `set notermguicolors`.

The theme I'm using (gruvbox) usually sets a solid background colour, so I'm forcing transparency on it like so:
```vim
autocmd ColorScheme * highlight Normal ctermbg=NONE guibg=NONE
```
I tried doing this to the `Terminal` highlight group as well, but that has no effect.

**Comment by baltitenger** [comment]
based on `:help terminal-size-color`:
> ```
> For a color terminal the 'background' option is used to decide whether the
> terminal window will start with a white or black background.
> 
> To use a different color the Terminal highlight group can be used, for
> example:
> [...]
> ```
I think it decides whether to use the `Terminal` highlight group by checking if its `*bg` is defined for the current display type, and I guess `NONE` counts as undefined, so it thinks it shouldn't use the highlight group and falls back to `'background'`.
So, if I have `guibg=Red` in `Terminal`, I get a red background. But if I have `guibg=NONE`, I get a black or white background based on `'background'`.

**Comment by xebcam** [comment]
Did anyone found a solution?

**Comment by nickspoons** [comment]
> Did anyone found a solution?

No, unfortunately. I have a command I use for opening a terminal and running a command, and it also turns off `'tgc'` for the session

**Comment by ariel-miculas** [comment]
any plans for a fix/workaround?

**Comment by allbombson** [comment]
same issue with tgc and st
