### ISSUE TITLE
Cursor one line off in Terminal mode when window toolbar (WinBar) is present

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#2362]
Likely related to https://github.com/vim/vim/issues/2356: in Vim 8.0.1300, if you add a window toolbar to a terminal window, the cursor (but not the text) will be one line off while in Terminal mode. To reproduce, execute `vim --clean`, and then:

```vim
:terminal
:nnoremenu 1.10 WinBar.Next :bn<cr>
```

**Comment by brammool** [comment]
Lifepillar wrote:

> Likely related to https://github.com/vim/vim/issues/2356: in Vim
> 8.0.1300, if you add a window toolbar to a terminal window, the cursor
> (but not the text) will be one line off while in Terminal mode. To
> reproduce, execute `vim --clean`, and then:
> 
> ```vim
> :terminal
> :nnoremenu 1.10 WinBar.Next :bn<cr>
> ```

Didn't think of adding a WinBar to a terminal window would be something
useful.  I suppose it can be.  I'll look into making that work, but
don't expect it soon.

-- 
hundred-and-one symptoms of being an internet addict:
24. You realize there is not a sound in the house and you have no idea where
    your children are.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lifepillar** [comment]
This is very minor issue, which I am reporting only because I have stumbled on it by chance. As far as I am concerned, you might as well remove WinBars from terminal windows: I am not using that feature. Ditto for https://github.com/vim/vim/issues/2356.

**Comment by chrisbra** [comment]
Hm, would that patch fix the issue:
```patch
diff --git a/src/screen.c b/src/screen.c
index 6b69d13b6..3938b43c8 100644
--- a/src/screen.c
+++ b/src/screen.c
@@ -1174,6 +1174,8 @@ win_update(win_T *wp)
      */
     if (term_update_window(wp) == OK)
     {
+       if (winbar_height(wp) > 0)
+           redraw_win_toolbar(wp);
        wp->w_redr_type = 0;
        return;
     }
diff --git a/src/terminal.c b/src/terminal.c
index 744b7dedf..08c15cdbe 100644
--- a/src/terminal.c
+++ b/src/terminal.c
@@ -1343,6 +1343,8 @@ send_keys_to_term(term_T *term, int c, int typed)
 position_cursor(win_T *wp, VTermPos *pos)
 {
     wp->w_wrow = MIN(pos->row, MAX(0, wp->w_height - 1));
+    if (wp->w_winbar_height && wp->w_wrow > 0)
+       wp->w_wrow--;
     wp->w_wcol = MIN(pos->col, MAX(0, wp->w_width - 1));
     wp->w_valid |= (VALID_WCOL|VALID_WROW);
 }
```

**Comment by lifepillar** [comment]
It seems to work perfectly: the window toolbar is only visible in Normal mode now.
