### ISSUE TITLE
Information out of date

### ISSUE THREAD

**Issue by mang1375** [vim/vim#2370]
in ~/neovim/runtime/doc/insert.txt line 47,
http://georgevreilly.com/vim/ctags.html

This page is not exist(404 not found).

**Comment by chrisbra** [comment]
next time please mention the vim runtime :)
anyway, as I said on the neovim tracker, I posted a patch here:
https://groups.google.com/d/msg/vim_dev/1a74UP8j1y4/oKuFaL5fAgAJ

(I'll keep this open and let Bram close it once he has merged the runtime file update).

**Comment by brammool** [comment]
Included Christian's patch
