### ISSUE TITLE
\n in substitute command

### ISSUE THREAD

**Issue by akayunov** [vim/vim#2382]
Hi
I put next text(see end of message) to vim with shift+insert, then try to substitute all "\n" with real newline symbol and do:
: s/\\n/\r/g

vim highlight all "\n", but show error:  E486 Pattern not found : \\n and do nothing.
vim ver = 7.4

PS:
if you can't reproduce it try to do wrong replacement first as if you just make a typo: s/\n/\r/g
and after that do needed replacement: s/\\n/\r/g
Example of text:

Nov 27 09:26:44 us2fmfe-va-2 data_v4.error[50149]: [py.warnings] WARNING:  USER: -, CLIENT: -, REQUEST_ID: -
500/(1452L, 'Cannot add or update a child row: a foreign key constraint fails (`filemirror`.`uploads`, CONSTRAINT `uploads_organizations` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`))')
==================================
['  File "/opt/securisync/be-active/lib/ss/apps/data/handler.py", line 49, in application\n    return v4application.WSGIResolver(HANDLER_CONFIGS, HANDLER_TO_MODULE).handle_request(environ, start_response)\n', '  File "/opt/securisync/be-2.31.0/lib/ss/apps/v4application.py", line 655, in handle_request\n    return handler.execute(environ, start_response)\n', '  File "/opt/securisync/be-2.31.0/lib/ss/apps/v4application.py", line 504, in execute\n    self._legacy_wrapper(self.handler, self.last_request, self.last_response)\n', '  File "/opt/securisync/be-2.31.0/lib/ss/apps/v4application.py", line 420, in _legacy_wrapper\n    headers_out, result = handler(uri_in, query_in, headers_in, body_in, context)\n', '  File "/opt/securisync/be-2.31.0/lib/ss/apps/data/upload.py", line 41, in put_handler\n    DbUploads.create_upload_item(uri_in[\'organization_id\'], uri_in[\'upload_id\'])\n', '  File "/opt/securisync/be-2.31.0/lib/ss/db/models/uploads.py", line 25, in create_upload_item\n    ignored_warnings=[\'Duplicate entry\']\n', '  File "/opt/securisync/be-2.31.0/lib/ss/db/model.py", line 214, in execute\n    self.last_count = cursor.execute(query, args)\n', '  File "/opt/securisync/virtualenv-2.24.0/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 253, in execute\n    self._warning_check()\n', '  File "/opt/securisync/virtualenv-2.24.0/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 155, in _warning_check\n    warn(self.Warning(*w[1:3]), stacklevel=3)\n', '  File "/usr/lib/python2.7/logging/__init__.py", line 1705, in _showwarning\n    s = warnings.formatwarning(message, category, filename, lineno, line)\n', '  File "/opt/securisync/be-2.31.0/lib/ss/logger.py", line 190, in warning_format\n    return format_traceback(message, traceback.format_stack(), {})\n']
==================================

**Comment by chrisbra** [comment]
this bug report is hard to read. Did you miss the `%` sign for the `:s` command?

**Comment by akayunov** [comment]
fixed, thank you
