### ISSUE TITLE
v_CTRL-A/X not incrementing some numbers when selection ends in an empty line

### ISSUE THREAD

**Issue by j201** [vim/vim#2387]
Selecting several numbers followed by an empty line and then using CTRL-A/X can result in only some of them being incremented/decremented. v_g_CTRL-A/X shows similar behaviour.

Input to reproduce:
`10i0<CR><Esc>vgg<C-A>`

Result:

```
1
1
1
1
1
1
1
0
0
0

```

I've reproduced this on MSYS2 on Windows using version 8.0.1305 and in gvim on Windows using version 8.0.586, both with `vim -N -u NONE`.

**Comment by h-east** [comment]
Hmm? My reply of vim_dev is not reflected in this issue of github.
https://groups.google.com/d/msg/vim_dev/uoA9Q9nARn8/J3vmL-uNAQAJ

**Comment by j201** [comment]
Thanks for the quick patch! I don't currently have a vim build set up, but if it would help, I could set one up and try it out when I have some time, hopefully within the next week or so.
