### ISSUE TITLE
&isident option is responsible for parsing special characters

### ISSUE THREAD

**Issue by ZyX-I** [vim/vim#2389]
Consider the following script:

```
% vim -u NONE -i NONE -N --cmd 'nnoremap <C-u> x' --cmd 'set isident=' --cmd 'nnoremap <C-x> u' --cmd $'nnoremap \C-x|nnoremap \C-u|echo "-"|nnoremap' --cmd cq
No mapping found
n  <C-U>       * x
-
n  <C-U>       * x
n  <C-x>       * u
```

You may see here that while `<C-u>` mapping was defined as expected `<C-x>` mapping was defined exactly as if I used `<LT>C-x>`, which is not the case. I do not really see why &isident option needs to affect VimL parsing at all (I mean parsing `$env`, this does not include `/\i` and “after a match of the 'define' option”: `$env` is editor-global, `/\i` and &define could be/are filetype-specific), but this specific case is listed neither under `:h 'isident'` nor under `:h key-notation`.

The root of the problem is the use of vim_isIDc() in find_special_key().

Vim version 8.0.1358.

**Comment by ZyX-I** [comment]
There are also uses in get_special_key_code().

**Comment by lacygoill** [comment]
I can reproduce with this shell command:

    vim -Nu NONE --cmd 'set isi= | nno <C-x> u|nno | cq'
    n  <C-x>       * u

Notice that the `x` is printed in lowercase:

    n  <C-x>       * u
          ^
          ✘

Which means that `<C-x>` was not translated into the literal control character `^X`.

The issue disappears as soon as `C` is included back inside the value of the `'isident'` option:

                                ✔
                                v
    vim -Nu NONE --cmd 'set isi=C | nno <C-x> u|nno | cq'
    n  <C-X>       * u
          ^
          ✔

---

> The root of the problem is the use of vim_isIDc() in find_special_key().

As of 8.2.2725, that's on line 2829 in `src/misc2.c`:
https://github.com/vim/vim/blob/e8c4660a55364a5d3e395652d1202b8702666823/src/misc2.c#L2829

    // Find end of modifier list
    last_dash = src;
    for (bp = src + 1; *bp == '-' || vim_isIDc(*bp); bp++)
                                     ^-------^
