### ISSUE TITLE
ctrl-] prefixes backslash to [ character in keyword

### ISSUE THREAD

**Issue by smhc** [vim/vim#2392]
Configure keywords to include the '[' character:

`:set iskeyword+=[`

Perform a 'ctrl-]' on the following text:

`ABC[`

Error produced:

`E426: tag not found: ABC\[`

vim will only look up the keyword if it also contains a backslash in the tags file.
Problem does not exist when using the command, ':ta ABC['
A similar issue exists when using '*' to search on the keyword.

(on a side note, it would be really helpful if iskeyword could support strings as well as characters. even better if it had regex support).

Seems somewhat related to https://github.com/vim/vim/issues/228

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov  8 2017 14:16:47)
Included patches: 1-1274

**Comment by chrisbra** [comment]
isn't the `[` taken as a pattern, so it must be escaped?

**Comment by smhc** [comment]
Escaped where?

In the setting of iskeyword, it makes no difference.
In the tags file - it matches, but:
1. Using ':ta ABC[' doesn't match.
2. ctags doesn't generate escaped [ characters, nor specify that they should be.

In retrospect using '[' as a keyword character doesn't solve my problem. It is actually a bad character to use as code often consists of ABC[1234]. My problem is that I'd like to specifically match the case of 'ABC&[]', only where the brackets are empty. Essentially I want iskeyword to have an additional regex of:

`set iskeyword += [a-zA-Z0-9]+[&#](\[\]|\{\})?`

But this isn't possible in vim. It's only needed in my case for ctrl-] support. It would be really good for ctrl-] to allow regex support, perhaps independent of iskeyword. Values in ctags are often populated with some strange and wonderful regexes that vim can't capture easily.

I can see why it is implemented this way however, as a list of characters is a lot easier to work backwards and forwards to determine the bounds of a 'word' when the cursor is in the middle of one. I'm not sure how this might work with a regex or even a basic string.

**Comment by chrisbra** [comment]
if `CTRL-]` is handling the given argument as pattern (which it looks like it), it would need to escape the `[` because it could be otherwise considered start of a collection, but `:h :tag` speaks about handling the given argument as pattern if it starts with a `/`

Note, I did not check the source, perhaps I am missing something here.

**Comment by smhc** [comment]
It works fine for other regex characters such as $, ?, ]. Note the error message itself isn't the problem - that is just reflective of what vim is attempting to find in the tags file, which is incorrect.

Even if vim escapes the character, it should 'unescape' it when matching against entries in the tags file. One would expect hitting 'ctrl-]' over a word would find that match in the tags file if there is a match.

I believe this is a duplicate of https://github.com/vim/vim/issues/228, only it pertains to the `[` character rather than `\` character. Both are being escaped incorrectly.

Either way it's not too much of a problem as I doubt anyone would have '[' in their iskeyword set. It is the wrong way to solve the problem I was trying to solve. Unfortunately I don't see a good solution for what I'm trying to do other than a custom function to determine the current tag.
