### ISSUE TITLE
Without a TTY, ex is fully buffered when interactive

### ISSUE THREAD

**Issue by bk2204** [vim/vim#2399]
When no TTY is available, ex is fully buffered instead of line buffered.  This makes it unusable for interactive use.  For example, nothing is printed when typing the following:

```shell
$ ssh localhost ex
i
a
b
c
.
%p
```
If you then run `q!`, the lines will be printed, because the buffer is flushed when Vim exits.

Since line buffering isn't harmful for noninteractive use, it's probably fine to just turn on line buffering the file all the time when started as ex.

**Comment by chrisbra** [comment]
fixed by  42b23fa
