### ISSUE TITLE
italicize italics in asciidoc.vim

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vim/vim#240]
```
italics are just bolded and colored, instead of being italicized. The rst 
syntax italicizes italics, see changeset 825.

https://code.google.com/p/vim/source/browse/runtime/syntax/rst.vim#180

I attached a patch for asciidoc.vim

What version of the product are you using? On what operating system?
7.4+335, Arch Linux.


```

Original issue reported on code.google.com by `muffinpo...@gmail.com` on 19 Jul 2014 at 7:07

Attachments:
- [vim_asciidoc.patch](https://storage.googleapis.com/google-code-attachments/vim/issue-240/comment-0/vim_asciidoc.patch)

**Comment by chrisbra** [comment]
seems fixed with the current runtime files.
