### ISSUE TITLE
Exit terminal properly back to current buffer

### ISSUE THREAD

**Issue by ghost** [vim/vim#2400]
Produce steps: gvim8 patch 1-1358 / windows 10, compiled with +terminal.
- `gvim --clean`
- open an arbitrary file
- type `:terminal`
- type `exit`  

Result: terminal window buffer still exist after filed `exit` command. Have to manually type `bdelete` to back to previous buffer.
Expected result: after type `exit`, terminal buffer should be killed and back to previous buffer.

**Comment by lifepillar** [comment]
Try `:terminal ++close`.

**Comment by ghost** [comment]
Is there any option to make default?

**Comment by lifepillar** [comment]
I don't think so. But you can define your own command:

```vim
:command! -nargs=* Terminal :terminal ++close
```

and maybe (untested):

```vim
:cnoreabbrev terminal Terminal
```

**Comment by chrisbra** [comment]
please ask user questions on the vim-use ml or vi.stackexchange.com.
