### ISSUE TITLE
When 4 spaces are created add icon

### ISSUE THREAD

**Issue by TheBabu** [vim/vim#2403]
I know that you can make it so that spaces and tabs are shown in vim using listchars:
`set listchars=tab:➡\`
`set listchars=space:␣`

What I want to achieve is this:
When 4 spaces are created, make it so that the very first space is changed into an icon
Is there any way to do this in vim?

**Comment by chrisbra** [comment]
No, remember Vim is a text editor and not a word processor. Also please note this is for issues about vim and not user support. Use vi.stackexchange.com or the vim-use mailinglist for user questions.

**Comment by TheBabu** [comment]
Alright, I'll use that instead...
