### ISSUE TITLE
Is netrw setting nohidden?

### ISSUE THREAD

**Issue by jnewbery** [vim/vim#2408]
In the last month I've noticed that `nohidden` is set even though `set hidden` is in my `.vimrc`.

Digging a bit, I've found that if I open a file directly with `vim <file>` and then check `:set hidden?`, `hidden` is set. If I open other files from within vim with `:e <file>` or using marks, then `hidden` remains set. If I go into netrw, then hidden is set to nohidden globally, and remains set for all new buffers that I open.

`:verbose set hidden?` shows `Last set from /usr/share/vim/vim80/autoload/netrw.vim`, and looking in that file, I see that the most recent change was:

```
" Date:		Nov 03, 2017
" Version:	162
```

This seems to coincide with when I started seeing this issue. I can work around this with `au BufWinEnter * set hidden` in my vimrc, but the question remains: why is netrw changing my global `hidden` setting?

(If this is the wrong place to raise a netrw issue, then please accept my apologies and let me know where a better place to do so is!)

**Comment by Eluminae** [comment]
I also add that netrw seems to clear the unnamed register.
- Edit file
- yy one line
- Ex then come back to the file
- p 
-> it paste an empty line return
=> it should paste the previously yanked line

**Comment by stacyharper** [comment]
I do not have this problem anymore. Could you try to upgrade your vim version and report if the problem has been solved for you too ?

**Comment by chrisbra** [comment]
closing then.

**Comment by jnewbery** [comment]
Yes, appears to have been fixed by https://github.com/vim/vim/commit/4697399e8c805325009351a2488e3da530d0af38. Thanks!
