### ISSUE TITLE
Can not resize a terminal window with mouse when it is focused

### ISSUE THREAD

**Issue by UncleBill** [vim/vim#2410]
As the title said.

**Comment by k-takata** [comment]
On which platform? Vim or gvim?

**Comment by nuko8** [comment]
As for me, just after a terminal was opened and the focus remained there, the behavior the OP is describing in the title was confirmed for both `xterm` and `iTerm2` on Mac.

That wasn't the whole story, however.  The behavior I found wasn't as simple as "As the title said." 

Once I switched the focus to the previous window after opening a terminal, tried resizing the windows with trackpad, which resizing worked perfectly as expected, and went back to the terminal, then somehow the mouse resizing started working (More precisely, it started working downwards only, then for both directions afterwards).

I do think it's poster's responsibility to give a good description of his issue to people.  In particular, I guess people want to know what terminal emulator the OP was using when he came across the issue as well as the platform and the Vim version he was using then.

**Comment by UncleBill** [comment]
>On which platform? Vim or gvim?

It's Windows 10 (64bit), and gVim.

**Comment by mattn** [comment]
```diff
diff --git a/src/terminal.c b/src/terminal.c
index 61630d5cc..b06c3b4d2 100644
--- a/src/terminal.c
+++ b/src/terminal.c
@@ -1308,7 +1308,8 @@ send_keys_to_term(term_T *term, int c, int typed)
 	case K_MOUSELEFT:
 	case K_MOUSERIGHT:
 	    if (mouse_row < W_WINROW(curwin)
-		    || mouse_row > (W_WINROW(curwin) + curwin->w_height)
+		    || mouse_row > (W_WINROW(curwin) + curwin->w_height
+			- curwin->w_status_height)
 		    || mouse_col < curwin->w_wincol
 		    || mouse_col > W_ENDCOL(curwin)
 		    || dragging_outside)
```
Could you please try this fix?

**Comment by UncleBill** [comment]
@mattn I don't know yet. 
BTW, both vertical and horizontal terminal windows can not resize.

**Comment by mattn** [comment]
@UncleBill Ah, you are right. Just decreesing is enough to fix.

```diff
diff --git a/src/terminal.c b/src/terminal.c
index 61630d5cc..c72b9e5ae 100644
--- a/src/terminal.c
+++ b/src/terminal.c
@@ -1308,9 +1308,9 @@ send_keys_to_term(term_T *term, int c, int typed)
 	case K_MOUSELEFT:
 	case K_MOUSERIGHT:
 	    if (mouse_row < W_WINROW(curwin)
-		    || mouse_row > (W_WINROW(curwin) + curwin->w_height)
+		    || mouse_row > (W_WINROW(curwin) + curwin->w_height - 1)
 		    || mouse_col < curwin->w_wincol
-		    || mouse_col > W_ENDCOL(curwin)
+		    || mouse_col > (W_ENDCOL(curwin) - 1)
 		    || dragging_outside)
 	    {
 		/* click or scroll outside the current window */
```

**Comment by UncleBill** [comment]
@mattn Nice to see your patch been applied! 👍 
I haven't test it, cause I don't have the building environment. But I would like to append a more complicate case:

```
|   N   |   N   |   N   |
-------------------------
|   N   |   T   |   N   |
-------------------------
|   N   |   N   |   N   |
```
`T` stands for terminal window here

Can't resize with both terminal window's right border and bottom one.
Could you do a test for this case?

**Comment by mattn** [comment]
Yes this change works fine.

![](https://go-gyazo.appspot.com/0d9ac4a1f0575828.png)

**Comment by UncleBill** [comment]
💯 Thanks!

**Comment by dpelle** [comment]
@UncleBill  wrote:

> I haven't test it, cause I don't have the building environment. 

You can download recent Windows binaries at:

https://github.com/vim/vim-win32-installer/releases

**Comment by UncleBill** [comment]
@dpelle Thanks ! I know that.
