### ISSUE TITLE
netrw seems to force selection=inclusive

### ISSUE THREAD

**Issue by cristibalan** [vim/vim#2412]
I have `set selection=exclusive` in my `.vimrc`. After opening and closing the netrw directory browser, `selection` is now set to `inclusive`.

Currently, I am forcing it back with:

```
au WinEnter * set selection=exclusive
au BufEnter * set selection=exclusive
```
macvim 8.0.1272 (142), netrw version 162

Previous version (macvim 8.0.1257 (141), netrw version 156) does not have this issue.

After some investigation, b0d45e7f5354375edd02afafde3bd37dac1515ff and #2408 seem to be related.

**Comment by k-takata** [comment]
Could you try `:verbose set selection?` to check whether netrw actually sets the option?

**Comment by cristibalan** [comment]
Sorry, forgot to mention. Yes, netrw changes it.

![kapture 2017-12-05 at 11 53 18](https://user-images.githubusercontent.com/122/33600835-292eda66-d9b3-11e7-9f68-80135683c8ab.gif)

**Comment by lacygoill** [comment]
Fixed by https://github.com/vim/vim/commit/4697399e8c805325009351a2488e3da530d0af38
