### ISSUE TITLE
inconsistent behavior for gtk gui find/replace dialog

### ISSUE THREAD

**Issue by kiloliter** [vim/vim#2418]
I tried to use the gtk find/replace dialog to replace text that had a newline in it (with "\n"). It works just fine if I click "replace all", but if I click "replace", it will find the first instance, but not replace anything.

I wrote a patch to fix this, but then I wondered what the correct behavior even be. Should the gui find/replace dialog allow "\n" at all? I think it would be useful if it did, but I thought it would be good to ask here first.

I attached a short video of the bug.

Thanks.

[vim_gui_replace_bug.zip](https://github.com/vim/vim/files/1533573/vim_gui_replace_bug.zip)

**Comment by nuko8** [comment]
(I'm going to talk about the issue, assuming people have already watched the short video.)

> I tried to use the gtk find/replace dialog to replace text that had a newline in it (with "\n"). It works just fine if I click "replace all", but if I click "replace", it will find the first instance, but not replace anything.

As shown in the video, if one clicks "replace", then no replacement takes place, and he gets "No match at cursor, finding next" instead.

Nonetheless, if one does `:s//hi` immediately after closing the dialog (which result would tell us whether or not the dialog passed the correct regular expression to the Vim core), then he gets
```
test test hitest test test ...
```
From this inconsistency and the one you've already mentioned, I think we can call it a bug.

> I wrote a patch to fix this, ...

I think the one would be worth a PR.

**Comment by nuko8** [comment]
I forgot to mention this:

> if one does :s//hi immediately after closing the dialog

`:&` will also do and would help us know whether or not both "Find what:" and "Replace with:" values were passed to the Vim core correctly.

**Comment by kiloliter** [comment]
Ok, I looked at the code more. At first, I wasn't sure if the gui find/replace dialog was even intended to allow escape characters, but now I'm pretty sure the original intent was to _not_ allow them. The programmer who created the original code just made an oversight that allowed some escape characters to slip through.

While I was working on it, I also noticed two other, related bugs:

If the string has a '?' in it, and you search in the up direction, things can behave strangely. 
[vim_question_mark_bug.zip](https://github.com/vim/vim/files/1549446/vim_question_mark_bug.zip)

If you put a '\\' at the end of a string, things can behave strangely, since vim thinks you're escaping the final '/' in the substitution string.

I created a pull request for all a fix for all these bugs: [https://github.com/vim/vim/pull/2435](https://github.com/vim/vim/pull/2435)
