### ISSUE TITLE
mouse scroll can not work in xshell by v8.0.1309

### ISSUE THREAD

**Issue by fcying** [vim/vim#2419]
It work righ in vim 8.0.1200

vim 8.0.1300 can scroll, but statusline display error

vim 8.0.1376 can not scroll.

I use xshell(terminal type: xterm) connect to ubuntu 16.04 ssh. If I use gnome terminal(bash) in Ubuntu 16.04, it work fine.

**Comment by brammool** [comment]
> It work righ in ver 8.0.1300

It works fine for me.  We'll need more information.  E.g., what terminal
are you using to run tmux in?  What is v:termresponse?  Is 'term' set to
"tmux"?

-- 
From "know your smileys":
 :-)	Funny
 |-)	Funny Oriental
 (-:	Funny Australian

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by fcying** [comment]
I use xshell(terminal type: xterm) connect to ubuntu 16.04 ssh.   If I use gnome terminal(bash) in Ubuntu 16.04, it work fine.

echo v:termresponse have nothing.

'term' set to "tmux" isn't work also.


test vimrc
```
set nocompatible
set guioptions=
set mouse=n

if exists("$TMUX")
  set term=tmux
endif

filetype plugin indent on
syntax enable
```

test tmux conf:
```
set -g default-terminal "screen-256color"
set -s escape-time 0
setw -g mode-keys vi
```

**Comment by fcying** [comment]
@brammool  Locate the problem is 51b0f3701ecb440aa72ab6017c1df6940c0e0f6f
```
51b0f3701ecb440aa72ab6017c1df6940c0e0f6f is the first bad commit
commit 51b0f3701ecb440aa72ab6017c1df6940c0e0f6f
Author: Bram Moolenaar <Bram@vim.org>
Date:   Sat Nov 18 18:52:04 2017 +0100

    patch 8.0.1309: cannot use 'balloonexpr' in a terminal

    Problem:    Cannot use 'balloonexpr' in a terminal.
    Solution:   Add 'balloonevalterm' and add code to handle mouse movements in a
                terminal. Initial implementation for Unix with GUI.

:040000 040000 1af927d6ab21f511d6a12df88fb44efaa35a9454 ac95b5bc5497c924cc12fa4d074bb47055764781 M      runtime
:040000 040000 ae9769caab08f498e828c48aa2a2cd7ebec67338 b92c397eeb9720b0f29348570ae88a9c6db911b8 M      src
```

**Comment by fcying** [comment]
@brammool 
when I remove the `held_button = MOUSE_RELEASE;` which add after v8.0.1309, it work fine in xshell. 
What is the use of this?

```
diff --git a/src/term.c b/src/term.c
index 83b54e18c..359c17100 100644
--- a/src/term.c
+++ b/src/term.c
@@ -5625,6 +5625,7 @@ check_termcode(
                    modifiers |= MOD_MASK_ALT;
                key_name[1] = (wheel_code & 1)
                                        ? (int)KE_MOUSEUP : (int)KE_MOUSEDOWN;
+               held_button = MOUSE_RELEASE;
            }
            else
                key_name[1] = get_pseudo_mouse_code(current_button,
```

**Comment by CandyGumdrop** [comment]
I seem to have the same problem using `st` as my terminal without tmux.  Removing the `held_button = MOUSE_RELEASE;` line fixes it for me too.  st used to work fine before the commit mentioned by @fcying was added.  xterm and rxvt-unicode work fine either way.

The way it seems to behave is as though it always scrolls up one step after either scrolling up or down one step, so scrolling up scrolls twice as far, but scrolling down doesn't work at all, but positions the cursor a few lines down if it was previously at the top of the screen, as though it has just scrolled down and then up.

I have `TERM` set to `st-256color` and I'm using the latest st from the suckless git repository, along with their up-to-date `st.info` terminfo description.

`v:termresponse` seems to be empty (I don't think `t_RV` is supported by st).

**Comment by brammool** [comment]
Appears to have been fixed by patch 8.0.1659.
Now if we can also make mouse move work....

**Comment by fcying** [comment]
@brammool  I test in 8.0.1661, if not remove `held_button = MOUSE_RELEASE;`,  it can scroll up, but can't scroll down...

**Comment by brammool** [comment]
> @brammool  I test in 8.0.1661, if not remove `held_button = MOUSE_RELEASE;`,  it can scroll up, but can't scroll down...

I'm using tmux right now, and scrolling works in both directions.
Perhaps it's a limit of the underlaying terminal?


-- 
Contrary to popular belief, Unix is user friendly.
It just happens to be selective about who it makes friends with.
                                               -- Dave Parnas

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by fcying** [comment]
@brammool  It is not a problem with tmux,  use xshell(terminal type: xterm) connect to ubuntu 16.04 ssh, the problem will occur.

**Comment by chrisbra** [comment]
Perhaps xshell is not compatible enough with xterm? Have you tried actually with an xterm?

**Comment by brammool** [comment]
> @brammool  It is not a problem with tmux,  use xshell(terminal type: xterm) connect to ubuntu 16.04 ssh, the problem will occur.

I can't claim I fully understand how tmux works, but I believe it
greatly depends on the underlying terminal (emulator).  Thus first thing
to do is to find out whether xshell works properly without using tmux.


-- 
Two percent of zero is almost nothing.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by fcying** [comment]
@chrisbra
using gnome terminal(bash) in Ubuntu 16.04, it work fine, using xshell(terminal type: xterm or linux) connect to ubuntu 16.04 ssh, work wrong(after v8.0.1309).

@brammool  
using xshell without using tmux is also wrong.
xshell version: xshell 6 build 0076

**Comment by numberZero** [comment]
Have the same problem in `st`. The reason is that while running `vim`, `st` reports mouse events using a variant of *Normal* mode, and not X10 mode, so that each scroll step generates two events: “button ... press” and “button release.” The latter confuses `vim`, which interprets it as “scroll up” for whatever reason.

An excerpt from the `console_codes(4)` manpage:

> The  X10  compatibility  mode  sends an escape sequence on button press encoding the location and the mouse button pressed.  It is      enabled by sending ESC [ ? 9 h and disabled with ESC [ ? 9 l.  On button press, xterm(1) sends ESC [ M bxy (6 characters).  Here b       is  button-1,  and x and y are the x and y coordinates of the mouse when the button was pressed.  This is the same code the kernel       also produces.
>
> Normal tracking mode (not implemented in Linux 2.0.24) sends an escape sequence on both button press and release.  Modifier information  is  also  sent.   It  is  enabled by sending ESC [ ? 1000 h and disabled with ESC [ ? 1000 l.  On button press or release,       xterm(1) sends ESC [ M bxy.  The low two bits of b encode  button  information:  0=MB1  pressed,  1=MB2  pressed,  2=MB3  pressed,        3=release.   The  upper  bits encode what modifiers were down when the button was pressed and are added together: 4=Shift, 8=Meta,       16=Control.  Again x and y are the x and y coordinates of the mouse event.  The upper left corner is (1,1).

@fcying Thank you for the patch, it helps.

**Comment by CandyGumdrop** [comment]
I've since found that `set ttymouse=sgr` fixes it for st rather than having a `ttymouse` of `xterm` or `xterm2`.

**Comment by baiwfg2** [comment]
@brammool  HI.  I can scroll up , but cannot scroll down in vim 8.1.1. Here's my `.vimrc`:
```
unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

set nu
set hlsearch

set tabstop=4
set softtabstop=4
set shiftwidth=4
set cindent
set autoindent
set smartindent
set smarttab
set expandtab

set mouse=a

```
I just use xshell to remotely connect server. I don't think xshell is the problem, because it worked in vim74.

**Comment by fcying** [comment]
@baiwfg2  you can upgrade your xshell version.
with xshell version `6:0089`, I need remove `held_button = MOUSE_RELEASE;` for mouse scroll work fine
with xshell version `6:0098`, No such problem.

**Comment by baiwfg2** [comment]
@fcying OMG, big surprise. It's really the xshell version issue... Thanks !

**Comment by axiaoxin** [comment]
I using Xshell 5.0.0048 also can't scroll down , but can scroll up in vim 8.1. vim7.4 is work fine.
