### ISSUE TITLE
"Local Additions" entries clobbered by similar filename

### ISSUE THREAD

**Issue by joshklod** [vim/vim#2421]
Documentation files with a filename matching the beginning of another documentation filename (e.g. `plugin.txt` and `plugin-extra.txt`) do not appear in the "Local Additions" list (`:h local-additions`).

### Test Case:

    mkdir -p ~/.vim/doc
    cd ~/.vim

    echo '*testplug.txt*   Example Plugin'   > doc/testplug.txt
    echo '*testplug2.txt*  Example Plugin 2' > doc/testplug2.txt
    vim '+help local-additions'

`testplug.txt` is not included:

    LOCAL ADDITIONS:				*local-additions*
    |testplug2.txt|  Example Plugin 2

With a different filename:

    mv doc/testplug.txt doc/testplug1.txt
    vim '+help local-additions'

`testplug.txt` is now listed:

    LOCAL ADDITIONS:				*local-additions*
    |testplug.txt|   Example Plugin
    |testplug2.txt|  Example Plugin 2

Tested with Vim 8.0.1216.

**Edit:** Also tested with Vim 8.0.1376.

**Comment by chrisbra** [comment]
fixed by https://github.com/vim/vim/releases/tag/v8.0.1383
