### ISSUE TITLE
autoload script is loaded twice when do :source

### ISSUE THREAD

**Issue by mattn** [vim/vim#2423]
autoload/foo.vim
```vim
let foo#bar = {}

echo 'loading foo#bar'
function! foo#bar.do_something()
endfunction
```
when `:source autoload/foo.vim`, `loading foo#bar` is displayed once.

```vim
"let foo#bar = {}

echo 'loading foo#bar'
function! foo#bar.do_something()
endfunction
```
This also diaplay `loading foo#bar` once. of course E121 will be occured.

however, below display `loading foo#bar` twice.
```vim
echo 'loading foo#bar'
function! foo#do_something()
endfunction
```

I know, this is `:source` command not autoloading. So you may think this behavior is expected. but at least it should behave as same as in dict func.

```diff
diff --git a/src/userfunc.c b/src/userfunc.c
index e18768455..71b52d708 100644
--- a/src/userfunc.c
+++ b/src/userfunc.c
@@ -1886,7 +1886,7 @@ ex_function(exarg_T *eap)
      * g:func	    global function name, same as "func"
      */
     p = eap->arg;
-    name = trans_function_name(&p, eap->skip, 0, &fudi, NULL);
+    name = trans_function_name(&p, eap->skip, TFN_NO_AUTOLOAD, &fudi, NULL);
     paren = (vim_strchr(p, '(') != NULL);
     if (name == NULL && (fudi.fd_dict == NULL || !paren) && !eap->skip)
     {
```
should fix this issue.

**Comment by brammool** [comment]
Yasuhiro Matsumoto wrote:

> autoload/foo.vim
> ```vim
> let foo#bar = {}
> 
> echo 'loading foo#bar'
> function! foo#bar.do_something()
> endfunction
> ```
> when `:source autoload/foo.vim`, `loading foo#bar` is displayed once.
> 
> ```vim
> "let foo#bar = {}
> 
> echo 'loading foo#bar'
> function! foo#bar.do_something()
> endfunction
> ```
> This also diaplay `loading foo#bar` once. of course E121 will be occured.
> 
> however, below display `loading foo#bar` twice.
> ```vim
> echo 'loading foo#bar'
> function! foo#do_something()
> endfunction
> ```
> 
> I know, this is `:source` command not autoloading. So you may think
> this behavior is expected. but at least it should behave as same as in
> dict func.

Hmm, not sure we should support sourcing an autoload script directly.

While trying some things I ran into the problem that calling a
dictionary function doesn't trigger the autoload.  Christian had a patch
for that, but it wasn't correct.  I'll make a patch now (and a test).

> 
> ```diff
> diff --git a/src/userfunc.c b/src/userfunc.c
> index e18768455..71b52d708 100644
> --- a/src/userfunc.c
> +++ b/src/userfunc.c
> @@ -1886,7 +1886,7 @@ ex_function(exarg_T *eap)
>       * g:func	    global function name, same as "func"
>       */
>      p = eap->arg;
> -    name = trans_function_name(&p, eap->skip, 0, &fudi, NULL);
> +    name = trans_function_name(&p, eap->skip, TFN_NO_AUTOLOAD, &fudi, NULL);
>      paren = (vim_strchr(p, '(') != NULL);
>      if (name == NULL && (fudi.fd_dict == NULL || !paren) && !eap->skip)
>      {
> ```
> should fix this issue.

I guess that should work, thanks.

-- 
From "know your smileys":
 O:-)	Saint

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
