### ISSUE TITLE
`t_Cs` set on unsupported terminal; Undercurl fallback broken

### ISSUE THREAD

**Issue by joshklod** [vim/vim#2424]
I noticed a while ago that `'t_Cs'` is somehow getting a value assigned, though nothing is assigning it.  It is neither in the terminfo entry, nor (as far as I can tell) the built-in termcaps.  It is definitely not getting set in a script.  (Yes, even with plugins disabled via `vim -N -u NONE`.)  So where does it come from?

Its value happens to be the xterm cursor color escape sequence.

Before 8b9e20afb0da79a21155988a38704b5777cc2efe, this code was never used, so it didn't really matter. But now it is causing a problem. As of this patch, Vim notices the presence of this option and assumes the terminal is capable of displaying undercurl.  As such, it no longer falls back to a normal underline.

Even manually clearing the option has no effect.  It seems once Vim detects that the feature is present, it will never attempt to fall back again.

### How to Reproduce:

I was able to reproduce the issue with several xterm-compatible terminals on Debian and Cygwin, using Vim v8.0.1376.

    iThis sentence has a spelilng mistake<Esc>
    :hi SpellBad cterm=undercurl
    :set spell
        -> 'spelilng' is not underlined
    :set t_Cs?
        -> t_Cs=^[]12;%p1%s^G
    :set t_Cs=
        -> 'spelilng' is still not underlined
    :hi SpellBad cterm=underline
        -> This works fine

**Comment by dpelle** [comment]
I'm having the same issue:
*  prior to vim-8.0.1358, Vim in terminal would underline misspelled words with my colorscheme.
* starting with vim-8.0.1357, Vim in terminal no longer underlines misspelled words

I can reproduce the bug with these simplified ~/.vimrc and ~/.vim/color/rastafari.vim files:

```
$ cat ~/.vimrc
set spell
set t_Co=256
colorscheme rastafari
```
```
$ cat ~/.vim/colors/rastafari.vim
set background=dark
hi clear
syntax reset
let g:colors_name="rastafari"
hi SpellBad   guisp=red    gui=undercurl guifg=NONE guibg=NONE ctermfg=NONE ctermbg=NONE term=underline cterm=underline
hi SpellCap   guisp=yellow gui=undercurl guifg=NONE guibg=NONE ctermfg=NONE ctermbg=NONE term=underline cterm=underline
hi SpellRare  guisp=blue   gui=undercurl guifg=NONE guibg=NONE ctermfg=NONE ctermbg=NONE term=underline cterm=underline
hi SpellLocal guisp=orange gui=undercurl guifg=NONE guibg=NONE ctermfg=NONE ctermbg=NONE term=underline cterm=underline
```

Then I see underlined typos as expected with: 
```
$ echo "Test wiith a typo" | vim-8.0.1357 -
```
But I no longer see underlined typos with vim-8.0.1358:
```
$ echo "Test wiith a typo" | vim-8.0.1358 -
```
The bug happens in all terminals that I tried (xterm among others).

**Comment by joshklod** [comment]
@dpelle That might be a different issue...

My problem is with using `cterm=undercurl`, you are using `cterm=underline`.  For me, `cterm=underline` works fine (see my example).

**Comment by puremourning** [comment]
I have the exact same issue - undercurl is not degrading to underline in the terminal.

My term is `xterm-256color` (actually iTerm2/tmux integration).

The difference in my case is that `t_Cs` is being determined as unset (or at least empty), but apparently not `NULL` (enough for the following check):

```c
              if ((attr & HL_UNDERCURL) && T_UCS != NULL) /* undercurl */
                  out_str(T_UCS);
```

`:echo t_Cs?` = `  t_Cs=`

I confirmed by setting a breakpoint on the `out_str` above, T_UCS is set to a valid, but empty string:

```
(lldb) p term_strings[29]
(char_u *) $3 = 0x0000000103c5f418 ""
```

Let me know if there are any other diagnostics I could provide.

**Comment by puremourning** [comment]
Thanks!

**Comment by blueyed** [comment]
@joshklod 
I assume your issue is still not fixed?

At least for me I see:
```
% TERM=tmux-256color vim --cmd 'echom &t_Cs' -c q
^[]12;%p1%s^G
```

Given `t-undercurl-pink.vim`:
```vim
let &term = 'tmux-256color'
hi SpellBad cterm=undercurl
set spell
```

`vim -Nu t-undercurl-pink.vim t-undercurl-pink.vim` will cause a pink color for me (with rxvt-unicode as the terminal).
I've noticed this initially when using tmux, but it happens also outside of it.

What is your TERM?

**Comment by k-takata** [comment]
I think #2126 will fix this kind of problem.

**Comment by joshklod** [comment]
@blueyed Well, half of it is fixed.

Undercurl fallback works properly as long as `t_Cs` is unset.  However, `t_Cs` is still being set when it shouldn't be, as you demonstrated.  (In hindsight, I probably should have submitted a separate issue for that.)

The pink color in your example is not a bug, it comes from the default colorscheme.  This modified demo works correctly for me in Vim v8.0.1451:

    let &term = 'tmux-256color'
    set t_Cs=
    hi SpellBad cterm=undercurl ctermbg=NONE
    set spell

My `$TERM` is `xterm-256color` and my terminal is mintty. But I always test with various configurations of both the variable and the actual terminal.

**Comment by redeyes2015** [comment]
> However, t_Cs is still being set when it shouldn't be

I was also troubled by this issue, while trying out vim 8 recently (using Jonathon F's [ppa], previously on v8.0.1542) . However, version 8.0.1567, released today, has seemed to solve this issue, well, at least for me. The terminal emulator is xfce4-terminal. I can confirm that `t_Cs` is no longer set by default, and undercurl falls back to underline correctly.

I have no idea which patch fixes this. (I would guess it is [patch 8.0.1556].) Hope this is a good news for others also having this `t_Cs` issue.

[ppa]: https://launchpad.net/~jonathonf/+archive/ubuntu/vim/+packages
[patch 8.0.1556]: https://github.com/vim/vim/commit/590ec878a52b3b3d4453475f1eb4899f2b37969f

**Comment by blueyed** [comment]
@joshklod 
> The pink color in your example is not a bug, it comes from the default colorscheme.

But the bug is that it is being used, no?

> This modified demo works correctly for me in Vim v8.0.1451:
> set t_Cs=

That is only a workaround, correct?

I've created https://github.com/vim/vim/issues/3471 now.

@k-takata 
> I think #2126 will fix this kind of problem.

I've tried it now, but it does not fix it for me.

**Comment by joshklod** [comment]
@blueyed 

> > The pink color in your example is not a bug, it comes from the default colorscheme.
> 
> But the bug is that it is being used, no?

You're right.  Sorry, I misinterpreted your previous comment.  I thought you were referring to the pink background color of misspelled words, which is expected from the default colorscheme.  If the cursor is turning pink, then that is indeed a bug, likely caused by this issue.

> > set t_Cs=
> 
> That is only a workaround, correct?

Correct, that is only a workaround.  Well, kinda.

You're overriding the escape sequence that Vim uses for undercurl to match the compatibility of your terminal.  I wouldn't exactly call that a workaround, because that is exactly how the `t_XX` settings are intended to be used.

The real problem is that you shouldn't *have* to manually override a setting that should have never been set in the first place.

**Comment by blueyed** [comment]
*edit* comment moved to https://github.com/vim/vim/issues/3471#issuecomment-424447977
