### ISSUE TITLE
ch_read(mode=NL) cannot read data which not have NL in rest

### ISSUE THREAD

**Issue by mattn** [vim/vim#2425]
When the channel mode is NL, ch_read cannot read rest part of data.

test.py
```python
import sys
# foo\n
# \n
# bar\n
# \n
# hoge
sys.stdout.write("foo\n\nbar\n\nhoge")
```

test.vim
```vim
" :help read-in-close-cb
function! s:on_close(channel) abort
  echomsg 'Start'
  while ch_status(a:channel, {'part': 'out'}) ==# 'buffered'
    echomsg ch_read(a:channel)
  endwhile
  echomsg 'End'
endfunction

call job_start('python test.py', {
      \ 'out_mode': 'nl',
      \ 'close_cb': function('s:on_close'),
      \})
```

`ch_status(a:channel, {'part': 'out'})` return `buffered` always because channel have data. But ch_read doesn't pick-out data from channel because it doesn't have NL. So this goes endless-loop.

This code is written in `:help read-in-close-cb`.

```vim
	func! CloseHandler(channel)
	  while ch_status(a:channel, {'part': 'out'}) == 'buffered'
	    echomsg ch_read(a:channel)
	  endwhile
	endfunc
	let job = job_start(command, {'close_cb': 'CloseHandler'})
```

I think this code have to call ch_readraw instead of ch_read (when mode is NL). But, ch_readraw also doesn't read the rest data. This is a bug of ch_readraw which ch_readraw is depend on the mode.

https://gist.github.com/mattn/270362fa9a72dff143832ea0d150fc6f

 This patch should fix. So I think the `:help read-in-close-cb` should be fxied too.

```vim
	func! CloseHandler(channel)
	  while ch_status(a:channel, {'part': 'out'}) == 'buffered'
	    echomsg ch_readraw(a:channel)
	  endwhile
	endfunc
	let job = job_start(command, {'close_cb': 'CloseHandler'})
```

However, I still have unclear. In C code, fgets can read rest data even if the data doesn't have `\n`. So I wonder we have to fix ch_read. Also we have to add new API to know that ch_read can read something at least.

@brammool how do you think?

**Comment by brammool** [comment]
Yasuhiro Matsumoto wrote:

> When the channel mode is NL, ch_read cannot read rest part of data.
> 
> test.py
> ```python
> import sys
> # foo\n
> # \n
> # bar\n
> # \n
> # hoge
> sys.stdout.write("foo\n\nbar\n\nhoge")
> ```
> 
> test.vim
> ```vim
> " :help read-in-close-cb
> function! s:on_close(channel) abort
>   echomsg 'Start'
>   while ch_status(a:channel, {'part': 'out'}) ==# 'buffered'
>     echomsg ch_read(a:channel)
>   endwhile
>   echomsg 'End'
> endfunction
> 
> call job_start('python test.py', {
>       \ 'out_mode': 'nl',
>       \ 'close_cb': function('s:on_close'),
>       \})
> ```
> 
> `ch_status(a:channel, {'part': 'out'})` return `buffered` always because channel have data. But ch_read doesn't pick-out data from channel because it doesn't have NL. So this goes endless-loop.
> 
> This code is written in `:help read-in-close-cb`.
> 
> ```vim
> 	func! CloseHandler(channel)
> 	  while ch_status(a:channel, {'part': 'out'}) == 'buffered'
> 	    echomsg ch_read(a:channel)
> 	  endwhile
> 	endfunc
> 	let job = job_start(command, {'close_cb': 'CloseHandler'})
> ```
> 
> I think this code have to call ch_readraw instead of ch_read (when mode is NL). But, ch_readraw also doesn't read the rest data. This is a bug of ch_readraw which ch_readraw is depend on the mode.
> 
> https://gist.github.com/mattn/270362fa9a72dff143832ea0d150fc6f
> 
>  This patch should fix. So I think the `:help read-in-close-cb` should be fxied too.
> 
> ```vim
> 	func! CloseHandler(channel)
> 	  while ch_status(a:channel, {'part': 'out'}) == 'buffered'
> 	    echomsg ch_readraw(a:channel)
> 	  endwhile
> 	endfunc
> 	let job = job_start(command, {'close_cb': 'CloseHandler'})
> ```
> 
> However, I still have unclear. In C code, fgets can read rest data even if the data doesn't have `\n`. So I wonder we have to fix ch_read. Also we have to add new API to know that ch_read can read something at least.
> 
> @brammool how do you think?

Thanks for the patch.  It appears to break the existing tests, e.g.:

    call ch_sendraw(handle, "echo something\n")
    call assert_equal("something", ch_readraw(handle))

This uses ch_readraw(), but the newline is being stripped because the
channel is in NL mode.  I think we need to preserve that behavior.

We can also make it so that ch_read() gets the last text even when a
final NL is missing.  That's better than getting stuck, waiting for the
NL.

So one can use ch_readraw() on a NL mode channel to not wait for the NL
to arrive, but it still does NUL to NL conversion.

I'll make it work this way, please check if this works properly.


-- 
From "know your smileys":
 *<|:-)	Santa Claus (Ho Ho Ho)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by wsdjeg** [comment]
I also get issue about it, the `out_cb` callback func will not be called when the data has no newline.

**Comment by mattn** [comment]
This can be closed by https://github.com/vim/vim/commit/620ca2da372dc9c892022faff83d363c67cc5c45 ?

**Comment by brammool** [comment]
Does the test in the original issue work now?
