### ISSUE TITLE
Ocaml runtime files not up to date

### ISSUE THREAD

**Issue by glacambre** [vim/vim#2428]
The Ocaml runtime files appear to be out of date, the commentstring isn't set in [vim's runtime files](https://github.com/vim/vim/blob/e4b78e2a42e9030348770764c478b73caa925539/runtime/ftplugin/ocaml.vim#L10) while it is in the [vim-ocaml repo](https://github.com/rgrinberg/vim-ocaml/blob/5c37f200329ab734a2bddee917084562289f938a/ftplugin/ocaml.vim#L10).

**Comment by jamessan** [comment]
Then the maintainers of the Ocaml runtime files should send Bram an update.

**Comment by glacambre** [comment]
Oh, sorry, I assumed they did send an update, given how old the change was. After taking a deeper look at the repo I linked, it doesn't seem to be maintained by one of the maintainers listed in the runtime files. Would it be fine if I just sent a single-line patch to add a `set commentstring=(*%s*)` to `ftplugin/ocaml.vim`? It's the one thing I'm really interested in.

**Comment by brammool** [comment]
> Oh, sorry, I assumed they did send an update, given how old the change
> was. After taking a deeper look at the repo I linked, it doesn't seem
> to be maintained by one of the maintainers listed in the runtime
> files. Would it be fine if I just sent a single-line patch to add a
> `set commentstring=(*%s*)` to `ftplugin/ocaml.vim`? It's the one thing
> I'm really interested in.

The problem with including patches from various sources is that once the
maintainer sends me a new version, I have no idea if those patches are
included or not.  If not, then we'll fall back to old behavior.

That is why I very much prefer for the maintainer to take care of
patches.  Also to do a check that it works for everyone.

-- 
From "know your smileys":
 :-X	My lips are sealed

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by glacambre** [comment]
My problem is that I can't find the "official repo" for these runtime files. The link in the current runtime file is dead, and digging a little deeper only leads to a personal repository that does more that just aggregating ocaml runtime files. The repo I linked to doesn't belong to anybody on the maintainer list of the current runtime file.

I'll try to send an email to each person listed in the file and see what they answer, but I get the (maybe misguided) feeling that the ocaml runtime files aren't maintained by them anymore. I'll close the issue for now.
