### ISSUE TITLE
Wrong highlighting in latex

### ISSUE THREAD

**Issue by urbainvaes** [vim/vim#2433]
Hi!

When I edit with `vim -N -u NONE` the following document,

```
\documentclass{article} 
\usepackage{amsmath} 
 
\begin{document} 
\begin{subequations} 
    \begin{align} 
        &1 + 1 = 2 \\
        &2 + 2 = 4
    \end{align} 
\end{subequations} 
\end{document}
```
and use `:syntax on`, the line `\end{subequations}` appears as an error, although I believe this is correct latex code.

Best, Urbain

**Comment by k-takata** [comment]
Dr. Chip commented at https://groups.google.com/d/msg/vim_dev/Q1YYNLNNes4/E0UC9zQvBwAJ .
(I don't know why his comment is reflected here.)

**Comment by lacygoill** [comment]
Fixed by https://github.com/vim/vim/commit/f0b03c4e98f8a7184d8b4a5d702cbcd602426923.
