### ISSUE TITLE
Vim can't build the athena GUI on macOS High Sierra

### ISSUE THREAD

**Issue by chdiza** [vim/vim#2444]
When I try, I get the following errors:
```
gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_ATHENA   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1     -I/usr/X11/include    -o objects/os_mac_conv.o os_mac_conv.c
In file included from os_macosx.m:18:
In file included from ./vim.h:1812:
./beval.h:47:5: error: unknown type name 'Widget'
    Widget              target;         /* widget we are monitoring */
    ^
./beval.h:48:5: error: unknown type name 'Widget'
    Widget              balloonShell;
    ^
./beval.h:49:5: error: unknown type name 'Widget'
    Widget              balloonLabel;
    ^
./beval.h:50:5: error: unknown type name 'XtIntervalId'
    XtIntervalId        timerID;        /* timer for run */
    ^
./beval.h:52:5: error: unknown type name 'XtAppContext'
    XtAppContext        appContext;     /* used in event handler */
    ^
./beval.h:53:5: error: unknown type name 'Position'
    Position            x;
    ^
./beval.h:54:5: error: unknown type name 'Position'
    Position            y;
    ^
./beval.h:55:5: error: unknown type name 'Position'
    Position            x_root;
    ^
./beval.h:56:5: error: unknown type name 'Position'
    Position            y_root;
    ^
./beval.h:67:5: error: unknown type name 'Dimension'
    Dimension           screen_width;   /* screen width in pixels */
    ^
./beval.h:68:5: error: unknown type name 'Dimension'
    Dimension           screen_height;  /* screen height in pixels */
    ^
In file included from os_mac_conv.c:18:
In file included from ./vim.h:1812:
./beval.h:47:5: error: unknown type name 'Widget'
    Widget              target;         /* widget we are monitoring */
    ^
./beval.h:48:5: error: unknown type name 'Widget'
    Widget              balloonShell;
    ^
./beval.h:49:5: error: unknown type name 'Widget'
    Widget              balloonLabel;
    ^
./beval.h:50:5: error: unknown type name 'XtIntervalId'
    XtIntervalId        timerID;        /* timer for run */
    ^
gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_ATHENA   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1     -I/usr/X11/include    -o objects/channel.o channel.c
./beval.h:52:5: error: unknown type name 'XtAppContext'
    XtAppContext        appContext;     /* used in event handler */
    ^
./beval.h:53:5: error: unknown type name 'Position'
    Position            x;
    ^
./beval.h:54:5: error: unknown type name 'Position'
    Position            y;
    ^
./beval.h:55:5: error: unknown type name 'Position'
    Position            x_root;
    ^
./beval.h:56:5: error: unknown type name 'Position'
    Position            y_root;
    ^
./beval.h:67:5: error: unknown type name 'Dimension'
    Dimension           screen_width;   /* screen width in pixels */
    ^
./beval.h:68:5: error: unknown type name 'Dimension'
    Dimension           screen_height;  /* screen height in pixels */
    ^
```

**Comment by chdiza** [comment]
My configure flags were:
```
--disable-netbeans
--disable-nls
--enable-gui=athena
```

If I don't specify athena, I get different errors:
```
gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MAC -fno-common -fpascal-strings -Wall -Wno-unknown-pragmas -mdynamic-no-pic -pipe -I. -Iproto -DMACOS_X -DMACOS_X_DARWIN -I/Applications/Xcode.app/Contents/Developer/Headers/FlatCarbon  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/os_macosx.o os_macosx.m
gui_mac.c:37:10: fatal error: 'Devices.h' file not found
#include <Devices.h> /* included first to avoid CR problems */
         ^~~~~~~~~~~
In file included from os_macosx.m:18:
In file included from ./vim.h:287:
./os_mac.h:31:11: fatal error: 'Quickdraw.h' file not found
# include <Quickdraw.h>     /* Apple calls it QuickDraw.h... */
          ^~~~~~~~~~~~~
gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MAC -fno-common -fpascal-strings -Wall -Wno-unknown-pragmas -mdynamic-no-pic -pipe -I. -Iproto -DMACOS_X -DMACOS_X_DARWIN -I/Applications/Xcode.app/Contents/Developer/Headers/FlatCarbon  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/os_mac_conv.o os_mac_conv.c
In file included from os_mac_conv.c:18:
In file included from ./vim.h:287:
./os_mac.h:31:11: fatal error: 'Quickdraw.h' file not found
# include <Quickdraw.h>     /* Apple calls it QuickDraw.h... */
          ^~~~~~~~~~~~~
1 error generated.
make[1]: *** [objects/os_mac_conv.o] Error 1
make[1]: *** Waiting for unfinished jobs....
1 error generated.
make[1]: *** [objects/gui_mac.o] Error 1
1 error generated.
make[1]: *** [objects/os_macosx.o] Error 1
make: *** [first] Error 2
```

I don't think we're *supposed* to be able to build an X11 GUI other than athena on macOS anyway, but I thought I'd report it here.

**Comment by nuko8** [comment]
Thank you for the report.

The key to building the Athena GUI on Mac is to give `--disable-darwin` as well as `--enable-gui=athena` to ` configure`.

Basically, with `--disable-darwin`, `configure` tries treating the host system as a variant of UNIX having no macOS-specific API.

So, if XQuartz (an X11 implementation for macOS) is installed, `configure --disable-darwin --enable-gui=athena` should detect X11 and Xaw libraries correctly and create auxiliary files which are suitable for `make(1)` to build the GUI without the errors seen above, which result from conflicts between UNIX's generic API and macOS-specific API.

**Comment by chdiza** [comment]
Thanks, that will build.  But unfortunately, all I get now is:
```
E323: Cannot open display
Press ENTER or type command to continue24;0M
```
This happens whether I do `vim -g` or just `vim` followed by `:gui`.

This is on iTerm2, but the same thing happens on Terminal.app except that it's "23;0M" appended to the message rather than "24;0M".

**Comment by chrisbra** [comment]
do you have a X11 server running and $DISPLAY variable set?

**Comment by nuko8** [comment]
> E323: Cannot open display

(Probably, E323 is a typo of E233)
This error message indicates that the Athena GUI failed to establish a connection to the X server.  As implied by  @chrisbra 's comment, you cannot establish a connection to an X server not being running,  This is a general principle.

For macOS, however, if an X client is invoked when XQuartz is not being running, then launchd(1) automatically invokes XQuartz.  In other words, since the very first X connection is established by the OS even if there's no running X server there, it appears to the user as if the X server were already being running when he invoked the X client.  (Having said that, for XQuartz to complete the startup process, it takes a couple of dozen seconds, most of which are used to update caches.  So, in reality, it would appear to the user that `vim -g` hanged at the moment.)

Accordingly, the E233 error indicates that something went wrong with your Mac/XQuartz side when you did `vim -g`.    In fact, I tried reproducing the E233 error with the newly installed High Sierra and XQuartz, but I couldn't.   

Honestly, I have no idea why the error took place.  Maybe the XQuartz wasn't installed properly?
Did you log out after installing XQuartz and then log in, which procedure is needed for the system to recognize the newly installed XQuartz?   Can you run XQuartz from Launchpad (XQuartz should be in the "Other" icon).   By default, an xterm will appear on the screen when XQuartz is launched from  there.

**Comment by chdiza** [comment]
I tried it in two ways, with XQuartz already running, and with XQuartz not already running.  It makes no difference.

> Did you log out after installing XQuartz and then log in

I thought I had, but after a reboot it seems to work.  Thanks.

> The key to building the Athena GUI on Mac is to give --disable-darwin as well as --enable-gui=athena to configure.

The configure script should automatically act as if --disable-darwin was passed, if --enable-gui=athena is given on macOS.  There is zero indication in `configure --help` that the former must also be entered if the latter is entered.  Nor is there anything in `:h os_mac` or `:h darwin`.  And `:h gui` doesn't contain the word "darwin" anywhere.  Helpgrepping for `athena` doesn't yield anything either that would tell the user about this.

**Comment by chdiza** [comment]
Someone on the vim_dev list asked why I'm even trying to do this in the first place (the message is not showing up here on GitHub).

I'm only doing it to potentially help debug a problem in MacVim, by comparing MacVim's behavior to other gVim behavior.  Since I don't have a machine that isn't a mac, the best I can do is build an X11 gVim on my mac.  I don't actually *use* the athena GUI on macOS---not because there's something weird about an athena gVim in particular, but because the interface of XQuartz with the rest of macOS is just unusable.  (Cmd-tabbing can't get you individual apps inside XQuartz, the Cmd key isn't generally usable, XQuartz windows tend to not be movable with mac window managers, etc. etc.)

**Comment by nuko8** [comment]
> The configure script should automatically act as if --disable-darwin was passed, if --enable-gui=athena is given on macOS. There is zero indication in configure --help that the former must also be entered if the latter is entered. Nor is there anything in :h os_mac or :h darwin. And :h gui doesn't contain the word "darwin" anywhere. Helpgrepping for athena doesn't yield anything either that would tell the user about this.

Seems like we need to do something about that...some documentation at least.  I'll look into that.  Anyway, if there's anyone who finds that automation useful, I'm absolutely one of them :)

> I'm only doing it to potentially help debug a problem in MacVim, by comparing MacVim's behavior to other gVim behavior.

An idea like this would help both MacVim and Vim development much, as every gvim implementation broadly consists of two layers; one is the interface between an abstracted GUI and the Vim core, and another is library/framework code to incarnate that abstraction.

For instance, if both MacVim and Athena on Mac gives the same or a similar buggy behavior.  Then it is quite natural to think it an issue of the abstracted GUI and thus better to report it to vim_dev first.  In contrast to that, if that behavior appears to be specific to MacVim, it's highly likely an MacVim issue; vim_dev wouldn't do much about that when that is the case.  So, consideration like that would help us much to get bug fixes on the fast track, which can't fail anybody.

> but because the interface of XQuartz with the rest of macOS is ~just unusable~ not-well-interoperable. (Cmd-tabbing can't get you individual apps inside XQuartz, the Cmd key isn't generally usable, XQuartz windows tend to not be movable with mac window managers, etc. etc.)

That explains well what MacVim is (The strikethrough is mine :).

**Comment by PegasusWang** [comment]
add —disable-darwin to the options
