### ISSUE TITLE
CursorHoldI events trigger at unexpected time when there are timers firing

### ISSUE THREAD

**Issue by lilydjwg** [vim/vim#2451]
1. install python3 and its neovim package
2. extract [this](https://github.com/vim/vim/files/1562972/cursorholdbug.zip) and put it in ~/.vim (containss nvim-yarp, vim-hug-neovim-rpc and some minimal code to reproduce the bug; you can install the plugins and copy the simple code under pack/general/start/deoplete too)
3. run gvim (terminal vim doesn't have this problem; Linux with GTK 2 GUI, don't know about others)
4. in insert mode, type some text quickly
5. try to undo several times

You'll see that the insertion is broken into many steps for undoing, because CursorHoldI has been called too many times.

I tracked this down from deoplete (see https://github.com/Shougo/deoplete.nvim/issues/598).

I think the problem happens because, in gui.c:2980, when `gui_wait_for_chars_or_timer(p_ut)` returns `FAIL`, Vim fires CursorHold* events. But in `gui_wait_for_chars_or_timer`, when a timer calls `feedkeys`, it may return `FAIL` soon.

This is the timing I have logged:

```
[
    ['NOTIFY:', [1513338040, 179913]],
    ['NOTIFY:', [1513338040, 431771]],
    ['BACK:', [1513338040, 474465]],
    ['BACK:', [1513338040, 494892]],
    ['feedkeys:', [1513338040, 524562]],
    ['NOTIFY:', [1513338040, 527912]],
    ['BACK:', [1513338040, 537664]],
    ['feedkeys:', [1513338040, 544299]],
    ['NOTIFY:', [1513338040, 557622]],
    ['NOTIFY:', [1513338040, 569784]],
    ['BACK:', [1513338040, 583423]],
    ['BACK:', [1513338040, 585836]],
    ['feedkeys:', [1513338040, 586457]],
    ['NOTIFY:', [1513338040, 601140]],
    ['BACK:', [1513338040, 631092]],
    ['feedkeys:', [1513338040, 633510]],
    ['feedkeys:', [1513338040, 635674]],
    ['NOTIFY:', [1513338040, 658948]],
    ['NOTIFY:', [1513338040, 666987]],
    ['BACK:', [1513338040, 674234]],
    ['BACK:', [1513338040, 675218]],
    ['feedkeys:', [1513338040, 680711]],
    ['feedkeys:', [1513338040, 723942]],
    ['feedkeys:', [1513338040, 723991]],
    ['NOTIFY:', [1513338040, 798839]],
    ['NOTIFY:', [1513338040, 802242]],
    ['BACK:', [1513338040, 806270]],
    ['BACK:', [1513338040, 808379]],
    ['feedkeys:', [1513338040, 856461]],
    ['feedkeys:', [1513338040, 858759]]
]
```

My vim version is 8.0.1387.

**Comment by lilydjwg** [comment]
Hi Bram, with 8.0.1406 I can still reproduce the problem.

**Comment by brammool** [comment]
> Hi Bram, with 8.0.1406 I can still reproduce the problem.

Do you have a (simple) example?  Without the whole plugin.

Hmm, I guess something may put K_IGNORE into the input stream, which is
hard to detect.  We can at least check that 'updatetime' has passed.

I looked into unifying the gui_inchar() and mch_inchar() functionality,
but there are too many differences.  Especially that the GUI uses a
timeout for waiting and polling channels.

-- 
"Microsoft is like Coke.  It's a secret formula, all the money is from
distribution, and their goal is to get Coke everywhere.  Open source is like
selling water.  There are water companies like Perrier and Poland Spring, but
you're competing with something that's free."   -- Carl Howe


 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
