### ISSUE TITLE
Termdebug buttons don't work in gnome-terminal

### ISSUE THREAD

**Issue by mcepl** [vim/vim#2452]
When running ``vim -N -u NONE testing_program.c`` (with vim 8.0.1389) and start ``:Termdebug`` (after ``:packadd termdebug``, of course), I get debugger running, but I cannot press any buttons with mouse while running vim inside of gnome-terminal on RHEL-7 (``gnome-terminal-3.22.1-2.el7.x86_64`` if it matters). I have to switch to GVim (either by ``:gui`` or running gvim directly) to have buttons working.

If buttons are not supported in text-only environment, they shouldn't be shown and documentation should suggest some alternatives how to operate termdebug (are there some shortcut keys similar to the generally used in other GUI debuggers like F10 for ``:Next``, F11 for ``:Step``, etc.?).

**Comment by brammool** [comment]
Matěj Cepl wrote:

> When running ``vim -N -u NONE testing_program.c`` and start
> ``:Termdebug`` (after ``:packadd termdebug``, of course), I get
> debugger running, but I cannot press any buttons with mouse while
> running vim inside of gnome-terminal on RHEL-7
> (``gnome-terminal-3.22.1-2.el7.x86_64`` if it matters). I have to
> switch to GVim (either by ``:gui`` or running gvim directly) to have
> buttons working.
> 
> If buttons are not supported in text-only environment, they shouldn't
> be shown and documentation should suggest some alternatives how to
> operate termdebug (are there some shortcut keys similar to the
> generally used in other GUI debuggers like F10 for ``:Next``, F11 for
> ``:Step``, etc.?).

The buttons work fine in xterm.  Do you have 'mouse' set to "a"?
Can you position the cursor with a mouse click?

-- 
A meeting is an event at which the minutes are kept and the hours are lost.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mcepl** [comment]
yes, ``set mouse=a`` in ``~/.vim/vimrc`` did the trick. It might be helpful to add mention of it in the Termdebug help (or perhaps switch it on automatically when ``:Termdebug`` command is run?), because it could be the only place in the terminal vim where mouse is used.
