### ISSUE TITLE
`TextYankPost` is emitted after leaving Visual mode

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#2459]
If I start Vim with the following minimal `vimrc` (`vim -Nu /tmp/vimrc some_file`):

    augroup my_textyankpost
        au!
        au TextYankPost * call s:hl_yanked_text()
    augroup END

    fu! s:hl_yanked_text() abort
        try
            if v:event.operator != 'y'
                return
            endif

            let text = v:event.regcontents
            let type = v:event.regtype
            if type ==# 'v'
                let text = join(v:event.regcontents, "\n")
                let pat = '\%'.line('.').'l\%'.virtcol('.').'v\_.\{'.strchars(text, 1).'}'
            elseif type ==# 'V'
                let pat = '\%'.line('.').'l\_.*\%'.(line('.')+len(text)-1).'l'
            elseif type =~# "\<c-v>".'\d\+'
                let width = matchstr(type, "\<c-v>".'\zs\d\+')
                let [line, vcol] = [line('.'), virtcol('.')]
                let pat = join(map(text, {i,v -> '\%'.(line+i).'l\%'.vcol.'v.\{'.width.'}'}), '\|')
            endif

            let id = matchadd('IncSearch', pat, 0, -1)
            call timer_start(150, {-> exists('id') ? matchdelete(id) : ''})
        catch
            echohl ErrorMsg
            echom v:exception
            echohl NONE
        endtry
    endfu

And then copy some text, the latter is briefly highlighted with the highlight group `IncSearch` which is the purpose of the code. However, if I visually select some text, then press `Escape` to get back to normal mode, the selection is briefly highlighted. It seems that `TextYankPost` is emitted when you leave visual mode. I don't think it should because the help doesn't talk about leaving visual mode:

    After text has been yanked or deleted in the current buffer.

Besides, if I delete the visual selection, a region of text whose dimension matches the one of the deleted text is briefly highlighted. It shouldn't because the function responsible for the highlighting (`s:hl_yanked_text()`) begins with the following check:

    if v:event.operator != 'y'
        return
    endif

It seems to indicate that when you leave visual mode, be it by pressing `Escape` or by deleting the visual selection, `TextYankPost` is emitted and the registered operator in `v:event.operator` is `y`, while it should be `d` when you delete the visual selection.

<hr/>

Here's a [gif to illustrate](https://imgur.com/a/IiLL3).

<hr/>

Environment:

- `vim --version`:      VIM - Vi IMproved 8.0  Included patches: 1-1397
- Operating system:     Ubuntu 16.04.3 LTS
- Terminal emulator:    rxvt-unicode v9.22
- Terminal multiplexer: tmux 2.3
- `$TERM`:              screen-256color
- Shell:                zsh 5.3.1

**Comment by andymass** [comment]
Is `v:event.regname` `*` (star) in this case?

**Comment by lacygoill** [comment]
@andymass  Ah yes, you're right, `v:event.regname` is indeed `*`.

**Comment by lacygoill** [comment]
Initially, I thought it was a bug because I couldn't reproduce in Neovim `v0.2.0`, but it seems the event is emitted because by default Vim copies the visual selection in one of the two selection registers, `*`. It could be useful to implement a selection ring, for the last visually selected texts, similar to a kill ring for the last deleted texts.

For the moment, I changed the condition to test the name of the register:

        if v:event.operator != 'y' || v:event.regname ==# '*'
            return
        endif

Thank you @andymass, I'm closing the issue, since it doesn't seem to be a bug.
