### ISSUE TITLE
Echoing multiple lines in exit_cb handler not working

### ISSUE THREAD

**Issue by mhinz** [vim/vim#2463]
**Works:**

```vim
call job_start('true', {'exit_cb': {-> execute('echo "foo"', '')}})
```

This prints "foo", as expected.

**Does not work:**

```vim
call job_start('true', {'exit_cb': {-> execute('echo "foo\nbar"', '')}})
```

I'd expect this to print two lines (or at least one, the last one), but it prints _none_.

**Comment by brammool** [comment]
The echo command causes the text to scroll up.  Vim then fixes that by redrawing.  So that's working as intended.
You can either set 'cmdheight' to 2 or higher, or add a sleep to give the user a chance to read the message.

**Comment by mhinz** [comment]
Hmm, I'm not sure I understand where the redraw is coming from.

I mean, assuming the default `cmdheight=1`, `:echo "foo\nbar"` prints 2 lines followed by the obligatory `Press ENTER or type command to continue`.

Why doesn't it work the same in the exit handler (without using `:sleep`)?

**Comment by brammool** [comment]
> Hmm, I'm not sure I understand where the redraw is coming from.
> 
> I mean, assuming the default `cmdheight=1`, `:echo "foo\nbar"` prints
> 2 lines followed by the obligatory `Press ENTER or type command to
> continue`.
> 
> Why doesn't it work the same in the exit handler (without using `:sleep`)?

The "press enter" prompt is part of the normal interactive command loop.
It is not used for asynchronous messages.  These asynchronous callbacks
can be invoked any time, they are not supposed to interrupt what the
user is doing.  Vim makes sure the screen is updated, which means
messages may be cleared. If you want to make sure they show up you could
open a window to put the message in.

-- 
hundred-and-one symptoms of being an internet addict:
127. You bring your laptop and cellular phone to church.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
