### ISSUE TITLE
Feature Request: Remember window view when switching back to a buffer

### ISSUE THREAD

**Issue by Asheq** [vim/vim#2477]
### Current Behavior:

When you switch back to a buffer that you had viewed previously (e.g. with `C-^` or `:e buffer_name`), Vim will scroll the window so that the line the cursor was on previously is now at the center of the window.

I find this disorienting; it contradicts the map my brain had made of the part of the buffer I was viewing. I imagine many other people have this same struggle (perhaps without fully realizing it).

### Desired Behavior:

I would rather Vim remember exactly how I left the window and return to that position exactly. If I want to center the window, I can do it manually with `zz`.

This behavior could be set by an option like `autowinrestview` or `nocenterwindow` (like `nostartofline`).

Thanks for your consideration!

**Comment by chrisbra** [comment]
Can you reproduce with `vim --clean`?

**Comment by Asheq** [comment]
Yeah, I can reproduce the "current behavior" from above with `vim --clean`.

Vim will move the line the cursor was on previously to the center of the window, except in one case: when doing that would move the window view past the top (or bottom) edge of the buffer.

**Comment by chrisbra** [comment]
ah, can reproduce it now. Yeah, this might be disturbing. You should however be able to fix this using a custom plugin, something like this:
```viml
aug VimStartup
  au!
  au BufLeave * :let b:lastpos=winsaveview()
  au BufEnter * if exists("b:lastpos") | try | call winrestview(b:lastpos) | endtry | endif
aug END
```
(this is only a very simple demo, that IIRC needs hidden to be set) There probably already exists a similar plugin.

**Comment by Asheq** [comment]
As you predicted, there is [this VimScript](http://vim.wikia.com/wiki/Avoid_scrolling_when_switch_buffers) that attempts to add this feature. However, I've run into a couple edge cases where it doesn't work properly.

If this feature were to be built into Vim itself (and not delegated to a plugin), it would get more attention and the first-class support that I believe it deserves. Most other editors (e.g. Sublime Text), seem to have it by default. For some reason, people seem to not realize it's missing while using Vim, until it's pointed out.

What are your thoughts?

**Comment by Asheq** [comment]
I personally don't care about this anymore (I am learning to embrace the default behavior), so I am closing.
