### ISSUE TITLE
Feature request: autocmd events for terminal-mode

### ISSUE THREAD

**Issue by dfb** [vim/vim#2487]
I'm trying to have an autocmd that runs when a terminal buffer's mode changes. More specifically, I'm trying to trigger off of the mode switching to Terminal-Normal mode.

In a normal buffer I'd use InsertLeave, but that doesn't fire on terminal windows since those aren't really in insert mode in the first place, but that's essentially where I'm trying to attach my autocmd - when the terminal buffer's mode transitions from Terminal-Job to Terminal-Normal.

Please let me know if this is achievable some other way already - even a suggestion for an alternative approach or temporary workaround would be much appreciated. Thanks!

**Comment by lacygoill** [comment]
I'm not sure it will help, but on my system, `CursorMoved` [is fired](https://imgur.com/a/aC0IG) whenever I switch from Terminal-Job mode to Terminal-Normal mode, and vice-versa.

Also, `CursorMoved` is NOT fired while I'm inserting characters in Terminal-Job mode, but it IS when I move the cursor while in Terminal-Normal mode.

**Comment by lacygoill** [comment]
So, maybe you could use `term_getstatus()` to save the mode in which you were the last time `CursorMoved` was fired, and listen to the latter to compare the current mode with the last one:

<details>
    <summary>click to expand snippet</summary>

    augroup my_terminal
        au!
        au BufWinEnter * if &l:buftype ==# 'terminal'
                      \|     call s:set_terminal()
                      \| endif
    augroup END
    
    fu! s:set_terminal() abort
        augroup do_sth_when_i_enter_terminal_normal_mode
            au! * <buffer>
            au CursorMoved <buffer> call s:do_sth()
        augroup END
    endfu
    
    fu! s:do_sth() abort
        if  get(b:, 'term_last_status', '') ==# 'job'
        \&& term_getstatus(bufnr('%')) =~# 'normal'
            echom 'do stuff'
        endif
    
        let b:term_last_status =
        \       term_getstatus(bufnr('%')) =~# 'normal'
        \?          'normal'
        \:          'job'
    endfu

</details>

<hr/>

Currently, the snippet simply writes `do stuff` in Vim's messages (execute `:messages` to read them) whenever you switch from Terminal-Job mode to Terminal-Normal mode.
But you could replace `echom 'do stuff'` with whatever command / function you want to execute / invoke.

**Comment by dfb** [comment]
Ah, this will do the trick - it didn't occur to me to check CursorMoved, good call. Thanks very much for taking the time!

I'll leave it up to Bram or someone else to decide if they want to close this ticket or to at some point add specific events.

**Comment by brammool** [comment]
It is about time we have a more generic autocommand event for changing mode.  A ModeChanged event that indicates the old and the new mode would be very useful.  Better than adding a few others for Terminal mode.

**Comment by ghost** [comment]
> I'm trying to have an autocmd that runs when a terminal buffer's mode changes. More specifically, I'm trying to trigger off of the mode switching to Terminal-Normal mode.

Is this supported now? I want to call a function upon entering normal mode in a Terminal buffer. What autocmd can I use? `InsertLeave` doesn't work as mentioned by the original post.

**Comment by brammool** [comment]
> > It is about time we have a more generic autocommand event for
> > changing mode. A ModeChanged event that indicates the old and the
> > new mode would be very useful. Better than adding a few others for
> > Terminal mode.
> 
> Hi @brammool I want to implement this generic ModeChanged autocmd and
> am thinking about how to best implement this.
> Are you sure, that there should be an extra argument that tells what
> the new mode is? I was thinking about an autocmd with no arguments,
> since you can always get the current mode just by using `mode()`.

There are a few choices to make, such as when exactly the event is
triggered.  Before or after the mode is changed?  I guess after.
But to make sure anybody using the event doesn't need to know, just
passing the old and new modes avoids any trouble.

I suggest first writing detailed help for this, and look at the places
in the code where "State" is changed.  Try this:
	:vimgrep /\<State = /

I see 82 matches.  Some of them are temporary, restoring a saved state.
What should happen there?


-- 
ARTHUR:    ... and I am your king ....
OLD WOMAN: Ooooh!  I didn't know we had a king.  I thought we were an
           autonomous collective ...
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vimpostor** [comment]
>look at the places
>in the code where "State" is changed.  Try this:
>	:vimgrep /\<State = /
>
>I see 82 matches.  Some of them are temporary, restoring a saved state.
>What should happen there?

I guess in the case where vim is just internally changing the State 
temporarily and then restoring it, the ModeChanged should NOT fire, as 
the user is probably not interested in that.

Optimally ModeChanged would behave exactly like the existing mode 
autocmds (e.g. InsertEnter), just that it works in general for all 
modes.

>There are a few choices to make, such as when exactly the event is
>triggered.  Before or after the mode is changed?  I guess after.

I agree after would be best.

**Comment by vimpostor** [comment]
Hi @brammool, I have the ModeChanged autocmd working pretty nicely now. I went through all of the `:vimgrep /\<State = /` results, but most of them were just immediately restoring old_State afterwards so I could ignore them. I think I have covered all mode change cases, but it is best if someone else would go through the list as well just to be sure.

BTW it is not sufficient, to only look for State changes. For example, VIsual_active is another variable that has to be taken into account, but I think I covered all Visual mode changes too.

Another nice thing I added, is pattern matching for the ModeChanged autocmd. For example, one can do `autocmd ModeChanged n:i` to only get called when normal mode switches to insert. Or one could use `*:n` to detect mode changes to Normal mode from any other mode.

Anyways, attached is the patch. Feel free to request any changes:

[0001-Add-ModeChanged-autocmd.patch.txt](https://github.com/vim/vim/files/7114878/0001-Add-ModeChanged-autocmd.patch.txt)

You can test the patch using:
```bash
vim --clean -Nu <(cat<<EOF
set noshowmode
au ModeChanged * echomsg printf('the old mode was: "%s", the new mode is: "%s"', v:event.old_mode, v:event.new_mode)
EOF
)
```

**Comment by vimpostor** [comment]
I noticed, that I somehow have some tests failing with this patch. I will look into it and I guess I should also add a new test for the new feature as well.
I will get back to you when I am done with it.

**Comment by brammool** [comment]
Can you please create a pull request with the patch?  Then the CI will check with many different builds.

**Comment by brammool** [comment]
Small suggestion: the buffer size "4" should match between the buffer in f_mode() and last_mode.  Define a macro for that to avoid them getting out of sync.

**Comment by vimpostor** [comment]
#8999 will fix this issue.

Once merged, you can use `au ModeChanged *:nt echom printf('Switched to Terminal normal mode from "%s" mode', v:event.old_mode)`.
