### ISSUE TITLE
Characters not rendered properly with DirectX

### ISSUE THREAD

**Issue by bohrshaw** [vim/vim#2489]
Text below

    我们、我们
    我们、我们

is rendered as

![image](https://user-images.githubusercontent.com/1585463/34316622-48ad0752-e7d5-11e7-9abb-3d37c4cb1a3c.png)

after `set renderoptions=type:directx`, type `<C-l>`, and move the cursor.

Related: #1520

**Comment by mattn** [comment]
Is this fixed with `set ambiwidth=double`?

**Comment by bohrshaw** [comment]
It's fixed now(v8.1.412) even without modifying `ambiwidth`.
Previously it has rendering problem with `let &guifontwide = 'Microsoft Yahei'`.

**Comment by k-takata** [comment]
OK, closing.
