### ISSUE TITLE
Add correct 'commentstring' for *.desktop files

### ISSUE THREAD

**Issue by dtcyganok** [vim/vim#2495]
Add correct `'commentstring'` to `runtime/ftplugin/desktop.vim` accordingly [freedesktop specification](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html).
```vim
setlocal commentstring=#%s
```

**Comment by chrisbra** [comment]
have you contacted the maintainer of the file?

**Comment by dtcyganok** [comment]
The file `runtime/ftplugin/desktop.vim` doesn't  even exist.

**Comment by chrisbra** [comment]
Ah, I see. Would a file ftplugin/desktop.vim like this do it?
```viml
" Vim filetype plugin file
" Language:  Desktop Entry Specification
" URL: https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html

if exists("b:did_ftplugin")
  finish
endif
let b:did_ftplugin = 1

let s:cpo_save = &cpo
set cpo&vim

let b:undo_ftplugin = "setl cms< fo<"
setlocal commentstring=#\ %s formatoptions-=t formatoptions+=croql

let &cpo = s:cpo_save
unlet s:cpo_save
```

Would you like to become maintainer of such filetype plugin?

**Comment by dkearns** [comment]
@e-kwsm  Would you be willing to maintain this along with the syntax file?

**Comment by e-kwsm** [comment]
Opened #10788

**Comment by dkearns** [comment]
Thank you.

**Comment by brammool** [comment]
I'll include the PR.
