### ISSUE TITLE
`:copen` ignores `:leftabove`

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#2496]
To reproduce:

    $ vim -Nu NONE some_file

    :vimgrep  /./ %
    :vertical leftabove copen

I expected the quickfix window to be opened on the left, but instead Vim opens it on the right.
Without `:vertical`, the issue persists:

    :leftabove copen

Opens the quickfix window below the current one, while I expected Vim to open it above.

<hr/>

According to `:h :lefta`:

    Doesn't work for |:execute| and |:normal|.

So, I thought that maybe `:leftabove` doesn't work with `:copen`, like for `:execute` and `:normal`.
But this remark is also present in `:h :topleft` and `:h :botright`, which doesn't prevent these modifiers to work with `:copen`:

    :bo copen

Correctly opens the quickfix window at the very bottom of the screen.

    :to copen

Correctly opens the quickfix window at the very top of the screen.

<hr/>

The same issue applies for the quickfix commands `lopen`, `cwindow` and `lwindow`, as well as the modifier `:rightbelow`, and the synonyms `:aboveleft`, `:belowright`.

I searched on the issue tracker (`is:issue leftabove`, `is:issue aboveleft`, `is:issue belowright`, `is:issue rightbelow`) but couldn't find anything which seemed relevant.

<hr/>

Environment:

 - `vim --version`:      VIM - Vi IMproved 8.0  Included patches: 1-1400
 - Operating system:     Ubuntu 16.04.3 LTS
 - Terminal emulator:    rxvt-unicode v9.22
 - Terminal multiplexer: tmux 2.3
 - `$TERM`:              screen-256color
 - Shell:                zsh 5.3.1

**Comment by vim-ml** [comment]
Hi,

On Mon, Dec 25, 2017 at 7:51 AM, lacygoill <vim-dev-github@256bit.org> wrote:
> To reproduce:
>
> vim -Nu NONE some_file
> :vim /./ %
> :leftabove copen
>
> I expected the window to be opened on the left, but instead Vim opens it on
> the right.
>
> According to :h :lefta:
>
> Doesn't work for |:execute| and |:normal|.
>
> So, I thought that maybe :leftabove doesn't work with :copen, like for
> :execute and :normal.
> But this remark is also present in :h :topleft and :h :botright, which
> doesn't prevent these modifiers to work with :copen:
>
> :bo copen
>
> Opens the quickfix window at the very bottom of the screen.
>
> :to copen
>
> Opens the quickfix window at the very top of the screen.
>
> I searched on the issue tracker (is:issue leftabove, is:issue aboveleft,
> is:issue belowright, is:issue rightbelow) but couldn't find anything which
> seemed relevant.
>

I am attaching a patch to do this. But I am not sure whether this behavior is
acceptable/expected. If you open the quickfix/location window in a vertically
split window, it is hard to read the lines. As the quickfix/location windows has
long lines, from a readability perspective, it makes sense to open it always as
a horizontally split window (either at the top or at the bottom).

- Yegappan

>
> The same issue applies for the quickfix commands lopen, cwindow and lwindow,
> as well as the modifier :rightbelow, and the synonyms :aboveleft,
> :belowright.
>
> ________________________________
>
> Environment:
>
> vim --version: VIM - Vi IMproved 8.0 Included patches: 1-1400
> Operating system: Ubuntu 16.04.3 LTS
> Terminal emulator: rxvt-unicode v9.22
> Terminal multiplexer: tmux 2.3
> $TERM: screen-256color
> Shell: zsh 5.3.1
>

diff --git a/src/quickfix.c b/src/quickfix.c
index 05e594628..02808e480 100644
--- a/src/quickfix.c
+++ b/src/quickfix.c
@@ -3229,10 +3229,14 @@ ex_copen(exarg_T *eap)
 
 	if ((eap->cmdidx == CMD_copen || eap->cmdidx == CMD_cwindow)
 		&& cmdmod.split == 0)
-	    /* Create the new window at the very bottom, except when
+	    /* Create the new quickfix window at the very bottom, except when
 	     * :belowright or :aboveleft is used. */
 	    win_goto(lastwin);
-	if (win_split(height, WSP_BELOW | WSP_NEWLOC) == FAIL)
+	/* Default is to open the window below the current window */
+	if (cmdmod.split == 0)
+	    cmdmod.split = WSP_BELOW;
+	cmdmod.split |= WSP_NEWLOC;
+	if (win_split(height, cmdmod.split) == FAIL)
 	    return;		/* not enough room for window */
 	RESET_BINDING(curwin);

**Comment by lacygoill** [comment]
Thank you very much for the patch, I'm going to try and test it.

The quickfix window is really convenient to create an interactive table of contents for the current help file you're reading. Same thing for a man page (with the `man` plugin), or some documentation written in markdown.

You collect all the interesting lines: titles, headings, subheadings … 
Then you populate the location list, and you conceal the locations (filepath, line/column number), or you delete them entirely (by temporarily making the buffer modifiable), so that you only see the text. In the quickfix buffer, you can also apply the syntax highlighting of the help/man/markdown file, from which the table of contents was built.

That's what Neovim does in its [`man` plugin](https://github.com/neovim/neovim/blob/249bdb07dd3a9555972deff625d67e4ee0eddc86/runtime/autoload/man.vim#L168-L191) and [`qf` plugin](https://github.com/neovim/neovim/blob/249bdb07dd3a9555972deff625d67e4ee0eddc86/runtime/ftplugin/qf.vim#L18-L39).

And usually, in a table of contents, the lines are rather short, so opening the quickfix window in a horizontal viewport [wastes a lot of empty space](https://imgur.com/a/j0yRd). That's why I prefer to open a TOC window in a vertical viewport.

Edit:

Besides, even if we ignore the `:vertical` modifier, it would still be useful for `:copen` to respect `:leftabove` and `:rightbelow`:

 - to be consistent with how `:copen` already respects `:topleft` and `:botright`
 - to be able to punctually (i.e. without setting a global option such as `'splitbelow'`) choose a relative position for the quickfix window:

`:topleft` or `:botright` give the window an absolute position: to the very top or to the very bottom.
`:leftabove` and `:rightbelow` a relative position: just above the current one, or just below.

**Comment by lacygoill** [comment]
I have tested the patch, and it seems to work as expected. I hope it will be merged, thank you again.

**Comment by vim-ml** [comment]
Yegappan wrote:

> On Mon, Dec 25, 2017 at 7:51 AM, lacygoill <vim-dev-github@256bit.org> wrote:
> > To reproduce:
> >
> > vim -Nu NONE some_file
> > :vim /./ %
> > :leftabove copen
> >
> > I expected the window to be opened on the left, but instead Vim opens it on
> > the right.
> >
> > According to :h :lefta:
> >
> > Doesn't work for |:execute| and |:normal|.
> >
> > So, I thought that maybe :leftabove doesn't work with :copen, like for
> > :execute and :normal.
> > But this remark is also present in :h :topleft and :h :botright, which
> > doesn't prevent these modifiers to work with :copen:
> >
> > :bo copen
> >
> > Opens the quickfix window at the very bottom of the screen.
> >
> > :to copen
> >
> > Opens the quickfix window at the very top of the screen.
> >
> > I searched on the issue tracker (is:issue leftabove, is:issue aboveleft,
> > is:issue belowright, is:issue rightbelow) but couldn't find anything which
> > seemed relevant.
> >
> 
> I am attaching a patch to do this. But I am not sure whether this behavior is
> acceptable/expected. If you open the quickfix/location window in a vertically
> split window, it is hard to read the lines. As the quickfix/location windows has
> long lines, from a readability perspective, it makes sense to open it always as
> a horizontally split window (either at the top or at the bottom).

Thanks for the patch.  However, I don't think it should change
cmdmod.split, that's an unexpected side effect.  Using a local variable
would be better.

It may be strange to do a vertical split, but if the screen is very wide
it does make sense.

Would be nice to have a test.

-- 
hundred-and-one symptoms of being an internet addict:
162. You go outside and look for a brightness knob to turn down the sun.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
Hi Bram,

On Mon, Dec 25, 2017 at 2:24 PM, Bram Moolenaar <Bram@moolenaar.net> wrote:
>
> Yegappan wrote:
>
>> On Mon, Dec 25, 2017 at 7:51 AM, lacygoill <vim-dev-github@256bit.org> wrote:
>> > To reproduce:
>> >
>> > vim -Nu NONE some_file
>> > :vim /./ %
>> > :leftabove copen
>> >
>> > I expected the window to be opened on the left, but instead Vim opens it on
>> > the right.
>> >
>> > According to :h :lefta:
>> >
>> > Doesn't work for |:execute| and |:normal|.
>> >
>> > So, I thought that maybe :leftabove doesn't work with :copen, like for
>> > :execute and :normal.
>> > But this remark is also present in :h :topleft and :h :botright, which
>> > doesn't prevent these modifiers to work with :copen:
>> >
>> > :bo copen
>> >
>> > Opens the quickfix window at the very bottom of the screen.
>> >
>> > :to copen
>> >
>> > Opens the quickfix window at the very top of the screen.
>> >
>> > I searched on the issue tracker (is:issue leftabove, is:issue aboveleft,
>> > is:issue belowright, is:issue rightbelow) but couldn't find anything which
>> > seemed relevant.
>> >
>>
>> I am attaching a patch to do this. But I am not sure whether this behavior is
>> acceptable/expected. If you open the quickfix/location window in a vertically
>> split window, it is hard to read the lines. As the quickfix/location windows has
>> long lines, from a readability perspective, it makes sense to open it always as
>> a horizontally split window (either at the top or at the bottom).
>
> Thanks for the patch.  However, I don't think it should change
> cmdmod.split, that's an unexpected side effect.  Using a local variable
> would be better.
>

Agreed.

>
> It may be strange to do a vertical split, but if the screen is very wide
> it does make sense.
>
> Would be nice to have a test.
>

I am attaching an updated patch with a test.

While writing the test, I realized that currently it is not possible to get
the position of a window in the layout. It is not possible to check whether
a window is vertically or horizontally split and occupies multiple window rows
or columns.

- Yegappan

diff --git a/src/quickfix.c b/src/quickfix.c
index 05e594628..8e745213a 100644
--- a/src/quickfix.c
+++ b/src/quickfix.c
@@ -3222,6 +3222,8 @@ ex_copen(exarg_T *eap)
     }
     else
     {
+	int flags = 0;
+
 	qf_buf = qf_find_buf(qi);
 
 	/* The current window becomes the previous window afterwards. */
@@ -3229,10 +3231,14 @@ ex_copen(exarg_T *eap)
 
 	if ((eap->cmdidx == CMD_copen || eap->cmdidx == CMD_cwindow)
 		&& cmdmod.split == 0)
-	    /* Create the new window at the very bottom, except when
+	    /* Create the new quickfix window at the very bottom, except when
 	     * :belowright or :aboveleft is used. */
 	    win_goto(lastwin);
-	if (win_split(height, WSP_BELOW | WSP_NEWLOC) == FAIL)
+	/* Default is to open the window below the current window */
+	if (cmdmod.split == 0)
+	    flags = WSP_BELOW;
+	flags |= WSP_NEWLOC;
+	if (win_split(height, flags) == FAIL)
 	    return;		/* not enough room for window */
 	RESET_BINDING(curwin);
 
diff --git a/src/testdir/test_quickfix.vim b/src/testdir/test_quickfix.vim
index 0787e60e3..fb78f6983 100644
--- a/src/testdir/test_quickfix.vim
+++ b/src/testdir/test_quickfix.vim
@@ -3078,3 +3078,30 @@ func Test_lvimgrep_crash()
   augroup END
   enew | only
 endfunc
+
+" Test for the position of the quickfix and location list window
+func Test_qfwin_pos()
+  " Open two windows
+  new | only
+  new
+  cexpr ['F1:10:L10']
+  copen
+  " Quickfix window should be the bottom most window
+  call assert_equal(3, winnr())
+  close
+  " Open at the very top
+  wincmd t
+  topleft copen
+  call assert_equal(1, winnr())
+  close
+  " open left of the current window
+  wincmd t
+  below new
+  leftabove copen
+  call assert_equal(2, winnr())
+  close
+  " open right of the current window
+  rightbelow copen
+  call assert_equal(3, winnr())
+  close
+endfunc
