### ISSUE TITLE
Multibyte fonts not supported in Windows

### ISSUE THREAD

**Issue by rickywu** [vim/vim#2497]
Vim version: 8.0 1486
Windows 10: 10.0.16299.125

I set vimrc follow this issue https://github.com/vim/vim/issues/2024,  but not work
if has("win32")
    set enc=utf-8
    scriptencoding utf-8
    set fenc=chinese
    set gfn=Consolas:h12 gfw=Microsoft\ YaHei:h12
    set linespace=0

Still got error: E231: invalid 'guifontwide', how should I fix it?

**Comment by k-takata** [comment]
Vim doesn't support proportional fonts. Please use fixed width fonts.

**Comment by rickywu** [comment]
I think Microsoft Yahei is fixed width font, and I can use it in Vim 7.4

**Comment by k-takata** [comment]
Seeing the following page, it is a proportional font.
https://www.microsoft.com/typography/fonts/font.aspx?FMID=2157

> Fixed Pitch: False

**Comment by rickywu** [comment]
OK, thanks, seems need change another font.
