### ISSUE TITLE
Vim hangs by a user's mistake

### ISSUE THREAD

**Issue by stefanos82** [vim/vim#2498]
I have mistyped `vim file_a.txt > file_b.txt` in place of `cat` command and have managed to hang Vim while in terminal.

Is there any command that could terminate this operation without being forced to close or kill my terminal in order to return back to normal?

Please advice, thank you.

**Comment by vim-ml** [comment]
On Tue, Dec 26, 2017 at 03:30:44AM -0800, Στέφανος wrote:
> I have mistyped vim file_a.txt > file_b.txt in place of cat command and have
> managed to hang Vim while in terminal.
> 
> Is there any command that could terminate this operation without being forced
> to close or kill my terminal in order to return back to normal?

Type :q! and press Enter.

HTH,
Marius Gedminas
-- 
We'll show a small example here with one user calling another. (Under
international treaties describing technical papers these users must be called
"Alice" and "Bob".)
        -- Anthony Baxter

**Comment by stefanos82** [comment]
Even though Vim is not visible in terminal, your suggestion works as expected @vim-ml, cheers!

Here's a screenshot of what I see:

![image](https://user-images.githubusercontent.com/1777466/34375527-a7c6a276-eaef-11e7-9e6d-30a7528a872c.png)
