### ISSUE TITLE
Excessive spaces in the title of a quickfix window

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#2516]
- `vim --version`:      VIM - Vi IMproved 8.0  Included patches: 1-1427
 - Operating system:     Ubuntu 16.04.3 LTS
 - Terminal emulator:    rxvt-unicode v9.22
 - Terminal multiplexer: tmux 2.3
 - `$TERM`:              screen-256color
 - Shell:                zsh 5.3.1

If I start Vim with this minimal `vimrc` (written in `/tmp/vimrc`):

    filetype plugin on
    nno  cd  :lvim /./ % <bar> lopen<cr>

… and open a file:

    vim -Nu /tmp/vimrc some_file

Then, use the custom mapping by pressing `cd`, the title in the quickfix window is correctly set as:

    [Location List] :lvim /./ some_file

<hr/>

But if I change the mapping so that `:lvim` is executed from a function:

    filetype plugin on

    nno  cd  :call Func()<cr>

    fu! Func() abort
        lvim /./ %
        lopen
    endfu

Then again open some file and use the custom mapping, here's how the title in the quickfix window is set:

    [Location List] :    lvim /./ some_file
                     ^^^^

4 spaces are automatically added between the colon and the rest of the command.

<hr/>

If I change the mapping one more time, so that the command is executed from a try conditional, but outside a function:

    filetype plugin on
    nno  cd  :try <bar> lvim /./ % <bar> endtry <bar> lopen<cr>

… here's the title:

    [Location List] : lvim /./ some_file
                     ^

This time, only 1 excessive space is added.

<hr/>

If I change the mapping, so that the command is executed from a try conditional, and inside a function:

    filetype plugin on

    nno  cd  :call Func()<cr>

    fu! Func() abort
        try
            lvim /./ %
            lopen
        endtry
    endfu

Here's the title:

    [Location List] :        lvim /./ some_file
                     ^^^^^^^^

This time, 8 excessive spaces are added.

<hr/>

Finally, no matter from where `:lvim` is executed (mapping, function, `try` conditional), if it's executed by `:execute`:

    :exe 'lvim /./ %'

Then Vim doesn't add any space.

**Comment by lacygoill** [comment]
Vim seems to copy the level of indentation of the command, so it's probably not a bug.

**Comment by vim-ml** [comment]
Hi,

On Sat, Dec 30, 2017 at 10:24 PM, lacygoill <vim-dev-github@256bit.org> wrote:
> Vim seems to copy the level of indentation of the command, so it's probably
> not a bug.
>

Yes. The quickfix/location list title is set (by default) to the
command (verbatim) that
created the list. This includes the spaces before the command name.

- Yegappan
