### ISSUE TITLE
when start a job with cwd option, the error should contains more info.

### ISSUE THREAD

**Issue by wsdjeg** [vim/vim#2519]
when start a job with a cwd option, if the cwd dir does not exist, it will show:

`E475: Invalid argument: cwd`

I think the error message should be improved, at leaset should tell the user, this diretory does not exist. as I know in old version of vim, it does not support `cwd` option, maybe we should not use same error message.

**Comment by wsdjeg** [comment]
and in neovim, the error message is:

`E475: Invalid argument: expected valid directory`

**Comment by chrisbra** [comment]
Hm, get_job_options returns `e_invarg2` several times with just a minor indication of what option failed. Perhaps get_job_option should return a better error number, for with a reference to the help tag job-options.
In this particular case for an invalid `cwd` item, we already have `E150`, but that one currently points to the `:h helptags`...

**Comment by wsdjeg** [comment]
Thanks, an accurate error message will help plugin author to handle this error when using job in plugin😊

**Comment by chrisbra** [comment]
closed by https://github.com/vim/vim/releases/tag/v8.0.1516

**Comment by wsdjeg** [comment]
@chrisbra Thanks, greate work.
