### ISSUE TITLE
Feature suggestion: CmdlineChanged autocmd event

### ISSUE THREAD

**Issue by markonm** [vim/vim#2524]
It would be very useful for plugins implementing live preview for commands like `:substitute`, `:global`, `:normal`, etc. Currently such plugins must rely on abusing `timers` and `getcmdline()` features. That approach, however, has some issues.

An example of a plugin which would use `CmdlineChanged` is my [traces.vim](https://github.com/xtal8/traces.vim#example) plugin. It implements substitute preview and some more.

**Comment by lacygoill** [comment]
+1. This would also be useful to implement some mappings which emulate [readline key bindings](https://www.gnu.org/software/bash/manual/html_node/Bindable-Readline-Commands.html).
