### ISSUE TITLE
Can I use WSL as terminal on Windows

### ISSUE THREAD

**Issue by rickywu** [vim/vim#2525]
From version 8.0 it has terminal feature, so how can I use WSL as default?

**Comment by NoCheroot** [comment]
Adding this to _vimrc works for me.

```
set shell=wsl.exe
set shellpipe=|
set shellredir=>
```

Replace wsl.exe with whatever shell you want.

![image](https://user-images.githubusercontent.com/10468415/34549735-9c4d47ba-f0d0-11e7-87df-aafa9c74a8df.png)

**Comment by chrisbra** [comment]
please ask user questions at vi.stackexchange.com or the vim-use mailinglist. This is for bugs in Vim, we cannot do user support here.

**Comment by rickywu** [comment]
@NoCheroot , works well, thanks
