### ISSUE TITLE
The "-O/-o switch + :bufdo used as a +{command} + opening more than 1 file" combination produces a bug(?)

### ISSUE THREAD

**Issue by lkintact** [vim/vim#2526]
Run, for example, `gvim -O "+bufdo set nowrap" 1.txt 2.txt`
(1.txt and 2.txt are files with any contents. Same behaviour with the -o switch, any number of files >1, and, perhaps, any arguments of `bufdo`).

gVim opens two windows, both named 2.txt and displaying the contents of 2.txt. 
`:ls` shows two opened buffers, 1.txt and 2.txt.

gvim 8.0.1428 x86

**Comment by chrisbra** [comment]
that is expected, as bufdo changes the buffers displayed in the first window and stays at the last buffer. After executing the commands, it does not switch back to the buffer where it was executed.
