### ISSUE TITLE
New highlight groups introduced with the :terminal feature are not properly documented

### ISSUE THREAD

**Issue by romainl** [vim/vim#2536]
These highlight groups:

    StatusLineTerm
    StatusLineTermNC

are only mentioned in the default value of `:help 'highlight'` but:

* they are not listed in the "occasions" list under `:help 'highlight'`,
* there's no `:help hl-StatusLineTerm` or `:help hl-StatusLinetermNC`.

These highlight groups:

    debugPC
    debugBreakpoint

are only mentioned under `:help termdebug-customizing` but:

* they are not mentioned in `:help 'highlight'`,
* there's no `:help hl-debugPC` or `:help hl-debugBreakpoint`.

**Comment by brammool** [comment]
I'll add some more links
