### ISSUE TITLE
Strange characters in the `:terminal` window

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#2538]
OS: Debian 9.0
Vim: 8.0.1428
Terminal Emulator: SecureCRT 8.1.3

instruction to reproduce:

1. `:vert terminal`:

![term-bug1](https://user-images.githubusercontent.com/3035071/34727162-1034fd5c-f591-11e7-9ae4-ead4021d1cc9.png)

2. press `<c-w><c-w>` goto the left window, and press again, to the right window:

![term-bug2](https://user-images.githubusercontent.com/3035071/34727263-5faef892-f591-11e7-8ec2-a5adfcca8676.png)

**Comment by skywind3000** [comment]
see: 

```
skywind@airvm1:~$
```

became

```
skywqnd@airvm1:~$
```

**Comment by skywind3000** [comment]
and the cursor had been moved one character to the right.

**Comment by chrisbra** [comment]
I suppose you have `splitright` set? does it happen in other terminals? What about `vim --clean`?

**Comment by skywind3000** [comment]
`vim --clean` doesn't help, still wrong characters there:

```
skywind@airvm1:~$
```

became:

```
qkywind@airvm1:~$
```

**Comment by chrisbra** [comment]
... and what about other terminals?

**Comment by skywind3000** [comment]
What does "other terminals" exactly mean ?
Other terminal emulators ? mintty and putty works fine.

**Comment by chrisbra** [comment]
> Other terminal emulators ? mintty and putty works fine.

That is an important information you should mention that.

**Comment by skywind3000** [comment]
Is it a matter of cursor shaping ? SecureCRT doesn't support that.

**Comment by chrisbra** [comment]
I don't know. I just want to gather as many specific information as possible and I suspected some control codes being sent and not being correctly understood by the underlying terminal emulator. The v:termresponse value could also be of interest. That might help identify the problem and might make fixing easier. So please include all your information here.

**Comment by skywind3000** [comment]
A new incompatible terminal have been found on windows: PenguiNet

**Comment by brammool** [comment]
Please check the output of ":set termcap".  The values should match what your terminal sends and accepts.  If it's wrong, try different values for $TERM (or 'term' in Vim).

**Comment by skywind3000** [comment]
thanks very much, finally, I found three `q` in my `t_RS` and `t_SH` and then after read the help:

```text
t_RS  - request terminal cursor style
t_SH  - set cursor shape
```

I put this in my vimrc:

```VimL
set t_RS=
set t_SH=
```

and problem solved !!

By the way, my `v:termresponse` is `^[[>1;136;0c`.  according to the `help v:termresponse`, 
the terminal type `>1`  stands for something newer than vt220.
and the patch level is `136` in SecureCRT's xterm mode.

But I can't still figure out whether it is a SecureCRT's bug (gave the wrong v:termresponse value) or vim's (interpreted `^[[>1;136;0c` in a wrong way) .

**Comment by skywind3000** [comment]
Solved
