### ISSUE TITLE
Cursor in wrong position when line not fitting screen

### ISSUE THREAD

**Issue by HarmtH** [vim/vim#2540]
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 10 2018 12:20:53)
Included patches: 1-1428

```
vim --clean
:set showbreak=xx
:set number
Create a line that is longer than fits the *complete* screen
$
```
Observe that the cursor is offset by the amount of characters in showbreak. It seems that Vim doesn't expect the 'xx' to be on the first line (as is the case when the line isn't longer than fits the complete screen), although without 'number' set it does expect 'xx' to be on the first line.

**Comment by chrisbra** [comment]
Ah, I have seen this problem previously but never got around to fix it.
