### ISSUE TITLE
`getqflist({'winid':1})` returns 0 when qflist is not initialised, even if it is open.

### ISSUE THREAD

**Issue by FalacerSelene** [vim/vim#2541]
Replication in version `8.0.1428` with `-u NONE`:

```
:copen
:echo getqflist({'winid':1})
```

which returns `{'winid':0}`. I would expect it to return the ID of the newly opened window. This makes it difficult to write a function which toggles the qfwindow that also works when the qflist is not initialized.

Any command which affects the qfwindow, including `:cexpr ''` makes the above start working as expected. Alternatively, perhaps `:copen` when the qflist is uninitialised should trigger an `E776`, same as `:lopen` when the loclist is uninitialised?

**Comment by vim-ml** [comment]
Hi,

On Wed, Jan 10, 2018 at 3:45 AM, FalacerSelene
<vim-dev-github@256bit.org> wrote:
> Replication in version 8.0.1428 with -u NONE:
>
> :copen
> :echo getqflist({'winid':1})
>
> which returns {'winid':0}. I would expect it to return the ID of the newly
> opened window. This makes it difficult to write a function which toggles the
> qfwindow that also works when the qflist is not initialized.
>

Can you try the attached patch that fixes this issue?

>
> Any command which affects the qfwindow, including :cexpr '' makes the above
> start working as expected. Alternatively, perhaps :copen when the qflist is
> uninitialised should trigger an E776, same as :lopen when the loclist is
> uninitialised?
>

The differences is that the quickfix stack is always present but can be empty
but the location list stack is created only when a location list is added to the
stack.

Thanks,
Yegappan

diff --git a/src/quickfix.c b/src/quickfix.c
index 8e745213a..ff7bf7a11 100644
--- a/src/quickfix.c
+++ b/src/quickfix.c
@@ -3430,9 +3430,9 @@ qf_find_win(qf_info_T *qi)
 
     FOR_ALL_WINDOWS(win)
 	if (is_qf_win(win, qi))
-	    break;
+	    return win;
 
-    return win;
+    return NULL;
 }
 
 /*
@@ -4944,6 +4944,27 @@ qf_id2nr(qf_info_T *qi, int_u qfid)
     return -1;
 }
 
+/*
+ * Return the quickfix/location list window identifier in the current tabpage
+ */
+    static int
+qf_winid(qf_info_T *qi)
+{
+    win_T	*win;
+    int		win_id = 0;
+
+    /*
+     * The quickfix window can be opened even if the quickfix list is not set
+     * using ":copen". This is not true for location lists.
+     */
+    if (qi == NULL)
+	return 0;
+    win = qf_find_win(qi);
+    if (win != NULL)
+	win_id = win->w_id;
+    return win_id;
+}
+
 /*
  * Return quickfix/location list details (title) as a
  * dictionary. 'what' contains the details to return. If 'list_idx' is -1,
@@ -5053,7 +5074,7 @@ qf_get_properties(win_T *wp, dict_T *what, dict_T *retdict)
 	if ((status == OK) && (flags & QF_GETLIST_NR))
 	    status = dict_add_nr_str(retdict, "nr", 0L, NULL);
 	if ((status == OK) && (flags & QF_GETLIST_WINID))
-	    status = dict_add_nr_str(retdict, "winid", 0L, NULL);
+	    status = dict_add_nr_str(retdict, "winid", qf_winid(qi), NULL);
 	if ((status == OK) && (flags & QF_GETLIST_CONTEXT))
 	    status = dict_add_nr_str(retdict, "context", 0L, (char_u *)"");
 	if ((status == OK) && (flags & QF_GETLIST_ID))
@@ -5079,15 +5100,7 @@ qf_get_properties(win_T *wp, dict_T *what, dict_T *retdict)
     if ((status == OK) && (flags & QF_GETLIST_NR))
 	status = dict_add_nr_str(retdict, "nr", qf_idx + 1, NULL);
     if ((status == OK) && (flags & QF_GETLIST_WINID))
-    {
-	win_T	*win;
-	int	win_id = 0;
-
-	win = qf_find_win(qi);
-	if (win != NULL)
-	    win_id = win->w_id;
-	status = dict_add_nr_str(retdict, "winid", win_id, NULL);
-    }
+	status = dict_add_nr_str(retdict, "winid", qf_winid(qi), NULL);
     if ((status == OK) && (flags & QF_GETLIST_ITEMS))
     {
 	list_T	*l = list_alloc();

**Comment by vim-ml** [comment]
Hi,

On Wed, Jan 10, 2018 at 7:37 AM, Yegappan Lakshmanan
<yegappanl@gmail.com> wrote:
> Hi,
>
> On Wed, Jan 10, 2018 at 3:45 AM, FalacerSelene
> <vim-dev-github@256bit.org> wrote:
>> Replication in version 8.0.1428 with -u NONE:
>>
>> :copen
>> :echo getqflist({'winid':1})
>>
>> which returns {'winid':0}. I would expect it to return the ID of the newly
>> opened window. This makes it difficult to write a function which toggles the
>> qfwindow that also works when the qflist is not initialized.
>>
>
> Can you try the attached patch that fixes this issue?
>

Attaching an updated patch with a test for this.

- Yegappan

>
>>
>> Any command which affects the qfwindow, including :cexpr '' makes the above
>> start working as expected. Alternatively, perhaps :copen when the qflist is
>> uninitialised should trigger an E776, same as :lopen when the loclist is
>> uninitialised?
>>
>
> The differences is that the quickfix stack is always present but can be empty
> but the location list stack is created only when a location list is added to the
> stack.
>
> Thanks,
> Yegappan

diff --git a/src/quickfix.c b/src/quickfix.c
index 8e745213a..ff7bf7a11 100644
--- a/src/quickfix.c
+++ b/src/quickfix.c
@@ -3430,9 +3430,9 @@ qf_find_win(qf_info_T *qi)
 
     FOR_ALL_WINDOWS(win)
 	if (is_qf_win(win, qi))
-	    break;
+	    return win;
 
-    return win;
+    return NULL;
 }
 
 /*
@@ -4944,6 +4944,27 @@ qf_id2nr(qf_info_T *qi, int_u qfid)
     return -1;
 }
 
+/*
+ * Return the quickfix/location list window identifier in the current tabpage
+ */
+    static int
+qf_winid(qf_info_T *qi)
+{
+    win_T	*win;
+    int		win_id = 0;
+
+    /*
+     * The quickfix window can be opened even if the quickfix list is not set
+     * using ":copen". This is not true for location lists.
+     */
+    if (qi == NULL)
+	return 0;
+    win = qf_find_win(qi);
+    if (win != NULL)
+	win_id = win->w_id;
+    return win_id;
+}
+
 /*
  * Return quickfix/location list details (title) as a
  * dictionary. 'what' contains the details to return. If 'list_idx' is -1,
@@ -5053,7 +5074,7 @@ qf_get_properties(win_T *wp, dict_T *what, dict_T *retdict)
 	if ((status == OK) && (flags & QF_GETLIST_NR))
 	    status = dict_add_nr_str(retdict, "nr", 0L, NULL);
 	if ((status == OK) && (flags & QF_GETLIST_WINID))
-	    status = dict_add_nr_str(retdict, "winid", 0L, NULL);
+	    status = dict_add_nr_str(retdict, "winid", qf_winid(qi), NULL);
 	if ((status == OK) && (flags & QF_GETLIST_CONTEXT))
 	    status = dict_add_nr_str(retdict, "context", 0L, (char_u *)"");
 	if ((status == OK) && (flags & QF_GETLIST_ID))
@@ -5079,15 +5100,7 @@ qf_get_properties(win_T *wp, dict_T *what, dict_T *retdict)
     if ((status == OK) && (flags & QF_GETLIST_NR))
 	status = dict_add_nr_str(retdict, "nr", qf_idx + 1, NULL);
     if ((status == OK) && (flags & QF_GETLIST_WINID))
-    {
-	win_T	*win;
-	int	win_id = 0;
-
-	win = qf_find_win(qi);
-	if (win != NULL)
-	    win_id = win->w_id;
-	status = dict_add_nr_str(retdict, "winid", win_id, NULL);
-    }
+	status = dict_add_nr_str(retdict, "winid", qf_winid(qi), NULL);
     if ((status == OK) && (flags & QF_GETLIST_ITEMS))
     {
 	list_T	*l = list_alloc();
diff --git a/src/testdir/test_quickfix.vim b/src/testdir/test_quickfix.vim
index fb78f6983..71aa7d5b1 100644
--- a/src/testdir/test_quickfix.vim
+++ b/src/testdir/test_quickfix.vim
@@ -2906,6 +2906,12 @@ func Xgetlist_empty_tests(cchar)
   call assert_equal(0, g:Xgetlist({'changedtick' : 0}).changedtick)
   call assert_equal({'context' : '', 'id' : 0, 'idx' : 0, 'items' : [], 'nr' : 0, 'size' : 0, 'title' : '', 'winid' : 0, 'changedtick': 0}, g:Xgetlist({'all' : 0}))
 
+  " Quickfix window with empty stack
+  silent! Xopen
+  let qfwinid = (a:cchar == 'c') ? win_getid() : 0
+  call assert_equal(qfwinid, g:Xgetlist({'winid' : 0}).winid)
+  Xclose
+
   " Empty quickfix list
   Xexpr ""
   call assert_equal('', g:Xgetlist({'context' : 0}).context)

**Comment by FalacerSelene** [comment]
Yep, can confirm that this patch fixes the issue. Thanks!
