### ISSUE TITLE
:silent prevents BufEnter, BufNew events

### ISSUE THREAD

**Issue by justinmk** [vim/vim#2542]
To reproduce, `:source` this script:

```
autocmd BufEnter * echomsg 'BufEnter:' expand('<afile>')
autocmd BufNew * echomsg 'BufNew:' expand('<afile>')
silent edit foo1
edit foo2
```

Expected:

```
BufNew: foo1
BufEnter: foo1
BufNew: foo2
BufEnter: foo2
```

Actual:

```
BufNew: foo2
BufEnter: foo2
```

This is not mentioned at `:help :silent`. Also `:helpgrep silent.*event` finds no results.

**Comment by jamessan** [comment]
It has nothing to do with the autocmds.  `:silent` is in effect when `:echomsg` is called, so the message is suppressed.
```
autocmd BufEnter * unsilent echomsg 'BufEnter:' expand('<afile>')
```
will override an existing `:silent`, if the desire is to force the output.
