### ISSUE TITLE
X_2_COL uses floor instead of rounding

### ISSUE THREAD

**Issue by adamnovak** [vim/vim#2562]
In other GIU applications (e.g. gedit or gnome-terminal), clicking near the right edge of a character will place the (flashing vertical bar) cursor after that character.

In gvim (version 7.4.52 on Ubuntu 14.04), I observe different behavior than int he other GUI applications and terminal emulators that I have installed. Clicking anywhere within a character cell, in insert mode, will put the cursor before that character. To place the cursor after a character, you have to actually click *on* the next character.

This is resulting in frustration and mistakes, as, from my user perspective, the misbehaving cursor is not going where I am telling it to go, and is sneakily typing at the wrong place and selecting the wrong thing.

I suspect that the underlying problem is that `X_TO_COL` [here](https://github.com/vim/vim/blob/c3719bd87beca9f72d2e9f11e36d561c2c3b57b0/src/gui.h#L97) and [here](https://github.com/vim/vim/blob/c3719bd87beca9f72d2e9f11e36d561c2c3b57b0/src/gui.h#L102) is using ordinary, truncating integer division by `gui.char_width`. It should add (some fraction of) `gui.char_width` to the numerator, so that mouse positions in the later parts are mapped to the next character, so that clicks with the vertical bar mouse cursor will correctly place the flashing vertical bar cursor.

**Comment by nuko8** [comment]
> This is resulting in frustration and mistakes, as, from my user perspective, the misbehaving cursor is not going where I am telling it to go, and is sneakily typing at the wrong place and selecting the wrong thing.

As for me, placing the pointer cursor exactly at either side of a character cell of 9x9 points and then giving a click is far more time-consuming and error-prone than going straight to the target cursor position using a single or a combination of Normal mode commands (cf. `usr_03.txt`) and then pressing `i` or `a` to enter Insert mode, depending on which side of the character cell I want to start insertion from.

If a pointer device has to be used to set the cursor position, it should work in a predictable, definite  way.  With the proposed feature, you don't know exactly where the cursor appears until you actually click if you work with characters of small sizes and place the pointer cursor around the center of the character cell.

**Comment by adamnovak** [comment]
In normal mode, where you place a block cursor with an arrow, the existing rounding behavior is probably the most correct. But in insert mode it is wrong.

The target areas I am suggesting wouldn't be the very edges of the characters; I think probably each half-character would map to the nearest inter-character space. The click targets wouldn't be any smaller than they are now.

As for predictability, I don't think shifting the mouse targets makes things any less predictable. Your insert mode cursor would go to the between-character space nearest to where you clicked. You can still miss where you were intending to click, but you can do that already. 

What's there right now, at least to me, invites mis-prediction of what will happen when you click. A vertical bar mouse cursor, and a vertical bar flashing in-text cursor, communicates to the user that they are aiming for spaces between characters. But that's not what's going on behind the scenes.

For reference, here's a photograph of my screen (the only way I could get the vertical bar mouse cursor to show up) showing where I clicked and where gvim has placed the cursor. I was clearly aiming to place my insert cursor after the space, but my insert cursor has landed before the space.

![cursor](https://user-images.githubusercontent.com/5062495/35167830-bc1f4380-fd0b-11e7-8c68-289ec16221d4.png)

If the rounding behavior is to be kept as is, perhaps the vertical bar mouse cursor should not be used, as it communicates that the user is supposed to aim at the spaces between characters, rather than the characters themselves.

**Comment by brammool** [comment]
The current behavior is correct. You click on a character. not on the gap between characters.  In Insert mode the cursor goes before the character that was clicked on.  Changing this would result in complaints from all existing users.

**Comment by adamnovak** [comment]
How about turning off the use of the vertical I-beam cursor, and just using
the arrow mouse pointer all the time?
