### ISSUE TITLE
when a terminal is open and in focus, reuse file window for opening file using a remote client

### ISSUE THREAD

**Issue by damnskippy** [vim/vim#2564]
If there is 
- a terminal split open in [g]vim (via `:terminal`) , and
- the focus is in the terminal window (split), and
- a vim client issues a new file to be opened in this vim server i.e. `--servername server --remote foo.c`

vim opens a NEW split to open this file (foo.c).
Normally without terminal this behavior occurs when the in-focus terminal cannot be [re]used if it has a buffer whose contents have been modified (and have not been saved to disk).
I'm guessing this must be the case when a terminal is open too and is in focus (the above example).
So is there a way to reuse the existing split even if the focus is in terminal?
I looked to see if there is an autocommand event but couldn't quite find one.

**Comment by chrisbra** [comment]
please ask user questions on vi.stackexchange.com or use the vim_use ml. Thanks.

**Comment by damnskippy** [comment]
I didn't think of this as a question but an enhancement request.
