### ISSUE TITLE
syntax/vim.vim forces Python2 dynamic load

### ISSUE THREAD

**Issue by foxwoods369** [vim/vim#2567]
I've compiled python with python2/dyn and python3/dyn on Linux Mint 18, but if I have 'syntax on' in my .vimrc, echo has('python3') always returns false. This is due to syntax/vim.vim:712
`if g:vimsyn_embed =~# 'P' && (has("python") || has("python3")) && filereadable(s:pythonpath)`
By calling has("python") first, it will load python 2 and prevent the load of python 3.
I found this discussion regarding this line: https://groups.google.com/forum/#!topic/vim_dev/24D_9TTGkiU, and it seems the last comment discusses removing the has python checks from this file. If possible, this would allow the user to properly choose whether python2/3 loads.

**Comment by k-takata** [comment]
`has('pythonx')` can be used for this purpose instead of just removing them.

@cecamp What do you think?

**Comment by cecamp** [comment]
K.Takata wrote:
>
> |has('pythonx')| can be used for this purpose instead of just removing 
> them.
>
> @cecamp <https://github.com/cecamp> What do you think?
>
I'll guess that that sounds like the better solution.  I'll put up an 
amended syntax/vim.vim shortly -- please test it.  I'm not a python user...

Regards,
Chip Campbell

P.S.  updated syntax/vim.vim available at: 
http://www.drchip.org/astronaut/vim/index.html#SYNTAX_VIM

**Comment by chrisbra** [comment]
closing.

**Comment by brammool** [comment]
There is a more generic problem checking for Python 2 or Python 3 support without the side effect of trying to dynamically load the library.  I'll add a few values for use with has().
