### ISSUE TITLE
Dot bug with cgn: 3. not the same result as ...

### ISSUE THREAD

**Issue by MarcelBoon** [vim/vim#2575]
Start with
1,2,3,4,5

Now type /,cgn Enter Esc
Result
1
2,3,4,5

I can repeat this with the dot command, so after pressing ...
1
2
3
4
5

I expect 3. should do the same, but when doing 3. instead of ...
1
2,3,4
5

Expected behaviour:
3. is identical to ...

Using vim 8.0.1428 on Linux Mint

**Comment by chrisbra** [comment]
duplicate of #632
