### ISSUE TITLE
problem of wrap indent

### ISSUE THREAD

**Issue by CoinCheung** [vim/vim#2577]
I read some tutorials online and find the method to break a long line to display is to use wrap:
```
    set wrap
```
This works but the wrapped line have no indent. I mean if I place a tab at the start of a long line, the following wrapped line will still start from the very beginning instead of the tabbed position, like this
```
    1 a wrapped long line ......
continue of the previous line.    
    2 another line ......
```

**Comment by lacygoill** [comment]
I think you want to enable the option `'breakindent'`. It was added in [Vim 7.4.338](https://github.com/vim/vim/releases/tag/v7.4.338).

If your Vim version is higher than `7.4.338`, you could try to add in your `vimrc`:

    set breakindent

Note that this is a window-local option, so a filetype plugin could still change its value in a given buffer. In this case, you may also need to write `setlocal breakindent` in `~/.vim/after/ftplugin/{some_filetype}.vim`.

See `:help 'breakindent'` for more info.

If you have other questions on how to configure or use Vim, there's a mailing list, see `:help vim-use`. Or https://vi.stackexchange.com/.

**Comment by k-takata** [comment]
Please ask user questions on vi.stackexchange.com or use the vim_use ml. Thanks.

**Comment by CoinCheung** [comment]
@k-takata 
 Hello, I believe this I met is a issue about wrap:
When I write a combination of English and Chinese, I cannot guarantee that the line wraps at the correct position.
Since Chinese characters do not separate with spaces, the Chinese lines will be regard as a single English word, and the line will wrap between English words instead of Chinese characters, like this:
```
line 1:  These are English words, followed by a many           
            Chinese这些是中文这些是中文这些是中文这些是中文
``` 
The correct break point should be among the Chinese characters but here it is before the English word "Chinese"

Hope I made myself clear. Do you have features to fix this or is this some feature that should be added?

**Comment by lacygoill** [comment]
I'm not sure, but if there's a solution to your issue, I think it should come from setting an option. More specifically, an option from the section `4 displaying text` in the output of the `:options` command. You could try and play with `'breakindentopt'` and `'breakat'`. See `:help 'breakindentopt'` and `:help 'breakat'`. 

Unfortunately, I don't know much more.

Alternatively, you could try and format the text with the `gw` or `gq` operator. See `:help gw`, `:help gq` and `:help formatprg`.

I'm just a user, not a developer, so if you think there's an issue with how lines containing chinese characters are wrapped, and you don't find any solution with the built-in options, maybe try to open a new issue.

**Comment by CoinCheung** [comment]
@lacygoill  OK, I see, thank you so much :)
