### ISSUE TITLE
I cannot show latex math symbols

### ISSUE THREAD

**Issue by CoinCheung** [vim/vim#2578]
I am writing markdown notes and sometimes I need to insert math equations. I know there is the conceal feature, and my settings in my vimrc is:
```
set conceallevel=2
let g:tex_conceal=''
```
However, when I type in the math symbol
```
$A^{2}$
```
It was not converted to a math symbol. Was there anything wrong with my settings or my understanding of this feature?

**Comment by k-takata** [comment]
This is not a right place to ask user questions.
Please ask on vi.stackexchange.com or use the vim_use ml. Thanks.

**Comment by lacygoill** [comment]
`'conceallevel'` is a window-local option. In `~/.vim/after/latex.vim` (replace `latex` with the filetype of your file), you could try to write:

    setlocal conceallevel=2

You may also need to configure `'concealcursor'`. This option determines the modes in which the line where the cursor is may also be concealed like the others.

For example, if you want the line where the cursor is to be concealed in normal mode and command-line mode, but not in visual mode and insert mode, you would write:

    setlocal concealcursor=nc

For more information, see `:help 'conceallevel'` and `:help 'concealcursor'`.
