### ISSUE TITLE
Executing "set <M-P>=\eP" causes spurious command execution

### ISSUE THREAD

**Issue by puremourning** [vim/vim#2581]
# Issue

Under *xterm(291)*, `execut`ing `set` to map `<M-P>=\eP` causes spurious output on vim startup.

Note: This does *not* happen within, `tmux` within `xterm`.
Note: This does *not* happen within, `:terminal` within `vim --clean` within said `xterm` .

Phew. I hope that makes sense! Point being, could it be related to xterm-specific termresponse?

# Steps to reproduce

1. Create a file `test.vim`:

```
$ cat test.vim 
execute "set <M-P>=\eP"
```

NOTE: If just writing `set <M-P>=^[P`, the issue does not occur.

2. Run `vim -Nu test.vim test.vim` under xterm

# Expected behaviour

Vim starts up and no changes are made to file

# Actual behaviour

The last character in the line is replaced with `1`

# Environment

* vim 8.0.1428
* RedHat 6.5
* Xterm(291) `v:termresponse` = `^[[>41;291;0c`
* `echo $TERM` = `xterm-256color`
* `set term?` = `  term=xterm-256color`
* NOT under tmux `v:termresponse = <empty>`
* NOT under `:terminal` within vim within Xterm(291): `v:termresponse = ^[[>0;100;0c`

## Detail

```
ukfd-ltp2l(benj:MMA_main.git) users/benj>vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 23 2018 12:18:35)
Included patches: 1-1428
Compiled by benj@ukfd-ltp2l
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
+balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
+browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          +toolbar
+cindent           +insert_expand     +path_extra        +user_commands
+clientserver      +job               -perl              +vertsplit
+clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           -python            +vreplace
+conceal           +linebreak         +python3/dyn       +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       -lua               +ruby/dyn          +X11
+dialog_con_gui    +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             +xim
+digraphs          +modify_fname      +smartindent       +xpm
+dnd               +mouse             +startuptime       +xsmp_interact
-ebcdic            +mouseshape        +statusline        +xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              -mouse_gpm         +syntax            
+ex_extra          -mouse_jsbterm     +tag_binary        
+extra_search      +mouse_netterm     +tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/mma/users/benj/proj/vim/root-6.5-py3/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -fstack-protector -rdynamic -Wl,-export-dynamic  -L/usr/local/lib -Wl,--as-needed -o vim   -pthread -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lgdk_pixbuf-2.0 -lpangocairo-1.0 -lcairo -lpango-1.0 -lfreetype -lfontconfig -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lrt -lglib-2.0   -lSM -lICE -lXpm -lXt -lX11 -lSM -lICE  -lm -ltinfo -lelf -lnsl  -lselinux  -ldl           
```

In case it is relevant, .xresources:

```
#define S_base03             #002b36
#define S_base02             #073642
#define S_base01             #586e75
#define S_base00             #657b83
#define S_base0              #839496
#define S_base1              #93a1a1
#define S_base2              #eee8d5
#define S_base3              #fdf6e3

XTerm*background:            S_base03
XTerm*foreground:            S_base0
XTerm*fadeColor:             S_base03
XTerm*cursorColor:           S_base1
XTerm*pointerColorBackground:S_base01
XTerm*pointerColorForeground:S_base1

#define S_yellow             #b58900
#define S_orange             #cb4b16
#define S_red                #dc322f
#define S_magenta            #d33682
#define S_violet             #6c71c4
#define S_blue               #268bd2
#define S_cyan               #2aa198
#define S_green              #859900

!! black dark/light
XTerm*color0:                S_base02
XTerm*color8:                S_base03

!! red dark/light
XTerm*color1:                S_red
XTerm*color9:                S_orange

!! green dark/light
XTerm*color2:                S_green
XTerm*color10:               S_base01

!! yellow dark/light
XTerm*color3:                S_yellow
XTerm*color11:               S_base00

!! blue dark/light
XTerm*color4:                S_blue
XTerm*color12:               S_base0

!! magenta dark/light
XTerm*color5:                S_magenta
XTerm*color13:               S_violet

!! cyan dark/light
XTerm*color6:                S_cyan
XTerm*color14:               S_base1

!! white dark/light
XTerm*color7:                S_base2
XTerm*color15:               S_base3

XTerm*termName:              xterm-256color
XTerm*utf8:                  1
```

**Comment by puremourning** [comment]
FWIW I realise this is an old xterm patch and the bug could be in xterm itself... 

If you think so, apologies. I will try and acquire a latest xterm build via the corporate machine!

**Comment by puremourning** [comment]
Reproduced with 

```
XTerm(331)
```

**Comment by chrisbra** [comment]
> execute "set <M-P>=\eP"

That looks wrong. Please use single quotation marks.

**Comment by puremourning** [comment]
Oh man, how'd I miss that. Thanks, @chrisbra.

**Comment by puremourning** [comment]
Of course, that has the disadvantage of not working at all.

The correct, seemingly working approach is:

```
execute 'set <M-P>=^[P'
```

**Comment by puremourning** [comment]
Nope, i take it back, that doesn't work either.

**Comment by puremourning** [comment]
New test case:

```viml
execute 'set <M-P>=\eP'
nmap <M-P> :echo "Worked"<CR>
```

* vim -Nu test.vim test.vim
* press `alt-shift P`
* expect: echos "Working"
* actual: nothing is echo'd.

**Comment by puremourning** [comment]
Or even smaller, the original case, just without the execute:

```
set <M-P>=^[P
```

* vim -Nu test.vim test.vim
* actual: changes the first line unexpectedly

**Comment by brammool** [comment]
Ben Jackson wrote:

> New test case:
> 
> ```viml
> execute 'set <M-P>=\eP'
> nmap <M-P> :echo "Worked"<CR>
> ```
> 
> * vim -Nu test.vim test.vim
> * press `alt-shift P`
> * expect: echos "Working"
> * action: nothing.

Not sure how you have your xterm setup, but for me pressing shift-alt-P
produces the 0xd0 character: Ð

-- 
       We're knights of the round table
       We dance whene'er we're able
       We do routines and chorus scenes
       With footwork impeccable.
       We dine well here in Camelot
       We eat ham and jam and spam a lot.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by puremourning** [comment]
I have it set with meta-sends-escape. 

Ctrl-v lalt-shift-P prints \[P

**Comment by puremourning** [comment]
Sorry that’s escape-P.

**Comment by brammool** [comment]
Ben Jackson wrote:

> I have it set with meta-sends-escape. 
> 
> Ctrl-v lalt-shift-P prints \[P

Great, so when you map this in Insert mode, and then type <Esc> P (get
out of Insert mode and put before the cursor) you trigger the mapping.
So you found a way to disable Vim commands, wonderful!

As I mentioned, meta-sends-escape should not be used, you WILL run into
trouble.

-- 
There is a fine line between courage and foolishness.
Unfortunately, it's not a fence.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by puremourning** [comment]
Thanks for taking a look, Bram.

Sorry, I tried to keep the example as small as possible. In practice, I tweak the settings as recommended in `:help timeoutlen`:

```
		:set timeout timeoutlen=3000 ttimeoutlen=100
```

Well, strictly I use the following:

```
		:set timeout timeoutlen=1000 ttimeoutlen=10
```

Also, I haven't change the behviour of xterm in the sense that meta-sends-escape is the default behaviour of xterm as far as I can tell (at least when using UTF-8?)

I understand this stuff is tricky, and if I'm just holding it wrong, then I guess I'll just learn to hold it differently, though I'm trying to follow what it says in `:help set-termcap`:

```
This can also be used to translate a special code for a normal key.  For
example, if Alt-b produces <Esc>b, use this: >
	:set <M-b>=^[b
(the ^[ is a real <Esc> here, use CTRL-V <Esc> to enter it)
The advantage over a mapping is that it works in all situations.
```

**Comment by lacygoill** [comment]
> Note: This does not happen within, tmux within xterm.

That's probably because tmux resets `TERM` to `screen`, `tmux` or a derivative.  I think that Vim configures some internal setting (not a terminal option, I've checked) when it thinks it's running inside xterm (i.e. when `TERM` is `xterm` or a derivative) which triggers the issue.

---

The terminal key doesn't matter, you can reproduce with any one.  What matters is the sequence in the rhs; i.e. `\eP`.

---

It causes a mapping whose lhs is `q` or `<space>q` to be triggered on startup.

---

As a workaround, you can either use the modifyOtherKeys feature to avoid setting the terminal key, or empty `'t_RV'`:

    :set t_RV=

---

> FWIW I realise this is an old xterm patch and the bug could be in xterm itself...

I can reproduce on [xterm 356](https://invisible-island.net/datafiles/release/xterm.tar.gz).  It's a Vim regression introduced by [8.0.0973](https://github.com/vim/vim/commit/ce1c32780a7d0ae5110eab627fcbfd4a11e5eb52).

**Comment by lacygoill** [comment]
This is obviously not the right fix, but removing this line makes the issue disappear:

https://github.com/vim/vim/blob/e0c3c3d6cbb6f356058f28ecbdf3438411222083/src/term.c#L884

**Comment by lacygoill** [comment]
Same thing with this line:

https://github.com/vim/vim/blob/e0c3c3d6cbb6f356058f28ecbdf3438411222083/src/term.c#L4834

If you remove it, the issue disappears.

**Comment by brammool** [comment]
<Esc>P is the prefix for the terminal version escape code.  If you map it, then the rest of that escaped code will remain and be the next input.
The only solution is: Don't map that.

**Comment by lacygoill** [comment]
I see, thank you for the explanation.

IIUC, Vim sends a sequence to the terminal (the one set in `'t_RV'`) to get xterm's version.  xterm answers back with another sequence which starts with `Esc P`.  If you set a terminal key – any key – to this sequence, then, in the typeahead buffer, `Esc P` is replaced with that key which messes up the answer.  As a result, Vim wrongly interprets xterm's answer as interactive keypresses.

So, in addition to the previous workarounds (modifiyOtherKeys and `:set t_RV=`), there is a third one, which is to delay the execution of the command after the startup.  `VimEnter` doesn't seem to be always late enough (sometimes it is), but a timer can fix that:

    " the buffer is modified
    vim -Nu NONE +"pu='some text'" +'execute "set <M-P>=\eP"'

    " the buffer is *not* modified
    vim -Nu NONE +"pu='some text'" +"au VimEnter * call timer_start(500, {-> execute('exe \"set <M-P>=\eP\"')})"

**Comment by puremourning** [comment]
Maybe the TermResponse autocommand `au TermResponse * set <M-P>.....`
