### ISSUE TITLE
Very slow scroll with cursorline enabled in newer versions of Vim

### ISSUE THREAD

**Issue by manasthakur** [vim/vim#2584]
With `cursorline` enabled, the scroll performance on recent versions of Vim is really bad. The cursorline keeps jumping across lines (on let's say a continuous press of `j` or `<C-y>`). I have checked this with folding disabled, all plugins disabled, and with both the settings for `lazyredraw`. The version I am using is 8.0.1400 on macOS.

I checked with the default version provided by macOS (8.0.642) and via SSH on a Linux machine with version 7.2.411, and the issue does not exist, even with my full vimrc (excluding the content for the features that don't exist on the older versions).

**Comment by chrisbra** [comment]
can you bisect the offending plugin?

**Comment by chrisbra** [comment]
sorry, I meant, can you please bisect the offending commit?

**Comment by manasthakur** [comment]
Probably a noob question. But how should I do that? Are you suggesting me to install different versions and check?

**Comment by nuko8** [comment]
That should be easy.

First, select or create a directory in which you want to have a clone repository of Vim.  `cd` there.  Then, do
```
$ git clone https://github.com/vim/vim.git
$ cd vim
$ git bisect start
$ git good v8.0.0642
$ git bad v8.0.1400
```
This starts a bisect session.

Then, configure and build Vim as usual; test the resulting one to see if its scroll gets slow or not.  If it turns out to have the regression, then
```
$ git bisect bad
```
otherwise,
```
$ git bisect good
```
Repeat this build-and-test until git tells you which commit is offending.

For details, see https://git-scm.com/docs/user-manual.html#using-bisect  and/or `git-bisect(1)`.

**Comment by nuko8** [comment]
Oops, I made a mistake.

In the sequence of git commands, please read 
```
$ git good v8.0.0642
$ git bad v8.0.1400
```
as
```
$ git bisect good v8.0.0642
$ git bisect bad v8.0.1400
```

**Comment by manasthakur** [comment]
@nuko8 Cool!! Thanks. Had no idea this exists.

@chrisbra Sure. I will try to bisect the commit and reply back.

**Comment by manasthakur** [comment]
Hi @chrisbra!

So I have bisected the offending commit. It seems https://github.com/vim/vim/commit/c9e9c7140994154bb4a29764491d42c001b24596 (patch 8.0.1275) is the culprit.

Scroll works fine till 8.0.1274.

**Comment by chrisbra** [comment]
Hu, I wonder why that commit slows it down...

On a related note, Bram says in the todo list:
https://github.com/vim/vim/blob/218101442e8775bd1f05d1dda18d3946ee032dd1/runtime/doc/todo.txt#L288-L289

I think Bram is right there. Syntax.c contains this bit:
https://github.com/vim/vim/blob/218101442e8775bd1f05d1dda18d3946ee032dd1/src/syntax.c#L9008-L9017
(note hl_combine_attr does not cache the result), however in screen.c we use `hl_combine_attr()` quite a lot for 'cursorline', 'cursorcolumn' and the 'colorcolumn' highlighting in `win_line()`

So the original comment in syntax.c that "we expect only a few hits for `hl_combine_attr`" is no longer true when `cursorline` is set.

Unfortunately, I understand syntax.c not really well to be able to fix this.

**Comment by akaspick** [comment]
Can confirm that vim performance is really bad with cursorline set.  I'm using 8.0.1420.

**Comment by bfredl** [comment]
Regarding `hl_combine_attr`, it should be safe to memoize it with a hashtable or something, as long as this cache gets cleared in `clear_hl_tables`. I have a branch in neovim which implements this (not yet published, does a lot of other speculative changes also, but shouldn't be hard to isolate this cache) , however it relies on  khash in klib for a `(int,int) -> int` hashtable, which neovim includes as a library, and I'm not sure if including khash would be acceptable with vim c standards. But there are of course other int hashes out there.

Tough I suspect `hl_combine_attr` is not the main culprit just for `cursorline`, it seems vim internally redraws the entire window when cursor is moved, and not just the old and the new cursor line. (checked with `vim -u NONE -N`, `writedelay`, and bypassing `char_needs_redraw` with magic writedelay value). But not sure if this is related to the bisected patch above.

**Comment by Artalus** [comment]
Can confirm that the issue is still present at least up until `8.1.0022-1` in Manjaro distro. `set cursorline` or `set relativenumber` cause extreme lags during scroll, either with `j` or mouse wheel.

**Comment by Jeansen** [comment]
I can also confirm this. On Debian testing I currently have the following version installed:

VIM - Vi IMproved 8.1 (2018 May 17, compiled Jun 20 2018 02:44:05)
Included patches: 1-89

I Have to disable relativenumbers and cursorline. Either one will result in slower scrolling. Though this only happens in areas, where there is a lot to parse for syntax highlight. But without those two options enabled, everything scrolls in the same speed if I move the cursor around.

**Comment by joaqo** [comment]
I have the same issue on vim 8.1 on macOS and on Ubuntu. Temporarily disabled relative numbers to make vim useable.

**Comment by ghost** [comment]
I have the same issues -- whenever I open a C file with Doxygen as c.doxygen (so that I get highlighting) and have relativenumber est, one of the CPU cores goes up to 100% and vim starts freezing while others stay at ~10%. Doing the same in neovim doesn't produce the lag, and 3 out of 4 cores go up to 40-50%. So, maybe it is a design issue, and it would be possible to rebalance the load from a single core to others?

Tried with:
```
curl http://fnch.users.sourceforge.net/data/doxygen_c/doxygen_c.h > header.h && curl https://ptpb.pw/z_9t > myvimrc && vim -u myvimrc header.h
```

Where vimrc is (in case ptpb shuts down tomorrow):
```
set nocompatible
filetype plugin indent on
syntax enable
set relativenumber
augroup vimrc
	autocmd!
	autocmd BufRead *.h set ft=c.doxygen
augroup END
```

Disable relativenumber -- and it works okay-ish again.

**Comment by rubyDoomsday** [comment]
I am also seeing this issue with vim 8.1 installed with hombrew. Disabling `relativenumber` allows the buffer to scroll at normal speed. As a quick (lazy) fix, I rolled back to vim version 7.4, and do not see the same issue.

**Comment by aunu53** [comment]
+1

**Comment by brammool** [comment]
Patch  8.0.1275 is very simple and has nothing to do with redrawing.  Did someone double-check that this would be the patch that causes the problem?

When I try myself, with 'cursorline' and 'relativenumber' set in src/main.c, everything updates quickly.
Does the problem only happen in some file types perhaps?

**Comment by Jeansen** [comment]
Hm...interesting. It really seems to be only slow in some file types. src/main.c works like a charm with my current setup. CPU almost not used. Using Perl is another thing. The file I am currently working in the most and where I simply have to do the workaround mentioned above is here: https://github.com/Jeansen/cdmn/blob/develop/cdmn

Though I must say I also had this problem without any plugins activated. That's actually why I thought it is related to vim in the first place and not any plugin.

@brammool: Would you mind having a look for yourself?

**Comment by chrisbra** [comment]
Please try to come up with a reproducible example using `vim --clean`. It might be simply because the syntax rules are too expensive, so please also test with syntax highlighting turned off. You might want to show the syntime report (see `:h :syntime`) just to make sure and be able to tell, which syntax rules affects this. You might also want to check or adjust your 'redrawtime' setting.

**Comment by Jeansen** [comment]
@chrisbra OK, I will do some tests and report back here.

**Comment by chrisbra** [comment]
Please check with https://github.com/vim/vim/commit/90a997987dbbe43af3c15118a35f658f0f037d1d

**Comment by joshdick** [comment]
I had this issue inside iTerm2 on macOS, but 90a9979 solves it for me. Awesome!

**Comment by Jeansen** [comment]
Works like a charm ................. :-) without changing my setup.

**Comment by chrisbra** [comment]
there were a couple of following commits fixing relativenumber and cursorline performance problems. So let me close this now.
