### ISSUE TITLE
Term vertical split

### ISSUE THREAD

**Issue by vitaly-zdanevich** [vim/vim#2586]
Now it is possible to make only horizontal term, but on usual wide display it usually looks non-efficient:
<img width="961" alt="screen shot 2018-01-27 at 12 16 21 pm" src="https://user-images.githubusercontent.com/3514015/35470522-2ad6d97c-035c-11e8-8930-e7cf6e3467b3.png">

**Comment by chrisbra** [comment]
I am not sure what exactly you want from this issue fixed. That is working as expected. If you want a smaller window, you need to first create your desired window layout.

**Comment by vitaly-zdanevich** [comment]
This is the future request - will be nice to have `vterm`.

**Comment by manasthakur** [comment]
You can have a terminal open in a vertical split as well by creating a split and then entering into a terminal that occupies the full window. I use a map that executes the following:
```vim
:vsplit | term ++curwin
```

**Comment by chrisbra** [comment]
Use `:vert :term` 
You can define your own command abbreviation if you really need this. There is no need for a general command like this.

**Comment by vitaly-zdanevich** [comment]
Oh, thank you! But now in the documentation:

`...there is no vertical split, the Vim window width is used.`

Maybe it is worth to add `:vert :term` to the documentation?

**Comment by mgedmin** [comment]
The full text is:

                        Two comma separated numbers are used as "rows,cols".                                                                          
                        E.g. :24,80gdb opens a terminal with 24 rows and 80                                                                           
                        columns.  However, if the terminal window spans the                                                                           
                        Vim window with, there is no vertical split, the Vim                                                                          
                        window width is used.                                                                                                         

I think it's trying to say that if you create an 80-column terminal inside a vim window wider than 80 columns, vim will not implicitly create a vertical split there.  Instead the extra space to the right will remain unused.

However the `:<rows>,<cols>term` syntax no longer works for specifying terminal size -- ranges are now used for feeding input.  I think this paragraph ought to be removed.

**Comment by mgedmin** [comment]
> I think it's trying to say that if you create an 80-column terminal inside a vim window wider than 80 columns, vim will not implicitly create a vertical split there. Instead the extra space to the right will remain unused.

I was wrong.

What actually happens, the requested terminal width (`:term ++cols=NN`) will be ignored if you don't have any preexisting vertical splits.  And if you do have vertical splits, what `:term ++cols=NN` does is resize the split to NN before launching the terminal.  It's as if you manually do a `:wincmd NN|` before the `:term`.
