### ISSUE TITLE
Test failure on macOS 10.13.3

### ISSUE THREAD

**Issue by chdiza** [vim/vim#2590]
```
Found errors in Test_filetype_detection():
function RunTheTest[38]..Test_filetype_detection[2]..CheckItems line 9: with file name: file.lpc: Expected 'pike' but got 'lpc'
function RunTheTest[38]..Test_filetype_detection[2]..CheckItems line 9: with file name: file.ulpc: Expected 'pike' but got 'lpc'


From test_alot.vim:
Found errors in Test_filetype_detection():
function RunTheTest[38]..Test_filetype_detection[2]..CheckItems line 9: with file name: file.lpc: Expected 'pike' but got 'lpc'
function RunTheTest[38]..Test_filetype_detection[2]..CheckItems line 9: with file name: file.ulpc: Expected 'pike' but got 'lpc'

Test results:


From test_alot.vim:
Found errors in Test_filetype_detection():
function RunTheTest[38]..Test_filetype_detection[2]..CheckItems line 9: with file name: file.lpc: Expected 'pike' but got 'lpc'
function RunTheTest[38]..Test_filetype_detection[2]..CheckItems line 9: with file name: file.ulpc: Expected 'pike' but got 'lpc'
TEST FAILURE
make[2]: *** [report] Error 1
make[1]: *** [scripttests] Error 2
make: *** [test] Error 2
```

**Comment by nuko8** [comment]
The failure itself is not specific to macOS and found in Linux and Windows as well.

That has already been known through the CI tests against the latest runtime update via the commit 40962ec9c:

https://travis-ci.org/vim/vim/builds/334483473
https://ci.appveyor.com/project/chrisbra/vim/build/4815

**Comment by brammool** [comment]
Kazunobu Kuriyama wrote:

> The failure itself is not specific to macOS and found in Linux and
> Windows as well.
> 
> That has already been known through the CI tests against the latest
> runtime update via the commit 40962ec9c:
> 
> https://travis-ci.org/vim/vim/builds/334483473
> https://ci.appveyor.com/project/chrisbra/vim/build/4815

Should be fixed now.

-- 
hundred-and-one symptoms of being an internet addict:
271. You collect hilarious signatures from all 250 mailing lists you
     are subscribed to.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
