### ISSUE TITLE
xxd -o truncated to 32 bits

### ISSUE THREAD

**Issue by rlipscombe** [vim/vim#2592]
If I use the following command (I'm running xxd from inside a gdb user command)...

    xxd -o 0x7f6f940008a8 /tmp/dump.bin

...I get the following output...

    940008a8: 0000 0000 0000 0000 0000 0000 0000 0000  ................

...etc.

It appears that the `-o` switch is truncated to 32 bits.

**Comment by k-takata** [comment]
This should be fixed in 8.1.0854: https://github.com/vim/vim/commit/d8c56a0d29ccb53e12c6dec73b9a0e8a6dad99c2.
