### ISSUE TITLE
Allow relative number when lines wrap

### ISSUE THREAD

**Issue by chiguiredev** [vim/vim#2593]
![vim_problem](https://user-images.githubusercontent.com/17623118/35547899-5cc94d6e-0552-11e8-9dde-30dbeac3ac80.png)

**Comment by chiguiredev** [comment]
I research it and it seems that there is no sane way to fix this.

**Comment by ZyX-I** [comment]
The issue is very vague. `&relativenumber` has a set semantics referring to specific linewise motions, it will break when fixing this case and you did not define new one.

**Comment by chrisbra** [comment]
what exactly would you like to see there instead? Also have a look at ['cpo-n'](http://vimhelp.appspot.com/options.txt.html#cpo-n)

**Comment by chrisbra** [comment]
no further information, closing then.
