### ISSUE TITLE
Concealed text causes vim to wrap before window width

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vim/vim#260]
```
What steps will reproduce the problem?
1. Execute ":setlocal conceallevel=3 concealcursor=nvic |syn match Foo conceal 
'^....................'".
2. Make vim window narrow, say ~40 columns.
3. Type "The quick brown fox jumps over the lazy dog." twice.

What is the expected output? What do you see instead?
Vim should not wrap the line until the visible text actually reaches the edge 
of the window, but it wraps apparently 20 columns before the edge, as if the 
concealed characters still contribute to the effective length.

What version of the product are you using? On what operating system?
vim 7.4.430 on Ubuntu Linux 14.04
```

Original issue reported on code.google.com by `dbarn...@google.com` on 22 Sep 2014 at 6:41

**Comment by nhooyr** [comment]
What about when `concealcursor=nvic`? Then it should only wrap on what is visible.

edit: whoops, didn't see `concealcursor=nvic` in the original post.

**Comment by nhooyr** [comment]
Also, horizontal scrolling doesn't scroll on only visible text.

**Comment by louwers** [comment]
@nhooyr It should, but it's not the case.

**Comment by nhooyr** [comment]
@louwers in the original post, the person has `concealcursor=nvic` set though?

**Comment by louwers** [comment]
@nhooyr Yes, so for that setting it's incorrect that it would create a wobbling effect or that it would be slow. However, there's still the issue of it being a lot of work to implement.

Are you working on a patch? Personally I think it would be worth it, because without correct wrapping the conceal feature has little use, at least to me.

**Comment by ao2** [comment]
And as mentioned by @brammool in https://groups.google.com/forum/#!topic/vim_dev/ZQTXsL4Tdyg on lines where there is some concealed text, positioning the cursor with the mouse also fails.

As aside effect of these bugs the AnsiEsc plugin which uses `conceal` to hide the ANSI escape sequences is not that useful either.

**Comment by henrebotha** [comment]
I know this is wontfix, but I would like to add my 2c that it be reconsidered. My use case: I write notes in markdown syntax, using [this plugin](https://github.com/plasticboy/vim-markdown) for syntax highlighting. The plugin helpfully defines conceals for URL patterns (like `[this](https://github.com/vim/vim/issues/260)`).

I'd like my notes to remain reasonably readable. With long URLs, it becomes a challenge. The "correct" answer here is `set conceallevel` > 0; however, due to also using `set wrap`, this completely breaks the flow of reading. I may as well not use `conceal` at all.

The behaviour I think anyone would expect is that wrapping happens based on visible characters only.

If we can map out what all needs to be done to implement this change, I'd be willing to help.

**Comment by ihadgraft** [comment]
For pages that contain reference information or a solution (most of my cases) I do this:

- Create a new page in vimwiki
- On the new page, I paste relevant content from the URL, add a summary, metadata, annotations, the source URL, and whatever else is useful

A quick way I've come up with to get nicely-formatted, easily "yankable" content from a URL is to use [Pandoc](https://pandoc.org) and pipe the output right into vim: 

```shell
$ pandoc -o - -t markdown ${SOME_URL} | vim - 
```
Creating my own page is a bit more up-front work but has a couple of nice advantages:

- The reference / solution itself is searchable in the wiki
- I often don't have to deal with a browser on repeat visits if I've done a good job capturing the critical information.
- Links in the wiki are far easier to deal with

If there are cases where this solution wouldn't work or would be annoying, I might use a URL shortener.  But I'm finding that most things I need to link to directly every time are site home pages or maybe one level deep, so they aren't causing issues to begin with.

**Comment by kflu** [comment]
> I know this is wontfix, but I would like to add my 2c that it be reconsidered. My use case: I write notes in markdown syntax, using [this plugin](https://github.com/plasticboy/vim-markdown) for syntax highlighting. The plugin helpfully defines conceals for URL patterns (like `[this](https://github.com/vim/vim/issues/260)`).
> 
> I'd like my notes to remain reasonably readable. With long URLs, it becomes a challenge. The "correct" answer here is `set conceallevel` > 0; however, due to also using `set wrap`, this completely breaks the flow of reading. I may as well not use `conceal` at all.
> 
> The behaviour I think anyone would expect is that wrapping happens based on visible characters only.
> 
> If we can map out what all needs to be done to implement this change, I'd be willing to help.


I want to make the same point as this comment, but mainly using the below screenshots to give an idea:

![image](https://user-images.githubusercontent.com/1031978/130737173-42425271-be36-4eff-af0a-02a369d6819f.png)

![image](https://user-images.githubusercontent.com/1031978/130737193-92844abc-4372-4989-b941-7806a10ef3cc.png)

**Comment by mtwebb** [comment]
+1 to this.   The visual example above is great, and there are many other use cases this would enable (hide footnotes, or notes to self in long prose work, hide commented out code).

**Comment by tusktenon** [comment]
Another vote for fixing this issue. I love Vim and use it for almost everything, but I still find myself using Emacs for Markdown and Org files. The ability to conceal links and still have properly wrapped lines is a huge advantage; I almost never need to bother with a separate viewer application.

**Comment by hneutr** [comment]
Adding a vote for a fix to this issue — seems clear to me this isn't desirable behavior.

**Comment by flechtwerkflechtwerk** [comment]
I'd also love this to be reconsidered. I use comments in Markdown a lot and would like to conceal them, but it truly messes up my lines.

**Comment by WhiteBlackGoose** [comment]
Bump

**Comment by ychin** [comment]
Just something random I have been dealing with: conceal also affects hard tab character positioning. In fact, if you read Vim documentation, it makes liberal uses of hard tabs and the alignment of the docs assume that conceal characters still count towards the hard tabs (in fact vimhelp.org only recently fixed this issue to make the online documentation look correct alignment-wise https://github.com/c4rlo/vimhelp/pull/23). So if we fix this this probably need to be a toggleable option unless we fix up all the docs (and not sure if others rely on this as well).

**Comment by mostafatouny** [comment]
I hope the community fixes this someday. My simple workaround would be `vim.opt.breakat = " "` so that reading flow is maintained.

<img width="1917" height="101" alt="Image" src="https://github.com/user-attachments/assets/a511fc92-70d6-4ba1-9c6c-e77a6d3ba81d" />
