### ISSUE TITLE
[8.0.1440] Test_terminal_response_to_control_sequence fails on Manjaro/Arch (with custom/different shell prompt?)

### ISSUE THREAD

**Issue by jonathonf** [vim/vim#2607]
## What happens
Compiling Vim version 8.0.1440 (and onwards) on [Manjaro](https://manjaro.org) ([Arch](https://archlinux.org)-like) fails.

## Suppositions

I thought this may have been down to having a shell prompt that's not `sh-4.4$`, but setting this manually to what might be the "expected" value doesn't appear to make a difference.

This happens with Zsh and Bash, and in Alacritty, Kitty, and Terminator, so doesn't appear to be shell- or terminal-dependent.

### Probably not related, but what's the shell prompt?
`PS1='[\u@\h \W]\$ '`

(See also e.g. https://git.archlinux.org/svntogit/packages.git/tree/trunk/system.bashrc?h=packages/bash)

```
root@box:~#
user@box:~$
```

## How to replicate
Build [Vim](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/vim) in Manjaro, whether the "normal" OS, a clean chroot, or a [build container](https://github.com/jonathonf/manjaro-build).

(_Or (possibly), set `PS1=` to something other than `sh-4.4$`, e.g._

```
export PS1='[\u@\h \W]\$ '
make -j1 test
```
_though I can't verify this on an otherwise-working system..._)

## What the error says
```
From test_terminal.vim:
Found errors in Test_terminal_response_to_control_sequence():
function RunTheTest[38]..Test_terminal_response_to_control_sequence line 13: Pattern ';\\d\\+R' does not match 'sh-4.4$ 1R'

Test results:


From test_terminal.vim:
Found errors in Test_terminal_response_to_control_sequence():
function RunTheTest[38]..Test_terminal_response_to_control_sequence line 13: Pattern ';\\d\\+R' does not match 'sh-4.4$ 1R'
TEST FAILURE
```

## Which bit of code might be involved
https://github.com/vim/vim/commit/b50773c6df0bc2c9c2ab1afecc78083abc606de0#diff-2a55be1a8b4cf82648a1b8ea487aca49

**Comment by jamessan** [comment]
That test is failing in all of Debian's builds, too, although a little differently.

```
Found errors in Test_terminal_response_to_control_sequence():
function RunTheTest[38]..Test_terminal_response_to_control_sequence line 13: Pattern ';\\d\\+R' does not match 'sh: 1: -c: not found'
```

Oddly, I didn't see it in any of the builds I did locally.

**Comment by brammool** [comment]
James McCoy wrote:

> That test is failing in all of Debian's builds, too, although a little
> differently.
> 
> ```
> Found errors in Test_terminal_response_to_control_sequence():
> function RunTheTest[38]..Test_terminal_response_to_control_sequence line 13: Pattern ';\\d\\+R' does not match 'sh: 1: -c: not found'
> ```
> 
> Oddly, I didn't see it in any of the builds I did locally.

I can reproduce it on a Linux machine.  Somehow the ";" before "1R" goes
missing.  And it's a bit slow, a sleep is needed.

-- 
Linux is just like a wigwam: no Windows, no Gates and an Apache inside.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by jonathonf** [comment]
Just confirming fixed. :+1:
