### ISSUE TITLE
vim won't display utf-8 characters

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vim/vim#261]
```
What steps will reproduce the problem?
1. set showbreak=↪ " character show when wrapping line
2.
3.

What is the expected output? What do you see instead?
Previously i see the "↪" escape character normally, now (since update i 
believe) I get error "E595: contains unprintable or wide character: 
showbreak=â~Fª"

What version of the product are you using? On what operating system?
Version 7.4. Arch Linux Operating System

Please provide any additional information below.
```

Original issue reported on code.google.com by `JorgeCha...@gmail.com` on 26 Sep 2014 at 6:40

**Comment by dapi** [comment]
The same thing. I think it is something in environment.

**Comment by sbwtw** [comment]
Same problem on Windows 64 Bit, Vim 8.1.1

**Comment by tonymec** [comment]
* I don't see an answer to @chrisbra 's comment asking for the full output of `:version`
* What is `'encoding'` set to?
* If you set `'encoding'` in your vimrc, the `:set showbreak=↪` statement should be placed afterwards.
* If your vimrc is in UTF-8 it should contain a `:scriptencoding utf-8` statement near the top to avoid misunderstandings.

Best regards,
Tony.

**Comment by chrisbra** [comment]
also Terminal or Gui version?
