### ISSUE TITLE
E492: Not an editor command

### ISSUE THREAD

**Issue by user67x** [vim/vim#2610]
Hello!

I have installed the PPA for having the latest Vim v8 for Xenial. I have follow this little tutorial: http://tipsonubuntu.com/2016/09/13/vim-8-0-released-install-ubuntu-16-04/
vim -version : 
`VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb  1 2018 14:53:29)`

When I try to reindente a opened css file, by enter this command : `gg=G`, I have this error: `E492: Not an editor command
`
I have try to deinstall the latest Vim by removing the PPA, but the error is still here.

I have try to remove spf13-vim too, and reinstall, but the problem is still here.

Someone can help, please?

//EDIT : 

apt-cache policy vim
vim:
  Installed: 2:8.0.1451-0york1~16.04
  Candidate: 2:8.0.1451-0york1~16.04
  Version table:
 *** 2:8.0.1451-0york1~16.04 500
        500 http://ppa.launchpad.net/jonathonf/vim/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     2:7.4.1689-3ubuntu1.2 500
        500 http://fr.archive.ubuntu.com/ubuntu xenial-security/main amd64 Packages
        500 http://fr.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
     2:7.4.1689-3ubuntu1 500
        500 http://fr.archive.ubuntu.com/ubuntu xenial/main amd64 Packages

**Comment by k-takata** [comment]
Please try with `vim --clean` to check if it is caused by your settings or plugins.

**Comment by tyru** [comment]
> E492: Not an editor command

Please type `gg=G` in normal mode, not command-line mode.
You can learn Vim basic operations from `vimtutor` command (you can invoke the command from your shell if you installed `vim`).

**Comment by user67x** [comment]
Oh sorry. You have right!

Thanks a lot! Have a nice day
