### ISSUE TITLE
mac build with ./config --with-features=huge but conceal feature unabled

### ISSUE THREAD

**Issue by playwolsey** [vim/vim#2621]
mac os high sieera ,version:10.13.3 (17D47) , vim version 8.0
build with ./config  --with-features=huge --enable-conceal not work

type 'vim --version | grep conceal'  shows -conceal

help

sorry I typed wrong, it's './config  --with-features=huge' not work

**Comment by chdiza** [comment]
Why are you passing `--enable-conceal`?  That will come automatically with a `huge` build.

**Comment by vim-ml** [comment]
2018-02-07 16:03 GMT+03:00 chdiza <vim-dev-github@256bit.org>:
> Why are you passing --enable-conceal? That will come automatically with a
> huge build.

That still should not harm, if it does this is a bug. Except that
`--with-feature` is not a valid variant AFAIK; at least my build
scripts do use plural form and same uses `--help`.

**Comment by chdiza** [comment]
Right, it should still work (provided it's `--with-features=huge` and not `--with-feature=huge`).  But since it's unnecessary, the OP has an awfully easy workaround!

**Comment by playwolsey** [comment]
@vim-ml  sorry I typed wrong, it's './config --with-features=huge' not work  , I use tab to complete command

**Comment by chdiza** [comment]
On vim 8.0.1475, `--enable-conceal` causes `configure` to bomb out with an error:
```
configure: WARNING: unrecognized options: --enable-conceal
```
I checked out 8.0.0054, and the `./configure --help` there doesn't mention --enable-conceal at all.  I'm not sure if it was ever a legitimate configure flag.  Even if it was, it is not now.  Just stop passing it.

**Comment by playwolsey** [comment]
@chdiza i removed --enable-conceal, not work too

**Comment by k-takata** [comment]
> type 'vim --version | grep conceal' shows -conceal

Did you do this after installing your self-compiled Vim?
If not, you should type `./vim` instead of `vim`.

**Comment by nuko8** [comment]
@playwolsey 

Building Vim on macOS is fairly straightforward:
```
$ mkdir -p ~/Documents/src
$ cd ~/Documents/src
$ git clone https://github.com/vim/vim.git
$ cd vim/src
$ make
```
This will run `configure` automatically and build a Vim having the default feature set (='huge').

To see if the conceal feature is included or not in the resulting Vim, try this, staying in the same directory that you built Vim:
```
$ VIMRUNTIME=../runtime ./vim --version | grep conceal
```
or,
```
$ sudo make install
$ PATH=/usr/local/bin:$PATH vim --version | grep conceal
```
Note that the conceal feature is to be included unconditionally when Vim is configured with a feature set equal to or bigger than 'big'; there's no way to add/remove the feature via command-line.

Accordingly,

> mac build with ./config --with-features=huge but conceal feature unabled 

should never happen.

**Comment by playwolsey** [comment]
@nuko8 thx. it's worked.
