### ISSUE TITLE
Syntax highlighting for CSS3 feature queries

### ISSUE THREAD

**Issue by PurpleVsGreen** [vim/vim#2623]
When using syntax highlighting for CSS, any ``@supports`` rule and its block of statements should be highlighted similarly to those of media queries. ([CSS Conditional Rules Module Level 3](https://www.w3.org/TR/css3-conditional/) specifies these queries.)

For example:
```
@supports (-webkit-perspective: 20px) and (not (perspective: 20px)) and (not (display: grid)) {
  /* CSS declarations for this condition */
}
```

**Comment by PurpleVsGreen** [comment]
Notifying @JulesWang as per #1705

**Comment by JulesWang** [comment]
Pls review PR #2637

**Comment by chrisbra** [comment]
PR has been included, closing
