### ISSUE TITLE
make sudo fails at macos using iterm2

### ISSUE THREAD

**Issue by kafeltz** [vim/vim#2625]
I have just git pulled the lastest (patch 8.0.1479) version of vim and today `make install` is failing.

> evalfunc.c:7980:15: error: use of undeclared identifier 'ctrl_x_mode'; did you mean 'cur_tmode'?
>             else if (ctrl_x_mode == 1)
>                      ^~~~~~~~~~~
>                      cur_tmode
> ./globals.h:1049:12: note: 'cur_tmode' declared here
> EXTERN int      cur_tmode INIT(= TMODE_COOK);   /* input terminal mode */
>                 ^
> 1 error generated.
> make[1]: *** [objects/evalfunc.o] Error 1
> make: *** [first] Error 2

The last vim workings compiling is:

> VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb  2 2018 09:36:44)
> macOS version

**Im using MACOS Sierra 10.12.6**

**Comment by nuko8** [comment]
The failure is due to [v8.0.1479](https://github.com/vim/vim/commit/bc0e9adae9c253f36803665180e4b576d1e725ab) and has already been fixed via [v8.0.1480](https://github.com/vim/vim/commit/0562532c2eee6205d225aa1dc7e3e89af0dfd990).

The issue itself is not specific to macOS.

**Comment by kafeltz** [comment]
You're right. It did work, thx.
