### ISSUE TITLE
how move buffer vim the position 4 to 2

### ISSUE THREAD

**Issue by cirelramos** [vim/vim#2635]
I want know how to move a buffer in the position 4 to position 2.
How can do it?
if vim can't do it, you will maybe can add it option?

**Comment by ZyX-I** [comment]
What is the buffer “position” and why do you need this feature?

If by “position” you meant “buffer number” then this is not going to ever happen, buffer number persistence is an essential feature for plugins (some caches, buffer switch/switch back functionality, etc) and for C code as well (e.g. numbers in global marks). You can do some switching by using `:file` command (save buffer contents, buffer options and buffer variables, rename buffer 4 to temporary name, rename buffer 2 to former buffer’s 4 name, rename buffer 4 to former buffer’s 2 name, then restore contents, options and variables), but this is extremely tricky and described sequence may confuse plugins and/or core code: e.g. such switching will make global mark A point to another file as a result (as global marks point to buffers and not files if corresponding files are loaded into buffers).

**Comment by ZyX-I** [comment]
Ah, and if buffer 2 was already closed then buffer number 2 is no longer available.

**Comment by cirelramos** [comment]
well now i see, i am new with vim and i was think it would easy move the buffer for order as i want.

thanks for the help

the tabs can move or order?

**Comment by tonymec** [comment]
``:help :tabmove``

Best regards,
Tony.

**Comment by ZyX-I** [comment]
Using tabs in one-tab-per-buffer manner is like using virtual desktops in one-desktop-per-window manner. Possible, but it is neither what they are designed for nor what commands that switch buffers are going to respect. It is better to install something like denite/command-t/ctrlp and switch buffers by typing something like `{mappingInvokingPluginCommand}smallPartOfTheBufferName<CR>` (e.g. I can switch to `eval.c` using Command-T and typing `,bev<CR>` (`,t` is my custom mapping for `:CommandTBuffer<CR>`)). With buffer switcher plugins you would not need to care about buffer order.

**Comment by chrisbra** [comment]
please ask user questions on the vim-use mailinglist or vi.stackexchange.com. This is for actual bugreports of Vim. Closing.
