### ISSUE TITLE
popupmenu is show in the wrong place

### ISSUE THREAD

**Issue by prabirshrestha** [vim/vim#2640]
I have noticed that recently popup menu sometimes shows up in the wrong place.

![image](https://user-images.githubusercontent.com/287744/36111888-8a4c233a-0fdc-11e8-8363-5a8efd8c75c0.png)

**Comment by brammool** [comment]
I already suspected patch 8.0.1491 would cause a problem.
How can this be reproduced?  Having this in the form of a simple test would help a lot.

**Comment by skywind3000** [comment]
![bad_position](https://user-images.githubusercontent.com/3035071/36238669-0acd2d92-123f-11e8-97fc-ccecb1f4cbff.png)

I have encountered the same issue. when I'm editing on the right split with YCM, the complition popup displays on left. But when I'm editing on the left, it seems no problem.

**Comment by davits** [comment]
Hi Bram,
Here is the simple way to reproduce:
![Bug](https://files.gitter.im/Valloric/ycmd/AdXH/vim_bug.png)
Vim window size is 80x24, pressed Ctrl+n.

The newly added logic is responsible: https://github.com/vim/vim/blob/master/src/popupmnu.c#L245-L301

**Comment by bstaletic** [comment]
For those who prefer a text based minimal reproducer:

File contents:

```
very_very_very_long_line_lets_repeat_this_again_just_to_make_sure_very_very_very_long_line
foo
bar
```
- The file in vim.
- Open an empty line.
- Move the cursor far enough to the right so that the long line can't fit between cursor and the right edge of the buffer.
- `<C-n>`

**Comment by h-east** [comment]
Could you please confirm this patch?
https://gist.github.com/h-east/988fec74d24724662a51234b898ac171

--
Best regards,
Hirohito Higashi (h_east)

**Comment by brammool** [comment]
I'll include that patch, it fixes the problems reported in this issue.
But there might still be other issues, please open a new issue for that and describe how to reproduce.
