### ISSUE TITLE
`getchangelist()` doesn't recognize the `'%'` string

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#2641]
- `vim --version`:      VIM - Vi IMproved 8.0  Included patches: 1-1515
 - Operating system:     Ubuntu 16.04.3 LTS
 - Terminal emulator:    rxvt-unicode v9.22
 - Terminal multiplexer: tmux 2.6
 - `$TERM`:              tmux-256color
 - Shell:                zsh 5.3.1

Hello,

from `:h getchangelist()`:

    Returns the |changelist| for the buffer {expr}. For the use
    of {expr}, see |bufname()| above.

Then, from `:h bufname()`:

    "" or "%" can be used for the current buffer, "#" for the
    alternate buffer.

So, I expected the following command to return the changelist for the current buffer:

    :echo getchangelist('%')

But instead, it returns an empty list, even though `:changes` reports that the buffer has a non-empty changelist.

**Comment by vim-ml** [comment]
Hi,

On Tue, Feb 13, 2018 at 6:35 AM, lacygoill <vim-dev-github@256bit.org> wrote:
> vim --version: VIM - Vi IMproved 8.0 Included patches: 1-1515
> Operating system: Ubuntu 16.04.3 LTS
> Terminal emulator: rxvt-unicode v9.22
> Terminal multiplexer: tmux 2.6
> $TERM: tmux-256color
> Shell: zsh 5.3.1
>
> Hello,
>
> from :h getchangelist():
>
> Returns the |changelist| for the buffer {expr}. For the use
> of {expr}, see |bufname()| above.
>

The help text is wrong. It should say see |bufexists()| above.
The use of {expr} for getchangelist() is similar to the
bufexists(), buflisted() and bufloaded() functions. I can change
it to be like bfuname().

- Yegappan

**Comment by lacygoill** [comment]
Sorry I was wrong, `getjumplist()` is not supposed to be passed the string `'%'`. It expects a window number.

As for `getchangelist()`, I don't know what is the best choice. I guess whatever is the most consistent with other similar functions.

If you think it's not an issue, feel free to close it.

Thank you very much for the function.

**Comment by vim-ml** [comment]
Hi,

On Tue, Feb 13, 2018 at 6:59 AM, lacygoill <vim-dev-github@256bit.org> wrote:
> Sorry I was wrong getjumplist() is not supposed to be passed the string '%'.
> It expects a window number.
>
> As for getchangelist(), I don't know what is the best choice. I guess
> whatever is the most consistent with other functions.
>

Can you try the attached patch which modifies getchangelist() to accept
buffer number similar to the bufname() function?

Thanks,
Yegappan

diff --git a/src/evalfunc.c b/src/evalfunc.c
index daef9a8c9..57929d6d7 100644
--- a/src/evalfunc.c
+++ b/src/evalfunc.c
@@ -4365,7 +4365,10 @@ f_getchangelist(typval_T *argvars, typval_T *rettv)
 	return;
 
 #ifdef FEAT_JUMPLIST
-    buf = find_buffer(&argvars[0]);
+    (void)get_tv_number(&argvars[0]);	    /* issue errmsg if type error */
+    ++emsg_off;
+    buf = get_buf_tv(&argvars[0], FALSE);
+    --emsg_off;
     if (buf == NULL)
 	return;

**Comment by lacygoill** [comment]
I've just tested the patch, and it seems to work. `getchangelist('%')` outputs the changelist of the current buffer. Thank you very much.

**Comment by vim-ml** [comment]
Hi,

On Tue, Feb 13, 2018 at 6:59 AM, lacygoill <vim-dev-github@256bit.org> wrote:
>
> As for getchangelist(), I don't know what is the best choice. I guess
> whatever is the most consistent with other functions.
>

For the record, I looked at all the Vim functions that accept a buffer number or
a buffer name. The following functions accept a buffer number/name along with
the special characters "%", "#" and "":

bufname(), bufnr(), bufwinid(), bufwinnr(), getbufinfo(),
getbufline(), getbufvar(),
getchangelist(), setbufline() and setbufvar().

The following functions accept a buffer number or name (but doesn't accept
the special characters):

bufexists(), buflisted() and bufloaded().

- Yegappan

**Comment by lacygoill** [comment]
Yes I agree with your choice, I think it makes `getchangelist()` more consistent with the majority of functions handling buffers. Thank you for taking the time to check this.
