### ISSUE TITLE
`:options` is missing some options

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#2642]
- `vim --version`:      VIM - Vi IMproved 8.0  Included patches: 1-1515
 - Operating system:     Ubuntu 16.04.3 LTS
 - Terminal emulator:    rxvt-unicode v9.22
 - Terminal multiplexer: tmux 2.6
 - `$TERM`:              tmux-256color
 - Shell:                zsh 5.3.1

Hello,

It seems `:opt` is missing some options. At the moment, on my machine:

    echo len(getcompletion('', 'option'))

… returns `378`.

However, I find only `374` options in the window opened by `:opt`:

    :opt
    :echo len(filter(getline(1, '$'), {i,v -> v =~# '^\%(\d\+\)\@!\&^[^\"]\&^\S'}))

The missing options seem to be:

    'browsedir'
    'key'
    'langnoremap'
    'prompt'
    'pumwidth'
    'termcap'
    'toolbariconsize'
    'wildoptions'

Some options are also present in the window opened by `:opt` but not in the output of `getcompletion()`. I guess it depends on how Vim was built.

---

Neovim `0.2.3` seems to have a similar issue. `:opt` doesn't show the following options:

    'channel'
    'guicursor'
    'guifont'
    'guifontset'
    'guifontwide'
    'inccommand'
    'langmenu'
    'makeencoding'
    'menuitems'
    'prompt'
    'scrollback'
    'shada'
    'wildoptions'
    'winaltkeys'
    'winhighlight'

And for some reason, `getcompletion('', 'option')` doesn't include `'browsedir'`.

**Comment by brammool** [comment]
Please be more specific.  A quick check shows that it's all fine.
Please report Neovim problems with Neovim, don't bother the Vim project with those.

**Comment by lacygoill** [comment]
Ok, I must have made a mistake, sorry for the inconvenience.
