### ISSUE TITLE
Assigning the variables used by a lambda expression after its definition raises `E121`.

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#2643]
- `vim --version`:      VIM - Vi IMproved 8.0  Included patches: 1-1515
 - Operating system:     Ubuntu 16.04.3 LTS
 - Terminal emulator:    rxvt-unicode v9.22
 - Terminal multiplexer: tmux 2.6
 - `$TERM`:              tmux-256color
 - Shell:                zsh 5.3.1

Hello,

I'm not sure this is a bug, so feel free to close this issue if you consider it's not one.

Consider this snippet:

    fu! Func()
        let foo = 1
        let bar = 2
        let l:Test = { -> foo + bar ==# 3 }
        return l:Test()
    endfu
    echo Func()

If I source the code, it works, and displays `1` on the command-line.

If I move the  assignment of the lambda expression to the variable `l:Test`, 1 line above:

    fu! Func()
        let foo = 1
        let l:Test = { -> foo + bar ==# 3 }
        let bar = 2
        return l:Test()
    endfu
    echo Func()

It still works.
But if I move it 1 line above again:

    fu! Func()
        let l:Test = { -> foo + bar ==# 3 }
        let foo = 1
        let bar = 2
        return l:Test()
    endfu
    echo Func()

It raises the errors `E121` and `E15`:

    Error detected while processing function Func[4]..<lambda>900:
    line    1:
    E121: Undefined variable: foo
    E15: Invalid expression: foo + bar ==# 3

It seems that at least one of the variables used by a lambda must be created before the lambda.
Is it documented? I can't find anything that seems to expain this in `:h lambda`, `:h closure`, `:h :func-closure` (nor in the issues: `is:issue lambda E121`).

I could understand the rule “all variables used by a lambda must be created before the latter“. But, if some variables can be created after, shouldn't it be possible to create all the variables after.

According to `:h closure`:

    Lambda expressions can access outer scope variables and arguments.

So, `l:Test` should be able to access the variables defined in the scope of the function `Func()`, that is `foo` and `bar`. And yet it seems to be true only depending on the location of the assignments.

**Comment by k-takata** [comment]
Interesting. I implemented this, but I wasn't aware of this behavior.

When Vim parses a lambda, Vim checks whether the lambda should be a closure or not. If the lambda uses outer variables, it becomes a closure.

When parsing the second example, `foo` already exists, so the lambda becomes a closure. `bar` doesn't exist yet, however, it doesn't cause an error when parsing and it can be accessed when executing the lambda.

When parsing the third example, either `foo` nor `bar` doesn't exist, so the lambda doesn't become a closure, so it cannot access the outer variables.

I'd like to say that this behavior is implementation detail and users should not rely on this. The first example is recommended. All the variables used in a lambda should be created before that.
(It might be better to add strict error checking, but it requires overhead.)

**Comment by lacygoill** [comment]
@k-takata Thank you very much for taking the time to explain this behavior.
