### ISSUE TITLE
In macOS, maxmem and maxmemtot set to random huge values at startup

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#2646]
After running `vim --clean` (Vim 8.0.1500) in macOS, `maxmem` and `maxmemtot` are set to unreasonably high values, approximately  around `9007199254522616`. I say approximately because the actual values change at every run (but they are always of the same order of magnitude).

I could not reproduce the issue under Linux, so I guess that this has to do with the way Vim detects the amount of memory in macOS.

**Comment by nuko8** [comment]
For El Capitan (10.11.6) and High Sierra (10.13.3), respectively, `vim --clean` on Terminal.app gave me

![screen shot 2018-02-15 at 18 25 53](https://user-images.githubusercontent.com/13826919/36249964-bfe256f4-127f-11e8-865a-37805fa216bd.png)
El Capitan (10.11.6)

![screen shot 2018-02-15 at 18 30 07](https://user-images.githubusercontent.com/13826919/36249982-ca0a821e-127f-11e8-8776-8ac86b8191c0.png)
High Sierra (10.13.3)

Honestly, as I usually don't care about `maxmem` or `maxmemtot`,  I'm not sure if those values shown above are normal for macOS.  That said, as`:h maxmem` says "The maximum usable value is about 2000000,"  it doesn't look to me that they are something unreasonable.  I'm totally at a loss to explain where that stunning huge value 9007199254522616 comes from.

**Comment by lifepillar** [comment]
Using an 8GB iMac with Sierra, I get value similar to yours (~332848), but with a 16GB MacBook Pro with High Sierra (10.3.3) I get those huge values (I have just tried with Vim 8.0.1520, built from source). May it depend on the total available memory?

**Comment by vim-ml** [comment]
On Thu, Feb 15, 2018 at 11:26 AM, Kazunobu Kuriyama <
vim-dev-github@256bit.org> wrote:

> For El Capitan (10.11.6) and High Sierra (10.13.3), respectively, vim
> --clean on Terminal.app gave me
>
> [image: screen shot 2018-02-15 at 18 25 53]
> <https://user-images.githubusercontent.com/13826919/36249964-bfe256f4-127f-11e8-865a-37805fa216bd.png>
> El Capitan (10.11.6)
>
> [image: screen shot 2018-02-15 at 18 30 07]
> <https://user-images.githubusercontent.com/13826919/36249982-ca0a821e-127f-11e8-8776-8ac86b8191c0.png>
> High Sierra (10.13.3)
>
> Honestly, as I usually don't care about maxmem or maxmemtot, I'm not sure
> if those values shown above are normal for macOS. That said, as:h maxmem
> says "The maximum usable value is about 2000000," it doesn't look to me
> that they are something unreasonable. I'm totally at a loss to explain
> where that stunning huge value 9007199254522616 comes from.
>
The maximum usable value on 32-bit systems is about 2 GiB, or about 2000000
(KiB). On 64-bit systems the usable value is higher, but probably not as
high as the 9 exabytes (if I count correctly) boasted by Lifepillar's Vim
(which is about half the maximum unsigned integer expressible in 64 bits).

On modern systems (where there is enormously much more memory than the 640
KiB of 16-bit Dos systems) the Vim default is half the size of the RAM. It
seems that on Lifepillar's system, when Vim asks how much RAM there is, the
systems answers 2^64 - 1 bytes i.e. 0xFFFFFFFFFFFFFFFF, or something close
to that.

Best regards,
Tony.

**Comment by nuko8** [comment]
Indeed,
```
0xFFFFFFFFFFFFFFFF >> 1 = 9223372036854775807,

                          9007199254522616000  (lifepillar's value * 1000)
```
So that's too huge, but the value itself may not be something randomly given.

Hmm,  if `fstatfs(2)` should return such a huge value for his 16GB MacBook Pro, what could Vim do with that?

**Comment by nuko8** [comment]
@lifepillar 

I forgot to ask you about an important thing: Other than the value appearing to be unusual which you are characterizing as "random", "huge" and "unreasonable," is there anything that you think makes Vim buggy due to that, e.g., slow I/O?  If any, please leave a note about that.

**Comment by lifepillar** [comment]
>is there anything that you think makes Vim buggy due to that, e.g., slow I/O?

AFAICT, the only effect is that the whole file is always loaded into memory. I/O is ~260 MB/s.

**Comment by ichizok** [comment]
On macOS, `maxmem` is obtained by `sysctl(3)`.

https://github.com/vim/vim/blob/36f923014a7eb7e24c4b0b88719cad14351e3a60/src/os_unix.c#L579-L589

(Actually, `maxmem` is `mem >> 11`)

However, `HW_USERMEM` is 32bit int value.

`/usr/include/sys/sysctl.h` (xnu source: `bsd/sys/sysctl.h`)

```c
#define	HW_USERMEM	 6		/* int: non-kernel memory */
```

Therefore, on 64bit system, it is considered that the value obtained from `HW_USERMEM` is unreliable (or maybe modulo 32bit?) and `maxmem` is also.

In my case, when I used VM software, Vim (on host macOS) `set mm` became huge (like 9007199254522616).

**Comment by brammool** [comment]
> On macOS, `maxmem` is obtained by `sysctl(3)`.
> 
> https://github.com/vim/vim/blob/36f923014a7eb7e24c4b0b88719cad14351e3a60/src/os_unix.c#L579-L589
> 
> (Actually, `maxmem` is `mem >> 11`)
> 
> However, `HW_USERMEM` is 32bit int value.
> 
> `/usr/include/sys/sysctl.h` (xnu source: `bsd/sys/sysctl.h`)
> 
> ```c
> #define	HW_USERMEM	 6		/* int: non-kernel memory */
> ```
> 
> Therefore, on 64bit system, it is considered that the value obtained from `HW_USERMEM` is unreliable (or maybe modulo 32bit?) and `maxmem` is also.
> 
> In my case, when I used VM software, Vim (on host macOS) `set mm` became huge (like 9007199254522616).

Well, if there is no alternative, can we at least detect the invalid
value and fall back to a reasonable value, like 1G?
I can't reproduce the problem, thus I can't work on a fix.


-- 
There are only two hard things in programming: Cache invalidation,
naming things and off-by-one errors.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by nuko8** [comment]
Hmm...what do we have to fix, then?  Let's recall that the OP replied to my question like this:

>> is there anything that you think makes Vim buggy due to that (= the huge `maxmex`), e.g., slow I/O?
>
> AFAICT, the only effect is that the whole file is always loaded into memory. I/O is ~260 MB/s.

It is clear from this statement that, aside from that huge `maxmem` value, he seemingly didn't have any actual or substantial issue for us to address for the Vim on his 16GB MBP, i.e., we don't know what to do yet.

@lifepillar Please clarify what to fix.  Or, if your purpose of opening the issue is only to ask for an explanation of the value, how about reading through [macOS's virtual memory system](https://developer.apple.com/library/content/documentation/Performance/Conceptual/ManagingMemory/Articles/AboutMemory.html) for yourself and learn how your machines are working?  I'm afraid that the stuff explained there won't fit a brief answer suitable for this issue tracker.

**Comment by ichizok** [comment]
On Linux, `maxmem` is based on the total physical memory size (fixed value).
So I propose that also on macOS (and other BSD) `maxmem` uses the same:

```diff
--- a/src/os_unix.c
+++ b/src/os_unix.c
@@ -577,12 +577,19 @@ mch_total_mem(int special UNUSED)
     long_u     shiftright = 10;  /* how much to shift "mem" right for Kbyte */

 # ifdef HAVE_SYSCTL
-    int                mib[2], physmem;
+#  if defined(HW_MEMSIZE)
+    int                mib[2] = {CTL_HW, HW_MEMSIZE};
+    long_u     physmem;
+#  elif defined(HW_PHYSMEM64)
+    int                mib[2] = {CTL_HW, HW_PHYSMEM64};
+    long_u     physmem;
+#  else
+    int                mib[2] = {CTL_HW, HW_PHYSMEM};
+    int                physmem;
+#  endif
     size_t     len;

     /* BSD way of getting the amount of RAM available. */
-    mib[0] = CTL_HW;
-    mib[1] = HW_USERMEM;
     len = sizeof(physmem);
     if (sysctl(mib, 2, &physmem, &len, NULL, 0) == 0)
        mem = (long_u)physmem;
```

**Comment by brammool** [comment]
> On Linux, `maxmem` is based on the physical memory size (fixed value).
> So I propose that also on macOS (and other BSD) `maxmem` uses the same:

I do prefer to only use user memory, since kernel memory is irrelevant.
This matters for small (embedded) systems.

I found a suggestion that HW_USERMEM may return a 64 bit value, even 
when sizeof(int) is 32.  In which case the call doesn't give enough
space.  This might work:

# ifdef HAVE_SYSCTL
    int		mib[2];
    union {
	unsigned int	u32;
	unsigned long	u64;
    } physmem;
    size_t	len;

    /* BSD way of getting the amount of RAM available. */
    mib[0] = CTL_HW;
    mib[1] = HW_USERMEM;
    len = sizeof(physmem.u64);
    if (sysctl(mib, 2, &physmem, &len, NULL, 0) == 0)
    {
	if (len == sizeof(physmem.u64))
	    mem = (long_u)physmem.u64;
	else
	    mem = (long_u)physmem.u32;
    }
# endif

Please give it a try.

-- 
So when I saw the post to comp.editors, I rushed over to the FTP site to
grab it.  So I yank apart the tarball, light x candles, where x= the
vim version multiplied by the md5sum of the source divided by the MAC of
my NIC (8A3FA78155A8A1D346C3C4A), put on black robes, dim the lights,
wave a dead chicken over the hard drive, and summon the power of GNU GCC
with the magic words "make config ; make!".
		[Jason Spence, compiling Vim 5.0]

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lifepillar** [comment]
Both @ichizok's and @brammool's solutions appear to work for me. With 16GB of available memory, the former sets `maxmem` and `maxmemtot` to ~8GB, while the latter sets it to ~1.8GB (1933564).

**Comment by ichizok** [comment]
> I found a suggestion that HW_USERMEM may return a 64 bit value, even
> when sizeof(int) is 32.  In which case the call doesn't give enough
> space.  

According to Apple's darwin-xnu sources, macOS `HW_USERMEM` returns signed int, so I can't think this value indicates the correct status.
https://github.com/apple/darwin-xnu/blob/master/bsd/kern/kern_mib.c#L293-L298
https://github.com/apple/darwin-xnu/blob/master/bsd/kern/kern_mib.c#L446

As far as I investigate, some BSD (NetBSD/OpenBSD) can use `HW_USERMEM64` to obtain 64bit value, and on some other (FreeBSD/DragonflyBSD) `HW_USERMEM` returns 64bit value.

And on macOS, it seems that should use Mach API in order to obtain the correct user memory size.
but I also think it is enough to use the total memory size (`HW_MEMSIZE`) since could consider that macOS is not on small systems.

using only `sysctl` (no Mach API for macOS):

```diff
--- a/src/os_unix.c
+++ b/src/os_unix.c
@@ -577,15 +577,30 @@ mch_total_mem(int special UNUSED)
     long_u     shiftright = 10;  /* how much to shift "mem" right for Kbyte */

 # ifdef HAVE_SYSCTL
-    int                mib[2], physmem;
-    size_t     len;
+    int                mib[2] = {
+       CTL_HW,
+#  if defined(HW_MEMSIZE)
+       HW_MEMSIZE
+#  elif defined(HW_USERMEM64)
+       HW_USERMEM64
+#  else
+       HW_USERMEM
+#  endif
+    };
+    union {
+       unsigned int    u32;
+       unsigned long   u64;
+    } physmem;
+    size_t     len = sizeof(physmem.u64);

     /* BSD way of getting the amount of RAM available. */
-    mib[0] = CTL_HW;
-    mib[1] = HW_USERMEM;
-    len = sizeof(physmem);
     if (sysctl(mib, 2, &physmem, &len, NULL, 0) == 0)
-       mem = (long_u)physmem;
+    {
+       if (len == sizeof(physmem.u64))
+           mem = (long_u)physmem.u64;
+       else
+           mem = (long_u)physmem.u32;
+    }
 # endif
```

**Comment by ichizok** [comment]
I confirmed `len` of `HW_USERMEM` is 4 (int) on macOS.

**Comment by ichizok** [comment]
Incidentally, `HW_MEMSIZE` is only on macOS (darwin), so other BSD can use `HW_USERMEM64` or `HW_USERMEM`.

**Comment by ichizok** [comment]
I consider that using Mach API could obtain the user memory (== total - wired) as follows.
https://github.com/vim/vim/compare/master...ichizok:fix/maxmem.diff

**Comment by brammool** [comment]
> I consider that using Mach API could obtain the user memory (== total - wired) as follows.
> https://github.com/vim/vim/compare/master...ichizok:fix/maxmem.diff

What is "wire_count" ?  Missing comments here.

This looks too complex.  Doesn't Mac have HW_USERMEM and/or
HW_USERMEM64?

-- 
Females are strictly forbidden to appear unshaven in public.
		[real standing law in New Mexico, United States of America]

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ichizok** [comment]
I updated the branch, added comments.

> What is "wire_count" ?  Missing comments here.

This is the page count used as kernel memory, thus `vm_stat.wire_count * getpagesize()` is kernel memory size (byte).

> Doesn't Mac have HW_USERMEM and/or HW_USERMEM64?

macOS has `HW_USERMEM`, but we cannot obtain the correct size of user memory from this.
And macOS does not have `HW_USERMEM64`.
Thus on macOS:

(A) Obtain the total memory size by `sysctl` (using `HW_MEMSIZE`: this is only on macOS)
(B) Obtain the kernel memory size by Mach API (`host_statistics`, `host_statistics64`)
(C) Obtain the user memory size: (A) - (B).

**Comment by brammool** [comment]
> > I found a suggestion that HW_USERMEM may return a 64 bit value, even
> > when sizeof(int) is 32.  In which case the call doesn't give enough
> > space.  
> 
> According to Apple's darwin-xnu sources, macOS `HW_USERMEM` returns signed int, so I can't think this value indicates the correct status.
> https://github.com/apple/darwin-xnu/blob/master/bsd/kern/kern_mib.c#L293-L298

Intresting, this takes the user memory as an int and the subtracts the
page size multiplied with someting as a long.  This might very well
result in a negative number, which used as an unsigned results in
rediculous numbers.

> https://github.com/apple/darwin-xnu/blob/master/bsd/kern/kern_mib.c#L446
> 
> As far as I investigate, some BSD (NetBSD/OpenBSD) can use
> `HW_USERMEM64` to obtain 64bit value, and on some other
> (FreeBSD/DragonflyBSD) `HW_USERMEM` returns 64bit value.

We need to make sure the code works for all systems.  So perhaps the
Darwin specific code in the #ifdef and the rest in a following #else,
using the 64 bit variants first, if they exist.


-- 
<Beeth> Girls are like internet domain names,
        the ones I like are already taken.
<honx>  Well, you can stil get one from a strange country :-P

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
> I updated the branch, added comments.
> 
> > What is "wire_count" ?  Missing comments here.
> 
> This is the page count used as kernel memory, thus `vm_stat.wire_count * getpagesize()` is kernel memory size (byte).
> 
> > Doesn't Mac have HW_USERMEM and/or HW_USERMEM64?
> 
> macOS has `HW_USERMEM`, but we cannot obtain the correct size of user memory from this.
> And macOS does not have `HW_USERMEM64`.
> Thus on macOS:
> 
> (A) Obtain the total memory size by `sysctl` (using `HW_MEMSIZE`: this is only on macOS)
> (B) Obtain the kernel memory size by Mach API (`host_statistics`, `host_statistics64`)
> (C) Obtain the user memory size: (A) - (B).

I think depending on HW_MEMSIZE to only exist on Mac is a bit brittle.
We should use HW_USERMEM64 first, when it not exists then use HW_MEMSIZE
on the Mac and fall back to HW_USERMEM otherwise.

Without the Darwin code, I think this would work:

# ifdef HAVE_SYSCTL
    /* BSD way of getting the amount of RAM available. */
    int		mib[2];
#  ifdef HW_USERMEM64
    int64_t	physmem;
#  else
    /* sysctl() may return 32 bit or 64 bit, accept both */
    union {
	unsigned int	u32;
	unsigned long	u64;
    } physmem;
#  endif
    size_t	len;

    mib[0] = CTL_HW;
#  ifdef HW_USERMEM64
    mib[1] = HW_USERMEM64;
    len = sizeof(physmem);
#  else
#    ifdef MACOS_X_DARWIN
    /* Mac has HW_USERMEM but it returns an int, which is insufficient. */
    mib[1] = HW_MEMSIZE;
#    else
    mib[1] = HW_USERMEM;
#    endif
    len = sizeof(physmem.u64);
#  endif
    if (sysctl(mib, 2, &physmem, &len, NULL, 0) == 0)
    {
#  ifdef HW_USERMEM64
	mem = (long_u)physmem;
#  else
	if (len == sizeof(physmem.u64))
	    mem = (long_u)physmem.u64;
	else
	    mem = (long_u)physmem.u32;
#  endif
    }
# endif

Quite a few #ifdefs though...


-- 
"I know that there are people who don't love their fellow man,
and I hate those people!" - Tom Lehrer

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ichizok** [comment]
`HW_MEMSIZE` returns 64bit, then it should use `int64_t physmem` too.

BTW: on macOS we can get the amount of RAM available by using only Mach API (without `sysctl` call).
In this way, we can make the code in `HAVE_SYSCTL` somewhat simple. 

https://github.com/vim/vim/compare/master...ichizok:fix/maxmem.diff
(I updated)

```c
# ifdef MACOS_X_DARWIN
    {
        /* Mac (Darwin) way of getting the amount of RAM available */
        /* ... */
    }
# endif

# ifdef HAVE_SYSCTL
    if (mem == 0)
    {
        /* BSD way of getting the amount of RAM available. */
        int     mib[2];
#  ifdef HW_USERMEM64
        long_u  physmem;
#  else
        union {
            int_u       u32;
            long_u      u64;
        } physmem;
#  endif
        size_t  len = sizeof(long_u);

        mib[0] = CTL_HW;
#  ifdef HW_USERMEM64
        mib[1] = HW_USERMEM64;  /* non-kernel memory (64bit) */
#  else
        mib[1] = HW_USERMEM;    /* non-kernel memory (32 or 64bit) */
#  endif
        if (sysctl(mib, 2, &physmem, &len, NULL, 0) == 0)
        {
#  ifdef HW_USERMEM64
            mem = physmem;
#  else
            if (len == sizeof(physmem.u64))
                mem = (long_u)physmem.u64;
            else
                mem = (long_u)physmem.u32;
#  endif
        }
    }
# endif
```
