### ISSUE TITLE
error with mksession E946: Cannot make a terminal with running job modifiable: nomodifiable

### ISSUE THREAD

**Issue by g-i-o-r-g-i-o** [vim/vim#2650]
If you save a session containing a terminal, you get an error code:
E946: Cannot make a terminal with running job modifiable: nomodifiable

Steps:
`start vim`
open a terminal session with
`:vertical terminal`
save the session with
`:mksession file`

Close and then start vim
load the session with
`:source file`

See that you receive the error
`E946: Cannot make a terminal with running job modifiable: nomodifiable`
which sends you to the row 373 (more or less) of the session file, where you find the row:
`setlocal nomodifiable`

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 26 2017 00:51:47)
Included patches: 1-1216
Compiled by 
Huge version with GTK2 GUI.  Features included (+) or not (-):

**Comment by brammool** [comment]
Fixed with patch 8.0.1589
