### ISSUE TITLE
echo mode(1) doesn't return full mode string

### ISSUE THREAD

**Issue by eraserhd** [vim/vim#2653]
If I run `:echo mode(1)`, or `echo mode("foo")`, I get back "n" or "t" (if I used `<C-w>:echo mode(1)` in a terminal) and I don't get back the full mode name as advertised in the docs.

I'm on 8.0.1523.

**Comment by k-takata** [comment]
"Full mode" means that it return the mode with two letters if available. (E.g. `no` for Operator-pending.)
However, if you run the command manually, it normally return only one letter.
It doesn't return "Normal", "Insert" and so on.

**Comment by eraserhd** [comment]
Oh, I see.  I think the documentation is clear enough, I misread it.
