### ISSUE TITLE
:wqa abandons running terminal job

### ISSUE THREAD

**Issue by eraserhd** [vim/vim#2654]
The docs say it will abort if a buffer cannot be saved, so it seems this isn't consistent with the terminal docs.

8.0.1523

**Comment by brammool** [comment]
Jason Felice wrote:

> The docs say it will abort if a buffer cannot be saved, so it seems
> this isn't consistent with the terminal docs.

Yeah, that's not right, it would require :wqa!

-- 
A hamburger walks into a bar, and the bartender says: "I'm sorry,
but we don't serve food here."

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
