### ISSUE TITLE
Have vim placed in .config directory

### ISSUE THREAD

**Issue by TheBabu** [vim/vim#2655]
Hello, I am in the process of reorganizing all of my files and such and I was just wondering if there was any way to the `~/.vim` directory somehow placed in `.config` like how much user defined configuration files are placed. I am also wondering if there is any consequences if I do this tho.

Thank you for any help!

**Comment by vim-ml** [comment]
2018-02-20 2:01 GMT+03:00 Ariq Haqq <vim-dev-github@256bit.org>:
> Hello, I am in the process of reorganizing all of my files and such and I
> was just wondering if there was any way to the ~/.vim directory somehow
> placed in .config like how much user defined configuration files are placed.
> I am also wondering if there is any consequences if I do this tho.
>
> Thank you for any help!

Based on what I know you may

1. Use Neovim as it supports XDG by default (and only XDG, ~/.vim or
~/.nvim or whatever is not supported).
2. Use symlinks. Will leave symlinks in home directory, of course.
3. Create a shell wrapper (function or alias) which will call Vim
using something like

       vim -u ~/.config/vim/init.vim -N "$@"

   (path based on Neovim XDG implementation, though note that Neovim
does respect $XDG* variables) and have proper `set runtimepath` and
`set viminfo` commands rewriting default ~/.vim* paths near the top of
`init.vim` (and proper configuration of plugin managers if you use
any).
4. Create your own Vim fork where default paths point to inside ~/.config.

Vim have no problems with any of the variants, the only issue you
theoretically *could* encounter is a *buggy* plugin which expects that
it is placed in ~/.vim directly and nowhere else. Given the existence
of plugin managers which place plugins anywhere, but in ~/.vim
directly (though in many cases somewhere under ~/.vim, but that does
not matter) and existence of Neovim which does not ever use ~/.vim
unless user explicitly configured Neovim to do just that such plugins
are very rare and I would not expect any actively supported plugin to
have any problems even if ~/.vim does not exist at all. If you do have
such plugin and do not want to edit its source code then symlinks are
the only option.

**Comment by ZyX-I** [comment]
Ah, and I just noted, but you should not use *issue tracker* for such questions. There is specific mailing list for user questions. You could place a *feature request* for XDG support here, but it would not be the first request to support XDG base directory specification (e.g. [this patch](https://groups.google.com/forum/#!topic/vim_dev/ieoldm29ymM)) and there are backwards compatibility considerations (Neovim can throw away some of them, Vim can’t).

**Comment by TheBabu** [comment]
Ah Thank you! I will look into neovim, I will note that there is a mailing list for this type of stuff next time! Closing issue!
