### ISSUE TITLE
Test failures on macOS, version 8.0.1529

### ISSUE THREAD

**Issue by chdiza** [vim/vim#2657]
8.0.1529 has a test failure on macOS 10.13.3, that doesn't seem to have been caught by CI:

```
From test_syntax.vim:
Found errors in Test_syntax_c():
function RunTheTest[38]..Test_syntax_c[27]..VerifyScreenDump line 14: See dump file difference: call term_dumpdiff("Test_syntax_c_01.dump.failed", "dumps/Test_syntax_c_01.dump")

Test results:


From test_syntax.vim:
Found errors in Test_syntax_c():
function RunTheTest[38]..Test_syntax_c[27]..VerifyScreenDump line 14: See dump file difference: call term_dumpdiff("Test_syntax_c_01.dump.failed", "dumps/Test_syntax_c_01.dump")
TEST FAILURE
make[2]: *** [report] Error 1
make[1]: *** [scripttests] Error 2
make: *** [test] Error 2
```

**Comment by nuko8** [comment]
Seems like whether or not the error in question takes place depends on the terminal in use:  While successfully passing the test for Terminal.app, xterm, urxvt and st on my macOS, Vim failed it with the same error above only for iTerm2.

On iTerm2, following the instructions suggested in the error message:

```
$ VIMRUNTIME=../runtime ./vim --clean --noplugin
:cd testdir
:call term_dumpdiff("Test_syntax_c_01.dump.failed", "dumps/Test_syntax_c_01.dump")
```
I got

![screen shot 2018-02-21 at 16 33 39](https://user-images.githubusercontent.com/13826919/36468510-fcc7d1b0-1726-11e8-954c-19f9a077e3b8.png)

The following is a result obtained by partially mimiking the test by hand for iTterm2 with the default profile (=settings):
```
vim --clean --noplugin -c 'hi Normal ctermfg=black ctermbg=white'
:e Xtest.c
:term
$ vim --clean --noplugin -R Xtest.c
```

![screen shot 2018-02-21 at 17 06 30](https://user-images.githubusercontent.com/13826919/36469149-9de8a0cc-1729-11e8-8f91-55a92945bee0.png)

So, it appears that screen dump itself works fine even for iTerm2.

As screen dump is a new feature introduced a few days ago and I haven't had time to look at it much, that's all I can tell for now.

**Comment by chdiza** [comment]
Indeed, I was using iTerm2.

**Comment by brammool** [comment]
Hmm, the diff looks similar to what happens on MS-Windows, where the console only supports 16 colors.  Is iTerm2 also having a restriction on the number of colors allowed?  Or does it default to 16 colors when started with "vim --clean"?
What happens when running Vim in iterm2 and setting t_Co to 256?
Can you get the colors to match then?

**Comment by nuko8** [comment]
iTerm2 gives 256 to t_Co for `vim --clean`.  t_Co values are the same for both Vim on iTerm2 and Vim on `:term` in Vim on iTerm2.

But there is a difference between them---`'background'`.  In fact, the following command sequence
```
vim --clean -c 'hi Normal ctermfg=0 ctermbg=15'
:term
% vim --clean
:set backround?
<C-w>w
:set background?
```
gives

![screen shot 2018-02-23 at 13 59 45](https://user-images.githubusercontent.com/13826919/36578640-eb0cd4f8-18a1-11e8-958f-12668ed820d9.png)

Obviously, the automatic background color detection fails for Vim on `:term` in Vim on iTerm2.

Naturally, one way for fixing it is to improve the automatic detection, but that may be tricky.  Until such an improvement is given, the following symptomatic and yet natural treatment will do:
```diff
diff --git a/src/testdir/screendump.vim b/src/testdir/screendump.vim
index 5131b935a..cb653b700 100644
--- a/src/testdir/screendump.vim
+++ b/src/testdir/screendump.vim
@@ -22,9 +22,10 @@ func RunVimInTerminal(arguments, options)
   " Always doo this with 256 colors and a light background.
   set t_Co=256
   hi Normal ctermfg=0 ctermbg=15
+  let arguments = "--cmd \"set background=light\" " . a:arguments
 
   let cmd = GetVimCommandClean()
-  let cmd .= ' ' . a:arguments
+  let cmd .= ' ' . arguments
   let buf = term_start(cmd, {'curwin': 1, 'term_rows': 20, 'term_cols': 75})
   call assert_equal([20, 75], term_getsize(buf))
 

```

**Comment by brammool** [comment]
I managed to implement t_RF and t_RB for libvterm, I'll send out the patch tomorrow.

**Comment by nuko8** [comment]
> I managed to implement t_RF and t_RB for libvterm, I'll send out the patch tomorrow.

I've just confirmed that Patch [8.0.1533](https://github.com/vim/vim/commit/674e482d1346aa1afddab62675f3a7d7a00a4894) gets Vim to pass `test_syntax` on iTerm2.  Thank you for giving it the definitive treatment :)

**Comment by chdiza** [comment]
> I've just confirmed that Patch 8.0.1533 gets Vim to pass test_syntax on iTerm2.

Yep, here too.  Thanks!
