### ISSUE TITLE
Could not load library msvcrt-ruby240.dll

### ISSUE THREAD

**Issue by FR4N7Z** [vim/vim#2660]
I have install the last version of the x86 version of vim 8 and I have an issue whith the ruby integration.
My plugins like LustyExplorer can’t work and when I enter

:ruby –version
I got the following error :

E370: Could not load library msvcrt-ruby240.dll  
E266 : Sorry, this command is disabled, the Ruby Library could not be loaded. 
When I run

:version
I have : +ruby/dyn and

-DDYNAMIC_RUBY -DDYNAMIC_RUBY_VER=24 -
DDYNAMIC_RUBY_DLL=\"msvcrt-ruby240.dll\"
Ruby is install in C:\Ruby24 and the bin folder containing the msvcrt-ruby240.dll is in %PATH%.
I also tried to put in my vimrc file

set rubydll="C:\Ruby24\bin\msvcrt-ruby240.dll"
but I got the following error :

E370: Could not load Library
E266 : Sorry, this command is disabled, the Ruby Library could not be loaded.
Both ruby and vim are x86.

I am working on windows 10. Thanks for your help.

**Comment by k-takata** [comment]
Please try updating the `PATH` as I wrote in vim/vim-win32-installer#47.
It might be better to update the document something like this:

```diff
--- a/runtime/doc/if_ruby.txt
+++ b/runtime/doc/if_ruby.txt
@@ -221,6 +221,9 @@ for sure edit "gvim.exe" and search for 
 If you want to build Vim with RubyInstaller 1.9 or 2.X using MSVC, you need
 some tricks.  See the src/INSTALLpc.txt for detail.
 
+If Vim is built with RubyInstaller 2.4 or later, you may also need to add
+"C:\Ruby<version>\bin\ruby_builtin_dlls" to the PATH environment variable.
+
 
 Unix ~
 
```

> :ruby –version

If you want to see the version of if_ruby, use `:ruby print RUBY_VERSION`. (See `:help :ruby`.)

> set rubydll="C:\Ruby24\bin\msvcrt-ruby240.dll"

This won't work as you expected. `"` is a start of a comment, so this makes `'rubydll'` empty.
(See `:help option-backslash`.)

**Comment by FR4N7Z** [comment]
Add C:\Ruby24\bin\ruby_builtin_dlls to the PATH solve the issue.
Thank you.
