### ISSUE TITLE
Popupmenu is in the wrong place again (v8.0.1529)

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#2661]
**Expected position (v8.0.1489):**

![pic1](https://user-images.githubusercontent.com/3035071/36522404-4bc58da6-17d7-11e8-9213-12f6d323c7f5.png)

In v8.0.1489, the popupmenu is adaptive to the cursor's position. The left edge of 
popupmenu corresponds to the cursor.

**Actuall position (v8.0.1529):**

![pic2](https://user-images.githubusercontent.com/3035071/36522413-5b3a139c-17d7-11e8-8278-57aeda27c68a.png)

But in v8.0.1529, popupmenu's left edge is not in the same column of cursor. I need move my eyes away from the cursor position to the left side to see the completion candidates, which is not convenient.

So, can popupmenu show itself in the old way ?

**Comment by Shougo** [comment]
```
						*'pumwidth'* *'pw'*
'pumwidth' 'pw'		number	(default 0)
			global
			{not available when compiled without the
			|+insert_expand| feature}
			{not in Vi}
	Determines the minium width to use for the popup menu for Insert mode
	completion.  When zero the default of 15 screen cells is used.
	|ins-completion-menu|.
```

**Comment by Shougo** [comment]
https://github.com/vim/vim/issues/2314

**Comment by skywind3000** [comment]
I have set `pumwidth` to 0 or 8, and got the same result.

**Comment by skywind3000** [comment]
In my second screen capture, the actual width of the popup menu is definitely more than 100, no matter I set the pumwidth to zero or something else.

When I am editing on the right split and writing something about STL, I will always get that huge popupmenu which occupy 1/3 of my screen size.

**Comment by skywind3000** [comment]
I don't care the minimum width of popupmenu, but I really care having to move eyes left and right repeatly and that makes me dizzy and become less productive.

Introducing new features should not break old rules.

**Comment by xguerin** [comment]
I believe the problems lays with the maximum width of the popup menu. It does not make much sense to move it leftward past the completion point by 1000s of characters in the case of a STL completion.

**Comment by skywind3000** [comment]
I have just tested v8.0.1538 immediately, but it appeared that still not fixed on my linux box:

![pum](https://user-images.githubusercontent.com/3035071/36633986-be5573f6-19d8-11e8-9545-c39a2afba243.png)

anybody can still reproduce this after v8.0.1538 ?

**Comment by brammool** [comment]
Looks like this still happens if the entries in the popup menu are wider than the window.

**Comment by brammool** [comment]
Actually, it's when the space available is more then 'pumwidth'.

**Comment by skywind3000** [comment]
Thanks, it seems to be fixed

**Comment by brammool** [comment]
Linwei wrote:

> Thanks, it seems to be fixed

Keep an eye open for other problems, I'm still not happy about the logic
of the code.  At least we now have tests to check for any regressions.

-- 
How do you know when you have run out of invisible ink?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
