### ISSUE TITLE
tabline mouse highlight stays permanently

### ISSUE THREAD

**Issue by vlachoudis** [vim/vim#2664]
Hi, I am using vim from ubuntu version 8.0.550.
There is a tiny problem, that is confusing some times.
When I hover the mouse over the tabline (without clicking anything), it highlights the tab with light blue color which is fine. However when the mouse moves down of the tabline the last highlighted tab will remain highlighted and it becomes confusing with the "lightgrey" active tab. Funny enough if I move the mouse "up" from the tabline then correctly it removes the lightblue highlight from the tab.

**Comment by nuko8** [comment]
Since gvim leaves tabline highlight to the GUI toolkit, that's not an issue of Vim.

**Comment by vlachoudis** [comment]
Ok thanks. I will open an issue to the toolkit. In the mean time can i control the setting of the high light from the tabline of vim? So i can set the same color as the unhilighted one? Otherwise it becomes confusing.

**Comment by chrisbra** [comment]
I am not sure and it probably depends on the toolkit you are using. GTK properties can be styled by using css properties, I believe. Other than that I have no knowledge about this. Have a look at `:h GTK3`.

Closing.
