### ISSUE TITLE
Full screen mode doesn't work, since upgrading to Mac OS X "High Sierra".

### ISSUE THREAD

**Issue by capn-freako** [vim/vim#2667]
Since upgrading my MacBook Air's OS to "High Sierra", _Vim_ doesn't work correctly in full screen mode.
It still works fine in normal windowed mode.
The symptom, in full screen mode, is an unrefreshed screen, which can't be completely restored with either "CTRL-L", or ":e". The void parts of lines have a black background, while the occupied parts have a dark gray background. And the contrast and resultant "blocky" appearance of the text area is VERY distracting.

**Comment by chdiza** [comment]
Vim doesn't have a fullscreen mode on macOS.  Are you thinking of MacVim?  That's a separate project.

**Comment by capn-freako** [comment]
Yes, sorry. :(
