### ISSUE TITLE
New pumwidth option has misspelling in help..

### ISSUE THREAD

**Issue by systemmonkey42** [vim/vim#2669]
> 'pumwidth' 'pw'		number	(default 15) 			global
> 			{not available when compiled without the
> 			|+insert_expand| feature}  {not in Vi}
> 	Determines the **minium** width to use for the popup menu for Insert mode'

This appears only in the latest builds. Searching issues for "minium" finds the following unrelated issue: #2661

**Comment by brammool** [comment]
Thanks, I'll fix it.
