### ISSUE TITLE
[Question] - Cursor position after closing VIM

### ISSUE THREAD

**Issue by thisSIDEofRANDOM** [vim/vim#2677]
Did something change recently with how VIM handles cursor position when closing? Suddenly when my cursor is always at the bottom of my screen after closing a file from edit

** Before
![image](https://user-images.githubusercontent.com/8302785/36693168-0b628f08-1b00-11e8-8f35-32c3a534fdda.png)

** After
![image](https://user-images.githubusercontent.com/8302785/36693263-5fa5000a-1b00-11e8-9c5f-c2f60ec7ad10.png)

I could be missing a setting in vimrc but it popped up just recently so was curious if anyone else was experiencing this.

**Comment by chrisbra** [comment]
Nothing changed in Vim. Check your `t_ti` and `t_te` settings and make sure your $TERM variable is setup correct (that means your terminal should behave as claimed :))

Please note, this forum here is not for user questions. Use vi.stackexchange.com or the vim-use mailinglist to ask user questions. As such, I am closing it, sorry

**Comment by chrisbra** [comment]
BTW: Perhaps you are running into this Arch specific problem: https://bugs.archlinux.org/task/57640

**Comment by thisSIDEofRANDOM** [comment]
Thanks @chrisbra thats it, was just looking through that file also trying to figure out why they set it that way.
