### ISSUE TITLE
Do you have features to color the code embedded in markdown file? 

### ISSUE THREAD

**Issue by CoinCheung** [vim/vim#2678]
For markdown files, there can be other programming language coded embedded between the \``` \``` pair. however, in vim these code blocks does not have highlighted syntax. Did I have the wrong configuration to turn this feature off, or does vim have no such features?

**Comment by mattn** [comment]
You can enable highlight with following configuration.

```vim
let g:markdown_fenced_languages = [
\  'vim',
\  'html',
\  'css',
\  'erb=eruby',
\  'go',
\  'java',
\  'javascript',
\  'js=javascript',
\  'json=javascript',
\  'ruby',
\  'sass',
\  'sql',
\  'xml',
\]
```

**Comment by k-takata** [comment]
Please note that this forum here is not for user questions. Use vi.stackexchange.com or the vim-use mailinglist to ask user questions. I'm closing this.

@mattn Thank you for answering.

**Comment by CoinCheung** [comment]
Ah I see, thanks a lot @mattn

**Comment by tyru** [comment]
@CoinCheung If you don't want to custom those filetypes in your vimrc, you can try this plugin.
https://github.com/tyru/markdown-codehl-onthefly.vim

The plugin automatically configures `g:markdown_fenced_languages`, and reload buffer.
The code between "\`\`\`{filetype}" and "\`\`\`" is highlighted as {filetype}.
But if you want to define additional alias filetypes like `viml` (as github is used), you can define like this.

```vim
let g:markdown_codehl_onthefly#additional_fenced_languages =
\     markdown_codehl_onthefly#get_default_fenced_languages() + ['vimscript=vim']
```

Or if you don't like default aliases, just overwrite it.

```vim
let g:markdown_codehl_onthefly#additional_fenced_languages = ['vimscript=vim']
```

You can view default aliases here (sorry for no documentation yet...).
https://github.com/tyru/markdown-codehl-onthefly.vim/blob/d34ce3fe2011009eb8712e3ae3cae8a51d3fccd2/autoload/markdown_codehl_onthefly.vim#L6-L25
