### ISSUE TITLE
How can I change this charachter ?

### ISSUE THREAD

**Issue by ghost** [vim/vim#2679]
I wanna change "~" character for not opened lines on leftside to " " . Do you guys have any idea where can I do it ? 

https://ibb.co/f7ry7c

**Comment by k-takata** [comment]
The character is hard-coded in the source code and cannot be changed. https://github.com/vim/vim/blob/33ef5bb0e4ea9a049c4311cfe59d1926dcb963a4/src/screen.c#L2298-L2299

However you can change the highlight. E.g. `:hi EndOfBuffer ctermfg=0 guifg=bg`
See `:help hl-EndOfBuffer` for detail.

**Comment by ghost** [comment]
Thank you, that works for me.

**Comment by chrisbra** [comment]
closing then. Please ask user questions at vi.stackexchange.com or at the vim-use mailinglist. Thanks.

**Comment by ghost** [comment]
Actually, because of my transparent background "~" was visible little bit which is annoying and then I download vim from git and changed file you mentioned then compiled again and it worked ! https://ibb.co/bzHuDH
