### ISSUE TITLE
quickfix: <c-w><cr> causes E36 with noequalalways and height < 3

### ISSUE THREAD

**Issue by blueyed** [vim/vim#2682]
Given a quickfix window with a height of 1 or 2 lines, `Ctrl-w enter` on an entry to open it in a new window results in "E36: Not enough room".
When using a height of 3 you will get new window of height 1 (which is not very useful).

1. As mentioned in https://github.com/vim/vim/issues/908 already (which has not been re-opened), it should behave like using `:help` from a quickfix window with a height of 3 or more: it opens a new window with a reasonable height.
2. `:help` in a window using a height of 1 or 2 also causes `E36` - this should get fixed, especially given that there is a workaround for `:help` not using a window of height 1 only with qf window of height 3 (also mentioned in #908 already).

**Comment by brammool** [comment]
I cannot reproduce. Did you start with "vim --clean"?

**Comment by blueyed** [comment]
Given `t-qf-cwcr.vim`:
```vim
set noequalalways
call setqflist("foo")
copen 1
call feedkeys("\<c-w>\<cr>")
```
Running `vim -u NONE --noplugin t-qf-cwcr.vim -c 'source %'` triggers it for me.

**Comment by blueyed** [comment]
You might have missed the `:set noequalalways` (from the subject).

**Comment by brammool** [comment]
Well, with 'equalalways' off this is expected, you need to create space first.
The option basically means "don't mess with my window sizes, I know what I'm doing".
Help is an exception, because it restores the window layout after it's closed.  And that is only possible assuming it's opened and then closed, without any other window changes.  This is not a generic solution.

**Comment by blueyed** [comment]
Ok.  I am using https://github.com/blueyed/dotfiles/blob/master/vim/after/ftplugin/qf.vim to work around this, basically temporarily unsetting `equalalways` in case there is not enough room.
