### ISSUE TITLE
"--clean" does not imply "--noplugin" (like --help says)

### ISSUE THREAD

**Issue by blueyed** [vim/vim#2684]
`vim --help` says:

> --clean              'nocompatible', Vim defaults, no plugins, no viminfo

But the "no plugins" part seems to be wrong: it will still trigger loading of e.g. `after/ftplugin/qf.vim` with `:copen`.

Either the help needs to be fixed, or it should include what `--noplugin` does.
I would prefer the latter, since that would give us an easy option to get a default Vim setup (ignoring user plugins).

**Comment by brammool** [comment]
--clean is supposed to allow for various features, but no personal preferences or history (from viminfo).  But 'runtimepath' still contains '~/.vim" and '~/.vim/after'.  As you mention, this does have side effects, depending on the plugins in your own vim directory.

I don't want to skip loading plugins, e.g. syntax highlighting is supposed to work.  We should probably not add ~/.vim to 'runtimepath'.

**Comment by tonymec** [comment]
@blueyed : IIUC, `--noplugin` avoids sourcing **global** plugins. But the one you mentioned is a **filetype** plugin. IIUC, the command `filetype plugin indent on` present in `defaults.vim` will load filetype plugins as needed whenever the `'filetype'` of a buffer is set.

Best regards,
Tony.

**Comment by chrisbra** [comment]
fixed by https://github.com/vim/vim/releases/tag/v8.0.1554
