### ISSUE TITLE
Support `winhighlight` feature.

### ISSUE THREAD

**Issue by jordwalke** [vim/vim#2686]
NeoVim added a feature called `winhighlight` which is really nice. Maybe vim should add it as well. It enables windows to have distinct highlighting (For example, the `Normal bgcolor` can be set *per* window).

**Comment by bfredl** [comment]
Note also `NormalNC` group that goes along with it. (different bg color of non-active window)

**Comment by unphased** [comment]
I would also like to request `winhighlight` and `NormalNC` for vim! :)

**Comment by chrisbra** [comment]
I believe you can have the same using the [wincolor option](https://vimhelp.org/options.txt.html#'wincolor') setting.

**Comment by noscript** [comment]
@unphased try
```vim
hi NormalNC guibg=#414B61
au WinEnter * setl wincolor=
au WinLeave * setl wincolor=NormalNC
```

**Comment by unphased** [comment]
~This is awesome, however I do plan to have asynchronous commands run inside vim that can change specific unfocused windows' background colors, which would require the `winhighlight` capability.~

Actually I may be mistaken, as although `wincolor` is a weaker capability than `winhighlight`, it seems like it would be able to support my actual use case! It just wouldn't be able to let me configure different colors for all different combinations.

**Comment by chrisbra** [comment]
I supposed this can be closed then.
