### ISSUE TITLE
Vim cannot write *.vba files

### ISSUE THREAD

**Issue by Eijebong** [vim/vim#2694]
Vim says: `E382: Cannot write, 'buftype' option is set` when you try to write a `.vba` file.

Steps to reproduce:
- vim toto.vba
- :wq

The problems seems to be coming from this line: https://github.com/vim/vim/blob/946acdac5b4e334f816e78f7876bde9d97b3d96a/runtime/plugin/vimballPlugin.vim#L31 as commenting it out "fixes" the bug.

**Comment by chrisbra** [comment]
Oh, I am surprised this has been finally noted. `.vba` files where initially used as vimball files to distribute vim plugins and it has been later switched to `.vmb` format.
cc @cecamp 
perhaps its time to drop support for the old `.vba` vimball format and only use `.vmb`, since vba could be legitimite files after all.

To workaround it, if you need to write a legimitate `.vba` file, simply set the `buftype` option to empty: `:set bt=`

**Comment by Nicceboy** [comment]
This issue seems to still happen. I was wondering, why I could not save files in `.vba` type.

**Comment by chrisbra** [comment]
if you do not intend to use vimballs, you can also disable it by setting

     let g:loaded_vimballPlugin=1

in your .vimrc. Then it shouldn't happen.

**Comment by Nicceboy** [comment]
> 
> 
> if you do not intend to use vimballs, you can also disable it by setting
> 
> ```
>  let g:loaded_vimballPlugin=1
> ```
> 
> in your .vimrc. Then it shouldn't happen.

Seems to solve issue in my case. Thank you.

**Comment by dkearns** [comment]
I was just updating the Visual Basic file type detection and was going to add support for `*.vba` files.

Unfortunately, there's some Vimball functionality triggered with BufEnter autocommands which I don't think can reasonably be disabled as it stands.

It seems to me that the easiest solution might be to make a dedicated filetype for Vimballs.  Then the autocommands can use FileType instead.

**Comment by chrisbra** [comment]
Yes, probably should get vimball as an own filetype. And possibly also get rid of `.vba` as extension for vimball. It's been long gone and nowadays vimballs use the `.vmb` extension anyhow.

**Comment by vim-ml** [comment]
On Mi, 23 Aug 2023, Gary Johnson wrote:

> All of the vimballs I have from Chip Campbell use the .vba
> extension.
> 
> The first line of a .vba file could be inspected to determine
> whether it was a vimball.

Oh, that is true. I just checked the website 
http://www.drchip.org/astronaut/vim/index.html

I also checked the documentation for the vimball:

,----
| 	33 : Apr 02, 2011 * Gave priority to *.vmb over *.vba
| 			  * Changed silent! to sil! (shorter)
| 			  * Safed |'swf'| setting (during vimball extraction,
| 			    its now turned off)
`----

Oh well ...

Best,
Christian
-- 
I am the wandering glitch -- catch me if you can.

**Comment by dkearns** [comment]
> On 2023-08-19, Christian Brabandt wrote: Yes, probably should get vimball as an own filetype. And possibly also get rid of .vba as extension for vimball. It's been long gone and nowadays vimballs use the .vmb extension anyhow.
> All of the vimballs I have from Chip Campbell use the .vba extension. The first line of a .vba file could be inspected to determine whether it was a vimball.

Yes, that's what I've done for now, in the simplest way possible.

Creating a separate filetype has other advantages but, of course, only works when filetype support is enabled.  I might still do that in a separate PR.

Thanks.
