### ISSUE TITLE
setline() which does not change contents should not change &modified

### ISSUE THREAD

**Issue by blueyed** [vim/vim#2700]
Currently `call setline('.', getline('.'))` will set the `&modified` flag and adds an undo step, although the buffer was not modified.

I think it is sensible to only set the flag and add an undo step for actual changes.

**Comment by k-takata** [comment]
But `yyVp` in normal mode also sets `&modified` and adds an undo step.

**Comment by chdiza** [comment]
This is how it's always worked.  That also happens if you open a file, navigate to some character (say `A`), then do `rA`.

This is one of those cases where the Vim name for something---`&modified`---is slightly misleading.  AFAICT it really means "edited", as in "an editing operation was performed", which doesn't entail that the operation's result is different from the starting point.  And if an editing operation was performed, one should be able to undo the operation.

Besides, surely this is so deeply embedded that changing it would break all kinds of things.

**Comment by chrisbra** [comment]
This is how every editor I have available works actually and that is how it always behaved in Vim. 
For this to be fixed, Vim would need to keep the state of the original file and compare them to the currently edited buffer after each editing step.

**Comment by brammool** [comment]
Right, although theoretically an improvement, being backwards compatible is more important.

**Comment by blueyed** [comment]
Please note that the issue was meant to be only about `setline()`, and other editors often do not provide an API for this in the first place.
It is easy for setline to compare the before and after state I would assume.
I've noticed this with tcomment, where it can be fixed manually (https://github.com/tomtom/tcomment_vim/pull/207), which is true for this issue in general - but I still think that `setline()` should not imply having an `undo` step always.

**Comment by chdiza** [comment]
> Please note that the issue was meant to be only about setline()

We know; but why should `setline()` work differently than other buffer-surgeries?  *That* would be unexpected behavior.

**Comment by blueyed** [comment]
> other buffer-surgeries

Yes, setting a buffer's line through e.g. the Python API should behave the same then - and I can see that this is not feasible easily.  I would draw the line between user actions (i.e. normal mode commands), and API functions - but that's not clear to distinguish likely.

**Comment by lifepillar** [comment]
>I still think that setline() should not imply having an undo step always.

Although this has been closed (and rightly so), I'd like to add that I see the current behaviour as the most sensible one (if not “the correct” one) and the easiest to reason about: if my script calls `setline()` N times, and then performs N undo operations, the original state of the buffer will be restored. With your proposal, this invariant would be violated, in general. *That* would be a bad API, IMO. 

Besides, it is easy to avoid “useless” calls to `setline()` if one wants to:

```vim
if (getline('.') !=# new_line)
  call setline('.', new_line)
endif
```

A little more involved if `new_line` is a List, but nothing that couldn't be wrapped into a simple function.
