### ISSUE TITLE
No error with :cc and :ll for unknown entry

### ISSUE THREAD

**Issue by blueyed** [vim/vim#2701]
Given a location/quickfix list with only one entry, `:cc`/`:ll` with a number of 2 will jump to the first entry, but it should cause an error instead - similar to `E42: No errors` when using it with an empty list.

**Comment by brammool** [comment]
Currently you can use ":999cc" to go to the last entry.  Making that an error would upset some users.

**Comment by blueyed** [comment]
There is `:clast` and `:llast` that could/should be used instead probably.
And there is `:99lnext` that will cause no error (when it moves), but only causes an error when at the end already.
