### ISSUE TITLE
Vim is involved with system corruption. 

### ISSUE THREAD

**Issue by Ernst03** [vim/vim#2705]
Vim is involved with system corruption. 
Memory 31.3 GIB. AMD FX 9590
Graphics NV126
Gnome Version 3.26.2
Fedora 27
------------------------------------------

When loading text files around 1 gigabyte or more Shell will become corrupt and shell will hang up, video will quit such as VLC and file systems will fail to unmount when the drives are encrypted.
 So check with super large files and see how it goes.  A shut-off and restart is the only answer here.
 As for why such large files.  I often have "printouts" of programs I write as an out-file. This latest effort generates a lot of text if I let it. I had a  7 gigabyte file I tried to load (without checking size before I tried) and VIM quit immediately. Shell locked and video became corrupt and quit playing.
  I saw some "Kernel Errors" a couple of times during this but mostly it is stop Jobs that run forever with "No Limit." when I go to power off. 
 I love Vim I live and Program by Vim!  So I hope this helps improve the Vim!

**Comment by mattn** [comment]
Vim doesn't know how many memory(s) could be allocated. You've better to add ulimit or you can add following code into your vimrc.

```vim
if len(filter(range(argc()), 'getfsize(argv(v:val))>pow(1024,3)*7')) > 0
  echomsg "Hey! Vim will quit VLC!"
  sleep 3
  cquit!
endif
autocmd BufReadPre * if getfsize(expand("<afile>"))>pow(1024,3)*7|echomsg "Hey! Vim will quit VLC"|sleep 3|cquit!|endif
```
Note that your changes will be lost after 3 seconds if you open 7GB.

**Comment by chrisbra** [comment]
This issue does not give much detail. But I haven't suffered from memory corruption when using Vim with large files. Are you sure you don't have an actual hardware issue here? Also you might try to compile Vim with address sanitizer flags to check if there is something unusual.

**Comment by brammool** [comment]
I recently edited a 5 Gbyte file.  It's a bit slow, but works fine.
Most likely it's just a heavy load on the system (both CPU and disk), things heat up and cause a crash.
Nothing we can do in Vim to avoid that.
Try reducing the CPU frequency, improve cooling, check your power supply, etc.  Could be anything.
