### ISSUE TITLE
Feature request: improve cmdline-completion for arglist commands with c_CTRL-D

### ISSUE THREAD

**Issue by kiryph** [vim/vim#2706]
As documented under `:h cmdline-completion` a user can press on the commandline `<C-d>` to get a list of possible values in many circumstances. This works for

- `:`
- `:b`
- `:ta` and similar `:tj` and `:ts`
- `:e`
- `:se`
- `:map`
- ...

In particular, I miss that `<C-d>` does not work for `:argu<space><C-d>`.
This should not list only possible numbers but also the filename.

Furthermore the `:argdelete` command could be improved:

`:argdelete<space><C-d>` should only list entries of the arglist.

**Comment by vim-ml** [comment]
Hi,

On Fri, Mar 9, 2018 at 1:14 AM, kiryph <vim-dev-github@256bit.org> wrote:
> As documented under :h cmdline-completion a user can press on the
> commandline <C-d> to get a list of possible values in many circumstances.
> This works for
>
> :
> :b
> :ta and similar :tj and :ts
> :e
> :se
> :map
> ...
>
> In particular, I miss that <C-d> does not work for :argu<space><C-d>.
> This should not list only possible numbers but also the filename.
>
> Furthermore the :argdelete command could be improved:
>
> :argdelete<space><C-d> should only list entries of the arglist.
>

The attached patch adds support for command line completion for
file names from the argument list. This works for the ":argedit" and
":argdelete" commands.

- Yegappan

**Comment by kiryph** [comment]
Hi Yegappan,

thanks for implementing this!

However, I think `:argedit` should actually allow to specify files which are not yet in the arglist:
```
:[count]arge[dit][!] [++opt] [+cmd] {name} ..		*:arge* *:argedit*
			Add {name}s to the argument list and edit it.
			When {name} already exists in the argument list, this
			entry is edited.
```

That's the reason why I was talking about `:argu`:
```
							*:argu* *:argument*
:[count]argu[ment] [count] [++opt] [+cmd]
			Edit file [count] in the argument list.  When [count]
			is omitted the current entry is used.  This fails
			when changes have been made and Vim does not want to
			|abandon| the current buffer.
			Also see |++opt| and |+cmd|.
			{not in Vi} {not available when compiled without the
			|+listcmds| feature}
```

**Comment by kiryph** [comment]
When I compare the situation to buffer commands, maybe one could allow `:argu[ment]` to use as an argument either the arglist number or the filename?

```
:[N]b[uffer][!] [+cmd] [N]		*:b* *:bu* *:buf* *:buffer* *E86*
		Edit buffer [N] from the buffer list. ...

:[N]b[uffer][!] [+cmd] {bufname}
		Edit buffer for {bufname} from the buffer list.  ...
```

**Comment by brammool** [comment]
I don't think completing numbers for :argument is useful.
Let's only do this for :argdelete now.

Changing :argument to accept a buffer name is tricky: what if an argument is a number?
I know for buffer names we already have this confusion.

**Comment by vim-ml** [comment]
Yegappan wrote:

> On Fri, Mar 9, 2018 at 1:14 AM, kiryph <vim-dev-github@256bit.org> wrote:
> > As documented under :h cmdline-completion a user can press on the
> > commandline <C-d> to get a list of possible values in many circumstances.
> > This works for
> >
> > :
> > :b
> > :ta and similar :tj and :ts
> > :e
> > :se
> > :map
> > ...
> >
> > In particular, I miss that <C-d> does not work for :argu<space><C-d>.
> > This should not list only possible numbers but also the filename.
> >
> > Furthermore the :argdelete command could be improved:
> >
> > :argdelete<space><C-d> should only list entries of the arglist.
> >
> 
> The attached patch adds support for command line completion for
> file names from the argument list. This works for the ":argedit" and
> ":argdelete" commands.

Thanks!

-- 
hundred-and-one symptoms of being an internet addict:
90. Instead of calling you to dinner, your spouse sends e-mail.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by kiryph** [comment]
My motivation is that I want to use the wildmenu to interactively switch to a buffer on the arglist. 

> I don't think completing numbers for :argument is useful.

Agreed.

> Changing :argument to accept a buffer name is tricky: what if an argument is a number?
I know for buffer names we already have this confusion.

Well, `:argu` accepts a count at two locations:

```
:[count]argu[ment] [count] [++opt] [+cmd]
```

What about accepting a count only beforehand and afterwards only a filename:
```
:[count]argu[ment] {name} [++opt] [+cmd]
```

**Comment by vim-ml** [comment]
Hi,

On Thu, Mar 29, 2018 at 1:45 AM, kiryph <vim-dev-github@256bit.org> wrote:
> Hi Yegappan,
>
> thanks for implementing this!
>
> However, I think :argedit should actually allow to specify files which are
> not yet in the arglist:
>
> :[count]arge[dit][!] [++opt] [+cmd] {name} .. *:arge* *:argedit*
> Add {name}s to the argument list and edit it.
> When {name} already exists in the argument list, this
> entry is edited.
>

Yes. But when selecting a name from the arglist, you can use command
line completion to select the name. If the file name is not in the arglist,
then you can manually enter it.

I see that Bram has already incorporated the patch with the command
line completion support  for the ":argdelete" command.

>
> That's the reason why I was talking about :argu:
>
> *:argu* *:argument*
> :[count]argu[ment] [count] [++opt] [+cmd]
> Edit file [count] in the argument list.  When [count]
> is omitted the current entry is used.  This fails
> when changes have been made and Vim does not want to
> |abandon| the current buffer.
> Also see |++opt| and |+cmd|.
> {not in Vi} {not available when compiled without the
> |+listcmds| feature}
>

But the ":argument" command currently takes a count and not
a name for a file in the arglist.

Unless the behavior of ":argedit" or ":argument" is modified, we cannot
extend command line completion to these commands.

Regards,
Yegappan

**Comment by brammool** [comment]
Yegappan wrote:

> On Thu, Mar 29, 2018 at 1:45 AM, kiryph <vim-dev-github@256bit.org> wrote:
> > Hi Yegappan,
> >
> > thanks for implementing this!
> >
> > However, I think :argedit should actually allow to specify files which are
> > not yet in the arglist:
> >
> > :[count]arge[dit][!] [++opt] [+cmd] {name} .. *:arge* *:argedit*
> > Add {name}s to the argument list and edit it.
> > When {name} already exists in the argument list, this
> > entry is edited.
> 
> Yes. But when selecting a name from the arglist, you can use command
> line completion to select the name. If the file name is not in the arglist,
> then you can manually enter it.

The normal way to use :argedit is to edit a file and add it to the
argument list a the same time.  That the file already is in the argument
list is the exception, normally you will want to complete any file name.

> I see that Bram has already incorporated the patch with the command
> line completion support  for the ":argdelete" command.

Yes, there we actually want to match argument file names.

-- 
From "know your smileys":
 :~)	A man with a tape recorder up his nose

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by kiryph** [comment]
I know that there is no hope that `:argu[ment]` will gain support to accept names for the arglist.
However, I still want to point following out:

- First of all, naming files `1, 2, 3, ...` is in my opinion an edge case.
- People can live with this for the `:buffer` command which means it is really not a serious issue. 
- Giving arglist numbers higher priority than filenames would leave current behavior untouched.
- And I would argue consistency with `:buffer` command makes it easier to memorize functionality.
