### ISSUE TITLE
Makefile:3276: recipe for target 'objects/regexp.o' failed 

### ISSUE THREAD

**Issue by moonwater** [vim/vim#2707]
gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix│·························································································
-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng16 -I/usr│·························································································
/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/u│·························································································
sr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2   -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/regexp.o regexp.c  │·························································································
                                                                                                                                                      │·························································································
                                                                                                                                                      │·························································································
gcc: internal compiler error: Killed (program cc1)                                                                                                    │·························································································
Please submit a full bug report,                                                                                                                      │·························································································
with preprocessed source if appropriate.                                                                                                              │·························································································
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.                                                                                       │·························································································
Makefile:3276: recipe for target 'objects/regexp.o' failed                                                                                            │·························································································
make[1]: *** [objects/regexp.o] Error 4                                                                                                               │·························································································
make[1]: Leaving directory '/home/pp_of_mm/vim/src'                                                                                                   │·························································································
Makefile:26: recipe for target 'first' failed                                                                                                         │·························································································
make: *** [first] Error 2                                                                                                                             │·························································································
Starting make in the src directory.                                                                                                                   │·························································································
If there are problems, cd to the src directory and run make there                                                                                     │·························································································
cd src && make install                                                                                                                                │·························································································
make[1]: Entering directory '/home/pp_of_mm/vim/src'                                                                                                  │·························································································
gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix│·························································································
-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng16 -I/usr│·························································································
/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/u│·························································································
sr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2   -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/regexp.o regexp.c  │·························································································
gcc: internal compiler error: Killed (program cc1)                                                                                                    │·························································································
Please submit a full bug report,                                                                                                                      │·························································································
with preprocessed source if appropriate.                                                                                                              │·························································································
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.                                                                                       │·························································································
Makefile:3276: recipe for target 'objects/regexp.o' failed                                                                                            │·························································································
make[1]: *** [objects/regexp.o] Error 4                                                                                                               │·························································································
make[1]: Leaving directory '/home/pp_of_mm/vim/src'                                                                                                   │·························································································
Makefile:36: recipe for target 'install' failed                                                                                                       │·························································································
make: *** [install] Error 2

**Comment by dpelle** [comment]
gcc crashed.  This is not a vim bug, but a gcc bug.
What version of gcc are you using?

**Comment by brammool** [comment]
Not a Vim problem
