### ISSUE TITLE
Colorscheme issue : Black lines

### ISSUE THREAD

**Issue by SkyMortal** [vim/vim#2718]
Hello !

I have issue when I use (any) colorscheme. When I open a vim, the background color fits to my terminal, but I soon as I scroll down, the background is black. It keeps the scheme's color if there is text only.

The scheme below is Paper Color (background : dark). But it happens with any scheme (I tried Tomorrow-* schemes)
![black](https://user-images.githubusercontent.com/37414814/37479581-4af27360-287d-11e8-8b01-22812f6bd384.png)

Can you help me please ?

**Comment by chrisbra** [comment]
Please ask user questions at vi.stackexchange.com or vim-use mailinglist. This one is for actual Vim bugs.

In any case, try `:let &t_ut=''`
