### ISSUE TITLE
`nnoremap q: <Nop>` doesn't seem to be "nnoremapping"

### ISSUE THREAD

**Issue by chdiza** [vim/vim#2719]
Because I don't like `q:` as a way of entering the cmdline window, I map it away to <Nop>.  I've been doing this for a long time:
```
nnoremap q: <Nop>
vnoremap q: <Nop>
```
I used `*noremap` rather than `*map` because I found that otherwise when hitting `q` to stop recording, recording won't stop immediately; it would wait `&tm` long before stopping recording, because it's waiting to see if `q` will be followed by something else.

I could *swear* that this has been working for a while.  I even have a note in my `vimrc` to do it with `*noremap` instead of `*map`.  But today I noticed it doesn't work anymore.  Even with `*noremap`, the delay between hitting `q` to stop recording and the disappearance of the "recording @j" at the bottom of the screen is `&tm` long.

This happens even starting with `vim -u NONE -U NONE --noplugin -N`, and then doing:
```
nnoremap q: <Nop>
qj
q
```
I can see that it takes 1 second to stop recording to register @j.

I hope that this is an accidental regression.  But even if I'm simply misremembering, this behavior is odd.  Because there are obviously no mappings starting with `q` other than the one that's mapped to <Nop>, I find it rather counterintuitive that Vim would still wait to see if I'm going to trigger a mapping.

I'm on macOS, and I can reproduce the behavior in vim 8.0.1608 and also in MacVim.

**Comment by chdiza** [comment]
I can't believe this, but on the GitHub web interface, the sequence "<", "Nop", ">" gets made invisible unless it's in backticks.

**Comment by tonymec** [comment]
IIUC, what you see is expected.

After hitting `qj` you are left in Normal mode, but recording to register j.

When you hit just `q` a little later, Vim examines Normal-mode mappings to see if there is one starting with `q` — and there is. So, if `'timeout'` is on, it waits for `'timeoutlen'` milliseconds (or 1 second by default) to see if you hit a colon after the `q`. Once the timeout expires without you having hit anything, or as soon as you type any _different_ key after the `q`, normal operation resumes: recording ends.

In order to terminate the waiting early, you might want to type either some do-nothing sequence such as `<Left> <Right>` or even, IIUC, any F-key (other than `<F1>` = Help or `<F10>` = Menu) that you didn't remap in Normal mode, or else, anything at all which is mapped to `<Nop>` in Normal mode. Or you might even type the following key "blind": for instance `qa` in Recording mode will stop recording and immediately start appending in Insert mode.

**Comment by k-takata** [comment]
> I can't believe this, but on the GitHub web interface, the sequence "<", "Nop", ">" gets made invisible unless it's in backticks.

It is parsed as an html tag, and (maybe) removed by sanitizing. If you don't want to use backticks, you can use a `\` to escape it.
E.g. `\<Nop>` will be shown as \<Nop>.

**Comment by chdiza** [comment]
> IIUC, what you see is expected.

So am I just misremembering how vim used to behave?  I'm going to try bisecting when I get a chance.

If `XY` has been mapped to `<Nop>`, and there are no other mappings starting with `X`, I don't see why vim should do the map-wait after an `X`  What's it waiting for?  To find out whether it needs to noop, or to instead noop?

**Comment by tonymec** [comment]
If `XY` has been mapped to `<Nop>` then `X` still means `X` (or, in Normal mode, "delete [count] characters, or 1 if no count, before the cursor) whenever it isn't followed by `Y`; but if it is, the whole `XY` sequence is a do-nothing. So as long as you type `X` followed by nothing, Vim doesn't yet know if that `X` will be part of the do-nothing sequence `XY`, or if it will have its Vim-default "delete character before" binding. So it waits to see, not if it is noop or noop, but if it is noop or erase-before.

Best regards,
Tony.

**Comment by tonymec** [comment]
Oh, and BTW: if `'timeout'` is set false or if `'timeoutlen'` is zero, there will never be any timeout, but that means that a mapping with a multi-character {lhs} will never be recognized.

Best regards,
Tony.

**Comment by chdiza** [comment]
"X" here is a variable for any key, not the name of the normal mode command.

**Comment by mattn** [comment]
If typing q and the macro mode will ends immediately, we cannot expand the mappings that have prefix q during macro recording.

**Comment by chdiza** [comment]
I now see that my notes that were in my `.vimrc` were incorrect and muddled to start with.  So my entire foundation for suspecting a regression has collapsed.

I still need to figure out how to deactivate `q:` without also imposing `&tm` on the halting of recording, but that's for me to mess around with.

Thanks to those who helped.

**Comment by chdiza** [comment]
> If typing q and the macro mode will ends immediately, we cannot expand the mappings that have prefix q during macro recording.

But if there are no mappings with prefix `q`, as in my case, surely vim should be able to know this, and hence know that there's nothing to wait on or expand.

**Comment by tonymec** [comment]
You might try the following (untested) **instead** of your mapping:
``` vim
au CmdWinEnter * quit
```
to close the command-line window as soon as it is opened. Then no mapping starting with `q` would (IIUC) be needed.

This would in effect change all three of `q:` `q/` and `q?` to do-nothing sequences. If you want to keep using the Search command-line window but not the Ex-command-line window, it is possible: see what is said about `<afile>` under `:help CmdWinEnter`.

Best regards,
Tony.
