### ISSUE TITLE
bash syntax highlight error inside if statement

### ISSUE THREAD

**Issue by btstw** [vim/vim#2722]
![1521427786171](https://user-images.githubusercontent.com/25838252/37575671-5adbf416-2b63-11e8-9ed8-af375969c618.jpg)

syntax highlight have some issue when using bitwise operator.

**Comment by cecamp** [comment]
Please try the syntax/sh.vim you can find at http://www.drchip.org/astronaut/vim/index.html#SYNTAX_SH .
