### ISSUE TITLE
Vertical split between windows should consistently separate status lines.

### ISSUE THREAD

**Issue by tylerstreeter** [vim/vim#2724]
The vertical split between windows seems to separate status lines inconsistently. Below are some examples, using VIM 8.0.1608 on macOS 10.13.3, compiled with all default build options. (This may be the intended behavior, but that seems unlikely to me... If so, please help me understand the current behavior.)

### Example 1: Left/Right Window Status Lines are Different

Start vim, and do a vertical split: `vim -c "vsp"`. The result looks like this:

![1](https://user-images.githubusercontent.com/32965714/37614463-ca907ce0-2b78-11e8-9fc7-a627d623556e.png)

(Here the status lines have been set up to show text at the extreme left and right sides.) Note the cell at the intersection of the vertical split and the status lines. Where should it belong? Is it part of the vertical split? Or part of the left or right status line? The current behavior makes it appear to belong to the left window's status line (i.e. it matches the left window's status line color, and it lacks the vertical split char). This behavior makes text at the right side of the status lines appear inconsistent between the left and right windows, i.e. the left status line contains an extra (unusable cell) which is not present in the right status line.

### Example 2: Top/Bottom are Different when Vertical Split is First

Now start vim, first do a vertical split, and then split each window horizontally, and go to the lower-left window: `vim -c "vsp | sp | wincmd l | sp | wincmd h | wincmd j"`. The result looks like this:

![2](https://user-images.githubusercontent.com/32965714/37614470-ce36568a-2b78-11e8-97ff-5aa43656e4d0.png)

Note how the bottom vertical split/status line intersection acts like **Example 1** above, but the top two status line are actually separated by the vertical split. This shows a second inconsistency beyond that described in **Example 1**: the top and bottom act differently.

### Example 3: Top/Bottom are Similar when Horizontal Split is First

Now start vim, but this time first do a horizontal split, and then split each window vertically: `vim -c "sp | vsp | wincmd j | vsp"`. The result looks like this:

![3](https://user-images.githubusercontent.com/32965714/37614481-d304d178-2b78-11e8-978f-02f0e8700ebf.png)

Note how, in this case, both the bottom and top pairs of status lines act like **Example 1**. So this is yet another inconsistency: the result depends on the order of vertical/horizontal splitting.

### Further Examples

Try splitting into more windows (e.g. >= 3 vertical splits) and/or try various combinations of vertical and horizontal splits to demonstrate the current behavior.

### Suggested Solution

In all cases, it would seem best for the vertical split to separate the status lines (i.e. the cell at the intersection should belong to the vertical split).

**Comment by brammool** [comment]
This is intentional.  The difference is needed to show what will happen if you try to drag a status line.
If the vertical separator continues, then the left and right status lines are dragged independently.

**Comment by tylerstreeter** [comment]
That makes sense. Thanks for the explanation!
