### ISSUE TITLE
can't edit anymore, caret disappears after <p><strong> html tags.

### ISSUE THREAD

**Issue by solomonvic** [vim/vim#2725]
![vim_bug](https://user-images.githubusercontent.com/36799050/37617268-f04d6706-2bb2-11e8-9943-0ad56c5d82ef.png)

please look closely to the string between opening and closing html tags `<p><strong>` in the attached desktop screenshot in MATE terminal.

**Comment by chrisbra** [comment]
Missing information. It looks like your color scheme has a problem. Please reproduce with `vim --clean`

Also is the text shown when you enter visual mode? What terminal is this? What colorscheme? What does `:set bg? t_Co?` show?

**Comment by solomonvic** [comment]
thank you, I figured out the issue, it was the inappropriate colorscheme.
I opted to desert one

**Comment by solomonvic** [comment]
I tought i figured out the issue by changing the t_Co variable from 8 to 256 on the vim command line, but the problem persist when reloading VIM, any other suggestions ?.
