### ISSUE TITLE
tabstop setting is overwritten when opening a python file

### ISSUE THREAD

**Issue by wanzzhehe** [vim/vim#2726]
In my vimrc, I set tabstop=4. But when I open a python file, tabstop=8, I have to set tabstop by hand.
What's wrong with it?

**Comment by Shougo** [comment]
You should execute `verbose setlocal tabstop?`.
I think ftplugin overwrites the config.

https://github.com/vim/vim/issues/989

```vim
let g:python_recommended_style = 0
```

**Comment by mattn** [comment]
This is issue tracker to fix bugs. Please ask on https://groups.google.com/forum/#!forum/vim_use

**Comment by k-takata** [comment]
Please ask user questions at the vim_use mailing list as @mattn says or at vi.stackexchange.com.
Closing.
