### ISSUE TITLE
Weird interaction between 'virtualedit' and i_CTRL-G_j

### ISSUE THREAD

**Issue by sedm0784** [vim/vim#2743]
**Steps to Reproduce**

1. `vim -Nu NONE`
2. `:set ve=insert`
3. `i123<CR>1<CR>12<Esc>`
4. `ggA`
5. `<C-G>jx`
6. `<C-G>jx`

**Expected results**

    123
    1  x
    12 x

**Observed results**

    123
    1  x
    1x2

The first `x` is in the correct column, but the second `x` is not where you'd expect.

After performing the first downward `j` motion, the "insert start column" has been set to the position of the end of the line *before* we move down into it and enter text.

This sort of makes sense when we consider how `virtualedit` functions&#8202;&mdash;&#8202;it allows you to move the cursor past the end of the line, but the position of the end of the line isn't moved until *after* we enter the `x`&#8202;&mdash;&#8202;but it's not really intuitive with how you'd imagine`<C-G>j` would work: I would've expected that the "insert start column" should remain constant throughout the current session of insert mode.

**EDIT**

Actually, after thinking about it more, I'm not even sure it's the "remaining constant through the insert session" thing that's bugging me. Consider the simpler case:

1. `vim -Nu NONE`
2. `:set ve=all`
3. `i1<CR>12<Esc>`
4. `ggll`
5. `ix`
6. `<C-G>jx`

**Expected results**

    1 x
    12x

**Observed results**

    1 x
    1x2

I'd expect the second `x` to be in the same column as first `x`, because when I started insert mode, *that's where the cursor was*. The contents of the line shouldn't come into it.

**Comment by vim-ml** [comment]
On Fr, 23 Mär 2018, Rich wrote:

> **Steps to Reproduce**
> 
> 1. `vim -Nu NONE`
> 2. `:set ve=insert`
> 3. `i123<CR>1<CR>12<Esc>`
> 4. `ggA`
> 5. `<C-G>jx`
> 6. `<C-G>jx`
> 
> **Expected results**
> 
>     123
>     1  x
>     12 x
> 
> **Observed results**
> 
>     123
>     1  x
>     1x2
> 
> The first `x` is in the correct column, but the second `x` is not where you'd expect.
> 
> After performing the first downward `j` motion, the "insert start column" has been set to the position of the end of the line *before* we move down into it and enter text.
> 
> This sort of makes sense when we consider how `virtualedit` functions: it allows you to move the cursor past the end of the line, but the position of the end of the line isn't moved until *after* we enter the `x`, but it's not really intuitive with how I think anyone would expect `<C-G>j` to work: I would've expected that the "insert start column" should remain constant throughout the current session of insert mode.

This happens, because the virtualedit setting is not taken into account. 
Attached is a patch with a test. 

Best,
Christian
-- 
Bemalung und Punktierung der Körper ist eine Rückkehr zur 
Tierheit.
		-- Goethe, Maximen und Reflektionen, Nr. 250
