### ISSUE TITLE
File "dehqx.py", line 19: SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by kenorb** [vim/vim#2754]
I've got the following error on macOS when compiling Vim with `--enable-gui`:

```
$ brew reinstall vim --enable-gui
==> Reinstalling vim --enable-gui
==> Downloading https://github.com/vim/vim/archive/v8.0.1600.tar.gz
Already downloaded: /Users/kenorb/Library/Caches/Homebrew/vim-8.0.1600.tar.gz
==> ./configure --prefix=/usr/local --mandir=/usr/local/Cellar/vim/8.0.1600/share/man --enable-multibyte --with-tlib=ncurses --enable-cscope --enable-terminal --with-compiledby=Homebrew
==> make
Last 15 lines from /Users/kenorb/Library/Logs/Homebrew/vim/02.make:
clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MAC -fno-common -fpascal-strings -Wall -Wno-unknown-pragmas -mdynamic-no-pic -pipe -I. -Iproto -DMACOS_X -DMACOS_X_DARWIN -I/Library/Developer/CommandLineTools/Headers/FlatCarbon  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/gui_mac.o gui_mac.c
/bin/sh install-sh -c -d Vim.app/Contents/Resources/English.lproj
clang -c -I. -Ilibvterm/include -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MAC -fno-common -fpascal-strings -Wall -Wno-unknown-pragmas -mdynamic-no-pic -pipe -I. -Iproto -DMACOS_X -DMACOS_X_DARWIN -I/Library/Developer/CommandLineTools/Headers/FlatCarbon  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -DINLINE="" -DVSNPRINTF=vim_vsnprintf -DIS_COMBINING_FUNCTION=utf_iscomposing_uint -DWCWIDTH_FUNCTION=utf_uint2cells -o objects/term_encoding.o libvterm/src/encoding.c
  File "dehqx.py", line 19
    print 'In file: ' + input
                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('In file: ' + input)?
make[1]: *** [bundle-rsrc] Error 1
make[1]: *** Waiting for unfinished jobs....
gui_mac.c:37:10: fatal error: 'Devices.h' file not found
#include <Devices.h> /* included first to avoid CR problems */
         ^~~~~~~~~~~
1 error generated.
make[1]: *** [objects/gui_mac.o] Error 1
make: *** [first] Error 2
```

Also related lines from the make log:

```
Creating resource fork
python dehqx.py os_mac.rsr.hqx
```

----

Repro steps on macOS:

1. Using Homebrew, edit `vim` formula via: `brew edit vim` and apply the following changes:

```
$ (cd $(brew --prefix)/Homebrew/Library/Taps/homebrew/homebrew-core; git diff)
diff --git a/Formula/vim.rb b/Formula/vim.rb
index 9df789f1..24e16c96 100644
--- a/Formula/vim.rb
+++ b/Formula/vim.rb
@@ -17,6 +17,7 @@ class Vim < Formula
   option "with-override-system-vi", "Override system vi"
   option "with-gettext", "Build vim with National Language Support (translated messages, keymaps)"
   option "with-client-server", "Enable client/server mode"
+  option "enable-gui", "Enable GUI mode"
 
   LANGUAGES_OPTIONAL = %w[lua python@2 tcl].freeze
   LANGUAGES_DEFAULT  = %w[python].freeze
@@ -67,7 +68,7 @@ class Vim < Formula
     end
 
     opts << "--disable-nls" if build.without? "gettext"
-    opts << "--enable-gui=no"
+    opts << "--enable-gui=yes"
 
     if build.with? "client-server"
       opts << "--with-x"
```
2. Install/re-install Vim via: `brew reinstall vim --enable-gui`.
You should see the error.

---

I'm not sure which Python is used to interpret the script since I've both:

```
$ python --version
Python 2.7.10
$ python3 --version
Python 3.6.4
$ which -a python
/usr/bin/python
```

Since the error is about missing parentheses, somehow I've ended up by parsing `dehqx.py` with Python 3 I believe as per this line from the log:

    Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/bin/python3.6

I'm attaching the log file: [vim-make.log](https://github.com/vim/vim/files/1848623/vim-make.log)

I believe the solution would be to make `dehqx.py` compatible with Python 3.

**Comment by parmort** [comment]
Yes, having parens around a print statement is `python 3+` syntax. Maybe try compiling with `python 2.*`?

**Comment by brammool** [comment]
Can we rely on python2 on the Mac to support print()?
Or add a header to have this file execute with Python2?

Not sure why it happens though, in the Makefile "python" is used and your "python --version" shows it is Python 2.

**Comment by parmort** [comment]
Would compiling vim from source solve the issue? Try using the instructions found in #2738.

**Comment by kenorb** [comment]
I think it happens, because by default `Formula["python"]` in Homebrew (see: `brew edit vim`) points to Python 3.

```
$ brew info python
python: stable 3.6.4
```

Would it be easier to add the brackets, so it works on both versions?

I've also proposed Homebrew PR to use `Formula["python@2"]` instead of `Formula["python"]`, see: Homebrew/homebrew-core/pull/25785

**Comment by jamessan** [comment]
> Would it be easier to add the brackets, so it works on both versions?

Well, you can't _just_ add the parens.  It would also require `from __future__ import print_function`.

> by default Formula["python"] in Homebrew (see: brew edit vim) points to Python 3.

Yeah, Homebrew switched what `Formula["python"]` installed at the start of March -- https://brew.sh/2018/01/19/homebrew-1.5.0/.

**Comment by mgedmin** [comment]
> Well, you can't just add the parens.

`print("a single string message")` works fine on both Python 2 and Python 3.  Python 2 sees a parenthesized expression, Python 3 sees a function call.

You need the `from __future__ import print_function` when you want to print to a file object, or when you want to print several comma-separated things.

**Comment by kenorb** [comment]
Adding curly brackets works for me in v2.7.10:

```
$ python2.7 -c "print('In file: ' + 'abc')"
In file: abc
$ python3 -c "print('In file: ' + 'abc')"
In file: abc
```

without adding any imports/futures.

**Comment by chrisbra** [comment]
and just adding parenthesis to the various print statements would make it work with python3? did someone test that the results are the same?

**Comment by jamessan** [comment]
Yes, it "works" in the simple case, but it's misleading because it isn't actually a function call.  It just makes it look like one so that Python3 doesn't trip over it.

Sure, it's possible to workaround the issue like that, but why not use the actual print function so you don't leave the next editor open to the pitfalls of it not actually being a function?

**Comment by nuko8** [comment]
Sorry for interrupting you all, but allow me to talk about the issue from a different point of view. 

@kenorb

>  -DFEAT_GUI_MAC

Judging from the source code, that GUI appears to be a legacy of the OS 9 era, and people got it to survive on Mac OS X by remaking it on top of Carbon as there was no better substitute for it those days.  It's rather for old Mac OS X versions, 10.1--10.5 (up to 10.8 at most), prior to a version that supports UNIX features enough to compile MacVim.

According to `src/Makefile`,  `dehqx.py` is used only for building that particular GUI.  So, unless your goal is to manage to build it semi-automatically through the package manager, it might be a good idea to make sure how much making it work with Python 3 will contribute to the goal.

**Comment by chrisbra** [comment]
closed by https://github.com/vim/vim/releases/tag/v8.0.1648
