### ISSUE TITLE
sudo prompt in command mode malforms status line

### ISSUE THREAD

**Issue by AvianY** [vim/vim#2758]
How to reproduce:
Start vim with vim -u NONE -i NONE -N
inside vim run:
:set laststatus=2
:args `sudo ls`
enter the password

The command works, but the prompt "password for $USER" will be overlayed on top of status line, with text and also the color vanishes.
The same problem happens with the plugin 'vim-airline'

**Comment by mattn** [comment]
markdown eat backtick
```
:args `sudo ls`
```

**Comment by chrisbra** [comment]
looks like a missing redraw, `Ctrl-L` fixes it, right?

**Comment by AvianY** [comment]
yes, it fixes it, but only for laststatus statusline, not for airline

**Comment by chrisbra** [comment]
Hm, a redraw might overwrite the 

    Illegal file name

Warning message, e.g. when you do in the source repository of Vim 

    :args `sudo echo src`

(it's a silly example, but shows the problem)
you get:

    srcs/ Illegal file name

But with an extra redraw, like in this patch:

```patch
diff --git a/src/os_unix.c b/src/os_unix.c
index 69fb29315..37cb110e6 100644
--- a/src/os_unix.c
+++ b/src/os_unix.c
@@ -6946,6 +6946,9 @@ mch_expand_wildcards(
        goto notfound;
     }

+    if (shell_style == STYLE_BT)
+       redraw_later_clear();   /* might have messed up screen */
+
     return OK;

 notfound:
```

you won't see that warning, because it has been overwritten by the redraw. 

So not sure what to do.

**Comment by brammool** [comment]
The backtick expsnsion command is not supposed to have output, other than what is redirected.
Redrawing the screen on every backtick expansion is overkill.
For the few cases it happens, just use CTRL-L.
If it happens often, find another way to do this.
