### ISSUE TITLE
Backtick expansion gives error when the expressions exits with a failed status code

### ISSUE THREAD

**Issue by AvianY** [vim/vim#2760]
the command in the shell:
find /etc -name ld.so.conf 
will give access errors, along with the file it found.

using this in vim like:
:args \`find /etc -name ld.so.conf\`
will give an error
"E79: Cannot expand wildcards"
"479: No match"

but if a "\\|\\| true" ending is used:
:args \`find /etc -name ld.so.conf \\|\\| true \`
it will execute correctly.

dealing with this is very cumbersome, because error messages are uninformative.
but even so, the only reason it failed is because of the exit code. The command would work otherwise.

**Comment by chrisbra** [comment]
I would say it is correct. If an error occurs, the user should know that one happened and only he can decide what to do with it (e.g. ignore it by using your `|| true ` )

**Comment by AvianY** [comment]
what I am saying, is that the errors are uninformative. I have no way of knowing why the error happened in the first place. Even worse, the errors in this case are a distraction from the real issue.

**Comment by chrisbra** [comment]
Well, the backtick expansion does never show the result of the command that is run. How should the error be shown? 

> the errors in this case are a distraction from the real issue

And the real issue is what?

**Comment by AvianY** [comment]
well, for one I think you make a great point. I have not found a way to see what the output of the backticks is. Something like :echo \`command\` would be cool I guess, but as of now it doesn't work.

> And the real issue is what?

The real issue is that the command finished with a failed exit code. This is what should be written instead.
Exyz: The expression returned with a failed exit code
or something like that. This would be more informative, or at least not distracting.

**Comment by AvianY** [comment]
PS: also, giving a hint in the help for backticks-expansion that such an error can occur and how to solve it (with the \|\| true if the user desires and is appropriate).

**Comment by AvianY** [comment]
But it's so strange, because other programs have no problem with the failed exit code.
If I do the following in the bash shell, there is no problem:
find /etc -name ld.so.conf | grep ld
So grep doesn't care if it received a failed exit code. Not just that. Grep itself will output a success code, so the whole command will return a success code.

What this means is, that if I type this into vim:
:args \`find /etc -name ld.so.conf \\| grep ld \` 
It will work, regardless of the failed exit code, that find gives, because grep gave success.

I don't know what to make of all this. The fact that the command without piping to grep **should** fail, but with piping to grep **shouldn't** is very confusing to me.
The command with grep is **no less** failed than the command with grep.

**Comment by k-takata** [comment]
(off topic)
It seems that you are not familiar with markdown, but you can use triple-backquotes to markup program codes. E.g.:

    ```
    :args `find /etc -name ld.so.conf \| grep ld`
    ```

will be shown as:

```
:args `find /etc -name ld.so.conf \| grep ld`
```

**Comment by chrisbra** [comment]
> find /etc -name ld.so.conf | grep ld

grep does not get the exit code. The shell will receive it. And as you note it, the shell will use the exit code of the last run command for a command that consists of pipes. That is specified somewhere in Posix or so, do not remember. Several shells have workarounds for that. See the `pipefail` option for bash for example.

The same is true in Vim. It runs the shell with the command mentioned. And since the shell does not receive the exit code, Vim doesn't either.

Having said this, it might be beneficial to have a way to see the result of the backtick expansion. Currently, setting the verbose option, one can at least see the command that has been executed. Make sure to set `:set verbose=4`

**Comment by AvianY** [comment]
Also, I have another proposal.
Say we instead use the following:
```
:args `=systemlist("find /etc -name ld.so.conf")`
```
This is on the other end of the spectrum. It will add all the lines to the arglist, even the error messages, this time with no error or warning from vim.
Maybe this is something that should be fixed at the same time?

**Comment by mattn** [comment]
```diff
diff --git a/src/os_unix.c b/src/os_unix.c
index b811ac3f4..87be1e1b0 100644
--- a/src/os_unix.c
+++ b/src/os_unix.c
@@ -6693,7 +6693,7 @@ mch_expand_wildcards(
     /*
      * execute the shell command
      */
-    i = call_shell(command, SHELL_EXPAND | SHELL_SILENT);
+    i = call_shell(command, SHELL_SILENT);
 
     /* When running in the background, give it some time to create the temp
      * file, but don't wait for it to finish. */
```
This change make display stderr.

**Comment by mattn** [comment]
Sorry, mistaken.

```diff
diff --git a/src/os_unix.c b/src/os_unix.c
index 2439c5e..6d7411d 100644
--- a/src/os_unix.c
+++ b/src/os_unix.c
@@ -4357,7 +4357,7 @@ mch_call_shell(cmd, options)
        {
            reset_signals();            /* handle signals normally */

-           if (!show_shell_mess || (options & SHELL_EXPAND))
+           if (!show_shell_mess /*|| (options & SHELL_EXPAND)*/)
            {
                int fd;
```

**Comment by chrisbra** [comment]
How about this documentation patch:
```patch
diff --git a/runtime/doc/editing.txt b/runtime/doc/editing.txt
index dc50455..a406769 100644
--- a/runtime/doc/editing.txt
+++ b/runtime/doc/editing.txt
@@ -424,6 +424,15 @@ On Unix and a few other systems you can also use backticks for the file name
 argument, for example: >
        :next `find . -name ver\\*.c -print`
        :view `ls -t *.patch  \| head -n1`
+This will let vim run the command given in backticks by your shell and use the
+standard output as input to the given vim command (error messages will be
+discarded).
+To see what shell command Vim is running, set the 'verbose' option to 4. When
+the command exits with a non-zero error code, an error message will be
+displayed and the vim command will be aborted. To prevent this, make the shell
+always return zero like so: >
+       :next `find . -name ver\\*.c -print \|\| true`
+
 The backslashes before the star are required to prevent the shell from
 expanding "ver*.c" prior to execution of the find program.  The backslash
 before the shell pipe symbol "|" prevents Vim from parsing it as command
```

**Comment by mattn** [comment]
If the file not found, new buffer name have the command name.

![25141047b367e479](https://user-images.githubusercontent.com/10111/37959833-06b8f072-31ef-11e8-9a19-5fb341dc9729.png)

**Comment by AvianY** [comment]
That documentation patch look promising, but there is still one more issue.
Namely, when the command fails because of non-zero exit code, it gives wrong/uninformative error messages.
```
E79: Cannot expand wildcards
479: No match
```
I propose that the error message is something else in this case, maybe something like I said in my previous post.
any suggestions?

**Comment by chrisbra** [comment]
> If the file not found, new buffer name have the command name.

So that is a bug:

```patch
diff --git a/runtime/doc/editing.txt b/runtime/doc/editing.txt
index dc5045531..a4067692a 100644
--- a/runtime/doc/editing.txt
+++ b/runtime/doc/editing.txt
@@ -424,6 +424,15 @@ On Unix and a few other systems you can also use backticks for the file name
 argument, for example: >
        :next `find . -name ver\\*.c -print`
        :view `ls -t *.patch  \| head -n1`
+This will let vim run the command given in backticks by your shell and use the
+standard output as input to the given vim command (error messages will be
+discarded).
+To see what shell command Vim is running, set the 'verbose' option to 4. When
+the command exits with a non-zero error code, an error message will be
+displayed and the vim command will be aborted. To prevent this, make the shell
+always return zero like so: >
+       :next `find . -name ver\\*.c -print \|\| true`
+
 The backslashes before the star are required to prevent the shell from
 expanding "ver*.c" prior to execution of the find program.  The backslash
 before the shell pipe symbol "|" prevents Vim from parsing it as command
diff --git a/src/os_unix.c b/src/os_unix.c
index b811ac3f4..69fb29315 100644
--- a/src/os_unix.c
+++ b/src/os_unix.c
@@ -6753,8 +6753,10 @@ mch_expand_wildcards(
     fseek(fd, 0L, SEEK_END);
     llen = ftell(fd);                  /* get size of temp file */
     fseek(fd, 0L, SEEK_SET);
-    if (llen < 0)
-       /* just in case ftell() would fail */
+    if (llen <= 0)
+       /* just in case ftell() would fail
+        * or file size is zero (shell
+        * did not return output) */
        buffer = NULL;
     else
        buffer = alloc(llen + 1);
@@ -6764,6 +6766,8 @@ mch_expand_wildcards(
        mch_remove(tempname);
        vim_free(tempname);
        fclose(fd);
+       if (llen == 0)
+           EMSG(_("EXXX: Shell returned no output"));
        return FAIL;
     }
     len = llen;
```

**Comment by brammool** [comment]
> > If the file not found, new buffer name have the command name.
> 
> So that is a bug:

Not really, backtick expansion resulting in an empty result should be
OK, it depends on how it is used.  E.g. to get an optional path.

The explanation for editing.txt is useful.  But the example doesn't
work.  Might depend on the shell.

I rephrased it a bit:

Vim will run the command in backticks using the 'shell' and use the standard
output as argument for the given Vim command (error messages from the shell
command will be discarded).
To see what shell command Vim is running, set the 'verbose' option to 4. When
the shell command returns a non-zero exit code, an error message will be
displayed and the Vim command will be aborted. To avoid this make the shell
always return zero like so: >
       :next `find . -name ver\\*.c -print \|\| true`

-- 
hundred-and-one symptoms of being an internet addict:
77. The phone company asks you to test drive their new PBX system

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
closed with https://github.com/vim/vim/commit/ab943431d8fcd856008a025b0e5652dd4b8007fc
