### ISSUE TITLE
maximize window using keyboard on Win 10

### ISSUE THREAD

**Issue by alan-isaac** [vim/vim#2761]
The standard Win 10 keystroke combination to maximize a window (Win key + up arrow) is not recognized by Vim 8.  (The Win key + down arrow to shrink a window is however recognized.)

**Comment by chrisbra** [comment]
Cannot reproduce. Works perfectly with vim 8.0.1451

**Comment by alan-isaac** [comment]
Confirm that today I cannot reproduce it either.  I will report back if I can find the conditions under which the problem occurs.  (This is not a hardware issue (e.g., sticky key); all other apps were responding normally.)

**Comment by chrisbra** [comment]
closing then.
