### ISSUE TITLE
Doesn't know why I can't execute some windows commands ?

### ISSUE THREAD

**Issue by cs86661** [vim/vim#2762]
OS: Windows 10
gVim: MS-Windows 32 Bit GUI 8.0.1645

I can execute "chgport /?" in Command Prompt (cmd.exe), but not in gVim's termial ?
```
'chport' is not recognized as an internal or external command,
operable program or batch file.
```

Windows Subsystem for Linux (bash.exe)
```
'bash' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by k-takata** [comment]
`chgport` is a 64-bit program and installed in `C:\Windows\System32`. However, the directory is not visible from a 32-bit program. Access to `C:\Windows\System32` is automatically redirected to `C:\Windows\SysWOW64` which is the system directory for 32-bit programs.
If you want to access the real `C:\Windows\System32` directory, you can use `C:\Windows\Sysnative`.
Please google with `wow64 fs redirection` for detail.

This is not a problem of Vim, so closing.
