### ISSUE TITLE
signcolumn triggers redraw, even with &lazyredraw

### ISSUE THREAD

**Issue by blueyed** [vim/vim#2763]
```vim
copen 20
set signcolumn=auto
set lazyredraw
sign define neomake_file_err
silent sign place 5000 line=1 name=neomake_file_err buffer=2
echom 'sleep: nothing should be drawn already'
sleep 1
resize 1
```

Use it with `vim -u NONE t.vim`, and then `:source %`.

Using `signcolumn=no` works around this (i.e. there is no redraw happening before the sleep).

I've noticed this with Neomake's custom quickfix, which adds signs to the entries, and then later vim-qf_resize resizing it: this causes flicker, since setting the signs triggers a redraw.

**Comment by brammool** [comment]
Daniel Hahler wrote:

> ```vim
> copen 20
> set signcolumn=auto
> set lazyredraw
> sign define neomake_file_err
> silent sign place 5000 line=1 name=neomake_file_err buffer=2
> echom 'sleep: nothing should be drawn already'
> sleep 1
> resize 1
> ```
> 
> Use it with `vim -u NONE t.vim`, and then `:source %`.
> 
> Using `signcolumn=no` works around this (i.e. there is no redraw happening before the sleep).
> 
> I've noticed this with Neomake's custom quickfix, which adds signs to the entries, and then later vim-qf_resize resizing it: this causes flicker, since setting the signs triggers a redraw.

Why do you say "nothing should be drawn"?  Is that because the buffer
does not exist?  Normally adding a first sign when 'signcolumn' is
"auto" causes the sign column to be displayed, thus require a redraw.

-- 
Ed's Radiator Shop: The Best Place in Town to Take a Leak.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by blueyed** [comment]
Sure, it should be drawn, but only later, i.e. after the window has been resized.
It seems to get redrawn due to placing a sign, but the sign itself (appears to) be drawn only later itself (but am not sure about that currently).

**Comment by brammool** [comment]
Daniel Hahler wrote:

> Sure, it should be drawn, but only later, i.e. after the window has
> been resized.
> It seems to get redrawn due to placing a sign, but the sign itself
> (appears to) be drawn only later itself (but am not sure about that
> currently).

Ehm, how can Vim know a resize will happen later?  Note that lazy redraw
checks if there is a typed character, it doesn't matter if there is more
Vim script to execute.  When checking for input it's possible that a
callback is invoked, which will then trigger a redraw, if one is
pending.

-- 
From "know your smileys":
 :^[/   mean-smiley-with-cigarette

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by blueyed** [comment]
> Note that lazy redraw checks if there is a typed character

But there is not in this case, is there?
Therefore `&lazyredraw` should have an effect at least, no?

**Comment by brammool** [comment]
Daniel Hahler wrote:

> > Note that lazy redraw checks if there is a typed character
> 
> But there is not in this case, is there?
> Therefore `&lazyredraw` should have an effect at least, no?

'lazyredraw' skips a redraw if there is still something to do.  Thus if
you type a mapping that makes several changes it only redraws once.
Thus you don't see anything until it is finished.

I suppose what you want is an option to not redraw while executing a
script or function.

-- 
From "know your smileys":
 O:-)	Saint

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chdiza** [comment]
According to `:h lazyredraw`, there is zero reason to expect a redraw in this case to be skipped unless one takes "macros" to cover sourced scripts.  But `:h macro` takes one to mappings, which are neither sourced scripts nor relevant to the present case.  So the asked-for behavior is not the documented behavior.

**Comment by chdiza** [comment]
It'd probably be a good idea to stress, at `:h lazyredraw`, that it doesn't apply to sourced scripts.

**Comment by blueyed** [comment]
Ah, yes.
I've assumed that &lazyredraw would also affect scripts/functions in general.

A workaround for Neomake is to hook into "FileType qf" as late as possible (via VimEnter, but maybe `after` should/could be used instead).
Another workaround could be wrapping things in a mapping (but that involves the `:lwindow` / `:cwindow` then already.

btw: using `cgetexpr 'foo'` instead of `sign place` does not trigger an early redraw already, so it might be possible to fix this issue by delaying the drawing of the signcolumn in the same way as the drawing of the list items.

**Comment by blueyed** [comment]
@chdiza
Yes.  And actually I would expect the redraw to be lazy here automatically, even without &lazyredraw (as it is for the list items itself).

**Comment by chrisbra** [comment]
I am closing this. There is an entry in the todo list now:
https://github.com/vim/vim/blob/d315cf551f1d15609c4d7cf724e471de55f5cdac/runtime/doc/todo.txt#L115-L116
that mentions to have a new option that skips redraws while executing a script
