### ISSUE TITLE
I got system("uname -s") == "Linux" equal 0

### ISSUE THREAD

**Issue by NSLog0** [vim/vim#2767]
I tried to binding the clipboard key by detecting the OS that I'm using in with this script 

```
if has("unix")
    if system("uname -s") == "Linux" 
         map <leader> e "+y
    else
         map <leader> e "*y
    endif
endif
``` 

It's always got  ```map <leader> e "*y``` because condition result is 0

What wrong with that? How do I fix that?

Thanks in advance.

**Comment by NSLog0** [comment]
I found the solution just use ```=~```  instead ```==```

**Comment by chrisbra** [comment]
Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here.
Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. Closing.

**Comment by k-takata** [comment]
Maybe `system("uname -s")` has a trailing newline.
Anyway, this is not a right place to ask user questions.
