### ISSUE TITLE
How can i solve these problems?

### ISSUE THREAD

**Issue by ghost** [vim/vim#2768]
I have already written into my .vimrc according to the requirements .But when i open the gvim.It said it has three errors.How can i solve these problem?
![1](https://user-images.githubusercontent.com/20223381/38172158-824e2df4-35d9-11e8-8ac5-a09a46525127.PNG)
![3](https://user-images.githubusercontent.com/20223381/38172159-82b4098a-35d9-11e8-95c1-c168b4370e37.PNG)

**Comment by chrisbra** [comment]
Please use single quotation marks for directories on Windows. Also this is a problem of a plugin, not of Vim. Closing. Please ask on the vim_use mailinglist, or vi.stackexchange.com or the plugins issue tracker for specific help with that plugin.
