### ISSUE TITLE
Indenting breaking block insert

### ISSUE THREAD

**Issue by chrisbra** [vim/vim#2778]
Take this file:
```vim
let a=[
  'eins',
  'zwei',
  'drei']
```
Start vim in a clean mode: `vim --clean -c 'set sw=2 et' file.vim`

Go to the beginning of the single quotation marks, block select them and try to add `backslashes in front of them, so that it will become a valid expression:

`ggjf'<C-V>2jI\ <ESC>`

The file will look now like this:

```vim
let a=[
      \ 'eins',
  'zwe\ 'eini',
  'dre\ 'eini']
```

I think the problem is that typing the `backslash` triggers the indent expression to kick in and the block insert code did not expect that to happen.

**Comment by vim-ml** [comment]
On Mi, 04 Apr 2018, Christian Brabandt wrote:

> Take this file:
> ```vim
> let a=[
>   'eins',
>   'zwei',
>   'drei']
> ```
> Start vim in a clean mode: `vim --clean -c 'set sw=2 et' file.vim`
> 
> Go to the beginning of the single quotation marks, block select them and try to add `backslashes in front of them, so that it will become a valid expression:
> 
> `ggjf'<C-V>2jI\ <ESC>`
> 
> The file will look now like this:
> 
> ```vim
> let a=[
>       \ 'eins',
>   'zwe\ 'eini',
>   'dre\ 'eini']
> ```
> 
> I think the problem is that typing the `backslash` triggers the indent expression to kick in and the block insert code did not expect that to happen.

Attached is a patch that fixes the issue including a test.

In addition, it fixes a misplaced comment.

Best,
Christian
-- 
"Was sind Tragödien anders als versifizierte Passionen solcher 
Leute, die sich aus den äußern Dingen ich weiß nicht was machen?"
		-- Goethe, Maximen und Reflektionen, Nr. 157
