### ISSUE TITLE
removing non-existing variable b:did_indent throws unnecessary error in rnoweb

### ISSUE THREAD

**Issue by floesche** [vim/vim#2779]
[rnoweb.vim](https://github.com/vim/vim/blob/master/runtime/indent/rnoweb.vim) throws error if b:did_indent is not set. The benefit of this error message is unclear.

One example to reproduce this is if [vimtex](https://github.com/lervag/vimtex) is used with the option `g:vimtex_indent_enabled=0`

**Comment by chrisbra** [comment]
closing as this seems to have been incorporated by the maintainer.
