### ISSUE TITLE
uninstall.exe broke Windows 10 when ran

### ISSUE THREAD

**Issue by Rimann91** [vim/vim#2781]
I installed VIM with the gvim80.exe. I ran everything as default but forgot to check the bat files so I unisnstalled using the uninstall.exe in the vim folder so that I could reinstall. After the uninstall completed I watched all desktop icons dissapear. Start menu no longer worked. After restart all settings were returned to default and all directories were still there but completely empty. No basic desktop applications such as `file explorer` appear in the `search windows` command bar. I have re imaged my machine and most of my data was backed up elsewhere so I am submitting this as an FYI not looking for a fix.

**Comment by chrisbra** [comment]
If uninstall.exe was that broken, I am sure we would have received a couple of more bug reports. I am closing this as unreproducible and not enough information.
