### ISSUE TITLE
[Termdebug] Is it possible to customize window positions?

### ISSUE THREAD

**Issue by echuraev** [vim/vim#2782]
Hi,

Today I tried to work with termdebug and it's awesome. But I don't like windows positions.
Is it possible to customize windows positions in config?
For example, I'd like to have something like that:
```
+------------------------------+
|                              |
|                              |
|                              |
|      Window with source      |
|                              |
|                              |
|                              |
+------------------------------+
|                              |
|        Window with gdb       |
|                              |
+------------------------------+
```

I'd like to have window with source on the top of the window and gdb window on the bottom. Also Window with source should be bigger than window with gdb.

Also, how can I restore window with source if I have closed it during debug? I tried to reopen buffer in new window, but it doesn't update cursor position when I go through code with gdb (I mean gdb command `next`).

**Comment by chrisbra** [comment]
You can move windows around as discussed in the help at `:h window-moving`. If you closed the source window, you probably have to restart the plugin.

**Comment by chrisbra** [comment]
I am closing this.
