### ISSUE TITLE
Access remote directory through SCP

### ISSUE THREAD

**Issue by Stephane-T** [vim/vim#2783]
VIM 8.x

VIM 7.x behaves differently.

Linux Debian 9.4

Terminal Xterm

Steps to reproduce using vim -NORC
:e scp://.......whatever a SSH remote account folder

First time, it works fine.

:e scp:// .... the same SSH remote account folder

Get error during the second call: --No lines in buffer--

In VIM 7, it just refresh as it's expected.

Issue has been feedback to Neovim first, as the bug is originated from vim, they advise to feedback here.

https://github.com/neovim/neovim/issues/8233

**Comment by brammool** [comment]
Stephane Tougard wrote:

> VIM 8.x
> 
> VIM 7.x behaves differently.
> 
> Linux Debian 9.4
> 
> Terminal Xterm
> 
> Steps to reproduce using vim -NORC
> :e scp://.......whatever a SSH remote account folder
> 
> First time, it works fine.
> 
> :e scp:// .... the same SSH remote account folder
> 
> Get error during the second call: --No lines in buffer--
> 
> In VIM 7, it just refresh as it's expected.
> 
> Issue has been feedback to Neovim first, as the bug is originated from vim, they advise to feedback here.
> 
> https://github.com/neovim/neovim/issues/8233

This is most likely a problem with the netrw plugin.
Have you tried getting the latest (beta) version?

-- 
hundred-and-one symptoms of being an internet addict:
106. When told to "go to your room" you inform your parents that you
     can't...because you were kicked out and banned.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Stephane-T** [comment]
Nope, I did not.

Neovim team confirms it's a problem with netrw, if you follow the link I gave in the bug report, they even give the commit in cause.

**Comment by chrisbra** [comment]
> Nope, I did not.

Well, then please do. It does provide valuable feedback to Charles how is the maintainer/developer of netrw. You'll find the latest version of netrw on his homepage: http://www.drchip.org/astronaut/vim/index.html#NETRW

Thanks.

**Comment by Stephane-T** [comment]
I installed the last version of vim from github.
I still got the same errur.

So I installed the last version of netrw on it and I got this error:
***sorry*** this version of netrw requires vim v7.4 with patch#1557
Error detected while processing BufReadCmd Auto commands for "scp://*":
E117: Unknown function: netrw#Nread
Press ENTER or type command to continue

Obviously, it's not possible to use netrw from your link and last version of vim.

**Comment by Stephane-T** [comment]
I could make work the latest vim from git (current version as of today) and the latest version of netrw (as downloaded from the above given link).

I'm still facing the same issue ("no lines in buffer" at the second attempt to reach a remote directory).

So currently, as I'm talking, the very last version of the software involved have still this bug.

**Comment by chreekat** [comment]
I can't reproduce this today. pi_netrw.txt says "For Vim version 8.1. Last change: 2017 Nov 03" and vim --version says "8.1 (2018 May 18)".
