### ISSUE TITLE
[patch] Switch the NSIS installer to MUI2

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vim/vim#279]
```
What steps will reproduce the problem?
1. start the NSIS installer on Windows

What is the expected output? What do you see instead?
the GUI looks outdated, but should not

What version of the product are you using? On what operating system?
Window 7 x64, Vim 7.4

Please provide any additional information below.
The patch and generated installer are attached. Only the console version runs 
in the installer as it was created with MinGW w64 32 bit compiler, but 
libstdc.dll is missing. Another workaround is that gvimext64.dll is just a copy 
of gvimext.dll.

```

Original issue reported on code.google.com by `tim.lebe...@gmail.com` on 9 Nov 2014 at 11:33

Attachments:
- [gvim74.zip](https://storage.googleapis.com/google-code-attachments/vim/issue-279/comment-0/gvim74.zip)
- [MUI2.patch](https://storage.googleapis.com/google-code-attachments/vim/issue-279/comment-0/MUI2.patch)

**Comment by k-takata** [comment]
The changes in this patch are now included in my PR #3501 in a similar way (with more enhancements).
So I close this.
