### ISSUE TITLE
Missing d, which vimtutor claims to exist

### ISSUE THREAD

**Issue by Ana06** [vim/vim#2792]
In [vimtutor](https://github.com/vim/vim/blob/master/runtime/tutor/tutor.utf-8#L199) is said:

>   NOTE: The letter  d  will appear on the last line of the screen as you type
> 	it.  Vim is waiting for you to type  w .  If you see another character
> 	than  d  you typed something wrong; press  <ESC>  and start over.

But I do not see any `d` appearing in any part of my screen. Is that correct? :thinking:

**Comment by grahamlyons** [comment]
I have the same experience. Vim works for me as expected but I see nothing displayed anywhere when I type `d`.

Could this be assuming that `set showcmd` is set somewhere?

**Comment by tonymec** [comment]
With `'showcmd'` set, the d appears near bottom right of the screen until you type an additional key (or keys) to tell Vim what you want to delete. 
With `'showcmd'` not set, the command prefix is not displayed.
`'showcmd'` is set on by `defaults.vim`, even on Linux, so you should see the partial command in a modern Vim if you either have no vimrc, or if your vimrc includes the line `runtime vimrc_example.vim`.

**Comment by k-takata** [comment]
When Vim is executed by the `vimtutor` command, `'showcmd'` is not set.
It might be better to set the option in the `vimtutor` script.

**Comment by k-takata** [comment]
`:help 'showcmd'` says that:

```
'showcmd' 'sc'		boolean	(Vim default: on, off for Unix,
				       Vi default: off, set in |defaults.vim|)
```

I wonder why it is off for Unix.

**Comment by k-takata** [comment]
Here is a patch:

```diff
--- a/src/vimtutor
+++ b/src/vimtutor
@@ -70,5 +70,5 @@ fi
 # The script tutor.vim tells Vim which file to copy
 $VIM -f -u NONE -c 'so $VIMRUNTIME/tutor/tutor.vim'
 
-# Start vim without any .vimrc, set 'nocompatible'
-$VIM -f -u NONE -c "set nocp" $TUTORCOPY
+# Start vim without any .vimrc, set 'nocompatible' and 'showcmd'
+$VIM -f -u NONE -c "set nocp showcmd" $TUTORCOPY
```

**Comment by chrisbra** [comment]
Yeah, perhaps better to have `showcmd` also be on by default for Vim on Unix.

**Comment by brammool** [comment]
> Yeah, perhaps better to have `showcmd` also be on by default for Vim
> on Unix.

It has been intentionally made to work that way.  I can't remember
why...


-- 
hundred-and-one symptoms of being an internet addict:
166. You have been on your computer soo long that you didn't realize
     you had grandchildren.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by tonymec** [comment]
Now that when there is no vimrc and no specific command-line switches, Vim will start with "sane defaults" by sourcing `defaults.vim`, which (among others) explicitly sets `'showcmd'` on all systems, it is a little weird that `:set nocompatible` would clear it on Unix but set it on all other systems, isn't it? I vote to remove the Unix exception to the default; or failing that, at least to `:set showcmd` when starting the vimtutor (like @k-takata 's above patch does) since the tutor's text seems to assume that `'showcmd'` is set.

**Comment by brammool** [comment]
Tony wrote:

> Now that when there is no vimrc and no specific command-line switches,
> Vim will start with "sane defaults" by sourcing `defaults.vim`, which
> (among others) explicitly sets `'showcmd'` on all systems, it is a
> little weird that `:set nocompatible` would clear it on Unix but set
> it on all other systems, isn't it? I vote to remove the Unix exception
> to the default; or failing that, at least to `:set showcmd` when
> starting the vimtutor (like @k-takata 's above patch does) since the
> tutor's text seems to assume that `'showcmd'` is set.

I feel uncomfortably changing this, not knowing why it was done this
way.  And we don't have users complaining, it's just we noticed an
inconsistency, which is not a very strong reason.

-- 
Microsoft says that MS-Windows is much better for you than Linux.
That's like the Pope saying that catholicism is much better for
you than protestantism.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
> I feel uncomfortably changing this, not knowing why it was done this way. And we don't have users complaining, it's just we noticed an inconsistency, which is not a very strong reason.

I went all the way back to vim 5.5 using the cvs repository. The first commit there already has this distinction in it (from 1999). Perhaps things have changed since then?
