### ISSUE TITLE
--startuptime overwrites existing files without warning

### ISSUE THREAD

**Issue by arp242** [vim/vim#2796]
I ran:

    $ vim --startuptime file

The expected behaviour was that Vim would start, load the buffer `file`, and show the startup performance report. The actual behaviours was to overwrite the contents of `file` with no warning.

I was able to restore the contents of `file` from my `~/.vim/tmp/backup`, but I think this is bad UX, and Vim should not overwrite existing files when using `--startuptime`.

**Comment by arp242** [comment]
Adding to that, I'll be happy to write a patch if people agree.

**Comment by chdiza** [comment]
That is not the expected behavior.  It is the documented behavior.  See `:h --startuptime`.

**Comment by chdiza** [comment]
`:s/expected/unexpected`

**Comment by chdiza** [comment]
Even in `vim --help`, it's clear that what you call expected is in fact to be unexpected.

**Comment by lifepillar** [comment]
>The actual behaviours was to overwrite the contents of file with no warning.

`--startuptime` should always *append* to an existing file, so even if you pass the wrong file, the mistake shouldn't be fatal.

**Comment by chrisbra** [comment]
Closing this as documented behaviour. If anyone wants to change the behaviour of making `--startuptime` append instead of truncating, feel free to post a patch/PR.

**Comment by lifepillar** [comment]
@chrisbra  My comment above was not clear enough (it was not a desideratum): `--startuptime` is already append-only (and, as @chdiza has said, that is the documented behaviour of that option). I guess the OP was complaining that Vim *modifies* (rather than *truncates*) the content of an existing file without warning.

**Comment by chrisbra** [comment]
ah okay, did miss that indeed.
