### ISSUE TITLE
Incorrect fixed-height window behavior with terminal

### ISSUE THREAD

**Issue by mrbiggfoot** [vim/vim#2798]
Found it in `neovim` (here's the [original issue](https://github.com/neovim/neovim/issues/8096)) but it also exists in the latest (as of today) version of `vim`. The repro steps are slightly different from neovim:
```
vim -u NORC
:terminal
less <file_with_enough_content_to_fill_the_window>
<C-\><C-n>:set winfixheight
:belowright 10new
```
The terminal window content gets damaged by the new window creation: the terminal output height becomes smaller, which should not happen.

**Comment by chrisbra** [comment]
I suppose this depends on the current height of your terminal window. Note, that the help for ['winfixheight'](http://vimhelp.appspot.com/options.txt.html#%27winfixheight%27) mentions this explicitly:

> The height may be changed anyway when running out of room.

So this is expected to a certain extend.

**Comment by mrbiggfoot** [comment]
> So this is expected to a certain extend.

@chrisbra please spend 30 seconds of your time to actually try the steps.

**Comment by chrisbra** [comment]
> @chrisbra please spend 30 seconds of your time to actually try the steps.

@mrbiggfoot  thanks for blaming me. I did even spend half an hour to do what you said and research a bit. And I even read the neovim issue and PR. But either your steps are incomplete or the bug did not happen for me, except for reducing the terminal window size, which as said seems to be expected from the documentation of the 'winfixheight' setting.

**Comment by mrbiggfoot** [comment]
@chrisbra I apologize then. What happens on my setup (the very latest vim on CentOS 6.9) every time, is that the window height stays the same, as intended, but the terminal output gets truncated. There's a screenshot in the neovim bug comments that represents what's happening.

**Comment by mrbiggfoot** [comment]
Just verified the steps again. Reproducible 100%.

**Comment by chrisbra** [comment]
Sorry, I have to apoligize. I read the steps to briefly missing the `less` part. I did fill the window completly but did not use less. So no wonder I could not verify it. Sorry. So this only happens with external commands running in the terminal.

I just tested and did try to send `SIGWINCH` to the terminal shell and less, but that did not fix it.

**Comment by brammool** [comment]
Andrew Pyatkov wrote:

> Found it in `neovim` (here's the [original issue](https://github.com/neovim/neovim/issues/8096)) but it also exists in the latest (as of today) version of `vim`. The repro steps are slightly different from neovim:
> ```
> vim -u NORC
> :terminal
> less <file_with_enough_content_to_fill_the_window>
> <C-\><C-n>:set winfixheight
> :belowright 10new
> ```
> The terminal window content gets damaged by the new window creation:
> the terminal output height becomes smaller, which should not happen.

I am unable to reproduce the problem.
The screenshot on the neovim issue suggests you have 'splitbelow' set.
Perhaps you also have other options set?  Try starting with "vim
--clean".

-- 
        Very funny, Scotty.  Now beam down my clothes.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mrbiggfoot** [comment]
@brammool reproducible with "vim --clean" too. The windows arrangement in the neovim screenshot is slightly different. Here's the screenshot from vim repro:

<img width="1280" alt="screen shot 2018-04-13 at 12 08 32 pm" src="https://user-images.githubusercontent.com/12175496/38753515-7cfb353e-3f13-11e8-979a-854fd22b0747.png">

See the lines in the terminal window that start with `~`. They appear after the middle window creation. They should not be there.

**Comment by mrbiggfoot** [comment]
Please follow the steps literally. You can use e.g. `less <vim_repo>/src/terminal.c` to showcase the issue.

**Comment by brammool** [comment]
> @brammool reproducible with "vim --clean" too. The windows arrangement
> in the neovim screenshot is slightly different. Here's the screenshot
> from vim repro:
> <img width="1280" alt="screen shot 2018-04-13 at 12 08 32 pm" src="https://user-images.githubusercontent.com/12175496/38753515-7cfb353e-3f13-11e8-979a-854fd22b0747.png">

Nope, can't reproduce that.  Please give more info.  What terminal are
you using?  Vim version?

Ah wait, you are still in Terminal-Normal mode.  As soon as you go back
to Terminal-Job mode it's all OK.

-- 
hundred-and-one symptoms of being an internet addict:
171. You invent another person and chat with yourself in empty chat rooms.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mrbiggfoot** [comment]
>  As soon as you go back to Terminal-Job mode it's all OK.

I can confirm it. As soon as I switch back to terminal window and enter insert mode, the content is restored. But why should it be needed? Still seems like a bug to me.

**Comment by mrbiggfoot** [comment]
Verified. Thanks @brammool !

**Comment by mrbiggfoot** [comment]
This issue is not fully fixed. The bug still exists in this sequence, without setting winfixheight (latest vim, commit 451fc7b954906069f1830a8092ad85616049a828):
```
vim --clean
:terminal ++rows=10
less <vim_repo>/src/terminal.c
<C-\><C-n>:below 20new
```

Result:
<img width="1280" alt="screen shot 2018-04-27 at 10 49 20 pm" src="https://user-images.githubusercontent.com/12175496/39392595-6f9e8624-4a6d-11e8-85c5-cfab990d7ff0.png">

**Comment by brammool** [comment]
I suppose 'equalalways' is set, thus this would be expected.

**Comment by mrbiggfoot** [comment]
@brammool the issue is not about window sizes, it's about terminal content not matching the window size. See the lines starting with `~` in the terminal window on the screenshot, they should be filled with the terminal buffer content.

**Comment by brammool** [comment]
> @brammool the issue is not about window sizes, it's about terminal
> content not matching the window size. See the lines starting with `~`
> in the terminal window on the screenshot, they should be filled with
> the terminal buffer content.

The terminal window is still in Terminal-normal mode, thus only shows
what the terminal showed before.  Only when you switch to Terminal-job
mode will the window go back to showing the job output.  Hopefully the
SIGWINCH is handled and the job will fill all the space.  Looks like
this works for "less".

-- 
GALAHAD: No, please.  Please! I can defeat them!  There's only a hundred.
GIRLS:   He will beat us easily.  We haven't a chance.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by JulianDPR** [comment]
> @brammool reproducible with "vim --clean" too. The windows arrangement in the neovim screenshot is slightly different. Here's the screenshot from vim repro:
> 
> <img alt="screen shot 2018-04-13 at 12 08 32 pm" width="1280" src="https://user-images.githubusercontent.com/12175496/38753515-7cfb353e-3f13-11e8-979a-854fd22b0747.png">
> 
> See the lines in the terminal window that start with `~`. They appear after the middle window creation. They should not be there.

I solved the same problem with the next command ":bel 10new |term"
