### ISSUE TITLE
Problem with :scriptnames, :history, etc.

### ISSUE THREAD

**Issue by ashishtibrewal** [vim/vim#2799]
When you run `:scriptnames`, `:history`, etc. and get to the end of the list by pressing the _f_ key, pressing _b_ prints _Press ENTER or type command to continue_ instead of moving up to the previous page. The following screenshot might be helpful:
![vim-issue](https://user-images.githubusercontent.com/8990952/38720882-897c2672-3f15-11e8-952a-3bfeccc078f0.png)
Any suggestions/help to fix this would be much appreciated. Thanks. :)

**Comment by tonymec** [comment]
Works for me in Huge Vim 8.0.1704 with GTK2 GUI, both in GUI mode and in console mode.

Which version of Vim are you using? On which OS? Console or GUI? If GUI on Unix-like OS, which GUI flavour? (See the top 5 or so lines in the output of the `:version` command)

**Comment by chrisbra** [comment]
I think this was fixed with https://github.com/vim/vim/releases/tag/v7.4.1876
