### ISSUE TITLE
Get rid of Python 2

### ISSUE THREAD

**Issue by dertuxmalwieder** [vim/vim#2801]
Python 2 is slowly being phased out with Jan 01, 2020 being the day of its death (meaning: no further upstream support whatsoever). As many Linux distributions and other operating systems slowly begin to remove things related to Python 2, it might be recommendable to drop Python 2 support from Vim as well, especially since you removed "old" operating systems a while ago for very similar reasons.

That should be doable by (mostly) just deleting `if_python.c` and *grep*ing for `ifdef PYTHON` (Makefiles) and `FEAT_PYTHON` (the actual sources) as far as I could see.

**Comment by georgevreilly** [comment]
I strongly disagree. While I've often been bemused at Vim's support for very old systems—witness that the support for Win9x and Win3.1 was only removed a couple of years ago or that Python 1.4 support was only just removed—removing Python 2 support is very much premature.

I'm still running Python 2 code in production. It's only in the last six months that I've been able to use Python 3 for new projects. I am far from alone in this. I recommend waiting until at least 2022 before removing Python 2 support.

**Comment by mcepl** [comment]
Please, don't. I like my [vim8 builds](https://copr.fedorainfracloud.org/coprs/mcepl/vim8/builds/) on RHEL-7. I know that removing support for Python 1.4 now has been ridiculous, but unless there are some compelling reasons, there is still some life in Python 2. Yes, I hate it, yes, I blame RH management for the ridiculous decision not to include Python 3 in RHEL-7 proper (I don't want to have vim dependent on EPEL packages, there are too many people who don't use EPEL), but this is the world we live in.

**Comment by dertuxmalwieder** [comment]
Clarification: This was not meant to be done immediately.

**Comment by mcepl** [comment]
> Clarification: This was not meant to be done immediately.

Then it shouldn't clutter the issue tracker. That should be used for actionable issues, for the long term plans there should be some TODO, or something. 569 issues is just too many for one human being to deal with.

**Comment by chrisbra** [comment]
yes, I agree. Let's see if the following works.

**Comment by chrisbra** [comment]
okay that did not work. Closing anyhow. Please report again in 3 years ...
