### ISSUE TITLE
How to compile Vim 8 under Windows without asked to run link.sh?

### ISSUE THREAD

**Issue by jiangjianshan** [vim/vim#2806]
Hello,

     Today when I try to compile Vim 8 as before using the build command. But immediately the build process will ask to find a program to run link.sh. I think this link.sh is no need for Windows. How to compile Vim 8 without asked to run link.sh?

**Comment by chrisbra** [comment]
please give exact steps to reproduce. Also please note, this is not a support forum but used for specific bug reports for Vim.

**Comment by jiangjianshan** [comment]
Hello @chrisbra , 

    My operation system is Windows 7 sp1 x64. When I use the compiler inside Windows SDK v7.0 to build Vim 8.0 by the build.cmd I wrote. During the build process, it will throw out the pop up window to ask to find a program to run link.sh.

![image](https://user-images.githubusercontent.com/20179047/38798158-5db113ba-4193-11e8-8327-18d467fcf9d7.png)

    Here is the build.cmd I'm using. It work.
------------------------- start : build.cmd ----------------------
@echo off
@rem to build big Vim with OLE, Perl, Python, Ruby and Tcl

set INCLUDE=D:\GnuWin64\include;D:\Lua\include;D:\Ruby\include;%INCLUDE%
set LIB=D:\GnuWin64\lib;D:\Lua\lib;D:\Ruby\lib;%LIB%
set TOOLDIR=D:\
set INSTALL_DIR=D:\Vim
set VIM_SRC_DIR=E:\Gits\vim
set PLUG_MGR=D:\Vim\vimfiles\autoload\plug.vim
::set SDK_INCLUDE_DIR=C:\Program Files\Microsoft SDKs\Windows\v7.0\Include

cd /d %~dp0

@rem uninstall previous version if it exist
if exist %INSTALL_DIR%\Vim80 (
    cd /d %INSTALL_DIR%\Vim80
    uninstal
)

if exist %VIM_SRC_DIR% (
  cd /d %VIM_SRC_DIR%
  git fetch --all
  git reset --hard origin/master
) else (
  echo "Downloading Vim ..."
  git clone https://github.com/vim/vim.git E:\Gits\vim
)

cd /d %VIM_SRC_DIR%\src

if exist .\ObjCULYHTRAMD64 rmdir /s /q .\ObjCULYHTRAMD64
if exist .\ObjGOULYHTRAMD64 rmdir /s /q .\ObjGOULYHTRAMD64

@rem build for no-GUI version
nmake -f Make_mvc.mak CPU=AMD64 FEATURES=HUGE debug=no GUI=no MBYTE=yes IME=yes DYNAMIC_IME=yes GIME=yes CSCOPE=yes ICONV=yes GETTEXT=yes NETBEANS=yes OPTIMIZE=MAXSPEED SNIFF=yes POSCRIPT=yes PERL=%TOOLDIR%Perl DYNAMIC_PERL=yes PERL_VER=524 PYTHON=%TOOLDIR%python27 DYNAMIC_PYTHON=yes PYTHON_VER=27 PYTHON3=%TOOLDIR%python35 DYNAMIC_PYTHON3=yes PYTHON3_VER=35 LUA=%TOOLDIR%Lua DYNAMIC_LUA=yes LUA_VER=53 RUBY=%TOOLDIR%Ruby DYNAMIC_RUBY=yes RUBY_VER=25 RUBY_VER_LONG=2.4.0 RUBY_PLATFORM=x64-mswin64_90 TCL=%TOOLDIR%Tcl TCL_VER=86 TCL_VER_LONG=8.6 DYNAMIC_TCL=yes %1

@rem build for GUI version
nmake -f Make_mvc.mak CPU=AMD64 FEATURES=HUGE debug=no GUI=yes OLE=yes MBYTE=yes IME=yes DYNAMIC_IME=yes GIME=yes CSCOPE=yes ICONV=yes GETTEXT=yes NETBEANS=yes OPTIMIZE=MAXSPEED SNIFF=yes POSCRIPT=yes PERL=%TOOLDIR%Perl DYNAMIC_PERL=yes PERL_VER=524 PYTHON=%TOOLDIR%python27 DYNAMIC_PYTHON=yes PYTHON_VER=27 PYTHON3=%TOOLDIR%python35 DYNAMIC_PYTHON3=yes PYTHON3_VER=35 LUA=%TOOLDIR%Lua DYNAMIC_LUA=yes LUA_VER=53 RUBY=%TOOLDIR%Ruby DYNAMIC_RUBY=yes RUBY_VER=25 RUBY_VER_LONG=2.4.0 RUBY_PLATFORM=x64-mswin64_90 TCL=%TOOLDIR%Tcl TCL_VER=86 TCL_VER_LONG=8.6 DYNAMIC_TCL=yes %1

@rem Copy the "runtime" files into "Vim80"
xcopy /I /Y /F /E ..\.\runtime\* %INSTALL_DIR%\Vim80

@rem Copy the new binaries into the "Vim80" directory
xcopy /I /Y /F *.exe %INSTALL_DIR%\Vim80
xcopy /I /Y /F vimtbar.dll %INSTALL_DIR%\Vim80
xcopy /I /Y /F .\GvimExt\gvimext.dll %INSTALL_DIR%\Vim80\GvimExt64
xcopy /I /Y /F .\xxd\xxd.exe %INSTALL_DIR%\Vim80

@rem Copy vimtutor into "Vim80"
xcopy /I /Y /F ..\vimtutor.* %INSTALL_DIR%\Vim80

@rem install vim
cd /d %INSTALL_DIR%\Vim80
::install -install-popup -install-openwith -add-start-menu -install-icons -create-directories vim -register-OLE
::del /F /S /Q "C:\Users\public\Desktop\gVim Easy 8.0.lnk"
::del /F /S /Q "C:\Users\public\Desktop\gVim Read only 8.0.lnk"

install

xcopy /F /Y E:\Releases\_vimrc %INSTALL_DIR%
xcopy /F /Y E:\Releases\.ycm_extra_conf.py %INSTALL_DIR%

@rem Update the plugins

if exist %PLUG_MGR% (
   vim +PlugUpgrade +qall
   vim +PlugUpdate +qall
) else (
   curl -fLo %INSTALL_DIR%\vimfiles\autoload\plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
   vim +PlugInstall +qall
)

cd /d %~dp0
-------------------------- end : build.cmd -------------------------

**Comment by jiangjianshan** [comment]
Hello @chrisbra ,

    The reason maybe the Makefile include the below line "sh $(srcdir)/link.sh". I think it should be excluded at Windows system or using another way to do the same job.
![image](https://user-images.githubusercontent.com/20179047/38798847-5b6388ac-4195-11e8-8819-38e9702bbbf7.png)

**Comment by k-takata** [comment]
Maybe your `PATH` setting is wrong. If you prepend a directory of GNU-like tools before the MSVC directories, it might cause the trouble.

**Comment by tonymec** [comment]
@jiangjianshan : the line you showed (starting `$(VIMTARGET):` and ending `sh $(srcdir)/link.sh` is not from the `Make_mvc.mak` which your earlier post shows as being in use (and which is the correct one to use for MS Visual Studio). The corresponding line (at `Make_mvc.mak` lines 1204-1213) goes as follows:
``` make
$(VIM).exe: $(OUTDIR) $(OBJ) $(GUI_OBJ) $(CUI_OBJ) $(OLE_OBJ) $(OLE_IDL) $(MZSCHEME_OBJ) \
		$(LUA_OBJ) $(PERL_OBJ) $(PYTHON_OBJ) $(PYTHON3_OBJ) $(RUBY_OBJ) $(TCL_OBJ) \
		$(CSCOPE_OBJ) $(TERM_OBJ) $(NETBEANS_OBJ) $(CHANNEL_OBJ) $(XPM_OBJ) \
		version.c version.h
	$(CC) $(CFLAGS_OUTDIR) version.c
	$(link) $(LINKARGS1) -out:$(VIM).exe $(OBJ) $(GUI_OBJ) $(CUI_OBJ) $(OLE_OBJ) \
		$(LUA_OBJ) $(MZSCHEME_OBJ) $(PERL_OBJ) $(PYTHON_OBJ) $(PYTHON3_OBJ) $(RUBY_OBJ) \
		$(TCL_OBJ) $(CSCOPE_OBJ) $(TERM_OBJ) $(NETBEANS_OBJ) $(CHANNEL_OBJ) \
		$(XPM_OBJ) $(OUTDIR)\version.obj $(LINKARGS2)
	if exist $(VIM).exe.manifest mt.exe -nologo -manifest $(VIM).exe.manifest -updateresource:$(VIM).exe;1
```
As you can see, it is totally different. The makefile extract you showed (with `-o objects/version.o` ending in .o) is for a Unix-like platform. So how come that Unix-like makefile got invoked?

Best regards,
Tony.

**Comment by jiangjianshan** [comment]
hello @tonymec ,

     I have just look very careful for the Mak_mvc.mak, when it want to generate the gvimext.dll, it will invoke src/Makefile, which I think will invoke the command "sh $(srcdir)/link.sh". This should be a bug for Mak_mvc.mak.

![image](https://user-images.githubusercontent.com/20179047/38843499-ccd8a8d2-4221-11e8-8a99-2ec18d333553.png)

**Comment by k-takata** [comment]
No, it's wrong.
See the line 1245. It changes the current directory to `GvimExt`. So, the `Makefile` is actrually `src\GvimExt\Makefile`.
Again, please check your `PATH` setting.

**Comment by k-takata** [comment]
Could you also show the results of the following commands?

```
echo %PATHEXT%
where link
```

**Comment by tonymec** [comment]
Since the current directory has been changed to `GvimExt`, the `Makefile` (with no explicit directory) is indeed `src/GvimExt/Makefile`; the first line of that makefile is
``` make
# Makefile for GvimExt, using MSVC
```
and it makes `gvimext.dll` by means of the following rules (at lines 59sqq):
``` make
all: gvimext.dll

gvimext.dll:    gvimext.obj	\
		gvimext.res
	$(link) $(lflags) -dll -def:gvimext.def -base:0x1C000000 -out:$*.dll $** $(olelibsdll) shell32.lib comctl32.lib -subsystem:$(SUBSYSTEM)
	if exist $*.dll.manifest mt -nologo -manifest $*.dll.manifest -outputresource:$*.dll;2

gvimext.obj: gvimext.h

.cpp.obj:
	$(cc) $(cflags) -DFEAT_GETTEXT $(cvarsmt) $*.cpp

gvimext.res: gvimext.rc
	$(rc) /nologo $(rcflags) $(rcvars)  gvimext.rc
```
No `link.sh` there either.

I notice that in your `build.cmd` you invoke `nmake` twice in succession, each time to make something named `%1`. Doesn't that overwrite your non-GUI version with your GUI version? And with what argument to you invoke `build.cmd`?

Best regards,
Tony.

**Comment by jiangjianshan** [comment]
hello @k-takata ,
    Here is the command output:
![image](https://user-images.githubusercontent.com/20179047/38844949-2b95f446-4228-11e8-9070-7e70582b38d4.png)

    Here is the PATH setting when using "echo %PATH%" on Windows SDK v7.0 command prompt.
---------------------------------------- begin -----------------------------------------
C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\Bin\amd64;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\vcpackages;C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE;C:\Program Files\Microsoft SDKs\Windows\v7.0\Bin\x64;C:\Program Files\Microsoft SDKs\Windows\v7.0\Bin;C:\Windows\Microsoft.NET\Framework64\v3.5;C:\Windows\Microsoft.NET\Framework\v3.5;C:\Windows\Microsoft.NET\Framework64\v2.0.50727;C:\Windows\Microsoft.NET\Framework\v2.0.50727;C:\Program Files\Microsoft SDKs\Windows\v7.0\Setup;D:\GnuWin64\bin;C:\Program Files (x86)\tbclient;D:\TBPublishingPoint\_admin\bin;C:\Windows\System32;C:\Windows;D:\Python27\;D:\Python27\Scripts;D:\Python35\Scripts\;D:\Python35\;C:\Program Files\Dell\DW WLAN Card;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\UCRT\;C:\Program Files\Intel\UCRT\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\WIDCOMM\Bluetooth Software\;C:\Program Files\WIDCOMM\Bluetooth Software\syswow64;D:\Cadence\SPB_16.6\tools\pcb\bin;D:\Cadence\SPB_16.6\tools\bin;D:\Cadence\SPB_16.6\tools\libutil\bin;D:\Cadence\SPB_16.6\tools\fet\bin;D:\Cadence\SPB_16.6\tools\specctra\bin;D:\Cadence\SPB_16.6\tools\pspice;D:\Cadence\SPB_16.6\tools\capture;D:\Cadence\SPB_16.6\openaccess\bin\win32\opt;D:\Program Files\CMake\bin;D:\Program Files\Git\cmd;D:\Program Files\TortoiseSVN\bin;D:\Program Files (x86)\MATLAB\R2008a\bin\win32;D:\Program Files\MATLAB\R2015b\bin;D:\Program Files (x86)\MATLAB\R2008a\bin;D:\Tasking\1.5r3\bin;D:\Program Files (x86)\VisualSVN Server\bin;D:\PROGRA~1\INTEGR~1\Toolkit\mksnt;C:\Program Files\Java\jdk1.8.0_162\bin;C:\Program Files\Java\jre1.8.0_162\bin;C:\ProgramData\Oracle\Java\javapath;D:\Program Files (x86)\Integrity\ILMClient11\bin;C:\Program Files (x86)\Common Files\ETAS\3rdParty4.0\;C:\Program Files (x86)\Vector vFlash 2.5\Bin; 
------------------------------------------------ end ---------------------------------------------

     I have put "D:\GnuWin64\bin" at the first position of PATH environment, but inside the Windows SDK v7.0 x64 command prompt, it is behind the path of MSVC.

Best regards,
jiangjianshan

**Comment by jiangjianshan** [comment]
hello @tonymec ,

    The way I use "build.cmd" is here. There is no argument input for "build.cmd".
![image](https://user-images.githubusercontent.com/20179047/38845285-6f14fe14-4229-11e8-9be6-a09088dc131b.png)

**Comment by k-takata** [comment]
Then, what does `echo %LINK%` show?

**Comment by jiangjianshan** [comment]
Hello @k-takata ,

    Here is the command output:

![image](https://user-images.githubusercontent.com/20179047/38846049-e4db8df4-422c-11e8-8ed7-33b0b796f6d1.png)

   It seems like the %LINK% is not defined.

**Comment by k-takata** [comment]
I think that some settings related to GnuWin (or some other Unix-like tools) might conflict with MSVC, but I haven't found such settings yet.

I checked your comments again. https://github.com/vim/vim/issues/2806#issuecomment-381522886

> Here is the build.cmd I'm using. It work.

Does it work? Then, what doesn't work?

Could you also show a few lines above in [this image](https://user-images.githubusercontent.com/20179047/38798158-5db113ba-4193-11e8-8327-18d467fcf9d7.png)?
In my case, it starts with:

```
        link /RELEASE /nologo /subsystem:windows /opt:ref /LTCG:STATUS -out:gvim.exe .\ObjGXULYHRi386\arabic.obj  
```

(when compiling 32-bit gvim.exe)

**Comment by jiangjianshan** [comment]
Hello @k-takata 
    This “build.cmd” I have use since Vim 7 until Vim 8.1645, it work.

    For the build process output when pop up the window to ask a program to run link.sh, it is here:
![image](https://user-images.githubusercontent.com/20179047/38847185-ed0427ec-4232-11e8-8dfb-f197df54ae33.png)
![image](https://user-images.githubusercontent.com/20179047/38847189-f2db9dda-4232-11e8-8085-d81ca0a2babc.png)

**Comment by k-takata** [comment]
What does happen when you execute `link` from command prompt manually?

**Comment by jiangjianshan** [comment]
Hello @k-takata ,

    When I type “link” from Windows SDK v7.0 x64 command prompt, it is exactly the linker from msvc.
![image](https://user-images.githubusercontent.com/20179047/38848633-b01290fa-423a-11e8-9c8e-ec6f99e11d22.png)

**Comment by k-takata** [comment]
Even if you executed it in the `src` directory?

**Comment by jiangjianshan** [comment]
Hello @k-takata ,

    If I execute it in the src directory, I have found it has different behavior. It is look like
![image](https://user-images.githubusercontent.com/20179047/38849155-6086d87c-423d-11e8-966c-10c77bff1415.png)

    The pop up windows ask to find a program to run link.sh will be directly appear.

    How can I solve it?

**Comment by k-takata** [comment]
Ah, okay. That is what I expected.
It is caused by the setting of `PATHEXT`.
Please try removing `.sh` from `PATHEXT`.
E.g.

```
set PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW
```

**Comment by jiangjianshan** [comment]
Hello @k-takata ,

    I put one line into “build.cmd” as below showing:
![image](https://user-images.githubusercontent.com/20179047/38850315-7e1884de-4243-11e8-8aec-22a264fefbc7.png)

    It works fine.

    Thanks very much @k-takata . Also thanks @tonymec .

Best regards,
jiangjianshan

**Comment by k-takata** [comment]
```
set PATHEXT=%PATHEXT:.sh;=%
```
might be better for removing an extra `;`.

Anyway, I close this because it is solved.

**Comment by jiangjianshan** [comment]
Hello @k-takata 

   OK, thank for hint.

**Comment by chrisbra** [comment]
I suppose the MS SDK supported link is actually a link.exe? So why not use `link.exe` in the Makefile directly so we do not depend on the %PATHEXT% setting?

**Comment by chrisbra** [comment]
BTW: shouldn't the first entry `.exe` in %PATHEXT% have priority over the `.sh` extension? Why does it use then link.sh and not link.exe? Is that because of the case sensitivity?

**Comment by k-takata** [comment]
We use `$(link)` in `Make_mvc.mak`, and it is defined as `link = link` in `Win32.mak` or in the above part of `Make_mvc.mak`. I don't think this is wrong.

> Why does it use then link.sh and not link.exe?

When searching a command, the command in the current directory with the PATHEXT extension is searched, then the first directory in the PATH with the PATHEXT extension, then 2nd directory, and so on. Therefore, `link.sh` in the current directory has a higher priority than `link.exe` in the PATH.

**Comment by chrisbra** [comment]
> We use $(link) in Make_mvc.mak, and it is defined as link = link in Win32.mak or in the above part of Make_mvc.mak. I don't think this is wrong.

Perhaps using `link = link.exe` would make it more explicit?

> When searching a command, the command in the current directory with the PATHEXT extension is searched, then the first directory in the PATH with the PATHEXT extension, then 2nd directory, and so on. Therefore, link.sh in the current directory has a higher priority than link.exe in the PATH.

Makes sense thanks.

**Comment by k-takata** [comment]
Well, the following patch should work when `Win32.mak` is not included.
However, it is defined as `link = link` when `Win32.mak` is included.

```diff
--- a/src/Make_mvc.mak
+++ b/src/Make_mvc.mak
@@ -272,7 +272,7 @@ MAKEFLAGS_GVIMEXT = DEBUG=yes
 !elseif "$(USE_WIN32MAK)"=="yes"
 !include <Win32.mak>
 !else
-link = link
+link = link.exe
 !endif
 
 
```

Not sure whether this patch is worth to be included.
