### ISSUE TITLE
Shift (>>) doesn't work as expected 

### ISSUE THREAD

**Issue by glacambre** [vim/vim#2809]
Hi,

On `353eeeaca`, using `>>` while on the `#pragma` line in the following C source code doesn't move the line to the right.
```c
void main () {
#pragma acc parallel
    for (int i = 0; i < 10; ++i) {
        i += i;
    }
}
```
However, I expected my source code to look like this (provided that my shiftwidth setting is set to 4):
```c
void main () {
    #pragma acc parallel
    for (int i = 0; i < 10; ++i) {
        i += i;
    }
}
```
In my opinion this behavior doesn't make sense. If I wanted to use vim's automatic indentation, I would have used `==`. When I use `>>`, I want vim to unconditionally add indentation to the current line.

Is this a bug or am I mistaken about what `>>` does?

**Comment by chrisbra** [comment]
What Vim version? I think this has been fixed with a later 7.4. or early 8.0 version. (The idea originally was that c compiler precompiler statements are only allowed when they start at the beginning of the line.

**Comment by chrisbra** [comment]
Ah, I remember. It was actually patch [7.4.069](https://github.com/vim/vim/commit/6bcbcc59be58d0c3b3cd53ac105c6eb7d0b87f06). So to make this work, add `:set cino+=#1` or something similar. See also the help at `:h cino-#`. Closing this.

**Comment by glacambre** [comment]
`:set cino+=#1` indeed fixes my issue, thank you!
What do you think about mentioning this in the `:help` description of  `>>`?

**Comment by jottkaerr** [comment]
From `:help >`:

> If the 'smartindent' option is on, or 'cindent' is on and 'cinkeys' contains
'#' with a zero value, shift right does not affect lines starting with '#'
(these are supposed to be C preprocessor lines that must stay in column 1).

**Comment by glacambre** [comment]
Oh, there's no need to change `>>`'s description then. I guess I should have read the whole help file. Thanks for pointing this out :)
