### ISSUE TITLE
Job/Timer callbacks are scheduled at the wrong moment.

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#2811]
I have been maintaining the [AsyncRun](https://github.com/skywind3000/asyncrun.vim) plugin from 2016. recently, I found a strange issue that job callbacks will happen while executing one of my function:

```VimL
function! StartDemo()
    let s:job_id = job_start(..., ...)
    let successful = (job_status(s:job_id) != 'fail')? 1 : 0
    if successful
       ... some complex work ...
       <PLACE 1>
       ... initialize some internal variables ...
       <PLACE 2>
       ...
       let s:state = 'running'
    endif
endfunc
```

As my expectation, job callbacks will only be scheduled in the top-level of the event-loop, will never happen inside a user defined function, just like other event-driven systems (win32, nodejs), one event will never be dispatched until previous event finished.

But some times, I find the callbacks are invoked in `PLACE 1` or `PLACE2` , and it becomes very dangerous, StartDemo hasn't finished, the internal states have not been initialized but the callbacks happens. Vim doesn't have threading locks, if job callbacks happen before `StartDemo()` exits, state conflict cannot be prevented.

The problem can be easily reproduced with `timer_start`:

```VimL
function! MyTimer(args)
	caddexpr "timer"
	cbottom
endfunc

function! MyTest()
	caddexpr "MyTest() begin"
	let s:tid = timer_start(300, 'MyTimer', {'repeat': 5})
	if s:tid >= 0
		sleep 1
		let s:state = 'running'
	endif
	caddexpr "MyTest() end"
endfunc

if exists('s:tid')
	call timer_stop(s:tid)
endif

cexpr ""
copen 8
wincmd p

call MyTest()
```

the output is:

```text
|| MyTest() begin
|| timer
|| timer
|| timer
|| MyTest() end
|| timer
|| timer
```

See, timer callback happens 3 times before `MyTest()` exit. If `MyTimer` relies on some variables which are initialized after timer starts successfully and before `MyTest()` exits, the result is unpredictable.

Can we prevent executing timer/job callbacks inside any user defined functions ?? just like win32 events and nodejs ??

**Comment by skywind3000** [comment]
x86 has two instructions `CLI` and `STI` to disable or enable interrupts. if this issue requires a big refactor, can we introduce something like `cli` and `sti` ??

and the demo could be write safely like this:

```VimL
function! StartDemo()
    call callback_disable()
    let s:job_id = job_start(..., ...)
    let successful = (job_status(s:job_id) != 'fail')? 1 : 0
    if successful
       ... some complex work ...
       ... initialize some internal variables ...
    else
       ... output error message
    endif
    call callback_enable()
endfunc
```

The callbacks can be guaranteed not to execute between the `callback_disable()` and `callback_enable()` .

**Comment by chrisbra** [comment]
does that always involve a `:sleep` command?

**Comment by skywind3000** [comment]
No, sleep is just for demonstration, in AsyncRun plugin, there are 5 things after job starts successfully:

1. clear the quickfix window and set the title of qf-windows.
2. display a successful message in quickfix window: may trigger some autocmds.
3. initialize internal variables, including: record starting time, update task states, setup a msg queue.
4. start a timer
5. call `doautocmd` several times.

And I found job callbacks may happen before the five steps finished.

**Comment by skywind3000** [comment]
And there is a similar issue that job callbacks are invoked while executing some sandbox commands and get a secure error:

```text
E523: Not allowed here: ^I^I^I^Icaddexpr l:text
E523: Not allowed here: ^I^Icbottom
```

see here: https://github.com/unblevable/quick-scope/issues/39

I think it is relative to this issue.

**Comment by brammool** [comment]
Callbacks can be invoked whenever Vim checks for input, which is when channels are read and possibly have side effects.  Thus a "sleep" will definitely trigger this.  If you don't wait for anything, just execute a sequence of commands, you should not be interrupted by callbacks.  It's not like a hardware interrupt, Vim has to check for the events to happen.

Disabling callbacks for a while is tricky.  First of all, if you forget to re-enable callbacks, things will fail miserably.  Secondly, if a sequence of events happen, Vim would have to make a list of callbacks to invoke later.  But when that later comes, the situation may already have changed and those callback functions have to check what happened in the mean time.

Most callbacks should be able to work without much side effects, so as not to disturb the user.  Disabling those will only make things more complicated.

**Comment by skywind3000** [comment]
Thanks for the explaination. May I ask what exactly does **"whenever Vim checks for input"** mean ? I read this sentence in the document times and times again, but still have no idea about a precise definition.

I ask for this because this problem has really happened without any `:sleep`, there are truely just few "sequence of commands" , I remember once, there is an "on_exit" callback which will set a local state to "stopped". and at the end of my job setup function, if job starts successfully, the internal state will be assigned to "running". Most of time, the state should first be set to "running", then to "stopped".

When a job exits too soon, the "on_exit" callback will be triggered before I change the state to "running", so, it had first been changed to "stopped" in the "on_exit" callback, then been changed to "running" in the job setup function, because job started successfully. As a result, the state has no chance to become  "stopped" and plugin could not create any new jobs because it assumed last command hadn't stopped yet.

There are really some "sequence of commands" after job starts. I am suspicious of some quickfix commands like `setqflist`, `caddexpr` and `cbottom`, because they may trigger some autocommands which I can't guarantee they only contain "sequence of commands".

So, can we have a clear definition of "whenever vim checks for input", like:

Will a job/timer callback happen when:

1. call "sleep" -- definitely yes.
2. call "getchar()" -- definitely yes.
3. before/after polling new events in the `select/poll` routines of the main event loop ? -- yes ?
4. do autocommands ??
5. run shell commands with `system()` or `!` ??
6. quickfix autocommands that will call external tool like "git" or something.
7. after one function returns to its caller, but the caller hasn't finished.

I believe no plugin will really call a ":sleep" command, but case 4, 5 and 6 are really common.

**Comment by brammool** [comment]
Linwei wrote:

> Thanks for the explaination. May I ask what exactly does **whenever
> Vim checks for input** mean ? Does it have a precise definition ? 
> 
> I ask for this because this problem has really happened without any
> `:sleep`, there are truely just few "sequence of commands" , I
> remember once, there is an "on_exit" callback which will set a local
> state to "stopped". and at the end of my job setup function, if job
> starts successfully, the internal state will be assigned to "running".
> Most of time, the state should first be set to "running", then to
> "stopped".

When starting a job it's likely to check for channels to have data to
read or send.

The job object provides the "running" state, it's not clear to me why
you need to keep your own state.  Anyway, you should set the state to
"starting" and in on_exit to "finished", then before setting it to
"running" you can check the value is still "starting" to avoid
overwriting "finished" with "running".

> When a job exits too soon, the "on_exit" callback will be triggered
> before I change the state to "running", so, it had first been changed
> to "stopped" in the "on_exit" callback, then been changed to "running"
> in the job setup function, because job started successfully. As a
> result, the state has no change to be changed to "stopped" and plugin
> could not create any new jobs because it assumed last command hadn't
> stopped yet.
> 
> There are really some "sequence of commands" after job starts. I am
> suspicious of some quickfix commands like `setqflist`, `caddexpr` and
> `cbottom`, because they may trigger some autocommands which I can't
> guarantee they only contain "sequence of commands".

Right, we can't expect a plugin to NOT be interrupted by other work.

> So, can we have a clear definition of "whenever vim checks for input",
> like:
> 
> Will a job/timer callback happen when:
> 
> 1. call "sleep" -- definitely yes.
> 2. call "getchar()" -- definitely yes.
> 3. before/after polling new events in the `select/poll` routines of the main event loop ? -- yes ?
> 4. do autocommands ??
> 5. run shell commands with `system()` or `!` ??
> 6. quickfix autocommands that will call external tool like "git" or something.
> 
> I believe no plugin will really call a ":sleep" command, but case 4, 5
> and 6 is really common.

Generally it's anything that would wait for something to happen.  E.g.
when starting a job this is a shell command, and that can take some
time.

I can't give an exact list, also because it will change over time.
You have to take asynchronous behavior into account.  And as you
mention, autocommands may also interfere.

-- 
Don't be humble ... you're not that great.
                      -- Golda Meir

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by skywind3000** [comment]
OK, I moved the state manipulation code before any quickfix window command. and added some `noautocmd`. hope it  works.
