### ISSUE TITLE
Add highlight group for current match

### ISSUE THREAD

**Issue by alok** [vim/vim#2819]
After patch 8.0.1238, it would be nice if the current match had its own highlight group (that could be linked by default to the regular Search hl group).

**Comment by brammool** [comment]
Which patch do you refer to?  Patch 8.0.0128 is:   Display test fails on MS-Windows.

**Comment by alok** [comment]
Sorry, missing a digit: I meant 12*3*8.

**Comment by jparise** [comment]
The [Loupe](https://github.com/wincent/loupe) plugin does this:

> ### Makes the currently selected match easier to see
> When searching using `/`, `?`, `star`, `#`, `n`, `N` or similar, it can be hard to see the "current" match from among all the matches that 'hlsearch' highlights. Loupe makes the currently selected match easier to see by:
> - Applying a different `:highlight group` (by default, `hl-IncSearch`) to the match under the cursor.

It implements this using `matchadd()` to highlight the current match, but it would also make a nice addition to vim itself.

**Comment by jparise** [comment]
There's also a recent [r/vim thread](https://www.reddit.com/r/vim/comments/ap9we4/vimsearchhi_highlight_the_current_search_result/) that suggests the [vim-searchhi](https://github.com/qxxxb/vim-searchhi) plugin as well as an [ad hoc scripting solution](https://www.reddit.com/r/vim/comments/ap9we4/vimsearchhi_highlight_the_current_search_result/eg8kybs/).

**Comment by qxxxb** [comment]
There's also [vim-searchlight](https://github.com/PeterRincker/vim-searchlight), which uses no mappings

**Comment by blueyed** [comment]
For reference, there's a WIP PR for Neovim at: https://github.com/neovim/neovim/pull/11082

**Comment by brammool** [comment]
It's not really the current match, more like the "last found match".  If you move the cursor around and hit "n" then only the cursor position matters, not what was found last.
Using IncSearch has the disadvantage that this highlight will always happen, not only when the user specifically adds highlighting for it.

**Comment by airblade** [comment]
I'll throw my hat in the ring: https://github.com/airblade/vim-current-search-match

**Comment by chrisbra** [comment]
Closing then: https://github.com/vim/vim/commit/a43993897aa372159f682df37562
