### ISSUE TITLE
Incorrect documentation of v_r in index.txt

### ISSUE THREAD

**Issue by techee** [vim/vim#2822]
The documentation of "r" in visual mode is incorrect here:

https://github.com/vim/vim/blob/285e3358696b1bc6296e5d4c53425680ce8fbd54/runtime/doc/index.txt#L962

"r" is used to replace the selected text with a character. Probably copy/paste error.

**Comment by tonymec** [comment]
Indeed, v_r replaces all characters in the visual text by repeated instances of one character. For instance selecting `abcdefghi` in Visual (not Select) mode then doing `rx` results in `xxxxxxxxx`. (Of course, in Select mode the r would replace the selection, and x after that would insert an x after the r).

**Comment by brammool** [comment]
Thanks for reporting, I'll fix it
