### ISSUE TITLE
Vim requires libwinpthread-1.dll (STATIC_LIBWINPTHREAD does not work)

### ISSUE THREAD

**Issue by graywolf** [vim/vim#2827]
When compiling vim the `libwinpthread-1.dll` library is required in the path in order to be able to start vim despite having `STATIC_LIBWINPTHREAD=yes` in my configuration. PR https://github.com/vim/vim/pull/1256 added the option, so I assume it used to work (and iirc it did even for me), probably broken by gcc update (or something).

I __think__ I know what the problem is, but have no idea what to do about it:

This is the output of the last step in building `gvim.exe` if I add `-v` flag to id:

		$ gcc -v -Iproto -DWIN32 -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 -DHAVE_PATHDEF -DFEAT_HUGE -DHAVE_STDINT_H -DMS_WIN64 -DHAVE_GETTEXT -DHAVE_LOCALE_H -DDYNAMIC_GETTEXT -DFEAT_CSCOPE -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL -DFEAT_TERMINAL -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DFEAT_DIRECTX_COLOR_EMOJI -DFEAT_GUI_W32 -DFEAT_CLIPBOARD -DFEAT_MBYTE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DDYNAMIC_ICONV -pipe -march=x86-64 -Wall -DFEAT_RUBY -I g:/WS/progs/Ruby25-x64/lib/ruby/2.5.0/x64-mingw32 -I g:/WS/progs/Ruby25-x64/include/ruby-2.5.0 -I g:/WS/progs/Ruby25-x64/include/ruby-2.5.0/x64-mingw32 -DRUBY_VERSION=25 -DFEAT_XPM_W32 -I xpm/x64/include -I xpm/x64/../include -O3 -fomit-frame-pointer -freg-struct-return -s -mwindows -o gvim.exe gobjx86-64/arabic.o gobjx86-64/beval.o gobjx86-64/blowfish.o gobjx86-64/buffer.o gobjx86-64/charset.o gobjx86-64/crypt.o gobjx86-64/crypt_zip.o gobjx86-64/dict.o gobjx86-64/diff.o gobjx86-64/digraph.o gobjx86-64/edit.o gobjx86-64/eval.o gobjx86-64/evalfunc.o gobjx86-64/ex_cmds.o gobjx86-64/ex_cmds2.o gobjx86-64/ex_docmd.o gobjx86-64/ex_eval.o gobjx86-64/ex_getln.o gobjx86-64/farsi.o gobjx86-64/fileio.o gobjx86-64/fold.o gobjx86-64/getchar.o gobjx86-64/hardcopy.o gobjx86-64/hashtab.o gobjx86-64/json.o gobjx86-64/list.o gobjx86-64/main.o gobjx86-64/mark.o gobjx86-64/memfile.o gobjx86-64/memline.o gobjx86-64/menu.o gobjx86-64/message.o gobjx86-64/misc1.o gobjx86-64/misc2.o gobjx86-64/move.o gobjx86-64/mbyte.o gobjx86-64/normal.o gobjx86-64/ops.o gobjx86-64/option.o gobjx86-64/os_win32.o gobjx86-64/os_mswin.o gobjx86-64/winclip.o gobjx86-64/pathdef.o gobjx86-64/popupmnu.o gobjx86-64/quickfix.o gobjx86-64/regexp.o gobjx86-64/screen.o gobjx86-64/search.o gobjx86-64/sha256.o gobjx86-64/spell.o gobjx86-64/spellfile.o gobjx86-64/syntax.o gobjx86-64/tag.o gobjx86-64/term.o gobjx86-64/ui.o gobjx86-64/undo.o gobjx86-64/userfunc.o gobjx86-64/version.o gobjx86-64/vimrc.o gobjx86-64/window.o gobjx86-64/if_ruby.o gobjx86-64/if_cscope.o gobjx86-64/netbeans.o gobjx86-64/channel.o gobjx86-64/gui_dwrite.o gobjx86-64/xpm_w32.o gobjx86-64/terminal.o gobjx86-64/term_encoding.o gobjx86-64/term_keyboard.o gobjx86-64/term_mouse.o gobjx86-64/term_parser.o gobjx86-64/term_pen.o gobjx86-64/term_screen.o gobjx86-64/term_state.o gobjx86-64/term_unicode.o gobjx86-64/term_vterm.o gobjx86-64/gui.o gobjx86-64/gui_w32.o gobjx86-64/gui_beval.o gobjx86-64/os_w32exe.o -lkernel32 -luser32 -lgdi32 -ladvapi32 -lcomdlg32 -lcomctl32 -lversion -lwsock32 -ld2d1 -ldwrite -Lxpm/x64/lib -lXpm -Wl,-Bstatic -lstdc++ -Wl,-Bdynamic -Wl,-Bstatic -lwinpthread -Wl,-Bdynamic -lole32 -luuid      -Lg:/WS/progs/Ruby25-x64/lib -lx64-msvcrt-ruby250
		Using built-in specs.
		COLLECT_GCC=G:\WS\progs\msys64\mingw64\bin\gcc.exe
		COLLECT_LTO_WRAPPER=G:/WS/progs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/lto-wrapper.exe
		Target: x86_64-w64-mingw32
		Configured with: ../gcc-7.3.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,objc,obj-c++,fortran,ada --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-time=yes --enable-libstdcxx-filesystem-ts=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev1, Built by MSYS2 project' --with-bugurl=https://sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld
		Thread model: posix
		gcc version 7.3.0 (Rev1, Built by MSYS2 project)
		COMPILER_PATH=G:/WS/progs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/;G:/WS/progs/msys64/mingw64/bin/../lib/gcc/;G:/WS/progs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/
		LIBRARY_PATH=G:/WS/progs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/;G:/WS/progs/msys64/mingw64/bin/../lib/gcc/;G:/WS/progs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/lib/../lib/;G:/WS/progs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../lib/;G:/WS/progs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/lib/;G:/WS/progs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../
		COLLECT_GCC_OPTIONS='-v' '-I' 'proto' '-D' 'WIN32' '-D' 'WINVER=0x0501' '-D' '_WIN32_WINNT=0x0501' '-D' 'HAVE_PATHDEF' '-D' 'FEAT_HUGE' '-D' 'HAVE_STDINT_H' '-D' 'MS_WIN64' '-D' 'HAVE_GETTEXT' '-D' 'HAVE_LOCALE_H' '-D' 'DYNAMIC_GETTEXT' '-D' 'FEAT_CSCOPE' '-D' 'FEAT_NETBEANS_INTG' '-D' 'FEAT_JOB_CHANNEL' '-D' 'FEAT_TERMINAL' '-D' 'FEAT_DIRECTX' '-D' 'DYNAMIC_DIRECTX' '-D' 'FEAT_DIRECTX_COLOR_EMOJI' '-D' 'FEAT_GUI_W32' '-D' 'FEAT_CLIPBOARD' '-D' 'FEAT_MBYTE' '-D' 'FEAT_MBYTE_IME' '-D' 'DYNAMIC_IME' '-D' 'DYNAMIC_ICONV' '-pipe' '-march=x86-64' '-Wall' '-D' 'FEAT_RUBY' '-I' 'g:/WS/progs/Ruby25-x64/lib/ruby/2.5.0/x64-mingw32' '-I' 'g:/WS/progs/Ruby25-x64/include/ruby-2.5.0' '-I' 'g:/WS/progs/Ruby25-x64/include/ruby-2.5.0/x64-mingw32' '-D' 'RUBY_VERSION=25' '-D' 'FEAT_XPM_W32' '-I' 'xpm/x64/include' '-I' 'xpm/x64/../include' '-O3' '-fomit-frame-pointer' '-freg-struct-return' '-s' '-mwindows' '-o' 'gvim.exe' '-Lxpm/x64/lib' '-Lg:/WS/progs/Ruby25-x64/lib'
		 G:/WS/progs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/collect2.exe -plugin G:/WS/progs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/liblto_plugin-0.dll -plugin-opt=G:/WS/progs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/lto-wrapper.exe -plugin-opt=-fresolution=G:\WS\progs\msys64\tmp\ccJLVZAV.res -plugin-opt=-pass-through=-lmingw32 -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_eh -plugin-opt=-pass-through=-lmoldname -plugin-opt=-pass-through=-lmingwex -plugin-opt=-pass-through=-lmsvcrt -plugin-opt=-pass-through=-lpthread -plugin-opt=-pass-through=-lgdi32 -plugin-opt=-pass-through=-lcomdlg32 -plugin-opt=-pass-through=-ladvapi32 -plugin-opt=-pass-through=-lshell32 -plugin-opt=-pass-through=-luser32 -plugin-opt=-pass-through=-lkernel32 -plugin-opt=-pass-through=-lmingw32 -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_eh -plugin-opt=-pass-through=-lmoldname -plugin-opt=-pass-through=-lmingwex -plugin-opt=-pass-through=-lmsvcrt -m i386pep --subsystem windows -Bdynamic -o gvim.exe -s G:/WS/progs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/lib/../lib/crt2.o G:/WS/progs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/crtbegin.o -Lxpm/x64/lib -Lg:/WS/progs/Ruby25-x64/lib -LG:/WS/progs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0 -LG:/WS/progs/msys64/mingw64/bin/../lib/gcc -LG:/WS/progs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/lib/../lib -LG:/WS/progs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../lib -LG:/WS/progs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/lib -LG:/WS/progs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../.. gobjx86-64/arabic.o gobjx86-64/beval.o gobjx86-64/blowfish.o gobjx86-64/buffer.o gobjx86-64/charset.o gobjx86-64/crypt.o gobjx86-64/crypt_zip.o gobjx86-64/dict.o gobjx86-64/diff.o gobjx86-64/digraph.o gobjx86-64/edit.o gobjx86-64/eval.o gobjx86-64/evalfunc.o gobjx86-64/ex_cmds.o gobjx86-64/ex_cmds2.o gobjx86-64/ex_docmd.o gobjx86-64/ex_eval.o gobjx86-64/ex_getln.o gobjx86-64/farsi.o gobjx86-64/fileio.o gobjx86-64/fold.o gobjx86-64/getchar.o gobjx86-64/hardcopy.o gobjx86-64/hashtab.o gobjx86-64/json.o gobjx86-64/list.o gobjx86-64/main.o gobjx86-64/mark.o gobjx86-64/memfile.o gobjx86-64/memline.o gobjx86-64/menu.o gobjx86-64/message.o gobjx86-64/misc1.o gobjx86-64/misc2.o gobjx86-64/move.o gobjx86-64/mbyte.o gobjx86-64/normal.o gobjx86-64/ops.o gobjx86-64/option.o gobjx86-64/os_win32.o gobjx86-64/os_mswin.o gobjx86-64/winclip.o gobjx86-64/pathdef.o gobjx86-64/popupmnu.o gobjx86-64/quickfix.o gobjx86-64/regexp.o gobjx86-64/screen.o gobjx86-64/search.o gobjx86-64/sha256.o gobjx86-64/spell.o gobjx86-64/spellfile.o gobjx86-64/syntax.o gobjx86-64/tag.o gobjx86-64/term.o gobjx86-64/ui.o gobjx86-64/undo.o gobjx86-64/userfunc.o gobjx86-64/version.o gobjx86-64/vimrc.o gobjx86-64/window.o gobjx86-64/if_ruby.o gobjx86-64/if_cscope.o gobjx86-64/netbeans.o gobjx86-64/channel.o gobjx86-64/gui_dwrite.o gobjx86-64/xpm_w32.o gobjx86-64/terminal.o gobjx86-64/term_encoding.o gobjx86-64/term_keyboard.o gobjx86-64/term_mouse.o gobjx86-64/term_parser.o gobjx86-64/term_pen.o gobjx86-64/term_screen.o gobjx86-64/term_state.o gobjx86-64/term_unicode.o gobjx86-64/term_vterm.o gobjx86-64/gui.o gobjx86-64/gui_w32.o gobjx86-64/gui_beval.o gobjx86-64/os_w32exe.o -lkernel32 -luser32 -lgdi32 -ladvapi32 -lcomdlg32 -lcomctl32 -lversion -lwsock32 -ld2d1 -ldwrite -lXpm -Bstatic -lstdc++ -Bdynamic -Bstatic -lwinpthread -Bdynamic -lole32 -luuid -lx64-msvcrt-ruby250 -lmingw32 -lgcc -lgcc_eh -lmoldname -lmingwex -lmsvcrt -lpthread -lgdi32 -lcomdlg32 -ladvapi32 -lshell32 -luser32 -lkernel32 -lmingw32 -lgcc -lgcc_eh -lmoldname -lmingwex -lmsvcrt G:/WS/progs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/lib/../lib/default-manifest.o G:/WS/progs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/crtend.o
		COLLECT_GCC_OPTIONS='-v' '-I' 'proto' '-D' 'WIN32' '-D' 'WINVER=0x0501' '-D' '_WIN32_WINNT=0x0501' '-D' 'HAVE_PATHDEF' '-D' 'FEAT_HUGE' '-D' 'HAVE_STDINT_H' '-D' 'MS_WIN64' '-D' 'HAVE_GETTEXT' '-D' 'HAVE_LOCALE_H' '-D' 'DYNAMIC_GETTEXT' '-D' 'FEAT_CSCOPE' '-D' 'FEAT_NETBEANS_INTG' '-D' 'FEAT_JOB_CHANNEL' '-D' 'FEAT_TERMINAL' '-D' 'FEAT_DIRECTX' '-D' 'DYNAMIC_DIRECTX' '-D' 'FEAT_DIRECTX_COLOR_EMOJI' '-D' 'FEAT_GUI_W32' '-D' 'FEAT_CLIPBOARD' '-D' 'FEAT_MBYTE' '-D' 'FEAT_MBYTE_IME' '-D' 'DYNAMIC_IME' '-D' 'DYNAMIC_ICONV' '-pipe' '-march=x86-64' '-Wall' '-D' 'FEAT_RUBY' '-I' 'g:/WS/progs/Ruby25-x64/lib/ruby/2.5.0/x64-mingw32' '-I' 'g:/WS/progs/Ruby25-x64/include/ruby-2.5.0' '-I' 'g:/WS/progs/Ruby25-x64/include/ruby-2.5.0/x64-mingw32' '-D' 'RUBY_VERSION=25' '-D' 'FEAT_XPM_W32' '-I' 'xpm/x64/include' '-I' 'xpm/x64/../include' '-O3' '-fomit-frame-pointer' '-freg-struct-return' '-s' '-mwindows' '-o' 'gvim.exe' '-Lxpm/x64/lib' '-Lg:/WS/progs/Ruby25-x64/lib'

We can see here that the issue (imho) is in the `-lpthread` flag witch seems to be auto-added by gcc itself (I found nothing about this in Make_cyg_ming file.

While it correctly sets `winpthread` to be static (`-Bstatic -lwinpthread -Bdynamic`) gcc auto-adds `-lpthread` after it which then requires the dll (since it's dynamic again).

Changing

	$(TARGET): $(OUTDIR) $(OBJ)
		$(CC) $(CFLAGS) $(LFLAGS) -o $@ $(OBJ) $(LIB) -lole32 -luuid $(LUA_LIB) $(MZSCHEME_LIBDIR) $(MZSCHEME_LIB) $(PYTHONLIB) $(PYTHON3LIB) $(RUBYLIB)

to

	$(TARGET): $(OUTDIR) $(OBJ)
		$(CC) $(CFLAGS) $(LFLAGS) -o $@ $(OBJ) $(LIB) -lole32 -luuid $(LUA_LIB) $(MZSCHEME_LIBDIR) $(MZSCHEME_LIB) $(PYTHONLIB) $(PYTHON3LIB) $(RUBYLIB) -Wl,-Bstatic

in `Make_cyg_ming.mak` would probably do the trick but I do not have enough knowledge about
gcc toolset to be able to tell if/what will the side effect of that be.

Maybe introduce new flag `STATIC_DEFAULT_LIBS` to make it optional?

I can put patch together if someone gives me a nudge in the right direction.

**Comment by k-takata** [comment]
I have noticed the same problem when I use MinGW-w64 GCC 7.x, and I personally use the following patch:

```diff
--- a/src/Make_cyg_ming.mak
+++ b/src/Make_cyg_ming.mak
@@ -853,7 +853,7 @@ endif
 endif
 
 ifeq (yes, $(STATIC_WINPTHREAD))
-LIB += -Wl,-Bstatic -lwinpthread -Wl,-Bdynamic
+LIB += -lgcc_eh -Wl,-Bstatic -lwinpthread -Wl,-Bdynamic
 endif
 
 all: $(TARGET) vimrun.exe xxd/xxd.exe install.exe uninstal.exe GvimExt/gvimext.dll
```

However, this patch might cause error on TDM-GCC 5.1.0, because it doesn't have libgcc_eh.a (not tested).
I'm not sure what is the best way to fix this.

**Comment by k-takata** [comment]
I have updated the patch:
https://bitbucket.org/k_takata/vim-ktakata-mq/src/eb27c934f5637bf7ceb3f5df1ff33852614a0261/mingw-link-libgcc_eh-explicitly.patch?fileviewer=file-view-default
If `STATIC_LIBWINPTHREAD=yes` (or `STATIC_STDCPLUS=yes`) is specified, `libwinpthread-1.dll` will be statically linked.
For TDM-GCC(-64) users, please also specify `HAS_GCC_EH=no`.

I also changed to use `-static-libstdc++` instead of `-Wl,-Bstatic -lstdc++ -Wl,-Bdynamic`.
This is easier to understand, however, we should use `g++` instead of `gcc`.
