### ISSUE TITLE
GVim deadlock when redirecting too many text from buffer to job's stdin.

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#2828]
version: GVim 8.0.1733 (Windows 10)

set job-option `in_io`  to `buffer`  can transfer data from buffer to job's stdin.
but if there are too many lines in the buffer.  GVim will get unresponsive.

while terminal vim and mac vim are both fine.

reproduce:

```VimL
" command "type con" will just eat data from stdin
let args = ['cmd', '/C', 'type', 'con']
let opts = { 'out_io':'null', 'err_io':'null', 'in_io':'buffer' }

" open a buffer with 500+ lines
help index

let opts['in_buf'] = bufnr('%')

" uncomment two lines below to prevent gvim deadlock 
" let opts['in_top'] = 1
" let opts['in_bot'] = 50

let job = job_start(args, opts)
```

But if we limit text size by `in_top` and `in_bot`,  it works as expected.

**Comment by skywind3000** [comment]
I just can't send more than 300+ lines to a job's stdin:

```VimL
" command "type con" will just eat data from stdin
let args = ['cmd', '/C', 'type', 'con']
let opts = { 'out_io':'null', 'err_io':'null', 'in_io':'pipe' }

let job = job_start(args, opts)

" GVim dead here.
for i in range(300)
	call ch_sendraw(job, "12341234123412341234\n")
endfor

echo "done"
```

**Comment by brammool** [comment]
Please try using the new "noblock" option from patch 8.1.0350

**Comment by skywind3000** [comment]
So, what will happen without "noblock" if data size exceeds limit ? deadlock too ?

**Comment by brammool** [comment]
> So, what will happen without "noblock" if data size exceeds limit ?
> deadlock too ?

The system is expected to split the write into pieces, or return an
error.  The problem we are solving with "noblock" is that the receiving
job read buffer is full, and writing won't happen until the job reads
from the buffer.  But if the job is writing to Vim at the same time,
this results in a deadlock.  We already had this fixed for the terminal,
now it's also possible for jobs and channels.

We cannot make this the default, as it may result in the ch_send
functions to return before writing is actually done. This may break
scripts that depend on it.


-- 
How To Keep A Healthy Level Of Insanity:
1. At lunch time, sit in your parked car with sunglasses on and point
   a hair dryer at passing cars. See if they slow down.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by skywind3000** [comment]
Seem fixed
