### ISSUE TITLE
Cannot use "}" in a statusline expression

### ISSUE THREAD

**Issue by blueyed** [vim/vim#2829]
`:let &stl = '%{"foo}"}` will cause:

```
E115: Missing quote: '%{"foo}"}
E15: Invalid expression: '%{"foo}"}
```

This prevents usage of function with dict arguments, e.g. `let &stl = 'F({opt: 1})'`.

**Comment by blueyed** [comment]
I've tried to escape the "}" using backslash(es) and as `%}`.

**Comment by tonymec** [comment]
What does
``` vim
    :set stl=%{\"foo\"\ .\ nr2char(125)}
```
give you? (and see `:help option-backslash` about the backslash-escaped spaces and quotes)

**Comment by blueyed** [comment]
That works, but unfortunately not for a dict:

```
:let &stl = "%{{'foo': 'bar'".nr2char(125)."}"
```

results in

> E722: Missing comma in Dictionary: 
E15: Invalid expression: {'foo': 'bar'

`eval` could be used here:

```vim
:let &stl = '%{string(eval(''{"foo": "bar"''.nr2char(125)))}'
```

However, a better mechanism to escape the closing `}` would be nice.
If that's not possible then the nr2char trick should get added to the documentation instead.

**Comment by brammool** [comment]
Daniel Hahler wrote:

> `:let &stl = '%{"foo}"}` will cause:
> 
> ```
> E115: Missing quote: '%{"foo}"}
> E15: Invalid expression: '%{"foo}"}
> ```
> 
> This prevents usage of function with dict arguments, e.g. `let &stl =
> 'F({opt: 1})'`.

Yeah, this was made this way long ago.  It's also a bit inconsistent,
using %( %)  and %{ }.  We can't change that now.  And escaping the }
will make the expression complicated.

I suggest you work around it by calling a function.

-- 
hundred-and-one symptoms of being an internet addict:
241. You try to look for Net Search even when you're in File Manager.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by blueyed** [comment]
Closing this then.

**Comment by blueyed** [comment]
> If that's not possible then the nr2char trick should get added to the documentation instead.

Maybe something to still do here.  But it might be good enough if it can be found here.

**Comment by mg979** [comment]
@blueyed this works for me
```vim
let &stl = '%{"foo\u7d"}'
```
