### ISSUE TITLE
sh: Incorrect highlighting when # is used inside backquotes.

### ISSUE THREAD

**Issue by ogiekako** [vim/vim#2831]
Let a.sh be:
```
#!/bin/sh
echo a `#foo` b
```
Vim highlights it as if `b` is commented out, which is wrong; ./a.sh outputs `a b`.

**Comment by ogiekako** [comment]
vim version: 7.4.1689

**Comment by chrisbra** [comment]
Please check with that latest version

**Comment by cecamp** [comment]
Please try v181 of syntax/sh.vim available at my website (http://www.drchip.org/astronaut/vim/index.html#SYNTAX_SH).  I note that this use of `..` is peculiar, as evidenced by its not working with the (usual) $(..) equivalent for either ksh or bash.

**Comment by quemeraisc** [comment]
With version 8.0 I could reproduce this issue. Using the provided syntax file fixes it for me.

**Comment by k-takata** [comment]
Now v185 is included in this repository, so I think we can close this.
