### ISSUE TITLE
change VIMRUNTIMEDIR after finish compile

### ISSUE THREAD

**Issue by oronge** [vim/vim#2835]
we can set  VIMRUNTIMEDIR when make in the process of compile such as
make VIMRUNTIMEDIR=/usr/local/share/vim/vim80,
then vim will load some files from the path VIMRUNTIMEDIR refers to，is there any way chang the path vim load the files from ? such as set some variables

**Comment by h-east** [comment]
Hi,
See the document `:h $VIMRUNTIME`.

**Comment by oronge** [comment]
@h-east  I have tried set $VIMRUNTIME, but it's useless
After compile vim8.0 and install it in /usr/local, the vim8.0 can work well.  
But when I execute the follow commands, the prolem arise, 

**mv /usr/local/share/vim/vim80/ /home/myusername/vim_tmp/
VIMRUNTIME=/home/myusername/vim_tmp/vim80**

The vim8.0 can run, but `:help` print
**E433: No tags file
E149: Sorry, no help for help.txt**

**Comment by h-east** [comment]
You need to use `export` command.

```bash
export VIMRUNTIME=/home/myusername/vim_tmp/vim80
```
Please check the value of the environment variable with the following command on Vim.
```vim
:echo $VIMRUNTIME
```

**Comment by chrisbra** [comment]
Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. Closing.

**Comment by oronge** [comment]
@h-east thank you very much! it's solved
