### ISSUE TITLE
A feature is not mentioned in doc/windows.txt

### ISSUE THREAD

**Issue by lkintact** [vim/vim#2839]
The `bufname` argument that some commands (`:bdelete`, `:buffer` etc) described in windows.txt take doesn't necessarily need to be a full buffer name, but can be just part of it. This isn't mentioned in the file, but perhaps should be.

[gvim_8.0.1750_x86.zip]

**Comment by brammool** [comment]
> The `bufname` argument that some commands (`:bdelete`, `:buffer` etc)
> described in windows.txt take doesn't necessarily need to be a full
> buffer name, but can be just part of it. This isn't mentioned in the
> file, but perhaps should, since it seems very useful.

I thought it was mentioned somewhere, but now I can't find it.
I'll add a few remarks.

-- 
hundred-and-one symptoms of being an internet addict:
263. You have more e-mail addresses than shorts.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lkintact** [comment]
>I thought it was mentioned somewhere, but now I can't find it. 

Turns out it's in the User Manual (usr_22.txt), but since commands like `:h :buffer` take the user to `windows.txt`, he/she might miss the feauture.

>I'll add a few remarks.

Thanks!

**Comment by chrisbra** [comment]
I think this has been fixed as of https://github.com/vim/vim/commit/15142e27aaafa15b72d1042c25fbb5e4f12b6736
