### ISSUE TITLE
:s_c help text for CTRL-E and CTRL-Y is reversed.

### ISSUE THREAD

**Issue by bcc32** [vim/vim#2845]
In vim 8.0.1750, the help text for the /c substitute flag (":help :s_c") says the following about CTRL-E and CTRL-Y

> CTRL-E  to scroll the screen up {not in Vi, not available when
>     compiled without the |+insert_expand| feature}
> CTRL-Y  to scroll the screen down {not in Vi, not available when
>     compiled without the |+insert_expand| feature}

This is backwards; CTRL-E scrolls down and CTRL-Y scrolls up.

**Comment by brammool** [comment]
The text is correct, perhaps you have a mapping?  Or it's a point-of-view misinterpretation.

**Comment by bcc32** [comment]
Ah, I see.  I was confused because the documentation for CTRL-E in normal mode has this to say:

```
							*CTRL-E*
CTRL-E			Scroll window [count] lines downwards in the buffer.
			Mnemonic: Extra lines.
```

I guess I did not quite understand the distinction between screen and window.
