### ISSUE TITLE
File names in qf window can't get reduced (GVim), absolute paths and relative paths mix together and mess up qflist.

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#2846]
GVim: 8.0.1733
System: Windows 10

It seems like quickfix window will reduce file path name to be relative to current directory, not all the file names get reduced, though they are in the same directory.

![quickfix1](https://user-images.githubusercontent.com/3035071/39287337-d47322c6-4955-11e8-9ca2-14211a3cf131.png)

This is a simple `grep` output, all the files locate in the the current directory, some of them get reduced to become a relative path. while some of them keep absolute path name.

Relative path names and absolute path names from the same directory totally mess up the quickfix window. Any clue or option the fix this ?

**Comment by skywind3000** [comment]
Many plugins get involved, 
https://github.com/rking/ag.vim/issues/79
https://github.com/mileszs/ack.vim/issues/143

external tools always output absolute path names, when they are inserted into quickfix list,
if the file is already loaded, it displays a relative path name, if unloaded, absolute path name is used:

ls output (all files come from same directory, but unloaded files display absolute names):

```text
1 #a   "[No Name]"                    line 1
2 %a   "keymaps.vim"                  line 404
3  a-  "[Quickfix List]"              line 0
4u     "D:\acm\github\vim\asc\config.vim" line 0
5u     "D:\acm\github\vim\asc\misc.vim" line 0
6u     "D:\acm\github\vim\asc\plugins.vim" line 0
7u     "D:\acm\github\vim\asc\tools.vim" line 0
8u     "D:\acm\github\vim\asc\unix.vim" line 0
9u     "D:\acm\github\vim\asc\viminit.vim" line 0
10u     "D:\acm\github\vim\asc\vimmake.vim" line 0
```

I noticed same problem was discussed here:
https://vi.stackexchange.com/questions/4815/uneven-quickfix-window-output-from-ack-ag

it recommend to use a `:cd .` to fix the issue, but `:cd .` will break local dir. 
no way to fix this without a `cd .` ??

Or can I just turn off the name resolving and use absolute names in quickfix window ?

**Comment by skywind3000** [comment]
```VimL
	au BufAdd * exec (haslocaldir()? "lcd ." : "cd .")
```

This doesn't work if the file has been added to buffer list as an unloaded file at the first time.

**Comment by skywind3000** [comment]
Every one uses a wide screen today, I can accept all names displayed as absolute names in quickfix window. If resolving file name is complex and hard to change, can we have an option to enforce display absolute names in quickfix window ??

I don't care they are absolute names or relative names in the `:ls` command, but a lot of plugins uses quickfix today, mixed absolute and relative names is really annoying.

**Comment by skywind3000** [comment]
If I add:

```VimL
exec (haslocaldir()? "lcd ." : "cd .")
```
before `caddexpr` in the job callback, the first line of the same file still uses absolute name, but the following lines of the same file use relative names:

```text
D:\acm\github\vim\site\calendar.vim|69| "     1.9  : bug fix, use nnoremap.
site\calendar.vim|384| nnoremap <silent> <Plug>CalendarV :cal Calendar(0)<CR>
site\calendar.vim|385| nnoremap <silent> <Plug>CalendarH :cal Calendar(1)<CR>
site\calendar.vim|1259| execute 'nnoremap <silent> <buffer> q :close<bar>wincmd p<cr>'
site\calendar.vim|1261| execute 'nnoremap <silent> <buffer> <Plug>CalendarDoAction  :call <SID>CalendarDoAction()<cr>'
site\calendar.vim|1262| execute 'nnoremap <silent> <buffer> <Plug>CalendarDoAction  :call <SID>CalendarDoAction()<cr>'
site\calendar.vim|1263| execute 'nnoremap <silent> <buffer> <Plug>CalendarGotoToday :call Calendar(b:CalendarDir)<cr>'
site\calendar.vim|1264| execute 'nnoremap <silent> <buffer> <Plug>CalendarShowHelp  :call <SID>CalendarHelp()<cr>'
site\calendar.vim|1265| execute 'nnoremap <silent> <buffer> <Plug>CalendarReDisplay :call Calendar(' . a:dir . ',' . a:vyear . ',' . a:vmnth . ')<cr>'
site\calendar.vim|1268| execute 'nnoremap <silent> <buffer> <Plug>CalendarGotoPrevMonth :call <SID>CalendarDoAction("<' . pnav . '")<cr>'
site\calendar.vim|1269| execute 'nnoremap <silent> <buffer> <Plug>CalendarGotoNextMonth :call <SID>CalendarDoAction("' . nnav . '>")<cr>'
site\calendar.vim|1270| execute 'nnoremap <silent> <buffer> <Plug>CalendarGotoPrevYear  :call Calendar('.a:dir.','.(a:vyear-1).','.a:vmnth.')<cr>'
site\calendar.vim|1271| execute 'nnoremap <silent> <buffer> <Plug>CalendarGotoNextYear  :call Calendar('.a:dir.','.(a:vyear+1).','.a:vmnth.')<cr>'
D:\acm\github\vim\site\dash.vim|26| noremap <script> <unique> <Plug>DashSearch <SID>DashSearch
site\dash.vim|27| noremap <SID>DashSearch :Dash<CR>
site\dash.vim|28| noremap <script> <unique> <Plug>DashGlobalSearch <SID>DashGlobalSearch
site\dash.vim|29| noremap <SID>DashGlobalSearch :Dash!<CR>
D:\acm\github\vim\site\echofunc.vim|473| inoremap <silent> <buffer>  (   (<C-R>=EchoFunc()<CR>
site\echofunc.vim|476| let map = maparg("(", "i", 0, 1)['noremap'] ? "inoremap" : "imap"
site\echofunc.vim|484| inoremap <silent> <buffer>  )   )<C-R>=EchoFuncClear()<CR>
site\echofunc.vim|487| let map = maparg(")", "i", 0, 1)['noremap'] ? "inoremap" : "imap"
site\echofunc.vim|495| exec 'inoremap <silent> <buffer> ' . g:EchoFuncKeyNext . ' <c-r>=EchoFuncN()<cr>'
site\echofunc.vim|496| exec 'inoremap <silent> <buffer> ' . g:EchoFuncKeyPrev . ' <c-r>=EchoFuncP()<cr>'
site\echofunc.vim|556| execute (b:maparg_left['noremap'] ? "inoremap" : "imap").' '
site\echofunc.vim|565| execute (b:maparg_right['noremap'] ? "inoremap" : "imap").' '
D:\acm\github\vim\site\indent-object.vim|28| onoremap <silent>ai :<C-u>cal <Sid>HandleTextObjectMapping(0, 0, 0, [line("."), line("."), col("."), col(".")])<CR>
site\indent-object.vim|29| onoremap <silent>ii :<C-u>cal <Sid>HandleTextObjectMapping(1, 0, 0, [line("."), line("."), col("."), col(".")])<CR>
site\indent-object.vim|30| vnoremap <silent>ai :<C-u>cal <Sid>HandleTextObjectMapping(0, 0, 1, [line("'<"), line("'>"), col("'<"), col("'>")])<CR><Esc>gv
site\indent-object.vim|31| vnoremap <silent>ii :<C-u>cal <Sid>HandleTextObjectMapping(1, 0, 1, [line("'<"), line("'>"), col("'<"), col("'>")])<CR><Esc>gv
site\indent-object.vim|34| onoremap <silent>aI :<C-u>cal <Sid>HandleTextObjectMapping(0, 1, 0, [line("."), line("."), col("."), col(".")])<CR>
site\indent-object.vim|35| onoremap <silent>iI :<C-u>cal <Sid>HandleTextObjectMapping(1, 1, 0, [line("."), line("."), col("."), col(".")])<CR>
site\indent-object.vim|36| vnoremap <silent>aI :<C-u>cal <Sid>HandleTextObjectMapping(0, 1, 1, [line("'<"), line("'>"), col("'<"), col("'>")])<CR><Esc>gv
site\indent-object.vim|37| vnoremap <silent>iI :<C-u>cal <Sid>HandleTextObjectMapping(1, 1, 1, [line("'<"), line("'>"), col("'<"), col("'>")])<CR><Esc>gv
D:\acm\github\vim\site\taglist.vim|1631| nnoremap <buffer> <silent> <CR>
site\taglist.vim|1633| nnoremap <buffer> <silent> o
site\taglist.vim|1635| nnoremap <buffer> <silent> p
site\taglist.vim|1637| nnoremap <buffer> <silent> P
site\taglist.vim|1640| nnoremap <buffer> <silent> t
```

that seems flaky.

IDEs display absolute path names in their output window, here is the output from visual studio:

```text
1>MainTest.cpp
1>e:\lesson\collection\contextswitch\maintest.cpp(87): error C2065: 'x': undeclared identifier
1>e:\lesson\collection\contextswitch\maintest.cpp(88): error C2065: 'y': undeclared identifier
1>e:\lesson\collection\contextswitch\maintest.cpp(89): error C2065: 'z': undeclared identifier
1>CtxWin64.cpp
```

Nobody uses a 80x25 character display now, is it possible to just display absolute names in quickfix window ? or to resolve every file path before adding to quickfix ?

**Comment by vim-ml** [comment]
Hi,

On Wed, Apr 25, 2018 at 11:31 PM, Linwei <vim-dev-github@256bit.org> wrote:
> Every one uses a wide screen today, I can accept all names displayed as
> absolute names in quickfix window. If resolving file name is complex and
> hard to change, can we have an option to enforce display absolute names in
> quickfix window ??
>
> I don't care they are absolute names or relative names in the :ls command,
> but a lot of plugins uses quickfix today, mixed absolute and relative names
> is really annoying.
>

The quickfix list commands (cwindow and clist) use the buffer name as
displayed by the :ls command. As described in the vi stackexchange discussion
that you referred to, the path to the file/buffer names are shortened only on
certain events (like changing the directory).

Can you try the attached patch which shortens all the buffer names whenever
the :cwindow or the :clist command is invoked?

- Yegappan

**Comment by skywind3000** [comment]
The patch seems work , I verified my previous case and all the file names are relative path names now.

And I write a test for this:

```VimL
copen
wincmd p
let cwd = getcwd()

set errorformat=%f:%l:%m

cexpr ""

caddexpr "abc.txt:100: test"
caddexpr cwd . "/src/a.cpp:100: should be shorten"
caddexpr cwd . "/src/b.cpp:100: should be shorten"
caddexpr cwd . "/main/main.cpp:100: should be shorten"
```

**Comment by vim-ml** [comment]
Hi,

On Thu, Apr 26, 2018 at 10:48 AM, Linwei <vim-dev-github@256bit.org> wrote:
> The patch seems work , I verified my previous case and all the file names
> are relative path names now.
>

Thanks for verifying the patch. There is one performance issue with this
approach. Every time the quickfix window is opened or refreshed, the code
will try to shorten the path for every file name in the buffer list. Depending
on the number of files in the buffer list, this may take some time. This can be
optimized by doing this only for newly added files.

- Yegappan

>
> And I write a test for this:
>
> copen
> wincmd p
> let cwd = getcwd()
>
> set errorformat=%f:%l:%m
>
> cexpr ""
>
> caddexpr "abc.txt:100: test"
> caddexpr cwd . "/src/a.cpp:100: should be shorten"
> caddexpr cwd . "/src/b.cpp:100: should be shorten"
> caddexpr cwd . "/main/main.cpp:100: should be shorten"
>

**Comment by skywind3000** [comment]
I don't really familiar the quickfix.c, but in the patch:

```VimL
+    /* Shorten all the file names, so that it is easy to read */
+    shorten_fnames(TRUE);
```

I noticed that will it shorten_fnames is invoked in `void qf_list(exarg_T *eap)` . does it have to calculate every file names listed in the buffer after every `:caddexpr` ?  a complexity of O(N*N) ?

Is this  a little inefficient ?? I supposed that each single `:caddexpr` will only solve the file name needs to be listed.

But like I said, I don't familiar with quickfix.c, may misunderstand the patch.

**Comment by vim-ml** [comment]
Hi,

On Thu, Apr 26, 2018 at 10:59 AM, Linwei <vim-dev-github@256bit.org> wrote:
> I don't really familiar the quickfix.c, but in the patch:
>
> +    /* Shorten all the file names, so that it is easy to read */
> +    shorten_fnames(TRUE);
>
> I noticed that will it shorten_fnames is invoked in void qf_list(exarg_T
> *eap) . does it have to calculate every file names listed in the buffer
> after every :caddexpr ? a complexity of O(N*N) ?
>

Yes. This is the performance penalty I was referring to in my previous e-mail.

>
> Is this a little inefficient ?? I supposed that each single :caddexpr will
> only solve the file name needs to be listed.
>

I will send out a patch later today that does this.

- Yegappan

> But like I said, I don't familiar with quickfix.c, may misunderstand the
> patch.
>

**Comment by vim-ml** [comment]
Hi,

On Thu, Apr 26, 2018 at 1:01 PM, Yegappan Lakshmanan
<yegappanl@gmail.com> wrote:
> Hi,
>
> On Thu, Apr 26, 2018 at 10:59 AM, Linwei <vim-dev-github@256bit.org> wrote:
>> I don't really familiar the quickfix.c, but in the patch:
>>
>> +    /* Shorten all the file names, so that it is easy to read */
>> +    shorten_fnames(TRUE);
>>
>> I noticed that will it shorten_fnames is invoked in void qf_list(exarg_T
>> *eap) . does it have to calculate every file names listed in the buffer
>> after every :caddexpr ? a complexity of O(N*N) ?
>>
>
> Yes. This is the performance penalty I was referring to in my previous e-mail.
>
>>
>> Is this a little inefficient ?? I supposed that each single :caddexpr will
>> only solve the file name needs to be listed.
>>
>
> I will send out a patch later today that does this.
>

I am attaching a patch the shortens only the files added to the quickfix
list when opening the quickfix window.

- Yegappan

**Comment by skywind3000** [comment]
Yes, the last patch works as expected, and may I ask .

`shorten_fnames(TRUE);` has been changed to `shorten_fnames(FALSE);`

but there is still a for loop in shorten_fnames:

https://github.com/vim/vim/blob/c3c3e698966fac86dee94799b70947defb85440d/src/fileio.c#L6160-L6174

It will iterate all the buffers in the list. could it be eliminated too ?

**Comment by vim-ml** [comment]
Hi,

On Thu, Apr 26, 2018 at 10:49 PM, Linwei <vim-dev-github@256bit.org> wrote:
> Yes, the last patch works as expected, and may I ask .
>
> shorten_fnames(TRUE); has been changed to shorten_fnames(FALSE);
>
> but there is still a for loop in shorten_fnames:
>
> https://github.com/vim/vim/blob/c3c3e698966fac86dee94799b70947defb85440d/src/fileio.c#L6160-L6174
>
> It will iterate all the buffers in the list. could it be eliminated too ?
>

The remaining shorten_fnames() call is used for the ":clist" and ":llist"
commands. This will not cause any performance problems as these
commands display all the quickfix entries and entries cannot be
dynamically added to the list while the ":clist" command is displaying
the list.

- Yegappan

**Comment by skywind3000** [comment]
Thanks, I will spend more time in reading vim's source.

@brammool , this patch seems work correctly, would you please review it and decide if or not merge into quickfix.c ??

**Comment by vim-ml** [comment]
Hi,

On Fri, Apr 27, 2018 at 7:30 AM, Linwei <vim-dev-github@256bit.org> wrote:
> Thanks, I will spend more time in reading vim's source.
>

Thanks for trying out the patch. The patch still has some performance issues.
Every time a new entry is added to the quickfix list, the buffer name is
shortened (even if the buffer name has already been shortened before).
Need to cache the shortened name in buf->b_sfname and reuse it
for subsequent entries in the same buffer.

- Yegappan

>
> @brammool , this patch seems work correctly, would you please review it and
> decide if or not merge into quickfix.c ??
>

**Comment by skywind3000** [comment]
I can test if you have future patches.

**Comment by vim-ml** [comment]
Hi,

On Fri, Apr 27, 2018 at 7:52 AM, Linwei <vim-dev-github@256bit.org> wrote:
> I can test if you have future patches.
>

An updated patch is attached. The file name of a buffer is shortened only
once with this patch.

- Yegappan

**Comment by vim-ml** [comment]
Hi,

On Fri, Apr 27, 2018 at 8:43 AM, Yegappan Lakshmanan
<yegappanl@gmail.com> wrote:
> Hi,
>
> On Fri, Apr 27, 2018 at 7:52 AM, Linwei <vim-dev-github@256bit.org> wrote:
>> I can test if you have future patches.
>>
>
> An updated patch is attached. The file name of a buffer is shortened only
> once with this patch.
>

A minor update to the patch is attached.

- Yegappan

**Comment by skywind3000** [comment]
I have tested your 4th patch, no problem in my test.

**Comment by skywind3000** [comment]
So, the 4th patch is OK, what's next ?

**Comment by yegappan** [comment]
Pull request #2851 has been created with the patch for this issue.
