### ISSUE TITLE
homebrew install vim error

### ISSUE THREAD

**Issue by huzhidong** [vim/vim#2848]
homebrew install vim , then run vim get error:
dyld: Library not loaded: /usr/local/opt/perl/lib/perl5/5.26.1/darwin-thread-multi-2level/CORE/libperl.dylib
Reason: image not found
zsh: abort      vi

**Comment by nuko8** [comment]
That's most likely to happen when you build Vim with a certain version of Perl, update that Perl to a newer version afterwards and forget to re-build Vim with that updated Perl.  At startup, the dynamic loader tries loading the image of the Perl library with which Vim was built.  So, if the current Perl differs from that Perl, the dynamic loader will exactly report the fact "image not found" to you, resulting in such an abort that you got.

If that is the case, it's the user's or the package manager's responsibility to re-build Vim with dependency libraries every time they are updated; that's neither a Vim error nor bug.

**Comment by k-takata** [comment]
Closing because this is not an issue of Vim itself.
Please report to the package manager of homebrew.

**Comment by huzhidong** [comment]
I see, Thanks!!
