### ISSUE TITLE
manpager.vim - CTRL-] on man page name hangs after remapping with the <nowait> argument

### ISSUE THREAD

**Issue by Jetfrog28** [vim/vim#2852]
Steps to reproduce:
open vim with 'vim +MANPAGER'
```
:Man bash
:nnoremap <nowait> d <C-d>
/sh(1)
^]
```

Expected Behavior:
show man page for `sh(1)`

Result:
hangs with `:call <SNR>28_PreGetPage(v:count)` in command line

Pressing `^C` will take you to the man page, but without syntax highlighting or tag-jumping abilities.  pressing `^o` twice brings you to the previous manpage and restores these features, but the hang will occur again on another tag jump.

`unmap d` will restore normal behavior, and oddly enough it will continue to work even if you enter the same remap command that caused the issue initially.

The hang only occurs if you remap certain keys in this fashion.  For example, remapping `g` this way causes the issue, but remapping `z` does not.

This only seems to affect man page tags.

Tested with stock .vimrc on 2 isolated up-to-date archlinux machines.  Vim was installed with the gvim package from the arch repositories.

**Comment by Jetfrog28** [comment]
> and oddly enough it will continue to work even if you enter the same remap command that caused the issue initially.

This doesn't seem to be consistent.  It's true occasionally, but not repeatably.

**Comment by brammool** [comment]
> Steps to reproduce:
> open vim with 'vim +MANPAGER'
> ```
> :Man bash
> :nnoremap <nowait> d <C-d>
> /sh(1)
> ^]
> ```
> 
> Expected Behavior:
> show man page for `sh(1)`
> 
> Result:
> hangs with `:call <SNR>28_PreGetPage(v:count)` in command line
> 
> Pressing `^C` will take you to the man page, but without syntax highlighting or tag-jumping abilities.  pressing `^o` twice brings you to the previous manpage and restores these features, but the hang will occur again on another tag jump.
> 
> `unmap d` will restore normal behavior, and oddly enough it will continue to work even if you enter the same remap command that caused the issue initially.
> 
> The hang only occurs if you remap certain keys in this fashion.  For example, remapping `g` this way causes the issue, but remapping `z` does not.
> 
> This only seems to affect man page tags.
> 
> Tested with stock .vimrc on 2 isolated up-to-date archlinux machines.  Vim was installed with the gvim package from the arch repositories.

Well, remapping "d" is tricky.  But in this case it can probably be
fixed by changing "norm" to "norm!" in ftplugin/man.vim

-- 
        **  Hello and Welcome to the Psychiatric Hotline **
If you are obsessive-compulsive, please press 1 repeatedly.
If you are co-dependent, please ask someone to press 2.
If you have multiple personalities, please press 3, 4, 5 and 6.
If you are paranoid-delusional, we know who you are and what you want
       - just stay on the line so we can trace the call.
If you are schizophrenic, listen carefully and a little voice will
       tell you which number to press next.
If you are manic-depressive, it doesn't matter which number you press
       - no one will answer.
If you suffer from panic attacks, push every button you can find.
If you are sane, please hold on - we have the rest of humanity on the
        other line and they desparately want to ask you a few questions.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Jetfrog28** [comment]
> changing "norm" to "norm!" in ftplugin/man.vim

That did the trick.  Looks like I should familiarize myself with vim's plugin system.

I'm new to all this, so I just want to check: is this something that warrants me submitting a pull request?  Are there any reasons not to change it?

**Comment by brammool** [comment]
> > changing "norm" to "norm!" in ftplugin/man.vim
> 
> That did the trick.  Looks like I should familiarize myself with vim's
> plugin system.
> 
> I'm new to all this, so I just want to check: is this something that
> warrants me submitting a pull request?  Are there any reasons not to
> change it?

The maintainer of the plugin was CC'ed on the thread.

-- 
Proverb: A nightingale that forgets the lyrics is a hummingbird.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by goweol** [comment]
Because man.vim used such as 'norm ggdd', if you remap 'g' or 'd', the result is unpredictable.
Because I don't see your patch, I just changed and tested.
Please let me know if you don't agree with my patch.
I will send full man.vim file to @brammool separately.
Thanks!

**Comment by Jetfrog28** [comment]
Looks great.  Thank you very much.

**Comment by chrisbra** [comment]
fxied with 85eee130f44a2201d88ca2aeff0af3b11dd75f
