### ISSUE TITLE
Feature request: enable <c-w><leader> in terminal buffers

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#2861]
More often than not, I find myself wanting to use one of my own mappings while in a terminal window. Correct me if I am wrong, this is currently not possible without switching to Normal mode. How about having Vim intercepting the key sequence given by `'termwinkey'` followed by `<leader>`?

So, for example, if map `<leader>a`, then `<c-w><leader>a` in a terminal buffer would execute my mapping.

**Comment by lifepillar** [comment]
To expand a bit on this, I know you may use `tmap`. Something like `tmap <leader>a :echo "hello!"<cr>` would enable what I want (`<c-w><leader>a` would print `hello` in the command line), but it will also have the “side effect” of enabling `<leader>a`, causing this mapping to send the string `hello` to the terminal job.

**Comment by brammool** [comment]
What do you mean with "use one of my own mappings"?  You mean mappings you defined to be used in Normal mode in Vim?  These would not work in a terminal (the expanded mapping goes to the job, not to Vim).
Perhaps you can give a practical example.

**Comment by lifepillar** [comment]
>What do you mean with "use one of my own mappings"? You mean mappings you defined to be used in Normal mode in Vim?

Yes. For example:

```vim
nnoremap <leader>2 2gt
```

Then, in a terminal window, I would type `<c-w><leader>2` to switch to tab 2. Currently, I have to type `<c-\><c-n><leader>2`, which, besides being one more character to type, leaves the terminal window in Normal mode. I would imagine, instead, that `<c-w><leader>2` would leave the window in Terminal mode.

Honestly, I didn't give this too much thought. Maybe, it's not an improvement worth the effort, or it's not an improvement at all.

**Comment by brammool** [comment]
> >What do you mean with "use one of my own mappings"? You mean mappings
> >you defined to be used in Normal mode in Vim?
> 
> Yes. For example:
> 
> ```vim
> nnoremap <leader>2 2gt
> ```
> 
> Then, in a terminal window, I would type `<c-w><leader>2` to switch to tab 2. Currently, I have to type `<c-\><c-n><leader>2`, which, besides being one more character to type, leaves the terminal window in Normal mode. I would imagine, instead, that `<c-w><leader>2` would leave the window in Terminal mode.
> 
> Honestly, I didn't give this too much thought. Maybe, it's not an
> improvement worth the effort, or it's not an improvement at all.

OK, I understand: You want to use a Normal mode mapping after CTRL-W in
a terminal window.

Unfortunately, <leader> can be multiple characters.  That makes it
difficult to handle this.  We could make it work if it is one character,
perhaps that would be sufficient?

However, it gets tricky if the RHS of the mapping is more than one
Normal mode command.  We would need to remember the end of it to decide
when to go back to Terminal-Job mode.

This seems brittle, it would be better if you can use tmap.

-- 
DEAD PERSON:  I don't want to go in the cart!
CUSTOMER:     Oh, don't be such a baby.
MORTICIAN:    I can't take him...
DEAD PERSON:  I feel fine!
CUSTOMER:     Oh, do us a favor...
MORTICIAN:    I can't.
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lifepillar** [comment]
Thanks for your explanation. I think I can live with things as they are ;)

Feel free to close this then.

**Comment by chrisbra** [comment]
closing then.
