### ISSUE TITLE
The 'number' option should probably not affect the output of the :print command

### ISSUE THREAD

**Issue by lkintact** [vim/vim#2862]
When `'number'` is set, `:print` displays line numbers as well as lines. This seems to make it impossible to print lines without line numbers without turning the option off. (Also, the effect of `'number'` on `:print` isn't mentioned in the description of either).

Taking into account there are at least two ways (`:print #` and `:number`) to print line numbers _regardless_ of the option value, maybe, to enable the user to print lines without line numbers when `'number'` is on, the option should not affect the command output?

**Comment by chrisbra** [comment]
looks like this is required by the [posix specification](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/ex.html#tag_20_40_13_31)

**Comment by lkintact** [comment]
Thanks for the link. I'll leave the issue open as a reminder for anyone who decides to add the connection between 'number' and :print to the docs. Please close it if you think it's not needed.

**Comment by lkintact** [comment]
>Please close it if you think it's not needed.

Closing myself: back then I didn't understand it's better to open new separate issues to suggest doc changes.
