### ISSUE TITLE
doc: generated session file does not unload current buffers

### ISSUE THREAD

**Issue by blueyed** [vim/vim#2864]
The help for `:mksession` says (https://github.com/vim/vim/blob/6e19040c4a7fc7a4cb75f61bcd5de224565fdf37/runtime/doc/starting.txt#L1352):

> 3. Unloads all currently loaded buffers.

But the generated session file only includes code to wipe the current buffer (if empty and unnamed, via s:wipebuf).
It uses `:only` however - but that's likely not what the help refers to, is it?

So either the code for the session file should get fixed (e.g. by including `exe 'noautocmd bwipe '.join(filter(range(1, bufnr('$')), 'bufexists(v:val)'))`, see https://github.com/dhruvasagar/vim-prosession/pull/47), or the help needs to be adjusted.

For compatibility reasons this would have to be a new flag with `'sessionoptions'` though possibly, and keeping existing buffers appears to be a valid (and good default) use case after all.

**Comment by brammool** [comment]
Daniel Hahler wrote:

> The help for `:mksession` says (https://github.com/vim/vim/blob/6e19040c4a7fc7a4cb75f61bcd5de224565fdf37/runtime/doc/starting.txt#L1352):
> 
> > 3. Unloads all currently loaded buffers.
> 
> But the generated session file only includes code to wipe the current buffer (if empty and unnamed, via s:wipebuf).
> It uses `:only` however - but that's likely not what the help refers to, is it?
> 
> So either the code for the session file should get fixed (e.g. by including `exe 'noautocmd bwipe '.join(filter(range(1, bufnr('$')), 'bufexists(v:val)'))`, see https://github.com/dhruvasagar/vim-prosession/pull/47), or the help needs to be adjusted.
> 
> For compatibility reasons this would have to be a new flag with `'sessionoptions'` though possibly, and keeping existing buffers appears to be a valid (and good default) use case after all.

Currently, when loading a session file while a window contains changes,
simply fails in a strange way.  You won't get the view back and need to
manually clean it up.

I think that when a user loads a session, what he wants is to get the
view of that session.  Dealing with modified buffers is probably best by
making them hidden.  That way you do get the view your wanted, and you
don't loose any changes.  Only that later you do need to take care of
the hidden, changed buffer(s).

I don't see a reason to actually unload buffers, especially if they are
already hidden.  So that would require a documentation change.

-- 
Nothing is impossible for the man who doesn't have to do it.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by blueyed** [comment]
> I don't see a reason to actually unload buffers, especially if they are already hidden.  So that would require a documentation change.

Agreed.  I assume you will take care of it.
Thanks!

**Comment by lacygoill** [comment]
> So that would require a documentation change.

> Agreed.

OK, so how about this:
```diff
diff --git a/runtime/doc/starting.txt b/runtime/doc/starting.txt
index 971181c55..18bc510ef 100644
--- a/runtime/doc/starting.txt
+++ b/runtime/doc/starting.txt
@@ -1344,7 +1344,9 @@ resulting file, when executed with a ":source" command:
    "options".  Script-local mappings will not be written.
 2. Restores global variables that start with an uppercase letter and contain
    at least one lowercase letter, if 'sessionoptions' contains "globals".
-3. Unloads all currently loaded buffers.
+3. Wipes out the current buffer, if it is empty and unnamed; closes all
+   windows in the current tab page, except the current one; closes all tab
+   pages except the current one.
 4. Restores the current directory if 'sessionoptions' contains "curdir", or
    sets the current directory to where the Session file is if 'sessionoptions'
    contains "sesdir".
```

**Comment by lacygoill** [comment]
The order of the operations was wrong.  New patch:
```diff
diff --git a/runtime/doc/starting.txt b/runtime/doc/starting.txt
index 971181c55..19f7b5a0e 100644
--- a/runtime/doc/starting.txt
+++ b/runtime/doc/starting.txt
@@ -1344,7 +1344,9 @@ resulting file, when executed with a ":source" command:
    "options".  Script-local mappings will not be written.
 2. Restores global variables that start with an uppercase letter and contain
    at least one lowercase letter, if 'sessionoptions' contains "globals".
-3. Unloads all currently loaded buffers.
+3. Closes all windows in the current tab page, except the current one; closes
+   all tab pages except the current one; wipes out the current buffer, if it is
+   empty and unnamed.
 4. Restores the current directory if 'sessionoptions' contains "curdir", or
    sets the current directory to where the Session file is if 'sessionoptions'
    contains "sesdir".
```

**Comment by brammool** [comment]
> The order of the operations was wrong.  New patch:
> ```diff
> diff --git a/runtime/doc/starting.txt b/runtime/doc/starting.txt
> index 971181c55..19f7b5a0e 100644
> --- a/runtime/doc/starting.txt
> +++ b/runtime/doc/starting.txt
> @@ -1344,7 +1344,9 @@ resulting file, when executed with a ":source" command:
>     "options".  Script-local mappings will not be written.
>  2. Restores global variables that start with an uppercase letter and contain
>     at least one lowercase letter, if 'sessionoptions' contains "globals".
> -3. Unloads all currently loaded buffers.
> +3. Closes all windows in the current tab page, except the current one; closes
> +   all tab pages except the current one; wipes out the current buffer, if it is
> +   empty and unnamed.
>  4. Restores the current directory if 'sessionoptions' contains "curdir", or
>     sets the current directory to where the Session file is if 'sessionoptions'
>     contains "sesdir".

I do think we should keep the remark that buffers are unloaded.  But
some may actually become hidden.  It's a bit complicated, we can just
mention it:

3. Closes all windows in the current tab page, except the current one; closes
   all tab pages except the current one (this results in currently loaded
   buffers to be unloaded, some may become hidden if 'hidden' is set or
   otherwise specified); wipes out the current buffer, if it is empty
   and unnamed.

-- 
LAUNCELOT: At last!   A call!  A cry of distress ...
           (he draws his sword, and turns to CONCORDE)
           Concorde!  Brave, Concorde ... you shall not have died in vain!
CONCORDE:  I'm not quite dead, sir ...
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
Fixed by https://github.com/vim/vim/commit/942db23c9cb7532d68048530d749eb84ca94d0cd
