### ISSUE TITLE
"vim -?" should display help page, same as "vim -h"

### ISSUE THREAD

**Issue by dwierenga** [vim/vim#2867]
It's commonplace to type "<command_name> -?" to get help on a command-line program.  Vim should support this as well.

While this may be a much more common pattern for MS-DOS/Windows programs than in Unix programs, it's such a common practice that it all but precludes using "-?" as a command-line argument that does something besides "print program usage help to the terminal".

**Comment by brammool** [comment]
> It's commonplace to type "<command_name> -?" to get help on a command-line program.  Vim should support this as well.
> 
> While this may be a much more common pattern for MS-DOS/Windows programs than in Unix programs, it's such a common practice that it all but precludes using "-?" as a command-line argument that does something besides "print program usage help to the terminal".

I don't recall using "-?" for help.   "?" is a wildcard, thus on Unix it's
very unlikely to be used.

Can you give a few examples of programs that support "-?"  ?

-- 
ARTHUR:  Well, I can't just call you `Man'.
DENNIS:  Well, you could say `Dennis'.
ARTHUR:  Well, I didn't know you were called `Dennis.'
DENNIS:  Well, you didn't bother to find out, did you?
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
Well, not sure if this is really that useful. I think this patch fixes it (not sure if it is really that useful, because one would need to escape the `?` at least on Unix):
```patch
diff --git a/src/main.c b/src/main.c
index 3b366b507..066a6df5c 100644
--- a/src/main.c
+++ b/src/main.c
@@ -2014,6 +2014,7 @@ command_line_scan(mparm_T *parmp)
 #endif
                break;

+           case '?':
            case 'h':           /* "-h" give help message */
 #ifdef FEAT_GUI_GNOME
                /* Tell usage() to exit for "gvim". */
```
```shell
0 109119 chrisbra@debian ~/code/vim-src/src (git)-[master]- % ./vim -\?|head
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled May  4 2018 14:02:33)

usage: vim [arguments] [file ..]       edit specified file(s)
   or: vim [arguments] -               read text from stdin
   or: vim [arguments] -t tag          edit file where tag is defined
   or: vim [arguments] -q [errorfile]  edit file with first error

Arguments:
   --                   Only file names after this
   -g                   Run using GUI (like "gvim")
0 109120 chrisbra@debian ~/code/vim-src/src (git)-[master]- % ./vim -?|head
zsh: no matches found: -?
0 109121 chrisbra@debian ~/code/vim-src/src (git)-[master]- %
```

**Comment by jottkaerr** [comment]
I doubt that Vim will ever see `-?` as an argument unless one is willing to enter `-\?` in the shell or one is working under Windows or in some shell where `?` is not interpreted as a wildcard.
[Edit]Sorry, I didn't see your comment on escaping.[/Edit]

**Comment by chrisbra** [comment]
yes, that's the reason I doubt the usefulness. But then it was only a single line change and it should in theory make it work on windows, which might justify the change again.

**Comment by dwierenga** [comment]
> I don't recall using "-?" for help.   "?" is a wildcard, thus on Unix it's
very unlikely to be used.
> Can you give a few examples of programs that support "-?"  ?

Sure.  nano, psql, mysql, svn, java are the ones I could find easily. Probably lots more..

**Comment by tonymec** [comment]
Others (e.g. hg) answer "option -? not recognized" followed by a "usage page". This, however, is not applicable to Vim since "vim" without arguments normally starts in interactive mode with just an empty buffer (except, of course, with a very nonstandard vimrc) while "hg" with no arguments gives the same usage page as above then quits. Similarly, "zip" (with no arguments) or "zip -?" also give a page of usage then quit. All this on Linux and with no backslash-escaping. (However, I don't think I have files whose name consists of just a dash followed by one character.)

**Comment by ZyX-I** [comment]
Python supports `-?` also.

@tonymec Without backslash-escaping it works in various flavours of POSIX shells, rc (plan 9 shell, has linux port) and bash (latter only by default). Zsh defaults (there are other variants, including POSIX-like behaviour) to error out without executing a command if glob pattern did not match, bash can be configured to do just that as well. Fish also errors out, not sure whether this can be configured not to though, fish authors officially do not like allowing users to do much of configuration. Xonsh shows contiuation dots when I use `-?` and I am not too familiar with syntax to know what it expects me to input. Tcsh errors out as well (if you are willing to use it at all).

I find errorring out being a more sane default then passing argument as-is: I normally do not like software which tries to guess what I meant, especially if it fails at that and many times failing pattern match means error in pattern. Also some programs (Vim included) do accept non-existent files without errorring out and I pretty much never want to have file name looking like a glob pattern.
