### ISSUE TITLE
Using Windows SDK v7.0 x64 version to build latest Vim from Git was failed 

### ISSUE THREAD

**Issue by jiangjianshan** [vim/vim#2870]
Hello,

   I'm using Windows SDK v7.0 x64 version to build Vim 8.0 from Git, but unfortunately it failed. 

![image](https://user-images.githubusercontent.com/20179047/39613353-1fe7c948-4f99-11e8-8c3e-7d181bcf31be.png)
 
   Here is my build script. It is always work before.
----------------------------------- script start : build.cmd -------------------------
@echo off
@rem to build big Vim with OLE, Perl, Python, Ruby and Tcl

set INCLUDE=D:\GnuWin64\include;D:\Lua\include;D:\Ruby\include;%INCLUDE%
set LIB=D:\GnuWin64\lib;D:\Lua\lib;D:\Ruby\lib;%LIB%
set TOOLDIR=D:\
set INSTALL_DIR=D:\Vim
set VIM_SRC_DIR=E:\Gits\vim
set PLUG_MGR=D:\Vim\vimfiles\autoload\plug.vim
set SDK_INCLUDE_DIR=C:\Program Files\Microsoft SDKs\Windows\v7.0\Include
:: to avoid invoke link.sh under src directory
set PATHEXT=%PATHEXT:.sh;=%

cd /d %~dp0

@rem uninstall previous version if it exist
if exist %INSTALL_DIR%\Vim80 (
    cd /d %INSTALL_DIR%\Vim80
    uninstal
)

if exist %VIM_SRC_DIR% (
  cd /d %VIM_SRC_DIR%
  git fetch --all
  git reset --hard origin/master
) else (
  echo "Downloading Vim ..."
  git clone https://github.com/vim/vim.git E:\Gits\vim
)

cd /d %VIM_SRC_DIR%\src

if exist .\ObjCULYHTRAMD64 rmdir /s /q .\ObjCULYHTRAMD64
if exist .\ObjGOULYHTRAMD64 rmdir /s /q .\ObjGOULYHTRAMD64

@rem build for no-GUI version
nmake -f Make_mvc.mak CPU=AMD64 FEATURES=HUGE debug=no GUI=no MBYTE=yes IME=yes DYNAMIC_IME=yes GIME=yes CSCOPE=yes ICONV=yes GETTEXT=yes NETBEANS=yes OPTIMIZE=MAXSPEED SNIFF=yes POSCRIPT=yes PERL=%TOOLDIR%Perl DYNAMIC_PERL=yes PERL_VER=524 PYTHON=%TOOLDIR%python27 DYNAMIC_PYTHON=yes PYTHON_VER=27 PYTHON3=%TOOLDIR%python35 DYNAMIC_PYTHON3=yes PYTHON3_VER=35 LUA=%TOOLDIR%Lua DYNAMIC_LUA=yes LUA_VER=53 RUBY=%TOOLDIR%Ruby DYNAMIC_RUBY=yes RUBY_VER=25 RUBY_VER_LONG=2.4.0 RUBY_PLATFORM=x64-mswin64_90 TCL=%TOOLDIR%Tcl TCL_VER=86 TCL_VER_LONG=8.6 DYNAMIC_TCL=yes

@rem build for GUI version
nmake -f Make_mvc.mak CPU=AMD64 FEATURES=HUGE debug=no GUI=yes OLE=yes MBYTE=yes IME=yes DYNAMIC_IME=yes GIME=yes CSCOPE=yes ICONV=yes GETTEXT=yes NETBEANS=yes OPTIMIZE=MAXSPEED SNIFF=yes POSCRIPT=yes PERL=%TOOLDIR%Perl DYNAMIC_PERL=yes PERL_VER=524 PYTHON=%TOOLDIR%python27 DYNAMIC_PYTHON=yes PYTHON_VER=27 PYTHON3=%TOOLDIR%python35 DYNAMIC_PYTHON3=yes PYTHON3_VER=35 LUA=%TOOLDIR%Lua DYNAMIC_LUA=yes LUA_VER=53 RUBY=%TOOLDIR%Ruby DYNAMIC_RUBY=yes RUBY_VER=25 RUBY_VER_LONG=2.4.0 RUBY_PLATFORM=x64-mswin64_90 TCL=%TOOLDIR%Tcl TCL_VER=86 TCL_VER_LONG=8.6 DYNAMIC_TCL=yes

@rem Copy the "runtime" files into "Vim80"
xcopy /I /Y /F /E ..\.\runtime\* %INSTALL_DIR%\Vim80

@rem Copy the new binaries into the "Vim80" directory
xcopy /I /Y /F *.exe %INSTALL_DIR%\Vim80
xcopy /I /Y /F vimtbar.dll %INSTALL_DIR%\Vim80
xcopy /I /Y /F .\GvimExt\gvimext.dll %INSTALL_DIR%\Vim80\GvimExt64
xcopy /I /Y /F .\xxd\xxd.exe %INSTALL_DIR%\Vim80

@rem Copy vimtutor into "Vim80"
xcopy /I /Y /F ..\vimtutor.* %INSTALL_DIR%\Vim80

@rem install vim
cd /d %INSTALL_DIR%\Vim80
::install -install-popup -install-openwith -add-start-menu -install-icons -create-directories vim -register-OLE
::del /F /S /Q "C:\Users\public\Desktop\gVim Easy 8.0.lnk"
::del /F /S /Q "C:\Users\public\Desktop\gVim Read only 8.0.lnk"

install

xcopy /F /Y E:\Releases\_vimrc %INSTALL_DIR%
xcopy /F /Y E:\Releases\.ycm_extra_conf.py %INSTALL_DIR%

@rem Update the plugins

if exist %PLUG_MGR% (
   vim +PlugUpgrade +qall
   vim +PlugUpdate +qall
) else (
   curl -fLo %INSTALL_DIR%\vimfiles\autoload\plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
   vim +PlugInstall +qall
)

cd /d %~dp0

------------------------------------------ script end ----------------------------------------------

**Comment by skywind3000** [comment]
take the daily build:
https://github.com/vim/vim-win32-installer/releases

**Comment by jiangjianshan** [comment]
Hello @skywind3000 ,

    Could you help to find the reason why I can't build it by myself by the Compiler version I'm using and the scripts. It seems like the newest Vim can't use VC2008 Express which included inside Windows SDK v7.0.

Kindly regards,
Jiang Jianshan

**Comment by chrisbra** [comment]
Have you read the documentation?
https://github.com/vim/vim/blob/master/src/INSTALLpc.txt

**Comment by tonymec** [comment]
IOW, the compiler currently guaranteed to work to compile Vim on Windows is MS Visual Studio Community 2015, which works (IIUC) on Windows XP and later. MS Visual Studio 2008 Express is only needed for older Windows versions (95/98) and it might or might not compile the latest Vim correctly, but IMHO if you're still using such an old version of Windows, it's time to upgrade, either to the latest Windows, or all the way ;-) to Linux.

Best regards,
Tony.

**Comment by jiangjianshan** [comment]
Hello @chrisbra and @tonymec ,

    I will switch the compiler from Visual Studio 2008 Express to Visual Studio Community 2015. Thanks for your hints.

Kindly regards,
Jiang Jianshan

**Comment by chrisbra** [comment]
closing then.

**Comment by k-takata** [comment]
I think this is caused by 8.0.1783 and should be fixed.
`uint8_t` should not be used here. It is a C99 feature but MSVC 2010 or older doesn't support it.
Cc @ntak

@brammool Which is the minimum version of MSVC we should support? Maybe MSVC 2008?

**Comment by brammool** [comment]
> I think this is caused by 8.0.1783 and should be fixed.
> `uint8_t` should not be used here. It is a C99 feature but MSVC 2010
> or older doesn't support it.
> Cc @ntak
> 
> @brammool Which is the minimum version of MSVC we should support? Maybe MSVC 2008?

We have been trying to support MSVC 2008, and we can fix this problem.
uint8_t is defined in libvterm/include/vterm.h, which is not included in
this place.  We can change it to char_u.


-- 
`When any government, or any church for that matter, undertakes to say to
 its subjects, "This you may not read, this you must not see, this you are
 forbidden to know," the end result is tyranny and oppression no matter how
 holy the motives' -- Robert A Heinlein, "If this goes on --"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
