### ISSUE TITLE
Slow escape from edit mode in WSL

### ISSUE THREAD

**Issue by StephaneKazmierczak** [vim/vim#2872]
I am using windows subsystem for Linux (Debian), vim 8 patches 1-1766
For some reason escaping from edit mode with <escape> is super slow, however <^c> is way faster. 
What should I change to get the same speed with the <escape> key ?

**Comment by chrisbra** [comment]
Isn'T that an issue that you should raise with [Microsoft](https://github.com/Microsoft/WSL)?

**Comment by k-takata** [comment]
Aren't you mapping `<Esc>` or something?
Please check if it can be reproduced with `vim --clean`.

**Comment by StephaneKazmierczak** [comment]
Thank you for the help, I checked with vim --clean and it is still the same delay with `<Esc>` compare to `<^c>`
I also checked vi and it is doing the same. to my knowledge `<Esc>` isn't mapped to anything ...

**Comment by chrisbra** [comment]
Please start with a clean setup `vim --clean` and check if this is still reproducible. Also, does it only behave on WSL so slow?

**Comment by StephaneKazmierczak** [comment]
yes @chrisbra I removed my vimrc, started with vim --clean and getting out of edit mode is still slow with `<Esc>` but not `<^c>`, I also tried to log with verbose 12 and saw nothing special. I will try to install the windows version that runs on windows to compare.
I just tried your win32 version, there is no delay at all with `<Esc>` while exiting edit mode and it feels crazy fast overall

**Comment by vim-ml** [comment]
which vim package are you using? Can it be the case that only one of the
versions is slow (If I remember correctly there were a few vim packages and
also I do not have this issue with wsl)?

On Mon, May 7, 2018 at 11:11 AM, stephane <vim-dev-github@256bit.org> wrote:

> yes @chrisbra <https://github.com/chrisbra> I removed my vimrc, started
> with vim --clean and getting out of edit mode is still slow with <Esc>
> but not <^c>, I also tried to log with verbose 12 and saw nothing
> special. I will try to install the windows version that runs on windows to
> compare
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/vim/vim/issues/2872#issuecomment-387135407>
>
> --
> --
> You received this message from the "vim_dev" maillist.
> Do not top-post! Type your reply below the text you are replying to.
> For more information, visit http://www.vim.org/maillist.php
>
> ---
> You received this message because you are subscribed to the Google Groups
> "vim_dev" group.
> To unsubscribe from this group and stop receiving emails from it, send an
> email to vim_dev+unsubscribe@googlegroups.com.
> For more options, visit https://groups.google.com/d/optout.
>



-- 
Vlad C.

**Comment by StephaneKazmierczak** [comment]
I am using packages 
vim 8.0.1766
vim-common
vim-nox 
vim-runtime 
vim-tiny 

But I do think now that it is more related to wsl than vim itself, I have been playing around, using vim -clean, removing my vimrc, setting shortcut for `<Esc>`, using log and and other things, and without any explanation, the speed of escape became normal again.  I only had :inoremap kj <Esc> at that time, after removing the line it was still fast. Also, it seems to slow down after a while but now if I just kill the windows and restart it is fast again...

**Comment by chrisbra** [comment]
I am closing this as being unrelated to Vim

**Comment by thijsbrilleman** [comment]
If you're running vim in tmux, tmux is the culprit.

See https://www.reddit.com/r/vim/comments/40257u/delay_on_esc_with_tmux_and_vim/ to configure tmux correctly and your problems will be gone.
