### ISSUE TITLE
FALLBACK argument to :setfiletype

### ISSUE THREAD

**Issue by lotan** [vim/vim#2884]
After opening .conf files (some, not all), I receive an error ```E518: Unknown option: conf``` back from vim.

This user seems to have a similar problem:
https://stackoverflow.com/questions/44889292/e518-unknown-option-conf-when-starting-vim

Attempt at analysis:
3e54569b17683318e0cb6693ab0024c2ad1e3e8f introduced the FALLBACK argument to :setfiletype.
In line https://github.com/vim/vim/blob/master/src/ex_docmd.c#L12174, ```FALLBACK``` is swallowed. It seems to me something similar needs to happen with the filetype itself as it seems the ```conf``` in https://github.com/vim/vim/blob/master/runtime/filetype.vim#L2124.

As I don't quite understand the options processing, I don't feel confident providing a patch.

**Comment by lacygoill** [comment]
I cannot reproduce.  When I open a `conf` file, no error is raised.  Can you provide a minimal working example?

**Comment by lotan** [comment]
In my current version, I don't have this issue anymore.
