### ISSUE TITLE
The title of the quickfix window is sometimes prefixed by an additional colon

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#2885]
- `vim --version`:      VIM - Vi IMproved 8.0  Included patches: 1-1789
 - Operating system:     Ubuntu 16.04.4 LTS
 - Terminal emulator:    rxvt-unicode v9.22
 - Terminal multiplexer: tmux v2.7
 - `$TERM`:              tmux-256color
 - Shell:                zsh 5.3.1

Here's a MWE:

        fu! Replace_qfl() abort
            call setqflist([], 'r',
                         \ {'items': [{ 'filename': $VIMRUNTIME.'/filetype.vim',
                         \              'lnum': 1,
                         \              'valid': 1 }],
                         \  'title': 'some title',
                         \ })
        endfu

        nno  <silent>  cd  :<c-u>call Replace_qfl()<cr>

        let &stl = "%{exists('w:quickfix_title') ? w:quickfix_title : ''}"

If you write this code in `/tmp/vimrc`, then start Vim like this:

    $ vim -Nu /tmp/vimrc

Then, execute a command to populate the quickfix list:

    :vim /pattern/ $VIMRUNTIME/**/*.vim | cw

Finally press `cd` to invoke the custom function `Replace_qfl()`, the title of the quickfix window as displayed in the status line becomes:

    :some title

While it should be:

    some title

A colon is added in front of the title of the quickfix list.
If you close and re-open the quickfix window, it disappears.

The issue seems to come from `w:quickfix_title`, not from the title itself:

    echo w:quickfix_title
        → ':some title'
           ^ ✘

    echo getqflist({'title':0}).title
        → 'some title'
           ^ ✔

**Comment by lacygoill** [comment]
It can probably be solved by checking for an additional colon in `w:quickfix_title` when the quickfix window is opened for the first time, so I close the issue.

**Comment by vim-ml** [comment]
Hi,

On Tue, May 8, 2018 at 11:08 AM, lacygoill <vim-dev-github@256bit.org> wrote:
> vim --version: VIM - Vi IMproved 8.0 Included patches: 1-1789
> Operating system: Ubuntu 16.04.4 LTS
> Terminal emulator: rxvt-unicode v9.22
> Terminal multiplexer: tmux master
> $TERM: tmux-256color
> Shell: zsh 5.3.1
>
> Here's a MWE:
>
>     fu! Replace_qfl() abort
>         call setqflist([], 'r',
>                      \ {'items': [{ 'filename': $VIMRUNTIME.'/filetype.vim',
>                      \              'lnum': 1,
>                      \              'valid': 1 }],
>                      \  'title': 'some title',
>                      \ })
>     endfu
>
>     nno  <silent>  cd  :<c-u>call Replace_qfl()<cr>
>
>     let &stl = "%{exists('w:quickfix_title') ? w:quickfix_title : ''}"
>
> If you write this code in /tmp/vimrc, then start Vim like this:
>
> $ vim -Nu /tmp/vimrc
>
> Then, execute a command to populate the quickfix list:
>
> :vim /pattern/ $VIMRUNTIME/**/*.vim | cw
>
> Finally press cd to invoke the custom function Replace_qfl(), the title of
> the quickfix window becomes:
>
> :some title
>
> A colon is added in front of the title of the quickfix list.
> If you close and re-open the quickfix window, it disappears.
>

This problem is addressed by  8.0.1831.

- Yegappan

>
> The issue seems to come from w:quickfix_title, not from the title itself:
>
> echo w:quickfix_title
>     → ':some title'
>        ^ ✘
>
> echo getqflist({'title':0})
>     → 'some title'
>        ^ ✔
>

**Comment by lacygoill** [comment]
Indeed I've just tested the patch, and it works great, thank you very much.
