### ISSUE TITLE
terminal broken after patch 8.0.1786 (spurious characters printed)

### ISSUE THREAD

**Issue by dpelle** [vim/vim#2886]
The :terminal command no longer works properly for me
after patch 8.0.1786.  When I run ":terminal", with the following
~/.vimrc-bug (a snippet from my full .vimrc) I see "g8g8" in the terminal
window.  With my full ~/.vimrc, I see even more spurious character
in the terminal.

Steps to reproduce:

```
$ cat ~/.vimrc-bug
set nocompatible                                                                
                                                                                
" Function used to display utf-8 sequence.                                      
func! ShowUtf8Sequence()                                                        
  try                                                                           
    let p = getpos('.')                                                         
    redir => utfseq                                                             
    sil normal! g8                                                              
    redir End                                                                   
    call setpos('.', p)                                                         
    return substitute(matchstr(utfseq, '\x\+ .*\x'), '\<\x', '0x&', 'g')        
  catch                                                                         
    return '?'                                                                  
  endtry                                                                        
endfunc                                                                         
                                                                                
set statusline=%{ShowUtf8Sequence()}  
```
```
$ vim --clean -u ~/.vimrc-bug
:terminal
```
Then observe the characters g8g8 in the terminal. I can't run
any command.  If I type "ls" in the terminal for example, I get:
```
g8g8g8ls: command not found
```
This is with xfce4-terminal.  With xterm it's even worse as
vim enters an endless loop print 8g8g8g8g8g8g8g8g8g8g (etc.).
I need to kill the terminal.

Doing a git bissection, I found that the bug is introduced by
this patch:
```
commit b2ac14c0b5e23f8ab97c5c784bcd83e13ba8ded3
Author: Bram Moolenaar <Bram@vim.org>
Date:   Tue May 1 18:47:59 2018 +0200

    patch 8.0.1786: no test for 'termwinkey'
    
    Problem:    No test for 'termwinkey'.
    Solution:   Add a test.  Make feedkeys() handle terminal_loop() returning
                before characters are consumed.
```

**Comment by brammool** [comment]
Dominique wrote:

> The :terminal command no longer works properly for me
> after patch 8.0.1786.  When I run ":terminal", with the following
> ~/.vimrc-bug (a snippet from my full .vimrc) I see "g8g8" in the terminal
> window.  With my full ~/.vimrc, I see even more spurious character
> in the terminal.
> 
> Steps to reproduce:
> 
> ```
> $ cat ~/.vimrc-bug
> set nocompatible                                                                
>                                                                                 
> " Function used to display utf-8 sequence.                                      
> func! ShowUtf8Sequence()                                                        
>   try                                                                           
>     let p = getpos('.')                                                         
>     redir => utfseq                                                             
>     sil normal! g8                                                              
>     redir End                                                                   
>     call setpos('.', p)                                                         
>     return substitute(matchstr(utfseq, '\x\+ .*\x'), '\<\x', '0x&', 'g')        
>   catch                                                                         
>     return '?'                                                                  
>   endtry                                                                        
> endfunc                                                                         
>                                                                                 
> set statusline=%{ShowUtf8Sequence()}  
> ```
> ```
> $ vim --clean -u ~/.vimrc-bug
> :terminal
> ```
> Then observe the characters g8g8 in the terminal. I can't run
> any command.  If I type "ls" in the terminal for example, I get:
> ```
> g8g8g8ls: command not found
> ```
> This is with xfce4-terminal.  With xterm it's even worse as
> vim enters an endless loop print 8g8g8g8g8g8g8g8g8g8g (etc.).
> I need to kill the terminal.
> 
> Doing a git bissection, I found that the bug is introduced by
> this patch:
> ```
> commit b2ac14c0b5e23f8ab97c5c784bcd83e13ba8ded3
> Author: Bram Moolenaar <Bram@vim.org>
> Date:   Tue May 1 18:47:59 2018 +0200
> 
>     patch 8.0.1786: no test for 'termwinkey'
>     
>     Problem:    No test for 'termwinkey'.
>     Solution:   Add a test.  Make feedkeys() handle terminal_loop() returning
>                 before characters are consumed.
> ```

I suppose when you use :normal you actually want to have the keys
executed in Normal mode, no matter what mode the terminal is in.
However, when using feedkeys() we do want to have the terminal use the
keys.  Both call exec_normal().

OK, let's change this back for when using :normal.

-- 
The early bird gets the worm. If you want something else for
breakfast, get up later.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
