### ISSUE TITLE
Incorrect documentation for c_<S-Tab>

### ISSUE THREAD

**Issue by frangio** [vim/vim#2890]
In the command line, `<S-Tab>` is documented to have the same behavior as `<C-P>`.

https://github.com/vim/vim/blob/39de95257714b76ccd845d081cff57830a79b488/runtime/doc/cmdline.txt#L418-L422

This doesn't seem correct: `<S-Tab>` by itself goes to the last match, even without having first used `'wildchar'` as documented.

**Comment by brammool** [comment]
> In the command line, `<S-Tab>` is documented to have the same behavior as `<C-P>`.
> 
> https://github.com/vim/vim/blob/39de95257714b76ccd845d081cff57830a79b488/runtime/doc/cmdline.txt#L418-L422
> 
> This doesn't seem correct: `<S-Tab>` by itself goes to the last match,
> even without having first used `'wildchar'` as documented.

Right, the documentation isn't clear about the difference.  I'll split
it into two items.

-- 
ARTHUR: Listen, old crone!  Unless you tell us where we can buy a shrubbery,
        my friend and I will ... we will say "Ni!"
CRONE:  Do your worst!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
fixed by https://github.com/vim/vim/commit/7db25fed5de1be922b8cbb0328149469606a0424
