### ISSUE TITLE
Windows 10 Defender reports virus on vimrun.exe

### ISSUE THREAD

**Issue by kgfly** [vim/vim#2895]
Latest Windows 10 Defender (5/10/18) reports virus "**_Win32/Fuery.A!.cl_**" on vimrun.exe.

vimrun.exe is from gvim_8.0.1806_x86.zip or gvim_8.0.1806_x86.exe.

But, I sync the code myself, "**_* (HEAD detached at v8.0.1806)"._** And build it by myself using Visual Studio 2017. However, Windows 10 Defender does NOT reports virus on the built vimrun.exe.

So is it a really virus???

**Comment by janlazo** [comment]
Does it happen in previous releases such as ftp://ftp.vim.org/pub/vim/pc/gvim80-586.exe?

**Comment by k-takata** [comment]
Could you report it to Microsoft?
See: https://github.com/vim/vim-win32-installer/issues/36

**Comment by chrisbra** [comment]
In addition, you can always upload the file to virustotal to have a check from other AV vendors. That can often give a clue

**Comment by kgfly** [comment]
Tried on VirusTotal. It turned to be a false positive.

And reported to MS.
