### ISSUE TITLE
`v:count` not reset when `:normal` is executed from a timer

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#2897]
- `vim --version`:      VIM - Vi IMproved 8.0  Included patches: 1-1789
 - Operating system:     Ubuntu 16.04.4 LTS
 - Terminal emulator:    rxvt-unicode v9.22
 - Terminal multiplexer: tmux v2.7
 - `$TERM`:              tmux-256color
 - Shell:                zsh 5.3.1

I'm not sure whether it's a bug or working as intended, so feel free to close the issue in the latter case.

If I source this line:

    nno  <expr><silent>  j  v:count ? (v:count >= 5 ? "m'".v:count : '').'j' : 'gj'

It installs a mapping which overwrites the default `j` motion to add the current position to the jumplist when it's prefixed by a count greater than `5`.

Now, if I execute `:e $VIMRUNTIME/filetype.vim`, then execute `:norm! 99l`, then press `j`, Vim:

 - opens `$VIMRUNTIME/filetype.vim`
 - moves the cursor 99 characters forward
 - moves one line down

But, if I execute the `:normal` command with a timer:

    call timer_start(1000, {-> execute('norm! 99l')})

Then wait for the callback, then press `j`, the cursor jumps `99` lines down, while I expected only one.
It seems that `v:count` has  kept the value of `99` due to `:norm! 99l`, which makes the `j` mapping move the cursor `99` lines below instead of a single line.

Shouldn't `v:count` have been reset to `0`, like what happens without a timer?

**Comment by brammool** [comment]
>  - `vim --version`:      VIM - Vi IMproved 8.0  Included patches: 1-1789
>  - Operating system:     Ubuntu 16.04.4 LTS
>  - Terminal emulator:    rxvt-unicode v9.22
>  - Terminal multiplexer: tmux v2.7
>  - `$TERM`:              tmux-256color
>  - Shell:                zsh 5.3.1
> 
> I'm not sure whether it's a bug or working as intended, so feel free to close the issue in the latter case.
> 
> If I write this code in `/tmp/vimrc` and source it:
> 
>     nno  <expr><silent>  j  v:count ? (v:count >= 5 ? "m'".v:count : '').'j' : 'gj'
> 
> It installs a mapping which overwrites the default `j` motion to add the current position to the jumplist when it's prefixed by a count greater than `5`.
> 
> Now, if I execute `:e $VIMRUNTIME/filetype.vim`, then execute `:norm! 99l` then press `j`, Vim:
> 
>  - opens `$VIMRUNTIME/filetype.vim`
>  - moves the cursor 99 characters forward
>  - moves one line down
> 
> But, if I execute the `:normal` command with a timer:
> 
>     call timer_start(1000, {-> execute('norm! 99l')})
> 
> Wait for the callback, then press `j`, the cursor jumps `100` lines down, while I expected only one.
> It seems that `v:count` has  kept the value of `99` due to `:norm! 99l`, which makes the `j` mapping move the cursor `99` lines below instead of a single line.
> 
> Shouldn't `v:count` have been reset to `0`, like what happens without a timer?

Yeah, this is unexpected.  What happens is that the count is set before waiting
for a character, and the timer triggers while waiting.  Then when typing "j"
the count isn't set again.

We can either save and restore v:count when executing a timer, or set the count
again after the character was typed.  Not sure what will work best.

-- 
TALL KNIGHT: We are now no longer the Knights Who Say Ni!
ONE KNIGHT:  Ni!
OTHERS:      Sh!
ONE KNIGHT:  (whispers) Sorry.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
