### ISSUE TITLE
Vim IGNORES personal configurations

### ISSUE THREAD

**Issue by 0xCA9E1** [vim/vim#2898]
### Machine Information
- OS: Mac High Sierra
- Version: 10.13.3

---

### Problems
Everything went well until I **upgraded my terminal** (I tried to change to iTerm2 but now use back to simple terminal). 
Vim **cannot read personal configurations** in `~/.vim/` just like `.vim/syntax/*.vim`, but in `/usr/share/vim` come to effect. I use `brew reinstall vim` and it is in vain ......    
Maybe I missed a vital __locating command__ ?

---

Thanks you !

**Comment by chrisbra** [comment]
Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. Closing.
