### ISSUE TITLE
Pressing CTRL-W in terminal moves cursor (regression introduced by patch 8.0.1810)

### ISSUE THREAD

**Issue by dpelle** [vim/vim#2904]
Pressing CTRL-W in the terminal window of the latest vim-8.0.1820 moves
the cursor unexpectedly.

Steps to reproduce:
```
$ vim --clean -c terminal
```
Then press CTRL-W and observe that cursor moves to the beginning of
the line in the terminal. Doing a git bissection, I found that it's a regression
introduced by the recent patch 8.0.1810 (cursor did not move in with
vim-8.0.1809): 
```
commit 56bc8e299cdae1b4606897749ef54a0161381a4a
Author: Bram Moolenaar <Bram@vim.org>
Date:   Thu May 10 18:05:56 2018 +0200

    patch 8.0.1810: buffer of a terminal only updated in Terminal-Normal mode
    
    Problem:    Buffer of a terminal only updated in Terminal-Normal mode.
    Solution:   Copy the terminal window content to the buffer when in
                Terminal-Job mode.
```

**Comment by dpelle** [comment]
Patch 8.0.1821 fixes it. However, it also introduces
another regression when doing:

```
$ ./vim --clean -c 'set nu' -c terminal
```
Then press  CTRL-W  N
And observe that:
* the cursor moves unexpectedly.
* the terminal window does not show line numbers despite being in normal mode.

That was working fine in 8.0.1820.

**Comment by dpelle** [comment]
The following patch appears to fix the issue described in my
previous comment at: 

https://github.com/vim/vim/issues/2904#issuecomment-388575555

```
$ git diff terminal.c
diff --git a/src/terminal.c b/src/terminal.c
index 21ef870de..99f5aad60 100644
--- a/src/terminal.c
+++ b/src/terminal.c
@@ -1606,8 +1606,9 @@ move_terminal_to_buffer(term_T *term)
     vterm_state_get_default_colors(vterm_obtain_state(term->tl_vterm),
                       &term->tl_default_color.fg, &term->tl_default_color.bg);
 
-    if (term->tl_normal_mode)
-       FOR_ALL_WINDOWS(wp)
+    FOR_ALL_WINDOWS(wp)
+    {
+       if (term->tl_normal_mode)
        {
            if (wp->w_buffer == term->tl_buffer)
            {
@@ -1624,6 +1625,10 @@ move_terminal_to_buffer(term_T *term)
                redraw_win_later(wp, NOT_VALID);
            }
        }
+       else
+               redraw_win_later(wp, NOT_VALID);
+    }
+
 }
 
 #if defined(FEAT_TIMERS) || defined(PROTO)
```

I don't understand this code enough to tell whether it's
the best solution, but it appears to work at least.

This ticket is marked as "closed" and I can't re-open it.
I can create a new ticket if it's preferable.

**Comment by brammool** [comment]
No, that's not the right solution.  The problem is that if the snapshot was already updated, the screen updating for switching to Terminal-Normal mode is skipped.

**Comment by dpelle** [comment]
@brammool wrote:

> No, that's not the right solution. The problem is that if the
> snapshot was already updated, the screen updating for
> switching to Terminal-Normal mode is skipped.

Patch 8.0.1830 introduces a change in behavior and I'm
not sure whether it's expected. The cursor now moves to
the beginning of the line when doing:
```
./vim --clean -c terminal
```
or
```
./vim --clean -c 'set nu' -c terminal
```
... followed by pressing CTRL-W  N

Is this expected?

**Comment by brammool** [comment]
Dominique wrote:

> @brammool wrote:
> 
> > No, that's not the right solution. The problem is that if the
> > snapshot was already updated, the screen updating for
> > switching to Terminal-Normal mode is skipped.
> 
> Patch 8.0.1830 introduces a change in behavior and I'm
> not sure whether it's expected. The cursor now moves to
> the beginning of the line when doing:
> ```
> ./vim --clean -c terminal
> ```
> or
> ```
> ./vim --clean -c 'set nu' -c terminal
> ```
> ... followed by pressing CTRL-W  N
> 
> Is this expected?

The code that does this was already there.  It always moves the cursor
to the first column of the last line and then tries to move it to the
right position.  Hmm, the cursor in the terminal is just after the
actual text, and that causes it to become zero.  I can fix that.
And it updates the scrollback an extra time, that should not happen.


-- 
Q: What kind of stuff do you do?
A: I collect hobbies.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
