### ISSUE TITLE
Pop-up menu overlapping terminal is not cleared completely when menu is closed

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#2908]
To reproduce:

1. `vim --clean`
2. `:term`
3. CTRL-W CTRL-X (put the terminal at the bottom half of the screen)
4. Enter Insert mode and press Enter until you reach the line immediately above the status line.
5. Type the following: `vi vim view vi<c-x><c-n>`. At this point, the pop-up menu should overlap the terminal window (see first screenshot below).
6. Press CTRL-Y to dismiss the pop-up menu. You should see that the part of the menu over the terminal window has not been cleared (see second screenshot below).
7. Return to Normal mode and press CTRL-L to clear the screen.

<img width="328" alt="1" src="https://user-images.githubusercontent.com/1193314/39969523-22b5beb4-56dd-11e8-9bb0-90a1a56f92a2.png">

<img width="328" alt="2" src="https://user-images.githubusercontent.com/1193314/39969527-30affebc-56dd-11e8-91cd-66fe7a947dc5.png">

I can reproduce this in macOS with Vim 8.0.1800, but also with the current master.

**Comment by chrisbra** [comment]
this is caused by 6eddadff13164b98fe

Maybe we need to increase the type level of `redraw_all_later()` in `pum_undisplay()` from `SOME_VALID` to `NOT_VALID`
