### ISSUE TITLE
Reproducible crash with matchadd, conceal cursor and submatches

### ISSUE THREAD

**Issue by coderonline** [vim/vim#2910]
In my .vimrc I do not want to have UTF-8 chars if possible, but working with numeric representations of those isn't that comfortable either. For that reason I tried to use Vims conceal feature to replace nr2char(0xE0B4) and alike with a single character. 

In an attempt I used a regex submatch:

`:call matchadd('Conceal', 'nr2char(\(0x[0-9A-Fa-f]*\))', 0, -1, {'conceal': nr2char("\1")})`

This caused a SEGFAULT (and sometimes 'strange' results). I imagine that 'matchadd' must share some code with substitute(), but that should either not lead to crash and work as expected or the expression for conceal cursors should be automatically escaped or something like that. 

Sorry for not creating a bugfix, but the conceal feature is relatively new to me.

**Comment by dpelle** [comment]
I'm not able to reproduce it:
* can you provide all steps to reproduce the crash starting with "vim --clean" if possible?
* which version of Vim are you using and on which OS?
* can you reproduce it with valgrind or the address sanitizer?

**Comment by chrisbra** [comment]
In addition, what is in the file, where you see the crash (e.g. what is matched)?

BTW: `:call matchadd('Conceal', 'nr2char(\(0x[0-9A-Fa-f]*\))', 0, -1, {'conceal': nr2char("\1")})` this does not work as intended. `\1` works only within `:s` or `substitute()` call. For your example, I think `nr2char("\1")` will only return an empty string.

**Comment by chrisbra** [comment]
No more info, I am closing this as unreproducible.
