### ISSUE TITLE
Bug with <nop> mapping on timeout followed by backspace

### ISSUE THREAD

**Issue by ryvnf** [vim/vim#2921]
I have found something that I believe to be a bug. It only affects Vim running in a terminal.

It can be reproduced using the following:

1. Vim running inside terminal that sends ASCII DEL (character code 127) when backspace is pressed
2. The following mappings:

```
set timeout
inoremap <bs> BACKSPACE TRIGGERED
inoremap ab test
inoremap a <nop>
```

Enter insert mode and press `a` and wait for the mapping to time out, now press backspace. This will not trigger the backspace mapping if there is one, and it won't trigger the default action for backspace if there is no mapping. Instead it will insert the ASCII delete character `^?` with character code 127 literally in the text.

The problem also affects command mode, which can be observed by changing `inoremap` to `cnoremap`

Tested on version 8.0 invoked using `vim -u NONE`.

**Comment by ryvnf** [comment]
Same behavior is observed by using:

    inoremap <expr> a ""

**Comment by ryvnf** [comment]
This behavior does not exist in Nvim, which might help someone trying to fix it.

**Comment by chrisbra** [comment]
I went back to v7.2 and it had the same behaviour in `nocp` mode. I believe neovim changed input processing quite a bit.

**Comment by chrisbra** [comment]
Looks like, the timedout flag needs to be reset, if the mapping timedout and did not insert anything.
I think this patch fixes it:
```patch
diff --git a/src/getchar.c b/src/getchar.c
index ff03905b4..21650cd39 100644
--- a/src/getchar.c
+++ b/src/getchar.c
@@ -2857,6 +2857,8 @@ vgetorpeek(int advance)
  * get a character: 3. from the user - get it
  */
                wait_tb_len = typebuf.tb_len;
+               if (timedout)
+                   timedout = FALSE;
                c = inchar(typebuf.tb_buf + typebuf.tb_off + typebuf.tb_len,
                        typebuf.tb_buflen - typebuf.tb_off - typebuf.tb_len - 1,
                        !advance
```

**Comment by chrisbra** [comment]
(sorry, no test, because I don't know how to test the timeout)

**Comment by ryvnf** [comment]
That solves it!

I would recommend removing the `if` and just write `timedout = FALSE` as it is more compact, but I am not the maintainer.

Good job! Please make this into a pull request!

**Comment by brammool** [comment]
Christian wrote:

> Looks like, the timedout flag needs to be reset, if the mapping
> timedout and did not insert anything.
> I think this patch fixes it:
> ```patch
> diff --git a/src/getchar.c b/src/getchar.c
> index ff03905b4..21650cd39 100644
> --- a/src/getchar.c
> +++ b/src/getchar.c
> @@ -2857,6 +2857,8 @@ vgetorpeek(int advance)
>   * get a character: 3. from the user - get it
>   */
>                 wait_tb_len = typebuf.tb_len;
> +               if (timedout)
> +                   timedout = FALSE;
>                 c = inchar(typebuf.tb_buf + typebuf.tb_off + typebuf.tb_len,
>                         typebuf.tb_buflen - typebuf.tb_off - typebuf.tb_len - 1,
>                         !advance
> ```

Thanks.  Since this is complicated stuff, I tend to stay on the safe
side and only reset timedout when typebuf.tb_len is zero.

Would be nice to have a test for this, probably requires running this in
a terminal window.

-- 
I wonder how much deeper the ocean would be without sponges.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
> Would be nice to have a test for this, probably requires running this in a terminal window.

I'll have a look.

**Comment by chrisbra** [comment]
I tried sending various combinations of `<bs>`, `&t_kb` or `^?`.  It never returned the mapping but always an empty space.
```vim
  func Test_map_nop()
    if !has('terminal') ||
      \ has('gui_running') ||
      \ winwidth(0) < 30 ||
      \ winheight(0) < 3 ||
      \ !exists("+t_kb")
      return
    endif
  
    " Prepare buffer text
    let buf = term_start([GetVimProg(), '--clean'], {'term_rows': 3})
  
    call term_sendkeys(buf, ":set timeout timeoutlen=400\<cr>")
    call term_sendkeys(buf, ":inoremap <bs> BACKSPACE ENTERED\<cr>")
    call term_sendkeys(buf, ":inoremap ab test\<cr>")
    call term_sendkeys(buf, ":inoremap a <nop>\<cr>")
    " Enter Insert mode
    call term_sendkeys(buf, "i")
    " Wait for a mapping to timeout
    call term_sendkeys(buf, "a")
    call term_wait(buf, 500)
    " Enter Backspace, should trigger the backspace imap
    call term_sendkeys(buf, &t_kb)
    "call term_sendkeys(buf, "^?")
    "call term_sendkeys(buf, "\<bs>")
    call term_sendkeys(buf, "\<c-c>")
    call WaitForAssert({-> assert_equal("BACKSPACE ENTERED", term_getline(buf, 1))})
    bwipe!
  endfunc
```
