### ISSUE TITLE
Why does check_unpack in dosinst.c enforce vim80 folder?

### ISSUE THREAD

**Issue by graywolf** [vim/vim#2936]
As title says, why is the folder name being enforced to `vim80` (or I guess `vim81` now?)? Why I cannot install vim into `g:/ws/progs/vim` but only into `g:/ws/progs/vim80`? What is the technical reason here?

**Comment by brammool** [comment]
Please ask questions on the maillist, this issue tracker is for issues.

**Comment by graywolf** [comment]
Ok, I'll reword it as an issue.

**Comment by graywolf** [comment]
Done (#2937), sorry about this one. Wording on the new issue should fit into the scope of issue tracker.
