### ISSUE TITLE
Install.exe on windows machine fails when not ran from folder named vim80

### ISSUE THREAD

**Issue by graywolf** [vim/vim#2937]
As title says. Steps to reproduce:

1. compile vim
2. copy relevant parts to g:/ws/progs/vim
3. run install.exe

Actual results:

4. install.exe complains about not being in folder vim80 <-------- ISSUE

Expected results:

4. install.exe works even from folder names vim

**Comment by tonymec** [comment]
That's weird. Are you compiling from the latest sources? (8.1.10 as of this writing). I would expect it to either require vim81, or to cd (after mkdir if necessary) to the appropriate …/vim/vim**81** from anywhere

**Comment by graywolf** [comment]
This was like 3 weeks ago, I'm pretty sure that now it would require `vim81`. That's part of why I've opened this issue, having to change my build script on every new version is bit annoying. I don't think it should check the name at all. If I want to have vim installed in `g:/foagjzdsgrjzd`, why can't I?

**Comment by tonymec** [comment]
IIRC, the executable can be anywhere in the $PATH, but it's better to have $VIM ending in …/vim (typically at $HOME/vim) and for $VIMRUNTIME to be $VIM/vim{version}. Makes it easier for Vim to find its runtime files (and to avoid loading those of a different version).

If you want to make $VIM equal to D:\qwerty\uiop, $VIMRUNTIME to F:\poiu\ytrewq, and to put the executable at E:\Mary\had\a\little\lamb\gvim.exe, go ahead, I think it's even possible to get it to work perfectly; but don't ask me how, and don't complain if it goes awry.

**Comment by brammool** [comment]
This is done intentionally.  It allows for having more than one version of Vim installed.  And it worked for a long time without users running into problems, thus I don't think it is a good idea to change now, just because you wonder why this happens.  Also note that unpacking the .zip archive already has the right name.

**Comment by k-takata** [comment]
The rules for setting `$VIM` and `$VIMRUNTIME` are described in the document. (See `help $VIM` and `help $VIMRUNTIME`.)

Following the rules, we can consider several directory structures. E.g.:

```
1. The standard structure

c:\foo\
  |
  +- vim\
      |
      +- vim81\
           |
           +- gvim.exe, vim.exe and runtime files

2. Remove the "vim" directory

c:\foo\
  |
  +- vim81\
       |
       +- gvim.exe, vim.exe and runtime files


3. Move the executable files to an upper directory

c:\foo\
  |
  +- gvim.exe, vim.exe
  |
  +- vim81\
       |
       +- runtime files

4. Rename "vim81" to "runtime"

c:\foo\
  |
  +- gvim.exe, vim.exe
  |
  +- runtime\
       |
       +- runtime files
```

Current `install.exe` only supports No. 1 and 2, I think.
Supporting other directory structures might be complex (especially for GvimExt).

P.S.
I actually use No. 3 for my installation, but I don't use GvimExt. Therefore I don't need execute `install.exe`.
