### ISSUE TITLE
Could `mapcheck()` return `<Nop>` instead of an empty string, when it finds a mapping whose `rhs` is `<Nop>`?

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#2940]
- `vim --version`:      VIM - Vi IMproved 8.1  Compiled by user
 - Operating system:     Ubuntu 16.04.4 LTS
 - Terminal emulator:    rxvt-unicode v9.22
 - Terminal multiplexer: tmux 2.7
 - `$TERM`:              tmux-256color
 - Shell:                zsh 5.5.1

Some plugin authors use `mapcheck()` to decide whether they can install a mapping.
For example, they can write something like this:

    nno  <plug>(func)  :call Func()<cr>
    if !hasmapto('<plug>(func)') && mapcheck('s', 'n') is# ''
        nmap  s  <plug>(func)
    endif

However, it seems that if `mapcheck()` finds a mapping whose `rhs` is `<nop>`, it returns an empty string, which is the same output as when it doesn't find any mapping:

    $ vim -Nu NONE +'nno s <nop>' +'echo mapcheck("s", "n") is# ""'

The previous shell command should start Vim and display `1` on the command line, because the output of `mapcheck('s', 'n')` is empty, even though there is a mapping whose `lhs` is `s` (`nno s <nop>`).

This can lead to unexpected results.

For example, the `vim-sneak` plugin uses `mapcheck()` [like this](https://github.com/justinmk/vim-sneak/blob/943e08445de3179fbb53e1b951df34998501be28/plugin/sneak.vim#L359):

    if !hasmapto('<Plug>SneakForward') && !hasmapto('<Plug>Sneak_s', 'n') && mapcheck('s', 'n') ==# ''

But I want the `s` key to be disabled, because of a recommendation given in the documentation of another plugin, [vim-sandwich](https://github.com/machakann/vim-sandwich/blob/4679a45801837bfb8727c5460cb07d0fe9aa5677/doc/sandwich.txt#L96-L102):

    NOTE: To prevent unintended operation, the following setting is strongly
          recommended to add to your vimrc.

            nmap s <Nop>
            xmap s <Nop>

    |s| could be easily replaced by |c|l| commands.

This is because `vim-sandwich` uses `s` in various operators (`sa`, `sd`, `sr`).

Since `mapcheck()` returns an empty string, `vim-sneak` overwrites my `s` mapping (`nno s <nop>`), even though it was probably trying to avoid that.

The interpretation of the output of `mapcheck()` can even change if you add a second mapping (`nno sab de`). If the two mappings are sourced in this order:

    nno s <nop>
    nno sab de

Then `mapcheck()` will return `de`, which will probably be correctly  interpreted as the `s` key being not available for a remapping.
This is confirmed by this command which displays `0` on the command line:

    $ vim -Nu NONE +'nno s <nop>' +'nno sab de' +'echo mapcheck("s", "n") is# ""'

But if the two mappings are sourced in the reverse order:

    nno sab de
    nno s <nop>

Then this time, the output of `mapcheck()` is again an empty string, which may be interpreted as the `s` key being available for a remapping.

This is confirmed by this command which displays `1` on the command line:

    $ vim -Nu NONE +'nno sab de' +'nno s <nop>' +'echo mapcheck("s", "n") is# ""'

I suppose a plugin author could also use `maparg()` to be completely sure that remapping a key will not cause any issue, and a user could disable their keys in `~/.vim/after/plugin/`, but would it be possible to make `mapcheck()` return the string `<Nop>` instead of an empty string, when it finds a mapping whose `rhs` is `<Nop>`? And reserve the empty string for when no mapping has been found.

This would prevent plugins which use `mapcheck()` from, sometimes and inconsistently, overwriting the mapping of a user.

Feel free to close the issue if you disagree, or if it's not possible.

**Comment by brammool** [comment]
>  - `vim --version`:      VIM - Vi IMproved 8.1  Compiled by user
>  - Operating system:     Ubuntu 16.04.4 LTS
>  - Terminal emulator:    rxvt-unicode v9.22
>  - Terminal multiplexer: tmux 2.7
>  - `$TERM`:              tmux-256color
>  - Shell:                zsh 5.5.1
> 
> Some plugin authors use `mapcheck()` to decide whether they can install a mapping.
> For example, they can write something like this:
> 
>     nno  <plug>(func)  :call Func()<cr>
>     if !hasmapto('<plug>(func)') && mapcheck('s', 'n') is# ''
>         nmap  s  <plug>(func)
>     endif
> 
> However, it seems that if `mapcheck()` finds a mapping whose `rhs` is `<nop>`, it returns an empty string, which is the same output as when it doesn't find any mapping:
> 
>     $ vim -Nu NONE +'nno s <nop>' +'echo mapcheck("s", "n") is# ""'
> 
> The previous shell command should start Vim and display `1` on the command line, because the output of `mapcheck('s', 'n')` is empty, even though there is a mapping whose `lhs` is `s` (`nno s <nop>`).
> 
> This can lead to unexpected results.
> 
> For example, the `vim-sneak` plugin uses `mapcheck()` [like this](https://github.com/justinmk/vim-sneak/blob/943e08445de3179fbb53e1b951df34998501be28/plugin/sneak.vim#L359):
> 
>     if !hasmapto('<Plug>SneakForward') && !hasmapto('<Plug>Sneak_s', 'n') && mapcheck('s', 'n') ==# ''
> 
> But I want the `s` key to be disabled, because of a recommendation given in the documentation of another plugin, [vim-sandwich](https://github.com/machakann/vim-sandwich/blob/4679a45801837bfb8727c5460cb07d0fe9aa5677/doc/sandwich.txt#L96-L102):
> 
>     NOTE: To prevent unintended operation, the following setting is strongly
>           recommended to add to your vimrc.
> 
>             nmap s <Nop>
>             xmap s <Nop>
> 
>     |s| could be easily replaced by |c|l| commands.
> 
> This is because `vim-sandwich` uses `s` in various operators (`sa`, `sd`, `sr`).
> 
> Since `mapcheck()` returns an empty string, `vim-sneak` overwrites my `s` mapping (`nno s <nop>`), even though it was probably trying to avoid that.
> 
> The interpretation of the output of `mapcheck()` can even change if you add a second mapping (`nno s<esc> <esc>`). If the two mappings are sourced in this order:
> 
>     nno s <nop>
>     nno s<esc> <esc>
> 
> Then `mapcheck()` will return `<Esc>`, which will probably be correctly  interpreted as the `s` key being not available for a remapping.
> This is confirmed by this command which displays `0` on the command line:
> 
>     $ vim -Nu NONE +'nno s <nop>' +'nno s<esc> <esc>' +'echo mapcheck("s", "n") is# ""'
> 
> But if the two mappings are sourced in the reverse order:
> 
>     nno s<esc> <esc>
>     nno s <nop>
> 
> Then this time, the output of `mapcheck()` is again an empty string, which may be interpreted as the `s` key being available for a remapping.
> 
> This is confirmed by this command which displays `1` on the command line:
> 
>     $ vim -Nu NONE +'nno s<esc> <esc>' +'nno s <nop>' +'echo mapcheck("s", "n") is# ""'
> 
> I suppose one could also use `maparg()` to be completely sure that remapping a key will not cause any issue, but would it be possible to make `mapcheck()` return the string `<Nop>` instead of an empty string, when it finds a mapping whose `rhs` is `<Nop>`? And reserve the empty string for when no mapping has been found.
> 
> This would prevent plugins which use `mapcheck()` from, sometimes and inconsistently, overwriting the mapping of a user.
> 
> Feel free to close the issue if you disagree, or if it's not possible.

You can get "<Nop>" if you use maparg() and have it return a Dict.
But with mapcheck() this is not possible.  And returning the same thing
for two very different situations is not good.  So let's change it.

-- 
I used to wonder about the meaning of life.  But I looked it
up in the dictionary under "L" and there it was - the meaning
of life.  It was less than I expected.              - Dogbert

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
