### ISSUE TITLE
balloon_show doesn't display the balloon

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#2948]
version: GVim 8.1.16 with (+balloon_eval)

```VimL
balloon_show({expr})					*balloon_show()*
		Show {expr} inside the balloon.  For the GUI {expr} is used as
		a string.  For a terminal {expr} can be a list, which contains
		the lines of the balloon.  If {expr} is not a list it will be
		split with |balloon_split()|.
```

reproduce:
- gvim -u NONE
- :call balloon_show("my balloon")

I can't see my balloon.

**Comment by chrisbra** [comment]
Hm, it looks like `BalloonEval` is initially not set therefore skipping displaying the balloon.

Shouldn't we need something like this?
```patch
diff --git a/src/evalfunc.c b/src/evalfunc.c
index 2793803b7..a1e243a9e 100644
--- a/src/evalfunc.c
+++ b/src/evalfunc.c
@@ -1481,6 +1481,8 @@ f_atan2(typval_T *argvars, typval_T *rettv)
     static void
 f_balloon_show(typval_T *argvars, typval_T *rettv UNUSED)
 {
+    if (balloonEval == NULL)
+       balloonEval = (BalloonEval *)alloc(sizeof(BalloonEval));
     if (balloonEval != NULL)
     {
        if (argvars[0].v_type == VAR_LIST
```

**Comment by skywind3000** [comment]
I have applied your patch, and find another problem:

sometimes `balloon_show` works, sometimes doesn't. and I traced into `gui_mch_post_balloon`:

```c
    void
gui_mch_post_balloon(BalloonEval *beval, char_u *mesg)
{
    POINT   pt;

    // TRACE0("gui_mch_post_balloon {{{");
    logout("[gui_mch_post_balloon] step1 %d/%d", (int)beval->showState, (int)ShS_SHOWING);
    if (beval->showState == ShS_SHOWING)
	return;
    GetCursorPos(&pt);
    ScreenToClient(s_textArea, &pt);

    if (abs(beval->x - pt.x) < 3 && abs(beval->y - pt.y) < 3)
    {
	/* cursor is still here */
	gui_mch_disable_beval_area(cur_beval);
	beval->showState = ShS_SHOWING;
	make_tooltip(beval, (char *)mesg, pt);
    }
    // TRACE0("gui_mch_post_balloon }}}");
}
```

after calling `balloon_show` several times, `beval->showState` will change to `ShS_SHOWING` and this function returns immediately because it thinks the balloon is showing, but actully not. and `balloon_show` doesn't work any more.

**Comment by chrisbra** [comment]
From my very brief testing I haven't noticed that. So how can this be reproduced? Since the above code is from gui_w32.c perhaps this only happens on windows?

**Comment by skywind3000** [comment]
reproduce: repeatly execute `:call balloon_show("my balloon")` three or more times. I have no idea if it is a win32 problem, seems like an internal state problem of `beval->showState`

I can check it later on linux.

**Comment by chrisbra** [comment]
Yes, in the terminal, we have this code:
https://github.com/vim/vim/blob/833093bfb0e4a7f89b5adc66babcfa8ac09cfda9/src/beval.c#L140-L147
and then ui_post_balloon:
https://github.com/vim/vim/blob/833093bfb0e4a7f89b5adc66babcfa8ac09cfda9/src/popupmnu.c#L1035-L1038
So it will always first remove it.

The GTK Version does this using the key_event callback when waiting for input
https://github.com/vim/vim/blob/833093bfb0e4a7f89b5adc66babcfa8ac09cfda9/src/gui_beval.c#L478
called from `gui_mch_wait_for_chars()`
https://github.com/vim/vim/blob/833093bfb0e4a7f89b5adc66babcfa8ac09cfda9/src/gui_gtk_x11.c#L6702-L6708

I suppose we need something similar in `gui_mch_wait_for_chars()` in gui_w32.c
https://github.com/vim/vim/blob/833093bfb0e4a7f89b5adc66babcfa8ac09cfda9/src/gui_w32.c#L2116

I don't know what the function needs to be called, `delete_tooltip(cur_beval)` if it is non null?

**Comment by skywind3000** [comment]
I don't have a gtk environment, nor mac vim.  I tested on linux terminal, and couldn't see any balloon messages either after `balloon_eval` .

edit: my terminal vim has +balloon_eval_term and `balloon_evalterm` was enabled.

**Comment by k-takata** [comment]
Maybe related? #1512

**Comment by chemzqm** [comment]
Not works in my terminal vim 8.1.50 on Mac (compiled with brew)
even after set `balloon_eval_term` and `balloon_eval`

**Comment by chemzqm** [comment]
Also not works with my macvim version: 8.1 1-39, latest installed via brew.
The macvim is complied with `balloon_eval` and `balloon_eval_term` and I have set
```
  set balloonevalterm
  set ballooneval
```

**Comment by chemzqm** [comment]
I find the way to make it works in my iTerm2:
``` vim
let s:timer = -1

function! s:BalloonShow(...)
  let s:message =
          \ 'Cursor is at line ' . v:beval_lnum .
          \', column ' . v:beval_col .
          \ ' of file ' .  bufname(v:beval_bufnr) .
          \ ' on word "' . v:beval_text . '"'
  call c(s:message)
endfunction

function! MyBalloonExpr()
  call timer_stop( s:timer )
  let s:timer = timer_start(100, function('s:BalloonShow'))
  return ''
endfunction

set mouse=a
set ttymouse=sgr
set balloonexpr=MyBalloonExpr()
set balloondelay=300
set ballooneval
set balloonevalterm
```
I have to set `balloondelay=300` and call `balloon_show` in an async way.

**Comment by smhc** [comment]
It may be unrelated, but I have not been able to have balloons show using any of the proposed tests/workarounds when using putty (v70 - 32 bit, or 32/64 bit builds of latest snapshopt: https://www.chiark.greenend.org.uk/~sgtatham/putty/snapshot.html) on Linux (OEL 6.9) with the latest builds of vim. I can get other 'popups' to appear, i.e completion menus and right click termdebug menus. I have tried many different 'TERM' settings and also tried within a tmux session.

The balloons show fine using the WSL bash.exe terminal client when connecting to the same Linux machine.

Can anyone confirm if they have balloons working through putty?

**Comment by chrisbra** [comment]
I wonder if patch [8.1.1300](2f10658b06bbdd8f25c4ff15226) fixed this.

**Comment by brammool** [comment]
There are too many different situations in this issue.  Let's close this, and if you still see a problem, please open a new issue, mentioning the context and an example of how to reproduce.
