### ISSUE TITLE
Test_terminal_scrollback fails if terminal > 125 lines

### ISSUE THREAD

**Issue by tjkirch** [vim/vim#2952]
If I try to build vim with my terminal taller than 125 lines, as seen with `tput lines`, I get this failure:

```
From test_terminal.vim:
Found errors in Test_terminal_scrollback():
function RunTheTest[38]..Test_terminal_scrollback line 13: Expected range 91 - 100, but got 90
TEST FAILURE
make: *** [report] Error 1
```

If I increase lines further to 147, you can see the value at the end of the error change:

```
From test_terminal.vim:
Found errors in Test_terminal_scrollback():
function RunTheTest[38]..Test_terminal_scrollback line 13: Expected range 91 - 100, but got 80
TEST FAILURE
make: *** [report] Error 1
```

If I decrease my terminal to 125 lines or less, the test passes and vim builds OK.

I'm building the latest git commit as of the time of writing this, which is 833093bfb0e4a7f89b5adc66babcfa8ac09cfda9 or Vim v8.1.0022.  I've had this trouble for some time, though.

My build process is:

```
make clean
./configure --prefix "${HOME}/local" --with-features=huge --enable-rubyinterp=no --enable-pythoninterp=yes --with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu --disable-netbeans --disable-gpm --enable-multibyte --with-x --disable-selinux
make -j8
pushd src/testdir
make clean
make nongui  # <-- failure happens in unit tests here
popd
make install
```

Here's my bugreport.txt header:

```
uname -a
Linux u480fcf3b680b56e1fd20 4.4.0-109-generic #132~14.04.1-Ubuntu SMP Tue Jan 9 21:46:42 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

VIM - Vi IMproved 8.1 (2018 May 17, compiled May 24 2018 12:08:16)
Included patches: 1-22
Compiled by tjk@u480fcf3b680b56e1fd20
Huge version without GUI.  Features included (+) or not (-):
+acl               +cmdline_compl     -ebcdic            -hangul_input      -lua               +mouse_xterm       +python            +tag_binary        +vertsplit         -xpm
+arabic            +cmdline_hist      +emacs_tags        +iconv             +menu              +multi_byte        -python3           +tag_old_static    +virtualedit       +xsmp_interact
+autocmd           +cmdline_info      +eval              +insert_expand     +mksession         +multi_lang        +quickfix          -tag_any_white     +visual            +xterm_clipboard
-autoservername    +comments          +ex_extra          +job               +modify_fname      -mzscheme          +reltime           -tcl               +visualextra       -xterm_save
-balloon_eval      +conceal           +extra_search      +jumplist          +mouse             -netbeans_intg     +rightleft         +termguicolors     +viminfo           
+balloon_eval_term +cryptv            +farsi             +keymap            -mouseshape        +num64             -ruby              +terminal          +vreplace          
-browse            +cscope            +file_in_path      +lambda            +mouse_dec         +packages          +scrollbind        +terminfo          +wildignore        
++builtin_terms    +cursorbind        +find_in_path      +langmap           -mouse_gpm         +path_extra        +signs             +termresponse      +wildmenu          
+byte_offset       +cursorshape       +float             +libcall           -mouse_jsbterm     -perl              +smartindent       +textobjects       +windows           
+channel           +dialog_con        +folding           +linebreak         +mouse_netterm     +persistent_undo   +startuptime       +timers            +writebackup       
+cindent           +diff              -footer            +lispindent        +mouse_sgr         +postscript        +statusline        +title             +X11               
+clientserver      +digraphs          +fork()            +listcmds          -mouse_sysmouse    +printer           -sun_workshop      -toolbar           +xfontset          
+clipboard         -dnd               +gettext           +localmap          +mouse_urxvt       +profile           +syntax            +user_commands     -xim               
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/home/local/ANT/tjk/local/share/vim"
Compilation: gcc -std=gnu99 -c -I. -Iproto -DHAVE_CONFIG_H     -march=native -pipe -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc -std=gnu99   -L/usr/local/lib -Wl,--as-needed -o vim    -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl   -ldl    -L/usr/lib/python2.7/config-x86_64-linux-gnu -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions       
```

**Comment by brammool** [comment]
> If I try to build vim with my terminal taller than 125 lines, as seen with `tput lines`, I get this failure:
> 
> ```
> >From test_terminal.vim:
> Found errors in Test_terminal_scrollback():
> function RunTheTest[38]..Test_terminal_scrollback line 13: Expected range 91 - 100, but got 90
> TEST FAILURE
> make: *** [report] Error 1
> ```
> 
> If I increase lines further to 147, you can see the value at the end of the error change:
> 
> ```
> >From test_terminal.vim:
> Found errors in Test_terminal_scrollback():
> function RunTheTest[38]..Test_terminal_scrollback line 13: Expected range 91 - 100, but got 80
> TEST FAILURE
> make: *** [report] Error 1
> ```
> 
> If I decrease my terminal to 125 lines or less, the test passes and vim builds OK.


Please try this simple change:


--- /home/mool/vim/git/vim81/src/testdir/test_terminal.vim	2018-05-15 23:53:22.100994659 +0200
+++ testdir/test_terminal.vim	2018-05-25 21:32:34.698182317 +0200
@@ -270,7 +270,7 @@
 endfunc
 
 func Test_terminal_scrollback()
-  let buf = Run_shell_in_terminal({})
+  let buf = Run_shell_in_terminal({'term_rows': 15})
   set termwinscroll=100
   call writefile(range(150), 'Xtext')
   if has('win32')

Let me know if that fixes the problem.

-- 
At some point in the project somebody will start whining about the need to
determine the project "requirements".  This involves interviewing people who
don't know what they want but, curiously, know exactly when they need it.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by tjkirch** [comment]
That does fix it, thank you!  I tried with my terminal at 48, 73, 125, 126, and 147 lines, and all were successful.
