### ISSUE TITLE
How can I "clear" my terminal buffer

### ISSUE THREAD

**Issue by srihari93** [vim/vim#2954]
Hi,

While using the :terminal in vim, I have performance issues when the logs being printed in the terminal exceed a few thousand lines. Is there a way to "clear" some those lines manually.

I tried deleting them but the modifiable is unset on the buffer and I "cannot set modifiable for a terminal with running job"

**Comment by chrisbra** [comment]
hmm, you might want to play with the ['termwinscroll'](http://vimhelp.appspot.com/options.txt.html#'termwinscroll') options.

**Comment by srihari93** [comment]
Perfect. 
Something like `:set termwinscroll=100` worked.
Thank you.

**Comment by chrisbra** [comment]
Note: Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here.
