### ISSUE TITLE
Fugitive branch name not truncated

### ISSUE THREAD

**Issue by dylan-chong** [vim/vim#2959]
![screen shot 2018-05-27 at 2 02 02 pm](https://user-images.githubusercontent.com/17482349/40581842-93a19876-61b6-11e8-9243-a7438897cfe1.png)

When on a branch that has a very long name, the branch name in the status line hogs the space.

There should be a good default that truncates the length of the branch.

**Comment by dpelle** [comment]
If it's about the fugitive plugin, then you should report this
at https://github.com/tpope/vim-fugitive and then close this
issue as it's not something that vim can do.

**Comment by dylan-chong** [comment]
Oops  just realised i created this on the wrong repo!. Im not sure how i got here
