### ISSUE TITLE
Cannot enter command after :ls, :oldfiles, etc… is invoked in terminal window

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#2960]
Run `vim --clean`, then open a terminal window and type `<c-w>:ls<enter>`. At the `Press ENTER or type command to continue` prompt, type `:`. Unexpectedly, the command is ended the colon is inserted into the terminal window. I would expect to be able to type a command instead.

**Comment by brammool** [comment]
> Run `vim --clean`, then open a terminal window and type
> `<c-w>:ls<enter>`. At the `Press ENTER or type command to continue`
> prompt, type `:`. Unexpectedly, the command is ended the colon is
> inserted into the terminal window. I would expect to be able to type a
> command instead.

I see the problem.  After entering the ":" it returns to the main loop,
thinking that it will be handled in Normal mode, but for a terminal
window it goes into the terminal Job.  We should be able to fix that.


-- 
Engineers understand that their appearance only bothers other people and
therefore it is not worth optimizing.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
I think this is fixed by 1d4754f96fa5bff1c349c
