### ISSUE TITLE
malware warning by windows defender on the gvim81.exe install

### ISSUE THREAD

**Issue by damnskippy** [vim/vim#2961]
Downloaded and installed windows gvim81.exe from vim.org and windows defender produces this alert.  Is this a false positive.  Any one else seeing this? 

![image](https://user-images.githubusercontent.com/5184519/40587624-bdf4cbc8-619f-11e8-9bbb-059f90bd0da8.png)

**Comment by brammool** [comment]
Very likely a false positive.  Something similar was reported, but I believe it's the same virus checker.
I think we can close this.

**Comment by k-takata** [comment]
@damnskippy Could you report it to Microsoft?
See #2933, #2895, vim/vim-win32-installer#36, etc.
