### ISSUE TITLE
exists('#TerminalOpen') returns 0 in Vim 8.1

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#2976]
```text
							*TerminalOpen*
TerminalOpen			Just after a terminal buffer was created, with
				`:terminal` or |term_start()|. This event is
				triggered even if the buffer is created
				without a window, with the ++hidden option.
```
reproduce:

```VimL
:echo exists('#TerminalOpen')
```
output is 0. But it is supposed to return 1.

I want to turn off line number for a terminal buffer and `TerminalOpen` event is required in my autocmd. But to keep compatible to old vims, I need detect if it is supported.

**Comment by tyru** [comment]
This returns 1.

```vim
au TerminalOpen * echom 'open!'
echo exists('#TerminalOpen')
```

from `:help exists()`

> #event		autocommand defined for this event

`exists('#TerminalOpen')` checks if any autocommand is defined for `TerminalOpen` (not `TerminalOpen` is usable or not).
If you want to check `TerminalOpen` is usable, just check by `v:version >=# 801` or `has("patch-8.0.1596")`.

**Comment by jamessan** [comment]
It seems you missed the other part of the help that mentions using `##event` to check if the event is supported.

`:echo exists('##TerminalOpen')` should do what's requested.

**Comment by tyru** [comment]
@jamessan oh... thanks! I didn't know that.
