### ISSUE TITLE
Input is invisible in terminal window

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#2977]
Version: 8.1.22
OS: Debian 9

reproduce:
- `:term` to open a new terminal window
- `CTRL+\ CTRL+N` to enter terminal normal mode
- `:vs` to clone a terminal window in a vertical split
- `i` to enter insert mode in the right terminal window
- input `ls -la`

`ls -la` is only visible in the left window:

![missing](https://user-images.githubusercontent.com/3035071/40874922-49a20858-66a9-11e8-9aea-0b6d538f6822.png)

**Comment by brammool** [comment]
Linwei wrote:

> Version: 8.1.22
> OS: Debian 9
> 
> reproduce:
> - `:term` to open a new terminal window
> - `CTRL+\ CTRL+N` to enter terminal normal mode
> - `:vs` to clone a terminal window in a vertical split
> - `i` to enter insert mode in the right terminal window
> - input `ls -la`
> 
> `ls -la` is only visible in the left window:
> 
> ![missing](https://user-images.githubusercontent.com/3035071/40874922-49a20858-66a9-11e8-9aea-0b6d538f6822.png)

I can reproduce it.

-- 
hundred-and-one symptoms of being an internet addict:
24. You realize there is not a sound in the house and you have no idea where
    your children are.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by skywind3000** [comment]
Does https://github.com/vim/vim/commit/3194e5bf87f8e08f519b947a03c46677616cd7e3 also work for this issue ?

**Comment by skywind3000** [comment]
and this line:

    - With a vertical split only one window is updated. (Linwei, 2018 Jun 2, #2977)

in todo.txt can also be removed
