### ISSUE TITLE
vim formating not working with "==" command 

### ISSUE THREAD

**Issue by ghost** [vim/vim#2980]
Following issues observed in **vim version 8.0.1813**
Linux version: CentOS Linux release 7.3.1611 (Core)

1. vim formatting with **==** command not working in both normal and visual mod
2. New line insert below the current line with command **o** in normal mode inserting cursor at beginning of new line but not auto-indenting according to previous line.

Please find attached screenshot

![capture](https://user-images.githubusercontent.com/3097226/40904543-b1a6bd36-67f8-11e8-94d5-43cf80ef65ec.JPG)

**Comment by k-takata** [comment]
Does it occur when you execute Vim with `vim --clean`?

**Comment by chrisbra** [comment]
I think you are having a configuration issue here. Try enabling `:filetype plugin indent on` to have cindent being set for cpp files. I suppose this will also fix your `==` issue. 
Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. Closing.
