### ISSUE TITLE
Is it possible to namespace Vim terminal device files?

### ISSUE THREAD

**Issue by lifecrisis** [vim/vim#2981]
I'm wondering if it's possible to namespace Vim terminal device files, especially on Unix-like systems.

For example, opening an gnome-terminal window on Ubuntu and running `tty` may output something like `/dev/pts/2`.  If you open a terminal window in Vim and run `tty`, you may then get `/dev/pts/3`.

Would it be possible to have our device files look like `/dev/vim/pts/3`?

I'm searching for ways to have a shell session know if it's running in a Vim terminal window, and this is the only way I can find that would always work.

An environment variable doesn't work!  If we open a `:terminal` window and then run `gnome-terminal`, the sub-sub-shell will still think it's in a Vim terminal window because it has the environment variable set. If we get clever and `unset` the environment variable, then a sub-sub-shell spawned in the terminal window won't know it's in the terminal window!

It would be really useful to me to make this distinction.  Let me know what you think.

**Comment by brammool** [comment]
Why would you start gnome-terminal from a Vim terminal window?  Sounds like a corner case.
And no, there is no choice in the device name.

**Comment by lifecrisis** [comment]
Well, I often spawn/fork processes from the terminal window.  `gnome-terminal` was just an example.  My main goal here was to find a way for a process to always know if its controlling terminal was a vim terminal window.  I guess there's no way to do that...

An environment variable is O.K., but it doesn't always work as noted above.

This all started because I wanted a more minimalist prompt in my Vim terminal window (I use a big 2-line prompt for full-screen shell sessions).  I can't figure out a way to always know for sure where my shell is running.  Is it a terminal window on it's own? Is it inside of Vim? IDK...

**Comment by lifecrisis** [comment]
I've done some more thinking, I arrived at a solution to my problem. A `VIM_TERMINAL` environment variable indicating that a sub-process is running in a `:terminal` window would be fine for my situation.  

Perhaps `VIM_TERMINAL=0` could indicate a child process that is not in a terminal window, and `VIM_TERMINAL=1` could indicate a child process that is in a terminal window.

This is similar to how Emacs does it (from the Bash documentation):

```
EMACS  If bash finds this variable in the environment when the shell starts 
       with value "t", it assumes  that  the  shell  is  running in an Emacs
       shell buffer and disables line editing.
```

That's just my idea at the moment... consider this a **feature request**!  I would code it up myself, but I'm not sure of where to put the definition for `VIM_TERMINAL`.

Thanks!

**Comment by pavoljuhas** [comment]
Perhaps you could check the parent process of your shell to
distinguish between Vim and gnome-terminal:
```
ps -o ppid= $$ | xargs ps -f
```

**Comment by andymass** [comment]
You might be able to (ab)use the $TERM variable, e.g., set `TERM=xterm-256color^vim` or anything else.  You can create a duplicate terminfo with a different name and strip off the trailing string if necessary.  The advantage is it's one of the few variables passed through SSH.  And semantically speaking, vim's terminal is not really an xterm.

**Comment by lifecrisis** [comment]
Patches 8.1.0049 and 8.1.0050 fixed this problem for me.  Closing this issue.

Many thanks to Christian and Bram!
