### ISSUE TITLE
cannot find <Python.h>

### ISSUE THREAD

**Issue by antoinemadec** [vim/vim#2984]
**OS**: Ubuntu 18.04 LTS

**steps to reproduce**:
```
./configure \
--enable-multibyte \
--enable-perlinterp=dynamic \
--enable-python3interp \
--with-python3-config-dir=/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu \
--enable-luainterp \
--with-luajit \
--enable-cscope \
--enable-gui=gtk2 \
--with-features=huge \
--with-x \
--enable-fontset \
--enable-largefile \
--disable-netbeans \
--with-compiledby="antoinemadec" \
--enable-fail-if-missing

make
```

**issue**: 
```
if_python3.c:70:10: fatal error: Python.h: No such file or directory
 #include <Python.h>
```

**quick fix**:
change ```#include <Python.h>``` for ```#include <python3.6/Python.h>```

**notes**:

- python3.6 is the default python3 version in Ubuntu 18.04 
- python3 packages have been updated and upgraded on Ubuntu 18.04 recently
- both my OS and my Vim git repo are up-to-date

**Comment by alphaCTzo7G** [comment]
Wondering if you know where the `python3 interface` is located in this repository? especially if I have a `vim8` version compiled with python support.

**Comment by tonymec** [comment]
@alphaCTzo7G : see above

`src/if_python3.c` (which includes, possibly among others, `if_py_both.h` in the same `src` directory) is the Python3 interface, written in C like most of the Vim source (especially the backends: some of the frontends are in Vimscript and there may be platform-specific modules in C++ for Windows or Objective-C for Mac OS X). Similarly `if_python.c` is the Python2 interface.

Best regards,
Tony.

**Comment by antoinemadec** [comment]
Is there any news about that ?
I just ```git pull```-ed the repo today, and the issue is still there.

**Comment by alphaCTzo7G** [comment]
@antoinemadec not sure whether this will work for you or not.. as I see you have some specific settings not included in this link.. but I was able to compile the latest VIM with python3 interpreter based on the instructions here a few days back: https://github.com/Valloric/YouCompleteMe/wiki/Building-Vim-from-source

On Ubuntu 16.04

**Comment by antoinemadec** [comment]
Yes, everything works fine on Ubuntu 16.04. The issue is with Ubuntu 18.04.

**Comment by micbou** [comment]
Just tried and it compiles fine. Check if the file `/usr/include/python3.6m/Python.h` exists. If it doesn't, try to reinstall the Python 3 headers:
```sh
sudo apt install python3-dev
```
Check also that Vim includes the `/usr/include/python3.6m` directory when compiling `if_python3.c`. You should see this line in the compilation output:
```sh
gcc -c -I. -I/usr/include/python3.6m -pthread -fPIE  -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/if_python3.o if_python3.c
```
By the way, you don't need to specify the `--with-python3-config-dir` option in the `configure` command. Vim will automatically find the directory.

**Comment by yknnnnft** [comment]
Came up against the same problem in Ubuntu 18.04 and just solved it.

My case is that the files constructed by executing "./confiure" are cached with a python3's version of 3.5,  
while the actual version of python3 has already been upgraded to 3.6.  
Thus when executing "configure",  
/usr/include/python3.5m is not found though /usr/include/python3.6m exists.

I solved the problem just by removing "src/auto/config.cache" before executing configure.

**Comment by antoinemadec** [comment]
@micbou , ```/usr/include/python3.6m/Python.h``` exists on my system but Vim was not including pyhon3.6m when invoking ```gcc```, but python3.5m instead. Also, thanks for the ```--with-python3-config-dir``` tip :smile: 

The bug was a Makefile/dependency issue I guess, an issue that ```make clean``` was not fixing.
The fix for me was to do a ```git clean -xdf``` before compilation. Closing the issue.

**Comment by wilywampa** [comment]
Building in a virtual environment, I had to run

```
ln -s /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m "${VIRTUAL_ENV}/include/python3.7m"
```

**Comment by justfortherec** [comment]
> The bug was a Makefile/dependency issue I guess, an issue that make clean was not fixing.
The fix for me was to do a git clean -xdf before compilation. Closing the issue.

This should be fixed with `make distclean`. `git clean -xdf` is also an option, as you found out.

**Comment by vsydorov** [comment]
If you are building from virtual environment and getting this error try puting the proper symlink in the <VENV_NAME>/include directory.

I was building for self-compiled python with --enable-shared and getting this error until I fixed the symlink. Apparently during the creationg of virtual environment it's not done automatically.
