### ISSUE TITLE
Is loadview conflicted with readonly mode?

### ISSUE THREAD

**Issue by loop0day** [vim/vim#2986]
- When i used following code to keep my folder view, it seemed that `vim -R` and `view` don't work at all (Only [readonly] was shown but it didn't work at all). Is there any misunderstanding about it? Thank you for all the people who can help me.
```vimscript
" save and restore view automatically                                      
autocmd BufWinLeave * silent! mkview                                       
autocmd BufWinEnter * silent! loadview
```

**Comment by chrisbra** [comment]
Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. Closing.
