### ISSUE TITLE
Cannot create tmp file after using vim for a long time

### ISSUE THREAD

**Issue by trisys3** [vim/vim#2987]
I'm following up from the issue opened at the gitgutter plugin, airblade/vim-gitgutter#433.

Essentially, having vim open until its tmp files are deleted throws an error. For me, my team deletes tmp files every night, so I get this problem on every single open vim window when I come in in the morning.

@airblade says the problem is in vim itself, as gitgutter requests a temporary filename through `tempname()`. vim doesn't realize the temp folder has been deleted so it just responds with a different file in the same folder. He suggests fixing this in vim itself.

If there are any other questions, I can try to help with examples, error messages, etc.

**Comment by tonymec** [comment]
IMHO, the problem lies in the policy of deleting temp files every night regardless of whether they are still in use. A "saner" policy would perhaps be deleting temp files that haven't been accessed for (let's say) a week.
One possible way to keep your temp files alive as long as you need them would be starting Vim with `$TEMPDIR` (on Unix) or `$TMP` (on Windows) set to some subdirectory of your home directory, and clean that subdirectory yourself, when appropriate, of files that aren't needed anymore. You could even set those environment variables in your vimrc to avoid interfering with a possible use of the same variables in programs other than Vim and than anything run by Vim.

See
``` vim
    :help tempname()
    :help tempfile
```
Best regards,
Tony.

**Comment by trisys3** [comment]
Thanks, I'll try that.

Not to belabor the point, but I'm not the only one with the issue. I wasn't even the one who opened the original issue on gitgutter, that honor goes to @wsfreund. As I said, I will try this, but what about others who may have different situations?

**Comment by chrisbra** [comment]
This has been discussed several times before (last time e.g. [here](https://groups.google.com/d/msg/vim_dev/vP3ScrWj6tU/rCKl5csjBwAJ). The problem is, that on a running system /tmp/ should not be cleaned. That is asking for trouble. I proposed a patch years ago, but it was never included.

**Comment by brammool** [comment]
> Essentially, having vim open until its tmp files are deleted throws an
> error. For me, my team deletes tmp files every night, so I get this
> problem on every single open vim window when I come in in the morning.

Why in the world does your team delete tmp files?
There really is no reason for it, it can only cause trouble.

> @airblade says the problem is in vim itself, as gitgutter requests a
> temporary filename through `tempname()`. vim doesn't realize the temp
> folder has been deleted so it just responds with a different file in
> the same folder. He suggests fixing this in vim itself.
> 
> If there are any other questions, I can try to help with examples, error messages, etc.

Vim relies on files not disappearing unexpectedly.  I think the only
reasonable action for Vim to take when a file disappears is to throw an
error, preserve files and exit.

-- 
How To Keep A Healthy Level Of Insanity:
17. When the money comes out the ATM, scream "I won!, I won! 3rd
    time this week!!!!!"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by trisys3** [comment]
Yeah, not sure but I'll ask. Thanks, again for the workaround, though, I'll try it if I can't get my team to stop this strange behavior.

**Comment by chrisbra** [comment]
A workaround would be to set the `$TMPDIR` environment to a different temporary directory.
