### ISSUE TITLE
Filename completion (i_CTRL-X_CTRL-F) doesn't work with paths containing :

### ISSUE THREAD

**Issue by sheeit** [vim/vim#2988]
### Test case:
```sh
mkdir -p 'dir_with_:_in_name/subdir'
touch 'dir_with_:_in_name/subdir/file'
vim test.txt
```
And then start typing the name of that directory, then do a `^X ^F`:
`"idir_wi^X^F"`, you'll get: `dir_with_:_in_name/`

Now let's say we want to auto-complete the full path to `file`, so we do `^X^F` again, but it doesn't work,
giving us the "Pattern not found" error.

I've tried both backslash-escaping the colon, and enclosing it in quotes, but neither worked.

I only noticed this with colons, but the same thing happes to paths that contain spaces, and maybe other punctuation.

**Comment by lifepillar** [comment]
Have you tried adding `:` to `isfname`?

**Comment by chrisbra** [comment]
> Have you tried adding : to isfname?

Yes, that should fix it. 

Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. Closing.
