### ISSUE TITLE
Popup menu unusable with omni-completion

### ISSUE THREAD

**Issue by mzanibelli** [vim/vim#2990]
Hi,

The commit 6d41c78e353b630bc1a72cbff9160311d2a81e8c introduced an issue with the popup menu when doing omni-completion.

As soon as the menu appears, it's not focused and won't close.

It seems to be easily reproducible with the following steps assuming the standard runtime script for PHP omni-completion is installed:
* open a clean vim instance with `vim --clean`
* open a PHP file
* trigger completion by typing `<C-X><C-O>` in insert mode (no tags are necessary, the standard PHP library's functions will show up)

Please note that keyword insert mode completion (`<C-P>`) still works as expected: we can cycle through the menu and select an entry.

**Comment by brammool** [comment]
Matéo Zanibelli wrote:

> The commit 6d41c78e353b630bc1a72cbff9160311d2a81e8c introduced an issue with the popup menu when doing omni-completion.

What patch is that?

> As soon as the menu appears, it's not focused and won't close.
> 
> It seems to be easily reproducible with the following steps assuming the standard runtime script for PHP omni-completion is installed:
> * open a clean vim instance with `vim --clean`
> * open a PHP file
> * trigger completion by typing `<C-X><C-O>` in insert mode (no tags are necessary, the standard PHP library's functions will show up)
> 
> Please note that keyword insert mode completion (`<C-P>`) still works as expected: we can cycle through the menu and select an entry.

-- 
I'm not familiar with this proof, but I'm aware of a significant
following of toddlers who believe that peanut butter is the solution
to all of life's problems... 		-- Tim Hammerquist

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mzanibelli** [comment]
@brammool patch 8.1.0035

**Comment by brammool** [comment]
fixed by patch 8.1.0042
