### ISSUE TITLE
getdate builtin function request

### ISSUE THREAD

**Issue by ocskai** [vim/vim#2992]
getdate builtin function could speed up date parsing.
Returned number should fit {time} argument of strftime builtin function. 
(similar to getftime, seconds since epoch)

Currently I use :%s/now/\=(system('date -d '.submatch(0)))[:-2]/g for this purpose
However, 100.000 process invocations needed in a 100.000 line log file...

It should based on the C lib function: struct tm * getdate (const char *string)

**Comment by k-takata** [comment]
Now we have strptime function. (Doesn't work on Windows, though.)
Closing.
