### ISSUE TITLE
Enter terminal normal mode by default.

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#2996]
When I open a file in vim it will not enter insert mode. but why does vim enter terminal insert mode by default if I open a terminal buffer ??

**Comment by chrisbra** [comment]
Probably this is the most sensible behaviour. In any case, if you don't like it, you can use e.g. the following autocommand: `:au TerminalOpen * call feedkeys("\<c-w>N", 't')`.

I am closing this as no bug report. Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. Closing.
