### ISSUE TITLE
Windows with fixed width or height do not always retain their size

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#2998]
I can reproduce with Vim 8.1.39, as follows:

1. Run `vim --clean`
2. Press ctrl-w v to create a vertical split.
3. Create a quickfix window, e.g., with `:make` (it doesn't matter if the window has no entries).
4. `:copen` or `:botright copen`.
5. `:botright new`.
6.  Press CTRL-W c to close the window opened at step 5.

You should see that the height of the quickfix window has increased, despite `winfixheight` being set for such window. That does not happen if at step 2 a horizontal split is created.

**Comment by linusboyle** [comment]
same problem.I can reproduce that

**Comment by lifepillar** [comment]
The issue is more general, as the following tests should show:

```vim
fun! Test_winfixheight_preserved()
  botright 11new
  let l:wid = win_getid()
  setlocal winfixheight
  call assert_equal(11, winheight(l:wid))
  botright new
  bwipe!
  call assert_equal(11, winheight(l:wid))
  %bwipe!
endf

fun! Test_winfixheight_preserved_when_vertical_split_exists()
  vsplit
  botright 11new
  let l:wid = win_getid()
  setlocal winfixheight
  call assert_equal(11, winheight(l:wid))
  botright new
  bwipe!
  call assert_equal(11, winheight(l:wid))
  %bwipe!
endf
```

The first passes, but the second fails. The only difference between the two tests is that a vertical split is open in the second case (the window height has become 17).

**Comment by lifepillar** [comment]
The following tests (both failing in Vim 8.1.300) show that horizontal splits are subject to a similar issue:

```vim
fun! Test_winfixwidth_preserved()
  botright 11vsplit
  let l:wid = win_getid()
  setlocal winfixwidth
  call assert_equal(11, winwidth(l:wid))
  botright vsplit
  wincmd c
  call assert_equal(11, winwidth(l:wid))
  %bwipe!
endf

fun! Test_winfixwidth_preserved_when_horizontal_split_exists()
  split
  botright 11vsplit
  let l:wid = win_getid()
  setlocal winfixwidth
  call assert_equal(11, winwidth(l:wid))
  botright vsplit
  wincmd c
  call assert_equal(11, winwidth(l:wid))
  %bwipe!
endf
```

**Comment by hiberabyss** [comment]
Also have the same problem.

**Comment by hiberabyss** [comment]
@brammool Could you help to have a look of this issue and the PR to fix the issue? Thanks!
