### ISSUE TITLE
Compiler warning in 8.1.0053 on macOS

### ISSUE THREAD

**Issue by chdiza** [vim/vim#3002]
Sometime by 8.1.0053 the following compiler warning appears on macOS 10.13.5:
```
gcc -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/os_unix.o os_unix.c
os_unix.c:4202:34: warning: format specifies type 'long' but the argument has type 'varnumber_T' (aka 'long long') [-Wformat]
        sprintf((char *)envbuf, "%ld",  get_vim_var_nr(VV_VERSION));
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
                                 %lld
/usr/include/secure/_stdio.h:47:56: note: expanded from macro 'sprintf'
  __builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
                                                       ^~~~~~~~~~~
1 warning generated.
```
I don't have time to bisect right now, but this is *very* recent.

**Comment by ghost** [comment]
I'm getting this too, it was introduced in [patch 8.1.0049](d7a137fb0d980545dd567bee9c24cf7b9c3a2eae)

Since this is just the version number, we can accept the compiler's suggestion. Here's a patch:

```patch
diff --git a/src/os_unix.c b/src/os_unix.c
index 71886538e..6b262fd6e 100644
--- a/src/os_unix.c
+++ b/src/os_unix.c
@@ -4199,7 +4199,7 @@ set_child_environment(
 #  ifdef FEAT_TERMINAL
     if (is_terminal)
     {
-	sprintf((char *)envbuf, "%ld",  get_vim_var_nr(VV_VERSION));
+	sprintf((char *)envbuf, "%lld",  get_vim_var_nr(VV_VERSION));
 	setenv("VIM_TERMINAL", (char *)envbuf, 1);
     }
 #  endif
@@ -4227,7 +4227,7 @@ set_child_environment(
     if (is_terminal)
     {
 	vim_snprintf(envbuf_Version, sizeof(envbuf_Version),
-			       "VIM_TERMINAL=%ld", get_vim_var_nr(VV_VERSION));
+			       "VIM_TERMINAL=%lld", get_vim_var_nr(VV_VERSION));
 	putenv(envbuf_Version);
     }
 #  endif
```

**Comment by brammool** [comment]
> I'm getting this too, it was introduced in [patch 8.1.0049](d7a137fb0d980545dd567bee9c24cf7b9c3a2eae)
> 
> Since this is just the version number, we can accept the compiler's
> suggestion. Here's a patch:

The type may differ between systems.  It's easier to add a type cast to
long.

-- 
Latest survey shows that 3 out of 4 people make up 75% of the
world's population.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
