### ISSUE TITLE
job_start("bin") - some bin do not execute inside a function

### ISSUE THREAD

**Issue by guido99** [vim/vim#3003]
If I directly execute

  :let j=job_start("some_exe")

with some_exe=gvim | xpdf | gv | xdvi, all works as expected.

If I put the same statement inside a function, gv & xdvi *no* longer run, but, gvim & xpdf do. job_info(j) & job_status(j) show no errors. Also, inside the function

  call system(bin &)

operates properly on all 4 arguments given above. (But, I do not want to use the system() function)

Feature or bug?

**Comment by chrisbra** [comment]
Try to run it in a shell and capture stdout and stderr output.

**Comment by guido99** [comment]
What I reported was a vim instance run in a xterm running a bash shell.
Could you be more specific?

**Comment by mattn** [comment]
Some appplication might require tty output. And those might deny output to the pipe.

**Comment by guido99** [comment]
The only obvious difference between gv, xdvi & the other examples I cited
is that they run an autoreload ("watch file") function to update changes on
the screen from the input src file.  So, maybe, that's it? job_status()
says it's running, but, nothing is on the screen & htop displays no such
process. I'm using system() with an &. It works.

**Comment by chrisbra** [comment]
> What I reported was a vim instance run in a xterm running a bash shell.

Instead of your pipe, run a `bash -c <pipecommand> 2> /foobar`  command, so you can capture the stderr of your command in the `job_start` function. I also suspect a missing pty or something similar.

**Comment by guido99** [comment]
This works

   function Test()
     let j=job_start('bash -c "gv 2> /tmp/err"')     "gv -> xdvi is also ok.
   end function

File err has minor message about missing charset (not important)

If I omit 2> /tmp/err, it will *not* work. (Can't write to stderr)

If I use as arg for job_start "gv 2> /tmp/err", it will not work.

Inside a function, I need both a shell to launch + a path to an error file.

Outside a *function*, as part of a map statement, for example, all I need is

   let j=job_start("gv")

Same, of course, if I simple give that command preceded by a :

So I ask again. Bug? Feature? Native characteristic? Add documentation to
Channels.txt?

**Comment by chrisbra** [comment]
The help for [job_start](http://vimhelp.appspot.com/eval.txt.html#job_start()) says:

>                 The command is executed directly, not through a shell, the
>                 'shell' option is not used.  To use the shell: 

Piping things is a property of the shell, it won't work when executing jobs directly. So you need to use a shell.

**Comment by guido99** [comment]
But, why, then, the difference between inside & outside a vim function?

**Comment by tonymec** [comment]
In the statement
```
let j = job_start(some_exe)
```
run outside a function, j is a global variable. When the same line is used inside a function, j is local to the function. To access a global variable inside a function, you need to explicitly specify the global scope, by calling the variable g:j instead.

Maybe that makes a difference?


Best regards,
Tony.

**Comment by chrisbra** [comment]
Not sure what you mean with inside the function and outside the function. I found your message hard to read. Please state clearly what works and what doesn't.

However note, that `2>` redirection is a property of your shell, so you need to use a shell command to the `job_start()`

**Comment by guido99** [comment]
Brilliant! You're right j -> g.j does it. I'm embarrassed by my oversight.

Thanks!

Guido99

**Comment by guido99** [comment]
By function I mean a VIM function as described in VIM documentation that
comes with a VIM package.

Anyway, read the two emails below. Vim contributor Tony Mechelynck figured
it out. It has nothing to do with piping or shells.


_RDS_ <rds1944@gmail.com>
1:16 PM (1 minute ago)￼
￼￼
to vim/vim￼
Brilliant! You're right

         j -> g.j

does it, of course. I'm embarrassed by my oversight.

Thanks!

Guido99


On Thu, Jun 14, 2018 at 1:06 PM, Tony Mechelynck <notifications@github.com>
wrote:
In the statement

let j = job_start(some_exe)

run outside a function, j is a global variable. When the same line is used
inside a function, j is local to the function. To access a global variable
inside a function, you ned to explicitly specify the global scope, by
calling the variable g:j instead.

Maybe that makes a difference?

Best regards,
Tony.

**Comment by chrisbra** [comment]
Please try to be concise and state clearly your problem, I have problems understanding your issue. So please be precise and clearly state what you do, what you expect and what you saw. 
Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. Closing.

**Comment by guido99** [comment]
I did my best to describe in detail with code examples of what I thought
was a bug. It is clear that the explanation of job_start() is inadequate in
its current form inside doc/channel.txt (my opinion).

**Comment by chrisbra** [comment]
> It is clear that the explanation of job_start() is inadequate in its current form inside doc/channel.txt 

In what way? What do you think is missing?

**Comment by mattn** [comment]
@guido99 See `:help job_start`.

>The command is executed directly, not through a shell, the 'shell' option is not used.  To use the shell:

job_start() works as expected. And documents is right.

**Comment by mattn** [comment]
Also piping thing is a feature of shell. This is basically knowledge of UNIX not Vim things.

**Comment by guido99** [comment]
Unlike other functions

    call job_start(...)

will not work. That should be noted in docs.

But, most importantly, the variable, eg, jobnum, as in

    let jobnum=job_start(...)

*must* be global, not local. Inside a VimScript function, such a variable
must be denoted explicitly as g:jobnum.

I think these two items are important because the function job_start() is
highly useful. With it, I have built a simple integrated environment (a
VimScript function) to create & edit Latex, Postscript, .. files.

**Comment by jamessan** [comment]
> Unlike other functions call job_start(...) will not work

It works just fine, as long as you don't need to access the job object later.

> But, most importantly, the variable, eg, jobnum, as in let jobnum=job_start(...) *must* be global, not local.

No, that's not true either.  The only requirement is that the variable is accessible for the lifetime that you need it.  If it needs to be accessed outside of a function, then it can be stored inside a script-local variable, buffer-local variable, or whatever makes sense for your plugin.

**Comment by guido99** [comment]
None of what you say is correct. I have tested numerous cases. What I
describe is true & accurate.

What you claim will work occasionally, not consistently. For example,
inside a function, let j=job_start("gvim") is ok, but if I use gv instead
of gvim, it won't. Other examples are readily found.

**Comment by guido99** [comment]
This comment is unrelated to job_start(), but, is to documentation. A
simple example:

The VimScript operator for concatenation is a period char (.) I often
forget that because I code in many languages. It's documented in Vim, but,
hard to find when I forget. Maybe, someone (BM?) add a tag or a few more
words in the text so I could quickly locate it?

**Comment by chrisbra** [comment]
Wrong. Please understand, that you cannot use shell constructs inside the `job_start()` function, as the job is started directly (without a shell in between). That means using `|` or redirection `>.. 2>`, globbing `*` or `&& ||` logical catenation of jobs (and similar ones) etc is a feature of your shell and not of the command being run. So if you want to use those, you need to explicitly call a shell with the job being given as parameter. Running a command most of the time works, as long as the program does not expect to have a terminal available (or stdin attached to it) or similar. There is nothing we can fix this in Vim.

> What you claim will work occasionally, not consistently. For example, inside a function, let j=job_start("gvim") is ok, but if I use gv instead of gvim, it won't. Other examples are readily found.

yes it does. If not, please give concrete examples for what does not work. 

> The VimScript operator for concatenation is a period char (.) I often forget that because I code in many languages. It's documented in Vim, but, hard to find when I forget. Maybe, someone (BM?) add a tag or a few more words in the text so I could quickly locate it?

Those tags already there, e.g. see `:h expr-.` See `:help summary` for finding efficiently the topics you need. Also please note, ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here.

**Comment by guido99** [comment]
You have not read or have not understood all the memos I sent based on
exhaustive testing concerning this issue. (I never claimed there is a
bug.)  One Vim GitHub contributor, Tony M..., fully understood the
situation AND provided the guidance I need to make Vim function as I
desire. Now, let's just drop the matter.

**Comment by andymass** [comment]
This thread is off the rails.. but there is actually something important here which has not yet been clearly understood.  There is an *actual* difference (for me) between the following lines typed into the cmdline:

`:call job_start('xdvi')`

and

`:let j = job_start('xdvi')`

In the former there is no xdvi window popup while in the latter, there is.  This is extremely surprising to me and I assume for anyone else experienced with vimscript.  If it is expected behavior, it is not clearly documented.

@chrisbra, @jamessan are you saying both examples produce the same result for you?

**Comment by jamessan** [comment]
Testing with both 8.0.1766 (current Debian package) terminal vim and gvim and freshly built 8.1.0055, both of those commands start xdvi for me.

**Comment by guido99** [comment]
Same for me in vim/gvim terminal! (8.1.0039.)
