### ISSUE TITLE
build issue vim81, Xpm related

### ISSUE THREAD

**Issue by bournejason** [vim/vim#3004]
objects/gui_motif.o: In function `check_xpm':
gui_motif.c:(.text+0x1af6): undefined reference to `XpmReadFileToPixmap'
gui_motif.c:(.text+0x1b00): undefined reference to `XpmFreeAttributes'
objects/gui_motif.o: In function `gui_mch_dialog':
gui_motif.c:(.text+0x5a96): undefined reference to `XpmCreatePixmapFromData'
objects/gui_x11.o: In function `gui_mch_register_sign':
gui_x11.c:(.text+0x3ab): undefined reference to `XpmReadFileToImage'
objects/gui_x11.o: In function `gui_mch_init':
gui_x11.c:(.text+0x35a4): undefined reference to `XpmCreatePixmapFromData'
gui_x11.c:(.text+0x35ac): undefined reference to `XpmFreeAttributes'
collect2: ld returned 1 exit status
link.sh: Linking failed
make[1]: *** [vim] Error 1
make[1]: Leaving directory `/home/qhuo/tools/gvim/vim81/src'
make: *** [first] Error 2

**Comment by bournejason** [comment]
platform:
Red Hat Enterprise Linux Workstation release 6.5 (Santiago)

**Comment by chrisbra** [comment]
I suppose, if you build with gtk it works? BTW: please give your configure parameters.

**Comment by nuko8** [comment]
Those errors are most likely to take place when the compiler command line at link stage misses `-L/directory/where/your libXpm resides/ -lXpm` for some reason, or when the dependency libraries such as `Xm`, `Xt`, `X11`, `Xpm` and so on are not ordered  correctly on that command line for some reason, thus the linker failing to resolve symbols even if your system actually have all the libraries to resolve them.  So, showing the compiler command line at link stage could help.

Knowing whether or not a gtk build works would help you probe whether or not your system has a working libXpm.

**Comment by bournejason** [comment]
@nuko8 you mean this command line?
link.sh: $LINK_AS_NEEDED set to 'yes': invoking linker directly.
  gcc   -L/usr/local/lib -Wl,--as-needed        -o vim objects/arabic.o objects/beval.o objects/buffer.o objects/blowfish.o objects/crypt.o objects/crypt_zip.o objects/dict.o objects/diff.o objects/digraph.o objects/edit.o objects/eval.o objects/evalfunc.o objects/ex_cmds.o objects/ex_cmds2.o objects/ex_docmd.o objects/ex_eval.o objects/ex_getln.o objects/farsi.o objects/fileio.o objects/fold.o objects/getchar.o objects/hardcopy.o objects/hashtab.o  objects/if_cscope.o objects/if_xcmdsrv.o objects/list.o objects/mark.o objects/memline.o objects/menu.o objects/misc1.o objects/misc2.o objects/move.o objects/mbyte.o objects/normal.o objects/ops.o objects/option.o objects/os_unix.o objects/pathdef.o objects/popupmnu.o objects/pty.o objects/quickfix.o objects/regexp.o objects/screen.o objects/search.o objects/sha256.o objects/spell.o objects/spellfile.o objects/syntax.o objects/tag.o objects/term.o objects/terminal.o objects/ui.o objects/undo.o objects/userfunc.o objects/version.o objects/window.o objects/gui.o objects/gui_motif.o objects/gui_x11.o objects/gui_beval.o objects/gui_xmdlg.o objects/gui_xmebw.o objects/term_encoding.o objects/term_keyboard.o objects/term_mouse.o objects/term_parser.o objects/term_pen.o objects/term_screen.o objects/term_state.o objects/term_unicode.o objects/term_vterm.o          objects/netbeans.o objects/channel.o  objects/charset.o objects/json.o objects/main.o objects/memfile.o objects/message.o  -lXmu -lXext -lXm -lXt -lSM -lICE -lXt -lX11 -lSM -lICE -ldl  -lm -ltinfo -lnsl  -lselinux -ldl

**Comment by bournejason** [comment]
@chrisbra I just simply did 'make'
How to do the gtk build? Where I can get the configure parameters you need?

**Comment by nuko8** [comment]
When I build Motif GVim, the command line gives
```
-lXp -lXmu -lXext -lXm -lXt -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE
```
On the other hand, that of your case gave
```
      -lXmu -lXext -lXm -lXt -lSM -lICE       -lXt -lX11        -lSM -lICE
```
Obviously, some libraries are missing from the command line, namely, `Xp`, `Xdmcp`, and, especially, `Xpm`.  Now the reason of the failure is clear.

When you run the configure script, it is to show the line
```
checking for XpmCreatePixmapFromData in -lXpm...
```
If the check above passes affirmatively, the script adds `-lXpm` to the command line; otherwise, that linker option won't appear on the command line.   What did the script say when you ran it to configure Motif GVim?

**Comment by chrisbra** [comment]
> How to do the gtk build? Where I can get the configure parameters you need?

Check the help option of the `configure` script.

**Comment by tonymec** [comment]
@bournejason : see http://users.skynet.be/antoine.mechelynck/vim/compunix.htm

**Comment by k-takata** [comment]
Looks like an environmental issue. No new information, so closing.
