### ISSUE TITLE
Search() problem

### ISSUE THREAD

**Issue by premysljordak** [vim/vim#3005]

**Comment by chrisbra** [comment]
Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. Closing.

**Comment by arno-luo** [comment]
You cannot search because the '+' is just matched a charactor '+', so
you should search like \d\+-\d\+. Also, [0-9]\{1,\}-[0-9]\{1,\} will
work.

On Wed, 2018-06-13 at 13:06 +0000, premysljordak wrote:
> Hello, search function doesnt respect repetition of regexp. In my
> case i want to search for \d+-\d+. That matches 123-12, 1-1, 123-
> 1234, 0-1234 etc. Doesnt work for [0-9]{1,}-[0-9]{1,} either.
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
-- 
Regards!
:-)
Arno Luo
mobile	： 13825154345
