### ISSUE TITLE
TextChangedP not triggered when used in conjuction with CursorHoldI

### ISSUE THREAD

**Issue by JBakamovic** [vim/vim#3006]
Hi,

Sorry for not having a full reproducible example but I'll try my best explaining the scenario which will hopefully give us some hints what might have gone wrong.

High-level overview of a feature I am trying to implement:
1. Auto-completion engine sits in the background (outside the Vim process).
2. Auto-completion engine listens on requests from the client (Vim).
3. Auto-completion engine on client request 'calculates' the auto-completion candidates and sends them back to the client.
4. To reduce the number of client requests (basically avoiding sending as many requests as there are characters typed in; auto-completion for C++ is a bit on a heavy side), `CursorHoldI` event is used.
5. On each `CursorHoldI` event an initial list of candidates will be eventually received from the auto-completion engine (e.g. all candidates that match `foo`).
5. Once the initial list of candidates is received, we will enter the `insert_expand` mode and present it to the user using the pop-up menu (pum). At this point `CursorHoldI` event will become inaccessible.
6. User will want to continue typing in the characters further to narrow down the list of candidates. As `CursorHoldI` event cannot be used anymore, `TextChangedP` event will be used.
7. `TextChangedP` _stops_ being triggered after typing in _exactly_ three characters.

E.g. 
* We ask for initial list by typing in the `er`. `CursorHoldI` event triggers the auto-completion engine. 
* We receive the initial list of: [`error`, `errMsg`, `errorMsg`, `worker`]. PUM pops up with the information presented. We enter the `insert_expand` mode.
* We type in the `r` character. `TextChangedP` event handles it and triggers the auto-completion engine accordingly.
* We receive a refined list of candidates: [`error`, `errMsg`, `errorMsg`]
* We type in the `o` character. `TextChangedP` event still handles it and triggers the auto-completion engine accordingly.
* We receive a refined list of candidates: [`error`, `errorMsg`]
* We type in the `r` character. `TextChangedP` _stops_ being triggered.

Do you have any clue why such a thing would be happening? I've tried looking around the code (and patchset for `TextChangedP` event) a bit but weren't able to deduce anything from a quick overview.

I hope I managed to explain the scenario.

Cheers,
Adi

**Comment by chemzqm** [comment]
>  As CursorHoldI event cannot be used anymore, TextChangedP event will be used.

You can hide the popup menu in InsertCharPre autocmd handler by send `<C-e>` when user type more character, and then you can receive TextChangedI event to do the filter or stop filter by check what user have typed.  Using TextChangedP probably not a good idea, since it could also triggered by completion item select change, and you have no way to distinguish.

**Comment by JBakamovic** [comment]
> You can hide the popup menu in InsertCharPre autocmd handler by send <C-e> when user type more character, and then you can receive TextChangedI event to do the filter or stop filter by check what user have typed.

Thanks for the hint but I really want to avoid using `TextChangedI` as much as possible. That's why I'm using the `CursorHoldI` in the first place.

> Using TextChangedP probably not a good idea, since it could also triggered by completion item select change

AFAIK this is not the case and wouldn't make sense if it really was like that IMO. I've tried it out right now and I see no additional `TextChangedP` events being triggered or I misunderstood you.

**Comment by chemzqm** [comment]
@JBakamovic It could be triggered with `<C-n>` and `<C-p>`, but not with `<Up>` and `<Down>`

If you use `CursorHoldI` instead of `TextChangedI ` for further filter the completion items, there would a short time for waiting and I'm afraid it's not a good experience.

**Comment by JBakamovic** [comment]
> It could be triggered with <C-n> and <C-p>, but not with <Up> and <Down>

Yes, you're right. However, I think this can be easily filtered out. Pop-up menu is still visible in that case and as such I won't be triggering any further requests.

> If you use CursorHoldI instead of TextChangedI for further filter the completion items

`CursorHoldI` is used for _initial_ candidate list. `TextChangedP` is supposed to be used for further filtering but I've stumbled upon what I think is a bug.

> there would a short time for waiting and I'm afraid it's not a good experience.

IMO `TextChangedI` is notoriously bad idea to do anything heavy especially sth like auto-completion.

**Comment by chemzqm** [comment]
> IMO TextChangedI is notoriously bad idea to do anything heavy especially sth like auto-completion.

It would not bad if you use it in asynchronous way

**Comment by JBakamovic** [comment]
> It would not bad if you use it in asynchronous way

As I've already mentioned in my first post whole stuff _is_ already [asynchronous](https://github.com/JBakamovic/cxxd#diagram). It doesn't help because the point is not to trigger the auto-completion engine after each and every character typed in. That needlessly puts burden on the CPU (and if you care, battery).

**Comment by chemzqm** [comment]
@JBakamovic I have tested that TextChangedP works correctly.

``` vim
set nocompatible
filetype plugin indent on

inoremap <C-l> <C-R>=MyComplete()<CR>

set completeopt=menuone,noinsert,noselect

func! MyComplete()
  let line = getline('.')
  let start = col('.') - 1
  while start > 0 && line[start - 1] =~# '\k'
    let start -= 1
  endwhile
  let suggestions = [{
        \"word": "abcdefghijlmn",
        \}, {
        \"word": "abcdefghijlmno",
        \}]
  call complete(start + 1, suggestions)
  return ''
endfunc

autocmd TextChangedP * :call ShowInput()

function! ShowInput()
  let pos = getcurpos()
  let line = getline('.')
  let l:start = pos[2] - 1
  while l:start > 0 && line[l:start - 1] =~# '\k'
    let l:start -= 1
  endwhile
  let input = pos[2] == 1 ? '' : line[l:start : pos[2] - 2]
  echo input
endfunction
```
source this code and use `<C-l>`.
The problem you described is that vim will do the match itself when `noinsert` used in `completeopt`, and it would hide popup and fire `completeDone` if it find miss match and no TextChangedP would fire this time.
So if you want to do filter yourself, you probably have to hide the menu by send `<C-e>` each time after user typed.

**Comment by chemzqm** [comment]
> t doesn't help because the point is not to trigger the auto-completion engine after each and every character typed in. That needlessly puts burden on the CPU (and if you care, battery).

You can check if the completion session is activted, if it's not, just do nothing.
And also you can debounce it.

**Comment by JBakamovic** [comment]
> You can check if the completion session is activted, if it's not, just do nothing.

That seems as a redundant check. What you propose is to use `TextChangedI` and then check if completion session is active? Completion session will be _already active_ because initial candidates list will be returned as soon as `CursorHoldI` is triggered. Once the initial list of candidates is received we will enter the `insert_expand` mode (e.g. show pop-up menu). So I'm afraid that is not the solution.

> @JBakamovic I have tested that TextChangedP works correctly.

You tested that `TextChangedP` works "correctly" under circumstances where `CursorHoldI` is not being used. This bug-report is about a situation where both are used in conjunction. So, no it's not really the same.

> The problem you described is that vim will do the match itself when noinsert used in completeopt, and it would hide popup and fire completeDone if it find miss match and no TextChangedP would fire this time. So if you want to do filter yourself, you probably have to hide the menu by send <C-e> each time after user typed.

This _might_ be the reason why I'm observing such a behavior but right now everything seems like a hack (hiding the menu?) to me. I definitely want to avoid such workarounds because it complicates the implementation needlessly. I would rather prefer to fix the bug or somebody enlighten me why this isn't a bug.

**Comment by chemzqm** [comment]
@JBakamovic TextChangedP could be triggered many times with completion started at CursorHoldI.
The reason is vim would also do the filter itself and stop completion when it find miss match.  So the bug does not exists.
Change the code above and add
```
autocmd CursorHoldI * :call MyComplete()
```
could test it.

**Comment by JBakamovic** [comment]
> TextChangedP could be triggered many times with completion started at CursorHoldI.

It does get triggered but only twice. Third time it doesn't. That's the whole point of this issue.

**Comment by chemzqm** [comment]
If could trigger more than twice, as long as vim find the matches.

**Comment by JBakamovic** [comment]
![vim-auto-completion](https://user-images.githubusercontent.com/7620680/41413403-4b28b51c-6fe3-11e8-95f4-65d8f6721bb4.gif)

Why in the world you would stop triggering the `TextChangedP` event? Text is still being modified and popup menu is still visible but at one point Vim decides not to generate another event? This is completely broken feature _and_ contract between the developer and the API & documentation.

Sorry, I really don't understand the reasoning behind it. It just doesn't make sense to me.

P.S. Log that can be seen on the left is the output from the auto-completion engine running in another process. It stops outputting after `err`, that is it doesn't react anymore to `erro`.

**Comment by JBakamovic** [comment]
Perhaps I should have mentioned explicitly before, but the same (unexpected) behavior as depicted in GIF does _not_ happen if we replace `CursorHoldI` event with `TextChangedI` event. I fail to see any consistency in that.

**Comment by chemzqm** [comment]
It's just because vim can't find a match that starts with `erro`, it uses exact match, before the `o` get inserted, vim will stop completion and no TextChangedP would fired anymore.

**Comment by JBakamovic** [comment]
And why doesn't it happen when `TextChangedI` + `TextChangedP` is used? It makes no sense.

![vim-auto-completion-2](https://user-images.githubusercontent.com/7620680/41418687-89ec5e72-6ff0-11e8-8dac-65e5fc89c270.gif)

**Comment by lifepillar** [comment]
>We type in the r character. TextChangedP stops being triggered.
>Do you have any clue why such a thing would be happening?

Perhaps your `completeopt` does not contain `menuone`, hence when there is only one match the pop-up menu is dismissed.

**Comment by JBakamovic** [comment]
> Perhaps your completeopt does not contain menuone, hence when there is only one match the pop-up menu is dismissed

It does. This is the relevant code excerpt:
```
setlocal completeopt-=menu
setlocal completeopt-=preview
setlocal completeopt+=menuone,noinsert,noselect
setlocal complete=
```

Relevant vim-plugin code is [here](https://github.com/JBakamovic/cxxd-vim/blob/auto_completion/plugin/cxxd/services/source_code_model/auto_completion.vim#L48-L62) and [here](https://github.com/JBakamovic/cxxd-vim/blob/auto_completion/plugin/cxxd.vim#L111-L115).

**Comment by chemzqm** [comment]
> And why doesn't it happen when TextChangedI + TextChangedP is used? It makes no sense.

Because vim find a match started with what you have typed, try to change the last one character you typed and you will understand.
It doesn't matter which event you're using

**Comment by chemzqm** [comment]
@JBakamovic Can not see the reason that the completion stops since you have `error_t` in the completion list, but I can't reproduce your issue with no plugin installed.

Could you try out these code with your plugins?
``` vim
set nocompatible
filetype plugin indent on

inoremap <C-l> <C-R>=MyComplete()<CR>
set completeopt=menuone,noinsert,noselect

func! MyComplete()
  let line = getline('.')
  let start = col('.') - 1
  while start > 0 && line[start - 1] =~# '\k'
    let start -= 1
  endwhile
  let input = GetInput()
  let suggestions = [{
        \"word": "errmessage",
        \}, {
        \"word": "err_message",
        \}]
  if input =~# '^err'
    call add(suggestions, {
          \"word": "erro_t"
          \})
  endif
  if input =~# '^erro'
    let suggestions =[{
          \"word": "erro_t"
          \}]
  endif
  call complete(start + 1, suggestions)
  return ''
endfunc

autocmd TextChangedP * :call MyComplete()
autocmd CursorHoldI * :call MyComplete()

function! GetInput()
  let pos = getcurpos()
  let line = getline('.')
  let l:start = pos[2] - 1
  while l:start > 0 && line[l:start - 1] =~# '\k'
    let l:start -= 1
  endwhile
  let input = pos[2] == 1 ? '' : line[l:start : pos[2] - 2]
  return input
endfunction
```
The completion doesn't stop after I type `erro`, check out https://asciinema.org/a/187262

**Comment by bstaletic** [comment]
Here's what I tried:
- `vim -Nu NONE .zshrc` - chosen that file because it already has a lot of words in it.
- `:set completeopt=menuone,noselect,noinsert`
- `:au TextChangedP * echom "foo"`
- `:au CursorHoldI * feedkeys("\<C-n>")`
- Enter insert mode on an empty line.
- Wait for the `CursorHoldI` event to get triggered and open the completion menu.
- Start typing. In my case I typed `auto`. `aut` narrowed down the list to 4 entries and `auto` to ust one.
- Exit insert mode and open `:messages`.

Here's the result:
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
".zshrc" 105L, 4174C
Scanning tags.
foo
foo
foo
foo
foo
foo
```
This definitely shows that `TextChangedP` doesn't stop after three characters.

**Comment by JBakamovic** [comment]
Do you have an idea why the example that I gave is not working?

**Comment by chrisbra** [comment]
> Do you have an idea why the example that I gave is not working?

Can you please provide a reproducible example? I did not see one from you

**Comment by JBakamovic** [comment]
> Can you please provide a reproducible example?

I would in the first place if it was that easy to make one. But unfortunately it isn't as everything is done in an async way. I thought I've made that clear in my initial post.

> I did not see one from you

You don't need to be snarky. I was politely asking for help and all I've got is a bunch of plastic counter-examples which barely reflect the use-case I am trying to describe. Thank you.

**Comment by chrisbra** [comment]
> You don't need to be snarky

I don't know what snarky is, but probably nothing polite, so I won't look it up :)
Honestly, I was trying to be helpful here and did not mean to be impolite. It was just that the whole thread was kind of long already and I had some problems following it. Therefore I explicitly asked for a reproducible example. In fact I was going to look into the issue and this is a lot easier if there is a working example I can use to find why you observed the behaviour.

**Comment by chemzqm** [comment]
@JBakamovic There is only one explanation that I could think of, that is the completion item abbr is `error_t` but the word of it is not, since vim filter item with word so it didn't find a match and fire `TextChangedI` instead of `TextChangedP`

**Comment by JBakamovic** [comment]
> I don't know what snarky is, but probably nothing polite, so I won't look it up :)

It's not impolite. That's not on my list when communicating with people. Meaning usually refers to people being sarcastic about something. I thought you were by giving that comment. My apologies on that.

> It was just that the whole thread was kind of long already and I had some problems following it.

Yes, that's true. TL;DR First post of mine provides I believe enough details about the issue and there are two other posts of mine which contain GIFs depicting the issue live in code. There are also links to the source code (vim plugin) which exhibits that behavior.

> In fact I was going to look into the issue and this is a lot easier if there is a working example I can use to find why you observed the behavior.

I am totally aware of that and I was thinking what would be the best way to come up with the reproducible example but I was unable to. I thought that the code is simple enough and can be understood in a glance by someone familiar with auto-completion stuff because there is really nothing strange or unusual there.

**Comment by JBakamovic** [comment]
I opened a new issue, #3026, with reproducible example. Let's please continue discussion there. Here's already too much noise.

Thanks,
Adi
