### ISSUE TITLE
Display breakpoint number in source window

### ISSUE THREAD

**Issue by joterway** [vim/vim#3007]
The :Termdebug feature is great but when a breakpoint is added, it simply shows "=>" in the source window for the breakpoint. VimGDB used to show the breakpoint number instead". Is it possible to get this functionality as well?

**Comment by brammool** [comment]
> The :Termdebug feature is great but when a breakpoint is added, it
> simply shows "=>" in the source window for the breakpoint. VimGDB used
> to show the breakpoint number instead". Is it possible to get this
> functionality as well?

How did VimGDB show that?  If you have a screen shot (or the text of the
sign), that would be helpful.

I'll add it to the todo list, but perhaps someone knows how to implement
this and can make a patch.

-- 
Don't read everything you believe.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by joterway** [comment]
![vimgdb breakpoints](https://user-images.githubusercontent.com/5936322/41427437-917335e0-6fcc-11e8-8d01-f2cd10414855.jpg)

**Comment by brammool** [comment]
> I've attached a screenshot of what it looks like.=E2=80=8B

This shows the breakpoint number above the breakpoint sign.
I wonder how it's doing that.  Possibly with another sign?
Do you know where the plugin can be found?


-- 
Light travels faster than sound.  This is why some people
appear bright until you hear them speak

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
On Do, 14 Jun 2018, Bram Moolenaar wrote:

> This shows the breakpoint number above the breakpoint sign.
> I wonder how it's doing that.  Possibly with another sign?
> Do you know where the plugin can be found?

Bram, here are two patches. Patch 1 uses the breakpoint number as sign 
label. Patch two, adjusts the highlighting for the DebugPC whenever the 
'background'  option changes. (It happens often, that Vim does not 
detect my background correctly and uses 'ligth'). However I only notice 
because the line of the debugPC sign is not readable. 

Best,
Christian
-- 
Nichts ewiges kann das Glück uns geben,
denn flüchtiger Traum ist Menschenleben,
und selbst die Trüme sind ein Traum.
		-- Pedro Calder¢n de la Barca

**Comment by joterway** [comment]
The number is the breakpoint sign. The "=>" you see is actually just
signifying the current line of execution, which confusingly is the same
symbol you've used to denote a breakpoint.

VimGDB was part of the Clewn project. It was a patch applied to the Vim
source when building, hence the reason it can't be used anymore (author
stopped updating it).

https://sourceforge.net/projects/clewn/files/vimGdb/

**Comment by chrisbra** [comment]
fixed by https://github.com/vim/vim/releases/tag/v8.1.0080
