### ISSUE TITLE
Add GDB mode, similar to VimGDB

### ISSUE THREAD

**Issue by joterway** [vim/vim#3011]
VimGDB used to support GDB mode, permitting common commands to be mapped to keys for easy access. For example, you could hit F7 to enter GDB mode then "u" for up, "d" for down, "w" for where, "b" to set a breakpoint, etc and when finished, return to editing mode again by hitting F7.

I'm sure a different set of keys makes sense now but I think the basic premise is sound. It's not something I can implement today, since the functions to send commands to the GDB buffer are private to the GDB script.

I've attached the vim script with the mappings you can start with.

[gdb_mappings.vim.log](https://github.com/vim/vim/files/2103348/gdb_mappings.vim.log)

**Comment by cecamp** [comment]
Uri Moszkowicz wrote:
>
> VimGDB used to support GDB mode, permitting common commands to be 
> mapped to keys for easy access. For example, you could hit F7 to enter 
> GDB mode then "u" for up, "d" for down, "w" for where, "b" to set a 
> breakpoint, etc and when finished, return to editing mode again by 
> hitting F7.
>
> I'm sure a different set of keys makes sense now but I think the basic 
> premise is sound. It's not something I can implement today, since the 
> functions to send commands to the GDB buffer are private to the GDB 
> script.
>
> I've attached the vim script with the mappings you can start with.
>
> gdb_mappings.vim.log 
> <https://github.com/vim/vim/files/2103348/gdb_mappings.vim.log>
>
>
There's also gdbmgr (http://www.drchip.org/astronaut/vim/index.html#GDBMGR).

Regards,
Chip Campbell

**Comment by brammool** [comment]
You can now define mappings:
	map ,w :call TermDebugSendCommand('where')<CR>
Creating a plugin with your favorite mappings is left for others to pick up
