### ISSUE TITLE
color scheme wasn't loaded

### ISSUE THREAD

**Issue by moyuanhuang** [vim/vim#3013]
Hi,

I run vim in iterm2, and I'm trying out the new feature to run terminal emulator inside vim. My iterm2's color scheme looks like this
![image](https://user-images.githubusercontent.com/14947870/41441119-1ecf6ae4-6fe6-11e8-98bd-b77be936bf22.png)

In side vim, however, the color scheme seems not loaded
![image](https://user-images.githubusercontent.com/14947870/41441225-91ef4436-6fe6-11e8-975c-00c2b4a10970.png)

Is this behavior expected? Or am I missing some configurations for vim's term emulator? I had `termguicolor` set to true in my `.vimrc`.

p.s. Neovim seems to have the same problem https://github.com/neovim/neovim/issues/4696

**Comment by tonymec** [comment]
what do you mean, not loaded? I see basically the same colours in both pictures, maybe a little more vivid in the second one, which could be explained by (for instance) a different number of possible colours, or an "all bold" font being selected in Vim.

Best regards,
Tony.

**Comment by moyuanhuang** [comment]
@tonymec Hi Tony, I'll try to make myself clear. The second one is the default color of iterm2, which is too vivid from my perspective. This is why I changed iterm2's color scheme to make it softer, as the first screenshoot shows. However, the terminal emulator seems not aware of this color scheme change, as it always looks like screenshoot 2 when I use `:term` to open a terminal.

https://github.com/neovim/neovim/issues/4696 This PR should have more detailed explanation of the context, if you're interested.

**Comment by moyuanhuang** [comment]
I found a way to explicitly define the terminal emulator's color scheme inside vim
```
" set the vim's terminal emulator color scheme
let g:terminal_ansi_colors = [
  \ "#373c40", "#ff5454", "#8cc85f", "#e3c78a",
  \ "#80a0ff", "#ce76e8", "#7ee0ce", "#c9c9c9",
  \ "#f09479", "#f74782", "#42cf89", "#cfcfb0",
  \ "#78c2ff", "#ae81ff", "#85dc85", "#e2637f"
  \]
```

The colors defined here correspond to 
```
" let g:terminal_ansi_colors = [
" \ '@guibase02', '@guired', '@guigreen', '@guiyellow',
" \ '@guiblue', '@guimagenta', '@guicyan', '@guibase2',
" \ '@guibase03', '@guiorange', '@guibase01', '@guibase00',
" \ '@guibase0', '@guiviolet', '@guibase1', '@guibase3'
" \]
```

My vim terminal emulator now looks like this
![image](https://user-images.githubusercontent.com/14947870/41451065-f27fd43a-701f-11e8-9c6a-73b5c68de5d9.png)

**Comment by chrisbra** [comment]
Yes, if you want your terminal to use specific colors, you need to use the `g:terminal_ansi_colors`. I am closing this as a configuration issue.
