### ISSUE TITLE
possible race condition with job_start | unlet job

### ISSUE THREAD

**Issue by andymass** [vim/vim#3019]
When job type variables are unlet or go out of scope quickly, occasionally the job will not run properly.  For example,

`let x = job_start('xdvi') | sleep 1 | unlet x`

will create a `xdvi` window whereas

`let x = job_start('xdvi') | unlet x`

will mostly not ( 95% of the time on my computer, arch linux / vim 8.1.55).  This suggests a possible race.  It doesn't happen with all programs, and it's probably difficult for others to reproduce.  Nevertheless, I don't see why destruction of the job object would effect the job in any way, at least this isn't documented as such.

**Comment by brammool** [comment]
> When job type variables are unlet or go out of scope quickly,
> occasionally the job will not run properly.  For example,
> 
> `let x = job_start('xdvi') | sleep 1 | unlet x`
> 
> will create a `xdvi` window whereas
> 
> `let x = job_start('xdvi') | unlet x`
> 
> will mostly not ( 95% of the time on my computer, arch linux / vim
> 8.1.55).  This suggests a possible race.  It doesn't happen with all
> programs, and it's probably difficult for others to reproduce.
> Nevertheless, I don't see why destruction of the job object would
> effect the job in any way, at least this isn't documented as such.

Does this only happen with "xdvi" ?  I tried with xterm but it always
works.  It's possible that xdvi checks stdin and stdout and exits when
they are not connected.

One trick you can try: Add an exit_cb parameter, then the job object
won't be deleted until it's finished, even when the job object is not
referenced.

-- 
hundred-and-one symptoms of being an internet addict:
54. You start tilting your head sideways to smile. :-)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by andymass** [comment]
Yes, `job_start` always works fine with xterm, so it depends critically on the particular program being run.  A user reported in #3003 that it also errors with `gv` but work properly with many other programs.

I tried:

    function! XX(...)
        echo 'bar' | sleep 1
    endfunction
    call job_start('xdvi', {'exit_cb': 'XX'})

and I see "bar" printed immediately.  X window does not pop up.

**Comment by brammool** [comment]
> Yes, `job_start` always works fine with xterm, so it depends
> critically on the particular program being run.  A user reported in
> #3003 that it also errors with `gv` but work properly with many other
> programs.
> 
> I tried:
> 
>     function! XX(...)
>         echo 'bar' | sleep 1
>     endfunction
>     call job_start('xdvi', {'exit_cb': 'XX'})
> 
> and I see "bar" printed immediately.  X window does not pop up.

Strange.  You can use ch_logfile() to see what happens.
If needed, add more ch_log() calls in the source code (and rebuild Vim)
to see more details.

-- 
hundred-and-one symptoms of being an internet addict:
55. You ask your doctor to implant a gig in your brain.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by andymass** [comment]
You are correct about it being due to stdout disconnecting; it can be reproduced using the simple script:

script.sh:
```sh
#!/bin/bash
echo "This is an arbitrary message"
exec xterm
```

 `call job_start('./script.sh')` will not pop up xterm (I think it's getting a SIGPIPE and ending the process), while `let x = job_start('./script.sh')` will.  The program xterm is arbitrary, just so I can see when it's actually run.  However, `call job_start('./script.sh', {'out_io': 'null'})` works.

I'm not sure whether this is expected, though it makes sense now.  Solutions might be 1) if possible, use a better check so that channels aren't destroyed if set to 'pipe' and these pipes would be broken or 2) add a note in the documentation that if the return value is not kept, the user should take care to redirect `out_io` and `err_io` (or to something other than default.

**Comment by chrisbra** [comment]
I think https://github.com/vim/vim/commit/d2f3a8b8787333abf2300d38836b196955f10c00 amended the documentation.
