### ISSUE TITLE
Bad layout using async function open preview window when pum is visible 

### ISSUE THREAD

**Issue by chemzqm** [vim/vim#3020]
The patch of https://github.com/chrisbra/vim/commit/0e08d8dd38cf9cff67575c9f336b922d3d302860 fixed when using autocmd to open preview window in sync.  However, the server response should be used in async way, so that it won't block user from typing.
 
The bug could be reproduced with:

```vim
set nocompatible
filetype plugin indent on
inoremap <C-l> <C-R>=MyComplete()<CR>

func! MyComplete()
  let suggestions = [{
        \"word": "foo",
        \}, {
        \"word": "bar",
        \}]
  call complete(1, suggestions)
  return ''
endfunc

autocmd TextChangedP * :call ShowPreview()

function! s:Preview(...)
  execute 'pedit '.tempname()
endfunction

function! ShowPreview()
  let timer = timer_start(300, function('s:Preview'))
endfunction
```

Use `vim -u test.vim` and press `<C-l>`

**Comment by brammool** [comment]
> The patch of https://github.com/chrisbra/vim/commit/0e08d8dd38cf9cff67575c9f336b922d3d302860 fixed when using autocmd to open preview window in sync.  However, the server response should be used in async way, so that it won't block user from typing.
>  
> The bug could be reproduced with:
> 
> ```vim
> set nocompatible
> filetype plugin indent on
> inoremap <C-l> <C-R>=MyComplete()<CR>
> 
> func! MyComplete()
>   let suggestions = [{
>         \"word": "foo",
>         \}, {
>         \"word": "bar",
>         \}]
>   call complete(1, suggestions)
>   return ''
> endfunc
> 
> autocmd TextChangedP * :call ShowPreview()
> 
> function! s:Preview(...)
>   execute 'pedit '.tempname()
> endfunction
> 
> function! ShowPreview()
>   let timer = timer_start(300, function('s:Preview'))
> endfunction
> ```
> 
> Use `vim -u test.vim` and press `<C-l>`

I can reproduce it, thanks for writing this.

That's a tough one, currently the popup menu code assumes the window
layout does not change.

I made a workaround that should solve it in most cases.  But when lines
wrap it may still go wrong.

-- 
Creating the world with Emacs:   M-x let-there-be-light
Creating the world with Vim:     :make world

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chemzqm** [comment]
It would be great if vim could provide a method to create another popup window when the completion popup is shown for showing the documentation, like what `balloon` did.

User would have better experience since it's doesn't change window layout.

**Comment by chrisbra** [comment]
fixed by https://github.com/vim/vim/releases/tag/v8.1.0062
