### ISSUE TITLE
Suggestion: Get rid of the Win32.mak dependency.

### ISSUE THREAD

**Issue by dertuxmalwieder** [vim/vim#3023]
Currently, `Make_mvc.mak` relies on `Win32.mak` which is a file that requires an ancient version of the Windows SDK (7.1), it was not included with later Windows SDKs. Installing the Windows SDK v7.1 on Windows 10 leaves a mess of outdated libraries *if* it can even be installed.

On my new Windows 10 machine with Visual Studio 2017, the Windows SDK v7.1 fails to be installed with unclear error messages. I'd need to hunt it down, probably. (Tomorrow or so.) For the time being, I really wish that building Vim on newer Windows versions was easier. Since I know that there is an "official" Windows nightly now, I can guess that Bram himself might be interested in a solution. :-)

(So, no new builds from me before I was able to fix this. Sorry!)

**Comment by k-takata** [comment]
> Make_mvc.mak relies on Win32.mak

It's not correct.
`Win32.mak` is used only when `SDK_INCLUDE_DIR` is set or `USE_WIN32MAK` is set to "yes".

**Comment by k-takata** [comment]
If you install VS2017 with support for Windows XP, Windows SDK 7.1A will be installed.

**Comment by dertuxmalwieder** [comment]
Ah, that explains it. Sorry! 

Would I have any obvious disadvantage from *not* using the SDK at all?

**Comment by k-takata** [comment]
> Would I have any obvious disadvantage from not using the SDK at all?

No.
Some useful variables are defined in win32.mak, but they are not used in Make_mvc.mak now.

**Comment by dertuxmalwieder** [comment]
Thank you. In this case, I apologize for this bug. :-(
