### ISSUE TITLE
Remove space from " ..."

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3028]
I see some strings end with "..." (without space) and others end with " ..." (with space).
Should the strings end the same way?

Here are the 6 strings that have space before "...":

    "Could not open temporary log file for writing, displaying on stderr ... "
    "Reading affix file %s ..."
    "Reading dictionary file %s ..."
    "Reading word file %s ..."
    "Writing suggestion file %s ..."
    "Writing spell file %s ..."

Should we change them to the following?:

    "Could not open temporary log file for writing, displaying on stderr... "
    "Reading affix file %s..."
    "Reading dictionary file %s..."
    "Reading word file %s..."
    "Writing suggestion file %s..."
    "Writing spell file %s..."

**Comment by brammool** [comment]
> I see some strings end with "..." (without space) and others end with " ..." (with space).
> Should the strings end the same way?
> 
> Here are the 6 strings that have space before "...":
> 
>     "Could not open temporary log file for writing, displaying on stderr ... "
>     "Reading affix file %s ..."
>     "Reading dictionary file %s ..."
>     "Reading word file %s ..."
>     "Writing suggestion file %s ..."
>     "Writing spell file %s ..."
> 
> Should we change them to the following?:
> 
>     "Could not open temporary log file for writing, displaying on stderr... "
>     "Reading affix file %s..."
>     "Reading dictionary file %s..."
>     "Reading word file %s..."
>     "Writing suggestion file %s..."
>     "Writing spell file %s..."

I suppose the space should be dropped, I see more cases where it's not
there.

-- 
If your nose runs, and your feet smell, you might be upside down.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
I  guess https://github.com/vim/vim/releases/tag/v8.1.0078 fixed it
