### ISSUE TITLE
Python ftplugin causes odd tab behavior and noexpandtab breakage

### ISSUE THREAD

**Issue by kallisti5** [vim/vim#3031]
https://github.com/vim/vim/blob/master/runtime/ftplugin/python.vim causes odd tab behavior forcing the "recommended" python guidelines.

How this plugin implements the standard results in the tab character changing to 4 spaces.  Leveraging the vim standard workarounds of "set noexpandtab" doesn't work and the tab to 4 space behavior persists.

Multiple issues have been opened on this in the past without any real solutions other than "working as designed".  A default plugin breaking noexpandtab shouldn't be working as designed.

#1078 , #989 , #2726

**Comment by chrisbra** [comment]
please contact the runtime script maintainer and discuss the issue with him.

**Comment by jamessan** [comment]
> How this plugin implements the standard results in the tab character changing to 4 spaces. Leveraging the vim standard workarounds of "set noexpandtab" doesn't work and the tab to 4 space behavior persists.

It's not _just_ `'expandtab'` that is changed.  `'shiftwidth'` is also changed to 4, which is why you're not seeing any difference when you `set noexpandtab`.

`:help ft-python-plugin` both documents what the ftplugin changes and how to disable it if you don't like the behavior.
