### ISSUE TITLE
Double and triple "?"'s

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3032]
I see some comments/strings containing double and triple "?"'s and "!"'s.
Is this nessesary?
Perhaps just use one.

    #. ???
    #: if_tcl.c:757
    msgid "cannot set line(s)"

    #. could not (re)open the swap file, what can we do????
    #: memline.c:716
    msgid "E301: Oops, lost the swap file!!!"

    #: memline.c:951
    msgid "E304: ml_upd_block0(): Didn't get block 0??"

    #: os_amiga.c:1036
    msgid "mch_get_shellsize: not a console??\n"

    #. don't overwrite messages here
    #. must give this prompt
    #. don't use emsg() here, don't want to flush the buffers
    #: fileio.c:5374
    msgid "WARNING: The file has been changed since reading it!!!"
    
    #. could not (re)open the swap file, what can we do????
    #: memline.c:716
    msgid "E301: Oops, lost the swap file!!!"

Also some strings have space before "?" and "!" and some strings does not.
Perhaps some spaces should be removed.

    #: os_amiga.c:957
    msgid "cannot change console mode ?!\n"

**Comment by brammool** [comment]
> I see some strings containing double and triple "?"'s.
> Is this nessesary?
> 
>     #. ???
>     #: if_tcl.c:757
>     msgid "cannot set line(s)"
>     
>     #. could not (re)open the swap file, what can we do????
>     #: memline.c:716
>     msgid "E301: Oops, lost the swap file!!!"
>     
>     #: memline.c:1480
>     msgid "???MANY LINES MISSING"
>     
>     #: memline.c:1496
>     msgid "???LINE COUNT WRONG"
>     
>     #: memline.c:1503
>     msgid "???EMPTY BLOCK"
>     
>     #: memline.c:1529
>     msgid "???LINES MISSING"
>     
>     #: memline.c:1567
>     msgid "???BLOCK MISSING"
>     
>     #: memline.c:1583
>     msgid "??? from here until ???END lines may be messed up"
>     
>     #: memline.c:1599
>     msgid "??? from here until ???END lines may have been inserted/deleted"
>     
>     #: memline.c:1619
>     msgid "???END"
>     
>     #: memline.c:1687
>     msgid ""
>     "E312: Errors detected while recovering; look for lines starting with ???"
> 
> Perhaps just use one "?".

No, please keep the ???.  These are markers that are inserted when
recovering a file with errors.  If the user doesn't have another way to
restore the text, searching for ??? will find the places where Vim was
unable to recover the text.

> Same for "!":
> 
>     #. don't overwrite messages here
>     #. must give this prompt
>     #. don't use emsg() here, don't want to flush the buffers
>     #: fileio.c:5374
>     msgid "WARNING: The file has been changed since reading it!!!"
>     
>     #. could not (re)open the swap file, what can we do????
>     #: memline.c:716
>     msgid "E301: Oops, lost the swap file!!!"

These are just to emphasise the text, as in shouting.

> Also some strings have space before "?" and "!" and some strings does not.
> Perhaps some spaces should be removed.

Examples?

-- 
hundred-and-one symptoms of being an internet addict:
80. At parties, you introduce your spouse as your "service provider."

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by scootergrisen** [comment]
It seems you quoted the initial text i wrote but i edited the text after that so its different now.

**Comment by brammool** [comment]
> It seems you quoted the initial text i wrote but i edited the text
> after that so its different now.

I don't think edits result in an email notification, thus I don't see
them.  I normally deal with issues through email to avoid having to jump
around the internet.


-- 
ASCII stupid question, get a stupid ANSI.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by scootergrisen** [comment]
These strings are not questions are they?:

    cannot change console mode ?!
    mch_get_shellsize: not a console??

Maybe it should be:

    cannot change console mode!
    mch_get_shellsize: not a console!

Or:

    cannot change console mode
    mch_get_shellsize: not a console

**Comment by scootergrisen** [comment]
Instead of:

    ??? from here until ???END lines may be messed up
    ??? from here until ???END lines may have been inserted/deleted
    ???END

Maybe use placeholder %s to insert the "???END" string so its the same:

    ??? from here until %s lines may be messed up
    ??? from here until %s lines may have been inserted/deleted
    ???END

In some translations like cs.po its translated like this which im guessing is not correct:

    msgid "??? from here until ???END lines may be messed up"
    msgstr "od ??? po ???END mohou být øádky pomíchané"
    
    msgid "??? from here until ???END lines may have been inserted/deleted"
    msgstr "od ??? po ???END mohou být vlo¾ené/smazané øádky"
    
    msgid "???END"
    msgstr "???KONEC"

**Comment by brammool** [comment]
> These strings are not questions are they?:
> 
>     cannot change console mode ?!

This is a "what happened here" remark.

>     mch_get_shellsize: not a console??

This is a "that's really weird" remark.

> Maybe it should be:
> 
>     cannot change console mode!
>     mch_get_shellsize: not a console!
> 
> Or:
> 
>     cannot change console mode
>     mch_get_shellsize: not a console

That takes the fun out of the messages.

-- 
From "know your smileys":
 :-{}	Too much lipstick

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by scootergrisen** [comment]
Also could remove space before "!" in these two strings:

    (NFA) COULD NOT OPEN %s !
    E874: (NFA) Could not pop the stack !

**Comment by brammool** [comment]
> Also could remove space before "!" in these two strings:
> 
>     (NFA) COULD NOT OPEN %s !
>     E874: (NFA) Could not pop the stack !

The first message is only for debugging.  I don't think we should bother
translating it.

The other space should indeed be dropped.

-- 
From "know your smileys":
 %	Bike accident.  A bit far-fetched, I suppose; although...
             o      _     _         _
     _o     /\_   _ \\o  (_)\__/o  (_)
   _< \_   _>(_) (_)/<_    \_| \   _|/' \/
  (_)>(_) (_)        (_)   (_)    (_)'  _\o_

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by scootergrisen** [comment]
E871: (NFA regexp) Can't have a multi follow a multi !

**Comment by scootergrisen** [comment]
If strings like "(NFA) COULD NOT OPEN %s !" is not suppose to be translated then perhaps remove it from the po files so people dont translate it.

**Comment by chrisbra** [comment]
Fixed by https://github.com/vim/vim/commit/3c867daaf09e8ac6ce4b9d43d6fbbfdd7689702d
