### ISSUE TITLE
"et al." or "and others"

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3033]
English it not my primary language so i did not know what "et al." meant as see on the start up screen of Vim.

    #: version.c:1320
    msgid "by Bram Moolenaar et al."

Also seen in:

    #: regexp.c:370
    msgid "E67: \\z1 et al. not allowed here"

I thought perhaps "Bram Moolenaar et al." was the full name or something.

Would it perhaps make more sense to write "and others" or something like that so perhaps more people can understand it?

    #: version.c:1320
    msgid "by Bram Moolenaar and others"

    #: regexp.c:370
    msgid "E67: \\z1 and others not allowed here"

**Comment by micbou** [comment]
"Et al." should be kept in "by Bram Moolenaar et al." because it's more specific than "and others" (it applies to people). However, using that expression in "\\z1 et al. not allowed here" is a mistake as "\\z1" doesn't refer to a person but a thing. "Etc." should be used instead.

**Comment by scootergrisen** [comment]
How is it more specific?
If it says a persons name followed by "and others" i would assume that its "and other people".

**Comment by micbou** [comment]
You answered yourself the question. With "et al.", you don't need that assumption.

**Comment by andymass** [comment]
I don't think 'et al.' only applies to people.  E.g., the similar phrase 'inter alia' just means "among other things"  whereas 'inter alios' means “among other people."  I.e., 'al.' can stand for anything; alii, aliae, alia, &c.

Anyway these messages are all translated with the appropriate words for other languages, so why change the english version, when one could use vim in their native language if they choose?

**Comment by micbou** [comment]
> I don't think 'et al.' only applies to people. E.g., the similar phrase 'inter alia' just means "among other things" whereas 'inter alios' means “among other people." I.e., 'al.' can stand for anything; alii, aliae, alia, &c.

That's the usage. The original meaning doesn't matter.

**Comment by scootergrisen** [comment]
Do people that use english as primary language generally know what el al. means?
I guess that is the most important thing.

**Comment by scootergrisen** [comment]
It seems that some of the translators keeps the "et al." part.
It could be that this is also valid translation in their language but perhaps the translators dont know what it means or think its part of the name and keeps it without translating it.

af.po:

    deur Bram Moolenaar et al.

ca.po:

    per Bram Moolenaar et al.

es.po:

    por Bram Moolenaar et al.

fi.po:

    tekijät Bram Moolenaar et al.

fr.po:

    par Bram Moolenaar et al.

ga.po:

    le Bram Moolenaar et al.

it.po:

    di Bram Moolenaar et al.

ko.po:

    by Bram Moolenaar et al.

ko.UTF-8.po:

    by Bram Moolenaar et al.

pt_BR.po:

    por Bram Moolenaar et al.

zh_TW.po:

    維護者: Bram Moolenaar et al.

zh_TW.UTF-8.po:

    維護者: Bram Moolenaar et al.

**Comment by vim-ml** [comment]
scootergrisen <vim-dev-github@256bit.org> wrote:

> It seems that some of the translators keeps the "et al." part.
> It could be that this is also valid translation in their language
> but perhaps the translators dont know what it means or
> think its part of the name and keeps it without translating it.

"et al." is a Latin abbreviation, so it's not surprising
that other languages use it as well  (just like "etc"
is used in many languages).

Dominique

**Comment by tonymec** [comment]
@scootergrisen : 
> Do people that use english as primary language generally know what el al. means?
> I guess that is the most important thing.

Many Latin abbreviations or expressions are common in English. I've often seen "et al." to mean "and others", especially about people, in English texts, so often in fact that even though my mother language is not English (but French) I understand this particular abbreviation as a matter of course. I don't have an English unilingual dictionary at hand, but I see "et al" even as an entry in the English-Russian part of the Concise Oxford Russian Dictionary, as follows:

et al [et 'æl] *(abbr. of ***et alii***)* и други́е.

where "и други́е" is Russian for "and others".

Best regards,
Tony.

**Comment by scootergrisen** [comment]
We also have "et al." in danish it seems i just never come across it i think.
I think i like the "and others" better at least for danish translation so people like my self have a chance to understand it.

**Comment by tonymec** [comment]
Well, if I am correct in assuming that you're the Danish translator, you're the one to choose between "et al." and "og andre" (if that's the native-Danish expression). As a former professional translator I would use the translation closest to the original text if it exists in the target language, but there is always some leeway coming from the fact that the expression might be less common, maybe much less common, in the target language than in the source language, and I don't know Danish well enough to have an opinion about that. What I do know is that "et al." is quite common in English.
