### ISSUE TITLE
gvim81.exe contains lang\messages\LC_MESSAGES\vim.mo

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3034]
For some reason ftp://ftp.vim.org/pub/vim/pc/gvim81.exe contains:
lang\messages\LC_MESSAGES\vim.mo

Which is the japanese translation.

I'm guessing the messages\ should not exists.

**Comment by brammool** [comment]
> For some reason ftp://ftp.vim.org/pub/vim/pc/gvim81.exe contains:
> lang\messages\LC_MESSAGES\vim.mo
> 
> Which is the japanese translation.
> 
> I'm guessing the messages\ should not exists.

Good catch.  It must have been there for a long time.  What happens is
that the distribution packaging needs to rename the message files to the
names that MS-Windows uses.  One name ja.euc-jp.mo was not recognized
and resulted in an empty directory name.  Another file "messages.mo" was
left behind for some reason and got picked up.

Should be OK with the next release build.

-- 
hundred-and-one symptoms of being an internet addict:
81. At social functions you introduce your husband as "my domain server."

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by scootergrisen** [comment]
If you run "msgfmt vim.po" it creates "messages.mo" automatically so maybe thats way.
If you run "msgfmt --output-file=/dev/null vim.po" it does not create the "messages.mo" file.
