### ISSUE TITLE
Missing instructions on how to translate gVim menus

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3035]
Should https://github.com/vim/vim/blob/master/runtime/lang/README.txt not contain some information on how to translation the menus in gVim?

There are some text at the bottom but that seems to be related to the po files found elsewhere.
I would like to translate the menus but i have no idea how.
These does not seem to be some souce files in english i could start a new translation from.
The english files are almost empty.

**Comment by brammool** [comment]
> Should https://github.com/vim/vim/blob/master/runtime/lang/README.txt not contain some information on how to translation the menus in gVim?
> 
> There are some text at the bottom but that seems to be related to the po files found elsewhere.
> I would like to translate the menus but i have no idea how.
> These does not seem to be some souce files in english i could start a new translation from.
> The english files are almost empty.

Best is to look at an example, e.g.
$VIMRUNTIME/lang/menu_de_de.latin.vim
Help is found at ":help menutrans".

-- 
hundred-and-one symptoms of being an internet addict:
84. Books in your bookcase bear the names Bongo, WinSock and Inside OLE

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by scootergrisen** [comment]
Why close? I still think instructions are needed.
I dont think its a good idea to take another language file and use that as starting point for new translations.
The german one was last updated in 2006 according to the file.
It would be better to have a file simalar til the pot fil for po files.
That way alle the translations have a file to compare with and update from.

**Comment by chrisbra** [comment]
The instructions are in the help file.

**Comment by scootergrisen** [comment]
Still missing the structure.
Look at translations for different language they dont use the same structure.
Like german have file menu first but italian have the help menu first.
German use "menutrans", italian use "menut".
German uses "tmenu" for toolbar.

It would be nice to be able to da line by line comparrision.

How could i know if i missed something to translate or something is wrong like missing \.

**Comment by scootergrisen** [comment]
Also i would like to translate the Netrw menu that shows when selecting Window > Split File Explore.
It does not seem to be translated in any of the menu_*.vim translation files so hard to translate.

**Comment by scootergrisen** [comment]
I'm spending more time figuering out how to get to the point where i can translate then what i spend on translating.

**Comment by scootergrisen** [comment]
I dont like how i have to escape spaces in most strings and then in a few strings it seems in dont have to.

    menut Set\ language\ to\ "en"	Sæt\ sprog\ til\ "en"
    let g:menutrans_set_lang_to = "Sæt sprog til"

Its confusing.
It would be much better if i didnt have to escape each space.
You almost spend more time writing those \ then writing the words.
