### ISSUE TITLE
Better "Messages maintainer:" string

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3037]
Since the following string is special i suggest moving it to the top of the file as the first string so its easy to spot:

    msgid "Messages maintainer: Bram Moolenaar <Bram@vim.org>"

I suggest using something like this insted:

    msgid "translator-credits"

And then add a comment telling the translator what should be written.

Other projects use:

    #. TRANSLATORS: Replace this string with your names, one name per line.
    msgid "translator-credits"
    msgstr ""
    "Name 1\n"
    "Name 2\n"
    "Name 3\n"

    #. Put one translator per line, in the form of NAME <EMAIL>, YEAR1, YEAR2
    msgid "translator-credits"
    msgstr ""
    "Name 1 <name1@example.com>, 2017\n"
    "Name 2 <name1@example.com>, 2018\n"
    "Name 3, 2018\n"

That way the comment is where the string is and dont need to be in the README files at https://github.com/vim/vim/tree/master/src/po

Then translate "Messages maintainer:" in another string.

String can be seen with ":messages" command.

**Comment by k-takata** [comment]
> i suggest moving it to the top of the file

`*.po` files are generated or updated by gettext tools.
Is it possible to emit such arbitrary msgid in arbitrary place?

**Comment by k-takata** [comment]
I don't think there is a portable way to do this.
Moreover, this is clearly documented:

https://github.com/vim/vim/blob/a87b72cc316e065d66dcbcf7ec1cde330adef3a3/src/po/README.txt#L88-L91

So, closing.

**Comment by scootergrisen** [comment]
Yes but it dont need to be documented in another file.
It would be smarter to add the comment where the string is (in the po file) so the translator can see it at the point of translation instead of have comments written in other files that the translator have to find.

Here are the strings from cs and ko translation:

    msgid "Messages maintainer: Bram Moolenaar <Bram@vim.org>"
    msgstr "Správce zpráv: Bram Moolenaar <Bram@vim.org>"

    msgid "Messages maintainer: Bram Moolenaar <Bram@vim.org>"
    msgstr "메시지 관리자: Bram Moolenaar <Bram@vim.org>"

I'm guessin Bram did not translate them.

If the po contained something like:

    #. Put one translator per line, in the form of NAME <EMAIL>, YEAR1, YEAR2
    msgid "translator-credits"

Then translators would not be able to make the mistake of keeping the name and email already there.

**Comment by chrisbra** [comment]
Hm, it looks like xgettext is able to do so.
With the following patch:
```patch
diff --git a/src/message.c b/src/message.c
index 4dac5ae04..bb2297813 100644
--- a/src/message.c
+++ b/src/message.c
@@ -982,7 +982,9 @@ ex_messages(exarg_T *eap)
     {
        s = mch_getenv((char_u *)"LANG");
        if (s != NULL && *s != NUL)
+           // Next Comment is extracted by xgettext and put in po file for translators
            msg_attr((char_u *)
+                   //  Translator: Please include your name and email address
                    _("Messages maintainer: Bram Moolenaar <Bram@vim.org>"),
                    HL_ATTR(HLF_T));
     }
```

after running `make de` in the po directory, the po file has this:

```po
  #. Translator: Please include your name and email address
  #: message.c:988
  msgid "Messages maintainer: Bram Moolenaar <Bram@vim.org>"
  msgstr "Übersetzt von Christian Brabandt <cb@256bit.org>"
```

**Comment by scootergrisen** [comment]
Cool.
I would prefer more clear instructions for the translators so it becomes consistant and what about when having multiple names, should they be seperated by ", " or "\n" and will "\n work on Windows, etc.

**Comment by k-takata** [comment]
How about using a comment based on the po/README.txt?
For example:
```
// This is a special message.
// You should include your name and E-mail address instead. (See src/po/README.txt)
```

**Comment by scootergrisen** [comment]
I dont see the need to refer to README.txt "(See src/po/README.txt)" if we can just write the comment in the po file where it is needed and delete it from README.txt.
