### ISSUE TITLE
Spell check not working in automake files

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vim/vim#304]
```
Doing "set spell" doesn't show any spelling errors when used on automake files 
(Makefile.am), even when I put in keyboard-mashing words.  It works just fine 
on the generated Makefile.

I'm using 7.4 on Fedora 21
```

Original issue reported on code.google.com by `khym.cha...@gmail.com` on 28 Dec 2014 at 7:56

**Comment by chrisbra** [comment]
cc @jamessan since you seem to be maintainer for the automake syntax file

**Comment by jamessan** [comment]
> cc @jamessan since you seem to be maintainer for the automake syntax file

Only a reluctant maintainer because we had accumulated some patches in Debian. :) If anyone else wants to take up active maintenance (which I suspect won't require much time given how often automake changes), please do contact me.

I'll include this and send it to Bram soon.

**Comment by lacygoill** [comment]
Fixed by https://github.com/vim/vim/commit/4c05fa08c9739e307ddc88ac91ba6d208f1fd68e.
