### ISSUE TITLE
searchpair with 'b' flag and stop_line returns 0

### ISSUE THREAD

**Issue by coot** [vim/vim#3047]
```
call searchpair('(', '',  ')' , 'bnW', 1)
```
will return `0` while `searchpair('(', '', ')', 'bnW')` will return the correct line number.

**Comment by brammool** [comment]
> ```
> call searchpair('(', '',  ')' , 'bnW', 1)
> ```
> will return `0` while `searchpair('(', '', ')', 'bnW')` will return
> the correct line number.

Well, you pass "1" for {skip}, so every match is skipped.

-- 
From "know your smileys":
 2B|^2B	  Message from Shakespeare

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by coot** [comment]
You're right, though there is still an issue:
```
:call searchpair('(', '', ')', 'bnW', 0, 1)     " returns 0
:call searchpair('(', '', ')', 'bnW', '0', 1)   " returns 2
:call searchpair('(', '', ')', 'bnW', {->0}, 1) " returns 2

**Comment by andymass** [comment]
{skip} can be a string, a lambda, a funcref or a partial.

It is an error (though a silent one) to provide a number as the skip argument.

**Comment by chrisbra** [comment]
So let's just amend the documentation:

```patch
diff --git a/runtime/doc/eval.txt b/runtime/doc/eval.txt
index 5ae0f6bca..7b8ec8566 100644
--- a/runtime/doc/eval.txt
+++ b/runtime/doc/eval.txt
@@ -7053,6 +7053,7 @@ searchpair({start}, {middle}, {end} [, {flags} [, {skip}
                When evaluating {skip} causes an error the search is aborted
                and -1 returned.
                {skip} can be a string, a lambda, a funcref or a partial.
+                Using a number as skip argument, will cause an (silent) error.

                For {stopline} and {timeout} see |search()|.

```

**Comment by brammool** [comment]
Christian wrote:

> So let's just amend the documentation:
> 
> ```patch
> diff --git a/runtime/doc/eval.txt b/runtime/doc/eval.txt
> index 5ae0f6bca..7b8ec8566 100644
> --- a/runtime/doc/eval.txt
> +++ b/runtime/doc/eval.txt
> @@ -7053,6 +7053,7 @@ searchpair({start}, {middle}, {end} [, {flags} [, {skip}
>                 When evaluating {skip} causes an error the search is aborted
>                 and -1 returned.
>                 {skip} can be a string, a lambda, a funcref or a partial.
> +                Using a number as skip argument, will cause an (silent) error.
> 
>                 For {stopline} and {timeout} see |search()|.

Since this function has so many arguments it's easy to make a mistake.
Let's give an error message.  I don't think anybody currently relies on
it silently failing.

-- 
hundred-and-one symptoms of being an internet addict:
106. When told to "go to your room" you inform your parents that you
     can't...because you were kicked out and banned.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
fixed by https://github.com/vim/vim/commit/3dddb09c98825acefa6f2d94bb369b8e00d7b3e5
