### ISSUE TITLE
Convert to HTML(5)

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3048]
Perhaps the Convert to HTML menu item could be changed to use HTML5.
It have a slightly simpler syntax.
And then switch to UTF-8 for the encoding.
Maybe better to use "Untitled" as title instead of "~\Untitled.html".
I think in HTML5 you can even remove `<meta charset="utf-8">` and ` type="text/css"` and `type="text/javascript"` because they are default but i like to include it.

This is the output:

    <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
    <html>
    <head>
    <meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
    <title>~\Untitled.html</title>
    <meta name="Generator" content="Vim/8.1">
    <meta name="plugin-version" content="vim7.4_v2">
    <meta name="syntax" content="none">
    <meta name="settings" content="use_css,pre_wrap,no_foldcolumn,prevent_copy=">
    <meta name="colorscheme" content="none">
    <style type="text/css">
    
    </style>
    
    <script type='text/javascript'>
    
    </script>
    </head>
    <body>
    <pre id='vimCodeElement'>
    
    </pre>
    </body>
    </html>
    

I use this for making HTML5 files:

    <!DOCTYPE html>
    
    <html lang="da">
    
    <head>
    
        <meta charset="utf-8">
        <title></title>
        <meta name="description" content="">
    
        <style type="text/css">
    
    
    
        </style>
    
    </head>
    
    <body>
    
    
    
    </body>
    
    </html>

**Comment by chrisbra** [comment]
The conversion is done by the distributed 2html.vim plugin. It supports a wide variety of options. Please read the help at [:h 2html.vim](http://vimhelp.appspot.com/syntax.txt.html#2html.vim)

**Comment by scootergrisen** [comment]
I dont see option for HTML5.

Der er some doctypes at https://github.com/vim/vim/blob/master/runtime/syntax/2html.vim#L1722 but no HTML 5 doctype.

**Comment by chrisbra** [comment]
This runtime file is maintained at https://bitbucket.org/fritzophrenic/vim-tohtml/src/default/

However @fritzophrenic doesn't seem to be too active anymore

**Comment by scootergrisen** [comment]
Ok

**Comment by fritzophrenic** [comment]
You're right, there isn't an option for html5. I played with it a while but there will need to be changes in other areas, in particular the meta tags if I remember correctly. There is an option to force UTF-8 if you like. I keep meaning to find time to work on the plugin but somehow never seem to get around to it. Thanks for the reminder that it exists and people use it. I'll try to move it up on my priority list. :-)

**Comment by scootergrisen** [comment]
I dont use it i just translate Vim at the moment so i try the different things and see from a new users point of view.
Another option is to remove it if its old and not being maintained or used.

**Comment by chrisbra** [comment]
> Another option is to remove it if its old and not being maintained or used.

Just because HTML5 isn't supported is not reason to drop it. I use id occasionally and find it really helpful (especially for sharing and visualizing diffs).
