### ISSUE TITLE
Remove (use '\\' to find  a '\') from search dialog title

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3049]
I dont like the `(use '\\' to find  a '\')` being part of the following strings used in the dialog title:

    Find string (use '\\' to find  a '\')
    Find & Replace (use '\\' to find  a '\')

I would like it better if the titles was:

    Find string
    Find & Replace

And then `(use '\\' to find  a '\')` inside the dialog or maybe have an option for search with and without escaping.

**Comment by ZyX-I** [comment]
I do not have this string (vim-8.0.1720). Though after trying to use the dialog I stumbled upon the bug “if you search for `\/` you end up with not finding a backslash because of the Vim escaping `/` even if it is already escaped” the second time I put something in it.

**Comment by scootergrisen** [comment]
https://github.com/vim/vim/blob/master/src/gui_w32.c#L2824
https://github.com/vim/vim/blob/master/src/gui_w32.c#L2859

**Comment by ZyX-I** [comment]
Looks like there is inconsistency between GTK 2 GUI and win32 GUI: after updating version to 8.1.91 I still do not have a note about escaping. Though problem with `\/` did get fixed by the update.

**Comment by k-takata** [comment]
> I dont like the `(use '\\' to find a '\')` being part of the following strings used in the dialog title:

The dialog box is the default one on Windows. It's very easy to change the title, but not so easy to add a text box in the dialog box.

**Comment by scootergrisen** [comment]
I made https://github.com/vim/vim/pull/3230

**Comment by k-takata** [comment]
Fixed by 8.1.0197: https://github.com/vim/vim/commit/9e42c866484fe0199e8b17e7c44489386173acc9
