### ISSUE TITLE
Segmentation fault in specific directory

### ISSUE THREAD

**Issue by mingrammer** [vim/vim#3050]
When I open the vim in my `~/Desktop` directory, vim returns `Vim: Caught deadly signal SEGV`. Before this problem raises, I've opened a medium (or large? but just 2.5MB) size file (about 150k lines) in this directory.

But, there is no problem in other directories except `~/Desktop`.

What should I check for solving this problem?

### Full errror message

```
im: Caught deadly signal SEGV
Vim: Finished.

[1]    56962 segmentation fault  vim
```

### OS info

macOS Sierra 10.12.6

### Vim info

`vim --version`

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled May  7 2018 03:54:08)

**Comment by k-takata** [comment]
Please try executing Vim without plugins: `vim --clean`

> Vim Info

Could you also show the patch number? Whole output of `vim --version` might be better.

**Comment by mingrammer** [comment]
`vim --clean` works well.

This is my `vim --version`

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled May  7 2018 03:54:08)
macOS version
Included patches: 1-1800
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    -gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               +perl              +vertsplit
+clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           -python            +vreplace
+conceal           +linebreak         +python3           +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       -lua               +ruby              -X11
+dialog_con        +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             -xim
+digraphs          +modify_fname      +smartindent       -xpm
-dnd               +mouse             +startuptime       -xsmp
-ebcdic            -mouseshape        +statusline        -xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              -mouse_gpm         +syntax            
+ex_extra          -mouse_jsbterm     +tag_binary        
+extra_search      +mouse_netterm     +tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -D_DARWIN_C_SOURCE -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework AppKit   -mmacosx-version-min=10.12 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.26.2/lib/perl5/5.26.2/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/config-3.6m-darwin -lpython3.6m -framework CoreFoundation  -lruby.2.5.1 -lobjc    
```

**Comment by k-takata** [comment]
Then some of your plugins (or your settings in your .vimrc) might cause the SEGV.
Please narrow down your .vimrc to find which plugin is related.

If you can use `gdb`, please get the stack trace information.

**Comment by mingrammer** [comment]
Ok, I'll try that

**Comment by nuko8** [comment]
Although it should be easy to install `gdb` via package managers, you need to do an extra post-installation procedure, i.e., codesigning that permits the debugger to control other processes to be debugged.   The way of codesigning varies from version  to version (See [this](https://sourceware.org/gdb/wiki/BuildingOnDarwin#Giving_gdb_permission_to_control_other_processes) for details).

In addition, by default, macOS won't dump core files when programs crash.  Furthermore, core files will be yielded at `/cores/`, not at the current working directory of crashed processes.

So, one thing and another, the most natural, easiest way to examine a core file to obtain the stack trace on macOS would be as follows:
1.  Rebuild Vim with the`-g` option (I don't know how to do this with Homebrew).
2. 
```
    $ cd ~/Desktop
    $ ulimit -c unlimited
```
3.  Run the Vim that was built with `-g` on the "`ulimit -c unlimited`" shell with the condition you know for Vim to crash.  When Vim crashes, you should have the core file `/cores/core.<PID>`, where `<PID>` is the process ID of the Vim process that has just crashed.
4.  Get the stack trace with Xcode's default debugger `lldb(1)`:
```
    $ lldb /path/to/vim -c /cores/core.<PID>
    (lldb) bt
```
(To quit lldb, just `(lldb) q`<kbd>Enter</kbd>).

The resulting backtrace should be readable for people who are usually using `gdb`.

**Comment by dpelle** [comment]
Can you reproduce this when running vim with valgrind?
i.e run vim like this for example:
```
$ valgrind --log-file=valgrind.log --num-callers=50 --track-origins=yes vim ~/Desktop/foo
```
After this, the log file valgrind.log may contain useful information to debug the issue.

**Comment by mingrammer** [comment]
I updated the vim with `brew upgrade && brew update`, the problem was gone!

**Comment by mingrammer** [comment]
Thank you guys..!
