### ISSUE TITLE
"[No Name]" or "[No File]"

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3052]
In gVim 8.1.1 i see "[No Name]" in the window title but "[No File]" in the buffer menu.
Should they not be the same?

**Comment by tonymec** [comment]
In gvim 8.1.92, when I open a normal buffer without naming it yet (e.g. with `:new` without a filename), I see `[No Name]` both on the statusline and in the output of `:ls`. OTOH, `[No File]` would mean a special buffer, not meant to be written to disk. `netrw`'s disk directories, even though they represent something that exists somewhere on a local or remote disk, are such "not-to-be-written" buffers, but they have a name, which is the directory name. A buffer *can* be both nameless and not-to-be-written if you open it without a name and give it a `'buftype'` of `nofile`. That is a rather special kind of buffer, however.

Best regards,
Tony.

**Comment by chrisbra** [comment]
I guess what is meant is the window title and the Buffer menu. How about the following patch:
```patch
diff --git a/runtime/menu.vim b/runtime/menu.vim
index fd5d91482..b9bd3d89c 100644
--- a/runtime/menu.vim
+++ b/runtime/menu.vim
@@ -809,7 +809,7 @@ func! s:BMMunge(fname, bnum)
   let name = a:fname
   if name == ''
     if !exists("g:menutrans_no_file")
-      let g:menutrans_no_file = "[No file]"
+      let g:menutrans_no_file = "[No Name]"
     endif
     let name = g:menutrans_no_file
   else
```

**Comment by brammool** [comment]
Looks like a good solution, I'll include it.
