### ISSUE TITLE
Multiple gVim dialog titles says "Vim 8.1"

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3055]
It seems most dialog titles in gVim just says "Vim 8.1".
Like the Help > Find... dialog.
Would it not be better to add a descriptive title?

**Comment by k-takata** [comment]
Do you mean that they should include patchlevel?

**Comment by scootergrisen** [comment]
No.
It should say "Find" in the title of the find dialog (Help>Find...).
Just like it says "Font" in the title of the font dialog (Edit>Font...).

**Comment by k-takata** [comment]
The dialog box is shown by the Vim script function `inputdialog()`. Currently it doesn't support setting the title.

**Comment by scootergrisen** [comment]
:cry: ok

**Comment by k-takata** [comment]
Adding an argument to `inputdialog()` might be an option, but it already has three arguments.
I think it's important to keep simplicity and also consistency with `input()`.

**Comment by scootergrisen** [comment]
From a users point of view its not consistent when some titles are "Vim 8.1" and some are not.
