### ISSUE TITLE
SQL syntax highlighting incorrectly escapes backslashes

### ISSUE THREAD

**Issue by LordAro** [vim/vim#3062]
Vim 8.1.22, but I think the relevant line is at https://github.com/vim/vim/blob/master/runtime/syntax/sqloracle.vim#L57-L58 in master

Backslashes in SQL do not need escaping, such that `'\'` is a valid string. The syntax highlighting does not reflect this - continuing the string past the end instead

There's also a lack of `''` not being escaped - this is a valid way of representing `'`

Best thing i could find resembling the standard: https://web.archive.org/web/20150922065035/https://mariadb.com/kb/en/sql-99/character-string-literals/

**Comment by LordAro** [comment]
My bad, i neglected to read to the end of the contributing document!

**Comment by LordAro** [comment]
...though it would be nice if the file were updated :)

**Comment by chrisbra** [comment]
I'll send an update to Bram soon
