### ISSUE TITLE
Autocommands strings with "-" and space

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3063]
It seems autocommand is written "autocommand" expect for this string with a "-" and big "C":

    #. Highlight title
    #: fileio.c:8537
    msgid ""
    "\n"
    "--- Auto-Commands ---"

And this string with a space:

    #: fileio.c:9858
    #, c-format
    msgid "%s Auto commands for \"%s\""

I'm guessing they should be without "-" and space and big "C".

    "--- Autocommands ---"
    "%s Autocommands for \"%s\""

**Comment by brammool** [comment]
> It seems autocommand is written "autocommand" expect for this string
> with a "-" and big "C":
> 
>     #. Highlight title
>     #: fileio.c:8537
>     msgid ""
>     "\n"
>     "--- Auto-Commands ---"
> 
> And this string with a space:
> 
>     #: fileio.c:9858
>     #, c-format
>     msgid "%s Auto commands for \"%s\""
> 
> I'm guessing they should be without "-" and space and big "C".
> 
>     "--- Autocommands ---"
>     "%s Autocommands for \"%s\""

I do like Auto-commands, but it's currently rarely used.  So let's make
it consistent by using Autocommands.

-- 
There's no place like $(HOME)!

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
Fixed with 8.1.0096: 8c55533c6f109db2a0fff69651887f9474eb09c6
