### ISSUE TITLE
Some submenus are not loaded on startup

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3064]
It seems some for the submenu items like:

    Edit > Show Color Schemes in Menu
    Edit > Show Keymaps in Menu

Does not initially show the submenu.
You have to click the submenu item one to load the submenu and then go into the Edit menu again to see that the submenu is now there.

But then again if you click Edit a few times to unfold/fold the menu then for some reason the Color Schemes and Keymaps menus are loaded.

I dont know why the sub menus are not just loaded. For reasons of speed i would presume.

But if the sub menus are not there on startup could we not make it so that you could just hover the cursor on the menu item or click it to load the submenu without having to go to the edit menu once again.

gVim 8.1.1 on Windows 7.

**Comment by k-takata** [comment]
They are loaded lazily because loading those menus are slow.
See `:help menu.vim` and the [patch 8.0.1279](https://github.com/vim/vim/commit/040c1feb212568cf04265e59b26182f8b76057aa).

**Comment by brammool** [comment]
> It seems some for the submenu items like:
> 
>     Edit > Show Color Schemes in Menu
>     Edit > Show Keymaps in Menu
> 
> Does not initially show the submenu.
> You have to click the submenu item one to load the submenu and then go
> into the Edit menu again to see that the submenu is now there.
> 
> But then again if you click Edit a few times to unfold/fold the menu
> then for some reason the Color Schemes and Keymaps menus are loaded.
> 
> I dont know why the sub menus are not just loaded. For reasons of
> speed i would presume.

Yes, analyzing startup time showed that loading these menus takes quite
a bit of time, while they are hardly ever used.

> But if the sub menus are not there on startup could we not make it so
> that you could just hover the cursor on the menu item or click it to
> load the submenu without having to go to the edit menu once again.

I think the current solution works quite well, don't see a reason to
change it.

-- 
From "know your smileys":
 :-| :-|   Deja' vu!

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by scootergrisen** [comment]
Cant they just be loaded when the cursor is on the menu item?
I find it annoying that i have to open the menu click the menu item... then do the exact same thing again.

Or dont close the menu when i click "Show..." that way i dont have to open it again.

**Comment by k-takata** [comment]
Vim script doesn't support such fancy mechanism.
If you don't like the behavior, write `let do_no_lazyload_menus = 1` in your .vimrc as the help says.

**Comment by scootergrisen** [comment]
In gVim on Linux Mint using GTK i think the menu updates when its unfolder without having to close and reopen it so thats kind of what i was looking for.
let do_no_lazyload_menus = 0 does not seem to disable it and let do_no_lazyload_menus = 1 does not seem to change it.
It take about 4 seconds from i start gvim untill the menu items changes to sub menus automatically.

**Comment by chrisbra** [comment]
You need to make sure this setting comes before the menus are actually loaded. This can happen when using the `:filetype` and `:syn` commands which might also load menus. So it should be at the very beginning.
