### ISSUE TITLE
VIM and GVIM window titles are all upper case

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3065]
If i start Vim or gVim the window title is VIM and GVIM.

I'm not sure but is Vim and gVim not the correct way to write it?

**Comment by tonymec** [comment]
The program names are vim and gvim (both in lowercase, except maybe in DOS-like 8.3 notation, where I suppose they are VIM.EXE and GVIM.EXE respectively. (On Unix-like OSes including Linux, binary executables usually have no extension to their filename, and Vim is no exception).

When talking about the editor, I usually use "Vim" when both the console utility and the GUI are meant, "gvim" for the GUI only, or "Console Vim" for the console utility only. Other people may have some slightly different customs, but IMHO as long as we understand each other's meaning, the rest is secondary. However I notice that both `:intro` and `:version` say `VIM - Vi IMproved` with VIM in all caps.

For the purposes of the `+clientserver` feature, server names' case is ignored, i.e. "gvim" and "GVIM" are considered equal. There has long been the following snippet in my vimrc:
``` vim
if has('gui_running')
  au GUIEnter *
    \ if has('clientserver') && v:servername == '' && serverlist() == ''
      \ | silent! call remote_startserver('GVIM') | endif
endif
```
As you can see, I use all caps in this case; but of course, YMMV. I think that this also sets the title for the gvim titlebar but it's been so long, I'm not sure anymore.

Best regards,
Tony.

**Comment by scootergrisen** [comment]
Ok so its the servername with all caps in the title.
Seems `--servername teST` becomes all upper case "TEST" even though i did not write it like that.
I would just expect it to be the program name in the title.

**Comment by chrisbra** [comment]
So let's amend the documentation:
```patch
diff --git a/runtime/doc/remote.txt b/runtime/doc/remote.txt
index f856c98fc..b477ca77d 100644
--- a/runtime/doc/remote.txt
+++ b/runtime/doc/remote.txt
@@ -63,7 +63,7 @@ The following command line arguments are available:
    --servername {name}         Become the server {name}.  When used together
                                with one of the --remote commands: connect to
                                server {name} instead of the default (see
-                               below).
+                               below).  The {name} will be used in upper case.
                                                                *--remote-send*
    --remote-send {keys}                Send {keys} to server and exit.  The {keys}
                                are not mapped.  Special key names are
```

**Comment by chrisbra** [comment]
closed by https://github.com/vim/vim/commit/675e8d6adb88d5b38087870dfda51c0205070741
