### ISSUE TITLE
The word "compiled" is not translateable

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3066]
I would like to translate the word word "compiled" in :verson.

    VIM - Vi IMproved 8.1 (2018 May 18, compiled May 18 2018 18:36:07)

From src/version.h:

    #define VIM_VERSION_LONG_DATE	"VIM - Vi IMproved 8.1 (2018 May 17, compiled "

**Comment by brammool** [comment]
> I would like to translate the word word "compiled" in :verson.
> 
>     VIM - Vi IMproved 8.1 (2018 May 18, compiled May 18 2018 18:36:07)
> 
> >From src/version.h:
> 
>     #define VIM_VERSION_LONG_DATE	"VIM - Vi IMproved 8.1 (2018 May 17, compiled "

That requires a few changes.

-- 
From "know your smileys":
 :.-(	Crying

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
Fixed by 8.1.0103: https://github.com/vim/vim/commit/35fb6fbf727c72eb5987a1556bbba26dca14cc48
