### ISSUE TITLE
how do I make popup menu transparent?

### ISSUE THREAD

**Issue by ghost** [vim/vim#3067]
Is it possible?

**Comment by k-takata** [comment]
AFAIK, no. Is there any use case for that?
Note that Vim is a cross platform editor. If a feature is really useful in many platforms, it might be accepted. But it is useful only in limited platform, it might not be accepted.

**Comment by ghost** [comment]
autocomplete popup menu show up window has  cover the code window, this could be not convinient .

**Comment by chrisbra** [comment]
I don't understand. When the popup window is transparent, it would make it a lot harder to read. BTW: have you tried to define the various Pmenu highlighting groups with bg=NONE? 

Also please note, ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. Closing.
