### ISSUE TITLE
:f[ile][!] prints nothing when 'shortmess' contains 'F'

### ISSUE THREAD

**Issue by flemingfleming** [vim/vim#3070]
I am assuming that this is a bug as `CTRL-G` still works the same way (prints the file information) when `'shortmess'` contains `F`, the documentation suggests that the message is only suppressed when going to edit another file, and `:file!` should never have it's output affected by `'shortmess'`

To reproduce with `vim -Nu NONE`

```
set shortmess=F

" All of
file | file! | f | f!
"print no output

" CTRL-G is not affected, the following will print information about the current file:
execute "normal! \<c-g>"
```

Note: `:f` can still change buffer names, only output appears to be surpressed

Tested on Vim version 8.1 patches 1-22, huge version with gtk3 gui (OS is Arch Linux)

**Comment by chrisbra** [comment]
This can be fixed with the following patch:
```patch
diff --git a/src/ex_cmds.c b/src/ex_cmds.c
index 53334342c..3f7cb7a60 100644
--- a/src/ex_cmds.c
+++ b/src/ex_cmds.c
@@ -3095,9 +3095,7 @@ ex_file(exarg_T *eap)
        if (rename_buffer(eap->arg) == FAIL)
            return;
     }
-    /* print full file name if :cd used */
-    if (!shortmess(SHM_FILEINFO))
-       fileinfo(FALSE, FALSE, eap->forceit);
+    fileinfo(FALSE, FALSE, eap->forceit);
     redraw_tabline = TRUE;
 }

diff --git a/src/testdir/test_options.vim b/src/testdir/test_options.vim
index 167cb1ce0..e4e64be2f 100644
--- a/src/testdir/test_options.vim
+++ b/src/testdir/test_options.vim
@@ -400,3 +400,12 @@ func Test_copy_winopt()
     call assert_equal(4,&numberwidth)
     bw!
 endfunc
+
+function! Test_shortmess()
+  new
+  set shortmess=F
+  call assert_match("\[No file\]", execute('file'))
+  bw
+  set shortmess&
+endfunction
```

**Comment by brammool** [comment]
Christian wrote:

> This can be fixed with the following patch:
> ```patch
> diff --git a/src/ex_cmds.c b/src/ex_cmds.c
> index 53334342c..3f7cb7a60 100644
> --- a/src/ex_cmds.c
> +++ b/src/ex_cmds.c
> @@ -3095,9 +3095,7 @@ ex_file(exarg_T *eap)
>         if (rename_buffer(eap->arg) == FAIL)
>             return;
>      }
> -    /* print full file name if :cd used */
> -    if (!shortmess(SHM_FILEINFO))
> -       fileinfo(FALSE, FALSE, eap->forceit);
> +    fileinfo(FALSE, FALSE, eap->forceit);
>      redraw_tabline = TRUE;
>  }
> 
> diff --git a/src/testdir/test_options.vim b/src/testdir/test_options.vim
> index 167cb1ce0..e4e64be2f 100644
> --- a/src/testdir/test_options.vim
> +++ b/src/testdir/test_options.vim
> @@ -400,3 +400,12 @@ func Test_copy_winopt()
>      call assert_equal(4,&numberwidth)
>      bw!
>  endfunc
> +
> +function! Test_shortmess()
> +  " This used to cause Vim to access uninitialized memory.
> +  new
> +  set shortmess=F
> +  call assert_match("\[No file\]", execute('file'))
> +  bw
> +  set shortmess&
> +endfunction
> ```

Hmm, not quite right.  The 'F' flag should apply when changing the file
name, then there is no need to display it.

Looks like you copy-pasted that test :-).  I'll add some more.

-- 
Contrary to popular belief, Unix is user friendly.
It just happens to be selective about who it makes friends with.
                                               -- Dave Parnas

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
