### ISSUE TITLE
Perhaps remove some strings starting with "syntax" from translation

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3071]
I see some strings in the po file that i think might be commands.

    MSG(_("syntax conceal on"));
    MSG(_("syntax conceal off"));
    MSG(_("syntax case ignore"));
    MSG(_("syntax case match"));
    MSG(_("syntax spell toplevel"));
    MSG(_("syntax spell notoplevel"));
    MSG(_("syntax spell default"));
    MSG_PUTS(_("syntax iskeyword "));

If they are commands and should always be the same i guess they should be removed from the po files.

**Comment by brammool** [comment]
> I see some strings in the po file that i think might be commands.
> 
>     MSG(_("syntax conceal on"));
>     MSG(_("syntax conceal off"));
>     MSG(_("syntax case ignore"));
>     MSG(_("syntax case match"));
>     MSG(_("syntax spell toplevel"));
>     MSG(_("syntax spell notoplevel"));
>     MSG(_("syntax spell default"));
>     MSG_PUTS(_("syntax iskeyword "));
> 
> If they are commands and should always be the same i guess they should
> be removed from the po files.

They are not commands but reporting the status.  For example, for "syntax
conceal on" the word "on" could be translated.

In many cases leaving it untranslated would work.  But disabling
translation might not be the best solution.

-- 
Common sense is what tells you that the world is flat.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
