### ISSUE TITLE
Display problem with vartabstop and linebreak

### ISSUE THREAD

**Issue by Raimondi** [vim/vim#3076]
Set up: Run vim with this command in a 90 columns wide terminal window:

    vim -Nu NONE -i NONE -c 'set linebreak vartabstop=10,20,30,40,50,60,70' -c 'call setline(1, "\tx\tx\tx\tx")'

Expected: After this, the fourth 'x' should be on the second line.

Result: The fourth 'x' is displayed in the first line, very close to the third 'x'.

This is the output of `vim --version`:

```
> vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 23 2018 17:26:08)
macOS version
Included patches: 1-105
Compiled by israel@Israels-iMac.lan
Huge version without GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               -perl              +vartabs
+clipboard         +jumplist          +persistent_undo   +vertsplit
+cmdline_compl     +keymap            +postscript        +virtualedit
+cmdline_hist      +lambda            +printer           +visual
+cmdline_info      +langmap           +profile           +visualextra
+comments          +libcall           -python            +viminfo
+conceal           +linebreak         -python3           +vreplace
+cryptv            +lispindent        +quickfix          +wildignore
+cscope            +listcmds          +reltime           +wildmenu
+cursorbind        +localmap          +rightleft         +windows
+cursorshape       -lua               -ruby              +writebackup
+dialog_con        +menu              +scrollbind        -X11
+diff              +mksession         +signs             -xfontset
+digraphs          +modify_fname      +smartindent       -xim
-dnd               +mouse             +startuptime       -xpm
-ebcdic            -mouseshape        +statusline        -xsmp
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_clipboard
+eval              -mouse_gpm         +syntax            -xterm_save
+ex_extra          -mouse_jsbterm     +tag_binary
+extra_search      +mouse_netterm     +tag_old_static
   system vimrc file: "/opt/local/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/opt/local/share/vim"
Compilation: /usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -I/opt/local/include -DMACOS_X -DMACOS_X_DARWIN  -pipe -Os -arch x86_64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: /usr/bin/clang   -L/opt/local/lib -Wl,-headerpad_max_install_names -arch x86_64 -o vim        -lm  -lncurses -liconv -lintl -framework AppKit
```

**Comment by vim-ml** [comment]
On Sa, 23 Jun 2018, Israel Chauca Fuentes wrote:

> Set up: Run vim with this command in a 90 columns wide terminal window:
> 
>     vim -Nu NONE -i NONE -c 'set linebreak vartabstop=10,20,30,40,50,60,70' -c 'call setline(1, "\tx\tx\tx\tx")'
> 
> Expected: After this, the fourth 'x' should be on the second line with the cursor.
> 
> Result: The fourth 'x' is displayed in the first line, very close to the third 'x'.
> 
> This is the output of `vim --version`:

Thanks for the clear explanation. The attached patch fixes it (only 
visible in the mailinglist). I took the liberty to turn your example 
into a test.

Best,
Christian
-- 
Die Kunst zu leben ist nicht zu existieren, sondern den
anderen zu zeigen, dass man existiert!
		-- Benjamin Stramke

**Comment by vim-ml** [comment]
Christian wrote:

> On Sa, 23 Jun 2018, Israel Chauca Fuentes wrote:
> 
> > Set up: Run vim with this command in a 90 columns wide terminal window:
> > 
> >     vim -Nu NONE -i NONE -c 'set linebreak vartabstop=10,20,30,40,50,60,70' -c 'call setline(1, "\tx\tx\tx\tx")'
> > 
> > Expected: After this, the fourth 'x' should be on the second line with the cursor.
> > 
> > Result: The fourth 'x' is displayed in the first line, very close to the third 'x'.
> > 
> > This is the output of `vim --version`:
> 
> Thanks for the clear explanation. The attached patch fixes it (only 
> visible in the mailinglist). I took the liberty to turn your example 
> into a test.

Thanks.  Can we make the test work with a narrower window?  Mostly 80
chars is used, I don't think the CI runs with a larger terminal,
resulting in the test being skipped.

-- 
hundred-and-one symptoms of being an internet addict:
105. When someone asks you for your address, you tell them your URL.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Raimondi** [comment]
This command can reproduce the issue with a window width between 64 to 83 columns:

    vim -Nu NONE -i NONE -c 'set linebreak vartabstop=10,15,20,40' -c 'call setline(1, "\tx\tx\tx\tx")'

Hope it helps with the test.

**Comment by chrisbra** [comment]
please hold back. I have a fix for a segfault in listmode and got a leak error von ex_retab I'd like to fix as well.

**Comment by brammool** [comment]
> This command can reproduce the issue with a window width between 64 to 83 columns:
> 
>     vim -Nu NONE -i NONE -c 'set linebreak vartabstop=10,15,20,40' -c 'call setline(1, "\tx\tx\tx\tx")'
> 
> Hope it helps with the test.

I'll put this in the test, please check that it works as expected once
you have the patch.

-- 
FIXME and XXX are two common keywords used to mark broken or incomplete code
not only since XXX as a sex reference would grab everybody's attention but
simply due to the fact that Vim would highlight these words.
					-- Hendrik Scholz

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
