### ISSUE TITLE
Running gvim --serverlist gives error dialog

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3077]
Running gvim --serverlist gives me a dialog with "Error" in the title and icon with X but its not an error.

**Comment by scootergrisen** [comment]
Running gvim --help gives a dialog with "Message" and a I icon.
So that would be better for gvim --serverlist.

**Comment by k-takata** [comment]
It looks that this is a Windows specific problem.
The title and the icon are controlled at here:
https://github.com/vim/vim/blob/04958cbaf25eea27eceedaa987adfb354ad5f7fd/src/os_mswin.c#L708-L715
I don't know why `gui.starting` is used here.

**Comment by k-takata** [comment]
Fixed by [8.1.1301](https://github.com/vim/vim/commit/0b75f7c97cd7f2529884c48dca8edb02abda4bc5) or some other version.
