### ISSUE TITLE
Command line is cleared after certain Python commands but shouldn't be

### ISSUE THREAD

**Issue by wilywampa** [vim/vim#3079]
I noticed this because call signatures displayed in the command line are being cleared for no good reason. Here's how to reproduce:

1. Run `vim -u NONE -i NONE` in vim compiled with `+python3`
2. Run `:python3 import vim`
3. Add any buffer to the buffer list with `:badd`, e.g. `:badd $MYVIMRC`
4. Run `:echo py3eval('vim.buffers[2].options["buflisted"]')`

The output from the `:echo` command will flash briefly and then disappear. If one runs the command above but change it to include `vim.buffers[1]` instead of `[2]`, the value is echoed and remains on screen as it should. It seems like accessing the options of an unloaded, listed buffer this way causes some side effect.

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 23 2018 19:49:03)
macOS version
Included patches: 1-105
Compiled by jniehus@MacBook-Pro-2
Huge version without GUI.  Features included (+) or not (-):
+sys_echo_off      -clientserver      +digraphs          +fork()            +listcmds          -mouse_sysmouse    +printer           -sun_workshop      -toolbar           -X11
+mac_clipboard     +clipboard         -dnd               -gettext           +localmap          +mouse_urxvt       +profile           +syntax            +user_commands     -xfontset
+acl               +cmdline_compl     -ebcdic            -hangul_input      +lua               +mouse_xterm       -python            +tag_binary        +vartabs           -xim
+arabic            +cmdline_hist      +emacs_tags        +iconv             +menu              +multi_byte        +python3           +tag_old_static    +vertsplit         -xpm
+autocmd           +cmdline_info      +eval              +insert_expand     +mksession         +multi_lang        +quickfix          -tag_any_white     +virtualedit       -xsmp
-autoservername    +comments          +ex_extra          +job               +modify_fname      -mzscheme          +reltime           -tcl               +visual            -xterm_clipboard
-balloon_eval      +conceal           +extra_search      +jumplist          +mouse             +netbeans_intg     +rightleft         +termguicolors     +visualextra       -xterm_save
+balloon_eval_term +cryptv            +farsi             +keymap            -mouseshape        +num64             +ruby              +terminal          +viminfo
-browse            +cscope            +file_in_path      +lambda            +mouse_dec         +packages          +scrollbind        +terminfo          +vreplace
++builtin_terms    +cursorbind        +find_in_path      +langmap           -mouse_gpm         +path_extra        +signs             +termresponse      +wildignore
+byte_offset       +cursorshape       +float             +libcall           -mouse_jsbterm     +perl              +smartindent       +textobjects       +wildmenu
+channel           +dialog_con        +folding           +linebreak         +mouse_netterm     +persistent_undo   +startuptime       +timers            +windows
+cindent           +diff              -footer            +lispindent        +mouse_sgr         +postscript        +statusline        +title             +writebackup
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/Users/jniehus/Documents/dev/vim_py3/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -ggdb -DDEBUG -Wall -Wshadow -Wmissing-prototypes
Linking: gcc   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lm -lncurses  -liconv -framew
ork AppKit  -L/usr/local/Cellar/lua/5.2.3_2/lib -llua -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.
6/lib/python3.6/config-3.6m-darwin -lpython3.6m -framework CoreFoundation  -lruby.2.4.1 -lobjc
  DEBUG BUILD
```

**Comment by brammool** [comment]
Jacob Niehus wrote:

> I noticed this because call signatures displayed in the command line
> are being cleared for no good reason. Here's how to reproduce:
> 
> 1. Run `vim -u NONE -i NONE` in vim compiled with `+python3`
> 2. Run `:python3 import vim`
> 3. Add any buffer to the buffer list with `:badd`, e.g. `:badd $MYVIMRC`
> 4. Run `:echo py3eval('vim.buffers[2].options["buflisted"]')`
> 
> The output from the `:echo` command will flash briefly and then
> disappear. If one runs the command above but change it to include
> `vim.buffers[1]` instead of `[2]`, the value is echoed and remains on
> screen as it should. It seems like accessing the options of an
> unloaded, listed buffer this way causes some side effect.

I haven't tried, but I see that the code uses aucmd_prepbuf() to get the
option value.  That may have side effects, we can avoid that.  I'll make
a patch, please let us know if it doesn't fix the problem.


-- 
hundred-and-one symptoms of being an internet addict:
98. The Alta Vista administrators ask you what sites are missing
    in their index files.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by wilywampa** [comment]
That fixed it. Thanks!
