### ISSUE TITLE
Make the Windows installer translatable

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3082]
I suggest making the Windows installer translatable.

I dont know how but i think it says here how to do it:
http://nsis.sourceforge.net/Docs/Chapter4.html#langsinstructions

There is an example here that might help:
https://github.com/belphegor-belbel/instlux

**Comment by k-takata** [comment]
This can be fixed with the PR #3501. It already includes some translation.

**Comment by k-takata** [comment]
PR #3501 has been merged as v8.1.0616, so now we can translate the Windows installer. Closing.

Note: We have only 8 translations and half of them are still incomplete (Dutch, Italian, Simplified Chinese and Traditional Chinese). Updates for the translations are welcome. Please check `nsis/lang/*.nsi`.
