### ISSUE TITLE
Adding .desktop strings til po files

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3085]
I suggest adding the translatable strings for the .desktop files in the po files so translators can translate the strings same place as the other strings.

https://github.com/vim/vim/blob/master/runtime/vim.desktop
https://github.com/vim/vim/blob/master/runtime/gvim.desktop

Looking at other projects it seems they add "_" at the beginning and then gettext takes the translations from the po file. But i dont know how it works.

    _GenericName=Text Editor
    _Comment=Edit text files

**Comment by k-takata** [comment]
It seems that GNU gettext supports .desktop files.
https://www.gnu.org/software/gettext/manual/html_node/xgettext-Invocation.html#Choice-of-input-file-language
https://www.gnu.org/software/gettext/manual/html_node/msgfmt-Invocation.html#Desktop-Entry-mode-operations

But I think we still need to support other gettext implementations.

**Comment by k-takata** [comment]
This is fixed with [8.1.1147](https://github.com/vim/vim/commit/a60e536a290f7c14cf2b255ddb7071b39619fcd3) (and other patches). Closing.
