### ISSUE TITLE
cexpr no longer jumps to first error automatically.

### ISSUE THREAD

**Issue by systemmonkey42** [vim/vim#3092]
Since upgrading to 8.1 (specifically tested with 8.1.0115) `:cexpr` command no longer jumps to first error automatically.

**Comment by systemmonkey42** [comment]
Full vim version details

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 25 2018 09:33:44)
Included patches: 1-115
Compiled by *******@********
Huge version without GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
+clientserver      +job               -perl              +vartabs
+clipboard         +jumplist          +persistent_undo   +vertsplit
+cmdline_compl     +keymap            +postscript        +virtualedit
+cmdline_hist      +lambda            +printer           +visual
+cmdline_info      +langmap           +profile           +visualextra
+comments          +libcall           +python/dyn        +viminfo
+conceal           +linebreak         -python3           +vreplace
+cryptv            +lispindent        +quickfix          +wildignore
+cscope            +listcmds          +reltime           +wildmenu
+cursorbind        +localmap          +rightleft         +windows
+cursorshape       +lua/dyn           +ruby              +writebackup
+dialog_con        +menu              +scrollbind        +X11
+diff              +mksession         +signs             +xfontset
+digraphs          +modify_fname      +smartindent       -xim
-dnd               +mouse             +startuptime       -xpm
-ebcdic            -mouseshape        +statusline        +xsmp_interact
+emacs_tags        +mouse_dec         -sun_workshop      +xterm_clipboard
+eval              -mouse_gpm         +syntax            -xterm_save
+ex_extra          -mouse_jsbterm     +tag_binary
+extra_search      +mouse_netterm     +tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim81"
Compilation: gcc -std=gnu99 -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc -std=gnu99   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic  -L/usr/local/lib -Wl,--as-needed -o vim -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -ldl       -lruby-2.3 -lpthread -lgmp -ldl -lcrypt -lm
```

**Comment by vim-ml** [comment]
Hi,

On Sun, Jun 24, 2018 at 4:49 PM, David le Blanc
<vim-dev-github@256bit.org> wrote:
>
> Since upgrading to 8.1 (specifically tested with 8.1.0115) :cexpr command no
> longer jumps to first error automatically.
>

I tried to reproduce this problem with ":cexpr" using Vim 8.1.26 and I couldn't
reproduce the problem. After using ":cexpr ...", the cursor does jump to the
first error. Can you send the list of steps to reproduce this problem?

- Yegappan

**Comment by systemmonkey42** [comment]
Hi, I've now tested with 8.1.26, and the problem doesn't appear.

I put together the following contrived example to test;

`vim -u NONE '+cexpr system("grep -nH : *.yml")'`

With 8.1.26, VIM opens with the first YML file displayed, and the cursor on the first line matching ':'

With 8.1.115, VIM opens with an empty buffer. Typing `:cfirst` jumps to the first file as expected because the quickfix list is valid.

Note that this effects 'cexpr' directly.  The following example using `-q` works correctly in either version;

`vi -u NONE -q <(grep -nH : *.yml)`

Regards

**Comment by vim-ml** [comment]
Hi,

On Sun, Jun 24, 2018 at 8:59 PM, David le Blanc
<vim-dev-github@256bit.org> wrote:
> Hi, I've now tested with 8.1.26, and the problem doesn't appear.
>
> I put together the following contrived example to test;
>
> vim -u NONE '+cexpr system("grep -nH : *.yml")'
>
> With 8.1.26, VIM opens with the first YML file displayed, and the cursor on
> the first line matching ':'
>
> With 8.1.115, VIM opens with an empty buffer. Typing :cfirst jumps to the
> first file as expected because the quickfix list is valid.
>

I am able to reproduce the problem with 8.1.115. I narrowed it down
to the patch 8.1.0073 which introduced this regression.

- Yegappan

>
> Note that this effects 'cexpr' directly. The following example using -q
> works correctly in either version;
>
> vi -u NONE -q <(grep -nH : *.yml)
>
> Regards
>
