### ISSUE TITLE
Button called 1

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3098]
Saw this lovely dialog/button running ":set spl=da spell" that dont make much sense.

![spell](https://user-images.githubusercontent.com/1836590/41874038-ffaafff4-78c6-11e8-8e1b-5e6a9d935626.jpg)

**Comment by scootergrisen** [comment]
In the console it makes a little more sense:

    In which directory do you want to write the file:
    1. C:\Program Files (x86)\Vim\vim81\spell
    [C]ancel, (1):

**Comment by brammool** [comment]
I don't think we can improve this.  Consider that when 'runtime' has multiple entries there can be several choices.

**Comment by scootergrisen** [comment]
If its a question it should have a "?".

How about changing the button order?
Have Cancel as the right most button in dialogs consistenty throughout the program.
At least in Windows 7 cancel appear to the right.
