### ISSUE TITLE
cs and ko says Bram for Messages maintainer

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3103]
cs and ko translations have the initial name and email from the msgid.
I'm guesstion Bram did not translated them.

    msgid "Messages maintainer: Bram Moolenaar <Bram@vim.org>"
    msgstr "Správce zpráv: Bram Moolenaar <Bram@vim.org>"

    msgid "Messages maintainer: Bram Moolenaar <Bram@vim.org>"
    msgstr "메시지 관리자: Bram Moolenaar <Bram@vim.org>"

I write the translators mentioned in the po files but one is updated last in 2002 so i write it here to.

**Comment by scootergrisen** [comment]
The 3 emails in cs dont exists anymore.

**Comment by lacygoill** [comment]
The korean translation file has been fixed, but not the czech one.  Its last update goes back to 2002.  Anyway, here is a patch:
```diff
diff --git a/src/po/cs.po b/src/po/cs.po
index 6e6cc3bd4..e1f1ee820 100644
--- a/src/po/cs.po
+++ b/src/po/cs.po
@@ -2927,7 +2927,7 @@ msgid "[string too long]"
 msgstr "[pøíli¹ dlouhý øetìzec]"
 
 msgid "Messages maintainer: Bram Moolenaar <Bram@vim.org>"
-msgstr "Správce zpráv: Bram Moolenaar <Bram@vim.org>"
+msgstr "Správce zpráv: Jiøí Pavlovský <jpavlovsky@mbox.vol.cz>"
 
 msgid "Interrupt: "
 msgstr "Pøeru¹ení: "
```
I didn't check whether the email address was still working; probably not.

**Comment by brammool** [comment]
> The korean translation file has been fixed, but not the czech one.
> Its last update goes back to 2002.  Anyway, here is a patch:
> ```diff
> diff --git a/src/po/cs.po b/src/po/cs.po
> index 6e6cc3bd4..e1f1ee820 100644
> --- a/src/po/cs.po
> +++ b/src/po/cs.po
> @@ -2927,7 +2927,7 @@ msgid "[string too long]"
>  msgstr "[pøíli¹ dlouhý øetìzec]"
>  
>  msgid "Messages maintainer: Bram Moolenaar <Bram@vim.org>"
> -msgstr "Správce zpráv: Bram Moolenaar <Bram@vim.org>"
> +msgstr "Správce zpráv: Jiøí Pavlovský <jpavlovsky@mbox.vol.cz>"
>  
>  msgid "Interrupt: "
>  msgstr "Pøeru¹ení: "
> ```
> I didn't check whether the email address was still working; probably not.

I'll include it and cc this message to that address.

We should perhaps have a yearly "translation festival" to encourage
updating the translations.  Someone want to organise that?

We could also use Google translate as a better-than-nothing solution for
untranslated messages.

-- 
Overflow on /dev/null, please empty the bit bucket.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by scootergrisen** [comment]
Oh no please don't automatically translate strings using something like google translate.
That will just give bad translations and make it harder for translators to correct the badly translated strings.
It would be better to instead focus on making it easier for translators to translate the strings so they would want to translate it.
