### ISSUE TITLE
Postscript match parentheses error

### ISSUE THREAD

**Issue by guido99** [vim/vim#3119]
Simple postscript file example, simple.ps

                 (       )

a pair of parentheses. With syntax *on* & cursor on either left or right char, I get "E475:Invalid argument:0. Error detected while processing function <SNR>11_Highlight_Matching_Pair: line 97." This occurs on *any* postscript file I edit. I am using 8.1.113.

![error](https://user-images.githubusercontent.com/34629286/42106252-440ecfd6-7b88-11e8-9e90-31393ddd9136.png)

![source](https://user-images.githubusercontent.com/34629286/42106399-d2c8353c-7b88-11e8-9f86-53377da5cd6c.png)

Can anyone else replicate this behavior?

**Comment by andymass** [comment]
This was fixed in 8.1.0115, https://github.com/vim/vim/commit/b7a5ab112ab2267c54acdb6a326642afcd797bc4

**Comment by guido99** [comment]
Thanks. Close the issue.
