### ISSUE TITLE
Is it possible to disable vim from opening too large files?

### ISSUE THREAD

**Issue by xuejipeng** [vim/vim#3120]
I performed a misoperation and opened a 6G file with vim, which caused the server to crash. I wonder if there is a configuration that can limit the size of the largest file that vim can open.

**Comment by chemzqm** [comment]
Maybe just wrap your vim command with `du -h` in a shell script.

**Comment by lifepillar** [comment]
From `:h Cmd-event`:

>When using one of the "*Cmd" events, the matching autocommands are expected to
>do the file reading, writing or sourcing.

Maybe, you may use `BufReadCmd` to check the file's size and skip the reading. Disclaimer: I have never used those autocommands myself.

**Comment by chrisbra** [comment]
Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. Closing.
