### ISSUE TITLE
"Ctrl+o u" in Insert mode is performed with a delay if 'showmode' is on

### ISSUE THREAD

**Issue by lkintact** [vim/vim#3125]
1. Run `gvim.exe -u NONE`
2. Execute `:set showmode`
3. Enter Insert mode, type some text and hit <kbd>Ctrl-o u</kbd>. Gvim waits for about 2.5 seconds before performing the undo operation.
4. Get back to Normal mode, execute `:set noshowmode`, repeat step 3. Gvim performs the undo almost instantly.

OS: Windows 7,
Gvim: gvim_8.1.0126_x86.zip

**Comment by AntonSamokat** [comment]
This similar bug present in VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec 07 2023 15:42:49) but without `showmode`.
To reproduce:
In insert mode press "Ctrl+o u". There is delay about 3 seconds.

**Comment by AntonSamokat** [comment]
Created new bug report about this: ["Ctrl+o u" in Insert mode is performed with a about 3 seconds delay · Issue #14947 · vim/vim](https://github.com/vim/vim/issues/14947)
