### ISSUE TITLE
docs: Update/remove `shell-window` section from `tips.txt`

### ISSUE THREAD

**Issue by joshklod** [vim/vim#3135]
This section is now wrong.  It claims that it is impossible to execute a shell in a Vim window, which is possible in v8.1.

See `:h shell-window`

**Comment by brammool** [comment]
> This section is now wrong.  It claims that it is impossible to execute
> a shell in a Vim window, which is possible in v8.1.
> 
> See `:h shell-window`

Thanks for the tip :-).  I'll update that text.


-- 
Apathy Error: Don't bother striking any key.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
fixed by 6dc819b1299e1d9f99303568772ade544d5c1322
