### ISSUE TITLE
function string() inconsistent

### ISSUE THREAD

**Issue by strux-net** [vim/vim#3141]
The problem can be best seen if I execute this line
`:redir @a>|let a=expand("\<c-u>\<c-m>")|echo string(a)|redir END`

this fills register a with two characters.

If I now do ``"ap``to paste this register I get
`'^U^M'`
where ^U is the two characters ^ and U and ^M is the one character.

Experimenting a bit more shows that all ctrl-characters except ^M are
translated into two characters.

This looks like a bug to me.
At least I find no mentioning of this difference in the help.

**Comment by k-takata** [comment]
The behavior is came from `:echo` and `:redir`.
If you use `:echom` instead (without `:redir`), it is consistent.

```
:let a=expand("\<c-u>\<c-m>")
:echom a
^U^M
:let b=string(a)
:echom b
'^U^M'
```

All `^U` and `^M` are highlighted.

**Comment by strux-net** [comment]
So my question should be rephrased:
How to redir a string (containing ctrl-characters) consistenly

**Comment by k-takata** [comment]
Isn't using `:echom` enough?

**Comment by strux-net** [comment]
:echom indeed gives consistent results. It translates  cntrl-x to the two-character sequence ^ and x for all x.
What I need is to not translate the characters. But I just found out, that I can do this easily with writefile().
I guess, that my redir approach was from the time where no writefile() existed.
So this issue can be closed
