### ISSUE TITLE
recording into register records focus changes

### ISSUE THREAD

**Issue by strux-net** [vim/vim#3143]
I'm on Ubuntu (if that matters)

I start `gvim -u NONE -U NONE`
  I type `qaq`.
  `:dis a` shows that register a is empty (ok so far).
  Now I do `qa` to start a recording, but before the final 'q' I now switch to another application and back to gvim.
  Now, after the 'q' register a has some content (bad for me).
  It looks like `<80><fd>c<80><fd>b`
  I suspect this is for focus loss and focus gain.

My gvim is :
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul  1 2018 04:17:01)
Included patches: 1-127, 129-133
```

**Comment by brammool** [comment]
Michael Naumann wrote:

> I'm on Ubuntu (if that matters)
> 
> I start `gvim -u NONE -U NONE`
>   I type `qaq`.
>   `:dis a` shows that register a is empty (ok so far).
>   Now I do `qa` to start a recording, but before the final 'q' I now switch to another application and back to gvim.
>   Now, after the 'q' register a has some content (bad for me).
>   It looks like `<80><fd>c<80><fd>b`
>   I suspect this is for focus loss and focus gain.
> 
> 
> My gvim is :
> ```
> VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul  1 2018 04:17:01)
> Included patches: 1-127, 129-133
> ```

Yeah, those events are unlikely ever useful in a recording.
Let's filter them out.

-- 
Living in Hollywood is like living in a bowl of granola.  What ain't
fruits and nuts is flakes.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
