### ISSUE TITLE
x86 versions of Vim aren't available in the list of Windows releases

### ISSUE THREAD

**Issue by lkintact** [vim/vim#3144]
I noticed there are no x86 versions of Vim (`gvim_8.1.*_x86.exe`, `gvim_8.1.*_x86.zip` and `gvim_8.1.*_x86_pdb.zip`) in the list of the latest (v8.1.0139) Windows releases on `https://github.com/vim/vim-win32-installer/releases`.
Since the description - "_Download and execute the most recent gvim\_8..\_x86.exe file to install Vim. The exe file contains the (32bit) installer while the .zip files contain an archive of the 32bit (\_x86) or 64bit versions (\_x64). [...]_" - stayed the same, this is probably not intentional.

**Comment by k-takata** [comment]
https://ci.appveyor.com/project/chrisbra/vim-win32-installer/build/job/sggn8mo7j089wo3d#L1510
> Found errors in Test_list_table():
function RunTheTest[40]..Test_list_table line 5: Expected [3.14, 'hello', v:false, v:true] but got []

It seems that there are some problems in the CI environment. I will look into it later.

**Comment by k-takata** [comment]
I tested this on my local machine. `Test_list_table()` didn't fail when I use luajit 2.0 (compatible with lua 5.1) on x86, but it failed with lua 5.3 on x86.
It seems that the `vim.list()` lua function fails to convert a lua table. Maybe there are some problems in if_lua itself, not in the CI environment.

**Comment by chrisbra** [comment]
closing in favor of #3157
