### ISSUE TITLE
Icons is missing white highlight (due to transparency)

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3148]
These two icons seem to be missing the white highlight color as it have been set transparent:
https://raw.githubusercontent.com/vim/vim/master/nsis/icons/vim_16c.ico
https://raw.githubusercontent.com/vim/vim/master/nsis/icons/vim_uninst_16c.ico

From the Windows installer/uninstaller:
![vimtranswhite](https://user-images.githubusercontent.com/1836590/42237634-a2a9cee6-7efe-11e8-9025-14049a677d34.gif)

**Comment by brammool** [comment]
Indeed.  Must have happened when making the background transparent.
I used Gimp to fix it.
