### ISSUE TITLE
Possibly missing evim.man file

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3151]
I was looking into possibly translating man files.
It seems there is no evim.man file on https://github.com/vim/vim/tree/master/runtime/doc
I dont know if this is an error or what.

**Comment by k-takata** [comment]
`evim.1` is the file. You can check the result by using `groff` or other similar commands.
E.g.

```
$ groff -Tutf8 -Dutf8 -mandoc vim-LL.UTF-8.1 | less -R
```

**Comment by scootergrisen** [comment]
How come the other files have a .man file but not evim?

**Comment by vim-ml** [comment]
On Wed, Jul 4, 2018 at 2:33 AM, scootergrisen <vim-dev-github@256bit.org> wrote:
> How come the other files have a .man file but not evim?

On my system, where there is an own-compiled Vim 8.1 (8.1.146 as of
this writing) and (further down the $PATH) a Vim 8.0.1568 from my
Linux distro, I see at the bottom "2006 Apr 11" in the manpage for vim
but "2002 February 16" in the manpage for evim. This might be due to a
missing symlink since even "man vi" displays the manpage for Vim,
where evim is mentioned as an alternative executable name near the
top. Both these dates, however, look suspiciously old to me.

Best regards,
Tony.

**Comment by k-takata** [comment]
All `*.man` files are generated from `*.1`. (See `runtime/doc/Makefile`.)
You should translate are the `*.1` files, not `*.man`.

**Comment by k-takata** [comment]
Ah, are you just pointing out that the `evim.man` doesn't exist in the repository, and not talking about translation?

**Comment by scootergrisen** [comment]
Yep.

**Comment by scootergrisen** [comment]
I'm trying to find documentation for the man format or what ever it is but i cant seem to find it.

For these line number 1 and 3 becomes bold:

    .B Vimtutor
    starts the
    .B Vim
    tutor.

But for my translation i want to use a "-" but then "-vejledningen." becomes bold which i dont want.

    .B Vimtutor
    starter
    .B Vim-vejledningen.

If i move "-vejledningen." to the next line i get a space in between "Vim" and "-vejledningen." which i dont want.

    .B Vimtutor
    starter
    .B Vim
    -vejledningen.

**Comment by k-takata** [comment]
I don't know how to do that, but this format is the roff format.
You can refer the manual by executing `man 7 roff` and `man 7 groff` on Linux (or other Unix-like systems).
You can also see on the Web. e.g. http://man.gnu.org.ua/manpage/?7+groff

**Comment by jottkaerr** [comment]
You might try

    .BR Vim"-vejledningen"

or

    .B Vim\c
    -vejledningen

or

    \fBVim\fR-vejledningen

I'm not sure which is most portable and works best for man pages, though

**Comment by scootergrisen** [comment]
I will use the \c one. Nice and short.

Are there any programs for checking the files for errors?

**Comment by k-takata** [comment]
Fixed in https://github.com/vim/vim/commit/fd35811ca528de7612f9571bce20ef4c392fe5f7 and https://github.com/vim/vim/commit/ae728edc93fe5a2f8c39fa75b1ae9ed71526858c.
