### ISSUE TITLE
Crash (FPE) with 'smarttab' 'sw=0', 'sts=-1'

### ISSUE THREAD

**Issue by FalacerSelene** [vim/vim#3155]
Running the following:

`set smarttab shiftwidth=0 softtabstop=-1`

then attempting to insert a tab at the start of a line causes

```
Vim: Caught deadly signal FPE
Vim: preserving files...
Vim: Finished.
```

Running Vim 8.1.152 on centos 7 compiled with all settings default.

**Comment by holygeek** [comment]
This seems to fix it:

```diff
diff --git src/edit.c src/edit.c
index 0519a015e..88bd73047 100644
--- src/edit.c
+++ src/edit.c
@@ -10201,7 +10201,9 @@ ins_tab(void)
     if (p_sta && ind)		/* insert tab in indent, use 'shiftwidth' */
     {
 	temp = (int)curbuf->b_p_sw;
-	temp -= get_nolist_virtcol() % temp;
+	if (temp > 0) {
+	    temp -= get_nolist_virtcol() % temp;
+	}
     }
     else if (tabstop_count(curbuf->b_p_vsts_array) > 0 || curbuf->b_p_sts != 0)
 	                        /* use 'softtabstop' when set */
```

**Comment by FalacerSelene** [comment]
That does fix the crash, yes. However, it doesn't do what I expect - I should have specifyied in the original bug report.

This fix causes <tab> at the start of a line to instead input 1 space. I would instead expect it to input 'tabstop', as though 'smarttab' were not on, because of the definition in 'shiftwidth':

> 'shiftwidth' 'sw'       number  (default 8)                             
>                         local to buffer                                 
>         Number of spaces to use for each step of (auto)indent.  Used for
>         'cindent', >>, <<, etc.                                         
>         When zero the 'ts' value will be used.  Use the shiftwidth()    
>         function to get the effective shiftwidth value.
