### ISSUE TITLE
Reproducible internal error: E315: ml_get: invalid lnum: 21

### ISSUE THREAD

**Issue by dpelle** [vim/vim#3177]
I can reproduce 100% of the time an internal error
using the latest vim-8.1.0169 and older.
```
E315: ml_get: invalid lnum: 21
```
Steps to reproduce:
1) run:
```
$ cd vim/src  # Important to be in that directory to reproduce issue
$ ./vim --clean -c 'set statusline=x' -c terminal -c 'call feedkeys("ls\<CR>")'
```

2) Then type the following keys (I could not automate this somehow):
```
<c-w>Ni<c-w>n
```
Note that when typing those keys:
* \<c-w\> is a the single key CTRL-w.
* the first N is uppercase and the second n is lowercase.

Observe that vim shows the internal error:
```
E315: ml_get: invalid lnum: 21
```
The line number value (21 in above message) depends on 
the terminal size.

When uncommenting the following lines with ABORT_CFLAGS
in src/Makefile,  Vim aborts at the internal error, so I can see
the stack trace with gdb:
```
(gdb) bt
#0  0x00007efd74422187 in kill () at ../sysdeps/unix/syscall-template.S:78
#1  0x000055dc0ef51464 in may_core_dump () at os_unix.c:3436
#2  0x000055dc0ef51417 in mch_exit (r=1) at os_unix.c:3402
#3  0x000055dc0f04dd27 in getout (exitval=1) at main.c:1535
#4  0x000055dc0ef05706 in preserve_exit () at misc1.c:9860
#5  0x000055dc0ef4efbe in deathtrap (sigarg=6) at os_unix.c:1217
#6  <signal handler called>
#7  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#8  0x00007efd74423801 in __GI_abort () at abort.c:79
#9  0x000055dc0f055457 in iemsgn (s=0x55dc0f06ce70 "E315: ml_get: invalid lnum: %ld", n=32) at message.c:808
#10 0x000055dc0eeebdc0 in ml_get_buf (buf=0x55dc10aff120, lnum=32, will_change=0) at memline.c:2452
#11 0x000055dc0ee22405 in build_stl_str_hl (wp=0x55dc10afcd80, out=0x7ffc4e1e8ee0 "x", ' ' <repeats 149 times>, outlen=4096, fmt=0x55dc10919e70 "x", u
se_sandbox=0, fillchar=32, maxwidth=150, hltab=0x7ffc4e1e84e0, tabtab=0x7ffc4e1e89e0) at buffer.c:3935
#12 0x000055dc0ef9cd75 in win_redr_custom (wp=0x55dc10afcd80, draw_ruler=0) at screen.c:7261
#13 0x000055dc0ef9c76d in redraw_custom_statusline (wp=0x55dc10afcd80) at screen.c:7057
#14 0x000055dc0ef9c20e in win_redr_status (wp=0x55dc10afcd80, ignore_pum=1) at screen.c:6924
#15 0x000055dc0ef8f6f4 in update_screen (type_arg=0) at screen.c:778
#16 0x000055dc0f04d6fb in main_loop (cmdwin=0, noexmode=0) at main.c:1232
#17 0x000055dc0f04d0fe in vim_main2 () at main.c:915
#18 0x000055dc0f04c8a7 in main (argc=8, argv=0x7ffc4e1ea208) at main.c:443
```
```
2434│     char_u  *
2435│ ml_get_buf(
2436│     buf_T       *buf,
2437│     linenr_T    lnum,
2438│     int         will_change)            /* line will be changed */
2439│ {
2440│     bhdr_T      *hp;
2441│     DATA_BL     *dp;
2442│     char_u      *ptr;
2443│     static int  recursive = 0;
2444│
2445│     if (lnum > buf->b_ml.ml_line_count) /* invalid line number */
2446│     {
2447│         if (recursive == 0)
2448│         {
2449│             /* Avoid giving this message for a recursive call, may happen when
2450│              * the GUI redraws part of the text. */
2451│             ++recursive;
2452├>            IEMSGN(_("E315: ml_get: invalid lnum: %ld"), lnum);
2453│             --recursive;
2454│         }
```
When at line memline.c:2452, I see with gdb:
```
(gdb) p lnum
$1 = 21
(gdb) p buf->b_ml.ml_line_count
$2 = 1
(gdb) p recursive
$3 = 1
```
Valgrind or asan do not give anything more useful than the
above stack trace.

**Comment by brammool** [comment]
Dominique wrote:

> I can reproduce 100% of the time an internal error
> using the latest vim-8.1.0169 and older.
> ```
> E315: ml_get: invalid lnum: 21
> ```
> Steps to reproduce:
> 1) run:
> ```
> $ cd vim/src  # Important to be in that directory to reproduce issue
> $ ./vim --clean -c 'set statusline=x' -c terminal -c 'call feedkeys("ls\<CR>")'
> ```
> 
> 2) Then type the following keys (I could not automate this somehow):
> ```
> <c-w>Ni<c-w>n
> ```
> Note that when typing those keys:
> * \<c-w\> is a the single key CTRL-w.
> * the first N is uppercase and the second n is lowercase.
> 
> Observe that vim shows the internal error:
> ```
> E315: ml_get: invalid lnum: 21
> ```
> The line number value (21 in above message) depends on 
> the terminal size.

I can reproduce it.  The problem is that resizing the terminal clears
the snapshot, and the cursor is then beyond the end of the buffer.

I can solve it by restoring the snapshot after resizing.

I did not manage to reproduce the problem in a test.
I'll send a fix, but leave the issue open until we have a test.

-- 
msdn.microsoft.com:
ERROR_SUCCESS 0 (0x0) The operation completed successfully.
I have always suspected that for Microsoft success is an error.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
I wonder, if this causes https://github.com/vim-airline/vim-airline/issues/1726 ...

**Comment by dpelle** [comment]
Bug is fixed in this recent commit:
```
commit 875cf8789426cc258d85358ea2c86744a5a87b16
Author: Bram Moolenaar <Bram@vim.org>
Date:   Sun Jul 8 20:49:07 2018 +0200

    patch 8.1.0171: typing CTRL-W n in a terminal window causes ml_get error
    
    Problem:    Typing CTRL-W n in a terminal window causes ml_get error.
    Solution:   When resizing the terminal outside of terminal_loop() make sure
                the snapshot is complete.
```
However, @brammool  left this issue opened because he could not
automate a test to reproduce it. Bug could only be reproduced 
manually somehow before 8.0.171. This is consistent with what I wrote
in the ticket description when I wrote "type the following keys (I could
not automate this somehow)".  I would not mind if we close this without
a test.

**Comment by chrisbra** [comment]
I think the mentioned patch fixed the airline issue. So let's close this issue now (as no news in the last months I prefer to close old bugs)
