### ISSUE TITLE
'viminfofile' requires double backslashes on Windows

### ISSUE THREAD

**Issue by lkintact** [vim/vim#3178]
Unlike other options expecting filenames as values (`backupdir`, `undodir`, `verbosefile`, `helpfile` etc.) `viminfofile` requires double, not single backslashes. 
For example `set backupdir=c:\test\backups` and `set verbosefile=c:\test\verbose.txt` work as expected (and, I think, consistently with the description at `:help option-backslash`), and `set viminfofile=c:\test\viminfo.txt` sets `viminfofile` to "c:testviminfo.txt".

OS: Windows 7,
Gvim: 8.1.0126 x86

**Comment by brammool** [comment]
> Unlike other options expecting filenames as values (`backupdir`,
> `undodir`, `verbosefile`, `helpfile` etc.) `viminfofile` requires
> double, not single backslashes.  For example `set
> backupdir=c:\test\backups` and `set verbosefile=c:\test\verbose.txt`
> work as expected (and, I think, consistently with the description at
> `:help option-backslash`), and `set viminfofile=c:\test\viminfo.txt`
> results in setting `viminfofile` to "c:testviminfo.txt".

Thanks for reporting this.  The option is missing the P_EXPAND flag.
I'll fix that.

-- 
hundred-and-one symptoms of being an internet addict:
216. Your pet rock leaves home.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
