### ISSUE TITLE
vim crashes cmd and hyper with win 10 insiders preview 

### ISSUE THREAD

**Issue by rogerellisjr** [vim/vim#3179]
Every time I try to run vim with win 10 insiders preview, in hyper or in a regular cmd , it crashes and closes out the program ? 

A work around is to enable legacy console in the command prompt settings. Then vim doesn't crash the command prompt or hyper, but then when I login remote servers, the terminal acts buggy so I have to keep turning this legacy console on and off when working remotely and locally? 

I tried running vim -N -u NONE and it still crashes my command prompt and hyper... 

VIM - Vi IMproved 8.1 (2018 May 18, compiled May 18 2018 18:26:56)
MS-Windows 32-bit console version

OS Name:                   Microsoft Windows 10 Pro Insider Preview
OS Version:                10.0.17692 N/A Build 17692
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Windows User
Registered Organization:
Product ID:                xxxxxxxxxxxxxxxxxxxx
Original Install Date:     7/3/2018, 8:18:39 PM
System Boot Time:          7/8/2018, 5:42:38 PM
System Manufacturer:       System manufacturer
System Model:              System Product Name
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 94 Stepping 3 GenuineIntel ~3401 Mhz
BIOS Version:              American Megatrends Inc. 1803, 5/6/2016

**Comment by chrisbra** [comment]
can you get a stacktrace?

**Comment by rogerellisjr** [comment]
Sure, if this is what you mean in the Event Viewer in win 10: 

These show up in my event log whenever the crash happens

`
Log Name:      Application
Source:        Application Error
Date:          7/13/2018 5:59:31 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-MCSOE7J
Description:
Faulting application name: conhost.exe, version: 10.0.17692.1004, time stamp: 0xdc961e97
Faulting module name: KERNELBASE.dll, version: 10.0.17692.1004, time stamp: 0x5ba2bbda
Exception code: 0xc0000005
Fault offset: 0x00000000000302e0
Faulting process id: 0x4b40
Faulting application start time: 0x01d41af4c54d5d3e
Faulting application path: C:\WINDOWS\system32\conhost.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 630f75d3-fa68-44b0-8117-e4f0a57961a6
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-07-13T21:59:31.990990800Z" />
    <EventRecordID>6367</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-MCSOE7J</Computer>
    <Security />
  </System>
  <EventData>
    <Data>conhost.exe</Data>
    <Data>10.0.17692.1004</Data>
    <Data>dc961e97</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.17692.1004</Data>
    <Data>5ba2bbda</Data>
    <Data>c0000005</Data>
    <Data>00000000000302e0</Data>
    <Data>4b40</Data>
    <Data>01d41af4c54d5d3e</Data>
    <Data>C:\WINDOWS\system32\conhost.exe</Data>
    <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data>630f75d3-fa68-44b0-8117-e4f0a57961a6</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
`



`
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Windows Error Reporting" /> 
  <EventID Qualifiers="0">1001</EventID> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2018-07-13T21:59:33.196995100Z" /> 
  <EventRecordID>6368</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>DESKTOP-MCSOE7J</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>1468500269044694089</Data> 
  <Data>4</Data> 
  <Data>APPCRASH</Data> 
  <Data>Not available</Data> 
  <Data>0</Data> 
  <Data>conhost.exe</Data> 
  <Data>10.0.17692.1004</Data> 
  <Data>dc961e97</Data> 
  <Data>KERNELBASE.dll</Data> 
  <Data>10.0.17692.1004</Data> 
  <Data>5ba2bbda</Data> 
  <Data>c0000005</Data> 
  <Data>00000000000302e0</Data> 
  <Data /> 
  <Data /> 
  <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER17EB.tmp.mdmp \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER185A.tmp.WERInternalMetadata.xml \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER187A.tmp.xml WPR_initiated_DiagTrackMiniLogger_OneTrace User Logger 20180711 Event Collector_0_inject.etl \\?\C:\Users\roger\AppData\Local\Temp\WER18D9.tmp.etl WPR_initiated_DiagTrackMiniLogger_WPR System Collector_inject.etl \\?\C:\Users\roger\AppData\Local\Temp\WER18DA.tmp.etl \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER18E7.tmp.csv \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER18F8.tmp.txt</Data> 
  <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_conhost.exe_bb2921b461a11e3bd89e51ec1e62c77536e9dda9_03a0cdfd_52d71c12</Data> 
  <Data /> 
  <Data>0</Data> 
  <Data>630f75d3-fa68-44b0-8117-e4f0a57961a6</Data> 
  <Data>268435456</Data> 
  <Data>31bf9f488ea7aaef44612936d8f97c49</Data> 
  <Data>0</Data> 
  </EventData>
  </Event>
`

**Comment by rogerellisjr** [comment]
This is inside that file in the WER\ReportArchive 

`Version=1
EventType=APPCRASH
EventTime=131759927720969932
ReportType=2
Consent=1
UploadTime=131759927723980271
ReportStatus=268435456
ReportIdentifier=ebc46257-b3b2-4986-b7bc-92cebe6c646a
IntegratorReportIdentifier=630f75d3-fa68-44b0-8117-e4f0a57961a6
Wow64Host=34404
NsAppName=conhost.exe
OriginalFilename=CONHOST.EXE
AppSessionGuid=00004b40-0001-0007-3e5d-4dc5f41ad401
TargetAppId=W:0000f519feec486de87ed73cb92d3cac802400000000!0000b4bd5dcaceb4fc22028176b40ae2849d6c8c5a5d!conhost.exe
TargetAppVer=2087//04//10:15:09:11!c3b61!conhost.exe
BootId=4294967295
TargetAsId=30231
UserImpactVector=808452912
IsFatal=1
Response.BucketId=31bf9f488ea7aaef44612936d8f97c49
Response.BucketTable=4
Response.LegacyBucketId=1468500269044694089
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=conhost.exe
Sig[1].Name=Application Version
Sig[1].Value=10.0.17692.1004
Sig[2].Name=Application Timestamp
Sig[2].Value=dc961e97
Sig[3].Name=Fault Module Name
Sig[3].Value=KERNELBASE.dll
Sig[4].Name=Fault Module Version
Sig[4].Value=10.0.17692.1004
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=5ba2bbda
Sig[6].Name=Exception Code
Sig[6].Value=c0000005
Sig[7].Name=Exception Offset
Sig[7].Value=00000000000302e0
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.17692.2.0.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=9371
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=937194b9655c7a9f5cc8105f3d38272f
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=37b8
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=37b853dfc9915bfeedf233bab36fe020
UI[2]=C:\WINDOWS\system32\conhost.exe
LoadedModule[0]=C:\WINDOWS\system32\conhost.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\WINDOWS\System32\KERNEL32.DLL
LoadedModule[3]=C:\WINDOWS\System32\KERNELBASE.dll
LoadedModule[4]=C:\WINDOWS\System32\msvcp_win.dll
LoadedModule[5]=C:\WINDOWS\System32\ucrtbase.dll
LoadedModule[6]=C:\WINDOWS\System32\shcore.dll
LoadedModule[7]=C:\WINDOWS\System32\msvcrt.dll
LoadedModule[8]=C:\WINDOWS\System32\RPCRT4.dll
LoadedModule[9]=C:\WINDOWS\System32\combase.dll
LoadedModule[10]=C:\WINDOWS\System32\bcryptPrimitives.dll
LoadedModule[11]=C:\WINDOWS\System32\advapi32.dll
LoadedModule[12]=C:\WINDOWS\System32\sechost.dll
LoadedModule[13]=C:\WINDOWS\System32\user32.dll
LoadedModule[14]=C:\WINDOWS\System32\win32u.dll
LoadedModule[15]=C:\WINDOWS\System32\GDI32.dll
LoadedModule[16]=C:\WINDOWS\System32\gdi32full.dll
LoadedModule[17]=C:\WINDOWS\System32\IMM32.DLL
LoadedModule[18]=C:\WINDOWS\System32\kernel.appcore.dll
LoadedModule[19]=C:\WINDOWS\system32\uxtheme.dll
LoadedModule[20]=C:\WINDOWS\System32\windows.storage.dll
LoadedModule[21]=C:\WINDOWS\System32\profapi.dll
LoadedModule[22]=C:\WINDOWS\System32\powrprof.dll
LoadedModule[23]=C:\WINDOWS\System32\shlwapi.dll
LoadedModule[24]=C:\WINDOWS\System32\ole32.dll
LoadedModule[25]=C:\WINDOWS\System32\OLEAUT32.dll
LoadedModule[26]=C:\WINDOWS\SYSTEM32\PROPSYS.dll
LoadedModule[27]=C:\WINDOWS\System32\clbcatq.dll
LoadedModule[28]=C:\WINDOWS\System32\shell32.dll
LoadedModule[29]=C:\WINDOWS\System32\cfgmgr32.dll
LoadedModule[30]=C:\WINDOWS\System32\cryptsp.dll
LoadedModule[31]=C:\WINDOWS\System32\MSCTF.dll
LoadedModule[32]=C:\WINDOWS\system32\dwmapi.dll
LoadedModule[33]=C:\WINDOWS\System32\CRYPT32.dll
LoadedModule[34]=C:\WINDOWS\System32\MSASN1.dll
LoadedModule[35]=C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.17692.1004_none_db91e2f73dfd56c2\comctl32.DLL
LoadedModule[36]=C:\WINDOWS\System32\TextInputFramework.dll
LoadedModule[37]=C:\WINDOWS\System32\CoreUIComponents.dll
LoadedModule[38]=C:\WINDOWS\System32\CoreMessaging.dll
LoadedModule[39]=C:\WINDOWS\SYSTEM32\ntmarta.dll
LoadedModule[40]=C:\WINDOWS\SYSTEM32\wintypes.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=17692
OsInfo[3].Key=ubr
OsInfo[3].Value=1004
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=1033
OsInfo[7].Key=geoid
OsInfo[7].Value=244
OsInfo[8].Key=sku
OsInfo[8].Value=48
OsInfo[9].Key=domain
OsInfo[9].Value=0
OsInfo[10].Key=prodsuite
OsInfo[10].Value=256
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=1
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=14260
OsInfo[15].Key=osinsty
OsInfo[15].Value=3
OsInfo[16].Key=iever
OsInfo[16].Value=11.1004.17692.0-11.0.47
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=16304
OsInfo[19].Key=svolsz
OsInfo[19].Value=111
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=180625
OsInfo[22].Key=bldtm
OsInfo[22].Value=1624
OsInfo[23].Key=bldbrch
OsInfo[23].Value=rs_prerelease_flt
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.17692.1004.amd64fre.rs_prerelease_flt.180625-1624
OsInfo[30].Key=buildflightid
OsInfo[30].Value=F4698483-30A1-4082-8DEA-D065BBCF55BF.1
OsInfo[31].Key=edition
OsInfo[31].Value=Professional
OsInfo[32].Key=ring
OsInfo[32].Value=WIS
OsInfo[33].Key=expid
OsInfo[33].Value=NG:664CD,FX:20F36D18
OsInfo[34].Key=containerid
OsInfo[35].Key=containertype
OsInfo[36].Key=edu
OsInfo[36].Value=0
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=Console Window Host
AppPath=C:\WINDOWS\system32\conhost.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=25BA642D992E70B8CB16B75A8A4F03CC
MetadataHash=-537803056
`

**Comment by mattn** [comment]
This is not a stacktrace. We expect call stack of function call.

**Comment by k-takata** [comment]
No feedback more than a year. Closing.
