### ISSUE TITLE
Don't permit lambda functions in the sandbox

### ISSUE THREAD

**Issue by w0rp** [vim/vim#3182]
I have been thinking about the sandbox, and it has occurred to me that lambda functions should not be permitted for code running in the sandbox. Consider the following:

1. User installs a plugin which evaluates functions based on global variables.
2. A global variable is set in the sandbox with a lambda function.
3. User triggers that plugin somehow, which in turn executes the lambda function from the setting.

You can't define functions in the sandbox, so this isn't an issue with the `:function` command, but is with lambda functions.

**Comment by brammool** [comment]
I'm not sure if defining a lambda function actually allows for more code to be executed.  But to stay on the safe side: If a function is defined in the sandbox, it must be executed in the sandbox.  If we do that, then we can also allow using :function in the sandbox.

**Comment by w0rp** [comment]
That makes sense to me. I'd be happy with that solution myself.
