### ISSUE TITLE
sh highlighting shows incorrect syntax error

### ISSUE THREAD

**Issue by hnicke** [vim/vim#3185]
Following snippet strips the first and last character param 1:
```bash
#!/bin/bash
var=$1
var=${var:1:$(( ${#var} - 2 ))}
echo $var
```

The second line is not highlighted correctly. Vim highlights the part marked with `|` with a red background (i.e., vim thinks it's an error).
I've executed vim with `vim -N -u NONE`, and only executed `:syntax on`.
```bash
var=${var:1:$(( ${#var} - 2 ))}
-----------------------|||||||-
```

**Comment by chrisbra** [comment]
Please check with current head. https://github.com/vim/vim/commit/d2855f5454c5c6c5f786b228c5b67757edfefcb1 included version 179

**Comment by lacygoill** [comment]
Can confirm that https://github.com/vim/vim/commit/d2855f5454c5c6c5f786b228c5b67757edfefcb1 fixes the issue.
