### ISSUE TITLE
feature request: scroll through soft wrapped lines

### ISSUE THREAD

**Issue by g-i-o-r-g-i-o** [vim/vim#3188]
I've been using vim for years to write prose, books, letters, tex, and to write code.

I've been growing increasingly frustrated by the lack of a nice way to navigate through long lines. And yes, I've remapped j and k to gj and gk, but yet all the other nice ways to scroll and navigate through text remain absolutely unusable (c-e, c-y, mouse wheel scroll, c-d, c-u...). Through the years I've found a very big number of topics on this subject, and many users that have requested this function. Many of them tried hard to get into it but end up getting really frustrated by its scrolling behavior and then give up.

**Can we please add an option that makes vim consider equal the soft wrapped (visual) lines and the hard wrapped lines? This will make my job infinitely more easy and enjoyable too.**

some links:
http://vim.1045645.n5.nabble.com/Scrolling-Long-Lines-Revisited-Again-td5031203.html
2001 "scrolling long lines": http://marc.info/?l=vim&m=100485909423627&w=2
2002 "smooth scroll": http://marc.info/?l=vim&m=102468968303594&w=2
2005 "how to view a long line": http://marc.info/?l=vim&m=111466655128136&w=2
2009 "can vim jump line by screen-line": http://groups.google.com/group/vim_use/browse_thread/thread/85318546ec889513/73ac449d902662e6
2010 "long lines and scrolling": http://groups.google.com/group/vim_use/browse_thread/thread/ed77cb8d39ff1bbf/31d252de859a80d5
http://vim.1045645.n5.nabble.com/Long-lines-and-scrolling-td1183898.html
http://vim.1045645.n5.nabble.com/Scrolling-Long-Lines-Revisited-Again-td5031203.html
https://vi.stackexchange.com/questions/11315/visual-scrolling-visual-c-e-and-c-y-across-wrapped-lines/11383#11383
http://vim.1045645.n5.nabble.com/Scrolling-screen-lines-I-knew-it-s-impossible-td3358342.html
http://vim.1045645.n5.nabble.com/Feature-request-Display-partial-paragraph-at-the-top-of-the-window-td1166809.html
https://github.com/neovim/neovim/issues/7172
https://vi.stackexchange.com/questions/11315/visual-scrolling-visual-c-e-and-c-y-across-wrapped-lines/11383#11383
set display+=lastline

**Comment by chrisbra** [comment]
Yes, smooth scrolling is known to be flawky. It's on my todo list to get a fix, but I haven't gotten far with it yet.

**Comment by g-i-o-r-g-i-o** [comment]
Do you suggest me to post this in the vim newsletter, to get some traction? Which one of the newsletters? 

This would really make vim much more usable for me. Scroling through long lines and not being able to use the standard vim tools or the mouse scroll is simply a nigthmare.

**Comment by chrisbra** [comment]
> Do you suggest me to post this in the vim newsletter, to get some traction? Which one of the newsletters?

Apart from what has been done, I believe there is nothing that can be done, except for getting your feet wet and start coding and implementing this feature. Sorry to say this, but apparently the demand for this feature was never that high or did not bother anybody seriously enough to get this fixed. Even I have been getting used to that quirky behaviour, that it moved down on my personal todo list.

**Comment by brammool** [comment]
The 'smoothscroll' option has been added.  Therefore closing.

The option is not working perfectly.  If you have a combination of options and commands when it does
not work as it should, please create an issue with a step-by-step reproduction case.
