### ISSUE TITLE
Change in paren matching from 8.0.0386 to 8.0.1298?

### ISSUE THREAD

**Issue by tlathm** [vim/vim#3190]
After updating from gvim/vim/vim-core 8.0.0386 to 8.0.1298 there appears to be a significant change in the behavior of the paren match highlighting. It appears that the highlighting no longer works within any quoted strings, for example strings that may be embedded SQL or strings used for regular expressions etc. This works in 8.0.0386. In 8.0.1298 is appears that the matching/highlighting is only working for the files language syntax itself(?).

Is this something known and/or intentional? It's certainly a significant loss of functionality for me. Thanks!

**Comment by dpelle** [comment]
Doing a git bissection should tell where the behavior changed.
But first, we need detailed instructions on how to reproduce this
starting with "vim --clean" to ensure that it's not triggered by 
your .vimrc or one of your plugins.  I could not reproduce it
with vim-8.1.177 so far, but I only spent one minute as I was
not sure I was doing the right steps to reproduce it.

vim-8.0.1298 is a bit old. It would be best to confirm whether this 
happens with the latest Vim from git? (currently vim-8.1.177)

**Comment by tlathm** [comment]
I'll try that test with --clean however first I need to clear up some unspeakable confusion: If I use vim --clean it appears that the paren matching is totally disabled. I've read countless conflicting things as to how to enable that. I'm trying ":let loaded_matchparen = 1", ":set showmatch" and every other imaginable thing I've read and can't get it to even work on things it was working on.

To be honest, without the --clean I have no idea what's enabling it in the first place...certainly nothing in my .vimrc that I'm aware of. Totally lost at this point. What am I missing?

**Comment by vim-ml** [comment]
On Wed, Jul 11, 2018 at 1:31 AM, tlathm <vim-dev-github@256bit.org> wrote:
> I'll try that test with --clean however first I need to clear up some
> unspeakable confusion: If I use vim --clean it appears that the paren
> matching is totally disabled. I've read countless conflicting things as to
> how to enable that. I'm trying ":let loaded_matchparen = 1", ":set
> showmatch" and every other imaginable thing I've read and can't get it to
> even work on things it was working on.
>
> To be honest, without the --clean I have no idea what's enabling it in the
> first place...certainly nothing in my .vimrc that I'm aware of. Totally lost
> at this point. What am I missing?

IIUC, --clean sources only the default.vim script but not your vimrc
and no plugins, not even the standard matchparen.vim plugin.

OTOH, setting loaded_matchparen _disables_ further loading of that
plugin. (It makes the plugin believe that it is already loaded.)

To have the defaults.vim plus paren matching but nothing else, use

    vim --clean -c 'runtime plugin/matchparen.vim'


Best regards,
Tony.

**Comment by tlathm** [comment]
Thanks for the clarification! I was at least able to test this using version 8.1.0034 which was available in Gentoo. Testing on anything newer would take a little digging on my part. In that version I do see the issue I was describing. Here's an example:

Using the command you suggested on a simple example file such as:

vim --clean -c 'runtime plugin/matchparen.vim' test.pl

Where the file contained this:

```
#!/usr/bin/perl
@a = ('aaa', 'bbb');
$sql = "SELECT (SELECT COUNT(*) FROM sometable)";
$reg = '/^(?:abc|def)$';
```

The paren highlighting in the above only works on line two. It doesn't work on either of the lines where the parens are in quoted strings. In 8.0.0386 (and before as far as I know) the highlighting works on every paren in that file. Hope this clarifies it. Thanks again!

**Comment by tonymec** [comment]
Maybe you came up against the following documented behaviour (about 30 lines down from `:help matchparen`):
```
The syntax highlighting attributes are used.  When the cursor currently is not
in a string or comment syntax item, then matches inside string and comment
syntax items are ignored.  Any syntax items with "string" or "comment"
somewhere in their name are considered string or comment items.
```
If brackets inside comments and strings were accepted before to match brackets outside them, then the present behaviour is better: for instance in
```vim
if (string2 == ")" && string1 == "(")
```
the plugin would formerly have matched the outside brackets, not with each other as it should have, but each with the closest quoted bracket, which is nonsense.

Best regards,
Tony.

**Comment by tlathm** [comment]
Correct me if I'm wrong, but that specifically says they're ignored "when the cursor currently is not in a string or comment item". I'm referring to cases where the cursor is inside the quoted string. For example, when the cursor is on the first paren in my '/^(?:abc|def)$' example. It appears that 8.0.0386 properly handles that matching using only the other parens in that string.

In fact, in 8.0.0386 your example actually works perfectly. That is, with the cursor on the first paren, it highlights that very last one, and with the cursor on either of the quoted parens, it highlights nothing at all.

**Comment by tlathm** [comment]
Ahhh...correction: I just realized I wasn't 100% correct on how your example behaves in 8.0.0386:

With the cursor on the first paren it correctly highlights the last one (ignoring the paren in the quoted string). Conversely, with the cursor on the last paren it highlights the first.

However with the cursor on either of the quoted parens it does improperly highlight an unquoted match. So yes...part of that is flawed. However it appears that all highlighting of parens within quoted strings (that is matches within the string itself) have been lost completely in recent versions. This means no highlighting in anything like embedded SQL etc, which is pretty extreme.

**Comment by k-takata** [comment]
It seems that this is caused by the patch 8.0.1239: https://github.com/vim/vim/commit/48570488f17e397183ea7d5c7ca67d6e4ffb013d

Before the patch, `do_searchpair()` called `eval_to_bool()` and it called `eval0()`.
But now `do_searchpair()` calls `eval_expr_to_bool()` and it calls `eval1()` (via `eval_expr_typval()`), and check for trailing chars after expr is added.

It seems that removing the check for trailing chars solves the issue.

```diff
--- a/src/eval.c
+++ b/src/eval.c
@@ -727,11 +727,6 @@ eval_expr_typval(typval_T *expr, typval_
 	s = skipwhite(s);
 	if (eval1(&s, rettv, TRUE) == FAIL)
 	    return FAIL;
-	if (*s != NUL)  /* check for trailing chars after expr */
-	{
-	    EMSG2(_(e_invexpr2), s);
-	    return FAIL;
-	}
     }
     return OK;
 }
```

```diff
--- a/src/eval.c
+++ b/src/eval.c
@@ -724,14 +724,8 @@ eval_expr_typval(typval_T *expr, typval_
 	s = get_tv_string_buf_chk(expr, buf);
 	if (s == NULL)
 	    return FAIL;
-	s = skipwhite(s);
-	if (eval1(&s, rettv, TRUE) == FAIL)
+	if (eval0(s, rettv, NULL, TRUE) == FAIL)
 	    return FAIL;
-	if (*s != NUL)  /* check for trailing chars after expr */
-	{
-	    EMSG2(_(e_invexpr2), s);
-	    return FAIL;
-	}
     }
     return OK;
 }
```

Not sure which patch is better.

**Comment by tlathm** [comment]
Strange. I was able to try applying each of those patches to vim 8.0.1298 and neither one fixed the issue I'm referring to. I even tried the second patch on 8.1.0034 and that didn't work either.

**Comment by brammool** [comment]
Ken Takata wrote:

> It seems that this is caused by the patch 8.0.1239: https://github.com/vim/vim/commit/48570488f17e397183ea7d5c7ca67d6e4ffb013d
> 
> Before the patch, `do_searchpair()` called `eval_to_bool()` and it called `eval0()`.
> But now `do_searchpair()` calls `eval_expr_to_bool()` and it calls `eval1()` (via `eval_expr_typval()`), and check for trailing chars after expr is added.
> 
> It seems that removing the check for trailing chars solves the issue.
> 
> ```diff
> --- a/src/eval.c
> +++ b/src/eval.c
> @@ -727,11 +727,6 @@ eval_expr_typval(typval_T *expr, typval_
>  	s = skipwhite(s);
>  	if (eval1(&s, rettv, TRUE) == FAIL)
>  	    return FAIL;
> -	if (*s != NUL)  /* check for trailing chars after expr */
> -	{
> -	    EMSG2(_(e_invexpr2), s);
> -	    return FAIL;
> -	}
>      }
>      return OK;
>  }
> ```
> 
> ```diff
> --- a/src/eval.c
> +++ b/src/eval.c
> @@ -724,14 +724,8 @@ eval_expr_typval(typval_T *expr, typval_
>  	s = get_tv_string_buf_chk(expr, buf);
>  	if (s == NULL)
>  	    return FAIL;
> -	s = skipwhite(s);
> -	if (eval1(&s, rettv, TRUE) == FAIL)
> +	if (eval0(s, rettv, NULL, TRUE) == FAIL)
>  	    return FAIL;
> -	if (*s != NUL)  /* check for trailing chars after expr */
> -	{
> -	    EMSG2(_(e_invexpr2), s);
> -	    return FAIL;
> -	}
>      }
>      return OK;
>  }
> ```
> 
> Not sure which patch is better.

I think neither should be used.  The check for trailing characters is
there for a good reason, it detects an invalid expression.

I did spot a memory leak, I'll fix that.

So what is the searchpair() call that reproduces the problem?

-- 
Eagles may soar, but weasels don't get sucked into jet engines.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
I can confirm that the patch [8.1.0181](https://github.com/vim/vim/commit/a43ebe9454386427ca38c75810e2d36991f17812) solves the problem in my environment.
I haven't actually checked which `searchpair()` call causes the problem though.

**Comment by chrisbra** [comment]
I tried 8.1.181 and the [given example](https://github.com/vim/vim/issues/3190#issuecomment-404159115) and it works perfectly. Make sure to get at least the latest version from matchparen from patch [8.1.115](https://github.com/vim/vim/releases/tag/v8.1.0115) and [8.1.143](https://github.com/vim/vim/releases/tag/v8.1.0143)

**Comment by tlathm** [comment]
Yes! You're correct. While 8.1.0034 still had the issue, I just added an 8.1.0181 ebuild to my local overlay in Gentoo and that does correct the issue.

**Comment by brammool** [comment]
> I can confirm that the patch 8.1.0181 solves the problem in my environment.
> I haven't actually checked which `searchpair()` call causes the
> problem though.

It can't be patch 181, that only fixes a memory leak.  Must be an
earlier patch that matters for this.

-- 
hundred-and-one symptoms of being an internet addict:
244. You use more than 20 passwords.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by tlathm** [comment]
If anyone's interested, I was able to determine that this seems to have been fixed in 115. Actually, in 114 as soon as your cursor highlighted a paren in a quoted string, it threw an error.
