### ISSUE TITLE
Add info on translation to contributing file

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3191]
I would like a "Translation" section added to https://github.com/vim/vim/blob/master/CONTRIBUTING.md

A place where translators can read how to translate Vim, where the files is, how to start a new language, how to update existing language, how to submit, etc.

I would also like a contributing page added on https://www.vim.org/ with a translation section so people can find it there.

Did i miss anything that can be translated?

I made this so far. We can improve it.
I used "da" as example.

    Translation:

        Vim:

            Vim itself

                Hopefully we can have this file:

                    src/po/vim.pot

                Duplicate the file and rename to da.po:

                    src/po/da.po

        gVim:

            Menu, dialogs

                Hopefully we can have this file:

                    runtime/lang/menu.vim

                Duplicate the file and add "_da.latin1" and "_da.utf-8":

                    runtime/lang/menu_da.latin1.vim
                    runtime/lang/menu_da.utf-8.vim

        Desktop entry:

            Launcher to start vim/gVim

            Hopefully these strings will be added to the pot/po files

                runtime/vim.desktop
                runtime/gvim.desktop

        Vim tutor:

            Run "Vim tutor" launcher to view the tutorial

                runtime/tutor/tutor

                Duplicate the file and add ".da" and ".da.utf-8":

                runtime/tutor/tutor.da
                runtime/tutor/tutor.da.utf-8

        Man files:

            For "man vim", "man evim", etc.

            Source:

                runtime/doc/vim.1
                runtime/doc/evim.1
                runtime/doc/vimdiff.1
                runtime/doc/vimtutor.1
                runtime/doc/xxd.1

            Duplicate the files and add "-da" and "-da.UTF-8":

                runtime/doc/vim-da.1
                runtime/doc/vim-da.UTF-8.1
                runtime/doc/evim-da.1
                runtime/doc/evim-da.UTF-8.1
                runtime/doc/vimdiff-da.1
                runtime/doc/vimdiff-da.UTF-8.1
                runtime/doc/vimtutor-da.1
                runtime/doc/vimtutor-da.UTF-8.1
                runtime/doc/xxd-da.1
                runtime/doc/xxd-da.UTF-8.1

        Doc files:

            The doc files are not included in Vim, they have to be downloaded seperately

            The translations can be found at https://www.vim.org/translations.php

                runtime/doc/*.txt

            Duplicate the files and change ".txt" to ".dax" if translating to "da" language:

                runtime/doc/*.dax

            Maybe a tags file should be created running "helptags $VIMRUNTIME /doc":

                runtime/doc/tags-da

        Windows installer:

            The Windows installer does not seem to translatable.

        Other files to read:

            src/po/README.txt

**Comment by k-takata** [comment]
> Vim itself

I think `src/po/README.txt` should be linked.

> Launcher to start vim/gVm

Typo: "gVm" -> "gVim"

> Run "Vim tutor" launcher or type ":e $VIMRUNTIME/tutor/tutor" to view the tutorial

":e $VIMRUNTIME/tutor/tutor" is not recommended.

> Duplicate the files and change ".txt" to ".dat" if translating to "da" language:

It should be ".dax" instead of ".dat".

**Comment by scootergrisen** [comment]
Why is ":e $VIMRUNTIME/tutor/tutor" not recomended?

**Comment by k-takata** [comment]
See the answer from Bram: https://github.com/vim/vim/issues/3111#issuecomment-401024515

**Comment by k-takata** [comment]
> ```
>             Hopefully we can have this file:
> 
>                 runtime/lang/menu.vim
> 
>             Duplicate the file and add "_da.latin1" and "_da.utf-8":
> ```

We only have `runtime/menu.vim` (not `runtime/lang/menu.vim`), and copying it to `runtime/lang/menu_[ll].[encoding].vim` (and translate it) won't work as expected.
As discussed in #3035, using another translation as a template might be a good way for now.

**Comment by scootergrisen** [comment]
I'm talking about making it better in the future so i write "hopefully we can have..." in the future.
The way its done now it not good.

**Comment by scootergrisen** [comment]
If we could use po files for translating the gVim menus that would improve the translation progress alot.
The part where you have to esacpe each space is not good for translators.

**Comment by chrisbra** [comment]
> If we could use po files for translating the gVim menus that would improve the translation progress alot.

That is not possible, as far as I know, since gettext doesn't understand the vim files.

**Comment by brammool** [comment]
> I would like a "Translation" section added to https://github.com/vim/vim/blob/master/CONTRIBUTING.md
> 
> A place where translators can read how to translate Vim, where the files is, how to start a new language, how to update existing language, how to submit, etc.
> 
> I would also like a contributing page added on https://www.vim.org/ with a translation section so people can find it there.
> 
> Did i miss anything that can be translated?
> 
> I made this so far. We can improve it.
> I used "da" as example.
> 
>     Translation:
> 
>         Vim:
> 
>             Vim itself
> 
>                 Hopefully we can have this file:
> 
>                     src/po/vim.pot
> 
>                 Duplicate the file and rename to da.po:
> 
>                     src/po/da.po
> 
>         gVim:
> 
>             Menu, dialogs
> 
>                 Hopefully we can have this file:
> 
>                     runtime/lang/menu.vim
> 
>                 Duplicate the file and add "_da.latin1" and "_da.utf-8":
> 
>                     runtime/lang/menu_da.latin1.vim
>                     runtime/lang/menu_da.utf-8.vim
> 
>         Desktop entry:
> 
>             Launcher to start vim/gVm
> 
>             Hopefully these strings will be added to the pot/po files
> 
>                 runtime/vim.desktop
>                 runtime/gvim.desktop
> 
>         Vim tutor:
> 
>             Run "Vim tutor" launcher or type ":e $VIMRUNTIME/tutor/tutor" to view the tutorial
> 
>                 runtime/tutor/tutor
> 
>                 Duplicate the file and add ".da" and ".da.utf-8":
> 
>                 runtime/tutor/tutor.da
>                 runtime/tutor/tutor.da.utf-8
> 
>         Man files:
> 
>             For "man vim", "man evim", etc.
> 
>             Source:
> 
>                 runtime/doc/vim.1
>                 runtime/doc/evim.1
>                 runtime/doc/vimdiff.1
>                 runtime/doc/vimtutor.1
>                 runtime/doc/xxd.1
> 
>             Duplicate the files and add "-da" and "-da.UTF-8":
> 
>                 runtime/doc/vim-da.1
>                 runtime/doc/vim-da.UTF-8.1
>                 runtime/doc/evim-da.1
>                 runtime/doc/evim-da.UTF-8.1
>                 runtime/doc/vimdiff-da.1
>                 runtime/doc/vimdiff-da.UTF-8.1
>                 runtime/doc/vimtutor-da.1
>                 runtime/doc/vimtutor-da.UTF-8.1
>                 runtime/doc/xxd-da.1
>                 runtime/doc/xxd-da.UTF-8.1
> 
>         Doc files:
> 
>             The doc files are not included in Vim, they have to be downloaded seperately
> 
>             The translations can be found at https://www.vim.org/translations.php
> 
>                 runtime/doc/*.txt
> 
>             Duplicate the files and change ".txt" to ".dat" if translating to "da" language:
> 
>                 runtime/doc/*.dat
> 
>             Maybe a tags file should be created running "helptags $VIMRUNTIME /doc":
> 
>                 runtime/doc/tags-da
> 
>         Windows installer:
> 
>             The Windows installer does not seem to translatable.
 

I like to keep CONTRIBUTING.md short and have it point to files that
give a comprehensive explanation.  How about this for a start:


# Translations

Translating messages and runtime files is very much appreciated!  These things can be translated:
*   Messages in Vim, see src/po/README.txt
*   Menus, see runtime/lang/README.txt
*   Vim tutor, see runtime/tutor/README.txt
*   Manual pages, see runtime/doc/*.1 for examples
*   Desktop icon, see runtime/vim.desktop and runtime/gvim.desktop

The help files can be translated and made available separately.
See https://www.vim.org/translations.php for examples.

-- 
hundred-and-one symptoms of being an internet addict:
242. You turn down a better-paying job because it doesn't come with
     a free e-mail account.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
> > If we could use po files for translating the gVim menus that would
> > improve the translation progress alot.
> 
> That is not possible, as far as I know, since gettext doesn't
> understand the vim files.

Would it be difficult to use a Vim script to extract the messages from
menu.vim and append them to the .pot file?

-- 
Married is a three ring circus:
First comes the engagement ring.
Then comes the wedding ring.
Then comes the suffering.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
> * Vim tutor, see runtime/tutor/README.txt

`runtime/tutor/README.txt` doesn't actually explain how to translate the tutor.
We need to update it.

**Comment by scootergrisen** [comment]
I think its better to keep the instructions on how to translate in one place instead of spreading the information across multiple files making it harder for translators to find.

**Comment by k-takata** [comment]
(off topic)
I found that `runtime/tutor/tutor.utf-8` was not updated. I think should be a copy of `runtime/tutor/tutor`.

**Comment by scootergrisen** [comment]
Its confusing with the naming tutor and tutor.utf-8 when seens in a long list of files because they does not come after each other.

**Comment by k-takata** [comment]
> I think should be a copy of runtime/tutor/tutor.

Mistake. It should be updated by running the `make` command.
It seems that ca.utf-8, es.utf-8, fr.utf-8 and zh.utf-8 have differences between their non-utf-8 version.
Not sure which are actually newer.

**Comment by brammool** [comment]
> (off topic)
> I found that `runtime/tutor/tutor.utf-8` was not updated. I think
> should be a copy of `runtime/tutor/tutor`.

I'll fix that and add it to my check script.


-- 
Marriage isn't a word.  It's a sentence.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
closing as of https://github.com/vim/vim/commit/b477af2260d9bc7ae7f743f0a14265d7ee12ee09

**Comment by scootergrisen** [comment]
Why close the issues when the instructions are like this:

    Translating messages and runtime files is very much appreciated! These things can be translated:

        Messages in Vim, see src/po/README.txt
        Menus, see runtime/lang/README.txt
        Vim tutor, see runtime/tutor/README.txt
        Manual pages, see runtime/doc/*.1 for examples
        Desktop icon, see runtime/vim.desktop and runtime/gvim.desktop

    The help files can be translated and made available separately. See https://www.vim.org/translations.php for examples.

The text just tells the translator to go elsewhere and there is not even links.

    Vim tutor, see runtime/tutor/README.txt

Why would a translator want to see that?

    Manual pages, see runtime/doc/*.1 for examples

I dont want examples i want instructions.
Not very good to just tell translators to go find some files that ends with .1 and figure it out.

    See https://www.vim.org/translations.php for examples

Again with the redirection and examples.

**Comment by brammool** [comment]
> Why close the issues when the instructions are like this:
> 
>     Translating messages and runtime files is very much appreciated! These things can be translated:
> 
>         Messages in Vim, see src/po/README.txt
>         Menus, see runtime/lang/README.txt
>         Vim tutor, see runtime/tutor/README.txt
>         Manual pages, see runtime/doc/*.1 for examples
>         Desktop icon, see runtime/vim.desktop and runtime/gvim.desktop
> 
>     The help files can be translated and made available separately. See https://www.vim.org/translations.php for examples.
> 
> The text just tells the translator to go elsewhere and there is not even links.

Yes, it's better to keep detailed instructions where the work needs to
be done.  File names are links.  They even work without an internet
connection.

>     Vim tutor, see runtime/tutor/README.txt
> 
> Why would a translator want to see that?
> 
>     Manual pages, see runtime/doc/*.1 for examples
> 
> I dont want examples i want instructions.
> Not very good to just tell translators to go find some files that ends with .1 and figure it out.
> 
>     See https://www.vim.org/translations.php for examples
> 
> Again with the redirection and examples.

well, feel free to write some of those instructions.

-- 
hundred-and-one symptoms of being an internet addict:
261. You find diskettes in your pockets when doing laundry.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by scootergrisen** [comment]
> File names are links.

Only link i see on https://github.com/vim/vim/blob/b477af2260d9bc7ae7f743f0a14265d7ee12ee09/CONTRIBUTING.md#translations is the one for https://www.vim.org/translations.php

> well, feel free to write some of those instructions.

Its in the first comment of this issue.

**Comment by chrisbra** [comment]
> Only link i see on https://github.com/vim/vim/blob/b477af2260d9bc7ae7f743f0a14265d7ee12ee09/CONTRIBUTING.md#translations is the one for https://www.vim.org/translations.php

If you open the file in Vim, try `gf` :) I realize you might want to see nice blue underlined links when viewing the files in a browser, but note, that once you checkout the repository, you might as well just open the file with your favorite text editor and then you can simply use `gf` to jump to different files (providing the `pwd` is correct).

@brammool 
Please include the following patch:
https://github.com/chrisbra/vim/commit/c8c50832d7a4a388aff6fb7c00336ac619cec2a2

> Its in the first comment of this issue.

I personally do not think the information given in your first comment is very good. Instead of giving short, imprecise steps, I think it is better to link to the existing documentation, after all, that's what is has been written for ;)

**Comment by scootergrisen** [comment]
I dont think it should be necessary to have the software (Vim) to read the instructions in a good way with links.
Better to have a contribution/translation page on vim.org that can always be up to date instead of including the instructions in Vim where it gets old quickly and then translators are given different instructions depending on what version of Vim they are using.

> I personally do not think the information given in your first comment is very good. Instead of giving short, imprecise steps, I think it is better to link to the existing documentation, after all, that's what is has been written for ;)

How would reading these files help you translate Vim to a new language?
runtime/tutor/README.txt
runtime/lang/README.txt

**Comment by chrisbra** [comment]
> Better to have a contribution/translation page on vim.org that can always be up to date instead of including the instructions in Vim where it gets old quickly and then translators are given different instructions depending on what version of Vim they are using.

Experience shows, that the documentation inside the vim source repository is more often updated than a webpage wherever it resides. Besides, it makes sense to have it together with the source, so that it will always be in sync with the latest Vim features.

> How would reading these files help you translate Vim to a new language?
runtime/tutor/README.txt
runtime/lang/README.txt

Well, for the first, I would say, go ahead and create a new file, similar to the other ones.

`runtime/lang/README.txt` contains links to the relevant vim help files. What exactly are you missing there?

**Comment by scootergrisen** [comment]
> I would say, go ahead and create a new file, similar to the other ones.

Where does it say that?

> runtime/lang/README.txt contains links to the relevant vim help files. What exactly are you missing there?

I dont see any links.
Where does it say how to start a new translation?

**Comment by chrisbra** [comment]
> Where does it say that?

Common sense when looking at the content :)

> I dont see any links.

So what is this?

> More information in the on-line help:
> 
> 	:help multilang-menus
> 	:help :menutrans
> 	:help 'langmenu'
>     :help :language
