### ISSUE TITLE
Can't find pkg-config during configure 

### ISSUE THREAD

**Issue by Char-Aznable** [vim/vim#3192]
Hi, I'm trying to compile vim 8.1.0150 from source with `./configure --enable-gui=gtk2 && make && make install` but I can't find the gvim binary. It turns out the problem is pkg-config is not found during configure:

```
...
checking for IceConnectionNumber in -lICE... yes
checking if X11 header files can be found... yes
checking for _XdmcpAuthDoIt in -lXdmcp... yes
checking for IceOpenConnection in -lICE... yes
checking for XpmCreatePixmapFromData in -lXpm... yes
checking if X11 header files implicitly declare return values... no
checking size of wchar_t is 2 bytes... no
checking --enable-gui argument... GTK+ 3.x GUI support
checking --disable-gtktest argument... gtk test enabled
checking for pkg-config... /home/linuxbrew/.linuxbrew/bin/pkg-config
no
checking X11/SM/SMlib.h usability... yes
...
```
src/auto/config.log says:

```
...
configure:9008: checking --enable-gui argument
configure:9086: result: GTK+ 3.x GUI support
configure:9617: checking --disable-gtktest argument
configure:9627: result: gtk test enabled
configure:9681: checking for pkg-config
configure:9699: found /home/linuxbrew/.linuxbrew/bin/pkg-config
configure:9711: result: /home/linuxbrew/.linuxbrew/bin/pkg-config
configure:9850: result: no
configure:10495: checking X11/SM/SMlib.h usability
...
```
Which is very weird. I'm on CentOS 6.9 and pkg-config version is 0.29.2 and which pkg-config returns `/home/linuxbrew/.linuxbrew/bin/pkg-config`. I can confirm that pkg-config is working by `pkg-config --modversion gtk+-2.0` which returns 2.24.32. Any clue about what's going on here?

**Comment by k-takata** [comment]
Somehow a comment from vim_dev is not forwarded here:
https://groups.google.com/d/msg/vim_dev/f-MXc3zvhLQ/BADaG_2LDAAJ

Quoting:
> The problem isn't with pkg-config. but with GTK.
>
> You check pkg-config with gtk+-2.0, but configure thinks you want GTK 3; if you really want GTK2 adjust the CONF_OPT_GUI line in the Makefile.  

See the link for detail.

**Comment by Char-Aznable** [comment]
Thanks for the hint. Actually the command that helps is 
```
pkg-config --exists --print-errors gtk+-2.0 
```
which not only tells if GTK2 exists, which it does in this case, but also tells if there's dependency issue here. In my case, the libuuid from util-linux was not properly installed, which failed `pkg-config --exists`. After installing libuuid, everything works.

I would recommend using `pkg-config --exists --print-errors PKG` to check for package in the configure script to provide diagnostics.

**Comment by aalvarado** [comment]
Sorry to necro post but this is an issue with Linuxbrew getting in the way. You can fix it by:

`brew unlink pkg-config`
