### ISSUE TITLE
setl scrolloff={value} works globally

### ISSUE THREAD

**Issue by I60R** [vim/vim#3195]
Instead it should work only for current buffer.

I'm not the only who [surprised by this behavior](https://www.reddit.com/r/vim/comments/39a9qx/setlocal_scrolloff_is_not_local_is_it_normal/)

**Comment by idbrii** [comment]
The option is global (only), so setlocal has no effect. 

This is true for any option marked as global in help.

This is not a defect. However, maybe you intended this as a feature request to make it global-local?

**Comment by I60R** [comment]
Yes, this is a feature request. I need this option to be a global-local

**Comment by lacygoill** [comment]
Fixed by https://github.com/vim/vim/commit/375e3390078e740d3c83b0c118c50d9a920036c7.
