### ISSUE TITLE
XML indentation after comment line is reset if syntax on/enable

### ISSUE THREAD

**Issue by e-kwsm** [vim/vim#3200]
<details>
<summary>vim --version: 8.1.178</summary>
<pre><code>VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 12 2018 23:51:06)
Included patches: 1-178
Compiled by kwsm@host
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
+balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
+browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          +toolbar
+cindent           +insert_expand     +path_extra        +user_commands
+clientserver      +job               -perl              +vartabs
+clipboard         +jumplist          +persistent_undo   +vertsplit
+cmdline_compl     +keymap            +postscript        +virtualedit
+cmdline_hist      +lambda            +printer           +visual
+cmdline_info      +langmap           +profile           +visualextra
+comments          +libcall           -python            +viminfo
+conceal           +linebreak         -python3           +vreplace
+cryptv            +lispindent        +quickfix          +wildignore
+cscope            +listcmds          +reltime           +wildmenu
+cursorbind        +localmap          +rightleft         +windows
+cursorshape       -lua               -ruby              +writebackup
+dialog_con_gui    +menu              +scrollbind        +X11
+diff              +mksession         +signs             -xfontset
+digraphs          +modify_fname      +smartindent       +xim
+dnd               +mouse             +startuptime       +xpm
-ebcdic            +mouseshape        +statusline        +xsmp_interact
+emacs_tags        +mouse_dec         -sun_workshop      +xterm_clipboard
+eval              -mouse_gpm         +syntax            -xterm_save
+ex_extra          -mouse_jsbterm     +tag_binary
+extra_search      +mouse_netterm     +tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/home/kawasima/usr/local/vim/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lgdk_pixbuf-2.0 -lpangocairo-1.0 -lcairo -lpango-1.0 -lfreetype -lfontconfig -lgobject-2.0 -lgmodule-2.0 -lglib-2.0   -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lelf -lnsl  -lselinux -lacl -lattr -ldl
</code></pre>
</details>

# How to Reproduce
```shellsession
vim -N -u NONE -c'setf xml' -c'ru indent/xml.vim' -c'syntax enable' -c'exe "normal! =G"' - << EOF
<?xml version="1.0" encoding="utf-8"?>
<tag0>
<tag1>
<!-- comment -->
<tag2>
<tag3/>
</tag2>
</tag1>
</tag0>
EOF
```

which gives

```xml
<?xml version="1.0" encoding="utf-8"?>
<tag0>
        <tag1>
<!-- comment -->
<tag2>
        <tag3/>
</tag2>
</tag1>
</tag0>
```

If `:syntax off` and `=G` again, the content is indented as expected:
```xml
<?xml version="1.0" encoding="utf-8"?>
<tag0>
        <tag1>
                <!-- comment -->
                <tag2>
                        <tag3/>
                </tag2>
        </tag1>
</tag0>
```

On the other hand, vim can indent correctly if comment and tag are in same line, e.g.,
```xml
<?xml version="1.0" encoding="utf-8"?>
<tag0>
<tag1>
<tag2> <!-- comment -->
<tag3/>
</tag2>
</tag1>
</tag0>
```

**Comment by chrisbra** [comment]
Please make sure to have a line of `:filetype plugin indent on` in your .vimrc to have the xml indenting runtime file sourced. That should make indentation work properly.

**Comment by e-kwsm** [comment]
Minimal vimrc is
```vim
syntax on
filetype plugin indent on
```
which doesn't work as expected.

I'm not sure why, but indentation doesn't work if a comment has 0 leading and 0 or 1 trailing characters:
```xml
<?xml version="1.0" encoding="utf-8"?>
<tag0>
                <tag1>
 <!-- no trailing character but a leading character, will be indented -->
                </tag1>
                <tag1>
<!-- no leading character but trailing characters, will be indented -->12
                </tag1>
                <tag1>
<!-- no leading character and a single trailing character, indention will have NO effect -->1
                </tag1>
                <tag1>
<!-- no leading nor trailing character, indention will have NO effect -->
                </tag1>
</tag0>
```

**Comment by chrisbra** [comment]
Hm, I see what is happening:

https://github.com/vim/vim/blob/master/runtime/indent/xml.vim#L59-L60

When there are neither trailing- nor leading characters, an xmlComment syntax will be correctly detected. That means, it will be handled internally by vim (returning -1) which according to `:h 'indentexpr'` means, to keep the indent as is, do not change it. If you manually change the `-1` to `1`, it will re-indent as you expect.

So the question is, should comments be re-indented or not? I am not sure. I think this should be discussed with the indent script maintainer, but I think he is inactive. As an alternative you might want to try if using `gq` works better for you.

**Comment by e-kwsm** [comment]
vim indents comments of HTML (and XHTML) as expected, so I think this behaviour should be fixed, namely be consistent with (X)HTML.

**Comment by chrisbra** [comment]
as you seem to be using xml indenting. You might try the change and check, whether that works for you well enough. Once you are satisfied, you can propose the change here and we might include it. I might become new maintainer, as I already maintain the xml ftplugin. But please test the change a while.

**Comment by e-kwsm** [comment]
#3248
