### ISSUE TITLE
langremap mapping issue

### ISSUE THREAD

**Issue by nikolapintaric** [vim/vim#3201]
Using 
```
set lnr nocompatible
set langmap=yneo;hjkl,YNEO;HJKL,hjkl;yneo,HJKL;YNEO

nmap J 5<down>
nmap K 5<up>
vmap J 5<down>
vmap K 5<up>
```
Now <S-J> jumps 5 lines but pressing it again joins 2 lines.
<S-k> opens manual on the second keypress.

If any other key is pressed before the second <S-J> it will jump 5 lines

**Comment by chrisbra** [comment]
duplicate of #3018
