### ISSUE TITLE
location list: get corresponding / parent window id

### ISSUE THREAD

**Issue by blueyed** [vim/vim#3202]
There is "winid" in `getloclist(0, {'all': 1})` already, but this corresponds to the location list window itself.

I would like to get the id of the window that the location list window is for.

For quickfix lists this would return 0 then.

**Comment by vim-ml** [comment]
Hi Daniel,

On Thu, Jul 12, 2018 at 1:36 PM, Daniel Hahler
<vim-dev-github@256bit.org> wrote:
> There is "winid" in getloclist(0, {'all': 1}) already, but this corresponds
> to the location list window itself.
>
> I would like to get the id of the window that the location list window is
> for.
>
> For quickfix lists this would return 0 then.
>

Can you try the attached patch? With this patch, when getloclist() is called
from the location list window, the 'winid' is set to the identifier of
the window
containing the location list.

Thanks,
Yegappan

**Comment by blueyed** [comment]
Thank you!

> With this patch, when getloclist() is called from the location list window,
> the 'winid' is set to the identifier of the window containing the location
> list.

Isn't that too magical, and also not backwards compatible?

I think `getloclist(0, {'what': 1})` should return the same regardless from if
you are in the window or its location list window.

Therefore a new entry should be added, e.g. `parent_winid`.

**Comment by vim-ml** [comment]
Hi,

On Thu, Jul 12, 2018 at 2:57 PM, Daniel Hahler
<vim-dev-github@256bit.org> wrote:
> Thank you!
>
> With this patch, when getloclist() is called from the location list window,
> the 'winid' is set to the identifier of the window containing the location
> list.
>
> Isn't that too magical, and also not backwards compatible?
>

Yes. I was trying to reduce the number of different window identifiers
returned by the function. But this will break backward compatibility.

>
> I think getloclist(0, {'what': 1}) should return the same regardless from if
> you are in the window or its location list window.
>
> Therefore a new entry should be added, e.g. parent_winid.
>

The window with the location list is not really a parent of the
location list window.
So what about calling the new item as "loclistwinid" or "llwinid" instead
of "parent_winid"? This will be only returned by the getloclist() function.

Regards,
Yegappan

**Comment by ychin** [comment]
If you want backwards compatibility without a custom patch you can always loop through all windows in your Vim script to see which one is pointing to the location list you want by checking `getloclist(0, {'all': 1})['winid'] == win_getid()`. It sounds inefficient but it's actually what Vim does under the hood anyway… (look at `qf_find_win_with_loclist()` in `quickfix.c`)

**Comment by vim-ml** [comment]
Hi,

On Thu, Jul 12, 2018 at 10:53 PM Yegappan Lakshmanan
<yegappanl@gmail.com> wrote:
>
> Hi,
>
> On Thu, Jul 12, 2018 at 2:57 PM, Daniel Hahler
> <vim-dev-github@256bit.org> wrote:
> > Thank you!
> >
> > With this patch, when getloclist() is called from the location list window,
> > the 'winid' is set to the identifier of the window containing the location
> > list.
> >
> > Isn't that too magical, and also not backwards compatible?
> >
>
> Yes. I was trying to reduce the number of different window identifiers
> returned by the function. But this will break backward compatibility.
>
> >
> > I think getloclist(0, {'what': 1}) should return the same regardless from if
> > you are in the window or its location list window.
> >
> > Therefore a new entry should be added, e.g. parent_winid.
> >
>
> The window with the location list is not really a parent of the
> location list window.
> So what about calling the new item as "loclistwinid" or "llwinid" instead
> of "parent_winid"? This will be only returned by the getloclist() function.
>

I am attaching an updated patch that adds 'filewinid' field to the list returned
by the getloclist() function. This patch also includes a test and update
to the documentation.

- Yegappan
