### ISSUE TITLE
Add function to get windows around the current one

### ISSUE THREAD

**Issue by blueyed** [vim/vim#3203]
Mainly due to https://github.com/vim/vim/issues/1839 it is not possible anymore to use `wincmd k` etc in a FileType autocommand to get this information.

I think it would be useful to have a function for this, e.g. `getwindowindirection(direction)` that could be used and would return a winid.

**Comment by andymass** [comment]
Yegappan has posted two patches wininfo.diff and winlayout.diff on vim_dev and they are in the todo list.  I too think they would be a useful addition.

In the meanwhile, could you emulate it using `win_screenpos()`?  You should be able to add a bounds check based on the cursor position.  See also https://vi.stackexchange.com/questions/16248/detect-if-window-has-neighbour-in-given-direction

**Comment by blueyed** [comment]
Thanks!

From the linked solution:

> It will not tell you which window is to the immediate right

That's a problem: I need to get to the window.

In https://github.com/vim/vim/issues/1839#issuecomment-348301996 I've mentioned to have tried `screenrow` and `winline` already, which appear to be similar.

Having the patches from Yegappan would be good after all - without having looked at them yet.

**Comment by vim-ml** [comment]
Hi,

On Fri, Jul 13, 2018 at 2:57 PM, Daniel Hahler
<vim-dev-github@256bit.org> wrote:
> Thanks!
>
> From the linked solution:
>
> It will not tell you which window is to the immediate right
>
> That's a problem: I need to get to the window.
>
> In #1839 (comment) I've mentioned to have tried screenrow and winline
> already, which appear to be similar.
>
> Having the patches from Yegappan would be good after all - without having
> looked at them yet.
>

The pull request https://github.com/vim/vim/pull/2521 adds a 'neighbors'
field to the dictionary returned by the getwininfo() function. This list field
contains the identifiers of the neighboring windows of the given window.
If more than one window is present in a given direction, then the identifier
of the first window is returned.

- Yegappan

**Comment by blueyed** [comment]
Awesome, exactly what I would need.
Thanks!
Closing in favor of https://github.com/vim/vim/pull/2521 then.

**Comment by brammool** [comment]
> On Fri, Jul 13, 2018 at 2:57 PM, Daniel Hahler
> <vim-dev-github@256bit.org> wrote:
> > Thanks!
> >
> > From the linked solution:
> >
> > It will not tell you which window is to the immediate right
> >
> > That's a problem: I need to get to the window.
> >
> > In #1839 (comment) I've mentioned to have tried screenrow and winline
> > already, which appear to be similar.
> >
> > Having the patches from Yegappan would be good after all - without having
> > looked at them yet.
> >
> 
> The pull request https://github.com/vim/vim/pull/2521 adds a 'neighbors'
> field to the dictionary returned by the getwininfo() function. This list field
> contains the identifiers of the neighboring windows of the given window.
> If more than one window is present in a given direction, then the identifier
> of the first window is returned.

I think this is hardly useful.  Especially if a window has several
neighbors on one side, just arbitrarily returning the first one is just
guessing what the caller wanted.

Having a function that returns the list of all windows, with their
positions and sizes, allows the caller to do whatever he wants.
Adding "wincol" and "winrow" to getwininfo() is probably sufficient.

-- 
hundred-and-one symptoms of being an internet addict:
243. You unsuccessfully try to download a pizza from www.dominos.com.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
https://github.com/vim/vim/releases/tag/v8.1.0185 included that patch I think.

**Comment by blueyed** [comment]
Thanks, it's https://github.com/vim/vim/releases/tag/v8.1.0184.
I will see what I can do with that - appears to be similar to nvim's API that I've tried to use already.

**Comment by andymass** [comment]
Well, `win_screenpos()` already existed.

Except now the situation is now super confusing because `getwininfo()` returns  `wp->w_winrow`/`wp->w_winrow` and `win_screenpos()` returns `wp->w_winrow + 1`/`wp->w_wincol + 1`.

**Comment by brammool** [comment]
Andy Massimino wrote:

> Well, `win_screenpos()` already existed.
> 
> Except now the situation is now super confusing because `getwininfo()`
> returns  `wp->w_winrow`/`wp->w_winrow` and `win_screenpos()` returns
> `wp->w_winrow + 1`/`wp->w_wincol + 1`.

Right, let's keep them equal.  I also see there are a few mistakes in
the help.

-- 
hundred-and-one symptoms of being an internet addict:
250. You've given up the search for the "perfect woman" and instead,
     sit in front of the PC until you're just too tired to care.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
