### ISSUE TITLE
"set spell" not downloading dictionaries

### ISSUE THREAD

**Issue by g-i-o-r-g-i-o** [vim/vim#3210]
In vim 8.0 I've got the same problem of the year 2006
http://vim.1045645.n5.nabble.com/Fwd-Missing-quot-it-ascii-spl-quot-td1156706.html

When I try
:set spell spelllang=it

I get a message that asks me if I want to download the spell file.  Then vim asks if I want to install it in ~/.vim/spell/ .
the I get the following error

Warning: Cannot find word list "it.latin1.spl" or "it.ascii.spl"

Next time, but when I write:
:set spell spelllang=it
I get the following error:
Warning: Cannot find word list "it.latin1.spl" or "it.ascii.spl"

It seems that there are outdated links in 
http://ftp.vim.org/vim/runtime/spell/it/
for example this 
http://ftp.services.openoffice.org/pub/OpenOffice.org/contrib/dictionaries
doesn't exist anymore

This is the output
```
Downloading IT.utf-8.spl...
:!curl 'http://ftp.vim.org/pub/vim/runtime/spell/IT.utf-8.spl' -o '/tmp/vgc9Y6a/
1.spl'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
"/tmp/vgc9Y6a/1.spl" 9L, 309C
Could not find it, trying IT.ascii.spl...
:!curl 'http://ftp.vim.org/pub/vim/runtime/spell/IT.ascii.spl' -o '/tmp/vgc9Y6a/
1.spl'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
"/tmp/vgc9Y6a/1.spl" 9L, 309C
Sorry, downloading failed
Warning: Cannot find word list "IT.utf-8.spl" or "IT.ascii.spl"
```

**Comment by GianniGi** [comment]
A small update on this.
Under ubuntu, if I run vim after pressing the windows key, and I run
set spelllang=it
and then
set spell
the command fails.

If I run the same commands after starting vim in a console, the commands run fine.
Where's the problem??

**Comment by vim-ml** [comment]
...it works for me in Vim 8.1.
You could try to do the download manually (see below).
Don't download the "suggestion" file, it is too huge.

C:\WINDOWS\system32\cmd.exe /c (curl ^"
http://ftp.vim.org/pub/vim/runtime/spell/it.latin1.spl^" -o
^"D:\cache\temp\VIA517E.spl^")
  % Total    % Received % Xferd  Average Speed   Time    Time     Time
Current
                                 Dload  Upload   Total   Spent    Left
Speed
100 1205k  100 1205k    0     0  1205k      0  0:00:01  0:00:01 --:--:--
941k
Hit any key to close this window...

All the best, Antonio
PS Contact me if you still have problems.

On Sun, Jul 15, 2018 at 11:54 AM GianniGi <vim-dev-github@256bit.org> wrote:

> In vim 8.0 I've got the same problem of the year 2006
>
> http://vim.1045645.n5.nabble.com/Fwd-Missing-quot-it-ascii-spl-quot-td1156706.html
>
> When I try
> :set spell spelllang=it
>
> I get a message that asks me if I want to download the spell file. Then
> vim asks if I want to install it in ~/.vim/spell/ .
> the I get the following error
>
> Warning: Cannot find word list "it.latin1.spl" or "it.ascii.spl"
>
> Next time, but when I write:
> :set spell spelllang=it
> I get the following error:
> Warning: Cannot find word list "it.latin1.spl" or "it.ascii.spl"
>
> It seems that there are outdated links in
> http://ftp.vim.org/vim/runtime/spell/it/
> for example this
> http://ftp.services.openoffice.org/pub/OpenOffice.org/contrib/dictionaries
> doesn't exist anymore
>
> This is the output
>
> Downloading IT.utf-8.spl...
> :!curl 'http://ftp.vim.org/pub/vim/runtime/spell/IT.utf-8.spl' -o '/tmp/vgc9Y6a/
> 1.spl'
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> "/tmp/vgc9Y6a/1.spl" 9L, 309C
> Could not find it, trying IT.ascii.spl...
> :!curl 'http://ftp.vim.org/pub/vim/runtime/spell/IT.ascii.spl' -o '/tmp/vgc9Y6a/
> 1.spl'
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> "/tmp/vgc9Y6a/1.spl" 9L, 309C
> Sorry, downloading failed
> Warning: Cannot find word list "IT.utf-8.spl" or "IT.ascii.spl"
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/vim/vim/issues/3210>
>
> --
> --
> You received this message from the "vim_dev" maillist.
> Do not top-post! Type your reply below the text you are replying to.
> For more information, visit http://www.vim.org/maillist.php
>
> ---
> You received this message because you are subscribed to the Google Groups
> "vim_dev" group.
> To unsubscribe from this group and stop receiving emails from it, send an
> email to vim_dev+unsubscribe@googlegroups.com.
> For more options, visit https://groups.google.com/d/optout.
>


-- 
   /||\    | Antonio Colombo
  / || \   |  azc100@gmail.com
 /  ()  \  | antonio@geekcorp.com
(___||___) |   azc10@yahoo.com

**Comment by g-i-o-r-g-i-o** [comment]
A small update on this.
Under ubuntu, if I run vim as as standalone app after pressing the windows key, and I run
set spelllang=it
and then
set spell
the command fails.

If I run the same commands after starting vim in a console, the commands run fine and I'm able to install the spell dictionaries.
Where's the problem??

**Comment by chrisbra** [comment]
The [spellfile plugin](https://github.com/vim/vim/blob/master/runtime/plugin/spellfile.vim) that is distributed with Vim tries to download the spellfiles from http://ftp.vim.org/pub/vim/runtime/spell/ using a `<two letter language code>.encoding.spl`.  You can read about it at `:h spellfile.vim` (also how to reset downloading).

Note, for you, it seems to have attempted to download `IT.utf-8-spl` rather `it`. Did you perhaps use `:set spelllang=IT`?

@brammool perhaps we need a patch like this:
```patch
diff --git a/runtime/autoload/spellfile.vim b/runtime/autoload/spellfile.vim
index e7fd1d8b1..69e45cd68 100644
--- a/runtime/autoload/spellfile.vim
+++ b/runtime/autoload/spellfile.vim
@@ -22,6 +22,7 @@ function! spellfile#LoadFile(lang)
     endif
     return
   endif
+  let lang=lower(a:lang)

   " If the URL changes we try all files again.
   if s:spellfile_URL != g:spellfile_URL
@@ -30,13 +31,13 @@ function! spellfile#LoadFile(lang)
   endif

   " I will say this only once!
-  if has_key(s:donedict, a:lang . &enc)
+  if has_key(s:donedict, lang . &enc)
     if &verbose
       echomsg 'spellfile#LoadFile(): Tried this language/encoding before.'
     endif
     return
   endif
-  let s:donedict[a:lang . &enc] = 1
+  let s:donedict[lang . &enc] = 1

   " Find spell directories we can write in.
   let [dirlist, dirchoices] = spellfile#GetDirChoices()
@@ -57,14 +58,14 @@ function! spellfile#LoadFile(lang)
     endif
   endif

-  let msg = 'Cannot find spell file for "' . a:lang . '" in ' . &enc
+  let msg = 'Cannot find spell file for "' . lang . '" in ' . &enc
   let msg .= "\nDo you want me to try downloading it?"
   if confirm(msg, "&Yes\n&No", 2) == 1
     let enc = &encoding
     if enc == 'iso-8859-15'
       let enc = 'latin1'
     endif
-    let fname = a:lang . '.' . enc . '.spl'
+    let fname = lang . '.' . enc . '.spl'

     " Split the window, read the file into a new buffer.
     " Remember the buffer number, we check it below.
@@ -95,7 +96,7 @@ function! spellfile#LoadFile(lang)
        let newbufnr = winbufnr(0)
       endif

-      let fname = a:lang . '.ascii.spl'
+      let fname = lang . '.ascii.spl'
       echo 'Could not find it, trying ' . fname . '...'
       call spellfile#Nread(fname)
       if getline(2) !~ 'VIMspell'
```

As to your [second problem later mentioned](https://github.com/vim/vim/issues/3210#issuecomment-405080468), can you please be more verbose about the `the command fails` part? I am guessing that netrw had a problem there (or the network connection was bad?)

If this is not reproducible, I am going to close this...

**Comment by brammool** [comment]
Christian wrote:

> The [spellfile
> plugin](https://github.com/vim/vim/blob/master/runtime/plugin/spellfile.vim)
> that is distributed with Vim tries to download the spellfiles from
> http://ftp.vim.org/pub/vim/runtime/spell/ using a `<two letter
> language code>.encoding.spl`.  You can read about it at `:h
> spellfile.vim` (also how to reset downloading).
> 
> Note, for you, it seems to have attempted to download `IT.utf-8-spl`
> rather `it`. Did you perhaps use `:set spelllang=IT`?
> 
> @brammool perhaps we need a patch like this:

That won't hurt.  Well, using tolower() instead of lower().


-- 
MAN:    Fetchez la vache!
GUARD:  Quoi?
MAN:    Fetchez la vache!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
closed by https://github.com/vim/vim/commit/a9604e61451707b38fdcb088fbfaeea2b922fef6

**Comment by Tanath** [comment]
I'm getting this issue with Termux. Says the language files are missing, and downloading fails. I installed elinks, which it uses to download, but then says it could not find it.

**Comment by matheusmoreira** [comment]
@Tanath Also ran into this issue on Termux.

```
$ vim
Warning: Cannot find word list "pt.utf-8.spl" or "pt.ascii.spl"
Press ENTER or type command to continue
```

I'll try creating an issue on the relevant Termux repositories but in the meantime: have you managed to resolve it?
