### ISSUE TITLE
Incorrect behavior on blank lines with foldmethod=indent

### ISSUE THREAD

**Issue by koshoi** [vim/vim#3214]
# Commit used
`2196bca7377ff245866cc3cee65b0adb48432ac3`

# Vim build and version
I've built the latest version of vim (that was available in master) without any tweaking and build configuration changes.
Just `./configure && make && ./src/vim -N -u NONE`
That gives me
`version 8.1.188`

# Setup
The only thing we need to define here is non-default foldmethod, so we type
`:set foldmethod=indent<CR>`
And also checking for the default foldingore
`:set foldignore<CR>`
That gives us the following result
`foldignore=#`

# Reproducing the bug
Let's pretend we are writing some JSON-config file (though it does not really matter)
We start with an empty buffer and type
`i{<CR><Tab>"key1":1,<CR><Tab>"key2":2<CR>}<Esc>`
That leaves us in normal mode and makes our buffer look like this:
```
{
        "key1":1,
        "key2":2
}
```

Then we type
`ggjza`
And out buffer begin to look like this:
```
{
+--  2 lines: "key1":1,--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
}
```
Which is totally ok.

Then let's pretend we want to add new key that is sepparated from the other two keys with a blank line.
So we type
`zajA,<CR><CR><Tab>"key3":3<Esc>`
That leaves us in normal mode and makes our buffer look like this:
```
{
        "key1":1,
        "key2":2,

        "key3":3
}
```
Then we type
`za`
and **nothing happens** (the bug).

# Bug workaround
There are methods to remind vim that the blank line should be included in the fold:

## Method 1 (works only on one line)
Go to the blank line and type
`S<Esc>`

After that vim will include the blank line in the fold.
In our case that would be
`GkkS<Esc>za`
That leaves us in normal mode with our buffer looking like this:
```
{
+--  4 lines: "key1":1,--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
}
```

**However**
If we have buffer looking like this (blank lines being completely blank without tab indentation)
```
{
        "key1":1,
        "key2":2,

        "key3":3,

        "key4":4
}
```
And type
`GkkS<Esc>za`
We will have our buffer look like this:
```
{
        "key1":1,
        "key2":2,

+--  3 lines: "key3":3,--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
}
```
And typing
`ggjza`
Makes the buffer look like this:
```
{
+--  2 lines: "key1":1,--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 
+--  3 lines: "key3":3,--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
}
```
(We still can fix this with the same trick on blank line between two folds)

## Method 2 (works on the whole buffer)
Let's go back and pretend, we are having buffer from the end of section **Reproducing the bug**
```
{
        "key1":1,
        "key2":2,

        "key3":3
}
```
We are in normal mode, so we type:
`:set foldingore=#<CR>za`
And that does the trick: the buffer is looking OK now
```
{
+--  4 lines: "key1":1,--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
} 
```
This method is cool because
* we don't need to to move cursor to a specific blank line
* it *fixes* every blank line in current buffer

So if we have empty buffer and type
`i{<CR><Tab>"key1":1,<CR><Tab>"key2":2,<CR><CR><Tab>"key3":3,<CR><CR><Tab>"key4":4<CR>}<Esc>`
We are going to have this buffer (with broken blank lines)
```
{
        "key1":1,
        "key2":2,

        "key3":3,

        "key4":4
}
```
And typing
`:set foldignore=#<CR>Gkza`
Make buffer look like this (fixing both broken lines at the same time)
```
{
+--  6 lines: "key1":1,--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
}
```
So it is kinda acceptable to add something like this in .vimrc
`nmap zz :set foldignore=#<CR>`
And type `zz` whenever you see broken blank lines messing with your folds.

**Comment by brammool** [comment]
> # Commit used
> `2196bca7377ff245866cc3cee65b0adb48432ac3`
> 
> # Vim build and version
> I've built the latest version of vim (that was available in master) without any tweaking and build configuration changes.
> Just `./configure && make && ./src/vim -N -u NONE`
> That gives me
> `version 8.1.188`
> 
> # Setup
> The only thing we need to define here is non-default foldmethod, so we type
> `:set foldmethod=indent<CR>`
> And also checking for the default foldingore
> `:set foldignore<CR>`
> That gives us the following result
> `foldignore=#`
> 
> # Reproducing the bug
> Let's pretend we are writing some JSON-config file (though it does not really matter)
> We start with an empty buffer and type
> `i{<CR><Tab>"key1":1,<CR><Tab>"key2":2<CR>}<Esc>`
> That leaves us in normal mode and makes our buffer look like this:
> ```
> {
>         "key1":1,
>         "key2":2
> }
> ```
> 
> Then we type
> `ggjza`
> And out buffer begin to look like this:
> ```
> {
> +--  2 lines: "key1":1,--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> }
> ```
> Which is totally ok.
> 
> Then let's pretend we want to add new key that is sepparated from the other two keys with a blank line.
> So we type
> `zajA,<CR><CR><Tab>"key3":3<Esc>`
> That leaves us in normal mode and makes our buffer look like this:
> ```
> {
>         "key1":1,
>         "key2":2,
> 
>         "key3":3
> }
> ```
> Then we type
> `za`
> and **nothing happens** (the bug).
> 
> # Bug workaround
> There are methods to remind vim that the blank line should be included in the fold:
> 
> ## Method 1 (works only on one line)
> Go to the blank line and type
> `S<Esc>`
> 
> After that vim will include the blank line in the fold.
> In our case that would be
> `GkkS<Esc>za`
> That leaves us in normal mode with our buffer looking like this:
> ```
> {
> +--  4 lines: "key1":1,--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> }
> ```
> 
> **However**
> If we have buffer looking like this (blank lines being completely blank without tab indentation)
> ```
> {
>         "key1":1,
>         "key2":2,
> 
>         "key3":3,
> 
>         "key4":4
> }
> ```
> And type
> `GkkS<Esc>za`
> We will have our buffer look like this:
> ```
> {
>         "key1":1,
>         "key2":2,
> 
> +--  3 lines: "key3":3,--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> }
> ```
> And typing
> `ggjza`
> Makes the buffer look like this:
> ```
> {
> +--  2 lines: "key1":1,--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
>  
> +--  3 lines: "key3":3,--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> }
> ```
> (We still can fix this with the same trick on blank line between two folds)
> 
> ## Method 2 (works on the whole buffer)
> Let's go back and pretend, we are having buffer from the end of section **Reproducing the bug**
> ```
> {
>         "key1":1,
>         "key2":2,
> 
>         "key3":3
> }
> ```
> We are in normal mode, so we type:
> `:set foldingore=#<CR>za`
> And that does the trick: the buffer is looking OK now
> ```
> {
> +--  4 lines: "key1":1,--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> } 
> ```
> This method is cool because
> * we don't need to to move cursor to a specific blank line
> * it *fixes* every blank line in current buffer
> 
> So if we have empty buffer and type
> `i{<CR><Tab>"key1":1,<CR><Tab>"key2":2,<CR><CR><Tab>"key3":3,<CR><CR><Tab>"key4":4<CR>}<Esc>`
> We are going to have this buffer (with broken blank lines)
> ```
> {
>         "key1":1,
>         "key2":2,
> 
>         "key3":3,
> 
>         "key4":4
> }
> ```
> And typing
> `:set foldignore=#<CR>Gkza`
> Make buffer look like this (fixing both broken lines at the same time)
> ```
> {
> +--  6 lines: "key1":1,--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> }
> ```
> So it is kinda acceptable to add something like this in .vimrc
> `nmap zz :set foldignore=#<CR>`
> And type `zz` whenever you see broken blank lines messing with your folds.

That looks like a bug.  Appending the empty line splits the fold, but
deleting that line and undoing joins the folds again.

-- 
Facepalm reply #3: "I had a great time in Manhattan" "I thought you were
going to New York?"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Rybadour** [comment]
I've been experiencing this for years it would be nice to see some resolution on it.

Updated: Just noticed this Stackoverflow question with a setting that fixes this:
https://stackoverflow.com/questions/8993455/how-do-i-fix-vim-to-properly-indent-folds-containing-python-comment-lines

Seems like "#" is a bad choice for a default at this point. Seems like an easy fix to change this to  be empty by default or make it do both?
