### ISSUE TITLE
Question about porting to JS

### ISSUE THREAD

**Issue by lunu-bounir** [vim/vim#3216]
I am trying to port vim to JS with [`--with-tlib=pdcurses`](https://pdcurses.sourceforge.io/)  as the terminal library and it actually works! Here is the output I get for now

![screen shot](https://user-images.githubusercontent.com/40388903/42755561-93510756-88f0-11e8-938e-aa6794ac981c.png)

As you can see vim successfully printed the 21 lines of "~" char plus the "1" which is the first line (since I have `set ruler` and `set number` rules in the vimrc). So it works as expected I guess. The warning I get is because the stdin is disabled and I'll handle that later.

At this point, I tried to run the following command to see if vim responses or not

```c
char_u buf[2];
buf[0] = 105;
buf[1] = 105;
add_to_input_buf(buf, 2);
```

I don't get any output what so ever. Considering the 105 is the code for "i", shouldn't I get one "i" being printed to the stdout?

**Comment by lacygoill** [comment]
This is a bug tracker.  For questions, visit the [developers mailing list](https://groups.google.com/g/vim_dev), the [users mailing list](https://groups.google.com/g/vim_use) or [vi.stackexchange.com](https://vi.stackexchange.com/).

**Comment by brammool** [comment]
I would say this is not an issue for Vim but a new project.  You could make a fork and work on it there.
