### ISSUE TITLE
README.txt doesn't mention manpager.vim

### ISSUE THREAD

**Issue by lkintact** [vim/vim#3217]
`$VIMRUNTIME/plugin/README.txt` doesn't include a description of `manpager.vim` located in the same directory.

Gvim build: `gvim_8.1.0189_x86.zip`, taken from https://github.com/vim/vim-win32-installer/releases.

**Comment by brammool** [comment]
> `README.txt` doesn't include a description of `manpager.vim` located in the same directory.

I'll add a line.

-- 
hundred-and-one symptoms of being an internet addict:
258. When you want to see your girlfriend, you surf to her homepage.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
closed by https://github.com/vim/vim/commit/a9604e61451707b38fdcb088fbfaeea2b922fef6
