### ISSUE TITLE
A correction to doc/usr_05.txt

### ISSUE THREAD

**Issue by lkintact** [vim/vim#3218]
In this part
```
GETTING A GLOBAL PLUGIN

Where can you find plugins?
- Some come with Vim.  You can find them in the directory $VIMRUNTIME/macros
  and its sub-directories.

```
`$VIMRUNTIME/macros and its sub-directories` should probably be replaced with `$VIMRUNTIME/plugins` since the global plugins mentioned in the previous section and linked to with the  `|standard-plugin-list|`  tag are located in `plugins`.

gvim_8.1.0189_x86.zip

**Comment by lkintact** [comment]
Also, in the same file, section `GETTING A FILETYPE PLUGIN`, `macros` should be replaced with `plugins` in `The scripts in $VIMRUNTIME/macros are global ones`

**Comment by tonymec** [comment]
The plugins in `$VIMRUNTIME/plugin` are (by virtue of being in the `plugin` subdirectory) already installed, you don't need to "get" them. OTOH, `$VIMRUNTIME/macros` contains additional, optional, plugins, which you may or may not want to install. Of these, matchit is also distributed as an optional package, so `:packadd matchit` will load it, and in fact that command (with an aditional ! to load it together with other global plugins) is found near the end of the `vimrc_example.vim`. (The reason this plugin is present at both places is that Vim acquired the package mechanism much later than both `matchit.vim` and the `macros` subdirectory.)

Best regards,
Tony.

**Comment by lkintact** [comment]
Ah, sorry, I understand now. Because instead of "complete" _plugins_ I found several small files sourcing _packages_ in `$VIMRUNTIME/macros`, I somehow decided the standard plugins had resided in `macros` in the past, but then were moved to `plugins`, which for some reason wasn't reflected in the docs.
Closing the issue, thank you.

**Comment by brammool** [comment]
> In this part
> ```
> GETTING A GLOBAL PLUGIN
> 
> Where can you find plugins?
> - Some come with Vim.  You can find them in the directory $VIMRUNTIME/macros
>   and its sub-directories.
> 
> ```
> `$VIMRUNTIME/macros and its sub-directories` should probably be
> replaced with `$VIMRUNTIME/plugins` since the global plugins mentioned
> in the previous section and linked to with the
> `|standard-plugin-list|`  tag are located in `plugins`.

The  plugin  directory contains files that are already being loaded.
The docs point to other plugins you could use.

It should now also point to the packages directory though.

-- 
hundred-and-one symptoms of being an internet addict:
260. Co-workers have to E-mail you about the fire alarm to get
     you out of the building.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
