### ISSUE TITLE
sudoers wrong highlighting

### ISSUE THREAD

**Issue by cbrchrt** [vim/vim#3222]
sudoers highlights #includedir directive as a comment.

To reproduce it just run sudo visudo in Debian 9 or Ubuntu 18.04 and check the last lines:

```
# See sudoers(5) for more information on "#include" directives:

#includedir /etc/sudoers.d
```

**Comment by tonymec** [comment]
This might be a known problem (the line in question seems to be the only non-comment line beginning with `#`); at least the openSUSE 42.3 sudoers file ends as follows:
```sudoers
## Read drop-in files from /etc/sudoers.d
## (the '#' here does not indicate a comment)
#includedir /etc/sudoers.d
```
Best regards,
Tony.

**Comment by chrisbra** [comment]
Yeah, I think we need this change:
```patch
diff --git a/runtime/syntax/sudoers.vim b/runtime/syntax/sudoers.vim
index df1eb99b4..67a248f5e 100644
--- a/runtime/syntax/sudoers.vim
+++ b/runtime/syntax/sudoers.vim
@@ -24,6 +24,7 @@ syn cluster sudoersCmndSpecList       contains=sudoersUserRunasBegin,sudoersPASS
 syn keyword sudoersTodo               contained TODO FIXME XXX NOTE

 syn region  sudoersComment            display oneline start='#' end='$' contains=sudoersTodo
+syn region  sudoersInclude            display oneline start='#\(include\|includedir\)' end='$'

 syn keyword sudoersAlias              User_Alias Runas_Alias nextgroup=sudoersUserAlias skipwhite skipnl
 syn keyword sudoersAlias              Host_Alias nextgroup=sudoersHostAlias skipwhite skipnl
@@ -335,6 +336,7 @@ hi def link sudoersIntegerValue             Number
 hi def link sudoersStringValue              String
 hi def link sudoersListValue                String
 hi def link sudoersPASSWD                   Special
+hi def link sudoersInclude                  Statement

 let b:current_syntax = "sudoers"

```

Note, I think Nikolai doesn't maintain the runtime files anymore, so I just paste the diff here, hoping Bram will apply it nevertheless.

**Comment by brammool** [comment]
Christian wrote:

> Yeah, I think we need this change:
> ```patch
> diff --git a/runtime/syntax/sudoers.vim b/runtime/syntax/sudoers.vim
> index df1eb99b4..67a248f5e 100644
> --- a/runtime/syntax/sudoers.vim
> +++ b/runtime/syntax/sudoers.vim
> @@ -24,6 +24,7 @@ syn cluster sudoersCmndSpecList       contains=sudoersUserRunasBegin,sudoersPASS
>  syn keyword sudoersTodo               contained TODO FIXME XXX NOTE
> 
>  syn region  sudoersComment            display oneline start='#' end='$' contains=sudoersTodo
> +syn region  sudoersInclude            display oneline start='#\(include\|includedir\)' end='$'
> 
>  syn keyword sudoersAlias              User_Alias Runas_Alias nextgroup=sudoersUserAlias skipwhite skipnl
>  syn keyword sudoersAlias              Host_Alias nextgroup=sudoersHostAlias skipwhite skipnl
> @@ -335,6 +336,7 @@ hi def link sudoersIntegerValue             Number
>  hi def link sudoersStringValue              String
>  hi def link sudoersListValue                String
>  hi def link sudoersPASSWD                   Special
> +hi def link sudoersInclude                  Statement
> 
>  let b:current_syntax = "sudoers"
> 
> ```
> 
> Note, I think Nikolai doesn't maintain the runtime files anymore, so I
> just paste the diff here, hoping Bram will apply it nevertheless.

Yeah, let me just include this.  Thanks.

-- 
The software said it requires Windows 95 or better, so I installed Linux.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
closed by https://github.com/vim/vim/commit/a9604e61451707b38fdcb088fbfaeea2b922fef6
