### ISSUE TITLE
sh.vim [178]: for (( expr1; expr2; expr3 )) not syntax-highlighted correctly

### ISSUE THREAD

**Issue by marcelpaulo** [vim/vim#3224]
command `for (( expr1; expr2; expr3 ))` is not syntax-highlighted correctly. And the highlight changes depending on the command location: whether outside or within a compound command.

I'm running vim built from master (lastest as of now: ca4cc018addbeb3ac5d0e05f18847015f91ff814) on Xubuntu 18.04, with _~/.vim/syntax/sh.vim_ **178** downloaded from [Dr Chip's Vim Page](http://www.drchip.org/astronaut/vim/index.html#SYNTAX_SH)

To reproduce it, run:

`vim -N -u NONE -i NONE -c 'let b:is_bash=1' -c 'set ft=sh' -c 'syn on'` _file_

where _file_ is this bash script:

```
for (( i=0; i < 10; i++ )); do
    echo "$i"
done

case $1 in
    foo)    for (( i=0; i < 10; i++ )); do
		echo "case: $i"
	    done
	    ;;
esac

if [[ $1 == bar ]]; then
    for (( i=0; i < 10; i++ )); do
	echo "if: $i"
    done
fi

for word in foo bar; do
    for (( i=0; i < 10; i++ )); do
	echo "if: $i"
    done
done

echo foo | while read -r word; do
    for (( i=0; i < 10; i++ )); do
	echo "if: $i"
    done
done
```

To give an idea of the results:
![image](https://user-images.githubusercontent.com/10074769/42826691-6319018a-89bb-11e8-9f72-bdad20c18af4.png)

**Comment by cecamp** [comment]
K.Takata wrote:
>
> Assigned #3224 <https://github.com/vim/vim/issues/3224> to @cecamp 
> <https://github.com/cecamp>.
>
>
I have this issue and several others fixed; however, I'm going through 
my syntax test files and fixing other problems too.  On top of that, 
I'll be gone for about a week on travel (and need to pack now).  So it 
may be awhile. I'll go ahead and put what I have on my website 
(http://www.drchip.org/astronaut/vim/index.html#SYNTAX_SH).

Regards,
Chip Campbell

**Comment by marcelpaulo** [comment]
Thanks a lot, @cecamp ! I suppose you're on the northern hemisphere, so enjoy your summer trip !

Using **179**, the only remaining glitches are the numbers and the variables: in the test file, the `0` and the `10` are not highlighted in the same way, and variable `i` is highlighted as a reserved word. Everything else is correct.

But that's for your return. Once again, thanks for this update !

**Comment by chrisbra** [comment]
https://github.com/vim/vim/commit/d2855f5454c5c6c5f786b228c5b67757edfefcb1 included version 179

**Comment by marcelpaulo** [comment]
Indeed ! And includes @cecamp's [latest](http://www.drchip.org/astronaut/vim/index.html#SYNTAX_SH). There's a still a glitch with numbers inside `(( ))`, and `[[ ]]`.

**Comment by cecamp** [comment]
Please try the latest one from my website. I did another update...

Chip Campbell

**Comment by marcelpaulo** [comment]
**181** gave the final blow to this issue !

I hope I haven't disturbed your trip again ! Thanks a lot !
