### ISSUE TITLE
Highlight_Matching_Pair called with invalid arguments on comments

### ISSUE THREAD

**Issue by wsfreund** [vim/vim#3225]
Dear devs,

When I go to a parenthesis in a comment I face the following issue (it is only triggered when syntax on is used):

```
Error detected while processing function <SNR>134_Highlight_Matching_Pair:
line   78:
E475: Invalid argument: 0
```

I believe that this was due to a recent change in the project since I update vim every week and only recently I've facing this issue. Unfortunately, it is not easy for me to track exactly which commit triggered this error, but I hope that the information make it easy for it to be fixed.

Btw, I just updated vim:

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 17 2018 18:40:02)
Included patches: 1-193
Compiled by wsfreund@verdun.lps.ufrj.br
Huge version without GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
+clientserver      +job               +perl              +vartabs
+clipboard         +jumplist          +persistent_undo   +vertsplit
+cmdline_compl     +keymap            +postscript        +virtualedit
+cmdline_hist      +lambda            +printer           +visual
+cmdline_info      +langmap           +profile           +visualextra
+comments          +libcall           +python            +viminfo
+conceal           +linebreak         -python3           +vreplace
+cryptv            +lispindent        +quickfix          +wildignore
+cscope            +listcmds          +reltime           +wildmenu
+cursorbind        +localmap          +rightleft         +windows
+cursorshape       +lua               +ruby              +writebackup
+dialog_con        +menu              +scrollbind        +X11
+diff              +mksession         +signs             +xfontset
+digraphs          +modify_fname      +smartindent       -xim
-dnd               +mouse             +startuptime       +xpm
-ebcdic            -mouseshape        +statusline        +xsmp_interact
+emacs_tags        +mouse_dec         -sun_workshop      +xterm_clipboard
+eval              -mouse_gpm         +syntax            -xterm_save
+ex_extra          -mouse_jsbterm     +tag_binary
+extra_search      +mouse_netterm     +tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim74"
Compilation: gcc -std=gnu99 -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc -std=gnu99   -L. -Wl,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,—enable-new-dtags -Wl,-rpath,/usr/lib64/perl5/CORE   -L/usr/local/lib -Wl,—as-needed -o vim    -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -lelf -lnsl  -lselinux  -lncurses -ldl  -L/usr/lib -llua -Wl,--enable-new-dtags -Wl,-rpath,/usr/lib64/perl5/CORE  -fstack-protector  -L/usr/lib64/perl5/CORE -lperl -lresolv -lnsl -ldl -lm -lcrypt -lutil -lpthread -lc -L/usr/lib64/python2.7/config -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic   -lruby -lpthread -lrt -ldl -lcrypt -lm
``` 

Cheers,
Werner.

**Comment by tonymec** [comment]
AFAICT (but maybe I missed it) I don't see a function `<SNR>nn_Highlight_Matching_Pair()` (where nn is some number) in the output of `:function` (with no argument); but I only have 55 scripts loaded, not 134.

The next time you get that error, please check in the output of `:scriptnames` what is the script listed at the same numbered spot in the list as the number that appears *at that moment* after `<SNR>_` in the error message (above it was 134 but it could be a different number the next time). That is the script where the error is found, at line 78 of a function named `s:Highlight_Matching_Pair()` or maybe the equivalent `<SID>Highlight_Matching_Pair()` (and that's line 78 of the function, not line 78 of the script).

Oh, and BTW, why are you configuring Vim to look for its runtime files under `/usr/share/vim/vim74` ? Without that configure setting, Vim 8.1 would look for them under `/usr/share/vim/vim81/` (which is normal for a Vim 8.1 distributed by the makers of a Unix-like distro) or even, preferably, under `/usr/local/share/vim/vim81/` (which is the default place for Vim 8.1 runtime files and the normal place for the runtime files of a Vim 8.1 compiled by the user). And remember that your own scripts, or any scripts not distributed with Vim, should not go there but either under `~/.vim` (for user-private scripts on Unix-like platforms) or under `$VIM/vimfiles` which on Unix-like platforms is normally `/usr/(local/)share/vim/vimfiles/` (for system-wide scripts accessible to all users of that system, whatever their login name).

Best regards,
Tony.

**Comment by wsfreund** [comment]
Ok, I had an outdated script that was setting VIMRUNTIME to this old path. When I recompiled without overriding this variable, the problem was gone. 

Thanks a lot for calling my attention for this fact. Best,
Werner.
