### ISSUE TITLE
Add new WinResized/WinLayoutChanged autocommand

### ISSUE THREAD

**Issue by blueyed** [vim/vim#3226]
There is currently no way to react on windows being resized.

For https://github.com/blueyed/vim-qf_resize it would be useful react on another plugin doing a `:resize`.

If `<amatch>` would contain the filetype, that would be good for vim-qf_resize (which only wants to handle `qf` windows), but I am not sure if this is a good fit in general (at least it feels out of place to link this to filetypes, and it easy to look at the &ft in the autocmd callback)).

Probably a more generic autocommand like "WinLayoutChanged" would be feasible, since `WinResized` would typically be triggered for multiple windows anyway.

Ref: https://github.com/neomake/neomake/issues/1970#issuecomment-405763953

**Comment by tonymec** [comment]
IMO plugins have no business changing the window layout, unless maybe by opening a new window like the netrw plugin does when I hit `o` on a filename, and even so, I want the new layout to be determined by whatever I, the user, have set the options `'equalalways'`, `'winheight'`, `'winminheight'`, etc. to be and not by any plugin author's whim. If a loaded plugin started misbehaving in such a way, and I noticed it, it would not long remain installed. But of course there is no limit to what plugin authors might program so maybe such an autocommand would be useful. I might want to know where the resize command is coming from though: if I split windows manually, of course the layout will be changed, but any script I wrote to react to such an event should be able to know that no action is wanted.

**Comment by blueyed** [comment]
Thanks for your feedback!

There is a reason for `:lwindow` accepting a number though, and e.g. Neomake uses it to use the minimum of the user configured height and the length of the list itself (i.e. with only two entries, it will use `:lwindow 2`).
However, since it runs multiple makers in parallel then the next maker might add some entries and users would like the height to be adjusted then (https://github.com/neomake/neomake/issues/1970).

I am using vim-qf_resize myself (I wrote it), and noticed that it does not get notified in this situation.

> I might want to know where the resize command is coming from though

This might be possible through some special `v:` vars, but it is not really clear to me yet - this issue is merely for discussing/brainstorming it.

For Neomake I will change it likely to delay the initial `:lwindow`, i.e. it will typically get done when all jobs have finished (using 500ms for this by default).  I will also add an option to skip the `resize` completely.  https://github.com/neomake/neomake/pull/2011

**Comment by andymass** [comment]
> There is currently no way to react on windows being resized.

I think it is possible to determine when windows change size within a statusline function.  If the user has vim-airline for example, you could write an extension which just monitors for size changes.

**Comment by zeertzjq** [comment]
I think this is closed by patch 9.0.0917

**Comment by chrisbra** [comment]
closing then.
