### ISSUE TITLE
gethostbyname() is deprecated, please use getaddrinfo() instead

### ISSUE THREAD

**Issue by fusion809** [vim/vim#3227]
Hi,

This is a fairly minor thing, my Vim build for openSUSE is giving me the rpmlint warning:

```bash
[  118s] gvim-gtk2.x86_64: I: binary-or-shlib-calls-gethostbyname /usr/bin/gvim-gtk2
[  118s] gvim-gtk3.x86_64: I: binary-or-shlib-calls-gethostbyname /usr/bin/gvim-gtk3
[  118s] vim.x86_64: I: binary-or-shlib-calls-gethostbyname /usr/bin/vim
[  118s] The binary calls gethostbyname(). Please port the code to use getaddrinfo().
```

and I thought you's may wish to do something about this. The [relevant article](https://en.opensuse.org/openSUSE:Packaging_checks) on the openSUSE Wiki explains:

> The gethostbyname*() and gethostbyaddr*() functions are deprecated as among other things they are not IPv6 ready. Applications should use getaddrinfo(3) and getnameinfo(3) instead. Please work with upstream to port the application to the modern interface. [Ulrich Drepper](https://udrepper.livejournal.com/16116.html) explains the issues in more detail. 

I'm not much of a programmer, at least not in C, but I thought you's might wish to know about this as it is relevant to IPv6. 

Thanks for your time,
Brenton

**Comment by chrisbra** [comment]
I think this has been fixed as of  bfe13ccc58ccb96f243a5830980041
