### ISSUE TITLE
Add text to .TH line in .1 files (man files)

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3232]
I have translate .1 files but i see the top center text is not translated and not found in the .1 files.

It seems it can be added to the end of the .TH line:

    .TH VIM 1 "11. april 2006"
    .TH VIM 1 "11. april 2006" "TEXT AT BOTTOM LEFT" "TEXT AT TOP CENTER"

So "TEXT AT TOP CENTER" will show at the top center.
Running "man vim" says "General Commands Manual" at top center which might be generic text that comes from groff command.

Should we keep "General Commands Manual" or change to something else?
When the text is added to the .1 files the translators can see it and translate it.

I dont know about the version text maybe we can just leave it empty?

    .TH VIM 1 "11. april 2006" "" "TEXT AT TOP CENTER"

**Comment by brammool** [comment]
> I have translate .1 files but i see the top center text is not translated and not found in the .1 files.
> 
> It seems it can be added to the end of the .TH line:
> 
>     .TH VIM 1 "11. april 2006"
>     .TH VIM 1 "11. april 2006" "TEXT AT BOTTOM LEFT" "TEXT AT TOP CENTER"
> 
> So "TEXT AT TOP CENTER" will show at the top center.
> Running "man vim" says "General Commands Manual" at top center which might be generic text that comes from groff command.
> 
> Should we keep "General Commands Manual" or change to something else?
> When the text is added to the .1 files the translators can see it and
> translate it.
> 
> I dont know about the version text maybe we can just leave it empty?
> 
>     .TH VIM 1 "11. april 2006" "" "TEXT AT TOP CENTER"

AFAIK the extra items are Linux extensions, not part of the original
Unix man pages.  Where they show up can change depending on what command
processes the file.

I don't see a reason to make changes.

-- 
Life would be so much easier if we could just look at the source code.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
