### ISSUE TITLE
langmenu is not set (gVim menus are in english)

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3233]
I build Vim in Linux Mint but it seems langmenu is not set so gVim menus are in english and not the language i use.

Running this changes the menu language:

    source $VIMRUNTIME/delmenu.vim
    set langmenu=da.utf-8
    source $VIMRUNTIME/menu.vim

But when i restart gVim, langmenu is again not set.

**Comment by chrisbra** [comment]
Well, if you do not set it inside your .vimrc file, it won't have an effect after a restart.

However, I think if langmenu is empty, it should use `v:lang`. So what locale are you using? What is the output of `:language mes` inside Vim?

**Comment by k-takata** [comment]
I think `menu_da_dk.*.vim` files are also needed.

**Comment by scootergrisen** [comment]
Having menu_da_dk.vim works (gVim menus are in danish).
Not that i want that as a solution.

env says:

    LANG=da_DK.UTF-8
    LANGUAGE=da

:language mes says:

    "da_DK.UTF-8"

:echo $lang says:

    da_DK.UTF-8

If they say "da_DK.UTF-8" it does not load menu_da.utf-8.vim/menu_da.latin1.vim.
But when they say "DA" it does.

**Comment by scootergrisen** [comment]
If i run:

    LANG=da_DK.UTF-8 gvim

:language mes says:

    da_DK.UTF-8

If i run:

    LANG=da_DK gvim
    LANG=da gvim

:language mes says:

    C

**Comment by scootergrisen** [comment]
In Windows 7 using MINGW64 terminal i can run:

    LANG=da_DK gvim
    LANG=da gvim

And :language mes says:

    da_DK
    da

But for some reason in Linux Mint it gives C.

**Comment by chrisbra** [comment]
If you do `:lang mess da` inside your .vimrc does it work? Note, this needs to be at the very beginning, before menus are loaded (might happen on :filetype and :syn commands).

**Comment by k-takata** [comment]
> If i run:
> 
> LANG=da_DK gvim
> LANG=da gvim
> 
> :language mes says:
> 
> C

It's not a Vim issue.
Try `locale -a` command to check what locales are installed in your system.
Only installed locale can be set to $LANG.

**Comment by chrisbra** [comment]
I am not so sure, if we can't do better here. 

We could try this:
```patch
diff --git a/runtime/menu.vim b/runtime/menu.vim
index b9bd3d89c..0963aeccb 100644
--- a/runtime/menu.vim
+++ b/runtime/menu.vim
@@ -51,10 +51,18 @@ if exists("v:lang") || &langmenu != ""
     exe "runtime! lang/menu_" . s:lang . ".vim"

     if !exists("did_menu_trans")
-      " There is no exact match, try matching with a wildcard added
-      " (e.g. find menu_de_de.iso_8859-1.vim if s:lang == de_DE).
-      let s:lang = substitute(s:lang, '\.[^.]*', "", "")
-      exe "runtime! lang/menu_" . s:lang . "[^a-z]*vim"
+      for pat in ['\.[^.]*', '_.*']
+        " There is no exact match, try matching with a wildcard added
+        " (e.g. find menu_de_de.iso_8859-1.vim if s:lang == de_DE).
+        " Try twice:
+        "   1) de_de.utf-8
+        "   2) de.utf-8 (e.g. remove everything after the '_')
+        let s:lang = substitute(s:lang, pat, "", "")
+        exe "runtime! lang/menu_" . s:lang . "[^a-z]*vim"
+        if exists("did_menu_trans")
+          break
+        endif
+      endfor

       if !exists("did_menu_trans") && strlen($LANG) > 1 && s:lang !~ '^en_us'
        " On windows locale names are complicated, try using $LANG, it might
```

e.g. when trying different locales and stripping everything after the `.`, why not also try afterwards to remove everything after the `_` and try loading again.

On a second thought, I am not even sure, this works correctly in all cases. I see two issues here:
1) does it actually make sense to source menu files which are in a different encoding than the one we are currently using? IMHO, this will garble menu strings and break
2) In case of `menu_de_de.utf-8.vim` why are we blindly sourcing `menu_de_de.latin1.vim`? Shoudln't there at least be a `:scriptencoding latin1`?

**Comment by chrisbra** [comment]
ah, there is actually a `:scriptencoding` block in the `latin1` case, did not see this.

**Comment by scootergrisen** [comment]
For some reason in Windows 7 using MINGW64 terminal i can set LANG to anything and it will show in :language mes.

From a users point of view i would expect that the translation for the menus follow that of Vim.
So if Vim is using danish translation i would expect gVim menus to also use danish translation.
And if there is some kind of problem loading the correct translation i would expect it to fail in both cases and not work in one case (Vim) and fail in another case (gVim menus).

**Comment by scootergrisen** [comment]
Another example:

If your locale is nb_NO.UTF-8 gVim will fall back to english and not load these files:

    menu_no.latin1.vim
    menu_no.utf-8.vim
    menu_no_no.latin1.vim
    menu_no_no.utf-8.vim

It seems silly if each translation have to have endless amounts of files that redirects to another file.

I guess the only reason gVim menus are in english for english languages is because it falls back to english when it dont work. When the translation like en_AU.UTF-8 does not exists.

**Comment by scootergrisen** [comment]
As i temporary solution for danish i can create all these files until the problem is corrected:

    menu_da.latin1.vim
    menu_da.utf-8.vim
    menu_da_de.latin1.vim
    menu_da_de.utf-8.vim
    menu_da_dk.latin1.vim
    menu_da_dk.utf-8.vim
    menu_da_fo.latin1.vim
    menu_da_fo.utf-8.vim
    menu_da_gl.latin1.vim
    menu_da_gl.utf-8.vim

menu_da.utf-8.vim containing the translations and all the others just sources the file.

**Comment by chrisbra** [comment]
fixed by https://github.com/vim/vim/commit/68f1b1b37fa7aba985d9f8727fd9f0f3eb0c19a9
