### ISSUE TITLE
Bug of ag or bug of vim?

### ISSUE THREAD

**Issue by Yggdroot** [vim/vim#3236]
My plugin [LeaderF](https://github.com/Yggdroot/LeaderF) encountered an [issue](https://github.com/Yggdroot/LeaderF/issues/190), [ag](https://github.com/ggreer/the_silver_searcher) can not list files on Windows.

**Steps to reproduce:**
1. enter vim
2. run the below commands:
   ```python
   :py import subprocess
   :py print subprocess.Popen('ag -g "" .', shell=True, stdout=subprocess.PIPE).stdout.read()
   ```
no output.(suppose there are some files in current directory)

**Expected result:**

all the files can be listed just like running `ag -g "" .` in git-bash.

If purely run the python code, everything works fine.
For example, execute the command ` py -2 test.py`, `test.py` is as below:
   ```python
   import subprocess
   print ( subprocess.Popen('ag -g "" .', shell=True, stdout=subprocess.PIPE).stdout.read() )
   ```
So, I think this probably is a bug of vim.

**Comment by chrisbra** [comment]
Have you tried with a different binary than ag?

**Comment by Yggdroot** [comment]
I have tried [rg](https://github.com/BurntSushi/ripgrep), it works well.

**Comment by JRuiChen** [comment]
I have encountered the same problem, but when i change 'ag' to 'Ag', the LeaderFile works well.  For my installation of ag, the system don't accept 'ag' but 'Ag'. Can you try it ?

**Comment by Yggdroot** [comment]
@JRuiChen  'Ag' does not work for me either.

**Comment by JRuiChen** [comment]
@Yggdroot

**Comment by JRuiChen** [comment]
@Yggdroot  
enter vim
:py import subprocess
:py print subprocess.Popen('ag -g "" .', shell=True, stdout=subprocess.PIPE).stdout.read()
I have no output either.

1. The problem i faced is,  in  .vimrc:
      **let g:Lf_IndexTimeLimit=20
      let g:Lf_DefaultExternalTool="ag"**
      let g:Lf_RootMarkers=['version.txt', 'server', 'client']
Enter vim , the LeaderFile command has no output.   In .LFCache Dir, there is no cache files greater than 0 created.
2. The i changed .vimrc to:
      **let g:Lf_IndexTimeLimit=120
      let g:Lf_DefaultExternalTool="Ag"**
      let g:Lf_RootMarkers=['version.txt', 'server', 'client']
Enter vim, LeaderFile works well. And in .LFCache Dir, it has created some caches file greater than 0

**Comment by Yggdroot** [comment]
@JRuiChen What is the output of `echo g:Lf_Debug_Cmd`? According to my logic, you are not using `ag`.

**Comment by JRuiChen** [comment]
@Yggdroot 
1. When `g:Lf_DefaultExternalTool="Ag"`,  there is no output for `echo g:Lf_Debug_Cmd`. But the command **LeaderFile** works well for a new directory  .
2. When  **g:Lf_DefaultExternalTool="ag"**,  there is the output   `ag --nocolor --silent -ignore "*.SW?" --ignore "*.bak" -g  "" "C:\pack_tool_chain"`.  But the command **LeaderFile** lists no files for a new directory  .
3. In my vim's command mode, only 'Ag' is valid, 'ag' is not.
So, the two commands **LeaderFile** and **echo g:Lf_Debug_Cmd** both use the property g:Lf_DefaultExternalTool,  but Ag is valid for LeaderFile, and ag is valid for  g:Lf_Debug_Cmd.

**Comment by Yggdroot** [comment]
@JRuiChen `let g:Lf_DefaultExternalTool="Ag"` is the same as `let g:Lf_DefaultExternalTool="asdfasfasdf"`, because in this case g:Lf_DefaultExternalTool does not take effect, LeaderF uses the default index logic.  
Available values for g:Lf_DefaultExternalTool are 'rg', 'pt', 'ag', 'find', which are case sensitive.
  
 https://github.com/Yggdroot/LeaderF/blob/a7ac653667fd23e74f8ac290a2796acd1123d299/autoload/leaderf/python/leaderf/fileExpl.py#L207-L367

**Comment by JRuiChen** [comment]
@Yggdroot 
You are right. It is not the prolem of 'Ag' or 'ag'. When 'Ag', it is just using os.walk(dir) to get filelist.

**Comment by Yggdroot** [comment]
@chrisbra Verified that this must be bug of vim.
```python
import subprocess
print ( subprocess.Popen('rg ""', shell=True, stdout=subprocess.PIPE).stdout.read() )
```
Because rg does not work either.
There must be something wrong for windows gvim to process double quote.

**Comment by chrisbra** [comment]
Have you checked the various `shell` options? 'shellquote'  might be relevant (and possibly others as well)

**Comment by mattn** [comment]
I tried this with ag installed from msys2/mingw64 package manager. Worked fine for me.

**Comment by Yggdroot** [comment]
`shell` options do not help.

**Comment by eirnym** [comment]
As per discussion in https://github.com/macvim-dev/macvim/issues/1003 LeaderF should add `stdin=subprocess.DEVNULL` as an additional component as a proper usage to pass an input stream to a python process. In `:help python-input` is written, that reading from standard input produces undefined behaviour including a possible crash  (see text below).

```vimscript
							*python-input*
	Input (via sys.stdin, including input() and raw_input()) is not
	supported, and may cause the program to crash.  This should probably be
	fixed.
`

**Comment by chrisbra** [comment]
This should go to the leaderf repo, not here, right?

**Comment by eirnym** [comment]
if it's not possible to provide for Python by Vim Core the stable and predictable stdin (like `/dev/null`), then yes. I *think* that neovim provides `/dev/null` as an stdin for plugins.

**Comment by Yggdroot** [comment]
> As per discussion in [macvim-dev/macvim#1003](https://github.com/macvim-dev/macvim/issues/1003) LeaderF should add `stdin=subprocess.DEVNULL` as an additional component as a proper usage to pass an input stream to a python process. In `:help python-input` is written, that reading from standard input produces undefined behaviour including a possible crash (see text below).
> 
> ```
> 							*python-input*
> 	Input (via sys.stdin, including input() and raw_input()) is not
> 	supported, and may cause the program to crash.  This should probably be
> 	fixed.
> `
> ```

Thanks, this works for me.

**Comment by ychin** [comment]
Actually, I kind of agree with @eirnym. Seems like having a "is not supported, and may cause the program to crash" default seems… dangerous? That sounds like it's easy to trick Vim into undefined behavior which is not great. The documentation even says "This should probably be fixed" which implies this was a temporary solution.

From the bug report, this didn't fail when being called in terminal Vim, which I think means the Python script is using the stdin from the terminal, which I think is not the desired behavior? Seems like providing `/dev/null` is going to improve compatibility and potential security/random issues.

**Comment by chrisbra** [comment]
could you provide a PR for that change then?

**Comment by ychin** [comment]
I could probably look into this in a few days.
