### ISSUE TITLE
Edit file with existing vim in right-mouse menu failed!

### ISSUE THREAD

**Issue by trackless** [vim/vim#3244]
os: win10 64bit
gvim version:8.1.1
buffer plugin: vim airline or buftabline

It works well before version 8.0.3.

**Comment by chrisbra** [comment]
do you get an error message?

**Comment by trackless** [comment]
No,nothing happened.
It seems that it is invalid that moment.

**Comment by k-takata** [comment]
"Edit file with existing vim" is implemented using D&D message.
Somehow the `updating_screen` variable becomes 1 when `handle_drop()` is called, and the D&D message is silently ignored:
https://github.com/vim/vim/blob/b6c8cd8dc3fbbe9da1180ce1b75f2252df2c1318/src/ex_docmd.c#L7896-L7899

Inserting a short sleep before posting the D&D message seems works around the issue:

```diff
--- a/src/GvimExt/gvimext.cpp
+++ b/src/GvimExt/gvimext.cpp
@@ -828,6 +828,8 @@ STDMETHODIMP CShellExt::PushToWindow(HWN
 	ShowWindow(hWnd, SW_SHOW);
     SetForegroundWindow(hWnd);
 
+    Sleep(100);
+
     // Post the selected files to the vim instance
     PostMessage(hWnd, WM_DROPFILES, (WPARAM)medium.hGlobal, 0);
 
```

However I'm not sure what the root cause is.

**Comment by brammool** [comment]
Ken Takata wrote:

> "Edit file with existing vim" is implemented using D&D message.
> Somehow the `updating_screen` variable becomes 1 when `handle_drop()` is called, and the D&D message is silently ignored:
> https://github.com/vim/vim/blob/b6c8cd8dc3fbbe9da1180ce1b75f2252df2c1318/src/ex_docmd.c#L7896-L7899
> 
> Inserting a short sleep before posting the D&D message seems works around the issue:
> 
> ```diff
> --- a/src/GvimExt/gvimext.cpp
> +++ b/src/GvimExt/gvimext.cpp
> @@ -828,6 +828,8 @@ STDMETHODIMP CShellExt::PushToWindow(HWN
>  	ShowWindow(hWnd, SW_SHOW);
>      SetForegroundWindow(hWnd);
>  
> +    Sleep(100);
> +
>      // Post the selected files to the vim instance
>      PostMessage(hWnd, WM_DROPFILES, (WPARAM)medium.hGlobal, 0);
>  
> ```
> 
> However I'm not sure what the root cause is.

Me neither.  But we could do something more robust: when handle_drop()
returns for one of the three reasons at the start, it could put
something in the typeahead buffer to have it done when the conditions
changed.  this requires saving the arguments, thus it's a bit of work.
Not sure if using the typeahead buffer works, perhaps setting a flag
that is checked after the conditions are reset works better.

If handle_drop() is called again before it's handled, we should probably
keep the last arguments.

Do you think you can give this a go?

-- 
FATHER:       Make sure the Prince doesn't leave this room until I come and
              get him.
FIRST GUARD:  Not ... to leave the room ... even if you come and get him.
FATHER:       No.  Until I come and get him.
SECOND GUARD: Hic.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
It seems that this is caused by 8.0.0274 https://github.com/vim/vim/commit/070b33da93ad3a191664bb61f5ccc50781460c03.

I'm still not sure which part should be updated, `handle_drop()` or `update_single_line()`.

**Comment by brammool** [comment]
> It seems that this is caused by 8.0.0274 https://github.com/vim/vim/commit/070b33da93ad3a191664bb61f5ccc50781460c03.
> 
> I'm still not sure which part should be updated, `handle_drop()` or
> `update_single_line()`.

When handle_drop() sees that updating_screen is set, it should store the
arguments somewhere.  Then when updating_screen is reset, it should
check for these arguments and execute the actual drop code. 


-- 
"Shoot for the moon. Even if you miss, you'll land among the stars."

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
Please check if patch  8.1.0228 has fixed this problem.

**Comment by trackless** [comment]
@brammool It has been fixed. Thanks a lot!🎉
