### ISSUE TITLE
{Visual}["x]r{char} doesn't put text into "x

### ISSUE THREAD

**Issue by lkintact** [vim/vim#3247]
The `{Visual}["x]r{char}` command described at `:help v_r` doesn't put the replaced text into register `"x`. Maybe it shouldn't and the `["x]` part is just a typo, since the description - `Replace all selected characters by {char}.` - doesn't mention the optional register?

Vim: gvim_8.1.0200_x86.zip

**Comment by brammool** [comment]
Fixed by including #5906
