### ISSUE TITLE
Make possibility for hybrid line-numbering to enumerate wrapped lines

### ISSUE THREAD

**Issue by Hi-Angel** [vim/vim#3250]
When line-wrap enabled, line-numbering only enumerates through "hard", newline-ended, lines. It's okay for usual line-numbering; however with hybrid line-numbers it confuses, because when they show the difference, say, as `8` lines, the actual one is often bigger. 

Again, this might be okay for peoples rarely working with plain text in vim; but those who do typically remap `j` → `gj` and `k` → `gk`, otherwise movement is cumbersome *(e.g. I'm typing this text from an external gvim right now, and have 10 wrapped lines against 3 "hard" ones)*, and not having such lines counted confuses.

Also, Emacs have had `visual` option, e.g. `(setq-default display-line-numbers 'visual)` for that exact usecase since the very moment they merged hybrid line numbers.

**Comment by chrisbra** [comment]
But as line numbers do not differ between wrapped lines, it might confuse people when using ex commands, like `:s`. So that decision needs to be well designed. Perhaps using something like `24.0, 24.1, 24.2` might be possible to indicate that we are still on the same physical line.  Also not sure how this should work with `cpo+=n`

**Comment by JZL** [comment]
I have also encountered this issue (thanks @hi-angel for linking from https://vi.stackexchange.com/questions/4186/relative-numbers-sidepanel-with-wrapped-lines)

I think that the decimal lines sounds like a good solution for more advanced manipulations. But, I also think there is a case for simpler (if less systematically consistent) increasing integers, especially for movement. Maybe in addition to, or as a supporting/ergonomic hack for, the decimal place strategy. Because this issue comes from the nonstandard, if common, combination of relative line and `gj` -> `j`mapping, I don't mind if it's not perfectly systematically consistent to ex mode, especially because I feel like the decimal point is slightly less ergonimic and the current situation is confusing anyway

Thanks

**Comment by chrisbra** [comment]
I made a quick patch:
![grafik](https://user-images.githubusercontent.com/244927/43306783-975d8236-917c-11e8-9836-583c860ccfb7.png)

I don't like it.

**Comment by Hi-Angel** [comment]
@chrisbra it looks like you didn't enable relative/hybrid line numbering on screenshot. I don't think there's any benefit from enumerated line-wraps in case of vanilla numbering.

Purpose of vanilla numbering is usually tightly coupled with "hard" lines; like correlating compiler errors with your position in file. Purpose of relative/hybrid line numbers is a movement assistance.

**Comment by chrisbra** [comment]
Well, then think of relative numbering. Will look as ugly. And I bet this will confuse people.

**Comment by Hi-Angel** [comment]
> Well, then think of relative numbering. Will look as ugly. And I bet this will confuse people.

Look, I'm using it every day, it was never confusing, and definitely don't look ugly. Here's a shot:

![screenshot_20180727_103548](https://user-images.githubusercontent.com/7935057/43308047-d54b0936-9188-11e8-8236-6551793e94ee.png)

**Comment by chrisbra** [comment]
How do you know that the line numbers are physical line numbers and not screen line numbers? It's not easy to determine what address to use for ex commands. That is actually very confusing.

**Comment by Hi-Angel** [comment]
> How do you know that the line numbers are physical line numbers and not screen line numbers?

The number of the line with caret is always the physical number. E.g. if you're on 9-th physical line, and this line has 5 line-wraps — movement up and down between these "screen lines" always keeps the number 9.

**Comment by chrisbra** [comment]
I am closing this, as the feature does not seem to work well with Vims notion of addresses, e.g. in your case, one never knows what lines for example `2dd` would work on. Or how about `2j`? I think the feature would be too confusing and not very helpful.

**Comment by JZL** [comment]
I understand what you are saying but I think, especially for an optional flag, that the small amount of confusion would be okay (especially for users who opt into it) and it could be very helpful. I conducted a small survey of my other VIM using friends and they agree they think this would be helpful (that is far from conclusive). I agree with Hi-Angel  that the fact that the hybrid line numbers in the Emacs VIM emulators do this points to the usability of such a feature.

For examples like `2dd`, as long as it was consistent, I don't think it makes a difference whether it emulated the whole line (in the way `V` visual mode does) or only the current visual line (`v`). Also, even if this was limited to only navigation, not chained commands, I would find it helpful

**Comment by Hi-Angel** [comment]
> I am closing this, as the feature does not seem to work well with Vims
> notion of addresses, e.g. in your case, one never knows what lines for
> example 2dd would work on. Or how about 2j? I think the feature would be
> too confusing and not very helpful.

It just needs to be thought trough, that's it. E.g. it doesn't make sense to delete the line partially with <kbd>dd</kbd> because line-wrap would always be at random place. Hence <kbd>2dd</kbd> should delete instead 2 physical lines. The <kbd>2j</kbd> can be left as is, and then user could remap it to <kbd>2gj</kbd> if they want to move through visual lines *(which is what I did for Emacs-Evil)*.

But I'm not a Vim dev, I guess my vote doesn't mean much, whatever, more users to Emacs' Evil-mode then.
