### ISSUE TITLE
Copying from vim terminal adds newlines

### ISSUE THREAD

**Issue by sambanks** [vim/vim#3253]
Not sure if this is a bug or user error, but couldn't find anything in the help about it.

## Vim version:
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled May 13 2018 19:34:14)
Included patches: 1-1838
Compiled by Arch Linux
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    +tcl/dyn
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
+balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
+browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          +toolbar
+cindent           +insert_expand     +path_extra        +user_commands
+clientserver      +job               +perl/dyn          +vertsplit
+clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           +python/dyn        +vreplace
+conceal           +linebreak         +python3/dyn       +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       +lua/dyn           +ruby/dyn          +X11
+dialog_con_gui    +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             +xim
+digraphs          +modify_fname      +smartindent       -xpm
+dnd               +mouse             +startuptime       +xsmp_interact
-ebcdic            +mouseshape        +statusline        +xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              +mouse_gpm         +syntax            
+ex_extra          -mouse_jsbterm     +tag_binary        
+extra_search      +mouse_netterm     +tag_old_static    
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I
/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/libdrm -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-
1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -D_FORTIFY_SOURCE=2  -march=x8
6-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.26/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z
,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lfribidi -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE
 -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lelf -lnsl    -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.26/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-s
trong -L/usr/local/lib  -L/usr/lib/perl5/5.26/core_perl/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm     
```

When running a terminal via :term (which is an amazing addition!) I have an issue copying text to the system clipboard.

## Steps to reproduce
Open a terminal in a vim split window with :term
Generate some output that spans multiple lines
Enter normal mode with ctrl-w N
Scroll back to a multiline string
Select in visual mode
Copy to system clipboard
Navigate to empty window
paste

## Expected behavior
String on a single line

## Actual behavoir
A newline is inserted

## Extra context
The smaller the split the terminal is running in, and therefore the more lines the value spans, the more newlines you get in the copied value.

If I am doing it wrong, I would love some guidance.
Thanks

**Comment by brammool** [comment]
> Not sure if this is a bug or user error, but couldn't find anything in the help about it.
> 
> ## Vim version:
> ```
> VIM - Vi IMproved 8.0 (2016 Sep 12, compiled May 13 2018 19:34:14)
> Included patches: 1-1838
> Compiled by Arch Linux
> Huge version with GTK3 GUI.  Features included (+) or not (-):
> +acl               +farsi             +mouse_sgr         -tag_any_white
> +arabic            +file_in_path      -mouse_sysmouse    +tcl/dyn
> +autocmd           +find_in_path      +mouse_urxvt       +termguicolors
> -autoservername    +float             +mouse_xterm       +terminal
> +balloon_eval      +folding           +multi_byte        +terminfo
> +balloon_eval_term -footer            +multi_lang        +termresponse
> +browse            +fork()            -mzscheme          +textobjects
> ++builtin_terms    +gettext           +netbeans_intg     +timers
> +byte_offset       -hangul_input      +num64             +title
> +channel           +iconv             +packages          +toolbar
> +cindent           +insert_expand     +path_extra        +user_commands
> +clientserver      +job               +perl/dyn          +vertsplit
> +clipboard         +jumplist          +persistent_undo   +virtualedit
> +cmdline_compl     +keymap            +postscript        +visual
> +cmdline_hist      +lambda            +printer           +visualextra
> +cmdline_info      +langmap           +profile           +viminfo
> +comments          +libcall           +python/dyn        +vreplace
> +conceal           +linebreak         +python3/dyn       +wildignore
> +cryptv            +lispindent        +quickfix          +wildmenu
> +cscope            +listcmds          +reltime           +windows
> +cursorbind        +localmap          +rightleft         +writebackup
> +cursorshape       +lua/dyn           +ruby/dyn          +X11
> +dialog_con_gui    +menu              +scrollbind        -xfontset
> +diff              +mksession         +signs             +xim
> +digraphs          +modify_fname      +smartindent       -xpm
> +dnd               +mouse             +startuptime       +xsmp_interact
> -ebcdic            +mouseshape        +statusline        +xterm_clipboard
> +emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
> +eval              +mouse_gpm         +syntax            
> +ex_extra          -mouse_jsbterm     +tag_binary        
> +extra_search      +mouse_netterm     +tag_old_static    
>    system vimrc file: "/etc/vimrc"
>      user vimrc file: "$HOME/.vimrc"
>  2nd user vimrc file: "~/.vim/vimrc"
>       user exrc file: "$HOME/.exrc"
>   system gvimrc file: "/etc/gvimrc"
>     user gvimrc file: "$HOME/.gvimrc"
> 2nd user gvimrc file: "~/.vim/gvimrc"
>        defaults file: "$VIMRUNTIME/defaults.vim"
>     system menu file: "$VIMRUNTIME/menu.vim"
>   fall-back for $VIM: "/usr/share/vim"
> Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I
> /usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/libdrm -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-
> 1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -D_FORTIFY_SOURCE=2  -march=x8
> 6-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
> Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.26/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z
> ,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lfribidi -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE
>  -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lelf -lnsl    -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.26/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-s
> trong -L/usr/local/lib  -L/usr/lib/perl5/5.26/core_perl/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm     
> ```
> 
> When running a terminal via :term (which is an amazing addition!) I have an issue copying text to the system clipboard.
> 
> ## Steps to reproduce
> Open a terminal in a vim split window with :term
> Generate some output that spans multiple lines
> Enter normal mode with ctrl-w N
> Scroll back to a multiline string
> Select in visual mode
> Copy to system clipboard
> Navigate to empty window
> paste
> 
> ## Expected behavior
> String on a single line
> 
> ## Actual behavoir
> A newline is inserted
> 
> ## Extra context
> The smaller the split the terminal is running in, and therefore the more lines the value spans, the more newlines you get in the copied value.
> 
> If I am doing it wrong, I would love some guidance.

The information that the line wrapped because it was long is lost.  Thus
unfortunately it is not possible to copy (yank) the line as one, you
always get the screen lines.

-- 
Q: How does a UNIX Guru do Sex ?
A: unzip;strip;touch;finger;mount;fsck;more;yes;umount;sleep

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mortelle1806** [comment]
Ended up here because I experience the same problem and was considering it an issue. Any workaround would be appreciated.

**Comment by sambanks** [comment]
Thanks for the info Bram

**Comment by sambanks** [comment]
@mortelle1806  I was unable to find a useable workaround unfortunately.
