### ISSUE TITLE
In GVim on Ubuntu 18.04, the mouse pointer is replaced with one pixel instead of hidden

### ISSUE THREAD

**Issue by roryokane** [vim/vim#3256]
To reproduce:

1. Run `gvim --clean`
2. Move the mouse cursor over the GVim window
3. Press any key such as <kbd>w</kbd>

The `'mousehide'` setting is enabled by default, so the mouse cursor should be hidden at this point. Instead, the cursor seems to be replaced with a single black pixel at the point where a click would be registered. At least, I see a pixel there – I can’t confirm that the cursor *turns into* the pixel because, as desired, the mouse cursor restores itself to the normal pointer when I move it.

This black pixel is a problem because it looks like either a speck of dust on my screen or a dead pixel. I often notice it when typing and momentarily wonder “what is that?”, and many times I have tried to wipe it off my screen before I remembered what it was.

When the mouse is supposed to be hidden, I want the cursor to be completely invisible. If this is impossible, changing the cursor to a pixel the color of the background would be an improvement in most cases.

I have never seen this problem in GVim on Windows or MacVim on macOS. I also never seen this problem in other programs on this computer such as `gnome-terminal`.

Pressing <kbd>Ctrl</kbd>-<kbd>L</kbd> to redraw the window does not affect the cursor when it is being displayed as a single pixel. The pixel does not even flicker, unlike the text in the window.

## Screenshots

(My screenshot software cannot capture the pixel, so I recreated it in an image editor, in exactly the same place.)

![GVim with normal cursor, before typing](https://user-images.githubusercontent.com/79168/43350962-fd9d8412-91d9-11e8-9e99-0f7d50f1e338.png)

![GVim with one pixel where the cursor was after typing](https://user-images.githubusercontent.com/79168/43350963-febf3aca-91d9-11e8-9307-ce190fb2bcc8.png)

![GVim with one pixel where the cursor was after typing, annotated](https://user-images.githubusercontent.com/79168/43350966-ff7fdece-91d9-11e8-8ce5-daa567a7f1e3.png)

## Version information

**Operating system:** Ubuntu 18.04.1 LTS
**Graphical shell:** GNOME Shell 3.28.2 (unchanged from the default)

### Vim version

The `bugreport.txt` created with `:so $VIMRUNTIME/bugreport.vim` is pretty long, so I'll just paste the parts that look relevant:

~~~
uname -a
Linux roryokane-Precision-7510 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux


VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
Included patches: 1-1453
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl
+arabic
+autocmd
-autoservername
+balloon_eval
+balloon_eval_term
+browse
++builtin_terms
+byte_offset
+channel
+cindent
+clientserver
+clipboard
+cmdline_compl
+cmdline_hist
+cmdline_info
+comments
+conceal
+cryptv
+cscope
+cursorbind
+cursorshape
+dialog_con_gui
+diff
+digraphs
+dnd
-ebcdic
+emacs_tags
+eval
+ex_extra
+extra_search
+farsi
+file_in_path
+find_in_path
+float
+folding
-footer
+fork()
+gettext
-hangul_input
+iconv
+insert_expand
+job
+jumplist
+keymap
+lambda
+langmap
+libcall
+linebreak
+lispindent
+listcmds
+localmap
+lua
+menu
+mksession
+modify_fname
+mouse
+mouseshape
+mouse_dec
+mouse_gpm
-mouse_jsbterm
+mouse_netterm
+mouse_sgr
-mouse_sysmouse
+mouse_urxvt
+mouse_xterm
+multi_byte
+multi_lang
-mzscheme
+netbeans_intg
+num64
+packages
+path_extra
+perl
+persistent_undo
+postscript
+printer
+profile
-python
+python3
+quickfix
+reltime
+rightleft
-ruby
+scrollbind
+signs
+smartindent
+startuptime
+statusline
-sun_workshop
+syntax
+tag_binary
+tag_old_static
-tag_any_white
+tcl
+termguicolors
+terminal
+terminfo
+termresponse
+textobjects
+timers
+title
+toolbar
+user_commands
+vertsplit
+virtualedit
+visual
+visualextra
+viminfo
+vreplace
+wildignore
+wildmenu
+windows
+writebackup
+X11
-xfontset
+xim
+xpm
+xsmp_interact
+xterm_clipboard
-xterm_save
   system vimrc file: "
$VIM/vimrc"
     user vimrc file: "
$HOME/.vimrc"
 2nd user vimrc file: "
~/.vim/vimrc"
      user exrc file: "
$HOME/.exrc"
  system gvimrc file: "
$VIM/gvimrc"
    user gvimrc file: "
$HOME/.gvimrc"
2nd user gvimrc file: "
~/.vim/gvimrc"
       defaults file: "
$VIMRUNTIME/defaults.vim"
    system menu file: "
$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "
/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-NQEcoP/vim-8.0.1453=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -Wl,-E  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.26/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm     
--- Directories and Files ---
[…]
--- Options ---
[…]
  mousehide
[…]
  guicursor=n-v-c:block-Cursor/lCursor,ve:ver35-Cursor,o:hor50-Cursor,i-ci:ver25-Cursor/lCursor,r-cr:hor20-Cursor/lCursor,sm:block-Cursor-blinkwait175-blinkoff150-blinkon175
  guifont=Consolas:h16
  guioptions=aegimrLt
[…]
~~~

**Comment by roryokane** [comment]
By the way, pressing <kbd>Ctrl</kbd>-<kbd>L</kbd> to redraw the window does not affect the cursor when it is being displayed as a single pixel. The pixel does not even flicker, unlike the text in the window.

**Comment by b-nik** [comment]
Can confim for Ubuntu 20 and gvim 8.2-1897

**Comment by kstauffer** [comment]
Confirmed on Ubuntu 20 with vim 9.0-1455 compiled from source.
