### ISSUE TITLE
[Feature request] Ability of  add highlight group to none current buffer

### ISSUE THREAD

**Issue by chemzqm** [vim/vim#3260]
The function `matchaddpos()` and `matchadd()` doesn't take a buffer number, so I can't add highlight to none current buffer.  But language server could return diagnostic result  for none current buffer, so I can't highlight them with current vim's API.

It could be resolved by using the preserved dict argument for this purpose.

Thanks.

**Comment by brammool** [comment]
Qiming Zhao wrote:

> The function `matchaddpos()` and `matchadd()` doesn't take a buffer
> number, so I can't add highlight to none current buffer.  But language
> server could return diagnostic result  for none current buffer, so I
> can't highlight them with current vim's API.
> 
> It could be resolved by using the preserved dict argument for this purpose.

That's actually quite easy to implement.  I'll make a patch.

-- 
Proverb: A nightingale that forgets the lyrics is a hummingbird.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
