### ISSUE TITLE
Resetting "timeoutlen" with "<" wont default to the global setting

### ISSUE THREAD

**Issue by fcarlosjr** [vim/vim#3265]
Well, I believe the title says it all. Just open vim using `vim -N -u NONE` and then issue the commands:

```
set timeoutlen=500
setlocal timeoutlen=200
setlocal timeoutlen<
setlocal timeoutlen?
```

The last command above will print 200, not the global value (500).

The same goes if I do not set a global value at all:

```
setlocal timeoutlen=200
setlocal timeoutlen<
setlocal timeoutlen?
```
The last command will print 200, not the default value (1000).

My first three lines of  `vim --version` are

```
VIM - Vi IMproved 8.1 (2018 May 17, compiled May 25 2018 00:50:25)
Included patches: 1-22
Compiled by Arch Linux
```

**Comment by k-takata** [comment]
'timeoutlen' is a global option. So `:setlocal` works as the same as `:set`.

**Comment by fcarlosjr** [comment]
Ohh I see. Missed that, sorry!
