### ISSUE TITLE
The keywords for some options are absent in syntax/vim.vim 

### ISSUE THREAD

**Issue by lkintact** [vim/vim#3266]
The keywords for the options `'varsofttabstop'`/`'vsts'` and ` 'vartabstop'`/`'vts'` are absent from `syntax/vim.vim`, and, consequently, don't get highlighted.

Gvim: gvim_8.1.0224_x86.zip

**Comment by k-takata** [comment]
`syntax/vim.vim` won't be updated so frequently.
See [the comment](https://groups.google.com/d/topic/vim_use/jnTOOh26umQ/discussion) from the maintainer to [a similar issue](https://github.com/vim/vim/issues/2995).
(I really don't understand why he post an answer for GitHub issues to win_use (or somewhere else). People who read the issue cannot find the comment in vim_use.)

If you need more frequently updated one, please use this fork: https://github.com/vim-jp/syntax-vim-ex

**Comment by lkintact** [comment]
I see, thank you for the link to the fork! Not sure if I should close the issue, so leaving it open.

**Comment by chrisbra** [comment]
The issue will go away, once a newer syntax file is distributed with Vim. So closing.

**Comment by chrisbra** [comment]
https://github.com/vim/vim/commit/d2855f5454c5c6c5f786b228c5b67757edfefcb1 included an updated vim syntax file
