### ISSUE TITLE
GVim displays the ibus' suggestion window on wrong monitor

### ISSUE THREAD

**Issue by graywolf** [vim/vim#3268]
When using gvim, the little popup window showing suggestions while inputing japanese text (ibus + anthy) is in wrong place in multi-monitor setup.

If gvim is on eDP1, the popup is shown in correct place (basically in the buffer where I am writing). If gvim is on DP1, last letter is visible on left side of the right monitor, rest is on the left. To put here a picture (when trying to write てすと):

```
-------------++--------------
             ||            |
         てす||と          |
             ||            | GVim window
  eDP1       ||       DP1  | is here
             ||            | 
             ||            |
             ||            |
-------------++--------------

```

I'm using tiling WM (i3) is relevant (probably).

Vim works correctly (I assume since this is handled by terminal and not by vim itself in that case).

```
   $ xrandr
Screen 0: minimum 8 x 8, current 3840 x 1080, maximum 32767 x 32767
eDP1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 310mm x 170mm
   1920x1080     60.02*+  59.93    48.00  
   1680x1050     59.88  
   1400x1050     59.98  
   1600x900      60.00    59.95    59.82  
   1280x1024     60.02  
   1400x900      59.96    59.88  
   1280x960      60.00  
   1368x768      60.00    59.88    59.85  
   1280x800      59.81    59.91  
   1280x720      59.86    60.00    59.74  
   1024x768      60.00  
   1024x576      60.00    59.90    59.82  
   960x540       60.00    59.63    59.82  
   800x600       60.32    56.25  
   864x486       60.00    59.92    59.57  
   640x480       59.94  
   720x405       59.51    60.00    58.99  
   640x360       59.84    59.32    60.00  
DP1 connected 1920x1080+1920+0 (normal left inverted right x axis y axis) 530mm x 300mm
   1920x1080     60.00*+  50.00    59.94  
   1920x1080i    60.00    50.00    59.94  
   1680x1050     59.88  
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1280x800      59.91  
   1152x864      75.00  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    60.00  
   832x624       74.55  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00    60.00    59.94  
   720x400       70.08  
DP2 disconnected (normal left inverted right x axis y axis)
HDMI1 disconnected (normal left inverted right x axis y axis)
HDMI2 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)

```

```
   $ uname -a
Linux ws 4.17.8-1-ARCH #1 SMP PREEMPT Wed Jul 18 09:56:24 UTC 2018 x86_64 GNU/Linux
```

```
   $ gvim --version
VIM - Vi IMproved 8.1 (2018 May 17, compiled May 25 2018 00:50:25)
Included patches: 1-22
Compiled by Arch Linux
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    +tcl/dyn
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
+balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
+browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          +toolbar
+cindent           +insert_expand     +path_extra        +user_commands
+clientserver      +job               +perl/dyn          +vertsplit
+clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           +python/dyn        +vreplace
+conceal           +linebreak         +python3/dyn       +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       +lua/dyn           +ruby/dyn          +X11
+dialog_con_gui    +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             +xim
+digraphs          +modify_fname      +smartindent       -xpm
+dnd               +mouse             +startuptime       +xsmp_interact
-ebcdic            +mouseshape        +statusline        +xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              +mouse_gpm         +syntax            
+ex_extra          -mouse_jsbterm     +tag_binary        
+extra_search      +mouse_netterm     +tag_old_static    
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/libdrm -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.26/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lfribidi -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lelf -lnsl    -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.26/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/5.26/core_perl/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm     
```

**Comment by graywolf** [comment]
Looking in the help I found `imstyle` setting. I have `imstyle=1` (since I'm not setting it, it's probably default?). Changing to `imstyle=0` makes it work as expected.

**Comment by k-takata** [comment]
How about this patch?
https://bitbucket.org/k_takata/vim-ktakata-mq/src/ca919fb0c158b74883902ccbbcb2b8f3af4edf52/fix-gtk-multidisplay-support.patch?fileviewer=file-view-default
Not tested well, though.

**Comment by graywolf** [comment]
Assuming I applied the patch correctly

	patch -p1 < fix-gtk.patch

and compiled

	./configure --with-features=big --enable-gui --with-x
	make

and tried it

	./src/vim -g -u NONE

it does not seem to work. I will find time over the weekend to try
to debug it.

**Comment by k-takata** [comment]
Then how about changing the following line in `im_preedit_window_set_position()` in `mbyte.c`

```C
    gui_gtk_get_screen_geom_of_win(preedit_window, &sx, &sy, &sw, &sh);
```

to

```C
    gui_gtk_get_screen_geom_of_win(gui.drawarea, &sx, &sy, &sw, &sh);
```

after applying my patch?

**Comment by graywolf** [comment]
Great! It works like this. So patch fixing this issue seems to be

	diff --git a/src/gui_beval.c b/src/gui_beval.c
	index 49694cfdd..03216008e 100644
	--- a/src/gui_beval.c
	+++ b/src/gui_beval.c
	@@ -944,6 +944,8 @@ drawBalloon(BalloonEval *beval)
		GtkRequisition  requisition;
		int             screen_w;
		int             screen_h;
	+       int             screen_x;
	+       int             screen_y;
		int             x;
		int             y;
		int             x_offset = EVAL_OFFSET_X;
	@@ -956,8 +958,8 @@ drawBalloon(BalloonEval *beval)
		screen = gtk_widget_get_screen(beval->target);
		gtk_window_set_screen(GTK_WINDOW(beval->balloonShell), screen);
	 # endif
	-       gui_gtk_get_screen_size_of_win(beval->balloonShell,
	-                                                        &screen_w, &screen_h);
	+       gui_gtk_get_screen_geom_of_win(beval->balloonShell,
	+                                   &screen_x, &screen_y, &screen_w, &screen_h);
	 # if !GTK_CHECK_VERSION(3,0,0)
		gtk_widget_ensure_style(beval->balloonShell);
		gtk_widget_ensure_style(beval->balloonLabel);
	@@ -998,14 +1000,16 @@ drawBalloon(BalloonEval *beval)
		y += beval->y;
	 
		/* Get out of the way of the mouse pointer */
	-       if (x + x_offset + requisition.width > screen_w)
	+       if (x + x_offset + requisition.width > screen_x + screen_w)
		    y_offset += 15;
	-       if (y + y_offset + requisition.height > screen_h)
	+       if (y + y_offset + requisition.height > screen_y + screen_h)
		    y_offset = -requisition.height - EVAL_OFFSET_Y;
	 
		/* Sanitize values */
	-       x = CLAMP(x + x_offset, 0, MAX(0, screen_w - requisition.width));
	-       y = CLAMP(y + y_offset, 0, MAX(0, screen_h - requisition.height));
	+       x = CLAMP(x + x_offset, 0,
	+                           MAX(0, screen_x + screen_w - requisition.width));
	+       y = CLAMP(y + y_offset, 0,
	+                           MAX(0, screen_y + screen_h - requisition.height));
	 
		/* Show the balloon */
	 # if GTK_CHECK_VERSION(3,0,0)
	diff --git a/src/gui_gtk_x11.c b/src/gui_gtk_x11.c
	index 9c7e8d564..87679da5d 100644
	--- a/src/gui_gtk_x11.c
	+++ b/src/gui_gtk_x11.c
	@@ -4976,27 +4976,35 @@ gui_mch_set_shellsize(int width, int height,
	 }
	 
	     void
	-gui_gtk_get_screen_size_of_win(GtkWidget *wid, int *width, int *height)
	+gui_gtk_get_screen_geom_of_win(
	+       GtkWidget *wid,
	+       int *x,
	+       int *y,
	+       int *width,
	+       int *height)
	 {
	+    GdkRectangle geometry;
	+    GdkWindow *win = gtk_widget_get_window(wid);
	 #if GTK_CHECK_VERSION(3,22,0)
	     GdkDisplay *dpy = gtk_widget_get_display(wid);
	-    GdkWindow *win = gtk_widget_get_window(wid);
	     GdkMonitor *monitor = gdk_display_get_monitor_at_window(dpy, win);
	-    GdkRectangle geometry;
	 
	     gdk_monitor_get_geometry(monitor, &geometry);
	-    *width = geometry.width;
	-    *height = geometry.height;
	 #else
	     GdkScreen* screen;
	+    int monitor;
	 
	     if (wid != NULL && gtk_widget_has_screen(wid))
		screen = gtk_widget_get_screen(wid);
	     else
		screen = gdk_screen_get_default();
	-    *width = gdk_screen_get_width(screen);
	-    *height = gdk_screen_get_height(screen);
	+    monitor = gdk_screen_get_monitor_at_window(screen, win);
	+    gdk_screen_get_monitor_geometry(screen, monitor, &geometry);
	 #endif
	+    *x = geometry.x;
	+    *y = geometry.y;
	+    *width = geometry.width;
	+    *height = geometry.height;
	 }
	 
	 /*
	@@ -5007,7 +5015,9 @@ gui_gtk_get_screen_size_of_win(GtkWidget *wid, int *width, int *height)
	     void
	 gui_mch_get_screen_dimensions(int *screen_w, int *screen_h)
	 {
	-    gui_gtk_get_screen_size_of_win(gui.mainwin, screen_w, screen_h);
	+    int            x, y;
	+
	+    gui_gtk_get_screen_geom_of_win(gui.mainwin, &x, &y, screen_w, screen_h);
	 
	     /* Subtract 'guiheadroom' from the height to allow some room for the
	      * window manager (task list and window title bar). */
	diff --git a/src/mbyte.c b/src/mbyte.c
	index 96b39b411..2a0a95ae6 100644
	--- a/src/mbyte.c
	+++ b/src/mbyte.c
	@@ -4951,12 +4951,12 @@ im_add_to_input(char_u *str, int len)
	      static void
	 im_preedit_window_set_position(void)
	 {
	-    int x, y, w, h, sw, sh;
	+    int x, y, w, h, sx, sy, sw, sh;
	 
	     if (preedit_window == NULL)
		return;
	 
	-    gui_gtk_get_screen_size_of_win(preedit_window, &sw, &sh);
	+    gui_gtk_get_screen_geom_of_win(gui.drawarea, &sx, &sy, &sw, &sh);
	 #if GTK_CHECK_VERSION(3,0,0)
	     gdk_window_get_origin(gtk_widget_get_window(gui.drawarea), &x, &y);
	 #else
	@@ -4965,10 +4965,10 @@ im_preedit_window_set_position(void)
	     gtk_window_get_size(GTK_WINDOW(preedit_window), &w, &h);
	     x = x + FILL_X(gui.col);
	     y = y + FILL_Y(gui.row);
	-    if (x + w > sw)
	-       x = sw - w;
	-    if (y + h > sh)
	-       y = sh - h;
	+    if (x + w > sx + sw)
	+       x = sx + sw - w;
	+    if (y + h > sy + sh)
	+       y = sy + sh - h;
	     gtk_window_move(GTK_WINDOW(preedit_window), x, y);
	 }
	 
	diff --git a/src/proto/gui_gtk_x11.pro b/src/proto/gui_gtk_x11.pro
	index aea8d0b68..af2c1f133 100644
	--- a/src/proto/gui_gtk_x11.pro
	+++ b/src/proto/gui_gtk_x11.pro
	@@ -25,7 +25,7 @@ int gui_mch_maximized(void);
	 void gui_mch_unmaximize(void);
	 void gui_mch_newfont(void);
	 void gui_mch_set_shellsize(int width, int height, int min_width, int min_height, int base_width, int base_height, int direction);
	-void gui_gtk_get_screen_size_of_win(GtkWidget *wid, int *width, int *height);
	+void gui_gtk_get_screen_geom_of_win(GtkWidget *wid, int *x, int *y, int *width, int *height);
	 void gui_mch_get_screen_dimensions(int *screen_w, int *screen_h);
	 void gui_mch_settitle(char_u *title, char_u *icon);
	 void gui_mch_enable_menu(int showit);

Thank you very much :)

**Comment by k-takata** [comment]
Thank you for trying the patch. I also updated it:
https://bitbucket.org/k_takata/vim-ktakata-mq/src/b1eb281199d3af2039a535d8da55fbefb3878e66/fix-gtk-multidisplay-support.patch?fileviewer=file-view-default
