### ISSUE TITLE
Vim source window fails to update with mappings

### ISSUE THREAD

**Issue by joterway** [vim/vim#3269]
GDB works well for me when I switch to the GDB window by hand, enter "up", then move down to the source window again. When I attempt to create a mapping for it, however, the source window fails to jump to the current location.

```
map ,u <C-W><Up>up<nl><C-W><Down>
```

The cursor in the source file stays in the same spot. Hitting return seems to cause it to move to the current location.

**Comment by k-takata** [comment]
(I edited your comment. It wasn't shown properly because of the markdown notation.)

**Comment by chrisbra** [comment]
Are you talking about the termdebug plugin?

**Comment by joterway** [comment]
yes

**Comment by chrisbra** [comment]
So you are trying to mix normal mode mappings with terminal mode mappings. I am not sure this can be done. It might need a combination of `:map` and `:tmap` commands.

**Comment by brammool** [comment]
The mapping works fine for me.  Perhaps try :noremap

**Comment by joterway** [comment]
No difference to me using :noremap. As I move up/down the stack, the file
in the source window changes but the lines shown does not. If I move, then
vim remembers the location I moved to so like line ~800 in one file or line
~3000 in another file, even though the program is not at either of those
locations.

Would it help to see a video of it?

**Comment by brammool** [comment]
> No difference to me using :noremap. As I move up/down the stack, the file
> in the source window changes but the lines shown does not. If I move, then
> vim remembers the location I moved to so like line ~800 in one file or line
> ~3000 in another file, even though the program is not at either of those
> locations.

Try adding a "redraw" command at the end.

-- 
ARTHUR:  I am your king!
WOMAN:   Well, I didn't vote for you.
ARTHUR:  You don't vote for kings.
WOMAN:   Well, 'ow did you become king then?
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by joterway** [comment]
Still no luck :( Typing any key causes the window to jump to the right
location though.

noremap ,u <C-W><Up>up<nl><C-W><Down>:redraw<nl>

**Comment by chrisbra** [comment]
can you please try to come up with a reproducible example? Try with Vims source code and start with `vim --clean -c 'packadd termdebug' -c "Termdebug vim"` (e.g. from the src/ directory of Vims source code).

**Comment by lacygoill** [comment]
Any update on the minimal reproducible example?

**Comment by joterway** [comment]
Sorry, I got distracted. It seems to have been fixed in the mean time.

**Comment by lacygoill** [comment]
> It seems to have been fixed in the mean time.

So I guess the issue can be closed.
