### ISSUE TITLE
function MyDiff() harms :diffupdate - screen not drawn

### ISSUE THREAD

**Issue by studog-github** [vim/vim#3274]
In `:he diff-diffexpr` there is an example `diffexpr` function:

> Example (this does almost the same as 'diffexpr' being empty): > 
> 
>         set diffexpr=MyDiff()
>         function MyDiff()
>            let opt = ""
>            if &diffopt =~ "icase"
>              let opt = opt . "-i "
>            endif
>            if &diffopt =~ "iwhite"
>              let opt = opt . "-b "
>            endif
>            silent execute "!diff -a --binary " . opt . v:fname_in . " " . v:fname_new .
>                 \  " > " . v:fname_out
>         endfunction
> 

This function causes the screen to not redraw after a `:diffupdate` command is issued.

Steps to reproduce:
1. Use attached files. [bugreport.tar.gz](https://github.com/vim/vim/files/2258753/bugreport.tar.gz)
2. `vimdiff -N --noplugin -u .test.vimrc -U NONE -i NONE a b`
3. `:diffupdate`
4. Observe screen is blank.
5. `ctrl-l` (Ctrl plus L)
6. Observe screen is redrawn correctly.

For contrast, this sequence does NOT produce the bug:
2. `vimdiff -N --noplugin -u NONE -U NONE -i NONE a b`
3. `:diffupdate`
4. Observe screen is drawn.

A sanitized `:so $VIMRUNTIME/bugreport.vim` is included in the attached zip.

I found this because I have a slightly modified copy of `MyDiff()` in my .vimrc.
I think this is a regression on Vim 8.0, but I'm not 100% sure about that.

Further info:

> user@histname:\~/vimbug$ lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 18.04.1 LTS
> Release:	18.04
> Codename:	bionic
> user@hostname:\~/vimbug$ vim --version
> VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
> Included patches: 1-1453
> Modified by pkg-vim-maintainers@lists.alioth.debian.org
> Compiled by pkg-vim-maintainers@lists.alioth.debian.org
> Huge version without GUI.  Features included (+) or not (-):
> +acl               +farsi             +mouse_sgr         -tag_any_white
> +arabic            +file_in_path      -mouse_sysmouse    -tcl
> +autocmd           +find_in_path      +mouse_urxvt       +termguicolors
> -autoservername    +float             +mouse_xterm       +terminal
> -balloon_eval      +folding           +multi_byte        +terminfo
> +balloon_eval_term -footer            +multi_lang        +termresponse
> -browse            +fork()            -mzscheme          +textobjects
> ++builtin_terms    +gettext           +netbeans_intg     +timers
> +byte_offset       -hangul_input      +num64             +title
> +channel           +iconv             +packages          -toolbar
> +cindent           +insert_expand     +path_extra        +user_commands
> -clientserver      +job               -perl              +vertsplit
> -clipboard         +jumplist          +persistent_undo   +virtualedit
> +cmdline_compl     +keymap            +postscript        +visual
> +cmdline_hist      +lambda            +printer           +visualextra
> +cmdline_info      +langmap           +profile           +viminfo
> +comments          +libcall           -python            +vreplace
> +conceal           +linebreak         +python3           +wildignore
> +cryptv            +lispindent        +quickfix          +wildmenu
> +cscope            +listcmds          +reltime           +windows
> +cursorbind        +localmap          +rightleft         +writebackup
> +cursorshape       -lua               -ruby              -X11
> +dialog_con        +menu              +scrollbind        -xfontset
> +diff              +mksession         +signs             -xim
> +digraphs          +modify_fname      +smartindent       -xpm
> -dnd               +mouse             +startuptime       -xsmp
> -ebcdic            -mouseshape        +statusline        -xterm_clipboard
> +emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
> +eval              +mouse_gpm         +syntax            
> +ex_extra          -mouse_jsbterm     +tag_binary        
> +extra_search      +mouse_netterm     +tag_old_static    
>    system vimrc file: "$VIM/vimrc"
>      user vimrc file: "$HOME/.vimrc"
>  2nd user vimrc file: "~/.vim/vimrc"
>       user exrc file: "$HOME/.exrc"
>        defaults file: "$VIMRUNTIME/defaults.vim"
>   fall-back for $VIM: "/usr/share/vim"
> Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-NQEcoP/vim-8.0.1453=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
> Linking: gcc   -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl     -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -lpthread -ldl -lutil -lm      
>

**Comment by brammool** [comment]
> In `:he diff-diffexpr` there is an example `diffexpr` function:
> 
> > Example (this does almost the same as 'diffexpr' being empty): > 
> > 
> >         set diffexpr=MyDiff()
> >         function MyDiff()
> >            let opt = ""
> >            if &diffopt =~ "icase"
> >              let opt = opt . "-i "
> >            endif
> >            if &diffopt =~ "iwhite"
> >              let opt = opt . "-b "
> >            endif
> >            silent execute "!diff -a --binary " . opt . v:fname_in . " " . v:fname_new .
> >                 \  " > " . v:fname_out
> >         endfunction
> > 
> 
> This function causes the screen to not redraw after a `:diffupdate` command is issued.
> 
> Steps to reproduce:
> 1. Use attached files. [bugreport.tar.gz](https://github.com/vim/vim/files/2258753/bugreport.tar.gz)
> 2. `vimdiff -N --noplugin -u .test.vimrc -U NONE -i NONE a b`
> 3. `:diffupdate`
> 4. Observe screen is blank.
> 5. `ctrl-l` (Ctrl plus L)
> 6. Observe screen is redrawn correctly.
> 
> For contrast, this sequence does NOT produce the bug:
> 2. `vimdiff -N --noplugin -u NONE -U NONE -i NONE a b`
> 3. `:diffupdate`
> 4. Observe screen is drawn.
> 
> A sanitized `:so $VIMRUNTIME/bugreport.vim` is included in the attached zip.
> 
> I found this because I have a slightly modified copy of `MyDiff()` in my .vimrc.
> I think this is a regression on Vim 8.0, but I'm not 100% sure about that.

It's not a regression, must have happened always.

The problem is the "silent" before the shell command.  This only works
if the shell command doesn't change the screen content.  But if
executing the shell does change the screen, it won't be redrawn.

If your t_ti and t_te termpcap options are set, try making them empty:

	set t_ti= t_te=

Or just add a redraw command after executing the diff.

-- 
MARTHA'S WAY: Don't throw out all that leftover wine. Freeze into ice cubes
              for future use in casseroles and sauces.
MY WAY:       What leftover wine?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
