### ISSUE TITLE
Patch 236 on 8.1 introduced a build error on older platforms: undefined reference to `rb_intern2`

### ISSUE THREAD

**Issue by fusion809** [vim/vim#3275]
Hi,

On Red Hat Enterprise Linux 6/7 (and derivatives thereof like Scientific and CentOS), SUSE Linux Enterprise 12 and openSUSE 42.3 release 8.1.0236 introduced the build error:

```bash
[  160s] terminal.c:3968: warning: ignoring return value of 'fwrite', declared with attribute warn_unused_result
[  160s] gcc -std=gnu99 -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12     -O2 -g -pipe -Wall -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/ui.o ui.c
[  161s] gcc -std=gnu99 -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12     -O2 -g -pipe -Wall -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/undo.o undo.c
[  161s] gcc -std=gnu99 -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12     -O2 -g -pipe -Wall -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/userfunc.o userfunc.c
[  161s] gcc -std=gnu99 -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12     -O2 -g -pipe -Wall -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/window.o window.c
[  161s] undo.c: In function 'undo_time':
[  161s] undo.c:2273: warning: 'nomark' may be used uninitialized in this function
[  162s] gcc -std=gnu99 -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12     -O2 -g -pipe -Wall -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/gui.o gui.c
[  162s] gcc -std=gnu99 -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12     -O2 -g -pipe -Wall -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/gui_gtk.o gui_gtk.c
[  162s] gcc -std=gnu99 -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12     -O2 -g -pipe -Wall -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/gui_gtk_x11.o gui_gtk_x11.c
[  163s] gcc -std=gnu99 -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12     -O2 -g -pipe -Wall -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/gui_gtk_f.o gui_gtk_f.c
[  163s] gcc -std=gnu99 -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12     -O2 -g -pipe -Wall -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/gui_beval.o gui_beval.c
[  164s] gcc -std=gnu99 -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12     -O2 -g -pipe -Wall -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        version.c -o objects/version.o
[  165s] link.sh: $LINK_AS_NEEDED set to 'yes': invoking linker directly.
[  165s]   gcc -std=gnu99   -L. -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/CORE   -L/usr/local/lib -Wl,--as-needed 	-o vim objects/arabic.o objects/beval.o objects/buffer.o objects/blowfish.o objects/crypt.o objects/crypt_zip.o objects/dict.o objects/diff.o objects/digraph.o objects/edit.o objects/eval.o objects/evalfunc.o objects/ex_cmds.o objects/ex_cmds2.o objects/ex_docmd.o objects/ex_eval.o objects/ex_getln.o objects/farsi.o objects/fileio.o objects/fold.o objects/getchar.o objects/hardcopy.o objects/hashtab.o  objects/if_cscope.o objects/if_xcmdsrv.o objects/list.o objects/mark.o objects/memline.o objects/menu.o objects/misc1.o objects/misc2.o objects/move.o objects/mbyte.o objects/normal.o objects/ops.o objects/option.o objects/os_unix.o objects/pathdef.o objects/popupmnu.o objects/pty.o objects/quickfix.o objects/regexp.o objects/screen.o objects/search.o objects/sha256.o objects/spell.o objects/spellfile.o objects/syntax.o objects/tag.o objects/term.o objects/terminal.o objects/ui.o objects/undo.o objects/userfunc.o objects/version.o objects/window.o objects/gui.o objects/gui_gtk.o objects/gui_gtk_x11.o objects/gui_gtk_f.o objects/gui_beval.o  objects/term_encoding.o objects/term_keyboard.o objects/term_mouse.o objects/term_parser.o objects/term_pen.o objects/term_screen.o objects/term_state.o objects/term_unicode.o objects/term_vterm.o objects/if_lua.o  objects/if_perl.o objects/if_perlsfio.o objects/if_python.o   objects/if_ruby.o   objects/netbeans.o objects/channel.o  objects/charset.o objects/json.o objects/main.o objects/memfile.o objects/message.o   -pthread -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lgdk_pixbuf-2.0 -lpangocairo-1.0 -lcairo -lpango-1.0 -lfreetype -lfontconfig -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lrt -lglib-2.0   -lSM -lICE -lXpm -lXt -lX11 -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr   -Wl,-E -Wl,-rpath,/usr/lib/perl5/CORE  -fstack-protector -L/usr/local/lib  -L/usr/lib/perl5/CORE -lperl -lresolv -lnsl -ldl -lm -lcrypt -lutil -lpthread -lc        
[  165s] objects/if_ruby.o: In function `error_print':
[  165s] /home/abuild/rpmbuild/BUILD/vim-8.1.0236/src/if_ruby.c:1030: undefined reference to `rb_intern2'
[  165s] collect2: ld returned 1 exit status
[  165s] link.sh: Linking failed
[  165s] make: *** [vim] Error 1
```

(full log is https://pastebin.com/xax8vt58). Packaging files for this failed build are https://build.opensuse.org/package/show/home:fusion809/vim-redhat. 

The versions of Ruby they are using are:

* 1.8.x (RHEL 6)
* 2.0.x (RHEL 7)
* 2.1.x (openSUSE 42.3/SLE 12)

The question is really whether this is a bug you's should handle upstream or I should by merely reversing this patch on my builds of Vim. I'm a believer of upstreaming wherever possible to minimize work down the track overall, but not all platforms experience this build issue (e.g. Ubuntu 14.04 doesn't, nor does Debian 8 nor do newer distros like Fedora 27/28, openSUSE 15, _etc._) so I can see the argument to myself and other Vim packagers merely handling this downstream. 

Thanks for your time,
Brenton

**Comment by tonymec** [comment]
I don't know about RedHat but openSUSE 42.3 is slated for EOL 2019-01-31. The "current stable" openSUSE release is 15.0 released 2018-05-25 (yes, 15 follows 42) where I just compiled a Huge gvim 8.1.236 with (among others) Ruby; and it had no errors. My ruby and ruby-devel packages seem to be metapackages: all they do is "require" ruby2.5 and ruby2.5-devel, version >= 2.5.0. My version of the latter two is 2.5.0-lp150.2.11 where the part after the dash is an "openSUSE build number".

I'm not sure the SUSE developers will do anything about a problem which is only seen on the last-but-one OS version, which will be EOL in six months, but not on the current release; and that only when trying to home-compile a program (gvim) which already exists in the distribution (on 15.0 it is package "gvim"; on earlier openSUSE releases it could be either the same, or "vim-x11" or "vim-gui" or something like that).

Of course you can always try opening a bug about it at https://bugzila.opensuse.org/ but, well… ma`a-sha'a-llah (in my native French it bears bad luck to wish good luck so I won't; instead: "je te dis merde".)

**Comment by fusion809** [comment]
Ah, thanks for trying to help but I'm not sure you read my report in full, or at least, I think you paid attention to some bits but ignored others.  

Firstly, I implied openSUSE 15 was a newer distro than openSUSE 42.3 (classed 42.3 with older platforms on which Vim didn't build correctly and mentioned 15 as a newer distro for which it builds fine, from that you can extrapolate I knew 42.3 is older than 15), so you didn't need to explain that. 

Secondly, I'm the one doing the packaging here, not openSUSE developers so I wouldn't be reporting to them, reporting to them would be more appropriate if they were the packagers of the problem package and I experienced a runtime error with their package. So I don't need to report it there. I'm reporting this issue here because: 

1. I'd like to keep packaging Vim for openSUSE 42.3 until it goes EOL, as well as these other platforms, so it'd be great if this could be fixed. 
2. I won't be the only packager experiencing this, or at least not if we give it enough time. Of course, my Vim packages are bleeding-edge, and most other packagers don't update their Vim packages as often as I do, but given how long their (RHEL 6/7 + SLE 12) support cycle is I would expect someone else to attempt to build this version of Vim or later on these distros before they go EOL and hence potentially experience the same build error.
3. openSUSE 42.3 isn't the only distribution I've been packaging for, which you would also know if you read my report in full, and the other distros I've been packaging for have much more support left in them than openSUSE 42.3. For example, while openSUSE 42.3 will be EOL in 6 months, SLE 12 which shares a fair bit of its codebase won't be EOL for almost a decade (LTSS support ends in October 2027).

**Comment by tonymec** [comment]
Ah, I didn't realize you were the guy packaging Vim for SUSE and other distros. Sorry.

**Comment by fusion809** [comment]
I don't think I'd be complaining of a build error unless I was. Runtime error perhaps, but not build error. But we all make mistakes, so apology accepted.

**Comment by tonymec** [comment]
Other people, other mores. I don't package Vim for anyone but myself, but when I notice a build error or even a compiler warning, I report it on the vim_dev list so Bram knows about it. (If an error doesn't get reported it remains in the code.) Time and again this led to the discovery of a missing #ifdef. What led me astray was your talk of upstream and downstream and where should the problem be reported. IMHO here (or on vim_dev where these issues are mirrored) was the right place for a build error.

**Comment by k-takata** [comment]
Do you use +ruby/dyn?
I'm not sure why it fails, but how about the following patch?

```diff
--- a/src/if_ruby.c
+++ b/src/if_ruby.c
@@ -254,9 +254,8 @@ static void ruby_vim_init(void);
 # define rb_hash_new			dll_rb_hash_new
 # define rb_inspect			dll_rb_inspect
 # define rb_int2inum			dll_rb_int2inum
-# ifndef rb_intern
-#  define rb_intern			dll_rb_intern
-# endif
+# undef rb_intern
+# define rb_intern			dll_rb_intern
 # ifdef RUBY_CONST_ID_CACHE
 #  define rb_intern2			dll_rb_intern2
 # endif
```

**Comment by fusion809** [comment]
It worked perfectly, thanks. Tested on CentOS 7, openSUSE Leap 42.3 and Tumbleweed (tested on Tumbleweed even though this bug only affect older platforms and not Tumbleweed because I wanted to see if it stuffed things up on these more up-to-date platforms).

**Comment by brammool** [comment]
Ken Takata wrote:

> Do you use +ruby/dyn?
> I'm not sure why it fails, but how about the following patch?
> 
> ```diff
> --- a/src/if_ruby.c
> +++ b/src/if_ruby.c
> @@ -254,9 +254,8 @@ static void ruby_vim_init(void);
>  # define rb_hash_new			dll_rb_hash_new
>  # define rb_inspect			dll_rb_inspect
>  # define rb_int2inum			dll_rb_int2inum
> -# ifndef rb_intern
> -#  define rb_intern			dll_rb_intern
> -# endif
> +# undef rb_intern
> +# define rb_intern			dll_rb_intern
>  # ifdef RUBY_CONST_ID_CACHE
>  #  define rb_intern2			dll_rb_intern2
>  # endif
> ```

Hmm, is it really a good idea to overrule defines from the header file?
I guess what it's doing is an optimization.

Actually, not using the "define rb_intern" won't work anyway with
dynamic loading, because dll_rb_intern must be used.

#define rb_intern(str) \
    (__builtin_constant_p(str) ? \
        __extension__ (RUBY_CONST_ID_CACHE((ID), (str))) : \
        rb_intern(str))

So when "__builtin_constant_p(str)" is false it would fail, since it's
calling rb_intern() which does not exist.  We currently only call it for
one constant string, so it *might* work.

It's tricky, but your solution appears to be best.  We don't need
rb_intern2 at all then.

-- 
Trees moving back and forth is what makes the wind blow.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
Brenton Horne wrote:

> On Red Hat Enterprise Linux 6/7 (and derivatives thereof like Scientific =
> and CentOS), SUSE Linux Enterprise 12 and openSUSE 42.3 release 8.1.0236 =
> introduced the build error:
> 
> [...]
> 
> [  165s] objects/if_ruby.o: In function `error_print':
> [  165s] /home/abuild/rpmbuild/BUILD/vim-8.1.0236/src/if_ruby.c:1030: und=
> efined reference to `rb_intern2'
> ```
> 
> (full log is https://pastebin.com/xax8vt58). Packaging files for this fai=
> led build are https://build.opensuse.org/package/show/home:fusion809/vim-=
> redhat. =
> 
> 
> The versions of Ruby they are using are:
> 
> * 1.8.x (RHEL 6)
> * 2.0.x (RHEL 7)
> * 2.1.x (openSUSE 42.3/SLE 12)
> 
> The question is really whether this is a bug you's should handle upstream=
>  or I should by merely reversing this patch on my builds of Vim. I'm a be=
> liever of upstreaming wherever possible to minimize work down the track o=
> verall, but not all platforms experience this build issue (e.g. Ubuntu 14=
> .04 doesn't, nor does Debian 8 nor do newer distros like Fedora 27/28, op=
> enSUSE 15, _etc._) so I can see the argument to myself and other Vim pack=
> agers merely handling this downstream. =

Vim actually doesn't use rb_intern2().  It does use rb_intern() and some
header file has a macro that then calls rb_intern2().  I added this,
which works on Ubuntu:

# ifdef RUBY_CONST_ID_CACHE
#  define rb_intern2			dll_rb_intern2
# endif

# ifdef RUBY_CONST_ID_CACHE
    {"rb_intern2", (RUBY_PROC*)&dll_rb_intern2},
# endif

The macro in ruby.h is:

#define rb_intern(str) \
    (__builtin_constant_p(str) ? \
        __extension__ (RUBY_CONST_ID_CACHE((ID), (str))) : \
        rb_intern(str))

And:

#define RUBY_CONST_ID_CACHE(result, str)		\
    {							\
	static ID rb_intern_id_cache;			\
	if (!rb_intern_id_cache)			\
	    rb_intern_id_cache = rb_intern2((str), (long)strlen(str)); \
	result rb_intern_id_cache;			\
    }

I cannot guess how to check if rb_intern2() can be used and/or is
needed.  We probably need to find out in which version it was added.

-- 
5 out of 4 people have trouble with fractions.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
