### ISSUE TITLE
g:actual_curbuf is not set when `statusline` is set via a wrapper function

### ISSUE THREAD

**Issue by blueyed** [vim/vim#3279]
Given `t-actual_curbuf.vim`:

```vim
function! Wrapper()
  set laststatus=2

  let g:called = 0
  function! Statusline()
    let g:called = g:actual_curbuf
    " setlocal statusline&
    return 'stl'
  endfunction

  set statusline=%!'%{Statusline()}'
  redraw

  echom g:called
endfunction
call Wrapper()
```

`vim -Nu t-actual_curbuf.vim` results in "E121: Undefined variable: g:actual_curbuf".

This works however when not using the `Wrapper` function, i.e. commenting the first, and last two lines.

It might be related to scope handling in `set_internal_string_var`, which is used for this:
https://github.com/vim/vim/blob/947b39e761b8a95cc1bd37ad0c2c30552238809a/src/buffer.c#L4232

I've noticed this, because I was testing something in this regard with Vader, which wraps the tests in a function itself.

**Comment by brammool** [comment]
Daniel Hahler wrote:

> Given `t-actual_curbuf.vim`:
> 
> ```vim
> function! Wrapper()
>   set laststatus=2
> 
>   let g:called = 0
>   function! Statusline()
>     let g:called = g:actual_curbuf
>     " setlocal statusline&
>     return 'stl'
>   endfunction
> 
>   set statusline=%!'%{Statusline()}'
>   redraw
> 
>   echom g:called
> endfunction
> call Wrapper()
> ```
> 
> `vim -Nu t-actual_curbuf.vim` results in "E121: Undefined variable: g:actual_curbuf".
> 
> This works however when not using the `Wrapper` function, i.e. commenting the first, and last two lines.
> 
> It might be related to scope handling in `set_internal_string_var`, which is used for this:
> https://github.com/vim/vim/blob/947b39e761b8a95cc1bd37ad0c2c30552238809a/src/buffer.c#L4232
> 
> I've noticed this, because I was testing something in this regard with
> Vader, which wraps the tests in a function itself.

Strangely the variable is set without the g: prefix.  Thus it gets
defined inside the Wrapper() function scope.  The delete does use g:.

-- 
Advice to worms:  Sleep late.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
