### ISSUE TITLE
reset tty's termios to expected values on SIGCONT

### ISSUE THREAD

**Issue by joshudson** [vim/vim#3285]
`vim` gets very confused when it gets a TSTOP, TTIN, or STOP signal and later a CONT signal. The program is still running but the terminal is in an oddball state. I remember being able to do this in classic `vi` from ages ago.

Workaround: ^L:&lt;ENTER&gt;

**Comment by brammool** [comment]
I don't see this problem.  How to reproduce?

**Comment by jhudsoncedaron** [comment]
Obvious way: Send vim a SIGSTOP from another terminal. Bash will printout [n] stopped on the terminal it was on. Do fg %n to switch back to it.

**Comment by joshudson** [comment]
Ah good; I discovered the workaround didn't always work.
