### ISSUE TITLE
:tabm 1 and :tabm 2 move current tab to the same position

### ISSUE THREAD

**Issue by codenara** [vim/vim#3288]
Both `:tabm 1` and `:tabm 2` move current tab to the same position.
That is, `:tabm 1` moves current tab to the second position.
And then `:tabm 2` does nothing (that is, moves current tab to the second position)

Update:
If current tab page is tab page N, then `:tabm N` and `:tabm N-1` do nothing

Regards~

**Comment by h-east** [comment]
It is expected behavior.
See document on Vim.

```
:h :tabm
```

Probably, it is easy to understand by checking three or more tab pages.

--
Best regards,
Hirohito Higashi (h_east)

**Comment by chrisbra** [comment]
I am not so sure. There might be a problem here. Try `vim --clean -p file1 file2 file3` and go to the 2 tab and enter `:tabmove 2` (which should move the current tab to the end) according to [`:help :tabmove`](http://vimhelp.appspot.com/tabpage.txt.html#%3Atabmove):

> Move the current tab page to after tab page N.

So if I am on tab 2 and enter `:tabmove 2` I expect the current tabpage to be moved one further back.
That is not what is happening, because it will return here early because `tp == curtab`.

https://github.com/vim/vim/blob/3cb4448b8a5c0192988f4e349aba6d7a91a9a4bd/src/window.c#L4100-L4105

**Comment by h-east** [comment]
No.
Before curtab is removed, the tab page number of the move destination is determined.
So, in that case it is correct not to move the tab page.
If you assign a number to the tab page after removing curtab, the relative movement logic such as `:tabm -` and `:tabm +` will be broken.

I examined it carefully and wrote a patch by [v8.0.0259](https://github.com/vim/vim/commit/2f72c70657129c16e6b0e413752a775c804f02f8)

**Comment by h-east** [comment]
The associated vim_dev's thread  is [here](https://groups.google.com/d/topic/vim_dev/swpWq_T_23U/discussion).

**Comment by chrisbra** [comment]
I see, thanks. But it contradicts documentation. So perhaps we need to amend the documentation then?

**Comment by h-east** [comment]
Hmm, I don't think that is contradictory.

> Move the current tab page to after tab page N.

Example:
- Start Vim with three tabpages and cuurent tabpage is `2`.
  ```
  $ vim --clean -p 1 2 3 +tabn
  ```
  Now tabpages are `1|(2)|3`. 
  (2) is current tabpage.

- DO `:tabm 2`
  ```
  :tabm 2
  ```
  Move the current tab page to after tab page 2.

  - Immediately after `tab page 2` and just before the `tab page 3`.
    (`after tab page 2` is not `tab page 3`)
  - `tab page 2` move to "immediately after `tab page 2`".
  - That is, the `tab page 2` does not change from its original position.

---
There is no objection to changing the document in an easy-to-understand manner.
But I am not native, so it is difficult to express in English.

Thanks.

**Comment by chrisbra** [comment]
Okay, so how about the following doc patch (which also includes a test just to make sure):

```patch
diff --git a/runtime/doc/tabpage.txt b/runtime/doc/tabpage.txt
index a80d7c3b4..fcc2d2930 100644
--- a/runtime/doc/tabpage.txt
+++ b/runtime/doc/tabpage.txt
@@ -252,7 +252,12 @@ REORDERING TAB PAGES:
                    :tabmove    " move the tab page to the last
                    :$tabmove   " as above
                    :tabmove $  " as above
-
+<
+               Note: Moving the tabpage after index N does not necessarily
+               mean, the current tabpage will become index N + 1, e.g. if one
+               is on tabpage is 2 and one uses `:tabmove 2` this will be a
+               no-op (since it would be moved to after 2, but before 3) and
+               therefore behaves like `:tabmove 1` .
 :tabm[ove] +[N]
 :tabm[ove] -[N]
                Move the current tab page N places to the right (with +) or to
diff --git a/src/testdir/test_tabpage.vim b/src/testdir/test_tabpage.vim
index f4fbf28d1..45ccc2f7f 100644
--- a/src/testdir/test_tabpage.vim
+++ b/src/testdir/test_tabpage.vim
@@ -105,6 +105,16 @@ function Test_tabpage()
   call assert_equal(4, tabpagenr())
   7tabmove 5
   call assert_equal(5, tabpagenr())
+  " The following is a no-op
+  norm! 2gt
+  tabmove 2
+  call assert_equal(2, tabpagenr())
+  2tabmove
+  call assert_equal(2, tabpagenr())
+  tabmove 1
+  call assert_equal(2, tabpagenr())
+  1tabmove
+  call assert_equal(2, tabpagenr())
   call assert_fails("99tabmove", 'E16:')
   call assert_fails("+99tabmove", 'E16:')
   call assert_fails("-99tabmove", 'E16:')
```

**Comment by h-east** [comment]
Oh, Thanks for the write a document.

> Moving the tabpage after index N does not necessarily mean, the current tabpage will become index N + 1

Umm, I am confused... Just making sure, let me check your perception.
Perhaps you think that the tab page number starts at zero?

The tab page number starts at 1.
Zero has a special meaning that moves to **before** the first tabpage.

**Comment by brammool** [comment]
Mentioning that N is counted before the move explains a lot.  I'll add something to the docs.

**Comment by codenara** [comment]
Hmmm
If current tab page is tab page N, then `:tabm N` and `:tabm N-1` do nothing, and this is an expected behavior, right?

**Comment by wurunjian** [comment]
Hi h-east,

How about changing ":tabm N" -> Moving the current tab page and make it become index N+1? It is consistent with ":tabm 0". For example, 1|2|3|[4]|5|6, [4] is current tab page, ":tabm 2" will move current tab page to page 3. ":tabm 5" will move current tab page to page 5. It is hard to comprehend.

**Comment by h-east** [comment]
Hi,

Please refer to the latest document.
`:tabm`'s document was updated by https://github.com/vim/vim/commit/d473c8c101262702ea9eeb14907ee20a786942b2#diff-c845c52c8b97208632000afd11291282 on 2018-08-11

                Move the current tab page to after tab page N.  Use zero to
                make the current tab page the first one.  N is counted before
                the move, thus if the second tab is the current one,
                :tabmove 1 and :tabmove 2  have no effect.
                Without N the tab page is made the last one.

I think that consistency is obtained by the following specifications.

> N is counted before the move

--

Best regards,
Hirohito Higashi (h_east)

**Comment by wurunjian** [comment]
Hi h_east,

Thanks for your explanation! The latest help document makes sense. For example, 1|2|3|[4]|5|6, [4] is current tab page, ":tabm 0" makes the current page tab index as 1, how about ":tabm 2" makes the current page tab index as 3, and ":tabm 4" makes the current page tab index as 5. it is consistent.
