### ISSUE TITLE
setline() on TextChangedI borks undo

### ISSUE THREAD

**Issue by eraserhd** [vim/vim#3291]
foo.txt:
```
x
```
foo.vim:
```
let g:handled = v:false
function! Foo()
  if !g:handled
    call setline(1, ["(x)"])
    let g:handled = v:true
  endif
endfunction
autocmd TextChangedI <buffer> call Foo()
```

Do `vim -u foo.vim foo.txt`, then `i(<Enter><Esc>u`.

Expected:
```
x
```

Actual:
```
x
x)
```

**Comment by TimoKramer** [comment]
Hi there,
the closing commit (91d2e78) was made undone by commit https://github.com/vim/vim/commit/9fa9506853516c82851baec643aa47458cb8b3bc as far as I can see it. This happened just one day later and it broke parinfer-rust plugin again. It would be awesome if this patch could be reapplied.
Thanks for the work!

**Comment by brammool** [comment]
It appears the original problem of this issue works fine.  What is broken then?  Please give a simple reproducible example.
