### ISSUE TITLE
About the ctrl&p

### ISSUE THREAD

**Issue by GangyiTian** [vim/vim#3298]
When I updated the vim8(version 8.1.150), I found a problem. When I used ctrl&p, it would not search for other files, but now it will search for other files, and then it will be a bit stuck. How can I solve it?

**Comment by chrisbra** [comment]
Well, for a starter you could try to be more precise what the problem is. Start with a clear description of what Vim version you are using (and what previous version), what you did and what you expect and what happened. If possible try to reproduce the problem starting from `vim --clean -c ...`. 

For now, I don't even know if you are talking about the ctrl-p vim plugin or ctrl-p key press (in what mode)? So please clarify

**Comment by GangyiTian** [comment]
Oh..sorry 
The version I am using is 8.1.150, then ctrl-p I think it should be the native function of vim, I have not installed any modules. I usually use ctrl-p to complete my code, but I just found out that during the process of completing my code, vim will search for the code in my other files.I forgot what the previous version is, maybe 8.0 XD
@chrisbra

**Comment by GangyiTian** [comment]
I think it should not be a plugin for the completion code called ctrlp. This is to complete the code with ctrl-p while in the input mode. I think scanning in other files is a nice feature, but I wonder if it can be turned off with some kind of switch? Because it will scan other files, it will be slightly stuck (just a little, maybe my computer is not good enough) 
Actually, I am a newbie.XD，but I love vim.

**Comment by brammool** [comment]
> Oh..sorry 
> The version I am using is 8.1.150, then ctrl-p I think it should be the native function of vim, I have not installed any modules. I usually use ctrl-p to complete my code, but I just found out that during the process of completing my code, vim will search for the code in my other files.I forgot what the previous version is, maybe 8.0 XD

You probably run into this issue in the todo list:

	Completion mixes results from the current buffer with tags and
	other files.  Happens when typing CTRL-N while still search for
	results.  E.g., type "b_" in terminal.c and then CTRL-N twice.
	Should do current file first and not split it up when more
	results are found.  (Also #1890)

It annoys me too.  I'll move it up in the todo list.

-- 
In Africa some of the native tribes have a custom of beating the ground
with clubs and uttering spine chilling cries.  Anthropologists call
this a form of primitive self-expression.  In America we call it golf.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
