### ISSUE TITLE
statusline: set g:actual_curbuf also with `set stl=%!MyStatuslines()`

### ISSUE THREAD

**Issue by blueyed** [vim/vim#3299]
Currently g:actual_curbuf is only available in a statusline expression, i.e. `'%{neomake#statusline#get()}'`, but not when used inside of a function that returns the statusline (`'set statusline=%!MyStatusLine()'`, where `MyStatusLine` uses neomake#statusline#get()`).

I think it would be useful to have it set also for `%!…` already.

**Comment by lacygoill** [comment]
I think [8.1.1372](https://github.com/vim/vim/releases/tag/v8.1.1372) fixes an item which is still in [todo.txt](https://github.com/vim/vim/blob/06b0b4bc27077013e9b4b48fd1d9b33e543ccf99/runtime/doc/todo.txt#L562-L563):

> Set g:actual_curbuf when evaluating 'statusline', not just with an expression.
> (Daniel Hahler, 2018 Aug 8, #3299)

Although, it doesn't set `g:actual_curbuf` outside `%{}`, but you can get it from `g:statusline_winid`:

    set stl=%!Status()
    fu Status()
        let actual_curbuf = winbufnr(g:statusline_winid)
        ...
    endfu
