### ISSUE TITLE
`test_backup.vim` tests fail when built under `/tmp`

### ISSUE THREAD

**Issue by jonathonf** [vim/vim#3301]
_Edit: Issue title changed; real reason was due to [documented behaviour](http://vimhelp.appspot.com/options.txt.html#'backupskip') of skipping backup files in temporary locations, see @chrisbra's reply [below](https://github.com/vim/vim/issues/3301#issuecomment-411821461)._

### Summary

The tests in  `test_backup.vim` as introduced in https://github.com/vim/vim/commit/b782ba475a3f8f2b0be99dda164ba4545347f60f#diff-56cbec7ca8be0936c91499a3c49255c7 fail when the filesystem is mounted with `noatime`.

Tests pass when the filesystem is mounted e.g. `relatime`.

(Not sure if this is the tests, the changes as introduced, or that it has never "worked" but it's now being tested.)

### Test failure output

```
Executed 398 tests
3 FAILED:
Found errors in Test_backup():
Caught exception in Test_backup(): Vim(let):E484: Can't open file Xbackup.txt~ @ function RunTheTest[40]..Test_backup, line 9
Found errors in Test_backup2():
function RunTheTest[40]..Test_backup2 line 10: Expected ['line1', 'line2', 'line3'] but got ['']
function RunTheTest[40]..Test_backup2 line 12: Pattern '%testdir%Xbackup.txt\\~' does not match '*Xbackup.txt~'
Found errors in Test_backup2_backupcopy():
function RunTheTest[40]..Test_backup2_backupcopy line 10: Expected ['line1', 'line2', 'line3'] but got ['']
function RunTheTest[40]..Test_backup2_backupcopy line 12: Pattern '%testdir%Xbackup.txt\\~' does not match '*Xbackup.txt~'


From test_alot.vim:
Found errors in Test_backup():
Caught exception in Test_backup(): Vim(let):E484: Can't open file Xbackup.txt~ @ function RunTheTest[40]..Test_backup, line 9
Found errors in Test_backup2():
function RunTheTest[40]..Test_backup2 line 10: Expected ['line1', 'line2', 'line3'] but got ['']
function RunTheTest[40]..Test_backup2 line 12: Pattern '%testdir%Xbackup.txt\\~' does not match '*Xbackup.txt~'
Found errors in Test_backup2_backupcopy():
function RunTheTest[40]..Test_backup2_backupcopy line 10: Expected ['line1', 'line2', 'line3'] but got ['']
function RunTheTest[40]..Test_backup2_backupcopy line 12: Pattern '%testdir%Xbackup.txt\\~' does not match '*Xbackup.txt~'

Test results:


From test_alot.vim:
Found errors in Test_backup():
Caught exception in Test_backup(): Vim(let):E484: Can't open file Xbackup.txt~ @ function RunTheTest[40]..Test_backup, line 9
Found errors in Test_backup2():
function RunTheTest[40]..Test_backup2 line 10: Expected ['line1', 'line2', 'line3'] but got ['']
function RunTheTest[40]..Test_backup2 line 12: Pattern '%testdir%Xbackup.txt\\~' does not match '*Xbackup.txt~'
Found errors in Test_backup2_backupcopy():
function RunTheTest[40]..Test_backup2_backupcopy line 10: Expected ['line1', 'line2', 'line3'] but got ['']
function RunTheTest[40]..Test_backup2_backupcopy line 12: Pattern '%testdir%Xbackup.txt\\~' does not match '*Xbackup.txt~'
TEST FAILURE
```

**Comment by brammool** [comment]
> ### Summary
> 
> The tests in  `test_backup.vim` as introduced in https://github.com/vim/vim/commit/b782ba475a3f8f2b0be99dda164ba4545347f60f#diff-56cbec7ca8be0936c91499a3c49255c7 fail when the filesystem is mounted with `noatime`.
> 
> Tests pass when the filesystem is mounted e.g. `relatime`.
> 
> (Not sure if this is the tests, the changes as introduced, or that it has never "worked" but it's now being tested.)
> 

Are you sure this is caused by "noatime" and not another difference?  I
don't think the code depends on the last access time.

> ### Test failure output
> 
> ```
> Executed 398 tests
> 3 FAILED:
> Found errors in Test_backup():
> Caught exception in Test_backup(): Vim(let):E484: Can't open file Xbackup.txt~ @ function RunTheTest[40]..Test_backup, line 9

This indicates a different error from what "no access time" would do.


-- 
An indication you must be a manager:
You feel sorry for Dilbert's boss.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
Perhaps somehow backupskip kicks in?

**Comment by jonathonf** [comment]
> Are you sure this is caused by "noatime" and not another difference?

You know, I spent two or three hours last night narrowing down the issue and I was pretty certain it was due to `noatime`. Then I try to replicate again this evening and I can't. :rage:

So, these steps _don't_ work to replicate:

```
$ sudo mount -t tmpfs -o noatime tmpfs /mnt
$ mount | grep /mnt
tmpfs on /mnt type tmpfs (rw,noatime)
... (build) ...
--> tests don't fail
$ sudo mount -o remount,relatime /mnt
$ mount | grep /mnt
tmpfs on /mnt type tmpfs (rw,relatime)
... (build) ...
--> tests pass
```

However, when I try to build in `/tmp`, which is set `noatime` via my `/etc/fstab`, the tests fail. If I remount _that_ `relatime`, then tests ... still fail.

Wat.

So, it appears something here is being messed up by whatever is "special" about this particular [tmpfs](https://wiki.archlinux.org/index.php/tmpfs). This doesn't make a lot of sense to me; I'll do more digging.

(Just to confirm it's not running out of space:

```
$ df -h | grep tmp
devtmpfs                     16G     0   16G   0% /dev
tmpfs                        16G   17M   16G   1% /dev/shm
tmpfs                        16G  1.6M   16G   1% /run
tmpfs                        16G     0   16G   0% /sys/fs/cgroup
tmpfs                        16G  192K   16G   1% /tmp
tmpfs                       3.2G  121M  3.1G   4% /run/user/1000
tmpfs                        16G  192M   16G   2% /mnt
```
`/mnt` contains the successfully-built Vim.)

**Comment by chrisbra** [comment]
> However, when I try to build in /tmp, which is set noatime via my /etc/fstab, the tests fail. If I remount that relatime, then tests ... still fail.

This is expected, because quoting the [documentation](http://vimhelp.appspot.com/options.txt.html#'backupskip'):

>  When one of the patterns matches with the name of the file which is written, no backup file is created

I have run previously into this problem. Perhaps this patch is needed in addition:

```patch
diff --git a/src/testdir/test_backup.vim b/src/testdir/test_backup.vim
index 0981efdce..ce2bfe72b 100644
--- a/src/testdir/test_backup.vim
+++ b/src/testdir/test_backup.vim
@@ -1,7 +1,7 @@
 " Tests for the backup function

 func Test_backup()
-  set backup backupdir=.
+  set backup backupdir=. backupskip=
   new
   call setline(1, ['line1', 'line2'])
   :f Xbackup.txt
@@ -12,13 +12,13 @@ func Test_backup()
   let l = readfile('Xbackup.txt~')
   call assert_equal(['line1', 'line2'], l)
   bw!
-  set backup&vim backupdir&vim
+  set backup&vim backupdir&vim backupskip&vim
   call delete('Xbackup.txt')
   call delete('Xbackup.txt~')
 endfunc

 func Test_backup2()
-  set backup backupdir=.//
+  set backup backupdir=.// backupskip=
   new
   call setline(1, ['line1', 'line2', 'line3'])
   :f Xbackup.txt
@@ -34,11 +34,11 @@ func Test_backup2()
   bw!
   call delete('Xbackup.txt')
   call delete(f)
-  set backup&vim backupdir&vim
+  set backup&vim backupdir&vim backupskip&vim
 endfunc

 func Test_backup2_backupcopy()
-  set backup backupdir=.// backupcopy=yes
+  set backup backupdir=.// backupcopy=yes backupskip=
   new
   call setline(1, ['line1', 'line2', 'line3'])
   :f Xbackup.txt
@@ -54,5 +54,5 @@ func Test_backup2_backupcopy()
   bw!
   call delete('Xbackup.txt')
   call delete(f)
-  set backup&vim backupdir&vim backupcopy&vim
+  set backup&vim backupdir&vim backupcopy&vim backupskip&vim
 endfunc
```

**Comment by jonathonf** [comment]
Yup, that got the tests passing.

I'll edit the issue title to fit the actual reason for the test failures.
