### ISSUE TITLE
Test_backupskip failing

### ISSUE THREAD

**Issue by tombriden** [vim/vim#3308]
Since the test was added in 8.0.1704, it's failing for me with:
```
From test_options.vim:                                                                                                                                                                                             
Found errors in Test_backupskip():                                                                                                                                                                                 
function RunTheTest[40]..Test_backupskip line 11: Pattern '/var/tmp/paludis/build/app-editors-vim-8.1.0263/temp/.\\*' does not match '/tmp/*,/var/tmp/paludis/build/app-editors-vim-8.1.0263/temp/*,/var/tmp/paluds/build/app-editors-vim-8.1.0263/temp/*'
```

It looks to me that the pattern can never match with the `.` char before the literal `*` so should actually be:

```
diff --git a/src/testdir/test_options.vim.old b/src/testdir/test_options.vim
index 460a569..28fee34 100644
--- a/src/testdir/test_options.vim.old
+++ b/src/testdir/test_options.vim
@@ -344,7 +344,7 @@ func Test_backupskip()
   for var in  ['$TEMPDIR', '$TMP', '$TEMP']
     if exists(var)
       let varvalue = substitute(expand(var), '\\', '/', 'g')
-      call assert_match(varvalue . '.\*', bskvalue)
+      call assert_match(varvalue . '\*', bskvalue)
     endif
   endfor
 endfunc
```

**Comment by brammool** [comment]
> Since the test was added in 8.0.1704, this test is failing for me with:
> ```
> From test_options.vim:                                                                                                                                                                                             
> Found errors in Test_backupskip():                                                                                                                                                                                 
> function RunTheTest[40]..Test_backupskip line 11: Pattern '/var/tmp/paludis/build/app-editors-vim-8.1.0263/temp/.\\*' does not match '/tmp/*,/var/tmp/paludis/build/app-editors-vim-8.1.0263/temp/*,/var/tmp/palud$
> s/build/app-editors-vim-8.1.0263/temp/*'
> ```
> 
> It looks to me that the pattern can never match with the `.` char before the literal `*` so should actually be:
> 
> ```
> diff --git a/src/testdir/test_options.vim.old b/src/testdir/test_options.vim
> index 460a569..28fee34 100644
> --- a/src/testdir/test_options.vim.old
> +++ b/src/testdir/test_options.vim
> @@ -344,7 +344,7 @@ func Test_backupskip()
>    for var in  ['$TEMPDIR', '$TMP', '$TEMP']
>      if exists(var)
>        let varvalue = substitute(expand(var), '\\', '/', 'g')
> -      call assert_match(varvalue . '.\*', bskvalue)
> +      call assert_match(varvalue . '\*', bskvalue)
>      endif
>    endfor
>  endfunc
> ```

The dot is supposed to match the "/" before the "*".
Is the problem that one of your variables ends in a slash perhaps?
Try changing the dot to a slash.

-- 
Dreams are free, but there's a small charge for alterations.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by tombriden** [comment]
Ah ok, makes sense. I think changing for just `/` would still fail in my case as the pattern would end up looking for `//` at the end. `/?` should work for both though, I'll give that a try when I'm back at my laptop

**Comment by tombriden** [comment]
Hm, using a `?` to make the appended `/` optional isn't working:
```
function RunTheTest[40]..Test_backupskip line 11: Pattern '/var/tmp/paludis/build/app-editors-vim-8.1.0264/temp//?\\*' does not match '/tmp/*,/var/tmp/paludis/build/app-editors-vim-8.1.0264/temp/*,/var/tmp/paludis/build/app-editors-vim-8.1.0264/temp/*'
```

But changing it to 
```
 call assert_match(varvalue . '.*\*', bskvalue)
```

works fine

**Comment by brammool** [comment]
> Hm, using a `?` to make the appended `/` optional isn't working:
> ```
> function RunTheTest[40]..Test_backupskip line 11: Pattern '/var/tmp/paludis/build/app-editors-vim-8.1.0264/temp//?\\*' does not match '/tmp/*,/var/tmp/paludis/build/app-editors-vim-8.1.0264/temp/*,/var/tmp/paludis/build/app-editors-vim-8.1.0264/temp/*'
> ```
> 
> But changing it to 
> ```
>  call assert_match(varvalue . '.*\*', bskvalue)
> ```
> 
> works fine

But then we don't check that the "*" comes after a slash.

Instead of "?" you should use "\=" (or "\\=").

-- 
BEDEVERE: How do you know so much about swallows?
ARTHUR:   Well you have to know these things when you're a king, you know.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by tombriden** [comment]
Yep,
```
call assert_match(varvalue . '/\=\*', bskvalue)
```
works perfectly. Thanks!
