### ISSUE TITLE
Order of "(Default)" in Windows installer

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3309]
In the Windows installer it seems strange the options for key remapping and mouse behavior is not in the same order.

"(Default)" is first in key mapping but last in mouse behavior.

![vim](https://user-images.githubusercontent.com/1836590/43972300-261ebe38-9cd4-11e8-8d4a-a5ffbba250f2.jpg)

**Comment by k-takata** [comment]
It is just based on `installer.exe` (`dosinst.c`).

**Comment by k-takata** [comment]
This is no more applicable in v8.1.0616. Closing.
