### ISSUE TITLE
Show "Default" "Windows" "Unix" first in Windows installer

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3310]
Instead of text like:

    Right button extends selection, left button starts visual mode (Unix)

Maybe its more easy to read and quicker to understand if its written like:

    Unix
        Right button extends selection, left button starts visual mode

    Windows
        Right button ...

    Default
        Right button ...

Or:

    Unix - Right button extends selection, left button starts visual mode

    Windows - Right button ...

    Default - Right button ...

Same for "Key remapping".
Having "Default" first and then the explanation afterwards.

![vim](https://user-images.githubusercontent.com/1836590/43972408-8f4588ec-9cd4-11e8-93e5-0d16a450d718.jpg)

**Comment by k-takata** [comment]
This is no more applicable in v8.1.0616. Closing.
