### ISSUE TITLE
"vim -?" shows incorrect encoding in cmd.exe

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3311]
It seems if i write "vim -?" in cmd.exe terminal in Windows 7 the encoding of characters like æøå does not show with correct encoding.

æ becomes µ
ø becomes °
Å becomes ┼
é becomes Ú

    VIM - Vi IMproved 8.1 (2018 May 18, compiled May 18 2018 18:26:56)

    usage: vim [argumenter] [file ..]       edit specified file(s)
    eller: vim [argumenter] -               lµs tekst fra stdin

Should have been:

    eller: vim [argumenter] -               læs tekst fra stdin

In MINGW64 terminal the encoding is correct.

**Comment by chrisbra** [comment]
this might be a codepage/encoding issue. I see similar behaviour with vim in a german environment with codepage=850

**Comment by mattn** [comment]
What $LANG do you use? or $LC_MESSAGES?

```
echo %LANG%
echo %LC_MESSAGES%
```

**Comment by tonymec** [comment]
%LANG% and %LC_something% are usually not set in the environment on (DOS and) Windows (though they are on Cygwin, which is Unix-Like): the Windows locale mechanism is different. However, even on Windows, Vim gets at startup the system's locale (on Windows it is often called something else, "country parameters" or something) and Vim translates it for its own purposes into Unix-like $LC_something stuff.

If you type `:language` or even just `:lang`, with no arguments, inside Vim, it will tell you what locale settings it is using. Of particular importance for the present problem is not only `$LC_MESSAGES` (which says in which human language — English, French, German, Chinese, Japanese, … — the menus and messages are to be displayed) but also `$LC_CTYPE` (which says which charset — Latin1, iso-8859-2, GBX, UTF-8, … — is to be used for the exchange of textual information between the computer program and whatever or whoever is to be found the other side of the screen and keyboard).

Best regards,
Tony.

**Comment by scootergrisen** [comment]
Did some testing with different fonts and code pages.
The default font in Windows 7 cmd.exe is raster and default code page is 850.
Since raster and 850 is the default i would like Vim to work with it instead of having the user change.

With Vim version 8.1.467 the correct letters are shown with Lucida Console (TrueType) code page 1252 and 65000.

Raster 850:

    eller: vim [argumenter] -               lµs tekst fra stdin
    eller: vim [argumenter] -q [fejlfil]    rediger fil med f°rste fejl
    -p[N]                ┼bn N fanebladssider (standard: Ún pr. fil)

Raster 1252 (Shows with µ┼°Ú like 850 in cmd window but copies to clipboard like this):

    eller: vim [argumenter] -               læs tekst fra stdin
    eller: vim [argumenter] -q [fejlfil]    rediger fil med første fejl
    -p[N]                Åbn N fanebladssider (standard: én pr. fil)

Raster 65000 (Shows with µ┼°Ú like 850 in cmd window but copies to clipboard like this):

    eller: vim [argumenter] -               læs tekst fra stdin
    eller: vim [argumenter] -q [fejlfil]    rediger fil med første fejl
    -p[N]                Åbn N fanebladssider (standard: én pr. fil)

Raster 65001 (Shows with µ┼°Ú like 850 in cmd window but copies to clipboard like this):

    eller: vim [argumenter] -               læs tekst fra stdin
    eller: vim [argumenter] -q [fejlfil]    rediger fil med første fejl
    -p[N]                Åbn N fanebladssider (standard: én pr. fil)



Lucida Console (TrueType) 850:

    eller: vim [argumenter] -               lµs tekst fra stdin
    eller: vim [argumenter] -q [fejlfil]    rediger fil med f°rste fejl
    -p[N]                ┼bn N fanebladssider (standard: Ún pr. fil)

Lucida Console (TrueType) 1252:

    eller: vim [argumenter] -               læs tekst fra stdin
    eller: vim [argumenter] -q [fejlfil]    rediger fil med første fejl
    -p[N]                Åbn N fanebladssider (standard: én pr. fil)

Lucida Console (TrueType) 65000:

    eller: vim [argumenter] -               læs tekst fra stdin
    eller: vim [argumenter] -q [fejlfil]    rediger fil med første fejl
    -p[N]                Åbn N fanebladssider (standard: én pr. fil)

Lucida Console (TrueType) 65001:

    eller: vim [argumenter] -               l�s tekst fra stdin
    eller: vim [argumenter] -q [fejlfil]    rediger fil med f�rste fejl
    -p[N]                �bn N fanebladssider (standard: �n pr. fil)

**Comment by scootergrisen** [comment]
> 
> 
> What $LANG do you use? or $LC_MESSAGES?
> 
> ```
> echo %LANG%
> echo %LC_MESSAGES%
> ```

cmd.exe gives:

    %LANG%
    %LC_MESSAGES%

**Comment by tonymec** [comment]
> cmd.exe gives:
> ```
> %LANG%
> %LC_MESSAGES%
> ```

So, as I said earlier, `%LANG%` and `%LC_MESSAGES%` are not defined in Windows.

Please do the following test:
1. Start Vim as `vim --clean`
2. In Vim, type
```vim
:language messages
:language ctype
```
and tell us what Vim answered to each of these.

However, your test with various fonts seems to indicate that your Windows defaults are not correctly set for Scandinavian text. IMHO the only way you can get Vim to work within such a broken system without changing anything inside or outside of Vim is by entering only unaccented text, e.g. either English text, or program code with no Danish (or Norwegian or…) strings or comments in it but only "plain" unaccented US-ASCII characters even in its strings and comments.

Best regards,
Tony.

**Comment by scootergrisen** [comment]
Running (in cmd.exe vim):

    :language messages
    :language ctype

Gives:

    Nuværende messages sprog: "DA"
    Nuværende ctype sprog: "C"

**Comment by tonymec** [comment]
> Running (in cmd.exe vim):
> ```
> :language messages
> :language ctype
> ```
> Gives:
> ```
> Nuværende messages sprog: "DA"
> Nuværende ctype sprog: "C"
> ```
IOW, menus and messages in Danish, and screen and keyboard interpreted as in ASCII (or maybe Latin1). As the æ (not µ) in "Nuværende" seems to show, Vim knows how to properly display Danish text to you. My guess is that you got a Windows problem, not a Vim problem, and that you should solve it by tweaking your Windows system settings.

Best regards,
Tony.

**Comment by scootergrisen** [comment]
If i run stuff like cmd.exe /h or audacity.exe /h the text shows with correct encoding so i think the problem is with Vim.
