### ISSUE TITLE
Using --not-a-term should not send terminal escape sequences

### ISSUE THREAD

**Issue by blueyed** [vim/vim#3313]
```
% vim --not-a-term -Nu NONE -cq | cat -A
^[[?2004h^[[?1049h^[[?1h^[=^[[?2004h^[[1;51r^[[?12h^[[?12l^[[27m^[[23m^[[29m^[[m^[[H^[[2J^[[51;1H^[[?2004l^[[?2004l^[[?1l^[>^[[r^[[?1049l
```

The output should be empty here.

**Comment by chrisbra** [comment]
I am not sure this is true. The `--not-a-term` was introduced to prevent the 2 second warning that comes when running vim tests in the CI testsuite not more and not less. Try running with a dumb terminal (or an empty environment. (It still might be, that Vim switches screens, asks the terminal for some questions or otherwise).

BTW: I'd really appreciate it, if questions regarding a certain behaviour would be first asked on vim-dev before opening random tickets. Thanks.

**Comment by brammool** [comment]
As Christian mentions, the argument is not to stop sending escape sequences.

**Comment by blueyed** [comment]
> the argument is not to stop sending escape sequences

But it would fit naturally, wouldn't it?
Why are terminal escape sequences sent if you say `--not-a-term`?

@chrisbra 
> The --not-a-term was introduced to prevent the 2 second warning that comes when running vim tests in the CI testsuite not more and not less.

I see that this might have been the initial intention (but `-s /dev/null` would also have worked already).
It wasn't named `--dont-wait-two-seconds-after-not-a-term-warning` however, and therefore it sounds like a good fit to suppress terminal escape sequences also.

> Try running with a dumb terminal (or an empty environment. (It still might be, that Vim switches screens, asks the terminal for some questions or otherwise).

I do not get what you mean.

**Comment by brammool** [comment]
> > Try running with a dumb terminal (or an empty environment. (It still
> > might be, that Vim switches screens, asks the terminal for some
> > questions or otherwise).
> 
> I do not get what you mean.

vi +"set term=dumb"

Only uses "clear screen" and move cursor.  Amazing that most things
still work....

-- 
Why is "abbreviation" such a long word?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
