### ISSUE TITLE
incsearch for :s command with range highlights incorrect lines

### ISSUE THREAD

**Issue by itchyny** [vim/vim#3318]
8.1.0271 introduces incsearch support for :s command but it works buggy.
Type `:.,.+2s/foo/bar` moves the cursor and highlight incorrect lines.

![incsearch](https://user-images.githubusercontent.com/375258/43999751-81daf0a0-9e4d-11e8-9d5d-a823e7bd048c.gif)

Screenshot on Vim 8.1.0274.

**Comment by brammool** [comment]
Thanks for reporting.  I thought I fixed it, but put it in the wrong order.
I'll also make it accept a match at the start of the first line.

**Comment by itchyny** [comment]
Thank you. I confirmed the issue is fixed.
