### ISSUE TITLE
Cannot input some Vietnamese characters

### ISSUE THREAD

**Issue by minhdanh** [vim/vim#3319]
Hi, I'm using vim 8.1 on macOS. Every time when I input some Vietnamese character, VIM skips that character and move the current line to a line below. If the current line is the only line, VIM skips that character and exits insert mode, then display an error: `E486: Pattern not found: \<deliver_later\>`
With `deliver_later` seems to be a register.

If I just paste the character from clipboard, there's no such issue.

Here a character that causing this issue: https://unicodelookup.com/?#%C3%AA/1

Here's record of the screen I made to explain the issue better: https://gifyu.com/image/K3BJ

Basically I tried to input:

```
itrông<Enter> # worked fine
trên # could not make it
```

Vim version:

```
vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug  7 2018 21:58:18)
macOS version
Included patches: 1-250
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     +tag_old_static
+arabic            +farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    -tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    -gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               +perl              +vartabs
+clipboard         +jumplist          +persistent_undo   +vertsplit
+cmdline_compl     +keymap            +postscript        +virtualedit
+cmdline_hist      +lambda            +printer           +visual
+cmdline_info      +langmap           +profile           +visualextra
+comments          +libcall           -python            +viminfo
+conceal           +linebreak         +python3           +vreplace
+cryptv            +lispindent        +quickfix          +wildignore
+cscope            +listcmds          +reltime           +wildmenu
+cursorbind        +localmap          +rightleft         +windows
+cursorshape       -lua               +ruby              +writebackup
+dialog_con        +menu              +scrollbind        -X11
+diff              +mksession         +signs             -xfontset
+digraphs          +modify_fname      +smartindent       -xim
-dnd               +mouse             +startuptime       -xpm
-ebcdic            -mouseshape        +statusline        -xsmp
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_clipboard
+eval              -mouse_gpm         +syntax            -xterm_save
+ex_extra          -mouse_jsbterm     +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework AppKit   -mmacosx-version-min=10.13 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.28.0/lib/perl5/5.28.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m -framework CoreFoundation  -lruby.2.5.1 -lobjc
```

**Comment by tonymec** [comment]
I don't understand how you try to enter the character (with some XIM maybe?)

You could enter the `ê` character (or similarly any troublesome character) in Vim with no external help (thus no need to invoke any Input Method or third-party plugin) in one of the following ways:
- by digraph (see `:h digraph.txt` and in particular `:h digraph-default`): `ê` is `Ctrl-K e >` (in Insert mode without intervening spaces)
- by Unicode codepoint (see `:h i_Ctrl-V_digit`): `ê` is U+00EA thus `Ctrl-V x EA` or `Ctrl-V u 00EA` (again, in Insert mode without intervening spaces)
- by means of the `accents` keymap (in Insert mode after `:setlocal keymap=accents`): `ê` is obtained by typing `^` followed by `e`

All of the above assume that your `'encoding'` is set to UTF-8, which should be done in your `.vimrc`, and allows handling text files in any charset: for details, see https://vim.wikia.com/wiki/Working_with_Unicode

Best regards,
Tony.

**Comment by minhdanh** [comment]
> I don't understand how you try to enter the character (with some XIM maybe?)

Yeah, I used a program to help with inputting Vietnamese. macOS has a Vietnamese input source too, but it's not very convenient to me. In case you want to try for yourself: 
<img width="665" alt="screen shot 2018-08-14 at 8 45 30 pm" src="https://user-images.githubusercontent.com/4865412/44095484-259a80d2-a003-11e8-8ee3-285d2d6f0ff2.png">

So when enabled, to input the `ê` character I would type `e6`. Same for `ô` (`o6`) (You'll see the characters are underlined, just press ESC for the character really sent to Vim).

I tried the ways you suggested, the first two methods worked, the third didn't for me. However that's not normally the way to input Vietnamese characters. Imagine we have a long sentence like this: `Ngày mai em đi biển nhớ tên em gọi về.`. It would be very painful to try insert each Unicode character in such sentence.

**Comment by HadesD** [comment]
@minhdanh
Atm, i think the best solution is type
:paste
To switch to paste mode, then you can type everythings
Then after, type
:nopaste

It is not best but can be use

Wait for vim team fix this

**Comment by minhdanh** [comment]
@HadesD Thank you. That seems working. But I had to use `:set paste` and `:set nopaste`

**Comment by tonymec** [comment]
> @HadesD Thank you. That seems working. But I had to use `:set paste` and `:set nopaste`

You can remap that to keys; here is an example (which assumes `'nocompatible'`, or at least that `'cpoptions'` does not include the `<` flag):
```vim
" Mappings for 'paste' option
" we intentionally don't touch F1 (Help)
" Shift-F1: Toggle
nmap <S-F1> :if &paste <Bar> set nopaste <Bar> else <Bar> set paste <Bar> endif <CR>
" F2: set paste ON
nmap <F2> :set paste<CR>
" Shift-F2: set paste OFF
nmap <S-F2> :set nopaste<CR>
```
(Of course it also assumes that you're running a Vim compiled with `+eval` otherwise the whole `if..endif` construct becomes a no-op.)

Also of course, you can use any other `{lhs}` that suits you, preferably something not already taken.

Best regards,
Tony.

**Comment by no-vici** [comment]
@minhdanh ,

You will have no problem with Vietnamese input if you use [OpenKey](https://github.com/tuyenvm/OpenKey).
