### ISSUE TITLE
Issues with incsearch for Ex commands

### ISSUE THREAD

**Issue by markonm** [vim/vim#3321]
Hi, thank you for new functionality. I noticed a few issues.

With the following buffer contents:
```
1 foo
2 foo
3 foo
4 bar
```

- `3;1s/.` reversed range doesn't produce highlight
- `%s//` Doesn't highlight previous pattern.
- when cursor is on the second line `%s/foo/` moves cursor to the match on the first line. It would be more natural to start the searching from the next line, the same as  with `/`  command.
- `1;3s/bar/` moves the cursor to the fourth line
- `%s/.` followed with `%s/` leaves unnecessary highlighting

**Comment by markonm** [comment]
- `%s /foo` doesn't produce highlight

Also, it would be nice if `incsearch` supported `:sort` and `:vim`.

**Comment by markonm** [comment]
The following are not issues but feature request that would be nice to have (at least for me)
 - `?` delimiter should search backwards
 - parsing should skip command modifiers (`windo`, `silent`, etc)

**Comment by brammool** [comment]
The bugs should be fixed now.

:%s/foo highlighting the first match is correct.  Highlighting a closer match avoids jumping around, but it's not consistent, e.g. when typing "foox" and there is only a match above the cursor it would suddenly jump.

Making :sort and :vimgrep work should be possible.  I'll add it on the todo list.
Parsing command modifiers should also be possible.

I don't understand the remark about ? searching backwards. :{range}s?pat? works just the same as when using /pat/.

**Comment by markonm** [comment]
> I don't understand the remark about ? searching backwards. :{range}s?pat? works just the same as when using /pat/.

That would be useful if `%s/foo` were changed to start searching at the current cursor position. It would be the same difference as it is for search commands `/` and `?`. One searches forwards and the other searches backwards. For every other range `/` delimiter would start search forwards at the start of a range and `?` would search backwards from the end of a range. I attached a gif to describe it better.

![2](https://user-images.githubusercontent.com/16160229/44044625-74017d94-9f26-11e8-93a6-ec0bdc364c77.gif)

> :%s/foo highlighting the first match is correct. Highlighting a closer match avoids jumping around, but it's not consistent, e.g. when typing "foox" and there is only a match above the cursor it would suddenly jump.

This is a good example when `?` delimiter searching backwards would be useful. I think that behavior would be more natural and consistent with current search commands (`/`, `?`).

**Comment by markonm** [comment]
> Making :sort and :vimgrep work should be possible. I'll add it on the todo list.

`:smagic` and `:snomagic` would also be useful.

I can confirm every issue is fixed except:

`1;3s/bar/ moves the cursor to the fourth line`

**Comment by brammool** [comment]
I cannot reproduce the problem with "1;3s/bar/", it shows me no match

**Comment by brammool** [comment]
> > I don't understand the remark about ? searching backwards. :{range}s?pat? works just the same as when using /pat/.
> 
> That would be useful if `%s/foo` were changed to start searching at the current cursor position. It would be the same difference as it is for search commands `/` and `?`. One searches forwards and the other searches backwards. For every other range `/` delimiter would start search forwards at the start of a range and `?` would search backwards from the end of a range. I attached a gif to describe it better.
> 
> ![2](https://user-images.githubusercontent.com/16160229/44044625-74017d94-9f26-11e8-93a6-ec0bdc364c77.gif)

OK, so this would also require when using ":%s/pat" to not highlight the
first "pat" in the file, but the first one from the current line.

> > :%s/foo highlighting the first match is correct. Highlighting a closer match avoids jumping around, but it's not consistent, e.g. when typing "foox" and there is only a match above the cursor it would suddenly jump.
> 
> This is a good example when `?` delimiter searching backwards would be useful. I think that behavior would be more natural and consistent with current search commands (`/`, `?`).

-- 
A special cleaning ordinance bans housewives from hiding dirt and dust under a
rug in a dwelling.
		[real standing law in Pennsylvania, United States of America]

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by markonm** [comment]
> I cannot reproduce the problem with "1;3s/bar/", it shows me no match

I can reproduce it with the following:
`vim --clean +"set incsearch hlsearch cursorline"`

It doesn't highlight anything for me also, it just moves cursor to the fourth line.

**Comment by brammool** [comment]
> > I cannot reproduce the problem with "1;3s/bar/", it shows me no match
> 
> I can reproduce it with the following:
> `vim --clean +"set incsearch hlsearch cursorline"`

Oh, it doesn't show a match, it has the cursorline highlighting in line
4.

-- 
"I know that there are people who don't love their fellow man,
and I hate those people!" - Tom Lehrer

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by markonm** [comment]
Another one I found:
`/foo/s//<esc>` changes search register to `foo`

**Comment by brammool** [comment]
I cannot reproduce the problem with /foo/s//<esc>. Can you give more information?

**Comment by markonm** [comment]
1. `vim --clean`
2. `:/foo/s//`
3. Press `<esc>` to leave command-line
4. `echo @/` outputs `foo` even though command-line was not executed

There is also an error `E486` after second step.

**Comment by markonm** [comment]
Closing this. Everything is fixed; thanks!
