### ISSUE TITLE
i compile vim in win10,but something error

### ISSUE THREAD

**Issue by flameOnYou** [vim/vim#3322]
I:\vim\src>mingw32-make.exe -f Make_ming.mak CC=x86_64-w64-mingw32-gcc
'x86_64-w64-mingw32-gcc' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
x86_64-w64-mingw32-gcc -c -Iproto -DWIN32 -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 -DHAVE_PATHDEF -DFEAT_HUGE -DHAVE_STDINT_H -DHAVE_GETTEXT -DHAVE_LOCALE_H -DDYNAMIC_GETTEXT -DFEAT_CSCOPE -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL -DFEAT_TERMINAL -DFEAT_GUI_W32 -DFEAT_CLIPBOARD -DFEAT_MBYTE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DDYNAMIC_ICONV -pipe -march= -Wall -O3 -fomit-frame-pointer -freg-struct-return -s arabic.c -o gobj/arabic.o
process_begin: CreateProcess(NULL, x86_64-w64-mingw32-gcc -c -Iproto -DWIN32 -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 -DHAVE_PATHDEF -DFEAT_HUGE -DHAVE_STDINT_H -DHAVE_GETTEXT -DHAVE_LOCALE_H -DDYNAMIC_GETTEXT -DFEAT_CSCOPE -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL -DFEAT_TERMINAL -DFEAT_GUI_W32 -DFEAT_CLIPBOARD -DFEAT_MBYTE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DDYNAMIC_ICONV -pipe -march= -Wall -O3 -fomit-frame-pointer -freg-struct-return -s arabic.c -o gobj/arabic.o, ...) failed.
make (e=2):
Make_cyg_ming.mak:935: recipe for target 'gobj/arabic.o' failed
mingw32-make.exe: *** [gobj/arabic.o] Error 2

**Comment by k-takata** [comment]
It looks that the make command failed to execute the `x86_64-w64-mingw32-gcc` command.
Does `x86_64-w64-mingw32-gcc.exe` exist in your $PATH?

**Comment by flameOnYou** [comment]
yes,mingw32-make.exe in my $PATH

**Comment by k-takata** [comment]
No, I mean `x86_64-w64-mingw32-gcc.exe`, not `mingw32-make.exe`.

**Comment by flameOnYou** [comment]
yes , it's also in my $PATH,when i use command **mingw32-make.exe -f Make_ming.mak** it will report the some error

**Comment by flameOnYou** [comment]
by the way,I try to use visual studio 2017 compile vim,my command is **nmake.exe -f Make_mvc.mak  PYTHON3=D:\Python36 PYTHON3_VER=36 DYNAMIC_PYTHON3=yes  GUI=yes IME=yes   ARCH=x86-64 gvim.exe**,it's build success,but the gvim.exe version is always the 32bit-gui version

**Comment by flameOnYou** [comment]
E:\vim\src>mingw32-make.exe -f Make_ming.mak
'sed' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
mkdir gobj
gcc -c -Iproto -DWIN32 -DWINVER=0x0600 -D_WIN32_WINNT=0x0600 -DHAVE_PATHDEF -DFEAT_HUGE -DHAVE_STDINT_H -DHAVE_GETTEXT -DHAVE_LOCALE_H -DDYNAMIC_GETTEXT -DFEAT_CSCOPE -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL -DFEAT_TERMINAL -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DFEAT_DIRECTX_COLOR_EMOJI -DFEAT_GUI_W32 -DFEAT_CLIPBOARD -DFEAT_MBYTE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DDYNAMIC_ICONV -pipe -march= -Wall -O3 -fomit-frame-pointer -freg-struct-return -s arabic.c -o gobj/arabic.o
gcc: error: missing argument to '-march='
Make_cyg_ming.mak:961: recipe for target 'gobj/arabic.o' failed
mingw32-make.exe: *** [gobj/arabic.o] Error 1

**Comment by k-takata** [comment]
Please read [INSTALLpc.txt](https://github.com/vim/vim/blob/master/src/INSTALLpc.txt) at first.
MinGW has some variants, but MSYS2 is recommended.

> 'sed' 不是内部或外部命令，也不是可运行的程序

If `ARCH` is not specified, the makefile tries to detect `ARCH` by itself using `sed` command.
Please make sure that sed is in your PATH or specify `ARCH` explicitly.

> by the way,I try to use visual studio 2017 compile vim

You need to use correct version of VS 2017 command prompt. If you want to build 64-bit version, use "x64 Native Tools" (or "x86_x64 Cross Tools") command prompt. `ARCH` is not used in the makefile for MSVC.

**Comment by flameOnYou** [comment]
oh! I've been puzzled for many days.
thank you very much!
best wishes for you!

**Comment by fourier49** [comment]
Hi flameOnYou
 The same issue happened to me . I am sure that the 'sed' is in the path , and i can key in the command 'sed' it does work well . but the error message show that the 'sed' 不是内部或外部命令，也不是可运行的程序. Could you solve it yet? thk for any suggestion

**Comment by flameOnYou** [comment]
@fourier49 
![image](https://user-images.githubusercontent.com/20795930/51371572-7fa13a00-1b35-11e9-8418-94f3d0a7c57b.png)
i use the error bat,finally,I use VS_2017_x64_x86 make it success,you can consult the comment with @k-takata
