### ISSUE TITLE
when i input :shell ,Eject a cmd window 

### ISSUE THREAD

**Issue by flameOnYou** [vim/vim#3324]
My system is win10,Normally it where run the terminal in vim.i don't now how to do
![image](https://user-images.githubusercontent.com/20795930/44027616-b61d94b2-9f29-11e8-8cab-08403ee1c5f7.png)

**Comment by flameOnYou** [comment]
when i input :terminal

![image](https://user-images.githubusercontent.com/20795930/44027765-38ec0fd6-9f2a-11e8-85c3-48dfe8741d18.png)

**Comment by k-takata** [comment]
If you don't want to open a command prompt window when you executing a command, try `:set guioptions+=!`. (See [`:help 'go-!'`](https://github.com/vim/vim/blob/2b926fcb3c5d8bd09a219009336bbec7c66ae67e/runtime/doc/options.txt#L3869-L3875) for detail.)
For winpty64.dll, see [`:help terminal-ms-windows`](https://github.com/vim/vim/blob/2b926fcb3c5d8bd09a219009336bbec7c66ae67e/runtime/doc/terminal.txt#L387-L405).

Anyway, please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. Closing.
