### ISSUE TITLE
'incsearch': CTRL-R CTRL-W works strangely on the second and third hits

### ISSUE THREAD

**Issue by lkintact** [vim/vim#3325]
1. Execute `:set incsearch` 
2. Start a new buffer, put this text into it: `test1 test2 test3 test4 test5`.
3. Place the cursor somewhere within `test5`.
4. Hit <kbd>/</kbd> and type `te`, hit <kbd>ctrl-r</kbd><kbd>ctrl-w</kbd>. `test1` is inserted into the command line, this behavior is described at `:help incsearch`.
5. Hit <kbd>ctrl-r</kbd><kbd>ctrl-w</kbd> again. `test1test2` is put into the command line. This isn't described anywhere but seems logical - inserting the next word after the current match when the current match word has been already inserted.
6. Hit <kbd>ctrl-r</kbd><kbd>ctrl-w</kbd> one more time. `test1test2test5` is inserted into the command line, the words `test3` and `test4` are "skipped".

Since the second and following hits of <kbd>ctrl-r</kbd><kbd>ctrl-w</kbd> aren't documented this is probably not a bug at all, but maybe for the sake of consistency Vim should add `test3` at step 6 or stop inserting altogether at step 5?

Vim: gvim_8.1.0280_x86.zip

**Comment by brammool** [comment]
This is working as intended.  As you mention, first "test1" is under the cursor and put in the search command.  This then puts the cursor at the end of "test1", thus the next CTRL-R CTRL-W takes "test2".
The search command then becomes /test1test2, which has no matches.  Thus the cursor is put back where you started, in test5.  Thus the next CTRL-R CTRL-W takes 'test5'.

**Comment by lkintact** [comment]
I see, thank you for the explanation...
