### ISSUE TITLE
[feature request]Tag search by kind

### ISSUE THREAD

**Issue by tkhai** [vim/vim#3335]
All kinds of tags are considered as having the same priority, and sometimes it's difficult to find struct declaration in big projects. For example, in Linux kernel we have many patterns like:

struct xxx {
        struct file *file;
};

When someone wants to jump to "struct file" declarations, all the above patterns are contained in ":ts file" results. There are 83 declaration of file, while "S" kind is lost somewhere in the middle of them, and it's not easy to find it.

Could you please consider to implement some way to jump to specific kind of tags only? Say, after typing ":tsS file" the results will contain only "struct file" declarations, after ":tsM main" there will be only members of structures, etc. Thanks!

**Comment by chrisbra** [comment]
See #2871

**Comment by tkhai** [comment]
There is already work in progress. Fantastic. Thanks!

**Comment by brammool** [comment]
Since there is already work ongoing and this issue doesn't contain extra info, let's close this (even though the feature hasn't been implemented yet).
