### ISSUE TITLE
Feature request/prototype: :push for modifying the tagstack

### ISSUE THREAD

**Issue by idbrii** [vim/vim#3336]
I'm not sure if the opposition in #1628 to allowing tagfunc to be asynchronous is a roadblock, but I thought I'd suggest a simpler alternative: add a `:push` analog to `:pop`.

Allowing plugin writers (i.e., jedi, omnisharp) to `:push symbol-name` before jumping to 'symbol-name' would let them integrate with the tagstack. This approach wouldn't solve the "support CTRL-W ] and similar" problem or allow custom sources for `:tselect`.

Here's a prototype of this in vimscript:

    let g:tagimposter_tagfile = get(g:, 'tagimposter_tagfile', '~/.vim-cache/imposter.tags')

    function! Tagimposter_setup()
        if exists("g:tagimposter_has_hookedup_tagfile")
            return
        endif 
        let g:tagimposter_has_hookedup_tagfile = 1

        exec 'set tags+='. g:tagimposter_tagfile
    endf

    function! Tagimposter_pushtag(symbol)
        call Tagimposter_setup()
        let symbol = 'IMPOSTER_' . a:symbol
        " Tags are a symbol, a file, and a search expression.
        let tag_str = printf("%s\t%s\t/^%s$/;", symbol, expand("%:p"), getline('.'))
        exec "keepalt split +edit ". g:tagimposter_tagfile
        .,$delete _
        put! =tag_str
        write
        close
        exec 'tjump '. symbol
    endf

    command! -bar Push silent call Tagimposter_pushtag(expand("<cword>"))

    nnoremap <Leader>jT :<C-u> Push <Bar> OmniSharpGotoDefinition<CR>

(I just pushed a slightly more complete version of this code as [vim-tagimposter](https://github.com/idbrii/vim-tagimposter).)

By implementing natively in vim, we could avoid the tempfile, messing with the user's 'tags', and the inaccurate symbol name.

While not as full-featured as 'tagfunc', it looks like there's lots of interest in this base-level functionality:

* prabirshrestha/vim-lsp#49
* fatih/vim-go#667
* mhinz/vim-lookup#2
* Valloric/YouCompleteMe#1675
* natebosch/vim-lsc#89
* https://stackoverflow.com/questions/26291758/how-to-manually-push-stack-entry-into-vim-tagstack
* https://groups.google.com/forum/#!topic/rope-dev/2nU_iq09k2M
* http://lists.gnu.org/archive/html/help-global/2001-08/msg00004.html

**Comment by vim-ml** [comment]
Hi,

On Thu, Aug 16, 2018 at 2:16 PM, David Briscoe
<vim-dev-github@256bit.org> wrote:
> I'm not sure if the opposition in #1628 to allowing tagfunc to be
> asynchronous is a roadblock, but I thought I'd suggest a simpler
> alternative: add a :push analog to :pop.
>

I think it will be more flexible to add a VimL function to push and pop file
location information from the tag stack along with a tag name.

Regards,
Yegappan

>
> Allowing plugin writers (i.e., jedi, omnisharp) to :push symbol-name before
> jumping to 'symbol-name' would let them integrate with the tagstack. This
> approach wouldn't solve the "support CTRL-W ] and similar" problem or allow
> custom sources for :tselect.
>
> Here's a prototype of this in vimscript:
>
> let g:tagimposter_tagfile = get(g:, 'tagimposter_tagfile',
> '~/.vim-cache/imposter.tags')
>
> function! Tagimposter_setup()
>     if exists("g:tagimposter_has_hookedup_tagfile")
>         return
>     endif
>     let g:tagimposter_has_hookedup_tagfile = 1
>
>     exec 'set tags+='. g:tagimposter_tagfile
> endf
>
> function! Tagimposter_pushtag(symbol)
>     call Tagimposter_setup()
>     let symbol = 'IMPOSTER_' . a:symbol
>     " Tags are a symbol, a file, and a search expression.
>     let tag_str = printf("%s\t%s\t/^%s$/;", symbol, expand("%:p"),
> getline('.'))
>     exec "keepalt split +edit ". g:tagimposter_tagfile
>     .,$delete _
>     put! =tag_str
>     write
>     close
>     exec 'tjump '. symbol
> endf
>
> command! -bar Push silent call Tagimposter_pushtag(expand("<cword>"))
>
> nnoremap <Leader>jT :<C-u> Push <Bar> OmniSharpGotoDefinition<CR>
>
> (I just pushed a slightly more complete version of this code as
> vim-tagimposter.)
>
> By implementing natively in vim, we could avoid the tempfile, messing with
> the user's 'tags', and the inaccurate symbol name.
>
> While not as full-featured as 'tagfunc', it looks like there's lots of
> interest in this base-level functionality:
>
> prabirshrestha/vim-lsp#49
> fatih/vim-go#667
> mhinz/vim-lookup#2
> Valloric/YouCompleteMe#1675
> natebosch/vim-lsc#89
> https://stackoverflow.com/questions/26291758/how-to-manually-push-stack-entry-into-vim-tagstack
> https://groups.google.com/forum/#!topic/rope-dev/2nU_iq09k2M
> http://lists.gnu.org/archive/html/help-global/2001-08/msg00004.html
>

**Comment by yegappan** [comment]
Patch 8.1.0519 adds the gettagstack() and settagstack() functions for manipulating
the tag stack. The settagstack() function can be used to push items onto the
tag stack.

**Comment by k-takata** [comment]
Then I think this can be closed.

**Comment by andymass** [comment]
@yegappan, is it possible to use `:tag` to go forwards in the tag stack after using `settagstack()` then using `:pop` ?  It seems as though vim does not have enough information in the stack to go to newer tags which are not backed by a tag file.

**Comment by vim-ml** [comment]
Hi,

On Wed, Jan 9, 2019 at 8:26 PM Andy Massimino <vim-dev-github@256bit.org> wrote:
>
> @yegappan, is it possible to use :tag to go forwards in the tag stack after
> using settagstack() then using :pop ? It seems as though vim does not have
> enough information in the stack to go to newer tags which are not backed by a
> tag file.
>

Yes. The ":tag" command goes forward in the tag stack by searching for tags
in the tags file. So currently if the tags file is not present, then
you cannot jump
between the entries in the tag stack.

- Yegappan
