### ISSUE TITLE
:undojoin doesn't join :startinsert

### ISSUE THREAD

**Issue by maurges** [vim/vim#3352]
Steps to reproduce:
1) type some text: `a111<esc>`
2) execute `:undojoin | startinsert<cr>`
3) type some more text: `222<esc>`
4) undo: `u`

Expected result - line with no text inserted by you
Actual result: `111` still in the file

**Comment by Houl** [comment]
The next Insert mode where you type some text always starts a new change.  Maybe not expected, but at least documented: "This doesn't work by itself, because the next key press will start a new
change again." (:h :undojoin).

**Comment by maurges** [comment]
You are right, after further testing I concluded that this is consistent behavior and is to be expected. That's a big disappointment for me.
