### ISSUE TITLE
Suggestion: Make 'cursorline' take care of the visual indent generated by 'breakindent'?

### ISSUE THREAD

**Issue by slmjkdbtl** [vim/vim#3355]
![44315359-6ca50500-a3f1-11e8-8ccc-89e74209151a](https://user-images.githubusercontent.com/9929523/44371284-311b4100-a4ac-11e8-8c62-0f5cc2dbe083.jpg)

Now is has this hideous gap between the number column and the text visually indented by 'breakindent', hoping the visual indents could be rendered with the cursorline color

**Comment by chrisbra** [comment]
It might look weird, but it makes clear, that the indent does not actually exist in the line. Which is an advantage.

**Comment by chrisbra** [comment]
I am closing this.

**Comment by jake-stewart** [comment]
@chrisbra would you be open to PR which adds `cul` option to `'breakindentopt'` which makes the indent highlighted with `CursorLine`?

**Comment by chrisbra** [comment]
and that would only affect when cursorline is set?

**Comment by jake-stewart** [comment]
> and that would only affect when cursorline is set?

Yes it would only apply if cursorline is set and is the current line.

**Comment by jake-stewart** [comment]
Looking at the help pages I see an option called `'cursorlineopt'`. which would make sense to have `breakindent` in.

**Comment by jake-stewart** [comment]
Here are the two diffs. Quite a simple change.

['cursorlineopt'](https://github.com/jake-stewart/vim/commit/8438627180fdd933fa20db91432b062929921cc2)
['breakindentopt'](https://github.com/jake-stewart/vim/commit/9bc9fb2e3a988542cd062e3232adfbd6b3563546)

I think adding it to `'cursorlineopt'` is more consistent and discoverable.

**Comment by zeertzjq** [comment]
It's probably better to use `apply_cursorline_highlight()` so that the priority of the `CursorLine` highlight relative to other line highlight groups remains the same.

Also "bri" may be a better field name than the full "breakindent", as 'breakindentopt' also has a short field name "sbr".

**Comment by jake-stewart** [comment]
> It's probably better to use `apply_cursorline_highlight()` so that the priority of the `CursorLine` highlight relative to other line highlight groups remains the same.
> 
> Also "bri" may be a better field name than the full "breakindent", as 'breakindentopt' also has a short field name "sbr".

`apply_cursorline_highlight()` only modifies `wlv->line_attr`, whereas we need `wlv->char_attr`. I am unfamiliar with the codebase but I assume we could call `apply_cursorline_highlight()` and then manually set `wlv->char_attr` to `wlv->line_attr`?

**Comment by zeertzjq** [comment]
I'll create a PR to implement this soon.

**Comment by zeertzjq** [comment]
Update: actually changing `char_attr` is the correct approach, as a similar thing is already done for 'showbreak'.

**Comment by zeertzjq** [comment]
Hmm, there are three cases to consider:
- What should happen when 'cursorlineopt' contains "bri" and "line"
- What should happen when 'cursorlineopt' contains "bri" and "screenline"
- What should happen when 'cursorlineopt' contains "bri", but neither "line" and "screenline"

The first cases may be obvious, but the two other cases are not, because 'cursorline' doesn't apply to 'showbreak' either when 'cursorlineopt' contains "screenline".

**Comment by jake-stewart** [comment]
Unless I am mistaken, the behaviour is the exact same as before, even in regards to the inconsistency with`'showbreak'`.

You have pointed out an edge case of `bri` on its own. We could consider that an invalid option.
