### ISSUE TITLE
Netrw error: "Illegal PORT command"

### ISSUE THREAD

**Issue by geryogam** [vim/vim#3357]
I installed Vim 8.1.1 on Windows 10.

My `_vimrc` in `C:\Users\Maggyero` has the following lines:

```
set spell
set spelllang=en,fr
set spellsuggest=5
```

When I open Vim, I get the following message:

> Alerte : Liste de mots "fr.utf-8.spl" ou "fr.ascii.spl" introuvable

After clicking on "Ok", I type:

```
:set spell
```

and I get the following message:

> Cannot find spell file for "fr" in utf-8
> Do you want me to try downloading it?

After clicking on "Yes", I get the following message:

> Downloading fr.utf-8.spl...
> \*\*error\*\* (netrw) Illegal PORT command.^M
> \*\*warning\*\* (netrw) file <C:\Users\MAGGYERO\AppData\Local\Temp\VIA45B2.spl> not readable
> Could not find it, trying fr.ascii.spl...
> \*\*error\*\* (netrw) Illegal PORT command.^M
> \*\*warning\*\* (netrw) file <C:\Users\MAGGYERO\AppData\Local\Temp\VIA45B2.spl> not readable
> Sorry, downloading failed
> Alerte : Liste de mots "fr.utf-8.spl" ou "fr.ascii.spl" introuvable

**Comment by k-takata** [comment]
The message "Illegal PORT command" is an output of ftp command.
It seems that the active mode of FTP is blocked (by a firewall).
Try installing `wget` or `curl` in your $PATH.

Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. Closing.

**Comment by chrisbra** [comment]
Also please have a look at `:h netrw-ftp` to enable passive mode.

**Comment by geryogam** [comment]
Thank you @k-takata and @chrisbra.

It seems that `netrw` invokes `wget` or `fetch` (via `cmd`, not `powershell` which aliases `wget` for the built-in `Invoke-WebRequest` command) for retrieving the spell file:

    C:\WINDOWS\system32\cmd.exe /c (wget ^"http://ftp.vim.org/pub/vim/runtime/spell/fr.utf-8.spl^" -q -O ^"C:\Users\MAGGYERO\AppData\Local\Temp\VIA77E3.spl^")
    SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
    syswgetrc = C:\Program Files (x86)\GnuWin32/etc/wgetrc

and the suggestion file:

    C:\Windows\system32\cmd.exe /c (wget ^"http://ftp.vim.org/pub/vim/runtime/spell/fr.utf-8.sug^" -q -O ^"C:\Users\MAGGYERO\AppData\Local\Temp\VIA126E.sug^")
    SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
    syswgetrc = C:\Program Files (x86)\GnuWin32/etc/wgetrc

If `wget` or `fetch` is not in the PATH environment variable (which was my case), `netrw` invokes `ftp`.

In _active mode_ (the default), `ftp` opens a T.C.P. control connection to the server port 21 and accepts a T.C.P. data connection opened by the server to a client port between 1024 and 65635—so if the _client_ has a firewall or a NAT gateway it must be correctly set up.

In _passive mode_, `ftp` opens a T.C.P. control connection to the server port 21 and opens a T.C.P. data connection to a server port between 1024 and 65635—so if the _server_ has a firewall or a NAT gateway it must be correctly set up.

As we are behind a NAT gateway (and maybe a firewall) at the office, it might be the reason why `ftp` failed. Switching to passive mode (`:let g:netrw_ftp_cmd= "ftp -p"`) removed the errors but kept the warnings so the downloading is still failing, for a reason that I ignore (maybe because the server has a firewall or a NAT gateway that is not correctly set up, or simply because the server does not allow passive mode).

**So simply installing GNU Wget from Sourceforge and adding it to the PATH environment variable solved the issue: http://gnuwin32.sourceforge.net/packages/wget.htm**
