### ISSUE TITLE
colorschemes under $HOME/vimfiles/pack/*/opt/colors/ aren't added to menu in gvim

### ISSUE THREAD

**Issue by LunarLambda** [vim/vim#3359]
![image](https://user-images.githubusercontent.com/38919842/44422947-f802cf80-a584-11e8-9fbb-c3403e82c856.png)

Tab completion for :colorscheme shows them, but the set colorscheme menu only appears to show themes under $HOME/vimfiles/colors (and the default ones)

![image](https://user-images.githubusercontent.com/38919842/44423072-59c33980-a585-11e8-908b-a63d96dd08ba.png)

![image](https://user-images.githubusercontent.com/38919842/44423061-5039d180-a585-11e8-9c1c-034d453d70e3.png)

**Comment by brammool** [comment]
> Tab completion for :colorscheme shows them, but the set colorscheme
> menu only appears to show themes under $HOME/vimfiles/colors (and the
> default ones)

Does this patch fix it:

--- /vim/git/runtime/menu.vim   2018-07-23 05:09:05.597235618 +0200
+++ ../runtime/menu.vim 2018-08-21 22:04:01.845987971 +0200
@@ -356,6 +356,8 @@
   let s:did_setup_color_schemes = 1
 
   let n = globpath(&runtimepath, "colors/*.vim", 1, 1)
+  let n .= globpath(&runtimepath, "pack/*/start/*/colors/*.vim", 1, 1)
+  let n .= globpath(&runtimepath, "pack/*/opt/*/colors/*.vim", 1, 1)
 
   " Ignore case for VMS and windows, sort on name
   let names = sort(map(n, 'substitute(v:val, "\\c.*[/\\\\:\\]]\\([^/\\\\:]*\\)\\.vim", "\\1", "")'), 1)


-- 
ARTHUR:       Now stand aside worthy adversary.
BLACK KNIGHT: (Glancing at his shoulder) 'Tis but a scratch.
ARTHUR:       A scratch?  Your arm's off.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lifepillar** [comment]
Please note that if a user has many colorschemes (or many directories under `pack`), your patch may slow down opening new windows significantly: https://github.com/macvim-dev/macvim/issues/351.

Some time ago I submitted a pull request to MacVim (https://github.com/macvim-dev/macvim/pull/385), which added a “Find more colorschemes…“ menu item under Edit > Color Scheme, to mitigate the above mentioned issue. The pull request was merged, but then reverted because of a conflict with Vim's repo. So, maybe the changes in that pull request might be applied here?

**Comment by LunarLambda** [comment]
I will try the patch after work today, thank you

**Comment by chrisbra** [comment]
> Please note that if a user has many colorschemes (or many directories under pack), your patch may slow down opening new windows significantly: macvim-dev/macvim#351.

IIRC, menu.vim was changed to allow lazy loading. If I read the patch correctly, it should only affect the loading once the user selects "Show color schemes in menu". So it shouldn't slow down Vim anymore.

**Comment by chrisbra** [comment]
fixed with fc65cabb15d0236bc
