### ISSUE TITLE
Function naming conventions?

### ISSUE THREAD

**Issue by slmjkdbtl** [vim/vim#3372]
I noticed a lot of function names that use underscore notations are deprecated, like `buffer_name()` is replaced by `bufname()`, but there're still new functions that use underscore notations, like `reg_recording()`. Just wondering if there's a standard naming convention for vim api?

**Comment by brammool** [comment]
> I noticed a lot of function names that use underscore notations are
> deprecated, like `buffer_name()` is replaced by `bufname()`, but
> there're still new functions that use underscore notations, like
> `reg_recording()`. Just wondering if there's a standard naming
> convention for vim api?

It changes over time.  It's not so much about using or dropping an
underscore, but being consistent, and making it easier to find what you
are looking for.

I have added functions with a prefix, such as "term_", "timer_", "test_"
and "win_", just to make it easier to read it back.  It doesn't mean
every new function should have a prefix like that.

-- 
Our job was to build a computer information system for the branch banks.  We
were the perfect people for the job: Dean had seen a computer once, and I had
heard Dean talk about it.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
