### ISSUE TITLE
Drop support for Borland compiler?

### ISSUE THREAD

**Issue by thomasdziedzic** [vim/vim#3374]
The compiler itself is [dead](https://www.theregister.co.uk/2015/09/01/borland_c_now_legacy_as_embarcadero_releases_delphi_and_c_builder_10/).

In addition, I was going through some of the source code, and Borland specific code exists in a bunch of files:

```
$ git grep -i borland | wc -l
102
```

Thoughts on dropping support and cleaning the code up a bit?

**Comment by brammool** [comment]
> The compiler itself is [dead](https://www.theregister.co.uk/2015/09/01/borland_c_now_legacy_as_embarcadero_releases_delphi_and_c_builder_10/).
> 
> In addition, I was going through some of the source code, and Borland specific code exists in a bunch of files:
> 
> ```
> $ git grep -i borland | wc -l
> 102
> ```
> 
> Thoughts on dropping support and cleaning the code up a bit?

Yeah, I wonder if there is any reason for someone using the Borland
compiler.  I believe this was for MS-Windows, for which we have the free
MSVC compiler and the MinGW / msys compiler.  I can't think of a reason
why someone would be stuck with Borland.

-- 
The only way the average employee can speak to an executive is by taking a
second job as a golf caddie.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by tonymec** [comment]
Some time ago, when Steve Hall had temporarily ceased compiling Vim for Windows, I took over the task, and already then there were some constructs in the Vim source which the Borland compiler could not compile properly (in the Unicode support, which at the time was a relative novelty in Vim, IIRC); so I switched over to gcc (MinGW-of-Cygwin, at the time), and that worked perfectly.

If the Borland compiler is now dead, I don't see either why we should still support it since we have the free (as in beer) MSVC compiler and the free (as in speech) MinGW compiler.

Best regards,
Tony.

**Comment by chrisbra** [comment]
closing this in favor of #3377

**Comment by vim-ml** [comment]
Sorry for my naivety but what does " supporting borland compiler mean
", I have been using borland compiler due to school and had to use an
obscure ide for it, is it possible to use vim instead of it?

**Comment by thomasdziedzic** [comment]
Yes, it seems there is some support for using borland in vim.
This issue and the associated pull request are to remove support for compiling vim with borland, not to remove support for compiling with borland in vim.

See https://github.com/vim/vim/pull/3377/commits/404aafc2d4ad681e8b39ff4256c0cdd9f659afef and https://stackoverflow.com/questions/3031009/what-does-the-compiler-command-do-in-vim

**Comment by tonymec** [comment]
It is possible to edit any text file, including C source, with Vim, and it is possible to use Vim (with `+quickfix` compiled-in, see the output of `:version`) as an IDE for various compilers including Borland C, see `:help quickfix.txt`.

Best regards,
Tony.
