### ISSUE TITLE
Support Floating Window

### ISSUE THREAD

**Issue by ghost** [vim/vim#3379]
Hi, I'm a programmer using vim to write C/C++ code, when I coding, I use the Ctrl-n to complete my code, and i use the plugin to show the function prototype at vim command line, I always to low my head to see the command line, vim can implement the floating window to change this situaion? I think this feature will can protect the programmer's cervical vertebra.

**Comment by idbrii** [comment]
> i use the plugin to show the function prototype at vim command line

Have you tried using the preview window to show function prototype: `set completeopt+=preview`

See more: `:help completeopt`

Also, vim does support nonmaximized windows with gvim. You can size the window on your desktop with `set lines=100 columns=100`.

**Comment by ghost** [comment]
Ok,I'll try

**Comment by prabirshrestha** [comment]
Would be good to have a proper floating window support besides preview window. https://www.reddit.com/r/neovim/comments/ars2ad/want_to_try_with_neovims_floating_window/

![image](https://user-images.githubusercontent.com/287744/53469690-d0992d80-3a13-11e9-893c-c6bd61c7ec8c.png)

**Comment by brammool** [comment]
This was in the poll done last year.  It's on the roadmap after text properties.

**Comment by blayz3r** [comment]
This is still WIP right? Sending grep results to a floating window like below is still not possible right? 
![2019-08-11_18-20-02]
![33796988-ee959e98-dcc4-11e7-987c-e91d8108a22a](https://user-images.githubusercontent.com/12205650/63203799-de914800-c05f-11e9-9aa8-1b7de6e8a844.gif)

**Comment by brammool** [comment]
The popup window has been implemented.  And you can also use the popup window for preview.
For lines from a grep command you perhaps want to use popup_menu().
If there is something that isn't working, please open a specific issue for that.
