### ISSUE TITLE
packadd vs. runtimepath

### ISSUE THREAD

**Issue by mkoskar** [vim/vim#3393]
Having `packadd! ultisnips` in my `.vimrc` results in runtime path:

    ~/.vim
    ~/.vim/pack/custom/opt/ultisnips
    /usr/share/vim/vimfiles
    /usr/share/vim/vim81
    /usr/share/vim/vimfiles/after
    ~/.vim/after
    ~/.vim/pack/custom/opt/ultisnips/after

Even though `:help` documents this behavior

    If the directory pack/*/opt/{name}/after exists it is
    added at the end of 'runtimepath'.

shouldn't it rather look like following?

    ~/.vim
    ~/.vim/pack/custom/opt/ultisnips
    /usr/share/vim/vimfiles
    /usr/share/vim/vim81
    /usr/share/vim/vimfiles/after
    ~/.vim/pack/custom/opt/ultisnips/after
    ~/.vim/after

**Comment by chrisbra** [comment]
I think this is fixed by https://github.com/vim/vim/releases/tag/v8.1.0353

**Comment by k-takata** [comment]
Oh, #3409 was duplicate of this...

**Comment by mkoskar** [comment]
Running `8.1 Included patches: 1-374`

I get:

```
~/.vim
~/.vim/pack/custom/opt/ultisnips
/usr/share/vim/vimfiles
/usr/share/vim/vim81
~/.vim/pack/custom/opt/ultisnips/after
/usr/share/vim/vimfiles/after
~/.vim/after
```

I would object that `/usr/share/vim/vimfiles/after` should come *before* `~/.vim/pack/custom/opt/ultisnips/after`, i.e., before and after dirs should be "mirrored" over `$VIMRUNTIME` (`/usr/share/vim/vim81` in this case).

Can we get this reopened?

**Comment by brammool** [comment]
What's the problem?  the package "after" directory would come from the distributed plugin, thus you might want to overrule things from that plugin in your personal "after" directory

**Comment by mkoskar** [comment]
To rephrase it, I would expect "after" directories to be in reverse order of directories before `$VIMRUNTIME`. IMHO it makes sense and is pretty straightforward rule.

**Comment by jamessan** [comment]
To be clear, the part that's odd is the order of these two:

```
~/.vim/pack/custom/opt/ultisnips/after
/usr/share/vim/vimfiles/after
```

One would expect stuff under ~/.vim to come after stuff in `/usr` so the user can override.
