### ISSUE TITLE
Windows: job_info: incorrect cmd info (removed backslashes)

### ISSUE THREAD

**Issue by blueyed** [vim/vim#3404]
Using `job_start('C:\windows\system32\cmd.exe /c doesnotexist')` appears to produce the following output via `job_info()`:

The "cmd" in there appears to look wrong (i.e. the backslashes are removed there):

> Vim job: {'status': 'run', 'cmd': ['C:windowssystem32cmd.exe', '/c', 'doesnotexist'], 'stoponexit': 'term', 'tty_out': '', 'exitval': 0, 'exit_cb': 0, 'tty_in': '', 'channel': 'channel 96 open', 'process': 2820}.

Using Vim 8.1.1, `noshellslash` and the default shell (`C:\windows\system32\cmd.exe`).

It seems to be only cosmetic, since it tries to run "doesnotexist":

```
> [verbose]: [118.112:3:1] Starting async job [string]: C:\windows\system32\cmd.exe /c doesnotexist.
> [debug  ]: [118.112:3:1] cwd: C:\projects\neomake.
> [debug  ]: [118.112:3:1] Vim job: {'status': 'run', 'cmd': ['C:windowssystem32cmd.exe', '/c', 'doesnotexist'], 'stoponexit': 'term', 'tty_out': '', 'exitval': 0, 'exit_cb': 0, 'tty_in': '', 'channel': 'channel 96 open', 'process': 2820}.
> [debug  ]: [118.112:3:1] Vim channel: {'status': 'open', 'id': 96, 'in_io': 'pipe', 'in_timeout': 2000, 'err_mode': 'RAW', 'in_status': 'open', 'out_io': 'pipe', 'err_io': 'pipe', 'err_status': 'open', 'out_timeout': 2000, 'out_status': 'open', 'out_mode': 'RAW', 'in_mode': 'RAW', 'err_timeout': 2000}.
> [D +0.03]: [118.112:3:1] stderr: unnamed_maker: ['''doesnotexist'' is not recognized as an internal or external command,', 'operable program or batch file.', ''].
> [D +0.03]: [118.112:3:1] exit: unnamed_maker: 1.
```

**Comment by mattn** [comment]
This is not an issue of job_info. When string is passed to job_start, the string is parsed to list of arguments as shell command. And backslash are treated as escape characters. Addressed #3517
