### ISSUE TITLE
Gvim in diffmode colors identical lines 'DiffChange'

### ISSUE THREAD

**Issue by lkintact** [vim/vim#3406]
1. Download the attached .txt files and run Gvim with this command:
`gvim.exe --cmd "language messages English" --cmd "set enc=utf-8" --clean -d 1.txt 2.txt `.
2. (The window with `1.txt` should be active), goto line 48129 with `48129gg`.
3. The two lines in `1.txt` and `2.txt`,
```
№
1
```
being absolutely identical (including end-of-lines and the absence of trailing white spaces) are displayed in the `DiffChange` color for some reason.

Sorry for the nonsensical files, I just tried to compare two different editions of a book and removed just enough of the text for the bug to stay reproducible.

[1.txt](https://github.com/vim/vim/files/2346463/1.txt)
[2.txt](https://github.com/vim/vim/files/2346464/2.txt)

OS: Windows 7,
Gvim: gvim_8.1.0346_x86.zip

**Comment by brammool** [comment]
I cannot reproduce the problem (Linux)

**Comment by lkintact** [comment]
I see... Here is the output of `:set all` :
```

--- Options ---
  aleph=224           filetype=text     nomodified            suffixesadd=
noarabic              fixendofline        more                swapfile
  arabicshape       nofkmap               mouse=a             swapsync=fsync
noallowrevins         foldclose=        nomousefocus          switchbuf=
noaltkeymap           foldcolumn=2        mousehide           synmaxcol=3000
  ambiwidth=single    foldenable          mousemodel=popup    syntax=text
noautochdir           foldexpr=0          mousetime=500       tabline=
noautoindent          foldignore=#        mzquantum=100       tabpagemax=10
noautoread            foldlevel=0         nrformats=bin,hex   tabstop=8
noautowrite           foldlevelstart=-1 nonumber              tagbsearch
noautowriteall        foldmethod=diff     numberwidth=4       tagcase=followic
  background=light    foldminlines=1      omnifunc=           taglength=0
nobackup              foldnestmax=20    noopendevice          tagrelative
  backupcopy=auto     formatexpr=         operatorfunc=       tags=./tags,tags
  backupext=~         formatoptions=tcq nopaste               tagstack
  balloondelay=600    formatprg=          pastetoggle=        tcldll=tcl86t.dll
noballooneval       nogdefault            patchexpr=          term=builtin_gui
  balloonexpr=        guifont=            patchmode=        notermbidi
  belloff=            guifontwide=        path=.,,            termencoding=
nobinary              guioptions=egmrLT nopreserveindent      termwinkey=
nobomb                guipty              previewheight=12    termwinsize=
nobreakindent         guitablabel=      nopreviewwindow     noterse
  breakindentopt=     guitabtooltip=      printdevice=        textauto
  browsedir=last      helpheight=20       printoptions=       textmode
  bufhidden=          helplang=En         prompt              textwidth=0
  buflisted         nohidden              pumheight=0         thesaurus=
  buftype=            history=200         pumwidth=15       notildeop
  cdpath=,,         nohkmap               pythonthreehome=    timeout
  cedit=^F          nohkmapp              pythonhome=         timeoutlen=1000
  charconvert=      nohlsearch            pyxversion=0        title
nocindent             icon                quoteescape=\       titlelen=85
  cinoptions=         iconstring=       noreadonly            titlestring=
  clipboard=        noignorecase          redrawtime=2000     ttimeout
  cmdheight=1         imactivatefunc=     regexpengine=0      ttimeoutlen=100
  cmdwinheight=7    noimcmdline         norelativenumber      ttybuiltin
  colorcolumn=      noimdisable           remap             nottyfast
  columns=80          iminsert=0          renderoptions=      ttyscroll=999
  commentstring=      imsearch=-1         report=2            undodir=.
nocompatible          imstatusfunc=       restorescreen     noundofile
  concealcursor=      includeexpr=      norevins              undolevels=1000
  conceallevel=0      incsearch         norightleft           undoreload=10000
  completefunc=       indentexpr=         ruler               updatecount=200
noconfirm           noinfercase           rulerformat=        updatetime=4000
nocopyindent        noinsertmode          scroll=11           varsofttabstop=
  cpoptions=aABceFs   isprint=@,~-255     scrollbind          vartabstop=
  cryptmethod=zip     joinspaces          scrolljump=1        verbose=0
  cscopepathcomp=0    key=                scrolloff=5         verbosefile=
  cscopeprg=cscope    keymap=           nosecure              viminfofile=NONE
  cscopequickfix=     keymodel=           selectmode=         virtualedit=
nocscoperelative      keywordprg=:help    shellcmdflag=/c   novisualbell
nocscopetag           langmap=            shellquote=         warn
  cscopetagorder=0    langmenu=         noshellslash        noweirdinvert
nocscopeverbose       langnoremap         shelltemp           whichwrap=b,s
  cursorbind        nolangremap           shellxquote=(       wildchar=<Tab>
nocursorcolumn        laststatus=1      noshiftround          wildcharm=0
nocursorline        nolazyredraw          shiftwidth=8        wildignore=
  debug=            nolinebreak         noshortname         nowildignorecase
nodelcombine          lines=25            showbreak=          wildmenu
  dictionary=         linespace=1         showcmd             wildmode=full
  diff              nolisp              noshowfulltag         wildoptions=
  diffexpr=         nolist              noshowmatch           winaltkeys=menu
  diffopt=filler      listchars=eol:$     showmode            window=24
nodigraph           noloadplugins         showtabline=1       winheight=1
  display=truncate    luadll=lua53.dll    sidescroll=0      nowinfixheight
  eadirection=both    magic               sidescrolloff=0   nowinfixwidth
noedcompatible        makeef=             signcolumn=auto     winminheight=1
  emoji               makeencoding=     nosmartcase           winminwidth=1
  encoding=utf-8      makeprg=make      nosmartindent         winwidth=20
  endofline           matchtime=5       nosmarttab          nowrap
  equalalways         maxcombine=2        softtabstop=0       wrapmargin=0
  equalprg=           maxfuncdepth=100  nospell               wrapscan
noerrorbells          maxmapdepth=1000    spellfile=          write
  esckeys             maxmem=1001186      spelllang=en      nowriteany
  eventignore=        maxmemtot=1001186   spellsuggest=best   writebackup
noexpandtab           menuitems=25      nosplitbelow          writedelay=0
noexrc                modeline          nosplitright
  fileformat=dos      modelines=5         startofline
  fileignorecase      modifiable          statusline=
  backspace=indent,eol,start
  backupdir=.,~\AppData\Local\Temp,c:\tmp,c:\temp
  backupskip=C:\Users\***\AppData\Local\Temp\*,C:\Users\***\AppData\Local\Temp\*
  breakat= ^I!@*-+;:,./?
  casemap=internal,keepascii
  cinkeys=0{,0},0),:,0#,!^F,o,O,e
  cinwords=if,else,while,do,for,switch
  comments=fb:-,fb:*
  complete=.,w,b,u,t,i
  completeopt=menu,preview
  define=^\s*#\s*define
  directory=.,~\AppData\Local\Temp,c:\tmp,c:\temp
  errorfile=errors.err
  errorformat=%f(%l) : %t%*\D%n: %m,%*[^"]"%f"%*\D%l: %m,%f(%l) : %m,%*[^ ] %f %l: %m,%f:%l:%c:%m,%f(%l):%m,%f:%l:%m,%f|%l| %m
  fileencoding=utf-8
  fileencodings=ucs-bom,utf-8,default,latin1
  fileformats=dos,unix
  fillchars=vert:|,fold:-
  foldmarker={{{,}}}
  foldopen=block,hor,mark,percent,quickfix,search,tag,undo
  foldtext=foldtext()
  formatlistpat=^\s*\d\+[\]:.)}\t ]\s*
  grepformat=%f:%l:%m,%f:%l%m,%f  %l%m
  grepprg=findstr /n
  guicursor=n-v-c:block-Cursor/lCursor,ve:ver35-Cursor,o:hor50-Cursor,i-ci:ver25-Cursor/lCursor,r-cr:hor20-Cursor/lCursor,sm:block-Cursor-blinkwait175-blinkoff150-blinkon175
  helpfile=~\Downloads\vim\vim81\doc\help.txt
  highlight=8:SpecialKey,~:EndOfBuffer,@:NonText,d:Directory,e:ErrorMsg,i:IncSearch,l:Search,m:MoreMsg,M:ModeMsg,n:LineNr,N:CursorLineNr,r:Question,s:StatusLine,S:StatusLineNC,c:VertSplit,t:Title,v:Visual,V:VisualNOS,w:WarningMsg,W:WildMenu,f:Folded,F:FoldColumn,A:DiffAdd,C:DiffChange,D:DiffDelete,T:DiffText,>:SignColumn,-:Conceal,B:SpellBad,P:SpellCap,R:SpellRare,L:SpellLocal,+:Pmenu,=:PmenuSel,x:PmenuSbar,X:PmenuThumb,*:TabLine,#:TabLineSel,_:TabLineFill,!:CursorColumn,.:CursorLine,o:ColorColumn,q:QuickFixLine,z:StatusLineTerm,Z:StatusLineTermNC
  include=^\s*#\s*include
  indentkeys=0{,0},:,0#,!^F,o,O,e
  isfname=@,48-57,/,\,.,-,_,+,,,#,$,%,{,},[,],:,@-@,!,~,=
  isident=@,48-57,_,128-167,224-235
  iskeyword=@,48-57,_,128-167,224-235
  lispwords=defun,define,defmacro,set!,lambda,if,case,let,flet,let*,letrec,do,do*,define-syntax,let-syntax,letrec-syntax,destructuring-bind,defpackage,defparameter,defstruct,deftype,defvar,do-all-symbols,do-external-symbols,do-symbols,dolist,dotimes,ecase,etypecase,eval-when,labels,macrolet,multiple-value-bind,multiple-value-call,multiple-value-prog1,multiple-value-setq,prog1,progv,typecase,unless,unwind-protect,when,with-input-from-string,with-open-file,with-open-stream,with-output-to-string,with-package-iterator,define-condition,handler-bind,handler-case,restart-bind,restart-case,with-simple-restart,store-value,use-value,muffle-warning,abort,continue,with-slots,with-slots*,with-accessors,with-accessors*,defclass,defmethod,print-unreadable-object
  matchpairs=(:),{:},[:]
  maxmempattern=1000
  mkspellmem=460000,2000,500
  mouseshape=i-r:beam,s:updown,sd:udsizing,vs:leftright,vd:lrsizing,m:no,ml:up-arrow,v:rightup-arrow
  mzschemedll=libracket3m_a36fs8.dll
  mzschemegcdll=libracket3m_a36fs8.dll
  packpath=~\Downloads\vim/vimfiles,~\Downloads\vim\vim81,~\Downloads\vim/vimfiles/after
  paragraphs=IPLPPPQPP TPHPLIPpLpItpplpipbp
  perldll=perl524.dll
  printfont=Courier_New:h10
  printheader=%<%f%h%m%=Page %N
  pythonthreedll=python36.dll
  pythondll=python27.dll
  rightleftcmd=search
  rubydll=msvcrt-ruby240.dll
  runtimepath=~\Downloads\vim/vimfiles,~\Downloads\vim\vim81,~\Downloads\vim/vimfiles/after
  scrollopt=ver,jump,hor
  sections=SHNHH HUnhsh
  selection=inclusive
  sessionoptions=blank,buffers,curdir,folds,help,options,tabpages,winsize,terminal
  shell=C:\Windows\system32\cmd.exe
  shellpipe=>%s 2>&1
  shellredir=>%s 2>&1
  shellxescape="&|<>()@^
  shortmess=filnxtToO
  spellcapcheck=[.?!]\_[\])'"^I ]\+
  suffixes=.bak,~,.o,.h,.info,.swp,.obj
  termwinscroll=10000
  titleold=<c1><eb><e0><e3><ee><e4><e0><f0><e8><ec> <e7><e0> <e8><f1><ef><ee><eb><fc><e7><ee><e2><e0><ed><e8><e5> Vim
  ttytype=builtin_gui
  viewdir=~\Downloads\vim/vimfiles/view
  viewoptions=folds,options,cursor,curdir
  viminfo='100,<50,s10,h,rA:,rB:
  winptydll=winpty32.dll

```
Is there any other info I can provide that might help with the issue?

**Comment by lkintact** [comment]
I also noticed that after reducing the files sizes (for example, removing lines 1-48128 from `1.txt` and lines 1-48817 from `2.txt`, so that both files start with the two lines in question), the problem disappears.

**Comment by b-nik** [comment]
I can reproduce this on Ubuntu 16.04 64bit (vim 8.1.0346) on both tui vim and gvim.

Going to the said line vim displays them as different (pink)

I tried entering a new line after the character "1" and that seemed to fix the color, even after undoing that change:
(on 1.txt) 48130ggo<esc>u

**Comment by lkintact** [comment]
>   (on 1.txt) 48130ggou

The problem reappears to me if after executing this command sequence I go to Normal mode with <kbd>Esc</kbd> and execute `:diffupdate`.

**Comment by b-nik** [comment]
Ah, you're right, I assumed diffupdate was automatic for some reason.

**Comment by vim-ml** [comment]
On 2018-09-05, b-nik wrote:
> Ah, you're right, I assumed diffupdate was automatic for some reason.

It is automatic, to an extent, but it doesn't work in all cases.
See ":help :diffupdate".

Regards,
Gary

**Comment by chrisbra** [comment]
can you please re-check with a current Vim and internal diff mode enabled?

**Comment by b-nik** [comment]
Seems to have been fixed for me (8.1.0369, after manually doing set diffopt=internal,filler due to not having the 0370 fix)

**Comment by chrisbra** [comment]
so let me close this

**Comment by lkintact** [comment]
@chrisbra I just tried it with the latest build for Windows x86 (https://github.com/vim/vim-win32-installer/releases/download/v8.1.0374/gvim_8.1.0374_x86.zip), started Gvim with the same command (`gvim.exe --cmd "language messages English" --cmd "set enc=utf-8" --clean -d 1.txt 2.txt`), `'diffopt'` was set to `internal,filler`.

To me the problem wasn't fixed, but rather changed: instead of hiding the two lines in both windows in folds (since they are  identical), Gvim displays them in the `DiffAdd` color in the window with `1.txt` and draws two filler lines in the one for `2.txt`. The line above, "8—10", is also affected in the same way.

Here are screenshots for making it more clear.
The situation I had in post 1, Gvim 8.1.0346_x86:

![gvim_8 1 0346_x86](https://user-images.githubusercontent.com/24726299/45485817-9a1b6f00-b761-11e8-8806-32629a51de5a.png)


The situation I have now, Gvim 8.1.0374_x86:

![gvim_8 1 0374_x86](https://user-images.githubusercontent.com/24726299/45485823-9daef600-b761-11e8-9e5c-337569c59a0c.png)

I also noticed that 8.1.0374 performs this particular diff operation about four times slower than 8.1.0346.

**Comment by chrisbra** [comment]
this is my screenshot:
![screenshot](https://user-images.githubusercontent.com/244927/45488253-16fa1900-b761-11e8-87f5-85b4b2b7ae78.png)

That looks actually reasonable correct. 

However I would have expected the internal diff to be a lot faster.

**Comment by chrisbra** [comment]
BTW: I did some profiling but did not have time to look into it:

https://gist.github.com/chrisbra/1bab02036679cda05abe9cb83605a691#file-diff_internal_profile-txt

https://gist.github.com/chrisbra/1bab02036679cda05abe9cb83605a691#file-diff_external_profile-txt

**Comment by lkintact** [comment]
Thanks for the profiling.

>However I would have expected the internal diff to be a lot faster.

I figured out it's the internal diff algorithm that affects the diff speed (which is of course obvious, but since the `algorithm` item in the ` 'diffopt'` option is rather new, at first I didn't even know it existed).

I tried all the algorithm variants, setting them with a command line argument, and here are the resulting screenshots, Gvim version still 8.1.0374:

1. "myers", the default, turned out to be the one that works slow (which I wrote about above), the other three seem much faster: `gvim.exe --cmd "language messages English" --cmd "set enc=utf-8" --cmd "set diffopt=internal,filler,algorithm:myers" --clean -d 1.txt 2.txt`

![myers](https://user-images.githubusercontent.com/24726299/45491220-dce54300-b771-11e8-92c5-45e4312d38dd.png)

2. "minimal": `gvim.exe --cmd "language messages English" --cmd "set enc=utf-8" --cmd "set diffopt=internal,filler,algorithm:minimal" --clean -d 1.txt 2.txt`

![minimal](https://user-images.githubusercontent.com/24726299/45491423-5bda7b80-b772-11e8-92b2-c8a42b21d502.png)

3. "patience": `gvim.exe --cmd "language messages English" --cmd "set enc=utf-8" --cmd "set diffopt=internal,filler,algorithm:patience" --clean -d 1.txt 2.txt`

![patience](https://user-images.githubusercontent.com/24726299/45491578-b2e05080-b772-11e8-93bd-498d37420e9b.png)

4. "histogram": `gvim.exe --cmd "language messages English" --cmd "set enc=utf-8" --cmd "set diffopt=internal,filler,algorithm:histogram" --clean -d 1.txt 2.txt`

![histogram](https://user-images.githubusercontent.com/24726299/45491613-c7244d80-b772-11e8-9b41-90106ecbe464.png)


>That looks actually reasonable correct.

Sorry, I don't understand why you see this as correct. Shouldn't the two identical lines be hidden in folds (as they are with the "minimal", "patience" and "histogram" algorithms on the screenshots above), or maybe I just need to wait for a more detailed description at `:help diffopt` of how "myers" works?

**Comment by chrisbra** [comment]
Please have a look at the 'context' suboption of the 'diffopt' setting.

**Comment by imgaoyang** [comment]
ok


On 9/13/2018 23:14，Christian Brabandt<notifications@github.com> wrote：

Please have a look at the 'context' suboption of the 'diffopt' setting.

**Comment by lkintact** [comment]
>Please have a look at the 'context' suboption of the 'diffopt' setting.

I did, and tried varying it, but regardless of its value (0, 1, 50, not set at all, etc.) the situation when the "myers" algorithm is used stays the same: the two lines don't get hidden in folds in both windows, but are displayed on the left in the `DiffAdd` color and shown as absent (with filler lines) on the right.

**Comment by chrisbra** [comment]
wait a second. Are you saying the default myers algorithm is wrong here? Can you post the screenshot again and mark the lines you don't expect to be there?

**Comment by lkintact** [comment]
>Are you saying the default myers algorithm is wrong here?

I can't say for sure, but at least it looks so.

This is what I think is wrong (using "myers"):
1. `gvim.exe --cmd "language messages English" --cmd "set enc=utf-8" --cmd "set diffopt=internal,filler,algorithm:myers" --clean -d 1.txt 2.txt`
2. `:windo set list`
3. <kbd>ctrl-w</kbd> <kbd>w</kbd> to switch back to 1.txt
4. `:48129`
5. The whole area outlined in red shouldn't be there as it's the same for both 1.txt and 2.txt and should be hidden in a fold:

![myers_outlined](https://user-images.githubusercontent.com/24726299/45502049-98ff3780-b78b-11e8-91a3-9edb97d45297.png)


And this is what I think is correct (using an algorithm other than "myers", for example "minimal"): 
1. `gvim.exe --cmd "language messages English" --cmd "set enc=utf-8" --cmd "set diffopt=internal,filler,algorithm:minimal" --clean -d 1.txt 2.txt`
2. `:windo set list`
3. <kbd>ctrl-w</kbd> <kbd>w</kbd> to switch back to 1.txt
4. `:48129`
5. The area is hidden in a fold:

![minimal](https://user-images.githubusercontent.com/24726299/45502364-7883ad00-b78c-11e8-8250-6af456f52f66.png)

6. Hitting <kbd>z</kbd><kbd>a</kbd> opens it, showing that the folded area is the same for both files:

![minimal_unfold](https://user-images.githubusercontent.com/24726299/45502449-abc63c00-b78c-11e8-93e0-117128cc9ba0.png)
