### ISSUE TITLE
Put 'after' directories of packages before '~/.vim/after' in the runtimepath

### ISSUE THREAD

**Issue by smancill** [vim/vim#3409]
When having a package that contains an `after` directory, the runtimepath looks like

    /Users/smancill/.vim
    /Users/smancill/.vim/pack/smancill/start/foo
    /usr/local/share/vim/vimfiles
    /usr/local/share/vim/vim81
    /usr/local/share/vim/vimfiles/after
    /Users/smancill/.vim/after
    /Users/smancill/.vim/pack/smancill/start/foo/after

And `:scriptnames` shows:

      1: ~/.vim/vimrc
      2: /usr/local/Cellar/vim/8.1.0300/share/vim/vim81/plugin/getscriptPlugin.vim
      3: /usr/local/Cellar/vim/8.1.0300/share/vim/vim81/plugin/gzip.vim
      4: /usr/local/Cellar/vim/8.1.0300/share/vim/vim81/plugin/logiPat.vim
      5: /usr/local/Cellar/vim/8.1.0300/share/vim/vim81/plugin/manpager.vim
      6: /usr/local/Cellar/vim/8.1.0300/share/vim/vim81/plugin/matchparen.vim
      7: /usr/local/Cellar/vim/8.1.0300/share/vim/vim81/plugin/netrwPlugin.vim
      8: /usr/local/Cellar/vim/8.1.0300/share/vim/vim81/plugin/rrhelper.vim
      9: /usr/local/Cellar/vim/8.1.0300/share/vim/vim81/plugin/spellfile.vim
     10: /usr/local/Cellar/vim/8.1.0300/share/vim/vim81/plugin/tarPlugin.vim
     11: /usr/local/Cellar/vim/8.1.0300/share/vim/vim81/plugin/tohtml.vim
     12: /usr/local/Cellar/vim/8.1.0300/share/vim/vim81/plugin/vimballPlugin.vim
     13: /usr/local/Cellar/vim/8.1.0300/share/vim/vim81/plugin/zipPlugin.vim
     14: ~/.vim/pack/smancill/start/foo/plugin/foo.vim
     15: ~/.vim/after/plugin/overrides.vim
     16: ~/.vim/pack/smancill/start/foo/after/plugin/foo.vim

This prevents the user to override any setting set by the package in its `after` directory, because `~/.vim/after` is sourced before `foo/after`.

The `~/.vim/after` directory should always be the last in the `runtimepath`, I think.

**Comment by brammool** [comment]
> When having a package that contains an `after` directory, the runtimepath looks like
> 
>     /Users/smancill/.vim
>     /Users/smancill/.vim/pack/smancill/start/foo
>     /usr/local/share/vim/vimfiles
>     /usr/local/share/vim/vim81
>     /usr/local/share/vim/vimfiles/after
>     /Users/smancill/.vim/after
>     /Users/smancill/.vim/pack/smancill/start/foo/after
> 
> And `:scriptnames` shows:
> 
>       1: ~/.vim/vimrc
>       2: /usr/local/Cellar/vim/8.1.0300/share/vim/vim81/plugin/getscriptPlugin.vim
>       3: /usr/local/Cellar/vim/8.1.0300/share/vim/vim81/plugin/gzip.vim
>       4: /usr/local/Cellar/vim/8.1.0300/share/vim/vim81/plugin/logiPat.vim
>       5: /usr/local/Cellar/vim/8.1.0300/share/vim/vim81/plugin/manpager.vim
>       6: /usr/local/Cellar/vim/8.1.0300/share/vim/vim81/plugin/matchparen.vim
>       7: /usr/local/Cellar/vim/8.1.0300/share/vim/vim81/plugin/netrwPlugin.vim
>       8: /usr/local/Cellar/vim/8.1.0300/share/vim/vim81/plugin/rrhelper.vim
>       9: /usr/local/Cellar/vim/8.1.0300/share/vim/vim81/plugin/spellfile.vim
>      10: /usr/local/Cellar/vim/8.1.0300/share/vim/vim81/plugin/tarPlugin.vim
>      11: /usr/local/Cellar/vim/8.1.0300/share/vim/vim81/plugin/tohtml.vim
>      12: /usr/local/Cellar/vim/8.1.0300/share/vim/vim81/plugin/vimballPlugin.vim
>      13: /usr/local/Cellar/vim/8.1.0300/share/vim/vim81/plugin/zipPlugin.vim
>      14: ~/.vim/pack/smancill/start/foo/plugin/foo.vim
>      15: ~/.vim/after/plugin/overrides.vim
>      16: ~/.vim/pack/smancill/start/foo/after/plugin/foo.vim
> 
> This prevents the user to override any setting set by the package in its `after` directory, because `~/.vim/after` is sourced before `foo/after`.
> 
> The `~/.vim/after` directory should always be the last in the `runtimepath`, I think.

Yes, the package "after" directory was simply added at the end.  It's
better to insert it before the first "after" directory found in 'rtp'.

Looking closer at this, I also see that if the package directory is not
in 'rtp' at all, it gets added at the end of 'rtp', which means after
any existing "after" directory.  It should go before the first "after"
directory.

-- 
How To Keep A Healthy Level Of Insanity:
13. Go to a poetry recital and ask why the poems don't rhyme.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
