### ISSUE TITLE
Feature request: make `:verbose {nnoremap|command|...}` include the line address of mappings, commands, ...

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#3415]
`:verbose` is useful to get the last file from which a mapping, command, autocmd, or abbreviation has been installed.
But it doesn't print the address of the line.
If it did, when you have an issue with a mapping, you could do:

    put =execute('verbose nnoremap <your key>')

... which would write in your buffer something like (assuming `:verbose` separates the path to the file and the line address with a colon):

    n  <your key>         <rhs>
    	Last set from /path/to/file.vim:123

Then, by pressing `C-w F` on the path, not only would Vim open a split window to display the file installing the mapping (like it does already now), but it would also position the cursor on the right line.

Would it be possible to modify the output of `:verbose` so that it includes the line address from which an element of interface has been installed?

**Comment by lacygoill** [comment]
Sorry, I didn't think about the possibility that the mapping is installed from a function, or something more complex like a lambda in a timer... and not directly sourced from a file.

**Comment by andymass** [comment]
Lambda complications aside, I think this would be handled by #3362
