### ISSUE TITLE
statusline not redrawn when terminal title changes

### ISSUE THREAD

**Issue by joshtriplett** [vim/vim#3418]
`term_gettitle` makes it possible to set a statusline that includes the current terminal title, but when the command running in the terminal sets that title, the statusline doesn't get redrawn.

Please redraw the statusline of windows associated with the terminal buffer when the terminal title changes.

**Comment by brammool** [comment]
This should be fixed by patch 8.2.5055.
If you still see the problem please reopen the issue.
