### ISSUE TITLE
Terminal window output hard-wraps after command finishes

### ISSUE THREAD

**Issue by niekomaatjes** [vim/vim#3420]
1. Start Vim 8.0 on Ubuntu 18.04.1 with `vim -N -u NONE`
2. Run a command in a terminal window: :term bash -c "for i in \`seq 1 1000\`; do echo -n $i; done"

Problem: the text hard-wraps to the terminal width, even though the output contains no newlines

3. Start gVim 8.1.1 on Windows 10 with `gvim.exe -N -u NONE`
4. Open a new terminal window: :term cmd.exe
5. Run the following command: dir /a /s /b
6. Resize the window so that text starts to wrap
7. Resize the window back so that text doesn't wrap anymore

Problem: the text mostly wraps just fine while the window is running, but sometimes completely screws up

![vim](https://user-images.githubusercontent.com/15003445/45304634-cabc9800-b518-11e8-83e4-e3799d2473cf.gif)

If I run the same commands in an actual command prompt or PowerShell, then wrapping works fine.

8. Exit the command; the terminal window changes from [running] to [finished]

Problem: the text again hard-wraps to the last terminal width

9. Start Vim 8.0 on Ubuntu 18.04.1 with `vim -N -u NONE`
10. Run: :r!for i in \`seq 1 1000\`; do echo -n $i; done
11. Start gVim 8.1.1 on Windows 10 with `gvim.exe -N -u NONE`
12. Run: :r!dir /a /s /b

These commands run just fine and do not hard-wrap output

**Comment by brammool** [comment]
This is normal behavior for a terminal. Xterm does exactly the same thing.  I don't think there is a way to make this work, because Vim doesn't get the "unwrapped" lines, libvterm does the wrapping.

**Comment by chrisbra** [comment]
so closing.
