### ISSUE TITLE
gvim does not compile  on RHEL5 with GTK 2.10.4

### ISSUE THREAD

**Issue by arenieri** [vim/vim#3421]
gvim does not compile  on RHEL5 with GTK 2.10.4
compile error message is:
```
#gcc -std=gnu99 -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng12     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/gui_gtk_x11.o gui_gtk_x11.c
gui_gtk_x11.c: In function ‘gui_gtk_get_screen_geom_of_win’:
gui_gtk_x11.c:5019: warning: implicit declaration of function ‘gtk_widget_get_window’
gui_gtk_x11.c:5019: warning: initialization makes pointer from integer without a cast
```
Linker error message is:
```
objects/gui_gtk_x11.o: In function `gui_gtk_get_screen_geom_of_win':
/users/arenieri/my_sw/vim.git/src/gui_gtk_x11.c:5019: undefined reference to `gtk_widget_get_window'
collect2: ld returned 1 exit status
link.sh: Linking failed
make[1]: *** [vim] Error 1
make[1]: Leaving directory `/users/arenieri/my_sw/vim.git/src'
make: *** [first] Error 2
```
The issue is related to changes done to fix issue #3268

**Comment by brammool** [comment]
> gvim does not compile  on RHEL5 with GTK 2.10.4
> compile error message is:
> ```
> #gcc -std=gnu99 -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng12     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/gui_gtk_x11.o gui_gtk_x11.c
> gui_gtk_x11.c: In function ‘gui_gtk_get_screen_geom_of_win’:
> gui_gtk_x11.c:5019: warning: implicit declaration of function ‘gtk_widget_get_window’
> gui_gtk_x11.c:5019: warning: initialization makes pointer from integer without a cast
> ```
> Linker error message is:
> ```
> objects/gui_gtk_x11.o: In function `gui_gtk_get_screen_geom_of_win':
> /users/arenieri/my_sw/vim.git/src/gui_gtk_x11.c:5019: undefined reference to `gtk_widget_get_window'
> collect2: ld returned 1 exit status
> link.sh: Linking failed
> make[1]: *** [vim] Error 1
> make[1]: Leaving directory `/users/arenieri/my_sw/vim.git/src'
> make: *** [first] Error 2
> ```
> The issue is related to changes done to fix issue #3268

Looks like gtk_widget_get_window() was introduced in GTK 2.14.
So for older GTK versions we need to fall back to the old way.

-- 
The only backup you need is the one that you didn't have time for.
(Murphy)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
I'm now thinking to reduce many #ifs in the GTK code by defining the function `gtk_widget_get_window()` if not available:
https://bitbucket.org/k_takata/vim-ktakata-mq/src/e881859312ba4efac3699f0c52c0e83e03b16936/simplify-gtk.patch?fileviewer=file-view-default
I haven't tested it, though.

**Comment by chrisbra** [comment]
Perhaps @arenieri could test, whether this patch fixes his issue?

**Comment by k-takata** [comment]
Updated.
https://bitbucket.org/k_takata/vim-ktakata-mq/src/b49dec560826590398996349662ec9bcac861d17/simplify-gtk.patch?fileviewer=file-view-default

**Comment by arenieri** [comment]
The latest patch fixes the issue. I can compile and run gvim.
Some tests of `Make test` fail (see [test.log](https://github.com/vim/vim/files/2370154/test.log) ) but for unrelated reasons, I think.
