### ISSUE TITLE
MS-Windows: Shift-Arrow keys do not work in command-line version

### ISSUE THREAD

**Issue by Pidgeot** [vim/vim#3423]
It is no longer possible to use Shift-Arrow keys to highlight text in the command-line version of Vim on Windows. In normal mode, nothing happens, in insert mode, garbage characters are inserted instead.

Reproduction steps:

1. Start command-line version of vim on Windows
2. `iasd` to insert some text in the buffer (so there's something to select)
3. Press Shift-Left (while still in insert mode)

I tested against binaries from https://github.com/vim/vim-win32-installer and was able to confirm that v8.0.1367 was the last build that worked correctly; v8.0.1376 exhibits the issue. Looking at the patch notes, I'm *guessing* this is a side effect of patch 8.0.1371, but have not looked further into this.

Vim 8.1 also exhibits this bug, even at latest patch 0369, although this inserts *different* garbage characters than 8.0.

**Comment by k-takata** [comment]
> I'm _guessing_ this is a side effect of patch 8.0.1371, but have not looked further into this.

8.0.1371 was written by @mattn. So mentioning him.

**Comment by chrisbra** [comment]
Can you please check, if this is fixed by https://github.com/vim/vim/commit/2bc152ab53c4b01072edf6ec2ff61e504cb03cbe (e.g. patch 8.1.0451)?

**Comment by Pidgeot** [comment]
Yes, that seems to have done the trick - 0450 still had the bug, 0451 does not. Thank you!
