### ISSUE TITLE
[syntax/tex] \textit etc inside brackets are not recognized as texTypeStyle

### ISSUE THREAD

**Issue by e-kwsm** [vim/vim#3431]
version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep 14 2018 11:34:20)
Included patches: 1-388

# Steps to Reproduce
Minimal `vimrc`:
```vim
filetype plugin indent on
syntax enable
let g:tex_flavor = 'latex'
```

`example.tex`:
```latex
  \textit{IT1}   % texTypeStyle
()\textit{IT2}   % texTypeStyle
[]\textit{IT3}   % texTypeStyle
{}\textit{IT4}   % texTypeStyle
 (\textit{IT5})  % texStatement
 [\textit{IT6}]  % texStatement
 {\textit{IT7}}  % texStatement
```

`vim -u vimrc example.tex` and `:echo synIDattr(synID(line('.'), col('.'), 1), 'name')` on each `\textit`.
IT1–IT4 are highlighted as `texTypeStyle`, as expected, while IT5–IT7 as `texStatement`.

**Comment by cecamp** [comment]
Please try http://www.drchip.org/astronaut/vim/index.html#SYNTAX_TEX .  It addresses the issue you directly mentioned; please see if there are any unwanted side effects and let me know (see my email address at the top of the syntax file).  Thanks!
