### ISSUE TITLE
MS-Windows 10: Terminal falsely reports t_Co = 16

### ISSUE THREAD

**Issue by LunarLambda** [vim/vim#3432]
Generally 16 is correct, however it should report 256 when VT sequences are enabled (+vtp). Ran into an issue with a colorscheme not working in terminal because it was checking for t_Co < 256. Manually setting the option doesn't work.

**Comment by ghost** [comment]
I fixed it now.
I will try for several days.
Then I will submit the patch.
Please wait for a moment.
