### ISSUE TITLE
Internal error E315 with ill-formed vim script

### ISSUE THREAD

**Issue by dpelle** [vim/vim#3434]
This ill-formed vim script causes internal errors E315
with vim-8.1.389 and older on Linux x86_64:
```
$ cat > bug.vim <<EOF
for
/1/5/2/s/\n
endfor
EOF
```
Then run vim and press <Return> a few times
```
$ vim --clean -S bug.vim
Error detected while processing /home/pel/sb/vim/src/bug.vim:
line    1:
E690: Missing "in" after :for
Press ENTER or type command to continue
E315: ml_get: invalid lnum: 2
Press ENTER or type command to continue
E315: ml_get: invalid lnum: 3
Press ENTER or type command to continue
E315: ml_get: invalid lnum: 4
Press ENTER or type command to continue
E315: ml_get: invalid lnum: 5
Press ENTER or type command to continue
E315: ml_get: invalid lnum: 6
Press ENTER or type command to continue
E315: ml_get: invalid lnum: 6
Press ENTER or type command to continue
```
If's fine of course to report errors, but not internal errors E315.
Bug was discovered using afl-fuzz.

**Comment by lacygoill** [comment]
Here is a backtrace:

    [New LWP 6363]
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
    Core was generated by `./src/vim -Nu NONE -S /proc/self/fd/11'.
    Program terminated with signal SIGABRT, Aborted.
    #0  0x00007f1d3d5b0777 in kill () from /lib/x86_64-linux-gnu/libc.so.6

    Thread 1 (Thread 0x7f1d40abf9c0 (LWP 6363)):
    #0  0x00007f1d3d5b0777 in kill () from /lib/x86_64-linux-gnu/libc.so.6
    No symbol table info available.
    #1  0x000000000055fb85 in may_core_dump () at os_unix.c:3432
    No locals.
    #2  0x000000000055fb29 in mch_exit (r=1) at os_unix.c:3398
    No locals.
    #3  0x00000000006ceb83 in getout (exitval=1) at main.c:1689
    No locals.
    #4  0x0000000000521bf3 in preserve_exit () at misc1.c:2189
            buf = 0x0
    #5  0x000000000055d42e in deathtrap (sigarg=6) at os_unix.c:1115
            entered = 1
            i = 4
    #6  <signal handler called>
    No symbol table info available.
    #7  0x00007f1d3d5b0438 in raise () from /lib/x86_64-linux-gnu/libc.so.6
    No symbol table info available.
    #8  0x00007f1d3d5b203a in abort () from /lib/x86_64-linux-gnu/libc.so.6
    No symbol table info available.
    #9  0x00000000006d54bf in siemsg (s=0x6ef688 "E315: ml_get: invalid lnum: %ld") at message.c:847
    No locals.
    #10 0x0000000000513806 in ml_get_buf (buf=0x2199b70, lnum=2, will_change=0) at memline.c:2562
            hp = 0x7ffd33e69210
            dp = 0xdb1cc76007c8f400
            recursive = 1
    #11 0x000000000051f42a in plines_win_nofold (wp=0x21974e0, lnum=2) at misc1.c:397
            s = 0x4c5918 <lineFolded+40> "H\205\300\017\225\300\017\266\300\311\303UH\211\345H\203\354\060H\211}\350H\211u\340H\211U\330dH\213\004%("
            col = 140725474202208
            width = -618870944
    #12 0x000000000051f3d4 in plines_win_nofill (wp=0x21974e0, lnum=2, winheight=1) at misc1.c:380
            lines = -618870944
    #13 0x000000000051f31e in plines_win (wp=0x21974e0, lnum=2, winheight=1) at misc1.c:349
    No locals.
    #14 0x000000000052e503 in curs_rows (wp=0x21974e0) at move.c:753
            lnum = 3
            i = 1
            all_invalid = 1
            valid = 0
            fold_count = 0
    #15 0x000000000052ebba in curs_columns (may_scroll=1) at move.c:965
            diff = 4279127
            extra = 0
            off_left = 0
            off_right = 0
            n = 0
            p_lines = 0
            width = 0
            textwidth = 35232624
            new_leftcol = 0
            startcol = 870749056
            endcol = 8
            prev_skipcol = 0
            so = 0
            siso = 0
    #16 0x000000000052e164 in validate_cursor () at move.c:655
    No locals.
    #17 0x00000000006ce49d in main_loop (cmdwin=0, noexmode=0) at main.c:1349
            oa = {op_type = 0, regname = 0, motion_type = 0, motion_force = 0, use_reg_one = 0, inclusive = 0, end_adjusted = 0, start = {lnum = 0, col = 0, coladd = 0}, end = {lnum = 0, col = 0, coladd = 0}, cursor_start = {lnum = 0, col = 0, coladd = 0}, line_count = 0, empty = 0, is_VIsual = 0, block_mode = 0, start_vcol = 0, end_vcol = 0, prev_opcount = 0, prev_count0 = 0}
            prev_oap = 0x0
            previous_got_int = 0
            conceal_old_cursor_line = 0
            conceal_new_cursor_line = 0
            conceal_update_lines = 0
    #18 0x00000000006cdabd in vim_main2 () at main.c:865
    No locals.
    #19 0x00000000006cd1fd in main (argc=5, argv=0x7ffd33e695e8) at main.c:412
            i = 5

Apparently, the error is raised from here:

https://github.com/vim/vim/blob/5ed58c7b700fcb9fd03c418300145b616f4bdcdd/src/memline.c#L2562

**Comment by lacygoill** [comment]
> from here:

That is the top of the `ml_get_buf()` function in `memline.c`.

**Comment by lacygoill** [comment]
Now that the issue is fixed, this todo item can be removed:

> ml_get error. (Dominique Pelle, 2018 Sep 14, #3434)
