### ISSUE TITLE
Fun with Xcode 10

### ISSUE THREAD

**Issue by chdiza** [vim/vim#3445]
Xcode 10 (and the associated Commandline Tools development package) was released today and it is doing weird things on macOS 10.13.6.

The latest Vim builds successfully but there are the following warnings at the end of the process.

```
link.sh: Using unmodified link command
  gcc   -L/usr/local/lib 	-o vim objects/arabic.o objects/beval.o objects/buffer.o objects/blowfish.o objects/crypt.o objects/crypt_zip.o objects/dict.o objects/diff.o objects/digraph.o objects/edit.o objects/eval.o objects/evalfunc.o objects/ex_cmds.o objects/ex_cmds2.o objects/ex_docmd.o objects/ex_eval.o objects/ex_getln.o objects/farsi.o objects/fileio.o objects/fold.o objects/getchar.o objects/hardcopy.o objects/hashtab.o  objects/if_cscope.o objects/if_xcmdsrv.o objects/list.o objects/mark.o objects/memline.o objects/menu.o objects/misc1.o objects/misc2.o objects/move.o objects/mbyte.o objects/normal.o objects/ops.o objects/option.o objects/os_unix.o objects/pathdef.o objects/popupmnu.o objects/pty.o objects/quickfix.o objects/regexp.o objects/screen.o objects/search.o objects/sha256.o objects/spell.o objects/spellfile.o objects/syntax.o objects/tag.o objects/term.o objects/terminal.o objects/ui.o objects/undo.o objects/userfunc.o objects/version.o objects/window.o  objects/encoding.o objects/keyboard.o objects/mouse.o objects/parser.o objects/pen.o objects/termscreen.o objects/state.o objects/unicode.o objects/vterm.o        objects/os_macosx.o objects/os_mac_conv.o   objects/channel.o objects/xdiffi.o objects/xemit.o objects/xprepare.o objects/xutils.o objects/xhistogram.o objects/xpatience.o   objects/charset.o objects/json.o objects/main.o objects/memfile.o objects/message.o        -lm -lncurses  -liconv -framework AppKit
ld: warning: text-based stub file /System/Library/Frameworks//AppKit.framework/AppKit.tbd and library file /System/Library/Frameworks//AppKit.framework/AppKit are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/PrivateFrameworks/UIFoundation.framework/Versions/A/UIFoundation.tbd and library file /System/Library/PrivateFrameworks/UIFoundation.framework/Versions/A/UIFoundation are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//ApplicationServices.framework/Versions/A/ApplicationServices.tbd and library file /System/Library/Frameworks//ApplicationServices.framework/Versions/A/ApplicationServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//Foundation.framework/Versions/C/Foundation.tbd and library file /System/Library/Frameworks//Foundation.framework/Versions/C/Foundation are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CoreGraphics.framework/Versions/A/CoreGraphics.tbd and library file /System/Library/Frameworks//CoreGraphics.framework/Versions/A/CoreGraphics are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CoreText.framework/Versions/A/CoreText.tbd and library file /System/Library/Frameworks//CoreText.framework/Versions/A/CoreText are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//ImageIO.framework/Versions/A/ImageIO.tbd and library file /System/Library/Frameworks//ImageIO.framework/Versions/A/ImageIO are out of sync. Falling back to library file for linking.
```

I have no idea what that means or whether Vim can do anything about it.  I know that Xcode10/CLT have changed the location of all kinds of header files.

**Comment by vim-ml** [comment]
Hi,

On Tue, Sep 18, 2018 at 7:39 AM chdiza <vim-dev-github@256bit.org> wrote:
>
> Xcode 10 (and the associated Commandline Tools development package) was released today and it is doing weird things on macOS 10.13.6.
>
> The latest Vim builds successfully but there are the following warnings at the end of the process.
>
> link.sh: Using unmodified link command
>   gcc   -L/usr/local/lib -o vim objects/arabic.o objects/beval.o objects/buffer.o objects/blowfish.o objects/crypt.o objects/crypt_zip.o objects/dict.o objects/diff.o objects/digraph.o objects/edit.o objects/eval.o objects/evalfunc.o objects/ex_cmds.o objects/ex_cmds2.o objects/ex_docmd.o objects/ex_eval.o objects/ex_getln.o objects/farsi.o objects/fileio.o objects/fold.o objects/getchar.o objects/hardcopy.o objects/hashtab.o  objects/if_cscope.o objects/if_xcmdsrv.o objects/list.o objects/mark.o objects/memline.o objects/menu.o objects/misc1.o objects/misc2.o objects/move.o objects/mbyte.o objects/normal.o objects/ops.o objects/option.o objects/os_unix.o objects/pathdef.o objects/popupmnu.o objects/pty.o objects/quickfix.o objects/regexp.o objects/screen.o objects/search.o objects/sha256.o objects/spell.o objects/spellfile.o objects/syntax.o objects/tag.o objects/term.o objects/terminal.o objects/ui.o objects/undo.o objects/userfunc.o objects/version.o objects/window.o  objects/encoding.o objects/keyboard.o objects/mouse.o objects/parser.o objects/pen.o objects/termscreen.o objects/state.o objects/unicode.o objects/vterm.o        objects/os_macosx.o objects/os_mac_conv.o   objects/channel.o objects/xdiffi.o objects/xemit.o objects/xprepare.o objects/xutils.o objects/xhistogram.o objects/xpatience.o   objects/charset.o objects/json.o objects/main.o objects/memfile.o objects/message.o        -lm -lncurses  -liconv -framework AppKit
> ld: warning: text-based stub file /System/Library/Frameworks//AppKit.framework/AppKit.tbd and library file /System/Library/Frameworks//AppKit.framework/AppKit are out of sync. Falling back to library file for linking.
> ld: warning: text-based stub file /System/Library/PrivateFrameworks/UIFoundation.framework/Versions/A/UIFoundation.tbd and library file /System/Library/PrivateFrameworks/UIFoundation.framework/Versions/A/UIFoundation are out of sync. Falling back to library file for linking.
> ld: warning: text-based stub file /System/Library/Frameworks//ApplicationServices.framework/Versions/A/ApplicationServices.tbd and library file /System/Library/Frameworks//ApplicationServices.framework/Versions/A/ApplicationServices are out of sync. Falling back to library file for linking.
> ld: warning: text-based stub file /System/Library/Frameworks//Foundation.framework/Versions/C/Foundation.tbd and library file /System/Library/Frameworks//Foundation.framework/Versions/C/Foundation are out of sync. Falling back to library file for linking.
> ld: warning: text-based stub file /System/Library/Frameworks//CoreGraphics.framework/Versions/A/CoreGraphics.tbd and library file /System/Library/Frameworks//CoreGraphics.framework/Versions/A/CoreGraphics are out of sync. Falling back to library file for linking.
> ld: warning: text-based stub file /System/Library/Frameworks//CoreText.framework/Versions/A/CoreText.tbd and library file /System/Library/Frameworks//CoreText.framework/Versions/A/CoreText are out of sync. Falling back to library file for linking.
> ld: warning: text-based stub file /System/Library/Frameworks//ImageIO.framework/Versions/A/ImageIO.tbd and library file /System/Library/Frameworks//ImageIO.framework/Versions/A/ImageIO are out of sync. Falling back to library file for linking.
>
> I have no idea what that means or whether Vim can do anything about it. I know that Xcode10/CLT have changed the location of all kinds of header files.
>

I am also seeing the same warning messages when building Vim with the
latest Xcode 10 tools.
Some of the articles on the web suggest removing and reinstalling the
Xcode command line tools.

https://github.com/EOSIO/eos/issues/5418

I haven't tried this workaround yet.

Regards,
Yegappan

**Comment by chdiza** [comment]
That workaround didn't do anything at all over here.

**Comment by uppercaveman** [comment]
![image](https://user-images.githubusercontent.com/4667056/45744069-24674580-bc30-11e8-9d14-6914ca23cab5.png)

Either way, it doesn't work。

**Comment by nuko8** [comment]
Hmm, seems like the original idea of the workaround comes from http://sd.jtimothyking.com/2018/07/26/stub-file-and-library-file-out-of-sync/ , and personally, I think the solution looks good.

So I'm not sure why that didn't work for both of them here.  I'm wondering how that failed to work.  By any chance, System Integrity Protection (SIP) was still enabled when both Option 1 and Option 2 were given a try?

**Comment by chdiza** [comment]
> I think the solution looks good.

It may look good, but it doesn't work :)

I have SIP disabled, and have had it disabled ever since installing the OS.

But hey, it's a new major version of Xcode, and every year Apple decides to break a bunch of things for no reason.  Apparently some of us are encountering one of the breakages.

**Comment by rdbisme** [comment]
I'm also with disabled SIP. Might it be the cause?

**Comment by dcollins-beam** [comment]
The above tricks didn't work for me either. I have a suspicion, that Xcode 10 will not be your friend until MacOS 10.14 comes out. Recall that the "out of sync" elements to which these refer are in the system frameworks, which are not updated by Xcode. Earlier, I had the same manifestation, and it happened because an in-place (non-clean) update of Xcode was screwed up. A clean install fixed it. I'm sure some of the tricks above would have worked as well, but despite manifesting the same way, I think this is a different problem. My guess is that after a little while, there will be an update for Xcode 10 that will fix it, followed by the release of...what's the new one called?...whatever, MacOS 10.14.

**Comment by nuko8** [comment]
Since I've got no technical details about the issue so far, I've just updated macOS and Xcode for myself and their current versions are 10.13.6 and 10.0 (10A255), respectively, and then did
```
$ git clone https://github.com/vim/vim.git
$ cd vim/src
$ ./configure
$ make
```
To my surprise, I didn't get any linker warnings at all...

So, would someone tell me how to reproduce or point out what I'm missing?  Are there any combinations of configure options which result in the linker warnings in question?

**Comment by chdiza** [comment]
It doesn't depend on my `./configure` options.  I can run e.g., `./configure` with no flags at all, then `make`, then I see the warnings.

This is probably a bug in either Xcode 10 or the installer package for the Xcode 10 CLT.  I have never touched the directory containing the allegedly out-of-sync things, so it must have been Xcode or the CLT that touched them.

Some other things that I build have shown this (though I can't recall what), while some other things *don't* show this.

@nuko8 I have the same Xcode 10 build (10A255) as you, and CLT 10.0.0.0.1.1535735448.

I wonder if perhaps it has something to do with what's described in the [Xcode 10 Release Notes](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes), under "Command Line Tools" => "New Features".

**Comment by rdbisme** [comment]
Also for me, stuff that I was compiling using `cmake` now raises the warnings. I tried to open a bug issue on the apple bug tracker...

**Comment by chdiza** [comment]
Those warnings also happen on Mojave, too.  Jeez.  I guess Apple done messed up.

**Comment by rdbisme** [comment]
I suddenly am not getting the warnings anymore... Did they push a silent update?

**Comment by chdiza** [comment]
I still get them.

**Comment by si-m** [comment]
same

**Comment by touchpeak** [comment]
Same here

**Comment by habpygo** [comment]
Same problem when compiling Golang files + compiling takes longer.
Tried option 1 and it didn’t work. During the next start-up of my Mac AppStore.app started moaning that the Xcode CLI had to be updated. Probably reverted back to the old version of CommandLineTools. Problem still persists.

**Comment by jyd519** [comment]
I had the same problem. The solution below works .

https://stackoverflow.com/a/53111824/1397565

**Comment by Jun-T** [comment]
Just reinstalling the Command Line Tools may not be enough. In my case (Mojave), setting the environment variable SDKROOT seems to work:
```
export SDKROOT=macosx10.14    # or macosx10.13 etc.
cd path/to/vim/src && ./configure && make
```

**Comment by chdiza** [comment]
This doesn't appear to have anything  to do with Vim in particular.  So I'll close it.
