### ISSUE TITLE
Delimiter in shell heredocs not recognized if word contains numbers

### ISSUE THREAD

**Issue by janlarres** [vim/vim#3457]
Delimiters in heredocs in shell scripts are defined as `word`s, which means they can contain numbers. So this would be a valid heredoc:

```
cat > foo.txt <<EOF1
foo=bar
EOF1
```

But the shell syntax misses the end delimiter and never ends the heredoc region, which means that syntax highlighting is broken after this.

**Comment by lacygoill** [comment]
Fixed by https://github.com/vim/vim/commit/b730f0c7ba36492d795f081b19bbcb85cdf0f50f.
