### ISSUE TITLE
Gvim incorrectly resolves .lnk files on Windows if 'encoding' is set

### ISSUE THREAD

**Issue by lkintact** [vim/vim#3473]
Create a file named "test.txt" and a link to it, "test.txt.lnk", run Gvim setting "encoding" to any valid value, for example `gvim.exe --cmd "set encoding=utf-8" test.txt.lnk`.

Gvim opens "test.txt", but displays an E211 error like this: `E211: File "ЂЂ\Users\UserName\Downloads\vim81\test.txt" no longer available`, that is `C:` in the path is replaced with `ЂЂ` (this changes depending on the 'encoding' set).

In the `:ls` output `C:` is replaced with `<ff><ff>`: `  1 %a   "<ff><ff>\Users\UserName\Downloads\vim81\test.txt" line 1`.

OS: Windows 7,
Gvim: gvim_8.1.0428_x86.zip

**Comment by k-takata** [comment]
Does't occur with older version of Vim?

**Comment by lkintact** [comment]
>Does't occur with older version of Vim?

It occurs with 8.1.327 and, as I just learned, even with 8.0.2 (downloaded from ftp://ftp.home.vim.org/pub/vim/pc/gvim80-002.zip), with the difference that the latter outputs a stranger path in the E211 error message:  `E211: File "J" no longer available`.

**Comment by mattn** [comment]
This is double free.

```diff
diff --git a/src/buffer.c b/src/buffer.c
index 35dd65fc9..50917445b 100644
--- a/src/buffer.c
+++ b/src/buffer.c
@@ -4845,8 +4845,9 @@ fname_expand(
 	if (rfname != NULL)
 	{
 	    vim_free(*ffname);
-	    *ffname = rfname;
-	    *sfname = rfname;
+	    *ffname = vim_strsave(rfname);
+	    vim_free(*sfname);
+	    *sfname = vim_strsave(rfname);
 	}
     }
 #endif
```
ffname and sfname should have been allocated individualy.

**Comment by brammool** [comment]
Yasuhiro Matsumoto wrote:

> This is double free.
> 
> ```diff
> diff --git a/src/buffer.c b/src/buffer.c
> index 35dd65fc9..50917445b 100644
> --- a/src/buffer.c
> +++ b/src/buffer.c
> @@ -4845,8 +4845,9 @@ fname_expand(
>  	if (rfname != NULL)
>  	{
>  	    vim_free(*ffname);
> -	    *ffname = rfname;
> -	    *sfname = rfname;
> +	    *ffname = vim_strsave(rfname);
> +	    vim_free(*sfname);
> +	    *sfname = vim_strsave(rfname);
>  	}
>      }
>  #endif
> ```
> ffname and sfname should have been allocated individualy.

sfname is not allocated, at least not when called from buflist_new().
When would there be a double free?

-- 
If Microsoft would build a car...
... The airbag system would ask "are you SURE?" before deploying.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mattn** [comment]
please see buf_set_name().

```
    void
buf_set_name(int fnum, char_u *name)
{
    buf_T	*buf;

    buf = buflist_findnr(fnum);
    if (buf != NULL)
    {
	vim_free(buf->b_sfname);
	vim_free(buf->b_ffname);
	buf->b_ffname = vim_strsave(name);
	buf->b_sfname = NULL;
	/* Allocate ffname and expand into full path.  Also resolves .lnk
	 * files on Win32. */
	fname_expand(buf, &buf->b_ffname, &buf->b_sfname);
	buf->b_fname = buf->b_sfname;
    }
}
```

**Comment by mattn** [comment]
you may want to do below?
```
vim_free(buf->b_sfname);
if (buf->b_sfname != buf->b_ffname)
    vim_free(buf->b_ffname);
```

**Comment by brammool** [comment]
> please see buf_set_name().
> 
> ```
>     void
> buf_set_name(int fnum, char_u *name)
> {
>     buf_T	*buf;
> 
>     buf = buflist_findnr(fnum);
>     if (buf != NULL)
>     {
> 	vim_free(buf->b_sfname);
> 	vim_free(buf->b_ffname);
> 	buf->b_ffname = vim_strsave(name);
> 	buf->b_sfname = NULL;
> 	/* Allocate ffname and expand into full path.  Also resolves .lnk
> 	 * files on Win32. */
> 	fname_expand(buf, &buf->b_ffname, &buf->b_sfname);
> 	buf->b_fname = buf->b_sfname;
>     }
> }
> ```

Here buf->b_ffname is allocated and buf->b_sfname is NULL.
Then fname_expand() will assign the pointer of b_ffname to b_sfname and
allocated a new buffer for b_ffname.  Thus they are both allocated.

I don't see the problem.

-- 
hundred-and-one symptoms of being an internet addict:
179. You wonder why your household garbage can doesn't have an
     "empty recycle bin" button.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mattn** [comment]
If set encoding option, vim call fname_expand and buf_set_name for update encoding of arguments.
fname_expand set same allocated pointer to b_sfname and b_ffname both. And buf_set_name free twice.

https://github.com/vim/vim/issues/3473#issuecomment-428051094

**Comment by brammool** [comment]
> If set encoding option, vim call fname_expand and buf_set_name for
> update encoding of arguments.
> fname_expand set same allocated pointer to b_sfname and b_ffname both.
> And buf_set_name free twice.

Hmm, ownership of the arguments is not clearly defined.  Also, in some
calls the function arguments are overwritten, which is ugly.

I think this deserves a bigger change.

-- 
hundred-and-one symptoms of being an internet addict:
185. You order fast food over the Internet

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
So does 3d6014f0336d9a64c (e.g. [patch 8.1.470](https://github.com/vim/vim/releases/tag/v8.1.0470)) fix this issue?

**Comment by chrisbra** [comment]
okay closing
