### ISSUE TITLE
Add larger icons to Windows installer (exe file)

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3478]
It seems the largest icon that the Windows exe have is 48 pixels.

I suggest adding larger icons.
Like up to 256 pixels or whatever is good.
It seems the largest i can view in Windows 7 is 256 pixels.

Also the 48 pixel icon does not look good. It looks like it have been upscaled from a smaller icon as opposed to being downscaled from a larger icon.
![vim48badscale](https://user-images.githubusercontent.com/1836590/45953826-91e9ec00-c00b-11e8-933c-f4a607499753.png)

**Comment by k-takata** [comment]
Duplicate of #978. (No progress in the PR, though.)

**Comment by scootergrisen** [comment]
Moved the text and image to the other issue: https://github.com/vim/vim/pull/978
