### ISSUE TITLE
Vim show some weird things when open a file.

### ISSUE THREAD

**Issue by roachsinai** [vim/vim#3486]
![91a0faece9324b36ebd3c0b678d4b1abfa9ce563](https://user-images.githubusercontent.com/9500049/46119470-a01f4e80-c23d-11e8-9116-0e7b507d5bba.png)

The weird things will disappear will in 1-3 seconds on win10 WSL Ubuntu(wsl performance no so good for we like install packages etc.), quickly disapper on Manjaro+Gnome3.

So what’s wrong with it? Thanks for any help!

The screenshot env is WSL, but I get same problem under Manjaro+Gnome3. For now each time open a file in wsl get this wierd thing. But Manjaro is sometimes.

**Comment by k-takata** [comment]
What terminal and which version do you use? What is the setting of `$TERM`?
Could you show the result of `:echo v:termresponse`?

**Comment by roachsinai** [comment]
Terminal Info:

* Guake

```
➜  ~ guake --version
Guake Terminal: 3.3.2
VTE: 0.52.2
VTE runtime: 0.52.2
Gtk: 3.22.30
```

* `$TERM`(not sure the meaning of `setting of $TERM`)

```
➜  ~ $TERM
zsh: command not found: xterm-256color
```

* result of `:echo v:termresponse`

```
[>1;5202;0c
```

**Comment by roachsinai** [comment]
Found the reason.
Remove setting `autocmd VimEnter * call ToggleFullscreen()` in `.vimrc` this `weird things` disappear.

**Comment by k-takata** [comment]
Closing then.
