### ISSUE TITLE
No BufReadPost fired when using checktime % in autocmd

### ISSUE THREAD

**Issue by chemzqm** [vim/vim#3487]
Minimal .vimrc:
``` vim
set nocompatible

filetype plugin indent on
syntax on

set termguicolors
set laststatus=2
set autoread
set updatetime=300

autocmd FocusGained,BufEnter,CursorHold * checktime %
autocmd BufReadPost * echom 'loaded'
```

After change the file outside and back to vim, the buffer reloaded as expected, but the `BufReadPost` is not fired, when remove `%` or run command `:checktime %` by hand, the event is fired as expected.

Without the `BufReadPost` fired, some plugin would lost track of current buffer.

**Comment by tonymec** [comment]
This is expected, see `:help autocmd-nested`

Best regards,
Tony.

**Comment by chemzqm** [comment]
Ok, it could fire`BufReadPost` by adding `nested`
