### ISSUE TITLE
ghost CursorLine in diff-mode

### ISSUE THREAD

**Issue by justinmk** [vim/vim#3488]
Similar/related to https://github.com/vim/vim/issues/3481 , but not the same, and still present in Vim 8.1.436

Steps to reproduce:

1.
  ```
  vim -N -u NORC +'hi CursorLine ctermbg=red ctermfg=white' +'set cursorline' +'call feedkeys("i
foo\<CR>foo\<CR>foo\<CR>bar", "x")'  +vnew +'call feedkeys("ibee\<CR>foo\<CR>foo\<CR>foo\<CR>baz", "x")' +'windo diffthis'
  ```
2. Hit `j` several times.
3. Hit `k` several times.

CursorLine highlight remains on non-cursor lines in one or both windows.

**Comment by ANtlord** [comment]
Confirm. I have the same issue
