### ISSUE TITLE
Vim embedded Python doesn't honor PYTHONDONTWRITEBYTECODE

### ISSUE THREAD

**Issue by DervishD** [vim/vim#3494]
Hi there!

Vim 8.1.332 x64 under Windows 10, Python 3 with dynamic linking.

Looks like at least with this combination, Vim plugins containing Python code generate `__pycache__ ` directories full of `.pyc` files. Not a life-or-death situation, but I have `PYTHONDONTWRITEBYTECODE` enabled in my system (as a system environment variable, my installed Python works) and I'd love Vim to honor this ;)

Looks like Vim is not providing the correct environment when loading the Python DLL, or maybe under Windows this is entirely impossible, or maybe Python doesn't even honor the environment variable when used through the DLL, but I thought that since Vim has been the first program showing the issue maybe reporting here is the proper way of starting.

Thanks a lot in advance. I'm including the output of the `:version` command just in case. Feel free to ask me for any other information you may need, and thanks!!!!
_[For some reason, the attachment failed, I'm editing to re-attach]_

[version.txt](https://github.com/vim/vim/files/2430451/version.txt)

**Comment by tonymec** [comment]
Hm... I am on Linux, where it seems that shells loaded from Vim don't source the same startup scripts as when they are loaded from login.

Maybe you could just add to your vimrc the line
```vim
let $PYTHONDONTWRITEBYTECODE = "1"
```
or something similar? Maybe (or maybe not) bracketed by `if has('python') || has('python3')`?

Best regards,
Tony.

**Comment by DervishD** [comment]
Hi Tony! Long time no see!!!! I'm very happy to read you again, amiko mia!

> Maybe you could just add to your vimrc the line
> 
> ```viml
> let $PYTHONDONTWRITEBYTECODE = "1"
> ```
> 
> or something similar? Maybe (or maybe not) bracketed by `if has('python') || has('python3')`?

Already tried this, to no avail. Looks like as soon as `jedi-vim` is loaded, the cache is recreated. No biggie, really, but I wondered why it happened. I'll try to investigate the issue more.

Thanks anyway!!!
Really, I'm happy you are still on the Vim trenches, helping :)

**Comment by micbou** [comment]
Looks like Python 3 in Vim does not honor the `PYTHONDONTWRITEBYTECODE` environment variable on Windows. Python 2 does not suffer from the issue. A workaround is to set `sys.dont_write_bytecode` to `True` in vimrc:
```viml
py3 sys.dont_write_bytecode = True
```

**Comment by DervishD** [comment]
I'll try that, @micbou , thanks for the suggestions. But the code should be like

py3 import sys; sys.dont_write_bytecode=True

right?

And it worked! I just tested it and it seems that Python 3 under Vim honors this setting. That's great, thanks a lot for the suggestion!

**Comment by micbou** [comment]
`sys` is already imported by Vim so the `import` statement is not needed (though it doesn't hurt to import it again).

**Comment by DervishD** [comment]
@micbou I didn't know `sys` was already imported by Vim, thanks a lot!!!

Obviously importing it again is not a big deal, but it's slower than not doing it, so I'll remove the `import` from my `.vimrc`. Thanks again 👍 :)
