### ISSUE TITLE
Add comments after "cscope add GTAGS" in .vimrc cause it invalid

### ISSUE THREAD

**Issue by bearzyj** [vim/vim#3498]
### 1 Vim Version
>VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep 27 2018 10:48:58)`

### 2 Issue description
Just using "global" utilities: "gtags" and "gtags-cscope"

In .vimrc, below line is invalid and not operated:
`cscope add GTAGS " Auto connect the database`

Must use:
` cscope add GTAGS`

**Comment by ghid** [comment]
@bearzyj Try putting the comment above the `cscope... ` line

**Comment by h-east** [comment]
Hi,

This is a specification. Please see the following documents.

```vim
:h :quote
```

```
[...]
It is not possible to add a comment to a shell command ":!cmd" or to the
":map" command and a few others, because they see the '"' as part of their
argument.  This is mentioned where the command is explained.
```

--

Best regards,
Hirohito Higashi (h_east)

**Comment by vim-ml** [comment]
On 2018-10-02, h_east wrote:
> Hi,
> 
> This is a specification. Please see the following documents.
> 
> :h :quote
> 
> [...]
> It is not possible to add a comment to a shell command ":!cmd" or to the
> ":map" command and a few others, because they see the '"' as part of their
> argument.  This is mentioned where the command is explained.

I don't see where this is mentioned anywhere in the cscope
documentation.  At least searches for "quote" and "comment" in
if_cscoe.txt return nothing.

Regards,
Gary

**Comment by chrisbra** [comment]
So how about this doc patch:

```patch
diff --git a/runtime/doc/cmdline.txt b/runtime/doc/cmdline.txt
index 3b2dd3206..38a208937 100644
--- a/runtime/doc/cmdline.txt
+++ b/runtime/doc/cmdline.txt
@@ -534,9 +534,46 @@ after a command causes the rest of the line to be ignored.  This can be used
 to add comments.  Example: >
        :set ai         "set 'autoindent' option
 It is not possible to add a comment to a shell command ":!cmd" or to the
-":map" command and a few others, because they see the '"' as part of their
-argument.  This is mentioned where the command is explained.
+":map" command and a few others (mainly commands that expect expressions)
+that see the '"' as part of their argument:

+    :argdo
+    :autocmd
+    :bufdo
+    :cexpr (and alike)
+    :call
+    :cdo (and alike)
+    :command
+    :cscope (and alike)
+    :debug
+    :display
+    :echo (and alike)
+    :elseif
+    :execute
+    :folddoopen
+    :folddoclosed
+    :for
+    :grep (and alike)
+    :help (and alike)
+    :if
+    :let
+    :make
+    :map (and alike including :abbrev commands)
+    :menu (and alike)
+    :mkspell
+    :normal
+    :ownsyntax
+    :popup
+    :promptfind (and alike)
+    :registers
+    :return
+    :sort
+    :syntax
+    :tabdo
+    :tearoff
+    :vimgrep (and alike)
+    :while
+    :windo
                                                        *:bar* *:\bar*
 '|' can be used to separate commands, so you can give multiple commands in one
 line.  If you want to use '|' in an argument, precede it with '\'.
```

**Comment by vim-ml** [comment]
On 2018-10-02, Christian Brabandt wrote:
> So how about this doc patch:
> 
> diff --git a/runtime/doc/cmdline.txt b/runtime/doc/cmdline.txt
> index 3b2dd3206..38a208937 100644
> --- a/runtime/doc/cmdline.txt
> +++ b/runtime/doc/cmdline.txt
> @@ -534,9 +534,46 @@ after a command causes the rest of the line to be ignored.  This can be used
>  to add comments.  Example: >
>         :set ai         "set 'autoindent' option
>  It is not possible to add a comment to a shell command ":!cmd" or to the
> -":map" command and a few others, because they see the '"' as part of their
> -argument.  This is mentioned where the command is explained.
> +":map" command and a few others (mainly commands that expect expressions)
> +that see the '"' as part of their argument:
> 
> +    :argdo
> +    :autocmd
> +    :bufdo
> +    :cexpr (and alike)
> +    :call
> +    :cdo (and alike)
> +    :command
> +    :cscope (and alike)
> +    :debug
> +    :display
> +    :echo (and alike)
> +    :elseif
> +    :execute
> +    :folddoopen
> +    :folddoclosed
> +    :for
> +    :grep (and alike)
> +    :help (and alike)
> +    :if
> +    :let
> +    :make
> +    :map (and alike including :abbrev commands)
> +    :menu (and alike)
> +    :mkspell
> +    :normal
> +    :ownsyntax
> +    :popup
> +    :promptfind (and alike)
> +    :registers
> +    :return
> +    :sort
> +    :syntax
> +    :tabdo
> +    :tearoff
> +    :vimgrep (and alike)
> +    :while
> +    :windo
>                                                         *:bar* *:\bar*
>  '|' can be used to separate commands, so you can give multiple commands in one
>  line.  If you want to use '|' in an argument, precede it with '\'.

That's nice.  It still requires an awareness of the problem, but
it's documented and all in one place.

I think by "(and alike)" you meant "(and the like)".

Regards,
Gary

**Comment by chrisbra** [comment]
> That's nice. It still requires an awareness of the problem, but it's documented and all in one place.

Yeah, I first thought about mentioning at each of all the mentioned commands, but that felt a bit "messy".

So I put it in one place, just like for the `:bar` help tag right below.

> I think by "(and alike)" you meant "(and the like)".

Oh, I did not know that. At the risk of being off topic, when would I then use alike vs. the like?

**Comment by chrisbra** [comment]
Updated patch:

```patch
diff --git a/runtime/doc/cmdline.txt b/runtime/doc/cmdline.txt
index 3b2dd3206..ff0ac3be2 100644
--- a/runtime/doc/cmdline.txt
+++ b/runtime/doc/cmdline.txt
@@ -534,9 +534,46 @@ after a command causes the rest of the line to be ignored.  This can be used
 to add comments.  Example: >
        :set ai         "set 'autoindent' option
 It is not possible to add a comment to a shell command ":!cmd" or to the
-":map" command and a few others, because they see the '"' as part of their
-argument.  This is mentioned where the command is explained.
+":map" command and a few others (mainly commands that expect expressions)
+that see the '"' as part of their argument:

+    :argdo
+    :autocmd
+    :bufdo
+    :cexpr (and the like)
+    :call
+    :cdo (and the like)
+    :command
+    :cscope (and the like)
+    :debug
+    :display
+    :echo (and the like)
+    :elseif
+    :execute
+    :folddoopen
+    :folddoclosed
+    :for
+    :grep (and the like)
+    :help (and the like)
+    :if
+    :let
+    :make
+    :map (and the like including :abbrev commands)
+    :menu (and the like)
+    :mkspell
+    :normal
+    :ownsyntax
+    :popup
+    :promptfind (and the like)
+    :registers
+    :return
+    :sort
+    :syntax
+    :tabdo
+    :tearoff
+    :vimgrep (and the like)
+    :while
+    :windo
                                                        *:bar* *:\bar*
 '|' can be used to separate commands, so you can give multiple commands in one
 line.  If you want to use '|' in an argument, precede it with '\'.
```

**Comment by chrisbra** [comment]
documented as of https://github.com/vim/vim/commit/2c64ca1802b2c99b16d2fdf581b68b5baffb082a

**Comment by chrisbra** [comment]
documented as of https://github.com/vim/vim/commit/2c64ca1802b2c99b16d2fdf581b68b5baffb082a
