### ISSUE TITLE
Empty Sides when fullscreen

### ISSUE THREAD

**Issue by fennecinspace** [vim/vim#3503]
VERSION   ==> VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
TERMINAL ==> gnome-terminal (also tried with Konsole)
DIST           ==> Linux Mint 19 64bit cinnamon 3.8.8
![image](https://user-images.githubusercontent.com/9774613/46319888-baf21a00-c5d3-11e8-9342-3b87d2d59334.png)

**Comment by brammool** [comment]
Most likely that space is just too small to fit another character, thus can't be avoided.

**Comment by chrisbra** [comment]
Note, this has been discussed various times in the past (and there are already issues for that). Please also have a look at `:h gtk-css`
