### ISSUE TITLE
Don't store swapfiles when equal to buffer contents

### ISSUE THREAD

**Issue by mclark-newvistas** [vim/vim#3505]
I often have several `vim` sessions open with 10's (30-90 typically) of buffers open at a time. This makes it easy to navigate around in projects via `:b <file>`, `c-^`, etc. (edit: I have `set hidden` in my `.vimrc`). Occasionally I reboot (power sag, carelessness) without first closing `vim`; I appreciate the swap file feature, which can preserve my edits in the case of a power loss. Unfortunately, I rarely have the patience to check every single swap file on every single buffer switch, and typically end up running `rm ~/.cache/vim/*` (I have `set directory=~/.cache/vim//` in my `.vimrc`) after the first 10 or so buffer switches post power-loss.

I would appreciate it if swap files were only created when the in-memory buffer _differs_ from what is on disk - so instead of opening a buffer creating a swap file, altering a buffer would instead. Successfully saving a modified buffer would then remove the swap file.

I recognize there are various plugins to attempt to solve various related issues. I would prefer to run without plugins as much as possible, as I have no decent system for keeping them in sync between the 4 different computers I primarily use on a daily basis (nor the root accounts of same which I occasionally use), much less the 10s of systems I shell into occasionally to do minor work occasionally. I further feel this or related issues are of general interest, given the prevalence of plugins to ease swap file management.

**Comment by jamessan** [comment]
That would remove the ability to detect when another Vim instance already has the file open.

**Comment by mclark-newvistas** [comment]
Ah, so they double as lock files... Can we split that into two features then, for data classification? Could put lock files in `/run/user/<uid>` or `/tmp` depending on if we care about cross user conflicts, while preserving crash recovery apart. Sounds like #1237 wouldn't work then either, since deleting it would void the lock file feature :/.

**Comment by mclark-newvistas** [comment]
To correct myself: in a world with networked filesystems, `/tmp` and `/run/user/<uid>` are unreliable - the most reliable place to put a lockfile is directly next to the file being locked (and various file locking APIs are essentially not useful). As we _also_ want memory editing recovery, and it's better to store one extra file than two, the swap file has dual semantics. Furthermore - we cannot automatically simply delete an unchanged swap file as a normal operation, as we have no way to know if `vim` might not be running on some other host with access to the same file, and so forward the question to an oracle (the human user).

Sadly, the oracle is busy, distracted, and doesn't really want to deal with the problem - meaning the oracle is sometimes wrong.

Problems then:

* Preserve in-memory edits w/o saving the file (good, ie partially edited source code probably won't run properly in an interpreted language)
* Prevent accidentally forking the file contents by editing in `vim` while still open with potentially unsaved edits.
* Make this work across networked filesystems
* ???

So, to adjust my initial proposal: `vim` checks the file `mtime` and reloads the buffer if newer, and locks the file when entering insert mode, or when changing the text. If there is already a lock (recovery) file it shows an error such as the present error. Once the file is successfully saved it removes the lock (recovery) file. I believe the race conditions should be the same as the present case.

This _would_ allow editing a file in multiple instances of `vim`, but should prevent forking the file contents in that case. If there is another reason preventing editing in multiple instances is desirable, the swap file could have a shared edit lock state or something - but would still make cleaning up the editor files somewhat bothersome in the case of an incomplete close.

This would also rely on `mtime` being generally available/useful from the filesystem; I believe this to generally be the case.

Edit: of particular note, I suspect my situation only becomes particularly burdensome with `set hidden`, and many open files. An acceptable compromise might be to simply remove swap files for hidden buffers without modifications when switching to another buffer.

**Comment by jamessan** [comment]
> Sounds like #1237 wouldn't work then either, since deleting it would void the lock file feature

No, that request is simply about deleting the stale swap file if there are no differences in the recovered buffer vs. the on-disk file (which should be easier now that there's a built-in diff implementation).  That's completely independent of the _new_ swapfile that gets created for this instance of Vim.

**Comment by mclark-newvistas** [comment]
Ah - I understand. #1237 is _after_ the oracle has made a choice, while my focus is on reducing choices required of the oracle.

**Comment by mgedmin** [comment]
> That would remove the ability to detect when another Vim instance already has the file open.

Could vim postpone the creation of the swap file until I make the 1st change, and warn me about it then?

I often open files just to look at them (e.g. by jumping to a tag), and it's annoying to get warnings when that file is already open (but unmodified) in another Vim instance.

**Comment by Houl** [comment]
Maybe Vim script already provides the tools needed.

Set global `'noswapfile'` per default and then `:setlocal swapfile` when the first change is made to a buffer, eg using a self-disabling `TextChanged` autocmd (or similar).

**Comment by jamessan** [comment]
tpope has something similar in his [vimrc](https://github.com/tpope/tpope/blob/e8f5d80cf46df8b962cd947a6575bd0621fd6da6/.vimrc#L330).

**Comment by chrisbra** [comment]
> Could vim postpone the creation of the swap file until I make the 1st change, and warn me about it then?

I always wanted Vim to behave this way and I think I even started on a [patch](https://github.com/chrisbra/vim-mq-patches/blob/master/swapfile_on_when_buffer_changed) (don't know if this actually works as expected, because I forced myself to use `view` or `vim -R` and then no swapfile would be created initially)

I am closing this, as it seems to be possible to do without a change in Vim itself.

**Comment by mclark-newvistas** [comment]
@chrisbra So - no changing the default behavior of `vim`? I recognize there are possibly workarounds (though I'm not enough of a master of `vim` as a target platform to evaluate their feasibility), and that there are likely some clever ways of making a clean and portable `.vimrc` (perhaps something like `ssh` forwarding of config files/folders; maybe even supporting the plugins folder somehow), however, I feel this would be a valuable change to the default settings independent of whether this is feasible to program in vimscript or not. I recognize that open source developer hours are few and precious; perhaps the perceived value of the proposal, while positive, is insufficient (if so, fair enough).
