### ISSUE TITLE
Test failures on macOS 10.11.6 with Vim 8.1.0450

### ISSUE THREAD

**Issue by chdiza** [vim/vim#3506]
```
From test_terminal.vim:
Found errors in Test_terminal_scrape_123():
function RunTheTest[40]..Test_terminal_scrape_123[14]..WaitForAssert[2]..<SNR>6_WaitForCommon[11]..<lambda>89 line 1: Expected 3 but got 0
function RunTheTest[40]..Test_terminal_scrape_123[15]..Check_123 line 6: Expected True but got 0
Caught exception in Test_terminal_scrape_123(): Vim(call):E684: list index out of range: 0 @ function RunTheTest[40]..Test_terminal_scrape_123[15]..Check_123, line 7
TEST FAILURE
make[2]: *** [report] Error 1
make[1]: *** [scripttests] Error 2
make: *** [test] Error 2
```

**Comment by brammool** [comment]
> From test_terminal.vim:
> Found errors in Test_terminal_scrape_123():
> function RunTheTest[40]..Test_terminal_scrape_123[14]..WaitForAssert[2]..<SNR>6_WaitForCommon[11]..<lambda>89 line 1: Expected 3 but got 0
> function RunTheTest[40]..Test_terminal_scrape_123[15]..Check_123 line 6: Expected True but got 0
> Caught exception in Test_terminal_scrape_123(): Vim(call):E684: list index out of range: 0 @ function RunTheTest[40]..Test_terminal_scrape_123[15]..Check_123, line 7
> TEST FAILURE
> make[2]: *** [report] Error 1
> make[1]: *** [scripttests] Error 2
> make: *** [test] Error 2

I don't think anything changed in this area.  Is this just flaky or does
it fail consistently?  Note that the CI on Travis doesn't have this
problem.

-- 
hundred-and-one symptoms of being an internet addict:
138. You develop a liking for cold coffee.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chdiza** [comment]
> I don't think anything changed in this area.  Is this just flaky or does it fail consistently?

I suppose it's flaky.  I just tried again and everything passed.  Note that I'm rarely sitting at the machine that has 10.11.6 on it, so it might have started flaking a long time ago and I wouldn't know.
