### ISSUE TITLE
Bug in makefile syntax highlighting

### ISSUE THREAD

**Issue by Boobies** [vim/vim#3511]
The colon in pattern matching expressions tricks include statements into thinking that the line actually represents a rule. The following example can be used to reproduce the error:

`include $(FILES:%=%)`

**Comment by chrisbra** [comment]
could you suggest a patch? Currently, the named syntax file is unmaintained.

**Comment by brammool** [comment]
> The colon in pattern matching expressions tricks include statements
> into thinking that the line actually represents a rule. The following
> example can be used to reproduce the error:
> 
> ``include $(FILES:%=%)

Don't you mean there is a problem in the indent plugin?
That one is currently without a maintainer.

-- 
hundred-and-one symptoms of being an internet addict:
154. You fondle your mouse.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Boobies** [comment]
The bug is in the make.vim syntax file. I'm not familiar enough with Vim scripting to suggest a patch but, basically, makeTarget should not kick in on a line makeInclude line.

**Comment by Boobies** [comment]
Perhaps moving makeInclude *after* makeTarget helps?

**Comment by lacygoill** [comment]
Fixed by b17893aa940dc7d45421f875f5d90855880aad27.
