### ISSUE TITLE
Bug in named.conf syntax highlighting (and fix)

### ISSUE THREAD

**Issue by danpritts** [vim/vim#3515]
Hi,

the named.conf syntax highlighting has an annoying bug.  

It highlights lines not ending in a semicolon as a syntax error.  This is correct, but it also highlights *comment* lines not ending in semicolons.

It's easily fixed with the following change in the `named.vim` syntax file:

    57c57
    < syn region	namedIntSection	contained start=+{+ end=+}+ 
    contains=namedIntKeyword,namedError
    ---
    > syn region	namedIntSection	contained start=+{+ end=+}+ 
    contains=namedIntKeyword,namedError,namedComment

I have tested this with the syntax file from git, using the following vim binaries from my OS vendors:

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 29 2017 18:37:46)
Included patches: 1-503, 505-680, 682-1283
Compiled by root@apple.com
(osx "high sierra" 10.13.6)

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 21 2016 17:10:41)
Included patches: 1-207, 209-629
Modified by <bugzilla@redhat.com>
(RHEL6)

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Sep  6 2017 07:41:47)
Included patches: 1-160, 399, 402-403, 1099
Modified by <bugzilla@redhat.com>
(RHEL7)

**Comment by k-takata** [comment]
Have you contacted the maintainer?

**Comment by chrisbra** [comment]
please try to contact the [maintainer](https://github.com/vim/vim/blob/master/runtime/syntax/named.vim#L3), however, it looks like it is unmaintained

**Comment by danpritts** [comment]
I dropped him a line.  

I can volunteer to shepherd this if he doesn't, but i have had limited luck editing syntax files in the past and won't have any time to devote to learning how to  improve it in any significant way.

**Comment by NickHibma** [comment]
Thanks for posting the update! And sorry for the delayed answer. I wanted to have a good look at it before replying.

I'd like to take you up on your suggestion to take over maintainership. I am not using bind anywhere (using unbound if needed), so maintaining that file by me doesn't make much sense.

To take over maintainership you have to send a message to Bram I believe, and CC: me in it.

**Comment by lump** [comment]
Could we at least just commit the named.vim patch from @danpritts without a maintainer for now?

**Comment by danpritts** [comment]
I'm willing to do it, but I just poked and couldn't find Bram's email, it is moderately well camouflaged.  @NickHibma  can you initiate the e-mail?  I'm vim@dogcheese.net.

**Comment by NickHibma** [comment]
I've sent him an e-mail.

Nick Hibma
nick@van-laarhoven.org

-- Open Source: We stand on the shoulders of giants.

**Comment by brammool** [comment]
Dan Pritts wrote:

> I'm willing to do it, but I just poked and couldn't find Bram's email,
> it is moderately well camouflaged.

Can't be that difficult...

> @NickHibma  can you initiate the e-mail?  I'm vim@dogcheese.net.  

Just send me the file, with the fix and update the header to add you as
maintainer, mentioning Nick as the previous maintainer.  You can drop
the URL.  Or change it to your own.


-- 
BROTHER MAYNARD: Armaments Chapter Two Verses Nine to Twenty One.
ANOTHER MONK:    And St.  Attila raised his hand grenade up on high saying "O
                 Lord bless this thy hand grenade that with it thou mayest
                 blow thine enemies to tiny bits, in thy mercy. "and the Lord
                 did grin and people did feast upon the lambs and sloths and
                 carp and anchovies and orang-utans and breakfast cereals and
                 fruit bats and...
BROTHER MAYNARD: Skip a bit brother ...
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
Fixed by https://github.com/vim/vim/commit/2e693a88b24dc6b12883fad78ff2cb9cd4469c98.
