### ISSUE TITLE
fnamemodify with ':~' mod adds a trailing slash when it should not

### ISSUE THREAD

**Issue by Asheq** [vim/vim#3524]
To reproduce:

`let $HOME='my/home'`

command | expected | actual |  |
--------|----------|--------|---|
`echo fnamemodify('my', ':~')` | `my` | `my` | ✅
`echo fnamemodify('my/home/dir', ':~')` | `~/dir` | `~/dir` | ✅
`echo fnamemodify('my/home', ':~')` | `~` | `~/` | ❌

In the last case, why does it print a trailing slash (`~/`)?

I only expect the trailing slash if the path passed into _fnamemodify_ itself has a trailing slash e.g. `my/`, `my/home/dir/`, `my/home/`.

**Comment by erickpaquin** [comment]
@Asheq ,

Is this still an issue? This was posted 5 years ago approximately. If you still have the issue, what version of vim are you running and on which OS?

Also, have you checked the help for fnamemodify() and filename-modifiers? Some interesting clues in there.

Thanks.

**Comment by chrisbra** [comment]
can no longer reproduce on Vim 9.0.078 but on an old 8.1.3741. 

So closing, assuming it has been fixed.
