### ISSUE TITLE
The application icons need to improve

### ISSUE THREAD

**Issue by ghost** [vim/vim#3528]
The applications icons quality need to improve, such as application icon and toolbar icons. These icons looks too old and with lower quality. Especially on a modern operation system such as Windows 10. Please consider to make the icons more nicer.

**Comment by k-takata** [comment]
Looks like a duplicate of #3478.

**Comment by chrisbra** [comment]
closing, for #3478

**Comment by chrisbra** [comment]
closing, for #3478
