### ISSUE TITLE
MDItemMarkAsUsedForPath

### ISSUE THREAD

**Issue by tobireif** [vim/vim#353]
I'm frequently getting this warning:

```
  MacVim[581:303] Metadata.framework [Error]: void
  _MDItemMarkAsUsedForPath(CFStringRef): was called with a NULL
  path
```

Vim 7.4.258
Mac OS 10.9.5

gvim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 21 2014 14:54:22)
MacOS X (unix) version
Included patches: 1-258
Compiled by Bjorn Winckler
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_binary
+arabic          +find_in_path    -mouse_sysmouse  +tag_old_static
+autocmd         +float           +mouse_urxvt     -tag_any_white
+balloon_eval    +folding         +mouse_xterm     -tcl
+browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +fullscreen      -mzscheme        +textobjects
+cindent         -gettext         +netbeans_intg   +title
+clientserver    -hangul_input    +odbeditor       +toolbar
+clipboard       +iconv           +path_extra      +transparency
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  -lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
+farsi           +mouse_netterm   +syntax
[...]
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -L/usr/local/lib -L. -L/usr/local/lib -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm -lncurses  -liconv -framework Cocoa   -fstack-protector -L/usr/local/lib  -L/System/Library/Perl/5.16/darwin-thread-multi-2level/CORE -lperl -framework Python   -framework Ruby

**Comment by brammool** [comment]
Please add Issues on code.google.com/p/vim.
These issues at github will be wiped before the import is done again.

**Comment by mattn** [comment]
Please file this issue into https://github.com/macvim-dev/macvim

This is not a repository of macvim.

**Comment by tobireif** [comment]
@mattn Where on the page you referred me to can I file issues? There doesn't seem to be a tab on the right named "Issues".

@brammool BTW, Thanks for Vim! As a suggestion: If you don't want issue reports here, you might want to disable issue reporting (and refer people to https://code.google.com/p/vim/issues/ on the front page of this repo / at the top of the README of this repo here).

I filed the issue here:
https://code.google.com/p/vim/issues/detail?id=351
and refd it here:
https://code.google.com/p/macvim/issues/detail?id=534

**Comment by mattn** [comment]
@tobireif 
> and refd it here:
> https://code.google.com/p/macvim/issues/detail?id=534

Yes, it is. AFAIK, vim-dev doesn't handle issues of macvim. 

evidence: https://github.com/vim/vim/search?utf8=%E2%9C%93&q=MDItemMarkAsUsedForPath

Thanks for that you filed it on https://code.google.com/p/macvim/issues/detail?id=534

**Comment by brammool** [comment]
Tobi -

> @mattn Where on the page you referred me to can I file issues? There
> doesn't seem to be a tab on the right named "Issues".
> 
> @brammool BTW, Thanks for Vim! As a suggestion: If you don't want
> issue reports here, you might want to disable issue reporting (and
> refer people to https://code.google.com/p/vim/issues/ on the front
> page of this repo / at the top of the README of this repo here).

I do not see a way on github to disable creating new issues.

- Bram

-- 
Sometimes I think the surest sign that intelligent life exists elsewhere
in the universe is that none of it has tried to contact us.     (Calvin)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vyp** [comment]
On the right, there is a settings icon. In that page there are checkboxes for things like issue tracking and wikis. Simply uncheck the one for issues.

**Comment by brammool** [comment]
[Not sure who wrote this, lost in the forwarding]

> On the right, there is a settings icon. In that page there are
> checkboxes for things like issue tracking and wikis. Simply uncheck
> the one for issues.

I'm quite sure I looked there, but only now do I see the checkbox.
OK, I switched it off.  Thanks for the hint!

-- 
Why don't cannibals eat clowns?
Because they taste funny.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
