### ISSUE TITLE
Access to free memory with quickfix commands

### ISSUE THREAD

**Issue by dpelle** [vim/vim#3538]
The following command causes vim-8.1.471 and older
to access free memory:

```
$ valgrind --num-callers=50 ./vim --clean -e -s \
   -c 'lexpr ""' \
   -c lopen \
   -c "au FileType * call setloclist(0, [], 'f')" \
   -c 'lexpr ""' 
```
```
==13901== Memcheck, a memory error detector
==13901== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==13901== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==13901== Command: ./vim --clean -e -s -c lexpr\ "" -c lopen -c au\ FileType\ *\ call\ setloclist(0,\ [],\ 'f') -c lexpr\ ""
==13901== 
==13901== Invalid read of size 4
==13901==    at 0x25A9F8: qf_win_pos_update (quickfix.c:4056)
==13901==    by 0x25B3D4: qf_update_buffer (quickfix.c:4176)
==13901==    by 0x25BC44: qf_init_ext (quickfix.c:1739)
==13901==    by 0x263050: ex_cexpr (quickfix.c:6749)
==13901==    by 0x1B014E: do_one_cmd (ex_docmd.c:2525)
==13901==    by 0x1B200C: do_cmdline (ex_docmd.c:1036)
==13901==    by 0x350B44: exe_commands (main.c:2957)
==13901==    by 0x350B44: vim_main2 (main.c:814)
==13901==    by 0x143536: main (main.c:441)
==13901==  Address 0xef529b8 is 8 bytes inside a block of size 1,216 free'd
==13901==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13901==    by 0x2628B1: qf_free_stack (quickfix.c:6481)
==13901==    by 0x2628B1: set_errorlist (quickfix.c:6518)
==13901==    by 0x187A7F: set_qf_ll_list.isra.29 (evalfunc.c:10716)
==13901==    by 0x187C03: f_setloclist (evalfunc.c:10737)
==13901==    by 0x18BA58: call_internal_func (evalfunc.c:1082)
==13901==    by 0x2EF7E1: call_func (userfunc.c:1478)
==13901==    by 0x2F099B: get_func_tv (userfunc.c:455)
==13901==    by 0x2F35C0: ex_call (userfunc.c:3128)
==13901==    by 0x1B014E: do_one_cmd (ex_docmd.c:2525)
==13901==    by 0x1B200C: do_cmdline (ex_docmd.c:1036)
==13901==    by 0x1CB2C5: apply_autocmds_group (fileio.c:9688)
==13901==    by 0x1CC093: apply_autocmds (fileio.c:9201)
==13901==    by 0x2471CE: did_set_string_option.constprop.12 (option.c:7729)
==13901==    by 0x24A8C5: set_string_option (option.c:6033)
==13901==    by 0x24A8C5: set_option_value (option.c:9920)
==13901==    by 0x25A3A2: qf_fill_buffer (quickfix.c:4334)
==13901==    by 0x25B3C2: qf_update_buffer (quickfix.c:4171)
==13901==    by 0x25BC44: qf_init_ext (quickfix.c:1739)
==13901==    by 0x263050: ex_cexpr (quickfix.c:6749)
==13901==    by 0x1B014E: do_one_cmd (ex_docmd.c:2525)
==13901==    by 0x1B200C: do_cmdline (ex_docmd.c:1036)
==13901==    by 0x350B44: exe_commands (main.c:2957)
==13901==    by 0x350B44: vim_main2 (main.c:814)
==13901==    by 0x143536: main (main.c:441)
==13901==  Block was alloc'd at
==13901==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13901==    by 0x2119B0: lalloc (misc2.c:969)
==13901==    by 0x21230F: alloc_clear (misc2.c:891)
==13901==    by 0x25AAB1: ll_new_list (quickfix.c:1988)
==13901==    by 0x25AAB1: ll_get_or_alloc_list (quickfix.c:2010)
==13901==    by 0x263150: ex_cexpr (quickfix.c:6735)
==13901==    by 0x1B014E: do_one_cmd (ex_docmd.c:2525)
==13901==    by 0x1B200C: do_cmdline (ex_docmd.c:1036)
==13901==    by 0x350B44: exe_commands (main.c:2957)
==13901==    by 0x350B44: vim_main2 (main.c:814)
==13901==    by 0x143536: main (main.c:441)
...snip more errors after that...
```
Bug was found using afl-fuzz.

**Comment by dpelle** [comment]
Here is another use of free memory also found by afl-fuzz
which may be related to the previous one despite having
a different stack:
```
$ valgrind --num-callers=50 ./vim -e -s -c "au BufNew * call setloclist(0, [], 'f')" -c "lexpr 'x:1:x'"
```
```
==21056== Memcheck, a memory error detector
==21056== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==21056== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==21056== Command: ./vim -e -s -c au\ BufNew\ *\ call\ setloclist(0,\ [],\ 'f') -c lexpr\ 'x:1:x'
==21056== 
==21056== Invalid read of size 4
==21056==    at 0x25B089: qf_add_entry (quickfix.c:1955)
==21056==    by 0x25BDD4: qf_init_ext (quickfix.c:1688)
==21056==    by 0x263050: ex_cexpr (quickfix.c:6749)
==21056==    by 0x1B014E: do_one_cmd (ex_docmd.c:2525)
==21056==    by 0x1B200C: do_cmdline (ex_docmd.c:1036)
==21056==    by 0x350B44: exe_commands (main.c:2957)
==21056==    by 0x350B44: vim_main2 (main.c:814)
==21056==    by 0x143536: main (main.c:441)
==21056==  Address 0xd6cc820 is 48 bytes inside a block of size 1,216 free'd
==21056==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==21056==    by 0x25D5A9: qf_free_all (quickfix.c:1876)
==21056==    by 0x262879: qf_free_stack (quickfix.c:6467)
==21056==    by 0x262879: set_errorlist (quickfix.c:6518)
==21056==    by 0x187A7F: set_qf_ll_list.isra.29 (evalfunc.c:10716)
==21056==    by 0x187C03: f_setloclist (evalfunc.c:10737)
==21056==    by 0x18BA58: call_internal_func (evalfunc.c:1082)
==21056==    by 0x2EF7E1: call_func (userfunc.c:1478)
==21056==    by 0x2F099B: get_func_tv (userfunc.c:455)
==21056==    by 0x2F35C0: ex_call (userfunc.c:3128)
==21056==    by 0x1B014E: do_one_cmd (ex_docmd.c:2525)
==21056==    by 0x1B200C: do_cmdline (ex_docmd.c:1036)
==21056==    by 0x1CB6B1: apply_autocmds_group (fileio.c:9688)
==21056==    by 0x1CC093: apply_autocmds (fileio.c:9201)
==21056==    by 0x14FCEB: buflist_new (buffer.c:2108)
==21056==    by 0x25AE00: qf_get_fnum (quickfix.c:2201)
==21056==    by 0x25AFC2: qf_add_entry (quickfix.c:1922)
==21056==    by 0x25BDD4: qf_init_ext (quickfix.c:1688)
==21056==    by 0x263050: ex_cexpr (quickfix.c:6749)
==21056==    by 0x1B014E: do_one_cmd (ex_docmd.c:2525)
==21056==    by 0x1B200C: do_cmdline (ex_docmd.c:1036)
==21056==    by 0x350B44: exe_commands (main.c:2957)
==21056==    by 0x350B44: vim_main2 (main.c:814)
==21056==    by 0x143536: main (main.c:441)
==21056==  Block was alloc'd at
==21056==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==21056==    by 0x2119B0: lalloc (misc2.c:969)
==21056==    by 0x21230F: alloc_clear (misc2.c:891)
==21056==    by 0x25AAB1: ll_new_list (quickfix.c:1988)
==21056==    by 0x25AAB1: ll_get_or_alloc_list (quickfix.c:2010)
==21056==    by 0x263150: ex_cexpr (quickfix.c:6735)
==21056==    by 0x1B014E: do_one_cmd (ex_docmd.c:2525)
==21056==    by 0x1B200C: do_cmdline (ex_docmd.c:1036)
==21056==    by 0x350B44: exe_commands (main.c:2957)
==21056==    by 0x350B44: vim_main2 (main.c:814)
==21056==    by 0x143536: main (main.c:441)
```

**Comment by vim-ml** [comment]
Hi,

On Sat, Oct 13, 2018 at 1:11 AM Dominique Pellé
<vim-dev-github@256bit.org> wrote:
>
> Here is another use of free memory also found by afl-fuzz
> which may be related to the previous one despite having
> a different stack:
>

Thanks for reporting these. I am able to reproduce the problem.
I am trying to address this and will send out a patch later.

Regards,
Yegappan

>
> $ valgrind --num-callers=50 ./vim -e -s -c "au BufNew * call setloclist(0, [], 'f')" -c "lexpr 'x:1:x'"
>
> ==21056== Memcheck, a memory error detector
> ==21056== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
> ==21056== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
> ==21056== Command: ./vim -e -s -c au\ BufNew\ *\ call\ setloclist(0,\ [],\ 'f') -c lexpr\ 'x:1:x'
> ==21056==
> ==21056== Invalid read of size 4
> ==21056==    at 0x25B089: qf_add_entry (quickfix.c:1955)
> ==21056==    by 0x25BDD4: qf_init_ext (quickfix.c:1688)
> ==21056==    by 0x263050: ex_cexpr (quickfix.c:6749)
> ==21056==    by 0x1B014E: do_one_cmd (ex_docmd.c:2525)
> ==21056==    by 0x1B200C: do_cmdline (ex_docmd.c:1036)
> ==21056==    by 0x350B44: exe_commands (main.c:2957)
> ==21056==    by 0x350B44: vim_main2 (main.c:814)
> ==21056==    by 0x143536: main (main.c:441)
> ==21056==  Address 0xd6cc820 is 48 bytes inside a block of size 1,216 free'd
> ==21056==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
> ==21056==    by 0x25D5A9: qf_free_all (quickfix.c:1876)
> ==21056==    by 0x262879: qf_free_stack (quickfix.c:6467)
> ==21056==    by 0x262879: set_errorlist (quickfix.c:6518)
> ==21056==    by 0x187A7F: set_qf_ll_list.isra.29 (evalfunc.c:10716)
> ==21056==    by 0x187C03: f_setloclist (evalfunc.c:10737)
> ==21056==    by 0x18BA58: call_internal_func (evalfunc.c:1082)
> ==21056==    by 0x2EF7E1: call_func (userfunc.c:1478)
> ==21056==    by 0x2F099B: get_func_tv (userfunc.c:455)
> ==21056==    by 0x2F35C0: ex_call (userfunc.c:3128)
> ==21056==    by 0x1B014E: do_one_cmd (ex_docmd.c:2525)
> ==21056==    by 0x1B200C: do_cmdline (ex_docmd.c:1036)
> ==21056==    by 0x1CB6B1: apply_autocmds_group (fileio.c:9688)
> ==21056==    by 0x1CC093: apply_autocmds (fileio.c:9201)
> ==21056==    by 0x14FCEB: buflist_new (buffer.c:2108)
> ==21056==    by 0x25AE00: qf_get_fnum (quickfix.c:2201)
> ==21056==    by 0x25AFC2: qf_add_entry (quickfix.c:1922)
> ==21056==    by 0x25BDD4: qf_init_ext (quickfix.c:1688)
> ==21056==    by 0x263050: ex_cexpr (quickfix.c:6749)
> ==21056==    by 0x1B014E: do_one_cmd (ex_docmd.c:2525)
> ==21056==    by 0x1B200C: do_cmdline (ex_docmd.c:1036)
> ==21056==    by 0x350B44: exe_commands (main.c:2957)
> ==21056==    by 0x350B44: vim_main2 (main.c:814)
> ==21056==    by 0x143536: main (main.c:441)
> ==21056==  Block was alloc'd at
> ==21056==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
> ==21056==    by 0x2119B0: lalloc (misc2.c:969)
> ==21056==    by 0x21230F: alloc_clear (misc2.c:891)
> ==21056==    by 0x25AAB1: ll_new_list (quickfix.c:1988)
> ==21056==    by 0x25AAB1: ll_get_or_alloc_list (quickfix.c:2010)
> ==21056==    by 0x263150: ex_cexpr (quickfix.c:6735)
> ==21056==    by 0x1B014E: do_one_cmd (ex_docmd.c:2525)
> ==21056==    by 0x1B200C: do_cmdline (ex_docmd.c:1036)
> ==21056==    by 0x350B44: exe_commands (main.c:2957)
> ==21056==    by 0x350B44: vim_main2 (main.c:814)
> ==21056==    by 0x143536: main (main.c:441)
>

**Comment by vim-ml** [comment]
Hi,

On Sat, Oct 13, 2018 at 7:58 AM Yegappan Lakshmanan <yegappanl@gmail.com> wrote:
>
> On Sat, Oct 13, 2018 at 1:11 AM Dominique Pellé
> <vim-dev-github@256bit.org> wrote:
> >
> > Here is another use of free memory also found by afl-fuzz
> > which may be related to the previous one despite having
> > a different stack:
> >
>
> Thanks for reporting these. I am able to reproduce the problem.
> I am trying to address this and will send out a patch later.
>

The attached patch fixes these crashes. I am still working on cleaning up
the changes. So it is not yet ready to be included.

Freeing up a quickfix/location list/stack or freeing up a buffer or closing a
window or tab page from an autocmd is unexpected and causes a lot
of issues. Checking for these conditions in the code all over the place
creates a lot of clutter and inefficiencies. I am not sure how to cleanly
handle these conditions without adding a lot of checks. We need to add
checks after every function call that can trigger an autocmd.

- Yegappan

>
> >
> > $ valgrind --num-callers=50 ./vim -e -s -c "au BufNew * call setloclist(0, [], 'f')" -c "lexpr 'x:1:x'"
> >
> > ==21056== Memcheck, a memory error detector
> > ==21056== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
> > ==21056== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
> > ==21056== Command: ./vim -e -s -c au\ BufNew\ *\ call\ setloclist(0,\ [],\ 'f') -c lexpr\ 'x:1:x'

**Comment by vim-ml** [comment]
Yegappan wrote:

> On Sat, Oct 13, 2018 at 7:58 AM Yegappan Lakshmanan <yegappanl@gmail.com> w=
> rote:
> >
> > On Sat, Oct 13, 2018 at 1:11 AM Dominique Pell=C3=A9
> > <vim-dev-github@256bit.org> wrote:
> > >
> > > Here is another use of free memory also found by afl-fuzz
> > > which may be related to the previous one despite having
> > > a different stack:
> > >
> >
> > Thanks for reporting these. I am able to reproduce the problem.
> > I am trying to address this and will send out a patch later.
> >
> 
> The attached patch fixes these crashes. I am still working on cleaning up
> the changes. So it is not yet ready to be included.
> 
> Freeing up a quickfix/location list/stack or freeing up a buffer or closing=
>  a
> window or tab page from an autocmd is unexpected and causes a lot
> of issues. Checking for these conditions in the code all over the place
> creates a lot of clutter and inefficiencies. I am not sure how to cleanly
> handle these conditions without adding a lot of checks. We need to add
> checks after every function call that can trigger an autocmd.

Some strategies are:
- Forbid the autocommand to make some changes.  E.g. we have the b_locked flag.
- Don't use local pointers, use an index or unique ID to refer to
  items (e.g. use buffer number instead of buffer pointer.
- Do use a pointer, but have a way to check if it's still valid.  E.g.
  win_valid().

It's still a hassle to check for weird things that can happen.
Autocommands are just too powerful...

-- 
Spam seems to be something useful to novices.  Later you realize that
it's a bunch of indigestable junk that only clogs your system.
Applies to both the food and the e-mail!

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dpelle** [comment]
Yegappan wrote:

> The attached patch fixes these crashes. 

Thanks. I tried your patch and it fixes the 2 cases I reported in this ticket.

However, I have a bunch of cases found by afl-fuzz that crash vim. I assumed that
they were all related to the same 2 cases that I reported earlier here. However, I can
see that some cases found by afl-fuzz still crash after your patch. I will try to simplify
those crashing cases and I'll report soon here here or create a new tickets if they
are unrelated.

**Comment by vim-ml** [comment]
Hi Bram,

On Sun, Oct 14, 2018 at 12:48 PM Bram Moolenaar <Bram@moolenaar.net> wrote:
>
> Yegappan wrote:
>
> > On Sat, Oct 13, 2018 at 7:58 AM Yegappan Lakshmanan <yegappanl@gmail.com> w=
> > rote:
> > >
> > > On Sat, Oct 13, 2018 at 1:11 AM Dominique Pell=C3=A9
> > > <vim-dev-github@256bit.org> wrote:
> > > >
> > > > Here is another use of free memory also found by afl-fuzz
> > > > which may be related to the previous one despite having
> > > > a different stack:
> > > >
> > >
> > > Thanks for reporting these. I am able to reproduce the problem.
> > > I am trying to address this and will send out a patch later.
> > >
> >
> > The attached patch fixes these crashes. I am still working on cleaning up
> > the changes. So it is not yet ready to be included.
> >
> > Freeing up a quickfix/location list/stack or freeing up a buffer or closing=
> >  a
> > window or tab page from an autocmd is unexpected and causes a lot
> > of issues. Checking for these conditions in the code all over the place
> > creates a lot of clutter and inefficiencies. I am not sure how to cleanly
> > handle these conditions without adding a lot of checks. We need to add
> > checks after every function call that can trigger an autocmd.
>
> Some strategies are:
> - Forbid the autocommand to make some changes.  E.g. we have the b_locked flag.
> - Don't use local pointers, use an index or unique ID to refer to
>   items (e.g. use buffer number instead of buffer pointer.
> - Do use a pointer, but have a way to check if it's still valid.  E.g.
>   win_valid().
>

Thanks for the suggestion.

The code already uses the quickfix list identifier to check whether a
list is still present or not after an autocmd. This is simpler for the
quickfix stack as the stack will never get freed.  But the location list
stack itself can get freed by setloclist().

To check whether the location list stack is still present or not, we
need to iterate through all the windows in all the tab pages looking for
a window with the location list stack. Even if I use the window
identifier, we still have to iterate through all the windows. The
location list stack can be referenced either by a file window or a
location list window.

This will cause a performance problem, as we need to do this a few times
in the process of adding an entry to the quickfix/location list.

Sometime ago I was working on adding a reference count to the quickfix
stack/list. But it lead to a lot of code changes and still didn't cleanly solve
the problem.

Regards,
Yegappan

>
> It's still a hassle to check for weird things that can happen.
> Autocommands are just too powerful...
>

**Comment by vim-ml** [comment]
Hi Dominique,

On Mon, Oct 15, 2018 at 4:42 AM Dominique Pellé
<vim-dev-github@256bit.org> wrote:
>
> Yegappan wrote:
>>
>> The attached patch fixes these crashes.
>>
>
> Thanks. I tried your patch and it fixes the 2 cases I reported in this ticket.
>

Thanks for confirming the fixes.

>
> However, I have a bunch of cases found by afl-fuzz that crash vim. I assumed that
> they were all related to the same 2 cases that I reported earlier here. However, I can
> see that some cases found by afl-fuzz still crash after your patch. I will try to simplify
> those crashing cases and I'll report soon here here or create a new tickets if they
> are unrelated.
>

Thanks. There may be more places in the code where we need to validate the
quickfix/location list stack pointers after invoking an autocmd.

Regards,
Yegappan

**Comment by vim-ml** [comment]
Yegappan wrote:

> > > On Sat, Oct 13, 2018 at 7:58 AM Yegappan Lakshmanan <yegappanl@gmail.com> w=
> > > rote:
> > > >
> > > > On Sat, Oct 13, 2018 at 1:11 AM Dominique Pell=C3=A9
> > > > <vim-dev-github@256bit.org> wrote:
> > > > >
> > > > > Here is another use of free memory also found by afl-fuzz
> > > > > which may be related to the previous one despite having
> > > > > a different stack:
> > > > >
> > > >
> > > > Thanks for reporting these. I am able to reproduce the problem.
> > > > I am trying to address this and will send out a patch later.
> > > >
> > >
> > > The attached patch fixes these crashes. I am still working on cleaning up
> > > the changes. So it is not yet ready to be included.
> > >
> > > Freeing up a quickfix/location list/stack or freeing up a buffer or closing=
> > >  a
> > > window or tab page from an autocmd is unexpected and causes a lot
> > > of issues. Checking for these conditions in the code all over the place
> > > creates a lot of clutter and inefficiencies. I am not sure how to cleanly
> > > handle these conditions without adding a lot of checks. We need to add
> > > checks after every function call that can trigger an autocmd.
> >
> > Some strategies are:
> > - Forbid the autocommand to make some changes.  E.g. we have the b_locked flag.
> > - Don't use local pointers, use an index or unique ID to refer to
> >   items (e.g. use buffer number instead of buffer pointer.
> > - Do use a pointer, but have a way to check if it's still valid.  E.g.
> >   win_valid().
> >
> 
> Thanks for the suggestion.
> 
> The code already uses the quickfix list identifier to check whether a
> list is still present or not after an autocmd. This is simpler for the
> quickfix stack as the stack will never get freed.  But the location list
> stack itself can get freed by setloclist().
> 
> To check whether the location list stack is still present or not, we
> need to iterate through all the windows in all the tab pages looking for
> a window with the location list stack. Even if I use the window
> identifier, we still have to iterate through all the windows. The
> location list stack can be referenced either by a file window or a
> location list window.
> 
> This will cause a performance problem, as we need to do this a few times
> in the process of adding an entry to the quickfix/location list.
> 
> Sometime ago I was working on adding a reference count to the quickfix
> stack/list. But it lead to a lot of code changes and still didn't cleanly solve
> the problem.

Can you (easily) mark the code that is manipulating the location list?
Something like 'quickfix_busy' that is incremented before doing some
work and decremented when done?

Then you could check for that flag and when it's > 0 then not delete the
location list stack, but put it in a "to be deleted" list.  Then when
decrementing 'quickfix_busy' to zero those can be deleted.

This is an efficient method, since the extra work is mostly done only
when something unusual is happening.  Something similar is happening for
user functions, esp. self-deleting functions.

-- 
hundred-and-one symptoms of being an internet addict:
213. Your kids start referring to you as "that guy in front of the monitor."

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
Hi Bram,

On Mon, Oct 15, 2018 at 1:03 PM Bram Moolenaar <Bram@moolenaar.net> wrote:
>
> Yegappan wrote:
>
> > > > On Sat, Oct 13, 2018 at 7:58 AM Yegappan Lakshmanan <yegappanl@gmail.com> w=
> > > > rote:
> > > > >
> > > > > On Sat, Oct 13, 2018 at 1:11 AM Dominique Pell=C3=A9
> > > > > <vim-dev-github@256bit.org> wrote:
> > > > > >
> > > > > > Here is another use of free memory also found by afl-fuzz
> > > > > > which may be related to the previous one despite having
> > > > > > a different stack:
> > > > > >
> > > > >
> > > > > Thanks for reporting these. I am able to reproduce the problem.
> > > > > I am trying to address this and will send out a patch later.
> > > > >
> > > >
> > > > The attached patch fixes these crashes. I am still working on cleaning up
> > > > the changes. So it is not yet ready to be included.
> > > >
> > > > Freeing up a quickfix/location list/stack or freeing up a buffer or closing=
> > > >  a
> > > > window or tab page from an autocmd is unexpected and causes a lot
> > > > of issues. Checking for these conditions in the code all over the place
> > > > creates a lot of clutter and inefficiencies. I am not sure how to cleanly
> > > > handle these conditions without adding a lot of checks. We need to add
> > > > checks after every function call that can trigger an autocmd.
> > >
> > > Some strategies are:
> > > - Forbid the autocommand to make some changes.  E.g. we have the b_locked flag.
> > > - Don't use local pointers, use an index or unique ID to refer to
> > >   items (e.g. use buffer number instead of buffer pointer.
> > > - Do use a pointer, but have a way to check if it's still valid.  E.g.
> > >   win_valid().
> > >
> >
> > Thanks for the suggestion.
> >
> > The code already uses the quickfix list identifier to check whether a
> > list is still present or not after an autocmd. This is simpler for the
> > quickfix stack as the stack will never get freed.  But the location list
> > stack itself can get freed by setloclist().
> >
> > To check whether the location list stack is still present or not, we
> > need to iterate through all the windows in all the tab pages looking for
> > a window with the location list stack. Even if I use the window
> > identifier, we still have to iterate through all the windows. The
> > location list stack can be referenced either by a file window or a
> > location list window.
> >
> > This will cause a performance problem, as we need to do this a few times
> > in the process of adding an entry to the quickfix/location list.
> >
> > Sometime ago I was working on adding a reference count to the quickfix
> > stack/list. But it lead to a lot of code changes and still didn't cleanly solve
> > the problem.
>
> Can you (easily) mark the code that is manipulating the location list?
> Something like 'quickfix_busy' that is incremented before doing some
> work and decremented when done?
>

Yes. I can try this approach. I will come up with a patch for this approach
and test it out.

Thanks,
Yegappan

>
> Then you could check for that flag and when it's > 0 then not delete the
> location list stack, but put it in a "to be deleted" list.  Then when
> decrementing 'quickfix_busy' to zero those can be deleted.
>
> This is an efficient method, since the extra work is mostly done only
> when something unusual is happening.  Something similar is happening for
> user functions, esp. self-deleting functions.
>

**Comment by vim-ml** [comment]
Hi,

On Mon, Oct 15, 2018 at 4:42 AM Dominique Pellé
<vim-dev-github@256bit.org> wrote:
>
> Yegappan wrote:
>
> The attached patch fixes these crashes.
>
> Thanks. I tried your patch and it fixes the 2 cases I reported in this ticket.
>
> However, I have a bunch of cases found by afl-fuzz that crash vim. I assumed that
> they were all related to the same 2 cases that I reported earlier here. However, I can
> see that some cases found by afl-fuzz still crash after your patch. I will try to simplify
> those crashing cases and I'll report soon here here or create a new tickets if they
> are unrelated.
>

Based on Bram's comments, I have modified the patch to set
the quickfix_busy flag. I have confirmed that Vim doesn't crash
for your 2 test cases with this patch. Can you try the attached
patch?

Thanks,
Yegappan

**Comment by vim-ml** [comment]
Hi,

On Wed, Oct 17, 2018 at 11:26 PM Yegappan Lakshmanan
<yegappanl@gmail.com> wrote:
>
> On Mon, Oct 15, 2018 at 4:42 AM Dominique Pellé
> <vim-dev-github@256bit.org> wrote:
> >
> > Yegappan wrote:
> >
> > The attached patch fixes these crashes.
> >
> > Thanks. I tried your patch and it fixes the 2 cases I reported in this ticket.
> >
> > However, I have a bunch of cases found by afl-fuzz that crash vim. I assumed that
> > they were all related to the same 2 cases that I reported earlier here. However, I can
> > see that some cases found by afl-fuzz still crash after your patch. I will try to simplify
> > those crashing cases and I'll report soon here here or create a new tickets if they
> > are unrelated.
> >
>
> Based on Bram's comments, I have modified the patch to set
> the quickfix_busy flag. I have confirmed that Vim doesn't crash
> for your 2 test cases with this patch. Can you try the attached
> patch?
>

An updated patch is attached.

- Yegappan

**Comment by vim-ml** [comment]
Yegappan wrote:

> On Wed, Oct 17, 2018 at 11:26 PM Yegappan Lakshmanan
> <yegappanl@gmail.com> wrote:
> >
> > On Mon, Oct 15, 2018 at 4:42 AM Dominique Pell=C3=A9
> > <vim-dev-github@256bit.org> wrote:
> > >
> > > Yegappan wrote:
> > >
> > > The attached patch fixes these crashes.
> > >
> > > Thanks. I tried your patch and it fixes the 2 cases I reported in this =
> ticket.
> > >
> > > However, I have a bunch of cases found by afl-fuzz that crash vim. I as=
> sumed that
> > > they were all related to the same 2 cases that I reported earlier here.=
>  However, I can
> > > see that some cases found by afl-fuzz still crash after your patch. I w=
> ill try to simplify
> > > those crashing cases and I'll report soon here here or create a new tic=
> kets if they
> > > are unrelated.
> > >
> >
> > Based on Bram's comments, I have modified the patch to set
> > the quickfix_busy flag. I have confirmed that Vim doesn't crash
> > for your 2 test cases with this patch. Can you try the attached
> > patch?
> >
> 
> An updated patch is attached.

Thanks!  Let me add a check that the counter goes back to zero,
otherwise this would go unnoticed and leak memory.

-- 
If you're sending someone Styrofoam, what do you pack it in?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
Hi Bram,

On Sat, Oct 20, 2018 at 11:54 AM Bram Moolenaar <Bram@moolenaar.net> wrote:
>
> > > >
> > > > Yegappan wrote:
> > > >
> > > > The attached patch fixes these crashes.
> > > >
> > > > Thanks. I tried your patch and it fixes the 2 cases I reported in this =
> > ticket.
> > > >
> > > > However, I have a bunch of cases found by afl-fuzz that crash vim. I as=
> > sumed that
> > > > they were all related to the same 2 cases that I reported earlier here.=
> >  However, I can
> > > > see that some cases found by afl-fuzz still crash after your patch. I w=
> > ill try to simplify
> > > > those crashing cases and I'll report soon here here or create a new tic=
> > kets if they
> > > > are unrelated.
> > > >
> > >
> > > Based on Bram's comments, I have modified the patch to set
> > > the quickfix_busy flag. I have confirmed that Vim doesn't crash
> > > for your 2 test cases with this patch. Can you try the attached
> > > patch?
> > >
> >
> > An updated patch is attached.
>
> Thanks!  Let me add a check that the counter goes back to zero,
> otherwise this would go unnoticed and leak memory.
>

Thanks for adding the check for the counter going negative.

Regards,
Yegappan

**Comment by vim-ml** [comment]
Hi Dominique,

On Mon, Oct 15, 2018 at 4:42 AM Dominique Pellé
<vim-dev-github@256bit.org> wrote:
>
> Yegappan wrote:
>
> The attached patch fixes these crashes.
>
> Thanks. I tried your patch and it fixes the 2 cases I reported in this ticket.
>
> However, I have a bunch of cases found by afl-fuzz that crash vim. I assumed that
> they were all related to the same 2 cases that I reported earlier here. However, I can
> see that some cases found by afl-fuzz still crash after your patch. I will try to simplify
> those crashing cases and I'll report soon here here or create a new tickets if they
> are unrelated.
>

Are you able to reproduce any of these crashes with the latest Vim?

Thanks,
Yegappan
