### ISSUE TITLE
Ubuntu 18.04.1: Vim doesn't honor g:terminal_ansi_colors?

### ISSUE THREAD

**Issue by LunarLambda** [vim/vim#3541]
Have Vim running on Terminator with termguicolors enabled. Using iceberg colorscheme, which sets g:terminal_ansi_colors, but...
When running colortest-16 and colortest-256 in a :terminal buffer, I get this, instead of the custom ones:
![image](https://user-images.githubusercontent.com/38919842/46918859-afd9b980-cfd7-11e8-8f7c-672c6a1ec13f.png)

Some relevant --version output:

[luna ~]% vim --version | head -n5
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
Included patches: 1-1453
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version with GTK3 GUI.  Features included (+) or not (-):
[luna ~]% vim --version | grep terminal
-autoservername    +float             +mouse_xterm       +terminal
[luna ~]% vim --version | grep termguicolors
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors

I tried opening Vim with
vim -u NONE -c "set termguicolors" -c "colorscheme iceberg", to make sure it's none of my init stuff, but it still doesn't work.

EDIT: echo g:terminal_ansi_colors yields
`['#1e2132', '#e27878', '#b4be82', '#e2a478', '#84a0c6', '#a093c7', '#89b8c2', '#c6c8d1', '#6b7089', '#e98989', '#c0ca8e', '#e9b189', '#91acd1', '#ada0d3', '#95c4ce', '#d2d4de']`
Has this been fixed already? I can't update Vim at the moment..

**Comment by chrisbra** [comment]
Setting the colors for the terminal using `g:terminal_ansi_colors`  is supported since [8.0.1685](https://github.com/vim/vim/releases/tag/v8.0.1685).

**Comment by LunarLambda** [comment]
Okay, just need to update my Vim then. Thank you!
