### ISSUE TITLE
Can't open vim.org web site.

### ISSUE THREAD

**Issue by SharonMina** [vim/vim#3553]
![image](https://user-images.githubusercontent.com/44023192/47240259-672c6100-d41a-11e8-8112-2cfb4cd7c8a5.png)

**Comment by brammool** [comment]
Works for me.  Must have been a temporary outage.

**Comment by tonymec** [comment]
Works for me too. http://www.vim.org/ redirects to https://www.vim.org/ and then the usual Vim site homepage appears.

@SharonMina : Your 404 screen seems to be in Chinese, but I don't know if you are in mainland China, in Hong Kong, in Taiwan, or even using a Chinese localization outside China. Depending on where you are, it might or might not mean that your country is (or was) blocking the Vim site.

Best regards,
Tony.

**Comment by lilydjwg** [comment]
That page says it cannot connect. Maybe temporary DNS or connection error, or a local network configuration error, or it's blocked by the ISP, or affected by the sea cable issues in Asia recently.

**Comment by SharonMina** [comment]
Thanks. We need vim. Please don't give up Maintenancing it.
