### ISSUE TITLE
`:!` isn't documented to take a range. patch.

### ISSUE THREAD

**Issue by jthill** [vim/vim#3554]
```
diff --git a/runtime/doc/various.txt b/runtime/doc/various.txt
index fce8ba1ec..42cbfaf41 100644
--- a/runtime/doc/various.txt
+++ b/runtime/doc/various.txt
@@ -242,8 +242,10 @@ g8			Print the hex values of the bytes used in the
 			mode.
 
 							*:!cmd* *:!* *E34*
-:!{cmd}			Execute {cmd} with the shell.  See also the 'shell'
-			and 'shelltype' option.
+:{range}!{cmd}		Execute {cmd} with the shell. If a {range} is given,
+			the supplied range is piped to stdin and replaced with
+			the command's output. See also the 'shell' and
+			'shelltype' option.
 
 			Any '!' in {cmd} is replaced with the previous
 			external command (see also 'cpoptions').  But not when
@@ -290,7 +292,7 @@ g8			Print the hex values of the bytes used in the
 			Also see |shell-window|.
 
 							*:!!*
-:!!			Repeat last ":!{cmd}".
+:{range}!!		Repeat last ":!{cmd}".
 
 							*:ve* *:version*
 :ve[rsion]		Print the version number of the editor.  If the

```

**Comment by Houl** [comment]
It _is_ documented, `:h :range!`.

**Comment by jthill** [comment]
> It _is_ documented, `:h :range!`.

I see it now.  Are there other commands documented in two completely different help files depending on whether you supply a range?  Maybe just a "see also" link would help.

**Comment by jamessan** [comment]
> Are there other commands documented in two completely different help files depending on whether you supply a range?

The functionality of `:!` and `:{range}!` are quite different, so it makes sense to be documented in different places.  They're documented where their individual functionality makes sense.

The former runs a shell command.  The latter writes the range to the shell command's stdin and replaces the range with the output of the shell command.
