### ISSUE TITLE
.vimrc file isn't read for some setups

### ISSUE THREAD

**Issue by zdohnal** [vim/vim#3555]
Hi,

we have a report in Fedora https://bugzilla.redhat.com/show_bug.cgi?id=1636809 , that ~/.vimrc file isn't read. User sent me his .vimrc file 
[vimrc_bugzilla.txt](https://github.com/vim/vim/files/2501157/vimrc_bugzilla.txt) , but I'm unable to reproduce it even with his .vimrc file. The issue started to show somewhere between 408 and 450 patchlevels, but when I went through these commits, I didn't see anything obvious which could cause the issue.
The issue is solved for him when he comments out these lines from ftplugin/python.vim:

if !exists("g:python_recommended_style") || g:python_recommended_style != 0
    " As suggested by PEP8.
    setlocal expandtab shiftwidth=4 softtabstop=4 tabstop=8
endif

Does anyone encounter such issue? Or am I missing something from these commits? I'm currently trying to bisect the commit which brought the issue.

**Comment by chrisbra** [comment]
I don't recall any changes on loading personal vimrc files. The user should report the output of `:scriptnames` and check the values of the `rtp` setting. Also, it is not sure from your report where the vimrc file is located that is not loaded.

**Comment by lilydjwg** [comment]
The python filetype overrides the settings in vimrc. I set my shiftwidth in the after/ftplugin/python.vim to get it effective.

**Comment by zdohnal** [comment]
@chrisbra From what I know, it is personal vimrc file, located in home directory - ~/.vimrc .

**Comment by chrisbra** [comment]
So it is only about the python filetype plugin setting some options as suggested by PEP8?
That is not a bug and has been discussed several times.
You can always use FileType plugins (for example in the after directory) to overwrite filetype specific settings. 

BTW: for debugging vimrc configuration settings, I recommend http://vimhelp.appspot.com/vim_faq.txt.html#faq-2.5

**Comment by zdohnal** [comment]
> The python filetype overrides the settings in vimrc. I set my shiftwidth in the after/ftplugin/python.vim to get it effective.

So is there a possibility that actually personal vimrc is read, but the user thinks it isn't because of only several values are overridden? So it should be visible only when he opens only python files...

**Comment by chrisbra** [comment]
Yes, check the output of `:scriptnames`.

**Comment by zdohnal** [comment]
> So it is only about the python filetype plugin setting some options as suggested by PEP8?
> That is not a bug and has been discussed several times.
> You can always use FileType plugins (for example in the after directory) to overwrite filetype specific settings.

Then it is is interesting it was triggered between patchlevels 408 and 450 - patchlevel 408 works fine according user and patchlevel 450 (next patchlevel built in Fedora) showed the issue... I'll get the values of :scriptnames and rtp and look into it more...

> 
> BTW: for debugging vimrc configuration settings, I recommend http://vimhelp.appspot.com/vim_faq.txt.html#faq-2.5

Thank you so much! I'll read it.

**Comment by tonymec** [comment]
No ftplugin can prevent a `~/.vimrc` file from being read, because ftplugins are sourced long after the vimrc. What can happen (for the same reason) is that some setting set by the .vimrc is overridden by some code in an ftplugin.

But all hope isn't lost. If you can find what setting that you don't like is set by which ftplugin, you can override it either in an after/ftplugin for the same filetype (e.g. in a new script named `~/.vim/after/ftplugin/python.vim`), or in an autocommand for the VimEnter event (which is triggered at the very end of startup).

**Comment by zdohnal** [comment]
@tonymec  @chrisbra Thank you for the help! It was exactly what you thought - .vimrc is really read, but only one option is overriden by python.vim, which made user think .vimrc isn't read at all. And he experienced the change between these two version because he had old files in ~/.vim directory, which gave him his expected behavior, and then he started to use the new ones.
 I'm sorry for trouble and thanks again!
