### ISSUE TITLE
make[1]: *** [auto/if_perl.c] 错误 29

### ISSUE THREAD

**Issue by Near-Tam** [vim/vim#3557]
$ make
when I run "make", error as follow,

/usr/bin/perl -e 'unless ( $] >= 5.005 ) { for (qw(na defgv errgv)) { print "#define PL_$_ $_\n" }}' > auto/if_perl.c
/usr/bin/perl  -prototypes -typemap \
    /usr/share/perl5/ExtUtils/typemap if_perl.xs >> auto/if_perl.c
Unrecognized switch: -rototypes  (-h will show valid options).
make[1]: *** [auto/if_perl.c] 错误 29
make[1]: 离开目录“/home/tzy/vim/src”
make: *** [first] 错误 2

Anyone has met and solved this problem?

**Comment by mattn** [comment]
What version of perl do you use?

```
$ perl -v
```

**Comment by tonymec** [comment]
There is a missing invocation of `xsubpp` on your command-line, and apparently your perl interprets `-prototypes` as `-p -rototypes` which is not what `xsubpp` would have done.

Here are the two command-lines used on my system to produce `auto/if_perl.c` from `if_perl.xs`:
```sh
/usr/bin/perl -e 'unless ( $] >= 5.005 ) { for (qw(na defgv errgv)) { print "#define PL_$_ $_\n" }}' > auto/if_perl.c
/usr/bin/perl /usr/lib/perl5/5.26.1/ExtUtils/xsubpp -prototypes -typemap \
    /usr/lib/perl5/5.26.1/ExtUtils/typemap if_perl.xs >> auto/if_perl.c
```
Best regards,
Tony.

**Comment by chrisbra** [comment]
closing for no feedback

**Comment by pketienne** [comment]
FYI, I also encountered this issue when attempting to compile Vim 8.x on Centos 7.x. Installing the `perl-ExtUtils-ParseXS` package via `sudo yum install perl-ExtUtils-ParseXS` resolved this particular issue. This package provides (`yum provides xsubpp`) the `xsubpp` utility which was not originally present with the OS but was created at `/usr/bin/xsubpp` per the package installation. (This was using perl 5.16.3).
