### ISSUE TITLE
test

### ISSUE THREAD

**Issue by vim-ml** [vim/vim#357]

**Comment by vim-ml** [comment]
add some text

**Comment by vim-ml** [comment]
some more test

**Comment by vim-ml** [comment]
1 2 3

**Comment by vim-ml** [comment]
test

**Comment by vim-ml** [comment]
one more

**Comment by vim-ml** [comment]
foo

**Comment by vim-ml** [comment]
one more

**Comment by vim-ml** [comment]
another one

**Comment by vim-ml** [comment]
one more

**Comment by vim-ml** [comment]
Closing

**Comment by brammool** [comment]
> another one

I think it's working now...

-- 
bashian roulette:
$ ((RANDOM%6)) || rm -rf ~

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
