### ISSUE TITLE
Build Issue with python 2.7 on Ubuntu 18.4

### ISSUE THREAD

**Issue by PAntoine** [vim/vim#3570]
current commit: master 5f57bdcab patch 8.1.0497: :%diffput changes order of lines

I have a build issue that causes python not to build. in the file src/auto/configure@6226:
`  withval=$with_python_command; vi_cv_path_python="$withval"; { $as_echo "$as_me:${as_lineno-$LINENO}: result: $vi_cv_path_python" >&5`

Which causes the "vi_cv_path_python" to be set to "yes" which causes the python build to fail, as it can no longer find python. I have changed it to:

  `withval=$with_python_command;  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $vi_cv_path_python" >&5`

And I get python to build. I have no idea about autoconf and the "configure" scripts so I don't know if the issue is something else I have done on the system. But setting that variable there does not quite seem correct with the way it is used later.

I can raise a patch if you require.

**Comment by k-takata** [comment]
What are your `./configure` options?

**Comment by PAntoine** [comment]
I tried all the following, with "git clean -fdx" and "git reset --hard" in between.
```
./configure --with-x --enable-pythoninterp --enable-gui --with-features=huge
./configure --with-x --enable-pythoninterp --enable-gui --with-features=huge --prefix=$HOME
./configure --with-x --enable-pythoninterp --enable-gui --with-features=huge --x-includes=/usr/include
./configure --with-x --enable-pythoninterp --enable-gui --with-features=huge --x-includes=/usr/include/
./configure --with-x --enable-pythoninterp --enable-gui --with-features=huge --x-includes=/usr/include/X11
./configure --with-x --enable-pythoninterp --enable-gui --with-features=huge --x-includes=/usr/include/X11/
./configure --with-x --enable-pythoninterp --enable-gui --with-python-command --with-features=huge --prefix=$HOME
./configure --with-x --enable-pythoninterp=yes --enable-gui --with-python --with-features=huge --prefix=$HOME
./configure --with-x --enable-pythoninterp=yes --enable-gui --with-python --with-features=huge --prefix=$HOME --with-python-config-dir=/usr/lib/python2.7/config
./configure --with-x --enable-pythoninterp=yes --enable-gui --with-python --with-features=huge --prefix=$HOME --with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu/
./configure --with-x --enable-pythoninterp=yes --enable-gui --with-python-command --with-features=huge --prefix=$HOME
./configure --with-x --enable-pythoninterp=yes --enable-gui --with-python-command --with-features=huge --prefix=$HOME --with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu/
```

**Comment by PAntoine** [comment]
with this being the one that worked with the fix:
`./configure --with-x --enable-pythoninterp --enable-gui --with-python-command --with-features=huge --prefix=$HOME`

**Comment by k-takata** [comment]
`--with-python-command` requires an option for specifying the name of the python command.
E.g. `--with-python-command=python2`
The option `--with-python` doesn't exist.
See `./configure --help` for the help.

**Comment by PAntoine** [comment]
No problem, I'll close this.
Thanks for responding.

I think my issue was that the configure did not fail when it could not build python properly, I think the early tries did not have python-dev installed. Then I went on a try everything loop. And lastly just hack the scripts. Sorry for wasting your time. Thanks again.
