### ISSUE TITLE
Files in "tee" are not cleaned if "sh" is the shell (re v8.1.0483)

### ISSUE THREAD

**Issue by ghost** [vim/vim#3571]
The "clean" target in tee/Makefile uses the DOS/Windows shell command "del" to delete files tee.exe and tee.o.  However, if make is using the "sh" shell, those commands will fail since "sh" does not grok "del".  This could happen if tee/Makefile is invoked from Make_cyg_ming.mak.  

I propose the attached "patch".
[Tee_diff.txt](https://github.com/vim/vim/files/2522390/Tee_diff.txt)

-mike

**Comment by tonymec** [comment]
```
+ifneq (sh.exe, $(SHELL))
+DEL = rm
+else
+DEL = del
+endif
```
Shouldn't it be `ifeq` rather than `ifneq`?

**Comment by k-takata** [comment]
@tonymec About the "sh.exe" condition, see this comment:
https://github.com/vim/vim/blob/d474686a09ef3f7529e65abe00cf8cd2ea8a95eb/src/Make_cyg_ming.mak#L176-L202

**Comment by k-takata** [comment]
So, @msoyka-of-wharton's patch is correct.

**Comment by tonymec** [comment]
Ah, I see; but it isn't obvious. Maybe a comment or two might be in order: I suggest
```
ifeq (sh.exe, $(SHELL))
# $SHELL set to "sh.exe" with no path means
# that sh.exe was not found in the $PATH,
# so use Dos-like commands
  DEL = del
else
# $SHELL is the full path to a Unix-like shell
# so Unix-like commands should work
  DEL = rm
endif
```

**Comment by k-takata** [comment]
Other makefiles have also the same condition: `GvimExt/Make_ming.mak`, `po/Make_ming.mak` and `xxd/Make_ming.mak`.

**Comment by tonymec** [comment]
I'm not the maintainer of that particular file (who is? Bram?) so I don't have the final say in the matter; but my point of view (about any source file I write in any programming language) is that adding a comment now may avoid a mistake later, when I'll have forgotten the fine points or when someone else (who perhaps never knew those fine points) will have taken responsibility for that source.
