### ISSUE TITLE
Can't start vim from Git Bash MINGW64 terminal

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3574]
I try to run vim.exe from Windows 7 Git Bash MINGW64 terminal.

Seems like vim is included so i can run the included vim by typing "vim" or:

    /c/Program\ Files/Git/usr/bin/vim.exe

But i can't run the newer vim.exe i installed in:

    /c/Program\ Files/Vim/vim81/vim.exe

If i try i get the error message from https://github.com/vim/vim/blob/27e80c885bcb5c5cf6a6462d71d6c81b06ba2451/src/main.c#L2599:

    Vim: Error: This version of Vim does not run in a Cygwin terminal

If i create a vim.bat fil containg "vim.exe" then i can run vim.bat and vim will start which makes no sense to me.
Why can i start vim.exe inside a bat file but not directly by typing it at the terminal?

**Comment by k-takata** [comment]
The batch file must have executed the vim.exe came from Git Bash, if the batch file was actually executed. Or you might fail to execute the batch file.
Check `:version`.
Win32 version of vim.exe cannot run inside mintty. (You can still execute it via winpty, though.)

**Comment by scootergrisen** [comment]
Ok i made a mistake i just wrote "vim.exe" in the .bat file but because i started the .bat file from another folder it started the built in vim instead of the vim.exe in the same folder where the .bat is.
So if i change to the folder with the .bat file and run it from there it also gives the error.

But i have installed the 64-bit version of Vim. That does not run in Git Bash.
But the built in Vim runs. The built in vim does not say 32-bit in \:version but i guess it might be.
Also i dont know what all this mintty etc. is.

If i run mintty.exe i can start MSYS2, Mingw-w64 32 bit,, Mingw-w64 64 bit but running the installed vim.exe gives the error message in all of them.

Do you mean the 64-bit version of Vim does not run inside mintty? You wrote Win32 version.

**Comment by scootergrisen** [comment]
Now i uninstalled vim 64-bit and installed vim 32-bit instead but that does also give the error.
I used gvim_8.1.0500_x64-mui2.exe
Tried in mintty.exe choosing MSYS2, Mingw-w64 32 bit,, Mingw-w64 64. Error in them all.

Works:

    Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -I/usr/include/ncursesw  -march=x86-64 -mtune=generic -O2 -pipe -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1

Does not work:

    Compilation: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_TERMINAL  -DFEAT_JOB_CHANNEL      -DWINVE
    rch:IA32 /Zl /MT -DFEAT_MBYTE_IME -DDYNAMIC_IME -DFEAT_MBYTE -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_
    LUA -DDYNAMIC_LUA_DLL=\"lua53.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_
    Program Files (x86)\Racket\include" -DMZ_PRECISE_GC -DDYNAMIC_MZSCHEME -DDYNAMIC_MZSCH_DLL=\"libracket3m_a36fs8.dll\" -DDYNAMIC_MZ
    -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl528.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_VER=24 -DDYNAMIC_R

**Comment by k-takata** [comment]
> Do you mean the 64-bit version of Vim does not run inside mintty? You wrote Win32 version.

Both Win32 64-bit version and Win32 32-bit version do not work inside mintty.
