### ISSUE TITLE
Internal-diff result is wrong, when hunk-header exists in content

### ISSUE THREAD

**Issue by h-east** [vim/vim#3581]
Hi Bram and developers,

### Prepare files to reproduce:
$ cat test_old.txt
```
1
2
3
4
5
@@ -3,2 +5,7 @@
6
7
8
9
10
```

$ cat test.txt
```
1
2
3
4
5
```

### How to reproduce:
- Start Vim with diff mode and two files.
  $ vim -d test_old.txt test.txt

### Expected behavior:
- Display the correct diff result.
![diff_expect](https://user-images.githubusercontent.com/518808/47798487-cddf4200-dd6b-11e8-80c0-c005c26b8509.png)

### Actual behavior:
- Highlight and folding are strange because hunk-header is in content.
  (Wrong highlight and folding)
![diff_actual](https://user-images.githubusercontent.com/518808/47798510-d9cb0400-dd6b-11e8-8c53-b493c05cd1d6.png)

### Investigation result:
Internal-diff refers to the diff-content at xdiff source code. In some cases the result is wrong, when hunk-header exists in content

I wrote a patch.
$ cat fix_internal-diff.patch
```patch
diff --git a/src/xdiff/xemit.c b/src/xdiff/xemit.c
index d8a6f1ed3..d1c34bab8 100644
--- a/src/xdiff/xemit.c
+++ b/src/xdiff/xemit.c
@@ -285,6 +285,7 @@ int xdl_emit_diff(xdfenv_t *xe, xdchange_t *xscr, xdemitcb_t *ecb,
 				      func_line.buf, func_line.len, ecb) < 0)
 			return -1;
 
+#if 0   // Do not refer to header (lines beginning with "@@ ") in content.
 		/*
 		 * Emit pre-context.
 		 */
@@ -326,6 +327,7 @@ int xdl_emit_diff(xdfenv_t *xe, xdchange_t *xscr, xdemitcb_t *ecb,
 		for (s2 = xche->i2 + xche->chg2; s2 < e2; s2++)
 			if (xdl_emit_record(&xe->xdf2, s2, " ", ecb) < 0)
 				return -1;
+#endif
 	}
 
 	return 0;
```

Is this correct?
If yes, I would write a test.

--
Best regards,
Hirohito Higashi (h_east)

**Comment by chrisbra** [comment]
I am not sure this is correct. If we can assume, that only the first line returned in the call back function can have a valid context header, then this patch works:
```patch
diff --git a/src/diff.c b/src/diff.c
index 23503d826..94e752a76 100644
--- a/src/diff.c
+++ b/src/diff.c
@@ -3213,7 +3213,7 @@ xdiff_out(void *priv, mmbuffer_t *mb, int nbuf)
     {
        // We are only interested in the header lines, skip text lines.
        if (STRNCMP(mb[i].ptr, "@@ ", 3)  != 0)
-           continue;
+           return 0;
        if (ga_grow(&dout->dout_ga, 1) == FAIL)
            return -1;
        p = vim_strnsave((char_u *)mb[i].ptr, mb[i].size);
```
However, I am not sure, this assumption always holds

**Comment by brammool** [comment]
Christian wrote:

> I am not sure this is correct. If we can assume, that only the first
> line returned in the call back function can have a valid context
> header, then this patch works:
> ```patch
> diff --git a/src/diff.c b/src/diff.c
> index 23503d826..94e752a76 100644
> --- a/src/diff.c
> +++ b/src/diff.c
> @@ -3213,7 +3213,7 @@ xdiff_out(void *priv, mmbuffer_t *mb, int nbuf)
>      {
>         // We are only interested in the header lines, skip text lines.
>         if (STRNCMP(mb[i].ptr, "@@ ", 3)  != 0)
> -           continue;
> +           return 0;
>         if (ga_grow(&dout->dout_ga, 1) == FAIL)
>             return -1;
>         p = vim_strnsave((char_u *)mb[i].ptr, mb[i].size);
> ```
> However, I am not sure, this assumption always holds

It does.  It's actually simpler: when called with a header it's always
one line, while when called with text it's always two lines or more.
Thus we can just check "nbuf".

I'll use the example as a test.

-- 
DINGO: Wicked wicked Zoot ... she is a bad person and she must pay the
       penalty.  And here in Castle Anthrax, we have but one punishment
       ... you must tie her down on a bed ... and spank her.  Come!
GIRLS: A spanking!  A spanking!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by h-east** [comment]
Thank you for fixing!

By the way, have you forgotten `testdir/test_diffmode.vim`'s commit or push?

**Comment by brammool** [comment]
Hirohito Higashi wrote:

> Thank you for fixing!
> 
> By the way, have you forgotten `testdir/test_diffmode.vim`'s commit or push?

Right, forgot to include that change.  Thanks for reminding.

-- 
Experience is what you get when you don't get what you want.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
