### ISSUE TITLE
Unable to send escape sequences to the terminal

### ISSUE THREAD

**Issue by resolritter** [vim/vim#3582]
While searching for a solution yesterday, I stumbled upon this [cached StackOverflow answer](https://webcache.googleusercontent.com/search?q=cache:mOXg0-qJmkgJ:https://stackoverflow.com/questions/32429471/how-to-send-escape-sequences-from-within-vim). The guy suggests that I do:

```
execute "silent !echo -ne " . ESCAPE_SEQUENCE
```

---

I therefore tried the following combinations:

```
!echo -ne "\\033]11;#404040\\007" (changes the background color)
```

Says **E194: No alternate file substitute for "#"**.

I tested with a different sequence which doesn't include '#'.

```
!printf '\033[2J' (clears the screen)
```

This doesn't error but it also doesn't do anything. The command just displays the character sequence escaped, like so:

![image](https://user-images.githubusercontent.com/17429390/47820956-cb65f380-dd3d-11e8-937f-432d0ac3939c.png)

Going back to the first sequence, I tried to manually escape all characters myself.

```
!printf '\x5C\x5Ce\x5C\x5C033]11;\x23555555\x5C\x5C007'
```

![image](https://user-images.githubusercontent.com/17429390/47821277-eb49e700-dd3e-11e8-889c-afc7b6041df5.png)

This doesn't output the characters escaped, but also doesn't do anything.

---

I've tried pretty much every combination I know with

- execute
- bash -c
- sh
- using system()

It doesn't matter the medium, the escape sequences don't seem to reach the underlying shell.

If this can't be feasibly solved, is there a way to get the process info from a running Vim instance from within it?

**Comment by lacygoill** [comment]
Fixed by [8.2.0258](https://github.com/vim/vim/releases/tag/v8.2.0258).

---

Instead of using `:!` which – in your first command – required the `#` to be escaped, use the [echoraw()](https://vimhelp.org/eval.txt.html#echoraw()) function:

    :call echoraw("\033]11;#404040\007")

This correctly changes the background color of the terminal (provided that it understands the sequence, I guess).  Tested on xterm(362).
