### ISSUE TITLE
Is the number of foldtext dashes correct?

### ISSUE THREAD

**Issue by zgpio** [vim/vim#3584]
Ref to :h foldtext()
The number of leading dashes depends on the foldlevel.
As follow, I think the foldlevel of printf is 1. And the result of `:echo foldlevel({lnum})` is 1.
![image](https://user-images.githubusercontent.com/19503791/47839416-a630be00-dded-11e8-9ee4-a89d50409342.png)
But, as you can see , the number of dashes is 2.
![image](https://user-images.githubusercontent.com/19503791/47839442-b5177080-dded-11e8-9772-ba607b38e280.png)

**Comment by zgpio** [comment]
ref to https://vi.stackexchange.com/questions/17794/is-the-number-of-foldtext-dashes-incorrect
But why `foldlevel+1`?
I feel this is not convenient by default.

**Comment by chrisbra** [comment]
> But why foldlevel+1?

Why does that matter? What problem does this cause to you?

**Comment by zgpio** [comment]
Ok, actually nothing. Thanks for your answer.

**Comment by Asheq** [comment]
@zgpio I'm actually having the same question as you now.

Was hoping someone could at least explain the reasoning behind the extra dash.

(Minor things like this keep me up at night).
