### ISSUE TITLE
vim with python2 and python3

### ISSUE THREAD

**Issue by Abinayasandhiya** [vim/vim#3585]
Hello,

Can anyone let me know do we can enable both python2 and python3 on single vim.

We are using RedHat machines and we want to use vim with python2[which is install under normal /usr path] and python3[which is installed on separate custom path].

so we have tried below option to enable python2 and python3:

``
%configure --prefix=%{_prefix} --with-features=huge \
           --enable-pythoninterp=dynamic \
           --enable-python3interp=dynamic --enable-perlinterp \
           --enable-rubyinterp --enable-xim --enable-multibyte \
           --with-tlib=ncurses --enable-gtk2-check --enable-gui=gtk2 \
           --enable-cscope  --enable-netbeans --enable-selinux \
           --with-python3-config-dir=/opt/python/x86_64/3.6.0/lib/python3.6/config-3.6m-x86_64-linux-gnu \
           --enable-fontset --with-tlib=tinfo \
``

But when we tried "vim --version" could see only python3 enabled but no python2.

``
[root@abi-qtcreator-test ~]$ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov  1 2018 11:47:04)
Included patches: 1-1097
Compiled by root@abi-qtcreator-test.novalocal
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
+balloon_eval    +folding         +mouse_xterm     +termguicolors
+browse          -footer          +multi_byte      +terminal
++builtin_terms  +fork()          +multi_lang      +terminfo
+byte_offset     +gettext         -mzscheme        +termresponse
+channel         -hangul_input    +netbeans_intg   +textobjects
+cindent         +iconv           +num64           +timers
+clientserver    +insert_expand   +packages        +title
+clipboard       +job             +path_extra      +toolbar
+cmdline_compl   +jumplist        +perl            +user_commands
+cmdline_hist    +keymap          +persistent_undo +vertsplit
+cmdline_info    +lambda          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       -python          +viminfo
+cscope          +lispindent      +python3/dyn     +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  -lua             +rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      +X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      +startuptime     +xpm
+eval            +mouse_dec       +statusline      +xsmp_interact
+ex_extra        +mouse_gpm       -sun_workshop    +xterm_clipboard
+extra_search    -mouse_jsbterm   +syntax          -xterm_save
+farsi           +mouse_netterm   +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/opt/vim/x86_64/8.0.1097-2/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/pixman-1 -I/usr/include/libpng15 -I/usr/include/libdrm     -Wall -O2 -pipe -Wl,--as-needed -march=x86-64 -m64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -Wl,--enable-new-dtags -Wl,-rpath,/usr/lib64/perl5/CORE  -Wl,-z,relro  -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfontconfig -lgobject-2.0 -lglib-2.0 -lfreetype   -lSM -lICE -lXpm -lXt -lX11 -lSM -lICE  -lm -lnsl  -lselinux  -ltinfo -lacl -lattr -lgpm -ldl   -Wl,--enable-new-dtags -Wl,-rpath,/usr/lib64/perl5/CORE  -fstack-protector  -L/usr/lib64/perl5/CORE -lperl -lresolv -lnsl -ldl -lm -lcrypt -lutil -lpthread -lc
[root@abi-qtcreator-test ~]$
``

Can anyone help me or clear my doubts here.

**Comment by chrisbra** [comment]
Looks like your system is missing some python2 development libraries. Not sure which ones you need on Red-Hat. Please also note, even if you compile with `+python/dyn` and `+python3/dyn` you most likely won't be able to use python2 and python3 within one single instance, see [this answer](https://vi.stackexchange.com/q/779/71) on stackexchange.

**Comment by chrisbra** [comment]
Note, also this is a user question and not an actual bug report. 
Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here.

**Comment by Abinayasandhiya** [comment]
Yeah, Thank you and sorry for wrong report.
