### ISSUE TITLE
MacOS Failed to build vim with python3 support when linking dynamic libraries after upgrade system from 10.13 to 10.14 mojave

### ISSUE THREAD

**Issue by dreamingo** [vim/vim#3589]
After I upgrade my MacOS system from 10.13 to 10.14 `mojave`, I want to compiled vim from source with python3 support(The python3 version installed from `pyenv`, not the one installed by system)

```bash
./configure --with-features=huge \                                                                                                                                                          
            --with-tlib=ncurses \
            --enable-multibyte \
            --enable-rubyinterp=yes \
            --enable-python3interp=yes \
            --with-python3-config-dir=/Users/xxx/.pyenv/versions/3.7.0/lib/python3.7/config-3.7m-darwin \
            --enable-perlinterp=yes \
            --enable-luainterp=yes \
            --enable-terminal \
            --enable-cscope \
           --prefix=/usr/local/Cellar/vim8.1_compiled
```

When I run `make` to build vim, I get the following `ld warnings`:

```
ld: warning: object file (/Users/ali/.pyenv/versions/3.7.0/lib/python3.7/config-3.7m-darwin/libpython3.7m.a(tokenizer.o)) was built for newer OSX version (10.14) than being linked (10.13)
ld: warning: object file (/Users/ali/.pyenv/versions/3.7.0/lib/python3.7/config-3.7m-darwin/libpython3.7m.a(getcompiler.o)) was built for newer OSX version (10.14) than being linked (10.13)
ld: warning: object file (/Users/ali/.pyenv/versions/3.7.0/lib/python3.7/config-3.7m-darwin/libpython3.7m.a(ast_unparse.o)) was built for newer OSX version (10.14) than being linked (10.13)
ld: warning: object file (/Users/ali/.pyenv/versions/3.7.0/lib/python3.7/config-3.7m-darwin/libpython3.7m.a(ast_opt.o)) was built for newer OSX version (10.14) than being linked (10.13)
ld: warning: object file (/Users/ali/.pyenv/versions/3.7.0/lib/python3.7/config-3.7m-darwin/libpython3.7m.a(hamt.o)) was built for newer OSX version (10.14) than being linked (10.13)
ld: warning: object file (/Users/ali/.pyenv/versions/3.7.0/lib/python3.7/config-3.7m-darwin/libpython3.7m.a(getopt.o)) was built for newer OSX version (10.14) than being linked (10.13)
ld: warning: object file (/Users/ali/.pyenv/versions/3.7.0/lib/python3.7/config-3.7m-darwin/libpython3.7m.a(asdl.o)) was built for newer OSX version (10.14) than being linked (10.13)
ld: warning: object file (/Users/ali/.pyenv/versions/3.7.0/lib/python3.7/config-3.7m-darwin/libpython3.7m.a(hashtable.o)) was built for newer OSX version (10.14) than being linked (10.13)
ld: warning: object file (/Users/ali/.pyenv/versions/3.7.0/lib/python3.7/config-3.7m-darwin/libpython3.7m.a(bufferedio.o)) was built for newer OSX version (10.14) than being linked (10.13)
ld: warning: object file (/Users/ali/.pyenv/versions/3.7.0/lib/python3.7/config-3.7m-darwin/libpython3.7m.a(bytesio.o)) was built for newer OSX version (10.14) than being linked (10.13)
ld: warning: object file (/Users/ali/.pyenv/versions/3.7.0/lib/python3.7/config-3.7m-darwin/libpython3.7m.a(fileio.o)) was built for newer OSX version (10.14) than being linked (10.13)
ld: warning: object file (/Users/ali/.pyenv/versions/3.7.0/lib/python3.7/config-3.7m-darwin/libpython3.7m.a(iobase.o)) was built for newer OSX version (10.14) than being linked (10.13)
ld: warning: object file (/Users/ali/.pyenv/versions/3.7.0/lib/python3.7/config-3.7m-darwin/libpython3.7m.a(textio.o)) was built for newer OSX version (10.14) than being linked (10.13)
ld: warning: object file (/Users/ali/.pyenv/versions/3.7.0/lib/python3.7/config-3.7m-darwin/libpython3.7m.a(stringio.o)) was built for newer OSX version (10.14) than being linked (10.13)
ld: warning: object file (/Users/ali/.pyenv/versions/3.7.0/lib/python3.7/config-3.7m-darwin/libpython3.7m.a(accu.o)) was built for newer OSX version (10.14) than being linked (10.13)
```

After I build and install `vim`, it will raise exceptions when it load python modules. For an example:

When I run `python3 import _posixsubprocess` in `vim`, it will raise an exception:

![image](https://user-images.githubusercontent.com/1538989/47952788-d1630b00-dfaf-11e8-95a5-0300c527c84e.png)

```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: dlopen(/Users/ali/.pyenv/versions/3.7.0/lib/python3.7/lib-dynload/_posixsubprocess.cpython-37m-darwin.so, 2): Symbol not found: _PyExc_OSError
  Referenced from: /Users/ali/.pyenv/versions/3.7.0/lib/python3.7/lib-dynload/_posixsubprocess.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Users/ali/.pyenv/versions/3.7.0/lib/python3.7/lib-dynload/_posixsubprocess.cpython-37m-darwin.so
```

Does someone have any ideas about how to fix this problem? Thanks!!

**Comment by tonymec** [comment]
Looks like you have a problem with mixed library versions.

Vim needs libraries of the exact same versions as what it was compiled for. Often, after I upgrade my Linux system, the Vim executable I built on the older OS release won't run on the newer one, it might even crash during startup.

The solution I found is to check that not only all needed libraries but also all needed "development packages" are still installed (possibly upgraded to a newer version) and then run "make reconfig" (which will run configure and then compile, so the configure arguments need to be set up in advance as environment variables) followed (in case of success) by "make install".

See http://users.skynet.be/antoine.mechelynck/vim/compunix.htm for details.

Best regards,
Tony.

**Comment by Integralist** [comment]
@dreamingo I also have this issue with a new laptop that is using Mojave, but I don't have the same errors as you (I don't think)...

https://github.com/vim/vim/issues/4233

**Comment by nuko8** [comment]
@dreamingo 

What do you have with the command line
```
$ xcrun --show-sdk-version
```
on you Mac?  If you get the version number other than 10.14 (Probably, that's 10.13), you are supposed to change the currently selected SDK version to the correct version number 10.14 using `xcode-select (1)`.

**Comment by Integralist** [comment]
Just wanted to circle back round for any future travellers...

The key ingredient for getting compilation of vim to work is to tell the compilation script which Python3 version you want to use, but that telling it what to use by itself won't work if it's trying to use 'cached' layers (kinda like Docker caches operations in layers to make future runs quicker).

So now whenever I'm compiling Vim I'm cleaning out the cache (see the first line in the below script)...

```bash
make clean distclean

./configure --with-features=huge \
  --enable-multibyte \
  --enable-rubyinterp=yes \
  --enable-python3interp=yes \
  --with-python3-command=/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/bin/python3.7 \
  --with-python3-config-dir=/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin/ \
  --enable-perlinterp=yes \
  --enable-luainterp=yes \
  --enable-gui=gtk2 \
  --enable-cscope \
  --prefix=/usr/local

make && make install
```

The key flags are...

- ` --enable-python3interp=yes`: tell the compilation you want Python3 support
- `--with-python3-command`: give it a path to a Python3 interpreter/binary (†)
- `--with-python3-config-dir`: a configuration directory used by the version of Python3 you want to use.

> † e.g. if I run that full path in my terminal shell it'll actually run the Python3 REPL so I know it's a valid path to provide.

**Comment by chrisbra** [comment]
closing then.
