### ISSUE TITLE
Update systemd runtime file to not piggypack on DOSINI format

### ISSUE THREAD

**Issue by crabdancing** [vim/vim#3600]
Editing systemd files with mere INI syntax highlighting is a pain because it doesn't show you when you've made an error. This is what I mean:

![nvim-issue0](https://user-images.githubusercontent.com/28266167/48063037-cc5db180-e191-11e8-8cce-04b4d9f09ada.png)

![nvim-issue1](https://user-images.githubusercontent.com/28266167/48063046-d1bafc00-e191-11e8-96b3-f7782dedafa1.png)

The first is stock `vim` highlighter as of the current revision, and the second is from my personal `vim` setup with [my preferred systemd syntax highlighter](https://github.com/alxpettit/fedora-vim-scripts/blob/master/syntax/systemd.vim).

I went further and actually tested my systemd syntax highlighter as a drop-in replacement for the current vim one, and it seems to work fine.

Can we just replace the built-in systemd syntax file with this syntax highlighter?

**Comment by chrisbra** [comment]
If you are willing to maintain that syntax file and send updates whenever needed, then please go ahead and send the syntax file to Bram for inclusion with Vim. Please send complete files, add your name and a license (Vim license preferred) and possibly mention where you intend to maintain the syntax file, e.g. add a line with the upstream repository. Thanks for volunteering!

**Comment by crabdancing** [comment]
Oh, awesome! Yes, I'd be happy to maintain this file. ^.^ I believe the original file set was public domain, so I can just re-license my fork of it under VIM's license no problem!

I just intend to keep it on Github or similar, so that there's a good version and issue tracker with good online code-browsing too... I assume I should format the repo in some way so that your downstream repo can pull from it. I'll talk to Bram about it.

**Comment by crabdancing** [comment]
I should mention I have no idea who Bram is and I was kind of too embarrassed to ask, but now that a long while has passed with no Bram-discovery I should probably just ask how to get in touch with them.

**Comment by tonymec** [comment]
"Bram" means Bram Moolenaar, the "enlightened despot" of the Vim lands, and his email address is bram@moolenaar.net . When he isn't traveling (and sometimes even when he is), he follows these issues and also the Vim mailing lists, which are mirrored as Google groups vim_use, vim_dev and vim_mac.

Best regards,
Tony.

**Comment by crabdancing** [comment]
Thanks!

**Comment by lacygoill** [comment]
The current syntax plugin for systemd files still relies on the dosini plugin:

    " Vim syntax file
    " Language:  systemd.unit(5)

    if !exists('b:current_syntax')
      " Looks a lot like dosini files.
      runtime! syntax/dosini.vim
      let b:current_syntax = 'systemd'
    endif

Any progress on this issue in the foreseeable future?

**Comment by chrisbra** [comment]
let's close it for now. @alxpettit if you still intend to maintain it, just submit it whenever you have something ready to be included. Thanks!
