### ISSUE TITLE
using tmux breaks vim's colors and termguicolors

### ISSUE THREAD

**Issue by vedantroy** [vim/vim#3608]
I am using Ubuntu 18 LTS, with gnome-terminal. 

Normally - "set termguicolors" does its job by generally enhancing the look of vim. However, if I use tmux, then vim looks off, and "set termguicolors" completely breaks all highlighting.

Note - I'm not using a colorscheme, this just my terminal's color scheme. 
Before termguicolors:
![before_termguicolors](https://user-images.githubusercontent.com/8407819/48450718-551db400-e775-11e8-8e45-7a649bd0cf88.png)
After termguicolors:
![after_termguicolors](https://user-images.githubusercontent.com/8407819/48450728-5b139500-e775-11e8-9eb2-e2b3113f2278.png)

However, tmux breaks set termguicolors

Before termguicolors (tmux):
![before_termguicolors_tmux](https://user-images.githubusercontent.com/8407819/48450762-7ed6db00-e775-11e8-889f-1b3afcbc3b09.png)

After termguicolors (tmux):
![after_termguicolors_tmux](https://user-images.githubusercontent.com/8407819/48451181-3b7d6c00-e777-11e8-8451-d7da142d6e36.png)

**Comment by vedantroy** [comment]
Solution:

Add the following lines before "set termguicolors" into my .vimrc. The first 2 commands are taken from this issue: https://github.com/vim/vim/issues/993

```
" This is only necessary if you use "set termguicolors".
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

" fixes glitch? in colors when using vim with tmux
set background=dark
set t_Co=256
```

**Comment by AkashKrDutta** [comment]
With the latest tmux version next-3.3, I did not need to make any changes in vimrc (I kept termguicolors only enabled), but added the following in tmux, and it worked for me:
```
# tmux colors
set -g default-terminal "xterm-256color"
set -ag terminal-overrides ",xterm-256color:Tc"
```

**Comment by brammool** [comment]
> With the latest tmux version next-3.3, I did not need to make any changes in vimrc (I kept termguicolors only enabled), but added the following in tmux, and it worked for me:
> ```
> # tmux colors
> set -g default-terminal "xterm-256color"
> set -ag terminal-overrides ",xterm-256color:Tc"
> ```

Assuming this will work for most users, let me add this in the help,
where cterm colors are explained:

							*tmux*
	When using tmux you may want to use this in the tmux config: >
	    # tmux colors
	    set -g default-terminal "xterm-256color"
	    set -ag terminal-overrides ",xterm-256color:Tc"

Let me know if something needs to be changed.

-- 
Be nice to your kids...  they'll be the ones choosing your nursing home.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by norogoth** [comment]
@vedantroy life-changing oh my gosh. My vim looks so much nicer.
