### ISSUE TITLE
GVim does not fill up parent region on creation in Windows

### ISSUE THREAD

**Issue by agorgl** [vim/vim#3615]
Using the  --windowid feature of gvim in Windows, gvim does not resize to fit into its given parent region when created as demostrated here:

![image](https://user-images.githubusercontent.com/4622346/48660209-d7a0bf00-ea66-11e8-9965-188343c57922.png)

Expected behavior would be this:

![image](https://user-images.githubusercontent.com/4622346/48660229-29494980-ea67-11e8-8a23-ad08e9d20536.png)

Knowing this worked in the past (having fixed another issue that came with this feature in patch 7.4.874) i traced this down until i found that the patch 8.0.1278 broke the behavior:

https://github.com/vim/vim/commit/8ac441576fd219fb7227349e228d5b68520b204a#diff-9eaea41323c4b4d45660fcb34a2d5351

Specifically, gui_mch_newfont() here https://github.com/vim/vim/blob/6b731886ca94d66b9bdedfb7e603af44a6400399/src/gui.c#L1595 is never executed because TRUE is passed in 'mustset' parameter here: https://github.com/vim/vim/blob/6b731886ca94d66b9bdedfb7e603af44a6400399/src/gui.c#L692
since the submission of the above patch.

The obvious fix is to revert that line into passing FALSE in 'mustset' parameter. As far as i can tell this line is only executed on initialization. Also as far as i can see, this shouldn't cause any regression issues, because the only dependent code on this value is a small portion of GTK gui code that is executed on a different invocation of gui_set_shellsize() here: https://github.com/vim/vim/blob/6b731886ca94d66b9bdedfb7e603af44a6400399/src/gui.c#L731

Should i create a PR here or submit a patch in the mailing list?

**Comment by k-takata** [comment]
> Should i create a PR here or submit a patch in the mailing list?

Either is good.

**Comment by k-takata** [comment]
Fixed by #3616 (8.1.0626).
