### ISSUE TITLE
Vim-terminal crashes when displaying certain multi-byte character

### ISSUE THREAD

**Issue by shwadi** [vim/vim#3619]
Hi,

I was using grep from inside a vim-terminal recently and noticed vim to crash on certain patterns if greps color-highliting was active. I traced the issue back to this minimal example:
```
:term bash -c "echo -n WBtbbRtbSxtbMzZtG1tLWVlZG1ttG1tLG1swMTszMW0bWy3gqIPgqLzgqL4u4KmC4KmH4KmI4KmLLi7gqY3gqZEu4Kmx4Km14KqBLuCqg+CqvOCqvi7gq4Xgq4cu4LOI4LOKLuCzhOCzhi7gs43gs5Xgs5bgs6Lgs6MK | base64 -d"
```

After some further digging, I encountered the definition of MB_MAXBYTES in vim.h:
```
/* Maximum number of bytes in a multi-byte character.  It can be one 32-bit
 * character of up to 6 bytes, or one 16-bit character of up to three bytes
 * plus six following composing characters of three bytes each. */
# define MB_MAXBYTES    21
```

Now if I am doing the math correct (and if the comment is correct as well) MB_MAXBYTES should resolve to:
`max(6,3) + 6*3 = 24`

At least setting MB_MAXBYTES to 24 solved the issue in my case.

Anyway. I may be missing something and if you can't reproduce the issue, please tell me which additional information you need.

Cheers
Shwadi

**Comment by dpelle** [comment]
Which version of Vim are you using?
Does it happen when starting vim with:  vim --clean ?

I'm not able to reproduce the issue with vim-8.1.535 (x86_64, Linux)
despite using a asan build.

**Comment by shwadi** [comment]
initially, I observed the crashes on vim versions shipped by arch:
extra/vim 8.1.0470-1
extra/gvim 8.1.0470-1
extra/gvim 8.1.0527-1

thereafter I compiled some versions from source, which crash as well:
v8.1.0502
v8.1.0535 (most recent)

I've just compiled the most recent version on an ubuntu-machine (x86_64) and it crashed too.

Starting vim with --clean does not prevent it from crashing.

After entering the base64 command, the colored output is shortly presented and in the very next moment there is this:
Vim: Caught deadly signal ABRT

I just realized that I accidentally added a linebreak into the command; sorry for that. So you need to hit
```
:term bash -c "echo -n WBtbbRtbSxtbMzZtG1tLWVlZG1ttG1tLG1swMTszMW0bWy3gqIPgqLzgqL4u4KmC4KmH4KmI4KmLLi7gqY3gqZEu4Kmx4Km14KqBLuCqg+CqvOCqvi7gq4Xgq4cu4LOI4LOKLuCzhOCzhi7gs43gs5Xgs5bgs6Lgs6MK | base64 -d"
```
or just open the terminal and do the base64-decoding in there.

If you already did this; any further ideas of why you can't reproduce this?

**Comment by mattn** [comment]
```diff
diff --git a/src/terminal.c b/src/terminal.c
index 53b6ca8a2..2b25b07c4 100644
--- a/src/terminal.c
+++ b/src/terminal.c
@@ -1561,7 +1561,7 @@ update_snapshot(term_T *term)

                        cell2cellattr(&cell, &p[pos.col]);

-                       if (ga_grow(&ga, MB_MAXBYTES) == OK)
+                       if (ga_grow(&ga, MB_MAXBYTES*VTERM_MAX_CHARS_PER_CELL) == OK)
                        {
                            int     i;
                            int     c;
```

Could you please try this?

**Comment by shwadi** [comment]
yes,
this looks like the correct solution. I most obviously misinterpreted the comment.
Thanks!

**Comment by shwadi** [comment]
In fact, I'll leave this issue opened until the patch gets applied or you advice me to close this.
