### ISSUE TITLE
Make incsearch CTRL-L work for final character in file

### ISSUE THREAD

**Issue by Smylers** [vim/vim#3620]
When searching with `incsearch` set, `CTRL-L` adds the next character to the search, except for the final character in the file, when there hasn't ever been anything after it.

Invoke a clean Vim with `incsearch`:

````
% vim -u NONE -c "set incsearch"
````

Then press `a` and type:

````
abcd
efgh
ijkl
````

Press `Esc` immediately after the `l` (don't press `Enter` at the end, nor type and then erase any other character).

Then start a seach with `/i` and press `CTRL-L`; Vim will add the `j` into the search, turning it into `/ij`. Press `CTRL-L` again; Vim adds the `k`, making `/ijk`.

But press `CTRL-L` a third time, and Vim doesn't do anything: the `l` doesn't get added into the search.

Now add and remove a blank line at the bottom, with `o`, `Esc`, `dd`, and repeat the search. This time pressing `CTRL-L` three times does yield the expected `/ijkl`.

Discovered with version 8.1 including patches 1-490, on Ubuntu Linux.

**Comment by h-east** [comment]
Hi,

Could you please confirm the following patch?

```patch
diff --git a/src/ex_getln.c b/src/ex_getln.c
index 31e646dd3..b5c36f734 100644
--- a/src/ex_getln.c
+++ b/src/ex_getln.c
@@ -747,26 +747,22 @@ may_add_char_to_search(int firstc, int *c, incsearch_state_T *is_state)
     if (is_state->did_incsearch)
     {
 	curwin->w_cursor = is_state->match_end;
-	if (!EQUAL_POS(curwin->w_cursor, is_state->search_start))
+	*c = gchar_cursor();
+	if (*c != NUL)
 	{
-	    *c = gchar_cursor();
-
 	    // If 'ignorecase' and 'smartcase' are set and the
 	    // command line has no uppercase characters, convert
 	    // the character to lowercase.
 	    if (p_ic && p_scs && !pat_has_uppercase(ccline.cmdbuff + skiplen))
 		*c = MB_TOLOWER(*c);
-	    if (*c != NUL)
+	    if (*c == firstc || vim_strchr((char_u *)(
+				p_magic ? "\\~^$.*[" : "\\^$"), *c) != NULL)
 	    {
-		if (*c == firstc || vim_strchr((char_u *)(
-				   p_magic ? "\\~^$.*[" : "\\^$"), *c) != NULL)
-		{
-		    // put a backslash before special characters
-		    stuffcharReadbuff(*c);
-		    *c = '\\';
-		}
-		return FAIL;
+		// put a backslash before special characters
+		stuffcharReadbuff(*c);
+		*c = '\\';
 	    }
+	    return FAIL;
 	}
     }
     return OK;
```

--

Best regards,
Hirohito Higashi (h_east)

**Comment by Smylers** [comment]
> Could you please confirm the following patch?

Thanks. I shall try to take a look, but I have never compiled Vim before so will have to look up how to do that, and it may be a while till I get back to you.

**Comment by Smylers** [comment]
Thank you for fixing, and sorry for not confirming this fix sooner.
