### ISSUE TITLE
Add verymagic option

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vim/vim#363]
```

Makes a more consistent regex experience (both more consistent for special 
chars within vim, and more consistent with other regex implementations).

Patch is fairly messy, not thoroughly tested, but seems to essentially work.

Also see demand for this option and attempted hackery:
- 
http://stackoverflow.com/questions/3760444/in-vim-is-there-a-way-to-set-very-mag
ic-permanently-and-globally
- 
http://vim.wikia.com/wiki/Simplifying_regular_expressions_using_magic_and_no-mag
ic
- etc: https://www.google.com/search?q=%22nnoremap+/+/\v%22
```

Original issue reported on code.google.com by `dersai...@gmail.com` on 10 May 2015 at 6:20

Attachments:
- [verymagic.diff](https://storage.googleapis.com/google-code-attachments/vim/issue-363/comment-0/verymagic.diff)

**Comment by lacygoill** [comment]
This option could [cause problems for plugin writers](https://github.com/vim/vim/issues/8026#issuecomment-808921537).

**Comment by brammool** [comment]
Let's close this one.  If someone has a good idea how to do this without hurting plugins please open a new issue or pull request.
