### ISSUE TITLE
`:!cmd` different to cmd.exe

### ISSUE THREAD

**Issue by zgpio** [vim/vim#3632]
* platform: Windows 10
* vim version: Vim 8.1
I change the code page of `cmd.exe` from cp936 to utf-8 by modify the registry of Windows, but it doesn’t work with `:!cmd`.

1. execute cmd.exe,  run `chcp` command as follow:
![image](https://user-images.githubusercontent.com/19503791/48897312-a9ffaf80-ee84-11e8-823e-37b7df400290.png)

2. mouse click to open gvim.exe or vim.exe,  exe `:!cmd`, and run `chcp` as follow:
![image](https://user-images.githubusercontent.com/19503791/48896904-b6cfd380-ee83-11e8-8ca1-13266bf6412a.png)

**Comment by k-takata** [comment]
Please explain what you did more detail.
Step-by-step instructions might be better.
Please also write your platform and versions.

**Comment by k-takata** [comment]
Do you execute vim.exe or gvim.exe? It looks you are using gvim.exe.

**Comment by zgpio** [comment]
If I use mouse click to open vim.exe or gvim.exe, the cmd's code page is wrong(cp936);
If I start vim.exe from cmd.exe, which code page is already utf-8,  and then exe `:!cmd`, the cmd's code page is right(utf-8).

**Comment by k-takata** [comment]
`chcp` only changes the code page of the current command prompt. It doesn't affect globally.
Not an issue of Vim, so closing.

**Comment by zgpio** [comment]
Not like this, you misunderstood, I modified the code page through the registry, I use `chcp` just for show the code page rather than change it.

**Comment by k-takata** [comment]
How did you modify the registry? Which do you use 32- or 64-bit Vim?

**Comment by zgpio** [comment]
I got it, It seems vimrun.exe has its own item of Regitstry. As follow:
![image](https://user-images.githubusercontent.com/19503791/48899009-4b890000-ee89-11e8-9101-f6a472cbf79d.png)
Now I add CodePage to vimrun item, it works.

What role does `vimrun.exe` play?
