### ISSUE TITLE
quickfix: appending (action "a") makes items to become "recognized" for :lwindow

### ISSUE THREAD

**Issue by blueyed** [vim/vim#3633]
Using `setloclist()` with action "a" for appending makes the list to contain
"recognized" items so that ":lwinow" will open it, although all entries have
`valid = 0`.

```vim
call setloclist(0, [{'text': 1}])

" :lwindow does not open it
let wbefore = winnr('$')
lwindow
call assert_equal(wbefore, winnr('$'))

" Bug: :lwindow opens it
call setloclist(0, [{'text': 1}], 'a')
lwindow
call assert_equal(wbefore, winnr('$'))

call assert_equal(map(getloclist(0), 'v:val.valid'), [0, 0])

if empty(v:errors)
  q
endif
echoerr string(v:errors)
cq
```

```
% vim -Nu t-lwindow.vim                                                                                                             ⟳(c) ⟳(m) 🐍? (neomake@3.7.1)
Error detected while processing /home/daniel/src/neomake/t-lwindow.vim:
line   18:
['…/t-lwindow.vim line 11: Expected 1 but got 2']
```

Vim 8.1.542.

A related patch in this regard was v7.4.379 / 158a1b074, where this was happening with "r".

**Comment by vim-ml** [comment]
Hi,

On Thu, Nov 22, 2018 at 9:16 AM Daniel Hahler <vim-dev-github@256bit.org>
wrote:

> Using setloclist() with action "a" for appending makes the list to contain
> "recognized" items so that ":lwinow" will open it, although all entries
> have
> valid = 0.
>
> call setloclist(0, [{'text': 1}])
> " :lwindow does not open itlet wbefore = winnr('$')lwindowcall assert_equal(wbefore, winnr('$'))
> " Bug: :lwindow opens itcall setloclist(0, [{'text': 1}], 'a')lwindowcall assert_equal(wbefore, winnr('$'))
> call assert_equal(map(getloclist(0), 'v:val.valid'), [0, 0])
> if empty(v:errors)
>   qendifechoerr string(v:errors)cq
>
> % vim -Nu t-lwindow.vim                                                                                                             ⟳(c) ⟳(m) 🐍? (neomake@3.7.1)
> Error detected while processing /home/daniel/src/neomake/t-lwindow.vim:
> line   18:
> ['…/t-lwindow.vim line 11: Expected 1 but got 2']
>
> Vim 8.1.542.
>
> A related patch in this regard was v7.4.379 / 158a1b0
> <https://github.com/vim/vim/commit/158a1b074828341767ad4ce912b346bf14189605>,
> where this was happening with "r".
>

Can you try the attached patch?

Thanks,
Yegappan

**Comment by blueyed** [comment]
That fixes it, thanks!

**Comment by blueyed** [comment]
I found another, apparently related issue, not fixed by the above patch:

Given `t-setqf-append.vim`:
```vim
let list = [
      \ {'lnum': 1, 'bufnr': bufnr('%'), 'text': '1', 'valid': 0},
      \ {'lnum': 2, 'bufnr': bufnr('%'), 'text': '2', 'valid': 0}]
call setloclist(0, list)
echom string(map(getloclist(0), 'v:val.valid'))

" Works.
lnext
lprev

call setloclist(0, [])
call setloclist(0, list, 'a')
echom string(map(getloclist(0), 'v:val.valid'))

" Does not work.
lnext
lprev
```

Outputs:

```
% vim -Nu t-setqf-append.vim
[0, 0]
(2 of 2) error: 2
(1 of 2) error: 1
[0, 0]
(1 of 2) error: 2
Error detected while processing …/src/neomake/t-setqf-append.vim:
line   12:
E553: No more items
```

I.e. in both cases the entries have valid=0, but in the first case `lprev/lnext` work.

The help for `:cnext` says that it is about entries having a file name, which probably internally is mapped to valid/bufnr/filename.

I am not sure what the correct behavior should be here, but it should be consistent.
I suggest relying on the provided "valid", and therefore it should be handled as if there was no file name (i.e. as if Vim would have set it valid=0 itself).

**Comment by blueyed** [comment]
Setting the "valid" flag was added in v8.0.0580 (f1d21c8cc).

**Comment by vim-ml** [comment]
Hi,

On Mon, Dec 3, 2018 at 8:22 PM Daniel Hahler <vim-dev-github@256bit.org> wrote:
>
> I found another, apparently related issue, not fixed by the above patch:
>
> Given t-setqf-append.vim:
>
> let list = [
>
>       \ {'lnum': 1, 'bufnr': bufnr('%'), 'text': '1', 'valid': 0},
>
>       \ {'lnum': 2, 'bufnr': bufnr('%'), 'text': '2', 'valid': 0}]
>
> call setloclist(0, list)
>
> echom string(map(getloclist(0), 'v:val.valid'))
>
>
>
> " Works.
>
> lnext
>
> lprev
>
>
>
> call setloclist(0, [])
>
> call setloclist(0, list, 'a')
>
> echom string(map(getloclist(0), 'v:val.valid'))
>
>
>
> " Does not work.
>
> lnext
>
> lprev
>
> Outputs:
>
> % vim -Nu t-setqf-append.vim
>
> [0, 0]
>
> (2 of 2) error: 2
>
> (1 of 2) error: 1
>
> [0, 0]
>
> (1 of 2) error: 2
>
> Error detected while processing …/src/neomake/t-setqf-append.vim:
>
> line   12:
>
> E553: No more items
>
> I.e. in both cases the entries have valid=0, but in the first case lprev/lnext work.
>
> The help for :cnext says that it is about entries having a file name, which probably internally is mapped to valid/bufnr/filename.
>
> I am not sure what the correct behavior should be here, but it should be consistent.
> I suggest relying on the provided "valid", and therefore it should be handled as if there was no file name (i.e. as if Vim would have set it valid=0 itself).
>

Can you try the attached patch which includes the previous patch also?

- Yegappan

**Comment by vim-ml** [comment]
Hi,

On Mon, Dec 3, 2018 at 11:36 PM Yegappan Lakshmanan <yegappanl@gmail.com> wrote:
>
> On Mon, Dec 3, 2018 at 8:22 PM Daniel Hahler <vim-dev-github@256bit.org> wrote:
> >
> > I found another, apparently related issue, not fixed by the above patch:
> >
> > Given t-setqf-append.vim:
> >
> > let list = [
> >       \ {'lnum': 1, 'bufnr': bufnr('%'), 'text': '1', 'valid': 0},
> >       \ {'lnum': 2, 'bufnr': bufnr('%'), 'text': '2', 'valid': 0}]
> >
> > call setloclist(0, list)
> > echom string(map(getloclist(0), 'v:val.valid'))
> >
> > " Works.
> > lnext
> > lprev
> >
> > call setloclist(0, [])
> > call setloclist(0, list, 'a')
> > echom string(map(getloclist(0), 'v:val.valid'))
> >
> > " Does not work.
> > lnext
> > lprev
> >
> > Outputs:
> > % vim -Nu t-setqf-append.vim
> > [0, 0]
> > (2 of 2) error: 2
> > (1 of 2) error: 1
> > [0, 0]
> > (1 of 2) error: 2
> > Error detected while processing …/src/neomake/t-setqf-append.vim:
> > line   12:
> > E553: No more items
> >
> > I.e. in both cases the entries have valid=0, but in the first case lprev/lnext work.
> >
> > The help for :cnext says that it is about entries having a file name, which probably internally is mapped to valid/bufnr/filename.
> >
> > I am not sure what the correct behavior should be here, but it should be consistent.
> > I suggest relying on the provided "valid", and therefore it should be handled as if there was no file name (i.e. as if Vim would have set it valid=0 itself).
> >
>
> Can you try the attached patch which includes the previous patch also?
>

I am attaching an updated patch that makes the "lnext/lprev" commands work
in both cases. I think this is consistent with other commands like cfile/lfile.
The patch also includes a test.

- Yegappan

**Comment by blueyed** [comment]
Yegappan, thanks again.  That fixes everything in this regard.

**Comment by vim-ml** [comment]
Hi Bram,

On Tue, Dec 4, 2018 at 9:05 AM Yegappan Lakshmanan <yegappanl@gmail.com> wrote:
>
> >
> > On Mon, Dec 3, 2018 at 8:22 PM Daniel Hahler <vim-dev-github@256bit.org> wrote:
> > >
> > > I found another, apparently related issue, not fixed by the above patch:
> > >
> > > Given t-setqf-append.vim:
> > >
> > > let list = [
> > >       \ {'lnum': 1, 'bufnr': bufnr('%'), 'text': '1', 'valid': 0},
> > >       \ {'lnum': 2, 'bufnr': bufnr('%'), 'text': '2', 'valid': 0}]
> > >
> > > call setloclist(0, list)
> > > echom string(map(getloclist(0), 'v:val.valid'))
> > >
> > > " Works.
> > > lnext
> > > lprev
> > >
> > > call setloclist(0, [])
> > > call setloclist(0, list, 'a')
> > > echom string(map(getloclist(0), 'v:val.valid'))
> > >
> > > " Does not work.
> > > lnext
> > > lprev
> > >
> > > Outputs:
> > > % vim -Nu t-setqf-append.vim
> > > [0, 0]
> > > (2 of 2) error: 2
> > > (1 of 2) error: 1
> > > [0, 0]
> > > (1 of 2) error: 2
> > > Error detected while processing …/src/neomake/t-setqf-append.vim:
> > > line   12:
> > > E553: No more items
> > >
> > > I.e. in both cases the entries have valid=0, but in the first case lprev/lnext work.
> > >
> > > The help for :cnext says that it is about entries having a file name, which probably internally is mapped to valid/bufnr/filename.
> > >
> > > I am not sure what the correct behavior should be here, but it should be consistent.
> > > I suggest relying on the provided "valid", and therefore it should be handled as if there was no file name (i.e. as if Vim would have set it valid=0 itself).
> > >
> >
> > Can you try the attached patch which includes the previous patch also?
> >
>
> I am attaching an updated patch that makes the "lnext/lprev" commands work
> in both cases. I think this is consistent with other commands like cfile/lfile.
> The patch also includes a test.
>

This patch is now ready to be merged.

Thanks,
Yegappan
