### ISSUE TITLE
Configuration doesn't work for :tabnew

### ISSUE THREAD

**Issue by bheadmaster** [vim/vim#3635]
I use a configuration in my .vimrc for highlighting lines that are longer than 80 characters.
>match ErrorMsg '\%>80v.\+'

However it doesn't work when using tabs in vim.

How to reproduce:
>add `match ErrorMsg '\%>80v.\+'` to .vimrc
>open vim
>100ia\<ESC\> (the last 20 characters are highlighted)
>:tabnew
>100ia\<ESC\> (none of the characters are highlighted)

**Comment by chrisbra** [comment]
It does. However the match command only applies to the first window. You need an autocommand to have it re-apply to other windows. However that is a configuration issue. No Vim bug here. 
Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com.  We cannot provide individual help here. Closing.
