### ISSUE TITLE
Feature request: provide a way to open preview window without click a valid tag.

### ISSUE THREAD

**Issue by kgfly** [vim/vim#3643]
I generally install https://github.com/vim-scripts/autopreview to my vim. So whenever, I clicked a tag, the  preview window can be opened automatically. I generally split windows virtually .

Current status:
To split window, I've to click a valid tag first. And wait till the preview window to be opened. Then split. So the windows layout looks like:

![image](https://user-images.githubusercontent.com/12282281/49125669-b49bb980-f275-11e8-8ef3-1e62becd7bfd.png)

This is the windows layout I need. But this is very inconvenient. Because I've to click a valid tag and wait till the preview windows is open.

On the other hand, if I did not click and wait and I split the windows first, then when the preview windows is open, the layout looks like this: This is not the layout I want.

![image](https://user-images.githubusercontent.com/12282281/49125692-c67d5c80-f275-11e8-8baa-925cd730b1f2.png)

Expected:
provide a way to open preview windows without click a valid tag. So people does not need click and wait. People can open preview window whenever they want, etc on startup. I believe many user could hit this issue.

**Comment by chrisbra** [comment]
you can already use `:pedit` to open the preview window and edit another file.

**Comment by kgfly** [comment]
Oh. Thanks for letting me know. I am not aware of it. I asked this Q in Google vim community. But no one replied. So I thought it's not implemented. Anyway, thanks.
