### ISSUE TITLE
vim autoindent not work in vim 8.0

### ISSUE THREAD

**Issue by nobody93** [vim/vim#3648]
I've used vim for many years for c++ program, it worked perfect until now in Ubuntu 18.4 vim version 8.0, autoindent is no longer working, what has been changed?

**Comment by chrisbra** [comment]
You are not giving much information. First of all, I don't remember any autoindentation changes (except perhaps runtime updates). Of course you can always have a look at `:h version8` to see what changed in each version. Then you might check the various indent options, how they are set (and also whether or not you are using indent plugins at all). And last, I suggest asking user questions either at the vim-use mailinglist or at vi.stackexchange.com. This one is for the discussion of bugs in Vim and we cannot provide individual support here. 

If you still think there is a bug, please provide a reproducible example, starting with `vim --clean`. Closing so long. Thanks for understanding.
