### ISSUE TITLE
job_start and job_stop on OpenBSD

### ISSUE THREAD

**Issue by olitb** [vim/vim#3656]
On OpenBSD, job_stop never kills the whole process group. Since job_start is often used to run sh -c 'single command', only the sh process gets a SIGTERM and job_stop does not terminate 'single command'. The reason for this is that job_start (mch_job_start in src/os_unix.c) calls setsid (after fork and before execvp) to create a new process group, but this also creates a new terminal session. Then in job_stop (via mch_signal_job in src/os_unix.c) vim first checks if the job is group leader using getpgid, and sends SIGTERM to the whole group only if it is. But on OpenBSD, getpgid returns EPERM (-1) when a process tries to checks another process in a different session.
There are two ways to fix this:
1) replace setsid() by setpgid(0, 0) in mch_job_start, so that only a new process group is created. This may have surprising side effects, because the jobs now share the same terminal as the parent vim process, although this is (incorrectly) explained in vim's help for job_start.
2) Remove the if (job_pid == getpgid(job_pid)) check in mch_signal_job.

**Comment by kernigh** [comment]
I suggest the 2nd way, to remove the getpgid call. I helped with a similar removal in [meson commit 64906b0](https://github.com/mesonbuild/meson/commit/64906b0). When job_start calls setsid(2) or setpgid(2) to create the process group, the process group id is equal to the process id. I believe that job_stop should go ahead and kill this process group.

This small patch to remove getpgid worked for me with Vim 8.1.0438 on OpenBSD.

```diff
Index: src/os_unix.c
--- src/os_unix.c.orig
+++ src/os_unix.c
@@ -5871,11 +5871,7 @@ mch_signal_job(job_T *job, char_u *how)
 	return FAIL;
 
     /* TODO: have an option to only kill the process, not the group? */
-    job_pid = job->jv_pid;
-#ifdef HAVE_GETPGID
-    if (job_pid == getpgid(job_pid))
-	job_pid = -job_pid;
-#endif
+    job_pid = -job->jv_pid;
 
     /* Never kill ourselves! */
     if (job_pid != 0)
```

This patch doesn't fix Vim's documentation. It says for job_start, "The job will use the same terminal as Vim." This is wrong when Vim calls setsid(2) to detach the job from the terminal.

**Comment by brammool** [comment]
This changes causes Test_job_stop_immediately() to fail on Linux.
Perhaps we should both kill(-pid) and kill(pid) ?

**Comment by blueyed** [comment]
> Perhaps we should both kill(-pid) and kill(pid) ?

This is prone to races (you might kill a newly created PID).

This might be caused by how the forking is done, and the child not being setup/configured fast enough.

I suggest doing at least the following to skip it if not needed:
```diff
diff --git i/src/os_unix.c w/src/os_unix.c
index 6387a7757..d672e99c6 100644
--- i/src/os_unix.c
+++ w/src/os_unix.c
@@ -5855,8 +5855,8 @@ mch_signal_job(job_T *job, char_u *how)
     if (job->jv_pid != 0)
     {
        // TODO: have an option to only kill the process, not the group?
-       kill(-job->jv_pid, sig);
-       kill(job->jv_pid, sig);
+       if (kill(-job->jv_pid, sig))
+           kill(job->jv_pid, sig);
     }

     return OK;
```

**Comment by blueyed** [comment]
libuv uses a pipe to communicate / wait for the child to call `execve`: https://github.com/neovim/libuv/blob/c41b31ed3b88aacae1d8498d0f3f6bbc20d56f9a/src/unix/process.c#L469-L491 - looks very relevant.

**Comment by brammool** [comment]
Daniel Hahler wrote:

> > Perhaps we should both kill(-pid) and kill(pid) ?
> 
> This is prone to races (you might kill a newly created PID).
> 
> This might be caused by how the forking is done, and the child not being setup/configured fast enough.
> 
> I suggest doing at least the following to skip it if not needed:
> ```diff
> diff --git i/src/os_unix.c w/src/os_unix.c
> index 6387a7757..d672e99c6 100644
> --- i/src/os_unix.c
> +++ w/src/os_unix.c
> @@ -5855,8 +5855,8 @@ mch_signal_job(job_T *job, char_u *how)
>      if (job->jv_pid != 0)
>      {
>         // TODO: have an option to only kill the process, not the group?
> -       kill(-job->jv_pid, sig);
> -       kill(job->jv_pid, sig);
> +       if (kill(-job->jv_pid, sig))
> +           kill(job->jv_pid, sig);
>      }
> 
>      return OK;
> ```

These things always have portability issues.  Since I haven't hear users
complain, making a change here might actually cause a problem.

I'm not really afraid the pid gets reused so quickly.

-- 
Female engineers become irresistible at the age of consent and remain that
way until about thirty minutes after their clinical death.  Longer if it's a
warm day.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
