### ISSUE TITLE
quickfix: vcol only appears to handle tabs

### ISSUE THREAD

**Issue by blueyed** [vim/vim#3658]
The help for vcol says:

> vcol	|TRUE|: "col" is visual column
>		|FALSE|: "col" is byte index

But it appears to only handle tab characters: https://github.com/vim/vim/blob/b513d3079bbe3f59a1f1a3d6931939a76cd7e54a/src/quickfix.c#L3100-L3120

Either the help (and internal documentation) should be clearer on this, or it should be changed to actually handle also multibyte characters.

I've found that e.g. ALE does this manually already, so in this case it would not be backward compatible, but ALE could check the patch number of course: https://github.com/w0rp/ale/blob/0a384a49d371838903d8401c5358ec60f3f4266d/autoload/ale/engine.vim#L444-L449

After all "vcol" in ALE appears to be "mis-used", but it would certainly be helpful if there was a way to handle quickfix entries that refer to char offsets instead of bytes more easily, and it appears that vcol could be extended to support this.

**Comment by chrisbra** [comment]
I am not sure what the issue for ALE is, but it seems to merely converting the vcol to a byte column. 
Note, that the vcol will only differ for TABs, since those appear to take more space than the actual character does. So the current logic in quickfix.c makes sense. The virtcol for multibyte characters should not differ, as long as they occupy a single cell.
The only exception being double width characters, which do not seem to be handled at all but probably should.

**Comment by blueyed** [comment]
> The only exception being double width characters, which do not seem to be handled at all but probably should.

Yes, that's what I've meant: the "col" refers to the byte index, which does not match the virtual column necessarily, e.g. with "1│345".
The question however is if this should be done automatically with "vcol=1" also, or if this would be kept only for handling of TABs.

I was about to use `byteidx()` for this, but recognized that there is quite some overhead involved, since you have to get the buffer's line also then for each entry.

**Comment by blueyed** [comment]
> I am not sure what the issue for ALE is, but it seems to merely converting the vcol to a byte column.

Yes - since Vim itself uses "col" as bytes, ALE converts the char offset to bytes.

**Comment by w0rp** [comment]
I assume that "visual column" as mentioned in `:help setqflist` means a column you see, as in multi-byte characters. What ALE does is let you pass on messages with `'vcol': 1` for multibyte characters, and leaves the rest to Vim. It makes sense for anyone who feels like making the changes to implement multi-byte character support for `vcol`.

**Comment by brammool** [comment]
> The help for vcol says:
> 
> > vcol	|TRUE|: "col" is visual column
> >		|FALSE|: "col" is byte index

You mean the help for getqflist() and setqflist().

> But it appears to only handle tab characters: https://github.com/vim/vim/blob/b513d3079bbe3f59a1f1a3d6931939a76cd7e54a/src/quickfix.c#L3100-L3120

That's a weird loop, doesn't handle multi-byte characters at all.
Relies on a TAB not being part of a multi-byte character.
If it would consider multi-byte characters it could probably use
coladvance() (except that perhaps tabs must always be counted as eight
characters).

> Either the help (and internal documentation) should be clearer on
> this, or it should be changed to actually handle also multibyte
> characters.
> 
> I've found that e.g. ALE does this manually already, so in this case
> it would not be backward compatible, but ALE could check the patch
> number of course:
> https://github.com/w0rp/ale/blob/0a384a49d371838903d8401c5358ec60f3f4266d/autoload/ale/engine.vim#L444-L449
> 
> After all "vcol" in ALE appears to be "mis-used", but it would
> certainly be helpful if there was a way to handle quickfix entries
> that refer to char offsets instead of bytes more easily, and it
> appears that vcol could be extended to support this.

I don't know if ALE matters, but we should be able to handle what
compilers produce.  This is the %v item in 'errorformat'.  It's
important that this works properly, the rest will follow.

I suppose this requires a multi-byte aware compiler to start with.
When I try gcc it outputs the byte column, thus that doesn't function as
an example.  What other popular compiler actually outputs virtual
columns?


-- 
CART DRIVER: Bring out your dead!
   We follow the cart through a wretched, impoverished plague-ridden village.
   A few starved mongrels run about in the mud scavenging.  In the open
   doorway of one house perhaps we jug glimpse a pair of legs dangling from
   the ceiling.  In another doorway an OLD WOMAN is beating a cat against a
   wall rather like one does with a mat.  The cart passes round a dead donkey
   or cow in the mud.  And a MAN tied to a cart is being hammered to death by
   four NUNS with huge mallets.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by blueyed** [comment]
> What other popular compiler actually outputs virtual columns?

One example here would be flake8 (a Python linter).
Please let me now if you need a concrete example - but in general we should just assume that programs might use the "virtual" column offset.

**Comment by vim-ml** [comment]
Hi,

On Wed, Dec 5, 2018 at 12:50 PM Bram Moolenaar
<vim-dev-github@256bit.org> wrote:
>
> > The help for vcol says:
> >
> > > vcol |TRUE|: "col" is visual column
> > > |FALSE|: "col" is byte index
>
> You mean the help for getqflist() and setqflist().
>
> > But it appears to only handle tab characters: https://github.com/vim/vim/blob/b513d3079bbe3f59a1f1a3d6931939a76cd7e54a/src/quickfix.c#L3100-L3120
>
> That's a weird loop, doesn't handle multi-byte characters at all.
> Relies on a TAB not being part of a multi-byte character.
> If it would consider multi-byte characters it could probably use
> coladvance() (except that perhaps tabs must always be counted as eight
> characters).
>

I normally don't use multi-byte characters. So I am not sure how to address
this issue.

Regards,
Yegappan

>
> > Either the help (and internal documentation) should be clearer on
> > this, or it should be changed to actually handle also multibyte
> > characters.
> >
> > I've found that e.g. ALE does this manually already, so in this case
> > it would not be backward compatible, but ALE could check the patch
> > number of course:
> > https://github.com/w0rp/ale/blob/0a384a49d371838903d8401c5358ec60f3f4266d/autoload/ale/engine.vim#L444-L449
> >
> > After all "vcol" in ALE appears to be "mis-used", but it would
> > certainly be helpful if there was a way to handle quickfix entries
> > that refer to char offsets instead of bytes more easily, and it
> > appears that vcol could be extended to support this.
>
> I don't know if ALE matters, but we should be able to handle what
> compilers produce. This is the %v item in 'errorformat'. It's
> important that this works properly, the rest will follow.
>
> I suppose this requires a multi-byte aware compiler to start with.
> When I try gcc it outputs the byte column, thus that doesn't function as
> an example. What other popular compiler actually outputs virtual
> columns?
>

**Comment by w0rp** [comment]
One example of multi-byte output is that Python variable names can contain multi-byte Unicode characters. `flake8` can report that an error begins at a character offset which differs from the byte offset.

**Comment by brammool** [comment]
> One example of multi-byte output is that Python variable names can
> contain multi-byte Unicode characters. `flake8` can report that an
> error begins at a character offset which differs from the byte offset.

A quick check shows that flake8 reports byte columns.
That is when using multi-byte characters in a string and the report is
after it.

-- 
If all you have is a hammer, everything looks like a nail.
When your hammer is C++, everything begins to look like a thumb.
			-- Steve Hoflich, comp.lang.c++

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by blueyed** [comment]
> A quick check shows that flake8 reports byte columns.

What have you tried?

Given `t.py`:
```
foo = '1│345'
```

`flake8 --max-line-length=10 t.py` displays:
```
t.py:1:11: E501 line too long (13 > 10 characters)
```

And `:laddexpr 't.py:1:11: E501 line too long (13 > 10 characters)'` in Vim will use col=11, but jumps to the visual column 9.

So at least in this case flake8 is refering to the visual column.
With only `foo = '1│3'` it still reports the line being too long, but not with `foo = '1│' (10 visual chars).

**Comment by brammool** [comment]
> > A quick check shows that flake8 reports byte columns.
> 
> What have you tried?
> 
> Given `t.py`:
> ```
> foo = '1│345'
> ```
> 
> `flake8 --max-line-length=10 t.py` displays:
> ```
> t.py:1:11: E501 line too long (13 > 10 characters)
> ```

Bad example, "line too long" is not bound to a certain column.

> And `:laddexpr 't.py:1:11: E501 line too long (13 > 10 characters)'`
> in Vim will use col=11, but jumps to the visual column 9.
> 
> So at least in this case flake8 is refering to the visual column.
> With only `foo = '1│3'` it still reports the line being too long, but
> not with `foo = '1│' (10 visual chars).


Running in the src directory and changing dehqx.py a bit:

./dehqx.py:27:21: E701 multiple statements on one line (colon)

I made line 27:

    if x != 'äøé': break

Here "21" is pointing to the colon, which is at byte 21.
In characters it is 18, since the three multi-byte characters take 2
bytes each.


-- 
BLACK KNIGHT: I'm invincible!
ARTHUR:       You're a looney.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by blueyed** [comment]
> Bad example, "line too long" is not bound to a certain column.

Well, it refers to the column after all, and does not say "too many bytes".

Given your example it looks like flake8 might be inconsistent here?!

But I am seeing it reported as 18 with your change:

> src/dehqx.py:27:18: E701 multiple statements on one line (colon)

Maybe py2/py3 is relevant here?

I have `flake8 --version`:

> 3.6.0 (mccabe: 0.6.1, pycodestyle: 2.4.0, pyflakes: 2.0.0) CPython 3.7.1 on Linux

Anyway, let's just assume that it is possible to have this with some output.

Do you still think your suggested fix applies?

> If it would consider multi-byte characters it could probably use
coladvance() (except that perhaps tabs must always be counted as eight
characters).

**Comment by vim-ml** [comment]
Hi,

On Fri, Dec 7, 2018 at 1:33 PM Daniel Hahler <vim-dev-github@256bit.org> wrote:
>
> Bad example, "line too long" is not bound to a certain column.
>
> Well, it refers to the column after all, and does not say "too many bytes".
>
> Given your example it looks like flake8 might be inconsistent here?!
>
> But I am seeing it reported as 18 with your change:
>
> src/dehqx.py:27:18: E701 multiple statements on one line (colon)
>
> Maybe py2/py3 is relevant here?
>
> I have flake8 --version:
>
> 3.6.0 (mccabe: 0.6.1, pycodestyle: 2.4.0, pyflakes: 2.0.0) CPython 3.7.1 on Linux
>
> Anyway, let's just assume that it is possible to have this with some output.
>
> Do you still think your suggested fix applies?
>
> If it would consider multi-byte characters it could probably use
> coladvance() (except that perhaps tabs must always be counted as eight
> characters).
>

Can you try the attached patch?

Thanks,
Yegappan

**Comment by vim-ml** [comment]
Hi,

On Fri, Dec 7, 2018 at 1:33 PM Daniel Hahler <vim-dev-github@256bit.org> wrote:
>
> Bad example, "line too long" is not bound to a certain column.
>
> Well, it refers to the column after all, and does not say "too many bytes".
>
> Given your example it looks like flake8 might be inconsistent here?!
>
> But I am seeing it reported as 18 with your change:
>
> src/dehqx.py:27:18: E701 multiple statements on one line (colon)
>
> Maybe py2/py3 is relevant here?
>
> I have flake8 --version:
>
> 3.6.0 (mccabe: 0.6.1, pycodestyle: 2.4.0, pyflakes: 2.0.0) CPython 3.7.1 on Linux
>
> Anyway, let's just assume that it is possible to have this with some output.
>
> Do you still think your suggested fix applies?
>
> If it would consider multi-byte characters it could probably use
> coladvance() (except that perhaps tabs must always be counted as eight
> characters).
>

Patch 8.1.0859 to support multibyte characters using the '%v' item in
'errorformat' has been merged now.

Can you try out the latest version of Vim and see whether this issue has
been addressed?

Thanks,
Yegappan

**Comment by yegappan** [comment]
The support for this was added in Patch 8.1.0859. Can this issue be closed now?
