### ISSUE TITLE
silent commands in execute() still generate output

### ISSUE THREAD

**Issue by liushapku** [vim/vim#3659]
[This follows a discussion in [vim.stackexchange](https://vi.stackexchange.com/posts/18104/edit)]

`execute(command)` should return what `command` outputs. If `command` itself contains `silent!` then it should return empty string. However the following code

    let x = execute('silent echo 3')  " silent! does the same

will have `x == "\n3"`.

So there must be some inconsistency in evaluating `execute(command)` with `silent` already set by the `command` itself.

**Comment by tonymec** [comment]
I confirm the discrepancy: apparently `execute()` and `:execute` do not act identically in this matter.

The following display a 3 below the command-line:
* `:echo execute('silent echo 3')`
* `:echo execute('silent! echo 3')`
* `:echo execute('echo 3', 'silent')`
* `:echo execute('echo 3', 'silent!')`

The following don't:
* `:exe 'silent echo 3'`
* `:exe 'silent! echo 3'`
* `:silent exe 'echo 3'`
* `:silent! exe 'echo 3'`
* `:silent echo 3`
* `:silent! echo 3`

P.S. Tested on version 8.1.560.

Best regards,
Tony.

**Comment by liushapku** [comment]
@tonymec, I think `exe command` should be equivalent to `call execute(command, '')`; both run the command and echo the output to screen. If you test them you will find they always behave consistently.

**Comment by liushapku** [comment]
@chrisbra @justinmk Let me make a realistic example to show why I think the "silent" inside command should be respected.

### content of /tmp/error_file
> this line has no error
> this line has no error
> /tmp/a.txt:30
> /tmp/b.txt:40
> /tmp/c.txt:50 no error
> this line has no error

### script
``` vim
func! Third_party_func()
  " run a command to generate /tmp/error_file
  " start editing it (assume the content now is as shown above)
  edit /tmp/error_file  
  " do not complain 'Pattern not found: ...'
  silent! global/no error/delete
  " suppress '/tmp/error_file ... written' message
  silent w
  " do not tell me which file I am going to
  silent b#  
  " trigger event but do not complain if no event handler
  silent! doautocmd User Third_party_event  
  " display what is left in the file to the user
  !cat /tmp/error_file
endfunc

func! End_user_func() abort
  """""" miracle happened
  let g:except = split(execute('call Third_party_func()'), "\n")
  let &l:efm = '%f:%l'
  cgetexpr g:except
endfunc
```

Source the script and then `:call End_user_func()`. The following is what `g:except` is and you can imagine what the quickfix list will be populated

> 4 fewer lines
> "/tmp/error_file" 2L, 28C written
> No matching autocommands
> :!cat /tmp/error_file^M
>
> /tmp/a.txt:30
> /tmp/b.txt:40

More lines will be included if no line matches pattern '/no error/'

### the problem
The third party plugin provider would think he has correctly hidden the implementation details and avoided side effect to the UI and developed an excellent plugin (and it is). But when the end user want to further manipulate its result, he got all the rubbish back. 

Hope this explains the motivation of raising the issue ticket.

**Comment by brammool** [comment]
> @chrisbra @justinmk Let me make a realistic example to show why I
> think the "silent" inside command should be respected.
> 
> ### content of /tmp/error_file
> > this line has no error
> > this line has no error
> > /tmp/a.txt:30
> > /tmp/b.txt:40
> > /tmp/c.txt:50 no error
> > this line has no error
> 
> ### script
> ``` vim
> func! Third_party_func()
>   " run a command to generate /tmp/error_file
>   " start editing it (assume the content now is as shown above)
>   edit /tmp/error_file  
>   " do not complain 'Pattern not found: ...'
>   silent! global/no error/delete
>   " suppress '/tmp/error_file ... written' message
>   silent w
>   " do not tell me which file I am going to
>   silent b#  
>   " trigger event but do not complain if no event handler
>   silent! doautocmd User Third_party_event  
>   " display what is left in the file to the user
>   !cat /tmp/error_file
> endfunc

Why does this function output its result on the display, instead of
returning a list with the result?  I think this is very brittle and just
the wrong way to do this.
 
> func! End_user_func() abort
>   let g:except = split(execute('call Third_party_func()'), "\n")
>   let &l:efm = '%f:%l'
>   cgetexpr g:except
> endfunc
> ```
> 
> Source the script and then `:call End_user_func()`. The following is what `g:except` is and you can imagine what the quickfix list will be populated
> 
> > 4 fewer lines
> > "/tmp/error_file" 2L, 28C written
> > No matching autocommands
> > :!cat /tmp/error_file^M
> >
> > /tmp/a.txt:30
> > /tmp/b.txt:40
> 
> More lines will be included if no line matches pattern '/no error/'
> 
> ### the problem
> The third party plugin provider would think he has correctly hidden
> the implementation details and avoided side effect to the UI and
> developed an excellent plugin (and it is). But when the end user want
> to further manipulate its result, he got all the rubbish back. 
> 
> Hope this explains the motivation of raising the issue ticket.

Relying on silencing all messages is a bad idea.  It's also easy that
mistakes or syntax errors go missing, it will be very hard to debug.

In other words: this is not what execute() was intended for.

-- 
BEDEVERE:        And what do you burn, apart from witches?
FOURTH VILLAGER: ... Wood?
BEDEVERE:        So why do witches burn?
SECOND VILLAGER: (pianissimo) ... Because they're made of wood...?
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by liushapku** [comment]
Sure, if you are not persuaded by the example. 

I will later post a possible solution just for others who are also interested to try on their own accord.

Thanks.
