### ISSUE TITLE
Different colors for filename in gitcommit.vim

### ISSUE THREAD

**Issue by bartkim0426** [vim/vim#3660]
According to gitcommit.vim, vim doesn't support distinguish between new file and modified file when commit - nowdays almost every other editor support.

Is there any specific reason why not including this? 

If not I want to make this function - though how to know modify well. Should I add group for new & modified? 

[Here](https://stackoverflow.com/questions/53590727/how-to-show-different-colors-in-files-list-when-i-filling-git-commit-message-in/53599708#53599708)'s my SO answer for this question for detail information. Thanks

**Comment by chrisbra** [comment]
that should be discussed with the syntax file maintainer. By coincidence, I just submitted a PR for that feature: https://github.com/tpope/vim-git/pull/58

**Comment by bartkim0426** [comment]
Cool! Thanks
Anyway, is it ok to use add/mod/del in code? Is it translated automatically for other languages?

**Comment by chrisbra** [comment]
> Anyway, is it ok to use add/mod/del in code? Is it translated automatically for other languages?

No, the syntax rules are basically just regexpes parsing buffer content. If they need to match different languages, it needs to be done manually by adjusting the regexpes. Have a look at how e.g. [syntax/diff.vim](https://github.com/vim/vim/blob/master/runtime/syntax/diff.vim) handles it.

**Comment by bartkim0426** [comment]
Oh I understand. 

Then how about using regex instead of using English? 

It can divide at least "new file" and "modified/deleted" - using space like this. (Actually I tried to make my own)

```
syn match   gitcommitSelectedModifiedType	"\t\@<=[[:lower:]][^: ]*[[:lower:]]: "he=e-2	contained containedin=gitcommitComment nextgroup=gitcommitSelectedFile skipwhite
syn match   gitcommitSelectedNewType	"\t\@<=[[:lower:]][^:]*[\ ][[:lower:]][^:]*: "he=e-2	contained containedin=gitcommitComment nextgroup=gitcommitSelectedFile skipwhite
```

Cause I checked other few other languages and they use space for 'new file'.

**Comment by lilydjwg** [comment]
Did you check with Chinese or Japanese?

**Comment by bartkim0426** [comment]
@lilydjwg 
Man you're right I checked right before and notice it's one word. Sorry for that

**Comment by chrisbra** [comment]
how do the other editors handle that?

**Comment by chrisbra** [comment]
do they use regexes we can borrow?

**Comment by bartkim0426** [comment]
@chrisbra 
Great idea! I searched some. [VScode](https://github.com/Microsoft/vscode/blob/4e4e6f9b44/extensions/git/syntaxes/git-commit.tmLanguage.json#L104) only supports English. Others (Atom, Sublime text3) not support this function. I guess your way is the best plan. 

Anyway, thanks for your kind reply and support. It's my first time to participate in Github issue and it's a really great experience.
