### ISSUE TITLE
autocmd ColorScheme * MyCmd  NOT work

### ISSUE THREAD

**Issue by chanfried** [vim/vim#3661]
vim in windows 10, vversion 8.1, patch 1-497
Add autocmd ColorScheme * echo("color scheme test") in _vimrc file for test purpose.
Use ":colorscheme mycolor", color scheme changed ,but autocmd not invocked

**Comment by chrisbra** [comment]
Please try using `:echomsg` and then check using the `:messages` command for the output. I think the colorscheme caused a redraw that causes your `:echo` to be cleared.

**Comment by andymass** [comment]
Indeed, the redraw or clearing the echo happens some short time after the ColorScheme autocmd is fired.  You can also try `autocmd ColorScheme * echo 'test' | sleep 500m` which will show the echo briefly.

**Comment by chanfried** [comment]
Find the cause of the problem, I change color scheme for difference file type, so i add "autocmd  BufWinEnter * call ChangeScheme()",  and "autocmd ColorScheme * echo("color scheme test")" for testing. but colorscheme in ChangeScheme() function not invoke another autocmd(autocmd ColorScheme * echo("color scheme test"))，so plugin like indentLine work Incorrect.
Add "nested" fix this:   autocmd BufWinEnter * nested call SetScheme()
Thanks 
@chrisbra @andymass
