### ISSUE TITLE
New search is horrible and difficult to disable (MINT19)

### ISSUE THREAD

**Issue by jonshouse1** [vim/vim#3663]
The new search behaviour (text moving as search is typed) is horrible, unwelcome and breaks years of workflow, but I can't seem to turn it off.

Not sure why people feel they can change default behaviours without reference to users, but no hum.

Using "set noincsearch" seems to disable it, yet adding that as the last line to /etc/vim/vimrc does not work !   This to me is a bug, as a user I would expect whatever is at the end of vimrc to be parsed LAST.

I cant see any user vim configuration files, /etc/vimrc is being parsed at some point as adding an error here is picked up when starting vim.

**Comment by chrisbra** [comment]
Use a custom vimrc file. After all that's what it is for :)
Otherwise, I believe this is a duplicate of #2841 and related issues.

**Comment by jonshouse1** [comment]
> Use a custom vimrc file. After all that's what it is for :)

Clear as mud. What makes a vimrc file "custom"?, is that $HOME/.vimrc or similar?

I want this feature disabled globally, so is "/etc/vim/vimrc" not the correct location ?

Is this not parsed last ? - If not, then what is overriding "set noincsearch" at the end of /etc/vim/vimrc ?

**Comment by chrisbra** [comment]
Copying from Debians `/etc/vim/vimrc`

> " Vim will load $VIMRUNTIME/defaults.vim if the user does not have a vimrc.
> " This happens after /etc/vim/vimrc(.local) are loaded, so it will override
> " any settings in these files.
> " If you don't want that to happen, uncomment the below line to prevent
> " defaults.vim from being loaded.
> " let g:skip_defaults_vim = 1

Also, please see the related discussions around #2841 and #2042 

It has been discussed to death without coming to a clear conclusion.

**Comment by h-east** [comment]
@jonshouse1 Execute the following command on Vim and check the location where `incsearch` is set.

```vim
:verbose set incsearch?
```

**Comment by jonshouse1** [comment]
Part of the problem with this comment is it assumes the user built the package!  

" # echo $VIMRUNTIME

Errrrrrrr .... so what path is that?

I tried uncommenting "let g:skip_defaults_vim = 1", works.... but now I lose the actual useful colour and syntax highlighting.


strace seems to show that this is parsed last:
stat("/usr/share/vim/vim80/scripts.vim", {st_mode=S_IFREG|0644, st_size=11367, ...}) = 0
fstat(3, {st_mode=S_IFREG|0644, st_size=11367, ...}) = 0
read(3, "\" Vim support file to detect fil"..., 4096) = 4096

Ahhh ... your message just poped up, same result
":verbose set incsearch?"
Last set from /usr/share/vim/vim80/defaults.vim

As a user this looks wrong to me,   I would expect the order to be load plugins (with a text config in /etc/vim/vimplugins for that) then parse /etc/vim/vimrc  then parse user vimrc ?

**Comment by jonathonf** [comment]
> Part of the problem with this comment is it assumes the user built the package!

If you're using someone else's package then you should also check that it's not a packaging issue. It wouldn't be the first time.

**Comment by chrisbra** [comment]
well, you can also do something along:

         unlet! skip_defaults_vim
         source $VIMRUNTIME/defaults.vim
         let g:skip_defaults_vim = 1
         set noincsearch

**Comment by jonshouse1** [comment]
"If you're using someone else's package then you should also check that it's not a packaging issue. It wouldn't be the first time."
Almost every user is using "someone elses package" ?  Out of the installed user base of vim the number of "from source" installers must be a fraction of a percent.
 
Part of the issue is that the vim devlopers seem to have rejected the purpose of /etc  - having their own sprawling tree of config text with a couple of symlinks band aided in does not fix the issue.
I see that vim in now pretty complex, but even so, I think the user config system looks partially broken from both a users and maintainers perspective.

**Comment by jonshouse1** [comment]
The main issue for me is that now this new search behaviour has been made a default I need to "fix" it on every new machine I install, every ssh session I make... pretty soon every machine is infected with this new horrible behaviour.

Who decided this new seach was "good"? 

If I wanted my text to dart around, and force the use of an extra keypress rather just "/" for "find next" then I would have used ANY other editor or IDE.

**Comment by chrisbra** [comment]
Not going to comment about the changes how the system vimrc file is handled. As mentioned before, this has been discussed in various issues before. And the change comes from [7.4.2111](https://github.com/vim/vim/commit/8c08b5b569e2a9e9f63dea514591ecfa2d3bb392), more than 2 years ago.

> Who decided this new seach was "good"?

This was discussed here: https://groups.google.com/d/msg/vim_use/iXH_Zxj8iBA/zWo19VFhAwAJ

and quite frankly, within the last two years, that is the first time I hear a complain about the incsearch default.

**Comment by jonshouse1** [comment]
"more than 2 years ago"
Two years for you, two days for me.  MINT19 is the first ditro I have installed with this feature, i've never seen it before, I did not hear anything about it.

Let me be clear here. I use a lot of Linux.
Linux servers, Linux main workstation, Linux laptops, I maintain racks of machines with Linux for customers... not ONE of them has this new search behaviour.  

Installing MINT19 xfce on my main workstation was the first time i've come across it, I only did that because for some reason my HP desktop decided to stop reliably booting my previous install of mint18.3 (thanks to systemd I will never know why, more "progress").

**Comment by chrisbra** [comment]
So how long should we wait after a change is made to know for sure? 5 years?
Certainly changing the defaults now back again we will hear a lot of complaints about breaking users expectations again. Vim has been very careful about being backward compatible. However the conservative settings have been a major complain by many users, so it was decided that a major release is a good time for introducing new defaults. 

Unfortunately people are still unhappy, partly because it seems there are many people who do not use a user specific vimrc file and simply used the system wide vimrc config file (I had a similar discussion with several Debian users) which will get overwritten by defaults.vim as you found out. 

Anyhow, this is really a duplicate. Closing.

**Comment by tonymec** [comment]
tooth pik wrote:
> i would have voted to have noincsearch be the default had i been paying attention -- incsearch would be horribly hard to live with and i don't get why anyone would want it turned on, let alone the majority?

It is a common fallacy to attribute one's own preferences to "everyone, or at least a large majority". Don't rush too fast to the idea that everyone has the same preferences as yourself. *«Tous les goûts sont dans la nature.»*

Incremental search existed (albeit in a less powerful fashion than today) since before I knew Vim (and I know Vim since version 6.1 or thereabouts), it wasn't the program default but it was set IIRC by the `vimrc_example.vim` (which my own `.vimrc` sources) and I've never felt the need to disable it. I don't think I'm alone in my case, or even in a small minority, but I have no proof; however, since you assert (also without proof, I suppose) that "most people" want `'noincsearch'` and that `'incsearch'` "would be horribly hard to live with" I feel obliged to react and say that I am of the opposite opinion.

Best regards,
Tony.

**Comment by jonshouse1** [comment]
> Unfortunately people are still unhappy, partly because it seems there are many people who do not use a user specific vimrc file and simply used the system wide vimrc config file (I had a similar discussion with several Debian users) which will get overwritten by defaults.vim as you found out.

I read this as "I've had similar discussions with people who expect vim configuration to act in a sane way" ....

At very least  /etc/vim/vimrc should be parsed 2nd from last, $HOME/vimrc last of all  ?  The USER should always win over the "default" yes ?

**Comment by tonymec** [comment]
@jonshouse1 said:
> At very least /etc/vim/vimrc should be parsed 2nd from last, $HOME/vimrc last of all ? The USER should always win over the "default" yes ?

The system vimrc (whose location can be set at compile-time, see near the middle of the output of `:version`) is usually sourced first, or almost (if present). The user vimrc is sourced next. Then comes everything invoked by the user vimrc, including by statements such as the `:source` and `:runtime` statements but also by `:filetype [plugin] [indent] on`, `:colorscheme {name}`, etc. Global plugins are sourced after the vimrc, but (if starting in GUI mode) before the gvimrc. Filetype plugins, syntax scripts, and indent scripts, are sourced (if enabled) when opening a file of the corresponding filetype; for instance those for the "help" filetype are sourced the first time you use the `:help` command. Et cetera.

To see which scripts have been sourced in what sequence in the current editing session, use the `:scriptnames` command. That command, however, doesn't repeat entries for scripts which have been sourced several times: such scripts are listed only at the point where they were first sourced in the present session.

Best regards,
Tony.
