### ISSUE TITLE
execute() resets cmdline column to 0

### ISSUE THREAD

**Issue by liushapku** [vim/vim#3669]
This follows a discussion in neovim issue [6035](https://github.com/neovim/neovim/issues/6035). There they found `neovim` does not reset the column after calling `execute()`. For vim, it always reset the column to 0, so that `echon` will continue after the new line character. 

For example

    function! Test1a()
      echo 12345678
      let x = execute('echo 1234567890')
      echon '1234'
    endfunction

will show

    12345678
    1234

instead of 

    123456781234

A [patch](https://github.com/liushapku/vim/commit/970d0c638b25a3f005243d03622bea35451dd7ae) has been created to address this issue. (Do I create an PR directly?)

Moreover a test script can be found [here](https://gist.github.com/liushapku/109d32188464c2c8ae1a8c4bc43a97f8). Each `call Testxa()` should generate exactly the same result as `call Testxb()` where `x=1,2,3,4`.

**Comment by tonymec** [comment]
With the following commands:
```vim
:exe 'echon 1234' | exe 'echon 5678'
```
I see `12345678` below the command-line. So I don't think that the `:execute` command adds a linefeed. But IIUC `:echo` does.

Best regards,
Tony.

**Comment by tonymec** [comment]
oops, I confused `:execute` and `execute()`

**Comment by chrisbra** [comment]
sure please go ahead and create a PR. Please also come up with a test, so that this behaviour won't regress.

**Comment by liushapku** [comment]
@chrisbra I don't know how to create test to check UI behavior

**Comment by chrisbra** [comment]
You can run vim recursively in a terminal and verify the behavior using the screendump feature. Have a look at the `VerifyScreenDump()` calls inside the src/testdir/*.vim testsuite, e.g. `Test_folds_with_rnu()` looks like a straight to follow test. (there are several other examples, like the new diff feature, the incsearch feature, etc).

**Comment by liushapku** [comment]
Actually you also need to teach me how to set up the testing environment. Never get the experience to do vim test. Thank you.

**Comment by chrisbra** [comment]
it is not that hard. Have a look at src/testdir/README.txt.

Basically run vim without customizations and add a new function called `Test_...()`

You might need to source view_util.vim and screendump.vim, have a look at the test_fold.vim. That is all. Then do you test (you can use the function provided in your issue and just add a `call VerifyScreenDump()`.  You might want to add the test to e.g. `test_eval_stuff.vim`. Then simply run `make test_eval_stuff.res` and check the output in messages. Once the test works, run `make` and verify that the test runs successfully. Once that is done, disable your change in the source code and run `make` again in the testdir to make sure the test now fails.
