### ISSUE TITLE
nvo-mode mappings are applied inconsistently with macros

### ISSUE THREAD

**Issue by Lodifice** [vim/vim#3678]
Assume that I create a mapping with `:map foo bar`, which should only be active in normal, visual, and operator-pending mode. The second thing needed is any line of text to put the cursor on.

Now I record a macro `ctdfoo<esc>`, where `d` occurs after the cursor. As expected, all text up to `d` is replaced by `foo`.

However, if I execute the macro again, the text is instead replaced by `bar`, which is clearly not expected.

So I assume that there is a bug in macro execution such that when `foo` is entered, the macro executor still thinks to be in operator-pending mode rather than in insert mode. If a macro not involving operators, e.g. `ifoo<esc>`, is used, then the bug does not occur.

**Comment by chrisbra** [comment]
I started vim --clean, did `:map foo bar`, entered some text with a d inside it, put the cursor at the start of the line, recorded a macro `qactdfoo<esc>q`, pressed undo, executed `@a` and the result was `food`.

So what exactly did you do?

**Comment by Lodifice** [comment]
The same, except that the result is `bard`. What version of Vim do you use? I have tested it with the 8.1 Arch Linux version and the git master.

**Comment by k-takata** [comment]
When I tried this on Win32 the result was `food`, however when I tried on Cygwin or Ubuntu the result was `bard`.

**Comment by Lodifice** [comment]
So it only affects Unix versions. As I'm using nothing else but Linux, this is the only situation I've tested.

**Comment by chrisbra** [comment]
Hm, I thought I tested it on my linux vm. But apparently, I only tried it on Windows.

**Comment by lacygoill** [comment]
This issue looks similar to #3021.

Here, during the recording, when the user types `foo`, they're in insert mode; but when the register is executed, and Vim types `foo`, it's still in operator-pending mode.

There, during the recording, when the user types `yy`, they're in normal mode; but when the register is executed, and Vim types `yy`, it's still in visual mode.

---

One (unpractical?) workaround is to insert a no-op during the recording right after the operator has been executed:

    vim -Nu NONE +'ono foo bar' +'let @q = "ctd\<c-r>=\"\"\<cr>foo\<esc>"' +"pu!='abcd'"
                                               ^^^^^^^^^^^^^^^^
                                               C-r = "" (no-op)

Maybe Vim could do something similar automatically during a recording, just like it does after an `Escape` since [8.1.1003](https://github.com/vim/vim/releases/tag/v8.1.1003).

**Comment by Lodifice** [comment]
Thanks for the notification.

I've read through the other issue and, since both are so similar and here the behavior differs between Windows and Unix-like version, I assume it does in the case of the other issue as well. If so, I would definitely consider it as a bug. At this point, it is still not clear what the correct behavior should be, but I'd make a strong point that a macro in execution should behave in the same way as when it was recorded.

**Comment by chrisbra** [comment]
hm, @zeertzjq ?

**Comment by zeertzjq** [comment]
Isn't that the same as the `:normal` case mentioned in #6350? The two lines are the same, so recording and replying behave the same here.

**Comment by chrisbra** [comment]
okay, let me close it then.
