### ISSUE TITLE
ActiveTcl blocks two-platform builds

### ISSUE THREAD

**Issue by dertuxmalwieder** [vim/vim#3680]
As this was mostly ignored on the mailing list, I open a ticket now. ;-)

For my [Vim builds](https://tuxproject.de/projects/vim/), I usually try to build both x86 and AMD64 builds with the Microsoft compiler. I made the experience that I can *almost* do that without having two versions of each supported scripting language installed. In fact, only ActiveTcl won't let me - I can't build Vim x86 with the 64-bit version of ActiveTcl:

> if_tcl.obj : error LNK2001: Nicht aufgelöstes externes Symbol "_Tcl_InitStubs".
> if_tcl.obj : error LNK2001: Nicht aufgelöstes externes Symbol "_tclStubsPtr".

This was "fine" when ActiveTcl 8.6.6 was the newest version. Now I wanted to update ActiveTcl to 8.6.8, but there is no x86 version yet and it is unclear whether there will be one. Sadly, I cannot install both ActiveTcl 8.6.6 x86 and ActiveTcl 8.6.8 AMD64 on the same machine either, the installer complains about "incompatible versions" when I try. I'm basically stuck with an older ActiveTcl version for the time being.

So I would like to suggest that Vim x86 can finally be built with ActiveTcl x64 as well, so I can stop worrying about the extra overhead and weird incompatibilities. Thank you.

**Comment by k-takata** [comment]
> I can't build Vim x86 with the 64-bit version of ActiveTcl:

It's impossible. You must use x86 version of Tcl to build x86 version of Vim.

> but there is no x86 version yet

It seems that ActiveState stopped providing new x86 versions. (It's [same for ActivePerl](https://github.com/vim/vim-win32-installer/issues/60).) So, I think 8.6.6 will be the last version for x86.
I haven't tried yet, but [IronTcl](https://www.irontcl.com/) might be an alternative.

**Comment by dertuxmalwieder** [comment]
Strawberry Perl works fine, but I am not sure about the various Tcl builds. The Makefile suggests that ActiveTcl is my best option.

*IronTcl* only has 8.6.7 so far, but I might try the compatibility tomorrow. Thank you...

**Comment by dertuxmalwieder** [comment]
Thank you, IronTcl works. *Maybe* the README should be fixed?

**Comment by chrisbra** [comment]
which README? How about a patch?

**Comment by dertuxmalwieder** [comment]
Basically, `INSTALLpc.txt` which still refers to ActiveTcl. I'm not sure whether Bram (or you ;-)) prefer to keep it for the time being.

**Comment by chrisbra** [comment]
So would that be correct:

```patch
diff --git a/src/INSTALLpc.txt b/src/INSTALLpc.txt
index d170da05d..6956b444c 100644
--- a/src/INSTALLpc.txt
+++ b/src/INSTALLpc.txt
@@ -849,7 +849,14 @@ You can use binaries from ActiveState (ActiveTcl).

     http://www.activestate.com/activetcl

-For MSVC 2015 use version 8.6.6 or later.
+Alternatively, you can use the binaries provided by IronTcl from
+
+    https://www.irontcl.com/
+
+They might lack behind the latest version a bit, but should provide 64bit
+and 32bit versions even if ActiveTcl does not provide them anymore.
+
+For building with MSVC 2015 use version 8.6.6 or later.
 When building, you need to set the following variables:

     TCL:          Where tcl is installed. E.g. C:\Tcl86
```

**Comment by dertuxmalwieder** [comment]
Yes, it would. Additional bonus: IronTcl is portable. No more installation conflicts.

**Comment by chrisbra** [comment]
thanks, I suppose @brammool will pick it up from here ;)

**Comment by brammool** [comment]
Included
