### ISSUE TITLE
/_CTRL-L fails for some Unicode characters

### ISSUE THREAD

**Issue by sedm0784** [vim/vim#3682]
Tested in v8.0.1420

Steps to reproduce:

1. Start vim with `vim --clean`
2. Enter the text:

       minč’der̊ hi

   (I just paste it in.)
3. Type:

       gg/min<C-L><C-L><C-L><C-L><C-L>

Expected results: the command line should be populated with the text `minč’der̊` and the first word in the file should be highlighted.

Observed results: the command line is populated with the text `minč’der`.

My complete stab-in-the-dark is that the `r̊` is composed of an ascii `r` followed by a combining character and that Vim is only grabbing the first of these when you press CTRL-L.

**Comment by chrisbra** [comment]
Can you post the `ga` on the last `r` character?

**Comment by sedm0784** [comment]
<r>  114,  Hex 72,  Octal 162 < ̊> 778, Hex 030a, Octal 1412

**Comment by chrisbra** [comment]
yeah, looks like a combining char

**Comment by chrisbra** [comment]
I think this patch: https://github.com/chrisbra/vim/commit/acf029a884d9982bcd558504022223bdcf58f454
fixes it

**Comment by tonymec** [comment]
U+030A COMBINING RING ABOVE

as to change a to something looking like å but with two successive codepoints instead of one precomposed character.

Best regards,
Tony.

**Comment by brammool** [comment]
Christian wrote:

> I think this patch: https://github.com/chrisbra/vim/commit/acf029a884d9982bcd558504022223bdcf58f454
> fixes it

Thanks!

-- 
For society, it's probably a good thing that engineers value function over
appearance.  For example, you wouldn't want engineers to build nuclear power
plants that only _look_ like they would keep all the radiation inside.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
