### ISSUE TITLE
run code on finish

### ISSUE THREAD

**Issue by dhduvall** [vim/vim#3684]
In working on fatih/vim-go#2090, I realized I really wanted a way to say "run this code when we stop sourcing this script" a la shell's `trap EXIT`, or Go's `defer`. I can imagine this problem lurks in a bunch of places, especially now that everyone's getting religion about setting and restoring `&cpo`.

**Comment by tonymec** [comment]
One possibility would be enclosing the rest of the script code in a `:try` block, with the "when stop sourcing" part in the `:finally` just before the `:endtry` at the end of the script.

This means of course running in a Vim supporting the `:try` command, which was new in Vim 6.2 and (I think) needs a Vim compiled with `+eval` (which usually means a Normal, Big or Huge build).

There may be more elegant solutions which don't jump into my mind at the moment.

Best regards,
Tony.

**Comment by lacygoill** [comment]
Possibly fixed by https://github.com/vim/vim/commit/2b6185287adf53343ed5f49e967ae402c64063e4 which provides `SourcePost`:

    au SourcePost <buffer> echom 'after script has been sourced'

**Comment by andymass** [comment]
@lacygoill what about

    execute 'au SourcePost' fnameescape(expand('<sfile>')) " ++once echom 'after script has been sourced'"

**Comment by dhduvall** [comment]
Probably with `++once`, too?

**Comment by lacygoill** [comment]
Yes, probably with `++once`.  See [the command given by @andymass](https://github.com/vim/vim/issues/3684#issuecomment-648515664):

    execute 'au SourcePost' fnameescape(expand('<sfile>')) " ++once echom 'after script has been sourced'"
                                                             ^----^

**Comment by dhduvall** [comment]
Ah, whoops; I misunderstood, thinking the first double-quote was the start of a comment. Thanks for pointing that out.
