### ISSUE TITLE
Job exit handler and timer callbacks not called with popup menu and closed stdin

### ISSUE THREAD

**Issue by blueyed** [vim/vim#3696]
Given
```vim
function Exit(...)
  q!
endfunction
let job = job_start(['true'], {'exit_cb': function('Exit')})
echom string(job)

" Trigger popup menu.
call append(0, ['word1', 'word2'])
call feedkeys("oword\<C-p>", 'x!')
```

Running `vim -u t-vim-job-with-pum.vim >/dev/null` shows:
```
Vim: Warning: Output is not to a terminal                                                                                                                                                                            process 24353 runScanning tags.match 1 of 2
```

But `vim -u t-vim-job-with-pum.vim >/dev/null <&-` hangs:
```
Vim: Warning: Output is not to a terminal
Vim: Warning: Input is not from a terminal
process 24441 run
```

This is also the case with `</dev/null` (although I've noticed this with tests where it would only happen with `<&-`, but not `</dev/null`).

In a similar way timer callbacks appear to not being triggered at all.
Wrapping the above example:
```
function Run(...)
  q!
endfunction

call timer_start(10, function('Run'))

" Trigger popup menu.
call append(0, ['word1', 'word2'])
call feedkeys("oword\<C-p>", 'x!')
```

`vim -u t-vim-timer-with-pum.vim -N <&-` hangs (same with `</dev/null`).

**Comment by brammool** [comment]
Daniel Hahler wrote:

> Given
> ```vim
> function Exit(...)
>   q!
> endfunction
> let job = job_start(['true'], {'exit_cb': function('Exit')})
> echom string(job)
> 
> " Trigger popup menu.
> call append(0, ['word1', 'word2'])
> call feedkeys("oword\<C-p>", 'x!')
> ```
> 
> Running `vim -u t-vim-job-with-pum.vim >/dev/null` shows:
> ```
> Vim: Warning: Output is not to a terminal                                                                                                                                                                            process 24353 runScanning tags.match 1 of 2
> ```
> 
> But `vim -u t-vim-job-with-pum.vim >/dev/null <&-` hangs:
> ```
> Vim: Warning: Output is not to a terminal
> Vim: Warning: Input is not from a terminal
> process 24441 run
> ```
> 
> This is also the case with `</dev/null` (although I've noticed this with tests where it would only happen with `<&-`, but not `</dev/null`).
> 
> In a similar way timer callbacks appear to not being triggered at all.
> Wrapping the above example:
> ```
> function Run(...)
>   q!
> endfunction
> 
> call timer_start(10, function('Run'))
> 
> " Trigger popup menu.
> call append(0, ['word1', 'word2'])
> call feedkeys("oword\<C-p>", 'x!')
> ```
> 
> `vim -u t-vim-timer-with-pum.vim -N <&-` hangs (same with `</dev/null`).

I would say this is expected.  Using feedkeys() with "x!" means it gets
stuck.  This argument is really only meant to be used in tests.
Not sure what you were trying to do, but you'll need to find another
way.

-- 
Anyone who is capable of getting themselves made President should on no
account be allowed to do the job.
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by blueyed** [comment]
> This argument is really only meant to be used in tests.

I am using it in tests.. :)

It works ok for me when using `</dev/null`, but noticed that it fails with `<&-` and tried to reproduce it (this issue).
However, since `<&-` also has other side effects, I am staying with the former approach.

Closing as per your comment.
