### ISSUE TITLE
DirChanged is triggered also for unchanged cwd

### ISSUE THREAD

**Issue by blueyed** [vim/vim#3697]
`:exe 'cd '.getcwd()` triggers `DirChanged`, although the dir has not changed.

I think it should also be triggered on changes.

This would fix e.g. https://github.com/tpope/vim-fugitive/issues/1132, and make https://github.com/mhinz/vim-startify/pull/347 unnecessary.

**Comment by brammool** [comment]
Daniel Hahler wrote:

> `:exe 'cd '.getcwd()` triggers `DirChanged`, although the dir has not changed.
> 
> I think it should also be triggered on changes.
> 
> This would fix e.g. https://github.com/tpope/vim-fugitive/issues/1132,
> and make https://github.com/mhinz/vim-startify/pull/347 unnecessary.

The docs say that the event is triggered when the directory changes,
thus it should be OK to skip it when the directory did not change.
I'll make a patch, let's see if that causes any trouble.

-- 
Q: What is the difference between open-source and commercial software?
A: If you have a problem with commercial software you can call a phone
   number and they will tell you it might be solved in a future version.
   For open-source software there isn't a phone number to call, but you
   get the solution within a day.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by andymass** [comment]
`exe 'cd '.getcwd()` is not a no-op because `getcwd()` returns the window's local directory, but `cd` operates globally.  So, I think the autocmd should be triggered.

**Comment by blueyed** [comment]
@andymass 
It is a no-op if nothing changes.

`exe 'lcd '.getcwd()` would be a no-op in that sense (if there is no window-local dir already).
But the actual change is about what `getcwd()` would return, and that does not change in both cases.

The use case in vim-startify for example is to re-build the list of most recently used files etc, and that depends just on the current dir (regardless of if it is window-local or not).

**Comment by jamessan** [comment]
> `exe 'lcd '.getcwd()` would be a no-op in that sense (if there is no window-local dir already).

The `DirChanged` even lets you match on the scope of the change, too.  Making a window have a local directory or reverting it to the global directory is something that should cause an event, even if the directory itself doesn't change.

**Comment by blueyed** [comment]
Good point.
Maybe the scope should be taken into account if specified in the autocommand then, i.e. if `lcd` is matched it should cause an event if the window-local option is changed / set initially.

**Comment by brammool** [comment]
James McCoy wrote:

> > `exe 'lcd '.getcwd()` would be a no-op in that sense (if there is no
> > window-local dir already).
> 
> The `DirChanged` even lets you match on the scope of the change, too.
> Making a window have a local directory or reverting it to the global
> directory is something that should cause an event, even if the
> directory itself doesn't change.

The idea of the DirChanged event is that the current directory changed.
It's not about some directory stored somewhere (the global or
window-local directory) which may be used later.

I can't think of a practical reason to trigger an event, DirChanged or
other, when the global directory is changed to the current directory.
Any example when it would be useful to trigger an event even though the
current directory didn't actually change?

-- 
Now it is such a bizarrely improbable coincidence that anything as
mind-bogglingly useful as the Babel fish could have evolved purely by chance
that some thinkers have chosen to see it as a final and clinching proof of the
NON-existence of God.
The argument goes something like this: 'I refuse to prove that I exist,' says
God, 'for proof denies faith, and without faith I am nothing.'
'But,' says Man, 'the Babel fish is a dead giveaway, isn't it?  It could not
have evolved by chance.  It proves you exist, and so therefore, by your own
arguments, you don't.  QED.'
'Oh dear,' says God, 'I hadn't thought of that,' and promptly vanishes in a
puff of logic.
'Oh, that was easy,' says Man, and for an encore goes on to prove that black
is white and gets himself killed on the next pedestrian crossing.
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
