### ISSUE TITLE
Possible NPD error 

### ISSUE THREAD

**Issue by 5hadowblad3** [vim/vim#3711]
Hi, recently I use fuzzing to check the vim and I find an NPD problem.
In **src/libvterm/src/termscreen.c**
<img width="681" alt="image" src="https://user-images.githubusercontent.com/7632714/50393633-728d6700-0792-11e9-8e38-9a10b38c7f0f.png">
This could return a null pointer for the caller function **vterm_obtain_screen** and store in the vt->screen.
<img width="706" alt="image" src="https://user-images.githubusercontent.com/7632714/50393673-bed8a700-0792-11e9-8acd-0a3e552f88e6.png">
This null screen is return to **create_vterm** function in **src/terminal.c**
<img width="889" alt="image" src="https://user-images.githubusercontent.com/7632714/50393689-d6179480-0792-11e9-9888-cc251e0089d5.png">
then again in **vterm_screen_set_callbacks** function defined in **src/libvterm/src/termscreen.c**
<img width="881" alt="image" src="https://user-images.githubusercontent.com/7632714/50393768-65bd4300-0793-11e9-8bed-389cab888d7c.png">
The callback function is set to a null pointer screen.
The potential problem is that you can set a callback function to a predefined NULL memory address which might lead to more problem.

I wonder this is a true problem in vim or not, could you help to verify it?

I am looking forward to your reply!

**Comment by chrisbra** [comment]
As this comes from libvterm, cc @leonerd

**Comment by brammool** [comment]
The check for vterm_obtain_state() to return null is bogus, that function never returns null.

**Comment by 5hadowblad3** [comment]
Is it possible that when memory resource is limited then the return value is NULL?

**Comment by 5hadowblad3** [comment]
![image](https://user-images.githubusercontent.com/7632714/50398588-ab8a0380-07b3-11e9-8105-e9826a4a1650.png)
Because it relies on the memory allocation return value.

**Comment by brammool** [comment]
> Is it possible that when memory resource is limited then the return value is NULL?

No, then it will crash.  It could be useful to check for that and return
NULL then.


-- 
hundred-and-one symptoms of being an internet addict:
39. You move into a new house and decide to Netscape before you landscape.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
I suppose this is fixed by cd929f7ba8cc5b6d6dcf35c8b34124e969fed6b8?

**Comment by brammool** [comment]
Yes, now vterm_obtain_state() can return NULL.
It no longer crashes in out-of-memory situations.
Since the state is created when creating the vterm, this should work OK for Vim.
Not in general for libvterm though.
