### ISSUE TITLE
Two Possible Memory Error

### ISSUE THREAD

**Issue by 5hadowblad3** [vim/vim#3716]
Hi, I find two possible errors with my fuzzer.
a) In src/regexp.c a null pointer can be returned for backward searching and some unexpected memory can be read
1,
<img width="668" alt="image" src="https://user-images.githubusercontent.com/7632714/50410262-b89a0780-0832-11e9-9986-656128fa2415.png">
Search result return null.
2,
<img width="887" alt="image" src="https://user-images.githubusercontent.com/7632714/50410331-3b22c700-0833-11e9-9005-8f64c7308eb0.png">
This null result is transfer for saving.
3,
In src/misc2.c. Some bytes of memory is load from a NULL pointer and saved.
<img width="365" alt="image" src="https://user-images.githubusercontent.com/7632714/50410358-60173a00-0833-11e9-8042-2454657c7c68.png">

b) In src/libvterm/src/termscreen.c, a null pointer is used when getcell return null.
1，
<img width="635" alt="image" src="https://user-images.githubusercontent.com/7632714/50410437-f6e3f680-0833-11e9-9213-9a8a68a6bd6d.png">
2， 
<img width="603" alt="image" src="https://user-images.githubusercontent.com/7632714/50410467-19760f80-0834-11e9-9f18-afefac277ee1.png">

Could you please verify it?

I am looking forward to your reply.

**Comment by dpelle** [comment]
If this is discovered by a fuzzer, then I assume you have the input that triggers the bug.
If so, can you attach it to the ticket?

To me, it looks more like warnings from a static analyzer than a runtime bug found by a fuzzer
but I could be wrong.  Static analyzer can have false positive, whereas if it's found
with a fuzzer, then it should be reproducible and it should be a real bug.

**Comment by 5hadowblad3** [comment]
> If this is discovered by a fuzzer, then I assume you have the input that triggers the bug.
> If so, can you attach it to the ticket?
> 
> To me, it looks more like warnings from a static analyzer than a runtime bug found by a fuzzer
> but I could be wrong. static analyzer can have false positive, whereas if it's found
> with a fuzzer, then it should be reproducible and it should be a real bug.


Sure,  
However, because of these problems related to the memory problem, the actual crashes triggered cannot be reproduced in memory available environment.
Therefore, I reuse a static analysis to help me relocate this bug. 

I would like to hear the reply from you. Thanks！

[crash.tar.zip](https://github.com/vim/vim/files/2716284/crash.tar.zip)

**Comment by brammool** [comment]
I cannot see an actual problem here.
In libvterm getcell() is often used without checking for a NULL return value, most likely because the parameters were already checked.
I am going to close this, since it's not a useful report as it is.
If you can reproduce the problem with step-by-step instructions, please reopen.
