### ISSUE TITLE
Why is there no system clipboard??(ubuntu 16.04)

### ISSUE THREAD

**Issue by suannilian** [vim/vim#3719]
:reg
--- 寄存器 ---
""   #!/bin/bash^JWORK_DIR=$( pwd )^Jsh $WORK_DIR/stop.sh^Jecho -e "Starting monitor \n"^Julimit -s 64000^Jcd "${WORK_DIR}/src"^Jnohup python3 monitor_main.py &^Jecho $! > $WORK_DIR/mo
"0   #!/bin/bash^JWORK_DIR=$( pwd )^Jsh $WORK_DIR/stop.sh^Jecho -e "Starting monitor \n"^Julimit -s 64000^Jcd "${WORK_DIR}/src"^Jnohup python3 monitor_main.py &^Jecho $! > $WORK_DIR/mo
"1   !/bin/bash^JWORK_DIR=$( pwd )^Jsh $WORK_DIR/stop.sh^Jecho -e "Starting monitor \n"^Jelimit -s 64000^Jddohup python3 monitor_main.py &^Jec
"2   et clipboard^=unnamed,unnamedplusd "${WORK_DIR}/src"^J
"3   #!/bin/bash^J
"4   source ~/.bashrc^J
"5   alias cleos="cleos -u http://127.0.0.1:8889/"^J
"6   source ~/.bashrc^J
"7   alias gleos="cleos -u http://127.0.0.1:8889/"^J
"8   source /etc/profile^J
"9   #plugin = eosio::wallet_plugin^J
"-   f
"%   123
"/   usr

 vim-scripts vim-gtk vim-gnome  has already installed，

ll /usr/bin/vim*
lrwxrwxrwx 1 root root      21 12月 26 00:49 /usr/bin/vim -> /etc/alternatives/vim*
lrwxrwxrwx 1 root root      21 5月  24  2018 /usr/bin/vim_bak -> /etc/alternatives/vim*
-rwxr-xr-x 1 root root 2437320 11月 25  2016 /usr/bin/vim.basic*
lrwxrwxrwx 1 root root      25 12月 26 00:49 /usr/bin/vimdiff -> /etc/alternatives/vimdiff*
-rwxr-xr-x 1 root root    1051 1月   6  2017 /usr/bin/vimdot*
-rwxr-xr-x 1 root root 2932160 11月 25  2016 /usr/bin/vim.gnome*
-rwxr-xr-x 1 root root 2923968 11月 25  2016 /usr/bin/vim.gtk*
-rwxr-xr-x 1 root root    7940 8月  19  2013 /usr/bin/vimplate*
-rwxr-xr-x 1 root root    2084 11月 25  2016 /usr/bin/vimtutor*

vim --version |grep clipboard
+clipboard       +insert_expand   +path_extra      +user_commands
+emacs_tags      +mouseshape      +startuptime     +xterm_clipboard

why :reg no  no system + or * clipboard

**Comment by nuko8** [comment]
That happens when both PRIMARY selection for "* clipboard" and CLIPBOARD selection for "+ clipboard" have no data to pass from other applications to Vim and vice versa.

**Comment by suannilian** [comment]
but i select content and "+y ,There's still no system paste board, so i can't copy things to external programs

**Comment by nuko8** [comment]
What do you mean by "no system paste board"?  If that means that neither X nor Wayland server is running on your system simultaneously with Vim, then there's no "system paste board" because Vim's copy/paste operation is done through the X11 selection mechanism. If that is the case, then you won't copy or paste anything from one application to another one.  In contrast, if the X server is actually running, then there should be the "system paste board" on your system. Some clarification on whether the X server is running or not is needed.

**Comment by suannilian** [comment]
Ubuntu requires something to install in order to use it, which I use over the xteam terminal connection？？thank！！！

**Comment by nuko8** [comment]
Hmm, seems like you actually want to say "over ssh connection" instead of "over the xterm terminal connection."  Then, [this](https://superuser.com/questions/326871/using-clipboard-through-ssh-in-vim) could help you.

**Comment by suannilian** [comment]
1. ssh -Y eos2@223.223.XX
2. xsel -o -b
xsel: Can't open display: (null)
: Success
3.It works the same way, but it still doesn't work，why？thanks

**Comment by suannilian** [comment]
~$ vim --version |grep X11
+diff            +menu            +ruby            +X11

**Comment by nuko8** [comment]
The Q&A I showed you with the link is followed up with two comments in small Latin characters.  Among them, the second comment seems to have an important info for you:

> `sudo apt-get install xauth` did the trick. – jaz Aug 23 '11 at 14:23

**Comment by chrisbra** [comment]
The question seems to be specific about how to use the clipboard remotely. 
Please ask user questions on vi.stackexchange.com or the vim-use mailinglist. We cannot provide individual support here. Closing.
