### ISSUE TITLE
Question: how to jump forward , my shorcut  <C-i>  was covered by a plugin which I don't know,how should I do?

### ISSUE THREAD

**Issue by sshsu** [vim/vim#3723]
Question: how to jump forward , my shorcut  <C-i>  was covered by a plugin which I don't know, how should I do?

**Comment by chrisbra** [comment]
Please ask user questions on vi.stackexchange.com or use the vim-use mailinglist. This one here is for actual bug reports. We cannot provide individual support here.
Oh and please state clearly what you did, what you expect and what happened. Your question is a bit brief on that.

**Comment by tonymec** [comment]
> Question: how to jump forward , my shorcut was covered by a plugin which I don't know, how should I do?

Try `:noremap <F12> <C-I>` (using anything else not already used if F12 is already in use). This should let you use F12 (or whatever) for the *original* function of Ctrl-I.

Best regards,
Tony.
