### ISSUE TITLE
GVim 8.1 netrw Windows Drive root folder inaccessible

### ISSUE THREAD

**Issue by elig0n** [vim/vim#3726]
Subfolders in any drive works fine.
Applying #1086 solved this.

I checked an older, vim73 installation I have on the same machine and although it doesn't have the relevant lines from the above patched in `netrw.vim`, I can still use it to get to a drive's root folder.

**Comment by skywind3000** [comment]
try dirvish instead.

**Comment by k-takata** [comment]
It looks that this has been already fixed. Closing.
