### ISSUE TITLE
vimdiff no longer triggers FilterWritePost

### ISSUE THREAD

**Issue by systemmonkey42** [vim/vim#3727]
I've been using FilterWritePost autocommand hook to configure Diff behaviour after loading.

FilterWritePost is documented as triggering after diff has created its DIFF.

I noticed it wasn't working in the latest build.  The autocommand is never triggered.   After a little digging it appears the commit

```
 c93262b2e -- patch 8.1.0363: internal diff isn't used by default as advertised
```

disables this behaviour.  This means the documentation and behavior no longer match.

Is there a better way to run commands in each Diff window without using FilterWritePost?

Thanks

**Comment by systemmonkey42** [comment]
As an aside, if I clear the doffopt 'internal' flag, (which is the new default since 8.1.0363) these triggers work as documented.

**Comment by mattn** [comment]
FYI, you can use OptionSet instead.
```vim
autocmd OptionSet diff if v:option_old == 0 && v:option_new != 0 | echo "diff!" | endif
```

**Comment by systemmonkey42** [comment]
I like the OptionSet autocommand, but it doesn't get triggered when launching VIM as vimdiff....

For now I have `autocmd OptionSet diff call diff#setup()` for normal use and 

```vim
if &diff
   autocmd VimEnter * bufdo if &diff | call diff#setup() | endif
endif
```

to configure each buffer in `vimdiff` mode. (The diff#setup() function does buffer local setup only)

It all seemed cleaned with `au FilterReadPost * if &diff | diff#setup() | endif` because that always worked.

Its also slightly more complex because I can't upgrade all vim instances I work with, so my vimrc must support a range of versions.

Thanks

**Comment by chrisbra** [comment]
You can use the DiffUpdated event that has been introduced as of v8.1.0397
