### ISSUE TITLE
Wrong type

### ISSUE THREAD

**Issue by joaothallis** [vim/vim#3735]
https://github.com/vim/vim/blob/ef0a1d5ed3566b91143d30ae9de3240f47c6e282/runtime/tutor/tutor#L557

Fix to: `** Type :s/old/new/g to substitute 'old' for 'new'. **`

**Comment by tonymec** [comment]
There is no error. «Substitute "new" for "old"» is another way to say «replace "old" by "new"». The "for" in the sentence means something like "instead of". I'm not sure how to say it in Portuguese. *Sostituar 'nova' para 'velha'* maybe?

Best regards,
Tony.

**Comment by joaothallis** [comment]
Thanks @tonymec by the explanation
