### ISSUE TITLE
configure --enable-gui=gtk3 disables GUI if gtk3 test program fails (instead of terminating with an error)

### ISSUE THREAD

**Issue by Rhialto** [vim/vim#3737]
If you run the configure script with `--enable-gui=gtk3` to enable the GTK 3 GUI, then it tries a compile of a little test program to see if gtk3 seems to be present and working.
However, if the test program fails, `configure` continues but without a GUI.checking --enable-gui argument... GTK+ 3.x GUI support
```
checking --disable-gtktest argument... gtk test enabled
checking for GTK - version >= 3.0.0... no
checking X11/SM/SMlib.h usability... yes
checking X11/SM/SMlib.h presence... yes
...
gcc  -L/usr/X11R7/lib -R/usr/X11R7/lib -L/usr/pkg/lib -L/usr/lib -Wl,-R/usr/lib -L/usr/X11R7/lib -Wl,-R/usr/X11R7/lib -Wl,-R/usr/pkg/lib -Wl,--as-needed  -o vim objects/arabic.o  objects/beval.o  objects/buffer.o  objects/blowfish.o  objects/crypt.o  objects/crypt_zip.o  objects/dict.o  objects/diff.o  objects/digraph.o  objects/edit.o  objects/eval.o  objects/evalfunc.o  objects/ex_cmds.o  objects/ex_cmds2.o  objects/ex_docmd.o  objects/ex_eval.o  objects/ex_getln.o  objects/farsi.o  objects/fileio.o  objects/fold.o  objects/getchar.o  objects/hardcopy.o  objects/hashtab.o    objects/if_cscope.o  objects/if_xcmdsrv.o  objects/list.o  objects/mark.o  objects/memline.o  objects/menu.o  objects/misc1.o  objects/misc2.o  objects/move.o  objects/mbyte.o  objects/normal.o  objects/ops.o  objects/option.o  objects/os_unix.o  objects/pathdef.o  objects/popupmnu.o  objects/pty.o  objects/quickfix.o  objects/regexp.o  objects/screen.o  objects/search.o  objects/sha256.o  objects/spell.o  objects/spellfile.o  objects/syntax.o  objects/tag.o  objects/term.o  objects/terminal.o  objects/ui.o  objects/undo.o  objects/userfunc.o  objects/version.o  objects/window.o    objects/encoding.o objects/keyboard.o objects/mouse.o objects/parser.o objects/pen.o objects/termscreen.o objects/state.o objects/unicode.o objects/vterm.o                    objects/netbeans.o  objects/channel.o  objects/xdiffi.o  objects/xemit.o  objects/xprepare.o  objects/xutils.o  objects/xhistogram.o  objects/xpatience.o   objects/charset.o  objects/json.o  objects/main.o  objects/memfile.o  objects/message.o       -lSM -lICE -lXpm  -lXt -lX11  -lXdmcp -lSM -lICE    -lm -lelf  -ltermcap -liconv                     
link.sh: Linked fine
...
murthe:.../pkgsrc/editors/vim-gtk3$ /scratch/chroot/pkg_comp.amd64-8.0/default/p/obj/pkgsrc/editors/vim-gtk3/default/vim-8.1.0551/src/vim --version   
VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec 30 2018 20:41:11)
Included patches: 1-551
Compiled by rhialto@murthe.falu.nl
Huge version without GUI.  Features included (+) or not (-):
```
For automated builds, a silent build of something else than asked for is worse than a failing build. In the latter case, it is clear that something needs to be fixed.

(this issue came up when packaging vim for pkgsrc; the cause of the failure was very obscure.)

**Comment by tonymec** [comment]
For plain Unix-like users like me, who compile their own Vim, a "best effort" like configure now does is just what we want. Then if the output of `src/vim --version` shows that we didn't get what we asked for, at least (in most cases) we can use the less-than-ideal Vim just compiled to inspect the logfiles and/or edit the config settings before we try to install the missing package(s) and recompile.

According to `auto/configure --help |less`, there is a command-line switch, `--enable-fail-if-missing`, which seems to do just what you want.

Best regards,
Tony.

**Comment by Rhialto** [comment]
Thanks, that sounds like it should do what I want, but when I tried it, it didn't.
Looking in `configure.ac`, it is only checked for lua, perl, python, python3, tcl and ruby.
I guess its use could be extended a bit.

(sorry for the small layout mishap in my original report. github seems to think my firefox is too old to allow me to preview or edit it)

**Comment by brammool** [comment]
Rhialto wrote:

> Thanks, that sounds like it should do what I want, but when I tried
> it, it didn't.  Looking in `configure.ac`, it is only checked for lua,
> perl, python, python3, tcl and ruby.  I guess its use could be
> extended a bit.
> 
> (sorry for the small layout mishap in my original report. github seems
> to think my firefox is too old to allow me to preview or edit it)

I sent out a patch to make the enable-gui argument also consider
fail-if-missing.  I think that's appropriate.

There are probably a few more arguments or values that should do this,
let me know if you spot one.

-- 
hundred-and-one symptoms of being an internet addict:
90. Instead of calling you to dinner, your spouse sends e-mail.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
