### ISSUE TITLE
packadd autocmd

### ISSUE THREAD

**Issue by timokau** [vim/vim#3739]
I would like to be able to run some code after a plugin was loaded. One example use-case would be call `neomake#configure#automake('nrwi', 500)` which is necessary to configure the neomake plugin. Currently it is hard to do that when neomake is an optional plugin.

I imagine something like this:

```
autocmd PackLoadPre neomake packadd some-dependency
autocmd PackLoadPost neomake call neomake#configure#automake('nrwi', 500)
```

The autocommand should only be triggered on the first `:packadd`. The natural place to call these autocommands seems to be the `add_pack_dir_to_rtp` function:
https://github.com/vim/vim/blob/af0839acec403379627a4bc50cbeca588344cea5/src/ex_cmds2.c#L3684

I previously opened https://github.com/neovim/neovim/issues/9415 for this, where I was redirected here. It was suggested to use `SourcePre`, which should be able to replace most usecases but would more cumbersome to use correctly.

**Comment by brammool** [comment]
> I would like to be able to run some code after a plugin was loaded. One
> example use-case would be call `neomake#configure#automake('nrwi', 500)`
> which is necessary to configure the neomake plugin. Currently it is hard to
> do that when neomake is an optional plugin.
> 
> I imagine something like this:
> 
> ```
> autocmd PackLoadPre neomake packadd some-dependency
> autocmd PackLoadPost neomake call neomake#configure#automake('nrwi', 500)
> ```
> 
> The autocommand should only be triggered on the first `:packadd`. The natural
> place to call these autocommands seems to be the `add_pack_dir_to_rtp`
> function:
> https://github.com/vim/vim/blob/af0839acec403379627a4bc50cbeca588344cea5/src/ex_cmds2.c#L3684
> 
> I previously opened https://github.com/neovim/neovim/issues/9415 for this,
> where I was redirected here. It was suggested to use `SourcePre`, which
> should be able to replace most usecases but would more cumbersome to use
> correctly.

I think what you want is a way to execute code after a plugin has been loaded.
Whether this was done with :packadd or some plugin manager most likely doesn't
matter.

We already have SourcePre, perhaps SourcePost would work?  You can then match
with a certain file name, such as "plugin/automake.vim".

-- 
From "know your smileys":
 :-)	Funny
 |-)	Funny Oriental
 (-:	Funny Australian

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by timokau** [comment]
> I think what you want is a way to execute code after a plugin has been loaded. Whether this was done with :packadd or some plugin manager most likely doesn't matter.

Well in my case I'm using `:packadd`, so having the convenience feature would be nice.

> We already have SourcePre, perhaps SourcePost would work? You can then match with a certain file name, such as "plugin/automake.vim".

That would also work, but not quite as nicely because
- to be reliable, I'd need to know the full path to the plugin
- I either need to know at least one filename per plugin or manually make sure the code only gets executed once. Even then I may get issues because not all plugin files are sourced yet.

**Comment by brammool** [comment]
> > I think what you want is a way to execute code after a plugin has
> > been loaded. Whether this was done with :packadd or some plugin
> > manager most likely doesn't matter.
> 
> Well in my case I'm using `:packadd`, so having the convenience feature would be nice.
> 
> > We already have SourcePre, perhaps SourcePost would work? You can
> > then match with a certain file name, such as "plugin/automake.vim".
> 
> That would also work, but not quite as nicely because
> - to be reliable, I'd need to know the full path to the plugin

Just like SourcePre <afile> will contain the full path.  But the
autocommand will match also part of it.

> - I either need to know at least one filename per plugin or manually
> make sure the code only gets executed once. Even then I may get issues
> because not all plugin files are sourced yet.

You can either set a flag yourself to indicate the work was done, or
trigger on VimEnter, which is when all the plugins loaded on startup are
available.  Then you need some way to know the plugin had loaded.  If
the plugin doesn't provide something for that, you can use the mechanism
mentioned at ":help scriptnames-dictionary".


-- 
From "know your smileys":
 O:-)	Saint

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by timokau** [comment]
On 18-12-31 09:06, Bram Moolenaar wrote:
> > That would also work, but not quite as nicely because
> > - to be reliable, I'd need to know the full path to the plugin
> 
> Just like SourcePre <afile> will contain the full path.  But the
> autocommand will match also part of it.

Yes, but to be reliable it would need to match the full path. But `PackLoadPre`
wouldn't need that because it has `packpath`.

> > - I either need to know at least one filename per plugin or manually
> > make sure the code only gets executed once. Even then I may get issues
> > because not all plugin files are sourced yet.
> 
> You can either set a flag yourself to indicate the work was done

But is there a generic way (e.g. without depending on the exact file layout of
the plugin) to trigger after the whole plugin was loaded?

> or
> trigger on VimEnter, which is when all the plugins loaded on startup are
> available.  Then you need some way to know the plugin had loaded.  If
> the plugin doesn't provide something for that, you can use the mechanism
> mentioned at ":help scriptnames-dictionary".

This is mainly interesting for lazy-loading of plugins. For the ones loaded at
startup I can just call `packloadall` in my vimrc.

**Comment by brammool** [comment]
> On 18-12-31 09:06, Bram Moolenaar wrote:
> > > That would also work, but not quite as nicely because
> > > - to be reliable, I'd need to know the full path to the plugin
> > 
> > Just like SourcePre <afile> will contain the full path.  But the
> > autocommand will match also part of it.
> 
> Yes, but to be reliable it would need to match the full path. But `PackLoadPre`
> wouldn't need that because it has `packpath`.

To be reliable you must NOT match the full path, since you can never
know where the user has put the plugin.  It can be the old style "drop
it in your ~/.vimrc/plugin directory", using :packadd, or any plugin
manager (where the path is quite unpredictable).  Only the last part of
the path "/plugin/{name}.vim" will always be the same.
 
> > > - I either need to know at least one filename per plugin or manually
> > > make sure the code only gets executed once. Even then I may get issues
> > > because not all plugin files are sourced yet.
> > 
> > You can either set a flag yourself to indicate the work was done
> 
> But is there a generic way (e.g. without depending on the exact file layout of
> the plugin) to trigger after the whole plugin was loaded?

No.  It's totally up to the plugin author.  After all, a plugin is just
a Vim script file that's loaded.

> > or
> > trigger on VimEnter, which is when all the plugins loaded on startup are
> > available.  Then you need some way to know the plugin had loaded.  If
> > the plugin doesn't provide something for that, you can use the mechanism
> > mentioned at ":help scriptnames-dictionary".
> 
> This is mainly interesting for lazy-loading of plugins. For the ones loaded at
> startup I can just call `packloadall` in my vimrc.

Well, you wanted to know how to make your code run after any plugins it
depends on are loaded.  If not using VimEnter, you will have to keep
track of what plugins have been loaded and trigger when you have the set
you need.

-- 
Where do you want to crash today?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by timokau** [comment]
On 18-12-31 13:03, Bram Moolenaar wrote:
> 
> > On 18-12-31 09:06, Bram Moolenaar wrote:
> > > > That would also work, but not quite as nicely because
> > > > - to be reliable, I'd need to know the full path to the plugin
> > > 
> > > Just like SourcePre <afile> will contain the full path.  But the
> > > autocommand will match also part of it.
> > 
> > Yes, but to be reliable it would need to match the full path. But `PackLoadPre`
> > wouldn't need that because it has `packpath`.
> 
> To be reliable you must NOT match the full path, since you can never
> know where the user has put the plugin.  It can be the old style "drop
> it in your ~/.vimrc/plugin directory", using :packadd, or any plugin
> manager (where the path is quite unpredictable).  Only the last part of
> the path "/plugin/{name}.vim" will always be the same.

Yes I suppose reliable is not the right word. What I meant was that there may be
false positives if the full path isn't used, although that is admittedly
unlikely.

> > > > - I either need to know at least one filename per plugin or manually
> > > > make sure the code only gets executed once. Even then I may get issues
> > > > because not all plugin files are sourced yet.
> > > 
> > > You can either set a flag yourself to indicate the work was done
> > 
> > But is there a generic way (e.g. without depending on the exact file layout of
> > the plugin) to trigger after the whole plugin was loaded?
> 
> No.  It's totally up to the plugin author.  After all, a plugin is just
> a Vim script file that's loaded.

But this would be easy to do with a `PackLoadPost` autocommand that triggers
after all the plugin files have been sourced.

> > > or
> > > trigger on VimEnter, which is when all the plugins loaded on startup are
> > > available.  Then you need some way to know the plugin had loaded.  If
> > > the plugin doesn't provide something for that, you can use the mechanism
> > > mentioned at ":help scriptnames-dictionary".
> > 
> > This is mainly interesting for lazy-loading of plugins. For the ones loaded at
> > startup I can just call `packloadall` in my vimrc.
> 
> Well, you wanted to know how to make your code run after any plugins it
> depends on are loaded.  If not using VimEnter, you will have to keep
> track of what plugins have been loaded and trigger when you have the set
> you need.

Yes, and that would be the usecase for the proposed autocommand.

**Comment by brammool** [comment]
> > > > > - I either need to know at least one filename per plugin or manually
> > > > > make sure the code only gets executed once. Even then I may get issues
> > > > > because not all plugin files are sourced yet.
> > > > 
> > > > You can either set a flag yourself to indicate the work was done
> > > 
> > > But is there a generic way (e.g. without depending on the exact file layout of
> > > the plugin) to trigger after the whole plugin was loaded?
> > 
> > No.  It's totally up to the plugin author.  After all, a plugin is just
> > a Vim script file that's loaded.
> 
> But this would be easy to do with a `PackLoadPost` autocommand that triggers
> after all the plugin files have been sourced.

"all the plugins" is not a clear state.  Some plugins may only be loaded
when editing a file of a certain type.
I think this will end up being the same as the VimEnter event.

> > > > or
> > > > trigger on VimEnter, which is when all the plugins loaded on startup are
> > > > available.  Then you need some way to know the plugin had loaded.  If
> > > > the plugin doesn't provide something for that, you can use the mechanism
> > > > mentioned at ":help scriptnames-dictionary".
> > > 
> > > This is mainly interesting for lazy-loading of plugins. For the ones loaded at
> > > startup I can just call `packloadall` in my vimrc.
> > 
> > Well, you wanted to know how to make your code run after any plugins it
> > depends on are loaded.  If not using VimEnter, you will have to keep
> > track of what plugins have been loaded and trigger when you have the set
> > you need.
> 
> Yes, and that would be the usecase for the proposed autocommand.

Ehm, the autocommand cannot possibly know what plugins you need, you can
do that only manually.

-- 
From "know your smileys":
 :-&	Eating spaghetti

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by timokau** [comment]
On 19-01-01 10:59, Bram Moolenaar wrote:
> 
> > > > > > - I either need to know at least one filename per plugin or manually
> > > > > > make sure the code only gets executed once. Even then I may get issues
> > > > > > because not all plugin files are sourced yet.
> > > > > 
> > > > > You can either set a flag yourself to indicate the work was done
> > > > 
> > > > But is there a generic way (e.g. without depending on the exact file layout of
> > > > the plugin) to trigger after the whole plugin was loaded?
> > > 
> > > No.  It's totally up to the plugin author.  After all, a plugin is just
> > > a Vim script file that's loaded.
> > 
> > But this would be easy to do with a `PackLoadPost` autocommand that triggers
> > after all the plugin files have been sourced.
> 
> "all the plugins" is not a clear state.  Some plugins may only be loaded
> when editing a file of a certain type.
> I think this will end up being the same as the VimEnter event.

I think we're talking about different issues. I didn't mean an autocommand that
triggers when all the plugins are loaded but one that is triggered when all the
files of one particular plugin is loaded. So

```
au PackLoadPost neomake
au PackLoadPre neomake
```

will trigger before and after the loading of the `neomake` plugin. The
`PackLoadPre` is similar to `SourcePre` only that it deals with whole plugins
instead of individual files. That has the advantages that

- I don't have to worry about the plugin location or false positives
- I don't have to worry about the autocommand being triggered multiple times
  when multiple files are sourced
- I don't have to worry about a plugin being only partially sourced in case of
  `PackLoadPost`

**Comment by brammool** [comment]
> > > > > > > - I either need to know at least one filename per plugin or manually
> > > > > > > make sure the code only gets executed once. Even then I may get issues
> > > > > > > because not all plugin files are sourced yet.
> > > > > > 
> > > > > > You can either set a flag yourself to indicate the work was done
> > > > > 
> > > > > But is there a generic way (e.g. without depending on the exact file layout of
> > > > > the plugin) to trigger after the whole plugin was loaded?
> > > > 
> > > > No.  It's totally up to the plugin author.  After all, a plugin is just
> > > > a Vim script file that's loaded.
> > > 
> > > But this would be easy to do with a `PackLoadPost` autocommand that triggers
> > > after all the plugin files have been sourced.
> > 
> > "all the plugins" is not a clear state.  Some plugins may only be loaded
> > when editing a file of a certain type.
> > I think this will end up being the same as the VimEnter event.
> 
> I think we're talking about different issues. I didn't mean an autocommand that
> triggers when all the plugins are loaded but one that is triggered when all the
> files of one particular plugin is loaded. So
> 
> ```
> au PackLoadPost neomake
> au PackLoadPre neomake
> ```
> 
> will trigger before and after the loading of the `neomake` plugin. The
> `PackLoadPre` is similar to `SourcePre` only that it deals with whole plugins
> instead of individual files. That has the advantages that
> 
> - I don't have to worry about the plugin location or false positives
> - I don't have to worry about the autocommand being triggered multiple times
>   when multiple files are sourced
> - I don't have to worry about a plugin being only partially sourced in case of
>   `PackLoadPost`

But if he plugin is loaded in any other way than :packadd (or loaded
automatically as a package on startup), then nothing will happen.
Since many Vim users are using a package manager that doens't use
:packadd this is a realistic problem.

The plugin/{name}.vim script file is the man file of every plugin.
Whatever else is loaded probably doesn't matter.   And it is very
unlikely it is loaded twice (probably only happens for someone working
on the plugin).  Thus I would think that a SourcePost event covers most
uses cases.

In other words: what you propose will cover only some use cases and will
require something else to make it work for many users.  What I propose
will work fine for nearly everybody, and may require some extra effort
to handle corner cases.

-- 
The primary purpose of the DATA statement is to give names to constants;
instead of referring to pi as 3.141592653589793 at every appearance, the
variable PI can be given that value with a DATA statement and used instead
of the longer form of the constant.  This also simplifies modifying the
program, should the value of pi change.
	-- FORTRAN manual for Xerox Computers

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by timokau** [comment]
> But if he plugin is loaded in any other way than :packadd (or loaded
> automatically as a package on startup), then nothing will happen.
> Since many Vim users are using a package manager that doens't use
> :packadd this is a realistic problem.

I don't see that as a problem. It would be a feature specific to the built in
package manager, which the name should also make clear. Other package managers
could do something similar.

If somebody is using this in their vimrc, they know which plugin manager they're
using.

> The plugin/{name}.vim script file is the man file of every plugin.
> Whatever else is loaded probably doesn't matter.   And it is very
> unlikely it is loaded twice (probably only happens for someone working
> on the plugin).  Thus I would think that a SourcePost event covers most
> uses cases.

So `plugin/{name}.vim` is always guaranteed to exist? But that would probably be
sourced first, not last right?

> In other words: what you propose will cover only some use cases and will
> require something else to make it work for many users.  What I propose
> will work fine for nearly everybody, and may require some extra effort
> to handle corner cases.

I don't think they have to be mutually exclusive. Such corner cases can be very
hard to debug and make the vimrc dependent on implementation details of the
plugins.

**Comment by timokau** [comment]
Another use-case for a `PackLoadPost` autocmd (although in this case `SourcePost` would be just as good): I'm trying to globally ignore spelling in URLs. That is tricky because filetype plugins will usually override the spell rule I create for that. If I lazy-load a filetype plugin (`autocmd BufReadPre,BufNewFile *.md :packadd vim-pandoc`), there is currently no reliable way to inject my spell rule:

```vim
syntax match URL /https\?:\/\/\(\w\+\(:\w\+\)\?@\)\?\([A-Za-z][-_0-9A-Za-z]*\.\)\{1,}\(\w\{2,}\.\?\)\{1,}\(:[0-9]\{1,5}\)\?\S*/ contains=@NoSpell transparent
syntax cluster Spell add=URL
```

*after* the lazy-loaded filetype plugin.

**Comment by timokau** [comment]
Thanks!

I still think `PackLoadPre` and `PackLoadPost` would be useful. `PackLoadPost` in particular, because of the difficulty of determining if the plugin has been fully loaded just based on `SourcePost` events.

Seeing that you closed this in 2b61852, is that a "No" on `PackLoadPost` from you?

**Comment by brammool** [comment]
> I still think `PackLoadPre` and `PackLoadPost` would be useful.
> `PackLoadPost` in particular, because of the difficulty of determining
> if the plugin has been fully loaded just based on `SourcePost` events.
> 
> Seeing that you closed this in 2b61852, is that a "No" on
> `PackLoadPost` from you?

I'm not yet convinced that PackLoadPost is useful.

-- 
An error has occurred.  Hit any user to continue.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by timokau** [comment]
Maybe I am missing something. Suppose I have a plugin that consists of multiple files. One example is [rust.vim](https://github.com/rust-lang/rust.vim/tree/master/plugin). Now according to `:help packadd`, loading that plugin will source all files matching `pack/*/opt/plugin/**/*.vim`.

How do I add a hook to run some configuration once that plugin is fully loaded? I can add a `SorucePost` to the `plugin` directory, but that will execute multiple times and the plugin will not yet be fully loaded the first time.

Of course I could find out which of those files I actually need to have loaded before applying the configuration, but that heavily depends on the plugin and its implementation details. I think a general solution would be valuable.

**Comment by brammool** [comment]
> Maybe I am missing something. Suppose I have a plugin that consists of
> multiple files. One example is
> [rust.vim](https://github.com/rust-lang/rust.vim/tree/master/plugin).
> Now according to `:help packadd`, loading that plugin will source all
> files matching `pack/*/opt/plugin/**/*.vim`.
> 
> How do I add a hook to run some configuration once that plugin is
> fully loaded? I can add a `SorucePost` to the `plugin` directory, but
> that will execute multiple times and the plugin will not yet be fully
> loaded the first time.
> 
> Of course I could find out which of those files I actually need to
> have loaded before applying the configuration, but that heavily
> depends on the plugin and its implementation details. I think a
> general solution would be valuable.

That's actually a good example.  The plugin is not presented as a
package.  Thus some users may just drop it in ~/.vim/plugins, others may
do it as a package themselves.

I see two files: rust.vim and cargo.vim.  They do different things, but
in case you depend on the contents of both, I would think you use an
autocommand like this:

   au SourcePost plugin/cargo.vim,plugin/rust.vim call CheckForRust()

   func CheckForRust()
     if !exists('g:did_the_work') && exists('g:loaded_rust_vim_plugin_cargo') && exists('g:loaded_rust_vim')
       let g:did_the_work = 1
       Do The Work
     endif
   endfunc


-- 
hundred-and-one symptoms of being an internet addict:
175. You send yourself e-mail before you go to bed to remind you
     what to do when you wake up.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by timokau** [comment]
> That's actually a good example.  The plugin is not presented as a
> package.  Thus some users may just drop it in ~/.vim/plugins, others may
> do it as a package themselves.

Yes, the solution would only apply to users using packages. I don't see
why this is an issue. Other package managers providing lazy loading could
either provide a simlar mechanism or even use vim packages as a backend.
If we don't want any additional functionality with vim packages, why
implement it in the first place?

> I see two files: rust.vim and cargo.vim.  They do different things, but
> in case you depend on the contents of both, I would think you use an
> autocommand like this:
> 
>    au SourcePost plugin/cargo.vim,plugin/rust.vim call CheckForRust()
> 
>    func CheckForRust()
>      if !exists('g:did_the_work') && exists('g:loaded_rust_vim_plugin_cargo') && exists('g:loaded_rust_vim')
>        let g:did_the_work = 1
>        Do The Work
>      endif
>    endfunc

Yes I could but that was just one arbitrary example. As I said before,
such a solution heavily depends on the plugin and implementation
details. A `PackLoadPost` solution would be general (over the plugin
taht is used, not general over the plugin manager of course).

It enables me to simply configure my plugins (setting certain variables
*before* they are loaded, calling certain functions *after* they were
loaded) without tailoring a solution to each plugin.

**Comment by andymass** [comment]
It seems like the only use case for a "PackLoadPost" would be when you explicitly and synchronously load a package yourself using `:packadd {name}` during a running vim session.  If this is the case, why not write a wrapper command called `:Packadd` or a command such as `:EnableRust` which can set up all the before/after options?

**Comment by timokau** [comment]
> It seems like the only use case for a "PackLoadPost" would be when you explicitly and synchronously load a package yourself using `:packadd {name}` during a running vim session

It could in theory also be loaded from another plugin.

> If this is the case, why not write a wrapper command called `:Packadd`

That would currently be the best solution, although it wouldn't work in the hypothetical case where a plugin loads another plugin.
Besides that I'm also thinking about making use of this in a [NixOS](https://nixos.org/) module (think of it as a configuration management system) to provide system-level package management. There it would also lead to confusion to have to tell users to use a wrapper.

**Comment by timokau** [comment]
@brammool pinging one time in case it got lost in your inbox. I'll let it rest after that.

Is there currently a way to execute a function after an arbitrary plugin has fully loaded (without relying on aspects of the plugins implementation)?

**Comment by brammool** [comment]
I expect most plugins  have just one main plugin file.  You can use the SourcePost event on that file.  In the rare cases this is not sufficient one needs to add something to handle that, it can't be very difficult.
Note that for Vim a package is no more than sourced scripts in a specific location.  I do care about plugins that are loaded in various ways and prefer a solution that works in all of those cases.

**Comment by timokau** [comment]
> I expect most plugins have just one main plugin file

But "most" is a real problem. It makes `SourcePost` impractical for generalized solutions like packaging and configuration generation.

> prefer a solution that works in all of those cases

I agree. There could be both however.

I understand that you can't incorporate everybody's wishes. Is this something that you won't do yourself but would accept a PR for, or do you not want that at all?

**Comment by andymass** [comment]
@timokau How do you propose that vim would know when a plugin is "fully loaded?"

**Comment by timokau** [comment]
Since vim is handling the loading itself, it can just call the autocommand afterwards:

https://github.com/vim/vim/blob/af0839acec403379627a4bc50cbeca588344cea5/src/ex_cmds2.c#L3684

**Comment by alohaia** [comment]
Are `SourcePre` events really triggered before loading a opt pack through `:packadd`? In my case, they seem to be triggered only when I source a file through `:source` explicitly.

**Comment by brammool** [comment]
Yes, SourcePre events should be triggered.

**Comment by chrisbra** [comment]
can you provide a minimal example?

**Comment by alohaia** [comment]
I supposed that I've found the problem. `:packadd` command does trigger `SourcePre` events UNLESS it's in another auto command.

For instance, run this command:

```vim
au SourcePre ~/.local/share/nvim/site/pack/packer/opt/vim-hexowiki/**/* let g:hexoLoaded = 1
```

When you load a markdown file, the command below will load plugin vim-hexowiki but won't assign `g:hexoLoaded` to 1.

```vim
au FileType markdown packadd vim-hexowiki
```

As expected, using `:packadd vim-hexowiki` explicitly does assign `g:hexoLoaded` to 1.

Is this a bug? Should I open an issue?

**Comment by chrisbra** [comment]
you need to use `nested`

**Comment by alohaia** [comment]
It works. Thanks a lot!
