### ISSUE TITLE
runtime/ftplugin files don't check correctly for g:loaded_matchit

### ISSUE THREAD

**Issue by averms** [vim/vim#3740]
_note: didn't contact the maintainers directly because this would require changing almost all ftplugin files_

In the matchit help file it says to disable matchit by doing `let g:loaded_matchit = 1`.
This doesn't exactly play well with all the files in runtime/ftplugin which extend matchit.
They all check for `exists('loaded_matchit')`.

### Reproduction

Make a vimrc like this:
```
set filetype plugin indent on
syntax enable
let g:loaded_matchit = 1
```

Open `asdf.csh`. Do `let b:` and notice that `b:match_words` has been defined.
This is proof that the csh ftplugin file ran the code to extend matchit even though it
was supposed to be disabled.

### Possible solution

Could change the matchit help to tell people to disable by doing `let g:loaded_matchit = 0`.
Then all the ftplugin files can check for the value of `g:loaded_matchit` being 1, and they will
know that it was the matchit.vim file that set the variable, not the user in an attempt to disable it.

**Comment by jamessan** [comment]
> Open `asdf.csh`. Do `let b:` and notice that `b:match_words` has been defined.
> This is proof that the csh ftplugin file ran the code to extend matchit even though it
> was supposed to be disabled.

What problem does this cause?

If anything, I'd say that the `if exists('loaded_matchit')` checks should just be removed, but that's more work than just doing nothing.  Defining `b:match_words` shouldn't really care about whether matchit is in use or not.  If matchit isn't in use, then nothing will read the variable -- no big deal.

**Comment by averms** [comment]
I get what you're saying but wouldn't it be better to not run unnecessary code?

**Comment by brammool** [comment]
Looks like the help about disabling matchit is wrong.  The part where it says how to activate the plugin is correct.  I'll remove the part at the top about disabling the plugin, since that no longer is how this is done.
So you don't set loaded_matchit to avoid loading, you use ":packadd! matchit" to enable it.

**Comment by chrisbra** [comment]
> I'll remove the part at the top about disabling the plugin, since that no longer is how this is done.
So you don't set loaded_matchit to avoid loading, you use ":packadd! matchit" to enable it.

I don't see how this is wrong, the check for that variable still happens in the plugin.
