### ISSUE TITLE
Invalid memory access when doing :TOhtml

### ISSUE THREAD

**Issue by dpelle** [vim/vim#3749]
I can reproduce an invalid memory access with the latest
vim-8.1.870 and older using this minimalistic ~/.vimrc:

```
set regexpengine=1
syntax on
```
And when running vim as follows:
```
$ valgrind --num-callers=50 ./vim -c help -c 'TOhtml' -c 'qa!' 2> valgrind.log
```

valgrind.log then contains:
```
==21218== Memcheck, a memory error detector
==21218== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==21218== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==21218== Command: ./vim -c help -c TOhtml -c qa!
==21218== 
==21218== Invalid read of size 1
==21218==    at 0x4DF7E3: utf_head_off (mbyte.c:3851)
==21218==    by 0x5423F8: regmatch (regexp.c:5588)
==21218==    by 0x5423F8: regtry (regexp.c:4072)
==21218==    by 0x5427CE: bt_regexec_both (regexp.c:3963)
==21218==    by 0x543B07: vim_regexec_multi (regexp.c:8378)
==21218==    by 0x57DC5E: syn_regexec (syntax.c:3292)
==21218==    by 0x586D47: syn_current_attr (syntax.c:2090)
==21218==    by 0x588AFF: get_syntax_attr (syntax.c:1842)
==21218==    by 0x588BD2: syn_get_id (syntax.c:6551)
==21218==    by 0x44D5E9: f_synID (evalfunc.c:12860)
==21218==    by 0x452F61: call_internal_func (evalfunc.c:1110)
==21218==    by 0x5AFAA9: call_func (userfunc.c:1507)
==21218==    by 0x5B0BA1: get_func_tv (userfunc.c:455)
==21218==    by 0x43EDFD: eval7 (eval.c:4147)
==21218==    by 0x43EFE3: eval6 (eval.c:3784)
==21218==    by 0x43F292: eval5 (eval.c:3600)
==21218==    by 0x439C33: eval4 (eval.c:3484)
==21218==    by 0x439C33: eval3 (eval.c:3404)
==21218==    by 0x439DC3: eval2 (eval.c:3336)
==21218==    by 0x439DC3: eval1 (eval.c:3264)
==21218==    by 0x43A55A: eval0 (eval.c:3224)
==21218==    by 0x43DDD0: ex_let (eval.c:1232)
==21218==    by 0x479053: do_one_cmd (ex_docmd.c:2525)
==21218==    by 0x479053: do_cmdline (ex_docmd.c:1036)
==21218==    by 0x4694CE: do_source (ex_cmds2.c:4615)
==21218==    by 0x467E75: do_in_path (ex_cmds2.c:3537)
==21218==    by 0x468036: do_in_path_and_pp (ex_cmds2.c:3597)
==21218==    by 0x479053: do_one_cmd (ex_docmd.c:2525)
==21218==    by 0x479053: do_cmdline (ex_docmd.c:1036)
==21218==    by 0x5B0217: call_user_func (userfunc.c:954)
==21218==    by 0x5B0217: call_func (userfunc.c:1488)
==21218==    by 0x5B0BA1: get_func_tv (userfunc.c:455)
==21218==    by 0x5B36E3: ex_call (userfunc.c:3171)
==21218==    by 0x479053: do_one_cmd (ex_docmd.c:2525)
==21218==    by 0x479053: do_cmdline (ex_docmd.c:1036)
==21218==    by 0x40ABA2: do_ucmd (ex_docmd.c:7010)
==21218==    by 0x479175: do_one_cmd (ex_docmd.c:2516)
==21218==    by 0x479175: do_cmdline (ex_docmd.c:1036)
==21218==    by 0x60DD68: exe_commands (main.c:2964)
==21218==    by 0x60DD68: vim_main2 (main.c:814)
==21218==    by 0x40D041: main (main.c:441)
==21218==  Address 0x91a308d is 13 bytes after a block of size 4,096 alloc'd
==21218==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==21218==    by 0x4D46D0: lalloc (misc2.c:982)
==21218==    by 0x60E6E0: mf_alloc_bhdr.isra.3 (memfile.c:898)
==21218==    by 0x60F4B6: mf_new (memfile.c:379)
==21218==    by 0x4BA38F: ml_new_data (memline.c:3827)
==21218==    by 0x4BC1B8: ml_append_int (memline.c:2895)
==21218==    by 0x49521A: readfile (fileio.c:2293)
==21218==    by 0x417CCD: open_buffer (buffer.c:215)
==21218==    by 0x45A501: do_ecmd (ex_cmds.c:4286)
==21218==    by 0x45A9C0: getfile (ex_cmds.c:3735)
==21218==    by 0x590361: jumpto_tag (tag.c:3279)
==21218==    by 0x590361: do_tag (tag.c:1029)
==21218==    by 0x460079: ex_help (ex_cmds.c:6483)
==21218==    by 0x479053: do_one_cmd (ex_docmd.c:2525)
==21218==    by 0x479053: do_cmdline (ex_docmd.c:1036)
==21218==    by 0x60DD68: exe_commands (main.c:2964)
==21218==    by 0x60DD68: vim_main2 (main.c:814)
==21218==    by 0x40D041: main (main.c:441)
```

Code at regexp.c:5588:
```
  5581 #ifdef FEAT_MBYTE
  5582                         if (has_mbyte)
  5583                         {
  5584                             char_u *line =
  5585                                          reg_getline(behind_pos.rs_u.pos.lnum);
  5586 
  5587                             rp->rs_un.regsave.rs_u.pos.col -=
!!5588                                 (*mb_head_off)(line, line
  5589                                     + rp->rs_un.regsave.rs_u.pos.col - 1) + 1;
  5590                         }
```
At regex.c:5588, I see that we have:
* line contains the following string of length=36:
```
|tips.txt|    various tips on using Vim
```
* and rp->rs_un.regsave.rs_u.pos.col is 51, so line + rp->rs_un.regsave.rs_u.pos.col - 1
  is beyond the end of the 'line' string.

The bug only happens with regexpengine=1.  It does not happen
with regexpengine=2.

**Comment by brammool** [comment]
Dominique wrote:

> I can reproduce an invalid memory access with the latest
> vim-8.1.870 and older using this minimalistic ~/.vimrc:
> 
> ```
> set regexpengine=1
> syntax on
> ```
> And when running vim as follows:
> ```
> $ valgrind --num-callers=50 ./vim -c help -c 'TOhtml' -c 'qa!' 2> valgrind.log
> ```
> 
> valgrind.log then contains:

I cannot reproduce the problem.  Does it still happen when you add
--clean to the command?

I did find a memory leak, I sent out a patch to fix that.

-- 
From "know your smileys":
 <>:-)	Bishop

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dpelle** [comment]
@brammool wrote: 

> I cannot reproduce the problem. Does it still happen when you
> add --clean to the command? 

Yes. I can reproduce it using the latest vim-8.1.674 with:
```
$ valgrind --num-callers=50 ./vim --clean -c 'so $VIMRUNTIME/plugin/tohtml.vim' -c 'set re=1' -c 'syntax on' -c help -c TOhtml -c 'qa!' 2> valgrind.log
```

**Comment by dpelle** [comment]
Hmmm, Now I cannot reproduce it anymore either!?  I'm confused. 
I could reproduce it all the time earlier.

**Comment by dpelle** [comment]
Now I can reproduce it again. Somehow the bug no longer happened with
help.txt after the latest runtime  commit today. But if I open the previous
version of help,txt then the bug happens again, with the latest vim-8.1.674.

I attach the file "help.txt" that makes the bug happen:

[help.txt](https://github.com/vim/vim/files/2719420/help.txt)

Using that help.txt, I can reproduce the bug with:
```
$ valgrind --num-callers=50 ./vim --clean -c 'so $VIMRUNTIME/plugin/tohtml.vim' -c 'set re=1' -c 'syntax on' help.txt -c TOhtml -c 'qa!' 2> valgrind.log
```

Then valgrind.log contains the errors.

**Comment by brammool** [comment]
Dominique wrote:

> Now I can reproduce it again. Somehow the bug no longer happened with
> help.txt after the latest runtime  commit today. But if I open the previous
> version of help,txt then the bug happens again, with the latest vim-8.1.674.
> 
> I attach the file "help.txt" that makes the bug happen:
> 
> [help.txt](https://github.com/vim/vim/files/2719420/help.txt)
> 
> Using that help.txt, I can reproduce the bug with:
> ```
> $ valgrind --num-callers=50 ./vim --clean -c 'so $VIMRUNTIME/plugin/tohtml.vim' -c 'set re=1' -c 'syntax on' help.txt -c TOhtml -c 'qa!' 2> valgrind.log
> ```
> 
> Then valgrind.log contains the errors.

It appears to depend on a combination of lines right at the end of a data
block.   Hard to find with stepping through the code.  I deleted lines until at
about line 100, this is apparently where it happens.  But still would require a
lot of single-stepping through the regexp code to find out what happens.

Fortunately, staring at the code I notice it changes the column in one
position, while using the line number of another.  That line number usually is
the same, except when a look-behind match crosses a line boundary.  Changing
the position used for the line number indeed makes the valgrind error go away.
Normally using the wrong line would still point inside the data block, and no
error would be generated.  It would just use the wrong text.

This must have been broken for years...

-- 
I AM THANKFUL...
...for the mess to clean after a party because it means I have
been surrounded by friends.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by fritzophrenic** [comment]
Just to make sure I'm clear...this was a Vim issue found *using* TOhtml, not a TOhtml issue that I need to fix, correct?

The next update is still a work in progress, I'm trying not to add even more scope if I can avoid it. :-)

**Comment by dpelle** [comment]
@fritzophrenic wrote:

> Just to make sure I'm clear...this was a Vim issue found using TOhtml,
> not a TOhtml issue that I need to fix, correct?

Yes, it was a Vim issue, not a bug with TOhtml script.
If valgrind complains about a memory error, it can only be a vim bug.

I confirm that patch 8.1.0677 fixes the bug. But I'm currently running
TOhtml on a bunch of files to see if there are remaining issues.  So far
so good, so I'm confident already that it's now fine.
