### ISSUE TITLE
`:set cpo+=y` breaks `:normal! .` in visual mode

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#3760]
- `vim --version`:      VIM - Vi IMproved 8.1  Included patches: 1-681
 - Operating system:     Ubuntu 16.04.5 LTS
 - Terminal emulator:    rxvt-unicode v9.22
 - Terminal multiplexer: tmux next-2.9
 - `$TERM`:              tmux-256color
 - Shell:                zsh 5.6.2-dev-1 (x86_64-pc-linux-gnu)

According to `:h 'cpo`, a yank command can be repeated with the dot command, provided that `'cpo'` contains the `y` flag.

Now, consider this `/tmp/file`:

    $ cat >/tmp/file <<'EOF'
    foo
    bar
    baz
    EOF

It contains 3 lines with the words `foo`, `bar` and `baz`.

I start Vim with no custom configuration, and include the `y` flag in `'cpo'`:

    $ vim -Nu NONE +'set cpo+=y' /tmp/file

Then, I insert a comma at the end of the first line by pressing `A,`.
Finally, I visually select the last two lines, and execute `:norm! .` to repeat the insertion of the comma.

Nothing happens, while I expected a comma to be inserted at the end of each visually selected line:

![gif](https://user-images.githubusercontent.com/8505073/50653205-04faeb00-0f89-11e9-9a80-816cf0559297.gif)

If I don't include the `y` flag in `'cpo'`, `:norm! .` works as expected:

![zekcjcl](https://user-images.githubusercontent.com/8505073/50653152-e1d03b80-0f88-11e9-8264-31c398b7e74e.gif)

**Comment by andymass** [comment]
With `cpo+=y`, after performing a visual selection the Redobuff contains `"*vy` as with any other visual yank.

Maybe this patch would be the best fix?

```diff
diff --git a/src/normal.c b/src/normal.c
index 77191c67e..b76a3852a 100644
--- a/src/normal.c
+++ b/src/normal.c
@@ -1628,7 +1628,8 @@ do_pending_operator(cmdarg_T *cap, int old_col, int gui_yank)
            }

            /* can't redo yank (unless 'y' is in 'cpoptions') and ":" */
-           if ((vim_strchr(p_cpo, CPO_YANK) != NULL || oap->op_type != OP_YANK)
+           if ((vim_strchr(p_cpo, CPO_YANK) != NULL && !gui_yank
+                       || oap->op_type != OP_YANK)
                    && oap->op_type != OP_COLON
 #ifdef FEAT_FOLDING
                    && oap->op_type != OP_FOLD
```

**Comment by lacygoill** [comment]
I wasn't able to apply the patch with `$ git apply /tmp/patch`:

    error: patch failed: src/normal.c:1628
    error: src/normal.c: patch does not apply

So I edited `src/normal.c` like the patch would have, and I can confirm that it fixes the issue.

`:normal! .` works as expected, from visual mode, even after including `y` in `'cpo'`.

Thank you very much @andymass.

**Comment by brammool** [comment]
Andy Massimino wrote:

> With `cpo+=y`, after performing a visual selection the Redobuff contains `"*vy` as with any other visual yank.
> 
> Maybe this patch would be the best fix?

Thanks.  Yes, that should work.  But CPO_YANK is used twice, I think
both should check gui_yank.

I do wonder why anybody would be using the 'y' flag in 'guioptions'.
I suspect it breaks some plugins.  But anyway, it should not break
things when yanking text for the clipboard.


-- 
hundred-and-one symptoms of being an internet addict:
99. The hum of a cooling fan and the click of keys is comforting to you.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
