### ISSUE TITLE
job_start does not regenerate its output buffer after it is deleted

### ISSUE THREAD

**Issue by trevoravant** [vim/vim#3764]
Consider the following command:

`:let job = job_start('/bin/sh -c "echo hello"', {'out_io': 'buffer', 'out_name': 'test_buffer', 'out_msg': 0})`

This command creates a new buffer called _test_buffer_ which contains _hello_. If I run this command again, as expected, _hello_ is appended to the buffer.

However, if I delete _test_buffer_ and run the command again, _test_buffer_ is not re-created. I would think that the buffer should be regenerated. Is this a bug or the expected behavior?

*tested using Vim 8.1.570 and Arch Linux

**Comment by brammool** [comment]
> Consider the following command:
> 
> `:let job = job_start('/bin/sh -c "echo hello"', {'out_io': 'buffer', 'out_name': 'test_buffer', 'out_msg': 0})`
> 
> This command creates a new buffer called _test_buffer_ which contains _hello_. If I run this command again, as expected, _hello_ is appended to the buffer.
> 
> However, if I delete _test_buffer_ and run the command again, _test_buffer_ is not re-created. I would think that the buffer should be regenerated. Is this a bug or the expected behavior?
> 
> *tested using Vim 8.1.570 and Arch Linux

It appears to work fine if you wipe out the buffer, but when you delete
the buffer (it's still in the list of buffers) then it won't be prepared
for writing to it.  We can fix that.

-- 
Laughing helps. It's like jogging on the inside.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
