### ISSUE TITLE
Syntax highlighting for bash: string operation wrongly highlighted as error

### ISSUE THREAD

**Issue by 38spl** [vim/vim#3773]
the following is valid bash(1) code to trim the last character of a string:

`string="${string::$((${#string}  -  1  ))  }"`

The text set apart (dash, last two parens) is **wrongly** highlighted as a syntax error.

Interestingly, very similar code to trim the _first_ character does not highlight as an error.

`string="${string:$((${#string}-1))}"`

So I am guessing this is a fairly simple fix. Unfortunately not sure where to start in the rather complex syntax highlighting file.

**Comment by chrisbra** [comment]
Please check the help at `:h ft-sh-syntax`. Especially relevant is the section about `bash`. So have you set the `g:is_bash` variable? I cannot reproduce it, once this is set.
