### ISSUE TITLE
Start blinking cursor while background on Windows

### ISSUE THREAD

**Issue by mattn** [vim/vim#3778]
Repro:

1. start with gvim.exe --clean -N
2. move focus to another window as soon as showing gVim window.
3. wait &updatetime seconds.

Cursor blink even if gVim window is background.

https://github.com/vim/vim/blob/b589f95b38ddd779d7e696abb0ea011dc92ea903/src/menu.c#L2086

This is caused by calling SetActiveWindow in gui_update_menus that is called for lazy updating menus. This lazy loading of menus are implemented in https://github.com/vim/vim/commit/040c1feb212568cf04265e59b26182f8b76057aa .

I checked some behaviors with removing this call of SetActiveWindow.

Cases|Focus is back to main Window
-|:-:
After `:tearoff Edit`| OK
After selecting tearoff menu(dotted)| OK
After clicking items in floating window| OK
After closing floating window| OK

So I think we can remove this call of SetActiveWindow. @brammool How do you think?

**Comment by brammool** [comment]
> Repro:
> 
> 1. start with gvim.exe --clean -N
> 2. move focus to another window as soon as showing gVim window.
> 3. wait &updatetime seconds.
> 
> Cursor blink even if gVim window is background.
> 
> https://github.com/vim/vim/blob/b589f95b38ddd779d7e696abb0ea011dc92ea903/src/menu.c#L2086
> 
> This is caused by calling SetActiveWindow in gui_update_menus that is called for lazy updating menus. This lazy loading of menus are implemented https://github.com/vim/vim/commit/040c1feb212568cf04265e59b26182f8b76057aa .
> 
> I checked some behaviors with removing this call of SetActiveWindow.
> 
> Cases|Focus is back to main Window
> -|:-:
> After `:tearoff Edit`| OK
> After selecting tearoff menu(dotted)| OK
> After clicking items in floating window| OK
> After closing floating window| OK
> 
> So I think we can remove this call of SetActiveWindow. @brammool How
> do you think?

I don't have an opinion about this.  I thought nobody would be using the
tearoff menu, but when I suggested removing the feature some people
mentioned they do use it.

I believe the situation this is covering is when there is a tearoff menu
open (which basically is a window), and something causes the menu's to
be updated, e.g. switching to Insert mode.  This is old code, maybe it
also depends on the Windows version?

-- 
hundred-and-one symptoms of being an internet addict:
133. You communicate with people on other continents more than you
     do with your own neighbors.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mattn** [comment]
Windows after Windows XP, some conditions to make the window foreground are added, but it is probably not related to this problem.

**Comment by tonymec** [comment]
For comparison, on Linux with GTK2 gvim, when gvim is not the active window, its cursor is a hollow unblinking box, regardless of whether the active window is konsole or a teared-off menu (which, on this GUI, has full "window decorations" i.e. titlebar with Vim icon and pin at left, "Maximize" and "Close" buttons at right). Making gvim active makes its cursor blinking black, even when showing the :intro screen.

**Comment by mattn** [comment]
@tonymec Yes, this is Windows specific code for workaround.

https://github.com/vim/vim/blob/b589f95b38ddd779d7e696abb0ea011dc92ea903/src/menu.c#L2083-L2087

**Comment by mattn** [comment]
FYI, SetActiveWindow is called in gui_mch_tearoff. So I don't understand why this code is needed in gui_update_menus.

https://github.com/vim/vim/blob/b589f95b38ddd779d7e696abb0ea011dc92ea903/src/gui_w32.c#L8217
