### ISSUE TITLE
`:chistory` doesn't show the list of error lists if the last one is empty

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#3784]
- `vim --version`:      VIM - Vi IMproved 8.1  Included patches: 1-707
 - Operating system:     Ubuntu 16.04.5 LTS
 - Terminal emulator:    rxvt-unicode v9.22
 - Terminal multiplexer: tmux next-2.9
 - `$TERM`:              tmux-256color
 - Shell:                zsh 5.6.2-dev-1 (x86_64-pc-linux-gnu)

If the last quickfix list in the stack contains no valid entry, it seems that `:chistory` reports the message `No entries`.

    $ vim -Nu NONE
    :exe 'helpgrep vim' | exe 'helpgrep text' | exe 'helpgrep wont_be_found'
    :chi

But in this example, there are still 2 quickfix lists with valid entries, and there are 3 quickfix lists in the stack as reported by:

    :echo get(getqflist({'nr': '$'}), 'nr', 0)

Shouldn't `:chi` display information about all the quickfix lists in the stack, regardless of whether the last one contains a valid entry?

**Comment by vim-ml** [comment]
Hi,

On Wed, Jan 9, 2019 at 3:55 PM lacygoill <vim-dev-github@256bit.org> wrote:
>
> vim --version: VIM - Vi IMproved 8.1 Included patches: 1-707
> Operating system: Ubuntu 16.04.5 LTS
> Terminal emulator: rxvt-unicode v9.22
> Terminal multiplexer: tmux next-2.9
> $TERM: tmux-256color
> Shell: zsh 5.6.2-dev-1 (x86_64-pc-linux-gnu)
>
> If the last quickfix list in the stack contains no valid entry, it seems that :chistory reports the message No entries.
>
> $ vim -Nu NONE
> :exe 'helpgrep vim' | exe 'helpgrep text' | exe 'helpgrep wont_be_found'
> :chi
>
> But in this example, there are still 2 quickfix lists with valid entries, and there are 3 quickfix lists in the stack as reported by:
>
> :echo get(getqflist({'nr': '$'}), 'nr', 0)
>
> Shouldn't :chi display information about all the quickfix lists in the stack, regardless of whether the last one contains a valid entry?
>

This will be fixed when the pull request #3701 is merged.

https://github.com/vim/vim/pull/3701

The change related to this in the above pull request is:

diff --git a/src/quickfix.c b/src/quickfix.c
index 71fe4939f..747dead65 100644
--- a/src/quickfix.c
+++ b/src/quickfix.c
@@ -3687,7 +3687,7 @@ qf_history(exarg_T *eap)

     if (is_loclist_cmd(eap->cmdidx))
        qi = GET_LOC_LIST(curwin);
-    if (qf_stack_empty(qi) || qf_list_empty(qi, qi->qf_curlist))
+    if (qf_stack_empty(qi))
        MSG(_("No entries"));
     else
        for (i = 0; i < qi->qf_listcount; ++i)
@@ -6548,6 +6548,49 @@ qf_setprop_context(qf_list_T *qfl, dictitem_T *di)
     return OK;
 }

Regards,
Yegappan

**Comment by lacygoill** [comment]
Ok, thank you very much for your answer. I close the issue, and will wait for the PR to be merged.

**Comment by vim-ml** [comment]
Hi,

On Wed, Jan 9, 2019 at 7:30 PM lacygoill <vim-dev-github@256bit.org> wrote:
>
> Ok, thank you very much for your answer. I close the issue, and will wait for the PR to be merged.
>

This has been merged now. Can you try with the latest version of Vim?

- Yegappan

**Comment by lacygoill** [comment]
Yes, the issue has been fixed by the patch.

I just tested on Vim version `8.1.728`, and `:chistory` doesn't report `No entries` anymore when the quickfix list is empty, and instead correctly prints the stack of quickfix lists. Thank you very much for the PR.
