### ISSUE TITLE
Value -Infinity does not behave as expected with js_decode() and js_encode

### ISSUE THREAD

**Issue by dpelle** [vim/vim#3788]
Value '-Infinity' does not behave as expected with js_decode() and js_encode() as discussed in this comment: https://github.com/vim/vim/pull/3787#discussion_r246865962

This works as expected:
```
:echo js_decode('Infinity')
inf
```
But this does not work as expected (should print -inf without any error):
```
:echo js_decode('-Infinity')
E474: Invalid argument
E474: Invalid argument
E474: Invalid argument
v:none
```

This works as expected:
```
:echo js_encode(1.0/0.0)
Infinity
```

But this does not work as expected (should print -Infinity):
```
:echo js_encode(-1.0/0.0)
Infinity
```

I'm using Vim-8.1.714 (huge).

**Comment by k-takata** [comment]
Fixed with 8.1.0731.
