### ISSUE TITLE
Feature request: allow properties to be attached to the text on the command-line

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#3796]
According to `:h text-prop-intro`, text properties can be used to find some known text.

> Text properties can also be used for other purposes to identify text.  For
> example, add a text property on a function name, so that a search can be
> defined to jump to the next/previous function.

But at the moment, they don't seem to be intended to be used on the command-line:

> Text properties can be attached to text in **a buffer**.

Would it be possible to extend their usage to the text on the command-line?

---

As an example of possible usage, I would like to reproduce [this functionality](https://www.youtube.com/watch?v=JJQYwt6Diro&t=420) provided by the UltiSnips plugin. But not in a buffer, on Vim's command-line.

So, I wrote this code which installs the `s:cmdline_complete_set()` function.

<details><summary>
click to see code:</summary>

    fu! s:monitor_change(seq) abort
        let s:seq = a:seq
        let s:old_prefix = ''
        augroup stop_monitoring_cmdline
            au!
            au CmdlineChanged : call s:update(s:seq)
            au CmdlineLeave : call s:leave()
        augroup END
        return ''
    endfu
    fu! s:leave() abort
        if exists('s:timer_id')
            call timer_stop(s:timer_id)
        endif
        unlet! s:timer_id s:old_prefix s:seq
        au! stop_monitoring_cmdline
        aug! stop_monitoring_cmdline
    endfu
    fu! s:update(seq) abort
        let cmdline = getcmdline()
        let pat = '\[' . '\%([^|\]]\+|\)'.'*' . '[^|\]]*' . '\]'
        let prefix_pat = '\S*\ze'.pat
        let prefix = matchstr(cmdline, prefix_pat)
        if prefix isnot# s:old_prefix && cmdline =~# '\S*\zs'.pat
            let candidates = deepcopy(s:db[a:seq])
            call filter(candidates, {i,v -> v =~# '^'.prefix})
            call map(candidates, {i,v -> substitute(v, '^'.prefix, '', '')})
            call filter(candidates, {i,v -> v isnot# ''})
            let pos = getcmdpos()
            if len(candidates) == 0
                let candidates = ''
            elseif len(candidates) == 1
                let candidates = candidates[0]
                let pos += strlen(candidates)
            else
                let candidates = '['.join(candidates, '|').']'
            endif
            let new_cmdline = substitute(cmdline, '\S*\zs'.pat, candidates, '')
            let seq = "\<c-e>\<c-u>".new_cmdline."\<c-r>=setcmdpos(".pos.")[-1]\<cr>"
            call feedkeys(seq, 'in')
            let s:old_prefix = prefix
        endif
    endfu
    fu! s:find_tabstop(rhs) abort
        exe 'nno <plug>(complete-find-tabstop) :'.a:rhs
        return stridx(maparg('<plug>(complete-find-tabstop)'), '@')
    endfu
    fu! s:set_candidates(...) abort
        let s:candidates = a:000
        return ''
    endfu
    fu! s:cmdline_complete_set(seq, cmd, ...) abort
        let pos = s:find_tabstop(a:cmd)
        let cmd = substitute(a:cmd, '@', '', '')
        let s:db = extend(get(s:, 'db', {}), {a:seq: a:000})
        exe 'nno <c-g>'.a:seq.' :<c-u><c-r>=<sid>monitor_change('.string(a:seq).')<cr>'
            \ . substitute(cmd, '[]', '['.join(a:000, '<bar>').']', '')
            \ . '<c-r>=setcmdpos('.pos.')[-1]<cr>'
    endfu
</details>

---

I intend to use it like this (just an example):

    call s:cmdline_complete_set('f', 'filter /@/ []',
        \ '%#','abbreviate','chistory','command','ls','map','messages','oldfiles','scriptnames')

This installs a mapping triggered by <kbd>C-g f</kbd>, which populates the command-line with:

    :filter // [%#|abbreviate|chistory|command|ls|map|messages|oldfiles|scriptnames]

If I press `c` while the cursor is before `[`, the command-line becomes:

    :filter /pat/ c[history|ommand]

If I then press `o`, the command-line becomes:

    :filter /pat/ command

But after that, if I realize I made a mistake and remove `command`, the line becomes:

    :filter /pat/

![gif](https://user-images.githubusercontent.com/8505073/51086038-c829b380-1741-11e9-8af4-901e467c2adc.gif)

While I would want all the original completions:

    :filter /pat/ [%#|abbreviate|chistory|command|ls|map|messages|oldfiles|scriptnames]

Which is what you get in the UltiSnips example shown in the video, earlier.

There are other issues with the current code. Like the fact that it won't work as expected if a completion contains spaces, or if the command-line contains square brackets which could interfere with the detection of the completions.

I think all of these issues could be reliably solved if I could attach a property on the space before the candidates,and use it to get the updated position of the completed text.

    :filter /pat/ [%#|abbreviate|chistory|command|ls|map|messages|oldfiles|scriptnames]
                 ^
                 here

I could then tell an autocmd listening to `CmdlineChanged` to monitor what the completed text is, and re-suggest relevant candidates when it's an invalid or incomplete candidate.

---

I also would like to emulate some readline functions on Vim's command-line, like `exchange-point-and-mark`, `kill-region` or `quote-region`.

But the issue is always the same: how to track the relevant text considering that the line can be edited in various ways? You can move around the command-line, and at any location press `C-w` to delete the previous word or `C-r a` to insert the contents of register `a`. Each of these edits would require to update the position of the text you're interested in. I guess you could install an autocmd listening to `CmdlineChanged`, and compare the old command-line with the new one to compute the new position of the text, but I'm not sure...

---

I may have misunderstood the concept of text properties, but it seems they could be very useful in these examples, and make the code much easier to write and more reliable.

Feel free to close the issue if it's not poossible, or if there's already a way to achieve all of this without text properties.

**Comment by lacygoill** [comment]
Having thought a little more about it, I think I will try to just use `CmdlineChanged` to compute the updated position of the text.

**Comment by brammool** [comment]
> According to `:h text-prop-intro`, text properties can be used to find
> some known text.
> 
> > Text properties can also be used for other purposes to identify text.  For
> > example, add a text property on a function name, so that a search can be
> > defined to jump to the next/previous function.
> 
> But at the moment, they don't seem to be intended to be used on the
> command-line:
> 
> > Text properties can be attached to text in **a buffer**.
> 
> Would it be possible to extend their usage to the text on the command-line?

No, that's something completely different.

-- 
hundred-and-one symptoms of being an internet addict:
193. You ask your girlfriend to drive home so you can sit back with
     your PDA and download the information to your laptop

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
