### ISSUE TITLE
Regression with signs introduced by vim-8.1.614 when using YouCompleteMe plugin

### ISSUE THREAD

**Issue by dpelle** [vim/vim#3802]
I'm using the YouCompleteMe plugin from: https://github.com/Valloric/YouCompleteMe

This plugin puts, among other things, signs to highlight syntax errors when editing
a source file. Those signs are automatically updated after a short delay as user edits
the buffer. The feature is further described at:
  https://github.com/Valloric/YouCompleteMe#diagnostic-display

That feature is broken in recent vim. I did a git bissection:

With vim-8.1.613, YouCompleteMe works as expected:
* a sign is introduced by YouCompleteMe when typing a syntax error (good)
* the sign is deleted when correcting the syntax error (good)

With vim-8.1.614 and newer (up to at least the latest 8.1.744), behavior is wrong:
* a sign is introduced by YouCompleteMe when typing a syntax error (good)
* the sign is no longer deleted when correcting the syntax error (BUG! )

The change that broke it is:
```
commit 162b71479bd4dcdb3a2ef9198a1444f6f99e6843
Author: Bram Moolenaar <Bram@vim.org>
Date:   Fri Dec 21 15:17:36 2018 +0100

    patch 8.1.0614: placing signs can be complicated
    
    Problem:    Placing signs can be complicated.
    Solution:   Add functions for defining and placing signs.  Introduce a group
                name to avoid different plugins using the same signs. (Yegappan
                Lakshmanan, closes #3652)
```

In case, it matters, I'm using this git SHA1 of the YouCompleteMe plugin
https://github.com/Valloric/YouCompleteMe/commit/75bf1738dcac502fa2d04e87116a3ce65249be8c

**Comment by dpelle** [comment]
In bug description, I wrote:

> In case, it matters, I'm using this git SHA1 of the YouCompleteMe plugin
> Valloric/YouCompleteMe@75bf173

I just upgraded my YouCompleteMe plugin and the issue is fixed somehow.
However, there must still be a bug in vim, since behavior was changed
between vim-7.1.613 and vim-7.1.614 as described in bug when using
the old version of YouCompleteMe (75bf173)

Furthermore, with the latest YouCompleteMe, I see another
regression.  Although the sign is now removed, the screen
is not properly updated, as depicted in this screenshot (sign
was removed at line 81 and that line is not properly redrawn):

![incorrect-redraw-after-sign-removal-at-line-81](https://user-images.githubusercontent.com/2261629/51133265-d0aee680-1834-11e9-874d-b63fda24ee1e.png)

Pressing CTRL-L fixes redraws the screen properly.
This 2nd regression is introduced by vim-8.1.709:

```
commit 27a472c32ed5b5298bca50864570a4a71ec1d204
Author: Bram Moolenaar <Bram@vim.org>
Date:   Wed Jan 9 21:47:30 2019 +0100

    patch 8.1.0709: windows are updated for every added/deleted sign
    
    Problem:    Windows are updated for every added/deleted sign.
    Solution:   Do not call update_debug_sign().  Only redraw when the line with
                the sign is visible.  (idea from neovim #9479)
```

In  summary, there appear to be 2 different regressions with signs:
* regression 1 is introduced by vim-8.1.614 (sign not removed when using old YouCompleteMe)
* regression 2 is introduced by vim-8.1.709 (screen not properly redrawn when using latest YouCompleteMe)

Pressing CTRL- L only works around regression 2.

I'll try to find a simpler way to reproduce the regressions without
using YouCompleteMe.

Cc-ing @yegappan for regression #1 and @micbou for YouCompleteMe.

**Comment by dpelle** [comment]
Searching a bit, I found https://github.com/Valloric/YouCompleteMe/pull/3279
which describes regression 1 (sign not removed) introduced by vim-8.614.
From the description there, it appears that was not a vim bug after all, but
a wrong assumption in the vim plugin.

However, regression 2 in my previous comment  (screen not properly redrawn
when removing sign) should definitely be a bug in Vim introduced by Vim-8.1.709.

**Comment by vim-ml** [comment]
Hi,

On Mon, Jan 14, 2019 at 11:02 AM Dominique Pellé
<vim-dev-github@256bit.org> wrote:
>
> Searching a bit, I found Valloric/YouCompleteMe#3279
> which describes regression #1 (sign not removed) introduced by vim-8.614.
> From the description there, it appears that was not a vim bug after all, but
> a wrong assumption in the vim plugin.
>

Thanks for reporting tracing the fix.

The YCM plugin can start using the new sign functions to get the list of placed
signs instead of parsing the command output to be more predictable in the
future.

It will be useful to get feedback on the new sign functions and functionalities
from plugins like this which use signs heavily.

Regards,
Yegappan

>
> However, regression #2 in my previous comment (screen not properly redrawn
> when removing sign) should definitely be a bug in Vim introduced by Vim-8.1.709.
>

**Comment by dpelle** [comment]
Since this ticket describes to different issue and since issue 1 was not a bug in vim after all.  I'm closing this ticket and I open a separate one (https://github.com/vim/vim/issues/3803 ) for the screen which is not properly redrawn, and for which I just found a simple way to reproduce it without YouCompleteMe.
