### ISSUE TITLE
gVim on Windows starts with a tiny window when using "set guioptions+=k" 

### ISSUE THREAD

**Issue by ychin** [vim/vim#3808]
## Bug
When running gVim on Windows, if you have `set guioptions +=k` in vimrc, the window will be really tiny (see screenshot). The user has to manually resize it for it to be in a usable size. This issue doesn't show up if the 'k' guioptions wasn't set.

## Screenshot
![image](https://user-images.githubusercontent.com/1217449/51235721-16e37300-1925-11e9-9c51-0f8d7928bf21.png)

## Cause
This bug was introduced by #3616. See my comment (https://github.com/vim/vim/pull/3616#issuecomment-449952161) for more details. We can't just fix this by reverting that PR (which changed initialization to call `gui_set_shellsize` with `FALSE`) since it would break the original issue it's trying to fix (#3615), but we should probably find a way to initialize it properly so it still works with `set guioptions+=k` in vimrc.

**Comment by mattn** [comment]
Can this solve this?
```diff
diff --git a/src/gui.c b/src/gui.c
index d993bc6b0..3d2e632bf 100644
--- a/src/gui.c
+++ b/src/gui.c
@@ -682,7 +682,11 @@ gui_init(void)
     // Set the shell size, adjusted for the screen size.  For GTK this only
     // works after the shell has been opened, thus it is further down.
     // For MS-Windows pass FALSE for "mustset" to make --windowid work.
-    gui_set_shellsize(FALSE, TRUE, RESIZE_BOTH);
+    // But if go+=k specified, resize forcibly.
+    if (vim_strchr(p_go, GO_KEEPWINSIZE) == NULL)
+	gui_set_shellsize(FALSE, TRUE, RESIZE_BOTH);
+    else
+	gui_set_shellsize(TRUE, TRUE, RESIZE_BOTH);
 #endif
 #if defined(FEAT_GUI_MOTIF) && defined(FEAT_MENU)
     /* Need to set the size of the menubar after all the menus have been
```
I don't make sure that it is needed to checking whether --windowid or --socketid is specified.

**Comment by ychin** [comment]
I think this patch wouldn't completely fix the issue. If a user's vimrc has `set go+=k` and launches gVim using `--windowid` he would still see the issue that #3616 is trying to fix (that the window size doesn't look maximized).

Looking more into it, the issue is that when you pass `--windowid` in, these lines in `gui_mch_init(void)` will maximize the window (`win_socket_id` would be non-null in this case):

````c
if (s_hwnd != NULL && win_socket_id != 0)
{
    SetParent(s_hwnd, (HWND)win_socket_id);
    ShowWindow(s_hwnd, SW_SHOWMAXIMIZED);
}
````

As I mentioned in https://github.com/vim/vim/pull/703#issuecomment-199448937, if the window is maximized, we should be calling `gui_set_shellsize(FALSE,…)` to initialize with the system's provided dimensions. Otherwise, we should pass call `gui_set_shellsize(TRUE,…)` to initialize with Vim's default lines/columns dimensions regardless of whether `GO_KEEPWINSIZE` is. The original patch (#703) just assumed gVim never starts maximized.

For reference this is the code in `gui_set_shellsize(int mustset, …)` that shows the behavior:

```c
    /* If not setting to a user specified size and maximized, calculate the
     * number of characters that fit in the maximized window. */
    if (!mustset && (vim_strchr(p_go, GO_KEEPWINSIZE) != NULL
						       || gui_mch_maximized()))
    {
	gui_mch_newfont();
	return;
    }
```

**Comment by ychin** [comment]
I think this following patch should fix the issue in Windows. I need to see if there are other lurking issues with the GTK implementation as well (even though this issue isn't related to the GTK GUI). This also fixes a bug in `gui_init_font(…)`, where if you call `set guifont=…` when maximized, it will bump you out of the maximized state.

````diff
diff --git a/src/gui.c b/src/gui.c
index 39968954a..dc99919ae 100644
--- a/src/gui.c
+++ b/src/gui.c
@@ -681,8 +681,13 @@ gui_init(void)
 #ifndef FEAT_GUI_GTK
     // Set the shell size, adjusted for the screen size.  For GTK this only
     // works after the shell has been opened, thus it is further down.
-    // For MS-Windows pass FALSE for "mustset" to make --windowid work.
-    gui_set_shellsize(FALSE, TRUE, RESIZE_BOTH);
+    // If the window is already maximized (e.g. when --windowid is passed in),
+    // we want to use the system-provided dimensions by passing FALSE to
+    // mustset. Otherwise, we want to initialize with the default rows/columns.
+    if (gui_mch_maximized())
+	gui_set_shellsize(FALSE, TRUE, RESIZE_BOTH);
+    else
+	gui_set_shellsize(TRUE, TRUE, RESIZE_BOTH);
 #endif
 #if defined(FEAT_GUI_MOTIF) && defined(FEAT_MENU)
     /* Need to set the size of the menubar after all the menus have been
@@ -721,7 +726,10 @@ gui_init(void)
 # endif
 
 	/* Now make sure the shell fits on the screen. */
-	gui_set_shellsize(TRUE, TRUE, RESIZE_BOTH);
+	if (gui_mch_maximized())
+	    gui_set_shellsize(FALSE, TRUE, RESIZE_BOTH);
+	else
+	    gui_set_shellsize(TRUE, TRUE, RESIZE_BOTH);
 #endif
 	/* When 'lines' was set while starting up the topframe may have to be
 	 * resized. */
@@ -906,7 +914,7 @@ gui_init_font(char_u *font_list, int fontset UNUSED)
 # endif
 	    gui_mch_set_font(gui.norm_font);
 #endif
-	gui_set_shellsize(TRUE, TRUE, RESIZE_BOTH);
+	gui_set_shellsize(FALSE, TRUE, RESIZE_BOTH);
     }
 
     return ret;
````

After scrubbing through the code seems like the only real place that sets `mustset` to `TRUE` outside of this is when you call `:win` or `:set lines`/`:set columns`. This means if you are in maximized mode calling `:win 100 100` will put you back to windowed mode. I'm not sure if that's the desired behavior or not (seems like `:win` should just be ignored in maximized mode).
