### ISSUE TITLE
[Feature Request] Allow customization of EndOfBuffer ~ character

### ISSUE THREAD

**Issue by fvgs** [vim/vim#3820]
**Problem**

As mentioned in #2679, the `~` character displayed in the first column of rows that are not part of the file is currently hard coded and cannot be customized from within Vim.

**Existing workarounds**

1.
```
hi EndOfBuffer ctermfg=0 guifg=bg
```
or

2. Change the hard coded `~` to a space and compile a custom Vim
https://github.com/vim/vim/blob/1ac56c2d11da5ffa44db23e1fd0c533d02ab2f66/src/screen.c#L2262-L2263

The first is problematic for terminal emulators utilizing background transparency as the `~` characters remain visible.

The latter requires maintaining an up to date fork of Vim with a tiny change.

**Proposal**

Add a setting to customize the character inserted in the first column of EndOfBuffer rows and the character inserted in the non-first columns of EndOfBuffer rows.

The proposed syntax is similar to that for setting `listchars`, specifically for setting tab characters where the second character is repeated.

e.g.

```vim
set endofbufferchars="  "
set endofbufferchars="• "
set endofbufferchars="••"
```

**Alternatives**

a. Change the hard coded `~` to a hard coded space.
b. Add a flag to enable/disable showing the `~` characters, replacing them with spaces when disabled.
c. Add a setting to customize just the character inserted in the first column of EndOfBuffer rows.

**Next steps**

I would be happy to introduce a PR implementing this and would welcome some guidance as a first time contributor.

**Comment by brammool** [comment]
Why would it be worth showing anything but '~'?

**Comment by fvgs** [comment]
Those wishing for a minimalist editor environment cannot remove or hide the `~` characters on a non-opaque background, such as when utilizing window transparency.

For example, the Goyo plugin would benefit from the ability to fully hide/remove the `~` characters to create a fully minimalist and distraction-free environment.

https://github.com/junegunn/goyo.vim

I would personally like to substitute spaces for the `~` characters so nothing is printed on lines that are not part of the file. This contributes to a more minimalist aesthetic.

Substituting other characters, such as `•`, either in the first column or in the latter columns, is not of interest to me personally. However, allowing that level of customization could be a reasonable consideration if some change is to be made.

**Comment by tonymec** [comment]
Personally I'm OK with the existing state of things; however I can imagine that some people might want to customize the ~ after the last line in the file and/or the @@@ or @ after or instead of the last partial line in the window, replacing them by characters of their choice, including spaces if desired. I suppose one "logical" place for the addition would be as additional items to the 'listchars' option.

Best regards,
Tony.

**Comment by tonymec** [comment]
P.S. Example of use in a hypothetical future plugin or vimrc (the try..catch..endtry part adds it in a backward-compatible way):
```
if exists('+list')
  set list
  if exists('+listchars')
    set lcs=eol:¶,tab:\|_,extends:>,precedes:<,conceal:*,nbsp:·
    try
      set lcs+=eof:\ ,partial:-->
    catch /^Vim\%((\a\+)\)\=:E474/
      " older Vim, eof: and partial: not yet supported,
      " do not add them but clear the error
    endtry
  endif
endif
```
Best regards,
Tony.

**Comment by brammool** [comment]
> Those wishing for a minimalist editor environment cannot remove or
> hide the `~` characters on a non-opaque background, such as when
> utilizing window transparency.
> 
> For example, the Goyo plugin would benefit from the ability to fully
> hide/remove the `~` characters to create a fully minimalist and
> distraction-free environment.
> 
> https://github.com/junegunn/goyo.vim
> 
> I would personally like to substitute spaces for the `~` characters so
> nothing is printed on lines that are not part of the file. This
> contributes to a more minimalist aesthetic.
> 
> Substituting other characters, such as `•`, either in the first column
> or in the latter columns, is not of interest to me personally.
> However, allowing that level of customization could be a reasonable
> consideration if some change is to be made.

How about:
	:hi EndOfBuffer ctermfg=white

You can try different values instead of "white".

-- 
Emacs is a nice OS - but it lacks a good text editor.
That's why I am using Vim.  --Anonymous

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bfredl** [comment]
For reference, Neovim introduced `fcs=eob:X` for this. Here is the patch https://github.com/neovim/neovim/pull/8546/commits/a7bb63c55dacfa822e1a24d041771d9e8d83a980

**Comment by fvgs** [comment]
> How about:
> 	:hi EndOfBuffer ctermfg=white
> 
> You can try different values instead of "white".

Setting the foreground color for the `EndOfBuffer` highlight group only achieves the desired effect of hiding the `~` characters on an opaque and solid color background. In a terminal emulator utilizing transparency or a background image, the characters will stand out from the background and remain visible.

As has been suggested, adding an `eob` option to either `listchars` or `fillchars` seems like a reasonable solution.

**Comment by chrisbra** [comment]
Hm, I wonder if setting `eob` should be buffer local?

**Comment by andymass** [comment]
@chrisbra In neovim, both `listchars` and `fillchars` are local to window (done so recently), in particular `fillchars=eob:...` is as well.

**Comment by fvgs** [comment]
@brammool Thoughts on green lighting this to get started on a PR?

**Comment by brammool** [comment]
So far 'fillchars' are for repeating, single characters.  This one would be a sequence of characters.  it scan still work.  I was also wondering about a window-local version of fillchars.  If we don't make 'fillchars' itself global-local, but instead add a new option for window-local overrides, then adding this one to 'fillchars' would work.

**Comment by fvgs** [comment]
It may be reasonable to restrict the setting to a single character (currently the `~`) and apply it only to the first column of EOB rows in the interest of consistency. The latter columns are currently hard coded as spaces with which I personally have no issue.

But I suppose the case for making both the initial and latter columns customizable is in the general interest of flexibility. Having the ability to insert horizontal lines or blocks instead of blank spaces may be of benefit to visually impaired users?

As for window-local vs global-local, would a global version as part of the existing `fillchars` be a suitable starting point, having either one or two characters pursuant to the above considerations?
