### ISSUE TITLE
`ch_open()` ignores `callback` key in `{options}`

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#3821]
- `vim --version`:      VIM - Vi IMproved 8.1  Included patches: 1-728
 - Operating system:     Ubuntu 16.04.5 LTS
 - Terminal emulator:    rxvt-unicode v9.22
 - Terminal multiplexer: tmux next-2.9
 - `$TERM`:              tmux-256color
 - Shell:                zsh 5.6.2-dev-1 (x86_64-pc-linux-gnu)

According to `:h ch_open()`, `ch_open()` can be passed an optional dictionary argument, `{options}`. And according to `:h channel-open-options` and `:h channel-callback`, this dictionary can contain the `callback` key. The help gives this example:

    func Handle(channel, msg)
      echo 'Received: ' . a:msg
    endfunc
    let channel = ch_open("localhost:8765", {"callback": "Handle"})

I tried to test it, in the following way:

 1. in a terminal, run the python server given in the output of `:echo $VIMRUNTIME/tools/demoserver.py`

 2. start Vim in a second terminal with the following minimal `vimrc`:

        func Handle(channel, msg)
          echom 'Received: ' . a:msg
        endfunc
        let channel = ch_open("localhost:8765", {"callback": "Handle"})

 3. execute `:call ch_sendexpr(channel, 'hello!')`

If the callback was invoked, the message `Received: got it` should be printed on the command-line, and logged in the output of `:messages`. But in practice, there's no message.

I tried to log the activity on the channel with `:call ch_logfile('/tmp/log', 'w')`. Here's what the logfile contains:

    ==== start log session ====
      7.752025 SEND on 0(sock): '[2,"hello!"]
    '
      7.752171 : looking for messages on channels
      7.753345 RECV on 0(sock): '[2, "got it"]'
      7.753363 on 0: Getting JSON message 2
      7.753374 on 0: Dropping message 2 without callback
     11.756455 : looking for messages on channels

This line:

      7.753374 on 0: Dropping message 2 without callback

seems to tell that Vim did receive an answer from the server, but that there was no callback to process it.

Is the help at `:h channel-demo` wrong when it says that one can set a default callback for all messages sent on a channel?

> Instead of giving a callback with every send call, it can also be specified
> when opening the channel:
>
>         call ch_close(channel)
>         let channel = ch_open('localhost:8765', {'callback': "MyHandler"})
>         call ch_sendexpr(channel, 'hello!')

Or did I misunderstand how `ch_open()` is to be used?

**Comment by brammool** [comment]
Please do not open an issue unless you know it's a bug.
Please read ":help channel-use", it will explain about using ch_sendexpr().
The callback is for NL or raw messages, you are using JSON here.

**Comment by badthird** [comment]
sorry ,i meet the same problem, thanks brammool's reply。

**Comment by lacygoill** [comment]
> Please do not open an issue unless you know it's a bug.

I'm never sure of anything so I never know whether something is a bug, but here is what I did before opening this issue:

   - write the issue in my notes

   - read my notes several months apart, and periodically re-perform the tests

   - after a year, since I could still not make the example given in the help work, I posted the issue on stackoverflow.com

   - read my notes several months apart, and periodically re-perform the tests (again)

   - after another year, nobody gave any answer on stackoverflow.com

   - spend a whole weekend only thinking about this issue (which included reading the Python source code of the demo server, while I don't understand Python)

Only then, I opened the current issue.

We are 5 years after I noted this issue for the first time, and I still cannot make the example given in the help work.

---

   > Please read ":help channel-use", it will explain about using ch_sendexpr().

I read [`:help channel-use`](https://vimhelp.org/channel.txt.html#channel-use) before opening the current issue, several times.  I re-read the help at the time the issue was closed.  I've re-read it now.  It still doesn't help me understand why the code doesn't work.

Note that for every single test I did, I run all the commands given at [`:help channel-demo`](https://vimhelp.org/channel.txt.html#channel-demo) without changing anything.  That is:

    # in one terminal
    $ /usr/local/share/vim/vim82/tools/demoserver.py

    # in another terminal
    $ vim -Nu NONE
    :let channel = ch_open('localhost:8765')
    :echo ch_evalexpr(channel, 'hello!')
    :func MyHandler(channel, msg)
    :  echo "from the handler: " . a:msg
    :endfunc
    :call ch_sendexpr(channel, 'hello!', {'callback': "MyHandler"})
    :call ch_close(channel)
    :let channel = ch_open('localhost:8765', {'callback': "MyHandler"})
    :call ch_sendexpr(channel, 'hello!')

Every Ex command after `$ vim -Nu NONE` is copied and pasted right from the current help, without omitting a single  one.

It never worked.  The very last command (the one invoking `ch_sendexpr()` without a callback argument) never triggered the channel callback which should echo `from the handler: got it` a second time.

---

   > The callback is for NL or raw messages, you are using JSON here.

I've reduced one of the few tests which uses this feature to this snippet:
```vim
vim9script
cd $HOME/Vcs/vim/src/testdir
def Ch_handler(_, msg: string)
    echomsg msg
enddef
job_start('python test_channel.py', {stoponexit: 'kill'})
ch_logfile('/tmp/channellog', 'w')
sleep 100m
var handle = ch_open('localhost:' .. readfile('Xportnr')[0], {callback: Ch_handler})
ch_sendexpr(handle, 'call me again')
echomsg 'the channel uses ' .. ch_info(handle).sock_mode
messages
```
Note that the path passed to the first `:cd` command needs to be adapted so that Vim's current working directory is `testdir/`.  Anyway, here is its output:

    the channel uses JSON
    we did call you

Notice that the callback was correctly invoked since it echo'ed `we did call you`.
More importantly, notice that the channel used JSON.  According to [`:help ch_sendexpr()`](https://vimhelp.org/channel.txt.html#ch_sendexpr%28%29), this means that `ch_sendexpr()` used JSON too:

   > Send {expr} over {handle}.  The {expr} is encoded
   > according to the type of channel.

IOW, there are no raw messages nor NL messages involved here.  And yet, the feature works.  This seems to contradict:

   > The callback is for NL or raw messages,

Besides, where is it documented that the callback can only work for NL or raw messages?  There are 64 occurrences of the pattern `callback` at [`:help channel`](https://vimhelp.org/channel.txt.html#channel).  I read the context surrounding each of them, and couldn't find anything explaining this.  The most relevant excerpt I could find is at [`:help channel-callback`](https://vimhelp.org/channel.txt.html#channel-callback), where we can read this:

   > When "mode" is "json" or "js" the "msg" argument is the body
   > of the received message, converted to Vim types.

It doesn't say that the callback feature cannot work for JSON.

**Comment by lacygoill** [comment]
I think the issue comes from the ID number used by the Python server.  When Vim looks for the message of ID 2, it probably doesn't find any associated callback.  The callback is not bound to the sent message, but to the channel whose ID is 0.

From [`:help channel-use`](https://vimhelp.org/channel.txt.html#channel-use):

   > Vim will match the response with the request using the message ID.  Once the
   > response is received the callback will be invoked.  Further responses with the
   > same ID will be ignored.  If your server sends back multiple responses you
   > need to send them with ID zero, they will be passed to the channel callback.

   ...

   > When the process wants to send a message to Vim without first receiving a
   > message, it must use the number zero:
   >     [0,{response}]

Patch fixing the issue:
```diff
diff --git a/runtime/doc/channel.txt b/runtime/doc/channel.txt
index 39cb43c00..c2686e2df 100644
--- a/runtime/doc/channel.txt
+++ b/runtime/doc/channel.txt
@@ -101,7 +101,7 @@ Instead of giving a callback with every send call, it can also be specified
 when opening the channel: >
 	call ch_close(channel)
 	let channel = ch_open('localhost:8765', {'callback': "MyHandler"})
-	call ch_sendexpr(channel, 'hello!')
+	call ch_sendexpr(channel, 'hello again!')
 
 When trying out channels it's useful to see what is going on.  You can tell
 Vim to write lines in log file: >
diff --git a/runtime/tools/demoserver.py b/runtime/tools/demoserver.py
index 00fe8bfbc..bf6ad4d19 100644
--- a/runtime/tools/demoserver.py
+++ b/runtime/tools/demoserver.py
@@ -60,11 +60,11 @@ class ThreadedTCPRequestHandler(socketserver.BaseRequestHandler):
             # Send a response if the sequence number is positive.
             # Negative numbers are used for "eval" responses.
             if decoded[0] >= 0:
-                if decoded[1] == 'hello!':
+                if decoded[1] == 'hello!' or decoded[1] == 'hello again!':
                     response = "got it"
                 else:
                     response = "what?"
-                encoded = json.dumps([decoded[0], response])
+                encoded = json.dumps([0 if decoded[1] == 'hello again!' else decoded[0], response])
                 print("sending {0}".format(encoded))
                 self.request.sendall(encoded.encode('utf-8'))
         thesocket = None
```

**Comment by brammool** [comment]
Thanks for picking up this old problem.  I am sure I tried that example and made sure it worked, but I suspect the code changed after that.  I will include the suggested change and tweak it a bit.
