### ISSUE TITLE
the double quotation of special marks is invalid with lubuntu 18

### ISSUE THREAD

**Issue by cs-pchsu** [vim/vim#3828]
I usually use double quotation of special marks to jump to position where last exited current buffer.
However, the double quotation of special marks is invalid with lubuntu 18.
After I reopen the vim with same file, use marks command to list all marks,  
the double quotation always show line one as the last line .

vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
Included patches: 1-1453

lsb_release -d
Description:    Ubuntu 18.04.1 LTS

**Comment by tonymec** [comment]
The current `defaults.vim` (for Vim 8.1, last change 2017 Jun 13) includes the following autocommand:
```vim
  " Put these in an autocmd group, so that you can revert them with:
  " ":augroup vimStartup | au! | augroup END"
  augroup vimStartup
    au!

    " When editing a file, always jump to the last known cursor position.
    " Don't do it when the position is invalid, when inside an event handler
    " (happens when dropping a file on gvim) and for a commit message (it's
    " likely a different one than last time).
    autocmd BufReadPost *
      \ if line("'\"") >= 1 && line("'\"") <= line("$") && &ft !~# 'commit'
      \ |   exe "normal! g`\""
      \ | endif

  augroup END
```
Thanks to this autocommand, Vim will always remember "where you were" in a file, **provided** that you use a viminfo to remember the marks (see `:help 'viminfo'`).

In earlier versions of Vim, the same autocommand used to be defined in group vimrcEx by the `vimrc_example.vim` and in still earlier versions (Vim 6 IIRC) you had to put it in your vimrc yourself. It is still mentioned by `:help last-position-jump` but if your vimrc sources the `vimrc_example.vim` (which in Vim 8.1 and possibly in 8.0 just sources the `defaults.vim`) you don't have to worry about it any further.

FWIW, when reporting supposed bugs (for any software, not only Vim), it is always advisable to check if they are still present in the latest version of the software. Vim 8.1.0 was published on 18 May 2018 and the latest version as of this writing is 8.1.784. See at http://users.skynet.be/antoine.mechelynck/vim/compunix.htm how to compile your own Vim on Unix-like systems.

**Comment by tonymec** [comment]
P.S. Of course, the above assumes that your Vim is compiled with `+eval`, `+autocmd` and `+viminfo`.

**Comment by cs-pchsu** [comment]
That's the compile option under lubuntu18

Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-NQEcoP/vim-8.0.1453=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -Wl,-E  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.26/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm

**Comment by chrisbra** [comment]
sorry, I am not sure I get what you are saying. Can you please show  a minimal example of what you do, what you see and what you expect? Thanks

**Comment by cs-pchsu** [comment]
Hi @chrisbra ,

Thank you for your attention.

The special marks like double quotation can help us remember the last line number when I close the vim.

Thus, if this function was work well, I could use '" or `" to jump to line of when I close the vim.

This function can not work in the lubutnu18, even I update the system.

**Comment by chrisbra** [comment]
yes I understood that. Please provide a minimal example that shows the issue.

**Comment by cs-pchsu** [comment]
After open file with vim, I use :marks to list the all marks.
The mark of  double quotation always show as below.

"      1    0 /*

**Comment by chrisbra** [comment]
that is not a minimal reproducing example and I cannot reproduce this. Please come up with a reproducible example starting from `vim --clean`. It might have also been fixed in between. Please try with the latest Vim version, before opening issues.

**Comment by chrisbra** [comment]
[patch 8.1.0034](https://github.com/vim/vim/releases/tag/v8.1.0034) looks related.

**Comment by chrisbra** [comment]
closing, assuming patch 8.1.0034 fixed it. If this is not fixed, please open a new issue with clear steps to reproduce. Thanks.
