### ISSUE TITLE
The quickfix window used too many buffer numbers

### ISSUE THREAD

**Issue by general0000** [vim/vim#3831]
1, I usually go to buffers with number+tab (mapped to number+<C-^>), it's convinent when buffer numbers are small;
2, But, I found that everytime quickfix window opens, the used buffer number is increased. And I often toggle the quickfix window.
3, How can I keep the buffer number of quickfix fixed ? Thanks!

**Comment by brammool** [comment]
What version of Vim are you using?  This might have been fixed in the last few months.

**Comment by vim-ml** [comment]
Hi,

On Sun, Jan 20, 2019 at 5:08 AM general0000 <vim-dev-github@256bit.org> wrote:
>
> 1, I usually go to buffers with number+tab (mapped to number+<C-^>), it's convinent when buffer numbers are small;
> 2, But, I found that everytime quickfix window opens, the used buffer number is increased. And I often toggle the quickfix window.
> 3, How can I keep the buffer number of quickfix fixed ? Thanks!
>

When the quickfix window is closed, the quickfix buffer is wiped out. When you
open a quickfix window again, a new quickfix buffer is created.

To retain the same quickfix buffer, the current behavior has to be changed to
not wipe out the buffer when the quickfix window is closed. As the current
behavior has been there for a long time, I am not sure whether changing
it now will break any of the existing Vim plugins that rely on the previous
behavior.

- Yegappan

**Comment by skywind3000** [comment]
so a new option can solve this:

    set quickfixreuse

when on, reuse the previous buffer if possible.

**Comment by brammool** [comment]
> so a new option can solve this:
> 
>     set quickfixreuse
> 
> when on, reuse the previous buffer if possible.

Having an option for this seems useles: Either it's possible to reuse
the buffer, then we can always do it, or we can't reuse the buffer, then
the option won't change antyhing.

-- 
Facepalm reply #9: "Speed up, you can drive 80 here" "Why, the cars behind us
are also driving 60"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
Since nothing should depend on the buffer number, we can wipe out the buffer and use the same number again later.  Just have to make sure the same autocommands are triggered.
We could also make the buffer unlisted instead of wiping it out.  It might work and be less "special", but there is a small chance it does cause trouble.  We could try it and think of anything that could go wrong, and if it doesn't work go for the first solution.

**Comment by general0000** [comment]
> What version of Vim are you using? This might have been fixed in the last few months.

1.   VIM 8.l (2018 May 18, compiled May 18 2018 18:36:07)
2.   Today I tried out the newest gvim_8.1.0829_x86.zip，and the problem also exists.
3.   And, there is no 'quickfixreuse' option in 8.1.0829 ?
4.   Unfortunately, sometimes 8.1.0829 crashed when ':AirlineRefresh' executed. I tried many times and VIM8.1 2018 is ok.
Thank you all .

**Comment by vim-ml** [comment]
Hi,

On Sun, Jan 27, 2019 at 4:17 AM general0000 <vim-dev-github@256bit.org> wrote:
>
> What version of Vim are you using? This might have been fixed in the last few months.
>
> VIM 8.l (2018 May 18, compiled May 18 2018 18:36:07)
> Today I tried out the newest gvim_8.1.0829_x86.zip，and the problem also exists.
> And, there is no 'quickfixreuse' option in 8.1.0829 ?
>
> Unfortunately, sometimes 8.1.0829 crashed when ':AirlineRefresh' executed. I tried many times and VIM8.1 2018 is ok.
>

Can you get a backtrace of this crash? You can run Vim under a debugger like GDB
and try to reproduce the crash. If you can come up with a list of
steps to reproduce
this crash (without many Vim plugins) that will be useful too.

- Yegappan

**Comment by chrisbra** [comment]
Note: There is no 'quickfixreuse' option yet. Also what exactly do you mean with the crash `::AirlineRefresh`. Please provide a backtrace (or at least exact steps how to reproduce the issue).

**Comment by general0000** [comment]
I got the steps to produce crash:
1)  This is my _vimrc content ( vim-plug + vim-airline only):
call plug#begin('$VIM/myplugs')
Plug 'vim-airline/vim-airline'
call plug#end()
map \<f7\> :AirlineRefresh<cr>
2) Continue pressing F7,  vim will crash soon.
@chrisbra  @vim-ml

**Comment by chrisbra** [comment]
cannot reproduce (using vim on linux in a terminal). Is this with gvim on Windows? Can you get a stack trace? See e.g. [this comment](https://github.com/vim/vim/issues/3873#issuecomment-458062817) (and do not strip the resulting binary. But on windows it might be a bit harder (and different) to get a proper stack trace.

**Comment by general0000** [comment]
Yeah, I use gvim on Windows.  I compiled a debug version and reproduced, the crash is here:
    static void
list_free_contents(list_T *l)
{
    listitem_T *item;

    for (item = l->lv_first; item != NULL; item = l->lv_first)
    {
	/* Remove the item before deleting it. */
	l->lv_first = item->li_next;    //  here the l->lv_first value is 0xdddddddd
The attach file is the stack trace.
[gvim_trace.txt](https://github.com/vim/vim/files/2812652/gvim_trace.txt)

**Comment by vim-ml** [comment]
Hi,

On Wed, Jan 23, 2019 at 12:14 PM Bram Moolenaar
<vim-dev-github@256bit.org> wrote:
>
> Since nothing should depend on the buffer number, we can wipe out the buffer
> and use the same number again later. Just have to make sure the same
> autocommands are triggered.  We could also make the buffer unlisted instead
> of wiping it out. It might work and be less "special", but there is a small
> chance it does cause trouble. We could try it and think of anything that
> could go wrong, and if it doesn't work go for the first solution.
>

I have created pull request #3902 to reuse the quickfix/location list
window buffer. Try this out and let me know if you see any issues.

https://github.com/vim/vim/pull/3902

- Yegappan

**Comment by general0000** [comment]
It works. Great! Thank you!
And I can't reproduce the crash with gvim_8.1.0877_x86.zip, was it solved?

**Comment by yegappan** [comment]
The pull request #3902 has been merged in patch 8.1.0877. Can this issue be closed now?

**Comment by brammool** [comment]
Let's assume this was fixed.  If there still is a problem, please create a new issue and describe it.
