### ISSUE TITLE
memory leak when assigning a:000 to a local variable

### ISSUE THREAD

**Issue by andymass** [vim/vim#3835]
It seems as though reference counting is done incorrectly for `a:000` and memory is leaked when local references are made to it.

To reproduce:

```vim
function s:dofoo(first, ...)
	let l:opts = a:000
	" unlet l:opts 
endfunction

for x in range(10000)
	call s:dofoo(10)
endfor
```

Run `watch 'cat /proc/$(pgrep vim | tail -1)/status | grep Vm'` and `vim --clean test.vim`

Repeatedly do `:so %` and watch the VmRSS shoot up rapidly.  Uncomment the `unlet` and the problem disappears.

Originally reported at https://github.com/vim-airline/vim-airline/issues/1858 ,  https://github.com/vim-airline/vim-airline/pull/1859

**Comment by brammool** [comment]
Andy Massimino wrote:


> It seems as though reference counting is done incorrectly for `a:000`
> and memory is leaked when local references are made to it.
> 
> To reproduce:
> 
> ```vim
> function s:dofoo(first, ...)
> 	let l:opts = a:000
> 	" unlet l:opts 
> endfunction
> 
> for x in range(10000)
> 	call s:dofoo(10)
> endfor
> ```
> 
> Run `watch 'cat /proc/$(pgrep vim | tail -1)/status | grep Vm'` and
> `vim --clean test.vim`
> 
> Repeatedly do `:so %` and watch the VmRSS shoot up rapidly.  Uncomment
> the `unlet` and the problem disappears.
> 
> Originally reported at
> https://github.com/vim-airline/vim-airline/issues/1858 ,
> https://github.com/vim-airline/vim-airline/pull/1859

I cannot see a leak with valgrind.  Perhaps it's because the garbage
collector doesn't kick in?  Try calling garbagecollect() in the loop
once in a while

-- 
Facepalm statement #6: "Estland is a fantasy place, just like Middle Earth and
Madagaskar"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dpelle** [comment]
It's not a memory leak in the sense that Vim loses track of memory.
Vim keeps track and eventually frees memory, so valgrind does
not show a leak. However, it does not look expected that memory
keeps growing as we iterate in this loop.

If I iterate a large number of times like this...
```
  function s:dofoo(first, ...)
      let l:opts = a:000
      " unlet l:opts
  endfunction

  for x in range(1000000)
      call s:dofoo(10)
  endfor
```
... then then memory keeps growing as the loop progresses
Eventually Vim uses several GiB of memory.  The memory is
released after the loop is finished.  Sourcing again, and memory
grows again.

Running it with Massif memory profiler, i.e. with:
```
valgrind --tool=massif ./vim --clean
```
I see that memory keeps growing linearly as the loop progress. 
At the peak usage (2 GiB in heap), I see almost all memory allocated
by vim comes from this call stack:
```
lalloc (misc2.c:984)
call_func (userfunc.c:725)
get_func_tv (userfunc.c:455)
ex_call (userfunc.c:3173)
do_cmdline (ex_docmd.c:2523)
do_source (ex_cmds2.c:4620)
cmd_source (ex_cmds2.c:4229)
do_cmdline (ex_docmd.c:2523)
nv_colon (normal.c:5389)
normal_cmd (normal.c:1121)
main_loop (main.c:1374)
vim_main2 (main.c:914)
main (main.c:441)
```

**Comment by brammool** [comment]
Dominique wrote:

> It's not a memory leak in the sense that Vim loses track of memory.
> Vim keeps track and eventually frees memory, so valgrind does
> not show a leak. However, it does not look expected that memory
> keeps growing as we iterate in this loop.
> 
> If I iterate a large number of times like this...
> ```
>   function s:dofoo(first, ...)
>       let l:opts = a:000
>       " unlet l:opts
>   endfunction
> 
>   for x in range(1000000)
>       call s:dofoo(10)
>   endfor
> ```
> ... then then memory keeps growing as the loop progresses
> Eventually Vim uses several GiB of memory.  The memory is
> released after the loop is finished.  Sourcing again, and memory
> grows again.
> 
> Running it with Massif memory profiler, i.e. with:
> ```
> valgrind --tool=massif ./vim --clean
> ```
> I see that memory keeps growing linearly as the loop progress. 
> At the peak usage (2 GiB in heap), I see almost all memory allocated
> by vim comes from this call stack:
> ```
> lalloc (misc2.c:984)
> call_func (userfunc.c:725)
> get_func_tv (userfunc.c:455)
> ex_call (userfunc.c:3173)

What happens is that the function creates a cyclic reference: the local
variables contain a reference to the function call instance.  The only
way to detect this is by running the garbage collector.

What we can do is that after making a copy of the a:000 a number of
times, then call the garbage collector.

I notice that with a large range Vim runs out of memory and crashes.
It's worth checking the return value of alloc(), then we can return
gracefully and not crash.

-- 
Linux is just like a wigwam: no Windows, no Gates and an Apache inside.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
