### ISSUE TITLE
How to set vim so that relative numbers could count from 1 (current line) not 0?

### ISSUE THREAD

**Issue by xylinkun** [vim/vim#3836]
The question in this [https://stackoverflow.com/questions/33582177/how-to-let-vim-use-relative-line-numbers-counting-from-1-instead-of-0] is exactly what I want to ask.

For example: I want to delete from current line to a line with a relative number 21, I have to add 1 to the relative number 21, and then type `22dd`.

If I can set Vim counting relative numbers from 1 not 0, the problem above will disappear.

**Comment by chrisbra** [comment]
not possible. 
As mentioned in the linked question, you can use a plugin like RltvNmbr.vim or my DynamicSigns plugin (which is not yet refactored to make use of the sign VimScript API).
please ask user questions on vi.stackexchange.com or use the vim-use mailinglist.
