### ISSUE TITLE
Cmdline window broken when invoked with completion active

### ISSUE THREAD

**Issue by bfredl** [vim/vim#3838]
Use vim master with "huge" build.

1) Invoke insert mode completion  with lots of suggestions so the popupmenu covers the entire height of the screen (e g do tag completion based on a single letter only)
2) type `<c-r>=<c-f>` ( `=` cmdline window)

Now cmdline window is entered, but it is covered by the popupmenu and unusable. Even after redraw the popupmenu still covers the cmdline window.

**Comment by brammool** [comment]
Bjorn Linse wrote:

> Use vim master with "huge" build.
> 
> 1) Invoke insert mode completion  with lots of suggestions so the popupmenu covers the entire height of the screen (e g do tag completion based on a single letter only)
> 2) type `<c-r>=<c-f>` ( `=` cmdline window)
> 
> Now cmdline window is entered, but it is covered by the popupmenu and
> unusable. Even after redraw the popupmenu still covers the cmdline
> window.

Oh, that's a weird sequence of events.  But it should not result in an
unusuable situation.

I can fix it, and even put the cursor back in position, but the popup
menu remains closed.  Oh well.

-- 
   They now pass three KNIGHTS impaled to a tree.  With their feet off the
   ground,  with one lance through the lot of them, they are skewered up
   like a barbecue.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
