### ISSUE TITLE
Forward / backward search weirdness

### ISSUE THREAD

**Issue by andreas-gruenbacher** [vim/vim#3839]
While trying to search in a file, I noticed that I can forward search with a command like `/a\/\?c<cr>` to match both `ac` and `a/c`, but I cannot specify the same pattern in a backward search because `?` apparently cannot be escaped: commands like `?a/\?c<cr>` or similar won't work. This is with vim 8.1, but I expect this to be a general problem. Any thoughts?

**Comment by Houl** [comment]
Vim's help is aware of it: `:h /\?`.  There is an alternative item `:h /\=` which you may want to use instead.  Actually `\=` was there first and `\?` was added later.

**Comment by andreas-gruenbacher** [comment]
Yes, that works. Thank you.

**Comment by k-takata** [comment]
Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. Closing.

**Comment by andreas-gruenbacher** [comment]
Actually this has a usability aspect too: I frequently end up searching for patterns I have recently searched for. Once I enter `/`or `?`, I can browse through the previous search patterns with `<up>` and `<down>`. Let's say the pattern I want to search for is `a\/\?c`, from a previous forward search. That pattern will work for another forward search, but it will **not** work for a backward search. That's rather surprising.
