### ISSUE TITLE
gzip#read occur error while read long line gz file

### ISSUE THREAD

**Issue by epheien** [vim/vim#3840]
Generate a big and long line json gz file
```python
#!/usr/bin/env python3
import uuid
import json
import gzip
d = {}
for i in range(10000):
    d[str(uuid.uuid4())] = str(uuid.uuid4())
with gzip.open('abc.json.gz', 'wb') as fp:
    fp.write(json.dumps(d).encode())
```

then open it with vim
`vim abc.json.gz`

found error
> "abc.json.gz" [noeol][CR missing][dos] 2094L, 439237C
Error detected while processing function gzip#read:
line   47:
Error: Could not read uncompressed file
Error: Could not read uncompressed file

**Comment by dpelle** [comment]
I ran your python script and I could open `abc.json.gz` without problem.
So Vim works fine for me. I'm using vim-8.1.789 (huge, Linux x86_64).
What version of Vim do you use?

Can you try with the `--clean` option like this to make sure
that it's not another plugin that breaks it?
```
$ vim --clean -c 'runtime plugin/gzip.vim' -c 'e abc.json.gz'
```

**Comment by epheien** [comment]
> I ran your python script and I could open `abc.json.gz` without problem.
> So Vim works fine for me. I'm using vim-8.1.789 (huge, Linux x86_64).
> What version of Vim do you use?
> 
> Can you try with the `--clean` option like this to make sure
> that it's not another plugin that breaks it?
> 
> ```
> $ vim --clean -c 'runtime plugin/gzip.vim' -c 'e abc.json.gz'
> ```

It work if I run with your command.
I will find out what plugin is causing this problem.

Please close this issue.
