### ISSUE TITLE
Specfile filetype plugin is not working properly

### ISSUE THREAD

**Issue by TomasKorbar** [vim/vim#3842]
Hi,
spec filetype plugin is not expanding variables.
Steps to reproduce:
1. change type of file from .spec.txt to .spec
[reproduce.spec.txt](https://github.com/vim/vim/files/2783943/reproduce.spec.txt)
2. open spec file in vim
3. press \c and enter your name
expected result:
new changelog message is created with version info 1.5-1
actual result:
new changelog message is created with version info 1.-1

Fedora bug: https://bugzilla.redhat.com/show_bug.cgi?id=1297746

**Comment by chrisbra** [comment]
closing for #3844
