### ISSUE TITLE
Specfile filetype plugin should not copy variable names of undefined variables to changelog message

### ISSUE THREAD

**Issue by TomasKorbar** [vim/vim#3843]
Hi,
In my opinion it is better to not mention variable names of variables which are undefined in specfile in changelog message. Take for example variable ?dist which is defined during a build and if you are using changelog generation then you have to remove it from messages version info manually every time.
Let me please know what you think about this.

**Comment by chrisbra** [comment]
this is very vague. Please discuss with the runtime file maintainer, mentioned at the top of the file. Closing.
