### ISSUE TITLE
delete() do not work when there is space in path

### ISSUE THREAD

**Issue by wsdjeg** [vim/vim#3849]
In windows os, when there is a space in the file name, delete() do not work when escape the file name.

```
:e f\ b.txt
:w 
:echo delete(fnameescape(expand('%:p')))
" you will see 0, and failed to delete file
:echo delete(expand('%:p'))
" this works well
```

so we do not need to escape the file name when using delete() function?

ref: https://github.com/SpaceVim/SpaceVim/pull/2490

**Comment by brammool** [comment]
fnameescape() is for escaping file names used on the command line.  Thus it works as intended.
