### ISSUE TITLE
XML indent jumps to right on tag closing

### ISSUE THREAD

**Issue by mismosmi** [vim/vim#3850]
I'm using 8.1.751. 

Since my last update, when writing xml the default indentation file turns
```xml
<a>
    <b>
```
into
```xml
<a>
        <b>
```
and with each closing tag it moves further to the right:
```xml
<a>
                <b>>>
```
I tried without any plugins or other config and very much hope this is not my own fault and this is the right place to report it, sorry if it is not.
the current maintainer of the file is @chrisbra in case that helps.

**Comment by chrisbra** [comment]
Please open am issue in the upstream repository

**Comment by mismosmi** [comment]
Ummmm,

I'm really sorry that I have to ask again but what upstream repo?

I thought this was the official vim repo, what more upstream is there? Should I write an email to bram?

**Comment by chrisbra** [comment]
Look at the header of the runtime file. I think it might be this problem https://github.com/chrisbra/vim-xml-ftplugin/issues/4

**Comment by mismosmi** [comment]
Ahh there it is.
