### ISSUE TITLE
exit_cb handle will not be called when cmd is not executable

### ISSUE THREAD

**Issue by wsdjeg** [vim/vim#3851]
here is simple test script:

```vim
function! Exit(...) abort
    echom string(a:000)
endfunction

if has('nvim')
    call jobstart('noexistcmd', {'on_exit':function('Exit')})
else
    call job_start('noexistcmd', {'exit_cb':function('Exit')})
endif
```

in neovim, you will see follow:

```
[6, 1, 'exit']
```

but in vim8, nothing is printed

EDIT:

my os is windows 7, and vim version is 8.1.664

**Comment by mattn** [comment]
This works as expected. job_start does not start command with shell. See `:help job_start`. i.e. process is not started. Thus, exit_cb is not called.

**Comment by brammool** [comment]
Wang Shidong wrote:

> here is simple test script:
> 
> ````vim
> function! Exit(...) abort
>     echom string(a:000)
> endfunction
> 
> if has('nvim')
>     call jobstart('noexistcmd', {'on_exit':function('Exit')})
> else
>     call job_start('noexistcmd', {'exit_cb':function('Exit')})
> endif
> ```
> 
> 
> in neovim, you will see follow:
> 
> ```
> [6, 1, 'exit']
> ```
> 
> but in vim8, nothing is printed

That is correct, if the job never started it can't exit.
job_status() can be used to check for the situation, it will return
"fail".

The exit callback is normally used to process the job output and/or
cleanup.  Handling the job to never start is something completely
different.

-- 
   GALAHAD turns back.  We see from his POV the lovely ZOOT standing by him
   smiling enchantingly and a number of equally delectable GIRLIES draped
   around in the seductively poulticed room.  They look at him smilingly and
   wave.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by wsdjeg** [comment]
I do not agree with this, as when use job_start to run a command, this action is a process. if the command is not executable, we should get the exit_data (1), then in the exit_cn handle function, we can check the exit data. if it is 1, then we can tell user, why the job is failed. I know we can use job_status() to check the job, but if the the job run successfully, no need to add extra code to check the job status.

**Comment by mattn** [comment]
No. neovim use shell to execute command. When the shell is exited, the exit_cb is called. But vim don't use  shell. That's all.

**Comment by mattn** [comment]
However, vim can raise exception when failed to execute the command.

**Comment by mattn** [comment]
At least, you must check `job_status(job)` after `job_start(...)`.

**Comment by wsdjeg** [comment]
got it, thanks. I will try to fix my script.

________________________________
wsdjeg@outlook.com

**Comment by skywind3000** [comment]
If you insist, you can simulate nvim's behavior by:

    call job_start([&shell, &shellcmdflag, 'You command here'], {...})

If your command doesn't exist, bash will still be executed and returns an error code.
