### ISSUE TITLE
:substitute from within :normal breaks :s_c flag confirmation

### ISSUE THREAD

**Issue by inkarkat** [vim/vim#3862]
I have a mapping that performs a `:substitute///gc` command, asking the user for confirmation on each match. In order to reuse that mapping (or to make it repeatable with `.`), other customizations invoke the original mapping via `:normal` [1]. I noticed that the confirmation queries don't happen then, and the whole substitution is aborted (withour error or beeping). I tried wrapping the call with `inputsave()` / `inputrestore()`, but that doesn't help.

I see this behavior in the latest Vim (8.1.744) and in previous versions (checked down to 7.0). Though not a regression, it's an annoying inconsistency that prevents useful functionality, and I hope there's a small tactical fix that makes `:s_c` recognize the runtime conditions of `:normal` somehow.

### Reproduction

    exe "normal! :substitute/^/x/c\<CR>"

This should ask `replace with x (y/n/a/q/l/^E/^Y)?`, but instead it does nothing.

---

[1] The latest [repeat.vim plugin](https://github.com/tpope/vim-repeat) uses `feedkeys(..., 'ni')` (which is not affected by the problem) for recent Vim versions, and `:normal` only as a fallback. That has other drawbacks, like not being able to programmatically repeat multiple times due to the asynchronicity of `feedkeys()`. And with `feedkeys('', 'x')`, the problem occurs there, too.

**Comment by lacygoill** [comment]
According to `:h :norm`:

> {commands} should be a complete command.  If
> {commands} does not finish a command, the last one
> will be aborted as if &lt;Esc> or &lt;C-C> was typed.

So, I guess that `:norm` considers `:s/pat/rep/c` as an incomplete command because it still requires the user input, and aborts as if `Esc` had been typed.

I agree with you, it would be nice if `:norm` was able to run `:s/pat/rep/c`.

I think the same issue exists with any command which requires the user input, like `z=` for example.

---

In the meantime, I use `feedkeys()` with the flags `in` as you mentioned in your post, and I don't use `vim-repeat`, but an opfunc. Here's an example:

    nno  <silent>  z=  :<c-u>set opfunc=<sid>my_z_equal<cr>g@l
    fu! s:my_z_equal(_) abort
        let spell_save = &l:spell
        try
            setl spell
            call feedkeys('z=', 'in')
        catch
        finally
            call timer_start(0, {-> execute('let &l:spell = '.spell_save)})
        endtry
    endfu

It seems to work, and the `z=` mapping is repeatable, but I admit I haven't tested it that much.

**Comment by inkarkat** [comment]
Great input on other interactive commands being affected by this as well; this increases the importance of a fix.

It don't follow your interpretation of `:h :normal`; it think _complete command_ just means that the key sequence must end in something that Vim can execute (and then return to normal mode after it). As the `:substitute` ends with `<CR>`, that's given there.

I think what's missing is an implementation that user queries inside internal Vim commands (as in `:s_c` and `z=`) need to consider the circumstances of running under `:normal`. For mappings, there's `inputsave()` for that; a similar internal implementation (that may be as simple as changing an internal flag; I'm unfortunately not familiar with internals) is needed here.

**Comment by inkarkat** [comment]
On 26-Jan-2019 16:41 +0100, Bram Moolenaar wrote:

> You are mistaken, this is not a bug but exactly how it is supposed to
> work.
> 
> The :normal command executes characters as if you type them.  And the
> confirmation of the substitute is just another character to type.  Thus
> that must be part of the :normal command argument.
> 
> Consider the "f" command.  It takes an argument, the character to find.
> So the user has to type that.  But ":normal fx" includes that typed
> character, Vim won't prompt the user.
> 
> The implementation puts the argument of :normal in the input buffer and
> executes until it is empty.  It's impossible to tell if getting the next
> character should NOT come from the input buffer, but ask the user
> directly.

Okay, that makes sense. Coming from the `:s///c` command, to automate the selection of matches, I think nobody would do it with

    execute "normal! :s/./\\u&/gc\<CR>ynnyynynyq"

but instead use a sub-replace-expression to select certain matches (though the above also works), so this use case didn't occur to me. But of course for commands like `fx`, that is something that should not prompt the user. As all queries internally use the same input mechanism, Vim cannot decide what is wanted. These details weren't clear to me; thank you for your great explanation!

> The only thing we could do is that when the input buffer is empty,
> instead of getting back to the Normal state, just leave it whereever we
> are and get further characters from the user.  This is very tricky to
> implement, since :normal has put typeahead to the side, and we are
> anywhere in the code waiting or a character.  We can't really restore
> the typeahead there.  Thus we would get stuck until the Normal mode
> command finishes, and then restore typeahead.  It's a bit dangerous, but
> it might work.
> 
> Anyway, this only solves the problem if the command that you want to
> prompt the user is at the very end of the :normal command.

Intuitively, this change in behavior would make sense (to me). But if you mean by _very tricky_ "I'm not gonna attempt to implement this", I can fully understand :-)

> I think there are other solutions instead of using :normal.

Yes, the solution that works is `feedkeys(..., 'ni')`, as mentioned by @lacygoill. As I've said, what I don't like about this solution is that it reverses the execution order (`:norm A | :norm B` executes `AB`, whereas `feedkeys(A) | feedkeys(B)` executes `BA`), but I can fix the ordering by inserting a `:call feedkeys('', 'x')` in between.

I think we can leave it at that. It's a very advanced topic, and now it's documented here.
