### ISSUE TITLE
The help doc for indentkeys-format lists the wrong default

### ISSUE THREAD

**Issue by bruce-hill** [vim/vim#3882]
The documentation for `:h indentkeys-format` lists the default indentkeys value as `0{,0},0),:,0#,!^F,o,O,e`, but it's actually `0{,0},:,0#,!^F,o,O,e` (the actual value has no `0),`). The help documentation for `:h indentkeys` has the correct default, which you can verify by running `:set indentkeys`. The documentation should have the correct default listed, as well as delete the line explaining `0)`.

To reproduce:
```
vim -N -u NONE
:h indentkeys-format
:set indentkeys
```

**Comment by andymass** [comment]
The documentation is surely confusing here, but the string listed at `:h indentkeys-format` is actually for `cinkeys` not `indentkeys`, which have different defaults.  This should be made more explicit in the documentation.

**Comment by bruce-hill** [comment]
@andymass Oh, that's good to know. Yeah, it would be less confusing if it said "For example, the default for cinkeys is...".

**Comment by brammool** [comment]
Andy Massimino wrote:

> The documentation is surely confusing here, but the string listed at
> `:h indentkeys-format` is actually for `cinkeys` not `indentkeys`,
> which have different defaults.  This should be made more explicit in
> the documentation.

Perhaps the defaults should be made the same?  The only difference is
that 'indentkeys' is missing the "0)" part.  I can't think of a reason
why.

-- 
"It's so simple to be wise.  Just think of something stupid to say
and then don't say it."        -- Sam Levenson

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bruce-hill** [comment]
I think it would make sense to include "0)" in the defaults for indentkeys. It would also probably make sense to have "0]" as well, since I would assume any line starting with a "]" would likely want to be dedented. But maybe that's a whole other can of worms...

**Comment by brammool** [comment]
> I think it would make sense to include "0)" in the defaults for
> indentkeys. It would also probably make sense to have "0]" as well,
> since I would assume any line starting with a "]" would likely want to
> be dedented. But maybe that's a whole other can of worms...

I think adding "0]" should be fine, since both "0}" and "0)" are already
there.

-- 
CRONE:  Who sent you?
ARTHUR: The Knights Who Say Ni!
CRONE:  Aaaagh!  (she looks around in rear) No!  We have no shrubberies here.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
