### ISSUE TITLE
Bug with listchars set to display nbsp only

### ISSUE THREAD

**Issue by rakus** [vim/vim#3889]
When `set listchars=nbsp:X` (replace `X` with char of your choice), non-breaking spaces are not highlighted, but when I `set listchars=nbsp:X,trail:Y` or `set listchars=nbsp:X,space:Y` it works.

The following patch fixes it:

```diff
diff --git a/src/screen.c b/src/screen.c
index 1370773..815e6be 100644
--- a/src/screen.c
+++ b/src/screen.c
@@ -3498,7 +3498,7 @@ win_line(

     if (wp->w_p_list)
     {
-       if (lcs_space || lcs_trail)
+       if (lcs_space || lcs_trail || lcs_nbsp)
            extra_check = TRUE;
        /* find start of trailing whitespace */
        if (lcs_trail)
```

I extended `test_listchars.vim` to check for the bug:

```diff
diff --git a/src/testdir/test_listchars.vim b/src/testdir/test_listchars.vim
index 4899f59..2fe3981 100644
--- a/src/testdir/test_listchars.vim
+++ b/src/testdir/test_listchars.vim
@@ -90,6 +90,30 @@ func Test_listchars()
              \ '.....h>-$',
              \ 'iii<<<<><<$', '$'], l)

+
+
+  " test nbsp
+
+  normal ggdG
+
+  set listchars=nbsp:X,trail:Y
+  set list
+  " Non-breaking space
+  let nbsp=nr2char(0xa0)
+  call append(0, [ ">".nbsp."<" ])
+
+  let expected = [ '>X< ' ]
+
+  redraw!
+  call cursor(1, 1)
+  call assert_equal([expected[0]], ScreenLines(1, virtcol('$')))
+
+  set listchars=nbsp:X
+  redraw!
+  call cursor(1, 1)
+  call assert_equal([expected[0]], ScreenLines(1, virtcol('$')))
+
+
   enew!
   set listchars& ff&
 endfunc
```

**Comment by rakus** [comment]
Here as one patch, and test slightly cleaned up:
```
diff --git a/src/screen.c b/src/screen.c
index 1370773..815e6be 100644
--- a/src/screen.c
+++ b/src/screen.c
@@ -3498,7 +3498,7 @@ win_line(
 
     if (wp->w_p_list)
     {
-	if (lcs_space || lcs_trail)
+	if (lcs_space || lcs_trail || lcs_nbsp)
 	    extra_check = TRUE;
 	/* find start of trailing whitespace */
 	if (lcs_trail)
diff --git a/src/testdir/test_listchars.vim b/src/testdir/test_listchars.vim
index 4899f59..408d28c 100644
--- a/src/testdir/test_listchars.vim
+++ b/src/testdir/test_listchars.vim
@@ -90,6 +90,26 @@ func Test_listchars()
 	      \ '.....h>-$',
 	      \ 'iii<<<<><<$', '$'], l)
 
+  " test nbsp
+  normal ggdG
+
+  set listchars=nbsp:X,trail:Y
+  set list
+  " Non-breaking space
+  let nbsp=nr2char(0xa0)
+  call append(0, ">".nbsp."<")
+
+  let expected = '>X< '
+
+  redraw!
+  call cursor(1, 1)
+  call assert_equal(expected, ScreenLines(1, virtcol('$')))
+
+  set listchars=nbsp:X
+  redraw!
+  call cursor(1, 1)
+  call assert_equal(expected, ScreenLines(1, virtcol('$')))
+
   enew!
   set listchars& ff&
 endfunc
```

**Comment by rakus** [comment]
Sorry, bug in previous post (never edit in one copy of the code and test in the other :-( ):
```
diff --git a/src/screen.c b/src/screen.c
index 1370773..815e6be 100644
--- a/src/screen.c
+++ b/src/screen.c
@@ -3498,7 +3498,7 @@ win_line(
 
     if (wp->w_p_list)
     {
-	if (lcs_space || lcs_trail)
+	if (lcs_space || lcs_trail || lcs_nbsp)
 	    extra_check = TRUE;
 	/* find start of trailing whitespace */
 	if (lcs_trail)
diff --git a/src/testdir/test_listchars.vim b/src/testdir/test_listchars.vim
index 4899f59..0b70663 100644
--- a/src/testdir/test_listchars.vim
+++ b/src/testdir/test_listchars.vim
@@ -90,6 +90,26 @@ func Test_listchars()
 	      \ '.....h>-$',
 	      \ 'iii<<<<><<$', '$'], l)
 
+  " test nbsp
+  normal ggdG
+
+  set listchars=nbsp:X,trail:Y
+  set list
+  " Non-breaking space
+  let nbsp=nr2char(0xa0)
+  call append(0, ">".nbsp."<")
+
+  let expected = '>X< '
+
+  redraw!
+  call cursor(1, 1)
+  call assert_equal([ expected ], ScreenLines(1, virtcol('$')))
+
+  set listchars=nbsp:X
+  redraw!
+  call cursor(1, 1)
+  call assert_equal([ expected ], ScreenLines(1, virtcol('$')))
+
   enew!
   set listchars& ff&
 endfunc
```

**Comment by brammool** [comment]
Ralf Schandl wrote:

> When `set listchars=nbsp:X` (replace `X` with char of your choice), non-breaking spaces are not highlighted, but when I `set listchars=nbsp:X,trail:Y` or `set listchars=nbsp:X,space:Y` it works.
> 
> The following patch fixes it:

Thanks!


-- 
Q: What do you call a fish without an eye?
A: fsh!
Q: What do you call a deer with no eyes?
A: no eye deer.
Q: What do you call a deer with no eyes and no legs?
A: still no eye deer.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
Ralf Schandl wrote:

> Sorry, bug in previous post (never edit in one copy of the code and
> test in the other :-( ):

I already included the patch, did I miss anything?


-- 
When I look deep into your eyes, I see JPEG artifacts.
I can tell by the pixels that we're wrong for each other.  (xkcd)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by rakus** [comment]
brammool wrote:

> >  Sorry, bug in previous post (never edit in one copy of the code and
> > test in the other :-( ):

> I already included the patch, did I miss anything?

No, your commit is correct. Were missing `[]` in `test_listchars.vim`, but you fixed it in the commit. Otherwise the test would fail.

Thanks,
Ralf
