### ISSUE TITLE
Unexpected return value when open the same file inside vim

### ISSUE THREAD

**Issue by 5hadowblad3** [vim/vim#3891]
Hi,
Recently I find that there is weired thing when I open a file, and then inside vim using
`!vim **same file**`
<img width="932" alt="image" src="https://user-images.githubusercontent.com/7632714/52102498-ad997a80-261b-11e9-9a86-e6e90410e5c2.png">

It pops up the warning windows since it has swp file and when I press q to quit, the shell return code is 1. Afterward the vim windows may behave abnormally and may still need to close twice.
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/7632714/52102471-8cd12500-261b-11e9-8bb1-31f34a9a50a6.png">

My system is 
<img width="382" alt="image" src="https://user-images.githubusercontent.com/7632714/52102566-1c76d380-261c-11e9-8aa0-73b5cbb730b6.png">
<img width="276" alt="image" src="https://user-images.githubusercontent.com/7632714/52102583-37494800-261c-11e9-9de7-bf69a946e714.png">

The attachment is the input file.

I wonder what happen with it. Thx.

[input.zip](https://github.com/vim/vim/files/2820071/input.zip)

**Comment by chrisbra** [comment]
works here. From your screenshot it is not clear what exactly you are experiencing here.

Also, please note, using `:!vim` is kind of silly, so closing.
