### ISSUE TITLE
CursorLineNr highlight wrong when soft-wrapping a line

### ISSUE THREAD

**Issue by bstaletic** [vim/vim#3893]
Steps to reproduce:

- `vim --clean`
- `set number relativenumber`
- `o<Esc>200ia`
  - One empty line and one that wraps
- `hi CursorLineNr term=bold ctermfg=73 ctermbg=236 guifg=#5fafaf guibg=#303030`
- `k`

Expected outcome:

- First line's number column is highlighted according to `hi CursorLineNr`.
- Second line's number column (for both, second and third visual line) is highlighted according to `hi LineNr`.

Actual outcome:

- First line's number column is highlighted according to `hi CursorLineNr`, as expected.
- Second visual line's number column is highlighted according to `hi LineNr`, as expected.
- Third visual line's number column is highlighted according to `hi CursorLineNr` instead of `hi LineNr`.

**Comment by protist** [comment]
I can confirm this bug on my system with the following version:
```
$ vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep 29 2019 22:27:49)
Included patches: 1-2102
Compiled by Arch Linux
Huge version with GTK3 GUI.  Features included (+) or not (-):
```

Here is a screenshot showing the problem. The cursor is on the first line. The line numbers of the first two lines are highlighted as expected. The third line should look like the second, but instead looks like the first.
![bug screenshot](https://i.imgur.com/kYGwEaD.png)

If I run `:syntax sync fromstart`, this fixes the problem, as long as my cursor is on a "single-line" line. However, if it is on a "overflowing" line, the buggy highlighting for that line will persist after navigating up or down.

**Comment by chrisbra** [comment]
That is a bit nasty, since it covers the details of `win_line()`. The thing is, to minimize the amount of redrawing involved, Vim will only redraw the number column. So that performance is not too much affected. So it basically calls the `win_line()` function with the parameter `number_only=TRUE`. Now in that case, the redraw function will break out early as soon as the number column has been drawn, however in your case, it should actually loop until the wrapping occurred to also change the highlighting in the number column. 

I really do not like to touch the `win_line()` function too much, since it is a bit complex. However with the following minimal patch the behaviour seems to be fixed. The patch is a kind of bad style, since it uses goto, but it was the easiest solution I could think of, without having to add a `!number_column` into each condition. Let me know what you think.

See this patch here: 
~~https://github.com/chrisbra/vim/commit/4d8c734e6d60aaf2d9f37c589e657be35640f012~~
this one had a small typo in it. I actually meant this one: https://github.com/chrisbra/vim/commit/0e3658c8d42a2ee63dba77e0f64ce7f396145fb5

**Comment by chrisbra** [comment]
updated patch: https://github.com/chrisbra/vim/commit/18c63e9591a89f58f66d71d96a4ca69a16f20333

**Comment by protist** [comment]
@chrisbra Your patch wouldn't apply to the latest stable release, so I tested the commit directly instead. I attempted to repeat the commands given in the first post, but after the `hi` command, none of the numbers were highlighted at all.

EDIT: I reverted to the stable release to confirm highlighting still worked (which it did). I also noticed that after the `set number relativenumber` command, the number in the left margin for the currently-selected line was underlined. When I tested your commit, that default underline was also missing.

**Comment by vim-ml** [comment]
Hi,

On Do, 24 Okt 2019, Sihera Andre wrote:

> 
>    Error detected while processing function <SNR>13_Highlight_Matching_Pair:
>    line   97:
>    E475: Invalid argument: 0
> 
> I have traced this to:
> 
>    /usr/local/share/vim/plugin/matchparen.vim
> 
> and this code:
> 
>    try
>      let [m_lnum, m_col] = searchpairpos(c, '', c2, s_flags, s_skip, 
> stopline, timeout)
>    catch /E118/
> 

[...]

> I have just performed upgrades of my Ubuntu systems from 15.04 to
> 18.10. This has meant upgrading VIM from the latest build at the time
> 7.4.XXX to 8.1.2186 (sorry, previous version deleted so can't provide
> the precise version number). The vim runtime appears to be 8.0.1766.
> 
> SDK packages installed were:
> 
>    libncurses5-dev libgnome2-dev libgnomeui-dev libgtk2.0-dev
>    libatk1.0-dev libbonoboui2-dev libcairo2-dev libx11-dev
>    libxpm-dev libxt-dev
> 
> 8.1.2186 was built locally with "configure --with-features=huge".
> 

With patch 8.1.0112 Vim will throw an error, if the `skip` argument for 
the searchpair() function is not a string argument while previously Vim 
did ignore this error. This means the matchparen plugin needs to be 
updated to fix this bug. 

The problem could be either a local older version of the matchparen 
plugin below your ~/.vim directory or the system runtime files have not 
been updated yet. It looks like you build Vim yourself but are using the 
system provided runtime files. Try to install the runtime files that 
come with the source repository and un-install the packaged one from 
Ubuntu and it should work again.

See also here for more information:
https://github.com/vim/vim/issues/3225
https://vi.stackexchange.com/questions/18701

Best,
Christian
-- 
Bildung ist das was übrig bleibt, wenn man alles andere vergessen hat.

**Comment by chrisbra** [comment]
Yeah, there was commit 49474ca12236776bb56aeb9d39b that fixed a "bug", that CursorLineNr is now only used, if you do `:set cursorline cursorlineopt=number`. I liked the previous behaviour, but this has been changed. 

So to reproduce the issue, you need to do now:

    
    vim --clean
    set number relativenumber cursorline cursorlineopt=number,line
    o<Esc>200ia
    hi CursorLineNr term=bold ctermfg=73 ctermbg=236 guifg=#5fafaf guibg=#303030
    k

**Comment by protist** [comment]
Nice. Yes, I can confirm that the fix works well then. Thank you!

**Comment by chrisbra** [comment]
pushed a slightly fixed version to the new branch  `update_number_column_3893`: 
https://github.com/chrisbra/vim/tree/update_number_column_3893

Changes: should not error out in tiny version.

**Comment by chrisbra** [comment]
Can someone please check that the original problem still exists? I can't seem to verify it anymore. So I am not sure this patch is actually needed.

**Comment by bstaletic** [comment]
@chrisbra I have just tested on the latest master and I can't reproduce the behaviour I reported either. I'm fine with closing this.

Thanks for the effort anyway.

**Comment by chrisbra** [comment]
Perhaps at @brammool can at least merge the test, pasting here as diff:

```patch
diff --git a/src/testdir/dumps/Test_winline_rnu.dump b/src/testdir/dumps/Test_winline_rnu.dump
new file mode 100644
index 000000000..31d579ec5
--- /dev/null
+++ b/src/testdir/dumps/Test_winline_rnu.dump
@@ -0,0 +1,5 @@
+|1+8#5fafaf255#303030255| @2> +0#0000000#ffffff0@45
+| +0#af5f00255&@1|1| |a+0#0000000&@45
+| +0#af5f00255&@3|a+0#0000000&@45
+| +0#af5f00255&@3|a+0#0000000&@17| @27
+@32|1|,|0|-|1| @8|A|l@1|
diff --git a/src/testdir/test_display.vim b/src/testdir/test_display.vim
index f500dc789..a25d2cfe0 100644
--- a/src/testdir/test_display.vim
+++ b/src/testdir/test_display.vim
@@ -158,3 +158,26 @@ func Test_display_listchars_precedes()
   set list& listchars& wrap&
   bw!
 endfunc
+
+" Check that win_lines() works correctly with the number_only parameter=TRUE
+" should break early to optimize cost of drawing, but needs to make sure
+" that the number column is correctly highlighted.
+func Test_scroll_CursorLineNr_update()
+  CheckScreendump
+
+  let lines =<< trim END
+    hi CursorLineNr ctermfg=73 ctermbg=236
+    set nu rnu cursorline cursorlineopt=number
+    exe ":norm! o\<esc>110ia\<esc>"
+  END
+  let filename = 'Xdrawscreen'
+  call writefile(lines, filename)
+  let buf = RunVimInTerminal('-S '.filename, #{rows: 5, cols: 50})
+  call term_sendkeys(buf, "k")
+  call term_wait(buf)
+  call VerifyScreenDump(buf, 'Test_winline_rnu', {})
+
+  " clean up
+  call StopVimInTerminal(buf)
+  call delete(filename)
+endfunc

```

(Now I wanted to keep this open until @brammool includes the test, but he was too fast :/)

**Comment by protist** [comment]
A bit late, but I can also confirm the error is fixed in the latest master.
