### ISSUE TITLE
`g2T` goes back two tabs, but `g2t` doesn't go forward two tabs

### ISSUE THREAD

**Issue by Plotnus** [vim/vim#3897]
Incosistent behaviour.

I'd expect `g2t` and `g2T` to cancel eachother out when done one after the other.

I'm using gvim and `g2T` works as expected but `g2t` does not.

**Comment by tonymec** [comment]
This is as expected: see `:help gt` and `:help gT`.

`gt` with a count goes to the nth tabpage (where the first tab, at far left, has number one) while `gT` with a count goes back by n tabs, with wraparound if the number given is equal to or higher than the current tab number.

Only with no count does `gt` go to the next tab.

**Comment by chrisbra** [comment]
this has been discussed before and decided not to change to not break users expectations. Closing.
