### ISSUE TITLE
utf8 listchars not displayed when NLS is enabled

### ISSUE THREAD

**Issue by CorentinDeBoisset** [vim/vim#3903]
Tested on version 8.1.0850
OS: MacOS Mojave (10.14.2)

My `.vimrc` is the following (no packages or any other configuration):

```
scriptencoding utf-8
set encoding=utf-8

set listchars=tab:→\ ,nbsp:␣,trail:•,extends:⟩,precedes:⟨
set list
```

My environment concerning the locale is `LC_CTYPE=UTF-8`

When running vim built without the `--disable-nls` flag, the first character of a tab, the trailing spaces and the nbsp all show up as the `¿` character. Other UTF8 characters show up if they are actual characters from the file (for instance on the `set listchars` line of the vimrc)

With vim built with the flag, so without national language support, the characters show up fine.

Example:

```
# With NLS:
¿¿¿
¿       ¿
¿¿¿
```

```
# Without NLS
•••
→       →
␣␣␣
```

**Comment by tonymec** [comment]
I don't have this problem. What does your Vim answer if you do
```vim
:verbose setlocal fenc? fencs?
```
while editing your vimrc?

My Vim is built with `+multi_byte` and `+multi_lang` which I suppose means that NLS is enabled.

My vimrc is actually in UTF-8 and it includes
```vim
scriptencoding utf-8
```
near the top and
```vim
if exists('+list')
  set list
  if exists('+listchars')
    set lcs=eol:¶,tab:\|_,extends:>,precedes:<,conceal:*,nbsp:·
  endif
endif
```
lower down. In particular the Pilcrow sign (U+00B6) and the middle-dot (U+00B7) are coded in UTF-8 (two bytes each), not in Latin1, and they do appear where they should.

Here are the configure settings which I set by means of environment variables in the shell where I "make" this Vim executable:
```bash
export CONF_OPT_GUI='--enable-gui=gtk2'
export CONF_OPT_MULTIBYTE='--enable-multibyte'
export CONF_OPT_AUTOSERVE='--enable-autoservername'
export CONF_OPT_FEAT='--with-features=big'
export CONF_OPT_COMPBY='"--with-compiledby=antoine.mechelynck@gmail.com"'
```

Best regards,
Tony.

**Comment by k-takata** [comment]
> My environment concerning the locale is `LC_CTYPE=UTF-8`

This looks incorrect. Normally, it should be `LC_CTYPE=en_US.UTF-8`, etc.
Your default value of `'encoding'` might not be "utf-8" because of this.

> scriptencoding utf-8
> set encoding=utf-8

These two lines are wrong. They should be:

```
set encoding=utf-8
scriptencoding utf-8
```

`'encoding'` must be set properly before `scriptencoding`.
This matters when the default value of `'encoding'` is not "utf-8".

**Comment by chrisbra** [comment]
See also this:
https://blog.remibergsma.com/2012/07/10/setting-locales-correctly-on-mac-osx-terminal-application/

**Comment by CorentinDeBoisset** [comment]
Indeed, my environment was incorrect, and that fixed it.

Had to remove the option in the terminal that automatically sets the locale environment vars, and manually set `LANG=en_GB.UTF-8` in my .zshrc

Now it works fine, thanks !
