### ISSUE TITLE
rvim shell execution?

### ISSUE THREAD

**Issue by ajes** [vim/vim#3904]
I was able to escape to shell from rvim on Fedora 28:
https://asciinema.org/a/9CJBU7F8Qwbv4jNzMmpTramP4
It shouldn't be allowed, right?

**Comment by brammool** [comment]
> I was able to escape to shell from rvim on Fedora 28:
> https://asciinema.org/a/9CJBU7F8Qwbv4jNzMmpTramP4
> It shouldn't be allowed, right?

I suppose we should disallow python commands in rvim.
And probably all other interfaces as well.
It will reduce functionality, but it's impossible to restrict what a
user can do in Python.

-- 
BEDEVERE: Look!  It's the old man from scene 24 - what's he Doing here?
ARTHUR:   He is the keeper of the Bridge.  He asks each traveler five
          questions ...
GALAHAD:  Three questions.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
Patch  8.1.0881 fixes this.  I hope it doesn't break someone's script.
