### ISSUE TITLE
Opening a non-existent file should set 'modified'

### ISSUE THREAD

**Issue by josn0** [vim/vim#3908]
If you edit a existing file, then write it, nothing happens with it contents. Thus, the 'modified' var should be 'false'.
If you edit a non-existing file, then write it, the end result is that a file is created. This makes the created buffer (empty, but existing) in the editor different from the on-disk one (non-existing), and thus that buffer should start with it's 'modified' var set to 'true'.
I found this when editing a bunch of new files, one of them should be empty. After adding the appropriate contents, I realized that exiting the editor with ':xall' would not suffice.

**Comment by tonymec** [comment]
I cannot reproduce this.

`vim foobar` edits the non-existing file "foobar" which is of course empty. It is not set as `'modified'`.
If I leave Vim with `:x`, which writes the file only if modified, the file still does not exist on disk. IOW, the `nomodified` empty buffer was "the same" as the nonexistent disk file.
Of course, as soon as I enter data into the empty buffer, it becomes modified, and `:x` will write it.

If you edit any file, existing or not, and then write it, a write operation takes place, which can be seen by the fact that the file's modification date has been set to the date-time when you hit Return on the `:w` command. Whether or not the file has been set `'modified'` between reading and writing is irrelevant.

If you want to make sure that a write operation happens on all the files currently open in Vim, even empty `'nomodified'` ones, do not use `:xall` or even `:wall|qall` (which writes only modified buffers); use `:bufdo w|q` which will write every (listed) buffer then close it.

**Comment by brammool** [comment]
The 'modified' flag is about whether the buffer is modified, not about the file.

**Comment by josn0** [comment]
@brammool I would say: the 'modified' flag is about whether anything would change if I would 'write' the buffer, except for the timestamps. If I would 'open' a file in the editor, then 'write' it, the file would exist afterwards. That would certainly be a change when editing a non-existing file.
In essence, the file is created in the editor's namespace (a buffer editing that file is created), which is a modification compared to the filesystem's namespace..
Besides, the example of @tonymec : if you change the filename of a 'nomodified' buffer using the 'file' command, then 'x' or 'xall', it is not written, but silently(!) dropped. I would say: the 'file' command effectively is a modification of the new file, in the editor's namespace, and 'modified' should be set..

A buffer's modification status should not only regard it's contents, but also it's binding with a file in the filesystem. Thus, editing a non-existing file, or binding it to a file, should also be regarded a modification..

**Comment by tonymec** [comment]
Setting `'modified'` as soon as an empty buffer is opened would break existing behaviour; in particular it might leave spurious empty files all over the place when closing Vim; or if not, it would refuse to close Vim because empty [NoName] buffers would now be `'modified'`; and you know, or should know, how important backward compatibility is for Bram. Why, he even hesitated about the usual 123.456 format when adding floating-point arithmetic to Vim, because before that it was a valid string operation: 123.456 would mean (before floating-point) 123 . 456 i.e. "123" . "456" i.e. "123456", see the paragraph just above ":help float-pi".

If you want an empty buffer to be written, write it yourself.

Best regards,
Tony.
