### ISSUE TITLE
.vimrc for projects and their trees

### ISSUE THREAD

**Issue by renich** [vim/vim#3911]
I work in a lot of different projects, with different coding guidelines. We have the `set exrc` setting but it doesn't work if one opens a file on directory level lower than where the `.vimrc` file is. 

For example:

```
project/
    .vimrc
    files/
        my-file.src
```
If I go to `project/files` and edit `my-file.src`, the settings don't apply. 

In a concrete example, if one uses puppet, one, usually, has a complex directory layout. It is usual that you want to work on a module only so one goes to that specific directory. It would be troublesome to maintain `.vimrc` files for all modules. 

I acknowledge that one could just open vim from the project's root but not all users use it like this.

My suggestion is to have a functionality similar to that of git with `.gitignore` files. You can have a `.gitignore` file anywhere in your tree and git honors it. 

This kind of functionality would be very useful IMHO.

**Comment by k-takata** [comment]
How about using a plugin like [vim-localrc](https://github.com/thinca/vim-localrc)?

**Comment by renich** [comment]
Not really. IMHO, this functionality is fundamental.

**Comment by mattn** [comment]
I disagree loading the project vimrc in default. For example, the case that a dangerous .vimrc (hidden) is placed in some repository which is cloned from GitHub.

**Comment by mattn** [comment]
https://github.com/editorconfig/editorconfig-vim ?

**Comment by tomtom** [comment]
As other have noted this can be done using plugins. I personally used [vim-localvimrc](https://github.com/embear/vim-localvimrc) for a long time but now use my own [autoproject_vim](https://github.com/tomtom/autoproject_vim) to achieve this.

.gitignore contains data. .vimrc contains code that is run within vim, which is a potential security risk. Even if vim had this feature by default, you might want to change the default filename to something only you and your team use. You probably wouldn't want to reuse such a file from a foreign source.

**Comment by tomtom** [comment]
The correct equivalent for .gitignore would be something like a vimrc.conf that contains buffer-local options and variables but no code.

**Comment by chrisbra** [comment]
If you want such a functionality, use one of the localvimrc plugins. I don't understand the reasoning, why it must be fundamentally included in Vim, when a plugin could achieve it. A related issue is to ship Vim with an editorconfig plugin. There is #2286 for that. Ping @Carpetsmoker perhaps he can comment on what the status is.
