### ISSUE TITLE
Compilation error RESTRICT no found in src/ex_docmd.c

### ISSUE THREAD

**Issue by damiengenthial** [vim/vim#3918]
Hello,
Trying to update my Vim with :

    git pull origin master
    make

I got this error :

    gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/ex_docmd.o ex_docmd.c
    ex_docmd.c: In function ‘do_one_cmd’:
    ex_docmd.c:2015:36: error: ‘RESTRICT’ undeclared (first use in this function)
      if (restricted != 0 && (ea.argt & RESTRICT))

I am on Debian Debian 4.9, with gcc 6.3.0 but I think it's not the point here (forget to add `RESTRICT` in `ex_cmds.h` ?).

Thanks,

**Comment by thornpig** [comment]
I am having the same issue on CentOS 7.5.1804.

**Comment by k-takata** [comment]
Fixed in 8.1.0883. Closing.
