### ISSUE TITLE
Support new Python 3.5 keywords and builtins (syntax)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vim/vim#392]
```
The attached patch adds highlighting for new coroutines:

  async def foo():
     await b()

and new builtins -- StopAsyncIteration and RecursionError

```

Original issue reported on code.google.com by `yseliva...@gmail.com` on 11 Aug 2015 at 6:55

Attachments:
* [python35.patch](https://storage.googleapis.com/google-code-attachments/vim/issue-392/comment-0/python35.patch)

**Comment by chrisbra** [comment]
seems fixed with current runtime files.
