### ISSUE TITLE
Bug: on Windows, hang when opening files from network.

### ISSUE THREAD

**Issue by kgfly** [vim/vim#3923]
Repro:

Eg, the file is \\\\dir1\dir2\dir3\file. I've r/w access to this file.
Under, \\\\dir1, there is a folder, eg \\\\dir1\dir_noaccess, which I don't have access right. Then when opening \\\\dir1\dir2\dir3\file, vim hangs.

As a comparison, notepad++ does not hang when opening this file.

I built windows vim tiny to take a look. The issue is here:

In fname_case of os_win32.c

	if (ptrue > ptruePrev
		&& (ptruePrev[0] != '.'
		    || (ptruePrev[1] != NUL
			&& (ptruePrev[1] != '.' || ptruePrev[2] != NUL)))
		&& (hFind = ### FindFirstFile(szTrueNameTemp, &fb))
						      != INVALID_HANDLE_VALUE)

**FindFirstFile** tries to access files from root dir to current dir, level by level. Because I don't have access right to \\\\dir1\dir_noaccess, when accessing \\\\dir1\\*, the API call just hang.

**Comment by kgfly** [comment]
I guest notepad++ just opens the file directly, without "access files from root dir to current dir, level by level". So it does not hang.

And the pattern of the bug repro should be a very common pattern for Windows users. I don't have environment to try the pattern on Linux. But I guess the pattern should be common too.

Because of the bug, I cannot set vim as the default editor (open files by double click), since when I double click the files from network, vim just hangs.

**Comment by k-takata** [comment]
Bram's comment is not forwarded here.
https://groups.google.com/d/msg/vim_dev/zzT5feYRKfk/8FKjC8sUAwAJ

> Does it really hang?  It's supposed to return an error.

**Comment by kgfly** [comment]
https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-findfirstfilea has a sample code. I just gave a try. I passed "\\\\dir1\\*". The API call just hangs. So I'm 100% sure it hangs. I doubt if this is a Win API bug.

In my production environment, \\\\dir1 is a network share folder. I don't have access to \\\\dir1\\dir_noaccess. When I double click the folder in Windows File Explorer, after about 10 seconds, the file explore prompts that "\\\\dir1\\dir_noaccess is not accessible. You might not have permission to use this network resource. Contact the administrator of this server to find out if you have access permissions. The device is not ready".

**Comment by brammool** [comment]
> https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-findfirstfilea has a sample code. I just gave a try. I passed "\\dir1\*". The API call just hangs. So I'm 100% sure it hangs. I doubt if this is a Win API bug.
> 
> In my production environment, \\dir1 is a network share folder. I
> don't have access to \\dir1\dir_noaccess. When I double click the
> folder in Windows File Explorer, after about 10 seconds, the file
> explore prompts that "\\dir1\dir_noaccess is not accessible. You might
> not have permission to use this network resource. Contact the
> administrator of this server to find out if you have access
> permissions. The device is not ready".

Hmm, that's annoying.  Perhaps we should first get the permissions to
check if we can use FindFirstFile.

-- 
MICHAEL PALIN PLAYED: 1ST SOLDIER WITH A KEEN INTEREST IN BIRDS, DENNIS, MR
                      DUCK (A VILLAGE CARPENTER WHO IS ALMOST KEENER THAN
                      ANYONE ELSE TO BURN WITCHES), THREE-HEADED KNIGHT, SIR
                      GALAHAD, KING OF SWAMP CASTLE, BROTHER MAYNARD'S ROOMATE
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by kgfly** [comment]
Thanks. Yes, it's annoying. Because I need open the file by double click, I cannot set gvim as my default editor. (Currently, I use notepad++ as the default editor).

**Comment by kgfly** [comment]
I want to do an update about previous observation. Actually, FindFirstFile, can return. It just takes a long time to return (20 seconds+). So gvim looks hung and unusable. Sorry for my previous incorrect report.

I've one more question: on Windows, is it possible to open the file directly without "access files from root dir to current dir, level by level."? In my production environment, vim is not usable for opening file from network, because the hung  time is too long.

**Comment by k-takata** [comment]
I wonder if we can use [GetLongPathName()](https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-getlongpathnamew) instead of FindFirstFile() to correct the file name.
(Not sure if it can solve the problem.)

**Comment by kgfly** [comment]
If you have a private bits to share, I am glad to help to verify.

I've a dumb question: why fname_case exists in Windows? If you use CreateFile to open the file, it should be able to open the file case insensitively.

**Comment by k-takata** [comment]
How about this patch?
https://gist.github.com/k-takata/2d475c21afb1dae67ba2b86f2a8f1c66

> why fname_case exists in Windows?

It corrects the case of filename so that Vim can show the correct filename. It also expands short name to long name.

**Comment by kgfly** [comment]
I've verified the patch. Yes, the patch is working. vim no longer hangs when opening the same file. Thanks.

Any idea when the patch could be checked in?

**Comment by brammool** [comment]
Ken Takata wrote:

> How about this patch?
> https://gist.github.com/k-takata/2d475c21afb1dae67ba2b86f2a8f1c66

Nice simplification!  I would like to hear from a few people that this
doesn't introduce a problem.


-- 
Computers make very fast, very accurate, mistakes.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by kgfly** [comment]
@k-takata Do you know when fix can be checked in? Thanks.

**Comment by k-takata** [comment]
Only Bram knows ;-)

**Comment by koron** [comment]
> How about this patch?
> https://gist.github.com/k-takata/2d475c21afb1dae67ba2b86f2a8f1c66

This works for my case very well.
My case was that it tooks about 1 minute to open a file on the samba server.
After applied the patch, it can be opened as fast as files on local.

I think that `FindFirstFile()` worked very slow on `\\machineA` or `\\`.

**Comment by kgfly** [comment]
Seems I am not the only one who hit this issue. Pls get it in at your earliest convenience. So people can set vim as default editor on Windows.  
Thanks.

**Comment by kgfly** [comment]
Verified. Thank for all your help, guys. Finally, I can set vim as the default editor on Windows now :)
