### ISSUE TITLE
Termdebug doesn't show breakpoint on source code in C project use allegro 5 API

### ISSUE THREAD

**Issue by misakisuna705** [vim/vim#3924]
vim 8.1.850 + python 3
macOS 10.13.6
compiler clang ( cmake ninja )

When I debug in most .c file / project, everything is fine.

However, when I debug in a .c project use allegro 5 API to deveolop a game, I can send command in gdb to set breakpoint and run, but termdebug show nothing on source code and doesn't trace it,

![2019-02-09 2 29 51](https://user-images.githubusercontent.com/40533309/52517623-b839bc80-2c78-11e9-8594-92f5833b8d8f.png)

I don't know the problem comes from using clang as compiler or from compile flags or from termdebug.

Sorry for poor English...

**Comment by damnskippy** [comment]
If you are hitting the breakpoint but just not seeing it displayed in vim, could it be a color highlighting issue possibly?  See what you get for highlighting when you do:
`:hi debugBreakpoint `
If the highlighting is not visible for your colorscheme, then that is likely your issue, you just need to change it to something other than the default that will stand out.

**Comment by misakisuna705** [comment]
I think it's not the highlight and colorscheme problem, because everything looks fine in my another test file with the same settings in my vimrc.

![2019-02-10 12 33 54](https://user-images.githubusercontent.com/40533309/52529645-6f453f00-2d30-11e9-9156-ea26d353d23e.png)

these are my settings:

let g:termdebug_wide = 1

au VimEnter * hi debugBreakpoint cterm=bold ctermbg=None
au VimEnter * hi debugPC ctermbg=242

au FileType c,cpp nnoremap <silent> <F4> :cclose<CR>:Tclose<CR>:cd %:p:h<CR>:packadd termdebug<CR>:Termdebug ../test/%:t:r<CR><C-w><C-h>

au FileType c,cpp nnoremap <silent> <F5> :Break<CR>
au FileType c,cpp nnoremap <silent> <F6> :Clear<CR>
au FileType c,cpp nnoremap <silent> <F7> :Run<CR>
au FileType c,cpp nnoremap <silent> <F8> :Continue<CR>
au FileType c,cpp nnoremap <silent> <F9> :Over<CR>
au FileType c,cpp nnoremap <silent> <F10> :Step<CR>

**Comment by brammool** [comment]
> I think it's not the highlight and colorscheme problem, because everything looks fine in my another test file with the same settings in my vimrc.
> 
> ![2019-02-10 12 33 54](https://user-images.githubusercontent.com/40533309/52529645-6f453f00-2d30-11e9-9156-ea26d353d23e.png)
> 
> these are my settings:
> 
> let g:termdebug_wide = 1
> 
> au VimEnter * hi debugBreakpoint cterm=bold ctermbg=None
> au VimEnter * hi debugPC ctermbg=242
> 
> au FileType c,cpp nnoremap <silent> <F4> :cclose<CR>:Tclose<CR>:cd %:p:h<CR>:packadd termdebug<CR>:Termdebug ../test/%:t:r<CR><C-w><C-h>
> 
> au FileType c,cpp nnoremap <silent> <F5> :Break<CR>
> au FileType c,cpp nnoremap <silent> <F6> :Clear<CR>
> au FileType c,cpp nnoremap <silent> <F7> :Run<CR>
> au FileType c,cpp nnoremap <silent> <F8> :Continue<CR>
> au FileType c,cpp nnoremap <silent> <F9> :Over<CR>
> au FileType c,cpp nnoremap <silent> <F10> :Step<CR>

The gdb responses are not very well documented, it's possible Termdebug
doesn't understand this specific one.  Please find the hidden
communication buffer and open it in a window.  Then when you set the
breakpoint, see what gdb sends to Vim.  You can also compare it to using
":Break" in the Vim window, to see what is different.

-- 
Living on Earth includes an annual free trip around the Sun.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by GitMensch** [comment]
@misakisuna705 That is a quite old issue - can you still reproduce that? If yes, does it still happen when you adjust TermDebug including #9140?

If one of the answers is "no", I guess this issue may be closed.
