### ISSUE TITLE
Is there a way to delete (trim) some jumplist items?

### ISSUE THREAD

**Issue by epheien** [vim/vim#3935]
I want a jumplist like tree (undotree), or like taglist stack (trim some needless items), but I can not find any way to delete jumplist items.
I think about hook jump action for my own jumplist, but I can not find some efficient way (CursorMove?).
Any suggestions?

**Comment by brammool** [comment]
This is not the right place to ask questions.  Please use the Vim maillist or https://vi.stackexchange.com/
