### ISSUE TITLE
Problem with returning tab variables

### ISSUE THREAD

**Issue by szw** [vim/vim#394]
Hi!

Recently I've encountered an issue with Vim 7.4.712 on Mac OSX Yosemite. It seems `gettabvar()` cannot read tab variables for the first time after Vim start and after `:only` (or `<C-w>o`) if there was an unlisted buffer and got closed. Here's how it behaves (and how to reproduce):

https://asciinema.org/a/emg1wb9ccmu72lhtoj62m8u6p

I can confirm the behavior with help buffer and `:only` command also on MacVim 7.4.769.

Interestingly, after first attempt (when the empty string is returned) the next call returns the variable value as expected.

Thanks in advance! And welcome to Github :)

s.

**Comment by chrisbra** [comment]
fixed with patch  7e47d1ac6a9 (7.4.834)

**Comment by szw** [comment]
:+1:
