### ISSUE TITLE
Splitted windows and File Explorer (It doesn't change directory in other window)

### ISSUE THREAD

**Issue by aleskandro** [vim/vim#395]
Hi all, I don't know if this could be a bug of netrw.
I'm trying to have a splitted session in vim with a window that keep sticky the File Explorer.
so I do this with:

```
:vsplit
:vertical resize 30
:Ex
```

So I can open a file in the right window clicking 'P'.
It works the first time. After, if I try to open a file in another directory it does't work.

Affected versions: 7.4.273 (Gentoo), 7.4 (Included patches: 1-488, 576) (Debian)

For example:

I'm in home and open the file /home/aleskandro/test.
Next I go back to the left window and open the /home/aleskandro/testdir clicking P in the file /home/aleskandro/testdir/testotherdir.
In the status bar vim return that it try to opening testotherdir in the same previous directory (in this example it opens a new file in /home/aleskandro/testotherdir

**Comment by chrisbra** [comment]
See:
https://groups.google.com/d/msg/vim_dev/W4KTuJ0ksYU/4gUZ1fFvAwAJ

Please discuss runtime issues with the maintainer of the file.
