### ISSUE TITLE
8.1.1: alt-space fails when .vimrc present

### ISSUE THREAD

**Issue by t0mj0nes** [vim/vim#3951]
Version: VIM - Vi IMproved 8.1 (2018 May 18, compiled May 18 2018 18:36:07)
MS-Windows 32-bit GUI version with OLE support
Included patches: 1
OS: Win10 Enterprise, Version 10.0.16299 Build 16299

Fresh install <alt>-<space> brings up control menu for window (restore, move, size, minimize, maximize, close)

touch C:\Users\{me}\.vimrc

<alt>-<space> no longer works.

<alt>-<F4> still closes window though.

**Comment by chrisbra** [comment]
Can you check, if setting the `winaltkey` option changes anything? Also you might want to compare the output of `:set` with and without a vimrc file. Might as well check the output of `:scriptnames`, if this gives a hint.

**Comment by chrisbra** [comment]
Missing feedback, closing. See the help for the `:simalt` command and the mentioned 'winaltkey'  option.
