### ISSUE TITLE
E315 occurs when typing text for search command in terminal-normal mode

### ISSUE THREAD

**Issue by mnishz** [vim/vim#3959]
Hi there,
Since this is my first post to vim-dev, first I appreciate the great text editor and your contribution for Vim. Really thank you.
I'm writing this because I found that E315 can occur in terminal-normal mode.

# Summary
E315 occurs when typing text for search command with the following conditions.

* :set incsearch
* Terminal-Normal mode
* The number of lines exceeds 'termwinscroll'.

# How to recreate
https://github.com/mnishz/E315_recreation
1. `vim -Nu NONE main.c`
1. `:set incsearch`
1. `:term`
1. `cat 9500_lines`
1. `<c-w>Ni`
1. `gcc main.c`
1. `./a.out`
1. `<c-w>N`
1. `/type something`

Please click the image to play GIF again.
![e315](https://user-images.githubusercontent.com/20806102/52277677-a1ede100-2998-11e9-9d25-5b3c9744dad5.gif)

# Failure sequence
    main
        vim_main2
            main_loop
                normal_cmd
                    nv_search
                        getcmdline
                            getcmdline_int
                                may_do_incsearch_highlighting
                                    restore curwin->w_cursor in the function
                                    validate_cursor
                                        curs_columns
                                            getvvcol
                                                getvcol
                                                    ml_get_buf
                                                        E315

I think there are *at least* three points that can cause E315.
```diff
diff --git a/src/ex_getln.c b/src/ex_getln.c
index cba082a0b..77478a012 100644
--- a/src/ex_getln.c
+++ b/src/ex_getln.c
@@ -434,7 +435,7 @@ finish_incsearch_highlighting(

        p_magic = is_state->magic_save;

-       validate_cursor();      /* needed for TAB */
+       validate_cursor();      /* needed for TAB */  // E315 here
        redraw_all_later(SOME_VALID);
        if (call_update_screen)
            update_screen(SOME_VALID);
@@ -592,7 +595,7 @@ may_do_incsearch_highlighting(
        ccline.cmdbuff[skiplen + patlen] = next_char;
     }

-    validate_cursor();
+    validate_cursor();  // E315 here
     // May redraw the status line to show the cursor position.
     if (p_ru && curwin->w_status_height > 0)
        curwin->w_redr_status = TRUE;
@@ -659,11 +662,11 @@ may_adjust_incsearch_highlighting(
     out_flush();
     if (c == Ctrl_G)
     {
-       t = is_state->match_end;
+       t = is_state->match_end;  // "t" could cause E315
        if (LT_POS(is_state->match_start, is_state->match_end))
            // Start searching at the end of the match not at the beginning of
            // the next column.
-           (void)decl(&t);
+           (void)decl(&t);  // E315 here
        search_flags += SEARCH_COL;
     }
     else
```

# Root cause
My 1st idea: Incsearch functions restore `curwin->w_cursor` to the last line after some lines in terminal were scrolled off. So, I thought that we can fix it by calling check_cusor() just after the restoring.
But, on second though, it might not be expected behavior that terminal buffer is updated during terminal-normal mode. When I type text for search command, it seems that the buffer is updated and could be scrolled off. If this is the true root cause, it looks complicated for me to fix.
> :h Terminal-Normal
> The commands that would start insert mode, such as 'i' and 'a', return to Terminal-Job mode.
> The window will be updated to show the contents of the terminal.

I also found that any motion normal commands like 'G' update the buffer.

# Recreation script (doesn't work though)
I tried to recreate this E315 using the following file, but it cannot be recreated.
https://github.com/mnishz/E315_recreation/blob/master/E315_recreation.vim

# Vim version
8.1.875

# OS
Linux Ubuntu 18.04 LTS 64 bit

# Note
This is a duplicate of https://github.com/vim-jp/issues/issues/1229.

**Comment by brammool** [comment]
> Hi there,
> Since this is my first post to vim-dev, first I appreciate the great text editor and your contribution for Vim. Really thank you.
> I'm writing this because I found that E315 can occur in terminal-normal mode.
> 
> # Summary
> E315 occurs when typing text for search command with the following conditions.
> 
> * :set incsearch
> * Terminal-Normal mode
> * The number of lines exceeds 'termwinscroll'.
> 
> # How to recreate
> https://github.com/mnishz/E315_recreation
> 1. `vim -Nu NONE main.c`
> 1. `:set incsearch`
> 1. `:term`
> 1. `cat 9500_lines`
> 1. `<c-w>Ni`
> 1. `gcc main.c`
> 1. `./a.out`
> 1. `<c-w>N`
> 1. `/type something`
> 
> Please click the image to play GIF again.
> ![e315](https://user-images.githubusercontent.com/20806102/52277677-a1ede100-2998-11e9-9d25-5b3c9744dad5.gif)
> 
> # Failure sequence
>     main
>         vim_main2
>             main_loop
>                 normal_cmd
>                     nv_search
>                         getcmdline
>                             getcmdline_int
>                                 may_do_incsearch_highlighting
>                                     restore curwin->w_cursor in the function
>                                     validate_cursor
>                                         curs_columns
>                                             getvvcol
>                                                 getvcol
>                                                     ml_get_buf
>                                                         E315
> 
> I think there are *at least* three points that can cause E315.
> ```diff
> diff --git a/src/ex_getln.c b/src/ex_getln.c
> index cba082a0b..77478a012 100644
> --- a/src/ex_getln.c
> +++ b/src/ex_getln.c
> @@ -434,7 +435,7 @@ finish_incsearch_highlighting(
> 
>         p_magic = is_state->magic_save;
> 
> -       validate_cursor();      /* needed for TAB */
> +       validate_cursor();      /* needed for TAB */  // E315 here
>         redraw_all_later(SOME_VALID);
>         if (call_update_screen)
>             update_screen(SOME_VALID);
> @@ -592,7 +595,7 @@ may_do_incsearch_highlighting(
>         ccline.cmdbuff[skiplen + patlen] = next_char;
>      }
> 
> -    validate_cursor();
> +    validate_cursor();  // E315 here
>      // May redraw the status line to show the cursor position.
>      if (p_ru && curwin->w_status_height > 0)
>         curwin->w_redr_status = TRUE;
> @@ -659,11 +662,11 @@ may_adjust_incsearch_highlighting(
>      out_flush();
>      if (c == Ctrl_G)
>      {
> -       t = is_state->match_end;
> +       t = is_state->match_end;  // "t" could cause E315
>         if (LT_POS(is_state->match_start, is_state->match_end))
>             // Start searching at the end of the match not at the beginning of
>             // the next column.
> -           (void)decl(&t);
> +           (void)decl(&t);  // E315 here
>         search_flags += SEARCH_COL;
>      }
>      else
> ```
> 
> # Root cause
> My 1st idea: Incsearch functions restore `curwin->w_cursor` to the last line after some lines in terminal were scrolled off. So, I thought that we can fix it by calling check_cusor() just after the restoring.
> But, on second though, it might not be expected behavior that terminal buffer is updated during terminal-normal mode. When I type text for search command, it seems that the buffer is updated and could be scrolled off. If this is the true root cause, it looks complicated for me to fix.
> > :h Terminal-Normal
> > The commands that would start insert mode, such as 'i' and 'a', return to Terminal-Job mode.
> > The window will be updated to show the contents of the terminal.
> 
> I also found that any motion normal commands like 'G' update the buffer.
> 
> # Recreation script (doesn't work though)
> I tried to recreate this E315 using the following file, but it cannot be recreated.
> https://github.com/mnishz/E315_recreation/blob/master/E315_recreation.vim
> 
> # Vim version
> 8.1.875
> 
> # OS
> Linux Ubuntu 18.04 LTS 64 bit
> 
> # Note
> This is a duplicate of https://github.com/vim-jp/issues/issues/1229.

I haven't tried your exact steps, but I can see that when going to
Terminal-Normal mode, while a job is running and causing the terminal to
scroll, weird things start happening.  The display is messed up and the
cursor is sometimes moved.  I can see that deleting the scrollback will
cause more problems.

I'll see if this can be fixed.  Simple attempts have not helped, this
will take some more time.

-- 
Why I like vim:
> I like VIM because, when I ask a question in this newsgroup, I get a
> one-line answer.  With xemacs, I get a 1Kb lisp script with bugs in it ;-)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
I suppose this has been fixed by 29ae223ddcfcbbce46c7e1f4e8fa71b8f2674271 ?

**Comment by mnishz** [comment]
Thank you for the patch and comment. I believe so, but got another E315.
1. `vim -Nu NONE main.c`
1. `:term`
1. `cat 9500_lines`
1. `<c-w>Ni`
1. `gcc main.c`
1. `./a.out`
1. `<c-w>N`
1. Wait for 10 seconds (until a.out finishes)
1. Press `i` to enter Terminal-Job mode

Would it be better to close this issue and open another one? I haven't took a look at new one at all, though...
```
(gdb) bt
#0  ml_get_buf (buf=0xe02620, lnum=0x2576, will_change=0x0) at memline.c:2488
#1  0x00000000004e04a6 in plines_win_nofold (wp=0xe00980, lnum=0x2576) at misc1.c:2134
#2  0x00000000004e0450 in plines_win_nofill (wp=0xe00980, lnum=0x2576, winheight=0x1) at misc1.c:2117
#3  0x00000000004e039a in plines_win (wp=0xe00980, lnum=0x2576, winheight=0x1) at misc1.c:2086
#4  0x00000000004e036e in plines (lnum=0x2576) at misc1.c:2074
#5  0x00000000004ed67d in validate_cheight () at move.c:844
#6  0x00000000004ef1fd in scroll_cursor_top (min_scroll=0x1, always=0x0) at move.c:1688
#7  0x00000000004ec6ac in update_topline () at move.c:296
#8  0x000000000061e499 in main_loop (cmdwin=0x0, noexmode=0x0) at main.c:1246
#9  0x000000000061deb1 in vim_main2 () at main.c:901
#10 0x000000000061d720 in main (argc=0x4, argv=0x7ffe8347b4f8) at main.c:441
```

**Comment by chrisbra** [comment]
yes, please open a new issue with steps to reproduce the issue. Closing this then. Thanks.
