### ISSUE TITLE
Multiple lines echo doesn't work with timer

### ISSUE THREAD

**Issue by chemzqm** [vim/vim#3960]
My vim version:
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 14 2019 04:56:33)
macOS version
Included patches: 1-912
```
Test code:
``` vim
function! s:Execute(cmd)
  echon "NAME\n"
  echon "NAME\n"
  echon "NAME\n"
endfunction
call timer_start(100, { -> s:Execute('')})
"call s:Execute('')
```

It works as expected without timer, but nothing would echo with timer.
Same issue with echo command send from channel.

**Comment by brammool** [comment]
> My vim version:
> ```
> VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 14 2019 04:56:33)
> macOS version
> Included patches: 1-912
> ```
> Test code:
> ``` vim
> function! s:Execute(cmd)
>   echon "NAME\n"
>   echon "NAME\n"
>   echon "NAME\n"
> endfunction
> call timer_start(100, { -> s:Execute('')})
> "call s:Execute('')
> ```
> 
> It works as expected without timer, but nothing would echo with timer.

The messages are actually output, but the screen is redrawn right away
afterwards.  Try adding a sleep after the messages.

It's a dilemma that when a callback outputs text, whether the user wants
to see it or not.  Best is to open a window to show the messages in.

-- 
LARGE MAN:   Who's that then?
CART DRIVER: (Grudgingly) I dunno, Must be a king.
LARGE MAN:   Why?
CART DRIVER: He hasn't got shit all over him.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by tinmarino** [comment]
@chemzqm my solution was documenting: advising user to use `g<` and making the important `OK` message the last one

**Comment by brammool** [comment]
As mentioned in issue #7451, echoing a message from a timer callback interrupts the UI at an unpredictable moment, thus can't be expected to show up.  Use another way, such as popup_notification()
