### ISSUE TITLE
Problem with uninstalling vim on windows 10 

### ISSUE THREAD

**Issue by wanjingz** [vim/vim#3962]
**Installed vim by the following lines:**
git clone https://github.com/vim/vim.git
cd vim/src
make

Version:
![image](https://user-images.githubusercontent.com/37635975/52806998-fd326a00-304f-11e9-8b23-c2174a8b5ac7.png)

Could not find 'uninstal.exe' in the vim directory.
Have no idea on how to uninstall it.

**Comment by k-takata** [comment]
It seems that you are building non-Windows version of Vim.
Please see `src/INSTALLpc.txt` to know how to build Windows versions of Vim.

Anyway, this is not right place to ask questions. Please use the vim_dev (or vim_use) mailinglist to ask how to build Vim.

**Comment by tonymec** [comment]
Building Vim for Windows should **not** be done with the default makefile named `Makefile` but with a different `.mak` file according to which compiler you are using (usually either MS Visual Studio or MinGW gcc). For details, see the file `src/INSTALLpc.txt` which has the format of a Vim helpfile except that it has no modeline.

Best regards,
Tony.
