### ISSUE TITLE
horizontal splits cause both windows to jump downwards

### ISSUE THREAD

**Issue by majuscule** [vim/vim#3973]
To reproduce, start with a file containing the following:
```
a
b
c
d
e
f
g
h
```

then `:split`, and observe lines 1-4 move out of the top window, and 1-3 move out of the bottom window. My terminal size is `stty rows 76 cols 119`, there is plenty of room available and no need or reason to scroll either window.

**Comment by majuscule** [comment]
Note, this behaviour does seem reasonable in large files where vim appears to attempt to keep the cursor centered in the split window, but is broken with small files.

**Comment by dylnmc** [comment]
I second this motion. If the entire buffer is visible, please show the entire buffer.

[![asciicast](https://asciinema.org/a/UkLhNoVosn23hUPEf03AAMkNf.svg)](https://asciinema.org/a/UkLhNoVosn23hUPEf03AAMkNf)

---

Update: essentially the `lsbuffer` is a single buffer such that when I press `l` it moves into that directory by doing `:lcd` (`h` goes backwards one directory, and there are a few other keybindings as well), and then it does a `%delete` to delete the `lsbuffer`'s contents, then it does a `append(0, sort(glob('*')))` (in a simplified sense) to paste in the the contents of something `ls -1` might show. When I get a full plugin out, I'll post a link, but I have been pretty busy and have only had a little less than an hour or so to dedicate some nights. It's something that I think will be of use to me once I implement everything I envision.

Thanks,
dylnmc

---

# Update

plugin that illustrates the issue: https://github.com/dylnmc/lsbuffer.vim

steps to reproduce.

1. install
2. `<leader>ls` to bring up lsbuffer
3. `<w-c>v` to vertical split
4. navigate to a directory and press `l` or `<cr>` to enter

You'll see the other window jump so tha the last line is at the very top of the buffer.

**Comment by martinkunev** [comment]
I'm working on this issue.

**Comment by brammool** [comment]
@martinkunev - looks like you never finished this?

**Comment by martinkunev** [comment]
@brammool I fixed it - check the pull requests. I don't have permission to close the ticket.

**Comment by brammool** [comment]
Which PR is that?  If it was included, what is the patch number?

**Comment by martinkunev** [comment]
https://github.com/vim/vim/pull/4367
https://github.com/vim/vim/commit/a9b2535f44f3265940a18d08520a9ad4ef7bda82
