### ISSUE TITLE
Unexpected output of `strdisplaywidth()` in presence of multibyte characters

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#3975]
- `vim --version`:      VIM - Vi IMproved 8.1  Included patches: 1-914
 - Operating system:     Ubuntu 16.04.5 LTS
 - Terminal emulator:    rxvt-unicode v9.22
 - Terminal multiplexer: tmux next-2.9
 - `$TERM`:              tmux-256color
 - Shell:                zsh 5.7.1-dev-0 (x86_64-pc-linux-gnu)

Consider this command:

    $ vim +'sil put =\"∅\thello\n123456789\nx\thello\"' +'norm! 1G8|' +'echom strdisplaywidth("\t", col(".")-1)' -Nu NONE

It starts Vim with no configuration, and puts these lines in a buffer:

    ∅       hello
    123456789
    x       hello

The whitespace before `hello` is a tab, and before the tab is a multibyte character on the first line, `∅`, whose weight is 3 bytes (`e2 88 85`).

When the cursor is on the tab of the first line, according to `:echo strdisplaywidth("\t", col('.')-1)`, the tab occupies 5 cells; I think it should be 7, since on my screen, I can see the tab beginning above the character `2` and ending above the character `8` (8-2+1 = 7).

If I move the cursor on the third line, which is almost identical, by pressing `j` twice, this time `:echo strdisplaywidth("\t", col('.')-1)` correctly reports that the tab occupies 7 cells. The only difference between the first and third line is the multibyte character on the first one which is replaced by a character whose weight is only 1 byte on the third one.

Shouldn't `strdisplaywidth()` report the same number of cells regardless of whether there's a multibyte character before on the line – provided that it occupies a single cell?

**Comment by tonymec** [comment]
`col()` is a byte index. Try using `virtcol()` instead, that one is a screen-cell index.

Best regards,
Tony.

**Comment by tonymec** [comment]
> `col()` is a byte index. Try using `virtcol()` instead, that one is a screen-cell index.

P.S., And do it with `'list'` set, it changes where the cursor is positioned when it is on a horizontal-tab character.
> 
> Best regards,
> Tony.

**Comment by tonymec** [comment]
> > `col()` is a byte index. Try using `virtcol()` instead, that one is a screen-cell index.
> 
> P.S., And do it with `'list'` set, it changes where the cursor is positioned when it is on a horizontal-tab character.

P.P.S. `'listchars'` should also be set, otherwise a tab will appear as `^I`. I use
```vim
if exists('+list')
  set list
  if exists('+listchars')
    set lcs=eol:¶,tab:\|_,extends:>,precedes:<,conceal:*,nbsp:·
  endif
endif
```
but any two- or three-character value for `tab:` can be used. (I use two, vertical bar and underscore, but the vertical bar has to be backslash-escaped.)
> 
> > Best regards,
> > Tony.

**Comment by lacygoill** [comment]
Thank you very much for your answer @tonymec. I think you're right, I should have used `virtcol()` instead of `col()`. I misread the documentation at `:h strdisplaywidth()`, sorry.
