### ISSUE TITLE
Vim doesn't meet PEP 451

### ISSUE THREAD

**Issue by joelfrederico** [vim/vim#3984]
There are a few issues with vim's Python "module" implementation. Most specifically, it doesn't meet PEP 451. This means that Google's [Protobuf](https://pypi.org/project/protobuf/) can't be imported within a Vim plugin.

The vim "module" is used in [`sys.path_hooks`](https://docs.python.org/3/library/sys.html#sys.path_hooks). It is intended to be a [`finder`](https://docs.python.org/3/glossary.html#term-finder), specifically a [path entry finder](https://docs.python.org/3/glossary.html#term-path-entry-finder). This means that it should at least duck-type as an [`importlib.abc.PathEntryFinder`](https://docs.python.org/3/library/importlib.html#importlib.abc.PathEntryFinder). Unfortunately, it doesn't support `find_module`, which is the reason for the error when importing Protobuf.

See https://github.com/vim/vim/commit/b999ba2778b6c02fdd100e498a9ba5b2e7036f7d, https://github.com/pypa/setuptools/pull/1563#issuecomment-463810046, and https://github.com/vim/vim/pull/3954#issuecomment-463708190.

**Comment by diraol** [comment]
More than that, this issue is severely impacting `python-mode` vim plugin, we have been trying to work around this issue for several months, but it always get back again (off course, we just worked around it).

**Comment by brammool** [comment]
PEP 451 title is "PEP 451 -- A ModuleSpec Type for the Import System" and it's a very long document.
This issue is very vague and unclear about what the actual problem is or how it could be fixed.
It's unlikely anything is going to happen unless that is cleared up.

**Comment by joelfrederico** [comment]
I left all of the information that's needed in order to fix the issue. The vim module needs to implement what's specified for a PathEntryFinder, which is an abstract base class. https://docs.python.org/3/library/importlib.html#importlib.abc.PathEntryFinder Specifically, it needs to implement find_spec, find_loader, find_module, and invalidate_caches. It does not implement find_module.

There's been some confusion in the past about deprecation. In order to work, *all* deprecated methods must be implemented. The reason is that these deprecated methods are part of the contract for *being* a PathEntryFinder. Those *using* a PathEntryFinder *should* use the newer methods, but they *may* use the deprecated API.

If a third-party module accesses and uses a PathEntryFinder, it will get the vim module and *may* attempt to use the deprecated API. If it does that, and the vim module does not implement the deprecated API, the third-party module will throw an exception. This is what in fact happens for a few edge cases.

**Comment by brammool** [comment]
Joel Frederico wrote:

> I left all of the information that's needed in order to fix the issue.
> The vim module needs to implement what's specified for a
> PathEntryFinder, which is an abstract base class.
> https://docs.python.org/3/library/importlib.html#importlib.abc.PathEntryFinder
> Specifically, it needs to implement find_spec, find_loader,
> find_module, and invalidate_caches. It does not implement find_module.
> 
> There's been some confusion in the past about deprecation. In order to
> work, *all* deprecated methods must be implemented. The reason is that
> these deprecated methods are part of the contract for *being* a
> PathEntryFinder. Those *using* a PathEntryFinder *should* use the
> newer methods, but they *may* use the deprecated API.

I suppose you are talking about what is at the end of if_py_both.h.
That was changed not too long ago.  It still isn't right?

-- 
SECOND SOLDIER: It could be carried by an African swallow!
FIRST SOLDIER:  Oh  yes! An African swallow maybe ... but not a European
                swallow. that's my point.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by joelfrederico** [comment]
Sorry for the delayed response. No, it still doesn't work. The changes didn't make it into the vim module. You can check by opening vim and running:

`:python3 import vim; vim.find_module`

It says there's no attribute find_module.

**Comment by joelfrederico** [comment]
~~I edited a bit and I got find_module to appear, but there's a segfault. I'd like to run MacVim through the XCode debugger so I can do breakpoints, etc., but I can't find documentation on how to do that?~~

Edit: Nevermind, figured it out.
