### ISSUE TITLE
Diff foldmethod folds too much with context:0

### ISSUE THREAD

**Issue by fritzophrenic** [vim/vim#4005]
Setting diffopt to include "context:0" makes the folding and text alignment incorrect with deleted lines in the text.

Example, with diffopt=internal,filler,vertical,context:0 I get the results from the attached screenshots.
![bad_diff_folded](https://user-images.githubusercontent.com/1334420/52993601-6280b500-33da-11e9-93ec-e10ece031bf7.png)
![bad_diff_unfolded](https://user-images.githubusercontent.com/1334420/52993602-6280b500-33da-11e9-96f0-4571370148ad.png)

**Comment by fritzophrenic** [comment]
Forgot to add: screenshots are from self-compiled gvim 8.1.952 on Ubuntu. I noticed it first while running 8.1.591. I have a couple patches applied but nothing that should affect diff functionality.

**Comment by brammool** [comment]
It is not possible to create two folds without a line in between.
Perhaps we should make context:0 behave like context:1
