### ISSUE TITLE
matchit is broken

### ISSUE THREAD

**Issue by chris-morgan** [vim/vim#4006]
I just upgraded from Vim 8.1.1 to today’s vim-win32-installer build 8.1.952, and matchit is broken:

> E117: Unknown function: matchit#Match_wrapper

Very quick investigation suggests that 314dd79cac2adc10304212d1980d23ecf6782cfc (patch 872) broke it, and 94688b8a2a1fc3d6c8e49151b9533ec1c0a6757f (patch 875) was supposed to fix it, but doesn’t actually seem to have done so.

This is from patches 872 and 875, two weeks ago. Today’s 952 build should have all of this stuff.

Is something more missing in some build system?

The autoload/matchit.vim file is definitely not there. I’ve copied it from this repository into my vimfiles as a temporary workaround and that makes it work for me.

**Comment by chrisbra** [comment]
The matchit autoload file is right there in the directory runtime/pack/dist/opt/matchit of your installation. I just verified by downloading the gvim_8.1.0952_x64.zip. After running `gvim.exe --clean` and doing `:packadd matchit`, hitting `%` works as expected and the autoload file for matchit has been successfully found.

**Comment by chris-morgan** [comment]
OK, that suggests the problem may be with the installer, or some build process that led to the installer: because it’s definitely not there in gvim_8.1.0952_x86.exe. Open it in 7-Zip, $0\pack\dist\opt\matchit\ contains no autoload directory.

**Comment by chrisbra** [comment]
Ah, it seems you are right here. I think we need an extra patch for nsis here:

```patch
diff --git a/nsis/gvim.nsi b/nsis/gvim.nsi
index 17e3e7238..9f9fb4ed5 100644
--- a/nsis/gvim.nsi
+++ b/nsis/gvim.nsi
@@ -379,6 +379,8 @@ Section "$(str_section_exe)" id_section_exe
        File ${VIMRT}\pack\dist\opt\matchit\doc\*.*
        SetOutPath $0\pack\dist\opt\matchit\plugin
        File ${VIMRT}\pack\dist\opt\matchit\plugin\*.*
+       SetOutPath $0\pack\dist\opt\matchit\autoload
+       File ${VIMRT}\pack\dist\opt\matchit\autoload\*.*

        SetOutPath $0\pack\dist\opt\shellmenu\plugin
        File ${VIMRT}\pack\dist\opt\shellmenu\plugin\*.*
```

I had only a quick look into the nsis script so not sure this fixes it correctly.
ping @k-takata as he did most of the nsis rework recently.

**Comment by k-takata** [comment]
Yes, I think it's the correct solution.
