### ISSUE TITLE
enabling other text editors to run vim's engine

### ISSUE THREAD

**Issue by mkuts12** [vim/vim#402]
hey there,
There are many plugins for various text editors that try to imitate the awesomeness of vim. But, unfortunately fail miserably. 
I would like them to run vim at the back and render the text themselves.

Please make it happen.

Best regards,
michael

**Comment by vim-ml** [comment]
On Aug 27, 2015 8:12 AM, "mkuts12" vim-dev-github@256bit.org wrote:

> hey there,
> There are many plugins for various text editors that try to imitate the
> awesomeness of vim. But, unfortunately fail miserably.
> I would like them to run vim at the back and render the text themselves.
> 
> Please make it happen.

Neovim exists for that purpose.

**Comment by mkuts12** [comment]
Neovim is not quite vim.
Besides, I work in a place that forces us to use windows and I have to use text editors that work on windows.
Some plugins for gvim, and gvim itself don't work quite well. 
I would like to use Atom or sublime as my UI, and vim for the editing and ex mode.
I want to use Vim and not an emulator of vim

**Comment by vim-ml** [comment]
On Aug 27, 2015 08:52, "mkuts12" vim-dev-github@256bit.org wrote:

> Neovim is not quite vim.
> Besides, I work in a place that forces us to use windows and I have to
> use text editors that work on windows.
> Some plugins for gvim, and gvim itself don't work quite well.
> I would like to use Atom or sublime as my UI, and vim for the editing and
> ex mode.
> I want to use Vim and not an emulator of vim

Ok. So what you are asking for is an effort similar to Neovim, but exactly
like Vim, without any transition period. Got it ;)

**Comment by mkuts12** [comment]
I want to use Vim and not an emulator in whatever editor I like,
for example I don't want a vim-mode in atom, I want Vim!

Neovim is still in beta and does not work well in windows yet. Furthermore, there are no plugins for atom or sublime that work with Neovim. 
Do you have a reasonable solution for my problem?

**Comment by justinmk** [comment]
> I want to use Vim and not an emulator in whatever editor I like,

Right, that is the entire purpose of Neovim. It is not an emulator, it is a modified version of Vim.

> Neovim is still in beta and does not work well in windows yet

True, but it is being worked on in earnest. Not sure what else can be expected.

> there are no plugins for atom or sublime that work with Neovim. 

There are several UI clients (and other plugins) listed here: https://github.com/neovim/neovim/wiki/Related-projects

In particular, there are two Atom clients:
- https://github.com/coolwanglu/neovim-e
- https://github.com/carlosdcastillo/vim-mode

They are experimental at this point, but rather than requesting that Vim "make it happen" with an entirely new effort, it makes more sense, in my opinion, to improve the existing efforts.

**Comment by mkuts12** [comment]
You are right. I was not aware of these clients, not sure about the functionalities of neovim, and i love vim so i asked here.
Thank you for your help =]

**Comment by vim-ml** [comment]
On Thursday, August 27, 2015 at 7:52:20 AM UTC-5, mkuts12 wrote:

> Some plugins for gvim, and gvim itself don't work quite well. 

What are you talking about? What plugins that work in Vim don't work in gvim? It's the exact same program!

And what do you mean gvim doesn't work well in Windows? gvim works great in Windows! Better than in some of its forms in Linux, even, where it depends on what GUI you compile with.
