### ISSUE TITLE
Feature request: Nofilter option for complete function

### ISSUE THREAD

**Issue by chemzqm** [vim/vim#4023]
When using auto completion engine the pum would be flicking when typing.

That's bacause auto completion engine not always filter completion items like vim does, some of them support fuzzy filter, so pum could be shown again by completion engine after type one character.

One way to solve this problem is add a `nofilter` option to `complete` function, like:
``` vim
complete({startcol}, {matches}, [{nofilter}])
```

When `nofilter` is `1`:

* Vim keep the pum unchanged when text changed.
* A function for hide the pum like `pumhide()` need to provide for completion engine to hide the pum. When it's called and pum is visible, vim hide the pum and trigger `CompleteDone` with empty `v:completed_item` , do nothing when pum is not visible.
* Behavior of `<C-y>` and `<C-e>` doesn't change.
* Another call to `complete` when pum is visible cause vim redraw the pum without trigger `CompleteDone`.

**Comment by mattn** [comment]
The new flag should be added as completeopt=nofilter ?

**Comment by mattn** [comment]
Ah, sorry. userfunc decide the candidates it self. so the flag should be added into argument of complete().

**Comment by chemzqm** [comment]
I would prefer set the flag with `complete` function, vim could revert the flag on CompleteDone, so that complete engine don't need to change user's completeopt.

**Comment by micbou** [comment]
See PR https://github.com/vim/vim/pull/3887 and in particular https://github.com/vim/vim/pull/3887#issuecomment-459359486.

> A function for hide the pum like `pumhide()` need to provide for completion engine to hide the pum. When it's called and pum is visible, vim hide the pum and trigger `CompleteDone` with empty `v:completed_item` , do nothing when pum is not visible.

Why is this needed? Can't `complete()` with a specific value of `startcol` be used for that?

**Comment by chemzqm** [comment]
> Can't `complete()` with a specific value of `startcol` be used for that?

It could, but it's confusing, and `complete()` requires a mapping with `CTRL-R`, which is harder to use.

I send empty complete items to vim to hide the pum for now.

**Comment by chemzqm** [comment]
`equal` field of complete item works fine.
