### ISSUE TITLE
Vim terminal clears output after running command

### ISSUE THREAD

**Issue by raman162** [vim/vim#4030]
I would be editing a file a rspec file in vim and then will proceed to run the following command below:

```
:term bundle exec rspec %
```

The command runs fine as usual but once finished, the output in the terminal clears. This only started happening after I upgraded vim earlier this morning on Feb 21st 2019. I have been able to reproduce with `vim -N -u NONE`.

My compiled version of vim:
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 18 2019 11:53:32)
Included patches: 1-946
```

**Comment by chrisbra** [comment]
does this still happen or has this been fixed by e.g. 8376c3d3216f65b93fb3bc03db

**Comment by chrisbra** [comment]
closing for now feedback.
