### ISSUE TITLE
Documentation typo: eval.txt

### ISSUE THREAD

**Issue by magicmissile** [vim/vim#4031]
Version: 8.1.  Platform (if it matters): Windows.  In [https://github.com/vim/vim/blob/master/runtime/doc/eval.txt#L5154](https://github.com/vim/vim/blob/master/runtime/doc/eval.txt#L5154) or in my installed version in eval.txt line 4863, in the last line of the section about gettabinfo, the second-to-the-last word on the line is "tag" and I'm pretty sure it should be "tab". 

The line in my eval.txt is this:
`	windows		List of |window-ID|s in the tag page.`

and I think it should be:
`	windows		List of |window-ID|s in the tab page.`

I did have to look up the tags feature because I've never used it, so maybe I'm wrong.

**Comment by brammool** [comment]
Thanks!
