### ISSUE TITLE
OptionSet event does not fully distinguish between local and global options

### ISSUE THREAD

**Issue by ghost** [vim/vim#4043]
I try to keep an option (spell) in sync with another option (matchpairs). I
found the OptionSet event which partially allows to do this with (simplified code):

:autocmd OptionSet * execute 'set' . v:option_type . ' matchpairs=a:b'

I say partially because OptionSet does not allow me to completely distinguish whether
the option was set window-local or global.

Simple test case:

vim -u NONE
:autocmd OptionSet * echom expand('<amatch>') . ' ; ' . v:option_type
:setlocal spell  " prints "spell ; local"
:setglobal spell " prints "spell ; global"
:set spell       " prints "spell ; global" but also sets local option

As can be seen :setlocal and :setglobal can be distinguished but :set cannot.

Thus, in the example below :set spell will only set the global value of
matchpairs but not the local value:

vim -u NONE
:autocmd OptionSet * execute 'set' . v:option_type . ' matchpairs=a:b'
:set spell
:setglobal matchpairs? " prints matchpairs=a:b
:setlocal matchpairs?  " prints matchpairs=(:),{:},[:]
:set matchpairs?       " prints matchpairs=(:),{:},[:]
:setglobal spell? " prints spell
:setlocal spell?  " prints spell
:set spell?       " prints spell

I cannot claim that OptionSet violates its description (since its too vague
what v:option_type might be for the :set case). However, it would be nice to
have a mechanism to tie two options together such that they are in sync on the
local and global level (global level can already be achieved but local cannot).

A suggestion (which would fit the pattern :execute 'set' . v:option_type)
would be to set v:option_type to an empty string when an option was changed
with :set (in comparison to :setlocal and :setglobal).

Another idea would be to trigger the autocommand twice: once with
v:option_type="global" and once with v:option_type="local". However, I might
point out that doubling the amount of events might break some expectations of
listeners (which then relayed on a non-documented behaviour).

Note:
The same reasoning should be applied to :let-&xxx, :let-&l:xxx and :let-&g:xxx
(and maybe any other possibility to set an option).

Thanks

**Comment by andymass** [comment]
Note that `spell` is window-local and `matchpairs` is buffer-local, so there is a disconnect in your expectations regardless of the behavior of `OptionSet`.  Can I ask what `spell` has to do with `matchpairs` (why do you want to "bind" these options)?

`v:option_type` is set to "global" if and only if the global value has been set.  If it's global, indeed you cannot tell exactly whether the local setting changed or not, but you could look at whether the the local value matches the new value `v:option_new`; if so the effect is the same in that the global and local values are now identical.  This should work for many use-cases.

```
For buffer-local and window-local options:
	Command		 global value	    local value ~
      :set option=value	     set		set
 :setlocal option=value	      -			set
:setglobal option=value	     set		 -
```

**Comment by ghost** [comment]
Hi Andy, thanks for the prompt reply.

>  Note that spell is window-local and matchpairs is buffer-local, so there is a disconnect in your expectations regardless of the behavior of OptionSet. Can I ask what spell has to do with matchpairs (why do you want to "bind" these options)?

Sure you can. In my use case its actually 'spelllang' and 'matchpairs' -- I was to lazy for the 4 extra letters ;-). Both are buffer-local, so the window-local vs buffer-local concern is none. The use case is adding different quotation marks to 'matchpairs' according to the current (primary) language. As different language use the same quote symbols but in different combinations, I cannot add them simultaneously to 'matchpairs' (e.g. Danish + English: would be :set matchpairs=„:“,“:”, which yields strange behaviour for jumping between English quotes (second entry)). Hence, I want to update 'matchpairs' whenever 'spelllang' changes.

> [...] but you could look at whether the the local value matches the new value v:option_new; if so the effect is the same in that the global and local values are now identical. This should work for many use-cases.

It works for some but not for all cases. Here is a sequence which yield to an undesired setting for option B.
Your suggestion, if I understand correctly, is the following algorithm: changing option A (e.g. 'spelllang') locally/globally to x changes also option B (e.g. 'matchpairs') locally/globally to y. Also if A is changed globally to x and the new value matches the local value of A (which should therefore be x) then also change B locally to y.

```
global | local
A B | A B
" initial configuration: local and global are the same and B is in sync with A.
a b | a b
:setl A=x
a b | x y
:setl B=c " User somehow wants B locally to be c. This does not alter A.
a b | x c
:setg A=x
x y | x y " Fail, not supposed to change local B!
```

**Comment by ghost** [comment]
What is your opinion on extending the OptionSet event such that v:option_type is either the empty string or "global,local" if the option was changed via a :set.
From a quick look in option.c it seems that `opt_flags` is 0 when :set was used, which is different to OPT_LOCAL and OPT_GLOBAL. Thus, implementing that would be a not so complex change in the source code. If that's really all that it takes, then I would volunteer to implement that.

**Comment by andymass** [comment]
On one hand, I think `v:option_type` _should_ be 'global-local' (since this is what it's referred to in the help.)

On the other, changing the values will likely break someone's plugins or configs because code often checks for `v:option_type ==# 'global'`.  I wonder if simply firing two `OptionSet` events would be the best (as you said, this might break plugins but I imagine less so than changing `v:option_type`).

Another solution would be to add the more detailed information to `v:event`.  This would probably include both old global and local values (right now it is not clear which old value is used for `v:option_old`).  I would probably recommend that route, just would need to come up with sensible names for the entries.

**Comment by ghost** [comment]
Just to be on the same page. You suggest to leave the v:option_* stuff untouched and instead put the new steroids into v:event.
For example with the entries:

`option_global_new`
`option_global_old`
`option_local_new`
`option_local_old`

> just would need to come up with sensible names for the entries.

That's always the hardest task. Here is another naming suggestion (the current documented entries of v:event have no underscore and use abbreviations)

`optlocalnew`
`optlocalold`
`optglobalnew`
`optglobalold`

Maybe also add the key

`option_name` (or `optname`)

to not have to use `expand("<amatch>")` all the time. That way v:event contains really all information about the event.

To check whether the option was set local or global we have to compare `option_*_new` with `option_*_old`. If they are different, then the variable was set.
However, when setting an option to the same value it is not detectable that way, so we need an additional field, lets say

`option_scope`  (or `optscope`)

`option_scope` could be a comma separated list of the scopes, e.g. "local" (for setlocal), "global" (for setglobal), and "local,global" or "global,local" (for set; the user should not rely on the order of the entries).
It might later even be refined to something like "local,local-window" (the first `local` is to be backwards compatible) for a window-local option.

Now the next question arises, if we have `option_scope` does v:event always have to have both global and local values or only the values indicated by `option_scope`? I'd say it should only have the ones specified by `option_scope` as this seems less to implement and more on point for v:event. On the other hand the user cannot just pass all four entries without looking at `option_scope`. If we supply always all entries, then we must look up the (unrelated) option value in the other scope but that does not seem to be too hard.

Thoughts?

**Comment by justinmk** [comment]
```
optlocalnew
optlocalold
optglobalnew
optglobalold
```

`v:event` should be treated as if it were a parameter to an event handler, not a global. (It's only a global because of the weird design of Vim's autocmd system stemming from Vim's reluctance to graduate `FEAT_EVAL`. )

So `v:event` key names do not need to be so specific. They are intended to have context-dependent semantics. So these keynames would suffice, and could be used potentially in other contexts (i.e. other event-types):

```
newvalue
oldvalue
scope
```

The `scope` keys is already used for the DirChanged event and it also makes sense here.

> Maybe also add the key `option_name` (or `optname`)

Again, `name` is sufficient. `v:event` is _semantically_ local to the event-handler, its keys are valid _only_ in the context of the _current_ event.

**Comment by ghost** [comment]
@justinmk thank you for your inputs and thoughts.

> `v:event` should be treated as if it were a parameter to an event handler, not a global. [...]
> So `v:event` key names do not need to be so specific. They are intended to have context-dependent semantics. So these keynames would suffice [...]
> ```
> newvalue
> oldvalue
> scope
> ```
That background information is good to know. With that in mind we can indeed drop the "option" part on the variable names. However, changing an option with :set still sets two values, a local and a global one, and therefore has two old values.

With this in mind, I would suggest `newvalue` and `oldvalue` to be dictionaries with the key(s) being the scope were the option changed (as given by `scope`). For easier use I would also suggest making `scope` a list (instead of a comma separated string) with the entries being the keys for the dictionaries `newvalue` and `oldvalue`.

For a :set command this means that we would have something like
```
scope = ["global", "local"]
oldvalue = {"global": x, "local": y}
newvalue = {"global": z, "local": z}
```
(Note that both values in `newvalue` are `z`.)

(All this is of course to understand for the context of an `OptionSet` event. Other events might have different types for `scope`, `newvalue`, `oldvalue`.)

**Comment by justinmk** [comment]
There is no point in having nested lists and nested dicts. That  makes `v:event` complicated. If you really need extra stuff then I guess you will need extra `v:event` keys.

**Comment by andymass** [comment]
I agree with @justinmk.  Creating and freeing lists and dicts has a cost.  I would say just `{ 'scope': , 'newvalue': , 'globalold': , 'localold': }`, or the subset that makes sense, and `scope` = one of `'local'`, `'global'`, `'global-local'`.  Personally, I don't see an advantage to a list `scope` because it's not any easier to check if a list contains than a string contains.

**Comment by ghost** [comment]
Ok, then we keep it simple and flat and use the following keys

- `valuenew` (changed from `newvalue` to have `old`/`new` as a postfix)
- `localold`
- `globalold`

We can also go with `new`/`old` as prefixes, i.e. `newvalue`, `oldlocal`, `oldglobal`, if that's preferred. Personally I don't care.

The last two entries are only set if the option is changed locally or globally, respectively. If the option is changed locally and globally, then both are set. This in turn implies that `scope` is redundant, as we can derive it from the existence of the keys `localold`, `globalold` in `v:event`. Should we nevertheless add a `scope` entry in `v:event`?

To pick up an older thought raised above. I always found it quiet unsatisfying that I can access the values with `v:option_old` et al. but have to fall back to `expand("<amatch>")` when needing the name of the option. Would it harm to include another entry in `v:event` named `name` containing the long option name? Then `v:event` would contain all the information of the OptionSet event; no additional variables (e.g. `v:option_type` or `<amatch>`) needed. In particular when the autocommand calls a function only `v:event` needs the be passed:
```
autocmd OptionSet * call SomeFunction(v:event) " or as deepcopy(v:event)
```

**Comment by chrisbra** [comment]
closing for #4118
