### ISSUE TITLE
do not open cmd.exe in new visible window when opening a file from https://

### ISSUE THREAD

**Issue by prabirshrestha** [vim/vim#4045]
Run this command `:e https://httpbin.org/ip`. This will open a new cmd and will autoclose when it is done.
Is it possible to have some flag to open it in a hidden window or have a flag to open it using the terminal window inside vim?

This didn't bother me before but now I have been giving [dwm - Dynamic window manager](https://github.com/prabirshrestha/dwm-win32) a try in Windows and it feels a bit irritating because it takes one of the spot on the tiles and closes.

**Comment by mattn** [comment]
Did you try `set guioptions+=!` ?

**Comment by prabirshrestha** [comment]
That is exactly what I wanted. Thanks.
