### ISSUE TITLE
"E431: Format error in tags file" with long tag name

### ISSUE THREAD

**Issue by blueyed** [vim/vim#4051]
Given a `tags` file with the following contents, `:tj /foo` will fail:

> E431: Format error in tags file "tags"                                               
> Before byte 540
> E426: tag not found: foo

```tags
1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678	django/contrib/admin/templates/admin/edit_inline/stacked.html	16;"	j	line:16	language:HTML
```

It appears to go through https://github.com/vim/vim/blob/ab350f89f9646e07aefe16a32ba3ddb847496b4a/src/tag.c#L2141 here, but have not really investigated.

Removing the 8 at the end fixes it, so this appears to just be enough to trigger it.

**Comment by brammool** [comment]
> Given a `tags` file with the following contents, `:tj /foo` will fail:
> 
> > E431: Format error in tags file "tags"                                               
> > Before byte 540
> > E426: tag not found: foo
> 
> ```tags
> 1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678	django/contrib/admin/templates/admin/edit_inline/stacked.html	16;"	j	line:16	language:HTML
> ```
> 
> It appears to go through https://github.com/vim/vim/blob/ab350f89f9646e07aefe16a32ba3ddb847496b4a/src/tag.c#L2141 here, but have not really investigated.
> 
> Removing the 8 at the end fixes it, so this appears to just be enough to trigger it.

There is a check for a line that is too long (around line 1942) that
should skip that line.  Not sure why that doesn't work in this case.

-- 
If you put 7 of the most talented OSS developers in a room for a week
and asked them to fix a bug in a spreadsheet program, in 1 week
you'd have 2 new mail readers and a text-based web browser.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by andymass** [comment]
The check for too-long lines is never hit because `orgpat.headlen == 0` (and even if so `tagp.tagname_end != NULL`).  The check would need to be moved up.  Also, removing 8 at the end of the tag name doesn't actually make this valid; the error is just more silent.   Tag file lines can be only 510 chars long (`LSIZE=512` minus newline and nul).

```patch
 src/tag.c | 44 ++++++++++++++++++++++----------------------
 1 file changed, 22 insertions(+), 22 deletions(-)

diff --git a/src/tag.c b/src/tag.c
index f109470bc..d78eaebb0 100644
--- a/src/tag.c
+++ b/src/tag.c
@@ -1921,6 +1921,28 @@ line_read_in:
 	    }
 
 parse_line:
+	    if (vim_strchr(lbuf, NL) == NULL)
+	    {
+		/* Truncated line, ignore it.  Has been reported for
+		 * Mozilla JS with extremely long names. */
+		if (p_verbose >= 5)
+		{
+		    verbose_enter();
+		    msg(_("Ignoring long line in tags file"));
+		    verbose_leave();
+		}
+#ifdef FEAT_TAG_BINS
+		if (state != TS_LINEAR)
+		{
+		    /* Avoid getting stuck. */
+		    linear = TRUE;
+		    state = TS_LINEAR;
+		    vim_fseek(fp, search_info.low_offset, SEEK_SET);
+		}
+#endif
+		continue;
+	    }
+
 	    /*
 	     * Figure out where the different strings are in this line.
 	     * For "normal" tags: Do a quick check if the tag matches.
@@ -1942,28 +1964,6 @@ parse_line:
 		if (tagp.tagname_end == NULL)
 #endif
 		{
-		    if (vim_strchr(lbuf, NL) == NULL)
-		    {
-			/* Truncated line, ignore it.  Has been reported for
-			 * Mozilla JS with extremely long names. */
-			if (p_verbose >= 5)
-			{
-			    verbose_enter();
-			    msg(_("Ignoring long line in tags file"));
-			    verbose_leave();
-			}
-#ifdef FEAT_TAG_BINS
-			if (state != TS_LINEAR)
-			{
-			    /* Avoid getting stuck. */
-			    linear = TRUE;
-			    state = TS_LINEAR;
-			    vim_fseek(fp, search_info.low_offset, SEEK_SET);
-			}
-#endif
-			continue;
-		    }
-
 		    /* Corrupted tag line. */
 		    line_error = TRUE;
 		    break;
```

**Comment by brammool** [comment]
> The check for too-long lines is never hit because `orgpat.headlen == 0` (and
> even if so `tagp.tagname_end != NULL`).  The check would need to be moved up.
> Also, removing 8 at the end of the tag name doesn't actually make this valid;
> the error is just more silent.   Tag file lines can be only 510 chars long
> (`LSIZE=512` minus newline and nul).

How about a test?

-- 
It is hard to understand how a cemetery raised its burial
cost and blamed it on the cost of living.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by andymass** [comment]
Patch and test at PR https://github.com/vim/vim/pull/4084
