### ISSUE TITLE
:w "E212 Can't open file for writing" when directory is not exists

### ISSUE THREAD

**Issue by vitaly-zdanevich** [vim/vim#4052]
Vim really cannot create a directory? Or as minimum I think that we can say to the user that he must create a directory manually.

**Comment by brammool** [comment]
The error is correct.  Quite often when this happens there is a mistake in the command, creating the directory would be the wrong solution.
There can be other reasons, such as the directory not being readable.  It's hard to give a better error message that is accurate.
