### ISSUE TITLE
vimdiff with a non-existing file on one side leads to strange view

### ISSUE THREAD

**Issue by Porkepix** [vim/vim#4053]
See joined screenshot, on the left side, with the non-existing file, there's this blue form which is kinda strange and hard to explain.

![screenshot from 2019-02-28 17-58-22](https://user-images.githubusercontent.com/709500/53583768-82566c80-3b82-11e9-871e-42fb6023c009.png)

**Comment by mgedmin** [comment]
That looks like a disagreement between vim and your terminal about the width of some of those Unicode code point sequences on the previous line.

**Comment by chrisbra** [comment]
I think @mgedmin is right here and I don't think there is anything for us to do here. Closing.

**Comment by mgedmin** [comment]
Well, vim _could_ add workaround to make such disagreements less painful to the user (e.g. explicit cursor positioning commands after every grapheme cluster of uncertain width), but the question is, should it?
