### ISSUE TITLE
Want to translate strings for appdata.xml (gnome-software etc.)

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#4054]
In gnome-software i see some text for Vim that i would like to translate.

It seems to be the same as https://github.com/flathub/org.vim.Vim/blob/master/org.vim.Vim.appdata.xml but i cant seem to find any appdata.xml file here.

So how/where to translate it?

**Comment by k-takata** [comment]
It might be better to ask to the gnome project, not here.

**Comment by chrisbra** [comment]
or ask on the github project tracker. I think it is wrong here, closing.

**Comment by scootergrisen** [comment]
I think appdata.xml is not just for gnome-software but some metadata that can be used my many software so show information about the package.
Like in KDE Discovery it can show the same data i think.
