### ISSUE TITLE
<Esc> in rhs of a :cmap runs command instead of cancelling it

### ISSUE THREAD

**Issue by sedm0784** [vim/vim#4057]
Steps to reproduce:

1. Run vim:

        vim --clean

2. Set up a `cmap`

        :cnoremap <Esc> <Esc>

3. Start typing a command, but do *not* press Enter to run it

        :echo "hi!"

4. Press `<Esc>`

Expected results: The command should be cancelled.
Observed results: Vim says "hi!"

Tested in Vim 8.0.1420

**Comment by andymass** [comment]
I think this is by design (see `:help c_Esc`).  Is there a reason you need to have `<Esc>` inside the mapping?  What is your use-case?

**Comment by chrisbra** [comment]
That is vi compatible and has been discussed before. I think this can be closed.

**Comment by sedm0784** [comment]
Thanks for the clarification. I didn’t find it in the docs because I was looking in map.txt. It’s not a problem: [I can use `<C-C>` instead](https://vi.stackexchange.com/a/19060/343). I was just surprised/confused when I first discovered it.
