### ISSUE TITLE
Bug: rv! does not load lowercase marks if the path is absolute  path.

### ISSUE THREAD

**Issue by kgfly** [vim/vim#4064]
Windows 64bit 8.1.829.

My viminfo file is (c:\1):

```
> M:\aa\bbb\1
	*	1551574438	0
	"	3	0
	a	1	0

> ~\ttt\1.cpp
	*	1551574435	0
	"	5	0
	b	3	0
```

When call ":rv! c:\1", vim only loads lowecase marks if the path is relative path, etc marks from "> ~\ttt\1.cpp"

It does not load marks from "> M:\aa\bbb\1"

**Comment by martin-macrometa** [comment]
I cannot reproduce this bug on Linux so it seems to be something windows-specific.
