### ISSUE TITLE
reg_executing() returns different values before/after a change on the buffer

### ISSUE THREAD

**Issue by machakann** [vim/vim#4066]
Hi, I found an unexpected behavior of `reg_executing()`. It seems the `reg_executing()` function returns an empty string after a change on the buffer, even in a complex-repeat action.

Please try to run the following script.

```vim
function! TestFunc() abort
  echomsg "before: " . reg_executing()
  normal! ia
  echomsg "after: " . reg_executing()
endfunction
nnoremap w :<C-u>call TestFunc()<CR>

messages clear
let @q = "w"
normal! @q
```

What I expect is:

```vim
before: q
after: q
```

What I got is:

```vim
before: q
after: 
```

I'm using Vim 8.1.985 on windows 10.

**Comment by machakann** [comment]
Thank you!

**Comment by machakann** [comment]
Excuse me, @ichizok pointed out that `reg_executing()` still returns an empty string if `getchar()` is used.

```vim
function! TestFunc() abort
  echomsg "before: " . reg_executing()
  call getchar(0)
  echomsg "after: " . reg_executing()
endfunction
nnoremap w :<C-u>call TestFunc()<CR>

messages clear
let @q = "w"
normal! @q
```

**Comment by brammool** [comment]
> Excuse me, @ichizok pointed out that `reg_executing()` still returns an empty string if `getchar()` is used.
> 
> ```vim
> function! TestFunc() abort
>   echomsg "before: " . reg_executing()
>   call getchar(0)
>   echomsg "after: " . reg_executing()
> endfunction
> nnoremap w :<C-u>call TestFunc()<CR>
> 
> messages clear
> let @q = "w"
> normal! @q
> ```

Well, it is done executing the register then.  But it might be
unexpected that the reg_executing() return value changes here.
I'll make a patch for that.

-- 
He who laughs last, thinks slowest.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
