### ISSUE TITLE
Popup flickering (ycm)

### ISSUE THREAD

**Issue by BigfootN** [vim/vim#407]
Hello,

I've been trying to use [youcompleteme plugin](https://github.com/Valloric/YouCompleteMe), but I don't know why when I have suggestions from the popup menu [it flickers](https://vid.me/Vt0s). 

Here is the output of `vim --version`:

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul 11 2015 08:45:35)
Included patches: 1-778
Compiled by Arch Linux
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
+balloon_eval    +float           +mouse_urxvt     -tag_any_white
+browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
+clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      +toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  +lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      +X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      -sniff           +xsmp_interact
+eval            +mouse_dec       +startuptime     +xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz  -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype  -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -lncurses -lelf -lnsl   -lacl -lattr -lgpm -ldl  -L/usr/lib -llua -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/core_perl/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc -L/usr/lib/python2.7/config -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic   -lruby -lpthread -lgmp -ldl -lcrypt -lm  -L/usr/lib    
```

Here is the result of `uname -r`:

```
4.1.6-1-ARCH
```

Other info:

Desktop environment: cinnamon
Vimrc: [vimrc](https://github.com/ScriptorNY/Dotfiles/blob/master/vimrc)
Xresources: [Xresources](https://github.com/ScriptorNY/Dotfiles/blob/master/Xresources)
Terminal: urxvt

graphic card: gtx 970
driver: nvidia

Thank you very much for any help :)

**Comment by raymond-w-ko** [comment]
If are feeling adventurous, you can try the final patch mentioned in the discussion group below by mattn. Note that it still might have glitches in certain cases, but I have been using it for quite a while and haven't noticed anything too crazy. There are also other patches before the last one which will definitely eliminate flicker but probably have very noticeable glitches.

https://groups.google.com/forum/#!msg/vim_dev/kFmrNmdnpSs/GMCMHodLflEJ

https://gist.github.com/6240679

**Comment by BigfootN** [comment]
Thank you very much I'll look at it and I'll tell you if it resolved anything :)

Thank you for your time :)

**Comment by BigfootN** [comment]
Hello,

I'm really sorry, but I didn't have much time these last days. So I've been trying to figure out how to apply the patch. So I took a look [at this page](http://www.vim.org/patches.php) and it didn't seem to have worked, the file is still the same.

Thank you very much in advance :)

**Comment by vim-ml** [comment]
Hi ScriptorNY!

On So, 06 Sep 2015, ScriptorNY wrote:

> I'm really sorry, but I didn't have much time these last days. So I've
> been trying to figure out how to apply the patch. So I took a look [at
> this page](http://www.vim.org/patches.php) and it didn't seem to have
> worked, the file is still the same.

Download the mentioned patch https://gist.github.com/mattn/6240679 to 
your vim source directory src/ as redraw.diff

In the Vim source repository, go to the src/ directory:
cd src
and apply the patch:
patch -p2 < redraw.diff

configure and build your vim like normal:

./configure --with-features=huge --prefix...
make
make install

Best,

## Christian

Wir sollten uns mit den großen Problemen beschäftigen, solange sie
noch ganz klein sind.
        -- Jadwiga Rutkowska

**Comment by BigfootN** [comment]
Thank you very much, I'll try that then :)

**Comment by BigfootN** [comment]
So, I tried it and it surely is better even though I must admit it still has some flickering in gvim. But, in vim there is absolutely no such thing (so in vim it's perfect :) ).

Thank you again for all your help and patience :)
