### ISSUE TITLE
[Netrw] "gx" does not process the port number in the URL

### ISSUE THREAD

**Issue by schoettl** [vim/vim#4082]
Example:

https://example.com:1234/index.html

Pressing `gx` on the first part of the URL opens `https://example.com/` instead.
Pressing `gx` on the last part has no effect.

Version:
VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb  7 2019 19:47:28)

Related to NetrwBrowseX, #2493

**Comment by cecamp** [comment]
Have you read the help for gx?  Netrw uses vim's expand() function, which doesn't have a <url> option.  The three most pertinent are:  <cfile>, <cword>, and <cWORD>.   By default, netrw uses <cfile>, but lets you choose whatever you wish -- see  :help g:netrw_gx.

Now, that's not the whole story, unfortunately.  Network-wise, netrw is glue -- it mates various tools with vim.  By default, netrw uses curl for getting a remote page.  Again, there are other possibilities; see :help g:netrw_http_cmd.  The default actually varies depending on what you have for executables: curl, wget, elinks, fetch, links; in that order.  Curl didn't seem to handle the example you gave when I tried it directly from the command line; it just hung.

So, try picking a tool that works for you, and use g:netrw_http_cmd.

**Comment by cecamp** [comment]
Have you read the help for gx?  Netrw uses vim's `expand()` function, which doesn't have a `<url>` option.  The three most pertinent are:  `<cfile>`, `<cword>`, and `<cWORD>`.   By default, netrw uses `<cfile>`, but lets you choose whatever you wish -- see  :help `g:netrw_gx`.

Now, that's not the whole story, unfortunately.  Network-wise, netrw is glue -- it mates various tools with vim.  By default, netrw uses curl for getting a remote page.  Again, there are other possibilities; see :help `g:netrw_http_cmd`.  The default varies depending on what you have for executables: curl, wget, elinks, fetch, links; in that order.  Curl didn't seem to handle the example you gave when I tried it directly from the command line; it just hung.

**Comment by schoettl** [comment]
Oh, OK, thanks!

Shouldn't vim provide an `<url>` for `expand()`? I would create an issue for that.

I think curl hangs with the example URL because it waits for a timeout. It works with a real example URL with port (on my system at least).

**Comment by brammool** [comment]
> Oh, OK, thanks!
> 
> Shouldn't vim provide an `<url>` for `expand()`? I would create an issue for that.

<cfile> also handles a URL, but this assumes that ":" is in 'isfname'.
That can be fixed.

-- 
George:  "I just got a new set of golf clubs for my wife!"
  John:  "Great trade!"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
