### ISSUE TITLE
getting rid on 7.3 when updating

### ISSUE THREAD

**Issue by AHL96** [vim/vim#409]
i just updated to 7.4 MacVim, but when I type "vim" in my terminal it says my version is 7.3. when I click on the macvim app it shows 7.4.  I just want to uninstall 7.3. Thanks

**Comment by nuko8** [comment]
You don't need to uninstall 7.3.

Open MacVim as usual and do "h: mvim", then you'll get an instruction to open that app from a terminal, 

(I think the most preferable place of questions like yours is MacVim's mailing list, not here.)

**Comment by chdiza** [comment]
> You don't need to uninstall 7.3.

Indeed, you don't _want_ to remove 7.3, either, as that's the system `vim`.

**Comment by chrisbra** [comment]
please keep the issue for bugs and patches. Discuss user support on the appropriate forum, e.g. vim-use maillinglist or in your case macvim specific forum.
