### ISSUE TITLE
BufWritePre not working on startup until sourced

### ISSUE THREAD

**Issue by ghost** [vim/vim#4092]
When I open a new project and save the file `BufWritePre` doesn't work. I have tried it in my `~/.vimrc` and even `~/.vim/after/plugin/spaces.vim`

```
set list
set listchars=trail:·

autocmd BufWritePre <buffer> :%s/\s\+$//e
```

Running `vim -V` I can see the file definitely gets sourced

```
sourcing "/Users/carlos/.vim/after/plugin/new.vim"
finished sourcing /Users/carlos/.vim/after/plugin/new.vim
Reading viminfo file "/Users/carlos/.viminfo" info oldfiles
```

Only when I manually source the file does it work.

**Comment by chrisbra** [comment]
why are you using a `<buffer>` autocommand?

**Comment by ghost** [comment]
New to vim I thought by adding `<buffer>` would ensure it only ran for the file I am in.

You're right, I removed it and it worked.

Would you mind explaining why it didn't work with `<buffer>`
