### ISSUE TITLE
updated ratpoison.vim syntax

### ISSUE THREAD

**Issue by trapd00r** [vim/vim#4093]
Hey,
For some reason I can no longer post to the vim-dev mailinglist. I just want the updated [ratpoison.vim](https://github.com/trapd00r/vim-syntax-ratpoison/blob/master/syntax/ratpoison.vim) with changes from #1721 to be taken in consideration. (I am the maintainer).

**Comment by k-takata** [comment]
The ratpoison.vim file included in this repository looks slightly different from yours.
Bram had removed the version check for Vim 6 or older versions and removed `HiLink` command.
Could you include these changes?

https://github.com/vim/vim/blob/55d81cd2a15d93dba89b2ff1c988d82789919b6b/runtime/syntax/ratpoison.vim#L8-L9

https://github.com/vim/vim/blob/55d81cd2a15d93dba89b2ff1c988d82789919b6b/runtime/syntax/ratpoison.vim#L249-L262

**Comment by trapd00r** [comment]
[Updated now](https://github.com/trapd00r/vim-syntax-ratpoison/blob/master/syntax/ratpoison.vim).

**Comment by brammool** [comment]
I'll include it, thanks.  But keep the previous-maintainer line
