### ISSUE TITLE
Unicode showbreak character not rendered properlly with breakindent

### ISSUE THREAD

**Issue by zhen-huan-hu** [vim/vim#4096]
Version 8.1.1
OS: Windows 10
Font: Consolas

Setting:
```
let &showbreak = "\u21AA"
set breakindent breakindentopt+=sbr
```

The unicode showbreak character is two characters wide and the right half would not show if the line starts with no preceding white spaces.

![image](https://user-images.githubusercontent.com/9272721/54133053-5e492580-43e3-11e9-84ce-db93f8dabda5.png)

**Comment by bfrg** [comment]
Just append a whitespace to `showbreak`. This is what I have in my `.vimrc`:
```vim
set showbreak=↪\
```

**Comment by zhen-huan-hu** [comment]
It's even worse now:

![image](https://user-images.githubusercontent.com/9272721/54140294-4d9fac00-43f1-11e9-8a21-64553913bad4.png)

**Comment by mattn** [comment]
>The unicode showbreak character is two characters wide and the right half would not show if the line starts with no preceding white spaces.

[EastAsianWidth.txt](http://www.unicode.org/Public/11.0.0/ucd/EastAsianWidth.txt) define \u21AA as N (Neutral), So it's not two character width. It's not even Ambiguous width.
