### ISSUE TITLE
v8.1.1005 is mis-tagged

### ISSUE THREAD

**Issue by Jesin** [vim/vim#4101]
[tags/v8.1.1005](https://github.com/vim/vim/releases/tag/v8.1.1005) should point to 55d81cd2a15d93dba89b2ff1c988d82789919b6b, but it incorrectly points to the same thing as [tags/v8.1.1004](https://github.com/vim/vim/releases/tag/v8.1.1004) instead.

**Comment by brammool** [comment]
Fixed it

**Comment by tonymec** [comment]
@chrisbra : On the Mercurial mirror there is no tag v8.1.1005 AFAICT: the last changeset has no tag other than "tip", and the last line in .hgtags points to v8.1.1004

Best regards,
Tony.

**Comment by chrisbra** [comment]
> On the Mercurial mirror there is no tag v8.1.1005 AFAICT: the last changeset has no tag other than "tip", and the last line in .hgtags points to v8.1.1004

should be fixed now

**Comment by tonymec** [comment]
> > On the Mercurial mirror there is no tag v8.1.1005 AFAICT: the last changeset has no tag other than "tip", and the last line in .hgtags points to v8.1.1004
> 
> should be fixed now

Yes, it is; thanks :-)

Best regards,
Tony.
