### ISSUE TITLE
feature request: external tags lookup program

### ISSUE THREAD

**Issue by fefe17** [vim/vim#4104]
I regularly use vim for code reviews of huge code bases. tags files of a gigabyte or more are not uncommon for me. This does not present a performance issue since they are sorted and vim uses binary search, but it does present a space issue.

I would therefore like to be able to configure an external tags lookup program. The command line is the word to lookup, and it outputs the matching lines out of the tags file. Then I could write a tool that stores the tags data in a compressed form and allows fast lookups on it.

Right now I'm in the (rather ridiculous, I find) situation that the tags file for a current project is 270MB but the full text index (!) is 1.8 MB. The tags file was already created with ctags -n as to contain the line numbers instead of regexes.

If you do this for me, I will write such a tool and will release it as open source.

**Comment by vim-ml** [comment]
On 2019-03-12, fefe17 wrote:
> I regularly use vim for code reviews of huge code bases. tags files of a
> gigabyte or more are not uncommon for me. This does not present a performance
> issue since they are sorted and vim uses binary search, but it does present a
> space issue.
> 
> I would therefore like to be able to configure an external tags lookup program.
> The command line is the word to lookup, and it outputs the matching lines out
> of the tags file. Then I could write a tool that stores the tags data in a
> compressed form and allows fast lookups on it.
> 
> Right now I'm in the (rather ridiculous, I find) situation that the tags file
> for a current project is 270MB but the full text index (!) is 1.8 MB. The tags
> file was already created with ctags -n as to contain the line numbers instead
> of regexes.
> 
> If you do this for me, I will write such a tool and will release it as open
> source.

There is already GNU Global which does this.

    https://www.gnu.org/software/global/

It comes with a plugin for Vim and instructions for using it instead
of cscope as an external symbol database.

By setting 'cscopetag', you can have Vim use GNU Global instead of
its internal tags facility to respond to Ctrl-] and other tags
commands.  See

    :help 'cscopetag'
    :help cscope

Regards,
Gary

**Comment by andymass** [comment]
What is the compression ratio you can achieve using eg tar.gz?

Are you alreadyusing relative filenames?

**Comment by fefe17** [comment]
Thanks Gary, I was not aware of that. Awesome!

**Comment by fefe17** [comment]
Hmm, OK, so I looked at GNU global and cscope.

GNU global does not use a compressed index, so it is still much larger than necessary.
Which leaves me with option B: Do what GNU global does and reimplement the cscops "API".
This strikes me as almost comically bad. Basically, GNU global implements an interactive line based terminal user interface that looks enough like cscope so that vim's reverse emulation of a user using cscope works.

I don't get why this has to be so complicated. I'll provide a little program that vim can call when I ctrl-] on a word, and it outputs either the (also horrible to parse) tags syntax, or, and this would be my preference, it would output something like the output of grep -n. filename:lineno:contents_of_that_line.

How is that not vastly superior than this horrendous hackery and layering of heuristics to parse ambiguous and under-defined "formats"?

**Comment by chrisbra** [comment]
I think the new `tagfunc` that has been included as of 45e18cbdc40afd8144d20dc can help you.
