### ISSUE TITLE
autoindent with <CR><CR> in the middle of a line keeps trailing whitespace

### ISSUE THREAD

**Issue by blueyed** [vim/vim#4119]
`vim -Nu NONE -c 'set autoindent' -c 'norm i    foo bar baz' -c 'exe "norm 2bea\<CR>\<CR>"' -c 'echo len(getline(2))'` displays "4", i.e.

```
    foo bar_ baz
```
with the cursor at "_" and pressing Enter twice results in:
```
    foo bar
    
    baz
```

Note that there are four spaces in line 2.

The help for 'autoindent' says:

> Copy indent from current line when starting a new line (typing <CR>
> in Insert mode or when using the "o" or "O" command).  If you do not
> type anything on the new line except <BS> or CTRL-D and then type
> <Esc>, CTRL-O or <CR>, the indent is deleted again.

So the "the indent is deleted again" is missing here.

This works when using it at the end of a line, so it looks like having the "baz" there in between (but only "moved", not typed) might cause this.

**Comment by brammool** [comment]
Daniel Hahler wrote:

> `vim -Nu NONE -c 'set autoindent' -c 'norm i    foo bar baz' -c 'exe "norm 2bea\<CR>\<CR>"' -c 'echo len(getline(2))'` displays "4", i.e.
> 
> ```
>     foo bar_ baz
> ```
> with the cursor at "_" and pressing Enter twice results in:
> ```
>     foo bar
>     
>     baz
> ```
> 
> Note that there are four spaces in line 2.
> 
> The help for 'autoindent' says:
> 
> > Copy indent from current line when starting a new line (typing <CR>
> > in Insert mode or when using the "o" or "O" command).  If you do not
> > type anything on the new line except <BS> or CTRL-D and then type
> > <Esc>, CTRL-O or <CR>, the indent is deleted again.
> 
> So the "the indent is deleted again" is missing here.
> 
> This works when using it at the end of a line, so it looks like having
> the "baz" there in between (but only "moved", not typed) might cause
> this.

Yeah, this looks wrong.  Must be a very old problem.
Let's see if I can fix it.

-- 
hundred-and-one symptoms of being an internet addict:
68. Your cat always puts viruses on your dogs homepage

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
