### ISSUE TITLE
Wrong indentation when typing a list of dict in `yaml` file

### ISSUE THREAD

**Issue by vimagick** [vim/vim#412]
I want to compose a list of dict in `yaml` file.

```
- hello: world
  foo: bar
- hello: world
  foo: bar
- hello: world
  foo: bar
```

When I type `foo:`, vim reindent to the beginning of line:

```
- hello: world
foo:
```

I shouldn't reindent in this case.

**Comment by chrisbra** [comment]
Hi Kev++!

On So, 06 Sep 2015, Kev++ wrote:

> I want to compose a list of dict in `yaml` file.
> 
> ```
> - hello: world
>   foo: bar
> - hello: world
>   foo: bar
> - hello: world
>   foo: bar
> ```
> 
> When I type `foo:`, vim reindent to the beginning of line:
> 
> ```
> - hello: world
> foo:
> ```
> 
> I shouldn't reindent in this case.

Please contact the maintainer of the indent file, before creating an 
issue here. He should fix it and send an update of the indent file to 
Bram for distribution with Vim.

Best,

## Christian

Zur Lebensart gehört, daß man auch gegen sich höflich sei.
        -- Jean Paul

**Comment by vimagick** [comment]
OK. I'll contact the maintainer. Tell him about this issue.
:smile:

**Comment by chrisbra** [comment]
thanks. I'll close this ticket for now.
