### ISSUE TITLE
--startuptime 

### ISSUE THREAD

**Issue by kerwinxu** [vim/vim#4120]
win10vc2017

locale set cost  many times . why ?

times in msec
 clock   self+sourced   self:  sourced script
 clock   elapsed:              other lines

000.000  000.000: --- VIM STARTING ---
001.000  001.000: Allocated generic buffers
031.000  030.000: locale set
059.000  028.000: GUI prepared
059.000  000.000: clipboard setup
059.000  000.000: window checked
060.000  001.000: inits 1
072.000  012.000: parsing arguments
093.000  021.000: expanding arguments
096.000  003.000: shell init
096.000  000.000: inits 2
096.000  000.000: init highlight
109.000  003.000  003.000: sourcing E:\home\kerwin\vimfiles\autoload\plug.vim
129.000  000.000  000.000: sourcing D:\Vim\vim80\ftoff.vim
144.000  003.000  003.000: sourcing D:\Vim\vim80\syntax\syncolor.vim
145.000  007.000  004.000: sourcing D:\Vim\vim80\syntax\synload.vim
165.000  000.000  000.000: sourcing D:\Vim\vim80\lang/menu_chinese_gb.936.vim
165.000  003.000  003.000: sourcing D:\Vim\vim80\lang\menu_zh_cn.cp936.vim
169.000  000.000  000.000: sourcing D:\Vim\vim80\autoload\paste.vim
177.000  018.000  015.000: sourcing D:\Vim\vim80/menu.vim
178.000  031.000  013.000: sourcing D:\Vim\vim80\filetype.vim
178.000  042.000  004.000: sourcing D:\Vim\vim80\syntax\syntax.vim
181.000  000.000  000.000: sourcing D:\Vim\vim80\filetype.vim
184.000  000.000  000.000: sourcing D:\Vim\vim80\ftplugin.vim
187.000  000.000  000.000: sourcing D:\Vim\vim80\indent.vim
187.000  054.000  012.000: sourcing D:\Vim\vim80/defaults.vim
192.000  061.000  007.000: sourcing D:\Vim\vim80/vimrc_example.vim
194.000  000.000  000.000: sourcing D:\Vim\vim80/mswin.vim
197.000  000.000  000.000: sourcing D:/gtags/share/gtags/gtags.vim
200.000  000.000  000.000: sourcing D:/gtags/share/gtags/gtags-cscope.vim
207.000  000.000  000.000: sourcing D:\Vim\vim80/delmenu.vim
213.000  001.000  001.000: sourcing D:\Vim\vim80\lang\menu_zh_cn.utf-8.vim
223.000  014.000  013.000: sourcing D:\Vim\vim80/menu.vim
231.000  000.000  000.000: sourcing D:\Vim\vim80\syntax\syncolor.vim
235.000  001.000  001.000: sourcing D:\Vim\vim80\syntax\syncolor.vim
239.000  013.000  012.000: sourcing E:\home\kerwin\vimfiles\colors\solarized.vim
249.000  001.000  001.000: sourcing D:\Vim\vim80\syntax\syncolor.vim
252.000  000.000  000.000: sourcing D:\Vim\vim80\syntax\syncolor.vim
256.000  012.000  011.000: sourcing E:\home\kerwin\vimfiles\colors\solarized.vim
264.000  000.000  000.000: sourcing D:\Vim\vim80\filetype.vim
267.000  000.000  000.000: sourcing D:\Vim\vim80\ftplugin.vim
269.000  000.000  000.000: sourcing D:\Vim\vim80\indent.vim
452.000  002.000  002.000: sourcing D:/Vim/vim80/ftoff.vim
469.000  000.000  000.000: sourcing E:/home/kerwin/vimfiles/pugged/slimv/ftdetect/clojure.vim
493.000  000.000  000.000: sourcing E:/home/kerwin/vimfiles/pugged/vim-fugitive/ftdetect/fugitive.vim
495.000  018.000  018.000: sourcing D:/Vim/vim80/filetype.vim
500.000  000.000  000.000: sourcing D:/Vim/vim80/ftplugin.vim
504.000  000.000  000.000: sourcing D:/Vim/vim80/indent.vim
509.000  000.000  000.000: sourcing D:/Vim/vim80/filetype.vim
514.000  000.000  000.000: sourcing D:/Vim/vim80/ftplugin.vim
519.000  000.000  000.000: sourcing D:/Vim/vim80/indent.vim
519.000  416.000  293.000: sourcing $HOME\vimfiles\vimrc
519.000  007.000: sourcing vimrc file(s)
526.000  000.000  000.000: sourcing E:/home/kerwin/vimfiles/pugged/gundo.vim/plugin/gundo.vim
533.000  001.000  001.000: sourcing E:/home/kerwin/vimfiles/pugged/ack.vim/plugin/ack.vim
539.000  001.000  001.000: sourcing E:/home/kerwin/vimfiles/pugged/surround.vim/plugin/surround.vim
545.000  000.000  000.000: sourcing E:/home/kerwin/vimfiles/pugged/rainbow_parentheses.vim/plugin/rainbow_parentheses.vim
557.000  007.000  007.000: sourcing E:/home/kerwin/vimfiles/pugged/YankRing.vim/plugin/yankring.vim
563.000  000.000  000.000: sourcing E:/home/kerwin/vimfiles/pugged/vim-gutentags/plugin/gutentags.vim
569.000  000.000  000.000: sourcing E:/home/kerwin/vimfiles/pugged/gutentags_plus/plugin/gutentags_plus.vim
575.000  000.000  000.000: sourcing E:/home/kerwin/vimfiles/pugged/vim-fugitive/plugin/fugitive.vim
581.000  000.000  000.000: sourcing E:/home/kerwin/vimfiles/pugged/gina.vim/plugin/gina.vim
587.000  000.000  000.000: sourcing E:/home/kerwin/vimfiles/pugged/vim-preview/plugin/preview.vim
594.000  001.000  001.000: sourcing D:/Vim/vim80/pack/dist/opt/matchit/plugin/matchit.vim
613.000  000.000  000.000: sourcing D:/Vim/vim80/plugin/getscriptPlugin.vim
615.000  000.000  000.000: sourcing D:/Vim/vim80/plugin/gzip.vim
618.000  000.000  000.000: sourcing D:/Vim/vim80/plugin/logiPat.vim
620.000  000.000  000.000: sourcing D:/Vim/vim80/plugin/manpager.vim
623.000  000.000  000.000: sourcing D:/Vim/vim80/plugin/matchparen.vim
626.000  001.000  001.000: sourcing D:/Vim/vim80/plugin/netrwPlugin.vim
629.000  000.000  000.000: sourcing D:/Vim/vim80/plugin/rrhelper.vim
632.000  000.000  000.000: sourcing D:/Vim/vim80/plugin/spellfile.vim
635.000  001.000  001.000: sourcing D:/Vim/vim80/plugin/tarPlugin.vim
637.000  000.000  000.000: sourcing D:/Vim/vim80/plugin/tohtml.vim
640.000  001.000  001.000: sourcing D:/Vim/vim80/plugin/vimballPlugin.vim
643.000  001.000  001.000: sourcing D:/Vim/vim80/plugin/zipPlugin.vim
643.000  110.000: loading plugins
645.000  002.000: loading packages
645.000  000.000: loading after plugins
645.000  000.000: inits 3
648.000  001.000  001.000: sourcing $VIMRUNTIME\menu.vim
830.000  184.000: starting GUI
832.000  002.000: reading viminfo
839.000  007.000: GUI delay
839.000  000.000: setting raw mode
839.000  000.000: start termcap
839.000  000.000: clearing screen
1104.000  001.000  001.000: sourcing D:/Vim/vim80/scripts.vim
1115.000  001.000  001.000: sourcing E:/home/kerwin/vimfiles/pugged/rainbow_parentheses.vim/autoload/rainbow_parentheses.vim
1174.000  000.000  000.000: sourcing D:/Vim/vim80/ftplugin/text.vim
1187.000  002.000  002.000: sourcing E:/home/kerwin/vimfiles/pugged/vim-gutentags/autoload/gutentags.vim
1207.000  364.000: opening buffers
1225.000  018.000: BufEnter autocommands
1225.000  000.000: editing files in windows
1239.000  014.000: VimEnter autocommands
1239.000  000.000: before starting main loop
1249.000  010.000: first screen update
1249.000  000.000: --- VIM STARTED ---

**Comment by chrisbra** [comment]
apparently setting the locale on Windows is a bit slow. You might check, if disabling FEAT_GETTEXT makes it a bit faster. Check the `init_locale()` function for details about what is done. Closing, as this is not a bug but a usage question. Please ask user questions on vi.stackexchange.com or vim_use mailinglist.
