### ISSUE TITLE
quickfix list get the incorrect directory when 'make -C'

### ISSUE THREAD

**Issue by acynothia** [vim/vim#4122]
project directory:
```
./
├── Makefile
└── main
    ├── Makefile
    └── main.go
```
Makefile
```
build:
	make -C main
```
main/Makefile
```
build:
         go build
```
main/main.go
```
package main

func main() {
	i := 0
}
```
when i call `:make` in `./main/` I get the right quick fix.
```
  1 main.go|4 col 7| i declared and not used                                                                            
```
but when i call `:make` in `./` I get the incorrect quick fix.
```
  1 || make -C main
  2 || go build
  3 || # _/Users/marco/Astone/git/test/main
  4 main.go|10 col 7| i declared and not used                                                                           
  5 || make[1]: *** [build] Error 2 
  6 || make: *** [build] Error 2
```
when I press enter in line 4. It will create a new file `_/Users/marco/Astone/git/test/main.go` not open the right file `_/Users/marco/Astone/git/test/main/main.go`

It's also happend in linux. and if u call `cd ..` in Makefile will cause the same problem.

**Comment by general0000** [comment]
I've had this problem, too.  I found the builtin errorformat can't work properly，I modified errorformat and now it's ok：

![errorformat](https://user-images.githubusercontent.com/45509755/54877928-0dfca980-4e60-11e9-8ee1-d1bd23d9d2f6.png)

**Comment by brammool** [comment]
> I've had this problem, too.  I found the builtin errorformat can't work properly，I modified errorformat and now it's ok：
> set errorformat+=
>             \%D%*\\a[%*\\d]:\ Entering\ directory\ `%f',
>             \%D%*\\a[%*\\d]:\ Entering\ directory\ '%f',
>             \%D%*\\a:\ Entering\ directory\ `%f',
>             \%D%*\\a:\ Entering\ directory\ '%f'

What exactly is the change?  The default should do the same:

	%D%*\a[%*\d]: Entering directory %%*[`']%f'
	%X%*\a[%*\d]: Leaving directory %*[`']%f'
	%D%*\a: Entering %directory %*[`']%f'
	%X%*\a: Leaving directory %*[`']%f'

-- 
hundred-and-one symptoms of being an internet addict:
108. While reading a magazine, you look for the Zoom icon for a better
     look at a photograph.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
Hi,

On Sat, Mar 16, 2019 at 9:12 PM Astone <vim-dev-github@256bit.org> wrote:
>
> project directory:
>
> ./
>
> ├── Makefile
>
> └── main
>
>     ├── Makefile
>
>     └── main.go
>
> Makefile
>
> build:
>
> make -C main
>
> main/Makefile
>
> build:
>
>          go build
>
> main/main.go
>
> package main
>
>
>
> func main() {
>
> i := 0
>
> }
>
> when i call :make in ./main/ I get the right quick fix.
>
>   1 main.go|4 col 7| i declared and not used
>
> but when i call :make in ./ I get the incorrect quick fix.
>
>   1 || make -C main
>
>   2 || go build
>
>   3 || # _/Users/marco/Astone/git/test/main
>
>   4 main.go|10 col 7| i declared and not used
>
>   5 || make[1]: *** [build] Error 2
>
>   6 || make: *** [build] Error 2
>
> when I press enter in line 4. It will create a new file _/Users/marco/Astone/git/test/main.go not open the right file _/Users/marco/Astone/git/test/main/main.go
>
> It's also happend in linux. and if u call cd .. in Makefile will cause the same problem.
>

Vim relies on the 'errorformat' option setting to parse the make
output. To correctly
parse entering and leaving directories, the 'errorformat' option setting must be
set to look for lines that print the directory names. You can refer to the
":help quickfix-directory-stack" help text for more information about this.

The default 'errorformat' option setting expects the text "Entering directory"
and "Leaving directory" in the make output to parse the change in directories.
In the above output, I don't see these lines. It looks like the directory
name is printed using the below format:

    # _/Users/marco/Astone/git/test/main

Which 'make' are you using? What is 'makeprg' set to?
You may need to modify the 'errorformat' setting to parse the above line
using %D and %X.

- Yegappan

**Comment by acynothia** [comment]
Thanks very much.  I thinks I got the key.
