### ISSUE TITLE
extend &define to match labels not at end of defining expression 

### ISSUE THREAD

**Issue by Konfekt** [vim/vim#4125]
Currently `&define` necessitates that the label come last in its defining expression. 

But not in all programming or markup languages the label comes last in the line that it defines, for example in `javascript`, to look up the definition of a method with label `method_name`, one would look for expressions such as
```javascript
this.method_name = function() {...
method_name : function() {...
```
 where the `method_name` comes *before* the pattern `function() { ...` that indicates the definition of a method.

Although  historically the key bindings and commands such as  `[d`, `]d`, `:dsearch`, `[D`, `]D`, `:dlist`, `[<C-D>`, `]<C-D>`, `<C-W>d`,  `:djump`, `:dsplit`, `<C-X><C-D>` were probably firstly defined to look up the definition of a given macro label in `C`, where the label always comes last, all of these key bindings and commands are *global*, whereas `&define` is a buffer-*local* setting. 

Therefore, these key bindings and commands  should be made use of in file types that do not use `C` macros for definitions. To permit looking up labels that are defined in an expression where the label does not come last, how about permitting `%s` inside `&define` to designate the looked up label? If `%s` does not occur, then fall back to the current interpretation of `&define` where the label comes last.

**Comment by brammool** [comment]
> Currently `&define` necessitates that the label come last in its
> defining expression. 

Not true, you can use \ze to end where the pattern matches, even when
more of the pattern follows.

> But not in all programming or markup languages the label comes last in
> the line that it defines, for example in `javascript`, to look up the
> definition of a method with label `method_name`, one would look for
> expressions such as
> ```javascript
> this.method_name = function() {...
> method_name : function() {...
> ```
>  where the `method_name` comes *before* the pattern `function() { ...`
>  that indicates the definition of a method.

Later versions of Javascript define functions in other ways, thus this
won't work in general.  This is something you would need to use tags
for.

> Although  historically the key bindings and commands such as  `[d`,
> `]d`, `:dsearch`, `[D`, `]D`, `:dlist`, `[<C-D>`, `]<C-D>`, `<C-W>d`,
> `:djump`, `:dsplit`, `<C-X><C-D>` were probably firstly defined to
> look up the definition of a given macro label in `C`, where the label
> always comes last, all of these key bindings and commands are
> *global*, whereas `&define` is a buffer-*local* setting. 

Yes, that's what it was made for.  For other languages something similar
might work, but not for everything.

> Therefore, these key bindings and commands  should be made use of in
> file types that do not use `C` macros for definitions. To permit
> looking up labels that are defined in an expression where the label
> does not come last, how about permitting `%s` inside `&define` to
> designate the looked up label? If `%s` does not occur, then fall back
> to the current interpretation of `&define` where the label comes last.

Just put \ze at the end of the label.

-- 
From "know your smileys":
 :-)	Funny
 |-)	Funny Oriental
 (-:	Funny Australian

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Konfekt** [comment]
There might be a misunderstanding as I am lost at how to apply `\ze` in the exmaples cited. `:help 'define'` reads

> 	Pattern to be used to find a macro definition ... for the
	commands like "[i" and "[d"...  The 'isident' option is
	used to recognize the defined name after the match:
		{match with 'define'}{non-ID chars}{defined name}{non-ID char}

For example, what pattern containing`\ze` makes `[d` recognize the label (= defined name) `method_name` in `method_name : function() {` after the match?

**Comment by tom-m** [comment]
@Konfekt

How about starting experiments with
```vim
let &l:define = '\ze\k\+\s*:\s*function()\s*{'
```
?

**Comment by Konfekt** [comment]
Thank you, this works as `:` is a non-ID char and `{non-ID chars}` means `[^[:ident:]]*`, that is, possibly no non-ID char.

**Comment by chrisbra** [comment]
perhaps, you can provide an example for the documentation?

**Comment by brammool** [comment]
> @Konfekt
> 
> How about starting experiments with
> ```vim
> let &l:define = '\ze\k\+\s*:\s*function()\s*{'
> ```
> ?

Perhaps this works:

	let &l:define = '^\s*\ze\k\+\s*=\s*function('


-- 
Momento mori, ergo carpe diem

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Konfekt** [comment]
Looks good. In https://github.com/vim/vim/pull/4157 I propose `\i` instead of `\k` as identifying labels seems to be the purpose of `\i` respectively `&isident`.
