### ISSUE TITLE
terminal display issue

### ISSUE THREAD

**Issue by epheien** [vim/vim#4126]
Windows 10 64bit
gvim 8.1.994
download from https://github.com/vim/vim-win32-installer/releases/tag/v8.1.0994 (https://github.com/vim/vim-win32-installer/releases/download/v8.1.0994/gvim_8.1.0994_x64.exe)

reproduce
```
:terminal<CR>
<C-\><C-n>i<C-\><C-n>
```
content of terminal buffer will not show

same issue in macvim
https://github.com/macvim-dev/macvim/issues/878

**Comment by chrisbra** [comment]
Hm, could that be caused by 29ae223ddcfcbbce46c7e1f4e8fa71 (patch 8.1.920)?

Does that patch fix it:
```patch
diff --git a/src/terminal.c b/src/terminal.c
index 8d05a188e..99af35f5c 100644
--- a/src/terminal.c
+++ b/src/terminal.c
@@ -2952,7 +2952,10 @@ handle_postponed_scrollback(term_T *term)
 {
     int i;

-ch_log(NULL, "Moving postponed scrollback to scrollback");
+    if (term->tl_scrollback_postponed.ga_len == 0)
+       return;
+
+    ch_log(NULL, "Moving postponed scrollback to scrollback");
     // First remove the lines that were appended before, the pushed lines go
     // above it.
     cleanup_scrollback(term);
```

**Comment by epheien** [comment]
> Hm, could that be caused by [29ae223](https://github.com/vim/vim/commit/29ae223ddcfcbbce46c7e1f4e8fa71b8f2674271) (patch 8.1.920)?
> 
> Does that patch fix it:
> 
> ```diff
> diff --git a/src/terminal.c b/src/terminal.c
> index 8d05a188e..99af35f5c 100644
> --- a/src/terminal.c
> +++ b/src/terminal.c
> @@ -2952,7 +2952,10 @@ handle_postponed_scrollback(term_T *term)
>  {
>      int i;
> 
> -ch_log(NULL, "Moving postponed scrollback to scrollback");
> +    if (term->tl_scrollback_postponed.ga_len == 0)
> +       return;
> +
> +    ch_log(NULL, "Moving postponed scrollback to scrollback");
>      // First remove the lines that were appended before, the pushed lines go
>      // above it.
>      cleanup_scrollback(term);
> ```

Yes, this can fix the issue.

**Comment by brammool** [comment]
Christian wrote:

> Hm, could that be caused by 29ae223ddcfcbbce46c7e1f4e8fa71 (patch 8.1.920)?
> 
> Does that patch fix it:
> ```patch
> diff --git a/src/terminal.c b/src/terminal.c
> index 8d05a188e..99af35f5c 100644
> --- a/src/terminal.c
> +++ b/src/terminal.c
> @@ -2952,7 +2952,10 @@ handle_postponed_scrollback(term_T *term)
>  {
>      int i;
> 
> -ch_log(NULL, "Moving postponed scrollback to scrollback");
> +    if (term->tl_scrollback_postponed.ga_len == 0)
> +       return;
> +
> +    ch_log(NULL, "Moving postponed scrollback to scrollback");
>      // First remove the lines that were appended before, the pushed lines go
>      // above it.
>      cleanup_scrollback(term);
> ```

Thanks for the fix.  I didn't manage to write a test to reproduce the
problem (yet).

-- 
From "know your smileys":
 !-|	I-am-a-Cylon-Centurian-with-one-red-eye-bouncing-back-and-forth

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
