### ISSUE TITLE
Indentation for shell scripts not properly closing.

### ISSUE THREAD

**Issue by a-tyler** [vim/vim#4132]
Hi it appears that an issue with the shell indent script was introduced in commit [#314dd7](https://github.com/vim/vim/blob/314dd79cac2adc10304212d1980d23ecf6782cfc/runtime/indent/sh.vim) that as far as I can tell isn't properly detecting when it should close. Here is an example:
Before indent:
```
#!/bin/bash
if [ "$1" == "test" ];
then
echo "";
fi
if [ "$1" == "1" ];
then
echo "test";
fi
if [ "$2" == "2" ];
then
echo "test";
fi
```
After indentation with sh.vim from [#314dd7](https://github.com/vim/vim/blob/314dd79cac2adc10304212d1980d23ecf6782cfc/runtime/indent/sh.vim):
```
#!/bin/bash
if [ "$1" == "test" ];
then
        echo "";
        fi
        if [ "$1" == "1" ];
        then
                echo "test";
                fi
                if [ "$2" == "2" ];
                then
                        echo "test";
                        fi
```
After indent with the sh.vim from the previous commit:
```
#!/bin/bash
if [ "$1" == "test" ];
then
    echo "";
fi
if [ "$1" == "1" ];
then
    echo "test";
fi
if [ "$2" == "2" ];
then
    echo "test";
fi
```
I have tried both the official package (version 8.1.0996-1) as well as a git build (493fbe4abee660d30b4f2aef87b754b0a720213c) under a fresh Arch Linux install and the issue exists in both.
Let me know if you need any other information.

**Comment by chrisbra** [comment]
yes, that was caused by an error in the shell indent script. My repository already includes the fix, I am just about to send an update to Bram for inclusion with vim.
For reference: https://github.com/chrisbra/vim-sh-indent/issues/11

**Comment by a-tyler** [comment]
Ah! Thanks! Sorry to be a bother.
