### ISSUE TITLE
has prebuilt android version?

### ISSUE THREAD

**Issue by ysh329** [vim/vim#4133]
Thanks in advance.

**Comment by chrisbra** [comment]
we don't provide any, if that was the question.

**Comment by ysh329** [comment]
Thanks ~

**Comment by mgedmin** [comment]
[Termux](https://termux.com/) has a command-line `vim`.

There's also [DroidVim](https://play.google.com/store/apps/details?id=com.droidvim&hl=en_US), but I haven't used it personally.
