### ISSUE TITLE
Repeatly 'Join' miscount when n>2

### ISSUE THREAD

**Issue by hukangha** [vim/vim#4134]
Hi,
I'm using vim for quite a while, on recent versions, there seems 
an issue for repeatly "Joinning" next row to current row.
for example, 
if I type "J"  , vim joins next row to current row once.
if I type "1J" , vim joins next row to current row once.
if I type "2J", it still Join only once.
if I type "3J", it join twice.
seems the join number is not [n] but [n-1].

This seems not an intended behavior.

**Comment by k-takata** [comment]
See `:help J`

> Join [count] lines, with a minimum of two lines.

`3J` joins 3 lines, so this is intended.

**Comment by hukangha** [comment]
> See `:help J`
> 
> > Join [count] lines, with a minimum of two lines.
> 
> `3J` joins 3 lines, so this is intended.

Yeah? 
so, n[key] does not always mean typing [key] for n times...
I see...

**Comment by Houl** [comment]
OT: this is one more example where `'relativenumber'` is off-by-one.  And there is no work-around, because `J` is not an operator.

**Comment by brammool** [comment]
> > See `:help J`
> > 
> > > Join [count] lines, with a minimum of two lines.
> > 
> > `3J` joins 3 lines, so this is intended.
> 
> Yeah? 
> so, n[key] does not mean typing [key] for n times...
> I see...

Yep, this is what vi has always done.

-- 
From "know your smileys":
 %	Bike accident.  A bit far-fetched, I suppose; although...
             o      _     _         _
     _o     /\_   _ \\o  (_)\__/o  (_)
   _< \_   _>(_) (_)/<_    \_| \   _|/' \/
  (_)>(_) (_)        (_)   (_)    (_)'  _\o_

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
