### ISSUE TITLE
win10python3.7

### ISSUE THREAD

**Issue by kerwinxu** [vim/vim#4136]
file : Make_mvc.mak
# PYTHON3 interface
!ifdef PYTHON3
!ifndef PYTHON3_VER
PYTHON3_VER = 36
!endif
!message Python3 requested (version $(PYTHON3_VER)) - root dir is "$(PYTHON3)"
!if "$(DYNAMIC_PYTHON3)" == "yes"
!message Python3 DLL will be loaded dynamically
!endif
CFLAGS = $(CFLAGS) -DFEAT_PYTHON3
**CFLAGS = $(CFLAGS) -DPYTHON3_HOME=L\"$(PYTHON3)\"**
PYTHON3_OBJ = $(OUTDIR)\if_python3.obj
PYTHON3_INC = /I "$(PYTHON3)\Include" /I "$(PYTHON3)\PC"
!if "$(DYNAMIC_PYTHON3)" == "yes"
CFLAGS = $(CFLAGS) -DDYNAMIC_PYTHON3 \
		-DDYNAMIC_PYTHON3_DLL=\"python$(PYTHON3_VER).dll\"
PYTHON3_LIB = /nodefaultlib:python$(PYTHON3_VER).lib
!else
PYTHON3_LIB = $(PYTHON3)\libs\python$(PYTHON3_VER).lib
!endif
!endif

**Comment by chrisbra** [comment]
Please be a bit more verbose. What are you trying to tell us?

**Comment by kerwinxu** [comment]
> Please be a bit more verbose. What are you trying to tell us?

add below line , 
CFLAGS = $(CFLAGS) -DPYTHON3_HOME=L"$(PYTHON3)"

**Comment by chrisbra** [comment]
and why would that be needed?

**Comment by k-takata** [comment]
The PYTHON3_HOME directory is not always the same when compile time and run time.
I don't think it is needed.

**Comment by k-takata** [comment]
I found that Make_cyg_ming.mak has definitions for PYTHON_HOME and PYTHON3_HOME.
Adding similar codes to Make_mvc.mak might be acceptable. So, how about this?

```diff
--- a/src/Make_mvc.mak
+++ b/src/Make_mvc.mak
@@ -922,6 +922,9 @@ PYTHON_VER = 27
 !message Python DLL will be loaded dynamically
 !endif
 CFLAGS = $(CFLAGS) -DFEAT_PYTHON
+!ifdef PYTHON_HOME
+CFLAGS = $(CFLAGS) -DPYTHON_HOME="$(PYTHON_HOME)"
+!endif
 PYTHON_OBJ = $(OUTDIR)\if_python.obj
 PYTHON_INC = /I "$(PYTHON)\Include" /I "$(PYTHON)\PC"
 !if "$(DYNAMIC_PYTHON)" == "yes"
@@ -943,6 +946,9 @@ PYTHON3_VER = 36
 !message Python3 DLL will be loaded dynamically
 !endif
 CFLAGS = $(CFLAGS) -DFEAT_PYTHON3
+!ifdef PYTHON3_HOME
+CFLAGS = $(CFLAGS) -DPYTHON3_HOME=L"$(PYTHON3_HOME)"
+!endif
 PYTHON3_OBJ = $(OUTDIR)\if_python3.obj
 PYTHON3_INC = /I "$(PYTHON3)\Include" /I "$(PYTHON3)\PC"
 !if "$(DYNAMIC_PYTHON3)" == "yes"
```

(Not tested at all.)

**Comment by kerwinxu** [comment]
win10,anaconda3.7,it does not set PYTHONHOME ,If you don't have this "PYTHON3_HOME", the vim  doesn't work.

the problem is blow 
file , if_python3

#ifdef PYTHON3_HOME
	else if (mch_getenv((char_u *)"PYTHONHOME") == NULL)
	    Py_SetPythonHome(PYTHON3_HOME);
#3237 

the blow code does not work well

	if (*p_py3home != NUL)
	{
	    size_t len = mbstowcs(NULL, (char *)p_py3home, 0) + 1;

	    /* The string must not change later, make a copy in static memory. */
	    py_home_buf = (wchar_t *)alloc(len * sizeof(wchar_t));
	    if (py_home_buf != NULL && mbstowcs(
			    py_home_buf, (char *)p_py3home, len) != (size_t)-1)
		Py_SetPythonHome(py_home_buf);
	}

so i found the easy way , 
add blow code 
CFLAGS = $(CFLAGS) -DPYTHON3_HOME=L"$(PYTHON3)"

**Comment by k-takata** [comment]
So, have you tried my patch?

You can also set the 'pythonthreehome' option.

**Comment by kerwinxu** [comment]
> So, have you tried my patch?
> 
> You can also set the 'pythonthreehome' option.

how set ?

**Comment by chrisbra** [comment]
> how set ?

`:h 'pythonthreehome'`

**Comment by kerwinxu** [comment]
> > how set ?
> 
> `:h 'pythonthreehome'`

thank you , it work . I do not want to modify code , my easy way as below 

call "d:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
cd vim
git pull
cd ..\
cd vim\src

rmdir /s/q ..\vim80
mkdir ..\vim80

del /q/a/f/s *.exe
del /q/a/f/s *.dll
del /q/a/f/s xxd\xxd.exe
del /q/a/f/s GvimExt\gvimext.dll
del /q/a/f/s GvimExt\uninst.bat
del /q/a/f/s tee\tee.exe


nmake.exe -f Make_mvc.mak clean
nmake.exe -f Make_mvc.mak GUI=no WINVER=0x0A00 CPU=AMD64  CSCOPE=yes POSTSCRIPT=yes NETBEANS=yes  TCL=E:\project\vc\Python-3.7.2\externals\tcltk64  DYNAMIC_TCL=yes TCL_VER=86 TCL_VER_LONG=8.6 TCL_DLL=tcl86t   PYTHON3=D:\Anaconda3 PYTHON3_VER=37 DYNAMIC_PYTHON3=yes CPUNR=avx2 DEBUG=no   LUA=E:\project\vc\lua-5.3.4\lua DYNAMIC_LUA=yes LUA_VER=53 

nmake.exe -f Make_mvc.mak GUI=yes  WINVER=0x0A00  CPU=AMD64  CSCOPE=yes POSTSCRIPT=yes   NETBEANS=yes TCL=E:\project\vc\Python-3.7.2\externals\tcltk64  DYNAMIC_TCL=yes TCL_VER=86 TCL_VER_LONG=8.6 TCL_DLL=tcl86t PYTHON3=D:\Anaconda3 PYTHON3_VER=37 DYNAMIC_PYTHON3=yes  OLE=yes DIRECTX=yes IME=yes GIME=yes  CPUNR=avx2 DEBUG=no  LUA=E:\project\vc\lua-5.3.4\lua DYNAMIC_LUA=yes LUA_VER=53 

xcopy ..\runtime ..\vim80\ /e /Y
xcopy *.exe ..\vim80\ /Y
xcopy *.dll ..\vim80 /Y
xcopy xxd\xxd.exe ..\vim80 /y
xcopy GvimExt\gvimext.dll ..\vim80 /y
xcopy E:\project\vc\Python-3.6.1\externals\tcltk64\bin\* ..\vim80 /y
xcopy GvimExt\uninst.bat ..\vim80 /y
xcopy tee\tee.exe ..\vim80 /y
xcopy E:\project\vc\lua-5.3.4\lua\lua53.dll ..\vim80 /y


del /q/a/f/s *.exe
del /q/a/f/s *.dll
del /q/a/f/s xxd\xxd.exe
del /q/a/f/s GvimExt\gvimext.dll
del /q/a/f/s GvimExt\uninst.bat
del /q/a/f/s tee\tee.exe

cd ../../

pause
