### ISSUE TITLE
Channel commands appear to redraw

### ISSUE THREAD

**Issue by myitcv** [vim/vim#4139]
The documentation for [channel commands](https://github.com/vim/vim/blob/61be376337b0374d55a4b1d8206b2ec87ca54252/runtime/doc/channel.txt#L284) says the following about the [`"redraw"` command](https://github.com/vim/vim/blob/61be376337b0374d55a4b1d8206b2ec87ca54252/runtime/doc/channel.txt#L311-L313):

```
The other commands do not update the screen, so that you can send a sequence
of commands without the cursor moving around.  You must end with the "redraw"
command to show any changed text and show the cursor where it belongs.
```

However, if I load up a minimal channel-based JSON plugin and send:

```
["ex", "call feedkeys('iClassName')"]
```

then I see the screen updated to include the inserted text.

Similarly if I were to:

```
["call", "matchaddpos", ["Statement", [[1, 1, 2]]]]
```

then the screen is updated to reflect the added match.

So it appears that, despite there being no explicit call to `"redraw"`, the screen is being updated.

Am I missing/misunderstanding something here?

Thanks

**Comment by myitcv** [comment]
To ask a somewhat related question, is there a way that we can similarly prevent redraws in calls handled by a defined [callback function](https://github.com/vim/vim/blob/61be376337b0374d55a4b1d8206b2ec87ca54252/runtime/doc/channel.txt#L130-L132)?

**Comment by chrisbra** [comment]
well, I wouldn't recommend it, because it should only be used for testing, but I think a `:call test_override('redraw', 1)` should disable all redraws. This hooks in very low in the redrawing logic, so make sure to re-enable it in any case.

**Comment by myitcv** [comment]
Thanks @chrisbra 

This helps in some respects, but it appears that re-enabling this setting (i.e. calling `test_override('redraw', 0)`) causes a redraw. 

So the best this would give me is effectively a batch window during which redraws will be disabled. 

Which is quite different semantically to any channel command not causing a redraw.

**Comment by brammool** [comment]
> The documentation for [channel commands](https://github.com/vim/vim/blob/61be376337b0374d55a4b1d8206b2ec87ca54252/runtime/doc/channel.txt#L284) says the following about the [`"redraw"` command](https://github.com/vim/vim/blob/61be376337b0374d55a4b1d8206b2ec87ca54252/runtime/doc/channel.txt#L311-L313):
> 
> ```
> The other commands do not update the screen, so that you can send a sequence
> of commands without the cursor moving around.  You must end with the "redraw"
> command to show any changed text and show the cursor where it belongs.
> ```
> 
> However, if I load up a minimal channel-based JSON plugin and send:
> 
> ```
> ["ex", "call feedkeys('iClassName')"]
> ```
> 
> then I see the screen updated to include the inserted text.
> 
> Similarly if I were to:
> 
> ```
> ["call", "matchaddpos", ["Statement", [[1, 1, 2]]]]
> ```
> 
> then the screen is updated to reflect the added match.
> 
> So it appears that, despite there being no explicit call to `"redraw"`, the screen is being updated.
> 
> Am I missing/misunderstanding something here?

Depending on the command it may trigger a redraw.  But Vim does not
normally go to the main loop, where a redraw normally happens.  This can
be a bit confusing, since Vim doesn't guarantee a redraw but also
doesn't promise to not redraw.  I haven't heard this being a real
problem, it's more a matter of efficiency, avoiding too many redraws.

-- 
From "know your smileys":
 :-F	Bucktoothed vampire with one tooth missing

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by myitcv** [comment]
Thanks @brammool, that makes sense.

Just one further question of clarification: does that same explanation hold for calls handled by a defined [callback function](https://github.com/vim/vim/blob/61be376337b0374d55a4b1d8206b2ec87ca54252/runtime/doc/channel.txt#L130-L132)?

**Comment by brammool** [comment]
> Thanks @brammool, that makes sense.
> 
> Just one further question of clarification: does that same explanation
> hold for calls handled by a defined [callback
> function](https://github.com/vim/vim/blob/61be376337b0374d55a4b1d8206b2ec87ca54252/runtime/doc/channel.txt#L130-L132)?

Callback functions usually cause a redraw when needed.

-- 
I AM THANKFUL...
...for the clothes that fit a little too snug because it
means I have more than enough to eat.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by myitcv** [comment]
Thanks again @brammool. 

So is there perhaps scope for a more official means by which redraw can be suspended while a batch of calls is handled? 

The use case here (expanding on the detail above) is a calling `matchaddpos` a number of times for the current "viewport". As the viewport shifts, I call `matchaddpos` roughly as many times as there are lines visible in a window.

I'm not clear on the cost of there potentially being a redraw after each call vs a single call once the batch is complete.

**Comment by brammool** [comment]
> Thanks again @brammool. 
> 
> So is there perhaps scope for a more official means by which redraw
> can be suspended while a batch of calls is handled? 
> 
> The use case here (expanding on the detail above) is a calling
> `matchaddpos` a number of times for the current "viewport". As the
> viewport shifts, I call `matchaddpos` roughly as many times as there
> are lines visible in a window.
> 
> I'm not clear on the cost of there potentially being a redraw after
> each call vs a single call once the batch is complete.

Have you tried setting 'lazyredraw' while still busy?

-- 
"Computers in the future may weigh no more than 1.5 tons."
                                   Popular Mechanics, 1949

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by myitcv** [comment]
> Have you tried setting 'lazyredraw' while still busy?

I haven't, but I will now 👍 

Thanks again.

**Comment by chrisbra** [comment]
I suppose this can be closed now, with the amendment of the documentation in 63b74a8362b14576b21d about `redraw`

**Comment by myitcv** [comment]
Thanks @chrisbra yes, I agree.

I think I'll end up raising a slightly different issue again in the future in case I revisit https://github.com/myitcv/govim/pull/24 in anger.

Reason being, I really need a means to bulk apply/remove matches. The overhead from, effectively, one call per line is too much.

But that's (maybe) for a future issue.
