### ISSUE TITLE
Wrong help for switchbuf=split / improve qf_goto_win_with_qfl_file

### ISSUE THREAD

**Issue by blueyed** [vim/vim#4140]
The help for "switchbuf" says:

> split
> If included, split the current window before loading
> a buffer for a |quickfix| command that display errors.
> Otherwise: do not split, use current window.

But it does not use the "current window" (which should/would rather be the
"last one used" anyway, since the current window is the quickfix window), but
the one above the quickfix window.

Related code (qf_goto_win_with_qfl_file): https://github.com/vim/vim/blob/61be376337b0374d55a4b1d8206b2ec87ca54252/src/quickfix.c#L2913-L2955

I think the best behavior would be if it would use the "previous (last accessed) window" (where `Ctrl-W-Ctrl-P` would go to), if it cannot find a window with the buffer.

I am using `switchbuf=` (the default), but it results in unexpected behavior often when a buffer is not yet visible, e.g. if you `:lcd` to some project in the first window, search something there (filling the quickfix list).  Results from other files will then open in another window (e.g. number 2), instead of the one where you did the search from.

**Comment by blueyed** [comment]
The following patch achieved my expected behavior:
```diff
diff --git c/src/quickfix.c i/src/quickfix.c
index d332e2364..8344398bd 100644
--- c/src/quickfix.c
+++ i/src/quickfix.c
@@ -2924,6 +2924,11 @@ qf_goto_win_with_qfl_file(int qf_fnum)

     win = curwin;
     altwin = NULL;
+    if (IS_QF_WINDOW(win)) {
+       if (prevwin && !prevwin->w_p_pvw && bt_normal(prevwin->w_buffer)) {
+           altwin = prevwin;
+       }
+    }
     for (;;)
     {
        if (win->w_buffer->b_fnum == qf_fnum)
```

TEST CASE: `vim -Nu NONE -c 'vsp' -c 'grep! vim README.md' -c 'copen' -c 'exe "norm \<CR>"'`

Without this patch the file is displayed in window 2, while with this patch it is window 1 (where `:copen` was done from, and where `ctrl-w ctrl-p` would go to).

(it confused me previously that there is a comment "go to previous window" in that function, but it uses `->w_prev`, which is not the same/similar to `prevwin`)

**Comment by vim-ml** [comment]
Hi,

On Wed, Mar 20, 2019 at 9:39 AM Daniel Hahler <vim-dev-github@256bit.org> wrote:
>
> The following patch achieved my expected behavior:
>
> diff --git c/src/quickfix.c i/src/quickfix.c
> index d332e2364..8344398bd 100644
> --- c/src/quickfix.c
> +++ i/src/quickfix.c
> @@ -2924,6 +2924,11 @@ qf_goto_win_with_qfl_file(int qf_fnum)
>
>      win = curwin;
>      altwin = NULL;
> +    if (IS_QF_WINDOW(win)) {
> +       if (prevwin && !prevwin->w_p_pvw && bt_normal(prevwin->w_buffer)) {
> +           altwin = prevwin;
> +       }
>

Can you move the above code into the below for() loop where there is a check for
IS_QF_WINDOW()? Can you also add a comment about this?

>
> +    }
>      for (;;)
>      {
>         if (win->w_buffer->b_fnum == qf_fnum)
>
> TEST CASE: vim -Nu NONE -c 'vsp' -c 'grep! vim README.md' -c 'copen' -c 'exe "norm \<CR>"'
>

Can you convert this into a test in test_quickfix.vim?

Thanks,
Yegappan

>
> Without this patch the file is displayed in window 2, while with this patch it is window 1 (where :copen was done from, and where ctrl-w ctrl-p would go to).
>
> (it confused me previously that there is a comment "go to previous window" in that function, but it uses ->w_prev, which is not the same/similar to prevwin)
>

**Comment by blueyed** [comment]
> Can you move the above code into the below for() loop where there is a check for IS_QF_WINDOW()? Can you also add a comment about this?

That does not really work, because "win" is updated via "win->w_prev" by then already.

I know that the code is clunky and needs to be cleaned up, but just wanted to post it already - not being sure if I missed something obvious etc, and what the desired behavior really is.
After all people might be used to the "w_prev" window being used.

**Comment by andymass** [comment]
At least it is consistent with `<cr>`, which goes to the window above the quickfix.  Perhaps both `<cr>` and `<c-w><cr>` should be changed to use the previous meaning ctrl-w ctrl-p window?  What about gated behind `switchbuf=previous`?

**Comment by blueyed** [comment]
@andymass 
I was only talking about `<cr>`, but they should be consistent.
A new `switchbuf` setting sounds good, but maybe can be avoided - I've looked at the help a few times when being confused to figure out what the intended behavior is, and it says "current window" there, where I've assumed it to be the window used before the quickfix window (i.e. previous window).

**Comment by vim-ml** [comment]
Hi Daniel,

On Wed, Mar 20, 2019 at 12:15 PM Daniel Hahler
<vim-dev-github@256bit.org> wrote:
>
> @andymass
> I was only talking about <cr>, but they should be consistent.  A new
> switchbuf setting sounds good, but maybe can be avoided - I've looked
> at the help a few times when being confused to figure out what the
> intended behavior is, and it says "current window" there, where I've
> assumed it to be the window used before the quickfix window (i.e.
> previous window).
>

The 'switchbuf' option is also used when using commands like ":cnext",
":cprev" without the quickfix window. In these cases, the "current window"
above refers to the window from which the command was invoked
and 'switchbuf' option determines which window is used.

- Yegappan

**Comment by chrisbra** [comment]
so is there anything to be done here or do we just need a clarification of the documentation?

**Comment by chrisbra** [comment]
no feedback, closing.
