### ISSUE TITLE
getjumplist() is not as useful as it should

### ISSUE THREAD

**Issue by romainl** [vim/vim#4145]
`getjumplist()` was added in https://github.com/vim/vim/pull/2609. It purports to allow people to get a usable representation of the jumplist but it fails to do so.

First, `getjumplist()[0]` is inverted compared to `:jumps`, with jump `0` being at `[-1]` and so on. Yes we can `reverse()` it to get the expected representation but that shouldn't be necessary.

Second, the items in `getjumplist()[0]` don't contain the most important information: the jump number. Without that information, "getting the jump list", is debatably useful because we don't get any actual "jump" in the returned list.

Third, the index of those items can't be used to infer actual jump numbers because jump `0` can be anywhere in the list and have relative numbers above and below.

Fourth, `getjumplist()[1]` is the last position reachable with `<C-o>` but the newest position reachable with `<C-i>` is not there.

**Comment by vim-ml** [comment]
Hi,

On Thu, Mar 21, 2019 at 1:35 PM Romain Lafourcade
<vim-dev-github@256bit.org> wrote:
>
> getjumplist() was added in #2609. It purports to allow people to get a
> usable representation of the jumplist but it fails to do so.
>
> First, getjumplist()[0] is inverted compared to :jumps, with jump 0
> being at [-1] and so on. Yes we can reverse() it to get the expected
> representation but that shouldn't be necessary.
>

The getjumplist() function returns the list of entries in the order in which
the ":jumps" command lists them. So the first entry in the returned list
may be the entry with the highest jump number as displayed by the
":jumps" command. Note that if you use <C-o> or <C-i> to traverse
the jump list, the jump list number for each entry will change and the
last entry may not be the one with the first jump list number.

>
> Second, the items in getjumplist()[0] don't contain the most important
> information: the jump number. Without that information, "getting the
> jump list", is debatably useful because we don't get any actual "jump"
> in the returned list.
>

The jump number for each entry can be derived from the second number
returned by getjumplist(). The ":jumps" command uses the following to
derive the jump number:

       i > curwin->w_jumplistidx ? i - curwin->w_jumplistidx
                                                : curwin->w_jumplistidx - i,

where i is the index of the jump list entry.

>
> Third, the index of those items can't be used to infer actual jump
> numbers because jump #0 can be anywhere in the list and have relative
> numbers above and below.
>
> Fourth, getjumplist()[1] is the last position reachable with <C-o> but
> the newest position reachable with <C-i> is not there.
>

To find the position reachable with <C-i> you can add 1 to the number
returned by getjumplist() (second item in the list).

- Yegappan

**Comment by vim-ml** [comment]
Hi,

On Thu, Mar 21, 2019 at 1:35 PM Romain Lafourcade
<vim-dev-github@256bit.org> wrote:
>
> getjumplist() was added in #2609. It purports to allow people to get a
> usable representation of the jumplist but it fails to do so.
>
> First, getjumplist()[0] is inverted compared to :jumps, with jump 0
> being at [-1] and so on. Yes we can reverse() it to get the expected
> representation but that shouldn't be necessary.
>
> Second, the items in getjumplist()[0] don't contain the most important
> information: the jump number. Without that information, "getting the
> jump list", is debatably useful because we don't get any actual "jump"
> in the returned list.
>

The attached patch adds a jump number to each entry in the
list returned by getjumplist().

- Yegappan

> Third, the index of those items can't be used to infer actual jump
> numbers because jump #0 can be anywhere in the list and have relative
> numbers above and below.
>
> Fourth, getjumplist()[1] is the last position reachable with <C-o> but
> the newest position reachable with <C-i> is not there.
>

**Comment by romainl** [comment]
> The getjumplist() function returns the list of entries in the order in which
the ":jumps" command lists them.

No, you reverse the order, with the lowest jump numbers at the end and the highest at the beginning. 

Also, the jumplist can look like this:

      6
      5
      4
      3
      2
      1
    > 0

or like that:

      3
      2
      1
    > 0
      1
      2
      3

It is quite obvious that the jumplist can't be modeled as a single list. What good is it to have two jump `3` if we don't know where the pivot is? Are we supposed to slice the returned list ourselves?

> The jump number for each entry can be derived from the second number
returned by getjumplist().

That shouldn't be necessary. Querying the *jump*list without getting jump numbers is useless.

> To find the position reachable with <C-i> you can add 1 to the number
returned by getjumplist() (second item in the list).

No. 53 + 1 doesn't equal 1.

**Comment by brammool** [comment]
You have all the information needed.  The current position is the index in the array.  You can compute anything you need from that.
Adding the jump number won't help, unless we use a negative number, which you will then need to use with a different command (and make positive again).  This isn't going to make it easier.
The output of :jumps shows the number you need to use with CTRL-O or CTRL-I to jump there.  For programmatic use you don't need that, it can be easily computed.
