### ISSUE TITLE
[request] Signal allowing a (remote) graceful shutdown of [g]vim in the absence of any unsaved changes

### ISSUE THREAD

**Issue by Tormen** [vim/vim#4162]
I am opting to add the possibility to send some signal (does not need to be SIGINT), 
that detects if there are unsaved changes ?
 * *without unsaved-changes*: it gracefully shuts down gvim (e.g. behaves like a `:q`, so it quits vim and removes the swapfile)
 * *with unsaved-chages*: it stops and displays the message: that currently is displayed when a SIGINT is received:
`Type  :qa!  and press <Enter> to abandon all changes and exit Vim`

**Comment by chrisbra** [comment]
If you are using gvim, you can use the remote client api, as documented at `:h remote.txt`
