### ISSUE TITLE
Allocated memory is used without null check in some places.

### ISSUE THREAD

**Issue by GoSSIP-SJTU** [vim/vim#4174]
src/crypt.c  line 256;
src/crypt_zip.c line  93;
src/gui_gtk_f.c  line 132;
src/gui_gtk_x11 line  1578;
src/ibvterm/src/state.c line 332;
src/ibvterm/src/state.c line 255;
src/ibvterm/src/state.c line 1618;
src/ibvterm/src/state.c line 1643
src/ibvterm/src/termscreen.c line 83;
src/ops.c  line 6185;
src/option.c  line 12980;
src/popupmnu.c line 1090;

All the allocated memory in those lines is used without null pointer check.

**Comment by martinkunevtoptal** [comment]
I can work on this issue.

**Comment by martinkunev** [comment]
I started working on this issue.
