### ISSUE TITLE
Conceal for tex and saving folds

### ISSUE THREAD

**Issue by mksyposz** [vim/vim#4175]
When I'm saving my folds by commands suggested on the internet: 
   ```augroup remember_folds
autocmd!
    autocmd BufWinLeave * mkview
    autocmd BufWinEnter * silent! loadview
augroup END
```

vim's function for concealing doesn't work anymore. At least for .tex files.

**Comment by chrisbra** [comment]
please provide a minimal example that reproduces the problem. I cannot reproduce this. Also please note, that you are missing a `augroup` at the start of your code snippet.

**Comment by mksyposz** [comment]
```
augroup remember_folds
    autocmd!
    autocmd BufWinLeave * mkview
    autocmd BufWinEnter * silent! loadview
augroup END

set conceallevel=2
let g:tex_conceal='abdmg'

set encoding=utf-8
```

I'm using this at my vimrc file, basically as miniaml as possible.

```
\documentclass[12pt]{article} 

\begin{document}
$$    \in
    \cup $$

\end{document} 
```

Sample tex file. 
With given vimrc neither \in nor \cup will be changed into their utf-8 equivalents. Aftering commeting the
```
augroup remember_folds
    autocmd!
    autocmd BufWinLeave * mkview
    autocmd BufWinEnter * silent! loadview
augroup END 
```

They will be correctly changed.

**Comment by cecamp** [comment]
Hello:

Your problem is that mkview/loadview do not handle filetype detection, 
nor do they handle syntax on.  See the help:  :help mkview  and search 
for "not perfect".

So, modify your BufWinEnter handling autocmd:

autocmd BufWinEnter * silent! loadview|filetype detect

Hope that helps,
Chip Campbell

**Comment by Konfekt** [comment]
You might also give https://github.com/zhimsel/vim-stay a shot.
