### ISSUE TITLE
matchdelete call fails when current window is not window associated with id

### ISSUE THREAD

**Issue by myitcv** [vim/vim#4178]
`matchaddpos` has the following signature:

```
matchaddpos({group}, {pos} [, {priority} [, {id} [, {dict}]]])
```

This allows me to add a match in a specific window because the `dict` argument is defined as follows:

```
                The optional {dict} argument allows for further custom
                values. Currently this is used to specify a match specific
                conceal character that will be shown for hl-Conceal
                highlighted matches. The dict can have the following members:

                        conceal     Special character to show instead of the
                                    match (only for hl-Conceal highlighted
                                    matches, see :syn-cchar)
                        window      Instead of the current window use the
                                    window with this number or window ID.
```

The value returned from `matchaddpos` is an ID which I had assumed was independent of window. But calling `matchdelete` with a current window of W2, say, passing in an ID that is the result of a call to `matchaddpos` for window W1, fails with:

```
E803: ID not found: <ID>
```

Am I doing something wrong here?

**Comment by andymass** [comment]
As far as I know there is no api to delete a match in a different window.

**Comment by myitcv** [comment]
Thanks.

Perhaps `matchdelete` could take an optional `dict` parameter, to mirror `matchaddpos`?

I think there needs to be some symmetry with `matchaddpos` here whatever the solution.

**Comment by andymass** [comment]
I suppose by symmetry then a dict argument would need to be added to `clearmatches()` and `getmatches()` as well, which is a bit unnatural.

**Comment by myitcv** [comment]
> I suppose by symmetry then a dict argument would need to be added to clearmatches() and getmatches() as well

Yes, I agree.

> which is a bit unnatural.

Why so? 

It's definitely unnatural _not_ to have the `dict` parameter, because it means that you can only call `matchaddpos` without switching windows. There is a definite use case for adding/removing matches in the non-current window (https://github.com/myitcv/govim/pull/24)

**Comment by andymass** [comment]
I just meant that the following API seemed more natural:

```
clearmatches([{win}])
getmatches([{win}])
matchdelete({id} [, {win}])
```

I don't see a strong reason for the extra indirection, i.e.,
```
clearmatches(l:win)           vs      clearmatches({'window': l:win})
getmatches(l:win)             vs      getmatches({'window': l:win})
matchdelete(l:id, l:win)      vs      matchdelete(id, {'window': l:win})
```

Are there any other options besides window that could be put in the dict?  I get the impression it was added to the dict in the case of `matchadd` only to avoid adding a 6th argument.

**Comment by myitcv** [comment]
Ah I see what you mean, apologies. 

I'm absolutely not fixed/set on a particular API, just that there needs to be some means by which a window ID can be specified for the functions you listed.

**Comment by andymass** [comment]
The following patch would implement the non-dict convention for functions `matchdelete, clearmatches, getmatches, setmatches` https://github.com/andymass/vim/commit/44c3c3e1bf7f777edbc282fef898b8eddd5f2f9e?format=patch

**Comment by myitcv** [comment]
Thanks @andymass and @brammool
