### ISSUE TITLE
Test Failure in Lua Test_blob

### ISSUE THREAD

**Issue by scolby33** [vim/vim#4181]
I have just compiled and tested Vim from source and received the following test errors.

```bash
$ pwd
/usr/local/src/vim
$ git status | head -n 1
HEAD detached at v8.1.1056
$ make clean
*snip*
$ rm src/auto/config.cache
$ ./configure --enable-fail-if-missing --with-features=huge --enable-luainterp=yes --enable-perlinterp=yes --enable-pythoninterp=yes --enable-python3interp=yes --enable-rubyinterp=yes --enable-terminal --enable-multibyte --enable-gui=no --with-compiledby="Scott Colby"
*snip*
$ make
*snip*
$ make test
*snip*
Executed 458 tests

Test results:


From test_lua.vim:
Found errors in Test_blob():
function RunTheTest[40]..Test_blob line 3: Expected 0z00010203 but got 0z78303078.30317830.32783033
function RunTheTest[40]..Test_blob line 4: Expected 0z8081FEFF but got 0z78383078.38317866.65786666
function RunTheTest[40]..Test_blob line 7: Expected 0z00000000 but got 0z78303078.30307830.30783030
function RunTheTest[40]..Test_blob line 8: Expected 4.0 but got 12.0
function RunTheTest[40]..Test_blob line 10: Expected 0z012000FF but got 0z012000FF.30307830.30783030
function RunTheTest[40]..Test_blob line 12: Expected 0z012000FF.7A but got 0z012000FF.7A307830.30783030
function RunTheTest[40]..Test_blob line 13: Expected 5.0 but got 12.0
function RunTheTest[40]..Test_blob line 16: Expected 0z012000FF.7A313261.62 but got 0z012000FF.7A307830.30783030.31326162
function RunTheTest[40]..Test_blob line 17: Expected 9.0 but got 16.0
TEST FAILURE
Makefile:52: recipe for target 'report' failed
make[2]: *** [report] Error 1
make[2]: Leaving directory '/usr/local/src/vim/src/testdir'
Makefile:2119: recipe for target 'scripttests' failed
make[1]: *** [scripttests] Error 2
make[1]: Leaving directory '/usr/local/src/vim/src'
Makefile:36: recipe for target 'test' failed
make: *** [test] Error 2

$ # FYI
$ cat /etc/issue
Raspbian GNU/Linux 8 \n \l

$ uname -a
Linux raspberrypi3bplus 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux
$ lua -v
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
```

The offending tests appear to be here: https://github.com/vim/vim/blob/b45125b374cc3a1cef176b704f518c72c518f24c/src/testdir/test_lua.vim#L436

**Comment by brammool** [comment]
The test passes in CI and locally for me, it's likely a problem either with how you run the test or how Vim was build.  My Lua is 5.2.4, perhaps 5.1.5 is too old?

**Comment by scolby33** [comment]
That makes sense. This is happening on a machine that will be upgraded to newer Debian soon and I've had a few problems with outdated dependencies for other programs, so I don't want to take any more time with this at the moment. Thanks for checking on your end!

**Comment by jamessan** [comment]
This is still an issue.  Lua's different versions (5.1, 5.2, etc.) are really different languages, not just iterative updates.

As described in their [version documentation](https://www.lua.org/versions.html):

>  The releases of Lua are numbered x.y.z, where x.y is the version and z is the release.
> 
> Different releases of the same version correspond to bug fixes. Different releases of the same version have the same reference manual, the same virtual machine, and are binary compatible (ABI compatible).
> 
> Different versions are really different. The API is likely to be a little different (but with compatibility switches), and there is no ABI compatibility: applications that embed Lua and C libraries for Lua must be recompiled.

Lua 5.1, primarily due to the fact that Luajit implements Lua 5.1, should probably be the primary target for supported Lua version.

I would suggest fixing Vim to work with Lua 5.1 and then changing the Travis config to test against Lua 5.1.
