### ISSUE TITLE
proposal: generate buffer deltas since last TextChanged,TextChangedI event

### ISSUE THREAD

**Issue by myitcv** [vim/vim#4191]
_I've searched for previous issues but apologies if I used the wrong terms and hence incorrectly turned up no results_

**Is your feature request related something that is currently hard to do? Please describe.**

At present, I use the `TextChanged` and `TextChangedI` events to handle buffer updates within a channel-based plugin (https://github.com/myitcv/govim). 

However I currently send the _entire_ buffer on each change; this is obviously very inefficient.

**Describe the solution you'd like**

To have some means of generating the range-based deltas since the last `TextChanged`/`TextChangedI` event for a given buffer.

My main motivation for this is being able to then pass these deltas on to an [LSP](https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md#textedit) implementation, in this case for the Go language.

**Describe alternatives you've considered**

None that I could think of. Because I think this solution needs to have its origins deep inside the Vim internals.

**Additional context**

n/a

Thank you.

**Comment by prabirshrestha** [comment]
I would also be very interested in support for generating deltas. For [vim-lsp](https://github.com/prabirshrestha/vim-lsp) we manually compute diff in vim script https://github.com/prabirshrestha/vim-lsp/blob/cf0ff507cd59958971142dcbdb54b82667cc1609/autoload/lsp/utils/diff.vim. So if someone is modifying a huge file it only sends partial changes. Computing diff still requires cpu cycles but is faster because the channel write is slower. Bit more context [here](https://github.com/prabirshrestha/vim-lsp/pull/241) where I had thought that adding a builtin diff function could be better and faster in c than vimscript. `let changes = diff(old, new)`.  diff should return a proper object and not diff filetype.

**Comment by chrisbra** [comment]
So a [xdiff function](https://groups.google.com/d/msg/vim_dev/7HX5RbrJIFc/rpcyvMm6CAAJ) would work?

**Comment by myitcv** [comment]
In the scenario I'm envisaging, I simply want to get the diff since the last `TextChanged`/`TextChangedI` event for a given buffer, via something like `getdiffsincelastchange(bufnr)`. 

I don't want to manage/hold on to `old`, the lines from the previous version of the buffer, because I suspect Vim can do this much more efficiently internally.

Or perhaps I misunderstood the question @chrisbra?

**Comment by brammool** [comment]
Something like this is in the todo list, in the context of text properties (which is also related to LSP).
The details haven't been worked out yet.  What I was thinking of was reporting the range of changed lines.  Not the text before the change, since that would involve saving text until it has been dealt with (which may be never).  Do you really need the old text, or just the range of lines that was changed recently?

**Comment by myitcv** [comment]
> Something like this is in the todo list

Fantastic.

> Not the text before the change, since that would involve saving text until it has been dealt with (which may be never)

I'm only proposing these diffs "persist" as long as there isn't another `TextChanged`/`TextChangedI` event. i.e. if you miss an event you lose the previous diffs. 

My starting preference is a diff format similar to the LSP spec:

https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md#textedit

But that preference is largely based on my guess at the most likely use of something like this. And selfishly it would require less effort on my side 😄 

Please let me know if I can help provide any more context/examples.

**Comment by brammool** [comment]
> > Something like this is in the todo list
> 
> Fantastic.
> 
> > Not the text before the change, since that would involve saving text until it has been dealt with (which may be never)
> 
> I'm only proposing these diffs "persist" as long as there isn't
> another `TextChanged`/`TextChangedI` event. i.e. if you miss an event
> you lose the previous diffs. 
> 
> My starting preference is a diff format similar to the LSP spec:
> 
> https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md#textedit
> 
> But that preference is largely based on my guess at the most likely use of something like this. And selfishly it would require less effort on my side 𐟘„ 
> 
> Please let me know if I can help provide any more context/examples.

Doesn't that interface specify a range of lines and the new text?  Then
the old text doesn't need to be passed.  That's a lot simpler.

-- 
In Joseph Heller's novel "Catch-22", the main character tries to get out of a
war by proving he is crazy.  But the mere fact he wants to get out of the war
only shows he isn't crazy -- creating the original "Catch-22".

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by myitcv** [comment]
> Doesn't that interface specify a range of lines and the new text?  Then the old text doesn't need to be passed.  That's a lot simpler.

Ah sorry, I misunderstood what you meant. Then yes, I agree. That is simpler.

> specify a range of lines and the new text

`TextEdit` is defined as:

```
interface TextEdit {
	range: Range;
	newText: string;
}
```

`Range` is defined as:

```
interface Range {
	start: Position;
	end: Position;
}
```

`Position` is define as:

```
interface Position {
	// Line position in a document (zero-based).
	line: number;

	// Character offset on a line in a document (zero-based)
	character: number;
}
```

So I think that allows for edits to be within a line.

_The ever so slightly annoying thing about the LSP spec is that the character offset is defined in terms of UTF16 code points, even though the protocol itself talks over JSON RPC i.e. UTF8. I would definitely recommend we stick with Vim's 1-indexed byte offset column number._

**Comment by myitcv** [comment]
All of that said, if Vim were to initially only generate these diffs line-wise that would be entirely fine by me at least.

**Comment by bobpepin** [comment]
(reposting my comment from the mailing list)
I just had a closer look, seems like the redo list should give us what we want. 
Concretely:
- Suppose the buffer is initially in state S
- make some changes that move the buffer to a new state E
- undo all the way from E until the buffer is back in state S
- then the undo entries between curhead and newhead (in undo.c terminology) are exactly the (range, length, text) events we need for LSP

Attached a little patch to include the text from the undo entries in the output of undotree(), if someone wants to play around with it.
[undo_entries.diff.txt](https://github.com/vim/vim/files/3026306/undo_entries.diff.txt)

**Comment by bobpepin** [comment]
While trying to implement this, I came across the issue that the LSP Change Event needs to include both a start and end position encoded as (line, character) and the length of the changed text in characters. This means that when deleting lines we need to do some extra work to get the length of the deleted text in characters, since it is not part of the redo information. It is however part of the undo information :)

**Comment by myitcv** [comment]
@bobpepin - I don't think that's an issue. If you want to delete the line number 3, for example, then the delta is specified as:

```
[]protocol.TextEdit{
    {
        Range: protocol.Range{
            Start: protocol.Position{Line:2, Character:0},
            End:   protocol.Position{Line:3, Character:0},
        },
        NewText: "",
    },
}
```

(LSP protocol is 0-indexed in terms of line numbers).

Or maybe I misunderstood the point you were making?

**Comment by bobpepin** [comment]
Initial implementation in ES5 available at https://github.com/bobpepin/vim/blob/duktape/src/delta.js, requires the patch above to include changed text in undotree(). It uses no special ES features, so should be straightforward to translate to C or VimScript.

**Comment by bobpepin** [comment]
@myitcv I was looking at this one https://microsoft.github.io/language-server-protocol/specification#textDocument_didChange
It doesn't use TextEdit but something called TextDocumentContentChangeEvent which requires both Range and RangeLength (although it seems that some Emacs guys somewhere are complaining because they can only implement one of them easily).
Is there another way to sync changes that doesn't require RangeLength?
(also, I solved it by combining undo and redo information)

**Comment by myitcv** [comment]
Ah @bobpepin my mistake. I hadn't actually looked in detail at message sent from client to server (because right now I end up sending the entire document). 

I'm unclear why a different message is required for `client -> server` vs `server -> client` (which does use `TextEdit`), but I'll just at that to the list of things I'm not clear on in the spec 😄 

> (also, I solved it by combining undo and redo information)

Great. I'm assuming `RangeLength` is length in bytes?

**Comment by bobpepin** [comment]
> Great. I'm assuming `RangeLength` is length in bytes?

You wish ;) characters between U+010000 and U+10FFFF count twice, http://lists.llvm.org/pipermail/clangd-dev/2018-October/000171.html and https://en.wikipedia.org/wiki/UTF-16.

**Comment by myitcv** [comment]
🤦‍♂️ 

This is probably the "definitive" answer: https://github.com/Microsoft/language-server-protocol/issues/588

I'd suggest that Vim keep things in terms of its version of range (i.e. line number and col byte index) and have length be number of bytes. Because there will likely be consumers of this data that are not LSP clients, and so presenting them with UTF-16 "numbers" would be weird at best, inconvenient at worst.

**Comment by myitcv** [comment]
I note the work that @brammool has done in https://github.com/vim/vim/commit/a334772967de25764ed7b11d768e8b977818d0c6 and prior commits. Will be giving this a test ASAP!

**Comment by chrisbra** [comment]
So I guess the Listener functionality [patch 8.1.1320](https://github.com/vim/vim/commit/6d2399bd1053b367e13cc2b8991d3ff0bf724c7c) solves this issue. See also here:
https://groups.google.com/d/msg/vim_dev/L8jg6u47Dro/CbH3LNXdAQAJ
