### ISSUE TITLE
build failure following 372674fca3250069d8f4943b572474ce077849fd

### ISSUE THREAD

**Issue by myitcv** [vim/vim#4194]
**Describe the bug**

Vim fails to build from source following 372674fca3250069d8f4943b572474ce077849fd

**To Reproduce**
```
./configure --prefix=$HOME/usr/vim --disable-darwin --disable-selinux --enable-perlinterp --enable-pythoninterp --enable-luainterp --disable-netbeans --with-lua-prefix=/usr --with-luajit 
make -j8
```

Gives the error:

```
gui.c: In function ‘gui_init’:
gui.c:687:9: warning: implicit declaration of function ‘gui_mch_maximized’; did you mean ‘gui_mch_mousehide’? [-Wimplicit-function-declaration]
     if (gui_mch_maximized())
         ^~~~~~~~~~~~~~~~~
         gui_mch_mousehide
```

**Expected behavior**

A successful build.

**Screenshots**

n/a

**Environment (please complete the following information):**

 - Vim version v8.1.1092
 - OS: Ubuntu 18.04.2 LTS, amd64
 - Terminal: XTerm(330)

**Additional context**

Please let me know if you need any more details about my setup.

**Comment by brammool** [comment]
I suppose you are not building with GTK.  Motif or Athena perhaps?

**Comment by myitcv** [comment]
Thanks for the fix. I was only looking to build a non-GUI, terminal version. So I think my answer to the above is none of them?

**Comment by brammool** [comment]
> Thanks for the fix. I was only looking to build a non-GUI, terminal
> version. So I think my answer to the above is none of them?

The error is in gui.c, thus you must have picked up some GUI library.
Configure finds it automatically.

-- 
Did you ever see a "Hit any key to continue" message in a music piece?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by myitcv** [comment]
> Configure finds it automatically.

Ah, ok thanks. I've actually switched to explicitly disabling the GUI now.
