### ISSUE TITLE
[Feature Request] Vimscript stopinsert!

### ISSUE THREAD

**Issue by vito-c** [vim/vim#420]
The current implantation of vimscripts stopinsert is a bit lacking. When you call stopinsert it does not fire until after the updatetime has transpired. Resulting in plugins having to do work arounds to get it to function correctly. It would be great if there was a way to do stopinsert! and have it leave insert mode immediately.

**Comment by vim-ml** [comment]
Am 2015-09-16 07:54, schrieb vito-c:

> The current implantation of vimscripts stopinsert is a bit lacking.
> When you call stopinsert it does not fire until after the updatetime
> has transpired. Resulting in plugins having to do work arounds to get
> it to function correctly. It would be great if there was a way to do
> stopinsert! and have it leave insert mode immediately.

Can you please provide an example, where stopinsert does not work
how you expect it?

Best,
Christian
