### ISSUE TITLE
Listchars: no utf8 char for 'space' (used to work)

### ISSUE THREAD

**Issue by Snaptags** [vim/vim#4203]
I am using an utf8 character as a listchar for space: 
![before](https://user-images.githubusercontent.com/1249745/55385644-dc55a380-552d-11e9-9568-e8c30ef4ccad.png)

Probable since 5f8069bbf this does not work any more:
![after](https://user-images.githubusercontent.com/1249745/55385651-e081c100-552d-11e9-9977-2953c6ea348d.png)

**To Reproduce**
Detailed steps to reproduce the behavior:
1. set up gvim to use any nerd font (https://github.com/ryanoasis/nerd-fonts)
2. set listchars=tab:\ ,eol:¬,trail:˽,extends:›,precedes:‹,space:

**Expected behavior**
Display the utf-8 character where spaces would be.

**Environment (please complete the following information):**
 - Vim version 8.1.1099
 - OS: Windows 10 1803
 - gVim

**Comment by k-takata** [comment]
I think this is a duplicate of #4197.

**Comment by Snaptags** [comment]
You're absolutely right, sorry.

**Comment by Snaptags** [comment]
Has been fixed by https://github.com/vim/vim/commit/e5e4e22c1c15c8c22b14935affe969569acc8df9
