### ISSUE TITLE
proposal: means of simulating mouse events to test balloonexpr et al

### ISSUE THREAD

**Issue by myitcv** [vim/vim#4210]
**Is your feature request related something that is currently hard to do? Please describe.**

At the moment it appears (based on my searching at least, apologies if I've used the wrong terms) to be impossible to test mouse-initiated events, e.g. a `balloonexpr`. I've also had a skim of the Vim tests and I can't see anything akin to:

* simulate mouse hover at `line,col`
* verify that balloon shown contains string `s`

**Describe the solution you'd like**

A back-door means by which, during a test run primarily, mouse events can be simulated in order to trigger behaviour. 

**Describe alternatives you've considered**

I don't have any good ideas to work around this right now, hence raising

**Additional context**

n/a

**Comment by brammool** [comment]
Paul Jolly wrote:

> **Is your feature request related something that is currently hard to do? Please describe.**
> 
> At the moment it appears (based on my searching at least, apologies if I've used the wrong terms) to be impossible to test mouse-initiated events, e.g. a `balloonexpr`. I've also had a skim of the Vim tests and I can't see anything akin to:
> 
> * simulate mouse hover at `line,col`
> * verify that balloon shown contains string `s`
> 
> **Describe the solution you'd like**
> 
> A back-door means by which, during a test run primarily, mouse events can be simulated in order to trigger behaviour. 
> 
> **Describe alternatives you've considered**
> 
> I don't have any good ideas to work around this right now, hence raising

Yeah, I also have been wondering about this.  A large part of the mouse
handling is currently not tested.

For the GUI we could insert something at the level of
gui_send_mouse_event().  We could go deeper, e.g. the GTK mouse event
handling, but that gets messy.

For the console we could insert byte sequences, such as the xterm mouse
codes.  It allows for testing the mouse sequence decoding, but that's
not helping for the effect of the mouse events.

It's probaby best to add a way to insert a pseudo-mouse event.  Besides
the byte sequence this would also set mouse_col and mouse_row.

This may need some extra work for double-clicks, since these are
time-sensitive.

-- 
Some of the well known MS-Windows errors:
	EMEMORY		Memory error caused by..., eh...
	ELICENSE	Your license has expired, give us more money!
	EMOUSE		Mouse moved, reinstall Windows
	EILLEGAL	Illegal error, you are not allowed to see this
	EVIRUS		Undetectable virus found

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by myitcv** [comment]
Sounds great. Please let me know if you would like more concrete examples of the tests I would write using such a system, to help flesh out the API.

**Comment by chrisbra** [comment]
we do have now `test_setmouse()` as of commit bb8476be871811e40ddc88c

**Comment by myitcv** [comment]
@brammool thanks for bb8476b. I am successfully using `test_setmouse` in https://github.com/myitcv/govim/commit/3522f71c11b2b5b4fb0d738dba10715499c05cc6

@chrisbra - I don't think we quite have enough here to test `balloonexpr`, because after a call to `test_setmouse` I'm not seeing the `balloonexpr` function be triggered. 

Also, I'm not sure I understand where I would check the current value of the balloon message, even if the call to `test_setmouse` were working?

Does it therefore make sense to reopen this as a tracking issue for the changes required to trigger `balloonexpr` and then test the value of the current balloon?

**Comment by brammool** [comment]
> @brammool thanks for bb8476b. I am successfully using `test_setmouse`
> in
> https://github.com/myitcv/govim/commit/3522f71c11b2b5b4fb0d738dba10715499c05cc6
> 
> @chrisbra - I don't think we quite have enough here to test
> `balloonexpr`, because after a call to `test_setmouse` I'm not seeing
> the `balloonexpr` function be triggered. 
> 
> Also, I'm not sure I understand where I would check the current value
> of the balloon message, even if the call to `test_setmouse` were
> working?
> 
> Does it therefore make sense to reopen this as a tracking issue for
> the changes required to trigger `balloonexpr` and then test the value
> of the current balloon?

I think it should work with the current functionality.  But I found one
problem: the output is not flushed, thus the balloon doesn't show up in
the terminal.  I'll fix that and have an attempt at making a test.

-- 
FROG: How you English say:  I one more time, mac, I unclog my nose towards
      you, sons of a window-dresser,  so, you think you could out-clever us
      French fellows with your silly knees-bent creeping about advancing
      behaviour.  (blows a raspberry) I wave my private parts at your aunties,
      you brightly-coloured, mealy-templed, cranberry-smelling, electric
      donkey-bottom biters.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by myitcv** [comment]
Thanks @brammool, look forward to that fix.

Would you also be open to the suggesting of balloons being tested without screen dumps? Perhaps some special test variables that can be inspect to confirm

* the balloon is visible
* the balloon's rendered contents

That way my checks are slightly more high level and can also apply to gvim.

**Comment by brammool** [comment]
> Thanks @brammool, look forward to that fix.
> 
> Would you also be open to the suggesting of balloons being tested without screen dumps? Perhaps some special test variables that can be inspect to confirm
> 
> * the balloon is visible
> * the balloon's rendered contents
> 
> That way my checks are slightly more high level and can also apply to gvim.

Not really.  It would mean checking if the function was called.  You
could check that in some other way, e.g. by setting a variable in the
script.

What also matters is that just about any "real world" event causes the
balloon to disappear.  For the GUI in a test this does not happen, thus
the balloon would hang around forever.  Hmm, we might actually need
something to get rid of it, such as calling balloon_show('').

-- 
ARTHUR: CHARGE!
   [The mighty ARMY charges.  Thundering noise of feet.  Clatter of coconuts.
   Shouts etc.   Suddenly there is a wail of a siren and a couple of police
   cars roar round in front of the charging ARMY and the POLICE leap out and
   stop them.  TWO POLICEMAN and the HISTORIAN'S WIFE.  Black Marias skid up
   behind them.]
HISTORIAN'S WIFE: They're the ones, I'm sure.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by myitcv** [comment]
@brammool  - just tried  https://github.com/vim/vim/commit/be0a2597ae0d9eb0b8a8a2fc9ae1784faa929844

I'm seeing an incorrect value in `v:beval_col`. `v:beval_bufnr` and `v:beval_lnum` appear to be ok, but the col value is off by ~4.

The approach I'm following is similar to the test in https://github.com/vim/vim/commit/06bd824869b1cb7a85e64ec94135a35698be5b7f:

```
call test_setmouse(6, 6)
feedkeys("\<MouseMove>\<Ignore>", "xt")
```

Given the above I'm seeing a `v:beval_col` value of 2 returned.

Any thoughts?

**Comment by chrisbra** [comment]
I am not completely sure what column and line number are used for  `test_setmouse`. Could it be that `test_setmouse()` takes actual screen columns and rows while the result for `v:beval_col` is the column in the actual line. So e.g. That would mean, that e.g. the gutter width (like numbering or signs column) would have to be substracted from the screen column.

**Comment by brammool** [comment]
> @brammool  - just tried  https://github.com/vim/vim/commit/be0a2597ae0d9eb0b8a8a2fc9ae1784faa929844
> 
> I'm seeing an incorrect value in `v:beval_col`. `v:beval_bufnr` and `v:beval_lnum` appear to be ok, but the col value is off by ~4.
> 
> The approach I'm following is similar to the test in https://github.com/vim/vim/commit/06bd824869b1cb7a85e64ec94135a35698be5b7f:
> 
> ```
> call test_setmouse(6, 6)
> feedkeys("\<MouseMove>\<Ignore>", "xt")
> ```
> 
> Given the above I'm seeing a `v:beval_col` value of 2 returned.
> 
> Any thoughts?

Is this in the GUI?  There the actual mouse pointer position might be
used.

Also, is there text at that position?  If not, then the column is
probably corrected for where there is text.

Otherwise, you might need to add ch_log() statements in the code to
figure out what happens.  Add ch_logfile() in your script to start
recording.

-- 
TERRY GILLIAM PLAYED: PATSY (ARTHUR'S TRUSTY STEED), THE GREEN KNIGHT
                      SOOTHSAYER, BRIDGEKEEPER, SIR GAWAIN (THE FIRST TO BE
                      KILLED BY THE RABBIT)
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by myitcv** [comment]
@brammool 

> Is this in the GUI?  There the actual mouse pointer position might be used.

No, just the terminal for now. Just tested with gvim, and I get 1, 1, 1, for `v:beval_bufnr`, `v:beval_lnum` and `v:beval_col` under the same test.

> Also, is there text at that position?  If not, then the column is probably corrected for where there is text.

Yes, there is definitely text at that position. Because if I move the cursor to that position and call a function that will return the same text as should be displayed in the balloon I get the expected result.

> Otherwise, you might need to add ch_log() statements in the code to figure out what happens.  Add ch_logfile() in your script to start recording.

I'm seeing all of the expected channel calls (I actually have logging within `govim` to also show calls to `gopls`, the LSP server, but the Vim logging shows much the same thing from Vim's perspective). The call is made to the function that is `balloonexpr`, I evaluate the mouse position...which is where I get the wrong column in terminal Vim (and completely wrong position in gvim); it just so happens that at that particular column there is an identifier for which `gopls` returns something sensible. Then `govim` calls `balloon_show` with that text, but then I also don't see anything when I subsequently try to call `balloon_gettext()` from my test harness (which is also remote).
