### ISSUE TITLE
'$ vim' in Linux-console: empty file has 'c' in first position

### ISSUE THREAD

**Issue by klartext** [vim/vim#4215]
opening vim in Linux-console without filename and the empty file/buffer shows a 'c' in first position.

**To Reproduce**
'vim' or 'vim --clean' in linux console
shows a 'c' in first position (1st char of 1st line).

**Expected behavior**
vim shows empyt lines only

**Screenshots**
no screenshot

**Environment (please complete the following information):**
- VIM - Vi IMproved 8.1 (2018 May 18, compiled Mar 29 2019 20:08:59)
- ARCH linux, up to date
- linux console

**Comment by chrisbra** [comment]
what is your $TERM variable set to?  I suppose it might be xterm, although this is not really an xterm? Also please show complete version output.

**Comment by klartext** [comment]
Yes, you are right, $TERM is 'xterm', which is wrong on the console.

------------
VIM - Vi IMproved 8.1 (2018 May 18, compiled Mar 29 2019 20:08:59)
Included patches: 1-1073
Compiled by Arch Linux
Huge version without GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     +tag_old_static
+arabic            -farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    +tcl/dyn
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +textprop
+byte_offset       -hangul_input      +num64             +timers
+channel           +iconv             +packages          +title
+cindent           +insert_expand     +path_extra        -toolbar
-clientserver      +job               +perl/dyn          +user_commands
-clipboard         +jumplist          +persistent_undo   +vartabs
+cmdline_compl     +keymap            +postscript        +vertsplit
+cmdline_hist      +lambda            +printer           +virtualedit
+cmdline_info      +langmap           +profile           +visual
+comments          +libcall           +python/dyn        +visualextra
+conceal           +linebreak         +python3/dyn       +viminfo
+cryptv            +lispindent        +quickfix          +vreplace
+cscope            +listcmds          +reltime           +wildignore
+cursorbind        +localmap          +rightleft         +wildmenu
+cursorshape       +lua/dyn           +ruby/dyn          +windows
+dialog_con        +menu              +scrollbind        +writebackup
+diff              +mksession         +signs             -X11
+digraphs          +modify_fname      +smartindent       -xfontset
-dnd               +mouse             +startuptime       -xim
-ebcdic            -mouseshape        +statusline        -xpm
+emacs_tags        +mouse_dec         -sun_workshop      -xsmp
+eval              +mouse_gpm         +syntax            -xterm_clipboard
+ex_extra          -mouse_jsbterm     +tag_binary        -xterm_save
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.28/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim        -lm -ltinfo -lelf -lnsl    -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.28/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/5.28/core_perl/CORE -lperl -lpthread -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm

**Comment by klartext** [comment]
When unsetting TERM-variable, the problem disappears.

**Comment by tonymec** [comment]
> When unsetting TERM-variable, the problem disappears.

Hm, on my Linux console (after Ctrl-Alt-F2 or similar) $TERM is set to `linux`. IIUC this is a standard setting, see `:help 'clipboard'` According to `:help 'term'`, if $TERM is unset, Vim will set `'term'` to some OS-dependent value, which on Linux is `ansi`. This may or may not be what you want.

Best regards,
Tony.

**Comment by k-takata** [comment]
Don't set $TERM to 'xterm' when you use a terminal which is not compatible with xterm.
Closing.
