### ISSUE TITLE
Vim and Gnome Clipboard indicator not working together

### ISSUE THREAD

**Issue by deragon** [vim/vim#4217]
I cannot get the X11 / Gnome Clipboard to paste into vim/gVim 8.0.1453 under Ubuntu 18.04 with Gnome 3.26 installed when using the [Gnome Clipboard indicator](https://extensions.gnome.org/extension/779/clipboard-indicator/). I also have the same problem with vim compiled from the latest source code cloned from here.  I always get the message:

    E353: Nothing in register "+

Yet, I tried the following settings:

    :set clipboard=unnamed
    :set clipboard=unnamedplus
    :set clipboard=unnamed,unnamedplus
    :set clipboard=unnamed,unnamedplus,autoselect,exclude:cons\|linux

Copy and paste with any other application through the system clipboard after choosing an item in the [Gnome Clipboard indicator](https://extensions.gnome.org/extension/779/clipboard-indicator/)  works well.   Using `xsel -b -o`, I always see my latest selection showing up, suggesting no problem with Gnome Clipboard indicator.  The problem lay only with gVim/vim.

However, if say I copy (CTRL-C) from LibreOffice to gVim, it works fine. Any clue what is going on or how to trace the problem? This inconsistency is baffling.  The problem may not be laying  with vim, but I do not know where to start reporting it so I chose here.  Beside, only vim has a problem with the Gnome Clipboard incdicator.

Someone on [vi.stackexchange.com](https://vi.stackexchange.com/questions/19441/vim-and-gnome-clipboard-indicator-not-working-together) confirmed the problem, suggesting that my particular environment / setup would not be the root cause of the problem.

**Comment by chrisbra** [comment]
So exactly are you trying to paste? Also, since you mention the Gnome Clipboard indicator, does it work without it?

**Comment by deragon** [comment]
[Gnome Clipboard indicator](https://extensions.gnome.org/extension/779/clipboard-indicator/) keeps a list of all the items that have been copied from the PRIMARY and CLIPBOARD and when the user selects one of the items, it is put into CLIPBOARD.

Simple ASCII/UTF8 text does not even work when pasting into vim when having selected an item from  [Gnome Clipboard indicator](https://extensions.gnome.org/extension/779/clipboard-indicator/).  However, pasting does work in any other application.  I do not understand why vim would be different.

**Comment by chrisbra** [comment]
You haven't answered all the questions I asked, but I guess it's the clipboard indicators fault if it works without it then.

**Comment by deragon** [comment]
Sorry, you are right, I have not answered your question.  Paste works if the CLIPBOARD was filled from another application.  It fails only from Gnome Clipboard indicator.

**Comment by chrisbra** [comment]
Then please file an issue at the Gnome Clipboard indicator. The upstream project seems to be there:
https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator

Thanks.

**Comment by deragon** [comment]
There is an existing [issue (#59)](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/issues/59) at Gnome Clipboard indicator.  I linked this issue to theirs.  Lets see if we can get to the bottom of this problem.
