### ISSUE TITLE
Block-mode replace works characterwise instead of blockwise after column 147

### ISSUE THREAD

**Issue by fritzophrenic** [vim/vim#422]
This works fine:

```
gvim -N -u NONE -i NONE
150aa
yyp
:set nowrap linebreak
147|
CTRL+Vj
r0
```

Now do this:

```
u
148|
.
```

Then this:

```
u
148|
CTRL+Vj
r0
```

Both of the bottom two sequences result in the following text:

```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa000
0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000aa
```

This is expected instead:

```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa0aa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa0aa
```

**Comment by fritzophrenic** [comment]
Oops, version info:

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Sep 10 2015 17:54:19)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-854
Compiled by {my user name@my domain}
Huge version with GUI.  Features included (+) or not (-):
+acl             +eval            +mouseshape      +tag_binary
+arabic          +ex_extra        +multi_byte      +tag_old_static
+autocmd         +extra_search    +multi_lang      -tag_any_white
+balloon_eval    +farsi           -mzscheme        -tcl
+browse          +file_in_path    +netbeans_intg   -tgetent
++builtin_terms  +find_in_path    +ole             -termresponse
+byte_offset     +float           +path_extra      +textobjects
+cindent         +folding         +perl/dyn        +title
+clientserver    -footer          +persistent_undo +toolbar
+clipboard       +gettext/dyn     -postscript      +user_commands
+cmdline_compl   -hangul_input    +printer         +vertsplit
+cmdline_hist    +iconv/dyn       +profile         +virtualedit
+cmdline_info    +insert_expand   +python/dyn      +visual
+comments        +jumplist        -python3         +visualextra
+conceal         +keymap          +quickfix        +viminfo
+cryptv          +langmap         +reltime         +vreplace
+cscope          +libcall         +rightleft       +wildignore
+cursorbind      +linebreak       -ruby            +wildmenu
+cursorshape     +lispindent      +scrollbind      +windows
+dialog_con_gui  +listcmds        +signs           +writebackup
+diff            +localmap        +smartindent     -xfontset
+digraphs        -lua             -sniff           -xim
-directx         +menu            +startuptime     -xterm_save
-dnd             +mksession       +statusline      +xpm_w32
-ebcdic          +modify_fname    -sun_workshop    
+emacs_tags      +mouse           +syntax          
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
  system gvimrc file: "$VIM\gvimrc"
    user gvimrc file: "$HOME\_gvimrc"
2nd user gvimrc file: "$HOME\vimfiles\gvimrc"
3rd user gvimrc file: "$VIM\_gvimrc"
    system menu file: "$VIMRUNTIME\menu.vim"
Compilation: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32   -DFEAT_CSCOPE -DFEAT_NETBEANS_INTG   -DFEAT_XPM_W32   -DWINVER=0x0400 -D_WIN32_WINNT=0x0400  /Fo.\ObjGOLYAMD64/ /Ox /GL -DNDEBUG  /Zl /MT -DFEAT_OLE -DFEAT_GUI_W32 -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_PYTHON -DDYNAMIC_PYTHON  -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl522.dll\" -DFEAT_HUGE /Fd.\ObjGOLYAMD64/ /Zi
Linking: link /RELEASE /nologo /subsystem:windows /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib uuid.lib /machine:AMD64 gdi32.lib version.lib   winspool.lib comctl32.lib advapi32.lib shell32.lib  /machine:AMD64 /nodefaultlib libcmt.lib oleaut32.lib user32.lib      /nodefaultlib:python27.lib     WSock32.lib xpm\x64\lib\libXpm.lib /PDB:gvim.pdb -debug
```

**Comment by vim-ml** [comment]
On Wednesday, September 16, 2015 at 10:38:49 AM UTC-5, fritzophrenic wrote:

> This works fine:
> 
> gvim -N -u NONE -i NONE
> 150aa
> yyp
> :set nowrap linebreak
> 147|
> CTRL+Vj
> r0
> 
> Now do this:
> 
> u
> 148|

Weird, that got truncated. Copied from GitHub:

This works fine:

gvim -N -u NONE -i NONE
150aa
yyp
:set nowrap linebreak
147|
CTRL+Vj
r0

Now do this:

u
148|
.

Then this:

u
148|
CTRL+Vj
r0

Both of the bottom two sequences result in the following text:

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa000
0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000aa

This is expected instead:

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa0aa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa0aa

**Comment by vim-ml** [comment]
Hi Ben!

On Mi, 16 Sep 2015, Ben Fritz wrote:

> On Wednesday, September 16, 2015 at 10:38:49 AM UTC-5, fritzophrenic wrote:
> 
> > This works fine:
> > 
> > gvim -N -u NONE -i NONE
> > 150aa
> > yyp
> > :set nowrap linebreak
> > 147|
> > CTRL+Vj
> > r0
> > 
> > Now do this:
> > 
> > u
> > 148|
> 
> Weird, that got truncated. Copied from GitHub:
> 
> This works fine:
> 
> gvim -N -u NONE -i NONE
> 150aa
> yyp
> :set nowrap linebreak
> 147|
> CTRL+Vj
> r0
> 
> Now do this:
> 
> u
> 148|
> .
> 
> Then this:
> 
> u
> 148|
> CTRL+Vj
> r0
> 
> Both of the bottom two sequences result in the following text:
> 
> aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa000
> 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000aa
> 
> This is expected instead:
> 
> aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa0aa
> aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa0aa

Looks like a regression from patch 7.4.818, sorry about that. Attached 
is a patch, that fixes it, including a test.

Attachment won't be visible in github however.

Best,

## Christian

Wer aus dem Rahmen fällt war vorher nicht unbedingt im Bilde.

**Comment by vim-ml** [comment]
On Wednesday, September 16, 2015 at 12:14:56 PM UTC-5, Christian Brabandt wrote:

> Hi Ben!
> 
> Looks like a regression from patch 7.4.818, sorry about that. Attached 
> is a patch, that fixes it, including a test.
> 
> Attachment won't be visible in github however.

Great, I confirm that fixes the problem!

I see that you test uses column 147, which was my "working" case. Column 148 was the broken case. I'm not sure if that number is special somehow, or if you got it to fail using column 147 on your machine, but maybe that test needs an update.

**Comment by vim-ml** [comment]
Christian wrote:

> Hi Ben!
> 
> On Mi, 16 Sep 2015, Ben Fritz wrote:
> 
> > On Wednesday, September 16, 2015 at 10:38:49 AM UTC-5, fritzophrenic wrote:
> > 
> > > This works fine:
> > > 
> > > gvim -N -u NONE -i NONE
> > > 150aa
> > > yyp
> > > :set nowrap linebreak
> > > 147|
> > > CTRL+Vj
> > > r0
> > > 
> > > Now do this:
> > > 
> > > u
> > > 148|
> > 
> > Weird, that got truncated. Copied from GitHub:
> > 
> > This works fine:
> > 
> > gvim -N -u NONE -i NONE
> > 150aa
> > yyp
> > :set nowrap linebreak
> > 147|
> > CTRL+Vj
> > r0
> > 
> > Now do this:
> > 
> > u
> > 148|
> > .
> > 
> > Then this:
> > 
> > u
> > 148|
> > CTRL+Vj
> > r0
> > 
> > Both of the bottom two sequences result in the following text:
> > 
> > aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa000
> > 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000aa
> > 
> > This is expected instead:
> > 
> > aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa0aa
> > aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa0aa
> 
> Looks like a regression from patch 7.4.818, sorry about that. Attached 
> is a patch, that fixes it, including a test.
> 
> Attachment won't be visible in github however.

Thanks, I'll look into it.

## 

If the Universe is constantly expanding, why can't I ever find a parking space?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
Does someone know where these duplicate messages from hostway.com
are triggered by?  And how to stop that?

## 

The budget process was invented by an alien race of sadistic beings who
resemble large cats.
                (Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///
