### ISSUE TITLE
make va"aw works fine

### ISSUE THREAD

**Issue by eiro** [vim/vim#4225]
imagine you have this text

            class="top" style="border:none;margin-top: 1px;" href="this"

if you want to select the first attribute from the word "style", you can 2f". but if you are in the middle of the value, it would be nice to have va"aw works. instead, aw selects href=.

**Comment by tonymec** [comment]
`<Visual>aw` seems to extend to the right; but you can do va"obb which does the following:
- va" selects the double-quoted string; the cursor is left on the right-hand quote.
- o moves the cursor to the other end of the visual selection
- b moves it to the equal sign
- b again moves it to the s of style=

Best regards,
Tony.

**Comment by eiro** [comment]
thanks for the tip. a bit shorter with va"oB.

but anyway, it doesn't feel consistent when you have habits like vatatatat.

regards

**Comment by erickpaquin** [comment]
@eiro , Can this PR be closed?

**Comment by eiro** [comment]
indeed
