### ISSUE TITLE
Help! Some errors about YCM for Gvim

### ISSUE THREAD

**Issue by ComeOrDream** [vim/vim#4227]
There is something wrong when I am installing YCM for Windows10 today. Could you guys please help me?
I think I have successfully installed python for Gvim.
![无标题](https://user-images.githubusercontent.com/43801479/55780575-dede6d00-5ada-11e9-8982-6ee21d324f1e.png)
![无标题2](https://user-images.githubusercontent.com/43801479/55780579-dede6d00-5ada-11e9-9efe-fbca0bff4bff.png)
![无标题3](https://user-images.githubusercontent.com/43801479/55780582-df770380-5ada-11e9-9c59-3bb58c52cdb3.png)

**Comment by k-takata** [comment]
Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. Closing.
