### ISSUE TITLE
Test_terminal_getwinpos fails when terminal is large

### ISSUE THREAD

**Issue by dpelle** [vim/vim#4228]
**Describe the bug**
Test `Test_terminal_getwinpos()` fails when terminal has many columns (>= 203 columns).

**To Reproduce**
1) Use a large terminal with >= 203 columns. You may need to reduce font size to be able to have a terminal with enough columns.
I can reproduce the ticket with for example with terminal that has 58 lines & 203 columns.
The bug does not happen with a terminal size of 58 lines & 202 columns.
I think that bug happens when number of columns is >= 203.

2) Run:
```
$ cd vim/src/testdir
$ make test_terminal
...snip...
Executed 78 tests
1 FAILED:
Found errors in Test_terminal_getwinpos():
function RunTheTest[40]..Test_terminal_getwinpos line 25: Expected range 1 - 999, but got 1246
```

**Expected behavior**
All tests should succeed.

**Environment**
 - vim-8.1.1140
 - OS: xubuntu 18.04.2 (up-to-date), x86_64
 - Terminal: at least xterm(330) or MATE terminal (1.20.0) & console without X.

**Comment by brammool** [comment]
Dominique wrote:

> **Describe the bug**
> Test `Test_terminal_getwinpos()` fails when terminal has many columns (>= 203 columns).
> 
> **To Reproduce**
> 1) Use a large terminal with >= 203 columns. You may need to reduce font size to be able to have a terminal with enough columns.
> I can reproduce the ticket with for example with terminal that has 58 lines & 203 columns.
> The bug does not happen with a terminal size of 58 lines & 202 columns.
> I think that bug happens when number of columns is >= 203.
> 
> 2) Run:
> ```
> $ cd vim/src/testdir
> $ make test_terminal
> ...snip...
> Executed 78 tests
> 1 FAILED:
> Found errors in Test_terminal_getwinpos():
> function RunTheTest[40]..Test_terminal_getwinpos line 25: Expected range 1 - 999, but got 1246
> ```
> 
> **Expected behavior**
> All tests should succeed.
> 
> **Environment**
>  - vim-8.1.1140
>  - OS: xubuntu 18.04.2 (up-to-date), x86_64
>  - Terminal: at least xterm(330) or MATE terminal (1.20.0) & console without X.

That rough value of 1000 was clearly not a good idea.
I'll calculate it more accurately.

-- 
Google is kind of like Dr. Who's Tardis; it's weirder on the
inside than on the outside...

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
