### ISSUE TITLE
:help shell-window should be removed after vim :terminal

### ISSUE THREAD

**Issue by zeus2615** [vim/vim#4231]
As vim has a terminal in window now, so the old help about shell-window should be removed.

==============================================================================
Executing shell commands in a window                    shell-window

There have been questions for the possibility to execute a shell in a window
inside Vim.  The answer: you can't!  Including this would add a lot of code to
Vim, which is a good reason not to do this.  After all, Vim is an editor, it
is not supposed to do non-editing tasks.  However, to get something like this,
you might try splitting your terminal screen or display window with the
"splitvt" program.  You can probably find it on some ftp server.  The person
that knows more about this is Sam Lantinga <slouken@cs.ucdavis.edu>.
An alternative is the "window" command, found on BSD Unix systems, which
supports multiple overlapped windows.  Or the "screen" program, found at
www.uni-erlangen.de, which supports a stack of windows.

**Comment by andymass** [comment]
How old is your vim?  This was edited over 9 months ago.

Nevertheless, the current information is still mostly outdated and can be removed.

**Comment by chrisbra** [comment]
The information in the latest version is correct: https://vimhelp.org/tips.txt.html#shell-window
closing as invalid.
