### ISSUE TITLE
xdiff as one of built-in functions

### ISSUE THREAD

**Issue by rickhowe** [vim/vim#4241]
I sometimes set `diffexpr` option to modify the diff behavior. For example, the following script compares different windows line-by-line.
```
set diffexpr=LineByLineDiff()
function! LineByLineDiff()
    let opt = '-a --binary '
    if &diffopt =~ 'icase' | let opt .= '-i ' | endif
    if &diffopt =~ 'iwhite' | let opt .= '-b ' | endif
    let [fi, fn, fo] = [v:fname_in, v:fname_new, v:fname_out]
    call writefile(map(readfile(fi), 'v:key . ":" . v:val'), fi)
    call writefile(map(readfile(fn), 'v:key . ":" . v:val'), fn)
    call writefile(split(system('diff ' . opt . fi . ' ' . fn), '\n'), fo)
endfunction
```
Until patch 8.1.360, in which the internal xdiff library was build in vim, it has been necessary to use the the external diff command.

I am interested in using the xdiff as well in my script because it should be much faster and, more importantly, the diff command should not be required in a system.

Is it possible to implement the xdiff as one of built-in functions?

**Comment by prabirshrestha** [comment]
I had requested diff as a builtin function to be used in vimscript here. https://github.com/vim/vim/issues/4191#issuecomment-478213781
