### ISSUE TITLE
Invalid JSON sent via ch_sendexpr

### ISSUE THREAD

**Issue by myitcv** [vim/vim#4244]
**Describe the bug**

Some invalid/junk characters are sent after a JSON-encoded value via a `ch_sendexpr` call. This results in the other end of the channel (https://github.com/myitcv/govim in this case) being unable to parse the next JSON message. Roughly the sequence sent looks like this (grabbing a couple of lines from the output of `ch_logfile`):

```
 30.280997 SEND on 0(sock): '[162,["function","autocommand:1"]]
'
 30.281073 on 0: Reading JSON
 30.281081 : looking for messages on channels
 30.281085 on 0: Waiting for up to 30000 msec
 30.281449 RECV on 0(sock): '[0,[90,"expr","{\"Num\": bufnr(\"\"), \"Name\": expand('%:p'), \"Contents\": join(getline(0, \"$\"), \"\\n\")}"]]
'
 30.281460 : looking for messages on channels
 30.281468 on 0: Getting JSON message 0
 30.281470 on 0: Invoking channel callback <SNR>46_define
 30.282097 SEND on 0(sock): '[163,["callback",90,["",{"Num":1,"Name":"/home/myitcv/gostuff/src/github.com/myitcv/govim/testdriver/testdriver.go","Contents":"file body"}]]]
 V'
```

Compare the first `SEND` (which is valid), with the second (which is invalid).

The second includes the junk ` V` after what is otherwise a valid blob of JSON, i.e. the encoding of the value was successful.

**To Reproduce**

I don't have a minimal reproduction unfortunately, so I'm reporting here to get some advice on how to proceed.

This does reproduce however with a very minimal `.vimrc`:

```
set nocompatible
set nobackup
set nowritebackup
set noswapfile
```

followed by then loading the `govim` plugin.

**Expected behavior**

No invalid/junk sent with the JSON value.

**Screenshots**

n/a

**Environment (please complete the following information):**
 - Vim version

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr  8 2019 15:10:04)
Included patches: 1-1137
Compiled by myitcv@myitcv
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     -tag_old_static
+arabic            -farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    -tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
+balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
+browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           -netbeans_intg     +textprop
+byte_offset       -hangul_input      +num64             +timers
+channel           +iconv             +packages          +title
+cindent           +insert_expand     +path_extra        +toolbar
+clientserver      +job               -perl              +user_commands
+clipboard         +jumplist          +persistent_undo   +vartabs
+cmdline_compl     +keymap            +postscript        +vertsplit
+cmdline_hist      +lambda            +printer           +virtualedit
+cmdline_info      +langmap           +profile           +visual
+comments          +libcall           +python            +visualextra
+conceal           +linebreak         -python3           +viminfo
+cryptv            +lispindent        +quickfix          +vreplace
+cscope            +listcmds          +reltime           +wildignore
+cursorbind        +localmap          +rightleft         +wildmenu
+cursorshape       +lua               -ruby              +windows
+dialog_con_gui    +menu              +scrollbind        +writebackup
+diff              +mksession         +signs             +X11
+digraphs          +modify_fname      +smartindent       -xfontset
+dnd               +mouse             +startuptime       +xim
-ebcdic            +mouseshape        +statusline        +xpm
+emacs_tags        +mouse_dec         -sun_workshop      +xsmp_interact
+eval              -mouse_gpm         +syntax            +xterm_clipboard
+ex_extra          -mouse_jsbterm     +tag_binary        -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/home/myitcv/usr/vim/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16   -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl   -ldl  -L/usr/lib/x86_64-linux-gnu -lluajit-5.1  -L/home/myitcv/.pythons/2.7.15/lib/python2.7/config -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic       
```

- OS: Ubuntu 18.04.2 LTS
- Terminal: XTerm(330)

**Additional context**

n/a

**Comment by myitcv** [comment]
Please note the lines I've copied from the output of `ch_logfile` are very much abbreviated. I don't know whether that's significant or not. i.e. the JSON messages quite a bit bigger than shown. I can provide the entire `ch_logfile` output if that would be useful.

**Comment by brammool** [comment]
> **Describe the bug**
> 
> Some invalid/junk characters are sent after a JSON-encoded value via a `ch_sendexpr` call. This results in the other end of the channel (https://github.com/myitcv/govim in this case) being unable to parse the next JSON message. Roughly the sequence sent looks like this (grabbing a couple of lines from the output of `ch_logfile`):
> 
> ```
>  30.280997 SEND on 0(sock): '[162,["function","autocommand:1"]]
> '
>  30.281073 on 0: Reading JSON
>  30.281081 : looking for messages on channels
>  30.281085 on 0: Waiting for up to 30000 msec
>  30.281449 RECV on 0(sock): '[0,[90,"expr","{\"Num\": bufnr(\"\"), \"Name\": expand('%:p'), \"Contents\": join(getline(0, \"$\"), \"\\n\")}"]]
> '
>  30.281460 : looking for messages on channels
>  30.281468 on 0: Getting JSON message 0
>  30.281470 on 0: Invoking channel callback <SNR>46_define
>  30.282097 SEND on 0(sock): '[163,["callback",90,["",{"Num":1,"Name":"/home/myitcv/gostuff/src/github.com/myitcv/govim/testdriver/testdriver.go","Contents":"file body"}]]]
>  ŽV'
> ```
> 
> Compare the first `SEND` (which is valid), with the second (which is invalid).
> 
> The second includes the junk ` ŽV` after what is otherwise a valid blob of JSON, i.e. the encoding of the value was successful.

Strange.  Looking at the code I actually do see a problem, the NUL is
missing at the end.  But that only happens when the result is exactly
4000 bytes long, you are not nearly close to that.

There is also a problem not appending the NUL when producing log
messages.  But you are also not close that that limit.

Anyway, let me fix that problem, then please check if your problem
persists.

-- 
hundred-and-one symptoms of being an internet addict:
261. You find diskettes in your pockets when doing laundry.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by myitcv** [comment]
> But that only happens when the result is exactly 4000 bytes long, you are not nearly close to that.

Apologies, I clarified that exact point in a follow up message:

https://github.com/vim/vim/issues/4244#issuecomment-482671578

> Anyway, let me fix that problem, then please check if your problem persists.

Fantastic, thanks. I'll look of for the commit

**Comment by myitcv** [comment]
Confirmed that 04af19637c14045fa33b99576de4eea1e3524edb does indeed fix this. Thanks for the quick turnaround @brammool
