### ISSUE TITLE
Test_term_gettitle fails when Vim built with autoservername feature

### ISSUE THREAD

**Issue by Tosainu** [vim/vim#4249]
**Describe the bug**
After [patch v8.1.1121](https://github.com/vim/vim/commit/4a5711b5ea54525a262a57ec0d418f76504bad46), `Test_term_gettitle` fails when Vim built with `+autoservername` feature.

**To Reproduce**
1. Build Vim v8.1.1121 with `+autoservername` feature.
    ```
    $ git clone -b v8.1.1121 https://github.com/vim/vim.git
    $ cd vim
    $ ./configure --with-x --disable-gui --enable-autoservername
    $ make -j4
    ```
2. Run `test_terminal`.
    ```
    $ cd src/testdir/
    $ make test_terminal
    ```
3. `Test_term_gettitle` fails with following messages.
    ```
    ...
    Executing Test_terminwinscroll()
    Executing Test_zz1_terminal_in_gui()
    Executing Test_zz2_terminal_guioptions_bang()
    Executed 77 tests
    1 FAILED:
    Found errors in Test_term_gettitle():
    function RunTheTest[40]..Test_term_gettitle[11]..WaitForAssert[2]..<SNR>6_WaitForCommon[11]..<lambda>1 line 1: Expected '[No Name] - VIM' but got '[No Name] - VIM1'
    ```

**Expected behavior**
All terminal tests should be passed.

**Environment**
 - Vim version: v8.1.1121
 - OS: Arch Linux
 - Terminal: [Alacritty](https://github.com/jwilm/alacritty)

**Comment by dpelle** [comment]
Fixed in PR #4250
