### ISSUE TITLE
python3 lib does not init finish sometimes when vim open vimrc file .

### ISSUE THREAD

**Issue by kerwinxu** [vim/vim#4254]
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Describe the bug**
(Issues related to the runtime files should be reported to their maintainer, check the file header.)
when i put the below into my vimrc , 
py3 import os;import sys;sys.executable=os.path.join(sys.prefix,'python.exe') 
it show the below error .
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

but  i input "py3 print('hello world')" when i opened vim and delete "py3 import os;import sys;sys.executable=os.path.join(sys.prefix,'python.exe') ", it show "hello world " , i think the problem is python3 is not init finish  when vim open vimrc file .

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean` (or `gvim --clean`, etc.)
2. Edit `filename`
3. Type '....'
4. Describe the error

**Expected behavior**
i input the below string into my vimrc
py3 print('hello world')" when i opened vim and delete "py3 import os;import sys;sys.executable=os.path.join(sys.prefix,'python.exe') 
it should work 
but it does not work sometimes , it show below error 
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

**Screenshots**
If applicable, copy/paste the text or add screenshots to help explain your problem.

**Environment (please complete the following information):**
 - Vim version [e.g. 8.1.1234] (Or paste the result of `vim --version`.)
 - OS: [Windows 10 1809,]
 - Terminal: [e.g. GNOME Terminal, mintty, iTerm2, tmux, GNU screen] (Use GUI if you use the GUI.)

**Additional context**

vim --version :
VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 14 2019 15:53:43)
MS-Windows 64-bit console version
Included patches: 1-1023
Compiled by kerwin@XUHENGXIAO
Huge version without GUI.  Features included (+) or not (-):
+acl               +eval              +multi_byte        +termguicolors
+arabic            +ex_extra          +multi_lang        +terminal
+autocmd           +extra_search      -mzscheme          -termresponse
+autochdir         -farsi             -netbeans_intg     +textobjects
+autoservername    +file_in_path      +num64             +textprop
-balloon_eval      +find_in_path      +packages          -tgetent
+balloon_eval_term +float             +path_extra        +timers
-browse            +folding           -perl              +title
++builtin_terms    -footer            +persistent_undo   -toolbar
+byte_offset       +gettext/dyn       +postscript        +user_commands
+channel           -hangul_input      +printer           +vartabs
+cindent           +iconv/dyn         +profile           +vertsplit
+clientserver      +insert_expand     -python            +virtualedit
+clipboard         +job               +python3/dyn       +visual
+cmdline_compl     +jumplist          +quickfix          +visualextra
+cmdline_hist      +keymap            +reltime           +viminfo
+cmdline_info      +lambda            +rightleft         +vreplace
+comments          +langmap           -ruby              +vtp
+conceal           +libcall           +scrollbind        +wildignore
+cryptv            +linebreak         +signs             +wildmenu
+cscope            +lispindent        +smartindent       +windows
+cursorbind        +listcmds          +startuptime       +writebackup
+cursorshape       +localmap          +statusline        -xfontset
+dialog_con        +lua/dyn           -sun_workshop      -xim
+diff              +menu              +syntax            -xpm_w32
+digraphs          +mksession         +tag_binary        -xterm_save
-dnd               +modify_fname      +tag_old_static
-ebcdic            +mouse             -tag_any_white
+emacs_tags        -mouseshape        +tcl/dyn
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
Compilation: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_TERMINAL  -DFEAT_JOB_CHANNEL      -DWINVER=0x0A00 -D_WIN32_WINNT=0x0A00 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG /arch:AVX2 /Zl /MT -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl86t\" -DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua53.dll\" -DFEAT_PYTHON3 -DPYTHON3_HOME=L\"D:\Anaconda3\" -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python37.dll\" -DMSWINPS -DFEAT_HUGE /Fd.\ObjCUHTAMD64/ /Zi
Linking: link  /nologo /subsystem:console /opt:ref /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib netapi32.lib uuid.lib /machine:AMD64   libcmt.lib  user32.lib  /nodefaultlib:lua53.lib    /nodefaultlib:python37.lib   "E:\project\vc\Python-3.7.2\externals\tcltk64\lib\tclstub86.lib" WSock32.lib /PDB:vim.pdb -debug

**Comment by k-takata** [comment]
You don't utilize the issue template at all.
Please fill "Environment" at least. What is your vim version? What is your OS? etc.
It is also recommended to fill "To Reproduce" and "Expected behavior", then remove irrelevant text as the first line of the template says:

> Instructions: Replace the template text and remove irrelevant text (including this line)

**Comment by chrisbra** [comment]
> i think the problem is python3 is not init finish when vim open vimrc file .

If that is really the case, you might want to wrap this into an VimEnter autocommand. 

Please note, I find your bug description to be hard to read, please format it using markdown besides filling out the issue template as already discussed. Also please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. Thanks. Closing.
