### ISSUE TITLE
Can the theme, desert, be improved?

### ISSUE THREAD

**Issue by kgfly** [vim/vim#4260]
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Is your feature request related something that is currently hard to do? Please describe.**

The char of most dark them except desert is too bright. So I only consider desert. However, for desert, the char in quickfix window is hard to read.

This is what the quickfix window of desert looks like,
![image](https://user-images.githubusercontent.com/12282281/56150324-80ded900-5f63-11e9-99c1-9dc6c6211ee1.png)

This is what the quickfix window of default theme looks like,

![image](https://user-images.githubusercontent.com/12282281/56150345-905e2200-5f63-11e9-98a1-336431174638.png)

You can see the highlighted char in desert is hard to read.

**Describe the solution you'd like**
For desert, change the background to make the char easier to ready.

**Describe alternatives you've considered**
I am currently using this dark theme, https://github.com/liuchengxu/space-vim-dark 

![image](https://user-images.githubusercontent.com/12282281/56150421-bc79a300-5f63-11e9-9cdc-7522b182293b.png)

**Additional context**

**Comment by chrisbra** [comment]
So the contrast in the quickfix window for the currently selected item is too small? That uses the `QuickFixLine` highlighting group. You can adjust that in your vimrc with e.g. a colorscheme auto command.

Have you contacted the maintainer of the file?

**Comment by chrisbra** [comment]
for better color schemes see #1665

**Comment by kgfly** [comment]
Thanks. I didn't contact the maintainer. I tried

hi QuickFixLine term=standout ctermfg=0 ctermbg=3 guifg=Black guibg=Yellow
hi QuickFixLine term=reverse ctermbg=52
hi QuickFixLine term=reverse ctermbg=Cyan guibg=Cyan

But  QuickFixLine  seems not working. It no longer has highlighted line, etc

![image](https://user-images.githubusercontent.com/12282281/56163929-741ead00-5f84-11e9-98dc-86d7a63455e2.png)

I prefer desert. If not  working, I just use the default white one.

**Comment by idbrii** [comment]
@9527KGG:  I forked desert to make my sandydune colorscheme to solve some of these issues, make some colour prettier, and to add more color variation to distinguish types. My reddish solution to this problem improves the contrast, ~but isn't pretty -- I might improve this one~ *fixed*.

Check it out: https://github.com/idbrii/vim-sandydune
