### ISSUE TITLE
Lost script color after deleting .swp file.

### ISSUE THREAD

**Issue by ahmedshaaban1** [vim/vim#4263]
I lost the bash and python script color after removing the .swp file ... 
Any idea how to restor the colors again. I tried syntax on, but it did not works. 
 Thanks 

**Environment (please complete the following information):**
 -  VIM 7.4.629
 - OS: Centos 6.8
 - Terminal: [ GNOME Terminal]

**Comment by chrisbra** [comment]
What do you mean, you lost the colors? Please give exact steps of what you did. We are missing lots of information here.
Also please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here.

**Comment by chrisbra** [comment]
missing feedback. Closing. If this happens again, please mention clearly what happens, what you see and what you expect (and try to reproduce with the latest version). 
Also please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. Closing.

**Comment by ahmedshaaban1** [comment]
sorry for the inconvenience... I could not produce the error.
