### ISSUE TITLE
typescript filetype and indent

### ISSUE THREAD

**Issue by misakisuna705** [vim/vim#4264]
vim 8.1.1150 installed by brew on macOS 10.13.6

*.ts filetype is xml, not typescript.

autoindent does not work in the file

**Comment by misakisuna705** [comment]
I temporarily use these to solve such issue:

au BufNewFile,BufRead *.ts set filetype=typescript

au FileType typescript set indentexpr=

set cindent

**Comment by brammool** [comment]
We don't have typescript runtime files yet, but I suppose typescript is now so widespread we should assume .ts files are typescript now.  I'll add it.
