### ISSUE TITLE
Allow substitution in a subset of a line

### ISSUE THREAD

**Issue by teto** [vim/vim#4272]
**Is your feature request related something that is currently hard to do? Please describe.**
When selecting a portion of a line with `ctrl_v` then entering command mode (`:`), the marks used are `'<, '>` instead of ``` `<,`> ```

My intention was to replace spaces ` ` by `,` in the block selection via ```:`<,`>s/ /, ``` but according to the doc, seems like substitute only applies to lines. Is there any workaround to substitute on a subset of the line (without regexes, just using the previously mentioned marks) ?

**Comment by vim-ml** [comment]
On 2019-04-16, Matthieu Coudron wrote:

> When selecting a portion of a line with ctrl_v then entering command mode (:),
> the marks used are '<, '> instead of `<,`>
> 
> My intention was to replace spaces by , in the block selection via :`<,`>s/ /,
> but according to the doc, seems like substitute only applies to lines. Is there
> any workaround to substitute on a subset of the line (without regexes, just
> using the previously mentioned marks) ?

There is a plugin that does that:  vis.vim.  It is available from
any of these places.

    http://www.vim.org/scripts/script.php?script_id=1195
    http://www.drchip.org/astronaut/vim/index.html#VIS
    https://github.com/vim-scripts/vis

Regards,
Gary

**Comment by chrisbra** [comment]
Yes, ex commands always work linewise. For `:s` you can make sure to match inside the visual selected area by using the `\%V` atom. For allowing `:commands` to work on the column, there is already #3292 (and it is a long standing item in the todo list). So closing.

**Comment by teto** [comment]
thanks gary for the mention. Seems a bit buggy (it replaced a character right before the selection start) but thanks for it. Also not sure why but neovim's inccommand wouldn't work.

@chrisbra  Thanks for the `s /\%V /,` trick, it works with inccommand preview as well ! My first post would make for a more consistent UI, but hopefully #3292 can help solve that.

**Comment by chrisbra** [comment]
> but hopefully #3292 can help solve that.

I wouldn't bet that it will be implemented anytime soon. It's been in the todo list for as long as I remember
