### ISSUE TITLE
setqflist causes current window "focus" to switch and not be restored?

### ISSUE THREAD

**Issue by myitcv** [vim/vim#4278]
**Describe the bug**

As part of https://github.com/myitcv/govim, I have a `CursorHold,CursorHoldI` autocmd setup the populates the quickfix list via `setqflist` if any diagnostics have changed.

This works well apart from the fact that there appears to be a changing of buffers that happens that causes a flicker on screen... and for the "current" window (excuse the almost certainly loose terminology) to not be restored. 

This is best demonstrated by a video in which I've slightly changed the code to _always_ call `setqflist(entries, 'r')`, regardless of whether the diagnostics have changed. In between cursor holds, I am simply moving up and down the document with `j` and `k`:

https://youtu.be/qi-tx2jNWBY

As you can see the "active" window changes to the quickfix window and doesn't return to where the cursor is. However when I press `j` or `k` again the focus shifts back to the where I'm expecting it to be.

**To Reproduce**

I don't have a minimal reproduction for this unfortunately.

**Expected behavior**

The "focus" not to flicker as shown above.

**Screenshots**

Video provided above.

**Environment (please complete the following information):**
 - Vim version

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 18 2019 02:24:21)
Included patches: 1-1183
Compiled by myitcv@myitcv
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     -tag_old_static
+arabic            -farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    -tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
+balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
+browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           -netbeans_intg     +textprop
+byte_offset       -hangul_input      +num64             +timers
+channel           +iconv             +packages          +title
+cindent           +insert_expand     +path_extra        +toolbar
+clientserver      +job               -perl              +user_commands
+clipboard         +jumplist          +persistent_undo   +vartabs
+cmdline_compl     +keymap            +postscript        +vertsplit
+cmdline_hist      +lambda            +printer           +virtualedit
+cmdline_info      +langmap           +profile           +visual
+comments          +libcall           +python            +visualextra
+conceal           +linebreak         -python3           +viminfo
+cryptv            +lispindent        +quickfix          +vreplace
+cscope            +listcmds          +reltime           +wildignore
+cursorbind        +localmap          +rightleft         +wildmenu
+cursorshape       +lua               -ruby              +windows
+dialog_con_gui    +menu              +scrollbind        +writebackup
+diff              +mksession         +signs             +X11
+digraphs          +modify_fname      +smartindent       -xfontset
+dnd               +mouse             +startuptime       +xim
-ebcdic            +mouseshape        +statusline        +xpm
+emacs_tags        +mouse_dec         -sun_workshop      +xsmp_interact
+eval              -mouse_gpm         +syntax            +xterm_clipboard
+ex_extra          -mouse_jsbterm     +tag_binary        -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/home/myitcv/usr/vim/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16   -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl   -ldl  -L/usr/lib/x86_64-linux-gnu -lluajit-5.1  -L/home/myitcv/.pythons/2.7.15/lib/python2.7/config -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic       
```

- OS: Ubuntu 18.04.2 LTS
- Terminal: XTerm(330)

**Additional context**

n/a

**Comment by vim-ml** [comment]
Hi,

On Thu, Apr 18, 2019 at 1:23 AM Paul Jolly <vim-dev-github@256bit.org> wrote:
>
> Describe the bug
>
> As part of https://github.com/myitcv/govim, I have a
> CursorHold,CursorHoldI autocmd setup the populates the quickfix list
> via setqflist if any diagnostics have changed.
>
> This works well apart from the fact that there appears to be a
> changing of buffers that happens that causes a flicker on screen...
>

When the quickfix list is changed by the setqflist() function, if the quickfix
window is present, then the quickfix buffer will be updated. As part of
updating the quickfix buffer, the screen will be refreshed (this includes
saving the current cursor position and window, making the quickfix window
as the current window, updating the quickfix buffer contents, restoring
the previous window as the current window and restoring the cursor
position).

>
> and for the "current" window (excuse the almost certainly loose
> terminology) to not be restored.
>
> This is best demonstrated by a video in which I've slightly changed
> the code to always call setqflist(entries, 'r'), regardless of whether
> the diagnostics have changed. In between cursor holds, I am simply
> moving up and down the document with j and k:
>
> https://youtu.be/qi-tx2jNWBY
>
> As you can see the "active" window changes to the quickfix window and
> doesn't return to where the cursor is. However when I press j or k
> again the focus shifts back to the where I'm expecting it to be.
>

From the video I am not able to see the problem. Are you saying that
the cursor is moved to the first column in the line instead of the
correct column and when you press j or k, it is moved to the correct
column?

I tried to reproduce this problem using an CursorHold autocmd and
couldn't reproduce the screen refresh problem. In this test, the
cursor is restored to the correct position.

Regards,
Yegappan

>
> To Reproduce
>
> I don't have a minimal reproduction for this unfortunately.
>
> Expected behavior
>
> The "focus" not to flicker as shown above.
>
> Screenshots
>
> Video provided above.
>
> Environment (please complete the following information):
>
> Vim version
>
> VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 18 2019 02:24:21)
> Included patches: 1-1183
> Compiled by myitcv@myitcv
> Huge version with GTK2 GUI.  Features included (+) or not (-):
> +acl               +extra_search      +mouse_netterm     -tag_old_static
> +arabic            -farsi             +mouse_sgr         -tag_any_white
> +autocmd           +file_in_path      -mouse_sysmouse    -tcl
> +autochdir         +find_in_path      +mouse_urxvt       +termguicolors
> -autoservername    +float             +mouse_xterm       +terminal
> +balloon_eval      +folding           +multi_byte        +terminfo
> +balloon_eval_term -footer            +multi_lang        +termresponse
> +browse            +fork()            -mzscheme          +textobjects
> ++builtin_terms    +gettext           -netbeans_intg     +textprop
> +byte_offset       -hangul_input      +num64             +timers
> +channel           +iconv             +packages          +title
> +cindent           +insert_expand     +path_extra        +toolbar
> +clientserver      +job               -perl              +user_commands
> +clipboard         +jumplist          +persistent_undo   +vartabs
> +cmdline_compl     +keymap            +postscript        +vertsplit
> +cmdline_hist      +lambda            +printer           +virtualedit
> +cmdline_info      +langmap           +profile           +visual
> +comments          +libcall           +python            +visualextra
> +conceal           +linebreak         -python3           +viminfo
> +cryptv            +lispindent        +quickfix          +vreplace
> +cscope            +listcmds          +reltime           +wildignore
> +cursorbind        +localmap          +rightleft         +wildmenu
> +cursorshape       +lua               -ruby              +windows
> +dialog_con_gui    +menu              +scrollbind        +writebackup
> +diff              +mksession         +signs             +X11
> +digraphs          +modify_fname      +smartindent       -xfontset
> +dnd               +mouse             +startuptime       +xim
> -ebcdic            +mouseshape        +statusline        +xpm
> +emacs_tags        +mouse_dec         -sun_workshop      +xsmp_interact
> +eval              -mouse_gpm         +syntax            +xterm_clipboard
> +ex_extra          -mouse_jsbterm     +tag_binary        -xterm_save
>    system vimrc file: "$VIM/vimrc"
>      user vimrc file: "$HOME/.vimrc"
>  2nd user vimrc file: "~/.vim/vimrc"
>       user exrc file: "$HOME/.exrc"
>   system gvimrc file: "$VIM/gvimrc"
>     user gvimrc file: "$HOME/.gvimrc"
> 2nd user gvimrc file: "~/.vim/gvimrc"
>        defaults file: "$VIMRUNTIME/defaults.vim"
>     system menu file: "$VIMRUNTIME/menu.vim"
>   fall-back for $VIM: "/home/myitcv/usr/vim/share/vim"
> Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16   -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
> Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl   -ldl  -L/usr/lib/x86_64-linux-gnu -lluajit-5.1  -L/home/myitcv/.pythons/2.7.15/lib/python2.7/config -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic
>
> OS: Ubuntu 18.04.2 LTS
> Terminal: XTerm(330)
>
> Additional context
>
> n/a
>

**Comment by myitcv** [comment]
Thanks for the comprehensive response @vim-ml 

> From the video I am not able to see the problem

What's a little hard to see in the video I agree is the green "highlight" that shows in the status line for each window. You will notice that after a slight pause after each movement (i.e. when `CursorHold` triggers), the green "focus" moves to the quickfix window, despite the cursor focus remaining in the top window. 

So, the cursor position remains correct, but there is a "flicker" as the focussed window (and I'm using https://github.com/vim-airline/vim-airline) changes.

I think this behaviour is also the root cause of https://github.com/myitcv/govim/issues/152

But as I said before I don't know how to precisely describe what's happening here, because unfortunately I don't know exactly what is "wrong"

Hopefully that help to explain what I was trying to show in the video at least? Please let me know if not.

**Comment by myitcv** [comment]
@bling, @chrisbra - given I'm seeing this in vim-airline (by which I mean I'm not sure I would have picked up the issue had vim-airline's colouring not shown me the change in "focus"), do you have any thoughts?

**Comment by chrisbra** [comment]
I have troubles understanding the video. I see that the coloring changes (which indicates that the current window changes). But I guess the cursor does not actually move to the quickfix window? does it change anything, if you use `noa call setqflist()` to suppress any autocommand to interfer? Also might be, that vim-airline is missing the `nested` flag for an autocommand somewhere.

**Comment by myitcv** [comment]
> I see that the coloring changes (which indicates that the current window changes)

Correct.

> But I guess the cursor does not actually move to the quickfix window

Correct.

> does it change anything, if you use noa call setqflist() to suppress any autocommand to interfer

I'll give that a try, thanks.

**Comment by myitcv** [comment]
@chrisbra 

> does it change anything, if you use noa call setqflist() to suppress any autocommand to interfer

This indeed fixes the issue. Does this point to an issue in Vim, my code, or vim-airline?

**Comment by chrisbra** [comment]
good question :)
probably neither you are just telling Vim your intent to not run any autocommands when running the `setqflist()` function, which will skip an event to trigger a redraw for the statusline (vim-airline). However, if you rely on a quickfix autocommand like `QuickFixCmdPost` it probably won't work.

**Comment by myitcv** [comment]
> if you rely on a quickfix autocommand like QuickFixCmdPost it probably won't work

I am not, but I guess others (using `govim`) might be (via other plugins).

So sounds like it's worth closing this issue here, and raising another one over in vim-airline?

**Comment by chrisbra** [comment]
`vim-airline`

you can do that. Please provide a reproducible example so I can check which autocommand triggers it. But not sure if I am able to help or fix it.

**Comment by myitcv** [comment]
https://github.com/vim-airline/vim-airline/issues/1914

> But not sure if I am able to help or fix it.

Quite understand. Thanks very much for helping to dig into this thus far.

**Comment by chrisbra** [comment]
Copying here for reference:

Hm, I see the problem. vim-airline installs an `FileType` autocommand to update the statusline on FileType autocommands. This is necessary because the default `qf` filetype plugin distributed with Vim simply overwrites the `statusline` setting for the quickfix window (so airline has to work-around it using the FileType autocommand). So when calling `setqflist()` Vim will trigger an `FileType` autocommand, that loads $VIMRUNTIME/ftplugin/qf.vim and sets the `statusline` option. Later the vim-airline autocommand runs and overwrites the statusline to the default airline appearance, however it behaves as if it is the actual current focus window. That's why you see the focused appearance of the airline statusline on the non-current quickfix window. But now there is no corresponding autocommand called, that tells vim-airline, that we are back to the original Window. So the acutal current window stays in `unfocussed mode`. 

I think best would be, if the global `qf` filetype plugin checks whether the local statusline option has been set by a different plugin, and only if not, set the statusline option. 

Ping @llorens who seems to be the ftplugin maintainer of the quickfix filetype.
