### ISSUE TITLE
"*.gradle" should be recognized as ft=groovy

### ISSUE THREAD

**Issue by justinmk** [vim/vim#428]
Gradle `build.gradle` files are written in groovy, so they should be detected as `ft=groovy`.

``` diff

index 4d8b7d8..3ec4a74 100644
--- a/runtime/filetype.vim
+++ b/runtime/filetype.vim
@@ -826,7 +826,7 @@ au BufNewFile,BufRead *.gs           setf grads
 au BufNewFile,BufRead *.gretl           setf gretl

 " Groovy
-au BufNewFile,BufRead *.groovy          setf groovy
+au BufNewFile,BufRead *.gradle,*.groovy     setf groovy

 " GNU Server Pages
 au BufNewFile,BufRead *.gsp         setf gsp

```

**Comment by brammool** [comment]
Justin M. Keyes wrote:

Gradle `build.gradle` files are written in groovy, so they should be detected as `ft=groovy`.

``` diff

index 4d8b7d8..3ec4a74 100644
--- a/runtime/filetype.vim
+++ b/runtime/filetype.vim
@@ -826,7 +826,7 @@ au BufNewFile,BufRead *.gs           setf grads
 au BufNewFile,BufRead *.gretl           setf gretl

 " Groovy
-au BufNewFile,BufRead *.groovy          setf groovy
+au BufNewFile,BufRead *.gradle,*.groovy     setf groovy

 " GNU Server Pages
 au BufNewFile,BufRead *.gsp         setf gsp

```

Thanks, I'll include it.

## 

You have heard the saying that if you put a thousand monkeys in a room with a
thousand typewriters and waited long enough, eventually you would have a room
full of dead monkeys.
                (Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///
