### ISSUE TITLE
Is it a possibility to omit dictionary source file in dictionary completion

### ISSUE THREAD

**Issue by asepsiswu** [vim/vim#4281]
\<C-X>\<C-K>  complete words with long dictionary file name, such as /home/xxx/.vim/mydict.
I'd like to omit or shorten the descriptive info.
I have googled but got no hints.
Any advice?

**Comment by chrisbra** [comment]
I don't think this is possible. 
Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. Closing.
