### ISSUE TITLE
xml file syntax error

### ISSUE THREAD

**Issue by guido99** [vim/vim#4284]
In xml files, errors are shown inside comment tags,  . Everything inside the tags should be highlighted as set by hi colors assignments.

Example from my openbox menu.xml

`   <!-- <item label="bank"><action name="Execute"><command>emacs -g 42x20 -execute '(menu-bar-mode 0)' -execute '(tool-bar-mode 0)' --execute '(scroll-bar-mode 0)' +999 /home/me/me/money/PTHOA/bank</command></action></item> --> `

The third execute with preceding -- starts errors; -execute is ok.

**Comment by chrisbra** [comment]
Those strings are marked as `xmlCommentError`

https://github.com/vim/vim/blob/eead75c5e8e1f965548c55ee3a9388b2cb3afc36/runtime/syntax/xml.vim#L238

So, I looked up the specification:
https://www.w3.org/TR/REC-xml/#sec-comments

> [Definition: Comments may appear anywhere in a document outside other markup; in addition, they may appear within the document type declaration at places allowed by the grammar. They are not part of the document's character data; an XML processor MAY, but need not, make it possible for an application to retrieve the text of comments. For compatibility, the string " -- " (double-hyphen) MUST NOT occur within comments.]
