### ISSUE TITLE
Qt interface

### ISSUE THREAD

**Issue by Fale** [vim/vim#429]
Gvim is pretty ugly and not integrated in a Qt Desktop Environment (ie: KDE, LxQt). Please do create a Qt  version.

**Comment by chrisbra** [comment]
That is very unlikely to happen anytime soon, unless someone dedicates a lot of effort into this and actively works on this.

**Comment by jamessan** [comment]
See [vim-qt](https://bitbucket.org/equalsraf/vim-qt/overview).
