### ISSUE TITLE
Uncaught events yield vacuous "No matching autocommands" warning

### ISSUE THREAD

**Issue by mhinz** [vim/vim#4300]
vim -u NONE +'doau VimLeave'

"No matching autocommands".

https://github.com/vim/vim/blob/725310d89e1ba268bf410472b7de054c6c260161/src/autocmd.c#L1317-L1318

Most Vim beginners are heavily confused by that message. I helped a lot of them over the years and this is a common source of confusion.

It often happens because of plugins that don't wrap their `doautocmd User` in `if exists('#User#...')` or at least use `silent doautocmd`.

In the current form the message is mostly useless, because it doesn't even mention the actual event.

Potential improvements:

- Improve the message to mention the actual event and maybe even the calling file.
- Only echo the message when verbosity is at least 9.
- Both of the above.

**Comment by chrisbra** [comment]
relevant discussion on vim_dev: https://groups.google.com/d/msg/vim_dev/RTbq58TMq9w/Xr4rSoUTCgAJ

**Comment by g0xA52A2A** [comment]
> It often happens because of plugins that don't wrap their doautocmd User in if exists('#User#...') or at least use silent doautocmd.

I just had issues because of exactly this in testing a plugin I was writing in a stand alone config.

Because it had been a while since I'd dealt with this and forgotten `exist()` was the way to handle it I was attempting to use `try`. Which interestingly failed as it doesn't appear that using `doautocmd` for an `augorup` without any associated events is an error. As such it appears this message is purely informational. This may lead some to naively do something like `silent doautocmd ...` which will have knock-on effects, namely if you trigger an `autocmd` that would normally echo something, it too is silenced.

Personally I think this message should be made an actual error. As mentioned in the initial comment plugins should be taking care to handle this already so it shouldn't break anything well behaved. And I imagine most people writing Vim script would not then incorrectly reach for `silent`.

What do people thing of adding the suggestion to use `exist()` in the documentation? If this scenario was made an error it could be mention in the associated E number, otherwise a mention in `:help :doautocmd`.

FWIW I am also in agreement that information about the callee in the message would be useful in any case.

**Comment by g0xA52A2A** [comment]
I've stumbled across an issue with the `exists()` check method today. It will only match literal patterns, so if an `autocmd` pattern is defined as a regex and `exists()` is passed an `autocmd` pattern that would match said pattern it actually returns zero. I don't think `exists()` should handle regex. Given this issue has been open for a while and hasn't garnered much interest perhaps the "No matching autocommands" message should simply be deleted?

**Comment by chrisbra** [comment]
So how something like the following patch:

```patch
diff --git a/src/autocmd.c b/src/autocmd.c
index 4c12e729e..e6ef2cc32 100644
--- a/src/autocmd.c
+++ b/src/autocmd.c
@@ -1283,6 +1283,7 @@ do_doautocmd(
     char_u     *fname;
     int                nothing_done = TRUE;
     int                group;
+    event_T     event = NUM_EVENTS;

     if (did_something != NULL)
        *did_something = FALSE;
@@ -1314,12 +1315,26 @@ do_doautocmd(
      * Loop over the events.
      */
     while (*arg && !ends_excmd(*arg) && !VIM_ISWHITE(*arg))
-       if (apply_autocmds_group(event_name2nr(arg, &arg),
-                                     fname, NULL, TRUE, group, curbuf, NULL))
-           nothing_done = FALSE;
+       event = event_name2nr(arg, &arg);
+
+    if (event < NUM_EVENTS)
+    {
+       if (apply_autocmds_group(event, fname, NULL, TRUE, group, curbuf, NULL))
+               nothing_done = FALSE;
+
+       if (nothing_done && do_msg && p_verbose > 9)
+       {
+           msg(_("No matching autocommands: "));
+           if (group > AUGROUP_DEFAULT && AUGROUP_NAME(group) != NULL)
+           {
+               msg_puts(_("group="));
+               msg_puts((char *)AUGROUP_NAME(group));
+               msg_puts(" ");
+           }
+           msg_puts((char *)event_nr2name(event));
+       }
+    }

-    if (nothing_done && do_msg)
-       msg(_("No matching autocommands"));
     if (did_something != NULL)
        *did_something = !nothing_done;

diff --git a/src/testdir/test_autocmd.vim b/src/testdir/test_autocmd.vim
index 8abf911fa..e2be2cbf4 100644
--- a/src/testdir/test_autocmd.vim
+++ b/src/testdir/test_autocmd.vim
@@ -2810,5 +2810,35 @@ func Test_autocmd_vimgrep()
   augroup END
 endfunc

+func Test_doaucmd_msg()
+  let verbose=&verbose
+  let a=''
+  let a=execute('doau VimLeave', '')
+  call assert_equal("", a)
+  let a=''
+  let a=execute('doau \|', '')
+  call assert_equal("", a)
+  augroup foobar
+  augroup END
+  let a=''
+  let a=execute('doau foobar VimLeave', '')
+  call assert_equal("", a)
+
+
+  set verbose=10
+  let a=''
+  let a=execute('doau VimLeave', '')
+  call assert_match("No matching autocommands: VimLeave", a)
+  let a=''
+  let a=execute('doau \|', '')
+  call assert_equal("", a)
+  let a=''
+  let a=execute('doau foobar VimLeave', '')
+  call assert_match("No matching autocommands: group=foobar VimLeave", a)
+
+  " restore
+  let &verbose=verbose
+  augroup! foobar
+endfunc

 " vim: shiftwidth=2 sts=2 expandtab
```

**Comment by brammool** [comment]
George Brown wrote:

> I've stumbled across an issue with the `exists()` check method today.
> It will only match literal patterns, so if an `autocmd` pattern is
> defined as a regex and `exists()` is passed an `autocmd` pattern that
> would match said pattern it actually returns zero. I don't think
> `exists()` should handle regex. Given this issue has been open for a
> while and hasn't garnered much interest perhaps the "No matching
> autocommands" message should simply be deleted?  

When typing ":doautocmd" manually the message is very useful, you know
nothing happened.

When doing this from a plugin you might not care about whether there are
matching commands and the message gets in the way.

What we could do:
- Use ":silent".  Mostly works, but could also hide other messages.

- Use ":doau!".  Could work, although exclamation mark usually means
		  "forced", which does not apply here.

- Use ":doau <silent>"  Probably works best.  It's longer, but in a
			  plugin that doesn't matter.

-- 
hundred-and-one symptoms of being an internet addict:
96. On Super Bowl Sunday, you followed the score by going to the
    Yahoo main page instead of turning on the TV.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by g0xA52A2A** [comment]
> So how something like the following patch:

That seems to work as @mhinz  original suggestion intends, though the
patch as-is did not apply cleanly for me.
