### ISSUE TITLE
Wonky mouse in rxvt-unicode after vim upgrade (regression)

### ISSUE THREAD

**Issue by draconx** [vim/vim#4301]
Hi,

After recently updating vim the mouse is all messed up for me on rxvt-unicode, causing really large amounts of unwanted scrolling when selecting text while holding shift.

To reproduce, create a file large enough to scroll (/tmp/spew in example), then:

    % yes | head -n1000 >/tmp/spew
    % vim -N -u NONE /tmp/spew
    :set mouse=a

Then scroll to the end, hold shift, and click+drag anywhere in an attempt to select some text in the terminal.  While dragging, the screen scrolls up (and only up) whenever the mouse is moving, moving very quickly to the top of the file.  This makes it essentially impossible to select any text with this method, unless it can be selected with the file scrolled all the way to the beginning.

Bisection implicates this patch as causing the problem:

    1f8495cf48888ff3a8ab3d0eb22db92389191a60 is the first bad commit
    commit 1f8495cf48888ff3a8ab3d0eb22db92389191a60
    Author: Bram Moolenaar <Bram@vim.org>
    Date:   Wed Apr 4 21:53:11 2018 +0200
    
        patch 8.0.1659: scroll events not recognized for some xterm emulators
    
        Problem:    Scroll events not recognized for some xterm emulators.
        Solution:   Recognize mouse codes 0x40 and 0x41 as scroll events.

    :040000 040000 ec2d44f201a600e1019817bb2e93327769f056f7 0d8eeeeb0adb90479c070e597251729abc96be64 M	src

and reverting this patch on master corrects the behaviour.

**Comment by draconx** [comment]
note: this problem does not happen with ttymouse=xterm, which appears to be the default unless vim is run with :set nocompatible or the -N option as in the above example, which in my case sets ttymouse=xterm2.

**Comment by brammool** [comment]
so, what is 'term' set to?  What is the output of ":set termcap"?

This works fine nearly everywhere.
The problem might be with rxvt or with wrong settings.

**Comment by draconx** [comment]
Ah, I see in rxvt-unicode changelog, the latest version has

- do not report mouse motion events if Shift is active (patch by Daniel Hahler).

And sure enough with rxvt-unicode 9.22 it seems the issue does not occur.  Maybe there is nothing to fix in vim then, although prior versions of vim did not exhibit any problem on rxvt-unicode 9.21 in this regard.

Regardless, to answer your questions...

TERM=rxvt-unicode-256color

    :set termcap                                                                                                             
    --- Terminal codes ---
      t_AL=^[[%p1%dL      t_Cs=               t_IS=^[]1;          t_RF=^[]10;?^G      t_SI=               t_ue=^[[m
      t_al=^[[L           t_CV=               t_ke=^[[?1l^[>      t_RB=^[]11;?^G      t_Si=^[[22;1t       t_us=^[[4m
      t_bc=               t_da=               t_ks=^[[?1h^[=      t_RC=^[[?12$p       t_so=^[[7m          t_ut=y
      t_BE=^[[?2004h      t_db=               t_le=^H             t_RI=^[[%p1%dC      t_SR=               t_ve=^[[?25h
      t_BD=^[[?2004l      t_DL=^[[%p1%dM      t_mb=^[[5m          t_Ri=^[[23;1t       t_sr=^[M            t_vi=^[[?25l
      t_cd=^[[J           t_dl=^[[M           t_md=^[[1m          t_RS=^[P$q q^[\     t_ST=^[[22;2t       t_VS=^[[?12l
      t_ce=^[[K           t_EC=^G             t_me=^[[m           t_RT=^[[23;2t       t_Te=^[[29m         t_vs=^[[?12h
      t_cl=^[[H^[[2J      t_EI=               t_mr=^[[7m          t_RV=^[[>c          t_ti=^[[?1049h      t_xn=y
      t_Ce=               t_fs=^G             t_ms=y              t_SC=^[]12;         t_Ts=^[[9m          t_xs=
      t_Co=256            t_GP=^[[13t         t_nd=^[[C           t_se=^[[27m         t_ts=^[]2;          t_ZH=^[[3m
      t_CS=               t_IE=^G             t_op=^[[39;49m      t_SH=^[[%p1%d q     t_u7=^[[6n          t_ZR=^[[23m
      t_AB=^[[48;5;%p1%dm
      t_AF=^[[38;5;%p1%dm
      t_cm=^[[%i%p1%d;%p2%dH
      t_cs=^[[%i%p1%d;%p2%dr
      t_Sb=%?%p1%{7}%>%t^[[48;5;%p1%dm%e^[[4%?%p1%{1}%=%t4%e%p1%{3}%=%t6%e%p1%{4}%=%t1%e%p1%{6}%=%t3%e%p1%d%;m%;
      t_Sf=%?%p1%{7}%>%t^[[38;5;%p1%dm%e^[[3%?%p1%{1}%=%t4%e%p1%{3}%=%t6%e%p1%{4}%=%t1%e%p1%{6}%=%t3%e%p1%d%;m%;
      t_te=^[[r^[[?1049l
      t_vb=^[[?5h$<20/>^[[?5l
      t_WP=^[[3;%p1%d;%p2%dt
      t_WS=^[[8;%p1%d;%p2%dt
      t_8f=^[[38;2;%lu;%lu;%lum
      t_8b=^[[48;2;%lu;%lu;%lum
    --- Terminal keys ---
    t_#2 <S-Home>    ^[[7$     t_K7 <kMinus>    ^[O*m     t_KL <k9>        ^[O*y     t_kD <Del>       ^[[3~          <xF4>       ^[O*S
    t_#4 <S-Left>    ^[[d      t_K8 <kDivide>   ^[O*o     t_PE <PasteEnd>  ^[[201~   t_kI <Insert>    ^[[2;*~        <xEnd>      ^[O*F
    t_%1 <Help>      ^[[28;*~  t_K9 <kMultiply> ^[O*j     t_PS <PasteStart> ^[[200~  t_kN <PageDown>  ^[[6;*~        <zEnd>      ^[[8;*~
    t_%i <S-Right>   ^[[c      t_KA <kEnter>    ^[O*M     t_k1 <F1>        ^[[11;*~  t_kP <PageUp>    ^[[5;*~        <xHome>     ^[O*H
    t_&8 <Undo>      ^[[26;*~  t_KB <kPoint>    ^[O*n     t_k2 <F2>        ^[[12;*~  t_kb <BS>        ^?             <zHome>     ^[[7;*~
    t_*7 <S-End>     ^[[8$     t_KC <k0>        ^[O*p     t_k3 <F3>        ^[[13;*~  t_kd <Down>      ^[O*B          <xUp>       ^[[1;*A
    t_@7 <End>       ^[[1;*F   t_KD <k1>        ^[O*q     t_k4 <F4>        ^[[14;*~  t_kh <Home>      ^[[1;*H        <xDown>     ^[[1;*B
    t_F1 <F11>       ^[[23;*~  t_KE <k2>        ^[O*r     t_k5 <F5>        ^[[15;*~  t_kl <Left>      ^[O*D          <xLeft>     ^[[1;*D
    t_F2 <F12>       ^[[24;*~  t_KF <k3>        ^[O*s     t_k6 <F6>        ^[[17;*~  t_kr <Right>     ^[O*C          <xRight>    ^[[1;*C
    t_K1 <kHome>     ^[[1;*~   t_KG <k4>        ^[O*t     t_k7 <F7>        ^[[18;*~  t_ku <Up>        ^[O*A          <kDel>      ^[[3;*~
    t_K3 <kPageUp>   ^[Oy      t_KH <k5>        ^[O*u     t_k8 <F8>        ^[[19;*~       <Mouse>     ^[[M
    t_K4 <kEnd>      ^[[4;*~   t_KI <k6>        ^[O*v     t_k9 <F9>        ^[[20;*~       <xF1>       ^[O*P
    t_K5 <kPageDown> ^[Os      t_KJ <k7>        ^[O*w     t_k; <F10>       ^[[21;*~       <xF2>       ^[O*Q
    t_K6 <kPlus>     ^[O*k     t_KK <k8>        ^[O*x     t_kB <S-Tab>     ^[[Z           <xF3>       ^[O*R

**Comment by chrisbra** [comment]
so this can be closed, right?
