### ISSUE TITLE
Indent test files not deleted by `make clean`

### ISSUE THREAD

**Issue by chdiza** [vim/vim#4307]
**Describe the bug**
Doing `make clean` after a `make test` should (and historically has, AFAICT) cleaned up all the test-file debris.  But lately there is new test debris, specifically from the testing of indent files.  At least some of these aren't cleaned up by `make clean`:
```
runtime/indent/testdir/html.out
runtime/indent/testdir/matlab.out
runtime/indent/testdir/tcl.out
runtime/indent/testdir/vim.out
runtime/indent/testdir/xml.out
```

**To Reproduce**
CD into the source repo.  Do `./configure [your flags] && make && make test`.  Then do `make clean`.  Then do `git clean -ndfx`.  Observe the aforementioned files hanging around.  If you do that same sequence of steps but without the `make clean`, you will see all of the other tons of test files that `make clean` does wipe out.

**Environment (please complete the following information):**
 This is on Vim 8.1.1205, on macOS 10.14.4, in iTerm2.app.

**Comment by chrisbra** [comment]
Are you sure that a simple `make && make test` will create those files? IIRC, they are only created if you enter `runtime/indent` directory and run make test there and they will be deleted if you run `make clean` in that directory.

**Comment by brammool** [comment]
Christian is right.

**Comment by chdiza** [comment]
> Are you sure that a simple make && make test will create those files?

Yes.  I just did it again.

> IIRC, they are only created if you enter runtime/indent directory

This is not true; I just tried it again.

> they will be deleted if you run make clean in that directory.

*That* might be true, but the base-dir `make clean` should handle them too.

**Comment by chdiza** [comment]
I don't know why it would make a difference, but my configuration flags are:
```
    --disable-gui
    --without-x
    --disable-netbeans
    --disable-nls
```

**Comment by brammool** [comment]
> > Are you sure that a simple make && make test will create those files?
> 
> Yes.  I just did it again.

You forgot to mention you do this in the top directory, not in "src".
That confused us.

> > IIRC, they are only created if you enter runtime/indent directory
> 
> This is not true; I just tried it again.
> 
> > they will be deleted if you run make clean in that directory.
> 
> *That* might be true, but the base-dir `make clean` should handle them too.

I'll have "make clean" in the top directory also clean the indent test
output.

-- 
    [clop clop]
MORTICIAN:  Who's that then?
CUSTOMER:   I don't know.
MORTICIAN:  Must be a king.
CUSTOMER:   Why?
MORTICIAN:  He hasn't got shit all over him.
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
Oh, it did not happen for me, just tried that again: https://gist.githubusercontent.com/chrisbra/0c5984d7ebddc94a07e7acc322c7a567/raw/8f0323ba1a99fa2fda3a4a45c8c326cb56a81552/vim_build_log_8.1.1212.log

However, I see 3 files surviving the clean:
`src/po/LINGUAS`, `src/po/gvim.desktop` and `src/po/vim.desktop`.

**Comment by chrisbra** [comment]
I think we also need this in addition:

```patch
diff --git a/Makefile b/Makefile
index 6ee3b1cdd..e9afdc340 100644
--- a/Makefile
+++ b/Makefile
@@ -47,6 +47,8 @@ all install uninstall tools config configure reconfig proto depend lint tags typ
        @if test "$@" = "clean" -o "$@" = "distclean" -o "$@" = "testclean"; then \
                cd runtime/indent && \
                        $(MAKE) clean; \
+               cd ../../src/po && \
+                       $(MAKE) clean; \
        fi

 # Executable used for running the indent tests.
diff --git a/src/po/Makefile b/src/po/Makefile
index 8383a1207..f5002a4ec 100644
--- a/src/po/Makefile
+++ b/src/po/Makefile
@@ -150,7 +150,7 @@ prefixcheck:
        fi

 clean: checkclean
-       rm -f core core.* *.old.po *.mo *.pot sjiscorr
+       rm -f core core.* *.old.po *.mo *.pot sjiscorr LINGUAS *.desktop

 distclean: clean
```

**Comment by brammool** [comment]
Christian wrote:

> I think we also need this in addition:
> 
> ```patch
> diff --git a/Makefile b/Makefile
> index 6ee3b1cdd..e9afdc340 100644
> --- a/Makefile
> +++ b/Makefile
> @@ -47,6 +47,8 @@ all install uninstall tools config configure reconfig proto depend lint tags typ
>         @if test "$@" = "clean" -o "$@" = "distclean" -o "$@" = "testclean"; then \
>                 cd runtime/indent && \
>                         $(MAKE) clean; \
> +               cd ../../src/po && \
> +                       $(MAKE) clean; \
>         fi

That should not be needed, since "make clean" is run in "src", which in
turn cleans "src/po".

>  # Executable used for running the indent tests.
> diff --git a/src/po/Makefile b/src/po/Makefile
> index 8383a1207..f5002a4ec 100644
> --- a/src/po/Makefile
> +++ b/src/po/Makefile
> @@ -150,7 +150,7 @@ prefixcheck:
>         fi
> 
>  clean: checkclean
> -       rm -f core core.* *.old.po *.mo *.pot sjiscorr
> +       rm -f core core.* *.old.po *.mo *.pot sjiscorr LINGUAS *.desktop
> 
>  distclean: clean
> ```

Thanks.

-- 
ARTHUR:  I did say sorry about the `old woman,' but from the behind you
         looked--
DENNIS:  What I object to is you automatically treat me like an inferior!
ARTHUR:  Well, I AM king...
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
