### ISSUE TITLE
Duplicate entries in desktop files

### ISSUE THREAD

**Issue by rakus** [vim/vim#4313]
The files `runtime/vim.desktop` and `runtime/gvim.desktop` contains duplicate entries for german `GenericName` and `Comment`.
```
$ desktop-file-validate runtime/*.desktop
runtime/gvim.desktop: error: file contains multiple keys named "GenericName[de]" in group "Desktop Entry"
runtime/gvim.desktop: error: file contains multiple keys named "Comment[de]" in group "Desktop Entry"
runtime/vim.desktop: error: file contains multiple keys named "GenericName[de]" in group "Desktop Entry"
runtime/vim.desktop: error: file contains multiple keys named "Comment[de]" in group "Desktop Entry"
```
The same is true for `./src/po/*.desktop` after build.

I guess this is irrelevant for normal operations, especially as the values are identical. 

Creating a AppImage with a newer AppImageKit validates the desktop file and fails because of this. Fixed by cleaning up the desktop files before feeding to AppImageKit.

**Comment by brammool** [comment]
> The files `runtime/vim.desktop` and `runtime/gvim.desktop` contains duplicate entries for german `GenericName` and `Comment`.
> ```
> $ desktop-file-validate runtime/*.desktop
> runtime/gvim.desktop: error: file contains multiple keys named "GenericName[de]" in group "Desktop Entry"
> runtime/gvim.desktop: error: file contains multiple keys named "Comment[de]" in group "Desktop Entry"
> runtime/vim.desktop: error: file contains multiple keys named "GenericName[de]" in group "Desktop Entry"
> runtime/vim.desktop: error: file contains multiple keys named "Comment[de]" in group "Desktop Entry"
> ```
> The same is true for `./src/po/*.desktop` after build.
> 
> I guess this is irrelevant for normal operations, especially as the values are identical. 
> 
> Creating a AppImage with a newer AppImageKit validates the desktop file and fails because of this. Fixed by cleaning up the desktop files before feeding to AppImageKit.

I suppose we can remove the line from the .in file as soon as the
translation is in the .po file.

-- 
A poem:                read aloud:

<> !*''#               Waka waka bang splat tick tick hash,
^"`$$-                 Caret quote back-tick dollar dollar dash,
!*=@$_                 Bang splat equal at dollar under-score,
%*<> ~#4               Percent splat waka waka tilde number four,
&[]../                 Ampersand bracket bracket dot dot slash,
|{,,SYSTEM HALTED      Vertical-bar curly-bracket comma comma CRASH.

Fred Bremmer and Steve Kroese (Calvin College & Seminary of Grand Rapids, MI.)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
> I suppose we can remove the line from the .in file as soon as the translation is in the .po file.

Can this be done automatically in the Makescript (some fancy vim script that filters duplicate entries)?
