### ISSUE TITLE
didn' t quit alternate screen on recieve SIGTSTP send with kill

### ISSUE THREAD

**Issue by jakio6** [vim/vim#4315]
**Describe the bug**
Didn't quit alternate screen on recive SIGTSTP send  with kill

**To Reproduce**
1. Run `vim --clean`
2. Run `kill -SIGTSTP pid-of-vim`
3. vim did't quit alternate screen,there 's a mess

**Expected behavior**
exit alternate screen when recieve SIGTSTP send with kill

**Screenshots**
![e](https://user-images.githubusercontent.com/33382676/56866100-32701680-6a08-11e9-9a19-9e605e1544bf.png)

**Environment :**
- vim version : 8.1.1073
- OS : Linux version 5.0.7-rt5-MANJARO
- Terminal : gnome-terminal

**Additional context**
none

**Comment by brammool** [comment]
This is infeasible.  Quoting the signal(2) manpage:      The signals SIGKILL and SIGSTOP cannot be caught or ignored.

**Comment by jakio6** [comment]
but this is caused by SIGTSTP, not SIGKILL or SIGSTOP

**Comment by brammool** [comment]
Hmm, perhaps we can catch it and call settmode(TMODE_COOK);
Must make sure this doesn't happen when in mch_suspend().

**Comment by dbivolaru** [comment]
This seems to still be an issue in vim 8.2.3755-1.fc35

Because SIGTSTP can also be ignored, the easiest would be to just handle a SIGTSTP identically to a ^Z.

**Comment by lacygoill** [comment]
Fixed by patch [8.2.3941](https://github.com/vim/vim/releases/tag/v8.2.3941)
