### ISSUE TITLE
bottom lines of previous tab page remain in the next one

### ISSUE THREAD

**Issue by rickhowe** [vim/vim#4321]
If a value of cmdheight option is different between tab pages,
when moving to the tab page where cmdheight has higher value,
bottom lines of previous tab page remain until refreshing or using command line.

This happens in latest vim 8.1.1240, but not in an official vim 8.1.

**Comment by tonymec** [comment]
According to the help, 'cmdheight' is global. However, `:tabnew` followed by `setlocal ch=3` changes it only for the new tab; but by going back to the previous tab and returning to the new tab, `setl ch?` answers `  cmdheight=3` but the actual height is 2 (as was set by my .vimrc and is set in the older tab). Even stranger: `:setg ch?` answers 3 in the new tab but 2 in the older tab; the actual height is 2 in both, and Ctrl-L doesn't change that. From that point on, the visible command-line height in the new tab is one less than the value the option is set to, even if I change the value.

There is something weird going on but I'm not sure exactly what.

I tested this on gvim 8.1.1240 with GTK2.

**Comment by vim-ml** [comment]
On Wed, May 1, 2019 at 1:16 PM Tony Mechelynck
<vim-dev-github@256bit.org> wrote:
>
> According to the help, 'cmdheight' is global. However, :tabnew followed by setlocal ch=3 changes it only for the new tab; but by going back to the previous tab and returning to the new tab, setl ch? answers cmdheight=3 but the actual height is 2 (as was set by my .vimrc and is set in the older tab). Even stranger: :setg ch? answers 3 in the new tab but 2 in the older tab; the actual height is 2 in both, and Ctrl-L doesn't change that. From that point on, the visible command-line height in the new tab is one less than the value the option is set to, even if I change the value.
>
> There is something weird going on but I'm not sure exactly what.
>
> I tested this on gvim 8.1.1240 with GTK2.

P.S. Closing the new tab when its displayed command-line is 1 goes
back to the older tab, but there the displayed height is now also
wrong: it is 1 but says 2. The only way I've found to go back to
"proper" functioning is to shut down and restart gvim.

Best regards,
Tony.
