### ISSUE TITLE
add -complete=colorscheme for complete with colorschemes

### ISSUE THREAD

**Issue by UncleBill** [vim/vim#4322]
as the title says.

**Is your feature request related something that is currently hard to do? Please describe.**
Not hard to do, here is my implement:
```viml
function! prism#Complete(arg_lead, cmd_line, cursor_pos)
	let colors = []
  for f in split(globpath(&rtp, "colors/*.vim"), "\n")
    let color = get(matchlist(f,'\([^\\\/]\+\)\.vim'), 1, '')
    if !empty(color)
      call add(colors, color)
    endif
  endfor

  let pos = len(a:arg_lead) - 1
  return filter(colors, {idx, val -> val[:pos] == a:arg_lead})
endfunction
```

**Describe the solution you'd like**
replate above function with `-complete=colorscheme`. I think it should be easy to reused existed code from vim's codebase.

**Comment by chdiza** [comment]
There is already `-complete=color`.  What is the point of this request?

**Comment by UncleBill** [comment]
> There is already -complete=color. What is the point of this request?

That's what I want. thanks!
