### ISSUE TITLE
error on opening compile vim with python support

### ISSUE THREAD

**Issue by itzmanish** [vim/vim#4327]
Getting error when executing vim command on bash.

`
vim: error while loading shared libraries: libtinfow.so.6: cannot open shared object file: No such file or directory
`

What i did -

```
sudo apt-get install libncurses5-dev libgnome2-dev libgnomeui-dev \
    libgtk2.0-dev libatk1.0-dev libbonoboui2-dev \
    libcairo2-dev libx11-dev libxpm-dev libxt-dev python-dev ruby-dev mercurial
```

Removed existing vim

```
sudo apt-get remove vim vim-runtime gvim vim-tiny vim-common vim-gui-common
```

```
hg clone https://code.google.com/p/vim/
cd vim
./configure --with-features=huge \
            --disable-darwin \
            --disable-selinux \
            --enable-luainterp \
            --enable-perlinterp \
            --enable-pythoninterp \
            --enable-python3interp \
            --enable-tclinterp \
            --enable-rubyinterp \
            --enable-cscope \
            --enable-multibyte \
            --enable-xim \
            --enable-fontset \
            --enable-gui=gnome2
make
sudo apt-get install checkinstall
sudo checkinstall
```

Using terminator and compiled using git repo of vim default branch.
I am using Bunsenlabs helium with backed by Debian Stretch.

**Comment by chrisbra** [comment]
did you really use ` https://code.google.com/p/vim/`? 

Also, can you please show the output of `ldd vim`, looks like you are missing the `libtinfo` library.

> I am using Bunsenlabs helium with backed by Debian Stretch.

Is that an operating system? You might try something like `apt-get build-dep vim-gtk3` (or similar) and see if this fixes things for you

**Comment by itzmanish** [comment]
> did you really use https://code.google.com/p/vim/?

No.

ldd vim - 

`
krishna@krishna:$ ldd vim`

`ldd: ./vim: No such file or directory
`

`krishna@krishna:$ vim`

`vim: error while loading shared libraries: libtinfow.so.6: cannot open shared object file: No such file or directory
krishna@krishna:$
`
>Is that an operating system? 

Yes it is. Bunsenlab helium is debian stretch os. 

> You might try something like apt-get build-dep vim-gtk3 (or similar) and see if this fixes things for you

`Reading package lists... Done`

`E: You must put some 'source' URIs in your sources.list
`

**Comment by k-takata** [comment]
> sudo apt-get remove vim vim-runtime gvim vim-tiny vim-common vim-gui-common

Removing system vim is not recommended. It might remove important libraries. libtinfow.so.6 might be removed by it.
If you want to install your own vim, you should install it to `/usr/local/bin` (which is the default). System vim is installed in `/usr/bin`, so they won't conflict.
Try installing system vim again:
`sudo apt-get install vim`

**Comment by tonymec** [comment]
> > sudo apt-get remove vim vim-runtime gvim vim-tiny vim-common vim-gui-common
> 
> Removing system vim is not recommended. It might remove important libraries. libtinfow.so.6 might be removed by it.
> If you want to install your own vim, you should install it to `/usr/local/bin` (which is the default). System vim is installed in `/usr/bin`, so they won't conflict.

Indeed. Not only they won't conflict, but since `/usr/local/bin` comes earlier in the $PATH than `/usr/bin`, invoking `vim` or `gvim` with no path will load your own Vim (once you have one). You can of course still load the OS's Vim by invoking it with a full path, i.e. as `/usr/bin/vim` or `/usr/bin/gvim`.

> Try installing system vim again:
> `sudo apt-get install vim`

Best regards,
Tony.

**Comment by chrisbra** [comment]
This looks like a system configuration issue and not a real Vim bug. 
Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. Closing.
