### ISSUE TITLE
PTY cannot read vim space/tab

### ISSUE THREAD

**Issue by xlpiao** [vim/vim#4331]
I have question about pty and vim in Linux.

When I write space or tab to pty, the write is successful. However, when I read pty, there's no space and tab. 

In order to figure it out, I use 'set cursorline' in vim, then I can get space and tab when I read pty. 

I want to know the reason about this. What exactly 'set cursorline' is doing in vim.

**Comment by brammool** [comment]
Please be specific: What do you mean with "write to pty"?  What command do you use?
Also what is the relation with Vim, why would this be a bug?
