### ISSUE TITLE
Allow combining of text property highlights and regular syntax hl

### ISSUE THREAD

**Issue by tsufeki** [vim/vim#4343]
**Is your feature request related something that is currently hard to do? Please describe.**
Currently highlights from text properties completely override regular syntax highlighting,
so it is hard/impossible to them in combination, with properties as an auxiliary source.

**Describe the solution you'd like**
Add option `'highlight_combine': v:true` to `prop_type_add()`, which will combine highlight attributes from syntax and text property when drawing.

Alternatively, always combine these attributes and require `'highlight_combine': v:false` to turn it off.

**Additional context**
I use a Language Server Protocol plugin and would like to have errors and warning underlined through textprops, but otherwise keep the syntax.

**Comment by brammool** [comment]
Good idea.
