### ISSUE TITLE
Can't compile Vim with MSVC 2017: Several errors in termscreen (or screen?)

### ISSUE THREAD

**Issue by dertuxmalwieder** [vim/vim#4345]
Using my [compilation script](https://tuxproject.de/projects/vim/_compile.bat.php), I have been unable to compile Vim - any of the six different binaries - for a few days now:

> termscreen.obj : error LNK2005: _vterm_screen_get_attrs_extent ist bereits in screen.obj definiert.
> termscreen.obj : error LNK2005: _vterm_screen_set_damage_merge ist bereits in screen.obj definiert.
> termscreen.obj : error LNK2005: _vterm_screen_flush_damage ist bereits in screen.obj definiert.
> termscreen.obj : error LNK2005: _vterm_screen_get_unrecognised_fbdata ist bereits in screen.obj definiert.
> termscreen.obj : error LNK2005: _vterm_screen_set_unrecognised_fallbacks ist bereits in screen.obj definiert.
> termscreen.obj : error LNK2005: _vterm_screen_get_cbdata ist bereits in screen.obj definiert.
> termscreen.obj : error LNK2005: _vterm_screen_set_callbacks ist bereits in screen.obj definiert.
> termscreen.obj : error LNK2005: _vterm_screen_enable_altscreen ist bereits in screen.obj definiert.
> termscreen.obj : error LNK2005: _vterm_obtain_screen ist bereits in screen.obj definiert.
> termscreen.obj : error LNK2005: _vterm_screen_is_eol ist bereits in screen.obj definiert.
> termscreen.obj : error LNK2005: _vterm_screen_get_cell ist bereits in screen.obj definiert.
> termscreen.obj : error LNK2005: _vterm_screen_get_text ist bereits in screen.obj definiert.
> termscreen.obj : error LNK2005: _vterm_screen_get_chars ist bereits in screen.obj definiert.
> termscreen.obj : error LNK2005: _vterm_screen_reset ist bereits in screen.obj definiert.
> termscreen.obj : error LNK2005: _vterm_screen_free ist bereits in screen.obj definiert.

Of course, that leads to a number of linker errors. I did an `nmake clean` before starting, so nothing *should* be dirty here. I don't know which flag causes the problem, but I'm positive that redefinitions should not occur. `screen.c` and `termscreen.c` are unchanged from the upstream repository.

**Comment by k-takata** [comment]
Isn't there another `screen.c` in `src/libvterm/src/` (or somewhere else)?

**Comment by chrisbra** [comment]
so what was the last version that compiled correctly? Could this have been caused by v8.1.1257?

**Comment by dertuxmalwieder** [comment]
> so what was the last version that compiled correctly?

The last one was 8.1.1229, so it should have happened within the few builds after that (I usually compile two or three times a week). Your assumption that 8.1.1257 could have caused it is not unlikely though.

@k-takata Yes, there is.

**Comment by k-takata** [comment]
Then, delete it.

**Comment by dertuxmalwieder** [comment]
Deleting it does not solve the problem, I get the same errors.

**Comment by k-takata** [comment]
I changed the build rules at 8.1.1230 to make the build faster.
It will build all files in `src/libvterm/src/`, so if you have an extra `screen.c`, it will be also built, and might cause the error.

Did you do make clean to delete the wrong `screen.obj`?

**Comment by dertuxmalwieder** [comment]
As stated above, I did an `nmake clean` before each step. Anyway, that might be the problem - my `ObjGXULYHTRZVAMD64` folder only contains `.obj` files without any further structures, so everything is mashed together:

> (...)\vim\vim\src\ObjGXULYHTRZVAMD64>dir /B
> arabic.obj
> autocmd.obj
> beval.obj
> blob.obj
> blowfish.obj
> buffer.obj
> channel.obj
> charset.obj
> crypt.obj
> crypt_zip.obj
> debugger.obj
> dict.obj
> diff.obj
> digraph.obj
> dimm_i.obj
> edit.obj
> encoding.obj
> eval.obj
> evalfunc.obj
> ex_cmds.obj
> ex_cmds2.obj
> ex_docmd.obj
> ex_eval.obj
> ex_getln.obj
> fileio.obj
> findfile.obj
> fold.obj
> getchar.obj
> glbl_ime.obj
> gui.obj
> gui_beval.obj
> gui_dwrite.obj
> gui_w32.obj
> hardcopy.obj
> hashtab.obj
> if_cscope.obj
> if_lua.obj
> if_mzsch.obj
> if_perl.obj
> if_perlsfio.obj
> if_python.obj
> if_python3.obj
> if_ruby.obj
> if_tcl.obj
> indent.obj
> insexpand.obj
> json.obj
> keyboard.obj
> list.obj
> main.obj
> mark.obj
> mbyte.obj
> memfile.obj
> memline.obj
> menu.obj
> message.obj
> misc1.obj
> misc2.obj
> mouse.obj
> move.obj
> netbeans.obj
> normal.obj
> ops.obj
> option.obj
> os_mswin.obj
> os_w32exe.obj
> os_win32.obj
> parser.obj
> pathdef.c
> pathdef.obj
> pen.obj
> popupmnu.obj
> quickfix.obj
> regexp.obj
> screen.obj
> search.obj
> sha256.obj
> sign.obj
> spell.obj
> spellfile.obj
> state.obj
> syntax.obj
> tag.obj
> term.obj
> terminal.obj
> termscreen.obj
> textprop.obj
> ui.obj
> undo.obj
> unicode.obj
> usercmd.obj
> userfunc.obj
> vc140.pdb
> version.obj
> vim.res
> vterm.obj
> winclip.obj
> window.obj
> xdiffi.obj
> xemit.obj
> xhistogram.obj
> xpatience.obj
> xpm_w32.obj
> xprepare.obj
> xutils.obj

As you can see, there's only one `screen.obj` for one build...

I have *not* passed the "VIMDLL" flag yet.

**Comment by dertuxmalwieder** [comment]
No changes with `VIMDLL=yes`.

**Comment by k-takata** [comment]
Please search `screen.c` under the `src` directory by `dir /s screen.c`, and if you found something other than `src/screen.c`, then delete them.

`VIMDLL=yes` won't help.

**Comment by dertuxmalwieder** [comment]
How mad at me would you be if I told you that this was the problem? It looks like I used `hg` wrong.

Indeed, *manually deleting* the output folders and *then* deleting the file `libvterm\screen.c` again (I honestly wonder how it got there) fixed the problem. Ouch!

Sorry for disturbing the general peace here. Thank you a ton!

**Comment by k-takata** [comment]
When you execute `nmake clean`, you must add the same option as you build. (At least, DEBUG or not, GUI or not or VIMDLL or not, OLE or not, and enable each interface or not.)
It is because the working directory depends on the above options and `clean` also depends on them.

**Comment by dertuxmalwieder** [comment]
I will change that in my script tomorrow. Thank you for the advice. :-)

**Comment by brammool** [comment]
> How mad at me would you be if I told you that this was the problem? It
> looks like I used `hg` wrong.
> 
> Indeed, *manually deleting* the output folders and *then* deleting the
> file `libvterm\screen.c` again (I honestly wonder how it got there)
> fixed the problem. Ouch!
> 
> Sorry for disturbing the general peace here. Thank you a ton!

At some point in the past the "screen.c" file was renamed "termscreen.c"
to avoid the collision of the object files.  You apparently still had
the old file there somehow.

-- 
Close your shells, or I'll kill -9 you
Tomorrow I'll quota you
Remember the disks'll always be full
And then while I'm away
I'll write ~ everyday
And I'll send-pr all my buggings to you.
    [ CVS log "Beatles style" for FreeBSD ports/INDEX, Satoshi Asami ]

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
@dertuxmalwieder I saw your latest build: https://tuxproject.de/projects/vim/
It seems that you tried to share the code between gvim with and without OLE using VIMDLL, however, it's not possible. gvim_noOLE.exe will also try to register itself if it is not registered. (But it will fail because the type library is missing, though.)
VIMDLL can share the code only between gvim and vim.

**Comment by dertuxmalwieder** [comment]
Yup, this was a (too) quick shot...

Thank you for the additional set of eyes, I'll fix that tonight. :-)

**Comment by k-takata** [comment]
> When you execute `nmake clean`, you must add the same option as you build. (At least, DEBUG or not, GUI or not or VIMDLL or not, OLE or not, and enable each interface or not.)

I forgot to mention about `USE_MSVCRT`. It also affects the working directory name.
See the following part for detail:
https://github.com/vim/vim/blob/06bd824869b1cb7a85e64ec94135a35698be5b7f/src/Make_mvc.mak#L164-L205
`DYNAMIC_PYTHON=yes` or other DYNAMIC_xx options doesn't affect. `PYTHON=...` and others affect.

**Comment by dertuxmalwieder** [comment]
Hmm... maybe it would be convenient to add a CLEAN=yes flag to the Makefile so that this happen automatically?

I'll fix the script soon. 😌
