### ISSUE TITLE
badd at the end of the session file changes the order of the buffers on load

### ISSUE THREAD

**Issue by beyondmarc** [vim/vim#4352]
[Patch 8.1.0829: when 'hidden' is set session creates extra buffers](https://github.com/vim/vim/commit/d39e275b57493f9e25e1b62f84810571eee30cf4) moved the `badd` commands to the end of the session file.

This means that `edit` commands are now before the `badd` commands in the session file, therefore loading the files and adding them first to the buffer list.

**To Reproduce**
1. Run vim
2. Edit `filename0` & `filename1` on a single window
3. `mksession` while `filename1` is in the window
4.  Exit vim
5. Run `vim -S session`
6. Error: the buffer order is reversed in the `:buffers` list (`filename1` and then `filename0`).

**Expected behavior**
I expect the order of the buffers to be the same I saved in the session

**Screenshots**
N/A

**Environment:**
 - Vim 8.1.1240
 - OS: Windows 10 1809
 - Terminal: mintty/Cygwin

**Comment by chrisbra** [comment]
It is not clear, that a Vim session guarantees, that the order of the buffer numbers are kept stable. At least, I did not find the documentation make such promises. Isn't this a rather cosmetic issue?

**Comment by beyondmarc** [comment]
No, I guess it's not explicitly specified in the documentation that buffers will be loaded in the same order however, since that's been the observed behavior in vim for as long as I've been using sessions I quickly noticed it when the behavior changed.

For reference, I generally open .c/.h or .cpp/.h/.hpp files together so I can switch between them going to the previous/next buffers. This change breaks this buffer pairing only on some instances, i.e. the buffers that were in the window when calling `:mksession`.

**Comment by echasnovski** [comment]
This should be fixed in 8.2.4090.

**Comment by chrisbra** [comment]
closing then.
