### ISSUE TITLE
font rendering issue

### ISSUE THREAD

**Issue by brettowe** [vim/vim#4353]
I found an issue using the Fira Code font that it cuts off part of the top of some characters
it displays fine on my linux box but I see this issue on a windows 10 1809 box at work
I was running 8.1.1 binary off vim.org to start and did try a binary from here, I forgot to note the exact version but it was 8.1.12xx+
attached are 2 screenshots of Fira Code and Fira Mono

![Capture-code](https://user-images.githubusercontent.com/7308203/57264639-d6207e80-7027-11e9-8c7b-9c153f8aa3f4.PNG)
![Capture-mono](https://user-images.githubusercontent.com/7308203/57264642-d91b6f00-7027-11e9-93e8-a5f2dbdb5cbe.PNG)

**Comment by chrisbra** [comment]
Have you checked if the `linespace` option works for you? Also, what does setting the `renderoptions` change anything?

**Comment by brettowe** [comment]
Linespace I had tried and forgotten about, it did nothing.
Renderoptions I didn't know about, setting type to DirectX did make it render correctly

**Comment by brettowe** [comment]
Well when I was testing it worked. Trying to add it to vimrc it's off again. I'll keep experimenting until I find the right combo that makes it work

**Comment by brettowe** [comment]
I left out setting encoding to utf8 which is required for DirectX. So yeah solves the rendering issue.
It's possible Linespace needs to be set to 3 to prevent some garage being left with some characters from the looks of it

**Comment by brettowe** [comment]
linespace didn't matter turned out. the font had a bug I found an update for it and no more garbage is being left on the screen now

**Comment by chrisbra** [comment]
closing then.
