### ISSUE TITLE
Regression: Lag when search hits start or end of file

### ISSUE THREAD

**Issue by axbender** [vim/vim#4354]
**Describe the bug**
When a standard search (no RE in my case ) hits the start or the end of the file (i.e. when the corresponding "continuing at {top|bottom}" message appears), the search "lags", i.e. it takes some time until the cursor moves to the next match. This behavior is not seen when the above message is not displayed.

**To Reproduce**
" Below, {} are used to indicate a variable

gvim.exe -i NONE -N -u NONE --noplugin -U NONE {file}  # longer than two pages
/\<{some_pattern}\>
/ or ?    " Multiple, until the above condition is satisfied

4. Describe the error
See 1

**Expected behavior**
No lag.

**Screenshots**
n/a

**Environment (please complete the following information):**
 - Vim version [8.1.1282]
 - Windows 64-bit, compiled with MinGW1809, macOS 10.14]

**Additional context**
The problem does not appear with the vanilla 8.1.0001 downloaded from the web site. (Was not able to bisect).

**Comment by chrisbra** [comment]
yes, please update, this has been fixed by https://github.com/vim/vim/commit/c7a10b35de70471519d104a74d402c63557f0512
