### ISSUE TITLE
Vim bug about term true transparency

### ISSUE THREAD

**Issue by ghost** [vim/vim#436]
Hello,

I have a problem with my vim since some times.
I'm using compton + urxvt + vim with true transparency (that's when the bug occurs)

Vim version : 7.4.769
When i start vim (with file or not), i have this line which is added (buffer problem?):
:dddd/0000/0000/0000[>85;95;0c

The only way i find to resolve this is to compile a minimal vim (i'm on gentoo).
Any idea about how i can track and resolve this problem?
I'm a little lost

Have a nice day,
Thanks

**Comment by vim-ml** [comment]
Hi,

2015-10-1 (Thu) 7:11:19 UTC+9 Celes-Eternal:

> Hello,
> 
> I have a problem with my vim since some times.
> 
> I'm using compton + urxvt + vim with true transparency (that's when the bug occurs)
> 
> When i start vim (with file or not), i have this line which is added (buffer problem?):
> 
> :dddd/0000/0000/0000[>85;95;0c
> 
> The only way i find to resolve this is to compile a minimal vim (i'm on gentoo).
> 
> Any idea about how i can track and resolve this problem?
> 
> I'm a little lost

What Vim version are you using?

## 

Best regards,
Hirohito Higashi (a.k.a h_east)

**Comment by vim-ml** [comment]
Hi,

2015-10-1 (Thu) 7:51:32 UTC+9 h_east:

> Hi,
> 
> 2015-10-1 (Thu) 7:11:19 UTC+9 Celes-Eternal:
> 
> > Hello,
> > 
> > I have a problem with my vim since some times.
> > 
> > I'm using compton + urxvt + vim with true transparency (that's when the bug occurs)
> > 
> > When i start vim (with file or not), i have this line which is added (buffer problem?):
> > 
> > :dddd/0000/0000/0000[>85;95;0c
> > 
> > The only way i find to resolve this is to compile a minimal vim (i'm on gentoo).
> > 
> > Any idea about how i can track and resolve this problem?
> > 
> > I'm a little lost
> 
> What Vim version are you using?

Perhaps, Are you using Vim 7.4.769 on Gentoo?
https://packages.gentoo.org/package/app-editors/vim

Your reported problem fixed by Vim 7.4.770.
https://groups.google.com/forum/#!searchin/vim_dev/7.4.770/vim_dev/BTuBkjUcoUw/KHtRSyXiRk8J

Please update Vim 7.4.770 or later.

## Thanks

Best regards,
Hirohito Higashi (a.k.a h_east)

**Comment by vim-ml** [comment]
On Thu, Oct 1, 2015 at 1:59 AM, h_east h.east.727@gmail.com wrote:

> Hi,
> 
> 2015-10-1 (Thu) 7:51:32 UTC+9 h_east:
> 
> > Hi,
> > 
> > 2015-10-1 (Thu) 7:11:19 UTC+9 Celes-Eternal:
> > 
> > > Hello,
> > > 
> > > I have a problem with my vim since some times.
> > > 
> > > I'm using compton + urxvt + vim with true transparency (that's when the bug occurs)
> > > 
> > > When i start vim (with file or not), i have this line which is added (buffer problem?):
> > > 
> > > :dddd/0000/0000/0000[>85;95;0c
> > > 
> > > The only way i find to resolve this is to compile a minimal vim (i'm on gentoo).
> > > 
> > > Any idea about how i can track and resolve this problem?
> > > 
> > > I'm a little lost
> > 
> > What Vim version are you using?
> 
> Perhaps, Are you using Vim 7.4.769 on Gentoo?
> https://packages.gentoo.org/package/app-editors/vim
> 
> Your reported problem fixed by Vim 7.4.770.
> https://groups.google.com/forum/#!searchin/vim_dev/7.4.770/vim_dev/BTuBkjUcoUw/KHtRSyXiRk8J
> 
> Please update Vim 7.4.770 or later.
> 
> ## Thanks
> 
> Best regards,
> Hirohito Higashi (a.k.a h_east)

Compiling your own Vim isn't hard stuff, and in most cases you don't
even need to uninstall a version coming, for instance, from your Linux
distro.

See:
- http://vim.wikia.com/wiki/Getting_the_Vim_source_with_Mercurial (the
  "master" repository is now on github, but for people who, like me,
  prefer Mercurial, there is a mirror at
  https://bitbucket.org/vim-mirror/vim )
- http://users.skynet.be/antoine.mechelynck/vim/compile.htm (Compiling
  Vim on Windows)
- http://users.skynet.be/antoine.mechelynck/vim/compunix.htm
  (Compiling Vim on unix-like systems incl. Linux)

For Windows, there exist precompiled 32-bit versions of Vim (which run
also on 64-bit systems) at
http://sourceforge.net/projects/cream/files/Vim/ — this is what the
regulars of these here lists have nicknamed "Vim without Cream". The
latest version available there is at patchlevel 7.4.827, dated
2015-09-05.

Best regards,
Tony.

**Comment by ghost** [comment]
Thanks for your answer, it seems that i have spend my night for nothing.
I wasn't thinking that was something like that because i remembered a time where it was working sorry...
I'll check that this night and come back after that.

Edit:
You was right, it works well now!
Thanks again
