### ISSUE TITLE
vim+urxvt loses keypresses at exit, stoptermcap stuck

### ISSUE THREAD

**Issue by arcnmx** [vim/vim#4365]
When run with the urxvt terminal, vim will [unnecessarily wait 0.1s when quitting](https://github.com/vim/vim/blob/2782126/src/term.c#L3575). Any characters typed during this time will be flushed/consumed; key sequences like `:wq<return>something<return>` if typed fast enough can result in a truncated `mething` being executed in the underlying shell.

**To Reproduce**
1. `xrdb -merge <<< 'URxvt*background: rgba:4444/4444/4444/eeee'`
2. `urxvt -e sh -i`
3. In the new terminal, `vim --clean '+set t_RC='`
4. type `:q<return>asdf<return>` rather quickly
5. observe your prompt/shell; you might get a disk space usage report!
6. re-run with an alpha of `ffff` and observe that it resolves the issue
7. Now try `vim --clean` (without clearing `t_RC`), it's back :( 

**Expected behavior**
vim should quit immediately and not eat keypresses that were not intended for vim.

**Environment (please complete the following information):**
- Vim 8.1.1186-1
- OS: Arch Linux and others
- Terminal: rxvt-unicode v9.22

**Additional context**

There are two bugs/issues here:
1. vim [acknowledges that `CSI 11;?` can return `rgba:`](https://github.com/vim/vim/blob/2782126/src/term.c#L4919), but is unable to parse the result. It will consume the result so it is not output to the user/terminal, but `rbg_status`/`rfg_status` will remain `STATUS_SENT`. This later on results in vim waiting for a message that will never arrive.
    - There seems to be no obvious `STATUS_INVALID` type option, and I'm not familiar enough with the context these values are used in or what minimal impact fix would be appropriate, so I'm filing this as an issue rather than a PR. I believe ideally vim would be able to parse urxvt's `rgba:` response (ignoring the alpha should be reasonable?), but am not sure whether a patch introducing this behaviour would be welcome?
2. urxvt appears to not support [T_CRC](https://github.com/vim/vim/blob/2782126/src/term.c#L4819)? The characters do not get echo'd to the screen (as the note says about gnome terminal), but as far as I can tell it does not seem to respond at all, and thus causes vim to wait at quit.

**Comment by brammool** [comment]
> When run with the urxvt terminal, vim will [unnecessarily wait 0.1s
> when
> quitting](https://github.com/vim/vim/blob/2782126/src/term.c#L3575).
> Any characters typed during this time will be flushed/consumed; key
> sequences like `:wq<return>something<return>` if typed fast enough can
> result in a truncated `mething` being executed in the underlying
> shell.
> 
> **To Reproduce**
> 1. `xrdb -merge <<< 'URxvt*background: rgba:4444/4444/4444/eeee'`
> 2. `urxvt -e sh -i`
> 3. In the new terminal, `vim --clean '+set t_RC='`
> 4. type `:q<return>asdf<return>` rather quickly
> 5. observe your prompt/shell; you might get a disk space usage report!
> 6. re-run with an alpha of `ffff` and observe that it resolves the issue
> 7. Now try `vim --clean` (without clearing `t_RC`), it's back :( 
> 
> **Expected behavior**
> vim should quit immediately and not eat keypresses that were not intended for vim.
> 
> **Environment (please complete the following information):**
> - Vim 8.1.1186-1
> - OS: Arch Linux and others
> - Terminal: rxvt-unicode v9.22
> 
> **Additional context**
> 
> There are two bugs/issues here:
> 1. vim [acknowledges that `CSI 11;?` can return
> `rgba:`](https://github.com/vim/vim/blob/2782126/src/term.c#L4919),
> but is unable to parse the result. It will consume the result so it is
> not output to the user/terminal, but `rbg_status`/`rfg_status` will
> remain `STATUS_SENT`. This later on results in vim waiting for a
> message that will never arrive.
>   - There seems to be no obvious `STATUS_INVALID` type option, and I'm
>   not familiar enough with the context these values are used in or
>   what minimal impact fix would be appropriate, so I'm filing this as
>   an issue rather than a PR. I believe ideally vim would be able to
>   parse urxvt's `rgba:` response, but am not sure whether a patch
>   introducing this behaviour would be welcome?
> 2. urxvt appears to not support
> [T_CRC](https://github.com/vim/vim/blob/2782126/src/term.c#L4819)? The
> characters do not get echo'd to the screen (as the note says about
> gnome terminal), but as far as I can tell it does not seem to respond
> at all, and thus causes vim to wait at quit.

It would be possible to figure out that a response to a foreground or
background request has been received that we can't parse.  But there is
a more general problem: For any of the requests, if the terminal does
not respond for any reason, then the STATUS_SENT will be maintained
forever.

It's probably best to remember when the request was sent, and assume the
response will never come after some time, e.g. two seconds.

-- 
A fool must search for a greater fool to find admiration.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by arcnmx** [comment]
> there is a more general problem: For any of the requests, if the terminal does not respond for any reason, then the STATUS_SENT will be maintained forever. It's probably best to remember when the request was sent, and assume the response will never come after some time, e.g. two seconds.

Though I'm now personally content working around this in vimrc, this would be a welcome change! It did take some digging to find the cause to begin with, so anything that resolves this on its own would've been nice.

> It would be possible to figure out that a response to a foreground or background request has been received that we can't parse. But

Considering that the code already does this (handles a 11/10 response, eats it until the terminating `\7`, then only ignores the contents because it doesn't start with `rgb:`), it seems reasonable to do so even with the timeout behaviour as a fallback? There is currently no `STATUS_` value to represent such a "received but unhandled" state which makes it harder to suggest a simple `else` to fix this, but I suppose having a status for timeouts would enable that.

**Comment by brammool** [comment]
> > there is a more general problem: For any of the requests, if the
> > terminal does not respond for any reason, then the STATUS_SENT will
> > be maintained forever. It's probably best to remember when the
> > request was sent, and assume the response will never come after some
> > time, e.g. two seconds.
> 
> Though I'm now personally content working around this in vimrc, this
> would be a welcome change! It did take some digging to find the cause
> to begin with, so anything that resolves this on its own would've been
> nice.
> 
> > It would be possible to figure out that a response to a foreground
> > or background request has been received that we can't parse. But
> 
> Considering that the code already does this (handles a 11/10 response,
> eats it until the terminating `\7`, then only ignores the contents
> because it doesn't start with `rgb:`), it seems reasonable to do so
> even with the timeout behaviour as a fallback? There is currently no
> `STATUS_` value to represent such a "received but unhandled" state
> which makes it harder to suggest a simple `else` to fix this, but I
> suppose having a status for timeouts would enable that.

The terminal might respond with several escape sequences.  Reacting on
one we don't recognize would not help for when another follows that we
can use.  Setting the status to another value won't change what happens.

The patch is out, give it a try.

-- 
To keep milk from turning sour: Keep it in the cow.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by arcnmx** [comment]
> The terminal might respond with several escape sequences.  Reacting on one we don't recognize would not help for when another follows that we can use.  Setting the status to another value won't change what happens.

I'm not sure that's quite true as the current implementation seems to react to any messages it can parse, regardless of the status or whether it even requested the message? There are interactions here but maybe not worth exploring given the timeout patch and ability to disable codes that aren't supported.

My real question anyway here regarding the 11/10 response is whether a patch parsing the `rgba:` variant is something that could be considered/accepted.

> The patch is out, give it a try.

Seems to work as expected, thanks! (I'm away from my usual machine for the week and having an issue where `can_get_termresponse()` is false and preventing the requests from being made at all, but that seems to just be something up with the build environment on this laptop unrelated to the patch)

**Comment by chrisbra** [comment]
closing then.
