### ISSUE TITLE
Recover from swap file failed on windows ?

### ISSUE THREAD

**Issue by cs86661** [vim/vim#4369]
**Describe the bug**
Recover from swap file failed on windows ?
When I using `:set dir =$TEMP//`

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `cmd.exe` and input `gvim --clean --cmd ":set dir=$TEMP//" "%ProgramFiles(x86)%\Vim\_vimrc"`
2. Modify some lines and use windows task manager to kill gvim.exe
3. Then back to Step 1, and choose `Recover` to restore last modified state.
4. Gvim will produce `E305: No swap file found for _vimrc`

**Expected behavior**
Recover from swap file.

**Screenshots**
![image](https://user-images.githubusercontent.com/2338762/57582691-619f8100-74fa-11e9-951d-ef8f1bda4734.png)

**Environment (please complete the following information):**
 - VIM - Vi IMproved 8.1 (2018 May 18, compiled May  8 2019 23:53:53)
MS-Windows 32-bit GUI version with OLE support
Included patches: 1-1296
Big version with GUI.  Features included (+) or not (-):
+acl                +cindent            +cursorshape        -farsi              +jumplist           +mksession          +path_extra         -ruby               +tcl/dyn            +vartabs            +writebackup
+arabic             +clientserver       +dialog_con_gui     +file_in_path       +keymap             +modify_fname       +perl/dyn           +scrollbind         -termguicolors      +vertsplit          -xfontset
+autocmd            +clipboard          +diff               +find_in_path       +lambda             +mouse              +persistent_undo    +signs              +terminal           +virtualedit        -xim
+autochdir          +cmdline_compl      +digraphs           +float              +langmap            +mouseshape         -postscript         +smartindent        -termresponse       +visual             +xpm_w32
+autoservername     +cmdline_hist       +directx            +folding            +libcall            +multi_byte_ime/dyn +printer            +startuptime        +textobjects        +visualextra        -xterm_save
+balloon_eval       +cmdline_info       -dnd                -footer             +linebreak          +multi_lang         -profile            +statusline         +textprop           +viminfo            
-balloon_eval_term  +comments           -ebcdic             +gettext/dyn        +lispindent         -mzscheme           +python/dyn         -sun_workshop       -tgetent            +vreplace           
+browse             +conceal            +emacs_tags         -hangul_input       +listcmds           +netbeans_intg      +python3/dyn        +syntax             +timers             -vtp                
++builtin_terms     +cryptv             +eval               +iconv/dyn          +localmap           +num64              +quickfix           +tag_binary         +title              +wildignore         
+byte_offset        +cscope             +ex_extra           +insert_expand      +lua/dyn            +ole                +reltime            -tag_old_static     +toolbar            +wildmenu           
+channel            +cursorbind         +extra_search       +job                +menu               +packages           +rightleft          -tag_any_white      +user_commands      +windows            
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
  system gvimrc file: "$VIM\gvimrc"
    user gvimrc file: "$HOME\_gvimrc"
2nd user gvimrc file: "$HOME\vimfiles\gvimrc"
3rd user gvimrc file: "$VIM\_gvimrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
    system menu file: "$VIMRUNTIME\menu.vim"
Compilation: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_TERMINAL -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL   -DFEAT_XPM_W32   -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG  /Zl /MT -DFEAT_OLE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DGLOBAL_IME -DFEAT_GUI_MSWIN -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl86.dll\" -DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua53.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python34.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl516.dll\" -DFEAT_BIG /Fd.\ObjGXOULYHTRi386/ /Zi
Linking: link  /nologo /opt:ref /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib netapi32.lib uuid.lib /machine:i386 gdi32.lib version.lib   winspool.lib comctl32.lib advapi32.lib shell32.lib netapi32.lib  /machine:i386 /nodefaultlib libcmt.lib oleaut32.lib user32.lib  /nodefaultlib:lua53.lib   /nodefaultlib:python27.lib /nodefaultlib:python34.lib   "C:\Tcl\lib\tclstub86.lib" WSock32.lib xpm\x86\lib\libXpm.lib /PDB:gvim.pdb -debug

 - OS: Windows 7
 - Terminal: GUI
**Additional context**
None.

**Comment by chrisbra** [comment]
so what does `:set dir?` show? I am confused, that there are 2 path separators in the dialogue above.

**Comment by k-takata** [comment]
Does it occur in other directory than `C:\Program Files (x86)`?

**Comment by cs86661** [comment]
> so what does `:set dir?` show? I am confused, that there are 2 path separators in the dialogue above.

`:set dir?` --> `directory=B:\Temp//`

Please refer to options.txt about 'directory':
```
	- For Unix and Win32, if a directory ends in two path separators "//",
	  the swap file name will be built from the complete path to the file
	  with all path separators substituted to percent '%' signs. This will
	  ensure file name uniqueness in the preserve directory.
	  On Win32, it is also possible to end with "\\".  However, When a
	  separating comma is following, you must use "//", since "\\" will
	  include the comma in the file name. Therefore it is recommended to
	  use '//', instead of '\\'.
```

**Comment by chrisbra** [comment]
I know what the meaning of the `double path separators` in the option `dir` means. That was not what I meant. What confuses me is that the swapname in the swap exists dialog also contains double slashes. IIRC it should contain an absolute path to the swapfile. Also, I am wondering, if Windows File Virtualization might cause this, since you are trying to access a file below `C:\Program Files (x86)`. So the answer to Kens question is also relevant.

**Comment by cs86661** [comment]
> Does it occur in other directory than `C:\Program Files (x86)`?

Yes! But I got different error message.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `cmd.exe` and input `gvim --clean --cmd ":set dir=$TEMP//" "C:\Tcl\license-at8.6-thread.terms"`
2. Modify some lines and use windows task manager to kill gvim.exe
3. Then back to Step 1, and choose `Recover` to restore last modified state.
4. Gvim will produce `E309: Unable to read block 1 from B:\Temp\C%%Tcl%license-at8.6-thread.terms.swp`

**Screenshots**
![image](https://user-images.githubusercontent.com/2338762/57703680-1d93b400-7693-11e9-9446-004c8514eef2.png)

**Comment by chrisbra** [comment]
> Gvim will produce E309: Unable to read block 1 from B:\Temp\C%%Tcl%license-at8.6-thread.terms.swp

That is expected if you don't give gvim time to actually write the swapfile.

**Comment by cs86661** [comment]
> > Gvim will produce E309: Unable to read block 1 from B:\Temp\C%%Tcl%license-at8.6-thread.terms.swp
> 
> That is expected if you don't give gvim time to actually write the swapfile.

I  modify some lines and wait about 20 seconds...Then I notice the .swp size changed.
This time will recover successfully.

**Some test results**
1. `C:\Program Files (x86)\Vim\_vimrc` --> `E305: ...`
2. `C:\Program Files (x86)\Vim\test.log` --> `E305: ...`
3. `C:\Program Files (x86)\test\_vimrc` --> `Recover successfully`
4. `C:\Program Files (x86)\test\test.log` --> `Recover successfully`

**Screenshots**
![image](https://user-images.githubusercontent.com/2338762/57706636-ba0c8500-7698-11e9-893d-aac9baef3ecc.png)
![image](https://user-images.githubusercontent.com/2338762/57710043-bbd94700-769e-11e9-8a7c-5b34f179d90f.png)
![image](https://user-images.githubusercontent.com/2338762/57710338-533e9a00-769f-11e9-8a1c-897e28d4a2f6.png)

**Comment by chrisbra** [comment]
so it only happens when you want to edit something in the $VIM installation directory below `C:\Program Files (x86)\Vim`

I wonder if this could be a permission problem?

**Comment by cs86661** [comment]
> so it only happens when you want to edit something in the $VIM installation directory below `C:\Program Files (x86)\Vim`
> 
> I wonder if this could be a permission problem?

No! I changed to using `:set dir=$TEMP`. It will recover successfully.
So the `double path separators` will caused this issue when edit files in $VIM.

**Screenshots**
![image](https://user-images.githubusercontent.com/2338762/57713589-59377980-76a5-11e9-9fa8-4cf3949a0d56.png)

**Comment by chrisbra** [comment]
so does the swapfile actually exists? can you do a `:recover .swapfilename`?

**Comment by k-takata** [comment]
Reproduced with `C:\tmp\x.c`. When I terminate gvim, then open the file again, E325 is shown. It says that a swapfile exists and it is actually exists. But when I select Recover, E305 is shown.

**Comment by cs86661** [comment]
Does *.scr is special ?
ps1. test.scr and test.log are new create zero size file, add some lines then wait 20 seconds.
ps2. Set default 'directory' setting by `:set dir&`

**Another weired test results**
1. D:\test.scr --> Error
2. D:\test.log --> Recover successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/2338762/57755535-c2f66880-7723-11e9-8e3a-1499aa518bd2.png)
![image](https://user-images.githubusercontent.com/2338762/57755761-44e69180-7724-11e9-9092-3c5304e4cf5d.png)

**Comment by chrisbra** [comment]
Just to make sure, does it make a difference whether you use: 

    :set dir =$TEMP//

or

     :set dir =$TEMP\\

**Comment by k-takata** [comment]
No difference between `\\` and `//` for me.

**Comment by cs86661** [comment]
> Just to make sure, does it make a difference whether you use:
> 
> ```
> :set dir =$TEMP//
> ```
> 
> or
> 
> ```
>  :set dir =$TEMP\\
> ```

The results are the same. only different is *.swp file name.

**Comment by k-takata** [comment]
I think I found the cause of this.

When editing `C:\tmp\x.c` and setting `dir=C:/swap//`, the swap file name becomes `C:/swap//C%%tmp%x.c`.
The function `recover_names()` in `memline.c`, calls `expand_wildcards()` with the swap file name.
`expand_wildcards()` expands not only wildcards but also environment variables. The string `%tmp%` inside the swap file name is expanded as the environment variable. So, Vim fails to find the swap file.
This does happen when a directory name is the same as one of the environment variables.
`C:\Program Files (x86)\Vim\foo` also fails because we have `$VIM`.

We should avoid expanding `%var%` in `expand_wildcards()` in this case. Maybe we need to add a flag to avoid expanding the environment variables? (E.g. `EW_NOTENV`)

**Comment by k-takata** [comment]
How about this patch?

```diff
--- a/src/memline.c
+++ b/src/memline.c
@@ -1887,7 +1887,7 @@ recover_names(
 	if (num_names == 0)
 	    num_files = 0;
 	else if (expand_wildcards(num_names, names, &num_files, &files,
-					EW_KEEPALL|EW_FILE|EW_SILENT) == FAIL)
+			    EW_NOTENV|EW_KEEPALL|EW_FILE|EW_SILENT) == FAIL)
 	    num_files = 0;
 
 	/*
--- a/src/misc1.c
+++ b/src/misc1.c
@@ -4020,7 +4020,7 @@ gen_expand_wildcards(
 	    /*
 	     * First expand environment variables, "~/" and "~user/".
 	     */
-	    if (has_env_var(p) || *p == '~')
+	    if ((has_env_var(p) && !(flags & EW_NOTENV)) || *p == '~')
 	    {
 		p = expand_env_save_opt(p, TRUE);
 		if (p == NULL)
--- a/src/vim.h
+++ b/src/vim.h
@@ -808,6 +808,7 @@ extern int (*dyn_libintl_wputenv)(const 
 				 * if executable is in $PATH */
 #define EW_DODOT	0x4000	/* also files starting with a dot */
 #define EW_EMPTYOK	0x8000	/* no matches is not an error */
+#define EW_NOTENV	0x10000	// do not expand environment variables
 
 /* Flags for find_file_*() functions. */
 #define FINDFILE_FILE	0	/* only files */
```

**Comment by brammool** [comment]
> How about this patch?

It's simpler than I expected.  Should be OK to include.
How about a test?


-- 
CRONE:  Who sent you?
ARTHUR: The Knights Who Say GNU!
CRONE:  Aaaagh!  (she looks around in rear) No!  We have no licenses here.
           "Monty Python and the Holy editor wars" PYTHON (MONTY) SOFTWARE LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
> I think I found the cause of this.
> 
> When editing `C:\tmp\x.c` and setting `dir=C:/swap//`, the swap file name becomes `C:/swap//C%%tmp%x.c`.
> The function `recover_names()` in `memline.c`, calls `expand_wildcards()` with the swap file name.
> `expand_wildcards()` expands not only wildcards but also environment variables. The string `%tmp%` inside the swap file name is expanded as the environment variable. So, Vim fails to find the swap file.
> This does happen when a directory name is the same as one of the environment variables.
> `C:\Program Files (x86)\Vim\foo` also fails because we have `$VIM`.
> 
> We should avoid expanding `%var%` in `expand_wildcards()` in this case. Maybe we need to add a flag to avoid expanding the environment variables? (E.g. `EW_NOTENV`)

Good catch.  Yes, adding an EW_NOTENV sounds like the right solution.
There already is  EW_NOTWILD, perhaps that would work?

-- 
FIRST VILLAGER: We have found a witch.  May we burn her?
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
> There already is EW_NOTWILD, perhaps that would work?

That might not work, because we still need to expand `?`. E.g. `C:/swap//C%%tmp%x.c.sw?`.
(My previous comment was a bit incorrect. I forget to add `.sw?` at the end of the swap file name.)

> How about a test?

Hmm, I have no idea how to test this at all.
We need to edit a file with Vim and terminate Vim, then open the same file again. And when E325 is shown, select "Recover", and make sure that E305 is not shown. I don't know whether we can do this automatically.

**Comment by brammool** [comment]
> > There already is EW_NOTWILD, perhaps that would work?
> 
> That might not work, because we still need to expand `?`. E.g.
> `C:/swap//C%%tmp%x.c.sw?`.
> (My previous comment was a bit incorrect. I forget to add `.sw?` at
> the end of the swap file name.)

OK, we do need a new flag.

> > How about a test?
> 
> Hmm, I have no idea how to test this at all.
> We need to edit a file with Vim and terminate Vim, then open the same
> file again. And when E325 is shown, select "Recover", and make sure
> that E305 is not shown. I don't know whether we can do this
> automatically.

This probably requires running Vim in a terminal window.  The swap file
can be created by having Vim create one, make a copy, exit Vim, then put
the copy in place of the original swap file.  Then start Vim for
recovery and use term_sendkeys() to have it do its thing.  Check the
expected behavior with either term_scrape() or a screenshot (that might
show a different path on different machines, then it doesn't work).

-- 
I have read and understood the above. X________________

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by cs86661** [comment]
> How about this patch?
> 
> ```diff
> --- a/src/memline.c
> +++ b/src/memline.c
> @@ -1887,7 +1887,7 @@ recover_names(
>  	if (num_names == 0)
>  	    num_files = 0;
>  	else if (expand_wildcards(num_names, names, &num_files, &files,
> -					EW_KEEPALL|EW_FILE|EW_SILENT) == FAIL)
> +			    EW_NOTENV|EW_KEEPALL|EW_FILE|EW_SILENT) == FAIL)
>  	    num_files = 0;
>  
>  	/*
> --- a/src/misc1.c
> +++ b/src/misc1.c
> @@ -4020,7 +4020,7 @@ gen_expand_wildcards(
>  	    /*
>  	     * First expand environment variables, "~/" and "~user/".
>  	     */
> -	    if (has_env_var(p) || *p == '~')
> +	    if ((has_env_var(p) && !(flags & EW_NOTENV)) || *p == '~')
>  	    {
>  		p = expand_env_save_opt(p, TRUE);
>  		if (p == NULL)
> --- a/src/vim.h
> +++ b/src/vim.h
> @@ -808,6 +808,7 @@ extern int (*dyn_libintl_wputenv)(const 
>  				 * if executable is in $PATH */
>  #define EW_DODOT	0x4000	/* also files starting with a dot */
>  #define EW_EMPTYOK	0x8000	/* no matches is not an error */
> +#define EW_NOTENV	0x10000	// do not expand environment variables
>  
>  /* Flags for find_file_*() functions. */
>  #define FINDFILE_FILE	0	/* only files */
> ```

I have tested your patch. Its almost fixed this issue...but still can't recover for *.scr ?
I can recover only by input `:recover B:\Temp\B%%test.scr.swp`

**Screenshots**
![image](https://user-images.githubusercontent.com/2338762/57943384-7919a800-7906-11e9-92df-64a946a839a3.png)
![image](https://user-images.githubusercontent.com/2338762/57943448-a7978300-7906-11e9-959a-3df929b8fb8f.png)

**Another weired test results**
1. "C:\Tcl\test.log" --> Show only one swap file can recover
2. "%ProgramFiles(x86)%\Vim\test.log" --> Show two swap file can recover

**Screenshots**
![image](https://user-images.githubusercontent.com/2338762/57945301-17f4d300-790c-11e9-9af1-bc841ddacd3b.png)
![image](https://user-images.githubusercontent.com/2338762/57945651-04963780-790d-11e9-9b85-3d3ef1416db4.png)

**Comment by k-takata** [comment]
> **Another weired test results**
> 
> 1. "C:\Tcl\test.log" --> Show only one swap file can recover
> 2. "%ProgramFiles(x86)%\Vim\test.log" --> Show two swap file can recover

Okay, I found the cause of this.
In `recover_name()`, `fullpathcmp()` is used to compare the swap file names, and if it matches with the current swap file ("*%test.log.swo" in this case), it is removed from the list. However, `fullpathcmp()` also expands the environment variables, so it doesn't match and causes the problem.
Maybe we should add a flag to `fullpathcmp()` not to expand the env variables?

Not sure about \*.scr.

**Comment by k-takata** [comment]
Add a test:
https://bitbucket.org/k_takata/vim-ktakata-mq/src/c3ec1efe18c3cd759e5969f2de8e10a9b108f44d/test-for-4369.patch?at=default

And updated the patch:
https://bitbucket.org/k_takata/vim-ktakata-mq/src/be1422cf12d00fb0f9af560d7ddc1cf42214d7ed/fix-4369.patch?at=default

**Comment by k-takata** [comment]
About \*.scr, it also occurs on Linux, not only on Windows. So, it's different from the env var expansion.
It seems that \*.s?? is (wrongly) considered as a swapfile at here:
https://github.com/vim/vim/blob/5c017b2de28d19dfa4af58b8973e32f31bb1477e/src/memline.c#L1131-L1148

**Comment by k-takata** [comment]
I created a PR for the two issues #4415.

**Comment by cs86661** [comment]
> I created a PR for the two issues #4415.

All test pass. Thanks everyone! :)
