### ISSUE TITLE
<C-w>p does not work in mapping when the cursor is in the first line or the last line

### ISSUE THREAD

**Issue by Shougo** [vim/vim#4373]
**Describe the bug**
`<C-w>p` does not work in mapping when the cursor is in the first line or the last line

**To Reproduce**
Detailed steps to reproduce the behavior:

```vim
filetype plugin indent on
syntax enable

set cursorline

nnoremap <buffer> <C-j>  <C-w>pj<C-w>p
nnoremap <buffer> <C-k>  <C-w>pk<C-w>p

split
```

1. Run `gvim -Nu test.vimrc test.vimrc`
2. Type '`<C-j>` `<C-j>`....'
3. The cursor stays another window when the cursor is on the last line

The same problem is reproduce-able by pressing `<C-k>` in the vimrc.

**Expected behavior**
The cursor should move to original window by `<C-w>p`.

**Environment (please complete the following information):**
 - Vim version : 8.1.1332
 - OS: Manjaro Linux
 - Terminal: GUI

**Additional context**

**Comment by jottkaerr** [comment]
That's not a bug. The mapping stops on encountering the first error, and pressing `k` on the first line or `j` on the last line is considered to be an error. The final `<C-W>p` is never executed.

Regards,
Jürgen

**Comment by Shougo** [comment]
> The mapping stops on encountering the first error, and pressing k on the first line or j on the last line is considered to be an error. 

Oh,  I have not known the behavior...
