### ISSUE TITLE
Makefile changes

### ISSUE THREAD

**Issue by DNSGeek** [vim/vim#4376]
For those of us that have customized makefiles, it's really painful every time the makefile is updated to have to go back through and apply the customizations after a git pull. Recently this has been happening several times a week. It's not fun.

**Comment by k-takata** [comment]
Do you use `git stash`?

**Comment by chrisbra** [comment]
I am not sure what you want us to do here. Certainly not, that makefiles are not changed anymore. However, what I have been doing is using `git pull --rebase`. That will keep your local commits on top of the upstream changes.

Closing, as this is clearly not a Vim issue.

**Comment by tonymec** [comment]
What concerns Vim makefiles, I don't custdomize them, and in shadow directories I even replace the copies of src/Makefile by links to it. My configure arguments are set by means of environment variables.

Best regards,
Tony.
