### ISSUE TITLE
E297: Write Error in swap file

### ISSUE THREAD

**Issue by snoopyjc** [vim/vim#4378]
I frequently leave many vim editor windows open.  Daily I have to unplug my laptop from the network and hook it back up in another location.  When I go to continue to edit the files I have open, I get E297: Write Error in swap file.  I can clear this error by using :e! but it would be much better if vim recovers on its own.

**To Reproduce**
Edit a file then unplug and re-plug the ethernet cable.

**Expected behavior**
No errors

**Screenshots**

![VIM issue](https://user-images.githubusercontent.com/9206213/57820650-a24a0500-775b-11e9-922f-af7a6768287f.png)

**Environment (please complete the following information):**
 - Vim version 8.1
 - OS: Windows 10

**Comment by tonymec** [comment]
Hm… Maybe I'm old-fashioned, but my take on this question is that before leaving the computer for any long time, and certainly before unplugging it to move it to another location, I would "save my work". In Vim I have the following mappings (in my vimrc) just for that:
```vim
        map  <F3> :wa|wv<CR>
        map! <F3> <C-O>:wa|wv<CR>
```

Best regards,
Tony.

**Comment by chrisbra** [comment]
is this with files you are editing on a network share or remote filesystem?

**Comment by snoopyjc** [comment]
Tony - I do save each time I change something.  I just like to keep the source code I'm working with open.  Chrisbra: Yes, the files are on my network drive.  I don't keep anything on my PC as it's not backed up.

**Comment by brammool** [comment]
Just set the 'directory' option to a local directory, then you won't have this problem.

**Comment by chrisbra** [comment]
> Yes, the files are on my network drive. I don't keep anything on my PC as it's not backed up.

Well, sorry, then don't cut your network connection and wonder about it. This is certainly not a bug in Vim here. 

You might be able to tweak your updatetime, directory and undofile option (and possibly also the backupskip option.

**Comment by snoopyjc** [comment]
It's ok - I fixed it myself!

[src.diff.txt](https://github.com/vim/vim/files/3221274/src.diff.txt)

**Comment by snoopyjc** [comment]
I say if the software can be adjusted to make my life easier and avoid an error message and a user action (:e!), then have the software do that.  Why have software at all if it's just gonna make things harder for me?

**Comment by brammool** [comment]
Thanks.  I like the idea, but the code needs a bit of cleaning up.  I'll make a patch.  Let me know your name if you want it on the patch.

**Comment by snoopyjc** [comment]
Thanks!

Joe Orost

-joe

**Comment by brammool** [comment]
> Thanks!
> 
> Joe Orost

I'm wondering if it fails when the seek bails out.  Then the
close+reopen doesn't happen.

-- 
Despite the cost of living, have you noticed how it remains so popular?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by yutsunoki** [comment]
So, I try my think to solve 
you can try to turn off the windows security `**Real-time protection**` or go to controlled folder access and click the `**allow an app through Controlled folder access.**`[enter image description here][1]


[enter image description here][2]


[enter image description here][3]


  [1]: https://i.stack.imgur.com/p1gFi.png
  [2]: https://i.stack.imgur.com/pmtSn.png
  [3]: https://i.stack.imgur.com/QpuWY.png
