### ISSUE TITLE
Text property moved to wrong location after a change done through blockwise Visual mode

### ISSUE THREAD

**Issue by markonm** [vim/vim#4384]
**To Reproduce**
1. Run `vim --clean -S reproduce.vim`

```
" reproduce.vim
call setline(1, 'The number 123 is smaller than 4567.')
call prop_type_add('number', {'highlight': 'Constant'})
call prop_add(1, 12, {'length': 3, 'type': 'number'})
execute "normal! 0\<c-v>ecThe"
```
**Expected behavior**
123 should remain highlighted.

**Environment**
Vim version 8.1.1333
OS: Windows 10
Terminal: GUI

**Comment by brammool** [comment]
> **To Reproduce**
> 1. Run `vim --clean -S reproduce.vim`
> 
> ```
> " reproduce.vim
> call setline(1, 'The number 123 is smaller than 4567.')
> call prop_type_add('number', {'highlight': 'Constant'})
> call prop_add(1, 12, {'length': 3, 'type': 'number'})
> execute "normal! 0\<c-v>ecThe"
> ```
> **Expected behavior**
> 123 should remain highlighted.
> 
> **Environment**
> Vim version 8.1.1333
> OS: Windows 10
> Terminal: GUI

Thanks for the example.  I was just working on text properties, it is
only halfway done.  There will be several more like this, it would be
good if you can show how to reproduce remaining problems.

-- 
Managers are like cats in a litter box.  They instinctively shuffle things
around to conceal what they've done.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
