### ISSUE TITLE
:vert options doesn't work

### ISSUE THREAD

**Issue by AvianY** [vim/vim#4401]
As the title says. I noticed, that `:vert options` doesn't open the options windos in a vertical split, but instead in the default, horizontal split

**Comment by k-takata** [comment]
How about this patch?

```diff
--- a/src/ex_cmds2.c
+++ b/src/ex_cmds2.c
@@ -3016,7 +3016,9 @@ ex_packadd(exarg_T *eap)
 ex_options(
     exarg_T	*eap UNUSED)
 {
-    vim_setenv((char_u *)"OPTWIN_CMD", (char_u *)(cmdmod.tab ? "tab" : ""));
+    vim_setenv((char_u *)"OPTWIN_CMD",
+	    (char_u *)(cmdmod.tab ? "tab" :
+		(cmdmod.split & WSP_VERT) ? "vert" : ""));
     cmd_source((char_u *)SYS_OPTWIN_FILE, NULL);
 }
 #endif
```

**Comment by brammool** [comment]
Ken Takata wrote:

> How about this patch?
> 
> ```diff
> --- a/src/ex_cmds2.c
> +++ b/src/ex_cmds2.c
> @@ -3016,7 +3016,9 @@ ex_packadd(exarg_T *eap)
>  ex_options(
>      exarg_T	*eap UNUSED)
>  {
> -    vim_setenv((char_u *)"OPTWIN_CMD", (char_u *)(cmdmod.tab ? "tab" : ""));
> +    vim_setenv((char_u *)"OPTWIN_CMD",
> +	    (char_u *)(cmdmod.tab ? "tab" :
> +		(cmdmod.split & WSP_VERT) ? "vert" : ""));
>      cmd_source((char_u *)SYS_OPTWIN_FILE, NULL);
>  }
>  #endif
> ```

That should do it.  Should not be difficult to add a test case in
test_options.vim, Test_options().  And also test ":tab options" there.

-- 
A)bort, R)etry, D)o it right this time

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
Okay, how about this then?

```diff
--- a/src/ex_cmds2.c
+++ b/src/ex_cmds2.c
@@ -3016,7 +3016,9 @@ ex_packadd(exarg_T *eap)
 ex_options(
     exarg_T	*eap UNUSED)
 {
-    vim_setenv((char_u *)"OPTWIN_CMD", (char_u *)(cmdmod.tab ? "tab" : ""));
+    vim_setenv((char_u *)"OPTWIN_CMD",
+	    (char_u *)(cmdmod.tab ? "tab" :
+		(cmdmod.split & WSP_VERT) ? "vert" : ""));
     cmd_source((char_u *)SYS_OPTWIN_FILE, NULL);
 }
 #endif
--- a/src/testdir/test_options.vim
+++ b/src/testdir/test_options.vim
@@ -51,6 +51,31 @@ func Test_options()
   endtry
   call assert_equal('ok', caught)
 
+  " Check if the option-window is opened horizontally.
+  wincmd j
+  call assert_notequal('option-window', bufname(''))
+  wincmd k
+  call assert_equal('option-window', bufname(''))
+  " close option-window
+  close
+
+  " Open the option-window vertically.
+  vert options
+  " Check if the option-window is opened vertically.
+  wincmd l
+  call assert_notequal('option-window', bufname(''))
+  wincmd h
+  call assert_equal('option-window', bufname(''))
+  " close option-window
+  close
+
+  " Open the option-window in a new tab.
+  tab options
+  " Check if the option-window is opened in a tab.
+  normal gT
+  call assert_notequal('option-window', bufname(''))
+  normal gt
+  call assert_equal('option-window', bufname(''))
   " close option-window
   close
 endfunc
```

**Comment by AvianY** [comment]
I also noticed that `:rightbelow options` doesn't work as well.

It is possible that other existing 'modifier' words also don't work on `options` command (just like `tab` and `vert` didn't...
