### ISSUE TITLE
Regression: Buffer is nomodifiable after :s/../\=Function/gn (after 8.1.1345)

### ISSUE THREAD

**Issue by inkarkat** [vim/vim#4403]
**Describe the bug**
Two of my plugins collect match information with `:substitute/.../\=Function()/gn`. Since

    patch 8.1.1345: stuck in sandbox with ":s/../\=Function/gn"
    
    Problem:    Stuck in sandbox with ":s/../\=Function/gn".
    Solution:   Don't skip over code to restore sandbox. (Christian Brabandt)

the buffer is left `nomodifiable`. So it looks like the sandbox is mistakenly kept active after the `:substitute` ends. The above patch (that supposedly should correct this exact issue) does not test `'modifiable'`, and only deals with error cases (normal error and `:throw`) inside `Function()`, but not the normal, successful execution. Vim versions prior to the patch work fine.

**To Reproduce**

    vim --clean -S <(cat <<'EOF'
    func! Foo()
        return submatch(0)
    endfunc
    call setline(1, ['1 aaa', '2 aaa', '3 aaa'])
    %s/aaa/\=Foo()/gn
    if &modifiable | quit! | else | cquit! | endif
    EOF
    )

**Environment:**
 - Vim version 8.1.1345
 - OS: Ubuntu 16.04 64-bit
 - Terminal: GNOME Terminal, GUI

**Comment by chrisbra** [comment]
Oh yes, the modifiable flag is stored too late. This patch fixes it (thanks for the clear example!)

```patch
diff --git a/src/ex_cmds.c b/src/ex_cmds.c
index df5dcd01f..0174fd6b0 100644
--- a/src/ex_cmds.c
+++ b/src/ex_cmds.c
@@ -5557,6 +5557,7 @@ do_sub(exarg_T *eap)
                 * 3. substitute the string.
                 */
 #ifdef FEAT_EVAL
+               save_ma = curbuf->b_p_ma;
                if (subflags.do_count)
                {
                    // prevent accidentally changing the buffer by a function
@@ -5566,7 +5567,6 @@ do_sub(exarg_T *eap)
                // Save flags for recursion.  They can change for e.g.
                // :s/^/\=execute("s#^##gn")
                subflags_save = subflags;
-               save_ma = curbuf->b_p_ma;
 #endif
                // get length of substitution part
                sublen = vim_regsub_multi(&regmatch,
diff --git a/src/testdir/test_substitute.vim b/src/testdir/test_substitute.vim
index 06bdc243d..a9541cda6 100644
--- a/src/testdir/test_substitute.vim
+++ b/src/testdir/test_substitute.vim
@@ -611,6 +611,20 @@ func Test_sub_cmd_8()
   set titlestring&
 endfunc

+func Test_sub_cmd_9()
+  new
+  let input=['1 aaa', '2 aaa', '3 aaa']
+  call setline(1, input)
+  func! Foo()
+    return submatch(0)
+  endfunc
+  %s/aaa/\=Foo()/gn
+  call assert_equal(input, getline(1, '$'))
+  call assert_equal(1, &modifiable)
+  delfunc Foo
+  bw!
+endfunc
+
 func Test_nocatch_sub_failure_handling()
   " normal error results in all replacements
   func! Foo()
```

(updated patch slightly and fixed whitespace errors)

**Comment by brammool** [comment]
Christian wrote:

> Oh yes, the modifiable flag is stored too late. This patch fixes it
> (thanks for the clear example!)

It's surprising there was no test for that.  Ideally we try break the
code and check that there is a failing test...


-- 
An operatingsystem is just a name you give to the rest of bloating
idiosyncratic machine-based-features you left out of your editor.
			(author unknown)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
