### ISSUE TITLE
Special variable for current window in statusline function

### ISSUE THREAD

**Issue by blueyed** [vim/vim#4406]
It is currently not easy to have a global statusline function, that knows about if the window it is handling (called for) is the active one.
A workaround is tracking WinEnter/WinLeave (and BufWinEnter) events, and setting up a new function for windows then, but that is clumsy.

It would be much easier, if there was a special variable (e.g. `v:statusline_winid`) that would provide the winid of the window this statusline is for, allowing to just do `let active = winid() == v:statusline_winid` then.

Note that using an expression has limitations (e.g. https://github.com/vim/vim/issues/2829), and does not allow for returning highlight groups (`%#Foo#` - which get used as text).

(There is `g:actual_curbuf` already, but it is only available for expressions (https://github.com/vim/vim/issues/3299) (and also not useful when you want to know if the window is the active one).)

**Comment by brammool** [comment]
> It is currently not easy to have a global statusline function, that knows
> about if the window it is handling (called for) is the active one.
> A workaround is tracking WinEnter/WinLeave (and BufWinEnter) events, and
> setting up a new function for windows then, but that is clumsy.

Why not use a local 'statusline' option value?  Hmm, is the problem that you
don't know if the window that statusline belongs to is the active window?

> It would be much easier, if there was a special variable (e.g.
> `v:statusline_winid`) that would provide the winid of the window this
> statusline is for, allowing to just do `let active = winid() ==
> v:statusline_winid` then.
> 
> Note that using an expression has limitations (e.g.
> https://github.com/vim/vim/issues/2829), and does not allow for returning
> highlight groups (`%#Foo#` - which get used as text).
> 
> (There is `g:actual_curbuf` already, but it is only available for expressions
> (https://github.com/vim/vim/issues/3299) (and also not useful when you want
> to know if the window is the active one).)

-- 
hundred-and-one symptoms of being an internet addict:
16. You step out of your room and realize that your parents have moved and
    you don't have a clue when it happened.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by blueyed** [comment]
> Why not use a local 'statusline' option value?

A location 'statusline' option value can be used as a workaround, but it needs to get updated to pass in the `active` state via it.

I.e. using something like the following (which needs to handle special cases / be more robust IIRC, and adds overhead to every movement between windows in this simplified form):
```vim
function! s:set_stl() abort
  let cur = winnr()
  for w in range(1, winnr('$'))
    let active = w == cur
    call setwinvar(w, '&stl', '%!NeomakeStatusLine('.w.', '.active.')')
  endfor
endfunction

augroup my_neomake_stl
  au!
  autocmd WinEnter,BufWinEnter * call s:set_stl()
augroup END
```

> Hmm, is the problem that you don't know if the window that statusline belongs to is the active window?

Yes.

**Comment by lifepillar** [comment]
For the record, status lines know when to redraw themselves, so autocommands are never necessary (stay away from what status line plugins do!). In particular, it is not necessary to use autocommands to track the currently drawn status line. You may use something like this:

```vim
fun! SetupStl(nr)
  return get(extend(w:, { "is_active": (winnr() == a:nr) }), "", "")
endf

fun! BuildStatusLine(nr)
  return '%{SetupStl(' . a:nr . ')} %{w:["is_active"] ? "active" : "inactive"}'
endf

" winnr() here is always the number of the *active* window
set statusline=%!BuildStatusLine(winnr())
```

This works because, in a `%{}` context (i.e., when `SetupStl()` is invoked), `winnr()` refers to the window to which the status line being drawn belongs.

Anyway, the patch is welcome and will simplify this task. Looking forward to trying it!
