### ISSUE TITLE
Corrupted memory

### ISSUE THREAD

**Issue by Derrior** [vim/vim#4408]
**Describe the bug**
vim crashes on a certain sequence of deleting and pasting (and misspelling)
**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim`
2. Open attached file.py (or create an empty file with following contents)
```
intervals.append(slot['interval'].split('_'))
print(slot['interval'].split('_'))
```
3. Type (in Normal mode) `jwvi(dkwwwlvi([p`
4. It crashes

**Expected behavior**
Expect no crash, but paste recently deleted code

**Screenshots**
```
derrior@derrior-nix:~$ vim vim-crash.py 
Vim: Caught deadly signal ABRT
Vim: preserving files...
Vim: Finished.
Aborted (core dumped)
```
and second time:
```
Vim: Caught deadly signal ABRT
Vim: preserving files...
*** Error in `/usr/bin/vim': malloc(): memory corruption: 0x0000000002484130 ***
                                                                                Vim: Finished.
```

**Environment (please complete the following information):**
 - Vim version ```
   VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
   Included patches: 1-1689
   Extra patches: 8.0.0056
   ```
 - OS: Ubuntu 16.04
 - Terminal: gnome-terminal

**Additional context**
Add any other context about the problem here.

[vim-crash.txt](https://github.com/vim/vim/files/3206696/vim-crash.txt)

**Comment by chrisbra** [comment]
Vim 7.4 is very old, can you first try to reproduce with an uptodate version? Also check if it makes a difference starting from `vim --clean`

**Comment by Derrior** [comment]
Okey. In version 8.0 it crashes the same way
In master build it does not crash, but result  of operation is sometimes different, maybe with sanitizers it can be found

**Comment by Derrior** [comment]
`jwwvi(dkwwwwvi([puukwwwwvi([p`
This command also does not crash, but the last paste can't be undone in second line, 
though after file reopening it disappears

**Comment by chrisbra** [comment]
I tried to reproduce with ASAN enabled, however I did not receive a stack trace. That you couldn't undo might be related to vim being started in compatible mode (try `vim --clean -N`) 

Anyhow, after performing your steps (`jwwvi(dkwwwwvi([puukwwwwvi([p`), the file looked like this to me:

    intervals.append(slot['interval'].split('_')slot['interval'].split('_'))
    print(slot['interslot['interval'].split('_')val'].split('_'))

That is certainly wrong, the last paste command did also change the second line, I guess it should rather look like this:

    intervals.append(slot['interval'].split('_')slot['interval'].split('_'))
    print(slot['interval'].split('_'))



So something fishy, indeed.

**Comment by chrisbra** [comment]
for reference, this was 8.1.1359

**Comment by brammool** [comment]
I don't see any crash or memory error, but I do see that "[p" in Visual mode does weird things.
I'll fix that.  Then it will also replace the Visual selection as it should.
