### ISSUE TITLE
(asan) global-buffer-overflow with text property

### ISSUE THREAD

**Issue by dpelle** [vim/vim#4412]
afl-fuzz found a case of invalid memory access with vim-8.1.1364.
It's a global-buffer-overflow, so not detected by valgrind.

**Steps to Reproduce**

1. Build vim with asan, i.e. uncomment out `SANITIZER_CFLAGS = -g -O0 -fsanitize=address -fno-omit-frame-pointer` in `src/Makefile`
2. Run the following command:
```
$ ./vim --clean \
   -c 'call prop_type_add("xxx", {})' \
   -c 'call prop_add(1, 1, {"type": "xxx"})' \
   -c 'next X' 2>  asan.log
```
3. Observe that vim crashed and `asan.log` contains:

```
=================================================================
==3669==ERROR: AddressSanitizer: global-buffer-overflow on address 0x5625398e5ca1 at pc 0x7f0d63831deb bp 0x7ffd90a24190 sp 0x7ffd90a23938
READ of size 21 at 0x5625398e5ca1 thread T0
    #0 0x7f0d63831dea in __interceptor_memmove (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x7adea)
    #1 0x56253947f72e in vim_memsave /home/pel/sb/vim/src/misc2.c:1330
    #2 0x56253974395f in u_save_line /home/pel/sb/vim/src/undo.c:371
    #3 0x5625397457e4 in u_savecommon /home/pel/sb/vim/src/undo.c:700
    #4 0x562539302f88 in do_ecmd /home/pel/sb/vim/src/ex_cmds.c:4176
    #5 0x5625393215b6 in do_argfile /home/pel/sb/vim/src/ex_cmds2.c:1928
    #6 0x5625393218da in ex_next /home/pel/sb/vim/src/ex_cmds2.c:1965
    #7 0x5625393389c7 in do_one_cmd /home/pel/sb/vim/src/ex_docmd.c:2496
    #8 0x56253932fcf8 in do_cmdline /home/pel/sb/vim/src/ex_docmd.c:991
    #9 0x56253932e39b in do_cmdline_cmd /home/pel/sb/vim/src/ex_docmd.c:592
    #10 0x56253987cf79 in exe_commands /home/pel/sb/vim/src/main.c:2966
    #11 0x5625398756fa in vim_main2 /home/pel/sb/vim/src/main.c:797
    #12 0x562539874d15 in main /home/pel/sb/vim/src/main.c:444
    #13 0x7f0d5f4b3b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #14 0x5625391f35c9 in _start (/home/pel/sb/vim/src/vim+0x1215c9)

0x5625398e5ca1 is located 63 bytes to the left of global variable '*.LC13' defined in 'memline.c' (0x5625398e5ce0) of size 3
  '*.LC13' is ascii string '.s'
0x5625398e5ca1 is located 0 bytes to the right of global variable '*.LC12' defined in 'memline.c' (0x5625398e5ca0) of size 1
  '*.LC12' is ascii string ''
SUMMARY: AddressSanitizer: global-buffer-overflow (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x7adea) in __interceptor_memmove
Shadow bytes around the buggy address:
  0x0ac527314b40: 00 00 00 05 f9 f9 f9 f9 00 00 00 00 00 03 f9 f9
  0x0ac527314b50: f9 f9 f9 f9 00 00 00 00 00 00 00 00 02 f9 f9 f9
  0x0ac527314b60: f9 f9 f9 f9 00 00 00 00 01 f9 f9 f9 f9 f9 f9 f9
  0x0ac527314b70: 00 00 00 00 00 00 00 05 f9 f9 f9 f9 00 00 00 00
  0x0ac527314b80: 00 04 f9 f9 f9 f9 f9 f9 00 00 00 00 00 00 00 00
=>0x0ac527314b90: 00 00 00 00[01]f9 f9 f9 f9 f9 f9 f9 03 f9 f9 f9
  0x0ac527314ba0: f9 f9 f9 f9 00 00 00 f9 f9 f9 f9 f9 00 00 00 00
  0x0ac527314bb0: f9 f9 f9 f9 00 00 00 00 00 07 f9 f9 f9 f9 f9 f9
  0x0ac527314bc0: 00 00 05 f9 f9 f9 f9 f9 00 00 00 05 f9 f9 f9 f9
  0x0ac527314bd0: 00 00 00 00 00 00 00 00 01 f9 f9 f9 f9 f9 f9 f9
  0x0ac527314be0: 00 f9 f9 f9 f9 f9 f9 f9 00 00 00 00 00 03 f9 f9
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==3669==ABORTING
```

**Environment**
 - Vim-8.1.1364 huge (asan build)
 - OS: xubuntu-18.04 x86_64

**Comment by dpelle** [comment]
The bug has been closed and vim-8.1.1387 was meant to fix this.

However, I can still reproduce the same crash with vim-8.1.1387.

I also see that the test added by vim-8.1.1387 actually did not trigger
the crash with asan, i.e. this script did not trigger the crash prior
to vim-8.1.1387:

```
call prop_type_add('comment', {'highlight': 'Search'})
new
call prop_add(1, 1, {'type': 'comment'})
close
```

But this script did and still triggers the crash even after vim-8.1.1387:
```
call prop_type_add("xxx", {})'
call prop_add(1, 1, {"type": "xxx"})
next X
```

**Comment by brammool** [comment]
Dominique wrote:

> The bug has been closed and vim-8.1.1387 was meant to fix this.
> 
> However, I can still reproduce the same crash with vim-8.1.1387.
> 
> I also see that the test added by vim-8.1.1387 actually did not trigger
> the crash with asan, i.e. this script did not trigger the crash prior
> to vim-8.1.1387:
> 
> ```
> call prop_type_add('comment', {'highlight': 'Search'})
> new
> call prop_add(1, 1, {'type': 'comment'})
> close
> ```
> 
> But this script did and still triggers the crash even after vim-8.1.1387:
> ```
> call prop_type_add("xxx", {})'
> call prop_add(1, 1, {"type": "xxx"})
> next X
> ```

I did not manage to trigger the problem in a test.  It seems related to
startup not being done yet.

Did you mean to add a trailing quote in the first line?

I did see the problem with valgrind before, but not after the fix.
I'm using:

valgrind --tool=memcheck --leak-check=yes --num-callers=25 --log-file=valgrind ./vim --clean -S /tmp/test.vim

If you can reproduce the problem in src/testdir/test_textprop.vim that
would be best.

-- 
"So this is it," said Arthur, "we are going to die."
"Yes," said Ford, "except...no!  Wait a minute!"  He suddenly lunged across
the chamber at something behind Arthur's line of vision.  "What's this
switch?" he cried.
"What?   Where?" cried Arthur, twisting around.
"No, I was only fooling," said Ford, "we are going to die after all."
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dpelle** [comment]
> Did you mean to add a trailing quote in the first line?

No, my mistake. Sorry, the quote should not be there.

> If you can reproduce the problem in src/testdir/test_textprop.vim
> that would be best.

I've just created a PR (https://github.com/vim/vim/pull/4428 ) which
should trigger this crash with asan in Travis CI.  At least on my
machine, the added test causes a crash with "make test_textprop"
when building with asan.

To @brammool : can't you build with asan?  If you want to
reproduce it, it should only be a matter of rebuilding vim with
asan, i.e.  with one line commented out and then running
"cd testdir ; make test_textprop":
```
$ git diff Makefile
diff --git a/src/Makefile b/src/Makefile
index ff5ae1016..1b1e4250f 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -689,7 +689,7 @@ LINT_OPTIONS = -beprxzF
 # address sanitizer or with the undefined sanitizer.  Works with gcc and
 # clang.  May make Vim twice as slow.  Errors reported on stderr.
 # More at: https://code.google.com/p/address-sanitizer/
-#SANITIZER_CFLAGS = -g -O0 -fsanitize=address -fno-omit-frame-pointer
+SANITIZER_CFLAGS = -g -O0 -fsanitize=address -fno-omit-frame-pointer
 #SANITIZER_CFLAGS = -g -O0 -fsanitize=undefined -fno-omit-frame-pointer
 SANITIZER_LIBS = $(SANITIZER_CFLAGS)
```

**Comment by dpelle** [comment]
The bug can be detected with valgrind as well, if we make this change,
to  dynamically allocate an empty string rather than using global data.
I'm not suggesting to checkin this change of course, it's just to help
understanding the bug:
```
diff --git a/src/memline.c b/src/memline.c
index 35b524e6b..9f1e53187 100644
--- a/src/memline.c
+++ b/src/memline.c
@@ -2578,8 +2578,14 @@ errorret:
     if (lnum <= 0)                     /* pretend line 0 is line 1 */
        lnum = 1;
 
+    static char* empty = NULL;
+    if (empty == NULL)
+    {
+       empty = strdup("");
+    }
+
     if (buf->b_ml.ml_mfp == NULL)      /* there are no lines */
-       return (char_u *)"";
+       return (char_u *)empty;
 
     /*
      * See if it is the same line as requested last time.
```

```
$ valgrind ./vim --clean \
   -c 'call prop_type_add("xxx", {})' \
   -c 'call prop_add(1, 1, {"type": "xxx"})' \
   -c 'next X' 2> valgrind.log

$ cat valgrind.log
==6519== Memcheck, a memory error detector
==6519== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==6519== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==6519== Command: ./vim --clean -c call\ prop_type_add("xxx",\ {}) -c call\ prop_add(1,\ 1,\ {"type":\ "xxx"}) -c next\ X
==6519== 
==6519== Invalid read of size 8
==6519==    at 0x4C367E0: memmove (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==6519==    by 0x21353E: memmove (string_fortified.h:40)
==6519==    by 0x21353E: vim_memsave (misc2.c:1312)
==6519==    by 0x2EF876: u_save_line (undo.c:373)
==6519==    by 0x2F173B: u_savecommon (undo.c:702)
==6519==    by 0x1985CC: do_ecmd (ex_cmds.c:4175)
==6519==    by 0x1A2F5E: do_argfile (ex_cmds2.c:1928)
==6519==    by 0x1B4040: do_one_cmd (ex_docmd.c:2496)
==6519==    by 0x1B4040: do_cmdline (ex_docmd.c:991)
==6519==    by 0x34EE2F: exe_commands (main.c:2968)
==6519==    by 0x34EE2F: vim_main2 (main.c:797)
==6519==    by 0x1453DE: main (main.c:444)
==6519==  Address 0x100f3798 is 7 bytes after a block of size 1 alloc'd
==6519==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==6519==    by 0x8E0D9B9: strdup (strdup.c:42)
==6519==    by 0x205D4B: ml_get_buf (memline.c:2584)
==6519==    by 0x20E3A1: plines_win_nofold (misc1.c:938)
==6519==    by 0x20E481: plines_win_nofill (misc1.c:921)
==6519==    by 0x217C4C: curs_rows (move.c:765)
==6519==    by 0x219B74: curs_columns (move.c:963)
==6519==    by 0x301304: scroll_to_fraction (window.c:5935)
==6519==    by 0x30151C: frame_new_height (window.c:2917)
==6519==    by 0x303A39: shell_new_rows (window.c:4934)
==6519==    by 0x2D8B47: win_new_shellsize (term.c:3360)
==6519==    by 0x286396: screenalloc (screen.c:8765)
...snip...
```

**Comment by brammool** [comment]
Dominique wrote:

> The bug can be detected with valgrind as well, if we make this change,
> to  dynamically allocate an empty string rather than using global data.
> I'm not suggesting to checkin this change of course, it's just to help
> understanding the bug:
> ```
> diff --git a/src/memline.c b/src/memline.c
> index 35b524e6b..9f1e53187 100644
> --- a/src/memline.c
> +++ b/src/memline.c
> @@ -2578,8 +2578,14 @@ errorret:
>      if (lnum <= 0)                     /* pretend line 0 is line 1 */
>         lnum = 1;
>  
> +    static char* empty = NULL;
> +    if (empty == NULL)
> +    {
> +       empty = strdup("");
> +    }
> +
>      if (buf->b_ml.ml_mfp == NULL)      /* there are no lines */
> -       return (char_u *)"";
> +       return (char_u *)empty;
>  
>      /*
>       * See if it is the same line as requested last time.
> ```

Thanks, that actually already points me to what the problem is:
ml_line_len is not set if returning here.

> ```
> $ valgrind ./vim --clean \
>    -c 'call prop_type_add("xxx", {})' \
>    -c 'call prop_add(1, 1, {"type": "xxx"})' \
>    -c 'next X' 2> valgrind.log
> 
> $ cat valgrind.log
> ==6519== Memcheck, a memory error detector
> ==6519== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
> ==6519== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
> ==6519== Command: ./vim --clean -c call\ prop_type_add("xxx",\ {}) -c call\ prop_add(1,\ 1,\ {"type":\ "xxx"}) -c next\ X
> ==6519== 
> ==6519== Invalid read of size 8
> ==6519==    at 0x4C367E0: memmove (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
> ==6519==    by 0x21353E: memmove (string_fortified.h:40)
> ==6519==    by 0x21353E: vim_memsave (misc2.c:1312)
> ==6519==    by 0x2EF876: u_save_line (undo.c:373)
> ==6519==    by 0x2F173B: u_savecommon (undo.c:702)
> ==6519==    by 0x1985CC: do_ecmd (ex_cmds.c:4175)
> ==6519==    by 0x1A2F5E: do_argfile (ex_cmds2.c:1928)
> ==6519==    by 0x1B4040: do_one_cmd (ex_docmd.c:2496)
> ==6519==    by 0x1B4040: do_cmdline (ex_docmd.c:991)
> ==6519==    by 0x34EE2F: exe_commands (main.c:2968)
> ==6519==    by 0x34EE2F: vim_main2 (main.c:797)
> ==6519==    by 0x1453DE: main (main.c:444)
> ==6519==  Address 0x100f3798 is 7 bytes after a block of size 1 alloc'd
> ==6519==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
> ==6519==    by 0x8E0D9B9: strdup (strdup.c:42)
> ==6519==    by 0x205D4B: ml_get_buf (memline.c:2584)
> ==6519==    by 0x20E3A1: plines_win_nofold (misc1.c:938)
> ==6519==    by 0x20E481: plines_win_nofill (misc1.c:921)
> ==6519==    by 0x217C4C: curs_rows (move.c:765)
> ==6519==    by 0x219B74: curs_columns (move.c:963)
> ==6519==    by 0x301304: scroll_to_fraction (window.c:5935)
> ==6519==    by 0x30151C: frame_new_height (window.c:2917)
> ==6519==    by 0x303A39: shell_new_rows (window.c:4934)
> ==6519==    by 0x2D8B47: win_new_shellsize (term.c:3360)
> ==6519==    by 0x286396: screenalloc (screen.c:8765)
> ...snip...
> ```

I do not get this error.  As mentioned in another message, when I run
this I don't get to u_savecommon().

-- 
Tips for aliens in New York: Land anywhere.  Central Park, anywhere.
No one will care or indeed even notice.
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
Dominique wrote:

> > Did you mean to add a trailing quote in the first line?
> 
> No, my mistake. Sorry, the quote should not be there.
> 
> > If you can reproduce the problem in src/testdir/test_textprop.vim
> > that would be best.
> 
> I've just created a PR (https://github.com/vim/vim/pull/4428 ) which
> should trigger this crash with asan in Travis CI.  At least on my
> machine, the added test causes a crash with "make test_textprop"
> when building with asan.
> 
> To @brammool : can't you build with asan?  If you want to
> reproduce it, it should only be a matter of rebuilding vim with
> asan, i.e.  with one line commented out and then running
> "cd testdir ; make test_textprop":
> ```
> $ git diff Makefile
> diff --git a/src/Makefile b/src/Makefile
> index ff5ae1016..1b1e4250f 100644
> --- a/src/Makefile
> +++ b/src/Makefile
> @@ -689,7 +689,7 @@ LINT_OPTIONS = -beprxzF
>  # address sanitizer or with the undefined sanitizer.  Works with gcc and
>  # clang.  May make Vim twice as slow.  Errors reported on stderr.
>  # More at: https://code.google.com/p/address-sanitizer/
> -#SANITIZER_CFLAGS = -g -O0 -fsanitize=address -fno-omit-frame-pointer
> +SANITIZER_CFLAGS = -g -O0 -fsanitize=address -fno-omit-frame-pointer
>  #SANITIZER_CFLAGS = -g -O0 -fsanitize=undefined -fno-omit-frame-pointer
>  SANITIZER_LIBS = $(SANITIZER_CFLAGS)
> ```

That never worked for me.  Let's give it another try:

==2904==ERROR: AddressSanitizer failed to allocate 0xdfff0001000 (15392894357504) bytes at address 2008fff7000 (errno: 12)
==2904==ReserveShadowMemoryRange failed while trying to map 0xdfff0001000 bytes. Perhaps you're using ulimit -v
Abort (core dumped)

It tries to allocate more memory than what is available.  And no, I'm
not using ulimit.

-- 
Time is an illusion.  Lunchtime doubly so.
		-- Ford Prefect, in Douglas Adams'
		   "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
