### ISSUE TITLE
Excessive "press enter to continue prompt" due to search stats

### ISSUE THREAD

**Issue by uguu-org** [vim/vim#4413]
**Describe the bug**
The new search stats feature (issue #453 and recently implemented) appears to cause excessive "press ENTER or type command to continue" prompts, because the number on the right appears to be positioned incorrectly.

This happens when typing '*' over identifiers that are 24 characters or longer (e.g. "123456789012345678901234") when window size is 80 columns or less.

**To Reproduce**
Detailed steps to reproduce the behavior:

0. Make sure window is small enough and search stats is shown: set columns=80 shortmess-=S
1. Copy&paste this text to a file.
2. Move cursor over 123456789012345678901234
3. Type *
4. Observe the "press enter to continue" prompt.

**Expected behavior**
There should be no prompt, since there is plenty of space to fit the [2/2] numbers.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/2000051/58217478-d0799880-7cb7-11e9-8e30-4a498adafae1.png)

**Environment (please complete the following information):**
vim 8.1.1363 on Linux.

**Comment by tonymec** [comment]
Try increasing `'cmdheight'`.

With `'cmdheight'` set to 2, I see the count displayed at the end of the command-line, one line below the pattern, but there is no press-ENTER message.

Best regards,
Tony.

**Comment by uguu-org** [comment]
I know I can just increase cmdheight, but I suspect this feature is actually not implemented correctly.  For example, typing * over every word in this message shows a consistent 2 space margin on the right, as opposed to no margin at all (plus a press enter prompt) like the earlier screenshot.  So somehow it's not utilizing the horizontal space correctly for long identifiers.
![screenshot](https://user-images.githubusercontent.com/2000051/58218751-fe151080-7cbc-11e9-8ce9-3b2d8987f5d5.png)

My current workaround is to just set shortmess+=S to get the old behavior.

**Comment by brammool** [comment]
> **Describe the bug**
> The new search stats feature (issue #453 and recently implemented)
> appears to cause excessive "press ENTER or type command to continue"
> prompts, because the number on the right appears to be positioned
> incorrectly.
> 
> This happens when typing '*' over identifiers that are 24 characters
> or longer (e.g. "123456789012345678901234") when window size is 80
> columns or less.
> 
> 
> **To Reproduce**
> Detailed steps to reproduce the behavior:
> 
> 0. Make sure window is small enough and search stats is shown: set columns=80 shortmess-=S
> 1. Copy&paste this text to a file.
> 2. Move cursor over 123456789012345678901234
> 3. Type *
> 4. Observe the "press enter to continue" prompt.
> 
> **Expected behavior**
> There should be no prompt, since there is plenty of space to fit the [2/2] numbers.
> 
> **Screenshots**
> ![screenshot](https://user-images.githubusercontent.com/2000051/58217478-d0799880-7cb7-11e9-8e30-4a498adafae1.png)
> 
> **Environment (please complete the following information):**
> vim 8.1.1363 on Linux.

I cannot reproduce it.  Please start with "vim --clean" and describe all
the steps.  You can use an 80 character wide terminal.

-- 
Q: What is the difference between open-source and commercial software?
A: If you have a problem with commercial software you can call a phone
   number and they will tell you it might be solved in a future version.
   For open-source software there isn't a phone number to call, but you
   get the solution within a day.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by uguu-org** [comment]
vim --clean doesn't reproduce for me either, probably because shortmess defaults to filnxToOS.  Minimal deviation from --clean to reproduce the behavior is
set shortmess-=T
set shortmess-=S
![screenshot](https://user-images.githubusercontent.com/2000051/58292693-1d707400-7d77-11e9-9606-6e5fa95a62ef.gif)

**Comment by chdiza** [comment]
I can reproduce it.

**Comment by uguu-org** [comment]
Works for me now, thanks!
