### ISSUE TITLE
Error detected while processing function <SNR>113_NetrwBrowseChgDir:

### ISSUE THREAD

**Issue by aaron-goshine** [vim/vim#442]
Error detected while processing function <SNR>113_NetrwBrowseChgDir:
seems like the latest version of vim is have problems with the NetrwBrowserChangeDir..
Possible triggered by  `set autochdir`

**Comment by mattn** [comment]
What error did you get? could you please show me the stacktrace?

**Comment by aaron-goshine** [comment]
Error detected while processing function <SNR>86_LocalBrowse[30]..netrw#LocalBrowseCheck[21]..<SNR>113_NetrwBrowse[233]..<SNR>113_PerformListing[195]..<SNR>113_NetrwWideListing:
line   64:
E31: No such mapping
Error detected while processing function <SNR>86_LocalBrowse[30]..netrw#LocalBrowseCheck[21]..<SNR>113_NetrwBrowse[233]..<SNR>113_PerformListing[195]..<SNR>113_NetrwWideListing:
line   67:
E31: No such mapping
Pattern not found: @$
Executing BufAdd Auto commands for "*"
autocommand cal s:record(expand('<abuf>', 1))

**Comment by aaron-goshine** [comment]
I am looking through my plugins maybe one of then is acting up

**Comment by mattn** [comment]
are you modifying verbose option?

```
sil! nunmap <buffer> w
```

This command do with `silent!` option. so you should not get message, I guess.

**Comment by aaron-goshine** [comment]
fchdir() to previous dir
`Error detected while processing function <SNR>19_LocalBrowse[30]..netrw#LocalBrowseCheck[21]..<SNR>28_NetrwBrowse[233]..<SNR>28_PerformListing[220]..<SNR>28_NetrwOptionRestore:
line   86:
`

**Comment by chrisbra** [comment]
What follows? The stack trace is incomplete. In any case, this is not a vim bug, closing as invalid. Please check with Dr. Chip.
