### ISSUE TITLE
:redraw doesn't work after :echon with GTK 3

### ISSUE THREAD

**Issue by lilydjwg** [vim/vim#4420]
**Describe the bug**
calling `:redraw` after `:echon` a partial line doesn't make that text visible to user with GTK 3 GUI.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `gvim --clean`
2. Put the following content in `t.vim`:
```vim
echon "test..."
redraw
sleep 1
echo "done"
```
3. Run `:so t.vim`
4. It shows `:so t.vim` and after one second `done`.

**Expected behavior**
It shows `test...` and after one second `test...done`.

**Environment (please complete the following information):**
 - Vim version 8.1.1359
 - OS: Arch Linux
 - Terminal: GTK 3 GUI

**Additional context**
With GTK 2 GUI it works as expected.

I have a command requesting the Internet. I want to show some status text before it's done.

**Comment by brammool** [comment]
You need to swap the "echo" and "echon" to make it work without the "redraw".
With the "redraw" it will never work, it resets the message column.
