### ISSUE TITLE
Up and Down key don't work on Vim terminal bash.

### ISSUE THREAD

**Issue by irreallich** [vim/vim#4421]
**Describe the bug**
Up and Down key don't work on Vim terminal bash.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run vim in putty terminal
2. use :term to open a terminal
3. int t mode , input up or down key 
4. can't get last of next shell cmd in shell 
    use message cmd in vim cmd line and get the following log
E21: Cannot make changes, 'modifiable' is off

**Expected behavior**
it should display last or next shell cmd when  press up&down key on shell

**Screenshots**
If applicable, copy/paste the text or add screenshots to help explain your problem.

**Environment (please complete the following information):**
:version
VIM - Vi IMproved 8.1 (2018 May 18, compiled May 15 2019 09:50:32)
Included patches: 1-1332
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl               +clientserver      +diff              +folding           +libcall           -mouse_gpm         +packages          +ruby              +termguicolors     +virtualedit       +xpm
+arabic            +clipboard         +digraphs          -footer            +linebreak         -mouse_jsbterm     +path_extra        +scrollbind        +terminal          +visual            +xsmp_interact
+autocmd           +cmdline_compl     +dnd               +fork()            +lispindent        +mouse_netterm     +perl              +signs             +terminfo          +visualextra       +xterm_clipboard
+autochdir         +cmdline_hist      -ebcdic            +gettext           +listcmds          +mouse_sgr         +persistent_undo   +smartindent       +termresponse      +viminfo           -xterm_save
-autoservername    +cmdline_info      +emacs_tags        -hangul_input      +localmap          -mouse_sysmouse    +postscript        +startuptime       +textobjects       +vreplace
+balloon_eval      +comments          +eval              +iconv             +lua               +mouse_urxvt       +printer           +statusline        +textprop          +wildignore
+balloon_eval_term +conceal           +ex_extra          +insert_expand     +menu              +mouse_xterm       +profile           -sun_workshop      +timers            +wildmenu
+browse            +cryptv            +extra_search      +job               +mksession         +multi_byte        -python            +syntax            +title             +windows
++builtin_terms    +cscope            -farsi             +jumplist          +modify_fname      +multi_lang        +python3           +tag_binary        +toolbar           +writebackup
+byte_offset       +cursorbind        +file_in_path      +keymap            +mouse             -mzscheme          +quickfix          -tag_old_static    +user_commands     +X11
+channel           +cursorshape       +find_in_path      +lambda            +mouseshape        +netbeans_intg     +reltime           -tag_any_white     +vartabs           -xfontset
+cindent           +dialog_con_gui    +float             +langmap           +mouse_dec         +num64             +rightleft         -tcl               +vertsplit         +xim
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-
1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/incl
ude/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16   -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0
 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -ldl  -L/us
r/lib -llua5.1 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.26/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -lpt
hread -ldl -lutil -lm  -lruby-2.5 -lpthread -lgmp -ldl -lcrypt -lm

 - OS: [e.g. Linux  4.18.0-20-generic #21~18.04.1-Ubuntu SMP Wed May 8 08:43:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux]
 - Terminal: [e.g. putty bash] 
**Additional context**

**Comment by chrisbra** [comment]
This works for me. I am always working with vim in putty terminal and it works as expected. What is your $TERM variable from within Vims terminal and outside of Vim? Interestingly, Vim seems to set it to xterm inside the terminal. Anyhow it works for me using either $TERM=xterm or $TERM=putty-256color. Also what putty version? I am using 0.71 (current latest release). Also please check from `vim --clean`

**Comment by irreallich** [comment]
Thanks for your reply and sorry to reply lately. 
I try to run vim without any plugin, it is worked,  so I think it is the issue about my vim plugin.
Thanks.

**Comment by irreallich** [comment]
The follow remap code in vim terminal mode whill cause this issue

     tnoremap <esc>      <c-w>N
I don't know why and is there any other way to map < c - w >N ?

**Comment by k-takata** [comment]
Mapping Esc may cause the problem, because cursor key codes start with Esc.

**Comment by tonymec** [comment]
> The follow remap code in vim terminal mode whill cause this issue
> tnoremap N
> I don't know why and is there any other way to map N ?

`tnoremap N` by itself ought to tell you to what N is remapped in the terminal, or say `No mapping found` if it isn't. Or did you use an `{rhs}` which you didn't mention?

Hint: To avoid having your `<>` codes gobbled up (as "unrecognised HTML") by the github interface, enclose the whole map command in back-quotes. This will display the text inside the back-quotes exactly as you typed it and in a monotype font.

Best regards,
Tony.

**Comment by chrisbra** [comment]
>  tnoremap <esc>      <c-w>N

(re-edited comment to make the mapping appear).

Note, mapping escape is discouraged strongly in Vim, as certain keys might send escape like sequences and this is known to break if `<esc>` is mapped to another key.

**Comment by irreallich** [comment]
> > The follow remap code in vim terminal mode whill cause this issue
> > tnoremap N
> > I don't know why and is there any other way to map N ?
> 
> `tnoremap N` by itself ought to tell you to what N is remapped in the terminal, or say `No mapping found` if it isn't. Or did you use an `{rhs}` which you didn't mention?
> 
> Hint: To avoid having your `<>` codes gobbled up (as "unrecognised HTML") by the github interface, enclose the whole map command in back-quotes. This will display the text inside the back-quotes exactly as you typed it and in a monotype font.
> 
> Best regards,
> Tony.

Hi, Thanks for you info,   I am a newer for github and I am learning.

**Comment by irreallich** [comment]
> > tnoremap       N
> 
> (re-edited comment to make the mapping appear).
> 
> Note, mapping escape is discouraged strongly in Vim, as certain keys might send escape like sequences and this is known to break if `<esc>` is mapped to another key.

Thanks , I will try to use another key to map as  < c - w >N ,  Is there any suggestion about it?

**Comment by ghomem** [comment]
Relevant status:

https://github.com/vim/vim/issues/2216#issuecomment-2407624950
