### ISSUE TITLE
Error detected while processing /usr/local/Cellar/vim/7.4.712_1/share/vim/vim74/ftoff.vim: line   11:

### ISSUE THREAD

**Issue by aaron-goshine** [vim/vim#443]
Error detected while processing /usr/local/Cellar/vim/7.4.712_1/share/vim/vim74/ftoff.vim:
line   11:

**Comment by aaron-goshine** [comment]
Error detected while processing /Users/aaron.goshine/.dotfiles/vim/after/plugin/autoreadwatch.vim:
line

**Comment by chrisbra** [comment]
It would be great when submitting bugs, if you could write, what did you do (write exactly what commands you entered), what happened and what you expect? Just dumping a random and incomplete errormessage isn't going to help anybody much.

So please answer the following questions:
How did you do this? What is the complete error message? What is your `:version` output? Is this reproducible with plain vim without any plugins? Try using with `vim -u NONE -N`. Thanks.

**Comment by mattn** [comment]
as i said in following issue, you probably set verbose option.

https://github.com/vim/vim/issues/442#issuecomment-146471895

**Comment by chrisbra** [comment]
If you reproduce this issue again, please create a new issue and answer all questions raised above. Don't just dump an error message.

(closing as invalid)
