### ISSUE TITLE
Buffer name resolution and simplification

### ISSUE THREAD

**Issue by memeplex** [vim/vim#444]
I have suggested some workarounds at the bottom of this thread:

https://groups.google.com/forum/#!topic/vim_use/Vq0z2DJH2So

but, nevertheless, I think the behavior is bizarre and specially confusing when using the quickfix list.

Why not always make the buffer name relative to the current working directory?

**Comment by vim-ml** [comment]
(Sorry, I accidentaly submit the issue in github and it was half sent here. The complete text follows.).

I have suggested some workarounds at the bottom of this thread:

https://groups.google.com/forum/#!topic/vim_use/Vq0z2DJH2So

but, nevertheless, I think the behavior is bizarre and specially confusing when using the quickfix list.

Why not always make the buffer name relative to the current working directory?

**Comment by memeplex** [comment]
I'm closing this one. I provided a better description of the issue in https://github.com/vim/vim/issues/549.
