### ISSUE TITLE
Netrw doesn't enter the directory symbolic link

### ISSUE THREAD

**Issue by yurivict** [vim/vim#445]
When I view the directory (:new .), select symbolic link representing another directory, and hit Enter, vim still stays the original directory.

vim-7.4.891 on FreeBSD-10.2

**Comment by tallysmartins** [comment]
:/ also got the same problem

**Comment by for-coursera** [comment]
Still here. vim-8.0.0066.

**Comment by tallysmartins** [comment]
Up

**Comment by vim-ml** [comment]
On Monday, April 17, 2017 at 9:02:30 PM UTC-5, Tallys Martins wrote:
> Up
> 
> 

Did you try going to Dr. Chip's website at http://www.drchip.org/astronaut/vim/index.html#NETRW to download his latest changes to netrw? If so, what was the result? If that version is still broken, how about the other information he asked for to help debug? Dr. Chip stated he was unable to reproduce, and asked:

* what netrw options, if any, are you using?
* what options are you using other than netrw ones?  acd, in particular,
can sometimes cause difficulties

**Comment by chrisbra** [comment]
seems to be fixed.
