### ISSUE TITLE
listener_add creates strange side effect

### ISSUE THREAD

**Issue by myitcv** [vim/vim#4455]
**Describe the bug**

Using auto-pairs with `autoindent` and `cindent` on an indented block causes a superfluous `}` character to be added/left when a `listener_add` callback has been registered.
 
**To Reproduce**

Start with a fresh setup:

```
$ cd $(mktemp -d)
$ git clone https://github.com/jiangmiao/auto-pairs .vim/pack/plugins/start/auto-pairs
$ cat <<EOD > .vimrc
set nocp
set noswapfile
function EchoChanges(bufnr, start, end, added, changes)
  for l:change in a:changes
    let l:change.lines = getbufline(a:bufnr, l:change.lnum, l:change.end-1+l:change.added)
  endfor
  redir >> /tmp/listener.log | echom a:changes | redir END
endfunction
call listener_add("EchoChanges")
set autoindent
set cindent
EOD
```

Now open Vim:

```
$ HOME=$PWD vi
```

The either:

```
call feedkeys("i{\<CR>if true {\<CR>", "xt")
```

or type the equivalent key sequece. 

You should be left with:

```
{
	if true {
	}
	}
}
```

Notice the superfluous `}` on line 3.

If instead you had done:

```
call feedkeys("iif true {\<CR>", "xt")
```

(i.e. the `if` block not indented), then you get the correct:

```
if true {

}
```

Note that the first problem does not occur if you comment out the following line in the `.vimrc`:

```
call listener_add("EchoChanges")
```

i.e. it's the adding of the listener callback that appears to have some sort of side effect.

**Expected behavior**

As above; no superfluous `}`

**Screenshots**

n/a

**Environment (please complete the following information):**
 - Vim version

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled May 30 2019 12:08:19)
Included patches: 1-1421
Compiled by myitcv@myitcv
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     -tag_old_static
+arabic            -farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    -tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
+balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
+browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           -netbeans_intg     +textprop
+byte_offset       -hangul_input      +num64             +timers
+channel           +iconv             +packages          +title
+cindent           +insert_expand     +path_extra        +toolbar
+clientserver      +job               -perl              +user_commands
+clipboard         +jumplist          +persistent_undo   +vartabs
+cmdline_compl     +keymap            +postscript        +vertsplit
+cmdline_hist      +lambda            +printer           +virtualedit
+cmdline_info      +langmap           +profile           +visual
+comments          +libcall           +python            +visualextra
+conceal           +linebreak         -python3           +viminfo
+cryptv            +lispindent        +quickfix          +vreplace
+cscope            +listcmds          +reltime           +wildignore
+cursorbind        +localmap          +rightleft         +wildmenu
+cursorshape       +lua               -ruby              +windows
+dialog_con_gui    +menu              +scrollbind        +writebackup
+diff              +mksession         +signs             +X11
+digraphs          +modify_fname      +smartindent       -xfontset
+dnd               +mouse             +startuptime       +xim
-ebcdic            +mouseshape        +statusline        +xpm
+emacs_tags        +mouse_dec         -sun_workshop      +xsmp_interact
+eval              -mouse_gpm         +syntax            +xterm_clipboard
+ex_extra          -mouse_jsbterm     +tag_binary        -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/home/myitcv/usr/vim/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16   -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl   -ldl  -L/usr/lib/x86_64-linux-gnu -lluajit-5.1  -L/home/myitcv/.pythons/2.7.15/lib/python2.7/config -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic       
```

- OS: Ubuntu 19.04
- Terminal: XTerm(330)

**Additional context**

n/a

**Comment by brammool** [comment]
Can you still reproduce with some mapping instead of loading that whole plugin?  Need that for a test anyway.

**Comment by myitcv** [comment]
I've tried, but unfortunately no luck. Is there some sort of debug mode we can turn on where Vim logs the actual buffer edits made, I guess the layer below the `listener_add` callbacks? Would that help to give a clue about where things are going wrong?

**Comment by brammool** [comment]
> I've tried, but unfortunately no luck. Is there some sort of debug
> mode we can turn on where Vim logs the actual buffer edits made, I
> guess the layer below the `listener_add` callbacks? Would that help to
> give a clue about where things are going wrong?

The easiest is to add ch_log() calls in the code and rebuild.
Then call ch_logfile() somewhere in your script to start logging.

You can also use gdb to step through, but it's usually more time
consuming, and for asynchronous stuff it doesn't work well.  And if
channels are involved you will get the activity on that added for free.

-- 
Q: Should I clean my house or work on Vim?
A: Whatever contains more bugs.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by myitcv** [comment]
In this case there is no channel based plugin involved. auto-pairs is vimscript only. But I've not been able to reduce that down any further

**Comment by brammool** [comment]
Does this still happen after the fix for #4493 ?

**Comment by myitcv** [comment]
Yes, unfortunately it does (just double-checked). 

I suspect the two are unrelated, but this issue does not rely on/involve any channel-based plugin.

**Comment by brammool** [comment]
I tried, but I cannot reproduce the problem.

**Comment by brammool** [comment]
Wait, if I start Vim with --clean then it does reproduce.

**Comment by puremourning** [comment]
> You can also use gdb to step through, but it's usually more time consuming

FWIW, in case anyone is interested, I have instructions for setting up vim debugging using vimspector https://puremourning.github.io/vimspector-web/demo-setup.html. I tend to just hit F5 and repro my issue. Some people might find this more accessible than gdb directly. I've certainly found it useful for investigations recently.
