### ISSUE TITLE
flicker in popup window

### ISSUE THREAD

**Issue by mattn** [vim/vim#4458]
**Describe the bug**

Updating text with setbufline makes flicker

**To Reproduce**

Download starwars.vim from:
 https://gist.githubusercontent.com/mattn/f37e1145a181224711ca1d8e86d8214a/raw/0afd380e7d82f56da94182e0568e7847b4fd3290/starwars.vim

Download sw1.txt from

https://raw.githubusercontent.com/mattn/vim-starwars/master/resources/sw1.txt

And put sw1.txt on $PWD/resources/sw1.txt

1. Run `vim --clean` (or `gvim --clean`, etc.)
2. so starwars.vim
3. :StarWars

**Expected behavior**

No flicker

**Screenshots**

![screenshot](https://user-images.githubusercontent.com/10111/58645734-e124b100-833e-11e9-8e75-c023b6a4d5f9.gif)

**Environment (please complete the following information):**
 - Vim version 8.1.1421
 - OS: Windows 10 1809
 - Terminal: cmd.exe

**Additional context**

I hope to watch starwars in Vim popup window.

**Comment by mattn** [comment]
It may be better to specify maxheight:20

**Comment by brammool** [comment]
That is to be expected, when there is a popup all text is redrawn every time.
It's part of the remaining work.

**Comment by mattn** [comment]
FYI, if trying on non-popup buffer, it clearly looks fine.

![screenshot](https://user-images.githubusercontent.com/10111/58674524-2ff83800-838b-11e9-9cae-fa29433a2b44.gif)
