### ISSUE TITLE
Problems with paths that includes swedish characters

### ISSUE THREAD

**Issue by OskarPersson** [vim/vim#446]
I've had problems with some plugins when working with paths that includes swedish characters. More info can be found [here](http://vi.stackexchange.com/questions/4951/problems-with-paths-that-includes-swedish-characters).

I have however found a way to fix this by removing [mac_precompose_path in misc1.c](https://github.com/vim/vim/blob/master/src/misc1.c#L10402-L10412). Though this fixes that specific problem, I don't know if something else might be broken because of it. I've created a fork with the change [here](https://github.com/OskarPersson/vim/commit/fe9f796ff33c80cab19625b22905456e50102ba9).

**Comment by erickpaquin** [comment]
@OskarPersson, @k-takata  , I do not see "mac_precompose_path" in the current misc1.c. Does that mean this issue can now be closed officially? Thanks.

**Comment by chrisbra** [comment]
then let's close it, assuming it has been fixed. If you notice any problems, please create a new ticket then please :)
