### ISSUE TITLE
The growing array is potentially slow

### ISSUE THREAD

**Issue by k-takata** [vim/vim#4461]
**Describe the bug**
Currently the growing array (`garray_T`) uses a constant growing size which
is specified by `ga_init2()`.  This is not suitable for some use cases.
Sometimes the calculation order becomes O(n^2).

**To Reproduce**
E.g.

```vim
let j = json_encode(repeat(['a', 'b'], 1000000))
```

This takes about 6 seconds in my environment.  When I increase the repeat
count from 1000000 to 2000000, it takes about 24 seconds.
(This is not a real world use case, though.)

**Expected behavior**
The calculation order of `json_encode()` should be faster than O(n^2).

**Proposal**
One idea to fix this is always growing the array with 1.5x (and at least with
the specified size):
https://bitbucket.org/k_takata/vim-ktakata-mq/src/7d47b619816ec1185544b2adccc5a1edb63b8e19/adjust-ga_grow-size.patch?at=default

When this patch is applied, the above example takes only less than 1 second.

Another idea is growing the array with 1.5x only when the size is negative,
and specify a negative size only if it is critical.  We need to investigate
which part is critical, though (e.g. json_encode()):
https://bitbucket.org/k_takata/vim-ktakata-mq/src/dde538bed5c5a1446176213f2465b4d2b212d8b6/adjust-ga_grow-size.patch?at=default

Nowadays we have large memory, so I don't think it has an impact even if we
use the first idea.  And this might solve some potential performance issues.
What do you think?
 
**Screenshots**
N/A

**Environment:**
 - Vim 8.1.1413
 - Windows 10 1809
 - GUI

**Additional context**
I thought that the problem that `100000ia<Esc>` (inserting 100000 `a`s) is
very slow on Vim might also related this, however, it wasn't related.

**Comment by brammool** [comment]
Ken Takata wrote:

> **Describe the bug**
> Currently the growing array (`garray_T`) uses a constant growing size which
> is specified by `ga_init2()`.  This is not suitable for some use cases.
> Sometimes the calculation order becomes O(n^2).
> 
> **To Reproduce**
> E.g.
> 
> ```vim
> let j = json_encode(repeat(['a', 'b'], 1000000))
> ```
> 
> This takes about 6 seconds in my environment.  When I increase the repeat
> count from 1000000 to 2000000, it takes about 24 seconds.
> (This is not a real world use case, though.)
> 
> **Expected behavior**
> The calculation order of `json_encode()` should be faster than O(n^2).
> 
> **Proposal**
> One idea to fix this is always growing the array with 1.5x (and at least with
> the specified size):
> https://bitbucket.org/k_takata/vim-ktakata-mq/src/7d47b619816ec1185544b2adccc5a1edb63b8e19/adjust-ga_grow-size.patch?at=default
> 
> When this patch is applied, the above example takes only less than 1 second.
> 
> Another idea is growing the array with 1.5x only when the size is negative,
> and specify a negative size only if it is critical.  We need to investigate
> which part is critical, though (e.g. json_encode()):
> https://bitbucket.org/k_takata/vim-ktakata-mq/src/dde538bed5c5a1446176213f2465b4d2b212d8b6/adjust-ga_grow-size.patch?at=default
> 
> Nowadays we have large memory, so I don't think it has an impact even if we
> use the first idea.  And this might solve some potential performance issues.
> What do you think?
>  
> **Screenshots**
> N/A
> 
> **Environment:**
>  - Vim 8.1.1413
>  - Windows 10 1809
>  - GUI
> 
> **Additional context**
> I thought that the problem that `100000ia<Esc>` (inserting 100000 `a`s) is
> very slow on Vim might also related this, however, it wasn't related.


Thanks for looking into this.  Yes, the growsize is set for normal-sized
operations, if the actual size is much bigger it becomes quite
expensive.

Although machines these days have a lot of memory, they can still run
out or make things go very slowly (I recently had a hang even though the
machine has 128 Gbyte).  Adding 50% all the time might be a bit much
when getting in the Mbyte range.  And a bit small when in the lower
range, we might want to double then.

Perhaps something like this:
	up to 100 Kbyte: double
	100 Kbyte - 1 Mbyte: add 50%
	> 1 Mbyte: add 30%

How about that?

-- 
hundred-and-one symptoms of being an internet addict:
68. Your cat always puts viruses on your dogs homepage

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
Bram Moolenaar <vim-dev-github@256bit.org> wrote:

> Ken Takata wrote:
>
> > **Describe the bug**
> > Currently the growing array (`garray_T`) uses a constant growing size which
> > is specified by `ga_init2()`. This is not suitable for some use cases.
> > Sometimes the calculation order becomes O(n^2).
> >
> > **To Reproduce**
> > E.g.
> >
> > ```vim
> > let j = json_encode(repeat(['a', 'b'], 1000000))
> > ```
> >
> > This takes about 6 seconds in my environment. When I increase the repeat
> > count from 1000000 to 2000000, it takes about 24 seconds.
> > (This is not a real world use case, though.)
> >
> > **Expected behavior**
> > The calculation order of `json_encode()` should be faster than O(n^2).
> >
> > **Proposal**
> > One idea to fix this is always growing the array with 1.5x (and at least with
> > the specified size):
> > https://bitbucket.org/k_takata/vim-ktakata-mq/src/7d47b619816ec1185544b2adccc5a1edb63b8e19/adjust-ga_grow-size.patch?at=default
> >
> > When this patch is applied, the above example takes only less than 1 second.
> >
> > Another idea is growing the array with 1.5x only when the size is negative,
> > and specify a negative size only if it is critical. We need to investigate
> > which part is critical, though (e.g. json_encode()):
> > https://bitbucket.org/k_takata/vim-ktakata-mq/src/dde538bed5c5a1446176213f2465b4d2b212d8b6/adjust-ga_grow-size.patch?at=default
> >
> > Nowadays we have large memory, so I don't think it has an impact even if we
> > use the first idea. And this might solve some potential performance issues.
> > What do you think?
> >
> > **Screenshots**
> > N/A
> >
> > **Environment:**
> > - Vim 8.1.1413
> > - Windows 10 1809
> > - GUI
> >
> > **Additional context**
> > I thought that the problem that `100000ia<Esc>` (inserting 100000 `a`s) is
> > very slow on Vim might also related this, however, it wasn't related.
>
>
> Thanks for looking into this. Yes, the growsize is set for normal-sized
> operations, if the actual size is much bigger it becomes quite
> expensive.
>
> Although machines these days have a lot of memory, they can still run
> out or make things go very slowly (I recently had a hang even though the
> machine has 128 Gbyte). Adding 50% all the time might be a bit much
> when getting in the Mbyte range. And a bit small when in the lower
> range, we might want to double then.
>
> Perhaps something like this:
> up to 100 Kbyte: double
> 100 Kbyte - 1 Mbyte: add 50%
> > 1 Mbyte: add 30%
>
> How about that?

I'd say keep it simple and multiply by x1.5.
Geometric growth by a factor x1.5 is enough to ensure O(n)
rather than O(n^2) when growing by constant size.

I recall reading that a growth with factor x1.5  is better
than by a factor x2.0.  There is an explanation here:

https://github.com/facebook/folly/blob/master/folly/docs/FBVector.md

Regards
Dominique

**Comment by vim-ml** [comment]
Dominique wrote:

> Bram Moolenaar <vim-dev-github@256bit.org> wrote:
> 
> > Ken Takata wrote:
> >
> > > **Describe the bug**
> > > Currently the growing array (`garray_T`) uses a constant growing size which
> > > is specified by `ga_init2()`. This is not suitable for some use cases.
> > > Sometimes the calculation order becomes O(n^2).
> > >
> > > **To Reproduce**
> > > E.g.
> > >
> > > ```vim
> > > let j = json_encode(repeat(['a', 'b'], 1000000))
> > > ```
> > >
> > > This takes about 6 seconds in my environment. When I increase the repeat
> > > count from 1000000 to 2000000, it takes about 24 seconds.
> > > (This is not a real world use case, though.)
> > >
> > > **Expected behavior**
> > > The calculation order of `json_encode()` should be faster than O(n^2).
> > >
> > > **Proposal**
> > > One idea to fix this is always growing the array with 1.5x (and at least with
> > > the specified size):
> > > https://bitbucket.org/k_takata/vim-ktakata-mq/src/7d47b619816ec1185544b2adccc5a1edb63b8e19/adjust-ga_grow-size.patch?at=default
> > >
> > > When this patch is applied, the above example takes only less than 1 second.
> > >
> > > Another idea is growing the array with 1.5x only when the size is negative,
> > > and specify a negative size only if it is critical. We need to investigate
> > > which part is critical, though (e.g. json_encode()):
> > > https://bitbucket.org/k_takata/vim-ktakata-mq/src/dde538bed5c5a1446176213f2465b4d2b212d8b6/adjust-ga_grow-size.patch?at=default
> > >
> > > Nowadays we have large memory, so I don't think it has an impact even if we
> > > use the first idea. And this might solve some potential performance issues.
> > > What do you think?
> > >
> > > **Screenshots**
> > > N/A
> > >
> > > **Environment:**
> > > - Vim 8.1.1413
> > > - Windows 10 1809
> > > - GUI
> > >
> > > **Additional context**
> > > I thought that the problem that `100000ia<Esc>` (inserting 100000 `a`s) is
> > > very slow on Vim might also related this, however, it wasn't related.
> >
> >
> > Thanks for looking into this. Yes, the growsize is set for normal-sized
> > operations, if the actual size is much bigger it becomes quite
> > expensive.
> >
> > Although machines these days have a lot of memory, they can still run
> > out or make things go very slowly (I recently had a hang even though the
> > machine has 128 Gbyte). Adding 50% all the time might be a bit much
> > when getting in the Mbyte range. And a bit small when in the lower
> > range, we might want to double then.
> >
> > Perhaps something like this:
> > up to 100 Kbyte: double
> > 100 Kbyte - 1 Mbyte: add 50%
> > > 1 Mbyte: add 30%
> >
> > How about that?
> 
> I'd say keep it simple and multiply by x1.5.
> Geometric growth by a factor x1.5 is enough to ensure O(n)
> rather than O(n^2) when growing by constant size.
> 
> I recall reading that a growth with factor x1.5  is better
> than by a factor x2.0.  There is an explanation here:
> 
> https://github.com/facebook/folly/blob/master/folly/docs/FBVector.md

OK, let's keep it simple.  It would be nice to get some more statistics,
but it probably depends a lot on what is being measured, since it's
difficult to define what is the normal use case.

-- 
hundred-and-one symptoms of being an internet addict:
74. Your most erotic dreams are about cybersex

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
