### ISSUE TITLE
Popup padding & border messed up the buffer

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#4469]
version: vim 8.1.1446
system: debian

reproduce:

```viml
let winid=popup_create(["hello", "world"], {"border":[1,1,1,1], "padding":[1,1,1,1]})
```

result: see the picture below

![mess](https://user-images.githubusercontent.com/3035071/58757211-f8c88900-853a-11e9-80da-0dfb9d3d31d3.png)

**Comment by brammool** [comment]
> version: vim 8.1.1446
> system: debian
> 
> reproduce:
> 
> ```viml
> let winid=popup_create(["hello", "world"], {"border":[1,1,1,1], "padding":[1,1,1,1]})
> ```
> 
> result: see the picture below
> 
> ![mess](https://user-images.githubusercontent.com/3035071/58757211-f8c88900-853a-11e9-80da-0dfb9d3d31d3.png)

I cannot reproduce this, it looks fine for me.  The border and padding
still need to be taken into account for positioning and sizing, but in
the middle of the screen it should just work.

-- 
hundred-and-one symptoms of being an internet addict:
87. Everyone you know asks why your phone line is always busy ...and
    you tell them to send an e-mail.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by skywind3000** [comment]
It seems OK in 8.1.1456.
