### ISSUE TITLE
popup_create doesn't accept empty string or list

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#4470]
Vim: 8.1.1446
system: debian

try:

    let winid = popup_create("", {})

result:

    E714: List required

try:

    let winid = popup_create([], {})

result:

    E714: List required

An empty popup is useful because I want to pre-create some popups (hide by default) and reuse them when needed. This can solve buffer reuse problem.

**Comment by brammool** [comment]
> Vim: 8.1.1446
> system: debian
> 
> try:
> 
>     let winid = popup_create("", {})
> 
> result:
> 
>     E714: List required
> 
> try:
> 
>     let winid = popup_create([], {})
> 
> result:
> 
>     E714: List required
> 
> An empty popup is useful because I want to pre-create some popups
> (hide by default) and reuse them when needed. This can solve buffer
> reuse problem.

I thought that creating an empty popup would be a mistake, but your use
case is valid.

-- 
hundred-and-one symptoms of being an internet addict:
85. Choice between paying Compuserve bill and paying for kids education
    is a no brainer -- although a bit painful for your kids.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
