### ISSUE TITLE
Add digraph for horizontal ellipsis

### ISSUE THREAD

**Issue by YodasWs** [vim/vim#4472]
I would like to request a digraph for the [horizontal ellipsis](https://en.wikipedia.org/wiki/Ellipsis), [U+2026](http://www.fileformat.info/info/unicode/char/2026/index.htm):
`…`

I did see PR #1226 from back 2016, but for some reason it was rejected.

I would like to propose using the digraph `el`, but I am really open to any proposal.

**Comment by tonymec** [comment]
There already is one. Be sure to be in Insert mode, then hit Ctrl-K followed by a comma then a full stop.

Best regards,
Tony.

**Comment by YodasWs** [comment]
> There already is one. Be sure to be in Insert mode, then hit Ctrl-K followed by a comma then a full stop.

I missed that. Thank you!
