### ISSUE TITLE
Does not find Lua 5.3 on Alpine Linux

### ISSUE THREAD

**Issue by blueyed** [vim/vim#4475]
What configure does:

```
configure:5396: checking for lua
configure:5426: result: /usr/bin/lua
configure:5435: checking Lua version
configure:5442: result: 5.3
configure:5458: checking if lua.h can be found in /usr/include
configure:5464: result: no
configure:5466: checking if lua.h can be found in /usr/include/lua5.3
configure:5469: result: yes
configure:5504: checking if link with -L/usr/lib -llua5.3 is sane
configure:5519: gcc -o conftest -g -O2   -L/usr/local/lib conftest.c  -L/usr/lib -llua5.3 >&5
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -llua5.3
collect2: error: ld returned 1 exit status
```

But it should do this:

> gcc -o conftest -g -O2   -L/usr/local/lib conftest.c  -L/usr/lib/lua5.3 -llua

Note that I also had to install a symlink `/usr/bin/lua -> /usr/bin/lua5.3` additionally.

Installing a symlink for the `.so` makes it work, so in total I needed this to make it work:
```
      (cd /usr/bin && ln -s lua5.3 lua)
      (cd /usr/lib && ln -s lua5.3/liblua.so liblua5.3.so)
```

**Comment by mikeslattery** [comment]
This is still an issue.   An update to @blueyed 's workaround for Alpine 3.17.2, without requiring to build:

```sh
apk add vim lua
ln -s /usr/lib/lua5.4/liblua-5.4.so.0 /usr/lib/liblua.so
```

**Comment by brammool** [comment]
Let me adjust the configure script to use the lua library subdirectory if it exists.
I can't try this myself, please reopen this issue if the patch does not fix the problem.
