### ISSUE TITLE
popup borderchars is using east asian ambiguous width letters.

### ISSUE THREAD

**Issue by mattn** [vim/vim#4477]
https://github.com/vim/vim/blob/98fb65cb051f625f4ce291a9f9cdb2e54ac1e688/src/screen.c#L1083-L1088

This makes many problems with multi-byte characters. For example, current implementation does not work correctly on CJK locales.

![image](https://user-images.githubusercontent.com/10111/58771877-7c44b180-85f1-11e9-8023-e7f0a98822e1.png)

I suggest to use ASCII letters.

```
diff --git a/src/screen.c b/src/screen.c
index 37999bbf6..ccae71e6d 100644
--- a/src/screen.c
+++ b/src/screen.c
@@ -1080,12 +1080,12 @@ update_popups(void)
 
 	if (enc_utf8)
 	{
-	    border_char[0] = border_char[2] = 0x2550;
-	    border_char[1] = border_char[3] = 0x2551;
-	    border_char[4] = 0x2554;
-	    border_char[5] = 0x2557;
-	    border_char[6] = 0x255d;
-	    border_char[7] = 0x255a;
+	    border_char[0] = border_char[2] = '-';
+	    border_char[1] = border_char[3] = '|';
+	    border_char[4] = '+';
+	    border_char[5] = '+';
+	    border_char[6] = '+';
+	    border_char[7] = '+';
 	}
 	for (i = 0; i < 8; ++i)
 	    if (wp->w_border_char[i] != 0)
```
![image](https://user-images.githubusercontent.com/10111/58772315-4e606c80-85f3-11e9-8e8b-02acc0756c01.png)

**Comment by k-takata** [comment]
How about using Unicode characters only when ambiwidth=single?

**Comment by k-takata** [comment]
E.g.:

```diff
--- a/src/screen.c
+++ b/src/screen.c
@@ -1078,7 +1078,7 @@ update_popups(void)
 		+ wp->w_height + wp->w_popup_padding[2] + wp->w_popup_border[2];
 	popup_attr = get_wcr_attr(wp);
 
-	if (enc_utf8)
+	if (enc_utf8 && *p_ambw == 's')
 	{
 	    border_char[0] = border_char[2] = 0x2550;
 	    border_char[1] = border_char[3] = 0x2551;
```

**Comment by brammool** [comment]
Yasuhiro Matsumoto wrote:

> https://github.com/vim/vim/blob/98fb65cb051f625f4ce291a9f9cdb2e54ac1e688/src/screen.c#L1083-L1088
> 
> This makes many problems with multi-byte characters. For example, current implementation does not work correctly on CJK locales.
> 
> ![image](https://user-images.githubusercontent.com/10111/58771877-7c44b180-85f1-11e9-8023-e7f0a98822e1.png)
> 
> I suggest to use ASCII letters.

We do want these characters to be single width.  But the ASCII is a bit
ugly.  Aren't there border characters that are single width?


-- 
From "know your smileys":
 ~#:-(	I just washed my hair, and I can't do nuthin' with it.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mattn** [comment]
> Aren't there border characters that are single width?

Unfortunately, it isn't.
