### ISSUE TITLE
Validate generated .desktop files before committing

### ISSUE THREAD

**Issue by wjt** [vim/vim#4480]
**Describe the bug**

`runtime/gvim.desktop` contains duplicate Esperanto translations for GenericName and Comment.

```
~/src/vim/vim$ find -name '*.desktop' | xargs desktop-file-validate 
./runtime/gvim.desktop: error: file contains multiple keys named "GenericName[eo]" in group "Desktop Entry"
./runtime/gvim.desktop: error: file contains multiple keys named "Comment[eo]" in group "Desktop Entry"
```

I see that `src/po/gvim.desktop.in` contains these translations, as well as this comment:

```ini
# The translations should come from the po file. Leave them here for now, they will
# be overwritten by the po file when generating the desktop.file!
```

But evidently they are not *overwritten*: instead, duplicate translations are added. I suggest that the `.in` files should not contain any translations; they should contain only the source strings, and only the `.po` files should contain the translations (#3085).

In the meantime, I suggest adding a step to whatever process generates & commits these files that validates the results, to avoid this recurring again (cf #4313).

**Expected behavior**

The generated `.desktop` files in `runtime/` pass `desktop-file-validate`, and this is verified when they are generated and committed.

**Comment by chrisbra** [comment]
Okay, so how about the following patch:

```patch
diff --git a/src/po/Makefile b/src/po/Makefile
index 6049b497e..0e6879c20 100644
--- a/src/po/Makefile
+++ b/src/po/Makefile
@@ -169,11 +169,13 @@ vim.desktop: vim.desktop.in $(POFILES)
        @echo $(LANGUAGES) | tr " " "\n" |sed -e '/\./d' | sort > LINGUAS
        $(MSGFMT) --desktop -d . --template vim.desktop.in -o vim.desktop
        rm -f LINGUAS
+       if command -v desktop-file-validate; then desktop-file-validate vim.desktop; fi

 gvim.desktop: gvim.desktop.in $(POFILES)
        @echo $(LANGUAGES) | tr " " "\n" |sed -e '/\./d' | sort > LINGUAS
        $(MSGFMT) --desktop -d . --template gvim.desktop.in -o gvim.desktop
        rm -f LINGUAS
+       if command -v desktop-file-validate; then desktop-file-validate gvim.desktop; fi

 update-po: $(LANGUAGES)
```

**Comment by wjt** [comment]
In the case where the file fails validation, that patch will leave `gvim.desktop` on disk, with a newer timestamp than `gvim.desktop.in` or the elements of `$(POFILES)`, so running `make` a second time will not update it and will spuriously succeed. How about something like this (untested):

```make
%.desktop: %.desktop.in $(POFILES)
	@echo $(LANGUAGES) | tr " " "\n" |sed -e '/\./d' | sort > LINGUAS
	$(MSGFMT) --desktop -d . --template %< -o tmp.$@
	rm -f LINGUAS
	if command -v desktop-file-validate; then desktop-file-validate tmp.$@; fi
	mv -f tmp.$@ $@
```

**Comment by chrisbra** [comment]
that is not portable (see https://github.com/vim/vim/commit/12e91862c14a1af44b537d). So how about the following (which also fixes the gvim.desktop.in and removes the esperanto part of it, that is provided by the updated po files):

```patch
diff --git a/src/po/Makefile b/src/po/Makefile
index 6049b497e..cda52d0e4 100644
--- a/src/po/Makefile
+++ b/src/po/Makefile
@@ -151,7 +151,7 @@ prefixcheck:

 clean: checkclean
        rm -f core core.* *.old.po *.mo *.pot sjiscorr
-       rm -f LINGUAS vim.desktop gvim.desktop
+       rm -f LINGUAS vim.desktop gvim.desktop tmp*

 distclean: clean

@@ -167,13 +167,17 @@ $(PACKAGE).pot: ../*.c ../if_perl.xs ../GvimExt/gvimext.cpp ../globals.h ../if_p

 vim.desktop: vim.desktop.in $(POFILES)
        @echo $(LANGUAGES) | tr " " "\n" |sed -e '/\./d' | sort > LINGUAS
-       $(MSGFMT) --desktop -d . --template vim.desktop.in -o vim.desktop
+       $(MSGFMT) --desktop -d . --template vim.desktop.in -o tmpvim.desktop
        rm -f LINGUAS
+       if command -v desktop-file-validate; then desktop-file-validate tmpvim.desktop; fi
+       mv tmpvim.desktop vim.desktop

 gvim.desktop: gvim.desktop.in $(POFILES)
        @echo $(LANGUAGES) | tr " " "\n" |sed -e '/\./d' | sort > LINGUAS
-       $(MSGFMT) --desktop -d . --template gvim.desktop.in -o gvim.desktop
+       $(MSGFMT) --desktop -d . --template gvim.desktop.in -o tmpgvim.desktop
        rm -f LINGUAS
+       if command -v desktop-file-validate; then desktop-file-validate tmpgvim.desktop; fi
+       mv tmpgvim.desktop gvim.desktop

 update-po: $(LANGUAGES)

diff --git a/src/po/gvim.desktop.in b/src/po/gvim.desktop.in
index 7d5234851..b547598e8 100644
--- a/src/po/gvim.desktop.in
+++ b/src/po/gvim.desktop.in
@@ -10,7 +10,6 @@ Comment=Edit text files
 # The translations should come from the po file. Leave them here for now, they will
 # be overwritten by the po file when generating the desktop.file!
 GenericName[da]=Teksteditor
-GenericName[eo]=Tekstoredaktilo
 GenericName[fr]=Éditeur de texte
 GenericName[pl]=Edytor tekstu
 GenericName[is]=Ritvinnsluforrit
@@ -29,7 +28,6 @@ Comment[da]=Rediger tekstfiler
 Comment[el]=Επεξεργασία αρχείων κειμένου
 Comment[en_CA]=Edit text files
 Comment[en_GB]=Edit text files
-Comment[eo]=Redakti tekstajn dosierojn
 Comment[es]=Edita archivos de texto
 Comment[et]=Redigeeri tekstifaile
 Comment[eu]=Editatu testu-fitxategiak
```

**Comment by wjt** [comment]
Wow, I had no idea that `%` patterns are a GNU extension. What you propose looks good to me.

**Comment by chrisbra** [comment]
slightly updated patch, that removes duplicate lines using `awk`:

```patch
diff --git a/src/po/Makefile b/src/po/Makefile
index 6049b497e..8bee36a1d 100644
--- a/src/po/Makefile
+++ b/src/po/Makefile
@@ -151,7 +151,7 @@ prefixcheck:

 clean: checkclean
        rm -f core core.* *.old.po *.mo *.pot sjiscorr
-       rm -f LINGUAS vim.desktop gvim.desktop
+       rm -f LINGUAS vim.desktop gvim.desktop tmp*

 distclean: clean

@@ -167,13 +167,21 @@ $(PACKAGE).pot: ../*.c ../if_perl.xs ../GvimExt/gvimext.cpp ../globals.h ../if_p

 vim.desktop: vim.desktop.in $(POFILES)
        @echo $(LANGUAGES) | tr " " "\n" |sed -e '/\./d' | sort > LINGUAS
-       $(MSGFMT) --desktop -d . --template vim.desktop.in -o vim.desktop
+       $(MSGFMT) --desktop -d . --template vim.desktop.in -o tmpvim.desktop
        rm -f LINGUAS
+       # remove duplicate lines
+       awk '!visited[$$0]++' tmpvim.desktop > tmp2vim.desktop
+       if command -v desktop-file-validate; then desktop-file-validate tmp2vim.desktop; fi
+       mv tmp2vim.desktop vim.desktop

 gvim.desktop: gvim.desktop.in $(POFILES)
        @echo $(LANGUAGES) | tr " " "\n" |sed -e '/\./d' | sort > LINGUAS
-       $(MSGFMT) --desktop -d . --template gvim.desktop.in -o gvim.desktop
+       $(MSGFMT) --desktop -d . --template gvim.desktop.in -o tmpgvim.desktop
        rm -f LINGUAS
+       # remove duplicate lines
+       awk '!visited[$$0]++' tmpgvim.desktop > tmp2gvim.desktop
+       if command -v desktop-file-validate; then desktop-file-validate tmp2gvim.desktop; fi
+       mv tmp2gvim.desktop gvim.desktop

 update-po: $(LANGUAGES)

diff --git a/src/po/gvim.desktop.in b/src/po/gvim.desktop.in
index 7d5234851..b547598e8 100644
--- a/src/po/gvim.desktop.in
+++ b/src/po/gvim.desktop.in
@@ -10,7 +10,6 @@ Comment=Edit text files
 # The translations should come from the po file. Leave them here for now, they will
 # be overwritten by the po file when generating the desktop.file!
 GenericName[da]=Teksteditor
-GenericName[eo]=Tekstoredaktilo
 GenericName[fr]=Éditeur de texte
 GenericName[pl]=Edytor tekstu
 GenericName[is]=Ritvinnsluforrit
@@ -29,7 +28,6 @@ Comment[da]=Rediger tekstfiler
 Comment[el]=Επεξεργασία αρχείων κειμένου
 Comment[en_CA]=Edit text files
 Comment[en_GB]=Edit text files
-Comment[eo]=Redakti tekstajn dosierojn
 Comment[es]=Edita archivos de texto
 Comment[et]=Redigeeri tekstifaile
 Comment[eu]=Editatu testu-fitxategiak
```

**Comment by brammool** [comment]
Christian wrote:

> that is not portable (see https://github.com/vim/vim/commit/12e91862c14a1af44b537d). So how about the following (which also fixes the gvim.desktop.in and removes the esperanto part of it, that is provided by the updated po files):
> 
> ```patch
> diff --git a/src/po/Makefile b/src/po/Makefile
> index 6049b497e..cda52d0e4 100644
> --- a/src/po/Makefile
> +++ b/src/po/Makefile
> @@ -151,7 +151,7 @@ prefixcheck:
> 
>  clean: checkclean
>         rm -f core core.* *.old.po *.mo *.pot sjiscorr
> -       rm -f LINGUAS vim.desktop gvim.desktop
> +       rm -f LINGUAS vim.desktop gvim.desktop tmp*
> 
>  distclean: clean
> 
> @@ -167,13 +167,17 @@ $(PACKAGE).pot: ../*.c ../if_perl.xs ../GvimExt/gvimext.cpp ../globals.h ../if_p
> 
>  vim.desktop: vim.desktop.in $(POFILES)
>         @echo $(LANGUAGES) | tr " " "\n" |sed -e '/\./d' | sort > LINGUAS
> -       $(MSGFMT) --desktop -d . --template vim.desktop.in -o vim.desktop
> +       $(MSGFMT) --desktop -d . --template vim.desktop.in -o tmpvim.desktop
>         rm -f LINGUAS
> +       if command -v desktop-file-validate; then desktop-file-validate tmpvim.desktop; fi
> +       mv tmpvim.desktop vim.desktop

I don't know about that "command -v" syntax.  It appears to work, but is
it portable?


-- 
From "know your smileys":
 :-F	Bucktoothed vampire with one tooth missing

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
> I don't know about that "command -v" syntax. It appears to work, but is it portable

according to https://unix.stackexchange.com/a/85250/303213 one should use `command -v` in bourne like shells and avoid which.

**Comment by brammool** [comment]
Christian wrote:

> slightly updated patch, that removes duplicate lines using `awk`:

I rather have it fail than silently remove duplicate lines.


-- 
I AM THANKFUL...
...for the taxes that I pay because it means that I am employed.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
Thanks for including the patch, but the duplicate lines are still in the desktops file.

**Comment by brammool** [comment]
> Thanks for including the patch, but the duplicate lines are still in
> the desktops file.

Yeah, I need to update the runtime files.  Done now.
I should update runtime files more often...

-- 
From "know your smileys":
 :.-(	Crying

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
