### ISSUE TITLE
patch 8.1.1375 seems to break the display of the search pattern in the case of set rightleft.

### ISSUE THREAD

**Issue by erw7** [vim/vim#4488]
**Describe the bug**
As of patch 8.1.1375, in the case of `set rightleft`, only one character of the search pattern is displayed.

**To Reproduce**
```
vim -u NORC
:set rightleft
:call setline(1, ['test', 'test', 'test'])
/test
```

**Expected behavior**
The search pattern is displayed on the bottom line with `tset/`.

**Screenshots**
![image](https://user-images.githubusercontent.com/11682285/58924908-919c1600-8780-11e9-928d-70f58ff194eb.png)

**Environment (please complete the following information):**
 - Vim version 8.1.1446
 - OS: N/A
 - Terminal: N/A

**Comment by chrisbra** [comment]
hm, why didn't the test capture that?

**Comment by erw7** [comment]
> hm, why didn't the test capture that?

This problem only occurs with `set shortmess+=S`. And in that case, it is only tested that search stat information is not displayed.

https://github.com/vim/vim/blob/32e1977012912cd5d7bc762dd41197bc3f1a1370/src/testdir/test_search_stat.vim#L31-L37

https://github.com/vim/vim/blob/32e1977012912cd5d7bc762dd41197bc3f1a1370/src/testdir/test_search_stat.vim#L61-L94

**Comment by chrisbra** [comment]
Ah, it only happens for when the search stat is not active. Did miss that, yes that is correct. And thanks for adding an additional test to #4489
