### ISSUE TITLE
Error Log should display some more details. or a verbose level for error log

### ISSUE THREAD

**Issue by gu-fan** [vim/vim#449]
when debugging. it's not easy sometime to track errors.

so the file name , line nr, buffer , script name script nr ,may should be displayed

**Comment by chrisbra** [comment]
please be more specific. What do you do, what do you expect, what does not work.

I think, this might be better suited on vim-use rather than opening an issue here.

**Comment by chrisbra** [comment]
unclear what is asked for. closing
