### ISSUE TITLE
listener_add created callback should contain two changes?

### ISSUE THREAD

**Issue by myitcv** [vim/vim#4490]
**Describe the bug**

Consider the following `.vimrc`:

```
set nocp
set noswapfile
function EchoChanges(bufnr, start, end, added, changes)
  redir >> /tmp/listener.log | echom a:changes | redir END
endfunction
call listener_add("EchoChanges")
```

Create a simple file, `input`:

```
Line 1
```

Open Vim and call:

```
call feedkeys("o\<CR>", "xt")
```

This results in the following log lines:

```
[{'lnum': 2, 'col': 1, 'added': 2, 'end': 3}]
```

I think the `o` change here needs to be invalidated by the the `<CR>` that follows, hence we should see this as two changes:

```
[{'lnum': 2, 'col': 1, 'added': 1, 'end': 2}, {'lnum': 2, 'col': 1, 'added': 1, 'end': 3}]
```

The likelihood of this happening in practice could be low, but I just found it as part of a test I was trying to write on something totally unrelated, so raising for completeness.

**To Reproduce**

As above

**Expected behavior**

As above.

**Screenshots**

n/a

**Environment (please complete the following information):**
 - Vim version

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled May 30 2019 12:08:19)
Included patches: 1-1421
Compiled by myitcv@myitcv
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     -tag_old_static
+arabic            -farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    -tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
+balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
+browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           -netbeans_intg     +textprop
+byte_offset       -hangul_input      +num64             +timers
+channel           +iconv             +packages          +title
+cindent           +insert_expand     +path_extra        +toolbar
+clientserver      +job               -perl              +user_commands
+clipboard         +jumplist          +persistent_undo   +vartabs
+cmdline_compl     +keymap            +postscript        +vertsplit
+cmdline_hist      +lambda            +printer           +virtualedit
+cmdline_info      +langmap           +profile           +visual
+comments          +libcall           +python            +visualextra
+conceal           +linebreak         -python3           +viminfo
+cryptv            +lispindent        +quickfix          +vreplace
+cscope            +listcmds          +reltime           +wildignore
+cursorbind        +localmap          +rightleft         +wildmenu
+cursorshape       +lua               -ruby              +windows
+dialog_con_gui    +menu              +scrollbind        +writebackup
+diff              +mksession         +signs             +X11
+digraphs          +modify_fname      +smartindent       -xfontset
+dnd               +mouse             +startuptime       +xim
-ebcdic            +mouseshape        +statusline        +xpm
+emacs_tags        +mouse_dec         -sun_workshop      +xsmp_interact
+eval              -mouse_gpm         +syntax            +xterm_clipboard
+ex_extra          -mouse_jsbterm     +tag_binary        -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/home/myitcv/usr/vim/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16   -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl   -ldl  -L/usr/lib/x86_64-linux-gnu -lluajit-5.1  -L/home/myitcv/.pythons/2.7.15/lib/python2.7/config -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic       
```

- OS: Ubuntu 19.04
- Terminal: XTerm(330)

**Additional context**

**Comment by brammool** [comment]
> **Describe the bug**
> 
> Consider the following `.vimrc`:
> 
> ```
> set nocp
> set noswapfile
> function EchoChanges(bufnr, start, end, added, changes)
>   redir >> /tmp/listener.log | echom a:changes | redir END
> endfunction
> call listener_add("EchoChanges")
> ```
> 
> Create a simple file, `input`:
> 
> ```
> Line 1
> ```
> 
> Open Vim and call:
> 
> ```
> call feedkeys("o\<CR>", "xt")
> ```
> 
> This results in the following log lines:
> 
> ```
> [{'lnum': 2, 'col': 1, 'added': 2, 'end': 3}]
> ```
> 
> I think the `o` change here needs to be invalidated by the the `<CR>` that follows, hence we should see this as two changes:
> 
> ```
> [{'lnum': 2, 'col': 1, 'added': 1, 'end': 2}, {'lnum': 2, 'col': 1, 'added': 1, 'end': 3}]
> ```
> 
> The likelihood of this happening in practice could be low, but I just
> found it as part of a test I was trying to write on something totally
> unrelated, so raising for completeness.
 

This happens because the two entries can be merged.  Perhaps in some
cases changes should not be merged?  Merging is most useful when making
several changes at the same position.  I suppose one can argue that
adding a line is not really at the same position.  Or perhaps a change
to add/remove a line should not be merged with any previous entry?
That would be the simplest.

-- 
A meeting is an event at which the minutes are kept and the hours are lost.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by myitcv** [comment]
> Perhaps in some cases changes should not be merged?

Yes, I think in this situation (at least from my perspective) the reasoning behind why the can't be merged is that the `end` field cannot be used by the consumer in _their_ version of the buffer (i.e. pre change). If instead this were two changes:

```
[{'lnum': 2, 'col': 1, 'added': 1, 'end': 2}, {'lnum': 2, 'col': 1, 'added': 1, 'end': 3}]
```

the first would be processed, at which point the `'end': 3` _would_ be valid (because there are now two lines).

> Or perhaps a change to add/remove a line should not be merged with any previous entry? That would be the simplest.

I defer to you on what's best here 😄  - I struggle to describe my expectations, let alone come up with solutions! But certainly what you suggest sounds like it will work in this case at least.

**Comment by brammool** [comment]
Paul Jolly wrote:

> > Perhaps in some cases changes should not be merged?
> 
> Yes, I think in this situation (at least from my perspective) the
> reasoning behind why the can't be merged is that the `end` field
> cannot be used by the consumer in _their_ version of the buffer (i.e.
> pre change). If instead this were two changes:
> 
> ```
> [{'lnum': 2, 'col': 1, 'added': 1, 'end': 2}, {'lnum': 2, 'col': 1, 'added': 1, 'end': 3}]
> ```
> 
> the first would be processed, at which point the `'end': 3` _would_ be
> valid (because there are now two lines).
> 
> > Or perhaps a change to add/remove a line should not be merged with
> > any previous entry? That would be the simplest.
> 
> I defer to you on what's best here 𐟘„  - I struggle to describe my
> expectations, let alone come up with solutions! But certainly what you
> suggest sounds like it will work in this case at least.

I'll make a patch, we can tune it further.

-- 
Laughing helps. It's like jogging on the inside.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by myitcv** [comment]
> I'll make a patch, we can tune it further.

Thanks - confirmed the patch works for the scenario above. Will report any further such issues as separate issues.
