### ISSUE TITLE
[GVim] Bad interaction between guioptions=! and TerminalOpen

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#4497]
(Previously posted at https://github.com/macvim-dev/macvim/issues/896, where it was suggested that it may affect GVim in general.)

Using MacVim (and possibly other GUI versions of Vim), when external commands are executed in a terminal window and a `TerminalOpen` autocommand is defined, the command may affect the current window.

**To Reproduce**

1. Run `gvim -N -i NONE -u vimrc` where `vimrc` has the following content:

```vim
  set number
  autocmd TerminalOpen * set nonumber
  set guioptions=!
```
3. Type `:!ls` (or any other `:!` command)
4. You should see the line numbers have disappeared from the current window.

I am expecting that the external command is executed in a *different* window, hence options set in the terminal window shouldn't affect the current window, as is the case if you remove `!` from `guioptions`.

 - MacVim 8.1.950
 - OS: macOS 10.14

**Comment by brammool** [comment]
The TerminalWinOpen autocommand was added for this.
