### ISSUE TITLE
Feature-Request:  add `modecolumns` which accompanies `modelines`

### ISSUE THREAD

**Issue by hilbix** [vim/vim#4508]
**Is your feature request related something that is currently hard to do? Please describe.**

Looking at

https://github.com/numirias/security/blob/f885bbf08c5af7e88631300eba0cfe6a52b28ed6/data/2019-06-04_ace-vim-neovim/shell.txt#L1

shows, that it is hard for the unenhanced human eye to spot a `modeline` of `vim` properly.

The problem is, that, in the example, the modeline's ` vim: ` comes so late in the line.  Far later than it is probably expected.  Humans are not good in detecting static patterns at locations they do not expect.

In normal circumstances you rarely need a modeline starting such late in the line.  (Perhaps I am not the standard.  But I never had a need for this, so I did not expect what I saw in the link shown above.  Thanks for finding, reporting and fixing the bug BTW.)

Having `vim:` starting from the 4th column usually should be enough (`# vim:`, `// vim:` and `/* vim:`), which then is much better to detect by humans.  However limiting it at a slightly higher position does do much harm (consider `rem vim:` or `    C vim: ft=fortran`), as long as it is not too high.

**Describe the solution you'd like**

There is setting `modelines` with a default of `5`.

I'd like to see a **similar setting `modecolums`** (or `modeskips` or likewise), perhaps with the same default of `5`.  This setting then limits how many characters to skip max until the SPC from ` vim: ` must be found in the scanned possible modelines.  If set to `0` (or unset?) this means "like today", as it makes few sense to skip 0 characters.

(Please feel free to adapt properly if I mixed something.)

**Describe alternatives you've considered**

No alternatives, except using/writing a plugin.  But this should be in core.

**Additional context**

`modecolums` is not meant to be a security feature.

--
I like `vim`.  But I cannot get rid of `emacs` due to `M-x dissociated-press`

**Comment by brammool** [comment]
I think this is too obscure.   Especially because the effect will be that the modeline will be ignored, and the user has no clue why.  And it doesn't really help for security.
