### ISSUE TITLE
`set previewwindow` doesn't work for popup window

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#4523]
Vim: 8.1.1517
System: Debian 9 

Reproduce

```viml
let winid = popup_create([], {"minwidth": 40, "minheight": 15})
call win_execute(winid, "set previewwindow")
pedit /etc/hosts
```

Expecting result:

Command `pedit` should open `/etc/hosts` in a window with a non-zero `&previewwindow`. As we already set `previewwindow` for the new popup window, the file should be previewed in the popup.

Actuall result:

`previewwindow` in the popup is totally ignored and `pedit` open another preview window.

**Comment by skywind3000** [comment]
Or, can there be a way to display a part of a file in the popup window ??

**Comment by brammool** [comment]
> Or, can there be a way to display a part of a file in the popup window ??

The preview window is an existing concept, I don't plan to change that.

You can easily create a popup showing file content:

	let winid = popup_create(readfile('yourfile.txt'), {})

Although it is probably more useful to show only part of a file.

-- 
hundred-and-one symptoms of being an internet addict:
155. You forget to eat because you're too busy surfing the net.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by skywind3000** [comment]
It would be convenient if `readfile` has additional arguments to specify a line range. useful for big files.

**Comment by andymass** [comment]
> Although it is probably more useful to show only part of a file.

This might be a problem because syntax highlighting might not work on a partial file

**Comment by skywind3000** [comment]
> This might be a problem because syntax highlighting might not work on a partial file

It is possible to apply syntax highlighting on a partial file, see:

```viml
:h syn-sync
```

**Comment by chrisbra** [comment]
> It would be convenient if readfile has additional arguments to specify a line range. useful for big files.

readfile returns a list, you can give additional list indices to limit what will be returned. Or are you worried, that this will take too much memory? Than you might need to pre-process the file first.

**Comment by andymass** [comment]
> It is possible to apply syntax highlighting on a partial file, see:
> :h syn-sync

True.. but isn't it simpler to just display part of an existing buffer?  Similarly, I can imagine someone would want to do `:ptag` in a popup window at the cursor.

**Comment by brammool** [comment]
> > It is possible to apply syntax highlighting on a partial file, see:
> > :h syn-sync
> 
> True.. but isn't it simpler to just display part of an existing
> buffer?  Similarly, I can imagine someone would want to do `:ptag` in
> a popup window at the cursor.

It's easy to specify the first line to display in the popup, I'll add a
property for that.

-- 
You're as much use as a condom machine at the Vatican.
                  -- Rimmer to Holly in Red Dwarf 'Queeg'

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
