### ISSUE TITLE
Out-of-date links to online Vim documentation

### ISSUE THREAD

**Issue by jairlopez** [vim/vim#4527]
According to these commits:
https://github.com/c4rlo/vimhelp/commit/565fe830fa62e2760cfb28975617e469631fb32f
https://github.com/c4rlo/vimhelp/commit/115ce1c1b802ed7a825e032f3a38831730959df2
https://github.com/c4rlo/vimhelp/commit/54bc151a06e231190e7f670d856128ed0296679e

The current URL for the online Vim documentation is https://vimhelp.org

The old links are present in these pages:
* https://www.vim.org/docs.php
* https://github.com/vim/vim/blob/12ee7ff00b91d852e060bb24951d1c94239863eb/runtime/doc/intro.txt#L68
* https://github.com/vim/vim/blob/12ee7ff00b91d852e060bb24951d1c94239863eb/runtime/doc/syntax.txt#L3143

**Comment by brammool** [comment]
The appspot links still work, but linking to vimhelp.org is nicer, thus I'll use that.

**Comment by chrisbra** [comment]
Oh, I didn't know that there exists a `vimhelp.org` domain. I only knew about vimhelp.appsport.com (which still works). Good to know.

**Comment by chrisbra** [comment]
this seems fixed, so closing.
