### ISSUE TITLE
libcanberra is linked with Tiny features build

### ISSUE THREAD

**Issue by valacar** [vim/vim#4531]
**Describe the bug**
The Canberra library is linked in when making a Tiny build (also Normal, and probably Small). In a Tiny build, the sound feature is disabled, so I don't think it's necessary to link with libcanberra which deals with playing sounds and "sound themes" as far as I know.

**To Reproduce**
* Download the Vim source code for at least version 8.1 patch 1502 (I'm using 1524)
* Go to the `vim/src` directory
* Run `make distclean`
* Run `CFLAGS='-O2 -pipe' ./configure --with-features=tiny`
* Run `make -j`
* Run `./vim --version` (or open vim and type :ver), and notice that at the bottom it shows `Linking:` and `-lcanberra` appears.

**Expected behavior**
Expected not to see `-lcanberra` since the sound feature is disabled (-sound). I believe it's only supposed to be in Big and Huge builds.

**Environment:**
 - Vim version 8.1.1524
 - OS: Linux 5.1.4-1-MANJARO
 - Terminal: xterm

**Comment by bukatlib** [comment]
I created a simple patch (attached as text file) that disables libcanberra by default to avoid desktop related dependencies. After configure file is regenerated,  libcanberra can be enabled by passing '--with-libcanberra' option. Maybe it can be extended to consider different build types as well.

The vim can be pached and configure file regenerated by the following commands:
`cd src/`
`patch -p2  -i disable_libcanberra.txt`
`aclocal`
`autoconf`
`../configure ...`

[disable_libcanberra.txt](https://github.com/vim/vim/files/3290818/disable_libcanberra.txt)

**Comment by valacar** [comment]
Thanks  for the patch Bukatlib, it's working as expected now.

**Comment by brammool** [comment]
Libor Bukata wrote:

> I created a simple patch (attached as text file) that disables libcanberra by default to avoid desktop related dependencies. After configure file is regenerated,  libcanberra can be enabled by passing '--with-libcanberra' option. Maybe it can be extended to consider different build types as well.
> 
> The vim can be pached and configure file regenerated by the following commands:
> `cd src/`
> `patch -p2  -i disable_libcanberra.txt`
> `aclocal`
> `autoconf`
> `../configure ...`
> 
> [disable_libcanberra.txt](https://github.com/vim/vim/files/3290818/disable_libcanberra.txt)

Thanks for the suggestion.  Since this is an on/off flag using
AC_ARG_ENABLE() is appropriate.  And it should be used by default for
big and huge features.  I'll make a patch for that, please check it.

-- 
If Apple would build a car...
... it would be powered by the sun, be reliable, five times
as fast and twice as easy to drive; but would only run on
five percent of the roads.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
Configure check added in patch 8.1.1529

**Comment by tonymec** [comment]
At version 8.1.1529 (and later), -lcanberra is seen only in the Big and Huge link command-lines; but does it make a difference, considering that we are linking with `-Wl,--as-needed`? I would have expected the libcanberra to be "not needed" (and therefore not included by the linker) when linking Normal and smaller builds even before 8.1.1529. (When the linker does not support --as-needed, link.sh tries removing libraries one by one until only the needed ones are left.)

**Comment by bukatlib** [comment]
Bram, thank you for the patch. I tested it and it works as expected. Library libcanberra is linked if the huge build is requested. On the other hand, if '--disable-canberra' is passed explicitly, the vim will not use libcanberra and X11 dependencies are avoided. Thank you very much for your work on it.
