### ISSUE TITLE
Consider to change the word movements model

### ISSUE THREAD

**Issue by XVilka** [vim/vim#4533]
Currently Vim interprets the meaning of "word" quite broadly, more in terms of the plain text rather than of any programming or markup language terms. These days Vim is being used mostly for writing programs or markup of some kind. And these use either underscores or a CamelCase for entities naming. And due to the development specifics the movements usually are more useful in terms of these words. There are a few plugins exist, that redefine the standard Vim configuration to be suitable for these scenarios. See [camelcasemotion](http://www.vim.org/scripts/script.php?script_id=1905) and [vim-wordmotion](https://github.com/chaoren/vim-wordmotion).

My suggestion is to make the vim-wordmotion behaviour default one, in the mainline Vim:
```
CamelCaseACRONYMWords_underscore1234
w--->w-->w----->w---->w-------->w->w
e-->e-->e----->e--->e--------->e-->e
b<---b<--b<-----b<----b<--------b<-b
```

**Comment by chrisbra** [comment]
that would be a backwards incompatible change and most likely annoy a lot of users.

**Comment by chrisbra** [comment]
I don't see why we would need to change this, if a plugin already does what you want. After all, that's what a plugin is for (and we don't have to maintain or change the C source).

**Comment by brammool** [comment]
These commands are not going to change.  What I have thought about is having more precise control over what is a word character.  Currently 'iskeyword' is used for many things, you might want to have a separate option for word movement commands.  But it's not been asked for much.

**Comment by XVilka** [comment]
Well, even separating the option from iskeyword would be an improvement.
