### ISSUE TITLE
":wincmd p" is ignored after closing current or previous window, when other windows are visible

### ISSUE THREAD

**Issue by fldef** [vim/vim#4537]
Closing the current or previous window may set `prevwin` to `curwin` or `NULL`, respectively.
There may be other windows that could be used as `prevwin` instead. (See tests below.)

Should `prevwin` point to a valid, different window in these cases?

Vim versions: 8.1.1486, 7.4
OS: Windows 10
Terminals: GUI, Windows console

```vim
func Test_window_prevwin_after_close_current()
  " start with one window, open two more, close the current one.
  split
  split
  close
  call assert_notequal(winnr('#'), winnr()) "fails
  call assert_notequal(winnr('#'), 0)
  let l:prevwin = winnr()
  wincmd p
  call assert_notequal(l:prevwin, winnr())  "fails: jumped to itself
  only!
  bwipe!
endfunc

func Test_window_prevwin_after_close_previous()
  " start with one window, open two more, close the previous one.
  split
  split
  exec winnr('#').'wincmd c'
  call assert_notequal(winnr('#'), winnr())
  call assert_notequal(winnr('#'), 0)      "fails
  let l:prevwin = winnr()
  wincmd p
  call assert_notequal(l:prevwin, winnr()) "fails: can't jump to window 0
  only!
  bwipe!
endfunc
```

**Comment by chrisbra** [comment]
I am not sure. If you close the last accessed window, I would expect that `wincmd p` does not work anymore. Using another window would mean we need to keep track all previous windows and adjust accordingly. And even than it might be confusing to the user. I would leave it as it is currently.
