### ISSUE TITLE
After opening the terminal and a file, you have to close the file two times.

### ISSUE THREAD

**Issue by g-i-o-r-g-i-o** [vim/vim#4539]
**Describe the bug**
If you open a text file, and you also open a vertical split with the terminal, you have to issue twice the command to close the text file.

**To Reproduce**
1. open vim (works also with vim --clean)
2. type "vertical terminal"
3. run a process in the terminal (for example open a file using "less"), but I've noticed that it happens also if you let the terminal sit idle.
4. open a text file in the first split (not the one with terminal)
5. wait a while (maybe 10 minutes)
6. close the text file
7. close the terminal typing "exit"
8. now, and this is wrong, vim opens again the already closed text file...  
9. close again the text file because it didn't close in step

**Expected behavior**
After step 7, vim should go back to the start screen, it makes no sense to open again the last opened file. In my case the start screen is Startify, but this happens also with "vim --clean".
The bugs happens also if you open the text file before opening the terminal, inverting steps 3 and 4.

**Environment (please complete the following information):**
- vim 8.1-473 
- OS: ubuntu 18.10
- terminal: GNOME terminal 3.30.1 Using VTE version 0.54.1 +GNUTLS -PCRE2

**Comment by brammool** [comment]
Yes, in this case it should close the tab page or exit Vim.

**Comment by ppalka-rh** [comment]
Is it now intended that doing e.g.

`:terminal ++curwin ++close git log`

in a single-window session causes vim to exit when the subprocess exits?  I was using this kind of idiom as a better alternative for `:! git log` etc.  Is there any way to restore this original behavior?  I'd want the terminal buffer to close when the subprocess exits, but I'd like it to behave just as if any other buffer was closed in that I'd expect the most recent opened buffer to be reopened in the current window

**Comment by andymass** [comment]
We have ++close and (not ++close). Maybe we should have ++return as well

**Comment by brammool** [comment]
> Is it now intended that doing e.g.
> 
> `:terminal ++curwin ++close git log`
> 
> in a single-window session causes vim to exit when the subprocess
> exits?  I was using this kind of idiom as a better alternative for `:!
> git log` etc.  Is there any way to restore this original behavior?
> I'd want the terminal to exit when the subprocess exits, but I'd like
> it to behave just as if a buffer was closed in that I'd like to go
> back to the most recent opened buffer.

How about using :terminal ++rows=999 ++close git log

The previous behavior was a bit strange, in that it would go to some
other buffer.

-- 
You have heard the saying that if you put a thousand monkeys in a room with a
thousand typewriters and waited long enough, eventually you would have a room
full of dead monkeys.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ppalka-rh** [comment]
Using `++rows=999` instead of `++curwin` works for me -- thank you!
