### ISSUE TITLE
Include a .desktop file

### ISSUE THREAD

**Issue by coldfix** [vim/vim#454]
Hey,

Is it possible to add to the repository a `.desktop` file for vim and gvim similar to the [gvim.desktop](https://projects.archlinux.org/svntogit/packages.git/plain/trunk/gvim.desktop?h=packages/vim) file packaged by archlinux. For the `vim.desktop` one would obviously have to set `Terminal=true`.

I can open a pull request if this makes it any easier. 

Best regards,
Thomas

**Comment by vim-ml** [comment]
Note: My HD crashed this summer, so I lost my address book. I added Steve
Hall's address from memory but I'm not sure it is his current address. If
he has a newer address, please let him and me know.

On Sun, Oct 18, 2015 at 5:25 PM, Thomas G. vim-dev-github@256bit.org
wrote:

> Hey,
> 
> Is it possible to add to the repository a .desktop file for vim and gvim
> similar to the gvim.desktop
> https://projects.archlinux.org/svntogit/packages.git/plain/trunk/gvim.desktop?h=packages/vim
> file packaged by archlinux. For the vim.desktop one would obviously have
> to set Terminal=true.
> 
> I can open a pull request if this makes it any easier.
> 
> Best regards,
> Thomas
> 
> You mean, a desktop icon to launch Console Vim and one to launch gvim? IIUC
> that should be done at install time (by "make install" on Linux), and on
> Windows the different desktop icon used by Windows should be installed. I
> don't know if the current Windows installers (Steve Hall's and Bram's)
> already do this but I do know that on Windows the desktop launch icons are
> not called *.desktop

On the Mac I don't know what is used, or if MacVim already does it.

Best regards,
Tony.

**Comment by coldfix** [comment]
> You mean, a desktop icon to launch Console Vim and one to launch gvim?

Not necessarily a desktop icon - rather a _configuration file describing how a particular program is to be launched, how it appears in menus, etc._ (which is I think linux only?), see here:

http://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#introduction

These files are used by tools like `xdg-open`, `mimeopen` to determine the correct way to open arbitrary files. Furthermore, there are mechanisms to automatically list all available applications for a particular mimetype, such that e.g. firefox can display a choice of several options if you select "Open with.." when downloading a file, etc.

Currently, the archlinux package includes one such desktop entry for gvim, but I'd like to see one for vim too. Their policy is that .desktop files should preferrably be added in the upstream repositories and I think this makes sense to avoid duplication among different distributions.

Thanks for considering,
Thomas

**Comment by brammool** [comment]
Thomas G. wrote:

> Is it possible to add to the repository a `.desktop` file for vim and
> gvim similar to the
> [gvim.desktop](https://projects.archlinux.org/svntogit/packages.git/plain/trunk/gvim.desktop?h=packages/vim)
> file packaged by archlinux. For the `vim.desktop` one would obviously
> have to set `Terminal=true`.
> 
> I can open a pull request if this makes it any easier. 

I assume that file needs to be installed somewhere.
Having a patch for that would be useful.

## 

A fine is a tax for doing wrong.  A tax is a fine for doing well.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
Hi Tony,

On Sun, Oct 18, 2015 at 4:46 PM, Tony Mechelynck <
antoine.mechelynck@gmail.com> wrote:

> Note: My HD crashed this summer, so I lost my address book. I added
> Steve Hall's address from memory but I'm not sure it is his current
> address. If he has a newer address, please let him and me know.

I'm at [digitect dancingpaper com] these days.

On Sun, Oct 18, 2015 at 5:25 PM, Thomas G. vim-dev-github@256bit.org
wrote:

> Is it possible to add to the repository a .desktop file[...]
> 
> > [...] and on Windows the different desktop icon used by Windows
> > should be installed. I don't know if the current Windows
> > installers (Steve Hall's and Bram's) already do this but I do know
> > that on Windows the desktop launch icons are not called *.desktop

The Cream installer uses NSIS to create Start Menu and Desktop icons
for Windows. They are usually not something that can be copied around
because they are OS version/system specific.

Most Linux GUI .desktop file formats are documented on the web. At one
point KDE and GNOME were trying to use a common format but I don't
know how that turned out.

## 

Steve Hall  [ digitect dancingpaper com ]
Cream for Vim  http://cream.SourceForge.net
