### ISSUE TITLE
add support for file uri scheme in quickfix (maven-compiler-plugin error log filename under msys2)

### ISSUE THREAD

**Issue by ex-privia** [vim/vim#4540]
Compilers may log the filename containing the compilation error using file uri scheme (or some abbreviation of it). When this happens %f of errorformat does correctly match the filename as a file uri but then Vim jumps to a new file whose filename is what has been captured in %f instead of the file whose file uri is what has been captured in %f.

This is the case for maven-compiler-plugin under msys2.

An error line like this (where the filename is reported by maven-compiler-plugin with an abbreviated file uri format, that is, without the trailing "file://"):

```
[ERROR] /C:/Users/exprivia/home/programs/msys64/home/exprivia/dev/java/start/src/main/java/com/sergiodegioia/trial/MyClass.java:[3,8] class f is public, should be declared in a file named f.java
```

or with ANSI escape code for colors

```
[[1;31mERROR[m] [1;31m/C:/Users/exprivia/home/programs/msys64/home/exprivia/dev/java/start/src/main/java/com/sergiodegioia/trial/MyClass.java:[3,8] class f is public, should be declared in a file named f.java[m
```

is correctly parsed using this errorformat:

```
set errorformat=%*[^E]%tRROR%*[^\ ]\ %f:[%l\\,%v]\ %m
```

but then vim jumps to a new file named:
```
/C:/Users/exprivia/home/programs/msys64/home/exprivia/dev/java/start/src/main/java/com/sergiodegioia/trial/MyClass.java
```
instead of what under msys2 must be:
```
/c/Users/exprivia/home/programs/msys64/home/exprivia/dev/java/start/src/main/java/com/sergiodegioia/trial/MyClass.java
```
or, equivalently, this:
```
/home/exprivia/dev/java/start/src/main/java/com/sergiodegioia/trial/MyClass.java
```

**Comment by chrisbra** [comment]
> format, that is, without the trailing "file://"):

What File URI are you talking about? I don't see a `file://` section here. Also I wonder is this something that could be fixed by a custom compiler plugin...

**Comment by ex-privia** [comment]
Thanks chrisbra,
no enhancement needed.

In the end my errorformat setting was wrong, neglecting a slash appearing in front of the path to the file in the compiler output (this slash made me think of an abbreviated file uri format without "file://").
But in the end it is enough to declare that slash in the errorformat and what %f captures then is good for Vim to correctly jump to the intended file, even under msys2. 

So the setting for error format for maven-compiler-plugin is:
```
set errorformat=%*[^E]%tRROR%*[^\ ]\ /%f:[%l\\,%v]\ %m
```

Thanks again
