### ISSUE TITLE
:reg command should also show register types

### ISSUE THREAD

**Issue by ayberkydn** [vim/vim#4546]
Getting the type of a register is cumbersome with :call getregtype('a'). Instead, 
:reg command should also show whether the register is linewise or characterwise since the paste behavior is directly dependent to this and it's not clear just from register content. ^J at the and only gives an hint but not explanatory. 

For example, the behavior of these apparently identical registers would be vastly different when it comes to pasting.
:reg 
"a foo
"b foo

Instead, it should show

:reg
"a foo (V)
"b foo (v)

or for terseness, only linewise registers can be shown with extra mark (V).

:reg
"a foo (V)
"b foo

**Comment by chdiza** [comment]
Make a custom command called `:Reg` that does `getregtype` on its argument.

**Comment by ayberkydn** [comment]
> Make a custom command called `:Reg` that does `getregtype` on its argument.

or it can show registers' contents with types.

**Comment by chrisbra** [comment]
So I suppose, this can be achieved by a custom plugin. Closing therefore.

**Comment by brammool** [comment]
Hmm, I think it's worth doing this with :reg, since it's generally useful.

We could add one character to indicate the type.  And leave it out for the most common type.  Would that be characterwise or linewise?

"1     deleted line
"2 c  deleted text
"3 b  deleted block

**Comment by chdiza** [comment]
>  ^J at the and only gives an hint but not explanatory.

If ^J is not "explanatory", then neither will be some other single character.

**Comment by ayberkydn** [comment]
> > ^J at the and only gives an hint but not explanatory.
> 
> If ^J is not "explanatory", then neither will be some other single character.

What I mean is, ^J does not tell you about (character/line)wiseness of a register. You can just fill a characterwise register with ^J at the end of it. 



> Hmm, I think it's worth doing this with :reg, since it's generally useful.
> 
> We could add one character to indicate the type. And leave it out for the most common type. Would that be characterwise or linewise?
> 
> "1 deleted line
> "2 c deleted text
> "3 b deleted block

I think characterwise would be the most common type. Not sure, though.
