### ISSUE TITLE
start_col seems to be wrong for textprop.

### ISSUE THREAD

**Issue by mattn** [vim/vim#4558]
**Describe the bug**

start_col seems to be wrong for textprop.

**To Reproduce**

start with `gvim --clean bug.vim`

```
new
set signcolumn=yes
call setline(1, "\tfoo")
call prop_type_add(1, { 'highlight': 'Error' })
call prop_add(1, 2, {'length': 10, 'type': 1})
```

The first character is tab. So Error highlight must be painted from "f".

![image](https://user-images.githubusercontent.com/10111/59673480-5e379d80-91fc-11e9-9ef9-ec7445d13471.png)

**Expected behavior**

Start from vertical column 4. (since first character is tab: tabstop=4)

**Environment (please complete the following information):**
 - Vim version 8.1.1566
 - OS: Windows 7

**Additional context**

If signcolumn is no, this does not appear wrong.

**Comment by brammool** [comment]
> **Describe the bug**
> 
> start_col seems to be wrong for textprop.
> 
> **To Reproduce**
> 
> start with `gvim --clean bug.vim`
> 
> ```
> new
> set signcolumn=yes
> call setline(1, "\tfoo")
> call prop_type_add(1, { 'highlight': 'Error' })
> call prop_add(1, 2, {'length': 10, 'type': 1})
> ```
> 
> The first character is tab. So Error highlight must be painted from "f".
> 
> ![image](https://user-images.githubusercontent.com/10111/59673480-5e379d80-91fc-11e9-9ef9-ec7445d13471.png)
> 
> **Expected behavior**
> 
> Start from vertical column 4. (since first character is tab: tabstop=4)
> 
> **Environment (please complete the following information):**
>  - Vim version 8.1.1566
>  - OS: Windows 7
> 
> **Additional context**
> 
> If signcolumn is no, this does not appear wrong.

I also see the problem without a signcolumn.  It appears to depend on
the property to start just after a tab.

-- 
hundred-and-one symptoms of being an internet addict:
230. You spend your Friday nights typing away at your keyboard

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
