### ISSUE TITLE
Can there be an option to scroll a popup along with the buffer?

### ISSUE THREAD

**Issue by andymass** [vim/vim#4560]
Many plugins would like to annotate the buffer using a popup, but when the user scrolls, it is difficult to react.  I would say `popup_atcursor` should follow the cursor when using `<c-y>/<c-e>`. 
 I think when the position goes off the screen the popup should exist but not be drawn until that position is on-screen again.  Or perhaps the popup can be hidden or close optonally.

```vim
call popup_create(['foo'], {'scroll': 1})
```

Maybe this would be better as "buffer-positioned" popups instead of screen-positioned?

**Comment by brammool** [comment]
> Many plugins would like to annotate the buffer using a popup, but when
> the user scrolls, it is difficult to react.  I would say
> `popup_atcursor` should follow the cursor when using `<c-y>/<c-e>`. 
>  I think when the position goes off the screen the popup should exist
>  but not be drawn until that position is on-screen again.  Or perhaps
>  the popup can be hidden or close optonally.
> 
> ```vim
> call popup_create(['foo'], {'scroll': 1})
> ```
> 
> Maybe this would be better as "buffer-positioned" popups instead of
> screen-positioned?

I suppose it's not just scrolling, but also inserting/deleting lines.
Thus it would be more like how a text property sticks to a certain
position.  Not sure how much that is to implement...

-- 
hundred-and-one symptoms of being an internet addict:
240. You think Webster's Dictionary is a directory of WEB sites.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
