### ISSUE TITLE
keyword-completion freeze

### ISSUE THREAD

**Issue by ghost** [vim/vim#4572]
**Describe the bug**
With my complete-as-you-type vimscript vim freezes on keyword-completion.

This with loop infinitely:

https://github.com/vim/vim/blob/6c1e1570b1346de0d438fbb991bddab38c228290/src/insexpand.c#L2714

searchit() will always find the same match:

https://github.com/vim/vim/blob/6c1e1570b1346de0d438fbb991bddab38c228290/src/insexpand.c#L2727

Later no break-condition is set.

It is important that `set complete+=k` and `setlocal spell spelllang=en_us` is set, since the problem only happens when dictionary-completion is active. Actually as far as I know everything in the script below is needed.

**To Reproduce**
1. Use the following script, I call it complete.vim

```vim
set nocp
set completeopt=menuone,preview,noinsert
set complete+=k
setlocal spell spelllang=en_us

" Complete if pop-menu is not visible and the current word is at least 2
" keyword-characters log, so dictionary-completion is active.
function! s:CompleteAsYouType()
  if !pumvisible()
    if match(getline('.')[col('.') - 2] . v:char, '\K\k') == 0
      call feedkeys("\<C-n>", 'n')
    endif
  endif
endfunction

autocmd InsertCharPre * call s:CompleteAsYouType()
```
2. Run `vim --clean -u complete.vim`
3. Type:

```
I can believe my eyes

I can
```
4.Vim will freeze with a infinite loop. If you can not trigger the freeze right away, please remove the word `can` and type it again. Also vary in speed.

**Expected behavior**
Vim should not freeze.

**Screenshots**
![vim](https://user-images.githubusercontent.com/1186530/59962903-dd262200-94eb-11e9-8dbb-f808c0a769c4.png)

I also recorded the freeze and a debug session. While recording there were some plugins active, but for all my other tests I only used the code in complete.vim.

https://asciinema.org/a/9l9YqDS68wSkkvSNmn6V2eout

I was using mozillas rr: https://github.com/mozilla/rr

**Environment (please complete the following information):**
 - Build from source: 87652a7e3b9475
 - Also happens with: VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 17 2019 09:09:11) Included patches: 1-1561
 - OS: Linux Fedora 30
 - Terminal: xterm, xfce-term, st

**Additional context**
I created a patch, it fixes the problem and doesn't break anything. Of course I don't know the code-base, so I am not 100% sure that it is ok.

It checks if there was no progress in the search, pos and last_match_pos are the some position, then it breaks the loop.

```cpp
diff --git a/src/insexpand.c b/src/insexpand.c
index fe475a5da..14c5ea0e7 100644
--- a/src/insexpand.c
+++ b/src/insexpand.c
@@ -2835,6 +2835,11 @@ ins_compl_get_exp(pos_T *ini)
                    found_new_match = OK;
                    break;
                }
+
+               if (pos->lnum == last_match_pos.lnum
+                       && pos->col == last_match_pos.col) {
+                   break;
+               }
            }
            p_scs = save_p_scs;
            p_ws = save_p_ws;
```

**Comment by ghost** [comment]
I ran the patch against vims/neovims CI:

* https://travis-ci.org/ganwell/vim/builds/549095035
* https://travis-ci.org/neovim/neovim/builds/549065678

**Comment by brammool** [comment]
> **Describe the bug**
> With my complete-as-you-type vimscript vim freezes on keyword-completion.
> 
> This with loop infinitely:
> 
> https://github.com/vim/vim/blob/6c1e1570b1346de0d438fbb991bddab38c228290/src/insexpand.c#L2714
> 
> searchit() will always find the same match:
> 
> https://github.com/vim/vim/blob/6c1e1570b1346de0d438fbb991bddab38c228290/src/insexpand.c#L2727

searchit() is not supposed to return a match at "pos", unless
SEARCH_START is passec, but it looks like it is not.  Thus this would
hint at a problem inside searchit().  What is the pattern passed to
searchit()?

> Later no break-condition is set.
> 
> It is important that `set complete+=k` and `setlocal spell
> spelllang=en_us` is set, since the problem only happens when
> dictionary-completion is active. Actually as far as I know everything
> in the below is needed.
> 
> **To Reproduce**
> 1. Use the following script I call it complete.vim
> 
> ```vim
> set nocp
> set completeopt=menuone,preview,noinsert
> set complete+=k
> setlocal spell spelllang=en_us
> 
> " Complete if pop-menu is not visible and the current word is at least 2
> " keyword-characters log, so dictionary-completion is active.
> function! s:CompleteAsYouType()
>   if !pumvisible()
>     if match(getline('.')[col('.') - 2] . v:char, '\K\k') == 0
>       call feedkeys("\<C-n>", 'n')
>     endif
>   endif
> endfunction
> 
> autocmd InsertCharPre * call s:CompleteAsYouType()
> ```
> 2. Run `vim --clean -u complete.vim`
> 3. Type:
> 
> ```
> I can believe my eyes
> 
> I can
> ```
> 4.Vim will freeze with a infinite loop. If you can not trigger the freeze right away, please remove the word `can` and type it again. Also vary in speed.
> 
> **Expected behavior**
> Vim should not freeze.
> 
> **Screenshots**
> ![vim](https://user-images.githubusercontent.com/1186530/59962903-dd262200-94eb-11e9-8dbb-f808c0a769c4.png)
> 
> I also recorded the freeze and a debug session. While recording there were some plugins active, but for all my other tests I only used the code in complete.vim.
> 
> https://asciinema.org/a/9l9YqDS68wSkkvSNmn6V2eout
> 
> I was using mozillas rr: https://github.com/mozilla/rr
> 
> **Environment (please complete the following information):**
>  - Build from source: 87652a7e3b9475
>  - Also happens with: VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 17 2019 09:09:11) Included patches: 1-1561
>  - OS: Linux Fedora 30
>  - Terminal: xterm, xfce-term, st
> 
> **Additional context**
> I created a patch, it fixes the problem and doesn't break anything. Of
> course I don't know the code-base, so I am not 100% sure that it is
> ok.
> 
> It checks if there was no progress in the search, pos and
> last_match_pos are the some position, then it breaks the loop.
> 
> ```cpp
> diff --git a/src/insexpand.c b/src/insexpand.c
> index fe475a5da..14c5ea0e7 100644
> --- a/src/insexpand.c
> +++ b/src/insexpand.c
> @@ -2835,6 +2835,11 @@ ins_compl_get_exp(pos_T *ini)
>                     found_new_match = OK;
>                     break;
>                 }
> +
> +               if (pos->lnum == last_match_pos.lnum
> +                       && pos->col == last_match_pos.col) {
> +                   break;
> +               }
>             }
>             p_scs = save_p_scs;
>             p_ws = save_p_ws;
> ```

It looks like it also bails out in the first pass, when compl_started
isn't set.

Please try to find a simple example, and use "vim --clean" to avoid any
plugins interfering.

-- 
hundred-and-one symptoms of being an internet addict:
253. You wait for a slow loading web page before going to the toilet.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ghost** [comment]
> searchit() is not supposed to return a match at "pos", unless
> SEARCH_START is passec, but it looks like it is not.  

You're right. I'll investigate in searchit(), thanks for the hint!

If the keyword-completion does not freeze, searchit() returns a new position:

```
(rr) p *pos
$1 = {
  lnum = 3,
  col = 1,
  coladd = 0
}
(rr) n
2731                    --msg_silent;
(rr) p *pos
$2 = {
  lnum = 1,
  col = 2,
  coladd = 0
}
(rr) p found_new_match
$3 = 1
```

In the freeze case it returns the same position.

```
(rr) p *pos
$1 = {
  lnum = 1,
  col = 2,
  coladd = 0
}
(rr) n
2731                    --msg_silent;
(rr) p *pos
$2 = {
  lnum = 1,
  col = 2,
  coladd = 0
}
(rr)
(rr) p found_new_match
$3 = 1
```

Which should be impossible without SEARCH_START.

> Thus this would
> hint at a problem inside searchit().  What is the pattern passed to
> searchit()?

```
(rr) p compl_pattern
$7 = (char_u *) 0x178b850 "\\<can"
```
I first thought this is wrong and feedkeys has something to do with "\\<" in the compl_pattern.

But without feedkeys:

```vim
set nocp
set completeopt=menuone,preview,noinsert
set complete+=k
setlocal spell spelllang=en_us
```

The pattern is still the same.

```
(rr) p compl_pattern
$1 = (char_u *) 0x2586270 "\\<can"
```

Of course it doesn't freeze without feedkeys. I am still trying to find a example without feedkeys, but I had no luck, yet.

**Comment by ghost** [comment]
A short update. I haven't solved it, but

> > searchit() is not supposed to return a match at "pos", unless
> > SEARCH_START is passec, but it looks like it is not.

> You're right. I'll investigate in searchit(), thanks for the hint!

Actually it can find a match at pos for two reasons:

* SEARCH_COL is not set, so it starts searching at the beginning of the line

* Since we are in the current buffer p_ws is set, I think the search can wrap around (haven't seen any code preventing returning the same pos)

But the main difference between the working case and looping one is:

Working:

```
(rr) p *compl_first_match
$2 = {
  cp_next = 0x0,
  cp_prev = 0x0,
  cp_str = 0x1568760 "can",
  cp_text = {0x0, 0x0, 0x0, 0x0, 0x0},
  cp_fname = 0x0,
  cp_flags = 1,
  cp_number = 0
}
```

Looping:

```cpp
(rr) p *compl_first_match
$2 = {
  cp_next = 0x16327d0,
  cp_prev = 0x0,
  cp_str = 0x178c140 "can",
  cp_text = {0x0, 0x0, 0x0, 0x0, 0x0},
  cp_fname = 0x0,
  cp_flags = 1,
  cp_number = 0
}
(rr) p *compl_first_match->cp_next
$3 = {
  cp_next = 0x0,
  cp_prev = 0x16337b0,
  cp_str = 0x178c180 "can",
  cp_text = {0x0, 0x0, 0x0, 0x0, 0x0},
  cp_fname = 0x0,
  cp_flags = 0,
  cp_number = -1
}
```

The looping case will find two matches for 'can', although this is not possible there is only one instance of 'can' in the ins_buf.

```cpp
(rr) p ml_get_buf(ins_buf, 1, FALSE)
$1 = (char_u *) 0x16d9d9a "I can believe my eyes"
(rr) p ml_get_buf(ins_buf, 2, FALSE)
$2 = (char_u *) 0x16d9d99 ""
(rr) p ml_get_buf(ins_buf, 3, FALSE)
$3 = (char_u *) 0x16d9d96 "I "
```

I checked that in both cases. In the looping case this code:

https://github.com/vim/vim/blob/5c381eb9e72990e4153045f4911c59b9b2194edd/src/insexpand.c#L596
```cpp
	do
	{
	    if (    !(match->cp_flags & CP_ORIGINAL_TEXT)
		    && STRNCMP(match->cp_str, str, len) == 0
		    && match->cp_str[len] == NUL)
		return NOTDONE;
	    match = match->cp_next;
	} while (match != NULL && match != compl_first_match);
```

will return NOTDONE and the loop will not break:

https://github.com/vim/vim/blob/5c381eb9e72990e4153045f4911c59b9b2194edd/src/insexpand.c#L2714

**Comment by brammool** [comment]
I tried but I am unable to reproduce the hang.

**Comment by ghost** [comment]
I just tried it with Fedora, Ubuntu, Alpine Linux and vim / neovim. I can reproduce it on all systems, but only the combination Fedora / Neovim is not interruptable. In all other cases the loop happens sometimes, but <C-c> will interrupt the loop. I also realized that on older versions of vim, complete.vim will trigger more races, like swapped letters and exiting insert-mode. I don't list the versions here, because all that counts is HEAD.

I admit that feedkeys in InsertCharPre is probably not a great idea, I will continue to try finding the problem for a while and then this issue can serve as warning for other people trying to use feedkeys in InsertCharPre.

**Comment by ghost** [comment]
And of course you actually need the en_us dictionary.

**Comment by brammool** [comment]
> And of course you actually need the en_us dictionary.

I tried with just "en", still didn't reproduce.


-- 
In his lifetime van Gogh painted 486 oil paintings. Oddly enough, 8975
of them are to be found in the United States.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ghost** [comment]
Hi Bram, thank you very much for trying to reproduce this, I really appreciate that you took the time. I decided to go for a workaround, if feedkeys is delayed using timer_start(0,....) there is no hang. Hopefully someone will come up with a way to reproduces this systematically.

**Comment by brammool** [comment]
> Hi Bram, thank you very much for trying to reproduce this, I really
> appreciate that you took the time. I decided to go for a workaround,
> if feedkeys is delayed using timer_start(0,....) there is no hang.
> Hopefully someone will come up with a way to reproduces this
> systematically.

Can you please try out the patch anyway?  Otherwise I don't know if it
will actually improve things.  It's an extra call in the input loop, we
should not add it unless there is a reason for it.

-- 
FIRST HEAD:  Oh! quick! get the sword out I want to cut his head off.
THIRD HEAD:  Oh, cut your own head off.
SECOND HEAD: Yes - do us all a favour.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ghost** [comment]
Sorry, I must have missed something, maybe because I write on github. What patch do you mean? The one I did is wrong, as you correctly assumed. It stops the search for completion words, vim won't hang, but it doesn't find all words.

**Comment by brammool** [comment]
Sorry, that patch was for another issue.
Since you found a workaround, perhaps we can close this issue.

**Comment by ghost** [comment]
Closing, to anyone who has this issue too: I am interested in working together. Send me a message.

**Comment by bagustris** [comment]
I have experienced this on vim8 under Ubuntu (16.06) installed from ppa (Jonathon's ppa). 
However, I found difficulties to reproduce it. Sometimes it freezes when I type faster.

**Comment by ghost** [comment]
> Sometimes it freezes when I type faster.

Yes, that is exactly the problem, you have to type quite fast and within a certain margin. Really difficult to reproduce. I got quite good at it. :-)

**Comment by TerryChau** [comment]
Can confirm that I still get this issue.  My vim version is listed below.  Ganwell's solution works.

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 17 2020 21:54:53)
Included patches: 1-1704
Compiled by Arch Linux
```

**Comment by TerryChau** [comment]
If the issue is with dictionary completion, perhaps a way to reproduce the issue is to type the most common dictionary prefixes in a row.  For example, "pre pre pre pre pre pre".

Edit: I can confirm that this test does work, and will freeze vim until `<C-C>` is pressed.

**Comment by brandon1024** [comment]
I've been seeing this occasionally in my environment as well. My configuration is very similar to what @ganwell listed in his original comment, except that I'm using tag completion instead of dictionary completion. It's certainly tricky to reproduce, but I've found that it happens most often when I'm tying quickly.

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 01 2021 01:51:08)
Included patches: 1-2434
Extra patches: 8.2.3402, 8.2.3403, 8.2.3409, 8.2.3428
```

@ganwell I'd take you up on your offer to team up on this one, if you're still interested. I'll reach out.
