### ISSUE TITLE
Need scroll in popup window

### ISSUE THREAD

**Issue by chemzqm** [vim/vim#4577]
**Is your feature request related something that is currently hard to do? Please describe.**

Can't scroll when popup contains more lines than window height.

**Describe the solution you'd like**

Make popup window focusable  and support mouse scroll event.

**Additional context**

When the popup shown at top of cursor, I would like the buffer scroll to the bottom, but I can't do it with `firstline` option since the lines could be wrapped, maybe vim could support `firstline: -1` for scroll to the bottom.

**Comment by Yggdroot** [comment]
@brammool  this issue seems not fixed yet. (vim version Included patches: 1-2151)
```vim
:let id = popup_create(1, {"pos":"botleft", "maxheight": theHeight, "cursorline": 1, "filter": 'popup_filter_menu'})
```
if **theHeight** is no less than `&lines`, when you press `j` in the popup window until cursorline reach the bottom, it won't scroll.

**Comment by Hritik14** [comment]
Any update on this ?
