### ISSUE TITLE
getbufinfo() gives outdated information on buffer leave/hide autocmds

### ISSUE THREAD

**Issue by LudvigHz** [vim/vim#4583]
**Describe the bug**
`getbufinfo()` is not updated in accordance with various events, such as `BufHidden` and `BufWinLeave`.

**To Reproduce**
1. Run `vim --clean` (or `gvim --clean`, etc.)
2. Edit `Filename`
3. Add the following autocmd:
```vimscript
:autocmd BufHidden * echo getbufinfo()
```
3. Edit another file: `:e <another_file>`
4. Switch to the other buffer: `:bprevious`
5. Observe the output.

**Expected behavior**
The following values should be updated for the now hidden buffer:
- `'hidden'` should be `1`
- `'windows'` should be an empty list

**Environment:**
 - Vim version 8.1.0320
 - OS: Pop!_OS 19.04
 - Terminal: rxvt-unicode 9.22-6 with tmux 2.8-3

**Additional context**
The specified values are correct on the `BufEnter` event.

**Comment by chrisbra** [comment]
I suppose this happens because by the time the autocommand triggers, the buffer is not yet actually set  hidden. That would mean this is not a bug, because the actual buffer will only being freed and hidden, **after** the autocommand fired.

**Comment by LudvigHz** [comment]
I see, well if this is intended for the `BufHidden` event, this should be reflected in the docs, since as of now it says the following:
 **autocmd.txt - autocmd-events**
```vimscript
  BufWinEnter             after a buffer is displayed in a window                                         
  BufWinLeave             before a buffer is removed from a window                                        
                                                                                                          
  BufUnload               before unloading a buffer                                                       
  BufHidden               just after a buffer has become hidden                                           
  BufNew                  just after creating a new buffer                                                
                                                              
```
So if the buffer is actually not set hidden by the time the autocmd fires, this means that BufHidden fires just **before** the buffer is hidden, and not after.

**Comment by brammool** [comment]
With the commands you describe the BufHidden event is not triggered, no buffer becomes hidden.
Please give the right reproduction steps.

**Comment by LudvigHz** [comment]
@brammool Right, `set hidden` needs to be applied of course, my bad.

**Comment by brammool** [comment]
OK, the text in the help should read "Just before a buffer becomes hidden".
