### ISSUE TITLE
vim cannot execute SHELL if it contains spaces

### ISSUE THREAD

**Issue by mhoran** [vim/vim#459]
To reproduce this issue:

```
mkdir with\ spaces
ln -s $(which sh) with\ spaces/
SHELL=$(pwd)/with\ spaces/sh vim
```

In the launched Vim, trying to execute anything through a shell, ie `:! ls`, will fail with the error
`Cannot execute shell /home/hotdog/with spaces/sh`.

While a typical shell path may not contain spaces, this is the case on Windows via Git bash when installed in `C:\Program Files`. See https://github.com/git-for-windows/git/issues/498 for context.

**Comment by vim-ml** [comment]
On Thursday, October 22, 2015 at 10:32:59 AM UTC-5, Matthew Horan wrote:

> To reproduce this issue:
> 
> mkdir with\ spaces
> ln -s $(which sh) with\ spaces/
> SHELL=$(pwd)/with\ spaces/sh vim
> 
> In the launched Vim, trying to execute anything through a shell, ie :! ls, will fail with the error
> 
> Cannot execute shell /home/hotdog/with spaces/sh.
> 
> While a typical shell path may not contain spaces, this is the case on Windows via Git bash when installed in C:\Program Files. See git-for-windows/git#498 for context.

I think in this case you may need to manually set your 'shell' option to wrap it in quotes, as in the example in :help 'shell'.

I know there is a place in the help somewhere that shows exactly how all the shell options fit together to build a command, but I can't find it at the moment.

**Comment by odeke-em** [comment]
Hello there @mhoran, thanks for reporting the issue and for the repro.
I've investigated this issue and discovered that it is because the shell passed into system when executing needs its spaces to be properly backquoted ie `\\` instead of ` ` as seen in this minimalist program

``` c
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <string.h>

int main(int argc, char **argv) {
    const char *command = "ls";
    if (argc >= 2)
      command = argv[1];

    const int status = system(command);
    if (status != 0)
      fprintf(stderr, "errno=%d desc=%s status=%d\n", errno, strerror(errno), status);
    return status;
}
```

``` shell
$ gcc syso.c -o syso
```

<img width="577" alt="screen shot 2016-06-18 at 5 21 09 am" src="https://cloud.githubusercontent.com/assets/4898263/16170828/87c5bca6-3514-11e6-8587-c7d343d98b99.png">

I came to this conclusion by examining file `src/os_unix.c` and making this diff

``` diff
diff --git a/src/os_unix.c b/src/os_unix.c
index f08adc5..a5553aa 100644
--- a/src/os_unix.c
+++ b/src/os_unix.c
@@ -4244,9 +4244,17 @@ mch_call_shell(
     if (options & SHELL_COOKED)
    settmode(TMODE_COOK);       /* set to normal mode */

+    fprintf(stderr, "before mch_parse strsave done newcmd %s p_sh %s\n", newcmd, p_sh);
     if (mch_parse_cmd(newcmd, TRUE, &argv, &argc) == FAIL)
    goto error;
+    fprintf(stderr, "after mch_parse strsave done newcmd %s p_sh %s\n", newcmd, p_sh);

+    vim_free(newcmd);
+    newcmd = lalloc(STRLEN(p_sh), TRUE);
+    if (newcmd == NULL)
+   goto error;
+
+    sprintf((char *)newcmd, "%s", (char *)p_sh);
     if (cmd != NULL)
     {
    char_u  *s;
```

which gave

``` shell
before mch_parse strsave done newcmd /Users/emmanuelodeke/Desktop/openSrc/bugs/vim/459/with spaces/sh p_sh /Users/emmanuelodeke/Desktop/openSrc/bugs/vim/459/with spaces/sh
after mch_parse strsave done newcmd /Users/emmanuelodeke/Desktop/openSrc/bugs/vim/459/with p_sh /Users/emmanuelodeke/Desktop/openSrc/bugs/vim/459/with spaces/sh

Cannot execute shell /Users/emmanuelodeke/Desktop/openSrc/bugs/vim/459/with spaces/sh
```

For a minimalist reproduction outside of vim but inside a C program, please see https://github.com/odeke-em/bugs/tree/master/vim/459

@brammool any thoughts on this? I wanted to ask if you had a preference for a function to backslash/escape spaces in a command that will be run in `system`, before I get started with a patch.

**Comment by roneyrao** [comment]
To surround command with quotes is a common practice to overcome space problem:
"C:\Program Files\Git\cmd\git.exe"

**Comment by roneyrao** [comment]
In windows, to surround command with quotes is a common practice to overcome space problem:
"C:\Program Files\Git\cmd\git.exe"
Please apply this style in vim.

**Comment by chrisbra** [comment]
you need to properly quote your shell setting as mentioned in the documentation. Either use
`:set shell=/tmp/with\\\ spaces/sh` (note the space needs to be double escaped) or quote it appropriately:
`:set shell=\"/tmp/with\ spaces/sh\"` (space needs to be escaped). 

Note, double quoting might need to be done to overcome the peculiarities of the `:set` command. Alternatively, it is easier to use `:let &shell='"/tmp/with spaces/sh"'` or `:let &shell='/tmp/with\ spaces/sh'` (note, needs single quotation marks)

Make sure to test the correct shell option using `:set shell?`

Closing.

**Comment by chrisbra** [comment]
I made a patch, to backslash escape the option value of `$SHELL` if it contains spaces.

**Comment by chrisbra** [comment]
To those reading this via the vim-dev list, patch is available here: https://github.com/chrisbra/vim/commit/92f15d58f1d675046758d6126ab022b51c4da47c

**Comment by chrisbra** [comment]
updated commit includes the missing change to term.c

**Comment by brammool** [comment]
Christian Brabandt wrote:

> To those reading this via the vim-dev list, patch is available here: https://github.com/chrisbra/vim/commit/92f15d58f1d675046758d6126ab022b51c4da47c

If I see this right, this will change the value of 'shell' to put a
backslash before a space.  I don't think that is a good solution, the
escaping should be done where 'shell' is used.

If 'shell' is a full path it should be possible to do:
	:exe  '!' . &shell . ' argument'

Wouldn't that break when 'shell' contains an extra backslash?

-- 
hundred-and-one symptoms of being an internet addict:
268. You get up in the morning and go online before getting your coffee.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by jamessan** [comment]
> If 'shell' is a full path it should be possible to do: :exe '!' . &shell . ' argument'

Shouldn't that be `:exe '!' . shellescape(&shell, 1) . ' argument'`?

However, the example given in the original post was about a user running `:!ls` when `&shell` has characters that need to be escaped.  There's no reason to assume this only applies to whitespace.

**Comment by chrisbra** [comment]
> If 'shell' is a full path it should be possible to do: 
> :exe '!' . &shell . ' argument'

That should work now. 

Vim   | sh w/o spaces | shell contains spaces
--|----------------|-----------
unpatched | works | breaks
patched  | works | works

However, it might break for `job_start()`

The patch basically does what is already suggested in the documentation:
https://github.com/vim/vim/blob/0479e910c423d71e2b96bc721feffad5808e767a/runtime/doc/options.txt#L6619-L6621

And you need to do this to make `:!ls` work as suggested [earlier](https://github.com/vim/vim/issues/459#issuecomment-354976758)

I think the case that spaces occur in the shell path is a pretty common on Windows and especially a problem for git-bash, when it is installed at `c:\Program Files` so at least this standard case should be fixed, not sure about the other cases where shellescape helps.

**Comment by brammool** [comment]
Christian wrote:

> > If 'shell' is a full path it should be possible to do: 
> > :exe '!' . &shell . ' argument'
> 
> That should work now. 

> Vim   | sh w/o spaces | shell contains spaces
> --|----------------|-----------
> unpatched | works | breaks
> patched  | works | works
> 
> However, it might break for `job_start()`
> 
> The patch basically does what is already suggested in the documentation:
> https://github.com/vim/vim/blob/0479e910c423d71e2b96bc721feffad5808e767a/runtime/doc/options.txt#L6619-L6621
> 
> And you need to do this to make `:!ls` work as suggested [earlier](https://github.com/vim/vim/issues/459#issuecomment-354976758)
> 
> I think the case that spaces occur in the shell path is a pretty
> common on Windows and especially a problem for git-bash, when it is
> installed at `c:\Program Files` so at least this standard case should
> be fixed, not sure about the other cases where shellescape helps.

It's unfortunate that we have this way of including a flag in the shell
option.  Now we can't give it to shellescape(), since it would escape the
space before the argument.

I previously thought that 'shell' should just use $SHELL, and escaping
where 'shell' is used, but that is now not possible.  Either a space in
$SHELL must be escaped when it's used for 'shell', or double quotes can
be used, as in the example.

-- 
In his lifetime van Gogh painted 486 oil paintings. Oddly enough, 8975
of them are to be found in the United States.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
I am not sure I understand. Adding a flag to the shell option is not correct. That's what we have the 'shellcmdflag' option for. We should strongly discourage adding parameters to the shell option.

**Comment by brammool** [comment]
Christian Brabandt wrote:

> I am not sure I understand. Adding a flag to the shell option is not
> correct. That's what we have the 'shellcmdflag' option for. We should
> strongly discourage adding parameters to the shell option.

The example clearly shows an argument included in the shell command.
E.g., you can use "dash -o vi".

The 'shellcmdflag' is different, it's used to pass a command argument to
the shell.  'shell' itself is the command to run a shell.

-- 
Microsoft: "Windows NT 4.0 now has the same user-interface as Windows 95"
    Windows 95: "Press CTRL-ALT-DEL to reboot"
Windows NT 4.0: "Press CTRL-ALT-DEL to login"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
closing then

**Comment by brammool** [comment]
No, the patch should be included.
