### ISSUE TITLE
Ex doesn't recognise URL in silent mode.

### ISSUE THREAD

**Issue by kenorb** [vim/vim#461]
The following command prints html code correctly:

```
 $ ex +%p http://example.com/ 
```

However when I'm using it in silent mode, it doesn't recognise URL format:

```
$ ex -scq! -V1 http://example.com/
"http://example.com/" Illegal file name
```

I'm missing anything or it's a bug?

**Comment by chrisbra** [comment]
Please use an explicit `-N` to make sure, all plugins work correctly.
