### ISSUE TITLE
":read !start /?" on Windows emits errors

### ISSUE THREAD

**Issue by lkintact** [vim/vim#4612]
Run `gvim.exe --clean` and exectute `:read !start /?`

Gvim reports two errors:
```
E371: Command not found
shell returned -1

E485: Can't read file C:\Users\***\AppData\Local\Temp\VIo9D68.tmp  
```
gvim_8.1.1622_x86_signed.zip,  
Windows 10 Home

**Comment by brammool** [comment]
Why would it not give these errors?

**Comment by lkintact** [comment]
I guess because other shell commands/programs like `dir /?`, `cd /?` and even `cmd /?` work correctly, 
e.g. `:read !cmd /?` puts the output of `cmd /?` to the buffer.
And `start /?` executed from Windows shell works too, of course, outputting the help for `start`.

**Comment by brammool** [comment]
> Because other shell commands/programs like `dir /?`, `cd /?` and even
> `cmd /?` work correctly, e.g. `:read !cmd /?` puts the output of `cmd
> /?` to the buffer?

"start" is not a command.  It's a modifier that runs the following
command asynchronously, and since no command is following it fails.

-- 
   LAUNCELOT leaps into SHOT with a mighty cry and runs the GUARD through and
   hacks him to the floor.  Blood.  Swashbuckling music (perhaps).
   LAUNCELOT races through into the castle screaming.
SECOND SENTRY: Hey!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lkintact** [comment]
> "start" is not a command. It's a modifier that runs the following command asynchronously, and since no command is following it fails.

Sorry, I think the fact that `start /?` executed from Windows command shell outputs help for `start` somewhat confused me, I expected `:read !start /?` to put that output to the buffer.

**Comment by brammool** [comment]
> > "start" is not a command. It's a modifier that runs the following
> > command asynchronously, and since no command is following it fails.
> 
> Sorry, I think the fact that `start /?` executed from Windows command
> shell outputs help for `start` somewhat confused me, I expected `:read
> !start /?` to put that output to the buffer.

I see.  That might be the only exception for "start" producing output
without a command following.  Probably not worth making an exception
for.

-- 
        **  Hello and Welcome to the Psychiatric Hotline **
If you are obsessive-compulsive, please press 1 repeatedly.
If you are co-dependent, please ask someone to press 2.
If you have multiple personalities, please press 3, 4, 5 and 6.
If you are paranoid-delusional, we know who you are and what you want
       - just stay on the line so we can trace the call.
If you are schizophrenic, listen carefully and a little voice will
       tell you which number to press next.
If you are manic-depressive, it doesn't matter which number you press
       - no one will answer.
If you suffer from panic attacks, push every button you can find.
If you are sane, please hold on - we have the rest of humanity on the
        other line and they desparately want to ask you a few questions.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
