### ISSUE TITLE
A couple of corrrections to the docs

### ISSUE THREAD

**Issue by lkintact** [vim/vim#4614]
1. `doc/mbyte.txt`:
In `This |+multi_byte_ime| feature help this` and `But this feature help this` "help" should be replaced with "helps".

2. `doc/change.txt`:
The first words of items 5, 6 and 7 of the list at `:help registers` should probably be capitalized for the sake of consistency with the rest of the list.

gvim_8.1.1622_x86_signed.zip

**Comment by brammool** [comment]
> 1. `doc/mbyte.txt`:
> In `This |+multi_byte_ime| feature help this` and `But this feature help this` "help" should be replaced with "helps".

That whole paragraph is hard to read.  How about this:

The |+multi_byte_ime| feature helps for this.  It reduces the number of times
the IME status has to be switched manually.  In Normal mode, there is almost
no need to use IME, even when editing multibyte text.  So when exiting Insert
mode, Vim memorizes the last status of IME and turns off IME.  When
re-entering Insert mode, Vim sets the IME status to that memorized status
automatically.

> 2. `doc/change.txt`:
> The first words of items 5, 6 and 7 of the list at `:help registers` should probably be capitalized for the sake of consistency with the rest of the list.

I'll do that.

-- 
A vacation is a period of travel during which you find that you
took twice as many clothes and half as much money as you needed.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
fixed by 396e829fa355ebc92a618ef18266a3fed71b7042
