### ISSUE TITLE
iskeyword ignores character code 64 (i.e. the `@`)

### ISSUE THREAD

**Issue by psprint** [vim/vim#4626]
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Describe the bug**
Setting: `:set iskeyword=@,48-57,_,192-255,-,64` doesn't make the "@" character (code 64) to be recognized by the completion (e.g. by ctrl-p).

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean` (or `gvim --clean`, etc.)
2. Issue `:set iskeyword=@,48-57,_,192-255,-,64`
3. Type:
```
@word-test
test-word

@<press ctrl-p here>
```

4. Describe the error

Both `test-word` and `word-test` will be completed, while only the latter should

**Expected behavior**

Only the `word-test` suggestion should be proposed, i.e. actually completed instantly (because of only single match)

**Environment (please complete the following information):**
 - VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul  4 2019 23:52:17)
macOS version
Included patches: 1-1635
 - OS X 10.13.4
 - Terminal: iTerm2

**Additional context**
I've started to use the @ char as the namespacer for zsh functions. Hope the issue will be fixed quick so that I can use the Vim completion.

**Comment by chrisbra** [comment]
See the help at :h 'isfname' on how to include the @

**Comment by brammool** [comment]
So that is: @-@

**Comment by psprint** [comment]
Thanks!

niedz., 7 lip 2019, 14:47 użytkownik Bram Moolenaar <
notifications@github.com> napisał:

**Comment by psprint** [comment]
I now have the same problem with symbol `+`. `diw` does delete the symbol, however Ctrl-P doesn't recognize/complete it. Could someone help?

**Comment by psprint** [comment]
ah no, it works, I was mislead by the fact that I have many +-starting symbols

**Comment by chrisbra** [comment]
Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. Thanks.
