### ISSUE TITLE
:execute 'normal! q:i!ls' broken between version 7.4.273 and 7.4.769

### ISSUE THREAD

**Issue by rolfasmund** [vim/vim#463]
:execute 'normal! q:i!ls'      " <-- doesn't work

should insert !ls in command line history, just like 

:call histadd('cmd', '!ls')       " <-- works fine

**Comment by mattn** [comment]
Maybe the behavior was changed in 7.4.441 https://groups.google.com/forum/#!topic/vim_dev/lrNHz8khMkE
Because opening cmdwin with normal command may occur endless loop. You need to do with following.

``` vim
:call feedkeys("q:i!ls\<cr>")
```

**Comment by rolfasmund** [comment]
nope. As stated in the title, it's still broken in 7.4.769. It's also broken in 7.4.827

**Comment by mattn** [comment]
No, I'm not talking FIXED.
Old behavior was a bug.

**Comment by chrisbra** [comment]
I am not sure, this was ever supposed to work. That's what the histadd() function is for. Therefore closing.

**Comment by rolfasmund** [comment]
Thanks. I fixed my scripts to use histadd()
