### ISSUE TITLE
Greater than sign `>` could not be inserted at beginning of a line directly in a markdown file.

### ISSUE THREAD

**Issue by brookhong** [vim/vim#4633]
**Describe the bug**
Greater than sign `>` could not be inserted at beginning of a line directly in a markdown file.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. echo "test line" > test.md
2. vim test.md
3. press `I` to insert `>` at beginning of the first line of test.md
4. you'll see below change, with `>` placed behind `t`:

        t>est line

**Expected behavior**
We should see, with cursor after `>`.

    >test line

**Screenshots**

**Environment (please complete the following information):**
 - Vim version [e.g. 8.1.1400] (Or paste the result of `vim --version`.)
 - OS: macOS 10.12.6
 - Terminal: in both MacVim and vim in terminal

**Additional context**
It is caused by this line https://github.com/vim/vim/blob/master/runtime/ftplugin/markdown.vim#L10

**Comment by brammool** [comment]
I can't reproduce the problem.  Did you try starting with "vim --clean"?

**Comment by brookhong** [comment]
Sorry, the root cause is another plugin -- https://github.com/sukima/xmledit, which also gets loaded for markdown by the line mentioned above.
