### ISSUE TITLE
regex: possessive quantifiers

### ISSUE THREAD

**Issue by junklogar** [vim/vim#4638]
Please add support in the regex engine for the possessive quantifiers (*+ and ++ in perl)
to take advantage of their performance benefits.

**Comment by brammool** [comment]
Please point to the relevant explanation of these constructs.

**Comment by dpelle** [comment]
@brammool wrote:

> Please point to the relevant explanation of these constructs.

https://www.regular-expressions.info/possessive.html

As to whether it's worth the effort to add to both vim regexp engines,
I don't really know.

**Comment by andymass** [comment]
Is this similar to `/\(a*\)\@>b/`?

**Comment by brammool** [comment]
> @brammool wrote:
> 
> > Please point to the relevant explanation of these constructs.
> 
> https://www.regular-expressions.info/possessive.html
> 
> As to whether it's worth the effort to add to both vim regexp engines,
> I don't really know.

The new regexp engine doesn't do backtracking, so "greedy" should have
nearly the same performance as "possessive".   Thus I don't think it's
worth the effort.

-- 
5 out of 4 people have trouble with fractions.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by junklogar** [comment]
> Is this similar to `/\(a*\)\@>b/`?

Unfortunately, that doesn't seem to work with newlines e.g. `/\(\_a*\)\@>b/`
