### ISSUE TITLE
vim crash on :py3 print("")

### ISSUE THREAD

**Issue by habamax** [vim/vim#4640]
**Describe the bug**

Vim crashes when any of the python command is issued.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean` (or `gvim --clean`, etc.)
2. Type `:py3 print("hello")<CR>`

**Expected behavior**
`hello` message should appear

**Screenshots**
![image](https://user-images.githubusercontent.com/234774/60945971-af1b4d00-a2f5-11e9-8218-180adca8c052.png)

**Environment (please complete the following information):**
 - Vim version [e.g. 8.1.1657] (Or paste the result of `vim --version`.)
 - OS: Windows 10 1903 (OS Build 18362.239)
 - Terminal: [cmd.exe, powershell] and GUI

**Additional context**
python version is 3.7.3

This happened after I updated windows to the recent version (+vim from 8.1.1649 to 8.1.1657).
Then I downgraded vim to 8.1.1649 again but error stays the same.

All python related plugins crash vim -- that was how I had encountered the issue.
I have just tried neovim -- everything works as expected (UltiSnips, LeaderF plugins, `:py3 print("hello")`

**Comment by habamax** [comment]
I have tried vim versions: 8.1.1640, 8.1.1635 and 8.1.1608 -- the same issue. Looks like the recent windows update is in question?

**Comment by habamax** [comment]
Upgraded python to v3.7.4 -- the same error

**Comment by mg979** [comment]
I had the same issue with python installed via Scoop, I uninstalled that and installed the normal python installer and it worked. The problem isn't vim (as you noted, downgrading vim doesn't solve the problem).

**Comment by habamax** [comment]
@mg979 indeed I use scooped python, let me try normal python

**Comment by habamax** [comment]
Yes, it did the trick. Regular python installation doesn't cause this problem. Thank you!
