### ISSUE TITLE
test_mksession.vim might hang (.another.swp)

### ISSUE THREAD

**Issue by blueyed** [vim/vim#4644]
I am seeing a hanging test with `test_mksession.vim`.

Running it without `>/dev/null` shows:

```console
% VIMRUNTIME=../../runtime  ../vim -f  -u unix.vim -U NONE --noplugin --not-a-term -S runtest.vim test_mksession.vim --cmd 'au SwapExists * let v:swapchoice = "e"'

"test_mksession.vim" [converted] 540 lines, 13013 characters
"Xtemp" [New] 10L, 214C written
Executing Test_mksession_arglist()
"file1" [New File]
Executing Test_mksession_blank_tabs()
4 buffers wiped out
Executing Test_mksession_blank_windows()
9 buffers wiped out
"Xbaz" [New] 0L, 0C written
"Xbaz" [converted] 0L, 0C
3 buffers wiped out
Executing Test_mksession_hlsearch()
Executing Test_mksession_large_winheight()
Executing Test_mksession_lcd_multiple_tabs()
Executing Test_mksession_no_errmsg()
5 buffers wiped out
"Xtest2" [New File]
Executing Test_mksession_quote_in_filename()
Found a swap file by the name ".another.swp"
          owned by: user   dated: Mon Jul 08 12:56:39 2019
         file name: …/Vcs/vim/src/testdir/another
          modified: no
         user name: user   host name: a.example.com
        process ID: 7577
While opening file "another"
      CANNOT BE FOUND
(1) Another program may be editing the same file.  If this is the case,
    be careful not to end up with two different instances of the same
    file when making changes.  Quit, or continue with caution.
(2) An edit session for this file crashed.
    If this is the case, use ":recover" or "vim -r another"
    to recover the changes (see ":help recovery").
    If you did this already, delete the swap file ".another.swp"
    to avoid this message.

Swap file ".another.swp" already exists!
[O]pen Read-Only, (E)dit anyway, (R)ecover, (D)elete it, (Q)uit, (A)bort:
```

I've tried to "fix" / improve this using the following (and also tried `throw`), but without success:

```diff
diff --git i/src/testdir/runtest.vim w/src/testdir/runtest.vim
index e120e7f23..8dc900889 100644
--- i/src/testdir/runtest.vim
+++ w/src/testdir/runtest.vim
@@ -72,6 +72,9 @@ func HandleSwapExists()
   " editing it and do ":make test_name") and the output file.
   if expand('<afile>') == 'messages' || expand('<afile>') =~ s:test_script_fname
     let v:swapchoice = 'e'
+  else
+    call assert_report('HandleSwapExists: unexpected swap file: '.expand('<afile>'))
+    let v:swapchoice = 'q'
   endif
 endfunc
```

It seems like errors are ignored from there, but `assert_report` should get passed through probably in general?

**Comment by blueyed** [comment]
@brammool 
Have you tried that the patch works as expected?
When I've tried it it did not have an effect - i.e. the test would still hang there.

**Comment by brammool** [comment]
Daniel Hahler wrote:

> @brammool 
> Have you tried that the patch works as expected?
> When I've tried it it did not have an effect - i.e. the test would
> still hang there.

Yes, it worked for me.  But I only tested with an empty .another.swp
file.  Tried again with a real swap file:

Found errors in Test_mksession_quote_in_filename():
function HandleSwapExists line 7: Unexpected swap file: .another.swp

Works with and without redirecting to /dev/null

-- 
ARTHUR:   Ni!
BEDEVERE: Nu!
ARTHUR:   No.  Ni!  More like this. "Ni"!
BEDEVERE: Ni, ni, ni!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
