### ISSUE TITLE
Unexpected behaviour on using clang binding

### ISSUE THREAD

**Issue by ghost** [vim/vim#467]
# PREREQUISITES:
1. clang-3.7 with python2 bindings installed
2. Python-2.7
3. vim-7.4(1-884)
# STEPS TO REPRODUCE:
1. unpack attachment "plugin.zip" to ~/.vim/plugin
2. Put source file "main.cpp" from attachment in some directory. Then edit "clang_service.py", path to source should point to the "main.cpp". It's very important! If script doesnt find the source bug wont reproduced.
3. execute in shell "export PYTHONPATH=~/.vim/plugin"
4. Run vim within the shell.
# EXPECTED RESULTS:

Vim works as usual.
# ACTUAL RESULTS

Vim goes to undefined state. Keys not work, strange output. In short not work everithing. For example pressing arrow keys in normal mode causes output of number. Here is the example: just opened main.cpp and pressed arrow buttons:

```
main2ain()
{
    return 0;
}2,1{
~                                                                                                
}3,2{                                                                                            
~                                                                                                
}4,1{                                                                                            
~                                                                                                
}3,21                                                                                            
~                                                                                                
~                                                                                                
"main.cpp" 4L, 29C                                                             1,1           Усе
```

---

This bug blocks work of highlighting plugin based on clang (like clighter).

Plugin (in attachment) very simple:

``` vim
" file  plug.vim
py import clang_service
```

``` python
# file clang_service.py
from clang import cindex

idx = cindex.Index.create()
idx.parse("/pathto/main.cpp", None, None, 0)
```

ATTACHMENTS:
[bugreport.txt](https://drive.google.com/file/d/0BxiAL-dZ0EWELTd2ZXlJdkh5elE/view?usp=sharing)
[main.cpp](https://drive.google.com/file/d/0BxiAL-dZ0EWEYmp5T1hZcGZFSUE/view?usp=sharing)
[plugin.zip](https://drive.google.com/file/d/0BxiAL-dZ0EWENFh3TkdvRDIyb3M/view?usp=sharing)

**Comment by lacygoill** [comment]
The attachment links are no longer working:

   > Sorry, the file you have requested does not exist.

So, there's no way to reproduce the issue anymore.

---

The OP deleted their account, so we won't get any feedback from them anymore.

---

After more than 5 years, nobody commented on this issue to acknowledge it or give more details.

---

Python 2 is [no longer supported](https://www.python.org/doc/sunset-python-2/).

**Comment by chrisbra** [comment]
so closing
