### ISSUE TITLE
XML indent double size for non-tag

### ISSUE THREAD

**Issue by PMox** [vim/vim#4670]
**Describe the bug**
In 63b74a8 a change was introduced in vim/runtime/indent/xml.vim for which if you add text as tag content on a new line the indent applied is twice shiftwidth().

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Edit `filename.xml`
2. <esc>set sw=2
3. <esc>set et
4. <esc>set ts=2
5. insert '<tag>'
6. insert a newline
7. Observe: indent for the line is 4, it must be 2
8. insert a "<"
9: Observe: indent for the line is 4, correct
4. Describe the error

**Expected behavior**
Add one single shiftwidth on newline, independently from the tag.

**Environment (please complete the following information):**
 - Vim version VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul  8 2019 19:26:28) via Homebrew
 - OS: Mac OS 10.13.6
 - Terminal: iTerm2

**Additional context**
The expected behavior appears before 63b74a8, so it's introduced here:
https://github.com/vim/vim/commit/63b74a8362b14576b21d342dc424d0396ca8ea27#diff-6cbcaa8336a0ca9e5e4bf3f0276ee25d, probably in XmlIndentSum.
I was unable to get the commit log message for that specific change, so I'm unable to tell if this is intentional (and I'd like to see the rationale of it) or a bug.

Workaround for me is to get the code ad the previous version:
https://github.com/vim/vim/blob/314dd79cac2adc10304212d1980d23ecf6782cfc/runtime/indent/xml.vim

**Comment by chrisbra** [comment]
Please report problems at my upstream repository (https://github.com/chrisbra/vim-xml-ftplugin) not here and make sure you test the latest version there first. Thanks.

**Comment by PMox** [comment]
In the last source code this is resolved, thanks.

Did you already sent a PR to have the latest version included in VIM?

**Comment by chrisbra** [comment]
Not yet, was trying to get some feedback first, before sending an update to Bram for distribution with Vim
