### ISSUE TITLE
mkvimrc writes to pwd, even if started with ~/.vimrc

### ISSUE THREAD

**Issue by Grossdm** [vim/vim#4677]
After I change a setting that I want to save in my `.vimrc` file, if I am not currently in `$HOME` `mkvimrc` saves a new `.vimrc` in `$PWD`.

Detailed steps to reproduce the behavior:
1. `cd` to any directory that is not `$HOME`
2. Run `vim`.
3. Change a setting, e.g. `:set nohlsearch`.
4. Confirm that vim has found and used `~/.vimrc` with `:echo $MYVIMRC`.
5. Tell vim to save the configuration: `:mkvimrc`.
6. Vim creates a new `.vimrc` file in `$PWD`.

**Expected behavior**
I expect vim to write to the `.vimrc` that it is currently using, unless I somehow specify otherwise.

**Environment:**
 - Vim version
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled May  1 2019 01:21:50)
Included patches: 1-1240
Modified by <cygwin@cygwin.com>
Compiled by <cygwin@cygwin.com>
Huge version without GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     -tag_old_static
+arabic            -farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    -tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +textprop
+byte_offset       -hangul_input      +num64             +timers
+channel           +iconv             +packages          +title
+cindent           +insert_expand     +path_extra        -toolbar
-clientserver      +job               +perl/dyn          +user_commands
+clipboard         +jumplist          +persistent_undo   +vartabs
+cmdline_compl     +keymap            +postscript        +vertsplit
+cmdline_hist      +lambda            +printer           +virtualedit
+cmdline_info      +langmap           +profile           +visual
+comments          +libcall           +python/dyn        +visualextra
+conceal           +linebreak         +python3/dyn       +viminfo
+cryptv            +lispindent        +quickfix          +vreplace
+cscope            +listcmds          +reltime           +wildignore
+cursorbind        +localmap          +rightleft         +wildmenu
+cursorshape       +lua/dyn           +ruby/dyn          +windows
+dialog_con        +menu              +scrollbind        +writebackup
+diff              +mksession         +signs             -X11
+digraphs          +modify_fname      +smartindent       -xfontset
-dnd               +mouse             +startuptime       -xim
-ebcdic            -mouseshape        +statusline        -xpm
+emacs_tags        +mouse_dec         -sun_workshop      -xsmp
+eval              -mouse_gpm         +syntax            -xterm_clipboard
+ex_extra          -mouse_jsbterm     +tag_binary        -xterm_save
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim81"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -ggdb -O2 -pipe -Wall -Werror=format-security -fstack-protector-strong --param=ssp-buffer-size=4 -fdebug-prefix-map=/usr/src/ports/vim/vim-8.1.1240-1.x86_64/build=/usr/src/debug/vim-8.1.1240-1 -fdebug-prefix-map=/usr/src/ports/vim/vim-8.1.1240-1.x86_64/src/vim-8.1.1240=/usr/src/debug/vim-8.1.1240-1 -fstack-protector-strong -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -fstack-protector-strong  -L/usr/local/lib -Wl,--as-needed -o vim.exe        -lm -lelf -lnsl    -lncursesw -liconv -lacl -lattr -lintl   -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base -fstack-protector-strong  -L/usr/lib/perl5/5.26/x86_64-cygwin-threads/CORE -lperl -lpthread -ldl -lcrypt        

```
 - OS: Microsoft Windows [Version 10.0.17134.885] Enterprise Edition
 - Terminal: Cygwin mintty 3.0.2 (x86_64-pc-cygwin)

**Additional context**
This is frustrating.
Vim also does this on Android running Termux.

**Comment by jottkaerr** [comment]
This is the document behavior (see `:help :mkvimrc`). And personally I (and I guess many more users) would not be happy if a hand-crafted .vimrc got overwritten by a long list of mappings and options that resulted from loading a lot of different plugins.

**Comment by chrisbra** [comment]
> And personally I (and I guess many more users) would not be happy if a hand-crafted .vimrc got overwritten by a long list of mappings and options that resulted from loading a lot of different plugins.

totally agree. Closing for not being a bug here.

**Comment by Grossdm** [comment]
Please note that `:mkvimrc` is not sufficient to "accidentally" overwrite `~/.vimrc`.
When vim is running in `$HOME`, if someone had created a hand-crafted .vimrc with no foresight to backup this file then `:mkvimrc` is at no risk of overwriting it.
An appropriate warning message is displayed which refuses to overwite .vimrc, further explaining that vim will only comply if `:mkvimrc!` is used.

This seems to be a reasonable and appropriate behavior.

In contrast, silently creating .vimrc in other directories seems likely to loose attempts to save the current configuration.

Thank you for your consideration.
