### ISSUE TITLE
ftplugin doesn't respect user set formatoptions

### ISSUE THREAD

**Issue by Tumbler** [vim/vim#4680]
**Describe the bug**
When `formatoptions` is set in a vimrc file, it will still be edited by ftplugin, creating undesired behavior.

**To Reproduce**
1. Put `set formatoptions=rql` your vimrc file.
2. Relaunch vim.
3. Edit any `.vim` file.
4. Type ":verbose set formatoptions?"
5. Observe output (Should be `formatoptions=croql Last set from .../ftplugin/vim.vim`)

**Expected behavior**
A user should be able to decide what format options they want by editing it in their vimrc. There should be an option to disable the automatic update of `formatoptions`.

**Suggested fix**
Add a global variable that is checked in ftplugin that will disable changing `formatoptions`.

**Environment:**
 - Vim version: 8.1.1
 - OS: Windows 7 Professional Service Pack 1
 - Terminal: GUI

**Comment by chrisbra** [comment]
The whole idea of filetype plugins is to define specific settings that might make sense for that specific filetype and most of its users. If you do not like those settings, the documented way to override it is to either use any of the the methods mentioned at `:h ftplugin-override` or simply do not enable filetype plugins in the first place. As such, it is not a bug here.

**Comment by tonymec** [comment]
This is intentional.

Almost every ftplugin sets one or more options locally (using `:setlocal`) for the file of that filetype which you just started editing. This doesn't affect the global default for options which have one, but asking an option value with `:set optionname?` gives you the local value for the current buffer in preference to the global setting. If you ask `:verbose setg fo?` the answer should be
```
  formatoptions=rql
        Last set from ~/.vimrc line 123
```
or similar.

If you want to override some ftplugin settings, specifically for that filetype, use an after-plugin, for instance a vim script named (on Unix-like systems) `~/.vim/after/ftplugin/vim.vim`. (On Windows, replace `.vim` by `vimfiles`.)

Best regards,
Tony.

**Comment by Tumbler** [comment]
Thanks Tony. The only problem with this is that I don't want to just change it for vim files. I want my format options to remain consistent between *all* filetypes. But I don't want to disable the rest of ftplugin.

**Comment by chrisbra** [comment]
Try an OptionSet autocommand.

**Comment by silverqx** [comment]
How can I remove the `ro` for all filetypes? I need this `set formatoptions-=ro` to be applied for all filetypes, I don't know how to script in Vim, so I would like to gently ask someone how do this.

Thx for suggestions.

**Comment by chrisbra** [comment]
This seems to be lua based config, which is invalid for Vim. As said before, ty an `OptionSet` autocommand:
```vim
au OptionSet formatoptions :setl formatoptions-=ro
```

**Comment by silverqx** [comment]
Thx, this works great on Linux, but why it doesn't work on Windows in `_vimrc` file?

**Comment by chrisbra** [comment]
It should work there as well.

**Comment by silverqx** [comment]
It doesn't work even on Linux, I forgot to remove `after/ftplugin/vim.vim`.

So it doesn't for me, I also tried with `vim --clean` and paste it like `:au OptionSet formatoptions :setl formatoptions-=ro` and it does nothing.

**Comment by chrisbra** [comment]
Interesting. I am pretty sure this worked at some point in the past. You can alternatively try:
```
au Filetype * :setl fo-=r fo-=o
```

**Comment by silverqx** [comment]
Also, in docs for `au` command is written something like:

> OptionSet is not triggered on startup and for the 'key' option for obvious reasons.

And I think that is the reason why it doesn't work.

**Comment by silverqx** [comment]
> au Filetype * :setl fo-=r fo-=o

This works great in all cases, it can even be set like:

```vim
au Filetype vim,conf :setl fo-=ro
```

**Comment by jmdevin** [comment]
> by default, it's like `formatoptions=vt` or something like that, so you think that it works but before you added that command formatoptions were also `formatoptions=vt`.

By default, `formatoptions` is set to `tcq`. However, it's set to `vt` if it's in `compatible` mode. If you try a different vimrc by using `vim -u othervimrc`, then it needs to begin with the line `set nocompatible`. That may have been part of the problem.

However, if you've found a solution that works then all's good.

**Comment by silverqx** [comment]
> By default, formatoptions is set to tcq

That was only an example, I wanted to explain somehow that those options aren't removed.

But I don't understand why these continue comments on the next line are set by default. This rule assumes that you are writing more multiline comments than single-line comments and this isn't true in 95% of filetypes. Single-line comments are used more often during coding which means this setting makes coding harder.

Of course, there are filetypes where this makes sense like qdoc files or files where you are writing a lot of multiline comments or filetypes for writing documentation. In these files this setting makes sense.

Also, in multiline comments which have an ending token like `*/`, in this case, the comment must continue on the next line.

But forcing it everywhere in general isn't a good choice from my view and I have to delete them almost every time.

Thx guys for suggestion now I'm happy. 😁
