### ISSUE TITLE
E325 message incorrectly displays day of week/month under Windows if "encoding" is set to "utf-8"

### ISSUE THREAD

**Issue by lkintact** [vim/vim#4681]
1. Create a file "1.txt".
2. Run `gvim.exe -u NONE --cmd "set encoding=utf-8" --cmd "language messages Russian" 1.txt `
3. Repeat step 2. Gvim outputs an E325: ATTENTION message:

```
Обнаружен своп-файл с именем ".1.txt.swp"
              дата: Âò èþë 16 01:07:25 2019
         имя файла: C:/Users/***/Downloads/1.txt
           изменён: нет
      пользователь: ***  компьютер: ***

при открытии файла: "1.txt"
              дата: Âò èþë 16 01:05:01 2019                                     

```
(Personal info replaced with "***"). Please note the "дата:" ("dated:") lines: the "Âò èþë" part should be "Вт июл" (which is short for "Вторник июль", the Russian for "Tuesday july").

If at step 3 I set "language messages English", i.e.
`gvim.exe -u NONE --cmd "set encoding=utf-8" --cmd "language messages English" 1.txt `,
the day of week/month part is still displayed incorrectly, in the same way:
```
Found a swap file by the name ".1.txt.swp"
             dated: Âò èþë 16 01:16:26 2019
         file name: C:/Users/***/Downloads/1.txt
          modified: no
         user name: ***  host name: ***

While opening file "1.txt"
             dated: Âò èþë 16 01:16:17 2019                                     
```

Windows 10 Home 1803 (Russian)
gvim_8.1.1674_x86.zip

**Comment by tonymec** [comment]
Try setting the `language messages` first and the `'encoding'` afterwards.

If that isn't enough, try setting both the "messages" language and the "ctype" language to some UTF-8 setting. On Linux that would be something like ru_RU.utf8 but Windows sets it differently. Maybe Russian_Russia.10646 or something similar. (Before you change it, check what it is set to now by issuing the `:language` command with no argument.)

I remember that when I was still on Windows (with Vim 6.x) the messages languages was one of the very few settings which needed to be set before sourcing the `vimrc_example.vim`. I admittedly used English, not Russian, as the language.

Best regards,
Tony.

**Comment by chrisbra** [comment]
so what does `Âò èþë`? I believe this output comes from the `strftime()` function, which is a system function and nothing we influence.

**Comment by k-takata** [comment]
Maybe we need to convert the result of `strftime()` from current code page to 'encoding'.

**Comment by k-takata** [comment]
This should fix the problem:

```diff
diff --git a/src/memline.c b/src/memline.c
--- a/src/memline.c
+++ b/src/memline.c
@@ -2142,7 +2142,23 @@ get_ctime(time_t thetime, int add_newlin
     if (curtime == NULL)
 	vim_strncpy((char_u *)buf, (char_u *)_("(Invalid)"), sizeof(buf) - 1);
     else
+    {
 	(void)strftime(buf, sizeof(buf) - 1, "%a %b %d %H:%M:%S %Y", curtime);
+# ifdef MSWIN
+	if (enc_codepage >= 0 && (int)GetACP() != enc_codepage)
+	{
+	    char_u	*to_free = NULL;
+	    int		maxlen;
+
+	    acp_to_enc((char_u *)buf, (int)strlen(buf), &to_free, &maxlen);
+	    if (to_free != NULL)
+	    {
+		STRCPY(buf, to_free);
+		vim_free(to_free);
+	    }
+	}
+# endif
+    }
 #else
     STRCPY(buf, "(unknown)");
 #endif
```

**Comment by k-takata** [comment]
I created a PR for this (with some modifications): #4685.

**Comment by brammool** [comment]
Ken Takata wrote:

> I created a PR for this (with some modifications): #4685.

Please let us know if that indeed fixes the problem.

Could it be that it depends on the library that provides strftime()?

-- 
SIGFUN -- signature too funny (core dumped)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
I see the same issue on my Japanese Windows and I confirmed that #4685 fixes it.

It could depends on the library, but I confirmed with both MSVC and MinGW.

**Comment by lkintact** [comment]
@tonymec thank you, Tony, I tried tinkering with the `:language` command and the `LC_*` environment variables, but that didn't help.
