### ISSUE TITLE
job_start() reports error for large input buffers: E631: write_buf_line(): write failed

### ISSUE THREAD

**Issue by bfrg** [vim/vim#4688]
**Describe the bug**
Vim reports an error when a large buffer is passed to `job_start({cmd})` and `{cmd}` is outputting some text before the input is processed.
This happens for example when `{cmd}` outputs an error because of wrong usage, or when `--help` is passed to it.

**To Reproduce**
1. Run `vim --clean -c "source run.vim"` (see below).
2. Open a large file, like Vim's `evalfunc.c` file.
3. Type `:Run<cr>` with focus on `evalfunc.c`.
4. Vim reports the following error:
```
Error detected while processing function <SNR>14_runjob:
line    1:
E631: write_buf_line(): write failed
```
Note: The output of the job contains the output of `cat --help` as one would have expected.

```vim
" run.vim
function! s:runjob() abort
    call job_start('cat --help', {
            \ 'in_io': 'buffer',
            \ 'in_buf': bufnr('%'),
            \ 'out_io': 'buffer',
            \ 'out_name': 'joboutput',
            \ 'err_io': 'out'
            \ })
endfunction

command! Run call s:runjob()
```

**Expected behavior**
No error messages thrown since the job output is correct.

**Environment**
- Vim version: `8.1.1700` and `8.1.1486`
- Gentoo Linux
- Terminal: `xfce4-terminal` and `gvim`

**Comment by brammool** [comment]
I would think this happens because the job exits, thus Vim cannot write to its input.  With a small file the buffer is filled, but once the buffer is full it fails.  I think that is to be expected.

**Comment by bfrg** [comment]
Okay thanks. I thought Vim would handle such cases internally without reporting an error to the user.
I can work around this with a try-catch block but I'm not sure if that's the best approach:
```vim
try
    let job = job_start('somefilter', opts)
catch /^Vim\%((\a\+)\)\=:E631:/
endtry
```
This is a common scenario when running a filter like `awk`, `sed` or `jq` in the background on the current buffer which all expect a filter text and a file as input.

**Comment by brammool** [comment]
It should work fine if the job reads the input.  If it doesn't then that is an error that should be reported, otherwise ig goes unnoticed that the job didn't process all the lines.

**Comment by chrisbra** [comment]
I suppose this is no bug then and can be closed?
