### ISSUE TITLE
Not working plugins

### ISSUE THREAD

**Issue by tanrax** [vim/vim#469]
It only works if I open this route:
`vim .vimrc`
In all other cases not.

**Comment by chrisbra** [comment]
Please be more specific. What do you expect, what does not work. What plugins are you talking about? Please give step by step examples.

**Comment by tanrax** [comment]
![screen shot 2015-11-06 at 12 49 00](https://cloud.githubusercontent.com/assets/4553672/10996452/2a0deee8-8485-11e5-9cb4-9ad07114a3f4.jpg)
![screen shot 2015-11-06 at 12 49 12](https://cloud.githubusercontent.com/assets/4553672/10996451/2a0d3a84-8485-11e5-88f3-b0ab31661d83.jpg)
![screen shot 2015-11-06 at 12 49 23](https://cloud.githubusercontent.com/assets/4553672/10996450/2a0bcca8-8485-11e5-9364-b3690fcf50ea.jpg)
![screen shot 2015-11-06 at 12 51 29](https://cloud.githubusercontent.com/assets/4553672/10996449/2a0a8abe-8485-11e5-96c9-7ab096772ed0.jpg)

I can not use any plugins, but if I know I have them.

Pardon my English :)

**Comment by chrisbra** [comment]
Looks like you have those `:NerdTreeToggle` and `:TagbarToggle` in your .vimrc. By the time the .vimrc is read, the plugins are not yet loaded, so those commands will give errors. One solution would be to move those commands to a VimEnter autocommand call.

**Comment by tanrax** [comment]
I have made two plugins for example, but it happens to everyone. If I run the same applies. Before upgrading me everything works.

**Comment by chrisbra** [comment]
Can you show the output of `:scriptnames`

**Comment by tanrax** [comment]
1: ~/.vimrc
  2: /usr/local/Cellar/vim/7.4.903/share/vim/vim74/ftoff.vim
  3: /usr/local/Cellar/vim/7.4.903/share/vim/vim74/filetype.vim
  4: /usr/local/Cellar/vim/7.4.903/share/vim/vim74/ftplugin.vim
  5: /usr/local/Cellar/vim/7.4.903/share/vim/vim74/indent.vim
  6: /usr/local/Cellar/vim/7.4.903/share/vim/vim74/syntax/syntax.vim
  7: /usr/local/Cellar/vim/7.4.903/share/vim/vim74/syntax/synload.vim
  8: /usr/local/Cellar/vim/7.4.903/share/vim/vim74/syntax/syncolor.vim
  9: ~/.vim/colors/base16-default.vim
 10: ~/.vim/bundle/Vundle.vim/autoload/vundle.vim
 11: ~/.vim/bundle/Vundle.vim/autoload/vundle/config.vim
 12: /usr/local/Cellar/vim/7.4.903/share/vim/vim74/plugin/getscriptPlugin.vim
 13: /usr/local/Cellar/vim/7.4.903/share/vim/vim74/plugin/gzip.vim
 14: /usr/local/Cellar/vim/7.4.903/share/vim/vim74/plugin/logiPat.vim
 15: /usr/local/Cellar/vim/7.4.903/share/vim/vim74/plugin/matchparen.vim
 16: /usr/local/Cellar/vim/7.4.903/share/vim/vim74/plugin/netrwPlugin.vim
 17: /usr/local/Cellar/vim/7.4.903/share/vim/vim74/plugin/rrhelper.vim
 18: /usr/local/Cellar/vim/7.4.903/share/vim/vim74/plugin/spellfile.vim
 19: /usr/local/Cellar/vim/7.4.903/share/vim/vim74/plugin/tarPlugin.vim
 20: /usr/local/Cellar/vim/7.4.903/share/vim/vim74/plugin/tohtml.vim
 21: /usr/local/Cellar/vim/7.4.903/share/vim/vim74/plugin/vimballPlugin.vim
22: /usr/local/Cellar/vim/7.4.903/share/vim/vim74/plugin/zipPlugin.vim

**Comment by chrisbra** [comment]
So no plugins from vundle are loaded. That explains your errors. Please share your .vimrc Looks like there is an error on how the plugins are loaded. I can't however say much about this, as I don't use vundle.

**Comment by tanrax** [comment]
```
" CONFIGURACION
set nocompatible            
filetype off               
filetype plugin indent on
syntax on
set so=15
set spelllang=es
set number
set hlsearch
set nobomb
set ignorecase
set smartcase
set autoindent
set laststatus=2
set ar "Auto carga cambios en archivo, sin preguntar
set background=dark
colorscheme base16-default
imap `\ <Esc>
set tabstop=4      "Decides cuantos espacios es una tabulación 
set shiftwidth=4
set noexpandtab    "No convierte tabulaciones en espacio (Lo hace por defecto) 
"Clear last search highlighting
map <Space> :noh<cr>
" Quita el scroll en MacVim
set guioptions-=L
set guioptions-=r
set guioptions-=T
"Session-vim
let g:session_autosave = 'yes'
let g:session_autoload = 'yes'
let g:session_lock_directory = '/var/lock'
"NerdTree
map <C-n> :NERDTreeToggle<CR>
set autochdir
let NERDTreeChDirMode=2
let NERDTreeIgnore = ['\.pyc$', '\.swp$']
let NERDTreeShowHidden=1
"Tagbar
nmap <C-m> :TagbarToggle<CR>
let g:tagbar_ctags_bin = '/usr/local/Cellar/ctags/5.8_1/bin/ctags'
"Multicursor
let g:multi_cursor_next_key='<C-j>'
nmap  :setlocal spell spelllang=es_es<cr>
"Autocompletado
let g:neocomplcache_enable_at_startup = 1
"jsBeatify
map <c-f> :call JsBeautify()<cr>
autocmd FileType javascript noremap <buffer>  <c-f> :call JsBeautify()<cr>
autocmd FileType html noremap <buffer> <c-f> :call HtmlBeautify()<cr>
autocmd FileType css noremap <buffer> <c-f> :call CSSBeautify()<cr>
"EasyMotion
let g:EasyMotion_do_mapping = 0 
nmap s <Plug>(easymotion-s)
"CtrlP auto cache clearing.
let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|git'
function! SetupCtrlP()
  if exists("g:loaded_ctrlp") && g:loaded_ctrlp
      augroup CtrlPExtension
      autocmd!
      autocmd FocusGained  * CtrlPClearCache
      autocmd BufWritePost * CtrlPClearCache
      augroup END
  endif
endfunction
if has("autocmd")
  autocmd VimEnter * :call SetupCtrlP()
endif")"
"Yank Ring
map <C-g> :YRShow<CR>
let g:yankring_replace_n_pkey = '<C-e>'
let g:yankring_replace_n_nkey = '<C-h>'
let g:yankring_history_dir = '/Users/androsfenollosa/Documents'
"PHP
 function! PhpSyntaxOverride()
   hi! def link phpDocTags  phpDefine
     hi! def link phpDocParam phpType
     endfunction

     augroup phpSyntaxOverride
       autocmd!
         autocmd FileType php call PhpSyntaxOverride()
         augroup END
"Compilar Python -  Ctrl+l run
autocmd BufRead *.py set makeprg=python\ -c\ \"import\ py_compile,sys;\ sys.stderr=sys.stdout;\ py_compile.compile(r'%')\"
autocmd BufRead *.py set efm=%C\ %.%#,%A\ \ File\ \"%f\"\\,\ line\ %l%.%#,%Z%[%^\ ]%\\@=%m
autocmd BufRead *.py nmap <C-l> :w !python %<CR>
" Incsearch
map /  <Plug>(incsearch-forward)
map ?  <Plug>(incsearch-backward)
map g/ <Plug>(incsearch-stay)
" Typescript
let g:typescript_indent_disable = 1

"Vundle manage
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-fugitive'
Plugin 'scrooloose/nerdtree'
Plugin 'kien/ctrlp.vim'
Plugin 'scrooloose/nerdcommenter'
Plugin 'tomasr/molokai'
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'tomtom/tlib_vim'
Plugin 'garbas/vim-snipmate'
Plugin 'mattn/emmet-vim'
Plugin 'honza/vim-snippets'
Plugin 'othree/html5.vim'
Plugin 'pangloss/vim-javascript'
Plugin 'Lokaltog/vim-easymotion'
Plugin 'godlygeek/tabular'
Plugin 'kien/rainbow_parentheses.vim'
Plugin 'xolox/vim-session'
Plugin 'gorodinskiy/vim-coloresque'
Plugin 'bling/vim-airline'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'nono/jquery.vim'
Plugin 'xolox/vim-misc'
Plugin 'maksimr/vim-jsbeautify'
Plugin 'rizzatti/dash.vim'
Plugin 'jiangmiao/auto-pairs'
Plugin 'YankRing.vim'
Plugin 'tpope/vim-repeat'
Plugin 'StanAngeloff/php.vim'
Plugin 'shawncplus/phpcomplete.vim'
Plugin 'xsbeats/vim-blade'
Plugin 'rking/ag.vim'
Plugin 'gregsexton/MatchTag'
Plugin 'davidhalter/jedi-vim'
Plugin 'junegunn/goyo.vim'
Plugin 'haya14busa/incsearch.vim'
Plugin 'Shougo/neocomplcache.vim'
Plugin 'vitalk/vim-simple-todo'
Plugin 'chriskempson/base16-vim'
Plugin 'majutsushi/tagbar'
Plugin 'mklabs/vim-backbone'

" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal

```

**Comment by chrisbra** [comment]
Some things I notice:
- I think, the vundle setup should be on top of your .vimrc possibly the first things to setup after the `:set nocompatible`
- There is a call to vundle#end() missing
- The `:filetype plugin indent on` should be after the vundle#end() call

As I said, I don't know much about vundle. If this doesn't help and noone here chimes in to help, you better take this to the vundle issue tracker.

**Comment by tanrax** [comment]
Still not working. I will try to tell in your repository. Thanks for the effort and your advice :)

**Comment by tanrax** [comment]
Solution:  add call vundle#end()after plugin list

**Comment by Shougo** [comment]
@tanrax This problem is resolved?

**Comment by tanrax** [comment]
Yes!
