### ISSUE TITLE
Gvim can't load libraries for Perl/Python under Windows

### ISSUE THREAD

**Issue by lkintact** [vim/vim#4690]
1. Put `perl528.dll` from `http://strawberryperl.com/download/5.28.2.1/strawberry-perl-5.28.2.1-32bit.zip` to `C:\Windows`

2. Put `python37.dll` from `https://www.python.org/ftp/python/3.7.3/python-3.7.3-embed-win32.zip` to `C:\Windows`

3. Unzip the contents of `https://github.com/vim/vim-win32-installer/releases/download/v8.1.1705/gvim_8.1.1705_x86_signed.zip` somewhere within the user home folder, enter the `vim81` folder and run `gvim.exe -u NONE --cmd "language messages English"`

4. Try executing `:perl VIM::Msg("Hello")`, gvim outputs
```
E370: Could not load library perl528.dll
Sorry, this command is disabled: the Perl library could not be loaded.   
```                                                      
5. Try executing `:py3 print("Hello")`, gvim outputs
```
E370: Could not load library python37.dll
E263: Sorry, this command is disabled, the Python library could not be loaded.   
```                                              

I also tried putting the dlls to other directories within PATH and manually setting paths in `'perldll'` and `'pythonthreedll'`, but it didn't help.

OS: Windows 10 Home 1803 (Russian)

**Comment by mattn** [comment]
Generally, dll probably be depend on another dlls. You need to extract all files in the zip file and set PATH environment variable to the extracted directory.

**Comment by lkintact** [comment]
Thank you, @mattn, doing what you'd advised helped. I think the size of the libraries and the fact that sometimes dlls work "autonomously", so to speak, somehow convinced me that the libraries themselves would be enough... Closing the issue.
