### ISSUE TITLE
Provide list of / info about builtin functions / commands

### ISSUE THREAD

**Issue by blueyed** [vim/vim#4700]
For https://github.com/vim-jp/vim-vimlparser it would be useful to have a method/function(s) to get the list of builtin functions and commands.

Currently builtin commands get parsed out of `vim/src/ex_cmds.h` manually (https://github.com/vim-jp/vim-vimlparser/blob/edd6a79ebf52930452aeaec13e5a6f9423896379/scripts/update_builtin_commands.vim), and has the following format: https://github.com/vim-jp/vim-vimlparser/blob/edd6a79ebf52930452aeaec13e5a6f9423896379/autoload/vimlparser.vim#L1978

The list of builtin functions is hardcoded (https://github.com/vim-jp/vim-vimlparser/issues/118).
Unlike commands there is no additional info stored with them, but it might certainly be useful to have the number of expected args for example available there then.

(Neovim has `nvim_get_commands` already, but only for non-builtins.)

**Comment by brammool** [comment]
> For https://github.com/vim-jp/vim-vimlparser it would be useful to
> have a method/function(s) to get the list of builtin functions and
> commands.

Shouldn't that be "vim script parser"?

> Currently builtin commands get parsed out of `vim/src/ex_cmds.h`
> manually
> (https://github.com/vim-jp/vim-vimlparser/blob/edd6a79ebf52930452aeaec13e5a6f9423896379/scripts/update_builtin_commands.vim),
> and has the following format:
> https://github.com/vim-jp/vim-vimlparser/blob/edd6a79ebf52930452aeaec13e5a6f9423896379/autoload/vimlparser.vim#L1978
> 
> The list of builtin functions is hardcoded
> (https://github.com/vim-jp/vim-vimlparser/issues/118).
> Unlike commands there is no additional info stored with them, but it might certainly be useful to have the number of expected args for example available there then.
> 
> (Neovim has `nvim_get_commands` already, but only for non-builtins.)

It is not generally useful functionality, thus I would prefer this works
with existing code.

You can use ":func" and parse the output.  One problem is that the
functions available depend on the build options.  If you want all
builtin functions, you need to get the table from src/evalfunc.c

-- 
<Beeth> Girls are like internet domain names,
        the ones I like are already taken.
<honx>  Well, you can stil get one from a strange country :-P

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by tyru** [comment]
@blueyed Thanks for opening this issue for vimlparser :smile: 
I've created the script which parses evalfunc.c as @brammool said.
I think it works well.

**Comment by blueyed** [comment]
> Shouldn't that be "vim script parser"?

See https://github.com/vim-jp/vim-vimlparser#about-project-name.

Thanks everybody, closing then.
