### ISSUE TITLE
Adding new flags to :let-heredoc breaks compatibility

### ISSUE THREAD

**Issue by tyru** [vim/vim#4705]
## Problem

This is a normal heredoc example.

```vim
let text =<< trim END
  if ok
    echo 'done'
  endif
END
```

If we wants new flags like `eol` other than `trim`,
the existing code like below will not work.

```vim
" eol is not flag!
let text =<< trim eol
  if ok
    echo 'done'
  endif
eol
```

Or some useful flags if available

* `trim_left`: if specified, trim only left
* `trim_right`: if specified, trim only right
* `template`: if specified, template string can be used in heredoc (#4634)
* `escape(chars)`: if specified, specified characters are escaped by backslash

## Solution

* Make flags is lowercase letters only
* Make marker is uppercase letters only (if omitted, "." is used)

It gets rid of ambiguity from :let-heredoc, and guarantees forward compatibility.

---

And, if possible, I would like marker to be required parameter.
Currently "." is used if omitted, but it may confuse users? 🤔 

```vim
" oops! "END" is missing
let text =<< trim
  if ok
    echo 'done'
  endif
END
```

**Comment by tyru** [comment]
> * Make flags is lowercase letters only
> * Make marker is uppercase letters only (if omitted, "." is used)

Sorry for ambiguous specification.
"lowercase" means : `^[a-z][a-z0-9_]*$`
"uppercase" means: `^[A-Z][A-Z0-9_]*$`

**Comment by mattn** [comment]
I prefer the marker is `^[A-Z_][A-Z0-9_]*$` for `__EOS__`.

**Comment by aiya000** [comment]
I think

**Comment by brammool** [comment]
It would be sufficient to disallow the marker to start with a lower case letter.  Can still use TextEnd, for example.
