### ISSUE TITLE
exepath() / mch_can_exe does not consider "bin/true" to be executable (in "/")

### ISSUE THREAD

**Issue by blueyed** [vim/vim#4710]
```vim
lcd /
echo exepath('bin/true')
```

`mch_can_exe` only assumes non-absolute paths starting with "./" or "../" to be executable (https://github.com/vim/vim/blob/acf7544cf62227972eeb063d6d9ecddaa5682a73/src/os_unix.c#L3098-L3108), but it is also enough for a slash to be in there.

**Comment by brammool** [comment]
Daniel Hahler wrote:

> ```vim
> lcd /
> echo exepath('bin/true')
> ```
> 
> `mch_can_exe` only assumes non-absolute paths starting with "./" or "../" to be executable (https://github.com/vim/vim/blob/acf7544cf62227972eeb063d6d9ecddaa5682a73/src/os_unix.c#L3098-L3108), but it is also enough for a slash to be in there.

The docs also say that it should work.  And ":!bin/true" works.
So this needs to be fixed.

-- 
Communication is one of the most compli..., eh, well, it's hard.
You know what I mean.  Not?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by blueyed** [comment]
> And ":!bin/true" works.

That's because it uses the shell.

It also works in `job_start`, which does not check if it is executable (unlike Neovim does, where I've noticed this).

Do you think the patch in https://github.com/neovim/neovim/pull/10556/files is fine, i.e. only checking for a slash here?  (`os_can_exe` is built on Vim's `mch_can_exe`)

**Comment by blueyed** [comment]
In particular `exepath()` should probably always return something if `executable()` is true.

**Comment by blueyed** [comment]
Slightly related: https://github.com/vim/vim/pull/3282 and https://github.com/vim/vim/pull/3283.

**Comment by brammool** [comment]
> > And ":!bin/true" works.
> 
> That's because it uses the shell.
> 
> It also works in `job_start`, which does not check if it is executable
> (unlike Neovim does, where I've noticed this).
> 
> Do you think the patch in
> https://github.com/neovim/neovim/pull/10556/files is fine, i.e. only
> checking for a slash here?  (`os_can_exe` is built on Vim's
> `mch_can_exe`)

That looks OK.  I wonder if we need to do anything for 'shellslash'.

And yes, it should be in sync with exepath().


-- 
Mynd you, m00se bites Kan be pretty nasti ...
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
