### ISSUE TITLE
E154: Duplicate tag "test-functions" in file /path/to/usr_41.txt

### ISSUE THREAD

**Issue by rbtnn** [vim/vim#4714]
**Describe the bug**
`E154: Duplicate tag "test-functions"` occurs.

**To Reproduce**
1. `helptags ALL`

**Screenshots**
<img width="784" alt="a" src="https://user-images.githubusercontent.com/1595779/61596177-224c8980-ac3b-11e9-85ac-7129b7c168dc.png">

**Environment (please complete the following information):**
 - Vim version [8.1.1727]

**Comment by brammool** [comment]
I'll fix it.
