### ISSUE TITLE
When deleting an entire buffer using deletebufline(), the text appended to the same buffer using appendbufline() isn't immediately visible

### ISSUE THREAD

**Issue by bfrg** [vim/vim#4718]
**Describe the bug**
When deleting all lines of a buffer using `deletebufline(buf, 1, '$')` and appending new lines at the end with `appendbufline(buf, '$', {text})`, the new text won't be visible until the focus is moved to the window displaying `buf`.
This happens **only** when previously the window displaying `buf` has been scrolled up such that the first line isn't visible and during the two `*bufline(buf, ...)` calls the focus is on another window that doesn't display the buffer `buf`.

**To Reproduce**
Run `vim --clean`.
1. Create a new window with a new file, then move the focus back to the previous window `[No Name]`:
```vim
new foo
let winnr = bufwinnr('foo')
let buf = bufnr('foo')
wincmd p
```
2. Append some text to the buffer `buf` and put the cursor on the last line. Make sure that the first line isn't visible anymore. Then move the focus back to the previous window `[No Name]`:
```vim
call appendbufline(buf, '$', range(1,200))
execute winnr . 'wincmd w'
normal! G
wincmd p
```
3. Delete all lines of the buffer using `deletebufline()` and append new text at the end of the same buffer, while focus is on the window `[No Name]`:
```vim
call deletebufline(buf, 1, '$')
call appendbufline(buf, '$', 'Hello Vim world...')
```
4. Result: The newly appended text isn't visible until the focus is moved to the window displaying `buf`.
Vim doesn't seem to fully scroll down the window after deleting the entire buffer with `deletebufline(buf, 1, '$')`. This is noticeable by the `EndOfBuffer` filler lines `~`. The very first line in the window contains a `~`, hence it can't be the first line of the buffer. When `number` is turned on, the line number column isn't visible either until the focus is moved to the window containing the modified buffer.

**Expected behavior**
The changes that are made to a buffer using `deletebufline()` and `appendbufline()` should be visible without having to move focus to the window displaying the buffer that has been changed.

**Environment**
- Vim version: `master`
- OS: `Gentoo Linux`
- Terminal: `xfce4-terminal`

**Additional Context**
I noticed this when a job was writing to a visible buffer while the focus was on another window.
Before every `job_start()` call, the previous content of the buffer is cleared using `deletebufline()`.  While `stdout` is written directly to the buffer, `stderr` is first preprocessed before also being appended to the same buffer:
```vim
call deletebufline(buf, 1, '$')
call job_start(cmd, {
    \ 'out_io': 'buffer',
    \ 'out_buf': buf,
    \ 'err_io': 'pipe', 
    \ 'err_cb': {_, msg -> appendbufline(buf, '$', '>>> ' . msg}
    \ })
```
Every time the job output is larger than the window height, the error messages of the next job won't be displayed -- at least not until the focus is moved to the window displaying the buffer the job writes to.

**Comment by chrisbra** [comment]
This might need a patch like the following:

```patch
From 237d24071579f626973e4be4bf148f3bc4522eaa Mon Sep 17 00:00:00 2001
From: Christian Brabandt <cb@256bit.org>
Date: Wed, 24 Jul 2019 11:49:55 +0200
Subject: [PATCH] Force redraw for appendbufline()

---
 src/evalfunc.c                              |  8 ++++++
 src/testdir/dumps/Test_appendbufline_1.dump | 10 +++++++
 src/testdir/test_bufline.vim                | 29 +++++++++++++++++++++
 3 files changed, 47 insertions(+)
 create mode 100644 src/testdir/dumps/Test_appendbufline_1.dump

diff --git a/src/evalfunc.c b/src/evalfunc.c
index 8b9fba02c..21a356c41 100644
--- a/src/evalfunc.c
+++ b/src/evalfunc.c
@@ -1309,6 +1309,7 @@ set_buffer_lines(
     buf_T	*curbuf_save = NULL;
     win_T	*curwin_save = NULL;
     int		is_curbuf = buf == curbuf;
+    int		RedrawingDisabled_save = RedrawingDisabled;
 
     /* When using the current buffer ml_mfp will be set if needed.  Useful when
      * setline() is used on startup.  For other buffers the buffer must be
@@ -1413,6 +1414,13 @@ set_buffer_lines(
 
     if (!is_curbuf)
     {
+	if (RedrawingDisabled_save)
+	    --RedrawingDisabled;
+
+	// force a redraw
+	update_curbuf(SOME_VALID);
+	if (RedrawingDisabled_save)
+	    ++RedrawingDisabled;
 	curbuf = curbuf_save;
 	curwin = curwin_save;
     }
diff --git a/src/testdir/dumps/Test_appendbufline_1.dump b/src/testdir/dumps/Test_appendbufline_1.dump
new file mode 100644
index 000000000..7938469f8
--- /dev/null
+++ b/src/testdir/dumps/Test_appendbufline_1.dump
@@ -0,0 +1,10 @@
+| +0&#ffffff0@74
+| +3&&@1|l+0&&@1|o| |V|i|m| |w|o|r|l|d|.@2| @56
+|~+0#4040ff13&| @73
+|~| @73
+|f+1#0000000&|o@1| |[|+|]| @49|1|,|0|-|1| @9|A|l@1
+> +0&&@74
+|~+0#4040ff13&| @73
+|~| @73
+|[+3#0000000&|N|o| |N|a|m|e|]| @47|0|,|0|-|1| @9|A|l@1
+|-+0&&@1|N|o| |l|i|n|e|s| |i|n| |b|u|f@1|e|r|-@1| @52
diff --git a/src/testdir/test_bufline.vim b/src/testdir/test_bufline.vim
index dbcd2e0fd..30afc7792 100644
--- a/src/testdir/test_bufline.vim
+++ b/src/testdir/test_bufline.vim
@@ -1,6 +1,7 @@
 " Tests for setbufline(), getbufline(), appendbufline(), deletebufline()
 
 source shared.vim
+source screendump.vim
 
 func Test_setbufline_getbufline()
   new
@@ -144,3 +145,31 @@ func Test_deletebufline()
   call assert_equal(['b', 'c'], getbufline(b, 1, 2))
   exe "bwipe! " . b
 endfunc
+
+func OtherWindowCommon()
+endfunc
+
+func Test_appendbufline_redraw()
+  if !CanRunVimInTerminal()
+    throw 'Skipped: cannot make screendumps'
+  endif
+  let lines =<< trim END
+    new foo
+    let winnr=bufwinnr('foo')
+    let buf=bufnr('foo')
+    wincmd p
+    call appendbufline(buf, '$', range(1,200))
+    exe winnr. 'wincmd w'
+    norm! G
+    wincmd p
+    call deletebufline(buf, 1, '$')
+    call appendbufline(buf, '$', 'Hello Vim world...')
+  END
+  call writefile(lines, 'XscriptMatchCommon')
+  let buf = RunVimInTerminal('-S XscriptMatchCommon', #{rows: 10})
+  call term_wait(buf)
+  call VerifyScreenDump(buf, 'Test_appendbufline_1', {})
+
+  call StopVimInTerminal(buf)
+  call delete('XscriptMatchCommon')
+endfunc
-- 
2.20.1
```

**Comment by bfrg** [comment]
The patch works for me, thank you. But shouldn't the redrawing happen already after `call deletebufline(buf, 1, '$')`?
When the first line of the buffer `foobar` is visible and I `call deletebufline(bufnr('foobar'), 1, '$')` I see the following (`number` is turned on in the upper window):
![screenshot-2019-07-25_103243](https://user-images.githubusercontent.com/6266600/61859003-8c795e80-aec7-11e9-8e1f-8797694e2bc0.png)

But when I scroll the window down so that the first line isn't visible anymore and I `call deletebufline(bufnr('foobar'), 1, '$')`, I literally see an empty buffer:
![screenshot-2019-07-25_103531](https://user-images.githubusercontent.com/6266600/61859234-06114c80-aec8-11e9-951d-510b9fd76691.png)

Adding one line to the buffer with `call appendbufline(bufnr('foobar'), '$', 'Hello World')` will add `Hello World` **after** the first line. The buffer now has two lines:
![screenshot-2019-07-25_104018](https://user-images.githubusercontent.com/6266600/61859616-c008b880-aec8-11e9-93a3-57cd288593b8.png)

I think the first line should become visible already after deleting the entire buffer, like in the first image.

**Comment by brammool** [comment]
Christian wrote:

> This might need a patch like the following:

This redraws while the current buffer is temporarily changed.  That's a
bit dangerous, I'm not sure what will happen.

I think we can call update_topline(), since that's what we actually
want: Fix the lines being displayed for the newly added lines.

Thanks for the test.

-- 
BLACK KNIGHT: The Black Knight always triumphs. Have at you!
   ARTHUR takes his last leg off.  The BLACK KNIGHT's body lands upright.
BLACK KNIGHT: All right, we'll call it a draw.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
