### ISSUE TITLE
matchdelete(id, win) doesn't remove the highlighting of the match when called from another window

### ISSUE THREAD

**Issue by bfrg** [vim/vim#4720]
**Describe the bug**
When `matchdelete(id, winnr)` is called from another window, the match `id` is deleted but the highlighting of the match remains until a `:redraw!` or `<C-L>`. This occurs only when the focus is on another window. Calling `matchdelete(id, winnr)` while window `winnr` is focused, everything works fine.

**To Reproduce**
1. Run `vim --clean`.
2. Type `Hello Vim world` into the buffer.
3. Then run:
```vim
let mid = matchadd('Error', 'world', 1)
new
call matchdelete(mid, 2)
```
The word `world` is still highlighted even though the match `mid` has been removed. Pressing `<C-L>` clears the highlighting.

**Expected behavior**
Always clear the highlighting without needing to run `:redraw!` or `<C-L>` afterwards, even when the focus is on another window.

**Environment**
- Vim version: `master`
- Gentoo Linux
- xfce4-terminal

**Comment by andymass** [comment]
There are two other functions which use `redraw_later` that maybe should use `redraw_win_later`; `match_add` and `clear_matches`.

By the way, `f_clearmatches` is still in `evalfunc.c`

```diff
--- a/src/highlight.c
+++ b/src/highlight.c
@@ -3850,7 +3850,7 @@ match_add(
        prev->next = m;
     m->next = cur;

-    redraw_later(rtype);
+    redraw_win_later(wp, rtype);
     return id;

 fail:
@@ -3932,7 +3932,7 @@ clear_matches(win_T *wp)
        vim_free(wp->w_match_head);
        wp->w_match_head = m;
     }
-    redraw_later(SOME_VALID);
+    redraw_win_later(wp, SOME_VALID);
 }
```

**Comment by brammool** [comment]
Andy Massimino wrote:

> There are two other functions which use `redraw_later` that maybe
> should use `redraw_win_later`; `match_add` and `clear_matches`.

Good catch!

> By the way, `f_clearmatches` is still in `evalfunc.c`

Should have named the functions match_*() so they sort together.

-- 
If you don't get everything you want, think of
everything you didn't get and don't want.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
