### ISSUE TITLE
setting 'ttimeoutlen' to a low value makes the file written by `$ vim -w file` hard to read

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#4725]
I have a shell function which starts Vim with the `-w /tmp/.vimkeys` command-line option to make Vim write any key I press in a file. When something unexpected happens in Vim, I quit the program and open `/tmp/.vimkeys` to read what were the last keys I pressed. This is mainly helpful to detect when the lhs of a mapping has been poorly chosen because it's too easy to type by accident.

I also set the value of the `'ttimeoutlen'` option to 6. I need a low value for the lhs of some of my mappings not to be intepreted as keycodes.

Unfortunately, doing so alters the contents of the file written in `/tmp/.vimkeys`.
Here is a list of some unexpected characters which appear frequently in the file, but that I never press:

    
    ¢
    ¤
    ¦
    µ
    Ã
    ý
    ÿ

The first character is not correctly represented, but here is what the `ga` command says about it:

    <<80>> 128, Hex 0080, Oct 200, Digr PA

I've noticed that the issue appears only when `'ttimeoutlen'` is set below a certain threshold.  
But the latter can vary, and I'm not sure what influences this variation.
On my machine, in xterm(322), this threshold seems to be somewhere around 300ms.

The issue also affects the contents of a recording. That is, after recording some keys in the register `q`, the output of `:echo @q` can contain unexpected characters.
For example, if I record the two keys `A` and `Escape`, then the output of `:echo @q` is `A^[<80><fd>a`.  

![gif](https://user-images.githubusercontent.com/8505073/61762945-eac51500-add3-11e9-927d-1813f2cbc4f2.gif)

I would expect just `A^[`.

Can this issue be fixed without increasing the value of `'ttimeoutlen'`?

If not, is there a way to substitute the unexpected characters recorded by the `-w` shell command-line option with the keys which were really pressed?

I don't think it's as easy as removing all of them, because I can see a lot of backticks in the file, which is a valid key, but I don't press it that often. This makes me think that some of those unexpected keys are combined with some valid keys to represent keys which were actually pressed.

**Environment:**

   - Vim version: 8.1.1735
   - OS: Ubuntu 16.04
   - Terminal: xterm

**Comment by chrisbra** [comment]
I suppose such a low ttimeoutlen value makes you see the internal representation of the keys.

**Comment by lacygoill** [comment]
Thank you very much for the explanation.
I could try to increase the timeout a little, but in xterm I can reproduce the issue even up to 250ms, which is already too long for me.

**Comment by lacygoill** [comment]
Closing because I have found 2 workarounds.  These commands clean a logfile for the most part:

    if search('\%x80') > 0
        sil keepj keepp :%s/\%x80ý[`a]//ge
        sil keepj keepp :%s/\%x80F\([2-9A-R]\)/\=CleanVimKeylogRep()/ge
        return
    endif

    def CleanVimKeylogRep(): string
        var s: string = "\e"
        var m: string = submatch(1)
        if m =~ '^\d$'
            s ..= (m->char2nr() + 47)->nr2char()
        else
            s ..= (m->char2nr() + 40)->nr2char()
        endif
        return s
    enddef

Alternatively, `ch_logfile('logfile', 'w')` can log the keypresses.  And this command can clean the noise:

    :v/raw key input/d _

---

Unrelated to this issue, but it has always bothered me how this pseudo-key was written in the output of `:set termcap`:

    <SgrMouseRelelase> ^[[<*m

I think it should be `<SgrMouseRelease>`; there seems to be a typo.  I never reported the issue because I thought it would break old Vim scripts.  Anyway, here is a patch:
```diff
diff --git a/src/misc2.c b/src/misc2.c
index 5a6d86352..6fb75d9dc 100644
--- a/src/misc2.c
+++ b/src/misc2.c
@@ -2497,7 +2497,7 @@ static struct key_name_entry
     {K_URXVT_MOUSE,	(char_u *)"UrxvtMouse"},
 #endif
     {K_SGR_MOUSE,	(char_u *)"SgrMouse"},
-    {K_SGR_MOUSERELEASE, (char_u *)"SgrMouseRelelase"},
+    {K_SGR_MOUSERELEASE, (char_u *)"SgrMouseRelease"},
     {K_LEFTMOUSE,	(char_u *)"LeftMouse"},
     {K_LEFTMOUSE_NM,	(char_u *)"LeftMouseNM"},
     {K_LEFTDRAG,	(char_u *)"LeftDrag"},
```
