### ISSUE TITLE
Enable GVIM to natively run in Wayland

### ISSUE THREAD

**Issue by ghost** [vim/vim#4727]
Wayland is future. GVIM runs in XWAYLAND in WAYLAND. Get RID of any X related code in GVIM,so that GVIM can run natively in Wayland without XWAYLAND

**Comment by chrisbra** [comment]
Note, this is a community project. That means we don't have to do what you or anybody else demands. 
However, if you really want that, well, now that is your chance to contribute to a wellknown open source project ... 😉

**Comment by ghost** [comment]
I wasn't demanding. ;(

**Comment by chrisbra** [comment]
sounded very much like it

**Comment by nuko8** [comment]
@varshitgithub 

> Wayland is future. GVIM runs in XWAYLAND in WAYLAND. Get RID of any X related code in GVIM,so that GVIM can run natively in Wayland without XWAYLAND

As written in `:h development`, Vim needs to take into account its own design goals and decisions.  Perhaps, one of them which is related to the current context would be  "Vim tries to help as many users on as many platforms as possible."  At present, if I understand correctly, WAYLAND is still not ubiquitous as much as X11 to UNIX or UNIX-like systems other than Linux.  So it sounds to me that getting rid of any X related code in gVim is a fairly radical proposal which is effectively asking Vim to change the design goal.  Accordingly, we need to hear/discuss further rationale for doing ~way~ away with the X11 code to make us sure why it's the right thing to do, though I won't be against the idea that gVim should run with WAYLAND natively when it's available.

**Comment by brammool** [comment]
Let's just keep this issue as the title says: Add native Wayland support.
We can get rid of X support when all existing computers support Wayland.  Might be a while.

**Comment by ghost** [comment]
> @varshitgithub
> 
> > Wayland is future. GVIM runs in XWAYLAND in WAYLAND. Get RID of any X related code in GVIM,so that GVIM can run natively in Wayland without XWAYLAND
> 
> As written in `:h development`, Vim needs to take into account its own design goals and decisions. Perhaps, one of them which is related to the current context would be "Vim tries to help as many users on as many platforms as possible." At present, if I understand correctly, WAYLAND is still not ubiquitous as much as X11 to UNIX or UNIX-like systems other than Linux. So it sounds to me that getting rid of any X related code in gVim is a fairly radical proposal which is effectively asking Vim to change the design goal. Accordingly, we need to hear/discuss further rationale for doing ~way~ away with the X11 code to make us sure why it's the right thing to do, though I won't be against the idea that gVim should run with WAYLAND natively when it's available.

At present GVIM runs in XWAYLAND in WAYLAND.And It runs natively in X. 
What I prefer is GVIM running natively in WAYLAND(without using Xwayland) as well as in X. many apps run natively in both X and Wayland and it doesn't hurt any compatibility issues.
App will only use Xwayland if it uses some X related technologies,otherwise it runs natively under both circumstances

**Comment by gbarta** [comment]
There is a native wayland backend for gtk, so am I right in thinking that a first pass this doesn't require a brand new gui backend but initially just involves allowing a compile using FEAT_GUI_GTK without FEAT_X11?  At least initially this would also involve disabling related features which access the X api like x clipboard, mksession, clientserver etc.

**Comment by lilydjwg** [comment]
I've just got gvim running on pure Wayland. I haven't do a lot of tests yet. It just runs, and clipboards work. If anyone feels like experiment with it, please try out and report any problems to me.

The code is at https://github.com/lilydjwg/vim/tree/wayland.

**Comment by tylerszabo** [comment]
@lilydjwg I tested your build locally and it's great right away: the quality of text rendering with scaling is immediately noticeable. When going through X the antialising is stretched and everything looks fuzzy but with these Wayland changes it's sharp.

I'd love for this behavior to make upstream. What criteria would need to be met to get it there?

**Comment by lilydjwg** [comment]
@tylerszabo I hesitate to send a pull request because there are two issues:

1. no +clientserver anymore
2. no clipboard support in the terminal (it still can reach the xwayland clipboard but it won't be synchronized with the wayland one since no X window is in focus)

**Comment by tylerszabo** [comment]
If the Wayland support were added such that a feature flag of `+wayland` could control compilation then having an issue where an option such as `+clientserver` is unavailable might be tolerable. I'd drop that feature in a heartbeat to make gvim usable on my laptop monitor.

In my testing I was able to use `"+p` and `"*p` to paste the clipboard selection and primary selection from a gnome-terminal window and `"+y` and  `"*y` from gvim to a gnome-terminal. There there was some nuanced behavior in that whenever I yank into `+` the same thing will get populated in `*` however, if I yank first into `+` then next into `*` then I get what I expect (middle click pastes from `*`, selecting "paste" pastes from `+`). Konsole seems to have the same behavior so even if there's some GTK fanciness at play it looks like QT is on board. Xterm was a bit more of a pain to test with but middle click would paste the `*` reliably and then changing VT options to use "select to clipboard" I was able to paste `+` and confirm that each selection was being independently maintained.

Is there a select workflow I'm missing?

**Comment by lilydjwg** [comment]
I've sent #9639 and let's see what the devs say about it.

**Comment by jclsn** [comment]
I just tried it. The clipboard+ functionality doesn't work for me unfortunately.

**Comment by chrisbra** [comment]
#9639 has been merged as patch [v9.1.0064](https://github.com/vim/vim/releases/tag/v9.1.0064) so closing it

**Comment by ronny-rentner** [comment]
For people missing clientserver support, I've managed to work around it using 'socat' like I've put 

```
function! RemoteHandler(chan, msg)
  echom 'Received: ' . a:msg
  execute a:msg
endfunction

let g:listener = job_start(['socat', 'UDP-RECVFROM:5000,ip-add-membership=224.0.0.123:127.0.0.1,reuseaddr,fork', '-'],
      \ {'out_mode': 'nl', 'out_cb': 'RemoteHandler'})
```

and then you can send commands to all your vim instances like:
```
echo 'tabnew' | socat - UDP-DATAGRAM:224.0.0.123:5000,ip-multicast-if=127.0.0.1,ip-multicast-loop=1
```

Of course you can filter it down further in the RemoteHandler to target specific vim instances etc.

**Comment by dezza** [comment]
> For people missing clientserver support, I've managed to work around it using 'socat' like I've put this in my .vimrc
Nice one, thanks. I found I had to add `XAUTHORITY` to env to get it working in gvim.
