### ISSUE TITLE
Visual block instert fail

### ISSUE THREAD

**Issue by kurkale6ka** [vim/vim#473]
Steps to reproduce:

Create a file with contents:

```
1 lorem
2 bla
```

Now, `:set ve=all`

Go in virtual column 7 on the first line and start visual block mode with `^v`, then `j`

Now when trying `I@`, we get:

```
1 lorem  @
2 bla
```

instead of:

```
1 lorem @
2 bla   @
```

Note `A@` does what we want

Tested with `Vim 7.4`, `1-884` (`vim -nNX -u NONE`)

**Comment by vim-ml** [comment]
Hi Dimitar!

On Di, 10 Nov 2015, Dimitar Dimitrov wrote:

> Steps to reproduce:
> 
> Create a file with contents:
> 
> ```
> 1 lorem
> 2 bla
> ```
> 
> Now, `:set ve=all`
> 
> Go in virtual column 7 on the first line and start visual block mode with `^v`, then `j`
> 
> Now when trying `I@`, we get:
> 
> ```
> 1 lorem  @
> 2 bla
> ```
> 
> instead of:
> 
> ```
> 1 lorem @
> 2 bla   @
> ```
> 
> Note `A@` does what we want
> 
> Tested with `Vim 7.4`, `1-884` (`vim -nNX -u NONE`)

block editing is a little bit tricky, but I think the attached patch 
fixes it. Please check (includes a test to verify)

Best,

## Christian

Man soll Denken lehren, nicht Gedachtes.
        -- Cornelius Gustav Gurlitt

**Comment by kurkale6ka** [comment]
Hi Christian,

Thanks for looking into this. I don't see a patch attached but since you create a test too, I reckon it's just ok to include the patch

**Comment by k-takata** [comment]
You can find the patch at here: https://groups.google.com/d/msg/vim_dev/ONNfEBHlD3Q/3YtxlEqBBAAJ

**Comment by chrisbra** [comment]
Okay, this is done intentionally, as it is mentioned briefly at :h v_b_A (see the Note section). So closing
