### ISSUE TITLE
Make sc_col (max room for messages) available as readonly setting

### ISSUE THREAD

**Issue by blueyed** [vim/vim#4732]
`sc_col` is internally used to decide if a more prompt ("hit-enter") is required with long messages.

For plugins it is often useful to avoid that, and truncate messages accordingly.

But it is hard to do so, since it depends on the settings `&showcmd` and `&ruler` (which might even have a dynamic/non-standard width).

Therefore it would be useful to have something like `v:max_msg_room` (needs a better name), which could be used for this.

Related code (`comp_col`): https://github.com/vim/vim/blob/1f164b19685d8ad709b11f3f1933685469251e30/src/option.c#L10825-L10869

**Comment by blueyed** [comment]
Note that tricks like setting `noshowcmd` temporarily will avoid the hit-enter prompt eventually, but the tail of the message then still gets overwritten when resetting it after the `echo` again.

**Comment by blueyed** [comment]
Of course it would also be great to have function that formats a string already, handling the truncation therein (left, right, middle, and/or similar as with the 'statusline' setting/format).
Still the readonly property could be useful in general.

**Comment by blueyed** [comment]
Maybe also a new ":echo_trunc" command could be added, which would automatically truncate it to the max width ("sc_col")?  (but then there could/should be options to either truncate it in the middle or the end also somehow probably)

I've found that there is `msg_strtrunc` already (https://github.com/vim/vim/blob/f1e0544d413b8b2ea129db0655b4e123d54177a6/src/message.c#L195-L236), which also gets used via `set shortmess+=T`, but not in ex mode.
This could be used for a helper function to truncation then maybe.

The following adds a `v:maxechospace` var, based on `sc_col`:  (patch based on Neovim's source):
```diff
 src/nvim/eval.c   | 2 ++
 src/nvim/eval.h   | 1 +
 src/nvim/option.c | 1 +
 3 files changed, 4 insertions(+)

diff --git i/src/nvim/eval.c w/src/nvim/eval.c
index 8f6d6cd55..8d65e6923 100644
--- i/src/nvim/eval.c
+++ w/src/nvim/eval.c
@@ -395,6 +395,7 @@ static struct vimvar {
   VV(VV_OP,             "operator",         VAR_STRING, VV_RO),
   VV(VV_SEARCHFORWARD,  "searchforward",    VAR_NUMBER, 0),
   VV(VV_HLSEARCH,       "hlsearch",         VAR_NUMBER, 0),
+  VV(VV_MAXECHOSPACE,   "maxechospace",     VAR_NUMBER, 0),
   VV(VV_OLDFILES,       "oldfiles",         VAR_LIST, 0),
   VV(VV_WINDOWID,       "windowid",         VAR_NUMBER, VV_RO_SBX),
   VV(VV_PROGPATH,       "progpath",         VAR_STRING, VV_RO),
@@ -621,6 +622,7 @@ void eval_init(void)
   set_vim_var_nr(VV_STDERR,   CHAN_STDERR);
   set_vim_var_nr(VV_SEARCHFORWARD, 1L);
   set_vim_var_nr(VV_HLSEARCH, 1L);
+  set_vim_var_nr(VV_MAXECHOSPACE, sc_col);
   set_vim_var_nr(VV_COUNT1, 1);
   set_vim_var_nr(VV_TYPE_NUMBER, VAR_TYPE_NUMBER);
   set_vim_var_nr(VV_TYPE_STRING, VAR_TYPE_STRING);
diff --git i/src/nvim/eval.h w/src/nvim/eval.h
index abe032a96..68a10aa3e 100644
--- i/src/nvim/eval.h
+++ w/src/nvim/eval.h
@@ -91,6 +91,7 @@ typedef enum {
     VV_OP,
     VV_SEARCHFORWARD,
     VV_HLSEARCH,
+    VV_MAXECHOSPACE,
     VV_OLDFILES,
     VV_WINDOWID,
     VV_PROGPATH,
diff --git i/src/nvim/option.c w/src/nvim/option.c
index 699f17acc..deb140e1c 100644
--- i/src/nvim/option.c
+++ w/src/nvim/option.c
@@ -5456,6 +5456,7 @@ void comp_col(void)
   if (ru_col <= 0) {
     ru_col = 1;
   }
+  set_vim_var_nr(VV_MAXECHOSPACE, sc_col - 1);  // -1 for newline being added
 }
 
 // Unset local option value, similar to ":set opt<".
```

This allows for:
```vim
let toolong = repeat("a", &columns * 2)
echo printf(printf('%%.%ds', v:maxechospace-3).'...', toolong)
```

However, it is not really clear to me why messages are not allowed to run into the space reserved for `&showcmd` in the first place (10 cells after all).

**Comment by brammool** [comment]
> Maybe also a new ":echo_trunc" command could be added, which would
> automatically truncate it to the max width ("sc_col")?  (but then
> there could/should be options to either truncate it in the middle or
> the end also somehow probably)
> 
> I've found that there is `msg_strtrunc` already
> (https://github.com/vim/vim/blob/f1e0544d413b8b2ea129db0655b4e123d54177a6/src/message.c#L195-L236),
> which also gets used via `set shortmess+=T`, but not in ex mode.
> This could be used for a helper function to truncation then maybe.
> 
> The following adds a `v:maxechospace` var, based on `sc_col`:  (patch based on Neovim's source):
> ```diff
>  src/nvim/eval.c   | 2 ++
>  src/nvim/eval.h   | 1 +
>  src/nvim/option.c | 1 +
>  3 files changed, 4 insertions(+)
> 
> diff --git i/src/nvim/eval.c w/src/nvim/eval.c
> index 8f6d6cd55..8d65e6923 100644
> --- i/src/nvim/eval.c
> +++ w/src/nvim/eval.c
> @@ -395,6 +395,7 @@ static struct vimvar {
>    VV(VV_OP,             "operator",         VAR_STRING, VV_RO),
>    VV(VV_SEARCHFORWARD,  "searchforward",    VAR_NUMBER, 0),
>    VV(VV_HLSEARCH,       "hlsearch",         VAR_NUMBER, 0),
> +  VV(VV_MAXECHOSPACE,   "maxechospace",     VAR_NUMBER, 0),
>    VV(VV_OLDFILES,       "oldfiles",         VAR_LIST, 0),
>    VV(VV_WINDOWID,       "windowid",         VAR_NUMBER, VV_RO_SBX),
>    VV(VV_PROGPATH,       "progpath",         VAR_STRING, VV_RO),
> @@ -621,6 +622,7 @@ void eval_init(void)
>    set_vim_var_nr(VV_STDERR,   CHAN_STDERR);
>    set_vim_var_nr(VV_SEARCHFORWARD, 1L);
>    set_vim_var_nr(VV_HLSEARCH, 1L);
> +  set_vim_var_nr(VV_MAXECHOSPACE, sc_col);

Here the value "sc_col" is used..

>    set_vim_var_nr(VV_COUNT1, 1);
>    set_vim_var_nr(VV_TYPE_NUMBER, VAR_TYPE_NUMBER);
>    set_vim_var_nr(VV_TYPE_STRING, VAR_TYPE_STRING);
> diff --git i/src/nvim/eval.h w/src/nvim/eval.h
> index abe032a96..68a10aa3e 100644
> --- i/src/nvim/eval.h
> +++ w/src/nvim/eval.h
> @@ -91,6 +91,7 @@ typedef enum {
>      VV_OP,
>      VV_SEARCHFORWARD,
>      VV_HLSEARCH,
> +    VV_MAXECHOSPACE,
>      VV_OLDFILES,
>      VV_WINDOWID,
>      VV_PROGPATH,
> diff --git i/src/nvim/option.c w/src/nvim/option.c
> index 699f17acc..deb140e1c 100644
> --- i/src/nvim/option.c
> +++ w/src/nvim/option.c
> @@ -5456,6 +5456,7 @@ void comp_col(void)
>    if (ru_col <= 0) {
>      ru_col = 1;
>    }
> +  set_vim_var_nr(VV_MAXECHOSPACE, sc_col - 1);  // -1 for newline being added

But here it's one less?

>  }
>  
>  // Unset local option value, similar to ":set opt<".
> ```
> 
> This allows for:
> ```vim
> let toolong = repeat("a", &columns * 2)
> echo printf(printf('%%.%ds', v:maxechospace-3).'...', toolong)
> ```
> 
> However, it is not really clear to me why messages are not allowed to
> run into the space reserved for `&showcmd` in the first place (10
> cells after all).

Well, part of the message would soon be erased, possibly leading to a
confusing message.

-- 
From "know your smileys":
 :-*	A big kiss!

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by blueyed** [comment]
> But here it's one less?

Forgot that then apparently - I've added the `-1` since otherwise it would trigger wait-enter also due to the newline at the end (which might not be necessary really, but is due to handling corner cases of terminals not handling the bottom right column IIRC from checking the code).

IIRC the first one is 0 likely anyway (during init).
It should not become -1 then at least.

> Well, part of the message would soon be erased, possibly leading to a
confusing message.

I see.  Just feels like a bit of wasted space (10 cells out of ~80).  Thanks for clarifying.

Do you think this change makes sense then?
In https://github.com/neovim/neovim/pull/10828#issuecomment-523892818 v:msgwidth or v:echowidth was suggested for a name.

**Comment by chrisbra** [comment]
> For plugins it is often useful to avoid that, and truncate messages accordingly.

May I ask, what the actual use case is? If you need to show a message, are you really going to truncate it and risk that the user will possibly no longer understand your message? Isn't it more reasonable to always show a clear and precise message (as short as possible) so that the user can understand it and act accordingly?

**Comment by blueyed** [comment]
> May I ask, what the actual use case is?

The case at hand was vim-grepper, which echos the program being run (e.g. `rg` with all the args).
This should not cause a wait-enter prompt before showing results.
It is questionable if this could be removed (by default, or via a setting).

Another usecase is Neomake, which displays the error under the cursor there (among other other methods).

There are many plugins using a workaround of hiding rulter etc, and using helper methods for this (e.g. https://github.com/blueyed/dotfiles/blob/3d3a476e85d5404cd8e9f49c9ff8dc0a2aae660a/vim/bundle/eclim/eclim/autoload/eclim/util.vim#L1751-L1774, https://github.com/tpope/vim-dispatch/pull/167).

**Comment by chrisbra** [comment]
> The case at hand was vim-grepper, which echos the program being run (e.g. rg with all the args).
> This should not cause a wait-enter prompt before showing results.

So instead you would prefer if the args get truncated (so the user possibly does not know that he is missing additional arguments)?

> Another usecase is Neomake, which displays the error under the cursor there (among other other methods).

Same question here: The user needs to understand the error/warning message. If you truncate it, because your Vim window is only 20 chars wide, how helpful is this actually?

**Comment by blueyed** [comment]
> So instead you would prefer if the args get truncated (so the user possibly does not know that he is missing additional arguments)?

Yes, since it is more informational - that's also why I think it could be disabled by default.
Still useful to see which tool was used etc (the beginning).

As for Neomake: there it is used on CursorMoved, and a wait-enter would be annoying there then.
(I know that newer methods like popup windows exists by now).

Having the available space in a variable just helps plugins that would do it anyway, instead of messing with `set ruler`, `redraw` etc.
I've figured to ask for this information via this issue, instead of using the workaround method for vim-grepper.

**Comment by blueyed** [comment]
Vim also truncates some messages by default, e.g. filenames with vimgrep IIRC (or somewhere else).

**Comment by brammool** [comment]
Daniel Hahler wrote:

> > But here it's one less?
> 
> Forgot that then apparently - I've added the `-1` since otherwise it
> would trigger wait-enter also due to the newline at the end (which
> might not be necessary really, but is due to handling corner cases of
> terminals not handling the bottom right column IIRC from checking the
> code).
> 
> IIRC the first one is 0 likely anyway (during init).
> It should not become -1 then at least.

I see that I can output 51 characters without triggering the prompt,
whilc sc_col is 52.  So it should be "sc_col - 1".

> > Well, part of the message would soon be erased, possibly leading to a
> confusing message.
> 
> I see.  Just feels like a bit of wasted space (10 cells out of ~80).
> Thanks for clarifying.

You can use more if you like, but it will trigger the prompt.

> Do you think this change makes sense then?
> In https://github.com/neovim/neovim/pull/10828#issuecomment-523892818 v:msgwidth or v:echowidth was suggested for a name.

Yeah, what to call it?  "maxechospace" sounds weird to me: "max" and
"space" have overlapping meaning.  I think "echospace" makes more sense:
The space you have for an :echo command.

I'll add a test and docs.

-- 
Contrary to popular belief, Unix is user friendly.
It just happens to be selective about who it makes friends with.
                                               -- Dave Parnas

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
