### ISSUE TITLE
Text added to a buffer with job_start() isn't always displayed

### ISSUE THREAD

**Issue by bfrg** [vim/vim#4745]
**Describe the bug**
Text added to a displayed buffer by `job_start({cmd}, {'out_io': 'buffer'})` isn't always displayed. 
This happens only when previously the window was scrolled up such that the first line of the buffer isn't visible anymore, and `deletebufline(buf, 1, '$')` was called prior to the job output.
Related: #4718 (and closed in 2984666)

**To Reproduce**
1. Go into Vim's `src/` directory and run `vim --clean`.
2. Open a new window with buffer `foo`, and run a job that will scroll the window displaying the buffer `foo`:
```vim
new foo
call job_start([&shell, &shellcmdflag, 'head -200 evalfunc.c'], {
    \ 'out_io': 'buffer',
    \ 'out_name': 'foo'
    \ })
```
3. Delete all lines in the buffer `foo`:
```vim
call deletebufline('foo', 1, '$')
```
* Notice, there's no topline in buffer `foo`.
4. Run a job that outputs one line:
```vim
call job_start([&shell, &shellcmdflag, 'head -1 evalfunc.c'], {
    \ 'out_io': 'buffer',
    \ 'out_name': 'foo',
    \ })
```
5. Result: the first line of buffer `foo` remains invisible, unless the focus is moved to the window displaying `foo`. When the job outputs 2 lines, the second line will be visible immediately.

**Expected behavior**
The first line of the buffer should be immediately visible.

**Environment**
- Vim version `8.1.1773`
- OS: Gentoo Linux
- Terminal: `xfce4-terminal`

**Comment by brammool** [comment]
> **Describe the bug**
> Text added to a displayed buffer by `job_start({cmd}, {'out_io': 'buffer'})` isn't always displayed. 
> This happens only when previously the window was scrolled up such that the first line of the buffer isn't visible anymore, and `deletebufline(buf, 1, '$')` was called prior to the job output.
> Related: #4718 (and closed in 2984666)
> 
> **To Reproduce**
> 1. Go into Vim's `src/` directory and run `vim --clean`.
> 2. Open a new window with buffer `foo`, and run a job that will scroll the window displaying the buffer `foo`:
> ```vim
> new foo
> call job_start([&shell, &shellcmdflag, 'head -200 evalfunc.c'], {
>     \ 'out_io': 'buffer',
>     \ 'out_name': 'foo'
>     \ })
> ```
> 3. Delete all lines in the buffer `foo`:
> ```vim
> call deletebufline('foo', 1, '$')
> ```
> * Notice, there's no topline in buffer `foo`.
> 4. Run a job that outputs one line:
> ```vim
> call job_start([&shell, &shellcmdflag, 'head -1 evalfunc.c'], {
>     \ 'out_io': 'buffer',
>     \ 'out_name': 'foo',
>     \ })
> ```
> 5. Result: the first line of buffer `foo` remains invisible, unless the focus is moved to the window displaying `foo`. When the job outputs 2 lines, the second line will be visible immediately.
> 
> **Expected behavior**
> The first line of the buffer should be immediately visible.
> 
> **Environment**
> - Vim version `8.1.1773`
> - OS: Gentoo Linux
> - Terminal: `xfce4-terminal`

I can reproduce it with:


new foo
call setline(1, range(1, 200))
$
redraw
wincmd w
call deletebufline('foo', 1, '$')
call job_start([&shell, &shellcmdflag, 'echo "a new line"'], {
    \ 'out_io': 'buffer',
    \ 'out_name': 'foo',
    \ })


-- 
You can test a person's importance in the organization by asking how much RAM
his computer has.  Anybody who knows the answer to that question is not a
decision-maker.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
