### ISSUE TITLE
Behavior described in #4419 regressed

### ISSUE THREAD

**Issue by brian-armstrong** [vim/vim#4748]
Hello,

I previously reported some faulty behavior with the E211 banner in #4419. I was happy to see the issue was fixed, however it seems a subsequent update regressed and the banner is now faulty again. It looks like the commit in question is https://github.com/vim/vim/commit/8239c62067c8d40720560496b25a82662126f2a2

Is there anything I can do to help arrive at the correct behavior for this? Is it possible to revert this commit?

Thanks!

**Comment by brammool** [comment]
Can you please add the reproduction steps, there are too many links back to old issues now.

**Comment by brian-armstrong** [comment]
Sure! It's relatively simple.

* Touch and open two files, foo and bar in two tabs
* `rm foo`
* Focus vim, status appears about foo being deleted
* Clear status
* Unfocus and focus vim
* Deleted status appears again

Expected behavior:
Deleted status only appears first time
