### ISSUE TITLE
Windows system() error: can't open temp file.

### ISSUE THREAD

**Issue by zcodes** [vim/vim#4754]
**Describe the bug**
on windows, the `system()` command cause error `E:484 can't open file c:\Users\xx\AppData\Local\Temp\xxx.tmp` when `noshelltemp`.

**To Reproduce**
1. :set noshelltemp
2. :set shellslash
3. :echo system(shellescape('cd /d d:/cpp/hello-cmale && git config --get remote.origin.url'))

**Expected behavior**
echo the remote url

**Screenshots**
![20190731125659](https://user-images.githubusercontent.com/1469192/62186185-dcf52e00-b397-11e9-8909-2f9815ba17e9.png)

**Environment (please complete the following information):**
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 30 2019 15:01:18)
MS-Windows 64-bit GUI version
Included patches: 1-1777
Compiled by zcodes@BLACKBOX2
Huge version with GUI.  Features included (+) or not (-):
+acl                +eval               +multi_lang         -tcl
+arabic             +ex_extra           -mzscheme           -termguicolors
+autocmd            +extra_search       -netbeans_intg      +terminal
+autochdir          -farsi              +num64              -termresponse
+autoservername     +file_in_path       -ole                +textobjects
+balloon_eval       +find_in_path       +packages           +textprop
-balloon_eval_term  +float              +path_extra         -tgetent
+browse             +folding            -perl               +timers
++builtin_terms     -footer             +persistent_undo    +title
+byte_offset        +gettext/dyn        -postscript         +toolbar
+channel            -hangul_input       +printer            +user_commands
+cindent            +iconv/dyn          +profile            +vartabs
+clientserver       +insert_expand      +python/dyn         +vertsplit
+clipboard          +job                +python3/dyn        +virtualedit
+cmdline_compl      +jumplist           +quickfix           +visual
+cmdline_hist       +keymap             +reltime            +visualextra
+cmdline_info       +lambda             +rightleft          +viminfo
+comments           +langmap            +ruby/dyn           +vreplace
+conceal            +libcall            +scrollbind         -vtp
+cryptv             +linebreak          +signs              +wildignore
+cscope             +lispindent         +smartindent        +wildmenu
+cursorbind         +listcmds           +sound              +windows
+cursorshape        +localmap           +spell              +writebackup
+dialog_con_gui     -lua                +startuptime        -xfontset
+diff               +menu               +statusline         -xim
+digraphs           +mksession          -sun_workshop       +xpm_w32
+directx            +modify_fname       +syntax             -xterm_save
-dnd                +mouse              +tag_binary         
-ebcdic             +mouseshape         -tag_old_static     
+emacs_tags         +multi_byte_ime/dyn -tag_any_white      
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
  system gvimrc file: "$VIM\gvimrc"
    user gvimrc file: "$HOME\_gvimrc"
2nd user gvimrc file: "$HOME\vimfiles\gvimrc"
3rd user gvimrc file: "$VIM\_gvimrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
    system menu file: "$VIMRUNTIME\menu.vim"
Compilation: gcc -I. -Iproto -DWIN32 -DWINVER=0X0600  -D_WIN32_WINNT=0X0
600  -DHAVE_PATHDEF -DFEAT_HUGE -DHAVE_STDINT_H -DMS_WIN64 
-DHAVE_GETTEXT -DHAVE_LOCALE_H -DDYNAMIC_GETTEXT -DFEAT_CSCOPE 
-DFEAT_JOB_CHANNEL -DFEAT_TERMINAL -DFEAT_SOUND -DFEAT_DIRECTX 
-DDYNAMIC_DIRECTX -DFEAT_DIRECTX_COLOR_EMOJI -DFEAT_GUI_MSWIN 
-DFEAT_CLIPBOARD -DFEAT_MBYTE_IME -DDYNAMIC_IME -DDYNAMIC_ICONV 
-pipe -march=x86-64 -Wall -DFEAT_RUBY -I c:/Tools/Ruby26/include/ruby-2.6.0 -I 
c:/Tools/Ruby26/include/ruby-2.6.0/x64-mingw32 -DDYNAMIC_RUBY 
-DDYNAMIC_RUBY_DLL="x64-msvcrt-ruby260.dll" -DDYNAMIC_RUBY_VER=26 
-DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL="python27.dll
" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL="python
37.dll" -DFEAT_XPM_W32 -I xpm/x64/include -I xpm/x64/../include -O3 
-fomit-frame-pointer -freg-struct-return
Linking: g++ -I. -Iproto -DWIN32 -DWINVER=0X0600  -D_WIN32_WINNT=0X0600  
-DHAVE_PATHDEF -DFEAT_HUGE -DHAVE_STDINT_H -DMS_WIN64 
-DHAVE_GETTEXT -DHAVE_LOCALE_H -DDYNAMIC_GETTEXT -DFEAT_CSCOPE 
-DFEAT_JOB_CHANNEL -DFEAT_TERMINAL -DFEAT_SOUND -DFEAT_DIRECTX 
-DDYNAMIC_DIRECTX -DFEAT_DIRECTX_COLOR_EMOJI -DFEAT_GUI_MSWIN 
-DFEAT_CLIPBOARD -DFEAT_MBYTE_IME -DDYNAMIC_IME -DDYNAMIC_ICONV 
-pipe -march=x86-64 -Wall -DFEAT_RUBY -I c:/Tools/Ruby26/include/ruby-2.6.0 -I 
c:/Tools/Ruby26/include/ruby-2.6.0/x64-mingw32 -DDYNAMIC_RUBY 
-DDYNAMIC_RUBY_DLL="x64-msvcrt-ruby260.dll" -DDYNAMIC_RUBY_VER=26 
-DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL="python27.dll
" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL="python
37.dll" -DFEAT_XPM_W32 -I xpm/x64/include -I xpm/x64/../include -O3 
-fomit-frame-pointer -freg-struct-return -s -municode -mwindows 
-Wl,-Map=gvim.exe.map -o gvim.exe -lkernel32 -luser32 -lgdi32 -ladvapi32 
-lcomdlg32 -lcomctl32 -lnetapi32 -lversion -lwsock32 -ld2d1 -ldwrite 
-Lxpm/x64/lib -lXpm -lwinmm -Wl,-Bstatic -lstdc++ -lgcc -Wl,-Bdynamic -lgcc_eh 
-Wl,-Bstatic -lstdc++ -lwinpthread -Wl,-Bdynamic -lole32 -luuid    

**Additional context**
the cmd passed to system() will wrapped with `C:\Windows\System32\cmd.exe /c` with another `C:\Windows\System32\cmd.exe /c`, then the cmd will be `c:\Windows\System32\cmd.exe /c C:\Windows\System32\cmd.exe /c (cd /d d:\cpp\hello-cmake && git config --get remote.origin.url ><tmp_file> 2>&1)`. 

as the screen demoed, `cmd /c cmd /c` not worked !
![20190731135317](https://user-images.githubusercontent.com/1469192/62187087-d9af7180-b39a-11e9-8cbe-ea1007d0336e.png)

I change the source code and remove one `c:\Windows\System32\cmd.exe /c` and then it works.

the patch is here:
```
diff --git a/src/os_win32.c b/src/os_win32.c
index f6eb67170..ae3142192 100644
--- a/src/os_win32.c
+++ b/src/os_win32.c
@@ -4840,7 +4840,7 @@ mch_call_shell(
 #ifdef FEAT_GUI_MSWIN
                ((gui.in_use || gui.starting) ?
                    (!s_dont_use_vimrun && p_stmp ?
-                       STRLEN(vimrun_path) : STRLEN(p_sh) + STRLEN(p_shcf))
+                       STRLEN(vimrun_path) : 0)
                    : 0) +
 #endif
                STRLEN(p_sh) + STRLEN(p_shcf) + STRLEN(cmd) + 10;
@@ -4886,8 +4886,8 @@ mch_call_shell(
 # endif
                        STRCMP(p_shcf, "/c") == 0)
                    // workaround for the case that "vimrun" does not exist
-                   vim_snprintf((char *)newcmd, cmdlen, "%s %s %s %s %s",
-                                          p_sh, p_shcf, p_sh, p_shcf, cmd);
+                   vim_snprintf((char *)newcmd, cmdlen, "%s %s %s",
+                                          p_sh, p_shcf, cmd);
                else
 #endif
                    vim_snprintf((char *)newcmd, cmdlen, "%s %s %s",
```

**Comment by k-takata** [comment]
`c:\Windows\System32\cmd.exe /c` is used twice for a workaround for the case that "vimrun" does not exist as the comment says. So removing one of them breaks it.

How about this patch?

```diff
diff --git a/src/os_win32.c b/src/os_win32.c
--- a/src/os_win32.c
+++ b/src/os_win32.c
@@ -4856,7 +4856,7 @@ mch_call_shell(
 # ifdef VIMDLL
 			(gui.in_use || gui.starting) &&
 # endif
-			STRCMP(p_shcf, "/c") == 0)
+			STRCMP(p_shcf, "/c") == 0 && s_dont_use_vimrun)
 		    // workaround for the case that "vimrun" does not exist
 		    vim_snprintf((char *)newcmd, cmdlen, "%s %s %s %s %s",
 					   p_sh, p_shcf, p_sh, p_shcf, cmd);
```

**Comment by zcodes** [comment]
@k-takata i test the patch, it works, and it should be a better solution.
