### ISSUE TITLE
balloonexpr message do not support \n

### ISSUE THREAD

**Issue by haolongzhangm** [vim/vim#4756]
tag: v8.1.1777
--------------code---------------------
function! BalloonDeclaration()
    let result = "hhhh\nkkkk\nlllllllll" 
    return result 
endfunction 
 

    set ballooneval
    set balloonexpr=BalloonDeclaration()

----------------end code--------------

issue:
balloon will show msg: 
hhhh^@kkkk^@lllllllll

expect：
balloon will show msg:
hhhh
kkkk
lllllllll

sames ballon do not support \n

**Comment by k-takata** [comment]
What OS?
Does `echo has("balloon_multiline")` show `1`?

**Comment by haolongzhangm** [comment]
> What OS?----- ubuntu 16.04
> Does `echo has("balloon_multiline")` show `1`? ----yes


more info:

VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 30 2019 23:08:32)
包含补丁: 1-1777
编译者 zhl@work
巨型版本 带 GTK2 图形界面。  可使用(+)与不可使用(-)的功能:
+acl               -farsi             -mouse_sysmouse    -tag_any_white
+arabic            +file_in_path      +mouse_urxvt       +tcl
+autocmd           +find_in_path      +mouse_xterm       +termguicolors
+autochdir         +float             +multi_byte        +terminal
-autoservername    +folding           +multi_lang        +terminfo
+balloon_eval      -footer            -mzscheme          +termresponse
+balloon_eval_term +fork()            +netbeans_intg     +textobjects
+browse            +gettext           +num64             +textprop
++builtin_terms    -hangul_input      +packages          +timers
+byte_offset       +iconv             +path_extra        +title
+channel           +insert_expand     +perl              +toolbar
+cindent           +job               +persistent_undo   +user_commands
+clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           -python            +visual
+cmdline_info      +libcall           +python3           +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
+cscope            +localmap          +ruby              +wildmenu
+cursorbind        -lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con_gui    +mksession         +smartindent       +X11
+diff              +modify_fname      -sound             -xfontset
+digraphs          +mouse             +spell             +xim
+dnd               +mouseshape        +startuptime       -xpm
-ebcdic            +mouse_dec         +statusline        +xsmp_interact
+emacs_tags        -mouse_gpm         -sun_workshop      +xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          +mouse_netterm     +tag_binary        
+extra_search      +mouse_sgr         -tag_old_static    
     系统 vimrc 文件: "$VIM/vimrc"
     用户 vimrc 文件: "$HOME/.vimrc"
 第二用户 vimrc 文件: "~/.vim/vimrc"
      用户 exrc 文件: "$HOME/.exrc"
    系统 gvimrc 文件: "$VIM/gvimrc"
    用户 gvimrc 文件: "$HOME/.gvimrc"
第二用户 gvimrc 文件: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
        系统菜单文件: "$VIMRUNTIME/menu.vim"
         $VIM 预设值: "/usr/local/share/vim"
编译方式: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2   -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
链接方式: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl   -ldl   -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.22/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-2.3 -lpthread -lgmp -ldl -lcrypt -lm

**Comment by brammool** [comment]
Consider using a popup window, see the example at :help popup_beval_example

**Comment by haolongzhangm** [comment]
> Consider using a popup window, see the example at :help popup_beval_example

try use popup_beval, issue also happened

**Comment by haolongzhangm** [comment]
@brammool @k-takata any idea about this issue

**Comment by haolongzhangm** [comment]
@brammool @k-takata 
use popup_beval with message of list will be ok
use popup_beval with message of string will be not ok

**Comment by haolongzhangm** [comment]
use popup_beval will find anthor issue:
when use this :
let s:winid = popup_beval(result, #{mousemoved: 'word'}) 
when popup disappeared， will auto call BufUnload , why? how to disable it

**Comment by brammool** [comment]
> use popup_beval will find anthor issue:
> when use this :
> let s:winid = popup_beval(result, #{mousemoved: 'word'}) 
> when popup disappeared， will auto call BufUnload , why? how to disable it

A popup window uses a buffer, which is unloaded after use.
What's the problem with that?  Buffers are unloaded at any time.


-- 
Everybody wants to go to heaven, but nobody wants to die.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by haolongzhangm** [comment]
> use popup_beval will find anthor issue: when use this : let s:winid = popup_beval(result, #{mousemoved: 'word'}) when popup disappeared， will auto call BufUnload , why? how to disable it
> A popup window uses a buffer, which is unloaded after use. What's the problem with that? Buffers are unloaded at any time.
> […](#)
> -- Everybody wants to go to heaven, but nobody wants to die. /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net \\\ /// sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\ \\\ an exciting new programming language -- http://www.Zimbu.org /// \\\ help me help AIDS victims -- http://ICCF-Holland.org ///

OK. so close this issue.

to sum up， 
balloonexpr message do not support \n
temp solution: use message with list and popup_* api, do not use message with \n
