### ISSUE TITLE
filereadable() returns false for paths starting with ~

### ISSUE THREAD

**Issue by GlancingMind** [vim/vim#4758]
**Describe the bug**
filereadable() won't return _true_ for filepaths relative to users home directory e.g.  `~/test.vim`.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Create a new vimscript with following content:
```
echomsg filereadable(expand('%:p'))
echomsg filereadable(expand('%:~'))
```
2. Save and source the vimscript with `:w test.vim | source %`
3. As indicated by the output is the return value of filereadable _true_ for the first and _false_ for the second given path. But the only difference between both paths being that the first is an absolute path to the sourced script while the second is relative to the users home directory.

**Expected behavior**
filereadable() should return _true_ for path relative to the users home directory.

**Environment:**
 - Vim version 8.1.1776
 - OS: Archlinux 5.2.5-arch1-1-ARCH x86_64
 - Terminal: suckless st

**Comment by chrisbra** [comment]
Please fill out the issue template.

**Comment by brammool** [comment]
This is intentional.  If you want to expand wildcards use filereadable(expand('~/.vimrc'))
This is to avoid needing to escape special characters.

**Comment by chrisbra** [comment]
Ah, you did already, I just saw the template notification and did not see you modified the issue afterwards (for which github does not sende notifications)
