### ISSUE TITLE
function to get list of all misspelled words in buffer

### ISSUE THREAD

**Issue by marcotrosi** [vim/vim#4765]
**Is your feature request related something that is currently hard to do? Please describe.**
Vim can highlight all words that are misspelled in the current buffer. It would be nice to get access to all of them at ones to allow simpler writing of better spelling plugins. For example to list all misspelled words in split view or popup.

**Describe the solution you'd like**
 The information seems to be inside Vim, otherwise the words couldn't be highlighted. And it would be great to have a function e.g. spellbadlist(), that returns a list of all misspelled words.
Every entry in that list would be something like  "word", "line", "col" (maybe col_start, col_end OR cal_start, word_len)

**Describe alternatives you've considered**
External tools could be an alternative but if the information is already inside Vim why not using it? 

Thanks for considering this idea

--marco

**Comment by inkarkat** [comment]
Right. Currently one needs to repeatedly call `spellbadword()` to iterate over all misspelled words in the buffer and extract them. My [SpellCheck plugin](http://www.vim.org/scripts/script.php?script_id=3844) uses this approach to obtain a list of all misspelled words and show them in the quickfix list.

A dedicated function, as suggested, certainly would make the implementation more straightforward. On the other hand, the iteration itself isn't too bad, the use case not very common, and there are still worse areas (where command output has to be captured with `execute()` and parsed) that should be considered first.

**Comment by brammool** [comment]
Using spellbadword() is not really complicated.  I don't see a good reason to add a function to return a list of spell mistakes.

**Comment by marcotrosi** [comment]
> Right. Currently one needs to repeatedly call `spellbadword()` to iterate over all misspelled words in the buffer and extract them. My [SpellCheck plugin](http://www.vim.org/scripts/script.php?script_id=3844) uses this approach to obtain a list of all misspelled words and show them in the quickfix list.
> 
> A dedicated function, as suggested, certainly would make the implementation more straightforward. On the other hand, the iteration itself isn't too bad, the use case not very common, and there are still worse areas (where command output has to be captured with `execute()` and parsed) that should be considered first.

Hi @inkarkat ,
because Bram closed this issue, I have written a function (first draft) that uses spellbadword() to collect the misspelled words.

```
function! GetMisspelledWords()
   let l:LineCnt  = 0
   let l:BufLines = getbufline('%', 1, '$')
   let l:BadWords = []
   for line in l:BufLines
      let l:Start=0
      let l:LineCnt = l:LineCnt + 1
      while v:true
         let l:Match = matchstrpos(line,'\a\+',l:Start)
         if l:Match[0] == ''
            break
         else
            let l:Word  = l:Match[0]
            let l:Start = l:Match[1]
            let l:End   = l:Match[2]
            let l:Check = spellbadword(l:Word)
            if l:Check[0] != ''
               call add(l:Check, l:LineCnt)
               " call add(l:Check, l:Start)
               " call add(l:Check, l:End-1)
               call add(l:Check, l:Start+1)
               call add(l:Check, l:End)
               call add(l:BadWords, l:Check)
            end
            let l:Start = l:End
         endif
      endwhile
   endfor
   return l:BadWords
endfunction
```

My problem is that it finds way more misspelled words than Vim does. Vim seems to know about language keywords etc.
Do you have a hint on how to solve this issue? Any function that I can use?
Or is Vim maybe excluding code (except for strings) and scans only comments?
Or do I only have to use a different regex to find words and not code fragments?

Thanks

marco

**Comment by brammool** [comment]
> > Right. Currently one needs to repeatedly call `spellbadword()` to iterate over all misspelled words in the buffer and extract them. My [SpellCheck plugin](http://www.vim.org/scripts/script.php?script_id=3844) uses this approach to obtain a list of all misspelled words and show them in the quickfix list.
> > 
> > A dedicated function, as suggested, certainly would make the implementation more straightforward. On the other hand, the iteration itself isn't too bad, the use case not very common, and there are still worse areas (where command output has to be captured with `execute()` and parsed) that should be considered first.
> 
> Hi @inkarkat ,
> because Bram closed this issue, I have written a function (first draft) that uses spellbadword() to collect the misspelled words.
> 
> ```
> function! GetMisspelledWords()
>    let l:LineCnt  = 0
>    let l:BufLines = getbufline('%', 1, '$')
>    let l:BadWords = []
>    for line in l:BufLines
>       let l:Start=0
>       let l:LineCnt = l:LineCnt + 1
>       while v:true
>          let l:Match = matchstrpos(line,'\a\+',l:Start)
>          if l:Match[0] == ''
>             break
>          else
>             let l:Word  = l:Match[0]
>             let l:Start = l:Match[1]
>             let l:End   = l:Match[2]
>             let l:Check = spellbadword(l:Word)
>             if l:Check[0] != ''
>                call add(l:Check, l:LineCnt)
>                " call add(l:Check, l:Start)
>                " call add(l:Check, l:End-1)
>                call add(l:Check, l:Start+1)
>                call add(l:Check, l:End)
>                call add(l:BadWords, l:Check)
>             end
>             let l:Start = l:End
>          endif
>       endwhile
>    endfor
>    return l:BadWords
> endfunction
> ```
> 
> My problem is that it finds way more misspelled words than Vim does. Vim seems to know about language keywords etc.
> Do you have a hint on how to solve this issue? Any function that I can use?
> Or is Vim maybe excluding code (except for strings) and scans only comments?

You should use spellbadword() without an argument, then Vim does the
advancing for you and should also take care of syntax annotations for
spelling.

-- 
hundred-and-one symptoms of being an internet addict:
28. You have comandeered your teenager's phone line for the net and even his
    friends know not to call on his line anymore.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by marcotrosi** [comment]
> You should use spellbadword() without an argument, then Vim does the advancing for you and should also take care of syntax annotations for spelling.

Thank you @brammool :-)
This means if I use spellbadword without an argument then I have to place the cursor on the words before using spellbadword(), right? how about the performance for doing it this way? And why does spellbadword() behave differently if invoked without parameter? which logic does it follow?

Thank you ;-)

**Comment by marcotrosi** [comment]
> > You should use spellbadword() without an argument, then Vim does the advancing for you and should also take care of syntax annotations for spelling.
> 
> Thank you @brammool :-)
> This means if I use spellbadword without an argument then I have to place the cursor on the words before using spellbadword(), right? how about the performance for doing it this way? And why does spellbadword() behave differently if invoked without parameter? which logic does it follow?
> 
> Thank you ;-)

Hello @chrisbra, do you know why spellbadword() behaves differently with and without parameter? How about the performance when positioning the cursor on the words in order to call spellbadword() without parameter?

Thank you

**Comment by chrisbra** [comment]
not sure why you are asking me directly, because I cannot say anything about `spellbadword()`.  You can measure the performance yourself using two different scripts and using `reltimestr()`
