### ISSUE TITLE
unnamedplus fails when using Mac Xquartz as X server.

### ISSUE THREAD

**Issue by mdemoney** [vim/vim#4766]
Setup:
	vim/gvim (Huge, gtk2, 8.1.1777) running on CentOS linux host.
	(g)vim started -N -u NONE -U NONE
	(g)vim then has clipboard=unnamedplus set.
	gvim displaying on Mac (10.14.6) via Xquartz

	Xquartz installed on mac via macports ("port install xorg-server")
	version XQuartz 1.20.5, xorg-server 1.20.5.
	Xquartz has followiong pasteboard preferences set:
		Enable syncing
		Enable Update Pasteboard when CLIPBOARD changes
		Enable Update CLIPBOARD when Pasteboard changes
		Other pasteboard options disabled (Update PRIMARY,
			Update Pasteboard immediately)

Test:
	copy/paste both within vim/gvim on Linux and
	from vim/gvim on Linux to Mac pasteboard/apps.

Result:
	Using gvim with Xquartz having "Update Pasteboard" option enabled,
	copy to + register (e.g. yy with clipboard=unamedplus) is unreliable.
	Subsequent paste in gvim gives error "E353: Nothing in register +".
	After copy, examination of + register (:reg +) shows it unset or
	with stale value.  Rarely, copy to + succeeds and then paste is
	successful both within gvim and on Mac.

	With gvim and Xquartz "Update pasteboard when CLIPBOARD changes"
	option disabled, copy to + register is reliable.

	With vim, copy to + register is reliable regardless of Xquartz
	"Update Pasteboard" setting and Mac pasteboard is updated correctly.

	gvim behavior seems to be specific to Xquartz.
	Using an Xserver on linux, copy with unnamedplus works fine,
	+ register is updated and clipboard may be pasted into another
	local X app.

Summary:
	This seems to be an interaction between gvim gtk2 and Xquartz.
	Enabling Xquartz X11 CLIPBOARD to Mac Pasteboard handling appears
	to cause + register to not get updated in gvim during gvim copy
	operation.

	Directly specifying + register ("+y) does not help.
	Specifying another register (other than + or *) works fine.

	While this gvim behavior seems to be specific to Xquartz, there seems
	to be some vim gtk2 involvement.  Use of unnamedplus works fine in vim
	with same Xquartz options and Xquartz reliably updates Mac pasteboard.

**Comment by mdemoney** [comment]
A couple of extra details regarding gvim failure scenario:

2yy does not show the expected status line "2 lines yanked".

The Mac pasteboard is updated, it's just the + register is not.

**Comment by mdemoney** [comment]
Ignore the "2yy  does no show.."  pilot error.

**Comment by mdemoney** [comment]
Another symptom: In gvim with Xquartz and "Update Pasteboard" enabled, doing dd (or any similar command that assigns to + register) will give the error:
E341:  Internal error: lalloc(0, )

As before, if Xquartz "Update Pasteboard" option is disabled, the error does not occur.

**Comment by chrisbra** [comment]
have you contacted the Xquartz developers?

**Comment by mdemoney** [comment]
I haven't yet contacted the XQuartz developers, but I will (as soon as I figure out how to contact them).

Vim (as opposed to gvim) seems to handles copy/paste with Xquartz just fine, so I was wonder if there was some hint to  the problem there.

**Comment by nuko8** [comment]
> Vim (as opposed to gvim) seems to handles copy/paste with Xquartz just fine, so I was wonder if there was some hint to the problem there.

While Vim uses the Xlib API directly to implement copy/paste, gVim relies on the API provided by the GUI toolkit it uses.  So, another hint might also lie in the difference, if any, between the implementation of Vim's copy/paste and that of the toolkit's.

**Comment by nuko8** [comment]
I found my previous comment was somehow misleading.  Let me correct that.  Vim rather uses the API of libXt instead of that of Xlib.  That said, as libXt is also known as X11 Toolkit **Intrinsics** Library, it's a straightforward application of the Xlib API.  That's what I actually wanted to mean with the previous comment.

**Comment by mdemoney** [comment]
Hi.  I now believe this issue can be attributed to an older version of libXt.

The system where gvim was exhibiting this problem was running Centos 6.  When I setup a similar experiment on a Centos 7 system, I could not reproduce the problem.

Thanks for your patience and suggestions.

Mike

**Comment by mdemoney** [comment]
This issue may be closed.
