### ISSUE TITLE
[RFC] I hope '->' operator can be applied to all built-in functions, funcref

### ISSUE THREAD

**Issue by tyru** [vim/vim#4768]
@brammool 
I really love the recently added `->` operator! ac92e25a33c37ec5becbfffeccda136c73b761ac

we can write like `list->map(...)->filter(...)->join(...)`
I'm very pleased to write method chaining in vim script! 😄

But it seems it is limited to these functions. why?

https://github.com/vim/vim/blob/ac92e25a33c37ec5becbfffeccda136c73b761ac/src/evalfunc.c#L997-L1020

I hope `lhs->rhs()` operator can be applied to when rhs is:

* Other all built-in functions
* Funcref (Lambda/Partial/User-defined function)

**Comment by tyru** [comment]
These are examples for above proposal.
How do you think?

## Other built-in functions

```vim
echo {'key': 42}->has_key('key')
```

## User-defined function

```vim
let s:Module = {}
function! s:Module.flatmap(list, func)
  ...
endfunction

function! s:fold(list, init, func)
  ...
endfunction

echo range(1,10)->s:Module.flatmap({n -> n % 2 == 0 ? ['even'] : []})
echo range(1,10)->s:fold(0, {acc,n -> acc + n})

function! GlobalFunc(list)
  ...
endfunction

function! Main()
  let LocalFunc = function('s:fold')
  echo range(1,10)->LocalFunc(0, {acc,n -> acc + n})
  echo range(1,10)->GlobalFunc()
endfunction
```

## Lambda

```vim
call obj->{o -> execute('echo o')}
```

Lambda is a special case.
because rhs is not function call (`func()`).
if only function call is allowed, it must be like this.

```vim
" obj is passed to the first argument of function call
call obj->{o -> execute('echo o')}()
```

`->` operator can define a flow of reading order.
One can read in very natural order (left to right).
but in above example, (1) "obj" (left) (2) "()" (right) (3) lambda (left)
so I think "()" is not necessary.

## Similar operator in other languages

Vim script `->` operator looks like method call.
However other languages seems to call this operator "pipeline operator".

* [ECMACcript pipeline operator](https://github.com/tc39/proposal-pipeline-operator)
* [Elixir pipeline operator](https://stackoverflow.com/a/41585450/6321251)

You may feel strange `->` accepts user defined function like this.
(rhs is not only alphabet)

```vim
echo range(1,10)->s:Module.flatmap({n -> n % 2 == 0 ? ['even'] : []})
echo range(1,10)->s:fold(0, {acc,n -> acc + n})
```

but if this is pipeline operator, I think this is not strange.

```vim
echo range(1,10) |> s:Module.flatmap({n -> n % 2 == 0 ? ['even'] : []})
echo range(1,10) |> s:fold(0, {acc,n -> acc + n})
```

**Comment by tyru** [comment]
> ```vim
> echo range(1,10) |> s:Module.flatmap({n -> n % 2 == 0 ? ['even'] : []})
> echo range(1,10) |> s:fold(0, {acc,n -> acc + n})
> ```

Sorry, @thinca told me that `|>` cannot be used in Vim script.
It breaks compatibility because `|` is used to separate each Ex command (`:h :bar`),
and `>` Ex command exists (`:h :>`).

I don't mean `->` operator should be changed.
I just say, hmm, different ways of thinking?

**Comment by tyru** [comment]
Added more examples to above comment:

```vim
function! GlobalFunc(list)
  ...
endfunction

function! Main()
  let LocalFunc = function('s:fold')
  echo range(1,10)->LocalFunc(0, {acc,n -> acc + n})
  echo range(1,10)->GlobalFunc()
endfunction
```

**Comment by tyru** [comment]
I have created patches, but I want to hear @brammool and other users' voices other than me :)

* Allow all built-in functions (`dict->has_key('key')`)
  * https://github.com/vim/vim/compare/master...tyru:chain-op-allow-builtin-func?expand=1
* Allow user-defined function (Both `GlobalFunc` and `s:func`)
  * https://github.com/vim/vim/compare/master...tyru:chain-op-allow-userfunc?expand=1
* Allow lambda (`echo obj->{o -> execute('echo o')}`)
  * https://github.com/vim/vim/compare/master...tyru:chain-op-allow-lambda?expand=1
  * derived from `tyru:chain-op-allow-userfunc` branch

**Comment by brammool** [comment]
Several other functions can be used as a method.  I just added a few more, and now notice that has_key() was missing.  For some the base is not the first argument, and also I want to test each one we add, thus we'll do a few at a time.

I'm not sure if we want to use this for simple values, such as number and Float.  E.g. it looks unnatural to do 1.234->asin()

I think Lambda makes most sense when defining it separately:
let percent = {x -> x * 100}
echo Fraction()->percent()

It doesn't look good in a -> chain, also because it has -> inside in another meaning.

**Comment by brammool** [comment]
For user defined functions, we have a few options:
- Just allow any user defined function to be used after -> and pass the base as the first argument.
- When defining a function specify on what types it can be used as a method.  This way you can define an Operate() function on a list and a separate Operate() function on a dict.
- When the base is a dictionary, use functions defined in that dictionary (a bit like a class).

The third one might not be needed, since we already have dictionary functions, and also supporting -> will lead to name conflicts.  The example at ":help Dictionary-function", defining a len() method already shows this.

The first two might be both done, I don't see a problem with that yet.

**Comment by tyru** [comment]
> * Just allow any user defined function to be used after -> and pass the base as the first argument.
> * When defining a function specify on what types it can be used as a method. This way you can define an Operate() function on a list and a separate Operate() function on a dict.

How about adding type to argument, and "method" attribute?

```vim
function! Percent(n: Number) method
  ...
endfunction
```

if type is not specified, any value is accepted.

**Comment by tyru** [comment]
> I'm not sure if we want to use this for simple values, such as number and Float. E.g. it looks unnatural to do 1.234->asin()

I think it is not unnatural for me.
because I'm used to the languages that everything are objects such Ruby, Scala.

> I think Lambda makes most sense when defining it separately:
> let percent = {x -> x * 100}
> echo Fraction()->percent()

Lambda is funcref, variable of funcref must start with uppercase.

```vim
let Percent = {x -> x * 100}
echo Fraction()->Percent()
```

And this is little off-topic,
currently if global function `Percent()` exists, `E705` error occurs.
so receiving funcref as variable `Percent` may be dangerous, not `l:Percent`.

```vim
function! Percent(x)
  return a:x * 100
endfunction

function! s:main()
  " E705: Variable name conflicts with existing function: Percent
  let Percent = {x -> x * 100}
  " This is OK
  let l:Percent = {x -> x * 100}
endfunction

call s:main()
```

**Comment by tyru** [comment]
In [8.1.1816](https://github.com/vim/vim/commit/fcfe1a9b8950b8b211ab3b24d84b17c6847ea43f), these cases seems to be supported. thanks!

```vim
echo {'foo': 42}->HasKey('foo')
echo {'foo': 42}->s:has_key('foo')
```

however, I want lambda style as well.
certainly your example works like this.
but the advantage of lambda is that it is not necessary to define a function to pass function to map(), filter(), and so on.

```vim
let l:Percent = {x -> x * 100}
echo (10.0 / 100.0)->l:Percent()
```

so I want

```vim
echo (10.0 / 100.0)->{x -> x * 100}
```

**Comment by nickspoons** [comment]
I also think that being able to use lambdas like this would be very very useful.

Not necessarily (for me) in actual scripts, where I would probably spread things out into several lines for readability. But when just testing things out or checking variable values etc., I find it much easier to write long one-liners in the command line than first defining a lambda, then using it in a new command, then needing to redefine the lambda and then using it again etc.

Once using methods, connecting them with lambdas feels very natural to me, and gives an awful lot of flexibility.

**Comment by k-takata** [comment]
> ```viml
> echo (10.0 / 100.0)->{x -> x * 100}
> ```

Shouldn't it be as follows?

```vim
echo (10.0 / 100.0)->{x -> x * 100}()
```

**Comment by tyru** [comment]
@k-takata 

https://github.com/vim/vim/issues/4768#issuecomment-517966291

> ```vim
> call obj->{o -> execute('echo o')}
> ```
> 
> Lambda is a special case.
> because rhs is not function call (`func()`).
> if only function call is allowed, it must be like this.
> 
> ```vim
> " obj is passed to the first argument of function call
> call obj->{o -> execute('echo o')}()
> ```
> 
> `->` operator can define a flow of reading order.
> One can read in very natural order (left to right).
> but in above example, (1) "obj" (left) (2) "()" (right) (3) lambda (left)
> so I think "()" is not necessary.

**Comment by aiya000** [comment]
This lambda support seems really good!
I want this!!
Because I often use `obj.let { x -> x }` in Kotlin.

(Personally I like `call obj->{x -> x}()` (Needing `()`), to avoid confusing :smiley:)

**Comment by brammool** [comment]
> This lambda support seems really good!
> I want this!!
> 
> (Personally I like `call obj->{x -> x}()` (Needing `()`) because I
> maybe confused :smiley:)

We need the () for consistency.

	let Lambda = {x -> x * 100}
	echo (10.0 / 100.0)->Lambda()

Does the same as:
	echo (10.0 / 100.0)->{x -> x * 100}()

It's more obvious if you have an argument:

	let Lambda = {x, y -> x * y}
	echo (10.0 / 100.0)->Lambda(100)

Does the same as:
	echo (10.0 / 100.0)->{x, y -> x * y}(100)

That last line is not something you would actually use though.

I'm still looking for a good example where the inline Lambda is useful.
Perhaps for modifying a value:

	echo GetResult()->{x -> floor(x + 0.5)}->Process()

Line continuation can help for long chains:

	echo GetResult()
		\ ->{x -> floor(x + 0.5)}
		\ ->Process()
		\ ->DoSomeMore()


-- 
"Space is big.  Really big.  You just won't believe how vastly hugely mind-
bogglingly big it is.  I mean, you may think it's a long way down the
road to the chemist, but that's just peanuts to space."
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by aiya000** [comment]
> I'm still looking for a good example where the inline Lambda is useful.

I have an example.

I'm always thinking how to write cool codes.
(code readabilities)

```vim
let x = foo
echo x
  \ ->very(
     \ very_complex,
     \ arguments
   \ )
  \ ->z(too_many_chars)
```
I think this is very cool.

I write below instead above if the inline lambda is nothing.
I think this is cool too.

```vim
let x = foo
let x = very(
    \ very_complex,
    \ arguments
    \ )
let x = z(too_many_chars)
echo x
```

But this is fail if I want to use `const x`.

And in my opinion, the first example is very very cooler than the below basic writing.

```vim
const x = foo
echo z(
    \ very(
        \ x,
        \ very_complex,
        \ arguments
        \ ),
    \ too_many_chars
    \ )
```

Thanks :sunglasses::+1:

**Comment by tyru** [comment]
> But this is fail if I want to use `const x`.

The combination with `:const` is certainly reasonable case to support lambda.
It encourages programming style without side-effect.
