### ISSUE TITLE
[Trivial][Doc] Grammar error in develop.txt

### ISSUE THREAD

**Issue by mcarden** [vim/vim#4774]
In runtime/doc/develop.txt, the phrase:
"which is unacceptable slow"
...should probably be:
"which is unacceptably slow"

Well, CONTRIBUTING.md does say "Feel free to report even the smallest problem, also typos in the documentation."    :)

**Comment by brammool** [comment]
Michael Carden wrote:

> In runtime/doc/develop.txt, the phrase:
> "which is unacceptable slow"
> ...should probably be:
> "which is unacceptably slow"
> 
> Well, CONTRIBUTING.md does say "Feel free to report even the smallest
> problem, also typos in the documentation."    :)

Sure, I'll include the fix.

-- 
How To Keep A Healthy Level Of Insanity:
12. Sing along at the opera.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
fixed by 088e8e3
