### ISSUE TITLE
Some changes for MSVC

### ISSUE THREAD

**Issue by cmdorexe** [vim/vim#478]
Some changes for msvc.bat
Alpha
http://pastebin.com/eLxWcBR4 // 1.12 no context.
http://pastebin.com/JBWwLS6Z // 1.14 no context.
http://pastebin.com/ssjP0521 // 1.17
http://pastebin.com/awEWKTg3 // 1.20
Beta
http://pastebin.com/x20TWjqe // 1.24
http://pastebin.com/wWDPZ7p4 // 1.25
http://pastebin.com/k9szCBGw // 1.29
http://pastebin.com/76kpSJ0e // 1.30
http://pastebin.com/01HfR0bR // 1.31
Release Candidate
http://pastebin.com/RQ9EvtZW // RC.1.32
Work perfect. If rebuild libXpm for vs12 and vs14.
Close Issue. I'm fork code.

**Comment by brammool** [comment]
> Some Changes for robots.
> http://pastebin.com/eLxWcBR4

I'm missing context.

## 

hundred-and-one symptoms of being an internet addict:
107. When using your phone you forget that you don't have to use your
     keyboard.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
I assume this is the same as https://github.com/vim/vim/pull/485, so I close this ticket. Please be sure to mention at that PR what problem you are trying to solve with that PR.
