### ISSUE TITLE
Multibyte characters in 'listchars' don't work correct if 'linebreak' is also enabled

### ISSUE THREAD

**Issue by arp242** [vim/vim#4812]
Since [patch 8.1.0759](https://github.com/vim/vim/commit/83a52171ba00b2b9fd2d1d22a07e38fc9fc69c1e) a third character for `tab:` is accepted in 'listchars', however this doesn't work if the second character is a multibyte character and the 'linebreak' setting is enabled:

    $ vim --clean
    :set linebreak list listchars=tab:!·x

That second character is a middle dot: U+00B7, or `0xc2 0xb7` in UTF-8 (it doesn't matter which multibyte character you use). This will display:

    !·······!·······Hello

It seems like the third character is ignored. The expected display – which works when 'linebreak' isn't set – would be:

    !······x!······xHello

Only seems to affect the second character; e.g. `:set listchars=tab:!x·` always works as expected.

Vim 8.1.1845, with default flags.

**Comment by chrisbra** [comment]
can you check the following patch please?

```patch
diff --git a/src/screen.c b/src/screen.c
index 72b346d96..2fac0b5cc 100644
--- a/src/screen.c
+++ b/src/screen.c
@@ -4939,14 +4939,19 @@ win_line(
                        p_extra_free = p;
                        for (i = 0; i < tab_len; i++)
                        {
+                           int lcs = lcs_tab2;
                            if (*p == NUL)
                            {
                                tab_len = i;
                                break;
                            }
-                           mb_char2bytes(lcs_tab2, p);
-                           p += mb_char2len(lcs_tab2);
-                           n_extra += mb_char2len(lcs_tab2)
+
+                           // need one final space for lcs_tab3
+                           if (lcs_tab3 && i == tab_len - 1)
+                               lcs = lcs_tab3;
+                           mb_char2bytes(lcs, p);
+                           p += mb_char2len(lcs);
+                           n_extra += mb_char2len(lcs)
                                                 - (saved_nextra > 0 ? 1 : 0);
                        }
                        p_extra = p_extra_free;
```

Happy to add a test, if this works. Seems to work for me, just wanted to make sure. Thanks!

**Comment by arp242** [comment]
Seems to work well for me @chrisbra; I did notice that this gives an error btw:

    :set listchars=tab:x😼
    E474: Invalid argument: listchars=tab:x😼

Because it's a 4 byte character (U+1F63C)? Does seem to work well with any combination of 2 and 3 byte characters with your patch:

    set listchars=tab:☻–☺

Not sure if that's strictly related to this, but just something I noticed while testing.

**Comment by chrisbra** [comment]
> E474: Invalid argument: listchars=tab:x😼

That is a different error, that might need to be fixed (I suppose in `set_chars_option`).

**Comment by chrisbra** [comment]
small comment, U+1F63C  😼 is considered to be a wide character according to Unicode and those chars are note allowed according to the [documentation](https://github.com/vim/vim/blob/master/runtime/doc/options.txt#L4822):

> All characters must be single width.

So not a bug.
