### ISSUE TITLE
vimfile syntax highlighting gets vimSubst at wrong time.

### ISSUE THREAD

**Issue by tplunket** [vim/vim#4816]
**Describe the bug**
vimSubst highlighting is selected when `'s'` appears in an array in a function. This happens in gvim and vim on Windows 10.

**To Reproduce**
Open any .vim file and enable syntax highlighting. Paste the following lines.
    function A()
        let a = [ ['s', 'r'], ['a', 'bar'], [] ]
    endfunction

Observe that the `'s` is highlighted as a "vimSubst", the following single quote is a "vimSubstDelim", and then "vimSubstPat" matches until the fourth single quote, then there is an error flagged at the first closing bracket. Changing `'a'` to `'s'` repeats the problem in the second sub-array.

**Expected behavior**
That the quoted text `'s'` is highlighted as a string and the remainder of the line is highlighted correctly.

**Screenshots**
![vimfile_highlight_error](https://user-images.githubusercontent.com/16263054/63115332-c8926300-bf4b-11e9-83ff-7911e1fe18b3.png)

![vimfile_highlight_error_c](https://user-images.githubusercontent.com/16263054/63115412-fa0b2e80-bf4b-11e9-84b4-ce47f7c2ceb0.png)

**Environment (please complete the following information):**
(Also happens in gVim.)
VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 29 2019 04:53:42)
Included patches: 1-1234
Compiled by <alexpux@gmail.com>
Huge version without GUI.  Features included (+) or not (-):

**Additional context**

**Comment by chrisbra** [comment]
Yeah, can reproduce. 

This patch seems to fix it:
```patch
diff --git a/runtime/syntax/vim.vim b/runtime/syntax/vim.vim
index 2ed4b30a8..77ce3bab1 100644
--- a/runtime/syntax/vim.vim
+++ b/runtime/syntax/vim.vim
@@ -317,7 +317,7 @@ syn cluster vimSubstList    contains=vimPatSep,vimPatRegion,vimPatSepErr,vimSubstTw
 syn cluster    vimSubstRepList contains=vimSubstSubstr,vimSubstTwoBS,vimNotation
 syn cluster    vimSubstList    add=vimCollection
 syn match      vimSubst        "\(:\+\s*\|^\s*\||\s*\)\<\%(\<s\%[ubstitute]\>\|\<sm\%[agic]\>\|\<sno\%[magic]\>\)[:#[:alpha:]]\@!" nextgroup=vimSubstPat
-syn match      vimSubst        "\%(^\|[^\\]\)\<s\%[ubstitute]\>[:#[:alpha:]]\@!"       nextgroup=vimSubstPat contained
+syn match      vimSubst        "\%(^\|[^\\\"']\)\<s\%[ubstitute]\>[:#[:alpha:]\"']\@!" nextgroup=vimSubstPat contained
 syn match      vimSubst        "/\zs\<s\%[ubstitute]\>\ze/"            nextgroup=vimSubstPat
 syn match      vimSubst        "\(:\+\s*\|^\s*\)s\ze#.\{-}#.\{-}#"             nextgroup=vimSubstPat
 syn match      vimSubst1       contained       "\<s\%[ubstitute]\>"    nextgroup=vimSubstPat
```

cc @cecamp

**Comment by lacygoill** [comment]
Fixed by https://github.com/vim/vim/commit/1ff14ba24c4d85c008d7abe5e140dbb497ffea8d.
