### ISSUE TITLE
VimLeave autocommand not triggered for deadly signals

### ISSUE THREAD

**Issue by blueyed** [vim/vim#4818]
Given t-dying.vim:

```vim
func F()
  " echom v:dying
  call writefile([getpid(), v:dying], '/tmp/d')
endfunc

augroup test
  au VimLeave * call F()
augroup END

echom getpid()
call writefile([getpid()], '/tmp/p')
while 1
  sleep 100m
endwhile
```

Calling `vim -Nu t-dying.vim -cq` and `Ctrl-C`ing it will write the pid and "0" to `/tmp/d`.

But when not using Ctrl-C, but killing the process, it will not write anything there:
```
% vim -Nu t-dying.vim | cat -A
Vim: Warning: Output is not to a terminal
22828^[[?25l^[[J^[[1;1H^[[34h^[[?25h
Error detected while processing /home/user/Vcs/neovim/t-dying.vim:
line   13:^[[?25l^[[J^[[J
Interrupted^[[J
Interrupt: Press ENTER or type command to continue^[[34h^[[?25h^[[16;1HVim: Caught deadly signal TERM^M$

Vim: Finished.^M$
                 ^[[16;1H[3]    22828 terminated  vim -Nu t-dying.vim |
                                                                               22829 done        cat -A
```

line 13 is the "sleep 100m".

But also with `call getchar()`, or nothing blocking in the vimrc (i.e. when Vim is in normal mode), it will not trigger the autocommand.

That does not match the help.  From `:h v:dying`:

```
v:dying		Normally zero.  When a deadly signal is caught it's set to
		one.  When multiple signals are caught the number increases.
		Can be used in an autocommand to check if Vim didn't
		terminate normally. {only works on Unix}
		Example: >
	:au VimLeave * if v:dying | echo "\nAAAAaaaarrrggghhhh!!!\n" | endif
<		Note: if another deadly signal is caught when v:dying is one,
		VimLeave autocommands will not be executed.
```

I have tested SIGTERM and SIGHUP.

(I was looking into having the signal name in `v:dying` instead of just "1",
and then noticed that Vim is meant to increase the value if multiple signals
where caught (and wanted to test that then).)

(Note that Neovim passes this test, but only sets `v:dying` to 1 always - I have not tried if it would actually work in theory to send two signals after each other to make a difference)

**Comment by blueyed** [comment]
It does not look like `v:dying` would ever become 2 anyway - from a quick test it seems that this would only happen during the signal handler itself?  (I've tried to `sleep` in a VimLeave autocommand in Neovim, where this works in the first place, but also there v:dying would not have been incremented then).

**Comment by brammool** [comment]
Daniel Hahler wrote:

> It does not look like `v:dying` would ever become 2 anyway - from a
> quick test it seems that this would only happen during the signal
> handler itself?  (I've tried to `sleep` in a VimLeave autocommand in
> Neovim, where this works in the first place, but also there v:dying
> would not have been incremented then).

It does get set to 2 sometimes, but then we are in trouble and Vim does
not execute code that could check the value of v:dying.

-- 
ASCII stupid question, get a stupid ANSI.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by pavoljuhas** [comment]
This still does not seem to work.  I have created `checkleave.vim` file with the following content
```
au VimLeavePre * call writefile([v:dying], 'vimleave.log')
```
and ran `vim -N -u checkleave.vim --noplugin`.  The vimleave.log file is created on normal exit, but not after `kill PID` or `kill -HUP PID` issued from a different terminal.

I have tested on Linux with a recent vim 8.2.0750 and also at the associated patch 8.1.1872 neither of which worked.

**Comment by brammool** [comment]
When I try the script from the original report, I do get the /tmp/d file filled properly.
Not sure what matters.

**Comment by pavoljuhas** [comment]
I only see the /tmp/d file if the original script is run as `vim -Nu t-dying.vim -cq` and I stop it with `Ctrl-C`.  However it exits because of `-cq` so it is a normal exit with `v:dying == 0`.

If I run it as follows, the /tmp/d file is not written:
```sh
$ rm -f /tmp/p /tmp/d
$ vim -Nu t-dying.vim | cat -A

# another terminal
$ kill -HUP $(cat /tmp/p)
$ ls /tmp/d
ls: cannot access '/tmp/d': No such file or directory
```

Is there a scenario where VimLeave autocommands run and `v:dying != 0`?

FYI, my use case for `v:dying` is that I would like to write viminfo file when `gvim` session over ssh dies because of ssh timeout, i.e., the forwarded DISPLAY stops working.  I am not sure if gvim dies a hard crash or if it runs some exit-cleanups on such termination.

**Comment by brammool** [comment]
> I only see the /tmp/d file if the original script is run as `vim -Nu
> t-dying.vim -cq` and I stop it with `Ctrl-C`.  However it exits
> because of `-cq` so it is a normal exit with `v:dying == 0`.
> 
> If I run it as follows, the /tmp/d file is not written:
> ```sh
> $ rm -f /tmp/p /tmp/d
> $ vim -Nu t-dying.vim | cat -A
> 
> # another terminal
> $ kill -HUP $(cat /tmp/p)
> $ ls /tmp/d
> ls: cannot access '/tmp/d': No such file or directory
> ```

As I mentioned, for me I do get the /tmp/d file written and it contains
"1" in the second line.

> Is there a scenario where VimLeave autocommands run and `v:dying != 0`?

Yes.

> FYI, my use case for `v:dying` is that I would like to write viminfo
> file when `gvim` session over ssh dies because of ssh timeout, i.e.,
> the forwarded DISPLAY stops working.  I am not sure if gvim dies a
> hard crash or if it runs some exit-cleanups on such termination.

gvim over ssh would be using X forwarding?  No idea what happens with
that.

Vim does save the viminfo file whenever possible.  If a clean exit is
possible, it should already take care of it.

-- 
From "know your smileys":
 <|-) Chinese
 <|-( Chinese and doesn't like these kind of jokes

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by pavoljuhas** [comment]
> As I mentioned, for me I do get the /tmp/d file written and it contains
> "1" in the second line.

I can see it now, sorry about not checking more carefully.
At the same time I noticed that `VimLeavePre` autocommands
are skipped in dying vim while `VimLeave` are triggered.
Here is another version of checkleave.vim:

```
set nocompatible
au VimLeavePre * call writefile([v:dying], 'vimleavepre.log')
au VimLeave * call writefile([v:dying], 'vimleave.log')
```

If I kill such session only the vimleave.log file appears.

> > FYI, my use case for `v:dying` is that I would like to write viminfo
> > file when `gvim` session over ssh dies because of ssh timeout, i.e.,
> > the forwarded DISPLAY stops working.  I am not sure if gvim dies a
> > hard crash or if it runs some exit-cleanups on such termination.

> gvim over ssh would be using X forwarding?  No idea what happens with that.
>
> Vim does save the viminfo file whenever possible.  If a clean exit is
> possible, it should already take care of it.

Indeed, I see Vim writes viminfo when killed with HUP or TERM signal.
An ssh gvim session that is killed by ssh timeout and dropped X-forwarding
does not write viminfo, that seems to be a hard crash.

However, I found a workaround is to use [xpra](https://xpra.org) for
display forwarding.  The xpra-managed display is persistent and a
dropped connections can be restored later.

**Comment by brammool** [comment]
> > As I mentioned, for me I do get the /tmp/d file written and it contains
> > "1" in the second line.
> 
> I can see it now, sorry about not checking more carefully.
> At the same time I noticed that `VimLeavePre` autocommands
> are skipped in dying vim while `VimLeave` are triggered.
> Here is another version of checkleave.vim:
> 
> ```
> set nocompatible
> au VimLeavePre * call writefile([v:dying], 'vimleavepre.log')
> au VimLeave * call writefile([v:dying], 'vimleave.log')
> ```
> 
> If I kill such session only the vimleave.log file appears.

Hmm, I was going to say "use VimLeave then", but the docs actually
mention that it's triggered unless v:dying is 2 or more.
We can use the same code as for VimLeave to unblock autocommands.
I suppose that won't be a problem for anyone.
 
> > > FYI, my use case for `v:dying` is that I would like to write viminfo
> > > file when `gvim` session over ssh dies because of ssh timeout, i.e.,
> > > the forwarded DISPLAY stops working.  I am not sure if gvim dies a
> > > hard crash or if it runs some exit-cleanups on such termination.
> 
> > gvim over ssh would be using X forwarding?  No idea what happens with that.
> >
> > Vim does save the viminfo file whenever possible.  If a clean exit is
> > possible, it should already take care of it.
> 
> Indeed, I see Vim writes viminfo when killed with HUP or TERM signal.
> An ssh gvim session that is killed by ssh timeout and dropped X-forwarding
> does not write viminfo, that seems to be a hard crash.
> 
> However, I found a workaround is to use [xpra](https://xpra.org) for
> display forwarding.  The xpra-managed display is persistent and a
> dropped connections can be restored later.

-- 
Laughing helps. It's like jogging on the inside.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
