### ISSUE TITLE
Issues with modeless selections longer than one line

### ISSUE THREAD

**Issue by lkintact** [vim/vim#4824]
The issues are perhaps related to bug #4783.

1. Run `gvim.exe --clean`
2. Type some text that's more than one line long, for example
```
line1
line2
line3
```
3. With <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+Left_click make a modeless selection of the text
4. Hit <kbd>:</kbd> and press <kbd>Ctrl</kbd>+<kbd>y</kbd> to put the selection into the clipboard

Issue 1: `:reg` reports that the clipboard register (`"*`) only contains the first line ("line1") of the text, without \<EOL\>.

Issue 2: Gvim adds spaces to the lines in the register, which can be seen by putting the copied text with `"*P`, executing `:set list`, and selecting the text with <kbd>Shift</kbd>+<kbd>v</kbd>, then hitting `2j`.

Vim: gvim_8.1.1866_x86.zip from https://github.com/vim/vim-win32-installer/releases/tag/v8.1.1866
OS: Windows 10 Home 1803

**Comment by lkintact** [comment]
Sorry, I realize now that Issue 1 is not an issue, but a normal consequence of Issue 2.

**Comment by brammool** [comment]
Should be fixed by patch 8.1.1871, please check.

**Comment by lkintact** [comment]
>Should be fixed by patch 8.1.1871, please check.

@brammool Just tried with gvim_8.1.1890_x86.zip, seems to work properly now, thank you for the fixes.
