### ISSUE TITLE
python pep8 code style

### ISSUE THREAD

**Issue by spavlovich001** [vim/vim#483]
Default indent python language so bad. 
Vim plugin Bundle 'tell-k/vim-autopep8' and pip install autopep8 package results in complete satisfaction. But this indentions(all specification pep8) should be initially in vim.

Please implement all pep8 specification python code style

**Comment by chrisbra** [comment]
Please discuss this with the maintainer of the current indentation file. See [Contributing.md](https://github.com/vim/vim/blob/master/CONTRIBUTING.md#syntax-indent-and-other-runtime-files).

**Comment by spavlovich001** [comment]
bustos@caltech.edu
Delivery to the following recipient failed permanently:

**Comment by chrisbra** [comment]
Then ask  @tell-k, if he would be willing to maintain the default vim indent file (create a issue there).

**Comment by memeplex** [comment]
If you want to include pep-8 indentation in vim (I think it's a good idea) I could maintain it in case tell-k doesn't want to do it.

**Comment by chrisbra** [comment]
whoever wants to maintain a new python indent file, should send an updated file to bram for inclusion. Please update the header and move the current maintainer to the previous maintainer. Thanks.
