### ISSUE TITLE
Copy & Paste Appends Spaces

### ISSUE THREAD

**Issue by zdohnal** [vim/vim#4833]
Copy & Paste Appends Spaces

**Describe the bug**
I have Fedora report https://bugzilla.redhat.com/show_bug.cgi?id=1738363 where Gabriel has issues with copy/paste in GVim which adds spaces between the last character and the newline. He tried to run it without any vimrc/gvim, viminfo etc. according https://vimhelp.org/vim_faq.txt.html#faq-2.5 , but the issue still occurs, although I'm not able to reproduce it. It occurs only when cursor is on Ex command prompt.

**To Reproduce**
Detailed steps to reproduce the behavior:
1.  Launch gvim editor.
2.  Insert Mode (i)
3.  Enter at least 2 lines.
4.  Command Mode (Esc)
5.  Print Lines 1 & 2 (:1,2p)
6.  Copy lines into clipboard from file or printed by the command above.
7.  Command Mode (Esc)
8.  Move cursor to last line (G).
9. Open (o) new line below cursor to insert lines.
10. Paste content in clipboard.
11. Command Mode (Esc)
12. Observe the difference from the source lines.

**Actual behavior**
1. For 1 line, pasted content will have spaces between the last character & the newline.
2. For multiple lines, pasted content is clobbered.

**Expected behavior**
The pasted content should match the content copied to the clipboard.

Environment (please complete the following information):**
 - Vim version 8.1.1713
 - OS: Fedora 29
 - Terminal: GUI

**Additional context**
Happens only when the cursor is on Ex (:) command prompt.

**Comment by chrisbra** [comment]
It is unclear to me, how do you copy at step 6 (when printing the line content using e.g. `:1,2p`)?

**Comment by brammool** [comment]
Please try the latest version, at least 8.1.1871.  There was a fix for modeless selection.

**Comment by zdohnal** [comment]
@brammool Ok, I'll check the newest version, I think I was probably able to reproduce yesterday.

It seems the key is to be in Ex mode (after typing ':') and then mark the text in file, click on 'Copy to clipboard' and then paste it somewhere outside of GVim. Then several blank lines and the last line are pasted out...

I'm not sure if it is the behavior Gabriel (original reporter) hit too (I asked him on the ticket, he has not replied yet), but it is the strange behavior too.

**Comment by zdohnal** [comment]
@brammool It works (at least the issue I hit) correctly now with 8.1.1890. But I'm not sure if it is the same problem as Gabriel hit, so I would like to leave the issue open until I'll check it with Gabriel.

Thank you for the heads up and help!

**Comment by brammool** [comment]
> @brammool It works (at least the issue I hit) correctly now with
> 8.1.1890. But I'm not sure if it is the same problem as Gabriel hit,
> so I would like to leave the issue open until I'll check it with
> Gabriel.

If that was about using the modeless selection (not Visual selection)
then it's probably the same cause and fix.

> Thank you for the heads up and help!

Enjoy!

-- 
The sooner you fall behind, the more time you'll have to catch up.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by zdohnal** [comment]
Gabriel said his issue is the same as me, so it is fixed in current master. Thank you again!
