### ISSUE TITLE
Highlight command line

### ISSUE THREAD

**Issue by flashrunnerGH** [vim/vim#4838]
It is hard to distinguish between the file itself and command line if you don't use the status line. The ability to highlight command line would resolve this issue.

**Comment by chrisbra** [comment]
Hm, I suppose this might be a bit confusing for new Vim users. However for Vi users, it should be quite clear, that the last line never belongs to the buffer, but will always be used for entering commands or echoing messages. And once you use several windows, the command line will be easily visible because of the statusline. For new users (especially when running with the new defaults), the `showcmd` and `ruler` setting also make it clear, that this line does not belong to the buffer I believe (because it always displays something on that line).

And for me it is quite clear where the command line starts, because it will be always the last line (and it won't have the `~` EOL lines).

**Comment by brammool** [comment]
There is a tendency in UI design to leave out all the non-essential coloring, especially backgrounds, and keep everything white (or dark).  It's just a matter of getting used to, I haven't heard this complaint from experienced Vim users.  And if you really want, you can set laststatus to 2 to always have the status line.

**Comment by flashrunnerGH** [comment]
> There is a tendency in UI design to leave out all the non-essential coloring, especially backgrounds, and keep everything white (or dark). It's just a matter of getting used to, I haven't heard this complaint from experienced Vim users. And if you really want, you can set laststatus to 2 to always have the status line.

Why status line is not in background color by default? Why do we have ability to change its color? Isn't it a tendency in UI design to leave out all the non-essential coloring?
Command line could be not colored by default.

**Comment by chrisbra** [comment]
Command line isn't colored and can't be. Styling of the statusline is different and coloring there is important, just look at all the fancy statusline plugins.

**Comment by flashrunnerGH** [comment]
> Styling of the statusline is different and coloring there is important, just look at all the fancy statusline plugins.

I don't use statusline at all because I have Ctrl-G, ruler, commands + 1 extra line of text. But I do use command line a lot and this is what important for me.
> Command line isn't colored and can't be.

Yes. That is why I requested it. If it could there would be a lot of fancy command line plugins too.

**Comment by chrisbra** [comment]
Except that the statusline is for displaying Information, while the command line is for inputting commands. That would need some kind of interface definition what to style how. Sounds complex for questionable benefit.

**Comment by flashrunnerGH** [comment]
```
hi StatusLine ctermbg=NONE
hi CommandLine ctermbg=Grey
```

**Comment by chrisbra** [comment]
That does not make a fancy command line, that you wanted

**Comment by chrisbra** [comment]
I figured I should elaborate. I understood your request like you wanted to have the ability to have the command line styled with different sections, but the cursor on the command line should be configurable to have a different style. Then you want powerline like section delimiters with a different highlighting and then even other highlighting for the messaging output. 

That's what I meant with complex for questionable benefit.

A custom highlighting group just for the command line however sounds doable.

**Comment by flashrunnerGH** [comment]
> A custom highlighting group just for the command line

This is all I wanted!
