### ISSUE TITLE
Null-Dereference in misc2.c

### ISSUE THREAD

**Issue by JZuming** [vim/vim#4839]
**Describe the bug**
The malloc() in the call stack shown below may fail:
#1 Call malloc() in lalloc(), at misc2.c: 924
#2 Call lalloc() in alloc(), at misc2.c: 827 
#3 Call alloc() in mf_alloc_bhdr, at memfile.c: 898
#4 Call mf_alloc_bhdr in mf_new(), at memfile.c: 379
#5 Call mf_new() in ml_new_data(), at memline.c: 4015
#6 Call ml_new_data() in ml_open(), at memline.c: 392
#7 Call ml_open() in open_buffer(), at buffer.c: 167
#8 Call open_buffer() in create_windows(), at main.c: 2750
#9 Call create_windows() in vim_main2(), at main.c: 728
#10 Call vim_main2() in main(), at main.c: 444

If the malloc() in this call stack fails, the return value of ml_open() at buffer.c: 167 is FAIL. And then the program will execute some instructions and check whether curbuf is NULL at buffer.c: 181. And curbuf is NULL actually, so the program will continue and enter the function parse_queued_messages() finally. The call stack is shown below:
#1 Call parse_queued_messages() in inchar() at getchar.c:3036
#2 Call inchar() in vgetorpeek() at getchar.c:2875
#3 Call vgetorpeek() in vgetc() at getchar.c:1602
#4 Call vgetc () in safe_vgetc() at getchar.c:1821
#5 Call safe_vgetc() in wait_return() at message.c:1098
#6 Call wait_return() in getout() at main.c:1502
#7 Call getout() in open_buffer() at buffer.c: 184
#8 Call open_buffer() in create_windows() at main.c:2750
#9 Call create_windows() in vim_main2() at main.c:728
#10 Call vim_main2 () in main() at main.c:444

In parse_queued_messages(), the program will execute the instruction at misc2.c: 4446 and curbuf is NULL, as a result of which the program will crash.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Make the malloc() shown at **Describe the bug** fail.
2. The program will crash.

**Expected behavior**
The program would not crash when malloc() fails.

**Additional context**
This bug is found by my fuzzing tool and the bug is triggered at runtime.

**Comment by chrisbra** [comment]
Unfortunately, the code changed a bit and functions have been moved around, so the above call stack is not that much useful anymore :(

However I think the following patch fixes the described issue:

```patch
diff --git a/src/getchar.c b/src/getchar.c
index f9bfab829..8837eb8e8 100644
--- a/src/getchar.c
+++ b/src/getchar.c
@@ -2059,8 +2059,8 @@ f_getcharmod(typval_T *argvars UNUSED, typval_T *rettv)
     void
 parse_queued_messages(void)
 {
-    int            old_curwin_id = curwin->w_id;
-    int            old_curbuf_fnum = curbuf->b_fnum;
+    int            old_curwin_id;
+    int            old_curbuf_fnum;
     int            i;
     int            save_may_garbage_collect = may_garbage_collect;
     static int entered = 0;
@@ -2071,6 +2071,13 @@ parse_queued_messages(void)
     if (updating_screen)
        return;

+    // safety check: curbuf could be NULL vim/vim#4839
+    if (curbuf == NULL || curwin == NULL)
+       return;
+
+    old_curbuf_fnum = curbuf->b_fnum;
+    old_curwin_id = curwin->w_id;
+
     ++entered;

     // may_garbage_collect is set in main_loop() to do garbage collection when
```

also available here: https://github.com/chrisbra/vim/commit/63c99532b39a347df7ed0

**Comment by brammool** [comment]
I could include the patch, but I suspect it will just crash somewhere else.  It's better to exit (hopefully cleanly) if allocating the first window and buffer fails.

**Comment by brammool** [comment]
Oh wait, it's already exiting, but fails while doing that.
