### ISSUE TITLE
Regression in 7.4.902 breaks window navigation

### ISSUE THREAD

**Issue by malcolmr** [vim/vim#484]
After a0f849e, using netrw seems to break window navigation in some circumstances:

``` sh
$ cat > /tmp/vimrc
set nocompatible 
filetype plugin on
$ vim -u /tmp/vimrc -U NONE 
:Se
(open any file)
^wj
:Se
```

At this point you have three splits: 1) the file you opened, 2) a netrw window, and 3) the [No Name] window you started with.

In 7.4.901, the focus is now in the newly-opened netrw window, and everything works.
After a0f849e (i.e. in 7.4.902), the focus is in the top-most window, and window navigation (`^wj`, `:wincmd`, etc) no longer functions.

I'm not entirely sure whether this is a netrw problem or a Vim problem, though it seems odd that a plugin would be able to break this.

**Comment by chrisbra** [comment]
Hm, I can't seem to verify this. What plugins have you been running?

**Comment by malcolmr** [comment]
@chrisbra Unless I've messed something up, this is compiled-from-source directly from this repository (using something like `./configure && make; VIM=runtime/ src/vim ...`). Per the reproduction shown above, no plugins beyond what's shipped with Vim (netrw, in this case).

I'm running on Ubuntu Trusty, in case that helps.

**Comment by raymond-w-ko** [comment]
I have also been getting this bug, and in fact am experiencing this right now. `:map <C-w>` shows no mappings bound, so it is indeed very strange that netrw.vim can mess up Vim so that this happens. I am on a regular JavaScript buffer, so this isn't even on a netrw buffer.

**Comment by chrisbra** [comment]
Thanks. I can now reproduce it. Not sure, why it didn't work before. This looks like the BufEnter savePosn and restorePosn autocommands reset the cursor position to the wrong window.  One can use `:noa wincmd j` to move the cursor by makeing sure, that the autocommands do not fire. So I think this is caused by a netrw problem.

**Comment by malcolmr** [comment]
Thanks, it's definitely something in that area. Reverting just `runtime/autoload/netrw.vim` to the previous version fixes this problem.

I think it might be something to do with how netrw is finding the buffer we're in, since this also depends on having opened the same directory both times (e.g. `:Se ~` and `:Se ~` will trigger it as well, but not two different paths).

In fact, if we comment out the call to `netrw#RestorePosn()` in s:NetrwBrowse(), the problem goes away. (The whole "If there is a rexposn: restore position with rexposn" block was added in a0f849e:

``` patch
--- a/runtime/autoload/netrw.vim
+++ b/runtime/autoload/netrw.vim
@@ -3794,11 +3794,11 @@ fun! s:NetrwBrowse(islocal,dirname)

   " If there is a rexposn: restore position with rexposn
   " Otherwise            : set rexposn
-  if exists("s:rexposn_".bufnr("%"))
-   NetrwKeepj call netrw#RestorePosn(s:rexposn_{bufnr('%')})
-  else
+  " if exists("s:rexposn_".bufnr("%"))
+  "  NetrwKeepj call netrw#RestorePosn(s:rexposn_{bufnr('%')})
+  " else
    NetrwKeepj call s:SetRexDir(a:islocal,b:netrw_curdir)
-  endif
+  " endif
   if v:version >= 700 && has("balloon_eval") && &beval == 0 && &l:bexpr == "" && !exists("g:netrw_nobeval")
    let &l:bexpr= "netrw#BalloonHelp()"
 "   call Decho("set up balloon help: l:bexpr=".&l:bexpr,'~'.expand("<slnum>"))
```

Opening a new netrw window onto the same path reuses the same buffer, so `bufnr('%')` doesn't change from when we used it before, and I'd guess that `s:rexposn_{bufnr('%')}` then somehow refers to the original window we were using (which now contains the file we opened), which is what we snap back into.

**Comment by momer** [comment]
The easiest way to reproduce this for me is:

```
mycomputer: cd my_dir
mycomputer: vim .
# navigate to a file, start editing
:vsp
:E
# navigate back to the my_dir folder in navigator, and experience the buffer lock-out
```

**Comment by silent-e** [comment]
I got hit by this too and am the OP on the macvim issue #185 just referenced.  So, officially…

+1

:smile:

(e)

**Comment by gwicke** [comment]
The work-around described by @malcolmr in https://github.com/vim/vim/issues/484#issuecomment-158020635 avoids the issue for me.

**Comment by dbarnett** [comment]
Any progress? I'm stuck sitting on an old vim build until this is fixed.

**Comment by k-takata** [comment]
This should be already fixed with netrw v155 which is included in e0fa3742ead676a3074a10edadbc955e1a89153d.
And here is a comment from the author (which was not redirected here):
https://groups.google.com/d/msg/vim_dev/xrkwm035gKE/syC63OuiBgAJ

**Comment by mcandre** [comment]
Which version of Vim will have the fix?

**Comment by k-takata** [comment]
7.4.1368.
