### ISSUE TITLE
Null-Dereference in charset.c

### ISSUE THREAD

**Issue by JZuming** [vim/vim#4842]
**Describe the bug**
The malloc() in the call stack shown below may fail:
#1 Call malloc() in lalloc(), at misc2.c: 924
#2 Call lalloc() in alloc(), at misc2.c: 827
#3 Call alloc() in vim_strsave(), at misc2.c: 1279
#4 Call vim_strsave() in set_string_option_direct(), at option.c: 5989
#5 Call set_string_option_direct() in set_option_default(), at option.c: 3782
#6 Call set_option_default() in set_options_default(), at option.c: 3860
#7 Call set_options_default() in set_init_1(), at option.c: 3535
#8 Call set_init_1() in common_init(), at main.c: 1010
#9 Call common_init() in main(), at main.c: 173

If the malloc() in this call stack fails, vim_strsave() will return NULL to s in set_string_option_direct(). So the program will not execute set_string_option_global() at option.c: 6000, as the result of which *options[idx].var will be NULL. So *option[i].var will be NULL because i is equal to idx in set_options_default().

After set_options_default() return, set_init_1() will call option_expand() iteratively. In option_expand(), the variable val is assigned *options[opt_idx].var at option.c: 5608, so val is NULL. And then option_expand() calls expand_env_esc() with val as the parameter srcp, so srcp is NULL in expand_env_esc().

Finally, expand_env_esc() calls skipwhite() with srcp as the parameter q, so q is NULL in skipwhite().  In skipwhite(), the variable p is assigned q, so p is NULL too. When skipwhite() uses *p at charset.c: 1456, the Null-Dereference occurs and the program crashes.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Make the malloc() shown at **Describe the bug** fail.
2. The program will crash.

**Expected behavior**
The program would not crash when malloc() fails.

**Additional context**
This bug is found by my fuzzing tool and the bug is triggered at runtime.

**Comment by brammool** [comment]
> **Describe the bug**
> The malloc() in the call stack shown below may fail:
> #1 Call malloc() in lalloc(), at misc2.c: 924
> #2 Call lalloc() in alloc(), at misc2.c: 827
> #3 Call alloc() in vim_strsave(), at misc2.c: 1279
> #4 Call vim_strsave() in set_string_option_direct(), at option.c: 5989
> #5 Call set_string_option_direct() in set_option_default(), at option.c: 3782
> #6 Call set_option_default() in set_options_default(), at option.c: 3860
> #7 Call set_options_default() in set_init_1(), at option.c: 3535
> #8 Call set_init_1() in common_init(), at main.c: 1010
> #9 Call common_init() in main(), at main.c: 173
> 
> If the malloc() in this call stack fails, vim_strsave() will return
> NULL to s in set_string_option_direct(). So the program will not
> execute set_string_option_global() at option.c: 6000, as the result of
> which *options[idx].var will be NULL. So *option[i].var will be NULL
> because i is equal to idx in set_options_default().
> 
> After set_options_default() return, set_init_1() will call
> option_expand() iteratively. In option_expand(), the variable val is
> assigned *options[opt_idx].var at option.c: 5608, so val is NULL. And
> then option_expand() calls expand_env_esc() with val as the parameter
> srcp, so srcp is NULL in expand_env_esc().
> 
> Finally, expand_env_esc() calls skipwhite() with srcp as the parameter
> q, so q is NULL in skipwhite().  In skipwhite(), the variable p is
> assigned q, so p is NULL too. When skipwhite() uses *p at charset.c:
> 1456, the Null-Dereference occurs and the program crashes.
> 
> **To Reproduce**
> Detailed steps to reproduce the behavior:
> 1. Make the malloc() shown at **Describe the bug** fail.
> 2. The program will crash.
> 
> **Expected behavior**
> The program would not crash when malloc() fails.
> 
> **Additional context**
> This bug is found by my fuzzing tool and the bug is triggered at runtime.

There is not much we can do if initializing the options fails.  We can
only exit.  To keep this easy we should just exit in do_outofmem_msg()
if "starting" is still at NO_SCREEN.  But printing the error message may
also make Vim crash, nothing we can do about that.

-- 
% cat /usr/include/real_life.h
void life(void);

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
