### ISSUE TITLE
Highlight group for the command line

### ISSUE THREAD

**Issue by flashrunnerGH** [vim/vim#4849]
It is hard to distinguish between the file itself and command line if you don't use the status line. The ability to set custom highlight group for the command line would resolve this issue.

**Comment by qsmodo** [comment]
+1 to that request.

For the time being, [this](https://stackoverflow.com/a/48055834)

```
au CmdLineEnter * hi Normal ctermfg=white ctermbg=NONE
au CmdLineLeave * hi Normal ctermfg=NONE  ctermbg=NONE
```

seems to work well enough, but it has side effects for `/search`.

**Comment by brammool** [comment]
Using 'wincolor' should work better:
```
set wincolor=RealNormal
hi RealNormal ctermbg=white  " whatever your normal colors are
hi Normal ctermbg=lightGrey ctermfg=darkBlue
```

**Comment by bfrg** [comment]
I think this can be closed. Implemented using a new highlight group, see `:h hl-MsgArea` (though still a little buggy).

**Comment by chrisbra** [comment]
closing then.
