### ISSUE TITLE
popup_create() displays number and cursorline in popup window when a buffer number is passed

### ISSUE THREAD

**Issue by bfrg** [vim/vim#4857]
**Describe the bug**
1. `popup_create()` uses `number` and `cursorline` settings of the current window and displays both in the popup window. This happens only when a buffer number is passed to `popup_create()`. It doesn't happen when a list of strings is passed.
2. When the `#{cursorline: 1}` option is passed to `popup_create()`, the popup's cursorline is also visible in the window that displays the buffer that was passed to `popup_create()`.
The sign column also appears suddenly.

**To Reproduce**
1. Run `vim --clean popup.vim -c "source popup.vim"`
```vim
" popup.vim
set number cursorline
call popup_create(1, #{
	\ pos: 'center',
	\ minwidth: 60,
	\ maxwidth: 60,
	\ minheight: 10,
	\ maxheight: 10,
	\ padding: [1]
	\ })
```
2. Run `vim --clean popup.vim -c "source popup.vim"`
```vim
" popup.vim
set number cursorline
call popup_create(1, #{
	\ pos: 'center',
	\ minwidth: 60,
	\ maxwidth: 60,
	\ minheight: 10,
	\ maxheight: 10,
        \ cursorline: 1,
	\ padding: [1]
	\ })
```

**Screenshots**

![screenshot-2019-08-24_005623](https://user-images.githubusercontent.com/6266600/63628074-d8c0d700-c60a-11e9-80b0-5c75c23c036a.png)

![screenshot-2019-08-24_005427](https://user-images.githubusercontent.com/6266600/63628073-d8c0d700-c60a-11e9-9615-c9985b3adcc4.png)

**Environment**
- Vim version `8.1.1912`
- OS: Gentoo Linux
- Terminal: xfce4-terminal

**Comment by brammool** [comment]
> **Describe the bug**
> 1. `popup_create()` uses `number` and `cursorline` settings of the current window and displays both in the popup window. This happens only when a buffer number is passed to `popup_create()`. It doesn't happen when a list of strings is passed.
> 2. When the `#{cursorline: 1}` option is passed to `popup_create()`, the popup's cursorline is also visible in the window that displays the buffer that was passed to `popup_create()`.
> The sign column also appears suddenly.
> 
> **To Reproduce**
> 1. Run `vim --clean popup.vim -c "source popup.vim"`
> ```vim
> " popup.vim
> set number cursorline
> call popup_create(1, #{
> 	\ pos: 'center',
> 	\ minwidth: 60,
> 	\ maxwidth: 60,
> 	\ minheight: 10,
> 	\ maxheight: 10,
> 	\ padding: [1]
> 	\ })
> ```
> 2. Run `vim --clean popup.vim -c "source popup.vim"`
> ```vim
> " popup.vim
> set number cursorline
> call popup_create(1, #{
> 	\ pos: 'center',
> 	\ minwidth: 60,
> 	\ maxwidth: 60,
> 	\ minheight: 10,
> 	\ maxheight: 10,
>         \ cursorline: 1,
> 	\ padding: [1]
> 	\ })
> ```

Yeah, we probably should not use window-local options for the popup
window.  Buffer-local options should be used though, thus it's still
different from creating a new buffer.

-- 
hundred-and-one symptoms of being an internet addict:
107. When using your phone you forget that you don't have to use your
     keyboard.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
