### ISSUE TITLE
CursorLine highlighting applied to previous line after pasting a new line above

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#4862]
**Describe the bug**

After pasting a line above the current one, while `'cursorline'` is set, the previous line is sometimes wrongly highlighted by CursorLine.

**To Reproduce**

1. Run this shell command:

       $ echo test | vim -Nu NONE +'set cursorline' -

2. Press `yy` to yank the current line, then `P` to paste it above.

Both lines are highlighted with CursorLine.

**Expected behavior**

Only the first line is highlighted with CursorLine.

**Screenshots**

![gif](https://user-images.githubusercontent.com/8505073/63648685-947d2600-c733-11e9-8528-e74329a005ef.gif)

**Environment**

 - Vim version: 8.1  Included patches: 1-1890
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: st

**Additional context**

The same issue applies when `:put!` is run, or `[p` is pressed.

The issue disappears:

   - after the cursor is moved on another line
   - if `'conceallevel'` is set to a non-zero value
   - if some syntax item is installed (i.e. the output of `:syn list` is not `No Syntax items defined for this buffer`)

**Comment by brammool** [comment]
> **Describe the bug**
> 
> After pasting a line above the current one, while `'cursorline'` is
> set, the previous line is sometimes wrongly highlighted by CursorLine.
> 
> **To Reproduce**
> 
> 1. Run this shell command:
> 
>        $ echo test | vim -Nu NONE +'set cursorline' -
> 
> 2. Press `yy` to yank the current line, then `P` to paste it above.
> 
> Both lines are highlighted with CursorLine.
> 
> **Expected behavior**
> 
> Only the first line is highlighted with CursorLine.
> 
> **Screenshots**
> 
> ![gif](https://user-images.githubusercontent.com/8505073/63648685-947d2600-c733-11e9-8528-e74329a005ef.gif)
> 
> **Environment**
> 
>  - Vim version: 8.1  Included patches: 1-1890
>  - OS: Ubuntu 16.04.6 LTS
>  - Terminal: st
> 
> **Additional context**
> 
> The same issue applies when `:put!` is run, or `[p` is pressed.
> The issue disappears if `'conceallevel'` is set to a non-zero value.
> The issue disappears after the cursor is moved on another line.

I can easily reproduce it. And can fix it.  Strangely I could not make
it fail in a screenshot test.  Would be good to have a test for this.

-- 
Amnesia is one of my favorite words, but I forgot what it means.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by tom-m** [comment]
I propose this test for the issue. The test fails before the patch and does not fail after it.

Tom

_P.S. By the way, some test functions in the `test_highlight.vim` end with side effects. Modified buffers and windows with matchadd() highlighting active._

```diff
diff --git a/src/testdir/test_highlight.vim b/src/testdir/test_highlight.vim
index 3d640bbe8..46d68f4f1 100644
--- a/src/testdir/test_highlight.vim
+++ b/src/testdir/test_highlight.vim
@@ -552,6 +552,26 @@ func Test_cursorline_after_yank()
   call delete('Xtest_cursorline_yank')
 endfunc
 
+func Test_put_before_cursorline()
+  " test for issue #4862
+  new
+  only!
+  call setline(1, 'A')
+  redraw
+  let std_attr = screenattr(1, 1)
+  set cursorline
+  redraw
+  let cul_attr = screenattr(1, 1)
+  normal yyP
+  redraw
+  " Line 1 has cursor so it should be highlighted with CursorLine.
+  call assert_equal(cul_attr, screenattr(1, 1))
+  " And CursorLine highlighting from the second line should be gone.
+  call assert_equal(std_attr, screenattr(2, 1))
+  set nocursorline
+  bwipe!
+endfunc
+
 func Test_cursorline_with_visualmode()
   CheckScreendump
 
```

**Comment by brammool** [comment]
> I propose this test for the issue. The test fails before the patch and
> does not fail after it.

Thanks, I'll include it.

> _P.S. By the way, some test functions in the `test_highlight.vim` end
> with side effects. Modified buffers and windows with matchadd()
> highlighting active._

Well, if you can suggest improvements, they are welcome.  But currently
it looks like the test works.

-- 
I noticed my daughter's Disney-net password on a sticky note:
"MickeyMinnieGoofyPluto".  I asked her why it was so long.
"Because they say it has to have at least four characters."

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
