### ISSUE TITLE
A typescript syntax is broken.

### ISSUE THREAD

**Issue by aiya000** [vim/vim#4864]
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Describe the bug**
Broken typescript syntax highlight.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. On CLI, `vim -u NONE foo.ts`
1. `:syntax on`
1. input the below code

```typescript
const y = ((`():${x}`))
const foo = 10
```

`const foo = 10` is not highlighted.

**Expected behavior**
`const foo = 10` is highlighted.

**Screenshots**

![スクリーンショット 2019-08-26 11 32 57](https://user-images.githubusercontent.com/4897842/63661490-c3f46700-c7f5-11e9-8248-efb1041d69c7.png)

**Environment (please complete the following information):**

```

VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 20 2019 10:34:41)
macOS version
Included patches: 1-1890
Compiled by aiya000
Huge version without GUI.  Features included (+) or not (-):
+acl               ++builtin_terms    +cmdline_info      +diff              -farsi             -hangul_input      +libcall           +modify_fname      -mouse_sysmouse    +packages          +python3/dyn       -sound             -tag_any_white     +timers            +visualextra       -xfontset
+arabic            +byte_offset       +comments          +digraphs          +file_in_path      +iconv             +linebreak         +mouse             +mouse_urxvt       +path_extra        +quickfix          +spell             -tcl               +title             +viminfo           -xim
+autocmd           +channel           +conceal           -dnd               +find_in_path      +insert_expand     +lispindent        -mouseshape        +mouse_xterm       +perl              +reltime           +startuptime       +termguicolors     -toolbar           +vreplace          -xpm
+autochdir         +cindent           +cryptv            -ebcdic            +float             +job               +listcmds          +mouse_dec         +multi_byte        +persistent_undo   +rightleft         +statusline        +terminal          +user_commands     +wildignore        -xsmp
-autoservername    -clientserver      +cscope            +emacs_tags        +folding           +jumplist          +localmap          -mouse_gpm         +multi_lang        +postscript        +ruby              -sun_workshop      +terminfo          +vartabs           +wildmenu          -xterm_clipboard
-balloon_eval      +clipboard         +cursorbind        +eval              -footer            +keymap            +lua               -mouse_jsbterm     -mzscheme          +printer           +scrollbind        +syntax            +termresponse      +vertsplit         +windows           -xterm_save
+balloon_eval_term +cmdline_compl     +cursorshape       +ex_extra          +fork()            +lambda            +menu              +mouse_netterm     +netbeans_intg     +profile           +signs             +tag_binary        +textobjects       +virtualedit       +writebackup       
-browse            +cmdline_hist      +dialog_con        +extra_search      -gettext           +langmap           +mksession         +mouse_sgr         +num64             +python/dyn        +smartindent       -tag_old_static    +textprop          +visual            -X11               
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib -L/usr/local/lib -o vim        -lncurses  -liconv -framework AppKit  -pagezero_size 10000 -image_base 100000000 -L/usr/local/Cellar/luajit/2.0.5/lib -lluajit-5.1 -mmacosx-version-min=10.13 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.28.0/lib/perl5/5.28.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc    -lruby.2.5.3 -lobjc    
```

 - OS: macOS 10.14
 - Terminal: iTerm2

**Additional context**

:+1:

**Comment by nickspoons** [comment]
The example snippet is perfectly highlighted if you use the [leafgarland/typescript-vim](https://github.com/leafgarland/typescript-vim/blob/master/syntax/typescript.vim) plugin. So perhaps some inspiration can come from there?

**Comment by chrisbra** [comment]
have you contacted the maintainer of the syntax file?

**Comment by aiya000** [comment]
mmm?
I don't use the plugin.

OK, thanks!

**Comment by nickspoons** [comment]
@chrisbra Bram is the maintainer of the [runtime/syntax/typescript.vim](https://github.com/vim/vim/blob/master/runtime/syntax/typescript.vim) file

**Comment by chrisbra** [comment]
ah, did not check. Sorry.

**Comment by brammool** [comment]
Nick Jensen wrote:

> The example snippet is perfectly highlighted if you use the
> [leafgarland/typescript-vim](https://github.com/leafgarland/typescript-vim/blob/master/syntax/typescript.vim)
> plugin. So perhaps some inspiration can come from there?

Unfortunately these files under leafgarland have an unclear copyright
status.  This basically means you can't use them.

The files included with Vim are from 
https://github.com/HerringtonDarkholme/yats.vim
If you see a problem (and hopefully can suggest a fix) please create an
issue there.


-- 
"A clear conscience is usually the sign of a bad memory."
                             -- Steven Wright

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
ping @HerringtonDarkholme

**Comment by aiya000** [comment]
I previously said

> I don't use the plugin.

Sorry, I wanted to say 'I didn't use the plugin.'.

Thanks for your suggestion, chrisbra :joy:

**Comment by chrisbra** [comment]
please create an issue with the upstream repository. The file seems to be maintained, so I am closing this one here.
