### ISSUE TITLE
vim v8.1.1929 bug

### ISSUE THREAD

**Issue by calibur88** [vim/vim#4866]
#one bug
can't open syntax.vim
 errorinfo:
处理 /home/xubuntu/.vimrc 时发生错误:
行   13:
E484: 无法打开文件 /home/xubuntu/vim81/syntax/syntax.vim
处理 function plug#end 时发生错误:
行   86:
E484: 无法打开文件 /home/xubuntu/vim81/syntax/syntax.vim
处理 /home/xubuntu/.vimrc 时发生错误:
行  132:
E484: 无法打开文件 /home/xubuntu/vim81/syntax/syntax.vim
请按 ENTER 或其它命令继续
if you can look know chinese

#two bug
vim with lua and perl can't two support?
I build vim with lua no perl or with perl no lua.
./configure --with-features=huge \
--enable-multibyte \
--enable-rubyinterp=yes \
--enable-python3interp=yes \
--with-python-config-dir=/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu\
--enable-perlinterp=yes \
--enable-luainterp=yes \
--enable-gui=gtk2 \
--enable-cscope \
--enable-terminal \
--prefix=/home/xubuntu/vim81

超强版本 带 GTK2 图形界面。  目前可使用(+)与不可使用(-)的模块列表:
+acl               -farsi             -mouse_sysmouse    -tag_any_white
+arabic            +file_in_path      +mouse_urxvt       -tcl
+autocmd           +find_in_path      +mouse_xterm       +termguicolors
+autochdir         +float             +multi_byte        +terminal
-autoservername    +folding           +multi_lang        +terminfo
+balloon_eval      -footer            -mzscheme          +termresponse
+balloon_eval_term +fork()            +netbeans_intg     +textobjects
+browse            +gettext           +num64             +textprop
++builtin_terms    -hangul_input      +packages          +timers
+byte_offset       +iconv             +path_extra        +title
+channel           +insert_expand     -perl              +toolbar
+cindent           +job               +persistent_undo   +user_commands
+clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           -python            +visual
+cmdline_info      +libcall           +python3           +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
+cscope            +localmap          +ruby              +wildmenu
+cursorbind        +lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con_gui    +mksession         +smartindent       +X11
+diff              +modify_fname      +sound             -xfontset
+digraphs          +mouse             +spell             +xim
+dnd               +mouseshape        +startuptime       +xpm
-ebcdic            +mouse_dec         +statusline        +xsmp_interact
+emacs_tags        -mouse_gpm         -sun_workshop      +xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          +mouse_netterm     +tag_binary        
+extra_search      +mouse_sgr         -tag_old_static  

I already install perl and lua and two environment  ,I can on terminal run lua and perl.

How can i do?
Help me!
Thank!

**Comment by calibur88** [comment]
I build vim v8.1.1850 no problem,all normal!

**Comment by k-takata** [comment]
Please provide reproducible steps using `vim --clean`.

**Comment by chrisbra** [comment]
and please post english error messages ;)

**Comment by calibur88** [comment]
> Please provide reproducible steps using vim --clean.
https://raw.githubusercontent.com/disknowsname/vimrc/master/vim编译.txt
Here are the commands I used to build vim, which is also the build process.
Sorry, I have reconstructed the 1927 version, there is a second problem in 1927, the first syntax problem is resolved properly.

**Comment by calibur88** [comment]
> Please provide reproducible steps using vim --clean.

**Comment by chrisbra** [comment]
and what problem are you actually facing? I see a build script, but no bug descriptions.

**Comment by calibur88** [comment]
> and please post english error messages ;)

Error processing /home/xubuntu/.vimrc:
Line 13:
E484: can't open the file/home/still/vim81 / syntax/syntax.vim
Error handling function plug#end:
Line 86:
E484: can't open the file/home/still/vim81 / syntax/syntax.vim
Error processing /home/xubuntu/.vimrc:
Line 132:
E484: can't open the file/home/still/vim81 / syntax/syntax.vim
Press ENTER or another command to continue

I use software translation english,this is roughly.

**Comment by chrisbra** [comment]
Could it be you have $VIMRUNTIME variable set? Try to unset the $VIMRUNTIME variable (or try with a clean session without that variable being set).

**Comment by calibur88** [comment]
Please wait while I rebuild vim 1929 and cancel the VIMRUNTIME variable to try

> Could it be you have $VIMRUNTIME variable set? Try to unset the $VIMRUNTIME variable (or try with a clean session without that variable being set).

**Comment by calibur88** [comment]
The first question is solved, thank you. The second question: does vim v1929 not support lua and perl build at the same time?I turned lua and perl support on at build time, but I built lua without support for perl, or turned off the lua option to support perl. Do lua and perl conflict?

> Could it be you have $VIMRUNTIME variable set? Try to unset the $VIMRUNTIME variable (or try with a clean session without that variable being set).
