### ISSUE TITLE
Scrolling a popup window using a popup-filter and setting 'firstline' does not work smoothly together

### ISSUE THREAD

**Issue by bfrg** [vim/vim#4876]
**Describe the bug**
When `firstline` is passed to `popup_create()`, and the popup window is scrolled using a `popup-filter`, Vim always first jumps to the first buffer line before scrolling the window. Only after hitting `<C-L>`, scrolling will start at `firstline`. This jump does not occur when the popup window is scrolled with the mouse.

**To Reproduce**
1. Run `vim --clean popup.vim -c "source %"`
```vim
" popup.vim
function! s:popup_filter(winid, key)
    if a:key ==# "\<c-k>"
        call win_execute(a:winid, "normal! \<c-y>")
        return v:true
    elseif a:key ==# "\<c-j>"
        call win_execute(a:winid, "normal! \<c-e>")
        return v:true
    elseif a:key ==# 'q' || a:key ==# 'x'
        return popup_filter_menu(a:winid, 'x')
    endif
    return v:false
endfunction

let winid = popup_create(range(50)->map('string(v:val)'), #{
        \ filter: function('s:popup_filter'),
        \ firstline: 20,
        \ close: 'button',
        \ minwidth: 60,
        \ maxwidth: 60,
        \ minheight: 10,
        \ maxheight: 10
        \ })
```
2. Press `<c-j>` or `<c-k>` to scroll the popup window down or up, respectively. Vim will first jump to the first buffer line before it scrolls the window. Pressing `<C-L>` will redraw the popup window. Now `<c-j>` and `<c-k>` will start scrolling the window from the buffer line that was set with `firstline`.
3. **Workaround:** Adding `call win_execute(winid, 'normal! zz')` to the above file will prevent the jumping (thanks to @nickspoons).

**Expected behavior**
Scrolling should start from the buffer line that was set with `firstline`, without first jumping to the first buffer line.

**Environment**
Vim version `v8.1.1939`

**Comment by brammool** [comment]
> **Describe the bug**
> When `firstline` is passed to `popup_create()`, and the popup window
> is scrolled using a `popup-filter`, Vim always first jumps to the
> first buffer line before scrolling the window. Only after hitting
> `<C-L>`, scrolling will start at `firstline`. This jump does not occur
> when the popup window is scrolled with the mouse.
> 
> **To Reproduce**
> 1. Run `vim --clean popup.vim -c "source %"`
> ```vim
> " popup.vim
> function! s:popup_filter(winid, key)
>     if a:key ==# "\<c-k>"
>         call win_execute(a:winid, "normal! \<c-y>")
>         return v:true
>     elseif a:key ==# "\<c-j>"
>         call win_execute(a:winid, "normal! \<c-e>")
>         return v:true
>     elseif a:key ==# 'q' || a:key ==# 'x'
>         return popup_filter_menu(a:winid, 'x')
>     endif
>     return v:false
> endfunction
> 
> let winid = popup_create(range(50)->map('string(v:val)'), #{
>         \ filter: function('s:popup_filter'),
>         \ firstline: 20,
>         \ close: 'button',
>         \ minwidth: 60,
>         \ maxwidth: 60,
>         \ minheight: 10,
>         \ maxheight: 10
>         \ })
> ```

Hmm, you tell Vim to put line 20 at the top of the popup, and then you
also tell it to show different lines by scrolling up or down.  Vim then
doesn't know which one to use.

> 2. Press `<c-j>` or `<c-k>` to scroll the popup window down or up,
> respectively. Vim will first jump to the first buffer line before it
> scrolls the window.

That looks like a bug.

> Pressing `<C-L>` will redraw the popup window. Now `<c-j>` and `<c-k>`
> will start scrolling the window from the buffer line that was set with
> `firstline`.

But using CTRL-L again will apply the "firstline" value.  That is
probably not what you want.  But you can't reset "firstline".  I'll make
that possible by accepting the value zero.

> 3. **Workaround:** Adding `call win_execute(winid, 'normal! zz')` to
> the above file will prevent the jumping (thanks to @nickspoons).
> 
> **Expected behavior**
> Scrolling should start from the buffer line that was set with
> `firstline`, without first jumping to the first buffer line.

I'll make a patch, please check that your problem is fixed.  But you may
want to set "firstline" to zero at some point.

-- 
hundred-and-one symptoms of being an internet addict:
139. You down your lunch in five minutes, at your desk, so you can
     spend the rest of the hour surfing the Net.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bfrg** [comment]
Thank you for the patch. CTRL-J and CTRL-K work now as intended.

I wrote a small ftplugin for the quickfix window that previews the current quickfix error in a popup window. `firstline` is set to something like `getqflist()[line('.')-1].lnum`, so that the line with the quickfix error is at the top of the window.

Having CTRL-L re-apply `firstline` is actually useful. After scrolling up or down, I can jump back to the quickfix error in the popup window at any time with CTRL-L.

Here's a screenshot:
![screenshot-2019-08-30_180725](https://user-images.githubusercontent.com/6266600/64035430-0e0c7e00-cb51-11e9-89eb-1a2e442f1916.png)
