### ISSUE TITLE
TCL indentation adds tab space when conditions in if statements span multiple lines.

### ISSUE THREAD

**Issue by surmish** [vim/vim#4880]
I am working on tcl files which are 5000+ lines long with hundreds of procedures. I wish to use an automated script to indent the TCL code. However I found this minor issue which prevents me from visually selecting the whole file and using the `=` command to indent it in VIM (latest version)

This is the sample code:

```tcl
if { ![string equal "abc" "def"]
  && [ expr 1 + 1]} {
    puts "here1"
  }  
```

If you notice the `if` condition, it is split into 2 lines which results in an incorrect indentation of the brace on the 4th line.  Due to this, the next line begins below the end of the brace above.
Joining the conditions into 1 line fixes the indentation as shown below:

```tcl
if { ![string equal "abc" "def"] && [ expr 1 + 1]} {                                                                                  
  puts "here1"
}
```

However, there are if conditions in the code which span 5-10 lines, which I can't combine into a single line for readability purposes. I hope this is worth looking into and fixable.

This is my vim compilation ( Vim (latest) compiled with tcl (8.6) support ):

```
prompt:> vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 31 2019 13:55:05)
Included patches: 1-1782
Compiled by urmish
Huge version with X11-Motif GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_any_white
-arabic            +file_in_path      +mouse_urxvt       +tcl
+autocmd           +find_in_path      +mouse_xterm       +termguicolors
+autochdir         +float             +multi_byte        +terminal
-autoservername    +folding           +multi_lang        +terminfo
+balloon_eval      -footer            -mzscheme          +termresponse
+balloon_eval_term +fork()            +netbeans_intg     +textobjects
+browse            +gettext           +num64             +textprop
++builtin_terms    -hangul_input      +packages          +timers
+byte_offset       +iconv             +path_extra        +title
+channel           +insert_expand     +perl              +toolbar
+cindent           +job               +persistent_undo   +user_commands
+clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           -python            +visual
+cmdline_info      +libcall           +python3/dyn       +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          -rightleft         +wildignore
+cscope            +localmap          -ruby              +wildmenu
+cursorbind        +lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con_gui    +mksession         +smartindent       +X11
+diff              +modify_fname      -sound             +xfontset
+digraphs          +mouse             +spell             -xim
-dnd               +mouseshape        +startuptime       +xpm
-ebcdic            +mouse_dec         +statusline        -xsmp
+emacs_tags        +mouse_gpm         -sun_workshop      +xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          +mouse_netterm     +tag_binary        
+extra_search      +mouse_sgr         -tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MOTIF -DFUNCPROTO=15 -DNARROWPROTO    -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -Wl,-E   -L/usr/local/lib -Wl,--as-needed -o vim  -lXp -lXmu -lXext -lXm -lXt -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE -ldl  -lm -ltinfo -lelf -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/local/lib -llua -Wl,-E  -fstack-protector -L/usr/local/lib -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc  -ltcl8.6 -ldl -lz -lpthread -lm     
```

**Comment by chrisbra** [comment]
it is a problem with the runtime [indent script](https://github.com/vim/vim/blob/master/runtime/indent/tcl.vim) for tcl. Please contact the maintainer first.

**Comment by surmish** [comment]
@Heithoff @now Any ideas?

**Comment by Heithoff** [comment]
I'm looking at it now!

**Comment by Heithoff** [comment]
Your problem occurred because the script only started counting closing braces after the first opening brace.   I changed it so any line after a line containing the same number of opening and closing braces will keep the same indentation as the previous line.  

```
diff --git a/runtime/indent/tcl.vim b/runtime/indent/tcl.vim
index d77081841..2fba8e016 100644
--- a/runtime/indent/tcl.vim
+++ b/runtime/indent/tcl.vim
@@ -1,8 +1,7 @@
 " Vim indent file
 " Language:            Tcl
-" Previous Maintainer:     Nikolai Weibull <now@bitwi.se>
 " Latest Update:       Chris Heithoff <chrisheithoff@gmail.com>
-" Latest Revision:         2018-12-05
+" Latest Revision:  2019-09-05

 if exists("b:did_indent")
   finish
@@ -38,27 +37,30 @@ function s:ends_with_backslash(lnum)
   endif
 endfunction

-function s:count_braces(lnum, count_open)
+function s:count_braces(lnum)
   let n_open = 0
   let n_close = 0
   let line = getline(a:lnum)
   let pattern = '[{}]'
+
+  " Iterate over each occurrence of an open or closed curly brace in the given line.
+  "   - Only consider braces which are not in a tclComment or tclString syntax region.
   let i = match(line, pattern)
   while i != -1
     if synIDattr(synID(a:lnum, i + 1, 0), 'name') !~ 'tcl\%(Comment\|String\)'
       if line[i] == '{'
         let n_open += 1
       elseif line[i] == '}'
-        if n_open > 0
-          let n_open -= 1
-        else
-          let n_close += 1
-        endif
+        let n_close += 1
       endif
     endif
+    " Jump to the next match position.
     let i = match(line, pattern, i + 1)
   endwhile
-  return a:count_open ? n_open : n_close
+
+  " Return the number of unmatched open braces.
+  return (n_open > n_close) ? (n_open - n_close) : 0
+
 endfunction

 function GetTclIndent()
@@ -77,7 +79,7 @@ function GetTclIndent()
   let ind = indent(pnum)

   " ...but if previous line introduces an open brace, then increase current line's indentation
-  if s:count_braces(pnum, 1) > 0
+  if s:count_braces(pnum) > 0
     let ind += shiftwidth()
   else
     " Look for backslash line continuation on the previous two lines.
```

**Comment by brammool** [comment]
Chris Heithoff wrote:

> Your problem occurred because the script only started counting closing
> braces after the first opening brace.   I changed it so any line after
> a line containing the same number of opening and closing braces will
> keep the same indentation as the previous line.  

Thanks, I'll include the fix.  But keep the "previous maintainer"
header, I like to keep a bit of history.

-- 
hundred-and-one symptoms of being an internet addict:
192. Your boss asks you to "go fer" coffee and you come up with 235 FTP sites.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Heithoff** [comment]
Sounds good.

**Comment by surmish** [comment]
@Heithoff Thank you!

**Comment by chrisbra** [comment]
closing then.

**Comment by surmish** [comment]
@Heithoff Sorry to reopen this, I manually patched my tcl.vim and compiled it. The code change results in another issue:

```tcl
if { ![string equal "abc" "def"]
  && [ expr 1 + 1]} {
  puts "here1"
} else {
puts "there"
}
```

The else section is not indented as intended. @chrisbra is it worth reopening this?

**Comment by Heithoff** [comment]
Oh no, you're right.   My attempt to fix your problem broke the much more common case.

 @brammool, please revert runtime/indent.vim to the previous version to undo my change.

The good news is that I'm improving the tcl.in and tcl.ok test files so I don't mess this up again

```
diff --git a/runtime/indent/testdir/tcl.in b/runtime/indent/testdir/tcl.in
index c769d5bf5..97a70ec25 100644
--- a/runtime/indent/testdir/tcl.in
+++ b/runtime/indent/testdir/tcl.in
@@ -11,9 +11,15 @@ puts $i
 }
 }

+if {$condition1} {
+puts "True"
+} else {
+puts "False"
+}
+
 command_with_a_long_time -arg1 "First" \
 -arg2 "Second" \
 -arg3 "Third"

 puts "Move indent back after line continuation is complete"
-# END_INDENT
\ No newline at end of file
+# END_INDENT
```


```
diff --git a/runtime/indent/testdir/tcl.ok b/runtime/indent/testdir/tcl.ok
index 77f24e904..1a2fc4a9c 100644
--- a/runtime/indent/testdir/tcl.ok
+++ b/runtime/indent/testdir/tcl.ok
@@ -11,6 +11,12 @@ proc abc {} {
     }
 }

+if {$condition1} {
+    puts "True"
+} else {
+    puts "False"
+}
+
 command_with_a_long_time -arg1 "First" \
     -arg2 "Second" \
     -arg3 "Third"
```

**Comment by Heithoff** [comment]
@surmish  I asked Bram to revert my change. 
 I can't think of a simple solution right now.   I'm not sure how many long multi-line if statement you have in the code, but I would suggest first running the gg=G on the entire file, then scroll through the file until you find the first line which is too far indented and then move that line to the left by a shiftwide (<<) and then re-indent from that line to the bottom with =G.   Continue until the entire file is correct.

**Comment by brammool** [comment]
Chris Heithoff wrote:

> Oh no, you're right.   My attempt to fix your problem broke the much
> more common case.
> 
>  @brammool, please revert runtime/indent.vim to the previous version
>  to undo my change.

OK, I'll do that.

> The good news is that I'm improving the tcl.in and tcl.ok test files
> so I don't mess this up again

-- 
Your mouse has moved.  Windows must be restarted for the change
to take effect.  Reboot now?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
