### ISSUE TITLE
sh.vim: doesn't recognize subshell function definitions

### ISSUE THREAD

**Issue by bmundt6** [vim/vim#4897]
The `sh.vim` syntax fails to recognize functions defined in a bash subshell, e.g:
![image](https://user-images.githubusercontent.com/11874063/64378938-d93e7200-cffb-11e9-91ad-f48e020dd8eb.png)

 - Vim version: 7.4
 - OS: macOS 10.14
 - Terminal: GNOME Terminal

**Comment by chrisbra** [comment]
please first try with an updated vim (including updated vim runtime files)

**Comment by bmundt6** [comment]
Just tested it with a fresh build from master (v8.1.1996), the behavior is the same.
I should note as well that the `sh.vim` syntax file from 7.4 correctly parses the subshell region as a subshell code block, while the 8.1 file (which I had previously copied over into my local config) parses the subshell region as an arithmetic statement. Neither of the syntax files recognizes the function between the parens.

**Comment by lacygoill** [comment]
Fixed by https://github.com/vim/vim/commit/1d9215b9aaa120b9d78fee49488556f73007ce78.

Note: you may need to set `g:is_bash` to 1 if Vim does not detect that the current file is a bash script (either via its name or its contents, typically the shebang line).

**Comment by cecamp** [comment]
I believe you need to update your syntax/sh.vim .  It was last updated on Apr 14, btw.
