### ISSUE TITLE
File listing gets corrupted when changing sort with `sizestyle = 'H'`

### ISSUE THREAD

**Issue by sharat87** [vim/vim#4899]
**Describe the bug**
The netrw file listing gets corrupted when cycling sort order with the `s` key, in the long listing and with `let g:netrw_sizestyle = 'H'` for human-readable file sizes.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `gvim` with no custom vimrc or vimfiles. Don't use `--clean` so that Netrw is loaded.
2. Run command `let g:netrw_sizestyle = 'H'`
3. Open a directory with a few files.
4. Hit `i` once to change to long listing style. Notice the human readable file sizes.
5. Hit the `s` key a few times to cycle the sorting order (current sorting order can be seen in the banner). After hitting `s` for 2-3 times, the file listing gets corrupted and it's no longer usable.

**Expected behavior**
The sorting order should change without corrupting the file listing.

**Screenshots**
[GIF demonstrating issue](https://gph.is/g/4owANpe).

**Environment (please complete the following information):**
- Vim version 8.1.1931
- Netrw version: v165
- OS: Windows 7
- GVIM

**Comment by chrisbra** [comment]
fixed by 8750e3cf81f12132e7b4141501feba586b1ae11d
