### ISSUE TITLE
completepopup highlight option has no effect

### ISSUE THREAD

**Issue by myitcv** [vim/vim#4907]
**Describe the bug**

When `completeopt` includes `popup` and there is `info` to display:

* the default highlight group appears to be `PmenuSel` as opposed to the documented `Pmenu`
* setting an alternative highlight group via `completepopup` has no effect

**To Reproduce**

Create `repro.vim`:

```vim
" repro.vim

set nocp
set noswapfile
set completeopt=menu,longest,popup
set completepopup=align:menu,border:off
set bs=2

let opts = {"in_mode": "json", "out_mode": "json", "err_mode": "json", "timeout": 30000}
let job = job_start("go run slow_job.go", opts)
let s:channel = job_getchannel(job)
call ch_logfile("/tmp/vim_channel.log", "a")

function DoComplete(findstart, base)
  if a:findstart == 1
    call ch_evalexpr(s:channel, {'Comment':'Complete findstart', 'Delay': '100ms', 'Calls':[['redraw', '']]})
    return 0
  else
    call ch_evalexpr(s:channel, {'Comment':'Complete base', 'Delay': '100ms'})
    if a:base == "mai"
      return [{"abbr":"main()","word":"main","info":""}]
    elseif a:base == "ma"
      return [{"abbr":"main()","word":"main","info":"Hello"},{"abbr":"make(t Type, size ...int)","word":"make","info":"World"}]
    endif
  endif
endfunction

function EchoChanges(bufnr, start, end, added, changes)
  call ch_evalexpr(s:channel, {'Comment':'listener_add callback', 'Delay': '10ms'})
  redir >> /tmp/listener.log | echom a:changes | redir END
endfunction

set omnifunc=DoComplete
call listener_add("EchoChanges")
```

Then open Vim via:

```
vi -u repro.vim
```

Then attempt completion on:

```
ma
```

Then use `<C-n>` to select an item in the list of completion candidates.

**Expected behavior**

The info popup to be coloured the same as the completion candidates popup.

**Screenshots**

![Screen Shot 2019-09-07 at 20 26 47](https://user-images.githubusercontent.com/3374574/64479360-f9159780-d1ad-11e9-822b-26eb80f94370.png)

**Environment (please complete the following information):**
 - Vim version

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep  3 2019 11:32:52)
Included patches: 1-1967
Compiled by myitcv@myitcv
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_any_white
+arabic            +file_in_path      +mouse_urxvt       -tcl
+autocmd           +find_in_path      +mouse_xterm       +termguicolors
+autochdir         +float             +multi_byte        +terminal
-autoservername    +folding           +multi_lang        +terminfo
+balloon_eval      -footer            -mzscheme          +termresponse
+balloon_eval_term +fork()            -netbeans_intg     +textobjects
+browse            +gettext           +num64             +textprop
++builtin_terms    -hangul_input      +packages          +timers
+byte_offset       +iconv             +path_extra        +title
+channel           +insert_expand     -perl              +toolbar
+cindent           +job               +persistent_undo   +user_commands
+clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           +python            +visual
+cmdline_info      +libcall           -python3           +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
+cscope            +localmap          -ruby              +wildmenu
+cursorbind        +lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con_gui    +mksession         +smartindent       +X11
+diff              +modify_fname      -sound             -xfontset
+digraphs          +mouse             +spell             +xim
+dnd               +mouseshape        +startuptime       +xpm
-ebcdic            +mouse_dec         +statusline        +xsmp_interact
+emacs_tags        -mouse_gpm         -sun_workshop      +xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          +mouse_netterm     +tag_binary        
+extra_search      +mouse_sgr         -tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/home/myitcv/usr/vim/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16   -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl   -ldl  -L/usr/lib/x86_64-linux-gnu -lluajit-5.1  -L/home/myitcv/.pythons/2.7.15/lib/python2.7/config -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic       
```

- OS: Ubuntu 19.04
- Terminal: XTerm(330)

**Additional context**

**Comment by brammool** [comment]
> **Describe the bug**
> 
> When `completeopt` includes `popup` and there is `info` to display:
> 
> * the default highlight group appears to be `PmenuSel` as opposed to
> the documented `Pmenu`

That is right, the documentation wasn't updated.

> * setting an alternative highlight group via `completepopup` has no effect

It works for me, using an example from the test.

> **To Reproduce**
> 
> Create `repro.vim`:

This doesn't work because it requires go and slow_job.go.

I tried using CTRL-X CTRL-U, does it make a difference when using
'omnifunc'?

Try this:


call popup_clear()

set completeopt+=preview,popup
set completefunc=CompleteFuncDict
hi InfoPopup ctermbg=yellow

func CompleteFuncDict(findstart, base)
  if a:findstart
    if col('.') > 10
      return col('.') - 10
    endif
    return 0
  endif

  return {
	\ 'words': [
	\ {
	\ 'word': 'aword',
	\ 'abbr': 'wrd',
	\ 'menu': 'extra text',
	\ 'info': 'words are cool',
	\ 'kind': 'W',
	\ 'user_data': 'test'
	\ },
	\ {
	\ 'word': 'anotherword',
	\ 'abbr': 'anotwrd',
	\ 'menu': 'extra text',
	\ 'info': "other words are\ncooler than this and some more text\nto make wrap",
	\ 'kind': 'W',
	\ 'user_data': 'notest'
	\ },
	\ {
	\ 'word': 'noinfo',
	\ 'abbr': 'noawrd',
	\ 'menu': 'extra text',
	\ 'info': "lets\nshow\na\nscrollbar\nhere",
	\ 'kind': 'W',
	\ 'user_data': 'notest'
	\ },
	\ {
	\ 'word': 'thatword',
	\ 'abbr': 'thatwrd',
	\ 'menu': 'extra text',
	\ 'info': 'that word is cool',
	\ 'kind': 'W',
	\ 'user_data': 'notest'
	\ },
	\ ]
	\ }
endfunc
" call setline(1, 'text text text text text text text ')
func ChangeColor()
  let id = popup_findinfo()
  eval id->popup_setoptions(#{highlight: 'InfoPopup'})
endfunc
set completepopup=height:4,highlight:InfoPopup

-- 
hundred-and-one symptoms of being an internet addict:
216. Your pet rock leaves home.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by myitcv** [comment]
> This doesn't work because it requires go and slow_job.go.

Apologies on two fronts:

* the repro was not standalone
* more importantly I've no idea what/why it didn't work for me before, because now it's working exactly as documented:

```vim
" repro.vim

set nocp
set noswapfile
set completeopt=menu,longest,popup
set completepopup=align:menu,border:off,highlight:Pmenu
set bs=2

function DoComplete(findstart, base)
  if a:findstart == 1
    return 0
  else
    if a:base == "mai"
      return [{"abbr":"main()","word":"main","info":""}]
    elseif a:base == "ma"
      return [{"abbr":"main()","word":"main","info":"Hello"},{"abbr":"make(t Type, size ...int)","word":"make","info":"World"}]
    endif
  endif
endfunction

set omnifunc=DoComplete
```

![Screen Shot 2019-09-08 at 16 39 46](https://user-images.githubusercontent.com/3374574/64490674-5580c180-d257-11e9-8275-d2921f2882a2.png)

Thanks for taking the time to reply in any case. I'll close this because there's no issue here.
