### ISSUE TITLE
:Man {number} {name} behavior is different from the SHELL's man

### ISSUE THREAD

**Issue by antoinemadec** [vim/vim#4919]
**Is your feature request related something that is currently hard to do? Please describe.**
The following command runs ```man 3 size``` and then runs ```man size```:
```vim
:Man 3 size
```
Whereas in a Shell, ```man 3 size``` would not try to run ```man size``` and would just return: 

> No manual entry for size in section 3

**Describe the solution you'd like**
I would like ```:Man {number} {name}``` to behave like ```man {number} {name}``` by not running ```man {name}``` if no page is found.
It is confusing to have GNU man pages when explicitly asking for C/C++ man pages.

**Additional context**
Minimal vimrc to reproduce:
```vim
set nocompatible
runtime! ftplugin/man.vim 
```

The code responsible for this behavior is in **ftplugin/man.vim**:
```vim
func <SID>GetPage(cmdmods, ...)
  " [...]
  if sect != "" && s:FindPage(sect, page) == 0
    let sect = ""
  endif
  if s:FindPage(sect, page) == 0
    echo "\nCannot find a '".page."'."
    return
  endif
```

Thanks :smiley: 
Antoine

**Comment by chrisbra** [comment]
please contact the runtime file maintainer first.

**Comment by antoinemadec** [comment]
No problem, I just sent an email to SungHyun Nam.

**Comment by goweol** [comment]
It is burdensome to suddenly change the basic behavior that has been used for a long time.
How about adding a new option such as 'g:ft_man_no_sect_fallback'?
If you set this option to non-zero value, man plugin works as you expected.
```
diff --git a/runtime/ftplugin/man.vim b/runtime/ftplugin/man.vim
index 4591c478d..3fb2d5521 100644
--- a/runtime/ftplugin/man.vim
+++ b/runtime/ftplugin/man.vim
@@ -132,11 +132,17 @@ func <SID>GetPage(cmdmods, ...)
     let page = expand('<cword>')
   endif
 
-  if sect != "" && s:FindPage(sect, page) == 0
-    let sect = ""
+  if !exists('g:ft_man_no_sect_fallback') || (g:ft_man_no_sect_fallback == 0)
+    if sect != "" && s:FindPage(sect, page) == 0
+      let sect = ""
+    endif
   endif
   if s:FindPage(sect, page) == 0
-    echo "\nCannot find a '".page."'."
+    let msg = "\nNo manual entry for ".page
+    if sect != ""
+      let msg .= " in section ".sect
+    endif
+    echo msg
     return
   endif
   exec "let s:man_tag_buf_".s:man_tag_depth." = ".bufnr("%")
```

**Comment by antoinemadec** [comment]
@goweol , I understand that this is your call, and that changing default behavior has repercutions.
However, I'm strongly in favor of having no fallback by default and only do it with an option like **g:ft_man_sect_fallback**

The reason is that I struggle finding a case in which a user would explicitly pass a man page number and expect it to fallback to another man page.

What do you think?

**Comment by goweol** [comment]
I personally agree with you. But I don't think it's good to change the default behaviour that have been around for years.

**Comment by antoinemadec** [comment]
@chrisbra @goweol , got it, what should be the next step?
Is @goweol patch enough or should someone push a PR?

**Comment by chrisbra** [comment]
I think this has been included as of https://github.com/vim/vim/commit/5be4ceecea5520265066eac972460ebb1cdf05e7, so closing.
