### ISSUE TITLE
Allow customization of completeopt+=popup's info field

### ISSUE THREAD

**Issue by thomasfaingnaert** [vim/vim#4924]
**Is your feature request related something that is currently hard to do? Please describe.**
Using `set completeopt+=popup`, we can show extra information of the currently selected completion item, but this has two problems:

1. It uses the `info` field of the completed item, which can only be a string. On the other hand, a popup can also open a buffer with syntax highlighting etc.
2. In some cases, it is expensive to populate the `info` field for all completion items. For example, in the language server protocol, some language servers don't return the documentation when asking for completion results. You have to explicitly ask for the documentation of the currently selected item.

**Describe the solution you'd like**
It would be nice if plugins can hook into the process of setting the content of popups created by `completeopt+=popup`. For example, one could have a function that takes as input the currently selected completion item, and returns either a string/buffer number that is passed to `popup_create` by Vim itself. This would allow using more than plaintext, and populate the `info` using custom logic.
If the function is not set, the default will be to return the completion item's `info` field.

**Describe alternatives you've considered**
This can also be done by using `CompleteDone` and creating the popup yourself. However, this has two disadvantages:

1. Sizing, positioning, closing, etc. must be handled in each plugin separately. It would be better if Vim handled this.
2. The settings from `'completepopup'` will not apply if the plugin calls `popup_create` itself. Most notably, `set completepopup=align:item` seems to be the hardest to replicate.

**Comment by brammool** [comment]
I suppose what would work is to provide a callback that is invoked just after the popup window has been created  and positioned.  You could set the info to "Loading..." or just "..." and fill it with the callback.

**Comment by thomasfaingnaert** [comment]
That would be great. One thing to keep in mind is that the popup window should only be displayed after the text has been filled in; otherwise, there will be noticeable flickering when scrolling through the completion menu.

**Comment by thomasfaingnaert** [comment]
Managed to get it working pretty well by using `CompleteChanged`, getting the popup id with `popup_findinfo()`, and then setting the content with `setbufline()`. However, there are some caveats:

1. I need to explicitly make the buffer modifiable with `setbufvar(winbufnr(...), '&modifiable', 1)`. Not a big deal, but `modifiable` is probably set for a good reason. Changing the info popup content after displaying it is probably not well supported, and might lead to problems in some cases?
2. It seems that changing the info buffer's content makes the buffer listed again. Manually `setbufvar(winbufnr(...), '&buflisted', 0)` fixes this, but it feels like a bit of a hack. There's probably other settings that are reset when changing the content, not sure why though.
3. `completepopup`'s `width` property doesn't work: Vim ignores the maximum width if you change the content after it has been displayed.
4. Using `CompleteChanged` seems to work, but I'm not sure if the popup is guaranteed to be created and position at that point?
5. Even if you change the popup content immediately on `CompleteChanged`, you will very briefly see the old content appear, leading to some distracting flickering. (Not really important; purely a cosmetic issue.)

Perhaps it would be simpler to provide a Vimscript function `complete_set_popup(completion_item, popup buffer/lines)` that can be called by a plugin to set the popup for a completion item whenever it has the result available (which would solve point 2 of the feature request). The second parameter can be any argument that is valid for `popup_create`, including buffers and strings (this would solve point 1).
