### ISSUE TITLE
expand() slower when a quote is added

### ISSUE THREAD

**Issue by whonore** [vim/vim#4926]
**Describe the bug**
`expand("a'")` is noticeably slower than `expand("a")`. This does not appear to be the case for `expand('a')` vs `expand('a"')`.

**To Reproduce**
Compare
`let s = localtime() | echo expand("a") | echo localtime() - s`
to
`let s = localtime() | echo expand("a'") | echo localtime() - s`

**Expected Behavior**
They take the same amount of time.

**Environment (please complete the following information):**
 - Vim: 8.1.1670, also tested with 8.0.1850, 7.4.2367
 - OS: Ubuntu 18.04
 - Terminal: GNOME Terminal

**Comment by brammool** [comment]
It always shows zero for me.   Not sure why it's different for you.

**Comment by whonore** [comment]
Interesting. I just tried compiling master and running it with `vim --clean` and I still see a slowdown with the quote. Testing on another machine though I don't see a difference. So I guess there's something else about my setup causing it.

I'm fine if you decide to close this. It seems it may be peculiar to my configuration and it's not actually a problem for me, I just discovered it by accident when a script was calling `expand` unnecessarily.

**Comment by whonore** [comment]
This is the output I get from running both commands using the locally compiled master branch. I'm not sure what the shell command in the second case is for but I guess that could be the problem.
```
./vim -V --clean --cmd 'let s = localtime() | echo expand("a") | echo localtime() - s'
a
0
chdir(/usr/local/share/vim)
fchdir() to previous dir
could not source "$VIMRUNTIME/defaults.vim"
Opening the X display took 0 msecOpening the X display took 1 msec
Press ENTER or type command to continue
```
```
./vim -V --clean --cmd 'let s = localtime() | echo expand("a\'") | echo localtime() - s'
Calling shell to execute: "set nonomatch; vimglob() { while [ $# -ge 1 ]; do echo "$1"; shift; done }; vimglob >/tmp/vQphk6j/0 a\'"

a'
1
chdir(/usr/local/share/vim)
fchdir() to previous dir
could not source "$VIMRUNTIME/defaults.vim"
Opening the X display took 0 msecOpening the X display took 1 msec
Press ENTER or type command to continue
```

**Comment by chrisbra** [comment]
> Calling shell to execute: "set nonomatch; vimglob() { while [ $# -ge 1 ]; do echo "$1"; shift; done }; vimglob >/tmp/vQphk6j/0 a\'"

So it is calling a shell to expand the wildcard and uses the `vimglob()` function. Whether or not it uses the `vimglob` function depends on the shell setting. So check those between your instances.

**Comment by whonore** [comment]
Ah, the delay is due to some slightly slow things in my shell startup config. I'm still not sure why adding the `'` requires a call to the shell but otherwise problem solved. Thank you all for your help.

**Comment by brammool** [comment]
Sound like a configuration problem, not a Vim problem, thus closing.
