### ISSUE TITLE
Fold deleted if whichwrap+=,l set

### ISSUE THREAD

**Issue by avalonv** [vim/vim#4927]
**Describe the bug**
Fold is deleted if `whichwrap+=,l` is set and you `x` in an empty line above it

**To Reproduce**
`vim --clean`
`:set whichwrap+=,l foldmethod=marker`
Create a fold using markers and close it
Create an empty line above the fold - `O`
`x` or `<del>` on empty line
The entire fold plus the empty line are deleted

**Expected behavior**
The fold isn't deleted, the cursor is placed on the first column of the line containing the closed fold

**Environment (please complete the following information):**
 - Vim version: Vi IMproved 8.1
 - OS: Void Linux
 - Terminal: kitty

**Comment by chrisbra** [comment]
Yeah, internally, `x` is translated to `dl`, which moves to the next line and deletes it. I think this patch fixes it. Theoretically, this could also happen with `X` and `:set whichwrap=h` on an empty line after a fold, but Vim doesn't delete the fold in this case, so we do not need to take care of this.

```patch
diff --git a/src/normal.c b/src/normal.c
index 2422de585..fbb3cb911 100644
--- a/src/normal.c
+++ b/src/normal.c
@@ -7399,8 +7399,8 @@ nv_optrans(cmdarg_T *cap)

     if (!checkclearopq(cap->oap))
     {
-       /* In Vi "2D" doesn't delete the next line.  Can't translate it
-        * either, because "2." should also not use the count. */
+       // In Vi "2D" doesn't delete the next line.  Can't translate it
+       // either, because "2." should also not use the count.
        if (cap->cmdchar == 'D' && vim_strchr(p_cpo, CPO_HASH) != NULL)
        {
            cap->oap->start = curwin->w_cursor;
@@ -7414,7 +7414,9 @@ nv_optrans(cmdarg_T *cap)
            ResetRedobuff();
            AppendCharToRedobuff('D');
        }
-       else
+       // if on an empty line and using 'x' and "l" is included in the whichwrap option,
+       // do not delete the next line
+       else if (!(cap->cmdchar == 'x' && vim_strchr(p_ww, 'l') != NULL && gchar_cursor() == NUL))
        {
            if (cap->count0)
                stuffnumReadbuff(cap->count0);
diff --git a/src/testdir/test_fold.vim b/src/testdir/test_fold.vim
index 7aef51f8b..90a6c2701 100644
--- a/src/testdir/test_fold.vim
+++ b/src/testdir/test_fold.vim
@@ -757,3 +757,14 @@ func Test_fold_delete_with_marker()
   bwipe!
   bwipe!
 endfunc
+
+func Test_fold_delete_with_marker_and_whichwrap()
+  new
+  let content=['', 'folded line 1 "{{{1', '  test', '  test2', '  test3', '', 'folded line 2 "{{{1', '  test', '  test2', '  test3']
+  call setline(1, content)
+  set fdm=marker ww+=l
+  normal! x
+  call assert_equal(content, getline(1, '$'))
+  set fdm& ww&
+  bwipe!
+endfunc
```

**Comment by brammool** [comment]
Christian wrote:

> Yeah, internally, `x` is translated to `dl`, which moves to the next
> line and deletes it. I think this patch fixes it. Theoretically, this
> could also happen with `X` and `:set whichwrap=h` on an empty line
> after a fold, but Vim doesn't delete the fold in this case, so we do
> not need to take care of this.
> 
> ```patch
> diff --git a/src/normal.c b/src/normal.c
> index 2422de585..fbb3cb911 100644
> --- a/src/normal.c
> +++ b/src/normal.c
> @@ -7399,8 +7399,8 @@ nv_optrans(cmdarg_T *cap)
> 
>      if (!checkclearopq(cap->oap))
>      {
> -       /* In Vi "2D" doesn't delete the next line.  Can't translate it
> -        * either, because "2." should also not use the count. */
> +       // In Vi "2D" doesn't delete the next line.  Can't translate it
> +       // either, because "2." should also not use the count.
>         if (cap->cmdchar == 'D' && vim_strchr(p_cpo, CPO_HASH) != NULL)
>         {
>             cap->oap->start = curwin->w_cursor;
> @@ -7414,7 +7414,9 @@ nv_optrans(cmdarg_T *cap)
>             ResetRedobuff();
>             AppendCharToRedobuff('D');
>         }
> -       else
> +       // if on an empty line and using 'x' and "l" is included in the whichwrap option,
> +       // do not delete the next line
> +       else if (!(cap->cmdchar == 'x' && vim_strchr(p_ww, 'l') != NULL && gchar_cursor() == NUL))
>         {
>             if (cap->count0)
>                 stuffnumReadbuff(cap->count0);
> diff --git a/src/testdir/test_fold.vim b/src/testdir/test_fold.vim
> index 7aef51f8b..90a6c2701 100644
> --- a/src/testdir/test_fold.vim
> +++ b/src/testdir/test_fold.vim
> @@ -757,3 +757,14 @@ func Test_fold_delete_with_marker()
>    bwipe!
>    bwipe!
>  endfunc
> +
> +func Test_fold_delete_with_marker_and_whichwrap()
> +  new
> +  let content=['', 'folded line 1 "{{{1', '  test', '  test2', '  test3', '', 'folded line 2 "{{{1', '  test', '  test2', '  test3']
> +  call setline(1, content)
> +  set fdm=marker ww+=l
> +  normal! x
> +  call assert_equal(content, getline(1, '$'))
> +  set fdm& ww&
> +  bwipe!
> +endfunc
> ```

Thanks.  But the line should still be deleted, thus in this case the
translated operation is "dd".

-- 
Facepalm statement #1: "I'm going to New York tomorrow, hopefully I have time
to visit the White House"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
