### ISSUE TITLE
Vim crash editing help filetypes with vim-airline errors

### ISSUE THREAD

**Issue by electro7** [vim/vim#4930]
**Describe the bug**

Editing a simple help vim file (help filetype) with vim-airline, after 3 o 4 saves with ":w", some errors are printed in vim output, and in the next save, vim crash.

Errors  are:

```
Error in function <SNR>50_airline_refresh[10]..airline#load_theme[16]..airline#update_statusline[14]..<SNR>79_invoke_funcrefs[2]..airline#util#exec_funcrefs[2]..airline#extensions#default#apply17..<SNR>100_build_sections[5]..<SNR>100_add_section:
Line 1
E121: Variable undefined: v:version
Line 8
E121: Variable undefined: condition
```

I test without plugins and clean config and don't happens. With this simple config it crash:

```
set runtimepath+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'bling/vim-airline'                  
call vundle#end()
filetype on
syntax on
let g:airline_powerline_fonts = 0
let g:airline_powerline_ascii = 1

```
I test in archlinux, debian buster 10.1 and gvim in win10. In all, vim crash with core output. In windows, with general protection error.

**To Reproduce**
1. Run vim with vim-airline plugin and edit a help filetype.
2. Edit a few lines and save it 4-5 times.
3. Vim output some error (above) and then crash with "vim: Caught deadly signal SEGV"

**Screenshots**

![Output screenshot](https://i.imgur.com/DpR9Vv0.png)

**Environment (please complete the following information):**
 - Vim version:
> :version
> VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep  3 2019 19:23:34)
> Parches incluidos: 1-1968
> Compilado por Arch Linux
> Versión "enorme" sin interfaz gráfica (GUI).  Aspectos incluidos (+) o no (-):
> +acl               +byte_offset       +conceal           -ebcdic            +folding           +keymap            +menu              +mouse_sgr         +packages          +quickfix          +startuptime       +terminal          +vartabs           +windows
> +arabic            +channel           +cryptv            +emacs_tags        -footer            +lambda            +mksession         -mouse_sysmouse    +path_extra        +reltime           +statusline        +terminfo          +vertsplit         +writebackup
> +autocmd           +cindent           +cscope            +eval              +fork()            +langmap           +modify_fname      +mouse_urxvt       +perl/dyn          +rightleft         -sun_workshop      +termresponse      +virtualedit       -X11
> +autochdir         -clientserver      +cursorbind        +ex_extra          +gettext           +libcall           +mouse             +mouse_xterm       +persistent_undo   +ruby/dyn          +syntax            +textobjects       +visual            -xfontset
> -autoservername    -clipboard         +cursorshape       +extra_search      -hangul_input      +linebreak         -mouseshape        +multi_byte        +postscript        +scrollbind        +tag_binary        +textprop          +visualextra       -xim
> -balloon_eval      +cmdline_compl     +dialog_con        -farsi             +iconv             +lispindent        +mouse_dec         +multi_lang        +printer           +signs             -tag_old_static    +timers            +viminfo           -xpm
> +balloon_eval_term +cmdline_hist      +diff              +file_in_path      +insert_expand     +listcmds          +mouse_gpm         -mzscheme          +profile           +smartindent       -tag_any_white     +title             +vreplace          -xsmp
> -browse            +cmdline_info      +digraphs          +find_in_path      +job               +localmap          -mouse_jsbterm     +netbeans_intg     +python/dyn        -sound             +tcl/dyn           -toolbar           +wildignore        -xterm_clipboard
> ++builtin_terms    +comments          -dnd               +float             +jumplist          +lua/dyn           +mouse_netterm     +num64             +python3/dyn       +spell             +termguicolors     +user_commands     +wildmenu          -xterm_save
>      archivo "vimrc" del sistema: "/etc/vimrc"
>      archivo "vimrc" del usuario: "$HOME/.vimrc"
>   2º archivo "vimrc" del usuario: "~/.vim/vimrc"
>       archivo "exrc" del usuario: "$HOME/.exrc"
>        defaults file: "$VIMRUNTIME/defaults.vim"
>             predefinido para $VIM: "/usr/share/vim"
> Compilación: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
> Enlazado: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.30/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim
>   -lm -ltinfo -lelf -lnsl    -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.30/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/5.30/core_perl/CORE -lperl -lpthread -ldl -lm -lcrypt -l
> util -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm
> 

 - OS: I test in archlinux, debian buster 10.1 and gvim 8.1 in win10. In all, vim crash.
 - Terminal: GUI, console, urxvt-unicode-256color.

**Additional context**

My dotfiles : [https://github.com/electro7/dot_arch](https://github.com/electro7/dot_arch)
One help file to reproduce the bug : [https://github.com/electro7/dot_arch/blob/master/.vim/doc/vim_cheatsheed.txt](https://github.com/electro7/dot_arch/blob/master/.vim/doc/vim_cheatsheed.txt)

I also post the bug in vim-airline git repository, here : [https://github.com/vim-airline/vim-airline/issues/1969](https://github.com/vim-airline/vim-airline/issues/1969)

Sorry for my horrible english.

**Comment by chrisbra** [comment]
as said on the vim-airline issue tracker. Can you generate a backtrace from a (debug) build of Vim? Might also try to compile using ASAN enabled (search src/Makefile for sanitizer).

**Comment by dpelle** [comment]
I tried to reproduce with vim-8.1.2161 but I could not.  I did not crash
for me. I used a asan build.

To @electro7: Your version vim-8.1.1968 is not so old (Sep 3, 2019), but
I suggest that you build the latest vim from github, and try to reproduce it.
As suggested by @chrisbra, providing stderr output with a asan build
would be ideal if it still crashes for you. To build with asan, you need to
uncomment this line in vim/src/Makefile:
```
SANITIZER_CFLAGS = -g -O0 -fsanitize=address -fno-omit-frame-pointer
```

**Comment by lacygoill** [comment]
I cannot reproduce the issue on 8.2.2154 with https://github.com/vim-airline/vim-airline/commit/f39208f1a074fb525270312a20c87521a50c74ef, and [this cheatsheet](https://github.com/electro7/dot_arch/blob/master/.vim/doc/vim_cheatsheet.txt) mentioned in the OP (the original link was broken).

@electro7 Can you still reproduce the crash with the latest Vim and the latest vim-airline?

**Comment by chrisbra** [comment]
Let's close it down. @electro7 if you can reproduce, please open a new issue with a reproducible example and if possible provide ASAN logs and/or a (gdb-) backtrace from the crash. Thanks.
