### ISSUE TITLE
unexpected cursor position after resizing the terminal while the cursor is on a line containing concealed characters

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#4931]
**Describe the bug**

After resizing the terminal window, while the cursor is on a line containing concealed characters, the cursor is redrawn in a different location.

**To Reproduce**

1. Open an xterm window.

2. Run this shell command:

        $ vim -Nu NONE  \
        --cmd 'syn region zshCommentCodeSpan matchgroup=Comment start=/\z(`\+\)/ end=/\z1/ concealends containedin=zshComment' \
        +'setl cocu=n cole=3' \
        +'norm! fb' \
        <(cat <<'EOF'
        `one` `two` `three` `four` `five`, the backticks should be concealed
        EOF
        )

3. Resize the terminal window.

It looks as if the cursor has moved ten characters forward.
It went from there:

    `one` `two` `three` `four` `five`, the backticks should be concealed
                                           ^
                                           cursor is here

To there:

    `one` `two` `three` `four` `five`, the backticks should be concealed
                                                     ^
                                                     now it's there

**Expected behavior**

I would expect the cursor to be drawn in the same location as it was before the terminal window was resized.

**Screenshots**

![gif](https://user-images.githubusercontent.com/8505073/64889701-2bbc0600-d66e-11e9-92df-3fac70dd0273.gif)

**Environment**

 - Vim version: 8.1  Included patches: 1-1967
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

I frequently encounters this issue when I [open a tmux pane](https://github.com/tmux/tmux/issues/1910), which – I guess – resizes the terminal window from Vim's point of view.

**Comment by brammool** [comment]
> After resizing the terminal window, while the cursor is on a line
> containing concealed characters, the cursor is redrawn in a different
> location.
> 
> **To Reproduce**
> 
> 1. Open an xterm window.
> 
> 2. Run this shell command:
> 
>         $ vim -Nu NONE  \
>         --cmd 'syn region zshCommentCodeSpan matchgroup=Comment start=/\z(`\+\)/ end=/\z1/ concealends containedin=zshComment' \
>         +'setl cocu=n cole=3' \
>         +'norm! fb' \
>         <(cat <<'EOF'
>         `one` `two` `three` `four` `five`, the backticks should be concealed
>         EOF
>         )
> 
> 3. Resize the terminal window.
> 
> It looks as if the cursor has moved ten characters forward.
> It went from there:
> 
>     `one` `two` `three` `four` `five`, the backticks should be concealed
>                                            ^
>                                            cursor is here
> 
> To there:
> 
>     `one` `two` `three` `four` `five`, the backticks should be concealed
>                                                      ^
>                                                      now it's there
> 
> **Expected behavior**
> 
> I would expect the cursor to be drawn in the same location as it was before the terminal window was resized.

Can you put the commands in a Vim script instead of a shell command?
The concealing doesn't work, it looks like it depends on zsh syntax, but
the file doesn't have zsh filetype.

-- 
hundred-and-one symptoms of being an internet addict:
252. You vote for foreign officials.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
Ah yes, you are right; the example doesn't need the zsh syntax. I didn't simplify the example enough, sorry.

Here is another example where the syntax code is in a Vim script file:

    $ cat <<'EOF' >/tmp/vim.vim
    setl cocu=n cole=3
    syn region CommentCodeSpan start=/`/ end=/`/ concealends
    EOF

    $ cat <<'EOF' >/tmp/file
    `one` `two` `three` `four` `five`, the backticks should be concealed
    EOF

    $ vim -Nu /tmp/vim.vim +'norm! fb' /tmp/file

**Comment by lacygoill** [comment]
No wait, I think it doesn't work. I'm going to try to come up with another working example.

**Comment by lacygoill** [comment]
Hopefully this one should work:

    $ cat <<'EOF' >/tmp/vim.vim
    setl cocu=n cole=3
    syn region CommentCodeSpan matchgroup=Comment start=/`/ end=/`/ concealends
    EOF

    $ cat <<'EOF' >/tmp/file
    `one` `two` `three` `four` `five`, the backticks should be concealed
    EOF

    $ vim -Nu /tmp/vim.vim +'norm! fb' /tmp/file

I think the `matchgroup=Comment` argument is needed to reproduce, that's why the previous example didn't work.
