### ISSUE TITLE
The popup window shrinks when norm! <c-f> is executed

### ISSUE THREAD

**Issue by mmahnic** [vim/vim#4935]
**Detailed description**
When a popup window is created all its items are displayed and the first one is highlighted. When `norm! \<c-f>`is executed (press `ctrl-f` in the example), the last item is correctly highlighted, but all the other items disappear and the window shrinks to only one line. When `norm! -` is executed (press `k` in the example), previous items are shown one by one and the window grows by one line with every keypress.

```
function! ScrollNarrowBug()
   let winid = popup_create( [ "Item A", "Item B", "Item C" ], #{
            \ filter: 'ScrollNarrowBugFilter',
            \ cursorline: 1,
            \ wrap: 0
            \ } )
endfunc

function! ScrollNarrowBugFilter( winid, key )
   if a:key == "\<C-F>"
     call win_execute( a:winid, "normal! \<C-F>" )
   elseif a:key == "k"
     call win_execute( a:winid, "normal! -" )
   else
      return popup_filter_yesno( a:winid, a:key )
   endif
   return v:true
endfunc

call ScrollNarrowBug()
```

**To Reproduce**
Detailed steps to reproduce the behaviour:

1. Save the above script into a file
2. Run vim --clean (or gvim --clean, etc.)
3. Open the saved script
4. :so %
5. A popup window with items A, B, C is displayed; Item A is highlighted
6. Press 'ctrl-f' to move down one page (_bug: the window shrinks, only item C is displayed_)
7. Press 'k' to move up; Item B appears; Item A appears after the next keypress

**Expected behaviour**
It is expected that after `ctrl-f` is pressed, the window size remains the same and that Item C is highlighted.
Optional (these suggestions might be in conflict with the normal behaviour of `ctrl-f`):
- If possible, the window should show all three items. 
- If possible, the distance from the topline to the highlighted line should remain the same after `ctrl-f` when the scrollbar is visible (there are more lines in the buffer than the hight of the window).
- If possible: when the last line is displayed, it should always be at the bottom of the window, assuming there are enough lines to fill the window; if there are not enough lines, `topline` should be 1.

**Environment (please complete the following information):**
-    Vim 8.1, patches 1-2022
-    OS: Ubuntu 18.04.3 LTS
-    Terminal: [Konsole and GUI]

**Comment by brammool** [comment]
> **Detailed description**
> When a popup window is created all its items are displayed and the
> first one is highlighted. When `norm! \<c-f>`is executed (press ctrl-f
> in the example), the last item is correctly highlighted, but all the
> other items disappear and the window shrinks to only one line. When
> `norm! -` is executed (press k in the example), previous items are
> shown one by one and the window grows by one line with every keypress.
> 
> ```
> function! ScrollNarrowBug()
>    let winid = popup_create( [ "Item A", "Item B", "Item C" ], #{
>             \ filter: 'ScrollNarrowBugFilter',
>             \ cursorline: 1,
>             \ wrap: 0
>             \ } )
> endfunc
> 
> function! ScrollNarrowBugFilter( winid, key )
>    if a:key == "\<C-F>"
>      call win_execute( a:winid, "normal! \<C-F>" )
>    elseif a:key == "k"
>      call win_execute( a:winid, "normal! -" )
>    else
>       return popup_filter_yesno( a:winid, a:key )
>    endif
>    return v:true
> endfunc
> 
> call ScrollNarrowBug()
> ```
> 
> 
> **To Reproduce**
> Detailed steps to reproduce the behavior:
> 
> 1. Save the above script into a file
> 2. Run vim --clean (or gvim --clean, etc.)
> 3. Open the saved script
> 4. :so %
> 5. A popup window with items A, B, C is displayed; Item A is highlighted
> 6. Press 'ctrl-f' to move down one page (_bug: the window shrinks, only item C is displayed_)
> 7. Press 'k' to move up; Item B appears; Item A appears after the next keypress
> 
> **Expected behavior**
> It is expected that after <ctrl-f> is pressed, the window size remains
> the same and that Item C is highlighted.
> Optional (these suggestions might be in conflict with the normal behaviour of <ctrl-f>):
> - If possible, the window should show all three items. 
> - If possible, the distance from the topline to the highlighted line
> should remain the same after <ctrl-f> when the scrollbar is visible
> (there are more lines in the buffer than the hight of the window).
> - If possible: when the last line is displayed, it should always be at
> the bottom of the window, assuming there are enough lines to fill the
> window; if there are not enough lines, `topline` should be 1.

Well, with the CTRL-F command you tell Vim to move a page forward, thus
the last line becomes the top line.  Since you haven't specified a
mininum height, Vim then sees no reason to display lines below the last
one, thus you only see one line.

You can add "minheight: 3", then the window won't shrink, but still
"Item C" becomes the first one, then two empty lines.  And you get a
scrollbar (which doesn't work properly, that might be a bug).

I think your suggestions all go against the flexibility of popup
windows.  In the filter you can easily get the properties and set the
first line and height as you desire.

-- 
hundred-and-one symptoms of being an internet addict:
258. When you want to see your girlfriend, you surf to her homepage.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mmahnic** [comment]
> Well, with the CTRL-F command you tell Vim to move a page forward, thus
> the last line becomes the top line.  Since you haven't specified a
> mininum height, Vim then sees no reason to display lines below the last
> one, thus you only see one line.
> 
> You can add "minheight: 3", then the window won't shrink, but still
> "Item C" becomes the first one, then two empty lines.  

I could use this as a workaround in my project with some effort. But I think the current behaviour is not consistent with the way normal windows work: when there are not enough lines, normal windows do not shrink, instead, Vim displays empty lines (~). Changing the geometry of a window after a move operation is unexpected.

Also this solution requires plugins to use two minimum heights: one for the absolute minimum height that the window is not supposed to shrink below, no matter the content. The second minimum depends on: the current content of the buffer, the current line, the top line, the absolute minimum size, the maximum size, the available screen space if the maximum is not set. It's a fairly complex calculation after every move operation and an additional window variable (or option) has to be used to save the absolute minimum. This reduces the flexibility of the popup window if we have to code the behaviour in every plugin.

> I think your suggestions all go against the flexibility of popup
> windows.  In the filter you can easily get the properties and set the
> first line and height as you desire.

I totally agree about the suggestions under 'Optional'.

But I think the logic for repositioning windows should be reversed for move operations: if the filter wants to shrink the window after a move operation, this should be coded explicitly in the filter. I think that operations that don't affect the content of the popup buffer should not modify the geometry of the window by default.

**Comment by brammool** [comment]
> > Well, with the CTRL-F command you tell Vim to move a page forward, thus
> > the last line becomes the top line.  Since you haven't specified a
> > mininum height, Vim then sees no reason to display lines below the last
> > one, thus you only see one line.
> > 
> > You can add "minheight: 3", then the window won't shrink, but still
> > "Item C" becomes the first one, then two empty lines.  
> 
> I could use this as a workaround in my project with some effort. But I
> think the current behaviour is not consistent with the way normal
> windows work: when there are not enough lines, normal windows do not
> shrink, instead, Vim displays empty lines (~). Changing the geometry
> of a window after a move operation is unexpected.

Popup windows are not normal windows.  BTW: CTRL-F is not a move
operation, it scrolls the text, the window stays in the same place.

> Also this solution requires plugins to use two minimum heights: one
> for the absolute minimum height that the window is not supposed to
> shrink below, no matter the content. The second minimum depends on:
> the current content of the buffer, the current line, the top line, the
> absolute minimum size, the maximum size, the available screen space if
> the maximum is not set. It's a fairly complex calculation after every
> move operation and an additional window variable (or option) has to be
> used to save the absolute minimum. This reduces the flexibility of the
> popup window if we have to code the behaviour in every plugin.

Why do you use the command to scroll?  Just move the cursor around, then
everything is fine.

> > I think your suggestions all go against the flexibility of popup
> > windows.  In the filter you can easily get the properties and set the
> > first line and height as you desire.
> 
> I totally agree about the suggestions under 'Optional'.
> 
> But I think the logic for repositioning windows should be reversed for
> move operations: if the filter wants to shrink the window after a move
> operation, this should be coded explicitly in the filter. I think that
> operations that don't affect the content of the popup buffer should
> not modify the geometry of the window by default.

In most cases all the text in the window needs to be readable, and the
window needs to resize to show it, without taking up too much space.
If you want to fix the size, then specify the size.  If you don't know
what size is needed to show the text, then first display it, get the
size with popup_getpos() and set max/min width/height with
popup_setoptions().

-- 
hundred-and-one symptoms of being an internet addict:
262. Your computer has it's own phone line - but your daughter doesn't.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mmahnic** [comment]
> Why do you use the command to scroll?  Just move the cursor around, then
> everything is fine.

Ok. I will avoid using `ctrl-f` and similar commands and use `+`, instead. This seems to work:

```
   if a:key == "\<C-F>"
     let pos = popup_getpos( a:winid )
     call win_execute( a:winid, "normal! " . pos.core_height . "+" )
   endif
```

Thanks!
