### ISSUE TITLE
vimrun.exe window keeps open alter pressing `gx` to open an URL.

### ISSUE THREAD

**Issue by JPLiu** [vim/vim#4936]
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Describe the bug**
(Issues related to the runtime files should be reported to their maintainer, check the file header.)

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Open a file with URL in it.
2. Press `gx` on URL to open it.
3. vimrun.exe window keeps open and the URL doesn't open until press any key to close the vimrun.exe window.

**Screenshots**
<img width="734" alt="vimrun_2019-09-14_20-24-44" src="https://user-images.githubusercontent.com/13379952/64908104-232b0480-d72e-11e9-82a9-26733d650957.png">

**Environment (please complete the following information):**
 - Vim version gvim for windows 8.1.2006
 - OS: Windows 10 1903
 - Terminal: GUI (Use GUI if you use the GUI.)

**Comment by chrisbra** [comment]
Have you tried `:set guioptions+=!`?

**Comment by JPLiu** [comment]
<img width="475" alt="gvim_2019-09-16_19-12-24" src="https://user-images.githubusercontent.com/13379952/64953699-0de0e200-d8b6-11e9-9595-dd788b80242e.png">

I just tried version 8.1.2044 and `:set guioptions+=!` doesn't work for me.

Also I tried version 8.1.1705 which works fine whether `set guioptions+=!` or not.

**Comment by chrisbra** [comment]
is the netrw version different between both Vim versions?

**Comment by JPLiu** [comment]
<img width="885" alt="WinMergeU_2019-09-16_19-51-46" src="https://user-images.githubusercontent.com/13379952/64955671-73839d00-d8bb-11e9-9984-4f5eed5675ec.png">

It seems that netrw updated in Jul 16, 2019.

**Comment by chrisbra** [comment]
so I suppose this is the same as #4738

**Comment by chrisbra** [comment]
can you check some of the workarounds mentioned in the other issue?

**Comment by JPLiu** [comment]
Closing as this is the same as #4738 
I checked the workarounds mentioned in the other issue and use open-brower.vim instead for now.
