### ISSUE TITLE
True colors in terminal 

### ISSUE THREAD

**Issue by nowox** [vim/vim#494]
My terminals (Cygwin Mintty and Ubuntu Terminal) support 24-bits colors. However Vim still use poor 256-colors for terminal. 

Is there any option for using GUI colors in terminal using this ANSI sequence `\x1b[38;2;255;100;0mTRUECOLOR\x1b[0m` ?

I imagine a vim option like `:set truecolors=1` (I renamed it from TrueColors after ZyX-I comment)

**Comment by ZyX-I** [comment]
I have posted 24-bit-xterm patch more then two years ago (Jan 2013) that adds `&guicolors` option (note: there are exactly no existing options that contain underscores or capital letters, so `TrueColors` name will never be accepted), but it is still not merged. Somewhat maintained version is at bookmark `local-default` in repository https://bitbucket.org/ZyX_I/vim: it is my local bookmark which has patches I care about merged in (I actually remember only merging in 24-bit-xterm bookmark (still existing there, less maintained), but AFAIR there was something else). AFAIR patch you may find in vim-dev can still be applied with minimal conflicts as well.

**Comment by ZyX-I** [comment]
Though note that terminals started actively supporting true color _after_ this patch, before there was literally one working example: konsole (KDE terminal) and one semi-working (xterm, used nearest color from its 8-bit palette in place of actually providing true color support).

**Comment by ZyX-I** [comment]
(Note that with my patch you will need to set options `t_8f` and `t_8b` for any terminal that does not report itself as `xterm` (`$TERM ≠ 'xterm'`).)

**Comment by nowox** [comment]
I will look at your repository. In the meantime I digged into vim source code and found that the story begins at `screen_start_highlight(attr)` in `screen.c`. I guess I can easily replace 

```
        if (aep != NULL)
        {
        if (t_colors > 1)
        {
            if (aep->ae_u.cterm.fg_color)
            term_fg_color(aep->ae_u.cterm.fg_color - 1);
            if (aep->ae_u.cterm.bg_color)
            term_bg_color(aep->ae_u.cterm.bg_color - 1);
        }
        else
        {
            if (aep->ae_u.term.start != NULL)
            out_str(aep->ae_u.term.start);
        }
        }  
```

with something like 

```
        if (aep != NULL)
        {
        if (t_colors > 1)
        {
            if (aep->ae_u.cterm.fg_color)
            term_fg_color(aep->ae_u.cterm.fg_color - 1);
            if (aep->ae_u.cterm.bg_color)
            term_bg_color(aep->ae_u.cterm.bg_color - 1);
        }
        else if (t_colors > 256) # Should set t_colors > ...
        {
            if (aep->ae_u.gui.fg_color)
            term_fg_true_color(aep->ae_u.gui.fg_color - 1);
            if (aep->ae_u.gui.bg_color)
            term_bg_true_color(aep->ae_u.gui.bg_color - 1);
        }
        else
        {
            if (aep->ae_u.term.start != NULL)
            out_str(aep->ae_u.term.start);
        }
        }  
```

where `term_fg_true_color` could be something like: 

```
    static void
term_true_color(s,n)
    char_u      *s;
    int         n;
{
    int r,g,b;
    r = (n & 0xFF0000) >> 16;
    g = (n & 0x00FF00) >> 8;
    b = (n & 0x0000FF);
    char buf[20];
    sprintf(buf, "\033[38;2;%d;%d;%dm\0", r, g, b);
    OUT_STR(buf);
}

    void
term_fg_true_color(n)
    int     n;
{
    /* Use "AF" termcap entry if present, "Sf" entry otherwise */
    if (*T_CAF)
    term_true_color(T_CAF, n);
    else if (*T_CSF)
    term_true_color(T_CSF, n);
}    
```

That said, it currently doesn't work and I get a very pinky colorscheme. I guess the encoding of `rgb` colors is not `0xRRGGBB`...

I still need more work I guess :)

**Comment by ZyX-I** [comment]
@nowox Patch was already done. In the repository it is present as a bookmark `24-bit-xterm` or `local-default` (such things are named branches in git), but bitbucket does not list this AFAIK. You may use search: https://bitbucket.org/ZyX_I/vim/commits/all?search=24-bit-xterm.

You cannot possibly get a patch out of this without using mercurial, so I suggest not to mess with the web interface in the first place. Just clone with all bookmarks.

**Comment by nowox** [comment]
Nice, I found it, but I am still wondering what is this https://bitbucket.org/ZyX_I repository? It is actively maintained, but not quite official. What are you offering beside this official repository?

**Comment by ZyX-I** [comment]
@nowox I do not understand your question. It is my fork of Vim where I post every my big enough patch to Vim. Also https://bitbucket.org/ZyX_I is not a _repository_, it is a link to a _user_.

**Comment by nowox** [comment]
Sorry, I wasn't very clear. I was indeed talking about https://bitbucket.org/ZyX_I/vim/ which I understood it is your fork. I also noticed you are actively wroking on it and I guess lot this of work deserve to be merged into this repository. So, my question was more why all these patches are not merged into this very repository and why I haven't seen more pull request from you?

That said, why did you use a new definition `ae_u.cterm.fg_rgb` instead of using the same definition used by the gui `ae_u.gui.fg_color`?

**Comment by ZyX-I** [comment]
@nowox I have only two major unmerged things there: 24-bit-xterm and extended-funcref (last is outdated and needs hard merging).

Also I do not remember exactly what and why I did, but if you can modify my code to use `gui.fg_color` without `#define FEAT_GUI` and with less code then you are welcome. Especially given the fact that I do not see any specific restrictions put on `guicolor_T` type, and I definitely see it being signed while `long_u` in place of `long` assumes I cared about signdness.

**Comment by justinmk** [comment]
This can be closed.

**Comment by chrisbra** [comment]
thanks for noticing.
