### ISSUE TITLE
Scheme: syntaxcomplete after quote (') character causes error

### ISSUE THREAD

**Issue by flux77** [vim/vim#4952]
**Describe the bug**
When editing a Scheme file, and the `omnifunc` is [`syntaxcomplete#Complete`](https://github.com/vim/vim/blob/v8.1.2052/runtime/autoload/syntaxcomplete.vim), attempting to use omni completion after a quote character (`'`) causes an error:

```
Error detected while processing function syntaxcomplete#Complete:
line   63:
E15: Invalid expression: *'
```

**To Reproduce**
1. Open a Scheme file using Vim (e.g. `vim myprog.scm`)
2. Set the omnifunc to `syntaxcomplete#Complete`: `:set omnifunc=syntaxcomplete#Complete`
2. Type a single quote character (`'`)
3. Omni complete: <kbd>Ctrl</kbd><kbd>x</kbd><kbd>Ctrl</kbd><kbd>o</kbd>
4. Resulting error:

```
Error detected while processing function syntaxcomplete#Complete:
line   63:
E15: Invalid expression: *'
```

**Expected behavior**
A list of Omni complete suggestions should have appeared.

**Environment (please complete the following information):**
 - Vim version: 8.0.1453
 - OS: Ubuntu 18.04
 - Terminal: GNOME Terminal

**Additional context**
The problem is probably caused by:

https://github.com/vim/vim/blob/7a9bd7c1e0ce1baf5a02daf36eeae3638aa315c7/runtime/autoload/syntaxcomplete.vim#L202-L205

When `base` contains single quotes, they are not escaped, resulting in an invalid `expr` passed to `filter`.

Note that quotes in Common Lisp files do not cause the same error.

@evhan (maintainer of the Scheme syntax file)

**Comment by evhan** [comment]
Hi @flux77, thanks, I can reproduce this (but don't know enough about omni completion or syntaxcomplete to say more than that just now).

**Comment by chrisbra** [comment]
please contact the maintainer of the syntaxcomplete file.

**Comment by flux77** [comment]
@chrisbra Email sent to the maintainer of the syntaxcomplete file.

**Comment by flux77** [comment]
This error appears when using the older version of the Scheme syntax file (dated: `2016 May 23`). In that older version, the problem can be solved by removing one line: `setlocal iskeyword=33,35-39,42-58,60-90,94,95,97-122,126,_` or by changing it to `setlocal iskeyword=33,35-38,42-58,60-90,94,95,97-122,126,_`. ASCII 39 is the single quote character (`'`).

The [current version of the Scheme syntax file](https://github.com/vim/vim/blob/d2c1fb476d5816db129eb428ffef6a81027eb13a/runtime/syntax/scheme.vim) does not cause this error because it does not set `iskeyword`
