### ISSUE TITLE
An inconsistency in docs, take 2

### ISSUE THREAD

**Issue by lkintact** [vim/vim#4957]
doc/starting.txt, line 871:

_Load the plugin script.
This does the same as the command:
`:runtime! plugin/**/*.vim`_

doc/repeat.txt, line 222:

_`:runtime! plugin/*.vim`
This is what Vim uses to load the plugin files when starting up._

Please note the _`<coded>`_ parts.

Gvim: https://github.com/vim/vim-win32-installer/releases/download/v8.1.2058/gvim_8.1.2058_x86.zip

**Comment by brammool** [comment]
I'll fix the one in repeat.txt.
