### ISSUE TITLE
bd has side effects on registers when used inside a command ?

### ISSUE THREAD

**Issue by eiro** [vim/vim#4960]
hello people,

using vim 8.1.1401 (provided by debian buster), i wanted to write
a plugin to highlight the covered and uncovered parts
of a golang code.

this is a sample of the cover.out file:

  mode: set
  github.com/libretro/ludo/input/input.go:53.43,54.34 1 0
  github.com/libretro/ludo/input/input.go:55.22,56.115 1 0
  github.com/libretro/ludo/input/input.go:57.25,58.71 1 0

now the expected command as i originaly wrote it is

   1    command GoCrazy exec 'new +set\ buftype=nofile\ bufhidden=hide\ noswapfile'
   2    \| r cover.out
   3    \| %v/\v.*:(\d+)\.(\d+),(\d+)\.(\d+) \d+ (\d+)$/d
   4    \| %s!!\5 start=/\\%\1l\\%\2c/ end=/\\%\3l\\%\4c/!
   5    \| %s!^0!syn region Uncovered!
   6    \| %s!^1!syn region Covered!
   7    \| %y z
   8    \| bd
   9    \| exec @z

there is this error message:

  Screen mode setting not supported

so obviously: the first line of the cover.out isn't removed (as i
expected at line 3). so i removed the line 8 of my code and now i can
see the buffer

  syn region Uncovered start=/\%53l\%43c/ end=/\%54l\%34c/
  syn region Uncovered start=/\%55l\%22c/ end=/\%56l\%115c/
  syn region Uncovered start=/\%57l\%25c/ end=/\%58l\%71c/

which is correct. also, the content of @z complies to the buffer
content. i repeatidly toggled the bd from the macro and my conclusion
is weird: the bug appears when bd is made by the command. so i verified this using
those 3 separed commands and they work like a charm:

command GoCrazy1 exec 'new +set\ buftype=nofile\ bufhidden=hide\ noswapfile'
\| r cover.out
\| %v/\v.*:(\d+)\.(\d+),(\d+)\.(\d+) \d+ (\d+)$/d
\| %s!!\5 start=/\\%\1l\\%\2c/ end=/\\%\3l\\%\4c/!
\| %s!^0!syn region Uncovered!
\| %s!^1!syn region Covered!
\| %y z

command GoCrazy2 bd
\| hi Covered ctermbg=green
\| hi Uncovered ctermbg=red
\| exec @z

command GoCrazy exec 'GoCrazy1'|exec 'GoCrazy2'

i removed my ~/.vim* but everything remains the same .. so i got to the point where i think it's a vim bug. i'm available for any extra test or assistance for someone who try to reproduce.

regards

**Comment by andymass** [comment]
Does this still happen with registers other than `@z`, e.g. `@y` or `@b`?

**Comment by eiro** [comment]
sorry i didn't mention. yes: i tested with @a @g and @z

**Comment by eiro** [comment]
i compiled vim from master and started it with --clean. not better

**Comment by chrisbra** [comment]
I think what you are experiencing is that the `|` following the `:v` command is seen as argument to the `:v` command and not as the next argument to be executed. Causing your whole command line to be executed for the `mode set`. Most of your commands use the `%` range, so you did not notice, except for the yank command that keeps adding the `mode` line to your register. 

This is mentioned briefly at `:h :bar`. The easy way to fix it is to use `exe '%v/\v.*:(\d+).(\d+),(\d+).(\d+) \d+ (\d+)$/d'` which will make sure only the `d` is executed after the `:v` command.

**Comment by eiro** [comment]
correct! i'm really sorry i opened an issue when the bug was mine. thanks for help anyway.

regards
