### ISSUE TITLE
doc: popup: mentions that autocommands are not executed, but FileType is

### ISSUE THREAD

**Issue by blueyed** [vim/vim#4961]
https://github.com/vim/vim/blob/cd67059c0c3abf1e28aa66458abdf6f338252eb2/runtime/doc/popup.txt#L138-L141:

> Note that this does not trigger autocommands.  Use `win_execute()` if you do
need them.

But using `call setbufvar(winbufnr(s:winid), '&filetype', 'diff')` actually triggers the `FileType` autocommand.

This is good I think, but the doc needs to be adjusted/fixed.

Ref: https://github.com/airblade/vim-gitgutter/issues/653#issuecomment-533795295

**Comment by brammool** [comment]
I'll adjust the help.
