### ISSUE TITLE
`pum_getpos()` function should be written on the `:h completion-function` too

### ISSUE THREAD

**Issue by mityu** [vim/vim#4967]
**Describe the bug**

`pum_getpos()` function is written on the `:h functions` but not on the `:h completion-function`.

https://github.com/vim/vim/blob/0f6629a08a9ae482956f5e70452ae78be569eadf/runtime/doc/eval.txt#L2640
https://github.com/vim/vim/blob/0f6629a08a9ae482956f5e70452ae78be569eadf/runtime/doc/usr_41.txt#L853-L858

**Expected behavior**

Written on `:h completion-function` too.

**Environment (please complete the following information):**
Vim8.1.2069

**Comment by brammool** [comment]
I think you mean ":help *completion-functions".  I'll add pum_getpos() there.

**Comment by mityu** [comment]
Yes, thank you!
