### ISSUE TITLE
Text property highlight breaks syntax highlighting in popup

### ISSUE THREAD

**Issue by airblade** [vim/vim#4968]
**Describe the bug**

In a popup window with filetype `diff`, adding a text property with a highlight breaks the diff syntax highlighting from the end of the text property to the end of the line.

In a normal, non-popup window the syntax highlighting following the text property is as expected.

**To Reproduce**

This is the behaviour in a popup (broken):

```
vim --clean -c 'highlight Reverse gui=reverse cterm=reverse' \
-c 'call prop_type_add("foo", {"highlight": "Reverse", "combine": 1})' \
-c 'let winid = popup_create("+the cat in the hat", {"line": 1, "col": 1})' \
-c 'call setbufvar(winbufnr(winid), "&filetype", "diff")' \
-c 'call prop_add(1, 6, {"type": "foo", "end_col": 9, "bufnr": winbufnr(winid)})'
```

In comparison this is the behaviour in a normal window (correct):

```
vim --clean -c 'highlight Reverse gui=reverse cterm=reverse' \
-c 'call prop_type_add("foo", {"highlight": "Reverse", "combine": 1})' \
-c 'call setline(1, "+the cat in the hat")' \
-c 'call setbufvar(1, "&filetype", "diff")' \
-c 'call prop_add(1, 6, {"type": "foo", "end_col": 9, "bufnr": 1})'
```

**Expected behavior**

I expect the highlighting in the popup to be the same as the highlighting in a normal window.

**Screenshots**

Popup (broken):

<img width="166" alt="Screenshot 2019-09-23 at 11 59 45 am" src="https://user-images.githubusercontent.com/7265/65420698-baace900-ddf9-11e9-8f0b-6cc55b9ec6d8.png">

Normal window (correct):

<img width="205" alt="Screenshot 2019-09-23 at 12 00 56 pm" src="https://user-images.githubusercontent.com/7265/65420738-d617f400-ddf9-11e9-859f-e7d1a056655d.png">

**Environment**
- Vim 8.1.1722 (terminal and macvim)
- macOS 10.14
- iTerm2

**Comment by brammool** [comment]
If you set 'wincolor' in the normal window the same thing happens.

**Comment by airblade** [comment]
Thank you very much!
