### ISSUE TITLE
`gk` moves the cursor unexpectedly below a long folded line

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#4969]
**Describe the bug**

Sometimes, `gk` doesn't move the cursor on the previous screen line, but at the start of the line.

**To Reproduce**

1. Run this shell command:

        $ vim -Nu NONE +"set co=80|setl fml=0 fdm=marker" +"pu=[repeat('x',90)..' {{{1', 'x {{{1']" +'norm! Gzv'

2. Press `gk`, `j` and `gk` again.

The last `gk` moves the cursor at the start of the current line.

**Expected behavior**

I would expect the last `gk` to move the cursor on the previous screen line.
The issue persists even after opening all folds with `zR`.

**Screenshots**

![gif](https://user-images.githubusercontent.com/8505073/65424858-d8d01480-de0c-11e9-86b8-7af87187de2b.gif)

**Environment**

 - Vim version: 8.1  Included patches: 1-2069
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Comment by chrisbra** [comment]
Looks like a typo:

```patch
diff --git a/src/normal.c b/src/normal.c
index 13ef51878..a74f91bda 100644
--- a/src/normal.c
+++ b/src/normal.c
@@ -3424,7 +3424,7 @@ nv_screengo(oparg_T *oap, int dir, long dist)
       {
        if (dir == BACKWARD)
        {
-           if ((long)curwin->w_curswant >= width2)
+           if ((long)curwin->w_curswant > width2)
                /* move back within line */
                curwin->w_curswant -= width2;
            else
```

I'll have a look at how to create a test (not sure currently, as this depends on the terminal size.

**Comment by lacygoill** [comment]
I've just tested the patch, and it fixes the issue. Thank you very much.

**Comment by chrisbra** [comment]
So here is a proper patch with a test:

```patch
diff --git a/src/normal.c b/src/normal.c
index 13ef51878..a74f91bda 100644
--- a/src/normal.c
+++ b/src/normal.c
@@ -3424,7 +3424,7 @@ nv_screengo(oparg_T *oap, int dir, long dist)
       {
        if (dir == BACKWARD)
        {
-           if ((long)curwin->w_curswant >= width2)
+           if ((long)curwin->w_curswant > width2)
                /* move back within line */
                curwin->w_curswant -= width2;
            else
diff --git a/src/testdir/test_normal.vim b/src/testdir/test_normal.vim
index c6df1834a..dcfa929c8 100644
--- a/src/testdir/test_normal.vim
+++ b/src/testdir/test_normal.vim
@@ -2633,3 +2633,25 @@ fun! Test_normal_gdollar_cmd()
   call assert_equal('100 foobar foobar fo', getreg(0))
   bw!
 endfunc
+
+func Test_normal_gk()
+  " needs 80 column new window
+  new
+  vert 80new
+  put =[repeat('x',90)..' {{{1', 'x {{{1']
+  norm! gk
+  " In a 80 column wide terminal the window will be only 78 char
+  " (because Vim will leave space for the other window),
+  " but if the terminal is larger, it will be 80 chars, so verify the
+  " cursor column correctly.
+  call assert_equal(winwidth(0)+1, col('.'))
+  call assert_equal(winwidth(0)+1, virtcol('.'))
+  norm! j
+  call assert_equal(6, col('.'))
+  call assert_equal(6, virtcol('.'))
+  norm! gk
+  call assert_equal(95, col('.'))
+  call assert_equal(95, virtcol('.'))
+  bw!
+  bw!
+endfunc
```

**Comment by itchyny** [comment]
This patch seems to break the behavior of gk. After executing
`vim -Nu NONE +"set co=80|pu=[repeat('x',90)..' {{{1', 'x {{{1']|norm gg"`
press gjgjgk should place the cursor at line 2 but after 8.1.2072 it moves to line 1.

**Comment by zwegner** [comment]
Interesting, I found this same bug independently a couple days ago, working on the row-wise scrolling feature for neovim. The proposed patch is still wrong AFAICT, as it compares against width2 and not width1.

As an example, try: `:set wrap number cpoptions+=n co=80 | put=[repeat('0',90), repeat('1',90)] | norm gj3h`, so the cursor is directly below the number display on a wrapped line. gk will go up two lines, to the end of the row, and another gk will move left in the same row to the column the cursor was at before. Instead, the cursor should probably go up one row and be pushed forward to column zero, after the number (the "proper" behavior here might be to use a negative value for w_curswant, but that would quite possibly break other things). Here's a patch that I believe is correct.

**EDIT:** Actually, a couple corrections: my patch originally had `>` instead of `>=` like patch 2072, but this is wrong. The comparison should be `>=`, since w_curswant is zero-based, and w_curswant==width1 corresponds to the first column of the second row. This breaks the test from 2072 though, which I think is for a different reason: the adjustment on lines 2502-2504 to the cursor position if w_curswant is past the end of the last row of the current line (i.e., the desired cursor position would be screen rows downwards, not columns to the right). The adjustment subtracts a multiple of width2, staying in the same window column, but if the test from 2072 is taken as the correct behavior (and to match the comment above these lines), this should instead be the rightmost column of the last screen row, n - 1. The comparison `> (colnr_T)n + 1` on line 2502 is also wrong for the same reason as `>=` vs `>` above.

So I believe this patch now fixes two bugs: the original reported bug here, and the width1/width2 discrepancy I described above with `cpoptions+=n` (which is actually unrelated).

```diff
diff --git a/src/normal.c b/src/normal.c
index 1fddeae07..e696ad07f 100644
--- a/src/normal.c
+++ b/src/normal.c
@@ -2499,18 +2499,17 @@ nv_screengo(oparg_T *oap, int dir, long dist)
            n = ((linelen - width1 - 1) / width2 + 1) * width2 + width1;
        else
            n = width1;
-       if (curwin->w_curswant > (colnr_T)n + 1)
-           curwin->w_curswant -= ((curwin->w_curswant - n) / width2 + 1)
-                                                                    * width2;
+       if (curwin->w_curswant >= (colnr_T)n)
+           curwin->w_curswant = n - 1;
       }

       while (dist--)
       {
        if (dir == BACKWARD)
        {
-           if ((long)curwin->w_curswant > width2)
+           if ((long)curwin->w_curswant >= width1)
                // move back within line
-               curwin->w_curswant -= width2;
+               curwin->w_curswant = MAX(0, curwin->w_curswant - width2);
            else
            {
                /* to previous line */
diff --git a/src/testdir/test_normal.vim b/src/testdir/test_normal.vim
index dcfa929c8..9b5af408f 100644
--- a/src/testdir/test_normal.vim
+++ b/src/testdir/test_normal.vim
@@ -2654,4 +2654,21 @@ func Test_normal_gk()
   call assert_equal(95, virtcol('.'))
   bw!
   bw!
+
+  " needs 80 column new window
+  new
+  vert 80new
+  set number
+  set numberwidth=10
+  set cpoptions+=n
+  put =[repeat('0',90), repeat('1',90)]
+  norm! 075l
+  call assert_equal(76, col('.'))
+  norm! gk
+  call assert_equal(1, col('.'))
+  norm! gk
+  call assert_equal(winwidth(0)+1, col('.'))
+  call assert_equal(winwidth(0)+1, virtcol('.'))
+  bw!
+  bw!
 endfunc
```

**Comment by brammool** [comment]
Zach Wegner wrote:

> Interesting, I found this same bug independently a couple days ago,
> working on the row-wise scrolling feature for neovim. The proposed
> patch is still wrong AFAICT, as it compares against width2 and not
> width1.
> 
> As an example, try: `:set wrap number cpoptions+=n co=80 |
> put=[repeat('0',90), repeat('1',90)] | norm gj3h`, so the cursor is
> directly below the number display on a wrapped line. gk will go up two
> lines, to the end of the row, and another gk will move left in the
> same row to the column the cursor was at before. Instead, the cursor
> should probably go up one row and be pushed forward to column zero,
> after the number (the "proper" behavior here might be to use a
> negative value for w_curswant, but that would quite possibly break
> other things). Here's a patch that I believe is correct.

This gets closer, but it's not symmetrical: When using "gj" on the first
line, with the cursor below the line number, it move so the second line
below the line number.  That looks OK, since that's where the next
screen line is.  Thus "gk" in that position should move back, so that a
sequence of "gj" and "gk" gets us back in the same position.


-- 
I bought a book on hair loss, but the pages kept falling out.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by zwegner** [comment]
I'd argue that in that case, gj should move one line down, and rightwards to the first column. This would itself be symmetric to the behavior of gj/gk if the new row is shorter than the cursor's column position (and virtualedit is off)--the cursor moves to the left, to the the end of the line. Ideally, another gj would move down and to the left, back to the original column position, but this would involve a negative value for w_curswant, which I think is a bit risky in terms of causing bugs.

Also, gj is broken in this case if the line below is short enough so it doesn't wrap around--in that case, the cursor moves to the rightmost column. Try `:set wrap number cpoptions+=n co=80 | put=[repeat('0',90), repeat('1',70)] | norm k078l` for a test case.

**Comment by zwegner** [comment]
I looked around at uses of w_curswant (not exhaustively) and I'm less concerned than before about using negative values, which would allow the "proper" behavior for gj/gk. I spotted just a couple places that need to be changed (both in `coladvance2`). Below is an updated patch that appears to work cleanly.

```diff
diff --git a/src/misc2.c b/src/misc2.c
index da274e603..e9db3f0af 100644
--- a/src/misc2.c
+++ b/src/misc2.c
@@ -206,6 +206,7 @@ coladvance2(

        if (virtual_active()
                && addspaces
+               && wcol >= 0
                && ((col != wcol && col != wcol + 1) || csize > 1))
        {
            /* 'virtualedit' is set: The difference between wcol and col is
@@ -305,7 +306,7 @@ coladvance2(
     if (has_mbyte)
        mb_adjustpos(curbuf, pos);

-    if (col < wcol)
+    if (wcol < 0 || col < wcol)
        return FAIL;
     return OK;
 }
diff --git a/src/normal.c b/src/normal.c
index 1fddeae07..50f7b3185 100644
--- a/src/normal.c
+++ b/src/normal.c
@@ -2499,17 +2499,18 @@ nv_screengo(oparg_T *oap, int dir, long dist)
            n = ((linelen - width1 - 1) / width2 + 1) * width2 + width1;
        else
            n = width1;
-       if (curwin->w_curswant > (colnr_T)n + 1)
-           curwin->w_curswant -= ((curwin->w_curswant - n) / width2 + 1)
-                                                                    * width2;
+       if (curwin->w_curswant >= (colnr_T)n)
+           curwin->w_curswant = n - 1;
       }

       while (dist--)
       {
        if (dir == BACKWARD)
        {
-           if ((long)curwin->w_curswant > width2)
-               // move back within line
+           if ((long)curwin->w_curswant >= width1)
+               // Move back within the line. This can give a negative value
+               // for w_curswant if width1 < width2 (with cpoptions+=n),
+               // which will get clipped to column 0.
                curwin->w_curswant -= width2;
            else
            {
@@ -2557,6 +2558,12 @@ nv_screengo(oparg_T *oap, int dir, long dist)
                }
                curwin->w_cursor.lnum++;
                curwin->w_curswant %= width2;
+               // Check if the cursor has moved below the number display
+               // when width1 < width2 (with cpoptions+=n). Subtract width2
+               // to get a negative value for w_curswant, which will get
+               // clipped to column 0.
+               if (curwin->w_curswant >= width1)
+                   curwin->w_curswant -= width2;
                linelen = linetabsize(ml_get_curline());
            }
        }
diff --git a/src/testdir/test_normal.vim b/src/testdir/test_normal.vim
index dcfa929c8..34184be73 100644
--- a/src/testdir/test_normal.vim
+++ b/src/testdir/test_normal.vim
@@ -2654,4 +2654,28 @@ func Test_normal_gk()
   call assert_equal(95, virtcol('.'))
   bw!
   bw!
+
+  " needs 80 column new window
+  new
+  vert 80new
+  set number
+  set numberwidth=10
+  set cpoptions+=n
+  put =[repeat('0',90), repeat('1',90)]
+  norm! 075l
+  call assert_equal(76, col('.'))
+  norm! gk
+  call assert_equal(1, col('.'))
+  norm! gk
+  call assert_equal(76, col('.'))
+  norm! gk
+  call assert_equal(1, col('.'))
+  norm! gj
+  call assert_equal(76, col('.'))
+  norm! gj
+  call assert_equal(1, col('.'))
+  norm! gj
+  call assert_equal(76, col('.'))
+  bw!
+  bw!
 endfunc
```

**Comment by chrisbra** [comment]
Thanks for the input.  The test needs to reset the `cpoptions` setting. BTW, would you consider a PR for the smooth scrolling feature here upstream?

**Comment by zwegner** [comment]
> BTW, would you consider a PR for the smooth scrolling feature here upstream?

Hmm, possibly. This feature has turned into a lot more work than I had initially expected, and it's not clear yet how much more work needs to be done to make the feature as polished as I'd like. Migrating patches back to Vim with a different coding style, FEAT_* macros, and a new set of tests would likely be a lot of work, which would be good to avoid while the code is still in a state of flux. If someone wants to port any patches in the meantime, I'm happy to help.
