### ISSUE TITLE
:term command not available in vim 8.0

### ISSUE THREAD

**Issue by TheSeriousProgrammer** [vim/vim#4971]
I am using vim 8.0 in Amazon-ami-linux

I know that the :term command works from vim version 8 ,but the :term command is not working in my release,

How to get the :term working in my version of vim?

**Command _vim --version_ output **
--version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 13 2019 21:28:49)
Included patches: 1-503, 1365
Modified by <amazon-linux-ami@amazon.com>
Compiled by <amazon-linux-ami@amazon.com>
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
-clientserver    +insert_expand   +packages        -toolbar
-clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python          +vreplace
+cscope          +lispindent      -python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      -lua             +rightleft       +writebackup
+diff            +menu            +ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      -mouseshape      +startuptime     -xsmp
+eval            +mouse_dec       +statusline      -xterm_clipboard
+ex_extra        +mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax
+farsi           +mouse_netterm   +tag_binary
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim80"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -O2 -g -pipe -Wall -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,--enable-new-dtags -Wl,-rpath,/usr/lib64/perl5/CORE   -L/usr/local/lib -Wl,--as-needed -o vim        -lm -lnsl   -lncurses -lacl -lattr -lgpm -ldl   -Wl,--enable-new-dtags -Wl,-rpath,/usr/lib64/perl5/CORE  -fstack-protector  -L/usr/lib64/perl5/CORE -lperl -lresolv -lnsl -ldl -lm -lcrypt -lutil -lpthread -lc -L/usr/lib64/python2.7/config -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic   -L/usr/lib64/ruby/2.0 -lruby -lpthread -lrt -ldl -lcrypt -lm

**Comment by chrisbra** [comment]
Your `:version` does not mention the `terminal` feature and indeed, the main feature of Vim 8.1 was the terminal command (see https://www.vim.org/vim-8.1-released.php). So you need a Vim 8.1. release.

**Comment by k-takata** [comment]
8.0.0693 was the initial patch for the terminal feature, so at least that patchlevel is needed. Of course that version is unstable, so 8.1 is recommended.

**Comment by TheSeriousProgrammer** [comment]
so how to install vim 8.1 in your device if it is not available in your OS package manager, sorry I am a beginner

**Comment by chrisbra** [comment]
This depends on your operating system and your user rights. 
Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here.

**Comment by tonymec** [comment]
> so how to install vim 8.1 in your device if it is not available in your OS package manager, sorry I am a beginner

- To get the latest official Vim source: see https://vim.fandom.com/wiki/Getting_the_Vim_source_with_Mercurial
- To compile on Unix-like (i.e. non-Windows) systems: see http://users.skynet.be/antoine.mechelynck/vim/compunix.htm

You don't need to uninstall your distro's Vim because the home-compiled one will reside before it in the $PATH: in /usr/local/bin (the default) if you have system administration rights, and in ~/bin (which can be set by an additional configure argument) otherwise.

Best regards,
Tony.
