### ISSUE TITLE
window-local option not copied from last window where buffer was displayed

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#4978]
**Describe the bug**

Sometimes, the local value of a window-local option is not copied from the last window where the buffer was displayed.

**To Reproduce**

Run this shell command:

    $ vim -Nu NONE +'sil pu=repeat(\"foo\tbar\n\", 3)|setl list|wincmd w|b x' -O x y

In the right window:

   - the `'list'` option is not set (`:echo &l:list` is 0)
   - the end of lines are not displayed with a dollar character
   - the tab characters are not displayed with `^I`

**Expected behavior**

I would expect that in the right window:

   - the `'list'` option is set to `1`
   - the end of lines are displayed with a dollar character
   - the tab characters are displayed with `^I`

because, according to `:h local-options`, Vim should have remembered that the `x` buffer was displayed in the left window, and in that window the `'list'` option is set to `1`.
Which is what happens when I run this similar shell command:

    $ vim -Nu NONE +'sil pu=repeat(\"foo\tbar\n\", 3)|setl list|bo vnew|b x' x

**Screenshots**

`'list'` is not remembered in the first command (unexpected):

![gif1](https://user-images.githubusercontent.com/8505073/65547341-98aa8800-df19-11e9-9085-ce1b592323c1.gif)

`'list'` is remembered in the second command (expected):

![gif2](https://user-images.githubusercontent.com/8505073/65547352-9f38ff80-df19-11e9-944b-d5be4f18edf1.gif)

**Environment**

 - Vim version: 8.1  Included patches: 1-2071
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

I know that `:h local-options` says:

> When editing a buffer that has been edited before, the options from the window
> that was last **closed** are used again.

So one could argue that `'list'` is not set to 1 in the right window, because the left window has not been closed.

However, the issue persists even if the left window is closed:

    $ vim -Nu NONE +'sil pu=repeat(\"foo\tbar\n\", 3)|setl list|w|close|b x' -O x y

Besides, I don't think closing the window is a requirement anymore, at least not since 25782a7ff4755daf16c2e1cb5e5f826b13b672ce.

---

This is not the same issue as #4976.
In the latter, some window-local options are correctly set, but have no visible effect.
In the current issue, no window-local option is correctly set in the second window when Vim is started with `-O`.

**Comment by nyngwang** [comment]
@lacygoill Did you get an answer when you closed this thread? I'm interested in your conclusion. Thanks!

**Comment by lacygoill** [comment]
Sorry, I don't remember.  Let me re-open the issue.

**Comment by zeertzjq** [comment]
There is something interesting here. With `vim --clean -O x y`, the alternate buffer of the right window is set to buffer `x`. Likewise, with `vim --clean -O x y z`, the alternate buffer of the middle and right windows are both set to buffer `x`. I'm not sure if anyone is relying on this behavior, as fixing this issue may require changing this behavior.
