### ISSUE TITLE
Some registers are absent in some command's descriptions

### ISSUE THREAD

**Issue by lkintact** [vim/vim#4979]
This is a (numbered) list obtained with `:lhelpgrep CTRL-R.*a-z`:

 1) cmdline.txt|132 col 1| CTRL-R `{0-9a-z"%#:-=.}`					*c_CTRL-R* *c_<C-R>*
 2) cmdline.txt|194 col 1| CTRL-R CTRL-R `{0-9a-z"%#:-=. CTRL-F CTRL-P CTRL-W CTRL-A CTRL-L}`
 3) cmdline.txt|195 col 1| CTRL-R CTRL-O `{0-9a-z"%#:-=. CTRL-F CTRL-P CTRL-W CTRL-A CTRL-L}`
 4) index.txt|76 col 4| |i_CTRL-R|	CTRL-R `{0-9a-z"%#*:=}`
 5) index.txt|78 col 4| |i_CTRL-R_CTRL-R| CTRL-R CTRL-R `{0-9a-z"%#*:=}`
 6) index.txt|80 col 4| |i_CTRL-R_CTRL-O| CTRL-R CTRL-O `{0-9a-z"%#*:=}`
 7) index.txt|83 col 4| |i_CTRL-R_CTRL-P| CTRL-R CTRL-P `{0-9a-z"%#*:=}`
 8) insert.txt|109 col 1| CTRL-R `{0-9a-z"%#*+:.-=}`					*i_CTRL-R*
 9) insert.txt|146 col 1| CTRL-R CTRL-R `{0-9a-z"%#*+/:.-=}`			*i_CTRL-R_CTRL-R*
10) insert.txt|158 col 1| CTRL-R CTRL-O `{0-9a-z"%#*+/:.-=}`			*i_CTRL-R_CTRL-O*
11) insert.txt|167 col 1| CTRL-R CTRL-P `{0-9a-z"%#*+/:.-=}`			*i_CTRL-R_CTRL-P*
12) quickref.txt|294 col 4| |i_CTRL-R|	CTRL-R `{0-9a-z%#:.-="}`  insert the contents of a register
13) quickref.txt|1080 col 4| |c_CTRL-R|	CTRL-R `{0-9a-z"%#:-=}`
14) vi_diff.txt|706 col 1| CTRL-R `{0-9a-z..}` can be used to insert the contents of a register.

Only lines 9, 10 and 11 seem to include all the registers. In other lines (with the exception of line 14 with the ellipsis) some of the registers (`+`,  `/`, `.` and `-`) are absent. 

Vim: https://github.com/vim/vim-win32-installer/releases/download/v8.1.2071/gvim_8.1.2071_x86_signed.zip

**Comment by chrisbra** [comment]
Perhaps its better to have a single tag `{register}` tags, perhaps in intro.txt right beyond the `{motion}` tag and then always refer to `{register}` in the various places.

**Comment by brammool** [comment]
I used {register} in the mentioned places.
