### ISSUE TITLE
remove angle bracket when "set wrap"

### ISSUE THREAD

**Issue by yinrong** [vim/vim#4981]
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Describe the bug**
As shown in the below scrrenshot, vim is adding "<" (angle bracket) when "set wrap", which makes it difficult to copy text.

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/4221569/65596627-d49d2600-dfc9-11e9-9b2d-efe6021e657d.png)

**Environment (please complete the following information):**

remote:
by ssh
 - VIM - Vi IMproved 7.4
 - OS: 3.18.6-2.el7.centos.x86_64

local:

 - OS: ubuntu 16.04
 - Terminal: GNOME Terminal

**Additional context**

**Comment by chrisbra** [comment]
Are you talking about `>` at the end of a line, when there is a double-width char that does not fit? Why are you not copying using the clipboard?

**Comment by tonymec** [comment]
Indeed, to copy text to the clipboard by Vim means, visually select what you want to copy, then use `"+y` or (in gvim) Edit→Copy. These "filler halfwidth characters" won't be copied.

**Comment by Shane-XB-Qian** [comment]
aha.. looks this is not a problem .. 
i guess you used to use 'mouse' to select & copy, right ? otherwise, how came that '>' copied, 
if so, just 'cat' and/or 'less' it first, problem solved ! :) :) :)
