### ISSUE TITLE
8.1.2079 Test failures on macOS 10.14.6

### ISSUE THREAD

**Issue by chdiza** [vim/vim#4983]
Vim 8.1.2079 builds on macOS 10.14.6, but `make test` fails:

```
Failures:
	From test_alot.vim:
	Found errors in Test_state():
	function RunTheTest[40]..Test_state[38]..WaitForAssert[2]..<SNR>10_WaitForCommon[11]..<lambda>10102 line 1: Pattern 'state: aSc; mode: i' does not match 'state: mSc; mode: n\[  occurs 38 times]4,3           All'

TEST FAILURE
make[2]: *** [report] Error 1
make[1]: *** [scripttests] Error 2
make: *** [test] Error 2
```

**Comment by brammool** [comment]
> Vim 8.1.2079 builds on macOS 10.14.6, but `make test` fails:
> 
> ```
> Failures:
> 	From test_alot.vim:
> 	Found errors in Test_state():
> 	function RunTheTest[40]..Test_state[38]..WaitForAssert[2]..<SNR>10_WaitForCommon[11]..<lambda>10102 line 1: Pattern 'state: aSc; mode: i' does not match 'state: mSc; mode: n\[  occurs 38 times]4,3           All'

Looks like the state didn't get updated (yet).  Must be some race
condition.  It works OK on Travis.


Can you try a few things:

- Set 'complete' to "." to avoid making search slow:
   	map ;; gg
   +	set complete=.
	func RunTimer()


- Increase the timer delay:

	func RunTimer()
  -	  call timer_start(10, {id -> execute('let g:state = state()') .. execute('let g:mode = mode()')})
  +	  call timer_start(50, {id -> execute('let g:state = state()') .. execute('let g:mode = mode()')})
	endfunc

- Increas the delay for the output:

         call term_sendkeys(buf, ":call RunTimer()\<CR>Got\<C-N>")
   -     call term_wait(buf, 50)
   +     call term_wait(buf, 200)
         call term_sendkeys(buf, "\<Esc>")

Does it always fails with this error, or sometimes with another one?


-- 
GUARD #2:  Wait a minute -- supposing two swallows carried it together?
GUARD #1:  No, they'd have to have it on a line.
GUARD #2:  Well, simple!  They'd just use a standard creeper!
GUARD #1:  What, held under the dorsal guiding feathers?
GUARD #2:  Well, why not?
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chdiza** [comment]
I will try, but I don't know where I'm supposed to make those modifications.  There are no such lines in `test_alot.vim`, which is the file referenced by the error message.

**Comment by brammool** [comment]
Test_state() is in testdir/test_functions.vim

**Comment by chdiza** [comment]
> Does it always fails with this error, or sometimes with another one?

As far as I can tell, it's always with that particular error.  The same happens on macOS 10.13.6 too.

I made the suggested modifications, and the test failures have disappeared.

**Comment by brammool** [comment]
> > Does it always fails with this error, or sometimes with another one?
> 
> As far as I can tell, it's always with that particular error.  The same happens on macOS 10.13.6 too.
> 
> I made the suggested modifications, and the test failures have disappeared.

Good, so it is a timing problem.

Do I understand you included all three changes?  Can you please try each
one separately?  I rather not add delays that aren't needed.

-- 
Individualists unite!

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chdiza** [comment]
I tried each one separately.  Neither of the first two changes fixed anything.  The third one caused the failure to disappear.

(Note that I only made one trial run each.)

**Comment by chdiza** [comment]
(My first report of success was after making all three changes at the same time.)
