### ISSUE TITLE
GTypeDebugFlags: ‘GTimeVal’ is deprecated: Use 'GDateTime', Linux install

### ISSUE THREAD

**Issue by wllclngn** [vim/vim#4987]
While installing Vim on Linux through GNOME Terminal (having downloaded the Github repository) this error appears: "warning: ‘GTimeVal’ is deprecated: Use 'GDateTime' instead [-Wdeprecated-declarations]".

The error seems to go into an infinite loop of attempting to continue the install, however it is always halted. 

Reproducing:

1) cd vim/src
2)  ./configure
3) sudo make install

Expected behavior:

gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/harfbuzz -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/atk-1.0 -pthread    -g -O2 -D_REENTRANT  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/autocmd.o autocmd.c
In file included from /usr/include/gtk-2.0/gtk/gtkobject.h:37,
                 from /usr/include/gtk-2.0/gtk/gtkwidget.h:36,
                 from beval.h:17,
                 from vim.h:1807,
                 from autocmd.c:14:
/usr/include/gtk-2.0/gtk/gtktypeutils.h:236:1: warning: ‘GTypeDebugFlags’ is deprecated [-Wdeprecated-declarations]
  236 | void            gtk_type_init   (GTypeDebugFlags    debug_flags);
      | ^~~~
In file included from /usr/include/glib-2.0/gobject/gobject.h:24,
                 from /usr/include/glib-2.0/gobject/gbinding.h:29,
                 from /usr/include/glib-2.0/glib-object.h:23,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from /usr/include/gtk-2.0/gdk/gdkapplaunchcontext.h:30,
                 from /usr/include/gtk-2.0/gdk/gdk.h:32,
                 from /usr/include/gtk-2.0/gtk/gtkwidget.h:34,
                 from beval.h:17,
                 from vim.h:1807,
                 from autocmd.c:14:
/usr/include/glib-2.0/gobject/gtype.h:679:1: note: declared here
  679 | {
      | ^
In file included from /usr/include/gtk-2.0/gtk/gtktoolitem.h:31,
                 from /usr/include/gtk-2.0/gtk/gtktoolbutton.h:30,
                 from /usr/include/gtk-2.0/gtk/gtkmenutoolbutton.h:30,
                 from /usr/include/gtk-2.0/gtk/gtk.h:126,
                 from gui.h:29,
                 from structs.h:105,
                 from vim.h:1811,
                 from autocmd.c:14:
/usr/include/gtk-2.0/gtk/gtktooltips.h:73:3: warning: ‘GTimeVal’ is deprecated: Use 'GDateTime' instead [-Wdeprecated-declarations]
   73 |   GTimeVal last_popdown;
      |   ^~~~~~~~
In file included from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/glib-2.0/gobject/gbinding.h:28,
                 from /usr/include/glib-2.0/glib-object.h:23,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from /usr/include/gtk-2.0/gdk/gdkapplaunchcontext.h:30,
                 from /usr/include/gtk-2.0/gdk/gdk.h:32,
                 from /usr/include/gtk-2.0/gtk/gtkwidget.h:34,
                 from beval.h:17,
                 from vim.h:1807,
                 from autocmd.c:14:
/usr/include/glib-2.0/glib/gtypes.h:551:8: note: declared here
  551 | struct _GTimeVal
      |        ^~~~~~~~~

Vim: 8.1.1991 [Attempting to install most recent version.]
OS: Linux 5.3.1
Terminal: GNOME Terminal

Unfortunately I cannot find "GTimeVal" in Vim's repository files. Also, I thought this might help others in the future. If this has already been solved, etal, apologies.

**Comment by k-takata** [comment]
> Unfortunately I cannot find "GTimeVal" in Vim's repository files.

It is used in GTK 2 (gtktooltips.h) as the error message says. Which linux distribution do you use?
I think it's better to report to the distributor.
(Or using GTK 3 might be another option.)

**Comment by chrisbra** [comment]
and what is the version of the gtk2 libraries you are using?

**Comment by wllclngn** [comment]
gtk2: 2.24.32-1
Distro: Arch Linux

"(Or using GTK 3 might be another option.)": Unfortunately GTK3 is used currently, but I won't leave gtk2 due to convoluted circumstances involving a self-created theme and Qt applications related to Arch usage.

This appears to be a Vim specific error while installing. I've had it for some time. I'd prefer not to have to go to the Arch forums, hah. They're not... qu'est-ce que c'est... ah, kind.

**Comment by chrisbra** [comment]
So could you provide a PR that fixes this for the later gtk2 versions? Is there actually still some development in gtk2?

**Comment by wllclngn** [comment]
What's the best course of action? I could try to contact the gtk2 maintainer. Let me know. Sorry, I'm not super into development at this point, so I just simply don't know.

**Comment by wllclngn** [comment]
Solved!

Within the following files, simply put ":%s/GTimeVal/GDateTime/g" in Normal Mode (w/out quotes, obviously); sudo will be required. 

/usr/include/glib-2.0/glib/gtypes.h
/usr/include/gtk-2.0/gtk/gtktooltips.h

While there are more "GTimeVal" variables in files throughout the GTK2 file structure, Vim's install does not seem to touch any more than the preceding two files.

I will file a bug report w/ GTK2 on Arch's repo.

**Comment by tonymec** [comment]
hm, IIUC you will have to repeat that change every time a GTK2 update arrives from your Linux distro, until and unless the same change is taken up upstream?

Best regards,
Tony.

**Comment by wllclngn** [comment]
It would appear there are more than 1.5K bug reports on the GTK2 repo for Arch. So, maybe it was best I posted here. Hopefully this helps someone in the future.

**Comment by jlittlenz** [comment]
> Within the following files, simply put ":%s/GTimeVal/GDateTime/g" in Normal Mode (w/out quotes, obviously); sudo will be required.
> 
> /usr/include/glib-2.0/glib/gtypes.h
> /usr/include/gtk-2.0/gtk/gtktooltips.h

This did not work at all for me; just as many warnings, and errors "unknown type name ‘GTimeVal'" in 6 vim sources.  There's another deprecation for GTypeDebugFlags, too.

Using -DGTK_DISABLE_DEPRECATED doesn't work either.  -Wno-deprecated-declarations does.  

This is glib deprecating something that GTK 2 has used; it's not a change in GTK 2.  I doubt if it will be fixed in GTK 2.

**Comment by wllclngn** [comment]
@jlittlenz For some reason it initially worked. I just did a fresh install of Arch Linux, and GTK2 was unable to be used for GVim install from sources. I changed the value to (as previously suggested) "--enable-gui=gtk3" and it worked. Hope this helps.

**Comment by chrisbra** [comment]
I have been seriously annoyed by those warning messages before and especially yesterday. 
And it slows down compiling (at least that was my feeling). I know I can set CFLAGS to include `-Wno-deprecated-declarations`, but how about making the GTK3 gui the default and do not prefer the older GTK2 version (just in case no `--enable-gui` argument has been given to configure)?

Something like this patch:

https://github.com/vim/vim/compare/master...chrisbra:gtk3_before_gtk2.patch

Thanks,
Christian

**Comment by chrisbra** [comment]
@brammool would it be reasonable, to switch from GTK2 to GTK3 as default when no argument is given to configure?

**Comment by brammool** [comment]
That's hard for me to say.  There were some problems reported for GTK3, I'm not sure how many users still run into them.  GTK2 has been quite stable.  It smells like "the old version is deprecated, the new version isn't fully working yet".

**Comment by wllclngn** [comment]
@chrisbra I can reopen this if my solution's no longer working.
