### ISSUE TITLE
Certain Vim builds of the latest Windows release are not available

### ISSUE THREAD

**Issue by lkintact** [vim/vim#4995]
Specifically, 
1. https://github.com/vim/vim-win32-installer/releases/download/v8.1.2099/gvim_8.1.2099_x64.exe,
2. https://github.com/vim/vim-win32-installer/releases/download/v8.1.2099/gvim_8.1.2099_x86.exe,
3. https://github.com/vim/vim-win32-installer/releases/download/v8.1.2099/gvim_8.1.2099_x86.zip
and
4. https://github.com/vim/vim-win32-installer/releases/download/v8.1.2099/gvim_8.1.2099_x86_pdb.zip
yeild a 404 Not Found page (1, 2) or just a "Not Found" message (3, 4).

**Comment by chrisbra** [comment]
Yes, if you look at the Build status from the main page https://ci.appveyor.com/project/chrisbra/vim-win32-installer you see that the x86 build failed: 

> From test_alot.vim:
> Found errors in Test_popup_and_window_resize():
> function RunTheTest[40]..Test_popup_and_window_resize[24]..WaitForAssert[2]..<SNR>9_WaitForCommon[11]..<lambda>10076 line 1: Expected '' but got '!                '
> function RunTheTest[40]..Test_popup_and_window_resize[27]..WaitForAssert[2]..<SNR>9_WaitForCommon[11]..<lambda>10077 line 1: Pattern '^!\\s*$' does not match '-- Command-line completion (^V^N^P) match 1 of 563'
> TEST FAILURE 
> NMAKE : fatal error U1077: 'if' : return code '0x1'
> Stop

This means, the build artifacts won't be uploaded to github. That can happen and is totally normal. If I notice and I am available, I usually rebuild the commit if the test is flaky and then the other artifacts will be uploaded as well. After that I might upload the signed binaries. But all that requires manual effort.

I will now re-build the failed commit in appveyor. That should fix it.

**Comment by chrisbra** [comment]
the zip files are there yet. However it looks like the installer script failed:

> C:\projects\vim-win32-installer\vim\nsis>if /I "x86" == "x64" ("C:\Program Files (x86)\NSIS\makensis" /DVIMRT=..\runtime /DGETTEXT=c: /DWIN64=1 /DPATCHLEVEL=2099 gvim.nsi "/XOutFile ..\..\gvim_8.1.2099_x86.exe" )  else ("C:\Program Files (x86)\NSIS\makensis" /DVIMRT=..\runtime /DGETTEXT=c: /DPATCHLEVEL=2099  gvim.nsi "/XOutFile ..\..\gvim_8.1.2099_x86.exe" ) 
> Command line defined: "VIMRT=..\runtime"
> Command line defined: "GETTEXT=c:"
> Command line defined: "PATCHLEVEL=2099"
> Processing config: C:\Program Files (x86)\NSIS\nsisconf.nsh
> Processing script file: "gvim.nsi" (ACP)
> File: "..\src\uninstallw32.exe" -> no files found.
> Usage: File [/nonfatal] [/a] ([/r] [/x filespec [...]] filespec [...] |
>    /oname=outfile one_file_only)
> Error in script "gvim.nsi" on line 344 -- aborting creation process

That is here: https://github.com/vim/vim/blob/master/nsis/gvim.nsi#L344

This looks like a problem with patch 30e8e73506e4522ef4aebf7d525c0e6ffe8805fd

CC @brammool @k-takata

**Comment by k-takata** [comment]
I created a PR for this: https://github.com/vim/vim-win32-installer/pull/147.

**Comment by chrisbra** [comment]
Thanks! I am closing this. With the next patches, it should build now again.
