### ISSUE TITLE
inittab: incorrect syntax highlighting

### ISSUE THREAD

**Issue by a-biardi** [vim/vim#5001]
**Describe the bug**
I'm sure everybody else has moved on, but I'm still using sysvinit and /etc/inittab; anyway, vim will highlight as errors any entries whose "process" field doesn't start with an absolute path.

**To Reproduce**
Save the following as /tmp/inittab:
c1:12345:respawn:agetty 38400 tty1 linux --noclear
Edit with vim (syntax highlight enabled). The portion from "agetty" to end of line is marked red because it does not start with a slash.

**Expected behavior**
Entry shouldn't be marked red. According to man (5) inittab (at least for sysvinit), there is no requirement that the path be absolute (indeed, the process might even be started via /etc/initscript).

**Environment (please complete the following information):**
 - Vim version  7.4
 - OS: Slackware 14.2
 - Terminal: linux (console)

**Additional context**
I originally wrote to the maintainer mentioned in inittab.vim, but he replied he's no longer involved; perhaps his contact should be removed from the file.

**Comment by chrisbra** [comment]
Is the syntax file the same for latest [master](https://github.com/vim/vim/blob/master/runtime/syntax/inittab.vim)? If it is unmaintained, would you volunteer to maintain it instead?

**Comment by brammool** [comment]
Fixed by including #5218

**Comment by a-biardi** [comment]
On Mon, 30 Sep 2019 03:57:03 -0700, Christian Brabandt
<notifications@github.com> wrote:

> Is the syntax file the same for latest
> [master](https://github.com/vim/vim/blob/master/runtime/syntax/inittab.vim)?
> If it is unmaintained, would you volunteer to maintain it instead?
> 

Christian,

Sorry for not following up on this earlier, I saw a commit today and it
suddently just came back to memory. If the file is still unmaintained,
yes, I can volunteer to adopt it.

Andrea.

**Comment by brammool** [comment]
Donovan Keohane volunteered to maintain it.  Please chat with Donovan if you see further ways to improve this syntax.
