### ISSUE TITLE
`<C-C>` only closes one popup when there are several and its callback is not triggered

### ISSUE THREAD

**Issue by liuchengxu** [vim/vim#5008]
**Describe the bug**

When there are more than one popups at the same time, `<C-C>` only close one popup and the others persist. What's more, the callback of that closed popup is not triggered.

**To Reproduce**

mini.vim:

```vim
set cpo&vim
function! s:callback() abort
  echom "callback get triggered!"
  call popup_hide(s:input_winid)
endfunction

function! s:popup_filter(winid, key) abort
  echom "key: ".a:key
endfunction

let s:display_winid = popup_create([], #{
      \ wrap: v:false,
      \ mapping: v:false,
      \ cursorline: 0,
      \ filter: function('s:popup_filter'),
      \ callback: function('s:callback'),
      \ scrollbar: 0,
      \ line: 10,
      \ col: 20,
      \ minwidth: 30,
      \ maxwidth: 30,
      \ maxheight: 10,
      \ minheight: 10,
      \ })

let s:input_winid = popup_create([], #{
      \ line: 5,
      \ col: 10,
      \ minwidth: 15,
      \ maxwidth: 15,
      \ maxheight: 5,
      \ minheight: 5,
      \ })
```

Detailed steps to reproduce the behavior:
1. Run `vim --clean mini.vim`
3. Type `:source %`
4. Press `<C-C>`

**Expected behavior**
The callback of the closed popup should be triggered and the upper popup should be hided.

**Screenshots**
If applicable, copy/paste the text or add screenshots to help explain your problem.

<img width="1680" alt="屏幕快照 2019-10-02 下午9 59 07" src="https://user-images.githubusercontent.com/8850248/66050506-ebaabd80-e55f-11e9-919e-f1a2156acce8.png">

<img width="1680" alt="屏幕快照 2019-10-02 下午10 00 05" src="https://user-images.githubusercontent.com/8850248/66050557-04b36e80-e560-11e9-82ff-de677c51de2f.png">

**Environment (please complete the following information):**
 - Vim version: 8.1-2108
 - OS: macOS 10.14
 - Terminal: kitty

**Additional context**
I don't know if `<C-C>` should close all the popups if there is more than one, but at least the one closed should trigger its callback.

**Comment by bfrg** [comment]
If you add a filter to the second window, CTRL-C will close both popup windows. For example:
```vim
let s:input_winid = popup_create([], #{
      \ line: 5,
      \ col: 10,
      \ minwidth: 15,
      \ maxwidth: 15,
      \ maxheight: 5,
      \ minheight: 5,
      \ filter: {... -> '' }
      \ })
```

**Comment by liuchengxu** [comment]
What if the second window actually doesn't have to have a filter, it's merely used for a display. The semantic doesn't make much sense. And still the callback is not triggered, that's not expected.

**Comment by liuchengxu** [comment]
@bfrg Adding a filter won't close all if you have 3 popups.

```vim
set cpo&vim
function! s:callback() abort
  echom "callback get triggered!"
  call popup_hide(s:input_winid)
endfunction

function! s:popup_filter_display(winid, key) abort
  echom "display key: ".a:key
endfunction

function! s:popup_filter_input(winid, key) abort
  echom "input key: ".a:key
endfunction

function! s:popup_filter_indicator(winid, key) abort
  echom "indicator key: ".a:key
endfunction

let s:display_winid = popup_create([], #{
      \ wrap: v:false,
      \ mapping: v:false,
      \ cursorline: 0,
      \ filter: function('s:popup_filter_display'),
      \ callback: function('s:callback'),
      \ scrollbar: 0,
      \ line: 10,
      \ col: 20,
      \ minwidth: 30,
      \ maxwidth: 30,
      \ maxheight: 10,
      \ minheight: 10,
      \ })

let s:input_winid = popup_create([], #{
      \ line: 5,
      \ col: 10,
      \ filter: function('s:popup_filter_input'),
      \ minwidth: 15,
      \ maxwidth: 15,
      \ maxheight: 5,
      \ minheight: 5,
      \ })

let s:indicator_winid = popup_create([], #{
      \ line: 30,
      \ col: 50,
      \ filter: function('s:popup_filter_indicator'),
      \ minwidth: 20,
      \ maxwidth: 20,
      \ maxheight: 5,
      \ minheight: 5,
      \ })

```

**Comment by brammool** [comment]
> **Describe the bug**
> 
> When there are more than one popups at the same time, `<C-C>` only close one
> popup and the others persist. What's more, the callback of that closed popup
> is not triggered.
> 
> **To Reproduce**
> 
> mini.vim:
> 
> ```vim
> set cpo&vim
> function! s:callback() abort
>   echom "callback get triggered!"
>   call popup_hide(s:input_winid)
> endfunction
> 
> function! s:popup_filter(winid, key) abort
>   echom "key: ".a:key
> endfunction
> 
> let s:display_winid = popup_create([], #{
>       \ wrap: v:false,
>       \ mapping: v:false,
>       \ cursorline: 0,
>       \ filter: function('s:popup_filter'),
>       \ callback: function('s:callback'),
>       \ scrollbar: 0,
>       \ line: 10,
>       \ col: 20,
>       \ minwidth: 30,
>       \ maxwidth: 30,
>       \ maxheight: 10,
>       \ minheight: 10,
>       \ })
> 
> let s:input_winid = popup_create([], #{
>       \ line: 5,
>       \ col: 10,
>       \ minwidth: 15,
>       \ maxwidth: 15,
>       \ maxheight: 5,
>       \ minheight: 5,
>       \ })
> ```
> 
> Detailed steps to reproduce the behavior:
> 1. Run `vim --clean mini.vim` (or `gvim --clean`, etc.)
> 3. Type `:source %`
> 4. Press `<C-C>`
> 
> **Expected behavior**
> The callback of the closed popup should be triggered and the upper popup should be hided.
> 
> **Screenshots**
> If applicable, copy/paste the text or add screenshots to help explain your problem.
> 
> <img width="1680" alt="屏幕快照 2019-10-02 下午9 59 07" src="https://user-images.githubusercontent.com/8850248/66050506-ebaabd80-e55f-11e9-919e-f1a2156acce8.png">
> 
> <img width="1680" alt="屏幕快照 2019-10-02 下午10 00 05" src="https://user-images.githubusercontent.com/8850248/66050557-04b36e80-e560-11e9-82ff-de677c51de2f.png">
> 
> **Environment (please complete the following information):**
>  - Vim version: 8.1-2108
>  - OS: macOS 10.14
>  - Terminal: alacritty
> 
> **Additional context**
> I don't know if `<C-C>` should close all the popups if there is more than one, but at least the one closed should trigger its callback.

In my opinion CTRL-C should only close the top popup window.  Think of a dialog
that grabs all keys that you want to close, but there are other informational
popups that you want to keep.

I think it's OK that you have to type CTRL-C for each popup.

-- 
There are 10 kinds of people: Those who understand binary and those who don't.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by liuchengxu** [comment]
>In my opinion CTRL-C should only close the top popup window.

I'm ok with that. But the top one that could be closed by the first `<C-C>` did not trigger its callback, is that expected?

No callback is triggered.

```vim
set cpo&vim

function! s:callback_display() abort
  echom "display callback get triggered!"
  call popup_hide(s:input_winid)
  call popup_hide(s:input_winid)
  call popup_hide(s:indicator_winid)
endfunction

function! s:callback_input() abort
  echom "input callback get triggered!"
  call popup_hide(s:input_winid)
  call popup_hide(s:input_winid)
  call popup_hide(s:indicator_winid)
endfunction

function! s:callback_indicator() abort
  echom "indicator callback get triggered!"
  call popup_hide(s:input_winid)
  call popup_hide(s:input_winid)
  call popup_hide(s:indicator_winid)
endfunction

function! s:popup_filter_display(winid, key) abort
  echom "display key: ".a:key
endfunction

function! s:popup_filter_input(winid, key) abort
  echom "input key: ".a:key
endfunction

function! s:popup_filter_indicator(winid, key) abort
  echom "indicator key: ".a:key
endfunction

let s:display_winid = popup_create([], #{
      \ wrap: v:false,
      \ mapping: v:false,
      \ cursorline: 0,
      \ filter: function('s:popup_filter_display'),
      \ callback: function('s:callback_display'),
      \ scrollbar: 0,
      \ line: 10,
      \ col: 20,
      \ minwidth: 30,
      \ maxwidth: 30,
      \ maxheight: 10,
      \ minheight: 10,
      \ })

let s:input_winid = popup_create([], #{
      \ line: 5,
      \ col: 10,
      \ filter: function('s:popup_filter_input'),
      \ callback: function('s:callback_input'),
      \ minwidth: 15,
      \ maxwidth: 15,
      \ maxheight: 5,
      \ minheight: 5,
      \ })

let s:indicator_winid = popup_create([], #{
      \ line: 30,
      \ col: 50,
      \ filter: function('s:popup_filter_indicator'),
      \ callback: function('s:callback_indicator'),
      \ minwidth: 20,
      \ maxwidth: 20,
      \ maxheight: 5,
      \ minheight: 5,
      \ })
```

What's more, there is no way/doc to know which one is the top popup if there are multiple popups.

**Comment by liuchengxu** [comment]
>In my opinion CTRL-C should only close the top popup window.

I'm ok with that. But the top one that could be closed by the first `<C-C>` did not trigger its callback, is that expected?

```vim
set cpo&vim

function! s:callback_display() abort
  echom "display callback get triggered!"
  call popup_hide(s:input_winid)
  call popup_hide(s:input_winid)
  call popup_hide(s:indicator_winid)
endfunction

function! s:callback_input() abort
  echom "input callback get triggered!"
  call popup_hide(s:input_winid)
  call popup_hide(s:input_winid)
  call popup_hide(s:indicator_winid)
endfunction

function! s:callback_indicator() abort
  echom "indicator callback get triggered!"
  call popup_hide(s:input_winid)
  call popup_hide(s:input_winid)
  call popup_hide(s:indicator_winid)
endfunction

function! s:popup_filter_display(winid, key) abort
  echom "display key: ".a:key
endfunction

function! s:popup_filter_input(winid, key) abort
  echom "input key: ".a:key
endfunction

function! s:popup_filter_indicator(winid, key) abort
  echom "indicator key: ".a:key
endfunction

let s:display_winid = popup_create([], #{
      \ wrap: v:false,
      \ mapping: v:false,
      \ cursorline: 0,
      \ filter: function('s:popup_filter_display'),
      \ callback: function('s:callback_display'),
      \ scrollbar: 0,
      \ line: 10,
      \ col: 20,
      \ minwidth: 30,
      \ maxwidth: 30,
      \ maxheight: 10,
      \ minheight: 10,
      \ })

let s:input_winid = popup_create([], #{
      \ line: 5,
      \ col: 10,
      \ filter: function('s:popup_filter_input'),
      \ callback: function('s:callback_input'),
      \ minwidth: 15,
      \ maxwidth: 15,
      \ maxheight: 5,
      \ minheight: 5,
      \ })

let s:indicator_winid = popup_create([], #{
      \ line: 30,
      \ col: 50,
      \ filter: function('s:popup_filter_indicator'),
      \ callback: function('s:callback_indicator'),
      \ minwidth: 20,
      \ maxwidth: 20,
      \ maxheight: 5,
      \ minheight: 5,
      \ })
```

What's more, there is no way/doc to know which one is the top popup if there are multiple popups.

**Comment by bfrg** [comment]
@brammool But why does a single CTRL-C always close two popup windows at once, even when both windows have different `zindex`?

Here is a smaller `vimrc`. I have added empty `popup-filters` since otherwise CTRL-C won't do anything:
```vim
function! s:popup_cb(winid, result) abort
    echom 'callback result: ' .. a:result
endfunction

let s:input_winid = popup_create('input window', #{
        \ line: 5,
        \ minwidth: 15,
        \ minheight: 3,
        \ filter: {... -> ''},
        \ zindex: 1000,
        \ })

let s:display_winid = popup_create('display window', #{
        \ line: 10,
        \ minwidth: 20,
        \ minheight: 3,
        \ filter: {... -> '' },
        \ callback: function('s:popup_cb'),
        \ zindex: 1001,
        \ })

let s:indicator_winid = popup_create('indicator window', #{
        \ line: 15,
        \ minwidth: 25,
        \ minheight: 3,
        \ filter: {... -> '' },
        \ zindex: 1002,
        \ })
```
When all three popup windows have the same `zindex` the last two defined will be closed first, then a second CTRL-C will close the first one.

@liuchengxu you can give a priority to each popup window through the `zindex`.

**Comment by liuchengxu** [comment]
@bfrg Thanks for the `zindex` info, but the problem stays the same(two closed when there are three and no callback is triggered) even when you give each popup a different `zindex`.

**Comment by brammool** [comment]
> @brammool But why does a single CTRL-C always close two popup windows at
> once, even when both windows have different `zindex`?
> 
> Here is a smaller `vimrc`. I have added empty `popup-filters` since otherwise
> CTRL-C won't do anything:

That looks like a mistake.  Turns out that got_int causes another loop through
the input function.  I'll fix that.

-- 
It's not hard to meet expenses, they're everywhere.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
> > In my opinion CTRL-C should only close the top popup window.
> 
> I'm ok with that. But the top one that could be closed by the first
> `<C-C>` did not trigger its callback, is that expected?

You added "abort" to all the functions, and CTRL-C probably causes
them to abort.  There is a test for CTRL-C invoking the callback, thus
it should work.

> What's more, there is no way/doc to know which one is the top popup if
> there are multiple popups. 

If you care you can set the zindex.  Otherwise it depends on the order
they are created (last one created goes on top of older ones).  But that
is obviously a bit unpredictable.

-- 
Did you ever stop to think...  and forget to start again?
                                  -- Steven Wright

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by liuchengxu** [comment]
> There is a test for CTRL-C invoking the callback, thus it should work.

@brammool Could you please point this test out? I need this to close all the popups I created when seeing CTRL-C, and I now have no idea to get that.

**Comment by bfrg** [comment]
@liuchengxu I think you're looking for [this](https://github.com/vim/vim/blob/master/src/testdir/test_popupwin.vim#L1227-L1255). There's also a second test below it.

I can't reproduce it for some reasons when I run `vim --clean popup.vim -c "source %"` with:
```vim
" popup.vim
function! s:popup_cb(winid, result)
    let g:result = a:result
    echomsg 'callback result: ' .. a:result
endfunction

let winid = popup_dialog('input window', #{
        \ filter: 'popup_filter_yesno',
        \ callback: function('s:popup_cb')
        \ })
```

**Comment by bfrg** [comment]
Running `call feedkeys("\<c-c>", 'xt')` will invoke the callback but not when I hit CTRL-C on my keyboard.

**Comment by liuchengxu** [comment]
@bfrg Same to me. The callback won't be triggered by hitting CTRL-C.
