### ISSUE TITLE
Calling `appendbufline()` against an empty file will introduce an extra unexpected line

### ISSUE THREAD

**Issue by liuchengxu** [vim/vim#5016]
**Describe the bug**
Calling `appendbufline()` against an empty file will introduce an extra unexpected line.

**To Reproduce**
Detailed steps to reproduce the behavior:

Case 1:

1. Run `vim --clean -c 'set number' tmp.vim`
2. `:call appendbufline('', '$', [1, 2])`

<img width="1680" alt="屏幕快照 2019-10-04 下午8 58 30" src="https://user-images.githubusercontent.com/8850248/66209514-14f75500-e6ea-11e9-88ef-953f92d7710b.png">

Line 1 is the unwanted blank line.

Case 2:

1. Run `vim --clean -c 'set number' tmp.vim`
2. `:call appendbufline('', 0, [1, 2])`

<img width="1680" alt="屏幕快照 2019-10-04 下午8 59 38" src="https://user-images.githubusercontent.com/8850248/66209430-e8dbd400-e6e9-11e9-9583-585e45a78d20.png">

Line 3 is the unwanted blank lines.

**Expected behavior**
Don't introduce extra blank line.

**Environment (please complete the following information):**
 - Vim version 8.1-2108
 - OS: Ubuntu 18.04
 - Terminal: GNOME Terminal

**Additional context**

**Comment by brammool** [comment]
An empty buffer consists of one empty line.  If you append, this line is still there.
This has always been this way, plugins normally overwrite the empty line or delete it after appending lines.  We can't change the behavior without breaking that.
