### ISSUE TITLE
Esc remaping doesn't work with "paste" enabled

### ISSUE THREAD

**Issue by ghost** [vim/vim#502]
I tried to remap <Esc> to jk but "set paste" makes some sort of conflict and blocks it.
Other keys combinaisons, without Escape, works fine.

**Comment by chrisbra** [comment]
The whole point of paste mode is to disable mappings among others. See the help `:h 'paste'`. For user questions, please ask the vim-use mailinglist, the issue tracker is the wrong place for that. Closing as invalid.
