### ISSUE TITLE
call win_execute(id, ':call cursor(100, 1)') do not redraw the windows 1002

### ISSUE THREAD

**Issue by wsdjeg** [vim/vim#5022]
the new feature `win_execute` do not redraw the move the screen line.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean` (or `gvim --clean`, etc.)
2. Edit `filename`, the filename has 800 lines
2. run `:20` to move to line 20
4. `:split` and `let id = win_getid()`
5. run `call win_execute(id, ':call cursor(100, 1)')`

but the window 2 screen do not changed, the cursor line of that creen should be able to see.

**Comment by brammool** [comment]
I cannot reproduce, the cursor jumps to line 100 as expected.
Perhaps a step is missing? Before step 5 did you do ":windcmd w" ?
Then the display isn't updated, because scrolling to show the cursor only happens for the current window, that is intentional.
You can use call win_execute(id, 'call cursor(100, 1)|normal zz')
I notice the ruler isn't updated then..

**Comment by wsdjeg** [comment]
what I need is to scroll a window without to jumto that window, this can be done in neovim's python mode, we can use buffer.col and buffer,line to set the cursor and the creen will be scrolled automatically.

**Comment by chrisbra** [comment]
so use `win_execute()` as suggested.

**Comment by wsdjeg** [comment]
@chrisbra thanks, I am writing compatible plugin for old vim, so how can I do this if my vim do not have this function?

**Comment by wsdjeg** [comment]
@chrisbra I mean, if in lua code, I use:

```
    local w = vim.window(winindex)
    w.line = pos[0]
    w.col = pos[1]
```

then, how can I scroll that windows.

**Comment by chrisbra** [comment]
Yeah, you need 868b7b6712ea4f2232eeeae18c5cbbbddf2ee84d (8.1.1418) for `win_execute()`. If your vim is older, then switch to the window and scroll and switch back. I don't understand how lua helps here, what if your Vim does not have a lua interface compiled in?

**Comment by wsdjeg** [comment]
@chrisbra Thanks, in neovim, when I use lua to change the cursor, the window scrolled automatically, so I just think it should works in vim7 too, but sad, it can not. thanks again.
