### ISSUE TITLE
Migrate vim to python 3

### ISSUE THREAD

**Issue by adudek16** [vim/vim#5028]
This is coming from macvim but may impact other recent deployments of linux since
python 2 will be end of support on Jan 1 2020, seems like a good idea to move to 3.7

https://github.com/macvim-dev/macvim/issues/939

**Comment by k-takata** [comment]
Vim already supports python 3.7. The version of python is selected at the compile time.
If you want to use python 3.7, please ask who build the Vim binary. (or build by yourself.)

**Comment by adudek16** [comment]
What is the current status on support for python 2.7 going forward? Will it be phased out.

**Comment by k-takata** [comment]
Basically Vim tries to keep supporting old platforms as much as possible (even the official support is ended).
E.g. Vim still supports WinXP, GTK 2.2, Ruby 1.8, etc.
So python 2.7 support might remain for a few years.
Who build Vim must consider the security risks of python 2.7 and need to decide whether they link Vim with python 2.7 or not.
