### ISSUE TITLE
gvim -p draws spurious vertical bar in some windows

### ISSUE THREAD

**Issue by marystern** [vim/vim#5030]
Whenever I open any files in gvim (on Ubuntu 18.04.3 LTS 32 bit), some of the windows have a spurious vertical window-dividing line towards the right of the window (see attached image). If I resize to smaller, then larger, it will disappear.

To reproduce the behavior:

gvim -p *.go

(seems to be not in the first tab, but in the second and later?)

**Expected behavior**
no spurious divider should be seen!

**Screenshots**
see attached

**Environment (please complete the following information):**
With latest master (and was the same for a while back too)
ref: commit b189295b72030f00c45c30d3daecf85d457221f8 (HEAD -> master, tag: v8.1.2125, 
![gvim_bug](https://user-images.githubusercontent.com/13821612/66444426-25396800-ea3b-11e9-8171-4a6d7f25a8a1.png)

$ vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct  9 2019 01:48:24)
Included patches: 1-2125
Compiled by x@y
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_any_white
+arabic            +file_in_path      +mouse_urxvt       -tcl
+autocmd           +find_in_path      +mouse_xterm       +termguicolors
+autochdir         +float             +multi_byte        +terminal
-autoservername    +folding           +multi_lang        +terminfo
+balloon_eval      -footer            -mzscheme          +termresponse
+balloon_eval_term +fork()            +netbeans_intg     +textobjects
+browse            +gettext           +num64             +textprop
++builtin_terms    -hangul_input      +packages          +timers
+byte_offset       +iconv             +path_extra        +title
+channel           +insert_expand     -perl              +toolbar
+cindent           +job               +persistent_undo   +user_commands
+clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           -python            +visual
+cmdline_info      +libcall           -python3           +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
+cscope            +localmap          -ruby              +wildmenu
+cursorbind        -lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con_gui    +mksession         +smartindent       +X11
+diff              +modify_fname      -sound             -xfontset
+digraphs          +mouse             +spell             +xim
+dnd               +mouseshape        +startuptime       +xpm
-ebcdic            +mouse_dec         +statusline        +xsmp_interact
+emacs_tags        +mouse_gpm         -sun_workshop      +xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          +mouse_netterm     +tag_binary        
+extra_search      +mouse_sgr         -tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/i386-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/i386-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16   -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux -lacl -lattr -lgpm -ldl  

 - OS: Ubuntu 18.04.3 LTS 32 bit
 - Terminal: GUI

**Comment by chrisbra** [comment]
is that the gui or the terminal vim? Can you bisect the offending commit?

**Comment by marystern** [comment]
it's the GUI version. 

I'll try to find a commit, but it might take a while (I know I had a master version from many weeks (possibly a couple of months) ago that has this problem, and I was hoping that it would have been fixed by now! 

FYI: I also didn't have this issue with the standard Ubuntu released version, so it's definitely a regression.

**Comment by chrisbra** [comment]
> FYI: I also didn't have this issue with the standard Ubuntu released version, so it's definitely a regression.

What is the standard Ubuntu released version?

**Comment by chrisbra** [comment]
That is gtk2 gui, right? Does it happen when starting without any plugins? Try to reproduce a minimal working example starting from `gvim --clean -p *` BTW: I cannot reproduce this. Does it happen in different desktop environments? It looks like a redraw a missing, but I have no clue, where the divider should come from, since you did not split the window.

**Comment by marystern** [comment]
Strangely this bug seems to have disappeared just recently (possibly due to Ubuntu/GTK updates?). Hence closing.
