### ISSUE TITLE
pi_netrw help was roll back, Is this intended ?

### ISSUE THREAD

**Issue by 0Delta** [vim/vim#5033]
I find roll back document in `runtime/doc/pi_netrw.txt` when translate help to Japanese.
Part of the document has been changed from `vim8x` to `vim7x` by 85850f3a5ef9f5a9d22e908ef263de8faa265a95 .
https://github.com/vim/vim/commit/85850f3a5ef9f5a9d22e908ef263de8faa265a95#diff-d64949e88953ad83cf5df8d5be72fd11L3505
https://github.com/vim/vim/commit/85850f3a5ef9f5a9d22e908ef263de8faa265a95#diff-d64949e88953ad83cf5df8d5be72fd11L3755-R3766

Is this change intended ?
If this change is incorrect, could you fix, and _back to future_ ?

**Comment by brammool** [comment]
We reverted netrw and then included a new version, must be a mistake merging versions.
