### ISSUE TITLE
Allow redefinition of the sentence text object

### ISSUE THREAD

**Issue by ainar-g** [vim/vim#5035]
<strong>
Is your feature request related something that is currently hard to do?
Please describe
</strong>

<p>
Currently, the definition of the sentence text object
<a href="https://vimhelp.org/motion.txt.html#sentence">cannot be changed</a>.
This prevents users from doing several useful things:
</p>

<ol>

<li>
<p>
Using sentence text objects with emoticons (e.g.  <code>:-)</code>) as
sentence-ending punctuation.  Note that while it is possible to require
users to add a “real” punctuation after the emoticon, some designers
recommend against it.  Example:
</p>
<pre>
Hey there :-)  I hope you're all right.
</pre>
</li>

<li>
<p>
Using sentence text object with emojis (e.g. <code>☺</code>) as
sentence-ending punctuation.  Same as the above.  Example:
</p>
<pre>
Hey there ☺  I hope you're all right.
</pre>
</li>

<li>
<p>
Using additional punctuation provided in Unicode, e.g. the “interrobang”
mark (<code>‽</code>).  Example:
</p>
<pre>
Did they really do that‽  I can't believe it!
</pre>
</li>

<li>
<p>
Using American style of punctuation ordering with Unicode quotes.
Example:
</p>
<pre>
“I don't like sand,” he said, “It gets everywhere.”  She didn't respond.
</pre>
</li>

<li>
<p>
(A continuation of the pevious point.)  Using Unicode quotes in Russian
etc.  texts.  Example:
</p>
<pre>
Я спросил: «Как дела?»  Он мне не ответил.
</pre>
</li>

<li>
<p>
Using the Greek question mark in Greek texts.  Example:
</p>
<pre>
Τι κάνεις;  Όλα καλά;
</pre>
</li>

</ol>

<strong>
Describe the solution you'd like
</strong>

<p>
An ability to redefine the sentence-ending markers would solve all these
issues.
</p>

<strong>
Describe alternatives you've considered
</strong>

<p>
One alternative would be creating your own text object and remapping
every sentence-related movement.  That sounds like an overkill to me,
although it is probably a working solution.
</p>

<p>
Another alternative would be adding all those cases as “corner cases”
into the still-non-redefinable sentence text object.  This sounds bad,
since it probably won't be a single change, but an ever-increasing
number of changes and complications.
</p>

<strong>
Additional context
</strong>

<p>
None, I guess?
</p>

**Comment by Houl** [comment]
Check out the existing plugins ... for a start:
https://github.com/kana/vim-textobj-user
and existing usages:
https://github.com/kana/vim-textobj-user/wiki

**Comment by ainar-g** [comment]
<p>
@Houl I'll take a look, thanks!
</p>

<p>
Another possible solution <em>for my personal case</em> is to either
redefine <code>cpoptions=J</code> or add a new compatible-option that
defines a sentence as “anything followed by two spaces”.  But that would
obviously not work for people who don't use the double sentence spacing
convention.
</p>

**Comment by chrisbra** [comment]
closing as this can be done using some plugins. The wiki also has some articles about creating custom text objects.

**Comment by dylnmc** [comment]
(don't know why this only stayed in mailing list but ...)

@ainar-g 

you can define your own text objects even without a plugin: https://vimways.org/2018/transactions-pending/

for example:

```
let s:sentence_seps = [
\    ':-)', ':)',
\    ':-(', ':(',
\    '.',
\    '!',
\    ';',
\    '?'
\]

function! s:select_is()
    let l:pat = printf('\(%s\)', join(map(s:sentence_seps, { _,v -> escape(v, '\') }), '\|'))
    unsilent echom l:pat
    if !search(printf('\V%s%s', l:pat, '\_s\*\zs'), 'bWc')
        call search('^', 'bWc')
    endif
    normal! v
    call search(printf('\V%s%s', '\.\ze\_s\*', l:pat), 'Wc')
endfunction

augroup Sentences
    autocmd!
    autocmd filetype text xnoremap <buffer> <silent> is :<c-u>call <sid>select_is()<cr>
    autocmd filetype text onoremap <buffer> <silent> is :<c-u>call <sid>select_is()<cr>
augroup end
```

See this asciinema where I have used the above maps and used `vis` to do what you want: https://asciinema.org/a/98GVydvcGxJrTJTESqNCLskL6

**Comment by ainar-g** [comment]
@dylnmc This is amazing, thank you! Going to play with your script right now :-)

**Comment by irisjae** [comment]
The definition of sentence affect more things than just text objects. Is there any way to redefine the marks `( as well?
