### ISSUE TITLE
:tselect gives undisired hit-enter message

### ISSUE THREAD

**Issue by georgexsh** [vim/vim#5040]
**Describe the bug**
`:tselect` gives undisired hit-enter message in recent releases.

**To Reproduce**
Detailed steps to reproduce the behavior:

1. generate a "tags" file with `ctags`
1. run `vim --clean`, open an empty buffer
1. execute command `:tselect someword`
1. press `1`, press `enter`, to select a tag
1. hit-enter message shows with file info, like:
```
"foo/bar.py" 254L, 8183C
Press ENTER or type command to continue
```
6. press enter, the file opened and jumped to the tag

**Expected behavior**

no hit-enter message, open the file and jump to the tag directly.
I believe this is the behavior of vim 8.1.1270 at least but changed in after upgrade to 8.1.2100.
with option `set shortmess+=F` could mute this hit-enter message, but I am worried about the side effects.

**Environment (please complete the following information):**
 - Vim version: 8.1.2100 (installed with homebrew)
 - OS: macOS 10.14
 - Terminal: iTerm2

**Comment by andymass** [comment]
The commit which broke this was 473952e8 aka "patch 8.1.2094: the fileio.c file is too big"

Specifically, src/file.io:62,

       if (prev_msg_col != 0 && msg_col == 0)
         	msg_putchar('\r');  // overwrite any previous message
