### ISSUE TITLE
setbufline failed for new buffer added by bufadd()

### ISSUE THREAD

**Issue by wsdjeg** [vim/vim#5044]
**Describe the bug**

setbufline failed if the buffer is added by bufadd function.

**To Reproduce**
Detailed steps to reproduce the behavior:

1. Run `vim --clean` (or `gvim --clean`, etc.)
2. `let nr = bufadd('')`
3. `call setbufline(nr, 1, 'sss')`
4. `echo getbufline(nr, 1)`

**Expected behavior**

the buffer content is updated.

**Comment by wsdjeg** [comment]
ok, I am not sure if this is a bug, because this is fixed by add `call bufload(nr)` before step 3.

**Comment by bfrg** [comment]
Under `:help getbufline()` is a small note that explains it very well:
```		
This function works only for loaded buffers.  For unloaded and 
non-existing buffers, an empty |List| is returned.
```
Maybe a similar note could be added to `:h setbufline()`, `appendbufline()` and `deletebufline()`?

**Comment by brammool** [comment]
We could automatically create the buffer, but what if it has the name of an existing file?  We can't just read the file unexpectedly and setting lines without reading the file may also not be what the user wants.  A note and hint to use bufload() is probably better.

**Comment by wsdjeg** [comment]
ok, thanks
