### ISSUE TITLE
Add function for set buffer lines instead of only one line

### ISSUE THREAD

**Issue by wsdjeg** [vim/vim#5046]
when I want to update the content of a background buffer, I need to set the line one by one, it is too slow. we hope there is a function like setbufline, but can accecpt a list of lines, instead of only one line.

**Comment by andymass** [comment]
setbufline does take a list (it is not very obvious from documentation)

**Comment by wsdjeg** [comment]
but it does not tack a rage as line number.

**Comment by brammool** [comment]
You only need the number of the first line.

**Comment by tonymec** [comment]
@wsdjeg : reading `:help setbufline()` attentively shows that when the `{text}` is a List the line `lnum` and the following lines will be replaced by the successive items of the List. No range is necessary because the last line replaced will be line `lnum + len(text) - 1`.

**Comment by wsdjeg** [comment]
but if I want to insert 10 lines to line 4 - 8 ,  how  can i do that?

**Comment by wsdjeg** [comment]
again, if I want to replace line 4 to -3 line, how can I do, count the buffer lines is slow.

**Comment by brammool** [comment]
> but if I want to insert 10 lines to line 4 - 8 ,  how  can i do that?

Set lines 4 - 8 with setbufline() and append the others with
appendbufline().

-- 
A special law prohibits unmarried women from parachuting on Sunday or she
shall risk arrest, fine, and/or jailing.
		[real standing law in Florida, United States of America]

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by wsdjeg** [comment]
@brammool oh, thanks, my vim is too old, I will check the latest version of gvim.
