### ISSUE TITLE
lines unexpectedly joined in a heredoc

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#5051]
**Describe the bug**

When writing a heredoc to assign a list of strings to a variable, sometimes, a line beginning with a backslash is unexpectedly joined with the previous one.

**To Reproduce**

1. Write this in `/tmp/vimrc`:

       let a =<< trim END
           \x
       END
       echo a

2. Start Vim like this:

       $ vim -Nu /tmp/vimrc

The command raises the error `E990`, because `\x` has been joined with `END` (the backslash is removed in the process):

    E990: Missing end marker 'ENDx'

---

Here is a different issue which also involves a line beginning with a backslash.

1. Write this in `/tmp/vimrc`:

       fu Func()
           let [a, b, c] =<< trim END
               xx
               \x
               xx
           END
           echo [a, b, c]
       endfu
       call Func()

2. Start Vim like this:

       $ vim -Nu /tmp/vimrc

The command raises the error `E688`:

    E688: More targets than List items

The first `xx` has been joined with `\x` (the backslash is removed in the process).
As a result, there are only 2 items (`xxx` and `xx`) for 3 targets (`a`, `b`, `c`).

**Expected behavior**

The first command raises no errors, and outputs:

    ['\x']

The second command raises no errors, and outputs:

    ['xx', '\x', 'xx']

**Environment**

 - Vim version: 8.1  Included patches: 1-2141
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

The second issue is due to a combination of several factors.

First, the heredoc needs to be inside a function. So this works:

    let [a, b, c] =<< trim END
        xx
        \x
        xx
    END

But not this:

    fu Func()
        let [a, b, c] =<< trim END
            xx
            \x
            xx
        END
    endfu
    call Func()

Second, the strings in the heredoc must be unpacked in several variables (see `:h :let-unpack`), and there must be a space around one of the comma separating the variables. So this works (because no unpacking):

    fu Func()
        let a =<< trim END
            xx
            \x
            xx
        END
    endfu
    call Func()

And this works too (because no extra space around a comma):

    fu Func()
        let [a,b,c] =<< trim END
            xx
            \x
            xx
        END
    endfu
    call Func()

But not this:

    fu Func()
        let [a, b,c] =<< trim END
            xx
            \x
            xx
        END
    endfu
    call Func()

Notice the space after the comma here:

    let [a, b,c] =<< trim END
           ^

Third, one of the line needs to start with a backslash. So this works:

    fu Func()
        let [a, b, c] =<< trim END
            xx
            xx
            xx
        END
    endfu
    call Func()

But not this:

    fu Func()
        let [a, b, c] =<< trim END
            xx
            \x
            xx
        END
    endfu
    call Func()

**Comment by brammool** [comment]
> **Describe the bug**
> 
> When writing a heredoc to assign a list of strings to a variable,
> sometimes, a line beginning with a backslash is unexpectedly joined
> with the previous one.
> 
> **To Reproduce**
> 
> 1. Write this in `/tmp/vimrc`:
> 
>        let a =<< trim END
>            \x
>        END
>        echo a
> 
> 2. Start Vim like this:
> 
>        $ vim -Nu /tmp/vimrc
> 
> The command raises the error `E990`, because `\x` has been joined with
> `END` (the backslash is removed in the process):
> 
>     E990: Missing end marker 'ENDx'

Yeah, that's because the line continuation is used before the command is
parsed.  You can avoid it by adding 'C' to 'cpoptions':

	set cpo+=C
        let a =<< trim END
            \x
        END
        echo a
	set cpo-=C

> ---
> 
> Here is a different issue which also involves a line beginning with a
> backslash.
> 
> 1. Write this in `/tmp/vimrc`:
> 
>        fu Func()
>            let [a, b, c] =<< trim END
>                xx
>                \x
>                xx
>            END
>            echo [a, b, c]
>        endfu
>        call Func()
> 
> 2. Start Vim like this:
> 
>        $ vim -Nu /tmp/vimrc
> 
> The command raises the error `E688`:
> 
>     E688: More targets than List items
> 
> The first `xx` has been joined with `\x` (the backslash is removed in
> the process).
> As a result, there are only 2 items (`xxx` and `xx`) for 3 targets
> (`a`, `b`, `c`).

Strange, when using "lines" instead of [a, b, c] it works.

> **Environment**
> 
>  - Vim version: 8.1  Included patches: 1-2141
>  - OS: Ubuntu 16.04.6 LTS
>  - Terminal: XTerm(322)
> 
> **Additional context**
> 
> The second issue is due to a combination of several factors.
> 
> First, the heredoc needs to be inside a function. So this works:
> 
>     let [a, b, c] =<< trim END
>         xx
>         \x
>         xx
>     END
> 
> But not this:
> 
>     fu Func()
>         let [a, b, c] =<< trim END
>             xx
>             \x
>             xx
>         END
>     endfu
>     call Func()
> 
> Second, the strings in the heredoc must be unpacked in several variables (see `:h :let-unpack`), and there must be a space after one of the comma separating the variables. So this works (because no unpacking):
> 
>     fu Func()
>         let a =<< trim END
>             xx
>             \x
>             xx
>         END
>     endfu
>     call Func()
> 
> And this works too (because no extra space after a comma):
> 
>     fu Func()
>         let [a,b,c] =<< trim END
>             xx
>             \x
>             xx
>         END
>     endfu
>     call Func()
> 
> But not this:
> 
>     fu Func()
>         let [a, b,c] =<< trim END
>             xx
>             \x
>             xx
>         END
>     endfu
>     call Func()
> 
> Notice the space after the comma here:
> 
>     let [a, b,c] =<< trim END
>            ^

Weird, that should not make a difference.
 
> Third, one of the line needs to start with a backslash. So this works:
> 
>     fu Func()
>         let [a, b, c] =<< trim END
>             xx
>             xx
>             xx
>         END
>     endfu
>     call Func()
> 
> But not this:
> 
>     fu Func()
>         let [a, b, c] =<< trim END
>             xx
>             \x
>             xx
>         END
>     endfu
>     call Func()

-- 
Why don't cannibals eat clowns?
Because they taste funny.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
