### ISSUE TITLE
sh syntax highlight breaks on "${*//#/x}": everything after becomes shDoubleQuote

### ISSUE THREAD

**Issue by chkno** [vim/vim#5054]
`sh` syntax highlighting treats `#` as introducing a comment when inside `"${var//  ....  /}"`, but shell does not.  `"${var/  ....  /}"` (single replace instead of replace-all -- one initial / instead of two) works as expected.

**To Reproduce**
1. Edit this file with syntax highlighting on:
```
#!/bin/bash

expand_octothorpes() {
  echo "${*//#/octothorpe}"
}

# The rest of this file is highlighted as shDoubleQuote

expand_octothorpes "$*"
```

**Screenshots**
![quoted-octothorpe](https://user-images.githubusercontent.com/1118859/66767123-9b3b3600-ee64-11e9-99c8-61960848260a.png)

**Environment:**
 - Vim version: VIM - Vi IMproved 8.1 (2018 May 18), Included patches: 1-578, with the latest sh syntax file from http://www.drchip.org/astronaut/vim/index.html#SYNTAX_SH -- Version:    188 marked "Last Change:    Jun 16, 2019"
 - OS: GNU/Linux NixOS 19.03
 - Terminal: st

**Additional context**
Possibly related to #364.
Maintainer: @cecamp

**Comment by chrisbra** [comment]
does is work if your force bash mode?

**Comment by chkno** [comment]
The `#!/bin/bash` forces bash mode -- `echo b:current_syntax` says `bash`.

**Comment by cecamp** [comment]
Please try version 189 (astro-only) from [my website](http://www.drchip.org/astronaut/vim/index.html#SYNTAX_SH)

**Comment by chkno** [comment]
This is fixed with version 189.  Thanks!

**Comment by chrisbra** [comment]
okay, closing then. I suppose Charles will submit an updated version to Bram eventually.
