### ISSUE TITLE
cursorlineopt option did not work for terminal buf.

### ISSUE THREAD

**Issue by Shane-XB-Qian** [vim/vim#5055]
**Describe the bug**
set cursorlineopt to 'number' - but it still would show 'line' still.

**To Reproduce**
1, open a term buf 
2, set cursorlineopt=number
3, set cursorline
4, hi cursorline ...sth...

**Expected behavior**
only number

**Screenshots**
n/a

**Environment (please complete the following information):**
 - vim8.1-2122, ubuntu

**Additional context**
refer #4693

**Comment by brammool** [comment]
If you open a terminal with a shell, there is no cursorline.  Even in terminal-Normal mode, the attributes from the terminal are used. Thus 'cursorline' isn't very useful in a terminal buffer.
Why would you want to use this feature?

**Comment by Shane-XB-Qian** [comment]
yes, as you said, i'd like to let cursorline disappeared - but linenr kept.
-- the 'line' still there even i set that option to 'number' only.

**Comment by Shane-XB-Qian** [comment]
it works fine -- except terminal-normal buf was bug.
