### ISSUE TITLE
Text-property highlighting interfering with syntax highlighting

### ISSUE THREAD

**Issue by nickspoons** [vim/vim#5057]
**Describe the bug**
When text properties are used to provide further highlighting on top of standard `syn match` and `syn region` highlighting, the first character that should be text-property highlighted actually has the highlight of the preceding character.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Create the file "syntax_prop.vim" containing the following:
```vim
syn match csParens "[()]" display
hi! link csParens MatchParen

call prop_type_add('TPTitle', #{ highlight: 'Title' })
call prop_add(line('$'), 2, #{type: 'TPTitle', end_col: 5})

finish

" Example: parentheses highlighted as MatchParen (syntax highlighting)
(abc)

" Example: parentheses highlighted as MatchParen (syntax highlighting) and
" contents highlighted as Title (text property)
(abc)
```
2. Run `vim --clean -S syntax_prop.vim syntax_prop.vim`
3. Note that in the last line, `(abc)` is incorrectly highlighted: The initial MatchParen highlighting includes the `a`.

**Screenshot**
![screenshot-2019-10-15_095843](https://user-images.githubusercontent.com/5274565/66782849-2420a300-ef33-11e9-888f-e7fc0d79d05c.png)

**Environment:**
 - From patch 8.1.2071 onwards.
 - OS: Seen in terminal Vim in arch linux and gVim in Windows10

**Comment by brammool** [comment]
I can reproduce it.

**Comment by nickspoons** [comment]
Lovely, thanks for the quick fix!
