### ISSUE TITLE
Wrong coding style

### ISSUE THREAD

**Issue by watiko** [vim/vim#506]
https://github.com/vim/vim/compare/v7.4.785...v7.4.790
- 7.4.786 : it is not possible for a plugin to adjust to a changed setting
- 7.4.787 : (after 7.4.786) snprintf() isn't available everywhere
- 7.4.788 : (after 7.4.786) can't build without the crypt feature
- 7.4.789 : (after 7.4.788) using freed memory and crash
- 7.4.790 : (after 7.4.786) test fails without the autochdir feature

There are still mixed `sprintf` and `vim_snprintf` cases.
https://github.com/vim/vim/blob/v7.4.943/src/option.c#L4979
https://github.com/vim/vim/blob/v7.4.943/src/option.c#L5808

We does not use the last allocated byte of `buf_old` and `buf_new`. 
**EDIT**: And Should we use `NUMBUFLEN`?

``` c
    char_u buf_old[11], buf_new[11], buf_type[7];
    vim_snprintf((char *)buf_old, 10, "%ld", old_value);
    vim_snprintf((char *)buf_new, 10, "%ld", value);
```

https://github.com/vim/vim/blob/v7.4.943/src/option.c#L8957-L8959

~~**EDIT2**
If `errmsg` equals `NULL`, `saved_origval` won't be freed (memory leaking).
https://github.com/vim/vim/blob/v7.4.943/src/option.c#L4955-L4991~~

**Comment by watiko** [comment]
https://github.com/vim/vim/commit/a98849670674264de699d7ab22ae4b9b32e78f4a fixes the memory leak.

**Comment by chrisbra** [comment]
Please create a PR for the wrong style. closing.
