### ISSUE TITLE
":verbose set opt?" should display a note when the value is different from where it was recorded to be changed

### ISSUE THREAD

**Issue by blueyed** [vim/vim#5066]
`:verb set diff?` might display:

>   diff
>        Last set from …/t.vim line 6

Although that line is: `autocmd BufWinLeave * set nodiff`

I.e. the line clearly has set it to `nodiff`, but `:verb set` reports it as `diff`.

This is due to it being changed internally (likely a bug), but it would be good if `:verb set` would display a warning/note in that case.
For this it might be required that the value is stored in `set_option_sctx_idx` and compared when being displayed with `:verb set`.

**Comment by brammool** [comment]
Daniel Hahler wrote:

> `:verb set diff?` might display:
> 
> >   diff
> >        Last set from …/t.vim line 6
> 
> Although that line is: `autocmd BufWinLeave * set nodiff`
> 
> I.e. the line clearly has set it to `nodiff`, but `:verb set` reports
> it as `diff`.
> 
> This is due to it being changed internally (likely a bug), but it
> would be good if `:verb set` would display a warning/note in that
> case.
> For this it might be required that the value is stored in
> `set_option_sctx_idx` and compared when being displayed with `:verb
> set`.

So the last change that is reported was followed by another change,
which didn't update or reset the context.  What was that change then,
how can it be reproduced?

-- 
(letter from Mark to Mike, about the film's probable certificate)
      For an 'A' we would have to: Lose as many shits as possible; Take Jesus
      Christ out, if possible; Loose "I fart in your general direction"; Lose
      "the oral sex"; Lose "oh, fuck off"; Lose "We make castanets out of your
      testicles"
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by blueyed** [comment]
> So the last change that is reported was followed by another change,
which didn't update or reset the context.  What was that change then,
how can it be reproduced?

It happens when using `set nodiff` in a BufWinLeave autocommand, and then going back to the previous buffer in the same window (`c-o`).
It might be intentional though - IIRC it seems like some window-local options are copied from buffers when those are displayed in the window again.
Likely via https://github.com/vim/vim/blob/b1ba9abcb385b0a5355788a7eefef78ec68d2f65/src/buffer.c#L2967-L2972.

But even if this would be fixed to update the location (which is not really easy I think), there are still other places in the source that set options directly, and therefore it would make sense to display a note then - otherwise it is confusing (especially when setting is based on some condition etc, and it therefore is not obvious that the value has changed in some other way).
