### ISSUE TITLE
Packages not respecting mapleader

### ISSUE THREAD

**Issue by kprussing** [vim/vim#5071]
**Describe the bug**

Loading packages before using `set mapleader` in a `vimrc` does not propagate the `<Leader>` to the loaded packages.  Specifically, if the leader is the default `\` when a package is loaded, it remains so even after `set mapleader=...`.

**To Reproduce**

Consider the following minimal `vimrc`:

    set nocompatible
    filetype plugin on
    packadd nerdcommenter
    let mapleader = ","

Using `,c<space>` does not comment out the selected text.  Instead, `\c<space>` does.  On the other hand, the following `vimrc` works with `,c<space>`

    set nocompatible
    filetype plugin on
    let mapleader = ","  " remapping leader _before_ `packadd`
    packadd nerdcommenter

**Expected behavior**

Packages such as [NERDcommenter](https://github.com/scrooloose/nerdcommenter/) define macros using the `<Leader>`.  After adding `set mapleader=','` in a `vimrc`, one expects the `<Leader>` to have been remapped independent of the order of commands.
 
**Environment:**

-  VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 28 2019 01:07:30)
    macOS version
    MacVim and MacPorts
-  OS: macOS High Sierra 10.13.6 (17G8037) (and Catalina, but I don't have the version number)
-  Terminal: GUI/tmux/macOS Terminal

**Additional context**

I discovered the issue with NERDcommenter (stupid habits grilled into fingers), but the problem also occurs with [the Unicode plugin](https://github.com/chrisbra/unicode.vim).  A straight forward work around is to simply use `packadd` _after_ `set mapleader` which is what I did (I don't use many external packages). Therefore, a note about ordering in the documentation seems like it would be sufficient.

I don't know how this interplays with packages under `pack/*/start`.

**Comment by jamessan** [comment]
This isn't a bug.  It's documented behavior.  See `:help mapleader`, particularly the last paragraph -- https://github.com/vim/vim/blob/b1ba9abcb385b0a5355788a7eefef78ec68d2f65/runtime/doc/map.txt#L562-L564

**Comment by kprussing** [comment]
Well that's what I get for reading the wrong part of the manual.  I was looking at `:help package`.
