### ISSUE TITLE
8.1.0629 changes the behavior of v_gn and v_gN with single character search pattern

### ISSUE THREAD

**Issue by tomtomjhj** [vim/vim#5075]
**Describe the bug**
The resulting highlight region of `v_gn` and `v_gN` with a search pattern that generates a match of length 1 doesn't include the matched string itself if it is on the left end. It works correctly for patterns that match longer strings.

**To Reproduce**
For example, 
1. Build 8.1.0629 version (just `make`) and run `src/vim`
2. Insert `12345678`
3. Search `1`
4. Enter visual mode and highlight `567` from right to left.
5. `gN`. Then `234567` is highlighted.

**Expected behavior**
The match should be included in the resulting highlight: `1234567`.

To reproduce for `v_gn`, search `5` and highlight `34567` from right to left, then `gn`. The resulting highlighted region is `67` but `567` is the correct behavior.

The version without patch 8.1.0629 works as expected. I tested on c33181c44ccb86637e011f35cc0397a2d76e23ae (the direct parent of this patch).

**Environment (please complete the following information):**
 - 8.1.0629 
 - Ubuntu 19.04
 - Gnome terminal, tmux

**Comment by chrisbra** [comment]
Hm, yes since patch 8.1.0629 I think we can simplify the logic further. I think this patch fixes it:

```patch
diff --git a/src/search.c b/src/search.c
index 77c3aa492..3b0204461 100644
--- a/src/search.c
+++ b/src/search.c
@@ -4663,7 +4663,7 @@ abort_search:

 #endif /* FEAT_TEXTOBJ */

-static int is_one_char(char_u *pattern, int move, pos_T *cur, int direction);
+static int is_zero_width(char_u *pattern, int move, pos_T *cur, int direction);

 /*
  * Find next search match under cursor, cursor at end.
@@ -4684,7 +4684,7 @@ current_search(
     char_u     old_p_ws = p_ws;
     int                flags = 0;
     pos_T      save_VIsual = VIsual;
-    int                one_char;
+    int                zero_width;

     /* wrapping should not occur */
     p_ws = FALSE;
@@ -4713,9 +4713,9 @@ current_search(

     /* Is the pattern is zero-width?, this time, don't care about the direction
      */
-    one_char = is_one_char(spats[last_idx].pat, TRUE, &curwin->w_cursor,
+    zero_width = is_zero_width(spats[last_idx].pat, TRUE, &curwin->w_cursor,
                                                                      FORWARD);
-    if (one_char == -1)
+    if (zero_width == -1)
     {
        p_ws = old_p_ws;
        return FAIL;  /* pattern not found */
@@ -4734,7 +4734,7 @@ current_search(
            dir = !i;

        flags = 0;
-       if (!dir && !one_char)
+       if (!zero_width)
            flags = SEARCH_END;
        end_pos = pos;

@@ -4782,12 +4782,13 @@ current_search(

     // put cursor on last character of match
     curwin->w_cursor = end_pos;
+    if (!zero_width && EQUAL_POS(VIsual, end_pos))
+       VIsual = pos;
     if (LT_POS(VIsual, end_pos))
        dec_cursor();
     VIsual_active = TRUE;
     VIsual_mode = 'v';

-    redraw_curbuf_later(INVERTED);     /* update the inversion */
     if (*p_sel == 'e')
     {
        /* Correction for exclusive selection depends on the direction. */
@@ -4823,7 +4824,7 @@ current_search(
  * Returns TRUE, FALSE or -1 for failure.
  */
     static int
-is_one_char(char_u *pattern, int move, pos_T *cur, int direction)
+is_zero_width(char_u *pattern, int move, pos_T *cur, int direction)
 {
     regmmatch_T        regmatch;
     int                nmatched = 0;
@@ -4874,9 +4875,6 @@ is_one_char(char_u *pattern, int move, pos_T *cur, int dir─ection)
            result = (nmatched != 0
                && regmatch.startpos[0].lnum == regmatch.endpos[0].lnum
                && regmatch.startpos[0].col == regmatch.endpos[0].col);
-           /* one char width */
-           if (!result && inc(&pos) >= 0 && pos.col == regmatch.endpos[0].col)
-               result = TRUE;
        }
     }

diff --git a/src/testdir/test_gn.vim b/src/testdir/test_gn.vim
index fc7e89190..85aa79d88 100644
--- a/src/testdir/test_gn.vim
+++ b/src/testdir/test_gn.vim
@@ -128,6 +128,17 @@ func Test_gn_command()
   call assert_equal([' nnoremap', '', 'match'], getline(1,'$'))
   sil! %d_

+  " make sure it works correctly for one-char wide search items
+  call setline('.', ['abcdefghi'])
+  let @/ = 'a'
+  exe "norm! 0fhvhhgNgU"
+  call assert_equal(['ABCDEFGHi'], getline(1,'$'))
+  call setline('.', ['abcdefghi'])
+  let @/ = 'b'
+  exe "norm! 0fhvhhgngU"
+  call assert_equal(['aBCDEFGHi'], getline(1,'$'))
+  sil! %d _
+
   set wrapscan&vim
 endfu
```

**Comment by tomtomjhj** [comment]
@chrisbra Hi. Thanks for the fast response.
The patch fixed the cases I described but unfortunately this breaks the symmetric case:
1. `abcdefghi`
2. search `f`
3. highlight from `abc` from left to right
4. after `gngU`, the text becomes `ABCDEfghi`

**Comment by chrisbra** [comment]
I have another look next week.

**Comment by brammool** [comment]
Christian wrote:

> Hm, yes since patch 8.1.0629 I think we can simplify the logic
> further. I think this patch fixes it:

Thanks for looking into it.  Sending a patch this way has modified
indent, which makes it difficult to include.  Can you email it as an
attachment or create a pull request?


-- 
Mynd you, m00se bites Kan be pretty nasti ...
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
@tomtomjhj is this related to my patch of does Vim currently also behave like this?

**Comment by tomtomjhj** [comment]
@chrisbra https://github.com/tomtomjhj/vim/tree/patch Here I first applied your patch on top of 8.1.2172 (right before the big `searchit` refactor) and then merged the patches up to 8.1.2178. Now it behaves as described in the original report. That is, your patch doesn't introduce any new behavior.

**Comment by tomtomjhj** [comment]
@chrisbra @brammool  Thanks for the patch. I found out that 8.1.2207 introduces another similar bug:
1. `12345678`
2. search `5`
3. highlight from `2` to `7`
4. `gN`. Then `234` is highlighted. `2345` is expected.

**Comment by chrisbra** [comment]
can you please check the following additional patch?

```patch
diff --git a/src/search.c b/src/search.c
index a1f8998df..18f7905e5 100644
--- a/src/search.c
+++ b/src/search.c
@@ -4677,7 +4677,7 @@ abort_search:
 #endif /* FEAT_TEXTOBJ */

 /*
- * Check if the pattern is one character long or zero-width.
+ * Check if the pattern is zero-width.
  * If move is TRUE, check from the beginning of the buffer, else from position
  * "cur".
  * "direction" is FORWARD or BACKWARD.
@@ -4851,7 +4851,7 @@ current_search(

     // put cursor on last character of match
     curwin->w_cursor = end_pos;
-    if (LT_POS(VIsual, end_pos))
+    if (LT_POS(VIsual, end_pos) && forward)
        dec_cursor();
     else if (VIsual_active && LT_POS(curwin->w_cursor, VIsual))
        curwin->w_cursor = pos;   // put the cursor on the start of the match
diff --git a/src/testdir/test_gn.vim b/src/testdir/test_gn.vim
index ecf9b8289..9edf0a21e 100644
--- a/src/testdir/test_gn.vim
+++ b/src/testdir/test_gn.vim
@@ -148,6 +148,11 @@ func Test_gn_command()
   norm! gg0f7vhhhhgnd
   call assert_equal(['12348'], getline(1,'$'))
   sil! %d _
+  call setline('.', ['12345678'])
+  let @/ = '5'
+  norm! gg0f2vf7gNd
+  call assert_equal(['1678'], getline(1,'$'))
+  sil! %d _

   set wrapscan&vim
 endfu
```

**Comment by tomtomjhj** [comment]
@chrisbra Yeah, I tested every possible combination and it seems to work correctly. Thanks!

**Comment by chrisbra** [comment]
great!. @brammool do you want me to send a new PR for this?

**Comment by brammool** [comment]
Christian wrote:

> can you please check the following additional patch?

I'll include it, thanks.

-- 
Engineers are always delighted to share wisdom, even in areas in which they
have no experience whatsoever.  Their logic provides them with inherent
insight into any field of expertise.  This can be a problem when dealing with
the illogical people who believe that knowledge can only be derived through
experience.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
