### ISSUE TITLE
Tab character wrongly highlighted by `helpNote` in help file

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#5076]
**Describe the bug**

A Tab character is sometimes wrongly highlighted by the syntax group `helpNote`.

**To Reproduce**

Run this shell command:

    vim -Nu NONE +'syn on|h :au'

The text `Note:` is correctly highligted by the syntax group `helpNote`.
The preceding Tab character is also – wrongly – highlighted.

                        Note: A quote character is seen as argument to the
                 ^^^^^^^

**Expected behavior**

The preceding Tab character is not highlighted.

**Screenshots**

![gif](https://user-images.githubusercontent.com/8505073/67037455-d320d280-f11d-11e9-9ad8-9c652237d8fb.gif)

**Environment**

 - Vim version: 8.1  Included patches: 1-2168
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

I bisected the issue to https://github.com/vim/vim/commit/3439028c8909aaa71ffe612a7191babdfe07c04c.

When this commit was added, the preceding Tab character was not fully highlighted though, only the second screen cell. When https://github.com/vim/vim/commit/9115c611dbd3e4abab583eade6888421f66077e7 was added, then the full Tab was highlighted by `helpNote`.

**Comment by chrisbra** [comment]
can confirm and just noted the same problem:

reproduced using `vim --clean -c ':h synID()|only'`
![grafik](https://user-images.githubusercontent.com/244927/67083027-abbc1b00-f19a-11e9-9e6c-b86bd7be4069.png)

**Comment by chrisbra** [comment]
I think we need this patch:

```patch
diff --git a/src/drawline.c b/src/drawline.c
index 319338ce3..13a91e4e4 100644
--- a/src/drawline.c
+++ b/src/drawline.c
@@ -1426,7 +1426,7 @@ win_line(

 #ifdef FEAT_SYN_HL
                // Get syntax attribute.
-               if (has_syntax)
+               if (has_syntax && n_extra == 0)
                {
                    // Get the syntax attribute for the character.  If there
                    // is an error, disable syntax highlighting.
```

No, this breaks `src/testdir/dumps/Test_syntax_c_01.dump` but I cannot detect a difference visually when I call `call term_dumpdiff("testdir/failed/Test_syntax_c_01.dump", "testdir/dumps/Test_syntax_c_01.dump")`

**Comment by brammool** [comment]
> I think we need this patch:
> 
> ```patch
> diff --git a/src/drawline.c b/src/drawline.c
> index 319338ce3..13a91e4e4 100644
> --- a/src/drawline.c
> +++ b/src/drawline.c
> @@ -1426,7 +1426,7 @@ win_line(
> 
>  #ifdef FEAT_SYN_HL
>                 // Get syntax attribute.
> -               if (has_syntax)
> +               if (has_syntax && n_extra == 0)
>                 {
>                     // Get the syntax attribute for the character.  If there
>                     // is an error, disable syntax highlighting.
> ```
> 
> No, this breaks `src/testdir/dumps/Test_syntax_c_01.dump` but I cannot
> detect a difference visually when I call `call
> term_dumpdiff("testdir/failed/Test_syntax_c_01.dump",
> "testdir/dumps/Test_syntax_c_01.dump")`

It's correct, the foreground color changes because of the fix, but
because it's on spaces you don't see the foreground color.  The dump
diff does see the different attributes, thus has "fffff" there.

-- 
There are two ways of constructing a software design. One way is to make
it so simple that there are obviously no deficiencies. The other way
is to make it so complicated that there are no obvious deficiencies.
                                                           -C.A.R. Hoare

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
