### ISSUE TITLE
8.1.2153 (3439028c) broke detection and highlighting of misspelled words

### ISSUE THREAD

**Issue by chdiza** [vim/vim#5078]
I'm on macOS 10.14.6.  Vim 8.1.2153 has broken the identification and highlighting of misspelled words.  Specifically, some words that aren't misspelled are highlighted as misspelled, but only partly.

Bisection reveals that this commit broke the identification and highlighting of misspelled words:

```
  commit 3439028c8909aaa71ffe612a7191babdfe07c04c
  Author: Bram Moolenaar <Bram@vim.org>
  Date:   Wed Oct 16 14:38:26 2019 +0200
  
      patch 8.1.2153: combining text property and syntax highlight is wrong
  
      Problem:    Combining text property and syntax highlight is wrong. (Nick
                  Jensen)
      Solution:   Compute the syntax highlight attribute much earlier.
                  (closes #5057)
```

It particular, if a word was declared good by me in `~/.vim/spell/en.utf-8.add.spl`, then if that word begins a line all of it except the first letter are highlighted as a misspelled word.  But if that same word is not at the start of a line, Vim correctly leaves it alone.  This only happens for words that I have in my spelling additions file.

All of this involves starting vim with -u NONE -U NONE -N --noplugin.

I have `en.utf-8.add.spl` in my `~/.vim/spell`.  It contains 'Quine' as a good word.

After 3439028c8, if I put the following in a file:

```
Quine
But not Quine
```

and do `:set spell`, then I observe the following:

1. In the first occurrence of 'Quine', only the 'uine' is highlighted as a bad word while the 'Q' is left alone.  So vim is wrongly identifying it as bad, and then botching the highlighting of the badness.

2. The second occurrence of 'Quine' is left alone.

Interestingly, `]s` doesn't move the cursor onto the first 'Quine'.  And interestingly, there's nothing special about 'Quine'.  This happens for *all* words in my spelling additions file, as far as I can see.

When I say that Vim highlights it as misspelled, I mean that I see the `undercurl` that is normally used for misspelled words.  I'm using a colorscheme that does not explicitly set `undercurl` or `guisp` for anything, so this is coming from Vim.

**Comment by uguu-org** [comment]
I see a similar issue on 8.1.2169 where most words at the beginning of lines appears to fail spellcheck, screenshot:
![a](https://user-images.githubusercontent.com/2000051/67053731-1e73ba80-f0f7-11e9-9ed1-7b4eee0531c7.gif)

Notice how all letters except the first letter are incorrectly marked as mispelled, but problem goes away after a space is inserted before each word.

**Comment by brammool** [comment]
> I see a similar issue on 8.1.2169 where most words at the beginning of lines appears to fail spellcheck, screenshot:
> ![a](https://user-images.githubusercontent.com/2000051/67053731-1e73ba80-f0f7-11e9-9ed1-7b4eee0531c7.gif)
> 
> Notice how all letters except the first letter are incorrectly marked
> as mispelled, but problem goes away after a space is inserted before
> each word.

Thanks for reporting.  That patch was a risky change.  I finally decided
to take the risk, because the computation of attributes was so messy.
It's at least in the right order now, but I already fixed a few problems
caught by tests, then found a few more problems not caught by tests,
like this one.  There might be another one.

-- 
(letter from Mark to Mike, about the film's probable certificate)
      I would like to get back to the Censor and agree to lose the shits, take
      the odd Jesus Christ out and lose Oh fuck off, but to retain 'fart in
      your general direction', 'castanets of your testicles' and 'oral sex'
      and ask him for an 'A' rating on that basis.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
