### ISSUE TITLE
syntax highlighting adds a lot of latency when 'cursorline' is set

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#5079]
**Describe the bug**

When `'cursorline'` is set, sometimes, the syntax highlighting takes a lot of time, which adds a lot of latency.

**To Reproduce**

1. Run this shell command:

       vim -Nu NONE +'setl cul' +'set ft=vim|syn enable|/readline#yank' +'setl noro|pu=\"th\"|startinsert!' <(curl -s https://raw.githubusercontent.com/lacygoill/vim-readline/master/autoload/readline.vim)

2. Press `C-n` to complete the text `th`, and maintain the key pressed for a few seconds.

3. Stop pressing `C-n`.

Vim keeps scrolling the pum for several seconds.

**Expected behavior**

Vim stops scrolling the pum immediately.

**Screenshots**

![gif](https://user-images.githubusercontent.com/8505073/67038499-c8ffd380-f11f-11e9-8b8a-269d01870c54.gif)

In the gif, `C-n` is pressed 210 times for about 5 seconds.
After being released, Vim keeps scrolling the menu for about 6 seconds.

**Environment**

 - Vim version: 8.1  Included patches: 1-2168
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

I bisected the issue to the commit https://github.com/vim/vim/commit/c2b97643a82bb9fbd202312dac4aa995f92e9e5b.
There was no increased latency just before.

---

I can also reproduce the issue when `'cursorline'` is not set, and `'cursorlineopt'` is set to `screenline`:

    vim -Nu NONE +'setl culopt=screenline' +'set ft=vim|syn enable|/readline#yank' +'setl noro|pu=\"th\"|startinsert!' <(curl -s https://raw.githubusercontent.com/lacygoill/vim-readline/master/autoload/readline.vim)
                   ^^^^^^^^^^^^^^^^^^^^^^

So, even if the cursor line is not visible, the latency can increase a lot.

---

The issue disappears if the syntax highlighting is disabled:

    vim -Nu NONE +'setl cul' +'set ft=vim|syn off|/readline#yank' +'setl noro|pu=\"th\"|startinsert!' <(curl -s https://raw.githubusercontent.com/lacygoill/vim-readline/master/autoload/readline.vim)
                                          ^^^^^^^

Here are two reports obtained with `:syntime`, after maintaining `C-n` pressed for 5 seconds:

   - [report while 'cursorline' is set](https://0x0.st/zxGA.txt)
   - [report while 'cursorline' is NOT set](https://0x0.st/zxGm.txt)

For some reason, when `'cursorline'` is set, the regexes are used and match several dozens of times more often.

---

I can not reproduce if – prior to the compilation – I configure Vim with just `--with-features=huge`.

I can reproduce if I configure with just `--enable-rubyinterp=dynamic`:

    make clean ; make distclean ; ./configure --enable-rubyinterp=dynamic ; make

Although, if I compile with just `--enable-rubyinterp`, the latency is not as high as before; it decreases by about 30%, but still remains very high.

This is how I configure the compilation:

      ./configure  \
        --enable-cscope                \
        --enable-fail-if-missing       \
        --enable-gui=gtk2              \
        --enable-luainterp=dynamic     \
        --enable-multibyte             \
        --enable-perlinterp=dynamic    \
        --enable-python3interp=dynamic \
        --enable-pythoninterp=dynamic  \
        --enable-rubyinterp=dynamic    \
        --enable-terminal              \
        --prefix=/usr/local            \
        --with-compiledby=user         \
        --with-features=huge           \
        --with-luajit                  \
        --with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu \
        --with-python3-config-dir=/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu

---

Here are two charts [measuring the latency](https://github.com/pavelfatin/typometer) when `'cursorline'` is respectively reset and set:

![nocursorline](https://user-images.githubusercontent.com/8505073/67039867-93101e80-f122-11e9-8ea8-1928e98a119a.png)

![cursorline](https://user-images.githubusercontent.com/8505073/67039884-9acfc300-f122-11e9-9bdb-dc42c79d04cd.png)

The average latency is multiplied by about 6.

**Comment by andymass** [comment]
There should be no cursorline when pum is visible right?

**Comment by lacygoill** [comment]
On my machine, the cursorline is still visible even when the pum is open (before and after https://github.com/vim/vim/commit/c2b97643a82bb9fbd202312dac4aa995f92e9e5b).

I used the pum to illustrate the issue, because it provides an easy way to convey that the latency has increased; but the issue is really about the latency which in some part of a buffer can become very noticeable.

In practice, I rarely use the cursorline (only in a few special buffers such as a quickfix one). However, in my vimrc I was setting by default `'cursorlineopt'` to the value `screenline` (`set culopt=screenline`), and because of that, I've noticed a bigger latency than usual, even in regular buffers where I don't set `'cursorline'`.

So now, I've stopped tweaking `'cursorlineopt'`, and I only set it (via custom mappings or filetype plugins) when I also set `'cursorline'` (which I guess makes more sense); I don't think I will experience the issue as frequently anymore; but I still thought it was worth being reported, in case other people – who use the cursorline frequently – face this issue.

**Comment by brammool** [comment]
I see that when 'cursorline' is set the main loop redraws just about everything.  it's not just that change you point to.  Let me try reduce the redrawing and find what tests fail then.  I do think we added tests for when the cursor line was not updated properly.

**Comment by chrisbra** [comment]
I suspected something similar because I could not reproduce the bug in #3893 anymore. The test added from there, should start to fail then.
