### ISSUE TITLE
"E730: using List as a String" when using `popup_setoptions()`

### ISSUE THREAD

**Issue by Yggdroot** [vim/vim#5081]
**Describe the bug**

"E730: using List as a String" when using `popup_setoptions()`

**To Reproduce**

test.vim
```vim
let id = popup_create(bufnr('%'), {"maxheight": 20})
let opt = popup_getoptions(id)

"echom string(opt)
call popup_setoptions(id, opt)
```
1. vim test.vim
2. :so %
3. errors occur

**Expected behavior**
There should be no error.

**Environment (please complete the following information):**
 - Vim version: 8.1.2151
 - OS: Linux
 - Terminal: 

**Additional context**

I find the value of `popup_getoptions(id)` is `{'highlight': '', 'mousemoved': [0, 0, 0], 'line': 0, 'close': 'none', 'time': 0, 'drag': 0, 'cursorline': 0, 'minheight': 0, 'wrap': 1, 'pos': 'topleft', 'minwidth': 0, 'fixed': 0, 'col': 0, 'maxwidth': 0, 'zindex': 50, 'firstline': 0, 'title': '', 'scrollbar': 1, 'moved': [0, 0, 0], 'mapping': 1, 'tabpage': 0, 'resize': 0, 'maxheight': 20}`, if remove `'mousemoved': [0, 0, 0]` and `'moved': [0, 0, 0]`, the errors disappear.

**Comment by brammool** [comment]
> **Describe the bug**
> 
> "E730: using List as a String" when using `popup_setoptions()`
> 
> **To Reproduce**
> 
> test.vim
> ```vim
> let id = popup_create(bufnr('%'), {"maxheight": 20})
> let opt = popup_getoptions(id)
> 
> "echom string(opt)
> call popup_setoptions(id, opt)
> ```
> 1. vim test.vim
> 2. :so %
> 3. errors occur
> 
> **Expected behavior**
> There should be no error.
> 
> **Environment (please complete the following information):**
>  - Vim version: 8.1.2151
>  - OS: Linux
>  - Terminal: 
> 
> **Additional context**
> 
> I find the value of `popup_getoptions(id)` is `{'highlight': '',
> 'mousemoved': [0, 0, 0], 'line': 0, 'close': 'none', 'time': 0,
> 'drag': 0, 'cursorline': 0, 'minheight': 0, 'wrap': 1, 'pos':
> 'topleft', 'minwidth': 0, 'fixed': 0, 'col': 0, 'maxwidth': 0,
> 'zindex': 50, 'firstline': 0, 'title': '', 'scrollbar': 1, 'moved':
> [0, 0, 0], 'mapping': 1, 'tabpage': 0, 'resize': 0, 'maxheight': 20}`,
> if remove `'mousemoved': [0, 0, 0]` and `'moved': [0, 0, 0]`, the
> errors disappear.

Well, that does work as documented.  I suppose the question then becomes
that the "moved" and "mousemoved" options of popup_setoptions() should
also accept the list of numbers.  

-- 
A fool must search for a greater fool to find admiration.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
