### ISSUE TITLE
popup_setoptions() does not take effect

### ISSUE THREAD

**Issue by Yggdroot** [vim/vim#5082]
**Describe the bug**

popup_setoptions() does not take effect

**To Reproduce**

test.vim
```vim
let id = 0
while 1
    let c = getchar(0)
    if nr2char(c) == "p"
        let id = popup_create(bufnr('%'), {'maxheight': 40, 'maxwidth': 70})
        redraw
    elseif nr2char(c) == "f"
        let opt = popup_getoptions(id)
        unlet opt.mousemoved
        unlet opt.moved
        let opt.filter = "popup_filter_menu"
        call popup_setoptions(id, opt)
    elseif nr2char(c) == "q"
        call popup_close(id)
        break
    endif
endwhile

```
1. vim test.vim
2. :so %
3. type p, a popup window is displayed
4. type f,   let opt.filter = "popup_filter_menu"

**Expected behavior**
type `<ESC>`, the popup window should be closed just like what popup_menu() behaves.

**Environment (please complete the following information):**
 - Vim version: 8.1.2151
 - OS: Linux
 - Terminal: 

**Additional context**

It is strongly recommended that the popup window can be focusable, thanks.

**Comment by brammool** [comment]
> **Describe the bug**
> 
> popup_setoptions() does not take effect
> 
> **To Reproduce**
> 
> test.vim
> ```vim
> let id = 0
> while 1
>     let c = getchar(0)
>     if nr2char(c) == "p"
>         let id = popup_create(bufnr('%'), {'maxheight': 40, 'maxwidth': 70})
>         redraw
>     elseif nr2char(c) == "f"
>         let opt = popup_getoptions(id)
>         unlet opt.mousemoved
>         unlet opt.moved
>         let opt.filter = "popup_filter_menu"
>         call popup_setoptions(id, opt)
>     elseif nr2char(c) == "q"
>         call popup_close(id)
>         break
>     endif
> endwhile
> 
> ```
> 1. vim test.vim
> 2. :so %
> 3. type p, a popup window is displayed
> 4. type f,   let opt.filter = "popup_filter_menu"
> 
> **Expected behavior**
> type `<ESC>`, the popup window should be closed just like what popup_menu() behaves.
> 
> **Environment (please complete the following information):**
>  - Vim version: 8.1.2151
>  - OS: Linux
>  - Terminal: 
> 
> **Additional context**
> 
> It is strongly recommended that the popup window can be focusable, thanks.

The popup_setoptions() works, but since the script loops and calls
getchar() this eats all the typed characters.  It works better if you
put "break" after the popup_setoptions() call.  Esc works then.

You can't see the effect of "j" and "k" then, this changes helps for
that:

          let opt = popup_getoptions(id)
          unlet opt.mousemoved
          unlet opt.moved
          let opt.filter = "popup_filter_menu"
+         let opt.cursorline = 1
          call popup_setoptions(id, opt)
+	  break


-- 
ARTHUR: The swallow may fly south with the sun, or the house martin or the
        plover seek warmer hot lands in winter, yet these are not strangers to
        our land.
SOLDIER: Are you suggesting coconuts migrate?
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Yggdroot** [comment]
There is another issue:
test.vim
```vim
let id = 0
while 1
    let c = getchar(0)
    if nr2char(c) == "p"
        let id = popup_create(bufnr('%'), {'maxheight': 10, 'maxwidth': 70})
        redraw
    elseif nr2char(c) == "f"
        let opt = popup_getoptions(id)
        unlet opt.mousemoved
        unlet opt.moved
        let opt.filter = "popup_filter_menu"
        let opt.cursorline = 1
        call popup_setoptions(id, opt)
        break
    elseif nr2char(c) == "q"
        call popup_close(id)
        break
    endif
endwhile
```
1. vim test.vim
2. if `call popup_create(bufnr('%'), {'maxheight': 10, 'maxwidth': 70})`, I can use the mouse wheel to scroll the popup window.
 3.  :call popup_clear() then :so %
 4. type p, a popup window is displayed
 5. type f,  I can not use the mouse wheel to scroll the popup window.

**Comment by brammool** [comment]
> There is another issue:
> test.vim
> ```vim
> let id = 0
> while 1
>     let c = getchar(0)
>     if nr2char(c) == "p"
>         let id = popup_create(bufnr('%'), {'maxheight': 10, 'maxwidth': 70})
>         redraw
>     elseif nr2char(c) == "f"
>         let opt = popup_getoptions(id)
>         unlet opt.mousemoved
>         unlet opt.moved
>         let opt.filter = "popup_filter_menu"
>         let opt.cursorline = 1
>         call popup_setoptions(id, opt)
>         break
>     elseif nr2char(c) == "q"
>         call popup_close(id)
>         break
>     endif
> endwhile
> ```
> 1. vim test.vim
> 2. if `call popup_create(bufnr('%'), {'maxheight': 10, 'maxwidth': 70})`, I can use the mouse wheel to scroll the popup window.
>  3.  :call popup_clear() then :so %
>  4. type p, a popup window is displayed
>  5. type f,  I can not use the mouse wheel to scroll the popup window.

The getchar() function eats the scroll wheel events.

-- 
BEDEVERE: And that, my lord, is how we know the Earth to be banana-shaped.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
