### ISSUE TITLE
24-bit color not restored correctly on Windows

### ISSUE THREAD

**Issue by lzybkr** [vim/vim#5092]
**Describe the bug**

If the terminal uses 24-bit color before starting vim, the colors are not restored correctly.
This happens because vim uses screen scraping to save the screen and those legacy console apis do not support 24-bit color.
One possible fix is to use the alternate screen buffer. I tried this myself and it seems to work. It also seems to be what the Linux version of vim does as the problem does not reproduce if you run vim from WSL.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Ensure the terminal displays some 24-bit color, e.g. run this [PowerShell script](https://gist.github.com/lzybkr/05bf1fe79852ee5f6facaf62999e53a7)
2. Run vim.exe
3. Exit

**Expected behavior**
The screen is restored without colors changing.

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/2148248/67155274-b375df80-f2c0-11e9-97a1-1cada0ad2214.png)

After:
![image](https://user-images.githubusercontent.com/2148248/67155278-bec90b00-f2c0-11e9-95bd-9dd456ac1854.png)

**Environment (please complete the following information):**
 - Vim version 8.1
 - OS: Windows 10 1903
 - Terminal: Windows Terminal

**Additional context**
My screen shots demonstrate a possible (minimally tested) fix. I'm guessing a better fix is possible though, maybe using a non-Windows code path.

**Comment by lzybkr** [comment]
For anyone else wanting a workaround, here is a PowerShell snippet you can add to your profile:

```powershell
if ($PSVersionTable.OS -like '*Windows*' -and $host.UI.SupportsVirtualTerminal) {
    function vim
    {
        Write-Host "`e[?1049h"
        vim.exe @args
        Write-Host "`e[?1049l"
    }
}
```

**Comment by heaths** [comment]
Thanks for the workaround. Unfortunately, while it works in Terminal (Preview) it does not work in conhost. When the original buffer is restored, the old contents appear, but the current line / cursor appear at the top of the window above the old buffer content that was not erased.

**Comment by ghost** [comment]
There is no way to get the 24-bit color number already drawn on the screen.

In the past, I wrote a patch to switch to another screen with an escape sequence.
However, I was at a loss whether to consider the case where Vim was restarted from within the :terminal. After all, I have not submitted the patch.

Try a little more thought.

**Comment by heaths** [comment]
Long-time vim user and I never new about `:terminal` (just Ctrl+Z, which uses the right colors going forward). That presents other issues. Color is initially wrong as mentioned, but characters are also wrong. In pwsh, my `[Console]::OutputEncoding` is `UTF8` (default is ibm437 on my machine, in which this problem also occurs). When I run `:terminal` (with `shell` set to "pwsh), I see this:

With ibm437, I see something slightly better:

![image](https://user-images.githubusercontent.com/1532486/70670445-d1f7b780-1c2d-11ea-8914-bbd09cb06cf0.png)

![image](https://user-images.githubusercontent.com/1532486/70670428-c60bf580-1c2d-11ea-9f49-0de1fe5e25bf.png)

So the initial console output encoding (according to pwsh, at least - conhost oem code page is still 437 in both cases) also impacts the embedded term.

**Comment by heaths** [comment]
This should be resolved in vim9, though you may want to set `termguicolors` explicitly:

```vim
if has('vcon')
  set termguicolors
endif
```

**Comment by k-takata** [comment]
Closing.
