### ISSUE TITLE
listener call back "added" parameter is wrong

### ISSUE THREAD

**Issue by andymass** [vim/vim#5105]
Listener callbacks provide a granular list of edits as well as "summary" parameters start, end, and added:

    listener_add({callback} [, {buf}])			*listener_add()*
                    ...
		    a:added	total number of lines added, negative if lines
				were deleted
                    ...
	    func Listener(bufnr, start, end, added, changes)

**Describe the bug**

`invoke_listeners` does not seem to compute the total number of lines added, just the last:

    for (li = buf->b_recorded_changes->lv_first; li != NULL; li = li->li_next)
    {
         ...
	     added = dict_get_number(li->li_tv.vval.v_dict, (char_u *)"added");
    }

**To Reproduce**
Detailed steps to reproduce the behavior:
Run `vim --clean test.py` then
```
:normal! idef fun():
:let g:g = [] | call listener_add({->execute('let g:g+=[a:000]')})
:normal! o
:echo g:g
```

The first 'added' parameter is zero, despite lines being added.

    [[1, 2, 3, 0, [{'lnum': 2, 'col': 1, 'added': 1, 'end': 2}, {'lnum': 2, 'col': 1, 'added': 0, 'end': 3}]],
      [1, 2, 3, 0, [{'lnum': 2, 'col': 3, 'added': 0, 'end': 3}, {'lnum': 2, 'col': 2, 'added': 0, 'end': 3}, {'lnum': 2, 'col': 1, 'added': 0, 'end': 3}, {'lnum': 2, 'col': 1, 'added': 0, 'end': 3}]]]

**Expected behavior**

Documentation suggests that `a:added` should reflect the total number of lines added.

**Comment by brammool** [comment]
The "added" value is the number of lines added (negative if deleted) in each change.  They don't add up for multiple changes.  I'll remove "total" from the help, apparently that was confusing.

**Comment by andymass** [comment]
Sorry I'm still a bit confused.  "Added" for each change in the list makes sense.  But the listener callback has an a:added parameter which is independent  What does this mean?

**Comment by brammool** [comment]
> Sorry I'm still a bit confused.  "Added" for each change in the list
> makes sense.  But the listener callback has an a:added parameter which
> is independent  What does this mean?

Ah, I didn't read it correctly, you mean the "added" argument passed to
the callback, not the "added" fields in the list.

Yeah, the start and end are computed from all the entries, thus "added"
should be too.


-- 
The word "leader" is derived from the word "lead", as in the material that
bullets are made out of.  The term "leader" was popularized at about the same
time as the invention of firearms.  It grew out of the observation that the
person in charge of every organization was the person whom everyone wanted to
fill with hot lead.
   I don't recomment this; it's just a point of historical interest.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
