### ISSUE TITLE
cursorline should not be displayed other than the popup window

### ISSUE THREAD

**Issue by Yggdroot** [vim/vim#5112]
**Describe the bug**
cursorline should not be displayed other than the popup window

**To Reproduce**
test.vim
```vim
call popup_create(bufnr('%'), #{cursorline:1, line:"cursor-1", col:"cursor", pos:"botleft", minheight:4, maxwidth:80})
"call popup_create(bufnr('%'), #{cursorline:1, line:"cursor-1", col:"cursor", pos:"botleft", minheight:4, maxwidth:80})
"call popup_create(bufnr('%'), #{cursorline:1, line:"cursor-1", col:"cursor", pos:"botleft", minheight:4, maxwidth:80})
```
1. :so %
2. cursorline also is displayed in the main window

**Expected behavior**
cursorline should not be displayed other than the popup window

**Screenshots**
![pop](https://user-images.githubusercontent.com/2705841/67455937-b4609580-f661-11e9-950d-b946cac46f19.png)

**Environment (please complete the following information):**
 - Vim version : 8.1.2151
 - OS:  CentOS 7
 - Terminal: GNOME Terminal

**Additional context**
It would be much appreciated if the pop up window can be focusable.

**Comment by brammool** [comment]
I really don't see the reason why you want to have the same buffer in a normal window and in a popup window.
The highlighting is done with a sign, which is local to the buffer, not the window.

**Comment by Yggdroot** [comment]
It is OK for me if it is by design. I can use `win_execute(id, 'set cursorline')` instead.
