### ISSUE TITLE
langmap doesn't work in vimrc in gVim on Windows unless encoding is set explicitly.

### ISSUE THREAD

**Issue by fj128** [vim/vim#5114]
If I put the line

     set langmap=ФИСВУАПРШОЛДЬТЩЗЙКЫЕГМЦЧНЯ;ABCDEFGHIJKLMNOPQRSTUVWXYZ,фисвуапршолдьтщзйкыегмцчня;abcdefghijklmnopqrstuvwxyz

into c:\users\me\vimfiles\vimrc, then start gvim, I get "E357: 'langmap': Matching character missing for Ð".

I don't get this error if I execute that line directly or if I open vimrc and `:source %`.

`langmap` appears to be set and working correctly despite the error message (!!!)

Adding `" vim: fileencoding=utf-8` modeline doesn't help.

If I start a console vim with that line in vimrc, I see 9 empty lines and "Press ENTER or type command to continue" on startup, then the usual banner. `langmap` is set all wrong though, with those "Ð" characters.

Now, as I discovered in the process of writing this, if I explicitly `set encoding=utf-8` before setting langmap, all my problems go away (and without that console vim displays utf-8 text incorrectly anyway, because it assumes encoding=cp1252). But if I check `set encoding?` in gVim, it is set to utf-8 already!

It's looks like gVim changes its encoding somewhere during startup and reinterprets langmap correctly, leading to this weird behavior.

**Environment (please complete the following information):**
 - VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 23 2019 22:02:12)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-2204
 - OS: Windows 7

**Comment by chrisbra** [comment]
The encoding option on Windows by default is not UTF-8, so you most likely change it after your langmap setting. 

It is a good recommendation, to set the encoding early in your .vimrc. You might as well set the `scriptencoding utf-8` early in your startup file. So that is not a bug.

> Adding " vim: fileencoding=utf-8 modeline doesn't help.

Note: That has never worked. By the time the modeline is read, the file has already been sourced with the wrong encoding.

**Comment by brammool** [comment]
> If I put the line
> 
>      set langmap=ФИСВУАПРШОЛДЬТЩЗЙКЫЕГМЦЧНЯ;ABCDEFGHIJKLMNOPQRSTUVWXYZ,фисвуапршолдьтщзйкыегмцчня;abcdefghijklmnopqrstuvwxyz
> 
> into c:\users\me\vimfiles\vimrc, then start gvim, I get "E357: 'langmap': Matching character missing for Ð".
> 
> I don't get this error if I execute that line directly or if I open vimrc and `:source %`.
> 
> `langmap` appears to be set and working correctly despite the error message (!!!)
> 
> Adding `" vim: fileencoding=utf-8` modeline doesn't help.
> 
> If I start a console vim with that line in vimrc, I see 9 empty lines and "Press ENTER or type command to continue" on startup, then the usual banner. `langmap` is set all wrong though, with those "Ð" characters.
> 
> Now, as I discovered in the process of writing this, if I explicitly `set encoding=utf-8` before setting langmap, all my problems go away (and without that console vim displays utf-8 text incorrectly anyway, because it assumes encoding=cp1252). But if I check `set encoding?` in gVim, it is set to utf-8 already!
> 
> It's looks like gVim changes its encoding somewhere during startup and reinterprets langmap correctly, leading to this weird behavior.
> 
> **Environment (please complete the following information):**
>  - VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 23 2019 22:02:12)
> MS-Windows 64-bit GUI version with OLE support
> Included patches: 1-2204
>  - OS: Windows 7

Try using :scriptencoding.

-- 
Scientists decoded the first message from an alien civilization:
        SIMPLY SEND 6 TIMES 10 TO THE 50 ATOMS OF HYDROGEN TO THE STAR
SYSTEM AT THE TOP OF THE LIST, CROSS OFF THAT STAR SYSTEM, THEN PUT
YOUR STAR SYSTEM AT THE BOTTOM OF THE LIST AND SEND IT TO 100 OTHER
STAR SYSTEMS.  WITHIN ONE TENTH GALACTIC ROTATION YOU WILL RECEIVE
ENOUGH HYDROGREN TO POWER YOUR CIVILIZATION UNTIL ENTROPY REACHES ITS
MAXIMUM!  IT REALLY WORKS!

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by fj128** [comment]
@chrisbra
> The encoding option on Windows by default is not UTF-8, so you most likely change it after your langmap setting.

Oh, it turns out that I totally did, specifically in gvimrc even, my bad, I searched for "encoding" but used "enc" there :(

It would be nice if the encoding _was_ utf-8 by default on Windows, especially for gVim that doesn't have to deal with console nonsense, but oh well.

**Comment by chrisbra** [comment]
that has been discussed several times in the past and not be done to be on the safe side.
