### ISSUE TITLE
Customisable column indicator for folds

### ISSUE THREAD

**Issue by Jeansen** [vim/vim#5115]
The help doc says with respect to folds:

```
An open fold is indicated with a column that has a '-' at the top and '|'
characters below it.  This column stops where the open fold stops.  When folds
nest, the nested fold is one character right of the fold it's contained in.

A closed fold is indicated with a '+'.
```

I'd like to be able to change these characters via my .vimrc. But so far, I cannot see how and think it is not yet possible. I know, it is a cosmetic (low priority) request. But if it is not too much work, I'd be happe to see it in some future release.

**Comment by chrisbra** [comment]
why do you want to customize it? The advantage of being hard coded is, that everybody right now already knows the meaning, while changing it, it might be confusing.

**Comment by Jeansen** [comment]
Well, generally speaking it is a matter of taste. And there are some good block/border symbols to use from Unicode. So it would look similar when using the `tree` command. On the other hand, IF someone changes it, then he/she knows what he/she has changed. I do not suggest to change the default. Just to make it configurable. Otherwise your argument would be true for almost every default in VIM mapped to something custom ;-)

**Comment by diego-treitos** [comment]
Customizable in neovim now: https://github.com/vim/vim/commit/3aca5a6fbcfbf5f4492b9ea0c4308ac524d33606#diff-442131dbc53d601ff38edcc95c73c09272934f92f7cf6601738cc6ceaf8a1e48

**Comment by chrisbra** [comment]
so closing, since fixed by https://github.com/vim/vim/releases/tag/v8.2.2524

**Comment by Jeansen** [comment]
Kudos to @brammool and everyone involved for implementing this and making a happy "vimer" even more happy ;-)
