### ISSUE TITLE
composer.json no longer detected

### ISSUE THREAD

**Issue by glensc** [vim/vim#512]
after [7.4.860](https://github.com/vim/vim/releases/tag/v7.4.860) opening composer.json in vim no longer highlights the file

typing `:set filetype` prints `filetype=json` but  there is no actual hiliting! 

the underlying problems seems to be that no `syntax/json.vim` present in vim-rt, which is weird,
as it is [present in the tree](https://github.com/vim/vim/blob/v7.4.860/runtime/syntax/json.vim)

perhaps as json.vim [was added in Jul 19, 2014](https://github.com/vim/vim/commit/07d87790f1e733d69bd7910bf049adeeb6d0f338#diff-f3de53aba75880747f42c5bb12bc0966) but vim-7.4 tar was released in 2013 and thus never appeared as patch diff on ftp?

```
➔ grep json 7.4.*
7.4.860:! au BufNewFile,BufRead *.js,*.javascript,*.es,*.jsx,*.json   setf javascript
7.4.860:+ au BufNewFile,BufRead *.json,*.jsonp          setf json
```

**Comment by glensc** [comment]
@brammool "setf json" should be rolled back to "setf javascript" as there's no "json" in 7.4 runtime files. please see the referenced commit in github issue.

**Comment by chrisbra** [comment]
What is vim-rt? A json.vim syntax file is clearly available at the current runtime tree, see [here](https://github.com/vim/vim/blob/master/runtime/syntax/json.vim). So perhaps just update your runtime files.

I am wondering, why you have the patch from 7.4.860, but not updated all your other runtime files?

**Comment by BlackIkeEagle** [comment]
@glensc Are you using Arch Linux ?

Then I assume you are using vim from my repo:

```
$ pacman -Ql vim-rt | grep json
vim-rt /usr/share/vim/vim74/ftplugin/json.vim
vim-rt /usr/share/vim/vim74/indent/json.vim
vim-rt /usr/share/vim/vim74/syntax/json.vim
```

@chrisbra If my assumption is correct, vim-rt is a the package name for the runtime files.

**Comment by glensc** [comment]
vim-rt is just convention to call vim runtime files, it used to be separate tarball prior 7.4.

@chrisbra i built my vim using [7.4 tarball](http://ftp.vim.org/pub/vim/unix/vim-7.4.tar.bz2) + [all patches from ftp](http://ftp.vim.org/pub/editors/vim/patches/7.4).
do the patches require updating runtime files separately? i assumed patches update runtime files too, no?

@BlackIkeEagle where is your repo? link? and if i was using yours, i wouldn't have this issue, as you paste, you do have json.vim syntax. and no, my .spec is here:
https://github.com/pld-linux/vim/blob/master/vim.spec

**Comment by chrisbra** [comment]
@glensc runtime files are more often updated, and not always get an extra official patch number. Therefore, I suggest to simply update the complete runtime files from the official repo.

**Comment by glensc** [comment]
@chrisbra that makes the from patches rather pointless

**Comment by glensc** [comment]
looks like fedora also switched to use git full checkout instead patches from ftp. likely due the same issue i'm having here

http://pkgs.fedoraproject.org/cgit/vim.git/commit/?id=56ffd8ab42f65a58b0f36c6d5cfb991d02222ebe

the timeline kind of matches (7.4.909 > 7.4.860)

**Comment by chrisbra** [comment]
the patches come from an old time, when vim was still developed from a central cvs server. Nowadays I don't see a reason to still use the patches, except for using an established workflow, which leads to some inconsistencies as you noticed. Note, see also the current discussion on [vim-dev](https://groups.google.com/d/msg/vim_dev/dAXpcpHmVw4/PtJIrRMACQAJ)

My opinion is just clone the vim repository and start working from there. It is just so much easier.

**Comment by BlackIkeEagle** [comment]
@glensc I would assume there is an issue in the pld-linux package then since other distro's have the runtime files. But I also build from this git repo, and not from patches.

**Comment by glensc** [comment]
@BlackIkeEagle 
1. give link to your package
2. please read again my posts, your diagonal reading missed point in messages i posted.

**Comment by glensc** [comment]
will switch from tarball+patches built to github git checkout

but i still think the patches should not add dependencies to runtime files that are not covered by the patches themselves, to keep existing workflow like this still functional:
- download 7.4 tarball (or zip)
- apply each patch from patches dir from ftp

**Comment by BlackIkeEagle** [comment]
@glensc 
1. https://github.com/herecura/vim (http://repo.herecura.eu) specific for Arch Linux
2. I don't see what I've missed. I just stated I'm also not building from patches so I'm unaware of the fact that some runtime files are missing when building from patches.

**Comment by glensc** [comment]
@BlackIkeEagle 

you missed that 7.4 tarball + patches DO contain runtime files
https://github.com/vim/vim/issues/512#issuecomment-166536921

just 7.4.860, a patch from ftp, changes syntax to use json, which is not updated by ftp patches and not present in 7.4 tarball. 7.4 tarball contains only javascript.vim syntax, no json.vim.
https://github.com/vim/vim/issues/512#issue-119947313

and therefore imho the patches on ftp, should not use the new json.vim syntax, but stick to javascript.vim
https://github.com/vim/vim/issues/512#issuecomment-166352626

like here:
https://github.com/pld-linux/vim/commit/55c10319d4a34aa45d11881f7fba88c96c01d8bc
