### ISSUE TITLE
Colorscheme's always diverge from source

### ISSUE THREAD

**Issue by redfoggg** [vim/vim#5127]
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Describe the bug**
No matter what is the colorscheme i chose, they never match with the expectation, the colors of variables or functions etc, in this issue i will use only the dracula theme for example, but i try others as well and all of them with no exception get's the same problem.

**Expected behavior**
Colors matches the expected match.

**Screenshots**
For example, dracula theme i get:
![Captura de tela de 2019-10-26 17-56-20](https://user-images.githubusercontent.com/32973761/67625848-021ffe00-f81a-11e9-90d1-7a67ced397fc.png)

The dracula theme i expect:
<img width="1028" alt="javascript" src="https://user-images.githubusercontent.com/32973761/67625864-50350180-f81a-11e9-8fbb-11acf0ac9040.png">

**Environment (please complete the following information):**
 - Vim version 8.0.1453
 - OS: Linux Mint 19.2 Tina 
 - Terminal: Tmux and zsh

**.vimrc Files**
![Captura de tela de 2019-10-26 18-04-41](https://user-images.githubusercontent.com/32973761/67625931-1e706a80-f81b-11e9-8551-359dea16f9ee.png)

**.tmux.conf File**
![Captura de tela de 2019-10-26 18-05-51](https://user-images.githubusercontent.com/32973761/67625947-465fce00-f81b-11e9-9509-cd7e28e49284.png)

**Comment by chrisbra** [comment]
Where does the screenshot come from, that describes how you expect the dracula theme to look like?  It looks more like that shows an enhanced syntax plugin, that is not available with default vim. Also, your issues actually looks like a configuration issue and not a Vim bug. Please use in that case `vi.stackexchange.com` or the vim mailinglist. We cannot provide individual support here.

**Comment by chrisbra** [comment]
For a starter, you should compare the output of `:hi` if the colors look like what you expect. If they don't, it might be a configuration issue of your terminal or a bug of the colorscheme. Simply showing two different screenshots of different contents(!) does not really help here. Also, it is usually easier to first set it up in  `gvim`, because you can rule out terminal configuration.

**Comment by redfoggg** [comment]
Okay
