### ISSUE TITLE
Lines starting with `.sh` are considered as blank lines

### ISSUE THREAD

**Issue by Alex-Canales** [vim/vim#5128]
**Describe the bug**

When a line start with `.sh`, and whatever characters are after, the line is considered as a blank line.

**To Reproduce**

Open a file with the following or paste it in Vim.

```
Line 1
Line 2

Line 4
.sh
Line 6

Line 8
.show { display: block; }
Line 10

Line 12
```

**Actual behaviour**

* The lines starting with `.sh` are considered as blank lines.
* The `{` and `}` operators jump to lines 3, 5, 7, 9 and 11.
* Placing the cursor at line 4 and using the `ip` operator selects only the line 4.
* Placing the cursor at line 8 and using the `ip` operator selects only the line 8.

**Expected behavior**

* The lines starting with `.sh` should not be considered as blank lines.
* The `{` and `}` operators should jump only to lines 3, 7 and 11.
* Placing the cursor at line 4 and using the `ip` operator should select the lines 4, 5 and 6.
* Placing the cursor at line 8 and using the `ip` operator should select the lines 8, 9 and 10.

**Environment**

 - Vim version: see below
 - OS: **Linux Mint 19.1 Tessa 64-bit**
 - Terminal: **mate-terminal/1.20.0**

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 06 2019 17:31:41)
Included patches: 1-1453
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Small version without GUI.  Features included (+) or not (-):
+acl               -extra_search      -mouse_netterm     -tag_old_static
-arabic            -farsi             -mouse_sgr         -tag_any_white
-autocmd           -file_in_path      -mouse_sysmouse    -tcl
-autoservername    -find_in_path      -mouse_urxvt       -termguicolors
-balloon_eval      -float             -mouse_xterm       -terminal
-balloon_eval_term -folding           +multi_byte        +terminfo
-browse            -footer            -multi_lang        -termresponse
+builtin_terms     +fork()            -mzscheme          -textobjects
-byte_offset       -gettext           -netbeans_intg     -timers
-channel           -hangul_input      -num64             -title
-cindent           +iconv             +packages          -toolbar
-clientserver      -insert_expand     -path_extra        -user_commands
-clipboard         -job               -perl              +vertsplit
-cmdline_compl     +jumplist          -persistent_undo   -virtualedit
+cmdline_hist      -keymap            -printer           +visual
-cmdline_info      -lambda            -profile           -visualextra
-comments          -langmap           -python            -viminfo
-conceal           -libcall           -python3           -vreplace
-cryptv            -linebreak         -quickfix          +wildignore
-cscope            -lispindent        -reltime           -wildmenu
-cursorbind        -listcmds          -rightleft         +windows
-cursorshape       -localmap          -ruby              +writebackup
-dialog            -lua               -scrollbind        -X11
-diff              -menu              -signs             +xfontset
-digraphs          -mksession         -smartindent       -xim
-dnd               -modify_fname      -startuptime       -xpm
-ebcdic            -mouse             -statusline        -xsmp
-emacs_tags        -mouse_dec         -sun_workshop      -xterm_clipboard
-eval              -mouse_gpm         -syntax            -xterm_save
+ex_extra          -mouse_jsbterm     +tag_binary        
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-8l5tlu/vim-8.0.1453=. -fstack-protector-strong -Wformat -Werror=format-security -DTINY_VIMRC -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim    -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo  -lselinux -lacl -lattr -ldl
```

**Additional context**

This bug also appears in neovim version 0.4.2. [See issue #11300.](https://github.com/neovim/neovim/issues/11300#issue-512918269)

**Comment by Alex-Canales** [comment]
I was wrong, this is not a bug. I quote the explanation by @justinmk from the neovim issue I opened.

> See :help paragraph , it regard it as a nroff macro. Weird but true.
>
> More-flexible paragraph has been on Bram's todo.txt for a long time. Would be great to have, but not going to track it here.

After reading the `:help paragraph` and `:help 'paragraphs'` this is an expected behaviour.

**Comment by tonymec** [comment]
I suppose that when editing a file which is not nroff text, the `'paragraphs'` and `'sections'` options could be set empty. These options are global, however, so the default should be reinstated when editing files which **are** nroff output.

**Comment by justinmk** [comment]
> These options are global, however, so the default should be reinstated when editing files which **are** nroff output.

In other words, almost never :)

**Comment by tonymec** [comment]
Maybe never for you or me, but not for people who use Vim as, for example, a pager for manual pages.

Best regards,
Tony.
