### ISSUE TITLE
height of entered window reset unexpectedly when leaving the command-line window

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#5130]
**Describe the bug**

When leaving the command-line window, the height of the entered window is reset to an unexpected value if the geometry of the terminal has changed after the command-line window was entered.

**To Reproduce**

1. Run this shell command:

       vim -Nu NONE +'au WinEnter * wincmd _' +'bo sp' +'set lines=10'

2. Press `q:` to open the command-line window.
3. Run `:set lines=30` to increase the height of the terminal from 10 lines to 30 lines.
4. Run `:q` to close the command-line window.

The window is `6` lines high.

**Expected behavior**

The window is `26` lines high, because of the autocmd running `wincmd _` on `WinEnter`.

**Environment**

 - Vim version: 8.1 Included patches: 1-2225
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

I could be wrong, but I think it's a bug because `WinEnter` is fired – in the context of the second window – *after* `CmdWinLeave` is fired; so `wincmd _` should maximize the latter after the command-line window has been closed.

Besides, if you replace `:bo sp` with `:sp`:

   - in the context of the command-line window, the previous window number changes from `2` to `1`
   - the issue is not triggered

So, if the autocmd succeeds in maximizing the window which is entered after leaving the command-line window while the previous window is the top one, I would expect it to also succeed when the previous window is the bottom one.

---

I think that the height of the last window which is entered is `6` because it's the height of the old command-line window (`4`) + `2` for the status line and the single text buffer line of the window which was above.
This is confirmed by the fact that if you set `'winminheight'` to `0`, the height of the last window which is entered is `7` (height of the old command-line window + `1` for the status line which was above).

---

This additional autocmd can be used as a workaround:

    au CmdWinLeave * au CursorMoved * ++once wincmd _

Example:

                   vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
    vim -Nu NONE +'au CmdWinLeave * au CursorMoved * ++once wincmd _' +'au WinEnter * wincmd _' +'bo sp' +'set lines=10'
    " press `q:`
    :set lines=30
    :q

---

I frequently encounter this issue when I use tmux and close a pane which changes the geometry of the terminal from Vim's point of view. I have a plugin to automatically set the height of the focused window; it succeeds into maximizing its height after leaving the command-line window; but Vim resets its height right afterward, if the geometry of the terminal has changed after the command-line window was opened.

**Comment by brammool** [comment]
I'm not quite sure what you are trying to do.  I do see that when 'lines' change while the command line window is open, restoring the window sizes causes trouble.  I'll make it so that window sizes won't be restored if 'lines' changes.  I would not know what to restore them to then, so might as well skip it.
