### ISSUE TITLE
can not directly squash a non-focused window to zero lines

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#5131]
**Describe the bug**

`:resize 0` fails to squash a non-focused window to zero lines, even when `'winminheight'` is set to `0`.

**To Reproduce**

Run this shell command:

    vim -Nu NONE +'set wmh=0|sp|call win_execute(win_getid(2), "resize 0")'

The bottom window is `1` line high.

**Expected behavior**

The bottom window is squashed to `0` lines.

**Environment**

 - Vim version: 8.1 Included patches: 1-2225
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

There may be more, but I can see two explanations.

First explanation:

Vim temporarily focuses the bottom window; and the cursor must be drawn somewhere, so the height of the window is set to `1`.

But that can't be right, because you can invoke `win_execute()` to execute an arbitrary command in a squashed window, without the height of the latter being reset to `1`:

    vim -Nu NONE +'set wmh=0|sp|wincmd _|call win_execute(win_getid(2), "echo 123")'

Notice how the bottom window is still squashed, even though it has been temporarily focused by `win_execute()`.

---

Second explanation:

When `:resize` was implemented, it could only be run in the context of the focused window, which can not be squashed because the cursor has to be drawn somewhere.
Therefore, it did not make sense for `:resize` to accept the `0` argument; the closest height it could accept was `1`, so it automatically turned `0` into `1`.
However, now, thanks to `win_execute()`, `:resize` can be run in the context of a *non*-focused window which *can* be squashed; so the `0` argument *does* make sense, and `:resize` should not alter it when it's run in the context of a non-focused window.

---

One could argue that you can still squash a non-focused window by maximizing the focused window (`:wincmd _`); but that's an indirect way of achieving the desired result, which can have other side-effects (i.e. squash other windows which you don't want to).

**Comment by brammool** [comment]
It's the first explanation: win_execute() makes the window the current window, which must always have at least one line visible.
You can do it with "2resize 0", put the window number before :resize.

**Comment by tonymec** [comment]
To always squash all non-current windows to zero lines, you can use my "Rolodex Vim" settings: https://vim.fandom.com/wiki/Window_zooming_convenience#Rolodex_Vim

**Comment by tonymec** [comment]
And BTW, I just saw on Wikipedia that the Rolodex was invented in Denmark in 1956. Didn't know it was that old.

**Comment by lacygoill** [comment]
Thank you for all the answers. So this is the right way of squashing the second window:

    vim -Nu NONE +'set wmh=0|sp|2resize 0'
                                ^^^^^^^^^

I did not know that `:resize` could accept a prefix count interpreted as a window number, and it does not seem to be documented (the help at `:h :resize` only mentions the current window); although now that I think about it, I remember seeing it used all the time in a session file created by `:mksession`. Anyway, sorry for the noise.
