### ISSUE TITLE
Vim configure should fail if a requested feature can't be provided instead of silently skipping it

### ISSUE THREAD

**Issue by ethouris** [vim/vim#5135]
**Describe the bug**
The build `configure` script, when `--enable-gui=gtk3` and you lack the kinda `libXt-devel` or `gtk3-devel` packages on your system, the script will... succeed, just after the build is complete you realize that your GUI, well, won't be available because you didn't have libraries needed to build with it. This happens even if you add `--enable-fail-if-missing`, no matter if this was predicted to work with this option in this case. Frankly, I don't understand who actually needs it to work this way that they think that GUI is MAYBE available on that system and use it if so - mostly people who add this `--enable-gui` option expect it to add the GUI or fail trying, or otherwise they don't add `--enable-gui`. I can understand that there can exist reasons for it to work this way by default, but it still lacks tools to enforce failure if required options cannot be satisfied, instead of silently turning off features that can't be provided. Just to make sure why some features can't be optional: because `--enable-gui` option **explicitly requires them**.

**To Reproduce**
Detailed steps to reproduce the behavior:

1. Have a linux system **without** provided development files for Gtk3 and Xt.
2. Run:
`./configure --enable-gui=gtk3`
3. The command should succeed. Then run: `make`
4. Result: `vim -G` doesn't work, despite that GUI has been requested at compile time.

**Expected behavior**
Either by default (I'd recommend) or when enforced by `--enable-fail-if-missing`, the command as in above #2 should fail with the following information provided (not exactly the expected message, just what should be made clear): Configure failed due to missing header files: `<X11/Intrinsic.h>` from `libXt` library (or similarly according to what kind of header file or library was missing in particular case).

**Screenshots**
N/A

**Environment (please complete the following information):**
- System: OpenSUSE Leap 15.1

**Comment by k-takata** [comment]
I think that such check was added as 8.1.0664. Is your Vim newer than that?

**Comment by tonymec** [comment]
Indeed (see http://ftp.vim.org/pub/vim/patches/8.1/README):
  6447  8.1.0664  configure "fail-if-missing" does not apply to enable-gui

BTW it isn't -G but -g — and of course, the usual way to do it is to have a soft link gvim -> vim and invoke that.
