### ISSUE TITLE
Spaces in the `shell` variables breaks command calling

### ISSUE THREAD

**Issue by shogerr** [vim/vim#5136]
**Describe the bug**
Vim/Gvim cannot use a shell command if the shell variable includes a space.

Different escaping methods methods do not resolve the problem.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Use `set shell=C:/Program\ Files/PowerShell/7-preview/pwsh.exe`
2. Test that `:terminal` works. It does.
3. Now try to run `:!xxd`.
4. Observe that the command fails with:
```
"C:/Program Files/PowerShell/7-preview/pwsh.exe" -command "xxd"
'C:/Program' is not recognized as an internal or external command,
operable program or batch file.
shell returned 1
Hit any key to close this window...
```

**Other Paths Attempted**
```
set shell=\"C:/Program\ Files/PowerShell/7-preview/pwsh.exe\"
set shell=C:/Program\ Files/PowerShell/7-preview/pwsh.exe
set shell=\"C:\\Program\ Files\\PowerShell\\7-preview\\pwsh.exe\"
set shell=C:\\Program\ Files\\PowerShell\\7-preview\\pwsh.exe
set shell="C:\Program Files\PowerShell\7-preview\pwsh"
```

**Full `vimrc` Settings supporting `shell`**
```
set shell=C:/Program\ Files/PowerShell/7-preview/pwsh.exe
set shellcmdflag=-command
set shellquote=\"
set shellxquote=
```

**Expected behavior**
Expect xxd to run.

**Environment (please complete the following information):**
- Vim: 8.1.1933
 - Windows 10
 - GUI/Console

**Comment by k-takata** [comment]
Please update to 8.1.2115 or later.

**Comment by chrisbra** [comment]
and don't use `"` for the option value.

**Comment by chrisbra** [comment]
I think this is a duplicate of https://github.com/vim/vim/issues/4950

**Comment by gdupras** [comment]
I don't have that PowerShell preview but I use Git Bash on Windows 10, which also has a space in the path. This is the best I came up with (in my vimrc):

    set shell=\"C:\Program\ Files\Git\bin\bash.exe\"
    set shellcmdflag=-c
    set shellquote="

With this I can do things like the following and they all work correctly.

    :terminal
    :terminal git log %
    :!git log
    :'<,'>!sort
    :'<,'>!sort -k2

However this doesn't work:

    :!git log %

This is the output:

    "C:\Program Files\Git\bin\bash.exe" -c "git log some\path\to\file.cpp"
    fatal: ambiguous argument 'somepathtofile.cpp': unknown revision or path not in the working tree.

Note that the backslashes are removed from the path. For some reason this does not happen if I pass the same command to `:terminal` instead. It also works fine if I leave `shell`, `shellcmdflag`, and `shellquote` to their default values.

I have a nightly build of Vim installed: 8.1.2229

**Comment by chrisbra** [comment]
> set shell=\"C:\Program\ Files\Git\bin\bash.exe\"

As I said before, this is not correct. For `set` do not use quotes, see `:h option-backslash`.

**Comment by shogerr** [comment]
> Please update to 8.1.2115 or later.

Alright, turns out I was using 8.1.1933. I've updated the main issue description.

> and don't use `"` for the option value.

I've entered the path for the `shell` using `set` without quotes. Thanks for the tip. The issue still persists with the same output. The issue has also been updated to reflect this.

**Comment by chrisbra** [comment]
I am confused, the original issue still contains double quotes for the shell setting. Please write down exactly what you have tried.

**Comment by shogerr** [comment]
> I am confused, the original issue still contains double quotes for the shell setting. Please write down exactly what you have tried.
Check again, I wrote my comment before making the edit (bad form I guess).

There was a list of attempted paths at the bottom of the issue. I've moved that list up towards the top.

**Edit**
Ah, I see, I didn't update the block of settings at the end of the issue. Got it. Updated.

**Comment by k-takata** [comment]
@ProgMetalSlug 

> ```
> set shell=\"C:\Program\ Files\Git\bin\bash.exe\"
> set shellcmdflag=-c
> set shellquote="
> ```

It looks that there are some mistakes. I think that the settings should be:

```
set shell=\"C:\Program\ Files\Git\bin\bash.exe\"
set shellcmdflag=-c
set shellquote=\"
set shellxquote=
```

> However this doesn't work:
> 
> ```
> :!git log %
> ```

Try this:

```
:!git log '%'
```

Or:

```
:set shellslash
:!git log %
```

`\` will be used as an escaping character on bash. It needs to be quoted or `/` should be used instead.

**Comment by k-takata** [comment]
@shogerr 

> > Please update to 8.1.2115 or later.
> 
> Alright, turns out I was using 8.1.1933. I've updated the main issue description.

Then, again, please update to 8.1.2115 or later.

**Comment by shogerr** [comment]
I played around with this for a minute and got things working.

Using the settings below allows `:terminal` and `%!xxd` to work for powershell, where a space exists in the path:
```
set shell=\"C:/Program\ Files/PowerShell/7-preview/pwsh.exe\"
set shellcmdflag=-command
set shellquote=
set shellxquote=
```

The environment loaded by vim causing failure was, `shellxquote="`, and `shellquote=`.

@k-takata 
I will also update and see how that changes things.

**Comment by shogerr** [comment]
@k-takata 
I updated to 8.1.2233. With the settings that worked with 3.1.1933, an error is now generated when calling `!xdd`:

```
"C:/Program Files/PowerShell/7-preview/pwsh.exe" -command \tmp\testxxd
\tmp\testxxd: The term '\tmp\testxxd' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
shell returned 1
```

This looks like the path is coming before the command, and of course a space is missing. So then this is possibly another issue altogether.

**Comment by k-takata** [comment]
> \tmp\testxxd

Didn't you execute `:!%xxd` instead of `:%!xxd`?

**Comment by shogerr** [comment]
> > \tmp\testxxd
> 
> Didn't you execute `:!%xxd` instead of `:%!xxd`?

Yeah, you're right, I did enter `:!%xxd`. It works with `:%!xxd` of course. Thanks.

**Comment by shogerr** [comment]
So I was curious, and used the `Tools > Convert to HEX` command from the menu bar.

`shell returned 1`

So that fails, but `:%!xxd` works in command mode.

```
:%!xxd
Calling shell to execute: "xxd <C:/Users/S/AppData/Local/Temp/VIiE9A.tmp > C:/Users/S/AppData/Local/Temp/VIoE9B.tmp"

" Tools > Convert to HEX "
Calling shell to execute: ""xxd" <C:/Users/S/AppData/Local/Temp/VIi3C07.tmp > C:/Users/S/AppData/Local/Temp/VIo3C08.tmp"
```

**Comment by shogerr** [comment]
If I make the change seen here: https://github.com/shogerr/vim/commit/403f8ff96f698c8ce439ba8e6ca7f8c1d1f19216#diff-0bf1822437d77cb156948e808487340d, I am able to use xxd through the GUI in Windows while using the shell settings from https://github.com/vim/vim/issues/5136#issuecomment-548181991.

**Comment by chrisbra** [comment]
> set shell=\"C:\Program\ Files\Git\bin\bash.exe\"

@k-takata are you sure? Shouldn't this rather be:

    set shell=C:\Program\ Files\Git\bin\bash.exe

**Comment by k-takata** [comment]
Yes, it is correct. Double quotes are needed even after 8.1.2115.

**Comment by chrisbra** [comment]
ah, right, `:h 'shell'` says it may need the double quotes. Should the documentation be updated?

```patch
diff --git a/runtime/doc/options.txt b/runtime/doc/options.txt
index c433b7e0c..0e558a72a 100644
--- a/runtime/doc/options.txt
+++ b/runtime/doc/options.txt
@@ -6530,8 +6530,8 @@ A jump table for the options with a short description can be found at |Q_op|.
        See |option-backslash| about including spaces and backslashes.
        Environment variables are expanded |:set_env|.

-       If the name of the shell contains a space, you might need to enclose
-       it in quotes or escape the space.  Example with quotes: >
+       If the name of the shell contains a space, you need to enclose it in
+        quotes and escape the space.  Example with quotes: >
                :set shell=\"c:\program\ files\unix\sh.exe\"\ -f
 <      Note the backslash before each quote (to avoid starting a comment) and
        each space (to avoid ending the option value).  Also note that the
```

**Comment by gdupras** [comment]
@k-takata 

> It looks that there are some mistakes. I think that the settings should be:
> 
> ```
> set shell=\"C:\Program\ Files\Git\bin\bash.exe\"
> set shellcmdflag=-c
> set shellquote=\"
> set shellxquote=
> ```

With `set shellquote=\"`, doing `'<,'>!sort` removes the selected lines from the buffer instead of sorting them. It works fine with `set shellquote="` however.

> Try this:
> 
> ```
> :!git log '%'
> ```
> 
> Or:
> 
> ```
> :set shellslash
> :!git log %
> ```
> 
> `\` will be used as an escaping character on bash. It needs to be quoted or `/` should be used instead.

Both of these worked correctly, thank you.

In the end, for all the examples of commands I gave in my previous comment to work correctly, I needed this in my vimrc:

    set shell=\"C:\Program\ Files\Git\bin\bash.exe\"
    set shellcmdflag=-c
    set shellquote="
    set shellslash

**Comment by k-takata** [comment]
`set shellquote="` is same as `set shellquote=`, because `"` is a start of a comment.
To check what is actually set, do `set shellquote?`.

**Comment by chrisbra** [comment]
it's a configuration issue right? So closing.

**Comment by shogerr** [comment]
Sort of? The underlying goal was to be able to use xxd. I ran into a possible gui bug and documented in this thread. I provided a possible fix for it as well. Should I open up a new issue? I thought about changing this issue's title the other day to reflect this.

**Comment by chrisbra** [comment]
you are right. @brammool I think the following changes can be included to the runtime files:

1) update of the documentation https://github.com/vim/vim/issues/5136#issuecomment-548282765
2) use of xxd in menu.vim https://github.com/shogerr/vim/commit/403f8ff96f698c8ce439ba8e6ca7f8c1d1f19216#diff-0bf1822437d77cb156948e808487340d

thanks!

**Comment by k-takata** [comment]
>2\. use of xxd in menu.vim [shogerr@403f8ff#diff-0bf1822437d77cb156948e808487340d](https://github.com/shogerr/vim/commit/403f8ff96f698c8ce439ba8e6ca7f8c1d1f19216#diff-0bf1822437d77cb156948e808487340d)

Double quotation should not be removed when cmd.exe is used as a shell (which is the default).
I also doubt whether this works when `g:xxdprogram` contains spaces even when powershell is used as a shell.

**Comment by brammool** [comment]
> you are right. @brammool I think the following changes can be included to the runtime files:
> 
> 1) update of the documentation https://github.com/vim/vim/issues/5136#issuecomment-548282765

I had already included that.

> 2) use of xxd in menu.vim https://github.com/shogerr/vim/commit/403f8ff96f698c8ce439ba8e6ca7f8c1d1f19216#diff-0bf1822437d77cb156948e808487340d

OK, but then we probably need to add double quotes in s:XxdFind():

    if has("win32") && !executable("xxd")
      let g:xxdprogram = $VIMRUNTIME . (&shellslash ? '/' : '\') . "xxd.exe"
      if g:xxdprogram =~ ' '
	let g:xxdprogram = '"' .. g:xxdprogram .. '"'
      endif
    else

-- 
I have a drinking problem -- I don't have a drink!

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
