### ISSUE TITLE
popup window is not considered to be a window?

### ISSUE THREAD

**Issue by Yggdroot** [vim/vim#5137]
**Describe the bug**
popup window is not considered to be a window?

**To Reproduce**
test.vim
```vim
call popup_create(bufnr('%'), #{line:"cursor-1", col:"cursor", pos:"botleft", minheight:4})
py import vim
py print(len(vim.windows))
```
1. so %
2. the printed message is 1 but not 2

**Expected behavior**
print 2

**Environment (please complete the following information):**
 - Vim version : 8.1.2151
 - OS:  CentOS 7
 - Terminal: GNOME Terminal

**Additional context**
It would be much appreciated if the pop up window can be focusable.

**Comment by chrisbra** [comment]
> It would be much appreciated if the pop up window can be focusable.

You keep on saying this, but you have never said why you need this.

**Comment by Yggdroot** [comment]
> > It would be much appreciated if the pop up window can be focusable.
> 
> You keep on saying this, but you have never said why you need this.

Because neovim's float window is focusable, though vim's popup window is already better than float window in most aspects except `focusable`, I still think popup window is inferior to float window.
With `focusable`, I can use the popup window more flexibly, also I think more feature is better than less feature. 
More and more plugin developers have transferred to neovim, their plugin called xxx.nvim, I like vim very much and don't want to join them.

**Comment by markonm** [comment]
> You keep on saying this, but you have never said why you need this.

It would be useful for scrolling and yanking. There is a support for scrolling and copying with the mouse, but the mouse doesn't work everywhere and requires _a third hand which we don't have_.

**Comment by bfrg** [comment]
@markonm You can scroll the popup window by using a `popup-filter` that sets the `firstline` entry.

**Comment by markonm** [comment]
`popup-filter` is useful when working with menus and such but it has the following disadvantages:

- user is required to remember which keys were assigned for scrolling for every plugin they use
- when two or more popup-windows are displayed at the same time it is not easy to predict or select which window should be scrolled
- some plugins not implementing scrolling keys (for example it is not implemented for Vim's popup window used for preview and completion info)

If focus were supported, It would be much more convenient to just hit `<c-w>w` a couple of times to select correct window, and do the scrolling with regular Vim commands. In popup windows we could also use Vim's text objects to easily yank desired text.

**Comment by brammool** [comment]
Using CTRL-W several times to focus a popup window is a hassle, and then how do you go back to where you started?  What if the popup closes?
I would also expect CTRL-W not to work from insert mode, where you would have many ways to trigger a popup window.
In general, although focusing a popup window may have an advantage in some situations, it will more often cause trouble and confusion.

If we need some generic way to scroll a popup window (which also works from Insert mode), I'm open for suggestions.  Perhaps Ctrl with cursor keys?  But then we still don't know which popup window if there are several, thus the popup window must somehow be marked as scrollable.  And then the plugin might as well do this with a filter...

Selecting text can currently be done with the mouse.  Just like modeless selection in several other situations (e.g. copying the output of a shell command).  Not being able to use Normal mode commands for this seems to be a minor issue.

Perhaps we can create some generic filter for whatever we decide is generally useful.  But it must work in may situations with many plugins, that might not be easy.

**Comment by Yggdroot** [comment]
`focusable` popup window is off the topic.

@brammool This issue is a bug report or question, could you reopen it?

**Comment by chrisbra** [comment]
can't we highlight the popup window that is (on focus) or will receive the keys?
