### ISSUE TITLE
Mapping raises E315

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#5139]
**Describe the bug**

When pressed, sometimes, a custom mapping raises `E315`.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -i NONE +"1pu='#'|nno n n:s///en<cr>" +"let @/='^#\n\zs'" +'norm n'

`E315` is raised:

    E315: ml_get: invalid lnum: 3

**Expected behavior**

`E315` is not raised.

**Environment**

 - Vim version:  8.1 Included patches: 1-2233
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

Here is a [backtrace](https://github.com/vim/vim/files/3785251/backtrace.txt).

**Comment by chrisbra** [comment]
I don't think mappings are directly involved with it. That comes from the `:s` command. Here is a slight simplification, that does not need any mappings:

> ./vim --clean +"1pu='#'"  +"let @/='^#\n\zs'" +':s///e'

(Note, without the `n` flags, you get a couple of more messages):

> Error detected while processing command line:
> E315: ml_get: invalid lnum: 3
> E881: Line count changed unexpectedly
> E315: ml_get: invalid lnum: 3
> 

Note also, the cursor is positioned incorrectly after the last line (on the tilde lines). I currently don't have time to debug this now, just thought I leave here what I found.

**Comment by chrisbra** [comment]
I am not sure, if this is correct, but the following patch fixes the problem:

```patch
diff --git a/src/ex_cmds.c b/src/ex_cmds.c
index fc692e323..80a7dc25b 100644
--- a/src/ex_cmds.c
+++ b/src/ex_cmds.c
@@ -3947,6 +3947,11 @@ do_sub(exarg_T *eap)
                    VIM_CLEAR(sub_firstline);
                }

+               // match could be after the buffer content for e.g. /\n\zs on the last line
+               // break out of the loop in that case
+               if (lnum > curbuf->b_ml.ml_line_count)
+                   break;
+
                if (sub_firstline == NULL)
                {
                    sub_firstline = vim_strsave(ml_get(sub_firstlnum));
```

Note, it won't find a match for the search atom `/#\n\zs`, but I believe this is correct, as the buffer does not contain anything after the final line break. Does that sound reasonable?

**Comment by lacygoill** [comment]
I've just tested the patch, and it fixes the issue; Vim doesn't complain with `E315` anymore, and it doesn't position the cursor on a tilde line. Thank you very much.
