### ISSUE TITLE
Speed up reading all the buffered content  at once by adding ch_readall()

### ISSUE THREAD

**Issue by liuchengxu** [vim/vim#5143]
**Is your feature request related something that is currently hard to do? Please describe.**
Using a while-loop in `close_cb` costs much more time, compared to neovim.

```vim
while ch_status(a:channel, {'part': 'out'}) == 'buffered'
  call add(s:chunks, ch_read(a:channel))
endwhile
```

Profile of neovim

```
FUNCTION  <SNR>175_on_event()
    Defined: ~/.vim/plugged/vim-clap/autoload/clap/forerunner.vim line 1
Called 14894 times
Total time:   1.192239
 Self time:   1.050879

count  total (s)   self (s)
                              " We only process the job that was spawned last time.
14894              0.041228   if s:job_id == -1 || a:job_id != s:job_id
                                return
14894              0.007161   endif
                            
14894              0.021911   if a:event ==# 'stdout'
14892              0.028434     if len(a:data) > 1
                                  " Second last is the real last one for neovim.
14891              0.583909       call extend(s:chunks, a:data[:-2])
14892              0.010812     endif
    2              0.000002   elseif a:event ==# 'stderr'
    1              0.000004     if !empty(a:data) && a:data != ['']
                                  let error_info = [ 'Error occurs when dispatching the command', 'job_id: '.a:job_id, 'command: '.s:executed_cmd, 'message: ' ]
                                  let error_info += a:data
                                  call s:abort_job(error_info)
    1              0.000000     endif
    1              0.000000   else
    1   0.000030   0.000009     if empty(g:clap.input.get())
    1   0.139606   0.000024       call g:clap.display.set_lines_lazy(s:chunks)
    1              0.000003       let g:clap.display.initial_size = len(s:chunks)
    1   0.030124   0.028367       call clap#impl#refresh_matches_count(string(g:clap.display.initial_size))
    1              0.000001     endif
14894              0.005206   endif
.....
FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
14894   1.192239   1.050879  <SNR>175_on_event()
...
```

Profile of vim:

```
FUNCTION  <SNR>169_close_cb()
    Defined: ~/.vim/plugged/vim-clap/autoload/clap/forerunner.vim:45
Called 1 time
Total time:   4.388645
 Self time:   4.257344

count  total (s)   self (s)
    1   0.000061   0.000020   if s:job_id > 0 && s:job_id_of(a:channel) == s:job_id
795848              1.923528 	  while ch_status(a:channel, {'part': 'out'}) == 'buffered'
795847              1.768541 	    call add(s:chunks, ch_read(a:channel))
795848              0.441582 	  endwhile
    1   0.000034   0.000017     if empty(g:clap.input.get())
    1   0.129316   0.000019       call g:clap.display.set_lines_lazy(s:chunks)
    1              0.000004       let g:clap.display.initial_size = len(s:chunks)
    1   0.026185   0.024239       call clap#impl#refresh_matches_count(string(g:clap.display.initial_size))
    1              0.000000     endif
    1              0.000001   endif
....
FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
    1   4.388645   4.257344  <SNR>169_close_cb()
```

Basically:

- neovim: count 14894, time: 1s
- vim: count 795848, time: 4s

Vim is slower using while-loop compared to neovim as the reading is linewise and the number of results is huge 795848, which are returned by calling `fd --type f` in my home directory.

**Describe the solution you'd like**
Add `ch_readall()` for reading all the buffer content at once.

**Describe alternatives you've considered**

1. Add an optional argument to `ch_read(channel[, size])` to read the output given the specified size.
2. Add `ch_getmsgcnt(channel)` that returns the number of currently buffered messages in this channel.

The use case is in [vim-clap](https://github.com/liuchengxu/vim-clap) I only care about the total number of return results and only display partial of them. I definitely won't display 795848 items, but I have to know this number and show the top N items returned first.

**Additional context**
https://github.com/liuchengxu/vim-clap/issues/75 is related I believe, neovim is more responsive in this case.

**Comment by brammool** [comment]
> **Is your feature request related something that is currently hard to do? Please describe.**
> Using a while-loop in `close_cb` costs much more time, compared to neovim.
> 
> ```vim
> while ch_status(a:channel, {'part': 'out'}) == 'buffered'
>   call add(s:chunks, ch_read(a:channel))
> endwhile
> ```
> 
> Profile of neovim
> 
> ```
> FUNCTION  <SNR>175_on_event()
>     Defined: ~/.vim/plugged/vim-clap/autoload/clap/forerunner.vim line 1
> Called 14894 times
> Total time:   1.192239
>  Self time:   1.050879
> 
> count  total (s)   self (s)
>                               " We only process the job that was spawned last time.
> 14894              0.041228   if s:job_id == -1 || a:job_id != s:job_id
>                                 return
> 14894              0.007161   endif
>                             
> 14894              0.021911   if a:event ==# 'stdout'
> 14892              0.028434     if len(a:data) > 1
>                                   " Second last is the real last one for neovim.
> 14891              0.583909       call extend(s:chunks, a:data[:-2])
> 14892              0.010812     endif
>     2              0.000002   elseif a:event ==# 'stderr'
>     1              0.000004     if !empty(a:data) && a:data != ['']
>                                   let error_info = [ 'Error occurs when dispatching the command', 'job_id: '.a:job_id, 'command: '.s:executed_cmd, 'message: ' ]
>                                   let error_info += a:data
>                                   call s:abort_job(error_info)
>     1              0.000000     endif
>     1              0.000000   else
>     1   0.000030   0.000009     if empty(g:clap.input.get())
>     1   0.139606   0.000024       call g:clap.display.set_lines_lazy(s:chunks)
>     1              0.000003       let g:clap.display.initial_size = len(s:chunks)
>     1   0.030124   0.028367       call clap#impl#refresh_matches_count(string(g:clap.display.initial_size))
>     1              0.000001     endif
> 14894              0.005206   endif
> .....
> FUNCTIONS SORTED ON SELF TIME
> count  total (s)   self (s)  function
> 14894   1.192239   1.050879  <SNR>175_on_event()
> ...
> ```
> 
> Profile of vim:
> 
> ```
> FUNCTION  <SNR>169_close_cb()
>     Defined: ~/.vim/plugged/vim-clap/autoload/clap/forerunner.vim:45
> Called 1 time
> Total time:   4.388645
>  Self time:   4.257344
> 
> count  total (s)   self (s)
>     1   0.000061   0.000020   if s:job_id > 0 && s:job_id_of(a:channel) == s:job_id
> 795848              1.923528 	  while ch_status(a:channel, {'part': 'out'}) == 'buffered'
> 795847              1.768541 	    call add(s:chunks, ch_read(a:channel))
> 795848              0.441582 	  endwhile
>     1   0.000034   0.000017     if empty(g:clap.input.get())
>     1   0.129316   0.000019       call g:clap.display.set_lines_lazy(s:chunks)
>     1              0.000004       let g:clap.display.initial_size = len(s:chunks)
>     1   0.026185   0.024239       call clap#impl#refresh_matches_count(string(g:clap.display.initial_size))
>     1              0.000000     endif
>     1              0.000001   endif
> ....
> FUNCTIONS SORTED ON SELF TIME
> count  total (s)   self (s)  function
>     1   4.388645   4.257344  <SNR>169_close_cb()
> ```
> 
> Basically:
> 
> - neovim: count 14894, time: 1s
> - vim: count 795848, time: 4s
> 
> Vim is slower using while-loop compared to neovim as the reading is linewise and the number of results is a huge number 795848, which uses `fd --type f` in my home directory.
> 
> **Describe the solution you'd like**
> Add `ch_readall()` for reading all the buffer content at once.
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> Add an optional argument to `ch_read(channel[, size])` to read the output given the specified size and add `ch_getmsgcnt(channel)` that returns the number of currently buffered messages in this channel.
> 
> The use case is in [vim-clap](https://github.com/liuchengxu/vim-clap) I only care about the total number of return results and only display partial of vim. I definitely won't display 795848 items, but I have to know this number and show the top N items returned first.
> 
> **Additional context**
> https://github.com/liuchengxu/vim-clap/issues/75 is related I believe, neovim is more responsive in this case.

What are you trying to read?  Looks like in the neovim case you do not
read lines but blocks of data?  In Vim you can use ch_readblob() or
ch_readraw() if you don't care about lines.

What are you reading that is 800'000 lines long?

-- 
The Feynman problem solving Algorithm:
	1) Write down the problem
	2) Think real hard
	3) Write down the answer

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by liuchengxu** [comment]
>What are you reading that is 800'000 lines long?

Find all the files under the home directory using `fd --type f`.

In neovim the output of job callback is returned by blocks of data, but in vim it's linewise, which results in the heavy while-loop in my previous case.

Using `let s:chunks = split(ch_readraw(a:channel), "\n")` is indeed much faster. `ch_readblob()` does not work for me as the output is not blob. I can take `ch_readraw()` then, close it for now :).

```
FUNCTION  <SNR>175_close_cb()
    Defined: ~/.vim/plugged/vim-clap/autoload/clap/forerunner.vim:45
Called 1 time
Total time:   0.641873
 Self time:   0.509531

count  total (s)   self (s)
    1   0.000065   0.000025   if s:job_id > 0 && s:job_id_of(a:channel) == s:job_id
    1              0.484983       let s:chunks = split(ch_readraw(a:channel), "\n")
                            		" while ch_status(a:channel, {'part': 'out'}) == 'buffered'
                            			" call add(s:chunks, ch_read(a:channel))
                            			" call add(s:chunks, ch_readblob(a:channel))
                            		" endwhile
    1   0.000048   0.000022     if empty(g:clap.input.get())
    1   0.130420   0.000026       call g:clap.display.set_lines_lazy(s:chunks)
    1              0.000005       let g:clap.display.initial_size = len(s:chunks)
    1   0.026346   0.024464       call clap#impl#refresh_matches_count(string(g:clap.display.initial_size))
    1              0.000000     endif
    1              0.000000   endif
```
