### ISSUE TITLE
[Windows 10] job_stop() calls exit_cb with a status of 0

### ISSUE THREAD

**Issue by mg979** [vim/vim#5150]
**Describe the bug**
In gvim/cmd terminal (Windows 10), if I terminate a job with job_stop(), this calls the exit_cb callback, but with a status of 0 (in Linux for the same event it is -1), so a terminated job runs the callback as a succesfully ended one.

In git bash mintty (Windows 10), `exitval` is -1 as in Linux.

**To Reproduce**
```vim
let g:job = job_start('grep foo', {})
call job_stop(g:job)
echo job_info(g:job)
```
In Windows (gvim/default terminal) `exitval` is 0, in Linux (but also in Windows git bash mintty terminal) it's -1.
If I run `cmd.exe /c grep foo` as command, I get the same.

**Expected behavior**
Terminating a command with `job_stop()` should always result in a non-zero exit code.

**Environment:**
 - Vim version 8.1.1967
 - OS: Windows 10
 - gvim

**Comment by mattn** [comment]
>In Windows (gvim/default terminal) exitval is 0, in Linux (but also in Windows git bash mintty terminal) it's -1.

Really?
```
let g:job = job_start('grep foo', {})
call job_stop(g:job)
call assert_equal(0, job_info(g:job).exitval)

let g:job = job_start('grep foo', {})
call job_stop(g:job, 'term')
call assert_equal(0, job_info(g:job).exitval)

let g:job = job_start('grep foo', {})
call job_stop(g:job, 'kill')
call assert_equal(0, job_info(g:job).exitval)
```
On my environment (Ubuntu), always 0 was returned.

**Comment by mg979** [comment]
Taken in vim 8.1 in Windows Linux Subsystem (debian buster)

![Imgur](https://i.imgur.com/9sIGjN0.png)

![Imgur](https://i.imgur.com/Zb6eBf8.png)

In git bash mintty it's the same. I tested it in Linux debian stretch in the past and it was also -1.

**Comment by mattn** [comment]
I could reproduce with `sleep 10m`.

```
let g:job = job_start('grep foo', {})
call job_stop(g:job)
sleep 10m
call assert_equal(0, job_info(g:job).exitval)

let g:job = job_start('grep foo', {})
call job_stop(g:job, 'term')
sleep 10m
call assert_equal(0, job_info(g:job).exitval)

let g:job = job_start('grep foo', {})
call job_stop(g:job, 'kill')
sleep 10m
call assert_equal(0, job_info(g:job).exitval)
echo v:errors
```

https://github.com/vim/vim/pull/5614
