### ISSUE TITLE
popup_atcursor() moves too much

### ISSUE THREAD

**Issue by mg979** [vim/vim#5151]
**Is your feature request related something that is currently hard to do? Please describe.**
When calling `popup_atcursor()`, the popup can appear at different positions, relatively to the cursor, sometimes above it, sometimes below it, as shown in this pic:

![Imgur](https://i.imgur.com/CwWsacG.gif)

**Describe the solution you'd like**
In this use case, I'd like the popup to be shown always below the cursor, if the cursor is in the upper half of the window, and viceversa. Is it currently possible?

**Describe alternatives you've considered**
I experimented a bit with `pos`, set to `topleft` or `topright` it keeps the position relative to the cursor, but it doesn't place the popup above the cursor, if this is in the lower half of the window.

![Imgur](https://i.imgur.com/AlDdf5T.gif)

**Comment by andymass** [comment]
Is there a reason you are regenerating the pop-up each time?

**Comment by mg979** [comment]
It's a yank stack plugin and the popup is redrawn when cycling among the stack elements.
I didn't think that it might be a very special case.. In neovim it works better though (it uses a fixed anchoring like NW, NE, SW, SE).

**Comment by andymass** [comment]
I meant why recreate the pop-up as opposed to just changing its contents?

**Comment by mg979** [comment]
Ok, even if I change the contents with `popup_settext()` the behaviour doesn't change, the popup is repositioned.

**Comment by brammool** [comment]
> **Is your feature request related something that is currently hard to do? Please describe.**
> When calling `popup_atcursor()`, the popup can appear at different positions, relatively to the cursor, sometimes above it, sometimes below it, as shown in this pic:
> 
> ![Imgur](https://i.imgur.com/CwWsacG.gif)
> 
> **Describe the solution you'd like**
> In this use case, I'd like the popup to be shown always below the cursor, if the cursor is in the upper half of the window, and viceversa. Is it currently possible?
> 
> **Describe alternatives you've considered**
> I experimented a bit with `pos`, set to `topleft` or `topright` it keeps the position relative to the cursor, but it doesn't place the popup above the cursor, if this is in the lower half of the window.
> 
> ![Imgur](https://i.imgur.com/AlDdf5T.gif)

popup_atcursor() is just a convenience function for popup_create() with
some default arguments.  If you want the popup to appear above the
cursor use 'botleft' for "pos" and "cursor-1" for "line".  You may also
want to set 'maxheight' to avoid it to flip to the other side when it
doesn't fit.  It should be possible to do what you want, experiment a
bit with the values.

-- 
hundred-and-one symptoms of being an internet addict:
9. All your daydreaming is preoccupied with getting a faster connection to the
   net: cable modem...100 Mbit...Fiber...1Gbit

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mg979** [comment]
@brammool 

Thanks, I could achieve more ore less what I wanted by manually setting the `line` option.

![Imgur](https://i.imgur.com/wYDlcZS.gif)

But maybe there's a problem (imho).

I'm using `topleft`, and it behaves differently from `botleft`, if you see the pics in my first post: `topleft` doesn't try to reposition the popup if it doesn't fit, good in this case, but maybe it's not working as intended?

Instead with `botleft` it attempts to reposition the popup if there's not enough room. From the help (line 797):
```
If the popup cannot fit in the desired position, it may show at a nearby
position.
```
The problem is that this repositioning is automatic (not avoidable) and is not always working as it should, that is:

- it prefers to place the popup above the cursor, so it checks if above the cursor there is enough room
- if there's not, it places the popup below it, but it does so, even if below the cursor there's even less room than above it

See this pic:

![Imgur](https://i.imgur.com/GKZb9y7.gif)

So the situation is:

- `topleft` never repositions the popup. What I want in this case, but maybe it's not as intended, and if it will be 'fixed', it could break it for me..

- `botleft` can reposition the popup, and place it below the cursor if above it there is not enough room, but it will put it below even if below there's less room than above.

Also, this automatic repositioning causes problems even if I manually set the line, that is, if I use `botleft` instead of `topleft` where it's working well (first pic in this post):

```vim
    let height = len(split(text, '\n')) + 3
    let s:id = popup_atcursor(split(text, '\n'),
          \{'pos': 'botleft', 'line': 'cursor+'.height,
          \ 'padding': [1,1,1,1], 'border':[1,1,1,1],
          \ 'borderchars': [' '], 'borderhighlight': ['PmenuSel'],
          \})
```

gives this (the biggest popup is cut offscreen):

![Imgur](https://i.imgur.com/qDTQKDM.gif)

while this:


```vim
    let height = len(split(text, '\n')) + 3
    let s:id = popup_atcursor(split(text, '\n'),
          \{'pos': 'topleft', 'line': 'cursor-'.height,
          \ 'padding': [1,1,1,1], 'border':[1,1,1,1],
          \ 'borderchars': [' '], 'borderhighlight': ['PmenuSel'],
          \})
```

gives this (the biggest popup correctly takes as much room as it can):

![Imgur](https://i.imgur.com/DmUE5nf.gif)

**Comment by mg979** [comment]
To sum it up, `botleft` is a bit buggy because it cuts the popup offscreen, if there's not enough room. `topleft` works much better (the popup takes as much room as it can).

**Comment by brammool** [comment]
> To sum it up, `botleft` is a bit buggy because it cuts the popup
> offscreen, if there's not enough room. `topleft` works much better
> (the popup takes as much room as it can).

I'll see if that can be fixed.  For now, check how much room there is
and set "maxheight".

-- 
hundred-and-one symptoms of being an internet addict:
23. You can't call your mother... she doesn't have VOIP

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mg979** [comment]
> I'll see if that can be fixed.  For now, check how much room there is
and set "maxheight".

Thanks, I'm not even sure what the ideal behaviour would be, and it works well enough for me with `topleft` and manually adjusting the `line` option, so maybe this is really a corner case. I'm closing it since atm it's working for me.

**Comment by mg979** [comment]
@brammool are you interested in a patch for this? I'd have a patch that changes the popup behaviour in this way:

- new `pos`: `auto` (the popup is placed in the part of the screen where there is more room, it will become either `topleft` or `botleft`).
- `topleft` and `botleft` are changed to be similar to how they work in neovim: if the popup doesn't fit, it is moved vertically until it can fit (or it reaches the top of the screen), but it isn't 'flipped' upside-down.

**Comment by brammool** [comment]
I don't think we should change topleft or botleft, in many cases the popup size can be adjusted to make it fit, or the popup is allowed to extend outside of the Vim window.  
We can add some way of positioning where there is more space.  The position given would then not be the popup position but the reference point (e.g. the cursor or start of a function name).  The popup would then be above or below that point.
"auto" is not descriptive enough. Perhaps we can make this "flip", the one option that isn't implemented yet (because it's not clear how it should work).  Makes more sense as a value for "pos" anyway.

**Comment by mg979** [comment]
Thanks, it's working much better but I still see a problem with `topleft`.
But maybe it's me? I don't know if there's a reason it's working in this way.

![Imgur](https://i.imgur.com/vgybwsP.gif)

It goes away if I change these lines (1421-1423)
```c
	    wp->w_winrow = wantline - 2 - wp->w_height - extra_height;
	else
	    wp->w_winrow = wantline - 1;
```
to this
```c
	    wp->w_winrow = wantline - wp->w_height - extra_height;
	else
	    wp->w_winrow = wantline + 1;
```

![Imgur](https://i.imgur.com/pXZ4iu2.gif)

The code for the popup is
```vim
    let title = printf(' [%d/%d] ', s:Y.offset+1, s:Y.size())
    let s:id = popup_atcursor(split(s:Y.get().text, '\n'),
          \{'title': title, 'pos': 'topleft',
          \ 'padding': [1,1,1,1], 'border':[1,1,1,1],
          \ 'borderchars': [' '], 'borderhighlight': ['PmenuSel'],
          \})
    call setbufvar(winbufnr(s:id), '&filetype', s:Y.get().ft)
```
that is, just popup_atcursor() with `topleft` and border/padding (but it happens also if I remove both border and padding).

**Comment by brammool** [comment]
popup_atcursor() uses "pos" "botleft" by default.
You change it to "topleft", but the "line" is still set to "cursor - 1".
In your case you will want to set it to "cursor + 1", that is one line below the cursor.
Maybe when 'line' is not passed we can do that by default.

**Comment by mg979** [comment]
> You change it to "topleft", but the "line" is still set to "cursor - 1".
In your case you will want to set it to "cursor + 1", that is one line below the cursor.
Maybe when 'line' is not passed we can do that by default.

Yes that fixes it. An adjusted default for `topleft` would be nice too thanks!

**Comment by brammool** [comment]
> > You change it to "topleft", but the "line" is still set to "cursor - 1".
> > In your case you will want to set it to "cursor + 1", that is one line below the cursor.
> > Maybe when 'line' is not passed we can do that by default.
> 
> Yes that fixes it. An adjusted default for `topleft` would be nice too
> thanks!

Patch 8.1.2273

-- 
hundred-and-one symptoms of being an internet addict:
50. The last girl you picked up was only a jpeg.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mg979** [comment]
> Patch 8.1.2273

Thank you again... now, for me it works well enough (at least `botleft`) but I can see that `topleft` isn't perfect yet. Just to report the issue, I'm sure there are more pressing things.

This is `botleft`, drawn at the top and then at the bottom of the window:

![Imgur](https://i.imgur.com/9ctajPS.gif)

This is `topleft`, at top and bottom:

![Imgur](https://i.imgur.com/F5RgkeT.gif)

You can see that when `topleft` is drawn at the bottom, it is inverted and shown above the cursor (ok), but it shows much less lines than it could, and the more near the bottom it goes, the more lines are cut (it should be the opposite).

Thanks again for working on this anyway!

**Comment by brammool** [comment]
That's because the height was already computed based on the position below the anchor.
We can recompute the height when the popup flips to above.

**Comment by mg979** [comment]
@brammool thanks it works perfectly now!
