### ISSUE TITLE
Without x11 headers, clipboard is disabled but mouse_xterm is enabled

### ISSUE THREAD

**Issue by raboof** [vim/vim#5156]
**Describe the bug**
When there are no X11 headers available at build time, the `clipboard` feature is diabled, but the `mouse_xterm` feature is enabled.

While the `mouse_xterm` feature indeed technically does not require on the X11 headers, the resulting behavior is inconvenient/inconsistent: when running vim in an xterm, you can now make a selection with the mouse, but have no way to send the selected text to the system clipboard.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Build vim without X11 headers available (or use the 'vim' package from nixos)
2. Open a file in vim in an xterm
3. There now is now way to copy-paste text from vim to an X11 application

**Expected behavior**
There should be a way to copy-paste text from vim to an X11 application.

A way to achieve this would be to disable `mouse_xterm` by default when `clipboard` is disabled.

**Environment (please complete the following information):**
 - 8.1.1967
 - OS: NixOS
 - Terminal: xterm, terminology

**Comment by brammool** [comment]
This works as intended: "mouse_xterm" means that xterm mouse escape codes are recognized, it has nothing to do with the clipboard.
Without clipboard support you can't use the clipboard, that's obvious.

**Comment by tonymec** [comment]
@raboof : +mouse_xterm means xterm mouse control sequences are supported. Not only (as Bram said) this has nothing to do with the clipboard, it has nothing to do with X11. Many different terminal emulators use the same control sequences as xterm. A text-only console (with a gpm replacement) could conceivably be written to support xterm sequences on the console, though I don't see why one would bother to write it. In that hypothetical case, +mouse_xterm might support a mouse without any X11 session being started — and with no clipboard being accessible at all.

Best regards,
Tony.

**Comment by raboof** [comment]
I understand the features work as intended (and I do not propose to change them), I just noticed the default configuration turns out awkward in this case.

Anyway, whatever, no big deal.
