### ISSUE TITLE
"gn" won't wrap around the end of the buffer anymore (since 8.1.2207)

### ISSUE THREAD

**Issue by bfrg** [vim/vim#5164]
**Describe the bug**
Until `8.1.2206`, hitting `cgn` on the last occurrence of a keyword will wrap around the end of the buffer when pressing `.` (assuming `wrapscan` is enabled). This does not happen anymore in `8.1.2207`. Pressing `.` won't start at the first occurence (above the cursor). Instead one needs to press `n` before pressing dot.

**Environment**
Vim version `8.1.2206` (works) and `8.1.2207` (doesn't work anymore)

**Comment by brammool** [comment]
Looks like "gn" doesn't wrap around the end of the file at all.  Not sure why.  I think we should let 'wrapscan' apply normally.

**Comment by chrisbra** [comment]
Upps, I think I have been causing this. I remember I wondered why the `wrapscan` setting was being reset twice. I apparently got confused. Sorry for that.
