### ISSUE TITLE
Some more spelling errors 

### ISSUE THREAD

**Issue by jschleus** [vim/vim#5167]
Since I saw the just closed PR #5160 ("Fixed typos in comments") here a few more possible spelling errors that were found by a `codespell`-based check on the FOSS server fossies.org: 

https://fossies.org/linux/misc/vim-8.1.2244.tar.gz/codespell.html

or version independent

https://fossies.org/linux/misc/vim/codespell.html

Although I have prefiltered some obvious FPs there may be still some errors listed that are at least arguable (for e.g. "upto").

**Comment by brammool** [comment]
> Since I saw the just closed PR #5160 ("Fixed typos in comments") here a
> few more possible spelling errors that were found by a `codespell`-based
> check on the FOSS server fossies.org: 
> 
> https://fossies.org/linux/misc/vim-8.1.2244.tar.gz/codespell.html
> 
> or version independent
> 
> https://fossies.org/linux/misc/vim/codespell.html
> 
> Although I have prefiltered some obvious FPs there may be still some
> errors listed that are at least arguable (for e.g. "upto").

Can someone select the right corrections and create a pull request?

-- 
How To Keep A Healthy Level Of Insanity:
11. Specify that your drive-through order is "to go".

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
Fixed by [8.2.0156](https://github.com/vim/vim/releases/tag/v8.2.0156).

**Comment by jschleus** [comment]
Thanks for the fixes in [8.2.0156](https://github.com/vim/vim/releases/tag/v8.2.0156).

Ok, it 's not important, but I can see that some misspellings have not been fixed, some have re-crept in in the meantime, and some have onlly now been recognized as the used dictionaries  have been expanded.

SInce the above mentioned version independent URL now redirects to the latest main release, I have now (like for some other FOSS projects) implemented a continuously updated report for the vim  GitHub "master" version which is available within a special restricted "test" folder that isn't really integrated into the standard Fossies services and should also not be accessible to search engines:

&nbsp;https://fossies.org/linux/test/vim-master.tar.gz/codespell.html

That version independent URL hopefully always redirects to the report for the latest "master" version identified by the short commit ID and a year-month-day string (YYMMDD) representing the according git pull date (mostly = commit date). The refresh rate is currently half-hourly.

Though no severe errors were found and the correction of misspellings and typos has probably not a top priority, I hope that the report can nevertheless be a little bit useful. Otherwise just ignore it.

**Comment by lacygoill** [comment]
I created [a PR](https://github.com/vim/vim/pull/7494) to fix most of the new errors.  A few of them were not in comments but in strings, either in the source code or in tests.  I didn't fix them.  And there was this one which I left alone because it seems the errors are intentional:

https://github.com/vim/vim/blob/6e562fcc07c71ad1437c89c3d3cc423efb691f0a/src/gui_photon.c#L452

**Comment by chrisbra** [comment]
> https://fossies.org/linux/test/vim-master.tar.gz/codespell.html

ah thanks for that. Perhaps we can make that link more obvious somewhere.

**Comment by jschleus** [comment]
Great.

@lacygoill I always have to smile a bit when I see such overlooked FPs ("wee" is now added to the list of FPs).

**Comment by jschleus** [comment]
@chrisbra Probably not what you meant but on request of another project Fossies also offered the optional use of special Fossies codespell report badges that are linked to the according report page (e.g. "systemd" uses them in its [README.md]( https://github.com/systemd/systemd/blob/master/README.md) file, currently second badge from the bottom)

https://fossies.org/fossies_codespell_report_badges/

**Comment by brammool** [comment]
> Thanks for the fixes in [8.2.0156](https://github.com/vim/vim/releases/tag/v8.2.0156).
> 
> Ok, it 's not important, but I can see that some misspellings have not been fixed, some have re-crept in in the meantime, and some have onlly now been recognized as the used dictionaries  have been expanded.
> 
> SInce the above mentioned version independent URL now redirects to the latest main release, I have now (like for some other FOSS projects) implemented a continuously updated report for the vim  GitHub "master" version which is available within a special restricted "test" folder that isn't really integrated into the standard Fossies services and should also not be accessible to search engines:
> 
> &nbsp;https://fossies.org/linux/test/vim-master.tar.gz/codespell.html
> 
> That version independent URL hopefully always redirects to the report for the latest "master" version identified by the short commit ID and a year-month-day string (YYMMDD) representing the according git pull date (mostly = commit date). The refresh rate is currently half-hourly.
> 
> Though no severe errors were found and the correction of misspellings
> and typos has probably not a top priority, I hope that the report can
> nevertheless be a little bit useful. Otherwise just ignore it.

Looks like all the listed errors are actually intended.  Perhaps you
have some whitelist mechanism to exclude them?

-- 
BEDEVERE:        And what do you burn, apart from witches?
FOURTH VILLAGER: ... Wood?
BEDEVERE:        So why do witches burn?
SECOND VILLAGER: (pianissimo) ... Because they're made of wood...?
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by jschleus** [comment]
Vimissimo! Yes, the master version looks perfect (at least from codespell's  point of view).

The only shortly available report for the current [vim version 8.2.2162](https://fossies.org/linux/misc/vim-8.2.2162.tar.gz/codespell.html) shows one misspelling respectively false positive at line 366 of the file `.github/workflows/ci.yml` that is excluded in Fossies master tarball ("Initalize" -> "Initialize"). If there is no according change in the next vim versions I will put it into the "whitelist".
 
By the way, there are also always three supplemental pages showing some used "codespell" [configuration details](https://fossies.org/linux/test/vim-master.tar.gz/codespell_conf.html) (including the vim specific "whitelist"), all obvious [false positives](https://fossies.org/linux/test/vim-master.tar.gz/codespell_fps.html) and a [misspelling history](https://fossies.org/linux/test/vim-master.tar.gz/codespell_hist.html) (log) (the given URLs are for the vim "master" version).

**Comment by chrisbra** [comment]
@brammool how about this patch in addition:

```patch
diff --git a/README.md b/README.md
index 9f8541607..92474c212 100644
--- a/README.md
+++ b/README.md
@@ -9,6 +9,7 @@
 [![Language Grade: C/C++](https://img.shields.io/lgtm/grade/cpp/g/vim/vim.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/vim/vim/context:cpp)
 [![Debian CI](https://badges.debian.net/badges/debian/testing/vim/version.svg)](https://buildd.debian.org/vim)
 [![Packages](https://repology.org/badge/tiny-repos/vim.svg)](https://repology.org/metapackage/vim)
+[![Fossies codespell report](https://fossies.org/linux/test/vim-master.tar.gz/codespell.svg)](https://fossies.org/linux/test/vim-master.tar.gz/codespell.html)

 For translations of this README see the end.

**Comment by chrisbra** [comment]
codespell badge has been included 4072ba571babd733d1800c082416fe8fe3c28ed7

**Comment by jschleus** [comment]
Wow, so now I will try more often to detect possible false positives in the vim codespell reports. If I have overseen or didn't recognize something, please send an email to info@fossies.org.

By the way the Vim logo seems to me personally now on GitHub a little bit too small. On Fossies (doing the HTML conversion with "pandoc") it looks "greater" but the white space in the middle column is also "greater": https://fossies.org/linux/test/vim-master.tar.gz/vim-master/README.md.

**Comment by brammool** [comment]
> Wow, so now I will try more often to detect possible false positives
> in the vim codespell reports. If I have overseen or didn't recognize
> something, please send an email to info@fossies.org.
> 
> By the way the Vim logo seems to me personally now on GitHub a little
> bit too small. On Fossies (doing the HTML conversion with "pandoc") it
> looks "greater" but the white space in the middle column is also
> "greater":
> https://fossies.org/linux/test/vim-master.tar.gz/vim-master/README.md.

Yeah, was trying to use a table to adjust the layout, which worked fine
using a preview tool, but ends up with borders on github.  Not sure how
to get rid of them.  Or make this layout without using a table.

I can get rid of the middle column.


-- 
hundred-and-one symptoms of being an internet addict:
20. When looking at a pageful of someone else's links, you notice all of them
    are already highlighted in purple.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by jschleus** [comment]
Although Fossies uses here the "pandoc" option `--from=gfm` (GitHub-flavored markdown) "pandoc" creates in contrast to GitHub three columns of equal size and shows the logo in its "natural" size while GitHub seems to adopt the display size according the columns contents and the browser window width.

Naturally Markdown has limited layout flexibility and the border width is probably fixed within the GitHub CSS. Maybe one can make as a hack  the logo column a little bit wider by adding spaces (`&nbsp;`) about the anchor element  and thus make the logo a little bit bigger. But unfortunately I'm a layout layman and probably there are better solutions available.
