### ISSUE TITLE
Scrolling a popup window using "firstline" doesn't work very well with wrapped lines

### ISSUE THREAD

**Issue by bfrg** [vim/vim#5170]
**Describe the bug (and feature request)**
- Scrolling a popup window using the `firstline` entry doesn't always work properly when the displayed buffer contains wrapped lines.
- In general, writing a popup-filter that provides scrolling similar to `CTRL-E/Y`, `CTRL-D/U` and `CTRL-F/B` and `gg/G` requires a lot of boilerplate code.
- Most of the functions below that are called by the filter function could be provided by Vim.

**To Reproduce**
1. Run `vim --clean popup.vim -c "source %"`
```vim
" popup.vim
let s:mappings = {
        \ 'k': {id -> s:scroll_line(id, -1)},
        \ 'j': {id -> s:scroll_line(id, 1)},
        \ 'd': {id -> s:scroll_page(id, 0.5)},
        \ 'u': {id -> s:scroll_page(id, -0.5)},
        \ 'f': {id -> s:scroll_page(id, 1)},
        \ 'b': {id -> s:scroll_page(id, -1)},
        \ 'g': {id -> popup_setoptions(id, #{firstline: 1})},
        \ 'G': {id -> s:bottom(id)},
        \ 'q': {id -> popup_close(id)}
        \ }

function! s:scroll_line(winid, step) abort
    let line = popup_getoptions(a:winid).firstline
    if a:step < 0
        let newline = (line + a:step) > 0 ? (line + a:step) : 1
    else
        let nlines = line('$', a:winid)
        let newline = (line + a:step) <= nlines ? (line + a:step) : nlines
    endif
    call popup_setoptions(a:winid, #{firstline: newline})
endfunction

function! s:scroll_page(winid, size) abort
    let height = popup_getpos(a:winid).core_height
    let step = float2nr(height*a:size)
    call s:scroll_line(a:winid, step)
endfunction

function! s:bottom(winid) abort
    let height = popup_getpos(a:winid).core_height
    let nlines = line('$', a:winid)
    let newline = (nlines - height) >= 0 ? (nlines - height + 1) : 1
    call popup_setoptions(a:winid, #{firstline: newline})
endfunction

function! s:popup_filter(winid, key) abort
    if has_key(s:mappings, a:key)
        call get(s:mappings, a:key)(a:winid)
        return v:true
    endif
    return v:false
endfunction

let text = range(50)->map({_,i -> string(i)})
call popup_create(text, #{
        \ minwidth: 40,
        \ maxwidth: 40,
        \ minheight: 8,
        \ maxheight: 8,
        \ firstline: 1,
        \ scrollbar: 1,
        \ mapping: v:false,
        \ filter: funcref('s:popup_filter')
        \ })
```
2. The popup window can be scrolled with `j/k`, `d/u`, `f/b` and `g/G`. As long as it doesn't display any wrapped lines, the popup-filter works great (apart from being very long).
3. When wrapped lines appear in the popup window, the key mappings that scroll more than one line won't work properly. And it is impossible to achieve this using `firstline` only. Example:
```vim
" Everything else same as above
let text = range(50)->map({_,i -> string(i) .. ' ' .. repeat('-', 60)})
```
4. Now press `G` to jump to the bottom of the displayed buffer. Instead of jumping to the last line, this will jump to `45`. Similar behavior can be observed with the `d/u` and `f/b` keys.
5. There is a workaround, but it requires using `win_execute()` and then setting `firstline`:
```vim
let s:mappings = {
        \ 'k': {id -> s:scroll_line(id, -1)},
        \ 'j': {id -> s:scroll_line(id, 1)},
        \ 'd': {id -> s:scroll_page(id, "\<c-d>")},
        \ 'u': {id -> s:scroll_page(id, "\<c-u>")},
        \ 'f': {id -> s:scroll_page(id, "\<c-f>")},
        \ 'b': {id -> s:scroll_page(id, "\<c-b>")},
        \ 'g': {id -> popup_setoptions(id, #{firstline: 1})},
        \ 'G': {id -> s:bottom(id)},
        \ 'q': {id -> popup_close(id)}
        \ }

function! s:bottom(winid) abort
    call win_execute(a:winid, 'normal! G')
    let newline = popup_getpos(a:winid).firstline
    call popup_setoptions(a:winid, #{firstline: newline})
endfunction

function! s:scroll_page(winid, key) abort
    call win_execute(a:winid, 'normal! ' . a:key)
    let newline = popup_getpos(a:winid).firstline
    call popup_setoptions(a:winid, #{firstline: newline})
endfunction
```
But for some reasons `win_execute(a:winid, "normal! \<c-d>")` and `win_execute(a:winid, "normal! \<c-u>")` won't do anything. This has also been addressed in #4882 very briefly.

**Expected behavior**
- `win_execute(a:winid, "normal! \<c-d>")`  and `win_execute(a:winid, "normal! \<c-u>")` should work just like the other scrolling keys.
- It would be nice if Vim provided some scrolling functions that could be used in a popup-filter.

**Environment**
Vim version: `master`

**Comment by brammool** [comment]
> **Describe the bug (and feature request)**
> - Scrolling a popup window using the `firstline` entry doesn't always work properly when the displayed buffer contains wrapped lines.
> - In general, writing a popup-filter that provides scrolling similar to `CTRL-E/Y`, `CTRL-D/U` and `CTRL-F/B` and `gg/G` requires a lot of boilerplate code.
> - Most of the functions below that are called by the filter function
> could be provided by Vim.

As you mention furthere down, passing the comman to the popup window
with win_execute() should work in most cases.

> **To Reproduce**
> 1. Run `vim --clean popup.vim -c "source %"`
> ```vim
> " popup.vim
> let s:mappings = {
>         \ 'k': {id -> s:scroll_line(id, -1)},
>         \ 'j': {id -> s:scroll_line(id, 1)},
>         \ 'd': {id -> s:scroll_page(id, 0.5)},
>         \ 'u': {id -> s:scroll_page(id, -0.5)},
>         \ 'f': {id -> s:scroll_page(id, 1)},
>         \ 'b': {id -> s:scroll_page(id, -1)},
>         \ 'g': {id -> popup_setoptions(id, #{firstline: 1})},
>         \ 'G': {id -> s:bottom(id)},
>         \ 'q': {id -> popup_close(id)}
>         \ }
> 
> function! s:scroll_line(winid, step) abort
>     let line = popup_getoptions(a:winid).firstline
>     if a:step < 0
>         let newline = (line + a:step) > 0 ? (line + a:step) : 1
>     else
>         let nlines = line('$', a:winid)
>         let newline = (line + a:step) <= nlines ? (line + a:step) : nlines
>     endif
>     call popup_setoptions(a:winid, #{firstline: newline})
> endfunction
> 
> function! s:scroll_page(winid, size) abort
>     let height = popup_getpos(a:winid).core_height
>     let step = float2nr(height*a:size)
>     call s:scroll_line(a:winid, step)
> endfunction
> 
> function! s:bottom(winid) abort
>     let height = popup_getpos(a:winid).core_height
>     let nlines = line('$', a:winid)
>     let newline = (nlines - height) >= 0 ? (nlines - height + 1) : 1
>     call popup_setoptions(a:winid, #{firstline: newline})
> endfunction
> 
> function! s:popup_filter(winid, key) abort
>     if has_key(s:mappings, a:key)
>         call get(s:mappings, a:key)(a:winid)
>         return v:true
>     endif
>     return v:false
> endfunction
> 
> let text = range(50)->map({_,i -> string(i)})
> call popup_create(text, #{
>         \ minwidth: 40,
>         \ maxwidth: 40,
>         \ minheight: 8,
>         \ maxheight: 8,
>         \ firstline: 1,
>         \ scrollbar: 1,
>         \ mapping: v:false,
>         \ filter: funcref('s:popup_filter')
>         \ })
> ```
> 2. The popup window can be scrolled with `j/k`, `d/u`, `f/b` and
> `g/G`. As long as it doesn't display any wrapped lines, the
> popup-filter works great (apart from being very long).
> 3. When wrapped lines appear in the popup window, the key mappings
> that scroll more than one line won't work properly. And it is
> impossible to achieve this using `firstline` only. Example:
> ```vim
> " Everything else same as above
> let text = range(50)->map({_,i -> string(i) .. ' ' .. repeat('-', 60)})
> ```

You need to compute the number of screenlines that the test occupies.
strdisplaywidth() can be used, but it's not easy.

Let me add a "lastline" property to popup_getpos(), so that you know how
many lines are displayed in the popup and can compute how many text
lines you want to scroll.

> 4. Now press `G` to jump to the bottom of the displayed buffer.
> Instead of jumping to the last line, this will jump to `45`. Similar
> behavior can be observed with the `d/u` and `f/b` keys.

Looks like that's a problem with your script.  Why not use "normal G"?

> 5. There is a workaround, but it requires using `win_execute()` and then setting `firstline`:
> ```vim
> let s:mappings = {
>         \ 'k': {id -> s:scroll_line(id, -1)},
>         \ 'j': {id -> s:scroll_line(id, 1)},
>         \ 'd': {id -> s:scroll_page(id, "\<c-d>")},
>         \ 'u': {id -> s:scroll_page(id, "\<c-u>")},
>         \ 'f': {id -> s:scroll_page(id, "\<c-f>")},
>         \ 'b': {id -> s:scroll_page(id, "\<c-b>")},
>         \ 'g': {id -> popup_setoptions(id, #{firstline: 1})},
>         \ 'G': {id -> s:bottom(id)},
>         \ 'q': {id -> popup_close(id)}
>         \ }
> 
> function! s:bottom(winid) abort
>     call win_execute(a:winid, 'normal! G')
>     let newline = popup_getpos(a:winid).firstline
>     call popup_setoptions(a:winid, #{firstline: newline})
> endfunction
> 
> function! s:scroll_page(winid, key) abort
>     call win_execute(a:winid, 'normal! ' . a:key)
>     let newline = popup_getpos(a:winid).firstline
>     call popup_setoptions(a:winid, #{firstline: newline})
> endfunction
> ```
> But for some reasons `win_execute(a:winid, "normal! \<c-d>")` and
> `win_execute(a:winid, "normal! \<c-u>")` won't do anything. This has
> also been addressed in #4882 very briefly.
> **Expected behavior**
> - `win_execute(a:winid, "normal! \<c-d>")`  and `win_execute(a:winid, "normal! \<c-u>")` should work just like the other scrolling keys.

That's a bug, the 'scroll' option is not set.  I'll fix that.

> - It would be nice if Vim provided some scrolling functions that could be used in a popup-filter.

You mean "please implement all the scrolling that I would like to work
in a specific way".  Sorry, that's too specific for the plugin you are
making.  Using win_execute() and "normal" should make most things work.
Let me know if you encounter bugs.
 

-- 
How To Keep A Healthy Level Of Insanity:
15. Five days in advance, tell your friends you can't attend their
    party because you're not in the mood.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by nickspoons** [comment]
> You mean "please implement all the scrolling that I would like to work
> in a specific way".  Sorry, that's too specific for the plugin you are
> making.  Using win_execute() and "normal" should make most things work.
> Let me know if you encounter bugs.

Scrolling is going to be a recurring theme that the vast majority of plugins implementing popups will have to solve. If there were some generic solutions available, a lot of boilerplate could be removed, and more importantly, there would be a more consistent experience across plugins.

The types of scrolling @bfrg has described here are approximations at "standard" vim scrolling - scroll to top/bottom, and up/down a line, half page and page. And the amount of calculation needed to do this is fine for a single case, but silly when all popup plugins need to work out how to do it.

In [this thread](https://github.com/vim/vim/issues/4882) you said that both `:normal` and `win_execute()` were "strange" and "not natural" ways to scroll, so I believe @bfrg is trying to find sensible alternatives.

**Comment by brammool** [comment]
> > You mean "please implement all the scrolling that I would like to work
> > in a specific way".  Sorry, that's too specific for the plugin you are
> > making.  Using win_execute() and "normal" should make most things work.
> > Let me know if you encounter bugs.
> 
> Scrolling is going to be a recurring theme that the vast majority of
> plugins implementing popups will have to solve. If there were some
> generic solutions available, a lot of boilerplate could be removed,
> and more importantly, there would be a more consistent experience
> across plugins.

Many plugins using popup windows will not need any kind of scrolling.
I'm not sure which ones do need it.

> The types of scrolling @bfrg has described here are approximations at
> "standard" vim scrolling - scroll to top/bottom, and up/down a line,
> half page and page. And the amount of calculation needed to do this is
> fine for a single case, but silly when all popup plugins need to work
> out how to do it.
> 
> In [this thread](https://github.com/vim/vim/issues/4882) you said that
> both `:normal` and `win_execute()` were "strange" and "not natural"
> ways to scroll, so I believe @bfrg is trying to find sensible
> alternatives.

Although the types of scrolling might be common, using some ascii keys
for the commands is far from obvious.  I would actually expect most
plugins to use those keys for typing text.  Something else would be
needed to scroll while still being able to continue typing.

I think it's better if we first have a couple plugins implement this
with Vim script, so we can see what the context is and what is common,
before hard coding this inside Vim.

What I mentioned was that the scrolling should normally be implemented
by setting "firstline".  But if that somehow doesn't work, using normal
mode commands may be a way out.  But I would avoid normal mode commands
if possible.

-- 
This planet has -- or rather had -- a problem, which was this: most
of the people living on it were unhappy for pretty much of the time.
Many solutions were suggested for this problem, but most of these
were largely concerned with the movements of small green pieces of
paper, which is odd because on the whole it wasn't the small green
pieces of paper that were unhappy.
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bfrg** [comment]
Thank you for the quick fix as well as adding the `lastline` property.

The above example was just to show how much code is required to implement standard scrolling -- especially when using the `firstline` property. Using Normal-mode commands is a lot simpler. 

Vim already provides two filters: `popup_filter_menu()` and `popup_filter_yesno()`. There are also two examples that demonstrate how to use and extend them in a custom filter. What I was asking for was to _maybe_ adding another filter like `popup_filter_scroll()` with some default key mappings that would provide standard scrolling as @nickspoons mentioned above: scroll to top/bottom, up/down a line, half page and page. (I think `Shift-Home`, `Shift-End`, `Shift-PgUp` and `Shift-PgDn` aren't used yet, but it could be anything else). The keys could still be overridden in a custom filter function. It would be a lot easier for plugin developers to use a provided filter that scrolls the popup window and resets `firstline` properly than doing it manually every time scrolling is required. For my purposes I will use the above, but everyone else who needs scrolling will need to write the same amount of code. And that seemed redundant to me.

It looks like `popup_getpos(id).lastline` is returning the old value and not the current one. Example:
```vim
function! s:popup_filter(winid, key) abort
    let line = popup_getoptions(a:winid).firstline
    if a:key ==# 'j'
        let nlines = line('$', a:winid)
        let newline = (line + 1) <= nlines ? (line + 1) : nlines
        call popup_setoptions(a:winid, #{firstline: newline})
        echo printf('firstline %d lastline %d',
                \ popup_getpos(a:winid).firstline,
                \ popup_getpos(a:winid).lastline)
        return v:true
    elseif a:key ==# 'k'
        let newline = (line - 1) > 0 ? (line - 1) : 1
        call popup_setoptions(a:winid, #{firstline: newline})
        echo printf('firstline %d lastline %d',
                \ popup_getpos(a:winid).firstline,
                \ popup_getpos(a:winid).lastline)
        return v:true
    elseif a:key ==# 'q'
        call popup_close(a:winid)
        return v:true
    endif
    return v:false
endfunction

call popup_create(range(1, 20)->map({_,i -> string(i)}), #{
        \ minwidth: 60,
        \ maxwidth: 60,
        \ minheight: 10,
        \ maxheight: 10,
        \ mapping: v:false,
        \ firstline: 1,
        \ filter: funcref('s:popup_filter')
        \ })
```

> Although the types of scrolling might be common, using some ascii keys
for the commands is far from obvious.  I would actually expect most
plugins to use those keys for typing text.  Something else would be
needed to scroll while still being able to continue typing.

The above was just an example. Depending on the purpose of the popup window one would obviously pick other keys.

**Comment by brammool** [comment]
> Thank you for the quick fix as well as adding the `lastline` property.
> 
> The above example was just to show how much code is required to
> implement standard scrolling -- especially when using the `firstline`
> property. Using Normal-mode commands is a lot simpler. 
> 
> Vim already provides two filters: `popup_filter_menu()` and
> `popup_filter_yesno()`. There are also two examples that demonstrate
> how to use and extend them in a custom filter. What I was asking for
> was to _maybe_ adding another filter like `popup_filter_scroll()` with
> some default key mappings that would provide standard scrolling as
> @nickspoons mentioned above: scroll to top/bottom, up/down a line,
> half page and page. (I think `Shift-Home`, `Shift-End`, `Shift-PgUp`
> and `Shift-PgDn` aren't used yet, but it could be anything else). The
> keys could still be overridden in a custom filter function. It would
> be a lot easier for plugin developers to use a provided filter that
> scrolls the popup window and resets `firstline` properly than doing it
> manually every time scrolling is required. For my purposes I will use
> the above, but everyone else who needs scrolling will need to write
> the same amount of code. And that seemed redundant to me.
> 
> It looks like `popup_getpos(id).lastline` is returning the old value
> and not the current one. Example:

Yes, it is only updated when redrawing the popup.  Normally that should
be OK, but if you want to see the result after setting other properties
a "redraw" command is needed.

> ```vim
> function! s:popup_filter(winid, key) abort
>     let line = popup_getoptions(a:winid).firstline
>     if a:key ==# 'j'
>         let nlines = line('$', a:winid)
>         let newline = (line + 1) <= nlines ? (line + 1) : nlines
>         call popup_setoptions(a:winid, #{firstline: newline})
>         echo printf('firstline %d lastline %d',
>                 \ popup_getpos(a:winid).firstline,
>                 \ popup_getpos(a:winid).lastline)
>         return v:true
>     elseif a:key ==# 'k'
>         let newline = (line - 1) > 0 ? (line - 1) : 1
>         call popup_setoptions(a:winid, #{firstline: newline})
>         echo printf('firstline %d lastline %d',
>                 \ popup_getpos(a:winid).firstline,
>                 \ popup_getpos(a:winid).lastline)
>         return v:true
>     elseif a:key ==# 'q'
>         call popup_close(a:winid)
>         return v:true
>     endif
>     return v:false
> endfunction
> 
> call popup_create(range(1, 20)->map({_,i -> string(i)}), #{
>         \ minwidth: 60,
>         \ maxwidth: 60,
>         \ minheight: 10,
>         \ maxheight: 10,
>         \ mapping: v:false,
>         \ firstline: 1,
>         \ filter: funcref('s:popup_filter')
>         \ })
> ```
> 
> > Although the types of scrolling might be common, using some ascii keys
> for the commands is far from obvious.  I would actually expect most
> plugins to use those keys for typing text.  Something else would be
> needed to scroll while still being able to continue typing.
> 
> The above was just an example. Depending on the purpose of the popup
> window one would obviously pick other keys. 

That is an essential choice though.  Without it a common filter cannot
be created.

When using ascii keys it's easy to do, but when the user must be able to
type while the popup is visible we would need to use keys that are
almost never typed.  That's going to be a hard choice.  Using the mouse
to scroll is obviously much easier and not conflicting with what's
typed.

Most users will already have mapped some easy key combinations to their
liking, it's likely we break at least some of them.  Perhaps it can be
done with a prefix, but that means typing twice as much.  And the prefix
would not be a normally typed key, probably using a modifier.

-- 
To define recursion, we must first define recursion.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
