### ISSUE TITLE
v:mouse_popup_col and v:mouse_popup_row are not implemented yet?

### ISSUE THREAD

**Issue by Yggdroot** [vim/vim#5171]
https://github.com/vim/vim/blob/197c6b7da3ad4c3e3942a553f5dbc35722a4a349/runtime/doc/popup.txt#L855-L858

echo v:mouse_popup_row

E121: Undefined variable: v:mouse_popup_row

**Comment by brammool** [comment]
> https://github.com/vim/vim/blob/197c6b7da3ad4c3e3942a553f5dbc35722a4a349/runtime/doc/popup.txt#L855-L858
> 
> echo v:mouse_popup_row
> 
> E121: Undefined variable: v:mouse_popup_row

That should be v:mouse_lnum and v:mouse_col, like what getchar()
returns.  But it's not impemented yet.

-- 
Tips for aliens in New York: Land anywhere.  Central Park, anywhere.
No one will care or indeed even notice.
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Yggdroot** [comment]
https://github.com/vim/vim/blob/197c6b7da3ad4c3e3942a553f5dbc35722a4a349/runtime/doc/popup.txt#L855-L858

I think this document should be modified so as not to mislead users.

**Comment by brammool** [comment]
> https://github.com/vim/vim/blob/197c6b7da3ad4c3e3942a553f5dbc35722a4a349/runtime/doc/popup.txt#L855-L858
> 
> I think this document should be modified so as not to mislead users.

Wasn't included in the patch, but it's done:

A mouse click arrives as <LeftMouse>.  The coordinates are in |v:mouse_col|
and |v:mouse_lnum|.  The top-left screen cell of the popup is col 1, row 1
(not counting the border).



-- 
A fine is a tax for doing wrong.  A tax is a fine for doing well.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Yggdroot** [comment]
Thanks.

**Comment by Yggdroot** [comment]
`v:mouse_win` and `v:mouse_winid` are always 0 in Popup window.

**Comment by Yggdroot** [comment]
Thanks.

**Comment by Yggdroot** [comment]
Can vim get the v:mouse_winid, v:mouse_col and v:mouse_lnum in normal window just like in popup window?

**Comment by brammool** [comment]
> Can vim get the v:mouse_winid, v:mouse_col and v:mouse_lnum in normal
> window just like in popup window?

They are currently only set when using getchar().  Hmm, I suppose you
mean you would want them on any click, so you can use them in a mapping?
Problem is that setting the values is a bit expensive, since the screen
position has to be converted to a text position.  It might be better to
add a function to fetch the values.  Probably should have done that in
the first place instead of using global variables.

-- 
"Thou shalt not follow the Null Pointer, for at its end Chaos and
Madness lie."

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Yggdroot** [comment]
I find some issues about `v:mouse_winid`, `v:mouse_col` and `v:mouse_lnum`, so still report it here.
1. if there are more than one popup window, `v:mouse_winid` is always the id of the first popup window. And if click outside of the popup, the value does not change. 
**Expected behavior is**: click first popup, the id is winid of the first popup, click the second, the id is winid of the second popup, click outside of the popups, id is another value.
2. value of  `v:mouse_col` and `v:mouse_lnum`  is not right.

test.vim
```vim
func! Filter(winid, key)
    echom v:mouse_winid v:mouse_lnum v:mouse_col
    if a:key == "\<Esc>"
        call popup_close(a:winid)
    endif
    return 0
endf

let id = popup_create(bufnr('%'), {
            \ "title": "test",
            \ "line": 1,
            \ "maxheight": 5,
            \ "padding":   [0, 0, 0, 1],
            \ "scrollbar": 0,
            \ "mapping":   1,
            \ "zindex":    1,
            \ "filter" :   "Filter"
            \})

call win_execute(id, "setlocal nu")

let id2 = popup_create(bufnr('%'), {
            \ "title": "test",
            \ "line": 8,
            \ "maxheight": 5,
            \ "padding":   [0, 0, 0, 1],
            \ "scrollbar": 0,
            \ "mapping":   1,
            \ "zindex":    9,
            \ "filter" :   "Filter"
            \})
call win_execute(id2, "setlocal nu")
echom id id2
```

Steps to reproduce:
1. so %
2. click the first character `f` in **f**unc!,  it outputs `xxx 2, 2`, expected output is ` xxx, 1, 1`

**Comment by brammool** [comment]
The position is computed based on the assumption that it's in the popup that the filter is for.  But when there are multiple popups this would indeed be wrong.  Let me rethink this.  Perhaps we should just depend on the function to get the info and let the filter check the window ID to find out if the click was inside its popup.
