### ISSUE TITLE
vim keeps showing errors regarding diff and gzip

### ISSUE THREAD

**Issue by eg020571** [vim/vim#5172]
I was trying to diff two files with gvimdiff a.txt and b.txt and vim shows

`E97:Cannot Create diffs
`
and when i tried opening a .gz file it shows

> Error detected while processing function 
gzip#read: 
line 44: Error: Could not read uncompressed file 

Just to make sure i did not mess up my .vimrc,.cshrc and .alias file i reverted back to empty .vimrc and .vim folder in my home directory, similarly i removed all my additions in .cshrc and .alias.

 I tried :help E97 and it shows the same error 

![image](https://user-images.githubusercontent.com/31349364/68105007-2b6c1880-ff03-11e9-8bce-414f89edcff3.png)

Suggest some solution.
If i restart my pc the issue seems to get resolved but returns after sometime.

**Comment by chrisbra** [comment]
does some command clean up `/tmp`?

**Comment by eg020571** [comment]
i am not cleaning up any /tmp with my .vimrc or .cshrc

**Comment by chrisbra** [comment]
but perhaps your system is running some kind of a clean up job?

**Comment by eg020571** [comment]
I am not sure about it, Is there any way to check for it?

**Comment by chrisbra** [comment]
If this happens again, check the output of `:echo tempname()` and make sure all directories mentioned there exist. (should be something like `/tmp/v<random_string>/0`.

**Comment by eg020571** [comment]
i have restarted again to get my work done. 
I am sure it will return in sometime, i wil make a note of this command to check the directories exist.

**Comment by eg020571** [comment]
yes chris,It points to a `/tmp/vbOOIeN/6` directory and it has one 4.gz file.

The issue is back again.

**Comment by chrisbra** [comment]
so the dir `/tmp/vbOOIeN/` exists? I have no clue, why it fails then for you. You would have to start debugging the gzip plugin to find out why it breaks.

**Comment by eg020571** [comment]
the gzip plugin opens initially , i dont know why it runs into this after sometime.
I have couple of files which i opened few hours back they are able to diff and open` :help E97` , now  i see this  
![image](https://user-images.githubusercontent.com/31349364/68196394-8fafda80-ffde-11e9-9fe8-1247991a8620.png)

**Comment by eg020571** [comment]
I guess there is a problem with how /tmp directory is loaded in vim..
when i set `verbose=2` and try to diff two files i see these errors

![image](https://user-images.githubusercontent.com/31349364/68198316-c804e800-ffe1-11e9-9268-befa1c47c214.png)

I tried running` :echo tempname()` after that error and it points to a path..

Is there a way i can set /tmp to a known path or find out  path to which /tmp  is set.

**Comment by chrisbra** [comment]
you still haven't confirmed that the path given by `tempname()` actually exists!

**Comment by eg020571** [comment]
yes, it exists. 
 i told that a .gz file is present inside that path. (8th comment)

**Comment by chrisbra** [comment]
so is the filesystem full? Or are you running out of inodes or something? This looks very much like a system specific problem here.

**Comment by chrisbra** [comment]
Does any `:!ls` command work? the error message `Cannot fork` indicates, that the `fork()` system function failed. This is used quite often by Vim for `system()` and `:!` external commands.

**Comment by eg020571** [comment]
the` :!1s`  gives a `cannot fork` result as you said.
What i have observed is when this issue returns i cannot use `:help e97 or 410 r 810` the help returns those errors that i have attached in previous image.
There is still 1TB left in my disk so i dont see this as disk space issue but i have a gut feeling that it might be due to /tmp

**Comment by chrisbra** [comment]
yes, check the space requirements for your /tmp partition.

**Comment by eg020571** [comment]
Is there a way to give a tmp path in .vimrc 
/tmp seems full now . 


![image](https://user-images.githubusercontent.com/31349364/68202792-61d09300-ffea-11e9-9e63-c3d7f572fc92.png)

**Comment by chrisbra** [comment]
Are you using LVM? Then it should be pretty easy to resize the `/tmp` partition. BTW: It is actually helpful not to always past screenshots, I am reading the issues mainly through mails and text output is easier to understand that way (don't forget to copy and paste it, or find it using the search!).

Your best bet is to manually clean up your `/tmp` directory. Find out what is eating up your space and remove unneeded items. I am not aware of a method to make vim use a different directory.

**Comment by eg020571** [comment]
sorry for that, Maybe i should have pasted it. 
I have less than 1MB in /tmp and rest of 4GB is full from root.
I dont think i can delete that without permissions.

**Comment by chrisbra** [comment]
If the files have been created by your user, you should be able to delete them. If not, then the system administrator of that system needs to take care of this. I am closing this, as this is no issue of Vim.
