### ISSUE TITLE
yw does not move cursor forward, but yb does move cursor backwards

### ISSUE THREAD

**Issue by jolmg** [vim/vim#5175]
**Describe the bug**

It's actually more generic than the title. Actions with `y` or `>`, when used with forward motions (like `e`, `)`, or `}`) don't move the cursor, but backward motions (like `b`, `(`, or `{`) do.

Maybe this is intentional, but I figured I should report it if it isn't. I've been using vim for years and it felt unexpected when I noticed it a few days ago, so I don't know if it's always been like that or if something's changed. If it's always been like that, then I think perhaps it's best left as-is to avoid breaking plugins and other people's expectations. However, I notice that vi[1] doesn't move backwards, and vim does even in compatible mode.

[1] From: http://ex-vi.sourceforge.net/

**To Reproduce**

Detailed steps to reproduce the behavior:
1. Run `vim --clean` (or `gvim --clean`, etc.)
2. Open up any text or type multiple words of gibberish
3. In between words, use `yw` to see the cursor no move, then `yb` to see the cursor move backwards.

**Expected behavior**

I expected the cursor to not move in either case.

**Environment**

 - Vim: 8.1.2102
 - OS: Archlinux
 - Terminal: urxvt

**Final Note**

I'd like to take this chance to thank you, brammool. :)  This text editor has had immense impact in my life.

**Comment by brammool** [comment]
It's always been this way, it is Vi compatible: The cursor moves to the start of the affected text.
One can argue this isn't what the user wants, but backwards compatibility is more important.

**Comment by andymass** [comment]
Confusingly, as @jolmg mentioned, at least one version of actual vi does not behave like vim.

**Comment by chrisbra** [comment]
> at least one version of actual vi does not behave like vim.

So it is backwards incompatible and compatible at the same time!

I tested this with nvi, and it behaves like `vim`. Also I checked the Posix Spec: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/vi.html

> 
> Yank
> 
> Synopsis:
> 
>     [buffer][count] y motion
> 
> Copy (yank) the region of text into buffer, if specified, and into the unnamed buffer.
> 
> If the motion command is the y command repeated:
> 
>   The buffer shall be in line mode.
> 
>   If there are less than count -1 lines after the current line in the edit buffer, it shall be an error.
> 
>   The text region shall be from the current line up to and including the next count -1 lines.
> 
> Otherwise, the buffer text mode and text region shall be as specified by the motion command.
> 
> Current line: If the motion was from the current cursor position toward the end of the edit buffer, unchanged. Otherwise, set to the first line in the edit buffer that is part of the text region specified by the motion command.
> 
> Current column:
> 
>   If the motion was from the current cursor position toward the end of the edit buffer, unchanged.
> 
>   Otherwise, if the current line is empty, set to column position 1.
> 
>   Otherwise, set to the last column that displays any part of the first character in the file that is part of the text region specified by the motion command.

Note: the last quoted line.

BTW: I have never gotten `ex-vi` to be working, it always complains about my terminal and stays in ex-mode.

**Comment by jolmg** [comment]
> it is Vi compatible

I'll provide 2 counter-examples. One is vi in an SCO Unix OpenServer Release 5, and the other is vi from ex-vi.sourceforge.net. I wrote gibberish, then moved to a word, did `yb`, and pasted with `P`:

![vi-vim-incompatible-behaviour-2019-11-05_09 35 04](https://user-images.githubusercontent.com/17855790/68231567-29ac5e80-ffb0-11e9-8919-ab6fb33a1b68.gif)

**Comment by jolmg** [comment]
bash/readline vi-emulation also doesn't move the cursor backwards, but interestingly zsh vi-emulation does.

**Comment by chrisbra** [comment]
@jolmg did you delete your comments?

**Comment by chrisbra** [comment]
I just tested busybox vi and it behaves like vim.

**Comment by jolmg** [comment]
@chrisbra  Yeah. It was just mentioning that besides ex-vi from the site I mentioned, the vi in SCO Unix OpenServer Release 5 also doesn't move backwards, and neither does the vi-emulation in bash/readline.

I did find that zsh's vi emulation does move backwards, though.

**Comment by jolmg** [comment]
The POSIX argument is pretty strong, too. I can't really argue against being POSIX compatible.

**Comment by chrisbra** [comment]
thanks. I also tested a couple of other vi clones [neatvi](https://github.com/aligrudi/neatvi) and a more recent [nvi](https://repo.or.cz/nvi.git) and [nvi2](https://github.com/lichray/nvi2), although I couldn't get nvi2 to compile. Those behaved like vim
