### ISSUE TITLE
Turkish Spellcheck for Vim

### ISSUE THREAD

**Issue by bitigchi** [vim/vim#5179]
Hello,

I've created the following `.aap` recipe for Turkish spellcheck, but I am kind of lost after this step:
```
# Aap recipe for Turkish Vim spell files.

# Use a freshly compiled Vim if it exists.
@if os.path.exists('../../../src/vim'):
    VIM = ../../../src/vim
@else:
    :progsearch VIM vim

SPELLDIR = ..
FILES    = tr_TR.aff tr_TR.dic

all: $SPELLDIR/tr.utf-8.spl 

$SPELLDIR/tr.utf-8.spl : $FILES
        :sys env LANG=tr_TR.UTF-8
		$VIM -u NONE -e -c "mkspell! $SPELLDIR/tr tr_TR" -c q

# Fetching LibreOffice spell files
FILE = https://github.com/bitigchi/bitigchi.github.io/raw/master/vim-tr-spell/tr_TR.zip
:attr {fetch = $FILE} tr_TR.zip

# The files don't depend on the .zip file so that we can delete it.
# Only download the zip file if the targets don't exist.
tr_TR.aff tr_TR.dic: {buildcheck=}
        :assertpkg unzip patch
        :fetch tr_TR.zip
        :sys $UNZIP tr_TR.zip
        :delete tr_TR.zip
        @if not os.path.exists('tr_TR.orig.aff'):
            :copy tr_TR.aff tr_TR.orig.aff
        @if not os.path.exists('tr_TR.orig.dic'):
            :copy tr_TR.dic tr_TR.orig.dic
        @if os.path.exists('tr_TR.diff'):
            :sys patch <tr_TR.diff

# Generate diff files
diff:
        :assertpkg diff
        :sys {force} diff -a -C 1 tr_TR.orig.aff tr_TR.aff >tr_TR.diff
        :sys {force} diff -a -C 1 tr_TR.orig.dic tr_TR.dic >>tr_TR.diff

# Check for updated LibreOffice spell files.  When there are changes the
# ".new.aff" and ".new.dic" files are left behind for manual inspection.
check:
        :assertpkg unzip diff
        :fetch tr_TR.zip
        :mkdir tmp
        :cd tmp
        @try:
            @import stat
            :sys $UNZIP ../tr_TR.zip
            :sys {force} diff ../tr_TR.orig.aff tr_TR.aff >d
            @if os.stat('d')[stat.ST_SIZE] > 0:
                :copy tr_TR.aff ../tr_TR.new.aff
            :sys {force} diff ../tr_TR.orig.dic tr_TR.dic >d
            @if os.stat('d')[stat.ST_SIZE] > 0:
                :copy tr_TR.dic ../tr_TR.new.dic
        @finally:
            :cd ..
            :delete {r}{f}{q} tmp
            :delete tr_TR.zip

# Remove all the downloaded and generated files.
clean:
        :delete tr_TR.aff
        :delete tr_TR.dic
        :delete tr_TR.orig.aff
        :delete tr_TR.orig.dic
```
I tried to run `aap main.aap` in command line, but got the following error:
>extra:	Reading recipe "main.aap"
>extra:	Finished reading recipe "main.aap"
>depend:	Adding default dependency for "cleanmore"
>depend:	Building targets specified on command line
>depend:	1 - updating target "main.aap"
>depend:	1 - Do not know how to build "main.aap"
>error:	Do not know how to build "main.aap"

What to do next?

**Comment by brammool** [comment]
> I've created the following `.aap` recipe for Turkish spellcheck, but I am kind of lost after this step:
> ```
> # Aap recipe for Turkish Vim spell files.
> 
> # Use a freshly compiled Vim if it exists.
> @if os.path.exists('../../../src/vim'):
>     VIM = ../../../src/vim
> @else:
>     :progsearch VIM vim
> 
> SPELLDIR = ..
> FILES    = tr_TR.aff tr_TR.dic
> 
> all: $SPELLDIR/tr.utf-8.spl 
> 
> $SPELLDIR/tr.utf-8.spl : $FILES
>         :sys env LANG=tr_TR.UTF-8
> 		$VIM -u NONE -e -c "mkspell! $SPELLDIR/tr tr_TR" -c q
> 
> # Fetching LibreOffice spell files
> FILE = https://github.com/bitigchi/bitigchi.github.io/raw/master/vim-tr-spell/tr_TR.zip
> :attr {fetch = $FILE} tr_TR.zip
> 
> # The files don't depend on the .zip file so that we can delete it.
> # Only download the zip file if the targets don't exist.
> tr_TR.aff tr_TR.dic: {buildcheck=}
>         :assertpkg unzip patch
>         :fetch tr_TR.zip
>         :sys $UNZIP tr_TR.zip
>         :delete tr_TR.zip
>         @if not os.path.exists('tr_TR.orig.aff'):
>             :copy tr_TR.aff tr_TR.orig.aff
>         @if not os.path.exists('tr_TR.orig.dic'):
>             :copy tr_TR.dic tr_TR.orig.dic
>         @if os.path.exists('tr_TR.diff'):
>             :sys patch <tr_TR.diff
> 
> # Generate diff files
> diff:
>         :assertpkg diff
>         :sys {force} diff -a -C 1 tr_TR.orig.aff tr_TR.aff >tr_TR.diff
>         :sys {force} diff -a -C 1 tr_TR.orig.dic tr_TR.dic >>tr_TR.diff
> 
> # Check for updated LibreOffice spell files.  When there are changes the
> # ".new.aff" and ".new.dic" files are left behind for manual inspection.
> check:
>         :assertpkg unzip diff
>         :fetch tr_TR.zip
>         :mkdir tmp
>         :cd tmp
>         @try:
>             @import stat
>             :sys $UNZIP ../tr_TR.zip
>             :sys {force} diff ../tr_TR.orig.aff tr_TR.aff >d
>             @if os.stat('d')[stat.ST_SIZE] > 0:
>                 :copy tr_TR.aff ../tr_TR.new.aff
>             :sys {force} diff ../tr_TR.orig.dic tr_TR.dic >d
>             @if os.stat('d')[stat.ST_SIZE] > 0:
>                 :copy tr_TR.dic ../tr_TR.new.dic
>         @finally:
>             :cd ..
>             :delete {r}{f}{q} tmp
>             :delete tr_TR.zip
> 
> # Remove all the downloaded and generated files.
> clean:
>         :delete tr_TR.aff
>         :delete tr_TR.dic
>         :delete tr_TR.orig.aff
>         :delete tr_TR.orig.dic
> ```
> I tried to run `aap main.aap` in command line, but got the following error:
> >extra:	Reading recipe "main.aap"
> >extra:	Finished reading recipe "main.aap"
> >depend:	Adding default dependency for "cleanmore"
> >depend:	Building targets specified on command line
> >depend:	1 - updating target "main.aap"
> >depend:	1 - Do not know how to build "main.aap"
> >error:	Do not know how to build "main.aap"
> 
> What to do next?

Hah, that error is confusing.  "main.aap" is the default recipe to read,
thus just "aap" will work.  If you pass the argument "main.aap" it will
still read main.aap, but then try to use the argument "main.aap" as the
build target.

So just execute "aap" without arguments.

-- 
Give a man a computer program and you give him a headache,
but teach him to program computers and you give him the power
to create headaches for others for the rest of his life...
        R. B. Forest

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bitigchi** [comment]
Ahah, got it. I was able to create the `.spl` file successfully. While creating a pull request do I need to submit that one as well? As far as I can see, in `spell/` directory only English ones are included by default. But on the other hand, `spellfile.vim` is looking for `.spl` files while trying to download them, so I believe I must submit that file somehow.

**Comment by brammool** [comment]
> Ahah, got it. I was able to create the `.spl` file successfully. While
> creating a pull request do I need to submit that one as well? As far
> as I can see, in `spell/` directory only English ones are included by
> default. But on the other hand, `spellfile.vim` is looking for `.spl`
> files while trying to download them, so I believe I must submit that
> file somehow.

The essential parts are the main.aap file and any diffs between the
downloaded files and what you end up using.

The resulting files could be included, so I can check that when I run
the script I get the correct result.  You can also mail them to me
directly (as an attachment).

-- 
hundred-and-one symptoms of being an internet addict:
34. You laugh at people with a 10 Mbit connection.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bitigchi** [comment]
Done. Thank you for your help.
