### ISSUE TITLE
vi' and vi" issues with selection=exclusive

### ISSUE THREAD

**Issue by sosmo** [vim/vim#5183]
**Describe the bug**
The normal mode commands `vi'`, `vi"` and possibly other related commands malfunction with selection set to "exclusive". This only happens with some cursor positions, not all.

**To Reproduce**
1. Run `vim -u NONE`
2. Do:
```
:set selection=exclusive<cr>
i
foo 'bar' baz<esc>
gevi'
```

**Expected behavior**
The text inside the quotes gets selected

**Actual behavior**
Only the "r" gets selected

**Environment**
 - Vim version: 8.1, patches 1-320
 - OS: Ubuntu 19.04, KDE Plasma 5.15 (X version)
 - Terminal: Konsole

**Comment by chrisbra** [comment]
Hm, for me it selects nothing. I think 55d3bdbbe2bfc7a78b4a (v8.1.0971) might be the cause. Will have a closer look later.

**Comment by chrisbra** [comment]
I think this one fixes it:
https://github.com/chrisbra/vim/commit/7482d1d389e7db97e247f8b509003e5ec27427a9
