### ISSUE TITLE
">" doesn't affect the last selected line when cursor in the first column and selection=exclusive

### ISSUE THREAD

**Issue by sosmo** [vim/vim#5184]
**To Reproduce**
1. Run `vim --u NONE`
2. Do:
```
:set selection=exclusive<cr>
i
foo<cr>bar<esc>
0vk>
```

**Expected behavior**
The two lines get indented

**Actual behavior**
Only the first line gets indented

**Environment**
 - Vim version: 8.1, patches 1-320
 - OS: Ubuntu 19.04, KDE Plasma 5.15 (X version)
 - Terminal: Konsole

**Comment by chrisbra** [comment]
> The two lines get indented

Sounds correct to me. You are moving upwards and start visual mode on the first line. Why would you expect the second line to be indented? BTW, I don't see how the 'selection' option is relevant here.

**Comment by sosmo** [comment]
Oh I'm sorry! It should have been `0vk>`. That is, selecting the two lines, but an "empty" selection on the second line, with the selection end boundary to the left of "bar". Then, with selection=inclusive, the ">" operation works linewise as you'd expect and indents both of the rows, whereas with selection=exclusive, the second row gets ignored. I assume this is because no characters on the second row are selected, but it would still make more sense for ">" to be linewise  and only care about the rows selected, not the characters (I think).

**Comment by brammool** [comment]
With "exclusive" the cursor position is excluded, thus the second line is not in the Visual area.
If you want to include it, use linewise selection.
