### ISSUE TITLE
Double click mouse selection ignores the current word when using selection=exclusive

### ISSUE THREAD

**Issue by sosmo** [vim/vim#5185]
**Describe the bug**
When double clicking in gVim, word-wise selection begins. However, when selection is set to exclusive, double clicking on a word and then moving the cursor backwards leaves the word that was double-clicked unselected.

**To Reproduce**
1. Run `gvim --u NONE`
2. Do:
```
:set selection=exclusive<cr>
i
foo bar baz<esc>
<doubleclick on "bar">
<drag left>
```

**Expected behavior**
"bar" and some text to the left of it get selected

**Actual behavior**
"bar" doesn't get selected, only the text to the left of it does

**Environment**
 - Vim version: 8.1, patches 1-320
 - OS: Ubuntu 19.04, KDE Plasma 5.15 (X version)
 - Terminal: Konsole

**Comment by chrisbra** [comment]
I can't seem to reproduce this, using Vim 8.1.2225 in xfce and gtk2 gui. Can you please verify with a current build?

**Comment by sosmo** [comment]
Thanks for the answer. I don't have enough time to build vim myself right now, but I can re-report back after I've installed a new version of Ubuntu with a fresher build. In the meantime I guess this can be closed if nobody else has the issue.

**Comment by brammool** [comment]
If 'mousemode' is set to "extend" (which is the default on Linux) then you need to use the right mouse button to extend the selection.
