### ISSUE TITLE
vimtutor: Rethinking "Lesson 1.1:  MOVING THE CURSOR"

### ISSUE THREAD

**Issue by arp242** [vim/vim#5188]
vimtutor is by far the best way to get started with Vim. I always recommend all new users run it. But there's one thing that has bugged me for years: the first lesson, which tells people to use `hjkl` instead of the arrow keys.

Is this really an important thing to tell users right at the start? Vim works fine with arrow keys, and all users already know how to use them. It takes quite a lot of effort and retraining of muscle memory to unlearn the arrow keys, and the cost/benefit ratio is not a good one.

I would say that everything below the first lesson is vastly more important than learning about `hjkl`. Motions like `w` and `}` will save people much more time; `llllllllll` and `jjjjjjjj` are just as bad as `<Left><Left>..` and `<Down><Down>..`

I propose that this section be rewritten to encourage the user of the arrow keys, while still mentioning `hjkl`. I don't think it should be vimtutor's job to explain *everything* about Vim, but rather get people reasonably productive with just the basics, prioritizing on the most important issues. In that context, `hjkl` seems like a micro-optimisation to me; something to learn after you've already learned all the basics already.

There is already much to take in from vimtutor, and the more is added, the more chance there is people will forget about those more important commands.

**Comment by brammool** [comment]
Using "hjkl" is one of the core functions of Vi and Vim.  Yes, it takes time to learn.  But it pays back very quickly.  I know no keyboard where I can reliably hit the cursor keys without looking at them. And moving a few lines or characters are the most often used commands.

**Comment by arp242** [comment]
>  I know no keyboard where I can reliably hit the cursor keys without looking at them

I don't think this is common among the kind of users who run `vimtutor`.

**Comment by vim-ml** [comment]
On 11/10/2019 7:57 PM, Martin Tournoij (Vim Github Repository) wrote:
 >> [Bram Moolenaar]
 >>
>> I know no keyboard where I can reliably hit the cursor keys without
>: looking at them
> 
> I don't think this is common among the kind of users who run |vimtutor|.

1) The quote is taken out of context
2) The argument is irrelevant.

The purpose of vimtutor is to teach vim, and as mentioned in the words 
preceding the quoted words:

 >> [Bram Moolenaar]
 >> Using "hjkl" is one of the core functions of Vi and Vim. Yes,
 >> it takes time to learn. But it pays back very quickly.

so it is best if the student get comfortable using 'hjkl' as soon as 
possible.

It is irrelevant what the users of vimtutor are comfortable with -- it 
might very well be that they are most comfortable with the mouse.  While 
it is possible to use vim via arrow-keys, GUI and mouse, teaching such a 
usage is not the goal of vimtutor.

--Suresh
