### ISSUE TITLE
matchadd() highlighting not merging with existing text properties

### ISSUE THREAD

**Issue by nickspoons** [vim/vim#5191]
**Describe the bug**
Highlighting with `matchadd()` and `matchaddpos()` etc. totally overrides existing text highlights, where it should be able to merge with them. When a highlight group defining `cterm` and/or `gui` properties only and no `ctermfg`/`ctermbg`/`guifg`/`guibg` is applied with `matchadd()`, it should apply the `cterm`/`gui` properties without removing the colours of existing text properties.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Create the file "syntax_prop.vim" containing the following:
```vim
hi HiColour ctermfg=blue guifg=blue
hi HiItalic cterm=italic gui=italic

call prop_type_add('TPHiColour', #{ highlight: 'HiColour' })
call prop_type_add('TPHiItalic', #{ highlight: 'HiItalic' })

" Colour lines 1 and 2 blue
call prop_add(1, 1, #{type: 'TPHiColour', end_lnum: 2, end_col: 36})

" Apply italics to line 2
call prop_add(2, 1, #{type: 'TPHiItalic', end_col: 36})

" Apply italics to 2nd word of line 1
call matchaddpos('HiItalic', [[1, 4, 8]])
```
2. Run `vim --clean -S prop.txt prop.txt`
2. Edit `filename`
3. The 2nd word of line 1 has had italics applied, but the colour of the existing text property has been cleared.

**Expected behavior**
The 2nd word of line 1 should have remained blue, and had italics applied on top.

**Screenshots**
![textprop_matchadd](https://user-images.githubusercontent.com/5274565/68464031-b129f400-0274-11ea-83c9-8f795e7fc46e.png)

**Environment (please complete the following information):**
 - Seen in terminal vim 8.1.2257 on arch linux, and gvim 8.1.2214 on Windows 10

**Comment by brammool** [comment]
8.1.2279 should have made this work.

**Comment by nickspoons** [comment]
Thanks Bram!
