### ISSUE TITLE
Support for bracket comments in cmake syntax highlighting

### ISSUE THREAD

**Issue by mathomp4** [vim/vim#5194]
I would like to request the ability to syntax highlight [CMake bracket comments](https://cmake.org/cmake/help/latest/manual/cmake-language.7.html#comments) as "comment". That is, currently if I do this:
```cmake
# This is a comment
This is not a comment
```
Much like how linguist sees the #-comment as a comment, so does Vim. However, this:
```cmake
#[[ This is a bracket comment in CMake.
It lasts until the end of the bracket ]]
This is not a comment
```
is not seen as a comment by Vim (and I guess by linguist...time for another FR! :smile:).

It would be nice if vim could display that as a "block comment" much like how it does with C-code:
```c
/* This is a nice multiple
 * line comment */
This isn't
```
I did try looking at the `c.vim` to see if I could figure out how to support it but this:
https://github.com/vim/vim/blob/dc9ef26845c6bf5ba63bfa8d00fc8a9bdc3b2de5/runtime/ftplugin/c.vim#L29-L30
and this chunk:
https://github.com/vim/vim/blob/dc9ef26845c6bf5ba63bfa8d00fc8a9bdc3b2de5/runtime/syntax/c.vim#L214
broke my mind like the dot in Jeremy Bearimy.

NOTE: I know that the docs say that bracket comments are only supported since CMake 3.0 but that was 5+ years ago. I guess one could try to be smart and detect if `cmake_minimum_required` is set to something higher than 3.0, but I think it's a fair assumption to think 3.x is now standard enough.

**Comment by chrisbra** [comment]
please contact the syntax file maintainer of [cmake](https://github.com/vim/vim/blob/master/runtime/syntax/cmake.vim) for your enhancement request. (see the top of the file).

**Comment by mathomp4** [comment]
@chrisbra Done. Forgot about that in this day of GitHub!

**Comment by bfrg** [comment]
Which Vim version do you use? Can you check the header of your `cmake` syntax file `$VIMRUNTIME/syntax/cmake.vim`? Mine is from `2017 Aug 30` and multi-line comments are properly highlighted.

Nevertheless the author could update the current syntax file. There's a new one from `2019 May 29`.

**Comment by mathomp4** [comment]
@bfrg Huh. You might be right. I just tried it at home (with a homebrew `vim`) and it works.

Home (works): 
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov  6 2019 08:27:51)
macOS version
Included patches: 1-2250

" Vim filetype plugin
" Language:    CMake
" Maintainer:  Keith Smiley <keithbsmiley@gmail.com>
" Last Change: 2018 Aug 30

" Vim syntax file
" Program:      CMake - Cross-Platform Makefile Generator
" Version:      cmake version 3.9.20170830-ge0713
" Language:     CMake
" Author:       Andy Cedilnik <andy.cedilnik@kitware.com>,
"               Nicholas Hutchinson <nshutchinson@gmail.com>,
"               Patrick Boettcher <patrick.boettcher@posteo.de>
" Maintainer:   Dimitri Merejkowsky <d.merej@gmail.com>
" Former Maintainer: Karthik Krishnan <karthik.krishnan@kitware.com>
" Last Change:  2017 Aug 30
```
Work Desktop (fails)
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 10 2019 07:53:31)
Included patches: 1-1142

" Vim filetype plugin
" Language:    CMake
" Maintainer:  Keith Smiley <keithbsmiley@gmail.com>
" Last Change: 2018 Aug 30

" Vim syntax file
" Program:      CMake - Cross-Platform Makefile Generator
" Version:      cmake version 3.9.20170830-ge0713
" Language:     CMake
" Author:       Andy Cedilnik <andy.cedilnik@kitware.com>,
"               Nicholas Hutchinson <nshutchinson@gmail.com>,
"               Patrick Boettcher <patrick.boettcher@posteo.de>
" Maintainer:   Dimitri Merejkowsky <d.merej@gmail.com>
" Former Maintainer: Karthik Krishnan <karthik.krishnan@kitware.com>
" Last Change:  2017 Aug 30
```
So huh.  Each one has the same `cmake.vim`. I guess my desktop has a few more patches...

**Comment by bfrg** [comment]
@mathomp4 You can check with `:scriptnames` which `cmake` syntax file is loaded (after you opened a `CMakeLists.txt` file). Maybe you have an older syntax file on your system which doesn't support multi-line comments. For example, my Distro (Gentoo Linux) puts the `cmake` syntax file that is shipped with CMake in `/usr/share/vim/vimfiles/syntax/cmake.vim`. Files in `$VIM/vimfiles` are sourced _before_ the ones in `$VIMRUNTIME`, see `:h 'runtimepath'`. This means whenever a syntax file in `$VIM/vimfiles` is sourced, the ones shipped with Vim won't be used.

**Comment by mathomp4** [comment]
@bfrg Ah. Okay. `:scriptnames` helped a lot! There was a random old `cmake.vim` in my `~/.vim` directory. Not sure why it's there as Vim has had cmake syntax for a while.

Now the issue seems to be that on my cluster at work the older system has Vim 8.0 which doesn't seem to handle bracket comments. But Vim 8.1 on the *new* system does! I guess I just need to either annoy them to install a newer version or build it myself. 😄
