### ISSUE TITLE
Can not show the color theme correctly

### ISSUE THREAD

**Issue by cs-pchsu** [vim/vim#5201]
For some reason, I need to build vim by myself, but the built result seem wrong.
The vim I build can not show the color theme correctly.

like this picture ..
![2019-11-09_150347](https://user-images.githubusercontent.com/21957111/68524526-0e6c8680-0303-11ea-940a-974c0fa0fb63.jpg)

the following is my configure options , then do making, 
Which kind person can tell me where the error is, thank you vert much.

./configure --with-features=huge \
            --enable-multibyte \
	    --enable-rubyinterp=yes \
	    --enable-pythoninterp=yes \
	    --with-python-config-dir=/usr/lib/python2.7/config \
	    --enable-python3interp=yes \
	    --with-python3-config-dir=/usr/lib/python3.5/config \
	    --enable-perlinterp=yes \
	    --enable-luainterp=yes \
	    --enable-gui=gtk2 \
	    --enable-cscope \
	    --prefix=/usr/local

If no errors occur during the process, the result maybe look like the image as below.
![2019-11-09_151554](https://user-images.githubusercontent.com/21957111/68524632-17aa2300-0304-11ea-8fff-a2430e91dbff.jpg)

**Comment by k-takata** [comment]
Lack of information. Why not use the issue template?
Which version of Vim? Which OS and version? What terminal? What colorscheme?
Any error messages?

**Comment by cs-pchsu** [comment]
Why not use the issue template? Sorry Sorry for the trouble 

Which version of Vim? tag: v8.1.2272
Which OS and version? LUbuntu 18.04.2 LTS
What terminal? konsole
What colorscheme? https://github.com/NLKNguyen/papercolor-theme
Any error messages? No

**Comment by k-takata** [comment]
Does it occur when you use another colorscheme?

**Comment by cs-pchsu** [comment]
Even though I removed that color scheme, the problem still exists.

**Comment by chrisbra** [comment]
Is vim correctly installed? Is the Vimruntime env variable correctly set?

**Comment by cs-pchsu** [comment]
Q: Is vim correctly installed? 
A: After I have compiled the project, I execute vim directly in the src directory.

Q:Is the Vimruntime env variable correctly set? 
A:What files are there for me to refer to how to set runtime env.

**Comment by k-takata** [comment]
Two messages are not forwarded here:

https://groups.google.com/d/msg/vim_dev/ore6oX0D60w/txILSJx-BQAJ
> If you are executing vim directly in the src directory, then
> I assume that you have not installed it (i.e., run "sudo make
> install").  Then vim is going to look for its configuration files in
> the place it expects them to be installed, not in the place they
> currently are.
> 
> To be sure you are using the configuration files that match the vim
> you just built, before you install it, run vim like this:
> 
>     $ VIMRUNTIME=runtime src/vim
> 
> HTH,
> Gary

https://groups.google.com/d/msg/vim_dev/ore6oX0D60w/fNCeZDNqBQAJ
> Try make install to make sure everything is setup correctly.

**Comment by k-takata** [comment]
This is not an issue of Vim itself. So closing.
