### ISSUE TITLE
EndOfBuffer color in popup window seems not right.

### ISSUE THREAD

**Issue by Yggdroot** [vim/vim#5204]
**Describe the bug**
EndOfBuffer color in popup window seems not right.

**To Reproduce**

EndOfBuffer 
test.vim
```vim
let id = popup_create(bufnr('%'),
            \ #{line:0, col:0, padding: [0, 1, 1, 1],
            \ maxwidth:60, minheight:7})
```
1. so %

PS. I am using colorscheme https://github.com/Yggdroot/duoduo.
**Screenshots**

![111](https://user-images.githubusercontent.com/2705841/68538163-28fa3a80-03ab-11ea-9f8c-d874858eddc3.png)

**Expected behavior**

I don't know if it is by design, but it doesnot look so reasonable.

**Environment (please complete the following information):**
 - Vim version : 8.1.2238
 - OS:  Windows 7

**Comment by brammool** [comment]
Yeah, it's better to not use EndOfBuffer by default.
If we do want to highlight it differently, we might want to make EndOfBuffer local to the window, like we have 'wincolor'.  But that probably isn't very useful.
