### ISSUE TITLE
Make fillchars a local setting

### ISSUE THREAD

**Issue by heroin-moose** [vim/vim#5206]
**Is your feature request related something that is currently hard to do? Please describe.**

It would be great to make `fillchars` a window-local setting to make it possible for plugins like https://github.com/liuchengxu/vista.vim to declare custom folding style via `fold`.

**Describe the solution you'd like**

Ability to call `setlocal fillchars=...` (similar to neovim solution).

**Describe alternatives you've considered**

Additional window-local variables for each setting (stl, stnc, vert, fold and diff).

**Comment by chrisbra** [comment]
I wonder if it makes sense to have 'fillchars' option being local to a window. That might cause inconsistencies in the display of several window (borders and such) and actually I would even say, a plugin shouldn't mess with my local configured fillchars setting. Either it sets it globally (and then affects all windows) or it just shouldn't modify it at all.

**Comment by brammool** [comment]
This is already mentioned in the todo list, but with some question marks:
Should make 'listchars' global-local.  Local to window or to buffer?
Probably window.  
Add something like 'fillchars' local to window, but allow for specifying a
highlight name.  Esp. for the statusline.
And "extends" and "precedes" are also useful without 'list' set.  Also in
'fillchars' or another option?

**Comment by chrisbra** [comment]
I am not so sure, it is a good idea to make the whole fillchars setting local to window. For one, which windows vert suboption of the fillchar setting will then be used for drawing windows? `fold`, `stl` and `diff` might make sense, not sure (thought it might cause inconsistent display of folds and diff lines), `stlnc` probably doesn't (again it is not easily possible to guess, for which windows this would be in effect, since other windows could have their own `stl` suboptions.

For `listchars`, `extends`, `precedes` makes sense yes.

**Comment by lacygoill** [comment]
This todo item is no longer relevant:

   > Should make 'listchars' global-local.  Local to window or to buffer?
   > Probably window.  #5206

**Comment by habamax** [comment]
The topic is about "Make fillchars a local setting" but the closing commit makes 'listchars' global-local...

**Comment by vim-ml** [comment]
On 2021-03-04, Maxim Kim wrote:
> The topic is about "Make fillchars a local setting" but the
> closing commit makes 'listchars' global-local...

That's correct.  The subject was meant to imply--in few words--that
the setting should be made local in addition to it already being
global.  Are you suggesting that 'listchars' be only local, or did
you just misunderstand the subject?

Regards,
Gary

**Comment by habamax** [comment]
> Are you suggesting that 'listchars' be only local, or did you just misunderstand the subject?

I mean listchars are not fillchars.

**Comment by vim-ml** [comment]
On 2021-03-04, Maxim Kim wrote:
>     Are you suggesting that 'listchars' be only local, or did you just
>     misunderstand the subject?
> 
> I mean listchars are not fillchars.

Oops.  I must read more carefully.

Regards,
Gary
