### ISSUE TITLE
<Plug> mapping g with <expr> does not execute 'opfunc'

### ISSUE THREAD

**Issue by zsugabubus** [vim/vim#5207]
The behavior could be best presented by the following script:

```vim
" OK (Bar executed, waiting for an operator):
map <Leader> <Plug>(Foo)
nmap <expr> <Plug>(Foo)y g:Bar()

" OK:
nmap <expr> gy g:Bar()

" OK:
set opfunc=g:Opfunc
nmap gy g@

" Not waiting for motion:
map g <Plug>(Foo)
nmap <expr> <Plug>(Foo)y g:Bar()

fu g:Bar()
    echom 'Bar()'
    set opfunc=g:Opfunc
    return 'g@'
endfu
fu g:Opfunc(a)
    echom 'Ok!'
endfu
```

---
- Version:
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov  7 2019 22:00:54)
Included patches: 1-2268
Compiled by Arch Linux
```

**Comment by andymass** [comment]
seems to work if you replace the line with `nnoremap <expr> <Plug>(Foo)y g:Bar()`; i.e., the mapping you proposed is recursive.

**Comment by zsugabubus** [comment]
Hmmm, thanks. But then why does it work with `<Leader>`? And `Bar()` gets called so the `<Plug>(Foo)y` part cannot be recursive.

**Comment by andymass** [comment]
`<Leader>y` expands to `<Plug>(Foo)y` expands to `g@` - OK, waits for input

`gy` expands to `<Plug>(Foo)y` expands to `g@` expands to `<Plug>(Foo)@` - invalid map.

**Comment by zsugabubus** [comment]
Eh, silly me. Thanks for the explanation.
