### ISSUE TITLE
[i18n] gVim fails to display Turkish letters in GUI by default

### ISSUE THREAD

**Issue by bitigchi** [vim/vim#5209]
Starting gVim on Windows with Turkish localisation fails to display Turkish letters correctly unless encoding is manually set to UTF-8.

To reproduce:
1. Install the latest nightly installer from the repository
2. Run gVim

Expected behaviour:
1. gVim should be able to pick UTF-8 encoding at launch, and display characters correctly.

Screenshots:
* ![First launch after installation](https://user-images.githubusercontent.com/2769571/68573257-6f699b00-0478-11ea-89a1-d749ecb28bb1.png)

Environment:
1. gVim 8.1.2291
2. MS Windows 10.0.18362, Build18362
3. 64 bit GUI version

**Comment by k-takata** [comment]
Are you saying about the menu?
What is the default encoding of Turkish Windows? What does `:set enc?` show?
Looking at `runtime/lang/`, Turkish menus are provided in two encodings; ISO 8859-9 and UTF-8.
Maybe we should add a menu file with another encoding matching with the default `enc`.

**Comment by bitigchi** [comment]
Yes, it's the menu. Okay, after mentioning the error in #5210, I decided to try with a different editor for the encoding, in this case Xcode, but even after saving with the new encoding, when I re-open the file, it still shows as "No explicit encoding".

Do you want me to send the files?

**Comment by k-takata** [comment]
How about copying menu_tr_tr.iso_8859-9.vim to menu_tr_tr.cp1254.vim, and create a file named menu_tr.cp1254.vim which sources menu_tr_tr.cp1254.vim?

**Comment by k-takata** [comment]
Or is this enough? (both menu_tr_tr.cp1254.vim and menu_tr.cp1254.vim):

```vim
" Menu Translations:	Turkish

source <sfile>:p:h/menu_tr_tr.iso_8859-9.vim
```

**Comment by bitigchi** [comment]
I will try that later on, and will report back.

**Comment by bitigchi** [comment]
How about we remove all the encoding support except Unicode? Is there any platform left that would not support Unicode out-of-the box nowadays?

**Comment by k-takata** [comment]
I proposed changing the default encoding on Windows to UTF-8, but Bram didn't agree. #3907

**Comment by bitigchi** [comment]
No, that was not what I meant, I was talking about removing the cp and iso versions of Turkish locales.

I just built vim on Windows without the CP and ISO files, and everything worked out perfectly. `set enc?` was `cp1254` still, but menus displayed Turkish letters without any issues. I am going to open a pull request for this.

**Comment by brammool** [comment]
> No, that was not what I meant, I was talking about removing the cp and
> iso versions of Turkish locales.
> 
> I just built vim on Windows without the CP and ISO files, and
> everything worked out perfectly. `set enc?` was `cp1254` still, but
> menus displayed Turkish letters without any issues. I am going to open
> a pull request for this.

I suppose the "scriptencoding utf-8" does the automatic conversion to
'encoding', and since all characters can be converted to iso9 and cp1254
that works.

Note that on systems other than MS-Windows the "iconv" library will be
needed.  It's widely spread, but I'm not sure how many users won't have
it.

-- 
hundred-and-one symptoms of being an internet addict:
72. Somebody at IRC just mentioned a way to obtain full motion video without
    a PC using a wireless protocol called NTSC, you wonder how you never
    heard about it

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bitigchi** [comment]
Confirmed fixed.
