### ISSUE TITLE
[i18n] Vimtutor fails to display Turkish letters on Windows

### ISSUE THREAD

**Issue by bitigchi** [vim/vim#5210]
Launching vimtutor from the Start Menu entry displays a version with broken encoding. See screenshot. The outcome is the same whether encoding in `vimrc` is set to `utf-8` or not.

To reproduce:
1. Install the latest nightly installer from the repository
2. Run gVim

Screenshots:
![vimtutor](https://user-images.githubusercontent.com/2769571/68573805-85c42680-0479-11ea-8f06-d1bc9a1099a8.png)

Environment:
1. gVim 8.1.2291
2. MS Windows 10.0.18362, Build 18362
3. 64 bit GUI version

**Comment by k-takata** [comment]
Same question as #5209, what is the default encoding on Turkish Windows?
Need to add `runtime/tutor/tutor.tr.xxx` matching with the default encoding.

**Comment by bitigchi** [comment]
The default encoding on Windows is CP1254. It still does not correct the letters even if I set the encoding to CP1254.

I can provide a CP1254 version, but when I try to set the encoding and try to write the file I get the following error:

> "tutor.tr.cp1254" E513: write error, conversion failed (make 'fenc' empty to override)

**Comment by k-takata** [comment]
Is CP1254 exactly the same as ISO 8859-9?
Then how about just copy tutor.tr.iso9 to tutor.tr.cp1254?

**Comment by k-takata** [comment]
Another idea:

```diff
--- a/runtime/tutor/tutor.vim
+++ b/runtime/tutor/tutor.vim
@@ -108,7 +108,7 @@ endif
 
 " The Turkish tutor is available in two encodings, guess which one to use
 if s:ext =~? '\.tr'
-  if &enc == "iso-8859-9"
+  if &enc == "iso-8859-9" || &enc == "cp1254"
     let s:ext = ".tr.iso9"
   endif
 endif
```

**Comment by bitigchi** [comment]
> Then how about just copy tutor.tr.iso9 to tutor.tr.cp1254?

It should probably work. Code points are the same I guess (as I remember), the only difference that one is the Windows implementation. Below there are screenshots after saving the encodings, which show different encodings on different files, so I am utterly confused about which encoding goes to which.

![ISO-8859-9](https://user-images.githubusercontent.com/2769571/68589502-15c79780-049d-11ea-93ac-f99aece0224b.png)
![CP-1254](https://user-images.githubusercontent.com/2769571/68589581-4e677100-049d-11ea-9eea-97e3bddd254d.png)

The difference between application encoding/file encoding could be the reason? Is this a thing?

**Comment by brammool** [comment]
> > Then how about just copy tutor.tr.iso9 to tutor.tr.cp1254?
> 
> It should probably work. Code points are the same I guess (as I
> remember), the only difference that one is the Windows implementation.
> Below there are screenshots after saving the encodings, which show
> different encodings on different files, so I am utterly confused about
> which encoding goes to which.
> 
> ![ISO-8859-9](https://user-images.githubusercontent.com/2769571/68589502-15c79780-049d-11ea-93ac-f99aece0224b.png)
> ![CP-1254](https://user-images.githubusercontent.com/2769571/68589581-4e677100-049d-11ea-9eea-97e3bddd254d.png)
> 
> The difference between application encoding/file encoding could be the
> reason? Is this a thing?

Try:  iconv -f utf-8 -t cp1254 < tutor.tr.utf-8 > tutor.tr.cp1254

Turns out to be the same as the .iso9 file.  Thus Ken's suggestion to
add this to the tutor.vim file should work:

if s:ext =~? '\.tr'
  if &enc == "iso-8859-9" || &enc == "cp1254"
    let s:ext = ".tr.iso9"
  endif
endif


-- 
hundred-and-one symptoms of being an internet addict:
69. Yahoo welcomes you with your own start page

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
I believe this has been fixed by https://github.com/vim/vim/commit/574ee7bc1246070dba598f9561a2776aa1a10d07
