### ISSUE TITLE
cursor jumps beyond end of line when pressing `$` and text is concealed

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#5214]
**Describe the bug**

When pressing `$` to move the cursor on the last character of the line, the cursor jumps beyond the latter if some text is concealed on the line.

**To Reproduce**

Run this shell command:

    vim -Nu NONE +"call matchadd('Conceal', '(.*)')|set cole=3 cocu=n nowrap" +"pu=repeat('x', &columns/2)..'('..repeat('y', &columns/2)..')z'"

Then press `$` to move the cursor on the last character of the line, which here is `z`.
The cursor jumps to some location way beyond `z`.

**Expected behavior**

The cursor jumps onto the last character, `z`.

**Screenshots**

![gif](https://user-images.githubusercontent.com/8505073/68668813-57158100-0549-11ea-8875-ae2774fe6db3.gif)

**Environment**

 - Vim version:  8.1 Included patches: 1-2291
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

In  reality, the cursor position – as reported by the ruler (`:set ruler`) – is correct.
So it seems to be a redraw issue; if you press  any key, e.g. `l`, the screen is redrawn and the cursor is drawn in the correct column.

---

If you set `'showcmd'`, then the issue disappears:

    vim -Nu NONE +'set showmcd' +"call matchadd('Conceal', '(.*)')|set cole=3 cocu=n nowrap" +"pu=repeat('x', &columns/2)..'('..repeat('y', &columns/2)..')z'"
                   ^^^^^^^^^^^

---

If you execute `:norm! $`, instead of pressing `$`, the issue disappears.

**Comment by brammool** [comment]
I cannot reproduce the problem.

**Comment by lacygoill** [comment]
I've updated to `8.1.2294` and I can still reproduce.

To be sure that no configuration interferes, I've also reproduced by starting xterm from the whisker menu (application launcher for xfce), and making it run an unconfigured bash (`xterm -e bash --norc --noprofile`).

I've also recompiled with a minimum of options:

    $ ./configure --with-features=huge && make

And I've tested different terminals (st, konsole, xfce4-terminal); in all of them, the cursor is drawn beyond the last character on the line.

That being said, maybe I misunderstood something.

**Comment by lacygoill** [comment]
Here are a few additional information.

The issue is not specific to the `$` motion; I think it's triggered whenever you use a motion which makes the cursor jump on a character which is not currently visible on the screen when the conceal feature is disabled (`setl cole=0`).

So, if you press `fz` to find the next `z` character, the issue is also triggered, because `z` is not visible on the screen when the text is not concealed.

---

Here is a minimal vimrc:

    nno gx :call Func()<cr>
    fu Func()
        let col = col('.')
        norm! 1|
        call cursor(1, col)
    endfu
    call matchadd('Conceal', '(.*)')
    set cole=3 cocu=n nowrap

If you write it in `/tmp/vimrc`, then start Vim like this:

    vim -Nu /tmp/vimrc +"pu=repeat('x', &columns/2)..'('..repeat('y', &columns/2)..')z'"

Then, press:

   - `fz` to move the cursor on the `z` character
   - `l` to cause a redraw and fix the cursor position
   - `gx` to invoke the custom mapping

Again, the cursor is drawn beyond the end of the line:

![gif](https://user-images.githubusercontent.com/8505073/68746530-137a5000-05f9-11ea-9108-6635720d8d97.gif)

But, inside `Func()`, if you replace `call cursor(1, col)` with `exe 'norm! '..col..'|'`, the issue disappears; this seems to confirm that moving the cursor with `:norm` does not trigger the issue (maybe because it causes Vim to redraw).

---

How far the cursor is drawn compared to the last character may be influenced by the values of the `'sidescroll'` and `'sidescrolloff'` options.

**Comment by brammool** [comment]
OK, I can reproduce it now.  Perhaps the drawing code relies on the cursor position to be updated but the concealing breaks that.
