### ISSUE TITLE
Mouse left-click doesn't move the cursor in the command line anymore

### ISSUE THREAD

**Issue by lkintact** [vim/vim#5220]
1. Run `gvim.exe --clean`
2. Type any command in Command-line mode, for example `:help cmdline.txt`, but don't execute it
3. Try left-clicking anywhere within the command text. The cursor doesn't move (but should, according to `:help c_<LeftMouse>`)

Vim: https://github.com/vim/vim-win32-installer/releases/download/v8.1.2300/gvim_8.1.2300_x86.zip,
Windows 10 Home 1803.

I don't know when the bug first appeared, but left-clicking does work in Vim 8.1.2102.

**Comment by frithrah** [comment]
Looks like mouse is set to nvi when running --clean. :set mouse=nvic will bring the behaviour you want.

**Comment by lkintact** [comment]
@frithrah Thank you, you are right: Vim 8.1.2102 run with `--clean` sets `'mouse'` to `a`, and 8.1.2300 to `nvi` correspondingly.

**Comment by k-takata** [comment]
This was changed at 8.1.2226: https://github.com/vim/vim/commit/5b418992cf254137fde2a14d7066fbea5afddb28.

**Comment by chrisbra** [comment]
so closing.
