### ISSUE TITLE
The color is not right if wincolor in popup window has `reverse`  attribute

### ISSUE THREAD

**Issue by Yggdroot** [vim/vim#5227]
**Describe the bug**
The color is not right if wincolor in popup window has `reverse`  attribute.

**To Reproduce**

```vim
hi! Test gui=NONE guibg=NONE guifg=RED cterm=NONE ctermbg=NONE ctermfg=12
hi! Win gui=reverse guibg=black guifg=white cterm=reverse ctermbg=black ctermfg=white
let id = popup_create(bufnr('%'), #{line:0, col:0, maxwidth:60, maxheight:9})

call win_execute(id, 'setlocal filetype=cpp')
call win_execute(id, 'setlocal wincolor=Win')

call win_execute(id, "call matchadd('Test', 'popup')")
call win_execute(id, "silent! call prop_type_add('number', {'highlight': 'Test'})")
call win_execute(id, "call prop_add(2, 15, {'length': 3, 'type': 'number'})")
call win_execute(id, "call prop_add(5, 12, {'length': 3, 'type': 'number'})")
```
1. so %
2. the **bg** color of highlight word is red

**Screenshot**
![111](https://user-images.githubusercontent.com/2705841/68994896-d8ab3d00-08c2-11ea-8176-5b27349ef723.png)

**Expected behavior**
2. the **fg** color of highlight word is red

**Environment (please complete the following information):**
 - Vim version [gvim 8.1.2291]
 - OS: Windows 7

**Comment by brammool** [comment]
"reverse" should not be used for basic highlighting, it messes things up when combining attributes.  Only use it for highlighting that goes on top of others and needs to revert, such as when selecting text.  With color support it's often better to not use reverse at all, e.g. when selecting text give it a background color.
