### ISSUE TITLE
printf(): negative field width is treated as SIZE_MAX

### ISSUE THREAD

**Issue by justinmk** [vim/vim#523]
In the source for `vim_vsnprintf()` there is this block:

```
  // parse field width
  if (*p == '*') {
    p++;
    int j = tvs ? tv_nr(tvs, &arg_idx) : va_arg(ap, int);
    if (j >= 0)
      min_field_width = j;
    else {
      min_field_width = -j;
      justify_left = 1;
    }
  }
```

`-j` is being assigned to a `size_t` field. This manifests as a bug with the `*` specifier, described in `:help printf()`:

```
A field width or precision, or both, may be indicated by an
asterisk '*' instead of a digit string.  In this case, a
Number argument supplies the field width or precision.  A
negative field width is treated as a left adjustment flag
followed by a positive field width; a negative precision is
treated as though it were missing.  Example:
:echo printf("%d: %.*s", nr, width, line)
This limits the length of the text used from "line" to
"width" bytes.
```

So the following call (note the `-4` value) does not truncate `'foo bar'`:

```
echo printf("A%.*sZ", -4, 'foo bar')
```

**Comment by jottkaerr** [comment]
The value assigned to min_field_width is always positive -- either it's `j` in case `j` is positive, or it's `-j` in case j is negative.

Also, your example works according to the documentation: you supply a negative _precision_ which is ignored.

**Comment by justinmk** [comment]
My mistake.
