### ISSUE TITLE
Scheme ftplugin sets local variable lispwords, clobbers/shadows any user-set values

### ISSUE THREAD

**Issue by andmis** [vim/vim#5235]
**Scheme ftplugin script sets local lispwords variable, clobbers/shadows any user-set values**

If I configure `lispwords` in either `.vimrc` or `~/.vim/ftplugin/scheme.vim`, the changes are clobbered/shadowed by `/usr/local/share/vim/<version>/ftplugin/scheme.vim` which clears and resets a local `lispwords` variable on line 24. I know I can disable the reading of this file altogether by setting `did_ftplugin`, but is this really the intended behavior?

**To Reproduce**
1. Add `set lispwords=hello` to `~/.vimrc` or `~/.vim/ftplugin/scheme.vim`.
2. Run `vim /tmp/hello.scm`.
3. Check out the value of the variable `lispwords` in the `vim` instance. It's not `hello`.

**Expected behavior**
I expect the value of `lispwords` to be `hello`, or at least to contain `hello`.

**Environment (please complete the following information):**
 - Vim version: [8.1.2250]
 - OS: [macOS 10.15.1]
 - Terminal: [iTerm]

**Comment by evhan** [comment]
Hi @mishchea, I think you're right, and moreover your fix makes sense to me. (Another option might be to only modify `lispwords` when it isn't already set, but I think that's less useful.)

I'll have a look at what some other plugins do, and assuming it's something similar I'll incorporate your patch from #5236 into the upstream Vim plugin. Thank you!

**Comment by brammool** [comment]
Included fix from #5236
