### ISSUE TITLE
unable to recognize "section" in html 5

### ISSUE THREAD

**Issue by ghost** [vim/vim#524]
Html5 has sections, which represent a grouping of content (in some cases it's basically a div) but vim's filetype indent isn't working with sections, it only works with divs.

**Comment by chrisbra** [comment]
The [html indent](https://github.com/vim/vim/blob/master/runtime/indent/html.vim#L244) script from the vim repository already contains the section keyword. In a short test, this seems to work okay. Perhaps you need to only update your runtime files?

**Comment by ghost** [comment]
That worked, thank you!
