### ISSUE TITLE
Cannot compile vim with MinGW on Windows10

### ISSUE THREAD

**Issue by ReneNyffenegger** [vim/vim#5241]
I am trying to compile vim with MinGW on Windows10:

     cd src
     mingw32-make -f Make_ming.mak gvim.exe

I get the following error message when the compiler tries to compile beval.c:

    In file included from beval.c:11:
    beval.c: In function 'find_word_under_cursor':
    vim.h:1705:18: error: 'INT_MAX' undeclared (first use in this function)
     # define MAXCOL  INT_MAX  // maximum column number

**Comment by k-takata** [comment]
Which version of MinGW do you use? How do you install it?

**Comment by ReneNyffenegger** [comment]
I am not sure how I can determine the version of MinGW. I downloaded the (what I believe to be) newest version from MinGWs site and installed it under C:\MinGw.

When I execute `mingw32-make -v`, it prints

    GNU Make 3.82.90
    Built for i686-pc-mingw32
    Copyright (C) 1988-2012 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.

`gcc -v` prints

    Using built-in specs.
    COLLECT_GCC=gcc
    COLLECT_LTO_WRAPPER=c:/mingw/bin/../libexec/gcc/mingw32/8.2.0/lto-wrapper.exe
    Target: mingw32
    Configured with: ../src/gcc-8.2.0/configure --build=x86_64-pc-linux-gnu --host=mingw32 --target=mingw32 --prefix=/mingw --disable-win32-registry --with-arch=i586 --with-tune=generic --enable-languages=c,c++,objc,obj-c++,fortran,ada --with-pkgversion='MinGW.org GCC-8.2.0-5' --with-gmp=/mingw --with-mpfr=/mingw --with-mpc=/mingw --enable-static --enable-shared --enable-threads --with-dwarf2 --disable-sjlj-exceptions --enable-version-specific-runtime-libs --with-libiconv-prefix=/mingw --with-libintl-prefix=/mingw --enable-libstdcxx-debug --with-isl=/mingw --enable-libgomp --disable-libvtv --enable-nls --disable-build-format-warnings
    Thread model: win32
    gcc version 8.2.0 (MinGW.org GCC-8.2.0-5)

**Comment by chrisbra** [comment]
Hm, I thought we need either mingw-w64 or msys2 compiler.

**Comment by ReneNyffenegger** [comment]
If this is the case,  the build instructions under `src/INSTALLpc.txt` should imho be changed. They currently read

    3. MinGW
    ========
    
    (written by Ron Aaron: <ronaharon@yahoo.com>)
    
    This is about how to produce a Win32 binary of gvim with MinGW.
    
    First, you need to get the 'mingw32' compiler, which is free for the download
    at:
    
        http://www.mingw.org/
    
    or you can use 'MinGW-w64' compiler.
    
        http://mingw-w64.sourceforge.net/

    ... etc ...

**Comment by k-takata** [comment]
I created a PR: #5248.

**Comment by ReneNyffenegger** [comment]
Just to make sure I interpret the thread correctly: "win32: Drop support for old msvc" also means that Mingw32 is not supported anymore (and I have to use Mingw64)?

**Comment by k-takata** [comment]
Yes, the header files and libraries come with the original mingw is too old to compile Vim.

**Comment by brammool** [comment]
> I created a PR: #5248.

Please close this issue if that patch fixes the problem.

-- 
I AM THANKFUL...
...for all the complaining I hear about the government
because it means we have freedom of speech.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
I think we can close this now.
