### ISSUE TITLE
Selecting text with the mouse doesn't select to the end of the line

### ISSUE THREAD

**Issue by basilisk0315** [vim/vim#5242]
**Describe the bug**
Text selection with the mouse does not select text to the end of the line, if only selecting text within a line.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `gvim --clean`
2. Enter some text.
3. Using the mouse select the text to the end of the line. If the line starts with a tab, the selection stops before it hits the end of the line. If line numbers are on, the selection stops earlier still.

**Expected behaviour**
The text selection should continue to the end of the line.

**Screenshots**
Enter some text and select to the end of the line:
![gvim1](https://user-images.githubusercontent.com/54644368/69081177-598a4600-0a35-11ea-91ca-d51872426eb3.PNG)
After inserting a tab at the start of the line (note the EOL marker is not selected):
![gvim2](https://user-images.githubusercontent.com/54644368/69081294-8e969880-0a35-11ea-835a-ea7df398e089.PNG)
Turning on line numbers makes it worse:
![gvim3](https://user-images.githubusercontent.com/54644368/69081362-b5ed6580-0a35-11ea-8d08-9ce0e32a3155.PNG)

**Environment (please complete the following information):**
 - Vim version is 8.1.2318.
 - OS: Windows 8.1
 - Terminal: GUI

**Additional context**
Selecting downward with the mouse selects the whole line.
As far as I can tell this behaviour started after patch 8.1.2303.

**Comment by brammool** [comment]
Note: requires setting 'list'.
Can still see the problem when reverting the change in 8.1.2303

**Comment by brammool** [comment]
Problem is in 8.1.2304
