### ISSUE TITLE
`WinLeave` is not triggered when Vim is invoked with `-O`

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#5243]
**Describe the bug**

When Vim is invoked with the flag `-d`, `-o` or `-O`, during the startup, none of these events seem to be triggered:

   - `BufLeave`
   - `BufWinLeave`
   - `WinLeave`

This may give unexpected results.

**To Reproduce**

Run this shell command:

    vim -Nu NONE --cmd 'au BufWinEnter,WinEnter * setl stl=active' --cmd 'au BufWinLeave,WinLeave * setl stl=NOT\ active' -O /tmp/file{1..2}

The status line in the right window displays `active`.

**Expected behavior**

The status line in the right window displays `NOT active`, because:

   - for the window to exist, Vim had to focus it at least temporarily
   - it is not focused anymore, therefore it was left
   - when it was left, `WinLeave` was triggered
   - when `WinLeave` was triggered, the autocmd `au BufWinLeave,WinLeave * setl stl=NOT\ active` was run
   - when the autocmd was run, the value of the `'statusline'` option – local to the window – was set to `NOT active`

**Screenshots**

![gif](https://user-images.githubusercontent.com/8505073/69081987-76c41200-0a3f-11ea-8432-dd87109db0cb.gif)

In the screenshot, initially, the status line of the second window displays `active`, even though the latter is not focused. Only after focusing it and coming back to the first window, does its status line display `NOT active`.

**Environment**

 - Vim version:  8.1 Included patches: 1-2315
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

Initially, I found this issue after starting Vim with the `-d` flag; the status line in an unfocused window was set as if I was focusing it. So, the issue is not specific to `-o`; it probably applies to all flags which create windows (`-o`, `-O`, `-d`).

---

I've run these shell commands to find out which events are triggered during startup::

    vim -Nu NONE -V8/tmp/log --cmd 'exe "au "..getcompletion("*", "event")->filter({_,v -> v !~# "Cmd$"})->join(",").." * \""' +qa -O /tmp/file{1..2}
    vim +'v/^executing/d_' +'sil %s/executing \(\S*\).*/\1/' +x /tmp/log
    vim /tmp/log

I found this list:

   - `BufEnter`
   - `BufNewFile`
   - `BufWinEnter`
   - `WinEnter`

`WinLeave` is not included, which probably explains the unexpected status line earlier.
`BufWinLeave` is included, but it's not triggered when Vim is starting up; it's triggered when Vim is quitting (here via `:qa`).

---

Contrary to `WinLeave`, `TabLeave` is triggered when invoking Vim with the `-p` flag:

    vim -Nu NONE -V8/tmp/log --cmd 'exe "au "..getcompletion("*", "event")->filter({_,v -> v !~# "Cmd$"})->join(",").." * \""' +qa -p /tmp/file{1..2}
    vim +'v/^executing/d_' +'sil %s/executing \(\S*\).*/\1/' +x /tmp/log
    grep -i 'tableave' /tmp/log

---

As a workaround, I'm experimenting with this autocmd which visits all windows after `VimEnter` has been triggered and Vim was invoked with `-d`, `-o` or `-O`:

    augroup trigger_leave_events_on_startup
        au!
        au VimEnter * call timer_start(0, {-> s:trigger_leave_events()})
    augroup END
    fu s:trigger_leave_events() abort
        if match(v:argv, '\C^-[doO]$') != -1)
            let curwin = win_getid()
            windo "
            call win_gotoid(curwin)
        endif
    endfu

It seems to work, but it also looks awkward.

---

In the case of the status line option, I know there are other solutions, like:

    set stl=%!GetStl(winnr())
    fu GetStl(nr)
        return '%{SetStlFlag('..a:nr..')} %{w:is_active ? "active" : "NOT active"}'
    endfu
    fu SetStlFlag(nr)
        return get(extend(w:, {'is_active': (winnr() == a:nr)}), '', '')
    endfu

Or even simpler:

    set stl=%!GetStl()
    fu GetStl()
        return g:statusline_winid == win_getid() ? 'active' : 'NOT active'
    endfu

But the current issue is really about some events which are not triggered.

---

I'm not sure this is a bug; maybe the events are intentionally not triggered, because the user did not create the windows from a Vim session but from the shell command-line. But if that is the reason, then why are `TabEnter` and `TabLeave` triggered when Vim is invoked with `-p`?

**Comment by brammool** [comment]
This is done intentionally, during startup windows are created and buffers loaded in no specific order and only some Enter events are triggered (ones that are expected to initialize the window and/or buffer).
You can use the VimEnter event to initialize anything else.

**Comment by lacygoill** [comment]
Ah ok, thank you very much for the explanation.

> You can use the VimEnter event to initialize anything else.

Although, not always right from `VimEnter`. If I use the same example as before, and try to fix it with a `VimEnter` autocmd, it doesn't work:

    vim -Nu NONE --cmd 'au VimEnter * exe "windo \"" | 1wincmd w' --cmd 'au BufWinEnter,WinEnter * setl stl=active' --cmd 'au BufWinLeave,WinLeave * setl stl=NOT\ active' -O /tmp/file{1..2}
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The right status line still displays `active`.
To make it display `NOT active`, the command has to be delayed further with a timer:

    vim -Nu NONE --cmd 'au VimEnter * call timer_start(0, {-> execute("windo \"") + execute("1wincmd w")})' --cmd 'au BufWinEnter,WinEnter * setl stl=active' --cmd 'au BufWinLeave,WinLeave * setl stl=NOT\ active' -O /tmp/file{1..2}
                                      ^^^^^^^^^^^^^^^^

And only with a timer; I tried to delay with a one-shot autocmd listening to `SafeState`, but it doesn't work:

    vim -Nu NONE --cmd 'au VimEnter * au SafeState * ++once exe "windo \"" | 1wincmd w' --cmd 'au BufWinEnter,WinEnter * setl stl=active' --cmd 'au BufWinLeave,WinLeave * setl stl=NOT\ active' -O /tmp/file{1..2}
                                      ^^^^^^^^^^^^^^^^^^^^^

Edit:

Yes, you're right. `VimEnter` is the right event; sorry for the noise.

**Comment by brammool** [comment]
> Ah ok, thank you very much for the explanation.
> 
> > You can use the VimEnter event to initialize anything else.
> 
> Although, not always right from `VimEnter`. If I use the same example as before, and try to fix it with a `VimEnter` autocmd, it doesn't work:
> 
>     vim -Nu NONE --cmd 'au VimEnter * exe "windo \"" | 1wincmd w' --cmd 'au BufWinEnter,WinEnter * setl stl=active' --cmd 'au BufWinLeave,WinLeave * setl stl=NOT\ active' -O /tmp/file{1..2}
>                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> The right status line still displays `active`.
> To make it display `NOT active`, the command has to be delayed further with a timer:
> 
>     vim -Nu NONE --cmd 'au VimEnter * call timer_start(0, {-> execute("windo \"") + execute("1wincmd w")})' --cmd 'au BufWinEnter,WinEnter * setl stl=active' --cmd 'au BufWinLeave,WinLeave * setl stl=NOT\ active' -O /tmp/file{1..2}
>                                       ^^^^^^^^^^^^^^^^
> 
> And only with a timer; I tried to delay with a one-shot autocmd listening to `SafeState`, but it doesn't work:
> 
>     vim -Nu NONE --cmd 'au VimEnter * au SafeState * ++once exe "windo \"" | 1wincmd w' --cmd 'au BufWinEnter,WinEnter * setl stl=active' --cmd 'au BufWinLeave,WinLeave * setl stl=NOT\ active' -O /tmp/file{1..2}
>                                       ^^^^^^^^^^^^^^^^^^^^^

On the VimEnter autocommand you will want to loop through all the
windows, or at least do enough to make the statusline update the way you
want it.

-- 
From "know your smileys":
 :-E	Has major dental problems

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
