### ISSUE TITLE
I translated 'README.md' and 'CONTRIBUTING.md' file into Korean.

### ISSUE THREAD

**Issue by cjw1359** [vim/vim#5245]
I hope that Korean people will know more about your project.
Can you add our Korean translation file to your project?

https://github.com/cjw1359/opensource/blob/master/Vim/README.md
https://github.com/cjw1359/opensource/blob/master/Vim/CONTRIBUTING.md

**Comment by k-takata** [comment]
I'm not sure whether they should be added into this project.
If they are added, I think they should be renamed to README.ko.md and CONTRIBUTING.ko.md, and put into the READMEdir directory, and add links from README.md and CONTRIBUTING.md.

Are you going to keep them up-to-date when the original README.md and CONTRIBUTING.md are updated?

**Comment by cjw1359** [comment]
Yes. I changed my file name to README_kr.md, CONTRIBUTING_kr.md. And I have a lot of interesting with vim project, so I will keep participating. Please update our file. Thank you:)

https://github.com/cjw1359/opensource/blob/master/Vim/README_kr.md
https://github.com/cjw1359/opensource/blob/master/Vim/CONTRIBUTING_kr.md

**Comment by k-takata** [comment]
"ko" is used for language code and "kr" is used for country code. So, "ko" is better.

**Comment by cjw1359** [comment]
Sorry, I've revised it again.

https://github.com/cjw1359/opensource/blob/master/Vim/README_ko.md
https://github.com/cjw1359/opensource/blob/master/Vim/CONTRIBUTING_ko.md

**Comment by brammool** [comment]
> Sorry, I've revised it again.
> 
> https://github.com/cjw1359/opensource/blob/master/Vim/README_ko.md
> https://github.com/cjw1359/opensource/blob/master/Vim/CONTRIBUTING_ko.md

I appreciate the effort.  I'm a bit worried the text will get outdated.
And including only one translation is a bit skewed.

How about including links for now?  Let me try something.


-- 
From "know your smileys":
 |-(	Contact lenses, but has lost them

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
closing for now.
