### ISSUE TITLE
Regression: vi' does not select anything with selection=exclusive (after 8.1.2314)

### ISSUE THREAD

**Issue by inkarkat** [vim/vim#5247]
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Describe the bug**
The fix for #5183 (_Vim 8.1.2314  vi' sometimes does not select anything_) introduces a regression when not selecting from the second `'`.

**To Reproduce**
Detailed steps to reproduce the behavior:

    $ vim --clean \
      -c "set buftype=nofile selection=exclusive" \
      -c "call setline(1, \"'here'\")" \
      -c "normal! wvi'y" \
      -c "execute (@@ == 'here' ? '' : 'c') . 'quit'"

Or, using the example from #5183:

    vim --clean
    :set selection=exclusive<CR>
    i
    foo 'bar' baz<Esc>
    0Wvi'

**Expected behavior**

Nothing is selected when on the first `'` and on the `b`. When on `a`, only `ba` is selected (the `r` is missed).

**Environment (please complete the following information):**
 - My plugin test suite picked up the problem with Vim version 8.1.2318
 - OS: Ubuntu 16.04 64-bit
 - Terminal: GNOME Terminal, GUI

**Comment by brammool** [comment]
Fixed by  8.1.2330
