### ISSUE TITLE
Update to Strawberry Perl 5.30.1.1 breaks Vim on MSVC ...

### ISSUE THREAD

**Issue by dertuxmalwieder** [vim/vim#5267]
As always, using my [compilation script](https://tuxproject.de/projects/vim/_compile.bat.php):

I updated Strawberry Perl from 5.30.0 to 5.30.1 - and now, Vim refuses to build:

    if_perl.obj : error LNK2001: Nicht aufgelöstes externes Symbol "__builtin_expect".
    vim64.dll : fatal error LNK1120: 1 nicht aufgelöste Externe

I imagine that some flag has changed.

**Comment by dertuxmalwieder** [comment]
It is still not working on latest trunk.

**Comment by dertuxmalwieder** [comment]
Just double-checked: Not working with 5.30.0.1 anymore either. Wtf...

**Comment by dertuxmalwieder** [comment]
Hmm, something seems to have changed...

Fixed in Perl's `config.h`:

    // #define HAS_BUILTIN_EXPECT

Not a Vim problem, presumably. Sorry! :-)

**Comment by k-takata** [comment]
I think this can be worked around in Vim side:

```diff
--- a/src/if_perl.xs
+++ b/src/if_perl.xs
@@ -48,6 +48,10 @@
 #ifdef _MSC_VER
 # define __inline__ __inline
 #endif
+/* Work around for using MSVC and Strawberry Perl 5.30. */
+#ifdef _MSC_VER
+# define __builtin_expect(expr,val) (expr)
+#endif
 
 #ifdef __GNUC__
 # pragma GCC diagnostic push
```

**Comment by tonymec** [comment]
This creates two consecutive ifdefs for the same condition. I suggest:
```diff
--- a/src/if_perl.xs
+++ b/src/if_perl.xs
@@ -48,4 +48,6 @@
 #ifdef _MSC_VER
 # define __inline__ __inline
+// Work around for using MSVC and Strawberry Perl 5.30.
+# define __builtin_expect(expr,val) (expr)
 #endif
 
```


Best regards,
Tony.

**Comment by brammool** [comment]
OK, let's include that and see if someone complains about any regressions.
