### ISSUE TITLE
`:const` and `:[un]lockvar` wrongly parse `| endif` as their argument if the `if` test fails

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#5269]
**Describe the bug**

`:const` and `:[un]lockvar` wrongly parse `| endif` as their argument if the matching `if` test fails.

**To Reproduce**

Write this in `/tmp/vim.vim`:

    if 0 | const a = 1 | endif

Then, start Vim like this:

    vim -Nu NONE -S /tmp/vim.vim

The error `E171` is raised:

    Error detected while processing /tmp/vim.vim:
    line    2:
    E171: Missing :endif

**Expected behavior**

No error is raised, because the `:endif` is not missing.

**Environment**

 - Vim version:  8.1 Included patches: 1-2342
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

The same issue applies to `:lockvar`:

    vim -Nu NONE -S <(echo 'if 0 | lockvar a | endif')
    E171: Missing :endif

And `:unlockvar`:

    vim -Nu NONE -S <(echo 'if 0 | unlockvar a | endif')
    E171: Missing :endif

---

If the test succeeds, no error is raised:

                               v
    vim -Nu NONE -S <(echo 'if 1 | const a = 1 | endif')
    vim -Nu NONE -S <(echo 'if 1 | lockvar a | endif')
    vim -Nu NONE -S <(echo 'if 1 | unlockvar a | endif')
                               ^

---

If the `endif` is on a separate line, no error is raised, regardless of the test result:

    vim -Nu NONE -S <(cat <<'EOF'
        if 0 | const a = 1
        endif
    EOF
    )

    vim -Nu NONE -S <(cat <<'EOF'
        if 1 | const a = 1
        endif
    EOF
    )

---

If the command is run directly from the shell command-line via the `+` argument, no error is raised:

    vim -Nu NONE +'if 0 | const a = 1 | endif'

I don't understand why; if it fails from a sourced file, I would expect it to also fail here.

---

You can prevent `:const` and `:[un]lockvar` from parsing `| endif` as their argument by wrapping them inside an `:execute`:

    if 0 | exe 'const a = 1' | endif
           ^^^

---

It is unexpected for `:const` and `:[un]lockvar` to consume `| endif` because:

   - The help doesn't say that they see a bar as their argument (at least they are not mentioned at `:h :bar`).

   - It doesn't make sense for them to see a bar as their argument.
     `:[un]lockvar` expects an optional number argument (`[depth]`), and one or several variable names (`{name}`).
     A bar is not a number, so `:[un]lockvar` can't parse it as `[depth]`.
     And a bar can't be used inside a variable name (`:let a|b = 1` raises `E121`, similar to `let a`),
     so `:[un]lockvar` can't parse it as `{name}`. I think the same is true for `:const`.

   - Even if it made sense for them to parse a bar as their argument, this is done inconsistently. Only when the test fails inside an `if test | ... | endif` block; not when the test succeeds.

---

Here is another command which also unexpectedly consumes a following `| endif`:

    if 0 | unknown_cmd | endif
    E171: Missing :endif

In practice, this can cause an issue when you try to run a command on the condition that the Vim binary includes the patch which implements it.
For example, suppose you want to redraw the tab line: you can execute `:redrawtabline` if your Vim binary includes `8.1.0706`, otherwise you can execute `let &ro = &ro` for an older Vim (to force an update by setting an option without changing its value):

    if has('patch-8.1.0706') | redrawt | else | let &ro = &ro | endif

If you run this command in a recent Vim which includes `8.1.0706`, it works as expected (i.e. `:redrawt` is executed). But if you run it on an older Vim, it raises `E171`. The error can be suppressed by wrapping `:redrawt` inside an `:execute`:

    if has('patch-8.1.0706') | exe 'redrawt' | else | let &ro = &ro | endif
                               ^^^

Or by moving `endif` on a dedicated line:

    if has('patch-8.1.0706') | redrawt | else | let &ro = &ro
    endif

Although in that case, `let &ro = &ro` is not executed and the tab line is not redrawn; presumably because `:redrawt` still consumes `| else | let &ro = &ro`. You need to also move `else` and `let &ro = &ro` on another line:

    if has('patch-8.1.0706') | redrawt
    else | let &ro = &ro | endif

---

Finally, a known command with a wrong syntax raises an error even if it's inside a skipped `if` block.
For example:

    if 0
        clear x
    endif
    E488: Trailing characters:     clear x

I would expect no error, because the `if` test fails, and so `clear x` should be skipped.
I guess that:

   - Vim has to parse the commands after `if` to find the matching `endif`
   - during the parsing, Vim has to check the syntax of the commands to determine when one starts and when one ends
   - when finding a syntax error in a command, Vim raises an error, even if the command will not be executed later

I'm not sure, but maybe it could be considered as a bug. For example, it creates an issue when you try to source this code:

    if has('patch-8.1.1354')
        let [a,b] =<< trim END
            clear x
            y
        END
    else
        let [a,b] = ['clear x', 'y']
    endif

With a Vim binary which includes the patch `8.1.1354` (the latter implements the heredoc operator `=<<`), the code works as expected (i.e. the strings `'clear x'` and `'y'` are assigned to the variables `a` and `b`).
But with a Vim binary which does not include the patch, the variables are not assigned anything, and `E488` is raised:

    E488: Trailing characters:         clear x

This is because `clear` was parsed as the `:clearjumps` command, and the latter does not accept any argument.

**Comment by brammool** [comment]
> **Describe the bug**
> 
> `:const` and `:[un]lockvar` wrongly parse `| endif` as their argument if the matching `if` test fails.
> 
> **To Reproduce**
> 
> Write this in `/tmp/vim.vim`:
> 
>     if 0 | const a = 1 | endif
> 
> Then, start Vim like this:
> 
>     vim -Nu NONE -S /tmp/vim.vim
> 
> The error `E171` is raised:
> 
>     Error detected while processing /tmp/vim.vim:
>     line    2:
>     E171: Missing :endif
> 
> **Expected behavior**
> 
> No error is raised, because the `:endif` is not missing.
> 
> **Environment**
> 
>  - Vim version:  8.1 Included patches: 1-2342
>  - OS: Ubuntu 16.04.6 LTS
>  - Terminal: XTerm(322)
> 
> **Additional context**

I'll fix this one.

Please file separate issues for separate problems, we can't half-close
an issue.

> 
> The same issue applies to `:lockvar`:
> 
>     vim -Nu NONE -S <(echo 'if 0 | lockvar a | endif')
>     E171: Missing :endif
> 
> And `:unlockvar`:
> 
>     vim -Nu NONE -S <(echo 'if 0 | unlockvar a | endif')
>     E171: Missing :endif

Similar problem, I'll fix this in a separate patch.
 
> ---
> 
> If the test succeeds, no error is raised:
> 
>                                v
>     vim -Nu NONE -S <(echo 'if 1 | const a = 1 | endif')
>     vim -Nu NONE -S <(echo 'if 1 | lockvar a | endif')
>     vim -Nu NONE -S <(echo 'if 1 | unlockvar a | endif')
>                                ^
> 
> ---
> 
> If the `endif` is on a separate line, no error is raised, regardless of the test result:
> 
>     vim -Nu NONE -S <(cat <<'EOF'
>         if 0 | const a = 1
>         endif
>     EOF
>     )
> 
>     vim -Nu NONE -S <(cat <<'EOF'
>         if 1 | const a = 1
>         endif
>     EOF
>     )
> 
> ---
> 
> If the command is run directly from the shell command-line via the `+` argument, no error is raised:
> 
>     vim -Nu NONE +'if 0 | const a = 1 | endif'
> 
> I don't understand why; if it fails from a sourced file, I would expect it to also fail here.
> 
> ---
> 
> You can prevent `:const` and `:[un]lockvar` from parsing `| endif` as their argument by wrapping them inside an `:execute`:
> 
>     if 0 | exe 'const a = 1' | endif
>            ^^^
> 
> ---
> 
> It is unexpected for `:const` and `:[un]lockvar` to consume `| endif` because:
> 
>    - The help doesn't say that they see a bar as their argument (at least they are not mentioned at `:h :bar`).
> 
>    - It doesn't make sense for them to see a bar as their argument.
>      `:[un]lockvar` expects an optional number argument (`[depth]`), and one or several variable names (`{name}`).
>      A bar is not a number, so `:[un]lockvar` can't parse it as `[depth]`.
>      And a bar can't be used inside a variable name (`:let a|b = 1` raises `E121`, similar to `let a`),
>      so `:[un]lockvar` can't parse it as `{name}`. I think the same is true for `:const`.
> 
>    - Even if it made sense for them to parse a bar as their argument, this is done inconsistently. Only when the test fails inside an `if test | ... | endif` block; not when the test succeeds.
> 
> ---
> 
> Here is another command which also unexpectedly consumes a following `| endif`:
> 
>     if 0 | unknown_cmd | endif
>     E171: Missing :endif

This is expected, because for finding the "endif" the command needs to
be recognized.  You can only use separate lines:

    if 0
      unknown_cmd
    endif

> In practice, this can cause an issue when you try to run a command on
> the condition that the Vim binary includes the patch which implements
> it.
> For example, suppose you want to redraw the tab line: you can execute
> `:redrawtabline` if your Vim binary includes `8.1.0706`, otherwise you
> can execute `let &ro = &ro` for an older Vim (to force an update by
> setting an option without changing its value):
> 
>     if has('patch-8.1.0706') | redrawt | else | let &ro = &ro | endif
> 
> If you run this command in a recent Vim which includes `8.1.0706`, it works as expected (i.e. `:redrawt` is executed). But if you run it on an older Vim, it raises `E171`. The error can be suppressed by wrapping `:redrawt` inside an `:execute`:
> 
>     if has('patch-8.1.0706') | exe 'redrawt' | else | let &ro = &ro | endif
>                                ^^^
> 
> Or by moving `endif` on a dedicated line:
> 
>     if has('patch-8.1.0706') | redrawt | else | let &ro = &ro
>     endif
> 
> Although in that case, `let &ro = &ro` is not executed and the tab line is not redrawn; presumably because `:redrawt` still consumes `| else | let &ro = &ro`. You need to also move `else` and `let &ro = &ro` on another line:
> 
>     if has('patch-8.1.0706') | redrawt
>     else | let &ro = &ro | endif

You need to put the commands on separate lines.
 
> ---
> 
> Finally, here is a command which raises an error even though it is skipped:
> 
>     if 0
>         clear x
>     endif
>     E488: Trailing characters:     clear x
> 
> I would expect no error, because the `if` test fails, and so `clear x` should be skipped.
> I guess that:
> 
>    - Vim has to parse the commands after `if` to find the matching `endif`
>    - during the parsing, Vim has to check the syntax of the commands to determine when one starts and when one ends
>    - when finding a syntax error in a command, Vim raises an error, even if the command will not be executed later

For a command that does not take an argumen the check for the next
command doesn't skip anything.  Thus this works as intended.
 
> I'm not sure, but maybe it could be considered as a bug. For example, it creates an issue when you try to source this code:
> 
>     if has('patch-8.1.1354')
>         let [a,b] =<< trim END
>             clear x
>             y
>         END
>     else
>         let [a,b] = ['clear x', 'y']
>     endif
> 
> With a Vim binary which includes the patch `8.1.1354` (the latter implements the heredoc operator `=<<`), the code works as expected (i.e. the strings `'clear x'` and `'y'` are assigned to the variables `a` and `b`).
> But with a Vim binary which does not include the patch, the variables are not assigned anything, and `E488` is raised:
> 
>     E488: Trailing characters:         clear x

I don't see this as a problem.  Using =<< will always have a potential
problem for Vim versions that don't recognize it.  Just like using
heredoc for other commands, such as :python.


-- 
Statistics say that you can have a baby per month on average:
Just get nine women pregnant.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
