### ISSUE TITLE
[Documentation] bad example for WORDs motion

### ISSUE THREAD

**Issue by Shir0kamii** [vim/vim#527]
Hi,

reading the help (in [usr_03.txt](https://github.com/vim/vim/blob/master/runtime/doc/usr_03.txt)), I found an example about WORDs motion : 

```
               ge      b          w                             e
               <-     <-         --->                          --->
        This is-a line, with special/separated/words (and some more).
           <----- <-----         -------------------->         ----->
             gE      B                   W                       E
```

But for me the beavior is : 

```
               ge      b          w                             e
           <----- <-----         -------------------->         ----->
        This is-a line, with special/separated/words (and some more).
           <----- <-----         -------------------->         ----->
             gE      B                   W                       E
```

When I tried to reproduce it in a normal buffer, I had the expected behaviour.

Tell me if I'm wrong, but this behaviour seems to be related to the help, probably to the format of help files.

First, is it normal ? If yes, I find this behaviour strange or at least it doesn't fit the help. Not being able to reproduce the motion while reading help is quite confusing.

What do you think of this ?

**Comment by ZyX-I** [comment]
@Shir0kamii This is the effect of using `&iskeyword` setting for too many purposes. Specifically:
1. It applies to word-based motions.
2. It applies to regular expressions, which is why you may see it in syntax files.
3. It applies to things that use word under cursor for their own purposes, which is why you may see it in ftplugin files.

Last is your case here: `,` is used in some help tags, so for `<C-]>` motion to work properly for these tags `,` must be a word character (same for `-`, `)`, `.` and `/`). World would really be better if 2 and 3 were disconnected from 1; part of this may be achieved by recent `syntax option iskeyword` patch, part by creating a filetype plugin which creates `<C-]>` mapping in place of modifying `&iskeyword` option.

**Comment by brammool** [comment]
Alexandre Bonnetain wrote:

> reading the help (in [usr_03.txt](https://github.com/vim/vim/blob/master/runtime/doc/usr_03.txt)), I found an example about WORDs motion : 
> 
> ```
>                ge      b          w                             e
>                <-     <-         --->                          --->
>         This is-a line, with special/separated/words (and some more).
>            <----- <-----         -------------------->         ----->
>              gE      B                   W                       E
> ```
> 
> But for me the beavior is : 
> 
> ```
>                ge      b          w                             e
>            <----- <-----         -------------------->         ----->
>         This is-a line, with special/separated/words (and some more).
>            <----- <-----         -------------------->         ----->
>              gE      B                   W                       E
> ```
> 
> When I tried to reproduce it in a normal buffer, I had the expected
> behaviour.
> 
> Tell me if I'm wrong, but this behaviour seems to be related to the
> help, probably to the format of help files.
> 
> First, is it normal ? If yes, I find this behaviour strange or at
> least it doesn't fit the help. Not being able to reproduce the motion
> while reading help is quite confusing.
> 
> What do you think of this ?

There is a remark about 'iskeyword', but it's not very clear.  Let's
change it to this:

A word ends at a non-word character, such as a ".", "-" or ")".  To change
what Vim considers to be a word, see the 'iskeyword' option.  If you try this
out in the help directly, 'iskeyword' needs to be reset for the examples to
work: >
    :set iskeyword&

Thanks for pointing out the confusing example!

## 

"Marriage is when a man and woman become as one; the trouble starts
when they try to decide which one"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Shir0kamii** [comment]
I didn't paid enough attention, thank you for pointing that out.

I think it is a good change, as it won't confuse anyone with this. Should I make a pull request ?

**Comment by chrisbra** [comment]
I think this is fixed with https://github.com/vim/vim/commit/256972a9849b5d575b62a6a71be5b6934b5b0e8b so closing.
