### ISSUE TITLE
xxd enters infinite loop with some inputs

### ISSUE THREAD

**Issue by aslvim** [vim/vim#5272]
`xxd -r` hits an infinite loop for some inputs:

for example, `echo -en '41414141\n\n' | xxd -r` will run forever, spinning.

**Environment:**

`xxd V1.10 27oct98 by Juergen Weigert`
`VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov  7 2019 22:30:47)`

x86_64 Arch Linux

**Comment by vim-ml** [comment]
You should add the "-p" option to your command (as documented in the xxd
man page):

$ echo -en '41414141\n\n' | xxd -r -p
AAAA$

Antonio


On Wed, Nov 27, 2019 at 6:25 AM aslvim <vim-dev-github@256bit.org> wrote:

> xxd -r hits an infinite loop for some inputs:
>
> for example, echo -en '41414141\n\n' | xxd -r will run forever, spinning.
>
> *Environment:*
>
> xxd V1.10 27oct98 by Juergen Weigert
> VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 7 2019 22:30:47)
>
> x86_64 Arch Linux
>
-- 
   /||\    | Antonio Colombo
  / || \   |  azc100@gmail.com
 /  ()  \  | antonio@geekcorp.com
(___||___) |   azc10@yahoo.com
