### ISSUE TITLE
Popup window sign_place has no effect

### ISSUE THREAD

**Issue by habamax** [vim/vim#5277]
**Describe the bug**

For buffer of popup window sign_place has no effect at all:

![image](https://user-images.githubusercontent.com/234774/69253779-3c38b180-0bc6-11ea-9925-acce8d18c0e4.gif)

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean`
3. Edit `~/vimtest.vim` and type
```
" sign place here

call sign_define('clapCurrentSelected', {
	\ 'text': '>>',
	\ 'texthl': 'WarningMsg',
	\ 'linehl': 'Error',
	\ })

let g:display_winid = popup_create(['hello', 'world'], {
	\ 'wrap': v:false,
	\ 'mapping': v:false,
	\ 'cursorline': 0,
	\ 'scrollbar': 0,
	\ 'minwidth': 20,
	\ 'maxwidth': 20,
	\ 'minheight': 20,
	\ 'maxheight': 20
	\ })

let g:display_bufnr = winbufnr(g:display_winid)

" add sign to current buffer
call sign_place(1, 'clapCurrentSelected2', 'clapCurrentSelected', bufnr('%'), {'lnum': 1})


" add sign to popup buffer
call sign_place(2, 'clapCurrentSelected', 'clapCurrentSelected', g:display_bufnr, {'lnum': 1})


```
4. Run `:so %`
5. Popup window has no sign placed

**Expected behavior**

Popup window should have sign placed

**Screenshots**
![image](https://user-images.githubusercontent.com/234774/69783387-79073880-11c4-11ea-878e-1ddf83375c5d.png)

**Environment (please complete the following information):**
 - Vim version [e.g. 8.1.2352] 
 - OS: Windows 10
 - Terminal: cmd.exe and GUI

**Additional context**
https://github.com/liuchengxu/vim-clap/issues/130
https://github.com/liuchengxu/vim-clap/issues/130#issuecomment-559266238

**Comment by brammool** [comment]
There was a previous bug which complained that signs were showing up in the popup window even though they were not supposed to.  That is when the buffer in the popup window is also displayed in a normal window, and signs have been added there.
It does work if you use the group name "popupmenu".  But that's a bit of a hack. We could also support the name "popupwindow", or the prefix "popup".
