### ISSUE TITLE
Question about crypt_zip.c

### ISSUE THREAD

**Issue by amc8391** [vim/vim#528]
Hey there,
I've been looking at the Vim source for a couple days now for a software security college project and just had a few quick questions about the crypt_zip.c file since it looked a little strange and I didn't find a whole lot of documentation on it in the readmes. The specific area of the file I mean is the "crypt_zip_init" function.

``` c
/*
 * Initialize for encryption/decryption.
 */
    void
crypt_zip_init(state, key, salt, salt_len, seed, seed_len)
    cryptstate_T    *state;
    char_u      *key;
    char_u      *salt UNUSED;
    int         salt_len UNUSED;
    char_u      *seed UNUSED;
    int         seed_len UNUSED;
{
    char_u  *p;
    zip_state_T *zs;

    zs = (zip_state_T *)alloc(sizeof(zip_state_T));
    state->method_state = zs;

    make_crc_tab();
    zs->keys[0] = 305419896L;
    zs->keys[1] = 591751049L;
    zs->keys[2] = 878082192L;
    for (p = key; *p != NUL; ++p)
    {
    UPDATE_KEYS_ZIP(zs->keys, (int)*p);
    }
}
```
- This init function takes in the state, key, salt, and seed but does not use either the salt or seed; are these not features included in this specific encryption algorithm?
- If so, what influenced the decision to keep them in the parameter list? Was it more uniform to the other encryption methods in Vim or are they there in case of further revision (or none of the above)?

Thank you in advance for your time!
--Alex Christodoulou

**Comment by brammool** [comment]
Alex Christodoulou Jr wrote:

> Hey there,
> I've been looking at the Vim source for a couple days now for a
> software security college project and just had a few quick questions
> about the crypt_zip.c file since it looked a little strange and I
> didn't find a whole lot of documentation on it in the readmes. The
> specific area of the file I mean is the "crypt_zip_init" function.
> - This init function takes in the state, key, salt, and seed but does
>   not use either the salt or seed; are these not features included in
>   this specific encryption algorithm?
> - If so, what influenced the decision to keep them in the parameter
>   list? Was it more uniform to the other encryption methods in Vim or
>   are they there in case of further revision (or none of the above)?

This function is in a table in crypt.c, it must have the same arguments
as the other crypt init functions.

## 

hundred-and-one symptoms of being an internet addict:
265. Your reason for not staying in touch with family is that
     they do not have e-mail addresses.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///
