### ISSUE TITLE
runtime/syntax/vim.vim highlights pyf[ile] but not py3f[ile]

### ISSUE THREAD

**Issue by pseyfert** [vim/vim#5282]
**Describe the bug**
The vim syntax highlighting does not highlight the py3file command. It should treat `py3f` the same way as `pyf`.
As far as I understand it's just and entry of `py3f[ile]` missing [here](https://github.com/vim/vim/blob/master/runtime/syntax/vim.vim#L24).

**To Reproduce**
1. open a vimscript file with syntax highlighting enabled
2. observe how `pyf` and `py3f` are rendered differently

**Screenshots**

**Environment (please complete the following information):**
vim 8.1 1-2268, arch linux, rxvt-unicode-256color

**Additional context**
I would've just posted a pull request, though I noticed the comment about the keyword list being generated [here](https://github.com/vim/vim/blob/master/runtime/syntax/vim.vim#L7).

![2019-11-29-182204_114x210_scrot](https://user-images.githubusercontent.com/5124749/69883706-9a0b7e80-12d5-11ea-8421-f1c7bf5e706a.png)

**Comment by brammool** [comment]
I got a new Vim syntax highlight file that will fix this.
