### ISSUE TITLE
vi{ and yi{ do not work correctly when the right brace is wrapped in a pair of quotes

### ISSUE THREAD

**Issue by alexaschee** [vim/vim#5284]
**Describe the bug**
`vi{` and `yi{` do not work correctly when the right brace is wrapped in a pair of quotes.

**To Reproduce**
1. With text like this:

`Text (abc')' text`
`Text {abc'}' text`
`Text [abc']' text`
`Text (abc")" text`
`Text {abc"}" text`
`Text [abc"]" text`

2.  Move cursor to the left ([{, type `vi(` or `yi(` or `yi{` ...

**Expected behavior**
`abc'` or `abc"`  is supposed to be highlighted or yanked.

**Environment (please complete the following information):**
 - Vim version [e.g. 8.1.2341]
 - OS: [Windows 7/10]

**Comment by brammool** [comment]
That is intentional.  These commands are usually used to select text in a program, where quotes surround a string.  And braces inside a string are to be ignored.  E.g.
if (text.equals('end) brace'))

**Comment by alexaschee** [comment]
I use vim to process a lot of tex files and often I come across text like:
``\textit{texts'}''. So ...

I'll rewrite my vim-scripts.

Thanks for your explanation.
