### ISSUE TITLE
Resource Leak found in file src/xxd/xxd.c

### ISSUE THREAD

**Issue by ChakshuGupta** [vim/vim#5287]
Resource leak found in the src/xxd/xxd.c file 

The bug can be reproduced using the following -
Detailed steps to reproduce the behavior:
1. cppcheck --force src/xxd/xxd.c

Found a resource leak in line 683.

![image](https://user-images.githubusercontent.com/6474622/69903455-bb35a300-1399-11ea-83bf-e07c2bb94f05.png)

 - Vim version: v8.1.2364
 - OS: Ubuntu 18.04

Checked the code, a file descriptor **fd** is not closed in the line 685, which is resulting in the resource leak.

**Comment by brammool** [comment]
Well, there is a "return" statement there, which means the program exits.  Thus the leak is irrelevant.
The same happens further down, I wonder why there is no warning for those.
