### ISSUE TITLE
Syntax error found in src/blowfish.c

### ISSUE THREAD

**Issue by ChakshuGupta** [vim/vim#5290]
Found a syntax error in the src/blowfish.c file, line - 44

It can be reproduced using:-
1. cppcheck --force src/blowfish.c

Expected no error.

![image](https://user-images.githubusercontent.com/6474622/69904875-d52cb100-13ac-11ea-9b4f-4e862e0f8e27.png)

 - Vim version:- v8.1.2364
 - OS:- Ubuntu 18.04

Checked the code -
![image](https://user-images.githubusercontent.com/6474622/69904905-305ea380-13ad-11ea-922a-d973ac758c1b.png)
Line 44 needs to be commented.

**Comment by brammool** [comment]
That is intentional.  The preprocessor would normally remove those lines, and if it doesn't the compiler will run into this error and fail.  Building without any symbols defined will do that.

**Comment by k-takata** [comment]
I think this is for pre-C89. Now we use C99. `#error` can be used instead.

**Comment by brammool** [comment]
Ken Takata wrote:

> I think this is for pre-C89. Now we use C99. `#error` can be used instead.

We use C89 and some of C99.  I think that #error was part of C89, but I
can't find a definitive answer.

-- 
"Hit any key to continue" is very confusing when you have two keyboards.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
Yes, AFAIK, `#error` is available from C89.
C99 only added `_Pragma` operator to preprocessor directives.
https://en.cppreference.com/w/c/preprocessor

Draft version of C99 is available at here:
http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf
`#error` is described at section 6.10.5.
I couldn't find C89/C90.

Anyway, I think we can use `#error`.
