### ISSUE TITLE
Common realloc mistake, memory nulled but not freed.

### ISSUE THREAD

**Issue by ChakshuGupta** [vim/vim#5292]
Hey @brammool, 
Running some more cppchecks in the code. Hope you don't mind.

Error found when using realloc in multiple files -  src/gui_photon.c, src/os_vms.c

It can be reproduced with the following-
1. cppcheck src/gui_photon.c 
2. cppcheck src/os_vms.c

![image](https://user-images.githubusercontent.com/6474622/69905775-f0052280-13b8-11ea-869b-53a37dfda626.png)

![image](https://user-images.githubusercontent.com/6474622/69905781-f6939a00-13b8-11ea-8236-df7c35189937.png)

If **realloc** fails, then the original memory allocation exists but is leaked as it is no longer referred to by the same variable.

 - Vim version:- v8.1.2364
 - OS:- Ubuntu 18.04

**Comment by brammool** [comment]
It's good to check for mistakes, but it's more useful if you copy/paste the text instead of including a screenshot.

The problem in gui_photon.c is worse: it doesn't check for NULL at all.  I hope someone who can build Vim with this file will send a patch.

I'll fix the ones in os_vms.c

**Comment by ChakshuGupta** [comment]
Okay noted!

**Comment by chandni1003** [comment]
I am getting the following error on running the splint debugger tool for the above 2 programs. I thought I should inform you of them.
![image](https://user-images.githubusercontent.com/37014697/69908071-6702e100-13e2-11ea-9610-8de064ce1acc.png)
