### ISSUE TITLE
Undefined behavior: Variable 'buf1' is used as parameter and destination in s[n]printf().

### ISSUE THREAD

**Issue by ChakshuGupta** [vim/vim#5293]
Error found in src/os_amiga.c on line - 448

Undefined behavior: Variable 'buf1' is used as parameter and destination in s[n]printf().

Detailed steps to reproduce the behavior:
1.  cppcheck src/os_amiga.c

![image](https://user-images.githubusercontent.com/6474622/69905882-bd5c2980-13ba-11ea-9e25-0343c14f1b11.png)

- Vim version:- v8.1.2364
- OS:- Ubuntu 18.04

**Comment by brammool** [comment]
That is a mistake in the analyzer: the "buf1" argument is a pointer, not the value.
