### ISSUE TITLE
v:register not cleared

### ISSUE THREAD

**Issue by andymass** [vim/vim#5294]
I realize this has been mentioned before but it has been a while, so maybe it can be revisited.

**Describe the bug**
v:register is not reset between commands, which leads to issues when following up any normal command issued with `"_`, then a custom command which needs v:register.

**To Reproduce**
Detailed steps to reproduce the behavior:
```vim
function s:DoPut()
  execute 'normal! "' .. v:register .. 'p'
endfunction

nnoremap d "_d
nnoremap p :call <sid>DoPut()<cr>
```

The first `p` after typing `dd` puts nothing.  The second will put whatever is in `"`.  (This applies to any registers, not just `_`)

**Expected behavior**
Ideally, `"{reg}d` should take effect only for that 'single' normal command.  This is really tricky because custom normal commands usually work through the `:` command, so it's important not to clear it too early.  Note, it is cleared when using `hjkl` between the two commands, it's not persisted forever.

**Environment (please complete the following information):**
 - vim 8.1.2369

**Additional context**
As an example, I made a quick patch which seems to work.  v:register should be cleared at the end of a user's mapped command, but not before the function call.  Ideally, this can be addressed without affecting any plugins.  If compatibility with plugins is still a concern, a new variable or cpoptions can be added.  But, the existing behavior is (imo) very unexpected and inconsistent, even if the behavior has been around for a long time and has been noticed before.

Note: updated patch in pull request below.

**Comment by k-takata** [comment]
Fixed in [8.2.0929](https://github.com/vim/vim/commit/cc613031b96f1cfa5a184253e745c26f1def9be4).
