### ISSUE TITLE
gcc not compiling because of include vterm.h

### ISSUE THREAD

**Issue by chandni1003** [vim/vim#5295]
I tried running vterm-dump.c and unterm.c via the gcc compiler and it gave an error regarding the vterm.h header class. I noticed it was entered as include "vterm.h"
It can be solved by include <vterm.h>

Detailed steps to reproduce the behavior:
1. Run gcc unterm.h -o output
2. Error will be shown on the include file

Expected behavior:
The compiler must run without errors

Screenshots:
![image](https://user-images.githubusercontent.com/37014697/69907297-dcff4c00-13d2-11ea-8788-b06dd55df7a2.png)

Environment :
 - OS: Ubuntu 19.10
 - Terminal

**Comment by k-takata** [comment]
Vim doesn't use the files in src/libvterm/bin/. Try using src/livterm/Makefile.

**Comment by brammool** [comment]
I have now removed the files in src/libvterm/bin/ to avoid any confusion
