### ISSUE TITLE
Warnings in vterm-ctrl.c

### ISSUE THREAD

**Issue by chandni1003** [vim/vim#5297]
**Describe the bug**
I was running the splint debugging tool on the C files in this repository to check for errors, but I found 55 warnings in the could that could affect the quality of the code. Hence I am sharing them with you.

**To Reproduce**
1. splint -preproc -exportlocal vterm-ctrl.c

**Screenshots**
![image](https://user-images.githubusercontent.com/37014697/69907485-2c934700-13d6-11ea-8c29-bff5a143f6a6.png)
![image](https://user-images.githubusercontent.com/37014697/69907496-551b4100-13d6-11ea-814b-b63a23069a61.png)
![image](https://user-images.githubusercontent.com/37014697/69907503-6b290180-13d6-11ea-956e-ab19390b6d23.png)

**Environment (please complete the following information):**
Ubuntu 19.10, Terminal

**Comment by k-takata** [comment]
Vim doesn't use vterm-ctrl.c. Please report to upstream.
