### ISSUE TITLE
":help /\V" does not mention special meaning of "/"

### ISSUE THREAD

**Issue by justinmk** [vim/vim#530]
`:help /\V` states the following:

```
Use of "\V" means that in the pattern after it only the backslash has a                                                                                     
special meaning.  "very nomagic"
```

But this seems incorrect, because `/` (forward-slash) still must be escaped with a backslash.

**Comment by chrisbra** [comment]
Only, when using '/' for searching, because than the '/' would terminate the search command.

 If you use `:let @/='\V/' then it works as expected.

This is actually not a bug.

**Comment by justinmk** [comment]
Er, ok. It's still confusing as a user when `/\Vfoo/bar<cr>` invokes the special meaning of `/`, contrary to the documentation of `:help /\V`.
