### ISSUE TITLE
GVim operator pending mode getting cancelled on X

### ISSUE THREAD

**Issue by sosmo** [vim/vim#5300]
**Describe the bug**

Updating from Vim 8.1.0320 to 8.1.0875 on Kubuntu, I've noticed that keyboard input handling has changed. GVim now exits operator pending mode when I perform any action in my window manager (KDE Plasma 5.16.5, X version), even if the action doesn't send a "real" keystroke to the active window. For example, if I press "d" in normal mode to enter operator pending mode and then press "alt+tab" to change the WM window, gVim's operator pending mode ends. Additionally, this also happens when changing the window using the mouse, but it can also happen with any shortcut that doesn't change the focused window.

I'm not sure if this is a bug or a new feature, but I couldn't find a way to change it. Terminal Vim, nVim-qt and Emacs don't behave similarly. Sadly this can break keyboard remaps by causing operator pending mode to end before the keys are sent (since the trigger combo ends operator pending), so I think it could warrant a look

**Environment**
 - Vim version 8.1.0875 
 - OS: Kubuntu 19.10
 - Terminal: GUI

**Comment by chrisbra** [comment]
do you have any FocusLost/FocusGained autocommand installed?

**Comment by sosmo** [comment]
I actually do have one, but I should have mentioned it also happens with `gvim --clean`
