### ISSUE TITLE
in `:cexpr system(cmd1 | cmd2)` the shell pipe character is unexpectedly parsed as command termination

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#5306]
**Describe the bug**

When passing a `system()` expression to `:cexpr`, if the shell command includes a pipe character, the latter is unexpectedly parsed as command termination.

**To Reproduce**

Start Vim like this:

    vim -Nu NONE

Then, execute this Ex command:

    :cexpr system('grep -Rn grail '..$VIMRUNTIME..' | grep -v tag')

The errors `E115` and `E116` are raised:

    E115: Missing quote: '
    E116: Invalid arguments for function system('grep -Rn grail '..$VIMRUNTIME..'

**Expected behavior**

No error is raised, Vim edits the file `$VIMRUNTIME/doc/index.txt`, and the quickfix list is populated with this entry:

    {'lnum': 1121,
     'bufnr': 2,
     'col': 0,
     'pattern': '',
     'valid': 1,
     'vcol': 0,
     'nr': -1,
     'type': '',
     'module': '',
     'text': 'You found it, Arthur!                         *holy-grail* *:smile*',}

**Environment**

 - Vim version:  8.1 Included patches: 1-2367
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

For the `:cexpr` command to work, the shell pipe character needs to be escaped with a backslash:

    :cexpr system('grep -Rn grail '..$VIMRUNTIME..' \| grep -v tag')
                                                    ^^

Otherwise, it's parsed as command termination. This is unexpected because:

   - the bar is inside a quoted string, so Vim should process it as a literal character.
    (just like when you execute `:echo 'foo | bar'`)

   - it's inconsistent with other Ex commands which also accept a `system()` expression as argument:

                                                         v
         :echo system('grep -Rn grail '..$VIMRUNTIME.. ' | grep -v tag')
         :echo expand('`grep -Rn grail '..$VIMRUNTIME..' | grep -v tag`')
         :sp `=system('grep -Rn grail '..$VIMRUNTIME.. ' | grep -v tag | tail -1 | cut -d: -f1')`
                                                         ^             ^         ^

   Notice how in those last three commands, the bar is never escaped with a backslash, and yet they all work as expected; Vim never parses the bar as command termination.

**Comment by chrisbra** [comment]
that is intentionally and mentioned briefly at [:h :bar](https://vimhelp.org/cmdline.txt.html#:bar) so the command can be followed by another command.

To fix it, one needs to remove the `EX_TRLBAR`  flag from the `ex_cexpr` definition (most likely for all the `:cexpr` variants. Note however, if this is changed, `:cexpr ... | anothercmd` won't work anymore.

**Comment by lacygoill** [comment]
As a user, I would have expected the bar to be ignored in `:cexpr system('cmd1 | cmd2')` (because inside a string), and parsed as command termination in `:cexpr ... | anothercmd` (because outside a string), which I guess is only possible if the parsing is done in several steps...

Anyway, it seems it's working as intended, so I close the issue. Thank you very much for the explanation; the current behavior makes sense now.

**Comment by lacygoill** [comment]
> Note however, if this is changed, :cexpr ... | anothercmd won't work anymore.

Is it possible to change `:cexpr` so that `:cexpr ... | anothercmd` works like it does now, and `:cexpr system('cmd1 | cmd2')` works too? Similar to how `:echo` terminates at a bar outside a string, but not at a bar inside a string:

    :echo 'a|b' | let c=1
            ^   ^

If not, why can `:echo` do it, but not `:cexpr`?

**Comment by brammool** [comment]
> > Note however, if this is changed, :cexpr ... | anothercmd won't work anymore.
> 
> Is it possible to change `:cexpr` so that `:cexpr ... | anothercmd`
> works like it does now, and `:cexpr system('cmd1 | cmd2')` works too?
> Similar to how `:echo` terminates at a bar outside a string, but not
> at a bar inside a string:
> 
>     :echo 'a|b' | let c=1
>             ^   ^
> 
> If not, why can `:echo` do it, but not `:cexpr`?

It is possible, the command needs to find the next command itself,
instead of using the generic code that finds the "|" anywhere in the
argument.  In this case the expression needs to be parsed to find the
end, then the "nextcmd" pointer needs to be set.

Can you reopen this issue?

-- 
If Microsoft would build a car...
... The airbag system would ask "are you SURE?" before deploying.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bfrg** [comment]
I have noticed the same behavior with `:grep` and `grepprg`.

Running `:grep foo` with
```vim
let &grepprg='rg --vimgrep --smart-case $* \| sort -V'
```
works fine. But when I set
```vim
let &grepprg='rg --vimgrep --smart-case $* | sort -V'
```
and run `:grep foo`, Vim will try to run `:sort` after `:grep`.

**Comment by lacygoill** [comment]
Closing since it has been fixed by https://github.com/vim/vim/commit/88a3e2b2ac33e3bb4b7cf9132eb75db051e8f4ed.
