### ISSUE TITLE
Strange E212 issues saving SFTP/GVFS files in (local) Vim...

### ISSUE THREAD

**Issue by kuraga** [vim/vim#5309]
Good day!

I have a very strange issue with a clean Gentoo full Vim/GVim 8.1.1486.

There is a server. I have an `E212: Can't open file for writing` error on saving _files with eXecute chmod enabled_ in Vim from this server (Vim is local; open file via SFTP/GVFS). I have no issues on saving files in (local) mcedit.

I even don't know what to do next...

**Comment by chrisbra** [comment]
do you have any kind of umask set there? Can you reproduce using `vim --clean` Does setting `backupcopy` make a difference?

**Comment by kuraga** [comment]
@chrisbra , thanks for reply!

> do you have any kind of umask set there?

I don't do it. `umask` (locally and remotely) outputs `0022`.

>  Can you reproduce using `vim --clean`

Yes.

> Does setting `backupcopy` make a difference?

Ahaaaaaa! Setting `set backupcopy=no` avoids the error.
And I _can't_ (locally) `touch 'file~'` if `file` has eXecute chmod enabled. Otherwise I can (locally).
Whaaaaat?
(BTW I can `touch 'file~'` remotely; `file~` won't have eXecute chmod enabled.)

**Comment by kuraga** [comment]
So close since it's not a Vim bug (UPD: or is; see below). But 'd very pleased if you point a direction to investigate :)

**Comment by jamessan** [comment]
Sounds like a duplicate of https://github.com/vim/vim/issues/5237.
