### ISSUE TITLE
vim mode and mapping

### ISSUE THREAD

**Issue by ri-aje** [vim/vim#5310]
hi, I use colemak keyboard layout, and put many mappings in my vimrc to simulate vim finger movements on the original querty layout. it mostly works fine but there are some mappings don't work up to expectation and I am trying to understand why. for example, if I have these mappings
```
noremap u i
noremap r p
```
I expect pressing `vur` to select current paragraph since that should be mapped to `vip`. in reality, however, I have to press `vup` to select the paragraph. judging from the effect, the `u` key is correctly translated to `i` for processing, whereas the next `r` key isn't and I really have to type in a plain `p` key for vim to receive a functional sequence. this is pretty inconsistent and confusing and I have to remember the key after `v` is subject to my mappings, and the next one isn't.

what makes to two mapped keys behave differently? as far as I can tell, they should all be available under nvo modes. thanks.

**Comment by sosmo** [comment]
Your maps map the "r" just in normal/visual/operator mode but not when it comes after "u". You'd need to map "ur" specifically in visual/operator mode to achieve the effect you want. Maybe instead try `:h langmap`, like `:set langmap=ui,rp`?
https://vim.fandom.com/wiki/Using_Vim_with_the_Dvorak_keyboard_layout
https://vi.stackexchange.com/questions/15350/how-can-i-use-langmap-and-noremap-together

**Comment by ri-aje** [comment]
> Your maps map the "r" just in normal/visual/operator mode but not when it comes after "u". You'd need to map "ur" specifically in visual/operator mode to achieve the effect you want. Maybe instead try `:h langmap`, like `:set langmap=ui,rp`?
> https://vim.fandom.com/wiki/Using_Vim_with_the_Dvorak_keyboard_layout
> https://vi.stackexchange.com/questions/15350/how-can-i-use-langmap-and-noremap-together

thanks. so what's mode vim was in after typing 'vu' in my example? I know my mappings cover nvo modes including select mode, which is pretty broad as far as I can tell. other than those, there are insert mode, command mode and terminal mode, and none of them seems a reasonable state after 'vu'. does vim have an unknown mode that is not subject to any user mappings?

**Comment by chrisbra** [comment]
Vim is not in a real mode. I believe mappings are just disabled for when the text object keys are retrieved. It seems you actually want langmode mappings, so please use those then.

**Comment by ri-aje** [comment]
> Vim is not in a real mode. I believe mappings are just disabled for when the text object keys are retrieved. 

@chrisbra this aligns with my observation. can you point me to vim docs talking about this specific mapping disable behavior? thanks.

> It seems you actually want langmode mappings, so please use those then.

I will explore. just to be clear though, I am ok with `vup` since the mnemonic does make sense and  assist memory, but I didn't expect there is a hidden boundary between `u` and `p` in terms of user mapping availability, and before I understand it, it makes making sense of vim much harder.
