### ISSUE TITLE
"Download runtime" page points to old runtime version

### ISSUE THREAD

**Issue by bam80** [vim/vim#5312]
Official [Download runtime files](https://www.vim.org/runtime.php) page contains instructions to get "the latest version of the runtime files".
Well, it seems not true any more: the runtime files on FTP are [outdated](https://ftp.nluug.nl/pub/vim/runtime/).
So we probably need update the instructions or/and the FTP.

> Alternate method: rsync
If you have the "rsync" command, you can use it to update your runtime files. This example works for Unix. Note that it deletes files that are not on the ftp site. If you want to be careful, leave out the --delete argument. Or be prepared to reinstall Vim.

        :cd $VIMRUNTIME
        :!rsync -avzcP --delete --exclude="dos" --exclude="spell" ftp.nluug.nl::Vim/runtime/ .

**Comment by chrisbra** [comment]
you can always download the runtime files from this repository.

**Comment by bam80** [comment]
Of course I can, and I did it eventually (however, downloading just `runtime` dir from Github repo was not so trivial).
I filed this issue because it's not obvious at all the official Download page points to outdated version.
I realized it occasionally, after installing and looking into the files.  
If FTP is not maintained, maybe just remove it's references from the page?
I think it worth keeping official pages in actual state.

**Comment by bam80** [comment]
> downloading just runtime dir from Github repo was not so trivial

I ended up with this command, maybe we could place it on the "Download runtime" page instead:
```
wget https://github.com/vim/vim/archive/master.tar.gz -O- |tar zfx - vim-master/runtime/ --strip-components=1

**Comment by brammool** [comment]
> > downloading just runtime dir from Github repo was not so trivial
> 
> I ended up with this command, maybe we could place it on the "Download runtime" page instead:
> ```
> wget https://github.com/vim/vim/archive/master.tar.gz -O- |tar zfx - vim-master/runtime/ --strip-components=1

That page is totally outdated.  Let me at least remove most of the
content.

I'll add some hints, but it can use some more updates.  E.g., it should
be possible to use "rsync" to update files from a github repo to the
right place, but I don't have time to figure out the arguments.

-- 
Wizards had always known that the act of observation changed the thing that
was observed, and sometimes forgot that it also changed the observer too.
			Terry Pratchett  -  Interesting times

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
seems to be fixed, closing.

**Comment by bam80** [comment]
Thanks!
