### ISSUE TITLE
:tabnew will auto enter insert mode in some circumstances

### ISSUE THREAD

**Issue by epheien** [vim/vim#5319]
**Describe the bug**
:tabnew will auto enter insert mode in some circumstances

**To Reproduce**
Detailed steps to reproduce the behavior:
```
vim --clean
:terminal<CR>
:<C-\><C-n>
:autocmd WinEnter <buffer> startinsert<CR>
:tabnew<CR>
```

**Expected behavior**
in normal mode

**Screenshots**
n/a

**Environment (please complete the following information):**
 - Vim version: 8.1.1517
 - OS: macOS 10.14.4
 - Terminal: iTerm2

**Additional context**
https://github.com/neovim/neovim/issues/11518#event-2857196204

**Comment by brammool** [comment]
This is unrelated to using a terminal window, a normal window does the same.
It's because the window is split first, ":new" also does this.
Since it's been like this for a long time I hesitate to change this.  Also because it's documented:
"Note: For split and tabpage commands the
WinEnter event is triggered after the split
or tab command but before the file is loaded."
I suggest you use a BufEnter autocommand

**Comment by epheien** [comment]
> This is unrelated to using a terminal window, a normal window does the same.
> It's because the window is split first, ":new" also does this.
> Since it's been like this for a long time I hesitate to change this. Also because it's documented:
> "Note: For split and tabpage commands the
> WinEnter event is triggered after the split
> or tab command but before the file is loaded."
> I suggest you use a BufEnter autocommand

But my WinEnter event limit by `<buffer>`
I make my terminal windows always enter insert mode, and found this issue.

```
vim --clean
:sp<CR>
:autocmd WinEnter <buffer> startinsert<CR>
:autocmd WinLeave <buffer> stopinsert<CR>
:tabnew<CR>
```

Same problem.
I think this issue need to be fixed.

**Comment by epheien** [comment]
> > This is unrelated to using a terminal window, a normal window does the same.
> > It's because the window is split first, ":new" also does this.
> > Since it's been like this for a long time I hesitate to change this. Also because it's documented:
> > "Note: For split and tabpage commands the
> > WinEnter event is triggered after the split
> > or tab command but before the file is loaded."
> > I suggest you use a BufEnter autocommand
> 
> But my WinEnter event limit by `<buffer>`
> I make my terminal windows always enter insert mode, and found this issue.
> 
> ```
> vim --clean
> :sp<CR>
> :autocmd WinEnter <buffer> startinsert<CR>
> :autocmd WinLeave <buffer> stopinsert<CR>
> :tabnew<CR>
> ```
> 
> Same problem.
> I think this issue need to be fixed.

If I replace `:autocmd WinLeave <buffer> stopinsert<CR>` to `:autocmd BufLeave <buffer> stopinsert<CR>`
no problem
