### ISSUE TITLE
Error from function s:GotoProgram() in termdebug.vim

### ISSUE THREAD

**Issue by tuarba** [vim/vim#5333]
**Describe the bug**
After termdebug is started, executing 'Program' command leads to an error:

    Error detected while processing function <SNR>75_GotoProgram:
    line    6:
    E465: :winsize requires two number arguments

It looks like in termdebug.vim, line 629 in function s:GotoProgram() should be changed from:

    win_gotoid(s:ptywin)

to:

    call win_gotoid(s:ptywin)

Doing this will fix the error

**Comment by brammool** [comment]
Good catch, thanks for the fix.
