### ISSUE TITLE
BufAdd (and other buffer events) not fired at startup

### ISSUE THREAD

**Issue by myitcv** [vim/vim#5336]
**Describe the bug**

The `BufAdd` autocommand is not fired when Vim starts.  

**To Reproduce**

Create the following file, `repro.vim`:

```vim
function s:EchoEvent(msg)
  redir >> /tmp/listener.log | echo a:msg | redir END
endfunction

au BufAdd * call s:EchoEvent("BufAdd ".expand("<afile>"))
```

Then:

```
touch /tmp/listener.log
```

In one terminal:

```
tail -f /tmp/listener.log
```

In the other:

```
vi -u repro.vim a b
```

Notice that there is nothing logged in the `tail` terminal.

Now in the Vim instance do:

```
:sp c
```

and notice the following is logged in the `tail` terminal:

```
BufAdd c
```

**Expected behavior**

`BufAdd` to be fired after creating a new buffer which is added to the buffer list, or adding a buffer to the buffer list, including at startup.

**Screenshots**

n/a

**Environment (please complete the following information):**
 - Vim version

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec  7 2019 20:00:23)
Included patches: 1-2408
Compiled by myitcv@myitcv
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_old_static
+arabic            +file_in_path      +mouse_urxvt       -tag_any_white
+autocmd           +find_in_path      +mouse_xterm       -tcl
+autochdir         +float             +multi_byte        +termguicolors
-autoservername    +folding           +multi_lang        +terminal
+balloon_eval      -footer            -mzscheme          +terminfo
+balloon_eval_term +fork()            -netbeans_intg     +termresponse
+browse            +gettext           +num64             +textobjects
++builtin_terms    -hangul_input      +packages          +textprop
+byte_offset       +iconv             +path_extra        +timers
+channel           +insert_expand     -perl              +title
+cindent           +job               +persistent_undo   +toolbar
+clientserver      +jumplist          +popupwin          +user_commands
+clipboard         +keymap            +postscript        +vartabs
+cmdline_compl     +lambda            +printer           +vertsplit
+cmdline_hist      +langmap           +profile           +virtualedit
+cmdline_info      +libcall           +python/dyn        +visual
+comments          +linebreak         +python3/dyn       +visualextra
+conceal           +lispindent        +quickfix          +viminfo
+cryptv            +listcmds          +reltime           +vreplace
+cscope            +localmap          +rightleft         +wildignore
+cursorbind        +lua               -ruby              +wildmenu
+cursorshape       +menu              +scrollbind        +windows
+dialog_con_gui    +mksession         +signs             +writebackup
+diff              +modify_fname      +smartindent       +X11
+digraphs          +mouse             -sound             -xfontset
+dnd               +mouseshape        +spell             +xim
-ebcdic            +mouse_dec         +startuptime       +xpm
+emacs_tags        -mouse_gpm         +statusline        +xsmp_interact
+eval              -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary        
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/home/myitcv/usr/vim/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16   -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl    -ldl  -L/usr/lib/x86_64-linux-gnu -lluajit-5.1         
```

- OS: Ubuntu 19.10
- Terminal: XTerm(348)

**Additional context**

**Comment by brammool** [comment]
Paul Jolly wrote:

> **Describe the bug**
> 
> The `BufAdd` autocommand is not fired when Vim starts.  
> 
> **To Reproduce**
> 
> Create the following file, `repro.vim`:
> 
> ```vim
> function s:EchoEvent(msg)
>   redir >> /tmp/listener.log | echo a:msg | redir END
> endfunction
> 
> au BufAdd * call s:EchoEvent("BufAdd ".expand("<afile>"))
> ```
> 
> Then:
> 
> ```
> touch /tmp/listener.log
> ```
> 
> In one terminal:
> 
> ```
> tail -f /tmp/listener.log
> ```
> 
> In the other:
> 
> ```
> vi -u repro.vim a b
> ```
> 
> Notice that there is nothing logged in the `tail` terminal.
> 
> Now in the Vim instance do:
> 
> ```
> :sp c
> ```
> 
> and notice the following is logged in the `tail` terminal:
> 
> ```
> BufAdd c
> ```
> 
> **Expected behavior**
> 
> `BufAdd` to be fired after creating a new buffer which is added to the buffer list, or adding a buffer to the buffer list, including at startup.
> 
> **Screenshots**

This is done intentionally.  Only BufEnter autocommands are triggered
for the initially loaded buffers.  Vim needs to get into an initialized
state before BufAdd events can be handled properly.

You can use the VimEnter event to do any work for buffers created
earlier.

-- 
hundred-and-one symptoms of being an internet addict:
239. You think "surfing" is something you do on dry land.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by myitcv** [comment]
> This is done intentionally

Thanks.

> You can use the VimEnter event to do any work for buffers created
earlier.

Is this documented somewhere and I just missed it?

**Comment by brammool** [comment]
Paul Jolly wrote:

> > This is done intentionally
> 
> Thanks.
> 
> > You can use the VimEnter event to do any work for buffers created
> earlier.
> 
> Is this documented somewhere and I just missed it?

I thought it was, but now I can't find it.  I will add a couple of
remarks.

-- 
hundred-and-one symptoms of being an internet addict:
251. You've never seen your closest friends who usually live WAY too far away.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
