### ISSUE TITLE
getchar() can not detect cmd-v on MacOS

### ISSUE THREAD

**Issue by Yggdroot** [vim/vim#5349]
**Describe the bug**
getchar() can not detect cmd-v on MacOS

**To Reproduce**
1. vim
2. `:echom getchar() == "\<D-v>"`

**Expected behavior**
outputs 1

**Comment by k-takata** [comment]
Only on console or also on GUI?

**Comment by Yggdroot** [comment]
> Only on console or also on GUI?

Both.

**Comment by eirnym** [comment]
FYI: Terminal.app by Apple doesn't send cmd key combinations to any app you run inside.

**Comment by eirnym** [comment]
@Yggdroot Can you put an example of what do you want to achieve?

**Comment by eirnym** [comment]
Also FYI: GUI menu key bindings are processed on macOS level so you have to unbind a key combination from menu and then you can use it.

**Comment by Yggdroot** [comment]
> @Yggdroot Can you put an example of what do you want to achieve?

I wrote a fuzzy finder plugin for vim, and encounter this issue: https://github.com/Yggdroot/LeaderF/issues/428

**Comment by eirnym** [comment]
In MacVim you can unmap `Cmd-V` from menu and then you can use it in GUI. iTerm2 and other terminals _could_ send this code if you configure them this way.

**Comment by ychin** [comment]
This should probably be resolved in https://github.com/macvim-dev/macvim/issues/1066 since it's a specific MacVim issue. I don't think `<D-v>` is a thing in vanilla Vim.

**Comment by chrisbra** [comment]
closing then.
