### ISSUE TITLE
[TEST] Test_edit_long_file_name may fail on some terminals

### ISSUE THREAD

**Issue by vp1981** [vim/vim#5358]
**Describe the bug**
The commit 0efd1bdcf4891f9ef2537e4c3d50a379186dca5f introduced test `Test_edit_long_file_name` that may fail due to FS limitation. I faced it when run tests after vim build in tmux running inside kitty open on full screen. I had to recompile vim and run tests in smaller window but still the test is fishy.

**To Reproduce**
Run kitty terminal or other one, open it on full screen, ensure that COLUMNS > 255 (FS limit), build vim and run tests.

**Expected behavior**
All tests should be passed

**Environment (please complete the following information):**
 - vim: 8.2.0002
 - Archlinux x86_64
 - kitty, tmux, inside kitty+tmux:
   COLUMNS: 205, test runs fine,
   COLUMNS: 274, test fails

**Comment by chrisbra** [comment]
255 should be safe right? So this patch should do it:

```patch
diff --git a/src/testdir/test_display.vim b/src/testdir/test_display.vim
index 4ef361e05..24b114db3 100644
--- a/src/testdir/test_display.vim
+++ b/src/testdir/test_display.vim
@@ -186,7 +186,7 @@ endfunc
 func Test_edit_long_file_name()
   CheckScreendump

-  let longName = 'x'->repeat(&columns)
+  let longName = 'x'->repeat(min([&columns,255]))
   call writefile([], longName)
   let buf = RunVimInTerminal('-N -u NONE ' .. longName, #{rows: 8})
```
