### ISSUE TITLE
:move command closes all folds

### ISSUE THREAD

**Issue by hallzy** [vim/vim#536]
I have 2 versions of vim. Both were installed on Ubuntu with `sudo apt-get install vim-gnome` but from different repositories. Both the exact same configuration, but whenever I do a :m command in one of them, it closes all open folds.

I ran `vim -N -u NONE` to open vim with no configs or plugins.

Then in vim I set `set foldmethod=marker`, to start using folds with a marker (without this setting the odd behaviour does not occur).

Now if I am on any line and do a command with `:m` it will close that fold.

Example:

``` vim
/*{{{*/
test
test
test
test
/*}}}*/

Hello
```

Here we have 4 lines with "test" in a fold, and a stray "Hello" that is not in the fold.

With my cursor on the line of Hello if I do a `:m` command such as `:m 6` the resulting document looks like this (note that I gave the example of `:m 6`, but every single combination of `:m` commands that I have tried yield the same result):

``` vim
+--  6 lines: ------------------------------------------------------------------------------------------
Hello
```

The movement is correct, but now the fold is closed, which is not what I would expect.

This occurs also when the line you are moving is inside a fold (All folds close).

This is the output of `vim --version` that behaves in this strange way for me:

``` bash
  $ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 28 2015 02:02:33)
Included patches: 1-942
Modified by pi-rho
Compiled by buildd@lcy01-36
Huge version with GTK2-GNOME GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
+balloon_eval    +float           +mouse_urxvt     -tag_any_white
+browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
+clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      +toolbar
+cmdline_compl   +insert_expand   +perl/dyn        +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python/dyn      +viminfo
+cscope          +lispindent      +python3/dyn     +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  +lua/dyn         +rightleft       +windows
+diff            +menu            +ruby/dyn        +writebackup
+digraphs        +mksession       +scrollbind      +X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      -sniff           +xsmp_interact
+eval            +mouse_dec       +startuptime     +xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    +xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/i386-linux-gnu/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/i386-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/harfbuzz   -pthread -DORBIT2=1 -D_REENTRANT -I/usr/include/libgnomeui-2.0 -I/usr/include/libart-2.0 -I/usr/include/gconf/2 -I/usr/include/gnome-keyring-1 -I/usr/include/libgnome-2.0 -I/usr/include/libbonoboui-2.0 -I/usr/include/libgnomecanvas-2.0 -I/usr/include/gtk-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gnome-vfs-2.0 -I/usr/lib/i386-linux-gnu/gnome-vfs-2.0/include -I/usr/include/dbus-1.0 -I/usr/lib/i386-linux-gnu/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/i386-linux-gnu/glib-2.0/include -I/usr/include/orbit-2.0 -I/usr/include/libbonobo-2.0 -I/usr/include/bonobo-activation-2.0 -I/usr/include/libxml2 -I/usr/include/pango-1.0 -I/usr/include/gail-1.0 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/atk-1.0 -I/usr/lib/i386-linux-gnu/gtk-2.0/include -I/usr/include/cairo -I/usr/include/gio-unix-2.0/ -I/usr/include/pixman-1 -I/usr/include/libpng12     -Wall -Wextra -g -O2 -fPIE -Wformat -Werror=format-security -fstack-protector-all -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -L/build/buildd/ruby1.9.1-1.9.3.484/debian/lib -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,-z,nodlopen -Wl,-z,nodump -Wl,-z,noexecstack -Wl,-z,noexecheap -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfontconfig -lgobject-2.0 -lglib-2.0 -lfreetype     -lgnomeui-2 -lSM -lICE -lbonoboui-2 -lgnomevfs-2 -lgnomecanvas-2 -lgnome-2 -lpopt -lbonobo-2 -lbonobo-activation -lORBit-2 -lart_lgpl_2 -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfontconfig -lfreetype -lgconf-2 -lgthread-2.0 -lgmodule-2.0 -lgobject-2.0 -lglib-2.0   -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux   -lacl -lattr -lgpm -ldl   -Wl,-E  -fstack-protector -L/usr/local/lib  -L/usr/lib/perl/5.18/CORE -lperl -ldl -lm -lpthread -lcrypt
```

And this is the version I have that behaves as I expect (The folds do not close themselves):

``` bash
  $ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:40:46)
Included patches: 1-52
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@
Huge version with GTK2-GNOME GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
+balloon_eval    +float           +mouse_urxvt     -tag_any_white
+browse          +folding         +mouse_xterm     +tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
+clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      +toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  +lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      +X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      -sniff           +xsmp_interact
+eval            +mouse_dec       +startuptime     +xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    +xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/i386-linux-gnu/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/i386-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/harfbuzz   -pthread -DORBIT2=1 -D_REENTRANT -I/usr/include/libgnomeui-2.0 -I/usr/include/libart-2.0 -I/usr/include/gconf/2 -I/usr/include/gnome-keyring-1 -I/usr/include/libgnome-2.0 -I/usr/include/libbonoboui-2.0 -I/usr/include/libgnomecanvas-2.0 -I/usr/include/gtk-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gnome-vfs-2.0 -I/usr/lib/i386-linux-gnu/gnome-vfs-2.0/include -I/usr/include/dbus-1.0 -I/usr/lib/i386-linux-gnu/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/i386-linux-gnu/glib-2.0/include -I/usr/include/orbit-2.0 -I/usr/include/libbonobo-2.0 -I/usr/include/bonobo-activation-2.0 -I/usr/include/libxml2 -I/usr/include/pango-1.0 -I/usr/include/gail-1.0 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/atk-1.0 -I/usr/lib/i386-linux-gnu/gtk-2.0/include -I/usr/include/cairo -I/usr/include/gio-unix-2.0/ -I/usr/include/pixman-1 -I/usr/include/libpng12     -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1     -I/usr/include/tcl8.6  -D_REENTRANT=1  -D_THREAD_SAFE=1  -D_LARGEFILE64_SOURCE=1
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfontconfig -lgobject-2.0 -lglib-2.0 -lfreetype     -lgnomeui-2 -lSM -lICE -lbonoboui-2 -lgnomevfs-2 -lgnomecanvas-2 -lgnome-2 -lpopt -lbonobo-2 -lbonobo-activation -lORBit-2 -lart_lgpl_2 -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfontconfig -lfreetype -lgconf-2 -lgthread-2.0 -lgmodule-2.0 -lgobject-2.0 -lglib-2.0   -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector -L/usr/local/lib  -L/usr/lib/perl/5.18/CORE -lperl -ldl -lm -lpthread -lcrypt -L/usr/lib/python2.7/config-i386-linux-gnu -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions  -L/usr/lib/i386-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-1.9.1 -lpthread -lrt -ldl -lcrypt -lm  -L/usr/lib
```

**Comment by vim-ml** [comment]
On Tue, Dec 22, 2015 at 12:19 AM, Steven Hall vim-dev-github@256bit.org wrote:

> I have 2 versions of vim. Both the exact same configuration, but whenever I
> do a :m command in one of them, it closes all open folds.
> 
> I ran vim -N -u NONE to open vim with no configs or plugins.
> 
> Then in vim I set set foldmethod=marker, to start using folds with a marker
> (without this setting the odd behaviour does not occur).
> 
> Now if I am on any line and do a command with :m it will close that fold.
> 
> Example:
> 
> /_{{{_/
> test
> test
> test
> test
> /_}}}_/
> 
> Hello
> 
> Here we have 4 lines with "test" in a fold, and a stray "Hello" that is not
> in the fold.
> 
> With my cursor on the line of Hello if I do a :m command such as :m 6 the
> resulting document looks like this (note that I gave the example of :m 6,
> but every single combination of :m commands that I have tried yield the same
> result):
> 
> ## +--  6 lines:
> 
> Hello
> 
> The movement is correct, but now the fold is closed, which is not what I
> would expect.
> 
> This occurs also when the line you are moving is inside a fold (All folds
> close).
> 
> This is the output of vim --version that behaves in this strange way for me:
> 
>   $ vim --version
> VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 28 2015 02:02:33)
> Included patches: 1-942
> Modified by pi-rho
> Compiled by buildd@lcy01-36
> Huge version with GTK2-GNOME GUI.  Features included (+) or not (-):
> […]
> 
> And this is the version I have that behaves as I expect (The folds do not
> close themselves):
> 
>   $ vim --version
> VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:40:46)
> Included patches: 1-52
> Modified by pkg-vim-maintainers@lists.alioth.debian.org
> Compiled by buildd@
> Huge version with GTK2-GNOME GUI.  Features included (+) or not (-):
> […]

Between 7.4.52 and 7.4.942, that's a wide range! I tried searching the
patch descriptions at http://ftp.vim.org/pub/vim/patches/7.4/ for the
word "fold" but the only "interesting" thing I found was patch
7.4.700, which would seem to repair what you found broken.

Then I tried to reproduce it in my Huge gvim 7.4.979 with GTK2/Gnome2
GUI for linux-x86_64, where the only "local changes" are in feature.h
to set +xterm_save -tag_old_static. First I tried checking the fold
option values and got
  foldmethod=manual
  foldlevel=0
  foldmarker={{{,}}}
  foldenable
  foldclose=

Setting foldmethod=marker _immediately_ closes the fold, which is what
I would expect with fdl=0. So I reopened the fold by clicking right on
the "+" character at its far left, moved the cursor back to "Hello"
and moved that line to immediately below the fold by ":m 6". The fold
indeed closes, which is in agreement with 'foldlevel'. So I set
'foldlevel' to 1 (which opened it), added an empty line above the
"Hello", then repeated the move.

This time the move didn't close the fold.

3rd experiment: Add two empty lines before Hello (e.g. by ":m $"), set
fdl=0 (e.g. by zM), reopen only this fold (by right-arrow on its +
token), bring back the cursor on Hello and move it, but not directly
below the fold (by :m 7)

Here too, the move closes the fold.

IOW, in "modern" Vim versions, :move reapplies 'foldlevel'. This may
be surprising to some, but I think it is understandable. Bram, what do
you think? Bug or feature?

Best regards,
Tony.

**Comment by vim-ml** [comment]
P.S. Switching two lines by ddp doesn't close the fold; OTOH the
do-nothing move ":m ." does.

Best regards,
Tony.

**Comment by hallzy** [comment]
Ya, sorry about the huge range, those are the two I had... It happened by accident, because the oldest one is the current version in the ubuntu repo, but I recently added another repo to install the latest version of tmux, and that repo happened to have the newer version of vim.

I kind of liked using the :m commands and have my folds stay the way they are (ie. If i had them open, they would stay open, and if they were closed, they would stay closed).

I have these mappings in my vimrc, which I think is fairly common which move lines up or down, or groups of lines up or down:

``` vim
nnoremap J :m .+1<cr>==
nnoremap K :m .-2<CR>==
vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv
```

(I do still use the defaults for J and K, I just mapped those elsewhere)

These mappings become very difficult to use when folds close on the line I am moving.

If this behaviour is going to stay, is there some fold setting (or any setting at all) that would be easy to do in order to replicate the behaviour that I see in my older version of vim?

If not, I think I can make something work with `ddkP==` etc anyways.

Thanks for the quick reply :)

**Comment by hallzy** [comment]
I have some working mappings that I would like to share here in case anyone comes searching for this same thing. I am still interested in knowing if this behaviour will be changed, or if it will stay this way just for the sake of knowing, but at least I have a workaround to make these mappings work the way I prefer.

here they are... just add to .vimrc

``` vim
function! MoveLineUp()
  let currentLine = line(".")
  let lastLine = line("$")

  if currentLine == lastLine
    " Do this on the bottom of the file otherwise the line will go up 2 lines
    " instead of one
    exec "normal! ddP=="
  elseif currentLine == 1
    " Don't go off the top of the page
  else
    " For anywhere else in the file, do this
    exec "normal! ddkP=="
  endif
endfun

function! MoveSelectionUp()
  " Selects the top part of the visual selection and Save that line number
  exec "normal! '<"
  let currentLineTop = line(".")

  " Selects the block, with the cursor on the bottom of the block and Save that
  " line number
  exec "normal! V'>"
  let currentLineBottom = line(".")

  let lastLine = line("$")

  if currentLineBottom == lastLine
    " Do this on the bottom of the file otherwise the line will go up 2 lines
    exec "normal! gvdP`[V`]=gv"
  elseif currentLineTop == 1
    " Don't go off the top of the page
  else
    exec "normal! gvdkP`[V`]=gv"
  endif
endfun


" With a J move the current line down, with K move the current line up.
nnoremap K :call MoveLineUp()<cr>
nnoremap J ddp==

" With a J move the current Selected lines down, with K move the current selected lines up.
vnoremap K <esc>:call MoveSelectionUp()<cr>
vnoremap J <esc>'<V'>dp`[V`]=gv
```

**Comment by chrisbra** [comment]
as has been mentioned, this is a side effect of patch 7.4.700 that fixes a bug, that folds get invalid after a `:m` command. The workaround is to `:set foldmethod=manual` I think.

**Comment by hallzy** [comment]
I like to have my folds persistent though (I realize now I never mentioned this), and my understanding is that `:set foldmethod=manual` does not do this (maybe my understanding is wrong, or there is something else I can do on top of this that makes my statement untrue?), and that you have to manually add the folds every time you open a file.

I find that it makes information easier to find sometimes if they are grouped, and I also find that it is a nice way to study for classes :) (ie. Having questions, and then hiding the answers in a fold)

**Comment by chrisbra** [comment]
Does it not work if before `:m` you do `:set fdm=manual` and reset it afterwards?

**Comment by hallzy** [comment]
Oh ya! Wow. Now I feel dumb. Thanks, that works.

for completeness and anyone looking at this, these are the mappings that work, in addition to the longer mappings I had earlier in this thread:

``` vim
nnoremap J :set fdm=manual<cr>:m .+1<CR>==:set fdm=marker<cr>
nnoremap K :set fdm=manual<cr>:m .-2<CR>==:set fdm=marker<cr>

vnoremap J <esc>:set fdm=manual<cr>'<V'>:m '>+1<CR>gv=:set fdm=marker<cr>gv
 vnoremap K <esc>:set fdm=manual<cr>'<V'>:m '<-2<CR>gv=:set fdm=marker<cr>gv
```
