### ISSUE TITLE
startuptime：it it took too much time to do "setup clipboard"

### ISSUE THREAD

**Issue by irreallich** [vim/vim#5372]
The following is the log of startuptime, it took too much time to do "152 1205.805  1060.095: setup clipboard"

139 144.247  000.614  000.614: sourcing /home/hjwang/.local/share/vim/vim82/plugin/netrwPlugin.vim
140 144.327  000.041  000.041: sourcing /home/hjwang/.local/share/vim/vim82/plugin/rrhelper.vim
141 144.383  000.031  000.031: sourcing /home/hjwang/.local/share/vim/vim82/plugin/spellfile.vim
142 144.599  000.193  000.193: sourcing /home/hjwang/.local/share/vim/vim82/plugin/tarPlugin.vim
143 144.741  000.100  000.100: sourcing /home/hjwang/.local/share/vim/vim82/plugin/tohtml.vim
144 144.984  000.218  000.218: sourcing /home/hjwang/.local/share/vim/vim82/plugin/vimballPlugin.vim
145 145.278  000.212  000.212: sourcing /home/hjwang/.local/share/vim/vim82/plugin/zipPlugin.vim
146 145.299  001.666: loading plugins
147 145.353  000.054: loading packages
148 145.468  000.017  000.017: sourcing /home/hjwang/work/config/vimrc.d/plugged_vim802_linux/indentLine/after/plugin/indentLine.vim
149 145.472  000.102: loading after plugins
150 145.491  000.019: inits 3
151 145.710  000.219: reading viminfo
152 1205.805  1060.095: setup clipboard
153 1205.830  000.025: setting raw mode
154 1205.855  000.025: start termcap
155 1205.938  000.083: clearing screen
156 1209.530  000.845  000.845: sourcing /home/hjwang/work/config/vimrc.d/plugged_vim802_linux/vim-airline/autoload/airline/extensions.vim
157 1209.913  000.147  000.147: sourcing /home/hjwang/work/config/vimrc.d/plugged_vim802_linux/vim-airline/autoload/airline/extensions/quickfix.vim
158 1210.516  000.440  000.440: sourcing /home/hjwang/work/config/vimrc.d/plugged_vim802_linux/vim-airline/autoload/airline.vim
159 1210.899  000.096  000.096: sourcing /home/hjwang/work/config/vimrc.d/plugged_vim802_linux/vim-airline/autoload/airline/extensions/netrw.vim
160 1211.602  000.201  000.201: sourcing /home/hjwang/work/config/vimrc.d/plugged_vim802_linux/vim-airline/autoload/airline/section.vim
161 1212.510  000.510  000.510: sourcing /home/hjwang/work/config/vimrc.d/plugged_vim802_linux/vim-airline/autoload/airline/highlighter.vim
162 1212.961  001.834  001.123: sourcing /home/hjwang/work/config/vimrc.d/plugged_vim802_linux/vim-airline/autoload/airline/extensions/term.vim
163 1213.257  000.041  000.041: sourcing /home/hjwang/work/config/vimrc.d/plugged_vim802_linux/vim-airline/autoload/airline/extensions/bookmark.vim
164 1213.653  000.149  000.149: sourcing /home/hjwang/work/config/vimrc.d/plugged_vim802_linux/vim-airline/autoload/airline/extensions/whitespace.vim

the vim version:
:version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 18 2019 13:04:29)
Included patches: 1-14
Compiled by hjwang@hjwang-Latitude-E5540
Huge version with X11-Athena GUI.  Features included (+) or not (-):
+acl               +clipboard         -dnd               +gettext           +localmap          +mouse_urxvt       +printer           +startuptime       +textprop          +wildmenu
+arabic            +cmdline_compl     -ebcdic            -hangul_input      -lua               +mouse_xterm       +profile           +statusline        +timers            +windows
+autocmd           +cmdline_hist      +emacs_tags        +iconv             +menu              +multi_byte        -python            -sun_workshop      +title             +writebackup
+autochdir         +cmdline_info      +eval              +insert_expand     +mksession         +multi_lang        +python3           +syntax            +toolbar           +X11
-autoservername    +comments          +ex_extra          +job               +modify_fname      -mzscheme          +quickfix          +tag_binary        +user_commands     +xfontset
+balloon_eval      +conceal           +extra_search      +jumplist          +mouse             +netbeans_intg     +reltime           -tag_old_static    +vartabs           +xim
+balloon_eval_term +cryptv            -farsi             +keymap            +mouseshape        +num64             +rightleft         -tag_any_white     +vertsplit         +xpm
+browse            +cscope            +file_in_path      +lambda            +mouse_dec         +packages          +ruby              -tcl               +virtualedit       +xsmp_interact
++builtin_terms    +cursorbind        +find_in_path      +langmap           -mouse_gpm         +path_extra        +scrollbind        +termguicolors     +visual            +xterm_clipboard
+byte_offset       +cursorshape       +float             +libcall           -mouse_jsbterm     -perl              +signs             +terminal          +visualextra       -xterm_save
+channel           +dialog_con_gui    +folding           +linebreak         +mouse_netterm     +persistent_undo   +smartindent       +terminfo          +viminfo
+cindent           +diff              -footer            +lispindent        +mouse_sgr         +popupwin          +sound             +termresponse      +vreplace
+clientserver      +digraphs          +fork()            +listcmds          -mouse_sysmouse    +postscript        +spell             +textobjects       +wildignore
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/home/hjwang/.local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_ATHENA     -g -O2 -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic  -L/usr/local/lib -Wl,--as-needed -o vim -lXaw -lXmu -lXext -lXt -lSM -lI
CE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE -ldl  -lm -ltinfo -lnsl  -lselinux  -lcanberra -ldl     -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -lpthread -ldl -lutil -lm  -lru
by-2.5 -lpthread -lgmp -ldl -lcrypt -lm

**Comment by dpelle** [comment]
Is your `DISPLAY` environment set correctly?
For diagnostic purpose, try with `-X` option i.e. `vim -X --startuptime startup.log`

**Comment by irreallich** [comment]
@dpelle 
Thanks for your help.  My display is   set display?   then   display=lastline . 
I try to start vim with -x , then I need to input crypt key, so the startuptime is not correct.
but the vim don't do "setup clipboard" now, I don't konw the reason.

**Comment by k-takata** [comment]
Not 'display' option, `DISPLAY` environment variable.
Not `-x`, use `-X`.

**Comment by irreallich** [comment]
@k-takata , thanks you too.
after :echo $DISPLAY ,  vim print 'localhost:10.0' or 'localhost:11.0'

Now I couldn't find the log about setup clipboard, it seems the issue is missing , it seems very strange.

**Comment by chrisbra** [comment]
so $DISPLAY is set, which is good. Perhaps Athena is slow for that? Have you tried a different gui? Is there anything special with your setup? (Wayland, or perhaps you are using an usual X-Server, or using remote capabilities)?

**Comment by k-takata** [comment]
A comment is not forwarded here.
https://groups.google.com/d/msg/vim_dev/LsZMwLMZbZc/4ykbdEW0CAAJ

**Comment by irreallich** [comment]
@chrisbra @k-takata @dpelle 
actually ，I changed nothing, the issue just gone, I don't konw why,  I am working on the terminal vim with MobaXterm, sometimes i will open the xserver.
anyway , thanks for your help . I will close this case.

**Comment by k-takata** [comment]
Closing then.
