### ISSUE TITLE
function() does not accept a number as argument

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#5373]
**Describe the bug**

Vim can represent a numbered function via the notation `function('123')`.
But I can't use the same notation when I need `"function('123')"` to be evaluated; it raises `E129` and `E475`.

**To Reproduce**

Write this in `/tmp/vim.vim` and source the file:

    let adict = {'data': [0, 1, 2]}
    fu adict.size()
        return len(self.data)
    endfu
    echo adict

The last command outputs:

    {'data': [0, 1, 2], 'size': function('123')}
                                ^^^^^^^^^^^^^^^

Now, execute this Ex command:

    echo eval(string(adict))

The errors `E129` and `E475` are raised:

    E129: Function name required
    E475: Invalid argument: 123

And the dictionary is not echo'ed with its original value:

    {'data': [0, 1, 2], 'size': 0}

In the output, the value of the `size` key is `0`, while it was `function('123')` in `adict`.

**Expected behavior**

No error is raised, and the command outputs the original dictionary `adict`.

**Environment**

 - Vim version:  8.2 Included patches: 1-7
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

It seems inconsistent:

   - You can *read* `function('123')` in some command output, but you can't *write* it in an evaluated expression.

     If I can read `function('123')`, I would expect I can write it too.

   - `:echo eval(string(adict))` works with most dictionaries; it only fails when the dictionary contains a numbered function.

     I would expect `:echo eval(string(adict))` to work all the time, not most of the time.

---

I'm using the [`vim-quickhl`](https://github.com/t9md/vim-quickhl/) plugin.
The latter runs a [`:windo` command](https://github.com/t9md/vim-quickhl/blob/ea4d43e3fd9a36cafc9a36b84021e10a31b70a35/autoload/quickhl.vim#L42) to install some match in all windows.

This breaks the layout of my windows; I want all unfocused windows to be squashed to 0 lines.
But when I use a command from the plugin, the height of the unfocused windows is reset to 1 line.

Here is a minimal example.

Run this shell command:

    git -C /tmp clone https://github.com/t9md/vim-quickhl

Then write this in `/tmp/vim.vim`:

    set rtp^=/tmp/vim-quickhl
    set wmh=0
    sp
    au VimEnter * call timer_start(0, {-> execute('wincmd _')})

Start Vim like this:

    vim -Nu /tmp/vim.vim

The unfocused bottom window should be squashed to 0 lines.
Now, call a function from the plugin:

    call quickhl#manual#this_whole_word('n')

The height of the bottom window has been reset to 1 line.

To fix this, I would need to replace `:windo` with `map()` + `win_execute()`, because the latter doesn't suffer from this undesirable side-effect.

That is, this block:

    let winnum = winnr()
    let pwinnum = winnr('#')
    noa windo call call(a:func, [], a:obj)
    if pwinnum != 0
        exe pwinnum..'wincmd w'
    endif
    exe winnum..'wincmd w'

should be replaced with this one:

    call map(range(1, winnr('$')),
        \ {_,v -> win_execute(win_getid(v),
        \ 'call call('..string(a:func)..', [], '..string(a:obj)..')')})

But it fails for the same reason as reported earlier.
`a:func` and `a:obj` contain dictionaries which themselves contain numbered functions.
Vim is ok with passing those dictionaries to `string()`; but Vim is not ok with giving back the dictionaries when evaluating the contents of the resulting strings.

For the moment, I've fixed the issue by passing the dictionaries to `call()` via temporary global variables, in order to avoid the evaluation step:

    let g:Quickhl_Funcref = a:func
    let g:quickhl_obj = a:obj
    call map(range(1, winnr('$')),
        \ {_,v -> win_execute(win_getid(v),
        \ 'call call(g:Quickhl_Funcref, [], g:quickhl_obj)')})
    unlet g:Quickhl_Funcref g:quickhl_obj

But it seems awkward.

**Comment by Houl** [comment]
Not all dictionaries have a string representation, also for other reasons.
Sounds like what you are asking for is a new function 
`win_call({id}, {func}, {args}[, {dict}])` where `{id}` is used like with `win_execute()` and `{func}, {args}, {dict}` are `call()`-like arguments.

**Comment by lacygoill** [comment]
Ok, if it's not a bug, I close the issue and maybe I'll open a feature request in the future.
In the meantime, I'll try to refactor the plugin to avoid numbered functions, for this reason [and others](https://github.com/LucHermitte/lh-vim-lib/blob/master/doc/OO.md#avoid-anonymous-functions).

**Comment by andymass** [comment]
What happens if you do 

```
call map(range(1, winnr('$')),
    \ {_,v -> win_execute(win_getid(v),
    \ 'call call(a:func, [], a:obj)')})
```

Or

```
let l:func = a:func
let l:obj = a:obj
call map(range(1, winnr('$')),
    \ {_,v -> win_execute(win_getid(v),
    \ 'call call(l:func, [], l:obj)')})
```

**Comment by lacygoill** [comment]
> What happens if you do
>
>     call map(range(1, winnr('$')),
>         \ {_,v -> win_execute(win_getid(v),
>         \ 'call call(a:func, [], a:obj)')})

That's what I tried at first, but it raises `E121` and `E116`:

    E121: Undefined variable: a:func
    E116: Invalid arguments for function call

I think that's because the `:call call(...)` command is not run in the context of the current function; so it can't access the variables in the `a:` scope.

I thought about asking for the `{command}` argument of `win_execute()` to support a lambda, because a lambda expression can access outer scope variables, so I could have fixed the bug by writing:

    call map(range(1, winnr('$')),
        \ {_,v -> win_execute(win_getid(v),
        \ {-> call(a:func, [], a:obj)})})

but then I realized that it would change the meaning of `win_execute()`. I think the latter is really meant to execute an Ex command, not evaluating an expression.

> Or
>
>     let l:func = a:func
>     let l:obj = a:obj
>     call map(range(1, winnr('$')),
>         \ {_,v -> win_execute(win_getid(v),
>         \ 'call call(l:func, [], l:obj)')})

It raises `E704`:

    E704: Funcref variable name must start with a capital: l:func

If I uppercase the name of the variable, I get – again – `E121` and `E116`:

    E121: Undefined variable: l:Func
    E116: Invalid arguments for function call

**Comment by Houl** [comment]
Maybe give the lambda a hint to capture the variables: `[win_execute(...), l:func, l:obj][0]`?

**Comment by andymass** [comment]
@Houl's suggestion is quite accurate.

```vim
func A()
    let l:foo = 'bar'
    " works
    call map(range(1,3), 'execute("echo l:foo v:val", "")')
    " doesn't work (l:foo not captured)
    call map(range(1,3), {_,v->execute('echo l:foo v', '')})
    " works (forces l:foo to be captured)
    call map(range(1,3), {_,v->[execute('echo l:foo v', ''), l:foo][0]})
    " works
    call map(range(1,3), function({foo,_,v->execute('echo foo v', '')}, [l:foo]))
endfunc
call A()
```

I also think in this case using a lambda is more complicated than using an old-school eval string because it introduces an additional function scope.  @lacygoill, you should be able to rewrite similar to

```
call map(range(1, winnr('$')),
         \ 'win_execute(win_getid(v:val), "eval a:func()")')
```
or
```
call map(range(1, winnr('$')),
         \ 'win_execute(win_getid(v:val), "eval a:obj.size()")')
```

**Comment by lacygoill** [comment]
Yes, you are right, all of these fix the bug where the height of a squashed window is reset to 1:

    call map(range(1, winnr('$')),
        \ "win_execute(win_getid(v:val), 'call call(a:func, [], a:obj)')")

    call map(range(1, winnr('$')),
        \ {_,v -> [win_execute(win_getid(v), 'call call(a:func, [], a:obj)'), a:func, a:obj]})

    call map(range(1, winnr('$')),
        \ function({func,obj,_,v -> win_execute(win_getid(v), 'call call(func, [], obj)')}, [a:func, a:obj]))

---

So the rules seem to be:

   - a lambda has access to the outer scope:

         fu Func()
             let l:var = 123
             echo map([1], {_,v -> v + l:var})
         endfu
         call Func()
         [124]

   - `execute()` inside a lambda which does not contain any reference to the outer scope does not have access to the latter:

         fu Func()
             let l:var = 123
             call map([1], {-> execute('echo l:var', '')})
         endfu
         call Func()
         E121: Undefined variable: l:var

   - `execute()` inside a lambda containing a reference to a variable in the outer scope has access to the latter:

         fu Func()
             let l:var = 123
             call map([1], {-> [execute('echo l:var', ''), l:var]})
         endfu
         call Func()
         123

   - `execute()` inside an eval string has access to the outer scope:

         fu Func()
             let l:var = 123
             call map([1], "execute('echo l:var', '')")
         endfu
         call Func()
         123

IIUC, it means that the command passed to `execute()` and `win_execute()` is run in its own separate context which can access the *immediate* outer scope (be it the lambda or `Func()`), but not further.
That is, even if `execute()` (E) can access the lambda scope (L), and the lambda can access the outer function scope (OF), that does not mean that `execute()` can access the outer function scope:

    ¬ ("E can access L" ∧ "L can access OF" ⇒ "E can access OF")

IOW, the mechanism which allows an expression to access variables outside its scope is not transitive.

So, this works:

    func A()
        let l:var = 123
        call map([1], 'execute("echo l:var", "")')
    endfunc
    call A()

because `echo l:var` has access to the `A()` scope (since it's inside an eval string).

This fails:

    func A()
        let l:var = 123
        call map([1], {-> execute('echo l:var', '')})
    endfunc
    call A()

because even though `echo l:var` has access to the lambda scope, and the latter has access to the `A()` scope, `echo l:var` does not have access to the `A()` scope (the access mechanism is not transitive).

And this works:

    func A()
        let l:var = 123
        call map([1], {-> [execute('echo l:var', ''), l:var][0]})
    endfunc
    call A()

because:

   - `l:var` has been moved in the lambda scope, since it was referred to inside the expression

         call map([1], {-> [execute('echo l:var', ''), l:var][0]})
                                                       ^^^^^

   - `execute()` has access to the lambda scope

Finally, this works:

    fu Func()
        let l:var = 123
        call map([1], function({var -> execute('echo var', '')}, [l:var]))
    endfu
    call Func()

because:

   - `l:var` has been bound to the lambda `{var -> execute('echo var', '')}`, creating a partial
   - `map()` evaluates the partial, like it would evaluate any kind of expression

---

In conclusion, if you need to access a variable in the outer scope from an `execute()` or `win_execute()` expression, you can:

   - use an eval string (not a lambda)
   - use a lambda and move the variable in its scope by referring to it inside the lambda but outside the `execute()`
   - use a partial

And I didn't know that:

   - the mechanism which allows an expression to access variables outside its scope is not transitive
   - you can move a variable from the outer scope to the lambda scope simply by referring to it inside the lambda (but outside `execute()`, probably because the latter is run in its own separate context)

---

Now I realize that a lambda is not always better than an eval string:

   - it introduces an additional function scope which can prevent the access to a variable in the outer scope
   - [it's slower](https://groups.google.com/d/msg/vim_dev/__gARXMigYE/a_aj5KgQCAAJ)

On my machine, this outputs a duration between 2.5s and 3s on average:

    vim -es -Nu <(cat <<'EOF'
    set vbs=1
    let time = reltime()
    call map(range(999999), {_,v-> v+1})
    echo matchstr(reltimestr(reltime(time)), '\v.*\..{,3}')..' seconds to run the command'
    qa!
    EOF
    )

While this outputs a duration of 0.5s on average:

    vim -es -Nu <(cat <<'EOF'
    set vbs=1
    let time = reltime()
    call map(range(999999), 'v:val + 1')
    echo matchstr(reltimestr(reltime(time)), '\v.*\..{,3}')..' seconds to run the command'
    qa!
    EOF
    )

It seems 5 to 6 times slower.

I have [a mapping](https://github.com/lacygoill/vim-vim/blob/4d872b016bdfa9b14c0097077fc6e0e70e30da39/after/ftplugin/vim.vim#L111) to refactor a `'... v:val ...'` into a `{_,v -> ... v ...}`.
The reverse refactoring is not as useless as I thought initially; I'll try to implement it (although I suspect dealing with escaping quotes will be tricky).

---

Anyway, I used your first – and imo simplest – solution (an eval string) to write and submit [a PR](https://github.com/t9md/vim-quickhl/pull/31) which fixes the bug. Thank you very much @Houl, @andymass.
