### ISSUE TITLE
Netrw throws Error detected while processing function netrw#BrowseX: while press x on folder.

### ISSUE THREAD

**Issue by amkarthik** [vim/vim#5379]
steps to reproduce:
![netrw-error](https://user-images.githubusercontent.com/12694917/71169541-32ff3b00-227f-11ea-8661-18f4bb1b08bf.gif)
My os is linux mint 18.
Happy to serve, if more informations needed.

**Comment by chrisbra** [comment]
what netrw version are you using? What Vim version?

**Comment by amkarthik** [comment]
@chrisbra 
My vim version:
IM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 15 2019 18:16:03)
netrw version: 
pi_netrw.txt  For Vim version 8.2.  Last change: 2019 Dec 10

**Comment by cecamp** [comment]
I see the problem, although the gif was too small for legibility.  See http://www.drchip.org/astronaut/vim/index.html#NETRW for netrw v168a.

**Comment by amkarthik** [comment]
@cecamp 
Are you proposing the drchip link as the solution for this problem? This is the reason you closed the issue?

**Comment by k-takata** [comment]
@amkarthik cecamp == Dr. Chip == The maintainer of netrw.
Please try the link and report whether it solves the problem.

**Comment by amkarthik** [comment]
@k-takata 
Thanks for the info.
Sure. I will try and report it here.

**Comment by amkarthik** [comment]
@cecamp 
Cleaned the plugin and reinstalled it. It works fine.
Thanks
