### ISSUE TITLE
Netrw: a confirmation when renaming files?

### ISSUE THREAD

**Issue by for-coursera** [vim/vim#5382]
When renaming multiple files in Netrw with `s/....` command, making a mistake can easily delete / overwrite selected files. Consider this: select multiple files -> press `R` -> clear the input -> enter the rename command `s/.*/test/`, press `<Return>` – and it will result in all the selected files gone except for the last one renamed to `test`.

Thus, it would be great to have a confirmation flag, like `/c`, or may be a confirmation option, something like `g:netrw_rename_confirm` (or may be even a flag, like `/t`, to show / preview the possible changes in a new temp buffer, like `old_file -> new_file`).

**Comment by cecamp** [comment]
Please get http://www.drchip.org/astronaut/vim/index.html#NETRW v168b; there's now some confirmation protection for local files.  Remote files will be trickier.

**Comment by for-coursera** [comment]
@cecamp, thanks!

In case you are interested, I kinda added support for the `/c` flag, in a way similar to the `:h s_c`:

    fun! s:NetrwLocalRename(path) range
    "  call Dfunc("NetrwLocalRename(path<".a:path.">)")
    
      " preparation for removing multiple files/directories
      let ykeep     = @@
      let ctr       = a:firstline
      let svpos     = winsaveview()
      let all_r     = 0     " answering 'all' to the 'moving' question
      let all_o     = 0     " answering 'all' to the 'oeverwrite' question
    "  call Decho("saving posn to svpos<".string(svpos).">",'~'.expand("<slnum>"))
    
      " rename files given by the markfilelist
      if exists("s:netrwmarkfilelist_{bufnr('%')}")
       for oldname in s:netrwmarkfilelist_{bufnr("%")}
    "    call Decho("oldname<".oldname.">",'~'.expand("<slnum>"))
        if exists("subfrom")
         let newname= substitute(oldname,subfrom,subto,'')
    "     call Decho("subfrom<".subfrom."> subto<".subto."> newname<".newname.">",'~'.expand("<slnum>"))
        else
         call inputsave()
         let newname= input("Moving ".oldname." to : ",oldname,"file")
         call inputrestore()
         if newname =~ ''
          " two ctrl-x's : ignore all of string preceding the ctrl-x's
          let newname = substitute(newname,'^.*','','')
         elseif newname =~ ''
          " one ctrl-x : ignore portion of string preceding ctrl-x but after last /
          let newname = substitute(newname,'[^/]*','','')
         endif
         if newname =~ '^s/'
          let subfrom = substitute(newname,'^s/\([^/]*\)/.*/.\{0,1}$','\1','')
          let subto   = substitute(newname,'^s/[^/]*/\(.*\)/.\{0,1}$','\1','')
    "      call Decho("subfrom<".subfrom."> subto<".subto."> newname<".newname.">",'~'.expand("<slnum>"))
          let command = newname
          let newname = substitute(oldname,subfrom,subto,'')
         endif
        endif
        if command[-2:] == '/c'
         if !all_r
          call inputsave()
           echohl Question
           let confirm = input("Moving '" . oldname . "' to '" . newname . "' (y/n/a/q)? ")
           echohl None
          call inputrestore()
          if confirm =~? '^a'
           let all_r = 1
          elseif confirm =~? '^n'
           continue
          elseif confirm =~? '^q'
           redraw!
           break
          elseif confirm != '' && confirm !~? '^y'
           redraw!
           echohl Error
           echom "ERROR: Wrong choice provided"
           echohl None
           break
          endif
         endif
        elseif command[-1:] != '/'
         redraw!
         echohl Error
         echom "ERROR: Wrong substitution command provided"
         echohl None
         break
        endif
        if !all_o && filereadable(newname)
         call inputsave()
          echohl WarningMsg
          let response= input("File '" . newname . "' already exists; do you want to overwrite it? (y/n/a/q)? ")
          echohl None
         call inputrestore()
         if response =~? '^a'
          let all_o= 1
         elseif response !~? '^y' && response !~? '^yes'
          redraw!
         " refresh the directory
    "      call Decho("refresh the directory listing",'~'.expand("<slnum>"))
          NetrwKeepj call s:NetrwRefresh(1,s:NetrwBrowseChgDir(1,'./'))
    "      call Decho("restoring posn to svpos<".string(svpos).">",'~'.expand("<slnum>"))
          NetrwKeepj call winrestview(svpos)
          let @@= ykeep
    "      call Dret("NetrwLocalRename")
          return
         endif
        endif
        call rename(oldname,newname)
       endfor
       call s:NetrwUnmarkList(bufnr("%"),b:netrw_curdir)
    [...]
