### ISSUE TITLE
add fold-related fillchars

### ISSUE THREAD

**Issue by teto** [vim/vim#5387]
**Is your feature request related something that is currently hard to do? Please describe.**
I like some eye-candy in my terminal and I'e implemented additionnal fold-related fillchars for neovim https://github.com/neovim/neovim/pull/11568. 
I wonder if there would be any interest for vim to implement something similar ? is the naming fine ?
I would like to avoid a divergence between the 2 software. 

NB: github accept hidden comments so it should be possible to provide a bug template that doesn't require to delete text. See the templates at github.com/nixos/nixpkgs for instance.

**Comment by Shane-XB-Qian** [comment]
https://github.com/vim/vim/pull/7924

**Comment by chrisbra** [comment]
so closing as fixed in  4fa1175
