### ISSUE TITLE
Vim doesn't output file and lines in a format that it can process

### ISSUE THREAD

**Issue by idbrii** [vim/vim#5391]
**Description**

Vim commands like `:verbose command` and `:profile` will output file and line numbers, but vim's `gF` command cannot jump to these line numbers.

This is because they are separated with the word 'line'.

```
FUNCTION  41()
    Defined: ~/.vim/bundle/unite-neomru/autoload/neomru.vim line 259
Called 1 time
Total time:   0.036302
 Self time:   0.004542
```

```
:verbose command UniteDo
    Name        Args       Address   Complete  Definition
    UniteDo     1                    command       call unite#start#_do_command(<q-args>)
	Last set from ~/.vim/bundle/unite/plugin/unite.vim line 55
```

The help for gF says:

> The file name and the number must be
> separated by a non-filename (see 'isfname') and
> non-numeric character.

**To Reproduce**
```
$ vim --clean
:profile start ~/vim-prof-example.log | profile file * | profile func *
:edit $VIMRUNTIME/filetype.vim
:quit
$ vim --clean ~/vim-prof-example.log
/Defined:.../e
gF
```

**Expected behavior**

We were on this line:

> Defined: /usr/local/Cellar/macvim/8.1-155/MacVim.app/Contents/Resources/vim/runtime/syntax/synload.vim line 33

We should jump to the displayed file and line number.

**Actual behavior**
We jump to the displayed file but not line number.

**Environment**

VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 19 2019 12:07:03)
macOS version
Included patches: 1-950

 - OS: macOS 10.14.6
 - Both GUI (gvim) and macOS Terminal

**Comment by idbrii** [comment]
Making gF accept 'line' as a separator seems nice, but probably brings up has translation issues.

I'd propose outputting in one of the forms that gF accepts:

	Last set from ~/.vim/bundle/unite/plugin/unite.vim @ 55
	Last set from ~/.vim/bundle/unite/plugin/unite.vim (55)

(I use `gF` on `:verbose command` output via vim-scriptease. But I think it should be updated along with profile to keep outputting file and lines in a consistent way! Not sure if there are other cases I missed.)

**Comment by tonymec** [comment]
If you can get the bare filename into some register (let's say the default register, but you could make it work with the clipboard), you can remember the line number, can't you? Then `:new +1234 ^R"` (where `^R"` means «hit Ctrl-R then the double quote character») will bring up line 1234 of that file in a new window. 

See
* `:help c_CTRL-R`
* `:help +cmd`

Best regards,
Tony.

**Comment by brammool** [comment]
We can recognize "line" and its translations.  It is currently defined in last_set_msg() and can be put in globals.h so the same translation is used.

**Comment by idbrii** [comment]
Thanks for the tip.

I usually `1234G` or search to get myself there, but it'd be great if gF was useful. This seems like low-hanging fruit, so hopefully I can find some time do to a patch myself...

**Comment by Shane-XB-Qian** [comment]
@brammool sorry, but recognized `' line '` as separator maybe not a good idea, looks it would break some rule ...

sth e.g i knew we refined '|' recoginzed in vimgrep which not need a 'escape' any more, but that probably make some plugin failed as well, if think the compatible, maybe need to be careful ...

anyway, looks if file had quoting e.g `"` before `' line '`, gF still not working ...

btw: au shellcmdpost and shellfilterpost looks was not reliable too, if  to capture last msg or rc or something ...

**Comment by chrisbra** [comment]
can you please clearly provide an example of what does not work and what should work?

**Comment by Shane-XB-Qian** [comment]
"xzy.foo" line 123

**Comment by brammool** [comment]
Where do you see such a quoted file name?

**Comment by Shane-XB-Qian** [comment]
e.g `ls`
but i mean such thing perhaps better be handled at user side (vs such general one) by his/her vim script or sth .. better be not to break the general rule like gF .. i am just thinking the backward compatible ...
some plugin had lost maintainer, if such un-compatible happened, no one to fix it .. just worry about that ..  -_-# :)

**Comment by Shane-XB-Qian** [comment]
or whatever, since other than `:`, those `@` and `()` and sth had been accepted already .. up to you .. :)

**Comment by idbrii** [comment]
I finally updated to a new version of vim (8.2.140) and can confirm that this change works as expected.

Thanks!
