### ISSUE TITLE
\_^ not match

### ISSUE THREAD

**Issue by agguser** [vim/vim#5400]
**Describe the bug**
`\_^` pattern does not match start-of-lines.

**To Reproduce**
```
:echo substitute("abc\nabc\nabc", '\_^a', 'A', 'g')
Abc
abc
abc
```

**Expected behavior**
```
Abc
Abc
Abc
```

**Environment (please complete the following information):**
- Vim 8.1.2268
- OS: Arch Linux 5.2.14
- Terminal: xterm

**Comment by andymass** [comment]
In `substitute()`, `^` means start of string not start of line.   Besides what do you expect `\_^` to mean?

**Comment by brammool** [comment]
See ":help string-match".  You can use \n to match the line break character.

**Comment by agguser** [comment]
So the following must be used:
``` 
:echo substitute("abc\nabc\nabc", '\(^\|\n\)a', '\1A', 'g')
```

Why make pattern for matching "string" and "text in buffer" different?
