### ISSUE TITLE
Out-of-date information about `:tselect` in tagsrch.txt

### ISSUE THREAD

**Issue by jairlopez** [vim/vim#5403]
I was reading [`:help :tselect`](https://github.com/vim/vim/blob/0c1e3744ff0cd6c17af773046b876b428ff3dded/runtime/doc/tagsrch.txt#L200)
https://github.com/vim/vim/blob/0c1e3744ff0cd6c17af773046b876b428ff3dded/runtime/doc/tagsrch.txt#L210-L232
when I realized these phrases are out of sync. The current phrase is:

    Enter nr of choice (<CR> to abort):

but `:tselect` shows this one:

    Type number and <Enter> (empty cancels):

The same goes for the header, it's

    nr pri kind tag		file

but `:tselect` currently shows:

    # pri kind tag               file

[This](https://github.com/vim/vim/blame/0c1e3744ff0cd6c17af773046b876b428ff3dded/runtime/doc/tagsrch.txt#L210) section was last updated on Jun 13th, 2004 so I wonder if this information is still up to date, specially this part:
https://github.com/vim/vim/blob/0c1e3744ff0cd6c17af773046b876b428ff3dded/runtime/doc/tagsrch.txt#L227-L229

**Comment by brammool** [comment]
I'll update the help.  Thanks for reporting
