### ISSUE TITLE
settagstack can't natively replicate :tag behavior

### ISSUE THREAD

**Issue by frangio** [vim/vim#5405]
Plugins like LSP clients are now using `settagstack` to replicate the behavior of `C-]`, but the provided API only allows replacing the entire stack or appending to it, which makes it non-trivial to replicate the native tagstack behavior.

Natively, jumping to a tag will insert the new tag at the current index, and remove everything that came after it. This allows "tree like" navigation through tags, by using `C-T` to go up in the stack and then jumping to a different tag branching off in a different direction.

I think `settagstack` should have a third mode to replace the tagstack entries from the current index up to the end, so as to easily replicate native tag navigation. Without this mode, plugin authors either manually reimplement it [as in vim-lsp](https://github.com/prabirshrestha/vim-lsp/blob/master/autoload/lsp/ui/vim.vim#L456-L476), or simply use append without being aware of the difference in behavior.

**Comment by andymass** [comment]
Use tagfunc

**Comment by brammool** [comment]
Francisco Giordano wrote:

> Plugins like LSP clients are now using `settagstack` to replicate the
> behavior of `C-]`, but the provided API only allows replacing the
> entire stack or appending to it, which makes it non-trivial to
> replicate the native tagstack behavior.
> 
> Natively, jumping to a tag will insert the new tag at the current
> index, and remove everything that came after it. This allows "tree
> like" navigation through tags, by using `C-T` to go up in the stack
> and then jumping to a different tag branching off in a different
> direction.
> 
> I think `settagstack` should have a third mode to replace the tagstack
> entries from the current index up to the end, so as to easily
> replicate native tag navigation. Without this mode, plugin authors
> either manually reimplement it [as in
> vim-lsp](https://github.com/prabirshrestha/vim-lsp/blob/master/autoload/lsp/ui/vim.vim#L456-L476),
> or simply use append without being aware of the difference in
> behavior.

Can't you get the existing stack with gettagsack() and modify it any way
before using settagstack() ?

-- 
Some say the world will end in fire; some say in segfaults.
I say it will end in a curly bracket.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by frangio** [comment]
>Can't you get the existing stack with gettagsack() and modify it any way
>before using settagstack() ?

Yes, this is what vim-lsp is doing. I'm trying to say that since it will almost always be the right thing to do, the functionality should exist out of the box.

**Comment by brammool** [comment]
> >Can't you get the existing stack with gettagsack() and modify it any way
> >before using settagstack() ?
> 
> Yes, this is what vim-lsp is doing. I'm trying to say that since it
> will almost always be the right thing to do, the functionality should
> exist out of the box.

So it would be sufficient to add an action "t" (for truncate), that
works like "a" (append), but first truncates at the current index?

-- 
I'm sure that I asked CBuilder to do a "full" install.  Looks like I got
a "fool" install, instead.		Charles E Campbell, Jr, PhD


 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by frangio** [comment]
That's what I had in mind yes!

**Comment by vim-ml** [comment]
Hi,

On Sun, Dec 29, 2019 at 8:44 PM Francisco Giordano <
vim-dev-github@256bit.org> wrote:

> That's what I had in mind yes!
>
>
>
I have created PR #5417 to add support for truncating the tag stack before
pushing new items onto the stack.

- Yegappan

**Comment by chrisbra** [comment]
included as of https://github.com/vim/vim/releases/tag/v8.2.0077

**Comment by vim-ml** [comment]
Hi,

On Sun, Dec 29, 2019 at 12:20 AM Francisco Giordano <
vim-dev-github@256bit.org> wrote:

> Plugins like LSP clients are now using settagstack to replicate the
> behavior of C-], but the provided API only allows replacing the entire
> stack or appending to it, which makes it non-trivial to replicate the
> native tagstack behavior.
>
> Natively, jumping to a tag will insert the new tag at the current index,
> and remove everything that came after it. This allows "tree like"
> navigation through tags, by using C-T to go up in the stack and then
> jumping to a different tag branching off in a different direction.
>
> I think settagstack should have a third mode to replace the tagstack
> entries from the current index up to the end, so as to easily replicate
> native tag navigation. Without this mode, plugin authors either manually
> reimplement it as in vim-lsp
> <https://github.com/prabirshrestha/vim-lsp/blob/master/autoload/lsp/ui/vim.vim#L456-L476>,
> or simply use append without being aware of the difference in behavior.
>

Can you try the latest version of Vim and see whether the new truncate
tagstack functionality meets your requirement?

Thanks,
Yegappan
