### ISSUE TITLE
user_data is always string. allow type to be any to improve perf

### ISSUE THREAD

**Issue by prabirshrestha** [vim/vim#5412]
**Is your feature request related something that is currently hard to do? Please describe.**
No. But this has performance impact.

**Describe the solution you'd like**
Allow `user_data` for `complete-items` to be of any type.

**Describe alternatives you've considered**
Currently using `json_encode` to convert object to string.

**Additional context**
If we have 100 autocomplete results, we need to call `json_encode` 100 times to save the state to `user_data` since it allows only string. And then when the `CompleteDone` is fired we need to again call `json_decode`. As you can we we mostly likely only need to process 1 item but we need to call `json_encode` n times.
LSP returns json data for complete help text/text edits(such as autoimports)/snippet information which can be quite big so I would prefer not to call `json_encode` we don't have to at all.

**Comment by brammool** [comment]
How about this: instead of adding your object to user_data, generate a unique key, put the data in a dictionary under that key and put the key in user_data.  Then on CompleteDone you can lookup the data in that dictionary.

**Comment by prabirshrestha** [comment]
I think that will increase the complexity on the plugin authors since plugins authors now have to cleanup once it is no longer needed. I was just hoping for vim GC to cleanup it up.

For LSP we could be having multiple language servers running and they are async so we can't just reset the key to 0. I do also want the generating key to be simple as just increment number for perf.

Any reason why `user_data` cannot support arbitrary object?

I would rather have a check on version number and ask the plugin users to upgrade their vim instead of having custom code in the plugin.

**Comment by puremourning** [comment]
The intention of this user data field was to do exact what Bram said - store an ID/key in the completion item. That’s what YCM does.

**Comment by brammool** [comment]
> I think that will increase the complexity on the plugin authors since
> plugins authors now have to cleanup once it is no longer needed. I was
> just hoping for vim GC to cleanup it up.
> 
> For LSP we could be having multiple language servers running and they
> are async so we can't just reset the key to 0. I do also want the
> generating key to be simple as just increment number for perf.
> 
> Any reason why `user_data` cannot support arbitrary object?
> 
> I would rather have a check on version number and ask the plugin users
> to upgrade their vim instead of having custom code in the plugin.

Internally all the info for a match is a string.  Making an exception
for user_data would be a bit of work.  Plus making sure it's freed
properly.  And add tests.

-- 
BLACK KNIGHT:  I move for no man.
ARTHUR:        So be it!
    [hah] [parry thrust]
    [ARTHUR chops the BLACK KNIGHT's left arm off]
ARTHUR:        Now stand aside, worthy adversary.
BLACK KNIGHT:  'Tis but a scratch.
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by prabirshrestha** [comment]
We are changing to use index key in https://github.com/prabirshrestha/vim-lsp/pull/637.

Bit more work for plugin authors 😞 but works.

@brammool Would it be better to document this as I would hate other plugins to just use `json_encode/json_decode` and impact perf?

 We are also now using the key that looks something like `vim-lsp/0` so that we can easily ignore completed items we don't generate when multiple sources are used.

Feel free to close the issue.

**Comment by chrisbra** [comment]
@prabirshrestha how about a suggestion on how to better document this?

**Comment by puremourning** [comment]
how about:

```diff
BenMBP:vim ben$ git diff
diff --git a/runtime/doc/insert.txt b/runtime/doc/insert.txt
index 419213dba..13e20fe80 100644
--- a/runtime/doc/insert.txt
+++ b/runtime/doc/insert.txt
@@ -1107,8 +1107,10 @@ items:
                        item with the same word is already present.
        empty           when non-zero this match will be added even when it is
                        an empty string
-       user_data       custom data which is associated with the item and
-                       available in |v:completed_item|
+       user_data       small custom datum which is associated with the item
+                       and available in |v:completed_item|
+                       If you have a lot of data, store an ID, don't just
+                       json-encode a big data object.

 All of these except "icase", "equal", "dup" and "empty" must be a string.  If
 an item does not meet these requirements then an error message is given and
```

**Comment by andymass** [comment]
@prabirshrestha, @puremourning it is not actually any faster (unfortunately) but you could use `string`/`eval` instead of `json_encode`/`json_decode` to be more vim "native."
