### ISSUE TITLE
Unable to build with --enable-mzschemeinterp in Pop!_OS 19.10

### ISSUE THREAD

**Issue by ksze** [vim/vim#5416]
**Describe the bug**
Unable to build with `--enable-mzschemeinterp` on Pop!_OS 19.10 (which is basically Ubuntu 19.10 with a different GNOME theme and different GNOME desktop environment defaults)

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Install essential tools for building programs:
```sudo apt update && sudo apt install build-essential autoconf automake autotools-dev```
2. Install Racket 7.5 from the PPA for Ubuntu, because the one from the Ubuntu deb repo is possibly too old (version 7.2), according to https://github.com/vim/vim/issues/2596#issuecomment-527155017:
  a. `sudo add-apt-repository ppa:plt/racket`
  b. `sudo apt update`
  c. `sudo apt install racket`
3. Clone the vim git repository and check out v8.2.0058;
4. Run the configure script in the vim repo directory:
```
CFLAGS='-O3 -march=native' ./configure \                                                                                                                                              
  --prefix="$HOME/.local" \
  --enable-fail-if-missing \
  --enable-mzschemeinterp \
  --with-plthome=/usr/local
```
5. `make -j`

**Expected behavior**
vim being built successfully

**Actual behavior**
Build fails, with this output at the end:
```
if_mzsch.c: In function ‘window_new’:
if_mzsch.c:1937:21: error: lvalue required as left operand of assignment
 1937 |     WINDOW_REF(win) = self;
      |                     ^
if_mzsch.c: In function ‘buffer_new’:
if_mzsch.c:2321:21: error: lvalue required as left operand of assignment
 2321 |     BUFFER_REF(buf) = self;
      |                     ^
make[1]: *** [Makefile:3236: objects/if_mzsch.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/kal/git/vim/vim/src'
make: *** [Makefile:29: first] Error 2
```

**Environment (please complete the following information):**
 - Vim version 8.2.0058
 - OS: Pop!_OS 19.10 (which is basically Ubuntu 19.10)
 - Terminal: GNOME Terminal

**Comment by brammool** [comment]
> **Describe the bug**
> Unable to build with --enable-mzschemeinterp on Pop!_OS 19.10 (which
> is basically Ubuntu 19.10 with a different GNOME theme and different
> GNOME desktop environment defaults)
> 
> **To Reproduce**
> Detailed steps to reproduce the behavior:
> 1. Install essential tools for building programs:
> ```sudo apt update && sudo apt install build-essential autoconf automake autotools-dev```
> 2. Install Racket 7.5 from the PPA for Ubuntu, because the one from the Ubuntu deb repo is possibly too old (version 7.2), according to https://github.com/vim/vim/issues/2596#issuecomment-527155017:
>   a. `sudo add-apt-repository ppa:plt/racket`
>   b. `sudo apt update`
>   c. `sudo apt install racket`
> 3. Clone the vim git repository and check out v8.2.0058;
> 4. Run the configure script in the vim repo directory:
> ```
> CFLAGS='-O3 -march=native' ./configure \                                                                                                                                              
>   --prefix="$HOME/.local" \
>   --enable-fail-if-missing \
>   --enable-mzschemeinterp \
>   --with-plthome=/usr/local
> ```
> 5. `make -j`
> 
> **Expected behavior**
> vim being built successfully
> 
> **Actual behavior**
> Build fails, with this output at the end:
> ```
> if_mzsch.c: In function ‘window_new’:
> if_mzsch.c:1937:21: error: lvalue required as left operand of assignment
>  1937 |     WINDOW_REF(win) = self;
>       |                     ^
> if_mzsch.c: In function ‘buffer_new’:
> if_mzsch.c:2321:21: error: lvalue required as left operand of assignment
>  2321 |     BUFFER_REF(buf) = self;
>       |                     ^
> make[1]: *** [Makefile:3236: objects/if_mzsch.o] Error 1
> make[1]: *** Waiting for unfinished jobs....
> make[1]: Leaving directory '/home/kal/git/vim/vim/src'
> make: *** [Makefile:29: first] Error 2
> ```
> 
> **Environment (please complete the following information):**
>  - Vim version 8.2.0058
>  - OS: Pop!_OS 19.10 (which is basically Ubuntu 19.10)
>  - Terminal: GNOME Terminal

I have not been able to build with Racket (installed from a package) for
a while.  The suggestion is to build racket from source.

I'm wondering though: What do you need the mzscheme interface for?
What plugin is using it?

-- 
If your life is a hard drive,
Christ can be your backup.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ksze** [comment]
Right, using Racket built from source works.

I don't have any immediate need for mzscheme, I think. I have no idea if any of the plugins I use needs it. I'm building vim with every interpreter interface just because I can. :P

Perhaps it would be a good idea to state in one of the README files the fact that using Racket built from source is usually required for `--enable-mzschemeinterp`?

**Comment by brammool** [comment]
It is mentioned in the Makefile.  It's not clear to me when building from source is required, thus the remark is a bit vague.

I wonder if we can just drop this interface.  What would break, who would complain?

**Comment by Gliese852** [comment]
Please, no

**Comment by k-takata** [comment]
This was discussed in the mailing list and the proposal to drop if_mzsch has been withdrawn.
