### ISSUE TITLE
custom highlighting broken with upgrade from 7.4.488

### ISSUE THREAD

**Issue by titus65** [vim/vim#542]
Hi,

Since upgrading from 7.4.488 to 7.4.963 my custom highlighting
rules are no longer effective.

Here is the .vimrc.test that demonstrates the problem:

```
    " comment this should appear in DarkCyan
set nocompatible
syntax on
hi Comment term=bold ctermfg=6 guifg=DarkCyan
hi Identifier term=underline ctermfg=4 guifg=Blue
    " EOF
```

And the command is:

```
vim --noplugin -i NONE -u ~/.vimrc.test ~/.vimrc.test
```

When "set nocompatible" is uncommented then the highlighting rules are
not effective. If commented they work. With 488-7 it makes no difference
(as expected).

**Comment by chrisbra** [comment]
I am not sure, I understand the problem. Please state clearly what does not work. For me, running your commandline it does not make any difference for the mentioned highlighting groups, whether set nocp is uncommented or not. I used vim 7.4.979  for testing.

**Comment by titus65** [comment]
with these two 'hi' lines in my ~/.vimrc I used to be able to swap Comment and Identifier colors but after 7.4.488 this no longer works.
How would you do the color swapping yourself?

**Comment by vim-ml** [comment]
On Wednesday, December 30, 2015 at 1:49:59 AM UTC-6, titus65 wrote:

> Hi,
> 
> Since upgrading from 74488 to 74963 my custom highlighting
> 
> rules are no longer effective
> 
> Here is the vimrctest that demonstrates the problem:
> 
> ```
> " comment this should appear in DarkCyan
> ```
> 
> set nocompatible
> syntax on
> hi Comment term=bold ctermfg=6 guifg=DarkCyan
> hi Identifier term=underline ctermfg=4 guifg=Blue
>     " EOF
> 
> And the command is:
> 
> vim --noplugin -i NONE -u ~/vimrctest ~/vimrctest
> 
> When "set nocompatible" is uncommented then the highlighting rules are
> 
> not effective If commented they work With 488-7 it makes no difference
> 
> (as expected)

First: I can confirm that these lines do not change the highlighting, in 7.4.909.

When I use the indicated commands as a .vimrc, the comments are blue, and not set from the test .vimrc. ":verbose hi Comment" gives:

Comment        xxx term=bold ctermfg=1 guifg=Blue
    Last set from C:\Program Files\vim\vim74\syntax\syncolor.vim

This is at least unexpected behavior. I'd certainly expect the .vimrc colors to apply.

However, I see no difference with and without the nocompatible setting.

To work around this behavior, and in general, I would suggest putting any such :hi commands either in a colorscheme file, or in a ColorScheme autocmd event. Doing it this way does NOT show the problem.

**Comment by arbitrary-dev** [comment]
Got the same problem (8.0.106). My color settings (`syntax.local`) get overwriten by `syncolor.vim`.

`:scriptnames`
```
  1: /etc/vim/vimrc
...
  4: /usr/share/vim/vim80/syntax/syncolor.vim
...
 10: /etc/vim/vimrc.local
...
 13: /etc/vim/syntax.local
...
... no mention of syncolor.vim any further
```

But `vim -V999log` reveals that `syncolor.vim` was sourced twice, and I don't know why:

```
line 19: sourcing "/usr/share/vim/vim80/syntax/synload.vim"line 16:
...
line 17: " Set the default highlighting colors.  Use a color scheme if specified.
line 18: if exists("colors_name")
line 19:   exe "colors " . colors_name
line 20: else
line 21:   runtime! syntax/syncolor.vim
Searching for "syntax/syncolor.vim" in "/root/.vim,/usr/share/vim/vimfiles,/usr/share/vim/vim80,/usr/share/vim/vimfiles/after,/root/.vim/after"
Searching for "/root/.vim/syntax/syncolor.vim"
Searching for "/usr/share/vim/vimfiles/syntax/syncolor.vim"
Searching for "/usr/share/vim/vim80/syntax/syncolor.vim"
chdir(/usr/share/vim/vim80/syntax)
fchdir() to previous dir
line 21: sourcing "/usr/share/vim/vim80/syntax/syncolor.vim"
...
finished sourcing /usr/share/vim/vim80/syntax/syncolor.vim
...
line 52: sourcing "/etc/vim/syntax.local"
...
line 18: verb hi Special
Special        xxx term=bold ctermfg=5 guifg=SlateBlue
	Last set from /usr/share/vim/vim80/syntax/syncolor.vim
line 19: hi Special ctermfg=1
line 20: verb hi Special
Special        xxx term=bold ctermfg=1 guifg=SlateBlue
	Last set from /etc/vim/syntax.local
...
finished sourcing /etc/vim/syntax.local
...
finished sourcing /usr/share/vim/vim80/plugin/zipPlugin.vim
Searching for "pack/*/start/*" in "/root/.vim,/usr/share/vim/vimfiles,/usr/share/vim/vim80,/usr/share/vim/vimfiles/after,/root/.vim/after"
Searching for "/root/.vim/pack/*/start/*"
Searching for "/usr/share/vim/vimfiles/pack/*/start/*"
Searching for "/usr/share/vim/vim80/pack/*/start/*"
Searching for "/usr/share/vim/vimfiles/after/pack/*/start/*"
Searching for "/root/.vim/after/pack/*/start/*"
not found in 'packpath': "pack/*/start/*"
Searching for "pack/*/start/*" in "/root/.vim,/usr/share/vim/vimfiles,/usr/share/vim/vim80,/usr/share/vim/vimfiles/after,/root/.vim/after"
Searching for "/root/.vim/pack/*/start/*"
Searching for "/usr/share/vim/vimfiles/pack/*/start/*"
Searching for "/usr/share/vim/vim80/pack/*/start/*"
Searching for "/usr/share/vim/vimfiles/after/pack/*/start/*"
Searching for "/root/.vim/after/pack/*/start/*"
not found in 'packpath': "pack/*/start/*"
Searching for "plugin/**/*.vim" in "/root/.vim,/usr/share/vim/vimfiles,/usr/share/vim/vim80,/usr/share/vim/vimfiles/after,/root/.vim/after"
Searching for "/usr/share/vim/vimfiles/after/plugin/**/*.vim"
Searching for "/root/.vim/after/plugin/**/*.vim"
not found in 'runtimepath': "plugin/**/*.vim"
Opening the X display took 0 msec
Reading viminfo file "/root/.viminfo" info oldfiles
Opening the X display took 0 msec
Searching for "syntax/syncolor.vim" in "/root/.vim,/usr/share/vim/vimfiles,/usr/share/vim/vim80,/usr/share/vim/vimfiles/after,/root/.vim/after"
Searching for "/root/.vim/syntax/syncolor.vim"
Searching for "/usr/share/vim/vimfiles/syntax/syncolor.vim"
Searching for "/usr/share/vim/vim80/syntax/syncolor.vim"
chdir(/usr/share/vim/vim80/syntax)
fchdir() to previous dir
sourcing "/usr/share/vim/vim80/syntax/syncolor.vim"
line 1: " Vim syntax support file
...
... and it overwrites my local colors
```

**Comment by xaizek** [comment]
@arbitrary-dev, Vim loads `syncolor.vim` directly in C code on certain occasions. See [`:help g:colors_name`](http://vimhelp.appspot.com/options.txt.html#g:colors_name) (if `g:colors_name` is not set, `syncolor.vim` is used). I had a similar issue, which was solved by moving `set background=dark` line in configuration.

**Comment by joelostblom** [comment]
Changing the comment highlight color as indicated in the first post, is working for me on vim 8.0.329. It works both  with `set nocompatible` and without it. `:verbose hi Comment` reports that colors has been set from my testvimrc file, not from `syncolor.vim`.

**Comment by chrisbra** [comment]
okay, closing then.

**Comment by ferpega** [comment]
In my vim 8.0.1453 it is not working also.
Perhaps I am doing something wrong, but I cannot get it to run.

If I set 'hi comment.....' in my opened vim it is running, but not in /etc/vimrc (ubuntu on WSL).
Thanks.
