### ISSUE TITLE
:{count}vim[grep] ... limit match totally but not per file

### ISSUE THREAD

**Issue by VimWei** [vim/vim#5420]
**Describe the bug**
gVim 8.2 `:{count}vim[grep] ...` limit the match number **totally but not per file** in gVim 8.1.

**To Reproduce**
Detailed steps to reproduce the behavior:

I updated gVim from 8.1 to 8.2 recently.

1. `<leader>ww`  "go to vimwiki and autochdir to vimwiki
2. `:1vimgrep /markdown/ **/*.md`  " search pattern in all .md files under vimwiki
3. There is only one match totally, but not one match per file.
4. If I use another tool, `Leaderf rg -m=1 markdown`, there are 13 matchs, one line per file.

**Expected behavior**
`:1vim[grep] ...`  can match multi lines, one line per file.

**Screenshots**
`:1vimgrep /markdown/ **/*.md` 
![1vimgrep](https://i.loli.net/2019/12/31/AP3r9DlZCtbgcE4.png)

`Leaderf rg -m=1 markdown`
![Leaderf rg -m=1](https://i.loli.net/2019/12/31/lKf3A6mcIzYQsCt.png)

**Environment (please complete the following information):**
 - Vim version 8.2 (2019 Dec 12, compiled Dec 17 2019 23:02:26)
 - OS: Windows 10 pro 1909
 - Terminal: Use GUI

**Additional context**
gvim_8.2.0019_x64_signed.exe from 
https://github.com/vim/vim-win32-installer/releases/tag/v8.2.0019

**Comment by chrisbra** [comment]
is this a feature request?

**Comment by VimWei** [comment]
> is this a feature request?

No. This is a bug report.

**Comment by chrisbra** [comment]
I don't understand it. As far as I know, that's how `{count}vimgrep` has always worked. I don't remember it ever being working differently. 

(:h :vimgrep)[https://vimhelp.org/quickfix.txt.html#%3Avimgrep] shows this:

> :{count}vim[grep] ...
>                         When a number is put before the command this is used
>                         as the maximum number of matches to find.  Use
>                         ":1vimgrep pattern file" to find only the first.
>                         Useful if you only want to check if there is a match
>                         and quit quickly when it's found.

So this works as expected. 

Can you please come up with a reproducible example (starting from `vim --clean`) that shows the bug (preferably without any external tools or mappings) in the previous version (which was what?) and the current version?

**Comment by VimWei** [comment]
Not exactly.  

**Reinstall and Run**
I reinstall the gvim 8.1 and 8.2 from vim.org ftp and Run `vim --clean` ( I do not know how to run gVim clean under win10, but I delete all my own vimrc and run gvim with default setting.)

**gvim Version**
ftp://ftp.vim.org/pub/vim/pc/gvim81.exe
ftp://ftp.vim.org/pub/vim/pc/gvim82.exe

**There are the contrast GIF:**

Same: OS, gVim setting, Data and Vim Command.
Different: gVim version.
The results are different: 

1.  gvim 8.1 has many matches, one match per file.
![gvim8.1-vimgrep.gif](https://i.loli.net/2019/12/31/hZKbjgrC31HfmNl.gif)
2.  gvim 8.2 has only one match. 
![gvim8.2-vimgrep.gif](https://i.loli.net/2019/12/31/G9Sf1wVtyKFqJPz.gif)

**Comment by chrisbra** [comment]
I am not sure what to do with this. Vim works as documented. The behaviour you saw with Vim 8.1 has been "fixed" by commit https://github.com/vim/vim/commit/1c29943416207e21abbc790e

The old behaviour can probably be restored by a custom plugin.

**Comment by VimWei** [comment]
But I'm not a programmer, do not know how to restore it. 
This issue would be better as a feature request.
Thanks!

**Comment by VimWei** [comment]
Document `Use":1vimgrep pattern file" to find only the first.` just describe one file, but not multifiles.

Rethink the actual scence of my daily work, "One match per file" may be more usefull then "one match in the whole project". I usually use":1vim pattern **" as fuzzy search to locate the files include pattern in the project, but not care many accurate locations of pattern in a file, the pattern is just breadcrumb.

**Comment by chrisbra** [comment]
I would suggest just to use `:vimgrep /patter/ files` and then use `:cnfile` to advance to the next file.

**Comment by VimWei** [comment]
Thanks
