### ISSUE TITLE
"expand('<sfile>')" wrongly evaluated inside a script-local function

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#5425]
**Describe the bug**

The first evaluation of `expand('<sfile>')` inside a script-local function is correct, but not the subsequent evaluations.

**To Reproduce**

Write this in `/tmp/vim.vim`:

    fu s:func()
        return expand('<sfile>')
    endfu
    echo s:func()

Then, start Vim with this shell command:

    vim -Nu NONE

Finally, execute this Ex command twice:

    :so /tmp/vim.vim

The first output is:

    function <SNR>1_func

The second one is:

    function <80><fd>R1_func

**Expected behavior**

The output is always `function <SNR>1_func`.

**Environment**

 - Vim version: 8.2 Included patches: 1-69
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

I rely on `expand('<sfile>')` in various locations to set some option with the value of a script-local function name.

Example:

    fu s:snr()
        return matchstr(expand('<sfile>'), '.*\zs<SNR>\d\+_')
    endfu
    let &l:inex = s:snr()..'inex()'
    fu s:inex()
        ...
    endfu

When the code is written inside a filetype plugin, the first time the buffer is loaded, the option is correctly set (`<SNR>123_inex()`); but as soon as I reload it, the option is reset to a wrong value (`inex()`) because the `<SNR>123_` prefix has been lost.

As a workaround, the issue can be avoided by saving the output of `s:snr()` in a variable, to avoid its re-evaluation:

    fu s:snr()
        return matchstr(expand('<sfile>'), '.*\zs<SNR>\d\+_')
    endfu
    let s:snr = get(s:, 'snr', s:snr())
    let &l:inex = s:snr..'inex()'
    fu s:inex()
        ...
    endfu

---

I think it's a regression introduced by https://github.com/vim/vim/commit/1a47ae32cdc19b0fd5a82e19fe5fddf45db1a506.

Before this commit, the evaluation was always the same.

**Comment by tonymec** [comment]
Hm, that patch (8.2.0056) is part of a series meant to make functions execute faster by means of, IIUC, JIT compiling to a sort of bytecode.

&lt;SNR&gt; has always been represented internally by a certain sequence of bytes beginning with 0x80. Maybe 0x80 0xFD R ? Then the error would be in failing to reinterpret it as one <> symbolic name.

Best regards,
Tony.
