### ISSUE TITLE
"R" displayed on the command-line before inserting a register

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#5429]
**Describe the bug**

When inserting a register on the command-line, the character `R` is displayed for 1 second.

**To Reproduce**

Open an xterm window.

Then, start Vim with this shell command:

    vim -Nu NONE +'cno <c-r><c-g> abc'

Finally, press `:` to enter the command-line, and `C-r` to insert the contents of a register.
The character `R` is displayed under the cursor for 1 second (or `&timeoutlen` ms). Then it's replaced by `"`.

**Expected behavior**

No character is displayed for 1 second. Then, `"` is displayed.

**Screenshots**

![gif](https://user-images.githubusercontent.com/8505073/71654895-7d2ef480-2d34-11ea-92e0-c2e3182aac58.gif)

**Environment**

 - Vim version: 8.2 Included patches: 1-76
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

I can only reproduce in xterm, not in other terminals (like st or gnome-terminal).

---

I can reproduce even without any config in `~/.Xresources`.

---

This behavior is new; it appeared from the commit 4b57018ee4e6d608e3a28e0ee4fdd2f057cc0e89.

---

I don't know whether this is intended.
I've looked at `:h modifyOtherKeys` but this is not listed there.
However, the help does say that if the modifyOtherKeys mode causes an issue, it can be disabled:

> In case the modifyOtherKeys mode causes problems you can disable it: >
>       let &t_TI = ""
>       let &t_TE = ""
> It does not take effect immediately.  To have this work without restarting Vim
> execute a shell command, e.g.: `!ls`  Or put the lines in your |vimrc|.

I tried what the help says:

    :let &t_TI = '' | let &t_TE = '' | !ls

But it doesn't work; `R` keeps being displayed.
Worse, after quitting Vim, I can no longer use readline commands such as `C-a` and `C-e` to move the cursor to the start/end of the shell's command-line; instead, the terminal inserts key sequences such as `;5;97~`.

OTOH, this works:

    :let &t_TI = '' | !ls

But then, all the command-line mappings whose lhs contains a key combined with the `CTRL` modifier seem to be broken. That is, if I press `C-r C-g`, `abc` is not inserted anymore.

    $ vim -Nu NONE +'cno <c-r><c-g> abc' +'cno z<c-z> def'
    :let &t_TI = '' | !

    " press C-r: the "R" character is not displayed anymore ✔
    " press C-g: "abc" is not inserted ✘

    " press z: the "z" character is displayed ✔
    " press C-z: "z^Z" is inserted on the command-line instead of "def" ✘

**Comment by brammool** [comment]
I would say this is working as intended.  Vim is waiting for the mapping to match or not.  Normally the typeahead is displayed, but before the CTRL-R was not visible.   Now the R is displayed, which is what you typed.
