### ISSUE TITLE
Request APIs to implement command line completion

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#5432]
Want to implement something like this:

![](https://user-images.githubusercontent.com/3035071/53684527-723cb980-3d49-11e9-9b6b-1a6ca7f1a19c.png)

It is possible now to display a completion popup window, but still lack of APIs to:

1. read content from current command line buffer.
2. modify command line buffer.
3. method to call the completion functions for each command.

command line completion is helpful to input filenames or command parameters.

It is impossible to implement without these APIs above.

**Comment by brammool** [comment]
1. getcmdline()
2. use feedkeys(), setcmdpos()
3. getcompletion()

**Comment by blayz3r** [comment]
Is there a possibility of having a popup analogous to the _'wildmenu'_?

**Comment by chrisbra** [comment]
> Is there a possibility of having a popup analogous to the 'wildmenu'?

do you want a popup or wildmenu? 

@skywind3000 please describe clearly what you think is missing, else it looks like it could already be implemented.

**Comment by skywind3000** [comment]
I am using wildmenu now, but I think a popup for cmdline completion is more handy.

**Comment by brammool** [comment]
> > Is there a possibility of having a popup analogous to the 'wildmenu'?
> 
> do you want a popup or wildmenu? 
> 
> @skywind3000 please describe clearly what you think is missing, else
> it looks like it could already be implemented.

There is an item in the todo list that is related:

- Use popup (or popup menu) for command line completion

Currently there is 'wildmenu', but it only shows few matches.  Using a
popupmenu for that would be nicer.  A complication is that when the
command line has scrolled, redrawing the text under the menu might be
complicated.

-- 
I wonder, do vegetarians eat fruit bats?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
How about @h-east's [CLPUM](https://h-east.github.io/vim/) (Command-Line mode PopUp Menu)?

**Comment by skywind3000** [comment]
neovim's behavior:

1. before cmdline scroll:

![cmd1](https://user-images.githubusercontent.com/3035071/71775791-c2b42180-2fc1-11ea-98ef-5448c9ec67f2.png)

2. the filename is too long and makes cmdline scroll and extend to 2 lines:

![cmd2](https://user-images.githubusercontent.com/3035071/71775798-d19ad400-2fc1-11ea-92d2-76d488f348ad.png)

3. choose a short file name, it shrinks:

![cmd3](https://user-images.githubusercontent.com/3035071/71775814-1e7eaa80-2fc2-11ea-8d83-ba5f73eec5af.png)

4. when you made your selection, the cmdline restores to 1 line:

![cmd4](https://user-images.githubusercontent.com/3035071/71775822-322a1100-2fc2-11ea-9dd2-b4c26a66fbe1.png)

**Comment by skywind3000** [comment]
@k-takata , that's cool:

![](https://raw.githubusercontent.com/wiki/h-east/vim/images/clpumDemo02.gif)

but requires a patched vim:

![patch](https://user-images.githubusercontent.com/3035071/71775891-d6ac5300-2fc2-11ea-8e02-7b613950656d.png)

Hi @brammool , is it possible to just include this patch ?

**Comment by h-east** [comment]
CLPUM is currently unable to follow Vim's head.
We need to change to an implementation that uses popup-window inside Vim.

**Comment by blayz3r** [comment]
@h-east any progress on that

**Comment by skywind3000** [comment]
@h-east, people are expecting your patch or plugin all the time.

**Comment by poetaman** [comment]
@brammool +1

> There is an item in the todo list that is related: - Use popup (or popup menu) for command line completion Currently there is 'wildmenu', but it only shows few matches.

This would be a more intuitive feature to have. The current UI is a bit distracting with completion options taking over screen with each ``<Tab>`` keypress.
