### ISSUE TITLE
"vim --clean" writes unrecognized KS_CTE and KS_CTI on entering/exiting insert mode

### ISSUE THREAD

**Issue by esiegerman** [vim/vim#5436]
**Describe the bug**
In "vim --clean", entering insert mode (via "a", "i", or other variants) writes
"\E[>4;m" to the screen.  Exiting insert mode writes "\E[>4;2m".  Neither of
these is recognized by my terminal emulator; thus, they're both displayed,
garbling the screen contents.

(The escape sequences in question are the hard-coded default values of KS_CTE
and KS_CTI, respectively.)

Without "--clean", it's all good.  I presume that's because my terminfo entry overrides
the hard-coded defaults.

**To Reproduce**
1. Launch an xfce-terminal session
2. Run "vim --clean" in it
3. Type "a"; notice the garbage
4. Type &lt;ESC&gt;; notice the additional garbage

**Expected behavior**
No garbage.

**Environment (please complete the following information):**
 - Vim version: v8.2.0086
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: xfce4-terminal 0.6.3

**Additional context**
 - Bug was introduced in v8.1.2261

**Comment by brammool** [comment]
What is $TERM set to?  I don't know what xfce4 would use.  I guess it's "xterm", in which case Vim uses xterm termcodes.  If that doesn't work, then don't set $TERM the 'xterm".

**Comment by dpelle** [comment]
I use xfce4-terminal 0.8.7.4 from xubuntu-18.04.3 I don't see this problem, neither with `export TERM=xterm-256color` nor with `export TERM=xterm`.

Bug reporter uses xfce4-terminal 0.6.3 which is quite old.

**Comment by brammool** [comment]
Thus it's not a Vim problem, closing...
