### ISSUE TITLE
"win_splitmove()" makes Vim hang when invoked to move a window across different tab pages

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#5444]
**Describe the bug**

When invoking `win_splitmove()` to move a window across two tab pages, Vim hangs, and the cpu usage increases significantly (a full core on my machine).

**To Reproduce**

Run this shell command:

    vim -Nu NONE +tabnew +'call win_splitmove(1, win_getid(1,1))'

**Expected behavior**

1. if `win_splitmove()` can move a window across different tab pages, it successfully does it
2. if it can't, an error is raised to let the user know of this limitation
3. no matter whether it can or not, Vim does not hang, and the cpu usage does not increase significantly

**Environment**

 - Vim version:  8.2 Included patches: 1-90
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

When Vim hangs, I can't interact with it anymore, even if I press `C-c`; I have to `kill -9` it.

**Comment by lacygoill** [comment]
I've just noticed other unexpected behaviors.
For example, if you run this shell command:

    vim -Nu NONE +'tabnew|sp|sp|call win_splitmove(1, win_getid(1,1))'

One of the 3 splits is closed, and the cursor is drawn after the last line of the buffer (on a filler line prefixed by `~`).

**Comment by andymass** [comment]
I guess there is no way currently in vim to move a window from one tabpage to another existing tabpage.  Ideally this should be added, though I don't know the implementation work.
