### ISSUE TITLE
Broken Markdown syntax regarding italics

### ISSUE THREAD

**Issue by Flobaer** [vim/vim#5448]
**Bug description**
When writing italics in Markdown syntax (i. e. encased in single asterisks) in a Markdown file, the part afterwards is also stylized in italics, although it shouldn't be. This is a known bug in [vim-markdown](https://github.com/tpope/vim-markdown) documented in this [issue](https://github.com/tpope/vim-markdown/issues/151). It's already resolved in this [commit](https://github.com/tpope/vim-markdown/commit/e875717243fbea38189f5590a25a05809f03672b) but vim 8.2 comes packaged with an older version of vim-markdown.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Open a Markdown file with vim: `vim test.md`
2. Write something in italics and afterwards something else (not in italics):
```
*this is in italics*
this is also in italics but shouldn't be
```
3. The first line is correctly stylized in italics but the second line as well, even though it shouldn't

**Expected behavior**
The expected behaviour is that the first line should be stylized in italics and the second line shouldn't.

**Screenshots**
A screenshot can be seen [here](https://github.com/tpope/vim-markdown/issues/151) (uploading one of my own doesn't work for some reason).

**Environment:**
 - Vim version 8.2.0095 (manually compiled on 2020-01-06)
 - OS: Debian Buster (also happens with the packaged Vim version (8.2.0033) on Arch Linux)
 - Terminal: SSH to a Debian VM

**Additional context**
This is a known bug in [vim-markdown](https://github.com/tpope/vim-markdown) documented in this [issue](https://github.com/tpope/vim-markdown/issues/151). It's already resolved in this [commit](https://github.com/tpope/vim-markdown/commit/e875717243fbea38189f5590a25a05809f03672b) but vim 8.2 comes packaged with an older version of vim-markdown.

**Comment by tpope** [comment]
This doesn't need to be reported upstream. I will send along an updated version when I am confident in the fix.

**Comment by k-takata** [comment]
Closing for now.
