### ISSUE TITLE
"E967 text property info corrupted" reports via govim

### ISSUE THREAD

**Issue by myitcv** [vim/vim#5454]
**Describe the bug**

At this stage we do not have a minimal set of repro steps, but per https://github.com/govim/govim/issues/656 we know:

* Vim becomes totally unusable
* Using Vim with `govim` for ~5 mins results in `E967 text property info corrupted` errors

**To Reproduce**

Per https://github.com/govim/govim/issues/656#issuecomment-571622571 we are working on this. 

Is there any particular logging we can turn on to help diagnose this?

**Expected behavior**

No errors

**Screenshots**

n/a

**Environment (please complete the following information):**
 - Vim version [e.g. 8.1.1234] (Or paste the result of `vim --version`.)

```
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 12 2019 16:52:17)
macOS version
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_old_static
+arabic            +file_in_path      +mouse_urxvt       -tag_any_white
+autocmd           +find_in_path      +mouse_xterm       -tcl
+autochdir         +float             +multi_byte        +termguicolors
-autoservername    +folding           +multi_lang        +terminal
-balloon_eval      -footer            -mzscheme          +terminfo
+balloon_eval_term +fork()            +netbeans_intg     +termresponse
-browse            +gettext           +num64             +textobjects
++builtin_terms    -hangul_input      +packages          +textprop
+byte_offset       +iconv             +path_extra        +timers
+channel           +insert_expand     +perl              +title
+cindent           +job               +persistent_undo   -toolbar
-clientserver      +jumplist          +popupwin          +user_commands
+clipboard         +keymap            +postscript        +vartabs
+cmdline_compl     +lambda            +printer           +vertsplit
+cmdline_hist      +langmap           +profile           +virtualedit
+cmdline_info      +libcall           -python            +visual
+comments          +linebreak         +python3           +visualextra
+conceal           +lispindent        +quickfix          +viminfo
+cryptv            +listcmds          +reltime           +vreplace
+cscope            +localmap          +rightleft         +wildignore
+cursorbind        +lua               +ruby              +wildmenu
+cursorshape       +menu              +scrollbind        +windows
+dialog_con        +mksession         +signs             +writebackup
+diff              +modify_fname      +smartindent       -X11
+digraphs          +mouse             -sound             -xfontset
-dnd               -mouseshape        +spell             -xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        -mouse_gpm         +statusline        -xsmp
+eval              -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary        
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -lintl -framework AppKit  -L/usr/local/opt/lua/lib -llua5.3 -mmacosx-version-min=10.15 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.30.0/lib/perl5/5.30.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m -framework CoreFoundation  -lruby.2.6 
```

 - OS: [e.g. Ubuntu 18.04, Windows 10 1809, macOS 10.14]

macOS

 - Terminal: [e.g. GNOME Terminal, mintty, iTerm2, tmux, GNU screen] (Use GUI if you use the GUI.)

macOS version

**Additional context**

n/a

**Comment by brammool** [comment]
Paul Jolly wrote:

> **Describe the bug**
> 
> At this stage we do not have a minimal set of repro steps, but per https://github.com/govim/govim/issues/656 we know:
> 
> * Vim becomes totally unusable
> * Using Vim with `govim` for ~5 mins results in `E967 text property info corrupted` errors
> 
> **To Reproduce**
> 
> Per https://github.com/govim/govim/issues/656#issuecomment-571622571 we are working on this. 
> 
> Is there any particular logging we can turn on to help diagnose this?

Run Vim in a debugger, put a breakpoint at the error, wait until it runs
into the problem.  It's proabably just after some text change.

-- 
Citizens are not allowed to attend a movie house or theater nor ride in a
public streetcar within at least four hours after eating garlic.
		[real standing law in Indiana, United States of America]

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by myitcv** [comment]
Thanks - we'll report back with more details.

**Comment by brammool** [comment]
Please check if patch 8.2.0109 fixes this.

**Comment by myitcv** [comment]
Thanks Bram. I've echoed this request onto our issue.

**Comment by myitcv** [comment]
Thanks again, Bram. The user reported (https://github.com/govim/govim/issues/656#issuecomment-573089241):

> Everything is looking great so far in the updated version of vim. I'm going to close unless there's some evidence that the vim bug was not the root cause of the issue

So I'll close this (for now).

**Comment by laoshaw** [comment]
running vim 8.2.2269(ubuntu 20.04) with newest vim-go and I'm still seeing this once a while. I actually disabled coc.nvim as it renders too slow sometimes for me.

**Comment by chrisbra** [comment]
So how to reproduce?

**Comment by laoshaw** [comment]
Can't reproduce it reliably, it seems this happens when I use vim-go along with nerdtree plugin

**Comment by brammool** [comment]
> Can't reproduce it reliably, it seems this happens when I use vim-go
> along with nerdtree plugin

I'm afraid there is nothing we can do without a reproducible example.

-- 
Support your right to bare arms!  Wear short sleeves!

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
