### ISSUE TITLE
Vim creating empty buffers with `:new +buffer <id>` command

### ISSUE THREAD

**Issue by kassio** [vim/vim#546]
![vim_empty_buffer](https://cloud.githubusercontent.com/assets/120483/12078676/e1474270-b1f9-11e5-9324-e2591c0c71f3.gif)

**Comment by chrisbra** [comment]
That is expecting, since the point of the `:new` command is to create a new window with a new buffer. Use `:sp` if you don't want this.

**Comment by ZyX-I** [comment]
If you need to create a new window with a specific buffer, there is `:sbuffer`. `:new +b2` does exactly what advertized: creates new window with new buffer and _then_ switches to buffer 2.

**Comment by kassio** [comment]
Thank you, I really mislead this.

**Comment by ZyX-I** [comment]
@kassio In cases when there is no special command (e.g. there is no `:vbuffer` and there is no `:sterminal` in Neovim) you need to use `[v]split` followed by the command or command modifiers (i.e. `vertical sbuffer` in place of `vbuffer`; `:h :vertical` will open a list of them), it does not create anything. Everything is documented in `windows.txt`.
