### ISSUE TITLE
Some fail cases for text object tag block

### ISSUE THREAD

**Issue by jackysee** [vim/vim#5462]
**Describe the bug**
Tag block text object fail in some case

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean`
3. Paste this code
```

<div
    class="header"
    id="header"
>
    <div
        class="logo"
        id="logo"
    >
        <img src="logo.png" />
    </div>
</div>

<span class="dolorum atque aspernatur"
    ><a 
        href="abc"
        >Est molestiae sunt facilis qui rem.</a
    ></span
>

```
3. `vat` on the `div#header`
![image](https://user-images.githubusercontent.com/30516/72030971-e62ee300-32c5-11ea-897c-fed8a9c6ad68.png)

`vat` on the `span` and `a` has no effect

**Environment (please complete the following information):**
 - `VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 31 2019 13:33:38)`
 - OS: Windows 10 1909, WSL
 - Terminal: termite

**Comment by brammool** [comment]
The line break inside the end tag is not allowed.  There isn't a full html parser for this, it matches patterns and that has it's limits.  You better make this HTML look nicer and then it will work.

**Comment by jackysee** [comment]
It's the whitespace preserving format in the popular formatter, it has its rationale.

https://prettier.io/blog/2018/11/07/1.15.0.html#whitespace-sensitive-formatting

**Comment by jackysee** [comment]
Also the `vat` on the `div#header` is not selecting the right range too.

**Comment by dzonatan** [comment]
wow, it's so hard to believe that not so many faced with this issue so far.

prettier is very popular within web development community and the main idea behind it is to have one common style guide which cannot be altered. so there is no other option to make this HTML look "nicer" but to stop using it entirely which isn't the solution either.
