### ISSUE TITLE
Syntax for Make assignment

### ISSUE THREAD

**Issue by Boobies** [vim/vim#5464]
The ::= assignment should be treated the same as :=. It has been adopted by GNU Make already and has been accepted for POSIX Issue 8. Currently, it is not recognized by the syntax highlighting.

**Comment by chrisbra** [comment]
On Do, 09 Jan 2020, Bogdan Barbu wrote:

> The ::= assignment should be treated the same as :=. It has been adopted by GNU Make already and has been accepted for POSIX Issue 8.

Please contact the syntax file maintainer. Thanks.

**Comment by bogdan-barbu** [comment]
I did but he didn't answer.

**Comment by Boobies** [comment]
I did but he didn't answer.

**Comment by brammool** [comment]
Roland @rohieb was active a month ago,

**Comment by rohieb** [comment]
Yes, there was a fair share of life this week. I've read your mail and will handle it.

**Comment by chrisbra** [comment]
closing then.

**Comment by rohieb** [comment]
@Boobies I'm not sure what your request is. Currently we don't highlight the := in assigments at all, so changing this to ::= is a trivial no-op and should already be supported in your version of vim. :)

**Comment by Boobies** [comment]
FOO := foo
BAR ::= bar

For me, FOO gets highlighted whereas BAR does not. It's not the whole assignment, it's just that BAR doesn't seem to be recognized as a variable definition there.

Using vim 8.1 from the Debian package repository (but I don't think anyone wrote a patch for that).

**Comment by rohieb** [comment]
@Boobies Ahh, I see now. Please have a look if #5482 does what you want.
