### ISSUE TITLE
expand('%:p') sometimes out C:\ sometimes output c:\ in windows10

### ISSUE THREAD

**Issue by lymslive** [vim/vim#5466]
I really don't know which option will affect this.
The prefix driver such as 'C:' in `echo expand('%;p') sometimes uppercase and sometimes lowercase.
Or dose have any function to normalize this behavior?

gvim version 8.1, download from official site.

**Comment by k-takata** [comment]
When I tried this, `expand('%:p')` always returned the drive letter in uppercase.
Can you provide a reproducible way that return in lowercase?

**Comment by k-takata** [comment]
Ah, if I execute `cd /d c:\` on Command Prompt then execute Vim, `expand('%:p')` returns lowercase drive letter.
Vim doesn't normalize it. It depends on the drive letter of the current directory.

**Comment by lymslive** [comment]
Thank you, I know why this happend.
I have to handle it myself in plugin with viml script.

**Comment by chrisbra** [comment]
closing then.
