### ISSUE TITLE
vim 8.2.116 compilation : message_test.c :170 : test_vim_snprintf: assertion " n == 6 " failed

### ISSUE THREAD

**Issue by apollolune** [vim/vim#5478]
Hi,

When compiling Vim on Debian, I got the error in the title when running "make test".
I'm using the same configure for some years now on Linux and Mac OS X machines.
Mac OS X (Catalina flavor) passes the test, Debian fails.
- Debian machine is:
Eeepc 1005HA
Linux 5.3.0-3-686-pae Debian 5.3.15-1 i686
2 x Intel Atom CPU N270 @ 1,6GHz 32 bits
- configure is:
./configure --with-features=huge --enable-gui=no --enable-terminal --enable-python3interp=yes

It seem line 170 of src/message_test.c was added in patch 66 here:

https://github.com/vim/vim/commit/d2c946bacfedf4e506a4c6771758beddb87df3af

I've been having this for the last 2/3 weeks (I compile Vim every week on Linux and Mac OS), so the dates check (patch 8.2.0066 is two weeks old).
I'm not vimscript savvy, and, even if I started compiling vim years ago it's my first Issue report, so I probably don't give enough informations or some that are not needed.
Please tell me if anything else is needed, or if my message is even useful at all,
I deeply appreciate the work of the Vim community, it's my editor of choice for a life, a big 'Thank You' to all the people contributing,
Cheers,
Apol

**Comment by dpelle** [comment]
This same issue was just discussed today in the vim_dev
mailing list, with a proposed patch to fix it.  See:

https://groups.google.com/forum/#!topic/vim_dev/FXM986Qx49E

So I suppose that an official patch from @brammool will come soon now.

**Comment by k-takata** [comment]
Fixed by 8.2.0119 (https://github.com/vim/vim/commit/1470dc35c4b14bda1995b7566c9a41a33eb06517).
