### ISSUE TITLE
can not open vim in macos

### ISSUE THREAD

**Issue by neuronphysics** [vim/vim#5484]
I can not open `vim` in terminal in my macos laptop. I get this error:
```
dyld: Library not loaded: /usr/local/opt/perl/lib/perl5/5.30.0/darwin-thread-multi-2level/CORE/libperl.dylib
  Referenced from: /usr/local/bin/vim
  Reason: image not found
Abort trap: 6
```
Any suggestion why it is happening?

**Comment by chrisbra** [comment]
This looks like a self compiled version and it looks like you need Perl installed. You might also try to compile a version without perl interface.

**Comment by chrisbra** [comment]
I am closing this as this is a question and not about a bug. 
Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. Closing.
