### ISSUE TITLE
Include Swift syntax highlighting and filetype detection support

### ISSUE THREAD

**Issue by bitigchi** [vim/vim#5490]
AFAICS, Vim does not provide syntax highlighting/filetype detection support for Swift. It would be cool to have it bundled.

Apple provides support for Swift within Vim, which can be found [here](https://github.com/apple/swift/tree/master/utils/vim). Would there be a licensing conflict on including these files?

**Comment by brammool** [comment]
> AFAICS, Vim does not provide syntax highlighting/filetype detection support for Swift. It would be cool to have it bundled.
> 
> Apple provides support for Swift within Vim, which can be found [here](https://github.com/apple/swift/tree/master/utils/vim). Would there be a licensing conflict on including these files?

There is only a license file in the top directory, which is Apache 2.0.
That license is OK, but it should be clearer that it also applies to the
Vim files (and check that the author actually put that license on the
files).

Best is to contact the author (there is an email in the header) and ask
them to send the files to me.  That avoids any confusion.

-- 
ARTHUR: It is I, Arthur, son of Uther Pendragon, from the castle of Camelot.
        King of all Britons, defeator of the Saxons, sovereign of all England!
   [Pause]
SOLDIER: Get away!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bitigchi** [comment]
> Best is to contact the author (there is an email in the header) and ask them to send the files to me. That avoids any confusion.

I sent an e-mail, and CC'd you as well.

**Comment by bitigchi** [comment]
Closed (PR #5517).
