### ISSUE TITLE
status line do not update when opening windows

### ISSUE THREAD

**Issue by coot** [vim/vim#5496]
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Describe the bug**
Status line of non focused windows are not updated when a new window is opened but are updated when some window is closed.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean` (or `gvim --clean`, etc.)
2.
```
set statusline=%{winnr()}
set laststatus=2
```
3. now split window with '^ws', and now split windows vertically with '^wv'. Observe that there are now two windows with window number 2 in status line.  Note also that when spliting windows horizontally everything works fine.

**Expected behavior**
Status line of non focused windows should get updated regardless of the split one is using.

**Screenshots**
![Screencast](https://user-images.githubusercontent.com/698209/72670350-b35eba80-3a3c-11ea-96bd-cdb1b7d69df7.gif)

**Environment (please complete the following information):**
 - Vim version
vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 14 2020 21:23:40)
Included patches: 1-118
Compiled by coot@fozzie
Huge version with GTK2 GUI.  Features included (+) or not (-):
 - OS:Debian bullseye/sid
 - Terminal: GNOME Terminal

**Comment by lacygoill** [comment]
I can reproduce too with these commands:

    vim -Nu NONE +'set ls=2 stl=%{winnr()}'
    :sp
    :vs

But for some reason, the issue disappears if `'splitbelow'` is set:

                                           vv
    vim -Nu NONE +'set ls=2 stl=%{winnr()} sb'
    :sp
    :vs

**Comment by lacygoill** [comment]
> But for some reason, the issue disappears if `'splitbelow'` is set:

Although, the issue seems to persist if you reverse the order of the splitting commands:

    vim -Nu NONE +'set ls=2 stl=%{winnr()} sb'
    :vs
    :sp

But in that case, if you set `'splitright'` in addition to `'splitbelow'`, then the issue disappears no matter the order:

    vim -Nu NONE +'set ls=2 stl=%{winnr()} sb spr'
    :vs
    :sp

    vim -Nu NONE +'set ls=2 stl=%{winnr()} sb spr'
    :sp
    :vs

**Comment by lacygoill** [comment]
Ah, I can reproduce even with `'splitright'` and `'splitbelow'` set; e.g. with the `:topleft` modifier:

    vim -Nu NONE +'set ls=2 stl=%{winnr()} sb spr'
    :to sp
    :vs

But not if the commands are joined with a bar:

    vim -Nu NONE +'set ls=2 stl=%{winnr()} sb spr'
    :to sp | vs

**Comment by lacygoill** [comment]
As a temporary workaround, maybe `:redrawstatus` could be executed from an autocmd listening to `WinNew`:

    vim -Nu NONE +'set ls=2 stl=%{winnr()} | au WinNew * redraws'

**Comment by lifecrisis** [comment]
Greetings:

This test captures the essence of the problem...

```
diff --git a/src/testdir/test_statusline.vim b/src/testdir/test_statusline.vim
index f73998a67..c138ff0fb 100644
--- a/src/testdir/test_statusline.vim
+++ b/src/testdir/test_statusline.vim
@@ -433,4 +433,20 @@ func Test_statusline_removed_group()
   call delete('XTest_statusline')
 endfunc
 
+func Test_statusline_after_split_vsplit()
+  only
+
+  " Make the status line of each window show the window number.
+  set ls=2 stl=%{winnr()}
+
+  split | redraw
+  vsplit | redraw
+
+  " The status line of the third window should read '3' here.
+  call assert_equal('3', nr2char(screenchar(&lines - 1, 1)))
+
+  only
+  set ls& stl&
+endfunc
+
 " vim: shiftwidth=2 sts=2 expandtab
```

I found that the function responsible for splitting windows will only update the status line of a window and its "offspring" after a split command (e.g,, `:split` or `:vsplit`).  I think Vim will also update the status lines of any windows that are resized as a side effect of the split.  If a window is not resized and is not the old window or the new window, it will not be redrawn, and its status line will not be updated.  The tab line, I found, is updated correctly.

This patch, in my opinion, is the correct way to fix the issue in future versions of Vim.  It marks status lines of other windows to be redrawn in all cases.  The content of another window need not be redrawn if its dimensions aren't changed after a split. See below...

```
diff --git a/src/window.c b/src/window.c
index c73062ddd..cee3674f9 100644
--- a/src/window.c
+++ b/src/window.c
@@ -1273,13 +1273,11 @@ win_split_ins(
     if (flags & (WSP_TOP | WSP_BOT))
 	(void)win_comp_pos();
 
-    /*
-     * Both windows need redrawing
-     */
+    // Mark the split windows to be redrawn.
     redraw_win_later(wp, NOT_VALID);
-    wp->w_redr_status = TRUE;
     redraw_win_later(oldwin, NOT_VALID);
-    oldwin->w_redr_status = TRUE;
+    // Status lines may show, e.g., window numbers.  Mark them to be redrawn.
+    status_redraw_all();
 
     if (need_status)
     {
```

Best,
Jason Franklin

**Comment by lifecrisis** [comment]
**Minor correction:** The content of another window need not be redrawn if its dimensions **and position** aren't changed after a split.
