### ISSUE TITLE
Stuck In Insert Mode

### ISSUE THREAD

**Issue by fffailed** [vim/vim#5497]
_Instructions: Unable to exit insert mode_

**Screenshots:**
![vim_case_v4 - 01](https://user-images.githubusercontent.com/12459641/72676616-282e0500-3ace-11ea-8632-b53ad2077127.gif)

**Environment:**
 - Vim: [8.1.1]
 - OS: [macOS Mojave 10.14.5]
 - Terminal: [Terminal.app]
 - Shell: [zsh + ohmyzsh]

**Vim --version:**
[vim_version.txt](https://github.com/vim/vim/files/4082355/vim_version.txt)

**Additional context**
[bugVim.log](https://github.com/vim/vim/files/4082351/bugVim.log)

**Comment by k-takata** [comment]
Try executing vim with `vim --clean` first. If it works fine, the issue is caused by your configuration and/or plugins.

**Comment by fffailed** [comment]
> Try executing vim with `vim --clean` first. If it works fine, the issue is caused by your configuration and/or plugins.

`vim --clean` works fine, How to find it

**Comment by fffailed** [comment]
I found it

```
function! XTermPasteBegin()
  set pastetoggle=<Esc>[201~
  set paste
  return ""
endfunction
inoremap <special> <expr> <Esc>[200~ XTermPasteBegin()
```

**Comment by tonymec** [comment]
With no change, `CTRL-\ CTRL-N` should bring you in Normal mode from any other mode without using the `<Esc>` key, thus also if there is an interfering mapping starting with `<Esc>` (or with `CTRL-[`, which is identical to `<Esc>` for Vim).

See `:help CTRL-\_CTRL-N`

Best regards,
Tony

**Comment by jericopulvera** [comment]
@fffailed how did you fix it? where do you add that code block?

I'm having the same exact issue. https://github.com/neovim/neovim/issues/19783#issuecomment-1420103980

**Comment by fffailed** [comment]
@jericopulvera 

I removed this code

This code causes the problem

> I found it
> 
> ```
> function! XTermPasteBegin()
>   set pastetoggle=<Esc>[201~
>   set paste
>   return ""
> endfunction
> inoremap <special> <expr> <Esc>[200~ XTermPasteBegin()
> ```

**Comment by jericopulvera** [comment]
Where did you find it?


> @jericopulvera
> 
> I removed this code
> 
> This code causes the problem
> 
> > I found it
> > ```
> > function! XTermPasteBegin()
> >   set pastetoggle=<Esc>[201~
> >   set paste
> >   return ""
> > endfunction
> > inoremap <special> <expr> <Esc>[200~ XTermPasteBegin()
> > ```
