### ISSUE TITLE
Update builtin syntax files

### ISSUE THREAD

**Issue by KiYugadgeter** [vim/vim#550]
Some builtin syntax files do not support latest version syntax.
For example, Template string (ES2015), async/await (Python3), and so on.
some file is too old.
Please update it!

**Comment by chrisbra** [comment]
Hi KiYugadgeter!

On Mi, 06 Jan 2016, KiYugadgeter wrote:

> Some builtin syntax files do not support latest version syntax
> For example, Template string (ES2015), async/await (Python3), and so on
> some file is too old
> Please update it!

Please contact the maintainer of each syntax file.

Best,

## Christian

Ich weiß zwar nicht, was du willst - aber ich werde mich trotzdem beeilen.
  -- Dein Computer

**Comment by zvezdan** [comment]
async/await is available in the Python syntax file.
See here: https://github.com/vim/vim/blob/master/runtime/syntax/python.vim#L84

Are you actually using the updated files?
