### ISSUE TITLE
Status line objects duplicate when sourcing .vimrc with vim running

### ISSUE THREAD

**Issue by bitigchi** [vim/vim#5502]
Vim vanilla status bar objects duplicate when sourcing .vimrc with vim running.

To reproduce:
- Open .vimrc
- :source %

Expected behaviour:
- Status bar objects should reload instead of multiplying

This is the status bar
![vim status bar](https://user-images.githubusercontent.com/2769571/72687024-4108db80-3b0b-11ea-852b-087395c27825.png)

And this is when .vimrc sourced
![vim status bar reloaded](https://user-images.githubusercontent.com/2769571/72687036-5aaa2300-3b0b-11ea-9f2b-045bffb5852c.png)

This is my status bar configuration:
```
 set statusline+=[%n]
 set statusline+=\ %f
 set statusline+=\ %m
 set statusline+=%=
 set statusline+=%#CursorColumn#
 set statusline+=\ %y
 set statusline+=\ %{&fileencoding?&fileencoding:&encoding}
 set statusline+=\ [%{&fileformat}\]
 set statusline+=\ %p%%
 set statusline+=\ %l:%c
```

Vim 8.2.132
macOS 10.15.2
iTerm2 3.3.7

**Comment by lacygoill** [comment]
Clear the option before appending items:

    " clear option
    set statusline=

    " append items
    set statusline+=[%n]
    set statusline+=\ %f
    set statusline+=\ %m
    set statusline+=%=
    set statusline+=%#CursorColumn#
    set statusline+=\ %y
    set statusline+=\ %{&fileencoding?&fileencoding:&encoding}
    set statusline+=\ [%{&fileformat}\]
    set statusline+=\ %p%%
    set statusline+=\ %l:%c

Or wrap the settings inside an `if has('vim_starting')` guard:

    if has('vim_starting')
        set statusline+=[%n]
        set statusline+=\ %f
        set statusline+=\ %m
        set statusline+=%=
        set statusline+=%#CursorColumn#
        set statusline+=\ %y
        set statusline+=\ %{&fileencoding?&fileencoding:&encoding}
        set statusline+=\ [%{&fileformat}\]
        set statusline+=\ %p%%
        set statusline+=\ %l:%c
    endif

**Comment by tonymec** [comment]
Indeed, if you set the `'statusline'` option (or any option for that matter) using only `+=` between the option name and the value, you will append to whatever the value was immediately before, not to the default setting.

I set it using only one `:set` statement, but the inconvenient is that it means a rather long line (109 characters), as follows (if you read this on github, use the horizontal scrollbar to see it all):
```vim
if has('statusline')
  set statusline=%<%f\ %h%m%r%=%k[%{(&fenc==''?&enc:&fenc)}%{(&bomb?',BOM':'')}][U+%04B]\ %-14.(%l,%c%V%)\ %P
endif
```
Best regards,
Tony.

**Comment by bitigchi** [comment]
@lacygoill thanks for the workarounds. I went ahead with clearing the status line, since second option will not refresh the status line until vim is relaunched.

With that said, I'm not sure if this still counts as a bug, maybe a very trivial one.

**Comment by bitigchi** [comment]
@lacygoill thanks for the workarounds. I went ahead with clearing the status line, since second option will not refresh the status line until vim is relaunched.

With that said, I'm not sure if this still counts as a bug, maybe a very trivial one.

**Comment by tonymec** [comment]
> @lacygoill thanks for the workarounds. I went ahead with clearing the status line, since second option will not refresh the status line until vim is relaunched.
> 
> With that said, I'm not sure if this still counts as a bug, maybe a very trivial one.

No it's not a bug, it's a feature. Sourcing the `.vimrc` again does not reset all options to their defaults, it leaves them as they are. So if you append without clearing, it will append again.

Best regards,
Tony.

**Comment by bitigchi** [comment]
@tonymec makes sense. Closing.
