### ISSUE TITLE
multi-line syntax pattern: rescan/redraw after changes below the first line not supported?

### ISSUE THREAD

**Issue by tom-m** [vim/vim#5518]
**Describe the bug**
The starting line(s) of a group of lines that were matching a multi-line syntax pattern is not redrawn to reflect a change of the last line of the group that makes them not match the pattern anymore. Only the changed line and the lines below it are redrawn upon the change. This happens even with `:syntax sync fromstart` which (as stated at `:help :syn-sync-first`) should make "[the syntax highlighting accurate](https://vimhelp.org/syntax.txt.html#%3Asyn-sync-first)".

**To Reproduce**
1. Create a file `test.txt` with the following lines:
`< comment?`
`-->`
2. Start Vim with: `vim --clean test.txt`
3. Setup syntax synchronizing with: `:syntax sync fromstart`
4. Setup a multi-line syntax pattern and let it's highlighting look like comment with:
`:syntax match m /<.*\n-->/`
`:hi link m Comment`
5. Check that the lines are colored as a comment (turquoise in my current setup).
6. Now type `gg0jf>` to place the cursor on the `>` char and change it to `x` with `rx`.
7. Check that the second line is redrawn as a normal text (white on black for me) to reflect the fact that the lines do not match the pattern anymore. But note that the first line is not redrawn and is still displayed in the color of a comment (torquoise for me).
8. Press `CTRL-L`.
9. Confirm that the lines really do not match the pattern any more: the whole screen is redrawn and both lines are now colored as normal text.

**Expected behavior**
Both lines should be colored as normal text immediately after step 6.

**Screenshots**
Can be provided if needed.

**Environment (please complete the following information):**
 - Vim 8.2.52. Huge version with GTK2 GUI.
 - OS: Debian 10 GNU/Linux
 - Terminal: GNOME Terminal

**Additional context**
This is a follow up of the discussion on vim_use mailing list. See "[automatic redraw for multi-line syntax highlighting patterns](https://groups.google.com/d/topic/vim_use/wUBLvNQ6hw4/discussion)".

**Comment by tom-m** [comment]
Correcting step 4 due to an error in the pattern. It was not brought up tu date with the actual content of the file:

4. Setup a multi-line syntax pattern and let it's highlighting look like comment with:
`:syntax match m /<.*\n-->/`
`:hi link m Comment`

**Comment by brammool** [comment]
Very similar problem as #8103, closing this one.
