### ISSUE TITLE
mode() and mode(1) on linux/unix

### ISSUE THREAD

**Issue by jerome-diver** [vim/vim#5525]
**Describe the bug**
vim function "mode()" doesn't return what vim manual (through :help) said. insert mode return "n", visual mode return "n", etc...
and mode(1) doesn't return full named mode, as manual explain.

**To Reproduce**
In linux (archlinux there) use function mode() in vimscript from gvim, vim terminal from urxvt, termite xterm, etc... and see the result at any vim mode.

**Expected behavior**
read :help mode() and hope to get what it has to do.
**Environment (please complete the following information):**
 - Vim-8.2
 - OS: archlinux
 - Terminal: GNOME Terminal, tmux, termite, xterm, urxvt, and same for gvim.

**Comment by k-takata** [comment]
How do you call mode()?
The help says:

```
		This is useful in the 'statusline' option or when used
		with |remote_expr()| In most other places it always returns
		"c" or "n".
```

**Comment by jerome-diver** [comment]
Hi @k-takata, thank you to try to help me.
i try this: https://gist.github.com/jerome-diver/b96efb9600bf613aa59683bb2f5f090f
i don't understand this "statusline" and "remote_expr() story.
Where i can learn what does it mean ? (totaly new on vimscript, and try to build a script for gigabyte rgb keyboard to publish on github)

**Comment by chrisbra** [comment]
> i try this: https://gist.github.com/jerome-diver/b96efb9600bf613aa59683bb2f5f090f

That is not particular helpful. So please be precise how you run the `mode()` function. The thing is, usually, when you use `:echo mode()`, to be able to run the `mode()` function, vim will be in normal or command line mode, that's why it will usually return `c` or `n`. Therefore, the `mode()` function is more useful when called from the statusline expression or when using the `remote_expr()` functionality (Please follow the help links).

So please be precise on what you expect and what you see. Thanks.

BTW: Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here.

**Comment by jerome-diver** [comment]
i'm trying to do a script to call ruby code for setup a rgb color keyboard's keys in relation with vim mode (and maybe next step would depend of motion state).
I was thinking that a software who can not provide what is official manual explain has bugs and that should be great to increase his ability to do what it should. I may be thinking wrong...

**Comment by chrisbra** [comment]
please be precise and show how you called mode().

**Comment by jerome-diver** [comment]
@chrisbra ok, i just copy/paste the line where i call mode() from my script (the one i linked there):
```
let s:vim_mode = mode(1)
```
i understand i have to call mode() from "remote_expr()" functionality, but i don't understand how i have to use it.
Could you, please, be precise and explicit by write an example code who use "remote_expr()", the way i can adapt mode() functionality to use with ?
thank you

**Comment by jerome-diver** [comment]
@chrisbra if you feel i was not precise by provide the full code and then a copy/paste of the line who call mode(), please try to explain precisely what can be more precise than the code used ?

**Comment by chrisbra** [comment]
The thing is, the way you are calling `mode()` is exactly what the help mentions. It won't give you the real mode(). I suggest thinking about what you want to achieve and how. I think `mode()` might not be correct here, perhaps better it is to use the `SafeState` autocommand. 

BTW: `remote_expr()` is a way to send an expression from outside of vim to a Vim server and return the result. Most likely not what you want. 

Anyhow, it looks like you are having some user questions. 
Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. Closing.

**Comment by k-takata** [comment]
Looking at the implementation in edit.c, the `InsertEnter` autocommand is executed before the `State` variable is changed to "i". So `mode()` in `InsertEnter` returns "n". I'm afraid that "fixing" the current implementation may break something.

As your script shows, you can distinguish current mode by autocommands.

**Comment by jerome-diver** [comment]
@chrisbra ok, i understand better. I thinking it was a bug at first due to the functionality it has to deserve, but it is not because of the context.
I will ask at better place then.
Thank you
@k-takata i will have a look on that way. Thank you.
