### ISSUE TITLE
Only partial highlighting in latex if command starts with `\cite` or `\citep`

### ISSUE THREAD

**Issue by lassepe** [vim/vim#5529]
**Description**

For some cases, the latex syntax highlighting only highlights parts of the command. This seems to happen if the the first part of the command is a known keyword.

**Reproduce**

In vim with `syntax on`:

1. `\cite` is highlighted correctly while in `\citeauthor`, only the "\cite"-part is highlighted:

![image](https://user-images.githubusercontent.com/10076790/73059690-8ecc6d80-3e96-11ea-957c-86bcfceb3f25.png)

2. `\citep` is picked up in any (potentially user defined macro) command starting with that phrase, e.g. `\citepfoobar` would only result in a highlighting of `\citepfoobar`.

![image](https://user-images.githubusercontent.com/10076790/73059724-9c81f300-3e96-11ea-8416-398f9d35b6a6.png)

**Environment:**
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan  7 2020 22:53:41)
Included patches: 1-100
Compiled by Arch Linux
```

**Comment by k-takata** [comment]
Cc: @cecamp

**Comment by cecamp** [comment]
Please try syntax/tex.vim version 116a; you can get it from [my website](http://www.drchip.org/astronaut/vim/index.html#SYNTAX_TEX).  Also, you're more likely to get my attention earlier by sending an email to me directly (which you can get in in the syntax/tex.vim file itself).

**Comment by k-takata** [comment]
> (which you can get in in the syntax/tex.vim file itself)

Your email address in tex.vim looks old.
