### ISSUE TITLE
text properties applied differently than matchaddpos

### ISSUE THREAD

**Issue by bhcleek** [vim/vim#5533]
**Describe the bug**
Highlighting using matchaddpos() and propadd() interacts differently with syntax highlighting

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Open a file and add three lines of text.
1. Set `Search` highlight group to `term=reverse cterm=reverse ctermfg=3 guifg=Black guibg=Yellow`
1. Set `Cursorline` highlight group  to `cterm=bold,underline,nocombine ctermbg=8                    gui=bold,underline,nocombine guibg=bg`
1. Create a property type using `prop_type_add()` that uses the Search highlight group.
1. Use `matchaddpos()` to highlight a position on the second line.
1. Use `prop_add()` to highlight a position on the third line.
1. Navigate to each line.

**Expected behavior**
The highlighting on the second line should be the same as the highlighting on the third line.

**Screenshots**
![recording](https://user-images.githubusercontent.com/1958864/73186043-fd4a3f00-40d3-11ea-8828-568b9b906c8f.gif)

**Environment (please complete the following information):**
 - Vim version:
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan  8 2020 00:57:57)
macOS version
Included patches: 1-100
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_old_static
+arabic            +file_in_path      +mouse_urxvt       -tag_any_white
+autocmd           +find_in_path      +mouse_xterm       -tcl
+autochdir         +float             +multi_byte        +termguicolors
-autoservername    +folding           +multi_lang        +terminal
-balloon_eval      -footer            -mzscheme          +terminfo
+balloon_eval_term +fork()            +netbeans_intg     +termresponse
-browse            +gettext           +num64             +textobjects
++builtin_terms    -hangul_input      +packages          +textprop
+byte_offset       +iconv             +path_extra        +timers
+channel           +insert_expand     +perl              +title
+cindent           +job               +persistent_undo   -toolbar
-clientserver      +jumplist          +popupwin          +user_commands
+clipboard         +keymap            +postscript        +vartabs
+cmdline_compl     +lambda            +printer           +vertsplit
+cmdline_hist      +langmap           +profile           +virtualedit
+cmdline_info      +libcall           -python            +visual
```
 - OS: macOS 10.15.2
 - Terminal: tmux in iTerm2

**Comment by andymass** [comment]
The second argument to matchaddpos is supposed to be a list of lists. E.g. [[2,1,10]]

**Comment by bhcleek** [comment]
That was my mistake in the bug report, but doesn't materially affect the described behavior. I've updated the screen recording.

**Comment by brammool** [comment]
Can you please type the commands?  I don't like grabbing them from the screenshot (how do you pause it?)

**Comment by bhcleek** [comment]
Here's a quick script to set the `CursorLine` and `Search` highlight groups, append some lines to a new buffer, and set the highlighting for the second line using `matchaddpos()` and the highlighting for the second line using `prop_add()`:

```
call append(0, ['This is some text', 'This is highlighted with matchpos', 'This is highlighted with prop_add()'])
highlight CursorLine cterm=bold,underline,nocombine ctermbg=8 gui=bold,underline,nocombine guibg=bg
highlight Search term=reverse cterm=reverse ctermfg=3 guifg=Black guibg=Yellow
hi def link test Search
call prop_type_add('test', {'highlight': 'test'})
call matchaddpos('test', [[2,1,10]])
call prop_add(3, 1, {'type':'test', 'length':10})
```

**Comment by brammool** [comment]
The way colors are combined for a match and a text property is different.  That by itself is not a bug.  Your highlight includes "reverse", which is always tricky, especially if also a background or foreground color is specified.  Vim doesn't really know what you are doing then.  With this example I can't decide if it is right or wrong.

**Comment by bhcleek** [comment]
🤔 Why do they combine differently and how would one know that text properties and matches are combined differently? I've looked through the docs, but can't find any mention of how and why they might differ, so my expectation was that text properties would combine with syntax highlighting as matches do.

Can you provide any guidance on how I could construct the text property highlight group so that it could result in the same thing that the match does in the example I provided?

Thanks for all you do, Bram!

**Comment by bhcleek** [comment]
I took another look at the help file, and based on its text, I am even more confused by the answer provided 

First, we have this description for text properties:
```
The main use for text properties is to highlight text.  This can be seen as a
replacement for syntax highlighting.  Instead of defining patterns to match
the text, the highlighting is set by a script, possibly using the output of an
external parser.  This only needs to be done once, not every time when
```

And then there's the `combine` attribute on text properties:
```
"combine"	when omitted or TRUE the text property highlighting is
       		combined with any syntax highlighting; when FALSE the
         	text property highlighting replaces the syntax
	        highlighting
```

And finally, this statement from the documentation for `matchadd()`:
```
Syntax highlighting (see 'syntax') is a separate mechanism, and regardless of the chosen priority a match will always overrule syntax highlighting.
```

Based on those three pieces of information, I would expect that setting `combine: 0` on the text property would cause the highlighting for the text property to behave as it would for matches, but I've tried that without success.

🤔
