### ISSUE TITLE
doc: v:event: clarify that it depends on the event

### ISSUE THREAD

**Issue by blueyed** [vim/vim#5535]
`:h v:event` currently says:

```
					*v:event* *event-variable*
v:event		Dictionary containing information about the current
		|autocommand|.  The dictionary is emptied when the |autocommand|
		finishes, please refer to |dict-identity| for how to get an
		independent copy of it.
```

This does not make it clear that this depends on the event, and often is empty.

Neovim's help is clearer in this regard: https://github.com/neovim/neovim/blob/3fa5946ab5e129bf47369d05ee96bd4b838e8764/runtime/doc/eval.txt#L1566-L1567

Related: https://github.com/vim/vim/issues/4232, which might add "name"  (or similar) there then always.

**Comment by chrisbra** [comment]
How about a doc patch?

**Comment by blueyed** [comment]
@chrisbra Patches/PRs do not get merged directly anyway here, and the above somehow contains a patch already (the extra info used in Neovim).
Also it is not clear to me how much info Vim / Bram wants to have there etc.
Therefore I do not think it makes sense to post a complete patch/PR.

**Comment by chrisbra** [comment]
It's an issue, issue can never be merged directly. However a proposed doc patch is always appreciated.

**Comment by lacygoill** [comment]
Possibly fixed by https://github.com/vim/vim/commit/560979ed4f0216f902a2c247e937f00a27dcb198, where this sentence was added at `:h v:event`:

https://github.com/vim/vim/blob/0353f56ddb379e7f1a68172fa4743355e04df21e/runtime/doc/eval.txt#L1890-L1891
