### ISSUE TITLE
Syntax highlighting error with initializer lists in CUDA 

### ISSUE THREAD

**Issue by gridley** [vim/vim#5540]
### Actual behaviour

Should not get error-style highlighting on initializer lists when writing cuda code. This appears as follows:

![2020-01-26-134042_563x103_scrot](https://user-images.githubusercontent.com/18088906/73139950-7f3d5800-4041-11ea-955e-3ac0b59a9d7f.png)

### Expected behaviour

Not red whenever I use an initializer list.

### To reproduce

Using the latest neovim 0.5 (the issue is rooted in vim, however), open any .cu file, and paste in:

```c++
int main()
{
   std::vector<double>({1.0, 2.0});
}
```

or the like. Then you get red error highlighting, even though nothing is wrong.

**Comment by k-takata** [comment]
The CUDA syntax file is sourcing `cpp.vim` and `c.vim`. So, the syntax settings for C/C++ also apply to CUDA.
How about doing `let g:c_no_curly_error = 1`? (See `:help c_no_curly_error`.)

**Comment by gridley** [comment]
Thanks @k-takata for the hint. This indeed removes the red highlighting from the curly bracket, but leaves the red highlighting on the second parenthesis. The odd thing about this is that if I open the file as a .C instead, the red highlighting goes away entirely even without setting the option you proposed above. So it's something that cuda.vim is causing, somehow. I looked at it and have no clue how this could arise...

**Comment by chrisbra** [comment]
I cannot confirm. I just tested it with your example and `:let g:c_no_curly_error=1` and saw no red highlighting anymore.

     vim --clean --cmd ':let g:c_no_curly_error=1' foobar.cu

**Comment by gridley** [comment]
Well, I suppose this must be a neovim issue then. Thanks @chrisbra

**Comment by chrisbra** [comment]
you can always try with the runtime files from Vim, if you cannot test directly with the latest Vim.

**Comment by chrisbra** [comment]
closing then.
