### ISSUE TITLE
Visual glitchs / artifacts on MS Windows GVim

### ISSUE THREAD

**Issue by harg** [vim/vim#5549]
**Describe the bug**
Visual artifacts/glitchs appear when inputing some characters on MS Windows Gvim

**To Reproduce**
1. Run gvim `gvim --clean`
2. Change font to consolas `:set guifont=Consolas:h11`
2. Change colorscheme to slate `:colo slate`
3. Type '@@' and then put your cusor between the two @ and insert some spaces
4. You can see the visual glitchs in blue

**Screenshot**
![image](https://user-images.githubusercontent.com/34398/73259169-770f2500-41c7-11ea-9a79-13a758363583.png)

**Expected behavior**
No visual artifacts/glitchs when inputing characters

**Environment**
 - Vim version : 8.2.0.158 x64
 - OS: Windows 10
 - gvim

**Additional context**
It can be reproduced on several windows machines.
Artifacts are gone with a `:redraw` 
`:set renderoptions=type:directx` does not fix the problem.
Same problem with Vim x86.
Same problem with different widely used fonts (Fira Code, ...).

**Comment by chrisbra** [comment]
Interesting, I thought the `linespace` option might influence this, but it actually doesn't matter.

**Comment by rksouthee** [comment]
I've noticed this being an issue when using a dark colorscheme. I've had issues when using Dark Blue, Slate and Apprentice.

**Comment by nir9** [comment]
This is not only on Windows, it also happens on gvim gtk

**Comment by determin1st** [comment]
![photo_2021-10-29_01-03-28](https://user-images.githubusercontent.com/16524081/140565940-80cab0d8-8e9d-4b09-9963-a6c5210742d0.jpg)

**Comment by chrisbra** [comment]
does it happen with other fonts?

**Comment by determin1st** [comment]
@chrisbra no, only with this "Comic Mono" https://dtinth.github.io/comic-mono-font/

**Comment by harg** [comment]
Any progress on this issue?

**Comment by chrisbra** [comment]
isn't this a font issue?

**Comment by harg** [comment]
I don't think so happen with a lots of font : Monaco, Roboto Mono, ...

**Comment by determin1st** [comment]
With Monaco font, it doesn't produce artifacts for me..

**Comment by harg** [comment]
Can you share tour version of Monaco, because mine glitches :
![image](https://user-images.githubusercontent.com/34398/152647980-98b9533b-9a47-4633-9bba-f1dcc5f138b9.png)

**Comment by determin1st** [comment]
Im not sure if it's legal to share fonts here. I says Monaco v.2.0 Apple in file monaco.ttf properties
