### ISSUE TITLE
Long lines make VIM slow but...

### ISSUE THREAD

**Issue by Deluxo** [vim/vim#555]
Hello.

As everybody knows already, long lines make vim slow.

However, recently I have found the synmaxcol variable.
It makes vim much more responsive, as you may already know.

The interesting part is this:
- vimrc has synmaxcol=256
- open file with a long line (its all fine. Vim's fast)
- :set syntax=on
  -set synmaxcol=9999

Result:
Vim is still much faster than without synmaxcol, although not as fast as without syntax highlighting.

Also, if i set synmaxcol, the long line that exeeds the limit stops being highlighted, and the next lines aren't highlighted properly any more, i.e. after a long line, highlighting is broken and off-sync.

**Comment by chrisbra** [comment]
> Also, if i set synmaxcol, the long line that exeeds the limit stops being highlighted, and the next lines aren't highlighted properly any more, i.e. after a long line, highlighting is broken and off-sync.

That is to be expected.

However I don't understand what this issue is for. Please discuss user questions at the vim-use ml. Closing.

**Comment by Deluxo** [comment]
The issue lies in the chain of settings in exactly this order:
syntax=on - slow
synmaxcol=200 - parts of text syntax highlighting messes up after the long line, but is fast
syntax=on - turning on full syntax highlighting again, only this time it's almost as fast as with synmaxcol=200, however even long lines are properly colored.

It's is not a bug per se, but a very awkward behaviour at minimum.

**Comment by ocehugo** [comment]
@chrisbra, I can also confirm the behaviour described  by @Deluxo. Using the kludge of setting synmaxcol to a high value and calling syntax on again  make scrolling faster. Can you explain why?

I have syntax on on my vimrc and editing latex files with synmaxcol really large make it much slower. doing @deluxo kludge make things much better (not super fast but fine for text editing).

Cheers

**Comment by vim-ml** [comment]
Am 2016-03-03 10:25, schrieb Hugo Oliveira:

> @chrisbra [1], I can also confirm the behaviour of @Deluxo [2]. Using
> the kludge of setting synmaxcol to a high value and calling syntax on
> again make scrolling faster. Can you explain why?

Please discuss this on the vim-use ml. This is no user support forum 
here.

**Comment by Deluxo** [comment]
This is also not a place to describe a bug..?
