### ISSUE TITLE
ftplugin/c.vim does not define 'commentstring', 'include', 'define' and 'path' option

### ISSUE THREAD

**Issue by ghost** [vim/vim#5556]
The c filetype plugin does not define values for the options

* 'commentstring'
* 'define'
* 'include'
* 'path'

but relies on the global setting to be C-conformant (which the default settings are).

Other filetype plugins for formats which also use the C-syntax (such as ftplugin/xdefault.vim) set these options explicitly, e.g.

```
setlocal include&
```

I suggest setting the above mentioned options in the c filtype plugin such that a users can safely override these options globally in their vimrc without reducing the functionality of the C filetype plugin, e.g.

```
setlocal commentstring&
setlocal define&
setlocal include&
setlocal path&
```

Workaround for people who set 'define' to something different in their vimrc:
Add ```setlocal define&``` to the file after/ftplugin/c.vim (create if necessary).

**Comment by brammool** [comment]
Makes sense.  However, 'path' should be left alone, it's unlikely the default value works better.
