### ISSUE TITLE
Tabs adjacent to concealed characters are displayed wider than a single tabstop

### ISSUE THREAD

**Issue by sedm0784** [vim/vim#5559]
When you conceal the characters directly before a tab, the tab is displayed wider than a tabstop.

**To Reproduce:**

1. Run `vim --clean`
2. Enter the following commands:

       :syntax match HideTwoIndents /\v^\t(\t)?/ conceal
       :syntax match HideTwoIndents /\v^z(z)?/ conceal
       :set conceallevel=2 concealcursor=n tabstop=2 list listchars=

3. Enter the following three lines into a buffer:

       <tab><tab><tab>ThreeTabs
       zz<tab>ZZTab
       ^^^^^^

   The start of each line is concealed as expected, so the buffer displays as:

       ^IThree tabs
       ^IZZTab
       ^^^^^^

4. Run the command: `:set listchars+=tab:xy`

   **Expected behavior**: The buffer should display as:

       xyThreeTabs
       xyZZTab
       ^^^^^^

   **Observed behaviour**: The buffer displays as:

       xyyyyyThree tabs
       xyyyZZTab
       ^^^^^^

5. Run the command: `:set nolist`.

   **Expected behavior**: The buffer should display as:

         ThreeTabs
         ZZTab
       ^^^^^^

   **Observed behaviour**: The buffer displays as:

            Three tabs
           ZZTab
       ^^^^^^

**Environment:**

I'm testing in Vim 8.1.2234 on Mac (but I don't believe the behaviour is OS specific).

**Additional context:**

I'm guessing that the position of the trailing (right-hand) edges of the tabs are set according to the `tabstop` _before_ the text is concealed, leading to the unexpected behaviour.

**Comment by zeertzjq** [comment]
This is intentional, otherwise concealing will break the alignment of text aligned using TABs.

**Comment by chrisbra** [comment]
closing then.

**Comment by sedm0784** [comment]
It look me a while to figure out what @zeertzjq's comment meant, and even longer to figure out an example where it occurs, so for the benefit of future readers, here's an example where calculating conceals before calculating the positions of tabs will break alignment:

1. Run the following:

        set list listchars+=tab:>-

2. Enter some text into a buffer:

        columnspanning<tab>column3
        column1<tab>column2<tab>column3

   Vim will display it like this:

        columnspanning>-column3
        column1>column2>column3

3. Then run the commands:

        syntax match hide /columnspanning/ conceal
        set conceallevel=2

   Vim will now display like this:

        >---------------column3
        column1>column2>column3

If conceals were processed first, then it would display like:

    >-------column3
    column1>column2>column3
