### ISSUE TITLE
crash when sourcing a Vim9 function with variable arguments

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#5572]
**Describe the bug**

Vim crashes when sourcing a Vim9 function with variable arguments.

**To Reproduce**

Write this in `/tmp/vim.vim`:

    def MyFunc(itemlist: list)
        for item in itemlist
            echo item
        endfor
    enddef

Start Vim like this:

    vim -Nu NONE -S /tmp/vim.vim

Vim crashes.

**Expected behavior**

Vim doesn't crash.

**Environment**

 - Vim version: 8.2 Included patches: 1-205
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

I probably misunderstood the help, and the function definition must contain some syntax error, but I still would expect Vim not to crash.

---

Here are:

   - [a backtrace](https://github.com/vim/vim/files/4151953/backtrace.txt)
   - [a valgrind log](https://github.com/vim/vim/files/4151954/valgrind.log)
   - [an asan log](https://github.com/vim/vim/files/4151955/asan.log)

**Comment by lacygoill** [comment]
I think the correct way to define the function is like this:

               ┌ name of the argument
               │         ┌ type of the argument
               │         │    ┌ type of the items inside the list
               │         │    │
    def MyFunc(itemlist: list<string>)
        for item in itemlist
            echo item
        endfor
    enddef

I wonder how you would define a list containing a mix of strings and numbers...
Anyway, it seems the crash is due to a combination of 2 things:

   1. an argument of type list, but whose items are not typed
   2. an iteration over this argument

So, this reproduces the crash too:

    def MyFunc(arg: list)
        for x in arg
            "
        endfor
    enddef

**Comment by lacygoill** [comment]
I'm not sure whether this is the same bug, but if I source this:

    def MyFunc(name = 'string')
        echo name
    enddef
    call MyFunc()

It raises `E685`:

    Error detected while processing function MyFunc:
    line    1:
    E685: Internal error: copy_tv(UNKNOWN)
    E908: using an invalid value as a String

Here is a [backtrace](https://github.com/vim/vim/files/4153356/backtrace.txt).

**Comment by brammool** [comment]
> I'm not sure whether this is the same bug, but if I source this:
> 
>     def MyFunc(name = 'string')
>         echo name
>     enddef
>     call MyFunc()
> 
> It raises `E685`:
> 
>     Error detected while processing function MyFunc:
>     line    1:
>     E685: Internal error: copy_tv(UNKNOWN)
>     E908: using an invalid value as a String
> 
> Here is a [backtrace](https://github.com/vim/vim/files/4153356/backtrace.txt)

Using default values on a "def" function is not implemented yet.
But it should give a proper error message.

-- 
"Space is big.  Really big.  You just won't believe how vastly hugely mind-
bogglingly big it is.  I mean, you may think it's a long way down the
road to the chemist, but that's just peanuts to space."
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
> I think the correct way to define the function is like this:
> 
>                ┌ name of the argument
>                │         ┌ type of the argument
>                │         │    ┌ type of the items inside the list
>                │         │    │
>     def MyFunc(itemlist: list<string>)
>         for item in itemlist
>             echo item
>         endfor
>     enddef
> 
> I wonder how you would define a list containing a mix of strings and
> numbers...

list<any>

> Anyway, it seems the crash is due to a combination of 2 things:
> 
>    1. an argument of type list, but whose items are not typed
>    2. an iteration over this argument
> 
> So, this reproduces the crash too:
> 
>     def MyFunc(arg: list)
>         for x in arg
>             "
>         endfor
>     enddef

It also crashes without the iteration, the type is NULL and that wasn't
checked for.

> ---
> 
> Not sure if it's intended, but Vim doesn't redraw the command-line:
> 
>     " write this in `/tmp/vim.vim`
>     def MyFunc(arg: list<string>)
>         for item in arg
>             echo item
>         endfor
>     enddef
>     call MyFunc(['a', 'b'])
> 
>     " execute this
>     :so /tmp/vim.vim
> 
> displays this:
> 
>     aso /tmp/vim.vim
>     b

When crashing anything can happen...

-- 
Apparently, 1 in 5 people in the world are Chinese.  And there are 5
people in my family, so it must be one of them.  It's either my mum
or my dad.  Or my older brother Colin.  Or my younger brother
Ho-Cha-Chu.  But I think it's Colin.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
> list\<any>

Will `list<string|number>` be supported?
