### ISSUE TITLE
Terminal background color not working correctly after patch 8.1.1146 on Ubuntu.

### ISSUE THREAD

**Issue by gmoshkin** [vim/vim#5574]
After patch 8.1.1146, when I set the highlighting of terminal background to my default background color, it shows up wrong.

**To Reproduce**
What I do to reproduce the issue:
* Run `vim --clean +'hi Terminal ctermbg=8' +terminal`

Before v8.1.1146 (e.g. v8.1.1145 in this case) I see this:
![vim-bug-before](https://user-images.githubusercontent.com/10168363/73730163-691d4f00-4747-11ea-98a8-a76ed107edc7.png)

After v8.1.1146 I see this:
![vim-bug-after](https://user-images.githubusercontent.com/10168363/73730275-910cb280-4747-11ea-8a07-f214f870884b.png)

The same holds in the latest version.
**Environment:**
 - Problems start and stay from version v8.1.1146
 - OS: Ubuntu 18.04
 - GNOME Terminal

**Comment by brammool** [comment]
I would say that is correct: a value of 8 is grey.
Your fix in #5575 is definitely wrong.

**Comment by gmoshkin** [comment]
@brammool, my fix may be wrong, but value of 8 in my terminal's color palette is not grey.

This is what my color palette looks like:
![vim-bug-color-palette](https://user-images.githubusercontent.com/10168363/73789931-beda1180-47b0-11ea-9f35-711eabbc3ad4.png)

The 8th color is the darkest one, and is the one used to color the background of the terminal in v8.1.1145.

**Comment by brammool** [comment]
How do you set that color palette?  What kind of terminal is this?

**Comment by gmoshkin** [comment]
I'm using the gnome-terminal:
```
$ gnome-terminal --version
# GNOME Terminal 3.34.2 using VTE 0.58.2 +BIDI +GNUTLS
```

To set the color palette I use the `https://github.com/Anthony25/gnome-terminal-colors-solarized` script. What it does is invoke `dconf` to configure the gnome-terminal's profile:
```
dconf write /org/gnome/terminal/legacy/profiles:/:<PROFILE_ID>/palette ['#070736364242', '#DCDC32322F2F', '#858599990000', '#B5B589890000', '#26268B8BD2D2', '#D3D336368282', '#2A2AA1A19898', '#EEEEE8E8D5D5', '#00002B2B3636', '#CBCB4B4B1616', '#58586E6E7575', '#65657B7B8383', '#838394949696', '#6C6C7171C4C4', '#9393A1A1A1A1', '#FDFDF6F6E3E3']
dconf write /org/gnome/terminal/legacy/profiles:/:<PROFILE_ID>/bold-color '#9393a1a1a1a1'
dconf write /org/gnome/terminal/legacy/profiles:/:<PROFILE_ID>/background-color '#00002B2B3636'
dconf write /org/gnome/terminal/legacy/profiles:/:<PROFILE_ID>/foreground-color '#838394949696'
dconf write /org/gnome/terminal/legacy/profiles:/:<PROFILE_ID>/use-theme-colors false
dconf write /org/gnome/terminal/legacy/profiles:/:<PROFILE_ID>/bold-color-same-as-fg false
```

I tried looking at the code, but I failed to understand where should I even look, i.e. which function sequence is being executed when the terminal color is being chosen.

**Comment by lifecrisis** [comment]
@brammool:

I just wanted to note that this issue is almost precisely the one I reported that is currently listed in the `todo.txt` file.

```
Problem with colors in terminal window. (Jason Franklin, 2019 May 12)
```

I couldn't arrive at a meaningful solution at the time, but I just wanted to note that this user appears to be experiencing a very similar issue.

**Comment by brammool** [comment]
There have been changes in how colors are handled.  Still, if you define a different color for gnome terminal, I'm not so sure it should be used in a terminal window, it emulates a standard terminal, not a gnome terminal.  You can easily define a different color with the Terminal highlight group.

**Comment by lifecrisis** [comment]
On Sun, 2020-06-07 at 12:11 -0700, Bram Moolenaar wrote:
> There have been changes in how colors are handled. Still, if you define a different color for gnome terminal, I'm not so sure it should be used in a terminal window, it emulates a standard terminal, not a gnome terminal. You can easily define a different color with the Terminal highlight group.

I did notice that something had changed.   It looks better upon
immediately opening a terminal window now.  The colors aren't
immediately broken, but they can be broken, for example, if I open a new
Vim session inside of the terminal window.

So, better, but still not quite what I expected.

---

I can understand your argument, though.

I wonder if the "g:terminal_ansi_colors" variable is of interest here. 
To explain: The documentation for this setting does say that the new
terminal window should always use the colors of the underlying terminal
if GUI colors is not set.

Should this be changed then?

-- 
Jason

**Comment by lifecrisis** [comment]
I would like to probe a bit further here, just because I don't understand well...

If `gnome-terminal` draws "green" (meaning the ANSI escape code) as a particular RGB value, I would think that libvterm should honor that without even knowing it.  That is, when it sends its escape code to draw "green", gnome-terminal will just draw the correct color based on the palette that has been configured.

Is that not how it works?

**Comment by gmoshkin** [comment]
> There have been changes in how colors are handled. Still, if you define a different color for gnome terminal, I'm not so sure it should be used in a terminal window, it emulates a standard terminal, not a gnome terminal. You can easily define a different color with the Terminal highlight group.

Yeah, the problem with the terminal background seems to be fixed, but as @lifecrisis mentioned, the color does break when you open a nested vim instance inside the terminal, which is not a big deal for me.

Thanks for the update on the issue, now I can use the latest vim build again!
