### ISSUE TITLE
smartindent in conflict with user defined completion

### ISSUE THREAD

**Issue by oblitum** [vim/vim#558]
Consider the following minimal `.vimrc`:

``` vim
set smartindent

function! FooBarComplete(findstart, base)
  if a:findstart
    return col('.') - 1
  else
    return ["Foo", "Bar"]
  endif
endfunction
set completefunc=FooBarComplete
```

Open an empty buffer and check that smartindent is working by entering insert mode and typing:
1. `{`
2. `Enter`
3. `}`

When pressing `Enter`, automatic tabulation should be inserted, and when pressing `}`, it should be automatically removed.

Now, in insert mode, type the following with the buffer empty:
1. `{`
2. `Enter`
3. `CTRL-X`, `CTRL-U`, `CTRL-P`
4. `}`

On step 3, after typing  `CTRL-X`, `CTRL-U`, "User defined completion" should be activated and `"Foo"` should have been inserted. After typing `CTRL-P`, we're back to original text state, but still in "User defined completion".
## The Conflict

When typing `}`, smartindent is ignored, I guess because we're inside "User defined completion". Should smartindent have precedence over "User defined completion" when it's "Back to original"? I guess it should.

This is one common cause of smartindent bugs in code completion plugins. Code completion plugins generally employ something along these lines:

``` vim
function! FooBarComplete(findstart, base)
  if a:findstart
    return col('.') - 1
  else
    return ["Foo", "Bar"]
  endif
endfunction
set completefunc=FooBarComplete

au TextChangedI * call feedkeys("\<C-X>\<C-U>\<C-P>", 'n')
```

Where they look to bring popup completion menu automatically for text selection, but break smartindent where it would remove indentation.

Related issues:
- https://github.com/oblitum/YouCompleteMe/issues/10
- https://github.com/Valloric/YouCompleteMe/pull/1901

Tested on Vim 7.4.1016.

**Comment by oblitum** [comment]
This issue doesn't happen with `cindent`. Actually, `cindent` behaves just as expected.

**Comment by oblitum** [comment]
If anyone is going to dig this, there's more to it which may be of interest:

> wow, following from this smartindent problem to https://github.com/Valloric/YouCompleteMe/issues/1352 and the inner links... there're just too many conflicts between completion mechanisms and indentation in Vim. I guess vim/vim#558 should provide a good testcase for one going to try fix this in Vim for good, it does need some care there. If I had the time and money....

source: https://github.com/Valloric/YouCompleteMe/pull/1901#issuecomment-171689113

**Comment by chrisbra** [comment]
I don't follow. What exactly are the other problems?

Here is a patch, that fixes this particular problem and adds a test:
diff --git a/src/edit.c b/src/edit.c
index bd5c57e..595118a 100644
--- a/src/edit.c
+++ b/src/edit.c
@@ -1432,6 +1432,7 @@ docomplete:
            if (ins_complete(c) == FAIL)
                compl_cont_status = 0;
            compl_busy = FALSE;
+           can_si = TRUE; /* allow smartindenting */
            break;
 #endif /* FEAT_INS_EXPAND */

diff --git a/src/testdir/test_alot.vim b/src/testdir/test_alot.vim
index 413e71b..8252fcf 100644
--- a/src/testdir/test_alot.vim
+++ b/src/testdir/test_alot.vim
@@ -9,3 +9,4 @@ source test_set.vim
 source test_sort.vim
 source test_undolevels.vim
 source test_unlet.vim
+source test_complete.vim
diff --git a/src/testdir/test_complete.vim b/src/testdir/test_complete.vim
new file mode 100644
index 0000000..233e124
--- /dev/null
+++ b/src/testdir/test_complete.vim
@@ -0,0 +1,22 @@
+" tests for completion mode
+
+
+function! FooBarComplete(findstart, base)
+  if a:findstart
+    return col('.') - 1
+  else
+    return ["Foo", "Bar", "}"]
+  endif
+endfunction
+
+func Test_complete_smartindent()
+  new
+  setlocal smartindent
+  set completefunc=FooBarComplete
+
+  exe "norm! o{\<cr>\<c-x>\<c-u>\<c-p>}\<cr>\<esc>"
+  let result=getline(1,'$')
+  call assert_equal(['', '{','}',''], result)
+  bw!
+  set completefunc=
+endfu

**Comment by chrisbra** [comment]
Arg, stupid Markdown formatting....

**Comment by vim-ml** [comment]
Hi Francisco!

On Mi, 13 Jan 2016, Francisco Lopes wrote:

> Consider the following minimal `vimrc`:
> 
> ``` vim
> set smartindent
> 
> function! FooBarComplete(findstart, base)
>   if a:findstart
>     return col('') - 1
>   else
>     return ["Foo", "Bar"]
>   endif
> endfunction
> set completefunc=FooBarComplete
> ```
> 
> Open an empty buffer and check that smartindent is working by entering insert mode and typing:
> 
> 1 `{`
> 2 `Enter`
> 3 `}`
> 
> When pressing `Enter`, automatic tabulation should be inserted, and when pressing `}`, it should be automatically removed
> 
> Now, in insert mode, type the following with the buffer empty:
> 
> 1 `{`
> 2 `Enter`
> 3 `CTRL-X`, `CTRL-U`, `CTRL-P`
> 4 `}`
> 
> On step 3, after typing  `CTRL-X`, `CTRL-U`, "User defined completion" should be activated and `"Foo"` should have been inserted After typing `CTRL-P`, we're back to original text state, but still in "User defined completion"
> 
> ## The Conflict
> 
> When typing `}`, smartindent is ignored, I guess because we're inside "User defined completion" Should smartindent have precedence when "Back to original"? I guess it should
> 
> This is the cause of code completion plugins with smartindent Code completion plugins generally employ something along these lines:
> 
> ``` vim
> function! FooBarComplete(findstart, base)
>   if a:findstart
>     return col('') - 1
>   else
>     return ["Foo", "Bar"]
>   endif
> endfunction
> set completefunc=FooBarComplete
> 
> "au TextChangedI * | call feedkeys("\<C-X>\<C-U>\<C-P>", 'n')
> ```
> 
> Where they look to bring popup completion menu automatically for text selection, but break smartindent where it would remove indentation
> 
> Related issues:
> - https://githubcom/oblitum/YouCompleteMe/issues/10
> - https://githubcom/Valloric/YouCompleteMe/pull/1901
> 
> Tested on Vim 741016

Okay, let's post the patch here:
diff --git a/src/edit.c b/src/edit.c
index bd5c57e..595118a 100644
--- a/src/edit.c
+++ b/src/edit.c
@@ -1432,6 +1432,7 @@ docomplete:
            if (ins_complete(c) == FAIL)
                compl_cont_status = 0;
            compl_busy = FALSE;
-           can_si = TRUE; /\* allow smartindenting _/
          break;
  #endif /_ FEAT_INS_EXPAND */

diff --git a/src/testdir/test_alot.vim b/src/testdir/test_alot.vim
index 413e71b..8252fcf 100644
--- a/src/testdir/test_alot.vim
+++ b/src/testdir/test_alot.vim
@@ -9,3 +9,4 @@ source test_set.vim
 source test_sort.vim
 source test_undolevels.vim
 source test_unlet.vim
+source test_complete.vim
diff --git a/src/testdir/test_complete.vim b/src/testdir/test_complete.vim
new file mode 100644
index 0000000..233e124
--- /dev/null
+++ b/src/testdir/test_complete.vim
@@ -0,0 +1,22 @@
+" tests for completion mode
+
+
+function! FooBarComplete(findstart, base)
-  if a:findstart
-    return col('.') - 1
-  else
-    return ["Foo", "Bar", "}"]
-  endif
  +endfunction
  +
  +func Test_complete_smartindent()
-  new
-  setlocal smartindent
-  set completefunc=FooBarComplete
  +
-  exe "norm! o{<cr><c-x><c-u><c-p>}<cr><esc>"
-  let result=getline(1,'$')
-  call assert_equal(['', '{','}',''], result)
-  bw!
-  set completefunc=
  +endfu

Best,

## Christian

Hallo Weißbrot-Angler!

**Comment by oblitum** [comment]
@chrisbra use fenced code blocks with patch or diff filetype. You may also alter the comment.

**Comment by oblitum** [comment]
@chrisbra This is nice, regarding the other issues, I've just made a reference because there're many issues related to indentation and code completion, and I thought if anyone would go check it could also be close to figuring out others or just ironing it out. For example, https://github.com/Valloric/YouCompleteMe/issues/1352 is another one that's quite annoying where backspace doesn't happen.

**Comment by oblitum** [comment]
@chrisbra it's just awesome how much discussion and circumvention code can be settled with a single line of code at the correct location :-).

It's working fine here, just applied the patch.

**Comment by chrisbra** [comment]
Thanks @oblitum. In case this does not fix Valloric/YouCompleteMe#1352, can you please also give precise instructions how to reproduce this issue? I'll try to fix this then as well.

**Comment by oblitum** [comment]
@chrisbra I've already checked that it doesn't fix that one, but still, I think that a small modification in the process I've given in this one can potentially reproduce the issue. For example, instead of typing `}`, pressing ESC to go to normal mode. If whitespace is left behind, it's a reproduction of the issue. I didn't got the time to try that yet.

**Comment by oblitum** [comment]
@chrisbra I've just checked that it reproduces like I described. Will open another issue with similar procedure.

**Comment by vim-ml** [comment]
Hi Francisco, Chris.B and list,

2016-1-15(Fri) 6:39:07 UTC+9 Francisco Lopes:

> @chrisbra I've just checked that it reproduces like I described. Will open another issue with similar procedure.

I think this behavior is specification at the moment.
(This is not written to the document...)

smart-indent is explicitly disabled has been written in the source code.
Please grep `can_bs` in Vim source code.

If the `can_bs` is true, smart-indent might be work.

Briefly explain:
`can_bs` is set true, when add a new line.
And set to false at the following operation.
- Iuput normal character
- Input ctrl-T or vtrl-D (indent shift)
- Input <DEL> or <BS> or <TAB>
- Do internal line formatting
- Stop insert mode
- Enter completion  (src/edit.c : 5065)

Christian Brabandt>
I think your patch is not good idea that to forcibly change to true the `can_bs` at that location.

The following behavior has unexpectedly changed actually.

How to reproduce:
  $ vim -Nu NONE -c "set smartindent nocindent"
  :exec "silent! norm! i{<CR><SPACE><BS><C-X><C-O>}"

Without your patch behavior:
{
<TAB>}

With your patch behavior: 
{
}

I think the patched version is not taken integrity of the following behavior.

How to reproduce:
  $ vim -Nu NONE -c "set smartindent nocindent"
  :exec "silent! norm! i{<CR><SPACE><BS>}"

With and without your patch behavior:
{
<TAB>}

## 

Best regards,
Hirohito Higashi (a.k.a h_east)

**Comment by vim-ml** [comment]
Hi,

2016-1-15(Fri) 18:10:10 UTC+9 h_east:

> Hi Francisco, Chris.B and list,
> 
> 2016-1-15(Fri) 6:39:07 UTC+9 Francisco Lopes:
> 
> > @chrisbra I've just checked that it reproduces like I described. Will open another issue with similar procedure.
> 
> I think this behavior is specification at the moment.
> (This is not written to the document...)
> 
> smart-indent is explicitly disabled has been written in the source code.
> Please grep `can_bs` in Vim source code.

Oops, Big typo.
`can_si` is correct.
And also all this later

> If the `can_bs` is true, smart-indent might be work.
> 
> Briefly explain:
> `can_bs` is set true, when add a new line.
> And set to false at the following operation.
> - Iuput normal character
> - Input ctrl-T or vtrl-D (indent shift)
> - Input <DEL> or <BS> or <TAB>
> - Do internal line formatting
> - Stop insert mode
> - Enter completion  (src/edit.c : 5065)
> 
> Christian Brabandt>
> I think your patch is not good idea that to forcibly change to true the `can_bs` at that location.
> 
> The following behavior has unexpectedly changed actually.
> 
> How to reproduce:
>   $ vim -Nu NONE -c "set smartindent nocindent"
>   :exec "silent! norm! i{<CR><SPACE><BS><C-X><C-O>}"
> 
> Without your patch behavior:
> {
> <TAB>}
> 
> With your patch behavior: 
> {
> }
> 
> I think the patched version is not taken integrity of the following behavior.
> 
> How to reproduce:
>   $ vim -Nu NONE -c "set smartindent nocindent"
>   :exec "silent! norm! i{<CR><SPACE><BS>}"
> 
> With and without your patch behavior:
> {
> <TAB>}

## 

Best regards,
Hirohito Higashi (a.k.a h_east)

**Comment by vim-ml** [comment]
Hi,

2016-01-15 7:14 GMT-02:00 h_east h.east.727@gmail.com:

> Hi,
> 
> 2016-1-15(Fri) 18:10:10 UTC+9 h_east:
> 
> > Hi Francisco, Chris.B and list,
> > 
> > 2016-1-15(Fri) 6:39:07 UTC+9 Francisco Lopes:
> > 
> > > @chrisbra I've just checked that it reproduces like I described. Will
> > > open another issue with similar procedure.
> > 
> > I think this behavior is specification at the moment.
> > (This is not written to the document...)
> > 
> > smart-indent is explicitly disabled has been written in the source code.
> > Please grep `can_bs` in Vim source code.
> 
> Oops, Big typo.
> `can_si` is correct.
> And also all this later
> 
> > If the `can_bs` is true, smart-indent might be work.
> > 
> > Briefly explain:
> > `can_bs` is set true, when add a new line.
> > And set to false at the following operation.
> > - Iuput normal character
> > - Input ctrl-T or vtrl-D (indent shift)
> > - Input <DEL> or <BS> or <TAB>
> > - Do internal line formatting
> > - Stop insert mode
> > - Enter completion  (src/edit.c : 5065)
> > 
> > Christian Brabandt>
> > I think your patch is not good idea that to forcibly change to true the
> > `can_bs` at that location.
> > 
> > The following behavior has unexpectedly changed actually.
> > 
> > How to reproduce:
> >   $ vim -Nu NONE -c "set smartindent nocindent"
> >   :exec "silent! norm! i{<CR><SPACE><BS><C-X><C-O>}"
> > 
> > Without your patch behavior:
> > {
> > <TAB>}
> > 
> > With your patch behavior:
> > {
> > }

You're right Hirohito, (except for the typo ;-) I got it). The patch is
operating
as if "losing memory" that we have inserted whitespace before entering
completion
mode. But I hope that this detail be easy to fix? and also that there'll be
nothing
left to fix besides this.

Thanks,
Francisco Lopes

**Comment by oblitum** [comment]
Also, as I said, I'd like to have a fix, but as you have stated, this would mean relaxing the internal specification (that isn't documented in Vim help), regarding "Enter completion (src/edit.c : 5065)".

**Comment by oblitum** [comment]
This relaxing of rules would mean adding a restriction to that bullet. Like:
- Enter completion, that _actually_ adds text.

**Comment by vim-ml** [comment]
s/an special case/restriction/

2016-01-15 13:52 GMT-02:00 Francisco Lopes vim-dev-github@256bit.org:

**Comment by lfrankel** [comment]
This is still a problem six years later, as is the YouCompleteMe issue it causes :(

https://github.com/ycm-core/YouCompleteMe/issues/1352

**Comment by lfrankel** [comment]
Awesome! Thanks folks :D
