### ISSUE TITLE
Calling popup_hide() on a terminal popup window doesn't move the focus back to the previous window

### ISSUE THREAD

**Issue by bfrg** [vim/vim#5585]
**Describe the bug**
Calling `popup_hide()` on a terminal popup window makes the cursor (sort of) unresponsive until the popup window is shown again. The cursor is kept at the same position where it was before the popup window is hidden and all characters are inserted into the hidden terminal buffer.

**To Reproduce**
1. Run `vim --clean -c "source popup.vim"`, with
```vim
let winid = term_start(&shell, {'hidden': 1, 'term_finish': 'close'})
    \ ->popup_create({'minwidth': 70, 'minheight': 20, 'border': []})
```
2. Type `<c-w>:call popup_hide(winid)` to hide the terminal window. The cursor will remain at the same position. All characters that are typed will be inserted into the (hidden) terminal buffer.
3. Type `<c-w>:call popup_show(winid)` to show the terminal popup window again.

**Expected behavior**
I would have expected Vim to move the focus back to the last active window when a terminal popup window is hidden.

**Environment**
Vim version `8.2.210`

**Comment by brammool** [comment]
The current approach is that when using a terminal in a popup window, it always gets keyboard focus.  Thus hiding it should not be allowed.
I'm a bit careful to not allow too much, because it can open can of worms...  We'll see if there are valid use cases that require more flexibility.

**Comment by skywind3000** [comment]
Can we use close on an unfinished terminal popup and reopen it when needed by `popup_create` ?
