### ISSUE TITLE
Windows uninstaller doesn't remove vimtutor.bat

### ISSUE THREAD

**Issue by lkintact** [vim/vim#5597]
1. Install Vim, make sure you check the "Create .bat files" box during the process
2. Uninstall Vim. The file `C:\Windows\vimtutor.bat` is still there.

Vim: https://github.com/vim/vim-win32-installer/releases/download/v8.2.0230/gvim_8.2.0230_x86.exe,
Windows 10 Home 1803.

**Comment by k-takata** [comment]
Fixed by #5603.
