### ISSUE TITLE
Docs: E146 (:s accepts non-/ delimiters) is not discoverable enough

### ISSUE THREAD

**Issue by hseg** [vim/vim#5600]
**Describe the bug**
`E146` describes the fact that `:s` accepts delimiters that aren't `/`, e.g. `:s,pat,rep,flags`.
However, a quick `:helpgrep E146` shows it isn't ever referenced, and the documentation for `:s`
similarly fails to allude to this behaviour. This impedes the discoverability of this feature - if I hadn't
known to look for it I never would've found it.

**Environment (please complete the following information):**
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 26 2020 11:45:38)
Included patches: 1-148
Compiled by Arch Linux

**Comment by brammool** [comment]
Let's add a pattern-delimiter tag.
