### ISSUE TITLE
gVim: Scrollbars not flush against the window edges when maximised

### ISSUE THREAD

**Issue by JMcKiern** [vim/vim#5602]
**Describe the bug**
The scrollbars are not flush against the window edges when the window is maximised.
This is true on the right and the bottom edges with the corresponding scrollbars enabled.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Open gvim
1. Type `:set guioptions=r`
1. Maximise the window

**Expected behavior**
The window is fully maximised and the scrollbars are flush against the edges.

**Screenshots**
![image](https://user-images.githubusercontent.com/9341692/74093913-8c8e2400-4ad0-11ea-9188-a616dcf63a86.png)
![image](https://user-images.githubusercontent.com/9341692/74093922-99127c80-4ad0-11ea-810b-eb94f6ac2517.png)
![image](https://user-images.githubusercontent.com/9341692/74093930-d1b25600-4ad0-11ea-8ed0-88c63fc2a118.png)

**Environment:**
 - Vim version 8.2
 - OS: Windows 10 17134
 - Terminal: GUI

**Additional context**
- This is dependent on the DPI scaling chosen in Windows Settings. Using 100%, 150% and 175%, the bug is present. However, with 125% (which is recommended), the bug does not appear. Although, at 125%, moving the mouse to the very right edge of the screen and trying to select the scrollbar is unreliable - sometimes it works, sometimes it doesn't.

**Comment by JMcKiern** [comment]
It appears that this is also dependent on the font and font size used.

The following fonts (including the sizes) lead to the expected behaviour:
- Lucida_Console:h14
- Consolas:h15

Note that using these fonts at different sizes causes the bug to reappear.

**Comment by Bakudankun** [comment]
This occurs when the column width is not a divisor of (screen resolution - scrollbar width).
If you make the scrollbar snap to the right edge, then another problem will arise; what should vim draw where the scrollbar was? Simply draw the Normal background color, or extend the background of each rows of the rightmost column?

Personally speaking, I'm satisfied with current behavior where no gap exists between scrollbar and the rightmost column.

FYI you have some option to make the gap less annoying.
- Disable the right scrollbar (`:h go-r`).
- Specify the font width to hopefully minimize the gap (`:h E244`).

**Comment by JMcKiern** [comment]
Ah interesting, that makes sense.

So basically, the scrollbar is rendered in a small "column" on the right hand side of the screen. And currently the scrollbar is aligned to the left hand side in that column. Is that roughly correct?

I see that there are advantages with the way it is currently set up. However, one thing that I would like to be able to do is slide my cursor to the edge of the screen and use the scroll bar.

And I don't really want to change my font size to fix this.

**Comment by chrisbra** [comment]
as this is expected, I guess it can be closed, right?

**Comment by JMcKiern** [comment]
Is this expected? What about desired?

The four applications that I currently have open (Chrome, Spotify, Discord and Microsoft To Do) all have scrollbars flush with the right hand side of the window. It seems that *this* is the expected behaviour of a scrollbar.

While the behaviour in gVim might not be a bug, I believe that it would make more sense to follow what appears to be a universal design standard.

**Comment by k-takata** [comment]
Current behavior has a reason, but I don't want to say it is ideal.
So, I reopen this. However this is low priority. (Of course, PR is welcome.)

**Comment by k-takata** [comment]
I created a PR for this: #6466.
