### ISSUE TITLE
Substitution with range - mistake in cmdline.txt?

### ISSUE THREAD

**Issue by dolohow** [vim/vim#561]
I tried to create a substitute that will match the current line and five lines below with range like this:

```
.+5 s/a/A/g
```

but it doesn't work it says that pattern was not found, yet

```
.,+5 s/a/A/g
```

works fine, therefore the following patch should be applied? Or am I doing something wrong?

``` diff
diff --git a/runtime/doc/cmdline.txt b/runtime/doc/cmdline.txt
index 8186678..d4c32e7 100644
--- a/runtime/doc/cmdline.txt
+++ b/runtime/doc/cmdline.txt
@@ -680,7 +680,7 @@ use it as a count do use it as a zero (|:tag|, |:pop|, etc).  Some commands
 interpret the zero as "before the first line" (|:read|, search pattern, etc).

 Examples: >
-       .+3             three lines below the cursor
+       .,+3            three lines below the cursor
        /that/+1        the line below the next line containing "that"
        .,$             from current line until end of file
        0;/that         the first line containing "that", also matches in the
```

**Comment by fritzophrenic** [comment]
No, this patch should not be applied. You've misunderstood the meaning of the help, here.

".+3" does not mean "the current line and three lines below". It means "the _single_ line which is three lines below the current line".
