### ISSUE TITLE
":eval" sees '|' as its argument inside an if block

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#5640]
**Describe the bug**

`:eval` sees `|` as its argument inside an if block when the condition fails.

**To Reproduce**

Start Vim with no config:

    vim -Nu NONE

Execute this Ex command:

    if 0 | eval 0 | endif | let x = 123 | echo x

The cursor is still on the command-line.

Execute `:endif`; the cursor leaves the command-line.
Execute `:echo x`; `E121` (undefined variable) is raised.

**Expected behavior**

There is no need to execute `:endif` a second time to leave the command-line; the first one is enough.
`:echo x` doesn't raise any error, and outputs `123`.

**Environment**

 - Vim version:  8.2 Included patches: 1-259
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

I think the issue is due to `:eval` which consumes the bar, instead of stopping at it.
This seems to be a bug for 3 reasons:

   - it's not documented at `:h :bar` (`:eval` is not mentioned there), nor at `:h :eval`

   - it's inconsistent with an `:eval` outside an `if` block:

         :eval 0 | echo 'test'

     Here `:eval` does not consume the bar, and the `test` message is correctly displayed on the command-line.

   - it's inconsistent with an `:eval` inside an `if` block whose condition is true:

         :if 1 | eval 0 | endif | echo 'test'

---

The same issue applies to other types of blocks (`:for`, `:while`, ...):

    :for i in [] | eval 0 | endfor | let x = 123

    :while 0 | eval 0 | endwhile | let x = 123

**Comment by tonymec** [comment]
- I confirm the error.
- Wrapping the `:eval` statement in an `:exe` statement, as in e.g. `:if 0 | exe "eval 0" | endif | let x = 0` makes Vim behave as expected.
- OTOH replacing one or more bars by carriage-returns (by hitting Ctrl-V followed by Enter) doesn't.
