### ISSUE TITLE
":call" sees "|" as its argument inside a try conditional

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#5642]
**Describe the bug**

`:call` sees `|` as its argument inside a try conditional.

**To Reproduce**

Start Vim with no config:

    vim -Nu NONE

Execute this Ex command:

    try | call Func() | catch | endtry

The cursor is still on the command-line.

Execute `:endtry`; the cursor leaves the command-line, and `E117` ("unknown function") is raised.

**Expected behavior**

There is no need to execute `:endtry` a second time to leave the command-line; the first one is enough.
No error is raised, because the call to the unknown function `Func()` was caught by the `:catch` clause.

**Environment**

 - Vim version:  8.2 Included patches: 1-259
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

I think that `:call` consumes `:catch | endtry` when it fails to call a function.

---

Originally, I found this issue while writing a custom command looking like this:

    com -nargs=1 Test try | call Func(<args>) | catch | endtry
    fu Func(arg)
        echo a:arg
    endfu

This works as expected (i.e. `message` is displayed on the command-line):

    :Test 'message'

But not this:

    :Test message

The cursor stays on the command-line.
I need to execute `:endtry`, and then `E121` ("Undefined variable") as well as `E116` ("Invalid arguments") are raised, while I would expect no error to be raised thanks to the `catch` clause of the `try` conditional.

---

If the code is sourced from a script written on a single line:

    vim -Nu NONE -S <(echo 'try | call Func() | catch | endtry')

Then `E117` is raised.

But if the same code is split on multiple lines:

    vim -Nu NONE -S <(cat <<'EOF'
        try
            call Func()
        catch
        endtry
    EOF
    )

Then no error is raised.

**Comment by tonymec** [comment]
I confirm the problem on gvim and Console Vim, version 8.2.260, on openSUSE Linux15.1.

When typing the command at the command-line, after hitting Return we are still on the command-line after a colon followed by two spaces. Then typing a second `endtry` gives me
```
Error detected while processing : 
E117: Unknown function: Func
```
(I wonder if this first line means just "Error detected while processing" or "…while processing a colon token")

I also confirm that when breaking the command into more than one line, e.g. (still typed from the keyboard at the command-line)
```vim
:try | call Func()
:  catch | endtry
```
(where the ":  " leader of the second line is provided by Vim) there is no error.

**Comment by jamessan** [comment]
@brammool The fix for this [broke a test](https://travis-ci.org/vim/vim/jobs/651184333#L5716) in test_trycatch.vim:

```
	From test_trycatch.vim:
	Found errors in Test_builtin_func_error():
	function RunTheTest[40]..Test_builtin_func_error line 112: Expected 'jlmnpqrtueghivyzACD' but got 'jlmnpqrsteghivyzACD'
```
