### ISSUE TITLE
Unmap accented characters

### ISSUE THREAD

**Issue by cup** [vim/vim#5644]
If I press `Alt + o`, it prints `ï`. I would prefer it not do
anything. I tried:

~~~
:unmap <M-o>
~~~

but it just says:

~~~
E31: No such mapping
~~~

**Comment by k-takata** [comment]
If you prefer not to do anything, map it to `<Nop>`. See `:help <Nop>`.

Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. Closing.

**Comment by cup** [comment]
@k-takata thanks, this works for upper and lower:

~~~
imap <M-o> <Nop>
imap <M-O> <Nop>
~~~

**Comment by tonymec** [comment]
This is not a mapping, Vim just represents Alt-x combinations (where x is a character below 0x80) by the corresponding character with the high bit set. IIUC, mapping `<M-o>` to `<Nop>` in Insert mode will also make the ï key or combo (if there is one on your keyboard) inoperative: for instance, some French words (e.g. the interjection "aïe" expressing sudden pain) include an i with diaeresis, and French-language keyboards (French AZERTY, Belgian AZERTY and Swiss-Romance QWERTZ) have a native way to produce it by means of a dead "umlaut or diaeresis" key followed with i. If you map Alt-o to `<Nop>` in Insert mode you won't be able to type that ï character, unless you define another :inoremap with it as the {rhs}.

Best regards,
Tony.
