### ISSUE TITLE
matchstr do not work as expected

### ISSUE THREAD

**Issue by wsdjeg** [vim/vim#5646]
**Describe the bug**

matchstr function do not work as expected.

**To Reproduce**

1. Run `echo matchstr('" heloo ss 123 ss 879 sss 1112', '\d*')`

**Expected behavior**

should see `123`

**Environment (please complete the following information):**
 - Vim version 8.1.2120
 - OS: windows

**Comment by lacygoill** [comment]
The `*` quantifier can match 0 characters.  Replace it with `\+`:

    $ vim -es -Nu NONE +"pu=matchstr('\\\" heloo ss 123 ss 879 sss 1112', '\d\+')" +'%p|qa!'
                                                                             ^^

Outputs `123`.

**Comment by k-takata** [comment]
It is expected behavior. Closing.
