### ISSUE TITLE
text property removed after a ":move" command

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#5648]
**Describe the bug**

A text property set on some text on a line is removed when the latter is moved with the `:move` command.

**To Reproduce**

Write this text in `/tmp/file`:

    The number 123 is smaller than 4567.
    aaa

Write this script in `/tmp/vim.vim`:

    call prop_type_delete('number')
    call prop_type_add('number', {'highlight': 'Search'})
    call prop_add(1, 12, {'length': 3, 'type': 'number'})
    call prop_add(1, 32, {'length': 4, 'type': 'number'})

Start Vim like this:

    vim -Nu NONE -S /tmp/vim.vim /tmp/file

The numbers on the first line are highlighted with the `Search` highlight group.

Execute this Ex command while on the first line:

    :m+1

The numbers on the line are no longer highlighted.

**Screenshots**

![gif](https://user-images.githubusercontent.com/8505073/74611304-bb248400-50fa-11ea-9b48-15f5512a3ed9.gif)

**Expected behavior**

The numbers on the line are still highlighted.

**Environment**

 - Vim version:  8.2 Included patches: 1-265
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

I think I understand why it happens.
Internally, Vim first [copies](https://github.com/vim/vim/blob/a76b31542e1d83b7d2fe7378439912e800a4d0f6/src/ex_cmds.c#L709) the line to its new address, then it [deletes](https://github.com/vim/vim/blob/a76b31542e1d83b7d2fe7378439912e800a4d0f6/src/ex_cmds.c#L779) the original line.
And according to [`:h text-prop-changes`](https://github.com/vim/vim/blob/a76b31542e1d83b7d2fe7378439912e800a4d0f6/runtime/doc/textprop.txt#L319-L320), when a text property no longer includes any text, it is deleted:

> When text is deleted and a text property no longer includes any text, it is
> deleted.

However, as a user, I find this unexpected, as I don't see the 2-steps edit (copy + deletion); I only see a 1-step edit (move).

---

In Nvim, the highlighting persists.

    nvim -u NONE -S <(cat <<'EOF'
        let id = nvim_create_namespace('search')
        call nvim_buf_add_highlight(0, id, 'search', 0, 11, 14)
        call nvim_buf_add_highlight(0, id, 'search', 0, 31, 35)
    EOF
    ) /tmp/file

    :m+1

![gif](https://user-images.githubusercontent.com/8505073/74611444-30448900-50fc-11ea-8f2a-1bb4d666aab9.gif)

It would be nice if the highlighting also persisted in Vim.

---

Feel free to close the issue if I misunderstood something and it's working as intended, or if it's too hard to fix.

**Comment by brammool** [comment]
Any change that involves taking a text out of context and putting it somewhere else will cause text properties to be lost.  This is expected behavior.  In the general case, one can't expect the text properties to be valid in the new location, e.g. when used for syntax highlighting.

**Comment by lacygoill** [comment]
For anyone having the same issue, as a workaround, instead of moving a range of lines directly, move its surroundings; you can get the same result, while preserving the text properties.

To move the range of lines, from the current one down to the next `p` ones, `q` lines downward, execute this Ex command:

    +p+1,+p+qm-|+

To move the range of lines, from the current one down to the next `p` ones, `q` lines upward, execute this Ex command:

    -q,-m.+p|-q

As an example, consider this text file in `/tmp/file`:

    The number 12 is smaller than 345.
    The number 6789 is bigger than 1234.
    The number 56789 is smaller than 123456.
    aaa
    bbb
    ccc
    ddd
    eee

And this script in `/tmp/vim.vim`:

    call prop_type_add('number', {'highlight': 'Search'})
    call prop_add(1, 12, {'length': 2, 'type': 'number'})
    call prop_add(1, 31, {'length': 3, 'type': 'number'})
    call prop_add(2, 12, {'length': 4, 'type': 'number'})
    call prop_add(2, 32, {'length': 4, 'type': 'number'})
    call prop_add(3, 12, {'length': 5, 'type': 'number'})
    call prop_add(3, 34, {'length': 6, 'type': 'number'})

Now, start Vim like this:

    vim -Nu NONE -S /tmp/vim.vim /tmp/file

To move the 3 lines containing numbers 4 lines downward, execute this Ex command while on the first line of the range of number lines:

    +2+1,+2+4m-|+

And to move it again 3 lines upward, execute this Ex command while on the first line of the range of number lines:

    -3,-m.+2|-3

![gif](https://user-images.githubusercontent.com/8505073/74694481-94e11000-51f0-11ea-8953-4bb59b523ecb.gif)

**Comment by lacygoill** [comment]
Although, doing so will break the text properties on the surrounding lines.

This is not an issue for me, as the buffer in which I execute the `:move` command does not contain other text properties.  I only use one as a kind of temporary mark to restore the cursor position after `:m` via `prop_find()`; a normal mark is not good enough, because even if you save and restore its position, the latter is still altered after an undo, and I don't know how to fix that.
