### ISSUE TITLE
Markdown: fenced code blocks

### ISSUE THREAD

**Issue by cup** [vim/vim#5660]
Fenced code blocks are defined as:

> A code fence is a sequence of at least three consecutive backtick characters
> (<code>&#x60;</code>) or tildes (`~`).

This is in the current Markdown spec (Apr 2019), and even back to the oldest
spec (Oct 2014):

- https://spec.commonmark.org/0.29#fenced-code-blocks
- https://spec.commonmark.org/0.5#fenced-code-blocks

However Vim only seems to define backticks with inline code:

https://github.com/vim/vim/blob/406cd90f1963ca60813db91c413eef4b1b78ee44/runtime/syntax/markdown.vim#L98-L100

Doesnt define tilde use at all, and only recognizes the indented style of code
blocks:

https://github.com/vim/vim/blob/406cd90f1963ca60813db91c413eef4b1b78ee44/runtime/syntax/markdown.vim#L64

Is this the case or am I overlooking something?

**Comment by cup** [comment]
As a workaround, this is available with other packages:

~~~
packadd vim-markdown-master
~~~

https://github.com/plasticboy/vim-markdown/blob/master/syntax/markdown.vim#L103-L105

**Comment by k-takata** [comment]
Could you contact the maintainer (@tpope)?

**Comment by cup** [comment]
I think you just did...

**Comment by cup** [comment]
https://github.com/tpope/vim-markdown/issues/156

**Comment by chrisbra** [comment]
closing and leaving for the syntax file maintainer.
