### ISSUE TITLE
vim9 def method: allow floaty brackets

### ISSUE THREAD

**Issue by puremourning** [vim/vim#5661]
**Describe the bug**

vim9 def functions enforce certain rules about whitespace around operators, and do not allow whitespace before the opening `(` of a function call. They _do_ allow whitespace after the initial `(` before the first argument, and before any argument following `,`. 

However, while it's not explicitly stated in the current docs, the parser will _not_ accept whitespace before the closing `)`. I believe this "floaty brackets' style should be allowed. 

**To Reproduce**

test.vim:

```viml
vim9script

def A_really_really_log_method_name( a: list<string>, b ): void
    add( a, b )
enddef

def Test(): void
    add( [], 'test' )
    add( [],
       \ 'test' )

    let a_really_really_long_variable_name = []
    let another_really_really_long_variable_name = 'test'
    A_really_really_log_method_name(
            \     a_really_really_long_variable_name
            \     another_really_really_long_variable_name )

    A_really_really_log_method_name(
            \     a_really_really_long_variable_name
            \     #{
            \         key: 'value',
            \         another_key: 'another_value',
            \     }
            \ )
enddef
```

* vim --clean -S test.vim

**Expected behavior**

Whitespace is accepted after the last argument, before the closing `)` of a function call and `test.vim` is parsed without errors

**Actual behaviour***

```
Error detected while processing /mma/users/benj/proj/dev-tools/RHEL7/vim/vim/test.vim:
line    4:
E1015: Name expected:  )
line    8:
E1015: Name expected:  )
```

**Environment (please complete the following information):**
 - Vim version: `VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 19 2020 09:34:00) Included patches: 1-275`

 - OS: macOS, Linux
 - Terminal: iTerm, Terminal.app, PuTTY, xterm

**Additional context**

Ensuring whitespace for readability in cretain contexts is good, but being opinionated about it (like go), is IMO not such a good thing. Forcing a particular style (like fixed indentation or no-floaty-brackets) doesn't appear to be the goal of the new restrictions - i suspect they are to simplify parsing and ensure some level of readability, so i suspect this restriction is not intentional.

I trapped it in vimspcector and found the part of the parser that needs to change. If you think this is acceptable, i can send a patch.

**Comment by puremourning** [comment]
```
diff --git a/src/vim9compile.c b/src/vim9compile.c
index adfcbcc8f..0da323183 100644
--- a/src/vim9compile.c
+++ b/src/vim9compile.c
@@ -1660,6 +1660,8 @@ compile_arguments(char_u **arg, cctx_T *cctx, int *argcount)
        ++*argcount;
        if (*p == ',')
            p = skipwhite(p + 1);
+       else
+           p = skipwhite(p);
     }
     if (*p != ')')
     {
```

This patch makes the above _compile_ if not execute.

**Comment by brammool** [comment]
Yeah, not allowing white space before the ")" is too restrictive.
I notice other checks are not in place yet.  I made patch 8.2.0276 to improve this.

**Comment by puremourning** [comment]
Thanks Bram
