### ISSUE TITLE
Several bugs in lex.vim (patch available)

### ISSUE THREAD

**Issue by genivia-inc** [vim/vim#5662]
**Describe the bug**

Note: I contacted the lex.vim maintainer about this with a description of the problems and included an updated lex.vim file that I spent some time on to fix all of these issues and that is actually thoroughly tested and practically usable. But after the initial email response I have not heard back for weeks.

The following issues are observed with lex.vim:

- Start condition states with a scope of the form `<state>{ ... }` are not recognized correctly, leading to highlighting errors below it such as `%%` not being highlighted.
- Action code is highlighted when enclosed in braces `{`...`}` but otherwise its is not, which is inconsistent.
- Indented initial code blocks (instead of placed in `%{`...`%}`) are not recognized and are not highlighted.
- Indented initial action code blocks are not recognized and not highlighted correctly, which appear right after the first `%%` and in start condition scopes
- initial action code blocks in `%{`...`%}` are not recognized in start condition scopes `<state>{ ... }`.
- The start condition state `<*>` is not recognized and not highlighted.
- `//`-comments are not always recognized and highlighted.
- Rule actions after patterns are not always highlighted, such as ECHO, which is inconsistent.
- Final code block is not always highlighted correctly when start condition states with scopes are used.
- Literal string quotes `“...”` are not highlighted in abbreviation definitions, whereas in patterns they are highlighted.
- `%options` are highlighted inconsistently when used before or after initial code blocks (both places are valid).
- Also highlighting of state declarations `%s` and `%x` are inconsistent or not highlighted at all when placed before initial code blocks.
- `%top{` is not recognized, which should be the same as a `%{` block, in principle any `%name{` should be recognized.

**To Reproduce**

Save the following file as `example.l` and open it in Vim to observe the issues (most but not all of the problems):

~~~
/* Example to show lex.vim bugs */
// %options and %s are inconsistent:
%option fast flex noyywrap interactive
%s state
%top{
// This is not OK
#include <stdio.h>
%}
%{
// this is OK
#include <stdio.h>
%}
// %options and %s are inconsistent:
%option fast flex noyywrap interactive
%s state
/*
  still not highlighted
*/
// still not highlighted
%%
    printf("This is an initial action block, not a pattern\n");
foo     ECHO; // ECHO is not highlighted here
bar   { ECHO; }
<*>xyz    // <*> is not highlighted as <state> is
<state>{
    printf("This is an initial action block, not a pattern\n");
"abc"  { while (1) nothing; }
}
%%
// final code block not highlighted correctly
int main()
{
  return yyFlexLexer().yylex();
}
~~~

See the first screenshot.

**Expected behavior**

Syntax highlighting should be consistent and expect C++ as the default instead of C. See the second screenshot.

**Screenshots**

The lex.vim syntax highlighting issues:
![image](https://user-images.githubusercontent.com/13117347/74853730-53de1e00-530c-11ea-86dd-0b54253379ef.png)

Using the updated lex.vim, this is correct:
![image](https://user-images.githubusercontent.com/13117347/74855075-30b46e00-530e-11ea-937a-d436404c13af.png)

**Environment (please complete the following information):**
 - Vim version [e.g. 8.1.1234]
 - OS: Mac OS 10.12.6

**Patch**
See https://github.com/Genivia/RE-flex/blob/master/lex.vim for the patched version of lex.vim that works and that was thoroughly tested with dozens of Flex files. An example test file is included in lex.vim as a comment to serve as a reference example.

**Comment by cecamp** [comment]
The new lex.vim has been sent for inclusion into the main distribution.
