### ISSUE TITLE
Make `popup_close()` or `popup_hide()` possible in terminal popup

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#5666]
**Is your feature request related something that is currently hard to do? Please describe.**
Both `popup_hide()` and `popup_close()` are disabled in an unfinished terminal popup.

**Describe the solution you'd like**
Enable one of `popup_close()` or `popup_hide()` in a terminal popup

**Describe alternatives you've considered**

**Additional context**

The popup terminal can be more useful if it can be temporary hidden or shown. (or the relative popup window can be closed and recreated). 

An efficient workflow will be possible if so:

1. When I need to use the shell, I can press `<c-F12>` to open a popup terminal, unlike split terminal, it will not change my window layout and will not disturb me.

2. The shell job is not finished, now I want to edit, I don't have to exit the terminal, just press `<c-F12>`  to hide it.

3. Then, I finish my editing I can use `<c-f12>` again to bring the popup terminal back and continue my previous works in the shell.

It can make me really productive if the terminal popup can be toggled on/off swiftly by `<c-f12>` .  I even don't need the tmux pane any more if I can use this.

But sadly, I found both `popup_hide()` and `popup_close()` are disabled in an unfinished terminal popup. Can we enable one of them ??

**Comment by bfrg** [comment]
Related to  #5585

**Comment by brammool** [comment]
So, popup_close() would make the terminal hidden.  I suppose there is no harm in that.
popup_hide() might be more complicated, as currently this state is not supported.

**Comment by skywind3000** [comment]
Thanks
