### ISSUE TITLE
strcmp should be replace with 'mystrncmp'(self-defined)

### ISSUE THREAD

**Issue by real-watson** [vim/vim#5667]
**Is your feature request related something that is currently hard to do? Please describe.**
The strcmp() function used in src/tee/ should be replaced with others because it is not in a safe way.

**Describe the solution you'd like**
I would use one safe way for replacing strcmp(). 

**Describe alternatives you've considered**

**Additional context**
In the source code
for (i = 1; i < argc; i++)
    {
        if (argv[i][0] != '-')
            break;
        if (!strcmp(argv[i], "-a"))
            append++;
        else
            usage();
        optind++;
    }

**Comment by k-takata** [comment]
Why do you think it is not safe?

**Comment by real-watson** [comment]
Because we should ensure that strings are null terminated before passing into function strcmp(). This can be enforced by always placing a \\0 in the last allocated byte of the buffer.

**Comment by k-takata** [comment]
It is ensured that both `argv[i]` and `"-a"` are null terminated.

**Comment by real-watson** [comment]
Well, I got this, thanks.
