### ISSUE TITLE
vim9script: some expr1 variables not recognised (echom <expr1>)

### ISSUE THREAD

**Issue by puremourning** [vim/vim#5670]
**Describe the bug**

In a script with `vim9script` at the top, some variables (function arguments, locals) are not recognised  when calling `echom`. I _susepct_ this applies to other expression arguments to normal commands, but that's mostly a guess.

**To Reproduce**

* `vim --clean -S test-function.vim`

`test-function.vim`

```
vim9script

function TestF( a )
  let x = 'x: ' .. a:a
  echom x
  echom a:a
endfunction

call TestF( 'test function' )
```

Result:

```
Error detected while processing function <SNR>97_TestF:
line    1:
E121: Undefined variable: a:a
line    2:
E121: Undefined variable: x
line    3:
E121: Undefined variable: a:a
```

The same occurs with `test-def.vim`

```
vim9script

def TestD( a:string ): void
  let x:string = 'x: ' .. a
  echom x
  echom a
enddef

call TestD( 'test def' )
```

result:

```
Error detected while processing function <SNR>97_TestD:
line    1:
E121: Undefined variable: x
E121: Undefined variable: a
```

**Expected behavior**

`echom` recognises arguments and other function-local variables and outputs 'x: test function` then 'test function`

**Environment (please complete the following information):**
 - Vim version [e.g. 8.1.1234] (Or paste the result of `vim --version`.)

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 20 2020 15:45:39)
macOS version
Included patches: 1-285
```

 - OS: macOS
 - Terminal: iTerm

**Comment by brammool** [comment]
That ":echomsg" doesn't work inside "def" is expected, it's not compiled yet.
The function should work.
