### ISSUE TITLE
cannot input chinese characters using bluetooth keyboard in termux's vim

### ISSUE THREAD

**Issue by MansonLuo** [vim/vim#5675]
cannot input chinese characters using bluetooth in termux's vim

**Comment by k-takata** [comment]
Not enough information.
Can you input Chinese characters in application other than Vim?

**Comment by chrisbra** [comment]
please fill out the issue template. Also, does it work without bluetooth? How about a different terminal emulator? What vim version?

**Comment by k-takata** [comment]
Closing as invalid.
