### ISSUE TITLE
vim9script: Function in dictionary cannot be called with dot without `eval` (and another suggestion)

### ISSUE THREAD

**Issue by Bakudankun** [vim/vim#5676]
**Describe the bug**
Functions in dictionaries cannot be called with dot without `eval` because `:Foo.Bar()` is treated as calling command `Foo` with argument `.Bar()`.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean`
2. Source the next script

```vim
vim9script

let Foo = {}

def Foo.Bar()
  let foo = 'foo'
  foo ..= 'bar'
  echo foo
enddef


eval Foo.Bar() " => foobar
eval Foo['Bar']() " => foobar
Foo['Bar']() " => foobar
:Foo['Bar']() " => foobar
Foo.Bar() " => E492: Not an editor command: Foo.Bar()
```

3. See the output

**Expected behavior**
`:eval` the line if `.Bar()` is following right after `Foo` (as `Foo['Bar']()` do so). 

**Environment (please complete the following information):**
 - Vim 8.2.292 64bit
 - OS: Windows 10 1909
 - Terminal: GUI and cmd

**Another suggestion**
Another suggestion is to require a colon (`:`) for Ex-commands in vim9script, and always treat those lines with colon as a full command line.

A few exceptions (that do not require colon) would be acceptable for the readability of computing functions. I think those exceptions should be restricted in two categories, declarations (`let`, `const`, `function`, `def`, ...) and control flow statements (`if`, `for`, `while`, `try`, `break`, `return`, `end*`, ...).

Currently, if a user want to name a variable `buffer`, they must give up using `buffer` as Ex-command and they must use abbreviations.
Using abbreviations is against readability, and furthermore, while writing every lines users must check above and below lines if the commands are not overlapped, and the variables certainly exist (there are very many short commands in Vim that can be executed if variables are mistyped). This is not smart as a modern programming language.
In legacy Vim script `:substitute('foo', 'bar', 'baz(', 'g')` is equivalent to `:substitute/'foo', 'bar', 'baz/', 'g')`, but what does Vim9 script will do?

Requiring `:` for Ex-commands will increase productivity because users can ensure when lines are treated as a command line or not, and also users can distinguish Vim operation commands from declarations and control flow statements.
`substitute('foo', 'bar', 'baz(', 'g')` will call function, and `:substitute('foo', 'bar', 'baz(', 'g')` will execute command. Obvious!

With this suggestion, above script would be like this:

```vim
:vim9script

let Foo = {}

def Foo.Bar()
  let foo = 'foo'
  foo ..= 'bar'
  :echo foo
enddef

:eval Foo.Bar() " => foo
:eval Foo['Bar']() " => foo
Foo['Bar']() " => foo
Foo.Bar() " => foo
```

and the following lines would throw errors:

```vim
echo foo
:Foo.Bar()
```

Note that this is test script, and the number of colons will be far less in most functions in Vim9 scripts.

**Comment by brammool** [comment]
I like the idea to use a colon to indicate what follows is an Ex command, not a variable or function.
It should only be needed when there is ambiguity. 
Making Foo.Bar() works is part of the implementation work.

**Comment by Bakudankun** [comment]
Thank you for adopting the colon!
Please consider requiring a colon because it is hard for users to predict how complex line Vim9 can recognize as a function call.

```vim
vim9script
:eval 'foo'->{str -> execute('echo str', '')}() " => foo
'foo'->{str -> execute('echo str', '')}() " => E20: Mark not set
```

Is Vim9 meant to treat every lines as function call if that can be evaluated so?

**Comment by brammool** [comment]
> Thank you for adopting the colon!
> Please consider requiring a colon because it is hard for users to
> predict how complex line Vim9 can recognize as a function call.

I don't think we should require a colon for every Ex command.  In
general, it's better to avoid punctuation.

> ```vim
> vim9script
> :eval 'foo'->{str -> execute('echo str', '')}() " => foo
> 'foo'->{str -> execute('echo str', '')}() " => E20: Mark not set
> ```
> 
> Is Vim9 meant to treat every lines as function call that can be evaluated so?

Starting with a string is the one exception.  A double quoted string
can't be reliably distinguised from a comment.  A single quoted string
could be an address with a mark.  We could recognize most of these, but
then we run into unexpected corner cases.  This would work:

	'string'->len()

But this won't:
	's,.list   '->len()

It gives an error "Trailing characters", but let's not make this
complicated and say that you can't start a command with a string.

-- 
From "know your smileys":
 C=}>;*{)) Drunk, devilish chef with a toupee in an updraft,
	   a mustache, and a double chin

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Bakudankun** [comment]
> This would work:
> 
> 	'string'->len()
> 
> But this won't:
> 	's,.list   '->len()
> 
> It gives an error "Trailing characters", but let's not make this
> complicated and say that you can't start a command with a string.

Would this be made to work? (currently not working)

```vim
('s,.list   ')->len()
("double-quoted string")->len()
```

If so, we can avoid the corner case and can ensure that lines starting with a `(` will be `:eval`-ed.

**Comment by brammool** [comment]
> > This would work:
> > 
> > 	'string'->len()
> > 
> > But this won't:
> > 	's,.list   '->len()
> > 
> > It gives an error "Trailing characters", but let's not make this
> > complicated and say that you can't start a command with a string.
> 
> Would this made to work? (currently not working)
> 
> ```vim
> ('s,.list   ')->len()
> ("double-quoted string")->len()
> ```
> 
> If so, we can avoid the corner case and can ensure that lines starting with a `(` will be `:eval`-ed.

Yeah, that should work.  It's a bit like using ":eval", but without
actually using an Ex command.  I don't see any way a valid Ex command
line could start with "(" before.

-- 
From "know your smileys":
 |-(	Contact lenses, but has lost them

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Bakudankun** [comment]
Thanks, then we can ensure a line to be treated as a Ex command with a colon, and as a expression by enclosing the line in parentheses.
I'm glad I didn't suggest you to add joke commands `:)` and `:(` !
(Well, `:)` could be injected for now, though.)

I'm happy enough, but I hope Vim9 to break bad habits of legacy Vim script.


By the way, it seems to me that patch 8.2.0294 is not taking effect. Sourcing next script shows me errors and creates buffer with "something" in it. Is there anything wrong with me?

(Windows 10 Pro 64bit 1909 / Vim 8.2.303 64bit from vim/vim-win32-installer)

```vim
vim9script
def Test_substitute_cmd()
  new
  setline(1, 'something')
  :substitute(some(other(
  " => E116: Invalid arguments for function (three times)
  assert_equal('otherthing', getline(1))
enddef

Test_substitute_cmd()
```

**Comment by brammool** [comment]
> Thanks, then we can ensure a line to be treated as a Ex command with a
> colon, and as a expression by enclosing the line in parentheses.
> I'm glad I didn't suggest you to add joke commands `:)` and `:(` !
> (Well, `:)` could be injected for now, though.)
> 
> I'm happy enough, but I hope Vim9 to break bad habits of legacy Vim script.
> 
> 
> By the way, it seems to me that patch 8.2.0294 is not taking effect.
> Sourcing next script shows me errors and creates buffer with
> "something" in it. Is there anything wrong with me?

The test wasn't done in Vim9 script context.  When it is then the
leading colons are stripped.  I'll fix it.


-- 
To be rich is not the end, but only a change of worries.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
