### ISSUE TITLE
Zero-width textprops get highlighted

### ISSUE THREAD

**Issue by axelf4** [vim/vim#5678]
Zero-width text properties get highlighted even though the documentation explicitly states they should not be:

> When neither "length" nor "end_col" are given the property will be zero-width.  That means it will not be highlighted — From the help file `textprop.txt`

To reproduce:
1. Run `vim --clean`
2. Source the following script:
    ```vim
    call prop_type_add('foo', #{highlight: 'TODO'})
    call prop_add(1, 1, #{type: 'foo'})
    ```
3. Insert text on the line.
4. The text property gets highlighted (!) as if being of length one.

![bad-zw-textprop-hl](https://user-images.githubusercontent.com/3679678/75095931-3de58d00-559a-11ea-82ea-877413f405ca.png)
*Screenshot of issue along with output of `:echomsg prop_list(1)`*

Environment:
 - Vim version: 8.2.251
 - OS: Ubuntu 18.04
 - Terminal: tmux in Alacritty

**Comment by brammool** [comment]
This is a mistake in the documentation, a zero-width text property will apply to one character.  To avoid highlighting use a property type without highlighting.
