### ISSUE TITLE
Textprops break apart when splitting line

### ISSUE THREAD

**Issue by axelf4** [vim/vim#5683]
Any attempts at, in insert mode or whatever, splitting a continuous text property over multiple lines actually creates new separate text properties, instead of extending the one that was already there. This complicates matters when text properties are used for semantic purposes, for example snippet plugins could want to track edits to placeholders.

To reproduce: With the following, where `#` represents one continuous text property which the cursor is inside

    Lorem ###|### ipsum

typing `<CR><CR><Up>...` produces

    Lorem ###
    ...|
    ### ipsum

where `...` is not in the text property that has been split into two separate ones. This is contrary to what one would expect - that insertions/edits confined to the interior of a textprop should remain inside.

![split-textprop](https://user-images.githubusercontent.com/3679678/75099043-5b781e00-55bd-11ea-85e0-4d6ce57f59e7.png)

Environment:
 - Vim version: 8.2.251
 - OS: Ubuntu 18.04
 - Terminal: tmux in Alacritty

**Comment by lacygoill** [comment]
Since the issue has been fixed, this todo item is no longer relevant:
https://github.com/vim/vim/blob/2f1228463aa9ff62814f9732561b1849e5f01f75/runtime/doc/todo.txt#L187
