### ISSUE TITLE
"]c" and "[c" don't generate any errors when there's no change for the cursor to move to

### ISSUE THREAD

**Issue by lkintact** [vim/vim#5686]
Line `247` of `doc/diff.txt` says: "It is an error if there is no change for the cursor to move to."

Perhaps this means an error message should be displayed in the described situation, which doesn't happen: when you hit <kbd>]</kbd><kbd>c</kbd> with the cursor on the last diff (or <kbd>[</kbd><kbd>c</kbd> on the first respectively), Gvim just doesn't move the cursor without displaying any errors.

OS: Windows Home 1803,
Gvim: https://github.com/vim/vim-win32-installer/releases/download/v8.2.0303/gvim_8.2.0303_x86.zip

**Comment by brammool** [comment]
There is no error message but it rings the bell.  It also aborts any pending mapping.
