### ISSUE TITLE
When opening a YAML file the default shiftwidth should be 2

### ISSUE THREAD

**Issue by madonius** [vim/vim#5697]
Currently when a YAML file is being opened, vim's default `shiftwidth` is 8. The current, de-facto, industry standard is 2 spaces

Ideally, in a similar manner to the [python default](https://github.com/vim/vim/blob/master/runtime/ftplugin/python.vim#L118) the `shiftwidth` should be set to 2.

The alternative option is that users set the `shiftwidth` in a local configuration. Considering the extent of the 2 spaces indentation practice, this would be the majority.

**Comment by k-takata** [comment]
Have you contacted the maintainer of the files?

> Ideally, in a similar manner to the [python default](https://github.com/vim/vim/blob/master/runtime/ftplugin/python.vim#L118) the `shiftwidth` should be set to 2.

[PEP-8](https://www.python.org/dev/peps/pep-0008/#indentation) says:

> Use 4 spaces per indentation level.

Doesn't this mean `shiftwidth` should be set to 4?

**Comment by brammool** [comment]
Included #5698
