### ISSUE TITLE
Haiku: Segmentation violation

### ISSUE THREAD

**Issue by bitigchi** [vim/vim#5700]
Haiku build fails with GUI enabled. Vim 8.2.320, latest Haiku nightly.
This is a tracking issue from the original PR (#5605).

**To Reproduce**
1. Get a fresh copy of Vim on latest Haiku
2. Run following commands to build Haiku on `vim/src/`

```make
  ./configure --prefix=`finddir B_SYSTEM_NONPACKAGED_DIRECTORY` \
     --datarootdir=`finddir B_SYSTEM_NONPACKAGED_DATA_DIRECTORY` \
     --mandir=`finddir B_SYSTEM_NONPACKAGED_DIRECTORY`/documentation/man \
   make clean
   make install
```
3. See the error below

**Expected behavior**
1. Vim should build fine with Haiku GUI support enabled.

**Error**
```make
gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_HAIKU    -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/beval.o beval.c
In file included from structs.h:110,
                from vim.h:1847,
                from beval.c:11:
beval.c: In function 'get_beval_info':
beval.c:154:21: error: 'BalloonEval' {aka 'struct BalloonEvalStruct'} has no member named 'y'
 row = Y_2_ROW(beval->y);
                    ^~
gui.h:117:24: note: in definition of macro 'Y_2_ROW'
# define Y_2_ROW(y) (((y) - gui.border_offset) / gui.char_height)
                       ^
beval.c:155:21: error: 'BalloonEval' {aka 'struct BalloonEvalStruct'} has no member named 'x'
 col = X_2_COL(beval->x);
                    ^~
gui.h:113:24: note: in definition of macro 'X_2_COL'
# define X_2_COL(x) (((x) - gui.border_offset) / gui.char_width)
                       ^
Makefile:3218: recipe for target 'objects/beval.o' failed
make: *** [objects/beval.o] Error 1
```

**Comment by bitigchi** [comment]
Could this be related to the linking of the build? So I was comparing the linking of two builds available:

Latest version, compiled manually:

```
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -Wl,--as-needed -o vim        -lm -lncurses -lnetwork  -lintl
```

8.1.1240, compiled through Haikuports recipe

```
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -I/packages/python-2.7.17-1/.self/develop/headers/python2.7                 -fPIC -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1  
Linking: gcc   -L. -lssp -fstack-protector-strong -Wl,-export-dynamic  -Wl,--as-needed -o vim        -lm -lncurses -lnetwork  -liconv -lintl
```

8.1.1240, GUI, compiled through Haikuports recipe

```
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_HAIKU    -I/packages/
python-2.7.17-1/.self/develop/headers/python2.7                 -fPIC -U_FORTIFY
_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -lssp -fstack-protector-strong -Wl,-export-dynamic  -Wl,--as-
needed -o vim -lbe -lroot -ltracker -ltranslation -lsupc++ -lstdc++       -lm -l
ncurses -lnetwork  -liconv -lintl
```

If I want to link the missing flags to the current version, do I have to go and add them to ./configure manually? I would like to try to configure with these flags but I'm not sure where to put them in configure.ac and such.

**Comment by bitigchi** [comment]
If I build with `--with-features=big`, it fails below:

```
gui_haiku.cc: In function 'void gui_mch_set_text_area_pos(int, int, int, int)':
gui_haiku.cc:3585:1: error: a function-definition is not allowed here before '{' token
 {
 ^
```

And the same error in lines 3611, 3653, 3669, 3700, 3728, 3740, 3758, 3779, 3794, 3801, 3816, 3923, 3944, 3957, 3968, 3997, 4027, 4046, 4053, 4071, 4238, 4252, 4265, 4276, 4285, 4294, 4306, 4312, 4338, 4358, 4371, 4383, 4395, 4421, 4450, 4470, 4533, 4552, 4561, 4576, 4588, 4600, 4615, 4626, 4679, 4685, 4699, 4747, 4797, 4820, 4830, 4836, 4870, 4921, 4930, 4943, 5015, 5077, 5091, 5100, 5108, 5120, 5127, 5145, 5159, 5175, 5185, 5229.

Plus:
```
gui_haiku.cc:5240:1: error: expected '}' at end of input
 }
 ^
gui_haiku.cc:3562:29: note: to match this '{'
  if (gui.vimWindow->Lock()) {
                             ^
gui_haiku.cc:5240:1: error: expected '}' at end of input
 }
 ^
```

**Comment by bitigchi** [comment]
I've fixed the above build errors, and `make` finishes without any errors. However, when I run `gvim` I get a segmentation violation:

> Vim: Caught deadly signal SEGV
Vim: Finished.
Segmentation violation

I've compiled Vim with the debug flag, but have no idea how to proceed further. Any ideas?

For reference, [these](https://github.com/bitigchi/vim/commits/fix_haiku_build) are the commits that contains the fixes.

**Comment by dpelle** [comment]
Try with gdb:
```
$ cd vim/src
$ gdb --args ./vim -f -g
(gdb) run
```
And if it crashes, use gdb `bt` command to get the stack:
```
(gdb) bt
```

**Comment by bitigchi** [comment]
@dpelle, thanks for the instructions. Now I can launch gvim just fine, but i see black boxes instead of toolbar icons. I guess one thing at a time. Below is the gdb output:

```Starting program: /boot/home/vim_emir/src/vim -f -g
[tcsetpgrp failed in terminal_inferior: Invalid Argument]
Error while mapping shared library sections:
commpage: Invalid Argument.
Error while reading shared library symbols:
commpage: No such file or directory.
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
Error while reading shared library symbols:
Dwarf Error: wrong version in compilation unit header (is 4, should be 2) [in module /boot/system/lib/libintl.so.8.1.5]
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
Error while reading shared library symbols:
commpage: No such file or directory.
Error while reading shared library symbols:
Dwarf Error: wrong version in compilation unit header (is 4, should be 2) [in module /boot/system/lib/libintl.so.8.1.5]
(no debugging symbols found)
Error while reading shared library symbols:
commpage: No such file or directory.
Error while reading shared library symbols:
Dwarf Error: wrong version in compilation unit header (is 4, should be 2) [in module /boot/system/lib/libintl.so.8.1.5]
Error while reading shared library symbols:
commpage: No such file or directory.
Error while reading shared library symbols:
Dwarf Error: wrong version in compilation unit header (is 4, should be 2) [in module /boot/system/lib/libintl.so.8.1.5]
(no debugging symbols found)
Error while reading shared library symbols:
commpage: No such file or directory.
Error while reading shared library symbols:
Dwarf Error: wrong version in compilation unit header (is 4, should be 2) [in module /boot/system/lib/libintl.so.8.1.5]
Error while reading shared library symbols:
commpage: No such file or directory.
Error while reading shared library symbols:
Dwarf Error: wrong version in compilation unit header (is 4, should be 2) [in module /boot/system/lib/libintl.so.8.1.5]
(no debugging symbols found)
```

Edit: I've found out that above wrong version errors could be related to the gdb version. Will try with a newer one.

**Comment by dpelle** [comment]
So vim does not crash with gdb but crashes without gdb?
I did not expect that.  I was hoping to see a crash with gdb
and get a stack trace.

When you run it without gdb, do you get a core dump?

Try:
```
$ ulimit -c unlimited
$ cd vim/src
$ ./vim -f -g
```
And I assuming it crashes and produces a `core` file, look at it with gdb using:
```
$ gdb vim core
$ (gdb) bt
…
```

**Comment by dpelle** [comment]
I'm not sure whether asan (address sanitizer) works with haiku,
but you may give it a try.

To try it, uncomment this line in vim/src/Makefile:
```
SANITIZER_CFLAGS = -g -O0 -fsanitize=address -fno-omit-frame-pointer
```
Then build and run vim normally.
Invalid memory access (if any) will produce useful information on stderr.
```
$ make clean
$ make 
$ ./vim -f -g 2> asan.log
$ cat asan.log
```

**Comment by bitigchi** [comment]
@dpelle, I get `... cannot find -lasan` eventually.

I did `ulimit -c`, (with output 0) it does not recognise `unlimited` in Haiku, and was able to launch gvim fine. Maybe one of my fixes cause this issue?

To be clearer, it launches normally with `./vim -f -g`.

I might be wrong, but it seems that the error is caused by the discrepancy between how Haiku handles GUI processes. I believe this is no easy fix, but still, this will allow Vim to be updated via Haikuporter, which is the de-facto standard way of installing new packages. I will approach Haiku developers about how to handle this in a more thorough way.

**Comment by bitigchi** [comment]
This is fixed. I don't get a SEGV anymore with the latest version.
