### ISSUE TITLE
I got auto-transparent that don't expect after enable true color.

### ISSUE THREAD

**Issue by roachsinai** [vim/vim#5703]
I enabled true color by:

```
" https://lotabout.me/2018/true-color-for-tmux-and-vim/
if has("termguicolors")
    " fix true color not work under tmux
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
    " enable true color
    set termguicolors
endif
```

It works for true color. But each time I use vim it enable transparent by it self.

![image](https://user-images.githubusercontent.com/9500049/75415633-29710e00-5967-11ea-8084-59574c659ab3.png)

If I remove that setting, the transparent effect disappear:

![image](https://user-images.githubusercontent.com/9500049/75415709-5ae9d980-5967-11ea-89bc-d06f15ddda59.png)

**Environment (please complete the following information):**
 - Vim version：VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 26 2020 11:45:38)
 包含补丁: 1-148
 编译者 Arch Linux
 巨型版本 with GTK3 GUI.
 - OS: Manjaro
 - Terminal: konsole

**Comment by k-takata** [comment]
What is your expected behavior?
It should not be transparent on true color, or it should be transparent on non-true color?
Are there any transparent-related-settings in konsole?

**Comment by roachsinai** [comment]
Thanks for your reply! It should not be transparent on true color!

Yeah I have transparent-related-settings in konsole, but it already there, and work fine with vim (no auto transparent) if I not using true color.

**Comment by chrisbra** [comment]
What color scheme is this?

**Comment by roachsinai** [comment]
@chrisbra it's gruvbox https://github.com/morhetz/gruvbox

**Comment by chrisbra** [comment]
Please check the output of `:hi Normal`. This might be a color scheme issue.

**Comment by roachsinai** [comment]
I got this:

```
:hi Normal
Normal         xxx ctermfg=223 ctermbg=235 guifg=#ebdbb2 guibg=#282828
```

You mean the `xxx`? I don't know much about color scheme.

**Comment by roachsinai** [comment]
Yeah, I tried other color schme like https://github.com/sainnhe/sonokai

It works fine, no this issue.

**Comment by chrisbra** [comment]
> I got this:
> 
> ```
> :hi Normal
> Normal         xxx ctermfg=223 ctermbg=235 guifg=#ebdbb2 guibg=#282828
> ```
> 
> You mean the `xxx`? I don't know much about color scheme.

That looks fine. This should not be transparent. In any case, you might want to discuss this with the colorscheme author further.

**Comment by roachsinai** [comment]
OK, I will make a thread about this. Thanks!
