### ISSUE TITLE
C syntax highlighting bug with uncommented #include

### ISSUE THREAD

**Issue by Boobies** [vim/vim#5705]
Try the following:
```
/* */ #include <stdio.h>
```

or

```
/*
*/ #include <stdio.h>
```

The `#include` directive will not be properly highlighted.

**Comment by chrisbra** [comment]
Is that actually valid syntax?

**Comment by Boobies** [comment]
Yes. According to section 5.1.1.2 of the C standard, comments are replaced by a space character before `#include` preprocessing directives are interpreted. Also, tested with GCC, just in case.

I suspect this also has to be fixed for other languages (C++ and Objective-C come to mind), if they do not share the same syntax highlighting code as far as preprocessing goes. I have not investigated the issue any further than this.

**Comment by Boobies** [comment]
What you probably had in mind was something along the lines of:

```
#define EMPTY
EMPTY #include <stdio.h>
```

where `#include` is indeed not a preprocessing directive because `EMPTY` will not have been replaced at the end of the 4th translation phase, as defined in the specification. This already works as expected.

It's just a matter of how the translation phases are ordered. I incidentally came across this bug because I'm doing some C parsing myself and was writing some test files in Vim.

**Comment by brammool** [comment]
Not all valid syntax can be recognized.  The highlighting is pattern based, it is not a full parser.
This construct is unusual enough that we don't need to support it.
I would discourage writing it like that anyway, better put the comment above the #include.
