### ISSUE TITLE
opening two popup terminals may cause a crash

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#5707]
**Describe the bug**

Opening two popup terminals may cause a crash.

**To Reproduce**

Run this shell command:

    vim -Nu NONE +'eval range(2)->map({-> term_start(&shell, #{hidden: 1})->popup_create({})}) | eval range(2)->map({-> popup_close(win_getid())})'

Vim crashes.

**Expected behavior**

Vim doesn't crash.

**Environment**

 - Vim version: 8.2 Included patches: 1-326
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

I guess the issue is that when a popup terminal is open, it is currently allowed to open a second one, while it should probably be forbidden.

Here are:

   - [a backtrace](https://github.com/vim/vim/files/4266358/backtrace.txt)
   - [a valgrind log](https://github.com/vim/vim/files/4266359/valgrind.log)
   - [an asan log](https://github.com/vim/vim/files/4266361/asan.log)

**Comment by brammool** [comment]
Not sure if we need to forbid opening two terminal popup windows, I can avoid the crash without that.
But then focus doesn't go back to the right window.  I'll fix that. 
Please do keep a look out for any other problems, we may have to disallow two terminal popup windows.
