### ISSUE TITLE
Python fstring syntax

### ISSUE THREAD

**Issue by ghost** [vim/vim#5718]
Python has supported so called "[f-strings](https://docs.python.org/3.6/whatsnew/3.6.html#pep-498-formatted-string-literals)" for string interpolation since 3.6. Vim's bundled python syntax file should support f-strings like the JavaScript syntax file works with [template strings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals).

**Comment by chrisbra** [comment]
please contact the syntax script maintainer.

**Comment by zvezdan** [comment]
I'm the maintainer. I'll prepare this change together with some other updates to the runtime file.

**Comment by chrisbra** [comment]
closing then.

**Comment by ghost** [comment]
@zvezdan could you please @<span></span>mention me when you make the changes?
