### ISSUE TITLE
[Feature Request][Contribution Advice] Adding Vimtutor lessons

### ISSUE THREAD

**Issue by sunwukonga** [vim/vim#5719]
The `vimtutor` is an excellent resource and I always point new users to it when learning vim. I love the tutor, but I feel that it stops short of exploring some vim features that I use constantly myself. To remedy this, I'd like to contribute some of my Sunday's to adding lessons to the tutor.

Specifically, I was thinking to add lessons on:
1. Registers (yanking and pasting to and from, and listing) [replacing text with text from register]
2. Buffers (new buffer, listing, navigating {by number and completion}, closing)
3. Macros (creating, editing, using, highlight crossover with Registers) 
4. Windows (splitting, navigating, closing) [already touched peripherally because of :help]
5. Tabs (new tabs, navigating, closing) [left till last because Buffers are a better solution to the problem most people try to solve with Tabs]

**Comment by brammool** [comment]
There are many things that could be added to the tutor, but the longer it gets the less useful it becomes overal. It's probably better to make a "part 2".  So the user would to the current tutor, then go use Vim for a while, and when feeling the need to learn more do "part 2".  It avoids "learning fatigue".

**Comment by sunwukonga** [comment]
Understood. What would be the best way to add a part 2? There's already a cmdline switch for choosing languages, could a switch be added select a "second chapter"?
 * `vimtutor -c 2` 
with a default of `-c 1`

I.e. 
```
vimtutor [-g] [language] [-c] [chapter] [--list]
```
Where `--list` can list the chapters with a short description?

**Comment by sunwukonga** [comment]
Seems the likeliest route is to add a `tutor/tutor02.vim` file to handle all files/translations for chapter two, as `tutor/tutor.vim` does for the original.

Chapter two files would be `tutor02`, `tutor02.utf`, ...`tutor02.xx.*`

`vimtutor` (and `vimtutor.bat`) would select the appropriate chapter config based on `-c cc`

`--list` would need to be a hard-coded list like:
```
01 (default) - {bar, bg, ca, cs, da, de, el, en (default), eo, es, fr, hr, hu, it, ja, ko, lv, nb, nl, no, pl, pt, ru, sk, sr, sv, tr, uk, vi, zh} 
02 - {en (default)}
```
And updated when translations or chapters added.

**Comment by pmerry96** [comment]
I saw this was still open, what else can be done in the vimtutor section?

I thought about building a vimtutor lesson concerning the vimrc, and then perhaps include a 'settings pane' option in the vimtutor lesson where new users could get the basics of a .vimrc file laid out for them.

Things I would be adding:
- Vimtutor lesson 3 - the vimrc file
- A program to view, select and change settings fields in a vimrc, existing or not.
- (Skill and Time Permitting) support for real time vimrc updating

This would be my first contribution to an Open source project, but I am fairly well versed in C and C++. I plan on opening another issue/making a pull request for this idea, but am also open to feedback. Please let me know what you might add or change about the idea!
