### ISSUE TITLE
indent/php.vim : PHP_BracesAtCodeLevel misses the closing brace

### ISSUE THREAD

**Issue by jolan78** [vim/vim#5722]
Since https://github.com/vim/vim/commit/bcb9898eba8c7dd7ed9a909c7055b2ab49cd8f6c#diff-9e960cf7c450293f34eac61702755b5e, PHP_BracesAtCodeLevel do not indent the closing brace (`}`) of a block.
This bug was introduced by https://github.com/2072/PHP-Indenting-for-VIm/commit/3bd7a43
Since the original author do not work on this project anymore (see https://github.com/2072/PHP-Indenting-for-VIm/issues/74) I am reporting it here.

**To Reproduce**
1. Run `vim -u NONE`
2. set up indent : 
    `:syntax on` (or indent the file after the fact)
    `:let g:PHP_BracesAtCodeLevel=1`
    `:filetype indent plugin on`
3. Edit a new file: `:e test.php`
3. Type : 
   `<?php<CR>function test()<CR>{<CR>}<CR>`
4. When you hit return after the last '}', it is de-indented : 
```
<?php
function test()
    {
}
```

**Expected behavior**
As stated in the documentation (`:help php-indent`), the closing brace should stay at code level : 
```
<?php
function test()
    {
    }
```

**Environment :**
 - Vim 8.1.1368
 - OS: macOS 10.14
 - Terminal: iTerm2

**Comment by chrisbra** [comment]
looks like this has been fixed upstream. I guess it will be included with one of the next runtime files update.
