### ISSUE TITLE
Non acsii characters in tag's kinds

### ISSUE THREAD

**Issue by coot** [vim/vim#5724]
When a non ascii character is present as a kind for a tag vim displays it differently from ascii ones.
See attached screenshot which contains a λ as a kind of a tag (a nice tag for lambdas, btw):
![Screenshot from 2020-03-03 09-47-17](https://user-images.githubusercontent.com/698209/75758606-9f44f300-5d34-11ea-891e-deacac95abfd.png)

Supporting any utf-8 encoded character could make the kind field more useful.

There is place to put more than a single character under `kind` (up to 4) - using all of them would also be useful.

**Comment by coot** [comment]
The work a round this is to encode the tag kind using field syntax `kind:λ`

**Comment by brammool** [comment]
Please check that the patch fixes your problem.
