### ISSUE TITLE
umask

### ISSUE THREAD

**Issue by hdatma** [vim/vim#5725]
The following behavior occurs on MacVim, the graphical vim for Mac OSX. Posting it here, because the graphical part is irrelevant to the case at hand. 

Vim saves any new file with the following permissions: "-r--r--rw- ".

The local umask is 0022, so the permissions should be "-rw-r--r--".

**Environment (please complete the following information):**

 >/Applications/MacVim.app/Contents/MacOS/Vim --version
                                                                                                                                                                                   
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 29 2019 10:40:52)
macOS version
Included patches: 1-2224
Compiled by sb@alice
Normal version with MacVim GUI.  Features included (+) or not (-):
+acl               +file_in_path      -mouse_urxvt       -tcl
-arabic            +find_in_path      +mouse_xterm       -termguicolors
+autocmd           +float             +multi_byte        -terminal
-autochdir         +folding           +multi_lang        +terminfo
-autoservername    -footer            -mzscheme          +termresponse
+balloon_eval      +fork()            -netbeans_intg     +textobjects
-balloon_eval_term +fullscreen        +num64             +textprop
+browse            -gettext           +odbeditor         +timers
+builtin_terms     -hangul_input      +packages          +title
+byte_offset       +iconv             +path_extra        +toolbar
+channel           +insert_expand     -perl              +transparency
+cindent           +job               +persistent_undo   +user_commands
+clientserver      +jumplist          +postscript        -vartabs
+clipboard         -keymap            +printer           +vertsplit
+cmdline_compl     +lambda            -profile           +virtualedit
+cmdline_hist      -langmap           -python            +visual
+cmdline_info      +libcall           -python3           +visualextra
+comments          +linebreak         +quickfix          +viminfo
-conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          -rightleft         +wildignore
-cscope            +localmap          -ruby              +wildmenu
+cursorbind        -lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con_gui    +mksession         +smartindent       -X11
+diff              +modify_fname      -sound             -xfontset
+digraphs          +mouse             +spell             +xim
+dnd               +mouseshape        +startuptime       -xpm
-ebcdic            -mouse_dec         +statusline        -xsmp
-emacs_tags        -mouse_gpm         -sun_workshop      -xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          -mouse_netterm     +tag_binary        
+extra_search      +mouse_sgr         -tag_old_static    
-farsi             -mouse_sysmouse    -tag_any_white     
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -O2   -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework AppKit 

>uname -a

Darwin alice 17.7.0 Darwin Kernel Version 17.7.0: Sun Dec  1 19:19:56 PST 2019; root:xnu-4570.71.63~1/RELEASE_X86_64 x86_64

Default OSX Terminal.

**Comment by chrisbra** [comment]
are you sure the umask is actually set correctly? Please provide complete steps to reproduce. 
Start from a terminal prompt and set the umask, e.g.

    ~$ umask 0022
    ~$ vim --clean testfile_umask -c ':wq'
    ~$ ls -l testfile_umask

**Comment by hdatma** [comment]
## This is your test from the command line:

 > umask 0022
 >/Applications/MacVim.app/Contents/MacOS/Vim --clean testfile_umask -c ':wq'                                                               
 >ls -l testfile_umask 
 -rw-r--r--  1 me  staff  0 Mar  3 20:34 testfile_umask

## This is the same test from the GUI:

- new tab
- i
- sample text
- esc
- File > Save As > Desktop > Untitled.txt

> ls -l ~/Desktop/Untitled.txt
-r--r--rw-  1 me  staff  5 Mar  3 20:37 /Users/me/Desktop/Untitled.txt

I am forwarding the case to MacVim.app.

**Comment by chrisbra** [comment]
could it be, that your gui vim does not know the actual umask? This might actually be a configuration issue. Anyhow, closing.
