### ISSUE TITLE
b:match_keywords for fortran lacks of defitinions for conditional pragma compilation directives

### ISSUE THREAD

**Issue by aitzkora** [vim/vim#5734]
Sometimes fortran files contains compilation conditional pragma statements like in

```fortran
program simple
   integer :: a,c

   read(*,*) a
   if (a==2 ) then
#if DEBUG
      print *,a
#endif
     c=a+2
   else 
#if DEBUG
      print *, a
#endif
      c = a -2
   end if
   print *,c
end program simple
````
In this program, #endif or #if keywords will make a mess for parsing keywords...

**Is your feature request related something that is currently hard to do? Please describe.**
the solution is to add to the fortran ftplugin the keywords corresponding to these pragma

**Describe the solution you'd like**
Manually I found the following solution : type 
```vim
let b:match_words = b:match_words . '^\s*#\s*if\(\|def\|ndef\)\>:^\s*#\s*elif\>:^\s*#\s*else\>:^\s*#\s*endif\>'
```
in my fortran file window. It is possible to add the keywords to the fortran ftplugin ?

**Comment by chrisbra** [comment]
can you please prepare a PR against the [fortran ftplugin file](https://github.com/vim/vim/blob/master/runtime/ftplugin/fortran.vim)?

**Comment by aitzkora** [comment]
I could prepare a PR, but I need some informations 
 - Could I also modify fortran extensions because those directives appear in .F90, .F77, .F files (fortran with preprocessor macros)
 -  How do your locally test that modifications are OK ? Is there a classical way, because those files are normally system wide, and I need to test without interfere with plugins

**Comment by brammool** [comment]
You can try out a modified runtime file by putting it in your ~/.vim directory.  E.g. ~/.vim/syntax/fortran.vim
Setting b:current_syntax should prevent the system-wide default script to be interfering.

**Comment by dkearns** [comment]
It appears I sent Ajit a patch for this in September along with some other changes which he acknowledged.  I'd consider it incoming.

```diff
diff --git a/runtime/ftplugin/fortran.vim b/runtime/ftplugin/fortran.vim
index 26dc90a18..6a016b3f3 100644
--- a/runtime/ftplugin/fortran.vim
+++ b/runtime/ftplugin/fortran.vim
@@ -105,12 +105,13 @@ if !exists("b:match_words")
   let s:notselect = '\%(\<select\s\+\)\@<!'
   let s:notelse = '\%(\<end\s\+\|\<else\s\+\)\@<!'
   let s:notprocedure = '\%(\s\+procedure\>\)\@!'
+  let s:nothash = '\%(^\s*#\s*\)\@<!'
   let b:match_ignorecase = 1
   let b:match_words =
     \ '(:),' .
     \ '\<select\s*case\>:' . s:notselect. '\<case\>:\<end\s*select\>,' .
     \ s:notelse . '\<if\s*(.\+)\s*then\>:' .
-    \ '\<else\s*\%(if\s*(.\+)\s*then\)\=\>:\<end\s*if\>,'.
+    \ s:nothash . '\<else\s*\%(if\s*(.\+)\s*then\)\=\>:' . s:nothash . '\<end\s*if\>,'.
     \ 'do\s\+\(\d\+\):\%(^\s*\)\@<=\1\s,'.
     \ s:notend . '\<do\>:\<end\s*do\>,'.
     \ s:notelse . '\<where\>:\<elsewhere\>:\<end\s*where\>,'.
@@ -122,7 +123,8 @@ if !exists("b:match_words")
     \ s:notend . '\<subroutine\>:\<end\s*subroutine\>,'.
     \ s:notend . '\<function\>:\<end\s*function\>,'.
     \ s:notend . '\<module\>' . s:notprocedure . ':\<end\s*module\>,'.
-    \ s:notend . '\<program\>:\<end\s*program\>'
+    \ s:notend . '\<program\>:\<end\s*program\>,'.
+    \ '\%(^\s*\)\@<=#\s*if\%(def\|ndef\)\=\>:\%(^\s*\)\@<=#\s*\%(elif\|else\)\>:\%(^\s*\)\@<=#\s*endif\>'
 endif
 
 " File filters for :browse e
```

**Comment by brammool** [comment]
Doug -

> It appears I sent Ajit a patch for this in September along with some
> other changes which he acknowledged.  I'd consider it incoming.
> 
> ```diff
> diff --git a/runtime/ftplugin/fortran.vim b/runtime/ftplugin/fortran.vim
> index 26dc90a18..6a016b3f3 100644
> --- a/runtime/ftplugin/fortran.vim
> +++ b/runtime/ftplugin/fortran.vim
> @@ -105,12 +105,13 @@ if !exists("b:match_words")
>    let s:notselect = '\%(\<select\s\+\)\@<!'
>    let s:notelse = '\%(\<end\s\+\|\<else\s\+\)\@<!'
>    let s:notprocedure = '\%(\s\+procedure\>\)\@!'
> +  let s:nothash = '\%(^\s*#\s*\)\@<!'
>    let b:match_ignorecase = 1
>    let b:match_words =
>      \ '(:),' .
>      \ '\<select\s*case\>:' . s:notselect. '\<case\>:\<end\s*select\>,' .
>      \ s:notelse . '\<if\s*(.\+)\s*then\>:' .
> -    \ '\<else\s*\%(if\s*(.\+)\s*then\)\=\>:\<end\s*if\>,'.
> +    \ s:nothash . '\<else\s*\%(if\s*(.\+)\s*then\)\=\>:' . s:nothash . '\<end\s*if\>,'.
>      \ 'do\s\+\(\d\+\):\%(^\s*\)\@<=\1\s,'.
>      \ s:notend . '\<do\>:\<end\s*do\>,'.
>      \ s:notelse . '\<where\>:\<elsewhere\>:\<end\s*where\>,'.
> @@ -122,7 +123,8 @@ if !exists("b:match_words")
>      \ s:notend . '\<subroutine\>:\<end\s*subroutine\>,'.
>      \ s:notend . '\<function\>:\<end\s*function\>,'.
>      \ s:notend . '\<module\>' . s:notprocedure . ':\<end\s*module\>,'.
> -    \ s:notend . '\<program\>:\<end\s*program\>'
> +    \ s:notend . '\<program\>:\<end\s*program\>,'.
> +    \ '\%(^\s*\)\@<=#\s*if\%(def\|ndef\)\=\>:\%(^\s*\)\@<=#\s*\%(elif\|else\)\>:\%(^\s*\)\@<=#\s*endif\>'
>  endif
>  
>  " File filters for :browse e
> ```

Well, let me include it and add a remark to the header.

- Bram

-- 
hundred-and-one symptoms of being an internet addict:
264. You turn to the teletext page "surfing report" and are surprised that it
     is about sizes of waves and a weather forecast for seaside resorts.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dkearns** [comment]
I think this can be closed.  The patch was applied and I'll keep an eye out for future syncing issues when @Ajit-Thakkar next updates.

**Comment by chrisbra** [comment]
thanks!
