### ISSUE TITLE
Cannot load registered type library

### ISSUE THREAD

**Issue by nu8** [vim/vim#5738]
If I get this file:

https://github.com/vim/vim-win32-installer/releases/download/v8.2.0357/gvim_8.2.0357_x86.zip

and start `gvim.exe`, I get this message:

~~~
Vim Initialisation
Cannot load registered type library.
Do you want to register Vim now?
~~~

If I choose No, then it will ask again on next startup. Vim should remember my
preference. I think if a user downloads Zip file over Exe, then they are
intentionally not wanting to register or install anything, and that should be
respected.

**Comment by muv1** [comment]
As a workaround, you can go here:

<https://www.vim.org/download#pc>

and get these:

- GUI executable
   - <https://ftp.nluug.nl/pub/vim/pc/gvim82.zip>
- Runtime files
   - <https://ftp.nluug.nl/pub/vim/pc/vim82rt.zip>

**Comment by k-takata** [comment]
The message is shown when the OLE version is used.
I think that the OLE feature was used mainly by VisVim, but VisVim is not included in the package anymore.
Maybe we don't need to enable the OLE feature?

**Comment by brammool** [comment]
Ken Takata wrote:

> The message is shown when the OLE version is used.
> I think that the OLE feature was used mainly by VisVim, but VisVim is not included in the package anymore.
> Maybe we don't need to enable the OLE feature?

I wonder if OLE is still a thing on Windows.  What would happen if we
remove OLE support?

-- 
hundred-and-one symptoms of being an internet addict:
189. You put your e-mail address in the upper left-hand corner of envelopes.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
I only know that VisVim relied on OLE support.
Other software that relies on it will also stop working, but I don't know such software.

**Comment by jamessan** [comment]
According to https://vim.fandom.com/wiki/VisVim_for_Visual_Studio VisVim hasn't been supported in VisualStudio since 2002.  Maybe it should be removed, since there seem to be other ways to integrate Vim with contemporary versions of VisualStudio.

**Comment by brammool** [comment]
It appears this functionality was already not used much, and by now it doesn't work with modern Windows systems.  I tend to think we can drop VisVim, unless someone says it is still being used.

**Comment by wangzq** [comment]
I personally use OLE feature a lot in my own scripting (powershell or C#) to call Eval or SendKeys, which is faster than using built-in remote server invocation; so I would hate to see this feature getting removed.
