### ISSUE TITLE
On Windows, fnamemodify(..., ":.") can strip the drive letter from the result.

### ISSUE THREAD

**Issue by jpetrie** [vim/vim#574]
On Windows,
- Run `vim` or `gvim` with `-N -u NONE`
- note the current directory via `:pwd`
- execute `:echo fnamemodify("C:\\X\\y.txt", ":.")` (or similar, the important part is that the given filename _not be underneath_ the current working directory).

The result will be something like "\X\y.txt" -- which is unexpected given that the documentation under `:help filename-modifiers` says that ":." will result in an unmodified file name if the file name is not below the current directory.

This occurred on vim 7.4 (patches 1 - 1087), obtained from the Cream distribution. It also happens on the gvim installed by the official installer on the vim.org website (I tried the Cream build in case it had more recent patches to fix the issue).

**Comment by jpetrie** [comment]
I've looked into it a little more and I think the reason this happens is because handling `fnamemodify` eventually calls `shorten_fname` in `fileio.c`, which has this bit of code:

```
/*
 * When using a file in the current drive, remove the drive name:
 * "A:\dir\file" -> "\dir\file".  This helps when moving a session file on
 * a floppy from "A:\dir" to "B:\dir".
 */
else if (len > 3
  && TOUPPER_LOC(full_path[0]) == TOUPPER_LOC(dir_name[0])
  && full_path[1] == ':'
  && vim_ispathsep(full_path[2]))
    p = full_path + 2;
```

...which makes it seem like this drive letter stripping is intentional and useful in scenarios _other than_ `fnamemodify`, but I'm not sure how to suggest fixing `fnamemodify` without breaking the behavior expected in the above comment.

**Comment by jamessan** [comment]
I don't see why this is anything other than a documentation issue.  The path is semantically the same.

**Comment by jpetrie** [comment]
Yeah, it could just be a documentation issue; adjusting the docs to note the potential behavior would certainly seem to me to be the simpler approach. I don't have a strong argument that the behavior should _change_, it just seemed surprising given the current documentation.

**Comment by jpetrie** [comment]
I guess it's also worth noting that `fnamemodify("C:\\X\\y.txt", ":~")` apparently does _not_ drop the drive letter under the same scenarios that `:.` does.
