### ISSUE TITLE
Tag stack is copied to newly opened tab

### ISSUE THREAD

**Issue by johnfrancismccann** [vim/vim#5742]
**Description**
When opening a new tab, the tag stack is copied from the previous tab to the new tab. If a user inadvertently runs `CTRL`-`t` after opening the new tab, the copied top tag is opened in the new tab.

IMHO, this is counterintuitive, as `:tabnew` would in most cases probably be used to open a file different to the one currently open.

**To Reproduce**
1. Files set up as follows:
```
$ ls
hello.cpp	hello.h		main.cpp
$
$ cat hello.h
void hello();
$
$ cat hello.cpp
#include <iostream>
#include "hello.h"

void hello() {
    std::cout << "Hello!" << std::endl;
}
$
$ cat main.cpp
#include "hello.h"

int main() {
    hello();
    return 0;
}
$
$ ctags -R .
$
$ cat tags
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR	Darren Hiebert	/dhiebert@users.sourceforge.net/
!_TAG_PROGRAM_NAME	Exuberant Ctags	//
!_TAG_PROGRAM_URL	http://ctags.sourceforge.net	/official site/
!_TAG_PROGRAM_VERSION	5.8	//
hello	hello.cpp	/^void hello() {$/;"	f
main	main.cpp	/^int main() {$/;"	f
$
```
2. `vim --clean main.cpp`
3. Place cursor over `hello` method call
4. Run `CTRL`-`]` (Vim opens `hello.cpp`)
5. Run `:tabnew blank.txt`
6. Run `CTRL`-`t`
7. Vim opens `main.cpp`

**Expected behavior**
`blank.txt` remains open with a message printed out that the user is at the bottom of the tag stack.

**Environment:**
 - Vim version
```
$ vim --version | head -n 4
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb  3 2020 15:27:20)
macOS version
Included patches: 1-200
Compiled by Homebrew
$
```
 - OS: macOS Sierra 10.12.4, Darwin 16.5.0
 - Terminal: iTerm2

**Comment by brammool** [comment]
> **Description**
> When opening a new tab, the tag stack is copied from the previous tab to the new tab. If a user inadvertently runs `CTRL`-`t` after opening the new tab, the copied top tag is opened in the new tab.
> 
> IMHO, this is counterintuitive, as `:tabnew` would in most cases probably be used to open a file different to the one currently open.

Is this different from opening a new window?  Opening a tab mostly works
like opening a new window.  We should probably keep it that way.

> **To Reproduce**
> 1. Files set up as follows:
> ```
> $ ls
> hello.cpp	hello.h		main.cpp
> $
> $ cat hello.h
> void hello();
> $
> $ cat hello.cpp
> #include <iostream>
> #include "hello.h"
> 
> void hello() {
>     std::cout << "Hello!" << std::endl;
> }
> $
> $ cat main.cpp
> #include "hello.h"
> 
> int main() {
>     hello();
>     return 0;
> }
> $
> $ ctags -R .
> $
> $ cat tags
> !_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
> !_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
> !_TAG_PROGRAM_AUTHOR	Darren Hiebert	/dhiebert@users.sourceforge.net/
> !_TAG_PROGRAM_NAME	Exuberant Ctags	//
> !_TAG_PROGRAM_URL	http://ctags.sourceforge.net	/official site/
> !_TAG_PROGRAM_VERSION	5.8	//
> hello	hello.cpp	/^void hello() {$/;"	f
> main	main.cpp	/^int main() {$/;"	f
> $
> ```
> 2. `vim --clean main.cpp`
> 3. Place cursor over `hello` method call
> 4. Run `CTRL`-`]` (Vim opens `hello.cpp`)
> 5. Run `:tabnew blank.txt`
> 6. Run `CTRL`-`t`
> 7. Vim opens `main.cpp`
> 
> **Expected behavior**
> `blank.txt` remains open with a message printed out that the user is at the bottom of the tag stack.
> 
> **Environment:**
>  - Vim version
> ```
> $ vim --version | head -n 4
> VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb  3 2020 15:27:20)
> macOS version
> Included patches: 1-200
> Compiled by Homebrew
> $
> ```
>  - OS: macOS Sierra 10.12.4, Darwin 16.5.0
>  - Terminal: iTerm2

-- 
hundred-and-one symptoms of being an internet addict:
191. You rate eating establishments not by the quality of the food,
     but by the availability of electrical outlets for your PowerBook.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by johnfrancismccann** [comment]
> Is this different from opening a new window?  Opening a tab mostly works
like opening a new window.  We should probably keep it that way.

I just tested by running `:new blank.txt`, and the tag stack is still copied to the new window.

**Comment by brammool** [comment]
So, that's working as expected.  Is this really a problem?

**Comment by johnfrancismccann** [comment]
It's definitely not a big deal, but I just feel that if a user is opening a completely different file with either `:tabnew` or `:new`, it's more intuitive that a clean, empty tag stack be used.

In step 7 above in the reproduction steps, for example, there is no method call in `main.cpp` that relates to anything the user was looking at in `blank.txt`, yet `main.cpp` gets opened over and above `blank.txt`. In this situation, as far as I know, there is no way for the user to quickly reopen `blank.txt` again without reentering `:tabnew blank.txt`.

Obviously, it could be said, "Well, just don't run `CTRL`-`t` if that's not the behavior that you want!" However, for me, I'm in the habit of always running `CTRL`-`t` after I'm finished looking at a method definition. After doing so, I would prefer to see a message that the tag stack is empty instead of an unrelated file being opened over the one that I was looking at.

**Comment by brammool** [comment]
Well, others may enjoy the current behavior.  In cases like this we prefer to keep it as-is.

**Comment by yugr** [comment]
I wonder if there's some option to get desired behavior (clean tag stack in new windows/tabs).

**Comment by yugr** [comment]
Potential workaround [suggested](https://github.com/vim/vim/pull/17589#issuecomment-3011525576) in PR:
```
:au WinNew * call settagstack(winnr(), {'items' : []})
```
