### ISSUE TITLE
can't close a popup terminal window when its buffer has been replaced by "term_start()"

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#5744]
**Describe the bug**

Sometimes, a popup terminal window can't be closed.

**To Reproduce**

Start Vim like this:

    vim -Nu NONE +'set hidden'

Run this Ex command:

    call popup_create(term_start(&shell, #{hidden: 1}), #{minheight: 10, minwidth: 10}) | call term_start(['sh', '-c', ':'], {'curwin': 1, 'exit_cb': {-> execute('enew')}})

And finally this other Ex command to close the popup terminal window:

    :call popup_close(win_getid())

The window stays open, and `E994: Not allowed in a popup window` is raised.

**Expected behavior**

The window is closed, and no error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-360
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

I don't know how to close this window; I've tried:

    :call popup_close(win_getid())
    :call popup_clear()
    :b#
    :bw!
    :q!
    :close!

All of them fail and raise `E994`.

The only command which works is `:qa!`, but it quits Vim entirely which is not my original purpose.

---

The code in the example may seem contrived, but I found it in a real case scenario.  I have a custom togglable popup terminal, and I'm using the plugin [`fzf.vim`](https://github.com/junegunn/fzf.vim) which can also open its own popup terminal.  If I open my popup terminal, then execute an fzf command which opens a second one, some function in `fzf.vim` raises `E994` and I'm stuck with 2 popup terminals, without the ability to close any of them.

---

I could be wrong, but I think it should be forbidden for `term_start()` to replace a terminal buffer in a popup window via the `exit_cb` key, and possibly via other keys.

**Comment by lacygoill** [comment]
> I could be wrong, but I think it should be forbidden for term_start() to replace a terminal buffer in a popup window via the exit_cb key, and possibly via other keys.

I'm not so sure about that anymore.
The [`fzf`](https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim) Vim plugin does something like this:

   - it invokes [`popup_create()`](https://github.com/junegunn/fzf/blob/7c40a424c0bf5a8967816d51ead6a71a334f30bb/plugin/fzf.vim#L841-L847) to open a popup terminal
   - it invokes [`term_start()`](https://github.com/junegunn/fzf/blob/7c40a424c0bf5a8967816d51ead6a71a334f30bb/plugin/fzf.vim#L768) to run the `fzf` binary inside the popup terminal

If too much is forbidden, it may break some `fzf` commands which currently are working fine...

**Comment by brammool** [comment]
> **Describe the bug**
> 
> Sometimes, a popup terminal window can't be closed.
> 
> **To Reproduce**
> 
> Start Vim like this:
> 
>     vim -Nu NONE +'set hidden'
> 
> Run this Ex command:
> 
>     call popup_create(term_start(&shell, #{hidden: 1}), #{minheight: 10, minwidth: 10}) | call term_start(['sh', '-c', ':'], {'curwin': 1, 'exit_cb': {-> execute('enew')}})
> 
> And finally this other Ex command to close the popup terminal window:
> 
>     :call popup_close(win_getid())
> 
> The window stays open, and `E994: Not allowed in a popup window` is raised.
> 
> **Expected behavior**
> 
> The window is closed, and no error is raised.

It works fine if you remove the "enew" command in the exit callback.
That makes sense, you can't use "enew" in the popup window.

> I don't know how to close this window; I've tried:
> 
>     :call popup_close(win_getid())
>     :call popup_clear()
>     :b#
>     :bw!
>     :q!
>     :close!
> 
> All of them fail and raise `E994`.
> 
> The only command which works is `:qa!`, but it quits Vim entirely which is not my original purpose.

Apparently the popup is in a weird state.  I can type "exit" and the
":q" to close the popup though.

-- 
What is the difference between a professional and an amateur?
The ark was built by an amateur; professionals gave us the Titanic.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> It works fine if you remove the "enew" command in the exit callback.
> That makes sense, you can't use "enew" in the popup window.

You're right, `enew` doesn't make sense here. There is a bug in the `fzf` Vim plugin.  I've found where it comes from; I'll try to fix it.

> Apparently the popup is in a weird state.  I can type "exit" and the
> ":q" to close the popup though.

I can type `exit` but it has no effect, because I'm not in a terminal buffer anymore.

![gif](https://user-images.githubusercontent.com/8505073/76151860-9f891980-60b9-11ea-8173-7d8857046fe8.gif)

I really don't know how to close this window; I think `:enew` should fail and raise `E863` when it's invoked from a `term_start()` callback, just like it would fail if you executed it manually on the command-line.

Otherwise, I really don't know how to close this kind of popup window.

**Comment by lacygoill** [comment]
Alternatively, `popup_close()` should be able to close it, just like it would close a regular popup terminal:

    :call popup_close(win_getid())

**Comment by lacygoill** [comment]
I've just found out that `:pedit` could escape the window (it raises `E994` and `E32`, but the window is still left); then `popup_clear()` can close it.

![gif](https://user-images.githubusercontent.com/8505073/76216755-72e81580-6211-11ea-8c89-e45e9099fe83.gif)

**Comment by lacygoill** [comment]
Actually, I think this is another Vim bug, because `:pedit` can escape any terminal popup window, and I don't think it's intended to work.  I'll try to open another issue later.

**Comment by brammool** [comment]
> I've just found out that `:pedit` could escape the window (it raises
> `E994` and `E32`, but the window is still left); then `popup_clear()`
> can close it.

I fixed this with 8.2.0367.  Please check if there is anything else.

-- 
hundred-and-one symptoms of being an internet addict:
196. Your computer costs more than your car.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
Here is another example where a popup terminal window can't be closed anymore:

    set hidden
    call term_start('sh', #{hidden: 1, term_finish: 'close'})->popup_create(#{minwidth: 30, minheight: 10, border: []})
    call term_start(['sh', '-c', ':'], #{curwin: 1, exit_cb: {-> bufnr('#')->term_sendkeys("exit\<CR>")}})
    sleep 100m
    bw

Write it in `/tmp/vim.vim`, then start Vim like this:

    vim -Nu NONE -S /tmp/vim.vim

You may need to increase the sleeping time (on my machine, I need to sleep at least 41 ms).

Here is what the code does:

   - it creates a popup terminal
   - it replaces the terminal buffer associated to an interactive `sh(1)` process, with another terminal buffer associated to a non-interactive `sh(1)` process which runs a dummy `:` command
   - it wipes the current buffer

In this case, the issue relies on `term_finish: 'close'` being passed to the first `term_start()`:

    call term_start('sh', #{hidden: 1, term_finish: 'close'})->popup_create(#{minwidth: 30, minheight: 10, border: []})
                                       ^^^^^^^^^^^^^^^^^^^^

And on typing `exit` in the first `!sh` buffer via the `exit_cb` key of the second `term_start()`:

    call term_start(['sh', '-c', ':'], #{curwin: 1, exit_cb: {-> bufnr('#')->term_sendkeys("exit\<CR>")}})
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by lacygoill** [comment]
Here is yet another example:

    set hidden
    call term_start('sh', #{hidden: 1, term_finish: 'close'})->popup_create(#{minwidth: 30, minheight: 10, border: []})
    fu Exit(...) abort
        call term_sendkeys(bufnr('#'), "exit\<CR>")
        sleep 100m
        call popup_clear()
    endfu
    call term_start(['sh', '-c', ':'], #{curwin: 1, exit_cb: function('Exit')})

With this one, I can't even enter the command-line after pressing `C-\ C-n`.  I'm not sure whether Vim hangs but it seems I can't interact with it anymore, so I have to `$ kill -9` it.

**Comment by lacygoill** [comment]
Closing since I can't reproduce any issue anymore.
All the examples raise `E863`, probably because of https://github.com/vim/vim/commit/5aed0ccb965dbad4b60f4c77c9c4455a9379e73c.
