### ISSUE TITLE
Option for scrollbind to work in non-focused windows

### ISSUE THREAD

**Issue by tbodt** [vim/vim#5752]
When I have a diff open, I expect scrolling with the mouse in either window to scroll the other. But this only works when scrolling in the focused window, so I have to remember to click the window before scrolling it.

`:h scroll-binding` says:

> The 'scrollbind' flag is meaningful when using keyboard commands to vertically scroll a window, and also meaningful when using the vertical scrollbar of the window which has the cursor focus.  However, when using the vertical scrollbar of a window which doesn't have the cursor focus, 'scrollbind' is ignored. This allows quick adjustment of the relative offset of 'scrollbind' windows.

So it sounds like this is intended. But this seems like a mis-feature to me. I'd like an option to disable it, and maybe even to disable it by default.

**Comment by brammool** [comment]
This is intentional.  It allows for looking around the changed text (in diff mode) without moving away from the change.  You can hover over one window or the other, without changing the scrollbind option.  Obviously it's one or the other, and the current choice is the best.

**Comment by tbodt** [comment]
I understand that some people like the way it is now, but every other diff-displaying GUI that I've used behaves differently. I'd like an option to make it behave that way.
