### ISSUE TITLE
combination of autocmd and 2 popup terminals creates an unwipable buffer

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#5764]
**Describe the bug**

The combination of a `BufWipeout` autocmd, 2 popup terminals, and a job with a particular exit callback can create a buffer which can't be wiped out anymore.

**To Reproduce**

Write this in `/tmp/vim.vim`:

    set hidden
    call term_start(&shell, #{hidden: 1})->popup_create({})
    let buf1 = term_start(&shell, #{hidden: 1})
    call popup_create(buf1, {})
    exe 'au BufWipeout * ++once bw! '..buf1
    let buf2 = term_start(['sh', '-c', ':'], #{curwin: 1, exit_cb: {-> execute('try|close|catch|endtry')}})
    sleep 100m
    call win_getid()->popup_close()
    exe 'bw! '..buf2

Start Vim with this shell command:

    vim -Nu NONE -i NONE -S /tmp/vim.vim

The output of `:ls!` is:

    1 %a   "[No Name]"                    line 1
    2  hR  "!/usr/local/bin/zsh [running]" line 0
    3  hR  "!/usr/local/bin/zsh (1) [running]" line 1
    4  aF  "!sh [finished]"               line 0

**Expected behavior**

The output of `:ls!` does not contain the buffer 4; IOW, it displays:

    1 %a   "[No Name]"                    line 1
    2  hR  "!/usr/local/bin/zsh [running]" line 0
    3  hR  "!/usr/local/bin/zsh (1) [running]" line 1

Because it was wiped out by this command:

    exe 'bw! '..buf2

**Environment**

 - Vim version: 8.2 Included patches: 1-371
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

This buffer 4 can't be wiped out anymore; that is, `:bw! 4` fails no matter how many times you run it.  `:bw!` also fails when the buffer 4 is the current one.

---

Without the `:try` conditional in the exit callback, Vim correctly wipes out the buffer, and an error is correctly raised when `:close` tries to close the popup terminal.

However, `:close` still succeeds in closing the popup terminal window, while I think it should fail (it should raise `E994`).  `:close` succeeds in closing the popup window with or without the `:try` conditional.

---

The flags displayed in the output of `:ls` seem wrong:

    4  aF  "!sh [finished]"               line 0
       ^^

The buffer is not displayed in any window, so it should be considered hidden, and it should bear the `h` flag, not the `a` flag.

Besides, according to `:h E947`, Vim should have wiped out this buffer automatically, because it's hidden and the associated job has finished:

> When the job has finished and no changes were made to the buffer: closing the
> window will wipe out the buffer.

**Comment by lacygoill** [comment]
Without the `:try` conditional in the exit callback, Vim correctly wipes out the buffer, and an error is correctly raised when `:close` tries to close the popup terminal.

However, `:close` still succeeds to close the popup terminal window, while I think it should fail.  `:close` succeeds in closing the popup window with or without the `:try` conditional.

**Comment by andymass** [comment]
Does a simple :%bw fail if you create any popup window with a new buffer?

**Comment by lacygoill** [comment]
Sorry, I'm not sure to understand, but if you mean just creating a regular popup window, then `%bw` fails and raises `E937`:

    E937: Attempt to delete a buffer that is in use: [NULL]

Tested with this shell command:

    vim -Nu NONE +'call popup_create(["a", "b"], #{minheight: 10, minwidth: 30})' +'%bw'

**Comment by lacygoill** [comment]
Ah I think I understand what you mean now.  It could be that Vim refuses to wipe out the buffer because it thinks the latter is still used in a popup window, which would also explain why it has the `a` flag in the output of `:ls!`.

If that's the case, it's still an error, because:

   - `:bw! 4` should raise `E937`; it does not
   - there is no popup window; I've made sure of that by running `:call popup_clear()`

**Comment by lacygoill** [comment]
Closing since I can't reproduce the issue anymore.
Now the original example raises `E863`, probably because of https://github.com/vim/vim/commit/5aed0ccb965dbad4b60f4c77c9c4455a9379e73c.
