### ISSUE TITLE
netrw does not show directory contents

### ISSUE THREAD

**Issue by reinerh** [vim/vim#5767]
**Describe the bug**

When opening a directory with netrw with `netrw_liststyle=3` and `netrw_list_hide='^\..*'`, the directory listing contains only the current directory, and it is not possible to navigate into it.

**To Reproduce**

1. Start vim with this minimal vimrc file:
```
set nocompatible
let g:netrw_liststyle=3
let g:netrw_list_hide='^\..*'
```
2. Open the current directory with netrw (`:e .`)
3. Now the directory list contains only `../` and `currentdir/`. It's not possible to open `currentdir/`, it loops back to the same directory listing.

**Expected behavior**
The file/directory browser lists all files and directories in the current directory.

**Environment:**
 - Vim version 8.2.0368-1
 - netrw version v169
 - OS: Debian unstable

**Additional context**
The same behavior already exists in version 8.1.2136-1, but not yet in 8.1.0875-5 (from Debian stable).
I reported the bug already to the Debian BTS: https://bugs.debian.org/942549

**Comment by cecamp** [comment]
The backslash in the pattern was essentially being ignored by the filter() command.  I've now "escape()"d it, so please try netrw v170a from my [website](http://www.drchip.org/astronaut/vim/index.html#NETRW).

**Comment by reinerh** [comment]
On Wed, Mar 11, 2020 at 06:34:56PM -0700, cecamp wrote:
> The backslash in the pattern was essentially being ignored by the filter() command.  I've now "escape()"d it, so please try netrw v170a from my [website](http://www.drchip.org/astronaut/vim/index.html#NETRW).

Thanks, I can confirm that the new version fixes it for me.
