### ISSUE TITLE
hidden buffer associated to finished job not wiped out when closing popup terminal

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#5768]
**Describe the bug**

Sometimes, a hidden buffer associated to a finished job is not wiped out when closing a popup terminal.

**To Reproduce**

Write this in `/tmp/vim.vim`

    set hidden
    call term_start('sh', #{hidden: 1})->popup_create(#{minwidth: 30, minheight: 10, border: []})
    call term_start(['sh', '-c', 'cat'], #{curwin: 1, exit_cb: {-> [term_sendkeys(bufnr('#'), "exit\<CR>"), popup_close(win_getid())]}})

Start Vim with:

    vim -Nu NONE -S /tmp/vim.vim

Press `C-d` to end the `cat(1)` process.

The `!sh` buffer associated to the *non*-interactive `sh(1)` process running `cat(1)` is wiped out automatically; but not the `!sh` buffer associated to the interactive `sh(1)` process, even though the latter is finished and the buffer is hidden.

According to `:h E947`, Vim should wipe out `!sh` automatically:

> When the job has finished and no changes were made to the buffer: closing the
> window will wipe out the buffer.

**Expected behavior**

Vim automatically wipes out the hidden `!sh` buffer associated to the finished `sh(1)` process, just like it automatically wipes out the hidden `!sh` buffer associated to the finished `cat(1)` process.

**Environment**

 - Vim version: 8.2 Included patches: 1-371
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

The fact that Vim does not wipe out this buffer seems inconsistent with the following experiment:

    set hidden
    call term_start('sh', #{hidden: 1})->popup_create({})
    call term_sendkeys('', "exit\<cr>")
    sleep 5m
    call popup_close(win_getid())

When Vim sources the previous code, the output of `:ls` does not include any `!sh` buffer.  It has been correctly wiped out.

Btw, not sure whether it's expected, but I need to make Vim `:sleep` for at least 2ms between `term_sendkeys()` and `popup_close()`, otherwise the buffer is not wiped out.

---

I'm working on fixing [a bug in the fzf Vim plugin](https://github.com/junegunn/fzf/issues/1916).
I'm almost done, but there is still one thing I can't fix; a terminal buffer hangs around after fzf has finished while it should be wiped out.  I can fix this by installing an autocmd which wipes out the `!sh` buffer associated to the `sh(1)` process when Vim automatically wipes out the `!sh` buffer associated to the `fzf(1)` process:

    set hidden
    let buf = term_start('sh', #{hidden: 1})
    call popup_create(buf, #{minwidth: 30, minheight: 10, border: []})
    call term_start(['sh', '-c', 'cat'], #{curwin: 1, exit_cb: {-> [term_sendkeys(bufnr('#'), "exit\<CR>"), popup_close(win_getid())]}})
    exe 'au BufWipeout * ++once bw! '..buf
    call term_sendkeys('', "\<c-d>")

It works when fzf is invoked from a regular buffer, i.e. the output of `:ls` does not contains any `!sh` buffer.  But it fails when fzf is invoked from a popup terminal:

    set hidden
    call term_start('sh', #{hidden: 1})->popup_create(#{line: 1, col: 1, minwidth: 30, minheight: 10, border: []})
    let buf = term_start('sh', #{hidden: 1})
    call popup_create(buf, #{minwidth: 30, minheight: 10, border: []})
    call term_start(['sh', '-c', 'cat'], #{curwin: 1, exit_cb: {-> [term_sendkeys(bufnr('#'), "exit\<CR>"), popup_close(win_getid())]}})
    exe 'au BufWipeout * ++once bw! '..buf
    call term_sendkeys('', "\<c-d>")

This time, the output of `:ls` still contains an undesirable hidden and finished `!sh` buffer:

    1  a   "[No Name]"                    line 1
    2 %aR  "!sh [Terminal]"               line 1
    3  hF  "!sh (1) [finished]"           line 0
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

When the `fzf(1)` process is finished, the autocmd fails to wipe out the `!sh` buffer, because the focus is still in a popup terminal, and `:bw` is forbidden there.

To fix this, I need yet another autocmd which delays `:bw` until it's allowed:

    set hidden
    call term_start('sh', #{hidden: 1})->popup_create(#{line: 1, col: 1, minwidth: 30, minheight: 10, border: []})
    let buf = term_start('sh', #{hidden: 1})
    call popup_create(buf, #{minwidth: 30, minheight: 10, border: []})
    call term_start(['sh', '-c', 'cat'], #{curwin: 1, exit_cb: {-> [term_sendkeys(bufnr('#'), "exit\<CR>"), execute('sil! call popup_close(win_getid())')]}})
    exe 'au BufWipeout * ++once bw! '..buf

    augroup fzf_wipe_sh
      execute "autocmd BufEnter * if win_gettype() !=# 'popup' | bwipeout! "..bufnr('#')
        \ .." | silent! execute 'autocmd! fzf_wipe_sh' | silent! augroup! fzf_wipe_sh | endif"
    augroup END

    call term_sendkeys('', "\<c-d>")
    sleep 5m
    call term_sendkeys('', "exit\<cr>")
    sleep 5m
    call popup_close(win_getid())

This works but it makes the code much more complex.

It would be nice if either of these statements was true:

   - Vim automatically wipes out any `!sh` buffer when it's hidden, and the associated `sh(1)` job is finished (just like what `:h E947` explains)
   - Vim allows you to run `:bw` from a popup terminal (to wipe out a terminal buffer with the flags `hF`)

**Comment by bfrg** [comment]
It works fine when you set `term_finish` in `term_start()`:
```vim
set hidden
call term_start('sh', #{hidden: 1, term_finish: 'close'})->popup_create(#{minwidth: 30, minheight: 10, border: []})
call term_start(['sh', '-c', 'cat'], #{
    \ curwin: 1,
    \ exit_cb: {-> [term_sendkeys(bufnr('#'), "exit\<CR>"), popup_close(win_getid())]}
    \ })
```

**Comment by bfrg** [comment]
And if you also set `term_finish` in the second `term_start()` call, you won't need `popup_close()` anymore:
```vim
set hidden
call term_start('sh', #{hidden: 1, term_finish: 'close'})->popup_create(#{minwidth: 30, minheight: 10, border: []})
call term_start(['sh', '-c', 'cat'], #{
    \ curwin: 1,
    \ term_finish: 'close',
    \ exit_cb: {-> term_sendkeys(bufnr('#'), "exit\<CR>")}
    \ })
```

**Comment by lacygoill** [comment]
Thank you very much, `term_finish: 'close'` fixes my issue.  I thought I had played with the option before, but apparently I did not.

**Comment by lacygoill** [comment]
Ok, I remember now; I had tested `term_finish: 'close'` in the first shell, and it didn't work.  I had also tested `term_sendkeys(bufnr('#'), "exit\<CR>")` in the second shell, and it didn't work either.
What I did not test is a combination of the two, which indeed works.

But I re-open the issue because I still think something is wrong.
For example, the previous snippet makes Vim correctly wipe the first `!sh` buffer:

    set hidden
    call term_start('sh', #{hidden: 1, term_finish: 'close'})->popup_create(#{minwidth: 30, minheight: 10, border: []})
    call term_start(['sh', '-c', 'cat'], #{curwin: 1, exit_cb: {-> [term_sendkeys(bufnr('#'), "exit\<CR>"), popup_close(win_getid())]}})

But only if all the commands are sourced.  If the last command is not sourced, but executed from a mapping, then the issue re-appears.

Write this in `/tmp/vim.vim`:

    set hidden
    call term_start('sh', #{hidden: 1, term_finish: 'close'})->popup_create(#{minwidth: 30, minheight: 10, border: []})
    nno <silent> cd :call term_start(['sh', '-c', 'cat'], #{curwin: 1, term_finish: 'close', exit_cb: {-> [term_sendkeys(bufnr('#'), "exit\<lt>CR>"), popup_close(win_getid())]}})<cr>
    call feedkeys("\<c-\>\<c-n>cd\<c-d>", 'it')

Start Vim with `vim -Nu NONE -S /tmp/vim.vim`, and check out the output of `:ls!`; it contains again an undesirable `!sh` buffer with the flags `hF`:

    1 %a   "[No Name]"                    line 1
    2  hF  "!sh [Terminal-finished]"      line 0
       ^^

And yet `term_finish: 'close'` was passed to the 2 `term_start()`.

I think an unchanged buffer with the flags `hF` should not exist, because Vim should wipe it out automatically according to `:h E947`.

Edit:

> Ok, I remember now; I had tested `term_finish: 'close'` in the first shell, and it didn't work.  I had also tested `term_sendkeys(bufnr('#'), "exit\<CR>")` in the second shell, and it didn't work either.
> What I did not test is a combination of the two, which indeed works.

Actually, [I did test the combination of the two](https://github.com/vim/vim/issues/5754#issuecomment-597337175), but it caused a crash when there were 2 popup terminals; [this was fixed recently](https://github.com/vim/vim/commit/cee52204ca030ce7814844e4dab8b4ed897ba3cc).

**Comment by lacygoill** [comment]
> I think an unchanged buffer with the flags `hF` should not exist, because Vim should wipe it out automatically according to `:h E947`.

This is confirmed by the fact that Vim does indeed wipe out the buffer automatically if you use `:b` to make it active in the current window, then get back to the previous buffer with `:b#`.  If you do that and inspect the output of `:ls!`, you should see that – this time – Vim has correctly wiped out the buffer even though you never ran `:bw` explicitly:

    set hidden
    let buf = term_start('sh', #{hidden: 1, term_finish: 'close'})
    call popup_create(buf, #{minwidth: 30, minheight: 10, border: []})
    nno <silent> cd :call term_start(['sh', '-c', 'cat'], #{curwin: 1, term_finish: 'close', exit_cb: {-> [term_sendkeys(bufnr('#'), "exit\<lt>CR>"), popup_close(win_getid())]}})<cr>
    call feedkeys("\<c-\>\<c-n>cd\<c-d>", 'it')
    set ut=100 | au CursorHold * exe 'b '..buf | b#
    "                            ^^^^^^^^^^^^^^^^^^

    :ls!
    1 %a   "[No Name]"                    line 1

**Comment by bfrg** [comment]
> Ok, I remember now; I had tested `term_finish: 'close'` in the first shell, and it didn't work. I had also tested `term_sendkeys(bufnr('#'), "exit\<CR>")` in the second shell, and it didn't work either.
> What I did not test is a combination of the two, which indeed works.
> 
> But I re-open the issue because I still think something is wrong.
> For example, the previous snippet makes Vim correctly wipe the first `!sh` buffer:
> 
> ```
> set hidden
> call term_start('sh', #{hidden: 1, term_finish: 'close'})->popup_create(#{minwidth: 30, minheight: 10, border: []})
> call term_start(['sh', '-c', 'cat'], #{curwin: 1, exit_cb: {-> [term_sendkeys(bufnr('#'), "exit\<CR>"), popup_close(win_getid())]}})
> ```
> 
> But only if all the commands are sourced. If the last command is not sourced, but executed from a mapping, then the issue re-appears.
> 
> Write this in `/tmp/vim.vim`:
> 
> ```
> set hidden
> call term_start('sh', #{hidden: 1, term_finish: 'close'})->popup_create(#{minwidth: 30, minheight: 10, border: []})
> nno <silent> cd :call term_start(['sh', '-c', 'cat'], #{curwin: 1, term_finish: 'close', exit_cb: {-> [term_sendkeys(bufnr('#'), "exit\<lt>CR>"), popup_close(win_getid())]}})<cr>
> call feedkeys("\<c-\>\<c-n>cd\<c-d>", 'it')
> ```
> 
> Start Vim with `vim -Nu NONE -S /tmp/vim.vim`, and check out the output of `:ls!`; it contains again an undesirable `!sh` buffer with the flags `hF`:
> 
> ```
> 1 %a   "[No Name]"                    line 1
> 2  hF  "!sh [Terminal-finished]"      line 0
>    ^^
> ```
> 
> And yet `term_finish: 'close'` was passed to the 2 `term_start()`.
> 
> I think an unchanged buffer with the flags `hF` should not exist, because Vim should wipe it out automatically according to `:h E947`.
> 
> Edit:
> 
> > Ok, I remember now; I had tested `term_finish: 'close'` in the first shell, and it didn't work.  I had also tested `term_sendkeys(bufnr('#'), "exit\<CR>")` in the second shell, and it didn't work either.
> > What I did not test is a combination of the two, which indeed works.
> 
> Actually, [I did test the combination of the two](https://github.com/vim/vim/issues/5754#issuecomment-597337175), but it caused a crash when there were 2 popup terminals; [this was fixed recently](https://github.com/vim/vim/commit/cee52204ca030ce7814844e4dab8b4ed897ba3cc).

Just as a side note: the two examples are different. In the first one you're not setting `'term_finish: 'close'` inside the second `term_start()` call, in the second example you do. But I don't think that's the issue here.

You can reproduce this issue even without using popup windows. I think it has to do with the fact that you first change to terminal-normal mode before executing the mapping. So, `term_sendkeys()` is invoked when the terminal buffer is in normal mode. I don't know if that's a bug in Vim.

Here's a minimal example without using popup windows:
Run `vim --clean test.vim -c "source %"` with
```vim
" test.vim
set hidden
terminal
nnoremap <silent> cd
        \ :call term_start([&shell, &shellcmdflag, 'cat'], #{
        \   curwin: 1,
        \   exit_cb: {-> [term_sendkeys(bufnr('#'), "exit\<lt>CR>"), execute('close')]}
        \ })<cr>
call feedkeys("\<c-\>\<c-n>cd\<c-d>", 'it')
```
There will be a terminal buffer `[Terminal-finished]` that hasn't been wiped out yet, until it's opened in a window with `:buffer 2` and then made hidden again `:buffer #`.

If you change the mapping to `tnoremap` you won't have to switch to terminal-normal mode before executing the mapping. With `tnoremap` the buffer gets wiped out properly:
```vim
" test2.vim
set hidden
terminal
tnoremap <silent> cd
        \ :call term_start([&shell, &shellcmdflag, 'cat'], #{
        \   curwin: 1,
        \   exit_cb: {-> [term_sendkeys(bufnr('#'), "exit\<lt>CR>"), execute('close')]}
        \ })<cr>
call feedkeys("cd\<c-d>", 'it')
```
You will obviously need to use a different mapping than `cd` :smile: .

**Comment by lacygoill** [comment]
> You can reproduce this issue even without using popup windows.

Good point, the issue is not limited to popup terminals.

> If you change the mapping to tnoremap you won't have to switch to terminal-normal mode before executing the mapping. With tnoremap the buffer gets wiped out properly:

It doesn't work on my machine.  When I source the code, the rhs is written inside the terminal which is in Terminal-Job mode, and the shell complains because it doesn't understand the Vim commands:

    $ :call term_start([&shell, &shellcmdflag, 'cat'], #{   curwin: 1,   exit_cb: {-> [term_sendkeys(bufnr('#'), "exit\<CR>
    "), execute('close')]} })
    [1] 8262
    zsh: bad pattern: term_start([
    [2] 8263
    [1]  - 8262 exit 1     :call term_start([
    [2]  + 8263 exit 127   shell,

Here is the output of `:ls!` afterward:

    1 #a   "[No Name]"                    line 1
    2 %aR  "!/usr/local/bin/zsh [Terminal]" line 4

This is interesting though.  I'll try to gather more information later.

**Comment by bfrg** [comment]
Oops, there's a typo, I forgot to add `<c-w>` in the `tnoremap`:
```vim
" test2.vim
set hidden
terminal
tnoremap <silent> cd
        \ <c-w>:call term_start([&shell, &shellcmdflag, 'cat'], #{
        \   curwin: 1,
        \   exit_cb: {-> [term_sendkeys(bufnr('#'), "exit\<lt>CR>"), execute('close')]}
        \ })<cr>
call feedkeys("cd\<c-d>", 'it')
```

**Comment by lacygoill** [comment]
Closing since I can't reproduce the issue anymore.
Now the original example raises `E863`, probably because of https://github.com/vim/vim/commit/5aed0ccb965dbad4b60f4c77c9c4455a9379e73c.
