### ISSUE TITLE
[Documentation] i_CTRL-R_CTRL-R behaviour unclearly defined.

### ISSUE THREAD

**Issue by sunwukonga** [vim/vim#5771]
While doing vimgolf challenge 5192f96ad8df110002000002, I noticed that while i_CTRL-R_CTRL-R does seem to follow the behaviour set out in it's associated :h i_CTRL-R_CTRL-R, it does not behave like i_CTRL-R_CTRL-O or i_CTRL-R_CTRL-P with respect to what is inserted into the `.` register; despite having identical wording.

From `:h i_CTRL-R_CTRL-R`, `:h i_CTRL-R_CTRL-O`, and `i_CTRL-R_CTRL-P`
```
...
The '.' register (last inserted text) is still inserted as typed.
```
^^^ I surmise this to mean that the literal insertion behaviour persists, even for `single-repeat`. I don't think it is referring to the actual form of what is stored in the `.` register.

**To Reproduce**
1. Run `vim --clean`
2. Type: `ione two three<Esc>cw(<C-R><C-R>-)<Esc>`
3. Inspect `".` of `:reg`
4. Repeat 2, 3 for `<C-R><C-O>` and `<C-R><C-P>`

Respectively, `".` contains:
```
(one)
(^R^O-)
(^R^P-)
```

I expected: 
```
(^R^R-)
(^R^O-)
(^R^P-)
```
It seems to me that this difference is not documented. In fact, I don't think that the way `(^R^O)` is inserted into `.` is mentioned at all.

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  1 2020 17:21:03)
Included patches: 1-343                                                                        
Compiled by Arch Linux
5.5.7-arch1-1 (x86x64)
terminator 1.91
tmux 3.0_a-1

**Comment by brammool** [comment]
Fixed by updating the docs, see #5902
