### ISSUE TITLE
Enable IXON in termios by default to enable CTRL+S

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#5775]
_Instructions: Replace the template text and remove irrelevant text (including this line)_

It is impossible to use `CTRL+s` and `CTRL+q` in vim by default, unless we include:

```bash
stty -ixon
```

in `.bashrc`.  But most of new users totally have no idea about this, only thing they perceive is the terminal stuck after `CTRL+S`. today, most cli softwares (emacs/neovim) have enabled this by default.

emacs users are able to use `CTRL+s` directly for `I-search` and `CTRL+q` for other things, they don't even need to know what `stty -ixon` is.

Some of my friends complain that they can map `CTRL+s`  in neovim, but unable to map in vim.  I told them to use `stty -ixon` to solve the problem. They have been using vim/nvim for more than five years, still lack of knowledge about this obscure terminal input flag.

I saw some new users attempted to map `<c-s>` to save file but failed. Enable `IXON` by default may make vim more friendly to new users. 

**Describe the solution you'd like**

I made a patch for this:

```diff
diff --git a/src/os_unix.c b/src/os_unix.c
index c0a4fdbe3..5d8ff04b7 100644
--- a/src/os_unix.c
+++ b/src/os_unix.c
@@ -3452,6 +3452,9 @@ mch_settmode(int tmode)
         * ~ICRNL enables typing ^V^M
         */
        tnew.c_iflag &= ~ICRNL;
+# if defined(IXON)
+       tnew.c_iflag |= IXON;
+# endif
        tnew.c_lflag &= ~(ICANON | ECHO | ISIG | ECHOE
 # if defined(IEXTEN) && !defined(__MINT__)
                    | IEXTEN        // IEXTEN enables typing ^V on SOLARIS
```

**Describe alternatives you've considered**

**Additional context**
Hope it can be included.

**Comment by skywind3000** [comment]
![图片](https://user-images.githubusercontent.com/3035071/76585592-b6949500-6519-11ea-9136-3480be8b6edf.png)

After this patch, vim can recognize `CTRL+S` and `CTRL+Q` without `stty -ixon`.

**Comment by chrisbra** [comment]
Does this only work for as long as vim is running? Or does this change disable flow control even after vim finishes? I am asking, because I do not see it being reset.

**Comment by skywind3000** [comment]
the previous termios info is saved in `told` when vim starts, and will be restore after exit. no side effect to user's terminal after vim exit.

you can check the termios by :

    stty -a | grep ixon

if `stty -ixon` is called, there will be an `-ixon`, if not, there will be an `ixon` (without minus).

the previous state can be precisely restored after exit this patched vim.

**Comment by skywind3000** [comment]
here, the old termios value is stored properly in `told`.

https://github.com/vim/vim/blob/8a677a37d03692db274c8b00cb20dbba9604505e/src/os_unix.c#L3441-L3448

**Comment by brammool** [comment]
> _Instructions: Replace the template text and remove irrelevant text (including this line)_

[who reads instructions...]

> It is impossible to use `CTRL+s` and `CTRL+q` in vim by default,
> unless we must include:
> 
> ```bash
> stty -ixon
> ```
> 
> in `.bashrc`.  But most of new users totally have no idea about this,
> only thing they perceive is the terminal stuck after `CTRL+S`, most
> cli software have enabled this by default.
> 
> like emacs, people are able to use `CTRL+q` in emacs for `I-search`
> and `CTRL+q` for other things, they don't even need to know what `stty
> -ixon` is.
> 
> Some of my friends complain that they can map `CTRL+s`  in neovim, but
> unable to map in vim.  I told them to use `stty -ixon` to solve the
> problem. They are using vim/nvim for more than five years, still have
> no idea about this obscure terminal input flag.
> 
> So I think, enable `IXON` by default may make vim more friendly to new users.

This is an old Unix thing.  Vim does have the 'more' option, thus we
don't really need to CTRL-S behavior.  Still, I haven't heard many
complaints.

Would this change cause trouble for anyone?


-- 
hundred-and-one symptoms of being an internet addict:
245. You use Real Audio to listen to a radio station from a distant
     city rather than turn on your stereo system.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by skywind3000** [comment]
If you need samples, here is one: https://github.com/skywind3000/vim-terminal-help/issues/19

One user created an issue in my plugin `vim-terminal-help`, after some investigation, he found the problem was caused by remapping `<c-w>`, I asked the reason why he want to override such an important key in vim. He explained that he just want to make "save file" a little easier but `<c-s>` didn't work so he choose `<c-w>` for saving current buffer.

I request this change because I heard two people made same mistake in `stty -ixon` this week.

Since nobody reply for opposition, can we consider this patch as "harmless" ??

**Comment by lilydjwg** [comment]
> Still, I haven't heard many complaints.

Either users are told not to use those keys or they `stty -ixon` in their shell startup scripts :-)

**Comment by skywind3000** [comment]
Vim has `set nocompatible` in `defaults.vim` since 8.0 to make vim more friendly to new users.

This patch has the same purpose. Emacs/neovim users can have their CTRL+S/Q available without knowing what `IXON` is, they may consider it as a vim issue because vim can't handle CTRL+S/Q properly.

**Comment by brammool** [comment]
When I run "vim -u NONE" I can already map <C-S> without this patch.
So when exactly does this patch make a difference?

**Comment by lacygoill** [comment]
Fixed by https://github.com/vim/vim/commit/d6cd5ffade84a1054fed23079133af3b837033bf and/or https://github.com/vim/vim/commit/928eec649b8af389de0fdb7aba2034d27df3e058.

**Comment by skywind3000** [comment]
Thanks Bram, this enables not only `CTRL+S` but also `CTRL+Q` in vim.

**Comment by brammool** [comment]
I assume you mean "mapping CTRL-S and CTRL-Q".  Note that enabling modifyOtherKeys also made it work.  I'll close this now, but watch out for any side effects.
