### ISSUE TITLE
"prop_find()" sometimes fails to find a text property

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#5776]
**Describe the bug**

`prop_find()` sometimes fails to find a text property.

**To Reproduce**

Write this in `/tmp/test.vim`:

    call setline(1, ['xxxx', 'x'])
    $
    call prop_type_add('tempmark', {'bufnr': bufnr('%'), 'highlight': 'Search'})
    call prop_add(1, 4, {'type': 'tempmark'})
    echom [prop_find({'type': 'tempmark'}, 'f'), prop_find({'type': 'tempmark'}, 'b')]

Start Vim like this:

    vim -Nu NONE -S /tmp/test.vim

This is printed on the command-line:

    [{}, {}]

**Expected behavior**

This is printed on the command-line:

    [{}, {'lnum': 1, 'id': 0, 'col': 4, 'end': 1, 'type': 'tempmark', 'length': 0, 'start': 1}]

**Environment**

 - Vim version: 8.2 Included patches: 1-373
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

It seems that `prop_find()` fails to find a text property in the backward direction from a line containing less characters than the text between the start of the line where the text property is set and the start of the latter (with an offset of 1).

For example, in the previous example, the buffer contains this text:

    xxxx
    x

The text property is on line 1 column 4, the cursor is on line 2, and its line contains only 1 character.  `prop_find()` fails to find the text property.  This is because the difference between 4 and 1 is greater than 1:

    4 - 1 > 1
    │   │
    │   └ number of characters on the cursor line
    └ colum position of the start of the text property

If you add another character on the cursor line:

    xxxx
    xx
     ^
     new character

`prop_find()` still fails to find the text property.  This is because the difference between 4 and 2 is still greater than 1:

    4 - 2 > 1
    │   │
    │   └ number of characters on the cursor line
    └ colum position of the start of the text property

If you add yet another character on the cursor line:

    xxxx
    xxx
      ^
      new character

This time, `prop_find()` finds the text property.  This is because the difference between 4 and 3 is not greater than 1:

    4 - 3 = 1
    │   │
    │   └ number of characters on the cursor line
    └ colum position of the start of the text property

---

It's a regression introduced by https://github.com/vim/vim/commit/66b98854d86f641db036fd1e6cf20f7b8905344e.

This commit fixed 2 other issues, one of which is still listed in the [todo list](https://github.com/vim/vim/blob/8a677a37d03692db274c8b00cb20dbba9604505e/runtime/doc/todo.txt#L97).

/cc @axelf4 (via 66b9885)

**Comment by axelf4** [comment]
The issue is [on this line](https://github.com/vim/vim/blob/8a677a37d03692db274c8b00cb20dbba9604505e/src/textprop.c#L726). I misunderstood the meaning of `buf->b_ml.ml_line_len`. I think the fix would be to move that line to the top of the `while (1)`-loop like so:

    while (1)
    {
        char_u  *text = ml_get_buf(buf, lnum, FALSE);
        size_t  textlen = STRLEN(text) + 1;
        int     count = (int)((buf->b_ml.ml_line_len - textlen)
                                / sizeof(textprop_T));
        int         i;
        textprop_T  prop;
        int         prop_start;
        int         prop_end;

    +   // Adjust col if we're continuing from prev/next line.
    +   if (lnum_start != lnum) col = dir < 0 ? textlen : 1;

**Comment by lacygoill** [comment]
Thank you very much for the patch and the quick answer; unfortunately, I can still reproduce the issue after applying the patch.

**Comment by axelf4** [comment]
Hmm, I just tried it and your example prints the expected result. Here is the patch in full for reference:

```
diff --git a/src/textprop.c b/src/textprop.c
index 4f5329ebb..9c8b6db57 100644
--- a/src/textprop.c
+++ b/src/textprop.c
@@ -658,6 +658,10 @@ f_prop_find(typval_T *argvars, typval_T *rettv)
 	int	    prop_start;
 	int	    prop_end;
 
+	// Adjust col if we're continuing from prev/next line.
+	if (lnum_start != lnum)
+	    col = dir < 0 ? textlen : 1;
+
 	for (i = 0; i < count; ++i)
 	{
 	    mch_memmove(&prop, text + textlen + i * sizeof(textprop_T),
@@ -722,8 +726,6 @@ f_prop_find(typval_T *argvars, typval_T *rettv)
 		break;
 	    lnum--;
 	}
-	// Adjust col to indicate that we're continuing from prev/next line.
-	col = dir < 0 ? buf->b_ml.ml_line_len : 1;
     }
 }
 
```

**Comment by lacygoill** [comment]
Ah sorry for the wrong feedback; I used a shell alias which ran `$ git stash`, which undid the patch.
You're right; your patch fixes the issue; thank you for the quick fix.

**Comment by brammool** [comment]
Axel Forman wrote:

> The issue is [on this line](https://github.com/vim/vim/blob/8a677a37d03692db274c8b00cb20dbba9604505e/src/textprop.c#L726). I misunderstood the meaning of `buf->b_ml.ml_line_len`. I think the fix would be to move that line to the top of the `while (1)`-loop like so:
> 
>     while (1)
>     {
>         char_u  *text = ml_get_buf(buf, lnum, FALSE);
>         size_t  textlen = STRLEN(text) + 1;
>         int     count = (int)((buf->b_ml.ml_line_len - textlen)
>                                 / sizeof(textprop_T));
>         int         i;
>         textprop_T  prop;
>         int         prop_start;
>         int         prop_end;
> 
>     +   // Adjust col if we're continuing from prev/next line.
>     +   if (lnum_start != lnum) col = dir < 0 ? textlen : 1;

Thanks.  Can you please add a test for verifying this change?

-- 
Hear about the guy who played a blank tape at full blast?
The mime next door went nuts.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by axelf4** [comment]
Here is @lacygoill's reproduction adapted:
```
func Test_find_smaller_len_than_match_col()
  new
  call prop_type_add('test', {'highlight': 'ErrorMsg'})
  call setline(1, ['xxxx', 'x'])
  call prop_add(1, 4, {'type': 'test'})
  call assert_equal({'id': 0, 'lnum': 1, 'col': 4, 'type': 'test', 'length': 0, 'start': 1, 'end': 1},
        \ prop_find({'type': 'test', 'lnum': 2, 'col': 1}, 'b'))
  bwipe!
  call prop_type_delete('test')
endfunc
```

**Comment by axelf4** [comment]
I guess another option would be to only bother with `col` for the starting line, which is maybe nicer? That is, this also fixes the problem:

```
diff --git a/src/textprop.c b/src/textprop.c
index 4f5329ebb..ec67df289 100644
--- a/src/textprop.c
+++ b/src/textprop.c
@@ -663,13 +663,14 @@ f_prop_find(typval_T *argvars, typval_T *rettv)
 	    mch_memmove(&prop, text + textlen + i * sizeof(textprop_T),
 			    sizeof(textprop_T));
 
-	    if (dir < 0)
-	    {
-		if (col < prop.tp_col)
-		    break;
-	    }
-	    else if (prop.tp_col + prop.tp_len - (prop.tp_len != 0) < col)
-		continue;
+	    if (lnum_start == lnum)
+		if (dir < 0)
+		{
+		    if (col < prop.tp_col)
+			break;
+		}
+		else if (prop.tp_col + prop.tp_len - (prop.tp_len != 0) < col)
+		    continue;
 
 	    if (prop.tp_id == id || prop.tp_type == type_id)
 	    {
@@ -722,8 +723,6 @@ f_prop_find(typval_T *argvars, typval_T *rettv)
 		break;
 	    lnum--;
 	}
-	// Adjust col to indicate that we're continuing from prev/next line.
-	col = dir < 0 ? buf->b_ml.ml_line_len : 1;
     }
 }
 
```
