### ISSUE TITLE
Minify And Unminify

### ISSUE THREAD

**Issue by devbapidey** [vim/vim#5784]
Could you provide a Build in feature to Minify and Unminify the code like JavaScript, CSS, etc.
It might be very helpful because it is usually hard to copy paste code here to there.

**Comment by vim-ml** [comment]
On 2020-03-15, Bapi Dey wrote:
> Could you provide a Build in feature to Minify and Unminiy the code like
> JavaScript, CSS, etc.
> It might be very helpful because it is usually hard to copy paste code here to
> there.

Would you please explain what Minify and Unminiy mean?  There may
already be a way in Vim to do what you want.

Regards,
Gary

**Comment by k-takata** [comment]
I don't think Vim needs to have such builtin feature. Plugins would be sufficient.

**Comment by devbapidey** [comment]
@vim-ml Minification is the process of removing all unnecessary characters from the source codes of interpreted programming languages or markup languages without changing their functionality. These unnecessary characters usually include white space characters, new line characters, comments, and sometimes block delimiters, which are used to add readability to the code but are not required for it to execute. Minification reduces the size of the source code, making its transmission over a network more efficient.

For unminify here is a ans from [stackoverflow](https://stackoverflow.com/questions/50153889/how-to-unminify-the-js-files#50153991). Now, maybe you understood what I am looking for.

**Comment by vim-ml** [comment]
On 2020-03-15, Bapi Dey wrote:
> @vim-ml Minification is the process of removing all unnecessary characters from
> the source codes of interpreted programming languages or markup languages
> without changing their functionality. These unnecessary characters usually
> include white space characters, new line characters, comments, and sometimes
> block delimiters, which are used to add readability to the code but are not
> required for it to execute. Minification reduces the size of the source code,
> making its transmission over a network more efficient.
> 
> For unminify here is a ans from stackoverflow. Now, maybe you understood what I
> am looking for.

Thank you.  Now I understand.

Given the speed of today's networks and the overhead of everything
else involved in transferring data over a network, it seems hardly
worth the effort.

In any case, I agree with K.Takata that this is something that could
be done in a plugin and definitely not something to be included
internally in Vim.

Regards,
Gary

**Comment by chrisbra** [comment]
I am closing this, as I don't see why this needs to be in the core. A plugin should work and might possibly already exists.
