### ISSUE TITLE
in-session reloading of syntax file fails to show updated highlighting/color/syntax

### ISSUE THREAD

**Issue by egberts** [vim/vim#5786]
I'm making a change to a syntax coloring file that is provided by `Vim` package.  There are new keywords to be added for later versions of ISC Bind (and DHCP) configuration file (`/usr/share/vim/syntax/named.vim`).  In short, I am trying to add new Vim syntax `match`, `keyword`, `region` into the `named.vim` syntax file.

When attempting to edit a private copy of `$HOME/.vim/syntax/named.vim`, I would like to program a function key (F10 or F12) to reload these updated syntax files under `$HOME/.vim/syntax` so that a quick review of any Syntax changes can be had within the same Vim terminal session (not having to exit then re-execute `vim` again to see these change results of the edited syntax highlighting, which seems to be the ONLY workaround at this point).

Nothing I've tried seems to work in reload syntax file ... within the same Vim terminal session.

**To Reproduce**
***Initial setup***
```shell
mkdir -p $HOME/.vim/syntax
cp -i /usr/share/vim/syntax/named.vim $HOME/.vim/syntax/
```
***Edit/Develop/Debug Cycle***

Detailed steps to reproduce the behavior are done in two terminal or Vim windows:
```shell
" -- first window
vim /etc/bind/named.conf
```
And in the second Vim window/session
```shell
" -- second window
vim $HOME/.vim/syntax/named.conf
```

Edit the change to `named.vim` in 1st window, 
save the edit change in 1st window.  

Note: I flipped the 'namedNumber' in private copy of `syntax/named.vim` and rock it back between `Type` and `Number` between each develop/debug cycle.  This is the debugging part where we hope to see the color changes after reloading the edited syntax file into the 2nd (but same Vim terminal session) window with hope to see the changes in highlighting colors.

Then the problem starts when attempting to reload the edited syntax file in 2nd window:
```vim
:source $MYVIMRC
```
In a Vim default setup, the `source $MYVIMRC``  made the default highlighting worse. 

Only when exiting the Vim terminal process back to shell and then re-starting the Vim will it finally reflect the edited changes in said syntax file.

**Expected behavior**
Reloading Vim Syntax file within the same Vim process should update the re-coloring of syntax object(s).

**Screenshots**
It did not incorporate new color selection(s) upon saving the changed syntax file.

UPDATE: Screenshots are no longer applicable to this issue (as it was fixed by removing `set ft=sh` statement in `~/.vimrc`.) and is left here for historical purpose.
[Images](https://gist.github.com/egberts/f7dcfd6b829490d6fb239048c620b911)

Currently, the 2nd screenshot remains unchanged despite re-editing the `~/.vim/syntax/named.vim` file and reloading via vim command `:source $MYVIMRC`.

**Environment (please complete the following information):**
```console
vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 15 2019 16:41:15)
Included patches: 1-875, 878, 884, 948, 1046, 1365-1368, 1382, 1401
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     +tag_old_static
+arabic            +farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    +tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
+balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
+browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +textprop
+byte_offset       -hangul_input      +num64             +timers
+channel           +iconv             +packages          +title
+cindent           +insert_expand     +path_extra        +toolbar
+clientserver      +job               +perl              +user_commands
+clipboard         +jumplist          +persistent_undo   +vartabs
+cmdline_compl     +keymap            +postscript        +vertsplit
+cmdline_hist      +lambda            +printer           +virtualedit
+cmdline_info      +langmap           +profile           +visual
+comments          +libcall           -python            +visualextra
+conceal           +linebreak         +python3           +viminfo
+cryptv            +lispindent        +quickfix          +vreplace
+cscope            +listcmds          +reltime           +wildignore
+cursorbind        +localmap          +rightleft         +wildmenu
+cursorshape       +lua               +ruby              +windows
+dialog_con_gui    +menu              +scrollbind        +writebackup
+diff              +mksession         +signs             +X11
+digraphs          +modify_fname      +smartindent       -xfontset
+dnd               +mouse             +startuptime       +xim
-ebcdic            +mouseshape        +statusline        +xpm
+emacs_tags        +mouse_dec         -sun_workshop      +xsmp_interact
+eval              +mouse_gpm         +syntax            +xterm_clipboard
+ex_extra          -mouse_jsbterm     +tag_binary        -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/libdrm -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-4Pursk/vim-8.1.0875=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.28/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.7/config-3.7m-x86_64-linux-gnu -lpython3.7m -lcrypt -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm -lruby-2.5 -lpthread -lgmp -ldl -lcrypt -lm  
```
 - OS:
```shell
# Debian 10.3
uname -a
Linux arca 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
```
 - Terminal: 
```shell
# xfce4-terminal 0.8.7.4 Xfce Terminal Emulator
set | grep TERM
COLORTERM=truecolor
TERM=xterm-256color
```
**Additional context**
Also I use HiLinkTrace Vimball regularly.

**Comment by k-takata** [comment]
What color scheme do you use?
Could you show a minimal .vimrc to reproduce this?

**Comment by egberts** [comment]
Well, I'll be darn.  @k-takata, during my effort to provide  you with a minimum `.vimrc` file, I've found the mis-colorization issue, but there is still an issue of getting the updated syntax file to be reflected on the screen after reload (it doesn't change any color now).

By inserting the following `finish` statement throughout my local `~/.vimrc` until the problem goes away, I've managed to narrow it down to this offending line:

```vim
set ft=sh
```

Once that offending vim command was removed from vimrc, only the discoloration of syntax highlighting problem got solved: the color remain unchanged now after executing `:source $MYVIMRC`.  But we are attempting to change the color within the same Vim terminal session ... still.

Still have this inability to reload and not being able to see re-colorization resulted by this changed `~/.vim/syntax/named.vim` file.

In detail, if I change the word `Type` to `Error` in `~/.vim/syntax/named.vim` from a separate non-Vim shell console, I would expect the color to change to "RED" after reloading `$MYVIMRC` in my Vim terminal session, no?

**Comment by egberts** [comment]
`strace -f vim named.conf 2>/tmp/vim-named.strace` shows that the `~/.vim/syntax/named.vim` never got reloaded after executing `:source $MYVIMRC`.  

Is this expected behavior?

**Comment by egberts** [comment]
Related bug reports:
* https://vi.stackexchange.com/questions/11578/reloading-syntax-file-without-restarting-vim

**Comment by egberts** [comment]
Found out that the following line in `vim/syntax/named.vim`:

```vim
if version >= 508 || !exists('did_named_syn_inits')
  if version < 508
    let did_named_syn_inits = 1
    command -nargs=+ HiLink hi link <args>
  else
    command -nargs=+ HiLink hi def link <args>
  endif
```
Caused the problem.  More specifically, the `command -nargs=+ HLink hi def link <args>` part (as my vim is version 810).

By removing the `def`, so that it looks like:
```vim
if version >= 508 || !exists('did_named_syn_inits')
  if version < 508
    let did_named_syn_inits = 1
  endif
  command -nargs=+ HiLink hi link <args>
```
now correctly updates the re-colorization effort by using `source $MYVIMRC`.

```vim
noremap <F12> <Esc>:source $MYVIMRC<CR>
inoremap <F12> <C-o>:source $MYVIMRC<CR>
```

And can now use F12 function key to reload the entire VIM RC files correctly, and immediately see the result of any change of highlighting made to the syntax file.

Problem solved.

**Comment by egberts** [comment]
Quick examination of latest official Vim syntax `named.vim` file shows that this has already been fixed.

https://github.com/vim/vim/blob/master/runtime/syntax/named.vim
