### ISSUE TITLE
Unwanted behaviour while yanking in Rust

### ISSUE THREAD

**Issue by ccarral** [vim/vim#5792]
**Bug description**
Yanking/pasting in a rust source file will produce unwanted comment characters and unpredictable indent patterns when pasting with CTRL-R " (default register).
**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim -u minimal` where minimal is a .vimrc file with only the next line: `filetype plugin on`
2. Yank from inside a braced function with yi}
3. Type `CTRL-R "` to read from default register.

**Expected behavior**
`CTRL-R "`  behaving just as `p`

**Screenshots**

**Environment:**
 - Vim version: 8.2
 - OS: Fedora 30
 - Terminal: Konsole
![Captura de pantalla de 2020-03-16 13-04-19](https://user-images.githubusercontent.com/49008964/76791511-b51bd480-6786-11ea-9e47-f124b842d1af.png)

**Comment by k-takata** [comment]
This is an expected behavior. 'autoindent' and some other options will be applied. See `:help i_CTRL-R`.
If you don't want to apply them, use `CTRL-R CTRL-O "`. See `:help i_CTRL-R_CTRL-O`.
