### ISSUE TITLE
Compilation error, missing stropts.h header

### ISSUE THREAD

**Issue by coot** [vim/vim#5794]
Compiling vim from source (current master branch) errors with:
```
In file included from os_unix.c:27:
os_unixx.h:53:11: fatal error: stropts.h: No such file or directory
   53 | # include <stropts.h>
      |           ^~~~~~~~~~~
compilation terminated.
```
`stropts.h` is no longer distributed by `glibc`, [ref](https://sourceware.org/legacy-ml/libc-alpha/2019-08/msg00029.html).

My distro currently is coming with:
```
libc6 - 2.30-2
gcc - 4:9.2.1-3.1
```

**Comment by brammool** [comment]
Have you done "make reconfig"?

**Comment by coot** [comment]
No, thanks for the tip :)
