### ISSUE TITLE
Test_terminal_in_popup fails

### ISSUE THREAD

**Issue by jamessan** [vim/vim#5795]
In the past few Debian uploads, `Test_terminal_in_popup` has been routinely failing across architectures.  There seem to be two flavors to the failure:

```
Tunction RunTheTest[40]..Test_terminal_in_popup[39]..VerifyScreenDump line 55: See dump file difference: call term_dumpdiff("testdir/failed/Test_terminal_popup_1.dump", "testdir/dumps/Test_terminal_popup_1.dump"); difference in line 15: "|t|e|r|m|i|n|a|l| |p|o|p|u|p| @42|1|,|1| @10|A|l@1| "
```

```
function RunTheTest[40]..Test_terminal_in_popup[39]..VerifyScreenDump line 55: See dump file difference: call term_dumpdiff("testdir/failed/Test_terminal_popup_1.dump", "testdir/dumps/Test_terminal_popup_1.dump"); difference in line 15: "|t|e|r|m|i|n|a|l| |p|o|p|u|p| @42|1|,|0|-|1| @8|T|o|p| "
```

**Comment by chrisbra** [comment]
Yes the ruler option seems to be the culprit. It looks like patch 8.2.0382 (353c351bd22e4dac4c) tried to fix it by setting `:noruler`, however I believe the final vim that shows the popup, does not see this, because it is started inside a new terminal and loads defaults.vim

Does that patch fix it:

```patch
diff --git a/src/testdir/test_terminal.vim b/src/testdir/test_terminal.vim
index e99ab7f5a..2f420870c 100644
--- a/src/testdir/test_terminal.vim
+++ b/src/testdir/test_terminal.vim
@@ -2366,7 +2366,7 @@ func Test_terminal_in_popup()
   call term_wait(buf, 200)
   call term_sendkeys(buf, ":call OpenTerm(0)\<CR>")
   call term_wait(buf, 200)
-  call term_sendkeys(buf, ":\<CR>")
+  call term_sendkeys(buf, ":set noruler\<CR>:\<CR>")
   call term_wait(buf, 200)
   call term_sendkeys(buf, "\<C-W>:echo getwinvar(g:winid, \"&buftype\") win_gettype(g:winid)\<CR>")
   call VerifyScreenDump(buf, 'Test_terminal_popup_1', {})
```

**Comment by brammool** [comment]
> In the past few Debian uploads, `Test_terminal_in_popup` has been
> routinely failing across architectures.  There seem to be two flavors
> to the failure:

Have you done this after patch 8.2.0382?  I managed to reproduce the
problems when valgrind is enabled and fixed them.  The ruler no longer
shows in the Vim running in the terminal.  It's still enabled in the
Vim running in the popup window, but that doesn't appear to cause this
problem.

-- 
press CTRL-ALT-DEL for more information

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by jamessan** [comment]
Yes, 8.2.0382 has fixed the problem.  Thanks!
