### ISSUE TITLE
New JSON v: vars produce internal errors

### ISSUE THREAD

**Issue by ZyX-I** [vim/vim#580]
`v:var == 1` is internal error. `v:true == v:true` and `v:true is v:true` is _two_ internal errors, though returns `1`. I think that first should error out like `[] == 1` does and second should silently produce 1.

Vim version 7.4.1161.

**Comment by ZyX-I** [comment]
I would though welcome if only `v:true is v:true` worked (and `v:true == v:true` produced an error) because this will allow Neovim not to add any new types while still keeping almost full compatibility with Vim with last my suggestion. But this would be inconsistent.

**Comment by ZyX-I** [comment]
Fixed by recent patches.

**Comment by brammool** [comment]
Nikolai Pavlov wrote:

> I would though welcome if only `v:true is v:true` worked (and `v:true
> == v:true` produced an error) because this will allow Neovim not to
> add any new types while still keeping almost full compatibility with
> Vim with last my suggestion. But this would be inconsistent.

"v:true == v:true" producing an error is not right.

I just added some test for the "is" operator, and that appears to work
correctly already.

## 

hundred-and-one symptoms of being an internet addict:
34. You laugh at people with a 10 Mbit connection.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///
