### ISSUE TITLE
Test_swap_prompt_splitwin failure in v8.2.0397

### ISSUE THREAD

**Issue by jamessan** [vim/vim#5800]
The two flavors of the failure I've seen are:

```
	Found errors in Test_swap_prompt_splitwin():
	function RunTheTest[40]..Test_swap_prompt_splitwin[15]..WaitForAssert[2]..<SNR>6_WaitForCommon[11]..<lambda>3 line 1: Pattern '^:$' does not match '[O]K, (L)oad File: '
	function RunTheTest[40]..Test_swap_prompt_splitwin[18]..WaitForAssert[2]..<SNR>6_WaitForCommon[11]..<lambda>4 line 1: Pattern '^1$' does not match '"" [New file] --No lines in buffer--'
```

and

```
	Found errors in Test_swap_prompt_splitwin():
	function RunTheTest[40]..Test_swap_prompt_splitwin[15]..WaitForAssert[2]..<SNR>6_WaitForCommon[11]..<lambda>3 line 1: Pattern '^:$' does not match '[O]K, (L)oad File: '
	function RunTheTest[40]..Test_swap_prompt_splitwin[18]..WaitForAssert[2]..<SNR>6_WaitForCommon[11]..<lambda>4 line 1: Pattern '^1$' does not match '[O]K, (L)oad File: '
	function RunTheTest[40]..Test_swap_prompt_splitwin[19]..StopVimInTerminal[7]..WaitForAssert[2]..<SNR>6_WaitForCommon[11]..<lambda>5 line 1: Expected 'finished' but got 'running'
```

**Comment by brammool** [comment]
James McCoy wrote:

> The two flavors of the failure I've seen are:
> 
> ```
> 	Found errors in Test_swap_prompt_splitwin():
> 	function RunTheTest[40]..Test_swap_prompt_splitwin[15]..WaitForAssert[2]..<SNR>6_WaitForCommon[11]..<lambda>3 line 1: Pattern '^:$' does not match '[O]K, (L)oad File: '
> 	function RunTheTest[40]..Test_swap_prompt_splitwin[18]..WaitForAssert[2]..<SNR>6_WaitForCommon[11]..<lambda>4 line 1: Pattern '^1$' does not match '"" [New file] --No lines in buffer--'
> ```
> 
> and
> 
> ```
> 	Found errors in Test_swap_prompt_splitwin():
> 	function RunTheTest[40]..Test_swap_prompt_splitwin[15]..WaitForAssert[2]..<SNR>6_WaitForCommon[11]..<lambda>3 line 1: Pattern '^:$' does not match '[O]K, (L)oad File: '
> 	function RunTheTest[40]..Test_swap_prompt_splitwin[18]..WaitForAssert[2]..<SNR>6_WaitForCommon[11]..<lambda>4 line 1: Pattern '^1$' does not match '[O]K, (L)oad File: '
> 	function RunTheTest[40]..Test_swap_prompt_splitwin[19]..StopVimInTerminal[7]..WaitForAssert[2]..<SNR>6_WaitForCommon[11]..<lambda>5 line 1: Expected 'finished' but got 'running'
> ```

I cannot reproduce and can't guess why this would result in the "OK /
Load File" prompt.  That would only happen if the file changed outside
of Vim, but it's a buffer without a name.

Just guessing: Maybe it helps to edit a non-existing file?  Add an
argument to RunVimInTerminal():

let buf = RunVimInTerminal('XNoFile', {'rows': 20})

Otherwise it might help to add some sleep commands, but can't guess
where.

-- 
   They now pass three KNIGHTS impaled to a tree.  With their feet off the
   ground,  with one lance through the lot of them, they are skewered up
   like a barbecue.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by jamessan** [comment]
> I cannot reproduce and can't guess why this would result in the "OK / Load File" prompt. That would only happen if the file changed outside of Vim, but it's a buffer without a name.
>
> Just guessing: Maybe it helps to edit a non-existing file? Add an argument to RunVimInTerminal():
>
> let buf = RunVimInTerminal('XNoFile', {'rows': 20})

Unfortunately, I haven't been able to reproduce this on the porter systems, but it reliably happens on the buildds themselves.  I'll see about doing some test uploads to try some of these suggestions.

**Comment by jamessan** [comment]
> let buf = RunVimInTerminal('XNoFile', {'rows': 20})

After adding this, I'm not getting failures that look like:

 	function RunTheTest[40]..Test_swap_prompt_splitwin[15]..WaitForAssert[2]..<SNR>6_WaitForCommon[11]..<lambda>23 line 1: Pattern '^:$' does not match '"XNofile" [New file] --No lines in buffer--'
	function RunTheTest[40]..Test_swap_prompt_splitwin[18]..WaitForAssert[2]..<SNR>6_WaitForCommon[11]..<lambda>24 line 1: Pattern '^1$' does not match '-- INSERT --'

I tried adding a longer sleep to the `term_wait()` call just before the `^:$` assert, but that didn't help.

**Comment by brammool** [comment]
"not getting failures" or "now getting failures" ??

**Comment by brammool** [comment]
I'll make another attempt in making the test more robust.  Please reopen if it didn't fix the problem.

**Comment by brammool** [comment]
That is with patch 8.2.0444
