### ISSUE TITLE
Terminal Popup overflows

### ISSUE THREAD

**Issue by blayz3r** [vim/vim#5802]
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Describe the bug**
(Issues related to the runtime files should be reported to their maintainer, check the file header.)

**To Reproduce**
```vim
fu! Flt_term_win(cmd, width, height, border_highlight) abort
    let width = float2nr(&columns * a:width)
    let height = float2nr(&lines * a:height)
    let row = float2nr((&lines - height) / 2)
    let col = float2nr((&columns - width) / 2)
    let top = '┌' . repeat('─', width - 2) . '┐'
    let mid = '│' . repeat(' ', width - 2) . '│'
    let bot = '└' . repeat('─', width - 2) . '┘'
    let border = [top] + repeat([mid], height - 2) + [bot]
    let frame = s:create_popup_window(a:cmd, a:border_highlight, {
        \ 'line': row,
        \ 'col': col,
        \ 'width': width,
        \ 'height': height,
        \ 'is_frame': 1,
        \ })
    call setbufline(frame, 1, border)
    call s:create_popup_window(a:cmd, 'Normal', {
        \ 'line': row + 1,
        \ 'col': col + 2,
        \ 'width': width - 4,
        \ 'height': height - 2,
        \ })
endfu

fu! s:create_popup_window(cmd,hl, opts) abort
    if has_key(a:opts, 'is_frame')
        let id = popup_create('', #{
            \ line: a:opts.line,
            \ col: a:opts.col,
            \ minwidth: a:opts.width,
            \ minheight: a:opts.height,
            \ zindex: 50,
            \ })
        call setwinvar(id, '&wincolor', a:hl)
        exe 'au BufWipeout * ++once call popup_close('..id..')'
        return winbufnr(id)
    else
        let buf = term_start(a:cmd, {'hidden': 1, 'exit_cb' : 'OnTermExit'})
        call popup_create(buf, #{
            \ line: a:opts.line,
            \ col: a:opts.col,
            \ minwidth: a:opts.width,
            \ minheight: a:opts.height,
            \ zindex: 51,
            \ })
    endif
endfu

function! OnTermExit(job, message)
    close
    " TODO: add some code to confirm that current window is a popup.
    " TODO: prevent close other window by accident.
endfunction 

:call Flt_term_win('bash',0.9,0.6,'Todo')<CR>
```
**Expected behavior**
_A clear and concise description of what you expected to happen._
**Output is redrawn when it reaches the edge(It is only redrawn when you go into normal mode and back)**
**Screenshots**
If applicable, copy/paste the text or add screenshots to help explain your problem.
![term2](https://user-images.githubusercontent.com/12205650/76880833-a39dff80-684e-11ea-93da-56bd5881cb10.png)
![term](https://user-images.githubusercontent.com/12205650/76880832-a39dff80-684e-11ea-95a3-a498b0ae62f9.png)
**Environment (please complete the following information):**
 - Vim version [e.g. 8.1.1234] (Or paste the result of `vim --version`.)
 - OS: [e.g. Ubuntu 18.04, Windows 10 1809, macOS 10.14]
 - Terminal: [e.g. GNOME Terminal, mintty, iTerm2, tmux, GNU screen] (Use GUI if you use the GUI.)

Windows 10
Vim 8.2

**Comment by bfrg** [comment]
You need to set the `maxheight` entry to the same value as `minheight`.

Why are you generating the borders manually in the first place? Vim does it for you automatically, see the `border`, `borderhighlight` and `borderchars` entries under `:h popup-usage`. There is no need to open two popup windows as above.

**Comment by bfrg** [comment]
I think the following does exactly what you want:
```vim
function! Pop_term_win(cmd, width, height, border_highlight) abort
    let width = float2nr(&columns * a:width)
    let height = float2nr(&lines * a:height)
    let bufnr = term_start(a:cmd, {'hidden': 1, 'term_finish': 'close'})

    let winid = popup_create(bufnr, {
            \ 'minwidth': width,
            \ 'maxwidth': width,
            \ 'minheight': height,
            \ 'maxheight': height,
            \ 'border': [],
            \ 'borderchars': ['─', '│', '─', '│', '┌', '┐', '┘', '└'],
            \ 'borderhighlight': [a:border_highlight],
            \ 'padding': [0,1,0,1],
            \ 'highlight': a:border_highlight
            \ })

    " Optionally set the 'Normal' color for the terminal buffer
    " call setwinvar(winid, '&wincolor', 'Special')

    return winid
endfunction

call Pop_term_win('bash', 0.9, 0.6, 'Todo')
```

**Comment by blayz3r** [comment]
Thanks

**Comment by lacygoill** [comment]
> Why are you generating the borders manually in the first place? Vim does it for you automatically, see the border, borderhighlight and borderchars entries under :h popup-usage. There is no need to open two popup windows as above.

I could be wrong, but I think it's based on [some code I wrote in the past](https://github.com/junegunn/fzf.vim/issues/821#issuecomment-581273191).

In the context of fzf, I think there was no need for `maxheight`.
As for the borders, I didn't want to add a second mechanism; I based the code on an existing implementation for Nvim, which doesn't support borders around floating windows.

I did try to submit a [PR to make fzf use Vim's native borders](https://github.com/junegunn/fzf/pull/1912) but it was not merged, because the maintainer was [reluctant to handle 2 different mechanisms](https://github.com/junegunn/fzf/issues/1916#issuecomment-596491603) for no visible gain to the user.

---

FWIW, I wrote [a small recipe](https://github.com/lacygoill/vim-cookbook/blob/master/autoload/cookbook/popup/terminal.vim) to create a popup terminal in Vim, and [a gist](https://gist.github.com/lacygoill/0bfef0a2e70ac7015aaee56a670c124b) to make it togglable.

**Comment by blayz3r** [comment]
> 
> 
> > Why are you generating the borders manually in the first place? Vim does it for you automatically, see the border, borderhighlight and borderchars entries under :h popup-usage. There is no need to open two popup windows as above.
> 
> I could be wrong, but I think it's based on [some code I wrote in the past](https://github.com/junegunn/fzf.vim/issues/821#issuecomment-581273191).
> 
> In the context of fzf, I think there was no need for `maxheight`.
> As for the borders, I didn't want to add a second mechanism; I based the code on an existing implementation for Nvim, which doesn't support borders around floating windows.
> 
> I did try to submit a [PR to make fzf use Vim's native borders](https://github.com/junegunn/fzf/pull/1912) but it was not merged, because the maintainer was [reluctant to handle 2 different mechanisms](https://github.com/junegunn/fzf/issues/1916#issuecomment-596491603) for no visible gain to the user.
> 
> FWIW, I wrote [a small recipe](https://github.com/lacygoill/vim-cookbook/blob/master/autoload/cookbook/popup/terminal.vim) to create a popup terminal in Vim, and [a gist](https://gist.github.com/lacygoill/0bfef0a2e70ac7015aaee56a670c124b) to make it togglable.

Totally my fault, I know that's not what the code was initially meant to be used for
