### ISSUE TITLE
src/dosinst.c: useless VIMARGS for os Windows_NT

### ISSUE THREAD

**Issue by hginzel** [vim/vim#5819]
The file [src/dosinst.c](https://github.com/vim/vim/blob/1fa8d2c33d7290eda7dc2a94d4ec6a599a2d61dd/src/dosinst.c#L870)  generates *.bat files containing
```
:havevim
rem collect the arguments in VIMARGS for Win95
set VIMARGS=
…
:loopend

if .%OS%==.Windows_NT goto ntaction

"%VIM_EXE_DIR%\vim.exe"  %VIMARGS%
goto eof

:ntaction
rem for WinNT we can use %*
"%VIM_EXE_DIR%\vim.exe"  %*
goto eof
```
Variable VIMARGS is not used for os Windows_NT.
I suggest to put the `if .%OS%==.Windows_NT goto ntaction` just after `:havevim`.

**To Reproduce**
Install gVim on Windows with “Create bat files.” checked.
See created bat files in C:\Windows.

**Environment (please complete the following information):**
 - Vim version 8.2
 - OS: Windows 10

**Comment by brammool** [comment]
> The file src/dosinst.c generatest *.bat files containing
> ```
> :havevim
> rem collect the arguments in VIMARGS for Win95
> set VIMARGS=
> :loopstart
> if .%1==. goto loopend
> set VIMARGS=%VIMARGS% %1
> shift
> goto loopstart
> :loopend
> 
> if .%OS%==.Windows_NT goto ntaction
> 
> "%VIM_EXE_DIR%\vim.exe"  %VIMARGS%
> goto eof
> 
> :ntaction
> rem for WinNT we can use %*
> "%VIM_EXE_DIR%\vim.exe"  %*
> goto eof
> ```
> Variable VIMARGS is not used for os Windows_NT.
> I suggest to put the `if .%OS%==.Windows_NT goto ntaction` just after `:havevim`.
> 
> **To Reproduce**
> Install gVim on Windows with “Create bat files.” checked.
> See created bat files in C:\Windows.

We do not actually support Windows 95 anymore (even XP is end of life
now).  So perhaps we can reduce this to:

  :havevim
  rem for WinNT we can use %*
  "%VIM_EXE_DIR%\vim.exe"  %*
  goto eof

-- 
Not too long ago, unzipping in public was illegal...

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
Fixed in https://github.com/vim/vim/commit/0df541963d406edd69d3ebe8de3912eb87b05414.
