### ISSUE TITLE
string() does not work correctly for new v:vars

### ISSUE THREAD

**Issue by ZyX-I** [vim/vim#582]
`echo string(v:true)` echoes `true`, same for other values. It should show `v:true` to make `eval(string(v:true))` work.

Vim version 7.4.1161.

**Comment by brammool** [comment]
Nikolai Pavlov wrote:

> `echo string(v:true)` echoes `true`, same for other values. It should
> show `v:true` to make `eval(string(v:true))` work.

OK, we can do that.

## 

hundred-and-one symptoms of being an internet addict:
35. Your husband tells you he's had the beard for 2 months.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
seems to be fixed.
