### ISSUE TITLE
jsonencode() documentation contains a typo

### ISSUE THREAD

**Issue by ZyX-I** [vim/vim#583]
The very first word in description is `Encodode`.

**Comment by brammool** [comment]
Nikolai Aleksandrovich Pavlov wrote:

> The very first word in description is `Encodode`.

I'll fix it.

## 

If you put 7 of the most talented OSS developers in a room for a week
and asked them to fix a bug in a spreadsheet program, in 1 week
you'd have 2 new mail readers and a text-based web browser.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by odeke-em** [comment]
Fixed by PR https://github.com/zuloloxi/vim/pull/9 and in particular commit https://github.com/vim/vim/commit/705ada1aff27ecd9c47c690df817d043c2ceb5e2#diff-bea881dfa9626bab7141337b0fcdb23eL4240
