### ISSUE TITLE
Editing single-quoted strings crashes python3complete

### ISSUE THREAD

**Issue by NeilGirdhar** [vim/vim#5838]
To reproduce:

1. gvim (must be gvim—not vim) a.py.
2. Type `i` to enter insert mode, then
```
'a'
``` 
then escape to exit insert mode.
3. Type `h` to go left so that the cursor is over the `a`.
4. Type `i` to enter insert mode, then `a_`.

My vimrc:
```
filetype off
set runtimepath+=~/.vim/bundle/Vundle.vim/
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'lifepillar/vim-mucomplete'
call vundle#end()
filetype plugin indent on
let g:mucomplete#enable_auto_at_startup = 1
```

**Comment by NeilGirdhar** [comment]
Only happens in graphical editor for some reason.

**Comment by k-takata** [comment]
It looks that your reproducing steps are incomplete, because you refer python3complete in the title but it is not appeared in the steps.

**Comment by NeilGirdhar** [comment]
@k-takata 
Sorry, the error I get is:

```
Error detected while processing function python3complete#Complete:
line   35:
  File "<string>", line 1                                        
```

**Comment by k-takata** [comment]
Ah, okay. When I type `<C-x><C-o>` instead of `a_` in the step 4, the same error occurred (both on gvim and vim).

**Comment by NeilGirdhar** [comment]
Yup, that's my problem!  Thanks for taking a look.

**Comment by brammool** [comment]
I only get a "pattern not found" error

**Comment by NeilGirdhar** [comment]
@brammool Thanks very much for trying it out.  I was mistaken about the minimal vimrc.  This is what I have it down to

```
filetype off
set runtimepath+=~/.vim/bundle/Vundle.vim/
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'lifepillar/vim-mucomplete'
call vundle#end()
filetype plugin indent on
let g:mucomplete#enable_auto_at_startup = 1
```
It's weird because the error happens in python3complete, but is partly caused by mucomplete.  They say it's a problem with vim (https://github.com/lifepillar/vim-mucomplete/issues/176), but I can understand how it might be a problem with them.  Not sure.  Either way, I'm avoiding single-quoted strings due to this bug!

**Comment by NeilGirdhar** [comment]
Is there anything I can do to help with this?  This still plagues me.

**Comment by chrisbra** [comment]
please contact the maintainer, mentioned at the top of the python3complete.vim script. I think it might be @aaronmgriffin not sure. I have no idea about this completion script, but does in any case this fix it?

```patch
diff --git a/runtime/autoload/python3complete.vim b/runtime/autoload/python3complete.vim
index f0f3aaddb..6f7e63bce 100644
--- a/runtime/autoload/python3complete.vim
+++ b/runtime/autoload/python3complete.vim
@@ -83,7 +83,7 @@ function! python3complete#Complete(findstart, base)
                 break
             endif
         endwhile
-        execute "py3 vimpy3complete('" . cword . "', '" . a:base . "')"
+        execute "py3 vimpy3complete('" . escape(cword, "'") . "', '" . escape(a:base, "'") . "')"
         return g:python3complete_completions
     endif
 endfunction
```

**Comment by k-takata** [comment]
Maybe a similar change is also needed for autoload/pythoncomplete.vim:
```diff
--- a/runtime/autoload/pythoncomplete.vim
+++ b/runtime/autoload/pythoncomplete.vim
@@ -81,7 +81,7 @@ function! pythoncomplete#Complete(findst
                 break
             endif
         endwhile
-        execute "python vimcomplete('" . cword . "', '" . a:base . "')"
+        execute "python vimcomplete('" . escape(cword, "'") . "', '" . escape(a:base, "'") . "')"
         return g:pythoncomplete_completions
     endif
 endfunction
```

**Comment by NeilGirdhar** [comment]
@chrisbra oh, sorry!  I just naively assumed that since it's distributed with vim, it's part of vim.

Your change is a perfect fix!  How do we get this checked in?

**Comment by chrisbra** [comment]
if possible, I'd like to see an ack from the maintainer. Otherwise, if no reaction from the maintainer (which means we have to wait a bit), I suppose Bram might just commit it with one of the runtime file updates). So if possible, please try to reach out to the maintainer.

**Comment by NeilGirdhar** [comment]
Sounds good, looks like you already pinged @aaronmgriffin?  I'll check back if there's no reply.  Thanks.

**Comment by chrisbra** [comment]
Yes, I am just not sure if @aaronmgriffin is the same user as the one given in the completion script.

**Comment by NeilGirdhar** [comment]
They do have the same email address.

**Comment by aaronmgriffin** [comment]
I haven't maintained this script in a long time. I do not recall who took
it over and don't know how to get this checked back into the core codebase.
Sorry

**Comment by k-takata** [comment]
@brammool Could you consider including the above two patches?
"Maintainer" should be changed to "Previous Maintainer".

**Comment by brammool** [comment]
OK, I'll include the suggested changes and update the header.

**Comment by NeilGirdhar** [comment]
Thank you!!
