### ISSUE TITLE
Using <C-]> in a man page does not respect the section number (with FIX)

### ISSUE THREAD

**Issue by adah1972** [vim/vim#5844]
**Problem**

Vim manpager does not respect the section number, when using <C-]> in a man page.

**Steps to Reproduce**

1. Run `vim --clean`
2. Run `:source $VIMRUNTIME/ftplugin/man.vim`
3. Run `:Man fopen`
4. Go to the `open(2)` near the end, and type <C-]> on `open`

**Expected behaviour**

I expect to see the open(2) page, but open(1) page is shown instead.

**Cause**

runtime/ftplugin/man.vim has this line:

```vim
call s:GetPage(sect, page)
```

But s:GetPage is currently defined as:

```vim
func <SID>GetPage(cmdmods, ...)
…
```

I.e. the first argument is not `sect`, but `cmdmods`.

**Fix**

This patch should solve the problem:

```diff
diff --git a/runtime/ftplugin/man.vim b/runtime/ftplugin/man.vim
index cbace44c1..d95d1d376 100644
--- a/runtime/ftplugin/man.vim
+++ b/runtime/ftplugin/man.vim
@@ -96,7 +96,7 @@ func <SID>PreGetPage(cnt)
     let sect = a:cnt
     let page = expand("<cword>")
   endif
-  call s:GetPage(sect, page)
+  call s:GetPage('', sect, page)
 endfunc
 
 func <SID>GetCmdArg(sect, page)
```

**Comment by brammool** [comment]
Ah, that has been bugging me for a while.  Thanks for the fix!

**Comment by Shane-XB-Qian** [comment]
btw: is it possible to move line#59~60:
```
  nmap <Leader>K :call <SID>PreGetPage(0)<CR>
  nmap <Plug>ManPreGetPage :call <SID>PreGetPage(0)<CR>
```
into
```
  if !exists("no_plugin_maps") && !exists("no_man_maps")
```
?
such global mapping looks a little aggressive ..
