### ISSUE TITLE
Test_popup_and_previewwindow_dump() fails because of difference in ruler display

### ISSUE THREAD

**Issue by jamessan** [vim/vim#5849]
Using v8.2.0448, this test is failing on some systems because the row displayed by ruler in the main Vim instance differs from the screen dump.

```
function RunTheTest[40]..Test_popup_and_previewwindow_dump[16]..VerifyScreenDump line 58: See dump file difference: call term_dumpdiff("testdir/failed/Test_popup_and_previewwindow_01.dump", "testdir/dumps/Test_popup_and_previewwindow_01.dump"); difference in line 19: "|[+3#0000000&|N|o| |N|a|m|e|]| |[|+|]| @43|1@1|,|1| @10|B|o|t"
```

For screen dump tests, maybe it's useful to always disable irrelevant UI to minimize the chance of false positive failures.

**Comment by brammool** [comment]
> Using v8.2.0448, this test is failing on some systems because the row displayed by ruler in the main Vim instance differs from the screen dump.
> 
> ```
> function RunTheTest[40]..Test_popup_and_previewwindow_dump[16]..VerifyScreenDump line 58: See dump file difference: call term_dumpdiff("testdir/failed/Test_popup_and_previewwindow_01.dump", "testdir/dumps/Test_popup_and_previewwindow_01.dump"); difference in line 19: "|[+3#0000000&|N|o| |N|a|m|e|]| |[|+|]| @43|1@1|,|1| @10|B|o|t"
> ```
> 
> For screen dump tests, maybe it's useful to always disable irrelevant UI to minimize the chance of false positive failures.

I would not call this irrelevant.  Apparently the line number is "11"
inatead of "10".  How can that happen?  The buffer should only have 10
lines. Something must have gone wrong.

-- 
ARTHUR:  Shut up!  Will you shut up!
DENNIS:  Ah, now we see the violence inherent in the system.
ARTHUR:  Shut up!
DENNIS:  Oh!  Come and see the violence inherent in the system!
         HELP! HELP!  I'm being repressed!
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by jamessan** [comment]
> How can that happen? The buffer should only have 10 lines.

Until the test adds a new one -- `call term_sendkeys(buf, "o\<C-X>\<C-N>")`.  So, I guess the question should rather be why the saved screen dump says there should only be 10?

**Comment by brammool** [comment]
Good point.  Looks like there needs to be a pause between the "o" and CTRL-X for the ruler to update.  So on a system that splits the keys in a way there is no typeahead after the "o" this happens, and on most systems the CTRL-X is already there and updating the ruler is skipped.
