### ISSUE TITLE
jsonencode() silently converts invalid unicode to valid unicode

### ISSUE THREAD

**Issue by ZyX-I** [vim/vim#585]
Consider the following script:

```
vim -u NONE --cmd 'set encoding=utf-8' --cmd 'let s="\xAB"' --cmd 'call writefile([jsonencode(s)], "/tmp/jetest.json", "b")' --cmd qa
cat /tmp/jetest.json | xxd
```

This will result in file with contents

```
00000000: 22c2 ab22                                ".."
```

without any notice. It would better be an error because there is no reason to think that byte 0xAB in a unicode string means U+00AB and not something else.

**Comment by brammool** [comment]
Fixed by patch 8.2.4695
