### ISSUE TITLE
looks vim less counted 1 line unless full-screen ?

### ISSUE THREAD

**Issue by Shane-XB-Qian** [vim/vim#5853]
**Describe the bug**
vim less counted 1 line of its window?

**To Reproduce**
e.g my term/vim here:
1, if full screen (f11), the lines is 95
2, or (not full screen - but max), the line is 93

**Expected behavior**
the lines# should be 94.

**Screenshots**
n/a

**Environment (please complete the following information):**
v8.2.430

**Additional context**
i can do the math and set the lines by myself, but just want to know if it was a bug or somehow i missed sth ?

**Comment by chrisbra** [comment]
a screenshot would help. Also a Vim with `:set nu` enabled. And finally, please show the output of echo $LINES $COLUMNS

**Comment by Shane-XB-Qian** [comment]
um, yes, it expected the `$LINES`. and i found the xfce-term 'stole' 1 line to 'frame' when max .. that's why ..
thanks your answer and confirm.
