### ISSUE TITLE
Option to not yank empty or whitespace lines

### ISSUE THREAD

**Issue by StavromulaBeta** [vim/vim#5859]
**Description of problem**
I often use dd to yank lines of text and then remove empty lines (with dd), overwriting the text that I yanked in the clipboard. This usually means that I have to undo until the line that I yanked is there again, and yank it once more, taking up time.

**Describe the solution**
An option in vimrc (disabled by default) to not yank empty lines or lines consisting of only whitespace.

**Alternatives I've considered**
I can remove empty lines with J without yanking them. This does not work on lines consisting of whitespace as the whitespace is appended to the next line.

**Comment by weirdsmiley** [comment]
You can achieve this by using any of the following methods:
1. V-line mode: dd the required line, then go to the line where replace should be done, do `Vp` over there.
2. Black hole register: writing to this register produces no affect and often used for specifically deleting text without yanking. You can read about this in the docs `:help "_`

**Comment by brammool** [comment]
You should be able to map "dd" to a function that checks whether the line is empty and uses dd directly if not, "_dd if it is empty.
It is not very useful to put an empty line on the clipboard, but it happens with other applications as well.
