### ISSUE TITLE
jsonencode() silently converts recursive containers into empty

### ISSUE THREAD

**Issue by ZyX-I** [vim/vim#586]
Consider the following script:

```
vim -u NONE --cmd 'let l=[]' --cmd 'call add(l, l)' --cmd 'echo jsonencode(l)'
```

This will echo `[[]]`, but actually it should error out because recursive container cannot be represented in JSON.

**Comment by brammool** [comment]
Nikolai Aleksandrovich Pavlov wrote:

> Consider the following script:
> 
> vim -u NONE --cmd 'let l=[]' --cmd 'call add(l, l)' --cmd 'echo jsonencode(l)'
> 
> This will echo [[]], but actually it should error out because
> recursive container cannot be represented in JSON.

Yeah, another case of either falling back to something or producing an
error.  I assume nobody wants to intentionally convert a recursive
structure into JSON. OK, let's make that an error.

## 

hundred-and-one symptoms of being an internet addict:
31. You code your homework in HTML and give your instructor the URL.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
seems to be fixed.
