### ISSUE TITLE
getcompletion for command type doesn't seem to complete multiple words

### ISSUE THREAD

**Issue by dbarnett** [vim/vim#5863]
I expected that `getcompletion({pat}, 'command')` would be able to complete the 2nd word of a command, but it doesn't seem to return any results. For instance:
```vim
echo getcompletion('set s', 'command')
```
returns `[]` instead of results I would expect like `['set scroll', 'set scrollbind', 'set scrolljump', 'set scrolloff', …]`.

Is this a bug, or am I using it wrong?

**Comment by vim-ml** [comment]
Hi,

On Sat, Mar 28, 2020 at 5:35 PM David Barnett <vim-dev-github@256bit.org>
wrote:

> I expected that getcompletion({pat}, 'command') would be able to complete
> the 2nd word of a command, but it doesn't seem to return any results. For
> instance:
>
> echo getcompletion('set s', 'command')
>
> returns [] instead of results I would expect like ['set scroll', 'set
> scrollbind', 'set scrolljump', 'set scrolloff', …].
>
> Is this a bug, or am I using it wrong?
>
>
>
You need to use getcompletion('s', 'option') to return the list of options
starting
with 's'. The 'command' option for getcompletion() is used to get the list
of
ex commands start with the specified prefix.

- Yegappan

**Comment by lacygoill** [comment]
> Is this a bug, or am I using it wrong?

That's not a bug; `command` is for names of Ex commands.  In `set s`, `s` is the start of an option; not the start an Ex command.

   > I would expect like ['set scroll', 'set scrollbind', 'set scrolljump', 'set scrolloff', …].

Try this:

    :vim9 echo getcompletion('set s', 'cmdline')->map((_, v) => 'set s' .. v[1 :])

General case:
```vim
vim9script
var cmdline: string = 'set s'
var start: number = cmdline->matchstr('\S\+$')->strcharlen()
echo getcompletion(cmdline, 'cmdline')->map((_, v) => cmdline .. v[start :])
```
Replace `set s` with whatever command line you want.  For example, with `profile f`:
```vim
vim9script
var cmdline: string = 'profile f'
var start: number = cmdline->matchstr('\S\+$')->strcharlen()
echo getcompletion(cmdline, 'cmdline')->map((_, v) => cmdline .. v[start :])
```
    ['profile file', 'profile func']

---

In the help, I suggest removing the reference to arguments of Ex commands:
```diff
diff --git a/runtime/doc/eval.txt b/runtime/doc/eval.txt
index 418aee9ce..fc3d40eef 100644
--- a/runtime/doc/eval.txt
+++ b/runtime/doc/eval.txt
@@ -5642,7 +5642,7 @@ getcompletion({pat}, {type} [, {filtered}])		*getcompletion()*
                buffer		buffer names
                behave		:behave suboptions
                color		color schemes
-		command		Ex command (and arguments)
+		command		Ex commands
                cmdline		|cmdline-completion| result
                compiler	compilers
                cscope		|:cscope| suboptions
```

**Comment by brammool** [comment]
I'll update the help, thanks for the hint.
