### ISSUE TITLE
the hi of cursorlinenum looks lost when diff mode in some case?

### ISSUE THREAD

**Issue by Shane-XB-Qian** [vim/vim#5866]
**Describe the bug**
the hi of cursorlinenum looks lost when diff mode in some case?  (pls check screen cut at following).

**To Reproduce**
1, vim diff mode
2, cursorlineoption=number

**Expected behavior**
hi as usual.

**Screenshots**
![image](https://user-images.githubusercontent.com/13550529/77849595-88909f80-71ff-11ea-932e-3ee38bfdee1b.png)
![image](https://user-images.githubusercontent.com/13550529/77849607-9fcf8d00-71ff-11ea-9583-930cee33b936.png)
![image](https://user-images.githubusercontent.com/13550529/77849624-b1189980-71ff-11ea-92a5-623f27182330.png)

**Environment (please complete the following information):**
v8.2.472

**Additional context**
n/a

**Comment by Shane-XB-Qian** [comment]
not sure if you can see the attached screen-cut, the short of description is the hi of cursorlinenr right after diffdelete is not highlighting... before and after that line is normal (highlighted).
or i missunderstood sth ?

**Comment by Shane-XB-Qian** [comment]
i tried `--clean`, looks that's a bug when cursorlineopt is `number`, no issue if `both`. fyi.

**Comment by dpelle** [comment]
I don't know how to reproduce it.
Please provide the complete reproducible steps:
* 2 concrete small files to diff
* and exact command line option you use (with `--clean`)

**Comment by Shane-XB-Qian** [comment]
xx:
```txt
aaa
bbb
ddd
eee
```
yy:
```txt
aaa
ccc


ddd
```
vimdiff --clean xx yy
set cursorliine
set cursorlineopt=number
hi cursorline ctermbg=red
set nu

**Comment by Shane-XB-Qian** [comment]
hi cursorlinenr ctermbg=red

**Comment by Shane-XB-Qian** [comment]
![image](https://user-images.githubusercontent.com/13550529/77850974-b29a8f80-7208-11ea-9faa-e5fa093c62c5.png)
sorry, probably this was not a bug, or depends on user thought ... that line (`#3` in this creen-cut) was not hightlight at that linenr (`#3`), maybe highlight at `#3` better? or current is good enough?

**Comment by Shane-XB-Qian** [comment]
![image](https://user-images.githubusercontent.com/13550529/77851220-6cdec680-720a-11ea-98b2-954220ee9577.png)

but when cursorlineopt=both, `#3` is highlighted, not sure if you can see the diff.. i think this way of highlight when cursorlineopt=both (but for linenr only - the cursorline is still non-hightlighted - since it is `number` only) is better.

**Comment by Shane-XB-Qian** [comment]
or actually i did not know which one was better, 
but just the linenr hightlight should be uniformed ..
- for `number` and `both` (regardless `line` - if just talk about linenr).

**Comment by Shane-XB-Qian** [comment]
closing, this is more like a preference & discuss & record. thx.
