### ISSUE TITLE
Filetypes with multiple consecutive dots source all syntax files

### ISSUE THREAD

**Issue by benknoble** [vim/vim#5919]
**Describe the bug**

Context: I was experimenting with the `.`-separated filetype mechanism for a plugin.

I typed `:set ft=text..` to see what would happen if the filetype isn't well-formed.

I was hit with error messages, the `syntax/hitest.vim` output, and more... after some digging, I have determined that what the command that caused this is equivalent to

    :runtime! syntax/*.vim

This happens because of these lines in `syntax/synload.vim`:

```
    for name in split(s, '\.')
      exe "runtime! syntax/" . name . ".vim syntax/" . name . "/*.vim"
    endfor
```

The problem is that `split('a..', '\.')` is `['a', '']`.

**To Reproduce**
1. Run `vim --clean` (or `gvim --clean`, etc.)
3. Type `:set filetype=a..`

**Expected behavior**

I would expect this not to be an issue. A simple fix is to add an `if !empty(name)` guard (I would be happy to send this patch if wanted).

**Environment (please complete the following information):**
 - Vim version: 8.2.400
 - OS: macOS 10.14.5
 - Terminal: Alacritty + tmux

**Comment by brammool** [comment]
Checking for an empty name is easy enough, I'll add that check.
Otherwise it's just a user error, thus error messages are to be expected.
