### ISSUE TITLE
doc: Obsolete documentation of debbugers in develop.txt

### ISSUE THREAD

**Issue by omrisarig13** [vim/vim#5923]
In the help file `develop.txt`, there is a line that references some optional tools that can be used to run gdb together with vim (Agide and clewn).

It seems that this line is now unneeded since vim has the feature of `terminal-debug` built into it. I think that this line should be removed from the documentation.

A patch that removes this line is attached to this issue (saved with `txt` extension to upload it to github).

[remove_obsolete_debbugger_doc.txt](https://github.com/vim/vim/files/4469168/remove_obsolete_debbugger_doc.txt)

**Comment by brammool** [comment]
Yes, that remark is outdated.  I'll add a link to terminal-debugger.
