### ISSUE TITLE
jsondecode() parses incorrect JSON

### ISSUE THREAD

**Issue by ZyX-I** [vim/vim#593]
With Vim 7.4.1165 try `jsondecode('[,]')`. This will produce `[v:none]`, but this string is not a correct JSON. `jsondecode('[1,]')` produces `[1]`, but JSON spec does not allow trailing commas. `jsondecode('{1: 1,}')` produces `{'1': 1}`, but JSON spec does not allow non-string keys or trailing comma.

**Comment by ZyX-I** [comment]
Also `jsondecode('1.')` produces `1.0`, but  JSON spec does not allow omitting number after decimal point.

**Comment by brammool** [comment]
Nikolai Pavlov wrote:

> With Vim 7.4.1165 try `jsondecode('[,]')`. This will produce
> `[v:none]`, but this string is not a correct JSON.
> `jsondecode('[1,]')` produces `[1]`, but JSON spec does not allow
> trailing commas. `jsondecode('{1: 1,}')` produces `{'1': 1}`, but JSON
> spec does not allow non-string keys or trailing comma.

jsondecode() allows for a bit more than the standard.  I'll update the
documentation.  This takes it a bit in the direction of what JavaScript
eval() does.

## 

Have you heard about the new Beowulf cluster? It's so fast, it executes
an infinite loop in 6 seconds.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///
