### ISSUE TITLE
":map" doesn't redraw the command-line

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#5962]
**Describe the bug**

`:map` doesn't redraw the command-line before displaying its output, which can make the latter confusing.

**To Reproduce**

Start Vim with this shell command:

    vim -Nu NONE +'map <c-b> <c-a>'

Run this Ex command:

    :map <c-b>xxxxxxxxxxxxx

It outputs:

    <C-B>         <C-A>x

This makes it seem that `<c-b>` is mapped to `<c-a>x`, while in fact it's mapped to `<c-a>`.

**Expected behavior**

Before displaying its output, `:map` clears the command-line, so that the old contents is not wrongly read as being part of the rhs of a mapping.

**Environment**

 - Vim version: 8.2 Included patches: 1-607
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Comment by chrisbra** [comment]
I think this is a duplicate of #5623

**Comment by lacygoill** [comment]
Ah yes, you're right. Sorry for the noise.
