### ISSUE TITLE
tabcloseleft option

### ISSUE THREAD

**Issue by gipi** [vim/vim#5967]
I found that some time ago someone proposed a patch about the option ``tabcloseleft`` in the [mailing list](https://www.mail-archive.com/vim_dev@googlegroups.com/msg18386.html) and indeed into todo.txt there is the line 

    Patch for :tabcloseleft, after closing a tab go to left tab. (William Bowers, 2012 Aug 4)

and I don't understand if it was dropped or if it needs more work on it in order to be merged or something else.

I think that is an option valuable to add, let me know if I can help, thank for your time.

**Comment by chrisbra** [comment]
We do have tablocal variables and autocommands. Is such a feature really needed built into the core? I think this can be achieved by some Vimscript

**Comment by gipi** [comment]
The choice to build such feature in the core is yours to do, but since I saw that someone proposed a patch that is listed in the todo I thought that internally the discussion was already settled for a yes but the patch was lost somewhere.

I know that is something feasible with scripting but to me seems an option valuable to be configurable (99% of the time I open a tab via the NerdTree and I would like to close it and come back to the file listing to open another one, not to the tab on the right).

**Comment by dpacbach** [comment]
This following vimscript solved this problem for me (adapted from [here](https://stackoverflow.com/a/14085713)):
```vim
function! OnQuit()
    if winnr("$") == 1 && tabpagenr("$") > 1 && tabpagenr() > 1 && tabpagenr() < tabpagenr("$")
        q | tabprev
    else
        q
    endif
endfunction

cnoremap q<CR> :call OnQuit()<CR>
```

It would kind of be nice to have an option to do this, since I think vim currently has the "wrong" default behavior.  That said, since it can be done with scripts such as the one above, I can understand the hesitancy.

**Comment by chrisbra** [comment]
closing

**Comment by gdupras** [comment]
Then what about these lines in todo.txt?

https://github.com/vim/vim/blob/73257149d759a8e6ddbe555d2b5aa37b6cb8db8b/runtime/doc/todo.txt#L1839-L1840

**Comment by brammool** [comment]
Whether you set the option or include the mentioned piece of Vim script, both require adding the change to your vimrc.
Adding yet another option for this isn't really needed, just nice.

The command only handles ":q" though, not other commands that close a tab page.  Something using a WinClose autocommand should work better.

**Comment by dpacbach** [comment]
Edit to one of my above comments: the vimscript snippet that I pasted actually does not work correctly (for multiple reasons), one of which is that it does not work when running the `:wq` command.  I think we need to get the `WinClosed` approach working, but would appreciate someone helping me with the issue above regarding the validity of the numbers returned by the various tabpage functions.

**Comment by Melandel** [comment]
For anyone pondering on the issue, right now here's how I'm doing it.

```vim
function! ShouldMoveToPreviousTab()
	" In some scenarios one field has the correct information, in other scearios the other has it
	let previousLastTabNr=max([g:TabLeave_TabsStatus.last, g:WinClosed_TabsStatus.last])
	return tabpagenr('$') < previousLastTabNr && g:TabLeave_TabsStatus.current != previousLastTabNr
endfunction

let g:WinClosed_TabsStatus = { 'current': 1, 'last': 1 } 
let g:TabLeave_TabsStatus =  { 'current': 1, 'last': 1 }
augroup tabcloseleft
	au!
	au TabLeave  * let g:TabLeave_TabsStatus  = { 'current': tabpagenr(), 'last': tabpagenr('$') }
	au WinClosed * let g:WinClosed_TabsStatus = { 'current': tabpagenr(), 'last': tabpagenr('$') }
	au TabClosed * if ShouldMoveToPreviousTab() | tabprevious | endif
augroup end
```
