### ISSUE TITLE
Make new wordcount function yield a human readable number?

### ISSUE THREAD

**Issue by RichardDooling** [vim/vim#597]
I write books in Vim. I like the new wordcount function, especially to use with vim-airline so that the wordcount is in the statuts bar, but instead of 76981, is it possible to add the comma for easy reading.
76,981. I have a Python function that does this but I don't know how to script in Vim.

Thanks for considering.

Rick Dooling

**Comment by chrisbra** [comment]
I think, this is an airline issue, so closing (see mentioned PR from vim-airline)
