### ISSUE TITLE
menu_chinese_gb.936.vim E474 startup error

### ISSUE THREAD

**Issue by yzlnew** [vim/vim#5970]
**Describe the bug**
Show error message when starting.

```
处理 C:xxx\lang\menu_chinese_gb.936.vim 时发生错误:
第  125 行:
E474: 无效的参数
```

**To Reproduce**
Run `gvim --clean`

**Expected behavior**

**Environment (please complete the following information):**

 - Vim version: 8.2.0618
 - OS: Windows10 1909

**Additional context**
Using Chinese language.

**Comment by chrisbra** [comment]
I suppose this is the same as https://github.com/vim/vim-win32-installer/issues/180

It looks like the maintainer knows of this and is currently working on fixing it.

**Comment by yzlnew** [comment]
Yes. Closing for now.
