### ISSUE TITLE
Haiku: :messages partially working

### ISSUE THREAD

**Issue by bitigchi** [vim/vim#5978]
Normally, `:messages` command should display translator/maintainer info if there are no other messages present. However in Haiku version, it does not display anything, but works if there are other messages printed.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean` (or `gvim --clean`, etc.)
2. Type: `:messages`

**Environment (please complete the following information):**
- Vim version 8.2.0628
- Latest Haiku nightly
- xterm-256color

haikuports/haikuports#4898

**Comment by dpelle** [comment]
Looking at code of `ex_messages()`, I see that it only outputs
`Messages maintainer: …` if the environment variable `LANG` is set.

By default, on my Linux box, `LANG` is set to `en_US.UTF-8`.
But if I do `unset LANG` in the shell, then I reproduce the "issue"
which you describe. So I suppose that the environment variable 
`LANG` is not set by default on Haiku.  Try e.g.:
```
$ export LANG=C
```
You can run `locale -a` to see all supported locale (assuming that
works on Haiku).  What is also the output of the following 2 commands
on your Haiku machine?
```
$ locale
$ locale -a
```

Not sure if we can consider that a bug. Maybe if `LANG` is not set,
it should behave as it it was `LANG=C`?

**Comment by bitigchi** [comment]
@dpelle, you are right. By default, `locale` is totally empty on Haiku, but after `export LANG=C` it works as expected.

**Comment by brammool** [comment]
The intention of this message is to give translators a chance to give a contact address for missing or wrong translations.  if $LANG isn't set then there are no translations, to this message is not useful.

**Comment by bitigchi** [comment]
Haiku probably uses a different approach on using translations. I can use Vim with Turkish translations just fine on Haiku.

**Comment by pulkomandy** [comment]
In Haiku, the LC_MESSAGES environment variable is set, at least for applications running in Terminal. According to https://www.gnu.org/software/gettext/manual/html_node/Locale-Environment-Variables.html this takes priority over LANG, and there is no need for LANG in that case. I would say vim should check LANGUAGE, LC_ALL and LC_MESSAGES before checking LANG?

**Comment by bitigchi** [comment]
Thank you @brammool!
