### ISSUE TITLE
Haiku: It's not possible to 'exit' terminal

### ISSUE THREAD

**Issue by bitigchi** [vim/vim#5982]
There is no way to exit `:term` on Haiku. `exit` does not work. See screenshot.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean
2. Type `:term`
3. Type `exit`

**Expected behavior**
Terminal should close.

**Screenshots**
![haiku_exit_term](https://user-images.githubusercontent.com/2769571/80252554-23a25b00-8680-11ea-8b3f-8bed7b5464ba.png)

**Environment (please complete the following information):**
- Vim version 8.2.0628
- Latest Haiku nightly
- xterm-256color

haikuports/haikuports#4894

**Comment by brammool** [comment]
Well, either the shell doesn't actually exit and close its I/O, or there is something not implemented properly related to job and channels.

**Comment by bitigchi** [comment]
@brammool, is there a `.configure` flag to disable terminal? I'd like to keep it disabled on Haiku recipe until this is fixed but keep 'huge' features.

**Comment by brammool** [comment]
Emir Sarı wrote:

> @brammool, is there a `.configure` flag to disable terminal? I'd like
> to keep it disabled on Haiku recipe until this is fixed but keep
> 'huge' features.

Check src/Makefile for configure arguments.

# TERMINAL - Terminal emulator support, :terminal command.  Requires the
# channel feature. The default is enable for when using "huge" features.
# Uncomment the first line when you want terminal emulator support for
# not-huge builds.  Uncomment the second line when you don't want terminal
# emulator support in the huge build.
#CONF_OPT_TERMINAL = --enable-terminal
#CONF_OPT_TERMINAL = --disable-terminal


-- 
Me?  A skeptic?  I trust you have proof.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bitigchi** [comment]
> Emir Sarı wrote:
> @brammool, is there a `.configure` flag to disable terminal? I'd like to keep it disabled on Haiku recipe until this is fixed but keep 'huge' features.
> Check src/Makefile for configure arguments. # TERMINAL - Terminal emulator support, :terminal command. Requires the # channel feature. The default is enable for when using "huge" features. # Uncomment the first line when you want terminal emulator support for # not-huge builds. Uncomment the second line when you don't want terminal # emulator support in the huge build. #CONF_OPT_TERMINAL = --enable-terminal #CONF_OPT_TERMINAL = --disable-terminal
> […](#)

I tried `--disable-terminal` before as natural instinct, but for some reason it didn't work with Haiku recipe. And I tried just now, no avail again. I'll try again, maybe it's a recipe syntax thing...

Edit: That damned backslash...
