### ISSUE TITLE
Mac OS X build is broken by patch 7.4.1182 when option Tcl interpreter is included

### ISSUE THREAD

**Issue by limintang** [vim/vim#599]
There is a function declaration conflict introduced by patch 7.4.1182:

New function:
src/proto/channel.pro:
void channel_close(int idx);

Existing function:
src/if_tcl.c:
static int channel_close(instance, interp)

The conflict causes channel_type initialization failure at if_tcl.c line 1653.

**Comment by pmcRTR** [comment]
This also affects the build on Ubuntu Linux 15.10

**Comment by brammool** [comment]
Should be fixed now.
