### ISSUE TITLE
If SIGTSTP is ignored do not install a handler for it

### ISSUE THREAD

**Issue by krader1961** [vim/vim#5990]
**Describe the bug**
If vim is started from a shell that does not support job-control it should be launched with `SIGTTIN`, `SIGTTOU`, and `SIGTSTP` marked to be ignored. The problem is that vim doesn't honor that setting for `SIGTSTP` and installs a handler despite the parent process indicating, by virtue of ignoring the signal, that it isn't prepared for vim to be suspended by [ctrl-z].

I noticed this because I've recently started using [Elvish](https://elv.sh/) which does not support tty job-control. See issue https://github.com/elves/elvish/issues/988.

**Environment (please complete the following information):**
 - Vim 8.2.600
 - OS: macOS 10.15, FreeBSD, and several flavors of Linux.

**Comment by krader1961** [comment]
Vim not only ignores whether SIGTSTP is ignored it also ignores the termios suspend key value. It instead uses a hardcoded definition of ctrl-z that always calls the vim suspend function.

I can appreciate why this is the case. I've been using UNIX since ~1985; including a decade as a UNIX support engineer for Sequent Computer Systems. I can't recall anyone, ever, redefining this character. And implementing support for it in the current fashion is considerably simpler than basing it on the termios structure at the time vim is started. So don't bother making this aspect 100% correct. It is sufficient to honor whether SIGTSTP is ignored when vim is started; thus indicating the process that launched it does not support job control.

**Comment by brammool** [comment]
> Vim not only ignores whether SIGTSTP is ignored it also ignores the
> termios suspend key value. It instead uses a hardcoded definition of
> ctrl-z that always calls the vim suspend function.
> 
> I can appreciate why this is the case. I've been using UNIX since
> ~1985; including a decade as a UNIX support engineer for Sequent
> Computer Systems. I can't recall anyone, ever, redefining this
> character. And implementing support for it in the current fashion is
> considerably simpler than basing it on the termios structure at the
> time vim is started. So don't bother making this aspect 100% correct.
> It is sufficient to honor whether SIGTSTP is ignored when vim is
> started; thus indicating the process that launched it does not support
> job control.

How would Vim be able to detect that?

-- 
How To Keep A Healthy Level Of Insanity:
8. Don't use any punctuation marks.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by krader1961** [comment]
> How would Vim be able to detect that?

In *./src/os_unix.c* change the `sigaction()` call to use a pointer to a `struct sigaction` rather than `NULL` for the `oact` argument. Then test whether the `sa_handler` member of `oact` is `SIG_IGN`. If true call `sigaction()` again passing the `oact` from the previous call to reinstate ignoring the signal. Set a global bool according to whether `SIGTSTP` is ignored and test that in `nv_suspend()` to decide if the suspend should actually occur.

**Comment by dpelle** [comment]
@krader1961 wrote:

> In ./src/os_unix.c change the sigaction() call to use a pointer to a struct sigaction

Consider providing a patch if you're confident about how to fix it and since you can
apparently test it too in your environment. It will help.  Thanks!

**Comment by krader1961** [comment]
> Consider providing a patch if you're confident about how to fix it...

Happy to do so. I first wanted to make sure a) this wasn't a known issue (I searched but the fact I didn't find this already reported doesn't mean it isn't a duplicate) and b) there were no major objections to making Vim behave better when run from a non-job control shell.

**Comment by brammool** [comment]
I wonder if this actually works.  What if systems do support SIGTSTP but it's ignored once Vim starts up?  There is explicit code to enable it, thus apparently that was needed.

**Comment by krader1961** [comment]
> What if systems do support SIGTSTP but it's ignored once Vim starts up?

The UNIX process model means that no other process can modify the signal handling of an already running process.

> There is explicit code to enable it, thus apparently that was needed.

Looking at the current code I suspect that was not done deliberately. It looks like the person who wrote it simply didn't realize the process might start with some signals in the ignored state. Which isn't surprising since that scenario is rare. One legitimate situation where it is needed is if the process that spawns vim does not implement the UNIX tty job control model. Which is also rare since legacy shells (bash, ksh, zsh, etc.) had little choice but to implement support for it. But newer shells tend to eschew implementing tty job control support because these days it's needed only in esoteric situations. Such as when running the shell on a "serial console" .

**Comment by krader1961** [comment]
FYI, I've given up on trying to honor the ignored status of all signals at the time vim starts running. The structure of the code in *src/os_unix.c* makes that impractical. And, in practice, Vim won't be, or shouldn't be, started with arbitrary signals set to be ignored. It's only SIGTSTP that is special with respect to this issue.

Instead I'm going to detect in `mch_init()` whether SIGTSTP is, or should be, ignored and use that information later on when SIGTSTP is manipulated in `set_signals()`.
