### ISSUE TITLE
:terminal doesn't use the 16 ANSI colors of the underlying terminal when t_Co > 16.

### ISSUE THREAD

**Issue by romainl** [vim/vim#5993]
`:help g:terminal_ansi_color` says:

> When not using GUI colors, the terminal window always uses the 16 ANSI colors of the underlying terminal.

When `&t_Co > 16`, this is true for 15 colors out of 16 but not for color 3, commonly called "DarkYellow" or "darkyellow".

**Detailed steps to reproduce the behavior:**

1. Set your `$TERM` to `xterm-256color`.
1. Run `vim --clean`.
2. Do `:terminal`.
3. Enter this command: `$ echo -e "\\033[48;5;3m        \\033[48;5;11m        \\033[0m"`.
4. You should get two rectangular blocks.

**Expected behavior**

* The first rectangular block should be painted in ANSI color 3 ("DarkYellow"), as defined at the terminal emulator level.
* The second rectangular block should be painted in ANSI color 11 ("Yellow"), as defined at the terminal emulator level.

The two blocks should be similar to this:
<img width="830" alt="Capture d’écran 2020-04-26 à 11 30 53" src="https://user-images.githubusercontent.com/344335/80303570-6c0d6600-87b1-11ea-8717-033fd19fb967.png">

Since the default ANSI colors are different from terminal emulator to terminal emulator *and* user-customisable, don't expect to have the exact same colors as in the screenshot above. This screenshot is only meant as a baseline to compare the actual behavior with.

**Actual behavior**

* The first rectangular block is incorrectly painted in a brownish orange, specifically color 130 in the xterm palette.
* The second rectangular block is correctly painted in ANSI color 11 ("Yellow"), as defined at the terminal emulator level.

MacOS 10.14.6, Bash 5.0.16, Vim 8.2.635, Terminal.app 2.9.5 (421.2):
<img width="830" alt="Capture d’écran 2020-04-26 à 11 24 12" src="https://user-images.githubusercontent.com/344335/80303457-c0641600-87b0-11ea-87a0-c9c6bc48f82c.png">

MacOS 10.14.6, Bash 5.0.16, Vim 8.2.635, iTerm.app 3.3.9:
<img width="830" alt="Capture d’écran 2020-04-26 à 11 41 57" src="https://user-images.githubusercontent.com/344335/80303829-f7d3c200-87b2-11ea-8a15-d857043d31b5.png">

MacOS 10.14.6, Bash 5.0.16, Vim 8.2.635, Kitty.app 10.7.3:
<img width="832" alt="Capture d’écran 2020-04-26 à 11 44 08" src="https://user-images.githubusercontent.com/344335/80303894-497c4c80-87b3-11ea-97b6-bd5f82200bd9.png">

MacOS 10.14.6, Bash 5.0.16, Vim 8.2.635, Alacritty 0.4.2:
<img width="832" alt="Capture d’écran 2020-04-26 à 11 46 21" src="https://user-images.githubusercontent.com/344335/80303953-9829e680-87b3-11ea-9f0f-2fbfbd9fcde2.png">

MacOS 10.14.6, Bash 5.0.16, Vim 8.2.635, XQuartz 2.7.11 (xorg-server 1.18.4), xterm 326:
<img width="730" alt="Capture d’écran 2020-04-26 à 11 49 16" src="https://user-images.githubusercontent.com/344335/80304035-fc4caa80-87b3-11ea-9801-e554128f34d7.png">

ANSI color 3 is systematically ignored and replaced with the same brownish orange, index 130 in the xterm palette.

Patch #5985 successfully fixed a related issue that affected general highlighting but I can't find what would cause the brownish switcheroo described in this issue.

**Comment by andymass** [comment]
@romainl What about white and bright black (escape code 47 & 100)?

**Comment by romainl** [comment]
@andymass What about them?

**Comment by andymass** [comment]
@romainl, using a basic [color test program](https://en.wikipedia.org/wiki/ANSI_escape_code#Example_of_use_in_C), I'm seeing a difference in white and bright black (37/47 & 90/100) when swapping between t_Co=256 and t_Co=16.
   
    cat color-test.c  # from wikipedia
    make color-test
    vim --clean +'term ./color-test'
    :nnoremap <space> :<c-u>let &t_Co = &t_Co > 16 ? 16 : 256 \| echo &t_Co<cr>

Tap space to see differences.  Prior to patch 8.2.0643, I also see dark yellow (33/43) changing.

**Comment by xulongwu4** [comment]
Yeah I observe the same thing as @andymass did. Prior to patch 8.2.0643, colors 3, 7, 8 in the vim terminal buffer do not match corresponding colors in a terminal emulator if `t_Co` is set to 256. Patch 8.2.0643 fixed color 3, but colors 7 (light grey) and 8 (dark grey) are still different.

I also tried vim version 8.0.1753, and the 16 ansi colors in a vim terminal buffer match exactly the ones in a terminal emulator when `t_Co` is set to 256. So I think this is a regression?

**Comment by romainl** [comment]
@andymass @xulongwu4 I tried that little program, too. Here are my results…

## Vim < 8.2.643 and `&t_Co == 256`:

* 3 (33/43) is brownish orange
* 7 (37/47) is darker than expected
* 8 (90/100) is darker than expected

## Vim < 8.2.643 and `&t_Co == 16`:

* all three colors are as expected

## Vim 8.2.643 and `&t_Co == 256`:

* 3 (33/43) is as expected
* 7 (37/47) is darker than expected
* 8 (90/100) is darker than expected

## Vim 8.2.643 and `&t_Co == 16`:

* all three colors are as expected

I suspect more hardcoding shenanigans.

**Comment by Shane-XB-Qian** [comment]
pls check my last comment at #5985, i think it's not about hardcode, as my understanding: it is just about reducing the impacted from terminal/palette, per diff terminal cfg such colors would looked diff, if changed like darkyellow/3 (and yes, it did now) - some one may/would complain such later ...

**Comment by romainl** [comment]
It's simple, really: I, the user, should be the only one making color-related decisions.

Here is a proposal:

1. The default behavior is to use the user's ANSI 0-15 untouched, no matter what is the current value of `&t_Co` or anything. $PROGRAM in `:terminal` says `3m`, parent terminal emulator paints with ANSI 3, end of the story.
2. We let the user define `g:terminal_ansi_color`-like override lists for each `&t_Co` value that matters to them:

        if &t_Co == 16
            let g:terminal_ansi_color = { 0, 2, 13, 4, ... }
        endif

        if &t_Co == 88
            let g:terminal_ansi_color = { 0, 2, 13, 4, ... }
        endif

        if &t_Co == 256
            let g:terminal_ansi_color = { 0, 2, 13, 4, ... }
        endif

This should give Vim:

* a simpler codebase with fewer special cases.

This should give users:

* a default experience that makes sense,
* the possibility to customise their experience according to their needs.

This should give colorscheme authors:

* a default experience that makes sense,
* more control over the integration of their colorscheme in more contexts.

**Comment by xulongwu4** [comment]
@Shane-XB-Qian The color palette used in a vim terminal buffer is really confusing at this moment (at least for me). When `t_Co` set to 256 and `notermguicolors`, Vim version 8.0.1753 respects the 16 ANSI colors of the parent terminal emulator, while vim 8.2 (prior to patch 8.2.643) has three colors that do not come from the ANSI colors of the parent terminal emulator, and I don't see this change is documented in vim's documentation. So I expect this is an unintended change and the expected behavior should be that vim terminal buffer uses the 16 ANSI colors from the parent emulator (as stated in the help tag for `g:terminal_ansi_color`)?

**Comment by Shane-XB-Qian** [comment]
i personally not like such patch much, i felt to 256 color: fixed color (over terminals) is more important, or someone like diff colorsheme or else -then 'true-color' (termguicolors) that should be used, and then `g:terminal_ansi_color` as you wish ..
anyway, up to @brammool ..

**Comment by IsaacElenbaas** [comment]
@romainl Could you reopen this? It's still not fixed, and the [difference in my colors](https://user-images.githubusercontent.com/34344969/97362179-fcb72280-1876-11eb-9fca-9f9892410773.png) is rather annoying. @brammool said in your pull "I suppose we can never do this right for everybody," but I don't see how not changing your colors would upset people nor why it would be difficult to get those colors.
@Shane-XB-Qian I am using GNU Screen and so `g:terminal_ansi_color` is not an option. I've played and searched around for a couple hours, there isn't even a janky workaround for this.
Even ignoring this issue, I don't see a reason for `g:terminal_ansi_colors` to not work without `termguicolors` (though perhaps only taking 256 color numbers).

**Comment by romainl** [comment]
@IsaacElenbaas I think the right course of action is to open a similar issue, but with a precise description of *your* problem and a link to this one. From your screenshot I can see that colors 7 and 8 are messed up, which should be the focus of your issue, I think.
