### ISSUE TITLE
Some explicitly listed registers in the docs should perhaps be replaced with {register}

### ISSUE THREAD

**Issue by lkintact** [vim/vim#5995]
This is related to #4979.

This is a (numbered) list obtained with `:lhelpgrep {0-9a-z"`:

1. index.txt|1118 col 28| |t_CTRL-W_quote|  CTRL-W " `{0-9a-z"%#*:=}`
2. repeat.txt|134 col 2| @`{0-9a-z".=*+}`		Execute the contents of register `{0-9a-z".=*+}` [count]
3. repeat.txt|146 col 27| @@			Repeat the previous @`{0-9a-z":*}` [count] times.
4. repeat.txt|148 col 9| :[addr]*`{0-9a-z".=+}`						*:@* *:star*
5. repeat.txt|149 col 9| :[addr]@`{0-9a-z".=*+}	`Execute the contents of register `{0-9a-z".=*+}` as an Ex
6. repeat.txt|169 col 34| :[addr]@@		Repeat the previous :@`{0-9a-z"}`.  First set cursor at

The highlighted parts should perhaps be replaced with the `{register}` tag, as was done in #4979.

Vim 8.2.0633.

**Comment by brammool** [comment]
> This is related to #4979.
> 
> This is a (numbered) list obtained with `:lhelpgrep {0-9a-z"`:
> 
> 1. index.txt|1118 col 28| |t_CTRL-W_quote|  CTRL-W " `{0-9a-z"%#*:=}`

OK.

> 2. repeat.txt|134 col 2| @`{0-9a-z".=*+}`		Execute the contents of register `{0-9a-z".=*+}` [count]
> 3. repeat.txt|146 col 27| @@			Repeat the previous @`{0-9a-z":*}` [count] times.
> 4. repeat.txt|148 col 9| :[addr]*`{0-9a-z".=+}`						*:@* *:star*
> 5. repeat.txt|149 col 9| :[addr]@`{0-9a-z".=*+}	`Execute the contents of register `{0-9a-z".=*+}` as an Ex

In these cases some register names are intentionally left out,
specifically % and #.

> 6. repeat.txt|169 col 34| :[addr]@@		Repeat the previous :@`{0-9a-z"}`.  First set cursor at

OK.

> The highlighted parts should perhaps be replaced with the `{register}`
> tag, as was done in #4979.
> 
> Vim 8.2.0633.

-- 
hundred-and-one symptoms of being an internet addict:
24. You realize there is not a sound in the house and you have no idea where
    your children are.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lkintact** [comment]
Thank you. Perhaps I should have lhelpgrepped more widely, `:lhelpgrep {0-9a-z` gives additional 3 lines:

7. index.txt|412 col 7| |q|		q`{0-9a-zA-Z"}`	   record typed characters into named register
8. index.txt|413 col 8| `{0-9a-zA-Z"}` (uppercase to append)
9. repeat.txt|118 col 2| q`{0-9a-zA-Z"}`		Record typed characters into register `{0-9a-zA-Z"}`

**Comment by lkintact** [comment]
And `:lhelpgrep {a-z.*regist` gives 9 more:

10. change.txt|999 col 2| "`{a-zA-Z0-9.%#:-"}`	Use register `{a-zA-Z0-9.%#:-"}` for next delete, yank
11. index.txt|249 col 11| |quote|		"`{a-zA-Z0-9.%#:-"}`  use register `{a-zA-Z0-9.%#:-"}` for next
12. index.txt|323 col 7| |@|		@`{a-z}`		2  execute the contents of register `{a-z}`
13. quickref.txt|489 col 12| |q|	      q`{a-z}`	record typed characters into register` {a-z}`
14. quickref.txt|492 col 12| |@|	   N  @`{a-z}`	execute the contents of register `{a-z}` (N times)
15. quickref.txt|494 col 11| |:@|	   :@`{a-z}`	execute the contents of register `{a-z}` as an Ex
16. various.txt|519 col 11| :redi[r] @`{a-zA-Z}`>	Redirect messages to register `{a-z}`.  Append to the
17. various.txt|523 col 11| :redi[r] @`{a-z}`>>	Append messages to register `{a-z}`.
18. version7.txt|1424 col 10| ":redir @`{a-z}`>>" appends to register a to z. (Yegappan Lakshmanan)

**Comment by lacygoill** [comment]
Fixed by https://github.com/vim/vim/commit/7ceefb35c8110d87ced884275ddbe63d024a014f.

The remaining matches can't be replaced with `{register}` because not all register names are valid when recording keys or executing the contents of a register.
