### ISSUE TITLE
0 Semicolon Search Ignores First Line

### ISSUE THREAD

**Issue by dylnmc** [vim/vim#5996]
## Bug Description

Using `:0;/PATTERN/` does not find the "first occurrence of `PATTERN` in the current buffer" if `PATTERN` is on line 1. This does work in *vi*, and `:help cmdline-ranges` does say the following in an example:

> 0;/that		the first line containing "that", also matches in the first line.
> 1;/that		the first line after line 1 containing "that"

## Bug Replication

1. Run `vim --clean`
2. Edit `test.txt` (see below, **test.txt** for an example)
3. Type `:0;/PATTERN/`
4. The cursor ends up on line 3 rather than line 1.

Consider the below example file (you may keep or disregard the prefixed line numbers as part of the buffer).

---
**test.txt**:
```
1. PATTERN 1
2. foo bar
3. PATTERN 2
```
---

Since `:0;/PATTERN/` in vi jumps to line 1, and the help suggests that vim should do the same, it seems like a bug that `:0;/PATTERN/` disregards the first line. (It seems like `:0,/PATTERN/` works properly even if PATTERN isn't on line 1, for what it is worth.)

## Info

 - *version __8.02.0618__*
 - *os __archlinux__ (compiled via modified __PKGBUILD__ from main arch repos)*
 - *terminal __urxvt__ (also tested in __st__ and __xterm__)*

**Comment by chrisbra** [comment]
This must be a recent regression. It looks like patch [8.0.0133](https://github.com/vim/vim/releases/tag/v8.0.0133) caused this. Well, took only 3.5 years until someone noticed :/

Here is a patch

```patch
diff --git a/src/ex_docmd.c b/src/ex_docmd.c
index c5dd1bd07..6a95a0c9c 100644
--- a/src/ex_docmd.c
+++ b/src/ex_docmd.c
@@ -3070,7 +3070,9 @@ parse_cmd_address(exarg_T *eap, char **errormsg, int silent)
            {
                curwin->w_cursor.lnum = eap->line2;
                // don't leave the cursor on an illegal line or column
-               check_cursor();
+               // but do accept zero as address, so 0;/PATTERN/ works correctly
+               if (eap->line2 > 0)
+                   check_cursor();
            }
        }
        else if (*eap->cmd != ',')
diff --git a/src/testdir/test_cmdline.vim b/src/testdir/test_cmdline.vim
index 7d3c0c87d..87edb2b72 100644
--- a/src/testdir/test_cmdline.vim
+++ b/src/testdir/test_cmdline.vim
@@ -1471,4 +1471,14 @@ func Test_cmdwin_insert_mode_close()
   call assert_equal(1, winnr('$'))
 endfunc

+func Test_zero_line_search()
+  new
+  call setline(1, ["1, pattern", "2, ", "3, pattern"])
+  call cursor(1,1)
+  0;/pattern/d
+  call assert_equal(["2, ", "3, pattern"], getline(1,'$'))
+  q!
+endfunc
+
+
 " vim: shiftwidth=2 sts=2 expandtab
```
