### ISSUE TITLE
Ctrl-] issue with Portuguese-Portugal keyboard layout

### ISSUE THREAD

**Issue by ircasl** [vim/vim#5997]
**Describe the bug**
The jump to tag shortcut `Ctrl-]` doesn't seem to work when using the Portuguese-Portugal keyboard layout.

It only shows `]` on the status bar when using showcmd.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Open GVim | Vim using either cmd or powershell.
2. Run `:set nocp` `:set showcmd`.
3. Open help using `:help`.
4. Move cursor to a tag.
5. Press `Ctrl-AltGr-´` to execute the jump to tag shortcut and fail.

**Expected behavior**
On a pt-PT keyboard `AltGr-´` gives the `]` character so I was expecting that `Ctrl-AltGr-´` would result in `Ctrl-]` shortcut.

**Environment (please complete the following information):**
 - GVim 8.2.0633 x64
 - OS: Windows 10 1809
 - Terminal: CMD,PowerShell and GVim GUI

**Additional context**

I already know this a pretty well know issue with non en-US keyboards, I already found a issue here on GitHub #1378 but in the reply it seems to suggest that the Belgian Keyboard is able to reproduce the `Ctrl-]` shortcut using `Ctrl-AltGr-$` similiar to the `Ctrl-AltGr-´` combination on the pt-PT keyboard. 

There's also possible some related threads on StackOverflow/Vi StackExchange like [this one](https://vi.stackexchange.com/questions/5732/tag-navigation-using-ctrl-does-not-work-with-non-english-keyboard-on-windows) that suggest that on non QWERTY keyboards we should use Ctrl-<Key on the same place of `]` in the US Keyboard> which in pt-PT keyboard is also `´`.

**Comment by tonymec** [comment]
I have a Belgian keyboard, and indeed it is capable to produce a Ctrl-] keystroke but not easily: I never use it. Indeed I had been using Vim for years before I found out how to make a Ctrl-] "natively" on my keyboard. What I use is the following, which can be used regardless of the keyboard layout on any Vim which can do mappings and is compiled with `+eval`: put it somewhere in your vimrc:
```vim
if exists(':map') == 2
    map  <F9>  <C-]>
    map! <F9>  <C-]>
endif
```
All this is written in ASCII in the vimrc (e.g. `<C-]>` is less-than, big-C, dash, close-square-bracket, greater-than). The use of <> notation assumes `'nocompatible'`, and of course you may replace `<F9>` by whatever strikes your fancy, preferably something that Vim doesn't already use.

Another possibility (but in Normal mode only, to go to a tag or follow help hotlinks) is to use a mouse double-click. To trigger an abbreviation in Insert or Command-line mode without inserting an additional character you could use backward-forward with the keyboard arrow keys.

Best regards,
Tony.

**Comment by ircasl** [comment]
Hey @tonymec thanks for the reply.

How did manage to figure out how to do it natively on your keyboard layout, did you stumble upon it? 
Or did you run some program to figure out the scan code that was being generated?

Also in your purposed workaround is the `if exists(':map') == 2` needed or is just there to check if Vim was compiled with the `+eval` option?

Sorry if I wasn't clear enough on the OP the issue isn't that I'm not able to use the shortcut but it's fact that it doesn't work when using a pt-PT keyboard layout with the key combination `Ctrl-AltGr-´` even though all information that I find seems to suggest that it should.

**Comment by ircasl** [comment]
So I did some further digging and found this website that has the information about the scancodes of each keyboard language layout here is the [pt-PT](http://kbdlayout.info/00000816/scancodes) and here's the [us-US](http://kbdlayout.info/00020409/scancodes), they both seem to have the same scancodes for the `Ctrl` key and share the same code for the `´` and `]` key.

This, plus the fact that I think the us keymappings we're used as a base for the other languages  layouts, supports the ideia that some non us keyboards are able to reproduce the `Ctrl-]` shortcut using the `Ctrl`-<Key on the same place of `]` in the US Keyboard>, it still doesn't explain why it doesn't work when using a pt-PT layout though. 

So to double check this scancode values were correct I also ran `showkey -s` on a live install of Kubuntu 20.04 LTS here's the results:
![pt-PT](https://user-images.githubusercontent.com/38358458/80807943-f25cea00-8bad-11ea-9c1d-017213fa89ce.png)
![us-US](https://user-images.githubusercontent.com/38358458/80807946-f557da80-8bad-11ea-9c59-08efdf742362.png)

And as you can see both layouts are generating the same scan codes for the `Ctrl-´` and the `Ctrl-]` as expected and the only difference being them outputting different characters the `^]` and the `´`.

From what I understand on the issue #1378 Vim `Ctrl-]` shortcut is read by checking the final key combo code that needs to be 0x1D (The 'ASCII' code as the showkey man page puts it). So this must mean that even though the `Ctrl-´` seems to be outputting as 0x1D 0x1B 0x9B same as `Ctrl-]` on the us-US layout it's not in actually giving 0x1D as the final key combo code.

So I've tried then running `showkey` with the `-a` argument and voilà I found one keycombo that gives the 0x1D byte and it works both on us-US and pt-PT:
![pt-PT_-a](https://user-images.githubusercontent.com/38358458/80815073-86ce4900-8bbc-11ea-9760-75bfe9302f6b.png)
![us-US_-a](https://user-images.githubusercontent.com/38358458/80815086-89c93980-8bbc-11ea-86c4-a506c128a7c2.png)

So now it all should be solved right? Wrong Windows doesn't seem to follow the same scancode/keymap standard so now I'm looking for a similar program to `showkey` for Windows I've come across this program taken from [StackOverflow](https://stackoverflow.com/questions/57153990/access-c-ascii-codes-via-windows-terminal/57154224):
```c
#include <conio.h>
#include <iostream>

int main()
{
	long c;
	while ((c = _getwch()) && c != 3)
		std::cout << "Keycode: 0x" << std::hex << c << std::endl;
}
```
But it doesn't work with certain key combos. This what I found so far will update if I find anything else.

**Comment by tonymec** [comment]
So you found that on your keyboard, Ctrl-5 produces a Ctrl-] character — on Kubuntu Linux with Portuguese (Portugal) locale. Congratulations! That's faster than I found that on my keyboard, AltGr-Ctrl-$ does the same. Since Ctrl-5 is relatively easy to hit, you can use that, yes (on Linux); and IIUC it will work even out of Vim (if ever you need it).

For any character which you *don't* find how to produce, for instance maybe for Ctrl-] on Windows, you can always (but only in Vim or gvim of course) assign it to the `{rhs}` of a mapping whose `{lhs}` will be something easy to hit and to remember, and that Vim doesn't use yet, for instance some `Fn` key. I still use that instead of that cumbersome Ctrl-AltGr-$ when I need a Ctrl-] in Vim or gvim.

Best regards,
Tony.

**Comment by ircasl** [comment]
Update time, so after even some more digging I found 4 tools of interest, some were more useful then the others.
I'll still post them all here in case someone needs them, but I ended up only using the last two to solve the problem on Windows:

1. A python script that uses getch from the msvcrt library, it's able to read most of the ASCII codes but not all (ScrLk and Pause for example):
```python
from msvcrt import getch
while True:
    key = getch()
    keyValue = int.from_bytes(key,"big")
    if keyValue == 3: #Ctrl-C
        break
    print("The pressed key was: 0x%04x" % keyValue)
```
2. A [C program](https://gist.github.com/WestonThayer/9b7a0e04b045be1656ce9f01de141cd2) that uses the WIN32 API raw input to read the key scancodes values, your antivirus might flag this.

3. [Keyview](http://www.cgl.ucsf.edu/home/tef/wintools/) a program that I assume uses the WIN32 API to read the pressed keys, I'm not sure exactly how it does it because I couldn't find the source code, the output looks something like this:
![keyview_b2kXrMVq6s](https://user-images.githubusercontent.com/38358458/80867562-4803c600-8c84-11ea-9011-7253174f14f3.png)
This was the most thorough tool that I found when it came to read the scancodes and the ASCII output of the key combos, I used it to check some keymaps that I wasn't able to check with the other tools.

4. And finally [Microsoft Keyboard Layout Creator](https://www.microsoft.com/en-us/download/details.aspx?id=22339), this one allowed me to check what keymaps were for each language layout.
For example here's the us-US keymap for the 0x1D byte:
![MSKLC_cDqXIoHMwx](https://user-images.githubusercontent.com/38358458/80867676-ef80f880-8c84-11ea-8897-dfb97a037f72.png)
And here's the pt-PT keymap:
![MSKLC_WamqDCNSRo](https://user-images.githubusercontent.com/38358458/80867918-74204680-8c86-11ea-976f-2b817ebc64a9.png)
As we're able to see the `Ctrl-5` keymap that was present on Kubuntu pt-PT keyboard layout is not present on the Windows pt-PT layout so what I did is I used this tool to add it to a new custom layout
![MSKLC_xIgkURlfMh](https://user-images.githubusercontent.com/38358458/80868656-96689300-8c8b-11ea-8b67-75efdd1f6474.png)
![MSKLC_uRYmApSmdl](https://user-images.githubusercontent.com/38358458/80868663-a3858200-8c8b-11ea-808b-f0102c1ee466.png)
I then built it and installed it
![MSKLC_Yy9UY1JOBW](https://user-images.githubusercontent.com/38358458/80868681-b39d6180-8c8b-11ea-8c75-212351875581.png)
And now GVim/Vim jump to tag shortcut works as expected on Windows when using `Ctrl-5` :)

I'll add some more notes when I have time before I close this issue so for now I'll leave it open for discussion.

**Comment by ircasl** [comment]
Last update so this will be just a few notes of what I would like to know about this issue before I started.

`^]` is not `Ctrl `+ `]` even though Vim represents it like it is, `^]` is in fact the representation of the GS(Group Seperator) character, that's why you can use other type of key combinations and still get the `^]` shortcut showup when `:set showcmd` is turned on. 

Scancode != ASCII code. Each key on the keyboard has a scancode, even though some scancodes could coincide with the ASCII code for that key they are not in fact the same thing, what seems to matter to Vim is the ASCII code. And that's why again you can use different key combos and still get `Jump to Tag` shortcut. 
In this case specific case you're not trying to get the combination `Ctrl` + `]`  which  for example in my case is `Ctrl-AltGr-´`, what you're trying to get is a key combo that gets you what `Ctrl` + `]` gives you in the us-US layout (The keyboard layout that I assume was used when creating Vim shortcuts) that is the GS character, which for my keyboard layout in Linux is  `Ctrl` + `5`.

Windows keyboard layouts might have different keymaps (translate scancode -> ASCII Code) from the Linux ones so something that might work on Linux might not on Windows which was this case.

P.S: While trying to find solution to this problem I also came across the ANSI escape codes support that seems to be different from Windows vs. Linux, but I found it not to be relevant to this shortcut issue, still there might be some shortcut that doesn't work because of it.
