### ISSUE TITLE
7.4.1185 fails to build with VS2015 on Windows 10

### ISSUE THREAD

**Issue by nanis** [vim/vim#600]
```
C:\...\vim\src> nmake -f Make_mvc.mak CPU=AMD64 OPTIMIZE=MAXSPEED NETBEANS=no GETTEXT=no CSCOPE=no XPM=no DIRECTX=yes GUI=yes
 ....
C:\...\src\gui_w48.c(1786): warning C4013: 'netbeans_read' undefined; assuming extern returning int
 ....
gui_w32.obj : error LNK2001: unresolved external symbol netbeans_read
gvim.exe : fatal error LNK1120: 1 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\link.EXE"' : return code '0x460'
Stop.
```

I have always built my `vim` and `gvim` without Netbeans support on Windows, so I consider it not working to be a bug, but if something changed and now this is expected behavior, I'll adjust my expectations accordingly.

**Comment by brammool** [comment]
A. Sinan Unur wrote:

> ```
> C:\...\vim\src> nmake -f Make_mvc.mak CPU=AMD64 OPTIMIZE=MAXSPEED NETBEANS=no GETTEXT=no CSCOPE=no XPM=no DIRECTX=yes GUI=yes
>  ....
> C:\...\src\gui_w48.c(1786): warning C4013: 'netbeans_read' undefined; assuming extern returning int
>  ....
> gui_w32.obj : error LNK2001: unresolved external symbol netbeans_read
> gvim.exe : fatal error LNK1120: 1 unresolved externals
> NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\link.EXE"' : return code '0x460'
> Stop.
> ```

Patch 7.4.1187 should fix this.

## 

"I can't complain, but sometimes I still do."   (Joe Walsh)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by nanis** [comment]
Yes, both `vim` and `gvim` build without problems now. Thank you.
