### ISSUE TITLE
systemctl edit --full isn't matched in vim's runtime.filetype

### ISSUE THREAD

**Issue by sidequestboy** [vim/vim#6003]
When I have my `SYSTEMD_EDITOR` set to `vim`, when I type

```sh
systemctl --user edit --full my-service.service
```

systemd copies the original file at `~/.config/systemd/user/my-service.service` to a temporary file named something like `~/.config/systemd/user/.#my-service.servicea607eb9af2ab1b6e`

This is not matched by vim's [`runtime/filetype.vim#L1651`](https://github.com/vim/vim/blob/2c7f8c574f1f8723d59adca3fec8fb89c41cf8c9/runtime/filetype.vim#L1651) (@brammool)

Note that without `--full`, the filetype is detected with the patterns at line 1651

```vim
" Systemd temp files
au BufNewFile,BufRead */etc/systemd/system/*.d/.#*	setf systemd
au BufNewFile,BufRead */.config/systemd/user/*.d/.#*	setf systemd
```

These patterns should probably be revised to

```vim
" Systemd temp files
au BufNewFile,BufRead */etc/systemd/system/.#*		setf systemd
au BufNewFile,BufRead */.config/systemd/user/.#*	setf systemd
```

vim version 8.2, arch linux

**Comment by brammool** [comment]
> When I have my `SYSTEMD_EDITOR` set to `vim`, when I type
> 
> ```sh
> systemctl --user edit --full my-service.service
> ```
> 
> systemd copies the original file at `~/.config/systemd/user/my-service.service` to a temporary file named something like `~/.config/systemd/user/.#my-service.servicea607eb9af2ab1b6e`
> 
> This is not matched by vim's [`runtime/filetype.vim#L1651`](https://github.com/vim/vim/blob/2c7f8c574f1f8723d59adca3fec8fb89c41cf8c9/runtime/filetype.vim#L1651) (@brammool)
> 
> Note that without `--full`, the filetype is detected with the pattern with the patterns at line 1651
> 
> ```vim
> " Systemd temp files
> au BufNewFile,BufRead */etc/systemd/system/*.d/.#*	setf systemd
> au BufNewFile,BufRead */.config/systemd/user/*.d/.#*	setf systemd
> ```
> 
> These patterns should probably be revised to
> 
> ```vim
> " Systemd temp files
> au BufNewFile,BufRead */etc/systemd/system/.#*		setf systemd
> au BufNewFile,BufRead */.config/systemd/user/.#*	setf systemd
> ```

You mention you see the actual file is
	~/.config/systemd/user/.#my-service.servicea607eb9af2ab1b6e

So the extra pattern would be:
	au BufNewFile,BufRead */.config/systemd/user/.#*	setf systemd

Why add any others?

-- 
How To Keep A Healthy Level Of Insanity:
14. Put mosquito netting around your work area. Play a tape of jungle
    sounds all day.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mgedmin** [comment]
> So the extra pattern would be:
>	au BufNewFile,BufRead */.config/systemd/user/.#*	setf systemd
> 
> Why add any others?

`systemctl --user edit --full` edits temporary files in ~/.config/systemd/user/.  With `--full` and without `--user` it would edit system-wide unit files in /etc/systemd/system/.

There ought to be four patterns to account for the four possible combinations of `--user` and `--full`.

**Comment by jameh** [comment]
Yes, there's four locations - my impression was that the pattern  

```sh
*/.config/systemd/user/.#*
```

would match the temporary files from both `systemctl --user edit {,--full}` whose filenames look like:

```
~/.config/systemd/user/my-service.d/.#override.confa607eb9af2ab1b6e
~/.config/systemd/user/.#my-service.servicea607eb9af2ab1b6e
```

and the pattern

```sh
*/etc/systemd/system/.#*
```

would match the temporary files from both `systemctl edit {,--full}` whose filenames look like:

```
/etc/systemd/system/my-service.d/.#override.confa607eb9af2ab1b6e
/etc/systemd/system/.#my-service.servicea607eb9af2ab1b6e
```

So that the four locations could be covered with just these two globbing patterns

**Comment by sidequestboy** [comment]
Yes there are four locations that look like this:

```sh
~/.config/systemd/user/my-service.d/.#override.confa607eb9af2ab1b6e
~/.config/systemd/user/.#my-service.servicea607eb9af2ab1b6e
/etc/systemd/system/my-service.d/.#override.confa607eb9af2ab1b6e
/etc/systemd/system/.#my-service.servicea607eb9af2ab1b6e
```

I made a mistake in my suggested revision to the glob patterns above. These locations should be covered by these four patterns (two of which already exist):

```sh
*/.config/systemd/user/*.d/.#*
*/.config/systemd/user/.#*
*/etc/systemd/system/*.d/.#*
*/etc/systemd/system/.#*
```
