### ISSUE TITLE
syntax/make.vim: Highlighting for "override" is too broad

### ISSUE THREAD

**Issue by jamessan** [vim/vim#6005]
Any line which starts with the word `override` highlights it as the keyword, as shown in the attached image.

![2020-04-27_21-34](https://user-images.githubusercontent.com/112971/80434304-7b7ed300-88c7-11ea-9e82-7df6f8a1eaf1.png)

It looks like it should follow the pattern of `makeExport` and require a word boundary:

```diff
diff --git i/runtime/syntax/make.vim w/runtime/syntax/make.vim
index 2a64dcd85..37969ff26 100644
--- i/runtime/syntax/make.vim
+++ w/runtime/syntax/make.vim
@@ -73,7 +73,7 @@ syn match makePreCondit	"^ *\(ifn\=\(eq\|def\)\>\|else\(\s\+ifn\=\(eq\|def\)\)\=
 syn match makeInclude	"^ *[-s]\=include\s.*$"
 syn match makeStatement	"^ *vpath"
 syn match makeExport    "^ *\(export\|unexport\)\>"
-syn match makeOverride	"^ *override"
+syn match makeOverride	"^ *override\>"
 " Statements / Functions (GNU make)
 syn match makeStatement contained "(\(abspath\|addprefix\|addsuffix\|and\|basename\|call\|dir\|error\|eval\|file\|filter-out\|filter\|findstring\|firstword\|flavor\|foreach\|guile\|if\|info\|join\|lastword\|notdir\|or\|origin\|patsubst\|realpath\|shell\|sort\|strip\|subst\|suffix\|value\|warning\|wildcard\|word\|wordlist\|words\)\>"ms=s+1
 
```

---
[§6.11](https://www.gnu.org/software/make/manual/make.html#Target_002dspecific-Variable-Values) of GNU Make's manual also mentions:

> Target-specific variable assignments can be prefixed with any or all of the special keywords `export`, `override`, or `private`; these apply their normal behavior to this instance of the variable only.

It would be nice to handle this in the highlighting.

Cc @rohieb

**Comment by rohieb** [comment]
Yes, your patch looks right to me. @brammool, can you include it?

**Comment by brammool** [comment]
I'll include the word boundary check.   Still seems a bit brittle, but should catch most cases.
