### ISSUE TITLE
ANSI save/restore cursor position escape sequences not working in terminal

### ISSUE THREAD

**Issue by gmoshkin** [vim/vim#6006]
**Describe the bug**
ANSI escape sequences for save cursor position `\033[s` and restore cursor position `\033[u` are not working (properly) in the terminal mode.

**To Reproduce**
Do:
1. Run `vim --clean -cterm`
2. Run a shell command like `printf "\e[s 1\e[u2\n"`
The output you get is something like ` 12`.

**Expected behavior**
What you want to get is `21`.

**Screenshots**
![image](https://user-images.githubusercontent.com/10168363/80519132-2f4b9580-8990-11ea-9e1b-5e1ffcf5beae.png)

**Environment:**
 - Vim version:
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 28 2020 23:23:28)
Included patches: 1-654
```
 - OS: Manjaro Linux
 - Terminal: GNOME Terminal

**Comment by brammool** [comment]
> **Describe the bug**
> ANSI escape sequences for save cursor position `\033[s` and restore cursor position `\033[u` are not working (properly) in the terminal mode.
> 
> **To Reproduce**
> Do:
> 1. Run `vim --clean -cterm`
> 2. Run a shell command like `printf "\e[s 1\e[u2\n"`
> The output you get is something like ` 12`.
> 
> **Expected behavior**
> What you want to get is `21`.
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/10168363/80519132-2f4b9580-8990-11ea-9e1b-5e1ffcf5beae.png)

It looks like these escape sequences are not implemented by libvterm.

-- 
How To Keep A Healthy Level Of Insanity:
6. In the memo field of all your checks, write "for sexual favors".

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by jamessan** [comment]
Right, because libvterm is targeting VT100-based terminals which use DECSC/DECRC (`\e7`/`\e8`), not ANSI.  What is generating these escape sequences?

**Comment by gmoshkin** [comment]
@jamessan I was using those sequence in my own code. I guess I'll just use DECSC/DECRC instead, thanks! The issue can be closed

**Comment by jamessan** [comment]
> I was using those sequence in my own code. I guess I'll just use DECSC/DECRC instead, thanks!

Even better would probably be to query the terminfo db for the `sc`/`rc` capabilities to know what to send, rather than hard code values.
