### ISSUE TITLE
Opening new buffer behaviour change?

### ISSUE THREAD

**Issue by pauldthomson** [vim/vim#6008]
**Describe the bug**
Using [vim-go](https://github.com/fatih/vim-go), sometime between Vim versions `8.1.0500` and `8.1.0600`, `:GoDef` functionality broke. I know this is a plugin and not necessarily a Vim thing, but I pinned down the change to jumping between those versions of Vim.

The command above is used to jump to the definition of a symbol in a Go file. If the definition is in another file, the file is opened in a new buffer and that buffer is switched to.

The problem I started seeing is that _only_ when jumping to the definition requires opening a new buffer, the new buffer is opened but Vim hangs and doesn't jump to it. If I hit ctrl+c then it jumps to the newly opened file. If the file was already open in another buffer, then everything works as expected. So this only happens when a file is being newly opened in a new buffer.

I guess I'm wondering if anything rings a bell to anyone about anything that may have changed in Vim between `8.1.0500` and `8.1.0600` around the behaviour of opening files in buffers? 

**To Reproduce**
1. Install [vim-go](https://github.com/fatih/vim-go)
2. Clone this repo: https://github.com/schemahero/schemahero
3. Open this [file](https://github.com/schemahero/schemahero/blob/master/pkg/controller/table/reconile_table.go) at [this line](https://github.com/schemahero/schemahero/blob/841b9e897f278e34e9b04a041e9968eb1b5b0d8c/pkg/controller/table/reconile_table.go#L199)
4. Run `:GoInstallBinaries` (sorry, I know this might require some Go setup)
5. On the line referenced above, move the cursor over `r.getPlanPod()`
6. Run `:GoDef`

**Expected behavior**
The file containing the definition is loaded in a new buffer, and vim jumps to the definition in that file

**Environment (please complete the following information):**
 - Vim version: 8.1.0600
 - OS: macOS 10.14.6
 - Terminal: iTerm2

**Comment by pauldthomson** [comment]
I noticed the same behaviour in a Java project using [coc.nvim](https://github.com/neoclide/coc.nvim) and [coc-java](https://github.com/neoclide/coc-java).

It's always when Vim's `gd` command will have to open another file in a new buffer. Buffer is opened but not jumped to.

**Comment by chrisbra** [comment]
can someone bisect the offending commit?

**Comment by lacygoill** [comment]
I can't reproduce.  I followed the instructions given in the OP, and with this minimal vimrc:

    set rtp-=~/.vim
    set rtp-=~/.vim/after
    set rtp^=$HOME/Vcs/vim/runtime
    set rtp^=/run/user/1000/tmp/vim-go
    filetype plugin on

It takes a few seconds for `:GoDef` to jump to the definition, but Vim doesn't hang; be it on 8.1.0500, 8.1.0600 or master:

![gif](https://user-images.githubusercontent.com/8505073/80809775-ab2d2400-8bc2-11ea-892d-ee0a0110a4ca.gif)

Something else must be necessary to reproduce the issue.

**Comment by pauldthomson** [comment]
Ok through deleting plugins one by one the offender seems to be [vim-gitgutter](https://github.com/airblade/vim-gitgutter), although not really sure how yet...

**Comment by chrisbra** [comment]
Ping @airblade

**Comment by airblade** [comment]
I tried to follow the repro steps but had some kind of problem installing the Go dependencies.

<img width="1260" alt="Screenshot 2020-05-04 at 10 06 57 am" src="https://user-images.githubusercontent.com/7265/80951236-65a16e80-8def-11ea-87c3-ccf71ac2f1e3.png">

I scanned through the git log for the commit range you gave but nothing jumped out at me.  If you were able to bisect the offending commit, that would really help.

Also, what commit is your copy of vim-gitgutter at?

When you enter a new buffer, vim-gitgutter (a) sets up some maps; (b) asynchronously figures out the file's path relative to the repo root; then (c) asynchronously runs a diff.  If the buffer already exists, only (c) happens.

Another approach to debugging this would be to profile what's happening.  Hopefully that would indicate where things are getting held up.

**Comment by pauldthomson** [comment]
[vim-plug.log](https://github.com/vim/vim/files/4576801/vim-plug.log)
Attached the profile log. I'm no expert in reading this but `gitgutter#diff#run_diff()` seems to be the culprit. Here's a second example where I let it sit for longer before hitting ctrl-c:
[vim-plug-2.log](https://github.com/vim/vim/files/4576828/vim-plug-2.log)

There seems to be a while loop that calls `gitgutter#utility#repo_path` and that looks like it was called 1163 and 2781 in the first 2 examples respectively, with `gitgutter#utility#getbufvar()` right behind it.

Here's an example from when the target file was already loaded in a buffer:
[vim-plug-3.log](https://github.com/vim/vim/files/4576858/vim-plug-3.log)

> Also, what commit is your copy of vim-gitgutter at?
Current `HEAD` of master, `b356cc9`


So I had all that ^ written up and decided to do one more remove/reinstall of the plugin, and now it works 🤦 

I'm gonna leave the profile logs here so I don't look crazy 😛 , but I guess sorry for wasting your time (_orrrr_, hooray, nothing to fix?)

**Comment by chrisbra** [comment]
so now it works?

**Comment by LyleZiegelmiller** [comment]
“so now it works?”
Yes.

As per my last comment:
Is anyone relying on the editor lurching into a random location and size on the screen simply because the user both:

  1.  Snapped the editor to the right-hand side of the screen with Windows Key + right arrow
  2.  Split the editor pane vertically
?

I will say no more about it. 😊


Lyle

**Comment by pauldthomson** [comment]
> so now it works?

Yep. Not sure why now, I had removed/re-added the plugin several times to confirm it was the culprit and on 2 machines and it was reproducible. But the last one sorted it.

Will close the issue. Thanks and sorry!
