### ISSUE TITLE
set cursorline drains CPU

### ISSUE THREAD

**Issue by fredaas** [vim/vim#6012]
**Description**

Scrolling up/down with `set cursorline` enabled is slow to the point where the editor becomes nearly unusable. Close to 100% of the CPU core the Vim instance is running on is utilized when scrolling with `set cursorline` enabled. 

**To Reproduce**

1. `vim --clean <filename>`
2. `set cursorline`
3. Scroll up/down the document with `j` and `k`

**Expected Behavior**

Close to zero observed latency is what I expect when scrolling in any descent editor.

**Environment**

- Vim version: 8.0.1453
- OS: Linux 4.15.0-72-generic, Ubuntu 18.04.3 LTS
- Terminal: GNOME Terminal

**Comment by chrisbra** [comment]
Please try an updated vim first. There have been some improvements
