### ISSUE TITLE
configure tty group/mode detection is broken

### ISSUE THREAD

**Issue by taralx** [vim/vim#6024]
On linux (and most platforms), configure will fail to detect the tty group/mode because it is looking at the wrong file descriptor.

The problem line is: https://github.com/vim/vim/blob/c8cd2b34d1027c93fbca90f3cdc8123fe22dfa25/src/auto/configure#L12512

The reason is that autoconf now moves the stdin aside to avoid accidentally blocking on input: 

https://github.com/vim/vim/blob/c8cd2b34d1027c93fbca90f3cdc8123fe22dfa25/src/auto/configure#L557

FWIW this has been broken since [at least 2010](https://github.com/vim/vim/commit/abb8d0b23a6cacc4881a812bbe60a63f16e2484f), so perhaps this check doesn't do anything anyone cares about?

**Comment by brammool** [comment]
> On linux (and most platforms), configure will fail to detect the tty group/mode because it is looking at the wrong file descriptor.
> 
> The problem line is: https://github.com/vim/vim/blob/c8cd2b34d1027c93fbca90f3cdc8123fe22dfa25/src/auto/configure#L12512
> 
> The reason is that autoconf now moves the stdin aside to avoid accidentally blocking on input: 
> 
> https://github.com/vim/vim/blob/c8cd2b34d1027c93fbca90f3cdc8123fe22dfa25/src/auto/configure#L557
> 
> FWIW this has been broken since [at least 2010](https://github.com/vim/vim/commit/abb8d0b23a6cacc4881a812bbe60a63f16e2484f), so perhaps this check doesn't do anything anyone cares about?

Looks like the resulting macros are not used anywhere.  I guess they
were removed at some point in the past.

-- 
You have the right to remain silent. Anything you say will be
misquoted, then used against you.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
