### ISSUE TITLE
":norm" fails to run "feedkeys()" with the "t" flag

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6037]
**Describe the bug**

`:norm` fails to run `feedkeys()` with the `t` flag.

**To Reproduce**

Start Vim with this shell command:

    vim -Nu NONE +'nno cd :exe "norm! :call feedkeys(\"aaa\",\"t\")\r"<cr>'

Press `cd`: nothing is inserted in the buffer.

**Expected behavior**

`aa` is inserted in the buffer.

**Environment**

 - Vim version: 8.2 Included patches: 1-683
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

If you remove the `t` flag, the issue disappears:

    vim -Nu NONE +'nno cd :exe "norm! :call feedkeys(\"aaa\")\r"<cr>'
    " press 'cd': 'aa' is inserted in the buffer

If you use the `x` flag, the issue – again – disappears:

                                                                v
    vim -Nu NONE +'nno cd :exe "norm! :call feedkeys(\"aaa\",\"tx\")\r"<cr>'
    " press 'cd': 'aa' is inserted in the buffer

---

You really need `:norm` to reproduce the issue.
For example, if you try to replace it with a second `feedkeys()`, the issue disappears (no matter whether you use the `t` flag in any function call):

    nno cd :call feedkeys('gh', 't')<cr>
    nno gh :call feedkeys('aaa', 'nt')<cr>
    " press 'cd': 'aa' is inserted

**Comment by brammool** [comment]
Using feedkeys() is mainly for tests.  There might be a few valid uses cases besides tests, but generally feedkeys() should be avoided.  The combination with :normal is especially problematic, both stuff text into the input buffer.
So the first question is: why are you doing this?

**Comment by lacygoill** [comment]
> So the first question is: why are you doing this?

I'm just studying how mappings work in Vim, and found this behavior which seems inconsistent.

> Using feedkeys() is mainly for tests. There might be a few valid uses cases besides tests, but generally feedkeys() should be avoided. The combination with :normal is especially problematic, both stuff text into the input buffer.

Ah ok, it makes sense; this is just an edge case, so I close the issue.
