### ISSUE TITLE
:source! behavior difference

### ISSUE THREAD

**Issue by justinmk** [vim/vim#606]
Vim 7.4.1187. In test53.in[1] there is this block of normal-mode commands:

```
/^<begin
jfXdit
0fXdit
fXdat
0fXdat
dit
```

which performs on this test buffer:

```
<begin>
-<b>asdf<i>Xasdf</i>asdf</b>-
-<b>asdX<i>a<i />sdf</i>asdf</b>-
-<b>asdf<i>Xasdf</i>asdf</b>-
-<b>asdX<i>as<b />df</i>asdf</b>-
-<b>
innertext object
</b>
</begin>
```

But the last `<cr>dit` does not actually work if you perform the commands interactively. It _does_ work if you save the commands to a file, e.g. "Xdotest", then source the commands with ":source! Xdotest" while viewing the test buffer.

[1] https://github.com/vim/vim/blob/master/src/testdir/test53.in#L21-L26

**Comment by chrisbra** [comment]
Does that work better?

``` patch
diff --git a/src/testdir/test53.in b/src/testdir/test53.in
--- a/src/testdir/test53.in
+++ b/src/testdir/test53.in
@@ -23,7 +23,7 @@ jfXdit
 0fXdit
 fXdat
 0fXdat
-dit
+0f<dit
 :"
 :put =matchstr(\"abcd\", \".\", 0, 2) " b
 :put =matchstr(\"abcd\", \"..\", 0, 2) " bc
```

**Comment by justinmk** [comment]
@chrisbra Yes, for sure. But is this possibly a bug with `:source!` ?

**Comment by chrisbra** [comment]
might be. I am not sure.

**Comment by brammool** [comment]
Justin M. Keyes wrote:

> Vim 7.4.1187. In test53.in[1] there is this block of normal-mode commands:
> 
> ```
> /^<begin
> jfXdit
> 0fXdit
> fXdat
> 0fXdat
> dit
> ```
> 
> which performs on this test buffer:
> 
> ```
> <begin>
> -<b>asdf<i>Xasdf</i>asdf</b>-
> -<b>asdX<i>a<i />sdf</i>asdf</b>-
> -<b>asdf<i>Xasdf</i>asdf</b>-
> -<b>asdX<i>as<b />df</i>asdf</b>-
> -<b>
> innertext object
> </b>
> </begin>
> ```
> 
> But the last `<cr>dit` does not actually work if you perform the
> commands interactively. It _does_ work if you save the commands to a
> file, e.g. "Xdotest", then source the commands with ":source! Xdotest"
> while viewing the test buffer.

Weird, it's like the curswant column is different.  Ah, it's the
difference between CR and NL: You type CR but the line break is a NL.
Try typing CTRL-J instead.

So Christian's suggestion to do "0f>" removes the difference.

## 

Proof techniques #2: Proof by Oddity.
    SAMPLE: To prove that horses have an infinite number of legs.
(1) Horses have an even number of legs.
(2) They have two legs in back and fore legs in front.
(3) This makes a total of six legs, which certainly is an odd number of
    legs for a horse.
(4) But the only number that is both odd and even is infinity.
(5) Therefore, horses must have an infinite number of legs.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by justinmk** [comment]
So not a bug. Thanks
