### ISSUE TITLE
The description of "[converted]" should probably be changed

### ISSUE THREAD

**Issue by lkintact** [vim/vim#6068]
As the indication "[converted]" is displayed in status line not only when the file is read (like in `"cp1251.txt" [converted] 1L, 27C`), when the conversion is made _from 'fileencoding' to 'encoding'_, but also when the file is written (like in `"cp1251.txt" [converted] 1L, 32C written`), when the reverse conversion is made, _from 'encoding' to 'fileencoding'_, the description of "[converted]" in doc/insert.txt, lines 2055-2056 should probably be changed to reflect that.

Vim: https://github.com/vim/vim-win32-installer/releases/download/v8.2.0735/gvim_8.2.0735_x86_signed.zip

**Comment by lkintact** [comment]
...but on the other hand, since the description of "[converted]" is given in the "_read_-messages" (doc/insert.txt, line  2036) section, perhaps no connection of "[converted]" to _writing_ files belongs in there.

**Comment by brammool** [comment]
There is no list to explain the message for writing.  I can add something at the help for ++enc
