### ISSUE TITLE
cursor in wrong position in a regular buffer displayed in a popup terminal

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6072]
**Describe the bug**

After pressing `gf` on a file path in a popup terminal, the cursor is wrongly positioned whenever insert or visual mode is entered.

**To Reproduce**

Write this in `/tmp/test.vim`:

    set hidden
    let bufnr = term_start(&shell, #{hidden: v:true})
    let winid = popup_create(bufnr, {'minwidth': &columns/2, 'border': [], 'minheight': &lines/2})
    call feedkeys('/tmp/file')

Run this shell command:

    printf -- 'foo\nbar' >/tmp/file && vim -Nu NONE -S /tmp/test.vim

- Press `C-\ C-n` to switch to Terminal-Normal mode.
- Press `gf` to load the file whose path is under the cursor.
- Press `V` to select the line `foo`; Vim seems to ignore the first character `f`, and the cursor jumps to the next line.
- Keep pressing `j` to extend the visual selection down to the lines below; the cursor moves to lines which don't contain text, it then goes beyond the popup and only stops once it reaches the bottom-right corner of the terminal window.

**Expected behavior**

One of these statements is true:

- It is forbidden to load a regular buffer in a popup terminal, and `gf`/`gF` raise `E994` (just like `C-w f`) or `E863` (just like `:e /tmp/file`).

- It is allowed for `gf`/`gF` to load a regular buffer in a popup terminal, in which case:

    Pressing `V` initially selects the whole line `foo`, and the cursor stays on the latter.
    Pressing `j` repeatedly selects the lines `foo` and `bar`; the cursor does not go beyond those.

**Screenshots**

![gif](https://user-images.githubusercontent.com/8505073/81673583-2bb61500-944c-11ea-9aa5-4778d6300d1c.gif)

**Environment**

 - Vim version: 8.2 Included patches: 1-740
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

There are similar issues when entering insert mode.
Sometimes, the cursor and the character which is inserted are in different positions.

---

The issue seems to disappear if the popup is created without a border.

**Comment by brammool** [comment]
Looks like you found a way to escape the terminal in the popup.  That should not be possible.  I think it should not even be possible to enter Terminal-Normal mode.  Let's see if I can disable that.

**Comment by brammool** [comment]
Hmm, a test is actually using Terminal-Normal mode, thus we need to disallow editing another file.
