### ISSUE TITLE
Set breakpoints on shared library source code with Termdebug

### ISSUE THREAD

**Issue by dcaballe** [vim/vim#6074]
Hi!

I'm giving Termdebug a try! Thanks for adding this feature!
I'm struggling with adding breakpoints to source code from shared libraries since Gdb doesn't load the source code until the binary is run at least once. If I try to add a breakpoint before running I get: `No source file named xxxx.xxx`. However, Gdb allows adding breakpoints to source code not loaded yet:
```
(gdb) b MySharedLib.cpp:77
No source file named MySharedLib.cpp.
Make breakpoint pending on future shared library load? (y or [n]) y
```
Is there a way to do this from the `:Break` command?

Thanks,
Diego

**Comment by GitMensch** [comment]
Workaround: there's a way to let GDB load the library even if it isn't active yet, see https://stackoverflow.com/questions/20380204/how-to-load-multiple-symbol-files-in-gdb/62471062#62471062 (if you have that in .gdbinit then you can manually load the library into GDB and then the `:Break` "obviously" will also work)

**Comment by chrisbra** [comment]
closing this, as this is not a vim problem and there is a work around.
