### ISSUE TITLE
Behavior Inconsistency of Some Motion

### ISSUE THREAD

**Issue by ghost** [vim/vim#6076]
In normal mode, `v$` then `d` performs variously from `d$`, and the former includes an `enter` or `\n`.

Is this a bug or a feature?

**Comment by chrisbra** [comment]
it is a feature and is mentioned briefly in `:h $`:

> 			In Visual mode the cursor goes to just after the last
> 			character in the line.

I always think of this as the cursor being on the `\n` (which is not selectable or visible by itself, apart from actually starting a new line). I suppose it was intentionally made that way, so you can either include or exclude the linebreak depending on the situation.

**Comment by k-takata** [comment]
You may want to use `vg_` if you don't want to include the `\n`.

Anyway, this is a user question. Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. Closing.

**Comment by Houl** [comment]
It's configurable: `:set selection=old`.
