### ISSUE TITLE
Undo inside a macro undoes the macro itself 

### ISSUE THREAD

**Issue by sosmo** [vim/vim#6080]
**Describe the bug**
Not sure if this is a bug per se, but the "undo" function when recording a macro doesn't behave as you'd expect it to. When recording a macro, "undo" reverts the last change. However, when replaying the recorded macro, the undo no longer behaves as if it was typed by the user, but instead returns back to the point where the macro was initiated. So it undoes everything inside the macro that came before it. I assume this is because Vim merges the changes of a macro together into one undo point, but the same thing happening for undos performed inside the macro is troublesome.

**To Reproduce**
1. Run `vim --clean` (or `gvim --clean`, etc.)
2. Type:
    ```
    iabcdef<esc>
    0qq
    ix<esc>
    lliy<esc>
    uix<esc>
    llq
    @q
    ```

The result of repeating the macro should intuitively be "xaxbxcxdef" - two x's inserted twice, as two x's were inserted during recording. However, the "u" inside the macro undoes the start of the macro (insertion of the first x), and you're left with just one.

:version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Mar 19 2020 13:12:18)
Included patches: 1-875

**Comment by brammool** [comment]
This is not a bug, see the help at "undo-blocks"

**Comment by sosmo** [comment]
> This is not a bug, see the help at "undo-blocks"

Thanks. Could this be made into a feature request instead? I know I've stumbled on it quite a few times when recording macros, but only now realized it's because of undo joins. Joining undos of a macro is great, but when you repeat a macro you'd expect "u" inside it to function similarly to how it functioned when you first recorded it. I'm not sure but I believe Emacs handles it that way while also joining the macro undos together. if not possible, maybe document that the undo context is different inside macro execution vs recording?

**Comment by tonymec** [comment]
see :help i_CTRL-G_u

Best regards,
Tony.

**Comment by sosmo** [comment]
> see :help i_CTRL-G_u

I did actually try entering insert and pressing `<c-g>u` before doing the undo, but it doesn't seem to have an effect... That undo point also gets joined with the start point of the macro

**Comment by tonymec** [comment]
Just u in Insert mode types the letter u. Record the sequence Ctrl-G u in your macro where you want an undo break.

Another possibility, as indicated in that same help paragraph which Bram told you to read, is (in Normal mode)
```vim
:let &undolevels = &undolevels
```

Best regards,
Tony.

**Comment by sosmo** [comment]
Sorry, I meant "ctrl-g u" but markdown turned the `<c-g>` into a tag... Anyway what I meant to say is "ctrl-g u" doesn't seem to work specially here, as it gets joined to the start of the macro too.

Same happened when running `:set undolevels=1000` just before the undo as well. Looks like this behavior currently can't be changed on the user side

**Comment by chrisbra** [comment]
I think you need to use the

    :let &undolevels = &undolevels

in macros. This is also used in a couple of tests, that test the undo behaviour.

**Comment by sosmo** [comment]
> I think you need to use the
> 
> ```
> :let &undolevels = &undolevels
> ```
> 
> in macros. This is also used in a couple of tests, that test the undo behaviour.

Tried it, seems to work similarly. Basically, if in your macro you do one or more undoable changes, then another, undo the last one and do a new change, only the latest change will happen when you re-execute the macro

**Comment by brammool** [comment]
OK, I can understand that when you record a macro and somehow use undo, you expect the same thing to happen when replaying it.
When replaying, it would be possible to set KeyTyped at the right time, so that syncing undo isn't skipped.  But currently there isn't a way to store meta data with recorded keys.
Another way would be to store calling u_sync() as an event, so that it can be done when replaying.  But then it might happen twice, thus it must only be when u_sync() is called because KeyTyped is true.  That requires checking every call to u_sync().  And then the timing might be wrong and the call to u_sync() happens at the wrong moment.
Thus this will be hard to get right.

**Comment by sosmo** [comment]
Alright. I don't know much about the internals, but if you call u_sync as an event, could duplicates be detected by checking which call comes from inside the macro and which doesn't?

Anyway, it would still be great seeing this hang around as an open issue to be fixed in the future. I'm sure other people sometimes run into this too - in fact this is where I first realized what was going on: https://www.hillelwayne.com/post/vim-macro-trickz/#undoing-mistakes

>If you’re recording a macro and make a mistake, don’t start over. Instead, undo it and keep going normally. Once you’re finished with the macro, press "qp to paste it to an empty line, remove the mistaken keystrokes and the undo, and copy it back in with "qy$. Since macros are just keystrokes in a register, this is sufficient the fix whatever you broke.

>Warning: Don’t leave undos in your macro. If you undo in a macro to correct a mistake, always be sure to manually remove the mistake and the undo from the macro. In replay mode, an undo will undo the entire macro up until that point, erasing all of your hard work and bleeding the macro out into the rest of your text.

Thanks.
