### ISSUE TITLE
`set shortmess` in vimrc not respected (macOS)

### ISSUE THREAD

**Issue by qbedard** [vim/vim#6085]
**Description**
Adding `set shortmess=a` to your vimrc, regardless of value, is not respected on macOS.

**To Reproduce**
1. Create the following minimal vimrc:
    ```vim
    set shortmess=a
     ```
2. `vim -u <above vimrc>`
3. `:set shortmess` displays `shortmess=filnxtToOF`

**Expected behavior**
`shortmess` uses what was set in vimrc.

**Environment (please complete the following information):**
 - Vim version: 8.1 (stock macOS), 8.2 (Homebrew at HEAD)
 - OS: macOS Catalina 10.15.4
 - Terminal: Kitty

**Notes**
- I have tested this on Ubuntu via Docker as well, and the issue is notably _not_ present there.
- The issue is also present in Neovim, for what it's worth.

**Comment by tonymec** [comment]
Is this macVim or plain Vim with no GUI capability? And which patchlevel? (as can be seen on the `:intro` screen or near the top of the `:version` output) — FWIW, as of this writing the latest version is 8.2.754.

Best regards,
Tony.

**Comment by chrisbra** [comment]
Please also show the output of  `:scriptnames` and `:verbose set shortmess?`

**Comment by qbedard** [comment]
`:scriptnames` help me identify that I had a plugin futzing with it that was getting sourced after the vimrc even when using `-u`. Should have used `--noplugin`. 😆

Thanks for the quick responses, y'all.
