### ISSUE TITLE
cpp.vim : line   15: E108: No such variable: "b:current_syntax

### ISSUE THREAD

**Issue by raJeev-M** [vim/vim#6086]
**Describe the bug**
E108: No such variable: "b:current_syntax"

**To Reproduce**
Download cpp.vim, put it inside any folder and source it from vimrc file
`source /usr/share/vim/vim80/syntax/cpp.vim`

open any file from command line:  vi test
Error detected while processing /usr/share/vim/vim80/syntax/cpp.vim:
line   15:
E108: No such variable: "b:current_syntax"
Press ENTER or type command to continue

**Environment (please complete the following information):**

Vim version 8.0.1453

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

**Comment by chrisbra** [comment]
that is not how you should use this syntax file. Why are you sourcing it from your .vimrc?

**Comment by raJeev-M** [comment]
> that is not how you should use this syntax file. Why are you sourcing it from your .vimrc?

So, if we source it from .vimrc , should it throw error?

**Comment by k-takata** [comment]
Syntax files are expected to be loaded indirectly and automatically.
Sourcing them from .vimrc is not expected.

**Comment by raJeev-M** [comment]
> Syntax files are expected to be loaded indirectly and automatically.
> Sourcing them from .vimrc is not expected.

Fine, I commented it out. Now opening a test file and here is the result

"test.hpp" 5L, 89C
Error detected while processing /usr/share/vim/vim80/syntax/cpp.vim:
line   15:
E108: No such variable: "b:current_syntax"

**Comment by jottkaerr** [comment]
Does the file /usr/share/vim/vim80/syntax/c.vim exist? It should have been sourced immediately before the `unlet` statement in line 14. After sourceing that file the variable `b:current_syntax` should exist.

**Comment by jottkaerr** [comment]
Or is there any other syntax/c.vim file which already `unlet`s the `b:current_syntax` variable.

**Comment by raJeev-M** [comment]
> Does the file /usr/share/vim/vim80/syntax/c.vim exist? It should have been sourced immediately before the `unlet` statement in line 14. After sourceing that file the variable `b:current_syntax` should exist.

Thank you, I forgot to `scp` c.vim to my other machine that's the problem.

**Comment by raJeev-M** [comment]
User installation error.

**Comment by chrisbra** [comment]
Yes, make sure to always copy the $VIMRUNTIME directory when installing your main vim binary around.
