### ISSUE TITLE
input(...) runs twice in vim9script

### ISSUE THREAD

**Issue by alexaschee** [vim/vim#6090]
**Describe the bug**
Function `input` when used in a assignment, runs twice: the first runs at the top of the script. Anything to do with `let` ?

**To Reproduce**

    vim9script
    echo "\n:: This should be first..."
    let x = input(":: Second?  ", '')
    " input(":: Second?  ", '')
    echo "\n:: Third"

**Environment**
 - Vim version [8.2.752]
 - OS: [Windows 10, Windows 7]

**Comment by brammool** [comment]
This is already fixed, please sync to head.
Your script now gives the error "E1091: type missing for x = input(":: Second?  ", '')".
When you add the type "let x: string = input()" then it works.
