### ISSUE TITLE
Vim.exe recognizes <c-h> as <c-bs> in Windows Terminal

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#6099]
**Describe the bug**

`<c-h>` can't work in [Windows Terminal](https://github.com/microsoft/terminal/).  

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean` (or `gvim --clean`, etc.) in Windows Terminal
2. Type 'iaaaaa' to enter insert mode, and input some character, 
3. Type '`<c-h><c-h><c-h>` '
4. The previous 'aaaa' can't get deleted, but `<c-h>` appends a `Îz` (like `<c-bs>`).

**Expected behavior**
Works exactly like `<c-h>`

**Screenshots**
![图片](https://user-images.githubusercontent.com/3035071/82169314-acb15880-98f3-11ea-9210-a603d642a8cc.png)

The key codes of `<c-h>` (or "Îz") are "206, 122" (same as `<c-bs>` in vim.exe), so a work-around can be:

```VimL
exec "set <c-h>=\xce\x7a"
```

**Environment (please complete the following information):**
 - Vim version 8.2.701
 - OS: Windows 10 1809
 - Terminal: [Windows Terminal](https://github.com/microsoft/terminal/)

**Additional context**

**Comment by k-takata** [comment]
Isn't it an issue of Windows Terminal?

**Comment by skywind3000** [comment]
Exactly, it is caused by Windows Terminal. And I have created an issue for them.

Maybe we can make vim compatible with Windows Terminal if they forget fix this ?

It is harmless to change the key code for `c-h` in vim.exe:

```VimL
exec "set <c-h>=\xce\x7a"
```

Works in both cmd.exe and Windows Terminal. Maybe we can make it default ??

**Comment by skywind3000** [comment]
it can't be reproduced in the latest vim.exe
