### ISSUE TITLE
Opening two popup terminals may cause error in BufFilePre/Post autocommand

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6101]
**Describe the bug**

Opening two popup terminals may raise `E16` in a `BufFilePre` or `BufFilePost` autocommand.

**To Reproduce**

Start Vim with this shell command:

    vim -Nu NONE +'call term_start(&shell, #{hidden: 1})->popup_create({})|au BufFilePre * call reltime()'

Press `C-\ C-n` to switch back to Terminal-Normal mode, and run this Ex command:

    :call term_start(':', #{hidden: 1})

`E16` is raised:

    Error detected while processing BufFilePre Autocommands for "*":
    E16: Invalid range: call reltime()

**Expected behavior**

No error is raised.

**Screenshots**

![gif](https://user-images.githubusercontent.com/8505073/82211201-c7de9100-9910-11ea-93e0-35fbc0997729.gif)

**Environment**

 - Vim version: 8.2 Included patches: 1-788
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

The same issue applies to `BufFilePost`.

---

It looks similar to #5682.

**Comment by brammool** [comment]
What is your intention - starting a terminal while already in a terminal?
Where would that new terminal appear?  Can't have two terminal popups, they would be fighting over user input.
The error message is weird, does some autocommand intercept this?

**Comment by lacygoill** [comment]
> What is your intention - starting a terminal while already in a terminal?

I sometimes open a popup terminal to run an interactive shell.  I also use the fzf plugin which may open its own popup terminal.  That's why sometimes, I have 2 popup terminals.

> Where would that new terminal appear?

The fzf popup appears right above my popup.

> Can't have two terminal popups, they would be fighting over user input.

On my machine, when the fzf plugin opens its popup over my own popup, it gets the input.  Once I close the fzf popup, my popup gets back the input.

FWIW, I think that opening 2 popup terminals should be disallowed.  It creates too many issues.  I have probably yet another one to report.  But it is allowed, so if I find an issue, I report it.

> The error message is weird, does some autocommand intercept this?

Yes, this autocmd:

    au BufFilePre * call reltime()

But the error doesn't make sense, because `:call` is not prefixed by a range.

**Comment by lacygoill** [comment]
Here's an example of 2 popup terminals:

    vim -Nu NONE -S <(cat <<'EOF'
      nno <silent> <c-a> :call term_start(&shell, #{hidden: 1, term_finish: 'close'})->popup_create({'border': []})<cr>
      nno <silent> <c-b> :call term_start([&shell, &shellcmdflag, 'cat'], #{hidden: 1, term_finish: 'close'})->popup_create(#{line: 9, col: 1, border: []})<cr>
    EOF
    )

![gif](https://user-images.githubusercontent.com/8505073/82226335-ab4d5380-9926-11ea-96b4-889d0b6a3e4b.gif)

They don't compete for the input; the input gets to the one which is focused at any given time.
When you create a second popup, the focus switches to the latter, and it gets the input.
When you close it, the focus switches back to the first popup, and the latter gets back the input as well.

**Comment by brammool** [comment]
> Here's an example of 2 popup terminals:
> 
>     vim -Nu NONE -S <(cat <<'EOF'
>       nno <silent> <c-a> :call term_start(&shell, #{hidden: 1, term_finish: 'close'})->popup_create({'border': []})<cr>
>       nno <silent> <c-b> :call term_start([&shell, &shellcmdflag, 'cat'], #{hidden: 1, term_finish: 'close'})->popup_create(#{line: 9, col: 1, border: []})<cr>
>     EOF
>     )
> 
> ![gif](https://user-images.githubusercontent.com/8505073/82226335-ab4d5380-9926-11ea-96b4-889d0b6a3e4b.gif)
> 
> They don't compete for the input; the input gets to the one which is
> focused at any given time.
> When you create a second popup, the focus switches to the latter, and
> it gets the input.  When you close it, the focus switches back to the
> first popup, and the latter gets back the input as well.

For me it creates a mess.  Using CTRL-A opens the first one, but then
how do you open the second one?  I tried using CTRL-W N  to go to
Terminal-Normal mode, then CTRL-B gives an error message similar to the
one you reported.  It does open a second popup.  Trying to close them
leaves the edited file in the popup, weird.

-- 
hundred-and-one symptoms of being an internet addict:
129. You cancel your newspaper subscription.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
> > What is your intention - starting a terminal while already in a terminal?
> 
> I sometimes open a popup terminal to run an interactive shell.  I also
> use the fzf plugin which may open its own popup terminal.  That's why
> sometimes, I have 2 popup terminals.

Well, that is what I wanted to avoid: using Vim as a display manager to
run a shell in a separate window.  That wasn't really intended.  I
already find it a border case to run a shell in a window, but as I
mentioned when adding this feature, there are valid reasons.  Personally
I use the debugger quite a lot.  And the screen shot tests work well.
But for a shell I open a new xterm.

I know i've been trying to stay strict with how popups can be used.  We
can relax the rules when there is a uses case that justifies it.  But
allowing any kind of use opens it up for all kinds of things that 1)
are not really the job of a text editor, and 2) will increase the number
of ways things can fail.  Well, I suppose we have quite a bit of 2)
already.
 
> > Where would that new terminal appear?
> 
> The fzf popup appears right above my popup.
> 
> > Can't have two terminal popups, they would be fighting over user input.
> 
> On my machine, when the fzf plugin opens its own popup over my own
> popup, it gets the input.  Once I close the fzf popup, my popup gets
> back the input.
> 
> FWIW, I think that opening 2 popup terminals should be disallowed.  It
> creates too many issues.  I have probably yet another one to report.
> But it is possible, so if I find an issue, I report it.
> 
> > The error message is weird, does some autocommand intercept this?
> 
> Yes, this autocmd:
> 
>     au BufFilePre * call reltime()
> 
> But the error doesn't make sense, because `:call` is not prefixed by a
> range.

True.  Is there a way to reproduce this without a plugin?

-- 
hundred-and-one symptoms of being an internet addict:
128. You can access the Net -- via your portable and cellular phone.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> For me it creates a mess.  Using CTRL-A opens the first one, but then
> how do you open the second one?  I tried using CTRL-W N  to go to
> Terminal-Normal mode, then CTRL-B gives an error message similar to the
> one you reported.  It does open a second popup.  Trying to close them
> leaves the edited file in the popup, weird.

The way I open the second one is similar to what you did; I press `C-\ C-n` then `C-b`.  But `C-w N` then `C-b` works too.  Yes, it's true that it creates a mess; in fact, this mess is the first bug which I found, and for which I've just opened another report (#6103).  While trying to understand it, I've found the current bug which is related to the `BufFilePre` autocmd.

> Well, that is what I wanted to avoid: using Vim as a display manager to
> run a shell in a separate window.  That wasn't really intended.  I
> already find it a border case to run a shell in a window, but as I
> mentioned when adding this feature, there are valid reasons.  Personally
> I use the debugger quite a lot.  And the screen shot tests work well.
> But for a shell I open a new xterm.

I wouldn't mind if you disallowed an interactive shell in a popup terminal, but other people may like the concept, and already use it.  I know one plugin which provides it for its users: [vim-floaterm](https://github.com/voldikss/vim-floaterm).

> Is there a way to reproduce this without a plugin?

Not sure to understand, but the current issue, which is about the unexpected `E16` error triggered by a `BufFilePre` autocmd, is reproducible with the 2 commands mentioned in the OP:

    $ vim -Nu NONE +'call term_start(&shell, #{hidden: 1})->popup_create({})|au BufFilePre * call reltime()'
    " press:  C-\ C-n
    :call term_start(':', #{hidden: 1})

They don't rely on any third-party plugin, nor on any custom configuration.
If something is wrong in the code, or if I misunderstood something, let me know, and I'll try to provide another example.

I wanted to simplify the code in a single script (without any user interaction), but I failed; I don't know how to make Vim enter Terminal-Normal mode from the script; I tried `feedkeys()` and `term_sendkeys()` without success.
