### ISSUE TITLE
How to remove the tip when open a terminal in Vim8.2

### ISSUE THREAD

**Issue by gVimer** [vim/vim#6109]
I hate the tip and want to remove it.but i do not know how to do
![QQ截图20200520071944](https://user-images.githubusercontent.com/6241431/82387817-98dc3280-9a6a-11ea-8f3c-670a14e35730.png)

**Comment by chrisbra** [comment]
What do you mean with tip?

**Comment by gVimer** [comment]
in the cmdline  like: XXXXXXX lines --25%-- 
the tip is unuseful

**Comment by k-takata** [comment]
Haven't you set the 'statusline' option that way?

**Comment by chrisbra** [comment]
I believe you need to configure your statuslineline configured to not show this. Closing, as this is a user question. 
Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here.
