### ISSUE TITLE
Does MacVim build against a custom Python Framework?

### ISSUE THREAD

**Issue by symbolix** [vim/vim#611]
Hi,

I would like to check if there is an update regarding this issue. When I tried to compile MacVim from source, against my own Python, some time ago, I was not able to do so due to a problem in one of the make files. So I had to compiled against the default system Python.

Here is my original question:

[MacVim does not build against a custom Python Framework](http://stackoverflow.com/questions/23817871/macvim-does-not-build-against-a-custom-python-framework)

Will MacVim compile against a custom Python Framework provided that the correct compiler flags are supplied?

No homebrew. No macports.

Thanks.

**Comment by chrisbra** [comment]
macvim is this way https://github.com/macvim-dev/macvim

**Comment by symbolix** [comment]
Sure. How did that happen?! Sorry.
