### ISSUE TITLE
<m-K> and <m-J> mappings stopped working in 8.2.801 (ALT+SHIFT mappings)

### ISSUE THREAD

**Issue by Praful** [vim/vim#6110]
**Brief description**
In the current version of `gvim.exe` (but _not_ `vim.exe`) on Windows, my mappings for `<m-J>` and `<m-K>` have stopped working.

**To reproduce**

1. Run `gvim --clean`
2. Add mappings:
```
nnoremap <silent> <m-J> mzyyp`zj
nnoremap <silent> <m-K> mzyyp`z
```
3. Put cursor on a line of text and press `<ALT><SHIFT>j` or `<ALT><SHIFT>k`.
4. Nothing happens.

**Expected behaviour**
The current line should be copied above or below. You can map the keys to something else. The issue seems to be mapping the `<ALT>+<SHIFT>` combination. This worked in previous versions of `gvim.exe` (up to 8.2.637). I have not tried versions between 637 and 801.

**Environment**
 - Vim version: 8.2.801
 - OS: Windows 10 1809
 - Terminal: GUI

**Additional context**
This continues to work in `vim.exe`. Mappings for `<m-j>` and `<m-k>` (lowercase j and k) continue to work also in both `gvim.exe` and `vim.exe`.

**Comment by rcraioveanu** [comment]
I am experiencing this same issue on Arch Linux, after upgrading from 8.2.0717 to 8.2.0814. It is specifically mappings with Alt+Shift that no longer work; other mappings with Alt are unaffected. Downgrading back to 717 resolves this issue.

**Comment by chrisbra** [comment]
please give some more information. Terminal or gui?

**Comment by chrisbra** [comment]
Note the initial bug report was for Windows, since you are using Linux, please mention specifically, what terminal or gui you are using. Also helpful might be to bisect the offending commit (and try with the latest version)

**Comment by rcraioveanu** [comment]
Apologies, this was in the GTK3 GUI version. I tried to test it in terminal for comparison, but all of my terminal emulators read Alt-keystroke combinations as Esc, and I didn't have a lot of time to mess around with things. 

Cool, I didn't know about bisect! I'll try it out and report back.

**Comment by brammool** [comment]
I'm not sure this is a real bug.  If you map a key with ALT and SHIFT, you need to use <M-S-k>.
Isn't it a bit strange to specify one modifier but not the other?
I wonder if <M-K> worked everywhere before or just in some environments.

**Comment by lacygoill** [comment]
Yes, that's what I wrote in [my notes](https://github.com/lacygoill/wiki/blob/master/vim/terminal.md#in-xterm-vim-doesnt-make-the-difference-between-m-g-and-m-g), i.e. the shift modifier must be explicit.  Maybe it could be implicit in the past, I don't know.

In any case, try to replace these mappings:

    nnoremap <silent> <m-J> mzyyp`zj
    nnoremap <silent> <m-K> mzyyp`z

With:

                         vv
    nnoremap <silent> <m-s-j> mzyyp`zj
    nnoremap <silent> <m-s-k> mzyyp`z
                         ^^

**Comment by chrisbra** [comment]
closing then.

**Comment by Praful** [comment]
Thanks - explicitly including SHIFT works fine.
