### ISSUE TITLE
Cannot change <Tab> mapping without changing <Ctrl-i>

### ISSUE THREAD

**Issue by sheerun** [vim/vim#6113]
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Describe the bug**

I cannot set mapping for `<Tab>` without changing `<Ctrl-i>` mapping.

**To Reproduce**

```
:nnoremap <TAB> >>
```

Then press `<Tab>` (ok), and then press `<Ctrl-i>` (not ok).

**Expected behavior**

`<Ctrl-i>` mapping should be not affected (it should go to previous location)

**Environment (please complete the following information):**
 - Vim version: 8.2
 - OS: MacOS 10.15.4
 - Terminal: iTerm2

**Comment by sosmo** [comment]
`<c-i>` in a terminal emulator means a tab, so Vim can't tell them apart. Graphical Vim theoretically could, but currently it doesn't have support for that either over its terminal counterpart

**Comment by sheerun** [comment]
eh, this is why we can't have nice things :(

**Comment by tonymec** [comment]
Maybe `:help modifyOtherKeys` might help you (or maybe not).

Best regards,
Tony.

**Comment by sheerun** [comment]
I'm using MacOS so I don't have access to xterm. iTerm2 author wants to implement it but there's not enough documentation how: https://gitlab.com/gnachman/iterm2/-/issues/8382
