### ISSUE TITLE
"recording @q" is not disappearing after recording ended

### ISSUE THREAD

**Issue by sheerun** [vim/vim#6114]
This is very confusing as it suggests that recording still happens

**To Reproduce**

Start recording macro with `qq`, then do something, then end recording macro with `q`

The "recording @q" is still visible on the screen

**Expected behavior**

Vim clears "recording @q" message after recording has ended

**Environment (please complete the following information):**
 - Vim version: 8.2
 - OS: MacOS 10.15.4
 - Terminal: iTerm2

**Comment by chrisbra** [comment]
What exact version? Did you try other tetminals/the gui? Is this a regression?

**Comment by sheerun** [comment]
It turns out it was because of `map q: :q` in some plugin

Sorry for the trouble, I hope this issue will help someone with similar issue in the future
