### ISSUE TITLE
"mapset()" doesn't translate special key codes

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6116]
**Describe the bug**

`mapset()` doesn't translate special key codes.

**To Reproduce**

Write this in `/tmp/t.vim`:

    nno K :echom 'original mapping'<cr>
    let save_map = maparg('K', 'n', 0, 1)
    nunmap K
    call mapset('n', 0, save_map)
    call feedkeys('K')

Start Vim with this shell command:

    vim -Nu NONE -S /tmp/t.vim

The command-line is populated with:

    echom 'original mapping'<cr>

Notice that `<cr>` has not been translated into a literal carriage return.

**Expected behavior**

When `K` is pressed, the Ex command `:echom 'original mapping'` is executed, just like it would have been before the mapping was removed by `:nunmap`.

**Environment**

 - Vim version: 8.2 Included patches: 1-807
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

It's as if `'cpo'` included the `<` flag which disables the recognition of special key codes.
However, that's not the issue here; `'cpo'` does not contain this flag when started with `-Nu NONE` (`-N` resets `'compatible'` which resets `'cpo'` to `aABceFs`).

**Comment by lacygoill** [comment]
Not sure whether this is the same issue, or I should open a new one, but the pseudo-key `<sid>` is not translated either:

    vim -Nu NONE -S <(cat <<'EOF'
        nno <expr> K <sid>func()
        fu s:func()
            return 'aaa'
        endfu
        let save_map = maparg('K', 'n', 0, 1)
        nunmap K
        call mapset('n', 0, save_map)
        call feedkeys('K')
    EOF
    )
    " result: E120: Using <SID> not in a script context: <sid>func
    " expected: 'aa' is inserted

**Comment by brammool** [comment]
> Not sure whether this is the same issue, or I should open a new one, but the pseudo-key `<sid>` is not translated either:
> 
>     vim -Nu NONE -S <(cat <<'EOF'
>         nno <expr> K <sid>func()
>         fu s:func()
>             return 'aaa'
>         endfu
>         let save_map = maparg('K', 'n', 0, 1)
>         nunmap K
>         call mapset('K', 0, save_map)
>     EOF
>     )
>     " press 'K'
>     " result: E120: Using <SID> not in a script context: <sid>func
>     " expected: 'aa' is inserted

This should work after patch 8.2.0812.  The first argument to mapset()
should be "n" though.

-- 
If you feel lonely, try schizophrenia.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
