### ISSUE TITLE
"maparg()" does not support the "!" mode

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6118]
**Describe the bug**

You can't pass the pseudo-mode `!` to `maparg()`.

**To Reproduce**

Run this shell command:

    vim -Nu NONE +'noremap! <c-a> <c-b>'

Run this Ex command:

    :echo maparg('<c-a>', '!', 0, 1)

The output is an empty dictionary.

**Expected behavior**

The output is this dictionary:

    {'lnum': 0, 'script': 0, 'simplified': 1, 'silent': 0, 'noremap': 1, 'lhs': '<C-A>', 'mode': '!', 'nowait': 0, 'expr': 0, 'sid': -3, 'rhs': '<c-b>', 'buffer': 0}

**Environment**

 - Vim version: 8.2 Included patches: 1-812
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

I think it's an omission because when reading `:h maparg()`, one can see that `{mode}` can be any mode used in a mapping command:

    {mode} can be one of these strings:
            "n"	Normal
            "v"	Visual (including Select)
            "o"	Operator-pending
            "i"	Insert
            "c"	Cmd-line
            "s"	Select
            "x"	Visual
            "l"	langmap |language-mapping|
            "t"	Terminal-Job
            ""	Normal, Visual and Operator-pending

- `n` = `:nmap`
- `v` = `:vmap`
- `o` = `:omap`
- `i` = `:imap`
- `c` = `:cmap`
- `s` = `:smap`
- `x` = `:xmap`
- `l` = `:lmap`
- `t` = `:tmap`
- `''` = `:map`

For each mapping command, there is a corresponding flag which can be passed as a second argument to `maparg()`.  Except for the `:map!` command; there is no corresponding `!` flag which could be passed to `maparg()`.

---

Because of this, you can't use `mapset()` to restore a mapping installed via `:map!`.

    vim -Nu NONE -S <(cat <<'EOF'
        noremap! X Y
        let save_map = maparg('X', '!', 0, 1)
        unmap! X
        call mapset('!', 0, 1)
        call feedkeys('iX')
    EOF
    )
    # result:   'X' is inserted
    # expected: 'Y' is inserted

That's because the first `{mode}` argument of `mapset()` is the same as for `maparg()`:

> {mode} and {abbr} should be the same as for the call to |maparg()|.

So, since `!` can't be used for `maparg()`, it can't be used for `mapset()` either.

**Comment by brammool** [comment]
> **Describe the bug**
> 
> You can't pass the pseudo-mode `!` to `maparg()`.
> 
> **To Reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE +'noremap! <c-a> <c-b>'
> 
> Run this Ex command:
> 
>     :echo maparg('<c-a>', '!', 0, 1)
> 
> The output is an empty dictionary.
> 
> **Expected behavior**
> 
> The output is this dictionary:
> 
>     {'lnum': 0, 'script': 0, 'simplified': 1, 'silent': 0, 'noremap': 1, 'lhs': '<C-A>', 'mode': '!', 'nowait': 0, 'expr': 0, 'sid': -3, 'rhs': '<c-b>', 'buffer': 0}
> 
> **Environment**
> 
>  - Vim version: 8.2 Included patches: 1-812
>  - OS: Ubuntu 16.04.6 LTS
>  - Terminal: XTerm(322)
> 
> **Additional context**
> 
> I think it's an omission because when reading `:h maparg()`, one can see that `{mode}` can be any mode used in a mapping command:
> 
>     {mode} can be one of these strings:
>             "n"	Normal
>             "v"	Visual (including Select)
>             "o"	Operator-pending
>             "i"	Insert
>             "c"	Cmd-line
>             "s"	Select
>             "x"	Visual
>             "l"	langmap |language-mapping|
>             "t"	Terminal-Job
>             ""	Normal, Visual and Operator-pending
> 
> - `n` = `:nmap`
> - `v` = `:vmap`
> - `o` = `:omap`
> - `i` = `:imap`
> - `c` = `:cmap`
> - `s` = `:smap`
> - `x` = `:xmap`
> - `l` = `:lmap`
> - `t` = `:tmap`
> - `''` = `:map`
> 
> For each mapping command, there is a corresponding flag which can be
> passed as a second argument to `maparg()`.  Except for the `:map!`
> command; there is no corresponding `!` flag which could be passed to
> `maparg()`.

The "!" addition would work like "ic".  However, the mapping can differ
between "i" and "c", then Vim doesn't know what to return.
It does work the other way around: If you ask for mode "i" you can get
back the info for a mapping that's defined like with :map!.


-- 
hundred-and-one symptoms of being an internet addict:
167. You have more than 200 websites bookmarked.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> The "!" addition would work like "ic".  However, the mapping can differ
> between "i" and "c", then Vim doesn't know what to return.

Sorry but I don't understand.  How could the mapping be different between `i` and `c`?  `:map!` can't install different mappings (i.e. one for `i` and another for `c`), can it?

It seems to me that `"!"` is similar to `""`.  They don't stand for real modes, but for sets of modes.  If `maparg()` is currently able to handle `""`, couldn't it handle `"!"` in a similar way?

**Comment by brammool** [comment]
> > The "!" addition would work like "ic".  However, the mapping can differ
> > between "i" and "c", then Vim doesn't know what to return.
> 
> Sorry but I don't understand.  How could the mapping be different
> between `i` and `c`?  `:map!` can't install different mappings (i.e.
> one for `i` and another for `c`), can it?

	map! <F2> xxx
	cmap <F2> yyy
	map! <F2>

> It seems to me that `"!"` is similar to `""`.  They don't stand for
> real modes, but for sets of modes.  If `maparg()` is currently able to
> handle `""`, couldn't it handle `"!"` in a similar way?

Then maparg() would need to return a list of dictionaries for all
matching modes.  That's getting complicated.

Let me first figure out how to deal with the simplified/not-simplified
variants.  I also think we want to have a literal code next to the human
readable "lhs" entry.

-- 
"Hit any key to continue" is very confusing when you have two keyboards.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
Closing in favor of PR #10295
