### ISSUE TITLE
7.4.1201 building will bomb out immediately on OS X

### ISSUE THREAD

**Issue by chdiza** [vim/vim#612]
7.4.1199, however, works fine.  This is what I see after `make` on OS X 10.11.3:

```
gcc -DMACOS_X_UNIX -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -L/usr/local/lib -DUNIX -o xxd xxd.c
In file included from os_mac_conv.c:19:
In file included from ./vim.h:1984:
In file included from ./proto.h:288:
proto/os_mac_conv.pro:2:27: error: expected ';' after top level declarator
char_u *mac_string_convert __ARGS((char_u *ptr, int len, int *lenp, int ...
                          ^
                          ;
```

**Comment by chdiza** [comment]
7.4.1200 is the first patch to introduce this.

**Comment by brammool** [comment]
chdiza wrote:

> 7.4.1199, however, works fine.  This is what I see after `make` on OS
> X 10.11.3:
> 
> ```
> gcc -DMACOS_X_UNIX -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -L/usr/local/lib -DUNIX -o xxd xxd.c
> In file included from os_mac_conv.c:19:
> In file included from ./vim.h:1984:
> In file included from ./proto.h:288:
> proto/os_mac_conv.pro:2:27: error: expected ';' after top level declarator
> char_u *mac_string_convert __ARGS((char_u *ptr, int len, int *lenp, int ...
>                           ^
>                           ;
> ```

Missed the proto file in the change.  Also, it doesn't generate with
cproto.

## 

hundred-and-one symptoms of being an internet addict:
82. AT&T names you Customer of the Month for the third consecutive time.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///
