### ISSUE TITLE
mouse or keyboard inserts strange ANSI code when a second pane is present(Plug or Nerdtree) under gnome-terminal but not xterm

### ISSUE THREAD

**Issue by laoshaw** [vim/vim#6122]
**Describe the bug**

after `set mouse=a` in gnome-terminal and lxterminal,  I saw lots of strange strings in the format of a square box with 001B inside, followed by `>4;2m`, see below screenshot:

![image](https://user-images.githubusercontent.com/18351761/82720983-6c98ff80-9c7e-11ea-97a7-63c579bcccbb.png)

If I use xterm I did not see them at all.

**To Reproduce**

1. run vim8.1 or vim8.2 with Plug in a $HOME/.vimrc with no packages installed on ubuntu 18.04
2. cat /tmp/.vimrc
```
runtime! debian.vim

if has("syntax")
  syntax on
endif

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
call plug#end()

set mouse=a
```
3. vim -u /tmp/.vimrc myfile.txt
4. inside vim, do: PlugClean, the goal is to open a second pane, choose N to do nothing but keep the pane on.
5. C-WW to myfile.txt and hit i to enter insert mode, type something
6. I immediate saw the strange string, it will disappear after refresh.
7. I can use mouse click inside the file to get the same strange string too.
8. Note without the Plug pane(or nerdtree pane if installed), everything works.
9. on xterm even with Plug and nerdtree pane everything still works.
10: normal screen split(vsp, sp) works fine
11. terminal pane works fine. so the issue is related with special pane from Plug or nerdtree.

**Expected behavior**

No strange string should be shown

**Environment (please complete the following information):**
 - Vim version : 8.1-2424(self build with --huge) and 8.2.0803(ubuntu newest)
 - OS:ubuntu 18.04
 - Terminal: gnome-terminal, lxterminal. Note, xterm is fine.

**Additional context**

**Comment by brammool** [comment]
If you use gnome-terminal, make sure $TERM is set to gnome-terminal.  If you set $TERM to something starting with "xterm" you will have the wrong terminal setup.

**Comment by laoshaw** [comment]
This is not the case actually, gnome-terminal on ubuntu 18.04 is default to xterm-256color and gnome-terminal is an invalid option. I did try  set TERM to *xterm* and same issue exists. 

in short, mouse does not work in gnome-terminal/lxterminal vim8.x when it's set to nvi or a. from the strange string it seems having something to do with GUI? but I'm not doing anything with gtk/gvim.

**Comment by dpelle** [comment]
There are at least 2 other related issues affecting at least Ubuntu-18.04 and slackware 14.2 (probably other distributions too) after patch vim-8.2.0767:

- #6111 (that one even affects xterm, so not just gnome-terminal or xfce4-terminal, reporter uses Slackware 14.2)
- #6112

I can reproduce all of them on xubuntu-18.04.

**Comment by laoshaw** [comment]
I started seeing issues on xterm this morning indeed. plus xterm does not do utf-8 so I come back to gnome-terminal.

Tried to downgrade to 8.1.2424(newest 8.1) and the problem persists.

**Comment by dpelle** [comment]
Upgrading to Ubuntu-20.04 will hopefully fix this kind of issues.
In the mean time, putting these lines in your `~/.vimrc` should avoid the issues:
```
" Avoid issues after vim-8.2.0767 with terminals presumably too old
" to handle t_TI and t_TE. See:
" - https://github.com/vim/vim/issues/6111
" - https://github.com/vim/vim/issues/6112
" - https://github.com/vim/vim/issues/6122
set t_TI= t_TE=
```

**Comment by laoshaw** [comment]
A quick testing showed this fix did help. Thanks!!!
