### ISSUE TITLE
'0 more files to edit' with arglocal

### ISSUE THREAD

**Issue by HarmtH** [vim/vim#6133]
**Describe the bug**
Vim shows error 'E173: 0 more files to edit' when trying to quit

**To Reproduce**
Detailed steps to reproduce the behavior:
```
vim --clean<cr>
:argl foo bar<cr>
:n<cr>
:q<cr>
```

**Current behaviour**
```E173: 0 more files to edit```

**Expected behaviour**
Vim exits

**Environment (please complete the following information):**
 - Vim version: 8.2.814

**Comment by chrisbra** [comment]
seems no longer reproducible, closing.
