### ISSUE TITLE
global/veto handling of backslashes in multi-line commands

### ISSUE THREAD

**Issue by konrad-schwarz** [vim/vim#6135]
## Description
The command(s) executed by the `global`/`veto` ex command
can be multi-line commands, e.g., `append`, `change`, or `insert`.  The newlines
in these multi-line commands are escaped by backslashes, but the
newlines themselves must remain in the `global` command list
to allow for appending/changing/inserting
multiple lines per match of the `global` command.

For example, if, in a C program, you wanted to insert an empty line before each
*enum* declaration, you would write (in ed or in traditional ex):
```
:g/enum/i\
\
.
```

That is, the backslashes -- *but not the newlines protected by those backslashes* --
are to be swallowed by `global` parsing.

However, what vim does (at least in ex mode as entered by visual-mode `Q`)
is to insert nothing, presumably because both the backslash *and* the newline
have been swallowed, leaving the `insert` command with nothing
(i.e., the empty string) to insert,

POSIX [says](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/ex.html#tag_20_40_13_20)
> For the `append`, `change`, and `insert` commands, the input text shall be included as part of the command, and the terminating `<period>` can be omitted if the command ends the list of commands.

It also says that multiple commands can be separated by `<vertical-line>` or by `<backslash>` escaped newlines.

The POSIX [ed man](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/ed.html#tag_20_38_13_10) page makes this clearer:
> A single command or the first of a list of commands shall appear on the same line as the `global` command. All lines of a multi-line list except the last line shall be ended with a backslash preceding the terminating `<newline>`; the `a`, `i`, and `c` commands and associated input are permitted. The '`.`' terminating input mode can be omitted if it would be the last line of the command list.

## To Reproduce
1. Run `vim --clean`
2. Edit `example`
3. Type `aenum^[Qg/enum/i\^M\^M.`, where `^[` is ASCII `ESC` (escape)
and `^M` is ASCII `CR` (carriage return),
backslashes exactly as specified (i.e., literally).
Or in ex mode, entered via `Q`:
```
:a
enum
.
:g/enum/i\
\
.
:%p
```
4. There should be an empty line in front of the line containing *enum*.

## Expected behavior
Multi-line `append`, `change`, and `insert` ex commands should be possible in ex `global` commands, at least in ex mode as entered via the visual `Q` command.:

## Environment:
 - Vim version: 8.2 (2019 Dec 12)
 - OS: Fedora 31
 - Terminal: urxvt

**Comment by mohd-akram** [comment]
I came across a similar issue (#7244). I posted a patch there which seems to resolve this as well.
