### ISSUE TITLE
Line number not updated in diff mode

### ISSUE THREAD

**Issue by zsugabubus** [vim/vim#6138]
**Describe the bug**
Line number not updated in diff mode.

**To Reproduce**

1. Diff these two files:
```
a
a
a
x
x
x
b
b
b
b
b
```

```
a
a
a
y
b
b
b
b
b
```
2. `set rnu` for the ‘y’ window.
3. Move cursor.
4. Line number immediately after deleted/changed lines in ‘y’ window should stay the same.
5. (`set rnu` again updates it.)

**Expected behavior**
Line number updated.

**Environment (please complete the following information):**
 - Vim version: 8.2
 - OS: Arch Linux
 - Terminal: st

**Comment by chrisbra** [comment]
That was a bit tricky to find. I can you check, if this patch fixes it? Will post a PR with a proper test later than.

```patch
diff --git a/src/drawline.c b/src/drawline.c
index 1c9ecd754..05d6c5397 100644
--- a/src/drawline.c
+++ b/src/drawline.c
@@ -1311,7 +1311,11 @@ win_line(
        {
            screen_line(screen_row, wp->w_wincol, col, -(int)wp->w_width,
                                                            screen_line_flags);
-           if (wp->w_p_wrap && (wp->w_p_nu || wp->w_p_rnu) && HL_ATTR(HLF_CLN) != 0)
+           if ((wp->w_p_wrap && (wp->w_p_nu || wp->w_p_rnu) && HL_ATTR(HLF_CLN) != 0) ||
+#ifdef FEAT_DIFF
+                   (filler_lines && (wp->w_p_nu || wp->w_p_rnu))
+#endif
+              )
            {
                ++row;
                ++screen_row;
```

**Comment by zsugabubus** [comment]
I freshly checked out ~master~ main but I could not apply your patch. (Am I doing something silly?) Manually trying to find the best place, I came up with this: (Not working)
```diff
diff --git a/src/drawline.c b/src/drawline.c
index 9d65aa4..29c5b27 100644
--- a/src/drawline.c
+++ b/src/drawline.c
@@ -2986,6 +2986,9 @@ win_line(
 #endif
                    || (wp->w_p_list && lcs_eol != NUL && p_extra != at_end_st>
                    || (n_extra != 0 && (c_extra != NUL || *p_extra != NUL)))
+#ifdef FEAT_DIFF
+               || (filler_lines && (wp->w_p_nu || wp->w_p_rnu))
+#endif
                )
        {
 #ifdef FEAT_CONCEAL
```

~Line numbers seems to be updated, but unfortunatelly, it messes up highlights for me, and fixing that is surely out of my understanding.~ Nah, sorry. Not working.

**Comment by chrisbra** [comment]
That is the wrong place I believe. I'll send a PR soon, which you can then test.

**Comment by zsugabubus** [comment]
That was the only place I could find `++screen_row`. Searched for other patterns too but they were scattered through the whole function.

**Comment by chrisbra** [comment]
ah, it was indeed based on an older patch of mine. I'll have to re-check, sorry.

**Comment by chrisbra** [comment]
Try this one please:

```patch
diff --git a/src/drawline.c b/src/drawline.c
index 9d65aa43e..9baf4b6e3 100644
--- a/src/drawline.c
+++ b/src/drawline.c
@@ -1293,7 +1293,11 @@ win_line(
                                   && filler_todo <= 0
 #endif
                )
-               || (number_only && draw_state > WL_NR))
+               || (number_only && draw_state > WL_NR
+#ifdef FEAT_DIFF
+                                  && filler_todo <= 0
+#endif
+                  ))
        {
            screen_line(screen_row, wp->w_wincol, col, -(int)wp->w_width,
                                                            screen_line_flags);

```

**Comment by zsugabubus** [comment]
Works great, thanks. (Seems like `&& ...` could be merged by the one above.)

**Comment by chrisbra** [comment]
Thanks, I'll create a test case before submitting a PR to fix this, so it won't regress.
