### ISSUE TITLE
copy() and deepcopy() do not work with special values

### ISSUE THREAD

**Issue by ZyX-I** [vim/vim#614]
Consider the following script:

```
vim -u NONE -i NONE --cmd 'echo copy(v:true)'
```

It will show internal error from item_copy(). Same for `deepcopy()`.

---

Note that to avoid all these internal errors one needed to do one the following:
1. Make v_type enum and not int.
2. _Never_ use `default` cases when working with this enum.

This way you get notification from compiler immediately when you add a new type in all places `switch(…v_type)` is used.

**Comment by brammool** [comment]
Nikolai Pavlov wrote:

> Consider the following script:
> 
> ```
> vim -u NONE -i NONE --cmd 'echo copy(v:true)'
> ```
> 
> It will show internal error from item_copy(). Same for `deepcopy()`.

I'll fix it and add a test.

> Note that to avoid all these internal errors one needed to do one the
> following:
> 1. Make v_type enum and not int.
> 2. _Never_ use `default` cases when working with this enum.
> 
> This way you get notification from compiler immediately when you add a
> new type in all places `switch(…v_type)` is used.

How about a patch?

## 

Momento mori, ergo carpe diem

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///
