### ISSUE TITLE
Vim don't show entire file

### ISSUE THREAD

**Issue by caduguedess** [vim/vim#6142]
For some reason, vim isn't showing the last file of a simple file.
The image shows nano editor in the left and vim editor in right, both opening the same file.
https://i.imgur.com/eQjoapU.png

**Comment by k-takata** [comment]
Isn't that just a colorscheme issue?

**Comment by caduguedess** [comment]
I'm not sure.
This picture shows more hidden words.
https://i.imgur.com/k2il1vI.png

**Comment by caduguedess** [comment]
Sorry, it was really a colorscheme issue.

**Comment by chrisbra** [comment]
I noted that in the past for the powershell. Make sure you configure vim correctly. By default Vim thinks this is only a 16 color capable terminal, however it seems to be capable of RGB colors, e.g. `:set termguicolors` setting.
