### ISSUE TITLE
":set clipboard=unnamed" works incorrectly if the cursor is on a ^@ char

### ISSUE THREAD

**Issue by lkintact** [vim/vim#6149]
**Describe the bug**
gVim doesn't yank to the `"*` register when `'clipboard'` is set to `unnamed` and the cursor is on a `^@` character; the register is removed instead

**To Reproduce**
1. Run `gvim.exe --clean test.txt` (the file: [test.txt](https://github.com/vim/vim/files/4685373/test.txt))
2. Execute `:set clipboard=unnamed`
3. Type <kbd>y</kbd><kbd>y</kbd> to yank the line
4. Execute `:registers`. The `"*` register is absent from the list (even if there was something in it before the yanking)

**Expected behavior**
The `"*` register should be there, filled with `^@test^J`

**Environment**
 - Vim 8.2.825 (https://github.com/vim/vim-win32-installer/releases/download/v8.2.0825/gvim_8.2.0825_x86_signed.zip)
 - OS: Windows 10 Home 1803
 - Terminal: GUI

**Comment by chrisbra** [comment]
I don't know what is going on here. In a plain `gvim --clean file.txt` I see this

![grafik](https://user-images.githubusercontent.com/244927/83734955-f9b16080-a64f-11ea-9e43-b1e6aba7ee59.png)

Loading it using  `gvim --clean -c ':set enc=utf-8'` shows this, without a null byte:

![grafik](https://user-images.githubusercontent.com/244927/83735041-1baae300-a650-11ea-82f2-3f7c5f155cee.png)


In both cases, `:set clipboard=unnamed` does the expected thing after yanking, `:reg` returns:
![grafik](https://user-images.githubusercontent.com/244927/83735110-367d5780-a650-11ea-9170-3e93071f4638.png)
E.g. the content is there. 

Note notepad and notepad++ show the content as the later screenshot (e.g. with ' :set enc=utf-8').

So I cannot reproduce.

**Comment by chrisbra** [comment]
BTW: vim version 8.2.896 from last night, but I did not see a difference with my previous version 8.2.625 (or whatever the older one version was).

**Comment by chrisbra** [comment]
oh and for the first version, I did also try with the cursor on the null byte. In any case, I did not see a difference with regard to `yy`

**Comment by k-takata** [comment]
When I yank a line `a^@test` by `yy`, `:reg *` shows `a^@test^J`.
However, when I yank a line `^@test`, `:reg *` shows nothing.

**Comment by lkintact** [comment]
> I don't know what is going on here. In a plain `gvim --clean file.txt` I see this
> 
> ![grafik](https://user-images.githubusercontent.com/244927/83734955-f9b16080-a64f-11ea-9e43-b1e6aba7ee59.png)

This is what I see in both 8.2.825 and 8.2.896 right after `gvim --clean file.txt`:
![Clip](https://user-images.githubusercontent.com/24726299/83743659-b365fc80-a663-11ea-9bd8-cabd148644bc.png)
To make it unambiguous, the file contents in hex values are `00 74 65 73 74 0A`.

**Comment by chrisbra** [comment]
thanks can reproduce now. How was that file created? It has a byte order mark, but it is not using unicode encoding. That is a bit strange.

**Comment by k-takata** [comment]
It doesn't have a BOM:

```console
$ curl -s -L https://github.com/vim/vim/files/4685373/test.txt | xxd
00000000: 0074 6573 740a                           .test.
```

**Comment by lkintact** [comment]
>How was that file created? It has a byte order mark, but it is not using unicode encoding.

Sorry, I can't remember or restore now the way it was created, but it was either with gVim or my file manger. It seems strange to me is that you have a BOM in the file: when I click on the [file link](https://github.com/vim/vim/files/4685373/test.txt) in my first message I get a file 6 bytes long, with the contents I specified above, `00 74 65 73 74 0A`, thus it doesn't have a BOM, and these were its intended contents.

**Comment by chrisbra** [comment]
hm, I must have made something wrong when downloading it. Sorry for the confusion.

**Comment by chrisbra** [comment]
I think this patch fixes it:

```patch
diff --git a/src/winclip.c b/src/winclip.c
index 767bf1c71..38b94481b 100644
--- a/src/winclip.c
+++ b/src/winclip.c
@@ -422,7 +422,7 @@ clip_mch_request_selection(Clipboard_T *cbd)
        }
     }

-    if (str != NULL && *str != NUL)
+    if (str != NULL)
     {
        char_u *temp_clipboard;

@@ -543,7 +543,7 @@ clip_mch_set_selection(Clipboard_T *cbd)

        if (lpszMem)
        {
-           vim_strncpy((char_u *)lpszMem, str, metadata.txtlen);
+           mch_memmove((char_u *)lpszMem, str, metadata.txtlen);
            GlobalUnlock(hMem);
        }
     }

```

However please note: While Vim is able to receive the copied selection from the clipboard, it is still not available for other programs, e.g. pasting into notepad won't work. I suppose this is because the text starts with an ascii null byte.

So if you use your testfile and put a couple of letters before the null byte and copy the line, it will only paste the characters in front of the null byte into the target application (e.g. notepad). Not sure if this is a general clipboard limitation.

Note, that a side-effect to this patch is that this will also always show the clipboard register in the output of `:reg`, even if you do `:let @*=''`,

**Comment by lkintact** [comment]
Thanks for the patch pointing out that peculiarity of the clipboard operation. 
Not sure if I should close the issue, because if I do the bug will probably remain in the master branch.

**Comment by chrisbra** [comment]
I don't know Windows very well (neither from the API nor the internal concepts for the Clipboard). So I hoped for some comments from developers that know it better like @k-takata
BTW: do you happen to know how other editors handle this ASCII NUL character and the clipboard integration?

**Comment by k-takata** [comment]
> Note, that a side-effect to this patch is that this will also always show the clipboard register in the output of `:reg`, even if you do `:let @*=''`,

Then, how about this?

```diff
--- a/src/winclip.c
+++ b/src/winclip.c
@@ -422,7 +422,7 @@ clip_mch_request_selection(Clipboard_T *
 	}
     }
 
-    if (str != NULL && *str != NUL)
+    if (str != NULL && metadata.txtlen != 0)
     {
 	char_u *temp_clipboard;
 
@@ -543,7 +543,7 @@ clip_mch_set_selection(Clipboard_T *cbd)
 
 	if (lpszMem)
 	{
-	    vim_strncpy((char_u *)lpszMem, str, metadata.txtlen);
+	    mch_memmove((char_u *)lpszMem, str, metadata.txtlen);
 	    GlobalUnlock(hMem);
 	}
     }
```

**Comment by chrisbra** [comment]
yes, makes sense I think.

**Comment by chrisbra** [comment]
FWIW: I tested it quickly with brackets and notepad++. Both replace the ASCII NUL by a space when copying to the clipboard.

**Comment by brammool** [comment]
Is it possible to write a test case for this?  Possibly by using the reproduction steps.

**Comment by Shane-XB-Qian** [comment]
> FWIW: I tested it quickly with brackets and notepad++. Both replace the ASCII NUL by a space when copying to the clipboard.

looks regardless &clipboard setting, even @+ @* @" all was this `^@test`, i tried mousepad and libreoffice writer, both can not **paste** such chars/text (both can not recognize this heading NUL). fyi.
