### ISSUE TITLE
has("patch-7.3.867") return 0.

### ISSUE THREAD

**Issue by wsdjeg** [vim/vim#615]
but my vim --version show me

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:47)
包含补丁: 1-52
修改者 pkg-vim-maintainers@lists.alioth.debian.org
编译者 buildd@
巨型版本 带 GTK2-GNOME 图形界面。
  可使用(+)与不可使用(-)的功能:
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
+balloon_eval    +float           +mouse_urxvt     -tag_any_white
+browse          +folding         +mouse_xterm     +tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
+clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      +toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  +lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      +X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      -sniff           +xsmp_interact
+eval            +mouse_dec       +startuptime     +xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    +xpm
     系统 vimrc 文件: "$VIM/vimrc"
     用户 vimrc 文件: "$HOME/.vimrc"
 第二用户 vimrc 文件: "~/.vim/vimrc"
      用户 exrc 文件: "$HOME/.exrc"
    系统 gvimrc 文件: "$VIM/gvimrc"
    用户 gvimrc 文件: "$HOME/.gvimrc"
第二用户 gvimrc 文件: "~/.vim/gvimrc"
        系统菜单文件: "$VIMRUNTIME/menu.vim"
         $VIM 预设值: "/usr/share/vim"
编译方式: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/harfbuzz   -pthread -DORBIT2=1 -D_REENTRANT -I/usr/include/libgnomeui-2.0 -I/usr/include/libart-2.0 -I/usr/include/gconf/2 -I/usr/include/gnome-keyring-1 -I/usr/include/libgnome-2.0 -I/usr/include/libbonoboui-2.0 -I/usr/include/libgnomecanvas-2.0 -I/usr/include/gtk-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gnome-vfs-2.0 -I/usr/lib/x86_64-linux-gnu/gnome-vfs-2.0/include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/orbit-2.0 -I/usr/include/libbonobo-2.0 -I/usr/include/bonobo-activation-2.0 -I/usr/include/libxml2 -I/usr/include/pango-1.0 -I/usr/include/gail-1.0 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/atk-1.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/cairo -I/usr/include/gio-unix-2.0/ -I/usr/include/pixman-1 -I/usr/include/libpng12     -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1     -I/usr/include/tcl8.6  -D_REENTRANT=1  -D_THREAD_SAFE=1  -D_LARGEFILE64_SOURCE=1  
链接方式: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfontconfig -lgobject-2.0 -lglib-2.0 -lfreetype     -lgnomeui-2 -lSM -lICE -lbonoboui-2 -lgnomevfs-2 -lgnomecanvas-2 -lgnome-2 -lpopt -lbonobo-2 -lbonobo-activation -lORBit-2 -lart_lgpl_2 -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfontconfig -lfreetype -lgconf-2 -lgthread-2.0 -lgmodule-2.0 -lgobject-2.0 -lglib-2.0   -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector -L/usr/local/lib  -L/usr/lib/perl/5.18/CORE -lperl -ldl -lm -lpthread -lcrypt -L/usr/lib/python2.7/config-x86_64-linux-gnu -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions  -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-1.9.1 -lpthread -lrt -ldl -lcrypt -lm  -L/usr/lib
```

**Comment by wsdjeg** [comment]
it is in 
https://github.com/artur-shaik/vim-javacomplete2/blob/f7a0a6e175011be95500452ba7a4cc510fd940dd/autoload/javacomplete.vim#L200-L202

``` vim
if has("patch-7.3.867")
    autocmd TextChangedI *.java,*.jsp call s:HandleTextChangedI()
endif
```

@artur-shaik should I change to 

``` vim
if v:version > 703 || v:version == 703 && has('patch867')
  autocmd TextChangedI *.java,*.jsp call s:HandleTextChangedI()
endif
```

thanks @mhinz  's vim-galore

#### By the way ,in neovim `has("patch-7.3.867")` return 1

**Comment by wsdjeg** [comment]
sorry , even if I change to 

``` vim
" if v:version > 703 || v:version == 703 && has('patch867')
  autocmd TextChangedI *.java,*.jsp call s:HandleTextChangedI()
" endif
```

still can not HandleTextchangedi,so I think maybe my vim really has no `patch-7.3.867`

**Comment by vim-ml** [comment]
Hi,

2016-1-31(Sun) 13:25:00 UTC+9 Wang Shidong:

> it is in 
> 
> https://github.com/artur-shaik/vim-javacomplete2/blob/f7a0a6e175011be95500452ba7a4cc510fd940dd/autoload/javacomplete.vim#L200-L202
> 
> if has("patch-7.3.867")
>     autocmd TextChangedI _.java,_.jsp call s:HandleTextChangedI()
> endif
> 
> @artur-shaik should I change to 
> 
> if v:version > 704 || v:version == 703 && has('patch867')
>   autocmd TextChangedI _.java,_.jsp call s:HandleTextChangedI()
> endif

In this case, it is better to use the `exists("##TextChangedI")`.

On Vim 7.3.866
:echo exists("##TextChangedI")
0

On Vim 7.3.867
:echo exists("##TextChangedI")
1

On Vim 7.4.1219
:echo exists("##TextChangedI")
1

## 

Best regards,
Hirohito Higashi (a.k.a h_east)

**Comment by wsdjeg** [comment]
got it thanks ,echo exists("##TextChangedI") return 1 .
but I mean even I remove if ...endif, `s:HandleTextChangedI()` still does not work in my vim.
I remamber it works well in ubuntu 16.04, but now I change my os to ubuntu 14.04. so the vim's version is very old.
`s:HandleTextChangedI()` work well in neovim (from PPA source)

**Comment by gisphm** [comment]
@wsdjeg well, you can build a brand new vim from source following the latest code.

**Comment by wsdjeg** [comment]
sorry ,I need to use the official installation package from trust main source to avoid bug.

**Comment by mattn** [comment]
Please discuss on plugin's issue. This is not an issue of vim self.

**Comment by wsdjeg** [comment]
I think it is vim's issue vim 7.4.052 from ubuntu 14.04
 `echo has("patch-7.3.867")` return 0
7.4.1129 show 1
and neovim show 1

**Comment by vim-ml** [comment]
On Sun, Jan 31, 2016 at 4:59 AM, Wang Shidong vim-dev-github@256bit.org wrote:

> but my vim --version show me
> 
> VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:47)
> 包含补丁: 1-52

Regardless of which version you are running (in this case: 7.4.52),
has('patch-7.3.867') will always return 0 because the format of the
argument is incorrect.

To test for the presence of patch 7.3.867, you should use

```
if (version > 703) || ((version == 703) && has('patch867'))
```

In the first parenthesis, version is preferable to v:version in order
to catch really old versions which knew about version but not about
v:version.
In the second parenthesis, version and v:version are equivalent
because these old versions have already been eliminated by
short-circuit evaluation.
Notice that the has() argument for the patch number includes neither
dot nor hyphen, and that the major-minor version must already be
known.

See ":help has-patch"

Best regards,
Tony.

**Comment by wsdjeg** [comment]
@vim-ml Thank you very much,from your letter,I got everything I needs.

**Comment by vim-ml** [comment]
On Sun, Jan 31, 2016 at 6:16 AM, Tony Mechelynck
antoine.mechelynck@gmail.com wrote:

> On Sun, Jan 31, 2016 at 4:59 AM, Wang Shidong vim-dev-github@256bit.org wrote:
> 
> > but my vim --version show me
> > 
> > VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:47)
> > 包含补丁: 1-52
> 
> Regardless of which version you are running (in this case: 7.4.52),
> has('patch-7.3.867') will always return 0 because the format of the
> argument is incorrect.
> 
> To test for the presence of patch 7.3.867, you should use
> 
> ```
> if (version > 703) || ((version == 703) && has('patch867'))
> ```
> 
> In the first parenthesis, version is preferable to v:version in order
> to catch really old versions which knew about version but not about
> v:version.
> In the second parenthesis, version and v:version are equivalent
> because these old versions have already been eliminated by
> short-circuit evaluation.
> Notice that the has() argument for the patch number includes neither
> dot nor hyphen, and that the major-minor version must already be
> known.
> 
> See ":help has-patch"
> 
> Best regards,
> Tony.

P.S. has('patch-7.4.1000') is correct, but only when running a Vim
version 7.4.237 or later, which is not your case. In earlier Vim
versions, you need to test separately for major-minor and for patch,
as mentioned in my earlier post.

Best regards,
Tony.

**Comment by wsdjeg** [comment]
ok ,I will try to switch to some other PPA source to install the newer version vim .

**Comment by lilydjwg** [comment]
I remember that without patch 7.4.143 `TextChangedI` doesn't work as expected.

**Comment by wsdjeg** [comment]
@lilydjwg thanks ,I think that is why even if I remove the if ---endif ,also can not work.
Did not find the right resources, I interrupted compiled myself
