### ISSUE TITLE
set foldopen-=search goes to a never-ending loop

### ISSUE THREAD

**Issue by kutsan** [vim/vim#6152]
### Steps to reproduce

```
1. vim -Nu NORC -c 'set foldopen-=search foldmethod=indent'

3. (Write the following into the buffer)
if
	foo
	foo
endif

4. (Fold the lines with za if it's not already folded.)
if
+--  2 lines: foo··············································································································
endif

5. /foo<CR>
6. n
7. n
8. n
9. n
.
.
.
```

### Actual behaviour

Pressing `n` makes a new entry in search list, thus it goes to a never-ending cycle.

### Expected behaviour

Pressing `n` should cycle through that two `foo`.

**Environment:**
 - Vim version [e.g. 8.1.1234]: `VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 19 2020 22:07:34)`
 - OS: [e.g. Ubuntu 18.04, Windows 10 1809, macOS 10.14]: `macOS 10.14.6 (18G95)`
 - Terminal: [e.g. GNOME Terminal, mintty, iTerm2, tmux, GNU screen]: `kitty`

See for the mirror issue: https://github.com/neovim/neovim/issues/12370

**Comment by chrisbra** [comment]
The bug description is a bit misleading, because there is no never-ending loop and it took me a while, that you meant the search-stats being wrong.

Anyhow, I think I have fixed it in my local copy, PR coming in just a minute

**Comment by kutsan** [comment]
@chrisbra I'm so sorry to provide misleading description, I was in a rush I hadn't put enough time to describe what was wrong. I'll try to be better next time. But I'm glad it's solved.
