### ISSUE TITLE
The 'verbose' level 16 is not documented

### ISSUE THREAD

**Issue by lkintact** [vim/vim#6153]
**Describe the bug**
The description at `:help 'verbose'` doesn't mention level 16, which does differ from level 15.

**To Reproduce**
1. Run `gvim.exe --clean -V15fifteen.txt`, quit gVim with `:q`
2. Run `gvim.exe --clean -V16sixteen.txt`, quit gVim with `:q`
3. Diff-compare the files `fifteen.txt` and `sixteen.txt`: the latter has 4507 lines starting with "Executing:" while the former only has 4; maybe there are some other differences.

**Environment**
 - Vim 8.2.825 (https://github.com/vim/vim-win32-installer/releases/download/v8.2.0825/gvim_8.2.0825_x86_signed.zip)
 - OS: Windows 10 Home 1803
 - Terminal: GUI.

**Comment by chrisbra** [comment]
Here would be a doc patch:
```patch
diff --git a/runtime/doc/options.txt b/runtime/doc/options.txt
index cc3f5126b..4b457ff76 100644
--- a/runtime/doc/options.txt
+++ b/runtime/doc/options.txt
@@ -8332,6 +8332,7 @@ A jump table for the options with a short description can be found at |Q_op|.
        >= 13   When an exception is thrown, caught, finished, or discarded.
        >= 14   Anything pending in a ":finally" clause.
        >= 15   Every executed Ex command (truncated at 200 characters).
+       >= 16   Also mention, when the executed command is executed
 
        This option can also be set with the "-V" argument.  See |-V|.
        This option is also set by the |:verbose| command.
```

Actually, I think this is not really useful, so perhaps it is better to remove verbose level 16 altogether:

```patch
diff --git a/src/ex_docmd.c b/src/ex_docmd.c
index adde9d75f..d0abc391f 100644
--- a/src/ex_docmd.c
+++ b/src/ex_docmd.c
@@ -1691,9 +1691,6 @@ do_one_cmd(
     if ((*cmdlinep)[0] == '#' && (*cmdlinep)[1] == '!')
        goto doend;
 
-    if (p_verbose >= 16)
-       msg_verbose_cmd(0, *cmdlinep);
-
 /*
  * 1. Skip comment lines and leading white space and colons.
  * 2. Handle command modifiers.
```

**Comment by brammool** [comment]
Christian wrote:

> Here would be a doc patch:
> ```patch
> diff --git a/runtime/doc/options.txt b/runtime/doc/options.txt
> index cc3f5126b..4b457ff76 100644
> --- a/runtime/doc/options.txt
> +++ b/runtime/doc/options.txt
> @@ -8332,6 +8332,7 @@ A jump table for the options with a short description can be found at |Q_op|.
>         >= 13   When an exception is thrown, caught, finished, or discarded.
>         >= 14   Anything pending in a ":finally" clause.
>         >= 15   Every executed Ex command (truncated at 200 characters).
> +       >= 16   Also mention, when the executed command is executed
>  
>         This option can also be set with the "-V" argument.  See |-V|.
>         This option is also set by the |:verbose| command.
> ```
> 
> Actually, I think this is not really useful, so perhaps it is better to remove verbose level 16 altogether:
> 
> ```patch
> diff --git a/src/ex_docmd.c b/src/ex_docmd.c
> index adde9d75f..d0abc391f 100644
> --- a/src/ex_docmd.c
> +++ b/src/ex_docmd.c
> @@ -1691,9 +1691,6 @@ do_one_cmd(
>      if ((*cmdlinep)[0] == '#' && (*cmdlinep)[1] == '!')
>         goto doend;
>  
> -    if (p_verbose >= 16)
> -       msg_verbose_cmd(0, *cmdlinep);
> -
>  /*
>   * 1. Skip comment lines and leading white space and colons.
>   * 2. Handle command modifiers.
> ```

We can do both: When the level is 16 we don't use the condition for the
source to be known.  That avoids printing every command twice.

-- 
hundred-and-one symptoms of being an internet addict:
207. You're given one phone call in prison and you ask them for a laptop.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
