### ISSUE TITLE
CTRL-B mapping ignored at the hit-enter prompt when modifyOtherKeys is enabled

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6158]
**Describe the bug**

A mapping using the control modifier is ignored at the hit-enter prompt when modifyOtherKeys is enabled.

**To Reproduce**

Start an xterm terminal, and run this shell command:

    vim -Nu NONE +'nno <c-b> :echom "C-b was pressed"<cr>' +hi

Press `C-b`: no message is printed on the command-line, nor logged in the output of `:messages`.

**Expected behavior**

"C-b was pressed" is printed on the command-line, and logged in the output of `:messages`.

**Environment**

 - Vim version: 8.2 Included patches: 1-836
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

The issue disappears if the modifyOtherKeys feature is disabled.

    vim -Nu NONE --cmd 'let [&t_TI, &t_TE] = ["", ""]' +'nno <c-b> :echom "C-b was pressed"<cr>' +hi
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by brammool** [comment]
I cannot reproduce the problem, it works with and without modifyOtherKeys enabled.

**Comment by lacygoill** [comment]
I'm on the latest commit (8.2.0836), and I can reproduce without:

   - any Vim config (`-Nu NONE`)
   - any shell config (`bash --norc --noprofile`)
   - any terminal config (commented the whole `~/.Xresources`)
   - any special option during the compilation, except `--with-features=huge` (`./configure --with-features=huge`)

Here is a gif when modifyOtherKeys is enabled:

![gif](https://user-images.githubusercontent.com/8505073/83296478-29480f00-a1f1-11ea-8fb0-1ec8d022a8fc.gif)

And here is a gif when modifyOtherKeys is disabled:

![gif](https://user-images.githubusercontent.com/8505073/83296644-66ac9c80-a1f1-11ea-98b7-e1e698db9c72.gif)

**Comment by lacygoill** [comment]
Another thing that I've just noticed.  The mapping works if `<c-b>` is replaced with a literal `C-b` character (obtained after pressing `C-v C-b`).

I guess the issue is somehow linked to what you said [here](https://github.com/vim/vim/issues/6117#issuecomment-632905823) about the fact that a `<C-b>` mapping exists in two forms; a simplified one and a non-simplified one.  It seems that the non-simplified form doesn't work at the hit-enter prompt when modifyOtherKeys is enabled.

**Comment by brammool** [comment]
Ah, I missed the part about this being at the hit enter prompt.  Hmm, I suppose much more must have already been failing there.
