### ISSUE TITLE
[enhancement] Vimtutor lesson 8 (on VimRC) and a VimRC creation tool

### ISSUE THREAD

**Issue by pmerry96** [vim/vim#6159]
As a soon to be computer science graduate, I wanted to make a tool to make programming with Vim (the editor my peers and I were told to use) a little more conducive to new users. This would mean adding to the VimTutor lessons, and including some tools to build or amend a VimRC. This is not meant to replace the vimrc, but rather is meant to serve as an introduction and subsequent jumping off point to customizing vim. 

I would like the solution to be threefold, here are the steps bulleted below
- Add lesson 8: the VimRC to vimtutor
- Add a tool for users to create, amend, or add to their vimRC from a set of commonly used options, for the purpose of users seeing how to synthesize their own vimRC. 
- Add the ability to see changes to the vimrc in the current Vim instance(s), for better understanding of how each option works. 
Each is a slight build upon the previous, with the hopes that a new user who chooses to use these tools will be given the background to modify their editor independently. Additionally, this may also serve as a faster way for developers to change their settings to fit their workflow without exiting their current work and navigating to a vimrc to enact changes. 

This is an alternative to a pre-packaged VimRC, which I believe is against the spirit of Vim. By adding the vimtutor lesson and the 'settings pane' tool, users will be introduced to creating their VimRC and customizing vim to their use. This foregoes the style-railroading that would apply should the vimrc ship with the software. 

This is my first OSS contribution, and as such I tried to choose tasks that were escalating in complexity. I have a firm knowledge of C, but should anything be impossible or able to be done better, please let me know! I hope you all find this applicable, and I look forward to firming the idea up and issuing a pull request!

**Comment by vim-ml** [comment]
On 2020-05-29, pmerry96 wrote:
> As a soon to be computer science graduate, I wanted to make a tool to make
> programming with Vim (the editor my peers and I were told to use) a little more
> conducive to new users. This would mean adding to the VimTutor lessons, and
> including some tools to build or amend a VimRC. This is not meant to replace
> the vimrc, but rather is meant to serve as an introduction and subsequent
> jumping off point to customizing vim.
> 
> I would like the solution to be threefold, here are the steps bulleted below
> 
>   • Add lesson 8: the VimRC to vimtutor
>   • Add a tool for users to create, amend, or add to their vimRC from a set of
>     commonly used options, for the purpose of users seeing how to synthesize
>     their own vimRC.
>   • Add the ability to see changes to the vimrc in the current Vim instance(s),
>     for better understanding of how each option works.
>     Each is a slight build upon the previous, with the hopes that a new user
>     who chooses to use these tools will be given the background to modify their
>     editor independently. Additionally, this may also serve as a faster way for
>     developers to change their settings to fit their workflow without exiting
>     their current work and navigating to a vimrc to enact changes.
> 
> This is an alternative to a pre-packaged VimRC, which I believe is against the
> spirit of Vim. By adding the vimtutor lesson and the 'settings pane' tool,
> users will be introduced to creating their VimRC and customizing vim to their
> use. This foregoes the style-railroading that would apply should the vimrc ship
> with the software.
> 
> This is my first OSS contribution, and as such I tried to choose tasks that
> were escalating in complexity. I have a firm knowledge of C, but should
> anything be impossible or able to be done better, please let me know! I hope
> you all find this applicable, and I look forward to firming the idea up and
> issuing a pull request!

Vimtutor Lesson 7.2 is "Create a Startup Script", which covers the
very basics of using a vimrc.  The last line of that lesson is
a pointer to ":help vim-intro", which explains more thoroughly how
to use a vimrc.  Is there something else important to a new user
that's missing?

The ideal tool for building or amending to a vimrc is Vim itself.
Vimrc is a text file.  Vim excels at editing text files.  One
benefit of teaching new users to use Vim to edit their vimrc is that
they gain experience and proficiency at using Vim.

I think that a separate tool for editing a vimrc, even one
integrated into Vim, would add a layer of magic over Vim's command
line and the vimrc that would not help a new user's understanding of
the process and would give the erroneous impression that a tool was
necessary to maintain a vimrc.

The best thing that a new user, or any user for that matter, can do
to build confidence and proficiency with Vim is to use it.

As for the tool being "a faster way for developers to change their
settings to fit their workflow without exiting their current work
and navigating to a vimrc to enact changes":  it is not necessary to
exit one's current work nor to navigate to the vimrc.  Simply
execute either of these commands:

    :new $MYVIMRC
    :tabnew $MYVIMRC

You write well.  You recognize the problems that you and your peers
have had in learning to use Vim.  You formulated and presented
a reasonable solution.  I don't think it should be adopted as-is for
the reasons above, but I think you have a lot to offer the Vim
project and hope you continue to contribute.

Regards,
Gary
