### ISSUE TITLE
why gvim has no icon?

### ISSUE THREAD

**Issue by wsdjeg** [vim/vim#616]
here is my config

``` sh
#!/bin/sh

./configure \
    --with-features=huge \
    --with-compiledby="wsdjeg" \
    --enable-multibyte \
    --enable-gui=gtk2 \
    --enable-gpm \
    --prefix=/usr \
    --enable-cscope \
    --enable-fontset \
    --enable-sniff \
    --enable-xim \
    --enable-fail-if-missing \
    --enable-mzschemeinterp \
    --enable-perlinterp \
    --enable-luainterp \
    --enable-tclinterp\
    --enable-rubyinterp \
    --enable-pythoninterp \
    --with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu

```
#### has no icon just a `?`

![2016-02-01 00 30 29](https://cloud.githubusercontent.com/assets/13142418/12703331/9183c6c6-c87b-11e5-885a-6f1042a247e6.png)

**Comment by vim-ml** [comment]
After the installation is done, do you have
/usr/share/applications/gvim.desktop?

2016-02-01 1:35 GMT+09:00 Wang Shidong vim-dev-github@256bit.org:

**Comment by wsdjeg** [comment]
has, here is 

```
[Desktop Entry]
Name=GVim
GenericName=Text Editor
GenericName[de]=Texteditor
Comment=Edit text files
Comment[af]=Redigeer tekslêers
Comment[am]=የጽሑፍ ፋይሎች ያስተካክሉ
Comment[ar]=حرّر ملفات نصية
Comment[az]=Mətn fayllarını redaktə edin
Comment[be]=Рэдагаваньне тэкставых файлаў
Comment[bg]=Редактиране на текстови файлове
Comment[bn]=টেক্স্ট ফাইল এডিট করুন
Comment[bs]=Izmijeni tekstualne datoteke
Comment[ca]=Edita fitxers de text
Comment[cs]=Úprava textových souborů
Comment[cy]=Golygu ffeiliau testun
Comment[da]=Redigér tekstfiler
Comment[de]=Textdateien bearbeiten
Comment[el]=Επεξεργασία αρχείων κειμένου
Comment[en_CA]=Edit text files
Comment[en_GB]=Edit text files
Comment[es]=Edita archivos de texto
Comment[et]=Redigeeri tekstifaile
Comment[eu]=Editatu testu-fitxategiak
Comment[fa]=ویرایش پرونده‌های متنی
Comment[fi]=Muokkaa tekstitiedostoja
Comment[fr]=Édite des fichiers texte
Comment[ga]=Eagar comhad Téacs
Comment[gu]=લખાણ ફાઇલોમાં ફેરફાર કરો
Comment[he]=ערוך קבצי טקסט
Comment[hi]=पाठ फ़ाइलें संपादित करें
Comment[hr]=Uređivanje tekstualne datoteke
Comment[hu]=Szövegfájlok szerkesztése
Comment[id]=Edit file teks
Comment[it]=Modifica file di testo
Comment[ja]=テキストファイルを編集します
Comment[kn]=ಪಠ್ಯ ಕಡತಗಳನ್ನು ಸಂಪಾದಿಸು
Comment[ko]=텍스트 파일을 편집합니다
Comment[lt]=Redaguoti tekstines bylas
Comment[lv]=Rediģēt teksta failus
Comment[mk]=Уреди текстуални фајлови
Comment[ml]=വാചക രചനകള് തിരുത്തുക
Comment[mn]=Текст файл боловсруулах
Comment[mr]=गद्य फाइल संपादित करा
Comment[ms]=Edit fail teks
Comment[nb]=Rediger tekstfiler
Comment[ne]=पाठ फाइललाई संशोधन गर्नुहोस्
Comment[nl]=Tekstbestanden bewerken
Comment[nn]=Rediger tekstfiler
Comment[no]=Rediger tekstfiler
Comment[or]=ପାଠ୍ଯ ଫାଇଲଗୁଡ଼ିକୁ ସମ୍ପାଦନ କରନ୍ତୁ
Comment[pa]=ਪਾਠ ਫਾਇਲਾਂ ਸੰਪਾਦਨ
Comment[pl]=Edytor plików tekstowych
Comment[pt]=Editar ficheiros de texto
Comment[pt_BR]=Edite arquivos de texto
Comment[ro]=Editare fişiere text
Comment[ru]=Редактор текстовых файлов
Comment[sk]=Úprava textových súborov
Comment[sl]=Urejanje datotek z besedili
Comment[sq]=Përpuno files teksti
Comment[sr]=Измени текстуалне датотеке
Comment[sr@Latn]=Izmeni tekstualne datoteke
Comment[sv]=Redigera textfiler
Comment[ta]=உரை கோப்புகளை தொகுக்கவும்
Comment[th]=แก้ไขแฟ้มข้อความ
Comment[tk]=Metin faýllary editle
Comment[tr]=Metin dosyalarını düzenle
Comment[uk]=Редактор текстових файлів
Comment[vi]=Soạn thảo tập tin văn bản
Comment[wa]=Asspougnî des fitchîs tecses
Comment[zh_CN]=编辑文本文件
Comment[zh_TW]=編輯文字檔
TryExec=gvim
Exec=gvim -f %F
Terminal=false
Type=Application
Icon=gvim
Categories=Utility;TextEditor;
StartupNotify=true
MimeType=text/english;text/plain;text/x-makefile;text/x-c++hdr;text/x-c++src;text/x-chdr;text/x-csrc;text/x-java;text/x-moc;text/x-pascal;text/x-tcl;text/x-tex;application/x-shellscript;text/x-c;text/x-c++;

```

**Comment by wsdjeg** [comment]
and vim.desktop is 

```
[Desktop Entry]
Name=Vim
GenericName=Text Editor
GenericName[de]=Texteditor
Comment=Edit text files
Comment[af]=Redigeer tekslêers
Comment[am]=የጽሑፍ ፋይሎች ያስተካክሉ
Comment[ar]=حرّر ملفات نصية
Comment[az]=Mətn fayllarını redaktə edin
Comment[be]=Рэдагаваньне тэкставых файлаў
Comment[bg]=Редактиране на текстови файлове
Comment[bn]=টেক্স্ট ফাইল এডিট করুন
Comment[bs]=Izmijeni tekstualne datoteke
Comment[ca]=Edita fitxers de text
Comment[cs]=Úprava textových souborů
Comment[cy]=Golygu ffeiliau testun
Comment[da]=Redigér tekstfiler
Comment[de]=Textdateien bearbeiten
Comment[el]=Επεξεργασία αρχείων κειμένου
Comment[en_CA]=Edit text files
Comment[en_GB]=Edit text files
Comment[es]=Edita archivos de texto
Comment[et]=Redigeeri tekstifaile
Comment[eu]=Editatu testu-fitxategiak
Comment[fa]=ویرایش پرونده‌های متنی
Comment[fi]=Muokkaa tekstitiedostoja
Comment[fr]=Édite des fichiers texte
Comment[ga]=Eagar comhad Téacs
Comment[gu]=લખાણ ફાઇલોમાં ફેરફાર કરો
Comment[he]=ערוך קבצי טקסט
Comment[hi]=पाठ फ़ाइलें संपादित करें
Comment[hr]=Uređivanje tekstualne datoteke
Comment[hu]=Szövegfájlok szerkesztése
Comment[id]=Edit file teks
Comment[it]=Modifica file di testo
Comment[ja]=テキストファイルを編集します
Comment[kn]=ಪಠ್ಯ ಕಡತಗಳನ್ನು ಸಂಪಾದಿಸು
Comment[ko]=텍스트 파일을 편집합니다
Comment[lt]=Redaguoti tekstines bylas
Comment[lv]=Rediģēt teksta failus
Comment[mk]=Уреди текстуални фајлови
Comment[ml]=വാചക രചനകള് തിരുത്തുക
Comment[mn]=Текст файл боловсруулах
Comment[mr]=गद्य फाइल संपादित करा
Comment[ms]=Edit fail teks
Comment[nb]=Rediger tekstfiler
Comment[ne]=पाठ फाइललाई संशोधन गर्नुहोस्
Comment[nl]=Tekstbestanden bewerken
Comment[nn]=Rediger tekstfiler
Comment[no]=Rediger tekstfiler
Comment[or]=ପାଠ୍ଯ ଫାଇଲଗୁଡ଼ିକୁ ସମ୍ପାଦନ କରନ୍ତୁ
Comment[pa]=ਪਾਠ ਫਾਇਲਾਂ ਸੰਪਾਦਨ
Comment[pl]=Edytor plików tekstowych
Comment[pt]=Editar ficheiros de texto
Comment[pt_BR]=Edite arquivos de texto
Comment[ro]=Editare fişiere text
Comment[ru]=Редактор текстовых файлов
Comment[sk]=Úprava textových súborov
Comment[sl]=Urejanje datotek z besedili
Comment[sq]=Përpuno files teksti
Comment[sr]=Измени текстуалне датотеке
Comment[sr@Latn]=Izmeni tekstualne datoteke
Comment[sv]=Redigera textfiler
Comment[ta]=உரை கோப்புகளை தொகுக்கவும்
Comment[th]=แก้ไขแฟ้มข้อความ
Comment[tk]=Metin faýllary editle
Comment[tr]=Metin dosyalarını düzenle
Comment[uk]=Редактор текстових файлів
Comment[vi]=Soạn thảo tập tin văn bản
Comment[wa]=Asspougnî des fitchîs tecses
Comment[zh_CN]=编辑文本文件
Comment[zh_TW]=編輯文字檔
TryExec=vim
Exec=vim %F
Terminal=true
Type=Application
Icon=gvim
Categories=Utility;TextEditor;
StartupNotify=false
MimeType=text/english;text/plain;text/x-makefile;text/x-c++hdr;text/x-c++src;text/x-chdr;text/x-csrc;text/x-java;text/x-moc;text/x-pascal;text/x-tcl;text/x-tex;application/x-shellscript;text/x-c;text/x-c++;
```

**Comment by vim-ml** [comment]
Then, what are the contents of /usr/share/icons/hicolor/48x48/apps?

Can you find gvim.png?

2016-02-01 1:42 GMT+09:00 Wang Shidong vim-dev-github@256bit.org:

**Comment by nuko8** [comment]
Adding to 48x48, check 32x32 and 16x16, too.

2016-02-01 1:48 GMT+09:00 vim-dev ML notifications@github.com:

**Comment by wsdjeg** [comment]
only `48x48` has gvim.png
`ls /usr/share/icons/hicolor/48x48/apps |ag gvim`
show me gvim.png

**Comment by nuko8** [comment]
If you can exercise root privilege on the computer in use, do

$ sudo mkdir -p /usr/share/icons/hicolor/32x32/apps
$ sudo mkdir -p /usr/share/icons/hicolor/16x16/apps

and then install vim again.  You should have 32x32 and 16x16 icons there.

**Comment by wsdjeg** [comment]
I have this two dir before I install vim

**Comment by nuko8** [comment]
Then, go to the vim source.  You'll find there

runtime/vim16x16.png
runtime/vim32x32.png

Can you do the following?

sudo cp runtime/vim16x16.png /usr/share/icons/hicolor/16x16/apps/gvim.png
sudo cp runtime/vim32x32.png /usr/share/icons/hicolor/32x32/apps/gvim.png

**Comment by wsdjeg** [comment]
is there any issue with my compile config? I have shown above

**Comment by nuko8** [comment]
No, I don't see any.

So I'm asking you to do some operations to check if the issue is on the vim side.

**Comment by wsdjeg** [comment]
so how should I write the config?

**Comment by nuko8** [comment]
You mean you can't see an icon even after installing 16x16 and 32x32 icons manually?

**Comment by chrisbra** [comment]
guys, can we please keep this here for actual issues? user configuration or compiling issues should first be discussed on the respective mailinglist before creating issues here. Thanks!

**Comment by wsdjeg** [comment]
sorry ,closing it ,I will move to maillist

**Comment by nuko8** [comment]
Ah...

The current Makefile installs the 16x16 and 32x32 icons only into `$prefix/share/icons/locolor/16x16/apps` and `$prefix/share/icons/locolor/32x32/apps`, respectively, not the `hicolor` counterparts.

Considering the [Icon Theme Specification](http://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html), I was thinking it might be a cause of the problem...

**Comment by wsdjeg** [comment]
@nuko8 fixed this issue by 

```
sudo vim /usr/share/applications/gvim.desktop
- Icon=gvim
+ Icon=/usr/share/icons/hicolor/48x48/apps/gvim.png
```

**Comment by nuko8** [comment]
OK, It's not vim's bug, but your system's issue.

Looks you forgot to update ~~`/opt/local~~ /usr/share/icons/hicolor/icon-theme.cache`.

Update it using `gtk-update-icon-cache`(1).  Then `Icon=gvim` should be OK.

Please make sure next time if your problem is relevant to vim development before creating a git issue.

Thank you.

**Comment by brammool** [comment]
nuko8 wrote:

> OK, It's not vim's bug, but your system's issue.
> 
> Looks you forgot to update `/opt/local/share/icons/hicolor/icon-theme.cache`.
> 
> Update it using `gtk-update-icon-cache`(1).  Then `Icon=gvim` should be OK.
> 
> Please make sure next time if your problem is relevant to vim
> development before creating a git issue.

We discussed this before: should we run that cache update command during
installation?  We could find the command with a configure check.

## 

Corduroy pillows: They're making headlines!

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
Oh, I thought you didn't like the idea to have our Makefile update other
systems' cache files, because my proposed patch for updating mime.cache was
placed in the todo list since then.

So, I'm rather happy to hear your thoughts.

I'll revise my previous patch with configure checks and the icon cache
update, and send it to the list.

Regards,
Kazunobu Kuriyama (nuko8)

2016-02-03 3:34 GMT+09:00 Bram Moolenaar vim-dev-github@256bit.org:

**Comment by wsdjeg** [comment]
thanks  all of you
