### ISSUE TITLE
syntax/vim.vim doesn't recognize some flags for the ":s" command

### ISSUE THREAD

**Issue by lkintact** [vim/vim#6161]
**To Reproduce**
1. Run `gvim.exe --clean`
2. Put this into the buffer: `:%s/one/two/&cegiInp#lr`
3. Execute `:set ft=vim`

Unlike other flags, `n`, `#` and `l` are displayed in white on red.

**Environment**
 - Vim 8.2.825
 - OS: Windows 10 Home 1803
 - Terminal: GUI

**Comment by vim-ml** [comment]
On 2020-05-29, lkintact wrote:
> To Reproduce
> 
>  1. Run gvim.exe --clean
>  2. Put this into the buffer: :%s/one/two/&cegiInp#lr
>  3. Execute :set ft=vim
> 
> Unlike other flags, n, # and l are displayed in white on red.
> 
> Environment
> 
>   • Vim 8.2.825
>   • OS: Windows 10 Home 1803
>   • Terminal: GUI

You should contact the maintainer of the syntax file, whose contact
information appears at the top of the syntax file,
$VIMRUNTIME/syntax/vim.vim.

I've bcc'd him to avoid his address appearing on the list.

Regards,
Gary

**Comment by lkintact** [comment]
> You should contact the maintainer of the syntax file, whose contact
> information appears at the top of the syntax file,
> $VIMRUNTIME/syntax/vim.vim.
> 
> I've bcc'd him to avoid his address appearing on the list.

Thank you, that gave me an idea I described in my [next issue](https://github.com/vim/vim/issues/6164).

**Comment by cecamp** [comment]
I just sent an updated copy of syntax/vim.vim to Bram which will include these new flags.
