### ISSUE TITLE
In the GUI can't distinguish "<M-v>" from "ö" in a mapping

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6163]
**Describe the bug**

In the GUI we can't use the meta modifier in a mapping without losing the ability to insert some accented character.

**To Reproduce**

Start gVim with this shell command:

    vim -g -Nu NONE -u NONE +'ino <m-v> <left>' +"pu='foobar'" +'startinsert!'

Press the dead key `¨` followed by `o`: the cursor moves one character backward.

**Expected behavior**

gVim inserts the character `ö`.

**Environment**

 - Vim version: 8.2 Included patches: 1-846, Huge version with GTK2 GUI
 - OS: Ubuntu 16.04.6 LTS

**Additional context**

Maybe I misunderstood something, but according to [this comment](https://github.com/vim/vim/issues/4974#issuecomment-629478246) and [this comment](https://github.com/vim/vim/issues/4974#issuecomment-629628029), gVim should be able to make the distinction between `<M-v>` and `ö`, at least starting from [`8.2.0765`](https://github.com/vim/vim/releases/tag/v8.2.0765).

---

I thought that maybe some input method option needed to be configured correctly:

> Most likely the input method converts to a character before Vim even sees it.

So I tried all possible combinations of values for the options `'imdisable'`, `'iminsert'`, and `'imstyle'` which seems the only relevant ones for my test case.

In Vim, I sourced this code:

    let counter = 0
    for imdisable in ['imdisable', 'noimdisable']
        for iminsert in ['iminsert=0', 'iminsert=1', 'iminsert=2']
            for imstyle in ['imstyle=0', 'imstyle=1']
                let counter += 1
                call writefile([printf('set %s %s %s %s %s', imdisable, iminsert, imstyle, imsearch, imcmdline)],
                   \ '/tmp/.test.'..printf('%02d', counter)..'.vim')
            endfor
        endfor
    endfor

To create 12 files with the combinations of settings.  Then I ran this shell command:

    for f in /tmp/.test.01.vim; do vim -gf -Nu NONE -u NONE --cmd "so $f" +'ino <m-v> <left>' +"pu='foobar'" +'startinsert!'; done

I was able to insert `ö` only when `'imdisable'` was reset.  But when `'imdisable'` is reset, the `<M-v>` mapping doesn't work.  That is, instead of moving the cursor 1 character backward, it inserts the `ö` character.  IOW, there is no combination of settings which allows to simultaneously use a `<M-v>` mapping and insert the `ö` character.

**Comment by brammool** [comment]
Caused by 8.2.0833.  We actually always need to set seenModifyOtherKeys in the GUI.
And then pass on <C-bslash> as a modifier and key.
