### ISSUE TITLE
The "Bug reports" section of the docs should probably be a bit changed

### ISSUE THREAD

**Issue by lkintact** [vim/vim#6164]
[This answer](https://github.com/vim/vim/issues/6161#issuecomment-636251275) by @vim-ml gave me the idea of suggesting that the "Bug reports" section (`:help bugs`) be expanded to specify that syntax file-related issues should be reported to file maintainers, not this bugtracker or the maillist.

Vim 8.2.825

**Comment by brammool** [comment]
I'll add a third way to report bugs.  Might as well make using github the first one now.
