### ISSUE TITLE
completing ':cop' and executing ':cop' assumes different commands

### ISSUE THREAD

**Issue by AvianY** [vim/vim#6165]
It is not necessary that it is a bug, but it seems to me.
I expect that running
`:cop<CR>`
will run `copen`, but it doesn't. It runs `copy` instead.

Meanwhile completing
`:cop<Tab>`
will give `copen`

it seems inconsistent to me.

**Comment by brammool** [comment]
> It is not necessary that it is a bug, but it seems to me.
> I expect that running
> `:cop<CR>`
> will run `copen`, but it doesn't. It runs `copy` instead.
> 
> Meanwhile completing
> `:cop<Tab>`
> will give `copen`
> 
> it seems inconsistent to me.

"copen" is the first suggestions, if you type <Tab> again it will
complete to "copy".  The suggestions are sorted alphabetically.
":e<Tab>" will show ":earlier" first.  There is no perfect way for this.

-- 
hundred-and-one symptoms of being an internet addict:
222. You send more than 20 personal e-mails a day.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
