### ISSUE TITLE
plugins broken vim 8.2.814

### ISSUE THREAD

**Issue by ambushed** [vim/vim#6169]
**Describe the bug**
After upgrading my Arch, vim 8.2.814 started having issues with loading multiple plugins, for instance: 
```Error detected while processing /home/chalkman/Code/vim/.vim/plugged/ale/plugin/ale.vim:
line   48:
E697: Missing end of List ']':
line   49:
E10: \ should be followed by /, ? or &
line   50:
E10: \ should be followed by /, ? or &
line   51:
E10: \ should be followed by /, ? or &
line   52:
E10: \ should be followed by /, ? or &
line   53:
E10: \ should be followed by /, ? or &
line   54:
E10: \ should be followed by /, ? or &
line  164:
E10: \ should be followed by /, ? or &
line  166:
E10: \ should be followed by /, ? or &
Error detected while processing function ale#events#Init:
line   30:
E10: \ should be followed by /, ? or &
```
Googling for this kind of error got me to [this link](https://github.com/vim/vim/issues/3014), where it is suggested that some system wide settings might interfere with the vim config.   I have tried setting "set nocompatible" explicitely in my vimrc, this fixes the issue of multline statements in plugins, but then my airline (or lightline) status bars lose 256 colors and formatting.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim -u .vimrc` with the following .vimrc in some folder:
```
set packpath+=.

if empty(glob('.vim/autoload/plug.vim'))
  silent !curl -fLo .vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('.vim/plugged')

Plug 'itchyny/lightline.vim'
Plug 'dense-analysis/ale'
"Plug 'gruvbox-community/gruvbox'

call plug#end()


set laststatus=2
set autowrite
set signcolumn=yes
"set nocompatible

let g:lightline = {'colorscheme': 'wombat'}
```
Errors should appear immediately.
2. uncomment "set nocompatible" and restart
3. errors disappear but the lightline loses colors and formatting

**Environment (please complete the following information):**
 - Vim version:
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 23 2020 22:02:57)
Included patches: 1-814
Compiled by Arch Linux
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       +tcl/dyn
-autoservername    +folding           +multi_byte        +termguicolors
-balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
-browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              +perl/dyn          +title
-clientserver      +job               +persistent_undo   -toolbar
-clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           +python/dyn        +visual
+conceal           +linebreak         +python3/dyn       +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua/dyn           +ruby/dyn          +wildmenu
+dialog_con        +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
-dnd               +mouse             -sound             -xfontset
-ebcdic            -mouseshape        +spell             -xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              +mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
```
 - OS: ArchLinux (5.6.14-arch1)
 - Terminal: Alacritty

**Comment by chrisbra** [comment]
Looks like a configuration issue to me. What terminal are you using? Do you correctly configure $TERM?

**Comment by k-takata** [comment]
Try `:verbose set compatible?` to check which script sets it.

**Comment by chrisbra** [comment]
> Try :verbose set compatible? to check which script sets it.

If you start `vim -u ...` without `-N` vim will start in compatible mode. So it is expected to start in compatible mode.

**Comment by ambushed** [comment]
Thanks for your reactions:  My terminal is `alacritty 0.4.2`.  The TERM env var is set in my `.zshrc` to `xterm-256color`.  echo-ing $TERM in vim also gives the same value. 

I am aware that if there is a system vimrc (which, in Arch, there is) then the default setting is `compatible`.  This is why i tried setting `nocompatible` in my `.vimrc` explicitly.  This however, caused lightline (or airline, which i tried as well) to lose formatting and 256 colors.   

A peculiar thing is that if i run `:PlugInstall` (install plugins with vim-plug) and then close the split where the installation progress was reported, the colors jump back into normal and formatting returns **until** i create an new buffer.

**Comment by chrisbra** [comment]
I am not sure, `xterm-256color` is actually correct for alacritty. I believe alacritty comes with its own entry in the terminfo database see [this PR for alacritty](https://github.com/alacritty/alacritty/pull/1491). So try using `TERM=alacritty` or `TERM=alacritty-direct` for RGB colors. 

In any case, you can force 256 colors using `:set t_Co=256`. Or you use `:set termguicolors` should also work, I believe.

**Comment by ambushed** [comment]
Thanks for the `TERM` tip!  Sadly trying both suggestions didn't change a thing for me.  Also setting `t_Co=256` didn't have any impact.  `set termguicolors` has turned any coloring off altogether.

I have also tried `termite` as a terminal application and see the same behaviour

**Comment by ambushed** [comment]
What i find strange is that if i do `:e .` to open netrw buffer, my status line shows correct 256 colors and formatting.  It is lost again, once a file is loaded into a buffer.

**Comment by ambushed** [comment]
tried reproducing this issue in a docker image and couldn't!  I guess it must be my config that is somehow messed.  Closing the issue.
