### ISSUE TITLE
:term ++curwin doesn't unload current buffer

### ISSUE THREAD

**Issue by HarmtH** [vim/vim#6170]
**Describe the bug**
Without 'hidden' in use, a buffer should be unloaded when it's not displayed anymore. ```:term ++curwin``` hides the current buffer instead. This is annoying when you try to load the file in another Vim instance, as the swapfile still exists.

**To Reproduce**
```
vim --clean
:edit foo<cr>
:term ++curwin<cr>
<C-\><C-n>:ls<cr>
  1 #h   "foo"                          line 1
  2 %aR  "!/bin/bash [Terminal]"        line 1
```

**Expected behavior**
```foo``` is unloaded

**Workaround**
When using ```:enew | term ++curwin```, ```foo``` does get unloaded.

**Environment (please complete the following information):**
 - Vim version [e.g. 8.1.1234] 8.2.858

**Comment by brammool** [comment]
Harm te Hennepe wrote;

> **Describe the bug**
> Without 'hidden' in use, a buffer should be unloaded when it's not displayed anymore. ```:term ++curwin``` hides the current buffer instead. This is annoying when you try to load the file in another Vim instance, as the swapfile still exists.
> 
> **To Reproduce**
> ```
> vim --clean
> :edit foo<cr>
> :term ++curwin<cr>
> :<C-\><C-n>ls<cr>
>   1 #h   "foo"                          line 1
>   2 %aR  "!/bin/bash [Terminal]"        line 1
> ```
> 
> **Expected behavior**
> ```foo``` is unloaded
> 
> **Workaround**
> When using ```:enew | term ++curwin```, ```foo``` does get unloaded.

That indeed looks wrong.  There is a remark in the help about this
failing when the current buffer can't be abandoned, and this is
implemented in the code, but then the buffer always becomes hidden.

-- 
Get a life?  What is the URL where it can be downloaded?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
