### ISSUE TITLE
off by one error in column position of "getmarklist()"

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6173]
**Describe the bug**

The column position of a mark as reported by `getmarklist()` is off by one.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -i NONE +"sil pu!=['abc', 'def', 'ghi']" +'norm! 2G3|mm1G1|' +'call getmarklist(bufnr("%"))->filter({_,v -> v.mark =~# ".m"})[0].pos->setpos(".")'

This populates a buffer with the text:

    abc
    def
    ghi

Then, it sets the mark `m` on the character `f` (third character on second line), and moves the cursor back on the the character `a` (first character on first line).  Finally, it invokes `getmarklist()` to retrieve the position of the mark `m` and `setpos()` to restore the cursor where the mark was set originally (i.e. on the character `f`).

The cursor is positioned on the character `e`.

**Expected behavior**

The cursor is positioned on the character `f`.

**Environment**

 - Vim version: 8.2 Included patches: 1-869
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

According to `:h getmarklist()`, the `pos` key should have the same meaning as for `getpos()`:

> pos - a |List| with the position of the mark:
>             [bufnum, lnum, col, off]
>       Refer to |getpos()| for more information.

If that's the case, then we should be able to restore the cursor position without having to apply a positive offset on the column number.

---

Unrelated to this issue, but I've also noticed that `getmarklist()` can't be used as a method contrary to the similar functions `getjumplist()` and `getchangelist()`.  Let me know if you want me to open a new issue for that too.

**Comment by lacygoill** [comment]
To summarize, `getmarklist()` starts indexing the column positions from the index 0, while `getpos()` starts from 1, which seems inconsistent.

**Comment by vim-ml** [comment]
Hi,

On Sun, May 31, 2020 at 4:22 PM lacygoill <vim-dev-github@256bit.org> wrote:

> To summarize, getmarklist() starts indexing the column positions from the
> index 0, while getpos() starts from 1, which seems inconsistent.
>
>
>
Thanks for reporting this issue. I have created the following PR to address
this.

https://github.com/vim/vim/pull/6176

- Yegappan

**Comment by brammool** [comment]
Fixed by 8.2.0871.
