### ISSUE TITLE
Suggestion: treat filetype *.jl as Julia, not Sawfish Window Manager's scripting language

### ISSUE THREAD

**Issue by mwgkgk** [vim/vim#6178]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

The problem: [Julia](https://julialang.org/) source files use `*.jl` extension. Vim, under `/usr/share/vim/vim82/filetype.vim`, assigns `setf lisp` for `*.jl` files among other lisp filetypes.

Problem with this is that Lisp tooling is abundant and heavyweight, and so unloading it cleanly after the filetype has changed is problematic. `b:undo_ftplugin` comes to rescue to an extent, but some subtle artifacts remain, including loading the auto-loaded code that should stay dormant. Here's my `b:undo_ftplugin` for lisp:

```vim
let b:undo_ftplugin = 'setlocal comments< define< formatoptions< iskeyword< lisp<'
            \ . '| mapclear <buffer>'
```

**Describe the solution you'd like**

Daring yet confident solution would be to detect `*.jl` as Julia. A sufficient compromise would be to remove the `*.jl` detection as lisp and let the users decide.

**Additional context**

Julia has been sponsored by NASA, DARPA, Mozilla, and [others](https://en.wikipedia.org/wiki/Julia_(programming_language)#Sponsors). It's a rather high-profile project, with Julia Computing, Inc. [raising](https://en.wikipedia.org/wiki/Julia_(programming_language)#Julia_Computing) $4.7M in seed funding in June 2017.

[Sawfish](https://github.com/SawfishWM/sawfish) is a window manager configured in a dialect of Lisp, with 104 stars on Github and 33 contributors. It being first to use the extension certainly is worth considering, however this issue can be easily resolved without creating any discomfort for either side. It's been a [source](https://github.com/JuliaEditorSupport/julia-vim/issues/38) of [problems](https://github.com/JuliaEditorSupport/julia-vim/issues/64) in the past, and still remains a problem for Vim users who utilize both Lisp and Julia.

**Comment by brammool** [comment]
Julia support is not included in the distribution, thus recognizing *.jl as Julia isn't very useful, you need to add the runtime files anyway.
Writing Lisp file is not very common, it's fading away.  We can remove the detection of *.jl as Lisp.  it's easy enough to find another way to set the filetype for those few users who need it.
