### ISSUE TITLE
Codecov migration to marketplace app

### ISSUE THREAD

**Issue by thomasrockhu** [vim/vim#6181]
Hi, Tom from [Codecov](https://codecov.io) here.

We noticed that you are using Codecov with fairly high frequency, and we’re so excited to see that! However, because you are not using our app, you may have experienced issues with uploading reports or viewing coverage information. This is due to rate-limiting issues from GitHub.

**In order to prevent any future outages, we ask that you move over to our [GitHub app integration](https://github.com/apps/codecov).**

The process is extremely simple and shouldn’t require more than a few clicks, and you should not expect any downtime. By moving to our app, you will no longer need an admin or separate account to manage the relationship with GitHub as the team bot.

Let me know if you have any questions, or if I can help at all with this process.

**Comment by chrisbra** [comment]
@brammool I tried re-configuring, but apparently this must be done by the repo owner.

**Comment by brammool** [comment]
I did follow the link and clicked on buttons.  Did I miss something?

**Comment by chrisbra** [comment]
There seems to be there as an githup app now at least. @thomasrockhu can you confirm, it is setup correctly now? Thanks!

**Comment by thomasrockhu** [comment]
Looks good to me on our side! Thanks everyone!
