### ISSUE TITLE
"readdirex()" should return 0 for the size of a directory to match "getfsize()"

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6185]
**Describe the bug**

`readdirex()` returns -2 for the size of a directory, which is inconsistent with `getfsize()`.

**To Reproduce**

Run this shell command:

    vim -es -Nu NONE +'call mkdir("/tmp/dir", "p", 0700) | pu=readdirex(\"/tmp\", {e -> e.name is# \"dir\"})[0].size | %p | qa!'

It outputs -2.

**Expected behavior**

It outputs 0.

Just like this other shell command which evaluates `getfsize("/tmp/dir")`:

    vim -es -Nu NONE +'call mkdir("/tmp/dir", "p", 0700) | pu=getfsize(\"/tmp/dir\") | %p | qa!'

**Environment**

 - Vim version: 8.2 Included patches: 1-882
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

According to `:h readdirex()`, the `size` key should be identical to the output of `getfsize()`:

> size	Size of the entry. See |getfsize()|.

And according to `:h getfsize()`, 0 is returned for a directory:

> If {fname} is a directory, 0 is returned.

**Comment by k-takata** [comment]
I wonder why I didn't notice this.

```diff
--- a/src/fileio.c
+++ b/src/fileio.c
@@ -4575,7 +4575,7 @@ create_readdirex_item(char_u *path, char_u *name)
 	if (S_ISDIR(st.st_mode))
 	    size = 0;
 	// non-perfect check for overflow
-	if ((off_T)size != (off_T)st.st_size)
+	else if ((off_T)size != (off_T)st.st_size)
 	    size = -2;
 	if (dict_add_number(item, "size", size) == FAIL)
 	    goto theend;
```
