### ISSUE TITLE
Can't scroll the screen in terminal-job mode by `Shift+PgUp/PgDown` or mouse wheel

### ISSUE THREAD

**Issue by coiby** [vim/vim#6188]
**Describe the bug**

In xfce4-terminal or gnome-terminal, we can use `<Shift+PgDn/PgUp>` to scroll down/up the screen. When running terminal inside vim, `<Shift+PgDn/PgUp>` does nothing. `xinput test` shows `<Shift+PgDn/PgUp>` or mouse wheeling scrolling event has been already be passed to the screen.

**To Reproduce**
1. Run `vim -u DEFAULTS`
2. `:terminal`
3. Run a command to fill-up the whole screen in the launched terminal, for example,
   ```bash
   for i in `seq 1 200`; do echo $i; done
   ```
4.  Hit `<Shift+PgUp>`

**Expected behavior**

The screen should be scrolled up.

**Screenshots**

**Environment (please complete the following information):**
 - Vim version: VIM - Vi IMproved 8.2 (2019 Dec 12) Included patches: 1-717

 - OS: Manjaro 20.0.1
 - Terminal: xfce4-terminal

**Additional context**

In both insert and normal mode, we can use PgUp/Down or mouse wheel to scroll the screen. It would be nice we needn't to switch to terminal-normal first to scroll the screen.

If I run the following bash command,
```bash
for i in `seq 1 200`; do echo $i; done|less
```
I can use PgUp/Down to go back and forth. I don't know why the terminal itself can't go back and forth.

**Comment by brammool** [comment]
That is not supported, at least not yet.  You need to go to Terminal-Normal mode first.
There is a todo item to allow for scrolling.  Would be useful.

**Comment by coiby** [comment]
> That is not supported, at least not yet. You need to go to Terminal-Normal mode first.
> There is a todo item to allow for scrolling. Would be useful.

Thank you for the clarification. I thought vim somehow is using xfce4-terminal which supports scrolling via `Shift+PgDn/PgUp` so I reported this a bug. Actually vim implements its own terminal enumerator based on libvterm. So I should label it as "Feature request" instead.
