### ISSUE TITLE
searchcount() still recomputes when "recompute" is reset and "S" is in 'shm'

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6195]
**Describe the bug**

`searchcount()` still recomputes when the `recompute` key is reset and the `S` flag is in `'shortmess'`.

**To Reproduce**

Run this shell command:

    vim -es -Nu NONE -i NONE +"let @/ = '.' | pu!='xxxxx' | call feedkeys('n$', 'tx') | set vbs=1 | echo searchcount(#{recompute: 0}).current" +'qa!'

The output is 5.

**Expected behavior**

The output is 2, because the last time the `n` command was executed, the cursor was on the second `x` on the line, and the index of the current match for the pattern `.` was 2, not 5.

**Environment**

 - Vim version: 8.2 Included patches: 1-890
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

If you remove the `S` flag from `'shm'`, then `recompute: 0` correctly prevents `searchcount()` from recomputing the result:

                               vvvvvvvvvv
    vim -es -Nu NONE -i NONE +"set shm-=S | let @/ = '.' | pu!='xxxxx' | call feedkeys('n$', 'tx') | set vbs=1 | echo searchcount(#{recompute: 0}).current" +'qa!'

This time, the output is 2 not 5.

---

There is nothing at `:h 'shm'` which explains that the `S` flag has such an influence on `searchcount()`.  And `:h searchcount()` documents the `recompute` key like this:

> recompute	|Boolean|
> if |TRUE|, recompute the count like |n| or |N| was executed.
> otherwise returns the last result by |n|, |N|, or this function is returned.
> (default: |TRUE|)

Again, there is nothing which explains that the `S` flag has any influence on the effect of the key.

And the only place where `'shortmess'` is mentioned, explains that the function should work the same when `S` is in `'shm'`:

> Get or update the last search count, like what is displayed without the "S" flag in 'shortmess'.
> This works even if 'shortmess' does contain the "S" flag.

**Comment by brammool** [comment]
If you use "n" or "N" with "S" in 'shortmess' then there is no previous value computed.  The docs should mention this: 
 recompute	|Boolean|	if |TRUE|, recompute the count
						like |n| or |N| was executed.
						otherwise returns the last
						computed result (when |n| or
						|N| was used when "S" is not
						in 'shortmess', or this
						function was called).
						(default: |TRUE|)
