### ISSUE TITLE
clipboard register still used for a put even after removing "unnamedplus" from 'clipboard'

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6198]
**Describe the bug**

Sometimes, the clipboard register is still used for a put, even after `unnamedplus` has been removed from the `'clipboard'` option.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -i NONE -S <(cat <<'EOF'
        set cb=unnamedplus
        au VimEnter * let @+ = 'clipboard' | g/^/set cb= | let @" = 'unnamed' | pu
    EOF
    )

Vim puts the text `clipboard` in the buffer.

**Expected behavior**

Vim puts the text `unnamed` in the buffer, because `'clipboard'` has been emptied before `:put` was executed.

**Environment**

 - Vim version: 8.2 Included patches: 1-896
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

This creates a bug for a user which includes `unnamedplus` in their `'clipboard'` option, when they use [vim-surround](https://github.com/tpope/vim-surround), and I suspect when they use any plugin providing a custom operator.

For example, `g/pat/norm ysiw'`, which invokes the pseudo-operator `ys`, fails to surround with quotes the word `pat` in the current buffer.

---

Neovim is not affected; i.e. the same command works as expected:

    nvim -Nu NONE -i NONE -S <(cat <<'EOF'
        set cb=unnamedplus
        au VimEnter * let @+ = 'clipboard' | g/^/set cb= | let @" = 'unnamed' | pu
    EOF
    )

It correctly puts the text `unnamed` in the buffer, and not `clipboard`.

**Comment by chrisbra** [comment]
I believe this is actually a feature. For performance reasons, we disable access to the clipboard in `:g` (and alike) commands. This is because people have been reporting that e.g. `:g/^/d` on a multi-thousands line file slows vim considerably if the every yank operation is also synced to the clipboard.

Hm, now that I think about it, I believe the internal global clipboard setting after the `:g` command does not match the actual clipboard setting. That is indeed a bug.

I suppose we need this patch:

```patch
diff --git a/src/clipboard.c b/src/clipboard.c
index 7a35112d2..5db13a0d2 100644
--- a/src/clipboard.c
+++ b/src/clipboard.c
@@ -1317,7 +1317,12 @@ check_clipboard_option(void)
     }
     if (errmsg == NULL)
     {
-       clip_unnamed = new_unnamed;
+       if (global_busy)
+           // clip_unnamed will be reset to clip_unnamed_saved
+           // at end_global_changes
+           clip_unnamed_saved = new_unnamed;
+       else
+           clip_unnamed = new_unnamed;
        clip_autoselect_star = new_autoselect_star;
        clip_autoselect_plus = new_autoselect_plus;
        clip_autoselectml = new_autoselectml;
```

(will post a PR with a test later)

**Comment by lacygoill** [comment]
> For performance reasons, we disable access to the clipboard in :g (and alike) commands. This is because people have been reporting that e.g. :g/^/d on a multi-thousands line file slows vim considerably if the every yank operation is also synced to the clipboard.

Yes, I found the item in the todo list before posting:

> Setting 'clipboard' to "unnamed" makes a global command very slow (Daniel
> Drucker, 2017 May 8).

But I didn't find the explanation behind the slow down. Thank you for the explanation.

> I suppose we need this patch:

Can confirm that it fixes the issue; thank you very much for the quick fix.
