### ISSUE TITLE
mapped-prefix for another map no longer works in the GUI

### ISSUE THREAD

**Issue by lilydjwg** [vim/vim#6200]
**Describe the bug**
See below.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `gvim --clean`
2. Run `nmap ' <c-w>`
3. Run `nmap <c-w>a :echo a<CR>`
4. Type `'a`

Nothing happens. The pending `^W` clears. (Builtin commands work, i.e. `'c` closes the window.)

**Expected behavior**
The map `<c-w>a` is triggered and an error about undefined variable `a` should be reported.

**Environment (please complete the following information):**
 - Vim version 8.2.884
 - OS: Arch Linux
 - Terminal: GTK3 GUI

**Additional context**

f4ae6b245a54f11dd967d06b80f30e5abf55fb82 is the first bad commit

**Comment by lilydjwg** [comment]
Hi, mappings like `<c-w>a` work now, but `<c-w><c-a>` still does not work, i.e.

1. Run `gvim --clean`
2. Run `nmap ' <c-w>`
3. Run `nmap <c-w><c-a> :echo a<CR>`
4. Type `'<c-a>`

It doesn't work.

**Comment by brammool** [comment]
Well, you certainly know how to find the problems.
Son in this case there are two CTRL- keys.  Two entries will be added, one with simplified keys (using a single byte for each key) and one with the modifyOtherKeys variant, using a separate modifier.
But the way it's used results in the first key using a single byte, and the second one is typed, thus uses a separate modifier.  That doesn't match either variant of the mapping.
I think another solution will be needed, similar to how escape sequences are recognized, and they can be mapped both before and after the conversion to special keys.
