### ISSUE TITLE
command-line window and :au WinNew * smile

### ISSUE THREAD

**Issue by chrisbarber** [vim/vim#6211]
**Describe the bug**

After `smile` is run from within WinNew autocmd upon opening the command-line window, closing it results in report of SIGSEGV and vim going to 100% CPU.

**To Reproduce**

1. Open `vim` *in a terminal small enough to not accomodate the full `:smile` output*
2. Type `:au WinNew * smile`<cr>
3. Type `q:` or some other way of opening command line window
4. Press `q` to dismiss the smile
5. Type for example `:q`<cr>, or run a command in the command-line window; anything to dismiss the command-line window

**Expected behavior**

More smile, less CPU

**Environment (please complete the following information):**
 - vim 8.2.800
 - macOS 10.15.4
 - macOS Terminal Version 2.10 (433)

**Additional context**

Just thought this one was maybe interesting. I was just idly messing around. I tried and it's just the command-line windows, but horizontal and vertical splits, quickfix, and location windows are all fine. I don't know how `:smile` is implemented or if this actually generalizes to other things that print lots of output and thus show the less/more style `--more--` scrollable output. 

I did notice that when dismissing the "more" smile output, when vim comes back up it is lacking colors. Using a bigger terminal or eg scrolling down to the end of the smile output until it is exhausted and closes without issuing `q` both avoid the issue, so it is something to do with doing the dismissal partway through the output.

**Comment by lacygoill** [comment]
- [backtrace](https://github.com/vim/vim/files/4738245/backtrace.txt)
- [valgrind log](https://github.com/vim/vim/files/4738260/valgrind.log)
- [asan log](https://github.com/vim/vim/files/4738281/asan.log)

**Comment by brammool** [comment]
Interesting sequence of events.  Basic problem is that when opening the buffer for the cmdline window, there is no check that this fails.  Fixing that avoids the crash.
Still, interrupting the output at the More prompt should not have such a drastic effect, it aborts many things, such as splitting and closing windows.  Perhaps it's better to reset "got_int" after an autocommand when it was set because of a prompt.
