### ISSUE TITLE
Optional arg for readdirex()?

### ISSUE THREAD

**Issue by chdiza** [vim/vim#6214]
When I saw the new readdirex() function I jumped for joy.  Now instead of glob()-bing a dir and looping over the result and calling  getf*() etc. on each member, I can save time and just use readdirex().

However, the savings that readdirex() offers are often completely canceled out by the fact that readdirex() sorts its results case-sensitively while glob()  on macOS sorts its results case-insensitively.  Since I want case-insensitivity, I have to then call sort() on the results of readdirex() and use a custom sorting function (since readdirex() provides a list of dicts and not a list of filenames).  The overhead this adds eats up nearly all the savings that readdirex() brought, and indeed sometimes is a net loss depending on the filenames in the dir and how many filenames there are.  (I've looked at it with `:profile`.)

Can readdirex() be made to take an optional argument, which if present causes readdirex() to sort case-insensitively?

**Comment by vim-ml** [comment]
On 2020-06-06, chdiza wrote:
> When I saw the new readdirex() function I jumped for joy. Now instead of glob()
> -bing a dir and looping over the result and calling getf*() etc. on each
> member, I can save time and just use readdirex().
> 
> However, the savings that readdirex() offers are often completely canceled out
> by the fact that readdirex() sorts its results case-sensitively while glob() on
> macOS sorts its results case-insensitively. Since I want case-insensitivity, I
> have to then call sort() on the results of readdirex() and use a custom sorting
> function (since readdirex() provides a list of dicts and not a list of
> filenames). The overhead this adds eats up nearly all the savings that
> readdirex() brought, and indeed sometimes is a net loss depending on the
> filenames in the dir and how many filenames there are. (I've looked at it with
> :profile.)
> 
> Can readdirex() be made to take an optional argument, which if present causes
> readdirex() to sort case-insensitively?

I just wanted to point out that you probably don't want a strictly
case-insensitive sort, but rather a sort using a collation order
other than ASCII, perhaps the current locale's collation order.  It
doesn't matter in most cases, but would if you were sorting
a directory containing, for example, README and readme.

Regards,
Gary

**Comment by chdiza** [comment]
> but would if you were sorting a directory containing, for example, README and readme.

On macOS there can be no directory containing both README and readme.

**Comment by chrisbra** [comment]
> I just wanted to point out that you probably don't want a strictly
case-insensitive sort, but rather a sort using a collation order

So wouldn't it make sense to always sort according to the collation order?

**Comment by vim-ml** [comment]
On 2020-06-09, Christian Brabandt wrote:
>     I just wanted to point out that you probably don't want a strictly
>     case-insensitive sort, but rather a sort using a collation order
> 
> So wouldn't it make sense to always sort according to the collation order?

I guess so.  I had thought that some users might expect the sorting
to be in C/ASCII order regardless of their locale, but now I think
that seems unlikely for a list of files.  If they did expect that,
they would have set LC_COLLATE=C, which would then be their
collation order.

That's a long way of saying "yes".

That would be a simple change, if this is seen as a fix without
backwards compatibility issues.  Unless not all systems support
strcoll(3).

Regards,
Gary

**Comment by chrisbra** [comment]
>  That would be a simple change, if this is seen as a fix without
> backwards compatibility issues.  Unless not all systems support
> strcoll(3).

I started replacing strcmp by strcoll. Then I thought, it needs probably changes to configure. Then I noticed, if we start using `strcoll()` we probably need to be able to check this from vimscript using `v:vars` and also set it using the `:lang` command. So the patch is getting bigger and bigger :)

`readdirex()` is new enough, that I wouldn't worry about backwards incompatibility. But not sure, also not sure, if strcoll can be expected to be available everywhere, my manpage mentions its in C89, so perhaps this is a non-issue.

For windows, we are already using `strcoll()` but only for generating the prototypes.

**Comment by chdiza** [comment]
What I want is for the ordering to be the same as that of vim's glob() on a case-insenstive filesystem like what's on (the default) macOS.  If glob() doesn't use this "strcoll()", then neither does readdirex(), right?

On a lark (I don't know C) I replaced STRCMP (I think?) with STRICMP, and that appeared to produce the desired results.  Maybe that's a lucky accident and an artifact of the contents of the dirs I tested it on.

**Comment by chrisbra** [comment]
I tested this very briefly with PR: #6229

If I use `:lang collate C`, Vim will sort the result of `readdireex()` like this:

    'Foo.txt', 'G.txt', 'foo.txt', 'g.txt'

While with my German locale using `:lang collate de_DE` it will sort like this:

        'foo.txt', 'Foo.txt', 'g.txt', 'G.txt'

So that's what you want, isn't it?

**Comment by chdiza** [comment]
The order f, F, g, G is what I want, but it is not clear to me that that's what I will get unless I set some environment variable first.  On macOS $LC_COLLATE  and $LOCALE are empty.  I'm loath to change that because changing it caused problems in the past.  All I do in my shell profile is set LANG=en_US.UTF-8

Looking only at the docs of the PR and without having tested the PR, it would appear that on macOS vim will just assume "C" and then give "F,G,f,g" for the ordering, which is exactly the opposite of what I want.  (I will try to test the PR anyway just to see what happens.)

Moreover, I would hope that the results of readdirex() are sorted in a way that matches what we'd get by sorting (in vimscript) on the filenames using `>?` and `<?`.  Perhaps what this means is that I really do want a case-insensitive ordering and not a "collation"?

**Comment by vim-ml** [comment]
On 2020-06-09, chdiza wrote:
> The order f, F, g, G is what I want, but it is not clear to me that that's what
> I will get unless I set some environment variable first. On macOS $LC_COLLATE
> and $LOCALE are empty. I'm loath to change that because changing it caused
> problems in the past. All I do in my shell profile is set LANG=en_US.UTF-8

Setting LANG should be sufficient.  Check the output of the locale
command.  It should look like this.

    $ locale
    LANG=en_US.UTF-8
    LANGUAGE=
    LC_CTYPE="en_US.UTF-8"
    LC_NUMERIC="en_US.UTF-8"
    LC_TIME="en_US.UTF-8"
    LC_COLLATE="en_US.UTF-8"
    LC_MONETARY="en_US.UTF-8"
    LC_MESSAGES="en_US.UTF-8"
    LC_PAPER="en_US.UTF-8"
    LC_NAME="en_US.UTF-8"
    LC_ADDRESS="en_US.UTF-8"
    LC_TELEPHONE="en_US.UTF-8"
    LC_MEASUREMENT="en_US.UTF-8"
    LC_IDENTIFICATION="en_US.UTF-8"
    LC_ALL=

Yet none of those will show up in your environment unless you set
them.

> Looking only at the docs of the PR and without having tested the PR, it would
> appear that on macOS vim will just assume "C" and then give "F,G,f,g" for the
> ordering, which is exactly the opposite of what I want. (I will try to test the
> PR anyway just to see what happens.)
> 
> Moreover, I would hope that the results of readdirex() are sorted in a way that
> matches what we'd get by sorting (in vimscript) on the filenames using >? and
> <?. Perhaps what this means is that I really do want a case-insensitive
> ordering and not a "collation"?

If you simply ignore the case, then the sequences "f, F, g, G", "f,
F, G, g", "F, f, g, G", and "F, f, G, g" are all equivalent.  Vim's
internal sort is stationary, which means that items that compare the
same are left in the order in which they were found.  That means
that the results of your sort will depend on the original sequence.
That's probably not what you want.

Regards,
Gary

**Comment by chdiza** [comment]
> If you simply ignore the case, then the sequences "f, F, g, G", "f,F, G, g", "F, f, g, G", and "F, f, G, g" are all equivalent.  Vim's internal sort is stationary, which means that items that compare the same are left in the order in which they were found.  That means that the results of your sort will depend on the original sequence. That's probably not what you want.

I'm learning more than I thought I would!

The key (for me at least) is for the sorting of the results of readdirex() should match the the order that Vimscript's glob() produces.  If there's a mismatch there, then the speed benefits of readdirex() are washed out by the need to re-sort the results.

**Comment by chrisbra** [comment]
closed by 84cf6bd81bec93b49166cd48fccc7087fdbaa6fc

**Comment by chdiza** [comment]
Thanks so much for the patch!
