### ISSUE TITLE
c++ syntax should not highlight "restrict" keyword

### ISSUE THREAD

**Issue by anntzer** [vim/vim#623]
`restrict` is not a keyword in c++ even with say `g++ -std=gnu++14`.  Instead there are some compiler-specific extensions, e.g. `__restrict__`, which you may or may not want to highlight; in any case highlighting `restrict` in c++ files is wrong.

**Comment by mattn** [comment]
@brammool 

could you please fix like below?

``` diff
diff --git a/runtime/syntax/c.vim b/runtime/syntax/c.vim
index ac4909e..103044b 100644
--- a/runtime/syntax/c.vim
+++ b/runtime/syntax/c.vim
@@ -264,7 +264,7 @@ syn keyword cStorageClass   static register auto volatile extern const
 if exists("c_gnu")
   syn keyword  cStorageClass   inline __attribute__
 endif
-if !exists("c_no_c99")
+if !exists("c_no_c99") && s:ft !=# 'cpp'
   syn keyword  cStorageClass   inline restrict
 endif
 if !exists("c_no_c11")
```

**Comment by brammool** [comment]
Yasuhiro Matsumoto wrote:

> @brammool 
> 
> could you please fix like below?
> 
> ``` diff
> diff --git a/runtime/syntax/c.vim b/runtime/syntax/c.vim
> index ac4909e..103044b 100644
> --- a/runtime/syntax/c.vim
> +++ b/runtime/syntax/c.vim
> @@ -264,7 +264,7 @@ syn keyword   cStorageClass   static register auto volatile extern const
>  if exists("c_gnu")
>    syn keyword    cStorageClass   inline __attribute__
>  endif
> -if !exists("c_no_c99")
> +if !exists("c_no_c99") && s:ft !=# 'cpp'
>    syn keyword    cStorageClass   inline restrict
>  endif
>  if !exists("c_no_c11")
> ```

OK.

## 

hundred-and-one symptoms of being an internet addict:
191. You rate eating establishments not by the quality of the food,
     but by the availability of electrical outlets for your PowerBook.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mattn** [comment]
This should be closable.
