### ISSUE TITLE
Duplicate tag "E964"

### ISSUE THREAD

**Issue by rbtnn** [vim/vim#6232]
**Describe the bug**
Duplicate tag "E964" in eval.txt and textprop.txt.

__eval.txt__
![image](https://user-images.githubusercontent.com/1595779/84280940-eb44d680-ab72-11ea-8b82-9ea0c68367d7.png)

__textprop.txt__
![image](https://user-images.githubusercontent.com/1595779/84280979-f992f280-ab72-11ea-9af4-5ab6ed1db968.png)

**To Reproduce**
1. execute `:helptags ALL`

**Screenshots**
![image](https://user-images.githubusercontent.com/1595779/84280859-ce100800-ab72-11ea-83a3-b578d7601408.png)

**Environment (please complete the following information):**
 - Vim 8.2.944

**Comment by brammool** [comment]
That was the error number in the pull request, which I replaced when including it.  But forgot to make the same changes in the help.  Will do that now.
