### ISSUE TITLE
An addition to the description of ":!{cmd}" in the docs

### ISSUE THREAD

**Issue by lkintact** [vim/vim#6233]
Turns out the `:!{cmd}` command can accept ranges (e.g., `:2,5!xxd`, `:%!xxd -r` etc.), which isn't reflected in the docs at `:help !cmd`.

Vim 8.2.940.

**Comment by jamessan** [comment]
It's documented at `:help :range!`.

**Comment by lkintact** [comment]
@jamessan Thanks for pointing that out.
