### ISSUE TITLE
How do I change cursor for Yank, Delete, and Change?

### ISSUE THREAD

**Issue by carljohnson93** [vim/vim#6236]
I've used **gvim** for quite of time, but it became inconvenient since I work in a terminal most of the time, so I switched to terminal **vim** completely. One feature that I miss is a different cursor in different modes, including when yank/change/delete is waiting for a modifier. The following "settings", did the trick:
`~/.vimrc`
```vim
let &t_SI = "\<Esc>[6 q" "SI = INSERT mode                                  
let &t_SR = "\<Esc>[4 q" "SR = REPLACE mode                                 
let &t_EI = "\<Esc>[2 q" "EI = NORMAL mode
"  1 -> blinking block
"  2 -> solid block
"  3 -> blinking underscore
"  4 -> solid underscore
"  5 -> blinking vertical bar
"  6 -> solid vertical bar
```
It works. But that covers only the modes themselves, and I didn't found anything relative to yank/delete/change. What settings responsible for cursor change in the beforementioned events?

**Comment by tonymec** [comment]
hm… AFAIK, from a Vim point of view, when you've hit c y or d in Normal mode and are thinking about "until where" the command will apply, you are in "operator-pending" mode. In gvim, or in Vim in a Windows console, you could customize operator-pending mode cursor shape (for all operator-pending variants, not for y c d etc. separately) by means of the o: part of the `'guicursor'` option. AFAIK (and if someone knows better, please chime in) for Console Vim other than on Windows, you're out of luck.

However, by setting the `'showcmd'` option (which is set by defaults.vim) you can have Vim display a partial command (e.g. the c d or y we're talking about, and even a register if you specify one) near bottom right of the Vim screen.

Best regards,
Tony.

**Comment by chrisbra** [comment]
I don't think this is possible. Note that changing the cursor style is highly dependent on your terminal and might not universally work. If you insist on doing it, I would try a TextYankPost autocommand and inspect the `v:event` dictionary and act on the value of the `operator` key.

Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. Closing.
