### ISSUE TITLE
assert_true and assert_false functions do not accept v:false/v:true

### ISSUE THREAD

**Issue by ZyX-I** [vim/vim#625]
Consider the following script:

```
LANG=C vim -u NONE -i NONE -N --cmd 'call assert_true(v:true)' --cmd 'call assert_false(v:false)' --cmd 'echo v:errors' --cmd qa
```

this will echo

```
['pre-vimrc command line: Expected True but got v:true', 'pre-vimrc command line: Expected False but got v:false']
```

, but it is expected to echo `[]`.

**Comment by brammool** [comment]
Nikolai Pavlov wrote:

> Consider the following script:
> 
> LANG=C vim -u NONE -i NONE -N --cmd 'call assert_true(v:true)' --cmd 'call assert_false(v:false)' --cmd 'echo v:errors' --cmd qa
> 
> this will echo
> 
> ['pre-vimrc command line: Expected True but got v:true', 'pre-vimrc command line: Expected False but got v:false']
> 
> , but it is expected to echo [].

I'll fix that.

## 

Send $25.00 for handy leaflet on how to make money by selling leaflets

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///
