### ISSUE TITLE
<action>k moves cursor while <action>j does not

### ISSUE THREAD

**Issue by jxu023** [vim/vim#6250]
For example, the command >j will indent the current line and line below while leaving the cursor at the current line.
But, the command >k will indent the current line and the line above, while moving the cursor to the line above.

This difference in cursor movement is present in yank (perhaps other actions in general too?) and is more pronounced when using a count with the j or k motion.
e.g. y4j, y4k, >4j, >4k

When used with an action that deletes lines such as c or d, such as d4j vs d4k, this difference in cursor movement makes sense, but it feels less intuitive when this difference shows up in actions that don't delete the line.

**Comment by lacygoill** [comment]
This is documented at `:h operator`:

> After applying the operator the cursor is mostly left at the start of the text
> that was operated upon.  For example, "yfe" doesn't move the cursor, but "yFe"
> moves the cursor leftwards to the "e" where the yank started.

**Comment by lacygoill** [comment]
And also right below `:h ']`:

> After executing an operator the Cursor is put at the beginning of the text
> that was operated upon.  After a put command ("p" or "P") the cursor is
> sometimes placed at the first inserted line and sometimes on the last inserted
> character.  The four commands above put the cursor at either end.  Example:
> After yanking 10 lines you want to go to the last one of them: "10Y']".  After
> inserting several lines with the "p" command you want to jump to the lowest
> inserted line: "p']".  This also works for text that has been inserted.

**Comment by chrisbra** [comment]
works as intended.
