### ISSUE TITLE
Regression with undercurl color in terminal introduced by patch 8.2.941.

### ISSUE THREAD

**Issue by dpelle** [vim/vim#6254]
**Describe the bug**
Patch 8.2.941 introduces a regression in rendering of colored undercurl in the terminal.

**To Reproduce**
1) Open a xfce4-terminal or gnome-terminal
2) Go into the `vim/src` directory
2) Run this command:
```
$ vim --clean -c 'set spell termguicolors background=dark' -c 'let &t_Cs = "\e[4:3m"' -c 'let &t_Ce = "\e[4:0m"' -c 'hi SpellBad guisp=red gui=undercurl guifg=NONE guibg=NONE ctermfg=NONE ctermbg=NONE term=underline cterm=undercurl' main.c
```
3) Observe that misspelled words in comment have red undercurl (good so far).
4) Press `CTRL-L` and observe that the color of undercurl becomes blue i.e. color of comments (bug!).

The regression is introduced in:
```
commit 517f00f78893087d2f9d45768a5ba4dc48cb6856
Author: Bram Moolenaar <Bram@vim.org>
Date:   Wed Jun 10 12:15:51 2020 +0200

    patch 8.2.0941: detecting terminal properties is unstructured
    
    Problem:    Detecting terminal properties is unstructured.
    Solution:   Add a table with terminal properties.  Set properties when a
                terminal is detected.
```

**Expected behavior**
CTRL-L should not remove color of undercurl.

**Screenshots**
Screenshot before pressing CTRL-L:
![before-CTRL-L](https://user-images.githubusercontent.com/2261629/84587446-b90bd100-ae1f-11ea-963d-d6e806d77982.png)

Screenshot after pressing CTRL-L:
![after-CTRL-L](https://user-images.githubusercontent.com/2261629/84587452-bf01b200-ae1f-11ea-9005-4c4de1e9f08e.png)

**Environment**
 - Vim-8.2.941 or newer (Vim-8.2.940 was fine)
 - OS: xubuntu-18.04.4
 - gnome-terminal-3.28.2 or xfce4-terminal-0.8.7.4

**Comment by brammool** [comment]
Check for term_prop was using "== TPR_YES", should be "!= TPR_YES"
