### ISSUE TITLE
"++opt" in ":[range]r[ead] [++opt] !{cmd}" prevents "!{cmd}" completion

### ISSUE THREAD

**Issue by lkintact** [vim/vim#6258]
1. Run `gvim.exe --clean`
2. Start typing `:r ++enc=cp866 !edi`, then press <kbd>Tab</kbd>. gVim doesn't complete `edi` to `edit.com` (or probably something else, depending on the $PATH value) as it would, were there no `++enc=cp866` in the command.

 - Vim 8.2.981 (https://github.com/vim/vim-win32-installer/releases/download/v8.2.0981/gvim_8.2.0981_x86.zip)
 - OS: Windows 10 Home 1803
 - Terminal: GUI.

**Comment by lkintact** [comment]
@chrisbra Somehow the issue isn't fixed for me in gVim  [8.2.1042](https://github.com/vim/vim-win32-installer/releases/download/v8.2.1042/gvim_8.2.1042_x86.zip), reproducible with the same steps as in [post 1](https://github.com/vim/vim/issues/6258#issue-638502836). Please let me know if any additional info's required.

**Comment by chrisbra** [comment]
Hm, interesting, using `:r! ++arg cmd` works, but `:r ++arg !cmd` doesn't. I suppose the code only handles the former and not the latter. Will have a look.

**Comment by lkintact** [comment]
@chrisbra Thanks, it's fixed for me in [8.2.1145](https://github.com/vim/vim-win32-installer/releases/download/v8.2.1145/gvim_8.2.1145_x86_signed.zip). I may not understand something, but shouldn't the issue have been auto-closed?

**Comment by brammool** [comment]
Thanks for checking.
