### ISSUE TITLE
Missing comma before `but` in assert messages

### ISSUE THREAD

**Issue by ZyX-I** [vim/vim#626]
Consider the following script:

```
LANG=C vim -u NONE -i NONE -N --cmd 'call assert_false(v:true)' --cmd 'call assert_true(v:false)' --cmd 'echo v:errors' --cmd qa
```

this will echo

```
['pre-vimrc command line: Expected False but got v:true', 'pre-vimrc command line: Expected True but got v:false']
```

which is missing commas before `but`.

**Comment by ZyX-I** [comment]
> No commas are needed there nor should they be there.  The two
> clauses separated by the but are not independent.  See for example,
> 
> http://www.grammarly.com/handbook/punctuation/comma/23/comma-before-but/

They are independent: “Expected False” is a separate subsentense then “got v:true”, nothing will change even if you swap them: “Got v:true, but expected False”.

**Comment by chrisbra** [comment]
If I read grammar rules correctly one would need a subject in the subsentence to be truly independent, but I don't hink we should discuss english grammar here. Closing for now, as both versions seems to be widely used.
