### ISSUE TITLE
Drag on the window split bar is do not work when vim run in tmux

### ISSUE THREAD

**Issue by pangchol** [vim/vim#6260]
**Describe the bug**
Like title, drag on the window split bar is do not work when vim run in tmux.
note:
1. the same system enveriament and same reproduce step flow on tmux with neovim has no this issue.
2. the same system enveriament and same reproduce step flow on bash with vim has no this issue.

**To Reproduce**
1. Run `vim --clean`
2. Run `set mouse=a`
3. Run `split`
4. try use mouse drag on the window split bar

**Expected behavior**
the window do not resize when drag mouse

**Environment (please complete the following information):**
 - Vim version [ 8.2.0981] 
 - OS: [Ubuntu 18.04 LTS]
 - Terminal: [tmux 3.1]

**Additional context**
tmux 3.1 use with default config.

**Comment by lacygoill** [comment]
I can't reproduce:

![gif](https://user-images.githubusercontent.com/8505073/84663156-0f126e80-af1d-11ea-8a45-b8e47ea34839.gif)

Dragging the status line of the top Vim window with the mouse correctly resizes its height.

Try to reproduce on [tmux master](https://github.com/tmux/tmux#from-version-control), and without any tmux config:

    $ tmux -Lx -f/dev/null

**Comment by k-takata** [comment]
Try setting `:set ttymouse=sgr`.

**Comment by pangchol** [comment]
> Try setting `:set ttymouse=sgr`.

this settings let mouse drag work fine in tmux, thanks k-takata !
