### ISSUE TITLE
vim9script: Segmentation fault when running :import Foo from "foo.vim" in command-line mode

### ISSUE THREAD

**Issue by bfrg** [vim/vim#6271]
**Describe the bug**
Vim crashes when an exported `vim9script` function is imported in command-line mode with `:import`.

**To Reproduce**
1. Add the following to `~/.vim/import/foo.vim`:
```vim
vim9script
export def Foo(): number
    return 0
enddef
```
2. Run `vim -c "import Foo from 'foo.vim'"

Vim will crash with the following message:
```
Vim: Caught deadly signal SEGV
Segmentation fault
```

**Expected behavior**
Importing `vim9script` functions in command-line mode using `:import` should probably be disabled.

**Environment**
Vim version `8.2.983`

**Comment by lacygoill** [comment]
- [backtrace](https://github.com/vim/vim/files/4783180/backtrace.txt)
 - [valgrind log](https://github.com/vim/vim/files/4783181/valgrind.log)
 - [asan log](https://github.com/vim/vim/files/4783193/asan.log)
