### ISSUE TITLE
Current b:match_words does not work very well for vim9script functions

### ISSUE THREAD

**Issue by bfrg** [vim/vim#6276]
**Describe the bug**
The [current](https://github.com/vim/vim/blob/9af78769eeae0318e07aa8b6af4d6e2244481ca7/runtime/ftplugin/vim.vim#L85-L92) `b:match_words` for vimscript files does not work very well with `vim9script` functions. Pressing `%` (provided by `matchit`) won't jump to the next `enddef` when the cursor is on `return` inside a `:def` function.

The following patch seems to fix this (thanks to @andymass):
```diff
--- /tmp/vim.vim
+++ /usr/share/vim/vim82/ftplugin/vim.vim
@@ -83,7 +83,8 @@
 if exists("loaded_matchit")
   let b:match_ignorecase = 0
   let b:match_words =
-	\ '\<\%(fu\%[nction]\|def\)\>:\<retu\%[rn]\>:\<\%(endf\%[unction]\|enddef\)\>,' .
+	\ '\<fu\%[nction]\>:\<retu\%[rn]\>:\<endf\%[unction]\>,' .
+	\ '\<def\>:\<retu\%[rn]\>:\<enddef\>,' .
  	\ '\<\(wh\%[ile]\|for\)\>:\<brea\%[k]\>:\<con\%[tinue]\>:\<end\(w\%[hile]\|fo\%[r]\)\>,' .
 	\ '\<if\>:\<el\%[seif]\>:\<en\%[dif]\>,' .
 	\ '{:},' .
```
Affected by this are also other plugins utilizing `b:match_words`, see https://github.com/andymass/vim-matchup/issues/96.

**Environment**
Vim version `8.2.983`

**Comment by brammool** [comment]
Thanks.  I thought I tried this and it didn't work.  But your change (in reverse) appears to work.  I'll include it.

**Comment by chrisbra** [comment]
closing then.
