### ISSUE TITLE
breakindent cuts off parts of the buffer

### ISSUE THREAD

**Issue by louwers** [vim/vim#628]
When vim cannot show the entire visually indented part, it cuts off the buffer and shows `@' signs (**note**: _visually_ indented, with breakindent is enabled).

![screenshot_2016-02-08_01-02-04](https://cloud.githubusercontent.com/assets/649392/12876312/124d875e-ce00-11e5-81b7-061692bf829f.png)
No, this is not the end of the buffer. When the whole visually indented part is shown:
![screenshot_2016-02-08_01-02-39](https://cloud.githubusercontent.com/assets/649392/12876313/1ef379c8-ce00-11e5-9fb0-e73ec5a246e0.png)

This gets especially problematic when a visually indented part of the buffer is taller than the height of the window (nothing would be shown at all).

**Comment by vim-ml** [comment]
On Sunday, February 7, 2016 at 6:08:40 PM UTC-6, Bart wrote:

> When vim cannot show the entire visually indented part, it cuts off the buffer and shows `@' signs (note: visually indented, with breakindent is enabled).
> 
> No, this is not the end of the buffer. When the whole visually indented part is shown:
> 
> This gets especially problematic when a visually indented part of the buffer is taller than the height of the window (nothing would be shown at all).

Try setting the 'lastline' option. 

From :help window-contents:

If the last line in a window doesn't fit, Vim will indicate this with a '@' in
the first column of the last lines in the window, like this:

```
+-----------------------+
|first line     |
|second line        |
|@          |
|@          |
+-----------------------+
```

Thus the '@' lines indicate that there is a line that doesn't fit in the
window.

When the "lastline" flag is present in the 'display' option, you will not see
'@' characters at the left side of window.  If the last line doesn't fit
completely, only the part that fits is shown, and the last three characters of
the last line are replaced with "@@@", like this:

```
+-----------------------+
|first line     |
|second line        |
|a very long line that d|
|oesn't fit in the wi@@@|
+-----------------------+
```
