### ISSUE TITLE
"." does not repeat "zf"

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6280]
**Describe the bug**

The `zf` operator is not repeatable with the dot command.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        call setline(1, ['aaa', 'aaa', 'aaa', '', 'bbb', 'bbb', 'bbb'])
        norm! zfipG.
    EOF
    )

The `aaa` block is folded, but not the `bbb` block.

**Expected behavior**

The `aaa` block is folded, *and* the `bbb` block.

**Environment**

 - Vim version: 8.2 Included patches: 1-985
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

One could argue that it's not a bug because according to `:h .`, the dot command repeats a change:

> .                   Repeat last change, with count replaced with [count].

And when `'foldmethod'` is `manual`, the buffer is not changed.
Even so, I think it would make sense for `.` to repeat `zf` if you've reset `'foldmethod'` to `marker`; because in that case, `zf` does change the buffer.

---

It's not a big issue; as a workaround, one can install a simple wrapper around `zf`:

    nno <expr> zf Zf()
    nno <expr> zff Zf()..'_'
    xno <expr> zf Zf()
    fu Zf(...) abort
        if !a:0
            let &opfunc = 'Zf'
            return 'g@'
        endif
        '[,']fold
    endfu

But it would be nice if it worked without extra config.  Maybe via a flag in `'cpo'`?  We could use `z`, just like we can already include the `y` flag to repeat the `y` operator.

---

Unrelated to this issue, but I've also noticed that there was a convention affecting most builtin operators.
If you repeat its last key, it operates on the current line; e.g.:

    !!
    cc
    dd
    g??
    gww
    g~~
    ...

And if you prefix it with a count, it operates on the current line and the next ones; e.g.:

    12!! = filter current line and the next 11 ones
    34gww = format current line and the next 33 ones

But `zf` doesn't seem to respect this convention; i.e. if you press `12zff`, Vim does not fold the current line and the next 11 ones.  Maybe `123zff` should operate on the current line and the next ones, just like `123dd`?

**Comment by chrisbra** [comment]
> And when 'foldmethod' is manual, the buffer is not changed.
> Even so, I think it would make sense for . to repeat zf if you've reset 'foldmethod' to marker; because  in that case, zf does change the buffer.

Yes, I think the reason is precisely, because `zf` is not creating a change (if one omit the creation of foldmarkers) and I would certainly not expect `.` to repeat the last fold operation. Having `.` only repeat `zf`, if the foldmethod == `marker` would also be a bit inconsistent, so I would argue the current behavior is okay and changing it might be a backwards incompatible change.

The other issue with `<count>zf` however sounds reasonable, so basically `<count>zf` should behave like `<count>zF`. not sure why there are actually 2 commands for the same action.

**Comment by lacygoill** [comment]
> Yes, I think the reason is precisely, because zf is not creating a change (if one omit the creation of foldmarkers) and I would certainly not expect . to repeat the last fold operation.

I recently pressed `.` to repeat the creation of a fold, and was surprised it didn't work.  I think that's because I've wrongly internalized that `.` was meant to repeat any operator, while it's meant to repeat a change.  But while an operator *can* change the buffer, it's not necessarily the case.

I can see how it would be annoying for someone which pressed, let's say:

   - `dd` to delete a line
   - `zfip` to fold a paragraph
   - `.` to repeat the deletion of a line

to see Vim – instead – fold another paragraph.

This is why I suggested to add a flag in `'cpo'`, just like for `y`.  Although, that may not scale well if there are other requests in the future for other builtin operators which are not currently repeatable.  So, it may not be a good idea after all...

I'll just use a wrapper around the default `zf`; or maybe wait for this item in the todo list:

> -   Add command to repeat a whole mapping ("." only repeats the last change in
>     a mapping).

---

> The other issue with <count>zf however sounds reasonable, so basically <count>zf should behave like <count>zF. not sure why there are actually 2 commands for the same action.

Agree on both points.

So, I'll keep the issue open just for `<count>zf`.

**Comment by chrisbra** [comment]
> Add command to repeat a whole mapping ("." only repeats the last change in
a mapping).

Or perhaps have a way to get and set the dot register (and even previous actions if possible).

**Comment by brammool** [comment]
"zf" does not change the buffer, therefore it cannot be undone.
There is also no undo for changing an option value, even though it may change the displayed text.
Perhaps it would be useful to have a "go back in view history" command, but it would be quite difficult to implement.

**Comment by chrisbra** [comment]
@brammool  what about `{count}zf`?

**Comment by brammool** [comment]
{count}zf is incomplete, needs to be followed by a movement. E.g 5zfj

**Comment by chrisbra** [comment]
okay makes sense. Thanks.
