### ISSUE TITLE
PowerShell syntax

### ISSUE THREAD

**Issue by nu8** [vim/vim#6283]
it seems PowerShell syntax highlighting is not currently supported:

https://en.wikipedia.org/wiki/PowerShell

**Comment by chrisbra** [comment]
Yes, if you want to have a syntax, filetype and/or indent script bundled with Vim, best would be to find a maintained existing one and ask the upstream authors if they would like to send it to Bram for inclusion with Vim. 

If there does not exist one, well, here is your chance to contribute to a well-known Open Source Project and get all the fame ;)

**Comment by chrisbra** [comment]
This one looks to be maintained: https://github.com/PProvost/vim-ps1 You can ask the author if he would like to have it distributed with Vim then he should send it to Bram for inclusion with Vim (and give us explicit permission).

**Comment by chrisbra** [comment]
closing.

**Comment by nu8** [comment]
workaround:

<https://github.com/sheerun/vim-polyglot>

**Comment by chrisbra** [comment]
> https://github.com/sheerun/vim-polyglot

which uses the same Powershell plugin that I mentioned before. As said, if you want to have that included, ask the maintainer to submit those files to Bram for inclusion with Vim.
