### ISSUE TITLE
Empty writefile() blob touches Preexisting File 

### ISSUE THREAD

**Issue by dylnmc** [vim/vim#6287]
## Problem

Currently, it's impossible to `touch` a preexisting file and not add any bytes without calling back to the shell via `system('touch ...')` (etc).

Here is a list of calls that seemingly should update the file time, yet do nothing:
- `call writefile(0z, fileName, 'ab')`
- `call writefile(0z, fileName, 'a')`
- `call writefile([''], fileName, 'ab')`
- `call writefile([], fileName, 'a')`

Here is a list of calls that append 0x0a ("\n") to the end of the file (undesirable):
- `call writefile(['', ''], fileName, 'ab')`
- `call writefile([''], fileName, 'a')`

Also note that `call writefile(0z00, fileName, 'ab')` does not work, nor does using `0z04` or any other blob in place of `0z00`.

## Solution

When `writefile()` refuses to **append** any bytes or update a file's time because the blob being appended is empty, please update the file time. With this propsed change, `call writefile(0z, fileName, 'ab')` would update the time stamp on the file like `touch` in a shell on a unix system would.

Alternatively, there could be a `setftime()` function (like there is a `setfperm()` function).

**Comment by chrisbra** [comment]
Remember, Vim is not an operating system and for that particular use-case a `system('touch')` should be easily possible and not too expansive. So can you please explain, why you need this enhancement?

**Comment by brammool** [comment]
I don't think we want to change the behavior that when nothing is written, the last-changed time is left alone.  If you are asking for adding a function to do what the shell command "touch" does, I'm wondering what you need that for, and how it's related to text editing.

**Comment by dylnmc** [comment]
I am making a file browsing plugin for myself. None of the current implementations tickle my fancy. In the plugin, I am creating a buffer-local `:Touch` command that will mimic `touch` in a cross-platform manner. I know I can check `if executable('touch')` for instance (and another backup function in case `touch` is not an executable that will very unfortunately have to read in the entire file - let's hope it's not huge - and write the file again), but I am trying to do everything in vimscript as well as avoid making 2 functions - one good and fast and the other atrocious and slow on big files.

Since it seems like everyone is opposed to this, I will close the issue in a couple days should there either be no more comments on the issue or none of the positions change.

Thanks for your consideration.

---

*post adendum*

vim isn't an OS, but it does work directly with files, and since it's scriptable, it seems logical that it should easily be able to update a modification time for a file, which is one of the easiest things to do. This is important when working with Makefiles or other things that do, ineed, look at modification time stamps.

**Comment by mattn** [comment]
I'm not sure but why you don't use `call writefile([], fileName, 'ab')` ?

**Comment by dylnmc** [comment]
`call writefile([], fileName, 'ab')` will create a new file but not `touch` (update modification time) of a preexisting file.

**Comment by mattn** [comment]
Ah, I see. Windows does not have touch command. So you should use `copy file1.txt+` instead.

**Comment by dylnmc** [comment]
I also don't buy the argument for this case that "vim isn't an OS so it shouldn't be able to update modification time without adding bytes" because, well, vim already does it when it writes bytes with `:write`, `:update`, `:call writefile()`, etc, and all of that **is** OS-specific. Plus the function is already in the C code; it's just not exposed (even indirectly). I guess since it's not something anyone wants to patch and since it's of little importance, though, it's fine.

**Comment by dylnmc** [comment]
WONTFIX

**Comment by nickspoons** [comment]
The usecase I was thinking of was that of filewatchers triggering builds/tests etc., where it makes sense to me to be able to purposefully `:w` to update the file's timestamp.

The documentation for `:w` and `:wa` start like this:

    :w[rite] [++opt]	Write the whole buffer to the current file.

    :wa[ll]			Write all changed buffers.

From this, I would have expected that `:wa` would _not_ affect unmodified buffers (as is the case), but `:w` _would_ actually write the file, and therefore update the timestamp. It was surprising to me to read this issue and discover that that is not what happens.

**Comment by brammool** [comment]
:w does write the file, also when it is unchanged.  Thus it can be used to update the timestamp, but in a rather inefficient way.

**Comment by nickspoons** [comment]
Ah, I misunderstood, apologies.
