### ISSUE TITLE
vim.org MX is down

### ISSUE THREAD

**Issue by 532910** [vim/vim#6288]
It's impossible to send letters to vim@vim.org as jail.42.org 46.41.23.236 is down.

https://groups.google.com/forum/#!forum/vim_use shows the last letter was received on Jun 15.

I did not find any information about this.
IRC says nothing.

**Comment by tonymec** [comment]
> It's impossible to send letters to [vim@vim.org](mailto:vim@vim.org) as jail.42.org 46.41.23.236 is down.
> 
> https://groups.google.com/forum/#!forum/vim_use shows the last letter was received on Jun 15.
> 
> I did not find any information about this.
> IRC says nothing.

vim@vim.org was the old mailing list. The new mailing lists are mirrored on Google Groups:

vim_use for normal user support
vim_dev for software bugs and bugfixes
vim_mac for problems specific to the Mac
All of them @googlegroups.com

Be patient the first time you post, because the only way we could keep the list reasonably spam-free was to have everyone's first post checked by a human moderator.

Best regards,
Tony.

**Comment by 532910** [comment]
So https://www.vim.org/community.php and https://www.vim.org/maillist.php MUST be updated!

**Comment by chrisbra** [comment]
no vim@vim.org is still used IIRC, but as Tony said, it is mirroed to googlegroups.

**Comment by brammool** [comment]
> jail.42.org 46.41.23.236 is down

I have been trying to contact the sysadmin, no success so far.
That his email is also on 42.org doesn't help...

-- 
There are 10 kinds of people: Those who understand binary and those who don't.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by 532910** [comment]
What is the reason for a separate MX, while it's possible to use google's MX for vim.org, isn't it?

**Comment by chrisbra** [comment]
> What is the reason for a separate MX, while it's possible to use google's MX for vim.org, isn't it?

Not that it maters, but I think this comes from a time, when it was not so easy to setup.

**Comment by chrisbra** [comment]
I just got notification, that this should have been fixed yesterday around 9pm CEST

Closing.
