### ISSUE TITLE
vim9script: Segmentation fault when a :def function contains nested if-statements

### ISSUE THREAD

**Issue by bfrg** [vim/vim#6289]
**Describe the bug**
Vim crashes when a `vim9script` function contains nested if-statements.

**To Reproduce**
Run `vim --clean -S tmp.vim` with
```vim
" tmp.vim
vim9script
def Test(i: number)
    let x: number = 0
    if i % 2
        if 1
            " comment
        else
            " comment
        endif
        x += 1
    else
        x += 1000
    endif
enddef
defcompile
```
Output:
```
Vim: Caught deadly signal SEGV
Vim: Finished.
Segmentation fault
```

When the `x += 1000` is removed the function compiles.

**Environment**
Vim version `8.2.998`

**Comment by bfrg** [comment]
The function also compiles when the nested if-statement is removed:
```vim
vim9script
def Test(i: number)
    let x: number = 0
    if i % 2
        x += 1
    else
        x += 1000
    endif
enddef
defcompile
```

**Comment by lacygoill** [comment]
- [backtrace](https://github.com/vim/vim/files/4797531/backtrace.txt)
- [valgrind log](https://github.com/vim/vim/files/4797532/valgrind.log)
- [asan log](https://github.com/vim/vim/files/4797530/asan.log)

**Comment by lacygoill** [comment]
Fixed by https://github.com/vim/vim/commit/72abcf42d4b28719863c3bdf72b4c05d147a7d83.
