### ISSUE TITLE
Sentence movement breaks if line starts with single or double quote

### ISSUE THREAD

**Issue by ghost** [vim/vim#6291]
**vim-8.2.0814
Archlinux
Alacritty**

Moving with `)` gets stuck at single/double quote when it's at start of line:

```
Hello world.
"Hello world".
Hello world.
```

Reproduce: `gg))`: the cursor doesn't move past the second sentence.

**Comment by lacygoill** [comment]
I don't know whether it's working as intended or a regression, but the current behavior started from https://github.com/vim/vim/commit/8516071124dbb7ad7caa43cc98ae3c57ae093c9e.
