### ISSUE TITLE
vim instances in screen session windows crashing

### ISSUE THREAD

**Issue by OSS542** [vim/vim#6296]
The following was run using vim 8.1 running under Linux with kernel 5.7.   The bash shell was used.

```
cd temp # at initial terminal
#
sess=test
screen -d -m -S "$sess" -T xterm -U -t "$sess" # create session
xterm -T "$sess" -e screen -x "$sess" -p "$sess" &
#
title=title1 fpath=~/temp/file1
screen -S "$sess" -X screen -t "$title" vim "$fpath"
xterm -T "$title" -e screen -x "$sess" -p "$title" &
#
title=title2 fpath=~/temp/file2
screen -S "$sess" -X screen -t "$title" vim "$fpath"
xterm -T "$title" -e screen -x "$sess" -p "$title" &
#
exit # at initial terminal
#
# wait a few seconds
# click in the vim windows and the vim instances will crash
```

**Comment by chrisbra** [comment]
Please first try with the latest Vim. If it still crashes, cocmpile a debug version and get a stacktrace where it crashes.

**Comment by OSS542** [comment]
Just built 8.2 which I think is the latest stable, and carried out quite a bit of testing.  It seems to be working without any problems so far.   I'm afraid I'll just have to find something else to complain about.....:-)
