### ISSUE TITLE
not easy for a popup filter to handle "<M-S-a>" when modifyOtherKeys is enabled

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6298]
**Describe the bug**

It is not easy for a popup filter to handle a chord using the alt and shift modifiers when modifyOtherKeys is enabled.

**To Reproduce**

Open an xterm terminal, and run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        exe "set <m-s-a>=\eA"
        fu s:popup_filter(winid, key)
            if a:key is# "\<m-s-a>"
                call s:setheight(a:winid)
                return v:true
            endif
            return v:false
        endfu
        fu s:setheight(winid)
            let s:height = get(s:, 'height', 1) + 1
            call popup_setoptions(a:winid, #{minheight: s:height})
        endfu
        call popup_create('test', #{
            \ filter: function('s:popup_filter'),
            \ filtermode: 'n',
            \ mapping: v:false,
            \ })
    EOF
    )

Press `M-S-a` (that is `Alt` + `Shift` + `a`): nothing happens.

**Expected behavior**

The height of the popup window is increased by 1.

**Environment**

 - Vim version: 8.2 Included patches: 1-1009
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

The issue is specific to a terminal where modifyOtherKeys is enabled, and to the GUI (which AFAICT uses a similar feature).

In a terminal where modifyOtherKeys is disabled, the popup filter handles `<M-S-a>` just fine.

---

Here are the sequences of bytes received by the popup filter in various environments:

                                                   ┌────────────────────────┐
                                                   │         chords         │
                                                   ├───────┬────────────────┤
                                                   │  M-a  │     M-S-a      │
    ┌─────────────┬────────────────────────────────┼───────┼────────────────┤
    │             │ gnome-terminal                 │ c3 a1 │          c3 81 │
    │             ├────────────────────────────────┼───────┼────────────────┤
    │             │ xterm modifyOtherKeys disabled │ c3 a1 │          c3 81 │
    │ environment ├────────────────────────────────┼───────┼────────────────┤
    │             │ xterm modifyOtherKeys enabled  │ c3 a1 │ 80 fc 02 c3 81 │
    │             ├────────────────────────────────┼───────┼────────────────┤
    │             │ GUI                            │ c3 a1 │ 80 fc 02 c3 81 │
    └─────────────┴────────────────────────────────┴───────┴────────────────┘

Notice how the two cells in the bottom-right corner of the table are different.

It seems inconsistent.  I would expect this table instead:

                                                   ┌───────────────┐
                                                   │    chords     │
                                                   ├───────┬───────┤
                                                   │  M-a  │ M-S-a │
    ┌─────────────┬────────────────────────────────┼───────┼───────┤
    │             │ gnome-terminal                 │ c3 a1 │ c3 81 │
    │             ├────────────────────────────────┼───────┼───────┤
    │             │ xterm modifyOtherKeys disabled │ c3 a1 │ c3 81 │
    │ environment ├────────────────────────────────┼───────┼───────┤
    │             │ xterm modifyOtherKeys enabled  │ c3 a1 │ c3 81 │
    │             ├────────────────────────────────┼───────┼───────┤
    │             │ GUI                            │ c3 a1 │ c3 81 │
    └─────────────┴────────────────────────────────┴───────┴───────┘

Because of this inconsistency, inside a popup filter, you can't handle a chord using the `M-` and `S-` modifiers with the expected notation if modifyOtherKeys is enabled:

    if a:key is# "\<m-s-a>"
                 ^^^^^^^^^^
                     ✘

Instead, you need to write this:

    if a:key is# "\x80\xfc\x02\<m-s-a>"

Ideally, we should not need this `\x80\xfc\x02` prefix.  But if there's really no way around it, at least we should have a way to get it programmatically (in case it can vary from a terminal to another).  I don't know how to get it.  I've tried to use the new `\<*xxx>` notation documented at `:h expr-quote`:

> \<*xxx> Like \<xxx> but prepends a modifier instead of including it in the
>         character.  E.g. "\<C-w>" is one character 0x17 while "\<*C-w>" is four
>         bytes: 3 for the CTRL modifier and then character "W".

But it doesn't give me the whole byte sequence; only the first 2 match:

    vim -es -Nu NONE +'call writefile(["\<*m-s-a>"], "/tmp/byteseq", "b") | .!xxd /tmp/byteseq' +'%p | qa!'
    00000000: 80fc 0041                                ...A
              ^^^^ ^^
              ✔    ✘
                   I need 02

**Comment by brammool** [comment]
> **Describe the bug**
> 
> It is not easy for a popup filter to handle a chord using the alt and shift modifiers.
> 
> **To Reproduce**
> 
> Open an xterm terminal, and run this shell command:
> 
>     vim -Nu NONE -S <(cat <<'EOF'
>         exe "set <m-s-a>=\eA"

This isn't relevant.

>         fu s:popup_filter(winid, key)
>             if a:key is# "\<m-s-a>"

Should use "==" instead of "is#".

>                 call s:setheight(a:winid)
>                 return v:true
>             endif
>             return v:false
>         endfu
>         fu s:setheight(winid)
>             let s:height = get(s:, 'height', 1) + 1
>             call popup_setoptions(a:winid, #{minheight: s:height})
>         endfu
>         call popup_create('test', #{
>             \ filter: function('s:popup_filter'),
>             \ filtermode: 'n',
>             \ mapping: v:false,
>             \ })
>     EOF
>     )
> 
> Press `M-S-a` (that is `Alt` + `Shift` + `a`): nothing happens.
> 
> **Expected behavior**
> 
> The height of the popup window is increased by 1.
> 
> **Environment**
> 
>  - Vim version: 8.2 Included patches: 1-1009
>  - OS: Ubuntu 16.04.6 LTS
>  - Terminal: XTerm(322)
> 
> **Additional context**
> 
> The issue is specific to a terminal where modifyOtherKeys is enabled,
> and to the GUI (which AFAICT uses a similar feature).
> 
> In a terminal where modifyOtherKeys is disabled, the popup filter
> handles `<M-S-a>` just fine.
> 
> ---
> 
> Here are the sequence of bytes received by the popup filter in various environments:
> 
>                                                    ┌────────────────────────┐
>                                                    │         chords         │
>                                                    ├───────┬────────────────┤
>                                                    │  M-a  │     M-S-a      │
>     ┌─────────────┬────────────────────────────────┼───────┼────────────────┤
>     │             │ gnome-terminal                 │ c3 a1 │          c3 81 │
>     │             ├────────────────────────────────┼───────┼────────────────┤
>     │             │ xterm modifyOtherKeys disabled │ c3 a1 │          c3 81 │
>     │ environment ├────────────────────────────────┼───────┼────────────────┤
>     │             │ xterm modifyOtherKeys enabled  │ c3 a1 │ 80 fc 02 c3 81 │
>     │             ├────────────────────────────────┼───────┼────────────────┤
>     │             │ GUI                            │ c3 a1 │ 80 fc 02 c3 81 │
>     └─────────────┴────────────────────────────────┴───────┴────────────────┘
> 
> Notice how the two cells in the bottom-right corner of the table are
> different.
> 
> It seems inconsistent.  I would expect this table instead:
> 
>                                                    ┌───────────────┐
>                                                    │    chords     │
>                                                    ├───────┬───────┤
>                                                    │  M-a  │ M-S-a │
>     ┌─────────────┬────────────────────────────────┼───────┼───────┤
>     │             │ gnome-terminal                 │ c3 a1 │ c3 81 │
>     │             ├────────────────────────────────┼───────┼───────┤
>     │             │ xterm modifyOtherKeys disabled │ c3 a1 │ c3 81 │
>     │ environment ├────────────────────────────────┼───────┼───────┤
>     │             │ xterm modifyOtherKeys enabled  │ c3 a1 │ c3 81 │
>     │             ├────────────────────────────────┼───────┼───────┤
>     │             │ GUI                            │ c3 a1 │ c3 81 │
>     └─────────────┴────────────────────────────────┴───────┴───────┘
> 
> Because of this inconsistency, inside a popup filter, you can't handle a chord using the `M-` and `S-` modifiers with the expected notation:
> 
>     if a:key is# "\<m-s-a>"
>                  ^^^^^^^^^^
>                      ✘
> 
> Instead, you need to write this:
> 
>     if a:key is# "\x80\xfc\x02\<m-s-a>"
> 
> Ideally, we should not need this `\x80\xfc\x02` prefix.  But if
> there's really no way around it, at least we should have a way to get
> it programmatically (in case it can vary from a terminal to another).
> I don't know how to get it.  I've tried to use the new `\<*xxx>`
> notation documented at `:h expr-quote`:
> 
> > \<*xxx> Like \<xxx> but prepends a modifier instead of including it in the
> >         character.  E.g. "\<C-w>" is one character 0x17 while "\<*C-w>" is four
> >         bytes: 3 for the CTRL modifier and then character "W".
> 
> But it doesn't give me the whole byte sequence; only the first 2 match:
> 
>     vim -es -Nu NONE +'call writefile(["\<*m-s-a>"], "/tmp/byteseq") | .!xxd /tmp/byteseq' +'%p | qa!'
>     00000000: 80fc 0041 0a                             ...A.
>               ^^^^ ^^
>               ✔    ✘
>                    I need 02

Hmm, I first thought of fixing this for the popup filter, but it should
probably be fixed much deeper down, where the modifyOtherKeys sequence
is detected.  It already removes the shift modifier when it looks like
it is included in the key.  E.g. for "A" we do get the shift modifier,
as if <S-a> was used, but the modifier is already included in the key.

We can do this also when the Alt or Meta modifier is present.  It looks
like everything works, only the termcodes test has a failure.  Need to
figure that out...

-- 
TIM: To the north there lies a cave,  the cave of Caerbannog, wherein, carved
     in mystic runes, upon the very living rock, the last words of Olfin
     Bedwere of Rheged make plain the last resting place of the most Holy
     Grail.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> This isn't relevant.

You're right, but I let it inside the code so that you could check that when disabling modifyOtherKeys, then the popup filter was able to handle `<M-S-a>`, and that the issue was not that my code was broken for some other reason.  And when you disable modifyOtherKeys, then you do need this line.

> Should use "==" instead of "is#".

I have the habit of using `is#` for a string comparison to avoid [this pitfall](https://github.com/Vimjas/vint/issues/233).  It's not necessary here, but I do it to be consistent; I rarely, if ever, need/want a coercion from string to number.

I'll try to lose this habit.

**Comment by lacygoill** [comment]
Fixed by https://github.com/vim/vim/commit/20298ce679dbf21c07c8fe2161724a12424f1e69.

**Comment by lacygoill** [comment]
> Fixed by https://github.com/vim/vim/commit/20298ce679dbf21c07c8fe2161724a12424f1e69.

Looks like I talked too fast, sorry.

The issue is indeed fixed in a terminal where modifyOtherKeys is enabled, but not in the GUI.

Minimal example:

    vim -Nu NONE -g -S <(cat <<'EOF'
        fu s:popup_filter(winid, key)
            if a:key == "\<m-s-a>"
                call s:setheight(a:winid)
                return v:true
            endif
            return v:false
        endfu
        fu s:setheight(winid)
            let s:height = get(s:, 'height', 1) + 1
            call popup_setoptions(a:winid, #{minheight: s:height})
        endfu
        call popup_create('test', #{
            \ filter: function('s:popup_filter'),
            \ filtermode: 'n',
            \ mapping: v:false,
            \ })
    EOF
    )

Press `M-S-a` and observe how the height of the popup window is not increased, while it should.

The issue is the same; 3 extra bytes – `\x80\xfc\x02` – are prepended in front of `M-S-a`.

---

In case it helps, I'm using gtk2, and I configure Vim like this before the compilation:

    ./configure  \
      --enable-fail-if-missing       \
      --enable-gui=gtk2              \
      --enable-luainterp=dynamic     \
      --enable-python3interp=dynamic \
      --prefix=/usr/local            \
      --with-compiledby=user         \
      --with-luajit

Let me know if you want me to open a new separate issue.

**Comment by brammool** [comment]
> > Fixed by https://github.com/vim/vim/commit/20298ce679dbf21c07c8fe2161724a12424f1e69.
> 
> Looks like I talked too fast, sorry.
> 
> The issue is indeed fixed in a terminal where modifyOtherKeys is enabled, but not in the GUI.
> 
> Minimal example:
> 
>     vim -Nu NONE -g -S <(cat <<'EOF'
>         fu s:popup_filter(winid, key)
>             if a:key == "\<m-s-a>"
>                 call s:setheight(a:winid)
>                 return v:true
>             endif
>             return v:false
>         endfu
>         fu s:setheight(winid)
>             let s:height = get(s:, 'height', 1) + 1
>             call popup_setoptions(a:winid, #{minheight: s:height})
>         endfu
>         call popup_create('test', #{
>             \ filter: function('s:popup_filter'),
>             \ filtermode: 'n',
>             \ mapping: v:false,
>             \ })
>     EOF
>     )
> 
> Press `M-S-a` and observe how the height of the popup window is not increased, while it should.
> 
> The issue is the same; 3 extra bytes – `\x80\xfc\x02` – are prepended in front of `M-S-a`.
> 
> ---
> 
> In case it helps, I'm using gtk2, and I configure Vim like this before the compilation:
> 
>     ./configure  \
>       --enable-fail-if-missing       \
>       --enable-gui=gtk2              \
>       --enable-luainterp=dynamic     \
>       --enable-python3interp=dynamic \
>       --prefix=/usr/local            \
>       --with-compiledby=user         \
>       --with-luajit
> 
> Let me know if you want me to open a new separate issue.

It's tricky.  I'll fix it for GTK.  It looks like every GUI has slightly
different code to deal with modifier keys, each one has to be checked
separately.  I could try to unify the code, but since I can't check for
each GUI if it works it might as well cause more problems.

-- 
The Law of VIM:
For each member b of the possible behaviour space B of program P, there exists
a finite time t before which at least one user u in the total user space U of
program P will request b becomes a member of the allowed behaviour space B'
(B' <= B).
In other words: Sooner or later everyone wants everything as an option.
                                        -- Vince Negri

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
Fixed by https://github.com/vim/vim/commit/ef6746f637adbdb6860b4fa0266c43c49fa498bc.  Thank you very much.
