### ISSUE TITLE
Umlauts are not properly inserted into built in :terminal (gvim)

### ISSUE THREAD

**Issue by jchtt** [vim/vim#6304]
**Describe the bug**
When using a German keyboard layout including umlauts (äöü), these characters are not properly inserted into the gvim built in terminal mode. Instead, some other bash commands are executed.

**To Reproduce**
Detailed steps to reproduce the behavior:

This assumes the OS is linux.
1. Run `setxkbmap de`
2. Run `export LC_ALL=de_DE.UTF-8`
2. Run `gvim --clean`
3. Run `:terminal`
4. Type `ä` (which is on the quote/doublequote key on the US layout). Nothing happens.
5. Type `ä` again. An `Ã` gets inserted.

**Expected behavior**
An `ä` should be inserted instead.

**Environment (please complete the following information):**
 - Vim version
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 23 2020 22:02:57)
Included patches: 1-814
Compiled by Arch Linux
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       +tcl/dyn
-autoservername    +folding           +multi_byte        +termguicolors
+balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
+browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              +perl/dyn          +title
+clientserver      +job               +persistent_undo   +toolbar
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           +python/dyn        +visual
+conceal           +linebreak         +python3/dyn       +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua/dyn           +ruby/dyn          +wildmenu
+dialog_con_gui    +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       +X11
+dnd               +mouse             +sound             -xfontset
-ebcdic            +mouseshape        +spell             +xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              +mouse_gpm         +statusline        +xsmp_interact
+ex_extra          -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/at-spi-2.0 -pthread    -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -D_REENTRANT  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.30/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lz -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0  -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lelf    -lcanberra  -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.30/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/5.30/core_perl/CORE -lperl -lpthread -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm     
```
 - OS: Archlinux, with up-to-date dependencies for the above vim version
 - Terminal: GUI

**Additional context**
This problem does not appear in a regular buffer.

If `LC_ALL=C` is set, the behavior is different, but also wrong. In this case, the `ä` key capitalizes the letter under the cursor and moves one word forward, so it seems like `<M-c>` is issued instead.

Moreover, the problem it is not present in the last version of gvim that I have access to, which is 8.2.0510-2, when using an UTF-8 locale. But I get the same undesired behavior when `LC_ALL=C`.

**Comment by lacygoill** [comment]
> VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 23 2020 22:02:57)
> Included patches: 1-814

Can you reproduce on master?  In particular make sure you have the patch [8.2.0851](https://github.com/vim/vim/releases/tag/v8.2.0851).

**Comment by jchtt** [comment]
> Can you reproduce on master? In particular make sure you have the patch 8.2.0851.

I just checked on the current master, that is:
```
Included patches: 1-1023
```

I get the same behavior. Also note that the problem is exclusive to gvim, terminal vim is fine.

**Comment by lacygoill** [comment]
Does it help if you press a chord using the control modifier (e.g. `<C-L>`) at least once before opening `:terminal`?  I ask because of the issue https://github.com/vim/vim/issues/5951.

---

Can you check whether an input method option has an influence on the issue?

You can find a list of them by executing the command `:opt`.  It should open a window with all Vim options.  In particular, have a look at the section `24 language specific`; it contains these options:

    imdisable       when set never use IM; overrules following IM options
    iminsert        in Insert mode: 1: use :lmap; 2: use IM; 0: neither
    imstyle         input method style, 0: on-the-spot, 1: over-the-spot
    imsearch        entering a search pattern: 1: use :lmap; 2: use IM; 0: neither
    imcmdline       when set always use IM when starting to edit a command line
    imstatusfunc    function to obtain IME status
    imactivatefunc  function to enable/disable IME

I think the most interesting ones are `'imdisable'`, `'iminsert'`, `'imstyle'` and maybe `'imcmdline'`.  Note that the window is interactive; its usage is documented at the top:

    " Each "set" line shows the current value of an option (on the left).
    " Hit <CR> on a "set" line to execute it.
    "            A boolean option will be toggled.
    "            For other options you can edit the value before hitting <CR>.
    " Hit <CR> on a help line to open a help window on this option.
    " Hit <CR> on an index line to jump there.
    " Hit <Space> on a "set" line to refresh it.

---

If you want to be exhaustive, and try all possible combinations, source this code in Vim:

    let counter = 0
    for imdisable in ['imdisable', 'noimdisable']
        for iminsert in ['iminsert=0', 'iminsert=1', 'iminsert=2']
            for imstyle in ['imstyle=0', 'imstyle=1']
                for imcmdline in ['imcmdline', 'noimcmdline']
                    let counter += 1
                    call writefile([printf('set %s %s %s %s', imdisable, iminsert, imstyle, imcmdline)],
                       \ '/tmp/.test.'..printf('%02d', counter)..'.vim')
                endfor
            endfor
        endfor
    endfor

It should create 24 minimal vimrc files with all possible combinations of values for the options `'imdisable'`, `'iminsert'`, `'imstyle'` and `'imcmdline'`.

Then, run this shell command:

    for f in /tmp/.test.*.vim; do vim -gf -Nu NONE -U NONE -i NONE --cmd "so $f" +term; done

It should start gVim 24 times (consecutively, not simultaneously), one for each possible combination of settings.

**Comment by jchtt** [comment]
> Does it help if you press a chord using the control modifier (e.g. <C-L>) at least once before opening :terminal? I ask because of the issue #5951.

> It should start gVim 24 times (consecutively, not simultaneously), one for each possible combination of settings.

Thanks for the script! I tried both, no change on either.

**Comment by lacygoill** [comment]
I can't fix the issue, but it's probably caused by https://github.com/vim/vim/commit/fd615a3c901f59abddca27c6a09940be552c0f4d.

This patch, combined with https://github.com/vim/vim/commit/f4ae6b245a54f11dd967d06b80f30e5abf55fb82, allows you to map something to a meta chord (e.g. `<M-a>`, `<M-b>`, ...) in the GUI, without losing the ability to insert some accented characters.

The purpose was to fix [this kind of issue](https://github.com/vim/vim/issues/4974#issuecomment-628916688):

> The solution (#4974 (comment)) talked in this thread doesn't apply to Gvim, does it? Is the differentiation of meta/alt+key from accented letters still impossible there? I.e <M-v> seems to still mean ö on my Gvim...

**Comment by jchtt** [comment]
Good to know, thanks for checking this so quickly! For now, I can just downgrade. Happy to help with testing some patches once someone gets there.

I’ll try to roll back to those exact changes when I have some spare time to see what happens.

Edit: I checked, it's [`fd615a3`](https://github.com/vim/vim/commit/fd615a3c901f59abddca27c6a09940be552c0f4d) after which it stops working.

**Comment by brammool** [comment]
It has nothing to do with modifyOtherKeys.  In a terminal XIM is off, which causes typed keys to go through another path, where multi-byte characters are not handled properly.  Must have been a problem for a very long time.
