### ISSUE TITLE
vim9script: some builtin functions cannot be called with the method syntax through a :def function

### ISSUE THREAD

**Issue by bfrg** [vim/vim#6305]
**Describe the bug**
`append()`, `setline()`, `appendbufline()` and `setbufline()` cannot be called through `:def` functions as methods in `vim9script`, for example, `GetLines()->append('$')`.

I haven't found anything in `:help todo` nor in `:help vim9`.

**To Reproduce**
1. Run `vim --clean -S tmp.vim` with
```vim
vim9script
def Lines(n: number): list<string>
    return range(n)->map('string(v:val)')
enddef

def Test(n: number)
    Lines(n)->append('$')
enddef
call Test(5)
```
2. Vim will print the following error:
```
E745: Using a List as a Number
```
3. Prepending the method invocation with `call` gives the same error.
4. Prepending the method invocation with `eval` prints the following error:
```
 E121: Undefined variable: n
 E116: Invalid arguments for function Lines(n)->append('$')
```
5. Using the old syntax works fine:
```vim
def Test(n: number)
    append('$', Lines(n))
enddef
```
6. Interestingly, Vim does not throw any errors when the comma is omitted between the first and second argument:
```vim
def Test(n: number)
    append('$' Lines(n))
enddef
```
7. For `appendbufline()` and `setbufline()` Vim won't even throw an error. When running the following script, no lines are added to buffer `foo`:
```vim
vim9script
def Lines(n: number): list<string>
    return range(n)->map('string(v:val)')
enddef

def Test(n: number)
    let bufnr: number = bufadd('foo')
    bufload(bufnr)
    setbufvar(bufnr, '&buflisted', 1)
    Lines(n)->setbufline(bufnr, '$')
enddef
call Test(5)
```
8. The old syntax works though:
```vim
def Test(n: number)
    let bufnr: number = bufadd('foo')
    bufload(bufnr)
    setbufvar(bufnr, '&buflisted', 1)
    setbufline(bufnr, '$', Lines(n))
enddef
```
As before, the following syntax is also valid `setbufline(bufnr '$' Lines(n))`. Notice the missing commas. Vim won't throw any errors. I don't know if that's intentional.

**Environment**
Vim version `8.2.1023`

**Comment by bfrg** [comment]
The following will insert a literal `$` in the first line of the current buffer, and not append `Hello World` to the end of the buffer:

Run `vim --clean tmp.vim -S tmp.vim` with
```vim
vim9script
def Line(): string
    return 'Hello World'
enddef

def Test()
    Line()->append('$')
enddef
call Test()
```

**Comment by brammool** [comment]
> The following will insert a literal `$` in the first line of the current buffer, and not append `Hello World` to the end of the buffer:
> 
> Run `vim --clean tmp.vim -S tmp.vim` with
> ```vim
> vim9script
> def Line(): string
>     return 'Hello World'
> enddef
> 
> def Test()
>     Line()->append('$')
> enddef
> call Test()
> ```

That hasn't been implemented yet:

	// TODO: base value may not be the first argument


-- 
Compilation process failed successfully.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
