### ISSUE TITLE
glitch on vim 8.2.0701 when folding a line of multibytes

### ISSUE THREAD

**Issue by teto** [vim/vim#6311]
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Describe the bug**
The default foldtext function produces strange characters on folded lines that contain multybyte, especially the end of the line is giberrish instead of containing the fillchar `fold`.

**To Reproduce**
with mbyte.txt:
```
å 语 x̨̣̘̫̲͚͎̎͂̀̂͛͛̾͢͟ العَرَبِيَّة
möre text

dadad
```
run  `vim -u NONE mbyte.txt` then `zfj` to create a fold containing the first and second line.
Instead of having the `fold` fillchar filling the rest of the line, it is kinda gibberish.

**Expected behavior**
foldtext should display some text and then be filled with fillchar 'fold'. This works with latin1 characters.

**Screenshots**
see on the right: instead of being filled with the same fillchar character, there is the fillchar character, some random character and empty spaces
![2020-06-21-205908_951x118_scrot](https://user-images.githubusercontent.com/886074/85232779-1694b480-b402-11ea-8870-9bf1da53e6d3.png)

**Environment (please complete the following information):**
 - Vim version [e.g. 8.1.1234] 8.2.0701
 - OS: [e.g. Ubuntu 18.04, Windows 10 1809, macOS 10.14] " nixos
 - Terminal: [e.g. GNOME Terminal, mintty, iTerm2, tmux, GNU screen] : plain kitty (0.17.4 )

**Additional context**
when I copy-paste the output in sublime text it displays these as arabic characters. I beleive arabicshape may have a role to play ?

**Comment by chrisbra** [comment]
is that a recent regression?

**Comment by teto** [comment]
I was able to test with termite on 8.2.0013 and it worked fine there. 8.2.0510 with the same termite, the output is garbled so it's indeed a regression (wasn''t sure since it's my first time witnessing this).

**Comment by chrisbra** [comment]
Thanks for checking. Did I understand correctly, that 8.2.510 did introduce the regression or did that happen in between?

**Comment by teto** [comment]
I tried to bisect but with termite everything looks fine, the problem seems to be with kitty after all. I've tried with 0.18 which has the same issue. I will open a ticket over there.
