### ISSUE TITLE
output of "state()" does not contain the "o" flag when the "f" command is waiting for input

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6317]
**Describe the bug**

The output of `state()` does not contain the `o` flag when the `f` command is waiting for input.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        au VimEnter * call Func()
        fu Func()
            call feedkeys('f', 't')
            call timer_start(100, {-> writefile([state()], '/tmp/.log', 'a')}, #{repeat: 10})
            call timer_start(1000, {-> feedkeys("\e")})
        endfu
    EOF
    )

Wait one second, then run this Ex command:

    :!cat /tmp/.log

The output is:

    Sc
    Sc
    Sc
    Sc
    Sc
    Sc
    Sc
    Sc
    Sc
    c

The `o` flag is absent from all the lines.

**Expected behavior**

The `o` flag is present in at least some of the lines.

**Environment**

 - Vim version: 8.2 Included patches: 1-1042
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(356)

**Additional context**

This seems to contradict `:h state()` which explains that the output of `state()` should contain the `o` flag when Vim is in operator-pending mode or when it's waiting for the argument of a command such as `f`:

>     o   operator pending or waiting for a command argument,
>         e.g. after |f|

**Comment by brammool** [comment]
The documentation is wrong, "o" is only added when an operator is pending.  Not when waiting for a count or an argument for "f".

**Comment by brammool** [comment]
Updated docs:
		These characters indicate the state, generally indicating that
		something is busy:
		    m	halfway a mapping, :normal command, feedkeys() or
			stuffed command
		    o	operator pending, e.g. after |d|
		    a	Insert mode autocomplete active
		    x	executing an autocommand
		    w	blocked on waiting, e.g. ch_evalexpr(), ch_read() and
			ch_readraw() when reading json
		    S	not triggering SafeState or SafeStateAgain, e.g. after
		    	|f| or a count
		    c	callback invoked, including timer (repeats for
			recursiveness up to "ccc")
		    s	screen has scrolled for messages
