### ISSUE TITLE
C/C++ syntax highlight - comment format not correct

### ISSUE THREAD

**Issue by branchus** [vim/vim#6321]
**Describe the bug**
In C/C++ source file, syntax for comment not correct. If comment include the ", part of those comment become normal text, it cannot handle number correctly too. all the numbers showing in the comment are different from the other texts

**To Reproduce**
to start a new vim editor, type in the C/C++ type comments, when there're " or numbers, it cannot handle correctly.
As can see from below screenshot
"good morning" has a different style
The printf statement is in the comment, but those text just not shown as comment
also number 1, 2, 3 are differnt from one two three

**Expected behavior**
I expect the numbers and " quoted text have the same style as other text in the comment.

**Screenshots**
![Screenshot from 2020-06-23 22-29-10](https://user-images.githubusercontent.com/1289143/85403955-9311c980-b5a1-11ea-8dd3-1aad1e769805.png)

**Environment (please complete the following information):**
 - Vim version [8.1.1401 & 8.2.752] 
 - OS: [Fedora 31 & Debian 10]
 - Terminal: [GNOME Terminal] & [gVim]

**Additional context**
In order to test this is not cause by my own configuration, no 3rd party syntax used, no vimrc file in place

**Comment by chrisbra** [comment]
cannot reproduce. Do you have custom syntax files installed? Check the output of `:scriptnames`

**Comment by branchus** [comment]
> cannot reproduce. Do you have custom syntax files installed? Check the output of `:scriptnames`

Hi Chrisbra
I only had bundled syntax/plugin files, no custom syntax files installed, no vimrc file either in this test environment
![Screenshot from 2020-06-23 22-49-42](https://user-images.githubusercontent.com/1289143/85405611-06b4d600-b5a4-11ea-8788-d02d41932d52.png)

**Comment by chrisbra** [comment]
oh yes, seems to be available per default. Please check the few settings mentioned at `:h ft-c-syntax` I think one can disable those using the `c_comment_strings` option.

**Comment by branchus** [comment]
> oh yes, seems to be available per default. Please check the few settings mentioned at `:h ft-c-syntax` I think one can disable those using the `c_comment_strings` option.

Thank you very much chrisbra
I finally solved this issue, bothered me for a long time.
Thanks
