### ISSUE TITLE
some todo items are stale

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6324]
I had a look at the first half of the todo list, and found some items which could be stale.  I don't submit a PR, because I'm not sure for all of them.

---

[Source](https://github.com/vim/vim/blob/df069eec3b90401e880e9b0e258146d8f36c474d/runtime/doc/todo.txt#L137-L140):

> - With some sequence get get hidden finished terminal buffer. (#5768)
>     Cannot close popup terminal (#5744)
>     Buffer can't be wiped, gets status "aF". (#5764)
>     Is buf->nwindows incorrect?

No longer relevant since [8.2.0743](https://github.com/vim/vim/releases/tag/v8.2.0743).

Actually, I'm not sure that `#5768` is no longer relevant since 8.2.0743.  Maybe it was fixed by another patch; but it is fixed anyway.

---

[Source](https://github.com/vim/vim/blob/df069eec3b90401e880e9b0e258146d8f36c474d/runtime/doc/todo.txt#L141-L142):

> - popup_clear() and popup_close() should close the terminal popup, and
>    make the buffer hidden. #5745

No longer relevant since [8.2.0747](https://github.com/vim/vim/releases/tag/v8.2.0747).

---

[Source](https://github.com/vim/vim/blob/df069eec3b90401e880e9b0e258146d8f36c474d/runtime/doc/todo.txt#L498-L499):

> v:register isn't reset early enough, may be used by next command.
> (Andy Massimino, #5294, possible fix in #5305)

No longer relevant since [8.2.0929](https://github.com/vim/vim/releases/tag/v8.2.0929):

---

[Source](https://github.com/vim/vim/blob/df069eec3b90401e880e9b0e258146d8f36c474d/runtime/doc/todo.txt#L583-L584):

> Add a way to create an empty, hidden buffer.  Like doing ":new|hide".
> ":let buf = bufcreate('name')

*Maybe* no longer relevant since Vim supports `bufadd()` and `bufload()`.  Now, one can run:

    vim -Nu NONE +'let buf = bufadd("name") | call bufload(buf) | call setbufvar(buf, "&buflisted", 1)'

---

[Source](https://github.com/vim/vim/blob/df069eec3b90401e880e9b0e258146d8f36c474d/runtime/doc/todo.txt#L1202-L1204):

> Implement named arguments for functions:
>     func Foo(start, count = 1 all = 1)
>     call Foo(12, all = 0)

No longer relevant since [8.1.1310](https://github.com/vim/vim/releases/tag/v8.1.1310).

---

[Source](https://github.com/vim/vim/blob/df069eec3b90401e880e9b0e258146d8f36c474d/runtime/doc/todo.txt#L1396):

> Cannot delete a file with square brackets with delete(). (#696)

No longer relevant since [8.1.1378](https://github.com/vim/vim/releases/tag/v8.1.1378).

---

[Source](https://github.com/vim/vim/blob/df069eec3b90401e880e9b0e258146d8f36c474d/runtime/doc/todo.txt#L1406):

> 'hlsearch' interferes with a Conceal match. (Rom Grk, 2016 Aug 9)

*Maybe* no longer relevant since [8.1.1082](https://github.com/vim/vim/releases/tag/v8.1.1082).

---

[Source](https://github.com/vim/vim/blob/df069eec3b90401e880e9b0e258146d8f36c474d/runtime/doc/todo.txt#L1419):

> Possibly wrong value for seq_cur. (Florent Fayolle, 2016 May 15, #806)

No longer relevant since [8.0.1290](https://github.com/vim/vim/releases/tag/v8.0.1290).

---

[Source](https://github.com/vim/vim/blob/df069eec3b90401e880e9b0e258146d8f36c474d/runtime/doc/todo.txt#L1439):

> Add redrawtabline command. (Naruhiko Nishino, 2016 Jun 11)

No longer relevant since [8.1.0706](https://github.com/vim/vim/releases/tag/v8.1.0706).

---

[Source](https://github.com/vim/vim/blob/df069eec3b90401e880e9b0e258146d8f36c474d/runtime/doc/todo.txt#L1510):

> Patch to show search statistics. (Christian Brabandt, 2016 Jul 22)

No longer relevant since [8.1.1270](https://github.com/vim/vim/releases/tag/v8.1.1270).

---

[Source](https://github.com/vim/vim/blob/df069eec3b90401e880e9b0e258146d8f36c474d/runtime/doc/todo.txt#L1516-L1522):

> Using ":windo" to set options in all windows has the side effect that it
> changes the window layout and the current window.  Make a variant that saves
> and restores.  Use in the matchparen plugin.
> Perhaps we can use ":windo <restore> {cmd}"?
> Patch to add <restore> to :windo, :bufdo, etc. (Christian Brabandt, 2015 Jan
> 6, 2nd message)
> Alternative: ":keeppos" command modifier: ":keeppos windo {cmd}".

*Maybe* no longer relevant since [8.1.1418](https://github.com/vim/vim/releases/tag/v8.1.1418).

Rationale: you can now use `map()` + `win_execute()` to emulate `:windo` without side-effects:

    :call range(1, winnr('$'))->map({_,v -> win_execute(v, '" set some option')})

---

[Source](https://github.com/vim/vim/blob/df069eec3b90401e880e9b0e258146d8f36c474d/runtime/doc/todo.txt#L1553):

> Add "===" to have a strict comparison (type and value match).

*Maybe* no longer relevant since Vim supports `is#`.

---

[Source](https://github.com/vim/vim/blob/df069eec3b90401e880e9b0e258146d8f36c474d/runtime/doc/todo.txt#L1726):

> Patch to add :arglocal and :arglists. (Marcin Szamotulski, 2014 Aug 6)

`:arglocal` already exists, so this item seems at least partially stale.

---

[Source](https://github.com/vim/vim/blob/df069eec3b90401e880e9b0e258146d8f36c474d/runtime/doc/todo.txt#L1754-L1755):

> Include a plugin manager with Vim? Neobundle seems to be the best currently.
> Also Vundle: https://github.com/gmarik/vundle

Right now, I think the most popular plugin manager is [vim-plug](https://github.com/junegunn/vim-plug), not Neobundle.

Although, one could make the argument that it would be better to include [minpac](https://github.com/k-takata/minpac) since it leverages the builtin package feature.

---

[Source](https://github.com/vim/vim/blob/df069eec3b90401e880e9b0e258146d8f36c474d/runtime/doc/todo.txt#L1808-L1809):

> Patch for XDG base directory support. (Jean François Bignolles, 2014 Mar 4)
> Remark on the docs.  Should not be a compile time feature.  But then what?

Maybe this item should be updated to reference the issue #2034 which is relevant (the [last comment](https://github.com/vim/vim/issues/2034#issuecomment-559254363) is imo especially interesting).

---

[Source](https://github.com/vim/vim/blob/df069eec3b90401e880e9b0e258146d8f36c474d/runtime/doc/todo.txt#L1869-L1870):

> Exception caused by argument of return is not caught by try/catch.
> (David Barnett, 2013 Nov 19)

[Source](https://github.com/vim/vim/blob/df069eec3b90401e880e9b0e258146d8f36c474d/runtime/doc/todo.txt#L2093-L2094):

> Bug in try/catch: return with invalid compare throws error that isn't caught.
> (ZyX, 2011 Jan 26)

[Source](https://github.com/vim/vim/blob/df069eec3b90401e880e9b0e258146d8f36c474d/runtime/doc/todo.txt#L2687):

> try/catch not working for argument of return. (Matt Wozniski, 2008 Sep 15)

Some of these items *could* be duplicate.

---

[Source](https://github.com/vim/vim/blob/df069eec3b90401e880e9b0e258146d8f36c474d/runtime/doc/todo.txt#L1905):

> patch to add "combine" flag to  syntax commands. (so8res, 2012 Dec 6)

[Source](https://github.com/vim/vim/blob/df069eec3b90401e880e9b0e258146d8f36c474d/runtime/doc/todo.txt#L2284-L2285):

> Patch to add "combine" to :syntax, combines highlight attributes. (Nate
> Soares, 2012 Dec 3)

These items *could* be duplicate.

---

[Source](https://github.com/vim/vim/blob/df069eec3b90401e880e9b0e258146d8f36c474d/runtime/doc/todo.txt#L2479-L2480):

> Consider making YankRing or something else that keeps a list of yanked text
> part of standard Vim.  The "1 to "9 registers are not sufficient.

[Source](https://github.com/vim/vim/blob/df069eec3b90401e880e9b0e258146d8f36c474d/runtime/doc/todo.txt#L5982-L5984):

> 6   When yanking into the unnamed registers several times, somehow make the
>     previous contents also available (like it's done for deleting).  What
>     register names to use?  g"1, g"2, etc.?

These items *could* be duplicate.

---

[Source](https://github.com/vim/vim/blob/df069eec3b90401e880e9b0e258146d8f36c474d/runtime/doc/todo.txt#L3259-L3260):

> 7   Add a command that goes back to the position from before jumping to the
>     first quickfix location.  ":cbefore"?

The name `:cbefore` is already taken.

---

[Source](https://github.com/vim/vim/blob/df069eec3b90401e880e9b0e258146d8f36c474d/runtime/doc/todo.txt#L3297):

> 7   Implement 'prompt' option.	Init to off when stdin is not a tty.

Maybe no longer relevant since the `'prompt'` option exists.

---

[Source](https://github.com/vim/vim/blob/df069eec3b90401e880e9b0e258146d8f36c474d/runtime/doc/todo.txt#L3475-L3476):

> 8   X11 GUI: When menu is disabled by excluding 'm' from 'guioptions', ALT key
>     should not be used to trigger a menu (like the Win32 version).

Maybe no longer relevant.  Test with:

    vim -Nu NONE -g --cmd 'set go-=m' +startinsert

Press `M-f`: the `File` menu is not opened, and a character is inserted.

---

[Source](https://github.com/vim/vim/blob/df069eec3b90401e880e9b0e258146d8f36c474d/runtime/doc/todo.txt#L3515-L3516):

> 8   A dead circumflex followed by a space should give the '^' character
>     (Rommel).  Look how xterm does this.

Maybe no longer relevant as it works for me.

---

[Source](https://github.com/vim/vim/blob/df069eec3b90401e880e9b0e258146d8f36c474d/runtime/doc/todo.txt#L3615-L3616):

> -   Can't disable terminal flow control, to enable the use of CTRL-S and
>     CTRL-Q.  Add an option for it?

No longer relevant since [8.2.0852](https://github.com/vim/vim/releases/tag/v8.2.0852) and [8.2.0856](https://github.com/vim/vim/releases/tag/v8.2.0856).

---

[Source](https://github.com/vim/vim/blob/df069eec3b90401e880e9b0e258146d8f36c474d/runtime/doc/todo.txt#L3619-L3625):

> -   When the quickfix window is open and executing ":echo 'hello'" using the
>     Command-line window, the text is immediately removed by the redrawing.
>     (Michael Henry, 2008 Nov 1)
>     Generic solution: When redrawing while there is a message on the
>     cmdline, don't erase the display but draw over the existing text.
>     Other solution, redraw after closing the cmdline window, before executing
>     the command.

No longer relevant since [8.1.0698](https://github.com/vim/vim/releases/tag/v8.1.0698).

---

[Source](https://github.com/vim/vim/blob/df069eec3b90401e880e9b0e258146d8f36c474d/runtime/doc/todo.txt#L4085-L4086):

> -   Support spelling words in CamelCase as if they were two separate words.
>     Requires some option to enable it. (Timothy Knox)

No longer relevant since [8.2.0953](https://github.com/vim/vim/releases/tag/v8.2.0953).

---

[Source](https://github.com/vim/vim/blob/df069eec3b90401e880e9b0e258146d8f36c474d/runtime/doc/todo.txt#L4693-L4694):

    8   When reading from stdin allow suppressing the "reading from stdin"
        message.

No longer relevant since [7.4.1453](https://github.com/vim/vim/releases/tag/v7.4.1453) which provides `--not-a-term`.

---

[Source](https://github.com/vim/vim/blob/df069eec3b90401e880e9b0e258146d8f36c474d/runtime/doc/todo.txt#L4461-L4462):

> 8   Add referring to key options with "&t_xx".  Both for "echo &t_xx" and
>     ":let &t_xx =".  Useful for making portable mappings.

No longer relevant since [8.0.0302](https://github.com/vim/vim/releases/tag/v8.0.0302).

**Comment by lacygoill** [comment]
Closing as *if* some of those items are stale, they'll be removed in the next update of the runtime files.

**Comment by brammool** [comment]
Thanks for cleaning this up.  I'll include (well, delete) most of them.

For some I'm not sure, but they are old, so we can remove them and expect them to be reported again if someone trips over it.

This one is still relevant:
Implement named arguments for functions with optional arguments:
    func Foo(start, count = 1, all = 1)
    call Foo(12, all = 0)

These ones are not backwards compatible, we'll fix this in Vim9 script:
   Also, "'' == 0" evaluates to true, which isn't nice.
   Add "===" to have a strict comparison (type and value match).
   Add "==*" (?) to have a value match, but no automatic conversion, and v:true
   equals 1 and 1.0, v:false equals 0 and 0.0.?
