### ISSUE TITLE
after map <esc> :nohls, the key map <F11> goes wrong

### ISSUE THREAD

**Issue by sbxjoy** [vim/vim#633]
Set the map `nnoremap <Esc> :nohls<CR>` in .vimrc.  the map of `<F11>` would change to toggle case of current word

**Comment by fritzophrenic** [comment]
This is almost certainly NOT a bug in Vim. Please use the issue tracker for things that are Vim issues. For help with Vim use the [vim_use mailing list](https://groups.google.com/forum/#!forum/vim_use).

**Comment by sbxjoy** [comment]
@fritzophrenic I see the reason....
