### ISSUE TITLE
:redraw emits invalid control sequences

### ISSUE THREAD

**Issue by zsugabubus** [vim/vim#6336]
**Describe the bug**

Vim emits invalid control sequences so screen expected to has glitches. 

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim '+call setline(1, repeat([">>----"], 5))' +redraw`.
2. In most terminals you will see (tested with alacritty, urxvt):
```
>>----
  ----

>>----
>>----
```

instead of (kitty):
```
>>----
>>----
>>----
>>----
>>----
```

**Expected behavior**

Redraw does not mess up screen.

**Environment (please complete the following information):**
 - Vim version: 8.2.1052
 - OS: Arch Linux

**Additional context**

I already experienced this behavior for a few days but it’s hardly vary between commit to commit. For example, a few commits before third line is displayed fine only “>>” was missing from the second.

Digging deeper, testing inside `kitty` I found that it complains about invalid CSI-sequences:
```
...
[PARSE ERROR] Unknown CSI code: 'm' with start_modifier: '>' and end_modifier: ';' and parameters: '5'  ((5??))
[PARSE ERROR] Unknown CSI code: 'm' with start_modifier: '>' and end_modifier: ';' and parameters: '1'
...
```

Recording with `script vim ...` I found this: `\e[m\e[?2004l\e[?1l\e>\e[>4;m`. `\e[>4;m` really does not look so right.

**Comment by brammool** [comment]
Do you set $TERM to "kitty", or whatever name it uses for termcap/terminfo?
If you use "xterm" it's likely to fail, since kitty is not 100% xterm compatible.

**Comment by Shane-XB-Qian** [comment]
that seq is from `t_TI` / `t_TE`
even it was a xterm compatible terminal, if it set, you would see some **annoyed** seq in the screen ..

**Comment by zsugabubus** [comment]
> Do you set $TERM to "kitty", or whatever name it uses for termcap/terminfo?

In `kitty` it’s “xterm-kitty” (guess it’s the default because I do not modify `$TERM` anywhere). But it also works with `TERM=kitty vim ...`.

> If you use "xterm" it's likely to fail, since kitty is not 100% xterm compatible.

There is no issues with `kitty`, since I do not experience missing characters (lines) with that but only with `alacritty` (`TERM=alacritty`) and `rxvt-unicode` (`TERM=rxvt-unicode-256color`)… and probably more. Because without `+redraw` everything is fine, I assume `:redraw` has to emit/do something wrong.

---

> that seq is from t_TI / t_TE

This: `\e[>4;m`? It wants to be an SGR sequence, no? (I just showed some context before it if somebody wants to check `script`.)

**Comment by Shane-XB-Qian** [comment]
`vim --clean -c "echo &t_TE"` :
![image](https://user-images.githubusercontent.com/13550529/85839409-7ce85100-b7cd-11ea-91b2-688029e90f5b.png)

i have no rxvt term, but it looks ok at my xfce-term, that 5 lines ('>>--------') put normally.
but just if `echo system('ls | head -1')` - you will see that seq: // though redraw can help to clean them.
![image](https://user-images.githubusercontent.com/13550529/85840182-a5bd1600-b7ce-11ea-87f1-ed8d50dc5c25.png)

may related to #5617 , fyi.

**Comment by Shane-XB-Qian** [comment]
and i saw you opened a ticket to kitty, looks kitty did not recognized that seq issue had been fixed now.
so again, looks it is terminal specific, but vim side may had some code leak too ..

**Comment by zsugabubus** [comment]
> vim --clean -c "echo &t_TE"

For me `empty(&t_TE) == 1` in all terminals. Guess then it’s set to default.

> echo system('ls | head -1')

I do not experience any issues with that.

> though redraw can help to clean them

(`:redraw!`)

> and i saw you opened a ticket to kitty, looks kitty did not recognized that seq issue had been fixed now.

That was only about the non-sense parse error message and nothing about implementation. It said it parsed an invalid SGR with parameters '5' but there is no '5' in the whole input…

---

Reading through what XTerm understands, `CSI > Ps; Ps m` really seems to be a valid sequence. Though `alacritty` does not advertise itself as `xterm-alacritty` (so not XTerm compatible?), I do not know what causes the missing characters. I thought the above mentioned sequence will be faulty since `kitty` outputted a parse error, but then my assumption is likely wrong. (But then it isn’t really a parse error since it could be parsed just does not understand…)

**Comment by Shane-XB-Qian** [comment]
no clue, at my case, just xfce-term did not recognized `^[[>4;m` . // but pure xterm do.
but your case, if t_TE was empty, then why it sent such seq to term when mode switch or vim exit?
so looks terminal specific, or i mis-understood sth ..

**Comment by brammool** [comment]
This is either a problem with the terminal emulator or with setting the correct termcap/terminfo entries.  Not a Vim problem.
