### ISSUE TITLE
Escape code agnostic key mappings (in gvim)

### ISSUE THREAD

**Issue by hasufell** [vim/vim#6338]
GVim seems to have limitations of mapping certain keys independently, which would result in the same escape code in the terminal. This is due to vims terminal nature, but has no sensible reasoning in a gtk application.

A prominent example is binding `<C-i>` independent of `<TAB>`, which pretty much every major editor in 2020 can do, including [emacs](https://www.emacswiki.org/emacs/TabKey).

This is a major issue for eg. [workman](https://workmanlayout.org/) users, where `i` is on the homerow.

**Comment by lacygoill** [comment]
Which Vim version are you using?  Which gui version (gtk, athena, motif, ...)?

FWIW, with GTK2, I can map different commands to `C-i` and `Tab`:

![gif](https://user-images.githubusercontent.com/8505073/85789957-bec2ba00-b72f-11ea-9d84-99e1621eeb08.gif)


Make a test with this command:

    vim -g -Nu NONE +'nno <C-i> :echom "C-i was pressed"<cr>' +'nno <tab> :echom "Tab was pressed"<cr>'

Make sure to have at least the patch [8.2.0765](https://github.com/vim/vim/releases/tag/v8.2.0765).

**Comment by lacygoill** [comment]
See also [`:h modifyOtherKeys`](https://vimhelp.org/map.txt.html#modifyOtherKeys) and [How to map &lt;C-i> separate from &lt;Tab>?](https://vi.stackexchange.com/questions/16161/how-to-map-c-i-separate-from-tab/23344#23344).

**Comment by hasufell** [comment]
I'm running Gtk3 gvim 8.1.1467. I guess that's too old.

**Comment by chrisbra** [comment]
closing
