### ISSUE TITLE
toggle option value

### ISSUE THREAD

**Issue by 532910** [vim/vim#6340]
Please add a way to toggle an option's value:

```Vim
se[t] {option}!={value}
```

```Vim
if strridx(&{option}, '{value}') > 0
        set {option}-={value}
else
        set {option}+={value}
endif
```

**Comment by nickspoons** [comment]
[:help :set-!](http://vimhelp.appspot.com/options.txt.html#%3Aset-%21)

**Comment by 532910** [comment]
it toggles option, not it's value

**Comment by chrisbra** [comment]
Is this actually needed in Vim core? You can easily script it yourself if you need this (as shown by your message).

**Comment by 532910** [comment]
`:set-inv` is also can be easily scripted, but it's a part of Vim core.

**Comment by chrisbra** [comment]
> :set-inv is also can be easily scripted, but it's a part of Vim core.

Indeed, but that comes probably from a time when VimScript wasn't an actual language.

**Comment by 532910** [comment]
This is some king of syntactic sugar that is a part of programming languages (:

**Comment by brammool** [comment]
"toggle" means switching between on and off, which only applies to boolean options, for which ":set invoption" already exists.
For number and string options there is no meaningful toggle operator

**Comment by 532910** [comment]
It's like that, but what's wrong to implement this operator?
