### ISSUE TITLE
cursorline disappears in the visual mode

### ISSUE THREAD

**Issue by 532910** [vim/vim#6341]
`cursorline` becomes invisible in visual mode while `cursorcolumn` stays visible. Steps to reproduce:

1.
```
set cursorline
set cursorcolumn
```
2. start visual mode with `v`, `V` or `Ctrl-V`

vim 8.2 debian sid

**Comment by nickspoons** [comment]
This is intentional. From [:help 'cursorline'](http://vimhelp.appspot.com/options.txt.html#%27cursorline%27):

> When Visual mode is active the highlighting isn't used to make it easier to see the selected text.
