### ISSUE TITLE
LaTeX syntax got confused by unmatched nested delimiters 

### ISSUE THREAD

**Issue by Rmano** [vim/vim#6344]
The LaTex syntax highlight got confused by nested, unmatched delimiters and fails to switch off math mode:

![image](https://user-images.githubusercontent.com/6414907/85841864-06345f00-b79f-11ea-8aaf-57ab1fd4715d.png)

**To Reproduce**

Run `vim -u ./plainrc open-intervals.tex`

with `plainrc` as

```vim
set nocompatible
filetype plugin indent on
syntax enable
```

and `open-intervals.tex` as:
```latex
Correct syntax $math$ here
  
    \begin{tabular}{cc}
    $\text{(20, 25]}$ &  \\
    \end{tabular}

Wrong syntax here...
```

**Expected behavior**

The last line should not be in math mode.  You can correct the thing by adding a `%stopmode` after the `\\` as a workaround...

**Environment (please complete the following information):**
 
- vim version:
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 18 2020 18:29:15)
Included patches: 1-1453
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version with GTK3 GUI.  Features included (+) or not (-):
```
 - OS: Ubuntu 18.04
 - Terminal: GNOME Terminal, or `gvim`

**Additional context**

Previously reported here: https://github.com/lervag/vimtex/issues/1723

**Comment by lervag** [comment]
A more minimal LaTeX example:

```tex
Correct syntax $math$ here
$\text{(20, 25]}$
Wrong syntax here...
```

**Comment by byteofsoren** [comment]
Any fixes for this issue?

**Comment by lervag** [comment]
FYI: This issue is not present in Vimtex, which now ships with its own syntax plugin.

**Comment by chrisbra** [comment]
Have you contacted Charles (@cecamp) directly or tried out the latest versions from http://www.drchip.org/astronaut/vim/index.html#SYNTAX_TEX?

**Comment by cecamp** [comment]
I can see where one may not want mismatched delimiter checking. Fortunately, there's already a mechanism in syntax/tex.vim to accomodate that wish:
```vim
let g:tex_matchcheck= '[{}]'
```
Its not currently documented, so I'll forward a bit more document to Bram. You may provide that setting in your .vimrc.  If you do this manually while in the document, you'll want to use `set ft=tex` to get the syntax to reload with it effective.
