### ISSUE TITLE
Vim doesn't allow preceding method calls with a logical NOT operator, like !mylist->empty()

### ISSUE THREAD

**Issue by bfrg** [vim/vim#6348]
**Describe the bug**
Currently it is not possible to precede a method call with a logical NOT operator, for example: `!mylist->empty()`.

**To Reproduce**
Run `vim --clean -S tmp.vim`, with
```vim
" tmp.vim
if !range(5)->empty()
    echo 'List not empty'
endif
```
Vim will print the following error:
```
E745: Using a List as a Number
```

At the moment we have to put the expression inside parentheses, like `!(range(5)->empty())`, or use the old syntax `!empty(range(5))`.

**Expected behavior**
I would have expected this to work just like in other languages. If it can't be implemented, maybe it could be mentioned somewhere in the documentation.

**Environment**
Vim version `8.2.1046`

**Comment by tonymec** [comment]
You could also reverse the `:if` syntax:
```vim
if range(5)->empty()
  echo "List empty"
else
  echo "List not empty"
endif
```
or even
```vim
if range(5)->empty()
  " do nothing
else
  echo "List not empty"
endif
```
Best regards,
Tony.

**Comment by brammool** [comment]
When using expr1->func()  the question is whether the prefix is applied to expr1 or to the whole.
The example in the code mentions "-1.0->method()". Her the "-" needs to be applied to expr1.
But in your example the "!" applies to the whole.
It gets even more tricky: "!-1.0->method()".  Then the "-" applies to expr1 and "!" to the whole.
