### ISSUE TITLE
Is there a way to log all my key press using vimscript?

### ISSUE THREAD

**Issue by suliveevil** [vim/vim#6349]
I search `vim log` `vim record` `vim track`  `vim keyfreq` `vim key` …… Still couldn't find a plugin or some code like Emacs's https://github.com/dacap/keyfreq .
Does the keylog thing violated some rules in Vim?
Or I should find a way outside Vim to achive?

**Comment by lacygoill** [comment]
The only builtin facility I can think of is [the `-w` argument](https://vimhelp.org/starting.txt.html#-w).  You could install some shell function to always start Vim with `-w`.

    vim() {
        vim -w /tmp/.vimkeys "$@"
    }

But there may be at least 2 issues with this approach:

   - the keys are not written in the file until you quit Vim
   - the keys may not always be written in a human readable form

For the first issue, you could try [this patch](https://gist.github.com/kana/4202311).  I've just tested it, and it seems to work:

```diff

diff --git a/src/main.c b/src/main.c
index 39e67e998..21e064042 100644
--- a/src/main.c
+++ b/src/main.c
@@ -2579,6 +2579,7 @@ scripterror:
                        mch_errmsg("\"\n");
                        mch_exit(2);
                    }
+		    setvbuf(scriptout, NULL, _IONBF, 0);
                    break;

 #ifdef FEAT_GUI_MSWIN
```

For [the second issue](https://github.com/vim/vim/issues/4725), I guess you would have to wait for/work on [this todo item](https://github.com/vim/vim/blob/8ea9390b78da9e34a20e7418712921397c0c1989/runtime/doc/todo.txt#L1189-L1193):

> Add a "keytrans()" function, which turns the internal byte representation of a
> key into a form that can be used for :map.  E.g.
>     let xx = "\<C-Home>"
>     echo keytrans(xx)
>     <C-Home>

---

Alternatively, you could try to record the keypresses at the OS level.  As an example, this [Vim screencast](https://www.youtube.com/watch?v=SCD2h3AT-EM) shows how to do it using Hammerspoon on OS X.

Or you could wait for/work on [this other todo item](https://github.com/vim/vim/blob/8ea9390b78da9e34a20e7418712921397c0c1989/runtime/doc/todo.txt#L1375-L1379).

> Idea from Sven: record sequence of keys.  Useful to show others what they are
> doing (look over the shoulder), and also to see what happened.
> Probably list of keystrokes, with some annotations for mode changes.
> Could store in logfile to be able to analyse it with an external command.
> E.g. to see when's the last time a plugin command was used.

**Comment by suliveevil** [comment]
Thank you very much.
The first solution is simple, I will try that first.
Compiling Vim is immpossible for now, because I'm using Vim 8.1.2110( iVim App) on iPadOS.

Take a note for this issue: https://github.com/suliveevil/ivim_rc/blob/master/resources/vim-keystroke.md

I will try to undersstand the byte representation of keystrokes.
