### ISSUE TITLE
markdown loads user ftplugin_html

### ISSUE THREAD

**Issue by dylnmc** [vim/vim#6354]
1. `vim README.md`
2. `~/.vim/after/ftplugin/html.vim` is loaded causing issues

what is this??  https://github.com/vim/vim/blob/master/runtime/ftplugin/markdown.vim#L10

maybe change to `source $VIMRUNTIME/ftplugin/html.vim` or something. Why would anyone ever want their html ftplugins from their user vim config sourced when editing markdown?

**Comment by andymass** [comment]
This seems expected, to me.. markdown is based on the html ftplugin, so if vim loads the built-in ftplugin why wouldn't it load your customizations too?  Specifically what kind of issues is it causing you?
 
(ps if you want support for an ftplugin you are better off contacting the maintainer: https://github.com/tpope/vim-markdown)

**Comment by dylnmc** [comment]
you think when I open *.md then ~/.vim/after/ftplugin/html.vim should be loaded? Not vimruntime stuff - **my** vim config...

Specifically, I do `inoremap <buffer> ...` in ~/.vim/after/ftplugin/html.vim and I don't want html crap in markdown files because html is not markdown.(??)

**Comment by bfrg** [comment]
Couldn't you just check the `filetype` in `after/ftplugin/html.vim` file:
```vim
if &filetype ==# 'html'
    " stuff that's only for html
endif
```
I do something similar for for `c` and `cpp`.

**Comment by dylnmc** [comment]
I could

**Comment by chrisbra** [comment]
closing, as this is not a vim issue.
