### ISSUE TITLE
:resize after :term causes SEGV

### ISSUE THREAD

**Issue by ghost** [vim/vim#6362]
**Description**
Program crashes immediately

**To Reproduce**
1. Open Vim
2. Execute :term
3. Move cursor to original buffer (\<C-w\>w)
4. Execute :resize (or \<C-w\>_)
5. Vim crashes with SEGV

**Expected behavior**
Expected resize window to maximum size (as described in :h resize)

    Set current window height to N (default: highest possible).

**Environment (please complete the following information):**
 - Vim version 8.2
 - OS: Arch Linux 5.7.5-arch1-1
 - Terminal: sakura, xterm

**Additional context**
This also seems to happen sometimes with other commands related to resizing windows not mentioned here.

**Comment by lacygoill** [comment]
Which version are you using?  If it's lower than [8.2.1030](https://github.com/vim/vim/releases/tag/v8.2.1030), try to update and see whether you can still reproduce.

**Comment by ghost** [comment]
Apologies for not checking that. The Arch package (vim 8.2.0814-3) is behind. I cannot reproduce it on the current version. Thanks.
