### ISSUE TITLE
Commandline s:foo causes SEGV

### ISSUE THREAD

**Issue by Termplexed** [vim/vim#6366]
**SEGV when trying to access non-accessible namespace**

```vim
:let x = get(s:, 'foo', 'x')
:echo get(s:, 'foo', 'x')
```

***Edit:*** or simply:

```vim
echo s:foo
```

Works fine if sourced from script. (`:so% `)

**To Reproduce**

1. Run `vim --clean`
2. Execute `:echo get(s:, 'foo', 'x')`, or `:echo s:foo`
3. Result:

        Vim: Caught deadly signal SEGV
        Vim: Finished.

**Expected behavior**

> E121: Undefined variable: s:

**Environment:**

Natively:
 - Vim version 8.2.1052
 - OS: Ubuntu 18.04
 - Terminal: various

Tested on some vim-appimages with `./GVim-vXXX -v --clean`

Looks to have been introduced in v8.2.0961

https://github.com/vim/vim-appimage/compare/v8.2.0959...v8.2.0961

CRASH:
GVim-v8.2.1097.glibc2.15-x86_64.AppImage (latest)
GVim-v8.2.0961.glibc2.15-x86_64.AppImage

OK:
GVim-v8.2.0959.glibc2.15-x86_64.AppImage

**Comment by lacygoill** [comment]
- [backtrace](https://github.com/vim/vim/files/4855611/backtrace.txt)
- [valgrind log](https://github.com/vim/vim/files/4855612/valgrind.log)
- [asan log](https://github.com/vim/vim/files/4855610/asan.log)

**Comment by k-takata** [comment]
How about this patch?

```diff
--- a/src/vim9compile.c
+++ b/src/vim9compile.c
@@ -2336,9 +2336,13 @@ get_script_item_idx(int sid, char_u *nam
     imported_T *
 find_imported(char_u *name, size_t len, cctx_T *cctx)
 {
-    scriptitem_T    *si = SCRIPT_ITEM(current_sctx.sc_sid);
+    scriptitem_T    *si;
     int		    idx;
 
+    if (current_sctx.sc_sid <= 0)
+	return NULL;
+
+    si = SCRIPT_ITEM(current_sctx.sc_sid);
     if (cctx != NULL)
 	for (idx = 0; idx < cctx->ctx_imports.ga_len; ++idx)
 	{
```

**Comment by lacygoill** [comment]
Can confirm that the patch fixes the crash.  Now `:echo s:foo` correctly raises `E121`:

    E121: Undefined variable: s:foo
