### ISSUE TITLE
Patch 1222 doesn't apply

### ISSUE THREAD

**Issue by lindhobe** [vim/vim#637]
Concatenated all patches together for the big patch apply.  Got the following error message:

Perhaps you used the wrong -p or --strip option?
## The text leading up to this was:

|**\* ../vim-7.4.1221/src/version.c      2016-01-31 14:36:53.419217174 +0100
|--- src/version.c      2016-01-31 14:49:11.627530146 +0100
## |--- 222,226 ----

File to patch: 
Skip this patch? [y] 
Skipping patch.
1 out of 1 hunk ignored

**Comment by chrisbra** [comment]
Is there a reason, you are not getting the source directly from the repository?

**Comment by brammool** [comment]
lindhobe wrote:

> Concatenated all patches together for the big patch apply.  Got the following error message:
> 
> Perhaps you used the wrong -p or --strip option?
> 
> ## The text leading up to this was:
> 
> |**\* ../vim-7.4.1221/src/version.c      2016-01-31 14:36:53.419217174 +0100
> |--- src/version.c      2016-01-31 14:49:11.627530146 +0100
> 
> ## |--- 222,226 ----
> 
> File to patch: 
> Skip this patch? [y] 
> Skipping patch.
> 1 out of 1 hunk ignored

I don't see anything special about this patch.  1222 was wrong some time
ago, but I fixed it.

## 

press CTRL-ALT-DEL for more information

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lindhobe** [comment]
The last few lines of patch 7.4.1222 read as follows:

**\* ../vim-7.4.1221/src/version.c       2016-01-31 14:36:53.419217174 +0100
--- src/version.c       2016-01-31 14:49:11.627530146 +0100
--- 222,226 ----

---

**\* 748,749 ****
--- 744,747 ----
  {   /\* Add new patch number below this line */
- /**/
-     1222,
  /**/

If I change it to the following, everything applies cleanly:

**\* ../vim-7.4.1221/src/version.c       2016-01-31 14:36:53.419217174 +0100
--- src/version.c       2016-01-31 14:49:11.627530146 +0100

---

**\* 744,745 ****
--- 744,747 ----
  {   /\* Add new patch number below this line */
- /**/
-     1222,
  /**/

The --- 222,226 --- line seems to be spurious and is the source of the patching failure.  The **\* 748,749 **\* line works, but applies without offset if changed to **\* 744,745 ***.

And as for why I'm not getting my source directly from the repository...  Old habit.  Many moons ago I wrote a script to fetch patches from the ftp server and a second script to build vim with all patches applied.  And for FWIW, it looks like the bulk of patch 7.4.1222 worked properly.  Only the change to src/version.c failed to apply.

**Comment by mattn** [comment]
could you please quote diff with triple backticks like below?

``````
```
*** ../vim-7.4.1221/src/version.c 2016-01-31 14:36:53.419217174 +0100
--- src/version.c 2016-01-31 14:49:11.627530146 +0100
--- 222,226 ----
... content ...
```
``````

**Comment by lindhobe** [comment]
Trying again with triple back-ticks...  Still learning this GitHub thing.

Original:

```
*** ../vim-7.4.1221/src/version.c       2016-01-31 14:36:53.419217174 +0100
--- src/version.c       2016-01-31 14:49:11.627530146 +0100
--- 222,226 ----
***************
*** 748,749 ****
--- 744,747 ----
  {   /* Add new patch number below this line */
+ /**/
+     1222,
  /**/
```

Fixed:

```
*** ../vim-7.4.1221/src/version.c       2016-01-31 14:36:53.419217174 +0100
--- src/version.c       2016-01-31 14:49:11.627530146 +0100
***************
*** 744,745 ****
--- 744,747 ----
  {   /* Add new patch number below this line */
+ /**/
+     1222,
  /**/
```

**Comment by mattn** [comment]
Thanks.

**Comment by brammool** [comment]
lindhobe wrote:

> The last few lines of patch 7.4.1222 read as follows:
> 
> **\* ../vim-7.4.1221/src/version.c       2016-01-31 14:36:53.419217174 +0100
> --- src/version.c       2016-01-31 14:49:11.627530146 +0100
> --- 222,226 ----
> 
> ---
> 
> **\* 748,749 ****
> --- 744,747 ----
>   {   /\* Add new patch number below this line */
> - /**/
> -     1222,
>   /**/
> 
> If I change it to the following, everything applies cleanly:
> 
> **\* ../vim-7.4.1221/src/version.c       2016-01-31 14:36:53.419217174 +0100
> --- src/version.c       2016-01-31 14:49:11.627530146 +0100
> 
> ---
> 
> **\* 744,745 ****
> --- 744,747 ----
>   {   /\* Add new patch number below this line */
> - /**/
> -     1222,
>   /**/
> 
> The --- 222,226 --- line seems to be spurious and is the source of the
> patching failure.  The **\* 748,749 **\* line works, but applies without
> offset if changed to **\* 744,745 ***.

Well spotted!  I'll fix that.

> And as for why I'm not getting my source directly from the
> repository...  Old habit.  Many moons ago I wrote a script to fetch
> patches from the ftp server and a second script to build vim with all
> patches applied.  And for FWIW, it looks like the bulk of patch
> 7.4.1222 worked properly.  Only the change to src/version.c failed to
> apply.

I'm still uploading the patches, also as an old habit.  I will stop
doing that some day.  I assume there are still people with a system
without git or mercurial.  The long tail of systems with a limited set
of tools, e.g. headless servers, where one does want to use Vim.
However, it should be possible to get a tar or zip file from github, if
we write down how to do that, and it actually works, perhaps I can stop
putting patches on the ftp site.

Ah, it's actually quite simple:
https://github.com/vim/vim/archive/v7.4.1343.tar.gz
https://github.com/vim/vim/archive/v7.4.1343.zip

That doesn't allow for only getting the latest patches.  Perhaps github
also has a simple link for each patch? I only see the link with the
hash:
https://github.com/vim/vim/commit/cd39bbcd1dd5bdc280f0fa5833b1107853f1227f

## 

Facepalm statement #9: "Did you see, there is now even a hobbit book"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vyp** [comment]
@brammool I'm not sure if this is what you want, but you can append ".patch" to a commit url to get a _git_ patch file. e.g. https://github.com/vim/vim/commit/cd39bbcd1dd5bdc280f0fa5833b1107853f1227f.patch

**Comment by brammool** [comment]
vyp wrote:

> @brammool I'm not sure if this is what you want, but you can append
> ".patch" to a commit url to get a _git_ patch file. e.g.
> https://github.com/vim/vim/commit/cd39bbcd1dd5bdc280f0fa5833b1107853f1227f.patch

What I want is a URL that has the tag or patch number in it, not that
weird hash.

To answer my own question, I believe this works:
https://github.com/vim/vim/compare/v7.4.1222%5E...v7.4.1222.diff

The only problem being that the version.c diff disallows skipping a
patch, only works when applied in sequence.

## 

If I tell you "you have a beautiful body", would you hold it against me?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lindhobe** [comment]
The patch on the ftp server has been updated and applies cleanly, so I'm going to close out the case.  And afterward, I'll spend some time learning GitHub better, as I've clearly gotten behind the times.

Many thanks for the help.

**Comment by vyp** [comment]
Learning git as opposed to github which is just a git hosting service will probably be more useful, by the way.
