### ISSUE TITLE
Could I special the jpeg giflib libtiff libpng PATH when building vim

### ISSUE THREAD

**Issue by cxwx** [vim/vim#6383]
Hi, I'm using vim installed by homebrew on mac os X
But if I set environment 
```
export DYLD_LIBRARY_PATH=${DYLD_LIBRARY_PATH}:/usr/local/lib/
```
cause errors 
```
dyld: Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /usr/local/lib//libJPEG.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
```

because the homebrew version of vim conflict with lib `jpeg` `libpng` `libtiff` `giflib`
could I set an environment for not using these library when using VIM

**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

**Describe the solution you'd like**
set an environment for not using `jpeg` `libpng` `libtiff` `giflib` these library when using VIM

**Describe alternatives you've considered**

**Additional context**

**Comment by cxwx** [comment]
It seems if I run porgram inside vim for example:
```
nnoremap <F3> :w<CR>:!python %<CR>
```
```
press <F3>
```
doesn't load the environment `DYLD_LIBRARY_PATH` and cause the bug, 
and if a program is linked  with @rpath it also cause not found library.
so I think it's better if vim load program with all system environment set in .bashrc or .zshrc

**Comment by chrisbra** [comment]
where do you set this environment variable. I think you may want to set `shellcmdflag` option, e.g. so that your shell login file (`.bashrc`) is loaded as well.

**Comment by cxwx** [comment]
> where do you set this environment variable. I think you may want to set `shellcmdflag` option, e.g. so that your shell login file (`.bashrc`) is loaded as well.

that's what I wanted,

but could I load only DYLD_LIBRARY_PATH, because I don't want to run other part in my .bashrc or .zshrc

**Comment by chrisbra** [comment]
Again, so where do you set it? Try putting it into `.bash_profile` or `.profile`. This depends on your used shell however.

**Comment by cxwx** [comment]
I'm using zsh so I set it in .zshrc

**Comment by chrisbra** [comment]
so how about putting this into `.zshenv` profile file then?

**Comment by cxwx** [comment]
great, thanks.
cheers
