### ISSUE TITLE
Linter not working till I enter :diffoff command

### ISSUE THREAD

**Issue by lakshits11** [vim/vim#6384]
**Describe the bug**
 Every time I open gvim , I have to manually input command :diffoff else my linter will not work..as soon as I enter command, my linter starts working. I have tried other linters too. Issue is with every linter...its linter independent issue.
One more thing..when I run vim using command prompt in windows, Issue is not present.
Issue only present in gvim and vim.
 
**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run gvim
2. Open a file already present or create a new one
3. Type something with incorrect syntax...linter will not show this error
4. As soon as you give command :diffoff , the linter will show error

**Expected behavior**
How to resolve it ?

**Screenshots**
1. Before
![vim_during](https://user-images.githubusercontent.com/54276661/86479566-07025d80-bd6a-11ea-838a-e256519c25ef.PNG)

2.After entering command
![vim_after_diffoff](https://user-images.githubusercontent.com/54276661/86479586-11bcf280-bd6a-11ea-8df3-2d977d05f1f2.PNG)

**Environment (please complete the following information):**
 - Vim version [e.g. 8.2] (Or paste the result of `vim --version`.)
 - OS: Windows 10 1809
 - I use gvim.

**Comment by k-takata** [comment]
It looks like a plugin issue. Please ask the plugin maintainer.
Or, please provide a reproducible way using `vim --clean`.
