### ISSUE TITLE
Vim9: a line starting with "#" is not highlighted as a comment

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6388]
**Describe the bug**

A line starting with `#` is not highlighted as a comment.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        set ft=vim
        syn on
        call setline(1, ['vim9script', '# some comment'])
    EOF
    )

`#` is not highlighted; `some` and `comment` are highlighted with the highlight group `vimIsCommand`.

**Expected behavior**

`#`, `some` and `comment` are highlighted with the highlight group `vim9LineComment`.

**Environment**

 - Vim version: 8.2 Included patches: 1-1123
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(356)

**Additional context**

It looks like a bug, because there is nothing in the help which documents this requirement.

Although, there is this:

> White space must also be put before the # that starts a comment: >
>         let var = 234# Error!
>         let var = 234 # OK

But I think it's only relevant for an *inline* comment.  Not for a comment on a dedicated line.

And if `#` is not preceded by a space, the line is still ignored; meaning that Vim does not need a space before `#` to correctly parse the line as a comment.

---

The issue comes from this line:

<https://github.com/vim/vim/blob/1c991144c502ade477e1a32fdfd0f78b6299fdc7/runtime/syntax/vim.vim#L632>

I think it should be:

    syn match   vim9LineComment +^[ \t:]*#.*$+ contains=@vimCommentGroup,vimCommentString,vimCommentTitle
                                        ^
                                        instead of \+

---

/cc @cecamp.

**Comment by bfrg** [comment]
The `vimCommentTitle` group doesn't work either. Here's a patch that fixes it (including the changes proposed by @lacygoill):
```diff
diff --git a/runtime/syntax/vim.vim b/runtime/syntax/vim.vim
index d01cc40b..b0ff51e9 100644
--- a/runtime/syntax/vim.vim
+++ b/runtime/syntax/vim.vim
@@ -629,11 +629,11 @@ syn match vimCtrlChar     "[^A^K^O-^_]"
 " Beginners - Patterns that involve ^ {{{2
 " =========
 syn match      vimLineComment  +^[ \t:]*".*$+  contains=@vimCommentGroup,vimCommentString,vimCommentTitle
-syn match      vim9LineComment +^[ \t:]\+#.*$+ contains=@vimCommentGroup,vimCommentString,vimCommentTitle
-syn match      vimCommentTitle '"\s*\%([sS]:\|\h\w*#\)\=\u\w*\(\s\+\u\w*\)*:'hs=s+1    contained contains=vimCommentTitleLeader,vimTodo,@vimCommentGroup
+syn match      vim9LineComment +^[ \t:]*#.*$+  contains=@vimCommentGroup,vimCommentString,vimCommentTitle
+syn match      vimCommentTitle '["#]\s*\%([sS]:\|\h\w*#\)\=\u\w*\(\s\+\u\w*\)*:'hs=s+1 contained contains=vimCommentTitleLeader,vimTodo,@vimCommentGroup
 syn match      vimContinue     "^\s*\\"
 syn region     vimString       start="^\s*\\\z(['"]\)" skip='\\\\\|\\\z1' end="\z1" oneline keepend contains=@vimStringGroup,vimContinue
-syn match      vimCommentTitleLeader   '"\s\+'ms=s+1   contained
+syn match      vimCommentTitleLeader   '["#]\s\+'ms=s+1        contained
 
 " Searches And Globals: {{{2
 " ====================
```

**Comment by brammool** [comment]
@cecamp

**Comment by lacygoill** [comment]
> The vimCommentTitle group doesn't work either. Here's a patch that fixes it (including the changes proposed by @lacygoill):

Thank you very much.  I've noticed something else.  When `#` is used as a comment leader on an empty line inside a `:def` function, it's still not correctly highlighted (no issue at the script level):

    vim9script
    def Func()
        # some comment{{{
        #
        # foo
        # bar
        # baz
        #}}}
    enddef

I can fix the issue on my machine, by adding the syntax group `vim9LineComment` to the `vimFuncBodyList` cluster:
```diff
diff --git a/runtime/syntax/vim.vim b/runtime/syntax/vim.vim
index d01cc40bb..ef57171f2 100644
--- a/runtime/syntax/vim.vim
+++ b/runtime/syntax/vim.vim
@@ -236,7 +236,7 @@ endif
 " Functions : Tag is provided for those who wish to highlight tagged functions {{{2
 " =========
 syn cluster	vimFuncList	contains=vimCommand,vimFunctionError,vimFuncKey,Tag,vimFuncSID
-syn cluster	vimFuncBodyList	contains=vimAbb,vimAddress,vimAugroupKey,vimAutoCmd,vimCmplxRepeat,vimComment,vim9Comment,vimContinue,vimCtrlChar,vimEcho,vimEchoHL,vimExecute,vimIsCommand,vimFBVar,vimFunc,vimFunction,vimFuncVar,vimGlobal,vimHighlight,vimIsCommand,vimLet,vimLetHereDoc,vimLineComment,vimMap,vimMark,vimNorm,vimNotation,vimNotFunc,vimNumber,vimOper,vimOperParen,vimRegion,vimRegister,vimSearch,vimSet,vimSpecFile,vimString,vimSubst,vimSynLine,vimUnmap,vimUserCommand
+syn cluster	vimFuncBodyList	contains=vimAbb,vimAddress,vimAugroupKey,vimAutoCmd,vimCmplxRepeat,vimComment,vim9Comment,vim9LineComment,vimContinue,vimCtrlChar,vimEcho,vimEchoHL,vimExecute,vimIsCommand,vimFBVar,vimFunc,vimFunction,vimFuncVar,vimGlobal,vimHighlight,vimIsCommand,vimLet,vimLetHereDoc,vimLineComment,vimMap,vimMark,vimNorm,vimNotation,vimNotFunc,vimNumber,vimOper,vimOperParen,vimRegion,vimRegister,vimSearch,vimSet,vimSpecFile,vimString,vimSubst,vimSynLine,vimUnmap,vimUserCommand
 syn match	vimFunction	"\<\(fu\%[nction]\|def\)!\=\s\+\%(<[sS][iI][dD]>\|[sSgGbBwWtTlL]:\)\=\%(\i\|[#.]\|{.\{-1,}}\)*\ze\s*("	contains=@vimFuncList nextgroup=vimFuncBody
 
 if exists("g:vimsyn_folding") && g:vimsyn_folding =~# 'f'
@@ -629,11 +629,11 @@ syn match	vimCtrlChar	"[--]"
 " Beginners - Patterns that involve ^ {{{2
 " =========
 syn match	vimLineComment	+^[ \t:]*".*$+	contains=@vimCommentGroup,vimCommentString,vimCommentTitle
-syn match	vim9LineComment	+^[ \t:]\+#.*$+	contains=@vimCommentGroup,vimCommentString,vimCommentTitle
-syn match	vimCommentTitle	'"\s*\%([sS]:\|\h\w*#\)\=\u\w*\(\s\+\u\w*\)*:'hs=s+1	contained contains=vimCommentTitleLeader,vimTodo,@vimCommentGroup
+syn match	vim9LineComment	+^[ \t:]*#.*$+	contains=@vimCommentGroup,vimCommentString,vimCommentTitle
+syn match	vimCommentTitle	'["#]\s*\%([sS]:\|\h\w*#\)\=\u\w*\(\s\+\u\w*\)*:'hs=s+1	contained contains=vimCommentTitleLeader,vimTodo,@vimCommentGroup
 syn match	vimContinue	"^\s*\\"
 syn region	vimString	start="^\s*\\\z(['"]\)" skip='\\\\\|\\\z1' end="\z1" oneline keepend contains=@vimStringGroup,vimContinue
-syn match	vimCommentTitleLeader	'"\s\+'ms=s+1	contained
+syn match	vimCommentTitleLeader	'["#]\s\+'ms=s+1	contained
 
 " Searches And Globals: {{{2
 " ====================
```
But I'm not sure it's the right fix.

**Comment by lacygoill** [comment]
Fixed by https://github.com/vim/vim/commit/2547aa930b59f5e2bcb70e81d5a57ed461e59b4f.

---

I'll open separate issues for `vimCommentTitle`, and other issues related to comments, later.
