### ISSUE TITLE
Vim9: cannot use a bar after many commands inside a ":def" function

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6391]
**Describe the bug**

We can't use a bar after many commands inside a `:def` function.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            let x = 123
            redraw | echo x
        enddef
        Func()
    EOF
    )

`E121` is raised:

    Error detected while processing function <SNR>1_Func:
    line    2:
    E121: Undefined variable: x

**Expected behavior**

No error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-1126
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(356)

**Additional context**

No error is raised if you reverse the order of the `:echo` and `:redraw` commands:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            let x = 123
            echo x | redraw
        enddef
        Func()
    EOF
    )

And no error is raised if you remove the function:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        let x = 123
        redraw | echo x
    EOF
    )

---

The same issue affects functions:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            let x = 123
            reltime() | echo x
        enddef
        Func()
    EOF
    )

`:let`, `:const` and `:echo` are *not* affected:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            let x = 123
            let y = 456 | echo x
        enddef
        Func()
    EOF
    )

Most other Ex commands seem to be affected.

**Comment by brammool** [comment]
Bar after function isn't fixed yet.
