### ISSUE TITLE
Vim9: can't iterate over a list generated by some builtin functions inside a ":def" function

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6395]
**Describe the bug**

We can't iterate over a list generated by some builtin functions, inside a `:def` function.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            for n in repeat([1], 3)
                echo n
            endfor
        enddef
        defcompile
    EOF
    )

It raises `E1024`:

    Error detected while processing function <SNR>1_Func:
    line    1:
    E1024: need a List to iterate over

**Expected behavior**

No error is raised, and the `:for` loop iterates over the list `[1, 1, 1]`.

**Environment**

 - Vim version: 8.2 Included patches: 1-1127
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(356)

**Additional context**

The issue disappears if you run the code from outside the `:def` function:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        for n in repeat([1], 3)
            echo n
        endfor
    EOF
    )

Or from inside a legacy `:fu` function:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        fu Func()
            for n in repeat([1], 3)
                echo n
            endfor
        endfu
        Func()
    EOF
    )

---

As a workaround, one can explicitly specify the type of the list before trying to iterate over it:

    let alist: list<number> = repeat([1], 3)
             ^------------^

Test:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            let alist: list<number> = repeat([1], 3)
            for n in alist
                echo n
            endfor
        enddef
        defcompile
    EOF
    )

This makes me think that the issue is due to the return type of `repeat()` which is maybe wrong.

---

The issue also affects these functions:

     ┌─────────────────┬────────────────────────────────────────────────────┐
     │ function name   │ expression to use in the `:for` statement          │
     ├─────────────────┼────────────────────────────────────────────────────┤
     │ add()           │ add([1, 2], 3)                                     │
     ├─────────────────┼────────────────────────────────────────────────────┤
     │ argc()          │ argc()                                             │
     ├─────────────────┼────────────────────────────────────────────────────┤
     │ call()          │ call('range', [3])                                 │
     ├─────────────────┼────────────────────────────────────────────────────┤
     │ copy()          │ [1, 2, 3]->copy()                                  │
     ├─────────────────┼────────────────────────────────────────────────────┤
     │ deepcopy()      │ [1, 2, 3]->deepcopy()                              │
     ├─────────────────┼────────────────────────────────────────────────────┤
     │ eval()          │ '[1, 2, 3]'->eval()                                │
     ├─────────────────┼────────────────────────────────────────────────────┤
     │ expand()        │ expand('/tmp/*', 0, 1)                             │
     ├─────────────────┼────────────────────────────────────────────────────┤
     │ extend          │ extend([1, 2], [3])                                │
     ├─────────────────┼────────────────────────────────────────────────────┤
     │ filter()        │ [1, 2, 3]->filter('v:val')                         │
     ├─────────────────┼────────────────────────────────────────────────────┤
     │ get()           │ get([[1,2,3]], 0)                                  │
     ├─────────────────┼────────────────────────────────────────────────────┤
     │ getbufvar()     │ getbufvar('', 'var', [1, 2, 3])                    │
     ├─────────────────┼────────────────────────────────────────────────────┤
     │ getreg()        │ getreg('a', 1, 1)                                  │
     ├─────────────────┼────────────────────────────────────────────────────┤
     │ gettabvar()     │ gettabvar(1, 'var', [1, 2, 3])                     │
     ├─────────────────┼────────────────────────────────────────────────────┤
     │ gettabwinvar()  │ gettabwinvar(1, 1, 'var', [1, 2, 3])               │
     ├─────────────────┼────────────────────────────────────────────────────┤
     │ getwinvar()     │ getwinvar(1, 'var', [1, 2, 3])                     │
     ├─────────────────┼────────────────────────────────────────────────────┤
     │ glob()          │ glob('/tmp/*', 0, 1)                               │
     ├─────────────────┼────────────────────────────────────────────────────┤
     │ globpath()      │ globpath(&rtp, 'syntax/c.vim', 0, 1)               │
     ├─────────────────┼────────────────────────────────────────────────────┤
     │ insert()        │ insert([2, 3], 1)                                  │
     ├─────────────────┼────────────────────────────────────────────────────┤
     │ map()           │ [1, 2, 3]->map('v:val+1')                          │
     ├─────────────────┼────────────────────────────────────────────────────┤
     │ readfile()      │ readfile('/tmp/file')                              │
     ├─────────────────┼────────────────────────────────────────────────────┤
     │ reduce()        │ reduce([[1], [2], [3]], { acc, val -> acc + val }) │
     ├─────────────────┼────────────────────────────────────────────────────┤
     │ remove()        │ remove([1, 2, 3], 0, 1)                            │
     ├─────────────────┼────────────────────────────────────────────────────┤
     │ reverse()       │ [1, 2, 3]->reverse()                               │
     ├─────────────────┼────────────────────────────────────────────────────┤
     │ sign_undefine() │ sign_undefine([])                                  │
     └─────────────────┴────────────────────────────────────────────────────┘

I couldn't test these functions because I don't know how to use them:

 - `ch_evalexpr()`
 - `ch_evalraw()`
 - `luaeval()`
 - `mzeval()`
 - `perleval()`
 - `py3eval()`
 - `pyeval()`
 - `pyxeval()`
 - `remote_read()`
 - `rubyeval()`

The issue does *not* affect any of these functions:

 - `balloon_split()`
 - `flatten()`
 - `getbufinfo()`
 - `getbufline()`
 - `getchangelist()`
 - `getcompletion()`
 - `getcurpos()`
 - `getjumplist()`
 - `getline()`
 - `getloclist()`
 - `getmarklist()`
 - `getmatches()`
 - `getpos()`
 - `getqflist()`
 - `gettabinfo()`
 - `getwininfo()`
 - `getwinpos()`
 - `items()`
 - `keys()`
 - `matcharg()`
 - `matchlist()`
 - `matchstrpos()`
 - `popup_list()`
 - `prop_list()`
 - `prop_type_list()`
 - `range()`
 - `readdir()`
 - `readdirex()`
 - `screenchars()`
 - `searchpairpos()`
 - `searchpos()`
 - `sign_getdefined()`
 - `sign_getplaced()`
 - `sign_placelist()`
 - `sign_unplacelist()`
 - `sort()`
 - `spellbadword()`
 - `spellsuggest()`
 - `split()`
 - `str2list()`
 - `synconcealed()`
 - `synstack()`
 - `systemlist()`
 - `tabpagebuflist()`
 - `tagfiles()`
 - `taglist()`
 - `term_getansicolors()`
 - `term_getcursor()`
 - `term_getsize()`
 - `term_list()`
 - `term_scrape()`
 - `test_null_list()`
 - `timer_info()`
 - `uniq()`
 - `values()`
 - `win_findbuf()`
 - `win_id2tabwin()`
 - `win_screenpos()`
 - `winlayout()`

**Comment by lacygoill** [comment]
I was also trying to determine whether the issue affected a list generated by a custom function, but I get unexpected and contradicting results:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Foo()
            return [1, 2, 3]
        enddef
        def Func()
            for n in Foo()
                echo n
            endfor
        enddef
        defcompile
    EOF
    )

This raises the errors `E1013` and `E1024`:

    Error detected while processing function <SNR>1_Foo:
    line    1:
    E1013: type mismatch, expected void but got list<number>
    Error detected while processing function <SNR>1_Func:
    line    1:
    E1024: need a List to iterate over

Which seems to suggest that custom functions are also affected.

But if I rename `Foo()` into `GetList()`, no error is raised:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def GetList()
            return [1, 2, 3]
        enddef
        def Func()
            for n in GetList()
                echo n
            endfor
        enddef
        defcompile
    EOF
    )

Which seems to suggest that custom functions are not affected.

Why does the name of the custom function generating the list have any influence on the results?

**Comment by brammool** [comment]
You forgot to specify the return type of GetList().  I'll make the error more clear.
I don't see why you get no errors later. Perhaps it doesn't try to compile the function again?

**Comment by bfrg** [comment]
The following patch seems to fix the issue with `repeat()`:
```diff
diff --git a/src/evalfunc.c b/src/evalfunc.c
index 8d81f151..072ba029 100644
--- a/src/evalfunc.c
+++ b/src/evalfunc.c
@@ -818,7 +818,7 @@ static funcentry_T global_functions[] =
     {"remote_startserver", 1, 1, FEARG_1, ret_void,     f_remote_startserver},
     {"remove",         2, 3, FEARG_1,    ret_any,      f_remove},
     {"rename",         2, 2, FEARG_1,    ret_number,   f_rename},
-    {"repeat",         2, 2, FEARG_1,    ret_any,      f_repeat},
+    {"repeat",         2, 2, FEARG_1,    ret_first_arg, f_repeat},
     {"resolve",                1, 1, FEARG_1,    ret_string,   f_resolve},
     {"reverse",                1, 1, FEARG_1,    ret_any,      f_reverse},
     {"round",          1, 1, FEARG_1,    ret_float,    FLOAT_FUNC(f_round)},
```

**Comment by brammool** [comment]
I'll see if other functions can have a more specific type.  But for some it won't be possible, such as getwinvar().  The type then has to be checked at runtime.  Let's do that last, so that we can spot functions that return "any" while they should not.
