### ISSUE TITLE
Vim9: can't use "setline()" as a method in a ":def" function

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6398]
**Describe the bug**

We can't use `setline()` as a method in a `:def` function.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            ['aaa', 'bbb', 'ccc']->setline(1)
        enddef
        Func()
    EOF
    )

`E745` is raised:

    Error detected while processing function <SNR>1_Func:
    line    1:
    E745: Using a List as a Number

**Expected behavior**

No error is raised, and the lines `aaa`, `bbb`, `ccc` are put in the buffer.

**Environment**

 - Vim version: 8.2 Included patches: 1-1127
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(356)

**Additional context**

The issue disappears in a legacy `:fu` function:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        fu Func()
            eval ['aaa', 'bbb', 'ccc']->setline(1)
        endfu
        call Func()
    EOF
    )

And outside any function:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        ['aaa', 'bbb', 'ccc']->setline(1)
    EOF
    )

**Comment by bfrg** [comment]
This is related to #6305.
