### ISSUE TITLE
Vim9: calling a ":def" function containing an undeclared variable closes the current window

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6399]
**Describe the bug**

Calling a `:def` function containing an undeclared variable causes Vim to close the current window.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            x = 1
        enddef
        Func()
    EOF
    )

Vim quits immediately.

**Expected behavior**

Vim doesn't quit; and *maybe* an error is raised to let the user know that they forgot to declare their variable.

**Environment**

 - Vim version: 8.2 Included patches: 1-1137
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(356)

**Additional context**

Vim really closes the current window; it doesn't necessarily quit the entire session:

    vim -Nu NONE -o /tmp/file{1..3} -S <(cat <<'EOF'
        vim9script
        def g:Func()
            x = 1
        enddef
        win_execute(win_getid(3), 'call g:Func()')
    EOF
    )

Here, notice how the third window is closed because that's where `Func()` is run.

**Comment by brammool** [comment]
"x" is a valid Ex command, :xit.  Thus this is expected.
If "x" is declared, then this takes priority over the :xit command.
You would have to use ":x" (including the leading colon) to use the :xit command.

**Comment by lacygoill** [comment]
I understand the rationale, but I would still consider the possibility of adding `:xit` to the list of commands which are disallowed in Vim9 script (along with `:append`, `:change`, `:insert`):
https://github.com/vim/vim/blob/0aac67a4314d72a29d3fbee91b6f0ba89e950462/runtime/doc/vim9.txt#L350-L352

For the same reason.  `:x` can also be confused with the local variable name `x`.
And if we want to run the legacy `:x`, we can still use `:exit` which is more readable anyway.

**Comment by brammool** [comment]
This is a balance between consistency, same rules for all Ex commands, and what more than a few users may make a mistake with.  Using '"x" for a variable name should be quite common, while using "x" for ":xit" in a :def function would be very uncommon.  Suppose we make an exception just for using "x", give an error for undeclared variable.  Using "xi" or "xit" would be very uncommon, but not handling them like "x" would be even more inconsistent.
Using "exit" is indeed a lot more obvious.  I would even recommend it.  I guess ":x" was just used for quick typing in the old days.

**Comment by lacygoill** [comment]
Thank you for the patch.  Another command which is similar to `:x` is `:t`; it has a much more readable synonym: `:copy`.
