### ISSUE TITLE
Vim9: can't refer to an outer function variable in a "map()" eval string

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6401]
**Describe the bug**

We can't refer to an outer function variable in a `map()` eval string.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def EvalString()
            let l = ['aaa', 'bbb', 'ccc', 'ddd']
            range(1, 2)->map('l[v:val]')
        enddef
        EvalString()
    EOF
    )

`E121` is raised:

    Error detected while processing function <SNR>1_EvalString:
    line    2:
    E121: Undefined variable: l

**Expected behavior**

No error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-1145
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(356)

**Additional context**

The issue persists when you prefix the function calls with `:call`:

    call range(1, 2)->map('l[v:val]')
    ^--^

And with `:eval`:

    eval range(1, 2)->map('l[v:val]')
    ^--^

---

The issue disappears in a legacy `:fu` function:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        fu EvalString()
            let l = ['aaa', 'bbb', 'ccc', 'ddd']
            call range(1, 2)->map('l[v:val]')
        endfu
        EvalString()
    EOF
    )

**Comment by brammool** [comment]
> **Describe the bug**
> 
> We can't refer to an outer function variable in a `map()` eval string.
> 
> **To Reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(cat <<'EOF'
>         vim9script
>         def EvalString()
>             let l = ['aaa', 'bbb', 'ccc', 'ddd']
>             range(1, 2)->map('l[v:val]')
>         enddef
>         EvalString()
>     EOF
>     )
> 
> `E121` is raised:
> 
>     Error detected while processing function <SNR>1_EvalString:
>     line    2:
>     E121: Undefined variable: l
> 
> **Expected behavior**
> 
> No error is raised.

This is not going to work.  The local variables are on the stack and
cannot be accessed outside of the compiled function.

Instead use a lambda:

	def EvalString(): list<string>
	  let list = ['aaa', 'bbb', 'ccc', 'ddd']
	  return range(1, 2)->map({ k, v -> list[v] })
	enddef
	echo EvalString()


-- 
The fastest way to get an engineer to solve a problem is to declare that the
problem is unsolvable.  No engineer can walk away from an unsolvable problem
until it's solved.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
