### ISSUE TITLE
Vim9: 'comments' option doesn't take into account the "#" comment leader

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6403]
**Describe the bug**

The `'comments'` option doesn't take into account the `#` comment leader.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        pu!=['vim9script', '# some comment']
        filetype plugin on
        set ft=vim fo+=o
    EOF
    )

Press `o` to open a new line below `# some comment`: the new line does not start with `#`.

**Expected behavior**

The new line starts with `#`, because `'formatoptions'` contains the `o` flag, and Vim has automatically inserted the comment leader matching the one used on the line above.

**Environment**

 - Vim version:  8.2 Included patches: 1-1145
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(356)

**Additional context**

I've somewhat fixed the issue by writing this in `~/.vim/after/ftplugin/vim.vim`:

    let &l:comments ..= ',' .. substitute(&l:comments, '"', '#', 'g')

I naively thought something similar could be done in the default Vim filetype plugin:

<https://github.com/vim/vim/blob/0ad3e894d75236915e67dfbbcc821b6bb3c05d91/runtime/ftplugin/vim.vim#L52>

But I think it's wrong since `#` seems to be parsed as a comment leader only if the first line of the script is `vim9script`.  With the exception that the latter can be preceded by lines commented with `"`, but not by lines commented with `#`.  So, I don't know how it can be fixed.

**Comment by brammool** [comment]
Let's just support # comments, then at least the formatting should be OK.  In legacy Vim script :# is a rarely used command.
