### ISSUE TITLE
vim9script: def functions that are used in sort() need to be exported and imported in other script files

### ISSUE THREAD

**Issue by bfrg** [vim/vim#6412]
**Describe the bug**
`def` functions that are used in `sort()`, `filter()` and friends always need to be exported and imported in other script files. 

For example, if `MyCompare()` is used as the sorting function inside `FastSort()`, it is not enough to just import `FastSort()` in another script file. `MyCompare()` needs to be exported and imported as well at the moment. Doing the same with `filter()` will crash Vim.

**To Reproduce**
1. Create the following two files in the same directory:
```vim
" sort.vim
vim9script
def Compare(i1: number, i2: number): number
    return 1
enddef

export def FastSort(): list<number>
    return range(5)->sort('Compare')
enddef
```
```vim
" test.vim
vim9script
import FastSort from './sort.vim'
def Test()
    let x: list<number> = FastSort()
enddef
Test()
```
2. Now run `vim --clean -S test.vim`. This will print the following error:
```
 Error detected while processing function <SNR>108_Test[2]..<SNR>109_FastSort:
 line    1:
 E117: Unknown function: Compare
 E702: Sort compare function failed
```
3. It works fine when I call `FastSort()` directly:
```vim
" test2.vim (this one works)
import FastSort from './sort.vim'
echo FastSort()
```
4. Exporting and importing the `Compare` function works, too (but I would like to keep the function script-local):
```vim
" test3.vim (this one works)
import {Compare, FastSort} from './sort.vim'
def Test()
    let x: list<number> = FastSort()
enddef
Test()
```
---
Similar errors occur with functions `map()` and `filter()`. Replacing `sort()` and its compare function by `filter()` and a filter function prints the following error:
```
Error detected while processing function <SNR>14_Test[1]..<SNR>15_FastFilter:
line    1:
E121: Undefined variable: FilterFunc
```
I tried to export the filter function like in the `sort()` case (see 4.), but this will crash Vim:
```vim
" filter.vim
vim9script
export def FilterFunc(idx: number, val: number): bool
    return idx % 2 == 1
enddef

export def FastFilter(): list<number>
    return range(10)->filter('FilterFunc')
enddef
```
```vim
" crash.vim
import {FilterFunc, FastFilter} from './filter.vim'
def Test()
    let x: list<number> = FastFilter()
enddef
Test()
```
Running `vim --clean -S crash.vim` results in:
```
Vim: Caught deadly signal SEGV
Vim: Finished.
Segmentation fault
```

**Expected behavior**
`def` functions used in `sort()` and friends shouldn't be required to be exported and then imported in other script files when the functions using those functions are already imported. And no segmentation faults.

**Environment**
Vim version `8.2.1127`

**Additional context**
So far I had my new `def` functions in the `autoload` directory. I started moving them into the `import` directory as suggested under `Import in an autoload script` in the documentation. This is obviously not necessary but I thought I give it a shot.

For example, I have a command to sort a quickfix list by filename and line+column number. Previously I had:
```vim
" autoload/qf/sort.vim
vim9script
def QfSort(item1: dict<any>, item2: dict<any>): number
    if item1.bufnr != item2.bufnr
        return bufname(item1.bufnr) ># bufname(item2.bufnr) ? 1 : -1
    elseif item1.lnum != item2.lnum
        return item1.lnum > item2.lnum ? 1 : -1
    elseif item1.col != item2.col
        return item1.col > item2.col ? 1 : -1
    endif
    return 0
enddef

def qf#sort#qflist()
    let info: dict<any> = getqflist({'title': 1, 'context': 1})
    getqflist()->sort('QfSort')->setqflist('r')
    setqflist([], 'r', info)
enddef

" after/ftplugin/qf.vim
command! -buffer Sort call qf#sort#qflist()
```

Then I tried to move the content into `import/qf/sort.vim`. The `autoload/qf/sort.vim` script reduces to:
```vim
vim9script
import QfSortList from 'qf/sort.vim'
def qf#sort#qflist()
    QfSortList()
enddef
```
And this is where I encountered the above errors. I'm not quite sure if that's how it was intended to be used.

**NB:** The new `vim9script` sort function runs approximately 3.5x faster than my old one.

**Comment by lacygoill** [comment]
> I tried to export the filter function like in the sort() case (see 4.), but this will crash Vim:

 - [backtrace](https://github.com/vim/vim/files/4882828/backtrace.txt)
 - [valgrind log](https://github.com/vim/vim/files/4882829/valgrind.log)
 - [asan log](https://github.com/vim/vim/files/4882827/asan.log)

---

> NB: The new vim9script sort function runs approximately 3.5x faster than my old one.

This is consistent with what I observed when rewriting a legacy function into Vim9 to format entries in a quickfix list.  5 times faster [in this case](https://github.com/vim/vim/pull/5465#issuecomment-653919272), 3.5 times faster [in that case](https://vi.stackexchange.com/a/26273/17449).
