### ISSUE TITLE
vim9script: E492: Not an editor command: test.data->sort()

### ISSUE THREAD

**Issue by bfrg** [vim/vim#6418]
**Describe the bug**
Vim throws an error when an expression like `test.data->sort()` is called inside a `:def` function. Currently, the expression works only with `eval`.

**To Reproduce**
1. Run `vim --clean -S test.vim`, with
```vim
" test.vim
vim9script
def Test()
    let test: dict<list<number>> = {'data': [1,2,3]}
    test.data->sort()
enddef
Test()
```
2. Vim will print the following error:
```
Error detected while processing function <SNR>112_Test:
line    2:
E492: Not an editor command:     test.data->sort()
```
3. Prepending the expression with `eval` works though:
```vim
vim9script
def Test()
    let test: dict<list<number>> = {'data': [1,2,3]}
    eval test.data->sort()
enddef
Test()
```
4. When a variable `x` is declared, the expression `x.data->sort()` will close Vim (somehow related to #6399):
```vim
vim9script
def Test()
    let x: dict<list<number>> = {'data': [1,2,3]}
    x.data->sort()
enddef
Test()
```

**Expected behavior**
I expected the expression `dict.data->sort()` to work without `eval` inside a `def` function. It should also be possible to declare variables named `x` without side effects.

**Environment**
 - Vim version `8.2.1152`

**Comment by bfrg** [comment]
Why doesn't `defcompile` print the error? Instead I need to explicitly call the function `Test()`. Shouldn't the error be detected during compilation?

**Comment by brammool** [comment]
If the parser doesn't recognize a line, it uses an EXEC instruction.  This was from when some commands were still missing.  I'll change it to give an error when a command isn't recognized, then we might get some errors where the parsing doesn't work properly, please report them.
