### ISSUE TITLE
"\|" removes highlighting when typed as part of "very magic" patterns in the commands connected with 'incsearch' (":search", ":global", etc)

### ISSUE THREAD

**Issue by lkintact** [vim/vim#6420]
**To Reproduce**
1. Run `gvim.exe --clean`
2. Type `abc|def` in the buffer
3. Type `:%s/\vabc\|` in the command line
4. The `abc|` part doesn't get highlighted

**Expected behavior**
`abc|` should get highlighted

**Environment**
 - Vim: 8.2.1145
 - OS: Windows 10 Home 1803
 - Terminal: GUI

**Comment by lkintact** [comment]
FWIW, the issue doesn't affect the `/` and `?` commands, e.g. typing `/\vabc\|` in the command line does highlight `abc|`.

**Comment by lkintact** [comment]
Also, if you continue `:%s/\vabc\|` at step 3 to `:%s/\vabc\|d`, the highlighting (of `abc|d` in the buffer) shows again.

**Comment by lkintact** [comment]
Still the same in 8.1.1377:

`/\vabc\|` highlights `abc|`
`:%s/\vabc\|` doesn't highlight `abc|`

Could anybody please confirm/refute reproducibility?

**Comment by chrisbra** [comment]
can reproduce, will have a look shortly

**Comment by chrisbra** [comment]
Well, Vim is guessing, that the pattern matches everywhere. The fault lies in `empty_pattern()`. It sees the `\|` at the end of the pattern and so vim thinks this pattern matches everywhere and stops highlighting (in order to prevent a blinking christmas like terminal). 

We could probably be a bit smarter by using something like the following patch, which does detect a leading `\v` and keeps on highlighting a trailing `\|`. But it still is guessing more or less (try moving the `\v` to a different position and it will start to fail again). So not sure this is worth the trouble or just live with it that this guesswork will never be completely correct.

```patch
diff --git a/src/ex_getln.c b/src/ex_getln.c
index 7afed52c9..d27a18914 100644
--- a/src/ex_getln.c
+++ b/src/ex_getln.c
@@ -94,7 +94,13 @@ empty_pattern(char_u *p)
     while (n >= 2 && p[n - 2] == '\\'
                          && vim_strchr((char_u *)"mMvVcCZ", p[n - 1]) != NULL)
        n -= 2;
-    return n == 0 || (n >= 2 && p[n - 2] == '\\' && p[n - 1] == '|');
+    // true, if the pattern is empty, or the pattern ends with \|
+    // (but only, if it does not start with \v
+    // (or if it does, it ends with '|' but not with '\|')
+    return n == 0 ||
+       (n >= 2 && p[n - 2] == '\\' && p[n - 1] == '|' &&
+       !(p[0] == '\\' && p[1] == 'v')) ||
+       (n >= 2 && p[0] == '\\' && p[1] == 'v' && p[n -2 ] != '\\' && p[n - 1] == '|');
 }

 // Struct to store the viewstate during 'incsearch' highlighting.
```

**Comment by chrisbra** [comment]
@brammool if you think this is actually worth to be included, let me know and I'll change it to a proper patch (including a screen test).

**Comment by brammool** [comment]
Christian wrote:

> Well, Vim is guessing, that the pattern matches everywhere. The fault
> lies in `empty_pattern()`. It sees the `\|` at the end of the pattern
> and so vim thinks this pattern matches everywhere and stops
> highlighting (in order to prevent a blinking christmas like terminal). 
> 
> We could probably be a bit smarter by using something like the
> following patch, which does detect a leading `\v` and keeps on
> highlighting a trailing `\|`. But it still is guessing more or less
> (try moving the `\v` to a different position and it will start to fail
> again). So not sure this is worth the trouble or just live with it
> that this guesswork will never be completely correct.
> 
> ```patch
> diff --git a/src/ex_getln.c b/src/ex_getln.c
> index 7afed52c9..d27a18914 100644
> --- a/src/ex_getln.c
> +++ b/src/ex_getln.c
> @@ -94,7 +94,13 @@ empty_pattern(char_u *p)
>      while (n >= 2 && p[n - 2] == '\\'
>                           && vim_strchr((char_u *)"mMvVcCZ", p[n - 1]) != NULL)
>         n -= 2;
> -    return n == 0 || (n >= 2 && p[n - 2] == '\\' && p[n - 1] == '|');
> +    // true, if the pattern is empty, or the pattern ends with \|
> +    // (but only, if it does not start with \v
> +    // (or if it does, it ends with '|' but not with '\|')
> +    return n == 0 ||
> +       (n >= 2 && p[n - 2] == '\\' && p[n - 1] == '|' &&
> +       !(p[0] == '\\' && p[1] == 'v')) ||
> +       (n >= 2 && p[0] == '\\' && p[1] == 'v' && p[n -2 ] != '\\' && p[n - 1] == '|');
>  }
> 
>  // Struct to store the viewstate during 'incsearch' highlighting.
> ```

It could be made a bit more accurate by using skip_regexp_ex(), it
detects the magicness.  Need to add a way to return "mymagic".

-- 
Nothing is impossible for the man who doesn't have to do it.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
