### ISSUE TITLE
getchar() return <80><fd>d when move cursor

### ISSUE THREAD

**Issue by wsdjeg** [vim/vim#6424]
**Describe the bug**

after calling `popup_create()` function, `echom getchar()` return `<80><fd>d` when move mouse
**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean` (or `gvim --clean`, etc.)
2. open popup
3. `echo getchar()`
4. move mouse

**Expected behavior**
nothing huppend

**Screenshots**
If applicable, copy/paste the text or add screenshots to help explain your problem.

**Environment (please complete the following information):**
- OS: windows
- gvim version: 8.1.2120

**Additional context**
vim print `<80><fd>d`

**Comment by lacygoill** [comment]
[8.1.2120](https://github.com/vim/vim/releases/tag/v8.1.2120) is 9 months old.  Since then, a lot of commits have been pushed including:

 - [8.2.1015](https://github.com/vim/vim/releases/tag/v8.2.1015) popup filter gets key with modifier prepended
 - [8.2.1019](https://github.com/vim/vim/releases/tag/v8.2.1019) mapping <M-S-a> does not work in the GUI

Can you reproduce on master?

**Comment by chrisbra** [comment]
FWIW, I can reproduce with 8.2.1114 using: 

    gvim --clean --cmd ":set encoding=utf-8" -c "call popup_create('foobar', {})" -c "redraw!" -c "echo getchar()"

**Comment by lacygoill** [comment]
Ah true, I can reproduce on 8.2.1164 too with your command.

**Comment by chrisbra** [comment]
Well, we can specifically ignore the MOUSEMOVE key by using this patch:

```patch
diff --git a/src/getchar.c b/src/getchar.c
index 2beffa578..c656ec371 100644
--- a/src/getchar.c
+++ b/src/getchar.c
@@ -1928,7 +1928,10 @@ plain_vgetc(void)

     do
        c = safe_vgetc();
-    while (c == K_IGNORE || c == K_VER_SCROLLBAR || c == K_HOR_SCROLLBAR);
+    while (c == K_IGNORE ||
+           c == K_VER_SCROLLBAR ||
+           c == K_HOR_SCROLLBAR) ||
+           c == K_MOUSEMOVE);

     if (c == K_PS)
        // Only handle the first pasted character.  Drop the rest, since we

```

But I doubt it is correct. However I am not sure where to handle the Mouseevent specifically in the various getchar functions.

**Comment by brammool** [comment]
It doesn't appear useful to get mouse-move events through getchar().  Ignoring them in plain_vgetc() is probably not the right spot though.

**Comment by wsdjeg** [comment]
Thanks for your work.

**Comment by wsdjeg** [comment]
@brammool thanks, But when we remove this event, how do we handle mouse-move event? This is useful to redraw popup without click mouse!

**Comment by chrisbra** [comment]
Why would you need to redraw on mouse move event?

**Comment by wsdjeg** [comment]
show doc for a word wothout move cursor。show info in popup based on mouse position。

**Comment by bfrg** [comment]
You can use `ballonexpr` for mouse-move events, see `:h ballonexpr` and `:h popup_beval-example`.
