### ISSUE TITLE
Install vim from source with +xterm_clipboard on MacOS

### ISSUE THREAD

**Issue by ep4sh** [vim/vim#6428]
Hey guys, could somebody help me with vim installation on macOS with +xterm_clipboard  enabled option?
I don't see any kind option in configure, how can I configure it?
I tried the option below, but it doesn't work for me:
```
./configure --prefix=/usr/local --mandir=/usr/local/Cellar/vim/8.2.1150/share/man --enable-multibyte --with-tlib=ncurses --enable-cscope --enable-terminal 
```

**Comment by chrisbra** [comment]
Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here.
