### ISSUE TITLE
folds close with autocomplete

### ISSUE THREAD

**Issue by nhooyr** [vim/vim#643]
Create a file that looks like this (main.go)

``` go
package main

import (
    "fmt"
)

func main() {
    fm
    fmt.Print("lmao")
}
```
1. `vim -N -u NONE main.go`
2. `:set foldmethod=indent`
3. `7jA`. 
4. `<c-x><c-l>`. 

Bam the fold gets closed.

**Comment by vim-ml** [comment]
Hi Anmol!

On Mi, 17 Feb 2016, Anmol Sethi wrote:

> Create a file that looks like this (main.go)
> 
> ``` go
> package main
> 
> import (
>   "fmt"
> )
> 
> func main() {
>   fm
>   fmt.Print("lmao")
> }
> ```
> 
> Now open it with vim as so
> 
> ``` zsh
> vim -N -u NONE main.go
> ```
> 
> First do `:set foldmethod=indent`
> 
> Now type `7jA`. Now press `<c-x><c-l>`. Bam the fold gets closed.

I think, this fixes it:

``` patch
diff --git a/src/edit.c b/src/edit.c
index d6d31f9..cbca9b6 100644
--- a/src/edit.c
+++ b/src/edit.c
@@ -1429,8 +1429,10 @@ doESCkey:

 docomplete:
            compl_busy = TRUE;
+           disable_fold++;
            if (ins_complete(c) == FAIL)
                compl_cont_status = 0;
+           disable_fold--;
            compl_busy = FALSE;
            break;
 #endif /* FEAT_INS_EXPAND */
diff --git a/src/fold.c b/src/fold.c
index e0b2609..5731285 100644
--- a/src/fold.c
+++ b/src/fold.c
@@ -811,6 +811,9 @@ foldUpdate(win_T *wp, linenr_T top, linenr_T bot)
 {
     fold_T     *fp;

+    if (disable_fold)
+       return;
+
     /* Mark all folds from top to bot as maybe-small. */
     (void)foldFind(&wp->w_folds, top, &fp);
     while (fp < (fold_T *)wp->w_folds.ga_data + wp->w_folds.ga_len
diff --git a/src/globals.h b/src/globals.h
index b43f1a2..db98584 100644
--- a/src/globals.h
+++ b/src/globals.h
@@ -1179,6 +1179,10 @@ EXTERN int       fill_fold INIT(= '-');
 EXTERN int     fill_diff INIT(= '-');
 #endif

+#ifdef FEAT_FOLDING
+EXTERN int     disable_fold INIT(= FALSE);
+#endif
+
 /* Whether 'keymodel' contains "stopsel" and "startsel". */
 EXTERN int     km_stopsel INIT(= FALSE);
 EXTERN int     km_startsel INIT(= FALSE);
```

Best,

## Christian

Alle sind schon sturzbetrunken, außer Reinhold, der den Wein
holt.

**Comment by nhooyr** [comment]
LGTM

**Comment by vim-ml** [comment]
What do we do now, how do we get this merged?

**Comment by vim-ml** [comment]
I went ahead and sent the patch in a separate email, crediting you of course.

**Comment by nhooyr** [comment]
the patch with a few modifications was merged into neovim https://github.com/neovim/neovim/pull/4409

**Comment by nhooyr** [comment]
@brammool https://github.com/neovim/neovim/pull/4409/files

In neovim, instead of creating a new variable `disable_fold_update`, `compl_busy` was used.

**Comment by brammool** [comment]
Anmol Sethi wrote:

> @brammool https://github.com/neovim/neovim/pull/4409/files
> 
> In neovim, instead of creating a new variable `disable_fold_update`,
> `compl_busy` was used.

And then made compl_busy global.  Same effect...

## 

This is an airconditioned room, do not open Windows.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///
