### ISSUE TITLE
vim9script: it is possible to change the type of a variable through map()

### ISSUE THREAD

**Issue by bfrg** [vim/vim#6437]
**Describe the bug**
Vim allows changing the type of a list through `map()`. When the type of a variable is set to `list<number>` it is possible to replace the items with another type, like `dict<number>`, using `map()`.

**To Reproduce**
1. Run `vim --clean -S test.vim`, with
```vim
" test.vim
vim9script
def Test(): list<number>
    let x: list<number> = range(10)
    map(x, {_, v -> v % 2 == 0 ? {'value': v} : 0 })
    return x
enddef
echo Test()
```
2. Output:
```
[{'value': 0}, 0, {'value': 2}, 0, {'value': 4}, 0, {'value': 6}, 0, {'value': 8}, 0]
```

**Expected behavior**
Since the type of variable `x` is explicitly set to `list<number>` I would have assumed that the types of the list items couldn't be changed anymore. Vim should print an error when the type of a variable is changed, here from `list<number>` to `list<any>` -- possibly when the function is compiled.

**Environment**
Vim version `8.2.1182`

**Comment by bfrg** [comment]
This is probably related to the following `todo` item:
https://github.com/vim/vim/blob/ecdd14a427108aa6f133c00655788f6ae80ad463/runtime/doc/todo.txt#L42-L43

**Comment by brammool** [comment]
map() changes a List or Dict in place, thus changing the value type should give an error.
But this makes it impossible to transform it to another type.
Perhaps we should add mapnew() which creates a new List or Dict for the result?

**Comment by bfrg** [comment]
Couldn't the check be made based on the type of the variable that is passed to `map()`? For example, when I pass a variable of type `list<number>` and try to transform it to another type with `map()` Vim gives an error. But when I pass a variable of type `list<any>` no error is thrown. Similar for dictionaries.

**Comment by brammool** [comment]
Yes, if the type is "any" then the changed type of value will be accepted.  That's not nice though, if you do want to end up with a list or dict with a certain type of value.  That's why we would need a new function that doesn't change the value in place.

**Comment by Shane-XB-Qian** [comment]
> map() changes a List or Dict in place

in legacy vim script, if no ':call' (omitted), that 'map()' looks returned the 'index' (-vs- 'val');
oppositely, in vim9 script, such ':call' was encouraged to be omitted, oh..My... looks that would be confused .. :rofl: 

btw: vim9 script, looks it is going to be more and more looked like 'javascript' ? haha ...

**Comment by bfrg** [comment]
`mapnew()` was added in ea696852e7, therefore closing.
