### ISSUE TITLE
vim9script: Segmentation fault when a :def function calls itself in a recursion

### ISSUE THREAD

**Issue by bfrg** [vim/vim#6441]
**Describe the bug**
Vim crashes when a `:def` function calls itself recursively.

**To Reproduce**
1. Run `vim --clean -S test.vim`, with
```vim
" test.vim
vim9script
def Fibonacci(n: number): number
    if !n
        return 0
    elseif n == 1
        return 1
    endif
    return Fibonacci(n - 1) + Fibonacci(n - 2)
enddef
defcompile
```
2. Result:
```
Vim: Caught deadly signal SEGV
Vim: Finished.
Segmentation fault
```
3. The above function works fine in legacy Vim script:
```vim
function Fibonacci(n)
    if !a:n
        return 0
    elseif a:n == 1
        return 1
    endif
    return Fibonacci(a:n - 1) + Fibonacci(a:n - 2)
endfunction
echo Fibonacci(8)
```

**Expected behavior**
No Segmentation faults.

**Environment**
Vim version `8.2.1182`

**Comment by lacygoill** [comment]
- [backtrace](https://github.com/vim/vim/files/4907709/backtrace.txt.gz)
 - [valgrind log](https://github.com/vim/vim/files/4907710/valgrind.log)
 - [asan log](https://github.com/vim/vim/files/4907708/asan.log)

**Comment by bfrg** [comment]
Thanks for the fix. But Unfortunately it still crashes when the function calls itself inside a `map()` [example from `:h readdir()`]:

```vim
vim9script
def Tree(dir: string): list<any>
    return readdir(dir)->map({_, val -> fnamemodify(dir .. '/' .. val, ':p')->isdirectory()
            \   ? {val : Tree(dir .. '/' .. val)}
            \   : val
            \ })
enddef

let dir: string = tempname()->fnamemodify(':h')
mkdir(dir .. '/test_dir', 'p')
writefile([], dir .. '/file_1')
writefile([], dir .. '/file_2')
writefile([], dir .. '/test_dir/file_3')
Tree(dir)
```

The following modification works though:
```vim
def Tree(dir: string): list<any>
    let tree: list<any> = readdir(dir)
    for i in len(tree)->range()
        if fnamemodify(dir .. '/' .. tree[i], ':p')->isdirectory()
            tree[i] = {tree[i]: Tree(dir .. '/' .. tree[i])}
        endif
    endfor
    return tree
enddef
```

**Comment by lacygoill** [comment]
- [backtrace](https://github.com/vim/vim/files/4914066/backtrace.txt)
 - [valgrind log](https://github.com/vim/vim/files/4914067/valgrind.log)
 - [asan log](https://github.com/vim/vim/files/4914065/asan.log)

**Comment by brammool** [comment]
That is a completely different problem, using a closure from a builtin function.  I think I'll make a hackish solution for that, please watch out for any other failures.
