### ISSUE TITLE
With autocmd CursorHoldI, CTRL-k in insert mode inserts <CursorHold> and not a digraph.

### ISSUE THREAD

**Issue by rpuntaie** [vim/vim#6447]
**Bug description**
In vim 8.2, in insert mode, with `autocmd CursorHoldI`,
<C-k> inserts `<CursorHold>` instead of a digraph.
I came across this,
because [coc.vim](https://github.com/neoclide/coc.nvim/blob/master/plugin/coc.vim) has such an autocmd.
Neovim does not have the problem.

**To Reproduce**
- check `<C-k>` *without* the autocmd: it works as expected

```
autocmd CursorHoldI
```

If it shows any, remove them, e.g.

```
augroup coc_nvim
    autocmd! CursorHoldI
augroup end
```

- check `<C-k>` *with* the autocmd: it inserts `<CursorHold>`.

Add an autocmd. For example:

```
augroup coc_nvim
    autocmd CursorHoldI * call getpos('.')
augroup end
```

Enter insert mode and do a `<C-k>`. 
It insert `<CursorHold>`.

**Expected behavior**
It should allow to enter digraph also if there is a `autocmd CursorHoldI`.

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun 21 2020 16:11:23)
Included patches: 1-814
Compiled by Arch Linux
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               +clientserver      +diff              +folding           +langmap           +mouse_dec         +num64             +reltime           +tag_binary        +toolbar           +writebackup
+arabic            +clipboard         +digraphs          -footer            +libcall           +mouse_gpm         +packages          +rightleft         -tag_old_static    +user_commands     +X11
+autocmd           +cmdline_compl     +dnd               +fork()            +linebreak         -mouse_jsbterm     +path_extra        +ruby/dyn          -tag_any_white     +vartabs           -xfontset
+autochdir         +cmdline_hist      -ebcdic            +gettext           +lispindent        +mouse_netterm     +perl/dyn          +scrollbind        +tcl/dyn           +vertsplit         +xim
-autoservername    +cmdline_info      +emacs_tags        -hangul_input      +listcmds          +mouse_sgr         +persistent_undo   +signs             +termguicolors     +virtualedit       -xpm
+balloon_eval      +comments          +eval              +iconv             +localmap          -mouse_sysmouse    +popupwin          +smartindent       +terminal          +visual            +xsmp_interact
+balloon_eval_term +conceal           +ex_extra          +insert_expand     +lua/dyn           +mouse_urxvt       +postscript        +sound             +terminfo          +visualextra       +xterm_clipboard
+browse            +cryptv            +extra_search      +ipv6              +menu              +mouse_xterm       +printer           +spell             +termresponse      +viminfo           -xterm_save
++builtin_terms    +cscope            -farsi             +job               +mksession         +multi_byte        +profile           +startuptime       +textobjects       +vreplace          
+byte_offset       +cursorbind        +file_in_path      +jumplist          +modify_fname      +multi_lang        +python/dyn        +statusline        +textprop          +wildignore        
+channel           +cursorshape       +find_in_path      +keymap            +mouse             -mzscheme          +python3/dyn       -sun_workshop      +timers            +wildmenu          
+cindent           +dialog_con_gui    +float             +lambda            +mouseshape        +netbeans_intg     +quickfix          +syntax            +title             +windows           
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/at-spi-2.0 -pthread    -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -D_REENTRANT  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.32/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lz -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0  -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lelf    -lcanberra  -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.32/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/5.32/core_perl/CORE -lperl -lpthread -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm     
```

**Comment by brammool** [comment]
I cannot reproduce this problem.

**Comment by rpuntaie** [comment]
Now I tried with `vim -u NONE` and then I cannot reproduce it either.

As a first step I removed coc.vim completely: Problem is still there.

So it is probably one of [my other plugins](https://github.com/rpuntaie/dotfiles/blob/desktop/etc/vim/vimrc).
I will try to find out and report.
It could also be related to one of my settings.

**Comment by rpuntaie** [comment]
The bug description applies only,
with the following status line entry of mine.

```
function! ShowUtf8Sequence()
  let p = getpos('.')
  redir => utfseq
  silent normal! g8
  redir End
  call setpos('.',p)
  return '['.trim(utfseq).']'
endfunction
set statusline+=%1*%{ShowUtf8Sequence()} " utf-8
```

If I comment `set statusline...` the bug description does not apply any more.

Note, that the bug description says that there needs to be the autocmd.
So if either the `autocmd CursorHoldI` or the mentioned status line entry is not there,
the bug will not occur.

With a default `updatetime` of 4000,
you will have to wait 4 seconds until `<CursorHold>` is inserted.

`coc.nvim` proposed `set updatetime=300` and it has the mentioned `autocmd`.
That is why I noticed.

Neovim does not have this bug.
That could help to identify the according code.

**Comment by brammool** [comment]
You are using a ":normal" command inside the status line update.  That's causing the trouble.
You already restore the cursor position, otherwise it will be moved.  That is just one of the side effects.
I can fix the problem mentioned here, but you can expect other things to fail.  Best is to avoid
using ":normal" while updating the status line.

**Comment by Shane-XB-Qian** [comment]
looks this is another terrible regression change .. :(
`au cursorhold` after this, looks almost not working anymore -only very less case would make it re-trigger again .. :(

btw: can we not keep fixing something, but broken sth also ... -_-#
specially, lots of legacy vim plugins perhaps not work too, such changes is harmful and not compatible to previous ones ...

------------
// or i may mis-understood / test sth .. so far, just `au cursorhold * echo xyz` would see ...
// sorry, if i mis-understood some, or wish this change can be revert ... :)

**Comment by brammool** [comment]
If you see a problem, please give a reproducible example, we can't guess what your problem is.

**Comment by vim-ml** [comment]
Hi,

On Mon, Jul 20, 2020 at 12:37 PM Shane-XB-Qian <vim-dev-github@256bit.org>
wrote:

> looks this is another terrible regression change .. :(
> au cursorhold after this, looks almost not working anymore -only very
> less case would make it re-trigger again .. :(
>
> btw: can we not keep fixing something, but broken sth also ... -_-#
> specially, lots of legacy vim plugins perhaps not work too, such changes
> is harmful and not compatible to previous ones ...
>

Can you create a test for the behavior that was working before this change?
Only by adding additional tests we can avoid regression breakages.

Regards,
Yegappan


> ------------------------------
>
> // or i may mis-understood / test sth .. so far, just au cursorhold *
> echo xyz would see ...
> // sorry, if i mis-understood some, or wish this change can be revert ...
> :)
>
>
>

**Comment by Shane-XB-Qian** [comment]
1. `x.vim`:
```vim
set ut=1000
au cursorhold * echo 'cur sr_kw: '.expand('<cword>')
```
2. `vim --clean -Nu x.vim`
3. you would see almost No `echo` there when cursor moved by e.g `w` & hold a 1s ...

**Comment by vim-ml** [comment]
Hi,

On Mon, Jul 20, 2020 at 1:02 PM Shane-XB-Qian <vim-dev-github@256bit.org>
wrote:

>
>    1. x.vim:
>
> set ut=1000au cursorhold * echo 'cur sr_kw: '.expand('<cword>')
>
>
>    1. vim --clean -Nu x.vim
>    2. you would see almost no echo there ...
>
>
>
I can reproduce the problem. It looks like the CursorHold autocmd is
triggered only once.
This will break the functionality of many of the plugins (e.g. taglist
relies on the autocmd to
update the current tag).

- Yegappan

**Comment by Shane-XB-Qian** [comment]
according to vim src code, you can try to do a 'fake' action e.g `c-x_c-o`, would make it re-trigger a `cursorhold`,
but almost No `echo` anymore - other than such 'fake' case .. :(

**Comment by vim-ml** [comment]
> >    1. x.vim:
> >
> > set ut=1000au cursorhold * echo 'cur sr_kw: '.expand('<cword>')
> >
> >
> >    1. vim --clean -Nu x.vim
> >    2. you would see almost no echo there ...
> >
> >
> >
> I can reproduce the problem. It looks like the CursorHold autocmd is
> triggered only once.
> This will break the functionality of many of the plugins (e.g. taglist
> relies on the autocmd to
> update the current tag).

It appears this regression when unnoticed because the test for
CursorHold is disabled, it's not working.  So I'll send a fix for now
without a test, but it would be good to have a test for this.

-- 
hundred-and-one symptoms of being an internet addict:
50. The last girl you picked up was only a jpeg.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Shane-XB-Qian** [comment]
@brammool @vim-ml  thanks your fix/refine. looks now it is working.
// looks a classic async code case, reduced competition, i learned a lot also, thx.
