### ISSUE TITLE
vim9script: Segmentation fault, and E1075/E116 errors for too short lambda argument passed to filter()

### ISSUE THREAD

**Issue by bfrg** [vim/vim#6449]
**Describe the bug**
Vim crashes when a list of numbers is passed to a `:def` function that filters the items. The same function works fine for a list of strings.

**To Reproduce**
1. Run `vim --clean -S test.vim`, with
```vim
vim9script
def Uniqify(items: list<number>): list<number>
    let visited: dict<number> = {}
    return filter(items, {_, val -> has_key(visited, val) ? 0 : len([extend(visited, {val: 1})])})
enddef
call Uniqify([2, 3, 2, 1, 3, 4, 5, 5, 4, 3])
```
2. Result:
```
Vim: Caught deadly signal SEGV
Vim: Finished.
Segmentation fault
```
3. Passing a list of strings to the same function works:
```vim
vim9script
def Uniqify(items: list<string>): list<string>
    let visited: dict<number> = {}
    return filter(items, {_, val -> has_key(visited, val) ? 0 : len([extend(visited, {val: 1})])})
enddef
call Uniqify(['three', 'one', 'one', 'three', 'one', 'two', 'two', 'one', 'three'])
```
4. The above function works in legacy functions:
```vim
function Uniqify(items)
    let visited = {}
    return filter(a:items, {_, val -> has_key(visited, val) ? 0 : len([extend(visited, {val: 1})])})
endfunction
call Uniqify([2, 3, 2, 1, 3, 4, 5, 5, 4, 3])
```

---
An error is printed when the second argument of the lambda passed to `filter()` is replaced by `i`:
```vim
vim9script
def Uniqify(items: list<string>): list<string>
    let visited: dict<number> = {}
    return filter(items, {_, i -> has_key(visited, i) ? 0 : len([extend(visited, {i: 1})])})
enddef
call Uniqify(['three', 'one', 'one', 'three', 'one', 'two', 'two', 'one', 'three'])
```

Result:
```
Error detected while processing function Uniqify[2]..<lambda>1:
line    1:
E1075: Namespace not supported: i: 1})])
E1075: Namespace not supported: i: 1})])
```

Using `v` for the second lambda argument results in a different error:
```
Error detected while processing function <SNR>14_Uniqify:
line    2:
E116: Invalid arguments for function extend(visited, {v: 1})])})
E116: Invalid arguments for function len([extend(visited, {v: 1})])})
```
Neither error occurs in legacy functions.

**Expected behavior**
No segmentation faults, and no `E1075` or `E116` errors.

Currently, Vim doesn't check the types of the variables passed to a `:def` function yet. But I think this is already mentioned in the `todo` list:
https://github.com/vim/vim/blob/7177da9dd4d9a521c6141c6fbf7e9a4d6296ab05/runtime/doc/todo.txt#L51-L53

**Environment**
Vim version `8.2.1199`

**Comment by lacygoill** [comment]
- [backtrace](https://github.com/vim/vim/files/4913527/backtrace.txt)
 - [valgrind log](https://github.com/vim/vim/files/4913528/valgrind.log)
 - [asan log](https://github.com/vim/vim/files/4913526/asan.log)
