### ISSUE TITLE
ml_get invalid lnum error on half-page scrolling

### ISSUE THREAD

**Issue by itchyny** [vim/vim#6450]
**Describe the bug**
In diff mode, <kbd>&lt;C-d&gt;</kbd> key causes `E315: ml_get: invalid lnum` error.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean`.
2. `:set ls=2`
3. `:for i in range(winheight(0)*2) | call setline(i, i < winheight(0) - 10 ? i : i + 10) | endfor`
4. `:vnew`
5. `:for i in range(winheight(0)*2 + 10) | call setline(i, i < winheight(0) - 10 ? 0 : i) | endfor`
6. `:diffthis`
7. `:wincmd p`
8. `:diffthis`
9. `:execute 'normal ' . winheight(0) . "\<C-d>"`
10. `E315: ml_get: invalid lnum: 119` happens (lnum may change).

**Expected behavior**
Scrolls without E315 error.

**Screenshots**
![](https://user-images.githubusercontent.com/375258/87371047-7f192080-c5bf-11ea-9d86-e48b7e341172.gif)

**Environment (please complete the following information):**
 - Vim version 8.2.1206
 - OS: macOS 10.15.5
 - Terminal: iTerm2

**Additional context**
Nothing

**Comment by dpelle** [comment]
I can reproduce the E315 internal error with the latest vim-8.2.1206.
I did a `git bisect` and the bug is a regression introduced by vim-8.2.1118:
```
commit 810af5ea460eab820cc5899892067d8c242be688 (tag: v8.2.1118)
Author: Bram Moolenaar <Bram@vim.org>
Date:   Thu Jul 2 21:23:42 2020 +0200

    patch 8.2.1118: condition can never be true, dead code
    
    Problem:    Condition can never be true, dead code.
    Solution:   Remove the dead code.
```
That change removed 2 lines in vim/src/move.c, but it was not dead code after all. So I suppose that we should revert 8.2.1118.

**Comment by brammool** [comment]
The patch removed a bit too much, the decrement should remain.

**Comment by itchyny** [comment]
Confirmed that 8.2.1211 (8455c5ed31c9cb2919f5e62693bab6b09bf60df2) fixed this. Thank you.
