### ISSUE TITLE
Mapping CTRL-^ fails for GTK Gvim since 8.2.0851

### ISSUE THREAD

**Issue by drmikehenry** [vim/vim#6457]
**Describe the bug**
Mapping CTRL-^ in the GTK version of Gvim stopped working as of vim-8.2.0851:

    patch 8.2.0851: can't distinguish <M-a> from accented "a" in the GUI

    Problem:    Can't distinguish <M-a> from accented "a" in the GUI.
    Solution:   Use another way to make mapping <C-bslash> work. (closes #6163)

Mapping continues to work as expected in console Vim.

**To Reproduce**
Use the below two-line vimrc file with no other content in ~/.vim:

```vim
nmap <c-^>  :echo 'CTRL-^'<CR>
nmap <c-6>  :echo 'CTRL-6'<CR>
```

In console Vim and versions of Gvim prior to 8.2.0851, both CTRL-^ and CTRL-6 trigger the `<c-^>` mapping and display `CTRL-^`; in Gvim 8.2.0851 and later, pressing CTRL-^ bypasses all mappings and performs the built-in behavior documented in `:help CTRL-^`, and pressing `<c-6>` invokes the mapping to display `CTRL-6`.

The above behavior persists in the latest tested Gvim (8.2.1217).  In this latest version, `<c-6>` can be mapped to `<c-^>` to work around the problem:
```vim
nmap <c-6>  <c-^>
```

However, this work-around fails with Gvim 8.2.0851; on this version, pressing CTRL-6 correctly invokes the mapping for `<c-^>`, but the mapping for `<c-^>` is ignored and the built-in CTRL-^ behavior is invoked instead.  No testing was done to determine what patch introduced this change in behavior.

Also, in all tested versions since Gvim 8.2.0851, the keystroke CTRL-^ cannot be intercepted by a mapping.

**Expected behavior**
Pressing either CTRL-^ or CTRL-6 should result in the invocation of the mapping for `<c-^>`.

**Environment (please complete the following information):**
 - Vim version 8.2.0851 through 8.2.1217
 - OS: Ubuntu 18.04
 - Terminal: GUI
 - Keyboard: US English

 - Build configuration:

   ```sh
     ./configure \
       --quiet \
       --with-features=huge \
       --enable-gui=gtk3 \
       --enable-perlinterp \
       --enable-pythoninterp \
       --enable-python3interp \
       --enable-tclinterp \
       --enable-rubyinterp \
       --enable-cscope \
       --with-compiledby=vim@drmikehenry.com \
       --with-ruby-command=/usr/bin/ruby
   ```

**Comment by brammool** [comment]
To see what happens:
imap <C-^> ctrl-hat
imap <C-6> ctrl-six
imap <C-S-^> ctrl-shift-hat

For my setup the <C-^> doesn't work, the others do.  Both in an xterm and in GTK GUI.
Where the hat is located depends on the keyboard, thus always using CTRL-6 as CTRL-^ won't work for everyone.
So I'm not sure if there is something to fix.

**Comment by lacygoill** [comment]
FWIW, both mappings work as expected on my machine (Vim 8.2.1218, Ubuntu 16.04, XTerm(356)).

    vim -g -Nu NONE +"nno <c-^> :echo 'CTRL-^'<CR>" +"nno <c-s-6> :echo 'CTRL-6'<CR>"

The only thing which I had to change was the lhs of the `<c-6>` mapping.  With my keyboard layout, to produce the keysym `6`, I need to press <kbd>Shift</kbd> and <kbd>-</kbd> at the same time.  Therefore, I need to include the shift modifier explicitly:

    nnoremap <c-s-6> :echo 'CTRL-6'<CR>
               ^^

**Comment by drmikehenry** [comment]
I see a few issues with the current behavior:

- Vim has historically documented the keystroke `CTRL-^` as the means to switch to the alternate buffer (as in `:help CTRL-^`); therefore, a mapping against `<c-^>` ought to intercept this standard behavior, and plugins such as BufMRU (https://github.com/mildred/vim-bufmru/) expect to be able to do so.  Currently I don't see any way to trigger such a mapping in GTK Gvim, and this is a regression against previous behavior (and console Vim behavior).

- When the control key is pressed for ASCII (https://www.asciitable.com/) characters in the range 0x40 (`@`) to 0x5f (`_`), historically the effect has been to subtract 0x40 to produce the corresponding control code.  This works for all 32 such control codes (0x00 through 0x1f).  Thus the standard ASCII code for `CTRL-^` would be 0x1e (0x5e - 0x40).  On a US keyboard, this would be accomplished by pressing `CTRL`, `SHIFT`, and `6` (because `^` is generated by `SHIFT-6`).  Because the key `6` is code 0x30, subtracting 0x40 isn't useful, so US terminals have historically inferred the `SHIFT` key when `CTRL-6` is pressed, converting `CTRL-6` into `CTRL-^`.

- A key definition such as `<c-^>` logically means to hold the control key and press whatever is needed on your keyboard to generate `^`.  On a US keyboard, this means pressing `CTRL-SHIFT-6`.  For mappings, this means the key sequences `<c-s-6>` and `<c-^>` are inherently ambiguous on US keyboards.  Given that `CTRL-^` has a well-defined ASCII code and `CTRL-SHIFT-6` does not, it seems reasonable to choose `CTRL-^` as the meaning (especially since this is the historical Gvim behavior and the current behavior for both terminals and console Vim).  This makes sense to apply to all ASCII codes in the range 0x40 - 0x5f for backward compatibility.

- It is desirable to reduce inconsistencies between console Vim and Gvim in order to minimize variations in vimrc.  This was historically possible when sticking to the standard set of ASCII keys supported everywhere.

- Aside from the uppercase letters `A` - `Z`, there are six additional ASCII codes that are in the range 0x40 - 0x5f:

  - 0x40: `@` (`SHIFT-2`)
  - 0x5b: `[`
  - 0x5c: `\`
  - 0x5d: `]`
  - 0x5e: `^` (`SHIFT-6`)
  - 0x5f: `_` (`SHIFT--`)

  In a terminal, each of the keys `@`, `[`, `\`, `]`, and `^` give their control-code equivalent when pressing `CTRL`, both with and without `SHIFT`, as their shifted (or unshifted) counterparts `2`, `{`, `|`, `}`, and `6` are not in the range 0x40 - 0x5f.  It's unclear why `_` requires both `SHIFT` and `CTRL` to produce `CTRL-_`, but in any case the counterpart key `-` has no ASCII control code equivalent, and pressing `CTRL--` just yields the unmodified `-` key.

  For compatibility with console Vim, terminals, and historical Gvim behavior, pressing `CTRL` with any of these six keys should be usable in mappings directly using the syntax `<c-X>` for each key `X`.

- When there is no pre-existing meaning in the console for a given key (e.g., pressing `CTRL-SHIFT-5`), there's an ambiguity how it ought to be interpreted (e.g., should it be considered `CTRL-%` or `CTRL-SHIFT-5`?).  For consistency with other shifted keys, it seems most reasonable to use the shifted key as a base (`CTRL-%`), but it could be defensible to choose the unshifted key (`CTRL-SHIFT-5`); it seems logically inconsistent, however, to treat it as `CTRL-SHIFT-%`, since the shift is already counted when converting `SHIFT-5` into `%`.

Consider these mappings to determine Vim's behavior:
```vim
inoremap 2 2<CR>
inoremap <s-2> shift-2<CR>
inoremap <c-2> ctrl-2<CR>
inoremap <c-s-2> ctrl-shift-2<CR>
inoremap @ @<CR>
inoremap <s-@> shift-@<CR>
inoremap <c-@> ctrl-@<CR>
inoremap <c-s-@> ctrl-shift-@<CR>

inoremap [  [<CR>
inoremap <s-[>  shift-[<CR>
inoremap <c-[>  ctrl-[<CR>
inoremap <c-s-[>  ctrl-shift-[<CR>
inoremap {  {<CR>
inoremap <s-{>  shift-{<CR>
inoremap <c-{>  ctrl-{<CR>
inoremap <c-s-{>  ctrl-shift-{<CR>

inoremap \  \<CR>
inoremap <s-\>  shift-\<CR>
inoremap <c-\>  ctrl-\<CR>
inoremap <c-s-\>  ctrl-shift-\<CR>
inoremap <bar>  <bar><CR>
inoremap <s-<bar>>  shift-<bar><CR>
inoremap <c-<bar>>  ctrl-<bar><CR>
inoremap <c-s-<bar>>  ctrl-shift-<bar><CR>

inoremap ]  ]<CR>
inoremap <s-]>  shift-]<CR>
inoremap <c-]>  ctrl-]<CR>
inoremap <c-s-]>  ctrl-shift-]<CR>
inoremap }  }<CR>
inoremap <s-}>  shift-}<CR>
inoremap <c-}>  ctrl-}<CR>
inoremap <c-s-}>  ctrl-shift-}<CR>

inoremap 6 6<CR>
inoremap <s-6> shift-6<CR>
inoremap <c-6> ctrl-6<CR>
inoremap <c-s-6> ctrl-shift-6<CR>
inoremap ^ ^<CR>
inoremap <s-^> shift-^<CR>
inoremap <c-^> ctrl-^<CR>
inoremap <c-s-^> ctrl-shift-^<CR>

inoremap -  -<CR>
inoremap <s-->  shift--<CR>
inoremap <c-->  ctrl--<CR>
inoremap <c-s-->  ctrl-shift--<CR>
inoremap _  _<CR>
inoremap <s-_>  shift-_<CR>
inoremap <c-_>  ctrl-_<CR>
inoremap <c-s-_>  ctrl-shift-_<CR>
```

Using the above mappings, the below table shows how the behavior of Gvim has changed.

Keypress        | Console Vim, old Gvim | New Gvim (if different)
--------------- | --------------------- | --------------------------
`2`             | `2`                   |
`SHIFT-2`       | `@`                   |
`CTRL-2`        | `ctrl-@`              | `ctrl-2`
`CTRL-SHIFT-2`  | `ctrl-@`              | `ctrl-shift-@`
`[`             | `[`                   |
`SHIFT-[`       | `{`                   |
`CTRL-[`        | `ctrl-[`              |
`CTRL-SHIFT-[`  | `ctrl-[`              | `ctrl-shift-{`
`\`             | `\`                   |
`SHIFT-\`       | `\|`                  |
`CTRL-\`        | `ctrl-\`              |
`CTRL-SHIFT-\`  | `ctrl-\`              | (no mapping; see below)
`]`             | `]`                   |
`SHIFT-]`       | `}`                   |
`CTRL-]`        | `ctrl-]`              |
`CTRL-SHIFT-]`  | `ctrl-]`              | `ctrl-shift-}`
`6`             | `6`                   |
`SHIFT-6`       | `^`                   |
`CTRL-6`        | `ctrl-^`              | `ctrl-6`
`CTRL-SHIFT-6`  | `ctrl-^`              | `ctrl-shift-^`
`-`             | `-`                   |
`SHIFT--`       | `_`                   |
`CTRL--`        | `-`                   | `ctrl--`
`CTRL-SHIFT--`  | `ctrl-_`              | `ctrl-shift-_`

For new Gvim, `CTRL-SHIFT-\` does not seem to trigger any of the mappings.  On the first keypress, Gvim pauses for another keystroke; afterward, each subsequent `CTRL-SHIFT-\` inserts a literal control-backslash (0x1c) into the buffer.  It seems that this is triggering Vim's behavior documented at `:help i_CTRL-\_CTRL-G` and `:help i_CTRL-\_CTRL-N`, rather than invoking the expected mapping.

As the table above indicates, there are four codes that used to be usable as the left-hand side of a mapping but which can no longer be typed in new Gvim:
- `<c-@>`
- `<c-^>`
- `<c-_>`
- `<c-\>`

In addition, two new codes are now available, but they have a spurious `shift`:
- `<c-s-{>`
- `<c-s-}>`

All of the `ctrl-shift-x` codes generated by new Gvim in the table above have the logical inconsistency of a spurious extra `shift`.

Overall, this recent change to Gvim loses some long-standing functionality and makes it harder to maintain portable configuration files that work across variations of Vim and across platforms.

**Comment by lacygoill** [comment]
@drmikehenry Can you check whether [8.2.1752](https://github.com/vim/vim/releases/tag/v8.2.1752) helped in any way?

**Comment by drmikehenry** [comment]
Unfortunately, 8.2.1752 doesn't help with this particular problem; however, the patch did help me to get a better understanding of what's going on.

Historically, when pressing the control key and an alphabetic key, the case of the letter didn't matter; the same ASCII code was generated either way.  Vim chose therefore to convert the letter to uppercase in its canonical representation in mappings.  Both `control-x` and `control-X` would be converted to the same ASCII code, and both would match a mapping for `<C-X>` (with the letter forced to uppercase).  Vim is now trying to distinguish uppercase and lowercase when combined with control.  Had this been the goal all along, Vim might have used the lowercase letter as the canonical representation without shift (viz. `<C-x>` instead of `<C-X>`), leaving the uppercase variant available for use when the shift key is pressed.  Given the history, Vim is now adding the `S-` modifier in cases where control and a letter are involved.  This allows for differentiation in a compatible way.

For letters, the canonical representation varies based on whether the control key is pressed.  Without the control key, the presence of the shift key is indicated by using the uppercase letter, and the absence is indicated by using the lowercase letter.  For example:
```vim
inoremap x  lowercase x<CR>
inoremap X  uppercase x<CR>
```

But when the control key is involved, the letter will always be in uppercase in the canonical representation, and the shift modifier (`S-`) will be included for only those cases when the shift key is pressed.  For example:
```vim
inoremap <C-X>  control-lowercase x<CR>
inoremap <C-S-X>  control-uppercase x<CR>
```

The logic above is specialized for letters due to Vim's historical behavior of forcing control-letter to uppercase; it is inapplicable to non-letters.  The function `may_remove_shift_modifier` correctly removes the shift modifier when the control modifier is not present.  In an attempt to retain the shift modifier for the control-letter case above, the function does nothing when the control key is pressed; but this logic should be more selective.  The shift modifier should be removed for all of the non-letter cases handled by the function, independent of the state of the control modifier; only the control-letter case should should be treated specially when control is pressed.

The function as written is careful to consider the entire set of modifiers as a whole (as opposed to considering shift and control individually) for reasons I don't understand.  Here is the current logic:

```c
    int
may_remove_shift_modifier(int modifiers, int key)
{
    if ((modifiers == MOD_MASK_SHIFT
                || modifiers == (MOD_MASK_SHIFT | MOD_MASK_ALT)
                || modifiers == (MOD_MASK_SHIFT | MOD_MASK_META))
            && ((key >= '!' && key <= '/')
                || (key >= ':' && key <= 'Z')
                || (key >= '[' && key <= '`')
                || (key >= '{' && key <= '~')))
        return modifiers & ~MOD_MASK_SHIFT;
    return modifiers;
}
```

If any other modifiers are present, such as OS X's `MOD_MASK_CMD`, the shift key will not be removed.  I'm not sure if that's intentional or not.  I'd have imagined that the same logic which applies for control-shift would apply to command-shift or control-command-shift, etc.  But if it's important to ensure no other modifiers are present, then the following change could be used to eliminate the logically inconsistent `S-` modifier:

```c
    int
may_remove_shift_modifier(int modifiers, int key)
{
    if ((modifiers == MOD_MASK_SHIFT
		|| modifiers == (MOD_MASK_SHIFT | MOD_MASK_ALT)
		|| modifiers == (MOD_MASK_SHIFT | MOD_MASK_META))
	    && ((key >= '!' && key <= '/')
		|| (key >= ':' && key <= 'Z')
		|| (key >= '[' && key <= '`')
		|| (key >= '{' && key <= '~')))
	return modifiers & ~MOD_MASK_SHIFT;
    if ((modifiers == (MOD_MASK_CTRL | MOD_MASK_SHIFT)
		|| modifiers == (MOD_MASK_CTRL | MOD_MASK_SHIFT | MOD_MASK_ALT)
		|| modifiers == (MOD_MASK_CTRL | MOD_MASK_SHIFT | MOD_MASK_META))
	    && ((key >= '!' && key <= '/')
		|| (key >= ':' && key <= '@')
		|| (key >= '[' && key <= '`')
		|| (key >= '{' && key <= '~')))
	return modifiers & ~MOD_MASK_SHIFT;
    return modifiers;
}
```

Alternatively, it makes sense to me to consider the modifier keys individually, in which case the shift modifier should be removed for all of the non-letters originally specified in the function, and for letters as well if and only if the control modifier is missing.  If that's the case, this logic would apply:

```c
    int
may_remove_shift_modifier(int modifiers, int key)
{
    if ((modifiers & MOD_MASK_SHIFT)
	    && ((key >= '!' && key <= '/')
		|| (key >= ':' && key <= '@')
		|| (key >= '[' && key <= '`')
		|| (key >= '{' && key <= '~')
		|| (key >= 'A' && key <= 'Z' && !(modifiers & MOD_MASK_CTRL))))
	return modifiers & ~MOD_MASK_SHIFT;
    return modifiers;
}
```

Either of these changes remove the spurious extra `S-` modifier which is half of the issue with this current ticket.  Fixing the spurious shift modifier would allow plugins to map `<C-^>` such that pressing `control-^` will invoke the mapping.

The other half of the issue in this ticket is caused by 8.2.0851 which removed the following logic from `gui_gtk_x11.c` in function `keyval_to_string`:
```c
     if (uc != 0)
     {
 	// Check for CTRL-char
 	if ((*state & GDK_CONTROL_MASK) && uc >= 0x20 && uc < 0x80)
 	{
 	    // These mappings look arbitrary at the first glance, but in fact
 	    // resemble quite exactly the behaviour of the GTK+ 1.2 GUI on my
 	    // machine.  The only difference is BS vs. DEL for CTRL-8 (makes
 	    // more sense and is consistent with usual terminal behaviour).
 	    if (uc >= '@')
 		string[0] = uc & 0x1F;
 	    else if (uc == '2')
 		string[0] = NUL;
 	    else if (uc >= '3' && uc <= '7')
 		string[0] = uc ^ 0x28;
 	    else if (uc == '8')
 		string[0] = BS;
 	    else if (uc == '?')
 		string[0] = DEL;
 	    else
 		string[0] = uc;
 	    len = 1;

 	    if (string[0] != uc)
 		// The modifier was used, remove it.
 		*state = *state & ~GDK_CONTROL_MASK;
 	}
```

In particular, the patch removed the code below, which had transformed `control-3` through `control-7` into usable ASCII codes (since there is no meaning in ASCII for these keys otherwise):
```c
 	    else if (uc >= '3' && uc <= '7')
 		string[0] = uc ^ 0x28;
```

The code previously had this effect:

| Key        | new code | new meaning | equivalent key |
| :------:   | :------: | :---------: | :------------: |
| control-3  | 0x1b     | ESC         | control-[      |
| control-4  | 0x1c     | FS          | control-\      |
| control-5  | 0x1d     | GS          | control-]      |
| control-6  | 0x1e     | RS          | control-^      |
| control-7  | 0x1f     | US          | control-\_     |

This transformation code was removed in 8.2.0851, which is the reason that for gtk2 and gtk3, `control-6` no longer works as an alias for `control-^` as documented in `:help CTRL-6` (for US keyboards).  Notably, it still works for all of the other cases I tested (console Vim on Linux, X11/athena, and Windows).

Among these transformations, only `control-6` is part of Vim's documented historical (and current) interface as far as I can tell.

With the patch to `may_remove_shift_modifier`, this behavior can be restored via the mapping:
```vim
    imap <C-6> <C-^>
```

But it seems to me that it shouldn't be necessary for the user to insert such a work-around.  Given that the other flavors of interface still generate `control-^` when `control-6` is pressed, it makes sense to me for the gtk-specific code to restore at least this transformation.

Thanks,
Michael Henry

**Comment by tonymec** [comment]
For better or worse, Vim historically represented the "Ctrl+printable character" combinations based on the ASCII conventions. This meant that:
* Ctrl+0xHH (where 0x40 <= 0xHH <= 0x5F) is 0xHH - 0x40
* Ctrl+lowercase is the same as Ctrl+uppercase
* Ctrl+ "other printable characters" has no representation.
For non-printable keys (arrows, F keys, etc.) the system is different.

But there is one more complication: when using gvim, most key combinations can be seen. When running Vim in a terminal, some of them are preempted by the terminal and never reach gvim.

IMHO, the safest keys for the {lhs} of a mapping, at least in gvim, are F2 to F9, F11, F12, and Shift-F1 to Shift-F12. (Even some of these get "stolen" by some terminals when running Vim in a terminal.) (For consistency across applications, F1 without Shift should be reserved for Help or for a mapping meaning Help, and F10 without Shift similarly for Menu.)

Anything can be used for the {rhs}. For instance, on my keyboard layout the Ctrl-] combo, used in Normal mode for "go to tag" or "go to help hotlink" and in Insert and Command-line modes for "trigger abbreviation", is hard to get: for years I didn't know where it was: so I defined the following mapping in my vimrc:
```vim
    map  <F9> <C-]>
    map! <F9> <C-]>
```
Lately I've found out that the "native" keyboard key for Ctrl-] is AltGr-Ctrl-$ — but rather than using this "emacs-like" three-finger combo I keep using F9.

Best regards,
Tony.

**Comment by tonymec** [comment]
Oops! When running Vim in a terminal […] never reach **vim**

**Comment by brammool** [comment]
Parial response:

Traditionally the hex codes 0x40 - 0x5f plus the CTRL key mapped to 0x00
to 0x1f.  Thus CTRL-@ is 0x00, CTRL-6 is 0x1e.  Adding Shift usually
didn't have an effect, thus Ctrl-Shift-a was the same as Ctrl-a.  And
mapping <C-a> and <C-A> was the same thing.

Now that we can distinguish the Shift key, we need to use the <C-S-a>
code to recognize that.  And to be consistent, also accept <C-S-A>.  I
haven't checked if that actually works everywhere (terminal, terminal
with modifyOtherKeys, GTK, Motif, Mac and MS-Windows).

For non-alpha characters <C-6> and <C-^> usually give the same hex code.
We don't write <C-S-6> or <C-S-^> though, but <C-^>.  But either of them
can work.

Unfortunately it's hard to tell how this worked in the past.  I like to
keep it backwards compatible, but if we can't check that I'm not sure if
I can make changes that won't break existing mappings.  Introducing the
modifyOtherKeys was hard enough.

We should at leasty try to centralize this, avoiding that different
environments have different effects.


-- 
hundred-and-one symptoms of being an internet addict:
10. And even your night dreams are in HTML.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by drmikehenry** [comment]
Understood.  Key handling is indeed hard.  For me, the main goal is to avoid the inconsistent notation of mappings like `<C-S-^>`, where the shift key is already accounted for when the `6` was converted to `^`.  If long-term goals indicate a break with the historical behavior of treating `control-6` as `control-^`, it can be handled in a mapping (perhaps even a mapping shipped by default that a user could undo to treat the keys separately).
