### ISSUE TITLE
vim9script: E1013: argument 2: type mismatch, expected bool but got bool

### ISSUE THREAD

**Issue by bfrg** [vim/vim#6458]
**Describe the bug**
It is not possible to provide a default value for function arguments of type
`bool` when the argument is not the first one. Vim prints an error when the
default value is set to `true`, `false`, `v:true` or `v:false`, but works fine
when set to a number.

**To Reproduce**
1. Run `vim --clean -S test.vim`, with
```vim
" test.vim
vim9script
def Test(n: number, neg: bool = true): number
    return neg ? -n : n
enddef
defcompile
```
2. Result:
```
Error detected while processing function <80><fd>R114_Test:
line    1:
E1013: argument 2: type mismatch, expected bool but got bool
```

The same error occurs when `v:true` or `v:false` are used.  Using `0` or `1` as
default values works though:
```vim
def Test(n: number, neg: bool = 1): number
    return neg ? -n : n
enddef
```

**Expected behavior**
No error messages.

**Environment**
Vim version `8.2.1206`

**Comment by brammool** [comment]
Best error message ever: "expected bool but got bool".  Giving an error for doing things right...
