### ISSUE TITLE
noai in .vimrc is ignored

### ISSUE THREAD

**Issue by LiohMoeller** [vim/vim#6468]
Since the recent upgrade to vim-8.2.1167, the set noai option in .vimrc seems to be ignored. Other options from .vimrc are working fine. I can :set noai interactive which also works but I would prefer if it's read from my config file.

Last known version where set noai in vimrc was working as expected is 8.2.0007

**Comment by lacygoill** [comment]
What's the output of `:verbose set ai?`

**Comment by LiohMoeller** [comment]
It seems to be correct:

noautoindent
        Zuletzt gesetzt in ~/.vimrc Zeile 5

Even though copy and paste with middle click mouse generates intends from:

```
test
test
test

```
to:

```
test
        test
                test
```

Which works correctly after :set noai interactively. set paste is also set in .vimrc

Maybe it is not related to noai but has another root cause. It just worked fine in the previous version I have mentioned.

**Comment by lacygoill** [comment]
Try to [bisect your config](https://github.com/chrisbra/vim_faq/blob/de424bd8e08bcf0e6b1e0563ee49514dfed926ae/vim_faq.txt#L1153-L1228) to find a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example).

---

For information, here is the list of commits between 8.2.0007 and 8.2.1167 containing the keyword "indent":

   - [8.2.0112](https://github.com/vim/vim/releases/tag/v8.2.0112)  illegal memory access when using 'cindent'
   - [8.2.0146](https://github.com/vim/vim/releases/tag/v8.2.0146)  wrong indent when 'showbreak' and 'breakindent' are set
   - [8.2.0358](https://github.com/vim/vim/releases/tag/v8.2.0358)  insufficient testing for indent.c
   - [8.2.0705](https://github.com/vim/vim/releases/tag/v8.2.0705)  indent tests don't run on CI for FreeBSD
   - [8.2.0766](https://github.com/vim/vim/releases/tag/v8.2.0766)  display error when using 'number' and 'breakindent'
   - [8.2.0864](https://github.com/vim/vim/releases/tag/v8.2.0864)  pragmas are indented all the way to the left

**Comment by LiohMoeller** [comment]
Thanks for the hints. My config is quite minimal for testing purposes:

```
set mouse=
set noai
set paste
```
I noticed another difference. In the previous version then there is a line beginning with a tab and I hit enter, the cursor jumps to the beginning of the new line. With the new version, the cursor jumps to the newline but at the same tab position (i hope that's understandable). Maybe this could be related to the changed behavior?

**Comment by k-takata** [comment]
Please use the issue template when you report an issue.
Does it depend on filetype? What OS? What terminal? Does your terminal support bracketed paste (`:help xterm-bracketed-paste`)?

**Comment by LiohMoeller** [comment]
Yes, the Konsole terminal supports if for quite some time.

**Comment by chrisbra** [comment]
Please answer all questions.

> Yes, the Konsole terminal supports if for quite some time.

If it does support bracketed-paste mode, why do you enable `set paste`? For konsole 
you probably need to enable it manually. IIRC, bracketed paste only gets enabled for xterms. See `:h xterm-bracketed-paste`

Can you please also show a (or better two for each of the problems encountered) minimal example that shows the different behaviour? Best to start with `vim --clean -c ':set ai'`

And if you could bisect to the patch that introduced the regression, that would be helpful.

**Comment by LiohMoeller** [comment]
It does not depend on the filetype. OS is Linux, as mentioned Konsole is the terminal. And you where right about the xterm-bracketed-paste, which seems to be enabled automatically on Konsole as well. Removing set paste from the configuration file solved the issue. Thanks all for your help and sorry for the noise (still not sure which change has introduced the issue I faced, but it's fine for me).
