### ISSUE TITLE
Moving Cursor Fast

### ISSUE THREAD

**Issue by mdtausifiqbal** [vim/vim#6473]
Include a feature that is moving cursor fast by pressing long h,j,k,l.

if we press this button for long time, cursor should move fast in relevant direction.

**Comment by gukz** [comment]
I want this Too !!! It will be better if I can control the speed when press this button for long time.

**Comment by k-takata** [comment]
I've seen this kind of request several times (mainly from Vim beginners).
Yes, that might be sometimes useful, but I don't think it's a Vim way.
Vim provides a variety of motions. See `:help motion.txt`.
E.g. To move left and right, `w`, `b`, `f`, `t`, etc.
To move up and down, `Ctrl-U`, `Ctrl-D`, `Ctrl-F`, `Ctrl-B`, `H`, `L`, etc.
You can also precede a count before motions. E.g. `3j`.
There are also some plugins that enhance such motions.
Utilizing them might be better.

If you still want to use hjkl, your OS might have a setting to change the key repeat rate.
