### ISSUE TITLE
winnr('$') do not include popup windows, can not count popups.

### ISSUE THREAD

**Issue by wsdjeg** [vim/vim#6474]
**Describe the bug**

can not count windows include popup

**To Reproduce**
Detailed steps to reproduce the behavior:
1. open a popup
2. run `:echo winnr("$")`

**Expected behavior**
It should print `2`

**Environment (please complete the following information):**
 - Vim version: 8.1.2120
 - OS: win 7
 - Terminal: gvim

**Comment by lacygoill** [comment]
[8.2.0748](https://github.com/vim/vim/releases/tag/v8.2.0748) provides the [`popup_list()`](https://vimhelp.org/popup.txt.html#popup_list()) function which returns the id of all the popup windows.

To get the number of all popup windows currently open, try this:

    :echo popup_list()->len()

To get the number of all popup windows open in the current tab page, try this:

    :echo popup_list()
        \ ->map({_,v -> popup_getoptions(v).tabpage})
        \ ->filter({_,v -> v == -1 || v == 0})
        \ ->len()

To get the number of all popup windows open in the current tab page *and visible*, try this:

    :echo popup_list()
        \ ->filter({_,v -> popup_getpos(v).visible})
        \ ->map({_,v -> popup_getoptions(v).tabpage})
        \ ->filter({_,v -> v == -1 || v == 0})
        \ ->len()

**Comment by brammool** [comment]
Closing, since there is a solution.
