### ISSUE TITLE
Vim9: can't use "#" as a comment leader at the start of an automatic line continuation at the script level

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6482]
**Describe the bug**

In Vim9 script, we can't use `#` as a comment leader at the start of an automatic line continuation at the script level.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        let mylist = [
                'one',
                # some comment
                'two',
                ]
    EOF
    )

`E121`, `E15` and `E492` are raised:

    Error detected while processing ...
    line    4:
    E121: Undefined variable: #
    line    5:
    E15: Invalid expression: 'two',
    line    6:
    E492: Not an editor command:             ]

**Expected behavior**

No error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-1233
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(356)

**Additional context**

The issue disappears in a `:def` function:
```vim
vim9script
def Func()
    let mylist = [
            'one',
            # some comment
            'two',
            ]
enddef
defcompile
```

**Comment by brammool** [comment]
Implemented by patch 8.2.1243
