### ISSUE TITLE
Vim9: can't use line break after method call operator at script level

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6492]
**Describe the bug**

In Vim9 script, we can't use a line break after the method call operator at the script level.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        let result = 'abcdefghi'->
            split('\zs')->
            filter('v:val !~# "[aei]"')->
            join('')
        echo result
    EOF
    )

`E260` is raised:

    Error detected while processing ...
    line    2:
    E260: Missing name after ->
    line    3:
    E260: Missing name after ->
    line    4:
    E119: Not enough arguments for function: filter
    line    5:
    E714: List required
    line    6:
    E121: Undefined variable: result

**Expected behavior**

No error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-1253
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(356)

**Additional context**

According to `:h vim9-declaration`, it should be possible to put a line break after a binary operator such as `->`:

https://github.com/vim/vim/blob/b146e01a7e41bf5787a2b5ccc6c340ed6001f308/runtime/doc/vim9.txt#L268-L269

---

The issue is specific to the method call operator.  As an example, `..` works fine:
```vim
vim9script
let result = 'foo' ..
    'bar' ..
    'baz'
echo result
```
---

The code works fine when the line break is *before* `->` instead of after:
```vim
vim9script
let result = 'abcdefghi'
    ->split('\zs')
    ->filter('v:val !~# "[aei]"')
    ->join('')
echo result
```
---

The issue disappears in a `:def` function:
```vim
vim9script
def Func()
    let result = 'abcdefghi'->
        split('\zs')->
        filter('v:val !~# "[aei]"')->
        join('')
    echo result
enddef
Func()
```
---

Non-automatic line continuations fix the error:
```vim
vim9script
let result = 'abcdefghi'
    \->split('\zs')
    \->filter('v:val !~# "[aei]"')
    \->join('')
echo result
```
```vim
vim9script
let result = 'abcdefghi'->
    \split('\zs')->
    \filter('v:val !~# "[aei]"')->
    \join('')
echo result
```

**Comment by brammool** [comment]
I very much prefer putting the "->" after the line break, it's more readable, it's easier to see that it is a continuation line:
       let result = expr
           ->method()
           ->method()

I do not consider "->" to be similar to an operator, just like ".member" is not.

So the question is, should we enforce putting the line break before "->", or allow for both?

**Comment by lacygoill** [comment]
> I very much prefer putting the "->" after the line break, it's more readable, ...

I have the same opinion; I like reading operators/tokens which are aligned; this is only possible when putting the line break before `->`.

---

> I do not consider "->" to be similar to an operator, just like ".member" is not.

Ok, I'll use the term "token" instead of "operator" from now on.

---

> So the question is, should we enforce putting the line break before "->", or allow for both?

There are two questions on softwareengineering.stackexchange.com which are relevant:

   - [Line break before/after operator](https://softwareengineering.stackexchange.com/questions/93670/line-break-before-after-operator)
   - [Should I put newlines before or after binary operators?](https://softwareengineering.stackexchange.com/questions/160522/should-i-put-newlines-before-or-after-binary-operators)

It seems that the most upvoted answers either recommend putting a line break *before* an operator, or to just follow the most commonly used style guidelines.  The only Vimscript style guideline I know of is the one from [Google](https://google.github.io/styleguide/vimscriptfull.xml), but it doesn't seem to recommend anything relevant for the current issue.

FWIW, I would enforce putting the line break before `->`, but other people may disagree.  No matter what is decided, I think it should be consistent between a `:def` function and the script level.

**Comment by brammool** [comment]
Since this line break support is new, it's better to be restrictive at first, and perhaps loosen it up when we decide that is needed.  The other way around, making it restrictive later, doesn't work well.
