### ISSUE TITLE
Vim9: "E1099: Unknown error" when calling a function via a funcref passed as a function argument

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6493]
**Describe the bug**

In Vim9 script, an unexpected error is raised when calling a function via a funcref passed as a function argument.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Foo()
            echo 'foo'
        enddef
        def Bar(F: func)
            F()
        enddef
        let Funcref = function('Foo')
        Bar(Funcref)
    EOF
    )

`foo` is echo'ed, and `E1099` is raised:

    foo
    Error detected while processing function <SNR>1_Bar:
    line    1:
    E1099: Unknown error while executing <SNR>1_Bar

**Expected behavior**

`foo` is echo'ed, and no error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-1253
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(356)

**Additional context**

Note that `Foo()` has been correctly invoked, since `foo` is echo'ed.  Which means that the funcref has been correctly used.

---

Here's another code snippet which triggers the same error, but which doesn't involve a funcref:
```vim
vim9script
def Foo()
    Bar()
enddef
def Bar()
    echo 'bar'
enddef
Foo()
```
    bar
    Error detected while processing function <SNR>1_Foo:
    line    1:
    E1099: Unknown error while executing <SNR>1_Foo

**Comment by bfrg** [comment]
I encountered the same error but in a different context (still haven't found a minimal example). 

The above snippet works fine in older versions. `git-bisect` shows that it was introduced in 682d0a15 (8.2.1251).

**Comment by brammool** [comment]
Please check if this is fixed in 8.2.1261

**Comment by lacygoill** [comment]
Can confirm that the issue is fixed by 8.2.1261; thank you very much.

**Comment by lacygoill** [comment]
I regularly encounter this E1099 error, but it's not documented.  Should it be consistently reported?  Is it similar to an internal error?  Does it necessarily come from a Vim bug, or is it just a regular error resulting from a mistake in our code?

**Comment by brammool** [comment]
> I regularly encounter this E1099 error, but it's not documented.
> Should it be consistently reported?  Is it similar to an internal
> error?  Does it necessarily come from a Vim bug, or is it just a
> regular error resulting from a mistake in our code?

This error is given when executing a compiled function fails, but when
aborting the function no error message was given yet.  It's a catch-all.

If you encounter this, please find a minimal reproducible example.
We should most likely report an error where it is detected.

-- 
hundred-and-one symptoms of being an internet addict:
89. In addition to your e-mail address being on your business
    cards you even have your own domain.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dpelle** [comment]
@brammool wrote:

> If you encounter this, please find a minimal reproducible example.
> We should most likely report an error where it is detected.

Does it mean it should be an internal error? If yes, it should
use `siemsg(_(e_unknown_error_while_executing_str), …`
instead of `semsg(_(e_unknown_error_while_executing_str), …`
(so such bug can be detected when fuzzing).

And the internal error would need to be added to the list
of internal errors in `runtime/doc/message.txt` (where it
documents all internal errors: E222, E228, etc.) and
where it suggests to report a bug if they can be reproduced.

There are probably other errors in vim which could be promoted
as internal errors. For example:

`regexp_nfa.c`:
```
  1755                             result = nfa_emit_equi_class(equiclass);
  1756                             if (result == FAIL)
  1757                             {
  1758                                 // should never happen
  1759                                 EMSG_RET_FAIL(_("E868: Error building NFA with equivalence class!"));
  1760                             }
```

`if_tcl.c:`
```
  1530     // This should never happen.  Famous last word?
  1531     emsg(_("E280: TCL FATAL ERROR: reflist corrupt!? Please report this to vim-dev@vim.org"));
```

`undo.c`:
```
3465     if (lnum < 1 || lnum > curbuf->b_ml.ml_line_count) // should never happen
3466         return;
```

**Comment by brammool** [comment]
> @brammool wrote:
> 
> > If you encounter this, please find a minimal reproducible example.
> > We should most likely report an error where it is detected.
> 
> Does it mean it should be an internal error? If yes, it should
> use `siemsg(_(e_unknown_error_while_executing_str), …`
> instead of `semsg(_(e_unknown_error_while_executing_str), …`
> (so such bug can be detected when fuzzing).

Eventually, yes.  But as the original reporter mentioned, we need to do
more work before it can be considered an internal error.

> And the internal error would need to be added to the list
> of internal errors in `runtime/doc/message.txt` (where it
> documents all internal errors: E222, E228, etc.) and
> where it suggests to report a bug if they can be reproduced.
> 
> There are probably other errors in vim which could be promoted
> as internal errors. For example:
> 
> `regexp_nfa.c`:
> ```
>   1755                             result = nfa_emit_equi_class(equiclass);
>   1756                             if (result == FAIL)
>   1757                             {
>   1758                                 // should never happen
>   1759                                 EMSG_RET_FAIL(_("E868: Error building NFA with equivalence class!"));
>   1760                             }
> ```
> 
> `if_tcl.c:`
> ```
>   1530     // This should never happen.  Famous last word?
>   1531     emsg(_("E280: TCL FATAL ERROR: reflist corrupt!? Please report this to vim-dev@vim.org"));
> ```
> 
> `undo.c`:
> ```
> 3465     if (lnum < 1 || lnum > curbuf->b_ml.ml_line_count) // should never happen
> 3466         return;
> ```

I suppose that should be OK.  Can you make a pull request?

-- 
hundred-and-one symptoms of being an internet addict:
91. It's Saturday afternoon in the middle of May and you
    are on computer.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
