### ISSUE TITLE
Vim9: can't unpack list items to variables in ":def" function

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6494]
**Describe the bug**

In Vim9 script, we can't unpack the items from a list to variables, while inside a `:def` function.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            let [x, y, z] = [1, 2, 3]
        enddef
        defcompile
    EOF
    )

`E1092` is raised:

    Error detected while processing function Func:
    line    1:
    E1092: Cannot use a list for a declaration

**Expected behavior**

No error is raised.  `1`, `2` and `3` are assigned to the variables `x`, `y` and `z`.

**Environment**

 - Vim version: 8.2 Included patches: 1-1253
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(356)

**Additional context**

The issue disappears at the script level:
```vim
vim9script
def Func(): any
    return [1, 2, 3]
enddef
let [x, y, z] = Func()
```
Although, another error is raised if we don't rely on `:h type-inference`:
```vim
vim9script
def Func(): any
    return [1, 2, 3]
enddef
let x: number
let y: number
let z: number
[x, y, z] = Func()
```
    Error detected while processing ...
    line    8:
    E15: Invalid expression: [x, y, z] = Func()

---

I found this test which suggests that the error is to be expected:

https://github.com/vim/vim/blob/6434fc574dfbde11461e70e5a62712370edf38e6/src/testdir/test_vim9_script.vim#L166

If it is working as intended, then maybe the documentation at `:h vim9-declaration` should be updated to let the user know of this limitation.

---

Or maybe we need the `tuple` type for the code to work; I don't know.  From `:h vim9-types`:

> Not supported yet:
>         tuple<a: {type}, b: {type}, ...>

Maybe we could/should then write something like this:
```vim
vim9script
def Func()
    let [x, y, z]: tuple<x: number, y: number, z: number> = [1, 2, 3]
enddef
defcompile
```

**Comment by lacygoill** [comment]
> Although, another error is raised if we don't rely on `:h type-inference`:
> ```vim
> vim9script
> def Func(): any
>     return [1, 2, 3]
> enddef
> let x: number
> let y: number
> let z: number
> [x, y, z] = Func()
> ```
>     Error detected while processing ...
>     line    8:
>     E15: Invalid expression: [x, y, z] = Func()

I don't know whether the fact that `:h let-unpack` doesn't work for declarations is a bug, but the fact that it doesn't even work for assignments definitely looks like one, because of this:

https://github.com/vim/vim/blob/b146e01a7e41bf5787a2b5ccc6c340ed6001f308/runtime/doc/vim9.txt#L309-L311

**Comment by lacygoill** [comment]
Btw, the example given in the previous paragraph of the documentation doesn't work.  Neither at the script level:
```vim
vim9script
def Func(): list<number>
    return [1, 2]
enddef
let var1: number
let var2: number
[var1, var2] =
        Func()
```
    Error detected while processing /proc/17235/fd/11:
    line    7:
    E15: Invalid expression: [var1, var2] =

Nor in a `:def` function:
```vim
vim9script
def Foo(): list<number>
    return [1, 2]
enddef
def Bar()
    let var1: number
    let var2: number
    [var1, var2] =
            Foo()
enddef
Bar()
```
    Error detected while processing function <SNR>1_Bar:
    line    3:
    E1004: white space required before and after '='

**Comment by brammool** [comment]
> **Describe the bug**
> 
> In Vim9 script, we can't unpack the items from a list to variables, while inside a `:def` function.
> 
> **To Reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(cat <<'EOF'
>         vim9script
>         def Func()
>             let [x, y, z] = [1, 2, 3]
>         enddef
>         defcompile
>     EOF
>     )
> 
> `E1092` is raised:
> 
>     Error detected while processing function Func:
>     line    1:
>     E1092: Cannot use a list for a declaration
> 
> **Expected behavior**
> 
> No error is raised.  `1`, `2` and `3` are assigned to the variables `x`, `y` and `z`.

Inferring types in an unpack assignment can be hard.  In the example it
works, since it's a list constant.  But when the type is "any" it would
need to be checked at runtime.  With list<any> the variable types become
"any", which isn't very nice.

Since first declaring the variables works, let's leave this for later.


> **Environment**
> 
>  - Vim version: 8.2 Included patches: 1-1253
>  - OS: Ubuntu 16.04.6 LTS
>  - Terminal: XTerm(356)
> 
> **Additional context**
> 
> The issue disappears at the script level:
> ```vim
> vim9script
> def Func(): any
>     return [1, 2, 3]
> enddef
> let [x, y, z] = Func()
> ```
> Although, another error is raised if we don't rely on `:h type-inference`:
> ```vim
> vim9script
> def Func(): any
>     return [1, 2, 3]
> enddef
> let x: number
> let y: number
> let z: number
> [x, y, z] = Func()
> ```
>     Error detected while processing ...
>     line    8:
>     E15: Invalid expression: [x, y, z] = Func()

That can be fixed.
 
> I found this test which suggests that the error is to be expected:
> 
> https://github.com/vim/vim/blob/6434fc574dfbde11461e70e5a62712370edf38e6/src/testdir/test_vim9_script.vim#L166
> 
> If it is working as intended, then maybe the documentation at `:h
> vim9-declaration` should be updated to let the user know of this
> limitation.

This refers to the first problem.  I can add a note in the help.

> Or maybe we need the `tuple` type for the code to work; I don't know.  From `:h vim9-types`:
> 
> > Not supported yet:
> >         tuple<a: {type}, b: {type}, ...>
> 
> We could/should then write something like this:
> ```vim
> vim9script
> def Func()
>     let [x, y, z]: <x: number, y: number, z: number> = [1, 2, 3]
> enddef
> defcompile
> ```

I don't like it, too complicated.  Either type inferrence should work,
or the types should be declared separately.

-- 
hundred-and-one symptoms of being an internet addict:
48. You get a tatoo that says "This body best viewed with Netscape 3.1 or
    higher."

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
