### ISSUE TITLE
vimrc sharing

### ISSUE THREAD

**Issue by y1lichen** [vim/vim#6500]
#press the f5 to compile and run the c/c++/python/javascript
map <F5> :call CompileAndRun()<CR>
func! CompileAndRun()
    exec "w"
    if &filetype == 'c'
        exec "!clang -std=c11 % -o /tmp/a.out && /tmp/a.out"
    elseif &filetype == 'cpp'
        exec "!clang++ -std=c++11 % -o /tmp/a.out && /tmp/a.out"
    elseif &filetype == 'java'
        exec "!javac %"
        exec "!java %<"
    elseif &filetype == 'sh'
        :!%
    elseif &filetype == 'python'
        exec "!python3 %"
    endif
endfunc

#auto matching the（）,[],{},<>,"",''
inoremap ( ()<ESC>i
inoremap [ []<ESC>i
inoremap { {}<ESC>i
inoremap < <><ESC>i
inoremap ‘ ‘‘<ESC>i
inoremap " ""<ESC>i

#press lh(line head) to go to the head of the line, and le(line end) to the end of the line.
nmap lh ^
nmap le $

#press ii to go back to normal mode.
map! ii <Esc> " map ii to Esc

#some fundamental setting 

set noswapfile

syntax on
set background=dark
set t_Co=256

filetype on
filetype indent on
filetype plugin on

set tabstop=4 softtabstop=4 shiftwidth=4
set scrolloff=10
set showmode
set clipboard=unnamed

set hlsearch
set ignorecase
set incsearch

set splitbelow
set splitright

set ai
set nowrap
set number
set cursorline
set showmatch

set nocompatible

**Comment by k-takata** [comment]
This is a bug tracker for problems with Vim. If you want to share some useful information on how to use vim, please use the vim_use mailing list or vi.stackexchange.com. Closing.
