### ISSUE TITLE
Vim9: can't specify "v:none" to use default expression in a ":def" function call

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6504]
**Describe the bug**

In Vim9 script, we can't specify `v:none` to use a default expression in a `:def` function call.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func(n = 123, s = 'foo')
        enddef
        Func(v:none, 'bar')
    EOF
    )

`E1013` is raised:

    E1013: type mismatch, expected number but got special

**Expected behavior**

No error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-1258
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(356)

**Additional context**

This usage of `v:none` is documented at `:h optional-function-argument`:
https://github.com/vim/vim/blob/08815a1d0350fbcc007aea5dd1272454c03fab4f/runtime/doc/eval.txt#L11714-L11721

---

The same code works as expected in a legacy function:
```vim
vim9script
fu Func(n = 123, s = 'foo')
endfu
Func(v:none, 'bar')
```

**Comment by lacygoill** [comment]
I understand the error.  On the one hand, in the function's header, Vim infers the type `number` from the value `123`. OTOH, at the call site, Vim gets a `v:none` value whose type is `special` which doesn't match the previously inferred type.

Maybe Vim could accept the `special` type for an optional named argument.

Otherwise, `:h vim9` says that we can use what seems to be an alternation of types:
https://github.com/vim/vim/blob/08815a1d0350fbcc007aea5dd1272454c03fab4f/runtime/doc/vim9.txt#L562

I guess that in theory, we could use this to declare the type `number|special`:
```vim
vim9script
def Func(n: number|special = 123, s = 'foo')
enddef
Func(v:none, 'bar')
```
But it doesn't work for the current issue:

    Error detected while processing ...
    line    2:
    E475: Invalid argument: n: number|special = 123, s = 'foo')
    line    3:
    E193: :enddef not inside a function
    line    4:
    E117: Unknown function: Func

More generally, it doesn't seem to work at all:
```vim
vim9script
def Func(x: number|string)
    echo x
enddef
Func(3)
```
    Error detected while processing ...
    line    2:
    E475: Invalid argument: x: number|string)
    line    3:
    E121: Undefined variable: x
    line    4:
    E193: :enddef not inside a function
    line    5:
    E117: Unknown function: Func

If it has not been implemented yet, maybe the documentation should be temporarily re-written like this:

    {type}|{type} {not implemented yet}

**Comment by brammool** [comment]
Support for passing v:none wasn't done yet, not even listed as TODO.

Support for {type}|{type} was mentioned tentatively.  It would probably be better to not support this, since it allows
for writing messy code.  On the other hand, we already have builtin functions where the return type depends on the situation,
thus it might be unavoidable to support it.

**Comment by andymass** [comment]
What about `optional<type>`?

Separately, was passing `v:none` to mean use default value a good idea in the first place?  It is a bit magical (neovim rejected the patch for these semantics).

**Comment by brammool** [comment]
optional<type> is something else, an object with methods like get() and isSet().  Such as the Java Optional class.
I think what you would want is  {type}|void

Javascript has the "undefined" value, but the semantics are different from v:none or anything else.
We probably can't make it do the same.  To avoid the wrong expectations it's probably better not to use it at all.

What does neovim use then to use the default value of an argument?

**Comment by lacygoill** [comment]
> Separately, was passing v:none to mean use default value a good idea in the first place? It is a bit magical (neovim rejected the patch for these semantics).

I could be wrong, but I think there is an item in the todo list which would allow us to avoid this pitfall:
https://github.com/vim/vim/blob/bc6fcbe4ce52bc48c3d77b24086acc61ed3333bc/runtime/doc/todo.txt#L1204-L1206

Once it's implemented in legacy Vimscript and adapted to Vim9, instead of using `v:none` to skip an argument in a function call, we should be able to specify for which argument a value is intended directly via its name rather than via its position.

**Comment by andymass** [comment]
> What does neovim use then to use the default value of an argument?

As far as I know, neovim did not pick up default function arguments at all, preferring lua for "advanced language features" (https://github.com/neovim/neovim/pull/11785#issuecomment-579655487, https://github.com/neovim/neovim/pull/12377).

**Comment by lacygoill** [comment]
> there is an item in the todo list which would allow us to avoid this pitfall:

Although, using a named argument in a function call can cause [another pitfall](https://groups.google.com/g/vim_dev/c/5p_6AFwBB9c/m/GHQJqo_XAwAJ); if you rename an argument in the function's header, you'll need to remember to visit each function call, check whether you specified the argument via its name rather than its position, and if so, rename it there too...

**Comment by brammool** [comment]
The mechanism to pass a value like "undefined" is useful, predictable and known to javascript/typescript programmers.  Some languages that don't have it often resort to passing "null", which the function then needs to check, no default value would work, and in some cases "null" is a valid value, thus it's not directly clear what happens with that value..  So I like this mechanism, and don't see a disadvantage in supporting it.

Passing arguments by name is useful when there are a lot of arguments.  But it's a complicated mechanism.  There are alternatives, such as passing a struct or, for Vim, passing a dict.  I'm not against supporting named argument, but I consider it "nice to have", lower priority.

One thing we could still choose is the name.  v:none is a bit strange.  I already mentioned why I don't like "undefined", we can't make it do what it does in Javascript, thus sets wrong expectations.  Another alternative is using "nil".  But that introduces another keyword.  So far I think using v:none is the least worst.
