### ISSUE TITLE
Vim9: can't declare a funcref with "func: {type}"

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6507]
**Describe the bug**

In Vim9 script, we can't declare a funcref with `func: {type}`.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Foo(): number
            return 123
        enddef
        let Funcref: func: number = function('Foo')
        echo Funcref()
    EOF
    )

`E117` is raised:

    E117: Unknown function:

Run this other shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Foo(): number
            return 123
        enddef
        def Bar(F: func: number)
            echo F()
        enddef
        let Funcref = function('Foo')
        Bar(Funcref)
    EOF
    )

`E475` is raised (along with a few other errors):

    E475: Invalid argument: F: func: number)

**Expected behavior**

No error is raised in either command.

**Environment**

 - Vim version: 8.2 Included patches: 1-1261
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(356)

**Additional context**

According to `:h vim9-types`, we can declare a funcref type in more or less specific ways (7 to be exact):
https://github.com/vim/vim/blob/f56c95fdad5af521887f8cd7bc15729b5355231d/runtime/doc/vim9.txt#L570-L587

We can do it in the context of a variable assignment, or in a function's header.

That's 14 possibilities in total (7 x 2). Right now, only 4 seem to work:

                                                                 ┌─────────────────────────────────────────┐
                                                                 │                  context                │
                                                                 ├─────────────────────┬───────────────────┤
                                                                 │ variable assignment │ function's header │
    ┌─────────────────┬──────────────────────────────────────────┼─────────────────────┼───────────────────┤
    │                 │ func                                     │          ✔          │         ✔         │
    │                 ├──────────────────────────────────────────┼─────────────────────┼───────────────────┤
    │                 │ func: {type}                             │          ✘          │         ✘         │
    │                 ├──────────────────────────────────────────┼─────────────────────┼───────────────────┤
    │                 │ func({type})                             │          ✔          │         ✘         │
    │ ways to specify ├──────────────────────────────────────────┼─────────────────────┼───────────────────┤
    │ a funcref type  │ func({type}): {type}                     │          ✔          │         ✘         │
    │                 ├──────────────────────────────────────────┼─────────────────────┼───────────────────┤
    │                 │ func(?{type})                            │          ✘          │         ✘         │
    │                 ├──────────────────────────────────────────┼─────────────────────┼───────────────────┤
    │                 │ func(...{type})                          │          ✘          │         ✘         │
    │                 ├──────────────────────────────────────────┼─────────────────────┼───────────────────┤
    │                 │ func({type}, ?{type}, ...{type}): {type} │          ✘          │         ✘         │
    └─────────────────┴──────────────────────────────────────────┴─────────────────────┴───────────────────┘

The rest of the report is just a long list of snippets which test each possibility.

---

`func` works in a variable assignment:
```vim
vim9script

def Foo()
    echo 'test'
enddef

let Funcref: func = function('Foo')
Funcref()
```
    test

And in a function's header:
```vim
vim9script

def Foo()
    echo 'test'
enddef

def Bar(F: func)
    F()
enddef

let Funcref = function('Foo')
Bar(Funcref)
```
---

`func({type})` works in a variable assignment:
```vim
vim9script

def Foo(n: number)
    echo n
enddef

let Funcref: func(number) = function('Foo')
Funcref(3)
```
    3

However, the `(number)` part of the type does not seem to have any effect. That is, if you declare that the type of the function argument is `string` in the funcref assignment, while in reality its type is `number` in the function's header, then Vim doesn't raise any error:
```vim
vim9script

def Foo(n: number)
    echo n
enddef

let Funcref: func(string) = function('Foo')
Funcref(3)
```
    3

Maybe I misunderstood something, but it looks wrong. During type checking, I would expect Vim to raise an error such as:

    E1013: type mismatch, expected func(number) but got func(string)

The `expected func(number)` part of the error message because of the function's header:

    def Foo(n: number)
            ^-------^

And the `but got func(string)` part because of the funcref assignment:

    let Funcref: func(string) = function('Foo')
                 ^----------^

Otherwise, I don't understand what is the purpose of `({type})`.

---

`func({type})` does *not* work in a function's header:
```vim
vim9script

def Foo(n: number)
    echo n
enddef

def Bar(F: func(number))
enddef

let Funcref: func(number) = function('Foo')
Bar(Funcref)
```
    E1013: type mismatch, expected func(number) but got func(): any

---

`func({type}): {type}` works in a variable assignment:
```vim
vim9script

def Foo(n: number): string
    return n .. ' things'
enddef

let Funcref: func(number): string = function('Foo')
echo Funcref(3)
```
    3 things

However, again, neither the `(number)` part nor the `: string` part of the type seem to have any effect:
```vim
vim9script

def Foo(n: number): string
    return n .. ' things'
enddef

let Funcref: func(bool): float = function('Foo')
echo Funcref(3)
```
The previous snippet does not raise any error, while I would expect Vim to raise an error such as:

    E1013: type mismatch, expected func(number): string but got func(bool): float

`expected func(number): string` because of the function's header:

    def Foo(n: number): string
            ^----------------^

And `but got func(bool): float` because of the funcref assignment:

    let Funcref: func(bool): float = function('Foo')
                 ^---------------^

---

`func({type}): {type}` does *not* work in a function's header:
```vim
vim9script

def Foo(n: number): string
    return n .. ' things'
enddef

def Bar(F: func(number): string)
enddef

let Funcref: func(number): string = function('Foo')
Bar(Funcref)
```
    E1013: type mismatch, expected func(number): string but got func(): any

---

`func(?{type})` does *not* work in a variable assignment:
```vim
vim9script

def Foo(n = 3)
    echo n
enddef

let Funcref: func(?number) = function('Foo')
Funcref()
```
    E117: Unknown function:

---

`func(?{type})` does *not* work in a function's header:
```vim
vim9script

def Foo(n: number = 3)
    echo n
enddef

def Bar(F: func(?number))
enddef

let Funcref: func(?number) = function('Foo')
Bar(Funcref)
```
    E475: Invalid argument: F: func(?number))

---

`func(...{type})` does *not* work in a variable assignment:
```vim
vim9script

def Foo(...l: list<number>)
enddef

let Funcref: func(...list<number>) = function('Foo')
Funcref()
```
    E985: .= is not supported with script version 2

---

`func(...{type})` does *not* work in a function's header:
```vim
vim9script

def Foo(...l: list<number>)
enddef

def Bar(F: func(...list<number>))
enddef

let Funcref: func(...list<number>) = function('Foo')
Bar(Funcref)
```
    E475: Invalid argument: F: func(...list<number>))

---

`func({type}, ?{type}, ...{type}): {type}` does *not* work in a variable assignment:
```vim
vim9script

def Foo(n: number, m = 12, ...l: list<number>): number
    return 34
enddef

let Funcref: func(number, ?number, ...list<number>): number = function('Foo')
Funcref()
```
    E1007: mandatory argument after optional argument

---

`func({type}, ?{type}, ...{type}): {type}` does *not* work in a function's header:
```vim
vim9script

def Foo(n: number, m = 12, ...l: list<number>): number
    return 34
enddef

def Bar(F: func(number, ?number, ...list<number>): number)
enddef

let Funcref: func(number, ?number, ...list<number>) = function('Foo')
Bar(Funcref)
```
    E475: Invalid argument: F: func(number, ?number, ...list<number>): number)

**Comment by brammool** [comment]
All the examples are working now.  Some with a small correction.
If you find any more problems, please use one issue for a problem that looks like it's the same problem (same error message).
It's a bit easier to keep track.
