### ISSUE TITLE
vim9script: w:, b:, t: and g: variables cannot be declared with a type

### ISSUE THREAD

**Issue by bfrg** [vim/vim#6521]
**Describe the bug**
`w:`, `b:`, `t:`, `g:` variables cannot be typed in `vim9script`, neither at script level nor inside `:def` functions.

**To Reproduce**
1. Run `vim --clean -S test.vim`, with
   ```vim
   vim9script
   def Test()
       w:foo: number = 10
   enddef
   Test()
   ```
2. Result: Vim writes the current buffer to file `:foo: number = 10`.

---

1. Doing the same with a buffer-variable:
   ```vim
   vim9script
   def Test()
       b:foo: number = 10
   enddef
   Test()
   ```
2. Result: `E94: No matching buffer for :foo: number = 10`

---

1. tabpage-variable:
   ```vim
   vim9script
   def Test()
       t:foo: number = 10
   enddef
   Test()
   ```
2. Result: `E16: Invalid range`

---

1. global-variable:
   ```vim
   vim9script
   def Test()
       g:foo: number = 10
   enddef
   Test()
   ```
2. Result: `Pattern not found: foo`

**Expected behavior**
I would have expected the above to work.

**Environment**
Vim version `8.2.1281`

**Comment by brammool** [comment]
These variables can be set to any value in legacy Vim script and legacy functions.  Specifying a type has very limited use that way.  It would work to catch mistakes in Vim9 code, in case you try to assign a value of the wrong type, but one cannot assume that these variables actually have the specified type.  This also means that in compiled functions the type always must be checked anyway.
For consistency I thought it might be better to just not use types for these variables, based on the namespace.  It could be possible to attach the type to the variable (would require more memory though).  Thus then what you get is once a variable has been given a type in Vim9 code, the type will also be checked in legacy code.  This also has runtime overhead, the type needs to be checked on every assignment.  And then you will have some g: variables with a specified type and some without.  Also, what if a variable is deleted and added back with a different type?  Would be confusing, and will be hard to avoid.

**Comment by bfrg** [comment]
Maybe an error message can be printed when someone specifies a type for these variables?
