### ISSUE TITLE
vim9script: not possible to use imported functions as popup-filters, error or segmentation fault

### ISSUE THREAD

**Issue by bfrg** [vim/vim#6522]
**Describe the bug**
It is not possible to use imported functions as popup-filters. Vim prints an error, or even crashes when the wrong syntax is used.

**To Reproduce**
1. Run `vim --clean -S test.vim` with the following two files:
   ```vim
   " filter.vim
   vim9script
   export def Filter(winid: number, key: string): bool
       return false
   enddef
   ```
   and
   ```vim
   " test.vim
   vim9script
   import Filter from './filter.vim'
   def Test()
       popup_create('test...', {'filter': funcref('Filter')})
   enddef
   Test()
   ```
2. Result:
   ```
   Error detected while processing function <SNR>14_Test:
   line    1:
   E700: Unknown function: Filter
   ```

---

1. A similar error occurs when `funcref()` is omitted:
   ```vim
   " test.vim
   vim9script
   import Filter from './filter.vim'
   def Test()
       popup_create('test...', {'filter': 'Filter'})
   enddef
   Test()
   ```
2. Result: Vim creates the popup window but when a key is pressed, the following error is printed:
   ```
   E117: Unknown function: Filter
   ```

---

When the function name is not put in quotes, Vim will crash:
```vim
" test.vim
vim9script
import Filter from './filter.vim'
def Test()
    popup_create('test...', {'filter': Filter})
enddef
Test()
```

and similarly:
```vim
" test.vim
vim9script
import Filter from './filter.vim'
def Test()
    popup_create('test...', {'filter': funcref(Filter)})
enddef
Test()
```

Result in either case:
```
Vim: Caught deadly signal SEGV
Vim: Finished.
Segmentation fault
```

**Expected behavior**
No errors or crashes when an imported function is used as a popup-filter.

**Environment**
Vim version `8.2.1281`

This seems to be somehow similar to #6412.

**Comment by lacygoill** [comment]
- [backtrace](https://github.com/vim/vim/files/4967898/backtrace.txt)
 - [valgrind log](https://github.com/vim/vim/files/4967899/valgrind.log)
 - [asan log](https://github.com/vim/vim/files/4967897/asan.log)
