### ISSUE TITLE
Vim9: ":def" cannot be followed by "!"

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6524]
**Describe the bug**

`:def` cannot be followed by `!`.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def! Func()
        enddef
    EOF
    )

`E477` and `E193` are raised:

    E477: No ! allowed
    E193: :enddef not inside a function

**Expected behavior**

No error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-1287
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(356)

**Additional context**

According to `:h :def`, `:def` can be followed by `!`:
<https://github.com/vim/vim/blob/40f4f7a48cae491f83bd3cdbf7e9b5a23ed870ef/runtime/doc/vim9.txt#L496-L498>

---

Vim suggests to add a bang when we try to redefine a `:def` function in the same script:

```vim
vim9script
def Func()
    echo 'one'
enddef
Func()
def Func()
    echo 'two'
enddef
Func()
```
    E122: Function <SNR>1_Func already exists, add ! to replace it

**Comment by lacygoill** [comment]
It's a regression introduced in 09689a02840be40fa7bb10b1921fb5bc5b2908f1.

Although, I'm not entirely sure, because at one point during the bisecting, the error changed from:

    E477: No ! allowed

to:

    E129: Function name required

**Comment by brammool** [comment]
In Vim9 script a function can only be defined once.  Just like variables are declared, you can't "undeclare" them later.

This should only apply to script-local functions, but I notice that it is also enforced for global functions. That looks like a bug.
