### ISSUE TITLE
Vim9: cannot get listing of matching function names after ":def Pattern"

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6525]
**Describe the bug**

On the command-line, we cannot get a listing of the matching function names after `:def Pattern`.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Pattern()
        enddef
        feedkeys(":def Pat\<c-d>", 'nt')
    EOF
    )

`C-d` does not cause the pager to display the functions whose name start with `Pat`; instead it is inserted literally on the command-line.

**Expected behavior**

`C-d` causes the pager to display the name of the `Pattern()` function:

    :def Pat
    <SNR>1_Pattern
    ^------------^

**Environment**

 - Vim version: 8.2 Included patches: 1-1287
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(356)

**Additional context**

The issue does not come from the fact that the pattern was not prefixed by `s:`; the issue persists even with the latter:
```vim
vim9script
def Pattern()
enddef
feedkeys(":def s:Pat\<c-d>", 'nt')
```
---

The issue disappears if we use `:fu` instead of `:def` on the command-line:
```vim
vim9script
def Pattern()
enddef
feedkeys(":fu s:Pat\<c-d>", 'nt')
```
Is it working as intended?  Shouldn't `:fu` only be able to access the names of legacy functions, and `:def` only the names of Vim9 functions?

**Comment by lacygoill** [comment]
I've also noticed that `:delfunction` is able to delete a `:def` function in a legacy script:
```vim
def Func()
enddef
delfunction Func
```
Again, is it working as intended?  Or should we instead use a new `:deldef` command?

**Comment by lacygoill** [comment]
Also, `:fu` is able to give the definition of a `:def` function
```vim
vim9script
def g:Func()
    echo 'test'
enddef
fu Func
```

    :fu Func
        def Func()
     1          echo 'test'
        enddef

So, all in all, it seems that `:fu` and `:delfu` can operate of `:def` functions, just like regular legacy functions.

**Comment by brammool** [comment]
Yes, :def functions are also functions.  You can also call them like functions defined with :function.  So there doesn't seem to be a reason for the need of :deldef.
If you delete a :def function and call it you will get "E933: Function was deleted"

About completion: The script-local function cannot be called from the command line without knowing the script ID.  I don't see why you would want to call it anyway.
In case you just want to find the function, use ":filter Pattern func".

**Comment by lacygoill** [comment]
> About completion: The script-local function cannot be called from the command line without knowing the script ID.  I don't see why you would want to call it anyway.

It's just a matter of consistency; if `:fu` and `:def` can both access the same functions, and if `:fu` is able to expand `s:` (which is the case), then I would expect `:def` to also be able to expand `s:` (which is not the case).

Other than consistency, I regularly want to create a breakpoint in a script-local function.  It only works if I provide the script ID:

    :breakadd func <SNR>123_myfunc

To get this command, I type this:

    :func s:myfunc

Then, I press Tab, and Vim expands the command-line into:

    :func <SNR>123_myfunc

Then, I press `C-b` to jump at the start of the command-line.  Finally, I type `:breakadd ` and press Enter.

It's not a big issue anyway, I'll keep using `:fu` both for legacy functions and Vim9 functions.

> In case you just want to find the function, use ":filter Pattern func".
 
`:filter` would print the full function name on the command-line, but I would still need to copy it; outside tmux, I'm not sure how to do it (I guess with the mouse, but I don't like the mouse).  With the previous method, I don't need to copy anything, because the expansion is not printed; it's inserted.

**Comment by lacygoill** [comment]
I'm closing the issue, because I don't think it's very important anyway, since we can use `:fu` or `:def` interchangeably on the command-line.

**Comment by brammool** [comment]
Ah, you first use completion and then go back and change the command.  Should have completion on ":breakadd func", isn't that working?  Apparently not.
Completion normally uses the typed text as the lead.  In this case the script number would be needed, which you generally don't know.  Expanding "s:FuncName" to include the script number is a bit weird, bit useful anyway.  When typing the "s:" is not meaningful, since there is no script context, thus interpreting this as "any script" makes sense.

**Comment by lacygoill** [comment]
Thank you for adding [a todo item](https://github.com/vim/vim/blob/fa57335e532e505ce9229ddb2354a593fb057561/runtime/doc/todo.txt#L397-L399) to add completion for `:breakadd`:

> Implement completion for "breakadd".  Should expand the second argument, e.g.
> "func", and then function names after ":breakadd func".  Including
> script-local functions.

The same issue applies to `:profile`.
