### ISSUE TITLE
Vim9: can nest a ":def" function inside a legacy function

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6527]
**Describe the bug**

We can nest a `:def` function inside a legacy function.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        fu Foo()
            def Bar()
                echo 'bar'
            enddef
            call Bar()
        endfu
        call Foo()
    EOF
    )

No error is raised; `bar` is echo'ed.

**Expected behavior**

An error is raised; `bar` is *not* echo'ed.

**Environment**

 - Vim version: 8.2 Included patches: 1-1287
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(356)

**Additional context**

According to `:h vim9`, it should not be possible to nest `:def` inside a legacy function:
<https://github.com/vim/vim/blob/40f4f7a48cae491f83bd3cdbf7e9b5a23ed870ef/runtime/doc/vim9.txt#L492-L494>

---

The issue persists even when the nested `:def` function is called at the script level, instead of inside a legacy function:
```vim
fu Foo()
    def Bar()
        echo 'bar'
    enddef
endfu
call Foo()
call Bar()
```
    bar

The issue persists even in a Vim9 script instead of a legacy script:
```vim
vim9script
fu Foo()
    def Bar()
        echo 'bar'
    enddef
    call Bar()
endfu
Foo()
```
    bar
```vim
vim9script
fu Foo()
    def Bar()
        echo 'bar'
    enddef
endfu
Foo()
Bar()
```
    bar

**Comment by brammool** [comment]
At first it wasn't possible to detect the end of the nested function, but since then this has been implemented.  There might be some problems with line continuation, but we can probably fix them if found.  Or add a rule what doesn't work, such as that you can't put :endfunction or :enddef after a |.  I'll adjust the help.
