### ISSUE TITLE
vim9script: E565: Not allowed to change text or change window: vim9script

### ISSUE THREAD

**Issue by bfrg** [vim/vim#6529]
**Describe the bug**
Vim prints an error when a `def` autoload function is called after the `TextYankPost` event. The error is printed only on the first yank.

**To Reproduce**
1. Run `vim --clean test.vim -S test.vim` with
   ```vim
   vim9script

   let file =<< trim END
       vim9script
       def foo#test()
           echomsg getreg('"')
       enddef
   END

   mkdir('/tmp/Xdir/autoload', 'p')
   writefile(file, '/tmp/Xdir/autoload/foo.vim')
   set rtp^=/tmp/Xdir

   augroup test
       autocmd!
       autocmd TextYankPost * call foo#test()
   augroup END
   ```
3. The following error is printed on the first yank:
   ```
   Error detected while processing /tmp/Xdir/autoload/foo.vim:
   line    1:
   E565: Not allowed to change text or change window: vim9script
   ```

---

When the function is in the same script as the `autocmd` declaration, no errors are printed. The following works:
```vim
vim9script

def Test()
    echomsg getreg('"')
enddef

augroup test
    autocmd!
    autocmd TextYankPost * call Test()
augroup END
```
Imported `def` functions work as well.

**Expected behavior**
No error messages.

**Environment**
Vim version `8.2.1287`

**Comment by lacygoill** [comment]
Not sure whether this is the same issue, but the same error is raised when we try to call an autoload function from an `<expr>` mapping.

To reproduce, run these shell commands:

    mkdir -p /tmp/some/{plugin,autoload}

    cat <<'EOF' >/tmp/some/plugin/some.vim
        nno <expr> <c-b> some#func()
        call feedkeys("\<c-b>")
    EOF

    cat <<'EOF' >/tmp/some/autoload/some.vim
        vim9script
        def some#func(): string
            return ''
        enddef
    EOF

    vim -Nu NORC --cmd 'set rtp^=/tmp/some'
