### ISSUE TITLE
crash when using a script-local function to generate matches for "input()"

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6532]
**Describe the bug**

Vim crashes when using a script-local function to generate matches for `input()`.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        fu s:func(...)
            return ''
        endfu
        call timer_start(0, {-> feedkeys("\<tab>", 'nt')})
        let _ = input('', '', 'custom,s:func')
    EOF
    )

Vim crashes.

**Expected behavior**

Vim doesn't crash.

**Environment**

 - Vim version: 8.2 Included patches: 1-1288
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(356)

**Additional context**

If we don't try to save the output of `input()` in a variable, Vim doesn't crash; instead, it raises `E120`:
```vim
fu s:func(...)
    return ''
endfu
call timer_start(0, {-> feedkeys("\<tab>", 'nt')})
call input('', '', 'custom,s:func')
```
    E120: Using <SID> not in a script context: s:func

---

- [backtrace](https://github.com/vim/vim/files/4973902/backtrace.txt)
- [valgrind log](https://github.com/vim/vim/files/4973903/valgrind.log)
- [asan log](https://github.com/vim/vim/files/4973901/asan.log)

**Comment by lacygoill** [comment]
I know that the code is wrong, because we need to expand `s:` manually:
```vim
if !exists('s:SID')
    fu s:SID() abort
        return expand('<sfile>')->matchstr('<SNR>\zs\d\+\ze_SID$')->str2nr()
    endfu
    const s:SID = s:SID()->printf('<SNR>%d_')
    delfu s:SID
endif

fu s:func(...) abort
    return ''
endfu

let _ = input('', '', 'custom,'..s:SID..'func')
```
Still, Vim should not crash.

**Comment by lacygoill** [comment]
It's a regression introduced in 793648fb563359396a23740c72a6e04cb64df3a9.

**Comment by lacygoill** [comment]
Forget about the previous comment; I must have made a mistake, because I can reproduce the crash on 8.2.1061.

**Comment by lacygoill** [comment]
Oh, I understand where I made a mistake.  The crash is non-deterministic, which means I should I have run the shell command several times for each test.

**Comment by lacygoill** [comment]
I've bisected a second time, making several tests on each commit, and it seems the regression was actually introduced in 9721fb4ea3db2559aaf7f71458da8ddda30ff93e.

**Comment by brammool** [comment]
When referencing a patch, it's a lot easier to mention the patch number.  Otherwise I have no navigate to github to check the link.
