### ISSUE TITLE
Vim behaves weirdly when a buffer for which a swap already exists is loaded in a timer callback

### ISSUE THREAD

**Issue by bfrg** [vim/vim#6541]
**Describe the bug**
Loading a buffer in a `timer` callback for which a swap file already exists makes the cursor jump and, depending on the user's configuration, inserts characters into the current buffer or command-line, for example `.,.+11grep<t_ý>gj<CursorHold>`.

**To Reproduce**
The following test loads the file under the cursor 200ms after a `CursorMoved` event has been triggered.

1. Run `vim --clean test.vim -S test.vim` with
   ```vim
   " /tmp/vim/test/file1
   " /tmp/vim/test/file2
   " /tmp/vim/test/file3
   " /tmp/vim/test/file4
   " /tmp/vim/test/file5
   " /tmp/vim/test/file6
   " /tmp/vim/test/file7
   " /tmp/vim/test/file8
   " /tmp/vim/test/file9
   " /tmp/vim/test/file10
   " /tmp/vim/test/file11
   " /tmp/vim/test/file12
   " /tmp/vim/test/file13
   " /tmp/vim/test/file14
   " /tmp/vim/test/file15
   " /tmp/vim/test/file16
   " /tmp/vim/test/file17
   " /tmp/vim/test/file18
   " /tmp/vim/test/file19
   " /tmp/vim/test/file20

   set swapfile
   set directory=/tmp/vim/swap//

   call mkdir('/tmp/vim/swap', 'p')
   call mkdir('/tmp/vim/test', 'p')

   for i in range(1, 20)
       call writefile(['test in file ' .. i], '/tmp/vim/test/file' .. i)
       call writefile([], '/tmp/vim/swap/%tmp%vim%test%file' .. i .. '.swp')
   endfor

   let s:timer = 0
   let s:lastpos = 0

   function s:load(file, ...) abort
       if !filereadable(a:file)
           return
       endif
       let bufnr = bufadd(a:file)
       try
           silent call bufload(bufnr)
       catch /E325:/
           echohl ErrorMsg | echomsg v:exception | echohl None
       endtry
   endfunction

   function s:on_cursor_moved(file) abort
       call timer_stop(s:timer)
       if line('.') != s:lastpos
           let s:lastpos = line('.')
           let s:timer = timer_start(200, funcref('s:load', [a:file]))
       endif
   endfunction

   augroup test
       autocmd! * <buffer>
       autocmd CursorMoved <buffer> call s:on_cursor_moved(expand('<cfile>'))
   augroup END
   ```
2. Now move the cursor over the commented lines `/tmp/vim/test/file1` etc at the top.
3. Result: Cursor jumps over several lines when a single `j` is pressed.

Here's a small [video](https://asciinema.org/a/S3dO8AcosysMljrv94qPMzxDo) that demonstrates this issue: After pressing `j` a few times times I go to the command-line to print the message history but Vim will insert `:jjjj` as soon as I start typing. Then when I move over the other file names, it appears that some of the command-line history is inserted into the buffer.

--- 

When a `CursorHold` autocommand is added, the `<CursorHold>` key is inserted into the command-line, like `:j<CursorHold>j<CursorHold>j<CursorHold>`. Example:
```vim
   augroup test
       autocmd! * <buffer>
       autocmd CursorMoved <buffer> call s:on_cursor_moved(expand('<cfile>'))

       set updatetime=200
       autocmd CursorHold <buffer> silent
   augroup END
```
Video demonstration: https://asciinema.org/a/Fuhf7T5bnxP0XiGXhSHntnTTS

**Expected behavior**
No weird behavior when the `E325` error is thrown in a `timer` callback.

**Environment**
- Vim version `8.2.1287`
- Gentoo Linux
- xfce4-terminal, xterm(357)

**Comment by lacygoill** [comment]
I thought it might be a regression, but it doesn't seem to be the case since I can reproduce the issue on 8.1.1610 where `bufadd()` was introduced.

**Comment by bfrg** [comment]
It looks like this is related to `timers` in combination with the `:h ATTENTION` screen.

When I replace `CursorMoved` and `timer_start()` by the `CursorHold` event, it works as expected:
```vim
" /tmp/vim/test/file1
" /tmp/vim/test/file2
" /tmp/vim/test/file3
" /tmp/vim/test/file4
" /tmp/vim/test/file5
" /tmp/vim/test/file6
" /tmp/vim/test/file7
" /tmp/vim/test/file8
" /tmp/vim/test/file9
" /tmp/vim/test/file10
" /tmp/vim/test/file11
" /tmp/vim/test/file12
" /tmp/vim/test/file13
" /tmp/vim/test/file14
" /tmp/vim/test/file15
" /tmp/vim/test/file16
" /tmp/vim/test/file17
" /tmp/vim/test/file18
" /tmp/vim/test/file19
" /tmp/vim/test/file20

set swapfile
set directory=/tmp/vim/swap//
set updatetime=200

call mkdir('/tmp/vim/swap', 'p')
call mkdir('/tmp/vim/test', 'p')

for i in range(1, 20)
    call writefile(['test in file ' .. i], '/tmp/vim/test/file' .. i)
    call writefile([], '/tmp/vim/swap/%tmp%vim%test%file' .. i .. '.swp')
endfor

function s:load(file) abort
    if !filereadable(a:file)
        return
    endif
    let bufnr = bufadd(a:file)
    try
        silent call bufload(bufnr)
    catch /E325:/
        echohl ErrorMsg | echomsg v:exception | echohl None
    endtry
endfunction

augroup test
    autocmd! * <buffer>
    autocmd CursorHold <buffer> call s:load(expand('<cfile>'))
augroup END
```

**Comment by brammool** [comment]
This indeed is a weird one.  Took me quite a while to dig into it.  Finally discovered that the ATTENTION prompt flushes the buffers, which causes previously typed characters to be used again.  I think I found a fix, but writing a test is too complicated.  Please try after the fix that it's also fixed for you.

**Comment by bfrg** [comment]
Thank you. It seems to work now.
