### ISSUE TITLE
popup_setoptions() resets the window-local 'signcolumn' option of that window

### ISSUE THREAD

**Issue by bfrg** [vim/vim#6542]
**Describe the bug**
Changing popup window options with `popup_setoptions()` always resets the `signcolumn` option of that window. This does not happen for the `number` option.

**To Reproduce**
1. Run `vim --clean -S test.vim` with
   ```vim
   let g:winid = range(1, 5)
           \ ->map({_, i -> repeat('test ', i)})
           \ ->popup_create({'minwidth': 40})
   
   call setwinvar(g:winid, '&signcolumn', 'yes')
   call setwinvar(g:winid, '&number', 1)
   ```
2. Now set one of the popup options, for example `call popup_setoptions(g:winid, {'zindex': 1000})`, and redraw the screen with `CTRL-L`.
3. Result: The `signcolumn` has been disabled.

**Expected behavior**
Since the `number` option of that window is kept the same, I would have expected the same behavior for `signcolumn`.

**Environment**
Vim version `8.2.1287`

**Comment by lacygoill** [comment]
[Can confirm](https://github.com/lacygoill/wiki/blob/master/vim/popup.md#signcolumn-is-sometimes-reset-in-my-popup).
