### ISSUE TITLE
dictionary numeric key assignment to non-existent keys no longer works

### ISSUE THREAD

**Issue by lilydjwg** [vim/vim#6546]
**Describe the bug**

Assignment like `let d.1 = xxx` no longer works after [8.2.1274](https://github.com/vim/vim/commit/63be3d4ba01d565e645d8bf7f4dc900fc9011534).

**To Reproduce**

1. Run `vim --clean`
2. Type 'let d = {}'
3. Type 'let d.1 = 1'
4. Got errors E716 and E488:

```
E716: Key not present in Dictionary: 1 = 1
E488: Trailing characters: = 1
```

**Expected behavior**

A new dictionary entry should be created under that numeric key.

**Environment (please complete the following information):**
 - Vim version: 8.2.1274 onwards
 - OS: Arch Linux
 - Terminal: GNOME Terminal and GUI

**Comment by brammool** [comment]
It looks like this is inconsistent.  Some places check for an alphabetic character, some for any variable name character (including _ and #).  Let's make a separate function for this, that allows for alphanumeric characters and underscore.
