### ISSUE TITLE
gvim fails to compile without glib-compile-resources

### ISSUE THREAD

**Issue by ebfe** [vim/vim#655]
The check in src/auto/configure sets GLIB_COMPILE_RESOURCES to "no" if glib-compile-resources is not found. The Makefile however checks if GLIB_COMPILE_RESOURCES is empty which results in the following error:

```
if test -z "no"; then touch auto/gui_gtk_gresources.h; else \
        no --target=auto/gui_gtk_gresources.h --sourcedir=../pixmaps --generate --c-name=gui_gtk --manual-register gui_gtk_res.xml; \
fi
/bin/sh: line 1: no: command not found
Makefile:2671: recipe for target 'auto/gui_gtk_gresources.h' failed
make[1]: *** [auto/gui_gtk_gresources.h] Error 127
make[1]: Leaving directory '/builddir/vim-7.4.1376/gvim/src'
```

I'm not familiar with the vim configuration machinery, but the following patch
seems to fix this (I only tests the glib-compile-resources not present case):

``` diff
diff --git src/Makefile src/Makefile
index 13c7bc6..cdab81c 100644
--- src/Makefile
+++ src/Makefile
@@ -2668,7 +2668,7 @@ GUI_GTK_RES_INPUTS = \
 auto/gui_gtk_gresources.c: gui_gtk_res.xml $(GUI_GTK_RES_INPUTS)
    $(GLIB_COMPILE_RESOURCES) --target=$@ --sourcedir=../pixmaps --generate --c-name=gui_gtk --manual-register gui_gtk_res.xml
 auto/gui_gtk_gresources.h: gui_gtk_res.xml $(GUI_GTK_RES_INPUTS)
-   if test -z "$(GLIB_COMPILE_RESOURCES)"; then touch $@; else \
+   if test x"no" = x"$(GLIB_COMPILE_RESOURCES)"; then touch $@; else \
        $(GLIB_COMPILE_RESOURCES) --target=$@ --sourcedir=../pixmaps --generate --c-name=gui_gtk --manual-register gui_gtk_res.xml; \
    fi

```

**Comment by nuko8** [comment]
> The check in src/auto/configure sets GLIB_COMPILE_RESOURCES to "no" if glib-compile-resources is not found. 

Right.  But it strongly indicates that your glib hasn't been installed completely, because `glib-compile-resources`  comes with it.   Is there any reason you couldn't install it with that utility for development?
Or, was it not included in  `PATH` at build time for some reason?

**Comment by ebfe** [comment]
> > The check in src/auto/configure sets GLIB_COMPILE_RESOURCES to "no" if glib-compile-resources is not found. 
> 
> Right.  But it strongly indicates that your glib hasn't been installed completely, because `glib-compile-resources`  comes with it.   Is there any reason you couldn't install it with that utility for development?
> Or, was it not included in  `PATH` at build time for some reason?

I cross-compile and prefer to not require glib-compile-resources on the
host system if it isn't necessary.

**Comment by nuko8** [comment]
Hmm.

The use of glib-compile-resources was introduced to the build system in order to avoid the use of a deprecated GDK function, which was used to load icon images.    So, it's indeed necessary.

**Comment by ebfe** [comment]
> The use of glib-compile-resources was introduced to the build system
> in order to avoid the use of a deprecated GDK function, which was used
> to load icon images.
> It was made conditional in bbb3339dbf.
> 
> So, it's indeed necessary.
> It builds just fine (modulo a deprecation warning) when the check is fixed.

**Comment by nuko8** [comment]
> It was made conditional in bbb3339.

It was made conditional to ease the maintenance of Makefile; with that `if` statement, we can keep a list of dependencies intact.

> It builds just fine (modulo a deprecation warning) when the check is fixed.

Suppressing the warning was discussed in our mailing list and is the very reason to use of glib-compile-resources...

**Comment by ebfe** [comment]
Ok. If `glib-compile-resources` is indeed a hard requirement I'd suggest failing at `./configure` time if it can't be found. Right now the build failure looks like the `if` simply tests the wrong condition (in a seldom used code path).

**Comment by nuko8** [comment]
> If glib-compile-resources is indeed a hard requirement

It's not a hard requirement.   I'd say it was a tacit agreement among the list members who thought the deprecated function issue could not be overlooked.

> I'd suggest failing at ./configure time if it can't be found. 

Did you mean you gave up your "cross compile"?

Maybe, the following solution would be better for you:

``` diff
diff --git a/src/configure.in b/src/configure.in
index 92a1bb5..08c326c 100644
--- a/src/configure.in
+++ b/src/configure.in
@@ -2615,6 +2615,7 @@ if test "x$GUITYPE" = "xGTK"; then
       AC_PATH_PROG(GLIB_COMPILE_RESOURCES,[glib-compile-resources],no)
       AC_MSG_CHECKING([glib-compile-resources])
       if test "x$GLIB_COMPILE_RESOURCES" = xno ; then
+       GLIB_COMPILE_RESOURCES=""
         AC_MSG_RESULT([cannot be found in PATH.])
       else
        AC_MSG_RESULT([usable.])
```

**Comment by ebfe** [comment]
On Mon, Feb 22, 2016 at 09:33:21AM -0800, nuko8 wrote:

> > If glib-compile-resources is indeed a hard requirement
> > It's not a hard requirement.   I'd say it was a tacit agreement among the list members who thought the deprecated function issue could not be overlooked.

I'm sorry. I can't follow your logic. Few comment above you said `So,
it's indeed necessary.`

> > I'd suggest failing at ./configure time if it can't be found. 
> > Did you mean you gave up your "cross compile"?
> > No, I use my patch.

**Comment by nuko8** [comment]
> No, I use my patch.

But what if we change the configure script based on your request, "I'd sunggest failing at ./configure time"?  You can't reach `make`...

**Comment by brammool** [comment]
nuko8 wrote:

> > If glib-compile-resources is indeed a hard requirement
> 
> It's not a hard requirement.   I'd say it was a tacit agreement among
> the list members who thought the deprecated function issue could not
> be overlooked.
> 
> > I'd suggest failing at ./configure time if it can't be found. 
> 
> Did you mean you gave up your "cross compile"?
> 
> Maybe, the following solution would be better for you:
> 
> ``` diff
> diff --git a/src/configure.in b/src/configure.in
> index 92a1bb5..08c326c 100644
> --- a/src/configure.in
> +++ b/src/configure.in
> @@ -2615,6 +2615,7 @@ if test "x$GUITYPE" = "xGTK"; then
>        AC_PATH_PROG(GLIB_COMPILE_RESOURCES,[glib-compile-resources],no)
>        AC_MSG_CHECKING([glib-compile-resources])
>        if test "x$GLIB_COMPILE_RESOURCES" = xno ; then
> +       GLIB_COMPILE_RESOURCES=""
>          AC_MSG_RESULT([cannot be found in PATH.])
>        else
>         AC_MSG_RESULT([usable.])
> ```

Thanks, looks like this works.  We just go back to the warning:

‘gdk_pixbuf_new_from_inline’ is deprecated [-Wdeprecated-declarations]

## 

```
f y cn rd ths thn y cn hv grt jb n cmptr prgrmmng
```

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///
