### ISSUE TITLE
Vim not upgrading in home-brew / checking for tgetent()... configure: error: NOT FOUND!

### ISSUE THREAD

**Issue by ans87gh** [vim/vim#6550]
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Describe the bug**
Running homebrew on macOS 11. unable to upgrade vim 8.2.1250 -> 8.2.1300.

**To Reproduce**
Error occurs when trying to upgrade vim 8.2.1250 -> 8.2.1300 or reinstall / force reinstall vim.

**Expected behavior**
Expected regular upgrade without issue as in the past.

**Screenshots**

**Environment (please complete the following information):**
==> Upgrading 1 outdated package:
vim 8.2.1250 -> 8.2.1300
==> Upgrading vim 8.2.1250 -> 8.2.1300 
==> Downloading https://github.com/vim/vim/archive/v8.2.1300.tar.gz
Already downloaded: /Users/ans87mos/Library/Caches/Homebrew/downloads/e8aca3de20bf56ff9e150286ff5f1aa684a1eb87c2a813aec7e01fad67eda7b7--vim-8.2.1300.tar.gz
==> ./configure --prefix=/usr/local --mandir=/usr/local/Cellar/vim/8.2.1300/shar
Last 15 lines from /Users/ans87mos/Library/Logs/Homebrew/vim/01.configure:
checking for uid_t in sys/types.h... yes
checking for uint32_t... yes
checking whether time.h and sys/time.h may both be included... yes
checking for ino_t... yes
checking for dev_t... yes
checking whether byte ordering is bigendian... no
checking for inline... inline
checking for rlim_t... yes
checking for stack_t... yes
checking whether stack_t has an ss_base field... no
checking --with-tlib argument... ncurses
checking for linking with ncurses library... OK
checking for tgetent()... configure: error: NOT FOUND!
      You need to install a terminal library; for example ncurses.
      Or specify the name of the library with --with-tlib.

Do not report this issue to Homebrew/brew or Homebrew/core!

Error: You are using macOS 11.0.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this pre-release version.

**Additional context**

**Comment by k-takata** [comment]
`src/configure.ac` is not changed between 8.2.1250 and 8.2.1300.
Isn't it a homebrew issue?

**Comment by ans87gh** [comment]
Is it? I wasn't exactly sure so I posted here in case there was some resolution.

**Comment by vim-ml** [comment]
On Mon, Jul 27, 2020 at 4:03 PM Ali <vim-dev-github@256bit.org> wrote:
>
> Is it? I wasn't exactly sure so I posted here in case there was some resolution.

Use whatever package manager your system provides to check that the
following are installed:
• the ncurses library;
• the ncurses development package (on my system it is called
ncurses-devel but the name may vary from one OS to the next);
• the terminfo library, or if that isn't available, the termcap library.
All three are necessary to build Vim, and your OS's package manager
should be able to get any of them which isn't yet installed.

Best regards,
Tony.

**Comment by ans87gh** [comment]
I do not have ncurses-dev* and a term* library installed on my macOS .. they are not available through the homebrew package manager but vim was working fine before the new vim release .. I am guessing it either has to do with (a) the new macOS DP3 release, (b) homebrew running on the new macOS release, or something to do with the update installing this time around .. but Im unsure where to start to resolve it .. I am probably going to want until a new DP release, an update of homebrew, or a new vim release to see if the issue persists .. but loosing vim is a blow

**Comment by k-takata** [comment]
This should be fixed in [8.2.1310](https://github.com/vim/vim/commit/bd7f7c123db58dd7f50f4d1391577686d2f1bcc6). Closing.
