### ISSUE TITLE
Vim9: documentation error at ":h autoload"; no need to specify "g:" scope for autoload function

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6553]
**Describe the bug**

Some information given at `:h autoload` is wrong:
https://github.com/vim/vim/blob/0aac67a4314d72a29d3fbee91b6f0ba89e950462/runtime/doc/eval.txt#L11867-L11868
https://github.com/vim/vim/blob/0aac67a4314d72a29d3fbee91b6f0ba89e950462/runtime/doc/eval.txt#L11881-L11885

We don't need need the `g:` scope to call an autoload function in a Vim9 script, nor do we need it in a function header.

**To Reproduce**

Run these shell commands:

    mkdir -p /tmp/some/autoload

    cat <<'EOF' >/tmp/some/autoload/some.vim
        vim9script
        def some#func()
        enddef
    EOF

    vim -Nu NORC --cmd 'set rtp^=/tmp/some' +'call some#func()'

No error is raised even though the `g:` scope was not used, neither in the function call `call some#func()`, nor in the function header `def some#func()`.

**Expected behavior**

Since the help says that `g:` needs to be used, I would expect an error to be raised.
Although, I would prefer Vim to keep working as it is right now (no need to specify `g:` when defining/calling an autoload function), and just remove the wrong documentation.

**Environment**

 - Vim version: 8.2 Included patches: 1-1307
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(358)

**Additional context**

It's not a regression; I can reproduce the current behavior on 8.2.0149 where the Vim9 branch was merged.

---

If the documentation is indeed wrong, then I would consider updating another piece of information at `:h vim9-scopes`:
https://github.com/vim/vim/blob/0aac67a4314d72a29d3fbee91b6f0ba89e950462/runtime/doc/vim9.txt#L122
```diff
diff --git a/runtime/doc/vim9.txt b/runtime/doc/vim9.txt
index 2ba227527..f589138dd 100644
--- a/runtime/doc/vim9.txt
+++ b/runtime/doc/vim9.txt
@@ -119,7 +119,8 @@ When using `:function` or `:def` to specify a new function at the script level
 in a Vim9 script, the function is local to the script, as if "s:" was
 prefixed.  Using the "s:" prefix is optional.
 
-To define or use a global function or variable the "g:" prefix must be used.
+To define or use a global function or variable, the "g:" prefix must be used,
+except for an autoload function.
 
 When using `:function` or `:def` to specify a new function inside a function,
 the function is local to the function.  It is not possible to define a
```

**Comment by lacygoill** [comment]
> Although, I would prefer Vim to keep working as it is right now (no need to specify g: when defining/calling an autoload function), and just remove the wrong documentation.

Rationale:

   1. Requiring the `g:` scope makes the code more verbose.

   2. Requiring the `g:` scope is unexpected for someone who is used to write legacy Vim script.

   3. What's the point of requiring the `g:` scope in the first place?
      Is it because in Vim9 script, an autoload function is meant to be script-local by default?
      But does it even make sense for an autoload function to be script-local?
      If it is script-local, it means it can only be called from the current script (unless – I guess – it's exported); while an autoload function is meant to be called from outside the current script.  I'm probably missing something obvious, but there seems to be a contradiction between script-local and autoload.

**Comment by brammool** [comment]
I hadn't looked into autoload scripts yet.
Normally, in Vim9 script all functions are local.  To use a function outside of the script it either has to be exported/imported, or made global.
Autoload scripts are different, they define a third type of function: "autoloadable".  Those are recognized by the "name#" prefix.
It's like these are exported to this autoload namespace.  These functions are not global, in the sense that the g: prefix is not used, not where it's defined nor where it is called.
As far as I can see we don't need to do anything special for Vim9 script.  The mechanism was already working fine.  So we can add a few tests that using "vim9script" in an autoload script works, and that the "name#" prefix works for :def functions.  And update the documentation.

**Comment by brammool** [comment]
Done in 8.2.1325
