### ISSUE TITLE
Vim9: wrong documentation about 'foobar'->Process()

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6554]
**Describe the bug**

According to the Vim9 help, it is not possible to use a method call on a string without `:eval`:
https://github.com/vim/vim/blob/0aac67a4314d72a29d3fbee91b6f0ba89e950462/runtime/doc/vim9.txt#L227

That's not the case; we *can* use a method call on a string without `:eval`.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Process(l: string)
            echo len(l)
        enddef
        'foobar'->Process()
    EOF
    )

No error is raised.

**Expected behavior**

Either the documentation is right, and an error should be raised, or it's wrong and should be removed.

**Environment**

 - Vim version: 8.2 Included patches: 1-1307
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(358)

**Additional context**

I think the example is no longer relevant since [8.2.1218](https://github.com/vim/vim/releases/tag/v8.2.1218), and should be removed:
```diff
diff --git a/runtime/doc/vim9.txt b/runtime/doc/vim9.txt
index 2ba227527..896dff370 100644
--- a/runtime/doc/vim9.txt
+++ b/runtime/doc/vim9.txt
@@ -224,8 +224,6 @@ identifier or can't be an Ex command.  It does NOT work for string constants: >
 	{'a': 1, 'b': 2}->Process()	# works
 	"foobar"->Process()		# does NOT work
 	("foobar")->Process()		# works
-	'foobar'->Process()		# does NOT work
-	('foobar')->Process()		# works
 
 In case there is ambiguity between a function name and an Ex command, use ":"
 to make clear you want to use the Ex command.  For example, there is both the
```
---

OTOH, the previous 2 examples are still relevant:
https://github.com/vim/vim/blob/0aac67a4314d72a29d3fbee91b6f0ba89e950462/runtime/doc/vim9.txt#L225-L226
```vim
vim9script
def Process(l: string)
    echo len(l)
enddef
"foobar"->Process()
```
    E492: Not an editor command: "foobar"->Process()

Is it working as intended?  If so, why is Vim able to process a method call on a single-quoted string, but not on a double-quoted one?  It can't be due to the fact that a double quote could be parsed as a comment leader; that's no longer possible since [8.2.1125](https://github.com/vim/vim/releases/tag/v8.2.1125) and [8.2.1227](https://github.com/vim/vim/releases/tag/v8.2.1227).

**Comment by brammool** [comment]
This was changed before, when requiring a colon before a range.
The documentation was updated recently.
If that solves it, please close this issue.
