### ISSUE TITLE
Vim9: cannot use "is#" or "is?" inside :def function

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6555]
**Describe the bug**

We cannot use `is#` or `is?` inside a `:def` function.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            echo 'abc' is# 'ABC'
        enddef
        defcompile
    EOF
    )

`E15` is raised:

    E15: Invalid expression:  is# 'ABC'

**Expected behavior**

No error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-1307
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(356)

**Additional context**

`is#` works as expected if you run the code at the script level:
```vim
vim9script
echo 'abc' is# 'ABC'
```
    v:false

This is inconsistent.  I would expect `is#` to work everywhere, including in a `:def` function, or to fail everywhere, including at the script level.

---

The same issue applies to `is?`:
```vim
vim9script
def Func()
    echo 'abc' is? 'ABC'
enddef
defcompile
```
    E15: Invalid expression:  is? 'ABC'

---

`is#` and `is?` work as expected if you replace them with `is`:
```vim
vim9script
def Func()
   echo 'abc' is 'ABC'
enddef
defcompile
```
---

Maybe `is#` and `is?` are meant to be deprecated in Vim9 script in favor of new comparison operators, like `===`:

> These ones are not backwards compatible, we'll fix this in Vim9 script:
> Also, "'' == 0" evaluates to true, which isn't nice.
> Add "===" to have a strict comparison (type and value match).
> Add "==*" (?) to have a value match, but no automatic conversion, and v:true
> equals 1 and 1.0, v:false equals 0 and 0.0.?

[Source](https://github.com/vim/vim/issues/6324#issuecomment-648380552).

This would be in line with the fact that, in Vim9 script, `'ignorecase'` should be ignored by comparison operators:
<https://github.com/vim/vim/blob/0aac67a4314d72a29d3fbee91b6f0ba89e950462/runtime/doc/vim9.txt#L355-L357>

And `is?` does *not* ignore `'ignorecase'`; so dropping it would make sense.

If so, maybe the help should mention this difference at `:h vim9-differences`.
```diff
diff --git a/runtime/doc/vim9.txt b/runtime/doc/vim9.txt
index 2ba227527..531dc14de 100644
--- a/runtime/doc/vim9.txt
+++ b/runtime/doc/vim9.txt
@@ -355,6 +355,7 @@ These commands are too quickly confused with local variable names.
 Comparators ~
 
 The 'ignorecase' option is not used for comparators that use strings.
+|expr-is#|, |expr-is?|, |expr-isnot#| and |expr-isnot?| cannot be used.
 
 
 White space ~
```

**Comment by lacygoill** [comment]
> And is? does not ignore 'ignorecase'; so dropping it would make sense.

Actually, I was wrong, it does ignore `'ignorecase'`, since `is?` always ignores the case regardless of the value of the latter option.

**Comment by brammool** [comment]
This was a mistake from the past.  "is" checks identity, thus matching or ignoring case is irrelevant.  In Vim9 script we are more strict about not allowing things that don't work, thus we give an error.

You first mention that you expected "is#" to work, perhaps I'm missing something?

**Comment by lacygoill** [comment]
> This was a mistake from the past. "is" checks identity, thus matching or ignoring case is irrelevant.

But the case is still relevant:
```vim
vim9script
echo 'abc' is? 'ABC'
```
    v:true

If the case was irrelevant, I would expect this expression to be false, because `'abc'` and `'ABC'` are not the same string; but it's true.

> In Vim9 script we are more strict about not allowing things that don't work, thus we give an error.

If `is#` and `is?` are disallowed in Vim9 script, then I think they should also be disallowed at the script level; not just in a `:def` function.  Right now, the results are inconsistent between the 2 contexts:
```vim
vim9script
echo 'abc' is? 'ABC'
```
    v:true
```vim
vim9script
def Func()
    echo 'abc' is? 'ABC'
enddef
Func()
```
    E15: Invalid expression:  is? 'ABC'

The same command doesn't raise any error at the script level, while it raises `E15` in a `:def` function.

> You first mention that you expected "is#" to work, perhaps I'm missing something?

I'm still used to write `is#` in Vim script legacy, where it doesn't raise any error.  And again, it doesn't raise any error in a Vim9 script at the script level, so why does it raise an error only in a `:def` function?

I'm not saying it should work; if it's meant to be deprecated or disallowed, then that's fine.  But I think it should:

   1. be disallowed in a consistent manner (script level + `:def`)
   2. be documented at `:h vim9-differences`

**Comment by lacygoill** [comment]
> This was a mistake from the past. "is" checks identity, thus matching or ignoring case is irrelevant.

Oh, I see what you mean now.  Yes, I always had difficulties understanding why `is#` and `is?` existed in the first place.  `is` is enough, and `is#`/`is?` don't make much sense, so there is no point in replicating them in Vim9 script.

However, I think my previous point still stands: `is#` and `is?` should be disallowed everywhere, including at the script level.

**Comment by lacygoill** [comment]
> `is` is enough

To be clear, the reason why `is` is enough in Vim9 script (not in legacy Vim script), is because just like any other comparison operator, it ignores `'ignorecase'`:
```vim
vim9script
set ignorecase
echo 'abc' is 'ABC'
```
    v:false
```vim
vim9script
def Func()
    set ignorecase
    echo 'abc' is 'ABC'
enddef
Func()
```
    v:false

**Comment by lacygoill** [comment]
I'm closing this issue because I think it's getting confusing, and the initial report is no longer valid.

The title should not be:

    Vim9: cannot use "is#" or "is?" inside :def function

But:

    Vim9: "is#" and "is?" should be disallowed at the script level

I will open a new updated report later.
