### ISSUE TITLE
Vim9: type of character indexed from string wrongly inferred as number

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6563]
**Describe the bug**

The type of a character indexed from a string is wrongly inferred as number.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            let line = 'abc'
            echo line[1] =~ '\w'
        enddef
        Func()
    EOF
    )

`E1072` is raised:

    E1072: Cannot compare number with string

**Expected behavior**

No error is raised, because `line[1]` is the substring `'b'`, which is still a string and not a number.

**Environment**

 - Vim version: 8.2 Included patches: 1-1313
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(358)

**Additional context**

The issue disappears at the script level:
```vim
vim9script
let line = 'abc'
echo line[1] =~ '\w'
```
    v:true

---

As a workaround, `strpart()` must be used:
```vim
vim9script
def Func()
    let line = 'abc'
    echo strpart(line, 1, 1) =~ '\w'
enddef
Func()
```
    v:true

But it's more verbose.

**Comment by brammool** [comment]
Considering indexing a string, perhaps it's time to index characters instead of bytes.
The only reason we use bytes is for backwards compatibility.  But now that multi-byte support
is default, it would be a good time to change this.
Javascript/typescript appear to do the same thing.
'áëû'[1]
"ë"
And since we do more expression evaluation like Javascript/typescript, this would be consistent.

**Comment by lacygoill** [comment]
> Considering indexing a string, perhaps it's time to index characters instead of bytes.

I can't remember the last time I needed a byte or a set of bytes out of a string.  I think I always need characters.  Indexing characters instead of bytes would definitely be an improvement.

**Comment by lacygoill** [comment]
Fixed by [8.2.1463](https://github.com/vim/vim/commit/ed5918771fcf9877d8445e74c62ab1ce6b8e28c1).

**Comment by nicsig** [comment]
> Considering indexing a string, perhaps it's time to index characters instead of bytes.

Not sure whether it's working as intended, but when using an index in a string slice, composing characters are counted separately:
```vim
vim9script
var str = 'Ë͙͙̬̹͈͔̜́̽D̦̩̱͕͗̃͒̅̐I̞̟̣̫ͯ̀ͫ͑ͧT̞Ŏ͍̭̭̞͙̆̎̍R̺̟̼͈̟̓͆'
echom 'Ë͙͙̬̹͈͔̜́̽D̦̩̱͕͗̃͒̅̐I̞̟̣̫ͯ̀ͫ͑ͧT̞Ŏ͍̭̭̞͙̆̎̍R̺̟̼͈̟̓͆getthis'[strchars(str, true) :]
```
    ̬̹͈ D͗̃Iͯ̀T̞Ŏ̆R̓͆getthi
    ✘
```vim
vim9script
var str = 'Ë͙͙̬̹͈͔̜́̽D̦̩̱͕͗̃͒̅̐I̞̟̣̫ͯ̀ͫ͑ͧT̞Ŏ͍̭̭̞͙̆̎̍R̺̟̼͈̟̓͆'
echom 'Ë͙͙̬̹͈͔̜́̽D̦̩̱͕͗̃͒̅̐I̞̟̣̫ͯ̀ͫ͑ͧT̞Ŏ͍̭̭̞͙̆̎̍R̺̟̼͈̟̓͆getthis'[strchars(str) :]
```
    getthis
    ✔

Maybe we should document this:
```diff
diff --git a/runtime/doc/eval.txt b/runtime/doc/eval.txt
index 03fcb655d..af9ac6ad8 100644
--- a/runtime/doc/eval.txt
+++ b/runtime/doc/eval.txt
@@ -1187,7 +1187,8 @@ byte under the cursor: >
 
 In Vim9 script:
 If expr8 is a String this results in a String that contains the expr1'th
-single character from expr8.  To use byte indexes use |strpart()|.
+single character from expr8; composing characters are counted separately.
+To use byte indexes use |strpart()|.
 
 Index zero gives the first byte or character.  Careful: text column numbers
 start with one!
@@ -1217,8 +1218,8 @@ In legacy Vim script the indexes are byte indexes.  This doesn't recognize
 multibyte encodings, see |byteidx()| for computing the indexes.  If expr8 is
 a Number it is first converted to a String.
 
-In Vim9 script the indexes are character indexes.  To use byte indexes use
-|strpart()|.
+In Vim9 script the indexes are character indexes; composing characters are
+counted separately.  To use byte indexes use |strpart()|.
 
 The item at index expr1b is included, it is inclusive.  For an exclusive index
 use the |slice()| function.
```

**Comment by brammool** [comment]
The strchars() function takes an extra argument to specify not counting composing characters.
When indexing a string we cannot have such an optional argument.  So there are two ways:
1. Index composing characters separately.  If you want to include them you need to figure out the count and use a slice with the right indexes.
2. Index ignoring composing characters.  Then you can easily get one character plus its composing characters.  Now how do you get each character separately?  strcharpart() can do this.

I would think that using a character including its composing characters is most common.  Otherwise you change the meaning of a character.  This is especially when looping over a word or a line and dealing with each character you find.

So how about making the index in string[idx] and string[idx : idx] take a character including the following composing characters?

We can also make strcharpart() have an extra argument to indicate not counting composing characters separately.
That would be consistent with the optional argument in strchars().  I wonder why we didn't call this strcharlen()....

**Comment by lacygoill** [comment]
> I would think that using a character including its composing characters is most common. Otherwise you change the meaning of a character. This is especially when looping over a word or a line and dealing with each character you find.

Indeed, I never want to deal with each composing character.  I always want the "whole" character.

> So how about making the index in string[idx] and string[idx : idx] take a character including the following composing characters?

Yes, I think that's what most people would expect.

**Comment by lacygoill** [comment]
Also, I think it was a bad decision to make `strchars()` count composing characters separately by default.  Every time I need it, I have to pass `true` as a second argument.  In contrast, `charidx()` (which is a much more recent function) does not index composing characters separately by default.  Basically, both functions accept a final optional argument which determines whether composing characters are counted separately or not; but their default behavior is different.  That's why the name of this optional argument is different in the help:

     ┌────────────┬───────────────────┐
     │ function   │ optional argument │
     ├────────────┼───────────────────┤
     │ charidx()  │ {countcc}         │
     ├────────────┼───────────────────┤
     │ strchars() │ {skipcc}          │
     └────────────┴───────────────────┘

Not sure whether it's possible, but – in Vim9 – it would make sense to replace `{skipcc}` with `{countcc}` for `strchars()`.  It would make the code less verbose, because we could drop `true` most of the time; and it would make the function more consistent with `charidx()`.

**Comment by lacygoill** [comment]
> in Vim9 – it would make sense to replace {skipcc} with {countcc} for strchars(). It would make the code less verbose, because we could drop true most of the time; and it would make the function more consistent with charidx().

And if it makes `strchars()` too confusing, then we could introduce a new `strcharlen()` function, as suggested previously:

> That would be consistent with the optional argument in strchars(). I wonder why we didn't call this strcharlen()....

**Comment by brammool** [comment]
> Also, I think it was a bad decision to make `strchars()` count
> composing characters separately by default.  Every time I need it, I
> have to pass `true` as a second argument.

I'm thinking of adding strcharlen() which would work like this.

> In contrast, `charidx()`
> (which is a much more recent function) does not index composing
> characters separately by default.  Basically, both functions accept a
> final optional argument which determines whether composing characters
> are counted separately or not; but their default behavior is
> different.  That's why the name of this optional argument is different
> in the help:
> 
>      ┌────────────┬───────────────────┐
>      │ function   │ optional argument │
>      ├────────────┼───────────────────┤
>      │ charidx()  │ {countcc}         │
>      ├────────────┼───────────────────┤
>      │ strchars() │ {skipcc}          │
>      └────────────┴───────────────────┘
> 
> Not sure whether it's possible, but – in Vim9 – it would make sense to
> replace `{skipcc}` with `{countcc}` for `strchars()`.  It would make
> the code less verbose, because we could drop `true` most of the time;
> and it would make the function more consistent with `charidx()`.

No, making functions behave differently in Vim9 script is too
unexpected.  Especially reverting the meaning of an argument, there is
no way to check it is correct and give a warning.

-- 
BLACK KNIGHT: None shall pass.
ARTHUR:       I have no quarrel with you, brave Sir knight, but I must cross
              this bridge.
BLACK KNIGHT: Then you shall die.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
