### ISSUE TITLE
Netrw: special directory names causes Vim to display directories as if they were empty [Bug]

### ISSUE THREAD

**Issue by ghost** [vim/vim#657]
I discovered this whilst trying to use Vim's Netrw as my file manager (for more generic use).
Me, including two other experienced users have successfully reproduced what seems to be a bug.

**Reproducing the bug:**

```
$ mkdir "Foo [Bar]" && cd $_
$ touch a b c
$ vim .
```

Result: Vim opens up with Netrw and displays an empty directory that contains only one item represented as a single dot (“.”).

**The expected result:**
Netrw should display the contents of the directory in this case the files [a, b, c].

**Comment by justinmk** [comment]
This is likely because `[]` are wildcard characters and netrw is not escaping them before sending to `glob()`. This also affected [dirvish.vim](https://github.com/justinmk/vim-dirvish) (fixed now).

**Comment by ZyX-I** [comment]
Theoretically netrw should be fine by using something like `glob(fnameescape(dir).'/*', 1, 1)`. Actually there is vim/vim#541.

**Comment by lemonad** [comment]
I think I ran into this bug today (OSX 10.13.4 [17E199], vim 8.0.1700).

NerdTree and netrw did not display the correct directory contents (mostly just displayed a single file). Further up the path, I had a directory with a Swedish character in its name. Removing that character, everything works as expected.

**Comment by lacygoill** [comment]
Fixed by https://github.com/vim/vim/commit/aa3b15dbebf333282503d6031e2f9ba6ee4398ed
