### ISSUE TITLE
strptime() is reported as unknown function

### ISSUE THREAD

**Issue by lkintact** [vim/vim#6573]
**To Reproduce**
1. Run `gvim --cmd "language messages English" --clean`
2. Execute `:echo strptime("%Y %b %d %X", "1997 Apr 27 11:49:23")` (the first example at `:help strptime()`)
3. Gvim displays an `E117: Unknown function: strptime` error.

**Expected behavior**
`862156163` should be echoed.

**Environment**
 - Vim version 8.2.1313
 - OS: Windows 10 Home 1803
 - Terminal: GUI.

**Comment by k-takata** [comment]
It isn't implemented on Windows, because MSVC doesn't provide `strptime`.

**Comment by lkintact** [comment]
@k-takata I see, thank you.

**Comment by lkintact** [comment]
@k-takata I think since it solely depends on MSCV, the issue can be closed. Please reopen if you disagree.

**Comment by mattn** [comment]
Added in https://github.com/vim/vim/commit/036e40e6d80b1d71e57d3715ae20175ce09d7b78

**Comment by lkintact** [comment]
Thanks for letting know, @mattn!
