### ISSUE TITLE
`r`eplace mode cursor shape bug (Windows Terminal)

### ISSUE THREAD

**Issue by gustaphe** [vim/vim#6576]
**Describe the bug**
When `&t_SR` or `&t_SI` is set, insert and `R`eplace mode work as expected, but in `r`eplace, the cursor jumps visually five steps to the right (seems to correspond to the length of the string variable) while the operation is pending. After replacement the cursor returns correctly, but if the character was changed, the new character is visually followed by the string in `&t_EI` (without the `^[`), and the cursor does not change back from the underline mode. This can be reset by triggering a redraw (`^L`).

I can't tell what changes in how `r` sends ansi escape codes compared to `R`, but something causes the two codes to interfere.

**To Reproduce**
1. In Windows Terminal, run `vim --clean`
2. `:let &t_SR="\e[7 q"`, `:let &t_EI="\e[2 q"`
3. Write `abcdefg`
4. Place cursor on `a`
5. Press `r`, first bug: cursor moves to `f`
6. Press `b`, second bug: text becomes `b[2 qfg`, cursor is still the replace shape
7. Press `<C-L>`, text is `bbcdefg`

**Expected behavior**
The cursor should stay in the same place, the text should immediately become `bbcdefg` and the cursor should reset.

**Screenshots**
![image](https://user-images.githubusercontent.com/6677110/88922710-c4e91080-d270-11ea-9063-e46edbb6078c.png)
![image](https://user-images.githubusercontent.com/6677110/88922746-d6321d00-d270-11ea-878c-5466869efd62.png)
![image](https://user-images.githubusercontent.com/6677110/88922776-e3e7a280-d270-11ea-955b-65f92cba4c7c.png)

**Environment (please complete the following information):**
 - VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 12 2019 13:19:27)
 - OS: Windows 10, 18363
 - Terminal: Windows Terminal

**Comment by gustaphe** [comment]
Update, using 
`let &t_SR="\<CSI>7\ q"` and `let &t_EI="\<CSI>2\ q"` fixes the second bug, but the cursor still jumps (but to `e` now, I guess because `&t_SR` is one character shorter)

**Comment by rmford91** [comment]
@gustaphe Were you able to find a fix for the cursor jumping forward? I'm currently dealing with this same issue and haven't been able to find a solution

**Comment by gustaphe** [comment]
No. In the WT convo linked above I've updated the description a little (new and interesting bugs ...), and there's a comment describing using C to solve it. One day I'll look into that, but I keep forgetting to.

**Comment by k-takata** [comment]
(Implementation detail)

Win32 version of Vim uses its own terminal codes:
https://github.com/vim/vim/blob/ad6d9cc679259936b7c8453f17c0ec9d7ab7dcd0/src/term.c#L561-L570
and they are translated into actual escape sequences (or into Win32 console API calls):
https://github.com/vim/vim/blob/ad6d9cc679259936b7c8453f17c0ec9d7ab7dcd0/src/os_win32.c#L6454-L6462

Currently, this doesn't support `t_SR`, `t_SI` and so on. Maybe we need to pass through these kind of esc sequences.

BTW, I found that this function missing implementation for Windows Terminal:
https://github.com/vim/vim/blob/ad6d9cc679259936b7c8453f17c0ec9d7ab7dcd0/src/os_win32.c#L1523-L1528

**Comment by gustaphe** [comment]
Okay, now there's a plugin at gustaphe/winterm.vim

**Comment by k-takata** [comment]
I'm now preparing a patch for this issue:
https://osdn.net/users/k_takata/pf/vim-ktakata-mq/scm/blobs/312c07eac6ba0528dde08cbd240fc7ea10fe3e44/win32-set-cursor-style.patch

The following .vimrc works after applying this patch.
```vim
" Change cursor shape
if &term =~ 'xterm' || &term == 'win32'
  " Use DECSCUSR escape sequences
  let &t_SI = "\e[5 q"    " blink bar
  let &t_SR = "\e[3 q"    " blink underline
  let &t_EI = "\e[1 q"    " blink block
  let &t_ti .= "\e[1 q"   " blink block
  let &t_te .= "\e[0 q"   " default (normally blink block)
endif
```
