### ISSUE TITLE
E696 when whitespace separates a list or dictionary item from next comma in legacy script

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6577]
**Describe the bug**

`E696` is raised when whitespace separates a list or dictionary item from the next comma in a legacy script.

**To Reproduce**

Run this shell command:

    vim -Nu NONE +'let l = [1 , 2 , 3]'

`E696` is raised:

    E696: Missing comma in List: , 2, 3]

**Expected behavior**

No error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-1326
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(358)

**Additional context**

There seems to be a new requirement that when a list or dictionary item is followed by a comma, no whitespace can be written in-between.  But I think it should only apply to Vim9 scripts:
https://github.com/vim/vim/blob/9d489566815d7913afc5dfc2a772bacede3970fb/src/userfunc.c#L645-L646

As a result, this command no longer works:

    let l = [1 , 2 , 3]
              ^   ^
              ✘   ✘

---

It's a regression introduced in [8.2.1326](https://github.com/vim/vim/commit/9d489566815d7913afc5dfc2a772bacede3970fb).

**Comment by brammool** [comment]
The rule that expression evaluation does not consume following white space was not kept in some places, which can cause ":echo" with more than one argument to fail.  Fixing it may have side effects, like this one.  Please give a reproducible example for each case you find.
