### ISSUE TITLE
termguicolors not working

### ISSUE THREAD

**Issue by Opencode-foss** [vim/vim#6580]
**Describe the bug**
The termguicolors does not work and use the ctermfg/ctermbg colors instead of the guifg/guibg colors. 

**To Reproduce**
1). Run :set termguicolors

**Expected behavior**
When termguicolors is set I expect that vim will use the guifg/guibg colors instead of the ctermfg/ctermbg colors.

**Environment:**
 - Vim version: 8.2 +termguicolors
 - OS: Manjaro 
 - Terminal: Alacritty (supports true color)

**Comment by lacygoill** [comment]
Duplicate of https://github.com/vim/vim/issues/1740.

**Comment by Opencode-foss** [comment]
I tested it on a newer version and it worked.
