### ISSUE TITLE
Vim9: misleading error message when trying to redefine a script-local function

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6581]
**Describe the bug**

In Vim9 script, when we try to redefine a script-local function, a misleading error message is printed.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            echo 'first'
        enddef
        def Func()
            echo 'second'
        enddef
    EOF
    )

`E122` is raised:

    E122: Function <SNR>1_Func already exists, add ! to replace it

**Expected behavior**

Another error message is printed; one which explains that it's impossible to redefine a script-local function.

**Environment**

 - Vim version: 8.2 Included patches: 1-1328
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(358)

**Additional context**

The error is expected, and its cause is documented:
https://github.com/vim/vim/blob/4d4d1cd5c8b61ef0296bd6190ca2a0b2d6d96ba7/runtime/doc/vim9.txt#L514-L516

Still, the error message is misleading; it makes us think that we can redefine a script-local function simply by appending a bang after `:def`:

    E122: Function <SNR>1_Func already exists, add ! to replace it
                                               ^-----------------^

That's not true; appending a bang only works for global functions.  For script-local functions, the only effect of appending a bang is to change the error from `E122` to `E477`:
```vim
vim9script
def Func()
    echo 'first'
enddef
def! Func()
    echo 'second'
enddef
```
    E477: No ! allowed

It would be less misleading to directly tell the user that the function simply cannot be redefined:

    E1234: Function <SNR>1_Func already exists and cannot be redefined
    ^---^                                      ^---------------------^
    new code                                   new message

**Comment by brammool** [comment]
Patch 8.2.1349 already fixes this, but there was no test for this specific case.
