### ISSUE TITLE
Vim9: cannot define a global ":def" function inside another ":def" function

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6584]
**Describe the bug**

In Vim9 script, we cannot define a global `:def` function inside another `:def` function.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Outer()
            def g:Inner()
            enddef
        enddef
        defcompile
    EOF
    )

`E124` is raised:

    E124: Missing '(': :Inner()

**Expected behavior**

No error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-1328
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(356)

**Additional context**

According to `:h vim9-scopes` and `:h :def`, it's possible to nest `:def` inside another `:def`:
https://github.com/vim/vim/blob/40f4f7a48cae491f83bd3cdbf7e9b5a23ed870ef/runtime/doc/vim9.txt#L126-L127
https://github.com/vim/vim/blob/40f4f7a48cae491f83bd3cdbf7e9b5a23ed870ef/runtime/doc/vim9.txt#L492-L494

---

It's not a regression; the current behavior could already be observed in [8.2.0696](https://github.com/vim/vim/releases/tag/v8.2.0696), when the implementation of nested functions was finished.

---

Relevant todo items:

https://github.com/vim/vim/blob/4d4d1cd5c8b61ef0296bd6190ca2a0b2d6d96ba7/runtime/doc/todo.txt#L68-L70
https://github.com/vim/vim/blob/4d4d1cd5c8b61ef0296bd6190ca2a0b2d6d96ba7/runtime/doc/todo.txt#L124-L125

**Comment by lacygoill** [comment]
The issue is specific to a `:def` inside a `:def`.

There is no issue for a `:def` inside a `:fu`:
```vim
vim9script
fu Outer()
    def g:Inner()
        echo 'inner'
    enddef
endfu
Outer()
Inner()
```
    inner

Nor for a `:fu` inside a `:fu`:
```vim
vim9script
fu Outer()
    fu g:Inner()
        echo 'inner'
    endfu
endfu
Outer()
Inner()
```
    inner

**Comment by brammool** [comment]
You do need to call g:Inner(), just calling Inner() calls the script-local function.
The very first example fails before the call though.

**Comment by lacygoill** [comment]
> You do need to call g:Inner(), just calling Inner() calls the script-local function.

I was going to answer that since there is no script-local `Inner()`, Vim had to look further in a set of scopes (block → function → script → import → global),  as documented at `:h vim9-scopes`.

But now that I re-read `:h vim9-scopes`, the global scope is not mentioned.  In any case, it works:  Vim does call the global function, even without `g:`.  Not sure whether it's working as intended.  In any case, I agree; in a real script, I would use `g:` to be sure Vim looks for `Inner()` in the global namespace.

> The very first example fails before the call though.

Sorry, I don't understand.

The very first example in the OP doesn't call a function, but indeed it fails.
The other examples do call functions, but they don't fail (at least they don't raise errors).

**Comment by lacygoill** [comment]
> But now that I re-read `:h vim9-scopes`, the global scope is not mentioned.

To be more accurate: it is mentioned, but not in the paragraph which explains how Vim processes a function name which is not prefixed by `s:` nor `g:`:

https://github.com/vim/vim/blob/4d4d1cd5c8b61ef0296bd6190ca2a0b2d6d96ba7/runtime/doc/vim9.txt#L134-L138

**Comment by brammool** [comment]
> > You do need to call g:Inner(), just calling Inner() calls the
> > script-local function.
> 
> I was going to answer that since there is no script-local `Inner()`,
> Vim had to look further in a set of scopes (block → function → script
> → import → global),  as documented at `:h vim9-scopes`.
> 
> But now that I re-read `:h vim9-scopes`, the global scope is not
> mentioned.  In any case, it works:  Vim does call the global function,
> even without `g:`.  Not sure whether it's working as intended.  In any
> case, I agree; in a real script, I would use `g:` to be sure Vim looks
> for `Inner()` in the global namespace.

At first I thought it would be good to require using g: for a global
function.  But the tests already omit it, it looks natural to find a
global function without using g:.  I'll add a test for when both exist.


-- 
hundred-and-one symptoms of being an internet addict:
99. The hum of a cooling fan and the click of keys is comforting to you.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
