### ISSUE TITLE
Vim9: imported function has priority over function-local function when both have same name

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6585]
**Describe the bug**

An imported function has priority over a function which is local to a function, when both have the same name; this contradicts the help at `:h vim9-scopes`.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        mkdir('/tmp/import', 'p')
        let lines =<< trim END
            vim9script
            export def Func()
                echo 'imported'
            enddef
        END
        writefile(lines, '/tmp/import/foo.vim')
        set rtp+=/tmp
        import Func from 'foo.vim'
        def Outer()
            def Func()
                echo 'local to function'
            enddef
            Func()
        enddef
        Outer()
    EOF
    )

`imported` is echo'ed.

**Expected behavior**

`local to function` is echo'ed.

**Environment**

 - Vim version: 8.2 Included patches: 1-1328
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(358)

**Additional context**

According to `:h vim9-scopes`, Vim should look for `Func()` in the current scope before looking in the imported functions:
https://github.com/vim/vim/blob/4d4d1cd5c8b61ef0296bd6190ca2a0b2d6d96ba7/runtime/doc/vim9.txt#L134-L138

When `Func()` is invoked, the current scope is the one of the outer function `Outer()`.
In the latter, another `Func()` is defined; I would expect Vim to use it.

---

The issue is specific to a function nested in a `:def` function.
There is no issue if the function is nested in a `:fu` function, regardless of its own type (Vim9 vs legacy):
```vim
vim9script
mkdir('/tmp/import', 'p')
let lines =<< trim END
    vim9script
    export def Func()
        echo 'imported'
    enddef
END
writefile(lines, '/tmp/import/foo.vim')
set rtp+=/tmp
import Func from 'foo.vim'
fu Outer()
    def Func()
        echo 'local to function'
    enddef
    call Func()
endfu
Outer()
```
    local to function
    ✔
```vim
vim9script
mkdir('/tmp/import', 'p')
let lines =<< trim END
    vim9script
    export def Func()
        echo 'imported'
    enddef
END
writefile(lines, '/tmp/import/foo.vim')
set rtp+=/tmp
import Func from 'foo.vim'
fu Outer()
    fu Func()
        echo 'local to function'
    endfu
    call Func()
endfu
Outer()
```
    local to function
    ✔

---

The issue also applies when the local function is local to a block:
```vim
vim9script
mkdir('/tmp/import', 'p')
let lines =<< trim END
    vim9script
    export def Func()
        echo 'imported'
    enddef
END
writefile(lines, '/tmp/import/foo.vim')
set rtp+=/tmp
import Func from 'foo.vim'
def Outer()
    if 1
        def Func()
            echo 'local to block'
        enddef
    endif
    Func()
enddef
Outer()
```
    imported
    ✘

With the same exceptions as for functions local to a function; i.e. there is no issue if the block is written in a legacy function:
```vim
vim9script
mkdir('/tmp/import', 'p')
let lines =<< trim END
    vim9script
    export def Func()
        echo 'imported'
    enddef
END
writefile(lines, '/tmp/import/foo.vim')
set rtp+=/tmp
import Func from 'foo.vim'
fu Outer()
    if 1
        fu Func()
            echo 'local to block'
        endfu
    endif
    call Func()
endfu
Outer()
```
    local to block
    ✔
```vim
vim9script
mkdir('/tmp/import', 'p')
let lines =<< trim END
    vim9script
    export def Func()
        echo 'imported'
    enddef
END
writefile(lines, '/tmp/import/foo.vim')
set rtp+=/tmp
import Func from 'foo.vim'
fu Outer()
    if 1
        def Func()
            echo 'local to block'
        enddef
    endif
    call Func()
endfu
Outer()
```
    local to block
    ✔

**Comment by brammool** [comment]
We should not allow for having an import and a local function (or variable) having the same name.
The example should result in an error.
There is no real need to use the same name twice.

**Comment by lacygoill** [comment]
> There is no real need to use the same name twice.

I don't disagree, but the fact that the help says that Vim looks into a set of namespaces in a certain *order* made me think that it was possible to have 2 functions with the same name in 2 different namespaces:
https://github.com/vim/vim/blob/e4218b9416bdcd78b9779a06258198573a0c369e/runtime/doc/vim9.txt#L134-L138

Just like in legacy Vim script, we can have a global `Func()`, and a script-local `s:Func()`.

If a function name can only be used in one namespace, then there is no need to follow any particular order. Just raise an error if the function can not be found in any namespace, or can be found in several namespaces; otherwise, just invoke the function from whatever unique namespace it was found.

**Comment by lacygoill** [comment]
That's why I tested whether the order mentioned in the help was really respected in practice:

    block-local > function-local > script-local > imported

And it seems that `script-local > imported` is really respected, but not `function-local > script-local` nor `function-local > imported`.

---

To be clear, I don't mind if it's disallowed to re-use the same name in different namespaces; I'll just try to re-read the help and better understand it.

**Comment by brammool** [comment]
Both are possible: allow overriding names and use the one that is closest, or disallow overriding names (shadowing).
There is an advantage in each of them.
Since we are making new rules, it's probably best to be strict at first, and perhaps allow some shadowing later.
There were some checks already, but probably some missing as well.
