### ISSUE TITLE
string arguments to custom Vim commands no longer highlighted

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6587]
**Describe the bug**

In a Vim file, strings (and lists, dictionaries, ...) passed as arguments to custom commands are no longer highlighted.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        call setline(1, "Plug 'tpope/vim-fugitive'")
        syn on
        set ft=vim
    EOF
    )

`'tpope/vim-fugitive'` is not highlighted.

**Expected behavior**

`'tpope/vim-fugitive'` is highlighted as a string.

**Environment**

 - Vim version: 8.2 Included patches: 1-1328
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(358)

**Additional context**

Before the commit 2547aa930b59f5e2bcb70e81d5a57ed461e59b4f, the string was correctly highlighted.  The latter has introduced this line which is responsible for the change:
https://github.com/vim/vim/blob/4d4d1cd5c8b61ef0296bd6190ca2a0b2d6d96ba7/runtime/syntax/vim.vim#L458

---

Not sure whether it can be considered as a bug, but it would be nice if string/list/dictionary arguments to custom commands could be still highlighted like before.

Here is a patch which I think can restore the highlighting:
```diff
diff --git a/runtime/syntax/vim.vim b/runtime/syntax/vim.vim
index 9b20392fa..b4d331ecf 100644
--- a/runtime/syntax/vim.vim
+++ b/runtime/syntax/vim.vim
@@ -455,7 +455,7 @@ syn match vimFunc		"\%(\%([sSgGbBwWtTlL]:\|<[sS][iI][dD]>\)\=\%(\w\+\.\)*\I[a-zA
 syn match vimUserFunc contained	"\%(\%([sSgGbBwWtTlL]:\|<[sS][iI][dD]>\)\=\%(\w\+\.\)*\I[a-zA-Z0-9_.]*\)\|\<\u[a-zA-Z0-9.]*\>\|\<if\>"	contains=vimNotation
 
 " User Command Highlighting: {{{2
-syn match vimUsrCmd	'^\s*\zs\u\w*.*$'
+syn match vimUsrCmd	'^\s*\zs\u\w*'
 
 " Errors And Warnings: {{{2
 " ====================
```
---

/cc @cecamp

**Comment by lacygoill** [comment]
Actually, even with the previous suggested patch, there is still an issue.  In Vim9 script, we can invoke a custom function without `:call`:
```vim
vim9script
Func()
```
With the current regex, and with the regex in the patch, `Func()` would be wrongly highlighted with `vimUsrCmd`; a better regex would be:

    ^\s*\zs\u\%(\w*\)\@>(\@!

Here is a new patch which should fix both issues:
```diff
diff --git a/runtime/syntax/vim.vim b/runtime/syntax/vim.vim
index 9b20392fa..141c614ee 100644
--- a/runtime/syntax/vim.vim
+++ b/runtime/syntax/vim.vim
@@ -455,7 +455,7 @@ syn match vimFunc		"\%(\%([sSgGbBwWtTlL]:\|<[sS][iI][dD]>\)\=\%(\w\+\.\)*\I[a-zA
 syn match vimUserFunc contained	"\%(\%([sSgGbBwWtTlL]:\|<[sS][iI][dD]>\)\=\%(\w\+\.\)*\I[a-zA-Z0-9_.]*\)\|\<\u[a-zA-Z0-9.]*\>\|\<if\>"	contains=vimNotation
 
 " User Command Highlighting: {{{2
-syn match vimUsrCmd	'^\s*\zs\u\w*.*$'
+syn match vimUsrCmd	'^\s*\zs\u\%(\w*\)\@>(\@!'
 
 " Errors And Warnings: {{{2
 " ====================
```

**Comment by casey** [comment]
In case anyone is looking for a workaround for this, you can put the following autocommand group in your vimrc to add the above rule:

```vim
augroup vimrc
  autocmd!
  " fix vim script user command syntax highlighting
  " (should be unnecessary when https://github.com/vim/vim/issues/6587 is fixed)
  autocmd Syntax vim syn match vimUsrCmd '^\s*\zs\u\%(\w*\)\@>(\@!'
augroup end
```

**Comment by lacygoill** [comment]
In the meantime, I found 2 other issues:
```vim
vim9script
var MYCONSTANT: number
MYCONSTANT = 123
```
Here, the last `MYCONSTANT` is wrongly highlighted with `vimUsrCmd`.
```vim
vim9script
AutoloadScript#somefunc()
```
And here, `AutoloadScript` is – again – wrongly highlighted with `vimUsrCmd`.

---

Here is a new patch which fixes all these issues:
```diff
diff --git a/runtime/syntax/vim.vim b/runtime/syntax/vim.vim
index 675c79503..dfc94b2b3 100644
--- a/runtime/syntax/vim.vim
+++ b/runtime/syntax/vim.vim
@@ -458,7 +458,7 @@ syn match vimFunc		"\%(\%([sSgGbBwWtTlL]:\|<[sS][iI][dD]>\)\=\%(\w\+\.\)*\I[a-zA
 syn match vimUserFunc contained	"\%(\%([sSgGbBwWtTlL]:\|<[sS][iI][dD]>\)\=\%(\w\+\.\)*\I[a-zA-Z0-9_.]*\)\|\<\u[a-zA-Z0-9.]*\>\|\<if\>"	contains=vimNotation
 
 " User Command Highlighting: {{{2
-syn match vimUsrCmd	'^\s*\zs\u\w*.*$'
+syn match vimUsrCmd	'^\s*\zs\u\%(\w*\)\@>\%([(#]\|\s\+=\)\@!'
 
 " Errors And Warnings: {{{2
 " ====================
```

**Comment by lacygoill** [comment]
I found yet 2 other issues:
```vim
vim9script
var NAME: number
NAME += 123
```
Here, the last `NAME` is wrongly highlighted with `vimUsrCmd`.
```vim
vim9script
var NAME: list<number>
NAME[0] = 0
```
Again, the last `NAME` is wrongly highlighted with `vimUsrCmd`.

New patch which fixes all the issues:
```diff
diff --git a/runtime/syntax/vim.vim b/runtime/syntax/vim.vim
index d900c5e78..4804da5a2 100644
--- a/runtime/syntax/vim.vim
+++ b/runtime/syntax/vim.vim
@@ -462,7 +462,7 @@ syn match vimFunc		"\%(\%([sSgGbBwWtTlL]:\|<[sS][iI][dD]>\)\=\%(\w\+\.\)*\I[a-zA
 syn match vimUserFunc contained	"\%(\%([sSgGbBwWtTlL]:\|<[sS][iI][dD]>\)\=\%(\w\+\.\)*\I[a-zA-Z0-9_.]*\)\|\<\u[a-zA-Z0-9.]*\>\|\<if\>"	contains=vimNotation
 
 " User Command Highlighting: {{{2
-syn match vimUsrCmd	'^\s*\zs\u\w*.*$'
+syn match vimUsrCmd	'^\s*\zs\u\%(\w*\)\@>\%([(#[]\|\s\+\%([-+*/%]\=\|\.\.\)=\)\@!'
 
 " Errors And Warnings: {{{2
 " ====================
```

**Comment by brammool** [comment]
@cecamp

**Comment by lacygoill** [comment]
Fixed by https://github.com/vim/vim/commit/d2ea7cf10a4d026ebd402594d656af7d5c811c24
