### ISSUE TITLE
[Windows] Enable remote development on WSL

### ISSUE THREAD

**Issue by luisiacc** [vim/vim#6588]
I think the title explains itself, What I propose is that from Windows OS could be able to connect to a remote WSL installation such as Ubuntu 18.04, so we don't need to have 2 vim installations(one in Windows and another in WSL, since in WSL vim is not as fast as in windows, at least for gVim), its quite a pain to have to check both vimrcs every time one of them gets updated, I really like vim I hope this could be done some day. Keep on the good work !

**Comment by k-takata** [comment]
You can access the files in WSL in the form of `\\wsl$\distribution\path`.

**Comment by luisiacc** [comment]
> You can access the files in WSL in the form of `\\wsl$\distribution\path`.

I ment a way so we could  also use the WSL environment variables like using Python envs installed on WSL only. Thanks por the quick reply do, it is appreciated.

**Comment by PhyX-Meow** [comment]
I use a single vimrc.vim in my windows file system, and source it in both vimrc.
For system specific settings I use `if has('win32')` to work around.
May be this can help you.

**Comment by chrisbra** [comment]
is this actually vim related or not more like a platform issue?

**Comment by k-takata** [comment]
I still don't understand what the actual request is. However, I think that the support for WSL might be implemented as a plugin. I close this for now.
@luisiacc If you still think that special support for WSL is needed in Vim itself, please explain what is actually needed.

**Comment by luisiacc** [comment]
> I still don't understand what the actual request is. However, I think that the support for WSL might be implemented as a plugin. I close this for now.
> @luisiacc If you still think that special support for WSL is needed in Vim itself, please explain what is actually needed.

If you think it could be implemented in a plugin then great !, What is needed is like the VSCode extension for WSL that would allow vim to access to all env variables on WSL, lets put an example, I have a project in WSL which runs a python virtual environment installed within WSL, from vim in windows I am unable to connect to this virtual environment, is this clear now ?, maybe I am not explaining myself correctly.
