### ISSUE TITLE
vim9script: It is not always possible to use an empty key for a dictionary

### ISSUE THREAD

**Issue by bfrg** [vim/vim#6591]
**Describe the bug**
It is not always possible to use an empty key for a dictionary.

**To Reproduce**
1. Run `vim --clean -S test.vim`, with
   ```vim
   vim9script
   def Test(): dict<number>
       let test: dict<number> = {'': 1}
       test[''] = 1000
       return test
   enddef
   Test()
   ```
2. Result:
   ```
   E713: Cannot use empty key for Dictionary
   ```

The following works though:
```vim
def Test(): dict<number>
    let test: dict<number> = {'': 1}
    extend(test, {'': 1000})
    return test
enddef
```

**Expected behavior**
No errors.

**Environment**
Vim version `8.2.1333`

**Comment by bfrg** [comment]
There's a `todo` item:
https://github.com/vim/vim/blob/af8edbb8dc551aaf2105a4d77b3d8495da239ef0/runtime/doc/todo.txt#L76-L78

Assigning a value to a non-empty dict item works:
```vim
def Test(): dict<number>
    let test: dict<number> = {}
    test['a'] = 100
    return test
enddef
```

**Comment by lacygoill** [comment]
> Assigning a value to a non-empty dict item works:

But not if the dictionary is in a namespace outside the function:
```vim
vim9script
def Test(): dict<number>
    let test: dict<number> = {}
    test['a'] = 100
    return test
enddef
echo Test()
```
    {'a': 100}
    ✔
```vim
vim9script
let s:test: dict<any> = {}
def Test(): dict<any>
    s:test['a'] = 100
    return s:test
enddef
echo Test()
```
    E1088: cannot use an index on s:test
    ✘
```vim
vim9script
g:test = {}
def Test(): dict<any>
    g:test['a'] = 100
    return g:test
enddef
echo Test()
```
    E1088: cannot use an index on g:test
    ✘
```vim
vim9script
b:test = {}
def Test(): dict<any>
    b:test['a'] = 100
    return b:test
enddef
echo Test()
```
    E1088: cannot use an index on b:test
    ✘

...

I don't know whether this is a temporary error which will be removed once a future patch implements the `s:dict['key']` feature, or if it's a definitive error and working as intended.  In any case, the error is not documented.

---

And if we use the `.` notation to access a dictionary member, another undocumented error is raised:
```vim
vim9script
def Test(): dict<number>
    let test: dict<number> = {}
    test.a = 100
    return test
enddef
echo Test()
```
    Not supported yet: test.a = 100
