### ISSUE TITLE
Vim9: misleading error message when declaring a global variable with a type

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6594]
**Describe the bug**

In Vim9 script, declaring a global variable with a type raises a misleading error message.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        let g:var: list<number> = []
    EOF
    )

`E1013` is raised:

    E1013: type mismatch, expected list<number> but got list<any>

**Expected behavior**

`E1016` is raised:

    E1016: Cannot declare a global variable: g:var

**Environment**

 - Vim version: 8.2 Included patches: 1-1335
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(358)

**Additional context**

The current error message makes us think that we can declare a global variable, and that the only issue is the type.  That's not true; the issue is that it is not allowed to declare a global variable:
https://github.com/vim/vim/blob/4e1d8bd79b87b120bd40afe0eba54a419f8c3aee/runtime/doc/vim9.txt#L192-L194

---

If the type is removed, `E1016` is correctly raised:
```vim
vim9script
let g:var = []
```
    E1016: Cannot declare a global variable: g:var

---

Raising `E1013` when declaring a global variable with a type, and `E1016` when declaring a global variable without a type is inconsistent, and doesn't make much sense because – again – specifying a type or not is irrelevant to the main issue.

**Comment by brammool** [comment]
This was fixed by one of the recent patches.
