### ISSUE TITLE
gtk3vim: no horiz. cursor movement visible after let &gcr and set ruler

### ISSUE THREAD

**Issue by luchr** [vim/vim#660]
Hello,

the GTK3-support (since 7.4.1402) is really really cool. Thank you a lot.

I found one (crazy and subtle) bug (in my compiled 7.4.1411 version):
1. Start gtk3vim with `gtk3vim -u NONE -U NONE -i NONE`
2. Enter some text (in insert-mode of course)
3. Leave insert-mode and enter `:let &gcr = &gcr.",a:blinkon0"`
4. Enter `:set ru`
5. Move the cursor horizontally (e.g. with the `h` key)

Expected behaviour: see block-cursor movement and position-update in ruler 
Seen behaviour: block-cursor is not moved, but (internal) cursor-position is changed (can be seen in the position in the ruler)

I can reproduce this bug only with the ruler-option and only if I change the option `gcr` with `let`. The bug didn't show up, if I use the `set`-command to change the option `gcr`.

**Comment by nuko8** [comment]
Thank you for reporting.

A [patch](https://github.com/vim/vim/releases/tag/v7.4.1497) for fixing the issue was included in the upstream master a few hours ago.

Hopefully, this works for you.

Regards,
Kazunobu Kuriyama

**Comment by luchr** [comment]
Thank you very much, Kazunobu Kuriyama. Patch 1497 fixed the issue for me.

Bye
C. Ludwig
