### ISSUE TITLE
Let variables equal hex colors

### ISSUE THREAD

**Issue by Opencode-foss** [vim/vim#6605]
I would like it to be possible to let a variable to be equal to a hex color. I would like it to make it possible to do the following:

let s:foo = #FC120C

hi Comment guifg = s:foo

**Comment by lacygoill** [comment]
Try this:

    let s:foo = '#FC120C'
    execute 'highlight Comment guifg=' .. s:foo

See [`:h :execute`](https://vimhelp.org/eval.txt.html#:exe).

**Comment by chrisbra** [comment]
closing
