### ISSUE TITLE
set{qf,loc}list functions silently ignore invalid “action” argument

### ISSUE THREAD

**Issue by ZyX-I** [vim/vim#661]
Currently if you write something like `setqflist([], [])` Vim will act as if you wrote `setqflist([])`. Fix is as simple as

``` Patch
diff --git a/runtime/doc/eval.txt b/runtime/doc/eval.txt
index 022a5da..56fa6be 100644
--- a/runtime/doc/eval.txt
+++ b/runtime/doc/eval.txt
@@ -6049,11 +6049,12 @@ setqflist({list} [, {action}])              *setqflist()*
        |getqflist()| returns.

        If {action} is set to 'a', then the items from {list} are
-       added to the existing quickfix list. If there is no existing
-       list, then a new list is created. If {action} is set to 'r',
+       added to the existing quickfix list.  If there is no existing
+       list, then a new list is created.  If {action} is set to 'r',
        then the items from the current quickfix list are replaced
-       with the items from {list}. If {action} is not present or is
-       set to ' ', then a new list is created.
+       with the items from {list}.  If {action} is not present or is
+       set to ' ', then a new list is created.  All other strings
+       are reserved and currently ignored.

        Returns zero for success, -1 for failure.

diff --git a/src/eval.c b/src/eval.c
index cc30308..32091f0 100644
--- a/src/eval.c
+++ b/src/eval.c
@@ -18241,7 +18241,7 @@ set_qf_ll_list(
     {
    list_T  *l = list_arg->vval.v_list;

-   if (action_arg->v_type == VAR_STRING)
+   if (action_arg->v_type != VAR_UNKNOWN)
    {
        act = get_tv_string_chk(action_arg);
        if (act == NULL)
```

**Comment by mattn** [comment]
So then, should be an error?

``` diff
diff --git a/src/eval.c b/src/eval.c
index db9c6b7..3740e70 100644
--- a/src/eval.c
+++ b/src/eval.c
@@ -18274,13 +18274,18 @@ set_qf_ll_list(
     {
    list_T  *l = list_arg->vval.v_list;

-   if (action_arg->v_type == VAR_STRING)
+   if (action_arg->v_type == VAR_UNKNOWN)
    {
        act = get_tv_string_chk(action_arg);
        if (act == NULL)
        return;     /* type error; errmsg already given */
        if (*act == 'a' || *act == 'r')
        action = *act;
+       else
+       {
+       EMSG(_(e_invarg));
+       return;
+       }
    }

    if (l != NULL && set_errorlist(wp, l, action,
```

**Comment by ZyX-I** [comment]
@mattn 
1. `!= VAR_UNKNOWN`, not `== VAR_UNKNOWN`.
2. You forgot that `*act == ' '` is also valid.
3. If one wants to filter out all incorrect strings this would be `if ((act[0] == 'a' || act[0] == 'r' || act[0] == ' ') && act[1] == NUL)`: length of the string should be one.
4. I am not really sure that nobody uses `0` or `""` in place of the action argument, these variants are pretty commonly used to mean absense of arguments. But floats, funcrefs  and containers are very unlikely here and their presence indicates an error almost for sure.
5. I hate almost useless `e_invarg` messages. If error message is given it should describe what is the error. Check differences between neovim/neovim#4131 (specifically search for `exc_exec` starting from https://github.com/ZyX-I/neovim/blob/35c4b0454b2ef5fabc4c8af96894b559a63f07f6/test/functional/eval/json_functions_spec.lua#L86) and current Vim implementation and say what you like more, especially in big JSON strings. This problem is very common in Vim code.

**Comment by mattn** [comment]
I just give you an example. (but mistaken) So please fix your patch.

**Comment by vim-ml** [comment]
Hi,

I think Nikolai's patch is simple and better.  Looks good for me.
This is perfect when adding a test :-)

mattn>
Detailed error will be output in get_tv_string_buf_chk().

## Thanks.

Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by vim-ml** [comment]
On Thursday, February 25, 2016 at 9:07:46 PM UTC+9, h_east wrote:

> Hi,
> 
> I think Nikolai's patch is simple and better.  Looks good for me.
> This is perfect when adding a test :-)
> 
> mattn>
> Detailed error will be output in get_tv_string_buf_chk().

No. When the option is passed neither a nor r, it should be error, I think.
- mattn

**Comment by vim-ml** [comment]
Hi mattn!

2016-2-25(Thu) 21:50:37 UTC+9 mattn:

> On Thursday, February 25, 2016 at 9:07:46 PM UTC+9, h_east wrote:
> 
> > Hi,
> > 
> > I think Nikolai's patch is simple and better.  Looks good for me.
> > This is perfect when adding a test :-)
> > 
> > mattn>
> > Detailed error will be output in get_tv_string_buf_chk().
> 
> No. When the option is passed neither a nor r, it should be error, I think.

I see.
Is attached patch OK?

## 

Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by vim-ml** [comment]
2016-02-25 16:30 GMT+03:00 h_east h.east.727@gmail.com:

> Hi mattn!
> 
> 2016-2-25(Thu) 21:50:37 UTC+9 mattn:
> 
> > On Thursday, February 25, 2016 at 9:07:46 PM UTC+9, h_east wrote:
> > 
> > > Hi,
> > > 
> > > I think Nikolai's patch is simple and better.  Looks good for me.
> > > This is perfect when adding a test :-)
> > > 
> > > mattn>
> > > Detailed error will be output in get_tv_string_buf_chk().
> > 
> > No. When the option is passed neither a nor r, it should be error, I think.
> 
> I see.
> Is attached patch OK?

As I said earlier if you want to filter out all incorrect strings this
should also have `&& act[1] == NUL` condition. Also consider the case
when user used `setqflist([], '')`, it will display “E475: Invalid
argument: ”. Now guess what argument it meant, this error message
looks more like a bug then like a reference to `''`.

> ## 
> 
> Best regards,
> Hirohito Higashi (a.k.a. h_east)
> 
> ## 
> 
> ## 
> 
> You received this message from the "vim_dev" maillist.
> Do not top-post! Type your reply below the text you are replying to.
> For more information, visit http://www.vim.org/maillist.php
> 
> ---
> 
> You received this message because you are subscribed to the Google Groups "vim_dev" group.
> To unsubscribe from this group and stop receiving emails from it, send an email to vim_dev+unsubscribe@googlegroups.com.
> For more options, visit https://groups.google.com/d/optout.

**Comment by vim-ml** [comment]
Hi Nikolai,

2016-2-25(Thu) 22:58:19 UTC+9 ZyX:

> 2016-02-25 16:30 GMT+03:00 h_east:
> 
> > Hi mattn!
> > 
> > 2016-2-25(Thu) 21:50:37 UTC+9 mattn:
> > 
> > > On Thursday, February 25, 2016 at 9:07:46 PM UTC+9, h_east wrote:
> > > 
> > > > Hi,
> > > > 
> > > > I think Nikolai's patch is simple and better.  Looks good for me.
> > > > This is perfect when adding a test :-)
> > > > 
> > > > mattn>
> > > > Detailed error will be output in get_tv_string_buf_chk().
> > > 
> > > No. When the option is passed neither a nor r, it should be error, I think.
> > 
> > I see.
> > Is attached patch OK?
> 
> As I said earlier if you want to filter out all incorrect strings this
> should also have `&& act[1] == NUL` condition. Also consider the case
> when user used `setqflist([], '')`, it will display “E475: Invalid
> argument: ”. Now guess what argument it meant, this error message
> looks more like a bug then like a reference to `''`.

It will be able to grasp when you see help.
Vim's document is very good.

## Thanks.

Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by vim-ml** [comment]
2016-02-25 17:21 GMT+03:00 h_east h.east.727@gmail.com:

> Hi Nikolai,
> 
> 2016-2-25(Thu) 22:58:19 UTC+9 ZyX:
> 
> > 2016-02-25 16:30 GMT+03:00 h_east:
> > 
> > > Hi mattn!
> > > 
> > > 2016-2-25(Thu) 21:50:37 UTC+9 mattn:
> > > 
> > > > On Thursday, February 25, 2016 at 9:07:46 PM UTC+9, h_east wrote:
> > > > 
> > > > > Hi,
> > > > > 
> > > > > I think Nikolai's patch is simple and better.  Looks good for me.
> > > > > This is perfect when adding a test :-)
> > > > > 
> > > > > mattn>
> > > > > Detailed error will be output in get_tv_string_buf_chk().
> > > > 
> > > > No. When the option is passed neither a nor r, it should be error, I think.
> > > 
> > > I see.
> > > Is attached patch OK?
> > 
> > As I said earlier if you want to filter out all incorrect strings this
> > should also have `&& act[1] == NUL` condition. Also consider the case
> > when user used `setqflist([], '')`, it will display “E475: Invalid
> > argument: ”. Now guess what argument it meant, this error message
> > looks more like a bug then like a reference to `''`.
> 
> It will be able to grasp when you see help.
> Vim's document is very good.

What I will be able to grasp? Consider setloclist(0, [], ''): to see
the problem in help file without any pointers from the error message I
need
1. :h setloclist()
2. Verify that `0` is indeed a valid window number in this context.
   This is in second paragraph.
3. <C-]> on setqflist() because setloclist() documentation does not
   contain anything useful.
4. Verify that [] is indeed a valid argument. This is two paragraphs,
   a table, and another four paragraphs below. Super: see how many time
   you have wasted for this.
5. Another two paragraphs below there is actually a paragraph about
   {action}. It lists three possible values, but they are scattered over
   the paragraph in place of being arranged into a table, so to get a
   list of possible values in mind you need to read the whole paragraph.
   Double super. And nobody said explicitly that these are the only
   accepted values, even though this is logical?.. no, in the current
   state of your patch `'at'` is also accepted, but is not in a list.

Now please write what you will do if you see “Exxx: Invalid action
argument: ” after doing `setloclist(0, [], '')`, pretending that you
do not know what is the problem.

Of course, you probably will not write `setloclist(0, [], '')`, but
you will `setloclist(winnr, constructed_list, action)` (`action` has
high chances of being a string literal though). This makes debugging
with e_invarg2 even more interesting, especially if you had an opinion
that `''` is a valid action (e.g. because it worked in your previous
Vim version) and thus will check other arguments first.

Clear message “Invalid _action_ argument” points right to the argument
which contains error, unclear “Invalid argument” requires checking all
arguments to `set*list()` functions.

> ## Thanks.
> 
> Best regards,
> Hirohito Higashi (a.k.a. h_east)
> 
> ## 
> 
> ## 
> 
> You received this message from the "vim_dev" maillist.
> Do not top-post! Type your reply below the text you are replying to.
> For more information, visit http://www.vim.org/maillist.php
> 
> ---
> 
> You received this message because you are subscribed to the Google Groups "vim_dev" group.
> To unsubscribe from this group and stop receiving emails from it, send an email to vim_dev+unsubscribe@googlegroups.com.
> For more options, visit https://groups.google.com/d/optout.

**Comment by vim-ml** [comment]
2016-02-25 18:46 GMT+03:00 Nikolay Aleksandrovich Pavlov zyx.vim@gmail.com:

> 2016-02-25 17:21 GMT+03:00 h_east h.east.727@gmail.com:
> 
> > Hi Nikolai,
> > 
> > 2016-2-25(Thu) 22:58:19 UTC+9 ZyX:
> > 
> > > 2016-02-25 16:30 GMT+03:00 h_east:
> > > 
> > > > Hi mattn!
> > > > 
> > > > 2016-2-25(Thu) 21:50:37 UTC+9 mattn:
> > > > 
> > > > > On Thursday, February 25, 2016 at 9:07:46 PM UTC+9, h_east wrote:
> > > > > 
> > > > > > Hi,
> > > > > > 
> > > > > > I think Nikolai's patch is simple and better.  Looks good for me.
> > > > > > This is perfect when adding a test :-)
> > > > > > 
> > > > > > mattn>
> > > > > > Detailed error will be output in get_tv_string_buf_chk().
> > > > > 
> > > > > No. When the option is passed neither a nor r, it should be error, I think.
> > > > 
> > > > I see.
> > > > Is attached patch OK?
> > > 
> > > As I said earlier if you want to filter out all incorrect strings this
> > > should also have `&& act[1] == NUL` condition. Also consider the case
> > > when user used `setqflist([], '')`, it will display “E475: Invalid
> > > argument: ”. Now guess what argument it meant, this error message
> > > looks more like a bug then like a reference to `''`.
> > 
> > It will be able to grasp when you see help.
> > Vim's document is very good.
> 
> What I will be able to grasp? Consider setloclist(0, [], ''): to see
> the problem in help file without any pointers from the error message I
> need
> 1. :h setloclist()
> 2. Verify that `0` is indeed a valid window number in this context.
>    This is in second paragraph.
> 3. <C-]> on setqflist() because setloclist() documentation does not
>    contain anything useful.
> 4. Verify that [] is indeed a valid argument. This is two paragraphs,
>    a table, and another four paragraphs below. Super: see how many time
>    you have wasted for this.
> 5. Another two paragraphs below there is actually a paragraph about
>    {action}. It lists three possible values, but they are scattered over
>    the paragraph in place of being arranged into a table, so to get a
>    list of possible values in mind you need to read the whole paragraph.
>    Double super. And nobody said explicitly that these are the only
>    accepted values, even though this is logical?.. no, in the current
>    state of your patch `'at'` is also accepted, but is not in a list.
> 
> Now please write what you will do if you see “Exxx: Invalid action
> argument: ” after doing `setloclist(0, [], '')`, pretending that you
> do not know what is the problem.
> 
> Of course, you probably will not write `setloclist(0, [], '')`, but
> you will `setloclist(winnr, constructed_list, action)` (`action` has
> high chances of being a string literal though). This makes debugging
> with e_invarg2 even more interesting, especially if you had an opinion
> that `''` is a valid action (e.g. because it worked in your previous
> Vim version) and thus will check other arguments first.
> 
> Clear message “Invalid _action_ argument” points right to the argument
> which contains error, unclear “Invalid argument” requires checking all
> arguments to `set*list()` functions.

Does not matter how good the help is, it can never replace the proper
error message. Help can teach what tutorials can’t. Help contains a
reference. Help may be the final argument. But using help to determine
_where_ is the problem is a just a huge waste of time when you have a
Vim which knows where is the problem exactly and for sure, just you
need to make it tell you.

And add point `0.` above: “I know that `:h E475` is an absolutely
useless piece of shit (it even talks about invalid arguments to _Ex
commands_ while here it means invalid argument to a _function_), so am
not checking `:h E475`; and I also know that `:call` will not give
this error for my code, so am not checking `:h :call`.” Otherwise
there are two other locations to check which also do not contain
anything useful, and even are misleading because `:h E475` will point
you to `:h :call` by talking about Ex commands.

> > ## Thanks.
> > 
> > Best regards,
> > Hirohito Higashi (a.k.a. h_east)
> > 
> > ## 
> > 
> > ## 
> > 
> > You received this message from the "vim_dev" maillist.
> > Do not top-post! Type your reply below the text you are replying to.
> > For more information, visit http://www.vim.org/maillist.php
> > 
> > ---
> > 
> > You received this message because you are subscribed to the Google Groups "vim_dev" group.
> > To unsubscribe from this group and stop receiving emails from it, send an email to vim_dev+unsubscribe@googlegroups.com.
> > For more options, visit https://groups.google.com/d/optout.

**Comment by vim-ml** [comment]
Hi, 

If conflict between actual behavior and documentation, to correct either.  You modify the document.  But I modified the source code.
If we want to modify the source code, backward compatibility is considered may not have to worry about.  in this case.

Update a patch.
Adding E917 and E918 like as E474 and E475.
This error code displays the argument number of the error.
If this patch is included, I will also modify other E474 and E475. If possible.

## 

Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by vim-ml** [comment]
2016-02-26 9:52 GMT+03:00 h_east h.east.727@gmail.com:

> Hi,
> 
> If conflict between actual behavior and documentation, to correct either.  You modify the document.  But I modified the source code.
> If we want to modify the source code, backward compatibility is considered may not have to worry about.  in this case.
> 
> Update a patch.
> Adding E917 and E918 like as E474 and E475.
> This error code displays the argument number of the error.
> If this patch is included, I will also modify other E474 and E475. If possible.

I do not like `emsg…` functions, it is better to have _one_ `emsgfmt`
function: just copy smsg function with one modification, it is varargs
and the only modification needed is replacing `msg(IObuff)` with
`emsg(IObuff)`.

And still you are not checking for string length, thus accepting any
actions that start with space, 'r' or 'a'.

> ## 
> 
> Best regards,
> Hirohito Higashi (a.k.a. h_east)
> 
> ## 
> 
> ## 
> 
> You received this message from the "vim_dev" maillist.
> Do not top-post! Type your reply below the text you are replying to.
> For more information, visit http://www.vim.org/maillist.php
> 
> ---
> 
> You received this message because you are subscribed to the Google Groups "vim_dev" group.
> To unsubscribe from this group and stop receiving emails from it, send an email to vim_dev+unsubscribe@googlegroups.com.
> For more options, visit https://groups.google.com/d/optout.

**Comment by vim-ml** [comment]
Hi Bram,

I rewrote a patch and added a test.
This issue is in the TODO list.
TODO> Patch to have better check for {action} argument of setqflist().
TODO> Nikolai Pavlov, Feb 25, #661.  Can be even more strict.
TODO> Also see patch from Hirohito Higash, Feb 25.

## Please include this.

Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by vim-ml** [comment]
Hirohito Higashi wrote:

> I rewrote a patch and added a test.
> This issue is in the TODO list.
> TODO> Patch to have better check for {action} argument of setqflist().
> TODO> Nikolai Pavlov, Feb 25, #661.  Can be even more strict.
> TODO> Also see patch from Hirohito Higash, Feb 25.
> 
> Please include this.

Thanks!  Hopefully I soon have time to include lots of patches.

## 

hundred-and-one symptoms of being an internet addict:
129. You cancel your newspaper subscription.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///
