### ISSUE TITLE
Multibyte statusline fillchars

### ISSUE THREAD

**Issue by gustaphe** [vim/vim#6610]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
Statusline fillchars can currently not be multibyte characters iff `'statusline'` is set (the default statusline handles them correctly, though). A comment [in the code](https://github.com/vim/vim/blob/v8.1.2203/src/buffer.c#L3971) says "yet" but I can't find an issue tracking it.

**Describe the solution you'd like**
Multibyte fillchars in the statusline, also in custom statuslines.

**Describe alternatives you've considered**
It's possible to define a statusline _function_ that does the correct thing, but that seems like double work. And of course I can use single-byte characters, but I would love to be able to use the ━━━━━ group.

**Comment by tonymec** [comment]
I notice the following in the Vim documentation:
```
$VIMRUNTIME/doc/options.txt line 3241:
	for "stl" and "stlnc" only single-byte values are supported.

$VIMRUNTIME/doc/todo.txt lines 1214-1215:
8   "stl" and "stlnc" in 'fillchars' don't work for multi-byte characters.
    Patch by Christian Wellenbrock, 2013 Jul 5.
```
I suppose this patch is still considered "experimental" and not included in the distributed Vim code. @brammool , do you have the patch code? Do you know if it compiles with the 8.2 code?

Best regards,
Tony.

**Comment by tonymec** [comment]
P.S. AFAICT, I can set stl and/or stlnc to characters above U+007F with no error, and `:set fcs?` displays the value I set, but the statuslines (of gvim, with `'statusline'` set) display minus signs instead. (I tried first with · U+00B7 MIDDLE DOT then with ζ U+03B6 GREEK SMALL LETTER ZETA then with é U+00E9 LATIN SMALL LETTER E WITH ACUTE but always got minus signs.)

Best regards,
Tony.

**Comment by yegappan** [comment]
The patch for this is available in the following discussion thread:

https://groups.google.com/g/vim_dev/c/0Cta0HGEHI8/m/UODu5ZlnICEJ

**Comment by brammool** [comment]
Yegappan wrote:

> The patch for this is available in the following discussion thread:
> 
> https://groups.google.com/g/vim_dev/c/0Cta0HGEHI8/m/UODu5ZlnICEJ

Can you turn that into a pull request, so CI runs and tests?

-- 
JOHN CLEESE PLAYED: SECOND SOLDIER WITH A KEEN INTEREST IN BIRDS, LARGE MAN
                    WITH DEAD BODY, BLACK KNIGHT, MR NEWT (A VILLAGE
                    BLACKSMITH INTERESTED IN BURNING WITCHES), A QUITE
                    EXTRAORDINARILY RUDE FRENCHMAN, TIM THE WIZARD, SIR
                    LAUNCELOT
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
Hi Bram,

On Wed, Mar 3, 2021 at 12:23 PM Bram Moolenaar <vim-dev-github@256bit.org>
wrote:

>
> Yegappan wrote:
>
> > The patch for this is available in the following discussion thread:
> >
> > https://groups.google.com/g/vim_dev/c/0Cta0HGEHI8/m/UODu5ZlnICEJ
>
> Can you turn that into a pull request, so CI runs and tests?
>
>
Sure. Some of the tests in test_statusline.vim are failing with this patch.
Once those failures are addressed, I will create a PR.

- Yegappan

**Comment by chrisbra** [comment]
fixed by https://github.com/vim/vim/releases/tag/v8.2.2569
