### ISSUE TITLE
Nothing selected inside "(a)" in one-character case of 'vib' with selection=exclusive

### ISSUE THREAD

**Issue by rparenzs** [vim/vim#6616]
With "set selection=exclusive", if there is only one character between the parentheses, eg '(a)', and the cursor is on the character, then 'vib' does not select anything, where it should select the one character ('a' in this case). Notably, if the cursor is on either parenthesis, then it works correctly. Also fails for vi[, vi{, vi<.

Tested with "gvim --clean" on vim(32-bit) 8.2.1313 on Windows 10-64

**Comment by tonymec** [comment]
I confirm the problem on gvim 8.2.1360 with GTK2 GUI on Linux. On a line containing

(x)

vib or vi(
(with the cursor on x) remains in Visual mode without selecting anything; but

vib or vi(
(with the cursor on a parenthesis) selects the x and moves the cursor to the right parenthesis; and

yib or yi(
yank the single x character into the unnamed register, moving the cursor on the x if it was on a parenthesis.
To make sure, I used
  :let @@ = ""
before each yank.

Best regards,
Tony.
