### ISSUE TITLE
Colorcolumn not shown in area indented by 'breakindent'

### ISSUE THREAD

**Issue by rparenzs** [vim/vim#6619]
The automatic visual indentation by 'bri' or 'briopt=shift:{n}' seems to cancel out any column highlighting by 'colorcolumn' in the indented area.

gvim --clean
:set co=40 linebreak bri briopt=shift:2 cc=40,41,43
Type "The quick brown fox jumped over the lazy dogs"

Result: Only columns 40 and 43 are highlighted, not 41

This might be an intentional consequence of 'bri', but I couldn't find it documented in the help file, so maybe I'm just missing the obvious reason for it. It seems inconsistent to hide the colored columns in the auto-indented area while showing them in other virtual screen positions like the area occupied by tabs, the area past the end-of-line, or the area after the last word of the line before it wraps.

Tested with "gvim --clean" on vim(32-bit) 8.2.1313 on Windows 10-64

**Comment by chrisbra** [comment]
That looks like an edge case, that has not been considered:

![grafik](https://user-images.githubusercontent.com/244927/89399500-dddf3f00-d712-11ea-8b22-49ca3b3a1dff.png)

If you check the statusline, it will show something like `1,37-43` if the cursor is on the `l` of `lazy`. That means it is on virtual column 43, but the columns before it, are only virtually there, that is not in the actual text.

It might not be so easy to fix it (and the win_line() function is a bit of a mess).

**Comment by ademin** [comment]
The same issue is for 'showbreak'
`set co=40 showbreak=> cc=40,41,43`
![bug_showbreak](https://user-images.githubusercontent.com/5213441/93015905-ece4c700-f5c5-11ea-90d4-58e14520c05f.png)
