### ISSUE TITLE
use of undeclared identifier 'u_char'

### ISSUE THREAD

**Issue by Patterner** [vim/vim#662]
edit.c:4650:7: error: expected expression
                    EMPTY_IF_NULL(compl_shown_match->cp_str));
                    ^
./macros.h:122:48: note: expanded from macro 'EMPTY_IF_NULL'
# define EMPTY_IF_NULL(x) ((x) ? (x) : (u_char *)"")

```
                                           ^
```

edit.c:4650:7: error: use of undeclared identifier 'u_char'

(char_u is known)

src/macros.h
122:#define EMPTY_IF_NULL(x) ((x) ? (x) : (u_char *)"")

Using char_u fixes it.

**Comment by brammool** [comment]
Jörg Plate wrote:

> edit.c:4650:7: error: expected expression
>                     EMPTY_IF_NULL(compl_shown_match->cp_str));
>                     ^
> ./macros.h:122:48: note: expanded from macro 'EMPTY_IF_NULL'
> #define EMPTY_IF_NULL(x) ((x) ? (x) : (u_char *)"")
>                                                ^
> edit.c:4650:7: error: use of undeclared identifier 'u_char'
> 
> (char_u is known)
> 
> src/macros.h
> 122:#define EMPTY_IF_NULL(x) ((x) ? (x) : (u_char *)"")
> 
> Using u_char fixes it.

Must have been there for a long time.  There is another one in
intergration.c.

## 

Shaw's Principle: Build a system that even a fool can use, and
only a fool will want to use it.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Patterner** [comment]
Fixed by 7.4.1416
