### ISSUE TITLE
Cannot type YEN SIGN (¥)

### ISSUE THREAD

**Issue by bitigchi** [vim/vim#6624]
I noticed this while working on #6623. I just get a `\` instead of YEN SIGN. Tried with US-International layout and Turkish-F layout.

**To Reproduce**
1. Run `vim --clean`
2. Type `¥`
3. Prints `\`

**Expected behavior**
YEN SIGN (¥) should be visible. Only available through copy-paste.

**Environment (please complete the following information):**
 - Vim version 8.2.1360
 - macOS 10.15.6
 - Terminal: iTerm2

**Comment by tonymec** [comment]
I don't have a "yen sign" on my keyboard, but Ctrl-K Ye (the digraph for U+00A5 YEN SIGN) or Ctrl-V 165 (by decimal value) or Ctrl-V x a5 (by hex value) or Ctrl-V u 00A5 (by four-nybble Unicode hex value) all give me the ¥ character. Have you tried them? If they work, then my guess is a problem with your keyboard driver.

Oh, another thing: have you tried it in gvim or macvim? It happens that some console terminals filter some keys and don't pass them, or don't pass what you expected, to the program running in them.

I'm using Belgian AZERTY keyboard http://users.skynet.be/antoine.mechelynck/other/keybbe.htm with no keymap, and gvim 8.2.1361 with GTK3 GUI on openSUSE Linux 15.2.

Edit: There _is_ a yen key on my keyboard (AltGr-Shift-Y) and that too gives me a ¥ sign.

Best regards,
Tony.

**Comment by bitigchi** [comment]
Latest MacVim works, can type the sign without any errors.
CTRL-K Ye works as well (in Terminal).

So it's a terminal (or `vim`) issue I guess.

**Comment by tonymec** [comment]
My guess is a terminal issue, but I can't test iTerm2 on this Linux system.

Best regards,
Tony.

**Comment by bitigchi** [comment]
It doesn't work on `nano` either. Closing then.
