### ISSUE TITLE
This function makes my vim slow on large greps

### ISSUE THREAD

**Issue by mtglsk** [vim/vim#663]
```
function! QuickFixCounter()
  if len(getqflist()) == 0
    return ''
  else
    return '[' . len(getqflist()) . ']'
  endif
endfunction

set statusline+=%{QuickFixCounter()}
```

Vim gets unseasonably slow on large greps (~30000 in Quickfix list). The window is slow to react to commands.

**Comment by mattn** [comment]
``` vim
function! QuickFixCounter()
  let n = len(getqflist())
  if n == 0
    return ''
  else
    return '[' . n . ']'
  endif
endfunction

set statusline+=%{QuickFixCounter()}
```

maybe this make speed-up.

**Comment by chrisbra** [comment]
statusline expressions are evaluated a lot. you should cache the current setting, instead of re-evaluating it always. You can use QuickFixCmdPost to update your cache. BTW: such thinks should first discussed on vim-use ml before submitting as issue. Closing.

**Comment by mtglsk** [comment]
Neither caching the value inside function and QuickFixCmdPost help.

But combining both seems to work:

```
function! QuickFixCounter()
  if g:n == 0
    return ''
  else
    return '[' . g:n . ']'
  endif
endfunction
autocmd BufWinEnter,QuickFixCmdPost * let g:n=len(getqflist())
set statusline+=%{QuickFixCounter()}
```

Thanks chrisbra and mattn.
