### ISSUE TITLE
No "swap file exists" warning in same filename case

### ISSUE THREAD

**Issue by rparenzs** [vim/vim#6635]
[Description]: If the swap file 'directory' is not the current directory ".", then you can have a case where you open the same file again but do not get the "swap file exists" warning, allowing you have to unknowingly have multiple instances of vim modifying the same file at once. This happens when you have two or more different files with the same name but different paths (eg "readme.txt"). When you edit the first "readme.txt" file, that file is protected with the "swap file exists" warning if you ever open it again. While the first file is open, if you open a second, different "readme.txt", that file is NOT protected from subsequent re-openings with the "swap file exists" warning. The same goes for the third, fourth, etc, different "readme.txt" files you open. Only the first "readme.txt" file, while it is still open, is protected.

[Reproduce]:
Create three folders, each with a readme.txt file (can be empty)
>1\readme.txt
>2\readme.txt
>3\readme.txt

Open each file:
`gvim --clean --cmd "set dir=$TEMP" 1\readme.txt`
`gvim --clean --cmd "set dir=$TEMP" 2\readme.txt`
`gvim --clean --cmd "set dir=$TEMP" 3\readme.txt`

Re-open each file:
`gvim --clean --cmd "set dir=$TEMP" 1\readme.txt`
`gvim --clean --cmd "set dir=$TEMP" 2\readme.txt`
`gvim --clean --cmd "set dir=$TEMP" 3\readme.txt`

[Result]: Only re-opening "1\readme.txt" produced the "swap file exists" warning.

[Expected]: The re-opening of any of the three files should produce the "swap file exists" warning.

[Comment]: It seems that when you open a file "readme.txt", the swap directory is checked for a corresponding "readme.txt.swp" file and if found, it also compares the path embedded in it for a match (I assume). But if you open a second "readme.txt" while the first is still open, it gets swap file "readme.txt.swo". A third gets "readme.txt.swn", etc. The problem seems to be that only ".swp" is ever checked when a file is opened, not the others. It seems vim should check all the "readme.txt.sw*" files in the swap directory for a matching path to prevent this problem. Just a guess.

[Environment]: Tested with "gvim --clean" on vim(32-bit) 8.2.1313 on Windows 10-64

**Comment by chrisbra** [comment]
I think this is a long standing peculiar behaviour that I have also noticed. If you have several swap files for the same file. As long as there is a `.swp` file, vim will present the attention message, but when there are only .swo and other files, Vim won't notice. Have never looked into this.

**Comment by brammool** [comment]
Correct.  Vim only checks for the .swp file, because checking all .sw[a-z] files can be slow.  On a local file system with proper caching it may be quite fast, but when using a networked file system it can be really slow.  This should not happen often enough to justify making the very common operation to edit a file slower.
One solution (which I never tried) is to check a few names, but limit the time to, say, 50 msec.

**Comment by tonymec** [comment]
This only happens when different files of the same name have their swapfiles in a common directory, which is not the default if the file's directory is writable (the first item in 'directory' is . by default, meaning "put the swapfile in the same directory as the file being edited").

**Comment by rparenzs** [comment]
The current way also means that, say the power went out while you had a file open (and modified) with .swo, you might never know you lost some changes until it was too late (eg, you remodified and saved the file), since you wouldn't get the warning prompt. If you knew the file had lost changes (eg, it was the file you were working on when it went dark), then you could run ":recover" but I wonder how many users are aware of that command since the "Recover" button is so convenient.

One idea might be just to echo (no dialog box) some kind of warning to the user if there are _any_ "readme.txt.sw*" files in the swap folder. Like "Caution: There are 3 possible swap files for this file in the swap directory $TMP ... you better know what you are doing; if unsure, try :recover...". Since it is just a directory search instead of reading each file, I imagine it would be fast enough (?). Granted, it might be confusing or obtrusive to some, but this is uncommon, it isn't going to happen all the time, and when it does, more info is better than less.

On the solution of checking a few files with a time limit, I think adding just .swo (very common), and maybe .swn and .swm too, would cover much of the cases.

**Comment by k-takata** [comment]
Not sure how to fix this, but there is a work around in user side: Append two slashes in the 'dir' option. (See `:help 'dir'`.

**Comment by rparenzs** [comment]
Uh, I think that workaround totally fixes it. Missed that completely, even though I was thinking about it (like the way the undodir is). Just want to test it a little. Maybe that should be on by default.

**Comment by chrisbra** [comment]
Well, it can technically also happen when you do not use the 'dir' option and the swapfile is in the same directory as the file being edited. It happens regularly to me, when working on Vim. But perhaps I am just too sloppy and it is not something to generally worry about.

**Comment by rparenzs** [comment]
@chrisbra: I tried to reproduce what you were talking about, but I can't seem to see it.  If there is no .swp, the next file opened will not get the warning but will also create .swp. That next file does not need the warning since the other files, with .swo, .swn, etc, should be 'readonly' by default due to the previous file, now gone, that created .swp.

**Comment by tonymec** [comment]
@rparenzs: what can happen, is that if Vim crashes (or if for instance you pull the computer's plug without closing Vim) the .swp won't be removed. Then the next time you edit the same file the ATTENTION message comes up. If you had dutifully saved your work before the crash appears, it wil say "modified:no" and in that case you can answer d (delete) to delete (and reuse) the same .swp filename.

IMHO it is more prudent to close all Vim sessions (if possible) before logging out or rebooting.

**Comment by tonymec** [comment]
@rparenzs: what can happen, is that if Vim crashes (or if for instance you pull the computer's plug without closing Vim) the .swp won't be removed. Then the next time you edit the same file the ATTENTION message comes up. If you had dutifully saved your work before the crash appears, it wil say "modified:no" and in that case you can answer d (delete) to delete (and reuse) the same .swp filename.

IMHO it is more prudent to close all Vim sessions (if possible) before logging out or rebooting.

**Comment by rparenzs** [comment]
@tonymec: You're describing the proper case where you do get the warning because of presence of .swp, and I'm all for that. Chris, if I'm not mistaken, was talking about _not_ getting the ATTENTION warning due to the absensce of .swp, despite the presence of .swo, .swn, etc.
I'm closing this since I'm satisfied with the workaround for the original case of 'dir' not being set to the current directory.
