### ISSUE TITLE
Request For Comment: Emoji

### ISSUE THREAD

**Issue by mattn** [vim/vim#665]
Vim doesn't handle emoji correctly. Most of terminal emulators including xterm have been drawn emoji with half width character in default. So many multi-byte users troubled. We can't see emoji on vim correctly.

![](https://i.gyazo.com/0c3c3a7abcdf91acc79c79d43ca1d7e5.png)

As you know emoji was defined as ambiguous width on unicode.org. (**fix1**: in latest, it's narrow, but may be fixed in [PRI318](http://www.unicode.org/review/pri318/), **fix2**: if PRI318 will be accepted, all of emoji will be wide) So vim doesn't handle emoji as double width. https://github.com/vim/vim/blob/master/src/mbyte.c#L1267 . 

However, most of ASCII users may not know, unicode.org recomend emoji as square aspect ratio.

http://unicode.org/reports/tr51/

> Current practice is for emoji to have a square aspect ratio, deriving from their origin in Japanese. For interoperability, it is recommended that this practice be continued with current and future emoji.

iTerm2 provide option to switch narrow and wide.

```
Preferences -> Advanced -> Unicode East Asian Ambiguous character are wide
```

And macvim render emoji as wide. https://github.com/macvim-dev/macvim/pull/187

So I hope that vim also can handle emoji as wide possibly. I don't have stuck about implementation of handling emoji widths to treat as double. We are okay if vim provide way to render emoji as double width. Even though if it is new option 'emoji' or something with false in default for doing that. For example,
### Suggestion1: load EastAsianWidth.txt

```
set ambiwidth=@/path/to/EastAsianWidth.txt
```

user can modify data.
### Suggestion2: new value for ambiwidth

Currently, it take two values single or double. Then new value 'fulldouble' for fix this issue.
### Suggestion3: new option 'emoji'

https://gist.github.com/mattn/00dc87d2e8cf1dd3131d

This implementation refered unicode data from 1.0 to 6.0. This patch handle emoji as wide.

![](https://i.gyazo.com/35c22d6a500122394468a315de2d9d64.png)

AFAIK, most of fonts expect the square aspect ratio for rendering of emoji as wide. For example, smily face ( :smile: :sushi: or etc ). At least, I don't want to eat sushi rendered as narrow width.

**Comment by adelarsq** [comment]
Would be nice this feature. Actually I have so much trouble with this too:
![a](https://cloud.githubusercontent.com/assets/430272/13407897/88320e30-df09-11e5-8cc9-a970f547722d.png)
The better option is the 3 I think. Others chars worked fine?

**Comment by brammool** [comment]
Adelar da Silva Queiróz wrote:

> Would be nice this feature. Actually I have so much trouble with this too:
> ![a](https://cloud.githubusercontent.com/assets/430272/13407897/88320e30-df09-11e5-8cc9-a970f547722d.png)
> The better option is the 3 I think. Others chars worked fine?

To get this moving forward we need to convince others that these Emoji
characters are to be considered full width.  I asked Thomas Dickey.
He suggested we should also get wcwidth() to behave this way.  I hope
someone can look into that.

## 

Computers make very fast, very accurate, mistakes.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mandel59** [comment]
FYI, [Proposed Update UAX #11, East Asian Width](http://www.unicode.org/reports/tr11/tr11-30.html) ([PRI318](http://www.unicode.org/review/pri318/)) notes:

> Review Note: In terms of Unicode Version 8.0, and although not yet reflected in the EastAsianWidth.txt data file, this will result in the following 774 characters being changed from Neutral to Wide: 231A..231B, 23E9..23EC, 23F0, 23F3, 25FD..25FE, 2648..2653, 267F, 2693, 26A1, 26AA..26AB, 26BD, 26CE, 2705, 270A..270B, 2728, 274C, 274E, 2753..2755, 2795..2797, 27B0, 27BF, 2B1B..2B1C, 2B50, 1F004, 1F0CF, 1F300..1F320, 1F32D..1F335, 1F337..1F37C, 1F37E..1F393, 1F3A0..1F3CA, 1F3CF..1F3D3, 1F3E0..1F3F0, 1F3F4, 1F3F8..1F43E, 1F440, 1F442..1F4FC, 1F4FF..1F53D, 1F54B..1F54E, 1F550..1F567, 1F595..1F596, 1F5FB..1F64F, 1F680..1F6C5, 1F6CC, 1F6D0, 1F6EB..1F6EC, 1F910..1F918, 1F980..1F984, and 1F9C0; and the following 25 characters being changed from Ambiguous to Wide: 2614..2615, 26BE, 26C4..26C5, 26D4, 26EA, 26F2..26F3, 26F5, 26FA, 26FD, 2757, 2B55, 1F18E, and 1F191..1F19A.

And:

> Emoji style standardized variation sequences behave as though they were East Asian Wide, regardless of their assigned East_Asian_Width property value.

**Comment by mattn** [comment]
Thanks!

https://github.com/vim/vim/commit/3848e00e0177abdb31bc600234967863ec487233

**Comment by adelarsq** [comment]
The vertical movement is showing a strange behavior.

With DirectX enabled:
![a](https://cloud.githubusercontent.com/assets/430272/13953680/e0310a8c-f01b-11e5-9e13-7dcea60095d7.png)
Without DirectX:
![b](https://cloud.githubusercontent.com/assets/430272/13954016/b766abe6-f01d-11e5-9b64-235be618efa2.png)

Others operations are working fine.

Vim 7.4.1627
SO: Windows 10

**Comment by mattn** [comment]
It seems that width of cursor is correct, But seems that the width of cells are bit storange to me.

**Comment by adelarsq** [comment]
This happen with all "no default" chars. In this case the chars are taken from [vim-webdevicons](https://github.com/ryanoasis/vim-webdevicons) plugin:
![c](https://cloud.githubusercontent.com/assets/430272/13956081/fb0f244c-f025-11e5-850e-a36b683df67f.png)
With ambiwidth double and single the behaviour is the same.

**Comment by adelarsq** [comment]
I think that this issue can be closed and open another to solve the rendering problem, since the cause isn't exactly related with the last changes.
