### ISSUE TITLE
key mapping partly stop working after few times pressing until move cursor

### ISSUE THREAD

**Issue by limkokhole** [vim/vim#666]
I follow instruction at http://stackoverflow.com/questions/2627886/how-do-i-run-a-c-program-from-vim , to run a C program from VIM by shortcut key.

I put `map <F8> :w <CR> :!gcc % -o %< && ./%< <CR>` inside ~/.vimrc, it did works but stop working after few times pressing. 

It's not terminal problem because it (sometime) affect other terminal as well, e.g. if konsole stop working, then open xterm, the key (might) stop working too.

The title stated "partly stop working" because the `:w` still working as it still able to print out "written" on the bottom of vim editor. Just the later part `<CR> :!gcc % -o %< && ./%< <CR`  is stop working. 
Note that nothing to do with `&&` because even `;` still same (And i removed the file then no file recreate, to proved gcc not running at all)

The temporary work around is move the cursor(e.g. right ), then the key working fine again.

Steps to reproduce:
1. Save `map <F8> :w <CR> :!gcc % -o %< && ./%< <CR>` inside ~/.vimrc.
2. Create a simple c program file.
3. Inside c file, press F8, then ENTER, repeat a few times.
4. Suddenly, the file did written but gcc not working anymore.
5. Move cursor up and press F8. Now the gcc works again.

My platform is:
[1] Fedora 21
[2] VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov  4 2015 13:11:36)

**Comment by fritzophrenic** [comment]
Please post to the [mailing list](https://groups.google.com/forum/#!forum/vim_use) for help requests such as this. I see a likely error in your mapping that could cause this (assuming it's not a formatting issue) but do not want to start an extended discussion in the **bug tracker**.
