### ISSUE TITLE
Popup windows not redrawn when normal-mode commands used for scrolling

### ISSUE THREAD

**Issue by bfrg** [vim/vim#6663]
**Describe the bug**
Popup windows are not redrawn when normal-mode commands are used for scrolling, only after pressing `CTRL-L`.

This is not the case when a popup window is scrolled using the `firstline` entry.

**To Reproduce**
1. Run `vim --clean -S test.vim`, with
   ```vim
   function Popup_filter(winid, key) abort
       if a:key ==# 'j'
           call win_execute(a:winid, "normal! \<c-e>")
       elseif a:key ==# 'k'
           call win_execute(a:winid, "normal! \<c-y>")
       else
           return v:false
       endif
       return v:true
   endfunction

   let text =<< trim END
       test test test
       test test test
       test test test
       test test test test test test test test test test test test
       test test test test test test test test test test test test
       test test test test test test test test test test test test
       test test test
       test test test
       test test test
   END

   let &showbreak = '+++ '
   call popup_create(text, {'maxheight': 2, 'filter': 'Popup_filter'})
   ```
2. Press `j` 3 times until the `showbreak` characters appear. Since no  `maxwidth` entry is specified, I would have assumed the popup window to be resized automatically, but this doesn't occur. Pressing `CTRL-L` will redraw the popup window and display its new size.

---

3. Setting the `maxheight` entry inside the popup filter will redraw the popup as expected:
   ```vim
   function Popup_filter(winid, key) abort
       if a:key ==# 'j'
           call win_execute(a:winid, "normal! \<c-e>")
       elseif a:key ==# 'k'
           call win_execute(a:winid, "normal! \<c-y>")
       else
           return v:false
       endif
       call popup_setoptions(a:winid, {'maxheight': 2})
       return v:true
   endfunction
   ```
4. Using the `firstline` entry for scrolling works as expected, too:
   ```vim
   function Popup_filter(winid, key) abort
       if a:key ==# 'j'
           let line = popup_getoptions(a:winid).firstline
           let nlines = line('$', a:winid)
           call popup_setoptions(a:winid, {'firstline': line < nlines ? (line + 1) : nlines})
       elseif a:key ==# 'k'
           let line = popup_getoptions(a:winid).firstline
           call popup_setoptions(a:winid, {'firstline': (line - 1) > 0 ? (line - 1) : 1})
       else
           return v:false
       endif
       return v:true
   endfunction
   ```

**Expected behavior**
I would have expected the popup window to be redrawn when normal-mode commands are used for scrolling, just like when the `firstline` entry is used for scrolling.

**Environment**
Vim version `8.2.1379`

**Comment by brammool** [comment]
If you use :normal to execute some command, this bypasses the code for popup windows.  I would think that if you do this it is intentionally not setting popup window properties, thus resizing would be unexpected.
If you call popup_setoptions() with any argument then the resizing will be triggered.  Thus I don't see a need to change the behavior.
