### ISSUE TITLE
Syntax highlighting - tex / latex - errors are an error

### ISSUE THREAD

**Issue by guido99** [vim/vim#6666]
revtex (used by physics community worldwide) extensions of latex use some a few extra environmental tags. Another form of "equation" is "gather". Currently tex.vim will mark all sub/superscripts as errors. I have patched tex.vim to incorporate the new label. It works for me.

```diff
--- tex.vim	2020-07-25 08:55:49.000000000 -0700
+++ tex.new.vim	2020-08-05 14:19:17.040835605 -0700
@@ -409,7 +409,7 @@
 " Bad Math (mismatched): {{{1
 if !exists("g:tex_no_math") && !s:tex_no_error
  syn match texBadMath		"\\end\s*{\s*\(array\|[bBpvV]matrix\|split\|smallmatrix\)\s*}"
- syn match texBadMath		"\\end\s*{\s*\(displaymath\|equation\|eqnarray\|math\)\*\=\s*}"
+ syn match texBadMath		"\\end\s*{\s*\(displaymath\|equation\|eqnarray\|math|gather\)\*\=\s*}"
  syn match texBadMath		"\\[\])]"
 endif
 
@@ -452,6 +452,7 @@
  call TexNewMathZone("B","eqnarray",1)
  call TexNewMathZone("C","equation",1)
  call TexNewMathZone("D","math",1)
+ call TexNewMathZone("E","gather",1)
 
  " Inline Math Zones: {{{2
  if s:tex_fast =~# 'M'
```

And here's a bash script using sed to do it in situ.

```bash
#!/bin/bash
TV=tex.vim ; TV0=$TV~ ; cd /usr/share/vim/vim82/syntax
grep '|gather' $TV && exit #already fixed
[[ -e $TV0 ]] || cp -p $TV $TV0
#syn match texBadMath		"\\end\s*{\s*\(displaymath\|equation\|eqnarray\|math\)\*\=\s*}"  #original line
LN=$( sed -n '/eqnarray..math/=' $TV )
#call TexNewMathZone("D","math",1)  #original line
sed -i '/eqnarray..math/ s:\\):|gather&: ; /MathZone..D/a\
 call TexNewMathZone("E","gather",1)' $TV
most +$LN $TV
#not in vimBuild


```

**Comment by guido99** [comment]
The documentation inside the tex.vim script **does** note that other math environments can be included using the function NewTexMathZone that seems to yield the same result noted above.

But, why not make all such changes permanently inside tex.vim. The maintainer should peruse RevTex docs for all the environments defined there?

**Comment by cecamp** [comment]
Try reading :help tex-package.  Check into the syntax additions I've made available on my website, which, by the way, include gather.

**Comment by cecamp** [comment]
Try reading :help tex-package.  Check into the syntax additions I've made available on my website, which, by the way, include gather.

**Comment by cecamp** [comment]
Try reading :help tex-package.  Check into the syntax additions I've made available on my website, which, by the way, include gather.

**Comment by cecamp** [comment]
Try reading :help tex-package.  Check into the syntax additions I've made available on my website, which, by the way, include gather.

**Comment by cecamp** [comment]
Try reading :help tex-package.  Check into the syntax additions I've made available on my website, which, by the way, include gather.

**Comment by albinahlback** [comment]
This issue should be closed, right?

**Comment by guido99** [comment]
OK.
