### ISSUE TITLE
Built-in xterm termcap's t_AU and t_8u settings cause blinking/faint text in mintty

### ISSUE THREAD

**Issue by bcat** [vim/vim#6687]
**Describe the bug**
Vim [currently sets the `t_AU` and `t_8u` termcap extensions](https://github.com/vim/vim/blob/master/src/term.c#L904) (set underline color indexed and RGB, respectively) as follows:

* `let &t_AU = "\e[58;5;%dm"`
* `let &t_8u = "\e[58;2;%lu;%lu;%lum"`

These are originally [kitty extensions](https://sw.kovidgoyal.net/kitty/protocol-extensions.html#colored-and-styled-underlines), but have since been added to more terminals. ([hterm](https://chromium-review.googlesource.com/c/apps/libapps/+/852390/), [iTerm2](https://gitlab.com/gnachman/iterm2/-/issues/6382), [mintty](https://github.com/mintty/mintty/commit/ee62f9006b4a14b5f71bf450e235fe63f3fba210), and [VTE](https://bugzilla.gnome.org/show_bug.cgi?id=721761) are the ones I know of.)

Like the 38 and 48 SGR codes to set RGB foreground and background colors, the SGR 58 code has the same choice of semicolon or colon as subparameter delimiter. However, unlike 38 and 48, there's a lot fewer legacy terminals using the semicolon delimiter. As such, it seems that at least mintty only implemented the colon delimeter, which offers better compatibility with older SGR parsers.

**To Reproduce**
Detailed steps to reproduce the behavior:

For indexed:
1. Run `vim --clean` in mintty.
2. Execute `hi clear SpellBad`.
3. Execute `hi SpellBad cterm=underline ctermul=1`.
4. Execute `set spell`.
5. Type a misspelt word.
6. Observe that the misspelt word is now blinking and the underline color is not changed. It appears mintty has parsed this as SGR 58, SGR 5 (blink).

For RGB color:
1. Run `vim --clean` in mintty.
2. Execute `hi clear SpellBad`.
3. Execute `hi SpellBad cterm=underline guisp=#00ff00`.
5. Execute `set termguicolors`.
5. Execute `set spell`.
6. Type a misspelt word.
7. Observe that the misspelt word is now not underlined at all. It appears mintty has parsed this as SGR 58, SGR 2 (dimmed).

**Expected behavior**
The text in the first case should have a red underline, and in the second case should have a green underline. The text should not blink or be dimmed.

Vim uses semicolon as a subparameter delimiter for SGR 38 and 48, and that's probably needed for compatibility; however, for the newer and much less widespread SGR 58, it looks like the colon delimiter actually has better compatability. It's also more likely be be ignored (instead of incorrectly processed as SGR 2 or SGR 5) on a terminal that doesn't support colored underlines at all. So I suggest the builtin xterm termcap be changed as follows:

* `let &t_AU = "\e[58:5:%dm"`
* `let &t_8u = "\e[58:2::%lu:%lu:%lum"`

 (Note the double colon in `t_8u`; this is indeed part of the syntax.)

I've tested these colon-delimited sequences in hterm, kitty, mintty, and VTE (Sakura) and they all work properly. I can't test iTerm2 since I don't have a Mac, but maybe @gnachman can help verify that?

**Environment (please complete the following information):**

```
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun  1 2020 06:42:35)
Included patches: 1-869
Compiled by <https://www.msys2.org/>
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
-autoservername    +folding           +multi_byte        +termguicolors
-balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
-browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              +perl/dyn          +title
-clientserver      +job               +persistent_undo   -toolbar
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           +python/dyn        +visual
+conceal           +linebreak         +python3/dyn       +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       -lua               +ruby/dyn          +wildmenu
+dialog_con        +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
-dnd               +mouse             -sound             -xfontset
-ebcdic            -mouseshape        +spell             -xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              -mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim82"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -I/usr/include/ncursesw  -march=x86-64 -mtune=generic -O2 -pipe -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -pipe -fstack-protector-strong -pipe -Wl,--as-needed -o vim.exe        -lm -lelf    -lncursesw -liconv -lacl -lintl   -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base -fstack-protector-strong  -L/usr/lib/perl5/core_perl/CORE -lperl -lpthread -ldl -lcrypt
```

```
$ uname -a
MINGW64_NT-10.0-19041 holden 3.1.6-340.x86_64 2020-07-17 05:52 UTC x86_64 Msys
```

```
$ mintty --version
mintty 3.2.0 (x86_64-pc-msys)
© 2013/2020 Andy Koppe / Thomas Wolff
License GPLv3+: GNU GPL version 3 or later
There is no warranty, to the extent permitted by law.
```

**Comment by bcat** [comment]
I could also file a bug against @mintty to support the semicolon delimiter for SGR 58, but it may have been an intentional choice on their part not to support it, since the colon delimiter is less "dangerous" (in the sense that it's easier for terminals that don't support SGR 58 at all to ignore). That ship has probably sailed for 38/48, but doing the right thing (colon) for 58 seems reasonable to me.

IMO the ideal solution is for Vim to change its delimiter (for 58 only) to colon, assuming we can verify iTerm2 compatibility (and maybe make sure it doesn't break anything in tmux... I don't know if tmux even passes SGR 58 today).

**Comment by bcat** [comment]
I verified that tmux also parses the colon-delimited version of this escape sequence, though it requires something like `set -g terminal-overrides '*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'` to pass it through to the outer terminal.

As such, assuming iTerm2 supports the colon delimiter, I think the change I proposed is a strict improvement (fixing mintty and being more compatible with SGR parsers not aware of SGR 58, without breaking any terminals that work today).

**Comment by brammool** [comment]
This was discussed before in various places, arguing that either one or the other was a mistake, and explaining some standard depending on how you read it..  Since the current implementation works in existing terminals, and mintty is a new one, best is to make this work in mintty.  Or make sure to set $TERM to mintty, so that the right termcap/terminfo is used.  As always, setting $TERM to "xterm" or something like that is intended to work with an actual xterm.  It might work with a few others, but we can't possibly guarantee that.

**Comment by bcat** [comment]
> This was discussed before in various places....

Not trying to be a jerk, just curious... can you link me to those previous discussions? I only found discussions in the context of SGR 38/48, and from what I could tell, the general consensus was "colons are safer than semicolons, but the semicolon form is too widespread for applications to use by default". For SGR 58, though, I am not sure that conclusion still holds, since SGR 58 is newer and less widespread (in both terminals and applications).

If the "right thing" is to use colons (which I may have misparsed... that was my understanding), then IMO it'd make sense to use colons for SGR 58 (and possibly for terminal emulators not to implement a semicolon form for SGR 58) even if SGR 38/48 are stuck with semicolons for historical reasoning.

I could also see an argument that doing something different for SGR 58 than for 38/48 is more confusing than it's worth.... I'd be mostly convinced by that; I just want to make sure I understand the reasoning.

> Or make sure to set $TERM to mintty, so that the right termcap/terminfo is used.

I'd love to just set `$TERM=mintty`, FWIW, but I couldn't find a good way to make that work with Vim right now. Codes like `t_AU` and `t_8u` seem to be Vim extensions that don't exist in published terminfo databases, only in Vim's builtin xterm termcap. (I wish Vim's builtin termcaps were encoded as Vimscript that could be updated and deployed separately rather than being compiled into Vim, but that seems like a big change and I wasn't sure it was worth proposing.)

I can, of course, work around this with something like

```
if &term =~# '\vmintty%(-|$)'
  let &t_AU = "\e[58:5:%dm"
  let &t_8u = "\e[58:2::%lu:%lu:%lum"
endif
```

but then mintty no longer passes Vim's "term is xterm" check, and so I lose all the _other_ useful default Vim termcap extensions for things like bracketed paste, etc. (tmux has the same problem, c.f. #6609.)

Maybe what I really want is a way for Vimscript to override the `vim_is_xterm` check? I haven't thought through the implications of that, but it would at least unblock setting an accurate `$TERM` instead of lying and saying xterm all the time.

**Comment by mintty** [comment]
@brammool,

> Since the current implementation works in existing terminals, and mintty is a new one, ...

Puzzled. SGR 58 is not supported in xterm and its semicolon usage makes xterm blink like mintty. If you maintain a strict view of things, you should drop SGR 58 from vim.

**Comment by brammool** [comment]
I don't maintain a strict view, I just do what works for most users.  Considering the lack of complaints it appears to work quite well.  Of course there are a few individuals, especially ones that try out different terminals, that run into problems.  It's unpredictable what will happen if I change the defaults, most likely more users will complain.

How do you make xterm blink?  I have never seen that.  Please give an example starting with "vim --clean".
