### ISSUE TITLE
Problems with indentation and comments

### ISSUE THREAD

**Issue by renu285** [vim/vim#669]
Hello,

I have observed that when the files are indented using the highlighter(ctrl - v) and indented (ctrl-+) extra comments are added.
Example: 
\ Line-1
   Line-2
After indenting using highlighter
\Line-1
\Line-2

This behaviour is observed on with "\" style of comment and not with "* *\" style.

**Comment by fritzophrenic** [comment]
What is the CTRL-+ command? Is that from a plugin? If it's from a plugin please consult the plugin author. If it's a custom mapping please ask for help on the [mailing list](https://groups.google.com/forum/#!forum/vim_use)

**Comment by chrisbra** [comment]
Please discuss user issues on the vim-use ml. This is only for actual bugs. Thanks! We can still create issues, if it turns out to be an actual bug.
