### ISSUE TITLE
crash when interrupting errors at more prompt

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6701]
**Describe the bug**

Sometimes, Vim crashes when interrupting errors at the more prompt.

**To Reproduce**

Write this in `/tmp/crash.vim`:
```vim
set columns=80 lines=15
call mkdir('/tmp/toggle/autoload', 'p')
let lines =<< trim END
    import MapSave from 'lg/map.vim'
    fu toggle#auto_open_fold()
        eval s:MapSave(['j', 'k', '<down>', '<up>', '<c-d>', '<c-u>', 'gg', 'G'], 'n', v:true)
    endfu
    nno coz :call toggle#auto_open_fold()<cr>
END
call writefile(lines, '/tmp/toggle/autoload/toggle.vim')
set rtp^=/tmp/toggle
set rtp^=/tmp/lg
let lines =<< trim END
    vim9script
    export def MapSave(keys: any, mode = '', wantlocal = v:false): list<dict<any>>
        if type(keys) != v:t_list && type(keys) != v:t_string | return [] | endif
        let _keys = type(keys) == v:t_list ? keys : [keys]
        let save: list<dict<any>> = []
        for key in _keys
            for m in mode == '' ? [''] : split(mode, '\zs')
                let maparg = Maparg(key, m, wantlocal)
                save += [maparg]
            endfor
        endfor
        return save
    enddef
    def Maparg(name: string, mode: string, wantlocal: bool): dict<any>
        let maparg = maparg(name, mode, 0, 1)
        if empty(maparg) || wantlocal && !Islocal(maparg)
            maparg = {
                'unmapped': v:true,
                'lhs': name,
                'mode': mode == '' ? ' ' : mode,
                'buffer': wantlocal,
            }
        endif
        if Islocal(maparg)
            extend(maparg, {'bufnr': bufnr('%')})
        endif
        return maparg
    enddef
    def Islocal(maparg: dict<any>): number
        echom maparg
        return 1
    enddef
END
call mkdir('/tmp/lg/import/lg', 'p')
call writefile(lines, '/tmp/lg/import/lg/map.vim')
nno j gj
nno k gk
nmap <down> j
nmap <up> k
augroup some_augroup
    au CmdlineEnter : ru autoload/toggle.vim | au! some_augroup
augroup END
au VimEnter * call feedkeys(":\ecoz", 't')
```
Start Vim like this:

    vim -Nu /tmp/crash.vim

Several `E731` errors are raised.  Do not press `G` or `j` to jump at the end of the pager.  Instead press `C-c` once or twice to interrupt and quit the pager.

Vim crashes.

**Expected behavior**

Vim doesn't crash.

**Environment**

 - Vim version: 8.2 Included patches: 1-1438
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: XTerm(358)

**Additional context**

I know the "minimal" example is complicated, but:

 - the original code was much more complicated and scattered across multiple plugins
 - it took me four hours to come up with it
 - hopefully, the next backtrace and logs will be enough to find a fix

---

I *think* the issue has something to do with the import because I wasn't able to reproduce when I briefly tried to remove it.

It definitely has something to do with the height of the terminal; I think it must be low enough so that we're at the more prompt when the errors are displayed (i.e. there must be lines which the pager can't display).

---

In xterm, you need to press `C-c` twice; it seems that in other terminals, pressing it once is enough.

---

- [backtrace](https://github.com/vim/vim/files/5066805/backtrace.txt)
- [valgrind log](https://github.com/vim/vim/files/5066806/valgrind.log)
- [asan log](https://github.com/vim/vim/files/5066804/asan.log)

Note that Vim doesn't crash when instrumented by valgrind, but it does when instrumented by asan.

**Comment by lacygoill** [comment]
Here's a shorter snippet which reproduces the crash (it's about 25% shorter):
```vim
vim9script
let lines =<< trim END
    import MapSave from 'map.vim'
    nno <F3> :call <sid>MapSave()<cr>
END
mkdir('/tmp/toggle/autoload', 'p')
writefile(lines, '/tmp/toggle/autoload/toggle.vim')
set rtp^=/tmp/toggle rtp^=/tmp/lg columns=80 lines=15
lines =<< trim END
    vim9script
    export def MapSave(): list<dict<any>>
        let save: list<dict<any>> = []
        for key in ['j', 'k', '<down>', '<up>', '<c-d>', '<c-u>', 'gg']
            let maparg = Maparg(key)
            save += [maparg]
        endfor
        return save
    enddef
    def Maparg(name: string): dict<any>
        let maparg = maparg(name, 'n', 0, 1)
        if empty(maparg) || !Islocal(maparg)
            maparg = #{unmapped: true, lhs: name}
        endif
        if Islocal(maparg)
        endif
        return maparg
    enddef
    def Islocal(maparg: dict<any>)
        echom maparg
    enddef
END
mkdir('/tmp/lg/import', 'p')
writefile(lines, '/tmp/lg/import/map.vim')
nno j j
nno k k
nmap <down> j
nmap <up> k
au CmdlineEnter : ru autoload/toggle.vim
feedkeys(":\e\<F3>")
```

**Comment by lacygoill** [comment]
> I think the issue has something to do with the import because I wasn't able to reproduce when I briefly tried to remove it.

I was wrong; it has nothing to do with the import; it can be reproduced without.

Here's yet another shorter snippet:
```vim
vim9script
set rtp^=/tmp/toggle rtp^=/tmp/lg columns=80 lines=15

let lines =<< trim END
    vim9script
    def MapSave()
        let save: list<dict<any>> = []
        for key in ['j', 'k', '<down>', '<up>', '<c-d>', '<c-u>', 'gg']
            Maparg()
        endfor
    enddef
    def Maparg()
        let maparg = #{unmapped: true, lhs: 'j'}
        Islocal(maparg)
        Islocal(maparg)
    enddef
    def Islocal(maparg: dict<any>)
        echom maparg
    enddef
    nno <F3> :call <sid>MapSave()<cr>
END
mkdir('/tmp/toggle/autoload', 'p')
writefile(lines, '/tmp/toggle/autoload/toggle.vim')

nno j j
nno k k
nmap <down> j
nmap <up> k
au CmdlineEnter : ru autoload/toggle.vim
feedkeys(":\e\<F3>")
```

**Comment by lacygoill** [comment]
Note that in xterm, with the last snippet, you need to press `C-c` three times for Vim to crash (with the very first snippet, twice was enough).  In other terminals, you need to press `C-c` only once.

**Comment by lacygoill** [comment]
Reduced to 17 lines of code; I don't think I can make it shorter:
```vim
vim9script
set columns=80 lines=15

def MapSave()
    for key in range(6)
        Maparg()
    endfor
enddef
def Maparg()
    let maparg = #{unmapped: true, lhs: 'x'}
    Islocal(maparg)
    Islocal(maparg)
enddef
def Islocal(maparg: any)
    echom maparg
enddef

nno <F3> :call <sid>MapSave()<cr>
feedkeys("\<F3>")
```

**Comment by brammool** [comment]
I could reproduce the crash and I think I fixed it.  I don't know how to write a test for this though, it depends on what happens on the stack.
