### ISSUE TITLE
Option for indenting

### ISSUE THREAD

**Issue by 1wsx10** [vim/vim#6704]
https://github.com/vim/vim/blob/7ac616cb0a52bc72b449e19cf9db93bee116c15a/runtime/indent/python.vim#L93

list = [
^I^I'item',
^I^I'another item'
^I^I]

is not very common. it'd be nice to have an option for something like:
list = [
^I'item',
^I'another item'
]

**Comment by 1wsx10** [comment]
maybe instead of hard-coding it as two * shiftwidth for the first level indentation, maybe let that number be configurable?
so default would be something like g:pyindent_opening_paren_shiftwidth=2

**Comment by gdupras** [comment]
There is an option for this. From `:help ft-python-indent`:

```
The amount of indent can be set for the following situations.  The examples
given are the defaults.  Note that the variables are set to an expression, so
that you can change the value of 'shiftwidth' later.

Indent after an open paren:
	let g:pyindent_open_paren = 'shiftwidth() * 2'
```

So to get the indent you want, do ```let g:pyindent_open_paren = 'shiftwidth()'```.

**Comment by chrisbra** [comment]
closing then.
