### ISSUE TITLE
Vim9: joining line starting with literal dictionary breaks the latter

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6710]
**Describe the bug**

In Vim9 script, joining a line starting with a literal dictionary breaks the latter.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        filetype plugin on
        set filetype=vim formatoptions=j
        let lines =<<trim END
            vim9script
            let l = [#{},
            #{}]
            echo l
        END
        setline(1, lines)
        :2
    EOF
    )

Press `J` to join the lines 2 and 3; the result is this line:

    let l = [#{}, {}]
                  ^
                  ✘

Notice how the `#` prefix in front of the second literal dictionary has been removed.  That's because the `j` flag is in `'formatoptions'`, and `J` has wrongly parsed `#{}` as a commented line.

**Expected behavior**

The result is this line:

    let l = [#{}, #{}]
                  ^

**Environment**

 - Vim version: 8.2 Included patches: 1-1444
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: XTerm(358)

**Additional context**

The issue has started when this line was changed in a recent update of the runtime files:
https://github.com/vim/vim/blob/bc4c505166dc82911553206bb0c2133c6ac94aa1/runtime/ftplugin/vim.vim#L52

The latter change is good; [it lets Vim correctly recognize a Vim9 commented line](https://github.com/vim/vim/issues/6403).

---

I don't know how to fix this, but I have 3 suggestions.

First suggestion: `'comments'` is upgraded so that it accepts regular expressions, and we can write this in the default Vim filetype plugin:

    comments=sO:" -,mO:"  ,sO:# -,mO:#  ,eO:##,:",:#{\@!
                                                    ^--^

I think the negative lookafter appended at the end would fix the issue.

Second suggestion: the value currently used in the Vim filetype plugin is updated to enforce a space after the `#` comment leader:
```diff
diff --git a/runtime/ftplugin/vim.vim b/runtime/ftplugin/vim.vim
index 295112297..d6c69d6d6 100644
--- a/runtime/ftplugin/vim.vim
+++ b/runtime/ftplugin/vim.vim
@@ -49,7 +49,7 @@ setlocal isk+=#
 setlocal keywordprg=:help
 
 " Set 'comments' to format dashed lists in comments
-setlocal com=sO:\"\ -,mO:\"\ \ ,sO:#\ -,mO:#\ \ ,eO:##,:\",:#
+setlocal com=sO:\"\ -,mO:\"\ \ ,sO:#\ -,mO:#\ \ ,eO:##,:\",:#\ 
 
 " Format comments to be up to 78 characters long
 if &tw == 0
```
Third suggestion: a white space after `#` is enforced at the syntax level, just like it is in other contexts (e.g. no space after the comma separating 2 items in a list raises `E1069`).  This might fix other similar issues which could arise in the future.

**Comment by lacygoill** [comment]
Actually, forget about the third suggestion; I don't think it would fix the current issue.

**Comment by brammool** [comment]
The simplest is to require white space after the #.  That also makes sense for how comments should be written.
I'll update the ftplugin to 
  setlocal com=sO:\"\ -,mO:\"\ \ ,sO:#\ -,mO:#\ \ ,eO:##,:\",b:#

**Comment by lacygoill** [comment]
There is a similar issue when joining a line starting with a double-quoted string; the opening double quote might be handled as a comment leader and wrongly removed if we've included the `j` flag in `'formatoptions'`:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9
        var lines =<< trim END
            var l = [
                "this is a string",
                "this is another string"
                ]
        END
        setline(1, lines)
        filetype plugin on
        syn on
        set ft=vim fo+=j
        feedkeys('jJ', 'xt')
    EOF
    )

I don't think there is a perfect solution, because there are several possible contexts: legacy function in Vim9 script, `:def` function in legacy script, ...

Maybe the default Vim filetype plugin should only handle the 2 most common cases: a legacy Vim script with no `:def` functions, and a Vim9 script with no legacy functions.  We can tell those 2 cases apart simply by inspecting the first line of the script (assuming there isn't a legacy comment above `:vim9script`, which seems like another corner case).

If so, here is a patch:
```diff
diff --git a/runtime/ftplugin/vim.vim b/runtime/ftplugin/vim.vim
index b87e14422..3af58e448 100644
--- a/runtime/ftplugin/vim.vim
+++ b/runtime/ftplugin/vim.vim
@@ -48,18 +48,23 @@ setlocal isk+=#
 " Use :help to lookup the keyword under the cursor with K.
 setlocal keywordprg=:help
 
-" Set 'comments' to format dashed lists in comments
-" Avoid that #{} starts a comment.
-setlocal com=sO:\"\ -,mO:\"\ \ ,sO:#\ -,mO:#\ \ ,eO:##,:\",b:#
+if getline(1) =~# '^vim9\%[script]\>'
+  " Set 'comments' to format dashed lists in comments
+  setlocal com=sO:#\ -,mO:#\ \ ,eO:##,:#
+  " Comments start with a double quote in a legacy script;
+  " with # in a Vim9 script
+  setlocal commentstring=\"%s
+else
+  setlocal com=sO:\"\ -,mO:\"\ \ ,:\"
+  setlocal commentstring=#%s
+endif
+
 
 " Format comments to be up to 78 characters long
 if &tw == 0
   setlocal tw=78
 endif
 
-" Comments start with a double quote; in Vim9 script # would also work
-setlocal commentstring=\"%s
-
 if !exists("no_plugin_maps") && !exists("no_vim_maps")
   let b:did_add_maps = 1
 
```
Note that it removes the `b` flag for the `#` comment leader, as well as this comment:

    " Avoid that #{} starts a comment.

That's because `#{}` is no longer valid in Vim9 script.  Now, `#` always start a comment; even in front of `{}`.

Also, it sets `'commentstring'` to `#%s` in a Vim9 script, because:

   - it seems to make sense
   - several popular plugins rely on `'commentstring'` to decide which comment leader they should use when implementing a commenting operator/command; if `'commentstring'` keeps the value `"%s`, they will wrongly use `"` to comment lines in a Vim9 script

**Comment by brammool** [comment]
Thanks, I'll include it and tweak it (vim9script may not appear at the start of the first line but a bit later or with preceding white apce)

**Comment by lacygoill** [comment]
Sorry, it appears I made a mistake.  For the `'commentstring'` option, I inverted the legacy comment leader with the new one, and the mistake was included in the last update of the runtime files, yesterday:

https://github.com/vim/vim/blob/64ed4d4398e92ac56a9bbd66d5ec992dd4c335f7/runtime/ftplugin/vim.vim#L54-L59

Here is a fix:
```diff
diff --git a/runtime/ftplugin/vim.vim b/runtime/ftplugin/vim.vim
index 3307de541..1a78a59c5 100644
--- a/runtime/ftplugin/vim.vim
+++ b/runtime/ftplugin/vim.vim
@@ -53,10 +53,10 @@ if "\n" .. getline(1, 10)->join("\n") =~# '\n\s*vim9\%[script]\>'
   setlocal com=sO:#\ -,mO:#\ \ ,eO:##,:#
   " Comments start with a double quote in a legacy script;
   " with # in a Vim9 script
-  setlocal commentstring=\"%s
+  setlocal commentstring=#%s
 else
   setlocal com=sO:\"\ -,mO:\"\ \ ,:\"
-  setlocal commentstring=#%s
+  setlocal commentstring=\"%s
 endif
 
 
```

**Comment by brammool** [comment]
Ah, I overlooked that.  I'll include the fix.
