### ISSUE TITLE
packpath/packages does not support pure ftplugins

### ISSUE THREAD

**Issue by leahneukirchen** [vim/vim#672]
The scanning of packpath for plugins only checks for `*.vim` files in the directory `plugin` to extend the runtimepath.

There are many plugins which only consist of a ftplugin, and will therefore be ignored.

In order to avoid having to add an empty `plugin/foo.vim` to these plugins, it would be good to extend the runtimepath also to folders which match `ftplugin/*.vim`.

**Comment by brammool** [comment]
7.4.1480 adds :packadd

Not sure if it's useful to find any non-empty directory under 'packpath'.
