### ISSUE TITLE
Vim9: cannot create a hidden terminal buffer

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6725]
**Describe the bug**

In Vim9 script, we cannot create a hidden terminal buffer.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        term_start(&shell, #{hidden: true})
    EOF
    )

`E611` is raised:

    E611: Using a Special as a Number

And the terminal buffer is displayed in a window.

**Expected behavior**

No error is raised, and the terminal buffer is not displayed in a window.

**Environment**

 - Vim version: 8.2 Included patches: 1-1471
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: XTerm(358)

**Additional context**

It's caused by a regression introduced in [8.2.1465](https://github.com/vim/vim/releases/tag/v8.2.1465).

---

`E611` is not documented.

**Comment by lacygoill** [comment]
> In Vim9 script, we cannot create a hidden terminal buffer.

Actually, we can.  We just need to avoid `true`, and use `1` instead:
```vim
vim9script
term_start(&shell, #{hidden: 1})
```
Still, we should be able to use `true`; I find it makes the code more readable.

**Comment by lacygoill** [comment]
> E611 is not documented.

The message is pretty clear by itself, but there is no help tag.

**Comment by bfrg** [comment]
The following doesn't work anymore either:
```vim
vim9script
popup_create('test...........', {'wrap': true})
```
Result:
```
E611: Using a Special as a Number
```

Vim version `8.2.1477`

**Comment by brammool** [comment]
> The following doesn't work anymore either:
> ```vim
> vim9script
> call popup_create('test...........', {'wrap': true})
> ```

I'm trying to find a balance between being backwards compatible and
being strict about the values for options.

When the value is a number, e.g. a height, then passsing "true" or
"false" is wrong.  So far that was accepted, I think it's good to start
giving an error for this.

When the value is a flag, e.g. "hidden", then passing 1234 is possibly
wrong.  But "0" and "1" are OK, as these were advertised as being the
same as "false" and "true".

At the other end of the possibilities, in a Vim9 expression we accept
many types and consider them "falsey" or not.  E.g. an empty list is
false, a non-empty list is true.  But this is where it's clear that the
expression needs to evaluate to a boolean, such as for ":if".

I tend to think that for these options it's easy to make a mistake and
use a number (or list or dict) where a boolean is expected.  And
accidentally use true/false for where a number of string is expected.
Thus I'm currently aiming at making this more strict.

Problem is that until now "get_number()" was used for both numbers and
booleans.  Thus we need to find all of the ones that are actually
booleans and change those.

-- 
hundred-and-one symptoms of being an internet addict:
231. You sprinkle Carpet Fresh on the rugs and put your vacuum cleaner
     in the front doorway permanently so it always looks like you are
     actually attempting to do something about that mess that has amassed
     since you discovered the Internet.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
