### ISSUE TITLE
VIM doesn't handle ":argdelete" according to the documentation.

### ISSUE THREAD

**Issue by ademin** [vim/vim#6726]
**Describe the bug**
In the documentation states the `:argd` command should delete
the current argument but the error occurs instead.

The documentation context (editing.txt)
```
:[range]argd[elete]	Delete the {range} files from the argument list.
			Example: 
				:10,$argdel
			Deletes arguments 10 and further, keeping 1-9. 
				:$argd
			Deletes just the last one. 
----- THIS ONE --------------->	:argd
				:.argd
			Deletes the current argument. 
				:%argd
			Removes all the files from the arglist.
			When the last number in the range is too high, up to
			the last argument is deleted.
```

**To Reproduce**
1. Run vim with argument list - `vim anyfile1.txt anyfile2.txt anyfile3.txt`
2. Do `:argd` command
3. Result: E471

**Expected behavior**
The `:argd` usage example without range & pattern specified 
should be removed from the documentation to conform with arglist-related commands.
Also, the `[range]` in the `:argd` command description should be changed to `{range}` for clarity
`:{range}argd[elete]	Delete the {range} files from the argument list.`
_Motivation:_
_It is highly probable the user might accidentally use `:argd` command 
during the intent of using the `:argd {pattern}` one._ 
_It is proposed to preserve the current behaviour of the VIM editor and fix the documentation only._
_The verbose indication of range (the current buffer) for the `:.argd` command clearly declares 
the explicit intent to delete the current argument from the argument list, therefore no accident is possible._

**Environment (please complete the following information):**
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 15 2019 23:09:16)

**Comment by k-takata** [comment]
> `:{range}argd[elete] Delete the {range} files from the argument list.`

This should be `:[range]argd[elete] Delete the [range] files from the argument list.`
(See `:help [range]`.)

**Comment by ademin** [comment]
Ranges might be declared as mandatory. (See `:helpgrep {range}`). Many commands have mandatory ranges.
Also, please note the current documentations states mandatory range in the `:argd` command description.
`Delete the {range} files from the argument list.`
**So, the documentation should be fixed.**

**Comment by ademin** [comment]
In this case, the correct behavior for `:argd` to delete the current argument and the VIM editor should be fixed.
Currently, Vim produces error **E471** in case of `:argd` command.
Looks like not a documentation bug.

**Comment by brammool** [comment]
Alexey Demin wrote:

> In this case, the correct behavior for `:argd` to delete the current
> argument and the VIM editor should be fixed.  Currently, Vim produces
> error **E471** in case of `:argd` command.
> Looks like not a documentation bug.

Many commands default to the current line, thus having ":argdel" default
to the current file makes sense.
It's unlikely that :argdel is used accidentally.
We can make it work like :.argdel.

-- 
hundred-and-one symptoms of being an internet addict:
222. You send more than 20 personal e-mails a day.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
