### ISSUE TITLE
vim9script: Still E611: Using a Special as a Number

### ISSUE THREAD

**Issue by bfrg** [vim/vim#6733]
**Describe the bug**
There are still some cases involving popup windows left that raise the error `E611: Using a Special as a Number`.

Related to #6725.

**To Reproduce**
1. Run `vim --clean -S test.vim`, with
   ```vim
   vim9script
   def Test()
       const winid = range(100)
           ->map({_, i -> string(i)})
           ->popup_create({
               'minwidth': 50,
               'maxheight': 10,
               'filter': {-> false}
           })

       win_execute(winid, 'normal! G')
   enddef
   Test()
   ```
2. Result:
   ```
   E611: Using a Special as a Number
   ```

---

3. The error disappears when `win_execute()` is removed:
   ```vim
   def Test()
       const winid = range(100)
           ->map({_, i -> string(i)})
           ->popup_create({
               'minwidth': 50,
               'maxheight': 10,
               'filter': {-> false}
           })
   enddef
   ```
4. The error also disappears when the return type of the popup-filter is changed to `number`:
   ```vim
   def Test()
       const winid = range(100)
           ->map({_, i -> string(i)})
           ->popup_create({
               'minwidth': 50,
               'maxheight': 10,
               'filter': {-> 0}
           })
   
       win_execute(winid, 'normal! G')
   enddef
   ```
5. But when the filter function returns `1`, the call of `win_execute()` seems to be ignored. I don't know if this has anything to do with the normal-mode command that is executed in the popup window:
   ```vim
   def Test()
       const winid = range(100)
           ->map({_, i -> string(i)})
           ->popup_create({
               'minwidth': 50,
               'maxheight': 10,
               'filter': {-> 1}
           })
   
       win_execute(winid, 'normal! G')
   enddef
   ```
**Expected behavior**
No errors.

**Environment**
Vim version `8.2.1479`

**Comment by brammool** [comment]
> **Describe the bug**
> There are still some cases involving popup windows left that raise the error `E611: Using a Special as a Number`.
> 
> Related to #6725.
> 
> **To Reproduce**
> 1. Run `vim --clean -S test.vim`, with
>    ```vim
>    vim9script
>    def Test()
>        const winid = range(100)
>            ->map({_, i -> string(i)})
>            ->popup_create({
>                'minwidth': 50,
>                'maxheight': 10,
>                'filter': {-> false}
>            })
> 
>        win_execute(winid, 'normal! G')
>    enddef
>    Test()
>    ```
> 2. Result:
>    ```
>    E611: Using a Special as a Number
>    ```
> 
> ---
> 
> 3. The error disappears when `win_execute()` is removed:
>    ```vim
>    def Test()
>        const winid = range(100)
>            ->map({_, i -> string(i)})
>            ->popup_create({
>                'minwidth': 50,
>                'maxheight': 10,
>                'filter': {-> false}
>            })
>    enddef
>    ```

That's because the filter is not invoked.

> 4. The error also disappears when the return type of the popup-filter is changed to `number`:
>    ```vim
>    def Test()
>        const winid = range(100)
>            ->map({_, i -> string(i)})
>            ->popup_create({
>                'minwidth': 50,
>                'maxheight': 10,
>                'filter': {-> 0}
>            })
>    
>        win_execute(winid, 'normal! G')
>    enddef
>    ```

Yes, that's where the problem is.

> 5. But when the filter function returns `1`, the call of `win_execute()` seems to be ignored. I don't know if this has anything to do with the normal-mode command that is executed in the popup window:
>    ```vim
>    def Test()
>        const winid = range(100)
>            ->map({_, i -> string(i)})
>            ->popup_create({
>                'minwidth': 50,
>                'maxheight': 10,
>                'filter': {-> 1}
>            })
>    
>        win_execute(winid, 'normal! G')
>    enddef
>    ```

The filter consumes all the typeahead.

-- 
hundred-and-one symptoms of being an internet addict:
238. You think faxes are old-fashioned.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
