### ISSUE TITLE
Valid C++ syntax "m[{1,1}]" is flagged with red

### ISSUE THREAD

**Issue by yurivict** [vim/vim#6741]
This is a valid C++ code:
```
#include <map>
#include <tuple>

void f() {
        std::map<std::tuple<int,int>,int> m;
        m[{1,1}] = 1;
}
```

Yet, vim-8.2.1382 flags the curly braces:
![image](https://user-images.githubusercontent.com/271906/90666307-06326780-e202-11ea-8cce-7947a2cd2045.png)

**Comment by bfrg** [comment]
You need to set `let c_no_curly_error = 1` in your `vimrc`. See `:help ft-c-syntax`.

**Comment by yurivict** [comment]
Shouldn't this be set automatically for C++ files?

**Comment by brammool** [comment]
C++ is close to impossible to parse correctly, anything that wasn't an error in the previous version is made to do something meaningful in the next version, it seems. This will continue until any random sequence of characters is meaningful C++ code :-).
 I used to know C++ but don't quite understand your example.  Is {1,1} a tuple literal?

The syntax file was made to highlight the most obvious errors.
You an disable highlighting curly errors, but then Vim won't highlight unpatched "}".  It's up to the user to decide what is preferred.

**Comment by yurivict** [comment]
> Is {1,1} a tuple literal?

{1,1} is ```aggregate initialization```, see https://en.cppreference.com/w/cpp/language/aggregate_initialization

Every syntactic element of C++ is documented in https://en.cppreference.com
