### ISSUE TITLE
Netrw: Incorrect command description states in the documentation for changing the current directory

### ISSUE THREAD

**Issue by ademin** [vim/vim#6745]
**Describe the bug**
According to the Netrw documentation `cd` should be used for changing the current directory:
```
*netrw-c* : This map's name has been changed from "c" to cd (see |netrw-cd|).
          This change was done to allow for |netrw-cb| and |netrw-cB| maps.
```
But `c` is used in the `QUICK REFERENCE` 

**To Reproduce**
1. Run `:help netrw-quickmaps`
2. Look at the command for `Make browsing directory the current directory` description

**Expected behavior**
`cd` is the map for changing the current directory

**Environment (please complete the following information):**
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 15 2019 23:09:16)
*pi_netrw.txt*  For Vim version 8.2.  Last change: 2019 Dec 10

**Comment by ademin** [comment]
Looks like `*pi_netrw.txt*  For Vim version 8.2.  Last change: 2020 Jun 07` has already fixed the issue.

**Comment by chrisbra** [comment]
so it can be closed.
