### ISSUE TITLE
Vim9: cannot use / Ex command in :def function

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6747]
**Describe the bug**

In Vim9 script, we cannot use a `/` Ex command in a `:def` function.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            append('$', 'pat')
            :/pat/
        enddef
        Func()
    EOF
    )

`E476` is raised:

    E476: Invalid command:

**Expected behavior**

No error is raised.  The cursor is moved on the next line where `pat` matches.

**Environment**

 - Vim version: 8.2 Included patches: 1-1490
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: XTerm(358)

**Additional context**

It's a regression introduced in [8.2.1156](https://github.com/vim/vim/releases/tag/v8.2.1156).

---

The issue disappears in a legacy function:
```vim
vim9script
fu Func()
    call append('$', 'pat')
    :/pat/
endfu
Func()
```
---

The issue also disappears at the script level:
```vim
vim9script
append('$', 'pat')
:/pat/
```
If for some reason it can't work in a `:def` function, then – to be consistent – I think it should also fail at the script level.

---

As a workaround, `search()` can be invoked:
```vim
vim9script
append('$', 'pat')
search('pat')
```
---

The code where I found this looked like this:
```vim
:sil! keepj keepp 1;/^# \%(Changes\|Untracked files\)/
```

**Comment by lacygoill** [comment]
I had a look at the patch 8.2.1156, and noticed [this line](https://github.com/vim/vim/blob/93ad14710bdf77591f927a2b244bba6a8cbc7706/src/testdir/test_vim9_expr.vim#L2328) in a test:

    call CheckDefFailure(["CallMe ('yes')"], 'E476:')

I think its purpose is to make sure that white space is disallowed between a function name and the open parenthesis in a function call.

This reminded me that this rule was enforced in a `:def` function, but not at the script level (issue #6496).  Similarly, no error is raised for missing white space after a comma in a dictionary in a `:def` function (issue #6672).

**Comment by brammool** [comment]
> I had a look at the patch 8.2.1156, and noticed [this line](https://github.com/vim/vim/blob/93ad14710bdf77591f927a2b244bba6a8cbc7706/src/testdir/test_vim9_expr.vim#L2328) in a test:
> 
>     call CheckDefFailure(["CallMe ('yes')"], 'E476:')
> 
> I think its purpose is to make sure that white space is disallowed
> between a function name and the open parenthesis in a function call.
> 
> This reminded me that this rule was enforced in a `:def` function, but
> not at the script level (issue #6496).  Similarly, no error is raised
> for missing white space after a comma in a dictionary in a `:def`
> function (issue #6672).

At some point all the tests done for Vim9 syntax should be done both for
use in a :def function and at the script level.  Not there yet...

-- 
hundred-and-one symptoms of being an internet addict:
259. When you enter your name in the AltaVista search engine, the top ten
     matches do indeed refer to you.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
