### ISSUE TITLE
running a `make clean` deletes parent directory and everything in it

### ISSUE THREAD

**Issue by mladenivkovic** [vim/vim#6751]
**Describe the bug**
Initially, I wanted to update my vim version. So I first ran a `make clean` in the root directory, which promptly deleted the root's parent directory and everything in it, which is causing me massive trouble right now. To be precise: I had the repo stored in `~/local/vim`, and after running `make clean` in that directory, it deleted the entire `~/local` dir.

The same thing happens when running a `make clean` from a freshly pulled repo on the master branch.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. clone the current master
2. go into the vim directory
3. run `make clean` 
4. cry

**Expected behavior**
removal of compiled objects for a fresh install

**Screenshots**
The output of `make clean` is
```
$ make clean
Starting make in the src directory.
If there are problems, cd to the src directory and run make there
cd src && make clean
make[1]: Entering directory '/home/mivkov/local/vim/src'
cd testdir; make -f Makefile clean
make[2]: Entering directory '/home/mivkov/local/vim/src/testdir'
rm -rf *.out *.failed *.res *.rej *.orig XfakeHOME Xdir1 Xfind
rm -f opt_test.vim test.log test_result.log messages
rm -f test.out X* viminfo test.ok benchmark.out
rm -f valgrind.*
rm -f asan.*
make[2]: Leaving directory '/home/mivkov/local/vim/src/testdir'
if test -d po; then \
	cd po; make checkclean; \
fi
make[2]: Entering directory '/home/mivkov/local/vim/src/po'
rm -f *.ck
make[2]: Leaving directory '/home/mivkov/local/vim/src/po'
rm -f *.o core vim.core vim vim xxd/*.o
rm -rf objects
rm -f xxd/xxd auto/osdef.h auto/pathdef.c auto/if_perl.c auto/gui_gtk_gresources.c auto/gui_gtk_gresources.h auto/os_haiku.rdef
rm -f conftest* *~ auto/link.sed
rm -f testdir/opt_test.vim
rm -f json_test kword_test memfile_test message_test
rm -f runtime pixmaps
rm -rf /home/mivkov/local
rm -rf mzscheme_base.c
rm -rf libvterm/.libs libterm/t/.libs libvterm/src/*.o libvterm/src/*.lo libvterm/t/*.o libvterm/t/*.lo libvterm/t/harness libvterm/libvterm.la
sh: 0: getcwd() failed: No such file or directory
if test -d po; then \
	cd po; make prefix= clean; \
fi
sh: 0: getcwd() failed: No such file or directory
make[1]: Leaving directory '/home/mivkov/local/vim/src'
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
/bin/sh: 2: cd: can't cd to runtime/indent
Makefile:36: recipe for target 'clean' failed
make: *** [clean] Error 2
```

**Environment (please complete the following information):**
 - Vim version: current master
 - OS:Ubuntu 18.04,
 - Terminal:GNOME Terminal

**Comment by chrisbra** [comment]
that is strange and it never happened to me on my system. What shell is this? Anything unusual in your setup?

**Comment by jottkaerr** [comment]
The culprit is
```
rm -rf /home/mivkov/local
```
which is the expansion of
```
	-rm -rf $(APPDIR)
```
in the Makefile. I didn't find a place where the APPDIR variable was set in a Makefile and I don't know if this is a special environment variable on your system. Is APPDIR define as an environment variable?

**Comment by k-takata** [comment]
Oh, that was removed in 8.2.1422.

**Comment by mladenivkovic** [comment]
Indeed, I set `APPDIR` to `/home/mivkov/local` in my `.bashrc` for my own purposes

**Comment by jottkaerr** [comment]
There are still 12 references to `$(APPDIR)` in src/Makefile. Should they and their dependencies be removed?

**Comment by brammool** [comment]
One of the disadvantages of the Makefile picking up random environment variables...
I'll delete that cleanup line, I'll ask if we can delete the whole section that is using $APPDIR.
Sorry you lost your files!
