### ISSUE TITLE
Two more corrections to the docs

### ISSUE THREAD

**Issue by lkintact** [vim/vim#6753]
In `doc/various.txt`:
1. The sentence in lines 147-150,

_If there is a {count}, that's how many lines you'll see; `if` there is only one window then twice the value of the 'scroll' option is used, otherwise the current window height minus 3 is used._

should probably be extended for better understanding about this way:

_If there is a {count}, that's how many lines you'll see; `if there's no {count} and` there is only one window then twice the value of the 'scroll' option is used, otherwise the current window height minus 3 is used._

2. The term _punctuation marks_ in line 156 should probably be replaced with something like "symbols" or just "marks" as `+`, `^` and `=` (afaik) aren't punctuation marks.

Vim 8.2.1490.

**Comment by brammool** [comment]
> In `doc/various.txt`:
> 1. The sentence in lines 147-150,
> 
> _If there is a {count}, that's how many lines you'll see; `if` there is only one window then twice the value of the 'scroll' option is used, otherwise the current window height minus 3 is used._
> 
> should probably be extended for better understanding about this way:
> 
> _If there is a {count}, that's how many lines you'll see; `if there's no {count} and` there is only one window then twice the value of the 'scroll' option is used, otherwise the current window height minus 3 is used._

You mean to insert "no {count}".  Yes, that makes it clearer.
 
> 2. The term _punctuation marks_ in line 156 should probably be
> replaced with something like "symbols" or just "marks" as `+`, `^` and
> `=` (afaik) aren't punctuation marks.

Just "mark" should work and is simpler.

Thanks!

-- 
hundred-and-one symptoms of being an internet addict:
250. You've given up the search for the "perfect woman" and instead,
     sit in front of the PC until you're just too tired to care.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lkintact** [comment]
> You mean to insert "no {count}".  Yes, that makes it clearer.

> Just "mark" should work and is simpler.

Yes, I meant adding "no {count}". Thanks for replying, please close the issue when you don't need it open anymore.
