### ISSUE TITLE
Unwanted interaction between `set cedit=^H` and `:cabbrev`

### ISSUE THREAD

**Issue by rafikdraoui** [vim/vim#6755]
When setting `'cedit'` to Ctrl-H and defining a command-line abbreviation, entering the abbreviated form will open the command-line window instead of expanding the abbreviation.

This might have something to do with Ctrl-H being a special character equivalent to `<bs>` in terminals, and as such not something that can easily be fixed from inside Vim. If that's the case, feel free to close the issue, as I don't rely on this use case. But I thought I would still mention it here as a curiosity!

**To Reproduce (1)**

1. Run `vim --clean -c 'cabbrev Q! q!' -c 'let &cedit="\<c-h>"'`
2. Type `:Q!<cr>` or `:Q!<space>`
3. The command-line window is displayed, with `Q!` on the line

Expected behavior: quitting  vim in the first case, `Q!` to be expanded to `q!` in the second case.

**To Reproduce (2)**

1. Run `vim --clean -c 'cabbrev Q! quit!' -c 'let &cedit="\<c-h>"'`
2. Type `:Q!<space>`
3. The command-line window is displayed, with `Qt! !` on the line, while being in insert mode and recording `@u`.

Expected behavior: `Q!` to be expanded to `quit!`

**To Reproduce (3)**

1. Run `vim --clean -c 'cabbrev Q! quit!' -c 'let &cedit="\<c-h>"'`
2. Type `:Q!<cr>`
3. `E492: Not an editor command: Qt!!`, and `@u` is being recorded.

Expected behavior: quitting Vim

**Environment:**
 - Vim version: 8.2.814
 - OS: Arch Linux, macOS 10.15.5
 - Terminal: kitty, macOS Terminal, xterm

**Additional context**

Using another key for `'cedit'` doesn't have this problem. For example, with `vim --clean -c 'cabbrev Q! quit!' -c 'let &cedit="\<c-g>"'` things work fine.

**Comment by chrisbra** [comment]
>  Ctrl-H being a special character equivalent to <bs>

yes CTRL-H is basically the same as backspace according to the Ascii definition so Vim cannot distinguish it (except for modifyotherkeys in xterm). Now, I don't actually know when the backspace comes into play when processing your abbreviation. So let's close it.
