### ISSUE TITLE
Vim9: cannot assign value to script-local variable from autocmd

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6758]
**Describe the bug**

In Vim9 script, sometimes, we cannot assign a value to a script-local variable from an autocmd.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        let s:var = 0
        def s:Func()
            s:var = 12
            au CursorHold * s:var = 34 | echom s:var
            do CursorHold
        enddef
        call s:Func()
    EOF
    )

This error message is printed:

    check_script_var_type(): not found

**Expected behavior**

No error is printed.  The value of `s:var` is reset to `34`, and `34` is printed.

**Environment**

 - Vim version: 8.2 Included patches: 1-1500
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: XTerm(358)

**Additional context**

Regression introduced in patch [8.2.0973](https://github.com/vim/vim/releases/tag/v8.2.0973).

---

The issue disappears when the script is refactored from a legacy script into a Vim9 script:
```vim
vim9script
let var = 0
def Func()
    s:var = 12
    au CursorHold * var = 34 | echom var
    do CursorHold
enddef
Func()
```

**Comment by lacygoill** [comment]
Actually, I'm not sure it's a bug.

An autocmd runs in the context of the script where it's defined.  Here, the autocmd is defined in a legacy script.  But in legacy Vim script, I don't think there is a type checking like in Vim9...

I thought that maybe the issue was that the variable was defined in the legacy context, then reset in a Vim9 context.  But I get the same error when the variable is set *and* reset in the legacy context:
```vim
let s:var = 0
def s:Func()
    au CursorHold * s:var = 34 | echom s:var
enddef
call s:Func()
do CursorHold
```
Notice that `s:var` is set at the script level:

    let s:var = 0

and reset from the script level too:

    do CursorHold

Unless it doesn't matter from which context `:doautocmd` is *run*.  Maybe what matters is from which context the autocmd is *installed*.  If it's working as intended, maybe it could be mentioned at `:h vim9-gotchas`.

**Comment by lacygoill** [comment]
> Here, the autocmd is defined in a legacy script. 

Ah no, it's defined in a `:def` function, thus from a Vim9 context.

Sorry, I'm a bit confused by all of the parameters which can influence the result.

**Comment by lacygoill** [comment]
The script can be legacy or Vim9: 2 possibilities.
The autocmd can be installed at the script level, from a legacy function, or from a Vim9 function: 3 possibilities.
The autocmd can be triggered at the script level, from a legacy function, or from a Vim9 function: 3 possibilities.

That's 18 possibilities in total (2 x 3 x 3).

Snippet ID: 111
```vim
let s:var = 0
au CursorHold * let s:var = 34 | echom s:var
do CursorHold
```
    34

Snippet ID: 112
```vim
let s:var = 0
au CursorHold * let s:var = 34 | echom s:var
fu Run()
    do CursorHold
endfu
call Run()
```
    34

Snippet ID: 113
```vim
let s:var = 0
au CursorHold * let s:var = 34 | echom s:var
def s:Run()
    do CursorHold
enddef
call s:Run()
```
    34

Snippet ID: 121
```vim
let s:var = 0
fu Install()
    au CursorHold * let s:var = 34 | echom s:var
endfu
call Install()
do CursorHold
```
    34

Snippet ID: 122
```vim
let s:var = 0
fu Install()
    au CursorHold * let s:var = 34 | echom s:var
endfu
call Install()
fu Run()
    do CursorHold
endfu
call Run()
```
    34

Snippet ID: 123
```vim
let s:var = 0
fu Install()
    au CursorHold * let s:var = 34 | echom s:var
endfu
call Install()
def s:Run()
    do CursorHold
enddef
call s:Run()
```
    34

Snippet ID: 131
```vim
let s:var = 0
def Install()
    au CursorHold * var = 34 | echom var
enddef
call Install()
do CursorHold
```
    check_script_var_type(): not found

Snippet ID: 132
```vim
let s:var = 0
def Install()
    au CursorHold * var = 34 | echom var
enddef
call Install()
fu Run()
    do CursorHold
endfu
call Run()
```
    check_script_var_type(): not found

Snippet ID: 133
```vim
let s:var = 0
def Install()
    au CursorHold * var = 34 | echom var
enddef
call Install()
def s:Run()
    do CursorHold
enddef
call s:Run()
```
    check_script_var_type(): not found

Snippet ID: 211
```vim
vim9script
let var = 0
au CursorHold * var = 34 | echom var
do CursorHold
```
    34

Snippet ID: 212
```vim
vim9script
let var = 0
au CursorHold * var = 34 | echom var
fu Run()
    do CursorHold
endfu
Run()
```
    34

Snippet ID: 213
```vim
vim9script
let var = 0
au CursorHold * var = 34 | echom var
def Run()
    do CursorHold
enddef
Run()
```
    34

Snippet ID: 221
```vim
vim9script
let var = 0
fu Install()
    au CursorHold * let s:var = 34 | echom s:var
endfu
Install()
do CursorHold
```
    34

Snippet ID: 222
```vim
vim9script
let var = 0
fu Install()
    au CursorHold * let s:var = 34 | echom s:var
endfu
Install()
fu Run()
    do CursorHold
endfu
Run()
```
    34

Snippet ID: 223
```vim
vim9script
let var = 0
fu Install()
    au CursorHold * let s:var = 34 | echom s:var
endfu
Install()
def Run()
    do CursorHold
enddef
Run()
```
    34

Snippet ID: 231
```vim
vim9script
let var = 0
def Install()
    au CursorHold * var = 34 | echom var
enddef
Install()
do CursorHold
```
    34

Snippet ID: 232
```vim
vim9script
let var = 0
def Install()
    au CursorHold * var = 34 | echom var
enddef
Install()
fu Run()
    do CursorHold
endfu
Run()
```
    34

Snippet ID: 233
```vim
vim9script
let var = 0
def Install()
    au CursorHold * var = 34 | echom var
enddef
Install()
def Run()
    do CursorHold
enddef
Run()
```
    34

---

Note that the error is raised only for the snippets whose IDs are `131`, `132` and `133`.  They have in common the prefix `13`, which means that the error only occurs when:

   - the script is in legacy Vim script
   - the autocmd is installed from a Vim9 function

It doesn't matter from which context the autocmd is run; and there's no issue in a Vim9 script, regardless of the context from which the autocmd is installed or run.

**Comment by lacygoill** [comment]
> Maybe what matters is from which context the autocmd is installed.

Yes, I think that's what matters.
```vim
vim9script
fu Install()
    au CursorHold * echom 'x' is# 'x'
endfu
Install()
def Run()
    do CursorHold
enddef
Run()
```
    1

Here, no error is raised, even though we're in a Vim9 script, and the autocmd is run from a Vim9 function.  If the autocmd was run in the Vim9 context, an error would have been raised because `is#` is disallowed in Vim9 script; thus, it was run in the legacy context; that's because the autocmd was installed from a legacy function.

**Comment by lacygoill** [comment]
Also, the issue might be related to these todo items:
https://github.com/vim/vim/blob/5d72ce69c8783fd8f1a0355c00806c5084010eec/runtime/doc/todo.txt#L55
https://github.com/vim/vim/blob/5d72ce69c8783fd8f1a0355c00806c5084010eec/runtime/doc/todo.txt#L63-L65

**Comment by brammool** [comment]
> Actually, I'm not sure it's a bug.
> 
> An autocmd runs in the context of the script where it's defined.
> Here, the autocmd is defined in a legacy script.  But in legacy Vim
> script, I don't think there is a type checking like in Vim9...
> 
> I thought that maybe the issue was that the variable was defined in
> the legacy context, then reset in a Vim9 context.  But I get the same
> error when the variable is set *and* reset in the legacy context:
> ```vim
> let s:var = 0
> def s:Func()
>     au CursorHold * s:var = 34 | echom s:var
> enddef
> call s:Func()
> do CursorHold
> ```
> Notice that `s:var` is set at the script level:
> 
>     let s:var = 0
> 
> and reset from the script level too:
> 
>     do CursorHold
> 
> Unless it doesn't matter from which context `:doautocmd` is *run*.
> Maybe what matters is from which context the autocmd is *installed*.
> If it's working as intended, maybe it could be mentioned at `:h
> vim9-gotchas`.

An autocommand runs in the script context where it was defined.
When it was defined in a Vim9 script or in a :def function, then Vim9
syntax is used.

Defining an autocommand in a :def function in a legacy script is a
corner case.  Obviously no type checking can be done, thus this specific
error can be avoided by checking the script where it is defined.
There might be a few other problems, we'll need to do a lot of testing
to find them.

I'll add a remark in the help that Vim9 syntax also applies to
autocommands, if they are defined where Vim9 syntax is used.


-- 
hundred-and-one symptoms of being an internet addict:
258. When you want to see your girlfriend, you surf to her homepage.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
