### ISSUE TITLE
Multibyte characters are split when pasting in visual block mode

### ISSUE THREAD

**Issue by geryogam** [vim/vim#6767]
**Description**
The non first-bytes of multibyte characters on the left of a selected block in visual block mode are moved on the right of the selected block when pasting.

**To reproduce**
1. Run `vim --clean`.
2. Type this in a buffer (here I use é as the multibyte character, that is U+00E9 latin small letter e with acute):

```
xxxxx
yéyyy
zzzzz
```

3. Copy any sequence of characters, e.g. `xx` (move the cursor to line 1, column 3 and type `vly`).
4. Switch to visual block mode (type `<C-v>`).
5. Select a block of text whose top-left corner strictly precedes the line 2 and strictly follows the column 2 of the multibyte character, e.g. line 1, column 3, and whose bottom-right corner follows the line 2 and follows the column 2 of the multibyte character, e.g. line 3, column 4 (type `ljj`):

```
xx|xx|x
yé|yy|y
zz|zz|z
```

6. Paste (type `p`).

**Actual behavior**

```
xxxxx
y<c3>xx<a9>y
zzxxz
```

The UTF-8 encoding of é is C3 A9 in hexadecimal, so it seems that the non first-bytes (A9) are moved on the right of the selected block.

**Expected behavior**

```
xxxxx
yéxxy
zzxxz
```

**Environment**

 - Vim: 8.2.1456.

```
:echo $LANG
fr_FR.UTF-8
:echo &encoding
utf-8
:echo &fileencoding

:echo &fileencodings
ucs-bom,utf-8,default,latin1
```

 - O.S.: macOS 10.14.
 - Interface: both GUI and TUI (Terminal).

**Comment by tonymec** [comment]
Strange.

I cannot reproduce the problem on Vim 8.2.1505 on Linux, neither in xterm nor in gvim. After yanking and putting I get

xxxxxx
y∞yyyy
zzzzzz

Best regards,
Tony.

**Comment by gdupras** [comment]
I can reproduce it with Vim 8.1.2269 on Linux, in Konsole. I think it has something to do with multibyte characters. For example, replacing ∞ with π:

```
xxxx
yπyy
zzzz
```
becomes
```
xxxx
y<cf>xx<80>
zzxx
```

**Comment by chrisbra** [comment]
What is your encoding setting?

**Comment by brammool** [comment]
I also cannot reproduce.  Please specify exactly what you do, what commands you type.
Start Vim with "vim --clean" to exclude any plugins.

**Comment by gdupras** [comment]
With this in a buffer, with the cursor on line 1, column 3:
```
xxxx
y∞yy
zzzz
```
Do:
```
vly<C-v>jjlp
```
As for my encoding:
```
:echo &encoding
utf-8
:echo &fileencoding

:echo &fileencodings
ucs-bom,utf-8,default,latin1
```

**Comment by k-takata** [comment]
What is your locale? What does `:echo $LANG` and `:lang` show?

**Comment by gdupras** [comment]
```
:echo $LANG
en_CA.UTF-8

:lang
Langue courante pour  : "LC_CTYPE=en_CA.UTF-8;LC_NUMERIC=C;LC_TIME=en_CA.UTF-8;LC_COLLATE=en_CA.UTF-8;LC_MONETARY=en_CA.UTF-8;LC_MESSAGES=en_CA.UTF-8;LC_PAPER=en_CA.UTF-8;LC_NAME=en_CA.UTF-8;LC_ADDRESS=en_CA.UTF-8;LC_TELEPHONE=en_CA.UTF-8;LC_MEASUREMENT=en_CA.UTF-8;LC_IDENTIFICATION=en_CA.UTF-8"
```

Edit:
I switched the local of my computer to the default and rebooted. I still get the same bug. I had to switch `'encoding'` in Vim from latin1 to utf-8 otherwise I couldn't even type ∞.

```
:echo $LANG
C

:lang
Current language: "C"
```

**Comment by geryogam** [comment]
> I also cannot reproduce. Please specify exactly what you do, what commands you type.
> Start Vim with "vim --clean" to exclude any plugins.

I have updated my post. `vim --clean` does not change the outcome. And like @ProgMetalSlug noted, this issue affects all multibyte characters (like French é, è, à, etc.). More precisely, I have realized that the non first-bytes of multibyte characters on the left of a selected block in visual block mode are moved on the right of the selected block when pasting.

**Comment by brammool** [comment]
Following your instructions, I get:
xxxx
xxyy
xxzz
Which appears to be OK.  Perhaps before "vl" your cursor is not in the first line, first column?

**Comment by brammool** [comment]
ah, I can reproduce first moving the cursor to the first line, third column

**Comment by geryogam** [comment]
> ah, I can reproduce first moving the cursor to the first line, third column

Yes you have to select a text block so that the multibyte character is on the left of the text block. After pasting the multibyte character gets split: its first byte remains on the left of the text block (as expected), but its remaining bytes are moved to the right of the text block. In other words, text block selection behaves as if the remaining bytes are on the right of the text block instead of the left. It seems that the text block selection algorithm that Vim uses works at the byte level instead of the character level.

**Comment by geryogam** [comment]
Thanks for the patch @brammool!
