### ISSUE TITLE
Vim9: allowing to define a script-local variable in a ":def" function in a legacy script is confusing

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6771]
**Describe the bug**

In Vim9 script, it is confusing to allow the definition of a script-local variable in a `:def` function in a legacy script.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        def Func()
            s:var = 123
            echo s:var
        enddef
        call Func()
    EOF
    )

No error is raised.

**Expected behavior**

`E1089` is raised:

    E1089: unknown variable: s:var

**Environment**

 - Vim version: 8.2 Included patches: 1-1505
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: XTerm(358)

**Additional context**

I'm not sure it's a bug.  Maybe Vim9's current implementation explains this behavior.  But from the user's point of view, I think it's still confusing.  Because in a Vim9 script, the exact same code would raise an error:
```vim
vim9script
def Func()
    s:var = 123
    echo s:var
enddef
Func()
```
    E1089: unknown variable: s:var

One explanation could be that – since we're in a legacy script – the restrictions specific to a Vim9 script do not apply.  But if that's the case, then why does the exact same code raise an error, when we define the variable with `:let`:
```vim
def Func()
    let s:var = 123
    echo s:var
enddef
call Func()
```
    E1101: Cannot declare a script variable in a function: s:var

If a legacy script makes Vim ignore `E1089` when `:let` is omitted, then I would expect Vim to also ignore `E1101` when `:let` is not omitted.

---

There is another benefit of disallowing the definition of a script-local variable in a `:def` function in a legacy script.  It would automatically fix yet another inconsistency.

We can omit the `s:` prefix if the variable is defined at the script level (which is consistent with a Vim9 script):
```vim
let s:var = 123
def Func()
    echo var
enddef
call Func()
```
    123

And we can also omit `s:` if the variable is defined in a legacy function:
```vim
fu Legacy()
    let s:var = 123
endfu
call Legacy()
def Func()
    echo var
enddef
call Func()
```
    123

But we can *not* omit `s:` if the variable is defined in a `:def` function (which is inconsistent with a Vim9 script; although, in a Vim9 script, we cannot define a script-local variable in a `:def` function, so this *other* inconsistency can't be observed in practice):
```vim
def Func()
    s:var = 123
    echo var
enddef
call Func()
```
    E1001: variable not found: var
```vim
def Func()
    s:var = 123
    echo s:var
enddef
call Func()
```
    123

The fact that `s:` can sometimes be omitted but not always is inconsistent in itself.

If it is disallowed to define a script-local variable in a `:def` function in a legacy script, then the last case becomes irrelevant, and there is no longer any inconsistency.

---

If we can't or don't want to disallow it, then I think it should be documented at `:h :def`:
https://github.com/vim/vim/blob/1b04ce2d400fda97410a961288c496bd8f445a9c/runtime/doc/vim9.txt#L538-L542

Maybe this sentence could be added at the end of the paragraph:

   > They **can** be defined in the function.

It would echo one of the previous sentences:

   > They **must** be defined before the function is compiled.
```diff
diff --git a/runtime/doc/vim9.txt b/runtime/doc/vim9.txt
index fa7febc4c..e49b58b36 100644
--- a/runtime/doc/vim9.txt
+++ b/runtime/doc/vim9.txt
@@ -539,7 +539,7 @@ If the script the function is defined in is Vim9 script, then script-local
 variables can be accessed without the "s:" prefix.  They must be defined
 before the function is compiled.  If the script the function is defined in is
 legacy script, then script-local variables must be accessed with the "s:"
-prefix.
+prefix.  They can be defined in the function.
 
 						*:defc* *:defcompile*
 :defc[ompile]		Compile functions defined in the current script that
```

**Comment by brammool** [comment]
A script-local variable in legacy Vim script largely behaves like a global variable. Only that the scope is different.
It can be created any moment and deleted any moment.  It does not have a specific type.
In a compiled function s:var and g:var can be used.  When using "var" it may refer to a variable in the script.
For Vim9 script the variable must have been declared and cannot be deleted.  That allows for accessing it by index and checking the type.
In legacy script we cannot know if the s:var variable exists at compile time or at runtime.  When using "var" we can check if it exists at compile time, but that doesn't guarantee it exists at runtime.
This unavoidably results in some inconsistencies.  It's not easy to decide what works best.

Perhaps when using "var" in a compiled function, it cannot refer to a script-local variable in legacy script, only in Vim9 script?
It probably makes sense that in a compiled function using "var" always refers to a declared variable with a known type.

**Comment by lacygoill** [comment]
> It can be created any moment and deleted any moment.

While it's true that it can be created at any moment, it can't be deleted at any moment.  It can be deleted at the script level:
```vim
let s:var = 123
unlet s:var
```
But not in a `:def` function:
```vim
def Func()
    s:var = 123
    unlet s:var
enddef
call Func()
```
    E1081: Cannot unlet s:var

In contrast, we can delete a global variable in a `:def` function in a legacy script:
```vim
def Func()
    g:var = 123
    unlet g:var
enddef
call Func()
```
---

Also, the patch made the design more consistent, but only for variables, not for functions.  That is, we can no longer omit `s:` for variable names, but we can for function names:
```vim
def s:ScriptLocalDef(): number
    return 123
enddef
def Func()
    echo ScriptLocalDef()
enddef
call Func()
```
    123
```vim
fu s:ScriptLocalFu()
    return 123
endfu
def Func()
    echo ScriptLocalFu()
enddef
call Func()
```
    123

I don't know what's best.  On the one hand, it's convenient to be able to omit `s:` for function names.  On the other hand, it's inconsistent with variable names.

**Comment by brammool** [comment]
Since a legacy-script variable can be created, it should also be possible to delete it.  I'll make that work.

Functions are different.  A global function can also be found without the g: prefix:

```
def g:GlobalDef(): number
    return 123
enddef
def Func()
    echo GlobalDef()
enddef
call Func()
```

Thus it's consistent between s:Func and g:Func.  It was always like this, and I don't think it needs to be different in a ;def function.
