### ISSUE TITLE
gtk3vim: unusual cursor jump in visual mode with set ruler

### ISSUE THREAD

**Issue by luchr** [vim/vim#678]
Hello,

thank you again for the GTK3 support of vim. 

I found one annoying issue with a "jumping" cursor (Version 7.4.1498):
1. Start gtk3vim with `gtk3vim -u NONE -U NONE -i NONE`
2. turn on rulers with `:set ru`
3. insert some text in the first line, leave insert mode and go to the first character (key `0`)
4. go to visual mode (key `v`) and mark the text (key `$`), now press key `h`

Expected behavior: cursor moves one character to the left (decreasing the visual selection block size)
seen behavior: cursor moves one to the _right_ and then jumps 2 characters to the left.
If you keep `h` pressed then you can see the annoying effect better.

If my description of the problem is too bad: Here is a movie: [mp4 movie](https://gist.github.com/luchr/078f452e57785501e402)

**Comment by nuko8** [comment]
Thank you for the report.

The phenomenon itself has also been seen with the GTK2 GUI and now becomes more noticeable with the GTK3 GUI.

I'll look into the issue and try to offer a better user experience with the new GUI, but I'm afraid it's a little bit tough to fix because the corresponding code is shared in common with both GTK2 and GTK3 GUIs. 

So please understand I can't promise you that the issue will soon be fixed.

**Comment by luchr** [comment]
Thank you for having a look at the issue.

In GTK2 this phenomenon seems to be below my perception possibilities.

**Comment by nuko8** [comment]
> In GTK2 this phenomenon seems to be below my perception possibilities.
> 
> seen behavior: cursor moves one to the _right_ and then jumps 2 characters to the left.'

What actually happens is this: When `h` is pressed, the selection area shrinks to the left while the cursor image is kept at the position before the key is pressed; then the cursor image is erased and the cursor is newly drawn at the expected position.

It looks that some people observe that whole movement as if the cursor moved to the right first and then jumped over 2 columns to the left, though the cursor update code is written in such a way that the cursor moves as described above.  Perhaps, how it looks depends on individuals.

**Comment by luchr** [comment]
Unfortunately I cannot confirm this description. Here is the "slow motion". In the figure in the middle the ruler-position is correctly decreased, but the cursor moves to the right.

![gtk3vim_slowmo](https://cloud.githubusercontent.com/assets/7441996/13580894/85bc2dac-e4a4-11e5-97fe-e958e9f1661f.png)

**Comment by nuko8** [comment]
I see.

Then the issue is much tougher than I expected.  I described the motion based on the GUI code.  But in reality code relevant to cursor update scatters in non-GUI code, too (Basically, the GUI text window is drawn by a sequence of commands which are mostly the same as those sent to a terminal to draw Vim on the terminal window).

So I have to spot the cause of the problem among a few 10k lines of code I've never touched, check and modify relevant code, build both gtk2 and gtk3 gui and make sure that they work as they did and that the issue is fixed (repeat this if the obtained result is unsatisfactory).  I hope you know what I mean :)

And considering the nature of the issue, the priority is not high because it doesn't prevent Vim from working correctly (If any, feel free adding a supplementary comment to this issue).

I'd highly appreciate it if someone would write a patch to fix the issue and send it to us!

**Comment by nuko8** [comment]
@luchr 

Although the following patch looks somehow naive to me and is not well-tested if it introduces regression, I'd be happy if you would try it and report its result here:

``` diff
diff --git a/src/gui_gtk_x11.c b/src/gui_gtk_x11.c
index 3ee2957..6299e05 100644
--- a/src/gui_gtk_x11.c
+++ b/src/gui_gtk_x11.c
@@ -647,7 +647,8 @@ gui_gtk3_should_draw_cursor(void)
 {
     unsigned int cond = 0;
     cond |= gui_gtk_is_blink_on();
-    cond |= is_key_pressed;
+    if (gui.cursor_col >= gui.col)
+   cond |= is_key_pressed;
     cond |= gui.in_focus == FALSE;
     return  cond;
 }
```

**Comment by luchr** [comment]
Thank you nuko8 for the fast patch. One good and one bad news: Yes this fixes the problem for the above scenario, but if you additionally turn off the cursor-blinking, i.e. between step 2 and 3 you insert
`let &gcr=&gcr.",a:blinkon0"`
then the cursor-right-movement-then-jump-by-2 effect is there again.

**Comment by nuko8** [comment]
Thank you for checking.

Based on that, I enhanced the patch in a natural way, i.e., I added a path for the visual mode:

``` diff
diff --git a/src/gui_gtk_x11.c b/src/gui_gtk_x11.c
index 3ee2957..3b48590 100644
--- a/src/gui_gtk_x11.c
+++ b/src/gui_gtk_x11.c
@@ -647,7 +647,8 @@ gui_gtk3_should_draw_cursor(void)
 {
     unsigned int cond = 0;
     cond |= gui_gtk_is_blink_on();
-    cond |= is_key_pressed;
+    if (gui.cursor_col >= gui.col)
+   cond |= is_key_pressed;
     cond |= gui.in_focus == FALSE;
     return  cond;
 }
@@ -683,17 +684,28 @@ draw_event(GtkWidget *widget,
        if (blink_mode)
            gui_gtk3_redraw(rect.x, rect.y, rect.width, rect.height);
        else
-           gui_redraw(rect.x, rect.y, rect.width, rect.height);
+       {
+           if (get_real_state() & VISUAL)
+           gui_gtk3_redraw(rect.x, rect.y,
+               rect.width, rect.height);
+           else
+           gui_redraw(rect.x, rect.y, rect.width, rect.height);
+       }
        }
    }
    cairo_rectangle_list_destroy(list);

+   if ((get_real_state() & VISUAL) &&
+       gui.cursor_col >= gui.col &&
+       gui.cursor_row == gui.row)
+       gui_update_cursor(TRUE, TRUE);
+
    cairo_paint(cr);
     }
     gui.by_signal = FALSE;

     /* Add the cursor to the window if necessary.*/
-    if (gui_gtk3_should_draw_cursor())
+    if (gui_gtk3_should_draw_cursor() && blink_mode)
    gui_gtk3_update_cursor(cr);

     return FALSE;

```

Although this might not be called perfect,  I think it considerably mitigates the "annoyance."

Your thoughts?

**Comment by luchr** [comment]
Thank you very much, nuko8. In my test cases this annoyance completely disappared :-)
Also thank you for looking in this annoyance-issue which was not a real "bug", because it didn't prevent Vim from working correctly.
I now switch to gtk3vim as default graphical vim. There is only one "annoyance" left (compared to gtk2vim), but I don't dare to open an issue for this.
Thanks again.

**Comment by nuko8** [comment]
Great.

I will use the patched version for a day to make sure it has no apparent problem.  If it still looks good, I send the patch to vim_dev for inclusion.

The idea of the patch is based on an inspiration I got from your description of the issue, "If you keep h pressed then you can see the annoying effect better."  You're really a good reporter. :)

> There is only one "annoyance" left (compared to gtk2vim), but I don't dare to open an issue for this.

Please feel free to open the issue.  By what I wrote, I never meant to impose anything on you.  I just wanted to explain to you in advance I might fail you, just in case.

> Thanks again.

That's also the word I have to say to you :)
