### ISSUE TITLE
sass.vim should be updated

### ISSUE THREAD

**Issue by yangxyo** [vim/vim#6781]
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Describe the bug**
The codes after `@keyframes` all show blue in *.sass

**To Reproduce**
```sass
$color-white: #fff
$background-color: #222

.page-container
  font-size: large
  padding: 20px
  text-align: center

.product-list
  list-style: none
  margin: 0
  padding: 0

.product-list-item
  padding: 5px

.header
  background-color: $background-color
  color: $color-white
  height: 160px
  padding: 20px
  text-align: center

.header-logo
  animation: header-logo-spin infinite 20s linear
  height: 80px

// fds
@keyframes header-logo-spin
  from

    transform: rotate(0deg)

  to

    transform: rotate(360deg)


.header-title
  font-size: 1.5em

.header-link
  color: $color-white
  padding: 5px
  text-decoration: none
```

**Expected behavior**
The highlight could display right.

**Screenshots**
If applicable, copy/paste the text or add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/32320149/91028623-4f365180-e630-11ea-983b-8953f5efcee7.png)

![image](https://user-images.githubusercontent.com/32320149/91031383-1350bb80-e633-11ea-8c2d-95f29df85feb.png)

**Environment (please complete the following information):**
 - Vim version:  latest
 - OS: latest
 -  iTerm2

**Comment by yangxyo** [comment]
![image](https://user-images.githubusercontent.com/32320149/91031807-ab4ea500-e633-11ea-9f0e-32e609e57db8.png)
This is with no plugin.

**Comment by chrisbra** [comment]
please contact the maintainer of the sass syntax file

**Comment by yangxyo** [comment]
I have contacted Tim Pope, but he ignored me.😂

**Comment by chrisbra** [comment]
ping @tpope

**Comment by brammool** [comment]
It might help if you have a suggestion how to fix it.

**Comment by tpope** [comment]
I did receive an email about this. The timestamp was 5:30 AM ET, 9 minutes before this issue was created.

@yangxyo if you want a GitHub issue for this, great, please create one at [tpope/vim-haml](https://github.com/tpope/vim-haml). I don't think vim/vim needs to be involved.

**Comment by tpope** [comment]
And yes, a fix or advice in that direction would be very helpful.

**Comment by yangxyo** [comment]
Sorry，I just think the sass.vim is a part of vim😂.

**Comment by yangxyo** [comment]
I will create one at tpope/vim-haml

**Comment by yangxyo** [comment]
But I still think this is a problem of vim because sass.vim is a part of it.

**Comment by yangxyo** [comment]
However, I've found the `sass.vim` in  `tpope/vim-haml` the Last Change is `2016 Aug 29`.

**Comment by yangxyo** [comment]
I think this problem is only`@keyframes` rather than `@`, because the key words such as `@import , @media` do not impact that.
![image](https://user-images.githubusercontent.com/32320149/91112329-69664300-e6b5-11ea-993f-cee2ea1457ce.png)

**Comment by yangxyo** [comment]
I can not write vimscript, but I found if I delete the line 504 in `runtime/syntax/css.vim` about `@keyframe`. The highlighting seems right.😭

**Comment by yangxyo** [comment]
I may resolve it, just add following line in sass.vim :
`syn region sassKeyframe matchgroup=cssAtKeyword start=/@\(-[a-z]\+-\)\=keyframes\>/ end=";\|$" contains=cssVendor,cssComment nextgroup=cssDefinition`

**Comment by yangxyo** [comment]
https://github.com/tpope/vim-haml/pull/93#issue-472895767

**Comment by chrisbra** [comment]
closing here. I assume tpope will send updates to Bram for inclusion with the next runtime files update.
