### ISSUE TITLE
Deceptive documentation for [[ [] ][ and ]] mappings

### ISSUE THREAD

**Issue by AvianY** [vim/vim#6783]
This is just an observation I made about these mappings. I believe they are a bit confusing and require some weird logic to understand them, but this is not the reason why I am writing.

I am specifically referring to the section in the 'motion.txt' page where it says the following:
`
The "]" and "[" commands stop at the '{' or '}' in the first column.  This is
useful to find the start or end of a function in a C program.  Note that the
first character of the command determines the search direction and the
second character the type of brace found.
`

The third sentence "Note ..." is deceptive, if not just wrong. While it is true, that the first bracket will indicate the direction in which to search, the second one does not indicate the type of brace. It doesn't indicate anything. **If the second brace is the same as the first one, then it will search for '{', otherwise it will search for '}'.**

Personally it's confusing to me, but anyway, I suggest that the bold sentence above replaces the "Note ..." sentence.

**Comment by brammool** [comment]
This should be easier to understand:
The "]]" and "[[" commands stop at the '{' in the first column.  This is
useful to find the start of a function in a C program.  To search for a '}' in
the first column, the end of a C function, use "][" (forward) or "[]"
(backward).  Note that the first character of the command determines the
search direction.
