### ISSUE TITLE
Vim9: wrong error message when passing unexpected type of argument to function

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6785]
**Describe the bug**

In Vim9 script, passing an unexpected type of argument to a function called at the script level prints a wrong error message.

**To Reproduce**

Write this in `/tmp/t.vim`:
```vim
vim9script
def Func(n: number, s: string)
    eval 1
    eval 2
    eval 3
enddef
Func(123, [])
```
Start Vim like this:

    vim -Nu NONE /tmp/t.vim

Run this Ex command:

    :so%

`E1012` is raised:

    Error detected while processing /tmp/t.vim[7]..function <SNR>1_Func:
    line    3:
    E1012: type mismatch, expected string but got list<unknown>

The error message looks wrong for 3 reasons:

   - the error does not occur in the body of `Func()`; it happens at the script level (where the function is called)
   - it does not occur on line 3 in the body of `Func()`; it happens on line 7 in the script
   - the message does not tell us which argument in the function call has an unexpected type

**Expected behavior**

`E1013` is raised (not `E1012`).

The error message does not tell us that the error was raised while processing `Func()`, but that it was raised while processing the script where `Func()` was called (i.e. `..function <SNR>1_Func` should not be in the stack trace):

    Error detected while processing /tmp/t.vim[7]..function <SNR>225_Func:
                                                 ^----------------------^
                                                            ✘

The error message tells us that the error comes from the line 7 in the script, because that's the address of the line where `Func()` is called with an unexpected type of argument.

And it tells us that the argument with the unexpected type is the second one.

    E1013: argument 2: type mismatch, expected string but got list<unknown>
           ^--------^

All in all, I would expect this error message:

    Error detected while processing /tmp/t.vim:
    line    7:
    E1013: argument 2: type mismatch, expected string but got list<unknown>

**Environment**

 - Vim version: 8.2 Included patches: 1-1520
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: XTerm(358)

**Comment by brammool** [comment]
The error messages do not include the column or argument number anywhere.  We still have errors that say nothing more than "invalid argument".  It's a bigger task to make this work better and it's not directly related to Vim9 script.  So let's make that a todo item.

**Comment by lacygoill** [comment]
> The error messages do not include the column or argument number anywhere.

If the same error is raised from a `:def` function, then Vim gives the number of the argument.
```vim
vim9script
def Func(n: number, s: string)
    eval 1
    eval 2
    eval 3
enddef
def OtherFunc()
    Func(123, [])
enddef
OtherFunc()
```
    E1013: argument 2: type mismatch, expected string but got list<unknown>
           ^--------^

> It's a bigger task to make this work better and it's not directly related to Vim9 script. So let's make that a todo item.

Understood.  I just thought it was worth reporting any difference between an error message raised at the script level, and the same error raised from a `:def` function.

**Comment by brammool** [comment]
> > The error messages do not include the column or argument number anywhere.
> 
> If the same error is raised from a `:def` function, then Vim gives the number of the argument.
> ```vim
> vim9script
> def Func(n: number, s: string)
>     eval 1
>     eval 2
>     eval 3
> enddef
> def OtherFunc()
>     Func(123, [])
> enddef
> OtherFunc()
> ```
>     E1013: argument 2: type mismatch, expected string but got list<unknown>
>            ^--------^

Ah, that's probably the only one.

> > It's a bigger task to make this work better and it's not directly related to Vim9 script. So let's make that a todo item.
> 
> Understood.  I just thought it was worth reporting any difference
> between an error message raised at the script level, and the same
> error raised from a `:def` function.

I'll just do this one, since it has enough code in common.

-- 
You were lucky to have a LAKE! There were a hundred and sixty of
us living in a small shoebox in the middle of the road.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
