### ISSUE TITLE
legacy vim script incompatible behavior change : join string and float

### ISSUE THREAD

**Issue by tsuyoshicho** [vim/vim#6787]
Latest 8.2.1500 or before legacy vim script incompatible behavior changed.

## reproduce

run below code

```vim
let a = 'A'
let b = 1.0e-6
echo a b
echo a . b
```

## other info

**Expected behavior**
E806 throw need.

**Screenshots**
as text

8.2.1139 : E806 throw

8.2.1500 : result

```
A 1.0e-6
A1.0e-6
```

**Environment**
 - Vim version 8.2.1500 (from linuxbrew)
 - OS: Linux ubuntu 16.04
 - Terminal: putty

**Additional context**
nothing.

**Comment by k-takata** [comment]
8.2.1424 produces E806, and 8.2.1477 doesn't.

**Comment by lacygoill** [comment]
Regression introduced in [8.2.1435](https://github.com/vim/vim/releases/tag/v8.2.1435).
