### ISSUE TITLE
Vim9: cannot use custom function to sort list of strings

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6788]
**Describe the bug**

In Vim9 script, we cannot use a custom function to sort a list of strings.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            echo ['bbb', 'aaa']->sort('MySort')
        enddef
        def MySort(line1: string, line2: string): number
            return line1 > line2 ? 1 : -1
        enddef
        Func()
    EOF
    )

`E1030` is raised:

    E1030: Using a String as a Number

**Expected behavior**

No error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-1520
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: XTerm(358)

**Additional context**

Regression introduced in 8.2.1465.

**Comment by bfrg** [comment]
Remove the quotes:
```vim
def Func()
    echo ['bbb', 'aaa']->sort(MySort)
enddef
```

**Comment by lacygoill** [comment]
Thank you for the workaround.  I keep the issue open, because it's still a regression, and should work with the quotes.

Btw, why does it work for `sort()` but not for `map()`?
```vim
vim9script
def Func(n: number): number
    return n + 1
enddef
let list = [1, 2, 3]
map(list, Func)
echo list
```
    E116: Invalid arguments for function map(list, Func)

Relevant todo item:
https://github.com/vim/vim/blob/c8ec5fe56fc30201c889ca577bf1e69823fadb2a/runtime/doc/todo.txt#L128-L130

**Comment by bfrg** [comment]
I don't know what the long-term goals are but personally I would prefer `sort(items, MyFunc)` or `filter(items, MyFilter)` over the old version where quotes are necessary. I always found it awkward that we need to pass functions as strings to other functions.

**Comment by lacygoill** [comment]
All right, I close the issue because the notation without quotes is indeed nicer to read and write.

It just needs to be generalized to all functions which accept a funcref as argument, which is the purpose of the previously mentioned todo item.

---

Btw, I made a mistake in the previous snippet; the header of `Func()` should have included 2 arguments.

Right now, we still need `function()`:
```vim
vim9script
def Func(i: number, v: number): number
    return v + 1
enddef
let list = [1, 2, 3]
map(list, function('Func'))
echo list
```
    [2, 3, 4]

Once the todo item is implemented, we'll be able to rewrite the code like this:
```vim
vim9script
def Func(i: number, v: number): number
    return v + 1
enddef
let list = [1, 2, 3]
map(list, Func)
echo list
```

**Comment by bfrg** [comment]
For imported functions it already works:
```vim
" foo.vim
vim9script
export def Foo(i: number, v: number): number
    return 100 * v
enddef

" test.vim
vim9script
import Foo from './foo.vim'
def Func()
    echo [1, 2, 3]->map(Foo)
enddef
Func() " [100, 200, 300]
```

**Comment by lacygoill** [comment]
Actually, the function doesn't need to be imported; it just needs to be a `:def` function:
```vim
vim9script
def Foo(i: number, v: number): number
    return 100 * v
enddef

def Func()
    echo map([1, 2, 3], Foo)
enddef
Func()
```
The issue is when `map()` is invoked at the script level; then it stops working.  It might be related to #6789.

**Comment by brammool** [comment]
> I don't know what the long-term goals are but personally I would
> prefer `sort(items, MyFunc)` or `filter(items, MyFilter)` over the old
> version where quotes are necessary. I always found it awkward that we
> need to pass functions as strings to other functions.

When using a string it's not feasible to check the type of the function
reference.  When using the function directly the argument and return
types can be checked.  Although for built-in functions this still needs
to be implemented.

Also, passing the function name as a string is different from what most
languages do.

-- 
This is an airconditioned room, do not open Windows.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
