### ISSUE TITLE
confused about expand and fnamemodify

### ISSUE THREAD

**Issue by wsdjeg** [vim/vim#6793]
I am not sure if these are bug, but they make me confused!

the reproduced step is:

- open a new buffer with empty bufname `:enew`
- run `echo expand('%')` return empty string
- run `echo expand('%:p')` return empty string
- run `echo fnamemodify('', ':p')` return current path
- open a new buffer  `:e test.txt`
- run `echo expand('%')` return `text.txt`
- run `echo expand('%:p')` return `/path/to/text.txt`

my question is why fnamemodify return a current path with empty string? and it is not shown on doc.

**Comment by gdupras** [comment]
From `:help expand()`:
```
When using '%' or '#', and the current or alternate file name
is not defined, an empty string is used.  Using "%:p" in a
buffer with no name, results in the current directory, with a
'/' added.
```
But as you said, doing `:echo expand('%:p')` in a buffer with no name returns an empty string. Based on the documentation, I would have expected the current directory, which would match the behavior of `fnamemodify('', ':p')`.

I agree, looks like there is something wrong here.

**Comment by brammool** [comment]
> From `:help expand()`:
> ```
> When using '%' or '#', and the current or alternate file name
> is not defined, an empty string is used.  Using "%:p" in a
> buffer with no name, results in the current directory, with a
> '/' added.
> ```
> But as you said, doing `:echo expand('%:p')` in a buffer with no name returns an empty string. Based on the documentation, I would have expected the current directory.
> 
> I agree, there is something wrong here.

When there is no file name there also isn't a directory in which that
file exists.  Perhaps expand('%:p') should result in an error.
Returning an empty string is basically the same as returning an error.

fnamemodify() doesn't use the current file name.  Now what should it do
with an empty string?  Not sure.  Anyway, the current behavoir is what
users rely on, so let's not change it.

-- 
Life would be so much easier if we could just look at the source code.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
closing then.
