### ISSUE TITLE
Mappings defined without shift (eg. <C-e>) require the shift key to work

### ISSUE THREAD

**Issue by creature** [vim/vim#6794]
**Describe the bug**
I've had some mappings in my `.vimrc` for years; they no longer work unless I use the shift key as well. I haven't seen any similar reports so this might be a quirk of my system, but I'd love some help tracking it down. I've boiled the issue down to the following test case: 

**To Reproduce**
1. Run `vim --clean` 
1. Define a mapping: `:nnoremap <special> <C-e> :e #<CR>` 
1. Press `<C-e>`. The Vim splash screen disappears, but the mapping does not fire. (You'd see an error if it did.) 
    * Pressing `<C-S-e>` _does_ fire the mapping; Vim displays "E194: No alternate file name to substitute for '#'.
    * If you create some lines in the buffer before pressing `<C-e>`, then the Vim default for this key (scroll buffer down one line) works fine.
    * `:nmap` displays the following maps:
        ```
           Q             gq
        n  <C-E>       * :e #<CR>
        n  <D-v>         "*P
        ```

**Expected behavior**

As I understand it, Vim shouldn't differentiate between `<C-e>` and `<C-S-e>` by default. That's borne out by testing on a Linux machine and my work machine; both `<C-e>` and `<C-S-e>` display `E194` in the test case above. 

**Environment:**
- Vim version 8.2.1500
- macOS Mojave (10.14.6)
- iTerm2 3.4.0beta4

I have a similar system on Vim version 8.2.950, macOS 10.14.6, and iTerm2 3.3.7beta1. That system doesn't exhibit this behaviour. Given the additional context below, if this is a Vim bug I think it would have been introduced between patch 950 and 1250. 

**Additional context**

A couple of months ago I copied my work `.vimrc` onto my home computer, to synchronise some settings and plugin additions. I also updated Vim and all plugins. 

After these updates, I found that my `<C-whatever>` keybindings would work when Vim was started initially, but after a while (normally a few minutes of editing) they'd stop working. Restarting Vim restores them. I figured that a plugin update would be the culprit. After regular updates failed to solve it, and commenting out recently-added plugins failed to solve it, I started trying to find more info. Removing all plugins didn't fix it, and eventually I found the test case above. 

I have a gist with details from when I first started trying to figure out the cause; although I'm currently on 8.2.1500, that indicates that this has affected me since 8.2.1250.

The full paste of my `vim --version` is as follows:

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Aug 20 2020 22:44:15)
macOS version
Included patches: 1-1500
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
-autoservername    +folding           +multi_byte        +termguicolors
-balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
-browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              +perl              +title
-clientserver      +job               +persistent_undo   -toolbar
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           -python            +visual
+conceal           +linebreak         +python3           +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua               +ruby              +wildmenu
+dialog_con        +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
-dnd               +mouse             -sound             -xfontset
-ebcdic            -mouseshape        +spell             -xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              -mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -lintl -framework AppKit  -L/usr/local/opt/lua/lib -llua5.3 -mmacosx-version-min=10.14 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.32.0/lib/perl5/5.32.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/config-3.8-darwin -lpython3.8 -framework CoreFoundation  -lruby.2.7
```

**Comment by chrisbra** [comment]
could it be, that Vim has enabled modifyotherkeys? What is the value of `$TERM` and does it make a difference if you do:

      let &t_TI = ""
      let &t_TE = ""

**Comment by creature** [comment]
`$TERM` is `xterm-256color`. Setting `&t_TI` and `&t_TE` to a blank string don't change the behaviour of the test case. 

Based on the test case described in the help file, I think modifyOtherKeys is always off: 

> A known side effect is that in Insert mode the raw escape sequence is inserted after the CTRL-V key.  This can be used to check whether modifyOtherKeys is enabled: In Insert mode type CTRL-SHIFT-V CTRL-V, if you get one byte then modifyOtherKeys is off, if you get `<1b>27;5;118~` then it is on.

* Starting Vim with `vim --clean` (ie. it exhibits the behaviour): Ctrl-shift-V Ctrl-v prints `^V`.
    * This test case on my work computer (ie. vim 8.2.950) also prints `^V`, but the `<C-e>` mapping works without shift. It also has its `$TERM` set to `xterm-256color`. 
* Starting Vim with `vim` (ie. mappings currently work): Ctrl-shift-V Ctrl-v prints `^V`.

**Comment by drmikehenry** [comment]
This may be related in some way to https://github.com/vim/vim/issues/6457, though that ticket is for Vim GTK on Linux.

**Comment by brammool** [comment]
"Vim shouldn't differentiate between <C-e> and <C-S-e>" is only true when not using modifyOtherKeys.  Thus if they do differ your terminal must be set to use modifyOtherKeys.
After setting t_TI and t_TE execute a shell command to have them be applied to the terminal: "!ls".

**Comment by brammool** [comment]
Note that it could also be a bug in iTerm

**Comment by creature** [comment]
> "Vim shouldn't differentiate between `<C-e>` and `<C-S-e>`" is only true when not using modifyOtherKeys. Thus if they do differ your terminal must be set to use modifyOtherKeys.

Thanks for the suggestions! I don't think modifyOtherKeys is coming into play, based on the following test case: 

1. Run `vim --clean`. 
1. Enter insert mode and press `<C-v>` `<C-S-v>`, which prints `^V`. 
1. Leave insert mode and run the following: 
    ```
    :let &t_TI = ""
    :let &t_TE = ""
    :!ls
    ```
1. Press enter to clear the command, then `i` to enter insert mode. 
1. Press `<C-v><C-S-v>`. This prints `^V`, like before. 
1. Leave insert mode, and configure the binding with `:nmap <special> <C-e> :e #<CR>`.
1. Pressing `<C-e>` does not trigger the binding; `<C-S-e>` does. 

> Note that it could also be a bug in iTerm. 

I think that iTerm might be a factor! I tried my original test case in Apple's terminal (version 2.9.5 (421.2)). That also has a `$TERM` variable set to `xterm-256color`, but it didn't exhibit the problem.

I'll compare my work iTerm2 configuration with my home configuration and see if anything looks different; if not, I'll seek help from the iTerm2 community. I'll report back here either way.

**Comment by RobBednark** [comment]
I'm seeing the same issue with `<c-p>` from my `ctrlp` plugin.  After a bit, `<C-p>` reverts to the default vim behavior of moving the cursor up a line, but `<C-S-p>` works.   I'm using the same vim version, OS and terminal as @creature.

Environment:

- Vim version: `8.2 (patches 1-1500)` 
- OS: `macOS Mojave (10.14.6)`
- terminal: `iTerm2 3.4.0beta4`

**Comment by chrisbra** [comment]
Can you try with a different terminal or a different version of that terminal?

**Comment by creature** [comment]
`<C-p>` is one of my affected keystrokes too, as is `<C-j>`. 

I've [opened an issue in the iTerm2 bug tracker](https://gitlab.com/gnachman/iterm2/-/issues/9110) and will report back here if I learn more.

**Comment by Yamagi** [comment]
I'm able to reproduce this in gvim, but not when vim is running under rxvt-unicode. Pressing ctrl-t in rxvt-unicode shows `^T` in the status line, like it should. Pressing the same key combination in gvim shows `<9b>ü^DT`.  I did a bisect:

* The control key behavior was broken in 8.2.0919: *Merging modifier for modifyOtherKeys is done twice.*
* The status line out is garbled since 8.2.0851: *Can't distinguish <M-a> from accented "a" in the GUI.*

**Comment by creature** [comment]
The iTerm2 author couldn't reproduce the test case above, but used my debug log to investigate. They [suspect this is an issue with how vim handles CSI u input](https://gitlab.com/gnachman/iterm2/-/issues/9110#note_406538380): 

> What's happening is that vim has enabled CSI u mode and does not accept a code point of 5 as control-E. iTerm2 is doing the right thing by sending the CSI u style code for control-shift-E.
> 
> I don't understand why vim won't accept 5 for C-e. This does seem like a vim bug to me, although the CSI u is pretty fragmented so it's possible this was tested against some terminal with a different implementation.

I'm not familiar with CSI u, so I don't know if that sounds plausible? If that's the cause, is this a Vim bug or a bug in iTerm2's CSI u implementation? 

In addition to the commits flagged by Yamagi, two which stand out to me are ef6746f6 (patch 8.2.1019: mapping <M-S-a> does not work in the GUI) and b42c0d54 (patch 8.2.0839: dropping modifier when putting a character back in typeahead).

**Comment by brammool** [comment]
> The iTerm2 author couldn't reproduce the test case above, but used my debug log to investigate. They [suspect this is an issue with how vim handles CSI u input](https://gitlab.com/gnachman/iterm2/-/issues/9110#note_406538380): 
> 
> > What's happening is that vim has enabled CSI u mode and does not accept a code point of 5 as control-E. iTerm2 is doing the right thing by sending the CSI u style code for control-shift-E.
> > 
> > I don't understand why vim won't accept 5 for C-e. This does seem like a vim bug to me, although the CSI u is pretty fragmented so it's possible this was tested against some terminal with a different implementation.
> 
> I'm not familiar with CSI u, so I don't know if that sounds plausible? If that's the cause, is this a Vim bug or a bug in iTerm2's CSI u implementation? 
> 
> In addition to the commits flagged by Yamagi, two which stand out to me are ef6746f6 (patch 8.2.1019: mapping <M-S-a> does not work in the GUI) and b42c0d54 (patch 8.2.0839: dropping modifier when putting a character back in typeahead).

I don't know what "CSI u mode" means.  The behavior is best documented
in the Xterm escape sequences:
https://invisible-island.net/xterm/manpage/xterm.html#VT100-Widget-Resources:modifyOtherKeys

Perhaps iTerm2 thinks the mode is set to "1", while actually it is set
to "2".  When modifyOtherKeys is active, the terminal should never send
"5" for CTRL-E.  It should send the CTRL modifier and the E key (or the
e key, that is open for interpretation).

I relalize that in Vim it's not so easy to see what Vim actually
received from the terminal, before any processing.  Let me add a patch
for that.  It's also useful in the context of sending messages over a
channel.  See patch 8.2.1582.

-- 
    [clop clop]
MORTICIAN:  Who's that then?
CUSTOMER:   I don't know.
MORTICIAN:  Must be a king.
CUSTOMER:   Why?
MORTICIAN:  He hasn't got shit all over him.
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by creature** [comment]
> I don't know what "CSI u mode" means. 

I'm not totally sure myself! As I understand it, it's a terminal input scheme designed to make modified keys unambiguous. (There's [a lot more details and a specification available](http://www.leonerd.org.uk/hacks/fixterms/).) Thanks for the link to XTerm's documentation on modifyOtherKeys – that led me to more information.

The [Xterm FAQ](https://invisible-island.net/xterm/modified-keys.html) includes an extended discussion about the history of modifyOtherKeys and CSI u. I'm out of my depth here, but I think they are similar-but-incompatible standards trying to accomplish the same thing. Thus, I'm guessing the root cause of my issue is that Vim enables modifyOtherKeys, but Xterm and iTerm2 report chorded keystrokes differently. Which is basically what Georg said: 

>  I don't understand why vim won't accept 5 for C-e... although the CSI u is pretty fragmented so it's possible this was tested against some terminal with a different implementation.

As I say, I'm out of my depth, but I don't have a sense of the "correct" solution here. iTerm2 [recommends `xterm-256color` as a `$TERM` variable](https://www.iterm2.com/faq.html), so I don't think setting a unique `$TERM` variable is going to be an option. I don't know if Vim can handle input regardless of whether it's produced from an Xterm-modifyOtherKeys or an iTerm2-CSI-u, and it seems a safe bet that iTerm2 can't emit cross-compatible escape sequences. Perhaps the best solution is for me to configure Vim to force `modifyOtherKeys` off. 

> I relalize that in Vim it's not so easy to see what Vim actually received from the terminal, before any processing.  Let me add a patch for that. 

Thanks! I think that'll be very useful. 

I'll try to [disable modifyOtherKeys](https://vimhelp.org/map.txt.html#modifyOtherKeys) in both iTerm2 and Vim, and see if that helps. I'll also take this background info to the iTerm2 project, and report back when I have something useful to share.

**Comment by brammool** [comment]
> > I don't know what "CSI u mode" means. 
> 
> I'm not totally sure myself! As I understand it, it's a terminal input
> scheme designed to make modified keys unambiguous. (There's [a lot
> more details and a specification
> available](http://www.leonerd.org.uk/hacks/fixterms/).) Thanks for the
> link to XTerm's documentation on modifyOtherKeys – that led me to more
> information.

What Paul Evans says must be taken with a grain of salt.  He is
enthusiastically implementing things, but when it comes to discussions he
often appears to be a bit over confident.  I relied on libvterm, but
discovered many bugs that had to be fixed.  It all feels a bit
unfinished.

> The [Xterm FAQ](https://invisible-island.net/xterm/modified-keys.html)
> includes an extended discussion about the history of modifyOtherKeys
> and CSI u. I'm out of my depth here, but I think they are
> similar-but-incompatible standards trying to accomplish the same
> thing. Thus, I'm guessing the root cause of my issue is that Vim
> enables modifyOtherKeys, but Xterm and iTerm2 report chorded
> keystrokes differently. Which is basically what Georg said: 
> 
> >  I don't understand why vim won't accept 5 for C-e... although the
> >  CSI u is pretty fragmented so it's possible this was tested against
> >  some terminal with a different implementation.

There are also a few standards floating around, which are surprisingly
hard to interpret.  When different terminals do different things, I
consider xterm to be the standard.  Since usually $TERM is set to
"xterm-something".  And also because it's the oldest and most complete.
Lacks some fancy features though, which has lead to this crazy explosion
of everybody implementing their own.  https://xkcd.com/927/

> As I say, I'm out of my depth, but I don't have a sense of the
> "correct" solution here. iTerm2 [recommends `xterm-256color` as a
> `$TERM` variable](https://www.iterm2.com/faq.html), so I don't think
> setting a unique `$TERM` variable is going to be an option. I don't
> know if Vim can handle input regardless of whether it's produced from
> an Xterm-modifyOtherKeys or an iTerm2-CSI-u, and it seems a safe bet
> that iTerm2 can't emit cross-compatible escape sequences. Perhaps the
> best solution is for me to configure Vim to force `modifyOtherKeys`
> off. 
> 
> > I relalize that in Vim it's not so easy to see what Vim actually
> > received from the terminal, before any processing.  Let me add a
> > patch for that. 
> 
> Thanks! I think that'll be very useful. 
> 
> I'll try to [disable
> modifyOtherKeys](https://vimhelp.org/map.txt.html#modifyOtherKeys) in
> both iTerm2 and Vim, and see if that helps. I'll also take this
> background info to the iTerm2 project, and report back when I have
> something useful to share.

That should work.  I suspect that when you say that it stops working at
some point, is when Vim has detected that the terminal supports
modifyOtherKeys (possibly when you use CTRL-Shift-key) and then assumes
the modifiers come separately and won't accept the previous encoding
(because that must be something else then).

-- 
A computer programmer is a device for turning requirements into
undocumented features.  It runs on cola, pizza and Dilbert cartoons.
					Bram Moolenaar

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by gnachman** [comment]
I suppose it may have been a mistake to use modifyOtherKeys=2 to enable this mode.

I like the design of Paul's "CSI u" mode better than xterm's implementation because it has a much nicer backward compatibility story. If you leave it enabled all the time, it mostly just works in apps that don't know about it.

OTOH, breaking vim was definitely not the goal, so something must be done.

@brammool what would be the harm of accepting C0 controls (e.g., 5 = <C-e>) in modifyOtherKeys mode?

**Comment by brammool** [comment]
George Nachman wrote:

> I suppose it may have been a mistake to use modifyOtherKeys=2 to
> enable this mode.
> 
> I like the design of Paul's "CSI u" mode better than xterm's
> implementation because it has a much nicer backward compatibility
> story. If you leave it enabled all the time, it mostly just works in
> apps that don't know about it.

I don't see the point of a half-implementation, where some characters
work as before, thus still unable to tell the difference between
entering a special character or using modifier keys, while still
requiring to recognize the extra modifier escape code.  It's going to be
a hit-and-miss where this works, depending on what keys are used, the
language and the keyboard setup.

> OTOH, breaking vim was definitely not the goal, so something must be
> done.
> 
> @brammool what would be the harm of accepting C0 controls (e.g., 5 =
> <C-e>) in modifyOtherKeys mode?

Yes, it makes it impossible to separate certain system generated keys,
such as CTRL-H from Backspace.  Vim has special code to figure out
whether the terminal supports modifyOtherKeys and what mappings the user
defined.  It took quite a bit of tuning to get this right and be able to
map all the different key combinations.

I understand there are different views on what would work best.  In
these situations I take the xterm behavior as the standard, since most
of these terminals pretend to be xterm compatible, and usually we end up
with $TERM being set to xterm-something.

-- 
WOMAN:   I didn't know we had a king. I thought we were an autonomous
         collective.
DENNIS:  You're fooling yourself.  We're living in a dictatorship.  A
         self-perpetuating autocracy in which the working classes--
WOMAN:   Oh there you go, bringing class into it again.
DENNIS:  That's what it's all about if only people would--
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by creature** [comment]
I tested out disabling modifyOtherKeys in a `.vimrc` tonight, and I can confirm that my test case above no longer exhibits the bug; `<C-e>` works again without shift. Thank you all for your help tracking it down! 

To test, I created a new file `vimrc-test` with the following contents:

```
let &t_TI = ""
let &t_TE = ""
```

And started vim with `vim -u vimrc-test`, then set `:nmap <special> <C-e> :e #<CR>`. Pressing `<C-e>` now produces the expected `E194` error message.

**Comment by creature** [comment]
I'm taking the liberty of closing this issue now, on the following basis: 

* This report kind of boils down to "Vim and iTerm2 are speaking different dialects when reporting modifier keys". It's debatable whether the "flaw" lies with iTerm2 or Vim – but there's no easy way for Vim to detect the dialect, and iTerm2's declaring itself as xterm-compatible. So there's no concrete next step for the Vim project to do here. 
* A viable workaround – [disabling Vim from triggering `modifyOtherKeys`](https://vimhelp.org/map.txt.html#modifyOtherKeys) – has been identified for anyone using an affected version of iTerm2. 
* Recent betas of iTerm2 have been updated for xterm compatibility. From the [3.4.0beta7 changelog](https://iterm2.com/downloads.html):
    > Modifier keys in vim should work better now. CSI u mode is no longer enabled by a control sequence. Instead, a "modifyOtherKeys" mode has been added which is compatible with xterm. 

Thanks again to everyone for helping track this down, and especially to George for updating iTerm2 so rapidly. :)
