### ISSUE TITLE
Problem with regressionImp and integer values.

### ISSUE THREAD

**Issue by jjanborowka** [vim/vim#6799]
Description: 
regressionImp don't work when integer values supplied. Error only appear when integer value supposed to be imputed.

Detailed steps to reproduce the behavior:
test  <- iris
test[,2] <- as.integer(test[,2])
test[1:50,2] <- NA
VIM::regressionImp(Sepal.Width ~Petal.Length,test)

Expected behavior
Error in  'regressionImp(Sepal.Width ~ Petal.Length, test)':
  coudnt found 'nLev' object.

Environment:
 - Vim:  [VIM_6.0.0] 
 - OS:  Ubuntu 20.04 LTS
 - R : 3.6.3

**Comment by chrisbra** [comment]
Is this an R error or a Vim error? It's not clear from your description.

**Comment by LemonBoy** [comment]
You probably want [this VIM repository](https://github.com/statistikat/VIM) heh

**Comment by k-takata** [comment]
Aha! Totally different project!
Closing.
