### ISSUE TITLE
Python: iteration over vim objects fails to keep reference.

### ISSUE THREAD

**Issue by paul-ollis** [vim/vim#6803]
The Python interface code does not hold a reference to the Vim object that
is being iterated. This can cause Vim to SegFault.

**To Reproduce**

Execute this script, using py3file.

    import sys

    import vim

    str2list = vim.Function('str2list')
    v = str2list('a')
    print('Expect refcount = 2, actual =', sys.getrefcount(v))
    for el in v:
        print('Correct refcount = 3, actual =', sys.getrefcount(v))
        print('A', el)

    # This loop may work OK, but more normally it will:
    #
    #   - Produce strange results
    #   - Cause Vim to SegFault.
    #
    for el in str2list('a'):
        print('B', el)

**Expected behavior**

The output should be:

    Expect refcount = 2, actual = 2
    Correct refcount = 3, actual = 3
    A 97
    V 97

The actual output varies, but one example of a non-SeqFault run is:

    Expect refcount = 2, actual = 2
    Correct refcount = 3, actual = 2
    A 97
    B 0
    B b''
    B b''

**Environment**

I have reproduced this using:

    vim.8.2.1525
    Linix
    Python 3.9

But I am confident that the issue is not affecetd by software versions nor
platform.

**Test and fix**

The attached provide a suitable test and a fix.

**Comment by paul-ollis** [comment]
[add-test-and-fix.patch.txt](https://github.com/vim/vim/files/5141901/add-test-and-fix.patch.txt)
[add-test-only.patch.txt](https://github.com/vim/vim/files/5141903/add-test-only.patch.txt)

**Comment by paul-ollis** [comment]
Forgot to mention. The fix should also work for Python2, but I am not (currently) set up to build Vim with Python2 support.

**Comment by chrisbra** [comment]
If you could turn that into a proper PR, we already see the results from the CI testing infrastructure.

**Comment by paul-ollis** [comment]
Will do. Should be there within 24 hours.
