### ISSUE TITLE
VimScript syntax hightlighting: 'nested' is not highlited

### ISSUE THREAD

**Issue by ademin** [vim/vim#6808]
According to the documentation `usr_40.txt`, there is
the optional `nested` argument but it is not highlighted
when the syntax is on.
```
NESTING

Generally, commands executed as the result of an autocommand event will not
trigger any new events.  If you read a file in response to a FileChangedShell
event, it will not trigger the autocommands that would set the syntax, for
example.  To make the events triggered, add the "nested" argument: >

	:autocmd FileChangedShell * nested  edit
```

**To Reproduce**
1. Open $MYVIMRC
2. Enable syntax highlighting via `:syntax on`
3. Add `autocmd! BufWinEnter *.[ch] nested :set nu`

**Expected behavior**
'nested' is highlighted

**Environment (please complete the following information):**
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Aug 28 2020 22:02:04)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-1537
Compiled by appveyor@APPVYR-WIN*

**Comment by chrisbra** [comment]
I think the prefered way to write it is nowadays `++nested` (it has been adjusted by some patch). Probably the documentation there needs to be adjusted.

However `++nested` is also not really highlighted, cc @cecamp for the vim syntax update

**Comment by cecamp** [comment]
I've updated the vim syntax file; you can get the cutting edge version from my [website](http://www.drchip.org/astronaut/vim/index.html#SYNTAX_VIM); that'll be version v8.0-43.

**Comment by ademin** [comment]
@cecamp Thank you! Yes, it works! 
Does the Vim team integrate the patch into the upcoming release?

**Comment by chrisbra** [comment]
I kept this open, so that Bram can fix the documentation (using `++nested` instead of `nested`). @brammool if you think the documentation should not be changed, just close it.

**Comment by brammool** [comment]
Fixed it in five places.
