### ISSUE TITLE
[doc] How to understand <nowait>

### ISSUE THREAD

**Issue by lervag** [vim/vim#6810]
First, for context, Vim's help page for `<nowait>` is:

```
                                                *:map-<nowait>* *:map-nowait*
When defining a buffer-local mapping for "," there may be a global mapping
that starts with ",".  Then you need to type another character for Vim to know
whether to use the "," mapping or the longer one.  To avoid this add the
<nowait> argument.  Then the mapping will be used when it matches, Vim does
not wait for more characters to be typed.  However, if the characters were
already typed they are used.
```

Recently, there was a discussion on map conflicts for the plugin vimtex (https://github.com/lervag/vimtex/issues/1783). During this discussion, we started to investigate how the `<nowait>` argument actually works. Essentially, it seems the current documentation is not "entire". Some observations made during our discussions, which may be summarized as follows:

A mapping with the `<nowait>` argument will be executed immediately, unless:

1. The mapping is global and there exists a conflicting `<buffer>` mapping.
2. A conflicting mapping has been added after it was defined (at the same scope).

Exception 2 is important, in that it means that user defined mappings can override plugin mappings if they occur after the plugin was initialized. In particular, one may add buffer local `<nowait>` mappings that will be executed immediately as long as they are defined after a plugin was loaded that defined conflicting mappings.

Or, perhaps more simply, "`<nowait>` can only suppress the timeout of an existing conflicting mapping; not future conflicting mappings".

As such, perhaps it would be appropriate to add a sentence or two in the docs to make this behaviour clear?

**Comment by brammool** [comment]
Can you please give reproducible examples?  Starting with a clean Vim, define some mappings, what you type, what you expected and what actually happened.

**Comment by lervag** [comment]
Yes, sure. Here are two examples:

1. Given `test1.vim`:

    ```vim
    set nocompatible
    set showcmd
    nnoremap <buffer><nowait> cda :echo 'I hit cda'<cr>
    nnoremap <buffer><nowait> cd  :echo 'I hit cd'<cr>
    ```

    * Start Vim: `vim -u test1.vim`
    * Type `cd`
    * As expected, the `cd` mapping executes immediately.

2. Given `test2.vim`:

    ```vim
    set nocompatible
    set showcmd
    nnoremap <buffer><nowait> cd  :echo 'I hit cd'<cr>
    nnoremap <buffer>         cda :echo 'I hit cda'<cr>
    ```

    * Start Vim: `vim -u test2.vim`
    * Type `cd`
    * Now `cd` no longer executes immediately, regardless of the `<nowait>` argument.

**Comment by brammool** [comment]
This is working as intended.  The original idea was that there is only one matching buffer-local mapping.  That one is always found before global mappings (which may map partially) and will be used without waiting.
If you have two buffer-local mappings that (partly) match, then the order in which they were defined matters.  If the <nowait> mapping is found first (defined last), then it won't bail out on the partial mapping.  But if the partial mapping is found first, before the <nowait> mapping has been seen, then it will bail out and wait for the next character.

I'll update the help text to explain this better.

**Comment by lervag** [comment]
> I'll update the help text to explain this better.

Great. Thanks for the info. I suspected everything worked as intended, but I think it would be good with a small update to the help text.
