### ISSUE TITLE
viminfo cleared when disk is full

### ISSUE THREAD

**Issue by leahneukirchen** [vim/vim#682]
I happened to work with some systems recently that often had the disk where .viminfo resides completely full, and i noticed that running vim then results in clearing the contents of the file... it would be great if this could be made more resilient, so we don't lose the command history or short-term macros in registers.

The viminfo seems to be updated via a tempfile anyway, so the update only should be committed when writing that tempfile was successful. Perhaps checking ferror of the temp handle is enough.

**Comment by leahneukirchen** [comment]
I managed to take an strace of when this happens:

```
open("/home/chris/.viminfo", O_RDONLY)  = 3
stat("/home/chris/.viminfo", {st_mode=S_IFREG|0600, st_size=23809, ...}) = 0  
getuid()                                = 1000
getuid()                                = 1000  
stat("/home/chris/.viminfo.tmp", 0x7ffcd850e990) = -1 ENOENT (No such file or directory)
umask(0)                                = 02  
open("/home/chris/.viminfo.tmp", O_WRONLY|O_CREAT|O_EXCL|O_NOFOLLOW, 0600) = 4
umask(02)                               = 0  
fcntl(4, F_GETFL)                       = 0x28001 (flags O_WRONLY|O_LARGEFILE|O_NOFOLLOW)
fchown(4, 1000, 1000)                   = 0
fstat(3, {st_mode=S_IFREG|0600, st_size=23809, ...}) = 0  
read(3, "# This viminfo file was generate"..., 4096) = 4096
read(3, "srcpkgs/libcxx/template\n'5  8  0"..., 4096) = 4096
read(3, "llfuse/template\n-'  16  8  ~/xbp"..., 4096) = 4096  
fstat(4, {st_mode=S_IFREG|0600, st_size=0, ...}) = 0
write(4, "# This viminfo file was generate"..., 4096) = -1 ENOSPC (No space left on device)  
write(4, "rcpkgs/libcxx/template\n'5  8  0 "..., 4096) = -1 ENOSPC (No space left on device)
read(3, "ages/srcpkgs/mc/template\n\t\"\t16\t1"..., 4096) = 4096
write(4, "fuse/template\n-'  16  8  ~/xbps-"..., 4096) = -1 ENOSPC (No space left on device)
read(3, "4\t0\n\t+\t85\t18\n\t+\t110\t0\n\t+\t110\t0\n\t"..., 4096) = 4096
write(4, "\n> ~/xbps-packages/srcpkgs/libgi"..., 4096) = -1 ENOSPC (No space left on device)
read(3, "\t45\n\t+\t27\t12\n\t+\t28\t12\n\t+\t24\t34\n\t"..., 4096) = 3329
write(4, "\t+\t107\t0\n\t+\t116\t34\n\t+\t53\t2\n\t+\t49"..., 4096) = -1 ENOSPC (No space left on device)
read(3, "", 4096)                       = 0
write(4, "\t+\t20\t0\n\t+\t14\t3\n\t+\t17\t0\n\t+\t6\t0\n\t"..., 3257) = -1 ENOSPC (No space left on device)  
close(4)                                = 0
close(3)                                = 0
stat("/home/chris/.viminfo.tmp", {st_mode=S_IFREG|0600, st_size=0, ...}) = 0  
stat("/home/chris/.viminfo", {st_mode=S_IFREG|0600, st_size=23809, ...}) = 0
unlink("/home/chris/.viminfo")          = 0  
rename("/home/chris/.viminfo.tmp", "/home/chris/.viminfo") = 0
```

As you can see, the writes are failing with ENOSPC, yet the original file is unlinked and renamed with the now empty viminfo.

**Comment by brammool** [comment]
Christian Neukirchen wrote:

> I managed to take an strace of when this happens:

Thanks.  I found that the fclose() had a remark about checking for
errors, but that was never added.  Added a check now.

## 

hundred-and-one symptoms of being an internet addict:
50. The last girl you picked up was only a jpeg.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///
