### ISSUE TITLE
:vimgrep will crash if vim was started with "-n" (no swap) argument

### ISSUE THREAD

**Issue by rulero** [vim/vim#6827]
Vim will crash if started with "-n" argument, and a :vimgrep command is executed with a pattern that does match at least one of the scanned files.

**To Reproduce**
1. Run `gvim -n`.
2. Type `:vimgrep /a/ *`.
4. Wait for gvim to scan the files, gvim window will just disappear right before opening the first match returning a "Segmentation fault" error.

**Expected behavior**
Command is expected to return a list with several files (in quickfix window) and open the first one of them.

**Environment:**
 - Vim version: 8.2.1384 
 - OS: Windows 10 1909
 - Compiler: MinGW cross compiler on Cygwin

The bug was introduced by v8.2.1384, and still present on v8.2.1548

**Comment by lacygoill** [comment]
- [backtrace](https://github.com/vim/vim/files/5152083/backtrace.txt)
- [valgrind log](https://github.com/vim/vim/files/5152085/valgrind.log)
- [asan log](https://github.com/vim/vim/files/5152081/asan.log)

**Comment by lacygoill** [comment]
cc @yegappan via https://github.com/vim/vim/pull/6638

**Comment by lacygoill** [comment]
> cc @yegappan via https://github.com/vim/vim/pull/6638

Sorry I checked the wrong commit; 8.2.1383 instead of 8.2.1384.

**Comment by vim-ml** [comment]
Hi,

On Mon, Aug 31, 2020 at 12:10 PM lacygoill <vim-dev-github@256bit.org>
wrote:

> cc @yegappan <https://github.com/yegappan> via #6638
> <https://github.com/vim/vim/pull/6638>
>
> Sorry I checked the wrong commit; 8.2.1383 instead of 8.2.1384.
>
>
>
The if condition in the existing_swapfile() function needs to be changed as
below:

    if ((buf->b_ml.ml_mfp != NULL) && (buf->b_ml.ml_mfp->mf_fname != NULL))

- Yegappan

**Comment by lacygoill** [comment]
Can confirm that this patch fixes the issue:
```diff
diff --git a/src/quickfix.c b/src/quickfix.c
index 99b0169ea..99847db13 100644
--- a/src/quickfix.c
+++ b/src/quickfix.c
@@ -6022,7 +6022,7 @@ vgr_process_args(
     static int
 existing_swapfile(buf_T *buf)
 {
-    if (buf->b_ml.ml_mfp != NULL)
+    if ((buf->b_ml.ml_mfp != NULL) && (buf->b_ml.ml_mfp->mf_fname != NULL))
     {
 	char_u *fname = buf->b_ml.ml_mfp->mf_fname;
 	size_t len = STRLEN(fname);
```
Thank you @yegappan.
