### ISSUE TITLE
End of line cannot be used inside a collection

### ISSUE THREAD

**Issue by sheerun** [vim/vim#6828]
**Describe the bug**

The documentation on regexps says:

```
|/^|	^	^	start-of-line (at start of pattern) |/zero-width|
|/\^|	\^	\^	literal '^'
|/\_^|	\_^	\_^	start-of-line (used anywhere) |/zero-width|
|/$|	$	$	end-of-line (at end of pattern) |/zero-width|
|/\$|	\$	\$	literal '$'
|/\_$|	\_$	\_$	end-of-line (used anywhere) |/zero-width|
```

Unfortunately it seems `\_$` and `\_^` cannot be used anywhere in pattern as advertised

**To Reproduce**

```vim
echo "type" =~ 'type[\_$]'
```

or

```vim
echo "type" =~ '[\_^]type'
```

**Expected behavior**

`1` should be displayed (match), instead it shows `0`

**Environment (please complete the following information):**
 - Vim version:

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul 27 2020 01:26:07)
macOS version
Included patches: 1-1300

 - OS: Macos
 - Terminal: iterm

**Comment by chrisbra** [comment]
What are you trying to match?

**Comment by lacygoill** [comment]
[A collection](https://vimhelp.org/pattern.txt.html#/collection) describes a set of characters:

> A collection.  This is a sequence of **characters** enclosed in brackets.

`\_^` and `\_$` are zero-width atoms; they don't describe characters but positions.  As such, they lose their special meaning inside a collection.  To include a newline inside a collection, you can either write `\n` (e.g. `[...\n...]`), or prepend `\_` to the collection (e.g. `\_[...]`).

**Comment by sheerun** [comment]
Either end of line or end of word, so both `foobar` and `foobar foobaz` would match (there's no new line character at the end)

**Comment by sheerun** [comment]
Here's example that I could not use:

```
echo "foobar" =~ 'foobar[\_$\W]'
echo "foobar yolo" =~ 'foobar[\_$\W]'
```

both should match but none is

**Comment by sheerun** [comment]
@lacygoill If that's on purpose then it would be nice if documentation said something like `used anywhere except collections` instead of `used anywhere` :) For me it's non-issue because for example `foobar\(\_$\|\W\)` would match above

**Comment by chrisbra** [comment]
So this is only a documentation update. Can you suggest an improvement that fits in the line?

**Comment by chrisbra** [comment]
or perhaps just removing the `used anyhwere` is sufficient?

**Comment by sheerun** [comment]
I think replacing it with `atom` would be most helpful, as it suggests to research where atom can be placed

**Comment by chrisbra** [comment]
but wouldn't a user than again try to put it into a collation?

**Comment by lacygoill** [comment]
The "anywhere" of `\_^` is there to contrast with the "at start of pattern" of `^`.

It could be replaced with "can be used inside pattern".  This would still contrast with "at start of pattern"; i.e. the user would understand that one atom is limited to the start of the pattern, while the other has no such restriction.  But it uses a less absolute language ("anywhere" vs "can").
```diff
diff --git a/runtime/doc/pattern.txt b/runtime/doc/pattern.txt
index f9a34d4a2..228997b2f 100644
--- a/runtime/doc/pattern.txt
+++ b/runtime/doc/pattern.txt
@@ -477,10 +477,10 @@ More explanation and examples below, follow the links.
       magic   nomagic	matches ~
 |/^|	^	^	start-of-line (at start of pattern) |/zero-width|
 |/\^|	\^	\^	literal '^'
-|/\_^|	\_^	\_^	start-of-line (used anywhere) |/zero-width|
+|/\_^|	\_^	\_^	start-of-line (can be used inside pattern) |/zero-width|
 |/$|	$	$	end-of-line (at end of pattern) |/zero-width|
 |/\$|	\$	\$	literal '$'
-|/\_$|	\_$	\_$	end-of-line (used anywhere) |/zero-width|
+|/\_$|	\_$	\_$	end-of-line (can be used inside pattern) |/zero-width|
 |/.|	.	\.	any single character (not an end-of-line)
 |/\_.|	\_.	\_.	any single character or end-of-line
 |/\<|	\<	\<	beginning of a word |/zero-width|
```

**Comment by chrisbra** [comment]
understood. But I am wondering if this is actually helpful. I would just remove the `(used anywhere)` and be done with it. I think that using `(can be used inside pattern)` could also be understood as using `\_^` inside a collation, which also is a pattern.

**Comment by sheerun** [comment]
I agree with @chrisbra either remove it or mention this is an atom

**Comment by lacygoill** [comment]
> or mention this is an atom

The help says that's it's an atom here:
https://github.com/vim/vim/blob/2f1228463aa9ff62814f9732561b1849e5f01f75/runtime/doc/pattern.txt#L473
and here:
https://github.com/vim/vim/blob/2f1228463aa9ff62814f9732561b1849e5f01f75/runtime/doc/pattern.txt#L476

The fact that it's an atom is irrelevant.  `\n` is also an atom.  An atom just means that the sequence of metacharacters can't be further divided without losing the original meaning.  What is really helpful is the fact that the descriptions for both atoms `\_^` and `\_$` are followed by the tag `|/zero-width|`, which means that they don't describe characters, and therefore can't be included inside a collection.

**Comment by sheerun** [comment]
I also agree, so:

```
|/\_^|	\_^	\_^	start-of-line                       |/zero-width|
```

And maybe write explicitly that zero-witdth atoms are not considered characters so no one needs to guess:

```
[]	(with 'nomagic': \[])		*/[]* */\[]* */\_[]* */collection*
\_[]
	A collection.  This is a sequence of characters enclosed in brackets.
        Note: zero-width atoms like \_$ or \> are not characters
```

**Comment by chrisbra** [comment]
no that is not correct. Then the next one is trying to add \%d atoms. Collections only allow characters, no patterns and no atoms. It's basically just a white list for what literal characters are allowed (or blacklist for `[^]`) with the exception of i believe `\n` and `\t` as special notation for the new line and tab

**Comment by brammool** [comment]
It's probably the easiest to understand to say "any position, but not inside []".  The "any position" is needed to balance with "at start of the patter".

**Comment by tonymec** [comment]
The way I understand it, a [] collection is a single atom, and the rules about the meanings of what you put inside it are different from the rules about what you put outside it. To take an obvious example: ^ as the first character of a _pattern_ (outside any collection) means "start of line" but a ^ immediately after the opening [ of a _collection_ means "not". Conversely (as explained in the help) the two ways to include a linebreak in a [] collection are:
* Use a [] collection and prefix it by an underscore, changing it to \_[]
* Include \r inside it.
Again, the rules are different inside and out. Similarly, the "named" classes can only be used inside a collection: "any letter, digit or whitespace" could be specified as [[:alnum:][:blank:]], but without the outside pair of [], [:alnum:][:space:] would mean "one of : a l m n u followed by one of : a c e p s", a totally different (and probably undesired) meaning.

**Comment by tonymec** [comment]
Well, this posting engin got me again, I meant:

* Use a `[]` collection and prefix it by an underscore, changing it to `\_[]`

**Comment by sheerun** [comment]
`\_[]` matches literal `\n`, not zero-length `\n` (i.e. one that includes the end of string)
