### ISSUE TITLE
CursorColumn doesn't respect background color

### ISSUE THREAD

**Issue by unode** [vim/vim#683]
In the screenshot below the word `CursorLocator` was being searched (highlighted).
The image also shows how in the current line the highlight background color is kept while for the column the background color is not.
This happens in both `vim` and `gvim` (7.4.1342).

![CursorColumn/CursorLine](https://cloud.githubusercontent.com/assets/122319/13724982/fbb1deb8-e895-11e5-85c8-fd1df2fe701b.png)

**Comment by mattn** [comment]
I get different result

![](https://i.gyazo.com/a23228c71ba828ed3926477fa9d11ed6.png)

**Comment by unode** [comment]
Hi @mattn,

Could you attach your colorscheme file? I wonder if some rule is causing this. I have tried different colorschemes and I get it consistently.
Also, which version of vim are you using?

**Comment by mattn** [comment]
I use this https://github.com/altercation/vim-colors-solarized and latest of repository of vim

**Comment by unode** [comment]
Thanks for the solarized theme. With it I can no longer reproduce the issue.
However using any of the built-in colorschemes still displays the problem.

I haven't been able to pinpoint how the solarized theme fixes this.
Solarized is a very different theme with lots of dynamic code so I'm not sure if it doesn't workaround the original problem by the dynamic way it sets the colorscheme.

**Comment by lifepillar** [comment]
See

```
:hi Search
:hi CursorColumn
```

The key is that `Search` uses `reverse`. Besides, both `Search` and `CursorColumn` only set the background color.

**Comment by chrisbra** [comment]
okay, closing it then. Please discuss user questions on the vim-use ml.
