### ISSUE TITLE
irrelevant information at ":h map-<expr>"

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6834]
The help at `:h map-<expr>` contains this paragraph at the end:
https://github.com/vim/vim/blob/2f1228463aa9ff62814f9732561b1849e5f01f75/runtime/doc/map.txt#L292-L300

   > Note that there are some tricks to make special keys work and escape CSI bytes
   > in the text.  The |:map| command also does this, thus you must avoid that it
   > is done twice.  This does not work: >
   >         :imap <expr> <F3> "<Char-0x611B>"
   > Because the <Char- sequence is escaped for being a |:imap| argument and then
   > again for using <expr>.  This does work: >
   >         :imap <expr> <F3> "\u611B"
   > Using 0x80 as a single byte before other text does not work, it will be seen
   > as a special key.

Most of this (if not all) is no longer relevant since [7.3.283](https://github.com/vim/vim/releases/tag/v7.3.283).  I've checked, and the patch fixed the issue which is described.  I think the workaround could be removed, because the underlying issue was fixed more than 9 years ago, and it's confusing to read it now (at least it was for me the first time I read it since I could not reproduce the issue).

**Comment by lacygoill** [comment]
Unrelated but this item in the todo list has been fixed by [8.1.0017](https://github.com/vim/vim/releases/tag/v8.1.0017):

https://github.com/vim/vim/blob/9c2b06637b32742cac11bfd66b1a4e84583c6c2e/runtime/doc/todo.txt#L1225

   > Completion for :!cmd shows each match twice. #1435

And this other todo item has been fixed by [8.0.0060](https://github.com/vim/vim/releases/tag/v8.0.0060):
https://github.com/vim/vim/blob/9c2b06637b32742cac11bfd66b1a4e84583c6c2e/runtime/doc/todo.txt#L1425-L1426

   > When 'keywordprg' starts with ":" the argument is still escaped as a shell
   > command argument. (Romain Lafourcade, 2016 Oct 16, #1175)

I think they could both be removed from the todo list.

**Comment by lacygoill** [comment]
Closing, since *if* this is correct, the items will be removed in the next update of the runtime files.

**Comment by lacygoill** [comment]
> I've checked, and the patch fixed the issue which is described.

On 7.3.282:

    $ ./src/vim -Nu NONE +'imap <expr> <F3> "<Char-0x611B>"' +'call feedkeys("i\<f3>")'

    愛ýQ
    ^--^
     ✘

On 7.3.283:

    $ ./src/vim -Nu NONE +'imap <expr> <F3> "<Char-0x611B>"' +'call feedkeys("i\<f3>")'

    愛
    ^
    ✔

**Comment by brammool** [comment]
Thanks, I'll update the docs.  Please keep issues open until they are actually fixed, otherwise they might go missing.
