### ISSUE TITLE
b2d0e51366dea6843f991f31a457f5456d162678 fails with linkage error on HP-UX

### ISSUE THREAD

**Issue by michael-o** [vim/vim#6838]
**Describe the bug**
b2d0e51366dea6843f991f31a457f5456d162678 introduced the usage of `dirfd()` which is unfortunately not available on HP-UX. Linking fails with unsatisfied symbol. The test in `configure.ac` compiles only, but does not link:

```
configure:13760: checking for dirfd
configure:13774: /opt/aCC/bin/aCC -Ae -c -g -I/opt/ports/include conftest.c >&5
"conftest.c", line 149: warning #2223-D: function "dirfd" declared implicitly
  DIR * dir=opendir("dirname"); dirfd(dir);
                                ^

configure:13774: $? = 0
configure:13775: result: yes
```

but it should be rather:
```
bash-5.0$ cc -o out test.c
"test.c", line 5: warning #2223-D: function "dirfd" declared implicitly
  DIR * dir=opendir("dirname"); dirfd(dir);
                                ^

ld: Unsatisfied symbol "dirfd" in file test.o
1 error.
bash-5.0$ echo $?
1
```

**Solution**
Either one needs to try link the application or do the naive patch I have done:
```
# if defined(UNIX) && defined(HAVE_FLOCK) && defined(HAVE_DIRFD)
# ifdef __hpux
#define dirfd(x) ((x)->__dd_fd)
#endif
...
```

Note: `flock()` is present on HP-UX.

After the patch:
```
bash-5.0$ ldd src/vim

src/vim:
        libm.so.1 =>    /usr/lib/hpux32/libm.so.1
        libxcurses.so.1 =>      /usr/lib/hpux32/libxcurses.so.1
        libintl.so.10 =>        /opt/ports/lib/hpux32/libintl.so.10
        libc.so.1 =>    /usr/lib/hpux32/libc.so.1
        libiconv.so.8 =>        /opt/ports/lib/hpux32/libiconv.so.8
        libc.so.1 =>    /usr/lib/hpux32/libc.so.1
        libdl.so.1 =>   /usr/lib/hpux32/libdl.so.1
        libc.so.1 =>    /usr/lib/hpux32/libc.so.1
bash-5.0$ file src/vim
src/vim:        ELF-32 executable object file - IA64
```

**Environment (please complete the following information):**
 - Vim version 8.2.1551
 - OS: HP-UX deblndw0 B.11.31 U ia64 HP-U
 - Terminal: PuTTY and dtterm

**References**
* https://www.mail-archive.com/search?l=help-cfengine@cfengine.org&q=subject:%22Cannot+compile+cfengine%5C-3.2.0.tar.gz+on+Solaris+10%22&o=newest&f=1
* https://openqnx.com/phpbbforum/viewtopic.php?f=20&t=4272#p16959
* https://womble.decadent.org.uk/readdir_r-advisory.html

**Comment by zdohnal** [comment]
Hi @michael-o ,

do you want the feature which the mentioned pull request brought available on HP-UX?

Either way, I propose to use AC_TRY_LINK instead of AC_TRY_COMPILE. It will catch the error and the feature will not be used.

**Comment by michael-o** [comment]
> 
> 
> Hi @michael-o ,
> 
> do you want the feature which the mentioned pull request brought available on HP-UX?
> 
> Either way, I propose to use AC_TRY_LINK instead of AC_TRY_COMPILE. It will catch the error and the feature will not be used.

I won't insist, but I would like to have consistency across platforms since `dirfd()` is likely to be a macro on other platforms too, it is fairly easy to add this for HP-UX. I checked the FreeBSD libc code and it is just a macro with wrapper call. I see no reason not to support this on HP-UX.

**Comment by zdohnal** [comment]
Ok, would you mind trying this 
[patch](https://github.com/vim/vim/files/5161464/vim-hpux.patch.txt) if it works on HP-UX?

**Comment by michael-o** [comment]
@zdohnal Going through...

**Comment by michael-o** [comment]
The check now properly fails:

```
configure:13760: checking for dirfd
configure:13774: /opt/aCC/bin/aCC -Ae -o conftest -g -I/opt/ports/include -L/opt/ports/lib/hpux32 conftest.c -lm -lelf  -lcurses -liconv >&5
"conftest.c", line 149: warning #2223-D: function "dirfd" declared implicitly
  DIR * dir=opendir("dirname"); dirfd(dir);
                                ^

ld: Unsatisfied symbol "dirfd" in file conftest.o
1 error.
...
configure:13779: result: not usable
```

and vim links correctly. Though I don't understand the hunk in `fileio.c`. Although you define this macro, it is never used because the function `vim_opentempdir()` is guarded by `defined(HAVE_DIRFD)` which is not set now in `config.h`.

**Comment by zdohnal** [comment]
(facepalm) You're right, sorry - another iteration...

**Comment by zdohnal** [comment]
Here we go 
[vim-hpux.patch.txt](https://github.com/vim/vim/files/5161853/vim-hpux.patch.txt)

**Comment by michael-o** [comment]
This one is incomplete, it ignores:
```
#ifdef TEMPDIRNAMES
# if defined(UNIX) && defined(HAVE_FLOCK) && defined(HAVE_DIRFD)
EXTERN DIR      *vim_tempdir_dp INIT(= NULL); // File descriptor of temp dir
# endif
```
from `globals.h`

**Comment by zdohnal** [comment]
Please check now 
[vim-hpux.patch.txt](https://github.com/vim/vim/files/5162045/vim-hpux.patch.txt)

**Comment by michael-o** [comment]
@zdohnal Patch works for me now.

**Comment by michael-o** [comment]
@zdohnal @brammool Thank you for the quick turnaround!

**Comment by zdohnal** [comment]
@michael-o I'm sorry for the inconvenience which my previous patch brought and thank you @brammool for pushing the changes!
