### ISSUE TITLE
netrw suppress '@' when editing a file (from ssh)

### ISSUE THREAD

**Issue by lesurp** [vim/vim#684]
When SSHing to a directory using vim:

`scp://user@host//dir/`

and you want to edit a file, the command will read as:

`scp://userhost//dir/file #<- '@' is missing !`

An empty file is then opened, and if saved, will override the real, potentially non empty, remote file.
It makes the whole ssh functionality almost useless in my opinion (unless you connect without specifying a username)

**Comment by chrisbra** [comment]
closing. Please continue discussion here: https://groups.google.com/d/msg/vim_dev/GAdDerLaA_s/tB1txJPMFwAJ
