### ISSUE TITLE
prop_find() fails to find previous text property when several before on same line

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6841]
**Describe the bug**

`prop_find()` fails to find the previous text property when there are several properties before the cursor, and they are on the same line.  It always finds the first one, regardless of whether there are other properties between the first one and the cursor.

**To Reproduce**

Write this test in `src/testdir/test_textprop.vim`:
```vim
func Test_prop_find_prev_on_same_line()
  call setline(1, 'the quikc bronw fox jumsp over the layz dog')
  call prop_type_add('misspell', #{highlight: 'ErrorMsg'})
  for col in [8, 14, 24, 38]
    call prop_add(1, col, #{type: 'misspell', length: 2})
  endfor
  norm! $
  let expected = #{lnum: 1, id: 0, col: 38, end: 1, type: 'misspell', length: 2, start: 1}
  let result = prop_find(#{type: 'misspell'}, 'b')
  call assert_equal(expected, result)
endfunc
```
Run the test:

    vim -u NONE -S runtest.vim test_textprop.vim prop_find_prev_on_same_line

The test fails:

    From test_textprop.vim:
    Found errors in Test_prop_find_prev_on_same_line():
    command line..script /home/user/Vcs/vim/src/testdir/runtest.vim[456]..function RunTheTest[39]..Test_prop_find_prev_on_same_line line 9: Expected {'col': 38} but got {'col': 8} - 6 equal items omitted

**Expected behavior**

The test passes.

**Environment**

 - Vim version: 8.2 Included patches: 1-1565
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(359)

**Additional context**

The test as a patch:
```diff
diff --git a/src/testdir/test_textprop.vim b/src/testdir/test_textprop.vim
index 9db5275d5..444de91fa 100644
--- a/src/testdir/test_textprop.vim
+++ b/src/testdir/test_textprop.vim
@@ -224,6 +224,18 @@ func Test_prop_find_smaller_len_than_match_col()
   call prop_type_delete('test')
 endfunc
 
+func Test_prop_find_prev_on_same_line()
+  call setline(1, 'the quikc bronw fox jumsp over the layz dog')
+  call prop_type_add('misspell', #{highlight: 'ErrorMsg'})
+  for col in [8, 14, 24, 38]
+    call prop_add(1, col, #{type: 'misspell', length: 2})
+  endfor
+  norm! $
+  let expected = #{lnum: 1, id: 0, col: 38, end: 1, type: 'misspell', length: 2, start: 1}
+  let result = prop_find(#{type: 'misspell'}, 'b')
+  call assert_equal(expected, result)
+endfunc
+
 func Test_prop_add()
   new
   call AddPropTypes()
```

**Comment by brammool** [comment]
Fixed with patch 8.2.4787, see #10220
