### ISSUE TITLE
How to avoid to open an outside new terminal window if set default terminal is Windows Termial on Windows 10

### ISSUE THREAD

**Issue by jiangjianshan** [vim/vim#6843]
Hello,

I'm using Vim 8.2.1563 on Windows 10.  I have changed the default terminal to wt.exe which is Windows Terminal introduce on Windows 10.

The setting of my _vimrc is here:
![image](https://user-images.githubusercontent.com/20179047/92068355-4b958e00-edd9-11ea-8a9a-1b62f919513b.png)

Before I have add above three lines into _vimrc, I use ':ter' open terminal windows, it will look like here:
![image](https://user-images.githubusercontent.com/20179047/92068979-dc209e00-edda-11ea-86e3-e420d0700fd1.png)

But after add them, if I input command ':ter' and try to open terminal inside Vim's windows, but actually it open outside.
![image](https://user-images.githubusercontent.com/20179047/92068394-5e0fc780-edd9-11ea-883d-2bb0d673320a.png)

If I change 'set shell=wt.exe‘ to 'set shell=bash.exe', or 'set shell=cmd.exe' . The terminal by base.exe or cmd.exe can exactly open inside Vim's window. Is there some setting missing for my _vimrc about 'set shell=wt.exe'?

**Comment by k-takata** [comment]
Windows Terminal is a terminal emulator. It's not a shell. So, setting `shell=wt.exe` is wrong.

Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. Closing.
