### ISSUE TITLE
./configure takes too long/does not return?

### ISSUE THREAD

**Issue by matthiasbeyer** [vim/vim#6845]
**Describe the bug**

`./configure --prefix=/usr/local/vim/8.2.1578 --libdir=/usr/local/vim/8.2.1578/lib` is what I call. It's been running without any output for about two hours now.

**To Reproduce**

I'm not sure what causes this, so I'm also not sure how to reproduce this.

**Expected behavior**

`./configure` should return, of course.

**Environment (please complete the following information):**
 - 8.2.1578
 - OS: centos 7

**Comment by lacygoill** [comment]
Try `strace(1)`.

In terminal 1:

    strace -o /tmp/trace ./configure --prefix=/usr/local/vim/8.2.1578 --libdir=/usr/local/vim/8.2.1578/lib

In terminal 2:

    tail -F /tmp/trace

**Comment by brammool** [comment]
What is the tail of the output you see?

**Comment by matthiasbeyer** [comment]
I see no tail output. I will try strace on Tuesday, as this is actually for my paid job and I'm not returning to office until then :-P

**Comment by matthiasbeyer** [comment]
So the output seems loopy... what catches my eyes is:

```
execve("/path/to/vimsource/vim-8.2.1578/configure", ["./configure", "--prefix=/usr/local/vim/8.2.1578", "--libdir=/usr/local/vim/8.2.1578"...], [/* 83 vars */]) = 0
```

which appears multiple times:


```
$ cat /tmp/trace | grep ^execve | sort  | uniq -c
      1 execve("./configure", ["./configure", "--prefix=/usr/local/vim/8.2.1578", "--libdir=/usr/local/vim/8.2.1578"...], [/* 84 vars */]) = 0
  17948 execve("/path/to/vimsource/vim-8.2.1578/configure", ["./configure", "--prefix=/usr/local/vim/8.2.1578", "--libdir=/usr/local/vim/8.2.1578"...], [/* 83 vars */]) = 0
```

**Comment by k-takata** [comment]
How about executing `./configure` in the `src` directory?

```shell
$ cd src
$ ./configure --prefix=/usr/local/vim/8.2.1578 --libdir=/usr/local/vim/8.2.1578/lib
```

Do you set `$SRCDIR` variable?

**Comment by matthiasbeyer** [comment]
> Do you set $SRCDIR variable?

Oh! Yes, our build setup uses this variable. Is that a problem?

**Comment by matthiasbeyer** [comment]
`cd`ing into `./src` and executing `./configure` seems to solve my problem. Thanks!
