### ISSUE TITLE
:sort sorts Japanese wrong

### ISSUE THREAD

**Issue by nielsk** [vim/vim#685]
I have this list after :sort 

作花文雄:著作権法
夏目漱石: こころ（前編）
岩本さゆみ:新·マネー敗戦 
日本の論点2008
日本の論点2009
高見広春: Battle Royale

But it should be (Gojūon):
岩本さゆみ:新·マネー敗戦 
作花文雄:著作権法
高見広春: Battle Royale
夏目漱石: こころ（前編）
日本の論点2008
日本の論点2009

Or (alphabet):
岩本さゆみ:新·マネー敗戦 
高見広春: Battle Royale
夏目漱石: こころ（前編）
日本の論点2008
日本の論点2009
作花文雄:著作権法

vim-version: 7.4.1556 on Linux (Fedora 23; vim installed via copr)

**Comment by vim-ml** [comment]
Hello,

On 14/03/16 14:35, Niels Kobschätzki (Vim Github Repository) wrote:

> I have this list after :sort
> 
> 作花文雄:著作権法
> 夏目漱石: こころ（前編）
> 岩本さゆみ:新·マネー敗戦
> 日本の論点2008
> 日本の論点2009
> 高見広春: Battle Royale
> 
> But it should be (Gojūon):
> 岩本さゆみ:新·マネー敗戦
> 作花文雄:著作権法
> 高見広春: Battle Royale
> 夏目漱石: こころ（前編）
> 日本の論点2008
> 日本の論点2009
> 
> Or (alphabet):
> 岩本さゆみ:新·マネー敗戦
> 高見広春: Battle Royale
> 夏目漱石: こころ（前編）
> 日本の論点2008
> 日本の論点2009
> 作花文雄:著作権法

Actually, your alphabetical sort prediction is wrong. In this case it 
should be:

岩本さゆみ (Iwamoto Sayumi)
夏目漱石 (Natsume Sosuke)
日本の論点2008 (Nihon no ronten 2008)
日本の論点2009 (Nihon no ronten 2009)
作花文雄  (Sakka Fumio)
高見広春 (Takami Koushun)

Japanese sorts are typically done using the Hiragana pronunciation (Goju-on)
of the word, not alphabetical, regardless of the chinese character used, and
this requires a database lookup of actual name to pronunciation for every
word being sorted.

I haven't checked, but Vim is probably using either JIS or Unicode 
sorting rules
to do its work. I wouldn't expect anything more than that.

Cheers

**Comment by e-kwsm** [comment]
@nielsk vim doesn't know their pronunciation.
But vim cannot sort even hiragana (ひらがな) and katakana (カタカナ) correctly!

The correct order is
カン
さつき
さっき
さつきばれ
さっきばれ
しや
しゃ
しやく
しゃく
but vim (7.4.576 on Debian) sort like
さっき
さっきばれ
さつき
さつきばれ
しゃ
しゃく
しや
しやく
カン

The problems are:
- Yōon (拗音; "ゃ") and sokuon (促音; "っ") have higher priority than usual characters ("や" and "つ")
- Hiragana has higher priority than katakana, regardless of pronunciation

**Comment by vim-ml** [comment]
On 14/03/16 15:59, E Kawashima (Vim Github Repository) wrote:

> @nielsk https://github.com/nielsk vim doesn't know their pronunciation.
> But vim cannot sort even hiragana (ひらがな) and katakana (カタカナ) 
> correctly!
> 
> The correct order is
> カン
> さつき
> さっき
> さつきばれ
> さっきばれ
> しや
> しゃ
> しやく
> しゃく
> but vim (7.4.576 on Debian) sort like
> さっき
> さっきばれ
> さつき
> さつきばれ
> しゃ
> しゃく
> しや
> しやく
> カン

This is because VIM is using Unicode codepoint value as the sort order.
In Unicode, the order of character codepoints in the Hiragana block is:

ぁあぃいぅうぇえぉおっつ etc.

i.e. the codepoint for the sokuon always appears before the codepoint
for its normal counterpart.

Cheers.

**Comment by vim-ml** [comment]
Hmmm… AFAIK this order is not "wrong", it is merely based on Unicode
codepoint value. When doing ga on the first character of each line in
your first example, they are in increasing Unicode sequence, except
lines 4 and 5 which differ only in their last character.

See the following remark near the end of ":help :sort":

<quote>
The details about sorting depend on the library function used.  There is no
guarantee that sorting obeys the current locale.  You will have to try it out.
Vim does do a "stable" sort.
</quote>

However, when I use the external "sort" filter with $LC_COLLATE set to
ja_JP.utf8, I get a different sequence, namely

夏目漱石: こころ（前編）
岩本さゆみ:新·マネー敗戦
高見広春: Battle Royale
作花文雄:著作権法
日本の論点2008
日本の論点2009

which is neither of those you mention. Is this one meaningful for you?
I don't know what Japanese sorting "ought" to give for an arbitrary
sequence of mixed kanji and kana.

Best regards,
Tony.

**Comment by e-kwsm** [comment]
@vim-ml 

> 夏目漱石: こころ（前編）
> 岩本さゆみ:新·マネー敗戦
> 高見広春: Battle Royale
> 作花文雄:著作権法
> 日本の論点2008
> 日本の論点2009

I don't feel meaningful.

**Comment by k-takata** [comment]
Hi Tony and @e-kwsm,

> 夏目漱石: こころ（前編）
> 岩本さゆみ:新·マネー敗戦
> 高見広春: Battle Royale
> 作花文雄:著作権法
> 日本の論点2008
> 日本の論点2009

This order is based on JIS Kanji code, so this order is the same as when you use CP932 or EUC-JP.
It is useful when you need compatibility with these encodings.

**Comment by mattn** [comment]
As @k-takata says, it's depend on the encoding of text. If you expect the order, you should convert encoding before/after sorting.

```
cat text.txt | iconv -f utf-8 -t cp932  | sort | iconv -f cp932 -t utf-8
```

**Comment by chrisbra** [comment]
closing. Please discuss user questions on vim-use ml
