### ISSUE TITLE
Editing multiple lines with Visual mode breaks <number>V feature of vim

### ISSUE THREAD

**Issue by ghost** [vim/vim#6859]
**Describe the bug**
1.When i select multiple lines with Visual mode and try to edit them: with '<,'>s/text/empty/<cr> or just '<,'>norm ^i//<cr>
2. After that when i try to select lines with Visual Line-block, like (number)V - it selects double of that count(if i've edited 2 lines before), or triple(if 3 lines was edited before) and etc. Like if i've (2)V - it select (4)V and etc.

**Environment (please complete the following information):**
 - Vim version 8.2.1-1558
 - OS: Debian 10
 - Terminal: xfce4-terminal

**Comment by brammool** [comment]
This works as documented under the "v" command: ":help v".
Only that with "V" it works on lines.
