### ISSUE TITLE
vim crashed with SEGV in __find_specmb (sequence seemingly in response to shell resize)

### ISSUE THREAD

**Issue by sinaraya** [vim/vim#6864]
I was running vim inside tmux (integrated with iterm2). vim was running with several terminal (shell) buffers. Overnight my laptop went to sleep, and after connecting to my server, I attached to my tmux session. I saw a lot of vim error messages which seemed to relate to shell resize (I am not sure why), and then I got:

======= Backtrace: =========
/lib/libc.so.6(+0x7f8b6)[0xf74a58b6]
/lib/libc.so.6(__libc_malloc+0xa4)[0xf74a6cd4]
vim(lalloc+0x4d)[0x812c9fd]
vim(prepare_viminfo_history+0x7b)[0x80e60bb]
vim[0x80bc079]
vim(write_viminfo+0x282)[0x80bcbc2]
vim(getout+0x26c)[0x8236a0c]
vim(preserve_exit+0x76)[0x8129f36]
[0xf77cab30]
/lib/libc.so.6(+0x156611)[0xf757c611]
vim[0x819282e]
vim(screen_del_lines+0x37d)[0x8198dad]
vim[0x823a00e]
vim[0x823df50]
vim[0x823ea1e]
vim(msg_putchar_attr+0x3f)[0x823ebef]
vim(msg_start+0x11c)[0x824081c]
vim(msg_attr_keep+0x7a)[0x82408da]
vim(emsg+0x1e2)[0x8240f52]
vim(ml_get_buf+0xd4)[0x8116ae4]
vim(plines_win_nofold+0x19)[0x811f789]
vim(plines_win_nofill+0x48)[0x811f858]
vim(plines_win+0x19)[0x811f889]
vim(curs_columns+0x59c)[0x8134b0c]
vim(scroll_to_fraction+0x214)[0x81fd9b4]
vim[0x81fdb6e]
vim(shell_new_rows+0x56)[0x81fddb6]
vim(win_new_shellsize+0x41)[0x81dfad1]
vim(screenalloc+0x8c)[0x8194aac]
vim(screenclear+0x19)[0x8195369]
vim(set_shellsize+0xb9)[0x81dfbd9]
vim(shell_resized+0x11)[0x81dfd61]
vim[0x816384f]
vim[0x8163b82]

The terminal output was actually completely messed up, I had to quit that shell instance.  

![vim-busted-terminal-output](https://user-images.githubusercontent.com/8021311/92253895-f747e800-ee84-11ea-93bb-26f8b83afb88.jpg)

Using a different shell instance, I captured the backtrace with gdb from the core file:

Program terminated with signal SIGSEGV, Segmentation fault.
#0  __find_specmb (format=0x8247de0 "# This viminfo file was generated by Vim %s.\n") at printf-parse.h:109
109	  return (const unsigned char *) __strchrnul ((const char *) format, '%');

(gdb) bt
#0  __find_specmb (format=0x8247de0 "# This viminfo file was generated by Vim %s.\n") at printf-parse.h:109
#1  _IO_vfprintf_internal (s=0xf6a00a28, format=0x8247de0 "# This viminfo file was generated by Vim %s.\n", ap=0xa1194b8 "\223u$\b\005\303\v\b(\n\240", <incomplete sequence \366>)
    at vfprintf.c:1308
#2  0xf7477ea5 in __fprintf (stream=0xf6a00a28, format=0x8247de0 "# This viminfo file was generated by Vim %s.\n") at fprintf.c:32
#3  0x080bc0fe in do_viminfo (fp_in=0x0, fp_out=0xf6a00a28, flags=136583204) at ex_cmds.c:2206
#4  0x080bcbc2 in write_viminfo (file=0x0, forceit=0) at ex_cmds.c:2076
#5  0x08236a0c in getout (exitval=1) at main.c:1465
#6  0x081656e8 in deathtrap (sigarg=6) at os_unix.c:1204
#7  <signal handler called>
#8  0xf77cab19 in __kernel_vsyscall ()
#9  0xf7453c08 in __GI_raise (sig=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:55
#10 0xf7455a96 in __GI_abort () at abort.c:90
#11 0xf749a486 in __libc_message (do_abort=<optimized out>, fmt=<optimized out>) at ../sysdeps/unix/sysv/linux/libc_fatal.c:196
#12 0xf74a58b6 in malloc_printerr (ar_ptr=0xf75f6780 <main_arena>, ptr=0xb952e40, str=0xf75b1606 "corrupted double-linked list", action=3) at malloc.c:5175
#13 _int_malloc (av=av@entry=0xf75f6780 <main_arena>, bytes=bytes@entry=800) at malloc.c:3709
#14 0xf74a6cd4 in __GI___libc_malloc (bytes=800) at malloc.c:2906
#15 0x0812c9fd in lalloc (size=800, message=0) at misc2.c:976
#16 0x080e60bb in prepare_viminfo_history (asklen=0, writing=1) at ex_getln.c:6436
#17 0x080bc079 in read_viminfo_up_to_marks (writing=<optimized out>, forceit=<optimized out>, virp=<optimized out>) at ex_cmds.c:2265
#18 do_viminfo (fp_in=0xb988730, fp_out=0xb1c4cf0, flags=4384) at ex_cmds.c:2189
#19 0x080bcbc2 in write_viminfo (file=0x0, forceit=0) at ex_cmds.c:2076
#20 0x08236a0c in getout (exitval=1) at main.c:1465
#21 0x08129f36 in preserve_exit () at misc1.c:9656
#22 <signal handler called>
#23 __memset_sse2_rep () at ../sysdeps/i386/i686/multiarch/memset-sse2-rep.S:242
#24 0x0819282e in memset (__len=<optimized out>, __ch=<optimized out>, __dest=<optimized out>) at /usr/include/bits/string3.h:84
#25 lineclear (off=173080611, width=191, attr=0) at screen.c:9141
#26 0x08198dad in screen_del_lines (off=0, row=0, line_count=1, end=37, force=1, clear_attr=0, wp=0x0) at screen.c:10144
#27 0x0823a00e in msg_scroll_up () at message.c:2311
#28 0x0823df50 in msg_puts_display (str=0x20202020 <error: Cannot access memory at address 0x20202020>, maxlen=-3542922, attr=-1, recurse=0) at message.c:2104
#29 0x0823ea1e in msg_puts_attr_len (str=0xffc9f076 "\n", maxlen=-1, attr=0) at message.c:2036
#30 0x0823ebef in msg_puts_attr (attr=<optimized out>, s=<optimized out>) at message.c:1987
#31 msg_putchar_attr (c=538976288, attr=0) at message.c:1406
#32 0x0824081c in msg_putchar (c=<optimized out>) at message.c:1378
#33 msg_start () at message.c:1347
#34 0x082408da in msg_attr_keep (s=0xa11b9d0 "Vim: Caught deadly signal SEGV\n", attr=298, keep=0) at message.c:184
--Type <RET> for more, q to quit, c to continue without paging--
#35 0x08240f52 in msg_attr (attr=<optimized out>, s=<optimized out>) at message.c:131
#36 emsg (s=0xa11b9d0 "Vim: Caught deadly signal SEGV\n") at message.c:711
#37 0x08116ae4 in ml_get_buf (buf=0x0, lnum=9788, will_change=0) at memline.c:2452
#38 0x0811f789 in plines_win_nofold (wp=0xb641f20, lnum=9788) at misc1.c:2014
#39 0x0811f858 in plines_win_nofill (wp=0xb641f20, lnum=9788, winheight=1) at misc1.c:1997
#40 0x0811f889 in plines_win (wp=0xb641f20, lnum=9788, winheight=1) at misc1.c:1966
#41 0x08134b0c in curs_rows (wp=<optimized out>) at move.c:734
#42 curs_columns (may_scroll=0) at move.c:945
#43 0x081fd9b4 in scroll_to_fraction (wp=0xb641f20, prev_height=21) at window.c:5774
#44 0x081fdb6e in frame_new_height (topfrp=0x20202020, height=35, topfirst=191, wfh=1) at window.c:2837
#45 0x081fddb6 in shell_new_rows () at window.c:4801
#46 0x081dfad1 in win_new_shellsize () at term.c:3187
#47 0x08194aac in screenalloc (doclear=0) at screen.c:8814
#48 0x08195369 in screenclear () at screen.c:9071
#49 0x081dfbd9 in set_shellsize (width=0, height=0, mustset=0) at term.c:3289
#50 0x081dfd61 in shell_resized () at term.c:3203
#51 0x0816384f in handle_resize () at os_unix.c:533
#52 RealWaitForChar (fd=0, msec=-3541616, check_for_gpm=0xbf, interrupted=0xffc9f644) at os_unix.c:6243
#53 0x08163b82 in WaitForCharOrMouse (msec=-1, interrupted=0xffc9f644, ignore_input=0) at os_unix.c:5957
#54 0x081ee110 in ui_wait_for_chars_or_timer (wtime=-1, wait_func=0x8163b30 <WaitForCharOrMouse>, interrupted=0xffc9f644, ignore_input=0) at ui.c:242
#55 0x08163e0a in WaitForChar (ignore_input=<optimized out>, interrupted=<optimized out>, msec=<optimized out>) at os_unix.c:5894
#56 mch_inchar (buf=0x82c245b <typebuf_init+59> "", maxlen=68, wtime=-1, tb_change_cnt=54485) at os_unix.c:487
#57 0x081ee080 in ui_inchar (buf=0x82c245b <typebuf_init+59> "", maxlen=68, wtime=-1, tb_change_cnt=54485) at ui.c:190
#58 0x080ff812 in inchar (buf=0x20202020 <error: Cannot access memory at address 0x20202020>, maxlen=368260755, wait_time=191) at getchar.c:3070
#59 0x081012e3 in vgetorpeek (advance=538976288) at getchar.c:2852
#60 0x08102299 in vgetorpeek (advance=<optimized out>) at getchar.c:1693
#61 vgetc () at getchar.c:1610
#62 0x081eb308 in term_vgetc () at terminal.c:1662
#63 terminal_loop (blocking=1) at terminal.c:2024
#64 0x0823759a in main_loop (cmdwin=0, noexmode=0) at main.c:1347
#65 0x08238016 in vim_main2 () at main.c:915
#66 0x0806de72 in main (argc=0, argv=0x0) at main.c:443

**Comment by lacygoill** [comment]
Which Vim version are you using?

If it's older than 8.2.0989, try to reproduce after upgrading Vim.  A few similar issues have been fixed a few months ago:

 - [8.2.0989](https://github.com/vim/vim/releases/tag/v8.2.0989)  crash after resizing a terminal window
 - [8.2.1030](https://github.com/vim/vim/releases/tag/v8.2.1030)  reducing size of a terminal window may cause a crash

**Comment by sinaraya** [comment]
My apologies, I thought I provided the version info. Clearly, I didn't. I am running vim 8.0. Ok, I will try to reproduce once I finish the upgrade process.

**Comment by dpelle** [comment]
If I look at Ubuntu-20.04 vim crashes automatically reported by apport, I see a crash in viminfo which is may related:

https://errors.ubuntu.com/?release=Ubuntu%2020.04&package=vim&period=day

That website has horrible user interface :-(
Anyway, stack in viminfo collected from that web site, which should be with vim-8.1.2269 (so quite old already):
```
Stacktrace

#0  0x00007f1cbaa0555b in kill () from /srv/daisy.ubuntu.com/production/cache/Ubuntu 20.04/cache-3J8USt/sandbox/Ubuntu 20.04/amd64/report-sandbox/lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x000056375de14763 in may_core_dump () at os_unix.c:3368
No locals.
#2  0x000056375de15a0d in may_core_dump () at os_unix.c:1075
No locals.
#3  deathtrap (sigarg=11) at os_unix.c:1072
        entered = 3
        i = <optimized out>
#4  <signal handler called>
No symbol table info available.
#5  0x000056375deca59a in handle_viminfo_history (values=0x7fff29e12300, values=0x7fff29e12300, writing=1) at viminfo.c:633
        sep = 0
        idx = <optimized out>
        overwrite = 0
        type = <optimized out>
        len = 70
        val = <optimized out>
        vp = <optimized out>
        p = 0x56375fba46e0 "\260{_`7V"
        type = <optimized out>
        len = <optimized out>
        val = <optimized out>
        p = <optimized out>
        vp = <optimized out>
        sep = <optimized out>
        idx = <optimized out>
        overwrite = <optimized out>
#6  read_viminfo_barline (writing=1, force=0, got_encoding=<optimized out>, virp=0x7fff29e12320) at viminfo.c:2719
        bartype = <optimized out>
        values = {ga_len = 4, ga_maxlen = 20, ga_itemsize = 32, ga_growsize = 20, ga_data = 0x56376052c000}
        vp = <optimized out>
        i = <optimized out>
        p = 0x5637606870e2 ",1,1599149449,,^    def _get_message(self, data: dict) -> pb3.AvailableSubscription:$"
        read_next = <optimized out>
        p = <optimized out>
        bartype = <optimized out>
        values = <optimized out>
        vp = <optimized out>
        i = <optimized out>
        read_next = <optimized out>
#7  read_viminfo_up_to_marks (writing=<optimized out>, forceit=0, virp=0x7fff29e12320) at viminfo.c:2785
        eof = 0
        buf = <optimized out>
        got_encoding = <optimized out>
        eof = <optimized out>
        buf = <optimized out>
        got_encoding = <optimized out>
#8  do_viminfo (fp_in=fp_in@entry=0x56376018f090, fp_out=fp_out@entry=0x56376003ec60, flags=flags@entry=3) at viminfo.c:2892
        eof = 0
        vir = {vir_line = 0x5637606870e0 "|2,1,1599149449,,^    def _get_message(self, data: dict) -> pb3.AvailableSubscription:$", vir_fd = 0x56376018f090, vir_conv = {vc_type = 0, vc_factor = 1, vc_fd = 0x7f1cbaad0498 <faccessat+120>, vc_fail = 0}, vir_version = 4, vir_barlines = {ga_len = 0, ga_maxlen = 0, ga_itemsize = 8, ga_growsize = 100, ga_data = 0x0}}
        merge = 0
        do_copy_marks = 0
        buflist = {ga_len = 4, ga_maxlen = 20, ga_itemsize = 32, ga_growsize = 20, ga_data = 0x56376052c000}
#9  0x000056375decd034 in write_viminfo (file=<optimized out>, forceit=0) at viminfo.c:3237
        fname = 0x56375ffc9ae0 "/home/mymedia/.viminfo"
        fp_in = 0x56376018f090
        fp_out = <optimized out>
        tempname = 0x56376044b8e0 "/home/mymedia/.viminfz.tmp"
        st_new = {st_dev = 53, st_ino = 4707244, st_nlink = 1, st_mode = 33152, st_uid = 1000, st_gid = 1000, __pad0 = 0, st_rdev = 0, st_size = 4096, st_blksize = 4096, st_blocks = 8, st_atim = {tv_sec = 1599150317, tv_nsec = 193748319}, st_mtim = {tv_sec = 1599150317, tv_nsec = 193748319}, st_ctim = {tv_sec = 1599150317, tv_nsec = 193748319}, __glibc_reserved = {0, 0, 0}}
        umask_save = <optimized out>
        shortname = <optimized out>
        st_old = {st_dev = 53, st_ino = 4707241, st_nlink = 1, st_mode = 33152, st_uid = 1000, st_gid = 1000, __pad0 = 0, st_rdev = 0, st_size = 54931, st_blksize = 4096, st_blocks = 112, st_atim = {tv_sec = 1599150317, tv_nsec = 193748319}, st_mtim = {tv_sec = 1599150316, tv_nsec = 973745673}, st_ctim = {tv_sec = 1599150316, tv_nsec = 985745817}, __glibc_reserved = {0, 0, 0}}
#10 0x000056375df2bdac in getout (exitval=exitval@entry=1) at main.c:1627
No locals.
#11 0x000056375de15a2b in deathtrap (sigarg=15) at os_unix.c:1082
        entered = 3
        i = <optimized out>
#12 <signal handler called>
No symbol table info available.
#13 subtract_refs (containers=<optimized out>) at ../Modules/gcmodule.c:406
        op = 0x7f1cb0cfb5b0
        traverse = 0x7f1cbafaf660 <subtype_traverse>
        gc = 0x7f1cb0cfb5a0
#14 collect.constprop.0 (generation=generation@entry=2, n_collected=n_collected@entry=0x0, n_uncollectable=n_uncollectable@entry=0x0, nofail=nofail@entry=1, state=0x7f1cbb297bd8 <_PyRuntime+344>) at ../Modules/gcmodule.c:1054
        i = <optimized out>
        m = 0
        n = 0
        young = <optimized out>
        old = 0x7f1cbb297c20 <_PyRuntime+416>
        unreachable = {_gc_next = 139761375891488, _gc_prev = 3137020583}
        finalizers = {_gc_next = 139761203814912, _gc_prev = 94795834149768}
        gc = <optimized out>
        t1 = 0
        stats = <optimized out>
#15 0x00007f1cbaecf33d in _PyGC_CollectNoFail () at ../Modules/gcmodule.c:1866
        state = <optimized out>
        n = <optimized out>
#16 _PyGC_CollectNoFail () at ../Modules/gcmodule.c:1848
        state = <optimized out>
        n = 94795824989200
#17 0x00007f1cbaf0ffac in PyImport_Cleanup () at ../Python/import.c:541
        pos = 257
        key = 0x7f1cb0d67f30
        value = 0x7f1cb0d760e0
        dict = 0x7f1cb05461c0
        interp = 0x563760041a60
        modules = 0x7f1cb0ec9d00
        weaklist = 0x7f1cb0eda180
        p = <optimized out>
        verbose = 0
        PyId_clear = {next = 0x0, string = 0x7f1cbb181b73 "clear", object = 0x0}
#18 0x00007f1cbaefb66d in Py_FinalizeEx () at ../Python/pylifecycle.c:1240
        status = <optimized out>
        interp = 0x563760041a60
        malloc_stats = 0
        runtime = <optimized out>
        tstate = 0x56375fac3eb0
        status = <optimized out>
        runtime = <optimized out>
        tstate = <optimized out>
        interp = <optimized out>
        malloc_stats = <optimized out>
        __atomic_load_ptr = <optimized out>
        __atomic_load_tmp = <optimized out>
#19 Py_FinalizeEx () at ../Python/pylifecycle.c:1154
        runtime = <optimized out>
        tstate = <optimized out>
        interp = <optimized out>
        malloc_stats = <optimized out>
        __atomic_load_ptr = <optimized out>
        __atomic_load_tmp = <optimized out>
#20 0x00007f1cbaefb7d5 in Py_Finalize () at ../Python/pylifecycle.c:1381
No locals.
#21 0x000056375df0e4fa in python3_end () at if_python3.c:876
        recurse = 1
#22 0x000056375df2bc55 in getout (exitval=0) at main.c:1685
No locals.
#23 0x00007f1cbbe0ae5b in _SmcProcessMessage (iceConn=0x56375f4bb460, clientData=0x56375f483ec0, opcode=<optimized out>, length=0, swap=0, replyWait=<optimized out>, replyReadyRet=0x7fff29e12ed0) at ../../src/sm_process.c:437
        smcConn = 0x56375f483ec0
#24 0x00007f1cbbdf9e96 in IceProcessMessages (iceConn=0x56375f4bb460, replyWait=replyWait@entry=0x0, replyReadyRet=replyReadyRet@entry=0x7fff29e12f24) at ../../src/process.c:386
        processProc = <optimized out>
        processMsgInfo = <optimized out>
        header = 0x56375f4b9990
        replyReady = 0
        useThisReplyWait = 0x0
        retStatus = IceProcessMessagesSuccess
#25 0x000056375de1a2fb in xsmp_handle_requests () at os_unix.c:7964
        rep = 32540
#26 0x000056375dee73e2 in local_xsmp_handle_requests (source=<optimized out>, condition=G_IO_IN, data=0x56375fc45000) at gui_gtk_x11.c:2459
No locals.
#27 local_xsmp_handle_requests (source=<optimized out>, condition=<optimized out>, data=0x56375fc45000) at gui_gtk_x11.c:2451
No locals.
#28 0x00007f1cbbe62e8e in ?? ()
No symbol table info available.
#29 0xffffffff29e12f90 in ?? ()
No symbol table info available.
#30 0x0000000000000000 in ?? ()
No symbol table info available.
```

To bug submitter @sinaraya : If you can try to reproduce this crash, it would be good to use the latest vim compiled with the address sanitizer. If there is a memory corruption, we will then have more information on stderr.

**Comment by lacygoill** [comment]
> Ok, I will try to reproduce once I finish the upgrade process.

Any update?

**Comment by chrisbra** [comment]
I think we can close this. @sinaraya  if you can reproduce this with an updated version, please open a new issue.

If possible, please include a backtrace or the output from an ASAN build. Thanks!

**Comment by sinaraya** [comment]
My apologies - I didn't get to test a whole lot but with 8.2 (patch level 1522), I couldn't reproduce this issue so far.
