### ISSUE TITLE
Vim9: cannot refer to function-local variable in command run by assert_fails()

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6868]
**Describe the bug**

In Vim9 script, we cannot refer to a function-local variable in a command run by `assert_fails()`.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Test_dict_deepcopy()
            v:errors = []
            var d: dict<any> = {'1': 1, '2': 2}
            var l = [4, d, 6]
            extend(d, {'3': l})
            assert_fails('deepcopy(d, 1)', 'E698')
            echom v:errors
        enddef
        Test_dict_deepcopy()
    EOF
    )

`v:errors` contains this error message:

    ['command line..script /proc/16106/fd/11[10]..function <SNR>1_Test_dict_deepcopy line 5: Expected ''E698'' but got ''E121: Undefined variable: d'': deepcopy(d, 1)']

**Expected behavior**

`v:errors` is empty.

**Environment**

 - Vim version: 8.2 Included patches: 1-1588
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(359)

**Additional context**

If the same code is refactored in Vim script legacy, then `v:errors` is empty.
```vim
vim9script
func Test_dict_deepcopy()
    let v:errors = []
    let d = {'1': 1, '2': 2}
    let l = [4, d, 6]
    call extend(d, {'3': l})
    call assert_fails('call deepcopy(d, 1)', 'E698')
    echom v:errors
endfunc
Test_dict_deepcopy()
```

**Comment by brammool** [comment]
assert_fails() runs the command in the current context, where "d" is not define, it's on the stack.

This works:
  try
    deepcopy(d, 1)
  catch
    assert_match('E698:', v:exception)
  endtry

But it doesn't check that there was an exception.

For Ex commands that evaluate an expression we already have code to not call the normal handling, but compile it, so that the variables on the stack can be found.
We don't make an exception for builtin functions yet, but this is one place where it makes sense.

**Comment by brammool** [comment]
It would be simpler (and better) to add a new command:
    assertfail
      eval unknown
    endassertfail E99:
Advantage is that the failing command doesn't need to be put in a string (with escaping)
It doesn't work for an unknown command, that can't be compiled.  But for that the existing assert_fails() can be used.
The argument to endassertfail should be a pattern, so we can use "E99:.*number expected".

Usual Ex command abbreviation:
  assert
    eval unknown
  endassert E99:

**Comment by lacygoill** [comment]
Closing because the solution is always the same.  Whenever we have some legacy code which raises an error in Vim9 because some function-local variable can't be found, we need to move it in the script-local scope.

Applied to the previous example, it gives:
```vim
vim9script
var d: dict<any>
def Test_dict_deepcopy()
    v:errors = []
    d = {'1': 1, '2': 2}
    var l = [4, d, 6]
    d = extendnew(d, {'3': l})
    assert_fails('deepcopy(d, 1)', 'E698')
    echom v:errors
enddef
Test_dict_deepcopy()
```
However, for some reason, `deepcopy()` no longer raises `E698`.  Maybe because of `extendnew()`... Anyway, that's a different issue.
