### ISSUE TITLE
when a line in a file is too long :cgetfile ignores the next line

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6870]
**Describe the bug**

When a line in a file is too long, `:cgetfile` ignores the next line.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        let lines = [
            \ '/tmp/file1:1:1:aaa',
            \ '/tmp/file2:1:1:%s',
            \ '/tmp/file3:1:1:bbb',
            \ '/tmp/file4:1:1:ccc',
            \ ]
        let lines[1] = substitute(lines[1], '%s', repeat('x', 7151), '')
        call writefile(lines, '/tmp/qfl.txt')
        setl efm=%f:%l:%c:%m
        cgetfile /tmp/qfl.txt
        cw
        setl nowrap
    EOF
    )

The quickfix list contains only 3 entries.

    /tmp/file1|1 col 1| aaa
    /tmp/file2|1 col 1| xxx...
    /tmp/file4|1 col 1| ccc

**Expected behavior**

The quickfix list contains 4 entries.

    /tmp/file1|1 col 1| aaa
    /tmp/file2|1 col 1| xxx...
    /tmp/file3|1 col 1| bbb
    /tmp/file4|1 col 1| ccc

**Environment**

 - Vim version: 8.2 Included patches: 1-1593
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: X.Org 7.7.0(359)

**Additional context**

This line in the file has not generated an entry in the quickfix list:

    /tmp/file3:1:1:bbb

That's because the previous line in the file was too long.

---

If the text on the second line in the file is shortened by 1 byte or more, the issue disappears:

    let lines[1] = substitute(lines[1], '%s', repeat('x', 7151), '')
                                                          ^--^
                                                           ✘

    let lines[1] = substitute(lines[1], '%s', repeat('x', 7150), '')
                                                          ^--^
                                                           ✔

I suspect that this maximum number (`7150`) depends on the OS and/or on the filesystem.  If you can't reproduce with `7151`, try to increase the number.

---

Regression introduced in [7.4.1802](https://github.com/vim/vim/releases/tag/v7.4.1802).

**Comment by lacygoill** [comment]
Patch testing this regression:
```diff
diff --git a/src/testdir/test_quickfix.vim b/src/testdir/test_quickfix.vim
index 2fbbd143e..c8feb008d 100644
--- a/src/testdir/test_quickfix.vim
+++ b/src/testdir/test_quickfix.vim
@@ -1744,6 +1744,19 @@ func Test_long_lines()
   call s:long_lines_tests('l')
 endfunc
 
+func Test_cgetfile_on_long_lines()
+  let lines = [
+    \ '/tmp/file1:1:1:aaa',
+    \ '/tmp/file2:1:1:%s',
+    \ '/tmp/file3:1:1:bbb',
+    \ '/tmp/file4:1:1:ccc',
+    \ ]
+  let lines[1] = substitute(lines[1], '%s', repeat('x', 7151), '')
+  call writefile(lines, '/tmp/qfl.txt')
+  cgetfile /tmp/qfl.txt
+  call assert_equal(4, getqflist(#{size: v:true}).size)
+endfunc
+
 func s:create_test_file(filename)
   let l = []
   for i in range(1, 20)
```

**Comment by lacygoill** [comment]
cc @mptre

The name Anton Lindqvist appears in the commit message of 7.4.1802.  I hope I don't ping the wrong person; sorry if I do.

**Comment by brammool** [comment]
Looks like adding another "x" also avoids the problem.  I wonder how you found that 7151 number.
