### ISSUE TITLE
When setting the 'term_rows' entry for a terminal buffer, the statusline gets shifted as if 'cmdheight' was increased

### ISSUE THREAD

**Issue by bfrg** [vim/vim#6872]
**Describe the bug**
Setting the `term_rows` option for a terminal buffer moves up the statusline as if `cmdheight` was increased. 

**To Reproduce**
Run `vim --clean -S test.vim`, with
```vim
call term_start(&shell, #{hidden: 1, term_finish: 'close', term_rows: 20})
```
Result: The statusline was moved up significantly (see screenshot below).

**Screenshots**
![screenshot-2020-09-05_095805](https://user-images.githubusercontent.com/6266600/92300828-5fb6c800-ef5e-11ea-9847-5180f8c38989.png)

**Environment**
Vim version `8.2.1593`

**Comment by lacygoill** [comment]
Regression introduced in [8.2.1589](https://github.com/vim/vim/releases/tag/v8.2.1589): *term_start() options for size are overruled by 'termwinsize'*
