### ISSUE TITLE
Test_expr5_fails() fails

### ISSUE THREAD

**Issue by dpelle** [vim/vim#6879]
`Test_expr5_fails()` fails 100% of the times when vim-8.2.1603 is configured with:
```
$ ./configure --with-features=normal --enable-gui=none --disable-channel
$ make -j8
$ make test
...snip...
Executed:  3079 Tests
 Skipped:   255 Tests
  FAILED:     2 Tests


Failures: 
	From test_vim9_expr.vim:
	Found errors in Test_expr5_fails():
	command line..script /home/pel/sb/vim/src/testdir/runtest.vim[456]..function RunTheTest[39]..Test_expr5_fails[30]..CheckDefFailure line 2: ['let x = ''a'' .. test_null_job()']: Expected 'E1105' but got 'E117: Unknown function: test_null_job': ['let x = ''a'' .. test_null_job()']
	command line..script /home/pel/sb/vim/src/testdir/runtest.vim[456]..function RunTheTest[39]..Test_expr5_fails[31]..CheckDefFailure line 2: ['let x = ''a'' .. test_null_channel()']: Expected 'E1105' but got 'E117: Unknown function: test_null_channel': ['let x = ''a'' .. test_null_channel()']
	Found errors in Test_expr5_vim9script():
	command line..script /home/pel/sb/vim/src/testdir/runtest.vim[456]..function RunTheTest[39]..Test_expr5_vim9script[1]..CheckScriptFailure line 2: ['vim9script', 'echo ''a'' .. test_null_job()']: Expected 'E908:' but got 'E117: Unknown function: test_null_job': ['vim9script', 'echo ''a'' .. test_null_job()']
	command line..script /home/pel/sb/vim/src/testdir/runtest.vim[456]..function RunTheTest[39]..Test_expr5_vim9script[1]..CheckScriptFailure line 2: ['vim9script', 'echo ''a'' .. test_null_channel()']: Expected 'E908:' but got 'E117: Unknown function: test_null_channel': ['vim9script', 'echo ''a'' .. test_null_channel()']

TEST FAILURE
Makefile:43: recipe for target 'report' failed
make[1]: *** [report] Error 1
make[1]: Leaving directory '/home/pel/sb/vim/src/testdir'
Makefile:2254: recipe for target 'scripttests' failed
make: *** [scripttests] Error 2
```

**Environment**
 - Vim-8.2.1603
 - OS: xubuntu-18.04.5

**Comment by lacygoill** [comment]
Expected 'E1105' but got 'E117: Unknown function: test_null_job': ['let x = ''a'' .. test_null_job()']
                                    ^-----------------------------^

    Expected 'E1105' but got 'E117: Unknown function: test_null_channel': ['let x = ''a'' .. test_null_channel()']
                                    ^---------------------------------^

    Expected 'E908:' but got 'E117: Unknown function: test_null_job': ['vim9script', 'echo ''a'' .. test_null_job()']
                                    ^-----------------------------^

    Expected 'E908:' but got 'E117: Unknown function: test_null_channel': ['vim9script', 'echo ''a'' .. test_null_channel()']
                                    ^---------------------------------^

I guess that's because Vim was compiled with `--disable-channel`.

Maybe the tests from where these errors come from should be guarded with an `if has('channel')` or `if has('job')` guard.

**Comment by lacygoill** [comment]
Untested, but maybe this patch could fix the tests:
```diff
diff --git a/src/testdir/test_vim9_expr.vim b/src/testdir/test_vim9_expr.vim
index a7d8d87f3..00eb60098 100644
--- a/src/testdir/test_vim9_expr.vim
+++ b/src/testdir/test_vim9_expr.vim
@@ -1105,16 +1105,18 @@ def Test_expr5_vim9script()
       echo 'a' .. function('len')
   END
   CheckScriptFailure(lines, 'E729:', 2)
-  lines =<< trim END
-      vim9script
-      echo 'a' .. test_null_job()
-  END
-  CheckScriptFailure(lines, 'E908:', 2)
-  lines =<< trim END
-      vim9script
-      echo 'a' .. test_null_channel()
-  END
-  CheckScriptFailure(lines, 'E908:', 2)
+  if has('channel')
+    lines =<< trim END
+        vim9script
+        echo 'a' .. test_null_job()
+    END
+    CheckScriptFailure(lines, 'E908:', 2)
+    lines =<< trim END
+        vim9script
+        echo 'a' .. test_null_channel()
+    END
+    CheckScriptFailure(lines, 'E908:', 2)
+  endif
 enddef
 
 def Test_expr5_float()
@@ -1172,8 +1174,10 @@ func Test_expr5_fails()
   call CheckDefFailure(["let x = 'a' .. 0z32"], 'E1105', 1)
   call CheckDefFailure(["let x = 'a' .. function('len')"], 'E1105', 1)
   call CheckDefFailure(["let x = 'a' .. function('len', ['a'])"], 'E1105', 1)
-  call CheckDefFailure(["let x = 'a' .. test_null_job()"], 'E1105', 1)
-  call CheckDefFailure(["let x = 'a' .. test_null_channel()"], 'E1105', 1)
+  if has('channel')
+    call CheckDefFailure(["let x = 'a' .. test_null_job()"], 'E1105', 1)
+    call CheckDefFailure(["let x = 'a' .. test_null_channel()"], 'E1105', 1)
+  endif
 endfunc
 
 " test multiply, divide, modulo
```

**Comment by brammool** [comment]
>     Expected 'E1105' but got 'E117: Unknown function: test_null_job': ['let x = ''a'' .. test_null_job()']
>                                     ^-----------------------------^
> 
>     Expected 'E1105' but got 'E117: Unknown function: test_null_channel': ['let x = ''a'' .. test_null_channel()']
>                                     ^---------------------------------^
> 
>     Expected 'E908:' but got 'E117: Unknown function: test_null_job': ['vim9script', 'echo ''a'' .. test_null_job()']
>                                     ^-----------------------------^
> 
>     Expected 'E908:' but got 'E117: Unknown function: test_null_channel': ['vim9script', 'echo ''a'' .. test_null_channel()']
>                                     ^---------------------------------^
> 
> I guess that's because Vim was compiled with `--disable-channel`.
> 
> Maybe the tests from where these errors come from should be guarded
> with an `if has('channel')` or `if has('job')` guard.

Adding an "if has(feature)" works, but we don't get any notification
that this part of the test was skipped.  I changed it to use a separate
function and :MissingFeature


-- 
-rwxr-xr-x  1 root          24 Oct 29  1929 /bin/ed
-rwxr-xr-t  4 root      131720 Jan  1  1970 /usr/ucb/vi
-rwxr-xr-x  1 root  5.89824e37 Oct 22  1990 /usr/bin/emacs

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
