### ISSUE TITLE
Undo number 0 not found

### ISSUE THREAD

**Issue by fflorent** [vim/vim#688]
I am quite surprised we can't undo to change number 0. It sounds like it is the reason why Gundo for example implement this workaround : 
https://github.com/sjl/gundo.vim/blob/master/autoload/gundo.py#L266

I currently write an addon, and I face the same issue.
### Steps to reproduce
1. Open vim on a new file
2. Type this command: `:echo undotree()`. 
   => `seq_cur` and `seq_last` both equal to 0
3. Type some text in insert mode
4. Go back to normal mode. Echoing `undotree()` should return something with `seq_cur` and `seq_last` that equals to 1
5. Type: `:undo 0` 
   => We get this error : `E830: Undo number 0 not found`
### Expected result

I personally would have expected to get back to an empty buffer (like if we would have pressed `u`).

Any particular reason for this behavior ?

Florent

**Comment by chrisbra** [comment]
I think this is beause the `:undo` command  moves **before** the mentioned undo number. It does not make sense to move before the 0 undo number.

**Comment by fflorent** [comment]
> I think this is beause the :undo command moves **before** the mentioned undo number.

Wait, that's not what the doc says : 

> :u[ndo] {N}        Jump to **after** change number {N}.  See |undo-branches|
>           for the meaning of {N}.  {not in Vi}

And in the example above : 
- you still can use `:undo`
- typing `:undo 1` doesn't change anything (we're already at sequence 1)
- typing `:undo 0` doesn't work 

Florent

**Comment by fflorent** [comment]
Thanks @brammool, this works like a charm :).

Florent
