### ISSUE TITLE
the example at ":h g@" could be improved

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6893]
The help at `:h g@` gives an example of how an operator can be implemented:
https://github.com/vim/vim/blob/3986b94b090ea258109630008611230a599999ab/runtime/doc/map.txt#L882-L912

It could be improved in several ways.

---

Problem: Mappings are recursive, which could have unexpected side-effects in the general case.

Solution: Use non-recursive mappings.

    v------v
    nnoremap <silent> <F4> :set opfunc=CountSpaces<CR>g@
    xnoremap <silent> <F4> :<C-U>call CountSpaces(visualmode(), 1)<CR>
    ^------^

Also, use `:xnoremap` instead of `:vnoremap`, because it probably doesn't make sense to install the mapping in select mode.

---

Problem: By the time the opfunc is processed, the count and register have been reset to resp. `0` and `"`.

Example:

    nno <c-b> :<c-u>set opfunc=Op<cr>g@
    fu Op(_)
        echom 'the count is ' .. v:count
        echom 'the register is ' .. v:register
    endfu

Press `"a 3 C-b l`, then run `:mess`.  The output is:

    the count is 0
    the register is "

It should be:

    the count is 3
    the register is a

You can pass them manually, either via `:norm` or `feedkeys()`, but it's trickier than it seems.  For example, `:norm` can break an interactive command by pressing `Escape` when an input is asked to the user.  And `feedkeys()` comes with its own pitfalls.

See here for a [real example](https://vi.stackexchange.com/q/12555/17449) of a user having an issue because they used the example from the help as a template.

Solution: Use the `<expr>` argument so that the count and register are passed naturally to the opfunc.

    nnoremap <expr> <F4> CountSpaces()

    function CountSpaces(...)
        if !a:0
            set opfunc=CountSpaces
            return 'g@'
        endif
        ...

---

Problem: Mappings enter the command-line; `CmdlineEnter` and `CmdlineLeave` are fired, which can have undesirable side-effects.

Solution: Again, use the `<expr>` argument to avoid entering the command-line.

---

Problem: Visual mode is handled specially, which makes the code harder to read and understand:

    nmap <silent> <F4> :set opfunc=CountSpaces<CR>g@
    vmap <silent> <F4> :<C-U>call CountSpaces(visualmode(), 1)<CR>

Notice how the rhs is different in the mappings.  And the `CountSpaces()` function handles visual mode as a separate case:

    if a:0  " Invoked from Visual mode, use gv command.
      silent exe "normal! gvy"

Solution: Again, use the `<expr>` argument to press `g@` directly from visual mode.

    nnoremap <expr> <F4> CountSpaces()
    xnoremap <expr> <F4> CountSpaces()

    function CountSpaces(...)
        if !a:0
            set opfunc=CountSpaces
            return 'g@'
        endif
    ...

The change marks will be set right where the visual marks are, and the code will be able to process the visual mode just like normal mode.  This makes the code more consistent and easier to read.

---

Problem: As a convention, when the key of an operator is pressed twice, it operates on the current line (or several if preceded by a count).  The current example lacks a mapping implementing this convention.

Solution: Add a mapping to operate on the current line.

    nnoremap <expr> <F4><F4> CountSpaces() .. '_'

---

Problem: The function does not abort on error.

Solution: Make the function abort on error.

    function! CountSpaces(type, ...) abort
                                     ^---^

---

Problem: Now that the function aborts on error, if an error occurs after an option or register has been temporarily reset, the latter won't be properly restored.

Solution: Wrap the code which alters the options and registers in a `try` conditional, and restore them from a `finally` clause.

    try
        " reset options and registers
    finally
        " restore options and registers
    endtry

---

Problem: `'clipboard'` is not temporarily reset; if the items `unnamed` or `unnamedplus` are present in the option, `"*` and/or `"+` could be clobbered.

Solution: Temporarily clear `'clipboard'`.

    let cb_save = &clipboard
    set clipboard=
    ...
    let &clipboard = cb_save

---

Problem: The operator enter visual mode to yank the text, which alters the visual marks.

Solution: Save and restore the visual marks.

    let visual_marks_save = [getpos("'<"), getpos("'>")]
    ...
    call setpos("'<", visual_marks_save[0])
    call setpos("'>", visual_marks_save[1])

---

Problem: Neither the type of the unnamed register, nor the name of the register to which it actually points, are preserved.

Solution: Use `getreginfo()` to preserve the type of the register and the name of the register to which it points.

    let reg_save = getreginfo('"')
    ...
    call setreg('"', reg_save)

---

Problem: `:execute` is used for every `:normal` command, but it's not necessary.

    silent exe "normal! gvy"
           ^^^
            ✘

    silent exe "normal! '[V']y"
           ^^^
            ✘

    silent exe "normal! `[v`]y"
           ^^^
            ✘

Solution: Only use `:execute` when necessary.

    silent normal! gvy

    silent normal! '[V']y

    silent normal! `[v`]y

---

Problem: A blockwise text is wrongly handled as if it was characterwise.  So, `<F4><C-v>j` prints the number of spaces in the characterwise region between the cursor and the character below.  Instead, it should print the number of spaces in the column of 2 characters containing the character under the cursor, and the one below.

Solution: Handle a blockwise text properly.

    elseif type ==# 'block'
        silent exe "normal! `[\<c-v>`]y"

---

Problem: The `:normal` commands add a useless entry in the jumplist.

Solution: Use `:keepjumps` to avoid adding an entry in the jumplist when yanking text.

    if type ==# 'line'
        silent keepjumps normal! '[V']y
        "      ^-------^
    elseif type ==# 'char'
        silent keepjumps normal! `[v`]y
        "      ^-------^
    elseif type ==# 'block'
        silent keepjumps exe "normal! `[\<c-v>`]y"
        "      ^-------^
    endif

---

Problem: The code repeats itself too much when yanking the text.

Solution: Move the parts of the commands which vary into a dictionary.

    let commands = #{line: "'[V']y", char: "`[v`]y", block: "`[\<c-v>`]y"}
    silent exe 'keepjumps normal! ' .. get(commands, type, '')

---

Problem: The code to get the number of spaces is not easy to read, and possibly inefficient.

Solution: Use `count()`.

    echom getreg('"')->count(' ')

---

As a suggestion, here is a patch which tries to address all of these issues:
```diff
diff --git a/runtime/doc/map.txt b/runtime/doc/map.txt
index 83fdbbb82..1d55c3236 100644
--- a/runtime/doc/map.txt
+++ b/runtime/doc/map.txt
@@ -881,35 +881,42 @@ g@{motion}		Call the function set by the 'operatorfunc' option.
 
 Here is an example that counts the number of spaces with <F4>: >
 
-	nmap <silent> <F4> :set opfunc=CountSpaces<CR>g@
-	vmap <silent> <F4> :<C-U>call CountSpaces(visualmode(), 1)<CR>
+	nnoremap <expr> <F4> CountSpaces()
+	xnoremap <expr> <F4> CountSpaces()
+	nnoremap <expr> <F4><F4> CountSpaces() .. '_'
 
-	function! CountSpaces(type, ...)
-	  let sel_save = &selection
-	  let &selection = "inclusive"
-	  let reg_save = @@
-
-	  if a:0  " Invoked from Visual mode, use gv command.
-	    silent exe "normal! gvy"
-	  elseif a:type == 'line'
-	    silent exe "normal! '[V']y"
-	  else
-	    silent exe "normal! `[v`]y"
+	function CountSpaces(...) abort
+	  if !a:0
+	    set opfunc=CountSpaces
+	    return 'g@'
 	  endif
 
-	  echomsg strlen(substitute(@@, '[^ ]', '', 'g'))
+	  let type = a:1
+	  let reg_save = getreginfo('"')
+	  let cb_save = &clipboard
+	  let sel_save = &selection
+	  let visual_marks_save = [getpos("'<"), getpos("'>")]
 
-	  let &selection = sel_save
-	  let @@ = reg_save
+	  try
+	    set clipboard= selection=inclusive
+	    let commands = #{line: "'[V']y", char: "`[v`]y", block: "`[\<c-v>`]y"}
+	    silent exe 'keepjumps normal! ' .. get(commands, type, '')
+	    echom getreg('"')->count(' ')
+	  finally
+	    call setreg('"', reg_save)
+	    call setpos("'<", visual_marks_save[0])
+	    call setpos("'>", visual_marks_save[1])
+	    let [&clipboard, &selection] = [cb_save, sel_save]
+	  endtry
 	endfunction
 
 Note that the 'selection' option is temporarily set to "inclusive" to be able
 to yank exactly the right text by using Visual mode from the '[ to the ']
 mark.
 
-Also note that there is a separate mapping for Visual mode.  It removes the
-"'<,'>" range that ":" inserts in Visual mode and invokes the function with
-visualmode() and an extra argument.
+Also note that the 'clipboard' option is temporarily emptied to avoid
+clobbering the `"*` or `"+` registers, if its value contains the item `unnamed`
+or `unnamedplus`.
 
 ==============================================================================
 2. Abbreviations			*abbreviations* *Abbreviations*
```

**Comment by lacygoill** [comment]
Maybe `:noautocmd` should also be used to reduce the side-effects when yanking the text:
```diff
diff --git a/runtime/doc/map.txt b/runtime/doc/map.txt
index 1d55c3236..83acac89c 100644
--- a/runtime/doc/map.txt
+++ b/runtime/doc/map.txt
@@ -900,7 +900,7 @@ Here is an example that counts the number of spaces with <F4>: >
 	  try
 	    set clipboard= selection=inclusive
 	    let commands = #{line: "'[V']y", char: "`[v`]y", block: "`[\<c-v>`]y"}
-	    silent exe 'keepjumps normal! ' .. get(commands, type, '')
+	    silent exe 'noautocmd keepjumps normal! ' .. get(commands, type, '')
 	    echom getreg('"')->count(' ')
 	  finally
 	    call setreg('"', reg_save)
```

**Comment by lacygoill** [comment]
We could also eliminate `...` and use a named optional argument, to make the code more readable:
```diff
diff --git a/runtime/doc/map.txt b/runtime/doc/map.txt
index 1d55c3236..e73e9f7c2 100644
--- a/runtime/doc/map.txt
+++ b/runtime/doc/map.txt
@@ -885,13 +885,12 @@ Here is an example that counts the number of spaces with <F4>: >
 	xnoremap <expr> <F4> CountSpaces()
 	nnoremap <expr> <F4><F4> CountSpaces() .. '_'
 
-	function CountSpaces(...) abort
-	  if !a:0
+	function CountSpaces(type = '') abort
+	  if a:type == ''
 	    set opfunc=CountSpaces
 	    return 'g@'
 	  endif
 
-	  let type = a:1
 	  let reg_save = getreginfo('"')
 	  let cb_save = &clipboard
 	  let sel_save = &selection
@@ -900,7 +899,7 @@ Here is an example that counts the number of spaces with <F4>: >
 	  try
 	    set clipboard= selection=inclusive
 	    let commands = #{line: "'[V']y", char: "`[v`]y", block: "`[\<c-v>`]y"}
-	    silent exe 'keepjumps normal! ' .. get(commands, type, '')
+	    silent exe 'keepjumps normal! ' .. get(commands, a:type, '')
 	    echom getreg('"')->count(' ')
 	  finally
 	    call setreg('"', reg_save)
```

**Comment by lacygoill** [comment]
New patch merging the previous changes:
```diff
diff --git a/runtime/doc/map.txt b/runtime/doc/map.txt
index 83fdbbb82..f4e4d170a 100644
--- a/runtime/doc/map.txt
+++ b/runtime/doc/map.txt
@@ -881,35 +881,41 @@ g@{motion}		Call the function set by the 'operatorfunc' option.
 
 Here is an example that counts the number of spaces with <F4>: >
 
-	nmap <silent> <F4> :set opfunc=CountSpaces<CR>g@
-	vmap <silent> <F4> :<C-U>call CountSpaces(visualmode(), 1)<CR>
+	nnoremap <expr> <F4> CountSpaces()
+	xnoremap <expr> <F4> CountSpaces()
+	nnoremap <expr> <F4><F4> CountSpaces() .. '_'
 
-	function! CountSpaces(type, ...)
-	  let sel_save = &selection
-	  let &selection = "inclusive"
-	  let reg_save = @@
-
-	  if a:0  " Invoked from Visual mode, use gv command.
-	    silent exe "normal! gvy"
-	  elseif a:type == 'line'
-	    silent exe "normal! '[V']y"
-	  else
-	    silent exe "normal! `[v`]y"
+	function CountSpaces(type = '') abort
+	  if a:type == ''
+	    set opfunc=CountSpaces
+	    return 'g@'
 	  endif
 
-	  echomsg strlen(substitute(@@, '[^ ]', '', 'g'))
+	  let reg_save = getreginfo('"')
+	  let cb_save = &clipboard
+	  let sel_save = &selection
+	  let visual_marks_save = [getpos("'<"), getpos("'>")]
 
-	  let &selection = sel_save
-	  let @@ = reg_save
+	  try
+	    set clipboard= selection=inclusive
+	    let commands = #{line: "'[V']y", char: "`[v`]y", block: "`[\<c-v>`]y"}
+	    silent exe 'noautocmd keepjumps normal! ' .. get(commands, a:type, '')
+	    echom getreg('"')->count(' ')
+	  finally
+	    call setreg('"', reg_save)
+	    call setpos("'<", visual_marks_save[0])
+	    call setpos("'>", visual_marks_save[1])
+	    let [&clipboard, &selection] = [cb_save, sel_save]
+	  endtry
 	endfunction
 
 Note that the 'selection' option is temporarily set to "inclusive" to be able
 to yank exactly the right text by using Visual mode from the '[ to the ']
 mark.
 
-Also note that there is a separate mapping for Visual mode.  It removes the
-"'<,'>" range that ":" inserts in Visual mode and invokes the function with
-visualmode() and an extra argument.
+Also note that the 'clipboard' option is temporarily emptied to avoid
+clobbering the `"*` or `"+` registers, if its value contains the item `unnamed`
+or `unnamedplus`.
 
 ==============================================================================
 2. Abbreviations			*abbreviations* *Abbreviations*
```

**Comment by lacygoill** [comment]
For symmetry with the `:let` which restores both options in a single line, we might want to also save both options in a single line:

    let cb_save = &clipboard
    let sel_save = &selection

    →

    let [cb_save, sel_save] = [&clipboard, &selection]

Or we might want to split the restoration on 2 lines:

    let [&clipboard, &selection] = [cb_save, sel_save]

    →

    let &clipboard = cb_save
    let &selection = sel_save

**Comment by brammool** [comment]
Thanks.  Using g@ has been tricky, this works around most of the disadvantages.

I prefer using two :let lines instead of the [] construct, it's simpler and easier to see what happens.
