### ISSUE TITLE
Unable to echo in job_start's lambda callback function

### ISSUE THREAD

**Issue by Melandel** [vim/vim#6896]
### Description
`echo` and `echomsg` do not display anything when invoked in the following fashion:
```vim
function! JobStartExample()
  let s:job = job_start(
    \'cmd /C dir',
    \{
      \'exit_cb':  { channel,status -> execute('echo "foo"') }
    \}
  \)
endfunction
```

### Notes
* With the same code, `echoerr` correctly displays `foo`
* Passing the name of a function instead of a lambda makes `echo`/`echomsg` display `fool` correctly, ie:
```vim
function! JobExitCbExample(channel, status)
  echo "foo"
endfunction

function! JobStartExample()
  let s:job = job_start(
    \'cmd /C dir',
    \{
      \'exit_cb':  'JobExitCbExample'
    \}
  \)
endfunction
```

### Expected Behaviour
I would have expected the same behaviour when using a lambda or when using a function name, ie displaying `foo`

### Environment
* on Windows 10 (gvim)
* version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul  4 2020 22:02:18), MS-Windows 64-bit GUI version with OLE support, Included patches: 1-1127

**Comment by k-takata** [comment]
Try `execute('echo "foo"', '')`.
See `:help execute()` for detail.

**Comment by Melandel** [comment]
Thank you very much!

**Comment by chrisbra** [comment]
Note, that depending on your ewnvironment, you may not see the result. It is usually better to use `:echomsg ...`
