### ISSUE TITLE
Deadly signal ABRT: using funcref inside dict-value in calls (introduced between 1559-1577)

### ISSUE THREAD

**Issue by luchr** [vim/vim#690]
Call vim or gtk2vim or gtk3vim (all behave the same) with

`vim -u NONE -U NONE -i NONE --noplugin  -S test.vim`

and the following small `test.vim` file:

```
fun InnerCall(funcref)
  echo a:funcref
endfu

fun OuterCall()
  let opt = { 'func' : function('sin') }
  call InnerCall(opt.func)
endfu

call OuterCall()
```

This produces in my case

```
vim: Caught deadly signal ABRT
Vim: Finished.
Aborted (core dumped) 
```

in Version 7.4.1577. It works perfectly under 7.4.1558.

**Comment by k-takata** [comment]
I confirmed that @mattn's patch fixes this problem.
https://groups.google.com/d/msg/vim_dev/fJz2q_9cE0o/87P5LQeeGAAJ
