### ISSUE TITLE
Syntax highlight inline css

### ISSUE THREAD

**Issue by timsofteng** [vim/vim#6900]
Hello.

Can I somehow enable syntax highlighting for inline css styles?

![image](https://user-images.githubusercontent.com/51912173/92402445-3e113880-f138-11ea-9bf1-d85c558d8f8c.png)

**Comment by chrisbra** [comment]
Does setting :set ft=html.css work?

**Comment by chrisbra** [comment]
Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. Closing.
