### ISSUE TITLE
Deadly signal ABRT/SEGV when typing backslash+newline in shell script on 7.4.1579

### ISSUE THREAD

**Issue by msto** [vim/vim#691]
Hi,

I recently installed Vim 7.4.1579 on RHEL 6.5 to add Python/Python 3 support. After installing, any time I edit a shell script and type in a backslash followed by a return, I get an ABRT (or SEGV if it's the second time in the session). I removed my vimrc entirely and it eliminated the problem, but the error returns after including only the Vundle stub:

```
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
```

Any suggestions here would be much appreciated. Thanks!

**Comment by msto** [comment]
The issue disappears in 7.4.1558, per @k-takata's comment [here](https://github.com/Shougo/vimproc.vim/issues/246#issuecomment-197147479)

**Comment by chrisbra** [comment]
duplicat of #690
