### ISSUE TITLE
Custom line number system on chunks of file

### ISSUE THREAD

**Issue by nordmagnus999** [vim/vim#6910]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
In Vim 8.0/9.0, there is (as far as I'm aware) 2 different line number system:
 - absolute
 - relative

There also a third one, though it's mostly a hybrid of the two, but anyway, that's the default one.

What I'm after is (as the title suggest) a custom line number system, that is only counting line of part/chunks of a file.
Let's illustrate this by the following example:
```
##1##
many text
and lines
##z##
##2##
more text
##z##
...etc
```
Where there example text, surrounded by a main header `##digit##` (which are incremented and are unique, which the `etc` implies in this example) and a non-changing header `##z##`.

In the context of the already explained custom line number system, it would look like this:
```
0 ##1##
1 many text
2 and lines
0 ##z##
0 ##2##
1 more text
0 ##z##
```
Where the line number on the side are supposed to be the already mentioned custom line number.

**Describe the solution you'd like**
A custom line number system for specific chunks of file. The solution would be either in vimscript or C (or both if need to be).

Either using the `sign` method, which already work, but without the width limit imposed by `sign` in the C code.
Or, a different line number, that won't be using `sign`, though that would also require modifying the C code too.

**Describe alternatives you've considered**
Someone on the [vim stackexchange](https://vi.stackexchange.com/a/27177/30351) mentioned using `sign` and `indentexpr` to make what was explained above, though it would be slower than the default line number, and would also be limited by the width limit on the `sign` column.

Someone else made [this plugin](https://github.com/rickhowe/partialnumber.vim) which also does the same thing i mentioned (surprisingly) though it still is ruled by the width limit of `sign` (which I'm aware need to be patched in the C code as i mentioned earlier)

I did thought of changing the width limit directly for the `sign` column, thanks to [this](https://stackoverflow.com/questions/17057201/make-sign-use-only-one-character-width/17057230#17057230) post, but it would probably be limited, compared to a automatically changed width.

**Comment by chrisbra** [comment]
This would also be quiet useful when editing patches to see the corresponding line numbers. Other than the suggested sign column, it is currently not possible, unfortunately.

**Comment by nordmagnus999** [comment]
Yeah @chrisbra The only way i see it is to do it in C, since i don't see any other way to do it in vimscript (beside using the `sign` as mentioned) though the `sign` function have a width limit, which also need to be patched or at least extended in some way, to make this more usable.

My main knowledge in C isn't too good, otherwise i would have done it by now :sweat_smile:

**Comment by chrisbra** [comment]
I think it would be not so straightforward and I am not sure, it's a feature that a lot of people would benefit from. 

Basically what we need would be a linenumberfunction setting, that can be set to a vim function, that takes line number as a parameter and returns whether or not to restart numbering. Depending on the function, it may slow down redrawing of vim. And not sure how it would handle inserting/replacing. So perhaps it should only be tested in normal mode.

**Comment by nordmagnus999** [comment]
I think (as i mentioned) that there two ways to do this:
- make this as a separate line number function in the C code.
- fix the width limit for `sign`, so the method i already mentioned would work better on more than 99 lines.

As you mentioned, making an actual new line number system, based on this, would be harder. I think it would be beneficial to consider both ways, especially since the latter one already work in vimscript, and just need the width limit lifted.

**Comment by nordmagnus999** [comment]
For the width limit of `sign`, i can change it manually on screen.c, and basically just change the `2` [here](https://github.com/vim/vim/blob/master/src/screen.c#L188) and [here](https://github.com/vim/vim/blob/master/src/screen.c#L4708), though i'm unsure if it's the only places that would work. Maybe [somewhere here](https://github.com/vim/vim/blob/master/src/screen.c#L4681) too.

But having a patch that would make the width change automatically/manually without recompiling would be better of course.

**Comment by brammool** [comment]
There is a better, and possibly easier way: Use a popup window without borders.
You can control the size and position, and set the contents to the line numbers you want to see.
You can also pick the colors you like.
You will need to write some Vim script to update popup when you scroll or make any changes.
It might help to use text properties as a marker in the text, so that at least some of this is updated when inserting/deleting lines.

**Comment by nordmagnus999** [comment]
Do you mean having the chunks of the file in a separate popup window? @brammool 

A bit like what [@chrisbra 's plugin](https://github.com/chrisbra/NrrwRgn) is doing or did you had something else in mind? (would love an example of what you meant)

**Comment by nordmagnus999** [comment]
Just looked into it, this does look like a lot what [NrrwRgn](https://github.com/chrisbra/NrrwRgn) plugin is doing, except it's in a popup window. That's actually a nice alternative to consider.

So to recapitulate:
- Make this as a separate line number function in the C code.
- Fix the width limit for sign, so the method i already mentioned would work better on more than 99 lines.
- Using a popup window without borders
- Using [NrrwRgn](https://github.com/chrisbra/NrrwRgn)

At least there a lot more options here.

**Comment by bfrg** [comment]
I think what @brammool meant was to place a narrow popup window displaying only the numbers on top of the line number column. If you attach it to a text-property the popup window will move with the buffer when you scroll the window.

**Comment by nordmagnus999** [comment]
That's even better than what i thought! This is a clever way to use the popup feature @bfrg

**Comment by chrisbra** [comment]
I suppose this can be closed then.

**Comment by nordmagnus999** [comment]
Now I actually noticed an interesting quirk with the great idea you suggested @brammool 

Basically, as far as i know, `:set number` is `3` width by default.
If i use the popup idea as already described, I'll need to use *something* to push the text into enough width/leave enough space, for the popup to take place (so it doesn't hover/hide the text), to emulate how `:set number` work in that sense.

That *something*, is two thing (afaik):
- Using a `sign` column under the popup window
- Using `:set number` directly under the popup window

Now I'm sure the easiest is using the `:set number`, since as already mentioned, `sign` have a limited width...
Any advice for the above? (beside using `:set number` since it seems kind of redundant given the end goal of this)

**Comment by brammool** [comment]
> Now I actually noticed an interesting quirk with the great idea you
> suggested @brammool 
> 
> Basically, as far as i know, `:set number` is `3` width by default.
> If i use the popup idea as already described, I'll need to use
> *something* to push the text into enough width/leave enough space, for
> the popup to take place (so it doesn't hover/hide the text), to
> emulate how `:set number` work in that sense.
> 
> That *something*, is two thing (afaik):
> - Using a `sign` column under the popup window
> - Using `:set number` directly under the popup window
> 
> Now I'm sure the easiest is using the `:set number`, since as already
> mentioned, `sign` have a limited width...
> Any advice for the above? (beside using `:set number` since it seems
> kind of redundant given the end goal of this)

You can most likely use the 'numberwidth' option.

-- 
Every exit is an entrance into something else.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by nordmagnus999** [comment]
Do you have any ways/advice for implementing the scrolling function, so it act like `:set number` when scrolling?
So that it scroll down or up the same way i mean (to reproduce how `:set number` as this is crucial).

I thought of just incrementing the numbers/deleting as it scroll up or down, but it'll be too slow... @brammool (this is basically one of the last thing i need to figure out, the rest is basically done beside that)

**Comment by nordmagnus999** [comment]
Nvm, figured it out...
