### ISSUE TITLE
Increment the number 0777 to 0778 using Ctrl-A, but it will be 01000.

### ISSUE THREAD

**Issue by bbq-all-stars** [vim/vim#6922]
**Describe the bug**
Increment the number 0777 to 0778 using Ctrl-A, but it will be 01000.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Type 0777
2. Select 0777 in visual mode
3. Type ctrl-A
4. Show 01000

**Expected behavior**
I expect to get 0778, because a number between 0001 and 0776 is incremented to 0002 and 0777 correctly.

**Screenshots**
![vim_bug](https://user-images.githubusercontent.com/8654703/92713840-6b5b2200-f396-11ea-8ef4-d9a74de91510.gif)
Using Ctrl-X for decrementing the number 01000, it become 00777.

**Environment (please complete the following information):**
 - Vim version: 8.2.1650
 - OS: macOS 10.15.6
 - Terminal: iTerm2 Build 3.3.12
 - Shell: zsh 5.7.1 (x86_64-apple-darwin18.2.0)

**Additional context**
I tried a few and the following cases were normal.
0001 => 0002
0776 => 0777
777 => 778

**Comment by tonymec** [comment]
see `:help 'nrformats'` which is mentioned (if you can scroll) in the commentaries for `:help CTRL-A`.

**Comment by bbq-all-stars** [comment]
I got. Thank you for your reply @tonymec
