### ISSUE TITLE
v:dying is 0 when exiting with :cq

### ISSUE THREAD

**Issue by noscript** [vim/vim#6924]
**Describe the bug**

`v:dying` is not set to `{N}` when exiting with `:cq {N}`

**To Reproduce**
1. Run VIM:
```sh
rm /tmp/died-* ; vim -g -f -u NONE +'au VimLeave * call system("touch /tmp/died-" . v:dying)' ; echo $? ; ls /tmp/died-*
```
2. Exit VIM with exit code 7:
```vim
:cq 7
```

**Expected behavior**
```
7
/tmp/died-7
```

**Actual behavior**
```
7
/tmp/died-0
```

**Environment:**
- Vim 8.2.1651
- OS: Ubuntu 18.04
- Terminal: GUI

**Comment by jottkaerr** [comment]
`v:dying` is set to `1` if Vim catches a deadly __signal__ and is increased if more signals are caught. `:cquit {N}` does not send a signal to kill Vim. Apart from the fact that it sets the exit code to `{N}` `:cquit` behaves more or less like a normal `:quit`.

**Comment by noscript** [comment]
I see. Is there something analogous to `v:dying` that is set to exit code from `:cq`, so it can be used with `VimLeave`?

**Comment by noscript** [comment]
Anyways, not a bug.
