### ISSUE TITLE
Vim9: cannot shadow a global function with a function-local funcref variable

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6926]
**Describe the bug**

In Vim9 script, we cannot shadow a global function with a function-local funcref variable.

**To Reproduce**

Suppose we create the plugin `some`; some people use it and it works fine for them:

    vim -Nu <(cat <<'EOF'
        vim9script
        let lines =<< trim END
            def Func()
                let Clash = function('strlen')
                echo Clash('string')
            enddef
        END
        mkdir('/tmp/some/plugin', 'p')
        writefile(lines, '/tmp/some/plugin/some.vim')
        set rtp^=/tmp/some
        au VimEnter * Func()
    EOF
    )

    6
    ✔

Now, one day, a user of the `some` plugin installs a second plugin: `another`.

    vim -Nu <(cat <<'EOF'
        vim9script
        let lines =<< trim END
            def Func()
                let Clash = function('strlen')
                echo Clash('string')
            enddef
        END
        mkdir('/tmp/some/plugin', 'p')
        writefile(lines, '/tmp/some/plugin/some.vim')
        lines =<< trim END
            func Clash()
            endfunc
        END
        mkdir('/tmp/another/plugin', 'p')
        writefile(lines, '/tmp/another/plugin/another.vim')
        set rtp^=/tmp/some rtp^=/tmp/another
        au VimEnter * Func()
    EOF
    )

    E1073: name already defined: Clash = function('strlen')

Our plugin doesn't work anymore because the name of the `Clash` variable, which stores a funcref, clashes with the global function `Clash()`.

**Expected behavior**

No error is raised because Vim lets us shadow the global function `Clash()` with the function-local `Clash` funcref variable.

**Environment**

 - Vim version: 8.2 Included patches: 1-1651
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(359)

**Additional context**

In Vim script legacy, a similar issue exists:
```vim
fu Clash(...)
    return 'Clash'
endfu

fu Func()
    let Clash = function('strlen')
    echo Clash('string')
endfu
call Func()
```
    E705: Variable name conflicts with existing function: Clash

But we can work around it by making the function-local scope explicit in the funcref assignment:

    let l:Clash = function('strlen')
        ^^

Example:
```vim
fu Clash(...)
    return 'Clash'
endfu

fu Func()
    let l:Clash = function('strlen')
    echo Clash('string')
endfu
call Func()
```
However, this workaround doesn't work anymore in Vim9 script, because `l:` doesn't exist there.

---

As a workaround, we can use `s:` instead:
```vim
vim9script
def g:Clash(s: string): string
    return 'Clash'
enddef

let s:Clash: func
def Func()
    s:Clash = function('strlen')
    echo s:Clash('string')
enddef
Func()
```
But I think it looks awkward or cumbersome.

---

I'm not sure this is a bug.  Maybe it's working as intended.  But I think it would be one less pitfall to be aware of if Vim let us shadow a global function with a function-local funcref variable.

Note that Vim already lets us shadow a global function with a script-local function:
```vim
vim9script
def g:Func()
    echom 'global'
enddef
def s:Func()
    echom 'script-local'
enddef
defcompile
```

**Comment by lacygoill** [comment]
> Note that Vim already lets us shadow a global function with a script-local function:
>
> vim9script
> def g:Func()
>     echom 'global'
> enddef
> def s:Func()
>     echom 'script-local'
> enddef
> defcompile

Here is a slightly better example:
```vim
vim9script
def g:Func()
    echom 'global'
enddef
def Func()
    echom 'script-local'
enddef
Func()
```
    script-local

Notice that – without any explicit scope – Vim is ok to define `Func()` in the script-local namespace, even though a function with the same name already exists in the global namespace.

**Comment by lacygoill** [comment]
Ah, I've just noticed that even though we can shadow a global function with a script-local one, we cannot with a function-local one:
```vim
vim9script
def g:Func()
    echom 'global'
enddef
def Outer()
    def Func()
        echom 'function-local'
    enddef
    Func()
enddef
Outer()
```
    E1073: name already defined: Func()

Maybe the reason for this error is the same as for the one in the OP.

**Comment by lacygoill** [comment]
If all of this is working as intended, maybe we should say something about this pitfall at `:h vim9-gotchas`, and possibly add a short recommendation as to how to avoid it (e.g. using the `s:` scope in the funcref assignment).

**Comment by lacygoill** [comment]
I understand that shadowing can be bad, because it lets us write ambiguous code.  But I think there are 2 cases to consider; whether we have full knowledge of the code, or whether there is some part which we do not and cannot know about.

For example, I can understand that this is disallowed:
```vim
vim9script
def Funcref()
enddef
def Func()
    let Funcref = function('strlen')
    echo Funcref('string')
enddef
Func()
```
    E1073: name already defined: Funcref = function('strlen')

Because, when we tried to assign the funcref, we might have forgotten that we already had a function with the same name in the script-local namespace.  And if that's the case, we might get unexpected results later.  Thanks to the warning, we can immediately change the name of the funcref variable to avoid any ambiguity in our code:
```vim
vim9script
def Funcref()
enddef
def Func()
    let OtherFuncref = function('strlen')
    echo OtherFuncref('string')
enddef
Func()
```
    6

So far so good, because we have full knowledge of the script-local namespace.  Similarly, we have full knowledge of the imported, function-local, and block-local namespaces.

But things are different with the global namespace.  Any function can be defined in there; from the user, or from third party plugins.  As a result, whatever name we choose for the funcref variable, there is no guarantee there will never be any clash.

And even if we choose a name which is already taken in the global namespace of some user, is it really useful for Vim to raise an error in our function?  From our perspective, there is no ambiguity.

**Comment by brammool** [comment]
Right, script-local and function-local names must be able to shadow global names, since you never know what's in the global namespace.  I think it already works for script-local names, that it doesn't work for function-local name is a bug.
