### ISSUE TITLE
In stacktrace, line number of last function was omitted.

### ISSUE THREAD

**Issue by kuuote** [vim/vim#6927]
**Describe the bug**
In stack trace, line number of last function was omitted.

**To Reproduce**
1. Run `vim --clean`
2. Execute below script
```vim
function s:a()
  echo expand("<stack>")
endfunction

function s:b()
  call s:a()
endfunction

function s:c()
  call s:b()
endfunction

call s:c()
```
3. displays `/path/to/script.vim[13]..function <SNR>8_c[1]..<SNR>8_b[1]..<SNR>8_a`

**Expected behavior**
displays `/path/to/script.vim[13]..function <SNR>8_c[1]..<SNR>8_b[1]..<SNR>8_a[1]`

**Environment (please complete the following information):**
 - Vim version: 8.2.1634
 - OS: Arch Linux
 - Terminal: Alacritty

**Comment by kuuote** [comment]
In source code and test are this behavior is specification, but document is not. Which is right?

**Comment by kuuote** [comment]
In my opinion, it would be better to have a line number.

**Comment by brammool** [comment]
You can use <slnum> to get the line number, but I agree that it's better that <stack> includes it.  I hope it doesn't cause trouble adding it now.

**Comment by kuuote** [comment]
Thank you for include it.

**Comment by lacygoill** [comment]
Not sure, but maybe we should remove the trailing double dot:
```vim
vim9script
def A()
    B()
enddef
def B()
    echo expand('<stack>')
enddef
A()
```
    /path/to/script[8]..function <SNR>123_A[1]..<SNR>123_B[1]..
                                                             ^^
                                                             ✘
