### ISSUE TITLE
Tutorial Correction

### ISSUE THREAD

**Issue by LORDTEK** [vim/vim#693]
At Lesson 6.5: SET OPTION
in the first NOTE, it is written as:
NOTE: To remove the highlighting of matches enter:    :nohlsearch

But it must change to:
..... enter:    :set nohlsearch

Please fix it. I am waiting for your correction.

**Comment by dpelle** [comment]
> But it must change to:
> ..... enter: :set nohlsearch

No. Both work  (:nohlsearch  or  :set nohlsearch).
But they are slightly different.
:nohlsearch stops highlighting, but it's turned on automatically when searching again (unlike ":set nohlsearch").

**Comment by LORDTEK** [comment]
E319: Sorry, the command is not available in this version

**Comment by k-takata** [comment]
If you use small or tiny version, `:nohlsearch` will not be available.

**Comment by LORDTEK** [comment]
That means you should not change :nohlsearch to :set nohlsearch even if :set nohlsearch works globaly. Oh I see. The source of the problem is my tiny or small version. But oh wait a second. I do not use small or tiny version. It is 7.4.182 so now what?

**Comment by chrisbra** [comment]
Install another version using your package manager. Look for e.g. vim-huge package. Closing. Please discuss user questions on vim-use ml. Thanks.

**Comment by LORDTEK** [comment]
Package manager LOL. vim-huge LOL.
It is on MS Windows not *nix.
Try to leave your ego and fix the problem.

**Comment by fritzophrenic** [comment]
There is no problem. :nohlsearch is a valid command in Vim. You must have a strange version of Vim, perhaps in cygwin or something. Please take this to the mailing list as this is a bug tracker and there is no bug.
