### ISSUE TITLE
Netrw: Incorrect command description states in the documentation for changing the current directory

### ISSUE THREAD

**Issue by ademin** [vim/vim#6934]
**Please, refer to the original issue reported** #6745 
The author of the plugin has made appropriate changes but those are not reflected in the vim's source tree.
So, I've reopened the issue(create a new one, since the previous one hasn't been closed by me)!

**Comment by chrisbra** [comment]
charles will send an updated script to Bram for inclusion with Vim. When this happens is Charles decision. Since this issue is already fixed, please do not open a new one. Thanks for understanding.
