### ISSUE TITLE
echo findfile('README.md', 'vimrc') return empty string

### ISSUE THREAD

**Issue by wsdjeg** [vim/vim#6939]
**Describe the bug**

vim can not find file in same directory.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. `touch README.md && touch vimrc`
2. vim -u vimrc
3. Type `:echo findfile('README.md', 'vimrc')`
4. nothing printed, 

**Expected behavior**
`README.md` should be printed

**Environment (please complete the following information):**
 - Vim version:
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 29 2020 12:02:33)
Included patches: 1-629
```
 - OS: ubuntu
 - Terminal:

**Comment by k-takata** [comment]
The second argument of findfile() is a path to find the file. So, `findfile('README.md', 'vimrc')` tries to find ` README.md` from `vimrc` directory. Retuning an empty string is expected behavior.

**Comment by wsdjeg** [comment]
I do not think so, because there is a `vimrc` file in current path, it is not a directory. and I have tested in latest version of vim, it return `README.md`.

**Comment by wsdjeg** [comment]
I am sorry for asking question for old version of vim, just want to make sure what is the second argv of `filefile()` and `filedir()`, it must be a directory?

**Comment by tonymec** [comment]
So IIUC Vim 7.4.629 is "bad" but the latest Vim 8.2 is "good" so what is your problem? I suppose the bug has been fixed in the meantime.

I tried the following in Vim 8.2.1665 on openSUSE Linux:
```bash
touch foo
touch bar
vim --clean
```
then in Vim:
```vim
:echo findfile('foo', 'bar')
```
and the result was `foo`.

Best regards,
Tony.

**Comment by tonymec** [comment]
FWIW, after removing `foo` and `bar` created above I tried
```
md foo
touch foo/bar
touch foo/baz
vim --clean
    :echo findfile('baz', 'foo/bar')
and the result was `foo/baz` as expected, IIUC, by @wsdjeg

Best regards,
Tony.

**Comment by wsdjeg** [comment]
just want to know the logic of this function. and create compatible function for old vim. BTW which patch fix this issue? I have search git log of Vim repo only find 3 commits. both are relative to test.
