### ISSUE TITLE
Columns seems to be counted in bytes by text properties

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#6941]
It seems that columns in text properties are counted in bytes, rather than characters. Is that intended behaviour? Counting bytes does not make much sense to me, but I may be missing something.

**To Reproduce**
1. Run `vim --clean` (or `gvim --clean`, etc.)
2. `I❯xyz<Esc>` (`❯` is U+276F; `len('❯')` is 3).
3. `:call prop_type_add('foo', #{ highlight: 'Error' })`
4. `:call prop_add(1, 4, #{type: 'foo'})`

**Expected behavior**
`z` is highlighted.

**Actual behavior**
`x` is highlighted.

**Environment**
 - Vim 8.2.1650
 - OS: macOS 10.15.6
 - Terminal: Apple's Terminal.app

**Comment by brammool** [comment]
The help is clear about that:
prop_add({lnum}, {col}, {props})
		Attach a text property at position {lnum}, {col}.  {col} is
		counted in bytes, use one for the first column.

Most line positions are counted in bytes.  It's often the simplest and fastest way.  Also avoids the question of whether composing characters are counted separately.

**Comment by habamax** [comment]
> The help is clear about that:
> prop_add({lnum}, {col}, {props})
> Attach a text property at position {lnum}, {col}. {col} is
> counted in bytes, use one for the first column.

@brammool Is there a way to add property to the correct position in unicode text? 
Function `fuzzymatchpos()` returns char positions I use to add properties, which obviously doesn't work correctly.

properties applied to non-unicode text:
![image](https://user-images.githubusercontent.com/234774/98651300-21b59600-234b-11eb-9dbd-430b56fcd742.png)

properties applied to unicode text:
![image](https://user-images.githubusercontent.com/234774/98651133-e4e99f00-234a-11eb-9b38-753361717c89.png)

**Comment by brammool** [comment]
> > The help is clear about that:
> > prop_add({lnum}, {col}, {props})
> > Attach a text property at position {lnum}, {col}. {col} is
> > counted in bytes, use one for the first column.
> 
> @brammool Is there a way to add property to the correct position in unicode text? 
> Function `fuzzymatchpos()` returns char positions I use to add properties, which obviously doesn't work correctly.
> 
> properties applied to non-unicode text:
> ![image](https://user-images.githubusercontent.com/234774/98651300-21b59600-234b-11eb-9dbd-430b56fcd742.png)
> 
> properties applied to unicode text:
> ![image](https://user-images.githubusercontent.com/234774/98651133-e4e99f00-234a-11eb-9b38-753361717c89.png)

You should be able to use byteidx() to convert a character position to a
byte position.

-- 
hundred-and-one symptoms of being an internet addict:
204. You have learned not to fall asleep on your keyboard
     the hard way

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by habamax** [comment]
> You should be able to use byteidx() to convert a character position to a byte position.

Awesome! Thank you!
