### ISSUE TITLE
gf / gF did not work on visual mode with line/col num.

### ISSUE THREAD

**Issue by Shane-XB-Qian** [vim/vim#6952]
**Describe the bug**
e.g `examples/mycachedapp/mycachedapp.go:44:`, visual select this line, then issue `gf` or `gF` reported error `e447` can not find path, but it works if on `normal` mode, or visual mode (selected the path) but did not include line/col num.
// cursor is not on line/col num.

**To Reproduce**
1. echo 'abc' > foo.txt
2. vim --clean x.txt
3. type 'foo.txt:1:' -and- ':w'
4. try 'gf' and 'gF' as description above.

**Expected behavior**
gf and gF worked.

**Screenshots**
n/a

**Environment (please complete the following information):**
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 14 2020 16:49:27)                                                                                                                              Included patches: 1-1678 

**Additional context**
n/a

**Comment by brammool** [comment]
The visual selection is for the file name itself, so that you can include ":123" in the file name.
But a ":123" following the visual selection can be used for "gF".  I can make that work.

**Comment by Shane-XB-Qian** [comment]
thanks. but i tried , looks still failed (E447 : can not find file) ..
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 15 2020 01:30:21)
Included patches: 1-1684
Compiled by shane@shanesmbxpro
```

btw: the description in `stl` about %c and %v was not correct, actually %c is the virtual col, and **%v** is the **screen col**, probably should update the `help` doc as well.
```
c N   Column number.
v N   Virtual column number.
V N   Virtual column number as -{num}.  Not displayed if equal to 'c'.
```

**Comment by Shane-XB-Qian** [comment]
@brammool  sorry, after read the modification and test case, looks i misunderstood your change.
looks it limited the visual selection should/had to exclude line num which only the fs path. um, i had not thought that, but it's ok.
just if 'gF' can open per line num with col num probably/would be better, which is xx:123:456: -vs- not only the :123 but :456 also.
