### ISSUE TITLE
encoding issue when using job_start

### ISSUE THREAD

**Issue by Melandel** [vim/vim#6953]
**Description**
I am working on replacing a synchronous `make` with something asynchronous based on `job_start` with `{'out_io': 'buffer'}` and `cgetbuffer`. Everything works except for some weird characters, amongst which, characters like `é` or `à` but also, it seems, some space characters.

* Given `set makeprg=dir` and `set errorformat=%m`, running `make` shows the following quickfix list:
![image](https://user-images.githubusercontent.com/48007894/93111389-d36f7800-f6b6-11ea-8d19-f118be508c58.png)
* Using `job_start`, running the following function:
```vim
function! JobStartExample()
	let cmd = 'dir'
	let s:job = job_start(
		\'cmd /C '.cmd,
		\{
			\'out_cb':   { chan,msg-> execute('echomsg "'.msg.'"',  '') },
			\'err_cb':   { chan,msg-> execute('echomsg "'.msg.'"',  '') },
			\'close_cb': { chan    -> execute('echomsg "'.chan.'"', '') },
			\'exit_cb':  { job,status-> execute('echomsg "foo"', '') }
		\}
	\)
endfunction
```
shows the following in `messages` :
![image](https://user-images.githubusercontent.com/48007894/93111961-ab344900-f6b7-11ea-83c1-71529ac2eaa9.png)

**Environment:**
 - gVim version : 
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 10 2020 22:02:04)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-1657
Compiled by appveyor@APPVYR-WIN
```
 - OS: Windows 10
 - Terminal: GUI (gVim)

**additional notes**
* chcp is 65001
* I have:
  * `set encoding=utf-8`
  * `set fileencoding=`
* using `'out_io': 'buffer'`, `'out_name': 'foo'`, and `'out_modifiable': 0`, I get the same result as shown in the previous screen

**Comment by Melandel** [comment]
Bump!

**Comment by brammool** [comment]
I suspect "cmd" does not use utf-8.  Thus the output is in another encoding.  You may need to use iconv() to convert to utf-8, or have the command output utf-8 somehow (not sure that is possible, the Windows console hasn't supported that).

**Comment by chrisbra** [comment]
don't you need to run the chcp command also in your `job_start()` command?

**Comment by Melandel** [comment]
@chrisbra I tried running `chcp && ` before my command. Below, the output:
![image](https://user-images.githubusercontent.com/48007894/93722462-4b4a1080-fb97-11ea-9736-cad745e21100.png)
`65001` is the correct chcp for `utf-8` in my understanding.
I also tried running `chcp 65001 && ` before my command. It didn't have any noticeable effect.

@brammool It reminds me that I had to tweak some code in fzf for a similar issue:
```vim
  function! s:enc_to_cp(str)
    if !has('iconv')
      return a:str
    endif
    if !exists('s:codepage')
			if &encoding == 'utf-8'
				let s:codepage = 65001
			else
      	let s:codepage = libcallnr('kernel32.dll', 'GetACP', 0)
			endif
    endif
    return iconv(a:str, &encoding, 'cp'.s:codepage)
  endfunction
``` 
The code that is oddly (too much) indented is the one I had to add to make fzf work without encoding issues. However, when I'm using that function:
```vim
function! JobStartExample(...)
	let cmd = 'dir'
	let g:a = ''
	let s:job = job_start(
		\'cmd /C '.cmd,
		\{
			\'callback': { chan,msg  -> execute('echomsg "[cb] '.escape(msg,'"\').'"',  1)                              },
			\'out_cb':   { chan,msg  -> execute('echomsg "'.iconv(escape(msg,'"\', 'utf-8', 'cp65001').'"',  1)                                   },
			\'err_cb':   { chan,msg  -> execute('echohl Constant | echomsg "\'.escape(msg,'"\').'" | echohl Normal',  1)},
			\'close_cb': { chan      -> execute('echomsg "[close] '.chan.'"', 1)                                        },
			\'exit_cb':  { job,status-> execute('echomsg "[exit] '.status.'"', '')                                      }
		\}
	\)
endfunction
```
I still get an output with problematic characters:
![image](https://user-images.githubusercontent.com/48007894/93722575-21ddb480-fb98-11ea-9d2b-d0308ae45521.png)

The issue remains if I'm inverting the two parameters:
```vim
function! JobStartExample(...)
	let cmd = 'dir'
	let s:job = job_start(
		\'cmd /C '.cmd,
		\{
			\'callback': { chan,msg  -> execute('echomsg "[cb] '.escape(msg,'"\').'"',  1)                              },
			\'out_cb':   { chan,msg  -> execute('echomsg "'.iconv(escape(msg,'"\', 'cp65001', 'utf-8').'"',  1)                                   },
			\'err_cb':   { chan,msg  -> execute('echohl Constant | echomsg "\'.escape(msg,'"\').'" | echohl Normal',  1)},
			\'close_cb': { chan      -> execute('echomsg "[close] '.chan.'"', 1)                                        },
			\'exit_cb':  { job,status-> execute('echomsg "[exit] '.status.'"', '')                                      }
		\}
	\)
endfunction
```
![image](https://user-images.githubusercontent.com/48007894/93723045-9108d800-fb9b-11ea-8341-29d15d9ed548.png)

**Comment by Melandel** [comment]
What I don't understand is that `:r !dir` works fine in terms of encoding...

Edit: Interestingly, `:r !chcp 65001 && dir` and `:r !chcp 65001 && cmd /c dir`, `:r !chcp` and `:r !dir && chcp` present encoding artifacts. The more I try things, the less I understand. Haha.

**Comment by chrisbra** [comment]
`:r !dir` this does some additional processing and I believe it uses the `&termencoding` setting.

it looks like the encoding conversion does not correctly work. Is `cp65001` a correct encoding for utf-8? Does it work if you use `utf-8` instead?

**Comment by Melandel** [comment]
I am not sure I understand what you are asking. Where do you want me to put `utf-8` instead of `cp65001` ?

**Comment by k-takata** [comment]
I also comfirmed that using `chcp 65001` didn't change the output encoding of `dir`. Not sure why.

**Comment by Melandel** [comment]
I still don't have a clue why that-which-should-have-worked did not work. I don't get it. It still stresses me out.

**However**, I found a way to make it work.

**Demonstration**
```vim
function! JobStartExample(...)
  let cmd = 'dir'
  let s:job = job_start(
    \'cmd /C '.cmd,
    \{
      \'out_cb':   { chan,msg  -> execute('echomsg "'.escape(msg,'"\').'"',  1)},
      \'close_cb': { chan      -> execute('echomsg "[close] '.chan.'"', 1)     },
      \'exit_cb':  { job,status-> execute('echomsg "[exit] '.status.'"', '')   }
    \}
  \)
endfunction

```
![image](https://user-images.githubusercontent.com/48007894/93751915-29d03f80-fbfe-11ea-933a-475c4ee83e7a.png)

**What fixed it for me**
Here's the [source](https://stackoverflow.com/a/57134096) on stackoverflow, credit to [mklement0](https://stackoverflow.com/users/45375/mklement0).

It's a configuration on Windows. Even though every time in the past, `chcp65001` always made the trick in my experience, it seems this time it doesn't.

In Windows 10 version 1903+, follow these steps:
1. Run `intl.cpl` (which opens the regional settings in Control Panel)
2. Go to `Administrative` tab
3. Click on `Change system locale`
4. Check the `Beta: Use Unicode UTF-8 for worldwide language support` box
5. Reboot

![image](https://user-images.githubusercontent.com/48007894/93751777-e8d82b00-fbfd-11ea-8938-6a44d4a13f4f.png)

Is this configuration point worth getting written somewhere in the doc, so people spend less time stretching their hair for `utf-8` on `job_start` for `Windows 10` ? I sure know I did.

I hope this will help others.

I would also like to thank you all for your time, guidance, and ideas. You are an inspiration to me.

@k-takata Maybe the fact that we are calling a `job` has an effect on how `chcp` affects the output ?

**Comment by k-takata** [comment]
Changing system locale to UTF-8 is still beta. So,

> Is this configuration point worth getting written somewhere in the doc,

I don't think so.

**Comment by brammool** [comment]
> What I don't understand is that `:r !dir` works fine in terms of encoding...

There are the options 'termencoding', 'makeencoding' and 'fileencoding'.
But I don't think any of them apply to channels.

-- 
ARTHUR:    Be quiet!  I order you to shut up.
OLD WOMAN: Order, eh -- who does he think he is?
ARTHUR:    I am your king!
OLD WOMAN: Well, I didn't vote for you.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ladayaroslav** [comment]
> I don't think so.

Well, I think it really should be mentioned --- encountered the same problem (wrapping psql using vim channels), and this is the only thing that helped in Win10.

**Comment by chrisbra** [comment]
then may be you want to contribute a doc patch to [os_win32s.txt](https://github.com/vim/vim/blob/master/runtime/doc/os_win32.txt) ?

**Comment by ladayaroslav** [comment]
> then may be you want to contribute a doc patch to [os_win32s.txt](https://github.com/vim/vim/blob/master/runtime/doc/os_win32.txt) ?

I didn't find "Known bugs" section in there? ;)
But really, this actually smells like a gvim bug --- why other programs don't need this?
It would be nice if someone re-tested that...

**Comment by ladayaroslav** [comment]
> Normally, 'tenc' is set to the current code page.

But the docs claim: "For the Win32 GUI and console versions 'termencoding' is not used, because the Win32 system always passes Unicode characters."

BTW, it's not what I see after trying the above workaround:

> set tenc?

termencoding=cp65001









> Converting the output from 'tenc' to 'enc' by using iconv() should be enough.

It should not be required (i.e. gvim should do this), IMNSHO.

> Using the UTF-8 system setting may "fix" some issues, but it can easily cause other issues.

Indeed.

**Comment by chrisbra** [comment]
@ladayaroslav  let me repeat: If you have specific suggestions, we gladly take any doc enhancements, preferably in the form of a patch.

**Comment by chrisbra** [comment]
> psql using vim channels

are you sure it's not `psql` outputing into your default Windows locale?

**Comment by k-takata** [comment]
> But the docs claim: "For the Win32 GUI and console versions 'termencoding' is not used, because the Win32 system always passes Unicode characters."

This means Vim doesn't use 'tenc' when showing the screen. Vim holds the internal data in 'enc' encoding (default is utf-8) and converts it to utf-16 (not to 'tenc') when showing the data.
Even 'tenc' is not used, it is set to the current code page.

> It should not be required (i.e. gvim should do this), IMNSHO.

Adding an option into job_start() to convert the encoding might be an option.

**Comment by ladayaroslav** [comment]
> are you sure it's not `psql` outputing into your default Windows locale?

Hmm... am I, indeed? Sorry, I haven't had time to test it... not sure when I'll do.
Perhaps, someone else could try it, if it's urgent?

But Bram might be right in https://github.com/vim/vim/issues/6953#issuecomment-1602628069 --- if a program really doesn't use unicode (or does it incorrectly) on Windows, it's not vim problem.

**Comment by ladayaroslav** [comment]
>  but it will require quite a lot of text to explain it properly, for something that few users will encounter.

Why not make a reference to this issue in the docs, then?
You had no problem referencing (external!) https://github.com/lacygoill/wiki/blob/master/vim/vim9.md in vim9.txt, after all. ;)
