### ISSUE TITLE
Text property does not follow its text when editing in blockwise visual mode

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#6961]
**To Reproduce**
1. Run `vim --clean` (or `gvim --clean`, etc.)
2. `Ixxx<Enter>yyy<Esc>`
3. `:call prop_type_add('foo', #{ highlight:'Error' })`
4. `:call prop_add(1,1, #{ length:3, type: 'foo' })`
5. `:call prop_add(2,1, #{ length:3, type: 'foo' })`
6. Blockwise-select (CTRL-V) the first column (both rows), type `I` and insert some spaces. The highlight of the second line does not move along with the text.

**Expected behavior**
The two lines of texts are indented and stay highlighted.

Before step 6:

<img width="262" alt="Screenshot 2020-09-15 at 15 52 23" src="https://user-images.githubusercontent.com/1193314/93219363-91ecd480-f76b-11ea-8595-17973a79cd80.png">

After step 6:

<img width="262" alt="Screenshot 2020-09-15 at 15 52 47" src="https://user-images.githubusercontent.com/1193314/93219383-99ac7900-f76b-11ea-8c4e-6e5afc40dc92.png">

**Environment:**
 - Vim 8.2.1650.
 - OS: macOS 10.15.6
 - Terminal: Apple's Terminal.app

**Additional context:**
Similar behavior (the highlight of the second line does not change) when the property type is defined with `start_incl: 1`.

**Comment by brammool** [comment]
fixed by 8.2.1690
