### ISSUE TITLE
CTRL-X and CTRL-A clear text properties

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#6962]
CTRL-A and CTRL-X act as text replacement, hence they remove underlying text properties. So, if one increments a highlighted number, the number loses its highlighting. Is this intentional?

**To Reproduce**
1. Run `vim --clean` (or `gvim --clean`, etc.)
2. `I100<Esc>`
3. `:call prop_type_add('foo', #{ highlight:'Error' })`
4. `:call prop_add(1,1, #{ length:3, type: 'foo' })`
5. Type CTRL-X or CTRL-A: the number is not highlighted any more.

**Expected behavior**
The number should remain highlighted.

**Environment:**
 - Vim 8.2.1650.
 - OS: macOS 10.15.6
 - Terminal: Apple's Terminal.app

**Comment by lifepillar** [comment]
Thanks for fixing this so promptly!

I have found a different situation, which I do not think is handled correctly even after this fix. Consider a number with a text property, and prepend or append digits to the number, so that the added digits are *not* included in the text property. Then, when you increment/decrement the number:

1. if digits were prepended, the highlight is removed;
2. if digits were only appended, the highlight is extended.

Example 1: a digit is prepended. Before incrementing:

<img width="262" alt="Screenshot 2020-09-16 at 12 16 50" src="https://user-images.githubusercontent.com/1193314/93325380-8820ab00-f817-11ea-85be-a8502e7200f5.png">

After incrementing:

<img width="262" alt="Screenshot 2020-09-16 at 12 16 58" src="https://user-images.githubusercontent.com/1193314/93325400-91117c80-f817-11ea-8b83-0529b4260132.png">

Example 2: a digit is appended. Before incrementing:

<img width="262" alt="Screenshot 2020-09-16 at 12 16 41" src="https://user-images.githubusercontent.com/1193314/93325436-a2f31f80-f817-11ea-910c-cb11aa4c68a5.png">

After incrementing:

<img width="262" alt="Screenshot 2020-09-16 at 12 16 29" src="https://user-images.githubusercontent.com/1193314/93325460-ab4b5a80-f817-11ea-8e3f-6e1c1d0baf4d.png">

**Comment by brammool** [comment]
> Thanks for fixing this so promptly!
> 
> I have found a different situation, which I do not think is handled correctly even after this fix. Consider a number with a text property, and prepend or append digits to the number, so that the added digits are *not* included in the text property. Then, when you increment/decrement the number:
> 
> 1. if digits were prepended, the highlight is removed;
> 2. if digits were only appended, the highlight is extended.
> 
> Example 1: a digit is prepended. Before incrementing:
> 
> <img width="262" alt="Screenshot 2020-09-16 at 12 16 50" src="https://user-images.githubusercontent.com/1193314/93325380-8820ab00-f817-11ea-85be-a8502e7200f5.png">
> 
> After incrementing:
> 
> <img width="262" alt="Screenshot 2020-09-16 at 12 16 58" src="https://user-images.githubusercontent.com/1193314/93325400-91117c80-f817-11ea-8b83-0529b4260132.png">
> 
> Example 2: a digit is appended. Before incrementing:
> 
> <img width="262" alt="Screenshot 2020-09-16 at 12 16 41" src="https://user-images.githubusercontent.com/1193314/93325436-a2f31f80-f817-11ea-910c-cb11aa4c68a5.png">
> 
> After incrementing:
> 
> <img width="262" alt="Screenshot 2020-09-16 at 12 16 29" src="https://user-images.githubusercontent.com/1193314/93325460-ab4b5a80-f817-11ea-8e3f-6e1c1d0baf4d.png">

Well, if a number is partially highlighted, what do you expect when
changing the whole number?  Keeping it partially highlighted isn't
reliable (the length may change).  Letting it depend on whether the
first character was highlighted isn't so bad.  Normally you would need
to update text properties for changed text anyway.  Vim only does try to
keep them if text before or after a text property changes.

-- 
MICHAEL PALIN PLAYED: 1ST SOLDIER WITH A KEEN INTEREST IN BIRDS, DENNIS, MR
                      DUCK (A VILLAGE CARPENTER WHO IS ALMOST KEENER THAN
                      ANYONE ELSE TO BURN WITCHES), THREE-HEADED KNIGHT, SIR
                      GALAHAD, KING OF SWAMP CASTLE, BROTHER MAYNARD'S ROOMATE
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
