### ISSUE TITLE
Vim9: cannot use ":breakadd func" with a :def function

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6969]
**Describe the bug**

We cannot use `:breakadd func` to debug a `:def` function.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def g:Func()
            echo 'inside'
        enddef
        breakadd func g:Func
        g:Func()
    EOF
    )

`inside` is echo'ed.  The execution of `Func()` is not stopped.

**Expected behavior**

`inside` is not echo'ed.  The execution of `Func()` is stopped right before.

**Environment**

 - Vim version: 8.2 Included patches: 1-1701
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(359)

**Additional context**

`:breakadd` keeps working for a legacy function, even in a Vim9 script:
```vim
vim9script
fu Func()
    echo 'inside'
endfu
exe 'breakadd func ' .. expand('<SID>') .. 'Func'
Func()
```
---

I'm not a programmer, so I have no idea whether adding a breakpoint into a *compiled* function is technically possible.  There is nothing at `:h vim9` on the subject of debugging (aside from `:h :disassemble`, but I don't think it can replace `:breakadd`).  And there is nothing at `:h todo` which suggests that the feature will be implemented at some point.

IMO, being able to debug `:def` functions with something like `:breakadd` is important, and would help plugin writers a lot.  On simple functions, a simple `:echom` can be enough, but this kind of debugging method is time consuming on complex code.

If `:breakadd` can't work for a `:def` function, I think it should be documented at `:h vim9-differences`.  And maybe suggest some debugging tool(s).  Maybe something like [vimspector](https://github.com/puremourning/vimspector) and [vim-debug-adapter](https://github.com/puremourning/vim-debug-adapter).  Although, it seems that the latter is still in an experimental stage.

I found some conversation about it: [RFC - External debugger API for debugging vimscript](https://groups.google.com/g/vim_dev/c/Xzb0a3bTg1U/m/m3WMcOu2BAAJ).  But I don't know whether this API and the tools which will use them are meant to replace our current debugging commands like `:breakadd`, or whether they are only meant to complement them.

---

I think the same issue applies to `:profile`.

**Comment by puremourning** [comment]
> If :breakadd can't work for a :def function, I think it should be documented at :h vim9-differences. And maybe suggest some debugging tool(s). Maybe something like vimspector and vim-debug-adapter. Although, it seems that the latter is still in an experimental stage.

vim-debug-adapter uses `breakadd` under the hood. As you've said, this doesn't currently work for vim9 script. I'm still working on the changes to improve the vim script debugging - this is a fairly long project with a lot of stuff to do. 

> I found some conversation about it: RFC - External debugger API for debugging vimscript. But I don't know whether this API and the tools which will use them are meant to replace our current debugging commands like :breakadd, or whether they are only meant to complement them.

I think the current status is that the vim script degging stuff just isn't implemented (yet) for vim9script. I meant to start up a conversation on vim-dev with Bram about what his plans were, but my guess is that it will be added after vim9script is complete. I had some ideas about how it can be done, but my current focus is on completing the debugging capabilities for legacy vim script, then focussing on vim9script.

**Comment by brammool** [comment]
As Ben mentions - no work has been done on debugging :def functions.  I'll add a todo item to make this clear.
No reason to keep this issue open then.
Profiling also has to be done, we probably need another instruction for this to avoid a slowdown when not profiling.
Part of the reason legacy script is slow is that there are so many "if (something enabled)" conditions for every line.
I'm trying to avoid that for :def functions.  Debugging may also require some extra instructions.  And a way to 
see what's on the stack.

**Comment by lacygoill** [comment]
> I had some ideas about how it can be done, but my current focus is on completing the debugging capabilities for legacy vim script, then focusing on vim9script.

Thank you very much for your work on this.

> I'll add a todo item to make this clear.

Thank you.  In addition to `:breakadd`, and `:profile`, I think `'verbose'` and `:verbose` don't work with `:def` functions either.  When we increase the verbosity level above 15, no message is given for each Ex command executed by a `:def` function, like it's done for a legacy one.
