### ISSUE TITLE
The file "Contents" in the root dir is out of date

### ISSUE THREAD

**Issue by chdiza** [vim/vim#697]
The file `Contents` contains out of date information about:
1. Which platforms Vim will run on.
2. The presence of the tarballs `vim74{rt,bin,src}.tgz`
3. The version of `xxd` that gets built.

**Comment by brammool** [comment]
Chdiza wrote:

> The file `Contents` contains out of date information about:
> 1. Which platforms Vim will run on.
> 2. The presence of the tarballs `vim74{rt,bin,src}.tgz`
> 3. The version of `xxd` that gets built.

This file is for the Amiga distribution.  It gets updated for a major
release.

Perhaps I should also move it to READMEdir.

## 

From "know your smileys":
 ~#:-(  I just washed my hair, and I can't do nuthin' with it.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///
