### ISSUE TITLE
how to set oldfiles num ? 

### ISSUE THREAD

**Issue by jingkai1** [vim/vim#6974]
how to set oldfiles num ? I wish oldfiles sum to 2000, but it is litter than 100.

**Comment by k-takata** [comment]
See `:help :oldfiles` and `:help v:oldfiles`, then `:help viminfo-'`.

Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. Closing.
