### ISSUE TITLE
Understanding <c-v>A and $

### ISSUE THREAD

**Issue by dylnmc** [vim/vim#6978]
*pre-disclaimer*: If I am misunderstanding anything, then please feel free to correct me in a friendly manner. It's a little bit involved, so please bear with me.

### v_b_A Documentation

I am unsure if my understanding is not clear or if the documentation is lacking or if the implementation is not working correctly, but it certainly is the case that if you **append** a string in visual-block mode (see `:help v_b_A`), then if you do `$.`, it will repeat the append after each line even if the line endings do not form a straight line. See the example gif:

![visual block with dollar and repeat](https://i.imgur.com/f4c2z0q.gif)

I suppose that this is because it is setting the *curswant* and since visual-block append adds text after the bottom-right corner, each of the lines in the range `'<,'>` (at curswant?) is affected. I was looking at `:help visual-repeat` which says the following:

> The start of the text is the Cursor position.  If the "$" command was used as
> one of the last commands to extend the highlighted text, the repeating will
> be applied up to the rightmost column of the longest line.

This appears to be about `$` used directly in visual-block mode. There is also `:help v_$`. This says the following:

> When the "$" command is used with blockwise Visual mode, the right end of the
> highlighted text will be determined by the longest highlighted line.  This
> stops when a motion command is used that does not move straight up or down.

Although it is not clear to me, I assumed that using "'$' with blockwise Visual mode" *could* mean that using `$` after returning to normal (command) mode will set the "right end of the [previously] highlighted text", but this is not very clear. I think that this is an interesting implementation if it is intended, but the help does it no justice, and left myself and others quite puzzled.

### Repeating

I was also a bit confused about repeating an append from a visual-block selection. There are three ways you can append after all of the lines using visual-block mode. Here are the following three ways:

1. `$<c-v>GAfoo<esc>`
2. `<c-v>$GAfoo<esc>`
3. `<c-v>GAfoo<esc>u$.`

I know that the third "option" is weird because we're doing an undo and then `$.` to repeat the append to the end of the line, but I found it quite interesting and confusing that (**when using repeat after a left or right command**) 1 and 2 behave the same but 3 behaves differently.

With 1 and 2, if you use `b` or `h` to "break" the curswant at the end-of-line, then `.` (repeat operator) will still append to the end of each line in the previously selected visual block. However, with 3, if you use `b` or `h` to "break" the curswant, then `.` will append the text in a vertical line (which is what I expected 1 and 2 to do). Either or both implementations are fine, but the help does not convey either of these at all, and it seems like there is a conflict between them

### Expectations

I don't expect anything. I (think I) understand how it works, and that is enough for me. However, I don't feel like the help accurately conveys how `$` and visual-block mode work - specifically, when you use `$.` after a visual-block append. In some irc channel, we just had a long, confusing brawl about the subject (where the curse words flowed freely), so I thought I would share this here.

Finally, this is such a low priority, that I don't expect there to be any changes in the near future, but I figured it would be worth opening Pandora's Box to either help solidify my understanding, find a hidden help section, or help the amazing help system become even better.

Thanks for all your hard work over the decades on this piece of software that has dramatically improved my productivity and been a large source of joy and inspiration,
Dylan

---

*vim 8.2.1684*

**Comment by brammool** [comment]
I do not see a bug here.  When combining several commands you get a ton of possibilities, the help cannot explain every single case.   Especially when it comes to undo and repeat.  Even when we would explain it somewhere, would a user find that text?  Probably just trying it out and seeing what happens is faster.

**Comment by Houl** [comment]
I was there ... ^^
Some user tried to understand the magic presented in the GIF (which is from a Vim Golf challenge ...) in terms of explanations in the help, but so far we found out, this is not documented (I haven't checked thoroughly).

There are several possible combinations of Visual block mode, the `A` command, the `$` motion and `.` repetition.

1. When you end Visual block mode with `$`, add text with `A` and then `.`-repeat, the repeated text always gets appended after EOL.
2. When you end Visual block mode with another motion (like in the GIF), add text with `A` and then `.`-repeat, the text is appended to the cursor column. But if you type `$.`, text is appended after EOL.  And the effect of `$` is not preserved here, when you just type `.` again, text is appended to the cursor column.

Thus when repeating `A` after Visual block mode, it makes an interesting difference whether the right edge of the Visual area was extended to EOL or not.
