### ISSUE TITLE
Popups do not inherit global tabstop value

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#6980]
**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean` (or `gvim --clean`, etc.)
2. `set tabstop=2`
3. `let winid = popup_create('hello', {})`
4. `echo getbufvar(winbufnr(winid), '&tabstop')`. The value of `tabstop` is `8`.

**Expected behavior**
I would expect the value of `tabstop` to be `2`, as when I create new buffers. For instance, after `:new`, `:echo &l:tabstop` returns `2`.

**Environment (please complete the following information):**
 - Vim 8.2.1650.
 - OS: macOS 10.15
 - Terminal: Apple's Terminal.app

**Additional context**
This may apply to other global settings—I haven't checked.

**Comment by brammool** [comment]
This is documented:

POPUP BUFFER AND WINDOW					*popup-buffer*

If a popup function is called to create a popup from text, a new buffer is
created to hold the text and text properties of the popup window.  The buffer
is always associated with the popup window and manipulation is restricted:
- the buffer has no name
- 'buftype' is "popup"
- 'swapfile' is off
- 'bufhidden' is "hide"
- 'buflisted' is off
- 'undolevels' is -1: no undo at all
- all other buffer-local and window-local options are **set to their Vim default
  value.**
