### ISSUE TITLE
gvim hangs when " asyncomplete-lsp.vim " trigger a lsp autocompletion

### ISSUE THREAD

**Issue by zoumi** [vim/vim#6982]
**Describe the bug**
The gvim's window is frozen while asyncomplete-lsp.vim is doing an autocompletion.
This only happens when the gvim's window maximized.
Other kind of completion work well.

https://github.com/prabirshrestha/asyncomplete-lsp.vim/issues/36

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Maximize gvim's window
2. Edit a .c file
3. Type something to trigger an LSP autocompletion
5. gvim hangs

Only certain LSP autocompletion trigger this.

**Screenshots**
If applicable, copy/paste the text or add screenshots to help explain your problem.

**Environment (please complete the following information):**
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 11 2020 23:33:50)
MS-Windows 64-bit GUI version

Microsoft Windows 7  64bit 
6.1.7601 Service Pack 1 Build 7601

**Additional context**

**Comment by zoumi** [comment]
![PIC](https://user-images.githubusercontent.com/5162901/93667794-1d8f9980-fabb-11ea-8d31-6d84d011fb04.png)

If I maximize the window, then type a '>' after 'BOOT_SV' gvim always hangs.

**Comment by zoumi** [comment]
In my newest test, it's seen that the width of window matters. It occurs when window's width exceed about 1300pix.

**Comment by zoumi** [comment]
![cap___](https://user-images.githubusercontent.com/5162901/93669959-16bc5300-faca-11ea-943a-a1ef6cee548c.PNG)
If I drag the buffer's window to a small size. gvim will not hangs.

**Comment by zoumi** [comment]
![___dd](https://user-images.githubusercontent.com/5162901/93670230-87646f00-facc-11ea-86f3-f27a42029376.png)

I drag the buffer window to a smaller size. gvim does not hang this time.

**Comment by chrisbra** [comment]
can you please try to reproduce this using some minimal example? It's unclear what's happening.

**Comment by mattn** [comment]
I suggest you to try to reproduce with the latest vim.

**Comment by zoumi** [comment]
I notice that in the 'no hang' example, the floating menu of C function's doc popup successfully.
And in the 'hang' example there is no menu of C function's doc.
So I change the setting of vim-lsp to disable the doc popup menu:
```viml
let g:lsp_documentation_float = 0
```
Finally, the 'hang' disappears.

I will post an issue to vim-lsp.
Thanks.

**Comment by zoumi** [comment]
https://github.com/prabirshrestha/vim-lsp/issues/854

Maybe it was solved. 
I upgrade my gvim version, it doesn't hang now. But the menu of C function's doc never popup even if I have set
```viml
let g:lsp_documentation_float = 1
```
I don't care about this. Thanks you!
