### ISSUE TITLE
Typo in syntax/cfg.vim

### ISSUE THREAD

**Issue by anntzer** [vim/vim#699]
syntax/cfg.vim contains the following line:

```
syn match   CfgParams    ".\{0}="me=e-1 contains=CfgComment
```

I am almost certain this is a typo, some time ago it used to be `".*="me=e-1` and I contacted the maintainer, Igor N. Prischepoff, to switch it to a nongreedy match (`".\{-}="me=e-1`), in order to properly highlight lines where the value also contains an equal sign (`key = value=value`) (he agreed to make the change).  As it is right now, the key is simply not highlighted anymore.

**Comment by chrisbra** [comment]
please discuss with the syntax script maintainer. Thanks.
