### ISSUE TITLE
string2float: de-DE locale + MacVim from Finder = E806

### ISSUE THREAD

**Issue by denisw** [vim/vim#7003]
**Describe the bug**

The `string2float` function in `src/eval.c` expects the `LC_NUMERIC` locale to be set to `"C"` so that the dot is used as decimal separator. Vim tries to ensure this by calling `setlocale(LC_NUMERIC, "C");` on startup, which seems to work fine when running Vim from the terminal.

However, if I start Vim on macOS through the Finder (via MacVim), this does _not_ work. Instead, if the macOS system language is set to German (Germany), any attempt to parse a floating-point number - even a floating-point literal in a Vim script - results in `E806: Float used as String`.

**To Reproduce**
1. Run `LANG=de_DE.UTF-8 vim` in a terminal
2. Execute `:language`, observe it's set to `de_DE.UTF-8/.../C/...`
3. Execute `:echo 0.5`, should work as expected
4. Set macOS system language to German (maybe just setting the decimal separator in the region settings is enough)
5. Start MacVim through Finder
4. Execute `:echo 0.5` again

**Expected Behavior**
* Output of `:language` should indicate the `C` locale for numbers.
* `0.5` should be echoed.

**Actual Behavior**
* The output of `:language` is just `de_DE.UTF-8`.
* The `echo` causes `E806: Float used as String` to be printed.

**Environment (please complete the following information):**
 - Vim version 8.2.1719 (MacVim)
 - OS: macOS 10.15.6
 - Terminal: GUI

**Remark / Workaround**

Curiously, running `:language de_DE.UTF-8` in MacVim fixes the issue; subsequent calls of `:language` will yield `de_DE.UTF-8/.../C/...` as when running from the terminal.

**Comment by chrisbra** [comment]
can you test, if this happens with a regular latest vim? This looks more or less like a macvim problem.

**Comment by denisw** [comment]
I also suspect it may be a MacVim issue; however, the matching issue on the MacVim side has been closed years ago: https://github.com/macvim-dev/macvim/issues/11

I'm not sure how I would test this on regular Vim. How would I open it in GUI mode from Finder without MacVim?

**Comment by chrisbra** [comment]
I don't have any clues about Apple and MacOS. But I believe MacVim is the gui for Vim. If this issue only occurs in MacVim, than it should be reported there. I don't think this is something we can fix here. 

ping @ychin

**Comment by brammool** [comment]
The GTK GUI had a similar problem, which was solved by setting LC_NUMERIC in gui_mch_init().  MacVim may need to do the same.

**Comment by ychin** [comment]
I think this is actually a common Vim bug. I can't test it right now but @denisw can try to test by doing the following in a new terminal:

```
unset LANG
vim
```

It should trigger the same bug too. The `src/os_mac_conv.c` code has functionality (in `mac_lang_init`) to detect that if `LANG` is non-existent (which will be the case if MacVim is launched from the Dock or it was manually unset from the environment like the above example), then it would manually set the locale to the system one. I think (not sure though, need to debug it) that code may be run after `init_locale` which manually sets the `LC_NUMERIC` locale to "C".

An easy fix would just be to change `mac_lang_init` to set `LC_NUMERIC` too, or see if we should re-order the initialization (seems more risky).

I have been meaning to submit a PR to port MacVim's change in related area (https://github.com/macvim-dev/macvim/pull/1036/) over to Vim anyway so I can take a look.

**Comment by denisw** [comment]
Indeed, `unset LANG` triggers the problem even if running Vim from the terminal. Thanks for tracking that down @ychin!

**Comment by brammool** [comment]
> I think this is actually a common Vim bug. I can't test it right now but @denisw can try to test by doing the following in a new terminal:
> 
> ```
> unset LANG
> vim
> ```
> 
> It should trigger the same bug too. The `src/os_mac_conv.c` code has functionality (in `mac_lang_init`) to detect that if `LANG` is non-existent (which will be the case if MacVim is launched from the Dock or it was manually unset from the environment like the above example), then it would manually reset the locale. I think (not sure though, need to debug it) that code may be run after `init_locale` which manually sets the `LC_NUMERIC` locale to "C".
> 
> An easy fix would just be to change `mac_lang_init` to set `LC_NUMERIC` too, or see if we should re-order the initialization (seems more risky).
> 
> I have been meaning to submit a PR to port MacVim's change in related area (https://github.com/macvim-dev/macvim/pull/1036/) over to Vim anyway so I can take a look.

You mean a patch like this:


*** ../vim-8.2.1734/src/os_mac_conv.c	2020-08-11 21:58:12.581968226 +0200
--- src/os_mac_conv.c	2020-09-23 22:03:57.649064086 +0200
***************
*** 580,585 ****
--- 580,589 ----
  #   ifdef HAVE_LOCALE_H
  	    setlocale(LC_ALL, "");
  #   endif
+ #   if defined(FEAT_FLOAT) && defined(LC_NUMERIC)
+ 	    // Make sure strtod() uses a decimal point, not a comma.
+ 	    setlocale(LC_NUMERIC, "C");
+ #   endif
  	}
      }
  }

-- 
The acknowledged parents of reengineering are Michael Hammer and James Champy.
When I say they're the "parents" I don't mean they had sex - and I apologize
for making you think about it.  I mean they wrote the best-selling business
book _Reengineering the Corporation_, which was published in 1993.
   Businesses flocked to reengineering like frat boys to a drunken
cheerleader.  (This analogy wasn't necessary, but I'm trying to get my mind
off that Hammer and Champy thing.)
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ychin** [comment]
@brammool Yeah basically. I think that will fix the issue.

I can do my other PR separately if you want to just commit this now.

**Comment by mattn** [comment]
FYI, I can provide code for vim_strtod on public-domain or vim-license.

https://gist.github.com/mattn/1890186
