### ISSUE TITLE
not easy to select and center arbitrary line in popup window menu

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7010]
**Describe the bug**

It is not easy to select and center an arbitrary line in a popup window menu.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        set lines=16
        let lines = range(1, &lines * 2)->map({_, v -> string(v)})
        let id = popup_menu(lines, #{
            \ minheight: &lines - 5,
            \ maxheight: &lines - 5,
            \ })
        call win_execute(id, 'norm! 17Gzz')
    EOF
    )

The line `1` is selected.

**Expected behavior**

The line `17` is selected and centered in the window.

**Environment**

 - Vim version: 8.2 Included patches: 1-1736
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(360)

**Additional context**

The issue comes from the `filter` key which is set to `'popup_filter_menu'` by `popup_menu()`.  If we remove it, the issue disappears, and the line 17 is correctly selected and centered:
```vim
set lines=16
let lines = range(1, &lines * 2)->map({_, v -> string(v)})
let id = popup_create(lines, #{
    \ minheight: &lines - 5,
    \ maxheight: &lines - 5,
    \ cursorline: 1,
    \ })
call win_execute(id, 'norm! 17Gzz')
```
---

As a workaround, we can:

   1. remove the `filter` key from the popup options
   2. delay `zz` with a timer
   3. set the `filter` key with a later timer

```vim
set lines=16
let lines = range(1, &lines * 2)->map({_, v -> string(v)})
let g:id = popup_create(lines, #{
    \ minheight: &lines - 5,
    \ maxheight: &lines - 5,
    \ cursorline: 1,
    \ })
call timer_start(0, {-> win_execute(g:id, 'norm! 17Gzz')})
call timer_start(5, {-> popup_setoptions(g:id, #{filter: 'popup_filter_menu'})})
```
Note that we need a long enough waiting time before setting the filter.  Otherwise, `zz` might sometimes fail.  5ms seems enough in practice.

It works, but it's brittle and looks like a hack.

---

There exists other workarounds.  For example, we can replace `norm! 17G` with `call cursor(17, 1)`, or with `firstline: 17` in the popup options.

But it doesn't fix the issue about `norm! zz`.  For the latter, we can also run a sequence of `jjj...` and `kkk...` to change the window's view and center the selected line.  I guess we could also compute `firstline` so that it centers the selected line, then we could run a sequence of `jjj...` to select the desired line, but all of this still looks like a hack.  It would be much simpler if `norm! zz` just worked.

**Comment by lacygoill** [comment]
> The issue comes from the filter key which is set to 'popup_filter_menu' by popup_menu(). If we remove it, the issue disappears, and the line 17 is correctly selected and raised:

Ah, I guess it's not a bug then.  The filter probably consumes the keys.  Sorry for the noise.

**Comment by lacygoill** [comment]
> Ah, I guess it's not a bug then.  The filter probably consumes the keys.  Sorry for the noise.

Although, if that's the case, then this shouldn't work:
```vim
vim9script
set lines=16
let lines = range(1, &lines * 2)->map({_, v -> string(v)})
let id = popup_menu(lines, #{
    minheight: &lines - 5,
    maxheight: &lines - 5,
    })
win_execute(id, ['cursor(18, 1)', 'norm! zz', 'redraw'])
```

And yet, it does.  The line `18` is correctly centered, which means that `zz` was not consumed by the filter.

However, the same code fails for the line `17`:
```vim
vim9script
set lines=16
let lines = range(1, &lines * 2)->map({_, v -> string(v)})
let id = popup_menu(lines, #{
    minheight: &lines - 5,
    maxheight: &lines - 5,
    })
win_execute(id, ['cursor(17, 1)', 'norm! zz', 'redraw'])
```
This time the line `17` is not centered.  This is inconsistent, but I'm not sure it's a bug.

**Comment by lacygoill** [comment]
I reopen because the "filter consumes the keys" explanation cannot explain this:
```vim
vim9script
set lines=16
let lines = range(1, &lines * 2)->map({_, v -> string(v)})
let id = popup_create(lines, #{
    minheight: &lines - 5,
    maxheight: &lines - 5,
    firstline: 17,
    cursorline: 1,
    })
win_execute(id, ['norm! zz', 'redraw'])
```
Here, there is no filter, and yet `norm! zz` fails to center the selected line.

We need a timer, which – again – looks like a hack:
```vim
vim9script
set lines=16
let lines = range(1, &lines * 2)->map({_, v -> string(v)})
g:id = popup_create(lines, #{
    minheight: &lines - 5,
    maxheight: &lines - 5,
    firstline: 17,
    cursorline: 1,
    })
timer_start(0, {-> win_execute(g:id, 'norm! zz')})
```

**Comment by brammool** [comment]
> I reopen because the "filter consumes the keys" explanation cannot explain this:
> ```vim
> vim9script
> set lines=16
> let lines = range(1, &lines * 2)->map({_, v -> string(v)})
> let id = popup_create(lines, #{
>     minheight: &lines - 5,
>     maxheight: &lines - 5,
>     firstline: 17,
>     cursorline: 1,
>     })
> win_execute(id, ['norm! zz', 'redraw'])
> ```
> Here, there is no filter, and yet `norm! zz` fails to center the selected line.
> 
> We need a timer, which – again – looks like a hack:
> ```vim
> vim9script
> set lines=16
> let lines = range(1, &lines * 2)->map({_, v -> string(v)})
> g:id = popup_create(lines, #{
>     minheight: &lines - 5,
>     maxheight: &lines - 5,
>     firstline: 17,
>     cursorline: 1,
>     })
> timer_start(0, {-> win_execute(g:id, 'norm! zz')})
> ```

There is some redraw error.  Using CTRL-L often makes it work.

Using "firstline" in the options should not be needed.  This works:


vim9script
set lines=16
let lines = range(1, &lines * 2)->map({_, v -> string(v)})
g:id = popup_create(lines, #{
    minheight: &lines - 5,
    maxheight: &lines - 5,
    cursorline: 1,
    })
win_execute(g:id, ['normal 17Gzz'])


When executing win_execute() later, the cursorline highlighting is not
updated:

:call win_execute(g:id, ['normal 20Gzz'])


Similarly, when redrawing before the win_execute() the same happens:

vim9script
set lines=16
let lines = range(1, &lines * 2)->map({_, v -> string(v)})
g:id = popup_create(lines, #{
    minheight: &lines - 5,
    maxheight: &lines - 5,
    cursorline: 1,
    })
redraw
win_execute(g:id, ['normal 17Gzz'])

When redrawing the popup it needs to check if the cursor was moved.
I can fix that.  Not sure if that fixes the whole problem, please see if
you can reproduce another problem after the fix.

-- 
A salesperson says:            Translation:
"backward compatible"          Old technology
"Premium"                      Overpriced
"Can't keep it on the shelf"   Unavailable
"Stands alone"                 Piece of shit
"Proprietary"                  Incompatible
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bfrg** [comment]
Calling `win_execute(winid, 'normal 17Gzz')` doesn't work when a popup-filter has been set.

This one here works:
```vim
def Test()
    const winid = range(1, 50)
        ->map({_, v -> string(v)})
        ->popup_create(#{
            minwidth: 60,
            maxwidth: 60,
            minheight: 15,
            maxheight: 15,
            cursorline: 1
        })
    win_execute(winid, 'normal! 17Gzz')
    popup_setoptions(winid, #{filter: 'popup_filter_menu'})
enddef
```
Whereas the following here fails (cursorline is not moved to line 17):
```vim
def Test()
    const winid = range(1, 50)
        ->map({_, v -> string(v)})
        ->popup_create(#{
            minwidth: 60,
            maxwidth: 60,
            minheight: 15,
            maxheight: 15,
            cursorline: 1,
            filter: 'popup_filter_menu'
        })
    win_execute(winid, 'normal! 17Gzz')
enddef
```

It depends on the filter we are setting for the popup-window. Using a simple filter works:
```vim
def Test()
    const winid = range(1, 50)
        ->map({_, v -> string(v)})
        ->popup_create(#{
            minwidth: 60,
            maxwidth: 60,
            minheight: 15,
            maxheight: 15,
            cursorline: 1,
            filter: {-> 0}
        })
    win_execute(winid, 'normal! 17Gzz')
enddef
```

**NB:** Tested with `8.2.1738`

**Comment by brammool** [comment]
> Calling `win_execute(winid, 'normal 17Gzz')` doesn't work when a popup-filter has been set.
> 
> This one here works:
> ```vim
> def Test()
>     const winid = range(1, 50)
>         ->map({_, v -> string(v)})
>         ->popup_create(#{
>             minwidth: 60,
>             maxwidth: 60,
>             minheight: 15,
>             maxheight: 15,
>             cursorline: 1
>         })
>     win_execute(winid, 'normal! 17Gzz')
>     popup_setoptions(winid, #{filter: 'popup_filter_menu'})
> enddef
> ```
> Whereas the following here fails (cursorline is not moved to line 17):
> ```vim
> def Test()
>     const winid = range(1, 50)
>         ->map({_, v -> string(v)})
>         ->popup_create(#{
>             minwidth: 60,
>             maxwidth: 60,
>             minheight: 15,
>             maxheight: 15,
>             cursorline: 1,
>             filter: 'popup_filter_menu'
>         })
>     win_execute(winid, 'normal! 17Gzz')
> enddef
> ```
> 
> It depends on the filter we are setting for the popup-window. Using a simple filter works:
> ```vim
> def Test()
>     const winid = range(1, 50)
>         ->map({_, v -> string(v)})
>         ->popup_create(#{
>             minwidth: 60,
>             maxwidth: 60,
>             minheight: 15,
>             maxheight: 15,
>             cursorline: 1,
>             filter: {-> 0}
>         })
>     win_execute(winid, 'normal! 17Gzz')
> enddef
> ```

The commands you give to ":normal" are put in the typahead buffer and
then executed.  The filter intercepts these characters.

It might be possible to not send any characters to popup filters if they
come from the ":normal" command.  I suppose that's what you would
expect.

You could still use feedkeys() if you want to. You don't even need to
use win_execute() then.  Thus we don't drop functionality.

-- 
Git catch 22: "merge is not possible because you have unmerged files."

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bfrg** [comment]
Something is still not right. When `cursorline` is enabled, `firstline` can't be changed through `popup_setoptions()`. This doesn't work:
```vim
def Test()
    const winid = range(1, 50)
        ->map({_, v -> string(v)})
        ->popup_create(#{
            minwidth: 60,
            maxwidth: 60,
            minheight: 15,
            maxheight: 15,
            cursorline: 1
        })
    popup_setoptions(winid, #{firstline: 10})
enddef
```

Setting `firstline` in `popup_create()` works though:
```vim
def Test()
    const winid = range(1, 50)
        ->map({_, v -> string(v)})
        ->popup_create(#{
            minwidth: 60,
            maxwidth: 60,
            minheight: 15,
            maxheight: 15,
            cursorline: 1,
            firstline: 10
        })
enddef
```

**Comment by lacygoill** [comment]
> It might be possible to not send any characters to popup filters if they
> come from the ":normal" command.  I suppose that's what you would
> expect.

I think that's what I would expect.  I think of `:normal` as a way to script normal commands, not to emulate interactive commands (like what `feedkeys()` can do with the `t` flag).  It would greatly simplify scripted interactions with a popup menu, like `norm! zz`.  I will open a new issue for that in the future.

> Something is still not right. When cursorline is enabled, firstline can't be changed through popup_setoptions(). This doesn't work:

I noticed this issue while I was trying to find a workaround for `norm! 123G` in a popup menu.  I'll open a new issue for this one too.
