### ISSUE TITLE
"mapping: 0" does not disable mappings when popup window created from <expr> mapping

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7011]
**Describe the bug**

`mapping: 0` does not disable mappings when a popup window is created from an `<expr>` mapping.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        let keys = ''
        def Popup(): string
            popup_create('', #{filter: Filter, mapping: false})
            return ''
        enddef
        def Filter(id: number, key: string): bool
            keys ..= key
            echo 'key: ' .. keys
            return true
        enddef
        set lz
        nno <expr> <F3> <sid>Popup()
        nno <down> abc
        feedkeys("\<F3>\<down>")
    EOF
    )

`key: abc` is echoed.

**Expected behavior**

`key: <80>kd` is echoed.

**Environment**

 - Vim version: 8.2 Included patches: 1-1736
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(360)

**Additional context**

The `nno <down> abc` mapping has not been ignored.  It should have been ignored, because the `mapping` property was set to `false`.

---

The issue disappears if the popup window is not created from an `<expr>` mapping.
```vim
vim9script
let keys = ''
def Popup(): string
    popup_create('', #{filter: Filter, mapping: false})
    return ''
enddef
def Filter(id: number, key: string): bool
    keys ..= key
    echo 'key: ' .. keys
    return true
enddef
set lz
Popup()
feedkeys("\<down>")
```

**Comment by brammool** [comment]
There is a race condition: feedkeys() puts both F3 and Down into the typeahead buffer.
F3 creates the popup, then when is Down processed?  Apparently it happens before the popup is active.
It can be avoided by splitting feedkeys() in two:
feedkeys("\<F3>", "xt")
feedkeys("\<down>", "xt")

**Comment by lacygoill** [comment]
> There is a race condition: feedkeys() puts both F3 and Down into the typeahead buffer.

I see; that explains why it only happens the first time we press `<Down>` and not the subsequent times.  That also probably explains why it only happens before the mappings timeout (`&timeoutlen`) and not after.

> It can be avoided by splitting feedkeys() in two:
> feedkeys("<F3>", "xt")
> feedkeys("<down>", "xt")

I found the issue while I was studying the [`fileselect.vim`](https://github.com/yegappan/fileselect/blob/d0390f0d13485343ce545e16d98d5d37e67df20c/plugin/fileselect.vim#L27) plugin.  To fix the issue in this plugin, we can't split `feedkeys()`, because there is none.  The popup is not created by `feedkeys()`; it's created when the user presses a mapping.

Note that the issue in this plugin is not currently visible; but that's only because of another unrelated bug.  The `fileselect#toggle()` function should return an empty string.  Once the function is fixed, we can see that mappings are not ignored when a key is pressed before the mappings timeout.  As you said it's probably due to a race condition.  I'm not sure whether it can be fixed from the plugin.

**Comment by lacygoill** [comment]
> That also probably explains why it only happens before the mappings timeout (&timeoutlen) and not after.

I was wrong.  The issue does not disappear after the mappings timeout (`&timeoutlen`); it disappears after `&updatetime`, but only if we have an autocmd listening to `CursorHold`.  I think that's because Vim writes the pseudo-key `<CursorHold>` into the typeahead buffer, and the issue disappears after any key has been pressed (because it causes the typeahead to be flushed?).

---

It's possible that a race condition is responsible for the example reported in the OP, but I'm not sure it's the cause of the original bug.  This snippet is identical to the one in the OP, except `feedkeys()` is removed:
```vim
vim9script
let keys = ''
def Popup(): string
    popup_create('', #{filter: Filter, mapping: false})
    return ''
enddef
def Filter(id: number, key: string): bool
    keys ..= key
    echo 'key: ' .. keys
    return true
enddef
set lz
nno <expr> <F3> <sid>Popup()
nno <down> abc
```
If we press `<F3>` interactively to create the popup, then no matter how long we wait, pressing `<Down>` will always use the mapping.  If it was a race condition, I would expect the issue to disappear after waiting some short period of time.

---

I found another similar issue in a different plugin:
```vim
vim9script
nno <cr> :echom 'was hit'<cr>
setpos("'w", [0, 3, 1, 0])
range(1, 20)->map({_, v -> string(v)})->setline(1)
def Callback(...l: any)
    norm! 10G
enddef
timer_start(0, {-> popup_create('', #{
    filter: 'popup_filter_menu',
    callback: Callback,
    mapping: false,
    })})
```
This creates a popup with a callback which should move the cursor on line 10 (`norm! 10G`).  But if we press `Enter`, instead of jumping on line 10, Vim inserts the text `s hit'` on line 3.

Two things are unexpected here.  First, the reason why Vim inserts the text `s hit'` on line 3 is because it has used the `<CR>` mapping.  But `mapping: false` should have prevented that.  Second, it seems that an extra `<CR>` has been written in the typeahead buffer (by the callback?) in the middle of the mapping:

    :echom 'was hit'<cr>
          ^
          probably inserted somewhere around here

This is confirmed by the fact that if we remove the `'w` mark, then `E20: Mark not set` is raised.

As a result, `'w` is parsed as a motion command, `a` is parsed as the append command, and the rest of the mapping is inserted literally into the buffer.

Note that this time, the issue is not triggered by `<expr>`, but by a timer.  The issue disappears if we remove the timer.  The issue persists no matter the waiting time we choose for the timer.  The issue persists no matter how long we wait before pressing Enter while the popup is visible.

**Comment by brammool** [comment]
In the example with Popup() I can only see the first use of the Down key causing "abc" to be found.
After that the raw Down key code is used.
This is happening because the <expr> mapping returns an empty string, thus Vim stays in the loop
to wait for a character.  But the code to check if any filter has disabled mappings is only executed
when starting to wait for a character.  Thus something must make the loop return first.

It's hard to make this work without side effects.  Especially starting to ignore mappings halfway getting
a character is going to be weird.  It's better to exit the loop and try again.
I would suggest that you make Vim return from the loop to get a character, possibly by returning <Nop>.
Not sure if that works when using the timer though.

**Comment by lacygoill** [comment]
I can confirm that returning a no-op like `<C-\><C-n>` fixes the issue in the `<expr>` mapping:
```vim
vim9script
let keys = ''
def Popup(): string
    popup_create('', #{filter: Filter, mapping: false})
    return "\<c-\>\<c-n>"
enddef
def Filter(id: number, key: string): bool
    keys ..= key
    echo 'key: ' .. keys
    return true
enddef
set lz
nno <expr> <F3> <sid>Popup()
nno <down> abc
feedkeys("\<F3>\<down>")
```
It doesn't fix the issue with the timer, but that's another issue and I've found another workaround.  Thank you very much for the hint and explanation.

**Comment by brammool** [comment]
You can return "\<Ignore>", it was especially aimed at returning something without effect.

For the timer: I think there are other situations where one wants the input loop to return after a timer triggered.
We could do this always, but it might have side effects.
How about adding an option to the timer that tells Vim to return the input loop with <Ignore>?

**Comment by brammool** [comment]
Looks like github ate the backslash before <Ignore>.  So it's a double quoted string, with the first character a backslash.
