### ISSUE TITLE
Vim9: crash when a Vim9 function that was defined on the Command-line causes an E117.

### ISSUE THREAD

**Issue by adscriven** [vim/vim#7012]
**Describe the bug**
A Vim9 function referencing another unknown function causes a crash when it was defined on the Command-line.

**To Reproduce**
1. $ vim -u NONE
2. On the Command-line:

    :def A()
    :  B()
    :  enddef
    :call A()

This causes a segmentation fault.

Sourcing the definition of A from a file, followed by ":call A()",
generates an E117 normally.

**Expected behavior**
No crash; E117 error message.

**Environment**
Vim: 8.2 1-1738
OS: Arch Linux
Terminal: tmux

Vim: 8.2 1-869
OS: Windows 10.0.18363
Terminal: mintty

**Comment by lacygoill** [comment]
- [backtrace](https://github.com/vim/vim/files/5283042/backtrace.txt)
- [valgrind log](https://github.com/vim/vim/files/5283043/valgrind.log)
- [asan log](https://github.com/vim/vim/files/5283041/asan.log)
