### ISSUE TITLE
cursorlineopt should be window level, but now wrong.

### ISSUE THREAD

**Issue by Shane-XB-Qian** [vim/vim#7014]
**Describe the bug**
`cursorlineopt` should be 'window level', but current actually is 'tab level', new 'tab' can get same cursorlineopt value from previous 'tab/window', unless it was a existed buf in opened tab.

**To Reproduce**
Detailed steps to reproduce the behavior:
1, vim --clean xyz
2, set cursorline
3, # check this 'xyz' tab/window had cursorline and cursorlineopt is 'both'
4, set cursorlineopt=number
5, tabe abc
6, # check this 'abc' tab/window had No cursorline and cursorlineopt also is 'number'

**Expected behavior**
that 'abc' tab/window should have cursorline and cursorlineopt also is 'both'

**Screenshots**
n/a

**Environment (please complete the following information):**
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 25 2020 12:28:52)
Included patches: 1-1738
Compiled by shane@shanesmbxpro

**Additional context**
n/a

**Comment by lacygoill** [comment]
> cursorlineopt should be 'window level', but current actually is 'tab level'

AFAIK, there is no tab local option; there are only:

   - global options
   - buffer-local options
   - window-local options
   - global or local to a buffer options
   - global or local to a window options

`'cursorline'` and `'cursorlineopt'` are window-local options.

> 6, # check this 'abc' tab/window had **No cursorline** and cursorlineopt also is 'number'

At the end of your example, the window displaying the buffer `abc` *has* the `'cursorline'` option set.

> that 'abc' tab/window should have cursorline and cursorlineopt also is 'both'

The `abc` window has `'cursorline'` set, but indeed, `'cursorlineopt'` is set to `number`.  Here is why:

   1. when you have executed `set cursorlineopt=number` you have set the local value of the option, *and* the global value
   2. when you create a new window, it inherits the global value of window-local options
   3. the global value of a window-local option is used to initialize the local value


If you want the `'cursorlineopt'` option to be set to `both` in the `abc` window, then do not use `:set` when setting the option in the `xyz` window.  Instead, use `:setlocal`.  This way, the global value won't be altered; it will still keep its default value `both`; and when you'll create the `abc` window, the latter will inherit this global value `both`, which will then be used to initialize the local value.

---

I think all of this is documented at [`:h local-options`](https://vimhelp.org/options.txt.html#local-options).  But I admit it's quite difficult to understand.  I've read other people which were also confused by how window-local options worked (me included the first time I studied them).  One day, I would like to write a gist explaining in detail how they work; there is a lot to unpack; mabye using a diagram could help.  I also would like to send a patch to improve the documentation.  But so far, I haven't found the time.  I still need to do a lot of tests.

In case it helps, here are [my notes about Vim options](https://github.com/lacygoill/wiki/blob/master/vim/config.md).  I haven't had the time to finish them; and I haven't reviewed them in a long time, so they might be sometimes inaccurate.

**Comment by Shane-XB-Qian** [comment]
> no tab local option

i mean 't:var_aa', and compared to 'w:var2', if i let 'w:var_bb' = 123 at 'xyz' tab/window, you would not get value at 'abc' tab/window.

but obviously looks this is not the point, point is: yes, i am confused.. :)
it said:
```
	global			one option for all buffers and windows
	local to window		each window has its own copy of this option
	local to buffer		each buffer has its own copy of this option
```
- `cursorlineopt` is 'local to window'.
and/but also said this:
```
:setl[ocal][!] ...	Like ":set" but set only the value local to the
			current buffer or window.  Not all options have a
			local value.  If the option does not have a local
			value the global value is set.
```
looks user difficult to know which had a 'global' or not, or by luck, unless check one by one, then try to know should 'set' or 'setl' ..
as my understanding per eye and those doc words, when 'set' cursorlineopt it meant `local to window`, it meant local to window.

anyway, for this case/option, you are right, i am confused.
