### ISSUE TITLE
Regression: Meta+nonalpha mapping needs to be defined inconsistently in GTK GUI (since 8.2.0851)

### ISSUE THREAD

**Issue by inkarkat** [vim/vim#7016]
**Describe the bug**
In the GUI, it is possible to define different mappings for Alt and Alt + Shift, e.g. `<A-a>` vs. `<A-A>` or `<A-/>` vs. `<A-?>`, with the latter being the shifted variant of the same key (at least on US-English keyboard layouts).

Since 8.2.0851, a mapping like `<A-?>` cannot be triggered any longer in the GTK2 GUI, and instead has to be defined as `<A-S-?>` to take effect. That latter definition, however, does not work e.g. in Windows GVIM, so an ugly conditional has to be used to define such mappings for multiple platforms (e.g. by plugins).

This only seems to affect non-alpha target keys, i.e. `<A-A>` still works and does not have to be written as `<A-S-A>` (but that also works and overrides a previous `<A-A>` definition).

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `gvim --clean`
2. `:nnoremap <A-?> :echo '<lt>A-?>'<CR>`
3. `:nnoremap <A-S-?> :echo '<lt>A-S-?>'<CR>`
3. Press <kbd>Alt</kbd> <kbd>Shift</kbd> <kbd>/</kbd> (US-English layout)
4. In GTK2 GVIM, `<A-S-?>` is printed, in Windows GVIM, `<A-?>`.

I used the following script to bisect the problem:

```
scriptencoding utf-8
nnoremap <A-?> :quitall!<CR>
call feedkeys("¿:cquit!\<CR>", 't')
```

**Expected behavior**
Having to include the `S-` modifier for the GTK2 GUI is a breaking change and inconsistent with other GUI implementations. I believe this is an unintended side effect of this change:

> commit f4ae6b245a54f11dd967d06b80f30e5abf55fb82
> Author: Bram Moolenaar <Bram@vim.org>
> Date:   2020-05-30 19:52:46 +0200
>
>     patch 8.2.0851: can't distinguish <M-a> from accented "a" in the GUI
>     
>     Problem:    Can't distinguish <M-a> from accented "a" in the GUI.
>     Solution:   Use another way to make mapping <C-bslash> work. (closes #6163)

**Environment (please complete the following information):**
 - Vim version 8.2.1738, starting from 8.2.0851
 - OS: Ubuntu 16.04 LTS 64-bit
 - GTK2 GUI version

**Comment by brammool** [comment]
Ingo Karkat wrote:

> **Describe the bug**
> In the GUI, it is possible to define different mappings for Alt and Alt
> + Shift, e.g. `<A-a>` vs. `<A-A>` or `<A-/>` vs. `<A-?>`, with the
> latter being the shifted variant of the same key (at least on US-English
> keyboard layouts).
> 
> Since 8.2.0851, a mapping like `<A-?>` cannot be triggered any longer in
> the GTK2 GUI, and instead has to be defined as `<A-S-?>` to take effect.
> That latter definition, however, does not work e.g. in Windows GVIM, so
> an ugly conditional has to be used to define such mappings for multiple
> platforms (e.g. by plugins).
> 
> This only seems to affect non-alpha target keys, i.e. `<A-A>` still
> works and does not have to be written as `<A-S-A>` (but that also works
> and overrides a previous `<A-A>` definition).
> 
> **To Reproduce**
> Detailed steps to reproduce the behavior:
> 1. Run `gvim --clean`
> 2. `:nnoremap <A-?> :echo '<lt>A-?>'<CR>`
> 3. `:nnoremap <A-S-?> :echo '<lt>A-S-?>'<CR>`
> 3. Press <kbd>Alt</kbd> <kbd>Shift</kbd> <kbd>/</kbd> (US-English layout)
> 4. In GTK2 GVIM, `<A-S-?>` is printed, in Windows GVIM, `<A-?>`.
> 
> I used the following script to bisect the problem:
> 
> ```
> scriptencoding utf-8
> nnoremap <A-?> :quitall!<CR>
> call feedkeys("¿:cquit!\<CR>", 't')
> ```
> 
> **Expected behavior**
> Having to include the `S-` modifier for the GTK2 GUI is a breaking
> change and inconsistent with other GUI implementations. I believe this
> is an unintended side effect of this change:

It's inconsistent, in some environments it works, in others it doesn't.
It doesn't work in xterm, it does in Motif.

For Motif and Win32 it was removing the Shift modifier for all ASCII
punctuation characters.  Let's do that for GTK too, and use the same
function for all.  I'll send out a patch after some more testing.

-- 
A consultant is a person who takes your money and annoys your employees while
tirelessly searching for the best way to extend the consulting contract.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
