### ISSUE TITLE
CursorHold not fired after entering first buffer

### ISSUE THREAD

**Issue by airblade** [vim/vim#7017]
**Describe the bug**
I expected that `CursorHold` would be fired `updatetime` ms after entering a new buffer, without any intervention from the user.  However it seems that this is not always true for the very first buffer.

I would like to know whether I can count on `CursorHold` to be always fired after entering a new buffer, or whether I have misunderstood the docs.

**To Reproduce**
1. Create a simple `vimrc` and touch two files (`touch a b`):

```
set nocompatible
set updatetime=100
autocmd CursorHold * echom 'cursorhold'
```

1. Run `vim -u vimrc -U NONE -i NONE a b`
3. `:n`
3. `:messages`

**Actual behaviour**
The messages show:

```
"a" 0L, 0C
"b" 0L, 0C
cursorhold
```

**Expected behavior**
The messages show:

```
"a" 0L, 0C
cursorhold
"b" 0L, 0C
cursorhold
```

**Environment (please complete the following information):**
 - Vim version 8.2.607.
 - macOS 10.14.6
 - iTerm2.

**Context**
This arose in https://github.com/airblade/vim-gitgutter/issues/738 where my Vim runs `CursorHold` when entering the very first buffer but @dargor's doesn't.  Which is odd because in my test case above my Vim doesn't run `CursorHold` initially in the first buffer.

**Comment by lacygoill** [comment]
> However it seems that this is not always true for the very first buffer.

I don't know whether `BufEnter` should be fired for the first buffer or not, but during startup, only some Enter events are triggered: [source](https://github.com/vim/vim/issues/5243#issuecomment-555244085).

It could be that `BufEnter` is not one of these Enter events.

But as said in the previous link, maybe you could also listen to `VimEnter` for the first buffer.

**Comment by lacygoill** [comment]
Ah sorry, I misread your report.  You were talking about `CursorHold`, not `BufEnter`.  But maybe the link is still relevant...

**Comment by airblade** [comment]
In a nutshell I want to run some code on `BufEnter` and then on every `CursorHold` – but I don't want to run anything while Vim is starting up (to keep the start-up time down).

I thought I could test for `has("vim_starting")` in my `BufEnter` handler and noop if true; and then rely on `CursorHold` to fire a little later.  But it seems `CursorHold` doesn't always fire after `BufEnter`.

**Comment by brammool** [comment]
CursorHold is only triggered after the user has pressed a key, that is documented.
If you type ":n" that means some keys were pressed.
On startup no keys were pressed.
Makes sense?

**Comment by airblade** [comment]
> only triggered after the user has pressed a key

I think the documentation is a little ambiguous:

```
CursorHold			When the user doesn't press a key for the time
				specified with 'updatetime'.  Not re-triggered
				until the user has pressed a key ...
```

I understood that to mean that if the user does nothing once a buffer is ready, CursorHold will be triggered (once) after 'updatetime'.  (And then, of course, 'updatetime' after each keypress.)

Anyway, thank you for clarifying when CursorHold is triggered.  The behaviour I observed makes sense now.

**Comment by Shane-XB-Qian** [comment]
> I don't know whether `BufEnter` should be fired for the first buffer or not

@lacygoill probably you were saying `winenter`, bufenter would fired at first b.

**Comment by Shane-XB-Qian** [comment]
> documentation is a little ambiguous

not sure it was changed recently, i recall it was fired in past, or whatever now it is not, unless some key press like ':n'.
but anyway looks doc did not mentioned: if `compatible` was true, looks `cursorhold` would fire at startup.

**Comment by Houl** [comment]
On Windows, this used to work for every Vim version (7.0 .. 8.2):
`gvim.exe -N -u NONE -i NONE --cmd "set ut=500" --cmd "au CursorHold * echomsg 'did CursorHold'"`.
An initial CursorHold is triggered without typing a key first.  I rely on that so I hope this keeps working.

**Comment by brammool** [comment]
> On Windows, this used to work for every Vim version (7.0 .. 8.2):
> `gvim.exe -N -u NONE -i NONE --cmd "set ut=500" --cmd "au CursorHold * echomsg 'did CursorHold'"`.
> An initial CursorHold is triggered without typing a key first.  I rely
> on that so I hope this keeps working.

Perhaps on Windows it sees some event that causes it to do this.

-- 
hundred-and-one symptoms of being an internet addict:
3. Your bookmark takes 15 minutes to scroll from top to bottom.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
