### ISSUE TITLE
Vim9: Why is a variable name starts with 'to_' special?

### ISSUE THREAD

**Issue by alexaschee** [vim/vim#7019]
**Describe the bug**
Why is a variable name starts with `to_` special?

**To Reproduce**

1. Run `vim --clean`
2. Run this script
```
vim9script
let t_f = 0
let to_f = 0
let ta_f = 0
let too_f = 0

too_f = 1 == 1 ? 2 : 1
ta_f = 1 == 1 ? 2 : 1
to_f = 1 == 1 ? 2 : 1
t_f = 1 == 1 ? 2 : 1

:echo "::  too_f = " .. too_f
:echo "::   ta_f = " .. ta_f
:echo "::   to_f = " .. to_f
:echo "::   t_f = " .. t_f
```

**Screenshots**
![Screenshot__](https://user-images.githubusercontent.com/13317191/94328515-d0915300-ffe5-11ea-86a6-2ccbb4bfb633.png)

**Environment:**
 - Vim version [e.g. 8.2.1734]
 - OS: Windows 10

**Comment by DavidTodd2** [comment]
I'm not very familiar with vim scripting but the following worked for me:

let t_f = 0
let to_f = 0
let ta_f = 0
let too_f = 0

let too_f = 1 == 1 ? 2 : 1
let ta_f = 1 == 1 ? 2 : 1
let to_f = 1 == 1 ? 2 : 1
let t_f = 1 == 1 ? 2 : 1

:echo "::  too_f = "  too_f
:echo "::   ta_f = "  ta_f
:echo "::   to_f = "  to_f
:echo "::   t_f = "  t_f

**Comment by tonymec** [comment]
@DavidTodd2 : the diference is that the bug report has it in a script whose first line is `vim9script`. You're doing it in "legacy Vim" code, not "Vim9" code.
