### ISSUE TITLE
c syntax highlighting issue

### ISSUE THREAD

**Issue by havetodothis** [vim/vim#702]
```
"typedef example
syn keyword cType hello

```

if placed within ~/.vim/after/syntax/ as "c.vim" the following snippet (test.h, it seems limited to header files) is properly highlighted (even though :set syntax reports it as cpp)

```
extern hello goodbye;

```

but if the same c.vim file is instead placed into ~/.vim/after/syntax/c/ as "types.vim", it is not highlighted unless explicitly set to syntax=c

**Comment by chrisbra** [comment]
I would say, this works as expected. syntax/cpp.vim explicitly only sources syntax/c.vim and no other file. I am closing this.
