### ISSUE TITLE
Confuse :final and :fina[lly]

### ISSUE THREAD

**Issue by rbtnn** [vim/vim#7020]
**Describe the bug**
```
vim9script
def Main()
    try
    catch
    fina
        let a = '123'
        echo a
    endtry
enddef
call Main()
```
Error detected while processing C:\Users\naru1\Desktop\a.vim[12]..function <SNR>50_Main:
line    3:
E1125: Final requires a value

**Environment (please complete the following information):**
- Patch 8.2.1744:

**Comment by brammool** [comment]
Yeah, I suppose we can keep the old meaning.
