### ISSUE TITLE
Vim9 segfault when importing function

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#7026]
**To Reproduce**

1. Save the following script as `foo.vim` where Vim can find it (e.g., into an `import` directory within `runtimepath`):

        vim9script
        export def Foo(): dict<any>
          return #{}
        enddef

2. Create another script `bar.vim` with the following content:

        vim9script
        import * as X from "foo.vim"
        X.Foo()

1. Run `vim --clean bar.vim`
2. Set `runtimepath` so that `foo.vim` can be found, if necessary.
3. `:source %`
4. A segmentation fault happens.

**Environment:**
 - Vim 8.2.1751
 - OS: macOS 10.15.6
 - Terminal: Apple's Terminal.app

**Comment by lacygoill** [comment]
Snippet reproducing the issue:
```vim
vim9script
mkdir('/tmp/some/import', 'p')
let lines =<< trim END
    vim9script
    export def Foo(): dict<any>
        return #{}
    enddef
END
writefile(lines, '/tmp/some/import/some.vim')
set rtp^=/tmp/some
import * as X from 'some.vim'
X.Foo()
```

---

Regression introduced in [8.2.1157](https://github.com/vim/vim/releases/tag/v8.2.1157).

---

- [backtrace](https://github.com/vim/vim/files/5288175/backtrace.txt)
- [valgrind log](https://github.com/vim/vim/files/5288176/valgrind.log)
- [asan log](https://github.com/vim/vim/files/5288174/asan.log)

**Comment by brammool** [comment]
> **To Reproduce**
> 
> 1. Save the following script as `foo.vim` where Vim can find it (e.g., into an `import` directory within `runtimepath`):
> 
>         vim9script
>         export def Foo(): dict<any>
>           return #{}
>         enddef
> 
> 2. Create another script `bar.vim` with the following content:
> 
>         vim9script
>         import * as X from "foo.vim"
>         X.Foo()
> 
> 1. Run `vim --clean bar.vim`
> 2. `:source %`
> 3. A segmentation fault happens.

The "import as" has not been implemented yet.  But it should not crash,
I'll add an error message.

-- 
Never enter the boss's office unless it's absolutely necessary.  Every boss
saves one corner of the desk for useless assignments that are doled out like
Halloween candy to each visitor.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
