### ISSUE TITLE
Vim9: wrong comment at ":h vim9-scopes"

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7030]
The help at `:h vim9-scopes` contains this line:

<https://github.com/vim/vim/blob/c0e29010f68a0ebe439f9bd78493799c60b7bfd3/runtime/doc/vim9.txt#L134>

It's wrong, and is inconsistent with one of the previous line:

    def ThisFunction()          # script-local
    ...
    def ThatFunction()          # global if no local ThatFunction()

Why would `ThisFunction()` be script-local *unconditionally*, while `ThatFunction()` would be global on the condition that there is no local `ThatFunction()`?  The only difference between the two is the name.  There is no rule which specifies that a function whose name starts with the prefix `This` is handled differently than a function whose name starts with the prefix `That`.

I think the comment only makes sense for a function reference; not for a function definition.  In a Vim9 script, `def ThatFunction()` *always* defines a script-local function.  However, if we call `ThatFunction()` and there is no function with this name in the script-local namespace, then Vim looks in the global namespace.

Here is a patch which tries to fix the error:
```diff
diff --git a/runtime/doc/vim9.txt b/runtime/doc/vim9.txt
index 4e5d2f3fe..61177b66c 100644
--- a/runtime/doc/vim9.txt
+++ b/runtime/doc/vim9.txt
@@ -131,8 +131,8 @@ autoload script the "name#" prefix is sufficient. >
 	def ThisFunction()          # script-local
 	def s:ThisFunction()        # script-local
 	def g:ThatFunction()        # global
-	def ThatFunction()          # global if no local ThatFunction()
 	def scriptname#function()   # autoload
+	ThatFunction()              # global if no local ThatFunction()
 
 When using `:function` or `:def` to specify a new function inside a function,
 the function is local to the function.  It is not possible to define a
```

**Comment by lacygoill** [comment]
I moved the line to the bottom to separate the function reference from the function definitions, which – I think – makes the documentation a little less confusing.

**Comment by lacygoill** [comment]
Although `:call` is technically not necessary, maybe it could be useful here to distinguish the function reference/call from the function definitions:
```diff
diff --git a/runtime/doc/vim9.txt b/runtime/doc/vim9.txt
index 4e5d2f3fe..45de01ed4 100644
--- a/runtime/doc/vim9.txt
+++ b/runtime/doc/vim9.txt
@@ -131,8 +131,8 @@ autoload script the "name#" prefix is sufficient. >
 	def ThisFunction()          # script-local
 	def s:ThisFunction()        # script-local
 	def g:ThatFunction()        # global
-	def ThatFunction()          # global if no local ThatFunction()
 	def scriptname#function()   # autoload
+	call ThatFunction()         # global if no local ThatFunction()
 
 When using `:function` or `:def` to specify a new function inside a function,
 the function is local to the function.  It is not possible to define a
```

**Comment by brammool** [comment]
Thanks for noticing.  Let make the first paragraph just about defining a function.  The second paragraph is about calling a function.  I will add a remark that using "g:" is recommended when calling a global function.
