### ISSUE TITLE
Unexpectedly leaving insert mode when job writes to hidden buffer using prompt buffers (regression by patch 8.2.1654)

### ISSUE THREAD

**Issue by puremourning** [vim/vim#7035]
**Describe the bug**

After patch 8.2.1654, insert mode is exited unexpectedly using prompt-buffers when a job writes to a hidden buffer.

I used the repro case to bisect this to 8.2.1654 patch.

**To Reproduce**
Detailed steps to reproduce the behavior:

test.vim

```viml
set buftype=prompt

call prompt_setprompt( bufnr(), 'Enter some text: ' )

call job_start( [ 'uuencode', '/dev/urandom', '/dev/stdout' ], #{
      \ out_io: 'buffer',
      \ out_name: ''
      \ } )
```

* `vim -Nu NONE -S test.vim`
* `i`
* type something

You will be bumped unexpectedly out of insert mode into normal mode as you're typing.

**Expected behavior**

Remain in insert mode until pressing `<CR>` in the prompt buffer.

**Environment (please complete the following information):**
 - Vim version 8.6.1654 and later
 - OS: Linux RHEL 7, macOS
 - Terminal: tmux, PuTTY, iTerm

**Comment by brammool** [comment]
I'm surprised patch  8.6.1654 would cause this, and only now gets reported.
Are you sure it's not related to 8.2.1762 ?

**Comment by puremourning** [comment]
I can check but I bisected and it indicated the above commit. I can confirm that with 8.2.1762 we no longer have the pum left open, but it still exits insert mode unexpectedly. With 8.1.1654, you end up with both - exit insert mode unexpectedly _and_ the pum is left open.

**Comment by tonymec** [comment]
* Does it happen also in gvim?
* What are the answers to
```vim
:set timeout? timeoutlen? ttimeout? ttimeoutlen?
```
(including the question marks)?


Best regards,
Tony.

**Comment by puremourning** [comment]
> Does it happen also in gvim?

Will check motif GUI at work tomorrow, sorry don't have a gvim here right now.

For the record, it _does_ repro in MacVim (GUI) with: 

```
ben@BenMBP vim-clean % gvim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 28 2020 22:02:11)
macOS version
Included patches: 1-1768
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
```

> What are the answers to :set timeout? timeoutlen? ttimeout? ttimeoutlen?

<img width="534" alt="Screenshot 2020-09-28 at 22 21 56" src="https://user-images.githubusercontent.com/10584846/94487504-09dde480-01d9-11eb-8c34-ec4fec370429.png">

* `timeout`
* `timeoutlen=1000`
* `ttimeout`
* `ttimeoutlen=100`

**Comment by vim-ml** [comment]
On Mon, Sep 28, 2020 at 11:23 PM Ben Jackson <vim-dev-github@256bit.org>
wrote:

> Does it happen also in gvim?
>
> Will check motif GUI at work tomorrow, sorry don't have a gvim here right
> now.
>
> For the record, it *does* repro in MacVim with:
>
> ben@BenMBP vim-clean % gvim --version
> VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 28 2020 22:02:11)
> macOS version
> Included patches: 1-1768
> Compiled by Homebrew
> Huge version with MacVim GUI.  Features included (+) or not (-):
>
> What are the answers to :set timeout? timeoutlen? ttimeout? ttimeoutlen?
>
> [image: Screenshot 2020-09-28 at 22 21 56]
> <https://user-images.githubusercontent.com/10584846/94487504-09dde480-01d9-11eb-8c34-ec4fec370429.png>
>
>    - timeout
>    - timeoutlen=1000
>    - ttimeout
>    - ttimeoutlen=100
>
>
> Hm, with the above settings, Vim ought to be able to tell the difference
between an Esc key hit at the keyboard and a ^[ sent as part of a keycode,
so I suppose it isn't that. Also, if the problem happens in the MacVim GUI
I would expect it to happen also in an X11 or W32/64 GUI but I'm less sure
about that.

Best regards,
Tony.

**Comment by puremourning** [comment]
Yes Tony I’m fairly sure that this is not a mapping issue. It’s as if something is calling stopinsert. I have a couple of theories of how to minimise the repro case. Will try after work hopefully. 

Re the point about being not reported before, it seems that it’s only prompt buffers that are affected, which are not frequently used.

**Comment by puremourning** [comment]
OK, this is easy to repro. Here's a trivial case.

```viml
set buftype=prompt

call prompt_setprompt( bufnr(), 'Enter some text: ' )

call job_start( [ 'uuencode', '/dev/urandom', '/dev/stdout' ], #{
      \ out_io: 'buffer',
      \ out_name: ''
      \ } )
```

* `vim -Nu NONE -S test.vim`
* enter insert mode `i` and type some characters - you're bumped out of insert mode

**Comment by puremourning** [comment]
Here's a test that repros it:

```

function! Test_Prompt_While_Writing_To_Hidden_Buffer()
  call CanTestPromptBuffer()
  let scriptName = 'XpromptscriptHiddenBuf'
  let script =<< trim END
    set buftype=prompt
    call prompt_setprompt( bufnr(), 'cmd:' )
    let job = job_start( [ 'uuencode', '/dev/urandom', '/dev/stdout' ], #{
      \ out_io: 'buffer',
      \ out_name: '' } )
    startinsert
  END
  exec script->writefile( scriptName )

  let buf = RunVimInTerminal('-S ' . scriptName, {})
  call WaitForAssert({-> assert_equal('cmd:', term_getline(buf, 1))})

  call term_sendkeys( buf, 'test' )
  call WaitForAssert( {-> assert_equal('cmd:test', term_getline(buf, 1)) } )

  call StopVimInTerminal(buf)
  call delete(scriptName)
endfunc
```

> || command line..script /Users/ben/Development/vim/src/testdir/runtest.vim[459]..function RunTheTest[39]..Test_Prompt_While_Writing_To_Hidden_Buffer[17]..WaitForAssert[2]..<SNR>6_WaitForCommon[11]..<lambda>3 line 1: Expected 'cmd:test' but got 'cmd:t'

**Comment by puremourning** [comment]
Been debugging this. I'm thinking that it's related to this:

```
    static void
leaving_window(win_T *win)
{
    // Only matters for a prompt window.
    if (!bt_prompt(win->w_buffer))
	return;

    // When leaving a prompt window stop Insert mode and perhaps restart
    // it when entering that window again.
    win->w_buffer->b_prompt_insert = restart_edit;
    if (restart_edit != 0 && mode_displayed)
	clear_cmdline = TRUE;		// unshow mode later
    restart_edit = NUL;

    // When leaving the window (or closing the window) was done from a
    // callback we need to break out of the Insert mode loop and restart Insert
    // mode when entering the window again.
    if (State & INSERT)
    {
	stop_insert_mode = TRUE;
	if (win->w_buffer->b_prompt_insert == NUL)
	    win->w_buffer->b_prompt_insert = 'A';
    }
}

    static void
entering_window(win_T *win)
{
    // Only matters for a prompt window.
    if (!bt_prompt(win->w_buffer))
	return;

    // When switching to a prompt buffer that was in Insert mode, don't stop
    // Insert mode, it may have been set in leaving_window().
    if (win->w_buffer->b_prompt_insert != NUL)
	stop_insert_mode = FALSE;

    // When entering the prompt window restart Insert mode if we were in Insert
    // mode when we left it.
    restart_edit = win->w_buffer->b_prompt_insert;
}

```

When using `aucmd_prepwin` we actually leave the window in order to write to the hidden buffer, and we're calling `leaving_window()`. . But it seems like  we're not calling `entering_window()` for the prompt buffer when reverting this temporary window.

For certain when we _do_ call `entering_window()`, `bt_prompt(win->w_buffer)` is false. I'ma summing that's actually entering the temporary autocmd window.


Are we missing a call to `win_enter` in `aucmd_restbuf()` ? That seems intrusive, but I haven't fully groked this code yet.

**Comment by brammool** [comment]
I can't reproduce because "uuencode: Command not found".  Perhaps something more common (and not keeping the CPU busy)?

**Comment by brammool** [comment]
Oh, and there is no aucmd_prepwin(), you probably mean aucmd_prepbuf().  But it doesn't call leaving_window() directly.

**Comment by puremourning** [comment]
Just need a job to write to a hidden buffer while in insert mode.

This repro's it too

```
set buftype=prompt

call prompt_setprompt( bufnr(), 'Enter some text: ' )

augroup TEST
  au InsertEnter call job_start( [ 'ls' ], #{
      \ out_io: 'buffer',
      \ out_name: ''
      \ } )
augroup END

```


this seems to resolve it:

```
ben@BenMBP vim-clean % git diff
diff --git a/src/autocmd.c b/src/autocmd.c
index d5c61ca6a..1789d0477 100644
--- a/src/autocmd.c
+++ b/src/autocmd.c
@@ -1530,6 +1530,7 @@ win_found:
 
        restore_snapshot(SNAP_AUCMD_IDX, FALSE);
        (void)win_comp_pos();   // recompute window positions
+       win_enter(aco->save_curwin, TRUE);
        unblock_autocmds();
 
        if (win_valid(aco->save_curwin))
ben@BenMBP vim-clean % 
```

**Comment by puremourning** [comment]
>Oh, and there is no aucmd_prepwin(), you probably mean aucmd_prepbuf(). But it doesn't call leaving_window() directly.

Yeah I meant `aucmd_prepbuf()` - this calls `win_split_ins()`, which calls `    win_enter_ext(wp, FALSE, FALSE, TRUE, TRUE, TRUE);` ... and _that_ calls `leaving_window()`

**Comment by puremourning** [comment]
OK here's a test which repros it too; had to introduce some sleeps though :/

```viml
function! Test_Prompt_While_Writing_To_Hidden_Buffer()
  call CanTestPromptBuffer()
  let scriptName = 'XpromptscriptHiddenBuf'
  let script =<< trim END
    set buftype=prompt
    call prompt_setprompt( bufnr(), 'cmd:' )
    let job = job_start( [ '/bin/sh', '-c', 'while true; do echo line; sleep 0.2; done' ], #{
      \ out_io: 'buffer',
      \ out_name: '' } )
    startinsert
  END
  exec script->writefile( scriptName )

  let buf = RunVimInTerminal('-S ' . scriptName, {})
  call WaitForAssert({-> assert_equal('cmd:', term_getline(buf, 1))})

  call term_sendkeys( buf, 'test' )
  call WaitForAssert( {-> assert_equal('cmd:test', term_getline(buf, 1)) } )
  sleep 10m
  call term_sendkeys( buf, 'test' )
  call WaitForAssert( {-> assert_equal('cmd:testtest', term_getline(buf, 1)) } )
  sleep 10m
  call term_sendkeys( buf, 'test' )
  call WaitForAssert( {-> assert_equal('cmd:testtesttest', term_getline(buf, 1)) } )

  call StopVimInTerminal(buf)
  call delete(scriptName)
endfunc
```

**Comment by tjdevries** [comment]
I was wondering if this patch (that I just made myself when I first encountered the bug) is useful:

https://github.com/neovim/neovim/pull/12977

I have no idea if this is the "right" solution or not, just figured I'd show what I was thinking. I just expected `:stopinsert` to just completely shutdown everything that could be happening in insert mode.

**Comment by happy-dude** [comment]
Just so no one is confused about @puremourning 's test script, `WaitForAssert` is defined in https://github.com/puremourning/vimspector/blob/4ed915828285c067b7f4a35fecc7e0ed56fc9be8/tests/lib/plugin/shared.vim.

I believe you are calling helper functions from the vimspector plugin, puremourning?

EDIT: if you can upload your full script (and dependencies), it could help us run your test case 👍
As it is now, `CanTestPromptBuffer`, `RunVimInTerminal` and other functions/vars are undefined.

**Comment by puremourning** [comment]
@Happy-Dude my test runs in Vim’s test suite. Paste it into `test_promt_buffer.vim`

Those functions are defined in vim’s shared.vim and friends.

**Comment by brammool** [comment]
Thanks for figuring this out and writing a test.  I'll clean it up a bit.

**Comment by puremourning** [comment]
Thanks Bram. That's working nice now.
