### ISSUE TITLE
Default rulerformat

### ISSUE THREAD

**Issue by nu8** [vim/vim#7038]
I like the default `rulerformat`, but I would like to add to it. However it
seems the default value is hidden. If I try these:

~~~
set rulerformat
set rulerformat?
~~~

I just get:

~~~
rulerformat=
~~~

Same for `statusline`.

**Comment by chrisbra** [comment]
The default rulerformat setting is used when the `rulerformat` option is empty. The default is `:set rulerformat=%c%V\ %P`

May be we should document it (or should we just change the default `p_ruf` option string?

**Comment by chrisbra** [comment]
note to readers via mail: adjusted the rulerformat setting slightly.

**Comment by nu8** [comment]
To me, if the default is empty string, then the default should be no `rulerformat`.

If the default is some `rulerformat`, then the value should not be empty.

**Comment by chrisbra** [comment]
> To me, if the default is empty string, then the default should be no rulerformat.

You mean, if the default is empty, then the default should be to disable the `ruler` option?  I suppose such a change would be backwards incompatible. I believe there are several options, that have a default built into the C core and changing the semantics might cause some complaints.

**Comment by nu8** [comment]
what I am saying, is that `set rulerformat` or `set rulerformat?` should always reflect what is actually being shown in the Ruler. This is the case if you have a custom Ruler, but it is not the case if you have the default Ruler.

So to resolve this concern, either the Ruler should be disabled by default, Or the `set rulerformat` or `set rulerformat?` should always return the Ruler value, even if the Ruler is default. It should never return an empty string, unless the Ruler is disabled.

**Comment by chrisbra** [comment]
yes, I got what you are saying. 

However note, that you cannot explicitly disable the ruler completely. Even if we make `:set rulerformat?` output the current format, if you make it an empty string, Vim would still use the default ruler format, because this is built into the C core.
And that's what I mean with backward incompatible change.

**Comment by nu8** [comment]
Ideally an empty string would disable the Ruler. However if that cannot be done because of backward compatibility, then a compromise would be:

- `:set rulerformat?` always reflect current Ruler, never empty
- Setting Ruler to empty string enables default behavior (which should match current behavior)
