### ISSUE TITLE
autochdir no longer works on starting files

### ISSUE THREAD

**Issue by hoelzro** [vim/vim#704]
To reproduce, run the following:

```
vim -N -u NONE --cmd 'set autochdir' path/to/file
```

If you then run `:pwd` within Vim, you'll notice that it displays the directory you started from, rather than `path/to`.

I did a bisect, which led me to 6bd364e.  This commit disables `autochdir` during startup entirely to address a problem using `autochdir` with diff mode.

**Comment by devjgm** [comment]
This problem has bitten me too. One _workaround_ is to add the following to your ~/.vimrc

```
autocmd VimEnter * set autochdir
```

**Comment by chrisbra** [comment]
I am sorry, I might have caused this. I'll be looking for a solution within the next days.

**Comment by chrisbra** [comment]
Here is a patch:

``` patch
diff --git a/src/main.c b/src/main.c
index 91ef66d..426a67c 100644
--- a/src/main.c
+++ b/src/main.c
@@ -958,6 +958,11 @@ vim_main2(int argc UNUSED, char **argv UNUSED)
     redraw_all_later(NOT_VALID);
     no_wait_return = FALSE;
     starting = 0;
+#ifdef FEAT_AUTOCHDIR
+    /* has been postponed */
+    if (p_acd)
+       DO_AUTOCHDIR
+#endif

 #ifdef FEAT_TERMRESPONSE
     /* Requesting the termresponse is postponed until here, so that a "-c q"
```

**Comment by brammool** [comment]
Christian Brabandt wrote:

> Here is a patch:
> 
> ``` patch
> diff --git a/src/main.c b/src/main.c
> index 91ef66d..426a67c 100644
> --- a/src/main.c
> +++ b/src/main.c
> @@ -958,6 +958,11 @@ vim_main2(int argc UNUSED, char **argv UNUSED)
>      redraw_all_later(NOT_VALID);
>      no_wait_return = FALSE;
>      starting = 0;
> +#ifdef FEAT_AUTOCHDIR
> +    /* has been postponed */
> +    if (p_acd)
> +       DO_AUTOCHDIR
> +#endif
> ```

Thanks.  We can simplify that to just DO_AUTOCHDIR.

## 

"The amigos also appear to be guilty of not citing the work of others who had
gone before them.  Even worse, they have a chapter about modeling time and
space without making a single reference to Star Trek!"
            (Scott Ambler, reviewing the UML User Guide)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by h3xx** [comment]
@chrisbra Please ensure you thoroughly test any changes you make before pushing into master. Simple stuff, much appreciated.
