### ISSUE TITLE
Vim9: documentation about nested functions could be improved

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7048]
The help at `:h vim9-scopes` says this about nested functions:
<https://github.com/vim/vim/blob/d569a9e74684cd17f9cea63e804281388728e513/runtime/doc/vim9.txt#L166-L168>

I think the repetition of the word "function" 5 times in the same sentence, with only 1 adjective ("new") to distinguish them, might be confusing:

> When using **`:function`** or `:def` to specify a new **function** inside a **function**, the **function** is local to the **function**.

---

Besides, it's not entirely correct.  A nested function is not always local to the outer function.  For example, a `:def` function nested inside a `:function` function is not local to the latter.  It's global:
```vim
vim9script
fu Outer()
    def Inner()
        echo 'inner'
    enddef
endfu
Outer()
Inner()
```
    inner

Here, if the documentation was right, then `Inner()` should be local to `Outer()`, and an error should be raised when we run `Inner()` outside `Outer()`.  That's not the case; no error is raised because `Inner()` is global.

Similarly, if a `:def` function is nested inside a block, then it's not local to the outer function; it's local to the block:
```vim
vim9script
def Outer()
    if 1
        def Inner()
            echo 'inner'
        enddef
    endif
    Inner()
enddef
Outer()
```
    E117: Unknown function: Inner

Again, here, if the documentation was right, then `Inner()` should be local to `Outer()`, and no error should be raised when we run `Inner()` from `Outer()` (but outside the block).  That's not the case; `E117` is raised because `Inner()` is local to the block.

---

Finally, the help says that it's not possible to define a script-local function inside a function.  That's only true if the outer function is a `:def` function.  We can still nest a script-local function inside `:function`, no matter its type (legacy vs Vim9):
```vim
vim9script
fu Outer()
    fu s:Inner()
        echo 'inner'
    endfu
endfu
Outer()
s:Inner()
```
    inner
```vim
vim9script
fu Outer()
    def s:Inner()
        echo 'inner'
    enddef
endfu
Outer()
s:Inner()
```
    inner

---

Here is a patch which tries to address all these issues:
```diff
diff --git a/runtime/doc/vim9.txt b/runtime/doc/vim9.txt
index 86879dde8..2c348cbb2 100644
--- a/runtime/doc/vim9.txt
+++ b/runtime/doc/vim9.txt
@@ -163,10 +163,11 @@ autoload script the "name#" prefix is sufficient. >
 	def ThatFunction()          # global if no local ThatFunction()
 	def scriptname#function()   # autoload
 
-When using `:function` or `:def` to specify a new function inside a function,
-the function is local to the function.  It is not possible to define a
-script-local function inside a function. It is possible to define a global
-function, using the "g:" prefix.
+When using `:function` or `:def` to define a nested function inside a `:def`
+function, the nested one is local to the outer one.  If it is nested inside a
+block, then it is local to the latter.  It is not possible to define a
+script-local function inside a `:def` function.  It is possible to define a
+global function, using the "g:" prefix.
 
 When referring to a function and no "s:" or "g:" prefix is used, Vim will
 prefer using a local function (in the function scope, script scope or
```

**Comment by brammool** [comment]
Thanks, I'll update the help.  It's still a bit complicated, but the error messages should tell the user what's wrong.
