### ISSUE TITLE
[Feature Request] Could Ctrl-W O ↔ window-the-only-one be toggling, i.e.: restoring splits on second call?

### ISSUE THREAD

**Issue by psprint** [vim/vim#7050]
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

I very often occur the following problematic situation:
1. I split for :help, some other buffer/file, for Mundo plugin, etc.
2. Let's assume that I've started Mundo, i.e.: 2 splits have been added: [screenshot](https://camo.githubusercontent.com/88e7b28111c7c53ccb1b44556d4d6783533f911b/68747470733a2f2f73696d6e616c616d627572742e6769746875622e696f2f76696d2d6d756e646f2f73637265656e73686f742e706e67).
3. When reading the windows I want to take a wider look at one of the small splits → so I invoke `<C-W>O` on it.
4. When I finished I want to continue using Mundo on the edited file → **ups, the problem:** the windows are closed and there is no easy way of restoring them.

**Describe the solution you'd like**

1. A new feature → restoration of the previous windows and their layout on a following `<C-W>O` call **if** invoked on a tab with a single window.
2. So after reading one of the Mundo's windows I then just invoke `<C-W>O` again and get back to the previous splits.

**Comment by chrisbra** [comment]
My workaround for that feature is to use `:tab :split` when needed. Also see this plugin: https://github.com/troydm/zoomwintab.vim

**Comment by brammool** [comment]
There are many ways this can be done.  You can easily make a plugin yourself, or a fairly simple mapping.  Perhaps using winsaveview() and winrestview(). 
I don't think we should add a command that only does one of the possible ways a user would want to do this.
