### ISSUE TITLE
unable to give focus to rightmost vim window using mouse

### ISSUE THREAD

**Issue by OSS542** [vim/vim#7052]
Description:
I am unable to give focus to the right-most window of a multiple window vim display by using the mouse.

Reproduction:
 1) xterm
 2) vim
 3) :vnew
 4) :vnew
     # three vim windows opened, focus is with left-hand window

 5) click on bottom bar of center window
     # focus goes to center window

6) click on bottom bar of right-hand window
    # focus goes to left-hand window

7) ctrl-w L
    # focus goes to center window

8) ctrl-w L
    # focus goes to right-hand window

9) click on bottom bar of right-hand window
    # focus goes to left-hand window

Expected behavior:
At step 6, focus should have gone to right-hand window instead of left hand window.

Environment :

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun 19 2020 20:54:44)

 OS: linux, custom built entirely from source code

window manager: i3 version 4.16 (2018-11-04)  running in X11 root window

Linux DellXPS 5.7.0 #2 SMP Sat Jun 6 23:11:36 JST 2020 x86_64 GNU/Linux

Terminal: xterm

**Comment by k-takata** [comment]
Maybe the cursor position is over 223 columns?
Try `set ttymouse=sgr`.
See `:help xterm-mouse` and `:help sgr-mouse`.

**Comment by OSS542** [comment]
Thanks for your quick response.   I tried that, but unfortunately got the same result as before.

**Comment by OSS542** [comment]
An additional note of interest:  I tried using a single single window taking up the entire width of the monitor.   I then used ":set ttymouse=sgr".  I made a single very long line of characters at the top of the display, and tried positioning the cursor along it using the mouse.   I found that the cursor went to the beginning of the line for every column after 223.

**Comment by k-takata** [comment]
Is your xterm version 277 or later? (What does `:echo v:termresponse` show?)

**Comment by OSS542** [comment]
something that may be important:
xterm version: X.Org 7.7.0(231)

**Comment by OSS542** [comment]
looks like I need to update xterm then.   I'll give that a shot and see what happens.

**Comment by OSS542** [comment]
updating xterm to 359 eliminates the problem.   Many Thanks for your very prompt assistance.....:-)
