### ISSUE TITLE
`%:p:h:S` doesn't work

### ISSUE THREAD

**Issue by DemiMarie** [vim/vim#706]
It would be nice to be able to run:

``` vim
:make -C %:p:h:S |" doesn't work
```

to run `make` with the directory set to the directory containing the file currently being edited.  This doesn't work because Vim expands `%:p:h:S` to the (shell-quoted) name of the currently-edited file, not that of the containing directory.

The (ugly) workaround is:

``` vim
" ugly workaround for %:p:h:S not working
:execute ':make -C' . shellescape(expand('%:p:h', 1))
```

**Comment by chrisbra** [comment]
closed by https://github.com/vim/vim/releases/tag/v7.4.1641
