### ISSUE TITLE
args forgets undo history

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#7072]
When editing a file with `:args`, its undo history is cleared.

**To Reproduce**
1. Run `vim --clean --cmd 'set undofile'` 
2. Make some changes to populate the undo history.
3. `:w foo.txt`
4. `:bwipe`
5. `:edit foo.txt`, undo and redo and verify that the undo history has been recorded.
6. `:bwipe`
7. `:args foo.txt` and type  `u`
8. The buffer is cleared. 

**Expected behavior**
The undo history should have been preserved.

**Environment**
 - Vim 8.2.1794
 - OS: macOS 10.15
 - Terminal: Apple Terminal.app

**Comment by lifepillar** [comment]
This is a couple of tests. For me, the first passes, but the second fails.

```vim
fun! Test_undo_after_edit()
  set undofile
  new
  execute "norm ix\<c-g>uy\<c-g>uz"
  write! foo.txt
  bwipe
  edit foo.txt
  call assert_equal('xyz', getline(1))
  silent undo
  call assert_equal('xy', getline(1))
  silent undo
  call assert_equal('x', getline(1))
  silent redo
  call assert_equal('xy', getline(1))
  silent redo
  call assert_equal('xyz', getline(1))
  bwipe!
  set undofile&
endf

fun! Test_undo_after_args()
  set undofile
  new
  execute "norm ix\<c-g>uy\<c-g>uz"
  write! foo.txt
  bwipe
  args foo.txt
  call assert_equal('xyz', getline(1))
  silent undo
  call assert_equal('xy', getline(1))
  silent undo
  call assert_equal('x', getline(1))
  silent redo
  call assert_equal('xy', getline(1))
  silent redo
  call assert_equal('xyz', getline(1))
  bwipe!
  set undofile&
endf
```

**Comment by lacygoill** [comment]
Regression introduced in [8.1.0341](https://github.com/vim/vim/releases/tag/v8.1.0341).
