### ISSUE TITLE
Vim9: obsolete documentation about || and && operators

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7076]
The help at `:h vim9` says this about the logical operators `||` and `&&`:

https://github.com/vim/vim/blob/d1ad99b65470d3e754f6a0588a6b0dc2214a1eab/runtime/doc/vim9.txt#L1156-L1170

I know that there is a TODO at the end, meaning that it's still a work in progress, but the documentation is no longer true since (I think) 8.2.1795.  The following snippet does not save the value `44` in the variable `result`:
```vim
vim9script
var value = 44
var result = value || 0  # result == 44
```
Instead, it raises `E1023`:

    E1023: Using a Number as a Bool: 44

---

The help also says that all these expressions raise errors:

    8 || 0       Error!
    'yes' && 0   Error!
    [] || 99     Error!

This is true, but the error message is not always the same.
```vim
vim9script
eval 8 || 0
```
    E1023: Using a Number as a Bool: 8
```vim
vim9script
eval 'yes' && 0
```
    E1030: Using a String as a Number
```vim
vim9script
eval [] || 99
```
    E745: Using a List as a Number

It's subjective, but I find it would be easier to understand if the error message was always like the first one:

    E1023: Using a Number as a Bool: 8
    E1023: Using a String as a Bool: 'yes'
    E1023: Using a List as a Bool: []

**Comment by lacygoill** [comment]
> The help also says that all these expressions raise errors:

On lines 511 to 513.

**Comment by lacygoill** [comment]
Should the help give a rationale as to why `&&` and `||` only accept booleans or the numbers 0 and 1, while `!` seems to accept any value?
```vim
vim9script
eval 1 && 'yes'
```
    E1030: Using a String as a Number
```vim
vim9script
eval !'yes'
```
    no error

**Comment by lacygoill** [comment]
> Should the help give a rationale as to why && and || only accept booleans or the numbers 0 and 1, while ! seems to accept any value?

I guess the help gives the rationale here:
https://github.com/vim/vim/blob/d1ad99b65470d3e754f6a0588a6b0dc2214a1eab/runtime/doc/vim9.txt#L485-L487

That's what JavaScript seems to do.

**Comment by lacygoill** [comment]
While we're on the subject of logical operators, there is no help tag for the new null coalescing operator.  So, if someone reads this in a plugin:

    0 ?? '' ?? [] ?? #{key: 123}

And they wonder what the `??` token means, they'll probably run:

    :h ??

Right now, this command jumps to the tag related to the normal filtering command `!!`.

---

Same issue with the trinary operator `?:`. `:h ?:` jumps to the `@:` tag.

---

Maybe we should add a tag for `?:` and `??` to make it easier for people to find the relevant documentation.  It could be useful if they don't know the technical names of the operators:
```diff
diff --git a/runtime/doc/eval.txt b/runtime/doc/eval.txt
index b2b16007e..cc75cb7db 100644
--- a/runtime/doc/eval.txt
+++ b/runtime/doc/eval.txt
@@ -897,7 +897,7 @@ Example: >
 All expressions within one level are parsed from left to right.
 
 
-expr1				*expr1* *trinary* *falsy-operator* *E109*
+expr1			*expr1* *trinary* *?:* *falsy-operator* *??* *E109*
 -----
 
 The trinary operator: expr2 ? expr1 : expr1
```

**Comment by lacygoill** [comment]
> there is no help tag for the new null coalescing operator

Actually there is one (`:h falsy-operator`), but its discoverability could be improved.

**Comment by lacygoill** [comment]
> Maybe we should add a tag for ?: and ?? to make it easier for people to find the relevant documentation. It could be useful if they don't know the technical names of the operators:

Ah no that's not possible, because `:h` parses `?` as a wildcard.

**Comment by lacygoill** [comment]
> Ah no that's not possible

Or maybe it is still possible:

https://github.com/vim/vim/blob/dda749ce85cc07000faa86bfd2ceaecd8e4805fc/runtime/doc/helphelp.txt#L37-L38

**Comment by lacygoill** [comment]
> Maybe we should add a tag for ?: and ?? to make it easier for people to find the relevant documentation. It could be useful if they don't know the technical names of the operators:

I forgot that tags related to operators are prefixed with `expr-` (like `:h expr-!`).  So, the patch should be:

```diff
diff --git a/runtime/doc/eval.txt b/runtime/doc/eval.txt
index b2b16007e..16e47ab8e 100644
--- a/runtime/doc/eval.txt
+++ b/runtime/doc/eval.txt
@@ -897,7 +897,7 @@ Example: >
 All expressions within one level are parsed from left to right.
 
 
-expr1				*expr1* *trinary* *falsy-operator* *E109*
+expr1		*expr1* *trinary* *expr-?:* *falsy-operator* *expr-??* *E109*
 -----
 
 The trinary operator: expr2 ? expr1 : expr1
```

**Comment by brammool** [comment]
I'll update the docs.
