### ISSUE TITLE
VIM as library

### ISSUE THREAD

**Issue by DebugBSD** [vim/vim#7077]
Hi, good afternoon!

I would like to know wif is it possible to use VIM as library instead of an editor and embed their functionality into an IDE. I tried to build VIM from source code and it seems that vim has some option to make a library but I couldn't find any documentation about it. If any, please, can someone point me to the correct place? 

Thanks!
Guille

**Comment by k-takata** [comment]
Vim doesn't support such an option.
Maybe libvim is for you?
https://github.com/onivim/libvim

**Comment by DebugBSD** [comment]
I already have seen libvim but I find somewhat more small than Vim. Well, thank you so much anyway. I had to try :D

**Comment by brammool** [comment]
The Netbeans interface was made for using Vim in an IDE.  It's very specific for the (discontinued) Sun Netbeans though.
