### ISSUE TITLE
Regression in patch 8.2.1513 for regular shells

### ISSUE THREAD

**Issue by olitb** [vim/vim#7079]
Since v8.2.1513, running a shell from vim (with :sh) leads to the parent shell (the one used to run vim in a terminal) to quit unexpectedly. This behavior is onbserved on OpenBSD-current with either bash or ksh.
This is due to the following chain of functions in os_unix.c:
mch_call_shell_fork calling (after fork, in the parent) mch_delay, calling mch_settmode (indirectly via settmode in term.c) which calls tcsetattr. But at this point the shell spawned with :sh has already called tcsetpgrp, so vim is in the background and tcsetattr triggers a SIGTTOU signal, which stops (i.e. suspends) vim. This triggers a reaction from the parent shell, etc.

In the case of a shell called from vim with :sh, vim should not touch the terminal after fork until the child shell exits.

**Comment by chrisbra** [comment]
good observation. Can you provide a PR? Thanks!

**Comment by brammool** [comment]
> Since v8.2.1513, running a shell from vim (with :sh) leads to the
> parent shell (the one used to run vim in a terminal) to quit
> unexpectedly. This behavior is onbserved on OpenBSD-current with
> either bash or ksh.
> This is due to the following chain of functions in os_unix.c:
> mch_call_shell_fork calling (after fork, in the parent) mch_delay,
> calling mch_settmode (indirectly via settmode in term.c) which calls
> tcsetattr. But at this point the shell spawned with :sh has already
> called tcsetpgrp, so vim is in the background and tcsetattr triggers a
> SIGTTOU signal, which stops (i.e. suspends) vim. This triggers a
> reaction from the parent shell, etc.
> 
> In the case of a shell called from vim with :sh, vim should not touch
> the terminal after fork until the child shell exits.

I cannot reproduc this problem.  Is this BSD specific?  Or it depends on
the shell?

I can see one problem: mch_delay() may skip setting the mode to
TMODE_SLEEP, but then restore the old mode anyway, which may have side
effects.  I'll make a patch for that.  Please check if this fixes your
problem.

-- 
You have the right to remain silent. Anything you say will be
misquoted, then used against you.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by olitb** [comment]
I can confirm that patch 8.2.1805 solves the problem under OpenBSD, thanks! This problem existed with both bash and ksh as a shell (the one calling vim and $SHELL).

Using strace under Linux before this patch, I can also see vim calling tcsetattr (ioctl TCSETS) after forking, but this does not seem to trigger any reaction from the kernel.
