### ISSUE TITLE
Incompatibilities introduced by partials

### ISSUE THREAD

**Issue by ZyX-I** [vim/vim#708]
I finally updated Vim to version 7.4.1639 and immediately regret it:
1. Automatic creation of partials by using `dict.func` have broken my plugin which relied on function reference stringified like `function('[^']\+')`. Actually it needed this only to workaround a problem in older Vim versions which created references to script-local functions as `s:…` and not as `<SNR>{SID}_…`, and other code did not need any specific output from `string(fref)`, so this was not much of a problem, also this code was broken if partials are created by `function()`.
2. Because partials are automatically created by `dict.func`, but they do not work with Python, `vim.bindeval('dict.func')` fails.
3. Because partials are automatically created by `dict.func` when `dict` contains self-containing containers plugins fail when trying to use `string(dict.func)` which errors out. `dict.func` is mentioned here only because this is not an incompatibility if partial is created “manually”.
4. I do not know what is the problem, but redefining partial stored in a dictionary does not work, which breaks https://github.com/Bashka/vim_lib and plugins based on that. Previous problems breaked my https://bitbucket.org/ZyX_I/frawor and it was fixed.

File that illustrates all problems:

``` VimL
let g:d = {}

" 1
function g:d.test1()
endfunction
let g:fname = string(g:d.test1)[len('function('''):-len(''')')-1]
call assert_true(g:fname =~ '^\d\+$', g:fname)

" 2
if has('python')
    function d.test2()
    endfunction
    python import vim
    try
        call assert_equal(pyeval('vim.bindeval("g:d.test2")'), g:d.test2)
    catch
        call assert_true(v:false, v:exception)
    endtry
endif

" 3
let g:d.d = g:d
function g:d.test3()
endfunction
try
    call string(g:d.test3)
catch
    call assert_true(v:false, v:exception)
endtry
unlet g:d.d

" 4
function g:d.test4()
endfunction
let g:d.test4 = g:d.test4
try
    function! g:d.test4(name)
    endfunction
catch
    call assert_true(v:errmsg, v:exception)
endtry
```

`v:errors`:

```
/tmp/incompat.vim line 7: '1'', {''test1'': function(''1'')'
/tmp/incompat.vim line 17: 'Vim(call):Traceback (most recent call last):'
/tmp/incompat.vim line 28: 'Vim(call):E724: variable nested too deep for displaying'
/tmp/incompat.vim line 40: 'Vim(function):E475: Invalid argument: 4'
```

**Comment by raymond-w-ko** [comment]
I think the issue I reported here haya14busa/incsearch.vim#111 is also an example of this.

Thanks for creating an isolated test case :-)

**Comment by brammool** [comment]
Nikolai Pavlov wrote:

> I finally updated Vim to version 7.4.1639 and immediately regret it:
> 1. Automatic creation of partials by using `dict.func` have broken my
>    plugin which relied on function reference stringified like
>    `function('[^']\+')`. Actually it needed this only to workaround a
>    problem in older Vim versions which created references to script-local
>    functions as `s:…` and not as `<SNR>{SID}_…`, and other code did not
>    need any specific output from `string(fref)`, so this was not much of
>    a problem, also this code was broken if partials are created by
>    `function()`.

Is this a problem that we need to fix?  Using string() inherently has
problems, the result may change.

> 1. Because partials are automatically created by `dict.func`, but they
>    do not work with Python, `vim.bindeval('dict.func')` fails.

Looks like the Python interface supports VAR_FUNC but not VAR_PARTIAL,
that should be easy to fix.

> 1. Because partials are automatically created by `dict.func` when
>    `dict` contains self-containing containers plugins fail when trying to
>    use `string(dict.func)` which errors out. `dict.func` is mentioned
>    here only because this is not an incompatibility if partial is created
>    “manually”.

Hmm, a dict containing itself can't be used with eval(string(dict)), but
otherwise it should be OK.  I suppose we can have eval() fail instead of
string().

> 1. I do not know what is the problem, but redefining partial stored in
>    a dictionary does not work, which breaks
>    https://github.com/Bashka/vim_lib and plugins based on that. Previous
>    problems breaked my https://bitbucket.org/ZyX_I/frawor and it was
>    fixed.

That can probably be fixed.

> File that illustrates all problems:

Thanks.  Can you look into the Python problem?  I'll look into this
later when I have some time.

It's a pity it causes problems, but being able to pass dict.func as a
callback and automatically binding the dict is very convenient.
I hope that after fixing the problems that can be fixed we have only
minor incompatibilities left.

## 

hundred-and-one symptoms of being an internet addict:
104. When people ask about the Presidential Election you ask "Which country?"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
> Hmm, a dict containing itself can't be used with eval(string(dict)), but otherwise it should be OK. I suppose we can have eval() fail instead of string().

Like this?

``` diff
--- a/src/eval.c
+++ b/src/eval.c
@@ -19279,7 +19279,8 @@ f_string(typval_T *argvars, typval_T *re
     char_u numbuf[NUMBUFLEN];

     rettv->v_type = VAR_STRING;
-    rettv->vval.v_string = tv2string(&argvars[0], &tofree, numbuf, 0);
+    rettv->vval.v_string = tv2string(&argvars[0], &tofree, numbuf,
+                               get_copyID());
     /* Make a copy if we have a value but it's not in allocated memory. */
     if (rettv->vval.v_string != NULL && tofree == NULL)
    rettv->vval.v_string = vim_strsave(rettv->vval.v_string);
```

Or, do we need a parameter to make string() fail or not?

**Comment by brammool** [comment]
three out of four items have been fixed.  The first one can't really be fixed, since it depends on specific output of function(), which was brittle anyway.

**Comment by raymond-w-ko** [comment]
I can confirm that incsearch.vim work again! Thanks :-)
