### ISSUE TITLE
Regression: Ctrl+shifted digit mapping needs to be defined inconsistently in GTK GUI (since 8.2.0851)

### ISSUE THREAD

**Issue by inkarkat** [vim/vim#7081]
**Describe the bug**
This is related to #7016 and unfortunately not fixed by 8.2.1752.

Since 8.2.0851, a mapping like

    :nnoremap <C-^> :echo "mapped"<CR>

does not trigger any longer in the GTK2 GUI; it still works in terminal Vim and also other (e.g. Windows) GVIM platforms. This also affects other combinations of Ctrl and shifted number, like `<C-@>` (has to be mapped as `<C-2>`).

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `gvim --clean`
2. `:nnoremap <C-^> :echo '<lt>C-^>'<CR>`
3. `:nnoremap <C-6> :echo '<lt>C-6>'<CR>`
3. Press <kbd>Ctrl</kbd> <kbd>6</kbd> (US-English layout)
4. In GTK2 GVIM, `<C-6>` is printed, in the terminal and Windows GVIM, `<C-^>`.

**Expected behavior**
As with #7016, this is inconsistent.

**Environment (please complete the following information):**
 - Vim version 8.2.1801, starting from 8.2.0851
 - OS: Ubuntu 16.04 LTS 64-bit
 - GTK2 GUI version

**Comment by chrisbra** [comment]
possibly duplicate of https://github.com/vim/vim/issues/6457

**Comment by inkarkat** [comment]
> possibly duplicate of #6457

Right. Closing this one then, as it provides little additional information.
