### ISSUE TITLE
UTF-8 encoding doesn't work with scandics

### ISSUE THREAD

**Issue by Paippi** [vim/vim#7098]
I'm using vim 8.2.

Setting encoding to utf-8 breaks scandics "öäå".
I'm not sure whether it has ever worked for me or did it actually broke just now.
Gvim seems to work.

I did clean my computer with bleachbit if that matters but the scandics work everywhere else (even on the terminal I'm trying to use vim with).

Here's the content of `vim --version`:

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 17 2020 21:54:53)
Included patches: 1-1704
Compiled by Arch Linux
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       +tcl/dyn
-autoservername    +folding           +multi_byte        +termguicolors
+balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
+browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              +perl/dyn          +title
+clientserver      +job               +persistent_undo   +toolbar
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           +python/dyn        +visual
+conceal           +linebreak         +python3/dyn       +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua/dyn           +ruby/dyn          +wildmenu
+dialog_con_gui    +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       +X11
+dnd               +mouse             +sound             -xfontset
-ebcdic            +mouseshape        +spell             +xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              +mouse_gpm         +statusline        +xsmp_interact
+ex_extra          -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/at-spi-2.0 -pthread    -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -D_REENTRANT  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.32/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lz -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0  -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lelf    -lcanberra  -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.32/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/5.32/core_perl/CORE -lperl -lpthread -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm

**Comment by Paippi** [comment]
Ok so it works within actual terminal but not in terminal emulator. Tried with urxvt and xterm.

**Comment by chrisbra** [comment]
Please provide a reproduction example

**Comment by Paippi** [comment]
Ok yeah so it wasn't problem in vim eventually, but anyway if someone else has the same problem as it can be unclear where the problem lies and it may seem like it's vim's problem when the scandics work everywhere else.

Heres the how to produce:
```
$ vim
:set encoding=utf-8
```
Type any of these characters "åäö".

It was indeed problem that the bleachbit had wiped out some important files.

Here's how I eventually fixed the issue (not sure if I had to reinstall all of those):
Reinstall glibc, lib32-glibc and dkms
```
pacman -S glibc lib32-glibc dkms
```
Changed LANG from /etc/locale.conf from en_US to en_US.UTF-8

regenerated locales
```
sudo locale-gen
```
Then I had to do a reboot (problem didn't get fixed until then).

**Comment by tonymec** [comment]
Yes, that change of $LANG change should cure it if you haven't set $LC_CTYPE which IIUC is the actual culprit ($LANG is used as a fallback for undefined $LC_ settings but $LC_ALL overrides them all).

It is no crime to set the various locale settings to different values: what I use is
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LC_TIME=en_GB
LC_PAPER=en_GB
LC_ALL=

and in addition, when I want a directory listing with all uppercase before all lowercase I use:

LC_COLLATE=C ls -l

to temporarily set that setting to C i.e. ASCII sort.

For details see
        man 7 locale

(N.B. There are several manpages for "locale", the one in section 7 has the best explanation of which variable is for what.)

Best regards,
Tony.

**Comment by Paippi** [comment]
Thanks for the response @tonymec!

The locales are a bit unknown territory for me. I have a feeling that the LANG wasn't the culprit or perhaps I had generated locales before with the right value before and then changed it to en_US if that can have impact(?). The reason why I'm doubting is because I reinspected some of my documents and I had used scandics.

Do you have the LC_COLLATE set to `C` or `C ls -l ` or is the `ls -l` just a demonstration where it would work?

BR,
Samuli

**Comment by tonymec** [comment]
The line

LC_COLLATE=C ls -l

is a bash command-line which means "set $LC_COLLATE temporarily to C while executing the command ls -l". The result is a directory listing in the order A..Za..z rather than (Aa)(Bb)(Cc)..(Xx)(Yy)(Zz).

Any environment variable can thus be set temporarily by prefixing it to a shell command (usually a command to execute some program); the previous value of that environment value will reappear when that command finishes executing.

Each locale setting is in several parts: for instance, en_US.UTF-8 means: language "English", region "United States", charset "UTF-8". Without the .UTF-8 the charset would default to Latin1 which has values for ö ä ø and IIRC even æ ð and þ so maybe it should be possible to type Scandinavian languages even in a Latin1 terminal — provided that your keyboard and the program you run agree on what means what. See for instance https://vim.fandom.com/wiki/Working_with_Unicode

UTF-8 is however "the way of progress", it can represent any character known anywhere to the computer industry and it is used in more and more systems as time goes on. In my experience, using it not only in Vim but also in terminals makes for fewer problems — as you noticed.

For a detailed explanation of what the LC_something environment variables do, see the manpage for "locale" in section 7 ("man 7 locale" on GNU-Linux).

Best regards,
Tony.
