### ISSUE TITLE
Vim9: crash when creating popup from timer

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7100]
**Describe the bug**

In Vim9 script, creating a popup from a timer might make Vim crash.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        au BufWinLeave * reltime()
        def Func()
            popup_menu('', {})
            timer_start(0, {-> popup_create('', 0)})
        enddef
        Func()
    EOF
    )

`E715` is raised; this is expected.

Press `C-c` twice to interrupt the error and get rid of its message.
Run `:b`: Vim crashes.

**Expected behavior**

Vim doesn't crash.

**Environment**

 - Vim version: 8.2 Included patches: 1-1817
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(360)

**Additional context**

- [backtrace](https://github.com/vim/vim/files/5357901/backtrace.txt)
- [valgrind log](https://github.com/vim/vim/files/5357902/valgrind.log)

**Comment by lacygoill** [comment]
The autocmd can be simplified a little; there is no need for it to execute anything; it just needs to exist:
```vim
vim9script
au BufWinLeave * #
def Func()
    popup_menu('', {})
    timer_start(0, {-> popup_create('', 0)})
enddef
Func()
```

**Comment by lacygoill** [comment]
> Run `:b`: Vim crashes.

It doesn't matter which command is executed.  At that point, any command makes Vim crash.

**Comment by lacygoill** [comment]
I wonder whether it has anything to do with https://github.com/vim/vim/issues/6701.

**Comment by lacygoill** [comment]
> I wonder whether it has anything to do with #6701.

The reason I mention this other report, is because in both cases:

 - the issue is specific to Vim9
 - a nested function is involved (if, here, we consider the lambda passed to the timer as a kind of nested function)
 - a crash is involved
 - an interruption is necessary to trigger the crash

**Comment by lacygoill** [comment]
Regression introduced in [8.2.0424](https://github.com/vim/vim/releases/tag/v8.2.0424).

---

I'm not sure but maybe these previous commits are somewhat related to the issue:

 - [8.2.0420](https://github.com/vim/vim/releases/tag/v8.2.0420)  Vim9: cannot interrupt a loop with CTRL-C
 - [8.2.0421](https://github.com/vim/vim/releases/tag/v8.2.0421)  interrupting with CTRL-C does not always work

**Comment by brammool** [comment]
I fixed it where it happens.  It's unclear why did_throw got set while current_exception isn't.
I didn't manage to write a test for this.  It may require running another Vim instance.
