### ISSUE TITLE
'langmap': perhaps incomplete docs or a bug

### ISSUE THREAD

**Issue by lkintact** [vim/vim#7101]
**Describe the bug**
'langmap' description at `:help 'langmap'` mentions escaping special characters:
```
	Special characters need to be preceded with a backslash.  These are
	";", ',' and backslash itself.
```
The double quote (`"`) isn't listed, but requires escaping too.

**To Reproduce**
1. Run `gvim.exe --clean --cmd "language messages English" --cmd "set encoding=utf-8"`.
2. Execute `:set langmap=Э;"`, gVim emits `E357: 'langmap': Matching character missing for <042d>`.
3. Execute `:set langmap=Э;\"`, no errors are displayed.

**Environment:**
 - Vim version 8.2.1815
 - OS: Windows 10 Home 1803
 - Terminal: GUI.

**Comment by jamessan** [comment]
See `:help option-backslash`.  `"` is the comment character, so it needs to be escaped for a literal `"` to be in the option value.

**Comment by brammool** [comment]
Yes, double quote and also | always need escaping.  Still useful to mention them here as well.
