### ISSUE TITLE
'langmap': the comma (,) character requires not one, but two backslashes to be escaped

### ISSUE THREAD

**Issue by lkintact** [vim/vim#7102]
**To Reproduce**
1. Run `gvim.exe --clean --cmd "language messages English" --cmd "set encoding=utf-8"`.
2. Execute `:set langmap=б;\,`. gVim emits `E357: 'langmap': Matching character missing for <0431>`.
3. Execute `:set langmap=б;\\,`, no errors are emitted.

**Environment:**
 - Vim version 8.2.1815
 - OS: Windows 10 Home 1803
 - Terminal: GUI.

**Comment by jamessan** [comment]
See `:help option-backslash`.  The backslash needs to be escaped for a literal backslash to be in the actual option value.

**Comment by lkintact** [comment]
Thanks for the help, @jamessan, and in #7101 too.
What confuses me here is the semicolon (`;`), also being a special character for `'langmap'`, doesn't require a second backslash, i.e. `:set langmap=ж;\;`, for example, works.
