### ISSUE TITLE
The gN command stops working under some cirumstances

### ISSUE THREAD

**Issue by lkintact** [vim/vim#7104]
**To Reproduce**
1. Run `gvim.exe --clean --cmd "language messages English" --cmd "set encoding=utf-8"`.
2. Execute `:set hlsearch`.
3. Execute `:help buffer`.
3. Execute `/list`, the matches become highlighted in yellow.
4. Hit <kbd>g</kbd><kbd>N</kbd>. gVim switches to Visual mode and selectes `list` in the `Edit buffer [N] from the buffer list.  If [N] is not given,` line.
5. Hit <kbd>g</kbd><kbd>N</kbd> again. The selection is expanded upper, up to `t that points` in the `This is the most recent entry in the jump list that points` line.
6. Hit <kbd>g</kbd><kbd>N</kbd> one more time. Nothing happens.

**Expected behavior**
The selection should be expanded further up to the in the `in the buffer list.` line at step 7.

 **Environment:**
 - Vim version 8.2.1815
 - OS: Windows 10 Home 1803
 - Terminal: GUI.

**Comment by lacygoill** [comment]
Possibly fixed by [8.2.1823](https://github.com/vim/vim/releases/tag/v8.2.1823).

**Comment by brammool** [comment]
Forgot to reference this issue in patch 8.2.1823.  Should be fixed now.
