### ISSUE TITLE
Under xterm, <CTRL-_> stops working after pressing another control character

### ISSUE THREAD

**Issue by tomushkin** [vim/vim#7108]
**Describe the bug**

`CTRL-_` mappings stop working after pressing any other `CTRL-?` combination. This appears to be xterm specific.

**To Reproduce**

1. Open xterm
2. Run:
```
$ vim -Nu NONE -c 'set <C-_>=/' -c 'nno <C-_> :echom "Control+/ pressed" <cr>'
```
(I discovered this trying to map `CTRL-/` to `CTRL-_`. Here I'm using just `/` as it doesn't appear to make a difference which key is pressed).

3. Press `/` : the mapping works
4. Press `CTRL-L` or any other `CTRL`
5. Press `/` : the mapping no longer works

**Expected behavior**
`/` should continue to be recognized. 

**Environment (please complete the following information):**
 - Vim version 8.2.1823
 - OS: Arch Linux
 - Terminal: XTerm(360)

**Additional context**

The issue is present even if I remap the key directly in xterm translations:

```
XTerm*VT100.translations:      #override \n\
       Ctrl <Key> /: string(0x1f) \n
```

**Comment by lacygoill** [comment]
Try to disable the modifyOtherKeys feature:

    vim -Nu NONE --cmd 'set t_TI= t_TE=' -c 'set <C-_>=/' -c 'nno <C-_> :echom "Control+/ pressed" <cr>'
                 ^---------------------^

Add this line into your vimrc:

    set t_TI= t_TE=

If you need the modifyOtherKeys feature to remain enabled, then I don't know how to fix the issue.  However, it reminds me of another issue https://github.com/vim/vim/issues/5951.

The reason why I mention the latter, is because in both cases, the mappings give different results depending on whether a chord using the control modifier has been pressed at least once.  I was told that maybe setting some of the input method options could help.  Run the `:opt` command, and look for the "24 language specific" section.  In it, you should find these options:

    iminsert            in Insert mode: 1: use :lmap; 2: use IM; 0: neither
    imstyle             input method style, 0: on-the-spot, 1: over-the-spot
    imsearch            entering a search pattern: 1: use :lmap; 2: use IM; 0: neither
    imcmdline           when set always use IM when starting to edit a command line
    imstatusfunc	function to obtain IME status
    imactivatefunc	function to enable/disable IME

In my case, it didn't seem to help, but maybe it will in your case.

**Comment by lacygoill** [comment]
> Run the :opt command, and look for the "24 language specific" section. In it, you should find these options:

I might have missed some input method options.  For example, `'imdisable'`.

**Comment by brammool** [comment]
Why do you use 'set <C-_>=/' ?  If you leave that out it should work fine.
Vim recognizes that the terminal supports modifyOtherkeys and then handles escape sequences differently, so that it is possible that key combinations that normally produce the same character can be mapped separately.

**Comment by lacygoill** [comment]
> I discovered this trying to map CTRL-/ to CTRL-_.

Try to use a recursive mapping.  For example, in your vimrc, instead of writing this:

    set <C-_>=/
    nno <C-_> :echom "Control+/ pressed"<cr>

Write this:

    nno <C-_> :echom "Control+/ pressed"<cr>
    nmap <C-S-/> <C-_>

**Comment by tomushkin** [comment]
I started with `set <C-_>=^[[27;5;47~` (`<C-S-V><C-/>`) because my mappings and a handful of plugins expect `<C-/>`, for which there is no control character to be sent as `^_`. I wanted to teach Vim about it so I don't have to redefine everything for xterm in particular.

I then realised that it doesn't matter which sequence `<C-_>` is set to, the behavior is still the same. Trying to keep it simple I used `/` here, sorry for the confusion.

@lacygoill Thanks! Disabling modifyOtherKeys solves the issue and makes xterm behave like other non-modifyOtherKeys terminals, sending `^_` for `CTRL-/`. Your second message is also correct, under modifyOtherKeys I can bind `<C-/>` to `<C-_>` directly.

**Comment by lacygoill** [comment]
> Disabling modifyOtherKeys solves the issue and makes xterm behave like other non-modifyOtherKeys terminals, sending ^_ for CTRL-/.

That's great; if you think your issue is fixed, consider closing the report.
