### ISSUE TITLE
The gn command stopped working under some conditions

### ISSUE THREAD

**Issue by lkintact** [vim/vim#7109]
This seems to be a side effect of fixing #7104.

1. Run `gvim.exe --clean --cmd "language messages English" --cmd "set encoding=utf-8"`.
2. Execute `:set hlsearch`.
3. Execute `:help buffer`.
3. Execute `/list`, the matches become highlighted in yellow.
4. Hit <kbd>g</kbd><kbd>N</kbd>. gVim switches to Visual mode and selectes `list` in the `Edit buffer [N] from the buffer list.  If [N] is not given,` line.
5. Hit <kbd>g</kbd><kbd>N</kbd> again. The selection is expanded up to `list that points` in the `This is the most recent entry in the jump list that points` line.
6. Now hit <kbd>g</kbd><kbd>n</kbd>. Nothing happens.

**Expected behavior**
The selection should get smaller at step 7.

**Environment**
 - Vim version 8.2.1830
 - OS: Windows 10 Home 1803
 - Terminal: GUI.

**Comment by brammool** [comment]
I'm not quite sure what should happen in this case, but at least the cursor should move.
I suppose that after "gN" extending the visual area, "gn" would go back to the previous position.
