### ISSUE TITLE
inconsistent parenthesis matching

### ISSUE THREAD

**Issue by bart9h** [vim/vim#711]
When you mix parenthesis with and without quotes, like that:
    ( 'a(' + ')' )
the highlighting of the matching parenthesis works ok, but the `%` key to jump to the corresponding parenthesis does not. If you press  `%` with the cursor on the second parenthesis, it jumps to the fourth one, not the third.

That was with Vim 7.4 (installed from Devuan repository).

**Comment by dmelo** [comment]
I have just compiled 7.4.1644. I'm running with the command `vim -N -u NONE`. I'm using your string.

The same is happening with me. But that is not the only odd association it made. From the first parenthesis it keeps on the first (doesn't move after pressing `%`). Both the third and fourth parenthesis jumps do the second.

If you use this other string `('a('+')')` (same as @bart9h 's but without the spaces), Vim changes the associations to another incorrect way:

first -> fourth
second -> third
third -> second
fourth -> second

**Comment by bart9h** [comment]
It works fine in neovim. Just saying :}

**Comment by vim-ml** [comment]
Hi Rodolfo,

2016-3-25(Fri) 9:05:23 UTC+9 Rodolfo Borges:

> It works fine in neovim. Just saying :}

Neovim is installed matchit.vim by default.
Vim is not.
It's just the difference.

Please see the document.
:h matchit-install

Someday, I'll improve the implementation of the C source code of findmatch().

## Thanks.

Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by bart9h** [comment]
> Neovim is installed matchit.vim by default.

Haven't noticed that. I don't use neovim yet, in fact I just installed to check this bug.

Thanks for explaining, I wasn't aware of extra plugins by default in neovim.

I find it odd to have the highlighting find the right matching paren, and % not. That means there are two codes for the matching?

**Comment by vim-ml** [comment]
Hi Rodolfo,

2016-3-28(Mon) 23:27:15 UTC+9 Rodolfo Borges:

> Neovim is installed matchit.vim by default.
> 
> Haven't noticed that. I don't use neovim yet, in fact I just installed to check this bug.
> 
> Thanks for explaining, I wasn't aware of extra plugins by default in neovim.
> 
> I find it odd to have the highlighting find the right matching paren, and % not. That means there are two codes for the matching?

Yes.  Each has been done in a separate process.

The highlighting matching parenthesis process has been performed by runtime/plugin/matchparen.vim.  (by default in Vim)
This can be disabled by write to `let g:loaded_matchparen=1` to your .vimrc.

The extended "%" matching process has been performed by Vim internal logic written by C language (_1).  (by default in Vim)
When loaded matchit.vim (_2), above process has been used this plugin.

*1
In many of the programming language can express the string in single quotes, but this logic is not possible to correspond to it.
I think that it should correspond to it.

... I wrote the following in the first response, including the kind of above meaning :-)

> Someday, I'll improve the implementation of the C source code of findmatch().

*2
If you use Vim 7.4.1648 or older, please see following document.
:h matchit-install

If you use Vim 7.4.1649 or newer, adding below in your .vimrc.
:packadd! matchit

## 

Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by chrisbra** [comment]
I suppose, this can be closed?
