### ISSUE TITLE
ferm syntax

### ISSUE THREAD

**Issue by 532910** [vim/vim#7119]
Please include ferm syntax.

https://github.com/cometsong/ferm.vim
https://github.com/MaxKellermann/ferm
http://ferm.foo-projects.org/

https://github.com/cometsong/ferm.vim/issues/3

**Comment by k-takata** [comment]
Please ask each author to send the files to Bram.
Explicit permission from each author is required.

**Comment by cometsong** [comment]
@k-takata - I should send these `ferm.vim` files to Bram's email directly?
Or send the repo url to '_brammool_' git user?

**Comment by k-takata** [comment]
You can send via email or create a PR.
