### ISSUE TITLE
Use 'smartcase' with :tselect/:tj etc

### ISSUE THREAD

**Issue by blueyed** [vim/vim#712]
I think a common setting is `:set ignorecase smartcase`, which ignores case for lowercase patterns, but not for mixed case.

While this works for searching in general, it's not honored with `:tj`: `:tj Foo` will also present a tag `foo`, even though `Foo` exists.
Even if `Foo` would not exist, `:tj Foo` should not go to `foo`.

**Comment by jamessan** [comment]
In other words, it'd be nice to do `:set tagcase=smart`?

**Comment by chrisbra** [comment]
closing, as there is a solution available.

**Comment by jamessan** [comment]
No, a solution isn't available.  I was suggesting that having a "smart" value for `'tagcase'` would address the request.

**Comment by blueyed** [comment]
I think `'tagcase'` should support `smart` explicitly, and `followic` (the default) should use `'smartcase'` also (and be "smart" in case it's set).

(btw: did not know about 'tagcase', because it's not in Neovim yet.)

**Comment by chrisbra** [comment]
I made a patch [here](https://gist.github.com/chrisbra/45a9cb6b7168458e5cb307457a17ffa1)

**Comment by vim-ml** [comment]
On 2016-03-30, Christian Brabandt wrote:

> I made a patch here

Is this behavior intended to apply now to all commands that accept
search patterns as arguments, such as Yegappan's :cfilter patch?

It was never clear to me from ":help 'smartcase'" to what commands
this option was meant to apply, but I think applying it whenever a
search pattern is typed and not when the pattern is selected by the
cursor makes sense.

Regards,
Gary

**Comment by vim-ml** [comment]
Hi Gary,

On Wed, Mar 30, 2016 at 1:06 PM, Gary Johnson garyjohn@spocom.com wrote:

> On 2016-03-30, Christian Brabandt wrote:
> 
> > I made a patch here
> 
> Is this behavior intended to apply now to all commands that accept
> search patterns as arguments, such as Yegappan's :cfilter patch?

The :cfilter command uses the same logic as the :vimgrep command
to process the pattern argument. So the help described in ":h vimgrep"
for the pattern also applies to the cfilter command:

```
'ignorecase' applies.  To overrule it put |/\c| in the
pattern to ignore case or |/\C| to match case.
'smartcase' is not used.
```
- Yegappan

> It was never clear to me from ":help 'smartcase'" to what commands
> this option was meant to apply, but I think applying it whenever a
> search pattern is typed and not when the pattern is selected by the
> cursor makes sense.
> 
> Regards,
> Gary

**Comment by blueyed** [comment]
Is there a reason to not apply `'smartcase'` also to e.g. `:cfilter`, apart from backward-incompatible changes?  (which is probably the reason for the new `'tagcase'` setting?!)

**Comment by vim-ml** [comment]
Hi Daniel,

On Fri, Apr 1, 2016 at 6:35 AM, Daniel Hahler vim-dev-github@256bit.org
wrote:

> Is there a reason to not apply 'smartcase' also to e.g. :cfilter, apart
> from backward-incompatible changes? (which is probably the reason for the
> new 'tagcase' setting?!)
> 
> I wanted to follow the same logic used for the vimgrep command to use the
> pattern. There is no specific reason to not apply the smartcase setting.
> I can modify the cfilter patch to support the smartcase setting.
- Yegappan
