### ISSUE TITLE
OpenSCAD syntax

### ISSUE THREAD

**Issue by 532910** [vim/vim#7121]
Please include OpenSCAD syntax.

https://github.com/sirtaj/vim-openscad

https://github.com/openscad/openscad/
https://www.openscad.org/

https://github.com/sirtaj/vim-openscad/issues/8

**Comment by k-takata** [comment]
Please ask each author to send the files to Bram.
Explicit permission from each author is required.

**Comment by chrisbra** [comment]
you don't need to open an issue here about including new runtime files. Rather always approach the runtime file maintainers directly.
