### ISSUE TITLE
[Q]  add `NOTE` as the highlight key words such as TODO BUG XXX FIXME

### ISSUE THREAD

**Issue by arthurkiller** [vim/vim#7124]
add `NOTE` as the highlight key words suck as TODO BUG XXX FIXME

really need this

**Comment by chrisbra** [comment]
For what filetype?

**Comment by arthurkiller** [comment]
> For what filetype?

`.cpp`

**Comment by chrisbra** [comment]
You can amend the syntax files yourself. For that drop a file into `~/.vim/after/syntax/cpp.vim` (create non-existing directories) with the following content:

    syn keyword  cTodo       contained NOTE

ping @vim-jp who are the maintainer of the cpp syntax files.

**Comment by brammool** [comment]
Others may consider highlighting NOTE a bit too much, since it's something that won't go away.
I don't think we should add this to the default.  Christian has already explained how to do it for your own setup, so I consider this taken care of.

**Comment by mralusw** [comment]
It's not a solved problem, but it also doesn't belong in `vim` core. Writing a separate syntax file for every programming language is not reasonable.

Something like [this gist](https://pastebin.com/raw/5JnXcsfx) is a solution. It goes way to far, but the basic idea is sound: highlight a customizable set of WORDS (including a ':' suffix) in all comments for all known languages, and maybe also highlight those WORDS in some files that have no notion of comments. And leave the keyword test out of it, that was a bad idea to begin with.
