### ISSUE TITLE
Description of quote-mark in user manual

### ISSUE THREAD

**Issue by nsmlzl** [vim/vim#7129]
Is the verb 'editing' a typo in the description of the quote-mark (user manual: 'usr_03.txt' line 653)? 

https://github.com/vim/vim/blob/3d30af8783bf43fbfece641ec81ad8d2f01b3735/runtime/doc/usr_03.txt#L653

The reference manual states regarding the quote-mark (`:h '"`): 

> ... the cursor position when last exiting the current buffer.

Was 'exiting' meant in the user manual (instead of 'editing')?

**Comment by brammool** [comment]
It's just two ways to say the same thing.  "last editing" implies that the buffer was exited.
