### ISSUE TITLE
first keystroke not responding on entering Vim with certain config and terminal

### ISSUE THREAD

**Issue by lilydjwg** [vim/vim#7135]
**Describe the bug**

This seems to be a(nother) terminal compatibility issue introduced in #2126.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. In xfce4-terminal (0.8.9.2, vte3 0.62.1)
2. Run `vim --clean -c $'set <M-P>=\x1bP' -c 'nmap <M-t> a'` (`P` is important, others (A-O, Q-Z, a-z, 0-9 etc) don't cause this issue; the latter mapping is arbitrary as long as it's `<M-` something)
3. Type any key
4. Vim doesn't respond to the first key. Also there is a `Ã` character shown in the pending operator area for a while.

**Expected behavior**
Vim should respond to the first key too.

**Environment (please complete the following information):**
 - Vim version 8.2.0936+
 - OS: Arch Linux, Manjaro Linux
 - Terminal: xfce4-terminal and gnome-terminal without tmux (konsole are ok)

**Additional context**
I'm [mapping `<M-x>` to `^[x`](https://github.com/lilydjwg/dotvim/blob/master/plugin/escalt.vim) so that they work in most terminals (which send these keys by default for Alt combinations).

**Comment by lacygoill** [comment]
These issues look similar: https://github.com/vim/vim/issues/2581 and https://github.com/vim/vim/issues/6206.

**Comment by lacygoill** [comment]
Does it help if you clear `'t_RV'`?

    set t_RV=

What's the value of `TERM` in xfce4-terminal?  Is it different in gnome-terminal and konsole?

Does it change anything if you reset `TERM` (maybe to `xfce`):

    TERM=xfce vim --clean -c $'set <M-P>=\x1bP' -c 'nmap <M-t> a'
    ^-------^

**Comment by lacygoill** [comment]
> I'm mapping <M-x> to ^[x so that they work in most terminals (which send these keys by default for Alt combinations).

This might cause an issue when trying to insert some accented characters.  For a workaround, see [this answer](https://vi.stackexchange.com/a/26503/17449).  I don't know whether it would help for the current issue, but it's worth a try.

**Comment by roachsinai** [comment]
@lacygoill you mean this explanation https://github.com/vim/vim/issues/2581#issuecomment-639762344 ?

**Comment by lacygoill** [comment]
> @lacygoill you mean this explanation #2581 (comment) ?

Well, yes it might be relevant here, as well as the [previous comment](https://github.com/vim/vim/issues/2581#issuecomment-639746235).

**Comment by lilydjwg** [comment]
`TERM=xterm-256color` (reproducible with `TERM=xterm`). Setting `TERM=xfce` prevents this issue.

`set t_RV=` prevents this issue too and a simple test on my config doesn't reveal other issues.

An update: it *does* happen with gnome-terminal, just not when also in tmux (`TERM=tmux-256color`) and the tmux session is only attached by one client. With two clients attaching to the same tmux session, no matter what combinations of xfce4-terminal and gnome-terminal, it reproduces. Weird. (I'm updating the original report.)

I didn't verify but konsole should have `TERM=konsole`.

I also verify that only `<M-P>` has this issue. I'm going to not `set` this key.

> This might cause an issue when trying to insert some accented characters.

Yes, but it doesn't bother me much. `modifyOtherKeys` doesn't seem to work in my case last time I checked (terminal doesn't support).
