### ISSUE TITLE
Colon in string considered for indentation for Python file

### ISSUE THREAD

**Issue by yogirajh007** [vim/vim#7138]
**Description:**
While editing a python file, when a colon ":" is typed in a string in quotes (" ") , the colon is considered for indentation.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim filename.py`
3. Type a string in quotes, which contains a colon (:)
4. As soon as colon is found, the line is indented using by a tab.

**Expected behavior**
No restructuring/indentation should occur.

**Environment (please complete the following information):**
 - VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 17 2020 21:54:53)
Included patches: 1-1704
Compiled by Arch Linux
 - OS: Arch Linux
 - Terminal: Konsole

**Comment by gdupras** [comment]
I cannot reproduce this bug with Vim 8.2.1522 nor with 8.2.1845.

Do you still get this incorrect behaviour if you start Vim with `vim --clean filename.py`?

Can you show exactly what you are writing in filename.py?
