### ISSUE TITLE
how to DIY the starting text when loding vim using the command "vim"?

### ISSUE THREAD

**Issue by Firestar-Reimu** [vim/vim#7141]
I am using vim on Arch/Manjaro and there is no `blah blah/src/version.c` on my computer

**Comment by chrisbra** [comment]
Not sure, please explain clearly what your problem is.

**Comment by lacygoill** [comment]
Not sure to understand either, but if you can't read the intro message when Vim has just started, that might be due to the `I` flag which is present inside the [`'shortmess'`](https://vimhelp.org/options.txt.html#'shortmess') option; if so, try to remove it in your vimrc:
    
    set shm-=I

**Comment by chrisbra** [comment]
you can also always use the `:intro` command

**Comment by Firestar-Reimu** [comment]
I do not want the sponsor texts and I am thinking how to delete them.

**Comment by chrisbra** [comment]
I don't think we are going to remove the help about donating to the poor children. See @lacygoill answer for how to disable it. 

Closing.
