### ISSUE TITLE
Vim9: E1099 unknown error while executing popup callback

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7143]
**Describe the bug**

In Vim9 script, an unknown error might be raised when a popup callback is invoked.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script

        var filter_text = ''
        var preview_winid = 0
        var menu_winid = 0
        var source = ['/tmp/e/test/file', '/tmp/test/error/[a-1]/file']

        au BufWinLeave * #

        def Fuzzy()
            menu_winid = popup_menu('', #{filter: FilterLines, callback: ExitCallback})
            preview_winid = popup_create('', {})
        enddef

        def FilterLines(id: number, key: string): bool
            if key =~ '^\p$'
                filter_text ..= key
                popup_settext(menu_winid, matchfuzzy(source, filter_text))
                winbufnr(menu_winid)
                    ->getbufline(line('.', menu_winid))
                    ->get(0, '')
                    ->expand()
                return true
            endif
            return popup_filter_menu(id, key)
        enddef

        def ExitCallback(id: number, result: number)
            popup_close(preview_winid)
        enddef

        Fuzzy()
    EOF
    )

While the popup is open, press `e`, then `r`; `E944` is raised:

    Error detected while processing function <SNR>1_FilterLines:
    line    7:
    E944: Reverse range in character class

This is expected.

Press Enter twice; `E1099` is raised:

    Error detected while processing function <SNR>1_FilterLines:
    line   10:
    E1099: Unknown error while executing <SNR>1_ExitCallback

This is not expected; or if it is, [it should be reported](https://github.com/vim/vim/issues/6493#issuecomment-708321260).

**Expected behavior**

`E1099` is not raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-1852
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(360)

**Additional context**

I know the "minimal" example is complicated, but the original code was 20 times longer; it took several hours to get it.

**Comment by lacygoill** [comment]
I also have a 281 lines long script which raises an `E1028` error ("E1028: Compiling :def function failed").  Should `E1028` be reported just like `E1099`?  If so, I'll try to reduce the code as much as I can later.

**Comment by lacygoill** [comment]
Slightly shorter:
```vim
vim9script
au BufWinLeave * #
def FilterLines(id: number, key: string): any
    if key =~ '^\p$'
        filter_text ..= key
        popup_settext(menu_winid, matchfuzzy(source, filter_text))
        winbufnr(menu_winid)
            ->getbufline(line('.', menu_winid))
            ->get(0, '')
            ->expand()
        return true
    endif
    return popup_filter_menu(id, key)
enddef
var filter_text = ''
var source = ['/tmp/e/file', '/tmp/error/[a-1]/file']
var menu_winid = popup_menu('', #{filter: FilterLines})
var preview_winid = popup_create('', {})
feedkeys('er')
```

**Comment by lacygoill** [comment]
A little simpler and fully automated (no need to press any key):
```vim
vim9script
au BufWinLeave * #
def FilterLines(id: number, key: string): any
    filter_text ..= key
    popup_settext(menu_winid, matchfuzzy(['e', 'error-[a-1]'], filter_text))
    winbufnr(menu_winid)
        ->getbufline(line('.', menu_winid))[0]
        ->expand()
    return popup_filter_menu(id, key)
enddef
var filter_text = ''
var menu_winid = popup_menu('', #{filter: FilterLines})
feedkeys("er\r\r", 't')
```

**Comment by brammool** [comment]
Yes, E1028: should be avoided, a more specific error should be given.

**Comment by brammool** [comment]
I can fix this, but making a test for it is a bit too complicated.
