### ISSUE TITLE
'buflisted' is set when switched to via alternate-file

### ISSUE THREAD

**Issue by auwsmit** [vim/vim#715]
Here's how to reproduce what I mean: 
- `:set hidden`
- Have any initial file(s) open. 
- Create a new buffer and `set nobuflisted` in this buffer. 
- From the new buffer, use `CTRL-^` twice to switch to the first file and back. 
- Notice how the buffer is listed in the buffer list, and `set bl?` is `buflisted`? What's up with that?

I checked the docs for `'hidden'`, `'buflisted'`, `alternate-file`, and `unlisted-buffer`, but none helped make light of this for me. Did I miss something? Is this intended, or a bug? I would rather my buffer stay unlisted, even if I switch back to it, if possible.

**Comment by chrisbra** [comment]
This is documented albeit very briefly at :h 'buflisted'

> Vim sets it when starting to edit a buffer.

using `<CTRL-^>` is a command that starts editing a buffer.

One should be able to script something using the BufEnter event to reset this setting, if this really bothers you.

**Comment by auwsmit** [comment]
Thanks for the pointer. I was able to get the behavior I desired (e.g. nobuflisted persists after editing a file) with this snippet in my vimrc:

```
function! s:PersistNobl()                             
  if exists('b:persist_nobl')                         
    setl nobuflisted                                
  elseif !&buflisted                                  
    let b:persist_nobl = 1                            
  endif                                               
endfunction                                           

augroup persist_nobuflisted                           
  autocmd!                                            
  autocmd OptionSet buflisted call <SID>PersistNobl() 
  autocmd BufEnter * call <SID>PersistNobl()          
augroup END                                           
```
