### ISSUE TITLE
the script will NOT be sourced every time when trying to call a non-existing function

### ISSUE THREAD

**Issue by Yggdroot** [vim/vim#7151]
**Describe the bug**

daa2f36573db3e1df7eb1fdbc3a09a2815644048 is the first bad commit
commit daa2f36573db3e1df7eb1fdbc3a09a2815644048
Author: Bram Moolenaar <Bram@vim.org>
Date:   Sat Aug 8 21:33:21 2020 +0200

    patch 8.2.1398: autoload script sourced twice if sourced directly
    
    Problem:    Autoload script sourced twice if sourced directly.
    Solution:   Do not source an autoload script again. (issue #6644)

This commit breaks the below functionality:

https://github.com/vim/vim/blob/e13bdec6b90b3a0fce4f021e3ee986e731cea3b5/runtime/doc/eval.txt#L12126-L12130

**Comment by chrisbra** [comment]
isn't that a good thing?

**Comment by Yggdroot** [comment]
But the behavior and the document should be consistent, shouldn't it?

**Comment by brammool** [comment]
I'll update the help:

Note that when you make a mistake and call a function that is supposed to be
defined in an autoload script, but the script doesn't actually define the
function, you will get an error message for the missing function.  If you fix
the autoload script it won't be automatically loaded again.  Either restart
Vim or manually source the script.
