### ISSUE TITLE
Current line is off-by-one in batch mode when feedkeys() + execute is used

### ISSUE THREAD

**Issue by inkarkat** [vim/vim#7153]
**Describe the bug**
I got inconsistent results when writing automated tests that exercise repeating a custom mapping via the [repeat.vim](https://www.vim.org/scripts/script.php?script_id=2136) plugin. That plugin is [using `:execute`](https://github.com/tpope/vim-repeat/blob/0b9b5e742f67bc81ae4a1f79318549d3afc90b13/autoload/repeat.vim#L141) on a result of a function call, which itself [uses `feedkeys()`](https://github.com/tpope/vim-repeat/blob/0b9b5e742f67bc81ae4a1f79318549d3afc90b13/autoload/repeat.vim#L116-L117). The third required piece (yeah, it really was tricky to track down) is that silent or batch mode has to be active [`:help -s-ex`](https://vimhelp.appspot.com/starting.txt.html#-s-ex) - my [runVimTests test framework](http://www.vim.org/scripts/script.php?script_id=2565) enables that when the output is not to the terminal.

**To Reproduce**

Create a script `feedkeys-exe-s-ex.vim`:

```
call append(0, ['one', 'two', 'three'])
fun Doit()
    call feedkeys('y$') " Yanking is just an example for working with the current line.
    " Using :normal instead of feedkeys() prevents the problem:
    " normal! y$
    return ''
endfun
exe "2normal :exe Doit()\<CR>"
" Using :call instead of :execute prevents the problem:
"exe "2normal :call Doit()\<CR>"

1verbose echomsg @@ | " verbose output to print in batch mode
sleep 2	" to be able to see the output in interactive mode
quit!
```

1. Run `vim --clean -S feedkeys-exe-s-ex.vim`; this outputs the expected `two`, because of the `:2normal`.
1. Run `vim --clean -es -S feedkeys-exe-s-ex.vim`; this strangely outputs `three`, so **the command is suddenly executed one line below the expected one!**

This is a minimal example; the original code involves the full repeat.vim plugin, my own plugin with its `<Plug>`-mappings registered with repeat.vim, and a test script that first exercises that mapping and then triggers a repeat (`:normal .`) in a different line, and that's where this discrepancy emerged.

**Expected behavior**
Silent mode should not behave differently. Though the problem seems to require a rather obscure combination of `:exe` and `feedkeys()`, this is used in an ubiquitous plugin (and not in a hacky way), so it's difficult to work around. I'd hope that this is just a corruption of the internal notion of current line that can be fixed with a targeted one-line change.

**Environment (please complete the following information):**
 - Vim 8.2.1855, also found in Vim 7.4.1689, so no regression
 - OS: Ubuntu 16.04 LTS 64-bit
 - Terminal: GNOME Terminal

**Comment by brammool** [comment]
You use feedkeys() with the second argument, which means it will be put in the typeahead buffer, but not executed yet.
In ex mode it doesn't read the typeahead until later.  But you want to execute it right there, thus you need to make it feedkeys('y$', 'x').  Then it works.

**Comment by inkarkat** [comment]
@brammool, I understand that `feedkeys(..., 'x')` more or less is equivalent to `:normal`, and therefore works. Unfortunately, the repeat.vim plugin already uses [three different approaches](https://github.com/tpope/vim-repeat/blob/0b9b5e742f67bc81ae4a1f79318549d3afc90b13/autoload/repeat.vim#L110-L118) for varying Vim versions, as it has been historically difficult to inject such commands; adding the `x` flag there might have other unforeseen consequences. I'm not sure that I can get Tim Pope to change this for my admittedly uncommon use case...

Furthermore, I don't see how this is a matter of when the typeahead is consumed; there's no following command that goes one line down (so what other than a bug is doing that?!), and the problem also goes away when changing `:exe` to `:call`, which should not affect typeahead consumption, right? Because the `feedkeys()` is triggered within the `:normal`, the yank happens before the following `:echomsg` is executed, and so the yank result is printed; it's just that the yank executes one line down, but I don't see anything that is supposed to change the line, and therefore I suspect that this happens as an unintended weird side effect, and is not caused by different typeahead consumption.

> In ex mode it doesn't read the typeahead until later.

That's fine as long as it's an implementation detail, but if this causes a command to be executed in a different line (and as the example shows no hacks have been used here; there may be good reasons for not passing the `x` flag to `feedkeys()`), shouldn't this be changed so that there's no noticeable inconsistency? In my case, I have a problem with writing an automated test case for my plugin; another user may record a macro and apply this to a script that runs non-interactively in Ex mode, and suddenly the result is subtly wrong, and the problem may go unnoticed for quite some time.

**Comment by brammool** [comment]
You should not use feedkeys() unless absolutely necessary.  It's mainly added for writing tests and in the rare cases you want to replace something that the user would type.  The "x" flag is exactly for using the typeahead right away, instead of waiting for Vim to decide to check for any input, which is quite unpredictable in a script.  In many ways feedkeys() with the 'x' flag is similar to using :normal, except that it also works when not in Normal mode.

In the Ex silent mode an empty line moves the cursor down.  Again, this is not a mode you would normally used, except for some batch scripting.

**Comment by inkarkat** [comment]
> In the Ex silent mode an empty line moves the cursor down.

Ah, I think that's the part I was missing, so I guess the `:exe` makes Vim somehow "see" an empty line (there's no actual empty line in `2normal :exe Doit()<CR>`), and that triggers the move one line down. By using `:call` instead, this is being avoided.

> Again, this is not a mode you would normally used, except for some batch scripting.

Yes, I'm only using Ex mode when [my test framework detects that it is not connected to a terminal](https://github.com/inkarkat/runVimTests/blob/c839706e7292989a29fc756b56aa1e5b105f0d38/bin/runVimTests.sh#L80-L85) (e.g. when run as part of a cron job).

    # Use silent-batch mode (-es) when the test log is not printed to stdout (but
    # redirected into a file or pipe). This avoids that the output is littered with
    # escape sequences and suppresses the Vim warning and a small delay:
    # "Vim: Warning: Output is not to a terminal".
    # (Just passing '-T dumb' is not enough.)
    [ -t 1 ] || vimArguments="$vimArguments -es"

As this is the first time this problem has occurred (and I've already written 4400 tests in this style so far!), I'm just skipping the test execution if run in Ex mode:

    call vimtest#SkipAndQuitIf(mode() ==# 'c', 'Cannot test in Ex mode')

Thanks for taking the time to look into this, and for the great explanation, Bram!

**Comment by jamessan** [comment]
> I guess the `:exe` makes Vim somehow "see" an empty line (there's no actual empty line in `2normal :exe Doit()<CR>`)

There is, though.  `Doit()` returns an empty string, so `2normal :exe Doit()<CR>` becomes `2normal :exe ''<CR>`.  Why is `:exe` being used when you just want to call a function, not execute a runtime-constructed statement?

**Comment by inkarkat** [comment]
Thanks @jamessan, of course you're right! In Ex mode, the `:exe ''` makes the cursor go to the next line.

The repeat.vim plugin tries to be clever; the function only returns an empty String on the happy path, in case of an error `echoerr "<error message>"` is returned instead, so that the command is executed in the global scope of the mapping, not directly inside the function, where it would cause an undesired multi-line output instead of just forwarding the actual error message.

In [this commit](https://github.com/inkarkat/vim-repeat/commit/78453f7ea614c90474650cb8cccfb492e2f01ca7) I've reworked the error handling, using a straightforward getter and Boolean return value to transfer any error message back to the mapping's global scope. (I use this idiom in all of my plugins through a [set of utility functions](https://github.com/inkarkat/vim-ingo-library/blob/5bb32fd27aa37a767d92ed29eb76dd48a7b0c7d2/autoload/ingo/err.vim#L38-L41), too.)
