### ISSUE TITLE
Hot Module Replacement fails on :w save but is okay when using :wq

### ISSUE THREAD

**Issue by ghost** [vim/vim#716]
I've isolated the cause of failing React js + webpack Hot Module Replacement to Vim (v7.4.52).  My OS is Ubuntu 14.04 LTS.  The failing occurs without any plugins installed as well.  Only on save AND exit (:wq) does HMR execute properly.  And, yes, I have confirmed HMR executes properly on soft saves using nano and sublime_text.  I even deleted my .vimrc file while trouble shooting.

A couple reference projects to use for replicating:
https://github.com/erikras/react-redux-universal-hot-example  (modify some text in the src/containers/Home/Home.js and save with :w and the modification should appear on the front page within 6 seconds automatically...but this will only happen when using :wq)

[https://github.com/codefoundries/isomorphic-material-relay-starter-kit](url)  (similarly, modify text in webapp/components/Home_screen.jsx)

I have a hunch it has something to do with how vim manages the buffer while the terminal is connected to localhost and the dev server is running in a separate terminal.

Any suggestions will be appreciated.

node version: 5.8
npm version: 3.8.5

**Comment by chrisbra** [comment]
I don't understand how HMR is supposed to hook into Vim and I am missing information here.. I have however a feeling, that this is the wrong forum to ask questions. Please use the vim-use or vim-dev ml. Thanks.

**Comment by brammool** [comment]
MercStills wrote:

> I've isolated the cause of failing React js + webpack Hot Module
> Replacement to Vim (v7.4.52).  My OS is Ubuntu 14.04 LTS.  The failing
> occurs without any plugins installed as well.  Only on save AND exit
> (:wq) does HMR execute properly.  And, yes, I have confirmed HMR
> executes properly on soft saves using nano and sublime_text.  I even
> deleted my .vimrc file while trouble shooting.
> 
> A couple reference projects to use for replicating:
> https://github.com/erikras/react-redux-universal-hot-example  (modify
> some text in the src/containers/Home/Home.js and save with :w and the
> modification should appear on the front page within 6 seconds
> automatically...but this will only happen when using :wq)
> 
> [https://github.com/codefoundries/isomorphic-material-relay-starter-kit](url)
> (similarly, modify text in webapp/components/Home_screen.jsx)
> 
> I have a hunch it has something to do with how vim manages the buffer
> while the terminal is connected to localhost and the dev server is
> running in a separate terminal.
> 
> Any suggestions will be appreciated.

Not sure what this Hot Module Replacement is, but if it's about the way
files are written, perhaps the 'backupcopy' option can help.

## 

Amazing but true: If all the salmon caught in Canada in one year were laid
end to end across the Sahara Desert, the smell would be absolutely awful.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ghost** [comment]
The solution to this was setting swapsync to "sync".
