### ISSUE TITLE
Vim9: inconsistent error messages when using string as a number

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7167]
**Describe the bug**

In Vim9 script, using a string as a number gives inconsistent error messages.

**To Reproduce**
```vim
vim9script
eval '' - 1
```
This raises `E1030`:

    E1030: Using a String as a Number
```vim
vim9script
def Func()
    eval '' - 1
enddef
Func()
```
This raises `E1036`:

    E1036: - requires number or float arguments
```vim
vim9script
def Func()
    eval '' + 1
enddef
Func()
```
This raises `E1051`:

    E1051: Wrong argument type for +

**Expected behavior**

The same error is always raised when we wrongly try to use a string as a number.

**Environment**

 - Vim version: 8.2 Included patches: 1-1862
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(360)

**Additional context**

I've found other unexpected error messages:
```vim
vim9script
eval {} - 1
```
    E1004: White space required before and after '-'

Here, I don't understand how the message is relevant.  I think it should be:

    E1234: using Dictionary as a Number

However, this error does not exist, so maybe it should be:

    E1036: - requires number or float arguments

---
```vim
vim9script
eval [] - 1
```
    E730: using List as a String

Again, this error message is unexpected.  We're not using a list as a string, but as a number.  Maybe `E1036` should be raised instead.

---
```vim
vim9script
eval 0z1234 - 1
```
    E976: using Blob as a String

Idem.

---

If indeed some of those error messages need to be updated, should I make more tests?

There are 3 parameters to consider.  First, the operator:

   - `+`
   - `-`
   - `*`
   - `/`
   - `%`
   - `..`

*I might have missed a few.*

Second, the types of the operands:

   - number, string
   - number, funcref
   - number, list
   - number, dictionary
   - number, float
   - number, bool
   - number, none
   - number, job
   - number, blob

   - string, funcref
   - string, list
   - string, dictionary
   - string, float
   - string, bool
   - string, none
   - string, job
   - string, blob

   - funcref, list
   - funcref, dictionary
   - funcref, float
   - funcref, bool
   - funcref, none
   - funcref, job
   - funcref, blob

   - list, dictionary
   - list, float
   - list, bool
   - list, none
   - list, job
   - list, blob

   - dictionary, float
   - dictionary, bool
   - dictionary, none
   - dictionary, job
   - dictionary, blob

   - float, bool
   - float, none
   - float, job
   - float, blob

   - bool, none
   - bool, job
   - bool, blob

   - none, job
   - none, blob

   - job, blob

*I've ignored the channel type, assuming it's handled like the job one.*

Third, the context: script level vs `:def` function.

That's 6 x 45 x 2 = 540 tests.

**Comment by brammool** [comment]
I don't think it is very important to have the same error message when compiling and when interpreting expressions.  The context is different, when compiling some types are known but not all (could be "any"), when interpreting the types are known.

Note that "+" can also be used with a list, thus getting 'float or number expected" would not be correct.

I'll see if the misleading error messages can be fixed.
