### ISSUE TITLE
Vim hangs for 60s before quitting file

### ISSUE THREAD

**Issue by joshpetit** [vim/vim#7168]
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Describe the bug**
When quitting files with `:q` vim hangs for 60s then displays the error:
```
Error on request (doAutocmd): equest doAutocmd [1] timedout after 60s
```
then quits the file.

**To Reproduce**
Attempt to quit a file

**Expected behavior**
Quit the file immediately

**Environment (please complete the following information):**
 - Vim 8.1
 - Ubuntu 20.04
 - Gnome Terminal

**Additional context**
It may very well be one of these plugins causing the error, but I'm having difficulty trying to narrow down which may be the cause (my largest intuition is vim-fugitive)
```.vimr
Plug 'dart-lang/dart-vim-plugin' " Dart support
Plug 'artur-shaik/vim-javacomplete2' "Better Java support
Plug 'pangloss/vim-javascript'    " JavaScript support
Plug 'leafgarland/typescript-vim' " TypeScript syntax
Plug 'sheerun/vim-polyglot' "Bunch of languages
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'tpope/vim-fugitive'
Plug 'prettier/vim-prettier', {
  \ 'do': 'npm install',
  \ 'for': ['javascript', 'typescript', 'css', 'less', 'scss', 'json', 'graphql', 'markdown', 'vue', 'yaml', 'html'] }
Plug 'preservim/nerdtree' |
            \ Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'airblade/vim-gitgutter'
```

**Comment by k-takata** [comment]
It looks that the error message comes from coc.nvim.
https://github.com/neoclide/coc.nvim/blob/e04caa308ed3e348c008c67a7153c77f864a7544/autoload/coc/client.vim#L141

**Comment by chrisbra** [comment]
I suppose this is a plugin error then. Closing.
