### ISSUE TITLE
Vim9: E1012 not raised at compile time

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7171]
**Describe the bug**

In Vim9 script, sometimes an `E1012` error is not raised at compile time.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            var d: dict<string> = #{ k: '' }
            d = #{ k1: true, k2: function('len') }
        enddef
        defcompile
    EOF
    )

No error is raised.

**Expected behavior**

`E1012` is raied:

    E1012: Type mismatch; expected dict<string> but got dict<any>

**Environment**

 - Vim version: 8.2 Included patches: 1-1862
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(360)

**Additional context**

The error is correctly raised at runtime:
```vim
vim9script
def Func()
    var d: dict<string> = #{ k: '' }
    d = #{ k1: true, k2: function('len') }
enddef
Func()
```
    E1012: Type mismatch; expected dict<string> but got dict<any>

---

If this is working as intended, then why is `E1012` correctly raised in the following snippet at compile time?
```vim
vim9script
def Func()
    var d: dict<string> = #{ k: '' }
    d = #{ k1: true, k2: 0z12 }
enddef
defcompile
```
    E1012: Type mismatch; expected dict<string> but got dict<any>

The only difference with the original snippet is the second key assigned to the dictionary.  It's a funcref in the original snippet, while it's a blob in the second one.

This is inconsistent.  Either `E1012` should not be raised at compile time for any snippet, or it should be raised for both.

**Comment by lacygoill** [comment]
> Vim version: 8.2 Included patches: 1-1862

There is a typo; I'm on 8.2.1864.

**Comment by brammool** [comment]
> **Describe the bug**
> 
> In Vim9 script, sometimes an `E1012` error is not raised at compile time.
> 
> **To Reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(cat <<'EOF'
>         vim9script
>         def Func()
>             var d: dict<string> = #{ k: '' }
>             d = #{ k1: true, k2: function('len') }
>         enddef
>         defcompile
>     EOF
>     )
> 
> No error is raised.
> 
> **Expected behavior**
> 
> `E1012` is raied:
> 
>     E1012: Type mismatch; expected dict<string> but got dict<any>

In this case the erorr is only detected at runtime.  It's going to be
quite difficult to detect this at compile time.

If you remove the second dict entry "k2: function('len')" then the error
is reported at compile time.

> **Environment**
> 
>  - Vim version: 8.2 Included patches: 1-1862
>  - OS: Ubuntu 16.04.7 LTS
>  - Terminal: xterm(360)
> 
> **Additional context**
> 
> The error is correctly raised at runtime:
> ```vim
> vim9script
> def Func()
>     var d: dict<string> = #{ k: '' }
>     d = #{ k1: true, k2: function('len') }
> enddef
> Func()
> ```
>     E1012: Type mismatch; expected dict<string> but got dict<any>
> 
> ---
> 
> If this is working as intended, then why is `E1012` correctly raised
> in the following snippet at compile time?
> ```vim
> vim9script
> def Func()
>     var d: dict<string> = #{ k: '' }
>     d = #{ k1: true, k2: 0z12 }
> enddef
> defcompile
> ```
>     E1012: Type mismatch; expected dict<string> but got dict<any>
> 
> The only difference with the original snippet is the second key
> assigned to the dictionary.  It's a funcref in the original snippet,
> while it's a blob in the second one.
> 
> This is inconsistent.  Either `E1012` should not be raised at compile
> time for any snippet, or it should be raised for both.

The "function()" call is not considered a constant.  Perhaps when
digging much deeper this can be made to work, but I don't see a good
reason to dig into that now.

-- 
Bare feet magnetize sharp metal objects so they point upward from the
floor -- especially in the dark.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> The "function()" call is not considered a constant.

I see, thank you for the explanation.  I found this while I was trying to understand why `E1036` was shadowing `E1012` in https://github.com/vim/vim/issues/7160:
```vim
vim9script
def Func()
    var menu_winid = popup_menu('', {})
    var opts = #{ key: '' }
    opts = popup_getoptions(menu_winid)
    eval opts.line - 1
enddef
Func()
```
But you're right; it's not that important.

---

Just for future reference, consider this code:
```vim
vim9script
def Func()
    var l: list<string>
    # ...
    # many lines of code
    # ...
    # FIRST ERROR
    l = ['', function('len')]
    # ...
    # many lines of code
    # ...
    # REPORTED ERROR
    eval l[0] - 1
enddef
Func()
```
It raises `E1036` from the last line of the function:

    E1036: - requires number or float arguments

However, the first error comes from a distant line:

    l = ['', function('len')]

It might make the debugging easier if the user is presented with the first error instead of the second one.
