### ISSUE TITLE
Event InsertLeavePre, FocusLostPre is needed.

### ISSUE THREAD

**Issue by seaspeak** [vim/vim#7177]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
Sometimes we need to save the state of the Insert Mode before leaving it, for example the keyboard layout. Now we have `InsertLeave` and `FocusLost`, but once we leave the insert mode, the keyboard layout has already been changed. Currently  no way to save this kind of information.

**Describe the solution you'd like**
Support Event `InsertLeavePre` and `FocusLostPre` which means before leaving insert mode. The event names are in line with the others, `BufReadPre`, `FileReadPre`, `FilterReadPre`, etc.

Note `FocusLost` is also a must. Some input methods have one global state, so losing the focus (switching to other app) will also change the input method state, so the state also needs to be saved before losing focus.

**Describe alternatives you've considered**
No other way to achieve this purpose.

**Additional context**

**Comment by brammool** [comment]
Not sure why you closed this.  Adding InsertLeavePre is quite simple and it might be useful.
