### ISSUE TITLE
`<C-\><C-O>:stopinsert<CR>` called from a silent Insert mapping doesn't clear '-- INSERT --' from the last line

### ISSUE THREAD

**Issue by Coacher** [vim/vim#718]
Hello.

Steps to reproduce:
0. Enable 'showcmd';
1. Enter Insert mode;
2. `<C-\><C-O>:stopinsert<CR>`;
3. You are now back in Normal mode. The last screen line says: ':stopinsert';
4. `:imap <silent> <F1> <C-\><C-O>:stopinsert<CR>`;
5. Enter Insert mode again;
6. Hit `<F1>`;
7. You are now back in Normal mode. The last screen line says: '-- INSERT --'.

On the last step '-- INSERT --' shouldn't be there as we are now in Normal mode. Please fix.

**Comment by chdiza** [comment]
I can reproduce this with 7.4.1683, starting with `vim -u NONE -N`

**Comment by chrisbra** [comment]
is there a reason, to use `<c-\><c-o>:stopinsert` rather than just `<esc>` It doesn't seem to make sense, to use `<c-\><c-o>` which is there to **temporarily** switch to normal mode, when you actually want to end insert mode.

**Comment by Coacher** [comment]
Yes. This way my cursor isn't moved. `<Esc>` moves my cursor.

**Comment by chrisbra** [comment]
Yeah, I almost expected that reason. However this is traditional vi behaviour and I don't think this is likely to get changed soon. However you could as a workaround do:

```
:imap <silent> <F1> <C-\><C-O>ma<esc>`a
:set virtualedit=onemore
```

**Comment by Coacher** [comment]
Thanks, but I've seen this `<Esc>`a` workaround before and to me it looks ugly with that mark fiddling.
I much prefer the `:stopinsert` way.
Regardless of use cases `:h vim-modes` says:

```
In Insert mode [...] "-- INSERT --" is shown at the bottom of the window.
```

Since `:stopinsert` leaves Insert mode '-- INSERT --' shouldn't be there IMHO. Clearly a bug.

**Comment by chrisbra** [comment]
okay, i think, this patch fixes it:

``` patch
diff --git a/src/ex_docmd.c b/src/ex_docmd.c
index 26f4219..4b1748e 100644
--- a/src/ex_docmd.c
+++ b/src/ex_docmd.c
@@ -10040,6 +10040,7 @@ ex_stopinsert(exarg_T *eap UNUSED)
 {
     restart_edit = 0;
     stop_insert_mode = TRUE;
+    do_unshowmode();
 }

 /*
diff --git a/src/proto/screen.pro b/src/proto/screen.pro
index aad8187..a28c3da 100644
--- a/src/proto/screen.pro
+++ b/src/proto/screen.pro
@@ -47,6 +47,7 @@ int screen_ins_lines(int off, int row, int line_count, int end, win_T *wp);
 int screen_del_lines(int off, int row, int line_count, int end, int force, win_T *wp);
 int showmode(void);
 void unshowmode(int force);
+void do_unshowmode(void);
 void get_trans_bufname(buf_T *buf);
 int redrawing(void);
 int messaging(void);
diff --git a/src/screen.c b/src/screen.c
index 9d854a2..e44c396 100644
--- a/src/screen.c
+++ b/src/screen.c
@@ -10184,12 +10184,16 @@ unshowmode(int force)
     if (!redrawing() || (!force && char_avail() && !KeyTyped))
        redraw_cmdline = TRUE;          /* delete mode later */
     else
-    {
-       msg_pos_mode();
-       if (Recording)
-           recording_mode(hl_attr(HLF_CM));
-       msg_clr_eos();
-    }
+       do_unshowmode();
+}
+
+    void
+do_unshowmode(void)
+{
+    msg_pos_mode();
+    if (Recording)
+       recording_mode(hl_attr(HLF_CM));
+    msg_clr_eos();
 }

     static void
```

**Comment by brammool** [comment]
Christian Brabandt wrote:

> okay, i think, this patch fixes it:

Thanks!

## 

hundred-and-one symptoms of being an internet addict:
196. Your computer costs more than your car.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Coacher** [comment]
Just tested on vim-7.4.1699 and I can confirm the problem is fixed.

Thank you very much!
