### ISSUE TITLE
Inconsistent highlighting of CursorLine in cterm

### ISSUE THREAD

**Issue by venthur** [vim/vim#7185]
**Describe the bug**

Currently the **default** CursorLine highlighting is defined like this:

    CENT("CursorLine term=underline cterm=underline",
        "CursorLine term=underline cterm=underline guibg=Grey40"),

i.e. in `term` and `cterm` it is underlined and with `gui` it gets a nice background instead. I believe when a `cterm` is available, it should have a colored background as well and should not be underlined anymore.

Note how the very similar CursorColum handles `term` vs `cterm` better: `term` gets some attribute, but `cterm` and `gui` get the respective bg-coloring: 

     CENT("CursorColumn term=reverse ctermbg=DarkGrey",
         "CursorColumn term=reverse ctermbg=DarkGrey guibg=Grey40"),

I propose that CursorLine gets the same `ctermbg` as as the CursorColumn and the underline removed. Analogously, I'd propose a similar treatment for CursorLineNr: underline removed from `cterm`.

I am aware that this might be a very subjective issue, but in this case I believe the proposed change is more consistent (and looks better)

**Environment (please complete the following information):**
 - Vim version 8.2
 - OS: Debian/Sid
 - Terminal: GNOME Terminal

**Comment by brammool** [comment]
Changing the default is likely to cause more Irritation than please users.  The underline combines well with other highlighting that uses a background.  When picking a background color there is a bigger chance of it not fitting in with the color scheme the user is using.  If the user cares, the color would already have been changed.

**Comment by venthur** [comment]
Hi Bram,

thanks for the reply! My arguments in favor would be:
 
* In this case, shouldn't we be only concerned that the default colorscheme is consistent? As in: not worry so much about other colorschemes? If we change something in the default scheme and it breaks another colorscheme, doesn't that mean that they  forgot to set a highlighting?
* I had a quick check over the default colorscheme and the only thing that **might** conflict with the proposed patch is `Conceal`, but I'm not sure actually how it interacts with the ColorLine.

Apart from that, I've been using `termguicolors` for quite a few months, together with the default colorscheme -- that effectively brings in the change I request (minus the removal of the underline) and I haven't noticed any weird things inside the default colorscheme.

**Comment by chrisbra** [comment]
Let's keep the defaults as is. You can still configure otherwise via a custom colorscheme. But I am not going to adjust the defaults, unless the changes bring clear advantags or fix clear bugs.
