### ISSUE TITLE
modifyOtherKeys mode treats shift-tab as `<95>`

### ISSUE THREAD

**Issue by gnachman** [vim/vim#7189]
**Describe the bug**
Using xterm or the iTerm2 3.4.0beta11 (which supports `modifyOtherKeys` when properly configured), pressing shift-tab in insert mode inserts `<95>`.  It does not respect keys bound to `<S-TAB>`.

**To Reproduce**
1. Run `vim --clean`
2. `inoremap <S-TAB> hello`
3. Enter insert mode by pressing `i`
4. Press shift-tab
5. Observe that `<95>` is inserted.

**Expected behavior**
`hello` should be inserted

**Environment (please complete the following information):**
 - Vim version
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul  5 2020 01:22:14)
macOS version
Included patches: 1-503, 505-680, 682-2292
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_any_white
-arabic            +file_in_path      -mouse_urxvt       -tcl
+autocmd           +find_in_path      +mouse_xterm       -termguicolors
+autochdir         +float             +multi_byte        +terminal
-autoservername    +folding           +multi_lang        +terminfo
-balloon_eval      -footer            -mzscheme          +termresponse
-balloon_eval_term +fork()            +netbeans_intg     +textobjects
-browse            -gettext           +num64             +textprop
+builtin_terms     -hangul_input      +packages          +timers
+byte_offset       +iconv             +path_extra        +title
+channel           +insert_expand     -perl              -toolbar
+cindent           +job               +persistent_undo   +user_commands
-clientserver      +jumplist          +postscript        -vartabs
+clipboard         -keymap            +printer           +vertsplit
+cmdline_compl     +lambda            -profile           +virtualedit
+cmdline_hist      -langmap           +python/dyn        +visual
+cmdline_info      +libcall           -python3           +visualextra
+comments          +linebreak         +quickfix          +viminfo
-conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          -rightleft         +wildignore
+cscope            +localmap          +ruby/dyn          +wildmenu
+cursorbind        -lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con        +mksession         +smartindent       -X11
+diff              +modify_fname      -sound             -xfontset
+digraphs          +mouse             +spell             -xim
-dnd               -mouseshape        +startuptime       -xpm
-ebcdic            -mouse_dec         +statusline        -xsmp
-emacs_tags        -mouse_gpm         -sun_workshop      -xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          -mouse_netterm     +tag_binary
+extra_search      +mouse_sgr         -tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L/usr/local/lib -o vim        -lm -lncurses  -liconv -framework Cocoa
```

 - OS:
macOS 10.15

 - Terminal:
xterm 326

**Additional context**
iTerm2 is adding support for `modifyOtherKeys` and a user brought this to my attention in this issue: https://gitlab.com/gnachman/iterm2/-/issues/9202

**Comment by lacygoill** [comment]
I don't know about iTerm2, but I can't reproduce the issue on xterm 361.

![gif](https://user-images.githubusercontent.com/8505073/96990912-044d9300-1528-11eb-8562-58eca24ed043.gif)

I also made some test after commenting out my whole `~/.Xresources`; same result.

Can you reproduce on master and maybe with a more recent xterm too?

**Comment by brammool** [comment]
I also can't reproduce the problem on a recent xterm.

**Comment by gnachman** [comment]
Not sure why our xterms are different, but my guess is that there's some environment variable causing trouble. I have `LANG=en_US-UTF-8`.

I stepped through the code and `simplify_key()` returns `K_S_TAB` (this looks right!), which on my system equals `0xffffbd95`. Then `modifiers2keycode` passes this to `utf_char2bytes` by calling the function pointer `mb_char2bytes`. Because it is less than 0x80, the first if statement in `utf_char2bytes` truncates `0xffffbd95` down to the last byte, `0x95`. That makes it the rest of the way through the input code and appears in my buffer.

Either `handle_key_with_modifier` has a bug in handling negative values placed in `key` from `modifiers2keycode`, or else `K_S_TAB` should have been nonnegative (which makes me wonder what sequence of code points could reasonably be assigned to shift-tab?).

`K_S_TAB` is defined in `keymap.h`:
```
#define K_S_TAB		TERMCAP2KEY('k', 'B')
```
And `TERMCAP2KEY` is definitely supposed to produce negative values:
```
#define TERMCAP2KEY(a, b)	(-((a) + ((int)(b) << 8)))
```
At this point I am stuck.

**Comment by gnachman** [comment]
^ this was done on master and with xterm-361 which is the most recent version I can find.

**Comment by brammool** [comment]
I think you looked at the wrong code, or something weird is happening.  do this;
call ch_logfile('logflie', 'w')
Then type some keys including shift-Tab, remember in what sequence.
Now you can check 'logfile' for what raw key codes Vim received.
For Shift-Tab is ESC[Z.  Looks like modifyOtherKeys isn't used for this.

**Comment by gnachman** [comment]
> I think you looked at the wrong code, or something weird is happening.

I am at commit 5661ed6c833e05467cab33cb9b1c535e7e5cc570 of https://github.com/vim/vim 

> For Shift-Tab is ESC[Z.

Shift-Tab is `ESC [ Z` in modifyOtherKeys=1 mode but not in modifyOtherKeys=2 mode (again, using xcode 361 built with default settings and run with no command line args). The log file shows:
```
  1.459511 : raw key input: "^[[27;2;9~"
```

I can see that vim sends `ESC [ > 4 ; 2 m` at startup. I ran vim within `script` and this is the start of the log:

```
$ ./vim --clean^M^M
^[[?1000h^[[?1049h^[[>4;2m
```

From xterm, pressing shift-tab after cat:
```
$ printf "\e[>4;1m"
$ cat
^[[Z

^C
$ printf "\e[>4;2m"
$ cat
^[[27;2;9~
```

**Comment by brammool** [comment]
George Nachman wrote:

> Shift-Tab is `ESC [ Z` in modifyOtherKeys=1 mode but not in
> modifyOtherKeys=2 mode (again, using xcode 361 built with default
> settings and run with no command line args). The log file shows:
> ```
>   1.459511 : raw key input: "^[[27;2;9~"
> ```
> 
> I can see that vim sends `ESC [ > 4 ; 2 m` at startup. I ran vim within `script` and this is the start of the log:
> 
> ```
> $ ./vim --clean^M^M
> ^[[?1000h^[[?1049h^[[>4;2m
> ```
> 
> >From xterm, pressing shift-tab after cat:
> ```
> $ printf "\e[>4;1m"
> $ cat
> ^[[Z
> 
> ^C
> $ printf "\e[>4;2m"
> $ cat
> ^[[27;2;9~
> ```

For me both result in the same thing.  It's possible that xterm has
changed this at some point.  You mention using version 326, I'm on 356.
Try getting a newer version.  Version 326 is four years old.

-- 
Statistics say that you can have a baby per month on average:
Just get nine women pregnant.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> From xterm, pressing shift-tab after cat:
>
>     $ printf "\e[>4;1m"
>     $ cat
>     ^[[Z
>
>     ^C
>     $ printf "\e[>4;2m"
>     $ cat
>     ^[[27;2;9~

I'm using xterm 361, and I get the same escape sequence whether modifyOtherKeys is set to 1 or 2:

    $ printf "\e[>4;1m"
    $ cat
    ^[[Z

    ^C
    $ printf "\e[>4;2m"
    $ cat
    ^[[Z

To be sure that no custom configuration was interfering, I've performed the tests after commenting out the whole `~/.Xresources`, and I've started xterm from the application launcher (Whisker Menu), with a bash shell and no shell config:

    xterm -e bash --norc --noprofile

When I compile xterm, I just run:

    ./configure
    make
    sudo make install

I guess some other parameter must influence the results, but I don't see which one...

**Comment by gnachman** [comment]
It looks like xterm's behavior varies between platforms. On Ubuntu 20, it gets a keysym of XK_ISO_Left_Tab and sends `ESC[Z` while on macOS it gets XK_Tab and sends the CSI ~-style code.

I'll check with Thomas Dickey about whether this behavior is intentional.

It would be nice for vim to recognize both since this behavior will be in the field for some time to come. The spec for modifyOtherKeys is not particularly helpful in telling which behavior is correct.

**Comment by gnachman** [comment]
BTW, this is on xterm 361

**Comment by Shane-XB-Qian** [comment]
i tried xterm 330, both is `^[[Z`

**Comment by Shane-XB-Qian** [comment]
`#define XK_Tab                           0xff09`
`#define XK_ISO_Left_Tab                  0xfe20`
that's 2 different keysym, looks you can chg the keysym of 'shift for tab' anyway .. as my understanding, looks it is ..

**Comment by gnachman** [comment]
Based on a conversation with Thomas Dickey, he advises that users fix their X configs to send XK_ISO_Left_Tab on macOS instead of XK_Tab. Since I don't see xterm changing any time soon, I'll modify iTerm2 to send CSI Z for shift-tab. I suppose xterm users on macOS would appreciate if vim handled the `ESC [ 27 ; 2 ; 9 ~` code the same as `ESC [ Z`, though.

**Comment by ThomasDickey** [comment]
something like that.  I don't see it as likely that XQuartz (or current macPorts xorg-server) will have something like the xkb utilities on other systems since macOS locale support is not as extensive.

xterm's handling of `XK_ISO_Left_Tab` is a very old workaround - balancing that against the `modifyOtherKeys` feature is problematic, since some users may prefer the _ESC [ 27 ; 2 ; 9 ~_
(the manual page implies that this is the preferred behavior, and that _ESC [ Z_ is incorrect).

That is a special case (testing modifiers with the tab character isn't straightforward since window managers tend to own most of the combinations.

The [table](https://invisible-island.net/xterm/modified-keys-us-pc105.html#detailed:XK_ISO_Left_Tab.54d) (and generating script) which I created last year doesn't  give enough insight for this special case.

**Comment by brammool** [comment]
Thomas Dickey wrote:

> something like that.  I don't see it as likely that XQuartz (or
> current macPorts xorg-server) will have something like the xkb
> utilities on other systems since macOS locale support is not as
> extensive.
> 
> xterm's handling of `XK_ISO_Left_Tab` is a very old workaround -
> balancing that against the `modifyOtherKeys` feature is problematic,
> since some users may prefer the _ESC [ 27 ; 2 ; 9 ~_
> (the manual page implies that this is the preferred behavior, and that
> _ESC [ Z_ is incorrect).
> 
> That is a special case (testing modifiers with the tab character isn't
> straightforward since window managers tend to own most of the
> combinations.
> 
> The
> [table](https://invisible-island.net/xterm/modified-keys-us-pc105.html#detailed:XK_ISO_Left_Tab.54d)
> (and generating script) which I created last year doesn't  give enough
> insight for this special case.

I found a bug in the code that handles modifyOtherKeys.  If the result
is a special key it's put in the typeahead buffer as a multi-byte
character instead of as a key code.  Once I fix that both codes for
Shift-Tab should work.

-- 
If you feel lonely, try schizophrenia.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
