### ISSUE TITLE
syntax/tex.vim matches against tex_conceal using '!~' instead of '!~#'

### ISSUE THREAD

**Issue by Coacher** [vim/vim#719]
Hello.

This is a followup of https://github.com/vim/vim/issues/646

Thanks again for fixing the initial problem with '=~' vs '=~#'.
I've noticed that tex.vim uses '!~', which has the same problems as '=~':
if 'ignorecase' is enabled, then matches become case-insensitive.
This already makes 's' and 'S' flags undistinguishable in tex_conceal.

Please fix.

**Comment by Coacher** [comment]
I've tried to contact the maintainer via the email in syntax file, but that address seem to be invalid.
This what I got:
Delivery to the following recipient failed permanently:

```
 NdrchipO@scampbellpfamily.abizm
```

Technical details of permanent failure: 
DNS Error: 683494 DNS type 'mx' lookup of scampbellpfamily.abizm responded with code NXDOMAIN
Domain name not found: scampbellpfamily.abizm

**Comment by vim-ml** [comment]
Hi Coacher,

2016-3-29(Tue) 16:50:04 UTC+9 Coacher:

> I've tried to contact the maintainer via the email in syntax file, but that address seem to be invalid.
> 
> This what I got:
> 
> Delivery to the following recipient failed permanently:
> 
>  NdrchipO@scampbellpfamily.abizm
> 
> Technical details of permanent failure: 
> 
> DNS Error: 683494 DNS type 'mx' lookup of scampbellpfamily.abizm responded with code NXDOMAIN
> 
> Domain name not found: scampbellpfamily.abizm

Please run the following command in Vim.
:echo substitute("NdrOchipS@PcampbellAfamily.Mbiz", "[NOSPAM]", "", "g")

## 

Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by Coacher** [comment]
I see. Thanks for the tip. I've sent an email again, but with the correct address now.

**Comment by cecamp** [comment]
Its always a good idea to check my website, which is mentioned 3 lines under the maintainer line as URL: http://www.drchip.org/astronaut/vim/index.html#SYNTAX_TEX.  Especially since this problem happens to have already been addressed.

**Comment by Coacher** [comment]
Thank you very much!
