### ISSUE TITLE
Build error: undefined reference to `ins_compl_update_sequence_numbers'

### ISSUE THREAD

**Issue by phmccarty** [vim/vim#7206]
**Describe the bug**
Attempting to build vim at revision caf73dcfade0a435ea3f989285b43f07c40c9948 (patch 8.2.1910), I see the following compiler warning, followed by a linker error:

```
insexpand.c: In function ‘ins_complete’:
insexpand.c:4072:3: warning: implicit declaration of function ‘ins_compl_update_sequence_numbers’ [-Wimplicit-function-declaration]
 4072 |   ins_compl_update_sequence_numbers();
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
```
/usr/bin/ld: objects/insexpand.o: in function `ins_complete':
/builddir/build/BUILD/vim-8.2.1910/src/insexpand.c:4072: undefined reference to `ins_compl_update_sequence_numbers'
collect2: error: ld returned 1 exit status
```

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Build with `./configure --with-features=tiny && make`

**Environment (please complete the following information):**
 - OS: Clear Linux OS, release 33890

**Comment by brammool** [comment]
Fixed with 8.2.1911
