### ISSUE TITLE
New emoji option breaks rendering of colorcolumn

### ISSUE THREAD

**Issue by beaugunderson** [vim/vim#721]
With `set emoji`:

![emoji](https://i.imgur.com/vXJim5s.png)

With `set noemoji`:

![noemoji](https://i.imgur.com/iwHI0mr.png)

This is in latest iTerm 2 (2.9.20160206) on El Capitan.

**Comment by mattn** [comment]
I don't see the behavior.

http://go-gyazo.appspot.com/8ff36abf2e08281f.png

did you set following?

![](https://qiita-image-store.s3.amazonaws.com/0/17722/66b79d3f-0d14-6cc0-2f5a-5b8260d10a93.png)

**Comment by beaugunderson** [comment]
Turning that on breaks airline regardless of whether `emoji` is set but does _almost_ fix things.

With "ambiguous as double width" and `emoji`:

![emoji](https://i.imgur.com/ieYPrvz.png)

With "ambiguous as double width" and `noemoji`:

![noemoji](https://i.imgur.com/BXNRfBn.png)

**Comment by mattn** [comment]
Could you please show me the file?

**Comment by beaugunderson** [comment]
yes; here's the [raw file](https://gist.githubusercontent.com/beaugunderson/fb5f0ee3ecdc1a1257e3bd08588bc411/raw/e661e7400dc481dd3426bd30e543a5c9ce99c0df/git%2520commit%2520template) :)

**Comment by mattn** [comment]
Thanks. `✅` should be double width. but it've changed to narrow.

https://groups.google.com/forum/#!searchin/vim_dev/emoji%7Csort:date/vim_dev/0y1ThP9Gj1Y/zsh6_LQfGwAJ

**Comment by beaugunderson** [comment]
Note the unicode arrow character at the bottom that has an incorrect width as well

**Comment by mattn** [comment]
what value of unicode code point?  `→` (\u2192)?

**Comment by mattn** [comment]
and do you set `ambiwidth=double`? or `single`?

**Comment by beaugunderson** [comment]
Yes, it's `\u2192`; my `ambiwidth` is set to `single` (it can't be set to `double` with that character in `listchars` apparently)

**Comment by vim-ml** [comment]
2016-03-30 5:12 GMT+03:00 mattn vim-dev-github@256bit.org:

> I don't see the behavior.
> 
> http://go-gyazo.appspot.com/8ff36abf2e08281f.png
> 
> did you set following?
> 
> https://camo.githubusercontent.com/74220b96c2175701bd4d6b2485fa7b18dc963796/68747470733a2f2f71696974612d696d6167652d73746f72652e73332e616d617a6f6e6177732e636f6d2f302f31373732322f36366237396433662d306431342d366363302d326635612d3562383236306431306139332e706e67
> 
> Making ambiguous characters have double width is one of the worst ideas:
> there are _way_ too much characters which have “A” East Asian Width
> property, but are single width in nearly all fonts I have, including
> powerline arrows (i.e. the whole Private Use Area, specifically for
> powerline arrows you may read _all_ fonts), some national alphabets like
> Russian and Greek and many other symbols like the one OP used in &listchars.

@Beau Gunderson &ambiwidth setting must be synchronized with the terminal
setting or you will get lots of rendering problems like wrapped statusline.
It is especially needed for statusline as it is output “in one piece” (so
rendering problem cannot be mitigated by telling terminal the explicit
position of some character) and contains “filler” elements whose width
depends on how many space is left in the line (so Vim will add more spaces
then actually needed).

**Comment by chrisbra** [comment]
I suppose, this can be closed then?

**Comment by beaugunderson** [comment]
my ambiwidth and my terminal are both set to single for ambiguous characters and I still see the issue with emoji and some Unicode characters. (mattn had asked me to try the ambiguous setting in iTerm, that's what the second set of screenshots are)

under all permutations of settings there are still rendering issues.

---

**Comment by mattn** [comment]
okay, then please `set noemoji`.

**Comment by brammool** [comment]
Beau Gunderson wrote:

> my ambiwidth and my terminal are both set to single for ambiguous
> characters and I still see the issue with emoji and some Unicode
> characters. (mattn had asked me to try the ambiguous setting in iTerm,
> that's what the second set of screenshots are)
> 
> under all permutations of settings there are still rendering issues.

Yeah, this is very hard to get right.  Blaming the user for not setting
the right options isn't a good solution.

I think what we need to do is to assume that some characters may have a
different width from what we expect.  To minimize drawing issues, the
cursor needs to be positioned after drawing such a character.

I'm thinking of setting screen_cur_col to a large value after drawing
such an ambiguous width character.  That is in screen_char().
And avoid using PLAN_WRITE in windgoto() if there are ambiguous width
characters to be writen.

There might still be some remaining problems, such as Visual block
selection.

## 

hundred-and-one symptoms of being an internet addict:
199. You read this entire list of symptoms, looking for something
     that doesn't describe you.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
can you check, if [1697](https://github.com/vim/vim/releases/tag/v7.4.1697) fixes your problem?

**Comment by mattn** [comment]
ping @beaugunderson

**Comment by k-takata** [comment]
Maybe, already fixed. Closing.
