### ISSUE TITLE
Arrow keys in insert mode cancel insert multiplicity

### ISSUE THREAD

**Issue by umanwizard** [vim/vim#7211]
**Describe the bug**
Example of multiple insert:

From normal mode, type "5i", then enter "asdf<ESC>". Buffer after this operation:

asdfasdfasdfasdfasdf

However, if an arrow key is entered in insert mode, the effect is canceled, and only one copy of "asdf" appears. 

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean`
2. Type "5iasdf&lt;left arrow>&lt;ESC>"
3. Notice that your buffer only contains "asdf".

**Expected behavior**
The buffer should contain "asdfasdfasdfasdfasdf".

**Environment (please complete the following information):**
 - Vim version: 
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 15 2020 06:40:31)
Included patches: 1-2269
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
```
 - OS: Ubuntu 20.04
 - Terminal: Default Ubuntu version of GNOME terminal

**Comment by tonymec** [comment]
«When using CTRL-O in Insert mode |i_CTRL-O| the count is not supported.»

Ctrl-O in Insert mode temporarily switches to Normal mode.  IIUC, so does the use of arrow keys. I believe that what we see here is a documentation bug, not a bug in Vim's behaviour.

Best regards,
Tony.

**Comment by umanwizard** [comment]
In nvi for example, after an arrow key is pressed, the inserted text is expanded `[count]` times (and, after that, further insertion behaves as normal with count 1).

Whereas in vim, as soon as an arrow key is used, the count is silently discarded.

I think the nvi behavior is much closer to the spirit of "arrow key temporarily activates normal mode", since it is the same behavior as <ESC>, then h/j/k/l, then back to insert.

**Comment by umanwizard** [comment]
There is also weird behavior when backspacing past the insert point (something that of course isn't possible in nvi):

buffer: 123456789
Cursor: on "5".
Input: 2i<BACKSPACE><BACKSPACE>a
Result: 1a56789

I can't find any possible logic to explain this.

**Comment by brammool** [comment]
I'm not sure what is the best behavior.  In cases like this it's better to just leave it, since users depend on the current behavior.  There are other ways to insert something multiple times.
