### ISSUE TITLE
`autoindent` with `filetype=html` over-indents <script>

### ISSUE THREAD

**Issue by bikubi** [vim/vim#7215]
**Describe the bug**

With `autoindent`, a `<script>` tag gets indented by two extra tabs/units.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean`
2. `:set filetype=html`, `:set autoindent`
3. Insert mode, type `<html>↵<script>` with `↵`=Enter/Return
4. First the `<script>` tag is indented properly, but as soon as I type its closing `>`, two extra tabs/units appear in front of it.

**Expected behavior**

The extra indentation should not appear.

**Environment (please complete the following information):**
 - VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 17 2020 21:54:53)  
  Included patches: 1-1704  
  Compiled by Arch Linux  
 - Arch Linux, up to date
 - Terminal: konsole (KDE terminal)

**Additional context**

* The extra tabs disappear when I type a closing `</script>` on the same line
* also after `<esc>==`
* Problem doesn't appear when there is any attribute, e.g. `<script foo>`
* Problem doesn't appear when there is no whitespace in front of the `<script>`

Thinking this is an user error I [discussed it on vi.sx](https://vi.stackexchange.com/questions/27810/filetype-plugin-indent-on-with-filetype-html-over-indents-script), two commenters there suggest it's a bug, [one](https://vi.stackexchange.com/questions/27810/filetype-plugin-indent-on-with-filetype-html-over-indents-script#comment50401_27810) suggests [it happened in 7ff78465f](https://github.com/vim/vim/commit/7ff78465f#diff-4fbf4cd2ef9bb7a186b50c1817c90033ef0d2e198378152ece90d04dc87bf2e6R589)

**Comment by rogerhub** [comment]
I observed the same problem, and indeed reverting 7ff78465f7057a672a6de0d75d56286da253501b seems to fix it.

**Comment by brammool** [comment]
Revering that change causes other problems.  It appears that shiftwidth is added twice in some situation.
I made a change that appears to fix it.  Will be in the next runtime file update.
I wouldn't mind if someone takes over this indent script, it's quite complicated.
