### ISSUE TITLE
vim9: ex command :filter not working in vim9script

### ISSUE THREAD

**Issue by alexaschee** [vim/vim#7216]
**Describe the bug**

    vim9script
    # :brow old
    :filter /anything/ brow old

This gives
    
    E476: Invalid command: :filter /anything/ brow old

since `brow old` works, it must be `filter`'s fault.

**Environment (please complete the following information):**
 - Vim version [e.g. 8.2.1900]
 - OS: Windows 10

**Comment by lacygoill** [comment]
This is probably a regression introduced in [8.2.1178](https://github.com/vim/vim/releases/tag/v8.2.1178).
