### ISSUE TITLE
Vim documentation on EPUB format.

### ISSUE THREAD

**Issue by apgrc** [vim/vim#7217]
Currently, vim's documentation as available through `:help` and in [html](http://vimdoc.sourceforge.net/htmldoc/) format, but there is no mobile friendly way to read the documentation.

It would be nice to be able to read the documentation on EPUB format from my smartphone for those times were I don't feel to use a computer any more.

A mobile friendly html documentation would be nice as an alternative.

**Comment by chrisbra** [comment]
can epub be automatically be converted from the existing documentation? I think this might be more relevant for https://github.com/c4rlo/vimhelp

**Comment by chrisbra** [comment]
I am closing this. The documentation is available in text format. Could be a nice side project to create an epub version, but this is out of scope for the Vim project. Feel free to contribute.
