### ISSUE TITLE
Tests wait for user input if $HOME isn't writable

### ISSUE THREAD

**Issue by jamessan** [vim/vim#722]
Currently, test_backspace_opt.vim and test_viminfo.vim hit E138 if $HOME isn't writable and wait for the user to press enter.  I noticed this since Debian's builds run with $HOME set to a non-existent directory to ensure the build/test process doesn't rely on modifying the user's environment.

A simple way to reproduce is to run the tests like `env HOME=/nonexistent/dir make test`.

**Comment by vim-ml** [comment]
Hi James,

2016-3-30(Wed) 11:53:13 UTC+9 James McCoy:

> Currently, test_backspace_opt.vim and test_viminfo.vim hit E138 if $HOME isn't writable and wait for the user to press enter.  I noticed this since Debian's builds run with $HOME set to a non-existent directory to ensure the build/test process doesn't rely on modifying the user's environment.
> 
> A simple way to reproduce is to run the tests like env HOME=/nonexistent/dir make test.

Reported issue is fixed by attached patch.
Please confirm this.

## Thanks.

Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by vim-ml** [comment]
On Tue, Mar 29, 2016 at 09:44:51PM -0700, h_east wrote:

> Hi James,
> 
> 2016-3-30(Wed) 11:53:13 UTC+9 James McCoy:
> 
> > Currently, test_backspace_opt.vim and test_viminfo.vim hit E138 if $HOME isn't writable and wait for the user to press enter.  I noticed this since Debian's builds run with $HOME set to a non-existent directory to ensure the build/test process doesn't rely on modifying the user's environment.
> > 
> > A simple way to reproduce is to run the tests like env HOME=/nonexistent/dir make test.
> 
> Reported issue is fixed by attached patch.
> Please confirm this.

That does fix it.

## Thanks!

James
GPG Key: 4096R/331BA3DB 2011-12-05 James McCoy jamessan@jamessan.com

**Comment by brammool** [comment]
James McCoy wrote:

> Currently, test_backspace_opt.vim and test_viminfo.vim hit E138 if
> $HOME isn't writable and wait for the user to press enter.  I noticed
> this since Debian's builds run with $HOME set to a non-existent
> directory to ensure the build/test process doesn't rely on modifying
> the user's environment.

Good catch.  I was wondering why my viminfo got screwed up when running
tests.

> A simple way to reproduce is to run the tests like `env
> HOME=/nonexistent/dir make test`.

Perhaps we should have the test script do that always.
Yes, that seems to work.

## 

Keep America beautiful.  Swallow your beer cans.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
Hi Bram!

On Mi, 30 Mär 2016, Bram Moolenaar wrote:

> > A simple way to reproduce is to run the tests like `env
> > HOME=/nonexistent/dir make test`.
> 
> Perhaps we should have the test script do that always.
> Yes, that seems to work.

I have been thinking, that at least for the new style tests, we have 
some global SetUp() function, that resets options to sane values (Vim 
defaults perhaps), before running the next test (file).

This should also protect from settings options leaking into the next 
test file.

Best,

## Christian

Jeder kann wütend werden, das ist einfach. Aber wütend auf den
Richtigen zu sein, im richtigen Maß, zur richtigen Zeit, zum richtigen
Zweck und auf die richtige Art, das ist schwer.
        -- Aristoteles, 384-322 v. Chr.
