### ISSUE TITLE
F15 is <help> ?

### ISSUE THREAD

**Issue by Shane-XB-Qian** [vim/vim#7223]
**Describe the bug**
1, not sure it was a bug or vim intended, i found `<s-f3>` did not equal to `<f15>`
2, but found `<f15>` equal to `<help>`, not sure if it was intended and compatible over window/mac/linux and over terminals ?

**To Reproduce**
Detailed steps to reproduce the behavior:
1. change one of your keyboard key to f15, e.g caps keycode 66 to f15
2. then 'vim -u NONE -N'
3. then press caps, you will see 'help'

**Expected behavior**
supposed `<s-f3>` should equal to `<f15>`, 
or if it intended to make it be compatible over platforms and terminals -to be fixed equal to `<help>` then ok too...

**Screenshots**
n/a

**Environment (please complete the following information):**
 - VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 29 2020 13:19:23) Included patches: 1-1920
 - OS: Ubuntu 18.04
 - Terminal: xfce-terminal

**Additional context**
n/a

**Comment by brammool** [comment]
Use ":set termcap" to see the terminal key configuration.
Normally F15 is not defined, thus you may have to add something for that.

**Comment by Shane-XB-Qian** [comment]
not sure ':set termcap' was my needed, but anyway looks that vim chg the keysym of `<help>` somewhere ..

`#define XK_Help                          0xff6a  /* Help */`
`#define XK_F15                           0xffcc`
`#define XK_L5                            0xffcc`

-vs- in vim:

`<SF3>		<S-F3>		0x94	148     0xc4	196`
`<HELP>		<Help>		0x9c	156     0xcc	204`

`t_help` renamed to `t_%1`:
`t_help	t_%1	<Help>		help key			*t_help*`

looks no `0x6a`, but was `0xcc` in vim, so it is `<f15>`, not sure why (why `<f15>`) or whatever, wish it is common over platforms/terminals.
// and looks `<s-f3>` was not equalled to `<f15>`.
// here `<help>` just is an example.

**Comment by Shane-XB-Qian** [comment]
@brammool since now vim chosed `<help>` fixed to `<f15>` -vs- `help` key itself, then wish this deal would keep for good for ever and cross over platforms/terminals, otherwise that would be compatible issue later/ in the future..
