### ISSUE TITLE
Specifying line number in file path

### ISSUE THREAD

**Issue by arbitrary-dev** [vim/vim#7224]
**Please describe the problem.**
It is difficult to open files on a specific line when you already have the following format reported by many apps:
```
deep/dark/fantasies/Dungeon.txt:69
```

**Describe the solution you'd like**
I'd like to open files on a correct line as simple as:
```
$ vim deep/dark/fantasies/Dungeon.txt:69

…or

:e deep/dark/fantasies/Dungeon.txt:69
```

**Describe alternatives you've considered**
Now I need to manually split the line number from the string and prepend it with +
```
$ vim +69 deep/dark/fantasies/Dungeon.txt
```

**Comment by lacygoill** [comment]
Relevant plugins:

- https://github.com/kopischke/vim-fetch
- https://github.com/bogado/file-line

**Comment by chrisbra** [comment]
this has been discussed several times. Please use any of the linked plugins.
