### ISSUE TITLE
console confirm() is case insensitive

### ISSUE THREAD

**Issue by noscript** [vim/vim#7233]
**Describe the bug**
Console version of `confirm()` does not distinguish between upper- and lower-case inputs. This does not apply to GUI version of dialogs.

**To Reproduce**
1. Run vim:
```
vim -g -u NONE +'set guioptions+=c | echo confirm("a or A?", "a\nA", 0)'
```
2. Reply to question with `a` or `A`.
3. In both cases the response is `1`.

**Expected behavior**
Response is `1` for `a`, and `2` for `A`

**Environment:**
 - Vim version: 8.2.1923
 - OS:  Ubuntu 20.04
 - Terminal: GUI

**Comment by tonymec** [comment]
I think this is intentional.

The example given in the help is
    confirm("Save changes?", "&Yes\n&No\n&Cancel")

which will ask "Save changes?" _Y_es, _N_o, _C_ancel.

After such a dialog, I would expect to be able to give a "yes" answer by typing just y without having to also press the Shift key.

Best regards,
Tony.

**Comment by tonymec** [comment]
P.S. The help says: "Thus you can type "c" to select "Cancel", confirmiing my hunch that case doesn't count.

Best regards,
Tony.

**Comment by noscript** [comment]
I think `confirm()` should have a case-sensitive flag.

**Comment by brammool** [comment]
I don't think a case sensitive version is very useful, this function is supposed to be for simple yes/no or cancel/ok questions, where case doesn't matter.
I'll add a remark in the help that case is ignored.
