### ISSUE TITLE
Compiler warning on Ubuntu 20.04

### ISSUE THREAD

**Issue by chdiza** [vim/vim#7235]
On Ubuntu 20.04, building 8.2.1931, I get the following warning that I wasn't getting several patchlevels ago IIRC:

```
gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_ATHENA     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1     -I/usr/include/x86_64-linux-gnu    -o objects/gui_at_fs.o gui_at_fs.c
In file included from /usr/include/string.h:495,
                 from os_unix.h:473,
                 from vim.h:228,
                 from gui_at_fs.c:44:
In function ‘strncat’,
    inlined from ‘SFreplaceText.isra.0’ at gui_at_fs.c:288:9:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:136:10: warning: ‘__builtin___strncat_chk’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
  136 |   return __builtin___strncat_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gui_at_fs.c: In function ‘SFreplaceText.isra.0’:
gui_at_fs.c:284:11: note: length computed here
  284 |     len = strlen(str);
      |           ^~~~~~~~~~~
```

**Comment by brammool** [comment]
> On Ubuntu 20.04, building 8.2.1931, I get the following warning that I wasn't getting several patchlevels ago IIRC:
> 
> ```
> gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_ATHENA     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1     -I/usr/include/x86_64-linux-gnu    -o objects/gui_at_fs.o gui_at_fs.c
> In file included from /usr/include/string.h:495,
>                  from os_unix.h:473,
>                  from vim.h:228,
>                  from gui_at_fs.c:44:
> In function ‘strncat’,
>     inlined from ‘SFreplaceText.isra.0’ at gui_at_fs.c:288:9:
> /usr/include/x86_64-linux-gnu/bits/string_fortified.h:136:10: warning: ‘__builtin___strncat_chk’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
>   136 |   return __builtin___strncat_chk (__dest, __src, __len, __bos (__dest));
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> gui_at_fs.c: In function ‘SFreplaceText.isra.0’:
> gui_at_fs.c:284:11: note: length computed here
>   284 |     len = strlen(str);
>       |           ^~~~~~~~~~~
> ```

I do see a few compiler warnings when building with Athena, but not this
one.  Perhaps your compiler has different defaults?
I'll make a patch for the errors that I can see.

-- 
        Very funny, Scotty.  Now beam down my clothes.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chdiza** [comment]
Thanks, but the exact same warning is still appearing.

I don't know what kind of defaults the compiler has.  I'm just using whatever came with Ubuntu 20.04.

**Comment by chdiza** [comment]
This eventually went away at some point.
