### ISSUE TITLE
Vim9: cannot put colon at start of line starting with modifier and containing range

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7239]
**Describe the bug**

In Vim9 script, we cannot put a colon at the start of a line starting with a modifier and containing a range.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        setline(1, 'xxx')
        def Func()
            :silent 1d _
        enddef
        defcompile
    EOF
    )

`E1050` is raised:

    E1050: Colon required before a range

**Expected behavior**

No error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-1936
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(361)

**Additional context**

Regression introduced in: [8.2.1934](https://github.com/vim/vim/releases/tag/v8.2.1934).

---

I'm not sure it's a bug.  Maybe it's working as intended.  However:

   - before the patch, we could use a colon anywhere before a range; not necessarily right before it
   - it is convenient to be able to write a colon anywhere before a range; not necessarily right before it
   - it looks weird to have to write a colon in the middle of a command

**Comment by lacygoill** [comment]
Also, if it is working as intended, then the error message at the script level is not very useful:
```vim
vim9script
setline(1, 'xxx')
:sil keepj 1d _
```
    E492: Not an editor command: :sil keepj 1d _

It should be:

    E1050: Colon required before a range

**Comment by brammool** [comment]
> **Describe the bug**
> 
> In Vim9 script, we cannot put a colon at the start of a line starting with a modifier and containing a range.
> 
> **To Reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(cat <<'EOF'
>         vim9script
>         setline(1, 'xxx')
>         def Func()
>             :silent 1d _
>         enddef
>         defcompile
>     EOF
>     )
> 
> `E1050` is raised:
> 
>     E1050: Colon required before a range
> 
> **Expected behavior**
> 
> No error is raised.
> 
> **Environment**
> 
>  - Vim version: 8.2 Included patches: 1-1936
>  - OS: Ubuntu 16.04.7 LTS
>  - Terminal: xterm(361)
> 
> **Additional context**
> 
> Regression introduced in: [8.2.1934](https://github.com/vim/vim/releases/tag/v8.2.1934).
> 
> ---
> 
> I'm not sure it's a bug.  Maybe it's working as intended.  However:
> 
>    - before the patch, we could use a colon anywhere before a range;
>    not necessarily right before it

The requirement for putting a colon before a range is to be able to tell
it apart from a command, variable name or operator.  Therefore it needs
to go just before the range itself, not before the modifier.  This was
wrong before the recent change.

>    - it is convenient to be able to write a colon anywhere before a range; not necessarily right before it
>    - it looks weird to have to write a colon in the middle of a command

It's even weirder to put a colon before a modifier to have it take
effect on the range that comes after it.  It's really as the error
message mentions: colon before a range.  This may take a little time to
get used to, but I think the rule is quite simple.

-- 
If Microsoft would build a car...
... You'd have to press the "Start" button to turn the engine off.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
Understood; it's working as intended then.  But if the colon is missing at the script level, maybe `E1050` should be raised instead of `E492`.
