### ISSUE TITLE
Git uses a lower case `index` for diffing

### ISSUE THREAD

**Issue by mtglsk** [vim/vim#724]
Here is a solution (runtime/syntax/diff.vim lines ~350) [note the lack of colon after `index`]:

```
syn match diffFile  "^index .*"
```

**Comment by chrisbra** [comment]
please contact the syntax script maintainer and discuss the issue with him.

**Comment by mtglsk** [comment]
According to the file, the author / maintainer is Bram Moolenaar, so i thought this would be a place to discuss this.

**Comment by chrisbra** [comment]
ah okay, I guess, it's okay then.

**Comment by brammool** [comment]
Looking at a git diff, that line is not really a line like "Index", it's some version thing.
Also "index " might match too match, I think we can make it more specific:

syn match diffIndexLine "^index \x\x\x\x.*"
hi def link diffIndexLine   PreProc
