### ISSUE TITLE
ex: global and ! commands don't handle multi-line commands correctly

### ISSUE THREAD

**Issue by mohd-akram** [vim/vim#7244]
**Describe the bug**
When vim is invoked as ex, it does not seem to handle several commands passed to the global command.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `printf '%s\n' i 1 2 . g/./p\\ p | ex`

**Expected behavior**
```
1
1
2
2
```

**Actual behavior**
```
1
2
2
```

**Environment (please complete the following information):**
 - Vim version 8.2.1943
 - OS: macOS 10.15.7
 - Terminal: Terminal.app

**Additional context**

It should also handle `!` commands correctly. `printf '%s\n' i 1 2 . 'g /./ !echo line \' p | ex` should output:

```
line
1
line
2
```

**Comment by chrisbra** [comment]
> printf '%s\n' i 1 2 . g/./p\\\\ p | ex

What is the backslash supposed to be doing there?

You can use:

    printf '%s\n' i 1 2 . g/./p|p | ex

See also `:h :bar`

**Comment by mohd-akram** [comment]
I've got too many commands to use the bar. According to [POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/ex.html):

> Multiple ex commands can be specified by entering multiple commands on a single line using a \<vertical-line> to delimit them, or one per line, by escaping each \<newline> with a \<backslash>.

The example I gave works correctly on nvi2, and on the version that comes with macOS:

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun  5 2020 21:30:37)
macOS version
Included patches: 1-503, 505-680, 682-2292
```

**Comment by mohd-akram** [comment]
Possible patch based on the macOS version:

```diff
--- a/src/ex_docmd.c
+++ b/src/ex_docmd.c
@@ -2301,12 +2301,6 @@ do_one_cmd(
 	    // versions.
 	    if (*p == '\\' && p[1] == '\n')
 		STRMOVE(p, p + 1);
-	    else if (*p == '\n')
-	    {
-		ea.nextcmd = p + 1;
-		*p = NUL;
-		break;
-	    }
 	}
     }
```

**Comment by brammool** [comment]
That patch is wrong, "global_busy" is always false here, thus it's basically make the block dead code.

You need to use three backslashes here.  This is a compromise between being able to have a line end in a backslash and being compatible with (very old) specs.  The example you give is very uncommon, not worth making a change to break backwards compatibility with previous versions of Vim.

**Comment by mohd-akram** [comment]
I applied the patch and all the tests passed. Which scenario breaks?

**Comment by mohd-akram** [comment]
@brammool I looked into this some more, and Vim's behavior definitely makes no sense.

Vim:

```
$ printf '%s\n' i 1 2 . '!echo hello' 'echo bye' | vim -e
hello
$ printf '%s\n' i 1 2 . '!echo hello\' 'echo bye' | vim -e
hello
$ printf '%s\n' i 1 2 . '!echo hello\\' 'echo bye' | vim -e
hello\
$ printf '%s\n' i 1 2 . '!echo hello\\\' 'echo bye' | vim -e
hello
bye
$ printf '%s\n' i 1 2 . '!echo hello\\\\' 'echo bye' | vim -e
hello\
```

nvi:

```
$ printf '%s\n' i 1 2 . '!echo hello' 'echo bye' | nvi -e
hello
script, 3: The echo command is unknown
$ printf '%s\n' i 1 2 . '!echo hello\' 'echo bye' | nvi -e
hello
bye
$ printf '%s\n' i 1 2 . '!echo hello\\' 'echo bye' | nvi -e
helloecho bye
$ printf '%s\n' i 1 2 . '!echo hello\\\' 'echo bye' | nvi -e
hello\
bye
$ printf '%s\n' i 1 2 . '!echo hello\\\\' 'echo bye' | nvi -e
hello\echo bye
```

Every useful permutation is possible in nvi but not vim (except maybe with even more backslashes...).

In fact the comment there seems to describe the opposite of what you said, and what the code is supposed to do:

```
	    // Remove one backslash before a newline, so that it's possible to
	    // pass a newline to the shell and also a newline that is preceded
	    // with a backslash.  This makes it impossible to end a shell
	    // command in a backslash, but that doesn't appear useful.
	    // Halving the number of backslashes is incompatible with previous
	    // versions.
```

> This makes it impossible to end a shell command in a backslash, but that doesn't appear useful.

I agree that it isn't useful, yet that is what Vim currently does.

The help says something similar:

```
A newline character ends {cmd}, what follows is
interpreted as a following ":" command.  However, if
there is a backslash before the newline it is removed
and {cmd} continues.  It doesn't matter how many
backslashes are before the newline, only one is
removed.
```

To address your other points:

- macOS [already patches](https://github.com/apple-open-source/macos/blob/10.15.6/vim/src/ex_docmd.c#L2209) their Vim to remove that `else if` clause completely (which isn't quite right). So that's a good portion of developers using Vim with this change, and presumably no one really noticed since its behavior is more correct and few will stumble on it.
- The specs aren't old, the one I linked is the latest 2018 edition. Their purpose is so I can write a script that uses `ex` and that will run the same everywhere. Right now the situation is that macOS has a half-patched version, presumably because they're certified UNIX, Vim behaving completely bizarrely, and nvi actually doing something sensible.
- `global_busy` is not always false there. My previous patch (see the edited comment) removed the `else if` cause completely like macOS but that wasn't quite right. The code seems to be removing backslashes beforehand so the comments above that section are misleading, and the incorrect behavior probably crept in at some point.

**Comment by konrad-schwarz** [comment]
Please see #6135 for more rationale for this change.  Ex `global` commands that use the `append`, `change`, or `insert` command require correct handling of backslash-newline; this is fundamental to line mode and inherited directly from Ed.

Thanks, mohd-akram, for cross-linking the issue and the patch!
