### ISSUE TITLE
Jump To Definition Implementation

### ISSUE THREAD

**Issue by beatscode** [vim/vim#725]
Could someone direct me to the area in the source code where "Jump to definition" is handled? I'm curious how this implemented.

**Comment by vim-ml** [comment]
Hi,

On Sat, Apr 2, 2016 at 6:33 AM, Alex Casanova vim-dev-github@256bit.org
wrote:

> Could someone direct me to the area in the source code where "Jump to
> definition" is handled? I'm curious how this implemented.
> 
> Are you referring to the gd/gD commands? These are implemented in the
> nv_gd() function in normal.c. Look into the find_ident_at_pos() and the
> find_decl() functions in the same file for more information.
- Yegappan
