### ISSUE TITLE
Vim9: cannot extend null dictionary

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7251]
**Describe the bug**

In Vim9 script, we cannot extend a null dictionary.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        var d: dict<any>
        extend(d, {'key': 123})
        assert_equal({'key': 123}, d)
        echo v:errors
    EOF
    )

`v:errors` contains one error:

    ['command line..script /proc/19712/fd/11 line 4: Expected {''key'': 123} but got {}']

**Expected behavior**

`v:errors` is empty.

**Environment**

 - Vim version: 8.2 Included patches: 1-1947
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(361)

**Additional context**

The issue persists in a `:def` function:
```vim
vim9script
var d: dict<any>
def Func()
    extend(d, {'key': 123})
    echom d
enddef
Func()
```
    {}

The issue disappears if the dictionary variable is assigned a value:
```vim
vim9script
var d: dict<any> = {}
extend(d, {'key': 123})
echom d
```
    {'key': 123}

**Comment by brammool** [comment]
> **Describe the bug**
> 
> In Vim9 script, we cannot extend a null dictionary.
> 
> **To Reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(cat <<'EOF'
>         vim9script
>         var d: dict<any>
>         extend(d, {'key': 123})
>         assert_equal({'key': 123}, d)
>         echo v:errors
>     EOF
>     )
> 
> `v:errors` contains one error:
> 
>     ['command line..script /proc/19712/fd/11 line 4: Expected {''key'': 123} but got {}']
> 
> **Expected behavior**
> 
> `v:errors` is empty.
> 
> **Environment**
> 
>  - Vim version: 8.2 Included patches: 1-1947
>  - OS: Ubuntu 16.04.7 LTS
>  - Terminal: xterm(361)
> 
> **Additional context**
> 
> The issue persists in a `:def` function:
> ```vim
> vim9script
> var d: dict<any>
> def Func()
>     extend(d, {'key': 123})
>     echom d
> enddef
> Func()
> ```
>     {}
> 
> The issue disappears if the dictionary variable is assigned a value:
> ```vim
> vim9script
> var d: dict<any> = {}
> extend(d, {'key': 123})
> echom d
> ```
>     {'key': 123}

The idea was that initializing a variable to a null dict was cheap.  But
extend() can only work on an existing (possibly empty) dictionary, not
on a null dictionary.  Thus there is no other way than to initialize the
variable to an empty dictionary.  Oh, we can do that when getting the
variable value.

-- 
hundred-and-one symptoms of being an internet addict:
190. You quickly hand over your wallet, leather jacket, and car keys
     during a mugging, then proceed to beat the crap out of your
     assailant when he asks for your laptop.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
