### ISSUE TITLE
Vim9: unexpected return type for reltime()

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7252]
**Describe the bug**

In Vim9 script, the return type of `reltime()` is `list<any>` instead of `list<number>`.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            var l: list<number> = []
            extend(l, reltime())
        enddef
        Func()
    EOF
    )

`E1013` is raised:

    E1013: Argument 2: type mismatch, expected list<number> but got list<any>

**Expected behavior**

No error is raised, because the output of `reltime()` is a list of numbers.

**Environment**

 - Vim version: 8.2 Included patches: 1-1947
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(361)

**Additional context**

I'm not sure this is a bug, because `:h reltime()` says that the format of the return value depends on the system.  On linux, it's a list of numbers; but it might be something different on other systems.

**Comment by brammool** [comment]
It is not stated that the returned item is of any specific type.  It currently happens to be a list of numbers, but it could also be something else, e.g. a float.  Using "any" doesn't give it any type checking though.  We can say the type is a list, but the member type should not matter.  Thus using list<any> should work.  I'll add a note in the help.
