### ISSUE TITLE
gvim display can become messed up after scrollup

### ISSUE THREAD

**Issue by basilisk0315** [vim/vim#7255]
**Describe the bug**
The screen may not always update properly in the windows gui after a cursor movement (via "{") causes the display to scroll downwards while both cursorline and scroll offset (2) are set.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run gvim on a file large enough to require scrolling. Enable cursorline and set scrolloff=2.
2. Scroll down the file a little.
3. Move the cursor upwards by pressing '{'.
4. After a few presses, the display may become corrupted.

**Expected behavior**
The display corruption does not happen.

**Screenshots**
This screenshot shows display before scroll:
![vim_before](https://user-images.githubusercontent.com/54644368/98164020-c002bf80-1f37-11eb-865c-9934831c728b.PNG)

This screenshot shows display after scroll (shift-{):
![vim_after](https://user-images.githubusercontent.com/54644368/98157896-24b91c80-1f2e-11eb-907f-77b86380e23e.PNG)

**Environment (please complete the following information):**
 - gVim 8.2 with patches 1-1955
 - OS: Windows 10 and Windows 8.1 both x64
 - Terminal: GUI

**Additional context**
This does not occur on every press of "{" which causes the display to scroll, but it does consistently for the text in the above screenshots, so I suspect something about the combination of the text and syntax highlighting perhaps. Edit: No, the problem occurs even with syntax highlighting off.
The problem does not happen if cursorline is disabled or scroll offset is set to 0.
I don't know when the problem was introduced. I tried going back to 8.2.1880 and the behaviour was still there but I just hadn't noticed.

**Comment by basilisk0315** [comment]
Update: I have tried to identify the problem but I'm not familiar enough with the code base to track it down.
I have found that the screen corruption only seems to occur if:
cursorline is set,
Lines are wrapped because the view is not wide enough,
The wrapped line is out of the view,
Pressing '{' causes the view to scroll so that the wrapped line is now in view.
I don't think the corruption is triggered when pressing '}'.

Before:
![gvim before](https://user-images.githubusercontent.com/54644368/126573855-d71740f0-d571-4bf7-b24b-2582d9515424.PNG)

After pressing '{' you can see the screen is now messed up with the cursorline artefact being left behind after the scroll:
![gvim after](https://user-images.githubusercontent.com/54644368/126573873-2dda5401-a512-40fb-ba7a-9f336d5377d2.PNG)

Then after pressing '}' you can see that the screen remains messed up:
![gvim after2](https://user-images.githubusercontent.com/54644368/126573978-13deeb99-5e5c-41cf-84bd-ae7ed889970e.PNG)

A screen refresh corrects the corruption, until it happens again of course.

Cheers

**Comment by brammool** [comment]
Have you tried doing the same in a terminal/console?  I wonder if this is a problem specifically in the GUI, the Windows GUI implementation or the generic drawing code.

**Comment by gdupras** [comment]
I can reproduce the bug consistently with this, with both Vim and gVim:

1. Open cmd.exe
2. `vim --clean -c"set co=40 lines=20 cursorline scrolloff=2" +120 $VIMRUNTIME\doc\options.txt`
3. `zt`
4. `CTRL-U`

Result:

![cursorline_bug](https://user-images.githubusercontent.com/57042631/126657598-b88fe3e6-954e-4d9f-a7cd-3c49178a1972.png)

Vim 8.2.3197 x64, from [https://github.com/vim/vim-win32-installer/releases](https://github.com/vim/vim-win32-installer/releases)

**Comment by brammool** [comment]
OK, now I can reproduce it.  The scroll amount is probably not computed correctly.

**Comment by brammool** [comment]
Fixed with patch 8.2.3204

**Comment by gdupras** [comment]
Thank you for the fix. However, in the commit message (c9e7e344ed3), you give me credit even though it really was @basilisk0315 who found and reported the bug.

**Comment by brammool** [comment]
> Thank you for the fix. However, in the commit message (c9e7e344ed3), you
> give me credit even though it really was @basilisk0315 who found and
> reported the bug.

Ah, I just noticed some strange user name "basilisk0315", didn't realize
that this is John Marriott.  I don't credit user names, only real names.
Anyway, you provided the reproduction steps, that matters a lot.

-- 
hundred-and-one symptoms of being an internet addict:
219. Your spouse has his or her lawyer deliver the divorce papers...
     via e-mail.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by basilisk0315** [comment]
Thanks Garbriel for the succinct repro instructions.
Thanks Bram for the fix. It has been bugging me for a while now and I am glad that it it has been sorted.

Cheers All
John
