### ISSUE TITLE
Unwanted Escape Sequences using vim

### ISSUE THREAD

**Issue by cecamp** [vim/vim#7257]
**Bug**
Unwanted escape sequences appear when starting/stopping vim

**To Reproduce**
```vim
vim -- clean  (or  vim -u NONE -U NONE)
:call system("/usr/bin/ls")
:q
```
On my scientific linux 7.9 system, I get a line of escape characters showing up on the bottom of the display: `<esc>>4;m<esc>>4;m<esc>>4;2m<esc>>4;2m`

Although annoying, the real problem is that I have some startup vim script that saves a list of files to a variable using system and /usr/bin/ls, and half of those escape sequences bleed through past the :q to the shell.

**Extra Information**
I suspect this may have something to do with the terminfo entry for xterm-256color.  However, only three sequences with `<esc>>` appear via the infocmp command:

`rs2=\E[!p\E[?3;4l\E[4l\E>`
`is2=\E[!p\E[?3;4l\E[4l\E`
`rmkx=\E[?1l\E>`

**Expected behavior**
No unwanted escape sequences.

**Comment by Shane-XB-Qian** [comment]
@cecamp  pls check #7015 - my comment at that ticket bottom.
// or detail at #5617

**Comment by cecamp** [comment]
It does appear that Shane-XB-Qian's ticket+solution stops the unwanted escape sequences for me, so I'll close the issue. FYI: the terminal is a gnome-terminal.
