### ISSUE TITLE
diffdelete messed if set cursorcolumn on when vimdiff

### ISSUE THREAD

**Issue by Shane-XB-Qian** [vim/vim#7258]
**Describe the bug**
highlight of diffdelete disappeared/messed if set cursorcolumn on when vimdiff and cursor on some specific place..

**To Reproduce**
1, e.g file 'x' had following content:
```txt
aa

cc
```
2, e.g file 'y' had following content:
```txt
aa
bb
cc
```
3, vimdiff --clean x y -c 'set cursorcolumn'
4, put cursor on first line, then compare the highlight different between cursor on 1st letter 'a' and 2ed letter 'a'.
5, if cursorcolumn off, highlight is no different.

**Expected behavior**
vimdiff highlight is no different, whatever cursorcolumn on or off.

**Screenshots**
![image](https://user-images.githubusercontent.com/13550529/98207322-784f5880-1f76-11eb-8b89-bae52e9c5d05.png)
// cursor on 1st letter 'a'
![image](https://user-images.githubusercontent.com/13550529/98207153-358d8080-1f76-11eb-87db-8346d9d30c69.png)
// cursor on 2ed letter 'a'

**Environment (please complete the following information):**
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov  5 2020 11:32:05) Included patches: 1-1955
 - OS: Ubuntu 18.04
 - Terminal: xfce-term

**Additional context**
n/a

**Comment by chrisbra** [comment]
isn't that just the Cursor Highlighting that you see there?

**Comment by Shane-XB-Qian** [comment]
pls check 'screenshot', so far the difference/mess i can see is highlight of `diffdelete` (the 2ed line - in this case).

**Comment by chrisbra** [comment]
So you would expect to see the cursorcolumn highlighting to be shown on top of the deleted line? 

Please be precise, it's not clear what you mean.

**Comment by Shane-XB-Qian** [comment]
this ticket title said this is about 'diffdelete', regardless 'cursorcolumn' hightlight, but just 'cursorcolumn' triggered this mess. clear?

or could you pls just try to reproduce and compare by :
move cursor on 1st letter 'a' -vs- 2ed letter 'a' when :
`vimdiff --clean x y -c 'set cursorcolumn'` -vs- `vimdiff --clean x y`

-or- just check the 'screenshots'.

**Comment by habamax** [comment]
I am not sure this is a "mess", it is just vim doesn't highlight anything on "deleted lines" as there are no actual lines:

![image](https://user-images.githubusercontent.com/234774/98220717-c73dc380-1f5f-11eb-8d18-01fa09cc95d0.png)

**Comment by chrisbra** [comment]
I did, but I find it hard to understand your wording, sorry. 

And please note, those are deleted lines, they are not really there. Can't you please answer my question:

> So you would expect to see the cursorcolumn highlighting to be shown on top of the deleted line?

**Comment by Shane-XB-Qian** [comment]
> I am not sure this is a "mess", it is just vim doesn't highlight anything on "deleted lines" as there are no actual lines:

@habamax no, if started vimdiff *withOut* 'cursorcolumn' on, you'll see 'diffdelete' showed on whereever your cursor placed.
-vs- if started vimdiff *With* 'cursorcolumn' on, where is the cursor looked like a trick, if at the linehead, 'diffdelete' disappeared.

**Comment by habamax** [comment]
@Shane-XB-Qian I don't understand to be fair, sorry.

**Comment by chrisbra** [comment]
so you are saying, that the diffeleted highlighting is different depending on the setting of the `cursorcolumn` option is set?

**Comment by Shane-XB-Qian** [comment]
@chrisbra  let's just focus on issue/bug itself, pls ..

pls just try to reproduce the case, note the 2ed line which 'bb' located, once you moved cursor on 1st 'a', or 2ed 'a', you will see 'diffdelete' is disappeared (if `cursorcolumn` set on -and- cursor put on linehead (1st 'a')).

**Comment by chrisbra** [comment]
> @chrisbra let's just focus on issue/bug itself, pls ..

That's what I am trying to do. However, I don't understand your wording. That's why I am asking the questions....

> pls just try to reproduce the case

Yes, so what is the case here?

**Comment by Shane-XB-Qian** [comment]
@chrisbra  at ticket description `To Reproduce` section, if you had trouble to reproduce it, pls just describle your 'trouble'.

**Comment by chrisbra** [comment]
@Shane-XB-Qian I am asking the questions, because I do not understand what issue you are having here. 

or perhaps I'll just leave this here for somebody else to understand. I am sorry.

**Comment by Shane-XB-Qian** [comment]
@habamax  pls started vim with '--clean', then `diffdelete` was there not matter had lines or lines deleted.

**Comment by Shane-XB-Qian** [comment]
@chrisbra what's your 'question' on reproducing, or you did not see the difference when reproducing ? let me know and try to help you understood the steps.
there 2 conditions: cursorcolumn on/off and cursor position, (plus '--clean'), then note the different on 2ed line where 'bb' located.
// or if you felt my english not very clear, then yes, i am not a native english speaker, if you are arguing that.

**Comment by k-takata** [comment]
Are you talking about that the background color of the 2nd line is changed from gray to cyan when the cursor is moved from the 1st column to the 2nd column?
Does it occur when you use a different terminal or gvim?

**Comment by chrisbra** [comment]
I suppose you are talking about this effect here:

https://asciinema.org/a/Ojpi8RPnXl6kMH5eRLQvdhm2d

note, how the DiffDelete color changes just by moving the cursor by one character in the first window

**Comment by Shane-XB-Qian** [comment]
> Are you talking about that the background color of the 2nd line is changed from gray to cyan when the cursor is moved from the 1st column to the 2nd column?

@k-takata  correct!

> Does it occur when you use a different terminal or gvim?

yes, i tried xfce-term, ternintor, xterm(330). same issue.
no, i only use tui vim.

**Comment by Shane-XB-Qian** [comment]
btw: the default `diffdelete` highlight is `cyan`.

**Comment by Shane-XB-Qian** [comment]
> when the cursor is moved from the 1st column to the 2nd column?

actually, this is not accurate, since `cyan` (`diffdelete`) disappeared when cursor on the 1st line (where 'aa' located).
-vs- if cursor located on 3rd line (where 'cc' located), then no matter cursor moved from 1st column or 2ed column.

// here, 'aa', 'bb', 'cc' is what file 'y' had -vs- file 'x' only had 'aa', 'cc'.

**Comment by Shane-XB-Qian** [comment]
> just by moving the cursor by one character in the first window

@chrisbra looks you reproduced the case now, and yes, in this case it is 'one char', but actually the difference was cursor on linehead or not-linehead, and if there was blank-line (for example: input a empty line after 'cc' in 'x') and cursor on that, then same issue: `diffdelete` (`cyan`) disappeared from 2ed line.

**Comment by habamax** [comment]
> 
> 
> I suppose you are talking about this effect here:
> 
> https://asciinema.org/a/Ojpi8RPnXl6kMH5eRLQvdhm2d
> 
> note, how the DiffDelete color changes just by moving the cursor by one character in the first window

Aha!

Can't reproduce on gvimdiff and vimdiff on windows 8.2.1947
Also can't reproduce on WSL debian 8.2.1955

**Comment by chrisbra** [comment]
If my git bisect magic was good, then this is caused by https://github.com/vim/vim/commit/ad5e5631c5dc93a50bbe63

**Comment by habamax** [comment]
![vim-issue-7258](https://user-images.githubusercontent.com/234774/98231264-3ec61f80-1f6d-11eb-84a9-5530ca1871ac.gif)

**Comment by chrisbra** [comment]
can you check, if this patch fixes it:

```diff
diff --git a/src/drawline.c b/src/drawline.c
index 82738f13c..c61cdfd55 100644
--- a/src/drawline.c
+++ b/src/drawline.c
@@ -2778,10 +2778,14 @@ win_line(
        // Also highlight the 'colorcolumn' if 'breakindent' and/or 'showbreak'
        // options are set
        vcol_save_attr = -1;
-       if ((draw_state == WL_LINE ||
+       if (((draw_state == WL_LINE ||
             draw_state == WL_BRI ||
             draw_state == WL_SBR) && !lnum_in_visual_area
                && search_attr == 0 && area_attr == 0)
+# ifdef FEAT_DIFF
+                       && filler_lines == 0
+# endif
+               )
        {
            if (wp->w_p_cuc && VCOL_HLC == (long)wp->w_virtcol
                                                 && lnum != wp->w_cursor.lnum)
```

**Comment by habamax** [comment]
Okay, was able to repro -- file contents in OP initial post is not correct:

it should be
```
aa
cc
```

not
```
aa

cc
```

**Comment by Shane-XB-Qian** [comment]
@chrisbra  yes, i tried. this patch / maco looks can get rid of this concern case.
however, not sure -or if it passed ci tests, if yes, then should be good to go. thx.
