### ISSUE TITLE
Vim9: E1028 when checking if the GUI is running

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7265]
**Describe the bug**

In Vim9 script, Vim fails to compile a function which returns when the GUI is not running.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            if has('gui_running')
                return
            endif
        enddef
        defcompile
    EOF
    )

`E1028` is raised:

    E1028: Compiling :def function failed

**Expected behavior**

`E1028` is not raised.  The compilation succeeds.  If for some reason, the compilation cannot succeed, then [a more specific error is given](https://github.com/vim/vim/issues/7143#issuecomment-710589398).

**Environment**

 - Vim version: 8.2 Included patches: 1-1959, 1959-1961
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(361)

**Additional context**

Regression introduced in [8.2.1528](https://github.com/vim/vim/releases/tag/v8.2.1528).

**Comment by brammool** [comment]
> In Vim9 script, Vim fails to compile a function which returns when the GUI is not running.
> 
> **To Reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(cat <<'EOF'
>         vim9script
>         def Func()
>             if has('gui_running')
>                 return
>             endif
>         enddef
>         defcompile
>     EOF
>     )
> 
> `E1028` is raised:
> 
>     E1028: Compiling :def function failed
> 
> **Expected behavior**
> 
> `E1028` is not raised.  The compilation succeeds.  If for some reason, the compilation cannot succeed, then [a more specific error is given](https://github.com/vim/vim/issues/7143#issuecomment-710589398).

There is a todo item for this:

	- has() is compiled as a constant, but some checks are dynamic.
	  Check for dynamic values, such as "gui_running".

-- 
    "You mean there really is an answer?"
    "Yes! But you're not going to like it!"
    "Oh do please tell us!"
    "You're really not going to like it!"
    "but we MUST know - tell us"
    "Alright, the answer is...."
    "yes..."
    "... is ..."
    "yes... come on!"
    "is 42!"
		(Douglas Adams - The Hitchhiker's Guide to the Galaxy)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
