### ISSUE TITLE
'quickfix' showed messed result if added an invalid item

### ISSUE THREAD

**Issue by Shane-XB-Qian** [vim/vim#7271]
**Describe the bug**
'quickfix' a.k.a 'qf' showed messed result if added an invalid item

**To Reproduce**
1, echo -e "aa\nbb\ncc" >x
2, vi --clean x -c "vimgrep /bb/ % | copen | redraw | clast | call setqflist([' <-- abc'], 'a')"

**Expected behavior**
pls check 'screenshot' below, normally and **compatible** result should be showing:
1. 'bb' at 1st item.
2, **' <-- abc' as invalid item at 2ed item.**
but now had 2 'bb' items showed, and/but actually there is only 1 'bb' item in `getqflist()`, even no that 'invalid' `<-- abc` item.

**Screenshots**
![image](https://user-images.githubusercontent.com/13550529/98437815-5691d500-2120-11eb-8a3e-ecf6ff390f85.png)

**Environment (please complete the following information):**
 - VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov  7 2020 12:24:04) Included patches: 1-1964
 - OS: Ubuntu 18.04
 - Terminal: xfce-term xterm(330)

**Additional context**
looked into about 60 plugins, looks it impacted lots of plugins behaviour, or unless if i misunderstood/confused something..

**Comment by brammool** [comment]
I think what you mean is that this part of the help is not applied: "Non-dictionary items in {list} are ignored.".
You pass a string but it's not ignored.

**Comment by brammool** [comment]
Oh, and this is about quickfix, not the "qf" command (which doesn't exist, I read it as "gf").

**Comment by Shane-XB-Qian** [comment]
yes. 'qf' generally shorten for 'quickfix'.  :)

// as compatible, `getqflist()` should return 'invalid' items also by default.
// and show qf items correctly, even it was an 'invalid' item.
otherwise lots plugins depends on getqflist() to judge qf items would be wrong, and qf items would Not be showed / matched 'getqflist()' reality, and cannot added 'invalid' items (sometime it is intended to do so) into qf.

spent 2 days to look into about 60 plugins, looks it is impacted a lot to plugins' right behaviours ..........

**Comment by Shane-XB-Qian** [comment]
and some native vim cmd e.g 'cadde' etc perhaps were wrong, also.. if so...

**Comment by Shane-XB-Qian** [comment]
@vim-ml @brammool we're working on this, right? or whatever pls queue it per your priority.

**Comment by yegappan** [comment]
I have opened PR #7291 to fix this issue.

**Comment by Shane-XB-Qian** [comment]
@yegappan thx. i tried that pr, looks showed 2 'bb' items issue had been fixed. however, i found a weird issue still:
![image](https://user-images.githubusercontent.com/13550529/99140989-55612a80-2681-11eb-836f-1692f3c1ff2d.png)
// however i cannot solid reproduce it specially when/if '--clean', i just tried to cadde some invalid items into a existed qf.
// but you saw the items showed is not same like getqflist() get, specially those cadde items merged into that existed item..
// why? not sure if you had chance to know/find-out if there was any possibility to make such case happened..

**Comment by bfrg** [comment]
This seemed to have been related to https://github.com/vim/vim/issues/5735.

**Comment by vim-ml** [comment]
Hi,

On Fri, Nov 13, 2020 at 10:01 PM Shane-XB-Qian <vim-dev-github@256bit.org>
wrote:

> @yegappan <https://github.com/yegappan> thx. i tried that pr, looks
> showed 2 'bb' items issue had been fixed. however, i found a weird issue
> still:
> [image: image]
> <https://user-images.githubusercontent.com/13550529/99140989-55612a80-2681-11eb-836f-1692f3c1ff2d.png>
> // however i cannot solid reproduce it specially when/if '--clean', i just
> tried to cadde some invalid items into a existed qf.
> // but you saw the items showed is not same like getqflist() get,
> specially those cadde items merged into that existed item..
> // why? not sure if you had chance to know/find-out if there was any
> possibility to make such case happened..
>
>
>
I tried to reproduce this problem by using the ':caddexpr "make\n<--
abc\n<-- def"' command.
I couldn't reproduce this problem. Are you using any plugins that modify
the quickfix list?
I assume, if you close and reopen the quickfix window, then the correct
entries are
displayed in the quickfix buffer?

- Yegappan

**Comment by Shane-XB-Qian** [comment]
@bfrg not sure that ticket detail, but seems this fix should be helpful to it.
// this fix/ticket i guess would stop many qf related weird issues, help them stop struggling with it.. :)

@yegappan @vim-ml pls ignore what i said second/another weird issue, it should be influenced by efm from somewhere, though so far i am not sure where it is..
// anyway, this qf showed messed result issue had been fixed, thx buddy and @brammool . :+1:
