### ISSUE TITLE
Running terminal inside Vim

### ISSUE THREAD

**Issue by a180024** [vim/vim#7274]
**Describe the bug**
When i run the terminal from inside Vim, every command that i type seems to be echoed out onto the terminal together with the output. If I run it outside of vim, it's fine.

**Screenshots**
```
$ls 
ls applications Desktop Documents
$which python
which/usr/local/python
```

**Environment (please complete the following information):**
 - Vim version [e.g. 8.1.1234] (Or paste the result of `vim --version`.)
 - OS: Mac 10.15.5
 - Terminal: [iTerm2, tmux]

Not sure why this is happening suddenly, can't seem to find a solution. 

Would appreciate any help thanks!

**Comment by chrisbra** [comment]
Please check your shell settings. BTW: what shell are you using?

**Comment by a180024** [comment]
> Please check your shell settings. BTW: what shell are you using?

Thank you! I've got it by removing export TERM='xterm-256color'. I'm using ZSH.
