### ISSUE TITLE
Character À eats up the next two characters when in scriptin in :source! <scriptin>

### ISSUE THREAD

**Issue by filipelbc** [vim/vim#728]
Problem: character `À` (Hex `00C0`) eats up the next two characters
when inside a script used as `<scriptin>` in `:source! <scriptin>`

**Steps to reproduce**
- Script file `script.vim`

```
:%s/à nossa/--à nossa--/g
:%s/À nossa/--À nossa--/g
```
- Sample file `text`

```
Assim mesmo, a complexidade dos estudos efetuados ainda não demonstrou
convincentemente que vai participar na mudança do levantamento das variáveis
envolvidas. Todas estas questões, devidamente ponderadas, levantam dúvidas
sobre se a constante divulgação das À nossa foo à nossa informações afeta
positivamente a correta previsão das diretrizes de desenvolvimento para o
futuro. Desta maneira, o entendimento das metas propostas nos obriga à análise
do sistema de participação geral. Podemos já vislumbrar o modo pelo qual a
futuro. Desta maneira, o entendimento das metas propostas nos obriga à análise
sobre se a constante divulgação das À nossa foo à nossa informações afeta
estrutura atual da organização é uma das consequências do impacto na agilidade
decisória.
```
- Vim invocation `$ vim -N -u NONE text`
- Command (a) `:source script.vim`
- Command (b) `:source! script.vim`

**Results:**

Using (a) everything works as expected.

Using (b) the second substitute command is read as
(which can be seen in the command history)

`:%s/Àossa/--Àossa/g`

resulting in the error

`E486: Pattern not found: Àossa`

while the first substitute works as expected.

Both files are uft-8. Others characters, like `Ò`, seems to work fine.

**Comment by chrisbra** [comment]
I think this patch fixes it:

``` patch
diff --git a/src/getchar.c b/src/getchar.c
index 4a225e1..75c083b 100644
--- a/src/getchar.c
+++ b/src/getchar.c
@@ -3059,7 +3059,7 @@ inchar(
     if (typebuf_changed(tb_change_cnt))
        return 0;

-    return fix_input_buffer(buf, len, script_char >= 0);
+    return fix_input_buffer(buf, len);
 }

 /*
@@ -3070,8 +3070,7 @@ inchar(
     int
 fix_input_buffer(
     char_u     *buf,
-    int                len,
-    int                script)         /* TRUE when reading from a script */
+    int                len)
 {
     int                i;
     char_u     *p = buf;
@@ -3105,7 +3104,7 @@ fix_input_buffer(
        }
        else
 #endif
-       if (p[0] == NUL || (p[0] == K_SPECIAL && !script
+       if (p[0] == NUL || (p[0] == K_SPECIAL
 #ifdef FEAT_AUTOCMD
                    /* timeout may generate K_CURSORHOLD */
                    && (i < 2 || p[1] != KS_EXTRA || p[2] != (int)KE_CURSORHOLD)
diff --git a/src/proto/getchar.pro b/src/proto/getchar.pro
index 97a2828..fd6ec5d 100644
--- a/src/proto/getchar.pro
+++ b/src/proto/getchar.pro
@@ -48,7 +48,7 @@ int vpeekc_any(void);
 int char_avail(void);
 void vungetc(int c);
 int inchar(char_u *buf, int maxlen, long wait_time, int tb_change_cnt);
-int fix_input_buffer(char_u *buf, int len, int script);
+int fix_input_buffer(char_u *buf, int len);
 int input_available(void);
 int do_map(int maptype, char_u *arg, int mode, int abbrev);
 int get_map_mode(char_u **cmdp, int forceit);
```

I am not sure, why the `!script` condition was there in the first place, but that prevents, that K_SPECIAL will be replaced correctly and then later parsed back correctly into the `À` character.

**Comment by filipelbc** [comment]
Seems to fix. But you forgot to change here:

``` diff
diff --git a/src/misc1.c b/src/misc1.c
index ddd9a07..3892e5e 100644
--- a/src/misc1.c
+++ b/src/misc1.c
@@ -3410,7 +3408,7 @@ get_keystroke(void)
    if (n > 0)
    {
        /* Replace zero and CSI by a special key code. */
-       n = fix_input_buffer(buf + len, n, FALSE);
+       n = fix_input_buffer(buf + len, n);
        len += n;
        waited = 0;
    }
```

**Comment by dpelle** [comment]
This issue might be related to the following entry in ":help todo.txt";

Test 44 fails when [[=A=]] is changed to [[=À=]].  Caused by getcmdline() not
handling the 0x80 as a second byte correctly?  (Dominique Pelle, 2015 Jun 10)

**Comment by chrisbra** [comment]
@filipelbc upps, you are correct, sorry for the inconvenience

And yes, I think, this also fixes the mentioned todo item.

**Comment by brammool** [comment]
Christian Brabandt wrote:

> I think this patch fixes it:

Can you give an explanation why this change is needed?

When recording key strokes and playing them back, does that still work?

## 

"After a few years of marriage a man can look right at a woman
without seeing her and a woman can see right through a man
without looking at him."
- Helen Rowland
  
  /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
  ///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
  \\  an exciting new programming language -- http://www.Zimbu.org        ///
  \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
Bram wrote:

> Can you give an explanation why this change is needed?

when reading the script, Vim finds the `À`,  whose second byte is the 80. And this is K_SPECIAL in Vim source and needs to be replaced by K_SPECIAL KS_SPECIAL KE_FILLER to be correctly parsed later in vgetorpeek when Vim sees the K_SPECIAL and increments the offset pointer of the typebuf struct by 2, thinking, that it needs to skip the next 2 special bytes. But since the K_SPECIAL has not been escaped correctly, it will skip two chars from the script file.

> When recording key strokes and playing them back, does that still work?

I will check and will try to create a test for that behaviour later when I come up with a proper patch.
