### ISSUE TITLE
complete-popup: WinLeave is triggered for every complete-item with an 'info' field

### ISSUE THREAD

**Issue by bfrg** [vim/vim#7296]
**Describe the bug**
When cycling through the insert-completion menu and `complete-popup` is enabled, Vim executes the `WinLeave` event and temporarily focuses the info-popup on every `CTRL-N` or `CTRL-P` key press. This occurs only for items that have the `info` field specified.

I'm not entirely sure whether that's intentional or unexpected. But since popup windows technically can't be focused I assumed this is a bug.

**To Reproduce**
1. Run `vim --clean -S test.vim`, with
   ```vim
   set completeopt=menu,popup
   let s:count = 1
   new logbuf
   wincmd p
   
   augroup test
       autocmd!
       autocmd WinLeave *
               \ call printf('WinLeave: %d, win-ID: %d, win_gettype: %s',
               \   s:count,
               \   win_getid(),
               \   win_gettype()
               \ )
               \ ->appendbufline('logbuf', '$')
               \ | let s:count += 1
   augroup END
   
   function ListMonths()
       call complete(col('.'), [
               \ {'word': 'January',   'info': 'January'},
               \ {'word': 'February',  'info': 'February'},
               \ {'word': 'March'},
               \ {'word': 'April'},
               \ {'word': 'May'},
               \ {'word': 'June'},
               \ {'word': 'July',      'info': 'July'},
               \ {'word': 'August',    'info': 'August'},
               \ {'word': 'September', 'info': 'September'},
               \ {'word': 'October',   'info': 'October'},
               \ {'word': 'November',  'info': 'November'},
               \ {'word': 'December',  'info': 'December'}
               \ ])
       return ''
   endfunction
   
   inoremap <F1> <cmd>call ListMonths()<cr>
   ```
2. Press `F1` in insert-mode to open the popup menu, then cycle through the menu with `CTRL-N` a few times.
3. Result: After pressing `F1`, the following is printed to the log buffer:
   ```
   WinLeave: 1, win-ID: 1000, win_gettype: 
   WinLeave: 2, win-ID: 1002, win_gettype: popup
   WinLeave: 3, win-ID: 1000, win_gettype: 
   WinLeave: 4, win-ID: 1002, win_gettype: popup
   ```
4. It appears that whenever an item has the `info` field specified, Vim temporarily focuses the info popup-window.

**Expected behavior**
No `WinLeave` events triggered when cycling through the `ins-completion-menu` with `CTRL-N` or `CTRL-P`.

**Environment**
Vim version `8.2.1980`

**Additional Context**
cc @obcat
https://github.com/obcat/vim-hitspop/issues/5

**Comment by brammool** [comment]
The code that shows the info popup is based on the code that uses the preview window.  For that one it might make sense to have WinEnter and WinLeave autocommands, e.g. to resize the window on demand.
I can't think of what the use of these autocommands is for the popup.  That the popup becomes the current window is just a side effect of how it's filled with text.
Let me disable autocommands and see if someone misses them.
