### ISSUE TITLE
Cursorline does not get removed when moving up (mac os terminal.app)

### ISSUE THREAD

**Issue by skamsie** [vim/vim#7297]
If cursorline is set to `underline` (the default option when you `:set cursorline`), the underline does not get removed when moving up with the 'k' key.

**Vim Version**
```
vim --version 
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov  4 2020 11:27:02)
macOS version
Included patches: 1-1950
Compiled by Homebrew
```
**OS**
```
macOS Catalina version 10.15.7
```

Example below with vanilla vim without .vimrc on the default terminal.app on mac

![vim_cursorline_bug](https://user-images.githubusercontent.com/7014744/99181114-b560db00-272c-11eb-90d0-eedf1cbfb840.gif)

**Comment by dpelle** [comment]
I don't see this issue, but I'm using Linux xubuntu-18.04.5 with xfce4-terminal, with TERM being xterm-256color.

What is your terminal and environment variable TERM?

**Comment by skamsie** [comment]
@dpelle mac os native terminal app

```
> echo $TERM     
xterm-256color
```

**Comment by skamsie** [comment]
Turns out it's font related, not sure if the bug is still relevant in this context so I am closing it.
