### ISSUE TITLE
issues of patch 8.2.1990

### ISSUE THREAD

**Issue by ZhiyuanLck** [vim/vim#7307]
**Describe the bug**
patch 8.2.1990 fix #7298, but brought some new problem

**To Reproduce**
1. `test.vim` this file provide function to reproduce the issues.
```vim
set number
function! Test(mode=0)
  let cmd = &shell
  let bufnr = term_start(cmd, #{
        \ term_cols:   80,
        \ term_rows:   20,
        \ hidden:      1,
        \ norestore:   1,
        \ term_finish: 'open'
        \ })
  let opts = #{
        \ maxwidth: 80,
        \ minwidth: 80,
        \ maxheight: 20,
        \ minheight: 20,
        \ zindex: 1000,
        \ pos: 'center',
        \ scrollbar: 0,
        \ }
  let last_bufnr = bufnr('%')
  if a:mode >= 0
    let winid = popup_create(bufnr, opts)
  endif
  if a:mode == 1
    call setbufvar(last_bufnr, '&number', 1)
  endif
  if a:mode == 2
    let opts = #{
          \ maxwidth: 10,
          \ minwidth: 10,
          \ maxheight: 1,
          \ minheight: 1,
          \ zindex: 1000,
          \ pos: 'topleft',
          \ line: 2,
          \ col: 4,
          \ scrollbar: 0,
          \ }
    let bufnr = bufadd('')
    call popup_create(bufnr, opts)
    call setbufline(bufnr, 1, 'test')
  endif
endfunction
```
2. run `vim --clean -S test.vim`
3. run `:call Test(0)`
4. quit vim, repeat step 2 and run `:call Test(1)`
5. quit vim, repeat step 2 and run `:call Test(2)`

**Expected behavior**
In step 3, a normal teminal is created and show in terminal, but the line number in the original buffer has gone (which may be **another issue**, this issue alse existed in the past verisons)

In step 4, I give a try to fix the problem of line number, in past versions, it works, but now, the terminal "dissapears", the popup is not shown and the focus is on the original buffer. If I quit vim, there is no warning that reminds me of a running job. But the terminal did exists, if I run `:bn`, I will get the terminal buffer, and if I run `<c-\><c-n>` next, the popup shows...

In step 5, If I try to open another popup, the same issue occurs as the same in step 4.

**Environment (please complete the following information):**
  - Vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 24 2020 16:26:37) included patch 1-1992
  - OS: Ubuntu 18.04,
  - Terminal: GNOME Terminal

**Comment by bfrg** [comment]
I couldn't reproduce the issue with the `number`. In general it's easier to follow what is going on when you separate the issues into separate test cases.

I can reproduce the issue with `call Test(2)`. Here's a slightly simplified version of above. Adding a border to the popup shows what's going on.

1. Run `vim --clean -S test.vim`, with:
```vim
" test.vim
function Test(mode) abort
    call term_start(&shell, #{hidden: 1, term_finish: 'close'})
            \ ->popup_create(#{
            \   border:    [],
            \   maxwidth:  80,
            \   minwidth:  80,
            \   maxheight: 20,
            \   minheight: 20
            \ })

    if a:mode
        let bufnr = bufadd('')
        call bufload(bufnr)
        call setbufline(bufnr, 1, 'test')
        call popup_create(bufnr, #{
                \ maxwidth:  10,
                \ minwidth:  10,
                \ maxheight: 1,
                \ minheight: 1,
                \ pos:       'topleft',
                \ line:      2,
                \ col:       4
                \ })
    endif
endfunction

call Test(2)
```
2. Result: The popup windows are drawn but the terminal buffer isn't displayed for some reasons.
3. Passing the text we want to display in the popup directly to `popup_create()` works fine though:
```vim
" test.vim
function Test(mode) abort
    call term_start(&shell, #{hidden: 1, term_finish: 'close'})
            \ ->popup_create(#{
            \   border:    [],
            \   maxwidth:  80,
            \   minwidth:  80,
            \   maxheight: 20,
            \   minheight: 20
            \ })

    if a:mode
        call popup_create('test', #{
                \ maxwidth:  10,
                \ minwidth:  10,
                \ maxheight: 1,
                \ minheight: 1,
                \ pos:       'topleft',
                \ line:      2,
                \ col:       4
                \ })
    endif
endfunction

call Test(2)
```

**Comment by ZhiyuanLck** [comment]
Thank for @bfrg's improvement about my example, the reason why the line number disappeared is that I set
```vim
au TerminalOpen * setlocal nonumber
```
which take effects after the call of `term_start()`. So it is not an issue, sorry for that.

**Comment by bfrg** [comment]
For that you can use the `TerminalWinOpen` event:
```vim
augroup termsettings
    autocmd!
    autocmd TerminalWinOpen * setlocal nonumber norelativenumber colorcolumn=
augroup END
```
