### ISSUE TITLE
Vim9: two syntaxes for dictionary is confusing

### ISSUE THREAD

**Issue by itchyny** [vim/vim#7310]
## Problem
Vim9 script supports two syntaxes for dictionary; dictionary and literal dictionary, as same as Vim script. However, having two syntaxes for dictionary in one language is confusing sometimes, especially for beginners. I'm afraid these syntaxes make Vim9 script wired for learners.
```
var x = { 'foo': 1, 'bar': 2 }

var foo = 'x'
var bar = 'y'
var y = { foo: 1, bar: 2 } # {'x': 1, 'y': 2}
var z = { join(range(5)): 10 } # {'0 1 2 3 4': 10} but who needs this?

# Literal dictionary
var w = #{ foo: 1, bar: 2 }
```
I know the literal dictionary syntax was introduced to avoid the confusing key-evaluation behavior in Vim script. But we don't need to bring this behavior to the new language.

## Specification suggestion
I suggest following changes.

- Changing the dictionary syntax supports either string literal keys or name keys.
  - For example, both `{ 'a b c': 1 }` and `{ foo: 1 }` (exactly same as `{ 'foo': 1 }`) are supported. Stop evaluating the keys as expression.
- Dropping literal dictionary syntax `#{ foo: 1 }`, and treat `#` as comment leader anytime.

```
var x = { 'foo': 1, 'bar': 2 }
var y = { x: 1, y: 2 }

# We cannot var z = { join(range(5)): 10 }, so we have to
var z: dict<number>
z[join(range(5))] = 10

# Mixing literal keys and string keys is allowed
var w = { foo: 1, 'a b c': 2 }
```

This is exactly same as JavaScript and much more intuitive for many programmers. And this also makes the Vim9 compiler simpler.

**Comment by brammool** [comment]
> ## Problem
> Vim9 script supports two syntaxes for dictionary; dictionary and
> literal dictionary, as same as Vim script. However, having two
> syntaxes for dictionary in one language is confusing sometimes,
> especially for beginners. I'm afraid these syntaxes make Vim9 script
> wired for learners.

It's a good point that the #{} syntax is unlike any other popular
language.  Using {} for all dictionaries is "less weird".

There are three disadvantages:
- Different from legacy script.  I think we can live with this, since
  there are other differences, such as the comment character #.
- Using {} both for literal keys and key expressions.  This can be a bit
  tricky, a typo may give unexpected errors.
- Separating {} used for a dictionary from {} used for a lambda.  The
  last has "->" somewhere, otherwise they are very similar.  Again, a
  typo can cause confusing error messages.


> ```
> var x = { 'foo': 1, 'bar': 2 }
> 
> var foo = 'x'
> var bar = 'y'
> var y = { foo: 1, bar: 2 } # {'x': 1, 'y': 2}

I don't think it is acceptable to look for the context to see what "foo"
means, "foo" should always be used as a literal key.
It should be possible to indicate "foo" is a variable name, e.g.

 var y = { '' .. foo: 1, '' .. bar: 2 } # {'x': 1, 'y': 2}

It's a bit clumsy, but it would not be used often.

> var z = { join(range(5)): 10 } # {'0 1 2 3 4': 10} but who needs this?

That can actually work, since "join(range(5))" is not an ID.

> # Mixing literal keys and string keys is allowed
> var w = { foo: 1, 'a b c': 2 }

This is a bit confusing and may lead to mistakes, but we need to allow
it for consistency.

> This is exactly same as JavaScript and much more intuitive for many
> programmers. And this also makes the Vim9 compiler simpler.

I actually don't like how JavaScript does this, it's not intuitive.
Someone who hasn't used this before needs to read documentation to find
out how this works.  But still, it's a popular language and this syntax
is used a lot.

It will make the compiler more complicated, actually.  Recognizing a
lambda gets tricky:
	{a: bool, b: string -> a .. b}
Up to the "->" this very much looks like a dictionary.

-- 
hundred-and-one symptoms of being an internet addict:
262. Your computer has it's own phone line - but your daughter doesn't.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
> > This is exactly same as JavaScript and much more intuitive for many
> > programmers. And this also makes the Vim9 compiler simpler.

This is actually not correct.  Since 2015 JavaScript uses square
brackets for a key that is made from an expression:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#Computed_property_names

```
	var fooVar = 'foo'
	var barVar = 'bar'
	var d = {[fooVar]: 1, [barVar]: 2}
```

Somehow I haven't seen this used, an indication that this isn't commonly
used. Mostly the keys would be literal IDs, then it looks very common:

```
	var d = {foo: 1, bar: 2}
```

Just like the #{} dictionary we have now, but without the #.
If you need to you can use the [] notation for computed keys.
This seems like a good solution for Vim9 script.

-- 
hundred-and-one symptoms of being an internet addict:
268. You get up in the morning and go online before getting your coffee.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Houl** [comment]
I guess `var d = {(fooVar): 1, (barVar): 2}` will work too.  Is the bracket-notation needed?

**Comment by itchyny** [comment]
> It will make the compiler more complicated, actually.  Recognizing a
> lambda gets tricky:
> 	{a: bool, b: string -> a .. b}
> Up to the "->" this very much looks like a dictionary.

Thanks for this example, I missed this point. I think this lambda syntax is also
rare in languages and want to change this like TypeScript arrow functions.

> This is actually not correct.  Since 2015 JavaScript uses square
> brackets for a key that is made from an expression:
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#Computed_property_names

I knew the syntax but I think we don't need to start with fat specifications. Even
for JavaScript it took 20 years to allow this syntax since it came out to the world.


Why don't we start with small syntaxes. Providing development tools like language server
and code formatter, and stable language specifications are much much more important for
users than implementing complex syntaxes.

**Comment by brammool** [comment]
> I guess `var d = {(fooVar): 1, (barVar): 2}` will work too.  Is the
> bracket-notation needed?

What other language does it like this?

One of the goals is to do things the same way as other popular
languages.  I think for dictionaries JavaScript comes closest.
They may also call them object literals.

Python also uses dictionaries, but there the key can be anything, not
only a string, thus that is different.

-- 
Ten bugs in the hand is better than one as yet undetected.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Houl** [comment]
Just asking, it was not a proposal.

**Comment by lacygoill** [comment]
Possibly fixed by [8.2.2015](https://github.com/vim/vim/commit/2bede173a177e227e6224a8713f5b88a38d011af):
```vim
vim9script
def Func()
    var d = {key: 123}
    echom d
enddef
Func()
```
However, the `#` sign can only be dropped in a `:def` function; not at the script level:
```vim
vim9script
var d = {key: 123}
echom d
```
    E121: Undefined variable: key
    E121: Undefined variable: d

**Comment by lacygoill** [comment]
> However, the `#` sign can only be dropped in a `:def` function; not at the script level:

Talked too fast; [8.2.2017](<https://github.com/vim/vim/commit/67d1c68f095eb6cbb6355b04972e384d23065c2c>) also implemented the new syntax at the script level.

**Comment by lacygoill** [comment]
Right now, `#{}` is still parsed as a literal dictionary in Vim9 script.  Will it change?  That is, will `#{}` be parsed as a comment in the future?

**Comment by brammool** [comment]
> Right now, `#{}` is still parsed as a literal dictionary in Vim9
> script.  Will it change?  That is, will `#{}` be parsed as a comment
> in the future?

Yes, I'm giving those who have started writing Vim9 scripts a chance to
adjust to the new syntax before disallowing the #{} syntax.
Although in a few cases the change has already broken some things, as
the changes to tests indicates.

I plan to remove the support for #{} in Vim9 script in a couple of
weeks.

-- 
       He was not in the least bit scared to be mashed into a pulp
       Or to have his eyes gouged out and his elbows broken;
       To have his kneecaps split and his body burned away
       And his limbs all hacked and mangled, brave Sir Robin.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
Not sure, but I think the issue can be closed now; in 8.2.2082 the old syntax has been dropped, so there's nothing left actionable.

To summarize, here is the list of relevant commits which has progressively fixed the issue:

 - [8.2.2015](https://github.com/vim/vim/releases/tag/v8.2.2015)  Vim9: literal dict #{} is not like any other language
 - [8.2.2017](https://github.com/vim/vim/releases/tag/v8.2.2017)  missing part of the dict change
 - [8.2.2082](https://github.com/vim/vim/releases/tag/v8.2.2082)  Vim9: can still use the depricated #{} dict syntax
 - [8.2.2090](https://github.com/vim/vim/releases/tag/v8.2.2090)  Vim9: dict does not accept a key in quotes

**Comment by itchyny** [comment]
Thank you for listing the related commits. Closing the issue.
Thank you all for discussion and Bram for accepting the spec changes.

**Comment by lacygoill** [comment]
Should we give a specific error for when using the old syntax `#{}`?  If we allow `#{` as the start of a comment, Vim can give a confusing error message.  For example:
```vim
vim9script
def Popup(): string
    popup_create('', #{})
    return ''
enddef
defcompile
```
    E1001: Variable not found: return

I understand the error, but it still looks weird the first time you read it.  A better error would be:

    E1234: "#{" cannot be used in Vim9 script to create literal dictionary

I would argue that it will be more frequent for people to wrongly use the deprecate literal dictionary syntax (for example after copying some legacy code) then to try to write a comment starting with `{`.  And fixing this kind of issue will be harder than it could be if the error message is not as obvious as possible.

**Comment by lacygoill** [comment]
> I would argue that it will be more frequent for people to wrongly use the deprecate literal dictionary syntax (for example after copying some legacy code) then to try to write a comment starting with {.

I mean a comment starting with `{` is certainly possible, but you should use a space between the comment leader and the text for better readability:

    # { some comment
     ^

**Comment by brammool** [comment]
> Should we give a specific error for when using the old syntax `#{}`?
> If we allow `#{` as the start of a comment, Vim can give a confusing
> error message.  For example:
> ```vim
> vim9script
> def Popup(): string
>     popup_create('', #{})
>     return ''
> enddef
> defcompile
> ```
>     E1001: Variable not found: return
> 
> I understand the error, but it still looks weird the first time you
> read it.  A better error would be:
> 
>     E1234: "#{" cannot be used in Vim9 script to create literal dictionary
> 
> I would argue that it will be more frequent for people to wrongly use
> the deprecate literal dictionary syntax (for example after copying
> some legacy code) then to try to write a comment starting with `{`.
> And fixing this kind of issue will be harder than it could be if the
> error message is not as obvious as possible.

Yeah, this can be confusing.  Previously we detected #{ and did not
handle it as a comment.  That check was removed, but now we may get the
problem you found.  Instead of removing the check for #{ we can turn it
into an error.

-- 
A radioactive cat has eighteen half-lives.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
