### ISSUE TITLE
Vim9 causes SEGV on calling function with duplicate name in a map()

### ISSUE THREAD

**Issue by itchyny** [vim/vim#7313]
**Describe the bug**
Vim9 causes SEGV on calling the argument functions in a map().

**To Reproduce**
Loading following script causes SEGV.
```
vim9script
def F(): list<number>
  var xs: list<func: number> = [{ -> 42}]
  # return xs->map({_, G -> G()}) # this works
  return xs->map({_, F -> F()}) # SEGV
enddef
echo F()
```

**Expected behavior**
Prints `[42]` with no error. It seems that using the same name causes the function lookup broken.

In addition to the above issue, following script causes error `E117: Unknown function: [unknown]` but should be `expected func but got a number` or something.
```
vim9script
def F(): list<number>
  var xs: list<number> = [0]
  return xs->map({_, G -> G()})
enddef
echo F()
```

**Screenshots**
If applicable, copy/paste the text or add screenshots to help explain your problem.

**Environment (please complete the following information):**
 - Vim version: 8.2.1992
 - OS: macOS 10.15.7
 - Terminal: iTerm2

**Additional context**

**Comment by lacygoill** [comment]
- [backtrace](https://github.com/vim/vim/files/5548653/backtrace.gz)
- [valgrind log](https://github.com/vim/vim/files/5548654/valgrind.log)
- [asan log](https://github.com/vim/vim/files/5548652/asan.log)
