### ISSUE TITLE
Function to provide info on where a right click was made

### ISSUE THREAD

**Issue by damnskippy** [vim/vim#7318]
When `mousemodel` option is set to `popup` or `popup_setpos`, right mouse buttons pops up a menu, and additionally cursor is moved to the clicked position in the case of `popup_setpos`.  However, when there is a mapping by way of `:map <RightMouse> {rhs}` the mapping overrides the `mousemodel` option and cursor is no longer moved (nor the popup menu is shown).  This is probably functions as designed but the user has lost the `mousemodel` option it seems and also there is no way for user to know where the right click was made even if the user wanted to move the cursor in their mapped action.

A use case would be if the user wants to perform some actions (like looking up a tag) on a word or a tag that is right clicked on.  Currently to do this, they would have first click on the word to move the cursor to the word and then right click to invoke their mapping.

To solve the above, if there is a function to know where (cursor position) the right click was made that the user can query it would help move the cursor and perform any actions they may want to.  I think it seems not viable, or somewhat doesn't even make sense, to honor both `mousemodel` option and a user mapping to right click at the same time; but a good middle option seems to be if there is way to emulate the `setpos` functionality when right clicking while at the same time map to an action, that would be very helpful.

This request is primarily based on usage in terminal vim, but probably applies to gui vim also.

Thanks.

**Comment by andymass** [comment]
Not sure if this is specific to a terminal or configuration but this seems to work for me;

    map <RightMouse> :call getchar()\|echo 'mouse' v:mouse_col v:mouse_lnum v:mouse_winid v:mouse_win getmousepos()<cr>

**Comment by damnskippy** [comment]
Your suggestion works perfectly fine - thanks so much.
