### ISSUE TITLE
Vim9: conditional return statement causes E1028 error

### ISSUE THREAD

**Issue by itchyny** [vim/vim#7319]
**Describe the bug**
Vim9 script fails to compile a function which has conditional statement.

**To Reproduce**
Loading the following script causes `E1028: Compiling :def function failed` error but I can't tell what's the actual problem.
```
vim9script
def F()
  if 1 < 0
    return
  endif
enddef
echo F()
```

**Expected behavior**
I believe this is a valid Vim9 script and echos 0 with no error.

**Screenshots**
If applicable, copy/paste the text or add screenshots to help explain your problem.

**Environment (please complete the following information):**
 - Vim version 8.2.2000
 - OS: macOS 10.15.7
 - Terminal: iTerm2

**Additional context**

**Comment by itchyny** [comment]
I noticed another case which causes SEGV with 8.2.2000. I believe this script is also valid.
```
vim9script
def F(): number
  if 1 < 0
    return 0
  endif
  return 1
enddef
echo F()
```

**Comment by lacygoill** [comment]
> I noticed another case which causes SEGV with 8.2.2000.

- [backtrace](https://github.com/vim/vim/files/5553616/backtrace.txt)
- [valgrind log](https://github.com/vim/vim/files/5553617/valgrind.log)
- [asan log](https://github.com/vim/vim/files/5553614/asan.log)

**Comment by brammool** [comment]
> **Describe the bug**
> Vim9 script fails to compile a function which has conditional statement.
> 
> **To Reproduce**
> Loading the following script causes `E1028: Compiling :def function failed` error but I can't tell what's the actual problem.
> ```
> vim9script
> def F()
>   if 1 < 0
>     return
>   endif
> enddef
> echo F()
> ```
> 
> **Expected behavior**
> I believe this is a valid Vim9 script and echos 0 with no error.

Interesingly, it works if the "1" is replaced by a global:

```
vim9script
g:one = 1
def Test()
  if g:one < 0
    return
  endif
enddef
```

Thus it's related to evaluating the condition at compile time.

-- 
There is a fine line between courage and foolishness.
Unfortunately, it's not a fence.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
