### ISSUE TITLE
Passing a pattern to `:sort` does not respect the 'smartcase' setting

### ISSUE THREAD

**Issue by filbranden** [vim/vim#7322]
**Describe the bug**

The `:sort` command takes an optional pattern to skip parts of a line when sorting.

That pattern does respect `'ignorecase'`, so that when `'ignorecase'` is set, it will skip both lowercase and uppercase versions of the pattern.

But it doesn't seem to respect `'smartcase'`, in that if both `set ic scs` are in effect, if the pattern includes an uppercase letter, it will skip both uppercase and lowercase (as if only `'ignorecase'` was in effect.)

**To Reproduce**

 1. Open Vim and create a buffer with these contents:

```
Alabama
alabastra
Alachua
alacrity
Aladdin
alagarto
Adam
adroit
bump
zebra
```

 2. Enable both `'ignorecase'` and `'smartcase'`:

```
set ic scs
```

 3. Sort, skipping pattern `/Ala/`:

```
:sort /Ala/
```

The buffer will be sorted, but same as if the pattern passed was `/ala/`, following `'ignorecase'`, but not respecting the behavior of `'smartcase'`. The results will be as follows:

```
Adam
adroit
bump
zebra
Alabama
alabastra
Alachua
alacrity
Aladdin
alagarto
```

**Expected behavior**

I would have expected the `/Ala/` pattern to have triggered the case-insensitive of `'smartcase'` and sorted the entries as follows:

```
alabastra
alacrity
alagarto
Adam
adroit
bump
zebra
Alabama
Alachua
Aladdin
``` 

**Environment (please complete the following information):**
 - Vim version: 8.2.1885
 - OS: Linux, Fedora 32
 - Terminal: GNOME Terminal 3.36.2

**Comment by gdupras** [comment]
Some other commands use  `'ignorecase'` but ignore `'smartcase'`. This behavior is documented for at least the following: `*`, `:vimgrep`, `match()`, `substitute()`, in their respective `:help` entry.

I suppose the easiest "fix" would be to mention in `:help :sort` that` 'smartcase`' is ignored.

**Comment by filbranden** [comment]
I do get it for `match()` and `substitute()` where backwards compatibility is important... But I don't really see why `:vimgrep` and `:sort` would ignore that...

I agree that, if this is indeed the intended behavior, then an update to the documentation to explicitly list it as such would be the proper fix.

**Comment by brammool** [comment]
Changing this now might break some things, and I can't see if the current behavior is right or wrong.  In cases like this it's better to not change it.  I'll update the help to mention 'ignorecase' and not using 'smartcase'.
