### ISSUE TITLE
Vim9: misleading error when executing string where colon not written before "*" range

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7335]
**Describe the bug**

In Vim9 script, a misleading error is raised when executing a string containing the `*` range, if the latter is not prefixed by a colon.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -i NONE -S <(cat <<'EOF'
        vim9script
        @s = 'blah'
        def Func()
            exe ':keepp *s/pat/rep/'
        enddef
        Func()
    EOF
    )

`E492` is raised at runtime:

    E492: Not an editor command: blah

**Expected behavior**

`E1050` is raised at compile time:

    E1050: Colon required before a range

**Environment**

 - Vim version: 8.2 Included patches: 1-2018
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(362)

**Additional context**

Without `:exe`, `E1050` is correctly raised at compile time:
```vim
vim9script
@s = 'blah'
def Func()
    :keepp *s/pat/rep/
enddef
defcompile
```
    E1050: Colon required before a range

Same thing if the `*` range is replaced with another range:
```vim
vim9script
@s = 'blah'
def Func()
    exe ':keepp 123s/pat/rep/'
enddef
Func()
```
    E1050: Colon required before a range

**Comment by lacygoill** [comment]
The original example can be simplified into this:
```vim
vim9script
@s = 'blah'
exe '*s/pat/rep/'
```
Not sure why the `:substitute` command is parsed as the `"s` register.

**Comment by lacygoill** [comment]
It's working as intended.  I didn't know that `*` could be used as a replacement for `@` to execute the contents of a register.  Sorry for the noise.

**Comment by lacygoill** [comment]
Although, it's a bit weird that `*` is parsed as an Ex command (instead of a range or maybe an arithmetic operator):
```vim
vim9script
@s = 'string'
exe '*s'
```
    E492: Not an editor command: string

Because according to `:h :*`, that should only be the case when the `*` flag is in `'cpo'`:

    Note that the ":*" command is only recognized when the
    '*' flag is present in 'cpoptions'.  This is NOT the
    default when 'nocompatible' is used.

Which is *not* the case in a Vim9 script, according to `:h :vim9`:

    A side effect of `:vim9script` is that the 'cpoptions' option is set to the
    Vim default value, like with: >
            :set cpo&vim

And `:h 'cpo`:

    'cpoptions' 'cpo'   string  (Vim default: "aABceFs",

I guess that `:exe` supersedes some logic here, and forces Vim to parse `*` as an Ex command...

**Comment by brammool** [comment]
See ":help :*", it's an old Vi command to execute the contents of a register.  Has nothing to do with :substitute

**Comment by brammool** [comment]
Oh, about using ":*" as the star command, even though '*' is not in 'cpoptions':  Well, the colon before a range is missing, thus it could not have the meaning of the Visual area.  Should this be an error?
