### ISSUE TITLE
Vim9: strict white space check is not developer friendly

### ISSUE THREAD

**Issue by itchyny** [vim/vim#7338]
## Problems
Currently (v8.2.2029), Vim9 checks white spaces strictly. It enforces white
space everywhere; around binary operators, assignment operators, function
arguments, dictionary keys and comment symbol. However, this smells like an
ancient language and is frustration for me. Most modern languages have lexers
and skips white spaces while scanning the source code (indentations are
exception; I couldn't find a language confiders spaces between tokens, maybe
TeX is one of them, but legacy language anyway). Enforcing white spaces is
not developer friendly and cannot be considered as a modern language IMO.

Some languages have linters or formatters which defines the number of white
spaces, but in language specification, white spaces are optional between tokens.
Some language formatters prefers omitting spaces due to precedence; `a*b + c*d`.
Some people like spaces all the way, and others don't. Formatters often suggest
the standard style for that language, but they _fix_ valid code to valid code.

## Specification changes suggestion
- Allow omitting white spaces around binary operators (`+`, `-`, `..`, `*`, `/`,
  `%`, `==`, `==#`, `>`, `=~`, etc) and assignment operators (`=`, `+=`, `..=`,
  `=<<` etc).
- Allow omitting white spaces after commas in function arguments (both `:def`
  and `:call`), arrays and dictionaries.
- Keep enforcing spaces after `:` in dictionaries and around `#` for comments.
  - `:` conflicts with scopes and `#` conflicts with autoload function names.

**Comment by brammool** [comment]
White space is very useful to make it easy to read back code.  Many projects enforce usage of white space with linters and other tools.  This has nothing to do with lexers.  In fact, very old languages such as C did not enforce white space, leading to obfuscated code contests.

We don't have a separate tool to check the format of Vim script, and including the checks in the interpreter works well.  We can debate over where exactly white space should be optional, but this very quickly becomes a personal preference. And it depends on what code you are writing.  I have seen enough ugly Vim script that I tend to want more white space.  And I like that when the script runs it means it won't be too ugly.

Using single character variables seems uncommon, your example of "a*b + c*d" is not something I often see in Vim script.  When we would allow this we would also allow "somename*somelist[index]+verylongname*thedict.member" and you can see that doesn't read easily.  If you want to indicate precedence you can add parens or use double spacing, but I already find "a * b + c * d" quite readable.

**Comment by itchyny** [comment]
I agree your opinion about code without spaces been ugly, but I don't argue about readability. I don't say `a*b + c*d` is often appears in Vim script; I also think it's uncommon. But some language formatters prefers this style and thus some people like this style. Considering rejecting ugly code, why <pre>1     +     1</pre> is not rejected? Such using too many spaces is ugly, uncommon, quite unreadable.
Making a code readable for humans and writing a code for interpreters/compilers are totally different things. And there are common understandings in most programmers on how modern language parsers handles white spaces. Language parser checking white spaces strictly is surprising for many programmers including me. Making a code readable is a task for linters and formatters, not enforced by parsers.

**Comment by mawkish** [comment]
I second this. I came here to complain about Vim9 requiring me to put no whitespace between my function names and their parameter lists. I like `def Func ()` over `def Func()`. I'm in the minority there, I know.

I'm not fussed about being able to write, eg, `2*2`, but that's because I don't. It's `whatever = 2 + this_func (etc)` all day for me.  But I do think you should be allowed to if you want to. Otherwise people like me will end up having to join their parameter lists to their function names, as if they were tasteless mathematicians!

**Comment by itchyny** [comment]
This is a slightly old thread and closed due to no response from Bram, but recently I've seen some complaint on this topic in Japanese Vim community so reopened. If anyone agree on making white spaces in Vim9 script optional, please comment below with reasonable explanation. Thank.
