### ISSUE TITLE
There are no entries for "<Cmd>" and ":map-cmd" in doc/tags

### ISSUE THREAD

**Issue by lkintact** [vim/vim#7340]
Perhaps there's nothing to add to the issue title.

Vim 8.2.2022.

**Comment by brammool** [comment]
https://github.com/vim/vim/blob/master/runtime/doc/tags#L3511
https://github.com/vim/vim/blob/master/runtime/doc/tags#L2728

**Comment by lkintact** [comment]
@brammool Sorry, since 8.2.2022 is the latest release at https://github.com/vim/vim-win32-installer/releases, I thought that's where I'd find the most up-to-date doc/tags. Completely forgot about the existence of the source code at https://github.com/vim/vim/ ...
