### ISSUE TITLE
vim9: for [k, v] in items(dict) not work in def-function

### ISSUE THREAD

**Issue by alexaschee** [vim/vim#7345]
**Describe the bug**
`for [k, v] in items(dict)`  not work in def-function

**To Reproduce**

    vim9script
    var dic = {tag: 'div', id: 'form'}

    def Dict_items(dic: dict<string>)
        for [k, v] in items(dic) # E690: Missing "in" after :for
            echo k .. " : " .. v
        endfor

        for it in items(dic)  #  works
            echo it[0] .. " : " .. it[1]
        endfor
    enddef

    Dict_items(dic)

    for [k, v] in items(dic)  #  works
        echo k .. " : " .. v
    endfor

**Environment (please complete the following information):**
 - Vim version 8.2.2030
 - OS: Windows 10

**Comment by lacygoill** [comment]
Relevant todo item:

https://github.com/vim/vim/blob/6abdcf82859e158713a3d5aa6b1012748ea5c2a0/runtime/doc/todo.txt#L90
