### ISSUE TITLE
oldfiles not updated when saving buffer under certain conditions

### ISSUE THREAD

**Issue by kiil** [vim/vim#7348]
**Describe the bug**

**When** Vim is opened, something is written in the editor and the buffer saved to a file by issuing the command ':w some-file-name.txt' and Vim is quit again

**Then** some-file-name.txt is not in oldfiles the next time Vim is opened.

**To Reproduce**

Open vim

Then press 'i' to start writing.

Then save the buffer and give the file a name by issuing the command ':w some-file-name.txt'

Then quit vim by :x

Then open vim again and observe oldfiles missing some-file-name.txt

**Expected behavior**
some-file-name.txt in oldfiles when vim is opened again

**Environment (please complete the following information):**
VIM - Vi IMproved 8.2 (2019 Dec 12, kompileret Nov 4 2020 11:27:02) macOS-version Rettelser som er med: 1-1950 Kompileret af Homebrew

And

MacVim, this version: Custom Version 8.2.1719 (166)

**See also**
https://vi.stackexchange.com/questions/28097/why-is-oldfiles-not-listing-last-edited-file

**Comment by chrisbra** [comment]
I created https://github.com/vim/vim/pull/7350 to fix this

**Comment by lacygoill** [comment]
Probably fixed by [8.2.2039](https://github.com/vim/vim/commit/8e6be34338f13a6a625f19bcef82019c9adc65f2).

**Comment by k-takata** [comment]
Closing then.
