### ISSUE TITLE
Wrong highlighting in contained transparent syn-region

### ISSUE THREAD

**Issue by aGHz** [vim/vim#7349]
**Describe the bug**
If a `contained` `transparent` region would extend the containing region past its `end` match, the highlighting is broken between the skipped end of the containing region and the end of the contained region.

**To Reproduce**
```vim
syn region testInner start=/S/ end=/E/ contained transparent
syn region testOuter start=/s/ end=/e/ contains=testInner
```

```
===s---S~~~S~~~e???E~~~E---e===
```

The sequence `???E` renders in the color of whatever is underneath `testOuter` on the stack. Adding a `matchgroup` to the `testOuter` `end` match doesn't highlight the contained `e`, and inspecting the synstack shows it's correct so the problem is probably with deciding the color of the transparent region, not with establishing the regions.

Note that adding a `matchgroup` to `testOuter` or otherwise altering its `re` and `he` is consistently reflected in the highlighting of the contained region, e.g. `end=/e/me=e+2,re=e+2,he=e+2` will correctly highlight `e??` but continue to fail for the subsequent `?E`.

**Expected behavior**
The sequence `???E` above should render in the color of `testOuter`.

**Full test script**

```vim
" Run with :so %
syn clear
set ft=vim

syn region TEST start=/X/ end=/$/ oneline keepend contained containedin=vim.*Comment.*
hi TEST ctermfg=DarkGray

"X ===s---S~~~S~~~e???E~~~E---e===
"X ===s---T~~~T~~~e~~~F~~~F---e===

syn region testInner1 start=/S/ end=/E/ contained transparent
syn region testInner2 start=/T/ end=/F/ contained contains=testInner2
syn region testOuter start=/s/ matchgroup=testRed end=/e/
  \ contained containedin=TEST
  \ contains=testInner1,testInner2

hi testInner2 ctermfg=Yellow
hi testOuter ctermfg=Blue
hi testRed ctermfg=Red

function! s:getSyntax(line, col)
  return string(a:line) .. ',' .. string(a:col) .. ' ' .. getline(a:line)[a:col - 1] .. ': '
    \ .. synIDattr(synID(a:line, a:col, 1), "name")
    \ .. ' - '
    \ .. join(map(synstack(a:line, a:col), 'synIDattr(v:val, "name")'), ',')
endfunction

for s:i in range(18,24)
    echo s:getSyntax(8, s:i)
endfor
```

Output:

```
8,18 ~: testOuter - vimLineComment,TEST,testOuter,testInner1,testInner1
8,19 e: TEST      - vimLineComment,TEST,testOuter,testInner1,testInner1
8,20 ?: TEST      - vimLineComment,TEST,testOuter,testInner1,testInner1
8,21 ?: TEST      - vimLineComment,TEST,testOuter,testInner1,testInner1
8,22 ?: TEST      - vimLineComment,TEST,testOuter,testInner1,testInner1
8,23 E: TEST      - vimLineComment,TEST,testOuter,testInner1,testInner1
8,24 ~: testOuter - vimLineComment,TEST,testOuter,testInner1
```

**Screenshots**

![image](https://user-images.githubusercontent.com/623725/99944611-2ada3600-2d41-11eb-92b0-769588afd855.png)
![image](https://user-images.githubusercontent.com/623725/99945906-7beb2980-2d43-11eb-8839-d04fb204fddf.png)

**Environment**
 - Vim 8.2.2018

**Comment by aGHz** [comment]
I traced the issue to [these two lines in `update_si_attr`](https://github.com/vim/vim/blob/v8.2.2054/src/syntax.c#L2609-L2610). Paraphrased:

```c
if ((spp->sp_flags & HL_TRANSP) && !(sip->si_flags & HL_MATCH)) {
  sip->si_h_startpos = CUR_STATE(idx - 1).si_h_startpos;
  sip->si_h_endpos = CUR_STATE(idx - 1).si_h_endpos;
}
```

I don't understand the purpose of making the highlight region of a transparent region the same as its container's. I tried to look it up, but the change was introduced in a [large commit from 2004 for vim 7.0021](https://github.com/vim/vim/commit/293ee4d421#diff-c38028a016955e04232a68fa2863907dc239587026ffde38e64075241abdde67), and there's no context around it.

Removing these two lines solves this issue and a few more cases I could think of, but I'm worried I might be missing something.

@brammool, do you have any guidance on this? Should I open a PR to remove them and add some test cases around it?

**Comment by brammool** [comment]
I haven't looked at this code for a long time.  I don't know what the purpose is of those two lines, that get the start and end of the outer match.
You could make a test that shows the problem and passes after removing the lines, and create a pull request with that.
And check that the change doesn't break something.

**Comment by aGHz** [comment]
While writing tests, I found the case that most likely prompted this logic. Could you please confirm: if a `syn match` without `keepend` contains a transparent region that extends the match past its `me`, the intent is to only extend the `me` and not the `he` of the match?

For example:

```vim
syn region B start=/(/ end=/)/ contained transparent
syn match A /ab.c/ contains=B
hi A ctermfg=green
```

How should `ab(c---)` be highlighted? Currently, `ab(c` is in green, and the remaining `---)` in whatever color was underneath `A`. Is this the intended behaviour, or is the entire string meant to be green?

(edited last paragraph for clarity)

**Comment by brammool** [comment]
Adrian Ghizaru wrote:

> While writing tests, I found the case that most likely prompted this
> logic. Could you please confirm: if a `syn match` without `keepend`
> contains a transparent region that extends the match past its `me`,
> the intent is to only extend the `me` and not the `he` of the match?
> 
> For example:
> 
> ```vim
> syn region B start=/(/ end=/)/ contained transparent
> syn match A /ab.c/ contains=B
> hi A ctermfg=green
> ```
> 
> How should `ab(c---)` be highlighted? I'm guessing `ab(c` is in green,
> and the remaining `---)` in whatever color was underneath `A`? Or is
> the entire string meant to be green?

Hmm, I would think that when A continues because of the B region, since
that is transparent the highlighting of A would show, but it doesn't.

When changing A to a region:

	syn region A start=/a/ end=/c/ contains=B

The same happens, but when B ends (and A continues further) it's clear
that "transparent" wasn't applied.  I think it should, since
"transparent" means the highlighting from below it is displayed.



-- 
Vim is like Emacs without all the typing.  (John "Johann" Spetz)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by aGHz** [comment]
That was my intuition too. I wanted to first check that nobody's relying on the current behaviour though, so I wrote [a quick script](https://gist.github.com/aGHz/5e7091d07442ec6e72731813576a6f77) to parse `runtime/syntax/*.vim`, resolve cluster references and check for matches that contain transparent regions:

```raw
ada.vim: match adaStructure contains transparent region adaRecord
ada.vim: match adaStructure contains transparent region adaRecord
ada.vim: match adaKeyword contains transparent region adaRecord
ada.vim: match adaBegin contains transparent region adaFunction
ada.vim: match adaBegin contains transparent region adaProcedure
ada.vim: match adaBegin contains transparent region adaPackage
freebasic.vim: match freebasicMathOperator contains transparent region freebasicParen
hog.vim: match HogFileType contains transparent region HogFileFROP
ibasic.vim: match ibasicMathOperator contains transparent region ibasicParen
make.vim: match makeTarget contains transparent region makeSpecTarget
nasm.vim: match nasmInMacMemRef contains transparent region nasmInMacPreConDef
nasm.vim: match nasmInMacMemRef contains transparent region nasmInMacStrucDef
nasm.vim: match nasmInMacMemRef contains transparent region nasmPreConditDef
nasm.vim: match nasmMemReference contains transparent region nasmInMacPreConDef
nasm.vim: match nasmMemReference contains transparent region nasmInMacStrucDef
nasm.vim: match nasmMemReference contains transparent region nasmPreConditDef
php.vim: match phpIdentifierSimply contains transparent region phpParent
pike.vim: match pikeWord contains transparent region pikeMlString
pike.vim: match pikeWord contains transparent region pikeNest
pike.vim: match pikeFirstWord contains transparent region pikePreCondit
pike.vim: match pikeFirstWord contains transparent region pikePreProc
vim.vim: match vimUserCmd contains transparent region vimEscapeBrace
```

I manually checked every one but `hog` and `pike`, trying to the best of my ability to get the contained region to expand the parent match. None of them seem to rely on the current behaviour of transparent highlighting.

I think it's safe to say nobody ran into this edge case before, so I'll prepare a PR this weekend to fix it and add some tests. We can then discuss there if the tests are sufficient or if I'm missing any case.
