### ISSUE TITLE
javascript: backtics as a string

### ISSUE THREAD

**Issue by Vanuan** [vim/vim#735]
Javascript syntax doesn't recognize backticks quotation as a string.

Example:

``` javascript
{
  string: `A string`
}
```

**Comment by chrisbra** [comment]
please discuss with the syntax script maintainer.

**Comment by Vanuan** [comment]
How can I contact him?

**Comment by k-takata** [comment]
Check the header of the file.
https://github.com/vim/vim/blob/master/runtime/syntax/javascript.vim#L1-L5
