### ISSUE TITLE
internal errors when undoing after sourcing broken Vim9 script on opening quickfix window

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7352]
**Describe the bug**

Undoing after sourcing a broken Vim9 script while opening the quickfix window might raise internal errors.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        let lines =<< trim END
            " comment
            def Foo(arg)
                try
                    Bar()
                endtry
            enddef
        END
        call writefile(lines, '/tmp/t.vim')
        sil e /tmp/t.vim
        vim /^def/ %
        pu=''
        au BufLeave * ++once source /tmp/t.vim
        call timer_start(0, {-> execute('set ma | undo')})
        sil! cw
    EOF
    )

`E440` is raised:

    E440: undo line missing

Press Enter to get the next message; `E438` is raised:

    E438: u_undo: line numbers wrong

`E438` and `E440` are internal errors.

**Expected behavior**

No internal error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-2033
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(362)

**Additional context**

Not sure whether they are related, but there are 2 other issues.

First, I don't understand why the contents of the file `/tmp/t.vim` is reset with the contents of the quickfix buffer.  It happens even without executing `:undo`:
```vim
let lines =<< trim END
    " comment
    def Foo(arg)
        try
            Bar()
        endtry
    enddef
END
call writefile(lines, '/tmp/t.vim')
sil e /tmp/t.vim
vim /^def/ %
pu=''
au BufLeave * ++once source /tmp/t.vim
sil! cw
```
It doesn't make sense.  After the file's contents is set with `writefile()`, there is no other command/function which alters the file, except for `pu=''` (but the latter does not alter the final contents).

Second, for the internal errors to be raised and the code to be fully automated, a timer is needed.  Otherwise, we need to execute `set ma | undo` manually.  That's because after `sil! cw`, nothing is executed.  This is unexpected for 2 reasons:

   - when an error is raised in a script, Vim does not abort the sourcing; it goes on sourcing the rest

```vim
unsilent echom 'one'
eval [][0]
unsilent echom 'two'
```
    one
    E684: list index out of range: 0
    two

   - even if Vim did abort on an error when sourcing a script, the error raised by `:cw` is suppressed by `:sil!`

```vim
unsilent echom 'one'
sil! eval [][0]
unsilent echom 'two'
```
    one
    two

---

- [backtrace](https://github.com/vim/vim/files/5582548/backtrace.txt)

**Comment by brammool** [comment]
This is indeed weird.  A minimal script to get E440:
```
let lines =<< trim END
    " comment
    def Foo(arg)
	try
	    Bar()
	endtry
    enddef
END
call writefile(lines, '/tmp/t.vim')
split /tmp/t.vim
vim /^def/ %
normal o
au BufLeave * ++once source /tmp/t.vim
silent! cwindow

```
And then type any character.  Any simplification appears to avoid the undo problem.
