### ISSUE TITLE
netrw not loading FileType options from .vimrc

### ISSUE THREAD

**Issue by aheath1992** [vim/vim#7353]
**Describe the bug**
When using netrw to view my file directory, if I open a file (i.e. a Yml file for Ansible), it does not load my autocmd FileType configs for YAML.Netrw sees that the file is YAML. When I open the file with `vim example.yml` all the configs load correctly.

The best example of this is the use of `cursorline` & `cursorcolumn` with the YAML configuration:
`autocmd FileType yaml set cursorline`
`autocmd FileType yaml set cursorcolumn`

**To Reproduce**
1. Run `vim`
2. Enter Command `:Explore`
3. Select and Open a YAML file
4. See if `autocmd FileType yaml set...` options have applied.

**Expected behavior**
When opening a file from the netrw file tree I would expect that it loads the appropriate FileType config for the files that are being opened via the netrw file tree.

**Screenshots**
netrw configuration.
```
" File Browsing:
let g:netrw_banner = 0 
let g:netrw_browse_split = 2 
let g:netrw_winsize = 75
let g:netrw_altv = 1 
let g:netrw_liststyle = 3 
let g:newrw_list_hide = netrw_gitignore#Hide()
let g:netrw_list_hide = ',\(^\|\s\s\)\zs\.\S\+'
```
Filetype configurations
```
augroup filetypegroup
   autocmd!
   autocmd FileType text setlocal wrap
   autocmd FileType text setlocal linebreak
   autocmd FileType text setlocal spell
   autocmd FileType text setlocal spelllang=en_us
   autocmd FileType text setlocal formatoptions=1
   autocmd FileType text setlocal noexpandtab
   autocmd FileType text set textwidth=80
   autocmd FileType text nnoremap j gj
   autocmd FileType text nnoremap k gk
   autocmd FileType yaml setlocal ai
   autocmd FileType yaml setlocal ci
   autocmd FileType yaml setlocal ts=2
   autocmd FileType yaml setlocal sw=2
   autocmd FileType yaml setlocal et
   autocmd FileType yaml set cursorline
   autocmd FileType yaml set cursorcolumn
   autocmd FileType python setlocal foldenable 
   autocmd FileType python setlocal foldmethod=indent
   autocmd FileType python setlocal foldlevel=99
   autocmd FileType python setlocal tabstop=4
   autocmd FileType python setlocal softtabstop=4
   autocmd FileType python setlocal shiftwidth=4
   autocmd FileType python setlocal expandtab
   autocmd FileType python setlocal autoindent
   autocmd FileType python setlocal copyindent
   autocmd FileType python setlocal fileformat=unix
   autocmd FileType python setlocal encoding=utf-8
   autocmd FileType python let python_highlight_all=1
augroup END
```
**Environment (please complete the following information):**
- Vim version: 8.2
- OS: Fedora 33
- Terminal: Terminator

**Comment by cecamp** [comment]
AFAIK, the group should be `filetypedetect`, not `filetypegroup`. Also, these settings should probably be done in a `ftplugin/yaml.vim` file, not in a file devoted to filetype detection.  That said, I've modified netrw to make a filetype detection in additional place and it appears to make the requested settings. See [my website](http://www.drchip.org/astronaut/vim/index.html#NETRW) for the updated version 171d.

**Comment by aheath1992** [comment]
@cecamp I have updated my vimrc and broke down the filetypes to the appropriate ftplugin files, thank you for that suggestion.  My question now is when will the 171d update make its way into the main branch and get pushed out?

**Comment by cecamp** [comment]
I've got a bug in netrw that I found (leaving "No Name" buffers around) and am working on removing. Given that its Thanksgiving week it might be a bit.
