### ISSUE TITLE
Terminal buffer deleted when hidden

### ISSUE THREAD

**Issue by noscript** [vim/vim#7358]
**Describe the bug**
Terminal buffer is deleted when hidden.

**To Reproduce**
1. Run vim
```
vim -g -u NONE +'set nohidden bufhidden=hide' +'term echo hello' +'only'
```
2. List buffers `:ls!`
```
  1 #h   "[No Name]"                    line 1
  2 %aF  "!echo hello [finished]"       line 1   
```
3. Create a new buffer `:edit new_buffer`
4. List buffers again `:ls!`
```
  1  h   "[No Name]"                    line 1
  3 %a   "new_buffer"                   line 1    
```
Terminal buffer is no longer there.
5. Try to force go to terminal buffer `:b2`
```
E86: Buffer 2 does not exist
```

**Expected behavior**
Terminal buffer is not deleted.

**Environment:**
 - Vim version: 8.2.2019
 - OS:  Ubuntu 20.04
 - Terminal: GUI

**Comment by brammool** [comment]
You need to set 'bufhidden' after opening the terminal, it's not copied from the global value.
But even then the problem still happens, 'bufhidden' is not used.
