### ISSUE TITLE
":h options-in-terminal" could be improved

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7362]
The help at `:h options-in-terminal` could be improved:

https://github.com/vim/vim/blob/a09bee322e605c8a076fa23c3d3259495a1129d2/runtime/doc/terminal.txt#L124-L131

Using `TerminalWinOpen` instead of `TerminalOpen` would simplify the autocmd:

    au TerminalOpen * if &buftype == 'terminal' | setlocal bufhidden=hide | endif

    →

    au TerminalWinOpen * setlocal bufhidden=hide

And make the explanation about `<abuf>` unnecessary.

As a suggestion, here is a patch:
```diff
diff --git a/runtime/doc/terminal.txt b/runtime/doc/terminal.txt
index 1d751c37b..e9751e90f 100644
--- a/runtime/doc/terminal.txt
+++ b/runtime/doc/terminal.txt
@@ -123,12 +123,9 @@ use |:tlmenu| instead of |:tmenu|.
 
 							*options-in-terminal*
 After opening the terminal window and setting 'buftype' to "terminal" the
-TerminalOpen autocommand event is triggered.  This makes it possible to set
+TerminalWinOpen autocommand event is triggered.  This makes it possible to set
 options specifically for the window and buffer.  Example: >
-   au TerminalOpen * if &buftype == 'terminal' | setlocal bufhidden=hide | endif
-The <abuf> is set to the terminal buffer, but if there is no window (hidden
-terminal) then setting options will happen in the wrong buffer, therefore the
-check for &buftype in the example.
+   au TerminalWinOpen * setlocal bufhidden=hide
 
 Mouse events (click and drag) are passed to the terminal.  Mouse move events
 are only passed when Vim itself is receiving them.  For a terminal that is
```

**Comment by brammool** [comment]
> The help at `:h options-in-terminal` could be improved:
> 
> https://github.com/vim/vim/blob/a09bee322e605c8a076fa23c3d3259495a1129d2/runtime/doc/terminal.txt#L124-L131
> 
> Using `TerminalWinOpen` instead of `TerminalOpen` would simplify the autocmd:
> 
>     au TerminalOpen * if &buftype == 'terminal' | setlocal bufhidden=hide | endif
> 
>     →
> 
>     au TerminalWinOpen * setlocal bufhidden=hide
> 
> And make the explanation about `<abuf>` unnecessary.
> 
> As a suggestion, here is a patch:

Thanks.  I think the info about <abuf> is still useful, but secondary.
This should be easier to understand:

							*options-in-terminal*
After opening the terminal window and setting 'buftype' to "terminal" the
|TerminalWinOpen| autocommand event is triggered.  This makes it possible to set
options specifically for the terminal window and buffer.  Example: >
   au TerminalWinOpen * setlocal bufhidden=hide

There is also the |TerminalOpen| event, but this may be triggered for a hidden
terminal, and the current window and buffer may not be for the new terminal.
You need to use <abuf>, which is set to the terminal buffer.


-- 
Veni, Vidi, Video -- I came, I saw, I taped what I saw.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
In that case, another example might be useful to illustrate how to use `<abuf>` to set an option in a hidden terminal buffer:

    au TerminalOpen * call setbufvar(+expand('<abuf>'), '&colorcolumn', 123)

The `+` in `+expand()` is to cast the string into a number, because `setbufvar()` handles its first argument like `bufname()`, and the latter handles a string as a pattern.

And to be complete, maybe we should add a note about a terminal in a popup.  In a popup, all local options are set to some default values, as documented at `:h popup-buffer`.  To override this, the user might want to delay the call, possibly with a one-shot autocmd listening to `SafeState`:

    au TerminalOpen * au SafeState * ++once call setbufvar(+expand('<abuf>'), '&colorcolumn', 123)

Edit: `'colorcolumn'` was a bad example because it's a window-local option.  A buffer-local option would have been better.
