### ISSUE TITLE
Add autocommand events TerminalLeave

### ISSUE THREAD

**Issue by ZhiyuanLck** [vim/vim#7363]
The problem is that I can not find a way to obtain the current mode before key `<c-\><c-n>` takes effect in terminal mode.

I want to restore the pos of cursor in terminal when reloading it in a popup:
 - If the mode was terminal when terminal popup is closed, feed 'a' to terminal when reopen it in popup
 - If the mode was normal before, record the pos of cursor before closing the popup and restore the pos when repoen the terminal in popup.

Cause actions such as recording modes, closing popup and restoring positions are done in functions, which means I need return from terminal mode to normal mode first by `<c-\><c-n>` and then call functions. If I perform record action in function, then I will alway get `n` through `mode()`.

So if it possible to add autocommands like `InsertLeave` and `InsertLeavepre` or there is some other way I do not know to handle such case.

**Comment by lacygoill** [comment]
> So if it possible to add autocommands like InsertLeave and InsertLeavepre

Relevant todo item:

https://github.com/vim/vim/blob/a09bee322e605c8a076fa23c3d3259495a1129d2/runtime/doc/todo.txt#L899-L900

> or there is some other way I do not know to handle such case.

> Cause actions such as recording modes, closing popup and restoring positions are done in functions, which means I need return from terminal mode to normal mode first by <c-\><c-n> and then call functions. If I perform record action in function, then I will alway get n through mode().

When calling your function, try to use the pseudo-key `<cmd>` (require patch [8.2.1978](https://github.com/vim/vim/releases/tag/v8.2.1978)):

    tnoremap <key> <c-\><c-n>:call MyFunc()<cr>
                   ^---------^
                        ✘

    tnoremap <key> <cmd>call MyFunc()<cr>
                   ^---^
                     ✔

Alternatively, you could try to emulate the `TermEnter` and `TermLeave` events by firing them manually via custom mappings.  That's what I do in [this gist](https://gist.github.com/lacygoill/0bfef0a2e70ac7015aaee56a670c124b).

**Comment by ZhiyuanLck** [comment]
> When calling your function, try to use the pseudo-key `<cmd>` (require patch [8.2.1978](https://github.com/vim/vim/releases/tag/v8.2.1978)):
> 
> ```
> tnoremap <key> <c-\><c-n>:call MyFunc()<cr>
>                ^---------^
>                     ✘
> 
> tnoremap <key> <cmd>call MyFunc()<cr>
>                ^---^
>                  ✔

It helps a lot! Thanks a lot.

**Comment by lacygoill** [comment]
Glad it helps.  Note that there is already a bug report currently open which asks for a `TermLeave` event: https://github.com/vim/vim/issues/2487
