### ISSUE TITLE
Vim9: E1050 error occurred while executing edit command with "+{num}"

### ISSUE THREAD

**Issue by rbtnn** [vim/vim#7364]
**Describe the bug**
E1050 error occurred while executing following script:

```
vim9script
edit +4 %
```

![image](https://user-images.githubusercontent.com/1595779/100187945-84528880-2f2c-11eb-835c-59a4ab923275.png)

**Expected behavior**
No error occurred

**Environment (please complete the following information):**
 - Vim version 8.2.2039

**Comment by brammool** [comment]
Strictly speaking this is correct.  You should use "edit +:4 %".

I can understand that this is unexpected.  We could make an exception for when the "+" is only followed by a number.
But what if using "edit +$ %"?
Assuming that the command is not an assignment or a function call without "call" I suppose we can just omit the error.
