### ISSUE TITLE
C-Syntax Highlighting: Compound literals in some expressions are falsely highlighted as errors.

### ISSUE THREAD

**Issue by bwagner** [vim/vim#7366]
C-Syntax Highlighting: Compound literals in some expressions are falsely highlighted as errors.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean` (or `gvim --clean`)
2. Edit `tst.c` source see below
3. Valid C-Syntax is highlighted as erroneous.

**Source File tst.c**
```C
#include <stdio.h>

int func(int index) {
   return (int[]){1, 2, 3, 4, 5}[index];
}
 
int main() {

  int mode = func(2);

  if(!(int[]){
    1,
    2,
  }[mode == 3]) {
    return;
  }

  printf("%d\n", 
     (int[]){1,2,3,4,5}[2]);
  return 0;
}
```

**Expected behavior**
The syntax to be highlighted like normal syntax.

**Screenshots**
Find Screenshots attached for gvim 8.2 on MS Windows and vim 8.2 on Linux

**Environment:**
 - Vim version (Linux)
   8.2 (2019 Dec 12, compiled Apr 27 2020 17:31:48)
   Included patches: 1-647
- Vim Version (Windows)
8.2 (2019 Dec 12, compiled Dec 15 2019 23:09:16)
MS-Windows 32-bit GUI version with OLE support
Included patches: 1-12
Compiled by appveyor@APPVYR-WIN
 - OS:
Microsoft Windows 10 Enterprise 10.0.17763 N/A Build 17763
and
Linux 2.6.5-7.155.29-default (very old, I know)
 - Terminal: [e.g. GNOME Terminal, mintty, iTerm2, tmux, GNU screen] (Use GUI if you use the GUI.)
Windows: use GUI
Linux: xterm  4.3.99.903(184)

**Additional context**
[Compound Literals](http://port70.net/%7Ensz/c/c11/n1570.html#6.5.2.5)
![Linux](https://user-images.githubusercontent.com/447049/100211563-93c1d980-2f0c-11eb-9297-f08014ad557e.PNG)
![Windows](https://user-images.githubusercontent.com/447049/100211568-945a7000-2f0c-11eb-9f5a-86b604bd2301.PNG)

**Comment by chrisbra** [comment]
please have a look at `:h ft-c-syntax` and use `:let c_no_curly_error=1` 

See also #406 and a couple of other duplicates: https://github.com/vim/vim/issues?q=is%3Aissue+c_no_curly_error
