### ISSUE TITLE
[v8.2.1967]: Can't go to older position in jump list

### ISSUE THREAD

**Issue by zbinlin** [vim/vim#7371]
**Describe the bug**
Unable to use `CTRL+o` jumping to older position.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean` (or `gvim --clean`, etc.)
2. Edit three files.
3. Use `CTRL+o` can't go back to first file, it is jumping between second file and last file.

**Expected behavior**
Cant go back to first file

**Environment (please complete the following information):**
 - Vim version: v8.2.1967

**Additional context**
I try to build v8.2.1966 for test, it is expect.

**Comment by brammool** [comment]
In step two "Edit three files" please say what commands you used exactly.
I don't see this problem when I use ":edit <name>" three times.

**Comment by zbinlin** [comment]
I'm so sorry!

I use `vim --clean file1` to open the first file, then run below code in vim:

```
:autocmd BufWinLeave * silent! mkview
:autocmd BufWinEnter * silent! loadview
```

then use `:edit file2`, `:edit file3` to adding other two files.

The issue seems to be about version v8.2.1967 and `:autocmd BufWinEnter * silent! loadview` setting.

**Comment by brammool** [comment]
OK, so it's because of the :balt command added in the session file by patch 8.2.1967.
:balt should not change the jumplist.

**Comment by zbinlin** [comment]
I found use `CTRL-O`  command, the will go back to older file, but run `:jumps` to print jumplist, the pointer always at last blank line.

```
:jumps
 jump line  col file/text
   4     1    0 appveyor.yml
   3     1    0 Makefile
   2     1    0 Filelist
   1     1    0 # Contributing to Vim
>
```
