### ISSUE TITLE
Cannot input ''/""

### ISSUE THREAD

**Issue by Firestar-Reimu** [vim/vim#7377]
cannot input ''/""

When I click the "/' button, it will crash like this:

![Screenshot_20201126_202537](https://user-images.githubusercontent.com/65082432/100351288-2dc97500-3026-11eb-8b8f-7259074caba0.png)

 It is in **INSERT** mode, but `Esc` does not work, so do all the other buttons, and the cursor is on the last row.

It happens on both Linux Konsole and Windows Terminal.

Vim Version is Latest: 8.2

My `.vimrc` file：https://github.com/1900011604/Manjaro-KDE-Installation-on-Surface-Pro-6/blob/master/Vim%20%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

**Comment by chrisbra** [comment]
> When I click the "/' button, it will crash like this:

I don't understand. Are you using the mouse? Where is the `/` button? And I do not see a crash on your screenshot.

Please try to reproduce the issue with a minimal example, start from `vim --clean`. Also it is helpful to fill out the issue template.

**Comment by Firestar-Reimu** [comment]
No, I mean the **quote** button `' "` between `Enter` and `: ;`. I cannot type ' or " in vim and it will crash. I set the mouse as 'on'.

Sorry that / means 'or'

**Comment by chrisbra** [comment]
okay, please fill out the issue template. It only happens in terminal vim, right? What about gvim? What about other terminals (cmd), what about `vim --cmd`?  and what do you mean with crash?

**Comment by chrisbra** [comment]
does it happen in other terminal applications? e.g. in the powershell or cmd window?

**Comment by k-takata** [comment]
So, does it occur with `vim --clean` or does it occur when you use plugins?
Does vim crash, or hang?

If you can build Vim by yourself, please build with debug information and try running on GDB.
https://github.com/vim/vim/wiki/Debugging-Vim-Bugs

> Vim Version is Latest: 8.2

What is the patch number?
The word "Latest" is not useful at all.

**Comment by Firestar-Reimu** [comment]
8.2.1989.2 Linux

8.2.2041 Windows

**Comment by Firestar-Reimu** [comment]
> okay, please fill out the issue template. It only happens in terminal vim, right? What about gvim? What about other terminals (cmd), what about `vim --cmd`? and what do you mean with crash?
I has said that:
Crash: `Esc` does not work, so do all the other buttons, including `:` so I cannot go into other modes.

**Comment by Firestar-Reimu** [comment]
using `vim --clean` solves the problem.

**Comment by k-takata** [comment]
Then, you should detect which plugin (or setting) causes the issue.

**Comment by chrisbra** [comment]
See also:
https://vi.stackexchange.com/questions/2003/how-do-i-debug-my-vimrc-file
https://vimhelp.org/vim_faq.txt.html#faq-2.5

**Comment by Firestar-Reimu** [comment]
I see, it is these two lines' fault:

```
imap ' ''<LEFT>
imap " ""<LEFT>
```
I was going to auto-match the quotemarks but it causes crash.

**Comment by jottkaerr** [comment]
You are running into an endless recursion. Change your mappings to
```
inoremap ' ''<LEFT>
inoremap " ""<LEFT>
```

**Comment by k-takata** [comment]
It is not a crash, just an infinite loop, but you can still stop it by Ctrl-C.
It is caused because you use `imap` instead of `inoremap`.
`imap` expands the mapping recursively.

**Comment by Shane-XB-Qian** [comment]
On 20/11/26 06:48AM, K.Takata wrote:
> It is not a crash, just an infinite loop, but you can still stop it by Ctrl-C.
> It is caused because you use `imap` instead of `inoremap`.
> `imap` expands the mapping recursively.

unles OOM? :)

-- 
Shane
