### ISSUE TITLE
FileType autocmds executed on every buffer change

### ISSUE THREAD

**Issue by jdpopkin** [vim/vim#738]
I'm using Vim 7.4.1718 on OSX 10.11.1 as `./vim -N -u NONE`. When I enter the following commands:

```
:filetype plugin on
:augroup foo
:au foo FileType ruby :execute "normal! ggOhello"
:augroup END
:e tmp
:w 
:e tmp.rb
:w 
:b # 
:b # 
```

The word "hello" will appear twice in `tmp.rb`. Another "hello" appears each time I change back to `tmp.rb`'s buffer. This will _not_ happen, however, if I call `:set hidden` before `:e tmp.rb`.

I'm not _certain_ that this behavior is a bug, since the documentation says that FileType events happen every time file type is detected, which doesn't specify if that should happen every time the user changes buffers. But it seems counterintuitive to me, and it's caused bugs in at least one plugin I use (jceb/vim-orgmode#222).

(Previously reported to Neovim at neovim/neovim#4536.)

**Comment by chrisbra** [comment]
If the `hidden` option isn't set, the buffer is completly deleted from vim when you switch to another buffer and once you do `:b #` to reopen it, Filetype detection will kick in again, since this is like completly new loading of the buffer.  So this is expected behaviour.
