### ISSUE TITLE
Vim & Netrw for large files & dirs

### ISSUE THREAD

**Issue by jchwenger** [vim/vim#7381]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

I've come across two use cases where I'd love to be able to use Vim (where would one *not* want to use Vim ?! <3) but couldn't:
- for browsing *large* files (think: plain text webscraping dumps of 10s or 100s of Gb);
- for exploring/browsing similarly large directories (a folder with one file per, say, wikipedia article, hundreds of thousands/millions of entries).

(I'm obviously hacking things using Unix utils (zcat and head and ripgrep and sed etc.) when I want to handle these large things, and yes I can split big folders into subfolders.)

**Describe the solution you'd like**

Vim capabilities to use it like a sliding window (not loading the whole file, but still be able to have search capabilities for instance, so Vim would search the file in the background, jump and load only a bit of it), and same for netrw.

**Describe alternatives you've considered**

For now just Unix utils.

I had a nice [question about doing batch editing for datasets](https://vi.stackexchange.com/questions/25327/plugin-to-edit-whole-datasets-projects), as :g/ and :s/ (or :sort) are so gorgeous to use, which goes into a similar direction, namely Vim textual powers for big data.

**Additional context**

A little [meme](https://ibb.co/87ZLHqp) in honour of Vim.

**Comment by cecamp** [comment]
I don't see where netrw enters into this; it sounds like a request for a new vim feature. As such, it doesn't belong on the vim issues list which is for bugs and fixes; the vimdev email list is intended for such things. Although not what you asked for, you may find `http://www.drchip.org/astronaut/vim/index.html#LARGEFILE` helpful for handling large files.

I'm closing this "issue".

**Comment by jchwenger** [comment]
@cecamp thanks a lot for the link! Just  to clarify, when opening this issue I chose the option, and I quote "Feature request: Suggest an enhancement for Vim", as the enhancement tag suggests, and as I've seen it practiced on many repos. But I'll look for that vimdev email list next time.
