### ISSUE TITLE
Preview windows is not working correctly on Windows 10

### ISSUE THREAD

**Issue by jiangjianshan** [vim/vim#7386]
Hello,

   I have dual system on my laptop, one is Kali Linux 2020.4 and another one is Windows 10. For linux, the vim version is Vim 8.2.1913. For Windows, the vim version is 8.2.2061. Both fzf version is 0.24.3 and bat version is 0.17.1, which are both same as Linux and Windows. But the preview windows are not working correctly on Windows. I have report an issue on the link of 
https://github.com/junegunn/fzf.vim/issues/1190 . I think this may be the issue of Vim also, so I report it here again.

**Comment by lacygoill** [comment]
> I think this may be the issue of Vim

Without a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example), there's no way to be sure.  See here for a [starting point](https://github.com/chrisbra/vim_faq/blob/7f9c65c91d01e289a92b9e43a70ee2becadd66ce/vim_faq.txt#L1153-L1228) on how to get one.  Note that your issue involves 2 plugins, `fzf` and `fzf-vim`.  You'll have to bisect them too, which is time-consuming.

Also, fill the issue template:

    _Instructions: Replace the template text and remove irrelevant text (including this line)_

    **Describe the bug**
    A clear and concise description of what the bug is.
    (Issues related to the runtime files should be reported to their maintainer, check the file header.)

    **To Reproduce**
    Detailed steps to reproduce the behavior:
    1. Run `vim --clean` (or `gvim --clean`, etc.)
    2. Edit `filename`
    3. Type '....'
    4. Describe the error

    **Expected behavior**
    A clear and concise description of what you expected to happen.

    **Screenshots**
    If applicable, copy/paste the text or add screenshots to help explain your problem.

    **Environment (please complete the following information):**
     - Vim version [e.g. 8.1.1234] (Or paste the result of `vim --version`.)
     - OS: [e.g. Ubuntu 18.04, Windows 10 1809, macOS 10.14]
     - Terminal: [e.g. GNOME Terminal, mintty, iTerm2, tmux, GNU screen] (Use GUI if you use the GUI.)

    **Additional context**
    Add any other context about the problem here.

**Comment by jiangjianshan** [comment]
@lacygoill , the issue has been solved by  author of fzf.vim, the solution is adding '--no-unicode' to $FZF_DEFAULT_OPTS at _vimrc
