### ISSUE TITLE
No doc tags file installed when cross-compiling

### ISSUE THREAD

**Issue by leahneukirchen** [vim/vim#740]
When cross-compiling vim, there is an error generating the tags (since vim cannot be executed), and therefore no tags file installed so :help doesn't work.

I think this is broken since 7.4.1633.

**Comment by brammool** [comment]
Christian Neukirchen wrote;

> When cross-compiling vim, there is an error generating the tags (since
> vim cannot be executed), and therefore no tags file installed so :help
> doesn't work.
> 
> I think this is broken since 7.4.1633.

Hmm, looks like the Makefile is not aware of cross-compiling.
We would need to do something in configure and use it to skip
generating the tags file.

## 

hundred-and-one symptoms of being an internet addict:
251. You've never seen your closest friends who usually live WAY too far away.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by leahneukirchen** [comment]
Or it could detect computing the tags failed and fall back to the included version.

**Comment by k-takata** [comment]
How about this?

``` diff
--- a/src/Makefile
+++ b/src/Makefile
@@ -2129,7 +2129,8 @@ installrtbase: $(HELPSOURCE)/vim.1 $(DES
 # different from the repository.
    cd $(HELPSOURCE); if test -f tags; then mv -f tags tags.dist; fi
    @echo generating help tags
-   -@cd $(HELPSOURCE); $(MAKE) VIMEXE=$(DEST_BIN)/$(VIMTARGET) vimtags
+   -@cd $(HELPSOURCE); $(MAKE) VIMEXE=$(DEST_BIN)/$(VIMTARGET) vimtags || \
+       if test ! -f tags; then cp tags.dist tags; fi
    cd $(HELPSOURCE); \
        files=`ls *.txt tags`; \
        files="$$files `ls *.??x tags-?? 2>/dev/null || true`"; \
```

**Comment by leahneukirchen** [comment]
@k-takata that patch works nicely in our cross-compiling environment.

:+1:

**Comment by brammool** [comment]
Ken Takata wrote:

> How about this?
> 
> ``` diff
> --- a/src/Makefile
> +++ b/src/Makefile
> @@ -2129,7 +2129,8 @@ installrtbase: $(HELPSOURCE)/vim.1 $(DES
>  # different from the repository.
>   cd $(HELPSOURCE); if test -f tags; then mv -f tags tags.dist; fi
>   @echo generating help tags
> - -@cd $(HELPSOURCE); $(MAKE) VIMEXE=$(DEST_BIN)/$(VIMTARGET) vimtags
> + -@cd $(HELPSOURCE); $(MAKE) VIMEXE=$(DEST_BIN)/$(VIMTARGET) vimtags || \
> +     if test ! -f tags; then cp tags.dist tags; fi
>   cd $(HELPSOURCE); \
>       files=`ls *.txt tags`; \
>       files="$$files `ls *.??x tags-?? 2>/dev/null || true`"; \
> ```

I don't like this solution, because an error in generating the tags file
would go unnoticed.

## 

hundred-and-one symptoms of being an internet addict:
261. You find diskettes in your pockets when doing laundry.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
> I don't like this solution, because an error in generating the tags file would go unnoticed.

Hmm, the error code has not been checked even before my patch. Is there any reason that the error code is not checked?
My patch just falls back to the same behavior before 7.4.1556 and 7.4.1633.
