### ISSUE TITLE
cannot pass list constant to mapnew()

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7400]
**Describe the bug**

We cannot pass a list constant to `mapnew()`.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        const LIST = [1, 2, 3]
        call mapnew(LIST, {_, v -> v + 1})
    EOF
    )

`E741` is raised:

    E741: Value is locked: mapnew() argument

**Expected behavior**

No error is raised, because `mapnew()` does not alter the locked list.  It returns a new one.

**Environment**

 - Vim version: 8.2 Included patches: 1-2072
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(362)

**Comment by lacygoill** [comment]
Although, this begs the question.  If we `mapnew()` a locked list/dictionary/blob, should the result be locked too?  I think I would want the result not to be locked, but I'm not sure everyone would agree.

**Comment by lacygoill** [comment]
> I think I would want the result not to be locked,

Because I (naively?) consider `mapnew()` as an alternative to `deepcopy()->map()`.  And with the latter, the new list is not locked:
```vim
const LIST = [1, 2, 3]
let newlist = deepcopy(LIST)->map({_, v -> v + 1})
let newlist[1] += 1
```

**Comment by lacygoill** [comment]
The patch fixed the issue for a simple list, but not for a list containing composite values:
```vim
const LD = [{'x': 12}]
call assert_equal([{'x': 12, 'y': 34}], mapnew(LD, {_, v -> extend(v, {'y': 34})}))
```
    E741: Value is locked: extend() argument

Is it working as intended?

**Comment by brammool** [comment]
I would say this is correct.  The list item is also a const, and mapnew() uses a shallow copy, thus the list items are still const.  You can make a copy of the item and change it, if you need to.

**Comment by lacygoill** [comment]
> mapnew() uses a shallow copy

Ok, I guess a deep copy would be too costly in the general case.  But it seems to contradict the help, which says:

> {expr1} remains unchanged.

That's not true:
```vim
let ld = [{'x': 12}]
call mapnew(ld, {_, v -> extend(v, {'y': 34})})
echo ld
```
    [{'x': 12, 'y': 34}]

`ld` has been changed by `mapnew()`.

Maybe this should be documented, so that people don't use `mapnew()` when they really need `deepcopy()` + `map()`.

**Comment by brammool** [comment]
Yes, the main purpose of mapnew() is that the item type can change without breaking the specified type.
I'll mention using deepcopy() when items themselves are being changed.
