### ISSUE TITLE
Vim9: unexpected E1004 error when executing :move command from visual mapping using <cmd>

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7401]
**Describe the bug**

In Vim9 script, executing a `:move` command from a `:normal` command from a `:def` function invoked by a visual mapping using the pseudo-key `<cmd>` might raise an unexpected error.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        xno <F3> <cmd>call <sid>Func()<cr>
        def Func()
            exe "norm! :m+1\r"
        enddef
        setline(1, ['aaa', 'bbb'])
        feedkeys("V\<F3>")
    EOF
    )

`E1004` is raised:

    E1004: White space required before and after '>'

**Expected behavior**

No error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-2072
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(362)

**Additional context**

In Vim script legacy, no error is raised:
```vim
vim9script
xno <F3> <cmd>call <sid>Func()<cr>
fu Func()
    exe "norm! :m+1\r"
endfu
setline(1, ['aaa', 'bbb'])
feedkeys("V\<F3>")
```

**Comment by lacygoill** [comment]
> In Vim script legacy, no error is raised:

To be more accurate, no error is raised if `Func()` is rewritten in a legacy function.

**Comment by lacygoill** [comment]
The code is a bit contrived, so I don't know whether there is really something to fix.  I found it while I was rewriting a plugin in Vim9 script.  The original command can be found [here](https://github.com/zirrostig/vim-schlepp/blob/dfe67ad49d534e6c442d589c558da7b3ab052f03/plugin/schlepp.vim#L122):

    execute "normal! :'<,'>m'>+1\<CR>" . l:reindent_cmd . 'gv'

**Comment by lacygoill** [comment]
> The code is a bit contrived

That is, I don't think it's necessary to run `:move` from `:normal`; [this should work too](https://github.com/lacygoill/vim-movesel/blob/48192d50c2c9f75d772fd04ffe8511dc6f6f7685/autoload/movesel.vim#L110):

    sil :*m'>+1
    norm! gv

**Comment by brammool** [comment]
> > The code is a bit contrived
> 
> That is, I don't think it's necessary to run `:move` from `:normal`; [this should work too](https://github.com/lacygoill/vim-movesel/blob/48192d50c2c9f75d772fd04ffe8511dc6f6f7685/autoload/movesel.vim#L110):
> 
>     sil :*m'>+1
>     norm! gv

Still, you expect the ":normal" argument to be executed as in legacy Vim
script.  Otherwise you would have to double the colon to put a colon in
front of the range.  And even that wouldn't work, it goes after the
range.

The ":normal" argument is supposed to be execute as typed, thus I would
think that's not as in Vim9 script.

-- 
The early bird gets the worm. If you want something else for
breakfast, get up later.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> Still, you expect the ":normal" argument to be executed as in legacy Vim script.

How about `feedkeys()`?  If the keys execute an Ex command, should it run in the legacy context, or the Vim9 one?

Right now, it depends on the flags:
```vim
vim9script
nno <F3> <cmd>let g:message = 'will fail'<cr>
feedkeys("\<F3>", 'x')
```
    E1126: Cannot use :let in Vim9 script
```vim
vim9script
nno <F3> <cmd>let g:message = 'no error' <bar> echo g:message<cr>
feedkeys("\<F3>")
```
    no error

Which is inconsistent and confusing.

**Comment by lacygoill** [comment]
> Which is inconsistent and confusing.

Or maybe not.  `x` causes Vim to execute the typeahead buffer immediately, while Vim is still in the Vim9 context.  Without `x`, the typeahead buffer is executed later.  I guess "later" happens in the legacy context.  It's probably just a corner case.

**Comment by lacygoill** [comment]
> It's probably just a corner case.

To avoid this, it's better to always run Ex commands from a function, where the context is explicit (`:fu` = legacy, `:def` = Vim9); rather than trying to figure out in which context Vim will implicitly be when it runs a command.

    # bad
    nno <F3> <cmd>let g:message = 'will fail'<cr>
                  ^-------------------------^
                  bad because no guarantee about the context in which Vim will be

Versus:

    nno <F3> <cmd>call Func()'<cr>
    def Func()
        # good because the context is explicit (:def = Vim9)
        let g:message = 'no error'
        echo g:message
    enddef
