### ISSUE TITLE
Vim9: cannot use key with a dash in literal dictionary

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7406]
**Describe the bug**

In Vim9 script, we cannot use a key with a dash in a literal dictionary without using the – soon-to-be-deprecated – `#{}` syntax, and without quoting the key.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        var d = {some-key: 0}
    EOF
    )

`E121` is raised:

    E121: Undefined variable: some

**Expected behavior**

No error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-2079
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(362)

**Additional context**

No error is raised with the `#{}` syntax:
```vim
vim9script
var d = #{some-key: 0}
```
And no error is raised when the key is quoted:
```vim
vim9script
var d = {'some-key': 0}
```
If this is working as intended, then it should be documented at `:h vim9`.  Right now, in the "Dictionary literals" section, I can't find anything which explains this limitation:

https://github.com/vim/vim/blob/38bd8de551225bfca133805f21cee2592f0c759d/runtime/doc/vim9.txt#L434-L452

**Comment by brammool** [comment]
This is a side effect of allowing both the old and the new syntax.  I think we have given enough time to deprecate the #{} syntax now.
