### ISSUE TITLE
Vim9: should a colon always be parsed as a delimiter between indexes in a slice?

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7409]
Consider this Vim9 snippet:
```vim
vim9script
def Func()
    var l = [1, 2, 3, 4, 5]
    var x = 1
    var y = 3
    echo l[x:y]
enddef
defcompile
```
It raises `E1075`:

    E1075: Namespace not supported: x:y]

I'm not sure the error message is easy enough to understand what is wrong with the code.  Usually, the way I fix these kind of issues, is by adding a space:

    # before
    echo l[x:y]

    # after
    echo l[x :y]
            ^

Which gives:
```vim
vim9script
def Func()
    var l = [1, 2, 3, 4, 5]
    var x = 1
    var y = 3
    echo l[x :y]
enddef
defcompile
```
    ✔

But I've always found this awkward.  Would it make sense for Vim9 to always parse a colon as a delimiter between 2 indexes inside a slice?  If one of the index is a variable with a prefix including a colon (e.g. `b:name`), then to remove any ambiguity the latter could be doubled:

                  delimiter between the two indexes in the slice
                  v
    echo l[b::name:123]
            ^^
           delimiter between the buffer namespace and the "name" variable in that namespace

This way, the first snippet would not raise any error anymore.  And if someone uses a variable with a `b:`, `g:`, `w:`, ... prefix, without doubling the colon:

    echo l[b:name:123]
            ^
            ✘

an error would be raised such as:

    E1234: too many ":" delimiters in slice

---

Note that the original snippet raises an error only in a `:def` function, not at the script level, which is inconsistent:
```vim
vim9script
var l = [1, 2, 3, 4, 5]
var x = 1
var y = 3
echo l[x:y]
```
    [2, 3, 4]

With the suggested change, the code would work both in a `:def` function, and at the script level, which would be more consistent.

**Comment by lacygoill** [comment]
The other benefit is that the code would be more readable.  Right now, when we read a colon inside a slice, we have to check what comes before to determine whether it's a delimiter between indexes, or whether it's part of a variable name.  With the suggested change, a colon would always be a delimiter between indexes; and 2 colons would always be a delimiter between a scope and a name.

**Comment by lacygoill** [comment]
Here is another example, where it's currently not obvious what is wrong, and which could benefit from the suggested change:
```vim
vim9script
var s = 3
var line = 'abcdef'
echo line[s:]
```
    E731: using Dictionary as a String

A newcomer to Vim9 might wonder what is wrong, and why Vim talks about a dictionary in the error message.  And while I do know why "Dictionary" is mentioned, I'm not sure why Vim refers to "String"; in a string slice, we typically use numbers, not strings, to index some bytes (legacy) or characters (Vim9).

**Comment by lacygoill** [comment]
Here is yet another confusing example.  This snippet works:
```vim
vim9script
var c = 3
var line = 'abcdef'
echo line[c:]
```
    def

This one does not:
```vim
vim9script
var l = 3
var line = 'abcdef'
echo line[l:]
```
    E121: Undefined variable: l:

Which does not make sense since `l:` is not a valid scope in Vim9 script.

Same thing with with `a:`:
```vim
vim9script
var a = 3
var line = 'abcdef'
echo line[a:]
```
    E121: Undefined variable: a:

**Comment by lacygoill** [comment]
Not to mention that – so far – across all those snippets, 3 different error messages are given (`E1075`, `E731`, `E121`), which all result from the same underlying issue: a single colon is too ambiguous in a slice.

**Comment by brammool** [comment]
There are probably many more ambiguous situations.  Since the text left and right of the colon is an expression, it's hard to impose restrictions on them.  The simplest solution would be to require white space before and after the colon used for the range.
The syntax originates in Python, which does not use a colon for a namespace, thus doesn't need this restriction.
