### ISSUE TITLE
Provide a method to get number of lines in a buffer (non-current window)

### ISSUE THREAD

**Issue by blueyed** [vim/vim#741]
Currently you have to use `len(getbufline(b, 1, '$'))` for a buffer that is not displayed in the current window (where `line('$')` works).
This has some internal overhead, and for a 11MB log file http://stackoverflow.com/questions/14544618 says that a solution using Vim's Python interface is 200 times faster..!

Could there be a read-only buffer variable, that would be available with `getbufvar`?
(`getbufvar(b, '&lines')` refers to the the global `lines` setting already (Vim's height)).

**Comment by chrisbra** [comment]
would be fixed by #2441 I guess.
