### ISSUE TITLE
Vim9: cannot refer to function-local function in replacement field of substitution command

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7410]
**Describe the bug**

In Vim9 script, we cannot refer to a function-local function in the replacement field of a substitution command.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            repeat(['the slow brown fox'], 3)->setline(1)
            def Rep(): string
                return 'quick'
            enddef
            :%s/slow/\=Rep()/
        enddef
        Func()
    EOF
    )

`E117` is raised:

    E117: Unknown function: Rep

**Expected behavior**

No error is raised.  `slow` is replaced with `quick`.

**Environment**

 - Vim version: 8.2 Included patches: 1-2081
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(362)

**Additional context**

No error is raised if `Rep()` is refactored in a script-local function:
```vim
vim9script
def Rep(): string
    return 'quick'
enddef
def Func()
    repeat(['the slow brown fox'], 3)->setline(1)
    :%s/slow/\=Rep()/
enddef
Func()
```
If Vim is able to find a script-local function while evaluating the replacement field of a substitution command, I would expect it could also find a function-local function.

---

As a workaround, we can use `:exe`:
```vim
vim9script
def Func()
    repeat(['the slow brown fox'], 3)->setline(1)
    def Rep(): string
        return 'quick'
    enddef
    exe ':%s/slow/' .. Rep() .. '/'
enddef
Func()
```
But I don't think `:exe` can be used when the replacement refers to a capturing group:
```vim
vim9script
setline(1, 'order reversed')
def Func()
    def Rep(): string
        return submatch(2) .. submatch(1)
    enddef
    s/\(\w*\) \(\w*\)/\=Rep()/
enddef
Func()
```
    E117: Unknown function: Rep

Because then, `Rep()` must be evaluated before each substitution, not just once before executing `:s`.

**Comment by brammool** [comment]
I do not think this can be made to work without disadvantages.  Invoking ":s" goes to the global context, making the local context available there temporarily, from the compiled function, is going to be inefficient at least, since we cannot know what will be needed there and would have to make everything from the local context available on every ":s" command.

**Comment by lacygoill** [comment]
Ok, that's what I suspected, because function-local functions seem to be implemented as lambdas, which can't be (easily?) used in the global context.  The only reason why I thought that maybe it would be possible is because it's working with a script-local function.  Anyway, closing and thank you for the explanation.

**Comment by lacygoill** [comment]
I'm regularly finding cases where this would be really convenient if it worked.

Here is one other – real – example.  This time, it involves a `:global` command:
```vim
vim9script

def ReverseEveryNLines(n: number, line1: number, line2: number)
    var mods = 'sil keepj keepp lockm '
    var range = ':' .. line1 .. ',' .. line2
    def Offset(): number
        var offset = (line('.') - line1 + 1) % n
        return offset != 0 ? offset : n
    enddef
    exe mods .. range .. 'g/^/exe "m .-" .. Offset()'
enddef

repeat(['aaa', 'bbb', 'ccc'], 3)->setline(1)
ReverseEveryNLines(3, 1, 9)
```
    E117: Unknown function: Offset

It works in Vim script legacy:
```vim
vim9script

fu ReverseEveryNLines(n, line1, line2)
    let mods = 'sil keepj keepp lockm '
    let range = ':' .. a:line1 .. ',' .. a:line2
    fu Offset() closure
        let offset = (line('.') - a:line1 + 1) % a:n
        return offset != 0 ? offset : a:n
    endfu
    exe mods .. range .. 'g/^/exe "m .-" .. Offset()'
endfu

repeat(['aaa', 'bbb', 'ccc'], 3)->setline(1)
ReverseEveryNLines(3, 1, 9)
```
As a workaround, `Offset()` needs to be turned into a script-local function, and we need to pass its arguments manually instead of relying on the closure:
```vim
vim9script

def ReverseEveryNLines(n: number, line1: number, line2: number)
    var mods = 'sil keepj keepp lockm '
    var range = ':' .. line1 .. ',' .. line2
    exe mods .. range .. printf('g/^/exe "m .-" .. Offset(%d, %d)', line1, n)
enddef

def Offset(line1: number, n: number): number
    var offset = (line('.') - line1 + 1) % n
    return offset != 0 ? offset : n
enddef

repeat(['aaa', 'bbb', 'ccc'], 3)->setline(1)
ReverseEveryNLines(3, 1, 9)
```
---

Here is yet another example on which I'm working:

https://github.com/vim/vim/blob/d0a1dee3f197d41434df4cf0271066b6aeb690fc/runtime/autoload/RstFold.vim#L11-L25

I'm trying to refactor the whole script in Vim9, because I think it could help in the issue #3430.  But because I can't use a function-local function in the replacement field of a substitution command, this substitution can't work:

https://github.com/vim/vim/blob/d0a1dee3f197d41434df4cf0271066b6aeb690fc/runtime/autoload/RstFold.vim#L28

While it does in Vim script legacy.  So, I have to turn it into a script-local function.  It's not that hard to do, but it's a bit unexpected when you refactor a script written in Vim script legacy.

If it really can't be made to work, maybe the help should be updated, because I suspect people will sometimes stumble upon this issue.  As a suggestion:
```diff
diff --git a/runtime/doc/vim9.txt b/runtime/doc/vim9.txt
index 1872b82ee..5a93e992f 100644
--- a/runtime/doc/vim9.txt
+++ b/runtime/doc/vim9.txt
@@ -701,6 +701,31 @@ function scope.  Instead, use a lambda: >
 	  return range(1, 2)->map({ _, v -> list[v] })
 	enddef
 
+They will not be visible to a substitution or global command either.
+For example: >
+	def Substitution()
+	  setline(1, 'xord')
+	  var newletter = 'w'
+	  s/x/\=newletter/
+	enddef
+	Substitution()
+
+Instead, use a script-local variable: >
+	var newletter: string
+	def Substitution()
+	  setline(1, 'xord')
+	  newletter = 'w'
+	  s/x/\=newletter/
+	enddef
+	Substitution()
+
+The map argument is a string expression, which is evaluated without the
+function scope.  Instead, use a lambda: >
+	def EvalString(): list<string>
+	  var list = ['aa', 'bb', 'cc', 'dd']
+	  return range(1, 2)->map({ _, v -> list[v] })
+	enddef
+
 
 ==============================================================================
 
```

**Comment by brammool** [comment]
In legacy Vim script it works because the function Offset() is defined as a global function.
I tried doing that in the :def function, but ran into a crash.  The global function is defined without the context as needed for the closure.  I'll make a fix for that.  I'm surprised it worked for a script-local function.

**Comment by lacygoill** [comment]
> I'm surprised it worked for a script-local function.

 Me too.  Usually, we can't refer to the script-local context from the global one, so I don't understand why that works; but it does.  That's why later, I was surprised it didn't also work for a function-local function.
