### ISSUE TITLE
Vim9: unexpected E1050 when evaluating "123 || 0"

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7414]
**Describe the bug**

In Vim9 script, evaluating `123 || 0` raises an unexpected error.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        eval 123 || 0
    EOF
    )

`E1023` and `E1050` are raised:

    E1023: Using a Number as a Bool: 123
    E1050: Colon required before a range

**Expected behavior**

Only `E1023` is raised; not `E1050`, because neither `123` nor `0` are used as ranges.

**Environment**

 - Vim version: 8.2 Included patches: 1-2083
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(362)

**Additional context**

It's a regression introduced in 8.2.1943.

**Comment by brammool** [comment]
Fixed by 8.2.2094
