### ISSUE TITLE
Artifacts with renderoptions=type:directx

### ISSUE THREAD

**Issue by 89z** [vim/vim#7417]
Using a file like this:

~~~
a̎.
~~~

If I move the line down, it creates artifacts:

> ![Untitled](https://user-images.githubusercontent.com/73562167/100972481-81443300-34fe-11eb-8586-086f22e4344e.png)

It only happens with this:

~~~
set renderoptions=type:directx
~~~

but I want to use that option if possible, as it allows for color emoji. I tried
with this file:

https://github.com/vim/vim-win32-installer/releases/download/v8.2.2083/gvim_8.2.2083_x64.zip

**Comment by chrisbra** [comment]
how do you move the line down?

**Comment by 89z** [comment]
Enter key

**Comment by chrisbra** [comment]
wow this is very terse. I am using gvim 8.2.2004 and starting from `gvim --clean -c ":set enc=utf-8 renderoptions=type:directx" ä.txt` (with `ä.txt` containing just one single utf-8 encoded `ä.`) I do not see those artifacts on typing enter in insert mode.

So please can you please give a reproducible minimal example that shows this behaviour? This might also be related to the font used. So can you reproduce this with other fonts? Thanks.

**Comment by 89z** [comment]
The text in question is this:

~~~
a       U+0061          codepoints.net/U+0061
̎       U+030E          codepoints.net/U+030E
~~~

Not what you put:

~~~
ä       U+00E4          codepoints.net/U+00E4
~~~

Also, I was able to reproduce using either of these:

~~~
gvim --clean -c 'set colorcolumn=80 guifont=Consolas number renderoptions=type:directx' a.txt
gvim --clean -c 'set colorcolumn=80 guifont=Cascadia_Mono number renderoptions=type:directx' a.txt
~~~

**Comment by chrisbra** [comment]
I would appreciate it, if you could give useful information right from the beginning, so we don't have to guess. 

So this looks like a font-related problem. For me, the following `.` is also not correctly rendered. Interesting, that this only happens with a colorcolumn setting enabled. It doesn't happen with the default font being used, whatever that is. 

Hm, while testing, I could make gvim crash by using `:set guifont=`. This does not always happen, hard to reproduce. Strange.
