### ISSUE TITLE
Some settings do not get applied for certain file types. Using `set hidden` disables set `autocmd filetype` settings.

### ISSUE THREAD

**Issue by DasOhmoff** [vim/vim#7420]
Hello, thank you for helping, and thank you for this great program!

I want to report two things which I **think** might be bugs.

**1.** Some settings do not get applied on some file types, even though no other sources (like plugins) changed these settings. Steps to reproduce:
- Open vim without any configuration or plugins by using the `vim -u NONE` command.
- Set the number settings by typing `:set number relativenumber`
- Open up the help window by typing `:help`.
_[There are no numbers or relative numbers in the help file.]_
- Check who changed the settings of the file by typing: `:verbose set nonumber?`
_[No one changed the settings.]_

**Expected behaviour:** numbers and relative numbers should show up in the help file.

**2.** Using `set hidden` disables set `autocmd FileType` settings.
Steps to reproduce:
- Open vim without any config by using the `vim -u NONE` command.
- Set the auto command by typing `:autocmd FileType help setlocal number relativenumber`
- Set the hidden setting by typing `:set hidden`
- Open up the help window by typing `:help`
_[**At the moment** the numbers and relative numbers are there, this seems to be correct.]_
- Close the help window by typing `:q`
- Open up the help window again by typing `:help`
_[The numbers and relative numbers are gone, this seems to be incorrect.]_

**Expected behaviour:** numbers and relative numbers should still be there, even if the help window was closed and reopened.

Thank you again, for helping, and thank you again for this great program, it is really appreciated :)

**Comment by brammool** [comment]
This is working as intended.
When opening a help file, several options are set for comfortably reading the help.  Line numbers aren't very useful, thus they are disabled.
A FileType autocommand is only executed when the filetype is set.  If a file is hidden and unhidden, the filetype is not set, but since opening a help buffer in a window does apply the help option values, the options are reset.

If you do want line numbers in the help file, use another autocommand, such as BufWinEnter and check the value of 'filetype'.

**Comment by DasOhmoff** [comment]
Ah OK I see, but why does the command `:verbose set nonumber?` not show in which file it is set?

> But since opening a help buffer in a window does apply the help option values ...

Where is this behaviour defined, is it in some script? Which options get changed by this?, and is there a way stop this behaviour? I like my options the way they are, for example I use `5j` instead of `jjjjj` (without relative number I don't know how many lines I have to jump to copy some text for example).

Also, are there other file types that behave in this way? Can I get a list of these kind of file types, or just outright say to not change my options?

**Comment by chrisbra** [comment]
> Ah OK I see, but why does the command :verbose set nonumber not show in which file it is set?

Because this is set internally by Vim in the C core. In general the help filetype is not a good way to test things, better use some other file types like `vim` or `c` or `python` or whatever you like. As said before, use a different auto command in that case when the buffer is not unloaded (like bufwinenter and check the filetype in that case).

**Comment by jottkaerr** [comment]
> Ah OK I see, but why does the command `:verbose set nonumber` not show in which file it is set?

Did this command actually output the current state of the 'number' option? I think this command should only have reset the 'number' otpion.

To display if a boolean option is set or reset you have to append a question mark to the option name in a `:set` command, i.e.
```
:set number?
```
or
```
:verbose set number?
```

**Comment by DasOhmoff** [comment]
@jottkaerr, yes sorry, my fault, I added the `?` when I was inside Vim executing the command, I forgot to add it in my github comment. So yes, it did output the current state of the number option.

@chrisbra, ah I see, so it is not in a Vim script. What are all the options that are changed through that?

Also, are there other file types (other than help) that have such a changing of options in the Vim C core? For example the quick fix list or so? If so, which options exactly are changed?

**Comment by brammool** [comment]
> Ah OK I see, but why does the command `:verbose set nonumber` not show
> in which file it is set?
> 
> > But since opening a help buffer in a window does apply the help option values ...
> 
> Where is this behaviour defined, is it in some script? Which options
> get changed by this?, and is there a way stop this behaviour? I like
> my options the way they are, for example I use `5j` instead of `jjjjj`
> (without relative number I don't know how many lines I have to jump to
> copy some text for example).
> 
> Also, are there other file types that behave in this way? Can I get a
> list of these kind of file types, or just outright say to not change
> my options?

I thought there was a section in the help about what options are
set/reset in the help buffer, but I can't find it.  I'll add it in
helphelp.txt.


-- 
Lose weight, NEVER Diet again with
                  The "Invisible Weight Loss Patch"
						(spam e-mail)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
