### ISSUE TITLE
Width of some 2-byte character becomes width of 1-byte character, on Windows.

### ISSUE THREAD

**Issue by aikige** [vim/vim#7424]
**Describe the bug**
When I'm using Windows version of GVim, some 2-byte character is treated as 1-byte character and not displayed properly.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `gvim --clean`
2. Set option: `:set encoding=utf-8`
3. Insert text `※テスト`
4. Width of first character `※` is treated as 1-byte character. Please refer 1st screenshot.

**Expected behavior**
First character should be treated as 2-byte character.
Following case works correct.
1. Run `gvim --clean`
2. Set option: `:set encoding=cp932`
3. Insert text `※テスト`
4. Get correct output. Please refer 2nd screen shot.

**Screenshots**

Error: `set encoding=utf-8`:
![VIM_Encoding_Error](https://user-images.githubusercontent.com/48190566/101152932-13ffe180-3667-11eb-899e-c4b93a5e4d13.png)

OK: `set encoding=cp932`
![VIM_Encoding_OK_CP932](https://user-images.githubusercontent.com/48190566/101153260-8a044880-3667-11eb-989c-444f9301b07a.png)

**Environment (please complete the following information):**
 - Vim version:
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 12 2019 13:30:17)`
MS-Windows 32 ビット GUI 版 with OLE サポート
Compiled by mool@tororo
```
 - OS: Windows 10 1909

**Comment by chrisbra** [comment]
Try a more updated version, that provides the `setcellwidth()` function. This allows to configure vim how wide certain characters are.

Having said this, We might need to update the internal unicode tables, but not sure if this would fix the issue.

**Comment by k-takata** [comment]
"※" is an ambiguous-width character. The width depends on the fonts or other factors.
Try `set ambiwidth=double`. (See `:help 'ambiwidth'` for detail.)
If you need fine tuning, use `setcellwidth()` as @chrisbra described.

**Comment by aikige** [comment]
Thank you for advice @k-takata and @chrisbra.

> Try `set ambiwidth=double`. (See `:help 'ambiwidth'` for detail.)

I tried this and it looks problem has been solved.
I did not know this option.
Thank you!
