### ISSUE TITLE
Mappings with <Cmd> don't work with Ex commands, take 2

### ISSUE THREAD

**Issue by lkintact** [vim/vim#7426]
**To Reproduce**
1. Run `gvim --clean`
2. Execute `:cnoremap <F3> <Cmd>setlocal list!<CR>`
3. Type <kbd>:</kbd> to enter Command-line mode.
4. Press <kbd>F3</kbd> a couple of times. Nothing happens.

**Expected behavior**
The `$` EOL symbol should appear and disappear. The mapping does work with patterns (if <kbd>/</kbd> or <kbd>?</kbd> are pressed at step 3).

**Environment**
 - Vim version 8.2.2086
 - OS: Windows 10 Home 1803
 - Terminal:  GUI.

**Comment by lacygoill** [comment]
The issue is not caused by `<cmd>`.  It can be reproduced with `<c-r>=`:

    vim --clean +"cnoremap <F3> <c-r>=execute('setlocal list!')[-1]<cr>" /tmp/file

The issue is that Vim doesn't redraw while on the Ex command-line.  One solution is to add a `:redraw`:

    vim --clean +'cnoremap <F3> <cmd>setlocal list!<bar>redraw<cr>' /tmp/file
                                                   ^---------^

**Comment by lkintact** [comment]
Thank you, @lacygoill, you are right, and thanks for the solution.
The issue can be closed, I think.
