### ISSUE TITLE
Menu backgroud is the same color as the main window background.

### ISSUE THREAD

**Issue by alex14641** [vim/vim#7427]
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Describe the bug**
When using gvim with the elflord color scheme, the menu background is black, making it difficult to see the menu text.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run gvim
2. :color elflord
3. Notice that the menu background changes to black.

**Expected behavior**
The menu background shouldn't change.

**Environment (please complete the following information):**
 - Vim version: 8.2.2093
 - OS: Slackware current
 - Terminal: GUI

**Additional context**

**Comment by habamax** [comment]
Colorschemes are being worked on another repo: https://github.com/vim/colorschemes/

What is the menu background you are talking about? A screenshot maybe? Or probably better to move it to https://github.com/vim/colorschemes/issues/21 .

**Comment by alex14641** [comment]
This is 8.2.1969: the menu background is light and the text is visible.
[
![gvim-1969](https://user-images.githubusercontent.com/52546769/101294455-5cdda480-37e5-11eb-9ffa-cd283fee2c42.png)
](url)
This is 8.2.2093: the menu background is dark and the text is almost invisible: 
![gvim-2093](https://user-images.githubusercontent.com/52546769/101294458-66ffa300-37e5-11eb-90ea-9a971fe8df02.png)

**Comment by k-takata** [comment]
Could you bisect it?
Is [8.2.2043](https://github.com/vim/vim/commit/ff94bd9e4779b918f3761035f43a97ba7175b3ce) related?

**Comment by habamax** [comment]
I can't reproduce it on windows with `gvim --clean`:
![image](https://user-images.githubusercontent.com/234774/101320816-657dbb80-3875-11eb-9e1f-c365eaee77b0.png)

version 8.2.2098

**Comment by alex14641** [comment]
> Could you bisect it?
> Is [8.2.2043](https://github.com/vim/vim/commit/ff94bd9e4779b918f3761035f43a97ba7175b3ce) related?

Reverting this patch fixed the problem; gvim --clean did not.

**Comment by k-takata** [comment]
@lilydjwg Do you have any idea?

**Comment by lilydjwg** [comment]
Oops, I totally forgot those elements and it turns out that the menubar is transparent, showing the window background color.

I'll fix it another way.

@habamax this happens with the gtk3 gui only.

**Comment by salortiz** [comment]
Using `:colorscheme material-monokai` this bug bitten me.
I found a workaraund: Invoke gvim with an alternate GTK "dark" theme:
```sh
$ GTK_THEME=Adwaita:dark gvim ...
```

**Comment by lilydjwg** [comment]
@salortiz I'm sorry for that. You can also `:set guioptions+=d` to use the dark version of gtk theme.

**Comment by salortiz** [comment]
@lilydjwg Your workaround is nicer, thanks!
