### ISSUE TITLE
autocmd BufUnload not work for hidden buffer

### ISSUE THREAD

**Issue by roachsinai** [vim/vim#7431]
**Describe the bug**

I use a vim plugin that when use Vim open a ipynb (python notebook) file, will use jupytext create corresponding python file to enable use like, YCM to help coding. This plugin set a autocmd BufUnload for the python file buffer to delete the python file when I quit Vim .

The bug is if the current buffer in current window is not the python file, the python file still there after quit Vim.

**To Reproduce**

I turn the plugin to a minimal version just vimscript.

1. Copy file `test_unload.vim` to ~/.vim/plugin (content of test_unload.vim will post below) .
2. `touch tt.ipynb && vim tt.ipynb`
3. `:e tt.c`
4. `:q`

After above steps, their should no `tt.py` file on disk, but have on `tt.py`.

**Contents of test_unload.vim**

```
if exists("loaded_test")
  finish
endif

function! s:read_from_ipynb()  "{{{
  if expand("<afile>:e") != "ipynb"
    echo "Not an ipynb file."
    return
  endif
  let l:filename = expand("%:p")
  let l:py_file = fnamemodify(l:filename, ":r") . ".py"
  call system('sleep 1;echo 123 > ' . l:py_file)
  " open the py file, wipe the ipynb file
  let l:bufnr = bufnr("%")
  execute "edit " . l:py_file
  execute "bwipeout" . l:bufnr
  set filetype=python
  execute "autocmd ipynb BufUnload <buffer> call s:cleanup()"
  let b:ipynb_file = l:filename
endfunction  "}}}

function! s:cleanup()  "{{{
  if !exists("b:ipynb_file")
    echo "Not a ipynb py file."
    return
  endif
  call delete(expand("<afile>:p"))
endfunction  "}}}

augroup ipynb
  au!
  autocmd BufReadPost *.ipynb call s:read_from_ipynb()
augroup END

let loaded_test = 1
```

What's in vimrc:

```
hmanx ~ » cat .vimrc            
set hidden
hmanx ~ »
```

**Expected behavior**

`tt.py` deleted by autocmd BufUnload when quit Vim.

**Environment:**
 - Vim version: 8.2.1989-2
 - OS: Manjaro Linux
 - Terminal: Konsole

**Additional context**

Or autocmd BufUnload not work after set hidden is by design?

---

Thanks in advance!

**Comment by chrisbra** [comment]
I believe the `BufUnload` autocommand are not executed, since the buffer is kept in memory. You might be able to fix this using the `bufhidden` local option

**Comment by roachsinai** [comment]
Oh, @chrisbra I found `s:cleanup()` returned directly as `b:ipynb_file` not exists which **should**.

I mean if function `s:cleanup()` is:

```
function! s:cleanup()  "{{{
  call delete(expand("<afile>:p"))
endfunction  "}}}
```

`tt.py` will be deleted.

---

Thanks for quick reply!

**Comment by roachsinai** [comment]
Any update? `b:ipynb_file` should exists but not...

**Comment by chrisbra** [comment]
Don't be so impatient. It is not clear this is a bug yet. For asking user questions I always recommend to either use vi.stackexchange.com or the vim_use maillinglist where people can answer even if from the core maintainers here nobody is only currently. 

Now regarding your questions. I am not sure I understand. I was merely answering to your question, that the BufUnLoad autocommand may not be triggered for `:set hidden`.  But I haven't tried to reproduce your use case yet.

**Comment by roachsinai** [comment]
Hi @chrisbra sorry for that. What I'm afraid is my post not clear which will waste member of VIM's time.

What I found is BufUnLoad autocommand did triggered! What's wrong is function `s:read_from_ipynb()` define a buffer variable named `b:ipynb_file` by:

`let b:ipynb_file = l:filename`

But when run BufUnLoad autocommand, call `s:cleanup()` function, check `b:ipynb_file` whether exists by:

```
  if !exists("b:ipynb_file")
    echo "Not a ipynb py file."
    return
  endif
```

failed, so `s:cleanup()` directly return and didn't delete file `tt.py`.

I encountered this issue in last year, today find a minimal script (people no need to install extra libraries and other plugins not involved) casually.

So sorry to let you have that feeling!

**Comment by chrisbra** [comment]
sorry, I did not wanted to sound negative. I'll have to check your script. Will do later.

**Comment by roachsinai** [comment]
I test it on a new created VPS (Ubuntu ), no plugins install, no other settings. This issue can be reproduced. @chrisbra if no more Vim members reply I think I better try ask on vi.stackexchange.com as you suggested :).

```
OS: Ubuntu 20.04 LTS x86_64 
Host: KVM RHEL 7.6.0 PC (i440FX + PIIX, 1996) 
Kernel: 5.4.0-26-generic
VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 15 2020 06:40:31) Included patches: 1-2269
```

**Comment by roachsinai** [comment]
Closed by answer: https://vi.stackexchange.com/a/28366/16299
