### ISSUE TITLE
TOML

### ISSUE THREAD

**Issue by 89z** [vim/vim#7432]
It looks like TOML is not currently supported:

https://github.com/toml-lang/toml

as a workaround, I am changing this:

https://github.com/vim/vim/blob/7b130b9738c3d3975721ce9b84f91320e8d4857c/runtime/filetype.vim#L1981-L1982

to:

~~~vim
au BufNewFile,BufRead *.yaml,*.yml,*.toml		setf yaml
~~~

**Comment by Shougo** [comment]
TOML is not yaml.

**Comment by 89z** [comment]
Yeah I know that.

but YAML has the closest syntax. So until someone imports a TOML syntax file, its the best option.

**Comment by jamessan** [comment]
You can use https://github.com/cespare/vim-toml/.

There's already discussion (although the maintainer has understandable reservations) about submitting the scripts to Vim -- https://github.com/cespare/vim-toml/issues/36.

**Comment by chrisbra** [comment]
so it looks like there is already discussion about this on the upstream repository. Until this is resolved, you can clone this repository. So I am closing this.

**Comment by brammool** [comment]
> It looks like TOML is not currently supported:
> 
> https://github.com/toml-lang/toml
> 
> as a workaround, I am changing this:
> 
> https://github.com/vim/vim/blob/7b130b9738c3d3975721ce9b84f91320e8d4857c/runtime/filetype.vim#L1981-L1982
> 
> to:
> 
> ~~~vim
> au BufNewFile,BufRead *.yaml,*.yml,*.toml		setf yaml
> ~~~

For a temporary solution you better set the right filetype (probably
"toml"), and add a syntax file that loads the yaml syntax for now.
Then it's easier for a user to drop in another toml.vim in their own
.vim/syntax directory to overrule it.

-- 
ROBIN:  (warily) And if you get a question wrong?
ARTHUR: You are cast into the Gorge of Eternal Peril.
ROBIN:  Oh ... wacho!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
