### ISSUE TITLE
Vim9: cannot pass list containing empty string to map()

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7447]
**Describe the bug**

In Vim9 script, sometimes, we cannot pass a list containing an empty string to `map()`.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        map(['aaa', '', 'bbb'], {_, v -> fnamemodify(v, ':p')})
    EOF
    )

`E928` is raised:

    E928: String required

**Expected behavior**

No error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-2123
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(362)

**Additional context**

Regression introduced in [8.2.2117](https://github.com/vim/vim/releases/tag/v8.2.2117).

**Comment by lacygoill** [comment]
It looks like it's working as intended. Sorry for the noise.

**Comment by brammool** [comment]
Well, the idea was to give an error if the argument type is wrong.  Is an empty string wrong?  It's hard to say, but if we accept it and return an empty string not much harm is done.  And with ":p" an empty filename is actually valid.
I'll look through the other functions.  using getfperm() on an empty string can be handled like a non-existing file, for example.
