### ISSUE TITLE
timer_start() truncates multi line messages

### ISSUE THREAD

**Issue by noscript** [vim/vim#7451]
**Describe the bug**
It's not possible to print a multi line message using `timer_start()` function, only the last line is visible.

**To Reproduce**
1. Create script `~/timer_echo.vim`:

```vim
function! MyFunction(...)
    echo 1
    echo 2
endfunction
```

2. Run VIM as:
 ```sh
vim -g -u NONE +'so ~/timer_echo.vim'
```

3. Type on VIM command line:
```vim
:call MyFunction()
```
Visible output:
```
1
2
Press ENTER or type command to continue
```

4. Type on VIM command line:
```vim
:call timer_start(0, 'MyFunction')
```

Visible output:
```
2
```

**Expected behavior**
Visible output:
```
1
2
Press ENTER or type command to continue
```

**Environment:**
 - Vim version: 8.2.2019
 - OS:  Ubuntu 20.04
 - Terminal: GUI

**Comment by chrisbra** [comment]
Hm, didn't we have something similar in the past? Similar issue is https://github.com/vim/vim/issues/836 
There [Bram mentioned](https://github.com/vim/vim/issues/836#issuecomment-221404233):

```
Not sure if you really want to do this, the user may be doing something
that should not be interrupted by a list of messages. The callback
functions are not really intended to output a list of messages, that
would mess up the screen.
```

So I think expecting vim to output (and scroll multi-line messages) via async jobs or timers is not really supported. This could happen in the background messing up whatever the user is doing. I don't think this is going to be changed. Best is to avoid such things.

**Comment by noscript** [comment]
Yes, is it a duplicate of #836. It's worth documenting the behavior in affected functions.

**Comment by brammool** [comment]
I'll add a note about using popup_notification() at timer_start().
As mentioned, changing the behavior will cause other problems, thus I'll close this.

**Comment by lacygoill** [comment]
> As mentioned, changing the behavior will cause other problems, thus I'll close this.

Then #3960 can be closed too, I think.  It seems to be the exact same issue.
