### ISSUE TITLE
Content of indented HTML comment loses indentation.

### ISSUE THREAD

**Issue by DaFreddy** [vim/vim#7453]
## To Reproduce

1. Have set (in `.vimrc`):
```
filetype indent on
set ai
```
2. Open a HTML file (`:verbose set indentexpr` says `HtmlIndent()`).
3. Indent at least two levels deep (`T__` is a tab):
```
<div>
T__<div>
T__T__<span>Comment goes into the div below this line:</span>
T__</div>
</div>
```
4. Write an HTML comment.
5. The indentation ends up wrong (the content of the comment being less indented than its surroundings, and using spaces instead of tabs):
```
<div>
T__<div>
T__T__<span>Comment goes into the div below this line:</span>
T__T__<!--
T__  this is a comment.
T__T__-->
T__</div>
</div>
```

## Expected Behaviour

I would expect it to behave like this (for example):

```
<div>
T__<div>
T__T__<span>Comment goes into the div below this line:</span>
T__T__<!--
T__T__T__this is a comment.
T__T__-->
T__</div>
</div>
```

## Environment

VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 15 2019 16:41:15)
Included Patches: 1-875, 878, 884, 948, 1046, 1365-1368, 1382, 1401
OS: Linux (Debian)

## Suggested Fix

The problem is with `indent/html.vim`, specificially in this section:

```
  let prevlnum = prevnonblank(v:lnum - 1)
  let prevtext = getline(prevlnum)
  let idx = match(prevtext, '^\s*\zs<!--')
  if idx >= 0
    " just below comment start, add a shiftwidth
    return idx + shiftwidth()
  endif
```

I could get it to behave the way I expect it to by changing the return value like this:

```
  let prevlnum = prevnonblank(v:lnum - 1)
  let prevtext = getline(prevlnum)
  let idx = match(prevtext, '^\s*\zs<!--')
  if idx >= 0
    " just below comment start, add a shiftwidth
    return indent(prevlnum) + shiftwidth()
  endif
```

**Comment by brammool** [comment]
Your solution looks correct.  It was previously only working when the comment was preceded with tabs.
I'll include the change.
