### ISSUE TITLE
The plugin in vim reports an error, which may be related to the installation directory

### ISSUE THREAD

**Issue by guonaihong** [vim/vim#7455]
https://github.com/fatih/vim-go/issues/3108

Plug in error message
```
处理 /home/guo/.vim/plugged/vim-go/syntax/go.vim 时发生错误:
第  115 行:
E475: 无效的参数: goFormatSpecifier   /\
第  116 行:
E10: \ 后面应该跟有 /、? 或 &
第  117 行:
E10: \ 后面应该跟有 /、? 或 &
第  118 行:
E10: \ 后面应该跟有 /、? 或 &
第  119 行:
E10: \ 后面应该跟有 /、? 或 &
第  120 行:
E10: \ 后面应该跟有 /、? 或 &
第  151 行:
E10: \ 后面应该跟有 /、? 或 &
第  153 行:
E10: \ 后面应该跟有 /、? 或 &
第  156 行:
E10: \ 后面应该跟有 /、? 或 &
第  158 行:
E10: \ 后面应该跟有 /、? 或 &
第  285 行:
E10: \ 后面应该跟有 /、? 或 &
第  312 行:
E10: \ 后面应该跟有 /、? 或 &
第  313 行:
E10: \ 后面应该跟有 /、? 或 &
第  314 行:
E10: \ 后面应该跟有 /、? 或 &
第  315 行:
E10: \ 后面应该跟有 /、? 或 &
第  316 行:
E10: \ 后面应该跟有 /、? 或 &
第  353 行:
E10: \ 后面应该跟有 /、? 或 &
第  354 行:
E10: \ 后面应该跟有 /、? 或 &
第  355 行:
E10: \ 后面应该跟有 /、? 或 &
第  356 行:
E10: \ 后面应该跟有 /、? 或 &
第  364 行:
E10: \ 后面应该跟有 /、? 或 &
第  365 行:
E10: \ 后面应该跟有 /、? 或 &
第  377 行:
E399: syntax region goPackageComment    start=/\v(\/\/.*\n)+\s*package/ 的参数太少
第  378 行:
E10: \ 后面应该跟有 /、? 或 &

```

In the problematic version, I continue to try the following methods. This problem may be related to the installation location of vim.

* Can be configured
```
./configure --with-features=huge \
--enable-multibyte \
--enable-rubyinterp=yes \
--enable-python3interp=yes \
--enable-perlinterp=yes \
--enable-luainterp=yes \
--prefix=/usr/local/vim \
```

* This is the configuration I used. There is a problem
```
./configure --with-features=huge \
--enable-multibyte \
--enable-rubyinterp=yes \
--enable-python3interp=yes \
--enable-perlinterp=yes \
--enable-luainterp=yes \
--prefix=/usr \
```

**Comment by chrisbra** [comment]
plese fill out the issue template. 

Unfortunately, I cannot read the errors, because they are in Chinese. Please provide english errors. If I have to guess, I would say you are running in compatible mode for whatever reason.

**Comment by brammool** [comment]
This is not a useful issue, please use English messages.

**Comment by k-takata** [comment]
It seems that the 'compatible' option is set. Make sure that you have `.vimrc` and 'compatible' is not set in it.
If you use `-u` from the command line, you should also use `-N`.

**Comment by guonaihong** [comment]
If I use the ```vim  -N t.go ```command, the vim plug-in will not report errors

**Comment by guonaihong** [comment]
@k-takata Thank you for your answer. Your guess is right.
