### ISSUE TITLE
Vim9: # parsed as Ex command in #{

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7456]
**Describe the bug**

In Vim9 script, `#` is parsed as an Ex command in `#{`.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        #{some comment
    EOF
    )

`E488` is raised:

    E488: Trailing characters: {some comment:     #{some comment

**Expected behavior**

No error is raised because `#` is always parsed as a comment leader, even in `#{`, since [8.2.2082](https://github.com/vim/vim/releases/tag/v8.2.2082).

**Environment**

 - Vim version: 8.2 Included patches: 1-2127
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(362)

**Additional context**

If a space is added afterward, `#` is correctly parsed as a comment leader:
```vim
vim9script
# {some comment
```
    ✔

This is inconsistent and unexpected.  The help does say that a space should be added, but only for readability:

> To improve readability there must be a space between a command and the #
> that starts a comment.

This suggests that the whitespace is not really enforced, and that it's just a recommendation.  This is confirmed by the following snippet:
```vim
vim9script
#another comment
```
    ✔

No error is raised, and yet there's no whitespace after the comment leader `#`.

If the intent is really to enforce a whitespace after a comment leader, then the previous snippet should also raise an error, and if possible different than `E488` which is confusing (there's no good reason for `#` to be parsed as an Ex command just for an error).

**Comment by tonymec** [comment]
Even after the latest runtime files update, the eval.txt helpfile still includes the following (at lines 515 sqq):

						*literal-Dict* *#{}*
To avoid having to put quotes around every key the #{} form can be used.  This
does require the key to consist only of ASCII letters, digits, '-' and '_'.
Example: >
	:let mydict = #{zero: 0, one_key: 1, two-key: 2, 333: 3}
Note that 333 here is the string "333".  Empty keys are not possible with #{}.

IIUC this is what causes the error.

Best regards,
Tony.

**Comment by tonymec** [comment]
Oops:
Even after the latest runtime files update, the eval.txt helpfile still includes the following (at lines 515 sqq):
```
					*literal-Dict* *#{}*

To avoid having to put quotes around every key the #{} form can be used. This
does require the key to consist only of ASCII letters, digits, '-' and '_'.
Example: >
:let mydict = #{zero: 0, one_key: 1, two-key: 2, 333: 3}
Note that 333 here is the string "333". Empty keys are not possible with #{}.
```
IIUC this is what causes the error.

Best regards,
Tony.

**Comment by lacygoill** [comment]
> IIUC this is what causes the error.

Indeed, it's probably the cause, and I think it's a bug, because the `#{}` syntax was dropped in Vim9 script in 8.2.2082:

https://github.com/vim/vim/blob/1b884a0053982335f644eec6c71027706bf3c522/runtime/doc/vim9.txt#L444-L449

So I don't see any reason for it to raise an error now, unless it's to enforce a whitespace, in which case it should be more consistent (i.e. the error should also be raised for `#some comment`), and the error message should be more clear (`E488` is not the right error, because `#` is always a comment leader in Vim9 script contrary to legacy Vim script).
