### ISSUE TITLE
Top padding of popup window is not drawn correctly when a title has been set

### ISSUE THREAD

**Issue by bfrg** [vim/vim#7460]
**Describe the bug**
The top padding of a popup window isn't drawn correctly (anymore) when a popup title has been specified.

**To Reproduce**
1. Run `vim --clean -S test.vim`, with
   ```vim
   call popup_create(['test 1', 'test 2', 'test 3'], {
           \ 'title': 'Title',
           \ 'border': [],
           \ 'padding': [2,2,2,2]
           \ })
   ```
2. Result: Top padding has wrong color.

**Screenshots**
![screenshot-2020-12-11_233914](https://user-images.githubusercontent.com/6266600/101961802-ca853880-3c0a-11eb-8b42-92e2ec777095.png)

**Environment**
- Vim version `8.2.2127`
- xfce4-terminal

**Comment by lacygoill** [comment]
Regression introduced in [8.2.2024](https://github.com/vim/vim/releases/tag/v8.2.2024).

**Comment by lacygoill** [comment]
cc @rbtnn via https://github.com/vim/vim/pull/7334
