### ISSUE TITLE
Vim9: whitespace not enforced after :exit

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7467]
**Describe the bug**

In Vim9 script, a whitespace is not enforced after `:exit` which can lead to unexpected results.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        job_start(['/bin/sh', '-c', cmd], {
            exit_cb: 0})
    EOF
    )

`E121` and `E116` are raised:

    E121: Undefined variable: cmd
    E116: Invalid arguments for function job_start(['/bin/sh', '-c', cmd], {

This is expected.

Vim closes the current window; since there is only 1 window, Vim quits immediately.
This is not expected.

**Expected behavior**

Vim doesn't close the window and doesn't quit.

**Environment**

 - Vim version: 8.2 Included patches: 1-2135
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(362)

**Additional context**

The issue disappears when `cmd` is replaced with an empty string:
```vim
vim9script
job_start(['/bin/sh', '-c', ''], {
    exit_cb: 0})
```
    ✔

The issue disappears when `exit_cb` is joined with the `job_start()` line:
```vim
vim9script
job_start(['/bin/sh', '-c', cmd], {exit_cb: 0})
```
    E121: Undefined variable: cmd
    E116: Invalid arguments for function job_start(['/bin/sh', '-c', cmd], {exit_cb: 0})

The issue disappears when `exit_cb` is replaced with any other key:
```vim
vim9script
job_start(['/bin/sh', '-c', cmd], {
    out_cb: 0})
```
    E121: Undefined variable: cmd
    E116: Invalid arguments for function job_start(['/bin/sh', '-c', cmd], {
    E492: Not an editor command:     out_cb: 0})

---

Here is what I think happens.

An error is raised from the first line because `cmd` is not defined:

    job_start(['/bin/sh', '-c', cmd], {

Therefore, the next line is parsed as an independent line:

    exit_cb: 0})

Finally, `exit_cb` causes `:exit` to be executed, and `_cb: 0})` is parsed as a filename (see `:h :exit`).

---

It would be nice if a whitespace was enforced after `:exit`, at least in Vim9 script.  This way, the `exit_cb: 0})` line would not cause Vim to close the current window.  Instead, it would raise an error, such as:

    E1234: White space required after ':exit'

More generally, I wonder whether a whitespace should be enforced between a few other Ex commands and their arguments (or maybe even between all Ex commands and their arguments?).

**Comment by lacygoill** [comment]
> It would be nice if a whitespace was enforced after :exit, at least in Vim9 script. This way, the exit_cb: 0}) line would not cause Vim to close the current window.

Although, it would not always prevent the pitfall:
```vim
vim9script
#                ✘ typo
#                v
var list =<< trimx END
    aaaa
    exit
    bbbb
END
```
Still, I think it would make Vim9 scripts a little more predictable (and readable).

**Comment by brammool** [comment]
Currently in Vim script a command directly followed by a character that can't be part of the command is allowed.
Such as ":e#" and ":w/tmp/tt".
The Vim9 script feature to allow for line breaks without a backslash does make it more likely that when parsing a line fails the next line is executed as another command.
Not having white space between the command and the argument is just to save typing a space.  In a script that's hardly relevant, and enforcing the space makes the command easier to read.
Thus I tend to agree: we can enforce the space between the command and the argument.  This avoids the reported problem and makes the script a little bit more readable.

**Comment by lacygoill** [comment]
I wonder whether a whitespace should also be enforced between a custom command and its argument; if only to be consistent with builtin commands:
```vim
vim9
e#
```
    E1144: Command is not followed by white space: e#
```vim
vim9
com -nargs=1 Cmd echom <q-args>
Cmd#
```
    #

**Comment by brammool** [comment]
I do get the error for "Cmd#", I can't guess why you see something different.

**Comment by lacygoill** [comment]
I've checked again:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9
        com -nargs=1 Cmd echom <q-args>
        Cmd#
    EOF
    )

And I don't get any error.  I'm on 8.2.2298:

![gif](https://user-images.githubusercontent.com/8505073/103541816-3c644100-4e9c-11eb-8e3c-fa5e3554c38b.gif)

**Comment by brammool** [comment]
Nope, definitely see the error.  Could it depend on compilation options?

**Comment by brammool** [comment]
Ah, it's an illegal memory access that valgrind doesn't report.
