### ISSUE TITLE
Vim9: :echo and :eval parsed inconsistently between :def function and script level

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7468]
**Describe the bug**

In Vim9 script, `:echo` and `:eval` are parsed inconsistently between a `:def` function and the script level.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            echo
        enddef
        defcompile
    EOF
    )

`E1015` is raised:

    E1015: Name expected:

This is expected.

Now, run this other shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        echo
    EOF
    )

No error is raised.  This is not expected.

**Expected behavior**

`E1015` is also raised when `:echo` is executed without argument at the script level; just like it is in a `:def` function.

**Environment**

 - Vim version: 8.2 Included patches: 1-2135
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(362)

**Additional context**

The same issue affects `:eval`:
```vim
vim9script
eval
```
    E15: Invalid expression:
```vim
vim9script
def Func()
    eval
enddef
defcompile
```
    E1015: Name expected:

I would expect the same error to be raised in both contexts.  Either `E15` or `E1015`.

---

Here is another inconsistency:
```vim
vim9script

eval #{some comment
eval # {some comment

echo #{some comment
echo # {some comment
```
Each of these commands raise `E121`:

    E121: Undefined variable: #

Except the last one which doesn't raise any error.

This is unexpected for 2 reasons:

 - Why is `#` parsed as a variable name? In Vim9 script, `#` should always be parsed as a comment leader (at least since [8.2.2082](https://github.com/vim/vim/releases/tag/v8.2.2082)).
 - Why doesn't the last command raise any error?  If the last but one raises an error, then the last one should too.

I think they should all raise `E1015`, because that's the error raised when `:eval` (or `:echo`) is executed in a `:def` function without argument.

**Comment by lacygoill** [comment]
> I think they should all raise E1015, because that's the error raised when :eval (or :echo) is executed in a :def function without argument.

And because `#` always starts a comment, therefore everything which follows should be ignored (including `#`), and `:echo` as well as `:eval` should be executed without argument.

**Comment by brammool** [comment]
I don't think there is a specific reason to disallow :echo and :exec without an argument only in Vim9 script.
:eval did already give an error for a missing argument, we can keep it like that.
