### ISSUE TITLE
Cannot catch an exception in top level of user command

### ISSUE THREAD

**Issue by thinca** [vim/vim#7469]
**Describe the bug**

Cannnot catch an exception in toplevel of user command.

**To Reproduce**

```vim
function s:throw() abort
  throw 'error'
endfunction

command! Execute
\   try
\ |   let s:x = s:throw()
\ | catch
\ |   echo 'caught'
\ | endtry

Execute
```

Detailed steps to reproduce the behavior:

1. Run `vim --clean -S test.vim`
2. You will see:

```
Error detected while processing command line..script /tmp/test.vim[13]..command line..script /tmp/test.vim[12]..function <SNR>8_throw:
line    1:
E605: Exception not caught: error
```

**Expected behavior**
Show `caught`.

**Environment**
 - Vim version v8.2.2123 (It can be reproduced from v8.2.2094)
 - OS: Arch Linux
 - Terminal: mintty 3.3.0

**Additional context**

It cannot be reproduced when `try` is written on top level.
```vim
function s:throw() abort
  throw 'error'
endfunction

try
  let s:x = s:throw()
catch
  echo 'cought'
endtry
```

It cannot be reproduced when using `call` instead of `let`.
```vim
function s:throw() abort
  throw 'error'
endfunction

command! Execute
\   try
\ |   call s:throw()
\ | catch
\ |   echo 'cought'
\ | endtry

Execute
```

**Comment by brammool** [comment]
Well, when an expression fails it doesn't check for a following command.  It could be halfway an expression and give up.
In this specific case it can work, since the whole expression was parsed.  We could check that a  bar is following, and assume that this indicates a next command.

**Comment by thinca** [comment]
Thank you!
