### ISSUE TITLE
Delete key does not work in insert mode

### ISSUE THREAD

**Issue by ghost** [vim/vim#7470]
**Describe the bug**
Pressing the delete key does not do anything in insert mode

**Steps to reproduce**
1. Run `vim` to enter the editor
2. Press `i` to enter insert mode
3. Insert some random characters
4. Press the escape key to exit insert mode
5. Press `i` to reenter insert mode
6. Press the delete key

**Expected behavior**
The character under the cursor should be deleted.

**Note**
With `vim --clean`, everything works fine, but without `--clean`, the delete key does not work. For reference, my .vimrc is empty.

**Environment**
Vim 8.2.2140
macOS 10.15.7 (19H15)
Terminal 2.10

**Comment by brammool** [comment]
Works as intended, Vi did not allow this, thus in compatible mode it won't work.  Check the 'backspace' option.

**Comment by nickspoons** [comment]
For some more context, when you run `vim --clean` you are telling Vim to use its `defaults.vim` configuration file, just as you are by starting vim with _no_ `.vimrc`. If you have an _empty_ `.vimrc`, you are telling Vim: I want to control my configuration now, don't source `defaults.vim`.

See [:help defaults.vim](http://vimhelp.appspot.com/starting.txt.html#defaults.vim) and [:help --clean](http://vimhelp.appspot.com/starting.txt.html#--clean)
