### ISSUE TITLE
Calling execute() asynchronously corrupts its output

### ISSUE THREAD

**Issue by noscript** [vim/vim#7472]
**Describe the bug**
Calling `execute()` with external command asynchronously messes up the output.

**To Reproduce**
1. Create script `~/async_exec.vim`:

```vim
function! MyFunction()
  echom execute("!bash -c 'for i in {0..9}; do echo $i; sleep 0.1; done'")->split('\r\n')[1:]
endfunction

call timer_start(0, {-> MyFunction()})
call timer_start(0, {-> MyFunction()})
```

2. Run VIM as:
 ```sh
vim -g -f -u NONE +'so ~/async_exec.vim'
```

3. Inspect messages log: `:mes`

The output is:
```
['0', '^@[''0'', ''1'', ''2'', ''3'', ''4'', ''5'', ''6'', ''7'', ''8'', ''9'']1', '2', '3', '4', '5', '6', '7', '8', '9']
```

**Expected behavior**
The output is:
```
['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
```

**Environment:**
 - Vim version: 8.2.2019
 - OS:  Ubuntu 20.04
 - Terminal: GUI

**Comment by lacygoill** [comment]
I always find `:!` weird in a script, unless the shell command needs to be connected to a terminal.

FWIW, I would re-write the code like this:
```vim
function! MyFunction()
  echom expand("`bash -c 'for i in {0..9}; do echo $i; sleep 0.1; done'`", v:true, v:true)
endfunction

call timer_start(0, {-> MyFunction()})
call timer_start(0, {-> MyFunction()})
```

**Comment by noscript** [comment]
@lacygoill that's a nice workaround, thanks!

**Comment by chrisbra** [comment]
> echom execute("!bash -c 'for i in {0..9}; do echo $i; sleep 0.1; done'")->split('\r\n')[1:]

Why would you use `execute()`  in such a case  and not `system()` or `systemlist()` if you want shell commands?

**Comment by noscript** [comment]
@chrisbra https://github.com/vim/vim/issues/6565 `system()` is not interruptible, I suppose `systemlist()` also

**Comment by noscript** [comment]
@lacygoill I seem not able to capture `stderr` using `expand()`
```vim
echom expand('`123 2>&1`')
```
expecting:
```
sh: 1: 123: not found
```

but instead outputs nothing

**UPDATE**: never mind, this works:
```vim
echom expand('`123 2>&1 | cat`')
```

**Comment by brammool** [comment]
Any output from a command started by a timer cannot be controlled by Vim.
Asynchronous stuff does not have any guaranteed sequence, especially for external commands.
Starting a shell can take any amount of time, executing commands in a shell can take any amount of time (including sleep).
So this really has nothing to do with what Vim is doing.

**Comment by noscript** [comment]
@lacygoill is it possible to obtain `v:shell_error` when using ```expand('`...`')```?

**Comment by lacygoill** [comment]
I'm not sure to understand, but it seems that `v:shell_error` is set when Vim runs a shell command which encounters an issue:

    $ vim -Nu NONE

    :echo v:shell_error
    0

    :call expand('`invalid`', v:true, v:true)
    :echo v:shell_error
    127

Or do you mean you want the shell exit code from the shell itself?

    :echo expand('`invalid; echo $?`', v:true, v:true)
    ['127']

**Comment by noscript** [comment]
I'm also trying to preserve `stderr`, so by piping to `cat` I mask the exit code of the original command:
```vim
:call expand('`false 2>&1 | cat`')
:echo v:shell_error
0
```

```vim
:call expand('`false 2>&1 | cat; echo $?`')
:echo v:shell_error
0
```

**Comment by chrisbra** [comment]
this is shell specific, but I guess you want to use `set :sehllcmdflag+=-eo\ pipefail`

Note: I still think using `system()` is a better aproach here.

**Comment by noscript** [comment]
@chrisbra `shellcmdflag` solved it, thanks.

As I stated above, I cannot use `system()` because it may freeze VIM and cannot be interrupted.

**Comment by bfrg** [comment]
If you're worried about freezing, why don't you use `job_start()`? It's a lot cleaner that this awful ```expand('`cmd`')``` hack.

**Comment by noscript** [comment]
I'm not sure if `job_start()` can be used synchronously, otherwise rewriting everything with callbacks is an overkill in my case.
