### ISSUE TITLE
A typo in the docs

### ISSUE THREAD

**Issue by lkintact** [vim/vim#7476]
The sentence in doc/pattern.txt, lines 404-405,
```
If a character is taken literally or not depends on the 'magic' option and the
items mentioned next.
```
should probably be something like
```
If a character is taken literally, it doesn't depend on the 'magic' option and the
items mentioned next.
```

Vim version: 8.2.2144.

**Comment by vim-ml** [comment]
On 2020-12-15 12:34:05-0800, lkintact wrote:
> The sentence in doc/pattern.txt, lines 404-405,
> ```
> If a character is taken literally or not depends on the 'magic' option and the
> items mentioned next.
> ```
> should probably be something like
> ```
> If a character is taken literally, it doesn't depend on the 'magic' option and the
> items mentioned next.
> ```

This isn't a typo. The sentence is stating that the current value of
Vim's `'magic'` option (and the items mentioned after this paragraph)
determines whether a character is interpreted literally in the pattern,
or used as a regex metacharacter.

Perhaps this should be reworded slightly, so it's clearer to the reader:

> Whether a character is taken literally or not depends on the 'magic'
> option, and the items mentioned next.

-- 
	Akshay Hegde

**Comment by brammool** [comment]
> The sentence in doc/pattern.txt, lines 404-405,
> ```
> If a character is taken literally or not depends on the 'magic' option and the
> items mentioned next.
> ```
> should probably be something like
> ```
> If a character is taken literally, it doesn't depend on the 'magic' option and the
> items mentioned next.
> ```

Reading this section of the help by itself it is very hard to
understand.  I think it should be completely rewritten.

-- 
SOLDIER: What?  Ridden on a horse?
ARTHUR:  Yes!
SOLDIER: You're using coconuts!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lkintact** [comment]
@vim-ml Thank you, it makes perfect sense now. 
@vim-ml, @brammool Sorry for that silly misinterpretation and the false alarm. Closing.
