### ISSUE TITLE
Vim9: crash when referring to script-local variable deleted in legacy function

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7483]
**Describe the bug**

In Vim9 script, referring to a script-local variable deleted in a legacy function might make Vim crash.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        var name: string
        def FuncA()
            name = 'test'
        enddef
        FuncA()
        fu FuncB() abort
            unlet! s:name
        endfu
        FuncB()
        def FuncC()
            echo name
        enddef
        FuncC()
    EOF
    )

Vim crashes, or an internal is raised:

    E685: internal error: copy_tv(UNKNOWN)

**Expected behavior**

Vim doesn't crash, and no internal error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-2148
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(362)

**Additional context**

- [backtrace](https://github.com/vim/vim/files/5708956/backtrace.txt)
- [valgrind log](https://github.com/vim/vim/files/5708957/valgrind.log)
- [asan log](https://github.com/vim/vim/files/5708955/asan.log)

---

On my machine (Ubuntu 16.04), Vim crashes systematically.
But in a virtual machine (Ubuntu 18.04), Vim doesn't crash; instead an internal error is raised.
No idea why the difference; in both cases, I compile Vim with the same commands:

    $ make clean
    $ make distclean
    $ git pull
    $ ./configure
    $ make

**Comment by lacygoill** [comment]
I wonder whether Vim should disallow the usage of legacy functions in a Vim9 script, just like it disallows the nesting of a legacy function in a Vim9 function.  I (naively?) think that "progressing" makes sense (legacy → Vim9), while "regressing" does not (Vim9 → legacy); and I suspect that allowing legacy functions in a Vim9 script will create all kind of weird issues such as this one.

What's the purpose of a legacy function in a Vim9 script anyway?

If you want the best performance, readability, reliability (thanks to type checking), then you completely (re-)write your script in Vim9.

If you just want to improve the performance, readability, reliability, *without* (re-)writing your whole script, then you only refactor the few functions which are the slowest/ugliest in Vim9.  But your script remains largely written in Vim script legacy (and no `:vim9script` at the top).

It seems to me that a Vim9 script with no legacy functions, and a legacy script with optionally some Vim9 functions cover most (if not all) need.

**Comment by lacygoill** [comment]
Regression introduced in [8.2.1846](https://github.com/vim/vim/releases/tag/v8.2.1846).

**Comment by brammool** [comment]
> I wonder whether Vim should disallow the usage of legacy functions in
> a Vim9 script, just like it disallows the nesting of a legacy function
> in a Vim9 function.  I (naively?) think that "progressing" makes sense
> (legacy → Vim9), while "regressing" does not (Vim9 → legacy); and I
> suspect that allowing legacy functions in a Vim9 script will create
> all kind of weird issues such as this one.
> 
> What's the purpose of a legacy function in a Vim9 script anyway?

Legacy functions are not compiled, thus provide more flexibility.  E.g.
in tests one can do this:

	func Test_some()
	  CheckFeature terminal
	  terminal some command
	endfunc

This throws an exception at "CheckFeature" and doesn't even try to parse
the rest of the function.  When compiling the function the ":terminal"
command might not exist and compiling fails before the CheckFeature
command is executed.

> If you want the best performance, readability, reliability (thanks to
> type checking), you completely (re-)write your script in Vim9.
> 
> If you just want to improve the performance, readability, reliability,
> *without* (re-)writing your whole script, then you only refactor the
> few functions which are the slowest/ugliest in Vim9.  But your script
> remains largely written in Vim script legacy (and no `:vim9script` at
> the top).
> 
> It seems to me that a Vim9 script with no legacy functions, and a
> legacy script with optionally some Vim9 functions cover most if not
> all need.

It should work best, but in some corner cases it can be useful to use a
legacy function.  And calling a function defined in a legacy script is
probably also quite useful.

-- 
ARTHUR:    ... and I am your king ....
OLD WOMAN: Ooooh!  I didn't know we had a king.  I thought we were an
           autonomous collective ...
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
