### ISSUE TITLE
Vim9: inconsistent usage of dict.name assignment at script-level

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7484]
**Describe the bug**

In Vim9 script, how `dict.name` must be used in an assignment depends on whether we're at the script level or in a `:def` function, which is inconsistent and confusing (because the rules are different for `dict['name']`).

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        var dict = {}
        dict.name = 123
    EOF
    )

`E716` is raised:

    E716: Key not present in Dictionary: "name = 123"

This is unexpected.

---

Run this other shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        var dict = {}
        var dict.name = 123
    EOF
    )

No error is raised.  This is also unexpected.

**Expected behavior**

No error is raised in the first snippet.

`E1017` is raised in the second snippet:

    E1017: Variable already declared: dict

**Environment**

 - Vim version: 8.2 Included patches: 1-2148
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(362)

**Additional context**

In a `:def` function, the first snippet works correctly:
```vim
vim9script
def Func()
    var dict = {}
    dict.name = 123
enddef
defcompile
```
    ✔

In a `:def` function, the second snippet correctly raises `E1017`:
```vim
vim9script
def Func()
    var dict = {}
    var dict.name = 123
enddef
defcompile
```
    E1017: Variable already declared: dict

At the script level, the `dict['name']` assignment syntax works correctly:
```vim
vim9script
var dict = {}
dict['name'] = 123
```
    ✔

---

The `dict.name` assignment syntax was implemented in [8.2.2000](https://github.com/vim/vim/releases/tag/v8.2.2000).

Cc @itchyny via #7312.

**Comment by itchyny** [comment]
Hmm, why implementation in a def function and script-level are different? I'll look into this anyway.
