### ISSUE TITLE
printf() with %{n}.{m}S format didn't handle multibyte character correctly

### ISSUE THREAD

**Issue by obcat** [vim/vim#7486]
**Describe the bug**
Display width of string returned by `printf({fmt}, {expr})` may be wrong.
The followings would be necessary conditions for that bug to occur.

* `{fmt}` is in `%{field-width}{.precision}S` format.
* `{expr}` contains multibyte characters.
* Display width of `{expr}` is greater than `{.precision}`.

**To Reproduce**
```vim
echo printf('[%10.6S]', 'あいうえお')   " [      あいう]  <-+
echo printf('[%10.8S]', 'あいうえお')   " [   あいうえ]   <-+ strange
echo printf('[%10.10S]', 'あいうえお')  " [あいうえお]    <-+
echo printf('[%10.12S]', 'あいうえお')  " [あいうえお]      | expected
echo printf('[%10.14S]', 'あいうえお')  " [あいうえお]      |
echo printf('[%10.16S]', 'あいうえお')  " [あいうえお]    <-+
```

<img width="571" alt="ss 2020-12-18 2 50 07" src="https://user-images.githubusercontent.com/64692680/102524057-c8741b80-40db-11eb-917e-850695ff8b3d.png">

**Expected behavior**
<img width="443" alt="ss 2020-12-18 2 48 14" src="https://user-images.githubusercontent.com/64692680/102523923-995daa00-40db-11eb-9a6c-b05e6e16aa57.png">

**Environment**
 - Vim 8.2.1719
 - macOS Catalina (version 10.15.7)
 - MacVim

**Additional context**
This will occur regardless of the value of `ambiwidth`.

**Comment by lacygoill** [comment]
Just for information, the `%S` item of `printf()` didn't handle multibyte characters correctly until [8.1.2083](https://github.com/vim/vim/releases/tag/v8.1.2083).
