### ISSUE TITLE
Vim9: cannot extend null dictionary stored in script-local variable from :def function

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7491]
**Describe the bug**

In Vim9 script, we cannot extend a null dictionary stored in a script-local variable from a `:def` function.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        var d: dict<any>
        def Func()
            extend(d, {key: 123})
            echom d
        enddef
        Func()
    EOF
    )

`E1133` is raised:

    E1133: Cannot extend a null dict

**Expected behavior**

No error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-2154
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(362)

**Additional context**

No error is raised when the variable is local to a function rather than to the script:
```vim
vim9script
def Func()
    var d: dict<any>
    extend(d, {key: 123})
    echom d
enddef
Func()
```
    {'key': 123}

No error is raised when `extend()` is run at the script level:
```vim
vim9script
var d: dict<any>
extend(d, {key: 123})
echom d
```
    {'key': 123}

This is confusing; if it works in these last 2 snippets, I would expect it also works in the first one.

---

Workaround: specify an empty dictionary in the assignment:

    var d: dict<any> = {}
                    ^---^

Which gives:
```vim
vim9script
var d: dict<any> = {}
def Func()
    extend(d, {key: 123})
    echom d
enddef
Func()
```
    {'key': 123}

---

It might be related to #7251, which was fixed in [8.2.1949](https://github.com/vim/vim/commit/348be7ed07d164970ec0004bc278e254eb0cf5bf).

**Comment by lacygoill** [comment]
The same issue affects lists:
```vim
vim9script
var l: list<any>
def Func()
    extend(l, [123])
    echom l
enddef
Func()
```
    E1134: Cannot extend a null list

However, this time, there exists another workaround; we can use `+=` instead of `extend()`:
```vim
vim9script
var l: list<any>
def Func()
    l += [123]
    echom l
enddef
Func()
```
    [123]

Which is again confusing.  Why can we extend a script-local null list from a `:def` function with `+=` but not with `extend()`?

**Comment by brammool** [comment]
When you call extend() it will use the first argument as the list. If it's null then it can't do anything.
Using += you actually assign to the left hand side of the assignment, thus the result can be stored.

I think the only reliable solution would be that when declaring a list without an assignment, we do allocate a list.
This adds a bit of overhead, but in most cases the list will be used and thus allocated anyway.

**Comment by brammool** [comment]
We can make it a bit more efficient by allocating the list or dict only when getting the value.
