### ISSUE TITLE
Vim9: type checking accepts string passed to cursor() as first argument

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7492]
**Describe the bug**

In Vim9 script, type checking accepts a string passed to `cursor()` as its first argument.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        var lines =<< trim END
            one
            two
            three
        END
        setline(1, lines)
        cursor('2', 1)
    EOF
    )

**Expected behavior**

An error is raised at compile time, because `cursor()` expects a number or a list of numbers as its first argument; not a string.

If for some reason, `cursor()` coerces the string into a number, then the cursor should move onto line 2; and not stay on line 1.

**Environment**

 - Vim version: 8.2 Included patches: 1-2154
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(362)

**Additional context**

Relevant todo item:

https://github.com/vim/vim/blob/0353f56ddb379e7f1a68172fa4743355e04df21e/runtime/doc/todo.txt#L70

**Comment by brammool** [comment]
It's hard to give an error at compile time.  It does accept a string like "$" or a mark.
But an error at runtime is expected.
