### ISSUE TITLE
Native vim support for Julia

### ISSUE THREAD

**Issue by paniash** [vim/vim#7498]
I was wondering if native [Julia](https://julialang.org) support (syntax-highlighting, indentation, etc.) will be added to vim anytime soon. 

**Describe the solution you'd like**

Essentially merging the [julia-vim](https://github.com/JuliaEditorSupport/julia-vim) plugin into vim through runtime files is the intended solution.

Thanks!

**Comment by brammool** [comment]
> I was wondering if native [Julia](https://julialang.org) support
> (syntax-highlighting, indentation, etc.) will be added to vim anytime
> soon. 
> 
> **Describe the solution you'd like**
> 
> Essentially merging the
> [julia-vim](https://github.com/JuliaEditorSupport/julia-vim) plugin
> into vim through runtime files is the intended solution.

You can ask the author or authors of this to give explicit permission
for including the files with the Vim distribution.  And provide a
contact for maintenance.

-- 
BEDEVERE:        Why do you think she is a witch?
SECOND VILLAGER: She turned me into a newt.
BEDEVERE:        A newt?
SECOND VILLAGER: (After looking at himself for some time) I got better.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by paniash** [comment]
@brammool Thanks! I'll do that. :)
