### ISSUE TITLE
Vim9: crash when interrupting timer's callback

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7499]
**Describe the bug**

In Vim9 script, interrupting a timer's callback with `C-c` might make Vim crash.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        set ls=2 stl=%!Stl()
        fu Stl()
            return ''
        endfu
        try | throw '' | catch | endtry
        def Callback(_: any)
            timer_start(50, Callback, {repeat: 2})
        enddef
        call Callback(v:none)
    EOF
    )

Press `C-c` a few times: Vim crashes.

**Expected behavior**

I'm not sure.  On the one hand, this code looks silly, because the timer recalls itself indefinitely and the user gets stuck.  So crashing might be better than having to `$ kill -9` Vim, I don't know.

On the other hand, this behavior is very particular.  That is, the crash only occurs when:

   - the statusline is set with a `%!` function
   - a `:throw` is run from a try/catch
   - the callback is written in Vim9 script

Maybe it means that there is some weird bug which warrants a fix?

**Environment**

 - Vim version: 8.2 Included patches: 1-2160
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(362)

**Additional context**

- [backtrace](https://github.com/vim/vim/files/5719308/backtrace.txt)
- [valgrind log](https://github.com/vim/vim/files/5719309/valgrind.log)
- [asan log](https://github.com/vim/vim/files/5719307/asan.log)

**Comment by brammool** [comment]
I can guess what the problem is and I have a patch that appears to fix it.  Adding a test is a bit complicated though.
