### ISSUE TITLE
Vim9: FuncUndefined event is not triggered when the function is called in a function

### ISSUE THREAD

**Issue by kg8m** [vim/vim#7501]
**Describe the bug**

In Vim9 script, `FuncUndefined` event is not triggered when the function is called in a function.

**To Reproduce**

Run this shell command:

```sh
vim -Nu NONE -S <(cat <<'EOF'
  vim9script
  autocmd FuncUndefined * echo 'FuncUndefined triggered.'
  def Foo()
    Bar()
  enddef
  Foo()
EOF
)
```

`FuncUndefined` event is not triggered when `Bar` is called, so the message "FuncUndefined triggered." doesn't appear.

**Expected behavior**

`FuncUndefined` event is triggered when `Bar` is called and the message "FuncUndefined triggered." appears.

**Screenshots**

\-

**Environment (please complete the following information):**

 - Vim version: 8.2 with patches 1-2146
 - OS: Amazon Linux release 2 / CentOS Linux release 7.7.1908 / macOS 10.15.7
 - Terminal: tmux in iTerm2

**Additional context**

Vim8 script is OK. And top-level calling is OK even if in Vim9 script.

Vim8 script:

```sh
vim -Nu NONE -S <(cat <<'EOF'
  autocmd FuncUndefined * echo 'FuncUndefined triggered.'
  function Foo()
    call Bar()
  endfunction
  call Foo()
EOF
)
```

Vim9 script but top-level calling:

```sh
vim -Nu NONE -S <(cat <<'EOF'
  vim9script
  autocmd FuncUndefined * echo 'FuncUndefined triggered.'
  Foo()
EOF
)
```

`FuncUndefined` event is triggered and the message "FuncUndefined triggered." appears when running these shell scripts.

**Comment by brammool** [comment]
This is an old mechanism I think we should not carry over to Vim9 script.
You can use an autoload function, as mentioned at the help for FuncUndefined.
Or you can import the function, that is not only when it's used though.
I'll add a remark at the help for FuncUndefined.

**Comment by kg8m** [comment]
Thanks for the reply.

I would be happy if `FuncUndefined` event was supported in Vim9 script because it is used for [dein.vim](https://github.com/Shougo/dein.vim)'s lazy loading feature, which can add plugins' runtimepaths when plugins' functions are called. But I'll try another way.

Thank you for all your development. Best regards.

**Comment by brammool** [comment]
> Thanks for the reply.
> 
> I would be happy if `FuncUndefined` event was supported in Vim9 script
> because it is used for
> [dein.vim](https://github.com/Shougo/dein.vim)'s lazy loading feature,
> which can add plugins' runtimepaths when plugins' functions are
> called. But I'll try another way.

The problem is that if we allow for undefined functions in a :def
function we can't give good error messages at compile time.

A workaround is to use a legacy function and call it from the :def
function.  That is a bit of a hack, but since this would be rarely
needed I consider that a valid solution.

	def SomeFunc()
	   # this can be found at compile time
	   LoadOnDemand() 
	enddef

	func LoadOnDemand()
	   " this may trigger FuncUndefined
	   call UnknownFunc()
	endfunc

	defcompile


-- 
Your company is doomed if your primary product is overhead transparencies.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by kg8m** [comment]
Thank you for your kind explanations and an advice of workaround. I didn't have the workaround idea.

I updated my Vim9 scripts. And now they don't depend on `FuncUndefined` event. I wrap a plugin's function and manually add its runtimepath if needed.

```vim
# Case 1: in my vimrc
def MyWrapperFunction()
  if !dein#is_sourced("some-plugin")
    dein#source("some-plugin")
  endif

  SomePluginsOriginalFunction()
enddef
```

```vim
# Case 2: in autoload/my/wrapper.vim
if !dein#is_sourced("some-plugin")
  dein#source("some-plugin")
endif

def my#wrapper#function()
  SomePluginsOriginalFunction()
enddef
```

I'll consider your advice if I encounter a similar situation. Thank you very much!!
