### ISSUE TITLE
Vim9: 'magic' should be ignored

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7509]
**Describe the bug**

In Vim9 script, `'magic'` is not ignored; maybe it should.

**To Reproduce**

Run this shell command:

    vim -es -Nu NONE -S <(cat <<'EOF'
        vim9script
        set nomagic
        setline(1, 'aaa')
        s/./b/g
        :%p
        qa!
    EOF
    )

It outputs `aaa`:

    aaa

And this error was raised:

    E486: Pattern not found: .

**Expected behavior**

It outputs:

    bbb

And no error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-2165
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(362)

**Additional context**

Similar to `'gdefault'`, for a plugin's author, `'magic'` is one more pitfall to be aware of.  You have to include `\m` in your pattern to be sure that it's parsed as if `'magic'` has its default value.

**Comment by brammool** [comment]
True, it's possible to get rid of this backwards-compatibility-breaking behavior.  It's not that easy though, patterns can overrule 'magic' and that must still work.
