### ISSUE TITLE
Vim9: error at ":h variable-types"

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7512]
The help at `:h variable-types` says this:

https://github.com/vim/vim/blob/d24602f43cf1f3c37136fe275b83153c26a406e7/runtime/doc/vim9.txt#L795-L800

This is no longer true.  Since [8.2.1691](https://github.com/vim/vim/releases/tag/v8.2.1691), no error is raised because `list<any>` is accepted where `list<number>` is expected.

So, this code doesn't raise any error, neither at the script level:
```vim
vim9script
g:two = 2
var l: list<number> = [1, g:two]
```
Nor in a `:def` function:
```vim
vim9script
def Func()
    g:two = 2
    var l: list<number> = [1, g:two]
enddef
Func()
```
Same thing with strings:
```vim
vim9script
g:str = 'bbb'
var l: list<string> = ['aaa', g:str]
```
    ✔
```vim
vim9script
def Func()
    g:str = 'bbb'
    var l: list<string> = ['aaa', g:str]
enddef
Func()
```
    ✔

It seems that – originally – type casting served 2 purposes:

   - ignore some type error at compile time when nesting a "public" variable in a composite data
   - ask Vim to perform some type checking at runtime on a public variable

Since 8.2.1691, the first one is no longer relevant.  So, type casting is only useful for the second purpose.  Maybe the help should reflect this change.

---

Btw, type casting doesn't work at the script level:
```vim
vim9script
g:two = 2
var l: list<number> = [1, <number>g:two]
```
    E15: Invalid expression: <number>g:two]

Is it working as intended?

Wouldn't it be useful if we could ask Vim to check the type of a public variable at runtime, even when that variable is referred to at the script level?

**Comment by lacygoill** [comment]
Also, isn't it a bit weird to call this feature "type casting"?  It sounds like it converts the type of a variable, but that's not what it does; it checks whether the type of a variable is correct.  Although, I can't think of a better name.  I guess it can't be called "type checking", because that's already used for when Vim checks the type of *any* variable either at compile time or at runtime, while "type casting" only checks the type of public variable at runtime.

**Comment by lacygoill** [comment]
> Also, isn't it a bit weird to call this feature "type casting"?

Ah, it was probably named like this because – in the past – it coerced the type of a public variable from `any` to whatever the user wanted to.  But this coercion is no longer necessary, so naming the feature according to this might be confusing.

**Comment by lacygoill** [comment]
FWIW, I would also move the help tag a few lines earlier, because when executing `:h type-casting`, it's a bit weird to jump in the middle of the explanation.  We're missing some context.
```diff
diff --git a/runtime/doc/vim9.txt b/runtime/doc/vim9.txt
index 1872b82ee..a49ad5bb0 100644
--- a/runtime/doc/vim9.txt
+++ b/runtime/doc/vim9.txt
@@ -791,14 +791,14 @@ specified explicitly or inferred from the initialization.
 Global, buffer, window and tab page variables do not have a specific type, the
 value can be changed at any time, possibly changing the type.  Therefore, in
 compiled code the "any" type is assumed.
-
+							*type-casting*
 This can be a problem when the "any" type is undesired and the actual type is
 expected to always be the same.  For example, when declaring a list: >
 	var l: list<number> = [1, g:two]
 This will give an error, because "g:two" has type "any".  To avoid this, use a
 type cast: >
 	var l: list<number> = [1, <number>g:two]
-<							*type-casting*
+<
 The compiled code will then check that "g:two" is a number at runtime and give
 an error if it isn't.  This is called type casting.
 
```

**Comment by brammool** [comment]
> The help at `:h variable-types` says this:
> 
> https://github.com/vim/vim/blob/d24602f43cf1f3c37136fe275b83153c26a406e7/runtime/doc/vim9.txt#L795-L800
> 
> This is no longer true.  Since [8.2.1691](https://github.com/vim/vim/releases/tag/v8.2.1691), no error is raised because `list<any>` is accepted where `list<number>` is expected.
> 
> So, this code doesn't raise any error, neither at the script level:
> ```vim
> vim9script
> g:two = 2
> var l: list<number> = [1, g:two]
> ```
> Nor in a `:def` function:
> ```vim
> vim9script
> def Func()
>     g:two = 2
>     var l: list<number> = [1, g:two]
> enddef
> Func()
> ```
> Same thing with strings:
> ```vim
> vim9script
> g:str = 'bbb'
> var l: list<string> = ['aaa', g:str]
> ```
>     ✔
> ```vim
> vim9script
> def Func()
>     g:str = 'bbb'
>     var l: list<string> = ['aaa', g:str]
> enddef
> Func()
> ```
>     ✔
> 
> It seems that – originally – type casting served 2 purposes:
> 
>    - ignore some type error at compile time when nesting a "public" variable in a composite data
>    - ask Vim to perform some type checking at runtime on a public variable
> 
> Since 8.2.1691, the first one is no longer relevant.  So, type casting
> is only useful for the second purpose.  Maybe the help should reflect
> this change.

Yeah, this changed a bit after discussions. There now is a check that
the result of the expression matches the type of the variable at
runtime.  This was needed e.g. when calling a builtin function.

The text can be adjusted for this:

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

Variable types and type casting	~
							*variable-types*
Variables declared in Vim9 script or in a `:def` function have a type, either
specified explicitly or inferred from the initialization.

Global, buffer, window and tab page variables do not have a specific type, the
value can be changed at any time, possibly changing the type.  Therefore, in
compiled code the "any" type is assumed.

This can be a problem when the "any" type is undesired and the actual type is
expected to always be the same.  For example, when declaring a list: >
	var l: list<number> = [1, g:two]
At compile time Vim doesn't know the type of "g:two" and the expression type
becomes list<any>.  An instruction is generated to check the list type before
doing the assignment, which is a bit inefficient.
							*type-casting*
To avoid this, use a type cast: >
	var l: list<number> = [1, <number>g:two]
The compiled code will then only check that "g:two" is a number and give an
error if it isn't.  This is called type casting.

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

> Btw, type casting doesn't work at the script level:
> ```vim
> vim9script
> g:two = 2
> var l: list<number> = [1, <number>g:two]
> ```
>     E15: Invalid expression: <number>g:two]
> 
> Is it working as intended?

That isn't implemented yet.  It should work the same was as in a :def
function.

> Wouldn't it be useful if we could ask Vim to check the type of a
> public variable at runtime, even when that variable is referred to at
> the script level?

Yes.


-- 
It doesn't really matter what great things you are able to do if
you don't do any of them.  (Bram Moolenaar)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
Fixed by https://github.com/vim/vim/commit/4072ba571babd733d1800c082416fe8fe3c28ed7.
