### ISSUE TITLE
could cfile handle special character in file name under the cursor?

### ISSUE THREAD

**Issue by huangyingw** [vim/vim#7523]
suppose file name under the cursor is as following:
front/node_modules/@ethersproject/web/lib.esm/geturl.js

when I press gf, vim will go to folder front/node_modules, instead of going to file geturl.js.

**Comment by lacygoill** [comment]
Try to include the `@` character in ['isfname'](https://vimhelp.org/options.txt.html#'isf'):

    set isfname+=@-@

**Comment by huangyingw** [comment]
cool, it works, thanks.
