### ISSUE TITLE
Vim9: should we allow :const with a global variable?

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7526]
**Describe the bug**

In Vim9 script, we cannot use `:const` with a global variable.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        const g:NAME = 123
    EOF
    )

    E1016: Cannot declare a global variable: g:NAME

**Expected behavior**

I'm not sure.  On the one hand, I understand the error.  `:const` is equivalent to `:var` + `:lockvar`, but `:var` is disallowed with a global variable.

On the other hand, it's inconvenient to have to use `:lockvar`:
```vim
vim9script
g:NAME = 123
lockvar g:NAME
```
Also, it creates an inconsistency with Vim script legacy, where a global constant can be created in one single line, while in Vim9 we need two of them.

Should we allow `:const` (and `:final`) to be used with "public" variables (global, buffer-local, ...)?  So that we can keep creating constants in one single line, regardless of their scopes, just like in Vim script legacy.

**Environment**

 - Vim version: 8.2 Included patches: 1-2186
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(362)

**Comment by brammool** [comment]
Yes, const and final should work.  I'll see if we make this consistent.
