### ISSUE TITLE
internal error when creating popup attached to text property

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7528]
**Describe the bug**

Creating a popup window attached to a text property might raise an internal error.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        call range(2)->setline(1)
        call prop_type_add('popupNumberColumn', {})
        call prop_add(1, 1, {'type': 'popupNumberColumn'})
        call popup_create('', {'textprop': 'popupNumberColumn'})
        $
        h
        call feedkeys("\r", 'xt')
    EOF
    )

`E315` and `E967` are raised:

    E315: ml_get: invalid lnum: 3
    E967: text property info corrupted

**Expected behavior**

No error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-2188
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(362)

**Additional context**

[backtrace](https://github.com/vim/vim/files/5731125/backtrace.txt)

**Comment by brammool** [comment]
I cannot reproduce this one

**Comment by lacygoill** [comment]
> I cannot reproduce this one

Ah, I think it's because the issue is influenced by the terminal's height; the latter seems to need at least 24 lines.  Here is a new snippet which should work better:
```vim
set lines=24
call range(2)->setline(1)
call prop_type_add('popupNumberColumn', {})
call prop_add(1, 1, {'type': 'popupNumberColumn'})
call popup_create('', {'textprop': 'popupNumberColumn'})
$
h
call feedkeys("\r", 'xt')
```

**Comment by lacygoill** [comment]
> Ah, I think it's because the issue is influenced by the terminal's height; the latter seems to need at least 24 lines.  Here is a new snippet which should work better:

I meant less than 24 lines, sorry.  I can reproduce with a default geometry (80 colums x 24 lines).

**Comment by lacygoill** [comment]
Here is another one:
```vim
call range(9999)->setline(1)
call prop_type_add('popupNumberColumn', {})
call prop_add(1, 1, {'type': 'popupNumberColumn'})
call popup_create('', {'textprop': 'popupNumberColumn'})
$
h
call feedkeys("\r", 'xt')
```
It should work no matter the terminal's geometry.

**Comment by lacygoill** [comment]
> It should work no matter the terminal's geometry.

But it needs to be sourced like this:

    vim -Nu NONE -S <(cat <<'EOF'
        call range(9999)->setline(1)
        call prop_type_add('popupNumberColumn', {})
        call prop_add(1, 1, {'type': 'popupNumberColumn'})
        call popup_create('', {'textprop': 'popupNumberColumn'})
        $
        h
        call feedkeys("\r", 'xt')
    EOF
    )

**Comment by lacygoill** [comment]
> It should work no matter the terminal's geometry.

Ah no, it doesn't work with any geometry, but it works with 80 columns x 24 lines.

**Comment by lacygoill** [comment]
> Ah no, it doesn't work with any geometry, but it works with 80 columns x 24 lines.

After doing a few more tests, it's more complex than that.

Depending on the height of the terminal:

   1. there can be no issue
   2. there can be an internal error and a text property info might be corrupted
   3. there can be no error but Vim ends in a messed up state

`1.` happens when the buffer displayed in the bottom split contains fewer lines than what its window can display.
`2.` and `3.` happen when the buffer displayed in the bottom split contains more lines than what its window can display.  `2.` happens below a certain height; `3.` happens above.

Here is a gif showing the messed up state in which Vim ends up in `3.`:

![gif](https://user-images.githubusercontent.com/8505073/102995141-b1d92480-4520-11eb-8846-a44df02617a1.gif)

So, here is a command which guarantees the internal error to be raised:

    vim -Nu NONE -S <(cat <<'EOF'
        set lines=24
        call range(2)->setline(1)
        call prop_type_add('popupNumberColumn', {})
        call prop_add(1, 1, {'type': 'popupNumberColumn'})
        call popup_create('', {'textprop': 'popupNumberColumn'})
        $
        h
        call feedkeys("\r", 'xt')
    EOF
    )

And here is another command which does not raise an internal error, but causes Vim to end in a messed up state:

    vim --clean -S <(cat <<'EOF'
        set lines=42
        call range(999)->setline(1)
        call prop_type_add('popupNumberColumn', {})
        call prop_add(1, 1, {'type': 'popupNumberColumn'})
        call popup_create('', {'textprop': 'popupNumberColumn'})
        $
        h
        call feedkeys("\r", 'xt')
    EOF
    )
