### ISSUE TITLE
Async popup menu updates corrupt in console vim

### ISSUE THREAD

**Issue by liskin** [vim/vim#7537]
**Describe the bug**
If popup menu is changed asynchronously (timer or after language server reply), it is not redrawn properly in console vim. Instead, the menu seems to show contents of memory that's been freed and is now used for something else.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. `/tmp/popup.vim`:

    ```
    set nocompatible
    set mouse=a
    set mousemodel=popup_setpos
    
    anoremenu <silent> PopUp.AAAAAAAA :echo "a1"<CR>
    anoremenu <silent> PopUp.BBBBBBBB :echo "b1"<CR>
    autocmd MenuPopup * :call s:popup1()
    
    func s:popup1()
    	call timer_start(1000, {-> s:popup2()})
    endfunc
    
    func s:popup2()
    	silent! aunmenu PopUp.AAAAAAAA
    	silent! aunmenu PopUp.BBBBBBBB
    	silent! aunmenu PopUp.CCCCCCCC
    	silent! anoremenu <silent> PopUp.AAAAAAAA :echo "a2"<CR>
    	silent! anoremenu <silent> PopUp.BBBBBBBB :echo "b2"<CR>
    	silent! anoremenu <silent> PopUp.CCCCCCCC :echo "c2"<CR>
    endfunc
    ```
2. `vim -U NONE -u /tmp/popup.vim --noplugin`
3. right click to show the popup menu
4. wait a second
5. one of the menu entries is replaced with `^C:echo "`, and the third entry doesn't appear; in gvim this works fine

**Expected behavior**
I expect the menu to be updated just like it is in gvim.

**Screenshots**
https://user-images.githubusercontent.com/300342/103034344-f686af00-4564-11eb-87f8-f74457ea2742.mp4

**Environment (please complete the following information):**

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 23 2020 19:48:05)
Included patches: 1-2199
Compiled by tomi@notes.lisk.in
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
-autoservername    +folding           +multi_byte        +termguicolors
+balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
+browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              -perl              +title
+clientserver      +job               +persistent_undo   +toolbar
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           -python            +visual
+conceal           +linebreak         +python3           +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       -lua               -ruby              +wildmenu
+dialog_con_gui    +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       +X11
+dnd               +mouse             -sound             -xfontset
-ebcdic            +mouseshape        +spell             +xim
+emacs_tags        +mouse_dec         +startuptime       +xpm
+eval              -mouse_gpm         +statusline        +xsmp_interact
+ex_extra          -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -O2 -fno-strength-reduce -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: gcc -L/usr/local/lib -Wl,--as-needed -o vim -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lharfbuzz -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE -lm -ltinfo -lelf -lselinux -ldl -L/usr/lib/python3.9/config-3.9-x86_64-linux-gnu -lpython3.9 -lcrypt -lpthread -ldl -lutil -lm -lm 
```
OS: Debian testing
Terminal: rxvt-unicode 

**Additional context**
This seems like a weird usecase, but it's being used by the ale plugin to populate the popup menu with LSP code actions that are possible _at that position_, and it's done asynchronously because all LSP communication in ale is done async: https://github.com/dense-analysis/ale/blob/master/autoload/ale/code_action.vim#L345-L356

**Comment by liskin** [comment]
Thanks for the fix.

There are still 2 issues after https://github.com/vim/vim/commit/38455a921395a56690790c8c1d28c1c43ca04c8a, however:

1. If all PopUp.* entries are unmenued and recreated, no command is executed after selecting a menu item, presumably because the entire PopUp menu itself gets freed and the call to `pum_execute_menu` operates on stale data. This is reproducible with the `popup.vim` above.

2. When the menu isn't completely unmenued, but only some items are removed and completely different items are added, selecting an entry that was removed executes the newly added entry instead of the one that is visible (the menu is not redrawn, as it is in gvim). This is reproducible using the following:

    ```
    set nocompatible
    set mouse=a
    set mousemodel=popup_setpos
    
    anoremenu <silent> PopUp.AAAAAAAA :echo "a1"<CR>
    anoremenu <silent> PopUp.BBBBBBBB :echo "b1"<CR>
    autocmd MenuPopup * :call s:popup1()
    
    func s:popup1()
    	call timer_start(1000, {-> s:popup2()})
    endfunc
    
    func s:popup2()
    	silent! aunmenu PopUp.BBBBBBBB
    	silent! anoremenu <silent> PopUp.DDDDDDDD :echo "d2"<CR>
    	silent! anoremenu <silent> PopUp.EEEEEEEE :echo "e2"<CR>
    endfunc
    ```

**Comment by brammool** [comment]
Tomáš Janoušek wrote:

> Thanks for the fix.
> 
> There are still 2 issues after https://github.com/vim/vim/commit/38455a921395a56690790c8c1d28c1c43ca04c8a, however:
> 
> 1. If all PopUp.* entries are unmenued and recreated, no command is
> executed after selecting a menu item, presumably because the entire
> PopUp menu itself gets freed and the call to `pum_execute_menu`
> operates on stale data. This is reproducible with the `popup.vim`
> above.

You are not supposed to change the menu while it's being displayed.  In
the GUI this may work, because it uses the library functions of the GUI
library.  In the console we display the menu and it won't be updated
dynamically.  The only thing the patch does is avoid crashing when the
menu is changed anyway.

It's a bit weird to change the menu "under the fingers" of the user.
Just when you want to select an item it changes?  Or might even move to
another position?

> 2. When the menu isn't completely unmenued, but only some items are
> removed and completely different items are added, selecting an entry
> that was removed executes the newly added entry instead of the one
> that is visible (the menu is not redrawn, as it is in gvim). This is
> reproducible using the following:
> 
>     ```
>     set nocompatible
>     set mouse=a
>     set mousemodel=popup_setpos
>     
>     anoremenu <silent> PopUp.AAAAAAAA :echo "a1"<CR>
>     anoremenu <silent> PopUp.BBBBBBBB :echo "b1"<CR>
>     autocmd MenuPopup * :call s:popup1()
>     
>     func s:popup1()
>     	call timer_start(1000, {-> s:popup2()})
>     endfunc
>     
>     func s:popup2()
>     	silent! aunmenu PopUp.BBBBBBBB
>     	silent! anoremenu <silent> PopUp.DDDDDDDD :echo "d2"<CR>
>     	silent! anoremenu <silent> PopUp.EEEEEEEE :echo "e2"<CR>
>     endfunc
>     ```

Yes, the selection works by index, thus if you change the entries there
is a mismatch between the index and the items that are displayed.  It
might be possible to improve this, but since some items won't work
anyway it will always be somewhat crippled.

-- 
How To Keep A Healthy Level Of Insanity:
2. Page yourself over the intercom. Don't disguise your voice.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by liskin** [comment]
Oh, so this is intended then, all right. I'll pass this info to the ale maintainers and see what we can do there.
