### ISSUE TITLE
Vim9: cannot use :lockvar and :unlockvar in :def function

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7538]
**Describe the bug**

In Vim9 script, we cannot use `:lockvar` nor `:unlockvar` in a `:def` function.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        var name = 0
        def Func()
            lockvar name
        enddef
        defcompile
    EOF
    )

This error message is printed:

    Sorry, :lock and unlock not implemented yet

**Expected behavior**

No error is printed.  `name` is locked.

**Environment**

 - Vim version: 8.2 Included patches: 1-2201
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: X.Org 7.7.0(362)

**Additional context**

Same issue with `:unlockvar`:
```vim
vim9script
const name = 0
def Func()
    unlockvar name
enddef
defcompile
```
    Sorry, :lock and unlock not implemented yet

---

I created this issue because there is no todo item for these commands.

**Comment by brammool** [comment]
> **Describe the bug**
> 
> In Vim9 script, we cannot use `:lockvar` nor `:unlockvar` in a `:def` function.
> 
> **To Reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(cat <<'EOF'
>         vim9script
>         var name = 0
>         def Func()
>             lockvar name
>         enddef
>         defcompile
>     EOF
>     )
> 
> This error message is printed:
> 
>     Sorry, :lock and unlock not implemented yet
> 
> **Expected behavior**
> 
> No error is printed.  `name` is locked.
> 
> **Environment**
> 
>  - Vim version: 8.2 Included patches: 1-2201
>  - OS: Ubuntu 16.04.7 LTS
>  - Terminal: X.Org 7.7.0(362)
> 
> **Additional context**
> 
> Same issue with `:unlockvar`:
> ```vim
> vim9script
> const name = 0
> def Func()
>     unlockvar name
> enddef
> defcompile
> ```
>     Sorry, :lock and unlock not implemented yet
> 
> ---
> 
> I created this issue because there is no todo item for these commands.

There is a TODO in the code.

I have been wondering if :lockvar and :unlockvar should be allowed to
use on local variables.  It's a bit like changing the type.  Also, I
don't know another language that has this mechanism.  Perhaps we should
only allow using it for global/window/buffer variables.  Use :const and
:final for local variables.

-- 
How To Keep A Healthy Level Of Insanity:
8. Don't use any punctuation marks.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> I have been wondering if :lockvar and :unlockvar should be allowed to
> use on local variables.  It's a bit like changing the type.  Also, I
> don't know another language that has this mechanism.  Perhaps we should
> only allow using it for global/window/buffer variables.  Use :const and
> :final for local variables.

There is [a plugin](https://github.com/tpope/vim-flagship/blob/e522bd0ffb0e329f695ead7d4288a6245ff22410/autoload/flagship.vim#L605-L607) which locks and unlocks a script-local variable.  It does that because it provides a public function which lets users add flags in their statusline.  The information is saved in a script-local variable, but the author doesn't want the variable to be altered outside this function.

Although, it's the only case I can think of, so probably not enough to take a design decision solely based on that.

In this example, if `:lockvar` was disallowed for script-local variables, I guess we could use an autoload variable instead.  The latter is global, so the restriction should not apply.

**Comment by lacygoill** [comment]
> There is a TODO in the code.

Ok, closing then.
