### ISSUE TITLE
Vim9: cannot access function-local variable from global command

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7541]
**Describe the bug**

In Vim9 script, we cannot access a function-local variable from a global command run in the same function.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            var name = 'test'
            g/^/echo name
        enddef
        Func()
    EOF
    )

`E121` is raised:

    E121: Undefined variable: name

**Expected behavior**

No error is raised.  `test` is echo'ed.

**Environment**

 - Vim version: 8.2 Included patches: 1-2201
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(362)

**Additional context**

This is not the same issue as #7410.  The latter was about a local function, and was fixed in [8.2.2170](https://github.com/vim/vim/releases/tag/v8.2.2170).  The current issue is about a local variable.

---

This is not just a theoretical issue; I'm encountering it regularly.  I guess one workaround is to use an `:exe`:
```vim
vim9script
def Func()
    var name = 'test'
    exe 'g/^/echo ' .. name->string()
enddef
Func()
```
But that's a bit ugly.

---

In Vim script legacy, no error is raised:
```vim
vim9script
fu Func()
    let name = 'test'
    g/^/echo name
endfu
Func()
```
---

Same issue when `:put`ting an expression from a global command:
```vim
vim9script
def Func()
    var name = 'word'
    g/^/pu =name
enddef
Func()
```
    E121: Undefined variable: name

And again, the equivalent in Vim script legacy works just fine:
```vim
fu Func()
    let name = 'word'
    g/^/pu =name
endfu
call Func()
```
---

Same issue with the replacement field of a substitution command:
```vim
vim9script
setline(1, 'xord')
def Func()
    var name = 'w'
    s/x/\=name/
enddef
Func()
```
    E121: Undefined variable: name

Again, in Vim script legacy, no error is raised:
```vim
vim9script
setline(1, 'xord')
fu Func()
    let name = 'w'
    s/x/\=name/
endfu
Func()
```
---

I haven't found a relevant todo item, although there is this:

https://github.com/vim/vim/blob/07761a3b965ec3be0c8d52aae9b6dc09c2127d27/runtime/doc/todo.txt#L82

Once Vim9 compiles `\=expr`, then maybe the error will disappear when we use a local variable in the replacement field of a substitution.  I say this because of [this comment](https://github.com/vim/vim/issues/6868#issuecomment-687284964):

   > assert_fails() runs the command in the current context, where "d" is not define, it's on the stack.
   > For Ex commands that evaluate an expression we already have code to not call the normal handling, but compile it, so that the variables on the stack can be found.

I assume Vim can't find `expr` because it's on the stack, while `:s` runs in the global context, where `expr` can't be found.

If my assumption is correct, then the error raised by a global command which refers to a local variable has the same cause, right?  The global command is run in the global context, while the variables of the function are on the stack.  If so, compiling the command executed by `:global` would fix the issue, right?  Is this possible without introducing too much inefficiency?

---

If all of this is working as intended or can't be fixed, then maybe it should be documented at `:h vim9 /Limitations`.

**Comment by lacygoill** [comment]
Same issue when the variable contains a funcref.  This worked fine in Vim script legacy:
```vim
vim9script
fu Func()
    let l:Funcref = {-> 'local funcref'}
    g/^/echo Funcref()
endfu
Func()
```
    local funcref

But no longer works in Vim9 script:
```vim
vim9script
def Func()
    var Funcref = {-> 'local funcref'}
    g/^/echo Funcref()
enddef
Func()
```
    E117: Unknown function: Funcref

**Comment by lacygoill** [comment]
> Same issue when the variable contains a funcref.

Since 8.2.2170, we can work around this particular pitfall by making the funcref global:
```vim
vim9script
def Func()
    g:Funcref = {-> 'global funcref'}
    g/^/echo g:Funcref()
enddef
Func()
```
    global funcref

But this pollutes the global namespace, and might overwrite some variable used by another plugin, which in turn could cause other issues.

**Comment by brammool** [comment]
It is simply not possible to access the compiled code and variables from interpreted code.
The closest we get is using `=expr`, which was already expanded in a few places.
I can make it work for :global too, let's give that a try.  I'm not sure it fully works, since any command may follow :g/pattern/

**Comment by brammool** [comment]
Hmm, github eats the backticks which are around =expr

**Comment by lacygoill** [comment]
> It is simply not possible to access the compiled code and variables from interpreted code.

Ok, I understand.

> The closest we get is using =expr, which was already expanded in a few places.
> I can make it work for :global too, let's give that a try. I'm not sure it fully works, since any command may follow :g/pattern/

I've just tested the change, and while it works for a command which expects a filename:
```vim
vim9script
def Func()
    var name = 'test'
    g/^/e `=name`
enddef
Func()
```
    ✔
It doesn't work when the command expects an expression:
```vim
vim9script
def Func()
    var name = 'test'
    g/^/echo `=name`
enddef
Func()
```
    E121: Undefined variable: test

---

The last time I've encountered this issue, here is what the code looked like:
```vim
vim9script
def Func()
    ...
    var tempdir = tempname()->substitute('.*/\zs.\{-}', '', '')
    ...
    sil keepj keepp :'x+,'y-g/^./exe 'keepalt r ' .. tempdir .. '/' .. getline('.')[2:]
enddef
```
And when `:g` was executed, Vim complained that `tempdir` was an unknown variable.  The code worked in Vim script legacy, so I was a bit surprised.

---

I think I've found a good workaround: use a script-local funcref.
```vim
vim9script
var Funcref: func
def Func()
    var name = 'test'
    Funcref = () => name
    g/^/echo Funcref()
enddef
Func()
```
```vim
vim9script
var Rep: func
def Func()
    setline(1, 'xx')
    var name = 'foobar'
    Rep = () => name
    g/^xx/s/.*/\=Rep()
enddef
Func()
```
   - it's much more readable than an `:exe`
   - it doesn't pollute the global namespace
   - I prefer a funcref over the new backtick syntax because:

        * it also works in Vim script legacy
        * it works no matter the command
        * it can also be used to access any function-local variable from an autocmd installed inside a function

---

Since this is one case where Vim9 works differently than Vim script legacy, I think it should be documented at `:h vim9-gotchas`.  If necessary, I can try to write a patch to update the help, so that people know how to handle the issue.

**Comment by lacygoill** [comment]
> it also works in Vim script legacy

Example adapting the test in the patch 8.2.2215:
```vim
vim9script
fu Func()
    call setline(1, 'xx')
    let name = 'foobar'
    let s:Rep = {-> name}
    g/^xx/s/.*/\=s:Rep()
endfu
call Func()
```
---

> it works no matter the command

Example when putting the expression register from a global command (which doesn't work with the new backtick syntax):
```vim
vim9script
var This: func
def Func()
    var name = 'test'
    This = () => name
    g/^/pu =This()
enddef
Func()
```
---

> it can also be used to access any function-local variable from an autocmd installed inside a function

Example:
```vim
vim9script
var FromFunc: func
def Func()
   var name = 'defined in function'
   FromFunc = () => name
   au SafeState * ++once echom FromFunc()
enddef
Func()
```
---

> If necessary, I can try to write a patch to update the help, so that people know how to handle the issue.

Here is a suggestion:

```diff
diff --git a/runtime/doc/vim9.txt b/runtime/doc/vim9.txt
index d68d936e5..ff0a2d90d 100644
--- a/runtime/doc/vim9.txt
+++ b/runtime/doc/vim9.txt
@@ -737,16 +737,33 @@ prefix and they do not need to exist (they can be deleted any time).
 Limitations ~
 
 Local variables will not be visible to string evaluation.  For example: >
-	def EvalString(): list<string>
+	def UseEvalString(): list<string>
 	  var list = ['aa', 'bb', 'cc', 'dd']
 	  return range(1, 2)->map('list[v:val]')
 	enddef
 
 The map argument is a string expression, which is evaluated without the
 function scope.  Instead, use a lambda: >
-	def EvalString(): list<string>
+	def UseLambda(): list<string>
 	  var list = ['aa', 'bb', 'cc', 'dd']
-	  return range(1, 2)->map({ _, v -> list[v] })
+	  return range(1, 2)->map((_, v) => list[v])
+	enddef
+
+Local variables will not be visible in a global command either.  For example: >
+	def Func()
+	  var name = 'set in function'
+	  g/^/put =name
+	enddef
+
+It is simply not possible to access the compiled code and variables from
+interpreted code.  Instead, use a script-local lambda: >
+	var This: func
+	def UseLambda()
+	  var name = 'set in function'
+	  This = () => name
+	  g/^/put =This()
 	enddef
 
 
```
This also renames the `EvalString()` function in the second example into `UseLambda()`, because the former looks misleading, since it doesn't use an eval string but a lambda.  And it also refactors the old `{arg -> expr}` syntax into the new `(arg) => expr` syntax.

**Comment by brammool** [comment]
> > It is simply not possible to access the compiled code and variables
> > from interpreted code.
> 
> Ok, I understand.
> 
> > The closest we get is using =expr, which was already expanded in a
> > few places.
> > I can make it work for :global too, let's give that a try. I'm not
> > sure it fully works, since any command may follow :g/pattern/
> 
> I've just tested the change, and while it works for a command which
> expects a filename:
> ```vim
> vim9script
> def Func()
>     var name = 'test'
>     g/^/e `=name`
> enddef
> Func()
> ```
>     ✔
> It doesn't work when the command expects an expression:
> ```vim
> vim9script
> def Func()
>     var name = 'test'
>     g/^/echo `=name`
> enddef
> Func()
> ```
>     E121: Undefined variable: test

The value of the variable is inserted in place, thus if you want to use
it as a string you need to add quotes:
	 def Func()
	     var name = 'test'
	     g/^/echo "`=name`"
	 enddef
 
> The last time I've encountered this issue, here is what the code looked like:
> ```vim
> vim9script
> def Func()
>     ...
>     var tempdir = tempname()->substitute('.*/\zs.\{-}', '', '')
>     ...
>     sil keepj keepp :'x+,'y-g/^./exe 'keepalt r ' .. tempdir .. '/' .. getline('.')[2:]
> enddef
> ```
> And when `:g` was executed, Vim complained that `tempdir` was an
> unknown variable.  The code worked in Vim script legacy, so I was a
> bit surprised.

Compiling instructions will result in some differences from purely
interpreted commands.  That is unavoidable.

> I think I've found a good workaround: use a script-local funcref.
> ```vim
> vim9script
> var Funcref: func
> def Func()
>     var name = 'test'
>     Funcref = () => name
>     g/^/echo Funcref()
> enddef
> Func()
> ```
> ```vim
> vim9script
> var Rep: func
> def Func()
>     setline(1, 'xx')
>     var name = 'foobar'
>     Rep = () => name
>     g/^xx/s/.*/\=Rep()
> enddef
> Func()
> ```
>    - it's much more readable than an `:exe`
>    - it doesn't pollute the global namespace
>    - I prefer a funcref over the new backtick syntax because:
> 
>         * it also works in Vim script legacy
>         * it works no matter the command
>         * it can also be used to access any function-local variable from an autocmd installed inside a function

Well, I think using the backtick notation is simpler, but you have the
choice.

-- 
One difference between a man and a machine is that a machine is quiet
when well oiled.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> The value of the variable is inserted in place, thus if you want to use
> it as a string you need to add quotes:

Oh right.  I simply missed the quotes.

> Well, I think using the backtick notation is simpler, but you have the
> choice.

Now that I better understand them, I agree.  If I want to access only one variable, I'll use the backtick syntax.  If I need to do something more complex or have access to more variables, then I'll consider the script-local lambda.

**Comment by lacygoill** [comment]
> I don't think `=expr` is evaluated for an :echo command.

Yes, in Vim script legacy, I think a backtick expansion is only evaluated for a command which expects a filename, like `:edit` and `:vimgrep`.  `:echo` does not expect a filename but an expression, therefore a backtick expansion should not work after `:echo`.

Nevertheless, I still thought it would work for several reasons.

First, it already works in a global command:
```vim
vim9
def Func()
    var name = 'test'
    g/^/echo '`=name`'
enddef
Func()
```
    test

Second, it was mentioned in [this comment](https://github.com/vim/vim/issues/7541#issuecomment-751354672):

   > The value of the variable is inserted in place, thus if you want to use
   > it as a string you need to add quotes:
   >          def Func()
   >              var name = 'test'
   >              g/^/echo "`=name`"
   >          enddef

Third, it is documented as working in the replacement field of a substitution command:

https://github.com/vim/vim/blob/b23279d7a2d28de5df942924b77cf23672fc684f/runtime/doc/vim9.txt#L800-L805

And indeed, it works as documented:
```vim
vim9
def Replace()
  setline(1, 'pattern')
  var newText = 'blah'
  g/pattern/s/^/`=newText`/
enddef
Replace()
echo getline(1)
```
    blahpattern

But this doesn't work in Vim script legacy:
```vim
fu Replace()
  call setline(1, 'pattern')
  let newText = 'blah'
  g/pattern/s/^/`=newText`/
endfu
call Replace()
echo getline(1)
```
    `=newText`pattern

Which means that the syntax has been made valid in more contexts than it was initially designed for.  As I didn't know which contexts it was valid in, I assumed it was valid everywhere.

Fourth, we can no longer access a function-local variable in a command which is executed in the global context like `:g` or `:s`.  For those cases, the backtick expansion could be useful.

That being said, I can understand that we don't allow the syntax to work in too many places, to avoid unexpected expansions.  And I don't mind if it's limited to commands expecting filenames as arguments and the replacement field of `:s`.  That's because it doesn't always work anyway.  For example, the last time I was tempted to use it, I had to execute an assignment in a `:folddoclosed` and a `:folddoopen` command; but the assignment involved a function-local dictionary variable:

    " inside a function
    let state = {'open': [], 'closed': []}
    folddoclosed let state.closed += s:get_state('closed')
    folddoopen let state.open += s:get_state('open')

The code worked fine in Vim script legacy, but not in Vim9.  I wasn't able to use a backtick expansion either.  So, in the end, I moved the function-local variable to the script-local namespace:

    # at the script level
    var state: dict<list<number>>

    # inside a function
    ...
    state = {open: [], closed: []}
    folddoclosed state.closed += GetState('closed')
    folddoopen state.open += GetState('open')
    ...

I think this is the general solution for this kind of issue.  I have yet to find a single case where it didn't work.

**Comment by lacygoill** [comment]
Sorry, disregard the previous comment, I pasted it in the wrong issue.
