### ISSUE TITLE
Vim9: :edit parses # inconsistently

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7545]
**Describe the bug**

In Vim9 script, `:edit` parses `#` inconsistently.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        e /tmp/file1
        e /tmp/file2
        e #
    EOF
    )

The current buffer is `/tmp/file2`.

Now, run this other shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        e /tmp/file1
        e /tmp/file2
        e#
    EOF
    )

This time, the current buffer is `/tmp/file1`, which is inconsistent.

**Expected behavior**

Either `:edit` should always parse `#` as a comment leader, and `/tmp/file1` should be the current buffer in both commands; or it should always be parsed as a shorthand for the alternate buffer, in which case `/tmp/file2` should be the current buffer in both cases.

**Environment**

 - Vim version: 8.2 Included patches: 1-2202
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(362)

**Additional context**

Same issue with `##`.  Sometimes, it's parsed as a comment leader; sometimes, it's parsed as the arglist.
```vim
vim9script
args /tmp/file1 /tmp/file2
e ##
```
Here, the current buffer is `/tmp/file1`, because `##` was parsed as the start of a comment.
```vim
vim9script
args /tmp/file1 /tmp/file2
e##
```
Here, the current buffer is `/tmp/file1 /tmp/file2`, because `##` was parsed as the arglist.

---

I guess the same issue applies to all commands which expect a filename as argument.

---

If it is decided to make `#` and `##` lose their special meaning after `:edit`, `:write` and similar commands, maybe it should be documented at `:h vim9-differences`.

Note that, as a workaround, we could still use a combination of `:exe` and `bufname()`:
```vim
vim9script
e /tmp/file1
e /tmp/file2
exe 'e ' .. bufname('#')->fnamemodify(':p')
```
Or a combination of `:exe` and `argv()` for `##`.

OTOH, if it is decided to keep the current situation, where `#` is parsed differently depending on whether it's preceded by a whitespace, then maybe it should be documented at `:h vim9-gotchas`.

**Comment by lacygoill** [comment]
Note that the fact that `:e#` doesn't raise any error seems to violate the rule enforced in the patch [8.2.2138](https://github.com/vim/vim/releases/tag/v8.2.2138); the one which requires that we put a white space between an Ex command and its argument.

Although, the fact that the help says that this rule is only enforced for *most* commands and not *all* commands might suggest that `:e#` is an exception:

https://github.com/vim/vim/blob/16204962c7ad7380a40f0855443303ad16114e2b/runtime/doc/vim9.txt#L413-L414

**Comment by brammool** [comment]
> **Describe the bug**
> 
> In Vim9 script, `:edit` parses `#` inconsistently.
> 
> **To Reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(cat <<'EOF'
>         vim9script
>         e /tmp/file1
>         e /tmp/file2
>         e #
>     EOF
>     )
> 
> The current buffer is `/tmp/file2`.
> 
> Now, run this other shell command:
> 
>     vim -Nu NONE -S <(cat <<'EOF'
>         vim9script
>         e /tmp/file1
>         e /tmp/file2
>         e#
>     EOF
>     )
> 
> This time, the current buffer is `/tmp/file1`, which is inconsistent.
> 
> **Expected behavior**
> 
> Either `:edit` should always parse `#` as a comment leader, and
> `/tmp/file1` should be the current buffer in both commands; or it
> should always be parsed as a shorthand for the alternate buffer, in
> which case `/tmp/file2` should be the current buffer in both cases.

The check for white space after a command errornously assumed "#" was
the end of the command.  I'll fix that.

Remains the question how ":e #" can be used to edit the alternate file.
One cannot use ":exe 'e #'".  Anything else gets too complicated.

Would it be a good idea to make an exception for using "#" as the
alternate file if nothing follows?  I can't think of a simple
alternative.


-- 
If Pacman had affected us as kids we'd be running around in dark rooms,
munching pills and listening to repetitive music.
                       -- Marcus Brigstocke

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> Would it be a good idea to make an exception for using "#" as the
> alternate file if nothing follows?  I can't think of a simple
> alternative.

I don't like exceptions, but I can't think of anything better either; or *maybe* choose a different special character like `~`, `&`, `@`... hoping that it doesn't cause other issues, and that people are ok with this change.  It would be an understandable change, since it's obvious that there is a conflict with the new `#` comment leader.

If we choose a different special character, then `:e#` should not raise any error anymore.
If we keep using `#`, then it should also work for the other special characters listed at `:h cmdline-special` which start with `#`:

   - `#` for the alternate file
   - `#n` for the buffer `n`
   - `##` for the arglist
   - `#<n` for the old file `n`

Also, I think it should also work when followed by a bar:

    e # | another command
    vimgrep /pat/ ## | another command

This will require a change in the Vim syntax plugin to not highlight `# | another command` as a comment.  I'll try to send a patch.  Although, it's going to be tricky, because this exception is only valid for certain Ex commands.

**Comment by lacygoill** [comment]
If one of the goals of Vim9 is to be less weird than Vim script legacy, then why wouldn't we simply deprecate `#`, `#n`, `##`, and `#<n`, which are a bit weird?

I guess they were added because they're quicker to type on the command-line during an interactive session, but that's hardly relevant when writing a script.  So, how about we replace them with something more readable.  For example, for the alternate file, we could replace `#` with `++alternate`:

    edit ++alternate

For the arglist, we would use `++arglist`:

    vimgrep /pattern/ ++arglist

I've used `++` because it seems to fit well alongside `++opt`

https://github.com/vim/vim/blob/e5730bdcea0d4b574835f94b9813f80316590db9/runtime/doc/editing.txt#L457-L486

But if it causes an issue, maybe we could choose another prefix.

**Comment by lacygoill** [comment]
> But if it causes an issue, maybe we could choose another prefix.

I guess one issue is that if we add an option in the future it might collide with `alternate` and `arglist`...

If so, we could use a longer prefix.  `+++` looks a bit long, but why not:

    edit +++alternate
    vimgrep /pattern/ +++arglist

Or `++vim9`:

    edit ++vim9alternate
    vimgrep /pattern/ ++vim9arglist

Or `++[]`:

    edit ++[alternate]
    vimgrep /pattern/ ++[arglist]

**Comment by lacygoill** [comment]
In `:keepalt`, "alternate" is shortened into "alt".  So, we could do the same here:

    edit ++[alt]

**Comment by lacygoill** [comment]
FWIW, I like the last syntax which uses brackets, because it reminds me of the `[expr]` syntax which we use to set or get a dictionary member whose name results from the evaluation of an expression:

    {[expr]: value}
     ^----^

    dict[expr]
        ^----^

In `++[alt]`, something similar happens, in the sense that we don't want to edit the literal file `alt`; we want `alt` to be evaluated into the name of the alternate file.

**Comment by brammool** [comment]
> > Would it be a good idea to make an exception for using "#" as the
> > alternate file if nothing follows?  I can't think of a simple
> > alternative.
> 
> I don't like exceptions, but I can't think of anything better either;

I agree that adding rules of when "#" starts a comment and when it
doesn't complicates things.  Comments are used everywhere, thus it helps
a lot if it's a simple syntax without exceptions.  ":edit #" is not used
very often in a script, thus changing that is probably better.

> or *maybe* choose a different special character like `~`, `&`, `@`...
> hoping that it doesn't cause other issues, and that people are ok with
> this change.  It would be an understandable change, since it's obvious
> that there is a conflict with the new `#` comment leader.

There are not really any characters available that already have a
meaning or should be taken literally.  E.g. "&" is often used at the end
of a shell command, "@" can appear in a file name, etc.

We do already have the special meaning of "%".  And using "%%" would
double the current file name, which is likely never needed.  So we could
use "%%" instead of "#".  It's not that obvious, but probably the best
solution.

> If we choose a different special character, then `:e#` should not
> raise any error anymore.
> If we keep using `#`, then it should also work for the other special
> characters listed at `:h cmdline-special` which start with `#`:
> 
>    - `#` for the alternate file
>    - `#n` for the buffer `n`
>    - `##` for the arglist
>    - `#<n` for the old file `n`

These then become
    - `%%` for the alternate file
    - `%%n` for the buffer `n`
    - `%%%` for the arglist
    - `%%<n` for the old file `n`
 
> Also, I think it should also work when followed by a bar:
> 
>     e # | another command
>     vimgrep /pat/ ## | another command

And also something like:
	!command # --option
It's impossible to distinguish that from a comment, while this works:
	!command %% --option

-- 
"So this is it," said Arthur, "we are going to die."
"Yes," said Ford, "except...no!  Wait a minute!"  He suddenly lunged across
the chamber at something behind Arthur's line of vision.  "What's this
switch?" he cried.
"What?   Where?" cried Arthur, twisting around.
"No, I was only fooling," said Ford, "we are going to die after all."
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
I would have preferred a more readable syntax. Not for me, but for people who say that Vim script is weird.

I thought that `+[alt]` or `++[alt]` would be a good idea, but now I realize that maybe it would cause issues in a `:!` command.

---

> These then become
>     - `%%` for the alternate file
>     - `%%n` for the buffer `n`
>     - `%%%` for the arglist
>     - `%%<n` for the old file `n`

Why `%%n` and not `%n`?  And why `%%<n` and not `%<n`?

Note that – according to `:h extension-removal` – the Vim script legacy `%<`syntax is not recommended anymore:

https://github.com/vim/vim/blob/b0ac4ea5e1c5f0ff4e951978c32ccfffe46916f8/runtime/doc/cmdline.txt#L1023-L1030

**Comment by lacygoill** [comment]
> Note that – according to :h extension-removal – the Vim script legacy %<syntax is not recommended anymore:

Instead, the help recommends to use the `:r` suffix.

**Comment by lacygoill** [comment]
> I would have preferred a more readable syntax.

Although, it does make sense to keep a short syntax, if one day we add a `'vim9cmdline'` option to let us use the Vim9 syntax while on an interactive command-line, which could be useful while developing.  Because in that case, being concise matters more.

**Comment by brammool** [comment]
> I would have preferred a more readable syntax. Not for me, but for
> people who say that Vim script is weird.
> 
> I thought that `+[alt]` or `++[alt]` would be a good idea, but now I
> realize that maybe it would cause issues in a `:!` command.
> 
> ---
> 
> > These then become
> >     - `%%` for the alternate file
> >     - `%%n` for the buffer `n`
> >     - `%%%` for the arglist
> >     - `%%<n` for the old file `n`
> 
> Why `%%n` and not `%n`?  And why `%%<n` and not `%<n`?

Consistency and simplicity: Just replace "#" with "%%".

Also, when editing "file" it is possible to use ":edit %4" to edit
"file4".  It's a corner case, but does have a higher chance of being
used somewhere compared to "%%".

> Note that – according to `:h extension-removal` – the Vim script
> legacy `%<`syntax is not recommended anymore:
> 
> https://github.com/vim/vim/blob/b0ac4ea5e1c5f0ff4e951978c32ccfffe46916f8/runtime/doc/cmdline.txt#L1023-L1030

Yeah, maybe it's no needed to keep #< as %%<, but for consistency it
might be better to do anyway.

-- 
The History of every major Galactic Civilization tends to pass through
three distinct and recognizable phases, those of Survival, Inquiry and
Sophistication, otherwise known as the How, Why and Where phases.
For instance, the first phase is characterized by the question 'How can
we eat?' the second by the question 'Why do we eat?' and the third by
the question 'Where shall we have lunch?'
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
