### ISSUE TITLE
Vim8.2: No methods to map combine key like:  [:ts + :UserCommand]

### ISSUE THREAD

**Issue by Shaiya2688** [vim/vim#7550]
**No methods to map combine key like:** `:ts`+`:UserCommand`
`:UserCommand` :  Get the latest tagstack and do more processing.
`:ts` : Vim built-in command to list the tags from the tag stack. The tagstack will be updated after the user enters the selection.
But the `UserCommand` executed before waiting for user input to complete, so `UserCommand` doesn't get the right tagstack.

**Describe the solution you'd like**
It's best to do `:UserCommand` with events or callbacks for commands with user input like `:ts`

**Describe alternatives you've considered**
I have tried to delay `UserCommand` or handle it in a later cursor movement event autocommand.
However, the time and window of input completion cannot be accurately matched. Instead, which result additional  performance problems.

**Environment**
Vim version 8.2
OS: Ubuntu 16.04LTS 64-bit
Terminal: xterm

**Comment by tonymec** [comment]
See
```vim
:help :|
:help :redir
:help <Bar>
```
the latter because in a mapping (if in `'nocompatible'` mode) you should represent the vertical bar by `<Bar>` to avoid it being seen as the start of a different command. If using `compatible` you may need to type `Ctrl-V` but I'm not sure how many times.
Best regards,
Tony.

**Comment by Shaiya2688** [comment]
> See
> 
> ```viml
> :help :|
> :help :redir
> :help <Bar>
> ```
> 
> the latter because in a mapping (if in `'nocompatible'` mode) you should represent the vertical bar by `<Bar>` to avoid it being seen as the start of a different command. If using `compatible` you may need to type `Ctrl-V` but I'm not sure how many times.
> Best regards,
> Tony.

Thanks for your reply.
This is useful for the `:ts` command.
In another case, if the first command is changed to `g<C-]>` key combination, how do I maping?

**Comment by tonymec** [comment]
see `:help :normal`

Best regards,
Tony.

**Comment by tonymec** [comment]
P.S. And see also `:help :execute`

Best regards,
Tony.

**Comment by tonymec** [comment]
P.P.S. Everything is in the Vim help, but for a newcomer it sometimes feels like looking for one tiny needle in a shipload of hay.

See `:help helphelp.txt` about various manners to search the help.

Best regards,
Tony.

**Comment by chrisbra** [comment]
please ask user questions on the vim mailinglist or use vi.stackexchange.com. We cannot provide individual support here. Closing.
