### ISSUE TITLE
cnoremap mappings to <Down> can incorrectly insert `wildchar`

### ISSUE THREAD

**Issue by godlygeek** [vim/vim#7552]
**Describe the bug**
With `:set wildmode=full wildmenu`, doing `:e <Tab>` will display a completion menu. If you navigate to a directory and press `<Down>`, completion will descend into that directory.

If you `cnoremap` a different key to `<Down>`, then instead of descending into the selected directory, the `wildchar` is written to the command line.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean`
2. Type `:e .<Tab><Down>` and observe that completion continues
3. Hit `<Esc>` to cancel the command
4. Execute `:cnoremap <C-o> <Down>`
5. Type `:e .<Tab><C-o>` and observe that completion ends and `^I` appears on the command line
6. Hit `<Esc>` to cancel the command
7. Execute `:set wildchar=<C-x>`
8. Type `:e .<C-x><C->` and observe that completion ends and `^X` appears on the command line

**Expected behavior**
A `cnoremap` of another key to `<Down>` should behave exactly like pressing `<Down>` does. Instead, it ends any current completion attempt and inserts the current `wildchar`.

**Environment (please complete the following information):**
 - Vim version: 8.2.2077
 - OS: Linux
 - Terminal: mintty

**Comment by godlygeek** [comment]
Presumably this is where the bug lies:
https://github.com/vim/vim/blob/e5730bdcea0d4b574835f94b9813f80316590db9/src/cmdexpand.c#L2732-L2741

That seems to be swapping the `<Down>` keypress for a press of the wildchar, but presumably the `cnoremap` is causing the wildchar to be inserted literally instead of triggering completion at that point.

**Comment by lacygoill** [comment]
I wonder whether it has the same cause as https://github.com/vim/vim/issues/4954 and https://github.com/vim/vim/issues/6045.

FWIW, here is a temporary workaround:

    cnoremap <C-o> <cmd>call feedkeys("\<lt>Down>", "nt")<cr>

**Comment by godlygeek** [comment]
The bug doesn't reproduce with `<Up>` as it does with `<Down>`, and the `<Up>` case instead has:
https://github.com/vim/vim/blob/e5730bdcea0d4b574835f94b9813f80316590db9/src/cmdexpand.c#L2815-L2818

I bet the bug here is just that `KeyTyped = TRUE;` needs to be added for the `<Down>` case as it already is for `<Up>`.

**Comment by lacygoill** [comment]
Can confirm that the following patch fixes the current issue as well as https://github.com/vim/vim/issues/4954 and https://github.com/vim/vim/issues/6045:

```diff
diff --git a/src/cmdexpand.c b/src/cmdexpand.c
index 4ebb69334..a318c2b6a 100644
--- a/src/cmdexpand.c
+++ b/src/cmdexpand.c
@@ -2738,6 +2738,7 @@ wildmenu_process_key(cmdline_info_T *cclp, int key, expand_T *xp)
 	{
 	    // go down a directory
 	    c = p_wc;
+	    KeyTyped = TRUE;
 	}
 	else if (STRNCMP(xp->xp_pattern, upseg + 1, 3) == 0 && c == K_DOWN)
 	{
```

**Comment by godlygeek** [comment]
There's 5 occurrences of `c = p_wc` in `wildmenu_process_key`, and only one of the 5 currently does `KeyTyped = TRUE` - I suspect all 4 of the others need it.

**Comment by lacygoill** [comment]
So this patch adds the `KeyTyped = TRUE;` statement after every `c = p_wc;` in `src/cmdexpand.c`:
```diff
diff --git a/src/cmdexpand.c b/src/cmdexpand.c
index 4ebb69334..ac7432b5c 100644
--- a/src/cmdexpand.c
+++ b/src/cmdexpand.c
@@ -2680,7 +2680,10 @@ wildmenu_process_key(cmdline_info_T *cclp, int key, expand_T *xp)
 	// Hitting <Down> after "emenu Name.": complete submenu
 	if (c == K_DOWN && cclp->cmdpos > 0
 		&& cclp->cmdbuff[cclp->cmdpos - 1] == '.')
+	{
 	    c = p_wc;
+	    KeyTyped = TRUE;
+	}
 	else if (c == K_UP)
 	{
 	    // Hitting <Up>: Remove one submenu name in front of the
@@ -2714,6 +2717,7 @@ wildmenu_process_key(cmdline_info_T *cclp, int key, expand_T *xp)
 	    if (i > 0)
 		cmdline_del(cclp, i);
 	    c = p_wc;
+	    KeyTyped = TRUE;
 	    xp->xp_context = EXPAND_NOTHING;
 	}
     }
@@ -2738,6 +2742,7 @@ wildmenu_process_key(cmdline_info_T *cclp, int key, expand_T *xp)
 	{
 	    // go down a directory
 	    c = p_wc;
+	    KeyTyped = TRUE;
 	}
 	else if (STRNCMP(xp->xp_pattern, upseg + 1, 3) == 0 && c == K_DOWN)
 	{
@@ -2763,6 +2768,7 @@ wildmenu_process_key(cmdline_info_T *cclp, int key, expand_T *xp)
 	    {
 		cmdline_del(cclp, j - 2);
 		c = p_wc;
+		KeyTyped = TRUE;
 	    }
 	}
 	else if (c == K_UP)
diff --git a/src/testdir/test_cmdline.vim b/src/testdir/test_cmdline.vim
index 1c5cac76b..7aabd8c1f 100644
--- a/src/testdir/test_cmdline.vim
+++ b/src/testdir/test_cmdline.vim
@@ -58,6 +58,19 @@ func Test_complete_wildmenu()
   call feedkeys(":e Xdir1/\<Tab>\<Down>\<Up>\<Right>\<CR>", 'tx')
   call assert_equal('testfile1', getline(1))
 
+  " <C-J>/<C-K> mappings to go up/down directories when 'wildcharm' is
+  " different than 'wildchar'.
+  set wildcharm=<C-Z>
+  cnoremap <C-J> <Down><C-Z>
+  cnoremap <C-K> <Up><C-Z>
+  call feedkeys(":e Xdir1/\<Tab>\<C-J>\<CR>", 'tx')
+  call assert_equal('testfile3', getline(1))
+  call feedkeys(":e Xdir1/\<Tab>\<C-J>\<C-K>\<CR>", 'tx')
+  call assert_equal('testfile1', getline(1))
+  set wildcharm=0
+  cunmap <C-J>
+  cunmap <C-K>
+
   " Test for canceling the wild menu by adding a character
   redrawstatus
   call feedkeys(":e Xdir1/\<Tab>x\<C-B>\"\<CR>", 'xt')
```
I compiled Vim and ran all the tests (on Ubuntu 16.04); all of them passed (a few were skipped).

This also includes a test which currently fails, but passes once the patch is applied.
