### ISSUE TITLE
Vim9: cannot import item from filetype plugin written in Vim script legacy

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7557]
**Describe the bug**

In Vim9 script, we cannot import an item from a filetype plugin written in Vim script legacy.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        mkdir('/tmp/import', 'p')
        mkdir('/tmp/ftplugin', 'p')
        var lines =<< trim END
            vim9script
            export var That = 123
        END
        writefile(lines, '/tmp/import/ExportThat.vim')
        writefile(["import That from 'ExportThat.vim'"], '/tmp/ftplugin/vim.vim')
        set rtp^=/tmp
        filetype plugin on
        e /tmp/vim.vim
        e
    EOF
    )

`E1073` is raised:

    E1073: Name already defined: That

**Expected behavior**

No error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-2223
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(362)

**Additional context**

Regression introduced in [8.2.2222](https://github.com/vim/vim/releases/tag/v8.2.2222).

**Comment by lacygoill** [comment]
The issue disappears if `vim9script` is added at the top of the filetype plugin:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        mkdir('/tmp/import', 'p')
        mkdir('/tmp/ftplugin', 'p')
        var lines =<< trim END
            vim9script
            export var That = 123
        END
        writefile(lines, '/tmp/import/ExportThat.vim')
        writefile(['vim9script', "import That from 'ExportThat.vim'"], '/tmp/ftplugin/vim.vim')
        set rtp^=/tmp
        filetype plugin on
        e /tmp/vim.vim
        e
    EOF
    )

**Comment by lacygoill** [comment]
> In Vim9 script, we cannot import an item from a filetype plugin written in Vim script legacy.

I mean, we can, but after reloading the file, an unexpected error is raised.  It was not raised before 8.2.2221.

**Comment by lacygoill** [comment]
> It was not raised before 8.2.2221.

Sorry, I meant before 8.2.2222.

**Comment by brammool** [comment]
Fixed by 8.2.2225
