### ISSUE TITLE
Vim9: wrong information at ":h vim9-reload"

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7558]
In `runtime/doc/vim9.txt`, on line 212:

https://github.com/vim/vim/blob/cdc40c43f1008bda2f173d3a13606236679e8067/runtime/doc/vim9.txt#L212

`vimscript` should be replaced with `vim9script`.

---

On line 216, same thing:

https://github.com/vim/vim/blob/cdc40c43f1008bda2f173d3a13606236679e8067/runtime/doc/vim9.txt#L216

---

On line 218, the `g:` scope should be specified in the `exists()` invocation:

https://github.com/vim/vim/blob/cdc40c43f1008bda2f173d3a13606236679e8067/runtime/doc/vim9.txt#L218

That's because, in a Vim9 script, the default scope when defining an item switches from global to script-local.  So, while we could omit `g:` in a Vim script legacy file because it matched the default scope, we can't in a Vim9 script.

Here is a patch:
```diff
diff --git a/runtime/doc/vim9.txt b/runtime/doc/vim9.txt
index dd8cd61f2..7357812c0 100644
--- a/runtime/doc/vim9.txt
+++ b/runtime/doc/vim9.txt
@@ -113,10 +113,10 @@ In Vi # is a command to list text with numbers.  In Vim9 script you can use
 
 To improve readability there must be a space between a command and the #
 that starts a comment: >
-	var = value # comment
-	var = value# error!
+	var name = value # comment
+	var name = value# error!
 
-In legacy script # is also used for the alternate file name.  In Vim9 script
+In legacy Vim script # is also used for the alternate file name.  In Vim9 script
 you need to use %% instead.  Instead of ## use %%% (stands for all arguments).
 
 
@@ -209,11 +209,11 @@ if you are developing a plugin and want to try a new version.  If you renamed
 something you don't have to worry about the old name still hanging around.
 
 If you do want to keep items, use: >
-	vimscript noclear
+	vim9script noclear
 
 You want to use this in scripts that use a `finish` command to bail out at
 some point when loaded again.  E.g. when a buffer local option is set: >
-	vimscript noclear
+	vim9script noclear
 	setlocal completefunc=SomeFunc
-	if exists('*SomeFunc') | finish | endif
+	if exists('*g:SomeFunc') | finish | endif
 	def g:SomeFunc()
```
It also includes a few extra fixes to errors which were introduced in [8.2.2222](https://github.com/vim/vim/releases/tag/v8.2.2222).  On the lines 116 and 117, the name of the variables are missing:

https://github.com/vim/vim/blob/cdc40c43f1008bda2f173d3a13606236679e8067/runtime/doc/vim9.txt#L116-L117

---

There might be another misleading information regarding the circumstances where the new `noclear` argument is useful:

https://github.com/vim/vim/blob/cdc40c43f1008bda2f173d3a13606236679e8067/runtime/doc/vim9.txt#L211-L220

At first, I thought it was right.  Here is why:

   1. we reload a buffer
   2. thus, `FileType` is fired a second time
   3. thus, the relevant filetype plugin is resourced
   4. Vim automatically clears the items from the filetype plugin written in Vim9 script, which includes the `SomeFunc()` function
   5. the guard prevents `SomeFunc()` from being reinstalled
   6. when we press `C-x C-u` in insert mode, an error is raised because `SomeFunc()` is no longer defined

But that should not happen.  I mean, if Vim deletes `SomeFunc()`, then the `exists()` condition should fail, the script should not bail out, and the function should be reinstalled, right?

To be sure, in a lua filetype plugin, I've created a dummy buffer-local mapping which invokes a script-local function.  I've loaded and reloaded a lua file, and tested whether the mapping still worked: it still worked, even though I didn't pass `noclear` to `vim9script`.

Here is an example:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        var lines =<< trim END
            setlocal completefunc=SomeFunc
            if exists('*g:SomeFunc') | finish | endif
            def g:SomeFunc(findstart: number, base: string): any
                if findstart
                    var line = getline('.')
                    var start = col('.') - 1
                    while start > 0 && line[start - 1] =~ '\a'
                        start -= 1
                    endwhile
                    return start
                else
                    var res = []
                    for m in split('Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec')
                        if m =~ '^' .. base
                            add(res, m)
                        endif
                    endfor
                    return res
                endif
            enddef
        END
        mkdir('/tmp/TestNoclear/ftplugin', 'p')
        writefile(lines, '/tmp/TestNoclear/ftplugin/vim.vim')
        set rtp^=/tmp/TestNoclear
        filetype plugin on
        e /tmp/vim.vim
        e
        feedkeys("i\<c-x>\<c-u>", 'nt')
    EOF
    )

The code works as expected and doesn't raise any error.  And yet the Vim file is reloaded, which in turn causes the Vim filetype plugin to be reloaded.  And note that in the Vim filetype plugin, I didn't pass `noclear` to `:vim9script`.

So, I *think* that the given example is misleading.  Or am I missing something?

---

Note that I'm not saying `noclear` is useless; it is *very* useful.  I've already used it to fix a bug in one of my plugins.  What I'm saying is that the given example might not be correct.  I don't think `noclear` is useful when there is a `finish` in a script; I think it's useful when we have a plugin with an internal state which is implemented via script-local variables, and we don't want a reload to mess up this state, because our code works under the assumption that this state will never be altered at runtime.

**Comment by lacygoill** [comment]
> this state will never be altered at runtime.

I meant: "this state will never be unexpectedly cleared/reset at runtime".

**Comment by lacygoill** [comment]
> I meant: "this state will never be unexpectedly cleared/reset at runtime".

Ok, one more time: "only the code we've explicitly written in our plugin can alter this state".

**Comment by brammool** [comment]
I'll update the help.  I don't think anything else is needed.
