### ISSUE TITLE
vim8 dvorak

### ISSUE THREAD

**Issue by tomiteo** [vim/vim#756]
could you please incorporate a setting in the new version of vim so it makes more sense for us dvorakers to use it?

thanks!

**Comment by vim-ml** [comment]
On Wednesday, April 13, 2016 at 9:53:32 PM UTC-5, Tim Gregg wrote:

> could you please incorporate a setting in the new version of vim so it makes more sense for us dvorakers to use it?

Well, there's a script to do some mappings for you. Previously it was in $VIMRUNTIME/macros/dvorak, it's been moved to a package for the next release.

But personally I don't use it and don't have any problems with Vim in Dvorak. I likewise don't use any language mappings for the same purpose: http://vim.wikia.com/wiki/Using_Vim_with_the_Dvorak_keyboard_layout

What's giving you trouble? Just muscle-memory from using Vim before learning Dvorak? Either of those solutions should help with that if you don't want to retrain on Vim. I had the advantage of learning Dvorak before I learned Vim.

**Comment by chrisbra** [comment]
Closing, as this seems more like a user question. Please ask user questions on the vim-use ml. thanks.
