### ISSUE TITLE
Vim crashes (SEGV) after resizing inactive window

### ISSUE THREAD

**Issue by obcat** [vim/vim#7568]
**Describe the bug**
Vim may crash (SEGV) after `:vertical {winnr}res[ize] [+-]N` command if:
* `{winnr}` is inactive (not current) window's number and
* `[-+]N` is too big or small.

**To Reproduce**
```vim
$ vim -u NONE
:vsplit
:echo winwidth(0)
" 80 (example)
:wincmd l
:echo winnr('h')
" 1
:vertical 1resize -100
" Vim: Caught deadly signal SEGV
" Vim: Finished.
```

**Expected behavior**
Vim does not crash and the width of target window is minimized.

**Environment**
 - Vim 8.2.2150
 - macOS Catalina (version 10.15.7)
 - iTerm2

**Comment by lacygoill** [comment]
- [backtrace](https://github.com/vim/vim/files/5749478/backtrace.txt)
- [valgrind log](https://github.com/vim/vim/files/5749479/valgrind.log)
- [asan log](https://github.com/vim/vim/files/5749477/asan.log)
