### ISSUE TITLE
Vim crashes (SEGV) after creating popup with invalid popup mask

### ISSUE THREAD

**Issue by obcat** [vim/vim#7569]
**Describe the bug**
Vim may crash (SEGV) after creating many popups with invalid popup mask.

**To Reproduce**
```vim
$ vim --clean
:call popup_create('test', #{mask: [[0, 0, 0, 0]]})
@:
@@
@@
@@
" ~ repeat over ~
@@
@@
@@
@@
" Vim: Caught deadly signal SEGV
" Vim: Finished.
```

**Expected behavior**
Vim does not crash.

**Environment**
 - Vim 8.2.2150
 - macOS Catalina (version 10.15.7)
 - iTerm2

**Comment by lacygoill** [comment]
Regression introduced in [8.1.1753](https://github.com/vim/vim/releases/tag/v8.1.1753) and [8.1.1754](https://github.com/vim/vim/releases/tag/v8.1.1754).

---

- [backtrace](https://github.com/vim/vim/files/5749839/backtrace.txt)
- [valgrind log](https://github.com/vim/vim/files/5749840/valgrind.log)
- [asan log](https://github.com/vim/vim/files/5749838/asan.log)
