### ISSUE TITLE
Default value of maxcount option of searchcount() is different from help

### ISSUE THREAD

**Issue by obcat** [vim/vim#7570]
**Describe the bug**
Help file says default value of `maxcount` option of  `searchcount()` is `0`, but it is actually `99`.

**To Reproduce**
```vim
$ vim --clean
:call append(0, 'a' ->repeat(200))
:echo searchcount(#{pattern: 'a'})
" {'exact_match': 0, 'current': 100, 'incomplete': 2, 'maxcount': 99, 'total': 100}
```

**Expected behavior**
The default value of `maxcount` option is `0` and the following is echoed:
```vim
" {'exact_match': 0, 'current': 200, 'incomplete': 0, 'maxcount': 0, 'total': 200}
```

**Environment**
 - Vim 8.2.2150
 - macOS Catalina (version 10.15.7)
 - iTerm2

**Comment by brammool** [comment]
Let me update the help, the default value of 99 was intentional.
