### ISSUE TITLE
Commands cannot be interrupted on Cygwin build

### ISSUE THREAD

**Issue by AvianY** [vim/vim#7575]
As the title says. I am unable to interrupt ```[i``` search function with ```ctrl-c``` or other ways. I don't know if this is a bug or just a missing feature, but it would be cool to be able to do that.

**Comment by AvianY** [comment]
this is in fact a common theme, since a lot of commands can't be interrupted

**Comment by chrisbra** [comment]
> this is in fact a common theme, since a lot of commands can't be interrupted

most commands should be interruptable. Please fill out the issue template. It is there for a reason. Also, does that happen with running from `vim --clean`?

**Comment by AvianY** [comment]
I have vim compiled for cygwin:
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 30 2020 21:58:19)
Included patches: 1-486

The same behaviour is observed with ```vim --clean```

Are you saying it works for you? Try having lots of includes and interrupting.

**Comment by chrisbra** [comment]
On Mi, 30 Dez 2020, AvianY wrote:

> I have vim compiled for cygwin:
> VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 30 2020 21:58:19)
> Included patches: 1-486
> 
> The same behaviour is observed with ```vim --clean```
> 
> Are you saying it works for you? Try having lots of includes and interrupting.

No I did not observe this behaviour with [i

I was just responding to your message that most commands are not 
interruptible. I think they are. 

Can you please provide an easy reproducible example?

Best,
Christian
-- 
Wenn Microsoft Autos bauen würde ...
würden neue Sitze erfordern, daß alle die selbe Gesäßgröße haben.

**Comment by AvianY** [comment]
1.) download cygwin
2.) install vim
3.) run vim however you like
4.) open a file with many includes
5.) press ```[i```
6.) try to interrupt
7.) pikachu face

**Comment by chrisbra** [comment]
okay, now this is getting ridiculous...

Perhaps it is a cygwin issue? Can you reproduce this on a vim without Cygwin?

I had a quick look into the `find_pattern_in_path()` function. It already contains some checks for `got_int`. Perhaps its the [while loop](https://github.com/vim/vim/blob/2808da39f9aad674d25df784da636e42372b78e3/src/search.c#L3934-L3946) that is not interruptible? 

Would you help getting this fixed and do some C profiling, which takes that long? Thanks.

**Comment by AvianY** [comment]
I tried on vim on linux and there is no issue (I can interrupt it).... so I guess it is connected to cygwin somehow, but I would still like to solve it, because it is annoying.

I would be glad to help. How do I do what you said?

**Comment by brammool** [comment]
Perhaps it gets stuck in a network request?  Try changing the 'path' option to exclude problematic directories.

**Comment by AvianY** [comment]
Are you sure 'path' could be the problem?
I tried interrupting in the same codebase on cygwin and linux with the same 'path' set and there is no problem on linux

**Comment by chrisbra** [comment]
> so I guess it is connected to cygwin somehow

Well, cygwin is known to be slow.

**Comment by AvianY** [comment]
it's not about "slow". It's about not being able to interrupt the command.

**Comment by brammool** [comment]
> it's not about "slow". It's about not being able to interrupt the command.

Can you interrupt other commands, where on Linux it would say
"Interrupted"?  If yes, then it's not specific for [i but for Cygwin not
checking for CTRL-C.  Actually, try using the Break key (might be called
something else, depending on the keyboard).
On MS-Windows CTRL-C also means "copy", thus perhaps it doesn't
interrupt.


-- 
The real
trick is
this: to
keep the
lines as
short as
possible
and keep
the size
the same
yet free
from the
need for
hyphena-
Dammit!!  (Matthew Winn)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by AvianY** [comment]
No, I am not able to break any command. Not even Ex command.
I tried ```ctrl c```, ```pause``` and ```break``` and simmilar.

**Comment by AvianY** [comment]
Although, ```ctrl-c``` does break bash commands in cygwin terminal.

**Comment by chrisbra** [comment]
On Mi, 30 Dez 2020, AvianY wrote:

> No, I am not able to break any command. Not even Ex command.
> I tried ```ctrl c```, ```pause``` and ```break``` and simmilar.

Did you try Ctrl-Break (see :h dos-CTRL-Break)?

Best,
Christian
-- 
Eine Million Steuerzahler verhalten sich vernünftiger als eine
öffentliche Hand.
		-- Hermann Josef Abs

**Comment by AvianY** [comment]
Yes, I tried and it doesn't work. It can stop commands in cygwin shell, but not in vim.

**Comment by dpelle** [comment]
For what it's worth, `CTRL-C` does interrupt a long `[i` for me on Linux x86_64 (xubuntu-18.04.5) with vim-8.2.2246.
And it shows `Interrupted` immediately after pressing `CTRL-C`.  I tried with `vim --clean` as well as with my full `~/.vimrc`.
I don't have Windows or Cygwin.
Are other commands interruptible?  Can you e.g. interrupt `:sleep 60`?

**Comment by AvianY** [comment]
Breaking works fine for me on linux as well.
I am asking specifically for vim on cygwin. I cannot break anything. Not ```[i```, not ```:isearch SMTH``` and not ```:sleep 60```.

**Comment by brammool** [comment]
So the actual problem is that on this Cygwin build CTRL-C is not considered the interrupt character.  Please update the title of the issue accordingly, it's not about the [i command doing something problematic (other than taking a while).
I'm afraid I won't have time to look into debugging a Cygwin build, I hope someone else can.

**Comment by k-takata** [comment]
It seems that mintty is related to this issue.
When I ran Cygwin vim on Command Prompt directly, `sleep` was interrupted by Ctrl-C.
I'm not sure whether this is caused by mintty or Cygwin itself, though.

**Comment by Shane-XB-Qian** [comment]
@AvianY this can be confirmed before @k-takata , Cygwin had native build vim, just try there, if no, then it’s not a problem of vim, unless the recent patch changed that. Or can narrow down patch range also if so.

**Comment by Shane-XB-Qian** [comment]
And mintty can configure some key’s esc value as well, as I remember..

**Comment by k-takata** [comment]
I found that this is a modifyOtherKeys issue.
When I disabled the modifyOtherKeys, Ctrl-C worked as expected.

**Comment by AvianY** [comment]
I can confirm @k-takata  that it works, thanks a lot. Now the question is, what do we make of this?

**Comment by brammool** [comment]
Ken Takata wrote:

> I found that this is a modifyOtherKeys issue.
> When I disabled the modifyOtherKeys, Ctrl-C worked as expected.

Aha, so apparently it doesn't reach the code in fill_input_buf() that
checks for the CTRL-C Escape sequence (src/ui.c line 1020).
Where does this build check for keys, which machine specific function is
used?

-- 
hundred-and-one symptoms of being an internet addict:
71. You wonder how people walk

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
I did run `vim -u NONE -N --cmd "call ch_logfile('cygwin.log', 'w')"` and just typed `:sleep 10` and pressed `Ctrl-C` a couple of times.

The log looks like this:

```
==== start log session ====
  0.003330 : raw terminal output: "[?1049h[22;0;0t[>4;2m[?1h=[?2004h"
  0.004941 : raw terminal output: "[1;77r[?12h[?12l[22;2t"
  0.081887 : raw terminal output: "[27m[23m[29m[m[H[2J[2;1H▽[6n"
  0.082870 : raw terminal output: "[2;1H  [3;1HPzz\[0%m[6n"
  0.084498 : raw terminal output: "[>c"
  0.085092 : raw terminal output: "]10;?]11;?"
  0.085167 : SafeState: Start triggering
  0.088913 : looking for messages on channels
  0.088949 : SafeState: back to waiting, triggering SafeStateAgain
  0.106492 : raw key input: "[2;2R[3;1R[>77;30404;0c]10;rgb:bfbf/bfbf/bfbf]11;rgb:0000/0000/0000"
  0.107687 : raw terminal output: "[?12$p"
  0.107865 : looking for messages on channels
  0.107891 : SafeState: back to waiting, triggering SafeStateAgain
  0.137455 : raw key input: "[?12;2$y"
  0.137598 : looking for messages on channels
  0.137665 : SafeState: back to waiting, triggering SafeStateAgain
  2.480000 : raw key input: "j"
  2.480245 : SafeState: reset: key typed
  2.480413 : SafeState: Start triggering
  2.481954 : looking for messages on channels
  2.482143 : SafeState: back to waiting, triggering SafeStateAgain
  2.936416 : raw key input: ":"
  2.936648 : SafeState: reset: key typed
  2.936887 : SafeState: Start triggering
  2.938686 : looking for messages on channels
  2.938823 : SafeState: back to waiting, triggering SafeStateAgain
  3.139082 : raw key input: "s"
  3.139254 : SafeState: reset: key typed
  3.139386 : SafeState: Start triggering
  3.140188 : looking for messages on channels
  3.140300 : SafeState: back to waiting, triggering SafeStateAgain
  3.294129 : raw key input: "l"
  3.294418 : SafeState: reset: key typed
  3.294551 : SafeState: Start triggering
  3.296200 : looking for messages on channels
  3.296338 : SafeState: back to waiting, triggering SafeStateAgain
  3.386380 : raw key input: "e"
  3.386676 : SafeState: reset: key typed
  3.386875 : SafeState: Start triggering
  3.388282 : looking for messages on channels
  3.388465 : SafeState: back to waiting, triggering SafeStateAgain
  3.526711 : raw key input: "e"
  3.526957 : SafeState: reset: key typed
  3.527092 : SafeState: Start triggering
  3.528692 : looking for messages on channels
  3.528861 : SafeState: back to waiting, triggering SafeStateAgain
  3.637025 : raw key input: "p"
  3.637151 : SafeState: reset: key typed
  3.637212 : SafeState: Start triggering
  3.637687 : looking for messages on channels
  3.637751 : SafeState: back to waiting, triggering SafeStateAgain
  3.778554 : raw key input: " "
  3.778649 : SafeState: reset: key typed
  3.778687 : SafeState: Start triggering
  3.779870 : looking for messages on channels
  3.779916 : SafeState: back to waiting, triggering SafeStateAgain
  3.949400 : raw key input: "1"
  3.949523 : SafeState: reset: key typed
  3.949570 : SafeState: Start triggering
  3.949980 : looking for messages on channels
  3.950025 : SafeState: back to waiting, triggering SafeStateAgain
  3.980468 : raw key input: "0"
  3.980571 : SafeState: reset: key typed
  3.980611 : SafeState: Start triggering
  3.981381 : looking for messages on channels
  3.981454 : SafeState: back to waiting, triggering SafeStateAgain
  6.489875 : raw key input: "
"
  6.489988 : SafeState: reset: key typed
  6.491579 : ui_delay(1000)
  7.504899 : raw key input: "[99;5u"
  7.505120 : looking for messages on channels
  7.505265 : ui_delay(1000)
  8.520085 : raw key input: "[99;5u[99;5u[99;5u[99;5u[99;5u[99;5u"
  8.520261 : looking for messages on channels
  8.520346 : ui_delay(1000)
  9.523245 : raw key input: "[99;5u[99;5u[99;5u[99;5u[99;5u[99;5u[99;5u"
  9.523349 : looking for messages on channels
  9.523391 : ui_delay(1000)
 10.537232 : raw key input: "[99;5u[99;5u[99;5u[99;5u"
 10.537451 : looking for messages on channels
 10.537537 : ui_delay(1000)
 11.552793 : looking for messages on channels
 11.553021 : ui_delay(1000)
 12.565324 : raw key input: "[99;5u"
 12.565447 : looking for messages on channels
 12.565517 : ui_delay(1000)
 13.580113 : raw key input: "[99;5u"
 13.580185 : looking for messages on channels
 13.580215 : ui_delay(1000)
 14.586493 : looking for messages on channels
 14.586752 : ui_delay(1000)
 15.596159 : raw key input: "[99;5u"
 15.596244 : looking for messages on channels
 15.596272 : ui_delay(894)
 16.503193 : raw key input: "[99;5u"
 16.503500 : looking for messages on channels
 16.503598 : SafeState: Start triggering
 16.503697 : looking for messages on channels
 16.503754 : SafeState: back to waiting, triggering SafeStateAgain
 16.503885 : SafeState: reset: key typed
 16.515460 : looking for messages on channels
 16.527236 : SafeState: Start triggering
 16.528294 : looking for messages on channels
 16.528389 : SafeState: back to waiting, triggering SafeStateAgain
 16.641439 : raw key input: "[99;5u"
 16.641640 : SafeState: reset: key typed
 16.643179 : SafeState: Start triggering
 16.644673 : looking for messages on channels
 16.644776 : SafeState: back to waiting, triggering SafeStateAgain
 17.269145 : raw key input: ":"
 17.269304 : SafeState: reset: key typed
 17.269388 : SafeState: Start triggering
 17.270356 : looking for messages on channels
 17.270499 : SafeState: back to waiting, triggering SafeStateAgain
 17.346651 : raw key input: "q"
 17.346785 : SafeState: reset: key typed
 17.346846 : SafeState: Start triggering
 17.347981 : looking for messages on channels
 17.348058 : SafeState: back to waiting, triggering SafeStateAgain
 17.486923 : raw key input: "a"
 17.487023 : SafeState: reset: key typed
 17.487080 : SafeState: Start triggering
 17.487721 : looking for messages on channels
 17.487774 : SafeState: back to waiting, triggering SafeStateAgain
 17.596503 : raw key input: "
"
 17.596638 : SafeState: reset: key typed
 17.597562 : Exiting...
 17.617552 : raw terminal output: "[?25l[?2004l[>4;m"
 17.619620 : raw terminal output: "[77;1H[K[77;1H[?2004l[?1l>"
```


According to the Mintty project, `Ctrl` keys send a bit other keys than xterm. If I read their [wiki page](https://github.com/mintty/mintty/wiki/CtrlSeqs) correctly, it should send something like `^[[99;5u` where `99` is the keycode and `5` is the modifier. So `Ctrl-C` should send `^[[99;5u` and that is exactly what Vim sees above.

So mintty does not use the xterm modifyOtherKeys control sequences, but something similar. I think the following patch should do it:

```patch
diff --git a/src/ui.c b/src/ui.c
index 7c8667559..6573e0841 100644
--- a/src/ui.c
+++ b/src/ui.c
@@ -1018,7 +1018,10 @@ fill_input_buf(int exit_on_error UNUSED)
             */
            if (ctrl_c_interrupts && (inbuf[inbufcount] == 3
                        || (len >= 9 && STRNCMP(inbuf + inbufcount,
-                                                  "\033[27;5;99~", 10) == 0)))
+                                                  "\033[27;5;99~", 10) == 0)
+                       || (len >= 7 && STRNCMP(inbuf + inbufcount,
+                                                  "\033[99;5u", 7) == 0)
+                   ))
            {
                // remove everything typed before the CTRL-C
                mch_memmove(inbuf, inbuf + inbufcount, (size_t)(len + 1));
```

But perhaps it is better to disable modifyOtherKeys when we are detecting that we are running in mintty? Or the condition above should at least add a check for the mintty terminal? However, I suppose we need a lot more changes for modifyOtherKeys in mintty, as those are quite different from xterms one.

**Comment by Shane-XB-Qian** [comment]
donot know those code much, but for your reference: you are right.
```c
void other_code(wchar c) {
    trace_key("other");
    len = sprintf(buf, "\e[%u;%uu", c, mods + 1);
  }
```
looks this is mintty 's 'other key'.. vs xterm 's '27' sth...

**Comment by Shane-XB-Qian** [comment]
@brammool hate to say, but like #7574 said, i am not care, but e.g this ticket, looks many guys joined to discuss to find out the cause.. just a friendly..wish... :(

**Comment by Shane-XB-Qian** [comment]
https://github.com/vim/vim/issues/4518#issuecomment-754656370
