### ISSUE TITLE
Vim9: not easy to find where a whitespace is missing

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7580]
**Describe the bug**

In Vim9 script, sometimes, it is not easy to find where a whitespace is missing.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            var v: number
            printf(' %*d%s%s%s%s%s %s',
                       bufnr('$')->len(), v,
                      !buflisted(v) ? 'u': ' ',
                      v == bufnr('%') ? '%' : v == bufnr('#') ? '#' : ' ',
                      win_findbuf(v)->empty() ? 'h' : 'a',
                      getbufvar(v, '&ma', 0) ? ' ' : '-',
                      getbufvar(v, '&mod', 0) ? '+' : ' ',
                      bufname(v)->empty()
                        ?    '[No Name]'
                        :     bufname(v)->fnamemodify(':t'))
        enddef
        Func()
    EOF
    )

`E1004` is raised:

    E1004: White space required before and after ':'

No context is given about where this whitespace is missing.

**Expected behavior**

The error message gives us more context about where the whitespace is missing.

For example, in the previous example, the missing whitespace comes from this line:

    !buflisted(v) ? 'u': ' ',
                      ^^

So, this error message would be more helpful:

    E1004: White space required before and after "!buflisted(v) ? 'u': ' ',"

**Environment**

 - Vim version: 8.2 Included patches: 1-2246
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(362)

**Additional context**

I suspect it can't be fixed, because when the compilation starts, the lines have already been concatenated during the sourcing step.  So, Vim doesn't see 10 short lines; it probably sees 1 long line:

    printf(' %*d%s%s%s%s%s %s', bufnr('$')->len(), v, !buflisted(v) ? 'u': ' ', v == bufnr('%') ? '%' : v == bufnr('#') ? '#' : ' ', win_findbuf(v)->empty() ? 'h' : 'a', getbufvar(v, '&ma', 0) ? ' ' : '-', getbufvar(v, '&mod', 0) ? '+' : ' ', bufname(v)->empty() ?    '[No Name]' :     bufname(v)->fnamemodify(':t'))

I still thought it was worth asking.  Maybe there is a way to add just a few characters before or after the missing whitespace to help us find it more quickly.

If it can be fixed, the code would need to change on this line:

<https://github.com/vim/vim/blob/4d8c96d4668ac965d4e84b9676fba6d7efe62a32/src/vim9compile.c#L4741>

    semsg(_(e_white_space_required_before_and_after_str), ":");
                                                          ^^^

I had a look at 8.2.2216 which fixed a similar issue, but couldn't fix it myself.

I tried to replace `":"` with different tokens which give different error messages:

    ┌─────────┬─────────────────────────────────────────────────────────────┐
    │ &next   │ E1004: White space required before and after ''             │
    ├─────────┼─────────────────────────────────────────────────────────────┤
    │ &p      │ E1004: White space required before and after '^ZWp^A'       │
    ├─────────┼─────────────────────────────────────────────────────────────┤
    │ arg     │ E1004: White space required before and after '^Z<8c><f3>^A' │
    ├─────────┼─────────────────────────────────────────────────────────────┤
    │ cctx    │ E1004: White space required before and after '<e0>:<fe>'    │
    ├─────────┼─────────────────────────────────────────────────────────────┤
    │ p       │ E1004: White space required before and after ': ' ','       │
    ├─────────┼─────────────────────────────────────────────────────────────┤
    │ ppconst │ E1004: White space required before and after ''             │
    └─────────┴─────────────────────────────────────────────────────────────┘

None of them seem to improve the error message.

**Comment by lacygoill** [comment]
> None of them seem to improve the error message.

Actually, I think using `p` helps; it's the end of the line.  The reason why I thought it didn't help is because Vim uses single quotes to surround the message.  It should be double quotes.

**Comment by lacygoill** [comment]
> It should be double quotes.

That is, instead of this:

    E1004: White space required before and after ': ' ','
                                                 ^      ^
                                                 ✘      ✘

We should read this:

    E1004: White space required before and after ": ' ',"
                                                 ^      ^
                                                 ✔      ✔

I'm going to try to find a fix, and submit a patch.

**Comment by lacygoill** [comment]
> It should be double quotes.

Although, what if the end of the line contains double quotes... I'm not sure how Vim handles quotes in error messages.

**Comment by hiromaily** [comment]
+1

**Comment by lacygoill** [comment]
I'm not sure it's correct, but I think this patch fixes the issue:
```diff
diff --git a/src/testdir/test_vim9_expr.vim b/src/testdir/test_vim9_expr.vim
index 4998471ee..58e0562bc 100644
--- a/src/testdir/test_vim9_expr.vim
+++ b/src/testdir/test_vim9_expr.vim
@@ -173,15 +173,14 @@ enddef
 func Test_expr1_trinary_fails()
   call CheckDefFailure(["var x = 1 ? 'one'"], "Missing ':' after '?'", 1)
 
-  let msg = "White space required before and after '?'"
+  let msg = "E1004: White space required before and after '?'"
   call CheckDefFailure(["var x = 1? 'one' : 'two'"], msg, 1)
   call CheckDefFailure(["var x = 1 ?'one' : 'two'"], msg, 1)
   call CheckDefFailure(["var x = 1?'one' : 'two'"], msg, 1)
 
-  let msg = "White space required before and after ':'"
-  call CheckDefFailure(["var x = 1 ? 'one': 'two'"], msg, 1)
-  call CheckDefFailure(["var x = 1 ? 'one' :'two'"], msg, 1)
-  call CheckDefFailure(["var x = 1 ? 'one':'two'"], msg, 1)
+  call CheckDefFailure(["var x = 1 ? 'one': 'two'"], "E1004: White space required before and after ': 'two''", 1)
+  call CheckDefFailure(["var x = 1 ? 'one' :'two'"], "E1004: White space required before and after ':'two''", 1)
+  call CheckDefFailure(["var x = 1 ? 'one':'two'"], "E1004: White space required before and after ':'two''", 1)
 
   call CheckDefFailure(["var x = 'x' ? 'one' : 'two'"], 'E1135:', 1)
   call CheckDefFailure(["var x = 0z1234 ? 'one' : 'two'"], 'E974:', 1)
diff --git a/src/vim9compile.c b/src/vim9compile.c
index 6ef2b5e77..b29d01721 100644
--- a/src/vim9compile.c
+++ b/src/vim9compile.c
@@ -4751,7 +4751,7 @@ compile_expr1(char_u **arg, cctx_T *cctx, ppconst_T *ppconst)
 
 	    if (!IS_WHITE_OR_NUL(**arg) || !IS_WHITE_OR_NUL(p[1]))
 	    {
-		semsg(_(e_white_space_required_before_and_after_str), ":");
+		semsg(_(e_white_space_required_before_and_after_str), p);
 		return FAIL;
 	    }
 
```

**Comment by brammool** [comment]
> I'm not sure it's correct, but I think this patch fixes the issue:

I think we should be more specific and mention both the character around
which the white space is required, and the point in the expression where
this is detected:

    E1004: White space required before and after '?' at "? this : that"

We can also use the same error number, since it's the same error, just
with a bit more info.

-- 
hundred-and-one symptoms of being an internet addict:
57. You begin to wonder how on earth your service provider is allowed to call
    200 hours per month "unlimited."

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
So, this patch is a start:
```diff
diff --git a/src/errors.h b/src/errors.h
index 4b4245a1b..37f546edc 100644
--- a/src/errors.h
+++ b/src/errors.h
@@ -42,7 +42,7 @@ EXTERN char e_syntax_error_at_str[]
 EXTERN char e_missing_return_value[]
 	INIT(= N_("E1003: Missing return value"));
 EXTERN char e_white_space_required_before_and_after_str[]
-	INIT(= N_("E1004: White space required before and after '%s'"));
+	INIT(= N_("E1004: White space required before and after '%s' at '%s'"));
 EXTERN char e_too_many_argument_types[]
 	INIT(= N_("E1005: Too many argument types"));
 EXTERN char e_str_is_used_as_argument[]
diff --git a/src/vim9compile.c b/src/vim9compile.c
index b483a6094..0544f67a7 100644
--- a/src/vim9compile.c
+++ b/src/vim9compile.c
@@ -4694,7 +4694,7 @@ compile_expr1(char_u **arg, cctx_T *cctx, ppconst_T *ppconst)
 
 	    if (!IS_WHITE_OR_NUL(**arg) || !IS_WHITE_OR_NUL(p[1]))
 	    {
-		semsg(_(e_white_space_required_before_and_after_str), ":");
+		semsg(_(e_white_space_required_before_and_after_str), ":", p);
 		return FAIL;
 	    }
 
```
It seems to fix the reported issue without breaking tests.  Before the patch, the error message is:

    E1004: White space required before and after ':'

After the patch, the error message is:

    E1004: White space required before and after ':' at ': ' ','

I'm surprised it doesn't break anything (considering that `e_white_space_required_before_and_after_str` now seems to expect two expressions, and that I'm pretty sure it's called with only 1 expression in other locations).  If this is correct, I'll try to do the other "missing whitespace" errors later.
