### ISSUE TITLE
Vim9: cannot use automatic line continuation in function call when line starts with function()

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7581]
**Describe the bug**

In Vim9 script, we cannot use an automatic line continuation inside the arguments of a function call, if a line starts with a `function()` expression.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            echo printf('%s %d',
                function('len'), 123)
        enddef
    EOF
    )

`E1057` is raised:

    E1057: Missing :enddef

**Expected behavior**

No error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-2246
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(362)

**Additional context**

The issue is specific to a `:def` function.  No error is raised at the script level:
```vim
vim9script
echo printf('%s %d',
    function('len'), 123)
```
    len 123

As a workaround, we need to break the arguments at a different location; so that `function()` doesn't end up at the start of an automatic line continuation.
```vim
vim9script
def Func()
    echo printf('%s %d', function('len'),
        123)
enddef
Func()
```
    len 123

---

If it can't be fixed, maybe it should be documented at `:h vim9-gotchas`.

**Comment by lacygoill** [comment]
> The issue is specific to a :def function. No error is raised at the script level:

Well, obviously, since there is no `:def`.  Although, what might be worth noting is that here `function()` is not parsed as a header's function.

**Comment by Shane-XB-Qian** [comment]
BTW: Vim9 cannot ‘echom Foo.bar’ but had to ‘echom foo bar’? Look so, a bit inconsistent..
