### ISSUE TITLE
Vim9: crash when concatenating boolean option with string

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7589]
**Describe the bug**

In Vim9 script, concatenating the value of a boolean option with a string inside a `:def` function might make Vim crash.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            set tgc
            echom '&tgc: ' .. &tgc
        enddef
        Func()
    EOF
    )

Vim crashes.

**Expected behavior**

Vim doesn't crash.

**Environment**

 - Vim version: 8.2 Included patches: 1-2257
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(363)

**Additional context**

Regression introduced in [8.2.2254](https://github.com/vim/vim/releases/tag/v8.2.2254).

---

- [backtrace](https://github.com/vim/vim/files/5758392/backtrace.txt)
- [valgrind log](https://github.com/vim/vim/files/5758393/valgrind.log)
- [asan log](https://github.com/vim/vim/files/5758391/asan.log)

**Comment by lacygoill** [comment]
I can't reproduce anymore.  It was probably fixed by [8.2.2261](https://github.com/vim/vim/releases/tag/v8.2.2261).

**Comment by brammool** [comment]
Also fixed by 8.2.2261.
I do think that the result should be "&tgc: true" instead of "&tgc: v:true".

**Comment by lacygoill** [comment]
> I do think that the result should be "&tgc: true" instead of "&tgc: v:true".

That's what I've always thought too.  If in the Vim9 context, `true` should be printed, otherwise `v:true`.  But I think `:echo` and `:echom` have always printed `v:true`.  And that's what the help seems to document:

https://github.com/vim/vim/blob/d5ea8f08f78d20fde8773663894de5e8c023bd83/runtime/doc/vim9.txt#L632

If `:echo` printed `true`, then this example should be re-written like this:

    'hello ' .. v:true  == 'hello true'
                                  ^--^
                                  no "v:" prefix

**Comment by brammool** [comment]
If we use "true" and "false" when writing Vim9 script, then Vim should also echo that.
Using v:true and v:false is unexpected.
