### ISSUE TITLE
sh syntax hightlight breaks on "${VAR/FOO/\\[}"

### ISSUE THREAD

**Issue by Self-Perfection** [vim/vim#759]
``` bash
"${VAR/FOO/\\[}"
```

is a bashism to substitute `'FOO'` in `$VAR` with `'\['`
vim fails to notice trailing double quote and the of a script becomes highlighted as doublequoted. Demo script to check highlighting:

``` bash
#!/bin/bash
VAR1=FOOBAR
VAR2="${VAR1/FOO/\\[}"
echo "$VAR2"
```

Handling of this case was broken in 541f92d6cfdf2215e743553b5f4b6529dd9fcf31 (starting sh.vim version 137)

Probably this issue is related to #364

**Comment by chrisbra** [comment]
please test with the latest version from [charles](http://www.drchip.org/astronaut/vim/index.html#SYNTAX_SH)

**Comment by Self-Perfection** [comment]
OK, rechecked with http://www.drchip.org/astronaut/vim/syntax/sh.vim.gz (version 148             ASTRO-ONLY) and it works as expected on my example.

**Comment by chrisbra** [comment]
thanks for checkint.
