### ISSUE TITLE
Vim9: unpack notation can be abused to bypass type checking

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7594]
**Describe the bug**

In Vim9 script, the unpack notation can be abused to bypass type checking.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            [x, y] = [1, 'string']
            x = {a: 0}
            echo x
            x = [2, 3]
            echo x
        enddef
        Func()
    EOF
    )

Vim echo'es a dictionary and a list:

    {'a': 0}
    [2, 3]

**Expected behavior**

Vim doesn't echo anything.  `E1012` is raised:

    E1012: Type mismatch; expected number but got dict<number>

**Environment**

 - Vim version: 8.2 Included patches: 1-2262
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(363)

**Additional context**

Regression introduced in [8.2.2114](https://github.com/vim/vim/releases/tag/v8.2.2114).

---

This can be used to bypass type checking on an arbitrary variable.

Example:
```vim
vim9script
def Func()
    var x = 1
    x = 'string'
enddef
Func()
```
    E1012: Type mismatch; expected number but got string

We correctly failed to change the type of `x`.
```vim
vim9script
def Func()
    [x, _] = [1, v:none]
    x = 'string'
enddef
Func()
```
This time, we incorrectly succeeded.

---

Patch adding a test:
```diff
diff --git a/src/testdir/test_vim9_assign.vim b/src/testdir/test_vim9_assign.vim
index 83c26a417..9cdd961b7 100644
--- a/src/testdir/test_vim9_assign.vim
+++ b/src/testdir/test_vim9_assign.vim
@@ -267,6 +267,12 @@ def Test_assign_unpack()
       [v1, v2] = ''
   END
   CheckDefFailure(lines, 'E1012: Type mismatch; expected list<any> but got string', 3)
+
+  lines =<< trim END
+      [v1, v2] = [1, 'string']
+      v1 = {a: 0}
+  END
+  CheckDefFailure(lines, 'E1012: Type mismatch; expected number but got dict<number>', 2)
 enddef
 
 def Test_assign_linebreak()
```

**Comment by lacygoill** [comment]
I guess the code was not unreachable, and needs to be re-included.  If so, maybe this patch will fix the issue:
```diff
diff --git a/src/vim9compile.c b/src/vim9compile.c
index 045061e1c..a03112f77 100644
--- a/src/vim9compile.c
+++ b/src/vim9compile.c
@@ -5578,6 +5578,16 @@ compile_assignment(char_u *arg, exarg_T *eap, cmdidx_T cmdidx, cctx_T *cctx)
 			    }
 			}
 		    }
+		    else if (name[1] == ':' && name[2] != NUL)
+		    {
+			semsg(_(e_cannot_use_namespaced_variable), name);
+			goto theend;
+		    }
+		    else if (!is_decl)
+		    {
+			semsg(_(e_unknown_variable_str), name);
+			goto theend;
+		    }
 		    else if (check_defined(var_start, varlen, cctx) == FAIL)
 			goto theend;
 		}
```

**Comment by lacygoill** [comment]
> I guess the code was not unreachable, and needs to be re-included. If so, maybe this patch will fix the issue:

Yes and no.  It does correctly reintroduce an error, but it's not the right error.

    E1089: Unknown variable: x

It should be `E1012`.

**Comment by lacygoill** [comment]
> It should be `E1012`.

Or:

   - it's the right error
   - it's not the right error, but `E1012` is not the right one either, because `[x, y] = ...` should already have raised one, since neither `x` nor `y` were declared before

**Comment by brammool** [comment]
> **Describe the bug**
> 
> In Vim9 script, the unpack notation can be abused to bypass type checking.
> 
> **To Reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(cat <<'EOF'
>         vim9script
>         def Func()
>             [x, y] = [1, 'string']
>             x = {a: 0}
>             echo x
>             x = [2, 3]
>             echo x
>         enddef
>         Func()
>     EOF
>     )
> 
> Vim echo'es a dictionary and a list:
> 
>     {'a': 0}
>     [4, 5, 6]
> 
> **Expected behavior**
> 
> Vim doesn't echo anything.  `E1012` is raised:
> 
>     E1012: Type mismatch; expected number but got dict<number>

Well, the actual error is declaring a variable without "var".
This is both in a compiled function and at the script level.
It takes some more effort to get it right.


-- 
hundred-and-one symptoms of being an internet addict:
82. AT&T names you Customer of the Month for the third consecutive time.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> Well, the actual error is declaring a variable without "var".

Yes, sorry, I'm not sure what I was thinking when I wrote that.  The real issue was that there was no declaration before the assignment.  Otherwise, there is no bug, because the rhs of the assignment has the type `list<any>`, therefore, anything in the lhs has the type `any`.  Thus, it's not unexpected to later be able to store any type of value in the variable.

Now I wonder whether we should have kept this syntax working.  It could have been used to tell Vim that we want to assign a few values to some variables, and that we don't care about their types.  We can already do it like this:
```vim
vim9script
var x: any
var y: any
var z: any
[x, y, z] = [1, 'x', true]
```
But with this special syntax, it would have been less verbose:
```vim
vim9script
[x, y, z] = [1, 'x', true]
```
Although, it would violate the rule which requires that a variable must be declared before being assigned, so maybe not a good idea if we want to stay consistent.

---

> This is both in a compiled function and at the script level.

True, there might be another issue at the script level, but I thought the report would become too confusing with it.

This works:
```vim
vim9script
var [x, y] = [123, 'string']
```
It shouldn't according to `:h E1092`.

https://github.com/vim/vim/blob/edc10b541b468f5f5aa2e2d5ef58a3e17e043bff/runtime/doc/vim9.txt#L320-L325

Unless this restriction is limited to a `:def` function.  In which case the help might need an update:
```diff
diff --git a/runtime/doc/vim9.txt b/runtime/doc/vim9.txt
index b21b7bfad..8d81c0d09 100644
--- a/runtime/doc/vim9.txt
+++ b/runtime/doc/vim9.txt
@@ -319,7 +319,7 @@ The constant only applies to the value itself, not what it refers to. >
 
 <							*E1092*
 Declaring more than one variable at a time, using the unpack notation, is
-currently not supported: >
+currently not supported inside a `:def` function: >
 	var [v1, v2] = GetValues()  # Error!
 That is because the type needs to be inferred from the list item type, which
 isn't that easy.
```
Although, it's really convenient that it works at the script level.  And it really works well; that is the variables are not inferred with the type `any` simply because the rhs has the type `list<any>`.  They are inferred with the proper types, which are enforced later on:
```vim
vim9script
var [x, y] = [123, 'string']
x = true
```
    E1012: Type mismatch; expected number but got bool

So, ideally, this should not be fixed; the help just needs a minor update.  Later, maybe we'll be able to leverage the mechanism which allows this syntax to work at the script level and make it work in a `:def` function too; at which point `:h E1092` might be removed.
