### ISSUE TITLE
Vim9: need str2nr() to compare g:actual_curwin to window ID

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7600]
**Describe the bug**

In Vim9 script, we cannot directly compare `g:actual_curwin` (nor `g:actual_curbuf`) to a window ID (or to a buffer number).

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9
        set laststatus=2 statusline=%{CurrentFlags()}
        def g:CurrentFlags(): string
            return (g:actual_curwin == win_getid() ? '[curwin]' : '[not curwin]')
              .. (g:actual_curbuf == bufnr() ? '[curbuf]' : '[not curbuf]')
        enddef
    EOF
    )

`E1030` is raised:

    E1030: Using a String as a Number: "1000"

**Expected behavior**

No error is raised, because we most probably want to use these variables in numeric comparisons, not string comparisons.

**Environment**

 - Vim version: 8.2 Included patches: 1-2269
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(363)

**Additional context**

Workaround: pass the variables to `str2nr()`:
```vim
vim9script
set laststatus=2 statusline=%{CurrentFlags()}
def g:CurrentFlags(): string
    return (g:actual_curwin->str2nr() == win_getid() ? '[curwin]' : '[not curwin]')
      .. (g:actual_curbuf->str2nr() == bufnr() ? '[curbuf]' : '[not curbuf]')
enddef
```
Still, I think people would prefer that the variables are recast as numbers; and it makes sense for a window *ID* and a buffer *number* to be stored in number variables rather than string variables.  I don't think it would cause issues in legacy scripts where a number can be automatically coerced into a string if necessary.

---

Patch adding a test:
```diff
diff --git a/src/testdir/test_vim9_script.vim b/src/testdir/test_vim9_script.vim
index d9aa71e26..28391337b 100644
--- a/src/testdir/test_vim9_script.vim
+++ b/src/testdir/test_vim9_script.vim
@@ -732,6 +732,19 @@ def Test_statusline_syntax()
       set laststatus statusline= 
   END
   CheckScriptSuccess(lines)
+
+  # g:actual_curwin and g:actual_curbuf are numbers, not strings
+  lines =<< trim END
+    vim9script
+    set laststatus=2 statusline=%{CurrentFlags()}
+    def g:CurrentFlags(): string
+      return (g:actual_curwin == win_getid() ? '[curwin]' : '[not curwin]')
+        .. (g:actual_curbuf == bufnr() ? '[curbuf]' : '[not curbuf]')
+    enddef
+    redrawstatus
+    set laststatus statusline= 
+  END
+  CheckScriptSuccess(lines)
 enddef
 
 def Test_list_vimscript()
```

**Comment by lacygoill** [comment]
> Patch adding a test:

Sorry, I didn't reset `'laststatus'` properly at the end.  That's because I started from a copy of the previous test where the option is incorrectly reset.  New patch:

```diff
diff --git a/src/testdir/test_vim9_script.vim b/src/testdir/test_vim9_script.vim
index d9aa71e26..3fb11af8f 100644
--- a/src/testdir/test_vim9_script.vim
+++ b/src/testdir/test_vim9_script.vim
@@ -729,7 +729,20 @@ def Test_statusline_syntax()
       endfunc
       set laststatus=2 statusline=%!Status()
       redrawstatus
-      set laststatus statusline= 
+      set laststatus&vim statusline= 
+  END
+  CheckScriptSuccess(lines)
+
+  # g:actual_curwin and g:actual_curbuf are numbers, not strings
+  lines =<< trim END
+    vim9script
+    set laststatus=2 statusline=%{CurrentFlags()}
+    def g:CurrentFlags(): string
+      return (g:actual_curwin == win_getid() ? '[curwin]' : '[not curwin]')
+        .. (g:actual_curbuf == bufnr() ? '[curbuf]' : '[not curbuf]')
+    enddef
+    redrawstatus
+    set laststatus&vim statusline= 
   END
   CheckScriptSuccess(lines)
 enddef
```

**Comment by brammool** [comment]
Well, the help explicitly states "These values are strings".  Changing that would not be backwards compatible.
As you mention, str2nr() can be used.  I don't think we should do something else, such as providing other variables that are type number, or detecting that a Vim9 function is used.  Usin str2nr() is simple enough.
