### ISSUE TITLE
Vim9: setwinvar() does not take true as third argument

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7603]
**Describe the bug**

In Vim9 script, we cannot use `setwinvar()` to set a boolean window-local option.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        setwinvar(win_getid(), '&number', true)
    EOF
    )

`E1138` is raised:

    E1138: Using a Bool as a Number

**Expected behavior**

No error is raised because `'number'` is a boolean option, and `true` is a boolean value.

**Environment**

 - Vim version: 8.2 Included patches: 1-2269
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(363)

**Additional context**

Regression introduced in [8.2.1465](https://github.com/vim/vim/releases/tag/v8.2.1465).

---

Same issue with `setbufvar()`:
```vim
vim9script
setbufvar(bufnr(), '&autoindent', true)
```
    E1138: Using a Bool as a Number

And `settabwinvar()`:
```vim
vim9script
settabwinvar(1, 1, '&list', true)
```
    E1138: Using a Bool as a Number

---

No error in Vim script legacy:
```vim
call setwinvar(win_getid(), '&number', v:true)
```
---

Patch adding a test:
```diff
diff --git a/src/testdir/test_vim9_builtin.vim b/src/testdir/test_vim9_builtin.vim
index accbca237..3fb2fb088 100644
--- a/src/testdir/test_vim9_builtin.vim
+++ b/src/testdir/test_vim9_builtin.vim
@@ -601,11 +601,15 @@ def Test_setbufvar()
   &syntax->assert_equal('vim')
   setbufvar(bufnr('%'), '&ts', 16)
   &ts->assert_equal(16)
+  setbufvar(bufnr('%'), '&ai', true)
+  &ai->assert_equal(true)
   settabwinvar(1, 1, '&syntax', 'vam')
   &syntax->assert_equal('vam')
   settabwinvar(1, 1, '&ts', 15)
   &ts->assert_equal(15)
-  setlocal ts=8
+  settabwinvar(1, 1, '&list', true)
+  &list->assert_equal(true)
+  setlocal ts=8 noai nolist
 
   setbufvar('%', 'myvar', 123)
   getbufvar('%', 'myvar')->assert_equal(123)
```

**Comment by lacygoill** [comment]
The issue persists when `setwinvar()` receives its value from `getwinvar()`:
```vim
vim9
var id = win_getid()
getwinvar(id, '&number')->setwinvar(id, '&number')
```
    E521: Number required: &number = 'false'

Which is weird, considering that `getwinvar()` outputs a boolean number, and that replacing `getwinvar()` with a boolean number doesn't raise any error:
```vim
vim9
var id = win_getid()
eval 0->setwinvar(id, '&number')
```
    ✔
```vim
vim9
var id = win_getid()
eval 1->setwinvar(id, '&number')
```
    ✔

---

Same issue in a `:def` function:
```vim
vim9
def Func()
    var id = win_getid()
    getwinvar(id, '&number')->setwinvar(id, '&number')
enddef
Func()
```
    E521: Number required: &number = 'false'

**Comment by brammool** [comment]
Strangely, it only happens when 'number' is not set.
