### ISSUE TITLE
Build failure after make distclean

### ISSUE THREAD

**Issue by ghost** [vim/vim#761]
I've always had the "make" build fail after a pull and distclean. It seems that distclean does not remove src/auto/config.mk. After removing that file manually after a distclean, I can "make" successfully.

Also, the "make distclean" has to be from the top level vim directory, not from within src, as http://www.vim.org/git.php says.

This is on Slackware current and Debian 7.

**Comment by brammool** [comment]
NightVigil wrote:

> I've always had the "make" build fail after a pull and distclean. It
> seems that distclean does not remove src/auto/config.mk. After
> removing that file manually after a distclean, I can "make"
> successfully.

What should happen is that config.mk.dist overwrites auto/config.mk.
Perhaps you have a permission problem?

## 

"My particular problem is with registry entries, which seem to just
accumulate like plastic coffee cups..."           -- Paul Moore

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ghost** [comment]
Permissions were good (664) on both config.mk.dist and auto/config.mk. I notice that "make" itself recreates that file, so I end up doing this from the top level directory:
1. git pull
2. make distclean
3. rm src/auto/config.mk
4. cd src
5. make
6. # auto/config.mk now exists

This, for me at least, works.

**Comment by lacygoill** [comment]
I can't reproduce; maybe it has been fixed?

I can run `make` after `make distclean` without removing the `src/auto/config.mk` file; and I don't have to run `make distclean` from the top level, it seems to also work from `src/`.

**Comment by brammool** [comment]
I'm sure we would hear many more complaints if this was still failing.
