### ISSUE TITLE
vim9: command :g/string/m$ not working

### ISSUE THREAD

**Issue by alexaschee** [vim/vim#7616]
**Describe the bug**
In a vim9script `:g/something/m$` raises error `E1144`.

**To Reproduce**

    vim9script
    # aaa
    :g/aaa/t$
    :g/aaa/m$    

`so %` gives:
 `E1144: Command is not followed by white space: m$`
  and
 `E1144: Command is not followed by white space: t$`

**Environment (please complete the following information):**
 - Vim version 8.2.2282
 - OS: Windows 10

**Comment by brammool** [comment]
That is intentional, you need to put a space between the command and the argument.
Also, the "t" command is not supported, you need to use "copy".
