### ISSUE TITLE
Mode and text-prop safe text patching solution

### ISSUE THREAD

**Issue by hrsh7th** [vim/vim#7617]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

I'm trying to implement a feature that likes a mirror cursor with text-prop because text-prop is a good solution for managing regions that will follow some text changes.

I tried the below approaches for the situation of `<div|>...</div>`.
1. Listen `TextChanged`, `TextChangedI` and `TextChangedP`.
2. Detect modified tag name (e.g.: `<span|>...</div>` as `span`)
3. Reflect `span` to other regions

The steps of 3 can't implement for now.

1. `normal! 1G11|v1G13|di...` (patching buffer text by `i`)
- It ideal solution but can't use `normal! i...` if `pumvisible()` is true.

2. `normal! 1G11|v1G13|dP` (patching buffer text by `P` command)
-  It does not modify text-props regions.

3. `setline/append/deletebufline` (patching buffer text by functions)
- It can't realize char-wise changes.

**Describe the solution you'd like**

I think the ideal solution is allowing `normal! i...` even if the `pumvisible()` is true.

**Describe alternatives you've considered**

Also, the below approaches will solve this problem.

- text-props follows the changes that by normal-mode commands
- Add a function that likes `settext(start_lnum, start_col, end_lnum, end_col, text)`

**Additional context**

The behavior of `normal! i...` is mentioned in here (https://github.com/vim/vim/blob/master/runtime/doc/insert.txt#L672)

**Comment by bfrg** [comment]
Related #5632

**Comment by hrsh7th** [comment]
I found the implementation that is responsible for this behavior.

https://github.com/vim/vim/blob/master/src/edit.c#L173

**Comment by hrsh7th** [comment]
I found the way to solve it!
The `substitute` command will fix text-props tegions and it is safe to use with `pumvisible() = true`!
