### ISSUE TITLE
Vim9: variable wrongly locked when saving option value

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7620]
**Describe the bug**

In Vim9 script, sometimes, we cannot save an option in a buffer-local variable, because the variable is locked, even though we never asked to lock it.

**To Reproduce**

Run this shell command:

    vim -Nu NONE --cmd 'au VimEnter * ++nested edit /tmp/file | tabe /tmp/file' -S <(cat <<'EOF'
        vim9script
        writefile([''], '/tmp/file')
        au BufWinEnter * Func()
        au BufWritePost * windo Func()
        def Func()
            b:name = &l:fdm
        enddef
        timer_start(0, () => execute('w'))
    EOF
    )

`E741` is raised:

    E741: Value is locked: name

It doesn't happen all the time.  If no error is raised, you might need to quit and re-run the command a few times.

**Expected behavior**

`E741` is never raised because `b:name` is not locked by `:const`, `:final`, or `:lockvar`.

**Environment**

 - Vim version: 8.2 Included patches: 1-2301
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(363)

**Additional context**

Regression introduced in [8.2.2193](https://github.com/vim/vim/releases/tag/v8.2.2193).

---

The issue disappears when `Func()` is re-written in a legacy function:

    vim -Nu NONE --cmd 'au VimEnter * ++nested edit /tmp/file | tabe /tmp/file' -S <(cat <<'EOF'
        vim9script
        writefile([''], '/tmp/file')
        au BufWinEnter * Func()
        au BufWritePost * windo Func()
        fu Func()
            let b:name = &l:fdm
        endfu
        timer_start(0, () => execute('w'))
    EOF
    )

The issue disappears when we save something else than an option value; e.g. a number like `123`:

    vim -Nu NONE --cmd 'au VimEnter * ++nested edit /tmp/file | tabe /tmp/file' -S <(cat <<'EOF'
        vim9script
        writefile([''], '/tmp/file')
        au BufWinEnter * Func()
        au BufWritePost * windo Func()
        def Func()
            b:name = 123
        enddef
        timer_start(0, () => execute('w'))
    EOF
    )

**Comment by lacygoill** [comment]
Workaround: wrap the assignment in an `:exe`:

    # ✘
    b:name = &l:fdm

    # ✔
    exe 'b:name = &l:fdm'

Which gives:

    vim -Nu NONE --cmd 'au VimEnter * ++nested edit /tmp/file | tabe /tmp/file' -S <(cat <<'EOF'
        vim9script
        writefile([''], '/tmp/file')
        au BufWinEnter * Func()
        au BufWritePost * windo Func()
        def Func()
            exe 'b:name = &l:fdm'
        enddef
        timer_start(0, () => execute('w'))
    EOF
    )

**Comment by lacygoill** [comment]
The issue has nothing to do with the unpredictability inherent to a timer, nor with the side-effects of `:windo`.
Where I found this issue, there is no timer, and no `:windo`.

The timer can be removed; but then we need to execute `:w` manually.
`:windo` can be replaced with a combination of `map()`, `getwininfo()` and `win_execute()`, without the issue being affected.

Here is [more context](https://github.com/lacygoill/vim-fold/blob/43061561b0dfd1181b0ed0e9005711c119872e5b/autoload/fold/lazy.vim#L411-L412) on the real code.

**Comment by brammool** [comment]
I managed to reproduce it manually, valgrind reports using uninitialized memory.
But haven't been able to have a test trigger this valgrind warning.
