### ISSUE TITLE
Using source to call a command with f-args does not work

### ISSUE THREAD

**Issue by daveola** [vim/vim#7623]
Example setup:

    :function Varg(...)
    :  echo a:000
    :endfunction

    :call Varg("a", "b")
    
    :command -nargs=* Vcmd call Varg(<f-args>)  

This all works.  We can do, as expected:

    :Vcmd a b c

And we get:

     ['a','b','c']

But if we try to put this same line in a file:

    :Vcmd a b c

Then we source it with:

    :so %

We get the error:

    Error detected while processing testfile:                                
    line   10:                           
    E176: Invalid number of arguments

**Comment by brammool** [comment]
It works fine for me.  Perhaps you have Vcmd redefined somehwere?

**Comment by daveola** [comment]
I invented those just for simplifying this case for the bug report.

And I just realized that I hadn't written the file when I did the last :so, and I've figured out the actual issue, so I'll close this and see if there's a bug for that already open.

**Comment by daveola** [comment]
Ah, sadly the problem is that (...) and a:000 is limited to 20 arguments.

Crushing.  This reminds me of the limit of +commands on the command line - presumably vim is using a bunch of statically allocated arrays somewhere?  It seems like it would make sense to use a growable resource and raise the limit of these arguments.

But so it goes for now, and it's not a bug.

**Comment by lacygoill** [comment]
How about this:
```vim
fu Varg(optional = [])
    echo a:optional
endfu

com -nargs=* Vcmd call Varg([<f-args>])

Vcmd a b c d e f g h i j k l m n o p q r s t u
```
