### ISSUE TITLE
Vim9: = operator conflates end of dictionary with end of block

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7628]
**Describe the bug**

In Vim9 script, the `=` operator might conflate the end of a dictionary with an end of block, which breaks the indentation.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9
        var lines =<< END
            vim9

            def FuncA()
                var d = {
                    }
            enddef

            def FuncB()
            enddef
    END
        setline(1, lines)
        filetype indent on
        set ft=vim
        feedkeys('=G', 'nxt')
    EOF
    )

The resulting buffer is:

    vim9

    def FuncA()
    	var d = {
    }
    	enddef

    	def FuncB()
    	enddef

**Expected behavior**

The resulting buffer is:

    vim9

    def FuncA()
    	var d = {
    	}
    enddef

    def FuncB()
    enddef

**Environment**

 - Vim version: 8.2 Included patches: 1-2305
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(363)

**Additional context**

This patch fixes the issue:
```diff
diff --git a/runtime/indent/vim.vim b/runtime/indent/vim.vim
index 4b0867d88..eab8a2c6c 100644
--- a/runtime/indent/vim.vim
+++ b/runtime/indent/vim.vim
@@ -117,7 +117,7 @@ function GetVimIndentIntern()

   " Subtract a 'shiftwidth' on a :endif, :endwhile, :catch, :finally, :endtry,
   " :endfun, :enddef, :else and :augroup END.
-  if cur_text =~ '^\s*\(ene\@!\|}\|cat\|finall\|el\|aug\%[roup]\s\+[eE][nN][dD]\)'
+  if cur_text =~ '^\s*\(ene\@!\|cat\|finall\|el\|aug\%[roup]\s\+[eE][nN][dD]\)'
     let ind = ind - shiftwidth()
   endif

```
However, it's probably wrong; I think `}` was there for the new block syntax.

I would argue that `}` will be used more often alone on a line to end a dictionary rather than to end a block, because:

   - the block syntax is much more recent
   - in practice, the block syntax is rarely needed

So, I would be tempted to apply the patch nevertheless.

Or, we could try to rely on some heuristics inspecting the previous line to try and guess whether `}` is closing a dictionary.  But I can't think of anything simple.

**Comment by brammool** [comment]
We can use the "%" command to find the matching "{".  If it's at the start of the line it must be a block, otherwise a dictionary.
We should also indent if the start of a dictionary is found, up to the matching "}".

We can also recognize a "[" at the end of the line and indent the next line, and de-indent when a "]" is found at the start of the line.

This only supports dicts and lists with items on a separate line, but that would be the usual way to do this.
