### ISSUE TITLE
Vim9: cannot use :function {'<lambda>123'} to get body of lambda expression

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7634]
**Describe the bug**

In Vim9 script, we cannot get the body of a lambda expression.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9
        timer_start(1'000, () => 0)
        exe timer_info()[0].callback
            ->string()
            ->substitute('(', '{', '')
            ->substitute(')', '}', '')
            ->substitute('function\zs', ' ', '')
    EOF
    )

`E129` is raised:

    E129: Function name required

**Expected behavior**

No error is raised, because the command `function {'<lambda123>'}` is valid and documented at the end of `:h lambda`.

https://github.com/vim/vim/blob/ebbf11c1198b7aec8a1a55f7231ecb4f1a432fa0/runtime/doc/eval.txt#L648-L650

**Environment**

 - Vim version: 8.2 Included patches: 1-2306
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(363)

**Additional context**

The exact same code works fine in Vim script legacy:
```vim
call timer_start(1000, {-> 0})
exe timer_info()[0].callback
    \ ->string()
    \ ->substitute('(', '{', '')
    \ ->substitute(')', '}', '')
    \ ->substitute('function\zs', ' ', '')
```
    function <lambda>1(...)
    1  return 0
    endfunction

---

This syntax is useful while debugging a lambda expression.  I rely on it in a plugin to display the output of `timer_info()` in a more human-readable form, and with more info (i.e. with the lambda's definition).

---

Regression introduced in [8.2.0601](https://github.com/vim/vim/releases/tag/v8.2.0601) (which is weird considering that the commit message is about something completely different...).

**Comment by brammool** [comment]
This uses the {} notation, which is not supported in Vim9 script.
The :disassemble command understands the <lambda>9 name, we can make :function do the same.
