### ISSUE TITLE
Vim9: internal error when filtering list with lambda expression

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7635]
**Describe the bug**

In Vim9 script, filtering a list with a lambda expression might raise an internal error.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9
        def Func(a: string, b: number, c: number)
            var Filter = (l) => filter(l, (_, v) => stridx(v, a) == 0)
            if 1
                ['']->Filter()
            endif
            var x = 0
        enddef
        Func('', 0, 0)
    EOF
    )

`E685` is raised:

    E685: Internal error: copy_tv(UNKNOWN)

**Expected behavior**

`E685` is not raised, because it's an internal error.

**Environment**

 - Vim version: 8.2 Included patches: 1-2306
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(363)

**Additional context**

I haven't been able to get any log for this issue, nor to bisect it.

There was a weird error on 8.2.0500:

    E1050: Item not found: a

It crashed on 8.2.1000.
And there was already an internal error on 8.2.1500.

**Comment by lacygoill** [comment]
Ah, the snippet can be simplified a little more:
```vim
vim9
def Func(a: string, b: number, c: number)
    var Filter = (l) => filter(l, (_, v) => stridx(v, a) == 0)
    ['']->Filter()
    var x = 0
enddef
Func('', 0, 0)
```

**Comment by lacygoill** [comment]
Since the issue involves a nested closure, it might be related to #7150, for which there is a todo item:

https://github.com/vim/vim/blob/ebbf11c1198b7aec8a1a55f7231ecb4f1a432fa0/runtime/doc/todo.txt#L112

**Comment by lacygoill** [comment]
> It crashed on 8.2.1000.
> And there was already an internal error on 8.2.1500.

The crash stopped on [8.2.1482](https://github.com/vim/vim/releases/tag/v8.2.1482).  On the same commit, the internal error started to appear.

**Comment by brammool** [comment]
Yes, it's because of the nested closure.  That's some work to implement...
