### ISSUE TITLE
Vim9: allow negative index to get character from string starting from its end

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7643]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

It is not hard to get the last character of a string:
```vim
echo 'string'[-1:-1]
```
    g

But we have to write `:-1`, otherwise we get an empty string:
```vim
echo 'string'[-1]
```
    empty string

This is weird.  This is also inconsistent with lists.  If we want the last item in a list, which is a similar goal, we can simply write `[-1]`:
```vim
echo [1, 2, 3][-1]
```
    3

**Describe the solution you'd like**

This quirk is documented at `:h subscript`:

https://github.com/vim/vim/blob/b657198cb30765468451d7f68fce49b5b4000c5d/runtime/doc/eval.txt#L1192-L1193

The help says it's for backward compatibility.  I can understand that Vim9 wants to stay compatible with some syntaxes because they're useful, but I don't think this particular syntax is one of them.

In Vim9 script, could we make `[-1]` work with a string just like it already works with a list?

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by lacygoill** [comment]
> But we have to write :-1, otherwise we get an empty string:

It can be slightly shortened into ` :`:
```vim
vim9
echo 'string'[-1 :]
```
    g

Unless we want the last but one character:
```vim
vim9
echo 'string'[-2 : -2]
```
    n

This time, we really need ` : -2`.

**Comment by lacygoill** [comment]
> Unless we want the last but one character:

In which case, we have to write 5 extra characters, not 3, because we need whitespace around the colon since [8.2.2250](https://github.com/vim/vim/releases/tag/v8.2.2250).

**Comment by brammool** [comment]
It makes sense to have the negative index work like with a list, that's what most people will expect.
Unlike a list we return an empty string when the index is out of range.  It's easier to handle than requiring a try/catch in a place the number can be computed wrong.
