### ISSUE TITLE
Vim9: type checking ignores wrong type in funcref declaration in ":def" function

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7646]
**Describe the bug**

In Vim9 script, sometimes, type checking ignores a wrong type in a funcref declaration in a `:def` function.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9
        def Func()
            var l = [1, 2, 3]
            var Ref: func(number, job): bool
            Ref = (_, v) => v == 2
            echo l->filter(Ref)
        enddef
        Func()
    EOF
    )

No error is raised.  `[2]` is echo'ed.

**Expected behavior**

An error is raised, because the funcref `Ref` is declared with the type `func(number, job): bool`:

    var Ref: func(number, job): bool

But `filter()` did not pass jobs to `Ref`; it passed numbers.

**Environment**

 - Vim version: 8.2 Included patches: 1-2318
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(363)

**Additional context**

There are other issues at the script level, but it's going to get confusing, so I'll open a separate issue.

**Comment by lacygoill** [comment]
I'm not sure this is a bug actually.  Maybe the types are only inspected at compile time, when the assignment occurs.  At that moment, it might be hard – if not impossible – for Vim to know whether the given types are right or wrong, simply by looking at the expression in the lambda which could be arbitrarily complex.

I wasn't expecting an error to be raised at that moment though.  I was expecting an error to be raised at runtime.  I'm not sure whether the types specified in the funcref declaration are meant to be still in effect after the assignment, once the funcref is invoked...

**Comment by lacygoill** [comment]
I suspect it's not a bug, so closing.

**Comment by lacygoill** [comment]
> I suspect it's not a bug, so closing.

Yes, I'm sure it's not a bug.  The types in a funcref declaration are only meant to be compared to the optional types in the lambda assignment.

---

However, there are still what seems to be inconsistent behaviors at the script level.

For example, this is OK in a `:def` function:
```vim
vim9
def Func()
    var l = [1, 2, 3]
    var Ref: func(number, number): bool
    Ref = (_, v) => v == 2
    echo l->filter(Ref)
enddef
Func()
```
But not at the script level:
```vim
vim9
var l = [1, 2, 3]
var Ref: func(number, number): bool
Ref = (_, v) => v == 2
echo l->filter(Ref)
```
    E1012: Type mismatch; expected func(number, number): bool but got func(any, any): any

And this doesn't raise any error:
```vim
vim9
var l = [1, 2, 3]
var Ref: func
Ref = (_: job, v: job): job => v.n+1 == 2
echo l->filter(Ref)
```
    [1, 2, 3]

But it should because:

   - all the types are wrong
   - the expression in the lambda's body handles `v` as a dictionary and tries to access the key `n`, while `v` is not a dictionary but a number
   - there is no whitespace around the `+`

Regarding the last bullet point, usually, Vim does enforce the rule even in a lambda's body:
```vim
vim9
echo (() => 1+1)()
```
    E1004: White space required before and after '+' at "+1"

**Comment by brammool** [comment]
Yeah, it's going to be hard to raise an error for this.  The individual commands are OK.
It would require adding a wrapper around the lambda when it is assigned to "Ref", checking that the argument indeed is a job.
But the lambda itself is fine, when assigning it to another funcref it should not check for a job argument.
Also, it's unlikely type checking will help the author of the script here.  So let's leave it.
