### ISSUE TITLE
Patch 7.4.1744 undoes patch 7.4.1743

### ISSUE THREAD

**Issue by Anstow** [vim/vim#765]
In the function `ConvertFromPySequence` in src/if_py_both.h, ret has no initial value (which clang warns about).

Fix change line 6080 of src/if_py_both.h from

```
int ret;
```

to

```
int ret = 0;
```

**Comment by vim-ml** [comment]
ConvertFromPyMapping also has no initial value. Why it does not warn there?

`ret` is always used initialized now.

2016-04-18 14:17 GMT+03:00 David Watson vim-dev-github@256bit.org:

**Comment by Anstow** [comment]
I see now, thanks.

**Comment by vim-ml** [comment]
Hi,

It is so exciting to tell you about what happened yesterday, you should better read it yourself <http://rijangeshy.thewilcoxes.org/lnkox>

All best, hide_seeker@yahoo.co.jp
