### ISSUE TITLE
Vim9: crash when making list mutate

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7652]
**Describe the bug**

In Vim9 script, making a list mutate might make Vim crash.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9
        def Func()
            var a = ['x']
            a->map((_, v) => split(v, ''))
            for b in a
                b[:]->copy()
            endfor
        enddef
        Func()
    EOF
    )

Vim crashes.

**Expected behavior**

Vim doesn't crash.

**Environment**

 - Vim version: 8.2 Included patches: 1-2323
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(363)

**Additional context**

- [backtrace](https://github.com/vim/vim/files/5793107/backtrace.txt)
- [valgrind log](https://github.com/vim/vim/files/5793108/valgrind.log)
- [asan log](https://github.com/vim/vim/files/5793106/asan.log)

**Comment by lacygoill** [comment]
It's a regression introduced between 8.2.1000 and 8.2.1500.  I'm going to bisect further.

**Comment by lacygoill** [comment]
Ah, I'm not sure anymore that it's caused by the list which mutates (`list<string>` → `list<list<string>>`).  It could be caused by the slice `[:]`.

**Comment by lacygoill** [comment]
> It's a regression introduced between 8.2.1000 and 8.2.1500.  I'm going to bisect further.

The crash started on [8.2.1465](https://github.com/vim/vim/releases/tag/v8.2.1465).

**Comment by lacygoill** [comment]
> The crash started on [8.2.1465](https://github.com/vim/vim/releases/tag/v8.2.1465).

Although, I'm not sure, because I had to adapt the syntax to make the code works on older Vim versions.

**Comment by brammool** [comment]
The map() call changes the list of strings to a list of list of strings.
This todo item applies:
- Make map() give an error if the resulting type of the first argument is
  wrong.  Only works if the type is known?  Is this slow (need to go over all
  items)?

**Comment by lacygoill** [comment]
Yes, I immediately thought about it, but since it's a crash, I thought it had to be reported.  I close because it's a known issue.

**Comment by brammool** [comment]
Still has to be fixed...
