### ISSUE TITLE
Syntax highlighting thinks $() is wrong

### ISSUE THREAD

**Issue by ghost** [vim/vim#7656]
**Describe the bug**
When storing the output of a shell command in a variable by using `$()`, Vim highlights the `$(` and `)` red. For example, to store the current hour in a variable, `$(date +"%H")` is used.

![figure1](https://user-images.githubusercontent.com/76850693/104145625-9ffadc80-537c-11eb-94ce-3a568418cdb7.png)
(This screenshot was not taken in `--clean`, however, the bug still occurs in `--clean`.)

**To reproduce**
1. Create a new file in Vim, making sure to specify it as a shell script. Example: `vim --clean example.sh`
2. Create a new while loop. For example,
```
while [  ]
do
done
```
3. Try to compare the output of a shell command to something else by wrapping a command in `$(` and `)`. For example, 
```
while [ $(date +"%H") -le 20 ]
do
done
```
4. Vim highlights the `$(` and `)` red

**Expected behavior**
The `$(` and `)` should not be highlighted red.

**Environment**
 - Vim version: 8.2.2327
 - OS: macOS 10.15.7 (19H15)
 - Terminal: Apple Terminal version 2.10 (433)

**Comment by k-takata** [comment]
Write `let g:is_posix = 1` in your .vimrc (See `:help ft-posix-syntax` for detail).

BTW, I think POSIX syntax should be enabled by default nowadays.
@cecamp What do you think?

**Comment by cecamp** [comment]
There are two main camps: posix posix posix! But the other camp is at least as loud: bash bash bash! So, I've chosen to encourage folks to choose what they want, and do so by having the old shell as default. (there's also the dash crew, but they don't appear to be as big as the other two). Me, I'm a kornshell user, which is rather closer to the posix camp. I'm fond of `integer var`.

**Comment by k-takata** [comment]
Hmm, most of the shells used nowadays (including bash, kornshell and dash) support posix.
Making posix as default doesn't confront bash folks.

**Comment by cecamp** [comment]
Yes, bash has a posix compliant mode. Most bash users would be upset to be limited to posix, however. So, bash != posix.
Kornshell is posix compliant with but slight differences.
I believe the only difference that I'm aware of between kornshell and posix is the <<< herestring (ksh has it, posix does not). There may be other differences that I'm not aware of.
