### ISSUE TITLE
Vim9: do we need "extendnew()"?

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7666]
In Vim9 script, since [8.2.2325](https://github.com/vim/vim/releases/tag/v8.2.2325), we can no longer use `extend()` to extend a dictionary of numbers into a dictionary of mixed values.
```vim
vim9
def Func()
    var d = extend({a: 0}, {b: 's'})
enddef
Func()
```
    E1013: Argument 2: type mismatch, expected dict<number> but got dict<string>

To fix this, we now need to create an intermediate variable:
```vim
vim9
def Func()
    var dd: dict<any> = {a: 0}
    var d = extend(dd, {b: 's'})
enddef
Func()
```
    ✔

Does that mean that we need a new `extendnew()` function, similar to the recent `mapnew()` function?

With this hypothetical `extendnew()`, the previous snippet could be simplified into:
```vim
vim9
def Func()
    var d = extendnew({a: 0}, {b: 's'})
enddef
Func()
```
---

Note that `copy()` and `deepcopy()` can't help here:
```vim
vim9
def Func()
    var d = deepcopy({a: 0})->extend({b: 's'})
enddef
Func()
```
    E1013: Argument 2: type mismatch, expected dict<number> but got dict<string>

**Comment by lacygoill** [comment]
> In Vim9 script, since 8.2.2325, we can no longer use extend() to extend a dictionary of numbers into a dictionary of mixed values.

Actually, I'm not sure the restriction started from this patch.  It might have started earlier.  This patch was for `map()`; not sure about `extend()`.

**Comment by lacygoill** [comment]
If we try to turn a `list<list<string>>` value into a `list<string>` value with `map()`, Vim complains:
```vim
vim9
[['a'], ['b']]->map((_, v) => v[0])
```
    E1012: Type mismatch; expected list<string> but got string

But if we try to turn a `list<list<string>>` value into a `list<string>` value with `flatten()`, Vim no longer complains:
```vim
vim9
[['a'], ['b']]->flatten()
```
It seems inconsistent.  Is this working as intended?  Shouldn't `flatten()` be subject to the same restrictions as `map()` (and `extend()`) and be disallowed to change the type of a value?  Do we need a `flattennew()` function, just like we needed the `mapnew()` and `extendnew()` functions?

**Comment by brammool** [comment]
Yes, flatten() is expected to change the type, so we should add flattennew() and disallow using flatten().
