### ISSUE TITLE
augroup end / END indent matching

### ISSUE THREAD

**Issue by nobe4** [vim/vim#767]
Hi,

Following a [stackoverflow discussion](http://vi.stackexchange.com/questions/7418/augroup-end-indentation) we noticed that the regex matching the `end`/`END` of an `augroup` actually only match the uppercase version during the indent increment: [indent/vim.vim file](https://github.com/vim/vim/blob/03413f44167c4b5cd0012def9bb331e2518c83cf/runtime/indent/vim.vim#L63)

Whereas for the decrement and on the syntax file, the `[eE][nN][dD]` regex is used: 
- [indent/vim.vim](https://github.com/vim/vim/blob/03413f44167c4b5cd0012def9bb331e2518c83cf/runtime/indent/vim.vim#L92)
- [syntax/vim.vim](https://github.com/vim/vim/blob/03413f44167c4b5cd0012def9bb331e2518c83cf/runtime/syntax/vim.vim#L203)

**Comment by brammool** [comment]
Victor Haffreingue wrote:

> Following a [stackoverflow discussion](http://vi.stackexchange.com/questions/7418/augroup-end-indentation) we noticed that the regex matching the `end`/`END` of an `augroup` actually only match the uppercase version during the indent increment: [indent/vim.vim file](https://github.com/vim/vim/blob/03413f44167c4b5cd0012def9bb331e2518c83cf/runtime/indent/vim.vim#L63)
> 
> Whereas for the decrement and on the syntax file, the `[eE][nN][dD]` regex is used: 
> - [indent/vim.vim](https://github.com/vim/vim/blob/03413f44167c4b5cd0012def9bb331e2518c83cf/runtime/indent/vim.vim#L92)
> - [syntax/vim.vim](https://github.com/vim/vim/blob/03413f44167c4b5cd0012def9bb331e2518c83cf/runtime/syntax/vim.vim#L203)

Although both "end" and "END" work, using "END" is recommended.

I'll change the indent script to also accept "end" (negatively) for
incrementing the indent.

## 

FATHER:    Did you kill all those guards?
LAUNCELOT: Yes ...  I'm very sorry ...
FATHER:    They cost fifty pounds each!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
fixed by aa3b15dbebf333282503d6031e2f9ba6ee4398ed
