### ISSUE TITLE
Pressing enter causes VIM to close and duplicate the line

### ISSUE THREAD

**Issue by n7z2** [vim/vim#7670]
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Describe the bug**
Launching VIM goes straight into insert mode and when I press the ENTER key VIM closes and the line I was on when vim is closed is duplicated.
(Issues related to the runtime files should be reported to their maintainer, check the file header.)

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run 'vim alone or on any text file'
2. Whilst in insert mode press Enter
3. Vim closes and the line the cursor was on is duplicated.

**Expected behavior**
A line break should be created and vim should stay open.

**Screenshots**
If applicable, copy/paste the text or add screenshots to help explain your problem.

**Environment (please complete the following information):**
 - Vim version 8.2
 - OS: Arch Linux 5.10.6 x86_64
 - Terminal: Termite

**Comment by lacygoill** [comment]
Can you reproduce with no config (`$ vim --clean`)?

**Comment by n7z2** [comment]
seems I do not have the issue when i run that command both alone and when opening a text file. 

My .vimrc file

`"Don't try to be vi compatible`
`set nocompatible
filetype off`

`""""""""""""""""""""""""""""""""""""""""""`
`"PLUGINS`
`""""""""""""""""""""""""""""""""""""""""""`

`call plug#begin('~/.vim/plugged')`
`Plug 'itchyny/lightline.vim'`
`Plug 'lilydjwg/colorizer'`
`Plug 'dylanaraps/wal.vim'`
`Plug 'junegunn/vim-emoji'`
`Plug 'pearofducks/ansible-vim'`
`Plug 'hashivim/vim-terraform'`
`call plug#end()`

`""""""""""""""""""""""""""""""""""""""""""`
`"KEY BINDINGS`
`""""""""""""""""""""""""""""""""""""""""""`
`" TODO: Pick a leader key`
`" let mapleader = ","`

`"""""""""""""""""""""""""`
`" Vifm`
`"""""""""""""""""""""""""`
`"map <Leader>vv :Vifm<CR>`
`"map <Leader>vs :VsplitVifm<CR>`
`"map <Leader>sp :SplitVifm<CR>`
`"map <Leader>dv :DiffVifm<CR>`
`"map <Leader>tv :TabVifm<CR>`

`" Turn on syntax highlighting`
`syntax on`

`" For plugins to load correctly`
`filetype plugin indent on`

`" Security`
`set modelines=0`

`" Show line numbers`
`" set number`

`" Show file stats`
`set ruler`

`" Blink cursor on error instead of beeping (grr)`
`" set visualbell`

`" Encoding`
`set encoding=utf-8`

`" Whitespace`
`set wrap`
`set textwidth=79`
`set formatoptions=tcqrn1`
`set tabstop=2`
`set shiftwidth=2`
`set softtabstop=2`
`set expandtab`
`set noshiftround`

`" Cursor motion`
`set scrolloff=3`
`set backspace=indent,eol,start`
`set matchpairs+=<:> " use % to jump between pairs`
`runtime! macros/matchit.vim`

`" Move up/down editor lines`
`nnoremap j gj`
`nnoremap k gk`

`" Allow hidden buffers`
`set hidden`

`" Rendering`
`set ttyfast`

`" Status bar`
`set laststatus=2`

`" Last line`
`set showmode`
`set showcmd`

`" Searching`
`nnoremap / /\v`
`vnoremap / /\v`
`set hlsearch`
`set incsearch`
`set ignorecase`
`set smartcase`
`set showmatch`
`map <leader><space> :let @/=''<cr> " clear search`

`" Remap help key.`
`inoremap <F1> <ESC>:set invfullscreen<CR>a`
`nnoremap <F1> :set invfullscreen<CR>`
`vnoremap <F1> :set invfullscreen<CR>`

" Textmate holdouts`

`" Formatting`
`map <leader>q gqip`

`" Visualize tabs and newlines`
`set listchars=tab:▸\ ,eol:¬`
`" Uncomment this to enable by default:`
`" set list " To enable by default`
`" Or use your leader key + l to toggle on/off`
`map <leader>l :set list!<CR> " Toggle tabs and EOL`

`" Color scheme (terminal)`
`set t_Co=256`
`set background=dark`
`let g:solarized_termcolors=256`
`let g:solarized_termtrans=1`
`" put https://raw.github.com/altercation/vim-colors-solarized/master/colors/solarized.vim`
`" in ~/.vim/colors/ and uncomment:`
 `colorscheme wal`

**Comment by lacygoill** [comment]
Then you need to bisect your config to find a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example).  For more info, see this [faq entry](https://github.com/chrisbra/vim_faq/blob/de424bd8e08bcf0e6b1e0563ee49514dfed926ae/vim_faq.txt#L1153-L1228).

**Comment by n7z2** [comment]
ok will do that

**Comment by n7z2** [comment]
I fixed the issue. somehow the .vifm folder in the plugin folder was causing this. I moved it into a backup folder .vim/backup/plugin/vifm.vim it fixed the issue. I think this happened after had that folder in the correct place then I added the plugin "vim/vifm.vim" line in my .vimrc file and installed it via :PlugInstall.
