### ISSUE TITLE
Vim9: readfile() return type is too generic

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7671]
**Describe the bug**

In Vim9 script, the return type of `readfile()` is `any`, which is too generic for Vim to catch some errors at compile time.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9
        def Func()
            writefile(['aaa', 'bbb', 'ccc'], '/tmp/file')
            var x = readfile('/tmp/file')
            map(x, (_, v) => 123)
        enddef
        Func()
    EOF
    )

No error is raised.

**Expected behavior**

`E1012` is raised because:

   - `readfile(...)` is a list of strings
   - `map()` tries to transform it into a list of numbers
   - `map()` is not allowed to do that since [8.2.2325](https://github.com/vim/vim/releases/tag/v8.2.2325)

**Environment**

 - Vim version: 8.2 Included patches: 1-2340
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(363)

**Additional context**

If we explicitly specify the type of `x`, then an error is correctly raised:
```vim
vim9
def Func()
    writefile(['aaa', 'bbb', 'ccc'], '/tmp/file')
    var x: list<string> = readfile('/tmp/file')
    map(x, (_, v) => 123)
enddef
Func()
```
    E1012: Type mismatch; expected list<string> but got list<number>

---

I think this patch fixes the issue:
```diff
diff --git a/src/evalfunc.c b/src/evalfunc.c
index 0e6d759c6..68cd6e830 100644
--- a/src/evalfunc.c
+++ b/src/evalfunc.c
@@ -1349,7 +1349,7 @@ static funcentry_T global_functions[] =
     {"readdirex",	1, 3, FEARG_1,	    NULL,
                        ret_list_dict_any,  f_readdirex},
     {"readfile",	1, 3, FEARG_1,	    NULL,
-			ret_any,	    f_readfile},
+			ret_list_string,    f_readfile},
     {"reduce",		2, 3, FEARG_1,	    NULL,
                        ret_any,	    f_reduce},
     {"reg_executing",	0, 0, 0,	    NULL,
diff --git a/src/testdir/test_vim9_builtin.vim b/src/testdir/test_vim9_builtin.vim
index 40cfdcbb1..49011dda3 100644
--- a/src/testdir/test_vim9_builtin.vim
+++ b/src/testdir/test_vim9_builtin.vim
@@ -623,6 +623,18 @@ def Test_readdir()
    eval expand('sautest')->readdirex((e) => e.name[0] !=# '.')
 enddef
 
+def Test_readfile()
+  var text = ['aaa', 'bbb', 'ccc']
+  writefile(text, 'Xreadfile')
+  var read: list<string> = readfile('Xreadfile')
+
+  var lines =<< trim END
+      var read: dict<string> = readfile('Xreadfile')
+  END
+  CheckDefAndScriptFailure(lines, 'E1012: Type mismatch; expected dict<string> but got list<string>', 1)
+  delete('Xreadfile')
+enddef
+
 def Test_remove_return_type()
   var l = remove({one: [1, 2], two: [3, 4]}, 'one')
   var res = 0
```

**Comment by lacygoill** [comment]
I have another similar snippet which doesn't raise any error while maybe it should:
```vim
vim9
def Func()
    helpg grail
    var items = getqflist({items: 0}).items
    map(items, (_, v) => v.valid)
enddef
Func()
```
    no error

I *think* an error should be raised because:

   - `getqflist({items: 0}).items` is a list of dictionaries
   - `map()` tries to transform it into a list of (boolean) numbers
   - `map()` is not allowed to do that since [8.2.2325](https://github.com/vim/vim/releases/tag/v8.2.2325)

If we explicitly specify the type of `items`, then an error is correctly raised:
```vim
vim9
def Func()
    helpg grail
    var items: list<dict<any>> = getqflist({items: 0}).items
    map(items, (_, v) => v.valid)
enddef
Func()
```
    E1012: Type mismatch; expected list<dict<any>> but got list<number>

I guess that – without an explicit type – Vim infers the type `any`.  Is it working as intended because it is not possible for Vim to infer the right type, or is it a bug because it should infer the type `list<dict<any>>` without our help?

**Comment by jamessan** [comment]
> In Vim9 script, the return type of `readfile()` is `any`,

`readfile()` either returns a list of strings or list of bytes depending on its second argument.

**Comment by lacygoill** [comment]
Ah, I missed that part.  So, either we keep `ret_any` and this issue can be closed, or we try to be more specific with something like `ret_list_string_or_byte`.

**Comment by brammool** [comment]
When using binary mode the result is still a list of strings, only the behavior is slightly different.
The real problem is that when {type} is "B" then a blob is returned.
I think it was a mistake to use readfile() also for reading a blob.  Let's deprecate that and add readblob().
Then in Vim9 readfile() can always return a list<string>
