### ISSUE TITLE
Build failure with --disable-gui option

### ISSUE THREAD

**Issue by ProgrammerPolymathic** [vim/vim#7680]
Compiling Vim with the --disable-gui option fails on term.c with the error `"gui" undeclared`.

**To Reproduce**
```
git clone https://github.com/vim/vim
cd vim
./configure --disable-gui
make
```

**Relevant Output**
```
gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/term.o term.c
term.c: In function 'out_flush':
term.c:2553:5: error: 'gui' undeclared (first use in this function)
 2553 |    (gui.in_use && !gui.dying && !gui.starting)
      |     ^~~
term.c:2553:5: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [Makefile:3512: objects/term.o] Error 1
make[1]: Leaving directory '/home/besitzer/Dokumente/Software/vim/src'
make: *** [Makefile:29: first] Error 2
```

**Environment**
Vim git commit 845b72854de90de13879598df53f1c388e52e1ba
OpenSUSE Tumbleweed (2021-01-07 snapshot)

**Additional context**
Appears to have been caused by the modifications to `out_flush` in commit 681fc3fa782e99fe69ed2c83c3e29109d2d61e1a (namely not checking whether GUI is enabled).

**Comment by brammool** [comment]
Fixed by 8.2.2347
