### ISSUE TITLE
Vim9: cannot put linebreak before "->" in command which takes a list of commands as argument

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7681]
**Describe the bug**

In Vim9 script, we cannot put a linebreak before `->` in a command which takes a list of commands as argument.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9
        def Func()
            windo echo 'edcba'
                ->split('\zs')
                ->reverse()
                ->join('')
        enddef
        Func()
    EOF
    )

`E1050` is raised at compile time:

    E1050: Colon required before a range: ->split('\zs')

**Expected behavior**

No error is raised.  `abcde` is echo'ed.

**Environment**

 - Vim version: 8.2 Included patches: 1-2344
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(363)

**Additional context**

At the script level, the exact same code doesn't raise any error:
```vim
vim9
windo echo 'edcba'
    ->split('\zs')
    ->reverse()
    ->join('')
```
    abcde

---

For other commands taking a list of commands such as `:g` and `:au`, we cannot put a linebreak before `->` even at the script level:
```vim
vim9
au CursorHold * echo 'edcba'
    ->split('\zs')
    ->reverse()
    ->join('')
```
    E1050: Colon required before a range: ->split('\zs')
    E1050: Colon required before a range: ->reverse()
    E1050: Colon required before a range: ->join('')

This is inconsistent with the `:*do` commands.

In addition to `|`, it would be convenient to be able to put a linebreak before `->` in any command taking a list of commands as argument, such as: `:au`, `:com`, `:g`, ...

**Comment by brammool** [comment]
At script level it also fails inside a block that's not executed:
```vim
vim9script
if 0
  windo echo 'edbcdf'
	->split('c')
endif
```

I'm not sure we can make this work without a lot of tricks.  We would need to parse the expression, which means we need to know it is an expression, which means we need to understand the type of argument of the command...

**Comment by lacygoill** [comment]
> I'm not sure we can make this work without a lot of tricks. We would need to parse the expression, which means we need to know it is an expression, which means we need to understand the type of argument of the command...

Ah, that's clearly too complex; at best it could work for a simple `:echo` command, but not for any command.  It's best to be consistent; if it can't work for any command, there's no reason it works for a simple `:echo`.  So, I close the issue.

But I don't understand why we would need to parse the expression.  Before running a command such as `:windo`, I thought we could simply inspect the next line; if it starts with `->`, then we would have concatenated it.  Just like we do right now if the next line starts with a bar.  I've encountered a few locations where it would have been handy.

**Comment by brammool** [comment]
> > I'm not sure we can make this work without a lot of tricks. We would
> > need to parse the expression, which means we need to know it is an
> > expression, which means we need to understand the type of argument
> > of the command...
> 
> Ah, that's clearly too complex; at best it could work for a simple
> `:echo` command, but not for any command.  It's best to be consistent;
> if it can't work for any command, there's no reason it works for a
> simple `:echo`.  So, I close the issue.
> 
> But I don't understand why we would need to parse the expression.
> Before running a command such as `:windo`, I thought we could simply
> inspect the next line; if it starts with `->`, then we would have
> concatenated it.  Just like we do right now if the next line starts
> with a bar.  I've encountered a few locations where it would have been
> handy.

Using "->" is just one case, the line could start with any operator,
such as "+" or "/".

-- 
hundred-and-one symptoms of being an internet addict:
150. You find yourself counting emoticons to get to sleep.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
