### ISSUE TITLE
Vim9: "silent!" cannot suppress ":throw" executed from "TerminalWinOpen" when ":term" run from try/catch

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7682]
**Describe the bug**

In Vim9 script, `silent!` cannot suppress `:throw` when it's executed from a `TerminalWinOpen` autocmd, which is triggered by a `:term` command inside a try/catch.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9
        au TerminalWinOpen * sil! Throw()
        def Throw()
            throw 'error'
        enddef
        try
            term
        catch /E123/
        endtry
    EOF
    )

`E605` is raised:

    E605: Exception not caught: error

**Expected behavior**

No error is raised, because `Throw()` is suppressed by `silent!`.

**Environment**

 - Vim version: 8.2 Included patches: 1-2352
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(363)

**Additional context**

The exact same code doesn't raise any error when the try/catch is run from the legacy context:
```vim
au TerminalWinOpen * sil! Throw()
def Throw()
    throw 'error'
enddef
try
    term
catch /E123/
endtry
```

**Comment by brammool** [comment]
:silent! suppresses an error message, it does not suppress an exception.
I'm not quite sure why it works in legacy script, the Implementation is very complex.
Perhaps the documentation should explain this better, but it doesn't look like a bug.

**Comment by lacygoill** [comment]
Understood.  Note that, even in Vim script legacy, the interactions between `silent!` and `throw` are sometimes a bit weird.  For example:
```vim
fu Throw()
    try
        throw 'error'
    endtry
endfu
sil! call Throw()
try
    call Unknown()
catch
endtry
```
    E117: Unknown function: Unknown

Here, `E117` should not be raised, because it should have been caught by the try/catch.  And, IIUC, `silent!` should not have suppressed `:throw`.
