### ISSUE TITLE
Arguments for cursor() function are inconsistent

### ISSUE THREAD

**Issue by tacahiroy** [vim/vim#7686]
**Describe the bug**

This behaviour was introduced with https://github.com/vim/vim/commit/6f02b00bb (Vim 8.2.2324).

The `cursor()` function doesn't allow string value for `{lnum}` and `{col}`, but string can be passed if the argument is a list.
For example,

```vim
" E474: Invalid argument
:cal cursor('1', '1')

" this is ok even if `{lnum}` and `{col}` are string
:cal cursor(['1', '1'])
```

**To Reproduce**

1. Run `vim --clean`
1. Execute `:call cursor(['1', '1'])`
1. The cursor position is changed to `1:1`
2. This is inconsistent, because `:call cursor('1', '1')` returns `E474: Invalid argument`.

**Expected behavior**
Although I'm not sure which is the correct behaviour, if string value is invalid for arguments for `cursor` function, it should be invalid sting values are passed as a List.

**Screenshots**

**Environment (please complete the following information):**
- VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 16 2021 01:05:13)
- Included patches: 1-2353
- OS: [Ubuntu 20.04 on WSL2]
- Terminal: Windows Terminal 1.5.3242.0

**Additional context**

**Comment by brammool** [comment]
I don't think patch 8.2.2324 changed this.  It was already like this before, and because of backwards compatibility can't be changed.
You an use Vim9 script, which is much stricter about this.

**Comment by tacahiroy** [comment]
No, it wasn't. String values are allowed with older versions of Vim 8.2.

I have also confirmed this on Windows.
String value is allowed for `{lnum}` and `{col}` in 8.2.2320 (no 2323 build available in vim/vim-win32-installer, so tried with this version), but it's not allowed with the version 8.2.2327 and 8.2.2352.
So this indicates some `cursor()` function specification was changed with some commit between 8.2.2320 and 8.2.2327; also means they are NOT backwards compatible especially this behaviour.

![7686](https://user-images.githubusercontent.com/76614/104817029-0773c900-5862-11eb-8a69-75f5a5ca49d1.gif)

**Comment by vim-ml** [comment]
Hi,

This has now been fixed by 8.2.2363.

- Yegappan

**Comment by Shane-XB-Qian** [comment]
https://github.com/vim/vim/pull/7648

**Comment by Shane-XB-Qian** [comment]
looks you were misunderstanding each other.. ;-) 
For this case, user/legacy-script should be not like more ‘strict’ type check.....
