### ISSUE TITLE
Compiling vim under Visual C++ 2008 Express Edition fails due to missing Win32.mak file

### ISSUE THREAD

**Issue by benfranklin79** [vim/vim#769]
I'm currently trying to compile my own version of vim from sources with python using the following command (after having installed visual c++)

`"C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\nmake.exe" -f Make_mvc.mak PYTHON3=C:\Python34 DYNAMIC_PYTHON3=yes PYTHON3_VER=34'`

I get the following error:

`Make_mvc.mak(254) : fatal error U1052: file 'Win32.mak' not found`

On inspecting Make_mvc.mak I see that it contains the following code:

```
!ifdef SDK_INCLUDE_DIR
!include $(SDK_INCLUDE_DIR)\Win32.mak
!else
!include <Win32.mak>
!endif
```

However, the notes towards the top of the Make_mvc.mak file say the following:

```
#   For MSVC 11 you need to specify where the Win32.mak file is, e.g.:
#      SDK_INCLUDE_DIR="C:\Program Files\Microsoft SDKs\Windows\v7.1\Include"
```

This seems to suggest that Win32.mak does not need specifying for the version of visual C++ I'm using. This leaves me wondering: was Win32.mak originally included in the repo and is it now missing?

**Comment by brammool** [comment]
Ben Franklin wrote:

> I'm currently trying to compile my own version of vim from sources with python using the following command (after having installed visual c++)
> 
> `"C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\nmake.exe" -f Make_mvc.mak PYTHON3=C:\Python34 DYNAMIC_PYTHON3=yes PYTHON3_VER=34'`
> 
> I get the following error:
> 
> `Make_mvc.mak(254) : fatal error U1052: file 'Win32.mak' not found`
> 
> On inspecting Make_mvc.mak I see that it contains the following code:
> 
> ```
> !ifdef SDK_INCLUDE_DIR
> !include $(SDK_INCLUDE_DIR)\Win32.mak
> !else
> !include <Win32.mak>
> !endif
> ```
> 
> However, the notes towards the top of the Make_mvc.mak file say the following:
> 
> ```
> #     For MSVC 11 you need to specify where the Win32.mak file is, e.g.:
> #        SDK_INCLUDE_DIR="C:\Program Files\Microsoft SDKs\Windows\v7.1\Include"
> ```
> 
> This seems to suggest that Win32.mak does not need specifying for the version of visual C++ I'm using. This leaves me wondering: was Win32.mak originally included in the repo and is it now missing?

You need to execute a command to set the path properly.  e.g.:
    call "%VS90COMNTOOLS%vsvars32.bat"
You can use src/msvc2008.bat

## 

Futility Factor: No experiment is ever a complete failure - it can always
serve as a negative example.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by benfranklin79** [comment]
I forgot to mention in my previous message that I did try running that command but it ran through with no errors but did not help with being able to run the nmake executable. That's why I specified the full path to nmake.

**Comment by benfranklin79** [comment]
I'm figuring that vsvars32.bat should setup some default paths for nmake to look in to find Win32.mak. A recursive grep of the whole of the folder `C:\Program Files (x86)\Microsoft Visual Studio 9.0` reveals no presence of Win32.mak at all.

**Comment by k-takata** [comment]
Normally vsvars32.bat also sets INCLUDE environment variable, and nmake uses %INCLUDE% to find win32.mak.

**Comment by benfranklin79** [comment]
Well `C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include` definitely doesn't contain Win32.mak. I'm on windows 10 and I'm wondering if that might be part of the problem.

**Comment by k-takata** [comment]
Windows specific headers (e.g. windows.h) and win32.mak are part of Windows SDK (or formerly Microsoft Platform SDK) and they are installed in a different directory.
Normally it is `C:\Program Files\Microsoft SDKs\Windows\vX.X` or `C:\Program Files (x86)\Microsoft SDKs\Windows\vX.X` but it might different with versions. (IIRC, VC2008 bundles Windows SDK 6.0.)

**Comment by benfranklin79** [comment]
Regarding your last comment I found the following link;

http://stackoverflow.com/questions/3213787/visual-studio-2008-installer-omits-sdk-6-0a

which says the SDK is in an odd place. This means that you have to specify the variable SDK_INCLUDE_DIR to make it work. I tested it and got the following error:

```
Cannot run Visual C to determine its version. Make sure cl.exe is in your PATH.
This can usually be done by running "vcvarsall.bat", located in the bin directory where Visual Studio was installed.
Make_mvc.mak(394) : fatal error U1050: Make aborted.
```

This means I've solved my problem and now have a completely new problem to solve. I will submit a change to the installation notes before closing this off, since those notes don't indicate you have to specify the SDK path for this specific version of VC. 

Thanks for help.

**Comment by benfranklin79** [comment]
Close this since instructions for compiling have been updated as part of:

https://github.com/vim/vim/commit/02cfac85b4e4b038bb2df6962699fa93a42c7eb1
