### ISSUE TITLE
Vim9: cannot capture output of Ex command with "execute()" inside "<C-\>e" mapping

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7699]
**Describe the bug**

In Vim9 script, we cannot capture the output of an Ex command with `execute()` inside a `<C-\>e`  mapping.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9
        cno <F3> <c-\>e Func()<cr>
        setline(1, ['abc', 'ddd', 'aef', 'ggg', 'ahi'])
        var output: string
        def g:Func(): string
            output = execute('g/^a/#', '')
            return ''
        enddef
        feedkeys(":\<F3>", 'xt')
        echo output
    EOF
    )

An empty string is echo'ed.

**Expected behavior**

This is echo'ed:

    1 abc
    3 aef
    5 ahi

**Environment**

 - Vim version: 8.2 Included patches: 1-2371
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(363)

**Additional context**

The exact same code works as expected if `Func()` is rewritten as a legacy function:
```vim
vim9
cno <F3> <c-\>e Func()<cr>
setline(1, ['abc', 'ddd', 'aef', 'ggg', 'ahi'])
var output: string
fu g:Func()
    let s:output = execute('g/^a/#', '')
    return ''
endfu
feedkeys(":\<F3>", 'xt')
echo output
```
    1 abc
    3 aef
    5 ahi

**Comment by brammool** [comment]
In Vim9 script g/pat/# does nothing, because # starts a comment.  You can use g/pat/number.
