### ISSUE TITLE
Add keepend to pythonString in syntax/python.vim

### ISSUE THREAD

**Issue by ibizaman** [vim/vim#770]
Is there a particular reason to not have a `keepend` on [`pythonString`](https://github.com/vim/vim/blob/master/runtime/syntax/python.vim#L101) and [`pythonRawString`](https://github.com/vim/vim/blob/master/runtime/syntax/python.vim#L107)?

If a `keepend` is added, it makes it a bit easier to use embedded syntax in python strings. See for example [this SO answer](http://stackoverflow.com/questions/29791199/highlight-sql-inside-python-string-literals/36754447#36754447) in which the two mentioned syntax regions are copied with a `keepend`.

**Comment by chrisbra** [comment]
please contact the syntax script maintainer and discuss the issue with him. Thanks.
