### ISSUE TITLE
Vim9: crash when dividing by zero in :def function

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7704]
**Describe the bug**

In Vim9 script, dividing a number by zero in a `:def` function makes Vim crash.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9
        def Func()
            eval 1 / 0
        enddef
        defcompile
    EOF
    )

Vim crashes.

**Expected behavior**

Vim doesn't crash.

**Environment**

 - Vim version: 8.2 Included patches: 1-2374
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(363)

**Additional context**

- [backtrace](https://github.com/vim/vim/files/5832461/backtrace.txt)
- [valgrind log](https://github.com/vim/vim/files/5832462/valgrind.log)
- [asan log](https://github.com/vim/vim/files/5832460/asan.log)

**Comment by lacygoill** [comment]
BTW, I *think* that in Vim script legacy, `1 / 0` could be used to get the highest number the running Vim binary could handle.  Not sure whether `1 / 0` should do the same in Vim9 script, or just raise an error...

**Comment by LemonBoy** [comment]
> Not sure whether 1 / 0 should do the same in Vim9 script, or just raise an error...

Returning `VARNUM_MIN` or `VARNUM_MAX` doesn't make any sense, the code in `num_divide` implies this value is supposed to be NaN-ish but it's not. A (quiet) NaN poisons the whole chain of calculation it's in while an arbitrarily large integer is simply treated as a regular number, leaving the user wondering where the bug is.

> 1 / 0 could be used to get the highest number the running Vim binary could handle

If that's the only use case for this I'd simply add a `v:maxintvalue` and call it a day, there's no reason for Vim9 script not to throw an error here.

**Comment by lacygoill** [comment]
I agree, it seems a bit weird to not raise an error here, considering that Vim9 is stricter in other areas.  I think it would make sense to raise a runtime error.  I found this while refactoring an [indent plugin](https://vimways.org/2019/indentation-without-dents/), where the author used `1 / 0` to represent infinity in a number assignment:

    function! s:SubmatchCount(lnum, pattern, ...)
            let endcol = a:0 >= 1 ? a:1 : 1 / 0
            ...
    endfunction

**Comment by lacygoill** [comment]
[8.2.2378](https://github.com/vim/vim/releases/tag/v8.2.2378) has fixed the issue; now `1 / 0` correctly raises an error.

However, something is inconsistent:
```vim
vim9
def Func()
    var x = 1 / 0
    echo x
enddef
Func()
```
    E1154: Divide by zero
```vim
vim9
var x = invalid
echo x
```
    E121: Undefined variable: invalid
    E121: Undefined variable: x
```vim
vim9
var x = 1 / 0
echo x
```
    E1154: Divide by zero
    9223372036854775807

Notice that in the last snippet, and only in that one, `x` is assigned a big number.
I think `x` should not be assigned anything, and `echo x` should raise `E121`.

**Comment by brammool** [comment]
> [8.2.2378](https://github.com/vim/vim/releases/tag/v8.2.2378) has fixed the issue; now `1 / 0` correctly raises an error.
> 
> However, something is inconsistent:
> ```vim
> vim9
> def Func()
>     var x = 1 / 0
>     echo x
> enddef
> Func()
> ```
>     E1154: Divide by zero
> ```vim
> vim9
> var x = invalid
> echo x
> ```
>     E121: Undefined variable: invalid
>     E121: Undefined variable: x
> ```vim
> vim9
> var x = 1 / 0
> echo x
> ```
>     E1154: Divide by zero
>     9223372036854775807
> 
> Notice that in the last snippet, and only in that one, `x` is assigned
> a big number.
> I think `x` should not be assigned anything, and `echo x` should raise `E121`.

Yes, continuing after the error is not right.  It requires passing an
extra argument.

-- 
hundred-and-one symptoms of being an internet addict:
194. Your business cards contain your e-mail and home page address.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
