### ISSUE TITLE
Vim9: wrong error when "silent!" suppresses previous error in autoloaded function

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7705]
**Describe the bug**

In Vim9 script, a wrong error might be raised at runtime, if `:silent!` has suppressed a previous error at compile time when invoking an autoloaded function.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9
        def Func()
            var view: dict<number> = winsaveview()
            sil! script#func()
            winrestview(view)
        enddef
        Func()
    EOF
    )

`E474` is raised:

    E474: Invalid argument

**Expected behavior**

No error is raised, because `view` is a dictionary of numbers obtained via `winsaveview()`, which is a valid argument for `winrestview()`.

**Environment**

 - Vim version: 8.2 Included patches: 1-2374
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(363)

**Additional context**

The issue disappears if `sil! script#func()` is removed:
```vim
vim9
def Func()
    var view: dict<number> = winsaveview()
    winrestview(view)
enddef
```
---

Here, `silent!` suppresses the error which is raised when calling an autoloaded function which can't be found.

But the issue would persist even if the autoloaded function could be found, provided that an error is raised at compile time when it's sourced (e.g. a type mismatch error).  `silent!` would suppress the latter error at compile time, and a wrong error would then be raised at runtime.  Example:
```vim
vim9
set rtp^=/tmp/some
mkdir('/tmp/some/autoload', 'p')
var lines: list<string> =<< trim END
    def script#func()
        var x: dict<any> = getwininfo()
    enddef
END
writefile(lines, '/tmp/some/autoload/script.vim')

def Func()
    var view: dict<number> = winsaveview()
    script#func()
    winrestview(view)
enddef
Func()
```
    E1012: Type mismatch; expected dict<any> but got list<dict<any>>

This snippet raises `E1012`, which is expected.

Now, prefix `script#func()` with `silent!` to suppress that error:
```vim
vim9
set rtp^=/tmp/some
mkdir('/tmp/some/autoload', 'p')
var lines: list<string> =<< trim END
    def script#func()
        var x: dict<any> = getwininfo()
    enddef
END
writefile(lines, '/tmp/some/autoload/script.vim')

def Func()
    var view: dict<number> = winsaveview()
    sil! script#func()
    winrestview(view)
enddef
Func()
```
    E474: Invalid argument

A new error is raised at runtime.  This one is unexpected.

**Comment by brammool** [comment]
Also fixed by 8.2.2386
