### ISSUE TITLE
Vim9: crash when interrupting job callback which encounters error

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7708]
**Describe the bug**

In Vim9 script, interrupting a job callback which encounters an error might make Vim crash.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9
        def Func(...l: any)
            try
                echohl ModeMsg
            catch
            endtry
            timer_start(0, () => win_execute(id, 'invalid'))
        enddef
        var id = popup_create('', {})
        job_start(['/bin/sh', '-c', 'locate /'], {out_cb: () => Func()})
    EOF
    )

`E492` is raised:

    E492: Not an editor command: invalid

This is expected.

Now, keep pressing `C-c` to interrupt the errors.  *Sometimes*, Vim ends up crashing.  If it doesn't crash, you might need to re-run the shell command.

**Expected behavior**

Vim doesn't crash.

**Environment**

 - Vim version: 8.2 Included patches: 1-2374
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(363)

**Additional context**

If the code is re-written in Vim script legacy, pressing `C-c` doesn't seem to make Vim crash:

    vim -Nu NONE -S <(cat <<'EOF'
        fu Func(...)
            try
                echohl ModeMsg
            catch
            endtry
            call timer_start(0, {-> win_execute(s:id, 'invalid')})
        endfu
        let s:id = popup_create('', {})
        call job_start(['/bin/sh', '-c', 'locate /'], {'out_cb': {-> Func()}})
    EOF
    )

---

- [backtrace](https://github.com/vim/vim/files/5837044/backtrace.txt)
- [valgrind log](https://github.com/vim/vim/files/5837045/valgrind.log)
- [asan log](https://github.com/vim/vim/files/5837043/asan.log)

**Comment by brammool** [comment]
Tricky to reproduce.  Or write a test for when it gets fixed.
Could you try to make it crash reliably?

**Comment by lacygoill** [comment]
I've just noticed that it was hard, if not impossible, to make it crash in xterm, unless `TERM` is changed.  If I run Vim inside tmux inside xterm, it seems much easier to cause a crash.  I guess it means that some terminal options are involved.  I'll start from there, and see what I can get.

**Comment by lacygoill** [comment]
> I guess it means that some terminal options are involved.

That won't help for a test, but it seems that clearing `t_TI` (`--cmd 'set t_TI='`) makes it easier to crash Vim by pressing `C-c` interactively.  I'll keeping looking for something which can be automated.

**Comment by lacygoill** [comment]
This crashes almost consistently in xterm on my machine; but it still needs a manual interrupt:

    vim -Nu NONE --cmd 'set t_TI=' -S <(cat <<'EOF'
        vim9
        def Func(...l: any)
            try
                echohl ModeMsg
            catch
            endtry
            timer_start(0, () => win_execute(id, 'invalid'))
        enddef
        var id = popup_create('', {})
        job_start('locate ' .. $HOME, {out_cb: Func})
    EOF
    )

**Comment by dpelle** [comment]
@brammool  wrote:

> Tricky to reproduce. Or write a test for when it gets fixed.
> Could you try to make it crash reliably?

On my system, it's easy to reproduce after running the command 
in bug description and pressing CTRL-C once or sometimes
multiple times till it crashes.  I get the same stack trace as @lacygoill .

I don't have time now, but I can try later to automate it with a test
if that's possible.

`excp` is `NULL` at `ex_eval.c:670` which causes the segfault:
```
 667     void
 668 catch_exception(except_T *excp)                                            
 669 {
!670     excp->caught = caught_stack;
 ```
I use vim-8.2.2377 (huge, without gui) in xfce4-terminal on xubuntu-18.04.5.

**Comment by brammool** [comment]
> This crashes almost consistently in xterm on my machine; but it still needs a manual interrupt:
> 
>     vim -Nu NONE --cmd 'set t_TI=' -S <(cat <<'EOF'
>         vim9
>         def Func(...l: any)
>             try
>                 echohl ModeMsg
>             catch
>             endtry
>             timer_start(0, () => win_execute(id, 'invalid'))
>         enddef
>         var id = popup_create('', {})
>         job_start('locate ' .. $HOME, {out_cb: Func})
>     EOF
>     )

Thanks, now I can reproduce it, although not reliably.

Looks like the problem is that when a timer is called nearly all state
concerning exceptions is saved and restored, but not the need_rethrow
flag.  Let's see if saving and restoring need_rethrow helps.

-- 
hundred-and-one symptoms of being an internet addict:
192. Your boss asks you to "go fer" coffee and you come up with 235 FTP sites.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
