### ISSUE TITLE
ctrl alt cursor keys inserts odd characters

### ISSUE THREAD

**Issue by paulkerry1** [vim/vim#7712]
![xterm](https://user-images.githubusercontent.com/23099638/105212917-f4a11300-5b45-11eb-9cd3-78b84f691683.png)
**Describe the bug**
When using vim-8.2.2347-1 in insert mode under XFCE in Arch Linux, pressing ctrl-alt-{left/right/up/down cursor} to change desktops inserts '"\<t_\<fd\>c\>"' into the editor

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run vim
2. Edit a new file
3. Type "i"
4. press for instance "ctrl-alt-right" to move to the desktop to the right
5. "<t_\<fd\>c>" is inserted into the new file

**Expected behavior**
Nothing should be inserted into the new file when pressing ctrl-alt-{left/right/up/down cursor}

**Screenshots**
see attached.

**Environment (please complete the following information):**
 - vim-8.2.2347
 - OS: Arch Linux
 - Terminal: regular xterm within XFCE

**Additional context**
vim 8.2.1989-3 and earlier releases do not do this.

Regards
Paul.

**Comment by brammool** [comment]
I cannot reproduce this, because my window manager intercepts those keys.
If you do see Vim getting an escape sequence, perhaps XFCE does something strange?
I would expect the window manager to either consume those keys or pass them on unmodified.

**Comment by paulkerry1** [comment]
Many thanks for the quick reply.
I've git cloned the latest vim 8.2.2377 and having built it locally it doesn't exhibit the same escape sequence problem.
I'll push this onto the Arch Linux bugs as it might be a build issue.
Regards
Paul.
