### ISSUE TITLE
Vim9: crash when suppressing "Pattern not found error"

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7717]
**Describe the bug**

In Vim9 script, suppressing a "Pattern not found" error might make Vim crash.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9

        def Func(b: bool)
            Eval(b)
            Crash()
        enddef

        def Eval(b: bool)
            eval !b
        enddef

        def Crash()
            sil! :/not found/d _
            sil! :/not found/put _
        enddef

        Func(true)
    EOF
    )

Vim crashes.

**Expected behavior**

Vim doesn't crash.

**Environment**

 - Vim version: 8.2 Included patches: 1-2380
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(363)

**Additional context**

- [backtrace](https://github.com/vim/vim/files/5846299/backtrace.txt)
- [valgrind log](https://github.com/vim/vim/files/5846300/valgrind.log)
- [asan log](https://github.com/vim/vim/files/5846298/asan.log)

**Comment by brammool** [comment]
Using valgrind to check for the error, it also happens without the Eval() function.
