### ISSUE TITLE
Side effect of 'splitright' for horizontal splits

### ISSUE THREAD

**Issue by gerw** [vim/vim#7721]
**Describe the bug**
If I have a vim session with three horizontally split windows in which the middle window is focused, the effect of 'q' depends on the setting of 'splitright': If set, the cursor ends up in the top window, otherwise in the bottom one.

**To Reproduce**
`vim --clean +":sp | :sp | :winc j | q"`
(Cursor in bottom window)

`vim --clean +":set splitright | :sp | :sp | :winc j | q"`
(Cursor in top window)

**Expected behavior**
I expect no influence of `splitright`, since we do not use vertical splits.

(For `splitbelow` similar things happen. However, this make sense such that ":sp | :q" becomes a no-op.)

**Environment (please complete the following information):**
````
VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 15 2020 06:40:31)
Included patches: 1-2269
````
Ubuntu 20.04
xterm

**Comment by brammool** [comment]
I cannot reproduce it, when 'splitright' is set the cursor still goes to the bottom window.

**Comment by gerw** [comment]
I just compiled the latest version of vim. With this version I am also not able to reproduce the bug. So it seems to be fixed already. Sorry for the noise.
