### ISSUE TITLE
Regression in indentation of if-endif blocks in vim filetype

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#7723]
Has something changed recently in vim filetype's indentation file? If-endif blocks that used to be indented correctly now do not.

Detailed steps to reproduce the behavior:
1. Run `vim --clean` (or `gvim --clean`, etc.)
2. Insert:

```vim
if 1
  let x = [
        \ ]
endif
```
3. Indent (type `gg=G`).
4. The `endif` is aligned with `let` instead of being aligned with `if`.

 - Vim version: 8.2.2375
 - OS: macOS 11.1
 - Terminal: Apple Terminal.app

I have not done a bisect, but Vim 8.2.1719 indents correctly.

**Comment by lacygoill** [comment]
It started from a recent update of the [Vim indent plugin](https://github.com/vim/vim/commit/82be4849eed0b8fbee45bc8da99b685ec89af59a#diff-48cf28a80003168943d20d7d40a2454ff6980019c84a3e4ac9cb7e819da22876).

Not sure it's the correct solution, but this patch should fix the issue:
```diff
diff --git a/runtime/indent/vim.vim b/runtime/indent/vim.vim
index 3e502c9ad..d45e2b45f 100644
--- a/runtime/indent/vim.vim
+++ b/runtime/indent/vim.vim
@@ -154,6 +154,7 @@ function GetVimIndentIntern()
   " A line ending in "{"/"[} is most likely the start of a dict/list literal,
   " indent the next line more.  Not for a continuation line.
   if prev_text =~ '[{[]\s*$' && !found_cont
+        \ && "\n" .. getline(1, 10)->join("\n") =~# '\n\s*vim9\%[script]\>'
     let ind = ind + shiftwidth()
   endif
 
```

**Comment by lacygoill** [comment]
Actually, evaluating `getline(1, 10)` is ok for the filetype plugin, which is sourced once in a while, but not for an indent function, which is potentially invoked much more frequently.  So the evaluation should probably be moved outside the function, saved in a script-local variable boolean flag, and inspected from the indent function.

**Comment by lacygoill** [comment]
So, this might be better:
```diff
diff --git a/runtime/indent/vim.vim b/runtime/indent/vim.vim
index 3e502c9ad..2bf9c53c7 100644
--- a/runtime/indent/vim.vim
+++ b/runtime/indent/vim.vim
@@ -14,6 +14,7 @@ setlocal indentkeys+==end,=},=else,=cat,=finall,=END,0\\,0=\"\\\
 setlocal indentkeys-=0#
 
 let b:undo_indent = "setl indentkeys< indentexpr<"
+let s:is_vim9 = "\n" .. getline(1, 10)->join("\n") =~# '\n\s*vim9\%[script]\>'
 
 " Only define the function once.
 if exists("*GetVimIndent")
@@ -153,7 +154,7 @@ function GetVimIndentIntern()
 
   " A line ending in "{"/"[} is most likely the start of a dict/list literal,
   " indent the next line more.  Not for a continuation line.
-  if prev_text =~ '[{[]\s*$' && !found_cont
+  if prev_text =~ '[{[]\s*$' && !found_cont && s:is_vim9
     let ind = ind + shiftwidth()
   endif
 
```

**Comment by lacygoill** [comment]
Still not good.  The variable should be local to the buffer, not to the script:
```diff
diff --git a/runtime/indent/vim.vim b/runtime/indent/vim.vim
index 3e502c9ad..5f5853749 100644
--- a/runtime/indent/vim.vim
+++ b/runtime/indent/vim.vim
@@ -14,6 +14,7 @@ setlocal indentkeys+==end,=},=else,=cat,=finall,=END,0\\,0=\"\\\
 setlocal indentkeys-=0#
 
 let b:undo_indent = "setl indentkeys< indentexpr<"
+let b:is_vim9 = "\n" .. getline(1, 10)->join("\n") =~# '\n\s*vim9\%[script]\>'
 
 " Only define the function once.
 if exists("*GetVimIndent")
@@ -153,7 +154,7 @@ function GetVimIndentIntern()
 
   " A line ending in "{"/"[} is most likely the start of a dict/list literal,
   " indent the next line more.  Not for a continuation line.
-  if prev_text =~ '[{[]\s*$' && !found_cont
+  if prev_text =~ '[{[]\s*$' && !found_cont && b:is_vim9
     let ind = ind + shiftwidth()
   endif
 
```

**Comment by lacygoill** [comment]
If the solution is roughly OK, then IMO, the `b:is_vim9` variable should be set from the Vim filetype plugin, because it could be useful for much more than just the indent function.

**Comment by chrisbra** [comment]
can't you use a `search()` call? Because, what happens if you start editing a function and add the `vim9script` later at the top (after starting editing)?

**Comment by lacygoill** [comment]
I copied the fix which was implemented in the Vim filetype plugin, but I guess we could instead invoke `search()` and limit the search to the first 10 lines, leveraging its optional 3rd argument.  But there might be legacy comments above the `:vim9` statement, so the pattern should take that into account.

**Comment by lacygoill** [comment]
> But there might be legacy comments above the :vim9 statement, so the pattern should take that into account.

Sorry, this is another corner case, which I think the current fix doesn't even take into account:

https://github.com/vim/vim/blob/5e6a7aa2b26077775906eb8411952dc6259694de/runtime/ftplugin/vim.vim#L51

It only checks that there is `:vim9` in one of the first 10 lines; it doesn't check that there are only empty lines or legacy comments.

So, what I wrote is irrelevant.

**Comment by lacygoill** [comment]
> it doesn't check that there are only empty lines or legacy comments.

And I don't think it needs to, because if we have a script with a `:vim9` statement with anything else than an empty line or a legacy comment above, then it's probably broken.

**Comment by brammool** [comment]
> It started from a recent update of the [Vim indent plugin](https://github.com/vim/vim/commit/82be4849eed0b8fbee45bc8da99b685ec89af59a#diff-48cf28a80003168943d20d7d40a2454ff6980019c84a3e4ac9cb7e819da22876).
> 
> Not sure it's the correct solution, but this patch should fix the issue:
> ```diff
> diff --git a/runtime/indent/vim.vim b/runtime/indent/vim.vim
> index 3e502c9ad..d45e2b45f 100644
> --- a/runtime/indent/vim.vim
> +++ b/runtime/indent/vim.vim
> @@ -154,6 +154,7 @@ function GetVimIndentIntern()
>    " A line ending in "{"/"[} is most likely the start of a dict/list literal,
>    " indent the next line more.  Not for a continuation line.
>    if prev_text =~ '[{[]\s*$' && !found_cont
> +        \ && "\n" .. getline(1, 10)->join("\n") =~# '\n\s*vim9\%[script]\>'
>      let ind = ind + shiftwidth()
>    endif
>  
> ```

The problem actually does not depend on whether this is Vim9 script or
not.  It also fails in legacy script.

The problem is that there is a check for "]" at the start of the
previous line, it should be at the end of the previous line.  That
matters if there is line continuation with a backslash.  I'll fix it.

-- 
hundred-and-one symptoms of being an internet addict:
200. You really believe in the concept of a "paperless" office.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
Fix will be in the next runtime file update.
