### ISSUE TITLE
Vim9: cannot break dictionary after [{

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7726]
**Describe the bug**

In Vim9 script, we cannot break a dictionary after `[{`.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9
        [{
            a: 0}]->string()->setline(1)
    EOF
    )

`E723` is raised:

    E723: Missing end of Dictionary '}':

**Expected behavior**

No error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-2389
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(363)

**Additional context**

If we add an extra linebreak between `[` and `{`, then no error is raised:
```vim
vim9
[
{
    a: 0}]->string()->setline(1)
```
    [{'a': 0}]

This seems inconsistent.

---

Workaround: use `:eval`.
```vim
vim9
eval [{
    a: 0}]->string()->setline(1)
```
    [{'a': 0}]

---

If we remove the list, and just keep the dictionary, another confusing error is raised:
```vim
vim9
{
    a: 0}->string()->setline(1)
```
    E121: Undefined variable: a:
    line    4:
    E171: Missing :endif

There is no `:if` anywhere, so why does Vim complain about a missing `:endif`?

In a `:def` function, yet another confusing error is raised:
```vim
vim9
def Func()
    {
        a: 0}->string()->setline(1)
enddef
defcompile
```
    E1075: Namespace not supported: a: 0}->string()->setline(1)

I suspect Vim somehow conflates a dictionary with a `{}` block.
Assuming that's correct, could Vim check whether there's a following `->` before parsing `{}` as a block?

**Comment by brammool** [comment]
The "{" in a line by itself starts a block.  You need to put the first key in that line to see the difference.

**Comment by lacygoill** [comment]
> In Vim9 script, we cannot break a dictionary after [{.

Fixed by [8.2.2393](https://github.com/vim/vim/commit/4bce26bb70144633713e7e8f149ba99cac511336).

---

> The "{" in a line by itself starts a block.

Yes, and it leads to error messages which I think users will have a hard time to understand.

> You need to put the first key in that line to see the difference.

This means that `{` is ambiguous; it can start a dictionary or a block.  In the past, we've changed some syntaxes to remove ambiguity, like `[b:c]` (variable `c` in namespace `b:` vs from variable `b` to variable `c`), and `->` (method call vs lambda).  I was thinking we might want to change the `{}` block syntax (e.g. `{{...}}`), especially since it seems rarely necessary (at least much less useful than the dictionary syntax).  But it seems they have the same ambiguity in javascript, so maybe it makes sense to keep it unchanged, I don't know.

**Comment by lacygoill** [comment]
> I was thinking we might want to change the {} block syntax (e.g. {{...}})

I've just realized we had the same issue in a lambda.  The rhs after `=>` can be a dictionary expression or a series of Ex commands inside curly brackets.  To remove the ambiguity, we now require the dictionary to be surrounded by parentheses:

    ( arguments ) => { Ex commands }

    ( arguments ) => ({ dictionary })
                     ^              ^

That's what they seem to do in javascript.

Maybe we could do something similar when a dictionary is written at the start of a line without `:eval`:

    { block }

    ({ dictionary })
    ^              ^

This way, there wouldn't be any ambiguity anymore.  A curly bracket at the start of a line would *always* start a block, and `({` would *always* start a dictionary.

**Comment by lacygoill** [comment]
And it would be entirely consistent with what we already do in a lambda, making the syntax easier to remember.

**Comment by brammool** [comment]
> > I was thinking we might want to change the {} block syntax (e.g. {{...}})
> 
> I've just realized we had the same issue in a lambda.  The rhs after `=>` can be a dictionary expression or a series of Ex commands inside curly brackets.  To remove the ambiguity, we now require the dictionary to be surrounded by parentheses:
> 
>     ( arguments ) => { Ex commands }
> 
>     ( arguments ) => ({ dictionary })
>                      ^              ^
> 
> That's what they seem to do in javascript.
> 
> Maybe we could do something similar when a dictionary is written at the start of a line without `:eval`:
> 
>     { block }
> 
>     ({ dictionary })
>     ^              ^
> 
> This way, there wouldn't be any ambiguity anymore.  A curly bracket at
> the start of a line would *always* start a block, and `({` would
> *always* start a dictionary.

Right, that was the solution we found before.

Using something else for a command block: we could use something like
":block" and ":endblock", but I have not see that in any popular
language.  It also is not easy to recognize.

Using a dictionary at the start of a command should be uncommon enough
that the solution with parenthesis seems OK.

-- 
hundred-and-one symptoms of being an internet addict:
213. Your kids start referring to you as "that guy in front of the monitor."

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
