### ISSUE TITLE
Vim9: "min()" and "max()" unexpectedly inferred with type "any" in list value

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7728]
**Describe the bug**

In Vim9 script, `min()` and `max()` are sometimes inferred with the type `any` in a list value, which can raise an unexpected error in an assignment.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9
        def Func()
            var l: list<number> = winnr() == 1
                ?     [1, min([2, 3])]
                :     [4, 5]
        enddef
        defcompile
    EOF
    )

`E1012` is raised:

    E1012: Type mismatch; expected list<number> but got list<any>

**Expected behavior**

No error is raised, because the output of `min()` is a number; therefore, `[1, min([2, 3])]` is a list of numbers which matches the type `list<number>` specified in the assignment.

**Environment**

 - Vim version: 8.2 Included patches: 1-2389
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(363)

**Additional context**

At the script level, the exact same code doesn't raise any error:
```vim
vim9
var l: list<number> = winnr() == 1
    ?     [1, min([2, 3])]
    :     [4, 5]
echo l->typename()
```
    list<number>

If the `?:` operator is removed, no error is raised:
```vim
vim9
def Func()
    var l: list<number> = [1, min([2, 3])]
    echo l->typename()
enddef
Func()
```
    list<number>

If the `?:` operator is preserved, but the condition is replaced with `true`, again, no error is raised:
```vim
vim9
def Func()
    var l: list<number> = true
        ?     [1, min([2, 3])]
        :     [4, 5]
    echo l->typename()
enddef
Func()
```
    list<number>

If `true` is obtained via another function, the error is raised again:
```vim
vim9
def Func()
    var l: list<number> = True()
        ?     [1, min([2, 3])]
        :     [4, 5]
    echo l->typename()
enddef
def True(): bool
    return true
enddef
defcompile
```
    E1012: Type mismatch; expected list<number> but got list<any>

---

Could the issue somehow be linked to the fact that `min()` and `max()` have a too generic return type?

https://github.com/vim/vim/blob/9b6344613eecfcf77c510d7b63fcc4b7b51aefbc/src/evalfunc.c#L1221-L1222
https://github.com/vim/vim/blob/9b6344613eecfcf77c510d7b63fcc4b7b51aefbc/src/evalfunc.c#L1231-L1232

In Vim9, can `min()` and `max()` return something else than a number?

This seems to suggest that they expect a list or dictionary of numbers, and nothing else:
```vim
vim9
echo min(['aaa', 'bbb'])
```
    E1030: Using a String as a Number: "aaa"
    E1030: Using a String as a Number: "bbb"
```vim
vim9
echo min({a: 'aaa', b: 'bbb'})
```
    E1030: Using a String as a Number: "aaa"
    E1030: Using a String as a Number: "bbb"

**Comment by brammool** [comment]
Interestingly, swapping the expressions after ? and : also makes the error go away.
