### ISSUE TITLE
Test_fold_relative_move() fails all the times from patch 8.2.2385

### ISSUE THREAD

**Issue by dpelle** [vim/vim#7731]
**Describe the bug**

Vim test `Test_fold_relative_move()` fails all the time
on my xubuntu-18.04.5 machine using the latest vim-8.2.2394.
I did a git bisection and bug started to appear with this commit:
```
commit e71996bd0865659bde5450f466bc3e53e83431b2 (tag: v8.2.2385)
Author: Bram Moolenaar <Bram@vim.org>
Date:   Thu Jan 21 17:03:07 2021 +0100

    patch 8.2.2385: "gj" and "gk" do not work correctly when inside a fold
    
    Problem:    "gj" and "gk" do not work correctly when inside a fold.
    Solution:   Move check for folding. (closes #7724, closes #4095)
```

Running the test with valgrind shows use of uninitialized memory:
```
==16012== Memcheck, a memory error detector
==16012== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==16012== Using Valgrind-3.17.0.GIT and LibVEX; rerun with -h for copyright info
==16012== Command: ../vim -f -u unix.vim -U NONE --noplugin --not-a-term -S runtest.vim test_fold.vim --cmd au\ SwapExists\ *\ let\ v:swapchoice\ =\ "e"
==16012== Parent PID: 16011
==16012== 
==16012== Conditional jump or move depends on uninitialised value(s)
==16012==    at 0x5C2B23: f_term_dumpwrite (terminal.c:4758)
==16012==    by 0x4544D5: call_internal_func (evalfunc.c:2047)
==16012==    by 0x5DEDB7: call_func (userfunc.c:2527)
==16012==    by 0x5DE6E8: get_func_tv (userfunc.c:906)
==16012==    by 0x5E5031: ex_call (userfunc.c:4482)
==16012==    by 0x470BE4: do_one_cmd (ex_docmd.c:2588)
==16012==    by 0x470BE4: do_cmdline (ex_docmd.c:1003)
==16012==    by 0x5E034A: call_user_func (userfunc.c:1889)
==16012==    by 0x5E034A: call_user_func_check (userfunc.c:2043)
==16012==    by 0x5DECA4: call_func (userfunc.c:2509)
==16012==    by 0x5DE6E8: get_func_tv (userfunc.c:906)
==16012==    by 0x5E5031: ex_call (userfunc.c:4482)
==16012==    by 0x470BE4: do_one_cmd (ex_docmd.c:2588)
==16012==    by 0x470BE4: do_cmdline (ex_docmd.c:1003)
==16012==    by 0x5E034A: call_user_func (userfunc.c:1889)
==16012==    by 0x5E034A: call_user_func_check (userfunc.c:2043)
==16012==    by 0x5DECA4: call_func (userfunc.c:2509)
==16012==    by 0x5DE6E8: get_func_tv (userfunc.c:906)
==16012==    by 0x5E5031: ex_call (userfunc.c:4482)
==16012==    by 0x470BE4: do_one_cmd (ex_docmd.c:2588)
==16012==    by 0x470BE4: do_cmdline (ex_docmd.c:1003)
==16012==    by 0x450F8B: ex_execute (eval.c:6128)
==16012==    by 0x470BE4: do_one_cmd (ex_docmd.c:2588)
==16012==    by 0x470BE4: do_cmdline (ex_docmd.c:1003)
==16012==    by 0x5E034A: call_user_func (userfunc.c:1889)
==16012==    by 0x5E034A: call_user_func_check (userfunc.c:2043)
==16012==    by 0x5DECA4: call_func (userfunc.c:2509)
==16012==    by 0x5DE6E8: get_func_tv (userfunc.c:906)
==16012==    by 0x5E5031: ex_call (userfunc.c:4482)
==16012==    by 0x470BE4: do_one_cmd (ex_docmd.c:2588)
==16012==    by 0x470BE4: do_cmdline (ex_docmd.c:1003)
==16012==    by 0x577AC8: do_source (scriptfile.c:1401)
==16012==    by 0x577198: cmd_source (scriptfile.c:971)
==16012==    by 0x470BE4: do_one_cmd (ex_docmd.c:2588)
==16012==    by 0x470BE4: do_cmdline (ex_docmd.c:1003)
==16012==    by 0x63BD0C: exe_commands (main.c:3056)
==16012==    by 0x63BD0C: vim_main2 (main.c:760)
==16012==    by 0x63ACF4: main (main.c:412)
==16012==  Uninitialised value was created by a stack allocation
==16012==    at 0x5C277A: f_term_dumpwrite (terminal.c:4658)
```
I'll try to find later what exactly is uninitialized.

**To Reproduce**
```
$ make test_fold
rm -f test_fold.res test.log messages
VIMRUNTIME=../../runtime  ../vim -f  -u unix.vim -U NONE --noplugin --not-a-term -S runtest.vim test_fold.vim --cmd 'au SwapExists * let v:swapchoice = "e"' > /dev/null


From test_fold.vim:
Executed Test_address_fold()                       in   0.000660 seconds
Executed Test_combining_folds_indent()             in   0.000391 seconds
Executed Test_combining_folds_marker()             in   0.000371 seconds
Executed Test_fold_create_delete()                 in   0.000243 seconds
Executed Test_fold_create_delete_create()          in   0.000225 seconds
Executed Test_fold_create_marker_in_C()            in   0.001731 seconds
Executed Test_fold_delete_first_line()             in   0.000395 seconds
Executed Test_fold_delete_with_marker()            in   0.000559 seconds
Executed Test_fold_delete_with_marker_and_whichwrap() in   0.000838 seconds
Executed Test_fold_error()                         in   0.000712 seconds
Executed Test_fold_expr()                          in   0.000730 seconds
Executed Test_fold_expr_error()                    in   0.000498 seconds
Executed Test_fold_indent()                        in   0.000532 seconds
Executed Test_fold_last_line_with_pagedown()       in   0.002351 seconds
Executed Test_fold_manual()                        in   0.000459 seconds
Executed Test_fold_marker()                        in   0.000484 seconds
Executed Test_fold_move()                          in   0.000443 seconds
Executed Test_fold_relative_move()                 in   0.000387 seconds
Executed Test_fold_syntax()                        in   0.000614 seconds
Executed Test_folddoopen_folddoclosed()            in   0.000574 seconds
Executed Test_foldopen_exception()                 in   0.000250 seconds
Executed Test_folds_marker_in_comment()            in   0.000388 seconds
Executed Test_folds_marker_in_comment2()           in   0.000382 seconds
Executed Test_folds_with_rnu()                     in   0.066821 seconds
Executed Test_foldtext_recursive()                 in   0.001113 seconds
Executed Test_indent_fold()                        in   0.000798 seconds
Executed Test_indent_fold2()                       in   0.000767 seconds
Executed Test_indent_fold_with_read()              in   0.003878 seconds
Executed Test_manual_fold_with_filter()            in   0.026270 seconds
Executed Test_move_folds_around_indent()           in   0.003427 seconds
Executed Test_move_folds_around_manual()           in   0.005859 seconds
Executed Test_move_no_folds()                      in   0.000846 seconds
Executed Test_undo_fold_deletion()                 in   0.001577 seconds
Executed Test_update_folds_expr_read()             in   0.004849 seconds
Executed 34 tests                        in   0.142166 seconds
1 FAILED:
Found errors in Test_fold_relative_move():
command line..script /home/pel/sb/vim/src/testdir/runtest.vim[468]..function RunTheTest[39]..Test_fold_relative_move line 25: Expected 3 but got 2
command line..script /home/pel/sb/vim/src/testdir/runtest.vim[468]..function RunTheTest[39]..Test_fold_relative_move line 30: Expected 2 but got 1
Makefile:63: recipe for target 'test_fold' failed
make: *** [test_fold] Error 1
```

**Environment**

 - Vim version Vim >= 8.2.2385 (huge)
 - OS: xubuntu 18.04.5
 - Terminal: xfce4-terminal-0.8.7.4

**Comment by brammool** [comment]
Dominique wrote:

> Vim test `Test_fold_relative_move()` fails all the time
> on my xubuntu-18.04.5 machine using the latest vim-8.2.2394.

Strangely it doesn't fail for me, and also do not see a problem with
valgrind.

> I did a git bisection and bug started to appear with this commit:
> ```
> commit e71996bd0865659bde5450f466bc3e53e83431b2 (tag: v8.2.2385)
> Author: Bram Moolenaar <Bram@vim.org>
> Date:   Thu Jan 21 17:03:07 2021 +0100
> 
>     patch 8.2.2385: "gj" and "gk" do not work correctly when inside a fold
>     
>     Problem:    "gj" and "gk" do not work correctly when inside a fold.
>     Solution:   Move check for folding. (closes #7724, closes #4095)
> ```
> 
> Running the test with valgrind shows use of uninitialized memory:
> ```
> ==16012== Memcheck, a memory error detector
> ==16012== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
> ==16012== Using Valgrind-3.17.0.GIT and LibVEX; rerun with -h for copyright info
> ==16012== Command: ../vim -f -u unix.vim -U NONE --noplugin --not-a-term -S runtest.vim test_fold.vim --cmd au\ SwapExists\ *\ let\ v:swapchoice\ =\ "e"
> ==16012== Parent PID: 16011
> ==16012== 
> ==16012== Conditional jump or move depends on uninitialised value(s)
> ==16012==    at 0x5C2B23: f_term_dumpwrite (terminal.c:4758)
> ==16012==    by 0x4544D5: call_internal_func (evalfunc.c:2047)
[...]
> I'll try to find later what exactly is uninitialized.

I have seen this warning before, it might be unrelated.  But it's good
to try and figure this out anyway.


-- 
hundred-and-one symptoms of being an internet addict:
212. Your Internet group window has more icons than your Accessories window.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dpelle** [comment]
I now recall a similar valgrind error in https://github.com/vim/vim/pull/7187
which was fixed at the time.  But there is still another bug with similar
symptoms.

**Comment by dpelle** [comment]
I found that the test fails when the terminal size wider or equal than 100 rows.
I created PR https://github.com/vim/vim/pull/7739 to fix it.

Regarding valgrind error, I will look at it later but it's unrelated tot he failing test.

**Comment by brammool** [comment]
Dominique wrote:

> I found that the test fails when the terminal size wider or equal than
> 100 rows.  I created PR https://github.com/vim/vim/pull/7739 to fix
> it.

Ah, that explains it.  Thanks for making a fix.

> Regarding valgrind error, I will look at it later but it's unrelated
> tot he failing test.

Yes, I have seen this before and could not pinpoint the cause then.

-- 
How do I set the laser printer to stun? 

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
