### ISSUE TITLE
xxd: Plain continuous style doesn't work for bits.

### ISSUE THREAD

**Issue by kenorb** [vim/vim#774]
Not sure if it's expected behaviour or not, but logically `-ps` (plain style) should apply for all formats?

E.g. this works:

```
 $ xxd -ps file.bin
b0726891ed7cbf3f
```

However when using `-b`, it doesn't work as expected (because offsets are printed):

```
$ xxd -ps -b file.bin
00000000: 10110000 01110010 01101000 10010001 11101101 01111100  .rh..|
00000006: 10111111 00111111                                      .?
```

I understand it may be expected behaviour, but I believe this should be corrected, so `-p`/`-ps` is consistent. It can be useful for parsing purposes.

**Comment by lacygoill** [comment]
> Not sure if it's expected behaviour or not

I think it's working as intended:

   > The command line switches -r, -p, -i do not work with this mode.

Source: https://github.com/vim/vim/blob/227c58a486d2459e7bf6ed2c917ede7e324e3570/runtime/doc/xxd.man#L35-L41

---

   > It can be useful for parsing purposes.

Maybe you could use `sed(1)` to remove the undesired information from the output of `xxd(1)`.  Something like this:

    xxd -ps -b /bin/true | sed 's/^[^ ]* //; s/  .*//; s/ //g'
                         ^-----------------------------------^

**Comment by chrisbra** [comment]
so closing.
