### ISSUE TITLE
cannot open popup terminal before VimEnter

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7742]
**Describe the bug**

We cannot open a popup terminal until after `VimEnter` has been fired.

**To Reproduce**

Run this shell command:

    vim -Nu NORC -c 'call term_start(&shell, #{hidden: 1})->popup_create({})'

`E994` is raised:

    E994: Not allowed in a popup window

**Expected behavior**

No error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-2406
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(363)

**Additional context**

The issue comes from these lines in the netrw plugin:

https://github.com/vim/vim/blob/c05fe07529f10fc32a2086cb44a708520c8d14ce/runtime/plugin/netrwPlugin.vim#L156-L157

`:windo` and `:wincmd` try to temporarily change the currently focused window, which is disallowed while a popup terminal is active.

In practice, it causes this kind of issues: https://github.com/junegunn/fzf.vim/issues/1231.

---

This patch should fix the issue:
```diff
diff --git a/runtime/plugin/netrwPlugin.vim b/runtime/plugin/netrwPlugin.vim
index 217a7795c..6083af0ce 100644
--- a/runtime/plugin/netrwPlugin.vim
+++ b/runtime/plugin/netrwPlugin.vim
@@ -151,10 +151,8 @@ endfun
 "             has already been called.
 fun! s:VimEnter(dirname)
 "  call Dfunc("s:VimEnter(dirname<".a:dirname.">) expand(%)<".expand("%").">")
-  let curwin       = winnr()
   let s:vimentered = 1
-  windo call s:LocalBrowse(expand("%:p"))
-  exe curwin."wincmd w"
+  call range(1, winnr('$'))->map({_, v -> win_execute(win_getid(v), 'call expand("%:p")->s:LocalBrowse()')})
 "  call Dret("s:VimEnter")
 endfun
 
```
It uses `win_execute()` which has fewer side-effects.

cc @cecamp

**Comment by lacygoill** [comment]
> We cannot open a popup terminal until after VimEnter has been fired.

Actually, we can, but it still raises `E994`.

**Comment by MaxGyver83** [comment]
Can anybody validate @lacygoill's patch?

**Comment by michaelorr** [comment]
I was able to apply the patch from @lacygoill and it does indeed resolve the "cannot open a popup prior to VimEnter" issue. 

With the patch, I am able to run:
`vim -c "Ag foo"` directly which results in a popup window opening correctly as expected, whereas without the patch this will throw an exception:
```
Error detected while processing VimEnter Autocommands for "*"..function <SNR>50_VimEnter:
line    4:
E994: Not allowed in a popup window
Press ENTER or type command to continue
```
and I have to resort to hacks like:
`vim -c "autocmd VimEnter * call timer_start(0, {->execute('Ag foo')})"` to get it to work.

**Comment by MaxGyver83** [comment]
@michaelorr : Thanks for testing!

Meanwhile I have built vim from source with this patch applied and I can confirm that it works as expected (tested with `vim -c "RgRaw netrw"`).

@lacygoill : Would you mind creating a pull request with your patch?

**Comment by k-takata** [comment]
I assigned to @cecamp.

**Comment by lacygoill** [comment]
Fixed in the last update of the runtime files: https://github.com/vim/vim/commit/89a9c159f23fb7b3e24e6d09068adfc24a73afcb
