### ISSUE TITLE
:set guioptions+=v ignored in GTK3 GVIM

### ISSUE THREAD

**Issue by inkarkat** [vim/vim#7746]
**Describe the bug**

The GTK3 GVIM does not honor the request to use a vertical button layout for dialogs (`:set guioptions+=v`), and always renders the buttons horizontally, which (when there are many and/or long choices) can lead to ugliness (in a horizontal multi-monitor setup, the dialog spans multiple monitors) or even inaccessibility (the dialog gets truncated and some buttons are now visible).

This affects the default _vim-gtk3-2:8.1.2269-1ubuntu5_ package that ships with Ubuntu 20.04 LTS, as well as a self-compiled (`--enable-gui=gtk3`) latest version 8.2.2406.

The GTK2 variant (_vim-gnome_ package, latest version compiled with `--enable-gui=gtk2`) is showing the vertical button layout just fine.

**To Reproduce**

1. Run `gvim --clean --cmd 'set guioptions+=v' -c 'call confirm("Test", "one\ntwo\nthree")'`

**Expected behavior**
I have plugins that present a lot of long options and therefore basically only are usable with a vertical button layout; the only fallback would be to use text-based dialogs via `:set go+=c`.

`:help confirm()` mentions:

> confirm()		tries to put the buttons in one horizontal line.  If they		don't fit, a vertical layout is used anyway.  For some systems		the horizontal layout is always used.

Even if (I'm guessing) GTK3 doesn't allow a vertical layout simply by setting a flag, a custom dialog (basically a modal window with a label, icon, and some buttons) surely could be implemented for it.

**Screenshots**

![gvim-gtk3-not-vertical](https://user-images.githubusercontent.com/181261/105834344-a3bc6f00-5fca-11eb-9704-0aa3265e40f4.png)

![gvim-gtk2-vertical](https://user-images.githubusercontent.com/181261/105834404-b767d580-5fca-11eb-8695-19198e1e8f6b.png)

**Environment (please complete the following information):**
 - Vim version 8.1.2269, 8.2.2406
 - OS: Ubuntu 16.04, 20.04
 - GTK3 GUI

**Comment by matveyt** [comment]
This proves to be tougher than it seems at first sight. GtkDialog does not support that kind of option and forcefully packs its buttons into hbox (aka action-area). In Gtk2 Vim does the trick by replacing action-area with a new vbox. This is in `src/gui_gtk.c`:

```c
    // Check 'v' flag in 'guioptions': vertical button placement.
    if (vim_strchr(p_go, GO_VERTICAL) != NULL)
    {
# if GTK_CHECK_VERSION(3,0,0)
    // Add GTK+ 3 code if necessary.
    // N.B. GTK+ 3 doesn't allow you to access vbox and action_area via
    // the C API.
# else
    GtkWidget   *vbutton_box;

    vbutton_box = gtk_vbutton_box_new();
    gtk_widget_show(vbutton_box);
    gtk_box_pack_end(GTK_BOX(GTK_DIALOG(dialog)->vbox),
                         vbutton_box, TRUE, FALSE, 0);
    // Overrule the "action_area" value, hopefully this works...
    GTK_DIALOG(dialog)->action_area = vbutton_box;
# endif
    }
```

However, Gtk3 closes this backdoor by hiding action_area inside a private structure (pimpl-alike). So the "vertical" option was never implemented in Gtk3 and it seems there's no easy way to implement it.

**Comment by chrisbra** [comment]
So we should then at least add a short comment at options.txt mentioning that GTK3 does not allow this I think.

**Comment by brammool** [comment]
I'll add a note.  So we close this as "infeasible".
