### ISSUE TITLE
Compiling vim under Visual C++ 2008 Express Edition fails to process blowfish.c file

### ISSUE THREAD

**Issue by benfranklin79** [vim/vim#775]
I'm trying to get the following script to work

```
SET TOOLS_DIR="C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\Tools"
call %TOOLS_DIR%\vsvars32.bat

SET MAKE_DIR="C:\dev\vim\src"
"C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\nmake.exe" -f %MAKE_DIR%\Make_mvc.mak PYTHON3=C:\Python34 DYNAMIC_PYTHON3=yes PYTHON3_VER=34 SDK_INCLUDE_DIR="C:\Program Files\Microsoft SDKs\Windows\v6.0A\Include"
```

Here "C:\dev\vim" is my local checkout of the vim repo.
I'm getting the following error:

```
Microsoft (R) Program Maintenance Utility Version 9.00.30729.01
Copyright (C) Microsoft Corporation.  All rights reserved.

Python3 requested (version 34) - root dir is "C:\Python34"
Python3 DLL will be loaded dynamically

        if not exist .\ObjCHi386/nul  mkdir .\ObjCHi386
NMAKE : fatal error U1073: don't know how to make 'blowfish.c'
Stop.

```

In the Make_mvc.mak script I note the following:

line 742 is where the python related message is generated
line 1023 is where the mkdir message is generated
line 1124 is the line I think is most likely responsible for the error but I'm not sure

Any help would be appreciated.
Note that the commit I'm working off is 763b684373bf5954445d8d8d99da1e39a4fc5105 and OS is windows 10

**Comment by k-takata** [comment]
You must run `nmake` in the `src` directory.

**Comment by benfranklin79** [comment]
Ok thanks, so I updated the script to CD to the src directory and now I've got a different error:

```
Python3 requested (version 34) - root dir is "C:\Python34"
Python3 DLL will be loaded dynamically

        if not exist .\ObjCHi386/nul  mkdir .\ObjCHi386
creating .\ObjCHi386\pathdef.c
        cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE        -DWINVER=0x0501 -D_WIN32_WINNT=0x0501  /Fo.\ObjCHi386/ /Ox /GL -DNDEBUG  /Zl /MT -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3  -DDYNAMIC_PYTHON3_DLL=\"python34.dll\" -DFEAT_HUGE /Fd.\ObjCHi386/ /Zi .\ObjCHi386\pathdef.c
pathdef.c
        rc /nologo /l 0x409 /Fo.\ObjCHi386/vim.res /r -DWIN32 -D_WIN32 -DWINVER=0x0500  -DNDEBUG vim.rc
fatal error RC1106: invalid option: -ologo
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft SDKs\Windows\v6.0A\bin\rc.EXE"' : return code '0x1'
```

**Comment by k-takata** [comment]
Maybe same as this problem: https://groups.google.com/d/msg/vim_dev/_yK-qgxVm1E/-aRrG0X0DQAJ
But I'm not sure why this happens on your environment, because you use VC2008 (not VC2005).
You may want to try one of the following:
- Edit `Make_mvc.mak` and remove `/nologo` from the line `$(RC) /nologo /l 0x409 ...`.
- Use newer rc.exe. (E.g. Use VC2010SP1 or later.)

**Comment by brammool** [comment]
I'm using VC2008 without problems, this is unlikely a bug in Vim, rather a problem with the user setup.  Closing...

**Comment by benfranklin79** [comment]
Fair enough. I think I will give a more recent compiler a go. I was only using 2008 since it was recommended in the PC install notes. Just in case anyone is still interested, after following the option of removing the /nologo option, like k-takata suggested, I got the following error which I've been unable to figure out:

```
Microsoft (R) Program Maintenance Utility Version 9.00.30729.01
Copyright (C) Microsoft Corporation.  All rights reserved.

Python3 requested (version 34) - root dir is "C:\Python34"
Python3 DLL will be loaded dynamically

        cd GvimExt
        "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\nmake.exe" -f Makefile

Microsoft (R) Program Maintenance Utility Version 9.00.30729.01
Copyright (C) Microsoft Corporation.  All rights reserved.

        Rc /nologo /r -DWIN32 -D_WIN32 -DWINVER=0x0500   gvimext.rc
fatal error RC1106: invalid option: -ologo
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft SDKs\Windows\v6.0A\bin\Rc.EXE"' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\nmake.exe"' : return code '0x2'
Stop.
```
