### ISSUE TITLE
laststatus=2 breaks au InsertEnter * hi ModeMsg

### ISSUE THREAD

**Issue by paulswanson** [vim/vim#7751]
Hello,

Given the following .vimrc in Vim 8.2:

    set nocompatible
    set laststatus=2
    au InsertEnter * hi ModeMsg ctermfg=yellow

Upon entering insert mode for the first time, the ModeMsg foreground colour is unchanged; subsequent entries to insert mode see the ModeMsg foreground colour change to yellow as expected.

If the "set laststatus=2" line is removed or changed another valid value, the ModeMsg highlighting is changed on both initial and subsequent entries to insert mode, as expected.

This seems like a bug to me. Can anyone else confirm this behaviour?

Thanks in advance.

Paul Swanson

**Comment by brammool** [comment]
Paul Swanson wrote:

> Given the following .vimrc in Vim 8.2:
> 
>     set nocompatible
>     set laststatus=2
>     au InsertEnter * hi ModeMsg ctermfg=yellow
> 
> Upon entering insert mode for the first time, the ModeMsg foreground colour is unchanged; subsequent entries to insert mode see the ModeMsg foreground colour change to yellow as expected.
> 
> If the "set laststatus=2" line is removed or changed another valid value, the ModeMsg highlighting is changed on both initial and subsequent entries to insert mode, as expected.
> 
> This seems like a bug to me. Can anyone else confirm this behaviour?

It's more prominent if the highlight is reset in InsertLeave:

	set laststatus=2
	au InsertEnter * hi ModeMsg ctermfg=yellow
	au InsertLeave * hi ModeMsg ctermfg=black

You can fix it by adding a redraw:

	au InsertEnter * hi ModeMsg ctermfg=yellow | redraw
	au InsertLeave * hi ModeMsg ctermfg=black | redraw

But I can change the code that takes care of it.

-- 
hundred-and-one symptoms of being an internet addict:
253. You wait for a slow loading web page before going to the toilet.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
