### ISSUE TITLE
vim.org's plugin update service is down

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#7752]
When uploading new script in vim.org, an error is encountered:

    XXXX is empty, are you sure you specified the correct path?

But the file is not empty.

![图片](https://user-images.githubusercontent.com/3035071/106124261-db2b4700-6195-11eb-9dd8-dcbe6158665b.png)

**Comment by skywind3000** [comment]
Now, it becomes like this:

    POST has been used more than 500 times within 5 hours. Assuming bot attack. Retry again later. If you continue having trouble write to the mailinglist.

![图片](https://user-images.githubusercontent.com/3035071/106149094-d033df00-61b4-11eb-8ff4-42a3b4089739.png)

**Comment by brammool** [comment]
This indicates that something is trying to send a lot of requests to the website.  As mentioned in the error, please try again after five hours.

**Comment by brammool** [comment]
I found that one IP address was sending lots of requests.  I have blocked it, now it should work again.

**Comment by skywind3000** [comment]
the first error happen again:

    XXXX is empty, are you sure you specified the correct path?

![图片](https://user-images.githubusercontent.com/3035071/106182643-18192d00-61da-11eb-9fff-72649b48c7c9.png)
