### ISSUE TITLE
term_dumpload("tempdump.log") shows only last 60-something lines to the dump

### ISSUE THREAD

**Issue by poetaman** [vim/vim#7754]
term_dumpload("tempdump.log") shows only last 60-something lines of dump. I produced dump while either one of terminal-normal or terminal mode is active.

```
Terminal emulator: Terminal.app of/on macOS
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 24 2021 04:31:58)
macOS version - arm64
Included patches: 1-2400
Compiled by Homebrew
```
 
Steps to reproduce:
- Open terminal in vim ```:term```
- Run some commands like echo in terminal with dummy text (in my case I did ```>>ls```, ```>>echo``` and filled few hundred lines).
- While terminal is focussed, press ```<C-w>:``` to enter vim command: ```:call term_dumpwrite(bufnr('%'),'tempdump.log')```
- Exit vim ```:q!``` (first enter ```<C-w>:``` to move to command buffer)
- Restart vim
- Open terminal  ```:term```, focus command buffer ```<C-w>:``` , and  ```:call term_dumpload('tempdump.log')```.
- Press ```i``` to enter insert mode, and scroll up and down.

As you would notice, the number of lines would be 60 something...

As a sidenote: I too see the bug reported here: https://github.com/vim/vim/issues/2865#issuecomment-479989618

**Comment by brammool** [comment]
term_dumpwrite()  writes the text in the terminal, not scrollback.  You can check the number of lines in the dump file.
That works as intended.
