### ISSUE TITLE
provide option to make small deletes go into numbered registers

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7756]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

It is not easy to recover an old small deletion because it's written into a single register, `"-`.  Vim can't remember more than one small deletion.

OTOH, it is much easier to recover old big deletions because they're written into several registers.  Vim can remember up to 9 big deletions.

**Describe the solution you'd like**

An option to tell Vim that we want small deletions to be written into the numbered registers 1 to 9, just like big deletions.

**Describe alternatives you've considered**

N/A

**Additional context**

Relevant todo item:

https://github.com/vim/vim/blob/df2c2988bbaecd28b0fbec8d64327b1bbb005e19/runtime/doc/todo.txt#L1906-L1907

---

I've seen this feature being asked for in at least 3 discussions:

   - [reddit](https://old.reddit.com/r/vim/comments/h7sbqw/can_we_make_small_deletes_no_newline_in_the/)
   - [vi.stackexchange](https://vi.stackexchange.com/questions/28950/recover-cut-text-in-vim)
   - [google groups](https://groups.google.com/g/vim_dev/c/pbN4rAw8LmI/m/l6kIkIXUv0YJ)

---

I think this patch would implement the option:
```diff
diff --git a/runtime/doc/change.txt b/runtime/doc/change.txt
index 7db3ffc41..9111edb47 100644
--- a/runtime/doc/change.txt
+++ b/runtime/doc/change.txt
@@ -1215,6 +1215,9 @@ less than one line (the small delete register is used then).  An exception is
 made for the delete operator with these movement commands: |%|, |(|, |)|, |`|,
 |/|, |?|, |n|, |N|, |{| and |}|.  Register "1 is always used then (this is Vi
 compatible).  The "- register is used as well if the delete is within a line.
+If 'regone' is set, both registers "1 and "- will always be used for small
+deletes, regardless of the movement commands used (this option is not Vi
+compatible).
 Note that these characters may be mapped.  E.g. |%| is mapped by the matchit
 plugin.
    With each successive deletion or change, Vim shifts the previous contents
diff --git a/runtime/doc/options.txt b/runtime/doc/options.txt
index 8b655dc60..009ebab2b 100644
--- a/runtime/doc/options.txt
+++ b/runtime/doc/options.txt
@@ -5978,6 +5978,15 @@ A jump table for the options with a short description can be found at |Q_op|.
 	many states.  This should prevent Vim from hanging on a combination of
 	a complex pattern with long text.
 
+				     *'regone'* *'rgo'* *'noregone'* *'norgo'*
+'regone' 'rgo'		boolean	(default off)
+                        global
+	When set, a delete which would normally be stored only in the small
+	delete register will also be pushed onto the number register stack,
+	that is the number registers will be shifted down and the delete
+	contents will be stored in numbered register 1.
+	See |quote_number| and |quote_-|.
+
 		*'relativenumber'* *'rnu'* *'norelativenumber'* *'nornu'*
 'relativenumber' 'rnu'	boolean	(default off)
 			local to window
diff --git a/src/ops.c b/src/ops.c
index d8e96ff1a..b39bc6f95 100644
--- a/src/ops.c
+++ b/src/ops.c
@@ -700,7 +700,7 @@ op_delete(oparg_T *oap)
 	 * changed it.
 	 */
 	if (oap->motion_type == MLINE || oap->line_count > 1
-							   || oap->use_reg_one)
+							   || oap->use_reg_one || p_rgo)
 	{
 	    shift_delete_registers();
 	    if (op_yank(oap, TRUE, FALSE) == OK)
diff --git a/src/option.h b/src/option.h
index 4bc189ca7..4f715c2a6 100644
--- a/src/option.h
+++ b/src/option.h
@@ -804,6 +804,7 @@ EXTERN int	p_ro;		// 'readonly'
 EXTERN long	p_rdt;		// 'redrawtime'
 #endif
 EXTERN int	p_remap;	// 'remap'
+EXTERN int p_rgo;		// 'regone' //
 EXTERN long	p_re;		// 'regexpengine'
 #ifdef FEAT_RENDER_OPTIONS
 EXTERN char_u	*p_rop;		// 'renderoptions'
diff --git a/src/optiondefs.h b/src/optiondefs.h
index 6cea0177c..a622c3e9e 100644
--- a/src/optiondefs.h
+++ b/src/optiondefs.h
@@ -2070,6 +2070,9 @@ static struct vimoption options[] =
     {"regexpengine", "re",  P_NUM|P_VI_DEF,
 			    (char_u *)&p_re, PV_NONE,
 			    {(char_u *)0L, (char_u *)0L} SCTX_INIT},
+    {"regone", "rgo",       P_BOOL|P_VI_DEF|P_VIM,
+			    (char_u *)&p_rgo, PV_NONE,
+			    {(char_u *)FALSE, (char_u *)0L} SCTX_INIT},
     {"relativenumber", "rnu", P_BOOL|P_VI_DEF|P_RWIN,
 			    (char_u *)VAR_WIN, PV_RNU,
 			    {(char_u *)FALSE, (char_u *)0L} SCTX_INIT},
diff --git a/src/testdir/test_registers.vim b/src/testdir/test_registers.vim
index b2916f4d0..10a5b1a39 100644
--- a/src/testdir/test_registers.vim
+++ b/src/testdir/test_registers.vim
@@ -92,6 +92,13 @@ func Test_register_one()
   call assert_equal("one\n", @1)
   call assert_equal("two", @-)
 
+  " delete a word does change register one if 'regone' is set
+  set regone
+  call setline(1, "one")
+  normal! de
+  call assert_equal("one", @1)
+  set regone&vim
+
   " delete a word with a register does not change register one
   call setline(1, "three")
   normal "ade
```
It is largely based on the patch of Aryeh Leib Taurog [found here](https://groups.google.com/g/vim_dev/c/pbN4rAw8LmI/m/l6kIkIXUv0YJ).

**Comment by brammool** [comment]
> **Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
> 
> It is not easy to recover an old small deletion because it's written into a single register, `"-`.  Vim can't remember more than one small deletion.
> 
> OTOH, it is much easier to recover old big deletions because they're written into several registers.  Vim can remember up to 9 big deletions.
> 
> **Describe the solution you'd like**
> 
> An option to tell Vim that we want small deletions to be written into the numbered registers 1 to 9, just like big deletions.

I don't like the idea of an option changing this behavior.  Many things
depend on the current behavior, including plugins.

I don't think small deletes are that important to remember.  Sure, once
in a while you want to get that deleted text, but usually there is
another way to get it.  E.g. by yanking it first.  And if you forgot, by
using undo, yanking the text, and then redo.

Perhaps we could have another set of registers for this, or even store
them in a list that is made available in some way.  Any of this would be
better than an option.


-- 
hundred-and-one symptoms of being an internet addict:
267. You get an extra phone line so you can get phone calls.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> or even store them in a list that is made available in some way.

This would be the best solution, I think.

It would be similar to this [other todo item](https://github.com/vim/vim/blob/3eb6bd9c2b36dcce471bfb543c8d5488f1dc17a4/runtime/doc/todo.txt#L2523-L2527) which suggests remembering more than 1 yanked text:

> Consider making YankRing or something else that keeps a list of yanked text
> part of standard Vim.  The "1 to "9 registers are not sufficient.
> 6   When yanking into the unnamed registers several times, somehow make the
>     previous contents also available (like it's done for deleting).  What
>     register names to use?  g"1, g"2, etc.?

**Comment by lacygoill** [comment]
Closing because it has been concluded that an option was not the right approach.  Instead, we want new normal commands to access the last 9 small deletions; for example, using these keys `"1-`, `"2-`, ..., `"9-`.  I don't think we could use `"-1`, `"-2`, because it would probably create an ambiguity if the user wants to supply a count.

---

We can probably remove a todo item, and update another one:
```diff
diff --git a/runtime/doc/todo.txt b/runtime/doc/todo.txt
index 835a5ccca..f425f81a9 100644
--- a/runtime/doc/todo.txt
+++ b/runtime/doc/todo.txt
@@ -1741,9 +1741,6 @@ Dec 13.  Only helps a bit, 10000ii<Esc> is still too slow.
 GTK: problem with 'L' in 'guioptions' changing the window width.
 (Aaron Cornelius, 2012 Feb 6)
 
-Patch to add option that tells whether small deletes go into the numbered
-registers. (Aryeh Leib Taurog, 2013 Nov 18)
-
 Javascript file where indent gets stuck on: GalaxyMaster, 2012 May 3.
 
 The BufUnload event is triggered when re-using the empty buffer.
@@ -2354,8 +2351,8 @@ Consider making YankRing or something else that keeps a list of yanked text
 part of standard Vim.  The "1 to "9 registers are not sufficient.
 6   When yanking into the unnamed registers several times, somehow make the
     previous contents also available (like it's done for deleting).  What
-    register names to use?  g"1, g"2, etc.?
-Also do this for the small delete register "-.
+    register names to use?  g1", g2", etc.?
+Also do this for the small delete register "-; "1-, "2-, etc.
 
 After doing "su" $HOME can be the old user's home, thus ~root/file is not
 correct.  Don't use it in the swap file.
```
