### ISSUE TITLE
PROPOSAL: Jump to last cursor position instead of specific line for global mark jump by quote

### ISSUE THREAD

**Issue by dalanicolai** [vim/vim#7764]
As a Spacemacs user I am implicitly using vim all the time. Now in Spacemacs I have seen multiple requests for how to simply mark buffers for quick buffer switching. Also, I found [this vim article](https://vim.fandom.com/wiki/Easier_buffer_switching) about easy buffer switching. Then I noticed that the quote character `'` jumps to a specific line when using global marks. I guess that for many users it is more handy to be able to jump to last buffer position instead (NOTE only for global marks). So I have created a [PR](https://github.com/emacs-evil/evil/pull/1413) for this for the Emacs evil package. But I guess this idea might be interesting for vim users too. I thought this is a very simple solution for implementing this functionality.

It is just some idea I wanted to share. I am not sure how often people use jump to line with global marks (there is already jump by backtick). So you probably can judge better yourself.

Cheers!

**Comment by fedorenchik** [comment]
It can be done with remapping `'` and ` in vimrc, and it seems relatively common (I have seen in several vim configs).

**Comment by brammool** [comment]
Yep, simply do this in your vimrc:
```vim
map ' `
```

**Comment by dalanicolai** [comment]
This jumps to last cursor position in the buffer, instead of to the location of the mark?
Well, this remapping seems to be a quite obvious solution indeed...
Thanks for your replies!
