### ISSUE TITLE
Command Prompt and Powershell don't show the ~ for an empty line

### ISSUE THREAD

**Issue by ghost** [vim/vim#7768]
**Describe the bug**
Empty lines designed by ~ don't show up in powershell or command prompt. They show up in windows terminal however.

**To Reproduce**
Just open any file in vim in powershell or command prompt.

**Expected behavior**
I expected the ~ for an empty line to show up in command prompt or powershell like it does in windows terminal.

**Screenshots**
![vimwindowsterminal](https://user-images.githubusercontent.com/76400942/106462574-4ad65600-6464-11eb-86c9-65469c0f88a2.png)
![vimcmd](https://user-images.githubusercontent.com/76400942/106462576-4ad65600-6464-11eb-91d3-6f2428ffa217.png)
![vimpowershell](https://user-images.githubusercontent.com/76400942/106462577-4b6eec80-6464-11eb-869d-452bbc4bb5ef.png)

**Environment**
Using vim 8.2 (2019 Dec 12, compiled Mar 30 2020 21:58:19) cygwin on windows 10 64 bit. Tested in command prompt, powershell, and windows terminal. I tried vim from vim.org and got the same results.

**Comment by chrisbra** [comment]
Did you try using `vim --clean`? For cmd.exe, vim should have `:set term=win32` I believe. For powershell I don't know. Make sure that the color configuration is actually correct, e.g. `:set bg=dark t_Co=16` for a very basic dark terminal with 16 colors. You can also check, what the empty lines highlighting will look like by using `:hi EndOfBuffer`

**Comment by ghost** [comment]
> 
> 
> Did you try using `vim --clean`? For cmd.exe, vim should have `:set term=win32` I believe. For powershell I don't know. Make sure that the color configuration is actually correct, e.g. `:set bg=dark t_Co=16` for a very basic dark terminal with 16 colors. You can also check, what the empty lines highlighting will look like by using `:hi EndOfBuffer`

I did both commands `vim --clean` in terminal and `:set term=win32` in vim and everything threw up everywhere.
![vimvomit](https://user-images.githubusercontent.com/76400942/106488077-5126fb00-6481-11eb-8170-31d5315d0551.png)

**Comment by chrisbra** [comment]
> I did both commands vim --clean in terminal and :set term=win32 in vim and everything threw up everywhere.

Isn't that the default? So you shouldn't need to set term manually. In any case, make sure that the bg setting is set correctly. And then check the EndOfBuffer highlighting is correct.

**Comment by ghost** [comment]
I tried both the bg and EndOfBuffer commands. Both didn't make a lick of difference.

**Comment by lacygoill** [comment]
Since [8.2.2508](https://github.com/vim/vim/releases/tag/v8.2.2508), we can set the tilde character via the ['fillchars'](https://vimhelp.org/options.txt.html#'fillchars') option:

    let &fillchars ..= ',eob:~'

Note that the OP deleted their account, so we'll probably never get any more feedback from them.

**Comment by k-takata** [comment]
Closing then
