### ISSUE TITLE
PWD not changed to follow buffer when writing a new file when &autochdir is on

### ISSUE THREAD

**Issue by h3xx** [vim/vim#777]
The working directory doesn't follow the buffer when it should, after writing a new file from a new buffer.

This seems like it's related to issue #704 
## Steps to reproduce:
1. Start vim from home directory with no arguments: `vim -N -u NONE`
2. `:set autochdir`
3. `:w /tmp/new_file.temp`
## Outcome:

The `%` register is set to "/tmp/new_file.temp" but the `:pwd` command gives the directory you started vim in.
## Expected outcome:

The `%` register should be set to "new_file.temp" and the `:pwd` command should give "/tmp".

Further information:

vim 7.4.1752
Linux

**Comment by h3xx** [comment]
Re-tried in d10abe5. Problem still exists.

**Comment by misterfish** [comment]
Hi, I'm not sure I agree with the expected outcome. If the % register is `/tmp/new_file.temp` then `:pwd` should not be `/tmp`; otherwise % would be just `new_file.temp`.

We could change pwd to `/tmp`, but did autocmd ever actually work that way?

Furthermore it doesn't seem to me that #704 is related to this.

**Comment by h3xx** [comment]
@misterfish Ah quite right. I've updated the expected outcome section in my bug report.

`&acd` should have the side affect that the % register will always be the basename of the current file. The fact that it's not is a side effect of PWD not getting updated.

**Comment by vim-ml** [comment]
The issue hasn't gone as of 7.2254 (Windows, 64-bit). The description of Dan Church still holds for the part of the ":pwd" command, i.e. autochdir is not effective here.
