### ISSUE TITLE
Random hang/pause processing received channel message

### ISSUE THREAD

**Issue by myitcv** [vim/vim#7781]
**Describe the bug**

Some [`govim`](https://github.com/govim/govim) users are experiencing random hangs that appear to be related to Vim waiting for a message, that appears to have been received but not yet processed.

**To Reproduce**

Happens randomly. Not a defined set of steps to reproduce.

**Expected behavior**

No hang.

Consider this Vim log: [vim_channel_20210204_1651_00_KHBria7mrWDa.log](https://github.com/vim/vim/files/5928434/vim_channel_20210204_1651_00_KHBria7mrWDa.log)

The section that I think is relevant is:

```
139.182550 SEND on 0(in): '[250,["function","function:GOVIM_internal_SetUserBusy",[1,{"bufnr":1,"col":9,"line":271,"winid":1000,"winnr":1,"screenpos":{"col":13,"row":47,"endcol":13,"curscol":13}}]]]
'
139.182597 on 0: Blocking read JSON for id 250
139.182608 : looking for messages on channels
139.182614 on 21: Closing channel because all readable fds are closed
139.182619 on 21: Closing channel
139.182648 on 21: Invoking callbacks and flushing buffers before closing
139.182659 on 21: Invoking channel callback <SNR>95_on_stdout_vim
139.182715 on 21: Invoking channel callback <SNR>95_on_stdout_vim
139.182753 on 21: Invoking channel callback <SNR>95_on_stdout_vim
139.182800 on 21: Invoking channel callback <SNR>95_on_stdout_vim
139.182837 on 21: Invoking channel callback <SNR>95_on_stdout_vim
139.182871 on 21: Invoking channel callback <SNR>95_on_stdout_vim
139.182908 on 21: Invoking channel callback <SNR>95_on_stdout_vim
139.182941 on 21: Invoking channel callback <SNR>95_on_stdout_vim
139.182973 on 21: Invoking channel callback <SNR>95_on_stdout_vim
139.183006 on 21: Invoking channel callback <SNR>95_on_stdout_vim
139.183038 on 21: Invoking channel callback <SNR>95_on_stdout_vim
139.183074 on 21: Invoking channel callback <SNR>95_on_stdout_vim
139.183107 on 21: Invoking close callback <SNR>95_on_exit_vim
139.183211 on 21: Job exited with 0
139.185026 RECV on 0(out): '[250,["",null]]
'
139.199411 on 0: Waiting for up to 30000 msec
169.228594 on 0: Timed out on id 250
169.229190 : SafeState: Start triggering
169.231681 : raw key input: "OCOCOAOBOAOBOAOBOAOBOAOBOAOBOAOBOAOBOAOAOB"
169.283780 : looking for messages on channels
169.283810 on 0: Getting JSON message 250
169.283821 on 0: Dropping message 250 without callback
```

Despite:

```
139.185026 RECV on 0(out): '[250,["",null]]
```

there is a timeout on id 250 (30 second blocking pause in this case). 

Contrast this with earlier messages, something seems a bit wrong:

```
139.146084 SEND on 0(in): '[249,["function","function:GOVIM_internal_BufChanged",[1,270,271,1,[{"lnum":270,"col":12,"added":1,"end":271,"lines":["        tx,","        &legacyFilter, ` select study_id, study_config_value from inc.study_config where study_id = $1 and study_config_type = 'diagnostics-filters'`, qdata.StudyID); err != nil {"]}]]]]
'
139.146126 on 0: Blocking read JSON for id 249
139.146140 : looking for messages on channels
139.146150 on 0: Waiting for up to 30000 msec
139.148505 RECV on 0(out): '[249,["",null]]
'
139.148531 on 0: Getting JSON message 249
139.148548 on 0: Received JSON for id 249
```

**Screenshots**

n/a

**Environment (please complete the following information):**
 - Vim version [e.g. 8.1.1234] (Or paste the result of `vim --version`.)

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 20 2021 22:47:34)
Included patches: 1-2380
Compiled by Arch Linux
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       +tcl/dyn
-autoservername    +folding           +multi_byte        +termguicolors
-balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
-browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              +perl/dyn          +title
-clientserver      +job               +persistent_undo   -toolbar
-clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           +python/dyn        +visual
+conceal           +linebreak         +python3/dyn       +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua/dyn           +ruby/dyn          +wildmenu
+dialog_con        +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
-dnd               +mouse             -sound             -xfontset
-ebcdic            -mouseshape        +spell             -xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              +mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: gcc -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.32/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim -lm -ltinfo -lelf -lacl -lattr -lgpm -ldl -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.32/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib -L/usr/lib/perl5/5.32/core_perl/CORE -lperl -lpthread -ldl -lm -lcrypt -lutil -lc -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm 
```

 - OS: [e.g. Ubuntu 18.04, Windows 10 1809, macOS 10.14]

```
Linux 5.10.11-arch1-1 x86_64
```

 - Terminal: [e.g. GNOME Terminal, mintty, iTerm2, tmux, GNU screen] (Use GUI if you use the GUI.)

```
termite v15-1-g7e9a93b
```

**Additional context**

n/a

**Comment by brammool** [comment]
Paul Jolly wrote:

> **Describe the bug**
> 
> Some [`govim`](https://github.com/govim/govim) users are experiencing
> random hangs that appear to be related to Vim waiting for a message,
> that appears to have been received but not yet processed.
> 
> **To Reproduce**
> 
> Happens randomly. Not a defined set of steps to reproduce.

That unfortunately makes it very difficult for me to try to fix this.
 
> **Expected behavior**
> 
> No hang.
> 
> Consider this Vim log: [vim_channel_20210204_1651_00_KHBria7mrWDa.log](https://github.com/vim/vim/files/5928434/vim_channel_20210204_1651_00_KHBria7mrWDa.log)
> 
> The section that I think is relevant is:
> 
> ```
> 139.182550 SEND on 0(in): '[250,["function","function:GOVIM_internal_SetUserBusy",[1,{"bufnr":1,"col":9,"line":271,"winid":1000,"winnr":1,"screenpos":{"col":13,"row":47,"endcol":13,"curscol":13}}]]]
> '
> 139.182597 on 0: Blocking read JSON for id 250
> 139.182608 : looking for messages on channels
> 139.182614 on 21: Closing channel because all readable fds are closed
> 139.182619 on 21: Closing channel
> 139.182648 on 21: Invoking callbacks and flushing buffers before closing
> 139.182659 on 21: Invoking channel callback <SNR>95_on_stdout_vim
> 139.182715 on 21: Invoking channel callback <SNR>95_on_stdout_vim
> 139.182753 on 21: Invoking channel callback <SNR>95_on_stdout_vim
> 139.182800 on 21: Invoking channel callback <SNR>95_on_stdout_vim
> 139.182837 on 21: Invoking channel callback <SNR>95_on_stdout_vim
> 139.182871 on 21: Invoking channel callback <SNR>95_on_stdout_vim
> 139.182908 on 21: Invoking channel callback <SNR>95_on_stdout_vim
> 139.182941 on 21: Invoking channel callback <SNR>95_on_stdout_vim
> 139.182973 on 21: Invoking channel callback <SNR>95_on_stdout_vim
> 139.183006 on 21: Invoking channel callback <SNR>95_on_stdout_vim
> 139.183038 on 21: Invoking channel callback <SNR>95_on_stdout_vim
> 139.183074 on 21: Invoking channel callback <SNR>95_on_stdout_vim
> 139.183107 on 21: Invoking close callback <SNR>95_on_exit_vim
> 139.183211 on 21: Job exited with 0
> 139.185026 RECV on 0(out): '[250,["",null]]
> '
> 139.199411 on 0: Waiting for up to 30000 msec
> 169.228594 on 0: Timed out on id 250
> 169.229190 : SafeState: Start triggering
> 169.231681 : raw key input: "OCOCOAOBOAOBOAOBOAOBOAOBOAOBOAOBOAOBOAOAOB"
> 169.283780 : looking for messages on channels
> 169.283810 on 0: Getting JSON message 250
> 169.283821 on 0: Dropping message 250 without callback
> ```
> 
> Despite:
> 
> ```
> 139.185026 RECV on 0(out): '[250,["",null]]
> ```
> 
> there is a timeout on id 250 (30 second blocking pause in this case). 
> 
> Contrast this with earlier messages, something seems a bit wrong:
> 
> ```
> 139.146084 SEND on 0(in): '[249,["function","function:GOVIM_internal_BufChanged",[1,270,271,1,[{"lnum":270,"col":12,"added":1,"end":271,"lines":["        tx,","        &legacyFilter, ` select study_id, study_config_value from inc.study_config where study_id = $1 and study_config_type = 'diagnostics-filters'`, qdata.StudyID); err != nil {"]}]]]]
> '
> 139.146126 on 0: Blocking read JSON for id 249
> 139.146140 : looking for messages on channels
> 139.146150 on 0: Waiting for up to 30000 msec
> 139.148505 RECV on 0(out): '[249,["",null]]
> '
> 139.148531 on 0: Getting JSON message 249
> 139.148548 on 0: Received JSON for id 249
> ```

The main difference appears to be that for message 249 the RECV happens
after the "Waiting for" message, while for message 250 the RECV is
before that.  I suspect that the "Job exited" and perhaps one of the
callbacks causes the message to be received just before starting the
blocking wait.

Can you add more ch_log() calls in channel_read_json_block() to see what
exactly happens there?  Especially around channel_parse_messages(), and
wether the "continue" after it is encountered or not.

I suspect there should be another check after channel_parse_messages()
to continue, go back to channel_parse_json().  Perhaps whether
channel_peek() returns the same as before.

-- 
Q: How does a UNIX Guru do Sex ?
A: unzip;strip;touch;finger;mount;fsck;more;yes;umount;sleep

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by whonore** [comment]
This looks similar to an issue I opened a while ago (#6364). Unfortunately, I wasn't able to come up with a reliable, self-contained example to trigger this behavior either, but I did include a log, which might be helpful if anyone looks into this further.

**Comment by prabirshrestha** [comment]
You might want to look at [async.vim](https://github.com/prabirshrestha/async.vim) source. We have a bunch of workarounds. Some of these PRs have bunch of other references.

- https://github.com/prabirshrestha/async.vim/pull/15
- https://github.com/prabirshrestha/async.vim/pull/22
- https://github.com/prabirshrestha/async.vim/pull/24
- https://github.com/prabirshrestha/async.vim/pull/31
- https://github.com/prabirshrestha/async.vim/pull/18
