### ISSUE TITLE
":new {file}" command changes alternate file of original window

### ISSUE THREAD

**Issue by obcat** [vim/vim#7782]
**Describe the bug**
The `:[N]new [++opt] [+cmd] {file}` command changes the alternate file of original window.

**To Reproduce**
```vim
$ vim --clean aaa
:edit bbb
:echo expand('#')
" => aaa
:new ccc
:wincmd p
:echo expand('#')
" => ccc
```

**Expected behavior**
`aaa` is echoed.

**Environment**
 - Vim 8.2.2300
 - macOS Catalina (version 10.15.7)
 - iTerm2

**Additional context**
This behavior is like an ":e" first, and then a ":split" command; reverse of the description:
```
:[N]new [++opt] [+cmd] {file}
:[N]sp[lit] [++opt] [+cmd] {file}			*:split_f*
		Create a new window and start editing file {file} in it.  This
		behaves like a ":split" first, and then an ":e" command.
		If [+cmd] is given, execute the command when the file has been
		loaded |+cmd|.
```

**Comment by brammool** [comment]
It's been like this for a very long time, changing it now might cause more problems than it solves.
Let me add a remark to the documentation.

**Comment by obcat** [comment]
I got it. Thank you very much ;)
