### ISSUE TITLE
[popup windows] resetting 'textprop' causes 'textpropwin' to be reset with the id of the current window

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7785]
**Describe the bug**

Resetting the `textprop` option of a popup causes the `textpropwin` option to be reset with the id of the current window.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9
        setline(1, 'text')
        prop_type_add('textprop', {})
        prop_add(1, 1, {type: 'textprop', length: 1})
        var id = popup_create('', {textprop: 'textprop'})
        echom "'textpropwin' BEFORE 'textprop' is reset: " .. popup_getoptions(id).textpropwin
        new
        popup_setoptions(id, {textprop: 'textprop'})
        echom "'textpropwin' AFTER 'textprop' is reset: " .. popup_getoptions(id).textpropwin
    EOF
    )

It outputs:

    'textpropwin' BEFORE 'textprop' is reset: 1000
    'textpropwin' AFTER 'textprop' is reset: 1002

**Expected behavior**

It outputs:

    'textpropwin' BEFORE 'textprop' is reset: 1000
    'textpropwin' AFTER 'textprop' is reset: 1000

IOW, I would expect the `textpropwin` option to be preserved, because `popup_setoptions()` only reset `textprop`.

**Environment**

 - Vim version: 8.2 Included patches: 1-2467
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(365)

**Additional context**

It's wrong for `textpropwin` to have been reset to `1002`.  There is no text property in this window to which the popup could be attached.

**Comment by brammool** [comment]
This is working as intended, when passing the "textprop" option then "textpropwin" and "textpropid" are used.  When omitted the default is used.  I'll add a remark in the help to make this clearer.
