### ISSUE TITLE
[popup windows] cannot get 'textprop*' options from non-focused tab page

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7786]
**Describe the bug**

We cannot get the `'textprop*'` options of a popup, if it's displayed in a non-focused tab page.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9
        setline(1, 'some text')
        prop_type_add('textprop', {})
        prop_add(1, 1, {type: 'textprop', length: 1})
        var id = popup_create('TEST', {textprop: 'textprop', highlight: 'ErrorMsg', tabpage: 1})
        tab sp
        echo popup_getoptions(id)->keys()->filter((_, v) => v =~ 'textprop')
    EOF
    )

It outputs an empty list:

    []

**Expected behavior**

It outputs this list:

    ['textprop', 'textpropid', 'textpropwin']

**Environment**

 - Vim version: 8.2 Included patches: 1-2467
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(365)

**Additional context**

No issue to get these options from a different window in the *same* tab page:
```vim
vim9
setline(1, 'some text')
prop_type_add('textprop', {})
prop_add(1, 1, {type: 'textprop', length: 1})
var id = popup_create('TEST', {textprop: 'textprop', highlight: 'ErrorMsg', tabpage: 1})
new
echo popup_getoptions(id)->keys()->filter((_, v) => v =~ 'textprop')
```
    ['textprop', 'textpropid', 'textpropwin']

---

There's nothing at [`:h popup_getoptions()`](https://vimhelp.org/popup.txt.html#popup_getoptions()) which suggests that it is required to be in the same tab page as a popup attached to a text property, if we want to get its `textprop*` options.

Although, there is this sentence:

   > "textprop", "textpropid" and "textpropwin" are only present
   > when "textprop" was set.

But again, it doesn't say that we need to be in the same tab page.  It just says that the options don't exist when `textprop` was not set.  But in the previous snippet, `textprop` *is* set.

**Comment by lacygoill** [comment]
I have found 3 other possible issues with popups attached to text properties in non visible windows:

   - we cannot attach a popup to a text property in a window in a non-focused tab page
   - `popup_setoptions()` fails to reset the `textpropwin` option of a popup attached to a text property in a window in a non-focused tab page
   - a popup attached to a text property loses its `textprop*` options when the buffer is reloaded while we're focusing a different tab page

But before I open separate issues, I need to know whether those are really bugs.  When we want to manipulate a popup attached to a text property, is it required that we are in the same tab page?

**Comment by lacygoill** [comment]
> - we cannot attach a popup to a text property in a window in a non-focused tab page
> - popup_setoptions() fails to reset the textpropwin option of a popup attached to a text property in a window in a non-focused tab page
> - a popup attached to a text property loses its textprop* options when the buffer is reloaded while we're focusing a different tab page

Those issues make it difficult to emulate virtual text when a buffer is displayed in several windows in different tab pages.  Instead of creating/updating virtual texts in *all* windows displaying the buffer, I think I need to only do it in the windows in the current tab page.  Then I probably need to install some autocmd listening to `TabEnter` which checks whether some windows need virtual texts to be created/updated.

**Comment by brammool** [comment]
I can fix the first issue.  Please open separate issues for the other problems.

**Comment by lacygoill** [comment]
Thank you, the patch fixed almost all the issues at once.
