### ISSUE TITLE
Vim9: :echo parses # inconsistently

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7794]
**Describe the bug**

In Vim9 script, `:echo` parses `#` inconsistently.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9
        echo #{
    EOF
    )

`E121` is raised:

    E121: Undefined variable: #

Now, run this other shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9
        echo # {
    EOF
    )

This time, no error is raised.

**Expected behavior**

The first command doesn't raise any error because this is consistent with:

   - the second command
   - other comments after `:echo`
   - other comments after `:exe`

**Environment**

 - Vim version: 8.2 Included patches: 1-2475
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(365)

**Additional context**

`#` should always be parsed as a comment leader.  The `#{}` syntax was removed in [8.2.2082](https://github.com/vim/vim/releases/tag/v8.2.2082).

**Comment by brammool** [comment]
Was fixed by patch 8.2.2484
