### ISSUE TITLE
Vim9: "=" fails to fix indentation in script iterating over list containing dictionary on separate line

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7798]
**Describe the bug**

In Vim9 script, the `=` operator might fail to properly fix the indentation when we iterate over a list containing a dictionary written on a separate line.

**To Reproduce**

Run this shell command:

    vim -Nu <(cat <<'EOF'
        vim9
        var lines =<< trim END
            vim9
            def Func()
                for x in [
                    {key: 'value'},
                ]
                    eval 0
                endfor
            enddef
            Func()
        END
        setline(1, lines)
        set et
        filetype plugin indent on
        set ft=vim
        sil norm! =G
    EOF
    )

The current buffer contains this text:

    vim9
    def Func()
            for x in [
                            {key: 'value'},
                                    ]
                            eval 0
                    endfor
            enddef
            Func()

**Expected behavior**

The current buffer contains this text:

    vim9
    def Func()
        for x in [
                {key: 'value'},
                ]
            eval 0
        endfor
    enddef
    Func()

**Environment**

 - Vim version: 8.2 Included patches: 1-2475
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(365)

**Additional context**

I *think* `=` conflates the start of the dictionary with the start of a block.

---

Not sure it's the right fix, but here is a suggestion:
```diff
diff --git a/runtime/indent/vim.vim b/runtime/indent/vim.vim
index b031d1f2e..a8f0d3bca 100644
--- a/runtime/indent/vim.vim
+++ b/runtime/indent/vim.vim
@@ -100,7 +100,7 @@ function GetVimIndentIntern()
   else
     " A line starting with :au does not increment/decrement indent.
     if prev_text !~ '^\s*au\%[tocmd]'
-      let i = match(prev_text, '\(^\||\)\s*\(export\s\+\)\?\({\|\(if\|wh\%[ile]\|for\|try\|cat\%[ch]\|fina\|finall\%[y]\|fu\%[nction]\|def\|el\%[seif]\)\>\)')
+      let i = match(prev_text, '\(^\||\)\s*\(export\s\+\)\?\({\%(\%(\s*\w\|-\)\+:\)\@!\|\(if\|wh\%[ile]\|for\|try\|cat\%[ch]\|fina\|finall\%[y]\|fu\%[nction]\|def\|el\%[seif]\)\>\)')
       if i >= 0
 	let ind += shiftwidth()
 	if strpart(prev_text, i, 1) == '|' && has('syntax_items')
```
Before parsing `{` as the start of a block, it makes sure there is not a key in a dictionary following immediately afterward; i.e. a sequence of ASCII letters, digits, '-' and '_', followed by a colon.

If that's not the right fix, then maybe we could borrow some code from this patch which fixed a similar issue (https://github.com/vim/vim/issues/7628):

https://github.com/vim/vim/commit/82be4849eed0b8fbee45bc8da99b685ec89af59a#diff-48cf28a80003168943d20d7d40a2454ff6980019c84a3e4ac9cb7e819da22876

**Comment by lacygoill** [comment]
Sorry, the patch contains an error.  New patch:
```diff
diff --git a/runtime/indent/vim.vim b/runtime/indent/vim.vim
index b031d1f2e..a8f0d3bca 100644
--- a/runtime/indent/vim.vim
+++ b/runtime/indent/vim.vim
@@ -100,7 +100,7 @@ function GetVimIndentIntern()
   else
     " A line starting with :au does not increment/decrement indent.
     if prev_text !~ '^\s*au\%[tocmd]'
-      let i = match(prev_text, '\(^\||\)\s*\(export\s\+\)\?\({\|\(if\|wh\%[ile]\|for\|try\|cat\%[ch]\|fina\|finall\%[y]\|fu\%[nction]\|def\|el\%[seif]\)\>\)')
+      let i = match(prev_text, '\(^\||\)\s*\(export\s\+\)\?\({\%(\s*\%(\w\|-\)\+:\)\@!\|\(if\|wh\%[ile]\|for\|try\|cat\%[ch]\|fina\|finall\%[y]\|fu\%[nction]\|def\|el\%[seif]\)\>\)')
       if i >= 0
 	let ind += shiftwidth()
 	if strpart(prev_text, i, 1) == '|' && has('syntax_items')
```

**Comment by brammool** [comment]
It probably works better to check if a "}" is following.  Even when the "{" starts a dictionary, increasing the indent is still needed.  Unless the dictionary ends in the same line.
I'll add a couple more tweaks, but it's far from finished.
