### ISSUE TITLE
" mark not set on :bd, when :bd also closes tab

### ISSUE THREAD

**Issue by HarmtH** [vim/vim#780]
Description:
The " mark, which should be set to the last location when exiting the buffer, is not set when :bd also closes the tab the buffer is displayed in.

Version:
Tested on VIM 7.4.1786

Reproduction:
seq 3 > ~/test
vim -u NONE -N ~/test
3G
:bd
:e ~/test
'" (single quote, double quote)
(observe cursor goes to line 3, expected behaviour)
:bd
:tabedit ~/test
(cursor is on line 1 now)
:bd
(line 1 should be set to " mark)
:e ~/test
'"
(observe cursor goes to line 3 again, line 1 expected)

Extra info:
- When the :bd commands closes a window/split, this bug does not occur.
- This also means that when editing ~/test in a new tab, open another file in a split in this tab, and then :bd'ing ~/test (such that the window closes but the tab stays open), this bug also does not occur.

**Comment by dechimp** [comment]
When I type :bd in a tab, I expect to be taken back to the previous buffer, not the previous tab

**Comment by chrisbra** [comment]
@dechimp it is clearly documented that `:bd` closes a window, which will close a tab, if it is the last window in the tab.

**Comment by HarmtH** [comment]
Fixed by patch 7.4.2212

**Comment by dechimp** [comment]
@chrisbra thanks for clarifying, even though the behavior throws me and maybe other new users off. I just realized my comment wasn't related to HarmtH's issue, so no need to discuss here

**Comment by lacygoill** [comment]
Since the issue was fixed, then this todo item is no longer relevant:

https://github.com/vim/vim/blob/21829c5f2c86cd525c8468121b4fc54c5d75bf6e/runtime/doc/todo.txt#L1590-L1591
