### ISSUE TITLE
In :terminal, output containing certain special characters is garbled.

### ISSUE THREAD

**Issue by kyoh86** [vim/vim#7801]
In `:terminal`, when the output contains `U+309A` (utf-8: `\xe3 \x82 \x9a`), I get garbled text.

1. Run `vim --clean` or the `gvim --clean`.
2. Call `:terminal`
3. Run `echo -e "\xe3\x83\x9b\xe3\x82\x9a"`

Expected result (in direct terminal):

![9d89ae38e0dd10b8cbb2a0fc050d85a8](https://user-images.githubusercontent.com/5582459/107249607-dbb9bc80-6a76-11eb-8630-3c61244ed689.png)

Actual I got (in `:terminal` on vim):
![6e6beac13884bd7b3691786450ec7667](https://user-images.githubusercontent.com/5582459/107250576-4a971580-6a77-11eb-94bb-8c82564100f4.png)

<details><summary>Environment (vim/GNOME terminal/arch)</summary><pre>VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 20 2021 22:47:34)
Included patches: 1-2380
Compiled by Arch Linux
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               +cryptv            +fork()            +modify_fname      +persistent_undo   +syntax            +visualextra
+arabic            +cscope            +gettext           +mouse             +popupwin          +tag_binary        +viminfo
+autocmd           +cursorbind        -hangul_input      +mouseshape        +postscript        -tag_old_static    +vreplace
+autochdir         +cursorshape       +iconv             +mouse_dec         +printer           -tag_any_white     +wildignore
-autoservername    +dialog_con_gui    +insert_expand     +mouse_gpm         +profile           +tcl/dyn           +wildmenu
+balloon_eval      +diff              +ipv6              -mouse_jsbterm     +python/dyn        +termguicolors     +windows
+balloon_eval_term +digraphs          +job               +mouse_netterm     +python3/dyn       +terminal          +writebackup
+browse            +dnd               +jumplist          +mouse_sgr         +quickfix          +terminfo          +X11
++builtin_terms    -ebcdic            +keymap            -mouse_sysmouse    +reltime           +termresponse      -xfontset
+byte_offset       +emacs_tags        +lambda            +mouse_urxvt       +rightleft         +textobjects       +xim
+channel           +eval              +langmap           +mouse_xterm       +ruby/dyn          +textprop          -xpm
+cindent           +ex_extra          +libcall           +multi_byte        +scrollbind        +timers            +xsmp_interact
+clientserver      +extra_search      +linebreak         +multi_lang        +signs             +title             +xterm_clipboard
+clipboard         -farsi             +lispindent        -mzscheme          +smartindent       +toolbar           -xterm_save
+cmdline_compl     +file_in_path      +listcmds          +netbeans_intg     +sound             +user_commands     
+cmdline_hist      +find_in_path      +localmap          +num64             +spell             +vartabs           
+cmdline_info      +float             +lua/dyn           +packages          +startuptime       +vertsplit         
+comments          +folding           +menu              +path_extra        +statusline        +virtualedit       
+conceal           -footer            +mksession         +perl/dyn          -sun_workshop      +visual            
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/lzo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cloudproviders -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/at-spi-2.0 -pthread -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: gcc -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.32/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim -lgtk-3 -lgdk-3 -lz -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE -lm -ltinfo -lelf -lcanberra -lacl -lattr -lgpm -ldl -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.32/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib -L/usr/lib/perl5/5.32/core_perl/CORE -lperl -lpthread -ldl -lm -lcrypt -lutil -lc -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm 
</pre></details>

**Comment by brammool** [comment]
That's a bug in libvterm. I'm surprised we haven't seen this problem before.  @leonerd

**Comment by brammool** [comment]
There was actually a test for this, but it happily accepted the wrong output.
