### ISSUE TITLE
[Vim indent plugin] wrong indentation on line following start of fold

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7804]
**Describe the bug**

The Vim indent plugin wrongly indents a line following the start of a fold.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9
        var lines =<< trim END
            fu Func()
                " some text {{{
                "}}}
            endfu
        END
        setline(1, lines)
        filetype plugin indent on
        set ft=vim
        feedkeys('2Go', 'ntx')
    EOF
    )

The buffer contains this text:

    fu Func()
        " some text {{{
                "
        "}}}
    endfu

**Expected behavior**

The buffer contains this text:

    fu Func()
        " some text {{{
        "
        "}}}
    endfu

**Environment**

 - Vim version: 8.2 Included patches: 1-2488
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(365)

**Additional context**

Suggestion 1:
```diff
diff --git a/runtime/indent/vim.vim b/runtime/indent/vim.vim
index b031d1f2e..d39a02db1 100644
--- a/runtime/indent/vim.vim
+++ b/runtime/indent/vim.vim
@@ -158,7 +158,7 @@ function GetVimIndentIntern()
 
   " A line ending in "{"/"[} is most likely the start of a dict/list literal,
   " indent the next line more.  Not for a continuation line.
-  if prev_text_end =~ '[{[]\s*$' && !found_cont
+  if prev_text_end =~ '\%({{\)\@2<!{\s*$\|\[\s*$' && !found_cont
     let ind = ind + shiftwidth()
   endif
 
```
Suggestion 2:
```diff
diff --git a/runtime/indent/vim.vim b/runtime/indent/vim.vim
index b031d1f2e..e3c248548 100644
--- a/runtime/indent/vim.vim
+++ b/runtime/indent/vim.vim
@@ -158,7 +158,7 @@ function GetVimIndentIntern()
 
   " A line ending in "{"/"[} is most likely the start of a dict/list literal,
   " indent the next line more.  Not for a continuation line.
-  if prev_text_end =~ '[{[]\s*$' && !found_cont
+  if prev_text_end !~ '^\s*["#]' && prev_text_end =~ '[{[]\s*$' && !found_cont
     let ind = ind + shiftwidth()
   endif
 
```
None of them are entirely correct, but I still think they would be a significant improvement over the current situation.

**Comment by brammool** [comment]
Checking that there is a space before the { or [ should work.
