### ISSUE TITLE
[popup windows] popup attached to text property wrongly displayed in tabline

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7807]
**Describe the bug**

A popup attached to a text property might be displayed in the tabline when there is no more room for any of its text to be displayed after the text to which it's attached.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9
        set nowrap stal=2
        rightb vnew
        setline(1, ['', '', '', 'some text'])
        prop_type_add('textprop', {})
        prop_add(4, 9, {type: 'textprop', length: 5})
        popup_create('attached to "text"', {
            textprop: 'textprop',
            highlight: 'ErrorMsg',
            line: -1,
            wrap: false,
            fixed: true,
            })
    EOF
    )

Execute this Ex command:

    :vert res -1

Press `@:` to repeat the Ex command.
Keep pressing `@@` to repeat the Ex command even more, until the width of the window doesn't give enough room for any character inside the text of the popup to be displayed: the popup jumps into the tabline.

**Expected behavior**

When there is no more room, the popup is simply hidden; it doesn't jump into the tabline.

**Screenshots**

![gif](https://user-images.githubusercontent.com/8505073/107382182-e5333b00-6aef-11eb-8d5c-6b71669fba55.gif)

**Environment**

 - Vim version: 8.2 Included patches: 1-2488
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(365)

**Additional context**

N/A

**Comment by lacygoill** [comment]
This also contradicts `popup_getpos()` which reports that the popup is on the 5th line of the screen; not the first one:
```vim
vim9
set nowrap stal=2
rightb vnew
setline(1, ['', '', '', 'some text'])
prop_type_add('textprop', {})
prop_add(4, 9, {type: 'textprop', length: 5})
var id = popup_create('attached to "text"', {
    textprop: 'textprop',
    highlight: 'ErrorMsg',
    line: -1,
    wrap: false,
    fixed: true,
    })
wincmd w
wincmd |
echo popup_getpos(id).line == 5
```
    true

**Comment by lacygoill** [comment]
Same issue when we insert enough characters to push the entire popup outside the window:

![gif](https://user-images.githubusercontent.com/8505073/107463032-a936bf00-6b5d-11eb-80e0-c9da85fcc945.gif)

**Comment by bfrg** [comment]
That always seemed like intentional to me. The help even mentions it:
https://github.com/vim/vim/blob/963ffa0a5a6091655ed72b4590ec5d5a1653bce8/runtime/doc/popup.txt#L849-L850

**Comment by lacygoill** [comment]
OK, but in this case, the tabline is not nearby at all.

It looks a bit similar to #7808 which was closed because it's working as intended.

In both cases, I would like the popup to completely disappear when there is no more room, because that's the behavior I need to improve a virtual text emulation I'm working on.

This causes several issues, which I'm trying to fix by resetting the popup text so that:

   - it doesn't overflow when creating a vertical split
   - it doesn't jump in unexpected locations when inserting characters or scrolling on long non-wrapped lines

I have an idea, but I'm not sure it'll work all the time.  In any case, if I find a fix, I'll close this issue; otherwise, it would be nice to have an option to tell Vim to hide the popup when there's no more room to display it.

**Comment by lacygoill** [comment]
> OK, but in this case, the tabline is not nearby at all.

Worse, if you have several popups attached to text properties, they can all stack up in the tabline which is even more confusing.

**Comment by lacygoill** [comment]
To illustrate:

![gif](https://user-images.githubusercontent.com/8505073/107494626-4e1dc000-6b8f-11eb-80fd-27d85ed252b8.gif)

Notice the unreadable mess in the tabline at the end of the gif.

---

Here is my [current code](https://github.com/lacygoill/vim-virtual-text).

**Comment by lacygoill** [comment]
Actually, I wonder whether all my issues don't stem from the way I compute the padding.  I think it's too naive.  It doesn't take into account that we could be scrolling on a long non-wrapped line, and possibly other factors.  I'm going to try to find a more sophisticated algorithm to get a better padding.  Maybe it will fix all these weird issues.  If not, I'll re-open the issue or ask a new popup option argument.

**Comment by lacygoill** [comment]
Some further tests suggest that the issue cannot be avoided simply by tweaking the padding, so I re-open.

As a last resort, I'm considering hiding all the popups with `popup_hide()` when the issue arises.  But it doesn't work.  `popup_hide()` doesn't hide a popup attached to a text property.

Is it working as intended?  There's nothing at `:h popup_hide()` which documents this limitation.

Also, the help says:

> If the text property moves out of view then the popup will be hidden.

That's not what I observe.  The popup is always visible (totally or partially).  What am I missing?

**Comment by bfrg** [comment]
> If the text property moves out of view then the popup will be hidden.

Out of view means, scrolling the window up/down until the line with the text-property is not visible anymore.

**Comment by lacygoill** [comment]
> Out of view means, scrolling the window up/down until the line with the text-property is not visible anymore.

Ah thanks.  So, "out of view" only cares about the line position, not the column position.

---

At least, I need to find a way to temporarily hide these popups.  `popup_hide()` fails to do that:
```vim
vim9
setline(1, 'some text')
prop_type_add('textprop', {})
prop_add(1, 9, {type: 'textprop', length: 5})
var id = popup_create('attached to "text"', {
    textprop: 'textprop',
    highlight: 'ErrorMsg',
    line: -1,
    })
popup_hide(id)
```

**Comment by bfrg** [comment]
I can confirm, a popup window that is attached to a text-property cannot be hidden with `popup_hide()`.
