### ISSUE TITLE
[popup windows] padding of popup attached to text property gets truncated when decreasing windows's width

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7808]
**Describe the bug**

When decreasing the width of a window, the first character in a popup window attached to a text property "consumes" the left padding to always remain visible.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9
        set nowrap
        rightb vnew
        setline(1, 'some special word')
        prop_type_add('textprop', {})
        prop_add(1, 6, {type: 'textprop', length: 7})
        popup_create('attached to "special"', {
            textprop: 'textprop',
            highlight: 'ErrorMsg',
            line: -1,
            wrap: false,
            fixed: true,
            padding: [0, 0, 0, 6],
            mask: [[1, 6, 1, 1]],
            })
    EOF
    )

Execute this Ex command:

    :vert res -1

Press `@:` to repeat the Ex command.

Keep pressing `@@` to repeat the Ex command even more, until the width of the window only allows for 1 character in the popup: the next resizes don't push the last character of the popup outside the terminal window, and the left padding decreases.

**Expected behavior**

The next resizes *do* push the last character outside the terminal window.

**Screenshots**

![gif](https://user-images.githubusercontent.com/8505073/107390043-94274500-6af7-11eb-8567-c854196ec187.gif)

**Environment**

 - Vim version: 8.2 Included patches: 1-2488
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(365)

**Additional context**

It is useless for a single character to remain visible.  It would make more sense for it to be pushed outside the terminal window, just like all the rest of the text in the popup.  It would be also useful to better emulate virtual text.

**Comment by lacygoill** [comment]
The following snippet doesn't require any interactive keypress:
```vim
vim9
set nowrap
rightb vnew
setline(1, 'some special word')
prop_type_add('textprop', {})
prop_add(1, 6, {type: 'textprop', length: 7})
popup_create('attached to "special"', {
    textprop: 'textprop',
    highlight: 'ErrorMsg',
    line: -1,
    wrap: false,
    fixed: true,
    padding: [0, 0, 0, 6],
    mask: [[1, 6, 1, 1]],
    })
exe 'vert res -' .. (winwidth(0) - strchars('some special '))
```
Notice that there is a trailing `a` character which is highlighted right after the word `special`.  I think it should not be there.  Instead the following space character should remain visible.

**Comment by brammool** [comment]
it may look a bit strange in this example, but it is intended.  When the popup doesn't fit on the screen then padding is reduced, so that it can still show the user it exists. It might not be the best solution, but it's not completely wrong either.
