### ISSUE TITLE
au TerminalOpen * call setbufvar(...) does not work

### ISSUE THREAD

**Issue by fedorenchik** [vim/vim#7811]
**Describe the bug**
As described in documentation `:h options-in-terminal`:
`au TerminalOpen * call setbufvar(+expand('<abuf>'), '&colorcolumn', 123)`
should be run, but it does not get executed when switching to terminal buffer later.

Both `setbufvar(...)` and `setwinvar(...)` don't work.

Or `au TerminalOpen` does not work.

Tested in both terminal & GTK3 GUI.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean` or `gvim --clean`
2. `:au TerminalOpen * call setbufvar(+expand('<abuf>'), '&colorcolumn', 123)`
3. `:terminal ++hidden`
4. `:bnext`
5. `^W N`
6. `:set colorcolumn?`
7. Observe setting is not set.

**Expected behavior**
Settings are set and autocommands are run.

**Environment (please complete the following information):**
 - Vim version 8.2.2489
 - OS: Manjaro KDE
 - Terminal: Konsole and GTK3 GUI.

**Comment by lacygoill** [comment]
The example is wrong, and [it's my fault](https://github.com/vim/vim/issues/7362#issuecomment-733672169), sorry.  `'colorcolumn'` is a window-local option; it doesn't make sense to set it with `setbufvar()`.  But at the time, I had difficulties finding a good example of a useful buffer-local option for a terminal buffer.  I think I found one: `'termwinscroll'`.  So, this patch would improve the example:
```diff
diff --git a/runtime/doc/terminal.txt b/runtime/doc/terminal.txt
index 5885cb197..87cbe6575 100644
--- a/runtime/doc/terminal.txt
+++ b/runtime/doc/terminal.txt
@@ -130,7 +130,7 @@ options specifically for the terminal window and buffer.  Example: >
 There is also the |TerminalOpen| event, but this may be triggered for a hidden
 terminal, and the current window and buffer may not be for the new terminal.
 You need to use <abuf>, which is set to the terminal buffer.  Example: >
-    au TerminalOpen * call setbufvar(+expand('<abuf>'), '&colorcolumn', 123)
+    au TerminalOpen * call setbufvar(+expand('<abuf>'), '&termwinscroll', 1234)
 
 Mouse events (click and drag) are passed to the terminal.  Mouse move events
 are only passed when Vim itself is receiving them.  For a terminal that is
```
---

Now, regarding your issue, you can't use `setbufvar()`, because `'colorcolumn'` is not a buffer-local option.  You should use `setwinvar()` (or maybe `settabwinvar()`); but you can't, because at the time `TerminalOpen` is fired, your hidden terminal buffer has no window yet.  You need to delay the setting until the window has been created.  This should work:
```vim
au TerminalOpen * exe printf('au BufWinEnter <buffer=%d> ++once setl cc=%d', +expand('<abuf>'), 123)
terminal ++hidden
```
Note that the `+` prefix trick to coerce a string into a number only works in Vim script legacy.  In Vim9, you need `str2nr()`:
```vim
vim9
au TerminalOpen * exe printf('au BufWinEnter <buffer=%d> ++once setl cc=%d', expand('<abuf>')->str2nr(), 123)
terminal ++hidden
```

**Comment by lacygoill** [comment]
Maybe we should include 2 examples; one for a buffer-local option, and another one for a window-local option:
```diff
diff --git a/runtime/doc/terminal.txt b/runtime/doc/terminal.txt
index 5885cb197..0d0825009 100644
--- a/runtime/doc/terminal.txt
+++ b/runtime/doc/terminal.txt
@@ -130,7 +130,14 @@ options specifically for the terminal window and buffer.  Example: >
 There is also the |TerminalOpen| event, but this may be triggered for a hidden
 terminal, and the current window and buffer may not be for the new terminal.
 You need to use <abuf>, which is set to the terminal buffer.  Example: >
-    au TerminalOpen * call setbufvar(+expand('<abuf>'), '&colorcolumn', 123)
+    au TerminalOpen * call setbufvar(+expand('<abuf>'), '&termwinscroll', 1234)
+For a window-local option, you need to delay the setting until the terminal
+window has been created: >
+    au TerminalOpen * exe printf(
+        \    'au BufWinEnter <buffer=%d> ++once '
+        \ .. 'setlocal colorcolumn=%d',
+        \ expand('<abuf>')->str2nr(), 123
+        \ )
 
 Mouse events (click and drag) are passed to the terminal.  Mouse move events
 are only passed when Vim itself is receiving them.  For a terminal that is
```

**Comment by lacygoill** [comment]
> This should work:

You can check that it works with this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        au TerminalOpen * exe printf('au BufWinEnter <buffer=%d> ++once setl cc=%d', +expand('<abuf>'), 123)
        terminal ++hidden
        sil bn
        call feedkeys("\<c-w>N", 'nxt')
        setl cc?
    EOF
    )

**Comment by lacygoill** [comment]
> Maybe we should include 2 examples

Let's be consistent, if we use `str2nr()` in the second example, we should also use it in the first one:
```diff
diff --git a/runtime/doc/terminal.txt b/runtime/doc/terminal.txt
index 5885cb197..105917767 100644
--- a/runtime/doc/terminal.txt
+++ b/runtime/doc/terminal.txt
@@ -130,7 +130,14 @@ options specifically for the terminal window and buffer.  Example: >
 There is also the |TerminalOpen| event, but this may be triggered for a hidden
 terminal, and the current window and buffer may not be for the new terminal.
 You need to use <abuf>, which is set to the terminal buffer.  Example: >
-    au TerminalOpen * call setbufvar(+expand('<abuf>'), '&colorcolumn', 123)
+    au TerminalOpen * call setbufvar(expand('<abuf>')->str2nr(), '&termwinscroll', 1234)
+For a window-local option, you need to delay the setting until the terminal
+window has been created: >
+    au TerminalOpen * exe printf(
+        \    'au BufWinEnter <buffer=%d> ++once '
+        \ .. 'setlocal colorcolumn=%d',
+        \ expand('<abuf>')->str2nr(), 123
+        \ )
 
 Mouse events (click and drag) are passed to the terminal.  Mouse move events
 are only passed when Vim itself is receiving them.  For a terminal that is
```

**Comment by brammool** [comment]
Looks like this was a documentation problem.  I'll include the second example, that will fix it.
The example is a bit complicated, but will be helpful for someone who wants to do this.

**Comment by fedorenchik** [comment]
@lacygoill yes, this works, thank you.

**Comment by fedorenchik** [comment]
However, then this autocmd does not run when starting terminal without `++hidden`, but according to documentation, it should run.

This can be checked with:
```
vim -Nu NONE -S <(cat <<'EOF'
    au TerminalOpen * exe printf('au BufWinEnter <buffer=%d> ++once setl cc=%d', +expand('<abuf>'), 123)
    terminal
    call feedkeys("\<c-w>N", 'nxt')
    setl cc?                       
EOF         
)
```

**Comment by fedorenchik** [comment]
> However, then this autocmd does not run when starting terminal without `++hidden`, but according to documentation, it should run.
> 
> This can be checked with:
> 
> ```
> vim -Nu NONE -S <(cat <<'EOF'
>     au TerminalOpen * exe printf('au BufWinEnter <buffer=%d> ++once setl cc=%d', +expand('<abuf>'), 123)
>     terminal
>     call feedkeys("\<c-w>N", 'nxt')
>     setl cc?                       
> EOF         
> )
> ```

@brammool  @lacygoill  I've created related issue #7816 for this.
