### ISSUE TITLE
au TerminalOpen does not run when start terminal with window

### ISSUE THREAD

**Issue by fedorenchik** [vim/vim#7816]
**Describe the bug**
As described in documentation `:h TerminalOpen`:
`au TerminalOpen` should run both with `:terminal` and `:terminal ++hidden`
, but it only run with `:terminal ++hidden`.

Tested in both terminal & GTK3 GUI.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean` or `gvim --clean`
2. `:au TerminalOpen exe printf('au BufWinEnter <buffer=%d> ++once setlocal colorcolumn=40', expand('<abuf>')->str2nr())`
3. `:terminal`
4. `^W N`
5. `:set colorcolumn?`
6. Observe setting is not set.

**Expected behavior**
Settings are set and autocommands are run when open terminal with window.

**Environment (please complete the following information):**
 - Vim version 8.2.2489
 - OS: Manjaro KDE
 - Terminal: Konsole and GTK3 GUI.

**Comment by lacygoill** [comment]
I'll make more tests later, but I think that you want `TerminalWinOpen`:

    au TerminalWinOpen * setlocal colorcolumn=40

If both autocmds look too complex, you could simply listen to `BufWinEnter` and inspect `&buftype`:

    au BufWinEnter * if &buftype == 'terminal' | setlocal colorcolumn=40 | endif

**Comment by lacygoill** [comment]
> As described in documentation :h TerminalOpen:
> au TerminalOpen should run both with :terminal and :terminal ++hidden
> , but it only run with :terminal ++hidden.

`TerminalOpen` is fired both with `:terminal` and with `:terminal ++hidden`.  The reason why your code doesn't work is because `BufWinEnter` is not fired right after `:terminal`; instead, `TerminalWinOpen` is fired.

**Comment by lacygoill** [comment]
> If both autocmds look too complex, you could simply listen to BufWinEnter and inspect &buftype:
>
>     au BufWinEnter * if &buftype == 'terminal' | setlocal colorcolumn=40 | endif

Untested, but you would probably need to add `TerminalWinOpen`:

    au BufWinEnter,TerminalWinOpen * if &buftype == 'terminal' | setlocal colorcolumn=40 | endif

---

Here is the list of events fired after `:terminal`:

    WinLeave              abuf: 1
    WinNew                abuf: 1
    WinEnter              abuf: 1
    BufNew                abuf: 2
    BufAdd                abuf: 2
    BufLeave              abuf: 1
    BufEnter              abuf: 2
    BufWinEnter           abuf: 2
    BufFilePre            abuf: 2
    BufFilePost           amatch: !/usr/local/bin/zsh
                          afile: !/usr/local/bin/zsh
                          abuf: 2
    TerminalOpen          amatch: !/usr/local/bin/zsh
                          afile: !/usr/local/bin/zsh
                          abuf: 2
    TerminalWinOpen       amatch: !/usr/local/bin/zsh
                          afile: !/usr/local/bin/zsh
                          abuf: 2

Here is the list of events fired after `:terminal ++hidden`:

    BufNew                amatch: /home/user
                          afile: /home/user
                          abuf: 2
    BufAdd                amatch: /home/user
                          afile: /home/user
                          abuf: 2
    BufFilePre            amatch: /home/user
                          afile: /home/user
                          abuf: 2
    BufFilePost           amatch: !/usr/local/bin/zsh
                          afile: !/usr/local/bin/zsh
                          abuf: 2
    TerminalOpen          amatch: !/usr/local/bin/zsh
                          afile: !/usr/local/bin/zsh
                          abuf: 2

Here is the list of events fired after `:bn` (assuming `:terminal ++hidden` has just been executed):

    BufLeave              abuf: 1
    BufWinLeave           abuf: 1
    BufHidden             abuf: 1
    BufEnter              amatch: !/usr/local/bin/zsh
                          afile: !/usr/local/bin/zsh
                          abuf: 2
    BufWinEnter           amatch: !/usr/local/bin/zsh
                          afile: !/usr/local/bin/zsh
                          abuf: 2
    TextChanged           amatch: !/usr/local/bin/zsh
                          afile: !/usr/local/bin/zsh
                          abuf: 2

FWIW, I have [a plugin](https://github.com/lacygoill/vim-logevents) to log all the events fired by Vim (it requires tmux).

**Comment by fedorenchik** [comment]
@lacygoill Thank you. The final code that works for me is:
```viml
au TerminalWinOpen * setlocal foldcolumn=0 signcolumn=no nonumber norelativenumber
au BufWinEnter * if &buftype == 'terminal' | setlocal foldcolumn=0 signcolumn=no nonumber norelativenumber | endif
```
Sadly, can't use one autocmd for this.

**Comment by lacygoill** [comment]
I think You could merge the 2 autocmds like this:

    au TerminalWinOpen,BufWinEnter * if &buftype == 'terminal' | setlocal foldcolumn=0 signcolumn=no nonumber norelativenumber | endif

The `&buftype` guard would be useless for `TerminalWinOpen`, but it shouldn't hurt, and it's necessary for `BufWinEnter`.

Alternatively, you could wrap the settings in a function:

    au TerminalWinOpen * call MyTerminalSettings()
    au BufWinEnter * if &buftype == 'terminal' | call MyTerminalSettings() | endif

    function MyTerminalSettings() abort
        setlocal foldcolumn=0
        setlocal signcolumn=no
        setlocal nonumber
        setlocal norelativenumber
    endfunction

**Comment by fedorenchik** [comment]
@lacygoill  Thank you! :smile: 
I just leave this open for @brammool to decide if there need any change to `BufWinEnter`, `TerminalWinOpen` and `TerminalOpen` autocmds related to `:terminal ++hidden`.

**Comment by brammool** [comment]
I don't think we need to change the code, but it might help to add some comments or examples to the help.
Any suggestions?

**Comment by lacygoill** [comment]
There are 6 cases to consider:

   1. setting a buffer-local option in a non-hidden terminal buffer
   2. setting a window-local option in a non-hidden terminal buffer
   3. setting a buffer-local option in a hidden terminal buffer
   4. setting a window-local option in a hidden terminal buffer
   5. setting a buffer-local option in any kind of terminal buffer (hidden or non-hidden)
   6. setting a window-local option in any kind of terminal buffer (hidden or non-hidden)

`1.` and `2.` can be handled by `TerminalWinOpen`, and this is already documented:

    au TerminalWinOpen * setlocal bufhidden=hide
    au TerminalWinOpen * setlocal colorcolumn=123

`3.` and `5.` can be handled by `TerminalOpen`, and this also already documented (although the example should use a buffer-local option, instead of a window-local one):

    au TerminalOpen * call setbufvar(+expand('<abuf>'), '&termwinscroll', 123)

`4.` and `6.` can be handled by a combination of `TerminalOpen` + `BufWinEnter`; this is currently not documented:

    au TerminalOpen * exe printf('au BufWinEnter <buffer=%d> ++once setlocal colorcolumn=123', expand('<abuf>')->str2nr())

I think this should cover all cases, but it makes the help tag a bit verbose:
```diff
diff --git a/runtime/doc/terminal.txt b/runtime/doc/terminal.txt
index 5885cb197..7b3bc0743 100644
--- a/runtime/doc/terminal.txt
+++ b/runtime/doc/terminal.txt
@@ -130,7 +130,20 @@ options specifically for the terminal window and buffer.  Example: >
 There is also the |TerminalOpen| event, but this may be triggered for a hidden
 terminal, and the current window and buffer may not be for the new terminal.
 You need to use <abuf>, which is set to the terminal buffer.  Example: >
-    au TerminalOpen * call setbufvar(+expand('<abuf>'), '&colorcolumn', 123)
+    au TerminalOpen * call setbufvar(expand('<abuf>')->str2nr(), '&termwinscroll', 123)
+For a window-local option, you need to delay the setting until the terminal
+window has been created: >
+    au TerminalOpen * exe printf(
+        \ 'au BufWinEnter <buffer=%d> ++once setlocal colorcolumn=%d',
+        \ expand('<abuf>')->str2nr(),
+        \ 123
+        \ )
+Note that this only works for a hidden terminal.  For a non-hidden terminal,
+use |TerminalWinOpen|.  For any kind of terminal and any kind of options, try
+this: >
+    au TerminalWinOpen,BufWinEnter * if &buftype == 'terminal'
+        \ | setlocal bufhidden=hide colorcolumn=123
+        \ | endif
 
 Mouse events (click and drag) are passed to the terminal.  Mouse move events
 are only passed when Vim itself is receiving them.  For a terminal that is
```

**Comment by lacygoill** [comment]
The problem with the last example, is that it doesn't set a buffer-local option until a window has been created.  For a hidden terminal buffer, it might matter if the user wants the option to be set immediately.

**Comment by brammool** [comment]
Thanks, I'll include the examples.
