### ISSUE TITLE
Show number of matches on the fly

### ISSUE THREAD

**Issue by Sebastian-Nielsen** [vim/vim#7817]
Is it possible to have Vim automatically update the number of matches as you type out the regex search query? As opposed to it only showing the number of matches when you hit enter?

**Comment by bfrg** [comment]
I use the following function to add number of matches and the match the cursor is currently on to my statusline:
```vim
function statusline#searchcount() abort
    if !v:hlsearch
        return ''
    endif

    try
        const count = searchcount({'maxcount': 0, 'timeout': 50})
    catch /^Vim\%((\a\+)\)\=:\%(E486\)\@!/
        return '[?/??]'
    endtry

    return count.total
            \ ? count.incomplete
            \   ? printf('[%d/??]', count.current)
            \   : printf('[%d/%d]', count.current, count.total)
            \ : '[0/0]'
endfunction
```
The function is called in `statusline#main()` which I set to `'statusline'` in my `vimrc`. So something like:
```vim
" File: autoload/statusline.vim
function statusline#main() abort
    " Other parts of statusline ...
    let stl ..= '%{statusline#searchcount()}'
    return stl
endfunction

" In my vimrc
set statusline=%!statusline#main()
```

Screenshot:
![screenshot-2021-02-11_124028](https://user-images.githubusercontent.com/6266600/107632318-a07de000-6c66-11eb-9f08-523564eeaf2b.png)

**Comment by bfrg** [comment]
There's also a plugin that displays the number of matches in a popup window: https://github.com/obcat/vim-hitspop

**Comment by brammool** [comment]
The problem for a generic solution is: Where to show the count?  Either it requires a statusline or some kind of overlay on the window text.  There may not be space on the command line itself.  There are other complications, such as it has to be asynchronous to avoid a lag in typing the pattern.
Since there is a plugin for those users who really want it, I rather not implement this in code.

**Comment by Sebastian-Nielsen** [comment]
@bfrg Thank you for your response.
 
When I run: `:call statusline#main()` I get this error: (Now that I think about it that might be expected since the function only is expected to be run when you are typing out a search query)

![image](https://user-images.githubusercontent.com/34586104/107679793-4b10f580-6c9d-11eb-9e69-10dca8d31310.png)

Anyways, it doesn't work ... 
![image](https://user-images.githubusercontent.com/34586104/107680153-c4104d00-6c9d-11eb-9ad6-c9c2684f819f.png)

**Comment by bfrg** [comment]
@Sebastian-Nielsen 
You're getting an error because I gave you only a snippet of the function `statusline#main()`. The above was only meant as an example. Try the following here:
```vim
set statusline=%<%f\ %h%m%r\ %{statusline#searchcount()}%=%-14.(%l,%c%V%)\ %P
```
This will add the number of matches to the default statusline.

**Comment by Sebastian-Nielsen** [comment]
@bfrg I assume that line is supposed to substitute the `set statusline=%!statusline#main()` function in `.vimrc`. Having done that, there is still no match count on the fly: (I did remember to save the .vimrc file)

I haven't altered anything in statusline.vim file at all, its content is as depicted on the image I sent earlier.
![image](https://user-images.githubusercontent.com/34586104/107684984-bd84d400-6ca3-11eb-9fbe-340d53e15b7f.png)

**Comment by bfrg** [comment]
You need to add `set laststatus=2` to enable the statusline.

**Comment by Sebastian-Nielsen** [comment]
@bfrg Thank you, we're almost there! For some reason though, it always only displays question marks (no matter the search query), any idea why?

![image](https://user-images.githubusercontent.com/34586104/107686818-f9209d80-6ca5-11eb-82c8-8f8aa476aa44.png)

Edit:
- I tried increasing `'maxcount'` in `statusline.vim` to no avail

**Comment by bfrg** [comment]
You need to add `scriptversion 4` at the top of the script-file that contains the `statusline#searchcount()` function.

**Comment by Sebastian-Nielsen** [comment]
@bfrg 
Hmm, it still doesn't seem to work. 

I tried with both `'maxcount': 0` and `'maxcount': 50`

![image](https://user-images.githubusercontent.com/34586104/107692750-8d423300-6cad-11eb-9074-138954a7a7e2.png)

I tried moving the `count = searchcount(...)` statement out of the try catch to see the error message. 
![image](https://user-images.githubusercontent.com/34586104/107697466-8b7b6e00-6cb3-11eb-8118-0ade7a8799dc.png)

I am not sure how to resolve that error.

**Comment by bfrg** [comment]
Which Vim version do you have? `searchcount()` was added in 8.2.0877.

**Comment by Sebastian-Nielsen** [comment]
@bfrg

> Which Vim version do you have? `searchcount()` was added in 8.2.0877.

My version was `8.1` before. I just updated the version to `8.2` now. ([following this tutorial](https://ubuntuhandbook.org/index.php/2019/12/install-vim-8-2-ubuntu-18-04-16-04-19-10/))

```
sebastian@ubuntu:~$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 08 2021 14:00:27)

```

Unfortunately, I still get the same error:

![image](https://user-images.githubusercontent.com/34586104/107743675-99f87280-6d11-11eb-80f6-3b47c6a885f0.png)

**Comment by bfrg** [comment]
You need to show us the included patches, for example:
```
$ vim --version | head -2
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 12 2021 04:05:19)
Included patches: 1-2501
```

**Comment by Sebastian-Nielsen** [comment]
Oh right, here you go: 
```
sebastian@ubuntu:~$ vim --version 
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 11 2021 23:59:16)
Included patches: 1-2501
```

**Comment by bfrg** [comment]
Can you move the `searchcount()` call outside of the try-catch block so that we can see what error is emitted?

**Comment by Sebastian-Nielsen** [comment]
@bfrg 
There is no error now, but now there is also no "match display" printed anymore

This is the `.vim/autoload/statusline.vim` file:
![image](https://user-images.githubusercontent.com/34586104/107774916-ed81b500-6d3f-11eb-9a9e-e482aa8b30e2.png)

I still got these two lines in my `.vimrc` file as you told me to:

```
set statusline=%<%f\ %h%m%r\ %{statusline#searchcount()}%=%-14.(%l,%c%V%)\ %P
set laststatus=2                                                             
```

**Comment by bfrg** [comment]
Can you try it with this modification:
```vim
function statusline#searchcount() abort
    if !v:hlsearch
        return ''
    endif

    try
        const count = searchcount({'maxcount': 0, 'timeout': 50})
    catch /^Vim\%((\a\+)\)\=:\%(E486\)\@!/
        return '[?/??]'
    endtry

    if empty(count)
        return ''
    endif

    return count.total
            \ ? count.incomplete
            \   ? printf('[%d/??]', count.current)
            \   : printf('[%d/%d]', count.current, count.total)
            \ : '[0/0]'
endfunction
```

**Comment by Sebastian-Nielsen** [comment]
Hmm, there is still no match display shown 

(again, I did remember to save the file before writing out the search query)

![image](https://user-images.githubusercontent.com/34586104/107777505-325b1b00-6d43-11eb-92b3-81e24af371da.png)

**Comment by bfrg** [comment]
After you saved the file, you need to either restart Vim or resource the file with `:source %`.

**Comment by Sebastian-Nielsen** [comment]
> After you saved the file, you need to either restart Vim or resource the file with `:source %`.

Yeah, sorry, that was what I meant I did. 

Anyways, I appreciate your help buddy, I feel like we're almost there.

**Comment by bfrg** [comment]
I really don't know why it doesn't work on your computer. Maybe someone else can take a look at this.

The following works on my system:
```bash
$ vim --clean test.vim -S test.vim
```
with
```vim
" test.vim
function Searchcount() abort
    if !v:hlsearch
        return ''
    endif

    try
        const cnt = searchcount({'maxcount': 0, 'timeout': 50})
    catch /^Vim\%((\a\+)\)\=:\%(E486\)\@!/
        return '[?/??]'
    endtry

    if empty(cnt)
        return ''
    endif

    return cnt.total
            \ ? cnt.incomplete
            \   ? printf('[%d/??]', cnt.current)
            \   : printf('[%d/%d]', cnt.current, cnt.total)
            \ : '[0/0]'
endfunction

set laststatus=2
set hlsearch
set incsearch
set statusline=%<%f\ %h%m%r\ %{Searchcount()}%=%-14.(%l,%c%V%)\ %P
```
You can put this into your `vimrc` and try it again. 

Notice that I removed the `scriptversion 4`. If we do so, we need to rename the variable `count` because `v:count` is a built-in variable. Prefixing Vim variables with `v:` is optional in `scriptversion < 3`  (see `:help scriptversion-3` for more details), therefore `count` can't be used as a variable name, unless we prefix it with an `l:`.

**Comment by Sebastian-Nielsen** [comment]
**That works!**  

Thank you so much. 

![image](https://user-images.githubusercontent.com/34586104/107782023-de533500-6d48-11eb-90dc-01d943df793d.png)
