### ISSUE TITLE
vim9script: segmentation fault when a function parameter of type 'func' is called inside map() or filter()

### ISSUE THREAD

**Issue by bfrg** [vim/vim#7821]
**Describe the bug**
Vim crashes when a function parameter of type `func` is called inside `map()` or `filter()` in vim9script.

**To Reproduce**
Run `vim --clean -S test.vim`, with
```vim
vim9script
def Test(Fun: func(number): number): list<number>
    return map([1, 2, 3], (_, i) => Fun(i))
enddef
defcompile
```

Result:
```
Vim: Caught deadly signal SEGV
Vim: Finished.

Segmentation fault
```

The following works though:
```vim
vim9script
def Test(Fun: func(number): number): list<number>
    const X = Fun
    return map([1, 2, 3], (_, i) => X(i))
enddef
defcompile
```

**Environment**
Vim version `8.2.2501`

**Additional context**
I find it unusual that function parameters of type `func` need to be capitalized. Will this ever be changed? Similar is true for (local) variables of type `func`.

**Comment by lacygoill** [comment]
- [backtrace](https://github.com/vim/vim/files/5970169/backtrace.txt)
- [valgrind log](https://github.com/vim/vim/files/5970170/valgrind.log)
- [asan log](https://github.com/vim/vim/files/5970168/asan.log)

---

Regression introduced in [8.2.2002](https://github.com/vim/vim/releases/tag/v8.2.2002).

**Comment by lacygoill** [comment]
> I find it unusual that function parameters of type func need to be capitalized. Will this ever be changed? Similar is true for (local) variables of type func.

Yes, it's on [my list](https://github.com/lacygoill/wiki/blob/master/bug/vim.md#-50) of things which I'm monitoring.  There is also a [todo item](https://github.com/vim/vim/blob/f785aa1354208f6b644e891aa01f8f86d947af7e/runtime/doc/todo.txt#L72-L74).

I don't know what's best.  I *think* that – in Vim script legacy – the purpose of this requirement was to avoid the funcref to shadow a builtin function.  Not sure what [other programming languages do](https://github.com/vim/vim/commit/4072ba571babd733d1800c082416fe8fe3c28ed7#r45375881).
