### ISSUE TITLE
clipboard+=unnamed does not affect paste

### ISSUE THREAD

**Issue by jlittlenz** [vim/vim#7822]
The default (for X) "exclude:cons\|linux" phrase in the 'clipboard' option stops the "unnamed" phrase from affecting paste with 'p':

1. Run `vim --clean`
2. Type three lines:
    alfa
    bravo
    charlie
3. On the first line, type `"*yy`
4. On the third, type `yy`
5. `:set clipboard+=unnamed`
6. Type `p` - "charlie" is pasted, "alfa" was expected
7.  `:set clipboard=autoselect,unnamed,exclude:cons\|linux`
8. Type '`p` - "alfa" is pasted, correctly

vim version 8.2.2466, Ubuntu 20.10, xterm and konsole.

**Comment by vim-ml** [comment]
On 2021-02-11, John Little wrote:
> The default (for X) "exclude:cons|linux" phrase in the 'clipboard' option stops
> the "unnamed" phrase from affecting paste with 'p':
> 
>  1. Run vim --clean
>  2. Type three lines:
>     alfa
>     bravo
>     charlie
>  3. On the first line, type "*yy
>  4. On the third, type yy
>  5. :set clipboard+=unnamed

Instead, try

    :set clipboard^=unnamed

Note the last lines of ":help 'clipboard' where it says for the
"exclude:{pattern}" option/name:

    The rest of the option value will be used for {pattern}, this
    must be the last entry.

See also

    :help :set^=

>  6. Type p - "charlie" is pasted, "alfa" was expected
>  7. :set clipboard=autoselect,unnamed,exclude:cons\|linux
>  8. Type 'p - "alfa" is pasted, correctly
> 
> vim version 8.2.2466, Ubuntu 20.10, xterm and konsole.

Regards,
Gary

**Comment by jlittlenz** [comment]
Gary:
    The rest of the option value will be used for {pattern}, this
    must be the last entry.
I looked for something like that, repeatedly, but didn't see it.  Thank you.
