### ISSUE TITLE
gvim colortable on Windows BGR instead of RGB

### ISSUE THREAD

**Issue by freeo** [vim/vim#783]
Compiled on Win 7 64 with MinGW 64, gcc 4.9.2.

I've noticed in 5487544fa5d46af9f8f98aa4f5c59074a6e0639a that the colors were displayed wrong. 

It's a global rendering issue, RGB colors are interpreted as BGR. I've reverted back to 674127e1801fd02ff07dddf0dc3bf0d8cce68997 which displays the colors as expected.

**Comment by k-takata** [comment]
Already reported at here: https://groups.google.com/d/topic/vim_dev/t7uZx3jCp14/discussion
Patch is also available.

**Comment by lakewalker** [comment]
i swap r and b
term.c: 6071
#define TORGB(r, g, b) ((b<<16) | (g<<8) | (r))
this bug make all color scheme terriable

**Comment by chrisbra** [comment]
known problem, closing.
