### ISSUE TITLE
vim9script: type mismatch with getqflist() and extend()

### ISSUE THREAD

**Issue by bfrg** [vim/vim#7833]
**Describe the bug**
Type mismatch when a dictionary returned by `getqflist()` is extended with `extend()`.

**To Reproduce**
1. Run `vim --clean test.vim -S test.vim`, with
   ```vim
   vim9script
   def Test()
       var test: dict<any> = getqflist({'lines': ['foo.vim:1:2: test'], 'efm': '%f:%l:%c:%m'})
       extend(test, {'id': 1})
   enddef
   Test()
   ```
2. Result:
   ```
   E1013: Argument 2: type mismatch, expected dict<list<dict<any>>> but got dict<number>
   ```
3. The following works though:
   ```vim
   vim9script
   def Test()
       var test: dict<any> = getqflist({'lines': ['foo.vim:1:2: test'], 'efm': '%f:%l:%c:%m'})
       test['id'] = 1
   enddef
   Test()
   ```

**Environment:**
Vim version `8.2.2505`

**Comment by lacygoill** [comment]
I've also found this issue, and I agree it's unexpected.  But I don't think it can easily be fixed.  See [here for the rationale](https://github.com/vim/vim/issues/7655#issuecomment-757874370).

Basically, with `map()` and `extend()`, Vim doesn't care with which type you declared the variable; I *think* that they infer the type from the value, and then they check whether the new value has a different type.  If it has, an error is raised.  The workaround is to use a `*new()` function, like `mapnew()`, `extendnew()` and `flattennew()`.

For example:
```vim
vim9
def Test()
    var test: dict<any> = getqflist({'lines': ['foo.vim:1:2: test'], 'efm': '%f:%l:%c:%m'})
    test = extendnew(test, {'id': 1})
enddef
Test()
```
Maybe my understanding is wrong though.

**Comment by lacygoill** [comment]
Relevant excerpt from the help:

https://github.com/vim/vim/blob/8d4be8901139f698c7919fd697d82abb1ce41911/runtime/doc/vim9.txt#L1023-L1027

But maybe the help should also say that when passing a variable, the type with which the latter was declared does not matter.  Only the type inferred at runtime from the value matters.
