### ISSUE TITLE
Capital 'V' letter in regex `%V` seems to trigger smartcase in very magic mode

### ISSUE THREAD

**Issue by rminehan** [vim/vim#7845]
**Describe the bug**

Including `\%V` in an otherwise lowercase pattern makes it case sensitive even if `smartcase` is on if you use `%V` and very magic mode.

**To Reproduce**

1. Run `vim --clean`.

2. Create a buffer with text like:

```
abc
ABC
Abc
```

3. Do `:set ignorecase smartcase`.

4. Visually select the text and hit escape (so that it's the most recently selected text with respect to `gv`)

5. Do a search: `/\v%Vabc` (ie search for text "abc" starting in the last visually selected area - see `:help /\%V`)

6. Only "abc" is matched. Effectively it's a case sensitive search.

**Expected behavior**

I expected it to match all 3 words ("abc", "ABC" and "Abc").

Based on my understanding: the search term `abc` is lowercase and `ignorecase` is on, meaning the search should be case insensitive. `smartcase` _shouldn't_ switch the search to be case sensitive as there's no literal uppercase letter in the pattern.

**Environment**
 - Vim version 8.0.1453
 - Operating system/version: Ubuntu 18.04.5 LTS and Macos Big Sur
 - Terminal name/version: Standard default ubuntu gnome terminal and default macos terminal

**Additional context**

I think that the capital 'V' in `%V` is causing the `smartcase` setting to change the search to be case sensitive. When I turn off `smartcase` and rerun the test I get all 3 matches.

If you do the equivalent search without the "very magic" flag and escape the `%V` instead (ie. `/\%Vabc`) it finds 3 matches, so I'm guessing there's logic inside smartcase for handling capital letters when they're part of an explicit `\` escape sequence (but not when unescaped).

The help for smartcase doesn't explicitly say whether "capital letters" are just for literal capital letters but I'm pretty sure that was the intention, particularly as that's how it works when an escaped `\%V` is used. So I'm fairly confident it's a bug as smartcase shouldn't be affected by whether you're using very magic or regular magic mode. If this _is_ the intended behavior it would be helpful to make that clear in the help docs for smartcase as it has implications for very magic mode: you have to explicitly put a `\c` in your pattern if you want it to ignore case.

Neovim has the same behavior. I originally posted [there](https://github.com/neovim/neovim/issues/13837) and they redirected me to post an issue here.

**Comment by brammool** [comment]
It's because the code skips over \%V but not %V, it doesn't respect \v  for "very magic" mode.
If someone wants to look into fixing this, the code is in pat_has_uppercase().
