### ISSUE TITLE
Termguicolors disables terminal transparency, and ability to set custom fg/bg without side effects

### ISSUE THREAD

**Issue by poetaman** [vim/vim#7849]
Enabling truecolors (``set termguicolors``) disables transparency of "terminal" buffer/window region in vim. Also, setting ``&t_8b`` to some reasonable (r,g,b) value disables syntax coloring all of vim.

**To Reproduce**
1. Launch terminal that supports true colors on macOS (iTerm2, WezTerm, Alacritty, etc)
2. Set some transparency (method varies by terminal)
2. ```>>vim -u termguicolor.vim termguicolor.vim```
3. Run command ``:terminal`` from within vim
 
Contents of file ``termguicolor.vim``:
```vim
set nocompatible
set encoding=utf-8
set noswapfile nobackup
syntax enable
if exists('+termguicolors')
  set background=dark
  set t_Co=256
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
  "Following two lines help to change the color of terminal
  "but they also disable syntax, and requires 'tput reset'
  "for colors to be avialable again in terminal
  "let &t_8f= printf("\<Esc>[38;2;%lu;%lu;%lum",225,225,225)
  "let &t_8b= printf("\<Esc>[48;2;%lu;%lu;%lum",20,30,67)
  set termguicolors
endif
```

**Expected behavior**
Enabling truecolors in terminal should not affect transparency of windows running ``:terminal`` within vim. There should be a option that has an effect similar to ``hi ctermbg=NONE guibg=NONE`` for instead of ``let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"``. Finally setting, a custom value like ``let &t_8b= printf("\<Esc>[48;2;%lu;%lu;%lum",20,30,67)`` should not cause syntax colors to completely get disabled.

> As a sidenote: ``:terminal`` window within vim in non-truecolor mode works well. I have never encountered any problems with transparency, and it also automatically inherits theme of vim. Ideally that should be how truecolor support be too...

**Screenshots**

<img width="1317" alt="Screen Shot 2021-02-14 at 10 22 36 PM" src="https://user-images.githubusercontent.com/71736629/107912761-f75c1180-6f13-11eb-9873-8214577bba01.png">

<img width="1322" alt="Screen Shot 2021-02-14 at 10 23 41 PM" src="https://user-images.githubusercontent.com/71736629/107912775-fb882f00-6f13-11eb-88cb-8d7bffd05844.png">

**System information**

```
>> neofetch
                   'c.           reportaman@Mac-mini.local
                 ,xNMM.          ------------------------------
               .OMMMMo           OS: macOS 11.2 20D64 arm64
               OMMM0,            Host: Macmini9,1
     .;loddo:' loolloddol;.      Kernel: 20.3.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 4 hours, 40 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 1 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.8
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 2880x1620
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Blue (Dark)
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: WezTerm
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   CPU: Apple M1
    kMMMMMMMMMMMMMMMMMMMMMMd     GPU: Apple M1
     ;KMMMMMMMWXXWMMMMMMMk.      Memory: 1980MiB / 16384MiB
       .cooc,.    .,coo:.



```

**Comment by nickspoons** [comment]
This is unfortunately an old issue, see #2361

**Comment by chrisbra** [comment]
closing as duplicate
