### ISSUE TITLE
GVim 32bits Build fails under new version of MSYS2 msys2-x86_64-20210105 and GCC version 10.2.0

### ISSUE THREAD

**Issue by niva-xx-zz** [vim/vim#7852]
**Describe the bug**
GVim 32bits Build fails with new MSYS2 32bits following installPC.txt instructions section MSYS

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Download installer: msys2-x86_64-20210105.exe from https://www.msys2.org/
2. Git Clone last version of https://github.com/vim/vim under /c/foobar/source/vim
3.  Follow instruction of Msys2 Build in vim/src/installPC.txt section MSYS
     configured as ![image](https://user-images.githubusercontent.com/747998/107965805-41dc9d00-6fab-11eb-95cf-1cce78a16f28.png)

4.  Try to launch gvim.exe and dependency exception appears:
From Ken Takata, `libgcc_s_dw2-1.dll is required when vim is compiled by a recent version of 32-bit GCC gcc version 10.2.0, even if STATIC_STDCPLUS=yes is specified`

**Screenshots**
If applicable, copy/paste the text or add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/747998/107965892-5faa0200-6fab-11eb-8b02-9fa65ab0358b.png)

**Environment (please complete the following information):**
 - Vim version [e.g. 8.2.2516] (Or paste the result of `vim --version`.)
 - OS: Windows 10 64bits
 - MSYS2 msys2-x86_64-20210105.exe 
 - GCC version 10.2.0

**Comment by chrisbra** [comment]
So copying the dll is not an option? It should come with your compiler (e.g. MSYS2).  Alternatively `-static-libgcc -static-libstdc++` to your compiler flags should also work I think

**Comment by k-takata** [comment]
> GVim 32bits Build fails with new MSYS2 32bits

I don't want to say it is failing. It just requires additional dependency.

> Alternatively `-static-libgcc -static-libstdc++` to your compiler flags should also work I think

Unfortunately, it didn't work when I tried before.
It would be nice if someone finds a way to remove the dependency on the DLL.

**Comment by chrisbra** [comment]
Perhaps this needs to be reported to msys2 then. Does this only happen with gcc 10.2?

**Comment by k-takata** [comment]
I think it depends on the version of gcc.

**Comment by niva-xx-zz** [comment]
Maybe under Msys2 just trying to downgrade version of gcc, too many dependencies..: 

 pacman -U http://repo.msys2.org/msys/i686/gcc-9.3.0-1-i686.pkg.tar.xz

![image](https://user-images.githubusercontent.com/747998/108032244-79daf300-7032-11eb-96d4-2ce21348ab90.png)
![image](https://user-images.githubusercontent.com/747998/108034662-2074c300-7036-11eb-8f75-3585dcbfc1a6.png)

**Comment by niva-xx-zz** [comment]
ByPass done to Build GVim 8.2.2519 under MSYS2 32bits versions

![image](https://user-images.githubusercontent.com/747998/108054287-be748780-704e-11eb-8e78-c14f2ecc6f73.png)


1. Install MSYS2 Version msys2-x86_64-20201109.exe and launch MSYS2 in 32bits mode
2. Update packages to build  _pacman -S base-devel mingw-w64-i686-toolchain as described byt MSYS Section in installPC.txt_
3. make -f Make_ming.mak ${FLAGS} DEBUG=no with FLAGS="OLE=yes GUI=yes XPM=no DIRECTx=yes DYNAMIC_LUA=yes LUA=./lua-5.3.5/src LUA_VER=53 PYTHON3=/c/Python38-32 DYNAMIC_PYTHON3=yes PYTHON3_VER=38 RUBY=C:/Ruby27 DYNAMIC_RUBY=no RUBY_VER=27 RUBY_API_VER_LONG=2.7.0 TERMINAL=yes EVENT_LOOP=yes STATIC_STDCPLUS=yes" WINVER=0x600

Deployment needs to copy **some dll** at root of gvim.exe

- libgcc_s_dw2-1.dll
- libgmp-10.dll
- libssp-0.dll
- libwinpthread-1.dll

**Comment by k-takata** [comment]
If you don't want any dependancy dlls, using MSVC is the easiest workaround for now.

**Comment by k-takata** [comment]
Okay, I investigated the issue.

The problem is that the `__umoddi3` function in `libgcc_s_dw2-1.dll` is used indirectly.
The recent versions of mingw64 define `__USE_MINGW_ANSI_STDIO` to 1, and when it is defined to 1, printf-like functions from mingw64 are used, and the functions use `__umoddi3`.
Moreover, even if you add `-D__USE_MINGW_ANSI_STDIO=0` to `CFLAGS`, the `new` operator in libstdc++ uses the printf-like function and it uses `__umoddi3`.
So, the dependency on `libgcc_s_dw2-1.dll` is unavoidable.

Possible workarounds for this might be:
1. Stop using 32-bit mingw64 and migrate to 64-bit mingw64.
2. Stop using 32-bit mingw64 and migrate to MSVC.
3. Turn off DirectWrite and if_ole, and add `-D__USE_MINGW_ANSI_STDIO=0` to `CFLAGS`. Or,
4. Get the source code of `__umoddi3` and link it statically by yourself.

**Comment by k-takata** [comment]
This is not a vim issue. Closing.
