### ISSUE TITLE
Doc: 'normal' is highlighted as if it was an option name

### ISSUE THREAD

**Issue by gdupras** [vim/vim#7853]
**Describe the bug**
In `:help last-pattern`, in the file `pattern.txt`, the highlighting makes `'normal'` look like an option name.

**To Reproduce**
1. `gvim --clean`
2. `:help last-pattern`

**Expected behavior**
`'normal'` should not have any special highlighting. The fix is probably just to replace the single quotes with double quotes.

**Screenshots**
![normal](https://user-images.githubusercontent.com/57042631/108012461-6ea6a980-6fd7-11eb-9aa0-72ccc3bd3563.png)

**Environment:**
 - Vim version 8.2.2517
 - OS: Kubuntu 20.10
 - Terminal: GUI

**Comment by brammool** [comment]
Yes, using double quotes is better.
