### ISSUE TITLE
Support registering functions in embedded scripting languages as Vim functions

### ISSUE THREAD

**Issue by DemiMarie** [vim/vim#786]
It would be nice for Vimscript to be able to call other languages without just evaluating a string.

**Comment by vim-ml** [comment]
2016-05-01 21:14 GMT+03:00 Demetri Obenour vim-dev-github@256bit.org:

> It would be nice for Vimscript to be able to call other languages without
> just evaluating a string.

​That was once possible (and AFAIR implemented for Python, though not sure;
at least I wanted to implement and knew I could) with my extended-funcrefs
patch (BTW, new partials would be trivial to implement on top of that), but
it did not get enough attention and is outdated and does not work now.​

**Comment by lacygoill** [comment]
Considering that the interfaces are going to be phased out ([source](https://groups.google.com/d/msg/vim_dev/__gARXMigYE/orGEJs3PBwAJ)), I don't think this feature request is going to be implemented any time soon.

> 2. PHASING OUT INTERFACES

> Attempts have been made to implement functionality with built-in script
> languages such as Python, Perl, Lua, Tcl and Ruby.  This never gained much
> foothold, for various reasons.

> Instead of using script language support in Vim:
> - Encourage implementing external tools in any language and communicate
>   with them.  The job and channel support already makes this possible.
>   Really any language can be used, also Java and Go, which are not
>   available built-in.
> - Phase out the built-in language interfaces, make maintenance a bit easier
>   and executables easier to build.  They will be kept for backwards
>   compatibility, no new features.
> - Improve the Vim script language, so that it can be used when an
>   external tool is undesired.

> All together this creates a clear situation: Vim with the +eval feature
> will be sufficient for most plugins, while some plugins require
> installing a tool that can be written in any language.  No confusion
> about having Vim but the plugin not working because some specific
> language is missing.  This is a good long term goal.

> Rationale: Why is it easier to run a tool separately from Vim than using a
> built-in interface and interpreter?  Take for example something that is
> written in Python:
> - The built-in interface uses the embedded python interpreter.  This is less
>   well maintained than the python command.  Building Vim with it requires
>   installing developer packages.  If loaded dynamically there can be a version
>   mismatch.
> - When running the tool externally the standard python command can be used,
>   which is quite often available by default or can be easily installed.
> - A .py file can be compiled into a .pyc file and execute much faster.
> - Inside Vim multi-threading can cause problems, since the Vim core is single
>   threaded.  In an external tool there are no such problems.
> - The Vim part is written in .vim files, the Python part is in .py files, this
>   is nicely separated.
> - Disadvantage: An interface needs to be made between Vim and Python.
>   JSON is available for this, and it's fairly easy to use.  But it still
>   requires implementing asynchronous communication.

**Comment by lacygoill** [comment]
See also `:h vim9`, and look for the header `Classes`:

> Vim supports interfaces to Perl, Python, Lua, Tcl and a few others.  But
> these have never become widespread.  When Vim 9 was designed a decision was
> made to phase out these interfaces and concentrate on Vim script, while
> encouraging plugin authors to write code in any language and run it as an
> external tool, using jobs and channels.

**Comment by brammool** [comment]
Also hasn't seen activity for four years.  Let's close.
