### ISSUE TITLE
incorrect indent of *.vim file

### ISSUE THREAD

**Issue by ZSaberLv0** [vim/vim#7865]
**Describe the bug**
incorrect indent of *.vim file

**To Reproduce**
1. prepare `min.vim`

    ``` vim
    filetype plugin indent on
    syntax on
    set nocompatible
    ```

1. prepare `test.vim`

    ``` vim
    "   function! YourCppFlagsFunc()
    "     return [
    "         \   '-DDEBUG',
    "         \   '-Ipath1',
    "         \   '-Ipath2',
    "         \ ]
    "   endfunction
    ```

1. `vim -u min.vim test.vim`
1. `gg=G`

**Expected behavior**
correct indent

**Screenshots**
![image](https://user-images.githubusercontent.com/6846867/108374604-191f0680-723c-11eb-880a-fa8172624131.png)

**Environment (please complete the following information):**
 - Vim version: 8.2.2500, installed by MacOS's brew
 - OS: MacOS 11.2
 - Terminal: MacOS's builtin terminal, Putty

**Comment by brammool** [comment]
The check for being inside a comment was wrong, I'll fix it.

**Comment by ZSaberLv0** [comment]
``` vim
let t = [
            \   {
            \   'a' : 'a',
            \   'b' : 'b',
            \   },
            \ ]
```
![image](https://user-images.githubusercontent.com/6846867/175451894-f90bd76c-1e2d-4124-b7bc-dd373e00d6cf.png)

still not work for this case (`vim -u min.vim test.vim`)

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun 22 2022 18:08:38)
macOS version - x86_64
Included patches: 1-5150
Compiled by Homebrew
```

**Comment by brammool** [comment]
Do you mean that the second backslash should not have more indent, or that the indent should be reduced after the closing curly?

**Comment by brammool** [comment]
I think it's best to align the backslashes.  Could perhaps adjust the indent after that. Later.

**Comment by ZSaberLv0** [comment]
all of the backslash should be aligned

**Comment by ZSaberLv0** [comment]
![image](https://user-images.githubusercontent.com/6846867/175755445-9475b978-aa1c-4f5d-8817-bb5c3c75e4e3.png)

seems has other strange issue, the red area has "inaccessable tab", the cursor (the green block) can't move to the red area (can't by any means, `0` or `h`), and `echo getpos('.')` reports `[0, 2, 1, 0]`
however, with `set expandtab`, or with `set list`, it's alright

---

![image](https://user-images.githubusercontent.com/6846867/175756007-a4d01084-5fa1-41f8-8ed2-de8684875909.png)

another issue, the first backslash on line 2 has 3 tabs, which was 2 tabs on old vim version, seems no reason to have so many indents. `min.vim`:

```
filetype plugin indent on
syntax on
set nocompatible
set number
set noexpandtab
set list
set listchars=tab:>\ ,trail:-,extends:>,precedes:<,nbsp:+
highlight Whitespace ctermfg=White guifg=White
```

**Comment by brammool** [comment]
When moving the cursor onto a Tab, it will be displayed on the last position, that is normal.

You can change the amount of indent with 'shiftwidth'.  For Vim script a value of 2 or 3 works well.

**Comment by dkearns** [comment]
> another issue, the first backslash on line 2 has 3 tabs, which was 2 tabs on old vim version, seems no reason to have so many indents

You can control that by setting `g:vim_indent_cont` which defaults to 3 and has done so since at least 2003.  Perhaps you had the variable set in the older version?
