### ISSUE TITLE
CPU usage 100% when typing 

### ISSUE THREAD

**Issue by chenziliang** [vim/vim#7866]
Hi,

**Describe the bug**
I am using vim to edit C++ files (the C++ project itself is big and has lots of files), but sometimes vim cpu usage went up to 100% and got frozen. Initially i suspected it may be related to VIM plugins I installed, so i tried to remove all plugins, but no luck. I upgraded VIM to latest 8.2 version, still no luck.

May I ask if there are further troubleshooting steps i can try to collect more information ?

**To Reproduce**
Detailed steps to reproduce the behavior:
1. vim <c++ source file>
2. type c++ code
3. vim freeze (cpu usage is 100%)

**Expected behavior**
vim shall not freeze

**Screenshots**
If applicable, copy/paste the text or add screenshots to help explain your problem.

**Environment (please complete the following information):**
 - Vim version [e.g. 8.1.1234] (Or paste the result of `vim --version`.)

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 08 2021 14:00:27)
Included patches: 1-2311
Modified by jonathon.fernyhough@york.ac.uk
Compiled by jonathon.fernyhough@york.ac.uk
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
-autoservername    +folding           +multi_byte        +termguicolors
-balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
-browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              -perl              +title
-clientserver      +job               +persistent_undo   -toolbar
-clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           -python            +visual
+conceal           +linebreak         +python3           +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       -lua               -ruby              +wildmenu
+dialog_con        +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
-dnd               +mouse             +sound             -xfontset
-ebcdic            -mouseshape        +spell             -xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              +mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -Wdate-time -g -O2 -fdebug-prefix-map=/build/vim-aswg2n/vim-8.2.2311=. -fstack-protector-strong -Wformat -Werror=format-security -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: gcc -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim -lm -ltinfo -lselinux -lcanberra -lacl -lattr -lgpm -ldl -L/usr/lib/python3.8/config-3.8-x86_64-linux-gnu -lpython3.8 -lcrypt -lpthread -ldl -lutil -lm -lm 
```
 - OS: [e.g. Ubuntu 18.04, Windows 10 1809, macOS 10.14]
 Ubuntu 20.04

 - Terminal: [e.g. GNOME Terminal, mintty, iTerm2, tmux, GNU screen] (Use GUI if you use the GUI.)
 tmux

**Comment by lacygoill** [comment]
> May I ask if there are further troubleshooting steps i can try to collect more information ?

Assuming that your vimrc was not only containing plugins, and you didn't already reproduce with no config (`-Nu NONE` or `--clean`), I would start by minimizing the vimrc.  See [here](https://github.com/chrisbra/vim_faq/blob/7f9c65c91d01e289a92b9e43a70ee2becadd66ce/vim_faq.txt#L1153-L1228) for how to do so.

In your vimrc, you might need to enable the filetype detection:

    filetype on

And maybe the filetype plugins too:

    filetype plugin on

Or maybe the indent plugins:

    filetype indent on

Or maybe both:

    filetype plugin indent on

And you might need to enable syntax highlighting:

    syntax enable

Once you get a minimal vimrc, you could profile Vim to get more info about which commands consume most of the time:

    :prof start profile.log
    :prof func *
    :prof file *
    " At this point do whatever is necessary to reproduce the issue/slowness
    :prof pause
    :noa qall!

Then read or post the contents of the `profile.log` file.  See [this answer](https://stackoverflow.com/questions/12213597/how-to-see-which-plugins-are-making-vim-slow/12216578#12216578).

**Comment by chenziliang** [comment]
Thanks a lot, @lacygoill . Will give it a try

**Comment by lacygoill** [comment]
Any update?

**Comment by chenziliang** [comment]
Hi @lacygoill, sorry for late response. I played around the debugging tips above. It appeared that the problem lied in YouCompleteMe plugin and after removing this plugin, the CPU usage remained normal. Please feel free to close this one and i will reopen it with more debug info it really comes back. 

Thanks again for your help and followup. It was very helpful.

**Comment by dpelle** [comment]
@chenziliang wrote:

> It appeared that the problem lied in YouCompleteMe plugin and after removing this plugin, the CPU usage remained normal. 

I also use the YouCompleteMe vim Plugin with C++ and the latest Vim, and I do not see this issue.
Try to upgrade YouCompleteMe?  I do it regularly using:

```
$ ~/.vim/plugged/YouCompleteMe
$ git pull
$ CC=clang-12 CXX=clang-12 ./install.sh --clang-completer --clangd-completer
```
If you still see the issue, consider reporting to https://github.com/ycm-core/YouCompleteMe.
