### ISSUE TITLE
Vim9: cannot use "true" for "border" key in "{opts}" dictionary of "popup_create()"

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7869]
**Describe the bug**

In Vim9 script, we cannot use `true` for the `border` key in the `{opts}` dictionary of `popup_create()`.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        popup_create('', {border: [false, true, false, true]})
    EOF
    )

`E1138` is raised 4 times:

    E1138: Using a Bool as a Number

**Expected behavior**

No error is raised, because `border` expects a list of boolean numbers:

   > border          List with numbers, defining the border thickness
   >                 above/right/below/left of the popup (similar to CSS).
   >                 Only values of zero and non-zero are recognized.

**Environment**

 - Vim version: 8.2 Included patches: 1-2529
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(366)

**Additional context**

Regression introduced in 8.2.1465.

**Comment by brammool** [comment]
As the help indicates, this is a list of numbers.  Currently only zero and non-zero are supported, but in the future we may actually support thicker borders.

**Comment by lacygoill** [comment]
> in the future we may actually support thicker borders.

OK, I didn't know this.

---

And what about the `cursorline` key?  It also expects a boolean number, and this time, I doubt it will expect other numbers like 2 or 3 in the future.
```vim
vim9script
popup_create('', {cursorline: true})
```
    E475: Invalid value for argument cursorline

**Comment by brammool** [comment]
> > in the future we may actually support thicker borders.
> 
> OK, I didn't know this.
> 
> ---
> 
> And what about the `cursorline` key?  It also expects a boolean number, and this time, I doubt it will expect other numbers like 2 or 3 in the future.
> ```vim
> vim9script
> popup_create('', {cursorline: true})
> ```
>     E475: Invalid value for argument cursorline

That should indeed be a boolean or zero or one.
It has a bit of a strange value check.  Let's use the standard way for a
bool option.

-- 
A hamburger walks into a bar, and the bartender says: "I'm sorry,
but we don't serve food here."

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
