### ISSUE TITLE
Setting conceal level above 0 in vimrc causes gvim to skip donation screen.

### ISSUE THREAD

**Issue by li-ruijie** [vim/vim#7871]
Gvim appears to insert a character on load and thereby skipping the initial donation screen if I set conceal level to  1 or 2.

OK:
`gvim -u NONE +'set conceallevel=0'`

Skip donation screen:
`gvim -u NONE +'set conceallevel=1`
`gvim -u NONE +'set conceallevel=2`

This behaviour is not seen in terminal vim.

Tested on:
vim-gtk3 2:8.2.2434-1, Debian testing (updated 2021-02-19)
gvim 8.2.2529, windows 10x64 Pro.

**Comment by tonymec** [comment]
Try adding the following anywhere in your vimrc:
```vim
augroup vimrc
  au VimEnter * intro
augroup END
```

Best regards,
Tony.

**Comment by brammool** [comment]
It is hard to avoid, anything that causes a redraw will make the intro message disappear.  I don't think it is worth trying to avoid this.
