### ISSUE TITLE
Vim9: omitting whitespace after Ex command can give confusing error message

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7874]
**Describe the bug**

In Vim9 script, omitting a whitespace after an Ex command name can give a confusing error message.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        setline(1, ['pat', 'xxx', 'pat'])
        exe "norm! ggVG\e"
        :'<,'>keeppatterns s/pat/rep/
    EOF
    )

`E1144` is raised:

    E1144: Command is not followed by white space: keeppatterns s/pat/rep/

This is actually expected, but it's not that obvious why.

Indeed, in the error message, "Command" *seems* to refer to `:keeppatterns`, which makes us think that we forgot a whitespace after the latter.  That's not the case; we did not forget a whitespace after `:keeppatterns`.  In reality, "Command" refers to `:k` (alias of `:mark`).

**Expected behavior**

To avoid any confusion, the error message should separate the command name from the rest; maybe like this:

    E1144: Command ":k" is not followed by white space: eeppatterns s/pat/rep/

**Environment**

 - Vim version: 8.2 Included patches: 1-2529
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(366)

**Additional context**

A whitespace between an Ex command name and its argument(s) is enforced since [8.2.2138](https://github.com/vim/vim/commit/b5b9480ee936ef4cd0e350c468ef8c5f42fa398b).

**Comment by lacygoill** [comment]
Also, I wonder whether `:k` should be deprecated in Vim9 script, just like `:a`, `:c`, `:i`, `:x`, and `:t`:

   > No :xit, :t, :append, :change or :insert~
   >
   > These commands are too easily confused with local variable names.
   > Instead of `:x` or `:xit` you can use `:exit`.
   > Instead of `:t` you can use `:copy`.

If we want to mark a line, we can still use the much more readable `:mark` command.

**Comment by lacygoill** [comment]
The only difference between `:k` and `:mark` is that the whitespace can be omitted after the former.  But that's irrelevant in Vim9, since it's disallowed to do that for any Ex command.

**Comment by lacygoill** [comment]
BTW, I know that passing a range to `:keeppatterns` is wrong; but I think it's necessary here to show how Vim can sometimes print a confusing error message.

**Comment by tonymec** [comment]
In legacy Vim,
```vim
:1,$keeppatterns s/pat/rep
```
gives me
```
E488: Trailing characters: eeppatterns s/pat/rep
```
I get the same error E488 (with a shorter text at the end, of course) if the `:substitute` command is omitted. Maybe that would be enough?

Best regards,
Tony.

**Comment by lacygoill** [comment]
> Maybe that would be enough?

Yes, it would also be an improvement over the current message.

**Comment by lacygoill** [comment]
I think deprecating `:k` was good in the general case, but in this specific case, the error message is still confusing:
```vim
vim9script
setline(1, ['pat', 'xxx', 'pat'])
exe "norm! ggVG\e"
:'<,'>keeppatterns s/pat/rep/
```
    E1100: Command not supported in Vim9 script (missing :var?): keeppatterns s/pat/rep/

It looks like `:keeppatterns` is not supported in Vim9.  It is.  The issue is that – because of the range – Vim thinks that the initial `k` in `keeppatterns` is the `:k` command.  And the suggestion "missing :var?" does not help, because there is no variable named `keeppatterns` which shadows the Ex command.

**Comment by lacygoill** [comment]
Although, it's probably a corner case which doesn't warrant more attention.

**Comment by lacygoill** [comment]
Ideally, the command name would be separated from the rest in the message:

    E1100: Command ":k" not supported in Vim9 script (missing :var?): eeppatterns s/pat/rep/

**Comment by lacygoill** [comment]
> Ideally, the command name would be separated from the rest in the message:

Actually, the ideal solution would be to raise `E481`:

    E481: No range allowed: :'<,'>keeppatterns

That was not possible before, because `:k` was still allowed in Vim9.  But since it's no longer allowed, Vim should not infer that `k` in `keeppaterns` is `:k`; it should use the whole command name and thus raise `E481`.

---

I've also noticed that `:open` is a bit obscure:

   > This command is in Vi, but Vim only simulates it:
   > [...]
   > Vim does not support open mode, since it's not really useful.

Maybe it should be deprecated in Vim9 too.  I'll make more tests later, and open separate issues.

**Comment by lacygoill** [comment]
> Maybe it should be deprecated in Vim9 too.

Because it can be shortened into `:o` and I wonder whether that can cause other confusing error messages.

**Comment by lacygoill** [comment]
> Because it can be shortened into :o and I wonder whether that can cause other confusing error messages.

Obviously, we cannot deprecate all Ex commands which can be shortened down to a single character, but if they are not useful in Vim9, it might be useful to deprecate them to avoid this kind of issue.
