### ISSUE TITLE
incorrect syntax highlighting with unabbrev, cunabbrev and iunabbrev vim commands

### ISSUE THREAD

**Issue by dpelle** [vim/vim#7876]
**Describe the bug**

vim syntax highlighting does not correctly highlight commands:
`unabbrev`, `cunabbrev` and `iunabbrev`.

**To Reproduce**

1) create a file `foo.vim` containing:
```
abbrev <buffer> foo foobar
cabbrev <buffer> cfoo cfoobar
iabbrev <buffer> cfoo cfoobar

" Bug: unabbrev, cunabbrev and iunabbrev are incorrectly
" highlighted.
unabbrev <buffer> foo
cunabbrev <buffer> cfoo
iunabbrev <buffer> ifoo
```

2) open `foo.vim` with:
```
$ vim --clean foo.vim
```

3) observe the incorrect syntax highlighting: `<buffer>` is highlighted
differently in `abbrev` and `unabbrev` as depicted in the following screenshot:

![unabbrev-highlight-before-fix](https://user-images.githubusercontent.com/2261629/108586402-8f139280-734e-11eb-8a46-7bf9acc8d77d.png)

**Expected behavior**

I would expect that `<buffer>` is highlighted similarly in `abbrev` and `unabbrev`
commands as `vimMapModKey` group.

**Proposed Patch**

Following patch fixes it:
```
diff --git a/runtime/syntax/vim.vim b/runtime/syntax/vim.vim
index d900c5e78..c91c36ffb 100644
--- a/runtime/syntax/vim.vim
+++ b/runtime/syntax/vim.vim
@@ -397,7 +397,7 @@ VimFoldh syn region vimLetHereDoc   matchgroup=vimLetHereDocStart start='=<<\s\+\%
 
 " Abbreviations: {{{2
 " =============
-syn keyword vimAbb     ab[breviate] ca[bbrev] inorea[bbrev] cnorea[bbrev] norea[bbrev] ia[bbrev] skipwhite nextgroup=vimMapMod,vimMapLhs
+syn keyword vimAbb     ab[breviate] una[bbreviate] ca[bbrev] cuna[bbrev] inorea[bbrev] cnorea[bbrev] norea[bbrev] ia[bbrev] iuna[bbrev] skipwhite nextgroup=vimMapMod,vimMapLhs
 
 " Autocmd: {{{2
 " =======
```
After patch:
![unabbrev-highlight-after-fix](https://user-images.githubusercontent.com/2261629/108586506-4e684900-734f-11eb-98b4-886e40f011e3.png)

I emailed the maintainer @cecamp.

**Environment**

 - Vim: 8.2.2530
 - OS: 
xubuntu-18.04.5

**Comment by brammool** [comment]
@cecamp
