### ISSUE TITLE
cursorline causes an extra column to be highlighted

### ISSUE THREAD

**Issue by cwfoo** [vim/vim#7883]
**Describe the bug**
When using `set cursorline` with `cursorlineopt` set to either `both`, `line`, or `screenline`, an extra column will be highlighted on the cursor's line when using `matchadd()` to highlight multiple lines.  The problem does not occur when `set cursorline` is used with `set cursorlineopt=number`.

**To Reproduce**

Good behavior (without `set cursorline`):
1. Run `vim --clean`
2. Insert a few lines of text into the buffer.
3. `:call matchadd('Visual', '\_.*')`. Result:
    
    ![Correct highlighting of lines](https://user-images.githubusercontent.com/11555232/108606479-3f3bd680-73f5-11eb-8a09-d597c2a59c38.png)
    This is expected behavior.

Bad behavior (with `set cursorline`):
1. Run `vim --clean`
2. `:set cursorline`
3. Insert a few lines of text into the buffer.
4. Position the cursor on the first line of the buffer and `:call matchadd('Visual', '\_.*')`. Result:
    
    ![Wrong highlighting of lines (extra column is highlighted)](https://user-images.githubusercontent.com/11555232/108606406-e5d3a780-73f4-11eb-8c6d-5441789006a0.png)

5. Exit Vim, repeat steps 1-3, position the cursor on the second line of the buffer and `:call matchadd('Visual', '\_.*')`. Result:

    ![Wrong highlighting of lines (an extra column is highlighted)](https://user-images.githubusercontent.com/11555232/108606438-1287bf00-73f5-11eb-99be-07da7414a80d.png)

    Notice how an extra column is highlighted at the end of the cursor's line.

**Expected behavior**
There should be no extra highlighted column at the end of the cursor's line.

**Environment**
 - Vim version: 8.1.2269
 - OS: Ubuntu 20.04
 - Terminal: GNOME Terminal

**Comment by brammool** [comment]
Interestingly, when matching with ".*" then it's the other way around,  at the cursor line the last character is not highlighted.

**Comment by cwfoo** [comment]
> Interestingly, when matching with ".*" then it's the other way around, at the cursor line the last character is not highlighted.

Screenshot of `:set cursorline | call matchadd('Visual', '.*')`:

![Incorrect highlighting](https://user-images.githubusercontent.com/11555232/108612933-d02ba580-7427-11eb-98e9-b4c63c90a88f.png)

**Comment by brammool** [comment]
I would argue that searching for "\_.*" includes the line separator, thus highlighting the extra character would be correct.  Thus the highlight in the cursor line is OK.  Other lines stop too early.
".*" actually does not include the line separator, but after matching the whole line of  text there is an empty match at the end of the line, and for an empty match one character extra is highlighted. ".\+" does not have the extra match.  I managed to fix that part, the other one is not so easy.
