### ISSUE TITLE
Vim9: crash when type mismatch error raised from lambda on BufReadPost

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7884]
**Describe the bug**

In Vim9 script, a type mismatch error raised from a lambda run on `BufReadPost` might make Vim crash.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        sil e /tmp/file
        var bufnr = bufnr('%')
        var d = {[bufnr]: {a: {b: 0}}}
        au BufReadPost * Func()
        def Func()
            var abuf: string = expand('<abuf>')
            if d->has_key('')
            endif
            eval d[abuf]->mapnew((__, v: dict<job>) => v.b)
        enddef
        e
    EOF
    )

Vim crashes.

**Expected behavior**

Vim doesn't crash.

**Environment**

 - Vim version: 8.2 Included patches: 1-2536
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(366)

**Additional context**

- [backtrace](https://github.com/vim/vim/files/6017233/backtrace.txt)
- [valgrind log](https://github.com/vim/vim/files/6017234/valgrind.log)

Vim doesn't crash when instrumented by asan, and the latter doesn't give any info.

**Comment by lacygoill** [comment]
Ah, I forgot that `/tmp/file` needed to exist for the crash to occur.  New MWE:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        writefile([], '/tmp/file')
        sil e /tmp/file
        var bufnr = bufnr('%')
        var d = {[bufnr]: {a: {b: 0}}}
        au BufReadPost * Func()
        def Func()
            var abuf: string = expand('<abuf>')
            if d->has_key('')
            endif
            eval d[abuf]->mapnew((__, v: dict<job>) => v.b)
        enddef
        e
    EOF
    )

**Comment by lacygoill** [comment]
Simplified a bit more:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        writefile([], '/tmp/file')
        sil e /tmp/file
        var d = {[bufnr('%')]: {a: 0}}
        au BufReadPost * Func()
        def Func()
            if d->has_key('')
            endif
            var abuf: string = expand('<abuf>')
            eval d[abuf]->mapnew((_, v: dict<job>) => 0)
        enddef
        e
    EOF
    )

**Comment by lacygoill** [comment]
Simplified again:
```vim
vim9script
writefile([], '/tmp/file')
sil e /tmp/file
var d = {[bufnr('%')]: {a: 0}}
au BufReadPost * Func()
def Func()
    if d->has_key('')
    endif
    eval d[expand('<abuf>')]->mapnew((_, v: dict<job>) => 0)
enddef
e
```

**Comment by LemonBoy** [comment]
```patch
diff --git a/src/list.c b/src/list.c
index 2af3085cc..c7d8113a3 100644
--- a/src/list.c
+++ b/src/list.c
@@ -2136,6 +2136,8 @@ filter_map(typval_T *argvars, typval_T *rettv, filtermap_T filtermap)
 		    int		r;
 		    typval_T	newtv;
 
+		    newtv.v_type = VAR_UNKNOWN; // clear_tv() uses this
+
 		    --todo;
 		    di = HI2DI(hi);
 		    if (filtermap == FILTERMAP_MAP
```

There are a few more uses of `clear_tv` on possibly uninitialized `typval_T` variables.
