### ISSUE TITLE
Typo in usr_04

### ISSUE THREAD

**Issue by xalexalex** [vim/vim#7888]
Hey, this is a very quick one:

https://github.com/vim/vim/blob/6bfc475f717aa0412d13163d47ff6210fa611fb5/runtime/doc/usr_04.txt#L467

should be either "to make a correction" or "to make corrections".

Thanks!

**Comment by brammool** [comment]
Alessandro Caputo wrote:

> Hey, this is a very quick one:
> 
> https://github.com/vim/vim/blob/6bfc475f717aa0412d13163d47ff6210fa611fb5/runtime/doc/usr_04.txt#L467
> 
> should be either "to make a correction" or "to make corrections".

"a correction" sounds correct.  Thanks!

-- 
BROTHER MAYNARD: Armaments Chapter Two Verses Nine to Twenty One.
ANOTHER MONK:    And St.  Attila raised his hand grenade up on high saying "O
                 Lord bless this thy hand grenade that with it thou mayest
                 blow thine enemies to tiny bits, in thy mercy. "and the Lord
                 did grin and people did feast upon the lambs and sloths and
                 carp and anchovies and orang-utans and breakfast cereals and
                 fruit bats and...
BROTHER MAYNARD: Skip a bit brother ...
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by gdupras** [comment]
Fixed in 9faec4e.
