### ISSUE TITLE
Crash when resize window with terminal & WinBar

### ISSUE THREAD

**Issue by fedorenchik** [vim/vim#7890]
**Describe the bug**
(G)Vim crashes when resize window to min size with terminal in 'Terminal Job' mode and WinBar.

**To Reproduce**

1. Run `vim --clean` or `gvim --clean`
2. `^Ws` to split window 
3. `^Wj` to focus window below
4. `:an 1.1 WinBar.test :`
5. `:terminal ++curwin`
6. `^Wk` to focus window above
7. `^W_` to maximize current window size
8. observe vim prints errors & crash:
```
E341: Internal error: lalloc(0, )
E341: Internal error: lalloc(0, )
Press ENTER or type command to continue
E341: Internal error: lalloc(0, )
Press ENTER or type command to continue
E341: Internal error: lalloc(0, )
Press ENTER or type command to continue

Vim: Caught deadly signal SEGV
Vim: Finished

Segmentation fault (core dumped)
```

**Expected behavior**
No crash.

**Environment (please complete the following information):**
 - Vim version: 8.2.2489
 - OS: Manjaro Gnome 3.38.3
 - Terminal: `kitty` and `GTK3 GUI`.

**Additional Info**
1. Does not happen if terminal is in 'Terminal Normal' mode.
2. Does not happen without WinBar in terminal window.
3. Does not happen if terminal window is focused.

**Comment by lacygoill** [comment]
- [backtrace](https://github.com/vim/vim/files/6026541/backtrace.txt)
- [valgrind log](https://github.com/vim/vim/files/6026542/valgrind.log)
- [asan log](https://github.com/vim/vim/files/6026539/asan.log)
