### ISSUE TITLE
"{{{{{{{{" and "}" can be inserted by cmdline-completion

### ISSUE THREAD

**Issue by obcat** [vim/vim#7904]
**Describe the bug**
`{{{{{{{{` and `}` can be inserted by cmdline-completion.

**To Reproduce**

1. Run `vim --clean`.
1. Type `:` to start cmdline-mode:
    ```vim
    :
    ```
    
1. Press <kbd>Tab</kbd><kbd>CTRL-P</kbd><kbd>CTRL-P</kbd><kbd>CTRL-P</kbd>:
    ```vim
    :}
    ```

1. Press <kbd>CTRL-P</kbd> again:
    ```vim
    :{{{{{{{{
    ```

**Expected behavior**
These are not inserted by cmdline-completion.

**Environment**
 - Vim 8.2.2549
 - macOS Catalina (version 10.15.7)
 - iTerm2

**Comment by lacygoill** [comment]
`{` and `}` start and end a block in Vim9 script.  They were added in the patch [8.2.1826](https://github.com/vim/vim/releases/tag/v8.2.1826).

However, I don't know why `{{{{{{{{` is considered as an Ex command:
https://github.com/vim/vim/blob/0e62a6742bca186624e97e2121c98ada30e009a0/src/ex_cmds.h#L1822-L1824

Also, not sure how useful it is for `{` and `}` to be suggested on the command-line.  I can't find a usage example:

    :vim9 { echo 'inside a block' }
    E720: Missing colon in Dictionary:  'inside a block' }

In a script, `{` and `}` should be on separate lines.  Usually, to emulate a newline on the command-line, we can press `C-v C-j`:

    :fu Func()^@endfu

but it doesn't work here:

    :vim9 {^@echo 'inside a block'^@}
    E488: Trailing characters: ^@echo 'inside a block'^@}

**Comment by Shane-XB-Qian** [comment]
perhaps can be used for foldlevel mark, e.g `" LOAD GUARD {{{1`, though no `}}}1`, 
but most users may have auto-fill for `{` to `{}`, another hand `}` would not auto-fill normally...
// just a Guess.. :-)

**Comment by brammool** [comment]
Fixed by patch 8.2.2552

**Comment by brammool** [comment]
> `{` and `}` start and end a block in Vim9 script.  They were added in the patch [8.2.1826](https://github.com/vim/vim/releases/tag/v8.2.1826).
> 
> However, I don't know why `{{{{{{{{` is considered as an Ex command:
> https://github.com/vim/vim/blob/0e62a6742bca186624e97e2121c98ada30e009a0/src/ex_cmds.h#L1822-L1824

I forgot why I did it that way.  Just using "{" should work.  Tests
pass.  Let me change it.

> Also, not sure how useful it is for `{` and `}` to be suggested on the command-line.  I can't find a usage example:
> 
>     :vim9 { echo 'inside a block' }
>     E720: Missing colon in Dictionary:  'inside a block' }

Yeah, it's more for consistency than that it's useful.

> In a script, `{` and `}` should be on separate lines.  Usually, to
> emulate a newline on the command-line, we can press `C-v C-j`:
> 
>     :fu Func()^@endfu
> 
> but it doesn't work here:
> 
>     :vim9 {^@echo 'inside a block'^@}
>     E488: Trailing characters: ^@echo 'inside a block'^@}

Using {} for blocks is for when writing a script.  Typing them is hardly
ever useful.  Still, it should work.  Ah, the EX_TRLBAR flag is missing.

-- 
The Law, in its majestic equality, forbids the rich, as well as the
poor, to sleep under the bridges, to beg in the streets, and to steal
bread.                       -- Anatole France

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by obcat** [comment]
Thanks for fixing!🎉
