### ISSUE TITLE
lightyellow is missing from the Vim syntax file

### ISSUE THREAD

**Issue by cwfoo** [vim/vim#7906]
**Describe the bug**
"lightyellow" is missing from the [Vim syntax file](https://github.com/vim/vim/blob/0abc6e471ae78167bd75f95603b9bdd27ff0b38f/runtime/syntax/vim.vim). As a result, "lightyellow" will be incorrectly highlighted as an error.

**To Reproduce**
1. Run `vim --clean mytest.vim`
2. Insert: `highlight Search ctermbg=lightyellow`
3. Observations:
    * `lightyellow` is highlighted as an error:
        ![Vim highlight lightyellow](https://user-images.githubusercontent.com/11555232/109389206-7d318100-7946-11eb-93e6-b8fe1e18e3fb.png)
    * `:echon map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')` on any of the 11 letters of `lightyellow` prints `['vimHiKeyList', 'vimHiCtermError']`.
    * (As requested by the maintainer) Using the [HiLinks](http://www.drchip.org/astronaut/vim/index.html#HILINKS) plugin's `:HLT!` command and moving across all 11 letters of `lightyellow` results in this:
        ```
        SynStack:  vimHiKeyList->vimHiCtermError       HltTrace: vimHiCtermError->vimError->Error    fg<15> bg<9>
        ```
       The same output appears for all 11 letters of `lightyellow`.

**Expected behavior**
`lightyellow` should not be highlighted as an error because it is a valid color (refer to `:help cterm-colors`).

**Environment**
 - Vim version: 8.1.2269
 - OS: Ubuntu 20.04
 - Terminal: GNOME Terminal

@cecamp (maintainer). I have also sent an email to the maintainer.

**Comment by cecamp** [comment]
I've fixed the missing "lightyellow" issue, plus included a few more colors which I gleaned from vim's source code. Closing...
