### ISSUE TITLE
Incorrect data type used for %u

### ISSUE THREAD

**Issue by davidsilveiro** [vim/vim#791]
in **runtime/tools/ccfilter.c line 312** requires an unsigned integer :)

**Comment by brammool** [comment]
David Silveiro wrote:

> in **runtime/tools/ccfilter.c line 312** requires an unsigned integer :) 

Thanks.  Must have been there for many years.  I think this works:

```
    printf( "[%u]?%s\n", (unsigned)ok, Line );
```

## 

SOLDIER: What? A swallow carrying a coconut?
ARTHUR:  It could grip it by the husk ...
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by davidsilveiro** [comment]
@brammool 
Just learned something new with that fix of yours, so it was an equal trade ^_^ Thanks for taking the time!
