### ISSUE TITLE
Clarify documentation of :sc and friends

### ISSUE THREAD

**Issue by Abraxas-Knister** [vim/vim#7911]
I've recently stumbled across [:sc](https://github.com/vim/vim/blob/087b5ff35d219f4f48a3d4854783799d0f6a1732/runtime/doc/change.txt#L881) and friends in the docs and frankly couldn't really make sense of that section in change.txt. After some digging and asking I found an explanation in [:&](https://github.com/vim/vim/blob/087b5ff35d219f4f48a3d4854783799d0f6a1732/runtime/doc/change.txt#L647-L651) and would now like to give the following suggestion to make it a little bit clearer (line numbers refer to change.txt)

- add a help tag `*sub-repeat*` to line 880
- add some text to line 881, referring to the `*:&*` tag and do not make it a heading. Something like   

    Table of two and three lettered :substitute commands that can be obtained by
    ommiting a space between :s and its flags, see |:&|. Combinations that would
    be recognized as abbreviations for other EX commands are omitted in the table.

- remove line 883
- in the table (lines 884-893) change dashes to spaces
- add some text after line 651, referring to the new `*sub-repeat*`, like:

    When omitting a space between :s and the flags, some combinations could be
    recognized as abbreviations for other commands, see |sub-repeat|.

**Comment by lacygoill** [comment]
Attempt at a patch based on the OP's comments:
```diff
diff --git a/runtime/doc/change.txt b/runtime/doc/change.txt
index 7db3ffc41..523eb1d0d 100644
--- a/runtime/doc/change.txt
+++ b/runtime/doc/change.txt
@@ -649,6 +649,9 @@ For other systems the tmpnam() library function is used.
                        The space between `:substitute` and the 'c', 'g',
                        'i', 'I' and 'r' flags isn't required, but in scripts
                        it's a good idea to keep it to avoid confusion.
+			When omitting a space between :s and the flags, some
+			combinations could be recognized as abbreviations for
+			other commands, see |sub-repeat|.
 
 :[range]~[&][flags] [count]					*:~*
                        Repeat last substitute with same substitute string
@@ -877,20 +880,22 @@ either the first or second pattern in parentheses did not match, so either
                *:sge* *:sgi* *:sgI* *:sgl* *:sgn* *:sgp* *:sgr* *:sI* *:si*
                *:sic* *:sIc* *:sie* *:sIe* *:sIg* *:sIl* *:sin* *:sIn* *:sIp*
                *:sip* *:sIr* *:sir* *:sr* *:src* *:srg* *:sri* *:srI* *:srl*
-		*:srn* *:srp*
-2-letter and 3-letter :substitute commands ~
+		*:srn* *:srp* *sub-repeat*
+
+Table of two and three lettered :substitute commands that can be obtained by
+ommiting a space between :s and its flags, see |:&|. Combinations that would
+be recognized as abbreviations for other EX commands are omitted in the table.
 
-     List of :substitute commands
      |      c    e    g    i    I    n    p    l    r
-     | c  :sc  :sce :scg :sci :scI :scn :scp :scl  ---
+     | c  :sc  :sce :scg :sci :scI :scn :scp :scl     
      | e
      | g  :sgc :sge :sg  :sgi :sgI :sgn :sgp :sgl :sgr
-     | i  :sic :sie  --- :si  :siI :sin :sip  --- :sir
+     | i  :sic :sie      :si  :siI :sin :sip      :sir
      | I  :sIc :sIe :sIg :sIi :sI  :sIn :sIp :sIl :sIr
      | n
      | p
      | l
-     | r  :src  --- :srg :sri :srI :srn :srp :srl :sr
+     | r  :src      :srg :sri :srI :srn :srp :srl :sr
 
 Exceptions:
      :scr  is  `:scriptnames`
```

**Comment by Abraxas-Knister** [comment]
Brilliant, thanks!

**Comment by brammool** [comment]
Thanks, I'll include it and tweak it a bit.
