### ISSUE TITLE
Change Go syntax provider

### ISSUE THREAD

**Issue by 89z** [vim/vim#7917]
Currently this Go syntax is used:

https://github.com/google/vim-ft-go

However this syntax hasnt been updated in several years. In addition, it has some
problems. For example, it doesnt even recognize underscore in integer literals.
Here is an alternative that is popular and up to date:

https://github.com/fatih/vim-go

**Comment by brammool** [comment]
Please file an issue for the vim-ft-go repository, explaining what the problems are.
Or ask them to drop it and direct to the other one.
It's not good if every Vim users has to figure out which one to use.

**Comment by 89z** [comment]
Sorry I was not clear, I am suggesting to change this file:

https://github.com/vim/vim/blob/master/runtime/syntax/go.vim

to this one:

https://github.com/fatih/vim-go/blob/master/syntax/go.vim

I can do a pull request if that is acceptable

**Comment by brammool** [comment]
I now notice that vim-ft-go already points to the fatih/vim-go repository.  Could be a bit more explicit.  Or perhaps the vim-ft-go repository should be archived to avoid confusion.

**Comment by 89z** [comment]
I think I am not being clear. These files:

- https://github.com/google/vim-ft-go/blob/master/syntax/go.vim
- https://github.com/vim/vim/blob/master/runtime/syntax/go.vim

are both old and have problems. I am suggesting to change to this newer, improved file:

https://github.com/fatih/vim-go/blob/master/syntax/go.vim

are you really saying that once a file is put here:

https://github.com/vim/vim/tree/master/runtime/syntax

that it must stay forever and never be changed? If that is the case, that is a poor design decision, as programming languages change over time. I am not suggesting it needs to be updated every day, but if you are vendoring these files in the Vim repository, you are implicitly taking responsibility for them. I think that once a year update is not much to ask. Otherwise if Vim maintainers are unwilling to do that, I think this folder should be removed completely:

https://github.com/vim/vim/tree/master/runtime/syntax

**Comment by jamessan** [comment]
> are you really saying that once a file is put here:
> 
> [https://github.com/vim/vim/tree/master/runtime/syntax](https://github.com/vim/vim/tree/master/runtime/syntax?rgh-link-date=2021-03-01T21%3A33%3A25Z)
> 
> that it must stay forever and never be changed?

No, that's not at all what's being stated.  Your suggestion is understood, but that's not how runtime updates work.

When a runtime file maintainer has updated their file(s) and considers the updates ready to be in Vim proper, then they push the updated file(s) to Bram for inclusion.

It's not up to Bram to poll every maintainer to see if they have updates.  There are over 300 syntax files.  That doesn't scale well.

**Comment by k-takata** [comment]
Explicit permission from the maintainer is required for inclusion.
And the files should be sent to Bram from the maintainer (via an email or a PR).
Please ask the maintainer about them.
