### ISSUE TITLE
:filter does not ignore case when 'ignorecase' is set

### ISSUE THREAD

**Issue by gdupras** [vim/vim#7918]
**Describe the bug**
When `'ignorecase'` is set I would expect `:filter` to ignore case in the pattern but it does not. If this is the intended behavior, I think it should be documented under `:help :filter`.

**To Reproduce**
1. `gvim --clean` (or vim)
2. `:e a`
3. `:e AA`
4. `:set ignorecase`
5. `:filter a ls` or `:filter /a/ ls`
6. Only the file "a" is shown.

**Expected behavior**
I would expect both "a" and "AA" to appear in the output.

**Environment:**
 - Vim version: 8.2.2559
 - OS: Windows 10
 - Terminal: GUI

**Additional context**
As a workaround, I can do `:filter /\ca/ ls` to ignore case but I wish that was not necessary.

**Comment by brammool** [comment]
Having 'ignorecase' apply to :filter may not be desired by other users.  It already applies to too many things.
As you mentioned, adding \c to the pattern has the desired effect.
I'll add a note that the pattern of :filter does not use 'ignorecase'.
