### ISSUE TITLE
Underscore with Python numbers

### ISSUE THREAD

**Issue by 89z** [vim/vim#7923]
None of the current Python number patterns allow for underscores:

https://github.com/vim/vim/blob/37096afd3f3133a831ab49a9677f090c3c935c9d/runtime/syntax/python.vim#L161-L170

while the standard allows for them:

https://docs.python.org/reference/lexical_analysis.html#numeric-literals

I am posting here, as I dont see an upstream repo listed:

https://github.com/vim/vim/blob/37096afd3f3133a831ab49a9677f090c3c935c9d/runtime/syntax/python.vim#L3-L6

**Comment by ProgMetalSlug** [comment]
@zvezdan

**Comment by 89z** [comment]
this might be helpful:

https://github.com/python-mode/python-mode/blob/76df35a8/syntax/python.vim#L247-L256

**Comment by zvezdan** [comment]
@89z Thank you for reporting.

I'm going through a backlog of updates that need to be added for the newer language features and decided to do them in smaller pieces starting with this one that was recently merged as a part of larger Vim runtime update: https://github.com/vim/vim/pull/7855
The last sentence in that PR is mentioning that more updates are coming.

I am using the exact regex definitions from the Python documentation that you referenced in my working copy.
This will be coming soon in a separate PR as well as some other changes and other PRs.

**Comment by chrisbra** [comment]
closing then

**Comment by 89z** [comment]
I found this as a workaround:

https://github.com/vim-python/python-syntax/blob/master/syntax/python.vim

**Comment by 89z** [comment]
For anyone interested, I added underscore support for Python and JavaScript in the linked Pull Request

**Comment by 89z** [comment]
https://github.com/vim/vim/pull/8023

**Comment by zvezdan** [comment]
The PR #8033 resolves this issue.
