### ISSUE TITLE
[compatible mode] 'Insert' mode is exited once focus is lost

### ISSUE THREAD

**Issue by zdohnal** [vim/vim#7926]
Vim exists 'Insert' mode if compatible mode is turned on and you switch into a different application and back.

How to reproduce:
0) ./configure --enable-gui=no --with-features=huge && make
1) ./src/vim -U NONE -u NONE -i NONE -c ':set compatible'
2) switch to 'Insert' mode by 'i'
3) write some text and don't leave 'Insert' mode
4) lose focus on Vim - f.e. by switching to a different window/application
5) switch back to Vim and try to write again

Actual behavior:
The insert mode is gone and you need to type 'i' again.

Expected behavior:
The insert mode stays active until user presses Esc.

Environment:
 - Vim version 8.2.2562 - compiled the current master branch from github
 - OS: Fedora 32
 - Terminal:GNOME Terminal

**Additional context**
The issue is reported by user for [Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1933594) - the behavior started with adding the feature in 8.2. 2345 and can be worked around by unsetting  ```t_fd``` and ```t_fe``` like ```:set t_fd=``` and ```:set t_fe=```.

There is an incomplete analysis in the bug, where I was able to track down the reason why the bug appears. ```check_termcode()``` uses ```typebuf``` struct for comparing with ```termcodes``` list which will determine the ```key_name``` which is used later. ```typebuf``` has a different ```tb_off``` in compatible mode and in nocompatible, which seems to cause wrong interpretation of the incoming event - so Vim will interpret FOCUS_LOST as FOCUS_GAINED.
```typebuf``` structure is used on many places and I wasn't able to track the issue further down...

Would you mind looking into it?

Thank you in advance!

Zdenek

**Comment by brammool** [comment]
This happens because in compatible mode 'esckeys' is not set.  In that case we should not enable reporting focus lost/gained.

**Comment by zdohnal** [comment]
Hi Bram,

thank you for looking into it! I compiled the latest master, but unfortunately I can still reproduce the issue.
Please let me know if you need more information.

**Comment by brammool** [comment]
Strange, it was fixed for me.  Can you avoid the problem by setting 'esckeys' before going to Insert mode?

**Comment by zdohnal** [comment]
@brammool Yes, setting 'esckeys' does the trick - I guess the fix will need some other check for p_ek somewhere else.

**Comment by brammool** [comment]
And that is with exactly the original reproduction steps?  I can not reproduce it that way.
If you actually do something else now, please say so.

**Comment by rmyorston** [comment]
I'm the user who raised the downstream issue with Fedora.

I've tried building from the latest source and confirm that the issue I reported has been fixed to my satisfaction. I also used the source to build RPMs for Fedora and again found the problem has been resolved without having to resort to workarounds.

**Comment by zdohnal** [comment]
Interesting... I cannot reproduce it now... sorry for the noise :(

**Comment by zdohnal** [comment]
Thanks for fixing it!
