### ISSUE TITLE
8.1.1241 introduces new requirement for count of custom Ex command which breaks old working scripts

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7934]
**Describe the bug**

Since 8.1.1241, when a custom command is defined with the `-range` attribute, a count is tested against a line number in the current buffer (unless `-addr=` specifies another kind of range).  This breaks old working scripts which provide custom Ex commands with a range of no specific kind.  Now, such commands need to be prefixed with a count matching an existing line in the buffer; or they need `-addr=other`.  This requirement didn't exist before.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        com -range=1 Cmd echo "the command was used with the count: " . <count>
        3Cmd
    EOF
    )

`E16` is raised:

    E16: Invalid range:     3Cmd

That's because `3` is tested against a line number.  But there's no line 3 in the current empty buffer.

**Expected behavior**

No error is raised, because the command was working before 8.1.1241.

**Environment**

 - Vim version: 8.2 Included patches: 1-2572
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(366)

**Additional context**

I suppose it's working as intended.  I think it's documented at `:h :command-addr`:

   > Possible values are (second column is the short name used in listing):
   >     -addr=lines                 Range of lines (this is the default for -range)
   >     -addr=arguments       arg   Range for arguments
   >     -addr=buffers         buf   Range for buffers (also not loaded buffers)
   >     -addr=loaded_buffers  load  Range for loaded buffers
   >     -addr=windows         win   Range for windows
   >     -addr=tabs            tab   Range for tab pages
   >     -addr=quickfix        qf    Range for quickfix entries
   >     -addr=other           ?     other kind of range; can use ".", "$" and "%"
   >                                 as with "lines" (this is the default for
   >                                 -count)

The solution now is to use the `-addr=other` attribute:
```vim
com -range=1 -addr=other Cmd echo "the command was used with the count: " . <count>
3Cmd
```
But this has broken old working scripts.  For example [`vim-scriptease`](https://github.com/tpope/vim-scriptease).  According to [@tpope](https://github.com/tpope/vim-scriptease/commit/6755d1fdb88b2b384990a0d131629b76e92831fa#commitcomment-47935200), it would still be useful it the old behavior was restored:

> it's not too late in terms of the old behavior still being worth restoring. Sometimes I want to be able to do :12345Foo, but also :$Foo! for example, where the interpretation varies based on the presence of ! or some other argument. Also restoring backwards compatibility would be helpful to users of unmaintained plugins.

I must add that the commit which introduced the regression did not change any help file.  So, I'm not sure whether the change was entirely intentional.  I mean, that a range is interpreted as a line number by default is one thing; and it has probably always been the case.  That this line number has to exist is another.

**Comment by brammool** [comment]
That patch is almost two years old.  I haven't seen complaints about making the range checking stricter.  In general, a range can be expected to be a line range, unless specified otherwise.  
Changing it now might also introduce new problems, for commands that omitted "-addr=lines" because it's already the default.
Thus I rather not change this now.
