### ISSUE TITLE
problems of meta key in terminal

### ISSUE THREAD

**Issue by ZhiyuanLck** [vim/vim#7939]
**Describe the bug**
I'm using alacritty with zsh. And I bind some keys leading with meta key. For example: `^]m` for `accept-line`. When I start vim by `vim --clean` and run `:term`, `<M-m>` works, the test by `showkey -a` also shows that `<M-m>` is accepted as `^]m`.

But I also configure the meta key in my vimrc to make meta key able to be mapped, something like
```vim
exec "set <M-".a:key.">=\e".a:key
```
with the code above, `<M-m>` in terminal is recognized as `í` rather than `^]m` so that the key bindings of the meta key does not work in zsh.

I try to solve it by clearing the setting when I enter the terminal and recovering it when I leave the termianl
```vim
  function! s:metacode(key, clear)
    if a:clear
      exec "set <M-".a:key.">="
    else
      exec "set <M-".a:key.">=\e".a:key
    endif
  endfunc

  function! s:set_meta(clear)
    for i in range(10)
      call s:metacode(nr2char(char2nr('0') + i), a:clear)
    endfor
    for i in range(26)
      call s:metacode(nr2char(char2nr('a') + i), a:clear)
      let t = nr2char(char2nr('A') + i)
      call s:metacode(t, a:clear)
    endfor
    for c in [',', '.', '/', ';', '{', '}']
      call s:metacode(c, a:clear)
    endfor
    for c in ['?', ':', '-', '_', '+', '=', "'"]
      call s:metacode(c, a:clear)
    endfor
  endfunction

  " init
  call s:set_meta(0)

  function! s:auto_meta(clear)
    if &bt == 'terminal'
      if a:clear
        call s:set_meta(1)
      else
        call s:set_meta(0)
      endif
    endif
  endfunction

  augroup TermMeta
    autocmd!
    autocmd WinEnter * call <sid>auto_meta(1)
    autocmd WinLeave * call <sid>auto_meta(0)
  augroup END
```
But then came the problem that **`<M->` mappings do not work in terminal mode**.

**Environment:**
 - Vim version 8.2.2246
 - OS: Ubuntu 20.04
 - Terminal: Alacritty with the option `send_alt_esc: false`

**Comment by nicsig** [comment]
Try this:

    fu s:fix_terminal_readline() abort
        for key in map(range(char2nr('a'), char2nr('z')) + range(char2nr('A'), char2nr('Z')), 'nr2char(v:val)')
            exe 'tno <m-' .. key .. '> <esc>' .. key
        endfor
    endfu
    call s:fix_terminal_readline()

See [this comment](https://github.com/vim/vim/issues/2397#issuecomment-750255716).

**Comment by ZhiyuanLck** [comment]
@nicsig It didn't work in console vim and I did not test it in gvim. The problems seems to be that vim send the wrong key rather than `<esc>`.

Without vim, run `showkey -a`:
`l` shows `108 0154 0x6c`, `<m-l>` (`^[l`) shows `27 0033 0x1b 108 0154 0x6c` where `27 0033 0x1b` is `<esc>`.
`m` shows `109 0155 0x6d`, `<m-m>` (`^[m`) shows `27 0033 0x1b 109 0155 0x6d` where `27 0033 0x1b` is `<esc>`.
Same is other keys.

Run vim with `vim -u NONE` or `vim --clean`, no problem, the results are the same as above.

Run vim with `exec "set <M-".a:key.">=\e".a:key`:
`m` shows `109 0155 0x6d`, `<m-m>` (`í`) shows `195 0303 0xc3 173 0255 0xad`, the strange key codes.

I tested `alt + [a-zA-Z]` and they are all shown as unregular symbols other than a compose key.

**Comment by ZhiyuanLck** [comment]
Here is the script for testing.
```vim
let symbols =  map(range(char2nr('0'), char2nr('9')), 'nr2char(v:val)')
let symbols += map(range(char2nr('a'), char2nr('z')), 'nr2char(v:val)')
let symbols += map(range(char2nr('A'), char2nr('Z')), 'nr2char(v:val)')
let symbols += [',', '.', '/', ';', '{', '}']
let symbols += ['?', ':', '-', '_', '+', '=', "'"]

for key in symbols
  exec "set <m-" .. key .. ">=\e" .. key
  exec "tnoremap <m-" .. "> <esc>" .. key
endfor
```

1. run `vim --clean -S test.vim`
2. run ex command `:term`
3. run terminal command `showkey -a`
4. test meta keys

**Comment by nicsig** [comment]
> @nicsig It didn't work in console vim

That's because you didn't run the same code I posted:

    exec "tnoremap <m-" .. "> <esc>" .. key

That's wrong.  It should be:

    exec "tnoremap <m-" .. key .. "> <esc>" .. key

**Comment by ZhiyuanLck** [comment]
> exec "tnoremap <m-" .. key .. "> <esc>" .. key

It's my fault! Thanks a lot for help!
