### ISSUE TITLE
Don't undo indents added by autoindent, perhaps add a new cpoptions character

### ISSUE THREAD

**Issue by poetaman** [vim/vim#7941]
At times I like to create a few blank lines at the right indent level, and then fill them all together later. Currently ``autoindent``, even with ``cpoptions+=I`` enabled, deletes the just added indent after hitting ``<CR>``. This way at any given point, only one blank line has the right indent level.

Example: after entering ``<CR>`` 3 times at the end of line containing  ``let hello=world``, there should be 3 indented lines below it. Then, as I move the cursor with ``<Up>/<Down>``, it should move to the position where dots ``.`` are in the following code block.
```
if foo==bar
    let hello=world
    .
    .
    .   
endif
```

**Comment by brammool** [comment]
I don't think there are more than a few users who would want to use this, adding "yet another option" is not really desired.
You can probably make it work like this:
:inoremap <CR> .<BS><CR>

**Comment by brammool** [comment]
Hmm, github eats the angle brackets.  Another try:
```vim
:inormap <CR> .<BS><CR>
```

**Comment by reportaman** [comment]
@brammool I believe you got be wrong, the full stops ``.`` are only to indicate where cursor lands if one were to press ``<Up>/<Down>`` after entering 3 ``<CR>``'s. Currently if I press ``<CR>`` thrice this is how it looks, and do ``<Up>`` the cursor moves to left column 0, and I need to hit tab again to get to reindent it.

```
if foo==bar
    let hello=world
.
.
    .   
endif
```

**Comment by poetaman** [comment]
@brammool This still doesn't fully work... Let's say after pressing ``<CR>`` three times, I hit ``<Up>`` or ``<Down>`` arrow key (with or without ``cpoptions+=I`` enabled), it deletes indent from the last line that was indented, and I end up with situation below where I need to reindent last line.

```
if foo==bar
    let hello=world
    .
    .
.   
endif
```

IMHO, not automatically un-indenting is pretty common & intuitive. If users really care about trailing whitespace, they can always visualize it, or run a vim command to delete it while saving/closing a buffer.

**Comment by vim-ml** [comment]
On 2021-03-09, reportaman wrote:
> @brammool This still doesn't fully work... Let's say after pressing <CR> three
> times, I hit <Up> arrow key, it deletes indent from the last line that was
> indented.
> 
> if foo==bar
>     let hello=world
>     .
>     .
> .
> endif

    :inormap <Up> .<BS><Up>

HTH,
Gary

**Comment by poetaman** [comment]
@vim-ml That doesn't work either, it has the same problem as in https://github.com/vim/vim/issues/7941#issuecomment-794452836. 

Actually this is what @brammool might have meant (``<BS>`` & ``<CR>`` are swapped from his mapping):

``inoremap <CR> <CR>.<BS>`` works... quite interesting business :)

**Comment by brammool** [comment]
You can use any character instead of the dot, it just means that something was inserted and the <CR> won't remove the auto-indent.  The auto-indent is removed because it looks like the user wants an empty line, and trailing white space is undesired in 99% of the cases.

**Comment by poetaman** [comment]
@brammool Thanks! As a side-note regarding predicting user intent, someone is already generating vim commands using [OpenAI GPT3 model](https://openai.com/blog/openai-api/):

https://jameslu.substack.com/p/using-gpt-3-to-generate-vim-commands

**Comment by OrestesK** [comment]
Depending on how you're creating the new line (ex. I mainly use 'o'), add a simple keymap
`vim.keymap.set('n', 'o', 'o<Left><Right>', { noremap = true, silent = true })`

**Comment by journaljemmy** [comment]
I'd like to add that the autoindent is also removed if you use the up or down arrow key after creating the new line. So it's not just ‘move and it doesn't happen’ it's ‘move left or right and it doesn't happen’. That's is an insane amount of mental overhead when all I want to do is a normal mode operation on my new autoindented line.

I think that undoing an autoindent in the first place is a terrible feature. If you want to be picky with lines that consist of spaces, they should be removed when saving the file not when I'm trying to do something in normal mode on my autoindented line. 100% of the time that an autoindent is undone, I find myself indenting as my next operation. Surely that's a massive red flag.
