### ISSUE TITLE
Setting markdown_folding in ~/.vim/after/ftplugin.markdown.vim has no effect

### ISSUE THREAD

**Issue by venthur** [vim/vim#7944]
**Describe the bug**

Setting `g:markdown_folding` in `~/.vim/after/ftplugin.markdown.vim` has no effect. I believe it is because of [this line](https://github.com/vim/vim/blob/fa79be6b10e1d34fd697a56e85f6c0ce101f3d62/runtime/ftplugin/markdown.vim#L67) in the official ftplugin.

I believe this option should effectively enable the desired behavior even if it is set in .vim/**after**/ftplugin/...

**To Reproduce**

1. put `let g:markdown_folding = 1` in `~/.vim/after/ftplugin.markdown.vim`
2. restart vim
3. edit some markdown file
4. no folding

**Expected behavior**
folding should be enabled

**Environment (please complete the following information):**
 - Vim version 8.2
 - OS: Debian/Unstable
 - Terminal: GNOME Terminal

**Comment by habamax** [comment]
If you put this in `after` then how plugin should know if folding has to be turned on or off? I mean you set it after the markdown ftplugin has been already sourced.

**Comment by venthur** [comment]
I understand and agree, but isn't it a bug in the first place to check for such an option in a way that it **can't** be affected anymore by configuring specific options in `after`? 

I.e. shouldn't the `markdown.vim` ftplugin provided by vim find some other means to enable this option?

**Comment by habamax** [comment]
> I.e. shouldn't the markdown.vim ftplugin provided by vim find some other means to enable this option?

I personally don't think it should. This option is to let ftplugin know what to do when ftplugin is being loaded -- thus it should be defined beforehand.

Everything else would complicate things a lot. You can use timers to check the value (but vim could be compiled without timer support), you can use CursorHold event to check the value (but again vim could be compiled without autocmd support) etc...

**Comment by habamax** [comment]
And if you want folding to be applied after ftplugin load then just use their code:

```
  setlocal foldexpr=MarkdownFold()
  setlocal foldmethod=expr
  setlocal foldtext=MarkdownFoldText()
```

**Comment by venthur** [comment]
The way I understand the `after` directories is, that it allows you to customize your configuration **additionally** to the stuff that vim does by default. And it seems to be the **recommended** way to configure stuff, according to [vim's documentation](https://vimhelp.org/filetype.txt.html) from ftplugin-overrule:

> If a global filetype plugin does not do exactly what you want, there are three
ways to change this:

> 1. Add a few settings.
   You must create a new filetype plugin in a directory early in
   'runtimepath'.  For Unix, for example you could use this file: 
        vim ~/.vim/ftplugin/fortran.vim
  You can set those settings and mappings that you would like to add.  Note
   that the global plugin will be loaded after this, it may overrule the
   settings that you do here.  If this is the case, you need to use one of the
   following two methods.

> 2. Make a copy of the plugin and change it.
   You must put the copy in a directory early in 'runtimepath'.  For Unix, for
   example, you could do this: 
        cp $VIMRUNTIME/ftplugin/fortran.vim ~/.vim/ftplugin/fortran.vim
  Then you can edit the copied file to your liking.  Since the b:did_ftplugin
   variable will be set, the global plugin will not be loaded.
   **A disadvantage of this method is that when the distributed plugin gets
   improved, you will have to copy and modify it again.**

> 3. Overrule the settings after loading the global plugin.
   You must create a new filetype plugin in a directory from the end of
   'runtimepath'.  For Unix, for example, you could use this file: 
        vim ~/.vim/after/ftplugin/fortran.vim
  **In this file you can change just those settings that you want to change.**

**Comment by habamax** [comment]
Overrule "settings" with 

```
  setlocal foldexpr=MarkdownFold()
  setlocal foldmethod=expr
  setlocal foldtext=MarkdownFoldText()
```

If you override/rule/change some global `variable` (not a setting) then it would mean nothing for the ftplugin if ftplugin knows nothing about your change.

**Comment by jottkaerr** [comment]
The recommended way is to put
```
let g:markdown_folding = 1
```
in your `~/.vimrc`.

**Comment by jottkaerr** [comment]
> The recommended way is to put
> 
> ```
> let g:markdown_folding = 1
> ```
> 
> in your `~/.vimrc`.

And in your case putting that line in `~/.vim/ftplugin/markdown.vim` should work equally well.

**Comment by brammool** [comment]
Not a bug.
