### ISSUE TITLE
Please document the hidden g:markdown_folding option.

### ISSUE THREAD

**Issue by venthur** [vim/vim#7945]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
There is a somewhat [hidden option](https://github.com/vim/vim/blob/fa79be6b10e1d34fd697a56e85f6c0ce101f3d62/runtime/ftplugin/markdown.vim#L67) `g:mardown_folding`, that is currently not documented.

**Describe the solution you'd like**
Please document that option.

**Describe alternatives you've considered**
None, really.

**Comment by habamax** [comment]
There are more

* `g:markdown_fenced_languages`
* `g:markdown_minlines`

Not sure what is the approach to the documentation of the `ftplugin/syntax` files. This one is from Tim Pope.

**Comment by brammool** [comment]
Cc'ing Tim Pope

> **Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
> There is a somewhat [hidden option](https://github.com/vim/vim/blob/fa79be6b10e1d34fd697a56e85f6c0ce101f3d62/runtime/ftplugin/markdown.vim#L67) `g:mardown_folding`, that is currently not documented.
> 
> **Describe the solution you'd like**
> Please document that option.

This would go under ":help ftplugin-docs".

-- 
Looking at Perl through Lisp glasses, Perl looks atrocious.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
I think something like this would be sufficient:

MARKDOWN                                                *ft-markdown-plugin*

To enable folding use this: >
        let g:markdown_folding = 1
<

**Comment by brammool** [comment]
Tim Pope wrote:

> I think something like this would be sufficient:
> 
> MARKDOWN                                                *ft-markdown-plugin*
> 
> To enable folding use this: >
>         let g:markdown_folding = 1
> <

I'll include that, thanks.

To also allow for zero to disable it, this should work:

	if get(g:, 'markdown_folding', 0)

-- 
ARTHUR:       Now stand aside worthy adversary.
BLACK KNIGHT: (Glancing at his shoulder) 'Tis but a scratch.
ARTHUR:       A scratch?  Your arm's off.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
fixed as of c8cdf0f80b3cfd88a4490d80572062c1fd1a96ca
