### ISSUE TITLE
Buggy foldclose in 'fillchars' option, for some characters

### ISSUE THREAD

**Issue by gdupras** [vim/vim#7955]
**Describe the bug**
When a fold is closed, the wrong character might be displayed in the fold column, for some `foldclose` characters in `'fillchars'` option.

**To Reproduce**
1. `vim --clean` or `gvim --clean`
2. Type some lines of text in the buffer.
3. `:set foldcolumn=1`
4. `:set fillchars+=foldclose:¬`
5. `V` and select some lines.
6. `zf` to fold the selected lines.
7. "Â" is displayed in the fold column.

**Expected behavior**
"¬" should appear in the fold column next to the closed fold, not "Â".

**Screenshots**
With `:set foldcolumn=1`:
![foldcolumn1](https://user-images.githubusercontent.com/57042631/110962411-f81f7200-831e-11eb-93ff-b3db731b7ec8.png)

With `:set foldcolumn=3`:
![foldcolumn3](https://user-images.githubusercontent.com/57042631/110962423-fb1a6280-831e-11eb-9753-fd3e59f911e3.png)

**Environment:**
 - Vim version: 8.2.2590
 - OS: Windows 10
 - Terminal: cmd.exe and GUI

**Comment by yegappan** [comment]
What is the output of the ":set encoding?" command. The encoding should be set to utf8
to use multibyte characters.

**Comment by gdupras** [comment]
Oh, right. I didn't consider encoding. With `--clean`, the encoding is "latin1" (in my environment anyway). Doing `:set encoding=utf-8` solves the problem with `foldclose`.

There is still an issue with `foldopen` though. To reproduce:

1. `vim --clean --cmd "set encoding=utf-8"`
2. Type some lines of text in the buffer.
3. `:set foldcolumn=1`
4. `:set fillchars+=foldopen:¬`
5. `V` and select some lines.
6. `zf` to fold the selected lines.
7. "+" is displayed in the fold column instead of "¬".

Same behavior with gvim. Same behavior if I set the encoding from within Vim instead of with `--cmd`.

With `:set foldcolumn=1`:

![foldcolumn1_utf8](https://user-images.githubusercontent.com/57042631/110978387-52293300-8331-11eb-9cea-fd514ff21b28.png)


With `:set foldcolumn=3`:

![foldcolumn3_utf8](https://user-images.githubusercontent.com/57042631/110978404-56555080-8331-11eb-981e-0dc6f86f4542.png)

**Comment by yegappan** [comment]
The 'foldopen' item in 'fillchars' specifies the character to display in the fold column when a fold is opened.
The 'foldclose' item in 'fillchars' specifies the character to display in the fold column when a fold is closed.

In your case, because the fold is closed, the default value of 'foldclose' (which is '+') is used. To display a
different character, you need to set 'foldclose'.

**Comment by gdupras** [comment]
Right, sorry. Still, the second image shows that there is something wrong. With a closed fold, only "+" should be displayed yet "+¬" is displayed instead.
