### ISSUE TITLE
Re-edit a file with space at the beginning will move the cursor to the first line

### ISSUE THREAD

**Issue by kalokng** [vim/vim#796]
Using vim / gvim on Windows.
Here is the file:

```
 test
test
```

There is a space at the first line before "test"
Move the cursor to line 2, and re-edit the file by :edit, the behaviors are different:
gvim 7.4: The cursor will move to line 2 column 1
gvim 7.4.1023: The cursor will move to line 1 column 2 (the first non-space char)

It also happens in MacVim 7.4.1811 as well. And vim with the following command can also reproduce it:
vim -u NONE -c "set nocp" file

**Comment by chrisbra** [comment]
fixed by https://github.com/vim/vim/releases/tag/v8.1.0034
