### ISSUE TITLE
Vim9: cannot execute custom Ex command from :def function with same name

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7960]
**Describe the bug**

In Vim9 script, we cannot execute a custom Ex command from a `:def` function which has the same name.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        com Cmd g:Cmd_was_run = 'yes'
        def Cmd()
            Cmd
        enddef
        Cmd()
        echo g:Cmd_was_run
    EOF
    )

`E121` is raised:

    E121: Undefined variable: g:Cmd_was_run

**Expected behavior**

No error is raised, because:

   - the `Cmd()` function is invoked at the end of the script
   - the latter has executed the custom Ex command `:Cmd`
   - the latter has set the global variable `g:Cmd_was_run` with the string `'yes'`

**Environment**

 - Vim version: 8.2 Included patches: 1-2601
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(366)

**Additional context**

The issue disappears if `:Cmd` is executed from a legacy function instead of a `:def` one:
```vim
vim9script
com Cmd g:Cmd_was_run = 'yes'
fu Cmd()
    Cmd
endfu
Cmd()
echo g:Cmd_was_run
```
    yes

The issue disappears if `:Cmd` is run from a `:def` function with a different name:
```vim
vim9script
com Cmd g:Cmd_was_run = 'yes'
def CmdDifferent()
    Cmd
enddef
CmdDifferent()
echo g:Cmd_was_run
```
    yes

**Comment by lacygoill** [comment]
I don't think there can be any confusion between the Ex command `:Cmd` and the `Cmd()` function, even though `:call` can be dropped.  For `Cmd` to be parsed as a function, there must still be parentheses afterward.  There are none in the previous snippet.

---

Something else is weird:
```vim
vim9script
def Cmd()
    echom 'yes'
enddef
def CmdFunc()
    Cmd
enddef
CmdFunc()
```
`yes` is not echo'ed, which is expected.  It means that `Cmd` was not parsed as the `Cmd()` function.  But no error is raised; that is unexpected.  There is no custom command named `:Cmd`, so this error should be raised:

    E476: Invalid command: Cmd

**Comment by lacygoill** [comment]
> Something else is weird:

Simpler MWE:
```vim
vim9script
fu Cmd()
endfu
Cmd
```
No error is – unexpectedly – raised.

Note that this time, `Cmd()` is a legacy function, not a Vim9 one.  This seems to suggest that it's a different issue (which might have the same cause though, I don't know).

In any case, for this other issue, it doesn't matter whether `Cmd()` is a legacy function or a `:def` one.  No error is ever raised.

**Comment by lacygoill** [comment]
> In any case, for this other issue, it doesn't matter whether Cmd() is a legacy function or a :def one. No error is ever raised.

And it's not that `:Cmd` somehow invokes `Cmd()`; it does not:
```vim
vim9script
fu Cmd()
    echom 'Cmd() was invoked'
endfu
Cmd
```
This snippet doesn't print any message.

**Comment by brammool** [comment]
It is confusing, just using "Cmd" is equivalent to "eval Cmd", which doesn't do anything.
The help mentions that a colon should be prepended if a user command and function are ambiguous.
But it's easy to make a mistake.  We can require for "(" or "->" to follow, then it's a lot simpler.
That you can't break the line before the "(" or "->" is a tiny price to pay.
