### ISSUE TITLE
Disambiguate Ctrl-i and Tab in Gvim

### ISSUE THREAD

**Issue by qsmodo** [vim/vim#7967]
Ordinary terminals send the same keycode for Ctrl-i and Tab, so there is nothing Vim can do to distinguish them. I believe Gvim, on the other hand, could handle those keys differently (after all, Gvim can tell Ctrl-Shift-a and Ctrl-a apart although they send the same keycodes in normal terminals), but right now it does not. For example,
```
:noremap <Tab> :echo "X"<CR>
```
also makes Ctrl-i print `X` in normal mode, but the default Ctrl-i action is too important to lose, whereas Tab is a very convenient and big key to leave unused. It would be great if Gvim distinguished them.

**Comment by lacygoill** [comment]
> but the default Ctrl-i action is too important to lose

Not sure it helps, but on Ubuntu 16.04, Vim 8.2.2607, and GTK2 for the GUI, I can map different commands to `<Tab>` and `<C-i>`:

    vim -g -Nu NONE +'nno <C-i> <C-i>' +'nno <Tab> :echom "Tab was pressed"<cr>'

![gif](https://user-images.githubusercontent.com/8505073/111212517-f8926400-85cf-11eb-9580-97882ea0c7ba.gif)

**Comment by lacygoill** [comment]
Although, I'm not sure why `<C-i>` has to be "fixed" (with `nno <C-i> <C-i>`), nor why it has to be before `<Tab>` is mapped, and not afterward.

**Comment by brammool** [comment]
Traditionally <Tab> and CTRL-I do the same thing, so that is what happens by default.
But you can map them separately if you like.  This also works in the terminal if it supports modifyOtherKeys.
Thus this already works, no need to change.

**Comment by qsmodo** [comment]
@lacygoill Thank you, very nice! I wonder how you found that out. I believe it might be worth a mention in the docs, I can't find it under `:h ctrl-i` (maybe it's elsewhere?).

**Comment by lacygoill** [comment]
> I wonder how you found that out.

By testing the [modifyOtherKeys](https://vimhelp.org/map.txt.html#modifyOtherKeys) feature.

> I believe it might be worth a mention in the docs, I can't find it under :h ctrl-i (maybe it's elsewhere?).

I agree.  At the very least, it might be worth documenting that if we want `<C-i>` and `<Tab>` to execute different commands, the former must be mapped *before* the latter.

This works:

    vim -g -Nu NONE +'nno <C-i> <cmd>echom "C-i was pressed"<cr>' +'nno <Tab> <cmd>echom "Tab was pressed"<cr>'

This does not:

    vim -g -Nu NONE +'nno <Tab> <cmd>echom "Tab was pressed"<cr>' +'nno <C-i> <cmd>echom "C-i was pressed"<cr>'

Because `<Tab>` does the same thing as `<C-i>`.

Also, mapping `<C-i>` separately from `<Tab>` is – I think – [a popular request](https://vi.stackexchange.com/q/16161/17449), for the reasons mentioned by the OP.  Even though the help already documents the ability to distinguish various chords at `:h modifyOtherKeys`, the feature would probably be more discoverable if it was also mentioned at `:h <Tab>`.  As a suggestion here is a patch:
```diff
diff --git a/runtime/doc/motion.txt b/runtime/doc/motion.txt
index d6215a4c6..409a9ab6c 100644
--- a/runtime/doc/motion.txt
+++ b/runtime/doc/motion.txt
@@ -1037,6 +1037,11 @@ CTRL-I			Go to [count] newer cursor position in jump list
 			(not a motion command).
 			{not available without the |+jumplist| feature}
 
+			NOTE: In the GUI and in a terminal supporting
+			|modifyOtherKeys|, CTRL-I can be mapped separately
+			from <Tab>, on the condition that the former is
+			mapped before the latter.
+
 							*:ju* *:jumps*
 :ju[mps]		Print the jump list (not a motion command).
 			{not available without the |+jumplist| feature}
```

**Comment by qsmodo** [comment]
@lacygoil This is weird... In Debian and Ubuntu your suggestion worked perfectly for me. In Gentoo, however, I cannot reproduce it with the GTK2 or GTK3 GUIs, although I can reproduce it with neXt GUI. Something mysterious is going on...

**Comment by tonymec** [comment]
From `:help <Tab>`:
```
			NOTE: In the GUI and in a terminal supporting
			|modifyOtherKeys|, CTRL-I can be mapped separately
			from <Tab>, on the condition that CTRL-I is
			mapped before <Tab>, otherwise the mapping applies to
			both.
```

**Comment by qsmodo** [comment]
Thanks @tonymec, but as I said I tried what lacygoill suggested, who was careful enough to observe that note in the help section.
