### ISSUE TITLE
Setting ```filetype plugin indent on``` in vimrc breaks Tcl indentation

### ISSUE THREAD

**Issue by ghost** [vim/vim#797]
The result of pressing `==` in visual mode to reindent the following lines by:

`````` tcl
# setting ```filetype plugin indent on``` in vimrc
if true {
  if true {
}
}

# setting ```filetype plugin indent on``` manually in Vim
if true {
  if true {
  }
}
``````

I expect the latter behavior regardless of where `filetype plugin indent on` is set. Thanks!

**Info**
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May  8 2016 22:57:26)
MacOS X (unix) version
Included patches: 1-1816

**Comment by vim-ml** [comment]
Hi Rob,

2016-5-12(Thu) 10:32:12 UTC+9 Rob Buonpastore:

> The result of pressing == in visual mode to reindent the following lines by:
> 
> # setting `filetype plugin indent on` in vimrc
> 
> if true {
>   if true {
> }
> }
> 
> # setting `filetype plugin indent on` manually in Vim
> 
> if true {
>   if true {
>   }
> }
> 
> I expect the latter behavior regardless of where filetype plugin indent on is set. Thanks!
> 
> Info
> 
> VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May  8 2016 22:57:26)
> 
> MacOS X (unix) version
> 
> Included patches: 1-1816

filetype plugin indent on

Above command are only enable file type detection, loading the plugin files and loading the indent file.
Then, you need to detect the file type in the following method and the like.

(a) Read file (e.g.`:e foo.tcl`)
(b) To detect the file type again (i.e. `:filetype detect`)
(c) To set the file type directly  (e.g. `:set ft=tcl`)

Case 1:

> # setting `filetype plugin indent on` in .vimrc
> 
> and If you specify a file to Vim startup.

Vim read specified file after reading .vimrc.
That is, enable file type detection before reading specified file. (same as above (a))

You can get the following result:
:set indentexpr?
  indentexpr=GetTclIndent()

Case 2:

> # setting `filetype plugin indent on` manually in Vim

None of the above((a),(b) and (c)) has not been carried out.

You can get the following result:
:set indentexpr?
  indentexpr=

Main issue is from here.
Only the case 1 is correctly file type detection has been carried out.
And The indentation is not correct, please contact the runtime/indent/tcl.vim maintainer.
(e.g. To: Nikolai Weibull, Cc: vim_dev ML)

## Thank you reading my crazy English.

Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by ghost** [comment]
Thanks Hirohito, very much appreciated.

@chrisbra, the following patch seems to fix the problem.

``` diff
diff --git a/runtime/indent/tcl.vim b/runtime/indent/tcl.vim
index a92f57d..b3dd74a 100644
--- a/runtime/indent/tcl.vim
+++ b/runtime/indent/tcl.vim
@@ -4 +4 @@
-" Latest Revision:  2006-12-20
+" Latest Revision:  2016-06-29
@@ -59 +59,2 @@ function GetTclIndent()
-    return indent(v:lnum) - &sw
+    let [lnum, _] = searchpairpos('{', '', '}', "bnW")
+    return indent(lnum)
```

**Comment by chrisbra** [comment]
Can you please contact the indent file maintainer? Thanks.
