### ISSUE TITLE
`b[:] = ['111', '222']` causes wrong redraw

### ISSUE THREAD

**Issue by Yggdroot** [vim/vim#7972]
**Describe the bug**
`b[:] = ['111', '222']` causes wrong redraw

**To Reproduce**
vimrc:
```vim
set nocp
set hidden
set nu

new|hide


func! Test()
python3 << EOF

import vim

b = vim.buffers[2]
b[:] = ['111', '222']

EOF
endf
```
test.txt:
```
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
bbbbbb
aaa
aaa
```
1. vim -u vimrc test.txt
2. `norm! 58Gzb` , now the cursor line is `bbbbbb`
3. `call Test()`
4. the screen is changed.

**Expected behavior**
The screen should not be changed.

**Screenshots**
If applicable, copy/paste the text or add screenshots to help explain your problem.

**Environment (please complete the following information):**
 - Vim version [e.g. 8.1.1234] (Or paste the result of `vim --version`.) 8.2.2282
 - OS: [e.g. Ubuntu 18.04, Windows 10 1809, macOS 10.14] centos 7
 - Terminal: [e.g. GNOME Terminal, mintty, iTerm2, tmux, GNU screen] (Use GUI if you use the GUI.) GNOME Terminal

**Comment by lacygoill** [comment]
A little simpler MWE:
```vim
set hidden number

new
hide

sil call setline(1, repeat(['aaa'], &lines) + ['bbbbbb'])

fu Func()
python3 << EOF
import vim
b = vim.buffers[2]
b[:] = ['', '']
EOF
endfu

norm! Gzb
call feedkeys(":call Func()\r", 'n')
```
The last `bbbbbb` line is no longer displayed.  Pressing `<C-L>` or executing `:redraw!` is necessary for Vim to display it again.

---

- [asan log](https://github.com/vim/vim/files/6147117/asan.log)
- [valgrind log](https://github.com/vim/vim/files/6147118/valgrind.log.gz)

The asan log reports memory leaks:

    SUMMARY: AddressSanitizer: 461288 byte(s) leaked in 386 allocation(s).

The valgrind log reports a bunch of errors from different contexts:

    ==3271== ERROR SUMMARY: 2756 errors from 121 contexts (suppressed: 0 from 0)
