### ISSUE TITLE
Closing preview window moves cursor to unexpected window

### ISSUE THREAD

**Issue by airblade** [vim/vim#7974]
**Describe the bug**
Under certain conditions, when the preview window is closed the cursor ends up in an unexpected place.  I don't know whether my expectation is wrong or it's a bug.

**To Reproduce**
1. Run `vim --clean`.
2. Open three files in this arrangement:

```
+-------------------+---------+
|                   |         |
|        A          |         |
|                   |         |
+-------------------+    C    |
|                   |         |
|        B          |         |
|                   |         |
+-------------------+---------+
```

3. With your cursor in B, open file D in a preview window: `:bo pedit D` (or `:to pedit D`).
4. Move to D: `:wincmd P`.
5. Close D: `:pclose`.
6. Expected: the cursor returns to B.  Actual: the cursor goes to A.

Variations:

- If window C is not open, the cursor behaves as expected in step 6.
- If D is opened with `:pedit D`, the cursor behaves as expected in step 6.

**Environment**
Vim 8.2.2566 via Homebrew – both terminal version (iTerm2) and GUI version.
macOS 10.14

**Comment by airblade** [comment]
@andymass kindly dug into the code and explained what is going on in this [StackOverflow answer and associated comments](https://vi.stackexchange.com/a/29630/1643).

In a nutshell it seems that when the preview window spans a vertical split, as it does in the example above with C when using `:bo`, Vim always places the cursor in the top-left window of the frame, i.e. A above.

I'm still not sure if this is intentional or a bug.  Either way, I could not find any description in Vim's docs of where the cursor is placed after closing a window.

**Comment by chrisbra** [comment]
Changing the logic where the cursor jumps when closing a window might annoy people again. So best is to leave it as is, so closing it.
