### ISSUE TITLE
vim -f -g -geometry 80x30+10+10"

### ISSUE THREAD

**Issue by dpelle** [vim/vim#7978]
Starting vim as follows gives an assertion failure:
```
$ vim -f -g -geometry 80x30+10+10

(gvim:3491): Gdk-CRITICAL **: 21:14:46.751: IA__gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed
```
The error is not fatal and I don't notice any consequences.

I found this bug after `Test_geometry()` was added in `test_startup.vim`.
That test triggers the error visible in the log when running `vim test_startup`.

**Environment**

 - Vim version: 8.2.2610 GUI gtk2 or gtk3
 - OS: xubuntu-18.04.5

**Comment by brammool** [comment]
Dominique wrote:

> **Describe the bug**
> ```
> $ vim -f -g -geometry 80x30+10+10
> 
> (gvim:3491): Gdk-CRITICAL **: 21:14:46.751: IA__gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed
> ```

This appears to come from this line in gui_gtk_get_screen_geom_of_win():

  monitor = gdk_screen_get_monitor_at_window(screen, win);

"win" is NULL.  Apparently the window hasn't been created yet.
I don't think we can create the window earlier, it's a chicken-egg
problem.

Perhaps we can do something like:

	monitor = gdk_screen_get_monitor_at_point(screen, 10, 10);

If we can pass the coordinates from higher up.

-- 
Imagine a world without hypothetical situations.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dpelle** [comment]
Patch 8.2.2622 fixed the assertion with gtk2 GUI, but with gtk3, I still see the same error.
I'm using Linux x86-64, xubuntu-18.04.5.

With gtk3, if I put a printf at line `gui_gtk_x11.c:4171`, I see this:
```
[gui_gtk_get_screen_geom_of_win:4171] win=(nil)
[gui_gtk_get_screen_geom_of_win:4171] win=0x559c998fa4b0
[gui_gtk_get_screen_geom_of_win:4171] win=0x559c998fa4b0
```
So at startup, we enter this function multiple times.  `win` is NULL in only the first call.

I don't know if this the right way to fix it, but this the following
patch gets rid of the assertion and the `-geometry 80x40+10+100`
parameter still works as expected. All tests also pass:
```
diff --git a/src/gui_gtk_x11.c b/src/gui_gtk_x11.c
index 3fdff4d3f..c0064e22a 100644
--- a/src/gui_gtk_x11.c
+++ b/src/gui_gtk_x11.c
@@ -4168,6 +4168,8 @@ gui_gtk_get_screen_geom_of_win(
     GdkRectangle geometry;
     GdkWindow *win = gtk_widget_get_window(wid);
 #if GTK_CHECK_VERSION(3,22,0)
+    if (win == NULL)
+       return;
     GdkDisplay *dpy = gtk_widget_get_display(wid);
     GdkMonitor *monitor = gdk_display_get_monitor_at_window(dpy, win);
```

**Comment by tonymec** [comment]
Rather than `#if GTK_CHECK_VERSION(3,22,0)`, what about `#ifdef USE_GTK3` ? This is defined (or not) in `src/auto/config.h` (or in `src/shadow/auto/config.h`) at line 485 for my "big" build. It might or might not need to be written as `#if DEFINED(FEAT_GUI_GTK) && DEFINED(USE_GTK3)` instead.

Best regards,
Tony.

**Comment by brammool** [comment]
Dominique wrote:

> Patch 8.2.2622 fixed the assertion with gtk2 GUI, but with gtk3, I still see the same error.
> I'm using Linux x86-64, xubuntu-18.04.5.
> 
> With gtk3, if I put a printf at line `gui_gtk_x11.c:4171`, I see this:
> ```
> [gui_gtk_get_screen_geom_of_win:4171] win=(nil)
> [gui_gtk_get_screen_geom_of_win:4171] win=0x559c998fa4b0
> [gui_gtk_get_screen_geom_of_win:4171] win=0x559c998fa4b0
> ```
> So at startup, we enter this function multiple times.  `win` is NULL in only the first call.
> 
> I don't know if this the right way to fix it, but this the following
> patch gets rid of the assertion and the `-geometry 80x40+10+100`
> parameter still works as expected. All tests also pass:
> ```
> diff --git a/src/gui_gtk_x11.c b/src/gui_gtk_x11.c
> index 3fdff4d3f..c0064e22a 100644
> --- a/src/gui_gtk_x11.c
> +++ b/src/gui_gtk_x11.c
> @@ -4168,6 +4168,8 @@ gui_gtk_get_screen_geom_of_win(
>      GdkRectangle geometry;
>      GdkWindow *win = gtk_widget_get_window(wid);
>  #if GTK_CHECK_VERSION(3,22,0)
> +    if (win == NULL)
> +       return;
>      GdkDisplay *dpy = gtk_widget_get_display(wid);
>      GdkMonitor *monitor = gdk_display_get_monitor_at_window(dpy, win);
> ```

I'll do something similar as the change to GTK2.

-- 
Often you're less important than your furniture.  If you think about it, you
can get fired but your furniture stays behind, gainfully employed at the
company that didn't need _you_ anymore.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
