### ISSUE TITLE
'is' should be 'ic'

### ISSUE THREAD

**Issue by jstraceski** [vim/vim#7980]
https://github.com/vim/vim/blob/5f91e74bf968c9033474086b2d9cb457281c8aa6/runtime/tutor/tutor#L822

The shorthand for 'incsearch' is 'ic' not 'is'.
This doesn't really affect the overall tutorial because setting 'inner sentence' doesn't change the search in a significant way but it may be confusing to those paying attention.

**Comment by nickspoons** [comment]
`'ic'` is short for `'ignorecase'`: [:h 'ic'](http://vimhelp.appspot.com/options.txt.html#%27ic%27)
`'is'` is short for `'incsearch'`: [:h 'is'](http://vimhelp.appspot.com/options.txt.html#%27is%27)

**Comment by jstraceski** [comment]
This was a mistake and can be deleted.

Realistically, this should probably be explained in lesson 6.5 and not just in the summary.
