### ISSUE TITLE
getqflist's items do not contain pattern and type information for inbuilt commands like vimgrep, grep

### ISSUE THREAD

**Issue by poetaman** [vim/vim#7984]
**Describe the bug**
When I run commands that populate quickfix/location list (like ``:vimgrep`` or ``:grep``), the values of important item properties like ``pattern`` & ``type`` returned by functions ``getqflist`` & ``getloclist`` have value ``''`` (instead of meaningful values). Example returned item after ``:vimgrep``:

``{'lnum': 2, 'bufnr': 4, 'col': 3, 'pattern': '', 'valid': 1, 'vcol': 0, 'nr': 0, 'type': '', 'module': '', 'text': '["something"] 1615923666 "helloworld.md" "helloworld.pdf" "helloworld" 1615923667'}``

**Expected behavior**
The items should contain ``pattern``, and ``type`` information at least for all internal commands that populate these lists.

Alternate solution: If the ``pattern``, ``type`` information is not stored for these commands because its redundant (given their values are same across the items), then is there a way to find out their value? In that case, maybe there should also be a`` pattern`` & ``type`` field in ``{what}`` dictionary to save space and performance. User can then decide what to process based on the context (or command). If it's present there, user can use that value if for such commands.

> Sidenote: So far I have never come across any command that populates ``pattern``, which one could it be if not something like ``:vimgrep`` or ``:grep``?

**Environment (please complete the following information):**
 - Vim version: 8.2 (patches: 1-2576)
 - OS: macOS 11.2.3 (ARM64)
 - Terminal: iTerm2

**Additional context**
Ideally, doing ``:ll num``, ``:cc num``, ``:lnext``, ``:lprevious``, ``:cnext``, ``:cprevious`` will highlight the exact match instance in the corresponding buffer (only one instance at a time, based on current ``idx`` of quickfix/location list). Given it doesn't do that by default, I went on this trip to try to do that & encountered this problem. A complete solution is welcome as well!

**Comment by lacygoill** [comment]
> User can then decide what to process based on the context (or command).

Are you looking for the context property of a quickfix list?  If so, see [`:h quickfix-context`](https://vimhelp.org/quickfix.txt.html#quickfix-context).

---

> Sidenote: So far I have never come across any command that populates pattern, which one could it be if not something like :vimgrep or :grep?

The pattern property of a quickfix entry is used by Vim to find where the latter is.  It has priority over the `lnum` and `col` properties:
```vim
vim9script
[{
  pattern: 'abc.*page',
  lnum: 1128,
  col: 32,
  filename: $VIMRUNTIME .. '/doc/index.txt',
}]->setqflist()
cc 1
```
    |:tabclose|     :tabc[lose]     close current tab page

Notice that you're on line 1642 which references the `:tabclose` Ex command.  You're not on the line 1128, which matches the `grail` help tag.

Builtin commands like `:vimgrep` set the `lnum` and `col` properties.  Therefore, `pattern` can't be set; at least, it doesn't need to.  Besides, finding an entry with a line and column numbers is probably faster than with a regex.

As for the `type` property, it's meant to be set by a compiler plugin when writing an errorformat which includes a `%t` item.  See [`:h errorformat`](https://vimhelp.org/quickfix.txt.html#errorformat); in particular these lines:

https://github.com/vim/vim/blob/a555e6fcb6ec97b5ab30b20a340b228f4d820f14/runtime/doc/quickfix.txt#L1384-L1388

A compiler plugin only makes sense for when parsing the output of a known external program (typically a compiler, but not necessarily).  A builtin command like `:vimgrep` is not parsing the output of an external program; there is no compiler plugin involved.  `:grep` can parse the output of an external program, but there is no easy way for Vim to know which one it is and which compiler plugin it should use.

If you're interested in reading existing compiler plugins, run this Ex command which should populate the arglist:

    :next $VIMRUNTIME/compiler/*.vim

---

> Ideally, doing :ll num, :cc num, :lnext, :lprevious, :cnext, :cprevious will highlight the exact match instance in the corresponding buffer (only one instance at a time, based on current idx of quickfix/location list). Given it doesn't do that by default, I went on this trip to try to do that & encountered this problem. A complete solution is welcome as well!

You already have enough information to highlight the first character of the text of a quickfix entry.  But I guess you want to highlight all the characters in the text; not just the first one.  If so, maybe you would need quickfix entries to get two new properties; something like `end_lnum` and `end_col`, which are already used as key names in the `{props}` dictionary that we can pass to `prop_add()`.

**Comment by poetaman** [comment]
@lacygoill Yep I was trying to highlight all characters that match. I did think of that too, yes it would be wonderful if it is possible to get end_lnum & end_col. It would make the UI more intuitive IMO, given the nature of regex & the differing lengths they can match to depending on greedy/non-greedy/etc settings. I don’t know what you mean by “pass to prop_add”... Are you suggesting that what I intend to do is already possible? Will it work for all commands that populate quickfix/location list? (Including for plugins like ALE lint) It would be nice to see a snippet.

**Comment by lacygoill** [comment]
> I don’t know what you mean by “pass to prop_add”... Are you suggesting that what I intend to do is already possible? 

No, I simply meant that those hypothetical new property names would be consistent with what we already have in a different – but still similar – context.  That is, when we add text properties.  Incidentally, if you had this information, you would probably use text properties to implement the highlighting.

**Comment by poetaman** [comment]
@lacygoill Ok then let’s see what @brammool has to say about adding end_lnum & end_col to quickfix/location list item properties!

**Comment by yegappan** [comment]
The pattern in the quickfix list is not referring to the search pattern used by the vimgrep or grep commands. It refers to the text found by the %s item in 'errorformat'.

The '%s' item in 'efm' was introduced to support locating error lines without the line number. For example, the tags file (produced by ctags) contains search patterns to locate the line containing a tag. The '%s' item in 'efm' can be used to parse the tags file and populate the quickfix list.

This is used by the ':ltag' command which populates the location list with the matching tags. After running the ":ltag" command, if you look at the output returned by getloclist(0), you will see the pattern in the returned dictionary.

**Comment by chrisbra** [comment]
I suppose this can be closed then?

**Comment by poetaman** [comment]
@chrisbra I don't think this should be closed, and @lacygoill will agree. The intent of question was to highlight the exact match (which @lacygoill inferred correctly from "Additional context" section of my description) & @lacygoill's proposal is to have end_lnum & end_col properties added to quickfix/location list items.

**Comment by lacygoill** [comment]
Bear in mind that there are more than a thousand open bug reports, and not enough people to give answers or submit patches.  The devs can't spend too much time on each report.  Your original report made it sound like there was a bug in the output of `getqflist()`, while I don't think there is.  It seems that what you want is more info about each entry in a quickfix list; specifically, the positions where they end.  I agree that it might be useful; but that's a feature request, not a bug, for which I suggest you open a new report.
