### ISSUE TITLE
Example windo command does not work

### ISSUE THREAD

**Issue by dstein64** [vim/vim#7993]
**Describe the bug**

The help for `:windo` is followed by the following [example](https://github.com/vim/vim/blob/c5cf369e9543ff065e2e1da91da3218c223840e2/runtime/doc/windows.txt#L793).

https://github.com/vim/vim/blob/c5cf369e9543ff065e2e1da91da3218c223840e2/runtime/doc/windows.txt#L793

Executing this command results in the following error:
```
E474: Invalid argument: nofoldcolumn
```

**To Reproduce**

Detailed steps to reproduce the behavior:
1. Run `vim --clean` (or `gvim --clean`, etc.)
2. `:windo set nolist nofoldcolumn | normal zn`

**Expected behavior**

The help page says "This resets the 'list' option and disables folding in all windows."

**Environment (please complete the following information):**

 - Vim version: 8.2.2529
 - OS: Ubuntu 20.04.2
 - Terminal: Konsole 19.12.3

**Comment by lacygoill** [comment]
Patch to update the documentation:
```diff
diff --git a/runtime/doc/windows.txt b/runtime/doc/windows.txt
index 69de9bafe..9e1f010ed 100644
--- a/runtime/doc/windows.txt
+++ b/runtime/doc/windows.txt
@@ -790,7 +790,7 @@ can also get to them with the buffer list commands, like ":bnext".
 
 Examples: >
 
-	:windo set nolist nofoldcolumn | normal zn
+	:windo set nolist foldcolumn=0 | normal! zn
 
 This resets the 'list' option and disables folding in all windows. >
 
```

**Comment by brammool** [comment]
I'll include the correction, thanks.
