### ISSUE TITLE
winrow is reported as a 'column' in :help getwininfo()

### ISSUE THREAD

**Issue by dstein64** [vim/vim#7994]
**Describe the bug**

The [help](https://github.com/vim/vim/blob/c5cf369e9543ff065e2e1da91da3218c223840e2/runtime/doc/eval.txt#L6094) for `getwininfo()` refers to `winrow` as a "column" (as opposed to a "row").

https://github.com/vim/vim/blob/c5cf369e9543ff065e2e1da91da3218c223840e2/runtime/doc/eval.txt#L6094-L6095

**Environment (please complete the following information):**

 - Vim version: 8.2.2529
 - OS: Ubuntu 20.04.2
 - Terminal: Konsole 19.12.3

**Comment by lacygoill** [comment]
Patch to update the documentation:
```diff
diff --git a/runtime/doc/eval.txt b/runtime/doc/eval.txt
index 723a7329b..3d18e36ba 100644
--- a/runtime/doc/eval.txt
+++ b/runtime/doc/eval.txt
@@ -6087,11 +6087,11 @@ getwininfo([{winid}])					*getwininfo()*
 			width		window width
 			winbar		1 if the window has a toolbar, 0
 					otherwise
-			wincol		leftmost screen column of the window,
+			wincol		leftmost screen column of the window;
 					col from |win_screenpos()|
 			winid		|window-ID|
 			winnr		window number
-			winrow		topmost screen column of the window,
+			winrow		topmost screen line of the window;
 					row from |win_screenpos()|
 
 		Can also be used as a |method|: >
```

**Comment by brammool** [comment]
I'll include the fix, thanks.
