### ISSUE TITLE
wrong documentation at ":h prop_type_add()"

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7996]
The help at `:h E971` says this:

   > "combine"       **when omitted or TRUE** the text property highlighting is
   >                 combined with any syntax highlighting; when FALSE the
   >                 text property highlighting replaces the syntax
   >                 highlighting

The help at `:h prop_type_add()` says this:

   > combine      when TRUE combine the highlight with any
   >              syntax highlight; **when omitted or FALSE** syntax
   >              highlight will not be used

There is a contradiction.  The first excerpt says that omitting the `combine` field is equivalent to setting it with the value `TRUE`.  The second excerpt says that omitting the `combine` field is equivalent to setting it with the value `FALSE`.

In practice, omitting the `combine` field is equivalent to setting it with the value `TRUE`:
```vim
vim9script
setline(1, 'some combined property, some not combined property, and some combine-is-omitted property')
hi Comment ctermfg=green
hi PropHighlight ctermbg=lightgrey
syn match Comment '.*'

prop_type_add('combined', {
    highlight: 'PropHighlight',
    combine: true
    })
prop_type_add('not_combined', {
    highlight: 'PropHighlight',
    combine: false
    })
prop_type_add('combine-is-omitted', {
    highlight: 'PropHighlight',
    })

prop_add(1, searchpos('combined', 'nW')[1], {
    type: 'combined',
    length: strcharlen('combined'),
    })
prop_add(1, searchpos('not combined', 'nW')[1], {
    type: 'not_combined',
    length: strcharlen('not combined'),
    })
prop_add(1, searchpos('combine-is-omitted', 'nW')[1], {
    type: 'combine-is-omitted',
    length: strcharlen('combine-is-omitted'),
    })
```
So, it's the first excerpt which is correct; not the second one.

Patch fixing the documentation:
```diff
diff --git a/runtime/doc/textprop.txt b/runtime/doc/textprop.txt
index 169520cfd..9d81c0652 100644
--- a/runtime/doc/textprop.txt
+++ b/runtime/doc/textprop.txt
@@ -258,8 +258,8 @@ prop_type_add({name}, {props})		*prop_type_add()* *E969* *E970*
 				properties the one with the highest priority
 				will be used; negative values can be used, the
 				default priority is zero
-		   combine	when TRUE combine the highlight with any
-				syntax highlight; when omitted or FALSE syntax
+		   combine	when omitted or TRUE, combine the highlight
+				with any syntax highlight; when FALSE, syntax
 				highlight will not be used
 		   start_incl	when TRUE inserts at the start position will
 				be included in the text property
```

**Comment by brammool** [comment]
I'll include the fix, thanks.
