### ISSUE TITLE
Vim9: buffer line unexpectedly printed on command-line when invoking "system()" with ":silent"

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8005]
**Describe the bug**

In Vim9 script, invoking a shell command with `system()` and `:silent` from an `<expr>` mapping might unexpectedly cause a line in the buffer to be printed on the command-line, if the shell command has the side-effect of resizing the terminal.

**To Reproduce**

Open an xterm terminal.

Then, run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        set t_ut=
        set lines=24
        set lazyredraw
        set laststatus=2
        hi Normal ctermbg=lightgrey
        range(&lines)->mapnew((_, v) => v .. ' some text')->setline(1)
        def g:Func(): string
            sil system('resize -s ' .. (&lines / 2) .. ' ' .. &columns)
            return ''
        enddef
        nno <expr> <F3> g:Func()
        feedkeys("\<F3>")
    EOF
    )

This line is printed on the command-line:

    11 some text

**Expected behavior**

Nothing is printed on the command-line.

**Screenshots**

![gif](https://user-images.githubusercontent.com/8505073/112377165-b4951280-8ce5-11eb-9428-d670b58813b7.gif)

**Environment**

 - Vim version: 8.2 Included patches: 1-2649
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(366)

**Additional context**

`11 some text` is the line which would be displayed if there was no status line and no command line.  For some reason, Vim behaves as if those didn't exist.

---

If `Func()` is re-written as a legacy function, which runs the exact same commands, the issue disappears:
```vim
vim9script
set t_ut=
set lines=24
set lazyredraw
set laststatus=2
hi Normal ctermbg=lightgrey
range(&lines)->mapnew((_, v) => v .. ' some text')->setline(1)
fu g:Func()
    sil call system('resize -s ' .. (&lines / 2) .. ' ' .. &columns)
    return ''
endfu
nno <expr> <F3> g:Func()
feedkeys("\<F3>")
```
---

The issue also disappears when:

   - `'t_ut'` keeps its default value (i.e. `y`)
   - `'lazyredraw'` keeps its default value (i.e. is reset)
   - the background color of the `Normal` HG is not set
   - `system()` is invoked without `:silent`
   - `Func()` is invoked from a mapping which is not defined with the `<expr>` argument

---

I frequently see this issue, because I have a mapping which runs arbitrary code written under the cursor (when it's inside a fenced code block in a markdown file) in a separate tmux pane.  To open the new tmux pane, the current pane where Vim is running has to be resized.  This resizing triggers the issue; that is, I can see some line in my notes being printed on the command-line.

**Comment by lacygoill** [comment]
The minimal reproducible example relies on the shell utility `resize(1)`, which I think comes with `xterm(1)`.  I can reproduce with and without config in `~/.Xresources`.

**Comment by lacygoill** [comment]
> The issue also disappears when:

Note that all of these conditions don't need to be true for the issue to disappear.  Just one.  If any of them is true, the issue disappears.

**Comment by brammool** [comment]
Well, if you use "silent" then you can expect side effects of executing a shell command.
I don't think we need to fix this.

**Comment by lacygoill** [comment]
Ok, understood.
