### ISSUE TITLE
Snap the GUI scrollbar to window edge

### ISSUE THREAD

**Issue by xlucn** [vim/vim#8008]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
Currently on all platforms other than windows the gvim scrollbar snaps to the last visible column/row. There was an issue, #5602, that was labeled only for windows. The behavior was changed for windows in #6466 to let the scrollbar snap to window border instead. However that PR only implements the functions for win32 but not the other platforms.

**Describe the solution you'd like**
Is it planned to implement the same behavior on other platforms? I am on Linux so the gtk one is probably most related.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by chrisbra** [comment]
so would you be able to provide a patch for that?

**Comment by k-takata** [comment]
I don't know well about GTK and other GUIs. So, I only implemented for Windows, and I just prepared stub functions for other GUIs. PR is welcome.

**Comment by xlucn** [comment]
@chrisbra sorry, I don't know about GTK UI developing (or any other ones).

**Comment by k-takata** [comment]
Fixed by [8.2.2709](https://github.com/vim/vim/commit/26af8e54ff0d423b7258ef84d175c8570740629a).
