### ISSUE TITLE
Scrolling performance reduced when popup is visible

### ISSUE THREAD

**Issue by noscript** [vim/vim#8009]
**Describe the bug**
When popup is visible and the buffer is being scrolled the content of the buffer often half way rendered or completely blank. Hiding the popup restores the performance.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run vim:
```
vim -g -u NONE -f +"set columns=80 lines=50" +"help version8.txt" +"only" +"call popup_create('hello', #{line: 1, close: 'click'})"
```
2. Start scrolling the buffer, preferably with a mouse.
3. Observe the buffer is half way empty or completely blank.
4. Click on the popup to hide it.
5. Start scrolling again, no more rendering issues.

**Expected behavior**
Scrolling performance is unaffacted by visible popups.

**Screenshots**

https://user-images.githubusercontent.com/717109/112445818-37ef4c00-8d58-11eb-8f76-cb4ba3b771ea.mp4

**Environment:**
 - Vim 8.2 1-2650
 - OS: Ubuntu 20.04
 - Terminal: GUI

**Comment by brammool** [comment]
This is normal.  Vim tries to use terminal codes to move lines up/down, but when there is a popup this might cause a mess.
See win_do_lines(): if "popup_visible" is set it bails out.
This cannot be improved without adding very complicated code (which most likely causes a slowdown in some way).
