### ISSUE TITLE
[Regression] textyankpost kicked after 'visual' + 'esc'

### ISSUE THREAD

**Issue by Shane-XB-Qian** [vim/vim#8010]
**Describe the bug**
event 'textyankpost' was kicked off when just issued 'v' then 'esc'.
// not sure since when, but no issue at v8.1.2269

**To Reproduce**
Detailed steps to reproduce the behavior:
1. vim --clean foo
2. edit and type 'abc'
3. and `:au textyankpost * echomsg 'foo'`
4. issue 'v' on 'a' of 'abc'
5. then 'esc' escape from 'visual'
// output: 'foo'

**Expected behavior**
// no 'foo'

**Environment (please complete the following information):**
vim v8.2.2653
xterm and xfce-term

**Comment by Shane-XB-Qian** [comment]
`{'regcontents': ['a'], 'visual': v:true, 'regname': '*', 'regtype': 'v', 'operator': 'y'}`

// here actually no 'y'. but it kicked... somehow...

// and testcase looks didnot cover this case........

**Comment by Shane-XB-Qian** [comment]
some plugins depended on textyankpost, then would be broken..............
and/or whatever, there lots unnecessary yank happening... if so..............

**Comment by LemonBoy** [comment]
This is done on purpose and is covered by [this test](https://github.com/vim/vim/blob/master/src/testdir/test_autocmd.vim#L1810,L1811). See #7367 for more info.

**Comment by Shane-XB-Qian** [comment]
> This is done on purpose

really? supposed here had some misunderstanding... 
here just tried to 'esc' escape from 'visual' mode, did not do any 'y' yanking..........
why it auto kicked off the yanking?!

**Comment by LemonBoy** [comment]
It's a synthetic yank event caused by your `clipboard` option containing `autoselect` (or `autoselectplus`).

**Comment by Shane-XB-Qian** [comment]
so far i donot understand the purpose of this change, but it messed up some plugins e.g yankring, as long as esc from visual mode, the yank history messed up. and if some activities depended on textyankpost, then as long as you esc from visual (but actually you did not do any 'yank') the activities kicked off..... looks quite mess.......

**Comment by LemonBoy** [comment]
Please read the linked ticket, before that change `textyankpost` event would fire at random times whenever an external client requested the clipboard data from Vim.

Whenever you exit the Visual mode the contents of `+` or `*` are updated (again, check your `clipboard` value), the autocmd fires because of that.

**Comment by Shane-XB-Qian** [comment]
> before that change textyankpost event would fire at random times whenever an external client requested the clipboard data from Vim.

so far i was not noticed there was such issue, or perhaps 'yes', 
But compared to now, it is ALWAYS (kicked off textyankpost) vs random.
// IF had to say something, then i donot like this change, before there would be a better solution, i think we'd better stop 'fix sth while broken sth'.

**Comment by Shane-XB-Qian** [comment]
> before that change textyankpost event would fire at random times whenever an external client requested the clipboard data from Vim.

so far i was not noticed there was such issue, or perhaps 'yes', 
But compared to now, it is ALWAYS (kicked off textyankpost) vs random.
// IF had to say something, then i donot like this change, before there would be a better solution, i think we'd better stop 'fix sth while broken sth'.

**Comment by Shane-XB-Qian** [comment]
let me explain more:
to mock 'yank' when 'visual mode' just left looks was not a good solution, even IF there really was a 'random' issue.
since 'yank' and esc from 'visual' mode it definitely is a two things, it's over the user nature mind to image auto yanking happening in that timing... since (if) no manual 'y' issued too.

**Comment by LemonBoy** [comment]
> // IF had to say something, then i donot like this change, before there would be a better solution, i think we'd better stop 'fix sth while broken sth'.

Have you seen [this XKCD](https://xkcd.com/1172/) comic?

> to mock 'yank' when 'visual mode' just left looks was not a good solution, even IF there really was a 'random' issue.

IF you try reading the linked issue (and #4201) you will find all the infos needed to understand what triggers the 'random' autocommands. I added the yank on visual exit because the register content is updated and people may want to react to this change, if you don't like that add `set clipboard -= autoselect` to your vimrc and carry on.

> since (if) no manual 'y' issued too.

This raises a good point, do we need a way of tagging yank ops not initiated by the user?

**Comment by Shane-XB-Qian** [comment]
it's not regarding to what i set or my vimrc, those actually didnot bother me too much, but what i said here mostly were the default value of vim option, i think it's not a good idea to let common user to debug 'surprise' or he/she had to change the default value of vim option. though so far i am not sure how often of that 'random', but now it's 'always'. Or if this is really the only better/acceptable solution, then let it be, someone else would bring up with 'angry' instead of me someday i Guess... :-) saying why his/her plugin is broken...
// not sure what your mean of that 'comic'... supposed that's a joke or something...

**Comment by Shane-XB-Qian** [comment]
@LemonBoy perhaps should doc it at somewhere (which if also was easy to find out such instruction when user had to 'debug'), **IF** this change was really necessary... since it is an inconsistent behavior like before, to reduce the surprise of additional 'textyankpost' event kicked off, then maybe ok (reduce the pain) if so........

**Comment by Shane-XB-Qian** [comment]
v9 had been released, so no meaning to argue if this was a regression or not..
// so closing...
