### ISSUE TITLE
Can you increase the mouse operation

### ISSUE THREAD

**Issue by 209150579** [vim/vim#8016]
![-4c0444a9bc013da](https://user-images.githubusercontent.com/80696034/112702795-a571b880-8ecf-11eb-83d8-93b375820577.png)

**Comment by 209150579** [comment]
Pop-up event: click to select, slide ≈ scroll, press and hold to delay copy and paste

**Comment by 209150579** [comment]
I sorted out my thoughts. To detect whether a pop-up window is generated. If yes, get the number of entries first and generate a coordinate x y for each entry. Start and detect mouse events. When clicking in the pop-up window, get the element of the pop-up window with cursor x y, and input it into text.

What you need to know is the result of the entry, the generation process of the pop-up window, the process of selecting the approximate location of the event, and inputting it into the file.

**Comment by brammool** [comment]
Please follow the template to provide more information.  I don't understand what this issue is about.

**Comment by lacygoill** [comment]
I don't understand either.

If – after 10 days – the OP didn't find the time to give more information about what their feature request is, or at least leave a comment to tell that they intend to do it in the future, they'll probably never do it.

**Comment by k-takata** [comment]
No feedback from the OP, so closing.
