### ISSUE TITLE
Question vim9 comments sign

### ISSUE THREAD

**Issue by lkjell** [vim/vim#8021]
If I understand vim9 script will have a new syntax. Is it possible for you to define a new comment sign instead of " (double quote)? Suggest to use # (hash).

I know it will break a lot but since vim9 will break a lot of stuff it might be for the better.

I mean in vimrc

**Comment by gdupras** [comment]
From `:help vim9-differences`:

```
- Comments start with #, not ": 
	echo "hello"   # comment
```
