### ISSUE TITLE
Statusline disappear in window with WinBar

### ISSUE THREAD

**Issue by fedorenchik** [vim/vim#8037]
**Describe the bug**
statusline of window disappear when maximize other window with `set winminheight=0` and window has `WinBar`.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean` or `gvim --clean`
2. Run following commands:
```viml
term ls
nnoremenu WinBar.Test :test
set winminheight=0
wincmd j
wincmd _
```
3. Observe statusline of window above disappeared, and only WinBar is visible.

**Expected behavior**
Statuslines of all windows are visible.

**Environment (please complete the following information):**
 - Vim version 8.2.2601
 - OS: Manjaro Gnome
 - Terminal: GUI GTK3, Kitty

**Comment by ychin** [comment]
I think the fix doesn't fix the case when `statusline` is set to a custom text. Added a new PR #8047 to fix it.
