### ISSUE TITLE
&t_ut not respected when using &termguicolors

### ISSUE THREAD

**Issue by wilywampa** [vim/vim#804]
A common issue running Vim under tmux is that the background color will only be drawn under text, e.g.:

<img width="659" alt="screen shot 2016-05-14 at 2 20 02 pm" src="https://cloud.githubusercontent.com/assets/4472522/15270749/0ac0b22e-19df-11e6-86fb-5d203bee1712.png">

The usual solution is to set `&t_ut` to empty to tell Vim it needs to draw the background color. However, in Vim 7.4.1830 and https://github.com/tmux/tmux/commit/e76d44a64081ea1ea325b23266ad60a24448d9ab true color mostly works but I get the same background color erase problem even with `&t_ut` cleared:

<img width="638" alt="screen shot 2016-05-14 at 2 25 49 pm" src="https://cloud.githubusercontent.com/assets/4472522/15270766/c7a3bbac-19df-11e6-92d4-59bd764cc284.png">

I tested this in iTerm2 and mintty with the same results. Everything works fine outside of tmux, but that never needed `&t_ut` set even for 256 colors.

~~I found a workaround which was to delete these three lines~~ (only works if the color scheme sets `ctermbg` to non-zero value): https://github.com/vim/vim/blob/master/src/screen.c#L8962-L8964

I'm not sure if that's the right solution. The fact that the logic is there suggests it's intentional, but Vim is not drawing the background color so it seems to me that function should return false.

**Comment by djmoch** [comment]
Glad I found this. I've been moving toward writing an issue for the same problem. I has assumed I was doing something wrong and was asking for help on [StackExchange](http://vi.stackexchange.com/questions/8116/truecolor-termguicolors-causes-display-issues-in-tmux). I link here in case the details are useful. Hope to see a fix for this soon!

**Comment by brammool** [comment]
Have you tried if patch 7.4.1854 fixes this problem?

**Comment by djmoch** [comment]
I'm using MacVim with 7.4.1901

**Comment by wilywampa** [comment]
I tested with 7.4.1910 and still needed https://github.com/vim/vim/pull/805 for this to work.

**Comment by rpereira** [comment]
Hi @brammool,

I have the same problem. The 24-bit colors are rendered nicely outside tmux, but here's how it looks inside tmux:

![screen shot 2016-06-09 at 10 01 00](https://cloud.githubusercontent.com/assets/3859158/15924335/7593bf2a-2e29-11e6-85bf-f5a8f3fe6e87.png)

Running on:
- iTerm2 3.0.1
- Vim 7.4.1910 with +termguicolors
- tmux 2.2

**Comment by AlessandroYorba** [comment]
A user from one of my own colorschemes thad a similar issue [sierra Issue#3](https://github.com/AlessandroYorba/Sierra/issues/3). I don't know if this solution will work for you guys but it did for my user.

``` VimL
if &term =~ '256color'
  " disable Background Color Erase (BCE) so that color schemes
  " render properly when inside 256-color tmux and GNU screen.
  set t_ut=
endif
```

The solution was found from this post here: [Source](http://sunaku.github.io/vim-256color-bce.html)

**Comment by lifepillar** [comment]
Curiously, I can reproduce the problem when `default-terminal` is set to `xterm-256color` in `.tmux.conf`:

```
set -g  default-terminal            "xterm-256color"
set -ga terminal-overrides          ",xterm-256color:Tc"
```

But that is _not_ a correct value: according to tmux's manual, `default-terminal` must be `screen-*` or `tmux-*`. When I use the following settings instead (in iTerm2, the terminal is set to xterm-256color):

```
set -g  default-terminal            "tmux-256color"
set -ga terminal-overrides          ",xterm-256color:Tc"
```

I get no syntax coloring and changing color scheme has no effect: Vim simply uses the terminal colors. In all cases, `termguicolors` is set, of course. Btw, the value of `t_ut` does not seem to matter.

Below you find my configuration, including terminfo files (which I copied from ncurses 6.0_1 into `~/.terminfo`, so these should be more recent than the ones in OS X):
- OS X 10.11.5
- Vim 7.4 1-1910 (Homebrew)
- tmux 2.2
- iTerm2 3.0.20160607-nightly

In iTerm2, inside tmux:

```
$ echo $TERM`
tmux-256color
$ infocmp $TERM
#   Reconstructed via infocmp from file: /Users/me/.terminfo/74/tmux-256color
tmux-256color|tmux with 256 colors,
    am, hs, km, mir, msgr, xenl,
    colors#256, cols#80, it#8, lines#24, pairs#32767,
    acsc=++\,\,--..00``aaffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
    bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
    clear=\E[H\E[J, cnorm=\E[34h\E[?25h, cr=^M,
    csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
    cud=\E[%p1%dB, cud1=^J, cuf=\E[%p1%dC, cuf1=\E[C,
    cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\EM,
    cvvis=\E[34l, dch=\E[%p1%dP, dch1=\E[P, dim=\E[2m,
    dl=\E[%p1%dM, dl1=\E[M, dsl=\E]0;\007, ed=\E[J, el=\E[K,
    el1=\E[1K, enacs=\E(B\E)0, flash=\Eg, fsl=^G, home=\E[H,
    ht=^I, hts=\EH, ich=\E[%p1%d@, il=\E[%p1%dL, il1=\E[L,
    ind=^J, is2=\E)0, kbs=^H, kcbt=\E[Z, kcub1=\EOD, kcud1=\EOB,
    kcuf1=\EOC, kcuu1=\EOA, kdch1=\E[3~, kend=\E[4~, kf1=\EOP,
    kf10=\E[21~, kf11=\E[23~, kf12=\E[24~, kf2=\EOQ, kf3=\EOR,
    kf4=\EOS, kf5=\E[15~, kf6=\E[17~, kf7=\E[18~, kf8=\E[19~,
    kf9=\E[20~, khome=\E[1~, kich1=\E[2~, kmous=\E[M,
    knp=\E[6~, kpp=\E[5~, nel=\EE, op=\E[39;49m, rc=\E8,
    rev=\E[7m, ri=\EM, ritm=\E[23m, rmacs=^O, rmcup=\E[?1049l,
    rmir=\E[4l, rmkx=\E[?1l\E>, rmso=\E[27m, rmul=\E[24m,
    rs2=\Ec\E[?1000l\E[?25h, sc=\E7,
    setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
    setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
    sgr=\E[0%?%p6%t;1%;%?%p1%t;3%;%?%p2%t;4%;%?%p3%t;7%;%?%p4%t;5%;%?%p5%t;2%;m%?%p9%t\016%e\017%;,
    sgr0=\E[m\017, sitm=\E[3m, smacs=^N, smcup=\E[?1049h,
    smir=\E[4h, smkx=\E[?1h\E=, smso=\E[7m, smul=\E[4m,
    tbc=\E[3g, tsl=\E]0;,

$ infocmp xterm-256color
#   Reconstructed via infocmp from file: /Users/me/.terminfo/78/xterm-256color
xterm-256color|xterm with 256 colors,
    am, bce, ccc, km, mc5i, mir, msgr, npc, xenl,
    colors#256, cols#80, it#8, lines#24, pairs#32767,
    acsc=``aaffggiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
    bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
    clear=\E[H\E[2J, cnorm=\E[?12l\E[?25h, cr=^M,
    csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
    cud=\E[%p1%dB, cud1=^J, cuf=\E[%p1%dC, cuf1=\E[C,
    cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\E[A,
    cvvis=\E[?12;25h, dch=\E[%p1%dP, dch1=\E[P, dim=\E[2m,
    dl=\E[%p1%dM, dl1=\E[M, ech=\E[%p1%dX, ed=\E[J, el=\E[K,
    el1=\E[1K, flash=\E[?5h$<100/>\E[?5l, home=\E[H,
    hpa=\E[%i%p1%dG, ht=^I, hts=\EH, ich=\E[%p1%d@,
    il=\E[%p1%dL, il1=\E[L, ind=^J, indn=\E[%p1%dS,
    initc=\E]4;%p1%d;rgb\:%p2%{255}%*%{1000}%/%2.2X/%p3%{255}%*%{1000}%/%2.2X/%p4%{255}%*%{1000}%/%2.2X\E\\,
    invis=\E[8m, is2=\E[!p\E[?3;4l\E[4l\E>, kDC=\E[3;2~,
    kEND=\E[1;2F, kHOM=\E[1;2H, kIC=\E[2;2~, kLFT=\E[1;2D,
    kNXT=\E[6;2~, kPRV=\E[5;2~, kRIT=\E[1;2C, kb2=\EOE, kbs=^H,
    kcbt=\E[Z, kcub1=\EOD, kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA,
    kdch1=\E[3~, kend=\EOF, kent=\EOM, kf1=\EOP, kf10=\E[21~,
    kf11=\E[23~, kf12=\E[24~, kf13=\E[1;2P, kf14=\E[1;2Q,
    kf15=\E[1;2R, kf16=\E[1;2S, kf17=\E[15;2~, kf18=\E[17;2~,
    kf19=\E[18;2~, kf2=\EOQ, kf20=\E[19;2~, kf21=\E[20;2~,
    kf22=\E[21;2~, kf23=\E[23;2~, kf24=\E[24;2~,
    kf25=\E[1;5P, kf26=\E[1;5Q, kf27=\E[1;5R, kf28=\E[1;5S,
    kf29=\E[15;5~, kf3=\EOR, kf30=\E[17;5~, kf31=\E[18;5~,
    kf32=\E[19;5~, kf33=\E[20;5~, kf34=\E[21;5~,
    kf35=\E[23;5~, kf36=\E[24;5~, kf37=\E[1;6P, kf38=\E[1;6Q,
    kf39=\E[1;6R, kf4=\EOS, kf40=\E[1;6S, kf41=\E[15;6~,
    kf42=\E[17;6~, kf43=\E[18;6~, kf44=\E[19;6~,
    kf45=\E[20;6~, kf46=\E[21;6~, kf47=\E[23;6~,
    kf48=\E[24;6~, kf49=\E[1;3P, kf5=\E[15~, kf50=\E[1;3Q,
    kf51=\E[1;3R, kf52=\E[1;3S, kf53=\E[15;3~, kf54=\E[17;3~,
    kf55=\E[18;3~, kf56=\E[19;3~, kf57=\E[20;3~,
    kf58=\E[21;3~, kf59=\E[23;3~, kf6=\E[17~, kf60=\E[24;3~,
    kf61=\E[1;4P, kf62=\E[1;4Q, kf63=\E[1;4R, kf7=\E[18~,
    kf8=\E[19~, kf9=\E[20~, khome=\EOH, kich1=\E[2~,
    kind=\E[1;2B, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
    kri=\E[1;2A, mc0=\E[i, mc4=\E[4i, mc5=\E[5i, meml=\El,
    memu=\Em, op=\E[39;49m, rc=\E8, rev=\E[7m, ri=\EM,
    rin=\E[%p1%dT, ritm=\E[23m, rmacs=\E(B, rmam=\E[?7l,
    rmcup=\E[?1049l, rmir=\E[4l, rmkx=\E[?1l\E>,
    rmm=\E[?1034l, rmso=\E[27m, rmul=\E[24m, rs1=\Ec,
    rs2=\E[!p\E[?3;4l\E[4l\E>, sc=\E7,
    setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
    setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
    sgr=%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p5%t;2%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m,
    sgr0=\E(B\E[m, sitm=\E[3m, smacs=\E(0, smam=\E[?7h,
    smcup=\E[?1049h, smir=\E[4h, smkx=\E[?1h\E=,
    smm=\E[?1034h, smso=\E[7m, smul=\E[4m, tbc=\E[3g,
    u6=\E[%i%d;%dR, u7=\E[6n, u8=\E[?1;2c, u9=\E[c,
    vpa=\E[%i%p1%dd,
```

**Comment by wilywampa** [comment]
@lifepillar When `$TERM` doesn't contain `xterm` as in tmux, you need to set `t_8f` and `t_8b` manually as shown in @ruiafonsopereira's comment (or see `:help xterm-true-color`).

@AlessandroYorba That works for 256 color terminals but has no effect in a true color terminal (which is the subject of this issue).

**Comment by lifepillar** [comment]
>I get no syntax coloring and changing color scheme has no effect: Vim simply uses the terminal colors

I have just discovered that `t_8f` and `t_8b` are empty when `default-terminal` is `tmux-256color`. After manually setting those options, I can reproduce the OP's problem even when tmux is configured correctly.

**Comment by lifepillar** [comment]
@wilywampa Thanks, didn't notice that. After setting `t_8f` and `t_8b` I can reproduce the OP's problem even when tmux is configured correctly.

**Comment by nuko8** [comment]
It looks to me that both vim and tmux work correctly.

Vim fills the background with the color specified by the colorscheme in use in an optimized way (I mean, it updates only regions that really need update), and tmux does a similar thing with the color either inherited from the underlying terminal or set by the user in `~/.tmux.conf`.

If those two colors are different from each other,  the consequence is obvious as shown in the pictures above.

What is missing here is to specify which color to be used for the background color, colorscheme's or tmux's.

If you prefer to colorscheme's, you have to either tell tmux about that or adjust the background color of the underlying terminal to colorscheme's so that tmux can use it as its default background color.

I think the best is the latter.  The setting is easily done with the "Preferences..." window, and more importantly, vim won't be involved in unnecessary drawing operations.

But if you still prefer to the former, the following idea might work for you.

In your `~/.vim/vimrc`, define

``` VimL
function! s:GetNormalBG()
    return synIDattr(synIDtrans(hlID('Normal')), 'bg#')
endfunction

function! s:UpdateTmuxPaneBG()
    if has('gui_running') || !exists('$TMUX')
        return
    endif
    call system("tmux select-pane -P 'bg=" . s:GetNormalBG() . "'")
endfunction

function! s:RestoreTmuxPaneBG()
    if has('gui_running') || !exists('$TMUX')
        return
    endif
    call system("tmux select-pane -P 'bg=default'")
endfunction
```

Then, set autocommands up so that they are invoked in relevant events:

``` VimL
autocmd ColorScheme * call s:UpdateTmuxPaneBG()
autocmd VimLeave * call s:RestoreTmuxPaneBG()
```

Finally, have tmux redraw the background with the color specified by vim:

``` VimL
call s:UpdateTmuxPaneBG()
```

One thing to note: According to `tmux(1)`,  while the command  `tmux select-pane -P 'bg=<color>'` accepts a hexdecimal string such as `#rrggbb`,  it chooses the closest match from the default 256 color set.  Therefore, there are some corner cases where the resulting color approximation is not satisfactory.

That said, I'm now enjoying the Apprentice colorscheme on iTerm2 3.0.1 + tmux 2.2. 

Best,
Kazunobu Kuriyama

**Comment by djmoch** [comment]
@nuko8 This may be a valid workaround, but it doesn't address the issue, which is that `t_ut` is not respected when `termguicolors` is set.

**Comment by nuko8** [comment]
From my point of view, `t_ut` is irrelevant to the issue from the beginning.  It's useless for the underlying terminal because it already leaves drawing operations to tmux, and, as far as I know, tmux doesn't know what to do with `t_ut`.

**Comment by djmoch** [comment]
@nuko8 No one is suggesting tmux _should_ know what to do with `t_ut`. It's an option to tell _Vim_ to use the theme's background color. It's common practice for Vim users inside tmux to use `t_ut` to fix this issue in a 256 color mode (just look [here](http://vi.stackexchange.com/questions/238/tmux-is-changing-part-of-the-background-in-vim?lq=1) and [here](http://sunaku.github.io/vim-256color-bce.html)), but the problem we're finding is that `t_ut` doesn't work when `termguicolors` is set. You've found a different way to work around the issue, and that's fine, but there's no reason `t_ut` shouldn't work, and that's why this issue was opened.

**Comment by vim-ml** [comment]
Hi Bram and list,

It seems that discussions on GitHub are not synced in the mailing list. Thus I'm leaving here the link that has the latest comments on this.

https://github.com/vim/vim/issues/804#issuecomment-224855265

Thanks.

**Comment by chrisbra** [comment]
don't know why vim-dev did not get all comments. It seems, that E-Mail account did not get any notifications. Not sure why.

**Comment by ninrod** [comment]
I think commit d18f672fc9477f3c0cb7cc4ce8d9237ed825c612 should close this issue.

**Comment by wilywampa** [comment]
Thanks! Closed via https://github.com/vim/vim/commit/d18f672fc9477f3c0cb7cc4ce8d9237ed825c612.
