### ISSUE TITLE
vim9: source legacy script in vim9

### ISSUE THREAD

**Issue by lkjell** [vim/vim#8040]
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Describe the bug**
Unable to source legacy vim script from vim9script

**To Reproduce**
turn vimrc to vim9scrip
source a legacy script

**Expected behavior**
Hope it is possible since sourcing vim9script from legacy script is possible

**Screenshots**
If applicable, copy/paste the text or add screenshots to help explain your problem.

**Environment (please complete the following information):**
 - VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 26 2021 00:21:09)
Included patches: 1-2653
 - OS: Arch linux
 - Terminal: Mate Terminal, 

**Additional context**
Sourcing legacy script from vim9script can be problematic because by default everything vim9script scope is local. However since legacy scrpts' scope is globally this should not be a problem.

**Comment by lkjell** [comment]
I think I figured out the problem. When vim9script source a legacy script it is more stingy on white space in the legacy script than the other way around.

**Comment by brammool** [comment]
Please give specific examples and the errors you encounter.

**Comment by lkjell** [comment]
Strange I am unable to reproduce the error now.
The initial problem was space between `<silent> <leader> `

```
nnoremap <silent> <leader>      :<c-u>WhichKey '<Space>'<CR>
nnoremap <silent> <localleader> :<c-u>WhichKey  ','<CR>
```
 from the vim-which-key plugin. https://github.com/liuchengxu/vim-which-key/tree/master/doc

**Comment by brammool** [comment]
Let's close it then.  Please reopen if you have a reproducible example (without loading some plugin if possible).
