### ISSUE TITLE
Possible issue with macvim internal function mode()

### ISSUE THREAD

**Issue by retiredff** [vim/vim#8044]

**Comment by retiredff** [comment]
I use mode() on the StatusLine to display the current mode like this;
set statusline+=%{g:mode_map[mode()]}

let g:mode_map = {
    \ '__'     : ' - ',
    \ 'c'      : ' COMMAND ',
    \ 'i'      : ' INSERT ',
    \ 'ic'     : ' INSERT ',
    \ 'ix'     : ' INSERT ',
    \ 'n'      : ' NORMAL ',
    \ 'multi'  : ' MULTI ',
    \ 'ni'     : ' NORMAL ',
    \ 'no'     : ' NORMAL ',
    \ 'R'      : ' REPLACE ',
    \ 'Rv'     : ' REPLACE ',
    \ 's'      : ' I-SELECT ',
    \ 'S'      : ' I-SELECT ',
    \ 't'      : ' TERMINAL ',
    \ 'v'      : ' VISUAL ',
    \ 'V'      : ' VISUAL ',
    \ ''     : ' V-BLOCK ',
    \ '!'      : ' SHELL ',
    \ }

The problem is MODE() never returns 'c' when pressing ':' to enter command mode. Is this a bug or not? Or does mode() not work the way I think it does?

**Comment by retiredff** [comment]
I am not a developer, just a weekend hack and trying to teach myself MacVim.

Thanks

**Comment by lacygoill** [comment]
@retiredff Try to add this into your vimrc:

    augroup my_statusline | autocmd!
        autocmd CmdlineEnter * redrawstatus
    augroup END

It should make Vim redraw the status line of the current window when you enter the command-line, whose contents should then be updated.  If you want Vim to redraw *all* the status lines, and not just the one of the current window, append a bang to `:redrawstatus`.

For more info see:

- [`:h :autocmd`](https://vimhelp.org/autocmd.txt.html#:au)
- [`:h :augroup`](https://vimhelp.org/autocmd.txt.html#:augroup)
- [`:h :redrawstatus`](https://vimhelp.org/various.txt.html#:redraws)
- [`:h CmdlineEnter`](https://vimhelp.org/autocmd.txt.html#CmdlineEnter)

For questions, visit the [users mailing list](https://groups.google.com/g/vim_use), [vi.stackexchange.com](https://vi.stackexchange.com/), or the [`#vim` irc channel](https://www.vi-improved.org/).

**Comment by retiredff** [comment]
Thank you, works like a charm!

Tony

**Comment by chrisbra** [comment]
Hm, in Neovim this works out of the box. It looks like the following patch would be needed. Credits to @raichoo and @justinmk from Neovim:


```patch
diff --git a/src/ex_getln.c b/src/ex_getln.c
index dc451f455..97a8b6bc2 100644
--- a/src/ex_getln.c
+++ b/src/ex_getln.c
@@ -1708,6 +1708,14 @@ getcmdline_int(
     // and execute commands. Display may be messed up a bit.
     if (did_emsg)
        redrawcmd();
+
+    // redraw the statusline for statuslines that display the current mode
+    // using the mode() function.
+    if (!cmd_silent && msg_scrolled == 0) {
+      curwin->w_redr_status = TRUE;
+      redraw_statuslines();
+    }
+
     did_emsg = FALSE;
     got_int = FALSE;

```

**Comment by retiredff** [comment]
thanks for the reply. Someone also answered and told me to add this to my .vimrc. After adding this when going into Command mode my function properly displays COMMAND as it should.

" add this so COMMAND will show when changing to command mode.
" leave the bang '!' off if updates for other windows is not required
augroup my_statusline | autocmd!
    autocmd CmdlineEnter * redrawstatus!
augroup END

**Comment by brammool** [comment]
To reduce redraws a bit more I added a check for 'statusline' not being empty.  I hope this works for everyone.
