### ISSUE TITLE
vim9script: import * as That from "somefile.vim" not working inside functions

### ISSUE THREAD

**Issue by ghost** [vim/vim#8045]
**Describe the bug**
When doing an aliased import for all symbols in another file, I can't refer to that alias inside functions.

**To Reproduce**
1. In file somelib.vim

```vimscript
vim9script

export def SomeFunc(): number
  return 1
enddef
```

2. In file sometest.vim, in the same directory as somelib.vim

```vimscript
vim9script

import * as someAlias from "./somelib.vim"

def AnotherFunc()
  echo someAlias.SomeFunc()
enddef

AnotherFunc()
```

3. Run sometest.vim with `so %`
4. An error is generated: E1001: variable not found: someAlias
5. Edit sometest.vim

```vimscript
vim9script

import * as someAlias from "./somelib.vim"

def AnotherFunc()
  echo someAlias.SomeFunc()
enddef

echo someAlias.SomeFunc()
```
6. Run `so %` again in sometest.vim.
7. This time the number "1" is echoed, as expected.
8. Replace `echo someAlias.SomeFunc()` with `call someAlias.SomeFunc()`.
9. Another error is generated: E121: Undefined variable: someAlias.

**Expected behavior**
I would expect to be able to use the alias inside functions as well.

**Environment (please complete the following information):**
 - Vim version: 8.2
 - OS:  Ubuntu 20.04
 - Terminal: GNOME terminal

**Comment by lacygoill** [comment]
And if `someAlias.SomeFunc()` is prefixed with `s:`, Vim crashes:
```vim
vim9script
var dir = '/tmp/test/import'
mkdir(dir, 'p')
var lines =<< trim END
    vim9script
    import * as someAlias from './somelib.vim'
    def Func()
        echo s:someAlias.SomeFunc()
    enddef
    defcompile
END
writefile(dir .. '/sometest.vim')
var lines =<< trim END
    vim9script
    export def SomeFunc(): number
      return 1
    enddef
END
writefile(dir .. '/somelib.vim')
exe 'so ' .. dir .. '/sometest.vim'
```
Here is a backtrace:

    [New LWP 26009]
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
    Core was generated by `/home/user/Vcs/vim/src/vim -Nu NONE -S /tmp/crash.vim'.
    Program terminated with signal SIGSEGV, Segmentation fault.
    #0  0x00007f980aad0777 in kill () from /lib/x86_64-linux-gnu/libc.so.6

    Thread 1 (Thread 0x7f980dfdf9c0 (LWP 26009)):
    #0  0x00007f980aad0777 in kill () from /lib/x86_64-linux-gnu/libc.so.6
    No symbol table info available.
    #1  0x00000000005620fb in may_core_dump () at os_unix.c:3447
    No locals.
    #2  0x000000000056209f in mch_exit (r=1) at os_unix.c:3413
    No locals.
    #3  0x00000000006d45fb in getout (exitval=1) at main.c:1698
    No locals.
    #4  0x0000000000523ddf in preserve_exit () at misc1.c:2190
            buf = 0x0
    #5  0x000000000055f992 in deathtrap (sigarg=11) at os_unix.c:1123
            entered = 1
            i = 7
    #6  <signal handler called>
    No symbol table info available.
    #7  0x0000000000654352 in compile_load_scriptvar (cctx=0x7ffd47f1a160, name=0xc64940 "someAlias", start=0x0, end=0x0, error=1) at vim9compile.c:2693
            cc = 0
            ufunc = 0x7ffd47f1d1f0
            type = 0xa
            p = 0x7ffd47f197a0 "P\230\361G\375\177"
            exp_name = 0x0
            si = 0xc65300
            idx = -2
            import = 0xc681d0
    #8  0x000000000065480a in compile_load (arg=0x7ffd47f19f88, end_arg=0xc648f4 ".SomeFunc()", cctx=0x7ffd47f1a160, is_expr=1, error=1) at vim9compile.c:2818
            isn_type = ISN_DROP
            type = 0x7347f19870
            name = 0xc64940 "someAlias"
            end = 0xc648f4 ".SomeFunc()"
            res = 0
            prev_called_emsg = 3
    #9  0x00000000006581ab in compile_expr7 (arg=0x7ffd47f19f88, cctx=0x7ffd47f1a160, ppconst=0x7ffd47f19c00) at vim9compile.c:4371
            p = 0xc648f4 ".SomeFunc()"
            r = 0
            start_leader = 0xc648e9 "s:someAlias.SomeFunc()"
            end_leader = 0xc648e9 "s:someAlias.SomeFunc()"
            ret = 2
            rettv = 0x7ffd47f19c00
            used_before = 0
    #10 0x000000000065844a in compile_expr7t (arg=0x7ffd47f19f88, cctx=0x7ffd47f1a160, ppconst=0x7ffd47f19c00) at vim9compile.c:4436
            want_type = 0x0
    #11 0x000000000065855b in compile_expr6 (arg=0x7ffd47f19f88, cctx=0x7ffd47f1a160, ppconst=0x7ffd47f19c00) at vim9compile.c:4472
            op = 0x0
            next = 0x0
            ppconst_used = 0
    #12 0x0000000000658876 in compile_expr5 (arg=0x7ffd47f19f88, cctx=0x7ffd47f1a160, ppconst=0x7ffd47f19c00) at vim9compile.c:4551
            op = 0x0
            next = 0x0
            oplen = 0
            ppconst_used = 0
    #13 0x0000000000658d30 in compile_expr4 (arg=0x7ffd47f19f88, cctx=0x7ffd47f1a160, ppconst=0x7ffd47f19c00) at vim9compile.c:4664
            type = EXPR_UNKNOWN
            p = 0x0
            next = 0x0
            len = 2
            type_is = 0
            ppconst_used = 0
    #14 0x000000000065943c in compile_expr3 (arg=0x7ffd47f19f88, cctx=0x7ffd47f1a160, ppconst=0x7ffd47f19c00) at vim9compile.c:4862
            ppconst_used = 0
    #15 0x00000000006594a3 in compile_expr2 (arg=0x7ffd47f19f88, cctx=0x7ffd47f1a160, ppconst=0x7ffd47f19c00) at vim9compile.c:4887
            ppconst_used = 0
    #16 0x000000000065954e in compile_expr1 (arg=0x7ffd47f19f88, cctx=0x7ffd47f1a160, ppconst=0x7ffd47f19c00) at vim9compile.c:4926
            p = 0x0
            ppconst_used = 0
            next = 0x0
    #17 0x0000000000659c07 in compile_expr0_ext (arg=0x7ffd47f19f88, cctx=0x7ffd47f1a160, is_const=0x0) at vim9compile.c:5083
            ppconst = {pp_tv = {{v_type = VAR_UNKNOWN, v_lock = 0 '\000', vval = {v_number = 0, v_float = 0, v_string = 0x0, v_list = 0x0, v_dict = 0x0, v_partial = 0x0, v_job = 0x0, v_channel = 0x0, v_blob = 0x0}} <repeats 50 times>}, pp_used = 0, pp_is_const = 0}
    #18 0x0000000000659cb5 in compile_expr0 (arg=0x7ffd47f19f88, cctx=0x7ffd47f1a160) at vim9compile.c:5101
    No locals.
    #19 0x000000000065fe69 in compile_mult_expr (arg=0xc648e9 "s:someAlias.SomeFunc()", cmdidx=136, cctx=0x7ffd47f1a160) at vim9compile.c:8046
            p = 0xc648e9 "s:someAlias.SomeFunc()"
            prev = 0xc648e9 "s:someAlias.SomeFunc()"
            count = 0
    #20 0x0000000000661a7b in compile_def_function (ufunc=0xc66a50, check_return_type=0, profiling=0, outer_cctx=0x0) at vim9compile.c:8782
            ea = {arg = 0x0, nextcmd = 0x0, cmd = 0xc648e4 "echo s:someAlias.SomeFunc()", cmdlinep = 0x7ffd47f1a028, cmdline_tofree = 0x0, cmdidx = CMD_echo, argt = 17565700, skip = 0, forceit = 0, addr_count = 0, line1 = 0, line2 = 0, addr_type = ADDR_LINES, flags = 0, do_ecmd_cmd = 0x0, do_ecmd_lnum = 0, append = 0, usefilter = 0, amount = 0, regname = 0, force_bin = 0, read_edit = 0, force_ff = 0, force_enc = 0, bad_char = 0, useridx = 0, errmsg = 0x0, getline = 0x0, cookie = 0x0, cstack = 0x0}
            starts_with_colon = 0
            cmd = 0xc648e4 "echo s:someAlias.SomeFunc()"
            local_cmdmod = {cmod_flags = 0, cmod_split = 0, cmod_tab = 0, cmod_filter_regmatch = {regprog = 0x0, startp = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, endp = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, rm_ic = 0}, cmod_filter_force = 0, cmod_verbose = 0, cmod_save_ei = 0x0, cmod_did_sandbox = 0, cmod_verbose_save = 0, cmod_save_msg_silent = 0, cmod_save_msg_scroll = 0, cmod_did_esilent = 0}
            line = 0xc648e0 "    echo s:someAlias.SomeFunc()"
            p = 0xc648e9 "s:someAlias.SomeFunc()"
            errormsg = 0x0
            cctx = {ctx_ufunc = 0xc66a50, ctx_lnum = 0, ctx_line_start = 0xc648e0 "    echo s:someAlias.SomeFunc()", ctx_instr = {ga_len = 0, ga_maxlen = 0, ga_itemsize = 24, ga_growsize = 50, ga_data = 0x0}, ctx_profiling = 0, ctx_locals = {ga_len = 0, ga_maxlen = 0, ga_itemsize = 32, ga_growsize = 10, ga_data = 0x0}, ctx_locals_count = 0, ctx_has_closure = 0, ctx_imports = {ga_len = 0, ga_maxlen = 0, ga_itemsize = 40, ga_growsize = 10, ga_data = 0x0}, ctx_skip = SKIP_NOT, ctx_scope = 0x0, ctx_had_return = 0, ctx_outer = 0x0, ctx_outer_used = 0, ctx_type_stack = {ga_len = 0, ga_maxlen = 0, ga_itemsize = 8, ga_growsize = 50, ga_data = 0x0}, ctx_type_list = 0xc66aa8, ctx_has_cmdmod = 0}
            instr = 0x7ffd47f1a178
            did_emsg_before = 0
            ret = 0
            save_current_sctx = {sc_sid = 2, sc_seq = 2, sc_lnum = 0, sc_version = 999999}
            save_estack_compiling = 0
            do_estack_push = 1
            new_def_function = 1
            prof_lnum = -1
    #21 0x000000000064c732 in ex_defcompile (eap=0x7ffd47f1a410) at userfunc.c:4234
            todo = 0
            changed = 2
            hi = 0x99d0b0 <func_hashtab+112>
            ufunc = 0xc66a50
    #22 0x0000000000499f17 in do_one_cmd (cmdlinep=0x7ffd47f1a648, flags=7, cstack=0x7ffd47f1a740, fgetline=0x5bffa9 <getsourceline>, cookie=0x7ffd47f1ae90) at ex_docmd.c:2591
            p = 0xc6683a ""
            lnum = 0
            n = 140290991190484
            errormsg = 0x0
            after_modifier = 0xc66830 "defcompile"
            ea = {arg = 0xc6683a "", nextcmd = 0x0, cmd = 0xc66830 "defcompile", cmdlinep = 0x7ffd47f1a648, cmdline_tofree = 0x0, cmdidx = CMD_defcompile, argt = 17563904, skip = 0, forceit = 0, addr_count = 0, line1 = 1, line2 = 1, addr_type = ADDR_NONE, flags = 0, do_ecmd_cmd = 0x0, do_ecmd_lnum = 0, append = 0, usefilter = 0, amount = 0, regname = 0, force_bin = 0, read_edit = 0, force_ff = 0, force_enc = 0, bad_char = 0, useridx = 0, errmsg = 0x0, getline = 0x5bffa9 <getsourceline>, cookie = 0x7ffd47f1ae90, cstack = 0x7ffd47f1a740}
            save_cmdmod = {cmod_flags = 0, cmod_split = 0, cmod_tab = 0, cmod_filter_regmatch = {regprog = 0x0, startp = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, endp = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, rm_ic = 0}, cmod_filter_force = 0, cmod_verbose = 0, cmod_save_ei = 0x0, cmod_did_sandbox = 0, cmod_verbose_save = 0, cmod_save_msg_silent = 0, cmod_save_msg_scroll = 0, cmod_did_esilent = 0}
            save_reg_executing = 0
            ni = 0
            cmd = 0xc66830 "defcompile"
            starts_with_colon = 0
            may_have_range = 0
            vim9script = 1
            did_set_expr_line = 0
            sourcing = 1
    #23 0x0000000000497299 in do_cmdline (cmdline=0xc65710 "vim9script", fgetline=0x5bffa9 <getsourceline>, cookie=0x7ffd47f1ae90, flags=7) at ex_docmd.c:1000
            next_cmdline = 0xc66830 "defcompile"
            cmdline_copy = 0xc66830 "defcompile"
            used_getline = 1
            recursive = 4
            msg_didout_before_start = 0
            count = 6
            did_inc = 0
            retval = 1
            cstack = {cs_flags = {0 <repeats 50 times>}, cs_pending = '\000' <repeats 49 times>, cs_pend = {csp_rv = {0x0 <repeats 50 times>}, csp_ex = {0x0 <repeats 50 times>}}, cs_forinfo = {0x0 <repeats 50 times>}, cs_line = {0 <repeats 50 times>}, cs_block_id = {0 <repeats 50 times>}, cs_script_var_len = {0 <repeats 50 times>}, cs_idx = -1, cs_looplevel = 0, cs_trylevel = 0, cs_emsg_silent_list = 0x0, cs_lflags = 0 '\000'}
            lines_ga = {ga_len = 0, ga_maxlen = 0, ga_itemsize = 16, ga_growsize = 10, ga_data = 0x0}
            current_line = 0
            current_line_before = 0
            fname = 0xc643a0 "/tmp/test/import/sometest.vim"
            breakpoint = 0x7ffd47f1aeb0
            dbg_tick = 0x7ffd47f1aec0
            debug_saved = {trylevel = 0, force_abort = 0, caught_stack = 0x0, vv_exception = 0x0, vv_throwpoint = 0x0, did_emsg = 0, got_int = 0, did_throw = 0, need_rethrow = 0, check_cstack = 0, current_exception = 0x0}
            initial_trylevel = 0
            saved_msg_list = 0x7ffd47f1b240
            private_msg_list = 0x0
            cmd_getline = 0x5bffa9 <getsourceline>
            cmd_cookie = 0x7ffd47f1ae90
            cmd_loop_cookie = {lines_gap = 0x7ffd47f1a838, current_line = 0, repeating = 0, getline = 0x7ffd47f1aa80, cookie = 0x6e284a <vim_vsnprintf_typval+8914>}
            real_cookie = 0x7ffd47f1ae90
            getline_is_func = 0
            call_depth = 4
            estack_len_before = 0
    #24 0x00000000005bf5ef in do_source (fname=0xc64e03 "/tmp/test/import/sometest.vim", check_other=0, is_vimrc=0, ret_sid=0x0) at scriptfile.c:1404
            cookie = {fp = 0xc650d0, nextline = 0x0, sourcing_lnum = 8, finished = 0, breakpoint = 0, fname = 0xc643a0 "/tmp/test/import/sometest.vim", dbg_tick = 0, level = 3, conv = {vc_type = 0, vc_factor = 0, vc_fd = 0x7ffd47f1af28, vc_fail = 12996099}}
            p = 0xc650d0 "\230$\255\373/tes ", <incomplete sequence \306>
            fname_exp = 0xc64350 "/tmp/test/import/sometest.vim"
            firstline = 0xc65710 "vim9script"
            retval = 0
            save_current_sctx = {sc_sid = 1, sc_seq = 1, sc_lnum = 0, sc_version = 999999}
            last_current_SID = 3
            last_current_SID_seq = 3
            funccalp_entry = {top_funccal = 0x0, next = 0x7ffd47f1c500}
            save_debug_break_level = -1
            sid = 0
            si = 0xc65300
            tv_rel = {tv_sec = 140725810474624, tv_usec = 5401827}
            tv_start = {tv_sec = 469358456448, tv_usec = 12996127}
            wait_start = {tv_sec = 140725810474624, tv_usec = 7141997}
            trigger_source_post = 0
            estack_len_before = 4
    #25 0x00000000005be89b in cmd_source (fname=0xc64e03 "/tmp/test/import/sometest.vim", eap=0x7ffd47f1b000) at scriptfile.c:971
    No locals.
    #26 0x00000000005be96f in ex_source (eap=0x7ffd47f1b000) at scriptfile.c:997
    No locals.
    #27 0x0000000000499f17 in do_one_cmd (cmdlinep=0x7ffd47f1b238, flags=3, cstack=0x7ffd47f1b330, fgetline=0x5bffa9 <getsourceline>, cookie=0x7ffd47f1c560) at ex_docmd.c:2591
            p = 0xc64e02 " /tmp/test/import/sometest.vim"
            lnum = 140725810475472
            n = 140725810475464
            errormsg = 0x0
            after_modifier = 0xc64e00 "so /tmp/test/import/sometest.vim"
            ea = {arg = 0xc64e03 "/tmp/test/import/sometest.vim", nextcmd = 0x0, cmd = 0xc64e00 "so /tmp/test/import/sometest.vim", cmdlinep = 0x7ffd47f1b238, cmdline_tofree = 0x0, cmdidx = CMD_source, argt = 17563934, skip = 0, forceit = 0, addr_count = 0, line1 = 1, line2 = 1, addr_type = ADDR_NONE, flags = 0, do_ecmd_cmd = 0x0, do_ecmd_lnum = 0, append = 0, usefilter = 0, amount = 0, regname = 0, force_bin = 0, read_edit = 0, force_ff = 0, force_enc = 0, bad_char = 0, useridx = 0, errmsg = 0x0, getline = 0x5bffa9 <getsourceline>, cookie = 0x7ffd47f1c560, cstack = 0x7ffd47f1b330}
            save_cmdmod = {cmod_flags = 0, cmod_split = 0, cmod_tab = 0, cmod_filter_regmatch = {regprog = 0x0, startp = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, endp = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, rm_ic = 0}, cmod_filter_force = 0, cmod_verbose = 0, cmod_save_ei = 0x0, cmod_did_sandbox = 0, cmod_verbose_save = 0, cmod_save_msg_silent = 0, cmod_save_msg_scroll = 0, cmod_did_esilent = 0}
            save_reg_executing = 0
            ni = 0
            cmd = 0xc64e00 "so /tmp/test/import/sometest.vim"
            starts_with_colon = 0
            may_have_range = 0
            vim9script = 1
            did_set_expr_line = 0
            sourcing = 1
    #28 0x0000000000497299 in do_cmdline (cmdline=0xc64880 "so /tmp/test/import/sometest.vim", fgetline=0x5bffa9 <getsourceline>, cookie=0x7ffd47f1c560, flags=3) at ex_docmd.c:1000
            next_cmdline = 0xc64e00 "so /tmp/test/import/sometest.vim"
            cmdline_copy = 0xc64e00 "so /tmp/test/import/sometest.vim"
            used_getline = 0
            recursive = 4
            msg_didout_before_start = 0
            count = 1
            did_inc = 0
            retval = 1
            cstack = {cs_flags = {0 <repeats 50 times>}, cs_pending = '\000' <repeats 49 times>, cs_pend = {csp_rv = {0x0 <repeats 50 times>}, csp_ex = {0x0 <repeats 50 times>}}, cs_forinfo = {0x0 <repeats 50 times>}, cs_line = {0 <repeats 50 times>}, cs_block_id = {0 <repeats 50 times>}, cs_script_var_len = {0 <repeats 50 times>}, cs_idx = -1, cs_looplevel = 0, cs_trylevel = 0, cs_emsg_silent_list = 0x0, cs_lflags = 0 '\000'}
            lines_ga = {ga_len = 0, ga_maxlen = 0, ga_itemsize = 16, ga_growsize = 10, ga_data = 0x0}
            current_line = 0
            current_line_before = 0
            fname = 0xc3cce0 "/tmp/crash.vim"
            breakpoint = 0x7ffd47f1c580
            dbg_tick = 0x7ffd47f1c590
            debug_saved = {trylevel = 0, force_abort = 0, caught_stack = 0x0, vv_exception = 0x0, vv_throwpoint = 0x0, did_emsg = 0, got_int = 0, did_throw = 0, need_rethrow = 0, check_cstack = 0, current_exception = 0x0}
            initial_trylevel = 0
            saved_msg_list = 0x7ffd47f1bd20
            private_msg_list = 0x0
            cmd_getline = 0x5bffa9 <getsourceline>
            cmd_cookie = 0x7ffd47f1c560
            cmd_loop_cookie = {lines_gap = 0x7ffd47f1b920, current_line = 12996259, repeating = 0, getline = 0x0, cookie = 0x0}
            real_cookie = 0x7ffd47f1c560
            getline_is_func = 0
            call_depth = 4
            estack_len_before = 0
    #29 0x000000000046eda5 in ex_execute (eap=0x7ffd47f1bae0) at eval.c:6248
            arg = 0xc64ea3 ""
            rettv = {v_type = VAR_STRING, v_lock = 0 '\000', vval = {v_number = 0, v_float = 0, v_string = 0x0, v_list = 0x0, v_dict = 0x0, v_partial = 0x0, v_job = 0x0, v_channel = 0x0, v_blob = 0x0}}
            ret = 1
            p = 0xc64e00 "so /tmp/test/import/sometest.vim"
            ga = {ga_len = 32, ga_maxlen = 80, ga_itemsize = 1, ga_growsize = 80, ga_data = 0xc64880}
            len = 32
    #30 0x0000000000499f17 in do_one_cmd (cmdlinep=0x7ffd47f1bd18, flags=7, cstack=0x7ffd47f1be10, fgetline=0x5bffa9 <getsourceline>, cookie=0x7ffd47f1c560) at ex_docmd.c:2591
            p = 0xc64e83 " 'so ' .. dir .. '/sometest.vim'"
            lnum = 0
            n = 140290991190484
            errormsg = 0x0
            after_modifier = 0xc64e80 "exe 'so ' .. dir .. '/sometest.vim'"
            ea = {arg = 0xc64e84 "'so ' .. dir .. '/sometest.vim'", nextcmd = 0x0, cmd = 0xc64e80 "exe 'so ' .. dir .. '/sometest.vim'", cmdlinep = 0x7ffd47f1bd18, cmdline_tofree = 0x0, cmdidx = CMD_execute, argt = 17565700, skip = 0, forceit = 0, addr_count = 0, line1 = 1, line2 = 1, addr_type = ADDR_NONE, flags = 0, do_ecmd_cmd = 0x0, do_ecmd_lnum = 0, append = 0, usefilter = 0, amount = 0, regname = 0, force_bin = 0, read_edit = 0, force_ff = 0, force_enc = 0, bad_char = 0, useridx = 0, errmsg = 0x0, getline = 0x5bffa9 <getsourceline>, cookie = 0x7ffd47f1c560, cstack = 0x7ffd47f1be10}
            save_cmdmod = {cmod_flags = 0, cmod_split = 0, cmod_tab = 0, cmod_filter_regmatch = {regprog = 0x0, startp = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, endp = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, rm_ic = 0}, cmod_filter_force = 0, cmod_verbose = 0, cmod_save_ei = 0x0, cmod_did_sandbox = 0, cmod_verbose_save = 0, cmod_save_msg_silent = 0, cmod_save_msg_scroll = 0, cmod_did_esilent = 0}
            save_reg_executing = 0
            ni = 0
            cmd = 0xc64e80 "exe 'so ' .. dir .. '/sometest.vim'"
            starts_with_colon = 0
            may_have_range = 0
            vim9script = 1
            did_set_expr_line = 0
            sourcing = 1
    #31 0x0000000000497299 in do_cmdline (cmdline=0xc630b0 "vim9script", fgetline=0x5bffa9 <getsourceline>, cookie=0x7ffd47f1c560, flags=7) at ex_docmd.c:1000
            next_cmdline = 0xc64e80 "exe 'so ' .. dir .. '/sometest.vim'"
            cmdline_copy = 0xc64e80 "exe 'so ' .. dir .. '/sometest.vim'"
            used_getline = 1
            recursive = 4
            msg_didout_before_start = 0
            count = 8
            did_inc = 0
            retval = 1
            cstack = {cs_flags = {0 <repeats 50 times>}, cs_pending = '\000' <repeats 49 times>, cs_pend = {csp_rv = {0x0 <repeats 50 times>}, csp_ex = {0x0 <repeats 50 times>}}, cs_forinfo = {0x0 <repeats 50 times>}, cs_line = {0 <repeats 50 times>}, cs_block_id = {0 <repeats 50 times>}, cs_script_var_len = {0 <repeats 50 times>}, cs_idx = -1, cs_looplevel = 0, cs_trylevel = 0, cs_emsg_silent_list = 0x0, cs_lflags = 0 '\000'}
            lines_ga = {ga_len = 0, ga_maxlen = 0, ga_itemsize = 16, ga_growsize = 10, ga_data = 0x0}
            current_line = 0
            current_line_before = 0
            fname = 0xc3cce0 "/tmp/crash.vim"
            breakpoint = 0x7ffd47f1c580
            dbg_tick = 0x7ffd47f1c590
            debug_saved = {trylevel = 0, force_abort = 0, caught_stack = 0x0, vv_exception = 0x0, vv_throwpoint = 0x0, did_emsg = 0, got_int = 0, did_throw = 0, need_rethrow = 0, check_cstack = 0, current_exception = 0x0}
            initial_trylevel = 0
            saved_msg_list = 0x7ffd47f1c910
            private_msg_list = 0x0
            cmd_getline = 0x5bffa9 <getsourceline>
            cmd_cookie = 0x7ffd47f1c560
            cmd_loop_cookie = {lines_gap = 0xc39d40, current_line = 12819788, repeating = 0, getline = 0x21e000000a7, cookie = 0x0}
            real_cookie = 0x7ffd47f1c560
            getline_is_func = 0
            call_depth = 4
            estack_len_before = 0
    #32 0x00000000005bf5ef in do_source (fname=0xc62983 "/tmp/crash.vim", check_other=0, is_vimrc=0, ret_sid=0x0) at scriptfile.c:1404
            cookie = {fp = 0xc629a0, nextline = 0x0, sourcing_lnum = 20, finished = 0, breakpoint = 0, fname = 0xc3cce0 "/tmp/crash.vim", dbg_tick = 0, level = 1, conv = {vc_type = 0, vc_factor = 0, vc_fd = 0x147f1c5c0, vc_fail = 12986752}}
            p = 0xc629a0 "\230$\255\373/cra\300", <incomplete sequence \306>
            fname_exp = 0xc63090 "/tmp/crash.vim"
            firstline = 0xc630b0 "vim9script"
            retval = 0
            save_current_sctx = {sc_sid = -3, sc_seq = 0, sc_lnum = 0, sc_version = 0}
            last_current_SID = 3
            last_current_SID_seq = 3
            funccalp_entry = {top_funccal = 0x0, next = 0x0}
            save_debug_break_level = -1
            sid = 0
            si = 0xc62c80
            tv_rel = {tv_sec = 140725810480464, tv_usec = 5401827}
            tv_start = {tv_sec = 469358462288, tv_usec = 12986768}
            wait_start = {tv_sec = 140725810480464, tv_usec = 7141997}
            trigger_source_post = 0
            estack_len_before = 3
    #33 0x00000000005be89b in cmd_source (fname=0xc62983 "/tmp/crash.vim", eap=0x7ffd47f1c6d0) at scriptfile.c:971
    No locals.
    #34 0x00000000005be96f in ex_source (eap=0x7ffd47f1c6d0) at scriptfile.c:997
    No locals.
    #35 0x0000000000499f17 in do_one_cmd (cmdlinep=0x7ffd47f1c908, flags=11, cstack=0x7ffd47f1ca00, fgetline=0x0, cookie=0x0) at ex_docmd.c:2591
            p = 0xc62982 " /tmp/crash.vim"
            lnum = 140291046588416
            n = 140290990665088
            errormsg = 0x0
            after_modifier = 0xc62980 "so /tmp/crash.vim"
            ea = {arg = 0xc62983 "/tmp/crash.vim", nextcmd = 0x0, cmd = 0xc62980 "so /tmp/crash.vim", cmdlinep = 0x7ffd47f1c908, cmdline_tofree = 0x0, cmdidx = CMD_source, argt = 17563934, skip = 0, forceit = 0, addr_count = 0, line1 = 1, line2 = 1, addr_type = ADDR_NONE, flags = 0, do_ecmd_cmd = 0x0, do_ecmd_lnum = 0, append = 0, usefilter = 0, amount = 0, regname = 0, force_bin = 0, read_edit = 0, force_ff = 0, force_enc = 0, bad_char = 0, useridx = 0, errmsg = 0x0, getline = 0x0, cookie = 0x0, cstack = 0x7ffd47f1ca00}
            save_cmdmod = {cmod_flags = 0, cmod_split = 0, cmod_tab = 0, cmod_filter_regmatch = {regprog = 0x0, startp = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, endp = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, rm_ic = 0}, cmod_filter_force = 0, cmod_verbose = 0, cmod_save_ei = 0x0, cmod_did_sandbox = 0, cmod_verbose_save = 0, cmod_save_msg_silent = 0, cmod_save_msg_scroll = 0, cmod_did_esilent = 0}
            save_reg_executing = 0
            ni = 0
            cmd = 0xc62980 "so /tmp/crash.vim"
            starts_with_colon = 0
            may_have_range = 1
            vim9script = 0
            did_set_expr_line = 0
            sourcing = 1
    #36 0x0000000000497299 in do_cmdline (cmdline=0xc130d0 "so /tmp/crash.vim", fgetline=0x0, cookie=0x0, flags=11) at ex_docmd.c:1000
            next_cmdline = 0xc62980 "so /tmp/crash.vim"
            cmdline_copy = 0xc62980 "so /tmp/crash.vim"
            used_getline = 0
            recursive = 4
            msg_didout_before_start = 0
            count = 1
            did_inc = 0
            retval = 1
            cstack = {cs_flags = {0 <repeats 50 times>}, cs_pending = '\000' <repeats 49 times>, cs_pend = {csp_rv = {0x0 <repeats 50 times>}, csp_ex = {0x0 <repeats 50 times>}}, cs_forinfo = {0x0 <repeats 50 times>}, cs_line = {0 <repeats 50 times>}, cs_block_id = {0 <repeats 50 times>}, cs_script_var_len = {0 <repeats 50 times>}, cs_idx = -1, cs_looplevel = 0, cs_trylevel = 0, cs_emsg_silent_list = 0x0, cs_lflags = 0 '\000'}
            lines_ga = {ga_len = 0, ga_maxlen = 0, ga_itemsize = 16, ga_growsize = 10, ga_data = 0x0}
            current_line = 0
            current_line_before = 0
            fname = 0x0
            breakpoint = 0x0
            dbg_tick = 0x0
            debug_saved = {trylevel = 0, force_abort = 0, caught_stack = 0x0, vv_exception = 0x0, vv_throwpoint = 0x0, did_emsg = 0, got_int = 0, did_throw = 0, need_rethrow = 0, check_cstack = 0, current_exception = 0x0}
            initial_trylevel = 0
            saved_msg_list = 0x0
            private_msg_list = 0x0
            cmd_getline = 0x0
            cmd_cookie = 0x0
            cmd_loop_cookie = {lines_gap = 0xffffffff, current_line = 1207028248, repeating = 32765, getline = 0x7f980c59a9f0, cookie = 0x7f980dff84f8}
            real_cookie = 0x0
            getline_is_func = 0
            call_depth = 4
            estack_len_before = 0
    #37 0x0000000000496745 in do_cmdline_cmd (cmd=0xc130d0 "so /tmp/crash.vim") at ex_docmd.c:592
    No locals.
    #38 0x00000000006d6984 in exe_commands (parmp=0x99dee0 <params>) at main.c:3068
            i = 0
            estack_len_before = 2
    #39 0x00000000006d334f in vim_main2 () at main.c:760
    No locals.
    #40 0x00000000006d2c47 in main (argc=5, argv=0x7ffd47f1d1f8) at main.c:412
            i = 5

**Comment by lacygoill** [comment]
Sorry, the previous MWE contained an error; here is a new – corrected – one:
```vim
vim9script
var dir = '/tmp/test/import'
mkdir(dir, 'p')
var lines =<< trim END
    vim9script
    import * as someAlias from './somelib.vim'
    def Func()
        echo s:someAlias.SomeFunc()
    enddef
    defcompile
END
writefile(lines, dir .. '/sometest.vim')
var lines =<< trim END
    vim9script
    export def SomeFunc(): number
      return 1
    enddef
END
writefile(lines, dir .. '/somelib.vim')
exe 'so ' .. dir .. '/sometest.vim'
```
