### ISSUE TITLE
":h lambda" can be improved

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8052]
The help at `:h lambda` says this:

> 1. The body of the lambda expression is an |expr1| and not a sequence of |Ex|
>    commands.

That's no longer true since [8.2.2635](https://github.com/vim/vim/releases/tag/v8.2.2635).

---

A little further, the help says this:

> The arguments are optional.  Example: >
>         :let F = {-> 'error function'}
>         :echo F()
> <       error function

That's true when the body is an expression:
```vim
vim9script
timer_start(0, () => execute('eval 0'))
```
    no error

But that's not true when the body is a sequence of Ex commands:
```vim
vim9script
timer_start(0, () => {
    eval 0
})
```
    E118: Too many arguments for function: <lambda>1

Here, the error is due to us having omitted to declare the argument for the timer id which is automatically passed to the lambda:
```vim
vim9script
timer_start(0, (_) => {
    eval 0
})
```
    no error

This is confirmed by the definition of the lambda as given by `:def <lambda>1`, when its body is an expression:

        def <lambda>1(...): string
     1  return execute('eval 0')
        enddef

Versus when its body is a sequence of Ex commands:

        def <lambda>1()
     1      eval 0
        enddef

In the first case, notice `...` which stands for variable arguments.  BTW, I wonder whether `...` should be replaced with `...l: list<any>`; although, I'm not sure it's possible to use the name `l`, because it could shadow a variable in the closure...

Also, the current example does not seem to correctly illustrate that arguments are optional; `F` is defined without any argument, and invoked without any argument either, so it's obvious that no error is raised.  I think the example needs the lambda to be invoked *with* an argument, to show that it doesn't raise any error:

    :let F = {-> 'no error'}
    :echo F('optional argument')
    no error

---

Finally, at `:h closure`, the help says this:

> The lambda expression is also useful for Channel, Job and timer: >
>         :let timer = timer_start(500,
>                         \ {-> execute("echo 'Handler called'", "")},
>                         \ {'repeat': 3})
> <       Handler called
>         Handler called
>         Handler called

> Note how execute() is used to execute an Ex command.  That's ugly though.

It's true that the example is ugly; in part because of the Ex command which needs to be nested inside a string, which in turn can be tricky if it contains a mix of single and double quotes, and result in a hard-to-read string with tokens like `\"` (for an escaped double quote inside a double-quoted string) or `''` (for a literal single quote embedded inside a single-quoted string).

But that's no longer an issue in Vim9 thanks to the previously mentioned syntax; the example can be re-written like this:

    var timer = timer_start(500, (_) => {
        echom 'Handler called'
    }, {repeat: 3})

I used `:echom` instead of `:echo` because it lets us run `:mess` to check that the callback was indeed invoked 3 times.  The same check is not possible with `:echo` (because a new message simply overwrites the previous one on the command-line).

---

As a suggestion, here is a patch to improve the help:

```diff
diff --git a/runtime/doc/eval.txt b/runtime/doc/eval.txt
index 57ab47e0c..fe247fa08 100644
--- a/runtime/doc/eval.txt
+++ b/runtime/doc/eval.txt
@@ -1542,16 +1542,19 @@ evaluating |expr1|.  Lambda expressions differ from |user-functions| in
 the following ways:
 
 1. The body of the lambda expression is an |expr1| and not a sequence of |Ex|
-   commands.
+   commands.  NOTE: In Vim9 script, this limitation does not exist.
+   See |vim9-inline-function|.
 2. The prefix "a:" should not be used for arguments.  E.g.: >
 	:let F = {arg1, arg2 -> arg1 - arg2}
 	:echo F(5, 2)
 <	3
 
 The arguments are optional.  Example: >
-	:let F = {-> 'error function'}
-	:echo F()
-<	error function
+	:let F = {-> 'no error'}
+	:echo F('optional argument')
+<	no error
+NOTE: In Vim9 script, if the body is a sequence of |Ex| commands, the arguments
+are mandatory.
 							*closure*
 Lambda expressions can access outer scope variables and arguments.  This is
 often called a closure.  Example where "i" and "a:arg" are used in a lambda
@@ -1579,13 +1582,17 @@ Examples for using a lambda expression with |sort()|, |map()| and |filter()|: >
 
 The lambda expression is also useful for Channel, Job and timer: >
 	:let timer = timer_start(500,
-			\ {-> execute("echo 'Handler called'", "")},
+			\ {-> execute("echom 'Handler called'", "")},
 			\ {'repeat': 3})
 <	Handler called
 	Handler called
 	Handler called
 
 Note how execute() is used to execute an Ex command.  That's ugly though.
+In Vim9 script, an inline function can be used instead: >
+	:vim9 var timer = timer_start(500, (_) => {
+		echom 'Handler called'
+	}, {repeat: 3})
 
 
 Lambda expressions have internal names like '<lambda>42'.  If you get an error
diff --git a/runtime/doc/vim9.txt b/runtime/doc/vim9.txt
index 974ee6af6..c89950fd3 100644
--- a/runtime/doc/vim9.txt
+++ b/runtime/doc/vim9.txt
@@ -426,6 +426,8 @@ But you can use a backslash to concatenate the lines before parsing: >
 		\	v)
 		\	=> v > 0)
 
+						*vim9-inline-function*
+
 Additionally, a lambda can contain statements in {}: >
 	var Lambda = (arg) => {
 		g:was_called = 'yes'
```

**Comment by brammool** [comment]
> The help at `:h lambda` says this:
> 
> > 1. The body of the lambda expression is an |expr1| and not a sequence of |Ex|
> >    commands.
> 
> That's no longer true since [8.2.2635](https://github.com/vim/vim/releases/tag/v8.2.2635).

I think that, at least for now, it should point to the Vim9 style lambda
in the Vim9 help file.

> A little further, the help says this:
> 
> > The arguments are optional.  Example: >
> >         :let F = {-> 'error function'}
> >         :echo F()
> > <       error function
> 
> That's true when the body is an expression:
> ```vim
> vim9script
> timer_start(0, () => execute('eval 0'))
> ```
>     no error
> 
> But that's not true when the body is a sequence of Ex commands:
> ```vim
> vim9script
> timer_start(0, () => {
>     eval 0
> })
> ```
>     E118: Too many arguments for function: <lambda>1
> 
> Here, the error is due to us having omitted to declare the argument for the timer id which is automatically passed to the lambda:
> ```vim
> vim9script
> timer_start(0, (_) => {
>     eval 0
> })
> ```
>     no error
> 
> This is confirmed by the definition of the lambda as given by `:def <lambda>1`, when its body is an expression:
> 
>         def <lambda>1(...): string
>      1  return execute('eval 0')
>         enddef
> 
> Versus when its body is a sequence of Ex commands:
> 
>         def <lambda>1()
>      1      eval 0
>         enddef
> 
> In the first case, notice `...` which stands for variable arguments.

In the past the lambda arguments were flexible, which could make it hard
to find mistakes.  I think it's better to be more strict in Vim9.
It's a compromise though.

> BTW, I wonder whether `...` should be replaced with `...l: list<any>`;
> although, I'm not sure it's possible to use the name `l`, because it
> could shadow a variable in the closure...

Also, the variable isn't actually available, "..." indicates that what
follows is ignored, not that it can be used.

> Also, the current example does not seem to correctly illustrate that
> arguments are optional; `F` is defined without any argument, and
> invoked without any argument either, so it's obvious that no error is
> raised.  I think the example needs the lambda to be invoked *with* an
> argument, to show that it doesn't raise any error:
> 
>     :let F = {-> 'no error'}
>     :echo F('optional argument')
>     no error

I'll change that.
 
> Finally, at `:h closure`, the help says this:
> 
> > The lambda expression is also useful for Channel, Job and timer: >
> >         :let timer = timer_start(500,
> >                         \ {-> execute("echo 'Handler called'", "")},
> >                         \ {'repeat': 3})
> > <       Handler called
> >         Handler called
> >         Handler called
> 
> > Note how execute() is used to execute an Ex command.  That's ugly though.
> 
> It's true that the example is ugly; in part because of the Ex command
> which needs to be nested inside a string, which in turn can be tricky
> if it contains a mix of single and double quotes, and result in a
> hard-to-read string with tokens like `\"` (for an escaped double quote
> inside a double-quoted string) or `''` (for a literal single quote
> embedded inside a single-quoted string).
> 
> But that's no longer an issue in Vim9 thanks to the previously mentioned syntax; the example can be re-written like this:
> 
>     var timer = timer_start(500, (_) => {
>         echom 'Handler called'
>     }, {repeat: 3})
> 
> I used `:echom` instead of `:echo` because it lets us run `:mess` to
> check that the callback was indeed invoked 3 times.  The same check is
> not possible with `:echo` (because a new message simply overwrites the
> previous one on the command-line).

It's a bit more useful like this:

	var count = 0
	var timer = timer_start(500, (_) => {
	       count += 1
	       echom 'Handler called ' .. count
	   }, {repeat: 3})


-- 
Light travels faster than sound.  This is why some people
appear bright until you hear them speak

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
Fixed by https://github.com/vim/vim/commit/130cbfc31235c6cb52ffe718ea0a5bb50fbbc9fd.
