### ISSUE TITLE
Adding TODO, XXX, FIXME to Haskell syntax file

### ISSUE THREAD

**Issue by Aster89** [vim/vim#8054]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
I find special coloring for the words `TODO`, `XXX`, and `FIXME` (when in comments) very useful. The Haskell syntax file doesn't define any of these, nor the others (listed below) I've `grep`ped in other syntax files.

**Describe the solution you'd like**
Haskell syntax file integrated with something that allows special coloring of the three words above.

```
BUG
CHECK
COMBAK
DEBUG
DEPRECATED
FINISH
FIX
FIXME
HACK
LOUT
MARK
NB
NOT
NOTE
NOTES
OPTIMIZE
README
REFACTOR
REVIEW
SYS_BOOTWIN_INSTALL
SYS_RESTART
SYS_SHUTDOWN
SYS_TODOS
TBD
TEMP
TEST
TODO
XXX
XXX[XXXXX]
ZZZ
```

**Comment by brammool** [comment]
Just a few words would be OK to include in the syntax file itself.  And #8054 proposes that.
If you want more that's a personal preference.  You can do this in the ~/.vim/after/syntax/haskell.vim file, e.g.
```vim
syn keyword hsTodo	        contained FINISH REVIEW TEMP
```
