### ISSUE TITLE
 :lfile, :cfile and -q don't seem to work

### ISSUE THREAD

**Issue by lkintact** [vim/vim#8056]
**Describe the bug**
 `:lfile`, `:cfile` and `-q` don't seem to work: gVim doesn't jump to the first error.

**To Reproduce**
1. Run `gvim --clean test.txt` (the file: [test.txt](https://github.com/vim/vim/files/6251569/test.txt)).
2. Execute `:lvimgrep /error/ %`.
3. Execute `:lwindow`. A location window opens.
4. Save the location list to a file with `:write locations.txt`, exit gVim with `:qall`.
5. Run `gvim --clean -q locations.txt`.
6. Execute `:lfile locations.txt`.
7. Execute `:cfile locations.txt`.

gVim doesn't jump to the first error (`test.txt`, line 2, column 6) in the location list at steps 5-7.

**Expected behavior**
gVim should open `test.txt` and position the cursor at line 2, column 6 at any of the steps 5-7.

**Environment**
 - Vim version 8.2.2681
 - OS: Windows 10 Home 1803
 - Terminal: GUI.

**Comment by lacygoill** [comment]
You need to set a proper errorformat for Vim to parse the contents of the file into a list of valid quickfix entries.  A simple one which should work in your example is:

    %f\|%l col %c\|%m
    ├┘  ├┘     ├┘  ├┘
    │   │      │   └ message
    │   │      └ column number
    │   └ line number of quickfix entry
    └ whatever is matched by this item will be used to set the filename of a quickfix entry

You can test it with this shell command:

    gvim --clean --cmd "let &efm = '%f\|%l col %c\|%m'" -q locations.txt

If this is something you want definitely, add this in `~/.vim/after/ftplugin/qf.vim`:

    let &l:errorformat = '%f\|%l col %c\|%m'

If you think there might be some whitespace that you need to take into account, use these items:

    %\s%#

This is equivalent to `\s*` in a regular regex.

For more info, see [`:h error-file-format`](https://vimhelp.org/quickfix.txt.html#error-file-format).

**Comment by lacygoill** [comment]
> If this is something you want definitely, add this in ~/.vim/after/ftplugin/qf.vim:

Although, that's only useful if you temporarily make a quickfix buffer modifiable, edit it, then run something like `:cbuffer`.

If you want this to work anywhere, I guess you would need to add this in your vimrc:

    let &errorformat ..= ',%f\|%l col %c\|%m'

**Comment by lacygoill** [comment]
Since `%f|%l| %m` is already included in the default errorformat, it might make sense to also include `%f|%l col %c| %m`:
```diff
diff --git a/src/option.h b/src/option.h
index 0b1183fec..0b95587ab 100644
--- a/src/option.h
+++ b/src/option.h
@@ -91,7 +91,7 @@ typedef enum {
 #    ifdef EBCDIC
 #define DFLT_EFM	"%*[^ ] %*[^ ] %f:%l%*[ ]%m,%*[^\"]\"%f\"%*\\D%l: %m,\"%f\"%*\\D%l: %m,%f:%l:%c:%m,%f(%l):%m,%f:%l:%m,\"%f\"\\, line %l%*\\D%c%*[^ ] %m,%D%*\\a[%*\\d]: Entering directory %*[`']%f',%X%*\\a[%*\\d]: Leaving directory %*[`']%f',%DMaking %*\\a in %f,%f|%l| %m"
 #     else
-#define DFLT_EFM	"%*[^\"]\"%f\"%*\\D%l: %m,\"%f\"%*\\D%l: %m,%-G%f:%l: (Each undeclared identifier is reported only once,%-G%f:%l: for each function it appears in.),%-GIn file included from %f:%l:%c:,%-GIn file included from %f:%l:%c\\,,%-GIn file included from %f:%l:%c,%-GIn file included from %f:%l,%-G%*[ ]from %f:%l:%c,%-G%*[ ]from %f:%l:,%-G%*[ ]from %f:%l\\,,%-G%*[ ]from %f:%l,%f:%l:%c:%m,%f(%l):%m,%f:%l:%m,\"%f\"\\, line %l%*\\D%c%*[^ ] %m,%D%*\\a[%*\\d]: Entering directory %*[`']%f',%X%*\\a[%*\\d]: Leaving directory %*[`']%f',%D%*\\a: Entering directory %*[`']%f',%X%*\\a: Leaving directory %*[`']%f',%DMaking %*\\a in %f,%f|%l| %m"
+#define DFLT_EFM	"%*[^\"]\"%f\"%*\\D%l: %m,\"%f\"%*\\D%l: %m,%-G%f:%l: (Each undeclared identifier is reported only once,%-G%f:%l: for each function it appears in.),%-GIn file included from %f:%l:%c:,%-GIn file included from %f:%l:%c\\,,%-GIn file included from %f:%l:%c,%-GIn file included from %f:%l,%-G%*[ ]from %f:%l:%c,%-G%*[ ]from %f:%l:,%-G%*[ ]from %f:%l\\,,%-G%*[ ]from %f:%l,%f:%l:%c:%m,%f(%l):%m,%f:%l:%m,\"%f\"\\, line %l%*\\D%c%*[^ ] %m,%D%*\\a[%*\\d]: Entering directory %*[`']%f',%X%*\\a[%*\\d]: Leaving directory %*[`']%f',%D%*\\a: Entering directory %*[`']%f',%X%*\\a: Leaving directory %*[`']%f',%DMaking %*\\a in %f,%f|%l| %m,%f|%l col %c| %m"
 #    endif
 #   endif
 #  endif
```

**Comment by lkintact** [comment]
Thank you, @lacygoill, honestly, I had no idea the `'errorformat'` option existed.

I think this paragraph confused me (doc/quickfix.txt, lines 677-682):
```
Note: Making changes in the quickfix window has no effect on the list of
errors.  'modifiable' is off to avoid making changes.  If you delete or insert
lines anyway, the relation between the text and the error number is messed up.
If you really want to do this, you could write the contents of the quickfix
window to a file and use ":cfile" to have it parsed and used as the new error
list.
```
Since it doesn't mention `'errorformat'` (and nor do the descriptions at `:help :lfile`, `:help :cfile` or `:help -q`) I thought just writing the location list to a file would be enough.

**Comment by lacygoill** [comment]
Yes, I think it should work.  It would if `%f|%l col %c| %m` was included into the default value of `'errorformat'`.

As for the help, you don't have to write the buffer in a file.  You can populate a new quickfix list directly from the edited quickfix buffer with `:cbuffer` or `:cgetbuffer`.

Here is a simple snippet to illustrate:
```vim
silent helpgrep pattern
copen
set modifiable
silent normal! 124GdG
let &errorformat ..= ',%f|%l col %c| %m'
cgetbuffer
chistory
```
      error list 1 of 2; 1526 errors  :silent helpgrep pattern
    > error list 2 of 2; 123 errors   :cgetbuffer

Notice that a new quickfix list has been pushed on the stack, after we've edited the quickfix buffer to remove all the lines whose address is above 123.  At no point did we write an extra file.

So, maybe the help could be re-written like this:
```diff
diff --git a/runtime/doc/quickfix.txt b/runtime/doc/quickfix.txt
index 2f34f49bf..1f309aa12 100644
--- a/runtime/doc/quickfix.txt
+++ b/runtime/doc/quickfix.txt
@@ -677,9 +677,8 @@ triggered.
 Note: Making changes in the quickfix window has no effect on the list of
 errors.  'modifiable' is off to avoid making changes.  If you delete or insert
 lines anyway, the relation between the text and the error number is messed up.
-If you really want to do this, you could write the contents of the quickfix
-window to a file and use ":cfile" to have it parsed and used as the new error
-list.
+If you really want to do this, you need to execute ":cbuffer" to have the
+modified buffer parsed and used as the new error list.
 
 						*location-list-window*
 The location list window displays the entries in a location list.  When you
```

**Comment by brammool** [comment]
Doesn't look like an issue with Vim.
