### ISSUE TITLE
Wrong value in seq_cur when playing with the undo tree?

### ISSUE THREAD

**Issue by fflorent** [vim/vim#806]
## Steps to reproduce
1. open a new buffer in vim
2.  Type the following keys: `itest<cr><esc>`
3. Enter this command: `:echo undotree()['seq_cur']` (should display 1)
4. Type this (to repeat the last insertion): `.`
5. Now your file should contain:
   
   ``` text
   test
   test
   
   ```
6. Enter this command: `:echo undotree()['seq_cur']` (should display 2)
7. Undo (type `u`)
8. Type `.`
9. Enter this command: `:echo undotree()['seq_cur']` (should display 3)
10. Type this command: `:undo 1`
11. Enter this command: `:echo undotree()['seq_cur']` 
## Expected result

I would expect the last command to display 1
## Actual result

It displays 2.

**Comment by fflorent** [comment]
FWIW, same issue with `changenr()`

Florent

**Comment by lacygoill** [comment]
I think the issue was fixed by https://github.com/vim/vim/commit/80eaddd3a0bc47cb14168964678420cfe03a2502.

**Comment by k-takata** [comment]
Closing then.
