### ISSUE TITLE
filetype.vim: /usr/share/doc/bash-completion/AUTHORS incorrectly detected as a shell script

### ISSUE THREAD

**Issue by cwfoo** [vim/vim#8065]
**Describe the bug**

In Ubuntu, Vim sets the filetype to `sh` when opening `/usr/share/doc/bash-completion/AUTHORS`.

Vim sets the filetype to `sh` for any text file within a directory named `bash-completion`.

**To Reproduce**
In Ubuntu:
1. Run `vim --clean /usr/share/doc/bash-completion/AUTHORS`
2. Observation: `set ft?` is `sh`.

**Expected behavior**
A text file should not be highlighted a shell script.

**Environment**
 - Vim version: 8.1.2269
 - OS: Ubuntu 20.04
 - Terminal: GNOME Terminal

**Comment by lacygoill** [comment]
This is caused by this line in `$VIMRUNTIME/filetype.vim`:

https://github.com/vim/vim/blob/f2dd9cb9958962302d33fab8fe6439645a2d1e1b/runtime/filetype.vim#L1560

More specifically, from this file pattern:

    */{,.}bash[_-]completion{,.d,.sh}{,/*}

**Comment by brammool** [comment]
The patterns ending in a star belong further down.  That doesn't solve the problem though, because AUTHORS does not have a filetype.  Let's match /doc/bash-completion/* as text files.
