### ISSUE TITLE
sh syntax: redirection operators after heredoc are incorrectly highlighted as string

### ISSUE THREAD

**Issue by cwfoo** [vim/vim#8066]
**Describe the bug**

In `sh` files, redirection operators after a heredoc operator will be incorrectly highlighted as a string.

**To Reproduce**
1. Run `vim --clean myscript.sh`
2. Insert:
    ```
    #!/bin/sh

    cat << 'EOF' > myfile.txt
    Hello!
    EOF
    ```
3. Observation: `> myfile.txt` is highlighted like a string:
    ![Shell script](https://user-images.githubusercontent.com/11555232/113534156-76abbe80-9602-11eb-8b4b-733ae3d505cc.png)

    On all 13 columns of <code>&nbsp;> myscript.txt</code>, running `:echon map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')` prints `['shHereDoc']`.

**Expected behavior**
`> myfile.txt` is not part of the heredoc string, so it should not be highlighted like a string.

**Environment**
 - Vim version: 8.1.2269
 - OS: Ubuntu 20.04
 - Terminal: GNOME Terminal

**Side notes**

The highlighting is correct when the output redirection comes before the heredoc operator:

![Shell script](https://user-images.githubusercontent.com/11555232/113534388-313bc100-9603-11eb-8ea0-8595e341fd1f.png)

---

@cecamp (maintainer)

**Comment by cecamp** [comment]
Unfortunately this is a problem that cannot (currently) be solved. The "cat <<EOF" triggers one of the heredoc syntax recognition patterns as a region, and subsequent text is recognized as heredoc until the EOF.

Additionally, I like folding to be enabled for the entire heredoc block of text, and so would like that entire block (including the whole of cat <<EOF >myfile.txt) to be folded as a heredoc block. So I don't want to recognize the start of a heredoc, nextgroup to end-of-line (using sh syntax), and then begin the heredoc region.

If I could have a "this string starts off the region" magic pattern, something akin to "^" starts off a line, then I could highlight the rest of the line as sh and subsequent text as heredoc. Unfortunately no such magic pattern exists in vim. 

So, so far, its something that we'll have to live with.
