### ISSUE TITLE
One more correction to the docs

### ISSUE THREAD

**Issue by lkintact** [vim/vim#8070]
As `:helpgrep` and `:lhelpgrep` see `|` as their argument, they should probably be added to the list at `:help :bar`.

Vim version 8.2.2681.

**Comment by brammool** [comment]
I'll do that.

**Comment by cecamp** [comment]
Hello, Bram -- as a suggestion, perhaps you could come up with a script that would check for some of these document issues; something like grep "[mM][sS] [wW]indows" *.txt in the present case. I know you get a number of these sorts of things and it might be good to semi-automate detecting them. Just collect 'em as you get 'em...

**Comment by brammool** [comment]
> Hello, Bram -- as a suggestion, perhaps you could come up with a
> script that would check for some of these document issues; something
> like grep "[mM][sS] [wW]indows" *.txt in the present case. I know you
> get a number of these sorts of things and it might be good to
> semi-automate detecting them. Just collect 'em as you get 'em...

I do have a script to check the runtime files, which I run after
including changes and before sending out runtime file updates.
I keep improving it.  Can't catch everything though.

-- 
hundred-and-one symptoms of being an internet addict:
77. The phone company asks you to test drive their new PBX system

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
