### ISSUE TITLE
Vim9: confusing error when assigning to script-local variable in ":def" function in legacy script without "s:" prefix

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8076]
**Describe the bug**

In Vim9 script, assigning to a script-local variable in a `:def` function in a legacy script might give a confusing error if the `s:` prefix is omitted.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        let s:name = ''
        def Func()
            name = 'assigned'
        enddef
        call Func()
    EOF
    )

`E1054` is raised:

    E1054: Variable already declared in the script: name = 'assigned'

**Expected behavior**

`E476` is raised:

    E476: Invalid command: name = 'assigned'

Because the issue is not that we are trying to declare the variable a second time.  A declaration requires the keyword `:var`; but there is no `:var` here.

**Environment**

 - Vim version: 8.2 Included patches: 1-2725
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(366)

**Additional context**

Since [8.2.1510](https://github.com/vim/vim/releases/tag/v8.2.1510), in a legacy script, it is required for the name of a script-local variable to be prefixed with `s:`, even in a `:def` function.  That's not the case here:

    name = 'assigned'
    ^
    no "s:" prefix

So, `name` should not be parsed as the name of a variable.

---

The concept of declaration only makes sense in the Vim9 context.  It doesn't make sense for a legacy script-local variable:
```vim
def Func()
    s:name = 123
    s:name = "I was a number, now I'm a string"
    echo s:name
enddef
call Func()
```
    I was a number, now I'm a string

Notice that no error was raised even though the type of `s:name` has changed.  There is no type checking, which means there was no declaration either.  This contradicts the first error message:

    E1054: Variable already declared in the script: name = 'assigned'
           ^-----------------------^

**Comment by brammool** [comment]
I am reconsidering whether we should require the s: prefix to find a script-local variable only in legacy script.  This rule probably isn't easy to understand.  We also don't require a prefix for finding a function.  We do need the s: prefix if the variable does not exist at the time the function is compiled.  I think that is OK.

**Comment by lacygoill** [comment]
This works when `legacy` is assigned to:
```vim
let s:legacy = 'one'
def Func()
    legacy = 'two'
enddef
call Func()
```
But not when `legacy` is referred to:
```vim
let s:legacy = 'one'
def Func()
    echo legacy
enddef
call Func()
```
    E1001: Variable not found: legacy

In that case, we still need `s:`:
```vim
let s:legacy = 'one'
def Func()
    echo s:legacy
enddef
call Func()
```
    one

This seems inconsistent.  And confusing when we do both in the same function:
```vim
let s:legacy = 'one'
def Func()
    legacy = 'two'
    echo legacy
enddef
call Func()
```
    E1001: Variable not found: legacy

**Comment by lacygoill** [comment]
When referring to a script-local variable in a `:def` function in a legacy script, we can omit the `s:` prefix if it was assigned at the script level:
```vim
let s:legacy = 'no error'
def Func()
    echo legacy
enddef
call Func()
```
    no error

But not if it was assigned in the `:def` function itself:
```vim
def Func()
    s:legacy = 'no error'
    echo legacy
enddef
call Func()
```
    E1001: Variable not found: legacy

In that case, we still need the `s:` prefix:
```vim
def Func()
    s:legacy = 'no error'
    echo s:legacy
enddef
call Func()
```
    no error

After failing to find `legacy` in the function scope, shouldn't Vim also look in the script-local namespace?  It would be more consistent with the first snippet.

**Comment by lacygoill** [comment]
Ah no.  I understand what happens.  Sorry for the noise.

**Comment by lacygoill** [comment]
The rule is that we can drop `s:` only for variables that Vim can see in the script-local namespace at compile time.  If the variable was not declared in the script earlier, Vim can't know about its existence.  The fact that it's created/assigned in the function itself doesn't matter.  The variable won't exist until runtime.
