### ISSUE TITLE
macOS: make test: glibtool not found

### ISSUE THREAD

**Issue by ma11hew28** [vim/vim#8084]
`src/INSTALLmac.txt` says to run `make test`, but when I did, I got the error `glibtool: command not found`.

**Steps to Reproduce**

```sh
curl -LJO https://github.com/vim/vim/archive/refs/tags/v8.2.2730.tar.gz
gunzip vim-8.2.2730.tar.gz
tar -x -f vim-8.2.2730.tar
cd vim-8.2.2730/src
make
make test
```

**Environment**

- macOS 11.2 (20D64)
- Xcode 12.4 (12D4e)

**Comment by poetaman** [comment]
You probably need to install this: https://formulae.brew.sh/formula/libtool, src: https://stackoverflow.com/questions/54078839/mac-osx-where-can-i-download-glibtool

**Comment by ma11hew28** [comment]
@reportaman, OK, thank you. If that's the case, then maybe your suggestion should be added to `src/INSTALLmac.txt`.

**Comment by chrisbra** [comment]
@ma11hew28 can you prepare a PR with a doc update then please?

**Comment by brammool** [comment]
No need, I'll add a remark to src/INSTALLmac.txt

**Comment by ma11hew28** [comment]
Sure, @chrisbra. Done.

Sorry, @brammool, I didn't see your reply until I had already finished updating `src/INSTALLmac.txt`, so I figured I'd just make a pull request anyway. Feel free to use all of it, part of it, or none of it at all.

In addition to fixing this issue, I also updated some things, removed some things, and tried to make the document simpler.

I removed the part about:

- how to install Command Line Tools. I think the command to do that is `xcode-select --install`, but I decided to leave it out, because people could google how to install Command Line Tools.
- '/' being the only supported path separator because I think that's the only path separator that macOS supports.
- the `--with-mac-arch` option because I thought it'd be rather unusual to need to "overrule the architecture" and people who have unusual needs could just run `./configure --help`, but I just realized that `--with-mac-arch` was probably mentioned because it's a Mac-specific option, so maybe I should add it back.
- compiling with GUI, since it seemed outdated—XQuartz seems to be used now—and now there's MacVim, which seems to be the recommended way to go now, so I just added a section for MacVim.

I also modified the flow and content of the document to more closely match these [instructions on downloading Vim for Mac][1].

Anyway, feel free to let me know what you think. I'm open to feedback, questions, and suggestions.


  [1]: https://www.vim.org/download.php#mac

**Comment by brammool** [comment]
Matthew Mario Di Pasquale wrote:

> Sure, @chrisbra. Done.
> 
> Sorry, @brammool, I didn't see your reply until I had already finished
> updating `src/INSTALLmac.txt`, so I figured I'd just make a pull
> request anyway. Feel free to use all of it, part of it, or none of it
> at all.
> 
> In addition to fixing this issue, I also updated some things, removed
> some things, and tried to make the document simpler.
> 
> I removed the part about:
> 
> - how to install Command Line Tools. I think the command to do that is
> `xcode-select --install`, but I decided to leave it out, because
> people could google how to install Command Line Tools.

No, the hint to use "make --version" is very good, it pops up a dialog
that makes this a one-button-click.  I assume it will also automatically
pick the right Xcode version for the system.

> - '/' being the only supported path separator because I think that's
> the only path separator that macOS supports.

Let's move this to the remark about MacOS Classic, I think they go
together.

> - the `--with-mac-arch` option because I thought it'd be rather
> unusual to need to "overrule the architecture" and people who have
> unusual needs could just run `./configure --help`, but I just realized
> that `--with-mac-arch` was probably mentioned because it's a
> Mac-specific option, so maybe I should add it back.

This must have changed recently with the support for the new processor.
And is "ppc" still supported?
It is an important choice since a generic binary is a lot bigger.

> - compiling with GUI, since it seemed outdated—XQuartz seems to be
> used now—and now there's MacVim, which seems to be the recommended way
> to go now, so I just added a section for MacVim.

This file is about building Vim from source.  If someone wants MacVim
that belongs elsewhere.  We could add a hint "if you don't want to build
from source, go there" with a specific note about where to go.

> I also modified the flow and content of the document to more closely
> match these [instructions on downloading Vim for Mac][1].
> 
> Anyway, feel free to let me know what you think. I'm open to feedback,
> questions, and suggestions.

It would be good to add more info about configure options and be
specific about what to do.  The part about X-Windows probably needs some
updating.

-- 
From "know your smileys":
 :-H	Is missing teeth

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ma11hew28** [comment]
OK, I can add back the hint about how to install Command Line Tools. But I think we should put `xcode-select --install` instead of `make --version` because if you don't have Xcode or Command Line Tools installed, then I think both commands do the same thing, and `xcode-select --install` is documented (in `man xcode-select`) and is fairly self-explanatory.

I see. We could, but then I think including the consideration that "only '/' is supported as path separator" is redundant since the reader could deduce that from the remark that "Classic Mac OS is no longer supported", which implies that only macOS is supported, and if macOS only supports "/" as path separator, which I think is the case, then the reader could deduce that "only '/' is supported as path separator". But if you really think it should be included, then I think the term "file separator" is a bit more clear than "path separator", which might be confused with the ":" used by the `PATH` environment variable.

Good point. I don't know if PPC is still supported. I see the string "ppc" in `src/Makefile` and `src/configure.ac`, so I guess so? (Or maybe you weren't asking but were instead suggesting that `src/INSTALLmac.txt` should answer your question.) For the option `--with-mac-arch`, `src/Makefile` says the "default is to build for the current platform", so I don't think a generic binary is built by default, but still, I'll add a note about this option and the `--disable-darwin` option since they're both Mac-specific. For the option `--with-mac-arch`, `src/Makefile` lists `i386` as a possible value, but `./configure --help` lists `intel`. I guess `i386` and `intel` are the same, but maybe we should change `i386` in `src/Makefile` to `intel` for consistency. The rest of this paragraph is a separate issue, but maybe `--with-mac-arch` should also accept a value for Apple silicon (`apple` maybe?), and then instead of `both` it could accept comma-separated values (each of which could be `apple`, `intel`, or `ppc`), and then maybe it should be renamed to `--with-mac-archs`. For example, you could specify `--with-mac-archs=apple,intel` to [build a universal macOS binary][1]. Or, probably a better idea is to stop supporting PPC (if we haven't already)—because according to the [Wikipedia article "Mac transition to Intel processors"][2], "PowerPC-based Macs are now considered obsolete"—and leave the option name as `--with-mac-arch` and then `both` would mean `apple` and `intel`. Currently, I don't see that `src/Makefile` supports building an Apple silicon binary on an Intel-based Mac, but I think that's possible to do.

OK, I think keeping this file about building Vim from source makes sense. (So I'll also remove the part about Homebrew.) I'm just not sure how to compile Vim with GUI on macOS. When I googled how, most people seemed to suggest just using MacVim instead. I was thinking maybe if I install XQuartz and then compile Vim, that the GUI and X11 libraries would be included automatically, as described by `src/INSTALL`, but I didn't feel like installing XQuartz to test this out. However, it seems like that's the only way to figure it out, unless someone knows about this?


  [1]: https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary
  [2]: https://en.wikipedia.org/wiki/Mac_transition_to_Intel_processors

**Comment by ma11hew28** [comment]
Oh, by the way, the tests passed for me yesterday after I installed `libtool`, which I did by running:

```sh
curl -LJO https://ftpmirror.gnu.org/libtool/libtool-2.4.6.tar.gz
gunzip libtool-2.4.6.tar.gz
tar -x -f libtool-2.4.6.tar
cd libtool-2.4.6
./configure --program-prefix=g
make
sudo make install
```

So thank you, @reportaman.

Also, I just installed XQuartz in order to compile Vim with GUI on my Mac. I got the same compilation errors reported by @chdiza in issue #2444, which I found by googling `error: unknown type name 'Widget' x11`. @nuko8's answer worked. I can add these updated instructions to `src/INSTALLmac.txt`.

**Comment by brammool** [comment]
Matthew Mario Di Pasquale wrote:

> Oh, by the way, the tests passed for me yesterday after I installed
> `libtool`, which I did by running:
> 
> ```sh
> curl -LJO https://ftpmirror.gnu.org/libtool/libtool-2.4.6.tar.gz
> gunzip libtool-2.4.6.tar.gz
> tar -x -f libtool-2.4.6.tar
> cd libtool-2.4.6
> ./configure --program-prefix=g
> make
> sudo make install
> ```
> 
> So thank you, @reportaman.

I assume these instructions can be found somewhere.  Perhaps we can add
a link to that, instead of using the version-specific instructions.
Or perhaps there is a simpler way than building from source?

> Also, I just installed XQuartz in order to compile Vim with GUI on my
> Mac. I got the same compilation errors reported by @chdiza in issue
> #2444, which I found by googling `error: unknown type name 'Widget'
> x11`. @nuko8's answer worked. I can add these updated instructions to
> `src/INSTALLmac.txt`.

That sounds useful.

-- 
From "know your smileys":
 :-)-O	Smiling doctor with stethoscope

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ma11hew28** [comment]
Sure. I just pushed [this commit][1] in which I added instructions on how to install glibtool on macOS.

Great. I added instructions on how to install a GUI version of Vim on macOS in [my second-to-last commit][2].


  [1]: https://github.com/vim/vim/pull/8087/commits/70627ee65a9a85fb251b4837ef6af9acd3b3ed98
  [2]: https://github.com/vim/vim/pull/8087/commits/d7c96d7eea7e99659a59282242c63404b0eb602b
