### ISSUE TITLE
gVim 8.2 : extra line between tabs and where menu bar would be

### ISSUE THREAD

**Issue by mpettis** [vim/vim#8088]
**Describe the bug**
Extra blank and unused line in the gui between the navigation menu (or where it is normally) and the region that shows buffer tabs.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `gvim -u NONE`

**Expected behavior**
I expect there to be no blank line there

**Screenshots**
[screenshot](https://imgur.com/a/msjK57p)

**Environment (please complete the following information):**
 - Vim version
 ```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 15 2019 23:09:16)
MS-Windows 32-bit GUI version with OLE support
Included patches: 1-12
Compiled by appveyor@APPVYR-WIN
Huge version with GUI.  Features included (+) or not (-):
+acl                +eval               +multi_lang         -tag_any_white
+arabic             +ex_extra           +mzscheme/dyn       +tcl/dyn
+autocmd            +extra_search       +netbeans_intg      -termguicolors
+autochdir          -farsi              +num64              +terminal
+autoservername     +file_in_path       +ole                -termresponse
+balloon_eval       +find_in_path       +packages           +textobjects
-balloon_eval_term  +float              +path_extra         +textprop
+browse             +folding            +perl/dyn           -tgetent
++builtin_terms     -footer             +persistent_undo    +timers
+byte_offset        +gettext/dyn        +popupwin           +title
+channel            -hangul_input       -postscript         +toolbar
+cindent            +iconv/dyn          +printer            +user_commands
+clientserver       +insert_expand      +profile            +vartabs
+clipboard          +job                +python/dyn         +vertsplit
+cmdline_compl      +jumplist           +python3/dyn        +virtualedit
+cmdline_hist       +keymap             +quickfix           +visual
+cmdline_info       +lambda             +reltime            +visualextra
+comments           +langmap            +rightleft          +viminfo
+conceal            +libcall            +ruby/dyn           +vreplace
+cryptv             +linebreak          +scrollbind         -vtp
+cscope             +lispindent         +signs              +wildignore
+cursorbind         +listcmds           +smartindent        +wildmenu
+cursorshape        +localmap           +sound              +windows
+dialog_con_gui     +lua/dyn            +spell              +writebackup
+diff               +menu               +startuptime        -xfontset
+digraphs           +mksession          +statusline         -xim
+directx            +modify_fname       -sun_workshop       +xpm_w32
-dnd                +mouse              +syntax             -xterm_save
-ebcdic             +mouseshape         +tag_binary         
+emacs_tags         +multi_byte_ime/dyn -tag_old_static     
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
  system gvimrc file: "$VIM\gvimrc"
    user gvimrc file: "$HOME\_gvimrc"
2nd user gvimrc file: "$HOME\vimfiles\gvimrc"
3rd user gvimrc file: "$VIM\_gvimrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
    system menu file: "$VIMRUNTIME\menu.vim"
Compilation: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  
-DFEAT_CSCOPE -DFEAT_TERMINAL -DFEAT_SOUND -DFEAT_NETBEANS_IN
TG -DFEAT_JOB_CHANNEL   -DFEAT_XPM_W32   -DWINVER=0x0501 
-D_WIN32_WINNT=0x0501 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG 
/arch:IA32 /Zl /MT -DFEAT_OLE -DFEAT_MBYTE_IME -DDYNAMIC_IME 
-DFEAT_GUI_MSWIN -DFEAT_DIRECTX -DDYNAMIC_DIRECTX 
-DFEAT_DIRECTX_COLOR_EMOJI -DDYNAMIC_ICONV -DDYNAMIC_GETTEX
T -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl86t.dll\" 
-DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_LUA -DDYNAMIC_LUA 
-DDYNAMIC_LUA_DLL=\"lua53.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHO
N -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 
-DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python37.dll\" 
-DFEAT_MZSCHEME -I "C:\Program Files (x86)\Racket\include" 
-DMZ_PRECISE_GC -DDYNAMIC_MZSCHEME -DDYNAMIC_MZSCH_DLL=\"li
bracket3m_a36fs8.dll\" -DDYNAMIC_MZGC_DLL=\"libracket3m_a36fs8.dll\" 
-DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS 
-DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl528.dll\" -DFEAT_RUBY 
-DDYNAMIC_RUBY -DDYNAMIC_RUBY_VER=24 -DDYNAMIC_RUBY_DLL=\"
msvcrt-ruby240.dll\" -DFEAT_HUGE /Fd.\ObjGXOULYHTRZi386/ /Zi
Linking: link  /nologo /opt:ref /LTCG:STATUS oldnames.lib kernel32.lib 
advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib netapi32.lib uuid.lib
```
 - OS: Windows 10
 - Terminal: GUI

**Comment by chrisbra** [comment]
that looks like the toolbar is missing. Does it happen without `-u NONE`? What about `gvim --clean`?  Was the installation successful?

**Comment by mpettis** [comment]
Thanks @chrisbra ... using `gvim --clean` gives the same state (per the screenshot), with no menu items.  When I start with the bundles from my old install in `.vim`, I get a menu bar, but also that same blank line.  Here is a screenshot:

[screenshot with my bundles](https://imgur.com/a/8mFid5r)

**Comment by chrisbra** [comment]
there should be an icon bar. How did you install it?

**Comment by chrisbra** [comment]
if you run it from the console, do you get any error message, that vim cannot find some resources?

**Comment by tonymec** [comment]
@mpettis You are using gvim 8.2.12, published 15 December 2019. The latest version is 8.2.2738. Could you please try something more recent?

**Comment by mpettis** [comment]
@chrisbra Running from console is fine, no error messages.  I installed from an .exe installer (see comment below for link).

@tonymec Open to newer version.  I just reinstalled this on new laptop earlier this week.  I used the recommended Windows installer from here (https://www.vim.org/download.php).  I took the recommended link from there (https://github.com/vim/vim-win32-installer/releases/download/v8.2.0012/gvim_8.2.0012_x86_signed.exe ), so if you could point me to where to install a more recent one, I'd be happy to install more recent version.

Thanks both.

**Comment by tonymec** [comment]
Hm, Steve Hall used to compile versions of Vim and gvim for Windows but apparently no more since 8.0. I thought I could find a more recent Vim for Windows somewhere on the web but I haven't succeded.

When I was on Windows I used to compile my own Vim, and I even wrote a couple of HowTo pages, but it's been years since I made the changeover to Linux and I'm not sure they are stil up-to-date. Here are the URLs:
* https://vim.fandom.com/wiki/Getting_the_Vim_source_with_Mercurial
* http://users.skynet.be/antoine.mechelynck/vim/compile.htm

Best regards,
Tony.

**Comment by mpettis** [comment]
Thank you @tonymec !  I'll give these a shot when I have some open time.  This issue isn't stopping my work -- it's just one line of wasted space that is just gnawing at me.  Truth be told, the console version is working fine (using either cmd.exe or cygwin bash terminal), and those I can upgrade to use *nix varieties if need be.  It's just nice to have a version of Vim that works seamlessly with Windows.  And I like the solarized color scheme I get with the gui version...

**Comment by vim-ml** [comment]
On Fr, 09 Apr 2021, Tony Mechelynck wrote:

> Hm, Steve Hall used to compile versions of Vim and gvim for Windows but apparently no more since 8.0. I thought I could find a more recent Vim for Windows somewhere on the web but I haven't succeded.
> 
> When I was on Windows I used to compile my own Vim, and I even wrote a couple of HowTo pages, but it's been years since I made the changeover to Linux and I'm not sure they are stil up-to-date. Here are the URLs:
> * https://vim.fandom.com/wiki/Getting_the_Vim_source_with_Mercurial
> * http://users.skynet.be/antoine.mechelynck/vim/compile.htm

You can always use https://github.com/vim/vim-win32-installer

Best,
Christian
-- 
Ein wirklich weiser Mann spielt nie mit einem Einhorn Bockspringen!

**Comment by mpettis** [comment]
@vim-ml Thank you Christian.  I downloaded the x64 version (gvim_8.2.2753_x64.zip) and installed it.  I ran `gvim.exe --clean`, and appear to have the same blank line.

[gvim --clean, gvim_8.2.2753_x64 ](https://imgur.com/a/kVIqo6T)

**Comment by chrisbra** [comment]
I have no idea, what could be causing this. If you don't need the toolbar or the menubar, you can simply use `:set guioptions=M`. This needs to be done early during startup, otherwise Vim will source the menu vim script files.

**Comment by mpettis** [comment]
@chrisbra Thank you, this does work:

`gvim.exe --cmd "set guioptions=M"`

It removes that line and the menu bar, which I can live with, as I don't use it.  In fact, taking it away adds another precious line to the buffer area, so that is a plus.  I can set the start menu call to this to take this argument with a little work I'm sure.  So I consider my problem solved.  I don't know what to say about what is going on with the default behavior or, if you are interested in it, how to recreate it.  If there is anything I can provide that will help you or someone recreate this, if it is of interest, I'd be happy to help.

Here is a screenshot of how I changed the start menu configuration to take these options, should someone else use this issue as a guide.

[Alter Start Menu Entry to take command line options](https://imgur.com/a/5cpUEiI)

Thanks again,
Matt

**Comment by brammool** [comment]
Glad you found a solution.  I'm not aware of any other users running into this problem, so let's close this.
If others also have a missing toolbar either reopen or create a new issue.
