### ISSUE TITLE
Vim9: type checking ignores error in return type of lambda expression passed to "map()" at compile time

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8092]
**Describe the bug**

In Vim9 script, at compile time, type checking might ignore an error in the return type of a lambda expression passed to `map()`.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            getbufinfo()->map((_, v): dict<float> => v)
        enddef
        defcompile
    EOF
    )

No error is raised.

**Expected behavior**

`E1012` is raised:

    E1012: Type mismatch; expected dict<float> but got dict<any>

Because, at compile time, Vim knows that the return type of `getbufinfo()` is a list of dictionaries of mixed values.  This is confirmed by this command:

    :echo getbufinfo()->typename()
    list<dict<any>>

And this is also confirmed by the return type as specified in the source code:

https://github.com/vim/vim/blob/2a38908b05c1d3973a8edbeb5b3e05a11332faf0/src/evalfunc.c#L994-L995

    {"getbufinfo",	0, 1, FEARG_1,	    NULL,
                        ret_list_dict_any,  f_getbufinfo},
                        ^---------------^

Besides, Vim knows that `map()` can't change the type of the items in a list (only `mapnew()` can do that).  Therefore, it knows that – whatever expression we use to replace the items – the new items will always have the same type; i.e. they will still be dictionaries of mixed values.  But that's not what we've specified in the return type of the lambda:

    getbufinfo()->map((_, v): dict<float> => v)
                              ^---------^

We've told Vim that we expected dictionaries of floats.  That can't possibly match whatever `getbufinfo()` will pass to `map()`, and Vim should tell us about that error as soon as possible; i.e. at compile time.

**Environment**

 - Vim version: 8.2 Included patches: 1-2740
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: X.Org 7.7.0(366)

**Additional context**

The error is finally raised at runtime:
```vim
vim9script
def Func()
    getbufinfo()->map((_, v): dict<float> => v)
enddef
Func()
```
    E1012: Type mismatch; expected dict<float> but got dict<any>

**Comment by lacygoill** [comment]
The issue persists when we also type check the argument of the lambda:
```vim
vim9script
def Func()
    getbufinfo()->map((_, v: dict<float>): dict<float> => v)
enddef
defcompile
```
    no error

**Comment by lacygoill** [comment]
Ah it might be related to an existing todo item:

> - Check many more builtin function arguments at compile time.

Or maybe:

> - Compile builtin functions that access local variables:
>     islocked()

**Comment by lacygoill** [comment]
Actually, the fact that Vim doesn't raise any error at compile time for the return type might be expected.  For the same reason that this snippet doesn't raise any error either:
```vim
vim9script
def Func()
    var d: dict<any>
    d = {a: 1.23}
enddef
Func()
```
    no error

We've told Vim that `d` was a dictionary of mixed values, while we assign it a dictionary of floats; and yet no error is given.  That's because `float` is a special case of the `any` type.

And maybe the same reasoning applies to a wrong type which we specify in a lambda's arguments:
```vim
vim9script
def Func()
    getbufinfo()->map((_, v: dict<float>) => v)
enddef
defcompile
```
Forget about `getbufinfo()`; consider the hypothetical builtin function `foo()` whose return type is `list<any>`:
```vim
vim9script
def Func()
    foo()->map((_, v: job) => v)
enddef
defcompile
```
Should Vim raise an error here?  What if `foo()` *sometimes* returns a list of jobs.  That would be entirely possible; i.e. there would be no mismatch with `list<any>`, because `list<job>` is a special case of `list<any>`.

---

That's not to say there is no issue right now; there is one:
```vim
vim9script
def Func()
    getbufline(1, 1)->map((_, v: float): float => v)
enddef
defcompile
```
    no error

The return type of `getbufline()` is a list of strings.  This time, `float` cannot be a special case of `any`; it's just wrong.

**Comment by brammool** [comment]
Patch 8.2.3897 adds more type checking for map() and filter().
The first example does not raise an error though, since dict<any> is expected, and dict<float> does not conflict with that.

The example with getbufline() now does generate an error.
I think the basic problem has been taken care of.  If you find an example where a type error is missing, please create a new issue.
