### ISSUE TITLE
Vim9: cannot ignore argument inside inner lambda when other argument ignored in outer lambda

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8096]
**Describe the bug**

In Vim9 script, we cannot ignore an argument inside an inner lambda, if we're already ignoring an argument in the outer one.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        echo range(3)->mapnew((_, v) => [v]->map((_, w) => w + 1))
    EOF
    )

`E1167` is raised:

    E1167: Argument name shadows existing variable: _

**Expected behavior**

No error is raised.  This is echo'ed:

    [[1], [2], [3]]

**Environment**

 - Vim version: 8.2 Included patches: 1-2746
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(367)

**Additional context**

Since 8.2.745, `_` is a special name for an argument, as documented at `:h vim9-ignored-argument`.  It's meant to be ignored, and can be repeated.

The purpose of the rule which disallows shadowing is to avoid an error where we accidently use the same name for 2 variables in 2 different scopes, and one silently overrides the other which could lead to subtle bugs.  There is no such risk if we intend to ignore the argument, so this rule should be lifted for `_`.

Otherwise, we need to write something like this which looks awkward:

    :vim9 echo range(3)->mapnew((_, v) => [v]->map((__, w) => w + 1))
                                                    ^^
                                                    awkward

**Comment by lacygoill** [comment]
This new syntax is very handy.  Could it be extended to the unpack notation?
```vim
vim9script
def Func(): list<string>
    return ['one', 'to be ignored', 'two']
enddef
var x: string
var y: string
[x, _, y] = Func()
```
    E1181: Cannot use an underscore here
    E1181: Cannot use an underscore here

**Comment by brammool** [comment]
Yes, this would be useful for unpacking.  Thanks for the hint.

**Comment by lacygoill** [comment]
Not sure whether it's working as intended, but an underscore cannot be used in a `:for` loop:
```vim
for _ in range(3)
    echo 'do this three times'
endfor
```
    E1181: Cannot use an underscore here

It would be convenient if it worked; for the cases where we want to repeat something a given number of times, and don't need any variable to refer to the index of the iteration in the loop.

Otherwise, we have to give a proper name to the iteration variable:
```vim
for i in range(3)
    echo 'do this three times'
endfor
```
But it looks weird, because upon reading the `:for` statement, we immediately assume that `i` is referred to somewhere in the loop (which might be long, so we might lose time trying to find it).  With `_`, the code would be more meaningful; we would immediately know that we don't care about the index of the iteration.

**Comment by lacygoill** [comment]
> Not sure whether it's working as intended

No, it must be a bug, because we can use an underscore when iterating over a list of variables:
```vim
vim9script
for [_, n] in [['a', 1], ['b', 2]]
    echo n
endfor
```
    1
    2
