### ISSUE TITLE
do_debug memory leak

### ISSUE THREAD

**Issue by justinmk** [vim/vim#811]
Neovim ASAN found a leak from patch 7.4.1102: https://github.com/neovim/neovim/pull/4734#issuecomment-219323138

Proposed fix: https://github.com/neovim/neovim/pull/4734/commits/a59603a20833d2003ea4c0db7e2b02708bf4c59d

**Comment by brammool** [comment]
Justin Keyes wrote:

> ASAN found a leak from patch 7.4.1102: https://github.com/neovim/neovim/pull/4734#issuecomment-219323138
> 
> Proposed fix: https://github.com/neovim/neovim/pull/4734/commits/a59603a20833d2003ea4c0db7e2b02708bf4c59d

Thanks.  It's easier to free the pointer just before assigning a new
value.

## 

OLD WOMAN: King of the WHO?
ARTHUR:    The Britons.
OLD WOMAN: Who are the Britons?
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///
