### ISSUE TITLE
Option argument --clean isn't in vim.man

### ISSUE THREAD

**Issue by ma11hew28** [vim/vim#8116]
I didn't find `--clean` in the output of `man vim`.

But I found it with `:h --clean`.

Vim 8.2.2730

**Comment by cecamp** [comment]
There are a lot of options available on the command line for vim that are not mentioned in `man vim`. See `:help starting` while in vim and you'll see quite a few.

**Comment by ma11hew28** [comment]
Oh, OK. I didn't realize that. I just checked a couple other options (the ones listed above and below `:h --clean`) and saw that they were mentioned in `man vim`. But now I see that, like you said, other options are also missing from `man vim`, such as `--ttyfail`.

**Comment by brammool** [comment]
Matthew Mario Di Pasquale wrote:

> I didn't find `--clean` in the output of `man vim`.

Indeed.  I'll add it, it's quite useful.


-- 
In a world without walls and borders, who needs windows and gates?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ma11hew28** [comment]
OK, sounds good. Thanks, @brammool.

**Comment by lacygoill** [comment]
Fixed by https://github.com/vim/vim/commit/56994d215815139207f3c5ce02a1720e44e93c09
