### ISSUE TITLE
Multi-line Comment Indenting With C -- incorrect initial spacing

### ISSUE THREAD

**Issue by cecamp** [vim/vim#8118]
**Describe the bug**
Normally, a multi-line comment in C will show a new "*" at the correct indentation every time a carriage return is entered. However, that is not the case with the attached example file. Instead, extra (unwanted) spaces are prepended prior to the asterisk. Removing a line or two from the example file often shows no initial spacing.
(hopefully I've successfully attached cindent-prblm.c and bad.vimrc, because although nominally attached I don't see a confirmation list)

**To Reproduce**
Detailed steps to reproduce the behavior:
1. vim -u bad.vimrc cindent-prblm.c
2. Go to bottom of file:  G
3. Append to bottom of file: o
4. You'll see that, instead of beginning with " * ", the line begins with a number of unwanted extra spaces: "        * "
5. I will note that deleting a line in the comment area above frequently changes the number of unwanted initial spaces, sometimes yielding no initial spaces; ie. "* "

**Expected behavior**
It should start with " * " (or some number of spaces following the asterisk).
You can see what it should start with by 
1. vim -u bad.vimrc cindent-prblm.c
2. Go to 4th line:  4G
3. Append:  o

**Environment (please complete the following information):**
 - Vim version [e.g. 8.1.1234] (Or paste the result of `vim --version`.)
	VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 16 2021 16:08:47)
	Included patches: 1-2772
	Compiled by cec@sphinx.fios-router.home
	Huge version with GTK3 GUI.  Features included (+) or not (-):
 - OS: [e.g. Ubuntu 18.04, Windows 10 1809, macOS 10.14]
	Scientific Linux release 7.9 (Nitrogen)
 - Terminal: [e.g. GNOME Terminal, mintty, iTerm2, tmux, GNU screen] (Use GUI if you use the GUI.)
   gnome terminal 3.28.2

**Comment by cecamp** [comment]
Looks like "Attach files by ...selecting..." them did not work. Please see the vimdev mailing list for the two files.

**Comment by brammool** [comment]
Your 'cinoptions' ends in "*30", which means Vim will look back only 30 lines for the start of a comment.
But the comment is 32 lines long.  Either remove that restriction, or use a larger number.  "*50" works fine.
