### ISSUE TITLE
mksession vs splitbelow and splitright

### ISSUE THREAD

**Issue by habamax** [vim/vim#8119]
**Describe the bug**

`:mksession` saves `splitbelow` and `splitright` even though `set sessionoptions=buffers,curdir,tabpages,winsize`

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim -Nu NONE`
2. `:set splitbelow splitright`
3. `:set sessionoptions=buffers,curdir,tabpages,winsize`  -- note there is no `options` here
4. `:mksession test.vim`
5. exit vim and run again `vim -Nu NONE`
6. `:source test.vim`
7. `:split`
8. window is splitted with `splitbelow`

**Expected behavior**

Window should be splitted with default `nosplitbelow`.

`:mksession` should not save `splitbelow` and `splitright` options.

**Environment (please complete the following information):**
 - Vim version [e.g. 8.2.2771]
 - OS: win10
 - Terminal: cmd.exe

**Additional context**

my saved session `test.vim`, and there is `set splitbelow splitright`:

```
let SessionLoad = 1
if &cp | set nocp | endif
let s:so_save = &g:so | let s:siso_save = &g:siso | setg so=0 siso=0 | setl so=-1 siso=-1
let v:this_session=expand("<sfile>:p")
silent only
silent tabonly
cd ~
if expand('%') == '' && !&modified && line('$') <= 1 && getline(1) == ''
  let s:wipebuf = bufnr('%')
endif
set shortmess=aoO
argglobal
%argdel
set splitbelow splitright
wincmd t
set winminheight=0
set winheight=1
set winminwidth=0
set winwidth=1
tabnext 1
if exists('s:wipebuf') && len(win_findbuf(s:wipebuf)) == 0
  silent exe 'bwipe ' . s:wipebuf
endif
unlet! s:wipebuf
set winheight=1 winwidth=20 shortmess=filnxtToOS
set winminheight=1 winminwidth=1
let s:sx = expand("<sfile>:p:r")."x.vim"
if filereadable(s:sx)
  exe "source " . fnameescape(s:sx)
endif
let &g:so = s:so_save | let &g:siso = s:siso_save
nohlsearch
doautoall SessionLoadPost
unlet SessionLoad
" vim: set ft=vim :
```

**Comment by habamax** [comment]
I have tried with other options:

1. global `backspace` is not saved into session file
2. local to window `number` is not saved into session file too.

**Comment by lacygoill** [comment]
[The same issue applies to these options](https://github.com/lacygoill/vim-session/blob/fee6cbfc618ab951137001853d57ba82fa8509ea/plugin/session.vim#L635-L665):

   - `shortmess`
   - `splitbelow`
   - `splitright`
   - `showtabline`
   - `winheight`
   - `winminheight`
   - `winminwidth`
   - `winwidth`

A long time ago, I wrote that it couldn't be avoided; but now that I re-read myself, I'm not so sure anymore.  Maybe Vim could save the current values of these options in a script-local dictionary at the start of the session script; but not the current values at the time the script is created; the ones at the time the script is sourced.  And Vim would use this info at the end of the script to restore the options.

**Comment by habamax** [comment]
@lacygoill the thing is why `splitbelow` and `splitright` are saved in the first place...

If I do the same steps but explicitly do `set nosplitbelow nosplitright` -- they also would be saved!

```
let SessionLoad = 1
if &cp | set nocp | endif
let s:so_save = &g:so | let s:siso_save = &g:siso | setg so=0 siso=0 | setl so=-1 siso=-1
let v:this_session=expand("<sfile>:p")
silent only
silent tabonly
cd ~
if expand('%') == '' && !&modified && line('$') <= 1 && getline(1) == ''
  let s:wipebuf = bufnr('%')
endif
set shortmess=aoO
argglobal
%argdel
set splitbelow splitright
set nosplitbelow
set nosplitright
wincmd t
set winminheight=0
set winheight=1
set winminwidth=0
set winwidth=1
tabnext 1
if exists('s:wipebuf') && len(win_findbuf(s:wipebuf)) == 0
  silent exe 'bwipe ' . s:wipebuf
endif
unlet! s:wipebuf
set winheight=1 winwidth=20 shortmess=filnxtToOS
set winminheight=1 winminwidth=1
let s:sx = expand("<sfile>:p:r")."x.vim"
if filereadable(s:sx)
  exe "source " . fnameescape(s:sx)
endif
let &g:so = s:so_save | let &g:siso = s:siso_save
nohlsearch
doautoall SessionLoadPost
unlet SessionLoad
" vim: set ft=vim :
```
