### ISSUE TITLE
`:term ++curwin` unexpected behavior with `ctrl+d`

### ISSUE THREAD

**Issue by amadeus** [vim/vim#8121]
**Describe the bug**
If you have a terminal buffer taking up the entire view and a hidden buffer, pressing `ctrl+d` to kill the terminal buffer will close vim completely, instead of moving to the hidden buffer under a normal type of `:bd` action.

**To Reproduce**
1. Run `vim --clean`
2. `:set hidden`
3. `:edit file.md`
4. `:term ++curwin`
5. Press the hotkey `ctrl+d` to kill the session, and vim will close

**Expected behavior**
I expect vim to return to the hidden buffer or a `[No Name]` buffer if hidden is set and there are no more buffers

**Environment (please complete the following information):**
 - Vim version: 8.2.2750
 - OS: macOS 11.2.3
 - Terminal: iTerm2

**Comment by brammool** [comment]
This is the intended behavior.  That a hidden buffer exists doesn't prevent Vim from exiting.  If you would edit a few files and then ":quit" Vim also exits.  If the buffer is modified then Vim doesn't quit.

**Comment by amadeus** [comment]
I guess I just don't see `ctrl+d` as an equivalent to `:quit` operation. Quit is very explicit about closing vim itself, `ctrl+d` is more like - disconnect from this session (in my head it maps to `:bd` more than `:quit`. Is there an equivalent command that kills the terminal session without closing vim?

**Comment by brammool** [comment]
Not really, it's like closing the last window.
You can use :term ++curwin ++noclose
Then after exiting the shell the window remains, and you can do :edit to edit another file.
