### ISSUE TITLE
is it possible to make 'switchbuf' stick on specific winid?

### ISSUE THREAD

**Issue by Shane-XB-Qian** [vim/vim#8122]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

current default value of option `switchbuf` or its new added value 'uselast' -their behavior actually looks a bit magic,
// since perhaps it was not a 'quickfix' commands issued..
for now i think it's not very certain sure which window it would jump to.. 

**Describe the solution you'd like**

how about adding a new value e.g 'tgtwinid:123'
- if winid '123' not existed, then raise err.
- if found winid '123', then stick on it.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by tonymec** [comment]
`'switchbuf'` is (at the moment) a global option; it is a comma-separted string, and its default value is the empty string, meaning that every window-splitting command wil indeed open a new split window.

When coming from a non-quickfix window, only the first two possible entries are taken into account: `usetab`, `useopen` without `usetab`, or neither.

The other values come into play when a quickfix command is issued. IIUC, `split`, `vsplit` and `newtab` will open a new window for the source files opened by a quickfix command and (still IIUC) go back to the previous editfile when that source file is closed. I suppose that using `:set swb=useopen,split,uselast` can be used to reuse an existing window when using `:new` etc. for an existing edit file, to open source files opened by `:helpgrep, :vimgrep, :make` etc. in a new window, and load sucessive source files in a single window. CAUTION: This is how I read the help for `switchbuf`, the quickfix command I use most is `:helpgrep` and help files replace each other in a single window even with the default settings, so I may be in error.

In any case, splitting commands (`:new`, `:split`, `vsplit` etc.) take as argument (when one is used) a filename, not a window ID. Window IDs are not portable from one session to another, a small experiment I just did seems to indicate that they start at 1000, but in any case (a) it cannot be guaranteed that the same buffer name will correspond to the same window ID after quitting and restarting Vim; (b) after closing a window I suppose that its ID becomes forever unavailable in that Vim session; and (c) IMHO it would be hugely impractical, even dangerous, to force all split commands to go to the same target window regardless of the filename given as argument.

Best regards,
Tony.

**Comment by Shane-XB-Qian** [comment]
```
+----------+--------------------------------------+---------+
|          |                                      |         |
|          |                                      |         |
|          |                bar_fs                |         |
|          |                                      |         |
|          |                                      |         |
|          |                                      |         |
|          |--------------------------------------|         |
|          |                                      |         |
|          |                                      |         |
|          |                                      |         |
|          |                                      |         |
|  netrw   |                foo_fs                |  sth.   |
|          |                                      |         |
|          |                                      |         |
|          |                                      |         |
|          |                                      |         |
|          |                                      |         |
|          +--------------------------------------+         |
|          |                                      |         |
|          |                                      |         |
|          |                  qf                  |         |
|          |                                      |         |
|          |                                      |         |
+----------+--------------------------------------+---------+
```
// i supposed you agreed that help of 'switchbuf' is not quite easy to understand for most people.. :-)

for example above a general frame of splits, now you are working on 'qf' window to look over its items, how to make new opened into certainly just into 'foo_fs' window or 'bar_fs' looks needed quite magic.. :-) looks no 100% sure.. since commands used or last window visited or etc would make it different.. and sometimes it is hated if it was opened into 'netrw' window...

// so i was thinking if it's possible to stick on specific winid, but well, you are right, that winid into that option value should be just a **temp** setting, as long as finished e.g qf works, then you should reset it. 
// or you had another workaround is ok, for now just is a thinking, what do you think?

**Comment by tonymec** [comment]
No I don't have another workaround — or on second thought, maybe I do, see below. For `:helpgrep` reusing the already present help window is OK for me. For `:vimgrep` I neither want my existing windows to be obliterated nor the grepping operation to open 50 new windows if it looks into that many files, usually I open an empty window just before I start that command but I'll have to ponder possible better ways to do it.

Maybe opening an empty window just before running a quickfix command other than `:helpgrep` is the workaround you need: AFAIK it will open all files where there is a match into that formerly empty window. I don't open the quickfix window itself — I go directly to the place being matched.

I also define the following mappings in my vimrc:
```vim
  if has('quickfix')
    map  <F2>    :cnext<CR>
    map  <S-F2>  :cprev<CR>
  endif
```
and if I had had additional F keys not yet in use I would also have mapped `:cnfile, :cpfile, :cfirst` and `clast`.

Best regards,
Tony.

**Comment by Shane-XB-Qian** [comment]
ahaha... i see.. yea, i agree about 70~80% it is working as expected as long as you knew the trick of these..
but the problem is you may move the cursor to another window (then 'uselast' is broken'), and/or you just issued a 'enter' which not a quickfix command, then it maybe broken.. or 'netrw' was the last/neared window or somehow, then it maybe broken..
// so if wanted to be 100% sure, then that 'switchbuf' option value can be set to/with a specific winid looks was a choice.
// but well, if it had some cost/outage or something i didnot image, then let it be, so far most situation it can be working....

**Comment by Shane-XB-Qian** [comment]
this can stick on pvw actually, so let it be. closing..
