### ISSUE TITLE
Vim9: cannot omit quotes around autoload function name when passed to builtin function expecting funcref

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8124]
**Describe the bug**

In Vim9 script, we cannot omit the quotes around the name of an autoload function when passing it as an argument to a builtin function which expects a funcref.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        set rtp=/tmp/some
        var dir = '/tmp/some/autoload'
        mkdir(dir, 'p')
        var lines =<< trim END
            vim9script
            def script#func()
                echo 'script func'
            enddef
        END
        writefile(lines, dir .. '/script.vim')
        def Func()
            call(script#func, [])
        enddef
        Func()
    EOF
    )

`E1001` is raised:

    E1001: Variable not found: script#func

**Expected behavior**

No error is raised, because it is allowed to omit the quotes around the name of a user defined function, when it's passed as an argument to a function which accepts a funcref:

> Omitting function() ~
>
> A user defined function can be used as a function reference in an expression
> without `function()`. The argument types and return type will then be checked.
> The function must already have been defined. >
>
>        var Funcref = MyFunction

**Environment**

 - Vim version: 8.2 Included patches: 1-2783
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(367)

**Additional context**

Actually, the previously quoted excerpt from the help does not explicitly tell us that the quotes can be omitted.  It's about `function()`.  However, it seems to also apply to the quotes, at least in the case of `call()`:
```vim
vim9script
def MyCall()
    echo 'my call'
enddef
def Func()
    call('MyCall', [])
enddef
Func()
```
    my call
```vim
vim9script
def MyCall()
    echo 'my call'
enddef
def Func()
    call(MyCall, [])
enddef
Func()
```
    my call

Notice that the first snippet doesn't raise any error, which confirms what the help says: `function()` can be omitted.  Also notice that the second snippet doesn't raise any error either, which suggests that what the help says about `function()` also apply to the quotes (at least in the case of `call()`).

---

One could argue that the help says that – for `function()` (and the quotes?) to be omitted – the user function must have already been defined.  That's not the case of an autoload function which has never been called; it's not defined yet.

OK, but first, why does this requirement apply to the quotes, but not to `function()`?
```vim
vim9script
set rtp=/tmp/some
var dir = '/tmp/some/autoload'
mkdir(dir, 'p')
var lines =<< trim END
    vim9script
    def script#func()
        echo 'script func'
    enddef
END
writefile(lines, dir .. '/script.vim')
def Func()
    call('script#func', [])
enddef
Func()
```
    script func

Notice that this snippet doesn't give any error, even though we've omitted `function()` around the name of an autoload function.  If we can omit `function()` here, I would expect we can also omit the quotes.

Second, the issue persists even if the autoload function has been called once before `Func()` was compiled, so as to make sure it's defined when Vim finds out that we've omitted the quotes around its name:
```vim
vim9script
set rtp=/tmp/some
var dir = '/tmp/some/autoload'
mkdir(dir, 'p')
var lines =<< trim END
    vim9script
    def script#func()
        echo 'script func'
    enddef
END
writefile(lines, dir .. '/script.vim')
script#func()
def Func()
    call(script#func, [])
enddef
Func()
```
    E1001: Variable not found: script#func

Notice that this snippet gives an error, even though `script#func()` was called *before* `Func()` was compiled, hence it was also already defined at compile time.

---

The issue persists at the script level:
```vim
vim9script
set rtp=/tmp/some
var dir = '/tmp/some/autoload'
mkdir(dir, 'p')
var lines =<< trim END
    vim9script
    def script#func()
        echo 'script func'
    enddef
END
writefile(lines, dir .. '/script.vim')
call(script#func, [])
```
    E121: Undefined variable: script#func

**Comment by lacygoill** [comment]
Same issue with `function()`:
```vim
vim9script
set rtp=/tmp/some
var dir = '/tmp/some/autoload'
mkdir(dir, 'p')
var lines =<< trim END
    vim9script
    def script#func()
        echo 'script func'
    enddef
END
writefile(lines, dir .. '/script.vim')
def Func()
    function(script#func)()
enddef
Func()
```
    E1001: Variable not found: script#func

And with `setqflist()`:
```vim
vim9script
set rtp=/tmp/some
var dir = '/tmp/some/autoload'
mkdir(dir, 'p')
var lines =<< trim END
    vim9script
    def script#qftf(info: any): any
        return repeat(['test'], 100)
    enddef
END
writefile(lines, dir .. '/script.vim')
def Func()
    setqflist([], 'r', {lines: v:oldfiles, efm: '%f', quickfixtextfunc: script#qftf})
    cw
enddef
Func()
```
    E1001: Variable not found: script#qftf

And with `sort()`:
```vim
vim9script
set rtp=/tmp/some
var dir = '/tmp/some/autoload'
mkdir(dir, 'p')
var lines =<< trim END
    vim9script
    def script#sort(line1: string, line2: string): number
        return line1 > line2 ? 1 : -1
    enddef
END
writefile(lines, dir .. '/script.vim')
def Func()
    echo ['bbb', 'aaa']->sort(script#sort)
enddef
Func()
```
    E1001: Variable not found: script#sort

And with `timer_start()`:
```vim
vim9script
set rtp=/tmp/some
var dir = '/tmp/some/autoload'
mkdir(dir, 'p')
var lines =<< trim END
    vim9script
    def script#callback(_: number)
        echom 'my callback'
    enddef
END
writefile(lines, dir .. '/script.vim')
def Func()
    timer_start(0, script#callback)
enddef
Func()
```
    E1001: Variable not found: script#callback

---

In all cases, the issue disappears when we no longer omit the quotes:
```vim
vim9script
set rtp=/tmp/some
var dir = '/tmp/some/autoload'
mkdir(dir, 'p')
var lines =<< trim END
    vim9script
    def script#func()
        echo 'script func'
    enddef
END
writefile(lines, dir .. '/script.vim')
def Func()
    function('script#func')()
enddef
Func()
```
    script func
```vim
vim9script
set rtp=/tmp/some
var dir = '/tmp/some/autoload'
mkdir(dir, 'p')
var lines =<< trim END
    vim9script
    def script#qftf(info: any): any
        return repeat(['test'], 100)
    enddef
END
writefile(lines, dir .. '/script.vim')
def Func()
    setqflist([], 'r', {lines: v:oldfiles, efm: '%f', quickfixtextfunc: 'script#qftf'})
    cw
enddef
Func()
```
    no error
```vim
vim9script
set rtp=/tmp/some
var dir = '/tmp/some/autoload'
mkdir(dir, 'p')
var lines =<< trim END
    vim9script
    def script#sort(line1: string, line2: string): number
        return line1 > line2 ? 1 : -1
    enddef
END
writefile(lines, dir .. '/script.vim')
def Func()
    echo ['bbb', 'aaa']->sort('script#sort')
enddef
Func()
```
    ['aaa', 'bbb']
```vim
vim9script
set rtp=/tmp/some
var dir = '/tmp/some/autoload'
mkdir(dir, 'p')
var lines =<< trim END
    vim9script
    def script#callback(_: number)
        echom 'my callback'
    enddef
END
writefile(lines, dir .. '/script.vim')
def Func()
    timer_start(0, 'script#callback')
enddef
Func()
```
    my callback

---

And in all cases, the quotes can be omitted again when the function is no longer autoloaded (which seems inconsistent):
```vim
vim9script
def ScriptFunc()
    echo 'script func'
enddef
def Func()
    function(ScriptFunc)()
enddef
Func()
```
    script func
```vim
vim9script
def MyQftf(info: any): any
    return repeat(['test'], 100)
enddef
def Func()
    setqflist([], 'r', {lines: v:oldfiles, efm: '%f', quickfixtextfunc: MyQftf})
    cw
enddef
Func()
```
    no error
```vim
vim9script
def MySort(line1: string, line2: string): number
    return line1 > line2 ? 1 : -1
enddef
def Func()
    echo ['bbb', 'aaa']->sort(MySort)
enddef
Func()
```
    ['aaa', 'bbb']
```vim
vim9script
def MyCallback(_: number)
    echom 'my callback'
enddef
def Func()
    timer_start(0, MyCallback)
enddef
Func()
```
    my callback

**Comment by lacygoill** [comment]
Same issue with `eval()`;  `function()` and the quotes can be omitted for a custom function:
```vim
vim9script
def Foo(): string
    return 'working'
enddef
def Func()
    echo Foo->string()->eval()()
enddef
Func()
```
    working

But not when the function is autoloaded:
```vim
vim9script
set rtp=/tmp/some
var dir = '/tmp/some/autoload'
mkdir(dir, 'p')
var lines =<< trim END
    vim9script
    def script#func(): string
        return 'working'
    enddef
END
writefile(lines, dir .. '/script.vim')
def Func()
    echo script#func->string()->eval()()
enddef
Func()
```
    E1001: Variable not found: script#func

Same issue with `filter()`:
```vim
vim9script
def MyFilter(i: number, v: string): bool
    return v =~ 'keep'
enddef
def Func()
    echo ['removeme', 'keepme', 'deleteme']->filter(MyFilter)
enddef
Func()
```
    ['keepme']
```vim
vim9script
set rtp=/tmp/some
var dir = '/tmp/some/autoload'
mkdir(dir, 'p')
var lines =<< trim END
    vim9script
    def script#filter(i: number, v: string): bool
        return v =~ 'keep'
    enddef
END
writefile(lines, dir .. '/script.vim')
def Func()
    echo ['removeme', 'keepme', 'deleteme']->filter(script#filter)
enddef
Func()
```
    E1001: Variable not found: script#filter

And with `map()`:
```vim
vim9script
def MyMap(i: number, v: number): number
    return v * 100
enddef
def Func()
    echo [1, 2, 3]->map(MyMap)
enddef
Func()
```
    [100, 200, 300]
```vim
vim9script
set rtp=/tmp/some
var dir = '/tmp/some/autoload'
mkdir(dir, 'p')
var lines =<< trim END
    vim9script
    def script#map(i: number, v: number): number
        return v * 100
    enddef
END
writefile(lines, dir .. '/script.vim')
def Func()
    echo [1, 2, 3]->map(script#map)
enddef
Func()
```
    E1001: Variable not found: script#map

And with `search()`:
```vim
vim9script
setline(1, ['if', '" endif', 'endif'])
syn on
set ft=vim
def MySkip(): bool
    return synstack('.', col('.'))
        ->mapnew((_, v) => synIDattr(v, 'name'))
        ->match('\ccomment') != -1
enddef
def Func()
    echo search('\<endif\>', '', 0, 0, MySkip)
enddef
Func()
```
    3
```vim
vim9script
set rtp^=/tmp/some
var dir = '/tmp/some/autoload'
mkdir(dir, 'p')
var lines =<< trim END
    vim9script
    def script#skip(): bool
        return synstack('.', col('.'))
            ->mapnew((_, v) => synIDattr(v, 'name'))
            ->match('\ccomment') != -1
    enddef
END
writefile(lines, dir .. '/script.vim')
setline(1, ['if', '" endif', 'endif'])
syn on
set ft=vim
def Func()
    echo search('\<endif\>', '', 0, 0, script#skip)
enddef
Func()
```
    E1001: Variable not found: script#skip

And with `searchpair()`:
```vim
vim9script
setline(1, ['if', '" endif', 'endif'])
syn on
set ft=vim
def MySkip(): bool
    return synstack('.', col('.'))
        ->mapnew((_, v) => synIDattr(v, 'name'))
        ->match('\ccomment') != -1
enddef
def Func()
    echo searchpair('\<if\>', '', '\<endif\>', '', MySkip)
enddef
Func()
```
    3
```vim
vim9script
set rtp^=/tmp/some
var dir = '/tmp/some/autoload'
mkdir(dir, 'p')
var lines =<< trim END
    vim9script
    def script#skip(): bool
        return synstack('.', col('.'))
            ->mapnew((_, v) => synIDattr(v, 'name'))
            ->match('\ccomment') != -1
    enddef
END
writefile(lines, dir .. '/script.vim')
setline(1, ['if', '" endif', 'endif'])
syn on
set ft=vim
def Func()
    echo searchpair('\<if\>', '', '\<endif\>', '', script#skip)
enddef
Func()
```
    E1001: Variable not found: script#skip

And with `substitute()`:
```vim
vim9script
def MyRep(): string
    return '1'
enddef
def Func()
    echo substitute('aaa', '.', MyRep, 'g')
enddef
Func()
```
    111
```vim
vim9script
set rtp=/tmp/some
var dir = '/tmp/some/autoload'
mkdir(dir, 'p')
var lines =<< trim END
    vim9script
    def script#rep(): string
        return '1'
    enddef
END
writefile(lines, dir .. '/script.vim')
def Func()
    echo substitute('aaa', '.', script#rep, 'g')
enddef
Func()
```
    E1001: Variable not found: script#rep

**Comment by lacygoill** [comment]
Closing because I think the errors are to be expected when the autoload function has not been defined yet.  Although, maybe it should be made to work for the cases where it *has* been defined; but that's a corner case which doesn't seem important.

**Comment by brammool** [comment]
Well, I suppose we could support the non-quoted autoload function name, but it would imply to load that function at that spot.  Thus when quoted the name would be passed around until the function is actually called (and you might get an error then), or the name is used without quotes and it is loaded right away and any errors are reported.  This could be useful.

**Comment by lacygoill** [comment]
> or the name is used without quotes and it is loaded right away and any errors are reported.

It would be loaded right away at compile time, or right away at runtime?  If we write this in a non-autoloaded script:

    def Func()
        call(script#func, [])
    enddef
    defcompile

When `Func` is compiled, would the autoloaded script be sourced immediately to load the definition of `script#func`?  Or would it be deferred to runtime?

This matters when we want to avoid increasing Vim startup time.

**Comment by lacygoill** [comment]
> It would be loaded right away at compile time, or right away at runtime?

Considering that this:

    call(script#func, [])

should be equivalent to this:

    script#func()

And that Vim doesn't autoload a script at compile time just because one of its functions is called in a `:def` function:
```vim
vim9script
set rtp=/tmp/some
var dir = '/tmp/some/autoload'
mkdir(dir, 'p')
var lines =<< trim END
    vim9script
    def script#func()
        echo 'script func'
    enddef
END
writefile(lines, dir .. '/script.vim')
def Func()
    script#func()
enddef
defcompile
scriptnames
```
    1: /proc/10710/fd/11
    ^------------------^
    no /tmp/some/autoload/script.vim

I guess the answer is "at runtime".  Which is good.  It means we could use the syntax without worrying about startup time.

**Comment by brammool** [comment]
>    > or the name is used without quotes and it is loaded right away and any errors are reported.
> 
> It would be loaded right away at compile time, or right away at runtime?  If we write this in a non-autoloaded script:
> 
>     def Func()
>         call(script#func, [])
>     enddef
>     defcompile
> 
> When `Func` is compiled, would the autoloaded script be sourced immediately to load the definition of `script#func`?  Or would it be deferred to runtime?
> 
> This matters when we want to avoid increasing Vim startup time.

It would be loaded at compile time.  And compiled, if script#func is a
:def function.  So this kind of defeats the idea of auto-loading on
demand.  It can be useful e.g. in a filetype plugin, which is loaded
only when editing a file with that filetype.  Then you don't slow down
Vim startup.

-- 
"The sun oozed over the horizon, shoved aside darkness, crept along the
greensward, and, with sickly fingers, pushed through the castle window,
revealing the pillaged princess, hand at throat, crown asunder, gaping
in frenzied horror at the sated, sodden amphibian lying beside her,
disbelieving the magnitude of the frog's deception, screaming madly,
"You lied!"
    - Winner of the Bulwer-Lytton contest (San Jose State University),
      wherein one writes only the first line of a bad novel

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
