### ISSUE TITLE
codecov security incident

### ISSUE THREAD

**Issue by chrisbra** [vim/vim#8125]
There was a [codecov security breach](https://about.codecov.io/security-update/). Apparently it was possible to send out secret tokens with the codecov bash uploader script.

I'd suggest to regenerate the [COVERALLS_REPO_TOKEN](https://coveralls.io/github/vim/vim/settings) and updating it in the secrets section of this [repository](https://github.com/vim/vim/settings/secrets/actions).

I think this is the only one affected.

**Comment by brammool** [comment]
Christian wrote:

> There was a [codecov security
> breach](https://about.codecov.io/security-update/). Apparently it was
> possible to send out secret tokens with the codecov bash uploader
> script.
> 
> I'd suggest to regenerate the
> [COVERALLS_REPO_TOKEN](https://coveralls.io/github/vim/vim/settings)
> and updating it in the secrets section of this
> [repository](https://github.com/vim/vim/settings/secrets/actions).
> 
> I think this is the only one affected.

Done that.  Let me know if you spot a problem.

-- 
~
~
~
".signature" 4 lines, 50 characters written

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
closing then.
