### ISSUE TITLE
Partials are compared incorrectly

### ISSUE THREAD

**Issue by ZyX-I** [vim/vim#813]
When comparing funcrefs they are assumed true if they are both partials or both not and functions they point to are the same. I think this is invalid, specifically:

Funcrefs should be compared unequal (!=) if
1. They point to different functions (OK).
2. One is partial and one is not (FAIL).
3. Both are partials, but with different number of arguments (FAIL). Even the following two are equal: `function('1126', [1])`, `function('1126', {'f': function('1126')})`
4. Both are partials, but one has dictionary attached and one not (FAIL).
5. Both are partials, but attached arguments differ (FAIL).
6. Both are partials, but attached dictionaries differ (FAIL).

Funcrefs should be compared not same (isnot) if (option 1)
1. They point to different functions (OK).
2. One is partial and one is not (OK).
3. Both are partials, but dictionaries are not same (FAIL).
4. Both are partials, but one has dictionary attached and one not (FAIL).
5. Both are partials, but number of arguments differ (FAIL).
6. Both are partials, but arguments are not identical (FAIL).

(option 2) (is, I think, more consistent, but less useful)
1. They point to different functions (OK).
2. One is partial and one is not (OK).
3. partial_T pointers point to different addresses (FAIL).

---

Specifically I mean here:
1. Partials _are_ containers, even though read-only ones. So `==` and `is` should behave differently.
2. Partials are containers, so `==` should compare what they contain like it does for other containers.
3. Partials are containers, so `is` should check their identity and not their contents. In second option identity is basically the address of the container, like with other containers. In first option identity is the tuple (function name, (argument1 identity, …), dictionary identity).

**Comment by brammool** [comment]
Nikolai Pavlov wrote:

> When comparing funcrefs they are assumed true if they are both partials or both not and functions they point to are the same. I think this is invalid, specifically:
> 
> Funcrefs should be compared unequal (!=) if
> 1. They point to different functions (OK).
> 2. One is partial and one is not (FAIL).
> 3. Both are partials, but with different number of arguments (FAIL). Even the following two are equal: `function('1126', [1])`, `function('1126', {'f': function('1126')})`
> 4. Both are partials, but one has dictionary attached and one not (FAIL).
> 5. Both are partials, but attached arguments differ (FAIL).
> 6. Both are partials, but attached dictionaries differ (FAIL).
> 
> Funcrefs should be compared not same (isnot) if (option 1)
> 1. They point to different functions (OK).
> 2. One is partial and one is not (OK).
> 3. Both are partials, but dictionaries are not same (FAIL).
> 4. Both are partials, but one has dictionary attached and one not (FAIL).
> 5. Both are partials, but number of arguments differ (FAIL).
> 6. Both are partials, but arguments are not identical (FAIL).
> 
> (option 2) (is, I think, more consistent, but less useful)
> 1. They point to different functions (OK).
> 2. One is partial and one is not (OK).
> 3. partial_T pointers point to different addresses (FAIL).
> 
> ---
> 
> Specifically I mean here:
> 1. Partials _are_ containers, even though read-only ones. So `==` and `is` should behave differently.
> 2. Partials are containers, so `==` should compare what they contain like it does for other containers.
> 3. Partials are containers, so `is` should check their identity and not their contents. In second option identity is basically the address of the container, like with other containers. In first option identity is the tuple (function name, (argument1 identity, …), dictionary identity).

Can you write the expected behavior in the form of a test?

## 

BLACK KNIGHT: I'm invincible!
ARTHUR:       You're a looney.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ZyX-I** [comment]
``` VimL
let d1 = {}
let d2 = {}
function d1.f1() dict
endfunction
function d1.f2() dict
endfunction
let F1 = get(d1, 'f1')
let F2 = get(d1, 'f2')
let F1d1 = function(F1, d1)
let F2d1 = function(F2, d2)
let F1d1a1 = function(F1d1, [1])
let F1d1a12 = function(F1d1, [1, 2])
let F1a1 = function(F1, [1])
let F1a2 = function(F1, [2])
let F1d2 = function(F1, d2)
let d3 = {'f1': F1, 'f2': F2}
let F1d3 = function(F1, d3)
let F1ad1 = function(F1, [d1])
let F1ad3 = function(F1, [d3])

call assert_match('^function(''\d\+'')$', string(F1))  " Not a partial
call assert_match('^function(''\d\+'')$', string(F2))  " Not a partial
call assert_match('^function(''\d\+'', {.*})$', string(F1d1))  " A partial
call assert_match('^function(''\d\+'', {.*})$', string(F2d1))  " A partial
call assert_match('^function(''\d\+'', [.*])$', string(F1a1))  " No dict

" !=
call assert_true(F1 != F2)  " Different functions
call assert_true(F1 != F1d1)  " Partial /= non-partial
call assert_true(F1d1a1 != F1d1a12)  " Different number of arguments
call assert_true(F1a1 != F1d1a12)  " One has no dict
call assert_true(F1a1 != F1a2)  " Unequal arguments
call assert_true(F1d2 != F1d1)  " Unequal dictionaries
call assert_true(F1d1 == F1d3)  " Equal dictionaries, even though d1 isnot d3

" isnot, option 1
call assert_true(F1 isnot# F2)  " Different functions
call assert_true(F1 isnot# F1d1)  " Partial /= non-partial
call assert_true(F1d1 isnot# F1d3)  " d1 isnot d3, even though d1 == d3
call assert_true(F1a1 isnot# F1d1a12)  " One has no dict
call assert_true(F1a1 isnot# F1a12)  " Different number of arguments
call assert_true(F1ad1 isnot# F1ad3)  " In arguments d1 isnot d3

" isnot, option 2
call assert_true(F1 isnot# F2)  " Different functions
call assert_true(F1 isnot# F1d1)  " Partial /= non-partial
call assert_true(d.f1 isnot# d.f1)  " handle_subscript creates new partial each time
```

**Comment by brammool** [comment]
Nikolai Pavlov wrote:

> ``` VimL
> let d1 = {}
> let d2 = {}
> function d1.f1() dict
> endfunction
> function d1.f2() dict
> endfunction
> let F1 = get(d1, 'f1')
> let F2 = get(d1, 'f2')
> let F1d1 = function(F1, d1)
> let F2d1 = function(F2, d2)
> let F1d1a1 = function(F1d1, [1])
> let F1d1a12 = function(F1d1, [1, 2])
> let F1a1 = function(F1, [1])
> let F1a2 = function(F1, [2])
> let F1d2 = function(F1, d2)
> let d3 = {'f1': F1, 'f2': F2}
> let F1d3 = function(F1, d3)
> let F1ad1 = function(F1, [d1])
> let F1ad3 = function(F1, [d3])
> 
> call assert_match('^function(''\d\+'')$', string(F1))  " Not a partial
> call assert_match('^function(''\d\+'')$', string(F2))  " Not a partial
> call assert_match('^function(''\d\+'', {.*})$', string(F1d1))  " A partial
> call assert_match('^function(''\d\+'', {.*})$', string(F2d1))  " A partial
> call assert_match('^function(''\d\+'', [.*])$', string(F1a1))  " No dict
> 
> " !=
> call assert_true(F1 != F2)  " Different functions
> call assert_true(F1 != F1d1)  " Partial /= non-partial
> call assert_true(F1d1a1 != F1d1a12)  " Different number of arguments
> call assert_true(F1a1 != F1d1a12)  " One has no dict
> call assert_true(F1a1 != F1a2)  " Unequal arguments
> call assert_true(F1d2 != F1d1)  " Unequal dictionaries
> call assert_true(F1d1 == F1d3)  " Equal dictionaries, even though d1 isnot d3
> 
> " isnot, option 1
> call assert_true(F1 isnot# F2)  " Different functions
> call assert_true(F1 isnot# F1d1)  " Partial /= non-partial
> call assert_true(F1d1 isnot# F1d3)  " d1 isnot d3, even though d1 == d3
> call assert_true(F1a1 isnot# F1d1a12)  " One has no dict
> call assert_true(F1a1 isnot# F1a12)  " Different number of arguments
> call assert_true(F1ad1 isnot# F1ad3)  " In arguments d1 isnot d3
> 
> " isnot, option 2
> call assert_true(F1 isnot# F2)  " Different functions
> call assert_true(F1 isnot# F1d1)  " Partial /= non-partial
> call assert_true(d.f1 isnot# d.f1)  " handle_subscript creates new partial each time
> ```

Thanks!  We need to tweak partials a bit more, it's good to have tests
for corner cases.

## 

It is too bad that the speed of light hasn't kept pace with the
changes in CPU speed and network bandwidth. -- wietse@porcupine.org

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dbarnett** [comment]
`:help E694` disagrees with the behavior after this change:

```
                            *E694*
A |Funcref| can only be compared with a |Funcref| and only "equal" and "not
equal" can be used.  Case is never ignored.  Whether arguments or a Dictionary
are bound (with a partial) is ignored.  This is so that when a function is
made a member of a Dictionary it is still considered to be the same function.
To compare partials to see if they bind the same argument and Dictionary
values use string(): >
    echo string(Partial1) == string(Partial2)
```

Can you either
  (a) Change behavior back to agree with the help, or
  (b) Update the help and suggest another mechanism to test whether functions refer to the same function name?

(Context: I'm interested in this change because it's the root cause for https://github.com/google/vim-maktaba/issues/172)

**Comment by ZyX-I** [comment]
@dbarnett You should use `get()` to get function names out of funcref. Previous behaviour breaks semantics of equality comparisons.

Also suggested `string() == string()` comparison does not do what is described here: a paragraph below it states that is/isnot that are checking whether their operands (assuming containers) point to the same memory check “if expressions are referring to the **same** List or Dictionary”. This means that if you use `string(fref1) == string(fref2)` you will check that whether they bind _equal_ arguments, not _same_, and this did not change, that piece of advice was broken from the very beginning.

**Comment by brammool** [comment]
David Barnett wrote:

> `:help E694` disagrees with the behavior after this change:
> 
> ```
>                           *E694*
> A |Funcref| can only be compared with a |Funcref| and only "equal" and "not
> equal" can be used.  Case is never ignored.  Whether arguments or a Dictionary
> are bound (with a partial) is ignored.  This is so that when a function is
> made a member of a Dictionary it is still considered to be the same function.
> To compare partials to see if they bind the same argument and Dictionary
> values use string(): >
>   echo string(Partial1) == string(Partial2)
> ```
> 
> Can you either
>   (a) Change behavior back to agree with the help, or
>   (b) Update the help and suggest another mechanism to test whether functions refer to the same function name?
> 
> (Context: I'm interested in this change because it's the root cause for https://github.com/google/vim-maktaba/issues/172)

Normally I prefer being backwards compatible, but in this case we might
consider the old behavior to be broken.

The help is actually giving a hint about why it's wrong: Comparing two
Funcref variables would result in true, even though they differ in the
bound dictionary and arguments.  I would say these Funcrefs are
different, since calling the function has quite a different effect.

So I tend to think we need to adjust the documentation.

To check if two Funcrefs refer to the same function use get():
    let F1 = ...
    let F2 = ...
    if get(F1, 'name') == get(F2, 'name')
       " same function
    else
       " different function
    endif

## 

hundred-and-one symptoms of being an internet addict:
185. You order fast food over the Internet

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ZyX-I** [comment]
Documentation should be something like this:

```
A |Funcref| can only be compared with a |Funcref| and only "equal" and "not
equal" can be used.  This compares function names, function arguments (if any) 
and bound dictionary (if any), regular funcrefs or partials with different set 
of attached entities (arguments and bound dictionary) are also not equal.  
Case is never ignored when comparing function names, comparing function 
arguments and dictionaries follow the same rules |expr-==| does.  If you want 
to compare only which function two |Funcref|s refer to, use >

    :if get(Fref1, 'name') is# get(Fref2, 'name')
```

**Comment by ZyX-I** [comment]
@brammool I would suggest to never, ever use `==` to compare strings in documentation. Almost nobody needs to follow `&ignorecase` and nobody at all needs to follow it in the example.

**Comment by ZyX-I** [comment]
\* Forgot “to” after “refer”.
