### ISSUE TITLE
Completion window flickers hard in vim but normal in nvim

### ISSUE THREAD

**Issue by HO-COOH** [vim/vim#8131]
**Describe the bug**
In vim, the auto-completion pop-up flickers when holding arrow keys to scroll items, in **all**  the terminals I tried (see environment).

However, neovim works perfectly fine.

**To Reproduce**
A minimal vimrc
```
set nocompatible
set runtimepath^=~\.vim\plugged\coc.nvim
filetype plugin indent on
syntax on
set hidden
```
- Open a file `vim -u mini.vim main.cpp`
- Operate vim
- Trigger an auto-completion

**Expected behavior**
No flickers. Like neovim
![nvim](https://user-images.githubusercontent.com/42881734/115477424-78cc6a80-a209-11eb-9056-5d1dcc517f45.gif)

**Screenshots**
Windows Terminal:
![vim4](https://user-images.githubusercontent.com/42881734/115478011-ca292980-a20a-11eb-8085-dd86f30d8322.gif)

Alacritty:
![vim3](https://user-images.githubusercontent.com/42881734/115477438-8550c300-a209-11eb-93c4-1430342831c2.gif)

**Environment (please complete the following information):**
 - Vim version 8.2 8020000
 - OS: Windows 10 2004, Ubuntu 20.10
 - Terminal: Windows Terminal, alacritty, cmder, old windows console

**Additional context**
Previously I raised this issue under [coc.nvim](https://github.com/neoclide/coc.nvim/issues/3035), but the maintainer seems to indicate it's vim's issue.

**Comment by habamax** [comment]
It is not a minimal repro though. Is it possible to have a repro steps without massive plugin (+nodejs) being involved?

PS Windows command-line vim rendering is slow indeed.

**Comment by habamax** [comment]
My guess -- it is somehow connected with `popup` documentation.

I have tried with YouCompleteMe where there is the same flickering happening if `completeopt` has `popup` and almost no flickering without `popup`.


no popup:

![vim-flicker-no](https://user-images.githubusercontent.com/234774/115495739-fecfcc00-a270-11eb-94b9-5f089d05064d.gif)


popup:

![vim-flicker](https://user-images.githubusercontent.com/234774/115495742-01cabc80-a271-11eb-9dfc-d7e6be7561b6.gif)

**Comment by habamax** [comment]
Not really, it flickers both with or without popups. (my prev message shows flickering difference in gvim which is not the case)

**Comment by HO-COOH** [comment]
The "minimal repro" is from what coc.nvim issue template provides, can't do much about it. And yes, after disable the documentation pop up, aka `suggest.floatEnable` in coc.nvim, there is no flicker anymore. But obviously disabling documentation is not an acceptable workaround.

The thing is that nvim is just god stable with the documentation pop up, with absolutely no flicker at all. I think this is "something" to be improved.

**Comment by Shane-XB-Qian** [comment]
![foo](https://user-images.githubusercontent.com/13550529/115679192-e355e580-a384-11eb-80d7-342540d6aa68.gif)
// this gif capture maybe not looked flash too freq, but actually evey 'enter' newline would flash..

looks it is terminal specific, same vim cfg but had some flash in pure xterm -vs- not xfce-term, maybe not vim bug.
in my case it impacted by 'end-wise' plugin and/or cursor related setting e.g 't_EI', but not sure what's exactly why..

**Comment by dpelle** [comment]
Ticket description says:

> Vim version 8.2 8020000

This is an odd version.  Is it vim-8.2.0802?
If that's the case, it's also a bit old.
Best to try with the latest in git.

**Comment by habamax** [comment]
> This is an odd version. Is it vim-8.2.0802?

I have flickeing with the latest version from the vim-nightly builds.

The main "issue" of the issue is that there is no minimal repro steps.

It has something to do with the way completion plugins populate pmenu and trigger popups.

**Comment by habamax** [comment]
Tried again (YouCompleteMe, Win10, Windows terminal)

 `completeopt`  has `popup`:

![vim-flick](https://user-images.githubusercontent.com/234774/115760127-a94b0a80-a3a9-11eb-8679-48a99136bfee.gif)

 `completeopt`  has no `popup`:

![vim-flick-no](https://user-images.githubusercontent.com/234774/115760167-b536cc80-a3a9-11eb-9b14-a076ca000f79.gif)

**Comment by HO-COOH** [comment]
@dpelle That version is from `:CocInfo`, I have no idea
![image](https://user-images.githubusercontent.com/42881734/115762981-a4666680-a369-11eb-966b-a7f7fa2428e4.png)

@habamax What do you mean by "minimal repro"? It's just coc.nvim plugin and a language server, `coc-clangd` in my case.

**Comment by habamax** [comment]
> @habamax What do you mean by "minimal repro"? It's just coc.nvim plugin and a language server, coc-clangd in my case.

@HO-COOH it means -- no additional plugins with nodejs or compiled CPP server (as with YCM) to reproduce the issue. 

Like

1. run `vim --clean`
2. ...
3. ...
4. ...
5. It should not flicker but it does.

**Comment by HO-COOH** [comment]
Sorry, but I don't really know how to trigger a pop up like the auto completion pop up without using a plugin.

**Comment by habamax** [comment]
> Sorry, but I don't really know how to trigger a pop up like the auto completion pop up without using a plugin.

That is why I called it "the main issue of the issue". Ppl who can provide minimal repro are not interested in it (cause it is some or maybe quite an effort to do for a benefit of minority of users using vim in cmd.exe/winterminal), other ppl just can't do it.

And without minimal repro chances that it would be resolved/fixed are pretty low.

**Comment by brammool** [comment]
Is the main flickering you see the status line switching between "current window" and "non-current window" state?
Or is it something else?
You could set 'writedelay' to better see what redrawing happens.

**Comment by chrisbra** [comment]
> Ticket description says:
> 
>     Vim version 8.2 8020000
> 
> This is an odd version. Is it vim-8.2.0802?
> If that's the case, it's also a bit old.

Isn't that the output of `:echo v:versionlong`, e..g this is plain version: 8.2

**Comment by puremourning** [comment]
@brammool  - I have a minimal repro. The issue seems to happen with `popup_settext()` called on the `info` popup.

Here's the repro:

1. Create redraw-popup.vim:

```viml
" toggle this to see the different behaviours
let g:set_text = get( g:, 'set_text', 1 )

set completefunc=CompleteSimple
set completeopt+=popup
set shortmess+=c
set writedelay=1

function! s:FindStart() abort
  let line = getline('.')
  let start = col('.') - 1
  while start > 0 && line[start - 1] =~ '\a'
    let start -= 1
  endwhile
  return start
endfunction

let s:completions = []
for i in range( 10 )
  let s:completions += map(
        \ split('Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec'),
        \ '{ "word": v:val . i, "info": "More info here" . v:val . i }' )
endfor

" The code is taken directly from the example in the Vim documentation
function! s:CompleteMonth( base ) abort
  " find months matching with "a:base"
  return filter(copy(s:completions), "v:val.word =~ '^' . a:base")
endfunction


function! CompleteSimple( findstart, base ) abort
  if a:findstart
    return s:FindStart()
  else
    return s:CompleteMonth( a:base )
  endif
endfunction


function! s:OnCompleteChanged()
  if !empty( v:completed_item )
    let id = popup_findinfo()
    if id
      if g:set_text
        call popup_settext(
              \ id,
              \ [ 'This is some other text', v:completed_item.info ] )
      endif
      call popup_show( id )
    endif
  endif
endfunction

autocmd CompleteChanged * call s:OnCompleteChanged()

```

2. `vim -Nu NONE -S redraw-popup.vim --cmd 'let g:set_text=1'`
3. type `<C-x><C-u>`
4. type `<C-n>`

Watch as the pum is drawn then cleared and re-drawn just before drawing the info popup.

To compare, run `vim -Nu NONE -S redraw-popup.vim --cmd 'let g:set_text=0'` and repeat. You will see that PUM is not redrawn.

Asiccinema of both cases: https://asciinema.org/a/ovsC3HxILzcFPqMuZJQb5OTaF

**Comment by brammool** [comment]
Ben Jackson wrote:

> @brammool  - I have a minimal repro. The issue seems to happen with `popup_settext()` called on the `info` popup.
> 
> Here's the repro:
> 
> 1. Create redraw-popup.vim:
> 
> ```
> " toggle this to see the different behaviours
> let g:set_text = get( g:, 'set_text', 1 )
> 
> set completefunc=CompleteSimple
> set completeopt+=popup
> set shortmess+=c
> set writedelay=1
> 
> function! s:FindStart() abort
>   let line = getline('.')
>   let start = col('.') - 1
>   while start > 0 && line[start - 1] =~ '\a'
>     let start -= 1
>   endwhile
>   return start
> endfunction
> 
> let s:completions = []
> for i in range( 10 )
>   let s:completions += map(
>         \ split('Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec'),
>         \ '{ "word": v:val . i, "info": "More info here" . v:val . i }' )
> endfor
> 
> " The code is taken directly from the example in the Vim documentation
> function! s:CompleteMonth( base ) abort
>   " find months matching with "a:base"
>   return filter(copy(s:completions), "v:val.word =~ '^' . a:base")
> endfunction
> 
> 
> function! CompleteSimple( findstart, base ) abort
>   if a:findstart
>     return s:FindStart()
>   else
>     return s:CompleteMonth( a:base )
>   endif
> endfunction
> 
> 
> function! s:OnCompleteChanged()
>   if !empty( v:completed_item )
>     let s:last_char_inserted_by_user = v:false
>     let id = popup_findinfo()
>     if id
>       if g:set_text
>         call popup_settext(
>               \ id,
>               \ [ 'This is some other text', v:completed_item.info ] )
>       endif
>       call popup_show( id )
>     endif
>   endif
> endfunction
> 
> autocmd CompleteChanged * call s:OnCompleteChanged()
> 
> ```
> 
> 2. vim -Nu NONE -s redraw-popup.vim --cmd 'let g:set_text=1'
> 3. type `<C-x><C-u>`
> 4. type `<C-n>`
> 
> Watch as the pum is drawn then cleared and re-drawn just before drawing the info popup.
> 
> To compare, run `vim -Nu NONE -s redraw-popup.vim --cmd 'let g:set_text=0'` and repeat. You will see that PUM is not redrawn.
> 
> Asiccinema of both cases: https://asciinema.org/a/ovsC3HxILzcFPqMuZJQb5OTaF 

Thank you very much!  Finally I can see what happens without a
complicated plugin involved.  It appears the window is redrawn, which
causes the popup menu to be overwritten, and then it's drawn again.
Let's see if we can detect this situation and not draw over the popup
menu.  The window does have to be redrawn to reveal the text under the
info popup, which will now appear elsewhere.

-- 
hundred-and-one symptoms of being an internet addict:
163. You go outside for the fresh air (at -30 degrees) but open the
     window first to hear new mail arrive.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Shane-XB-Qian** [comment]
in my case, I Guess it 'redraw' whole (or something like 'redraw!'), but could it just redraw the 'cursor'?
// maybe that's the why, though reset 't_EI' etc can workaround it.. FYI. anyway.

**Comment by habamax** [comment]
Can confirm PMenu is not flickering anymore:

![vim-flick-status](https://user-images.githubusercontent.com/234774/115951583-21204e80-a4ea-11eb-9467-8cb5a1681e10.gif)

Now it is only Statusline that flicks, not sure if it is YouCompleteMe related or no -- you can see how whenever I `<tab>` to select next statusline redraws (also cursor position numbers in statusline is changed too).

**Comment by habamax** [comment]
Sidenote, it is annoying I "can't" change popup color with a colorscheme. It looks like it uses `PmenuSel` instead of dedicated highlight group I can override.

**Comment by habamax** [comment]
@puremourning Ben, if you look at the cursor -- it "flicks" like crazy. It happens if I load YouCompleteMe and only in win terminal. Basically for me it looks like there is a regular blink of the cursor and shimmering blinks between regular ones.

Not sure if I should open an issue in your repo though :).

**Comment by puremourning** [comment]
Max do you get the same cursor/stl redraw behaviour with the minimal repro above? I can post a more maximal approximation to what YCM does too if not. I have it around for these sorts of tests.

**Comment by habamax** [comment]
@puremourning with a minimal repro

* cursor doesn't flick at all (regular blink is there)
* stl redraws as with youcomleteme.

For statusline it looks like when a next candidate is selected the word under cursor is deleted and new word is inserted and statusline reflects it with column position changes.

**Comment by puremourning** [comment]
Ok let’s take that question offline for this thread then. It may be timer related.

**Comment by puremourning** [comment]
> Sidenote, it is annoying I "can't" change popup color with a colorscheme. It looks like it uses `PmenuSel` instead of dedicated highlight group I can override.

https://vimhelp.org/windows.txt.html#preview-popup

You can control it with previewpopup option.

**Comment by habamax** [comment]
> You can control it with previewpopup option.

My help-fu is ... bad. Thank you, Ben!

**Comment by habamax** [comment]
@puremourning I have opened a separate issue on popup styling.

previewpopup doesn't affect the popup either from youcompeleteme or your minimal repro. The help also states default Pmenu is used, but for the popup in question it is clearly PmenuSel.
