### ISSUE TITLE
Dependencies of vim are not mention clearly on vim.org/git.php

### ISSUE THREAD

**Issue by JanPoonthong** [vim/vim#8132]
**Describe the bug**
When I clone vim repository and I tried to build(make) vim, I got a issue that in order to build(make) vim I need `libncurses-dev` and this library `libncurses-dev` is not mention on the docs or anywhere in vim.org.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. I cloned vim from Github
2. Run ./configure -> cause error
3. The error was `tgetent()` can't be called, NOT FOUND!

**Expected behavior**
I would expected it to work after running the command from https://www.vim.org/git.php, working just like that, by not struggling and  finding out the library like `libncurses-dev` to build(make) vim.

**Environment:**
 - Vim version 8.2
 - OS: linux mint: 20.1 (base on Ubuntu)
 - Terminal: GNOME Terminal, not using vim GUI

**Additional context**
I would like to have clear docs on building(making) vim, for example step by step of running the command and the dependencies to installed, because on https://www.vim.org/git.php, they do not specify dependencies and people who are new to vim or linux have to figure it out by their own, so it would amazing if their is a clear docs on running command and work just like that.

**Comment by chrisbra** [comment]
Please have a look into https://github.com/vim/vim/blob/master/src/INSTALL

Note, depending on configure flags, additional dependencies might be needed (gui support, etc). Also see the https://vimhelp.org/vim_faq.txt.html#faq-35.10

**Comment by brammool** [comment]
Configure does mention installing ncurses might be a solution.  It's different for every system, but I suppose many are using Linux.  I can add the name of the libncurses-dev package, that would help quite a few people.
Mentioning this in the documentation is less useful, who reads that?

**Comment by JanPoonthong** [comment]
Thanks @chrisbra for mention docs, everything on src/INSTALL is clear.

**Comment by JanPoonthong** [comment]
@brammool Maybe you could add those dependencies on https://www.vim.org/git.php, because on the site is not clear, what user need to installed in order to build(make) vim. Except that individual go through src/INSTALL and then they will find out the answer.

**Comment by tonymec** [comment]
@brammool @JanPoonthong : One problem is that even on Linux, the names of the development packages vary from one distro to the other: for instance on RedHat, Fedora, [open]SUSE etc. they have names ending in -devel while on Debian, Ubuntu etc. they have (IIUC) names ending in -dev: on my openSUSE system the development package for ncurses is called ncurses-devel; I found it by searching in the "Software Management" subsystem of YaST with the criteria "Name" "Begins with" "ncurses". On other distributions the way to find the exact name of a missing package may be different. On some distributions IIUC it is even possible to install all dependencies of a package (for instance, the Vim GUI) by means of one command typed at a shell prompt; but here too, the Vim package name may vary between distributions.

Best regards,
Tony.
