### ISSUE TITLE
gvim find/replace hot keys

### ISSUE THREAD

**Issue by davehouser1** [vim/vim#8135]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
I am not sure if this is possible but it would be great if there were some hot key for the find/replace... tool. 

**Describe the solution you'd like**
Most find/replace options I have come across use `Ctrl+h`. I am no vim pro, but when opening vim and trying to use "ctrl+h" nothing seems to happen, maybe this key combination is available? 
I would also recommend the following:
- Check box to only find/replace on selected text.
- Hot key to "Replace All" in the find/replace tool... I dont like having to hit tab a bunch to get to "Replace All" to apply submit my request.

**Describe alternatives you've considered**
I don't like having to use my mouse to go to the find and replace tool. I also dont like having to put complicated sed commands into vim with escape characters.

**Comment by chrisbra** [comment]
I think you are looking for [mswin.vim](https://github.com/vim/vim/blob/master/runtime/mswin.vim). It supports such things, although this is not the recommended Vim way of doing things. When running the windows installer, it also asks about that feature.

**Comment by chrisbra** [comment]
I am closing this.
