### ISSUE TITLE
Vim9: unexpected delayed hit-enter prompt erases message displayed with :echon and timer

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8136]
**Describe the bug**

In Vim9 script, a message displayed with `:echon` and a timer might be erased by a hit-enter prompt which is unexpectedly delayed until the next `CursorHold`.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        set showcmd ut=1000
        au CursorHold * #
        timer_start(0, (_) => {
            echon repeat('x', &columns - 11)
        })
    EOF
    )

`xxx...` is displayed which is expected.

A hit-enter prompt erases the message after 1 second.  The hit-enter prompt itself is expected.  But the fact that it's delayed *after* the message has been printed, causing the latter to be erased, is not expected.

**Expected behavior**

The hit-enter prompt occurs at the same time the message is printed.  Not afterward (on the next `CursorHold`).

**Environment**

 - Vim version: 8.2 Included patches: 1-2799
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(367)

**Additional context**

In Vim script legacy, the same issue exists:
```vim
set showcmd ut=1000
au CursorHold * "
call timer_start(0, {-> execute("echon repeat('x', &columns - 11)", '')})
```
However, using `:echo` instead of `:echon` can fix it:
```vim
set showcmd ut=1000
au CursorHold * "
call timer_start(0, {-> execute("echo repeat('x', &columns - 11)", '')})
```
OTOH, in Vim9, using `:echo` does not fix the issue:
```vim
vim9script
set showcmd ut=1000
au CursorHold * #
timer_start(0, (_) => {
    echo repeat('x', &columns - 11)
})
```
The hit-enter prompt is still delayed.

---

The issue is even worse when the message gets longer than the width of the terminal screen:
```vim
vim9script
set showcmd ut=1000
au CursorHold * #
timer_start(0, (_) => {
    echon repeat('x', &columns)
})
```
Notice that nothing is displayed at all.

In legacy, the same issue exists:
```vim
set showcmd ut=1000
au CursorHold * "
call timer_start(0, {-> execute("echon repeat('x', &columns)", '')})
```
But it can be fixed by using `:echo` instead of `:echon`:
```vim
set showcmd ut=1000
au CursorHold * "
call timer_start(0, {-> execute("echo repeat('x', &columns)", '')})
```
Which doesn't work in Vim9:
```vim
vim9script
set showcmd ut=1000
au CursorHold * #
timer_start(0, (_) => {
    echo repeat('x', &columns)
})
```
---

The issue has nothing to do with the new syntax which lets us write statements inside a lambda (as described at `:h inline-function`).  It can be reproduced with a regular function call:
```vim
vim9script
set showcmd ut=1000
au CursorHold * #
def Echo()
    echon repeat('x', &columns - 11)
enddef
timer_start(0, (_) => Echo())
```
    the hit-enter prompt is still unexpectedly delayed
```vim
vim9script
set showcmd ut=1000
au CursorHold * #
def Echo()
    echon repeat('x', &columns)
enddef
timer_start(0, (_) => Echo())
```
    the message is still unexpectedly not displayed

---

In Vim9, what's relevant is the context in which `:echo` is run.  All the rest is irrelevant.
So, if `Echo()` is re-written as a legacy function (and all the rest remains in Vim9), then we observe the same behavior as in a full legacy script:
```vim
vim9script
set showcmd ut=1000
au CursorHold * #
fu Echo()
    echo repeat('x', &columns)
endfu
timer_start(0, (_) => Echo())
```
    the message is correctly displayed because ":echon" was replaced with ":echo"

**Comment by brammool** [comment]
The autocommand is not needed.  Just output long enough text in the timer callback, then move the cursor.

**Comment by lacygoill** [comment]
The patch has improved the situation, but there is still an issue when the message gets long enough.  Often, it's not displayed at all:
```vim
set showcmd ut=1000
au CursorHold * "
call timer_start(0, {-> execute("echon repeat('x', &columns)", '')})
```
    ERROR: no visible message
```vim
vim9script
set showcmd ut=1000
au CursorHold * #
timer_start(0, (_) => {
    echo repeat('x', &columns)
})
```
    ERROR: no visible message
```vim
vim9script
set showcmd ut=1000
au CursorHold * #
timer_start(0, (_) => {
    echon repeat('x', &columns)
})
```
    ERROR: no visible message

When the message gets long enough, the only case where the timer correctly prints it, is when we use `:echo` (not `:echon`) in Vim script legacy (not in Vim9 script):
```vim
set showcmd ut=1000
au CursorHold * "
call timer_start(0, {-> execute("echo repeat('x', &columns)", '')})
```
    OK: the message is printed

**Comment by lacygoill** [comment]
And yes, you were right about the autocmd; it's not needed.  So, here are the same snippets without any autocmd:
```vim
call timer_start(0, {-> execute("echon repeat('x', &columns)", '')})
```
    ERROR: no visible message
```vim
vim9script
timer_start(0, (_) => {
    echo repeat('x', &columns)
})
```
    ERROR: no visible message
```vim
vim9script
timer_start(0, (_) => {
    echon repeat('x', &columns)
})
```
    ERROR: no visible message
```vim
call timer_start(0, {-> execute("echo repeat('x', &columns)", '')})
```
    OK: the message is printed

I think the message should be printed in all 4 cases; not just in the last one.

**Comment by lacygoill** [comment]
> I think the message should be printed in all 4 cases; not just in the last one.

Actually, I wonder whether it's the other way around.  Maybe the first 3 snippets are correct, but not the last one.  I seem to remember reading somewhere that a timer should not be able to print a multiline message ([maybe here](https://github.com/vim/vim/issues/836#issuecomment-221404233)).

**Comment by brammool** [comment]
> The patch has improved the situation, but there is still an issue when
> the message gets long enough.  Often, it's not displayed at all:
> ```vim
> set showcmd ut=1000
> au CursorHold * "
> call timer_start(0, {-> execute("echon repeat('x', &columns)", '')})
> ```
>     ERROR: no visible message

Actually, the message is displayed.  But then the ruler is displayed and
the message is overwritten.  You can see the text if you set
'writedelay'.  That's not useful though.  It stays if you set
'cmdheight' to 2 or more.

It also shows if you disable 'ruler' and don't overwrite the very last
character:

set cmdheight=1 noruler
call timer_start(0, {-> execute("echon repeat('x', &columns - 1)", '')})


-- 
hundred-and-one symptoms of being an internet addict:
165. You have a web page burned into your glasses

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
It still seems inconsistent for the message to be erased when using the new inline function syntax, but not when using `execute()`:
```vim
vim9script
timer_start(0, (_) => {
    echo repeat('x', &columns)
})
```
    the message is erased
```vim
vim9script
timer_start(0, (_) => execute("echo repeat('x', &columns)", ''))
```
    the message is NOT erased

**Comment by brammool** [comment]
This is because of using execute(), it executes the command in a different way, and also grabs the output.
When I try this I get the hit-enter prompt.  Whether you want that depends on what the message is about.
So it's actually useful to be able to choose how it's done.
