### ISSUE TITLE
Vim9: cannot evaluate output of script-local function using pseudo-key "<SNR>"

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8137]
**Describe the bug**

In Vim9 script, we cannot evaluate the output of a script-local function using the pseudo-key `<SNR>`.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func(): string
            return 'value'
        enddef
        echo <SNR>1_Func()
    EOF
    )

`E1010` is raised:

    E1010: Type not recognized: SNR>1_Func()

**Expected behavior**

No error is raised.  `value` is echo'ed.

**Environment**

 - Vim version: 8.2 Included patches: 1-2799
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(367)

**Additional context**

Regression introduced in [8.2.2799](https://github.com/vim/vim/releases/tag/v8.2.2799).

---

One could argue that `<SNR>` is not needed here.  That's true, but it can be necessary when we try to evaluate a script-local function from a different script.  That's what I do [here](https://github.com/lacygoill/vim-repmap/blob/4194f6a143e1d32d01c451866de78887fc8da841/autoload/repmap/make.vim#L387).

**Comment by brammool** [comment]
This is not supposed to work.  If you want to use that function elsewhere you can export it and import it in the other script.

**Comment by lacygoill** [comment]
> If you want to use that function elsewhere you can export it and import it in the other script.

I cannot do this.  The purpose of my plugin is to make a mapping repeatable by pressing the semicolon key or the comma key.  In the rhs of a mapping, `<SNR>` can appear in front of a function name, and I need to evaluate that function.  I cannot import the function for every single mapping I'm trying to make repeatable.  In fact, it could be used by someone else (it just provides functions which can be used to make arbitrary mappings repeatable); in which case, there's no way for the plugin to import the function.

> This is not supposed to work

My plugin has worked fine for several years, in Vim script legacy, and in Vim9 until the patch 8.2.2799.  Now, it raises the error `E1010` whenever I press `;` or `,` to repeat a mapping whose rhs invokes a script-local function.

**Comment by lacygoill** [comment]
Never mind, I fixed my issue by turning the script-local function which was invoked in the mapping that I'm making repeatable into an autoloaded function.  No `<SNR>` anymore.

It still means that my plugin will fail to make a mapping invoking a script-local function repeatable, but only if it uses `<expr>`, so that should be a rare issue.

**Comment by lacygoill** [comment]
> Never mind, I fixed my issue by turning the script-local function which was invoked in the mapping that I'm making repeatable into an autoloaded function. No <SNR> anymore.

[I found a reliable fix](https://github.com/lacygoill/vim-repmap/commit/c19caea91423a48b7ccb8653afe89a82830c8057).  Install a legacy `Eval()` function, and eval the expression inside the latter.

**Comment by brammool** [comment]
I'm not sure what you are doing, but something like this should work:
```vim
vim9script
def GetChar(): string
  return 'l'
enddef
inoremap <expr> ; <SID>GetChar()
```

**Comment by lacygoill** [comment]
> I'm not sure what you are doing, but something like this should work:

Basically, my plugin provides a "library" function: `repmap#make#repeatable()` .  You pass it some information about a list of keys that you use in the lhs of mappings, and the function should make them repeatable with `;` or `,`:

    repmap#make#repeatable({
        mode: 'n',
        buffer: false,
        motions: [
            {bwd: '<q', fwd: '>q'},
            {bwd: '[q', fwd: ']q'},
            {bwd: 'g,', fwd: 'g;'},
        ]})

It does so by saving the original rhs in a database, and installing wrapper mappings around the original mappings.  The latter could be installed anywhere; the plugin has no idea in advance from which script the original mappings could be installed.

The issue is when the original mapping uses the `<expr>` argument and the rhs is a script-local function:

    nno <expr> abc <sid>Func()

My library function turns this mapping into:

    nno <expr> abc <SNR>456_Move('abc', '<SNR>123_Func()')
                   ├───────────┘         ├───────────┘
                   │                     └ original function
                   └ wrapper function

The idea is that after pressing `abc` – a 3-char command – you can repeat the mapping by just pressing `;` (a 1-char command).

When you press `abc` the first time (and when you press `;` or `,` afterward), the wrapper mapping has to emulate the original mapping.  It does so by inspecting the database, retrieving the original rhs and evaluating it.  Now, that fails if the rhs is an expression starting with `<SNR>`.

But, I've realised that my code made a mistake anyway.  The patch 8.2.2799 didn't break anything; it just revealed the mistake.  The rhs of a mapping is evaluated in the legacy context by default.  So, my wrapper mapping should not evaluate it in the Vim9 context.  To be totally reliable, it really needs an ad-hoc legacy function:
```vim
vim9script
nno <expr> <F3> {-> 'no error'}()
echo maparg('<F3>')->eval()
```
    E720: Missing colon in Dictionary: > 'no error'}()
    E15: Invalid expression: {-> 'no error'}()
```vim
vim9script
nno <expr> <F3> {-> 'no error'}()
fu Legacy()
    echo maparg('<F3>')->eval()
endfu
Legacy()
```
    no error

However, it's not the first time that I need to install a legacy function just for a command.  Maybe we need a `:legacy` command modifier, similar to the `:vim9` one.  It's probably rarely needed; I only have 3 commands in all my config where I need this.  Still, it would be handy.  As an example, it could be used this way:
```vim
vim9script
nno <expr> <F3> {-> 'no error'}()
legacy echo maparg('<F3>')->eval()
```
    no error

**Comment by brammool** [comment]
> However, it's not the first time that I need to install a legacy
> function just for a command.  Maybe we need a `:legacy` command
> modifier, similar to the `:vim9` one.  It's probably rarely needed; I
> only have 3 commands in all my config where I need this.  Still, it
> would be handy.  As an example, it could be used this way:
> ```vim
> vim9script
> nno <expr> <F3> {-> 'no error'}()
> legacy echo maparg('<F3>')->eval()
> ```
>     no error

I'm not sure how useful a :legacy modifier is, but it's symmetric with
:vim9cmd, so we might as well add it.

-- 
"Hit any key to continue" is very confusing when you have two keyboards.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
It doesn't seem to work as expected when calling an autoload function:
```vim
vim9script
set rtp=/tmp/some
mkdir('/tmp/some/autoload', 'p')
var lines =<< trim END
    vim9script
    def script#func()
        echo (() => 'no error')()
    enddef
END
writefile(lines, '/tmp/some/autoload/script.vim')
legacy call script#func()
```
    E1015: Name expected: ) => 'no error')()

The issue disappears if `:legacy` is replaced by a legacy function:
```vim
vim9script
set rtp=/tmp/some
mkdir('/tmp/some/autoload', 'p')
var lines =<< trim END
    vim9script
    def script#func()
        echo (() => 'no error')()
    enddef
END
writefile(lines, '/tmp/some/autoload/script.vim')
fu Func()
    call script#func()
endfu
Func()
```
    no error

This seems inconsistent.

The issue also disappears if we execute `:defcompile` to make sure the autoload function is compiled earlier:
```vim
vim9script
set rtp=/tmp/some
mkdir('/tmp/some/autoload', 'p')
var lines =<< trim END
    vim9script
    def script#func()
        echo (() => 'no error')()
    enddef
    defcompile
END
writefile(lines, '/tmp/some/autoload/script.vim')
legacy call script#func()
```
    no error

**Comment by lacygoill** [comment]
> It doesn't seem to work as expected when calling an autoload function:

In case the example looks too contrived, I found this in some "real" code:

    legacy eval foldlevel(1)

The purpose of `foldlevel(1)` is to make Vim recompute the folding level of all the lines in the current buffer.  And the purpose of `:legacy` is to suppress spurious errors if the folding expression is written in a legacy script and does not include whitespace around some binary operators (this is frequently the case because of `:h option-backslash`).

If it turns out that the folding expression is a Vim9 autoload function, then an unexpected error is raised, similar as the one previously posted.
