### ISSUE TITLE
Ctrl-] in help buffers gets confused by punctuation

### ISSUE THREAD

**Issue by mgedmin** [vim/vim#814]
1. `:help :copy` shows this text:

```
:[range]co[py] {address}                *:co* *:copy*
            Copy the lines given by [range] to below the line
            given by {address}.
```
1. Position the cursor on top of `{address}`
2. Press Ctrl-]

Expected behavior:
- you're looking at the help topic for `{address}`

Actual behavior:
- `E149: Sorry, no help for {address}.`

**Comment by vim-ml** [comment]
Hi Marius,

2016-5-18(Wed) 16:07:50 UTC+9 Marius Gedminas:

> :help :copy shows this text:
> 
> :[range]co[py] {address}                _:co_ _:copy_
>             Copy the lines given by [range] to below the line
>             given by {address}.
> 
> Position the cursor on top of {address}
> 
> Press Ctrl-]
> 
> Expected behavior:
> 
> you're looking at the help topic for {address}
> 
> Actual behavior:
> 
> E149: Sorry, no help for {address}.

I can't reproduce.  (I got your expected behavior)
My Vim is 7.4.1831 on fedora 23.

What your Vim version?

Please retry after execute the following command in Vim.
:helptags ALL

## 

Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by mgedmin** [comment]
I'm on vim 7.4.1831.  I can reproduce with `vim -u NONE`, so it's not my .vimrc playing with &iskeyword or anything.

**Comment by vim-ml** [comment]
Hi Marius,

2016-5-18(Wed) 16:52:50 UTC+9 Marius Gedminas:

> I'm on vim 7.4.1831.  I can reproduce with vim -u NONE, so it's not my .vimrc playing with &iskeyword or anything.

Yes, I also ran same command and can't reproduce.
You've done below in vim directory?

$ sudo make install

## 

Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by mgedmin** [comment]
No, I've done `make`, and then I run vim with a wrapper script that sets`VIMRUNTIME=~/src/vim/runtime` and exec's ~/src/vim/src/vim.

But I can also reproduce with /usr/bin/vim, which is version 7.4.1689 from Ubuntu 16.04 vim-gnome-py2.

What else could be different between our systems?  Locale?  I can still reproduce after setting LC_ALL=C.

**Comment by vim-ml** [comment]
2016-05-18 14:06 GMT+03:00 Marius Gedminas vim-dev-github@256bit.org:

> No, I've done make, and then I run vim with a wrapper script that sets
> VIMRUNTIME=~/src/vim/runtime and exec's ~/src/vim/src/vim.
> 
> But I can also reproduce with /usr/bin/vim, which is version 7.4.1689 from
> Ubuntu 16.04 vim-gnome-py2.
> 
> What else could be different between our systems? Locale? I can still
> reproduce after setting LC_ALL=C.

In the text you quoted {address} is present _twice_: once with and once
without dot. Given your error message I think you used the second one with
dot, but besides that you have not stated explicitly which ​{address} you
meant and if I did not see the error message or did not knew that error
messages usually do not end with a dot I would never think you meant the
second one.

It is reproducible here on the second {address}.

**Comment by vim-ml** [comment]
Hi Bram and All,

2016-5-19(Thu) 0:05:03 UTC+9 ZyX:

> 2016-05-18 14:06 GMT+03:00 Marius Gedminas vim-dev...@256bit.org:
> 
> No, I've done make, and then I run vim with a wrapper script that setsVIMRUNTIME=~/src/vim/runtime and exec's ~/src/vim/src/vim.
> 
> But I can also reproduce with /usr/bin/vim, which is version 7.4.1689 from Ubuntu 16.04 vim-gnome-py2.
> 
> What else could be different between our systems?  Locale?  I can still reproduce after setting LC_ALL=C.
> 
> In the text you quoted {address} is present _twice_: once with and once without dot. Given your error message I think you used the second one with dot, but besides that you have not stated explicitly which ​{address} you meant and if I did not see the error message or did not knew that error messages usually do not end with a dot I would never think you meant the second one.
> 
> It is reproducible here on the second {address}.

Ah, nice catch up.  Thanks.

Bram>
I wrote a patch that improve :help for curly bracket.

## Please check and include an attached patch.

Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by mgedmin** [comment]
Oh dear.  I read the paragraph of text very carefully to make sure there was only one `{address}` in it, and completely managed to overlook the second one on the heading line.  _headdesk_

Sorry!

**Comment by vim-ml** [comment]
Hirohito Higashi wrote:

> Hi Bram and All,
> 
> 2016-5-19(Thu) 0:05:03 UTC+9 ZyX:
> 
> > 2016-05-18 14:06 GMT+03:00 Marius Gedminas vim-dev...@256bit.org:
> > 
> > No, I've done make, and then I run vim with a wrapper script that setsVIMRUNTIME=~/src/vim/runtime and exec's ~/src/vim/src/vim.
> > 
> > But I can also reproduce with /usr/bin/vim, which is version 7.4.1689 from Ubuntu 16.04 vim-gnome-py2.
> > 
> > What else could be different between our systems?  Locale?  I can still reproduce after setting LC_ALL=C.
> > 
> > In the text you quoted {address} is present _twice_: once with and once without dot. Given your error message I think you used the second one with dot, but besides that you have not stated explicitly which ​{address} you meant and if I did not see the error message or did not knew that error messages usually do not end with a dot I would never think you meant the second one.
> > 
> > It is reproducible here on the second {address}.
> 
> Ah, nice catch up.  Thanks.
> 
> Bram>
> I wrote a patch that improve :help for curly bracket.
> Please check and include an attached patch.

Thanks.

## 

```
        |
```

Ceci n'est pas une pipe.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///
