### ISSUE TITLE
Description of variable v:fname missing in eval.txt

### ISSUE THREAD

**Issue by Hans-Guenter** [vim/vim#8141]
The description of the variables in **eval.txt** lacks an entry for **v:fname** which is being used by the **includeexpr** option.

**Comment by brammool** [comment]
Hans-Guenter wrote:

> The description of the variables in **eval.txt** lacks an entry for
> **v:fname** which is being used by the **includeexpr** option.

Indeed.  I'll add an entry.

-- 
hundred-and-one symptoms of being an internet addict:
150. You find yourself counting emoticons to get to sleep.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
Fixed by https://github.com/vim/vim/commit/4c295027a426986566cd7a76c47a6d3a529727e7

The help now includes a help tag for `v:fname` which says:

>                                         *v:fname* *fname-variable*
> v:fname         The file name set by 'includeexpr'.  Empty otherwise.

**Comment by obcat** [comment]
I think current description is a bit wrong.
I'm not sure, but this seems to be more correct IMO: 

```diff
diff --git a/runtime/doc/eval.txt b/runtime/doc/eval.txt
index 7fb253453..830db1453 100644
--- a/runtime/doc/eval.txt
+++ b/runtime/doc/eval.txt
@@ -1963,7 +1963,8 @@ v:fcs_choice	What should happen after a |FileChangedShell| event was
 		Vim behaves like it is empty, there is no warning message.
 
 					*v:fname* *fname-variable*
-v:fname		The file name set by 'includeexpr'.  Empty otherwise.
+v:fname		The file name set by 'include', |gf|, or |<cfile>|.  Only
+		valid while evaluating the 'includeexpr' option.
 
 					*v:fname_in* *fname_in-variable*
 v:fname_in	The name of the input file.  Valid while evaluating:
```

**Comment by brammool** [comment]
> I think current description is a bit wrong.
> I'm not sure, but this seems to be more correct IMO: 

The "set by" is not correct.  Mentioning the commands that use
'includeexpr' isn't really needed here.  This should be better:

v:fname		When evaluating 'includeexpr': the file name that was
		detected.  Empty otherwise.


-- 
I got a new desk stapler. It broke on the first desk I tried.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by obcat** [comment]
Ah right, that looks better to me.
Maybe this change should be includes in the next "update runtime files".
Thank you:)
