### ISSUE TITLE
Cursor flickering in insert mode with vim-airline enabled

### ISSUE THREAD

**Issue by zakutin** [vim/vim#8144]
**Describe the bug**
The cursor is flickering on moving by arrow keys in Insert mode. It shortly appears in the beginning of the line. In Normal mode everything is fine. It happens only when vim-airline is plugged. The issue was already posted [here](https://github.com/vim-airline/vim-airline/issues/2367).

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Plug vim-airline with following settings
```
call plug#begin()
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
call plug#end()

let g:airline_powerline_fonts = 1
let g:airline_theme = 'minimalist'
let g:airline#extensions#tabline#enabled = 1

```
2. enable insert mode in vim
3. move cursor, it is flickering

**Expected behavior**
The cursor shall not flicker on moving.

**Screenshots**

https://user-images.githubusercontent.com/53969222/116134261-fc85cb80-a6cf-11eb-949f-f10aff2e3c3b.mp4

**Environment (please complete the following information):**
 - Vim version 8.2.2648
 - OS: Microsoft Windows 10 Pro, Version 10.0.19042 Build 19042
 - Terminal: Windows Terminal, Version: 1.7.1033.0

**Additional context**
- vim-airline: 0.11

**Comment by zakutin** [comment]
The same happens with lightline.vim plugin and `set laststatus=2` enabled.

**Comment by chrisbra** [comment]
Try to provide a minimal reproducible example (preferably without having to install a plugin, so set the statusline manually to some values), which allows to reproduce using e.g. `vim --clean`. Also it may help to set 'writedelay'  to see when a redraw is happening.

**Comment by zakutin** [comment]
I tried to launch `vim --clean` — no flickering in "Insert mode". I entered `set laststatus=2` — no flickering and then `set statusline=test` — flickering returned back. With `set writedelay=500` I noticed that when I move the cursor from line to line, it goes successively through all symbols from the beginning of the line. But when I press and hold the arrow, it flickers as before.


https://user-images.githubusercontent.com/53969222/116246810-95692500-a76a-11eb-9e40-6c0671b62581.mp4

**Comment by brammool** [comment]
> I tried to launch `vim --clean` — no flickering in "Insert mode". Then
> I entered `set laststatus=2` and `set statusline=test` — flickering
> returned back. With `set writedelay=500` I noticed that when I move
> the cursor from line to line, it goes successively through all symbols
> from the beginning of the line. But when I press and hold the arrow,
> it flickers as before.

I remembered that after patch 8.2.2803 the status line was still
flickering.  I'm sending out a patch now to fix that.

Is the cursor flickering also solved by that?
If not, can you check if the reproduction script on issue 8131 helps to
reproduce this problem?

-- 
hundred-and-one symptoms of being an internet addict:
182. You may not know what is happening in the world, but you know
     every bit of net-gossip there is.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by zakutin** [comment]
> I remembered that after patch 8.2.2803 the status line was still
flickering.  I'm sending out a patch now to fix that. 
Is the cursor flickering also solved by that?

Sorry, Bram.. I probably have to compile it, honestly, I have no idea how to make it :(

> If not, can you check if the reproduction script on issue 8131 helps to
reproduce this problem?

Will try.
