### ISSUE TITLE
syntaxcomplete ignores buffer-local ignorecase setting

### ISSUE THREAD

**Issue by mg979** [vim/vim#8153]
Here the setting is read:
https://github.com/vim/vim/blob/b98cec28d95b2184c64a0646458c1e62deb2524b/runtime/autoload/syntaxcomplete.vim#L150-L156

But then when it should be used, it reads it from the global variable:
https://github.com/vim/vim/blob/b98cec28d95b2184c64a0646458c1e62deb2524b/runtime/autoload/syntaxcomplete.vim#L201-L209

Note that in the commented part just above it uses `b:` but then in the real code it uses `g:`.

**Comment by chrisbra** [comment]
ping @dfishburn

**Comment by dfishburn** [comment]
Thanks for the bug report, I will address it.

**Comment by dfishburn** [comment]
I did quite a bit of testing on this, but if you could give it a quick run through before I upload it that would be good.
The [upload ](https://filebin.net/4bmj1v07tgvpoaf3) will expire 20200503.

**Comment by mg979** [comment]
For my use case I can confirm it works now.

**Comment by chrisbra** [comment]
let me close this and I let David handle sending a new file to Bram for inclusion :)

**Comment by mg979** [comment]
@dfishburn thanks for the fix by the way.
