### ISSUE TITLE
Clarify "word" character class in 'isk' documentation.

### ISSUE THREAD

**Issue by habamax** [vim/vim#8155]
If you do `:h 'iskeyword'` there will be a phrase:

```
For '@' characters above 255 check the "word" character class.
```

The question is what is this "word" character class?

Currently if I have `привет мир` unicode text in a buffer, I can match a letter with `/\k` but not with a `/\w` which I thought is the "word" character class...

**Comment by brammool** [comment]
> If you do `:h 'iskeyword'` there will be a phrase:
> 
> ```
> For '@' characters above 255 check the "word" character class.
> ```
> 
> The question is what is this "word" character class?
> 
> Currently if I have `привет мир` unicode text in a buffer, I can match
> a letter with `/\k` but not with a `/\w` which I thought is the "word"
> character class...

Hmm, I don't think this is clearly specified in the help.  The \< and \>
regexp items mention start and end of word, which does use a similar
rule.

Best I can think of is "any character that is not white space or punctuation".

-- 
hundred-and-one symptoms of being an internet addict:
187. You promise yourself that you'll only stay online for another
     15 minutes...at least once every hour.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
Possibly fixed by https://github.com/vim/vim/commit/4c295027a426986566cd7a76c47a6d3a529727e7

The help at `:h 'isk'` now says:

   > For '@' characters above 255 check the "word" character class (any character
   > that is not white space or punctuation).

**Comment by habamax** [comment]
Yes, thank you.

I am still a bit confused by a `"word" character class` mention there as it doesn't match to what is defined for a regex word character class. Or maybe quotes in "word" means it is different?

**Comment by lacygoill** [comment]
I don't know.  Maybe "word" character class refers to `[[:keyword:]]`?  If so, the definition might be circular, because the latter is already defined via `'iskeyword'`.

Maybe we could say this instead:

   > '@' characters above 255 match [^[:space:][:punct:]] (any character
   > that is not white space or punctuation).
```diff
diff --git a/runtime/doc/options.txt b/runtime/doc/options.txt
index 84969b23f..0ed431e9a 100644
--- a/runtime/doc/options.txt
+++ b/runtime/doc/options.txt
@@ -4563,9 +4563,9 @@ A jump table for the options with a short description can be found at |Q_op|.
 			local to buffer
 	Keywords are used in searching and recognizing with many commands:
 	"w", "*", "[i", etc.  It is also used for "\k" in a |pattern|.  See
-	'isfname' for a description of the format of this option.  For '@'
-	characters above 255 check the "word" character class (any character
-	that is not white space or punctuation).
+	'isfname' for a description of the format of this option.  '@'
+	characters above 255 match `[^[:space:][:punct:]]` (any character that
+	is not white space or punctuation).
 	For C programs you could use "a-z,A-Z,48-57,_,.,-,>".
 	For a help file it is set to all non-blank printable characters except
 	'*', '"' and '|' (so that CTRL-] on a command finds the help for that
```
