### ISSUE TITLE
pasting into a vim window switches from command mode to insert mode

### ISSUE THREAD

**Issue by neobrk** [vim/vim#8157]
It used to be possible (e.g., in vim 7.4.909) to leave vim in command mode (rather than insert mode) and then paste some copied characters into the vim window to make it execute the characters as a sequence of commands. This was a very useful behavior.

E.g., you could copy the characters "n0dt@" and then when you pasted them in with a right-click, it would search for the next item you last searched for ("n"), go to the beginning of that line ("0"), and delete everything up to the first "@" character in that line ("dt@"). Then you could right-click again and it would do it again on the next item, etc.

Now (at least since vim 8.0.1365) when I paste into the vim window, it somehow detects that I'm pasting rather than typing, and it "helpfully" switches into insert mode (for the duration of the paste) and just inserts the literal characters "n0dt@", which of course isn't what I want.

(Is there some option now or some other workaround that would turn off this automatic switch to insert mode when pasting or revert to the old behavior, to allow vim commands to be pasted in?)

This happens on multiple platforms, so it's definitely a vim issue, not a platform/terminal emulator/shell issue.

**Comment by brammool** [comment]
This is most likely caused by bracketed paste.  The idea is that one could accidentally paste something that wasn't supposed to be executed and cause arbitrary commands to be executed.  Thus it's a feature.  Try disabling it with:
```vim
set t_BE=
```

**Comment by neobrk** [comment]
Thank you, that fixes it!
