### ISSUE TITLE
job_stop will not actually stop the process in windows unless I unlet the job variable (gvim 7.4.1832)

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#816]
step to reproduct (windows gvim 7.4.1832):
1. start a background python job (output a single line and sleep 1 second, repeat 30 times)
2. redirect stdout/stderr into quickfix window by 'callback'
3. call job_stop with 'term' or 'kill' and *\* DO NOT unlet job object **
4. check job_status and it changed from 'run' to 'dead'
5. ERROR: but the job is still running, still output text to quickfix window
6. when it actually exit by it self (after repeat itself 30 times) 'close_cb' and 'exit_cb' were invoked

and if I unlet job object after job_stop, everything seems okay, the job can actually be stopped but job object can not be unleted after job_stop, because sometimes child process will stop signal from being terminated (ignore TERM etc) in this circumstance, if I immediately unlet job object after
a no-effect job_stop calling my script will fail into an error environment.

This is only in windows, in linux everything is fine, I can clean the job object in exit_cb/close_cb as my wish. and job_stop doesn't require a unlet in linux too.

**Comment by vim-ml** [comment]
sorry,I don't know issues in github will be redirect to this group.

**Comment by chrisbra** [comment]
There have been many patches regarding job feature. So is this still happening?

**Comment by skywind3000** [comment]
I will try it as soon as I get to my laptop.

**Comment by skywind3000** [comment]
wrote a script to verify:

``` VimL
function! JobCallback(channel, text)
    caddexpr a:text
    cbottom
endfunc

function! JobExit(job, message)
    caddexpr "[Job finished]"
    cbottom
endfunc

function! TimerKill(tid)
    caddexpr "--> try to terminate"
    cbottom
    call job_stop(g:myjob, 'kill')
    call job_status(g:myjob)
endfunc

cexpr "[Job start]"
botright copen 10
wincmd k

let statements = "import sys,time; [("
let statements = statements . "sys.stdout.write('%d\\n'%i),sys.stdout.flush(),"
let statements = statements . "time.sleep(1)) for i in xrange(30)]"

cexpr "[python -c \"".statements."\"]"
let opts = { "callback": "JobCallback", "exit_cb": "JobExit" }

let g:myjob = job_start(["python", "-c", statements], opts)
let g:mytimer = timer_start(5000, "TimerKill", {"repeat": 1})

```

And it seems that `job_stop` can work correctly on windows now. (vim 7.4.2078)

**Comment by vim-ml** [comment]
On Do, 21 Jul 2016, Linwei wrote:

> wrote a script to verify:
> 
> ``` VimL
> function! JobCallback(channel, text)
>   caddexpr a:text
>   cbottom
> endfunc
> 
> function! JobExit(job, message)
>   caddexpr "[Job finished]"
>   cbottom
> endfunc
> 
> function! TimerKill(tid)
>   caddexpr "--> try to terminate"
>   cbottom
>   call job_stop(g:myjob, 'kill')
>   call job_status(g:myjob)
> endfunc
> 
> cexpr "[Job start]"
> botright copen 10
> wincmd k
> 
> let statements = "import sys,time; [("
> let statements = statements . "sys.stdout.write('%d\\n'%i),sys.stdout.flush(),"
> let statements = statements . "time.sleep(1)) for i in xrange(30)]"
> 
> cexpr "[python -c \"".statements."\"]"
> let opts = { "callback": "JobCallback", "exit_cb": "JobExit" }
> 
> let g:myjob = job_start(["python", "-c", statements], opts)
> let g:mytimer = timer_start(5000, "TimerKill", {"repeat": 1})
> 
> ```
> 
> And it seems that `job_stop` can work correctly on windows now. (vim 7.4.2078)

I don't know that part of the code enough, but I wonder, if this could 
be added as a test?

Best,

## Christian

Wenn du nicht kommst, schmeiß ich dich raus.

**Comment by skywind3000** [comment]
alright, I'll learn to write a test
