### ISSUE TITLE
iabbrev not working properly with some symbols like ellipsis "…"

### ISSUE THREAD

**Issue by ewen-goisot** [vim/vim#8160]
When I create an abbreviation for insert mode, let's say `:iab foo bar`, it works correctly too if I type `foo.` or `foo,` or `foo)` or `foo` followed by almost any Unicode character. But for some (rare) cases, I get another result :
`foo…` (with ellipsis, aka `U2026`), it actually writes just `bar` and "wait" for another key : after that,
it usually gives me a `barâ` (last char is a `a` with circumflex accent : `Ue2`),
but the result depends on the next key I will press, so, I made several tests :
- if I press the <Space> key twice : `foo…<Space><Space>`, I get `barâ` (with no space).
- if I press the <Esc> key twice, the result is the same (and it does not leave the insert mode).
- `foo…<Left>` gives me `barâD`.
- `foo…<Right>` gives me `barâC`.
- `foo……` gives me `bar ¦` (the two last chars are `U2000` (not a true space) and `Ua6`).
- `foo…½` (last char is `Ubd`) gives me `foo‽` (last char is `U203d`).
- `foo…⸮` (last char is `U2e2e`) gives me `foo‸®` (the two las chars are `U2038` and `Uae`).

Some other symbols have the same behavior (putting a `â` or other unexpected chars).
It includes : `U2025` (`‥`, can be done with `<c-k>..`), `U2020` (`†`), `U201d` (`”`, can be done with `<c-k>9"`), `U2028`
and probably other with similar Unicode values. 

note: to reproduce it, if you don't have the ellipsis in your keyboard layout, it can be done with `<c-k>.,` in Vim.
I get the same issue with `foo…` and `foo<c-k>.,`, but I get different issues with `foo……` and `foo<c-k>.,<c-k>.,`.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean`.
2. Type `:`, then run the command `iab foo bar`.
3. Go to insert mode, and type `foo…<Space><Space>`, or `foo<c-k>.,<Space><Space>`.
4. You will see the text `barâ`.

**Expected behavior**
Typing `foo…` will print `bar…`, or at least it will stay `foo…` and not add an additional `â`.

**Environment :**
 - Vim version: 8.1
 - OS: Ubuntu 20.04
 - Terminal: GNOME Terminal
 
note : I tested with several keyboard layout, including Azerty and Bépo,
with several terminal emulators (also tried with ST), with both Vim and NeoVim, and with 2 different Ubuntu versions,
so I'm not sure it's related to this. The issue is also the same with other words than `foo` and `bar`.
On every test I made, pressing twice `<Space>` will either give me `â` (and not another char) + expand the abbreviation,
or just expand the abbreviation + add spaces.

**Comment by brammool** [comment]
How do you type that ellipsis character?

**Comment by Jonta** [comment]
Same OS and terminal, Norwegian QWERTY, Nvim v.0.4.3. Same result

Pressing AltGr(aph) + `.` (full stop)

xev-output of pressing this:
```
KeyRelease event, serial 34, synthetic NO, window 0x6000001,
    root 0x135, subw 0x0, time 547261870, (120,694), root:(764,733),
    state 0x0, keycode 65 (keysym 0x20, space), same_screen YES,
    XLookupString gives 1 bytes: (20) " "
    XFilterEvent returns: False

KeyPress event, serial 34, synthetic NO, window 0x6000001,
    root 0x135, subw 0x0, time 547262798, (120,694), root:(764,733),
    state 0x0, keycode 108 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
    XKeysymToKeycode returns keycode: 92
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 34, synthetic NO, window 0x6000001,
    root 0x135, subw 0x0, time 547263062, (120,694), root:(764,733),
    state 0x80, keycode 60 (keysym 0xaae, ellipsis), same_screen YES,
    XLookupString gives 3 bytes: (e2 80 a6) "…"
    XmbLookupString gives 3 bytes: (e2 80 a6) "…"
    XFilterEvent returns: False

KeyRelease event, serial 34, synthetic NO, window 0x6000001,
    root 0x135, subw 0x0, time 547263174, (120,694), root:(764,733),
    state 0x80, keycode 60 (keysym 0xaae, ellipsis), same_screen YES,
    XLookupString gives 3 bytes: (e2 80 a6) "…"
    XFilterEvent returns: False

KeyRelease event, serial 34, synthetic NO, window 0x6000001,
    root 0x135, subw 0x0, time 547263326, (120,694), root:(764,733),
    state 0x80, keycode 108 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
    XKeysymToKeycode returns keycode: 92
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 34, synthetic NO, window 0x6000001,
    root 0x135, subw 0x0, time 547264150, (120,694), root:(764,733),
    state 0x0, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 34, synthetic NO, window 0x6000001,
    root 0x135, subw 0x0, time 547264190, (120,694), root:(764,733),
    state 0x4, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 34, synthetic NO, window 0x6000001,
    root 0x135, subw 0x0, time 547264606, (120,694), root:(764,733),
    state 0x5, keycode 24 (keysym 0x51, Q), same_screen YES,
    XLookupString gives 1 bytes: (11) ""
    XmbLookupString gives 1 bytes: (11) ""
    XFilterEvent returns: False

KeyRelease event, serial 34, synthetic NO, window 0x6000001,
    root 0x135, subw 0x0, time 547264702, (120,694), root:(764,733),
    state 0x5, keycode 24 (keysym 0x51, Q), same_screen YES,
    XLookupString gives 1 bytes: (11) ""
    XFilterEvent returns: False

KeyRelease event, serial 34, synthetic NO, window 0x6000001,
    root 0x135, subw 0x0, time 547264806, (120,694), root:(764,733),
    state 0x5, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 34, synthetic NO, window 0x6000001,
    root 0x135, subw 0x0, time 547264830, (120,694), root:(764,733),
    state 0x4, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 34, synthetic NO, window 0x6000001,
    root 0x135, subw 0x0, time 547265598, (120,694), root:(764,733),
    state 0x0, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 34, synthetic NO, window 0x6000001,
    root 0x135, subw 0x0, time 547265614, (120,694), root:(764,733),
    state 0x4, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 34, synthetic NO, window 0x6000001,
    root 0x135, subw 0x0, time 547265910, (120,694), root:(764,733),
    state 0x5, keycode 25 (keysym 0x57, W), same_screen YES,
    XLookupString gives 1 bytes: (17) ""
    XmbLookupString gives 1 bytes: (17) ""
    XFilterEvent returns: False

KeyRelease event, serial 34, synthetic NO, window 0x6000001,
    root 0x135, subw 0x0, time 547266014, (120,694), root:(764,733),
    state 0x5, keycode 25 (keysym 0x57, W), same_screen YES,
    XLookupString gives 1 bytes: (17) ""
    XFilterEvent returns: False

MotionNotify event, serial 34, synthetic NO, window 0x6000001,
    root 0x135, subw 0x0, time 547266081, (121,693), root:(765,732),
    state 0x5, is_hint 0, same_screen YES

KeyRelease event, serial 34, synthetic NO, window 0x6000001,
    root 0x135, subw 0x0, time 547266094, (121,693), root:(765,732),
    state 0x5, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 34, synthetic NO, window 0x6000001,
    root 0x135, subw 0x0, time 547266110, (121,693), root:(765,732),
    state 0x4, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

**Comment by ewen-goisot** [comment]
@brammool 
> How do you type that ellipsis character?

I assume you have the `k`, `.` and `,` symbols (else, you just can't code or write in English).
Does the `<c-k>.,` (`<c-k>` means `Control + k`, it's an usual notation for Vim) works for you ?
It means : press `Control + k` (then, release it), then press the dot `.` (then, release it), then press the comma `,` (then, release it). It should be done in Insert mode… but you can get the same issue with `cab` instead of `iab` in command mode.

Read `:help digraph` for more infos about typing special symbols.

BTW, you can also type it with `<c-v>u2026`, but you can't reproduce this issue with this method.
`<c-v>` is a way to avoid abbreviations expanding in some cases.

You may also have it or not, depending on your keyboard layout.

**Comment by brammool** [comment]
> @brammool 
> > How do you type that ellipsis character?
> 
> I assume you have the `k`, `.` and `,` symbols (else, you just can't
> code or write in English).  Does the `<c-k>.,` (`<c-k>` means `Control
> + k`, it's an usual notation for Vim) works for you ?  It means :
> press `Control + k` (then, release it), then press the comma `,`
> (then, release it), then press the dot `.` (then, release it). It
> should be done in Insert mode… but you can get the same issue with
> `cab` instead of `iab` in command mode.
> 
> Read `:help digraph` for more infos about typing special symbols.
> 
> BTW, you can also type it with `<c-v>u2026`, but you can't reproduce
> this issue with this method.
> `<c-v>` is a way to avoid abbreviations expanding in some cases.
> 
> You may also have it or not, depending on your keyboard layout.

Ah, using a digraph also triggers the problem.

Anyway, I found that using Ctrl-Shift-u 2026 <Enter> also inserts this
special character.

I located the problem and sent out a patch.  The essential part is that
this character includes a 0x80 byte in utf-8 encoding.

-- 
hundred-and-one symptoms of being an internet addict:
201. When somebody asks you where you are, you tell them in which chat room.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
