### ISSUE TITLE
No mention of <Cmd> in documentation for menus

### ISSUE THREAD

**Issue by fedorenchik** [vim/vim#8166]
**Describe the bug**
Following mapping works:
```vim
:anoremenu Test.Test <Cmd>echo "Test"<CR>
```
There is no mention of this in `gui.txt` documentation (such as `:menu-cmd`), 
but there is documentation for `<Cmd>` in `map.txt`.

**Expected behavior**
Have documentation for `<Cmd>` in menu mappings.

**Environment:**
 - Vim version: 8.2.2730
 - OS: Manjaro GNOME
 - Terminal: GTK3 GUI.

**Comment by brammool** [comment]
Indeed, when <Cmd> was added no help was added for the :menu commands.  I'll add an example.
