### ISSUE TITLE
wrong spelling errors in config files

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8167]
**Describe the bug**

In config files, spelling errors are looked for inside settings, which can give some spurious highlightings.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        var lines =<< trim END
            # some comment with a typoX

            [color]
            status_auth_failed = lightred
        END
        lines->writefile('/tmp/conf.conf')
        e /tmp/conf.conf
        syn on
        &spell = true
    EOF
    )

Inside the comment, `typoX` is highlighted with `SpellBad`; this is expected.
Inside the settings, `auth` and `lightred` are also highlighted with `SpellBad`; this is not expected.

**Expected behavior**

Typos are looked for only in the comments; not in the settings.

**Screenshots**

![gif](https://user-images.githubusercontent.com/8505073/116785535-60c2d980-aa9a-11eb-8912-c23a9e55ede6.gif)

**Environment**

 - Vim version: 8.2 Included patches: 1-2820
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(367)

**Additional context**

I think making the `confComment` syntax items include the `@Spell` cluster would fix the issue.  As a suggestion, here is a patch:
```diff
diff --git a/runtime/syntax/conf.vim b/runtime/syntax/conf.vim
index 9b8a6361b..d7a1d582c 100644
--- a/runtime/syntax/conf.vim
+++ b/runtime/syntax/conf.vim
@@ -10,8 +10,8 @@ endif
 
 syn keyword	confTodo	contained TODO FIXME XXX
 " Avoid matching "text#text", used in /etc/disktab and /etc/gettytab
-syn match	confComment	"^#.*" contains=confTodo
-syn match	confComment	"\s#.*"ms=s+1 contains=confTodo
+syn match	confComment	"^#.*" contains=confTodo,@Spell
+syn match	confComment	"\s#.*"ms=s+1 contains=confTodo,@Spell
 syn region	confString	start=+"+ skip=+\\\\\|\\"+ end=+"+ oneline
 syn region	confString	start=+'+ skip=+\\\\\|\\'+ end=+'+ oneline
 
```

**Comment by brammool** [comment]
Thanks, I'll include it.
