### ISSUE TITLE
'close_cb' and 'exit_cb' will not be invoked if I stop the job by job_stop(s:job_obj, 'int') in windows

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#817]
'close_cb' and 'exit_cb' will not be invoked if I stop the job by job_stop(s:job_obj, 'int') in windows.

if 'term', 'kill' were used to stop the child process (s:job_obj must be unlet after it due to [issue 816](https://github.com/vim/vim/issues/816)), 'close_cb' and 'exit_cb' will be invoked correctly.

But 'close_cb' and 'exit_cb' can be lost if 'term', 'kill' has been replaced to 'int'.

These two bugs are ONLY in windows (gvim 7.4.1832),

**Comment by skywind3000** [comment]
sorry for my misunderstanding

**Comment by brammool** [comment]
I have now tried to reproduce the problem that exit_cb is not invoked on
Windows.  However, I discovered it's not called on Unix until a
character is typed.  That's fixed now.

This is the script I used:

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
let cnt = 1
func! Callback(ch, msg)
  caddexpr 'callback ' . g:cnt
  let g:cnt += 1
endfunc
func! Closed(ch)
  echomsg 'closed'
endfunc
func! Exited(job, status)
  echomsg 'exited with ' . a:status
endfunc

let job = job_start('sh r:/tmp/echolines', {'callback': 'Callback', 'close_cb': 'Closed', 'exit_cb': 'Exited'})

sleep 2

call job_stop(job)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

"echolines" is a simple shell script to output a line every second.

Works in Windows GUI and console.

If you still see the problem, please show us how to reproduce it with a
simple script.

## 

Change is inevitable, except from a vending machine.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///
