### ISSUE TITLE
"lazyredraw, laststatus=2, statusline=%f" generates a command-mode position problem

### ISSUE THREAD

**Issue by xvim64** [vim/vim#8170]
" --------------------------------------------------------------------------------
" _vimrc
" --------------------------------------------------------------------------------

set bomb
set enc=utf-8
set fenc=utf-8

" Vim 8.2.2825 compiled by MSVC (Visual Studio 2019)

" These below three lines cause the "command-mode position problem"
" in vim.exe (in cmd.exe) in windows 10 home 64bit

set lazyredraw | "when lazyredraw is true
	set laststatus=2 | "wneh statusline is visible
		set statusline=%f | "when statusline is defined

" --------------------------------------------------------------------------------
" [ command-mode position problem by { [ "set laststatus=2" and "set statusline=%f" ] when "set lazyredraw" }
" --------------------------------------------------------------------------------
" a
" b
" c
" d <- current cursor position
" e
" f
" g
" ~
" ~
" ~
" ******************************* status-line ************************************
"
" --------------------------------------------------------------------------------
" changed to command-mode
" --------------------------------------------------------------------------------
" a
" b
" c
" : <- wrong command-mode position
"
"
"
"
"
"
" ******************************* status-line ************************************
"
" --------------------------------------------------------------------------------

![1](https://user-images.githubusercontent.com/83569599/116844771-0901ab00-ac1f-11eb-915f-6cc3d3c1a6e1.jpg)
![2](https://user-images.githubusercontent.com/83569599/116844773-0a32d800-ac1f-11eb-8647-2fa78ad18855.jpg)

**Comment by brammool** [comment]
I cannot reproduce it.  Judging by the screenshots you do much more than those settings, e.g. splitting windows.
Please give exact reproduction steps, starting with "vim --clean".

**Comment by matveyt** [comment]
@brammool  Reproducible in standard Windows console. Any visible non-default status line and `set lazyredraw`.

```
$ vim --clean
:set lazyredraw
:set statusline=foo
:set laststatus=2
```

Now pressing "colon" takes cursor to the top line. not to the bottom one. Don't know how to test it though.

**Comment by k-takata** [comment]
I can reproduce on vim.exe 8.2.2825, not on 8.2.2451.
Need bisecting.

**Comment by k-takata** [comment]
8.2.2681 is okay, 8.2.2689 has this problem.
8.2.2686 caused this?

**Comment by xvim64** [comment]
There is nothing more than that three settings.

I tested it hundred times to find three settings by removing lines in my _vimrc.

The splitting window makes the user-defined status-line visible when "set laststatus=1"

When "set laststatus=2" the splitting window is not necessary.

The point is "user-defined(non-default) visible status-line" when "set lazyredraw" in Windows cmd.exe (vim.exe)

**Comment by xvim64** [comment]
> 
> 
> I cannot reproduce it. Judging by the screenshots you do much more than those settings, e.g. splitting windows.
> Please give exact reproduction steps, starting with "vim --clean".

There is nothing more than that three settings.

I tested it hundreds of times to find these three settings by removing lines in my _vimrc.

The splitting window makes the user-defined status-line visible when "set laststatus=1".

When "set laststatus=2" the splitting window is not necessary.

C:> vim.exe --clean
:set lazyredraw
:set statusline=hello\ world  <--  non-default status-line
:set laststatus=2  <-- no need to split window
":set laststatus=1  <-- need to split window to reproduce the problem

**Comment by k-takata** [comment]
It seems that this is Windows console-specific.

**Comment by matveyt** [comment]
Found it ce0b757. @k-takata is right. It's 8.2.2686.

**Comment by brammool** [comment]
Strange that this only happens in the windows console, the patch isn't windows-specific at all.
Ken, do you think you can find out what happens?

**Comment by matveyt** [comment]
There's something happening in `vgetorpeek(FALSE)` (`redrawstatuslines()` -> `win_redr_status()` -> `redrawing()` -> `char_avail()` -> ... -> `vgetorpeek()`). It probably shouldn't affect display while only peeking input queue but somehow it does.

If we could skip this check and simply repaint then it seems to work. The following is surely wrong and unsuitable for production code, but just for example:

```diff
diff --git a/src/ex_getln.c b/src/ex_getln.c
index a9f33e6ec..1e653ee42 100644
--- a/src/ex_getln.c
+++ b/src/ex_getln.c
@@ -1712,17 +1712,11 @@ getcmdline_int(
     // function.
     if (!cmd_silent && msg_scrolled == 0)
     {
-   int found_one = FALSE;
    win_T   *wp;
 
    FOR_ALL_WINDOWS(wp)
        if (*p_stl != NUL || *wp->w_p_stl != NUL)
-       {
-       wp->w_redr_status = TRUE;
-       found_one = TRUE;
-       }
-   if (found_one)
-       redraw_statuslines();
+       win_redr_custom(wp, FALSE);
     }
 #endif
```

**Comment by brammool** [comment]
> There's something happening in `vgetorpeek(FALSE)`
> (`redrawstatuslines()` -> `win_redr_status()` -> `redrawing()` ->
> `char_avail()` -> ... -> `vgetorpeek()`). It probably shouldn't affect
> display while only peeking input queue but somehow it does.
> 
> If we could skip this check and simply repaint then it seems to work.
> The following is surely wrong and unsuitable for production code, but
> just for example:

Hmm,  that seems to just skip some things.

Perhaps we need to set "State" earlier, so that this doesn't happen:

		// In insert mode a screen update is skipped when characters
		// are still available.  But when those available characters
		// are part of a mapping, and we are going to do a blocking
		// wait here.  Need to update the screen to display the
		// changed text so far. Also for when 'lazyredraw' is set and
		// redrawing was postponed because there was something in the
		// input buffer (e.g., termresponse).
		if (((State & INSERT) != 0 || p_lz) && (State & CMDLINE) == 0
			  && advance && must_redraw != 0 && !need_wait_return)
		{
		    update_screen(0);
		    setcursor(); // put cursor back where it belongs
		}


-- 
Get a life?  What is the URL where it can be downloaded?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by matveyt** [comment]
> Perhaps we need to set "State" earlier, so that this doesn't happen

I saw this code but the condition depends on `advance` parameter that is guaranteed to be `FALSE` from `char_avail()`, so it does not seem to help with this.
BTW. The issue can be partially reproduced in GUI/other platforms:

```VimL
set lazyredraw
nnoremap Q :find<Space>
```

Then pressing "Q" doesn't update status line(s) until you finally leave the command-line mode (though everything else is ok).

The only thing I can think of so far is to temporarily disable `lazyredraw`. This seems to cure both:

```diff
diff --git a/src/ex_getln.c b/src/ex_getln.c
index a9f33e6ec..89155b337 100644
--- a/src/ex_getln.c
+++ b/src/ex_getln.c
@@ -1722,7 +1722,12 @@ getcmdline_int(
        found_one = TRUE;
        }
    if (found_one)
+   {
+       int p = p_lz;
+       p_lz = FALSE;
        redraw_statuslines();
+       p_lz = p;
+   }
     }
 #endif
```

**Comment by brammool** [comment]
> > Perhaps we need to set "State" earlier, so that this doesn't happen
> 
> I saw this code but the condition depends on `advance` parameter that is guaranteed to be `FALSE` from `char_avail()`, so it does not seem to help with this.
> BTW. The issue can be partially reproduced in GUI/other platforms:
> 
> ```VimL
> set lazyredraw
> nnoremap Q :find<Space>
> ```
> 
> Then pressing "Q" doesn't update status line(s) until you finally
> leave the command-line mode (though everything else is ok).

That's a different thing, and might be considered an intentional effect
of 'lazyredraw'.  What should not happen is put the cursor in the wrong
plae.

> The only thing I can think of so far is to temporarily disable `lazyredraw`. This seems to cure both:
> 
> ```diff
> diff --git a/src/ex_getln.c b/src/ex_getln.c
> index a9f33e6ec..89155b337 100644
> --- a/src/ex_getln.c
> +++ b/src/ex_getln.c
> @@ -1722,7 +1722,12 @@ getcmdline_int(
>         found_one = TRUE;
>         }
>     if (found_one)
> +   {
> +       int p = p_lz;
> +       p_lz = FALSE;
>         redraw_statuslines();
> +       p_lz = p;
> +   }
>      }
>  #endif
> ```

That defeats the idea of what 'lazyredraw' is for, not redraw things
right away.



-- 
hundred-and-one symptoms of being an internet addict:
236. You start saving URL's in your digital watch.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
