### ISSUE TITLE
mapping: v:false in a popup window also disables keymap - is this intentional?

### ISSUE THREAD

**Issue by puremourning** [vim/vim#8173]
**Describe the bug**

Apologies, I'm not sure this is a bug exactly, but when you have a keyboard filter and mapping disabled in a popup, `keymap` is also disabled. Is this intentional? 

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean -S keymap.vim`

```viml
set keymap=russian-jcukenwin

function! s:Filter( id, key ) abort
  return 0
endfunction

let p = popup_create( 'this is a popup', #{
      \ filter: function( 's:Filter' ),
      \ mapping: v:false,
      \ } )
```

2. Type `I` to enter insert mode, and start typing characters (any should do, but hopefully some which are in the keymap)
4. See they are not mapped by the keymap

**Expected behavior**

Characters are mapped by the keymap, but not by say `:map`

**Environment (please complete the following information):**
 - Vim version 8.2.2800
 - OS: macOS BigSur
- Terminal : iTerm

( my user reported this on Windows with a different 8.2 build)

**Additional context**

https://github.com/ycm-core/YouCompleteMe/issues/3881

**Comment by brammool** [comment]
The keymap is implemented with :lmap commands, thus disabling mapping also disables keymap.
I don't think there is a way around that.

**Comment by puremourning** [comment]
OK, thanks.
