### ISSUE TITLE
Popup breaks normal mode commands

### ISSUE THREAD

**Issue by noscript** [vim/vim#8176]
**Describe the bug**
While popup is visible accidental mouse movement will interrupts normal mode commands.

**To Reproduce**
1. Run vim:
```
vim -g -u NONE -f +"help version8.txt" +"only" +"call popup_create('hello', #{line: 1, close: 'click'})"
```
2. Start `yy` command: press the first key `y`. Cursor will become half of its height.
3. Move the mouse.
4. Cursor becomes full height, command cannot be completed anymore. Pressing the next `y` starts a new command.

**Expected behavior**
Mouse movement is not interrupting unfinished commands.

**Environment**
 - Vim 8.2.2799
 - OS: Ubuntu 20.04
 - Terminal: GUI

**Comment by noscript** [comment]
Thank you! However 1ad72c8 fixes it only for some commands, not all. For example `gg` or `<C-W>s` are still being canceled by mouse movement. That can be seen after enabling `'showcmd'`. The printed keystroke in the right bottom corner disappears after moving the mouse.

**Comment by brammool** [comment]
Thank you! However 1ad72c8 fixes it only for some commands, not all. For
example `gg` or `<C-W>s` are still being canceled by mouse movement.
That can be seen after enabling `'showcmd'`. The printed keystroke in
the right bottom corner disappears after moving the mouse.

OK, I see this hapens.  Perhaps we can solve this in a generic way by
ignore K_MOUSEMOVE in plain_vgetc().  I hope this doesn't have side
effects.  It's hard to predict, I also didn't manage to write a test for
fixing the original problem.

-- 
hundred-and-one symptoms of being an internet addict:
231. You sprinkle Carpet Fresh on the rugs and put your vacuum cleaner
     in the front doorway permanently so it always looks like you are
     actually attempting to do something about that mess that has amassed
     since you discovered the Internet.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by noscript** [comment]
3a00659 fixes it completely, thank you again!
