### ISSUE TITLE
vim's configure.ac potentially breaks LDFLAGS

### ISSUE THREAD

**Issue by nmeum** [vim/vim#8181]
**Describe the bug**

The `gcc(1)` man page describes `-Wl` as follows:

```
       -Wl,option
           Pass option as an option to the linker.  If option contains commas,
           it is split into multiple options at the commas.
```

As such, an `LDFLAGS` value such as `LDFLAGS="-Wl,--as-needed,-O1,--sort-common"` should be perfectly valid. Unfortunately, vim's configure script assumes that each option passed to the Linker in `LDFLAGS` is prefixed with `-Wl,`:

https://github.com/vim/vim/blob/16678eb50f7fcb7138600bd0364edb2c9def8cb8/src/configure.ac#L4522

An `LDFLAGS` value such as the one above will break with these `sed(1)` invocations:

```
$ export LDFLAGS="-Wl,--as-needed,-O1,--sort-common"
$ echo "$LDFLAGS" | sed -e 's/ *-Wl,--as-needed//g' | sed -e 's/$/ -Wl,--as-needed/'
,-O1,--sort-common -Wl,--as-needed
```

Which is obviously an incorrect `LDFLAGS` value and causes linking to fail.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. `export LDFLAGS="-Wl,--as-needed,-O1,--sort-common"`
2. `./configure …`
3. `make`

Linking fails, the first linked binary on my system is xxd for which linking fails with the following error:

```
gcc -Os -fomit-frame-pointer -Os -fomit-frame-pointer -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 ,-O1,--sort-common -L/usr/local/lib -Wl,--as-needed -DUNIX -o xxd xxd.c 
gcc: error: ,-O1,--sort-common: No such file or directory
```

**Expected behavior**
vim should build fine with `LDFLAGS="-Wl,--as-needed,-O1,--sort-common"`.

**Additional context**
I discovered this because the aforementioned `LDFLAGS` values is the default on Alpine Linux.

**Comment by ncopa** [comment]
Introduced in a6cc03101e30d55d4039d539ed732bc02ffd909b

**Comment by ncopa** [comment]
Suggested fix:
```diff
diff --git a/src/configure.ac b/src/configure.ac
index 657cc97f7..bd4881e87 100644
--- a/src/configure.ac
+++ b/src/configure.ac
@@ -4519,7 +4519,9 @@ AC_MSG_CHECKING(linker --as-needed support)
 LINK_AS_NEEDED=
 # Check if linker supports --as-needed and --no-as-needed options
 if $CC -Wl,--help 2>/dev/null | grep as-needed > /dev/null; then
-  LDFLAGS=`echo "$LDFLAGS" | sed -e 's/ *-Wl,--as-needed//g' | sed -e 's/$/ -Wl,--as-needed/'`
+  if ! echo "$LDFLAGS" | grep -q -- '-Wl,[^[:space:]]*--as-needed'; then
+    LDFLAGS="$LDFLAGS -Wl,--as-needed"
+  fi
   LINK_AS_NEEDED=yes
 fi
 if test "$LINK_AS_NEEDED" = yes; then
```

**Comment by nmeum** [comment]
Is there actually any need to prepend `--as-needed` to `$LDFLAGS`? It seems to be me that it builds fine even when `--as-needed` isn't the last linker flag.

**Comment by ncopa** [comment]
> Is there actually any need to prepend `--as-needed` to `$LDFLAGS`? It seems to be me that it builds fine even when `--as-needed` isn't the last linker flag.

The comment explains why its there:
https://github.com/vim/vim/blob/588cf7547bafaff46a82bc125d05d24a1cedf827/src/configure.ac#L4515-L4517

**Comment by brammool** [comment]
> Is there actually any need to prepend `--as-needed` to `$LDFLAGS`? It
> seems to be me that it builds fine even when `--as-needed` isn't the
> last linker flag.

It produces a bigger binary.  This whole idea comes from long ago when
the binary size mattered and we tried to keep it small.  These days most
users don't care so much, but we still try to support this.

-- 
Facepalm statement #4: "3000 year old graves?  That's not possible, it's only
2014!"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
