### ISSUE TITLE
[RFC] Improved continued syntax highlighting for vimscript

### ISSUE THREAD

**Issue by lervag** [vim/vim#8182]
When writing syntax scripts, we often need long commands, e.g.:

```vim
  syntax region texSynIgnoreZone matchgroup=texComment
        \ start="^\c\s*% VimTeX: SynIgnore\%( on\| enable\)\?\s*$"
        \ end="^\c\s*% VimTeX: SynIgnore\%( off\| disable\).*"
        \ contains=texComment,texCmd
```

(Ignore the actualy command, the point is only the "structure".)

I believe it should be possible to improve the `vimContinue` "methodology" to allow e.g. this type of continued syntax statements. I might consider to open a PR for the runtime scripts, but I wanted to check first what the right approach for this might be? I.e., say I find a more or less simple way to improve the current `syntax/vim.vim` to fix the continued syntax statements: how would I procede to suggest the patches/PRs?

**Comment by k-takata** [comment]
The `vim.vim` syntax file is maintained by @cecamp, so contacting him is the best way.

**Comment by lervag** [comment]
@cecamp Are you active here, or do you prefer communications by email? Or elsewhere?

**Comment by cecamp** [comment]
I can see stuff here, but I prefer the vim email list. I'll have more time to look into this next week.

**Comment by lervag** [comment]
I don't mind to use the email list, but I'm not used to it. I'm not really used to email lists in general. Is there a simple description of how to post to the list, perhaps with rules?

**Comment by chrisbra** [comment]
no special rules needed. Just follow the obvious netiquette for mailing lists (just a random google link https://lowendmac.com/2016/netiquette-for-email-lists/). Let me close this, hoping that you either communicate directly using mail or use the vim mailing list.
