### ISSUE TITLE
gVim constantly crashes on Windows 10

### ISSUE THREAD

**Issue by andrescuco** [vim/vim#8187]
When using gVim, the window freezes and closes unexpectedly losing all unsaved changes.

**To Reproduce**
It happens randomly without any particular steps, under high use of splits and tabs it seems to be more common, or after having gVim open for long periods of time.

**Expected behavior**
I'd expect gVim to work without crashing.

**Environment**
 - Vim version 8.2 MS-Windows 64-bit GUI version
 - Windows 10 Home Version 2004 (OS Build 19041.928)
 - Terminal: gVim

**Additional context**
It happens randomly and unexpectedly, normally I have a few tabs open with multiple splits, however it also happens with only one tab. It doesn't happen with any other apps on my machine. I've tried with 32-bit versions of gVim and the same issue persists.

Please let me know if gVim has any crash logs I can share, I couldn't find any.

**Comment by brammool** [comment]
Not on MS-Windows.  Most Unix systems can catch a signal and save work.
You would need to find a pattern in when it happens.
But it can also be a hardware problem...

**Comment by chrisbra** [comment]
does it happen with `gvim --clean` ? What kind of plugins are you using? What is the exact version?

**Comment by dpelle** [comment]
> Vim version 8.2 MS-Windows 64-bit GUI version

Can you try with a more recent version of Vim?

At https://github.com/vim/vim-win32-installer/releases, you can download
the installer of vim-8.2.2844 for Windows.

**Comment by andrescuco** [comment]
> You would need to find a pattern in when it happens.

Tried yesterday and it seems to happen more often right after saving a buffer, I do have a plugin that formats on save (ALE).
> does it happen with `gvim --clean` ? What kind of plugins are you using? What is the exact version?

Currently testing with `gvim --clean`. it normally crashes after a few hours of use so I'm going to test it today and post results, but I can already notice a better performance. You can take a look at all the plugins I'm using [here](https://gist.github.com/andrescuco/f4766ffbff97dbce164bb5e51d6badca).

I'm not sure how to see the exact version, running `:version` gives me 8.2 (2019 Dec 12, compiled Mar 24 2021) Included patches: 1-2650
 
> Can you try with a more recent version of Vim?

Will do, thank you for the link.

**Comment by andrescuco** [comment]
After many hours of testing, I think it's fair to say this is not gVim's fault, but rather an issue with the plugin ALE. I'll be closing this issue and creating one on ALE's repository. Thank you everyone for the help.
