### ISSUE TITLE
guisp support when using termguicolors

### ISSUE THREAD

**Issue by petobens** [vim/vim#819]
I'm using `termguicolors`, but I can't seem to be able to change the spelling underline/undercurl highlight when running Vim from the terminal.  I tried with:

``` vim
hi SpellBad    ctermfg=203   ctermbg=233  cterm=underline gui=undercurl guisp=#fc4234
```

Is `guisp` supported by the `termguicolors` feature?
Thanks in advance.

**Comment by vim-ml** [comment]
2016-05-19 19:51 GMT+03:00 petobens vim-dev-github@256bit.org:

> I'm using termguicolors, but I can't seem to be able to change the
> spelling underline/undercurl highlight when running Vim from the terminal.
> I tried with:
> 
> hi SpellBad    ctermfg=203   ctermbg=233  cterm=underline gui=undercurl guisp=#fc4234
> 
> Is guisp supported by the termguicolors feature?
> Thanks in advance.

​I do not know a way to set highlighting of the underlining in terminal, so
I never tried to implement `guisp` with &termguicolors.​

**Comment by chrisbra** [comment]
So this is not possible. Closing then.

**Comment by ZyX-I** [comment]
“I do not know” ≠ “it is not possible”. AFAIR I examined issue a bit, but found nothing in xterm escape sequences and no good spec for konsole ones, but there are many different terminal emulators with different non-standard escape sequences. Though most likely if somebody finds something like this then some sort of campaign will be needed to make this supported in modern terminal emulators: like it was done for true colors (when I have written my 24-bit-xterm branch AFAIR only konsole supported true colors, and xterm had a limited support (understood, but mapped to closest (in RGB space) color in 8-bit palette)).

**Comment by dpelle** [comment]
@ZyX-I  wrote:
 ​

> I do not know a way to set highlighting of the underlining in terminal, so I never tried to implement `guisp` with &termguicolors.​  

The CSApprox plugin contains a variable to let user decode how to convert some GUI attribute to the terminal.  See help file CSApprox.txt  (https://github.com/godlygeek/csapprox/blob/master/doc/CSApprox.txt):

Relevant snippet:

```
g:CSApprox_attr_map                                      *g:CSApprox_attr_map*
    Since some attributes (like 'guisp') can't be used in a terminal, and
    others (like 'italic') are often very ugly in terminals, a generic way to
    map between a requested attribute and another attribute is included.  This
    variable should be set to a Dictionary, where the keys are strings
    representing the attributes the author wanted set, and the values are the
    strings that the user wants set instead.  If a value is '', it means the
    attribute should just be ignored.  The default is to replace 'italic' with
    'underline', and to use 'fg' instead of 'sp': >
        let g:CSApprox_attr_map = { 'italic' : 'underline', 'sp' : 'fg' }
<
    Your author prefers disabling bold and italic entirely, so uses this: >
        let g:CSApprox_attr_map = { 'bold' : '', 'italic' : '', 'sp' : 'fg' }
<

    Note: This transformation is considered at the time a snapshotted scheme
          is created, rather than when it is used.

    Note: You can only map an attribute representing a color to another
          attribute representing a color; likewise with boolean attributes.
          After all, sp -> bold and italic -> fg would be nonsensical.
```

Now I don't know whether something like this should be done in Vim, but it may give ideas.

**Comment by ZyX-I** [comment]
@dpelle About `guisp` this snippet directly tells you that it “can’t be used in a terminal”. `gui` attribute AFAIR is ignored completely, &termguicolors only works with guifg/guibg.

**Comment by venthur** [comment]
How about replacing the (hi gui-) undercurl with (hi term-) underlines in terminals when setting the `termguicolors` option? I assume this comes closest to the behavior a user would expect. When ignoring the undercurl completely the user will not see any spelling mistakes by default in the terminal when using the `termguicolors` option, which is certainly not expected.
