### ISSUE TITLE
Annoying scrollbars on Vim

### ISSUE THREAD

**Issue by vzytoi** [vim/vim#8196]
I have a bottom and right scrollbar that appear when I do some specific things :
1. ressourcing my vimrc (only when set termguicolors is activate)
2. using terminal commands in Vim like :!dir

There is no specific way to reproduce it, I recently reset my Windows 10 and it still doing it.

A screen of the scrollbars : [https://i.imgur.com/LoJBXqT.png](https://i.imgur.com/LoJBXqT.png)

**Environment (please complete the following information):**
 - VIM - Vi IMproved 8.2
 - OS: Windows 10 20H2
 - Terminal: cmd, powershell, [Ubuntu terminal](https://www.microsoft.com/fr-fr/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab)

**Comment by chrisbra** [comment]
I am not sure this helps, but see if `:set guioptions+=k`. Also you may want to check, if the `lines` and `columns` options (or the `$COLUMNS` and `$LINES` environment variables) changed unexpectedly whenever you experience this. Also, it may depend on what terminal type you have configured, check `:set term? ` and `echo $TERM`. Also please try to reproduce with a minimal config file, start from `vim --clean` and see if that happens there. If it doesn't, it may be something in your configuration (or plugins) that is causing this.)

**Comment by k-takata** [comment]
Which are you using, gvim.exe or vim.exe?

> * Terminal: cmd, powershell, [Ubuntu terminal](https://www.microsoft.com/fr-fr/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab)

Does it also happen on vim on WSL?

**Comment by mMontu** [comment]
From the image it seems Windows + gVim. You could try the following:

     " remove the bottom scrollbar
     set guioptions-=b
     " remove the right-hand scrollbar
     set guioptions-=r

**Comment by chrisbra** [comment]
no answer. Please open a new issue if you still encounter this and provide more information
