### ISSUE TITLE
add fish syntax highlighting

### ISSUE THREAD

**Issue by aeosynth** [vim/vim#820]
fish is a somewhat popular shell, and it would be nice if syntax highlighting were supported by default

is there a process for adding new languages to the default runtime?

**Comment by chrisbra** [comment]
Someone, who already maintains a fish syntax script should state, the he wants to distribute his syntax script with vim. idealy the license allows us to distribute it (i think the vim license would be preferable). Do you know such a script (or perhaps even maintain such one)?

**Comment by kopischke** [comment]
Just in case nobody more qualified steps forward: I have recently forked the excellent, but unmaintained (the most up to date fork just integrates pending pull requests) [vim-fish](https://github.com/kopischke/fish.vim) and started updating it (private branch, not pushed yet). I’m sure I am not the most qualified person to do so, but I would be willing to maintain it, or a syntax subset, for the Vim runtime if nobody else does.

**Comment by aeosynth** [comment]
@kopischke no one else seems interested, can you publish your code?

**Comment by OJFord** [comment]
It would be great if this could be added. I found this issue by trying to work through a mess of forks and determine which would be best to install. @wilriker and @fingerblaster have the most recently updated forks - I wonder if there's any interest there in maintaining an 'official' fork?

**Comment by wilriker** [comment]
On the one hand I'd like to provide my fork as an official source but to be honest, all I am doing here is trial&error most of the time as I am not exactly a master of vimscript. But I am willing to offer my code base to whoever feels more appropriate to maintain a vim plugin.

**Comment by rodrigobdz** [comment]
> Just in case nobody more qualified steps forward: I have recently forked the excellent, but unmaintained (the most up to date fork just integrates pending pull requests) [vim-fish](https://github.com/kopischke/fish.vim) and started updating it (private branch, not pushed yet). I’m sure I am not the most qualified person to do so, but I would be willing to maintain it, or a syntax subset, for the Vim runtime if nobody else does.

The link provided in the comment is broken. Would love to see Fish syntax highlighting in vim.

**Comment by MarcinOrlowski** [comment]
Seems @kopischke gave up as I am unable to find anything related vim-fish among his public repos.

**Comment by kopischke** [comment]
@MarcinOrlowski whoops, yes, sorry, I should have stated that but thought @wilriker would pick up the torch; my bad, this was not me at my best. I never pushed my half assed fork as RL has taken me away from regular Vim use, so consider me out of the equation. Again, apologies for not stating this clearly earlier.

**Comment by nickeb96** [comment]
I'd like to put [my vim plugin for fish](https://github.com/nickeb96/fish.vim) up as a candidate.  The syntax highlighting is more accurate and consistent compared to other plugins I've seen.  Also, it very closely matches how fish natively highlights interactive commands and output of the `type` builtin.

I will happily be a maintainer for these files and update them as fish changes and adds new features.  I also haven't selected a license yet, so I can use the vim license if that helps.

The only question I have is how I go about submitting them.  Do I just make a pull request with my additions?  I couldn't find any relevant info on adding new runtime files in [CONTRIBUTING.md](https://github.com/vim/vim/blob/master/CONTRIBUTING.md).

**Comment by brammool** [comment]
> I'd like to put [my vim plugin for
> fish](https://github.com/nickeb96/fish.vim) up as a candidate.  The
> syntax highlighting is more accurate and consistent compared to other
> plugins I've seen.  Also, it very closely matches how fish natively
> highlights interactive commands and output of the `type` builtin.

I don't know Fish, I'll let others comment on whether this syntax file
is a good choice.

> I will happily be a maintainer for these files and update them as fish
> changes and adds new features.  I also haven't selected a license yet,
> so I can use the vim license if that helps.

Using the Vim license avoids trouble distributing the whole package.
It is defenitely good to have an active maintainer.

> The only question I have is how I go about submitting them.  Do I just
> make a pull request with my additions?  I couldn't find any relevant
> info on adding new runtime files in
> [CONTRIBUTING.md](https://github.com/vim/vim/blob/master/CONTRIBUTING.md). 

You can create a PR, that gives others a chance to have a look and make
comments.  If that is too complicated you can also email me the files.


-- 
From "know your smileys":
 :-)	Funny
 |-)	Funny Oriental
 (-:	Funny Australian

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dkearns** [comment]
FWIW, I approached [another project](https://github.com/khaveesh/vim-fish-syntax/issues/1) some time ago but received no response.

I don't use Fish and have no opinion on which set of files are better I was just trying to close this issue which I thought might be low hanging fruit.

**Comment by nickeb96** [comment]
The fish runtime files above are now in vim as of this commit: 938ae280c79b8cdb0fca60336ec4c090ecd8bb5a

It looks like someone with admin rights can close complete this issue.

**Comment by chrisbra** [comment]
closing then
