### ISSUE TITLE
Enhancement: bwipeout should also remove buffer from jump list

### ISSUE THREAD

**Issue by joeytwiddle** [vim/vim#8201]
### Problem

I am working with multiple buffers open, and I open a new file, but I made a mistake and it was not the file I wanted, in fact it wasn't at all relevant to my current work. So I do `:bwipeout!` to close that buffer. This brings the focus back to my previous buffer, okay fine.

Unfortunately if at any point in future I start using CTRL-O to get back to where I was working earlier, now the unwanted file is in the jump list, and that file opens again!

This is undesirable, since I did `bwipeout!` specifically because I didn't want to work with that file any more. I cannot think of a situation where this behaviour would be desirable.

### Proposed solution

When using `bwipeout` or `bwipeout!` I would like all of the jump lists's references to that buffer to be removed/forgotten. (And indeed from anywhere else that buffer may have been referenced in Vim's state.)

Alternative: When doing jumps, do not open any files which are not already open. Unfortunately, that would significantly change Vim's traditional behaviour. However it might be acceptable if the new behaviour was behind an option, and disabled by default.

### Additional

Should this new behaviour apply to `bdel` and `bdel!` as well?

**Comment by brammool** [comment]
> ### Problem
> 
> I am working with multiple buffers open, and I open a new file, but I made a mistake and it was not the file I wanted, in fact it wasn't at all relevant to my current work. So I do `:bwipeout!` to close that buffer. This brings the focus back to my previous buffer, okay fine.
> 
> Unfortunately if at any point in future I start using CTRL-O to get back to where I was working earlier, now the unwanted file is in the jump list, and that file opens again!
> 
> This is undesirable, since I did `bwipeout!` specifically because I didn't want to work with that file any more. I cannot think of a situation where this behaviour would be desirable.
> 
> ### Proposed solution
> 
> When using `bwipeout` or `bwipeout!` I would like all references to that buffer dropped from the jump list. (And indeed from anywhere else it my be references in Vim's state.)
> 
> Alternative: When doing jumps, do not open any files which are not already open. Unfortunately, that would significantly change Vim's traditional behaviour. However it might be acceptable if the new behaviour was behind an option, and disabled by default.
> 
> ### Additional
> 
> Should this new behaviour apply to `bdel` and `bdel!` as well?

I think it makes sense that when doing :bwipe! the buffer references are
removed.  It's basically saying "forget about this buffer completely".
It's not 100% backwards compatible, but I doubt that anyone will notice.

Implementation is going to be some work.

-- 
ARTHUR: (as the MAN next to him is squashed by a sheep) Knights!  Run away!
   Midst echoing shouts of "run away" the KNIGHTS retreat to cover with the odd
   cow or goose hitting them still.  The KNIGHTS crouch down under cover.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
