### ISSUE TITLE
netrw.vim seems to reuse s:netrw_usercul, s:netrw_usercuc without reinitializing

### ISSUE THREAD

**Issue by xvim64** [vim/vim#8204]
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Describe the bug**
When executing the ":Explore" multiple times, the values of  "cursorline, cursorcolumn" are ignored from the second time onwards.

**To Reproduce**
1. C:> vim t.txt
2. :set cursorline
3. :set cursorcolumn
4. :Explore
// Select "t.txt"
5. :echo &cursorline    -->    1
6. :echo &cursorcolumn    -->    1
7. :set nocursorline
8. :set nocursorcolumn
9. :Explore
// Select "t.txt" again
10. :echo &cursorline    -->    1 ( Bug : "set nocursorline" is ignored )
11. :echo &cursorcolumn    -->    1 ( Bug : "set nocursorcolumn" is ignored )

**Expected behavior**
10. :echo &cursorline    -->    0
11. :echo &cursorcolumn    -->    0

**Screenshots**
![4](https://user-images.githubusercontent.com/83569599/118125328-c8c9d600-b431-11eb-8d2f-d66f091a4887.gif)
![5](https://user-images.githubusercontent.com/83569599/118125333-c8c9d600-b431-11eb-928f-6e22058e9074.gif)

**Environment (please complete the following information):**
 - Vim 8.2.2847
 - OS: [Windows 10 64bit, 20H2, 19042.985]

**Additional context**

// When executing ":Explore" at first these two lines are initialized
[netrw.vim] -- 332 --
![1](https://user-images.githubusercontent.com/83569599/118125322-c6677c00-b431-11eb-9fe7-02d84febb799.png)

// and when executing ":Explore" from the second time  ...
// it seems that "s:netrw_usercul, s:netrw_usercuc" are resued without reinitializing.
[netrw.vim] -- 11759 --
![2](https://user-images.githubusercontent.com/83569599/118125325-c798a900-b431-11eb-9c9e-3091eadcf497.png)

// When disabling these two lines, there is no problem anymore.
[netrw.vim] -- 11759 --
![3](https://user-images.githubusercontent.com/83569599/118125326-c8313f80-b431-11eb-8103-8e66b80b40e7.png)

**Comment by brammool** [comment]
@cecamp
