### ISSUE TITLE
vim.exe with "set lazyredraw, set laststatus=2, set statusline=foo" causes no output message

### ISSUE THREAD

**Issue by xvim64** [vim/vim#8211]
**Describe the bug**
vim.exe with "set lazyredraw, set laststatus=2, set statusline=foo" causes no output message

**To Reproduce**
1. C:> vim --clean
2. :set laststatus=2
3. :set statusline=foo
4. :echo "hello world"
5. // output --> hello world
6. :set lazyredraw
7. :echo "hello world"
8. // no output  -->  ( Bug)
9. :echo "abcdefg"
10. // no output  -->  ( Bug )

**Expected behavior**
7. :echo "hello world"
8. // output  -->  hello world
9. :echo "abcdefg"
10. // output  -->  abcdefg

**Screenshots**
![1](https://user-images.githubusercontent.com/83569599/118365559-3879c580-b5d8-11eb-9c06-5067b7dd971c.gif)

**Environment (please complete the following information):**
VIM - Vi IMproved 8.2
MS-Windows 64-bit console version
Included patches: 1-2850

**Comment by matveyt** [comment]
So it's about ce0b757 again. In  e08795e we've fixed the `cmdline_row` but never prevented redrawing.

[src/os_win32.c:1650](https://github.com/vim/vim/blob/0820f4de5872bfbdc25bf6cba6ec5646dbcec156/src/os_win32.c#L1650)
```c
# ifdef FEAT_MBYTE_IME
	if (State & CMDLINE && msg_row == Rows - 1)
	{
	    CONSOLE_SCREEN_BUFFER_INFO csbi;

	    if (GetConsoleScreenBufferInfo(g_hConOut, &csbi))
	    {
		if (csbi.dwCursorPosition.Y != msg_row)
		{
		    // The screen is now messed up, must redraw the command
		    // line and later all the windows.
		    redraw_all_later(CLEAR);
		    compute_cmdrow();
		    redrawcmd();
		}
	    }
	}
# endif
```
After ce0b757 the cursor gets on current line in active window, so the condition `csbi.dwCursorPosition.Y != msg_row` becomes true and we do redraw. Honestly, I don't get the kind of problem this code tries to deal with. It looks like if it's been deleted then everything works just fine. I'm probably missing something but the condition needs to be changed anyway.

**Comment by brammool** [comment]
> **Describe the bug**
> "set lazyredraw, set laststatus=2, set statusline=foo" cause no output message
> 
> 
> **To Reproduce**
> 1. C:> vim --clean
> 2. :set laststatus=2
> 3. :set statusline=foo
> 4. :echo "hello world"
> 5. // output --> hello world
> 6. :set lazyredraw
> 7. :echo "hello world"
> 8. // no output  -->  ( Bug)
> 9. :echo "abcdefg"
> 10. // no output  -->  ( Bug )
> 
> 
> **Expected behavior**
> 7. :echo "hello world"
> 8. // output  -->  hello world
> 9. :echo "abcdefg"
> 10. // output  -->  abcdefg
> 
> 
> **Screenshots**
> ![1](https://user-images.githubusercontent.com/83569599/118365559-3879c580-b5d8-11eb-9c06-5067b7dd971c.gif)
> 
> 
> **Environment (please complete the following information):**
> VIM - Vi IMproved 8.2
> MS-Windows 64-bit console version
> Included patches: 1-2850

I cannot reproduce this problem.  It might be MS-Windows specific.

-- 
FIRST HEAD:  Oh! quick! get the sword out I want to cut his head off.
THIRD HEAD:  Oh, cut your own head off.
SECOND HEAD: Yes - do us all a favour.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by matveyt** [comment]
> I cannot reproduce this problem. It might be MS-Windows specific.

Yes, it's Windows only. (Almost) the same as #8170,

**Comment by brammool** [comment]
> So it's about ce0b757 again. In  e08795e we've fixed the `cmdline_row` but never prevented redrawing.
> 
> [src/os_win32.c:1650](https://github.com/vim/vim/blob/0820f4de5872bfbdc25bf6cba6ec5646dbcec156/src/os_win32.c#L1650)
> ```c
> # ifdef FEAT_MBYTE_IME
> 	if (State & CMDLINE && msg_row == Rows - 1)
> 	{
> 	    CONSOLE_SCREEN_BUFFER_INFO csbi;
> 
> 	    if (GetConsoleScreenBufferInfo(g_hConOut, &csbi))
> 	    {
> 		if (csbi.dwCursorPosition.Y != msg_row)
> 		{
> 		    // The screen is now messed up, must redraw the command
> 		    // line and later all the windows.
> 		    redraw_all_later(CLEAR);
> 		    compute_cmdrow();
> 		    redrawcmd();
> 		}
> 	    }
> 	}
> # endif
> ```
> After ce0b757 the cursor gets on current line in active window, so the
> condition `csbi.dwCursorPosition.Y != msg_row` becomes true and we do
> redraw. Honestly, I don't get the kind of problem this code tries to
> deal with. It looks like if it's been deleted then everything works
> just fine. I'm probably missing something but the condition needs to
> be changed anyway.

There was a problem that the windows console did not handle some Asian
character properly, resulting in the display being messed up.  There
could perhaps be another condition that an Asian character (perhaps
double width) was output, but that might be complicated.  Most users
won't notice the extra redraw, but it does slow down things.  Thus the
redraw being triggered too often might not be reported by users.

-- 
Q: How does a UNIX Guru do Sex ?
A: unzip;strip;touch;finger;mount;fsck;more;yes;umount;sleep

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
