### ISSUE TITLE
No error when putting white spaces after `->` for a method call

### ISSUE THREAD

**Issue by obcat** [vim/vim#8212]
**Describe the bug**

No error is raised when putting white spaces after `->` for a method call.

**To Reproduce**

```vim
$vim --clean
:echo 3 ->        range()
" [0, 1, 2]
```

**Expected behavior**

`E274` is raised:

```vimhelp
							*E274*
"->name(" must not contain white space.  There can be white space before the
"->" and after the "(", thus you can split the lines like this: >
	mylist
	\ ->filter(filterexpr)
	\ ->map(mapexpr)
	\ ->sort()
	\ ->join()
```

**Environment**

 - Vim 8.2.2776
 - macOS Catalina (version 10.15.7)
 - iTerm2

**Comment by brammool** [comment]
> **Describe the bug**
> 
> No error is raised when putting white spaces after `->` for a method call.
> 
> **To Reproduce**
> 
> ```vim
> $vim --clean
> :echo 3 ->        range()
> " [0, 1, 2]
> ```
> 
> **Expected behavior**
> 
> `E274` is raised:
> 
> ```vimhelp
> 							*E274*
> "->name(" must not contain white space.  There can be white space before the
> "->" and after the "(", thus you can split the lines like this: >
> 	mylist
> 	\ ->filter(filterexpr)
> 	\ ->map(mapexpr)
> 	\ ->sort()
> 	\ ->join()
> ```

This was changed in patch 8.2.2396.  The comment says to allow for white
space before the "->", but it actually also allows it after.

We should probably keep the old behavior for legacy script.

I wonder about Vim9 script.  Should we allow for:

	value  ->  func()

Or is there a reason to disallow it?  I don't think it looks ugly or is
confusing, so we can keep skipping white space in Vim9 script.

-- 
       He was not in the least bit scared to be mashed into a pulp
       Or to have his eyes gouged out and his elbows broken;
       To have his kneecaps split and his body burned away
       And his limbs all hacked and mangled, brave Sir Robin.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by obcat** [comment]
Thank you for the update.

> I wonder about Vim9 script.  Should we allow for:
> 
> 	value  ->  func()
> 
> Or is there a reason to disallow it?  I don't think it looks ugly or is
> confusing, so we can keep skipping white space in Vim9 script.

I agree with you. Allowing for white space both before and after `->` would be more consistent :)
