### ISSUE TITLE
Vim incorrectly detects Slim files as HTML

### ISSUE THREAD

**Issue by hovsater** [vim/vim#822]
I have a file written in [Slim](http://slim-lang.com/). The contents of this file can be found below.

``` slim
doctype html
html
  head
    title Slim Examples
    meta name="keywords" content="template language"
    meta name="author" content=author
    javascript:
      alert('Slim supports embedded javascript!')

  body
    h1 Markup examples

    #content
      p This example shows you how a basic Slim file looks like.

      == yield

      - unless items.empty?
        table
          - items.each do |item|
            tr
              td.name = item.name
              td.price = item.price
      - else
        p
         | No items found.  Please add some inventory.
           Thank you!

    div id="footer"
      = render 'footer'
      | Copyright © #{year} #{author}
```

Vim incorrectly detects this file as html and thus, setting the filetype to `html` incorrectly. The culprit is found here https://github.com/vim/vim/blob/master/runtime/scripts.vim#L247-L249. The current regex is too generic and detects `doctype html` as a `<!DOCTYPE` declaration in HTML.

I'd expect Vim to not detect the file as `HTML` and by extension not setting the `filetype` setting. I think this can easily be solved by modifying the regex to look for a `!` before `DOCTYPE`.

I can submit a pull request if you're interested.

**Comment by brammool** [comment]
Script will be updated
