### ISSUE TITLE
Disambiguate %c in documentation of error-file-format

### ISSUE THREAD

**Issue by poetaman** [vim/vim#8222]
The description of ``%c`` [here](https://vimhelp.org/quickfix.txt.html#error-file-format) is not clear whether its byte offset or not (``(finds a number representing character column of the error, (1 <tab> == 1 character column))``). Given it is byte offset, it might be a good idea to mention that in the documentation. Or IMHO vim might be in need of a glossary of terms, given name "column" & "byteindex" ("byteoffset") get used interchangeably in places, which can lead to confusion as can be seen in above example:  byteindex/byteoffset is called by a 3rd name "character column" (which makes it sound like character number, which it is not...)

> As a side note, the new feature "text properties" uses the name "col" for byte-offset.

**Comment by brammool** [comment]
Well it does say that a tab is 1 column, so that means it is a byte index.
I'll add the term "byte index", some users may find that easier to understand.
