### ISSUE TITLE
Syntax highlighting with text property does not work well when setting cusorline.

### ISSUE THREAD

**Issue by dpelle** [vim/vim#8225]
**Describe the bug**

Syntax highlighting with text property does not work well when setting `cursorline`.

**To Reproduce**
```
$ cat > text-prop-and-set-cul.vim <<EOF
" www xxx yyy zzz

" Source this script with:
"   $ vim --clean -c 'so %' text-prop-and-set-cul.vim
" Then press j k and to move the cursor on line 2 and line 1 and
" notice that:
" - yyy which uses matchdd() is highlighted in red background
"   in line 1 as expected.
" - xxx which uses text property is not highlighted in red background
"   in line1 when current line is line 1 (BUG).
"
" Is there a way to make text property highlighted in the current line
" just like with matchadd()?

set termguicolors cursorline
hi CursorLine guifg=NONE guibg=#303030 gui=none term=none 
\             cterm=none ctermfg=darkgrey ctermbg=grey

" Highlight xxx using a text property.
call prop_type_add('my_prop', {'highlight': 'Error'})
call prop_add(1, 7, {'type': 'my_prop', 'length': 3})

" Highlight yyy using matchadd().
call matchadd('Error', 'yyy\%1l')         
EOF

$ vim --clean -c 'so %' text-prop-and-set-cul.vim
```
Then in normal mode, press `j` and `k`  to move the cursor outside and on of the first line.

Notice that:
- `yyy` which uses `matchadd()` is highlighted in red background in line 1 as expected.
- `xxx` which uses a text property is not highlighted in red background in line 1 when current line is line 1 (**BUG**).

**Expected behavior**
The text `xxx` should be highlighted in red background whether the cursor is on the first line or not (as what happens with `matchadd()`).

**Screenshots**
[![asciicast](https://asciinema.org/a/XYn3CYU5If9IEk4zejuYJNbs2.svg)](https://asciinema.org/a/XYn3CYU5If9IEk4zejuYJNbs2)

**Environment**
 - Vim-8.2.2867
 - OS: xubuntu-18.04.5

**Comment by brammool** [comment]
Dominique wrote:

> **Describe the bug**
> 
> Syntax highlighting with text property does not work well when setting `currentline`.
> 
> **To Reproduce**
> ```
> $ cat > text-prop-and-set-cul.vim <<EOF
> " www xxx yyy zzz
> 
> " Source this script with:
> "   $ vim --clean -c 'so %' text-prop-and-set-cul.vim
> " Then press j k and to move the cursor on line 2 and line 1 and
> " notice that:
> " - yyy which uses matchdd() is highlighted in red background
> "   in line 1 as expected.
> " - xxx which uses text property is not highlighted in red background
> "   in line1 when current line is line 1 (BUG).
> "
> " Is there a way to make text property highlighted in the current line
> " just like with matchadd()?
> 
> set termguicolors cursorline
> hi CursorLine guifg=NONE guibg=#303030 gui=none term=none 
> \             cterm=none ctermfg=darkgrey ctermbg=grey
> 
> " Highlight xxx using a text property.
> call prop_type_add('my_prop', {'highlight': 'Error'})
> call prop_add(1, 7, {'type': 'my_prop', 'length': 3})
> 
> " Highlight yyy using matchadd().
> call matchadd('Error', 'yyy\%1l')         
> EOF
> 
> $ vim --clean -c 'so %' text-prop-and-set-cul.vim
> ```
> Then in normal mode, press `j` and `k`  to move the cursor outside and on of the first line.
> 
> Notice that:
> - `yyy` which uses `matchadd()` is highlighted in red background in line 1 as expected.
> - `xxx` which uses a text property is not highlighted in red background in line 1 when current line is line 1 (**BUG**).
> 
> **Expected behavior**
> The text `xxx` should be highlighted in red background whether the cursor is on the first line or not (as what happens with `matchadd()`).
> 
> **Screenshots**
> [![asciicast](https://asciinema.org/a/XYn3CYU5If9IEk4zejuYJNbs2.svg)](https://asciinema.org/a/XYn3CYU5If9IEk4zejuYJNbs2)

I think we need more control over how text properties are displayed when
other highlighting is present.  Fist thing to do is to document the
current priorities (which isn't that simple) and define a way for text
properties to go somewhere in between.

-- 
This is the polymorph virus!  Follow these instructions carefully:
1. Send this message to everybody you know.
2. Format your harddisk.
Thank you for your cooperation in spreading the most powerful virus ever!

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
