### ISSUE TITLE
let `texMathZones` ignore the zone before `\begin{document}`

### ISSUE THREAD

**Issue by Edenharder** [vim/vim#8228]
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Describe the bug**
It about `.tex` file. It seems that `texMathZones` takes the zone before `\begin{document}` also into consideration. This is unnecessary and causes problem sometimes.
**To Reproduce**
For example, 
```
\documentclass{article}
\usepackage{array}
\newcolumntype{C}{>{$}c<{$}} %1
\begin{document}
$This part is detected as not texMathZones$ %2
This part is detected as texMathZones %3
\end{document}
```
The line `%1` contains `$`, and it is before the beginning of the document. Then the part between the two `$` in place `%2`has not been detected as `texMathZones`. Instead, the part in place `%3`, which should not be a `texMathZones`, is detected as `texMathZones`.

**Expected behavior**
`texMathZones` should ignore the zone before the beginning of the document.

**Environment (please complete the following information):**
 - Vim version 8.2

**Comment by cecamp** [comment]
I don't see the problem you're having. Have you tried the latest version of [tex.vim](http://www.drchip.org/astronaut/vim/index.html#SYNTAX_TEX)? The url is mentioned in syntax/tex.vim, by the way.

**Comment by Edenharder** [comment]
@cecamp Thank you for the reply. I find it out, the problem is with [`vimtex`](https://github.com/lervag/vimtex). If I turn off `vimtex`, then everything is normal. Otherwise, the `$` before the beginning of the document would be detected.

**Comment by Edenharder** [comment]
It has been fixed in the package `vimtex` now.
