### ISSUE TITLE
auto/configure support python 3.1x 

### ISSUE THREAD

**Issue by WinChua** [vim/vim#8233]
if we would like to support 
 python3.1x

maybe the code line here https://github.com/vim/vim/blob/5cf94577cf2045fec87344d7d89422fe6dfce62f/src/auto/configure#L6676

should be 
print("{}.{}".format(sys.version_info.major, sys.version_info.minor))
?

**Comment by brammool** [comment]
Yes, that is more reliable.  Using 3.1 for 3.10, 3.11, etc. might work, but it looks wrong.
