### ISSUE TITLE
Connect an lsp server to vim

### ISSUE THREAD

**Issue by SoilihBenSoilih** [vim/vim#8237]
Hello,

I hope you are well !
I have developed an LSP server for a developing programming language called **Typer** with `.typer` extension files
I have tested my server with emacs as a client, and I would like to try it on vim. My server starts up with the command
`typer-lsp-server`. With emacs, I used a _pipe connection_ which starts when opening a `.typer` file.
I don't have much experience with vim so I wouldn't say no to the details.
I would like to know how to use vim as an lsp client and get my server to work on vim as well.

Thank you very much, best to you!

**Comment by habamax** [comment]
Vim has no built-in lsp client facilities.

You should install plugins that make vim an lsp client:

* `vim-lsp` (pure vimscript)
* `vim-lsc` (pure vimscript)
* `youcompleteme` (python + compiled component)
* `coc.nvim` node.js
* probably more

And test you lsp server using one of them.

**Comment by SoilihBenSoilih** [comment]
but how to connect the server ?

**Comment by habamax** [comment]
> but how to connect the server ?

Connect using the way described in documentation of each plugin mentioned.

**Comment by SoilihBenSoilih** [comment]
ok ok, thank you !

**Comment by brammool** [comment]
Looks like this is not an issue
