### ISSUE TITLE
`filetype detect` causes memory leak

### ISSUE THREAD

**Issue by dunrix** [vim/vim#8240]
Invoking `filetype detect` command on a specific buffer causes *vim* process to start leak its resident memory and getting slower in responses. So far issue did manifested at *html* and *eruby* contents.

For example to demonstrate misbehavior:
1. put following content in a vim buffer
```
<!DOCTYPE html>
<html>

</html>
```
2. vim proces RSS is about 45 MB
3. repeatedly invoke in normal mode `filetype detect` command
4. observe vim process RSS grow with each invocation

After about 10 calls of `filetype detect` vim process memory has increased from 45MB to 200MB and responsiveness become significantly more clunky.

**Comment by dpelle** [comment]
I can't reproduce it using vim-8.2.2878 on Linux.

Which version of vim do you use? 
Can you automate the steps from a script to make sure we run the same steps as you by making sure you start vim with the `--clean`  option to make sure that it does not depend on a plugin?

**Comment by brammool** [comment]
I can see a little increas in RSS size when using "filetype detect" a few times, but soon it tops out and stops going up.  Even when using it a hundred times.
Note that RSS size increase is not a leak of any kind.  It may very well indicate use of virtual memory, not actual memory.
You may want to look into what alloc/free implementation is being used.

**Comment by dunrix** [comment]
**Update**

Just figured out I've tested reported behaviour with enabled plugins, although believed they were disabled in *.vimrc*. It stopped leaking when run with `--noplugin` option.

Now after adding plugins one-by-one, I did figured out it is an issue of [vim-rails](https://github.com/tpope/vim-rails), not stock vim.

I'm sorry for any possible inconvenience caused by this misleading report.

**Comment by dpelle** [comment]
@dunrix wrote:

> Now after adding plugins one-by-one, I did figured out it is an issue of vim-rails, not stock vim.

Even after installing the https://github.com/tpope/vim-rails plugin, I still could not reproduce the issue somehow using vim-8.2.2887. Maybe I'm missing something else.
