### ISSUE TITLE
cannot reset netrw_localrmdir command

### ISSUE THREAD

**Issue by zwhitchcox** [vim/vim#825]
I am running VIM 7.4, and netrw cannot delete a non-empty directory. When I try to delete a directory, I get this error:

```
**error** (netrw) unable to delete directory </Users/hitchza/source/sp/socketio-proxy-boilerplate/!
```

Even when I have reset the command with

```
let g:netrw_localrmdir = 'rm -rf'
```

It works when the directory is empty

**Comment by zwhitchcox** [comment]
So, it is actually reset, it still just doesn't work. I just rebuilt the current version of vim, and I still can't get it to work.

**Comment by cecamp** [comment]
Zane Hitchcox wrote:

> So, it is actually reset, it still just doesn't work. I just rebuilt
> the current version of vim, and I still can't get it to work.
> 
> Hello:

I see that there's an omission from netrw's help, which I'll fix in the
next release.  If your vim is version 7.4 and has patch#1109,
then vim's delete() command supercedes g:netrw_localrmdir's effect. 
However, just like system()+rmdir, delete() will not remove
a directory that is not empty.  Is your directory empty?

Regards,
Chip Campbell

**Comment by zwhitchcox** [comment]
No, the directory is not empty. The behavior I am trying to achieve is the ability to delete an empty directory though.

**Comment by ypresto** [comment]
We need to override the flag passed to `delete()'.

https://github.com/vim/vim/blob/95da136142628e06425f9d9eb2d1ca56a9e48feb/runtime/autoload/netrw.vim#L11274

```diff
-     if delete(rmfile,"d")
+     if delete(rmfile,"rf")
```

It think it is good to have vim config like `let g:netrw_local_delete_recursive=1`.

(The title should be "Ability to recursively delete directory".)

**Comment by vim-ml** [comment]
Yuya Tanaka (Vim Github Repository) wrote:
>
> We need to override the flag passed to `delete()'.
>
> https://github.com/vim/vim/blob/95da136142628e06425f9d9eb2d1ca56a9e48feb/runtime/autoload/netrw.vim#L11274
>
> - if delete(rmfile,"d")
> + if delete(rmfile,"rf")
>
> It think it is good to have vim config like |let 
> g:netrw_local_delete_recursive=1|.
>
> (The title should be "Ability to recursively delete directory".)
>
>
Its too easy to delete an entire directory and subdirectories 
accidentally.  That's why I never did it.

Chip Campbell

**Comment by AdamMomen** [comment]
It's not like the world will to end if we don't have this feature, but it's really nice to have.

**Comment by UnrealApex** [comment]
> It's not like the world will end if we don't have this feature, but it's really nice to have.

It is 2023 and I feel that this is the only thing that makes Netrw feel inferior to more modern file editors such as NERDTree.

**Comment by UnrealApex** [comment]
> Yuya Tanaka (Vim Github Repository) wrote:
> We need to override the flag passed to `delete()'. https://github.com/vim/vim/blob/95da136142628e06425f9d9eb2d1ca56a9e48feb/runtime/autoload/netrw.vim#L11274 - if delete(rmfile,"d") + if delete(rmfile,"rf") It think it is good to have vim config like |let g:netrw_local_delete_recursive=1|. (The title should be "Ability to recursively delete directory".)
> Its too easy to delete an entire directory and subdirectories accidentally.  That's why I never did it. Chip Campbell

@cecamp while it is possible, I doubt it would happen with the prompt. Perhaps Netrw could provide an additional warning that the folder is not empty?
