### ISSUE TITLE
Unexpected horizontal scroll using g$ in nowrap

### ISSUE THREAD

**Issue by epistularum** [vim/vim#8254]
**Describe the bug**
I'm editing a file that contains a mix of latin alphabet and japanese while using nowrap. Some lines experience a scroll when using g$ while some don't. The lines displaying an incorrect behaviour are distinguishable from the others by having a little gap right at the end of the screen.

**To Reproduce**
1. Enter vim, adjust number of columns to 160 and paste my [sample text](https://gist.github.com/epistularum/67d8859b0901e2fe6a991ba8d3b8a7a4).
2. Enable nowrap.
3. Press g$.
4. Lines 2, 4 and 5 ending in "心に", "百科" and "て記" respectively observe an unexpected horizontal scroll while other lines don't.

**Expected behavior**
g$ should move the cursor to the end of the line without scrolling.

**Screenshots**
The right end of the screenshot is the end of the vim window, notice the gap on some lines between the last character and the edge.
![image](https://user-images.githubusercontent.com/34507493/119426277-336bf300-bd09-11eb-8da3-2b46f53fed9d.png)

**Environment**
 - Vim version: 8.2.2845-1
 - OS: Manjaro 21.0.5
 - Terminal: Alacritty

**Additional context**
I'm using the "Noto Sans Mono CJK JP" font. I believe the current behaviour happens because this font isn't "truly" monospace as not all the characters have the same width. I assume this would be the case for most Japanese fonts?
See: https://github.com/googlefonts/noto-cjk/issues/67#issuecomment-217218192

**Comment by chrisbra** [comment]
so, have you tried with a default config (with no fancy font)?

**Comment by epistularum** [comment]
I'm not sure what you mean by no fancy font but I tried with a variety of fonts with the same result:
BitStream Vera Sans Mono, DejaVu Sans Mono, Droid Sans Mono, FreeMono, Inconsolata, Liberation Mono, Nimbus Mono PS,...

If you have any recommendation for a non-fancy font, I'll gladly try it out.

**Comment by k-takata** [comment]
In the first line, the 160th column is the first half of a full width character. When the cursor goes to the 160th column, the latter half of the cursor is now at the 161st column, then horizontal scroll occurs.
In the second line, the 160th column it the latter half of a full width character. The cursor doesn't exceed the 160th column. So, horizontal scroll doesn't occur.

It might be better to go to the 158-159th column in the first line.
