### ISSUE TITLE
Vim9: declaring lambda argument not enforced in "substitute()" replacement

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8259]
**Describe the bug**

In Vim9 script, declaring the lambda arguments is not enforced in the replacement expression of `substitute()`.

**To Reproduce**

Run this shell command:

    vim -Nu NONE +"vim9 echo substitute('aaa', '.*', () => 'bbb', '')"

`bbb` is echo'ed.

**Expected behavior**

Nothing is echo'ed.  This error is given:

    E118: Too many arguments for function: <lambda>1

Because, according to `:h vim9-lambda-arguments`, the number of arguments must match:

   > <							*vim9-lambda-arguments*
   > In legacy script a lambda could be called with any number of extra arguments,
   > there was no way to warn for not using them.  In Vim9 script the number of
   > arguments must match.  If you do want to accept any arguments, or any further
   > arguments, use "..._", which makes the function accept
   > |vim9-variable-arguments|.  Example: >
   >         var Callback = (..._) => 'anything'
   >         echo Callback(1, 2, 3)  # displays "anything"

Here, the lambda received a list of strings (one for each capturing group), but we didn't declare it:

    () => 'bbb'
    ^^
    ✘

I think Vim should tell us about this error.

**Environment**

 - Vim version: 8.2 Included patches: 1-2885
 - OS: Ubuntu 20.04.2 LTS
 - Terminal: XTerm(353)

**Additional context**

If we extract the lambda from outside `substitute()`, an error is correctly given:
```vim
vim9script
echo (() => 'bbb')(['aaa', '', '', '', '', '', '', '', '', ''])
```
    E118: Too many arguments for function: <lambda>1

Which is unexpected.  Unless there is some special code which makes Vim inspect the lambda's definition to decide whether or not it should send the list of capturing groups...  If so, this still looks inconsistent.

**Comment by brammool** [comment]
The documentation for substitute() mentions that the argument to the function is optional.  Perhaps it's not clear, but this means that when the function does not take an argument, the list of submatches isn't even created.  This is so that the overhead is reduced.

Thus this is working as intended.
