### ISSUE TITLE
vimtutor's instructions for editing _vimrc on Windows are wrong.

### ISSUE THREAD

**Issue by romainl** [vim/vim#8273]
**Describe the bug**
`vimtutor`'s instructions for editing `_vimrc` on Windows are wrong. It says:

    1. Start editing the "vimrc" file.  This depends on your system:
            :e ~/.vimrc             for Unix
            :e $VIM/_vimrc          for Windows

    2. Now read the example "vimrc" file contents:
            :r $VIMRUNTIME/vimrc_example.vim

    3. Write the file with:
            :w

But `$VIM` points to `C:\Program Files (x86)\Vim`, which is protected. The third step invariably results in `E212`, with no clear workaround.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `>vimtutor` on Windows.
2. Go to lesson 7.2.
3. Follow the instructions.
4. The file can't be written -> `E212` is thrown -> the lesson can't be successfully completed -> the user can't have a `_vimrc`.

**Expected behavior**
The user should be able to write their new `_vimrc` to disk.

**Environment (please complete the following information):**
 - Vim version: irrelevant
 - OS: Windows
 - Terminal: irrelevant

**Solution**
Replace:

    :e $VIM/_vimrc          for Windows

with:

    :e $HOME/_vimrc          for Windows

**Comment by habamax** [comment]
I don't remember if `$HOME` is defined in windows by default.

Win10 has `USERPROFILE` which is essentially a `HOME` but named differently. Older windows might not have even that.

**Comment by chrisbra** [comment]
I think vim has some custom code to construct `$HOME` from `$USERPROFILE` and `$HOMEDRIVE` and `$HOMEPATH`, see: https://github.com/vim/vim/blob/543467136f001708f4c63376ac5d18adde82db30/src/misc1.c#L1153-L1159

**Comment by romainl** [comment]
`$HOME` is indeed defined by default on Windows, which makes the suggested `:e $HOME\_vimrc` a practical command to use in this context.

For what it's worth, `~` works the same so one could even imagine `:e ~/_vimrc` which mimics the Unix instruction.

**Comment by k-takata** [comment]
Windows doesn't define `$HOME`, Vim does.

**Comment by brammool** [comment]
I'll change it to ~/_vimrc
