### ISSUE TITLE
In terminal mode <M-BS> does not erase the word before the cursor but enters this character ÿ (utf-8 0xFF)

### ISSUE THREAD

**Issue by aioiged** [vim/vim#8274]
**Describe the bug**
In terminal mode \<M-BS\> does not erase the word before the cursor but enters this character *ÿ* (utf-8 0xFF)

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim -u NONE`
2. Open a terminal `:ter`
3. Press '\<M-BS\>' (that is, Alt+Backspace)
4. The letter *y* with umlaut is written (*ÿ*, having code 0xFF in utf-8) 

**Expected behavior**
After step 3 above, the word or piece of word that precedes the cursor should be erased instead of writing a character.

**To Reproduce alternatively**
5. Run `vim -u NONE`
6. In command-line mode enter `:<C-V> <M-BS>`
7. In the command-line it appears *ÿ*

**Expected behavior**
After step 6 above '\<M-BS\>' should appear instead of *ÿ*.

**Environment:**
 - Vim version 
 ```
$ pacman -Q vim
vim 8.2.2859-2
```

 - OS: 
 ```
$ uname
MINGW64_NT-10.0-19043
```
```
$ cmd /c ver
Microsoft Windows [Version 10.0.19043.985]
```

 - Terminal: 
```
$ pacman -Q mintty
mintty 1~3.5.0-1
```

- Vim options are as follows

```
~
:set
--- Options ---
  helplang=en       noloadplugins         modified            scroll=26           ttyfast             ttymouse=xterm
  fileencodings=ucs-bom,utf-8,default,latin1
Press ENTER or type command to continue
```

- The followings are the terminal characteristics, should they be of any help.

```
$ stty -a
speed 38400 baud; rows 54; columns 194; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = ^Z; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; discard = ^O;
min = 1; time = 0;
-parenb -parodd cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc ixany imaxbel iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -tostop echoctl echoke -flusho
```

**Additional context**

1. The same letter is entered in insert mode, even if this is a minor problem for me because I never use Alt+Backspace in insert mode. I'm telling about it just for providing further symptoms.
2. It seems then that the terminal emulator is sending exactly what Vim expects, that is the key (<BS> 0x7F) OR'ed with 0x80, thus giving 0xFF. But then Vim prints it!
3. Backward word erasure can still be achieved in terminal mode by pressing "Esc" and then "Backspace"
4. Please note that downgrading to 

```
$ pacman -Q vim
vim 8.1.1234-1
```

the problem does not present itself.

**Comment by lacygoill** [comment]
Try to clear the terminal options `'t_TI'` and `'t_TE'`:

    set t_TI= t_TE=

**Comment by aioiged** [comment]
Just done, but I got no effect.

**Comment by lacygoill** [comment]
Make sure the command is run early.  That is, either write it in the vimrc, or execute it with `--cmd` (not with `+`):

    $ vim -Nu NONE --cmd 'set t_TI= t_TE=' +ter
                   ^---^

**Comment by aioiged** [comment]
Thanks. It works!
