### ISSUE TITLE
Implement a command for folding c-style multiline comments only

### ISSUE THREAD

**Issue by jclsn** [vim/vim#8278]
I have been searching the fold help page for a simple way to fold multiline comments so they look like ``/*...*/`` afterwards.
After reading all of that jazz it is still not clear to me. I have tried ``foldmethod=syntax`` and 

```
autocmd FileType cpp    setlocal foldmethod=expr foldexpr=getline(v:lnum)=~'^\\s*/\*'
```

Nothing works and I don't understand why there is not a simple command for this. 

This function also doesn't work.

```
set foldtext=MyFoldText()
function MyFoldText()
    let line = getline(v:foldstart)
    let sub = substitute(line, '/\*\|\*/\|{{{\d\=', '', 'g')
    return v:folddashes . sub
endfunction
```

**Comment by chrisbra** [comment]
> getline(v:lnum)=~'(?s)/\\*.*?\\*/'

what is the `(?s)` for?

>set foldtext=MyFoldText()

That only defines what to show for lines that are folded away.

**Comment by coldspark29** [comment]
@chrisbra That was a typo from something I had tried. I corrected it now. I can somehow work with markers now. It is a bit inconvenient though.

> That only defines what to show for lines that are folded away.
Then is also doesn't work. I just tried folding a multiple line comment manually.

**Comment by lacygoill** [comment]
Try this:
```vim
set foldmethod=expr foldexpr=MyFoldExpr()

def MyFoldExpr(): string
    var line: string = getline(v:lnum)
    if line =~ '^\s*/\*'
        return '>1'
    elseif line =~ '\*/\s*$'
        return '<1'
    endif
    return '='
enddef
```
If that doesn't work as you want, try to tweak the regexes.  When the function returns:

   - `>1`, it means that a fold of level 1 *starts* on this line.  When the function
   - `<1`, it means that a fold of level 1 *ends* on this line.  When the function
   - `=`, it means that the fold level of the line should be copied from the previous line

For more info, see [`:h fold-expr`](https://vimhelp.org/fold.txt.html#fold-expr).

**Comment by coldspark29** [comment]
@lacygoill Thanks, but it doesn't work either. I would not know what to change. The regexes seem right.

**Comment by coldspark29** [comment]
Found a solution:

```
set foldmethod=marker
set foldmarker=/*,*/
```

**Comment by lacygoill** [comment]
> it doesn't work either

Post a short sample file, and how you want the file to be folded.

For example, here are the first 21 lines in `src/evalfunc.c`:

    /* vi:set ts=8 sts=4 sw=4 noet:
     *
     * VIM - Vi IMproved	by Bram Moolenaar
     *
     * Do ":help uganda"  in Vim to read copying and usage conditions.
     * Do ":help credits" in Vim to see a list of people who contributed.
     * See README.txt for an overview of the Vim source code.
     */

    /*
     * evalfunc.c: Builtin functions
     */
    #define USING_FLOAT_STUFF

    #include "vim.h"

With the previously mentioned code, these lines are folded like this:

    +--  8 lines: vi:set ts=8 sts=4 sw=4 noet:-----------------------------------------------------------------------------

    +--  3 lines: evalfunc.c: Builtin functions----------------------------------------------------------------------------
    #define USING_FLOAT_STUFF

    #include "vim.h"

The first line is actually a fold containing the first comment:

    /* vi:set ts=8 sts=4 sw=4 noet:
     *
     * VIM - Vi IMproved	by Bram Moolenaar
     *
     * Do ":help uganda"  in Vim to read copying and usage conditions.
     * Do ":help credits" in Vim to see a list of people who contributed.
     * See README.txt for an overview of the Vim source code.
     */

The second line is actually a fold containing the second comment:

    /*
     * evalfunc.c: Builtin functions
     */

Tested by starting Vim with this shell command:

    vim -Nu NONE src/evalfunc.c -S <(cat <<'EOF'
        set foldmethod=expr foldexpr=MyFoldExpr()
        def MyFoldExpr(): string
            var line: string = getline(v:lnum)
            if line =~ '^\s*/\*'
                return '>1'
            elseif line =~ '\*/\s*$'
                return '<1'
            endif
            return '='
        enddef
    EOF
    )
