### ISSUE TITLE
Appending text in visual block mode doesn't work properly when cursor is moved

### ISSUE THREAD

**Issue by yegappan** [vim/vim#8288]
**Describe the bug**
When appending text in visual block mode, if the cursor is moved before the
start of the visual block, then incorrect text is inserted.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean`
2. Add the following text to an empty buffer.
        aaa
        bbb
        ccc
3. Execute the following commands:
       `gg$<C-V>2jA<Left>x<Esc>`

**Expected behavior**
The following lines are expected after the edit:
```
       aaxa
       bbxb
       ccxc
```

But the following lines are present after the edit:
```
       aaxa
       bbba
       ccca
```

The second and third lines are not correct.

**Environment (please complete the following information):**
 - Vim version 8.2.2911
 - OS: Ubuntu 21.04
 - Terminal: Gnome-terminal

Additional details:
A test for this is already added to the Test_visual_block_mode() function in test_visual.vim.

**Comment by vim-ml** [comment]
Hi,

On Sun, May 30, 2021 at 9:50 AM Yegappan Lakshmanan <
***@***.***> wrote:

> *Describe the bug*
> When appending text in visual block mode, if the cursor is moved before the
> start of the visual block, then incorrect text is inserted.
>
> *To Reproduce*
> Detailed steps to reproduce the behavior:
>
>    1. Run vim --clean
>    2. Add the following text to an empty buffer.
>    aaa
>    bbb
>    ccc
>    3. Execute the following commands:
>    gg$2jAx
>
>
As I didn't use the proper Github markdown, the special characters are not
shown here. The command to reproduce the bug is "gg$<C-V>2jA<Left>x<Esc>"
I have updated the issue in Github with the proper markdown now.

- Yegappan


>
>
> *Expected behavior*
> The following lines are expected after the edit:
> aaxa
> bbxb
> ccxc
>
> But the following lines are present after the edit:
> aaxa
> bbba
> ccca
>
> The second and third lines are not correct.
>
> *Environment (please complete the following information):*
>
>    - Vim version 8.2.2911
>    - OS: Ubuntu 21.04
>    - Terminal: Gnome-terminal
>
> Additional details:
> A test for this is already added to the Test_visual_block_mode() function
> in test_visual.vim.
>
>
>
