### ISSUE TITLE
Auto-close feature that doesn’t conflict with YCM and snippets

### ISSUE THREAD

**Issue by jclsn** [vim/vim#8294]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
There are many auto-close plugins available but all of them introduce bugs because they mess with the escape sequence. It would be nice to have a native auto-closing feature that does not have these problems.

**Describe the solution you'd like**
Auto-closing if parentheses and colons etc. as it is the case in modern IDEs.

**Comment by chrisbra** [comment]
can you please describe what problems you actually encounter that cannot be fixed in auto-closing plugins? This is a bit vague.

**Comment by k-takata** [comment]
I don't know what problems you are facing, but basically they should be fixed in the plugins. If it is not possible, please describe what function should be implemented in Vim to make the plugins don't conflict.

**Comment by coldspark29** [comment]
I guess you are right. It seems to be a YCM issue. I just tried the coc completion engine which doesn’t have this problem.
