### ISSUE TITLE
Vim script can overwrite builtin function

### ISSUE THREAD

**Issue by mattn** [vim/vim#8302]
`let g:.foo = 1` let `1` to global variable `foo`. And this way can overwrite builtin functions.

**Describe the bug**

`let g:.foo = 1` let `1` to global variable `foo`. And this way can overwrite builtin functions.

**To Reproduce**

```vim
let g:.trim = {x-> ' '..x..' '}
echo '['..trim(' foo ')..']'
```

This get `[  foo  ]`.

**Expected behavior**

`[foo]`

**Comment by mattn** [comment]
This is also wrong.
```vim
let g:['trim'] = {x-> ' '..x..' '}
echo '['..trim(' foo ')..']'
```

**Comment by mattn** [comment]
This should fix the issue.

```diff
diff --git a/src/userfunc.c b/src/userfunc.c
index f5d906302..e463d73cd 100644
--- a/src/userfunc.c
+++ b/src/userfunc.c
@@ -1436,6 +1436,12 @@ deref_func_name(
 
     cc = name[*lenp];
     name[*lenp] = NUL;
+
+    if (builtin_function(name, -1)) {
+	name[*lenp] = cc;
+	return name;
+    }
+
     v = find_var(name, &ht, no_autoload);
     name[*lenp] = cc;
     if (v != NULL)
```

**Comment by brammool** [comment]
Besides that check, it should not even be possible to add that variable in g: or s:

**Comment by brammool** [comment]
Actually, we cannot use builtin_function(), because in lambda's using a lower case name is possible.

**Comment by mattn** [comment]
@brammool Thank you. But still wrong.

```vim
call extend(g:, #{foo: { -> 'foo' }})
```

**Comment by mattn** [comment]
@brammool another degrade with this fix.

```
let s:trim = {x-> ' '..x..' '}
```
This makes error E704.

**Comment by mattn** [comment]
I prefer checking for the referencing to the symbol, Not checking for letting variables.

**Comment by brammool** [comment]
> @brammool another degrade with this fix.
> 
> ```
> let s:trim = {x-> ' '..x..' '}
> ```
> This makes error E704.

That looks correct, it should use "s:Trim".

Did this work OK before?  Then we might have to check this only in Vim9
script, where script-local variables can be used without s: prefix.

Actually, I cannot reproduce the error in legacy script.  And I do get
the error in Vim 9 script, looks OK to me.  Did you have some context to
trigger the error?

-- 
ARTHUR:  No, hang on!  Just answer the five questions ...
GALAHAD: Three questions ...
ARTHUR:  Three questions ...  And we shall watch ... and pray.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mattn** [comment]
```
:let s:.foo = { -> 'foo' }
:echo s:foo()
```
>Vim(let):E704: Funcref variable name must start with a capital: foo

**Comment by mattn** [comment]
```
:let g:s = s:
function! CallS(name)
  return s:[a:name]()
endfunction
:let g:s.foo = { -> 'foo' }
:echo CallS('foo')
```

**Comment by k-takata** [comment]
`:help E704` says:
```
<							*E704* *E705* *E707*
A Funcref variable must start with a capital, "s:", "w:", "t:" or "b:".  You
can use "g:" but the following name must still start with a capital.  You
cannot have both a Funcref variable and a function with the same name.
```
so, I think "s:" should be able to be followed by a lower letter.

And, I think that "s:" in this part should be changed to "l:"
https://github.com/vim/vim/commit/3d9c4eefe656ee8bf58c0496a48bd56bac180056#diff-3452ba3ede8c12266b78c613c3171f5a19f42244731749b3bc60072cdf45be46R2687-R2688
as follows:
```vim
  call assert_fails('let l:["trim"] = {x -> " " .. x}', 'E704:')
  call assert_fails('let l:.trim = {x -> " " .. x}', 'E704:')
```

**Comment by brammool** [comment]
> ```
> :let s:.foo = { -> 'foo' }
> :echo s:foo()
> ```
> >Vim(let):E704: Funcref variable name must start with a capital: foo

Looks like I missed the dot.

-- 
BRIDGEKEEPER: What is your favorite colour?
GAWAIN:       Blue ...  No yelloooooww!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
> `:help E704` says:
> ```
> <							*E704* *E705* *E707*
> A Funcref variable must start with a capital, "s:", "w:", "t:" or "b:".  You
> can use "g:" but the following name must still start with a capital.  You
> cannot have both a Funcref variable and a function with the same name.
> ```
> so, I think "s:" should be able to be followed by a lower letter.

In legacy script, yes.  But in Vim9 script a script-local variable can
be accessed without s:, so there we won't allow it.

But in Vim9 script assigning to s:.trim won't work, it tries to parse
".trim" as a type.  Same for s:['trim'].

 
> And, I think that "s:" in this part should be changed to "l:"
> https://github.com/vim/vim/commit/3d9c4eefe656ee8bf58c0496a48bd56bac180056#diff-3452ba3ede8c12266b78c613c3171f5a19f42244731749b3bc60072cdf45be46R2687-R2688
> as follows:
> ```vim
>   call assert_fails('let l:["trim"] = {x -> " " .. x}', 'E704:')
>   call assert_fails('let l:.trim = {x -> " " .. x}', 'E704:')
> ```

Except that this doesn't fail yet.

-- 
BRIDGEKEEPER: What is your favorite colour?
LAUNCELOT:    Blue.
BRIDGEKEEPER: Right.  Off you go.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
> ```
> :let g:s = s:
> function! CallS(name)
>   return s:[a:name]()
> endfunction
> :let g:s.foo = { -> 'foo' }
> :echo CallS('foo')
> ```

After the recent changes this also works correctly.  For legacy script
this is allowed, s:foo can be a function. For Vim9 script it gives the
E704 error.

-- 
BEDEVERE: How do you know so much about swallows?
ARTHUR:   Well you have to know these things when you're a king, you know.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
