### ISSUE TITLE
python version verify in auto/configure script 

### ISSUE THREAD

**Issue by mikhamikha** [vim/vim#8303]
is it correct variable?

6672: 
    if ${vi_cv_var_python3_version+:} false; then :

i can't compile  with --enable-python3interp=yes 
until change to
    if ${vi_cv_var_python3_version} false; then :

**Comment by k-takata** [comment]
What error is shown on what OS?

**Comment by chrisbra** [comment]
And what shell are you using?

**Comment by brammool** [comment]
> is it correct variable?
> 
> 6672: 
>     if ${vi_cv_var_python3_version+:} false; then :
> 
> i can't compile  with --enable-python3interp=yes 
> until change to
>     if ${vi_cv_var_python3_version} false; then :

The source code is: 
AC_CACHE_CHECK(Python version,vi_cv_var_python_version,
    [[vi_cv_var_python_version=`
	    ${vi_cv_path_python} -c 'import sys; print sys.version[:3]'`
    ]])

The "+:" is added by autoconf, thus it should be correct.
Do you have $vi_cv_var_python_version set somehow?

-- 
ROBIN:  (warily) And if you get a question wrong?
ARTHUR: You are cast into the Gorge of Eternal Peril.
ROBIN:  Oh ... wacho!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mikhamikha** [comment]
**brammol**, thanks! you are right!
