### ISSUE TITLE
Some issues if vim82 is renamed

### ISSUE THREAD

**Issue by lkintact** [vim/vim#8313]
**Describe the bug:**
Some issues with Vim if the vim82 folder is renamed.

**To Reproduce:**
1. Download Vim from [vim/vim-win32-installer](https://github.com/vim/vim-win32-installer/releases/download/v8.2.2920/gvim_8.2.2920_x86_signed.zip), unpack the archive.
2. Create a `_vimrc` file in the same folder as `vim82`, add a command to it, for example `:colorscheme desert`.
3. Run `gvim.exe --cmd "language messages English"`, make sure `_vimrc` is sourced.
4. Quit gVim.
5. Rename `vim82` to `vim82renamed`.
6. Run `gvim.exe --cmd "language messages English"` again. Note that this time `_vimrc` isn't sourced.
7. Quit gVim.
8. Rename `vim82renamed` to `[8.2.2920] vim82`.
9. Run `gvim.exe --cmd "language messages English"` once more. An error message pops up (username edited out):
```
Error detected while processing C:\Users\<user>\vim\[8.2.2920] 
vim82\defaults.vim[120]..C:\Users\<user>\vim\[8.2.2920] vim82\syntax\syntax.
vim:
line   42:
E216: No such group or event: filetypedetect BufRead
Error detected while processing C:\Users\<user>\vim\[8.2.2920] 
vim82\menu.vim:
line  185:
E121: Undefined variable: paste#paste_cmd
```
Click on `Ok`. gVim opens, but `_vimrc` isn't sourced again. Also, the main menu and the toolbar are absent.

**Expected behavior:**
`_vimrc` should be sourced at steps 6 and 9. There should be no error message at step 9, the main menu and the toolbar should be present.

**Environment:**
 - Vim version 8.2.2920
 - OS: Windows 10 Home 1803
 - Terminal: GUI.

**Additional context:**
If somebody wonders why I need to rename `vim82`: I usually keep several versions of Vim to be able to test new features and locate bugs. Each version (apart from the newest one) is located in a `[x.y.zzzz] vim82` folder -- this form is convenient because it lists the folders chronologically.

**Comment by lacygoill** [comment]
You might need to update the environment variables `$VIM` and `$VIMRUNTIME` as well as the Vim option `'helpfile'`.  Untested, but try to adapt the paths in this snippet (from Linux to Windows):

    let $VIMRUNTIME = '/new/path/to/vim82renamed/'
    let $VIM = $VIMRUNTIME
    set rtp-=~/.vim
    set rtp^=$VIMRUNTIME
    set rtp^=~/.vim
    set helpfile=$VIMRUNTIME/doc/help.txt

**Comment by k-takata** [comment]
The name "vim{version}" is special. See `:help $VIM` for detail.

I often use the following directory structure to test several versions of Vim:
```
vim-8.2.2929\
├─gvim.exe
├─vim.exe
├─.vimrc
└─runtime\
```

**Comment by lkintact** [comment]
Thank you, @k-takata  and @lacygoill. I don't know why I was absolutely sure the `[x.y.zzzz] vim82` form had worked perfectly earlier. I think the issue can be closed.
