### ISSUE TITLE
[Support request] Is there a way to globally remap hjkl?

### ISSUE THREAD

**Issue by jclsn** [vim/vim#8319]
I am currently learning to touch type and found that the hjkl keys are getting in the way of it. I have been trying to remap them with

```
noremap ö l
noremap l k
noremap k j
noremap j h
```
for my German keys, but then it breaks commands like ``Ctrl + w + j`` etc. So is there a way to globally remap they keys without having to change every single command?

**Comment by tonymec** [comment]
I'm not sure, but in any case, "real" hjkl are needed for typing German, and ought to exist on a QWERTZ keyword.

You might find the answer to your question under either `:help mbyte-keymap' (which tells how to customize your keyboard to keep unchanged in Normal mode and the same-or-different in Insert mode) or `:help 'langmap'` (which tells how to do the opposite, e.g. how to use some Latin keyboard in Normal mode if your locale is e.g. Greek).

You may have to need some trial-and-error before you reach a configuration suiting your taste.

**Comment by chrisbra** [comment]
> It is very unconvenient to switch from the touch type finger resting position which is jklö to hjkl when switching from insert to normal mode. So I want to map those to the touch type position. This way I would make less mistakes.

I don't understand the request. You don't switch the keys, you use the normal touch typing position, which is `jklö` and move your right finger to the left if you need the `h`. That is the normal way I believe.

**Comment by coldspark29** [comment]
I guess I have to unlearn having my fingers on ``hjkl`` constantly then

**Comment by brammool** [comment]
"and move your right finger to the left if you need the h"  that would be the index finger on the right hand.

**Comment by chrisbra** [comment]
ah yes, in German that's the "pointer" finger :)
