### ISSUE TITLE
Indentation for paragraphs in html.vim

### ISSUE THREAD

**Issue by ghost** [vim/vim#8322]
```
<p>
| < cursor here, when press jO in normal mode. NOT WORKING INDENTATION, but should by default.
</p>
```
```
<div>
(indent setting) | < cursor here, when press jO in normal mode, WORKS
</div>
```
Need to add an indent with paragraph by default like any other tags. It's convention now, my format linters correct that.

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 16 2021 09:37:15)
Included patches: 1-2856

**Comment by brammool** [comment]
The problem with <p> is that it can also be used like this:
```
<p>
paragraph with text
<p>
another paragraph
```

It's hard to tell if the </p> is following or not.
