### ISSUE TITLE
non deterministic behavior when querying current mode

### ISSUE THREAD

**Issue by pierreganty** [vim/vim#8323]
**Describe the bug**

When querying the mode, vim sometimes behaves non-deterministically.
I tweaked an existing test that reliably reproduce the problem.

**To Reproduce**
Detailed steps to reproduce the behavior:
`make test_mapping` with the modified `Test_motionforce_omap()` given below

**Expected behavior**
The second ` call assert_equal('no', g:m)` should not fail.

**Environment (please complete the following information):**
 - Vim version : v8.2.2932
 - OS: macOS 11.3.1
 - Terminal: Terminal.app

**Additional context**
Here is the modified version of `Test_motionforce_omap()` for which the assertion fails.
I deleted the `cursor`, `setline` and  the `assert_equal` calls  thereof.
I repeated subtest `"1)` after `"2)`.
```viml
func Test_motionforce_omap()
  func GetCommand()
    let g:m=mode(1)
    let [g:lnum1, g:col1] = searchpos('-', 'Wb')
    if g:lnum1 == 0
        return "\<Esc>"
    endif
    let [g:lnum2, g:col2] = searchpos('-', 'W')
    if g:lnum2 == 0
        return "\<Esc>"
    endif
    return ":call Select()\<CR>"
  endfunc
  func Select()
    call cursor([g:lnum1, g:col1])
    exe "normal! 1 ". (strlen(g:m) == 2 ? 'v' : g:m[2])
    call cursor([g:lnum2, g:col2])
    execute "normal! \<BS>"
  endfunc
  new
  onoremap <buffer><expr> i- GetCommand()
  " 1) default omap mapping
  %d_
  norm di-
  call assert_equal('no', g:m)
  " 2) forced characterwise operation
  %d_
  norm dvi-
  call assert_equal('nov', g:m)
  " 1) default omap mapping
  %d_
  norm di-
  call assert_equal('no', g:m)
  " 3) forced linewise operation
  %d_
  norm dVi-
  call assert_equal('noV', g:m)
  " 4) forced blockwise operation
  %d_
  exe "norm d\<C-V>i-"
  call assert_equal("no\<C-V>", g:m)
  bwipe!
  delfunc Select
  delfunc GetCommand
endfunc
```

**Comment by lacygoill** [comment]
Simplified MWE:
```vim
vim9script
ono <expr> i- execute('g:mode = mode(1)')->slice(0, 0)
feedkeys('dvi-', 'x')
assert_equal('nov', g:mode)
feedkeys('di-', 'x')
assert_equal('no', g:mode)
echom v:errors
```
    ['command line..script ... line 6: Expected ''no'' but got ''nov''']

**Comment by lacygoill** [comment]
It looks similar to these issues:

   - <https://github.com/vim/vim/issues/3021>
   - <https://github.com/vim/vim/issues/3678>
   - <https://github.com/vim/vim/issues/6350>

BTW, the latter two are duplicates of the first one.

However, there is a twist in the current issue.  Pressing `<Esc>` or a no-op doesn't help (not surprising considering the `x` flag passed to `feedkeys()`).  It does in the previously mentioned issues.
