### ISSUE TITLE
Vim9: cannot use float in replacement argument of "substitute()" function call

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8331]
**Describe the bug**

In Vim9 script, we cannot use a float in the replacement argument of a `substitute()` function call.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        'the float is '
            ->substitute('$', () => 1.23, '')
            ->setline(1)
    EOF
    )

`E806` is raised:

    E806: using Float as a String

**Expected behavior**

No error is raised.  The line in the buffer is replaced with:

    the float is 1.23

**Environment**

 - Vim version: 8.2 Included patches: 1-2946
 - OS: Ubuntu 20.04.2 LTS
 - Terminal: XTerm(353)

**Additional context**

In a substitution command, it is allowed to use a float:
```vim
vim9script
'the float is '->setline(1)
s/$/\=1.23/
print
```
    the float is 1.23

---

In a substitution function call, it is allowed to use any simple type in the replacement argument.
Like a number:
```vim
vim9script
'the number is '
    ->substitute('$', () => 123, '')
    ->setline(1)
```
    the number is 123

Or a boolean:
```vim
vim9script
'the boolean is '
    ->substitute('$', () => true, '')
    ->setline(1)
```
    the boolean is true

Or a special:
```vim
vim9script
'the special is '
    ->substitute('$', () => null, '')
    ->setline(1)
```
    the special is null

---

This seems inconsistent.  A float is also a simple type, which is why Vim doesn't complain in a concatenation:
```vim
vim9script
echo 'the float is ' .. 1.23
```
If Vim is ok to use any simple type in a concatenation – which includes a float – as well as in a substitution command, then I would expect it's ok to use any simple type in a substitution function call.  Right now, Vim seems to make an exception for a float for no obvious reason.

**Comment by brammool** [comment]
> **Describe the bug**
> 
> In Vim9 script, we cannot use a float in the replacement argument of a `substitute()` function call.
> 
> **To Reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(cat <<'EOF'
>         vim9script
>         'the float is '
>             ->substitute('$', () => 1.23, '')
>             ->setline(1)
>     EOF
>     )
> 
> `E806` is raised:
> 
>     E806: using Float as a String
> 
> **Expected behavior**
> 
> No error is raised.  The line in the buffer is replaced with:
> 
>     the float is 1.23

Looks like it has been like this for a very long time.  It does look
inconsistent that a number is accepted, but a float is not.  I think
there is no problem with allowing both.

> This seems inconsistent.  A float is also a simple type, which is why
> Vim doesn't complain in a concatenation:
> ```vim
> vim9script
> echo 'the float is ' .. 1.23
> ```

That's not a very good reason, the ".." implies using a string, thus
more conversion is acceptable.

> If Vim is ok to use any simple type in a concatenation – which
> includes a float – as well as in a substitution command, then I would
> expect it's ok to use any simple type in a substitution function call.
> Right now, Vim seems to make an exception for a float for no obvious
> reason.

I'm a bit careful allowing too much, but if a number can be used a float
should also be OK.

-- 
The MS-Windows registry is no more hostile than any other bunch of state
information... that is held in a binary format... a format that nobody
understands... and is replicated and cached in a complex and largely
undocumented way... and contains large amounts of duplicate and obfuscated
information...  (Ben Peterson)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
