### ISSUE TITLE
bufload() occurs E325 error when swap file exists

### ISSUE THREAD

**Issue by thinca** [vim/vim#8333]
**Describe the bug**

`bufload()` occurs E325 error when swap file exists.

`:help bufload()` says:

```
		If there is an existing swap file for the file of the buffer,
		there will be no dialog, the buffer will be loaded anyway.
```

`E325` is not a dialog, but it stops the running of the script.
I guess `there will be no dialog` means scripts keep running without any user interaction.
So I thinks this behavior is not expected.

**To Reproduce**

Detailed steps to reproduce the behavior:
1. Run `vim --clean test.txt`
2. Open other terminal
3. Run `vim --clean`
4. Execute `:call bufload(bufnr('test.txt', 1))` in second Vim

**Expected behavior**

`E325` does not occurred.

**Screenshots**

![image](https://user-images.githubusercontent.com/20474/120922765-ebd06880-c705-11eb-9012-440564436e0b.png)

**Environment (please complete the following information):**
 - Vim version 8.2.2948
 - OS: Arch Linux
 - Terminal: Windows Terminal and tmux 3.2

**Additional context**
Nothing

**Comment by brammool** [comment]
I'm not sure we want to change this.  You can use ":silent!" to not get the error.
You can also use try/catch, but the "Found a swap file" message will still show.

**Comment by thinca** [comment]
OK.  Thank you.
