### ISSUE TITLE
Allow sign_define to set a default value for the sign priority

### ISSUE THREAD

**Issue by mfussenegger** [vim/vim#8334]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

Plugins authors can currently tell users that they can override a sign definition to customize the text, or highlight groups. But if they want to allow users to customize the priority of signs they need to provide a separate custom setting.

It would be nice if users could set the default priority as part of a sign definition.

**Describe the solution you'd like**

- Extend the `dict` argument of `sign_define` to take a `priority` option.
- Change `sign_place` to lookup the `priority` value from the definition if there is no `priority` property within the `dict` argument.

**Describe alternatives you've considered**

The plugin can expose a custom setting to configure the sign priority and uses it whenever the plugin calls `sign_place`.

---

(I could create a PR to make this change, just wanting to ensure the feature itself would be accepted)

**Comment by brammool** [comment]
Adding a priority item to sign_define() can be useful.  If you can make a PR that would be good.
