### ISSUE TITLE
Vim9: putting line break before `->` for method call and white spaces after it may cause Vim to hang

### ISSUE THREAD

**Issue by obcat** [vim/vim#8341]
**Describe the bug**

In Vim9 script, putting a line break before `->` for a method call and white spaces after it may cause Vim to hang.

**To Reproduce**

1. Run `vim --clean`.

2. Source this script:

    ```vim
    vim9script
    
    echo [3, 1, 2]
    -> sort()
    ```

    Vim hangs.

**Expected behavior**

Vim does not hang. `[1, 2, 3]` is echoed.

**Environment**

 - Vim 8.2.2929
 - macOS Catalina (version 10.15.7)
 - iTerm2

**Comment by Shane-XB-Qian** [comment]
try:
```
vim9script
echo [3, 1, 2]
	->sort()
```
looks it make sense if no 'indent' or no 'end mark' e.g ';' then failed.
though/but:
```
vim9script
echo [3,1,2]->sort()
```
// E1069
not sure why here must have 'white space' in list items......... looks vim9 became much more strict. :-)

**Comment by Shane-XB-Qian** [comment]
```
skipwhite (q=q@entry=0x5555558d5980 "\t-> sort()") at charset.c:1470
1470		++p;
```
// dead loop ?
```
    while (VIM_ISWHITE(*p)) // skip to next non-white
	++p;
```

**Comment by obcat** [comment]
@Shane-XB-Qian Thanks for investigating.

> ```
> vim9script
> echo [3,1,2]->sort()
> ```
> 
> // E1069
> not sure why here must have 'white space' in list items......... looks vim9 became much more strict. :-)

Vim9 requires proper use of white space in many places. I guess it's to make parsing easier. Please see `:h vim9` `/^White space`.

@brammool Thanks for fixing! I'm looking forward to the official release of Vim9;)
