### ISSUE TITLE
vim9script and getchar

### ISSUE THREAD

**Issue by smekkley** [vim/vim#8343]
getchar() seems to return string or number, however, with vim9script when I get string, I can't do anything with it because it complains that it cannot compare number with string. 
The one from :help doesn't work, for example. I tried casting but it still complains the same. It'd be nice if there is a feature to disable type checking, especially if it can improve performance. 

```
			var c = getchar()
			if c == "\<LeftMouse>" && v:mouse_win > 0
			  exe v:mouse_win . "wincmd w"
			  exe v:mouse_lnum
			  exe "normal " . v:mouse_col . "|"
			endif
```

The following is a workaround, if anybody wants to suppress typechecking in comparison.
```
static isntype_T get_compare_isn(exprtype_T exprtype, vartype_T type1, vartype_T type2) {
    return ISN_COMPAREANY;
}
```

**Comment by brammool** [comment]
> getchar() seems to return string or number, however, with vim9script
> when I get string, I can't do anything with it because it complains
> that it cannot compare number with string. 
> The one from :help doesn't work, for example. I tried casting but it
> still complains the same. It'd be nice if there is a feature to
> disable type checking, especially if it can improve performance. 
> 
> ```
> 			var c = getchar()
> 			if c == "\<LeftMouse>" && v:mouse_win > 0
> 			  exe v:mouse_win . "wincmd w"
> 			  exe v:mouse_lnum
> 			  exe "normal " . v:mouse_col . "|"
> 			endif
> ```

Yeah, that getchar() sometimes returns a number and sometimes a string
doesn't agree with type checking.

How about adding getcharstr(), which always returns a string?  An empty
string if no character is available.

-- 
People who want to share their religious views with you
almost never want you to share yours with them.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by smekkley** [comment]
It's like a generic prompt for a buffer that sends only string to job, but handle commands in vim9. I'll try replacing with getcharstr(). Thanks!  

```
    while true
        var input = getchar()
        var input_type = type(input)
        if input_type != 0
            if input == "\<Down>"
                norm j
        else
            if input < 32
                if nr2char(input) == "\<C-k>"
                    norm k
            else
                   handle-nomarl-character.
       ....
```

**Comment by chrisbra** [comment]
that does not exist yet

**Comment by smekkley** [comment]
Ah sorry, misread your comment.
getcharstr() is great idea, I think. It'll make my code cleaner.

**Comment by smekkley** [comment]
So fast, thanks a lot @brammool !
