### ISSUE TITLE
Cannot highlight end-of-line with matchaddpos()

### ISSUE THREAD

**Issue by markonm** [vim/vim#8348]
**To Reproduce**
1. Run `vim --clean`
2. Execute `:put='test'`
3. Execute `:call matchaddpos('Search', [[2,5]])`
4. EOL is not highlighted

**Expected behavior**
EOL should be highlighted.

**Environment**
 - Vim version 8.2.2961
 - OS: Ubuntu 18.04, Windows 10 20H2, WSL
 - Terminal: GUI, xterm, cmd.exe

**Comment by brammool** [comment]
Hmm, I don't think a match like this every highlights anything but actual text.

**Comment by markonm** [comment]
It works fine when `'list'` is set and `'listchars'` contains `'eol:c'`. Other entries of `'listchar'` don't have such limitation.

 I'll close the issue since it is not considered a bug.
