### ISSUE TITLE
glob() and globpath() do not honor wildignorecase

### ISSUE THREAD

**Issue by josuf107** [vim/vim#8350]
**Describe the bug**
When wildignorecase is on, glob() and globpath() don't seem to match files with different case. The docs for glob() say "                'wildignorecase' always applies" so one might expect glob() to honor the flag.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Create file README.txt
2. Run `vim --clean`
3. `:set wildignorecase`
4. `:echo glob('readme.txt')`
5. `:echo globpath('.', 'readme.txt')`

**Expected behavior**
I would expect this to output "README.txt" and "./README.txt" respectively, as it does when I issue `:echo glob('README.txt')` and `:echo globpath('.', 'README.txt')`, but the results are empty.

**Environment (please complete the following information):**
 - Vim version:
 
     VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun  9 2021 11:53:49)
    Included patches: 1-2966
    Compiled by jbarratt@jbarratt
    Huge version without GUI.  Features included (+) or not (-):
    +acl               +cryptv            +fork()            +modify_fname      +persistent_undo   +syntax            +visualextra
    +arabic            +cscope            +gettext           +mouse             +popupwin          +tag_binary        +viminfo
    +autocmd           +cursorbind        -hangul_input      -mouseshape        +postscript        -tag_old_static    +vreplace
    +autochdir         +cursorshape       +iconv             +mouse_dec         +printer           -tag_any_white     +wildignore
    -autoservername    +dialog_con        +insert_expand     -mouse_gpm         +profile           -tcl               +wildmenu
    -balloon_eval      +diff              +ipv6              -mouse_jsbterm     -python            +termguicolors     +windows
    +balloon_eval_term +digraphs          +job               +mouse_netterm     -python3           +terminal          +writebackup
    -browse            -dnd               +jumplist          +mouse_sgr         +quickfix          +terminfo          +X11
    ++builtin_terms    -ebcdic            +keymap            -mouse_sysmouse    +reltime           +termresponse      +xfontset
    +byte_offset       +emacs_tags        +lambda            +mouse_urxvt       +rightleft         +textobjects       -xim
    +channel           +eval              +langmap           +mouse_xterm       -ruby              +textprop          -xpm
    +cindent           +ex_extra          +libcall           +multi_byte        +scrollbind        +timers            +xsmp_interact
    +clientserver      +extra_search      +linebreak         +multi_lang        +signs             +title             +xterm_clipboard
    +clipboard         -farsi             +lispindent        -mzscheme          +smartindent       -toolbar           -xterm_save
    +cmdline_compl     +file_in_path      +listcmds          +netbeans_intg     -sound             +user_commands
    +cmdline_hist      +find_in_path      +localmap          +num64             +spell             +vartabs
    +cmdline_info      +float             -lua               +packages          +startuptime       +vertsplit
    +comments          +folding           +menu              +path_extra        +statusline        +virtualedit
    +conceal           -footer            +mksession         -perl              -sun_workshop      +visual
       system vimrc file: "$VIM/vimrc"
         user vimrc file: "$HOME/.vimrc"
     2nd user vimrc file: "~/.vim/vimrc"
          user exrc file: "$HOME/.exrc"
           defaults file: "$VIMRUNTIME/defaults.vim"
      fall-back for $VIM: "/usr/local/share/vim"
    Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -O2 -fno-strength-reduce -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
    Linking: gcc -L/usr/local/lib -Wl,--as-needed -o vim -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE -lm -ltinfo -ldl

 - OS: Ubuntu 18.04
 - Terminal:.GNOME Terminal

**Comment by chrisbra** [comment]
I believe this only works, if there is an actual `wildcard` in your pattern. So just add a `*` to your pattern.

**Comment by josuf107** [comment]
Hmm okay that seems a bit unexpected but does make sense (you only get wildignorecase if you have wildcarding). It might be worth mentioning that in the docs? Also globpath() doesn't work the same way as glob() in this regard (that is, when wildignorecase is set `glob('readme.txt*')` works but `globpath('.', 'readme.txt*')`does nott). Is it worth either updating the docs for `glob()` (I'd be willing to take a shot) or addressing the issue in `globpath()`?

**Comment by brammool** [comment]
> Hmm okay that seems a bit unexpected but does make sense (you only get
> wildignorecase if you have wildcarding). It might be worth mentioning
> that in the docs? Also globpath() doesn't work the same way as glob()
> in this regard (that is, when wildignorecase is set
> `glob('readme.txt*')` works but `globpath('.', 'readme.txt*')`does
> nott). Is it worth either updating the docs for `glob()` (I'd be
> willing to take a shot) or addressing the issue in `globpath()`?

I would call it a bug.  There is an optimization that when no wildcards
are found, the name is matched directly.  When 'wildignorecase' is set
then case should be ignored also without wildcards.

-- 
BODY:        I'm not dead!
CART DRIVER: 'Ere.  He says he's not dead.
LARGE MAN:   Yes he is.
BODY:        I'm not!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by josuf107** [comment]
Okay so I originally thought this was the same issue, but we actually have two different ones:
* `glob()` doesn't honor 'wildignorecase' unless wildcards appear (this is a bug)
* `globpath()` never honors 'wildignorecase'. Is this considered a bug? The docs for `globpath()` don't mention 'wildignorecase', but since the expectation is that it means the same thing as `glob()` for each directory given, I would expect it to observe 'wildignorecase' the way `glob()` does. If this is a bug, let me know if I should create a separate issue or leave these together.
