### ISSUE TITLE
Extra cursor-down when calling macro from vim file

### ISSUE THREAD

**Issue by xvim64** [vim/vim#8357]
**Describe the bug**
There is extra cursor-down when @b from vim file
let @b = ':echo "hello world!"^M'

**To Reproduce**
1. vim --clean
2. :w t.vim
3. input [ let @b = ':echo "hello world!"^M' ]
4. :w t.vim
5. so %
5. @b  <--  cursor-down
6. @b  <--  cursor-down
7. @b  <--  cursor-down

**Expected behavior**
No cursor-down when @b

**Screenshots**
![output](https://user-images.githubusercontent.com/83569599/121519527-c5277000-ca2c-11eb-91a6-e9b5cb284bc1.gif)

**Environment (please complete the following information):**
 - vim 8.2.2968
 - Windows 10 21H1 19043.1052

**Additional context**
whend adding "^[" after "^M"  ( -->  let @b = ':echo "hello world!"^M^[' ) there is no extra cursor-down

**Comment by brammool** [comment]
The problem is that the CR at the end makes the register linewise and an extra line break will be added.
You can use this instead: ```let @b = ":echo 'hello world!'\n"```

**Comment by xvim64** [comment]
I have changed '^M' to "\n"

Thanks a lot @brammool !
