### ISSUE TITLE
exe 'messages' does not work when called from job_start callback

### ISSUE THREAD

**Issue by neowit** [vim/vim#836]
When async job is executed via `job_start` the only feedback user can see while job is running is messages in status line.
When job is complete it may be necessary to draw attention to all messages (pushed via `echomsg`) in `messages` window. 
Unfortunately calling `:messages` or `exe "messages"` from job_start callback does not seem to have any effect.

Steps to reproduce:
- Given the file `demo.vim`

``` vim
function! MyCallback(channel) 
    echomsg "async 1"
    echomsg "async 2"
    echomsg "async 3"
    exe "messages"
endfunction

function! Messages_Async()
    call job_start("ping -c 1 google.com", {"close_cb": "MyCallback"})
endfunction    

function! Messages_Sync()
    echomsg "sync 1"
    echomsg "sync 2"
    echomsg "sync 3"
    exe "messages"
endfunction    
```

vim -u NONE -U NONE -S demo.vim

Test 1:
`:call Messages_Sync()`

Result (works as expected) - `messages` window opens and displays

> ...
> sync 1
> sync 2
> sync 3

Test 2:
`:call Messages_Async()`

Expected result - messages window opens and displays:

> ...
> async 1
> async 2
> async 3

Actual result - nothing happens, `messages` window does not open

`:version`
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May 16 2016 09:38:30)
MacOS X (unix) version
Included patches: 1-1830
Compiled by Homebrew

**Comment by brammool** [comment]
Andrey Gavrikov wrote:

> When async job is executed via `job_start` the only feedback user can
> see while job is running is messages in status line.  When job is
> complete it may be necessary to draw attention to all messages (pushed
> via `echomsg`) in `messages` window. 
> Unfortunately calling `:messages` or `exe "messages"` from job_start
> callback does not seem to have any effect.

After invoking the callback Vim redraws the window, if needed.
But adding a sleep after "messages" doesn't help.  Perhaps the messages
are overwriting each other (no scroll up).

Not sure if you really want to do this, the user may be doing something
that should not be interrupted by a list of messages.  The callback
functions are not really intended to output a list of messages, that
would mess up the screen.

> Steps to reproduce:
> - Given the file `demo.vim`
> 
> ``` vim
> function! MyCallback(channel) 
>     echomsg "async 1"
>     echomsg "async 2"
>     echomsg "async 3"
>     exe "messages"
> endfunction
> 
> function! Messages_Async()
>     call job_start("ping -c 1 google.com", {"close_cb": "MyCallback"})
> endfunction    
> 
> function! Messages_Sync()
>     echomsg "sync 1"
>     echomsg "sync 2"
>     echomsg "sync 3"
>     exe "messages"
> endfunction    
> ```
> 
> vim -u NONE -U NONE -S demo.vim
> 
> Test 1:
> `:call Messages_Sync()`
> 
> Result (works as expected) - `messages` window opens and displays
> 
> > ...
> > sync 1
> > sync 2
> > sync 3
> 
> Test 2:
> `:call Messages_Async()`
> 
> Expected result - messages window opens and displays:
> 
> > ...
> > async 1
> > async 2
> > async 3
> 
> Actual result - nothing happens, `messages` window does not open
> 
> `:version`
> VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May 16 2016 09:38:30)
> MacOS X (unix) version
> Included patches: 1-1830
> Compiled by Homebrew

There is no such thing as a messages window, the messages are displayed
on the screen.

## 

A)bort, R)etry, D)o it right this time

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by neowit** [comment]
> There is no such thing as a messages window, the messages are displayed on the screen.  

Sorry, I knew my terminology was off, but was not sure what to call that "split" which pops up at the bottom when one invokes `:messages` command.

> The callback functions are not really intended to output a list of messages, that would mess up the screen.

Fair enough. Thank you for the clarification.

Is there a recommended way of showing job result to user in cases where it is not suitable for quickfix. e.g. job completed with multi line information such as: 

> No of tests complete 
> Code coverage per test/file
> overall code coverage

I am guessing this could be pushed in a separate buffer (split) which opens up upon job completion, but in this case every plugin developer would have to come up with their own solution/code to this.

**Comment by brammool** [comment]
> > There is no such thing as a messages window, the messages are
> > displayed on the screen.  
> 
> Sorry, I knew my terminology was off, but was not sure what to call
> that "split" which pops up at the bottom when one invokes `:messages`
> command.
> 
> > The callback functions are not really intended to output a list of messages, that would mess up the screen.
> 
> Fair enough. Thank you for the clarification.
> 
> Is there a recommended way of showing job result to user in cases
> where it is not suitable for quickfix. e.g. job completed with multi
> line information such as: 
> 
> > No of tests complete 
> > Code coverage per test/file
> > overall code coverage
> 
> I am guessing this could be pushed in a separate buffer (split) which
> opens up upon job completion, but in this case every plugin developer
> would have to come up with their own solution/code to this.

Using a separate buffer in a window seems like a good solution.
Especially if your Vim has many lines/columns.  Anything else would be
interruptive.

I'm afraid a generic solution would be hard to come up with.  There is
no standard way to use Vim.

If you only have a short status text it could go in the status line.

## 

Me?  A skeptic?  I trust you have proof.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by neowit** [comment]
Thank you for the clarification. Good to know.

Closing this issue since my original "problem" turned out to be expected behaviour.

Thanks for your help.
