### ISSUE TITLE
Incorrect UTF-8 displaying

### ISSUE THREAD

**Issue by Glamhoth** [vim/vim#8363]
**Describe the bug**
Somewhere between versions 8.2.0814 and 8.2.1704 an encoding bug was introduced. In version 0814 every UTF-8 character was displaying properly like that:
![image](https://user-images.githubusercontent.com/5027115/121656197-8bdc1800-ca9f-11eb-9e9c-ac945fc1092e.png)
![image](https://user-images.githubusercontent.com/5027115/121656360-b0d08b00-ca9f-11eb-99f3-14a7216da090.png)

but after upgrading to 1704 (and still present in 2891)
![image](https://user-images.githubusercontent.com/5027115/121656465-ca71d280-ca9f-11eb-86da-c2176259fa45.png)
![image](https://user-images.githubusercontent.com/5027115/121656648-fee58e80-ca9f-11eb-8ae7-e22c81b7f4b3.png)

I also noticed that reloading file to a different encoding, for example by running
`:e ++enc=utf16`
and then back to UTF-8
`:e ++enc=utf8`
fixes that opened file.

**To Reproduce**
1. Start Vim in version >=8.2.1704
2. Try to type a UTF-8 character (e.g. « by pressing alt-gr and 9) or open a file that contains one

**Expected behavior**
Characters should be displayed properly.

**Environment (please complete the following information):**
 - Vim version: 8.2.2891
 - OS: Arch Linux, kernel 5.12.8
 - Terminal: st

**Comment by Glamhoth** [comment]
#8075 seems to tackle the same issue

**Comment by chrisbra** [comment]
could you bisect the vim patch?

**Comment by brammool** [comment]
What is your 'encoding' set to?  Does it change between the Vim versions you tried?
When editing a file , what is 'fileencoding' set to?  Does it change when you use different ++enc arguments?
Does typing CTRL-L help at all?
Did you start Vim with "vim --clean" ?

**Comment by Glamhoth** [comment]
>What is your 'encoding' set to? Does it change between the Vim versions you tried?
It's (correctly) set to UTF-8, it doesn't change between versions.

>When editing a file , what is 'fileencoding' set to?
It's also (correctly) set to UTF-8.

>Does it change when you use different ++enc arguments?
>Does typing CTRL-L help at all?
Actually, yes! It seems that any buffer/screen refresh helps (so there is actually no need to change encodings like i mentioned in the issue, just 'rereading' is enough).

>Did you start Vim with "vim --clean" ?
Yes, I even deleted .vim directory and .vimrc altogether to be sure.

**Comment by jottkaerr** [comment]
What does `:verbose set fencs?` say?

**Comment by Glamhoth** [comment]
Okay, I just tried a different terminal (Alacritty) and everything works as it should, so it has to be a problem with st.

>What does :verbose set fencs? say?
fileencodings=ucs-bom,utf-8,default,latin1

**Comment by chrisbra** [comment]
so does an `:au VimEnter * refresh!` help? What about `:set t_u7=` in your .vimrc?

**Comment by Glamhoth** [comment]
>so does an :au VimEnter * refresh! help

`au BufEnter * redraw!` helps

>What about :set t_u7= in your .vimrc?

This does work too

**Comment by chrisbra** [comment]
then perhaps report to the st maintainers as well

**Comment by brammool** [comment]
This very much sounds like the terminal can't handle some more complicated escape codes and gets in a bad state until the screen is cleared.  Don't see a reason to look into the Vim side of this.

**Comment by Shane-XB-Qian** [comment]
how about following case: 
`│SELECT` was copied by mouse - its 'right key' (chose 'copy' of its popup menu)
if pasted into vim by `"+p` (or `"*p`), it would show as `\u2502SELECT`
or insert mode - pasted by 'shift+insert' then it would be `│SELECT`
// tried on xterm.
looks such case existed long time, any idea if it was expected or a bug?

**Comment by Shane-XB-Qian** [comment]
~~not sure which patch but looks version v8.2.3095 i can not reproduce above my case now... good! :-)~~

// update: actually above issue still there, opening #8706 for that.
