### ISSUE TITLE
Missaligned tab stops in .diff and .patch files

### ISSUE THREAD

**Issue by terminatorul** [vim/vim#8366]
**Describe the bug**
In a .diff or .patch file, tab stops within the text appear off-by-one

**To Reproduce**
Open a .diff or .patch file that uses tabs. Because diff inserts a new column at character position 1, for the '+', '-' and ' ' characters, tab stops in the rest of the content show up wrong

**Expected behavior**
In a .diff or .patch files, tab stops should start in column 2 instead of column 1. So instead of having tab stops in columns 1, 8, 16, 24, 32..., they should be in columns 2, 9, 17, 25, 33...

**Screenshots**
![image](https://user-images.githubusercontent.com/378924/121724962-4f390c80-caf1-11eb-9a81-406d3a4cf910.png)

[gitattributes.diff.gz](https://github.com/vim/vim/files/6640049/gitattributes.diff.gz)

**Environment (please complete the following information):**
 - VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 12 2019 13:19:27)

**Additional context**
Only affects .diff and .patch files

**Comment by brammool** [comment]
I think you can do this with ":set vartabstop=1,8".

**Comment by terminatorul** [comment]
Yes, thank you, that fixed my .diffs

I am not sure I understand the logic, though, my understanding would be
that I need vartabstop=7,8.

It would be nice if you could make this fix the default for .diff and
.patch files.

Otherwise this ticket should now be solved.
And thank you for such a great text editor!

**Comment by brammool** [comment]
It's not that easy, some diff files have a two character margin.  We could perhaps detect that.
