### ISSUE TITLE
Suggestion: Enabling Discussions

### ISSUE THREAD

**Issue by stefanos82** [vim/vim#8371]
Can we enable Discussions please? 

This way it could reduce the number of issues from asking the same questions more or less repeatedly.

I have some questions to ask from a user's perspective and I don't think opening an issue would be ideal.

@brammool what do you think?

**Comment by bfrg** [comment]
Probably a duplicate of #8291 . See the following comment by Bram: https://github.com/vim/vim/issues/8291#issuecomment-851631407.

**Comment by brammool** [comment]
There already is https://vi.stackexchange.com/ for discussions.   Having two places does not seem like a good idea.

**Comment by stefanos82** [comment]
Bummer...I don't want to create yet another account for the sake of asking a couple of questions; I thought here would be much more convenient and appropriate to have questions located in one place.

Oh well, closing this ticket.

**Comment by nickspoons** [comment]
@stefanos82 there is the [vim@vim.org mailing list](https://www.vim.org/maillist.php#vim) for user discussions ([archive on google groups](https://groups.google.com/g/vim_use))

There is also a very active IRC community at #vim on libera.chat, which is a great place for discussion, and getting questions answered.

**Comment by stefanos82** [comment]
@nickspoons after the Freenode incident I decided to never deal with opening account on any platform or service, for the sake of asking a single question every 3 to 5 years; in other words, it's not worth it.

Besides, I had not used IRC for a very long time because nearly all channels were too toxic, for me at least.

If I could sign-in in libera.chat with guest account to ask my question would be handy; but to open an account for a single question...no, thank you.

**Comment by chrisbra** [comment]
then use the mailinglists for discussions.

**Comment by habamax** [comment]
> @stefanos82 there is the [vim@vim.org mailing list](https://www.vim.org/maillist.php#vim) for user discussions ([archive on google groups](https://groups.google.com/g/vim_use))
> 
> There is also a very active IRC community at #vim on libera.chat, which is a great place for discussion, and getting questions answered.

https://www.vim.org/community.php still points to freenode though.

**Comment by stefanos82** [comment]
> then use the mailinglists for discussions.

You cannot ask a question without subscribing first.

![image](https://user-images.githubusercontent.com/1777466/122040314-52c5df80-cde0-11eb-9fa0-101320a70513.png)

**Comment by chrisbra** [comment]
Yes, and the first few messages will even be moderated. But you need an account for any other discussion forum as well.

**Comment by brammool** [comment]
Nearly all platforms require some form of login, because without that fighting spam is a nightmare.
We had to close Vim tips for that reason.

Since these days a lot of people go to github, I added a few lines at the top of the readme file.  I only want to put the most popular places there, if a useful one is missing let me know.

**Comment by stefanos82** [comment]
Those who are interested in answering my naive questions can visit my [Discussions'](https://github.com/stefanos82/nelua.vim/discussions/1) section for [Nelua](https://nelua.io)'s syntax highlighting support.

Thank you very much for the multiple suggestions.
