### ISSUE TITLE
Vim for CLI Linux

### ISSUE THREAD

**Issue by bagalexey** [vim/vim#8373]
Hello,

I'm using CLI version of pure Linux 5.4 x64 (no pakage manager) on hardware without display module.
I can compile and install Vim's latest version 8.2 only in tiny/small configuration. Starting from normal configuration compiler gives that type of error:

m_sgfmt --desktop -d . --template gvim.desktop.in -o tmp_gvim.desktop
af.po: warning: Charset "ISO-8859-1" is not supported. msgfmt relies on iconv(),
                and iconv() does not support "ISO-8859-1".
                Installing GNU libiconv and then reinstalling GNU gettext
                would fix this problem.
                Continuing anyway.
msgfmt: Cannot convert from "ISO-8859-1" to "UTF-8". msgfmt relies on iconv(), and iconv() does not support this conversion._

None of the  currently proposed solution works to solve this issue. And I need  a version with Python3  syntax  correction feature  enabled
.

Regards,
Alex

**Comment by dpelle** [comment]
What is the output of these commands?
```
$ locale
$ locale -a
```
Please also post the command you use to configure and build Vim.

> I can compile and install Vim's latest version 8.2

Is this vim-8.2.0000? or the latest from git, which is vim-8.2.2984 at the time of writing this.

If only msgfmt is having trouble (?), you could try adding `--disable-nls` to your `configure` command (it removes the translation of message with gettext).

**Comment by dpelle** [comment]
Also, the error message indicates that installing GNU libiconv and then reinstalling GNU gettext would fix this problem.
I don't know about pure Linux, but on Ubuntu, libiconv comes with the libc I think. And gettext would be installed with:
```
$ sudo apt-get install libgettextpo-dev 
```

**Comment by bagalexey** [comment]
Thank you,  --disable-nls flag solved the issue.

Regards,
Alex
