### ISSUE TITLE
Question: popup_create() with filter option

### ISSUE THREAD

**Issue by monkoose** [vim/vim#8374]
Vim version `8.2.2891`

Consider this code
```vim
function! Popup() abort
  call popup_create('foobar', {'filter': 'MyFilter'})
endfunction

function! MyFilter(w, k) abort
  echom a:k
  return 1
endfunction
```
With `vim --clean` it works as it should (or at least for my needs and how i understand it should work). But with my config on `:call Popup()` it immediately shows this sequence in command-line and a lot of keys behave in a strange way
```
<80><fd>`
```
notice backtick

Can someone explain what does this mean, and where to dig to resolve this problem in my config?

**Comment by lacygoill** [comment]
This is the byte encoding of the pseudo-key `<CursorHold>`:

    :echo "\<CursorHold>"
    <80><fd>`

**Comment by lacygoill** [comment]
It's automatically "pressed" after `&updatetime` milliseconds, on the condition that you have at least 1 autocmd listening to `CursorHold`.  IMO, a popup filter should ignore it, but since it does not, you might have to do it manually, [like I do here](https://github.com/lacygoill/vim-fuzzy/blob/13101f66d12001a462d8175b0593e49661a02242/autoload/fuzzy.vim#L940-L944).

**Comment by monkoose** [comment]
@lacygoill Thank you. This explain it. But from your description, and i already tested it, yes now it doesn't show this sequence, but at the same time it doesn't fix my main problem :( 

Main problem that with `nnoremap <nowait> <Esc> <Esc>`, when i press `<Esc>` it outputs (with echom key in filter)
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
<80><fd>f
c
a
l
l

<80><fd>R
3
_
C
l
o
s
e
P
o
p
u
p
W
i
n
d
o
w
(
)
^M
```

**Comment by lacygoill** [comment]
> Main problem that with nnoremap <nowait> <Esc> <Esc>, when i press <Esc> it outputs (with echom key in filter)

Mapping `<Esc>` is known to cause many issues.  See [here](https://github.com/lacygoill/wiki/blob/master/vim/mapping.md#why-should-i-avoid-a-mapping-with-an-esc-in-its-lhs).

> Side question: How to make in a filter function recognize kyes with Ctrl like \<c-y>, for now i need to use ^Y and for Esc ^[ is it terminal emulator related? I use kitty.

    def MyPopupFilter(id: number, key: string): bool
        ...
        if key == "\<c-y>"
                  ^------^
            ...
        endif
        ...
    enddef

**Comment by monkoose** [comment]
@lacygoill I tested this code, that's why i have asked. It doesn't recognize it in my terminal emulator. Does `\<Esc>` works for you too?

**Comment by monkoose** [comment]
> Mapping <Esc> is known to cause many issues. See here.

Seems like this is the  source of my main problem. 

Ok, side question again mappings like `nnoremap <m-a> any_rhs` works for you in your .vimrc, have you done something special for this to work?

**Comment by lacygoill** [comment]
> Ok, side question again mappings like nnoremap <m-a> any_rhs works for you in your .vimrc, have you done something special for this to work?

See [here](https://github.com/lacygoill/wiki/blob/master/vim/mapping.md#how-to-use-a-chord-with-the-meta-modifier-in-my-mappings).

**Comment by monkoose** [comment]
> > Ok, side question again mappings like nnoremap  any_rhs works for you in your .vimrc, have you done something special for this to work?
> 
> See [here](https://github.com/lacygoill/wiki/blob/master/vim/mapping.md#how-to-use-a-chord-with-the-meta-modifier-in-my-mappings).

Thank you. Seems like kitty doesn't have this modifyOtherKeys feature.
