### ISSUE TITLE
doc: "[cmd]" wrongly highlighted as "helpSpecial" at ":h vim9" and ":h index"

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8379]
`[cmd]` is wrongly highlighted as `helpSpecial` at `:h vim9` and `:h index`.  This is confusing, because – usually – this highlighting means that `[cmd]` is an arbitrary Ex command.  But here, `[cmd]` is just an optional suffix.

This patch should fix the issue:
```diff
diff --git a/runtime/syntax/help.vim b/runtime/syntax/help.vim
index a4c34cd46..d8f9f6b90 100644
--- a/runtime/syntax/help.vim
+++ b/runtime/syntax/help.vim
@@ -75,7 +75,7 @@ syn match helpSpecial		"\[range]"
 syn match helpSpecial		"\[line]"
 syn match helpSpecial		"\[count]"
 syn match helpSpecial		"\[offset]"
-syn match helpSpecial		"\[cmd]"
+syn match helpSpecial		"9\@1<!\[cmd]"
 syn match helpSpecial		"\[num]"
 syn match helpSpecial		"\[+num]"
 syn match helpSpecial		"\[-num]"
```

**Comment by brammool** [comment]
@cecamp

**Comment by lacygoill** [comment]
I might be wrong, but I don't think @cecamp is the maintainer of the help syntax plugin:

https://github.com/vim/vim/blob/5ffefbb35aba2448099314a9e09714d2f3b2b1bd/runtime/syntax/help.vim#L3

**Comment by brammool** [comment]
Yes, sorry, didn't read it properly.  Since we explicitly want to highlight vim9[cmd] normally, I think the simplest is:
syn match helpNormal		"vim9\[cmd]"
