### ISSUE TITLE
Can't load tag file with absolute path on Windows.

### ISSUE THREAD

**Issue by zoumi** [vim/vim#8380]
**Describe the bug**
I have set the tag file path with a absolute path, but gvim can't not find it.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. create a tag file: C:\Users\zoumi\.cache\HYtags
2. set tag file path for vim:

 ```
:setl tags+=C:\Users\zoumi\.cache\HYtags,tags
```

3. check the file exist:    

```
echo filereadable('C:\Users\zoumi\.cache\HYtags')        "return 1
```

4. check if vim can find this tag file
```
echo tagfiles() 
```

**Expected behavior**
echo tagfiles() should get ['C:\Users\zoumi\.cache\HYtags'], but it return []

**Environment (please complete the following information):**
 - Vim version
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun 13 2021 22:02:46)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-2994
Compiled by appveyor@APPVYR-WIN
```
 - OS: Windows 10 64bit
 - Terminal: GUI

**Comment by lacygoill** [comment]
Untested but try to double the backslashes:

    :setl tags+=C:\\Users\\zoumi\\.cache\\HYtags,tags
                  ^^     ^^     ^^      ^^

Or use `:let`:

    :let &l:tags = &l:tags .. ',' .. 'C:\Users\zoumi\.cache\HYtags,tags'

See [`:h option-backslash`](https://vimhelp.org/options.txt.html#option-backslash).

**Comment by zoumi** [comment]
```
:setl tags+=C:\\Users\\zoumi\\.cache\\HYtags,tags
```
and
```
:setl tags+=C:\\Users\\zoumi\\.cache\\HYtags,tags
```
both get:
echo &tags:
C:\Users\zoumi\.cache\HYtags,tags

**Comment by lacygoill** [comment]
Ah right.  On Windows, backslashes are not removed contrary to Linux:

> For Win32 backslashes in file names are mostly not removed.  More precise: For
> options that expect a file name (those where environment variables are
> expanded) a backslash before a normal file name character is not removed.  But
> a backslash before a special character (space, backslash, comma, etc.) is used
> like explained above.

**Comment by vim-ml** [comment]
On 2021-06-14, zoumi wrote:
> Describe the bug
> I have set the tag file path with a absolute path, but gvim can't not find it.
> 
> To Reproduce
> Detailed steps to reproduce the behavior:
> 
>  1. create a tag file: C:\Users\zoumi.cache\HYtags
>  2. set tag file path for vim:
> 
> :setl tags+=C:\Users\zoumi\.cache\HYtags,tags
> 
>  3. check the file exist:
> 
> echo filereadable('C:\Users\zoumi\.cache\HYtags')
> 
>  4. check if vim can find this tag file
> 
> echo tagfiles()      "return 1
> 
> Expected behavior
> echo tagfiles() should get ['C:\Users\zoumi.cache\HYtags'], but it return []
> 
> Environment (please complete the following information):
> 
>   • Vim version
> 
> VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun 13 2021 22:02:46)
> MS-Windows 64-bit GUI version with OLE support
> Included patches: 1-2994
> Compiled by appveyor@APPVYR-WIN
> 
>   • OS: Windows 10 64bit
>   • Terminal: GUI

It works for me, on Windows 10 with the same Vim 8.2.2994.

From a Cygwin prompt:

    $ touch 'C:\Users\gjohn\Documents\HYtags'

From a Windows Command Prompt:

    C:\Program Files\Vim\vim82>gvim -N -u NONE -i NONE
    :echo filereadable('C:\Users\gjohn\Documents\HYtags')
    1
    :setl tags+=C:\Users\gjohn\Documents\HYtags
    :echo tagfiles()
    ['\Users\gjohn\Documents\HYtags']

I'm afraid I can't think of any reason it wouldn't work for you.

Regards,
Gary

**Comment by zoumi** [comment]
@vim-ml I found it's because the dir name ".cache".If I change the name to "cache" it works.
I have set .gitignore to ignore all .* file, does this affects vim?

**Comment by zoumi** [comment]
So,is it a bug?

**Comment by zoumi** [comment]
It' because the plugin 'ZSaberLv0/ZFVimIgnore' set ".cache" in the wildignore option.
