### ISSUE TITLE
bindzone.vim requires 9 or 10 digits, while 1 digid is still a valid zone serial

### ISSUE THREAD

**Issue by OtherSystems** [vim/vim#8382]
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Describe the bug**
Create or edit a bind-zone file in vim with syntax hilighting where the serial is less then 9 digits. 
Vim will then show the serial field als invalid by giving it a particular colour (in my case red). 
As a serial is valid for any positive 32bit decimal value, a single digit is also valid, but vim no indicates it incorrectly as invalid.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. open vim with syntax hilighting
2. open a bind zone file with a short (<9 digit) serial
3. Serial number will be marked as invalid.
4. give it 9 or 10 digits and it will be marked as valid

**Expected behavior**
All values between 0 and 4294967295 should be marked as valid independent on how few digits are used.

**Screenshots**
![image](https://user-images.githubusercontent.com/25455376/121903026-2c446d80-cd28-11eb-8900-13591c010406.png)

**Environment (please complete the following information):**
- VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 15 2019 16:41:15)
Included patches: 1-875, 878, 884, 948, 1046, 1365-1368, 1382, 1401
- Debian 9 / Buster
- Terminal: Mate  Terminal

This seems to be handled on line 66 of bindzone.vim:
"syn match       zoneSerial      contained /\<[0-9]\{9,10}\(\s\|;\|$\)\@=/"

A simple fix would be:
"syn match       zoneSerial      contained /\<[0-9]\{1,10}\(\s\|;\|$\)\@=/"

A more complicated regular expression could match if it's actually below 4294967295 but that might be too much for this function.

**Comment by brammool** [comment]
Please send an email to the maintainer, Julian Mehnle.

Although theoretically just about any number is OK, the minimal normally used is year-month-day, thus 20210614, which is 8 digits.

**Comment by OtherSystems** [comment]
Thank you, I've mailed them.

There do exist multiple manuals online suggesting to start at 1, I think it would be nice to also consider those approaches.

**Comment by OtherSystems** [comment]
Thank you, I've mailed them, but have not received a reply. 

There do exist multiple manuals online suggesting to start at 1, I think it would be nice to also consider those approaches.

**Comment by chrisbra** [comment]
I don't think so. But there is a chance, that it is actually @jmehnle. So let's try to ping him here.
