### ISSUE TITLE
Vim9: cannot debug closure

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8384]
**Describe the bug**

In Vim9 script, we cannot debug a closure.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            var n: number
            def Closure(): number
                return n + 3
            enddef
            n += Closure()
        enddef
        debug Func()
    EOF
    )

Press `n` and `Enter` to execute the debugging command `next`.

`E1001` is raised:

    E1001: Variable not found: n

**Expected behavior**

No error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-3001
 - OS: Ubuntu 20.04.2 LTS
 - Terminal: XTerm(353)

**Additional context**

The code works fine without `:debug`:
```vim
vim9script
def Func()
    var n: number
    def Closure(): number
        return n + 3
    enddef
    n += Closure()
enddef
Func()
```
    no error

---

`:defcompile` can't help here:
```vim
vim9script
def Func()
    var n: number
    def Closure(): number
        return n + 3
    enddef
    n += Closure()
enddef
defcompile
debug Func()
```
    E1001: Variable not found: n

Presumably because the (problematic) compilation of a closure can only occur at runtime, contrary to a regular function defined directly at the script level.

---

If it can't be fixed, maybe this limitation should be documented.

**Comment by brammool** [comment]
> **Describe the bug**
> 
> In Vim9 script, we cannot debug a closure.
> 
> **To Reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(cat <<'EOF'
>         vim9script
>         def Func()
>             var n: number
>             def Closure(): number
>                 return n + 3
>             enddef
>             n += Closure()
>         enddef
>         debug Func()
>     EOF
>     )
> 
> Press `n` and `Enter` to execute the debugging command `next`.
> 
> `E1001` is raised:
> 
>     E1001: Variable not found: n
> 
> **Expected behavior**
> 
> No error is raised.
> 
> **Environment**
> 
>  - Vim version: 8.2 Included patches: 1-3001
>  - OS: Ubuntu 20.04.2 LTS
>  - Terminal: XTerm(353)
> 
> **Additional context**
> 
> The code works fine without `:debug`:
> ```vim
> vim9script
> def Func()
>     var n: number
>     def Closure(): number
>         return n + 3
>     enddef
>     n += Closure()
> enddef
> Func()
> ```
>     no error
> 
> ---
> 
> `:defcompile` can't help here:
> ```vim
> vim9script
> def Func()
>     var n: number
>     def Closure(): number
>         return n + 3
>     enddef
>     n += Closure()
> enddef
> defcompile
> debug Func()
> ```
>     E1001: Variable not found: n
> 
> Presumably because the (problematic) compilation of a closure can only occur at runtime, contrary to a regular function defined directly at the script level.
> 
> ---
> 
> If it can't be fixed, maybe this limitation should be documented.

This one I can fix.  There might be other combinations of a function
compiled normally and for debugging that doesn't work properly.  Please
report if you find one.  Perhaps it will get worse once we introduce
breakpoints, we'll see.

-- 
Sometimes you can protect millions of dollars in your budget simply by buying
a bag of cookies, dropping it on the budget anylyst's desk, and saying
something deeply personal such as "How was your weekend, big guy?"
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
It would help if we had `v:debugging` (just like we have `v:profiling`); to disable custom autocmds listening to `CmdlineLeave` or command-line mode mappings while we debug:

    au CmdlineLeave : if !v:debugging | do something | endif
                          ^---------^

**Comment by brammool** [comment]
> It would help if we had `v:debugging` (just like we have `v:profiling`); to disable custom autocmds listening to `CmdlineLeave` or command-line mode mappings while we debug:
> 
>     au CmdlineLeave : if !v:debugging | do something | endif
>                           ^---------^

Well, the question is, when would it be set?  When stepping through
code or when there is a breakpoint somewhere?
Also, when using "next" debugging is off in the called function and only
starts again when it returns.

Anyway, let's now restrict to making debugging work for Vim 9 script,
add any new features later.  Otherwise Vim 9 is never going to get done!

-- 
I used to be indecisive, now I'm not sure.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
