### ISSUE TITLE
line number digits in vim -H reversed

### ISSUE THREAD

**Issue by DanHaran9** [vim/vim#8389]
Six months ago I installed vim 8.2 on Windows 10 and vim 8.1.2269 on Linux Ubuntu, both with +rightleft option. 
When I use the "Hebrew mode" (gvim --clean -H or vim --clean -H) and run :set number, I get line numbers on the right side (as it should be - so far so good).
However, **some line numbers appear reversed, i.e., 009 instead of 900** -- unlike in previous versions of vim, e.g. version 7.4.52 and or 8.1.1, which displayed the line numbers correctly.
More precisely:
- if the last line number of the file has 2 digits, then line numbers consisting of 2 digits appear reversed.
- If the last line number has m digits, m>=3, then line numbers of lines, that have between 2 to m-1 digits, appear reversed.
I attach a screenshot of a file that has 1319 lines:
![reversed](https://user-images.githubusercontent.com/85963592/122114459-f8eb0700-ce2b-11eb-8588-02f16054189a.jpg)
See also:  https://vi.stackexchange.com/questions/28743/line-numbers-in-vim-h-reversed/

**Comment by chrisbra** [comment]
This is caused by patch: https://github.com/vim/vim/releases/tag/v8.1.1073

The problem is is part of the patch:
```diff
+                           // like rl_mirror(), but keep the space at the end
+                           p2 = skiptowhite(extra) - 1;
```

For lines where the whole numbercolumn is filled with numbers, this works as expected, but for the others, this will actually decrement the p2 and point to before the extra pointer.

I think this patch should fix it:
```patch
diff --git a/src/screen.c b/src/screen.c
index 7706b6c58..7913de678 100644
--- a/src/screen.c
+++ b/src/screen.c
@@ -3901,8 +3901,9 @@ win_line(
                            int         t;

                            // like rl_mirror(), but keep the space at the end
-                           p2 = skiptowhite(extra) - 1;
-                           for (p1 = extra; p1 < p2; ++p1, --p2)
+                           p2 = skipwhite(extra);
+                           p2 = skiptowhite(p2) - 1;
+                           for (p1 = skipwhite(extra); p1 < p2; ++p1, --p2)
                            {
                                t = *p1;
                                *p1 = *p2;
```

this would make: 
![image](https://user-images.githubusercontent.com/244927/122176488-f072ea80-ce84-11eb-8e7b-b8ce81faab3a.png)
