### ISSUE TITLE
Vim9: when debugging, automatic continuation lines are ignored

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8392]
**Describe the bug**

In Vim9 script, when debugging a function, automatic continuation lines are ignored, which makes it harder to know which commands Vim is executing.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            var d = {
                a: 1,
                b: 2,
                c: 3,
            }
        enddef
        debug Func()
    EOF
    )

Press `s` then Enter, to execute the debugging command `step` and step into the function `Func()`.

This line is printed:

    line 1:         var d = {

**Expected behavior**

This line is printed:

    line 1: var d = {  a: 1,  b: 2,  c: 3, }

**Environment**

 - Vim version: 8.2 Included patches: 1-3010
 - OS: Ubuntu 20.04.2 LTS
 - Terminal: XTerm(353)

**Additional context**

If `Func()` is rewritten as a legacy function, with explicit continuation lines, the assignment is printed in its entirety:
```vim
vim9script
fu Func()
    let d = #{
    \    a: 1,
    \    b: 2,
    \    c: 3,
    \ }
endfu
debug Func()
```
    # after executing >step
    line 1: let d = #{    a: 1,    b: 2,    c: 3,}

---

Adding explicit continuation lines fixes the issue:
```vim
vim9script
def Func()
    var d = {
    \   a: 1,
    \   b: 2,
    \   c: 3,
    \ }
enddef
debug Func()
```
    # after executing >step
    line 1:     var d = {   a: 1,   b: 2,   c: 3, }

**Comment by lacygoill** [comment]
Before the patch, Vim didn't join enough lines.  Now, it joins too many; that is, it joins a subsequent comment:
```vim
vim9script
def Func()
    var d = {
        a: 1,
        b: 2,
        c: 3,
    }
    # some
    # very
    # long
    # comment
enddef
debug Func()
```
    # after >step
    line 1: var d = {  a: 1,  b: 2,  c: 3,  }  # some  # very  # long  # comment
                                               ^-------------------------------^
                                                            noise

This is especially noticeable when there is a long comment.  If the comment is too long, it seems Vim stops at some arbitrary length.

---

There is also the case of closures:
```vim
vim9script
def Func()
    def Inner()
        eval 1
        eval 2
        eval 3
    enddef
enddef
debug Func()
```
    line 1: def Inner()  eval 1  eval 2  eval 3  enddef

I don't know what's best.  If we can't get each line separately, maybe they should be separated with bars?

    line 1: def Inner()  | eval 1 | eval 2 | eval 3 | enddef
                         ^        ^        ^        ^

In legacy, only the header is printed:
```vim
fu Func()
    fu Inner()
        eval 1
        eval 2
        eval 3
    endfu
endfu
debug call Func()
```
    line 1: fu Inner()

**Comment by lacygoill** [comment]
It's better, but there is yet another corner case.  If the comment is moved inside the dictionary, Vim truncates too early:
```vim
vim9script
def Func()
    var d = {
        a: 1,
        # comment
        b: 2,
    }
enddef
debug Func()
```
    # after executing >step
    line 1: var d = {  a: 1,

In legacy, the comment is removed, and the dictionary is printed in its entirety:
```vim
fu Func()
    let d = #{
    \    a: 1,
    "\ comment
    \    b: 2,
    \}
endfu
debug call Func()
```
    # after executing >step
    line 1: let d = #{    a: 1,    b: 2,}

**Comment by brammool** [comment]
> It's better, but there is yet another corner case.  If the comment is
> moved inside the dictionary, Vim truncates too early:
> ```vim
> vim9script
> def Func()
>     var d = {
>         a: 1,
>         # comment
>         b: 2,
>     }
> enddef
> debug Func()
> ```
>     # after executing >step
>     line 1: var d = {  a: 1,

It's not perfect, but it is enough to see where you are, what the next
command is.
 
Passing the line range to the debug command is a bit of a hassle,
because the debug instruction is generated before the lines are parsed.
I rather not spend too much time on this and make the code a bit more
complicated.

-- 
hundred-and-one symptoms of being an internet addict:
7. You finally do take that vacation, but only after buying a USB modem
   and a laptop.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
