### ISSUE TITLE
Unable to open file with special character ・ (0x30FB)

### ISSUE THREAD

**Issue by gqqnbig** [vim/vim#840]
![default](https://cloud.githubusercontent.com/assets/614159/15639614/ded01b5e-25e2-11e6-98c4-fc92f884fd7b.JPG)
See the figure. Notepad opens ・.txt correctly, but Vim opens it and shows empty content.

**Comment by k-takata** [comment]
What is the result of `set enc`?
How about setting `enc` to `utf-8` in your `.vimrc`?

**Comment by gqqnbig** [comment]
It works, thanks! I read [http://superuser.com/questions/373518/vim-cant-open-a-files-directory-if-it-contains-special-letters](http://superuser.com/questions/373518/vim-cant-open-a-files-directory-if-it-contains-special-letters) and thought it's related to the kernel.

You can close the issue.
