### ISSUE TITLE
Elixir filetype detection

### ISSUE THREAD

**Issue by aegatlin** [vim/vim#8401]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
There is nothing in the header of `runtime/filetype.vim` regarding where else to raise this feature request.

**Describe the solution you'd like**
I would like elixir filetype detection in vim.

**Describe alternatives you've considered**
I was initially going to submit a simple PR adding something like these lines to `runtime/filetype.vim`:

```
autocmd BufRead,BufNewFile *.ex,*.exs setf=elixir
autocmd BufRead,BufNewFile *.eex,*.leex,*.sface setf=eelixir
autocmd BufRead,BufNewFile mix.lock setf=elixir
```

However, while investigating, I noticed that Euphoria files are already set against `.ex` in particular (https://github.com/vim/vim/blob/59b50c3bee908694ae4ac10b26bfebf99d09d466/runtime/filetype.vim#L412). They call out to a `EuphoriaCheck` function that that always sets to some euphoria filetype (https://github.com/vim/vim/blob/59b50c3bee908694ae4ac10b26bfebf99d09d466/runtime/autoload/dist/ft.vim#L175).

This complicates things and so I wanted to discuss the best approach before submitting a PR. It is perhaps an understatement to say that elixir is a more popular programming language that euphoria these days, and as such, I feel like it should be given priority regarding the `.ex` file extension. But, that then leaves the question of how to handle the euphoria files. As it currently stands, elixir files are assigned `filetype=euphoria`, and so elixir devs have to write the above commands somewhere in their own config. 

Simply reversing this situation seems like a viable option. In such a situation, `.ex` would be assigned `filetype=elixir`, and that would leave to euphoria devs the task of overriding it in their own configuration files.

A more complicated solution would be write a resolution function for `.ex` files that could leverage current functionality, like the `g:filetype_euphoria` to figure out how to assign it.

I would be excited to have the opportunity to submit a PR against vim, and I'm keen to hear thoughts on the best way to approach this.

Thanks! :D

**Comment by brammool** [comment]
Austin Gatlin wrote:

> **Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
> There is nothing in the header of `runtime/filetype.vim` regarding where else to raise this feature request.
> 
> **Describe the solution you'd like**
> I would like elixir filetype detection in vim.
> 
> **Describe alternatives you've considered**
> I was initially going to submit a simple PR adding something like these lines to `runtime/filetype.vim`:
> 
> ```
> autocmd BufRead,BufNewFile *.ex,*.exs setf=elixir
> autocmd BufRead,BufNewFile *.eex,*.leex,*.sface setf=eelixir
> autocmd BufRead,BufNewFile mix.lock setf=elixir
> ```
> 
> However, while investigating, I noticed that Euphoria files are already set against `.ex` in particular (https://github.com/vim/vim/blob/59b50c3bee908694ae4ac10b26bfebf99d09d466/runtime/filetype.vim#L412). They call out to a `EuphoriaCheck` function that that always sets to some euphoria filetype (https://github.com/vim/vim/blob/59b50c3bee908694ae4ac10b26bfebf99d09d466/runtime/autoload/dist/ft.vim#L175).
> 
> This complicates things and so I wanted to discuss the best approach before submitting a PR. It is perhaps an understatement to say that elixir is a more popular programming language that euphoria these days, and as such, I feel like it should be given priority regarding the `.ex` file extension. But, that then leaves the question of how to handle the euphoria files. As it currently stands, elixir files are assigned `filetype=euphoria`, and so elixir devs have to write the above commands somewhere in their own config. 
> 
> Simply reversing this situation seems like a viable option. In such a situation, `.ex` would be assigned `filetype=elixir`, and that would leave to euphoria devs the task of overriding it in their own configuration files.
> 
> A more complicated solution would be write a resolution function for `.ex` files that could leverage current functionality, like the `g:filetype_euphoria` to figure out how to assign it.
> 
> I would be excited to have the opportunity to submit a PR against vim, and I'm keen to hear thoughts on the best way to approach this.

Is there something in the first few lines of an Elixir file that we can
recognize?  Especially something that's different from Euphoria, e.g.
the comment leader or some keyword.  If yes, then we can read those
lines and decide about the filetype.

Can you somehow show how Euphoria files are less popular than Elixir?


-- 
The Feynman problem solving Algorithm:
	1) Write down the problem
	2) Think real hard
	3) Write down the answer

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by jc00ke** [comment]
Hi there! Austin and I have been working on our vim setup together, so I'm pretty interested in this issue too.

Elixir's `.ex` files most often start off with `defmodule` but that's not guaranteed. I looked at all the projects I have checked out locally and out of the 1847 `.ex` files, only 19 _did not_ start with `defmodule`.

| word | count |
| -------| ---------|
| defmodule | 1828 |
| credo | 3 |
| import | 2 |
| defprotocol | 3 |
| defmock | 10 |
| require | 1 |

In terms of popularity, I'll look to GitHub:

![image](https://user-images.githubusercontent.com/18191/122604041-2b625300-d02a-11eb-85c8-0d86c3d19ccb.png)
![image](https://user-images.githubusercontent.com/18191/122604114-446b0400-d02a-11eb-8cf3-8488ffba71d8.png)

Euphoria is not even mentioned in "Written in this language" dropdown on their [Advanced Search](https://github.com/search/advanced) page. Elixir, however, is specifically listed as a popular language.

![image](https://user-images.githubusercontent.com/18191/122602034-06b8ac00-d027-11eb-868d-517e24f5649b.png)

I tried hacking [the search](https://github.com/search/advanced?q=language%3AEuphoria+size%3A%3E1&type=Repositories) but I can't get GitHub to return any search results for Euphoria. I'm guessing the use of Euphoria is too low to register. There are almost [32,000](https://github.com/search?q=language%3AElixir+size%3A%3E1&type=Repositories&ref=advsearch&l=&l=) Elixir repositories on GitHub alone.

Not that this will necessarily matter, but GitHub itself recognizes `.ex` as being Elixir and not Euphoria.

Finally, so no one else has to go digging, here's a link to [vim-elixir/ftdetect/elixir.vim](https://github.com/elixir-editors/vim-elixir/blob/58084475c1e523caeac97ffff62c154f7f8fcc66/ftdetect/elixir.vim) for the currently best supported detection.

Thanks!

**Comment by brammool** [comment]
OK, it's convincing that Elixir is much more popular than Euphoria.  Google trends also confirms this.

So let's turn it around: let's assume an .ex file is Elixir, unless we are quite sure it's Euphoria.  can we do this?
It would require looking a several Euphoria files.

**Comment by jc00ke** [comment]
I cloned the [Euphoria](https://github.com/OpenEuphoria/euphoria/) code base to look at the leading line of all the `.ex` and `.exw` files and luckily they tend to start files with words or comments that aren't used in Elixir.

```
> fd -e ex -e exw | xargs head -q -n 1 | sort | uniq

			   ------------------
		--------------------------------------
		----------------------------------------------------------
	--------------------------------
	-----------------------------------------------
	----------------------------------------------------------
--
--** 
--****
-- buildcpdb.ex Build Codepage Database
-- (c) Copyright - See License.txt
-- datesub.ex
include euphoria/keywords.e
include file.e
include ../foo.e
include std/cmdline.e
include std/console.e
include std/console.e -- so we can use the prompt_number() function
include std/graphics.e
include std/io.e
include std/map.e as m
include std/math.e
include std/sequence.e
include std/text.e as text
include wildcard.e
integer val = 1
--JBrown
-- process coverage database
-- Produce exw31.exe, a version of eui.exe that uses 
-- Program generates a PKGBUILD file for you.
-- replace all magic numbers in the source files in the current directory passed to GetMsgText, CompileErr, and ShowMsg 
-- Run this as with eui, or euiw, or translate with euc and it will inform you what platform
-- Spell check of a file. The default dictionary (EWORDS.TXT) or your own 
#!/usr/bin/env eui
#!/usr/bin/eui -i /usr/share/euphoria/source/
-- warning_file( "warnings_issued.txt" )
without warning
with trace
```

The only common word I see is `with` but I think it's *highly* unlikely an Elixir `.ex` file would begin with `with`. Looks like Euphoria uses `--` for comments and Elixir uses `#` so that's a decent way to distinguish. Also Elixir does not have an `include` keyword (it has `require`, `import` and `use`).

`#!/usr/bin/env eui` and `#!/usr/bin/eui` are also good contenders of words to look for, specifically `eui`.

**Comment by aegatlin** [comment]
One way of being sure `.ex` is a euphoria file is leveraging the pre-existing `g:filetype_euphoria` variable, which is already checked in `dist#ft#EuphoriaCheck` so that euphoria devs can switch between multiple versions of euphoria filetypes. Given they already have a special variable in the source code, we could merely increase the strictness of its usage, and _require_ that euphoria devs set `g:filetype_euphoria`. Plus, if they are using the most up-to-date version of euphoria anyways (which seems to be filetype `euphoria4`) then they are already setting this variable themselves. This would imply that the fallback to filetype `euphoria3` in `dist#ft#EuphoriaCheck` is both (1) most commonly assigned incorrectly to elixir files, and (2) not commonly assigned to euphoria files, which are presumably set by `g:filetype_euphoria` manually.

Thusly, we could swap the fallback filetype from `euphoria3` to `elixir`:

```vimscript
func dist#ft#EuphoriaCheck()
  if exists('g:filetype_euphoria')
    exe 'setf ' . g:filetype_euphoria
  else
     setf elixir " previously setf euphoria3
  endif
endfunc
```

We could change the function to `dist#ft#ExCheck()` and run it only for `*.ex` files:

```
au BufNewFile,BufRead *.ex  call dist#ft#ExCheck()
```

And then add the other elixir filetype checks. There is the curious edge case of Euphoria files _also_ being checked for all caps (https://github.com/vim/vim/blob/59b50c3bee908694ae4ac10b26bfebf99d09d466/runtime/filetype.vim#L413), while it's surrounding peers don't have similar checks. I'm not sure how to handle that, and would be keen for suggestions in the regard.

I think the **upside** of this approach is we don't have to worry about subtle/clever algorithms to differentiate between the two filetypes, opting instead for merely picking a different fallback filetype for `.ex`. This would result in a relatively simple changeset, as well.

I think the **downside** of this approach is that it's arguably a reversion, since some devs that have depended on this `setf euphoria3` fallback will be surprised on update of vim to discover the filetype is suddenly now `elixir`.

**Comment by brammool** [comment]
> One way of being sure `.ex` is a euphoria file is leveraging the
> pre-existing `g:filetype_euphoria` variable, which is already checked in
> `dist#ft#EuphoriaCheck` so that euphoria devs can switch between
> multiple versions of euphoria filetypes. Given they already have a
> special variable in the source code, we could merely increase the
> strictness of its usage, and _require_ that euphoria devs set
> `g:filetype_euphoria`. Plus, if they are using the most up-to-date
> version of euphoria anyways (which seems to be filetype `euphoria4`)
> then they are already setting this variable themselves. This would imply
> that the fallback to filetype `euphoria3` in `dist#ft#EuphoriaCheck` is
> both (1) most commonly assigned incorrectly to elixir files, and (2) not
> commonly assigned to euphoria files, which are presumably set by
> `g:filetype_euphoria` manually.
> 
> Thusly, we could swap the fallback filetype from `euphoria3` to `elixir`:
> 
> ```vimscript
> func dist#ft#EuphoriaCheck()
>   if exists('g:filetype_euphoria')
>     exe 'setf ' . g:filetype_euphoria
>   else
>      setf elixir " previously setf euphoria3
>   endif
> endfunc
> ```
> 
> We could change the function to `dist#ft#ExCheck()` and run it only for `*.ex` files:
> 
> ```
> au BufNewFile,BufRead *.ex  call dist#ft#ExCheck()
> ```

That sounds good.

> And then add the other elixir filetype checks. There is the curious
> edge case of Euphoria files _also_ being checked for all caps
> (https://github.com/vim/vim/blob/59b50c3bee908694ae4ac10b26bfebf99d09d466/runtime/filetype.vim#L413),
> while it's surrounding peers don't have similar checks. I'm not sure
> how to handle that, and would be keen for suggestions in the regard.
> 
> I think the **upside** of this approach is we don't have to worry
> about subtle/clever algorithms to differentiate between the two
> filetypes, opting instead for merely picking a different fallback
> filetype for `.ex`. This would result in a relatively simple
> changeset, as well.
> 
> I think the **downside** of this approach is that it's arguably a
> reversion, since some devs that have depended on this `setf euphoria3`
> fallback will be surprised on update of vim to discover the filetype
> is suddenly now `elixir`. l

If we have a way to reliable detect an Euphoria file we should use that.
We can default to Elixir if we are not sure and g:filetype_euphoria is
not set.

Main reason to do this is that the check for Euphoria can be tuned
easily, while adding that check migth not be so easy for an average
Euphoria user.

It's a little bit more work right now, but it makes further changes a
lot easier.

-- 
How To Keep A Healthy Level Of Insanity:
8. Don't use any punctuation marks.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dkearns** [comment]
Have you approached the [vim-elixir](https://github.com/elixir-editors/vim-elixir) project about also having their runtime files distributed with Vim or is this in preparation for another implementation (perhaps your own)?

I had a quick look through their issues but didn't find anything.
