### ISSUE TITLE
Inconsistent tag names in "doc/tags", "doc/ft_ps1.txt", and "doc/ft_raku.txt"

### ISSUE THREAD

**Issue by lkintact** [vim/vim#8402]
**To Reproduce**
1. Run `gvim --clean`
2. Execute `:help`
3. Press <kbd>157gg</kbd> to go to line 157 and press <kbd>K</kbd>. gVim issues an `E149: Sorry, no help for ft_ps1.txt` error.
4. Press <kbd>j</kbd> to go to line 158 and press <kbd>K</kbd>. gVim issues an `E149: Sorry, no help for ft_raku.txt` error.

**Environment:**
 - Vim version  8.2.2994
 - OS: Windows 10 Home 1803
 - Terminal: GUI.

**Comment by k-takata** [comment]
These lines should be updated:
https://github.com/vim/vim/blob/59b50c3bee908694ae4ac10b26bfebf99d09d466/runtime/doc/ft_ps1.txt#L1
https://github.com/vim/vim/blob/59b50c3bee908694ae4ac10b26bfebf99d09d466/runtime/doc/ft_raku.txt#L1

**Comment by brammool** [comment]
I will update the tags.
I thought my script would find these mistakes, but apparently not...
