### ISSUE TITLE
Add "Edit with Vim using Tabpages" to Windows Gvim

### ISSUE THREAD

**Issue by ghost** [vim/vim#8404]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
Gvim for Windows currently provides several "Edit with Vim" shell extensions by menu.  Since Vim now supports tab pages, I think it would be nice if that choice was available as an alternative to using multiple Gvim instances.

**Describe the solution you'd like**
A new shell extension menu option that is displayed when several files have been selected in Windows Explorer.

**Describe alternatives you've considered**
There are alternatives but, I could be wrong, none are as convenient.  

**Additional context**
None.

**Comment by brammool** [comment]
I never really liked the "edit with multiple Vims", it is usually not what you want.
Adding a lot of entries to the menu also isn't nice, good menus are short.
So how about replacing the "edit with multiple Vims" into "Edit with Vim in multiple tab pages"?

**Comment by msoyka-of-wharton** [comment]
In the absence of any other comments, I will volunteer to implement this change as Bram has suggested. Specifically, I will replace "Edit with multiple Vims" with "Edit with Vim using tabpages".

**Comment by gdupras** [comment]
Done in  83cd0156e01b. This todo item can be removed:

https://github.com/vim/vim/blob/60dc8274e9f8c6a20d54efebc7a8752fe062eead/runtime/doc/todo.txt#L308-L309
