### ISSUE TITLE
Vim9: should we disallow a space between an option name and a modifier?

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8408]
Right now, we can separate an option name from its modifier with a space:
```vim
vim9script
set hlsearch !
```
    no error

Should an error be given?

Note that it would be consistent with the `!` bang argument which can be appended to many command names:
```vim
vim9script
retab!
```
    no error
```vim
vim9script
retab !
```
    E474: Invalid argument

Notice that the last command gives an error (BTW, the message would be more clear if the argument was printed instead of being omitted), because a space separates the command name from the bang.

Also, it would make the code a little more readable.  Right now, if we're a bit tired, we might read this bang modifier as a logical not:
```vim
vim9script
set hlsearch ! wrap
```
Here, we might somehow think that `!` inverts the value of the `wrap` token, while in reality, it's the opposite: it inverts the value of the `hlsearch` token.

There would be no risk of such confusion if an error was given, and we were forced to write:
```vim
vim9script
set hlsearch! wrap
```
---

Similarly, should we enforce a space before and/or after a bar used as a termination symbol?

          ✘
          v
    eval 1|eval 2

    eval 1 | eval 2
          ^ ^
          ✔ ✔

Rationale: it's more readable, and might be a bit easier to parse when writing a syntax highlighting plugin.

---

The fact that we can omit spaces around `|` lets us write this kind of thing:

    set hlsearch&|eval 0

Here, `&|` looks a bit weird.  It looks like the equally weird `|&` bash control operator.

This would be less weird:

    set hlsearch& | eval 0
                 ^ ^

**Comment by brammool** [comment]
> Right now, we can separate an option name from its modifier with a space:
> ```vim
> vim9script
> set hlsearch !
> ```
>     no error
> 
> Should an error be given?
> 
> Note that it would be consistent with the `!` bang argument which can be appended to many command names:
> ```vim
> vim9script
> retab!
> ```
>     no error
> ```vim
> vim9script
> retab !
> ```
>     E474: Invalid argument
> 
> Notice that the last command gives an error (BTW, the message would be more clear if the argument was printed instead of being omitted), because a space separates the command name from the bang.
> 
> Also, it would make the code a little more readable.  Right now, if we're a bit tired, we might read this bang modifier as a logical not:
> ```vim
> vim9script
> set hlsearch ! wrap
> ```
> Here, we might somehow think that `!` inverts the value of the `wrap` token, while in reality, it's the opposite: it inverts the value of the `hlsearch` token.
> 
> There would be no risk of such confusion if an error was given, and we were forced to write:
> ```vim
> vim9script
> set hlsearch! wrap
> ```
> ---
> 
> Similarly, should we enforce a space before and/or after a bar used as a termination symbol?
> 
>           ✘
>           v
>     eval 1|eval 2
> 
>     eval 1 | eval 2
>           ^ ^
>           ✔ ✔
> 
> Rationale: it's more readable, and might be a bit easier to parse when writing a syntax highlighting plugin.
> 
> ---
> 
> The fact that we can omit spaces around `|` lets us write this kind of thing:
> 
>     set hlsearch&|eval 0
> 
> Here, `&|` looks a bit weird.  It looks like the equally weird `|&` bash control operator.
> 
> This would be less weird:
> 
>     set hlsearch& | eval 0
>                  ^ ^

I even forgot this is possible.  The help does not mention it.  In the
code it skips spaces manually, the comment mentions being able to put
spaces before the question mark.  I don't see why.

If I just remove skipping spaces only one test fails.  Also an
indication that it's not very useful.

-- 
hundred-and-one symptoms of being an internet addict:
22. You've already visited all the links at Yahoo and you're halfway through
    Lycos.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
Also, should we disallow a white space before an assignment operator.  This doesn't give any error:
```vim
vim9script
setlocal foldmethod =expr
```
Maybe it should.  If only because it would make the rules regarding white space symmetrical: no white space allowed after, no white space allowed before.  Right now, there is an asymmetry: no white space allowed after, but white space allowed before.

It also makes the code harder to read, because it might look like `'foldmethod'` is a boolean option which we're enabling.

I can't find any useful purpose behind this feature, other than alignment:

    set option_x   =value1
    set option_xx  =value2
    set option_xxx =value3

But those kind of alignments are brittle; they frequently break, making the code look weird ("why are there so many useless spaces here?").

**Comment by brammool** [comment]
It's even worse, currently "set foldlevel  =1" shows the value and silently ignores the "=1".
