### ISSUE TITLE
GUI blinks badly while populating quickfix from a background function (timer/channel cb)

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#841]
GUI/CUI will blink frequently while a background function (timer/channel cb) is using `caddexpr` to append text to quickfix. This issue could be reproduce from a script:

---

``` VimL
function! TimerBlink(id)
    caddexpr "TIMER: " . a:id
endfunc

let s:id = timer_start(100, 'TimerBlink', {'repeat':300})

copen 10
cexpr ""
wincmd k

tabnew %
```

---

key step to reproduce the issue:
1. open the quickfix window in the default tabpage
2. open a new tabpage (with quickfix window closed by default)

---

important: 
I am experimenting async-build with job/channel feature. and found `caddexpr` blinking is very boring especially for multi tabpage users.

environment:
vim 7.4.1856  (console)
gvim 7.4.1856 (windows)

Could it be fixed in the future release ? it is a very bad user experience.
screen capture:

![timerblink](https://cloud.githubusercontent.com/assets/3035071/15646379/dc3e4246-268f-11e6-87d4-750d92894e35.gif)

**Comment by brammool** [comment]
Linwei wrote:

> GUI/CUI will blink frequently while a background function
> (timer/channel cb) is using `caddexpr` to append text to quickfix.
> 
> ## This issue could be reproduce from a script:
> 
> ``` VimL
> function! TimerBlink(id)
>     caddexpr "TIMER: " . a:id
> endfunc
> 
> let s:id = timer_start(100, 'TimerBlink', {'repeat':300})
> 
> copen 10
> cexpr ""
> wincmd k
> 
> tabnew %
> ```
> 
> ---
> 
> key step to reproduce the issue:
> 1. open the quickfix window in the default tabpage
> 2. open a new tabpage (with quickfix window closed by default)
> 
> ---
> 
> important: 
> I am experimenting async-build with job/channel feature. and found
> `caddexpr` blinking is very boring especially for multi tabpage users.
> 
> environment:
> vim 7.4.1856  (console)
> gvim 7.4.1856 (windows)
> 
> Could it be fixed in the future release ? it is a very bad user experience.
> screen capture:
> 
> ![timerblink](https://cloud.githubusercontent.com/assets/3035071/15646379/dc3e4246-268f-11e6-87d4-750d92894e35.gif)

Possibly this is caused by updating the quickfix window.  Yegappan
suggested that adding to the quickfix list results in the quickfix
window to be refreshed, which would also cause the cursor to restart
blinking.

Does the problem go away when the quickfix window is not open?

## 

I am also told that there is a logical proof out there somewhere
that demonstrates that there is no task which duct tape cannot handle.
                    -- Paul Brannan

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by skywind3000** [comment]
In my test, quickfix windows has not been open in the current tabpage (tabpage2) and it is only open in tabpage1 and blink frequently in tabpage2.

And as you say if I comment `copen 10` in tabpage1, it will not blink in tabpage2.

But I don't understand that I am in tabpage2, and quickfix window in tabpage2 has not been open yet, it is only open in tabpage1, why does it blink in tabpage2 ??

It is very boring in my async build script.

**Comment by brammool** [comment]
Linwei wrote:

> In my test, quickfix windows is not open in the current tabpage
> (tabpage2) and it is only open in tabpage1 and blink frequently.
> 
> And as you say if I comment `copen 10` in tabpage1, it will not blink
> in tabpage2.
> 
> But I don't understand in my case, I am in tabpage2, and quickfix
> window in tabpage2 has not been open yet, it is only open in tabpage1,
> why does it blink in tabpage2 ??

Even though the window isn't visible, it probably still triggers a
redraw.  Vim doesn't really expect hidden windows to get updated, thus
there probably is no check for the window to be hidden.

## 

One difference between a man and a machine is that a machine is quiet
when well oiled.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by skywind3000** [comment]
Since I am not familiar with the vim source code and don't have the ability to make a pull request.
I would greatly appreciate if it could be fixed in the future release.

**Comment by crzytrane** [comment]
Could using the lazyredraw flag help with this @skywind3000?

**Comment by skywind3000** [comment]
@crzytrane lazyredraw is useless here.

**Comment by skywind3000** [comment]
excited !!
