### ISSUE TITLE
Vim9: should we change the semantics of buffer 0 for "bufexists()", or change number of non-existing buffer in "getqflist()"?

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8413]
For `bufexists()` (and probably most `buf*()` functions), the number 0 stands for the alternate buffer for the current window.  From `:h bufexists()`:

   > Number zero is the alternate buffer for the current window.

Buf for `getqflist()`, 0 stands for a non-existing buffer.  From `:h getqflist()`:

   > Quickfix list entries with non-existing buffer
   > number are returned with "bufnr" set to zero.

This can lead to confusing bugs.  For example, we might parse the output of `getqflist()` to operate on the quickfix entries.  And we might need to load the buffer of an entry with `bufload()`.  If we pass it a 0 from `getqflist()` – which means a non-existing buffer – then `bufload()` won't complain; instead, it will load the alternate buffer.  This will most probably results in confusing errors later in the code.  It would be better if an error was raised as soon as we try to load the buffer.

Assuming that it's acknowledged as something which warrants a change, I don't know what's best.  In Vim9, should we change how `buf*()` functions interpret 0?  Or should we change the number used by `getqflist()` for non-existing buffers (-1 maybe)?

---

**Comment by lacygoill** [comment]
> This will most probably results in confusing errors later in the code. It would be better if an error was raised as soon as we try to load the buffer.

It did to me while I was writing some code to highlight matches in the quickfix list.  The latter might contain an entry whose buffer number is 0 (happens to me when I use `rg(1)` to look for `foobar` in the Vim codebase).  This causes a confusing error with this code:
```vim
vim9script

prop_type_add('QuickFixHighlight', {highlight: 'QuickFixLine'})

augroup QuickFixHighlight
    autocmd!
    autocmd QuickFixCmdPost * QuickFixHighlight()
augroup END

def QuickFixHighlight()
    for entry in getqflist()
        entry.bufnr->bufload()
        prop_add(entry.lnum, entry.col, {
            type: 'QuickFixHighlight',
            bufnr: entry.bufnr,
            end_lnum: entry.end_lnum == 0 ? entry.lnum : entry.end_lnum,
            end_col: entry.end_col == 0 ? entry.col : entry.end_col,
        })
    endfor
enddef

grep foobar
```
    Error detected while processing ... QuickFixCmdPost Autocommands for "*"..function <SNR>149_QuickFixHighlight:
    line    8:
    E964: Invalid column number: 0

The error is raised by `prop_add()`, which makes us think that we somehow got wrong coordinates for the matches.  In reality, we never loaded the right buffer.  We could have been warned about this if `bufload()` had given an error when receiving 0.  Or if `getqflist()` had given an invalid number.

**Comment by lacygoill** [comment]
> which makes us think that we somehow got wrong coordinates for the matches

Actually, the coordinates were all wrong in this case anyway.  Still, I think it would make sense for `bufload()` to fail one way or another.

**Comment by brammool** [comment]
> For `bufexists()` (and probably most `buf*()` functions), the number 0
> stands for the alternate buffer for the current window.  From `:h
> bufexists()`:
> 
>    > Number zero is the alternate buffer for the current window.
> 
> Buf for `getqflist()`, 0 stands for a non-existing buffer.  From `:h
> getqflist()`:
> 
>    > Quickfix list entries with non-existing buffer
>    > number are returned with "bufnr" set to zero.
> 
> This can lead to confusing bugs.  For example, we might parse the
> output of `getqflist()` to operate on the quickfix entries.  And we
> might need to load the buffer of an entry with `bufload()`.  If we
> pass it a 0 from `getqflist()` – which means a non-existing buffer –
> then `bufload()` won't complain; instead, it will load the alternate
> buffer.  This will most probably results in confusing errors later in
> the code.  It would be better if an error was raised as soon as we try
> to load the buffer.
> 
> Assuming that it's acknowledged as something which warrants a change,
> I don't know what's best.  In Vim9, should we change how `buf*()`
> functions interpret 0?  Or should we change the number used by
> `getqflist()` for non-existing buffers (-1 maybe)?

I do not think this is a change associated with Vim 9 script.  It may be
confusing, but changing it may also cause confusing bugs for existing
plugins.  Instead of changing the behavior, I think it's better to add a
note in the help.

-- 
How To Keep A Healthy Level Of Insanity:
17. When the money comes out the ATM, scream "I won!, I won! 3rd
    time this week!!!!!"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> I do not think this is a change associated with Vim 9 script.

Yes, but changing the meaning of 0, or using a different number would break the compatibility in legacy Vim scripts, which is why I suggested that the change would be limited to Vim9 (for which it seems OK to break the compatibility).

> Instead of changing the behavior, I think it's better to add a note in the help.

OK, fair enough.  I'll try to come up with a patch for the documentation later.

**Comment by brammool** [comment]
> > I do not think this is a change associated with Vim 9 script.
> 
> Yes, but changing the meaning of 0, or using a different number would
> break the compatibility in legacy Vim scripts, which is why I
> suggested that the change would be limited to Vim9 (for which it seems
> OK to break the compatibility).
> 
> > Instead of changing the behavior, I think it's better to add a note
> > in the help.
> 
> OK, fair enough.  I'll try to come up with a patch for the
> documentation later.

This is what I have now:

		When there is no error list or it's empty, an empty list is
		returned. Quickfix list entries with a non-existing buffer
		number are returned with "bufnr" set to zero (Note: some
		functions accept buffer number zero for the alternate buffer,
		you may need to explicitly check for zero).

-- 
What a wonderfully exciting cough!  Do you mind if I join you?
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
It looks good, thank you.  I assume it will be in the next update of the runtime files, so closing.
