### ISSUE TITLE
Vim9: when defining a function whose name starts with an underscore at the script level, it becomes global

### ISSUE THREAD

**Issue by obcat** [vim/vim#8414]
**Describe the bug**

In Vim9 script, when defining a function whose name starts with an underscore at the script level, the function becomes global.

**To Reproduce**

1. Run `vim --clean`.

1. Source this script:

    ```vim
    vim9script
    def _Foo()
      echo 42
    enddef
    g:_Foo()
    ```

    `42` is echoed.

**Expected behavior**

`_Foo()` becomes script-local; `E117` is raised from line 5:

```
E117: Unknown function: g:_Foo
```

**Environment**

 - Vim 8.2.2976
 - macOS Catalina (version 10.15.7)
 - iTerm2

**Comment by brammool** [comment]
The documentation states that a user function must start with a capital letter.  But there is no error when an underscore is used.
To avoid backwards compatibility problems let's only give an error in Vim9 script.

**Comment by obcat** [comment]
Indeed, I had not noticed that.
Thank you for the fix!
