### ISSUE TITLE
Vim9: should we disallow a space after :g ?

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8415]
It is allowed for `:g` to be followed by a space.  This seems inconsistent in legacy, and can give unexpected results in Vim9:

In legacy:
```vim
eval ['aaa', 'bbb']->repeat(3)->setline(1)
g x^bxd
```
Notice that all the `bbb` lines have been removed.  It means that:

   1. `x` was used as a delimiter
   2. Vim had no issue with us separating `:g` from its pattern with a space

`1.` is wrong.  Vim should not have used `x` as a delimiter, because it's an alphanumeric character.  This is documented at `:h pattern-delimiter`:

   > *pattern-delimiter* *E146*
   > Instead of the '/' which surrounds the pattern and replacement string, you
   > can use any other single-byte character, but **not an alphanumeric character**,
   > '\', '"' or '|'.  This is useful if you want to include a '/' in the search
   > pattern or replacement string.  Example: >
   > :s+/+//+

IMO, that's a bug, but that's not the point of this issue.  This issue is about `2.`.  It's inconsistent with `:s`:
```vim
call setline(1, ['aaa', 'bbb']->repeat(3))
%s x^bxrepx
```
    E146: Regular expressions can't be delimited by letters

Notice that this time, Vim didn't skip over the space.  And it didn't accept the space as a delimiter.  This is correct, and `:g` should probably behave in the same way.  I can't find anything at `:h :g` which documents that we can write a space after `:g`.

And here is another issue caused by `2.`:
```vim
vim9script
g - a - p
```
    Pattern not found:  a

Here, `g` is parsed as a command.  But it could also be read as a variable name at the start of an arithmetic computation.  Although, it's useless to evaluate this expression if we don't do anything with it...

In any case, there would be no such confusion if we disallowed the space (provided that we keep enforcing spaces around binary operators).  The previous snippet would always be interpreted as a computation.  And the next one as a global command:
```vim
vim9script
g-a-p
```

**Comment by lacygoill** [comment]
> Notice that this time, Vim didn't skip over the space.

Actually, it did skip over the space.  Still, I think it should not (because of `2.`; i.e. it helps make the code more readable in Vim9).

**Comment by lacygoill** [comment]
Never mind, all the other commands expecting a pattern accept a space between them and the pattern.

I guess the only issue is that we can use an alphanumeric character around a pattern with `:g`; that should definitely not be allowed.  I'll try to open a separate issue later.

**Comment by brammool** [comment]
Right, skipping the space is expected, but using an alphabetic character to delimit the pattern is not.
Would anybody rely on the missing check?  That would be unexpected, thus I think we can add this check.
