### ISSUE TITLE
Vim9: crash when using `[a, b, ...] += {expr}` syntax in `:def` function

### ISSUE THREAD

**Issue by obcat** [vim/vim#8416]
**Describe the bug**

In Vim9 script, using the `[a, b, ...] += {expr}` syntax in a `:def` function causes a crash.

**To Reproduce**

1. Run `vim --clean`.

1. Source this script:

    ```vim
    vim9script
    def Test()
      var a = 1
      var b = 3
      [a, b] += [2, 4]
    enddef
    defcompile
    ```

    Vim crashes.

**Expected behavior**

Vim does not crash.

**Environment**

 - Vim 8.2.3027
 - macOS Catalina (version 10.15.7)
 - iTerm2

**Comment by lacygoill** [comment]
- [backtrace](https://github.com/vim/vim/files/6686111/backtrace.txt)
- [valgrind log](https://github.com/vim/vim/files/6686112/valgrind.log)
- [asan log](https://github.com/vim/vim/files/6686110/asan.log)

According to valgrind and asan, the issue starts from line 1249 in `src/vim9compile.c` where an invalid read of size 8 occurs:

    type_T	*type = ((type_T **)stack->ga_data)[stack->ga_len - 1];

https://github.com/vim/vim/blob/2ac4b2536a40e5cd75b4ff7a3d44a282d2f4f008/src/vim9compile.c#L1249

**Comment by obcat** [comment]
So fast, thanks a lot!
