### ISSUE TITLE
Add Autocommand for when the DPI of the gui changes

### ISSUE THREAD

**Issue by MartyLake** [vim/vim#8417]
First, thanks for creating and maintaining VIM.
Second, if it’s already possible to do so, excuse my `:he`-foo.

**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
On Windows, with gvim, it is difficult to read the font "Terminus:h9" when dpi is 200% on the hidpi laptop screen, so I want to change the font to "Noto_Mono:h9". But I prefer to have the font "Terminus:h9" when the gvim window is displayed on the1080p secondary desktop screen.

**Describe the solution you'd like**
I wish to have an autocommand for when the DPI of the gui changes. with this, I could conditionally choose which font I prefer.

**Describe alternatives you've considered**
The alternative right now is to change the font manually when I switch from laptop only setup to desktop secondary screen setup. It works, but it’s manual.

**Additional context**

**Comment by k-takata** [comment]
Currently, gvim doesn't support per-monitor DPI and I think PermonitorV2 should be supported.
I'm not sure if such autocommand is useful even if PermonitorV2 would be supported.

**Comment by k-takata** [comment]
PerMonitorV2 is supported since 8.2.4109.
I think that such an autocommand is not needed any more.

**Comment by chrisbra** [comment]
Closing then.
