### ISSUE TITLE
Segfault when passing a "Vim script" lambda to a "Vim9 script" function

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#8422]
**To Reproduce**
Detailed steps to reproduce the behavior:
1. Create the following `foo.vim` script in some autoload directory:

    ```vim
    vim9script
    def foo#F(x: func(string): list<string>)
    enddef
    ```
2. Run `vim --clean` (or `gvim --clean`, etc.)
3. Make sure that the autoload directory is in your runtime path; if not, add it to `rtp`.
3. Define the following command:

    ```vim
    command! -nargs=0 Foo call foo#F({v -> [v]})
    ```

3. Execute `:Foo`
4. You should see Vim crash.

**Environment (please complete the following information):**
 - Vim 8.2.3025
 - OS: macOS 11.3.1
 - Terminal: Apple Terminal

**Comment by lacygoill** [comment]
Simplified MWE:
```vim
vim9script
def g:Func(f: func())
enddef
legacy call g:Func({-> 0})
```
Not sure it's the same crash though.

It stops crashing once we remove the parens in the return type of the function argument:

    def g:Func(f: func())
                      ^^

Without those, Vim assumes any arguments, and any return type.
With those, Vim assumes no arguments, and the void return type.

---

- [backtrace.txt](https://github.com/vim/vim/files/6689855/backtrace.txt)
- [valgrind log](https://github.com/vim/vim/files/6689856/valgrind.log)
- [asan log](https://github.com/vim/vim/files/6689854/asan.log)

---

asan reports a heap-buffer-overflow error on line 37 in `src/vim9type.c`:

https://github.com/vim/vim/blob/419a40ac9657e39646b2e0f3f71d7736b0c459d1/src/vim9type.c#L37

	((type_T **)type_gap->ga_data)[type_gap->ga_len] = type;
