### ISSUE TITLE
Gemtext syntax highlighting in Vim

### ISSUE THREAD

**Issue by ghost** [vim/vim#8427]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
No, shouldn't be hard.

**Describe the solution you'd like**
Syntax highlighting for Gemtext (mime-type = text/gemini), a Markdown-like markup language used in the [Gemini protocol](https://gemini.circumlunar.space) which is an alternative to the Modern World Wide Web.

**Describe alternatives you've considered**
N/A

**Additional context**
Gemtext is generally represented by a `.gmi` file extension.
[Introduction to Gemtext](https://gemini.circumlunar.space/docs/gemtext.gmi)
[Gemtext CheatSheet](https://gemini.circumlunar.space/docs/cheatsheet.gmi)

**Comment by chrisbra** [comment]
Looks like there already exists https://github.com/SuneelFreimuth/vim-gemtext Please test this plugin. If it works well, you might want to request from its authors to send the runtime files to Vim for distribution with vim.

**Comment by chrisbra** [comment]
hi @LordRishav are you going to request inclusion for a specific plugin? If not, I am going to close this issue here. Thanks for understanding.

**Comment by LordRishav** [comment]
Oh, sorry for responding late. I tried the plugin which you shared, and as I use Vim 8 packages rather than third-party ones like vim-plug and Vundle, I had some difficulty in installing that plugin. I looked at Vim help pages for packages, and tried to install it accordingly, but still couldn't get it to work. I'll try to install it through vim-plug in a container and reach out to you if I get it to work. Thank you!

**Comment by LordRishav** [comment]
Alright, I tried it with vim-plug and it works. I have contacted the maker of the plugin SuneelFreimuth/vim-gemtext to help in inclusion of the syntax support in Vim distribution by filing an issue.

**Comment by brammool** [comment]
Unfortunately, when searching for "gemtext" and "gmi" it's not obvious these are related.  Can we have some motivation why .gmi files would be associated with the "gemtext" filetype?  Perhaps there are better names?

**Comment by LordRishav** [comment]
I searched about the .gmi extension with a search engine, and came to know that it is used by an application called GPS Tuner, for its Map Calibration Data. The gmi files used by GPS Tuner have the mimetype application/octet-stream. I don't think someone will open a binary file like this in a text editor, as it will just render stuff that can't be easily read. Whereas, the other type of .gmi file is completely human-readable, and someone would want to open such a file in an editor to edit it.

**Comment by brammool** [comment]
> I searched about the .gmi extension with a search engine, and came to
> know that it is used by an application called GPS Tuner, for its Map
> Calibration Data. The gmi files used by GPS Tuner have the mimetype
> application/octet-stream. I don't think someone will open a binary
> file like this in a text editor, as it will just render stuff that
> can't be easily read. Whereas, the other type of .gmi file is
> completely human-readable, and someone would want to open such a file
> in an editor to edit it.

OK, we can ignore those GPS files then.

There also is https://githubmemory.com/repo/kconner/vim-syntax-gemtext
So .gemini is also used?

-- 
hundred-and-one symptoms of being an internet addict:
77. The phone company asks you to test drive their new PBX system

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by LordRishav** [comment]
@brammool I think so, I haven't seen a Gemini capsule (equivalent to a 'website') using pages with a .gemini extension. There are no applications that use .gemini files other than the Gemini protocol, as far as I know. So it will be good to have this file extension recognized as gemtext too.

**Comment by brammool** [comment]
> @brammool I think so, I haven't seen a Gemini capsule (equivalent to a
> 'website') using pages with a .gemini extension. There are no
> applications that use .gemini files other than the Gemini protocol, as
> far as I know. So it will be good to have this file extension
> recognized as gemtext too.

I'll add a patch to recognize the filetype.  You can continue to persue
the syntax file is sent to me, we don't need an issue for that.

-- 
hundred-and-one symptoms of being an internet addict:
80. At parties, you introduce your spouse as your "service provider."

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by LordRishav** [comment]
@brammool Can't you use [SuneilFreimuth/vim-gemtext's syntax file ](https://github.com/SuneelFreimuth/vim-gemtext/blob/main/syntax/gemtext.vim) as the syntax file :smiley: ? Is that because of licensing issues?

**Comment by brammool** [comment]
I very much prefer the author of the file to send it to me or create a PR, so that it's clear  the author wants that file to be included in the distribution.

**Comment by LordRishav** [comment]
Oh alright, I'll wait for the author of the plugin to respond to my issue on their repository. Thank you

**Comment by SuneelFreimuth** [comment]
> I very much prefer the author of the file to send it to me or create a PR, so that it's clear the author wants that file to be included in the distribution.

Author of vim-gemtext here--my apologies for not noticing @LordRishav's issue on the repo. I would be happy to contribute syntax support for Gemtext files. Should I open a new issue to discuss this?

**Comment by LordRishav** [comment]
cc @brammool

**Comment by brammool** [comment]
Suneel Freimuth wrote:

> > I very much prefer the author of the file to send it to me or create
> > a PR, so that it's clear the author wants that file to be included
> > in the distribution.
> 
> Author of vim-gemtext here--my apologies for not noticing
> @LordRishav's issue on the repo. I would be happy to contribute syntax
> support for Gemtext files. Should I open a new issue to discuss this? 

I'm glad you agree with including the files.  The simplest is if you
email them to me.  Or create a pull request if you can, then others can
check and give comments.

-- 
FATHER: We are here today to witness the union of two young people in the
        joyful bond of the holy wedlock.  Unfortunately, one of them, my son
        Herbert, has just fallen to his death.
   [Murmurs from CROWD;  the BRIDE smiles with relief, coughs.]
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by SuneelFreimuth** [comment]
Got it, I will send them to you by email.
