### ISSUE TITLE
.swp file created with 0644 mode

### ISSUE THREAD

**Issue by profcav** [vim/vim#8436]
**Describe the bug**
When I open a file that has a 0664 mode, .swp file is created with 0644 mode
If another user opens the same file, my .swp file is deleted and a new .swp file for the other user is created
If .swp file has 0600 mode, the other user gets the message that the file is already open by another user

**To Reproduce**
*user1*
- touch newfile
- chmod 644 newfile
- vim newfile

*user2*
- ls -al .newfile.swp
output: -rw-r--r-- .newfile.swp
- vim newfile 
result: user2 open file newfile without any message

**Expected behavior**
user2 should receive the message "Found a swap file by the name .newfile.swp"

**Environment (please complete the following information):**
 - Vim version 
VIM - Vi IMproved 8.1 (2018 May 18, compilato Apr 15 2020 06:40:31)
Patch incluse: 1-2269
 - OS: Ubuntu 20.04

**Comment by chrisbra** [comment]
I think you only receive the swap file exists dialogue, if the user matches. However, something is strange here:

1) The Vim from user2 should notice, it cannot edit the file. The 'readonly' option should be set, preventing user 2 from making some changes.
2) The Vim from user2 should create a new swapfile and not silently remove the swapfile from user1. Check using the `:swapname` command.

You may want to verify using `vim --clean` and probably also using the latest master version.

**Comment by profcav** [comment]
new version:
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun 23 2021 15:22:17)
Included patches: 1-3036

used "vim --clean" 

same behaviour

**Comment by chrisbra** [comment]
still deleting the swapfile? Are you sure? and it did not create a new swapfile for the second user?

**Comment by brammool** [comment]
What are the permissions of the directory?  I suspect the other user can write.

**Comment by profcav** [comment]
> still deleting the swapfile? Are you sure? and it did not create a new swapfile for the second user?

when the second user open the file, vim remove the swapfile of the first user and create a new swapfile
if you trace the process:

if .swp file has permissions 600, second user can't read the file and all is ok
if .swp file has permissions 644, second user can read the file, read the process id in the file, try to kill the process to see if it is alive, but the process belongs to another user, so kill fails (EPERM); vim thinks that the process does not exist and remove .swp file and continue creating a new one

I think the problem are the permissions of .swp file

if I create a new file, .swp file has permissions 0600

**Comment by brammool** [comment]
Are you sure the directory permissions are 664?  That would explain it, without execute permission it is not possible to check if a file exists.  You need to make the directory 775.

**Comment by profcav** [comment]
sorry. you are right of course
the directory permissions are 775

**Comment by chrisbra** [comment]
https://github.com/vim/vim/blob/cc6504098605f894b557109b618e88913a89914b/src/memline.c#L2307-L2315
```c
    // process must be known and not be running
    if (char_to_long(b0.b0_pid) == 0L || swapfile_process_running(&b0, fname))
	ret = FALSE;
#endif

    // We do not check the user, it should be irrelevant for whether the swap
    // file is still useful.

    close(fd);
```

But if the swapfile belongs to a different user, swapfile_process_running() fails, which Vim interprets as the process is not running and can therefore delete the file. In that case, we should check the user (and the comment is in that case confusing)

**Comment by tonymec** [comment]
You are using Vim 8.1.2269 dated more than a year ago. The latest version is 8.2.3038. I don't see or remember changes which could have fixed your problem, but who knows?

You'l find a one-line description of each patch at (depending on version)
http://ftp.vim.org/pub/vim/patches/8.1/
http://ftp.vim.org/pub/vim/patches/8.2/

Best regards,
Tony.

**Comment by profcav** [comment]
already updated, new version:
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun 23 2021 15:22:17)
Included patches: 1-3036
same behaviour
thanks

**Comment by profcav** [comment]
> https://github.com/vim/vim/blob/cc6504098605f894b557109b618e88913a89914b/src/memline.c#L2307-L2315
> 
> ```c
>     // process must be known and not be running
>     if (char_to_long(b0.b0_pid) == 0L || swapfile_process_running(&b0, fname))
> 	ret = FALSE;
> #endif
> 
>     // We do not check the user, it should be irrelevant for whether the swap
>     // file is still useful.
> 
>     close(fd);
> ```
> 
> But if the swapfile belongs to a different user, swapfile_process_running() fails, which Vim interprets as the process is not running and can therefore delete the file. In that case, we should check the user (and the comment is in that case confusing)

yes this seems to be my case
but I can't understand why the swap file is created with permissions different from 600. That resolves the issue

**Comment by brammool** [comment]
> > https://github.com/vim/vim/blob/cc6504098605f894b557109b618e88913a89914b/src/memline.c#L2307-L2315
> > 
> > ```c
> >     // process must be known and not be running
> >     if (char_to_long(b0.b0_pid) == 0L || swapfile_process_running(&b0, fname))
> > 	ret = FALSE;
> > #endif
> > 
> >     // We do not check the user, it should be irrelevant for whether the swap
> >     // file is still useful.
> > 
> >     close(fd);
> > ```
> > 
> > But if the swapfile belongs to a different user, swapfile_process_running() fails, which Vim interprets as the process is not running and can therefore delete the file. In that case, we should check the user (and the comment is in that case confusing)
> 
> yes this seems to be my case
> but I can't understand why the swap file is created with permissions
> different from 600. That resolves the issue

Because if you can edit the file, you should be able to recover it from
the swapfile, if needed.

It appears the mch_process_running() function should check for the ESRCH
error.  Another error is EPERM, which does not mean the process
finished.  I assume this will fix the problem, please reopen the issue
if it doesn't.

Let me make a patch for that.  I'm not sure how to test this, we can't
just do something as another user.

-- 
"So this is it," said Arthur, "we are going to die."
"Yes," said Ford, "except...no!  Wait a minute!"  He suddenly lunged across
the chamber at something behind Arthur's line of vision.  "What's this
switch?" he cried.
"What?   Where?" cried Arthur, twisting around.
"No, I was only fooling," said Ford, "we are going to die after all."
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
