### ISSUE TITLE
Vim9: no proper error for incorrect usage of "++" operator

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8440]
**Describe the bug**

In Vim9 script, a confusing error is given when we use the increment `++` operator incorrectly.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        var n: number = 123
        ++ n
        echo n
    EOF
    )

`E488` is raised with this message:

    E488: Trailing characters:  n += 1

Run this other shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        var n: number = 123
        def Func(): number
            return n
        enddef
        ++Func()
        echo n
    EOF
    )

`E488` is – again – raised, with this other message:

    E488: Trailing characters: () += 1

**Expected behavior**

We never explicitly wrote `+= 1`, so the current messages are confusing (especially the second one).

I would expect proper errors to be given, like:

    E1234: No space allowed after "++"

And:

    E1235: "Func()" is not a valid identifier

**Environment**

 - Vim version: 8.2 Included patches: 1-3039
 - OS: Ubuntu 20.04.2 LTS
 - Terminal: XTerm(353)

**Additional context**

Same issue with the decrement operator `--`.
```vim
vim9script
var n: number = 123
-- n
echo n
```
    E488: Trailing characters:  n -= 1
```vim
vim9script
var n: number = 123
def Func(): number
    return n
enddef
--Func()
echo n
```
    E488: Trailing characters: () -= 1

---

Unrelated, but why are the operators `++` and `--` considered to be commands?
They are suggested when we use tab completion on the command-line, and they're given by `getcompletion()`:
```vim
echo getcompletion('[-+]', 'command')
```
    ['++', '--']

---

Also, I can't find where they are documented.  The only reference I can find at `:h vim9` is this one:

   > In legacy script "++var" and "--var" would be silently accepted and have no
   > effect.  This is an error in Vim9 script.

Which I don't understand.  `++var` and `--var` are not silently accepted in legacy; they give errors:
```vim
let var = 123
++var
```
    E481: No range allowed: ++var
```vim
let var = 123
--var
```
    E481: No range allowed: --var

And they are not silently accepted in Vim9 either; they're working as intended (i.e. they increment or decrement a variable).  Unless it refers to this:
```vim
vim9script
var name = 0
echo ++name
```
    E15: Invalid expression: "++name"

I suspect that the "silently accepted" part refers to a period where `++var` had not been implemented yet, and did not give an error either.  This was changed in this patch:

   - [8.2.2305](https://github.com/vim/vim/releases/tag/v8.2.2305)  Vim9: "++var" and "--var" are silently accepted

But since then, the operators have been implemented.  In a later patch:

   - [8.2.2806](https://github.com/vim/vim/releases/tag/v8.2.2806)  Vim9: using "++nr" as a command might not work

Maybe this part of the documentation is not up to date?

**Comment by lacygoill** [comment]
> Unrelated, but why are the operators ++ and -- considered to be commands?

Forget about this part.  Reading the comments in the source code of the patch 8.2.2806, it seems to be a detail of implementation.

**Comment by lacygoill** [comment]
> E1235: "Func()" is not a valid identifier

Or maybe:

    E1235: "++" must be followed by a valid identifier

**Comment by brammool** [comment]
> **Describe the bug**
> 
> In Vim9 script, a confusing error is given when we misuse the increment `++` operator.
> 
> **To Reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(cat <<'EOF'
>         vim9script
>         var n: number = 123
>         ++ n
>         echo n
>     EOF
>     )
> 
>     E488: Trailing characters:  n += 1

I'll fix this.

> Run this other shell command:
> 
>     vim -Nu NONE -S <(cat <<'EOF'
>         vim9script
>         var n: number = 123
>         def Func(): number
>             return n
>         enddef
>         ++Func()
>         echo n
>     EOF
>     )
> 
>     E488: Trailing characters: () += 1

This is tricky, because the "++" command is translated into an
assignment with an operator.  Not sure if this can be made better
without a lot of work.


> **Expected behavior**
> 
> We never explicitly wrote `+= 1`, so the current messages are confusing (especially the second one).
> 
> I would expect proper errors to be given, like:
> 
>     E1234: No space allowed after "++"
> 
> And:
> 
>     E1235: "Func()" is not a valid identifier
> 
> **Environment**
> 
>  - Vim version: 8.2 Included patches: 1-3039
>  - OS: Ubuntu 20.04.2 LTS
>  - Terminal: XTerm(353)
> 
> **Additional context**
> 
> Same issue with the decrement operator `--`.
> ```vim
> vim9script
> var n: number = 123
> -- n
> echo n
> ```
>     E488: Trailing characters:  n -= 1
> ```vim
> vim9script
> var n: number = 123
> def Func(): number
>     return n
> enddef
> --Func()
> echo n
> ```
>     E488: Trailing characters: () -= 1
> 
> ---
> 
> Unrelated, but why are the operators `++` and `--` considered to be commands?
> They are suggested when we use tab completion on the command-line, and
> they're given by `getcompletion()`:
> ```vim
> echo getcompletion('[-+]', 'command')
> ```
>     ['++', '--']
> ---
> 
> Also, I can't find where they are documented.  The only reference I can find at `:h vim9` is this one:

I was thinking of supporting ++ and -- as part of an expression, but
that turned out to be quite complicated, thus I postponed it.  Then I
forgot to add documention.  I'll add some now.
 
>    > In legacy script "++var" and "--var" would be silently accepted and have no
>    > effect.  This is an error in Vim9 script.
> 
> Which I don't understand.  `++var` and `--var` are not silently
> accepted in legacy; they give errors:
> ```vim
> let var = 123
> ++var
> ```
>     E481: No range allowed: ++var
> ```vim
> let var = 123
> --var
> ```
>     E481: No range allowed: --var
> 
> And they are not silently accepted in Vim9 either; they're working as
> intended (i.e. they increment or decrement a variable).  Unless it
> refers to this:
> ```vim
> vim9script
> var name = 0
> echo ++name
> ```
>     E15: Invalid expression: "++name"

In legacy script this remark applies to expressions, since using + or -
at the start of a command refers to the range.

> I suspect that the "silently accepted" part refers to a period where
> `++var` had not been implemented yet, and did not give an error
> either.  This was changed in this patch:
> 
>    - [8.2.2305](https://github.com/vim/vim/releases/tag/v8.2.2305)  Vim9: "++var" and "--var" are silently accepted
> 
> But since then, the operators have been implemented.  In a later patch:
> 
>    - [8.2.2806](https://github.com/vim/vim/releases/tag/v8.2.2806)  Vim9: using "++nr" as a command might not work
> 
> Maybe this part of the documentation is not up to date?

-- 
hundred-and-one symptoms of being an internet addict:
30. Even though you died last week, you've managed to retain OPS on your
    favorite IRC channel.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> This is tricky, because the "++" command is translated into an
> assignment with an operator.  Not sure if this can be made better
> without a lot of work.

I naively thought Vim could check the validity of the argument of `:++` before translating the command.  It's not that important; I highlight it as an error:

![gif](https://user-images.githubusercontent.com/8505073/123491975-6bbc6500-d618-11eb-98a3-7b360c556f5a.gif)

---

> I was thinking of supporting ++ and -- as part of an expression, but
> that turned out to be quite complicated, thus I postponed it.

FWIW, [rust doesn't support these syntaxes](https://github.com/dtolnay/rust-faq#why-doesnt-rust-have-increment-and-decrement-operators):

> Preincrement and postincrement (and the decrement equivalents), while convenient, are also fairly complex. They require knowledge of evaluation order, and often lead to subtle bugs and undefined behavior in C and C++. x = x + 1 or x += 1 is only slightly longer, but unambiguous.

I wanted to know why, and found [this answer](https://stackoverflow.com/a/971382) which gives these assignments:

    ++i = i++;
    i = i++ + ++i;

It seems that extending `++` from a simple command to a real operator could be (ab)used to write confusing code such as the previous lines.  And it might create subtle bugs or corner cases.  Maybe it should be postponed indefinitely; or at least until enough people ask for it.

**Comment by brammool** [comment]
> > I was thinking of supporting ++ and -- as part of an expression, but
> > that turned out to be quite complicated, thus I postponed it.
> 
> FWIW, [rust doesn't support these syntaxes](https://github.com/dtolnay/rust-faq#why-doesnt-rust-have-increment-and-decrement-operators):
> 
> > Preincrement and postincrement (and the decrement equivalents), while convenient, are also fairly complex. They require knowledge of evaluation order, and often lead to subtle bugs and undefined behavior in C and C++. x = x + 1 or x += 1 is only slightly longer, but unambiguous.
> 
> I wanted to know why, and found [this answer](https://stackoverflow.com/a/971382) which gives these assignments:
> 
>     ++i = i++;
>     i = i++ + ++i;
> 
> It seems that extending `++` from a simple command to a real operator
> could be (ab)used to write confusing code such as the previous lines.
> And it might create subtle bugs or corner cases.  Maybe it should be
> postponed indefinitely; or at least until enough people ask for it.

These examples are not useful code.  In most situations using "++" is
just convenient and easy to understand.  The argument "x = x + 1 is
only slightly longer" is not really true:
	var = list[idx++]
vs
	var = list[idx]
	idx = idx + 1
or
	var = list[idx]
	idx += 1

That's an extra statement.  Anyway, it can be added later.

-- 
He who laughs last, thinks slowest.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
