### ISSUE TITLE
Is there any way to colorize -ls command through the  :!ls in vim file?

### ISSUE THREAD

**Issue by Rassska** [vim/vim#8443]
**Describe the solution you'd like**
Would be great to colorize all directory/file names after writing ```:!ls``` directly from changing document! 

**Additional context**
![Screenshot from 2021-06-24 09-49-26](https://user-images.githubusercontent.com/73281386/123215758-820bd900-d4d1-11eb-98e6-2becd8102a4c.png)

**Comment by chrisbra** [comment]
does it work if you use `:ls --color`?

**Comment by Rassska** [comment]
> does it work if you use `:ls --color`?

U r right, thank you!
