### ISSUE TITLE
New commands zy and zp behave badly with virtualedit=block

### ISSUE THREAD

**Issue by the42** [vim/vim#8448]
**Describe the bug**
The recent introduction of zy and zp-commands causes bad interaction with the virtualedit=block behaviour up to the point I consider it a bug.

For context it is best to read first through an explanation given here: https://groups.google.com/g/vim_dev/c/CAvidJJNedo

**To Reproduce**
set virtualedit=block

Enter in a new buffer:

```
aa
bbbbb
ccc

xx
gghhj
rtzu
```

`gg<C-v>3j$zy`  (block select the first three lines, extending to the end of the line each). Note the use of the `zy`command

go to the first xx in the buffer. Either issue `P` or `zP`.

**Expected behavior**
```
aaxx
bbbbbgghhj
cccrtzu
```

**Actual behaviour**
```
aaa________xx
bbdfgdfgdfdfgdfgdfs
fds________vbv
```

With `ve=block` the new z-modifier to `y` as well as `p` (or `P`fwiw) get ignored. This behaviour is counterintuitive up to the point I consider it a bug.

I would expect at least if `C-v$` is used to block select up to the end of the line, a zy would discard trailing blanks even when `ve=block` is set

**Comment by chrisbra** [comment]
I'll have a look later this weekend.
