### ISSUE TITLE
segfault when trying to encrypt a file with xchacha20 when an undofile exists

### ISSUE THREAD

**Issue by arp242** [vim/vim#8467]
The undofile got disabled for xchacha20, but looks like there are some problems if there's already an undofile; with `set undofile` in my vimrc:

```
$ vim newfile
"newfile" [New]

:set cm=blowfish2
:X

" Make some changes

:wq
"newfile" [New][blowfish2] 1L, 7B written
```

Okay, now:

```
$ vim newfile
Enter encryption key:
"newfile" [blowfish2] 1L, 7B

:set cryptmethod=xchacha20
:w 

"newfile" [New][xchacha20] 1L, 7B written
```

Okay, that worked, but opening it gives me a segfault after entering my password (`a` here for testing):

```
$ vim newfile
Need encryption key for "newfile"
Enter encryption key: *
Note: Encryption of swapfile not supported, disabling swap- and undofile
Vim: Caught deadly signal SEGV
zsh: segmentation fault  vim -p newfile
```

In another example it segfaulted in step 2 (trying to first write as xchacha20); maybe because this is an older file with a longer history/undo file? I rm'd the undo file, copied the backup I made back, and then it didn't segfault. I can't readily reproduce that now any more (even when I make sure there's an undo file by making some changes in the blowfish file).

Either way, that also seems related to the undofile.

Vim 8.2.3061 054794c20 on Linux with libsodium 1.0.18

**Comment by brammool** [comment]
I'll fix the crash, but what should really happen is that the undo file is deleted.

**Comment by brammool** [comment]
Also, when 'cryptmethod' is set to "xchacha20", 'undofile' is still set.  Perhaps it's best to set it when writing or reading a file, so that 'cryptmethod' can be set without side effect until actually writing.  Since that is applying the current option values to the file.  Also that's when the undo file would be deleted, since it's no longer valid.  When reading we can simply ignore an existing undo file.

**Comment by chrisbra** [comment]
I am confused. Anything more to do for encryption here? Not sure if there is anything expected here from me 😕

**Comment by arp242** [comment]
Seems good after I update: it no longer crashes. But I'm not sure if Bram wanted to do something else based on his comments(?)

**Comment by brammool** [comment]
What still needs to be done is when writing a file, if the crypt method used is "xchacha20", then reset 'undofile' and make sure any existing undo file is deleted (it's invalid and might contain text that is now encrypted).
Then when changing 'cryptmethod' there is no need to reset 'undofile'.

**Comment by chrisbra** [comment]
I'll have a look. But it will take me some time.

**Comment by chrisbra** [comment]
okay, I think I have done that in #8630
