### ISSUE TITLE
xxd utility reports the same "version" regardless of actual version

### ISSUE THREAD

**Issue by asmunder** [vim/vim#8472]
When running `xxd --version` the response is always `xxd V1.10 27oct98 by Juergen Weigert`, regardless of actual version.

This caused me quite some confusion when trying to figure out why `xxd -e file.dat` was working fine on some machines but failing on others. The useful `-e` flag to swap endianness was introduced in more recent versions.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `xxd -e file.dat` on a machine with Vim version 8.1
2. As expected, a hexdump is produced with endianness swapped
3. Run `xxd -e file.dat` on a machine with Vim version 7.4
4. Usage instructions for xxd are printed, no hexdump is produced.
5. "Aha, maybe the xxd is an old version"
6. Run `xxd -v` on both machines
7. Both machines print the same version string.

**Expected behavior**
I expect the xxd utility to show different version strings for binaries that have different capabilities.

**Environment (please complete the following information):**
 - Vim versions 7.4 and 8.1 tested
 - OS: ArchLinux, RHEL 7.7
 - Terminal: urxvt

**Comment by brammool** [comment]
Yeah, the version string was never updated: "xxd V1.10 27oct98 by Juergen Weigert"
Perhaps we can make it "xxd by Juergen Weigert; 2020-02-04".
Since the last change mentioned in the comments is "04.02.2020  Add -d for decimal offsets by Aapo Rantalainen".
I don't know about the version number, it doesn't seem useful now.

**Comment by brammool** [comment]
@jnweigert

**Comment by jnweiger** [comment]
That definitly needs a facelift! Thank you @asmunder for raising the issue!
We failed to give proper credit to the contributors to xxd since 1998, my apologies.

**Comment by asmunder** [comment]
The proposed change in #8475 looks good to me.
I agree that it makes sense to switch to using the date of latest change instead of version number.

And thanks for creating xxd ! It has been immensely helpful in many occasions. The most recent one that spurred this issue involves using xxd to process a ~3 TB scientific dataset generated by an older Fortran code, so that it can be read from Python (Numpy).

**Comment by jnweiger** [comment]
xxd seems to attract the most hillarous use cases.
Connect Fortran with Python at scale -- great success story! :heart:

**Comment by k-takata** [comment]
Fixed by [8.2.3075](https://github.com/vim/vim/commit/80b2ba3e9602e09ab523e78946fbb26da311b68b).
