### ISSUE TITLE
Does not keep the aspect ratio when switching from smaller screen to larger screen. 

### ISSUE THREAD

**Issue by pranjaldoshi96** [vim/vim#8473]
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Describe the bug**
After splitting screen using `sp` if we move to some bigger monitor aspect ration get dis-propertionate. 

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim` on any 14'' (inch )screen
2. Split screen using `sp`
3. Move your terminal to some bigger screen (24'' inch)
4. You'll see change in aspect ratio.

**Expected behavior**
partition shape should not change in bigger screen.

**Screenshots**
![main](https://user-images.githubusercontent.com/25930426/123636873-fc728b00-d83a-11eb-8396-6cd11ee50345.PNG)
![new](https://user-images.githubusercontent.com/25930426/123636943-0c8a6a80-d83b-11eb-8eac-f332d5219908.PNG)

**Environment (please complete the following information):**
 - VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 13 2020 15:49:09)
Included patches: 1-1453

 - OS: [Ubuntu 18.04]
 - Terminal: GNOME Terminal

**Comment by brammool** [comment]
I see this also when resizing a terminal (with the mouse).
What happens is that the change in size is applied to the last window (until it runs out of space).
I'm not sure if this should be called a bug.  When increasing the size we could also make other windows bigger, but when reducing the size keeping the aspect ratio isn't that easy.
