### ISSUE TITLE
getmousepos().column returns "the length of the text in bytes" plus one

### ISSUE THREAD

**Issue by dstein64** [vim/vim#8474]
**Describe the bug**

`getmousepos().column` returns "the length of the text in bytes" plus one

**To Reproduce**

1. Run `vim --clean` (or `gvim --clean`, etc.)
2. Insert text "hello"
3. Click on the line of text, to the right of "hello"
4. `:echo getmousepos().column`
5. Output of `6`

**Expected behavior**

Output of `5`, since `:help getmousepos()` says "When the position is after the text then 'column' is the length of the text in bytes" and the length of "hello" is 5 bytes.

**Environment (please complete the following information):**
 - Vim version: 8.2.3070
 - OS: Ubuntu 21.04
 - Terminal: Konsole 20.12.3

**Comment by brammool** [comment]
This is a mistake in the help text.  Clicking after the last character returns one more.  Otherwise you would not be able to tell the difference between clicking on the last character.  I'll update the help.

**Comment by dstein64** [comment]
Thanks!

I see that similar behavior is not present for `getmousepos().line`. For example, if I click below the `h` in the `hello` example from above, `getmousepos` returns `1` for the line. Is that the intended/desired behavior?

**Comment by brammool** [comment]
> I see that similar behavior is not present for `getmousepos().line`.
> For example, if I click below the `h` in the `hello` example from
> above, `getmousepos` returns `1` for the line. Is that the
> intended/desired behavior?

Well, there really isn't a line below the last one.  Trying to navigate
there would result in an error.  While navigating to the last column
plus one usually works.

You can use screenrow, but it's not related to the buffer text.

I rather not change how this works, it might break a plugin.

-- 
hundred-and-one symptoms of being an internet addict:
46. Your wife makes a new rule: "The computer cannot come to bed."

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
