### ISSUE TITLE
Popup windows do not respect conceallevel option

### ISSUE THREAD

**Issue by monkoose** [vim/vim#8476]
**Describe the bug**
Positioning of popup windows doesn't respect `conceallevel` option. If there are some hidden concealed characters, then popup visually would be shifted to position such as if `conceallevel=0`.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean` (or `gvim --clean`, etc.)
2. `:h getpos()`
3. `/getting`
4. `:call popup_atcursor("I'm here", {})`

**Expected behavior**
In my opinion they should be placed due to respect of `conceallevel` option.

**Screenshots**
Without concealed elements on a line
![](https://i.ibb.co/LQbKQrw/2021-06-29-17-14-33.jpg)

And there are 2 concealed elements around `line()`
![](https://i.ibb.co/p24KpMX/2021-06-29-17-14-22.jpg)

**Environment (please complete the following information):**
 - Vim version `VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 28 2021 06:58:52)
Included patches: 1-2891`
 - OS: `ArchLinux`
 - Terminal: `kitty`

**Comment by monkoose** [comment]
Hello @brammool 
Does it only fix `popup_atcursos()`? I didn't describe all problems, but the same happends if you manually get some screen position with `screenpos()` and then applying this position to `popup_create()` or `popup_move()` it will place this popup in a visually shifted (if conceallevel=0) position.

**Comment by brammool** [comment]
> Does it only fix `popup_atcursos()`? I didn't describe all problems,
> but the same happends if you manually get some screen position with
> `screenpos()` and then applying this position to `popup_create()` or
> `popup_move()` it will place this popup in a visually shifted (if
> conceallevel=0) position.

Please report each reproduction case separately.  The tricky thing is
that the cursor column is only computed when drawing the line, when
updating the cursor position in another way it won't be correct, because
concealing is too complicated to compute it then.

-- 
hundred-and-one symptoms of being an internet addict:
53. To find out what time it is, you send yourself an e-mail and check the
    "Date:" field.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> Does vim have some public functions to get concealed characters on a line?

 Not sure this is exactly what you want, but maybe have a look at `:help synconcealed()`.

 In general, when you're looking for a builtin function and you have a keyword in mind, type this on the command-line:

    :h *your_keyword*(

Then press `<C-D>` to get a list of matching help tags.

**Comment by monkoose** [comment]
@lacygoill Yes, maybe `synconcealed()` can be used. Seems like you need to process each character till the column you are needed.

I'm guess it is easier to just temporary switch conceallevel to 0, and compare `wincol()` before and after the switch.

But thanks anyway. `<C-d>` is helpful.

**Comment by monkoose** [comment]
@brammool Did some tests, and it seems like it is `screenpos()` that doesn't return correct column number.
To reproduce on the same `getting` word of the example you can get it with `:echo screenpos(0, line('.'), col('.')` before and after setting `conceallevel=0`
`wincol()` at the same time returns correct column.

**Comment by brammool** [comment]
> @brammool Did some tests, and it seems like it is `screenpos()` that
> doesn't return correct column number.
> To reproduce on the same `getting` word of the example you can get it
> with `:echo screenpos(0, line('.'), col('.')` before and after setting
> `conceallevel=0`
> `wincol()` at the same time returns correct column.

Please provide a reproduction case.  Too many details matter, I can't
guess what you are doing to see the problem.

-- 
hundred-and-one symptoms of being an internet addict:
58. You turn on your computer and turn off your wife.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
