### ISSUE TITLE
Vim9: stuck when nested try/catch fail to catch error

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8478]
**Describe the bug**

In Vim9 script, a nested try/catch failing to catch an error might cause Vim to get stuck.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            try
                eval [][0]
            catch
                try
                    eval [][0]
                catch /nothing/
                endtry
            endtry
        enddef
        Func()
    EOF
    )

Vim is stuck, and cannot be interrupted by pressing `<C-C>`.

**Expected behavior**

Vim is not stuck.

**Environment**

 - Vim version: 8.2 Included patches: 1-3075
 - OS: Ubuntu 20.04.2 LTS
 - Terminal: XTerm(353)

**Additional context**

No issue at the script level:
```vim
vim9script
try
    eval [][0]
catch
    try
        eval [][0]
    catch /nothing/
    endtry
endtry
```
    E684: list index out of range: 0

---

In the outer catch, if we specify a pattern to catch the first error (instead of catching everything), then Vim is still stuck, but can be interrupted by pressing `<C-C>`:
```vim
vim9script
def Func()
    try
        eval [][0]
    catch /E684:/
        try
            eval [][0]
        catch /nothing/
        endtry
    endtry
enddef
Func()
```
---

In the outer try, if we trigger an error with `colder` instead of `eval [][0]`, and update the pattern to still catch it specifically, then Vim is no longer stuck; however the second `eval [][0]` which is run from the inner try/catch should give an uncaught error; it does not:
```vim
vim9script
def Func()
    try
        colder
    catch /E380:/
        try
            eval [][0]
        catch /nothing/
        endtry
    endtry
enddef
Func()
```
    no error

**Comment by lacygoill** [comment]
While I was trying to find a MWE for this issue, I found something else which looks weird:

    vim -Nu <(cat <<'EOF'
        vim9script
        &showtabline = 2
        &tabline = '%{Flag()}'
        def g:Flag(): string
            eval name
            return ''
        enddef
        autocmd VimEnter * var name = 0
        var lines =<< trim END
            vim9script
            try
                eval [][0]
            catch /nothing/
            endtry
        END
        lines->writefile('/tmp/s.vim')
    EOF
    ) -S /tmp/s.vim

This gives an expected error:

    E684: list index out of range: 0

Now, press `Enter`:

    Error detected while compiling function Flag:
    line    1:
    E1001: Variable not found: name

I don't know whether this second error is expected.

It disappears if we remove the try/catch, or if we keep it but make it catch the previous error.  Maybe it means that we should not declare a script-local variable from an autocmd (even though it's technically possible)?  If so, maybe it warrants some mention in the help.

**Comment by lacygoill** [comment]
The hanging issue is fixed, but not the missing error.  This should raise `E684`:
```vim
vim9script
def Func()
    try
        eval [][0]
    catch /E684:/
        try
            eval [][0]
        catch /nothing/
        endtry
    endtry
enddef
Func()
```
It does not.  But it does at the script level:
```vim
vim9script
try
    eval [][0]
catch /E684:/
    try
        eval [][0]
    catch /nothing/
    endtry
endtry
```
    E684: list index out of range: 0

**Comment by brammool** [comment]
About that "what looks weird" example: this reads a script from stdin, not a realistic example.  I think I'll just leave it.

I'll look into the nested try not throwing an exception
