### ISSUE TITLE
gtk3vim: Patch 1899: window (re-)drawing issue

### ISSUE THREAD

**Issue by luchr** [vim/vim#848]
Steps to reproduce
1. `gtk3vim -u NONE  -U NONE -i NONE -c 'set go='`
2. Bring other window to front (so that the vim window is _partially_ overlapped)
3. Bring vim window to front again

In more than 50% of the cases my vim window is not redrawn correctly: 
[please see movie](https://gist.github.com/luchr/c274359788bf93fed22d805b7b548692#file-gtk3vim_patch1899-avi)

**Comment by brammool** [comment]
Luchr wrote:

> Steps to reproduce
> 1. `gtk3vim -u NONE  -U NONE -i NONE -c 'set go='`
> 2. Bring other window to front (so that the vim window is _partially_ overlapped)
> 3. Bring vim window to front again
> 
> In more than 50% of the cases my vim window is not redrawn correctly: 
> [please see movie](https://gist.github.com/luchr/c274359788bf93fed22d805b7b548692#file-gtk3vim_patch1899-avi)

Was this OK before patch 1899?  If so then I should probably roll it
back.

## 

"I can't complain, but sometimes I still do."   (Joe Walsh)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by luchr** [comment]
This problem does not occur for me with patch level 1898.

The idea of the patch 1899 (or a very small variant of it) was discussed on vim-dev some months ago [I unfortunately find no reference to this discussion]. There was a request to find "test-users" for a propsed patch. I tested the patch and reported the exact same problem (only on vim-dev).

The conclusion (of, I think Kazunobu Kuriyama) was, that perhaps only I have this very strange problem with this patch ... 

So: Perhaps somebody else can test this before doing a roll back.

**Comment by luchr** [comment]
I think I've finally found out, the reason why this gtk3vim rendering bug happens for me. Here I made a movie, where one can see better, what is wrong:
[Movie](https://gist.github.com/luchr/c274359788bf93fed22d805b7b548692#file-gtk3vim_redrawissue-mp4)

And here is my proposed patch:
```diff
--- gui_gtk_x11_orig.c  2017-02-19 20:31:52.196659889 +0100
+++ gui_gtk_x11.c       2017-02-19 20:32:29.439659889 +0100
@@ -687,12 +687,17 @@
            for (i = 0; i < list->num_rectangles; i++)
            {
                const cairo_rectangle_t rect = list->rectangles[i];
 
                gui_mch_clear_block(Y_2_ROW(rect.y), 1,
                        Y_2_ROW(rect.y + rect.height - 1), Columns);
+           }
+
+           for (i = 0; i < list->num_rectangles; i++)
+           {
+               const cairo_rectangle_t rect = list->rectangles[i];
 
                if (blink_mode)
                    gui_gtk3_redraw(rect.x, rect.y, rect.width, rect.height);
                else
                {
                    if (get_real_state() & VISUAL)
```

And here are my thoughts for the "why": If `num_rectangles>1` one has to clear *all* the rectangles first and then start to (re-)draw them. Otherwise (it seems) part of the already drawn rectangles are cleared if they overlap.

I really hope, this fixes this. [Since 7.4 Patch 1899 I always needed to compile my own vim 7.4 and 8.0  excluding Patch 1899 in order to make gtk3vim usable for me.]

**Comment by nuko8** [comment]
2017-02-20 4:45 GMT+09:00 luchr <notifications@github.com>:

> I think I've finally found out, the reason why this gtk3vim rendering bug
> happens for me. Here I made a movie, where one can see better, what is
> wrong:
> Movie
> <https://gist.github.com/luchr/c274359788bf93fed22d805b7b548692#file-gtk3vim_redrawissue-mp4>
>
> And here is my proposed patch:
>
> --- gui_gtk_x11_orig.c  2017-02-19 20:31:52.196659889 +0100+++ gui_gtk_x11.c       2017-02-19 20:32:29.439659889 +0100@@ -687,12 +687,17 @@
>             for (i = 0; i < list->num_rectangles; i++)
>             {
>                 const cairo_rectangle_t rect = list->rectangles[i];
>
>                 gui_mch_clear_block(Y_2_ROW(rect.y), 1,
>                         Y_2_ROW(rect.y + rect.height - 1), Columns);+           }++           for (i = 0; i < list->num_rectangles; i++)+           {+               const cairo_rectangle_t rect = list->rectangles[i];
>
>                 if (blink_mode)
>                     gui_gtk3_redraw(rect.x, rect.y, rect.width, rect.height);
>                 else
>                 {
>                     if (get_real_state() & VISUAL)
>
> And here are my thoughts for the "why": If num_rectangles>1 one has to
> clear *all* the rectangles first and then start to (re-)draw them.
> Otherwise (it seems) part of the already drawn rectangles are cleared if
> they overlap.
>
How can that be possible?  The current code is written in such a way that
necessary redraw always, immediately follows for each rectangle region once
the same region has been cleared.  Since a set of rectangle regions to be
redrawn is given by the toolkit as part of an argument of the 'draw' signal
handler, and Vim doesn't do any operations such as taking intersection or
union of them, that "Otherwise (it seems) part of the already drawn
rectangles are cleared if they overlap" is unlikely to happen.

**Comment by luchr** [comment]
Let's see if I can answer the question with a concrete example (real numbers, logged from the code):

> The current code is written in such a way that necessary redraw always, immediately follows for each rectangle region once the same region has been cleared.

The *same* region? I'll don't sign this, because the set of rectangles (from the draw signal) are heavily changed to get the clearing region, because they are transformed to Vim rows and columns and *back*.

Here a concrete example, where I believe one can see, what is happening in complete detail:

```
19:07:31: draw_event: i=0, Rect: x=453, y=127, w=357, h=  6; (453,127)--(810,133)
19:07:31:   gui_mch_clear_block: Rows: 8--8, Cols: 1--109
19:07:31:     clearing Rect: x=10, y=122, w=872, h=15; (10,122)--(882,137)
19:07:31:   gui_gtk3_redraw for x=453, y=127, width=357, height=6
19:07:31:   redrawing block: rows 8--8, cols=56--100

19:07:31: draw_event: i=1, Rect: x=453, y=133, w=  9, h=231; (453,133)--(462,364)
19:07:31:   gui_mch_clear_block: Rows: 8--24, Cols: 1--109
19:07:31:     clearing Rect: x=10, y=122, w=872, h=255; (10,122)--(882,377)
19:07:31:   gui_gtk3_redraw for x=453, y=133, width=9, height=231
19:07:31:   redrawing block: rows 8--24, cols=56--57
```
Cols 56-100 are redrawn at `i=0` and cleared at `i=1`, but only columns 56-57 are redrawn.

Looking at the code my claim is: The columns for the clearing region `1--Columns` are completely decoupled from the columns that are redrawn.

Does this help? Is this a convincing argument?

**Comment by vim-ml** [comment]
2017-02-21 3:24 GMT+09:00 luchr <vim-dev-github@256bit.org>:

> Let's see if I can answer the question with a concrete example (real
> numbers, logged from the code):
>
> The current code is written in such a way that necessary redraw always,
> immediately follows for each rectangle region once the same region has been
> cleared.
>
> The *same* region? I'll don't sign this, because the set of rectangles
> (from the draw signal) are heavily changed to get the clearing region,
> because they are transformed to Vim rows and columns and *back*.
>
> Here a concrete example, where I believe one can see, what is happening in
> complete detail:
>
> 19:07:31: draw_event: i=0, Rect: x=453, y=127, w=357, h=  6; (453,127)--(810,133)
> 19:07:31:   gui_mch_clear_block: Rows: 8--8, Cols: 1--109
> 19:07:31:     clearing Rect: x=10, y=122, w=872, h=15; (10,122)--(882,137)
> 19:07:31:   gui_gtk3_redraw for x=453, y=127, width=357, height=6
> 19:07:31:   redrawing block: rows 8--8, cols=56--100
>
> 19:07:31: draw_event: i=1, Rect: x=453, y=133, w=  9, h=231; (453,133)--(462,364)
> 19:07:31:   gui_mch_clear_block: Rows: 8--24, Cols: 1--109
> 19:07:31:     clearing Rect: x=10, y=122, w=872, h=255; (10,122)--(882,377)
> 19:07:31:   gui_gtk3_redraw for x=453, y=133, width=9, height=231
> 19:07:31:   redrawing block: rows 8--24, cols=56--57
>
> Cols 56-100 are redrawn at i=0 and cleared at i=1, but only columns 56-57
> are redrawn.
>
> Looking at the code my claim is: The columns for the clearing region
> 1--Columns are completely decoupled from the columns that are redrawn.
>
> Does this help? Is this a convincing argument?
>
No, and you're raising another issue we need to resolve apart from the
current issue.  Also, the example above even proves that your patch is
incorrect since it relies on the same clear-block computation as the
current code does, which makes it impossible to explain why the proposed
patch resolves the issue in conjunction with your clear-redraw mismatch
hypothesis.

You took the word "the same" too strictly for us to continue the discussion
productively.  You should have already known that the calculation involves
char_width, char_height, char_ascent,  border_offset of struct Gui and a
single pixel compensation to remove possible artifacts caused by double
stroke bold as well as x, y, width and height.  Because of some correction
or adjustment using those variables, literal comparison of pixel numbers
does not make much sense, without revealing the rest of all the figures
involved.

The problem here is that you didn't mention the context nor provide a way
to reproduce those numbers in the example.

To get this nearly derailed discussion on the right track, I wrote a
patch.  It tries to fix clear-redraw mismatch and give a neater printf()
debug helper.

If you will, apply the patch to the latest source, 8.0.344, run `configure`
with suitable options as usual, then do `make CFLAGS=-DGTK3_DEBUG` to get
an executable having the helper.  If you find that those printf()s are
placed in wrong places, fix them so that the resulting executable will give
output similar to your example (If this is the case, send the modified
patch back to us).

Run the executable and see if the clear-redraw mismatch is resolved enough
to verify your hypothesis and patch, though I don't expect that the patch
fixes the original issue.

**Comment by zdohnal** [comment]
Hi,
I think I experienced similar issue as luchr - when I installed clear new Fedora 25 with Openbox desktop environment and when I switched desktops, that part of gvim, where 'openbox desktop switch dialog' was, wasn't rendered completely. Patch proposed by luchr worked for me, Kazunobu Kuriyama's doesn't.

**Comment by luchr** [comment]
I also use Fedora 25 (Fedora 24 before) with Openbox.

I've applied the patch of Kazunobu Kuriyama to deliver the requested informations:

Here is the output of printf-commands:
https://gist.github.com/luchr/6f6f7421856baa01f5d1a02cbb6c928e#file-vim-log

the Movie:
https://gist.github.com/luchr/6f6f7421856baa01f5d1a02cbb6c928e#file-movie-mp4
showing output and vim-Window in sync

Here an Image
https://gist.github.com/luchr/6f6f7421856baa01f5d1a02cbb6c928e#file-first_events-png
with the 5 first draw events where the problem occurs (careful; this is my interpretation), line 211 to 222 in the log output and and resized (increased) portion of vim showing the graphics.

Sorry, I don't know a way for me to move the mouse with pixel-precision in order to deterministically "reproduce those numbers in the example" (as requested).

**Comment by nuko8** [comment]
2017-02-22 9:02 GMT+09:00 luchr <notifications@github.com>:

> I also use Fedora 25 (Fedora 24 before) with Openbox.
>
> I've applied the patch of Kazunobu Kuriyama to deliver the requested
> informations:
>
> Here is the output of printf-commands:
> https://gist.github.com/luchr/6f6f7421856baa01f5d1a02cbb6c92
> 8e#file-vim-log
>
> the Movie:
> https://gist.github.com/luchr/6f6f7421856baa01f5d1a02cbb6c92
> 8e#file-movie-mp4
> showing output and vim-Window in sync
>
> Here an Image
> https://gist.github.com/luchr/6f6f7421856baa01f5d1a02cbb6c92
> 8e#file-first_events-png
> with the 5 first draw events where the problem occurs (careful; this is my
> interpretation), line 211 to 222 in the log output and and resized
> (increased) portion of vim showing the graphics.
>

OK, then could you try to apply your patch on top of mine and see if yours
still fixes the original issue on your desktop?

If it works, it means that mine is working to support the premise of your
hypothesis, thus verifying the correctness of yours.

Sorry, I don't know a way for me to move the mouse with pixel-precision in
> order to deterministically "reproduce those numbers in the example" (as
> requested).
>

If it is that hard, no problem at all.

**Comment by luchr** [comment]
Here are the results:

1. case: applying my patch on top of it: problem still exists
2. case: applying my patch on top of it and undoing one line of your patch to have
```
    gui_redraw_block(Y_2_ROW(y), X_2_COL(x),
            /* Y_2_ROW(y + height) - 1, X_2_COL(x + width) - 1, */
            Y_2_ROW(y + height - 1), X_2_COL(x + width - 1),
            GUI_MON_NOCLEAR);
```
then I don't see the problem.

**Comment by nuko8** [comment]
2017-02-22 9:28 GMT+09:00 luchr <notifications@github.com>:

> Here are the results:
>
>    1. case: applying my patch on top of it: problem still exists
>    2. case: applying my patch on top of it and undoing one line of your
>    patch to have
>
>     gui_redraw_block(Y_2_ROW(y), X_2_COL(x),
>             /* Y_2_ROW(y + height) - 1, X_2_COL(x + width) - 1, */
>             Y_2_ROW(y + height - 1), X_2_COL(x + width - 1),
>             GUI_MON_NOCLEAR);
>
> then I don't see the problem.
>
Oops, seems you're right.

Then, could you update your patch, merging the corrected version of mine
(i.e. with the fix above applied and the fprintf()s removed) into yours,
and send it to vim_dev?

**Comment by vim-ml** [comment]
2017-02-22 9:43 GMT+09:00 Kazunobu Kuriyama <vim-dev-github@256bit.org>:

> 2017-02-22 9:28 GMT+09:00 luchr <notifications@github.com>:
>
> > Here are the results:
> >
> > 1. case: applying my patch on top of it: problem still exists
> > 2. case: applying my patch on top of it and undoing one line of your
> > patch to have
> >
> > gui_redraw_block(Y_2_ROW(y), X_2_COL(x),
> > /* Y_2_ROW(y + height) - 1, X_2_COL(x + width) - 1, */
> > Y_2_ROW(y + height - 1), X_2_COL(x + width - 1),
> > GUI_MON_NOCLEAR);
> >
> > then I don't see the problem.
> >
> Oops, seems you're right.
>
> Then, could you update your patch, merging the corrected version of mine
> (i.e. with the fix above applied and the fprintf()s removed) into yours,
> and send it to vim_dev?
>

Ah, I forgot to add this, "If you agree,"  Sorry about asking you that way.

**Comment by luchr** [comment]
Sorry, sorry, I've lost context. I definitely thought my idea was wrong, because you wrote

> If it works, it means that mine is working to support the premise of your hypothesis, thus verifying the correctness of yours. 

Applying my patch on top did *not* work, so I thought the correctness of mine is *not* verified. [Too many if-then-elses for my bad English]. I had to undo one of your changes in your patch in order to go back to the original version in order to *not* see the problem.

I'll try to learn here, in order to write better bug reports for the future (this one was obviously not so nice/effective). I lost track now. Can you tell me, what you've tested with the line?
```
Y_2_ROW(y + height) - 1, X_2_COL(x + width) - 1,
```
That is the one I had to *revert* (=to undo, =to restore the old one) in order to make it work for me?

For the patch: Yes, I'll send it to vim_dev after some hours of sleep and after some hours of work and after I have understood (a small piece) what happend. Sorry.

**Comment by vim-ml** [comment]
2017-02-22 10:06 GMT+09:00 luchr <vim-dev-github@256bit.org>:

> Sorry, sorry, I've lost context. I definitely thought my idea was wrong,
> because you wrote
>
> If it works, it means that mine is working to support the premise of your
> hypothesis, thus verifying the correctness of yours.
>
> Applying my patch on top did *not* work, so I thought the correctness of
> mine is *not* verified. [Too many if-then-elses for my bad English]. I
> had to undo one of your changes in your patch in order to go back to the
> original version in order to *not* see the problem.
>
Ah, that simply means my patch still had a bug.  You found it in an attempt
to make your patch work again.  Having read your previous email, I noticed
the bug and approved the change you made for reviving yours as a bug fix to
mine.  But that approval was seemingly too vague or implicit for you to get
me.

In the end, each of us were working for fixing the bug of the other's patch
simultaneously.  As we happened to try to resolve two different, but
intrinsically related issues in a single thread, it was quite natural that
the context was easily lost or broken.  But somehow it looks we are going
to overcome the difficulty.

Now, let me repeat "sorry" as many times as you did.

> I'll try to learn here, in order to write better bug reports for the
> future (this one was obviously not so nice/effective). I lost track now.
> Can you tell me, what you've tested with the line?
>
> Y_2_ROW(y + height) - 1, X_2_COL(x + width) - 1,
>
> That is the one I had to *revert* (=to undo, =to restore the old one) in
> order to make it work for me?
>
Now you know that's my fault :)

> For the patch: Yes, I'll send it to vim_dev after some hours of sleep and
> after some hours of work and after I have understood (a small piece) what
> happend. Sorry.
>
No problem at all.  If you find there's still anything dubious, feel free
to ask me.

**Comment by zdohnal** [comment]
I tried the updated patch (luchr's + Kazunobi's without one line mentioned by luchr) and confirmed it works.

**Comment by nuko8** [comment]
@zdohnal  Glad to hear that.   That encourages us.

@luchr  Could you do the following three different tests against your updated patch to see if it causes regression or not?

1. With the operations below, does the cursor appear on the screen while the job is running?  Is it blinking almost normally?
```
$ gvim -u NONE -U NONE -N
:new
:call job_start(['/bin/sh', '-c', 'ls -R / | head -500000'], { 'out_io': 'buffer', 'out_buf': 1 })
```
2.  Source the following script:
```viml
set laststatus=2
let tcount = 0

func! Timer_cb(timer)
    let g:tcount += 1
    call setbufvar(1, '&stl', g:tcount)
endfunc

call timer_start(50, 'Timer_cb', {'repeat': 100})
```
Does the cursor appear on the screen while the timer is being activated?  Is it blinking almost normally?

3. In a directory, put the following two scripts, and name them `job.vim` and `job.sh`, respectively:
```viml
func! Close_cb(channel)
    echo 'Done!'
endfunc

map <F4> :call job_stop(job)<CR>

let job = job_start(['/bin/sh', '-c', '$PWD/job.sh'], {'out_io': 'buffer', 'out_buf': 1, 'close_cb': 'Close_cb'})
```
```sh
#!/bin/bash

for i in `seq 1 3000`;
do
        echo "$i dflsk ksdjf shdaf sdasdlkfh"
        sleep 80 ms
        echo "kldj fdljkshf kjsdh sdlkfj $i"
        sleep 270 ms
done
```
Source `job.vim`, then check if the cursor appears and is blinking almost normally.

These three tests were the very reason why the patches 1890 and 1899 were written.

UPDATE: Remove <<<<'s from test examples.

**Comment by zdohnal** [comment]
@luchr, @nuko8 Gentlemen, I think it is not issue of patches 1890 or 1899. I found out (when I was trying to reproduce issue) the problem was introduced at the time when vim started to use gtk3 for rendering (at least on fedora, vim-8.0 with patchlevel 22 worked fine until gtk3 was used). Probably there was some change in gtk3's behavior and yours patch solved it.

**Comment by luchr** [comment]
OK. I've tested the following patch(-set)

```diff
diff --git a/src/gui_gtk_x11.c b/src/gui_gtk_x11.c
index eef0bd4..4553d83 100644
--- a/src/gui_gtk_x11.c
+++ b/src/gui_gtk_x11.c
@@ -630,6 +630,7 @@ static void gui_gtk_window_clear(GdkWindow *win);
     static void
 gui_gtk3_redraw(int x, int y, int width, int height)
 {
+    /* Range checks are left to gui_redraw_block() */
     gui_redraw_block(Y_2_ROW(y), X_2_COL(x),
 	    Y_2_ROW(y + height - 1), X_2_COL(x + width - 1),
 	    GUI_MON_NOCLEAR);
@@ -688,9 +689,13 @@ draw_event(GtkWidget *widget UNUSED,
 	    {
 		const cairo_rectangle_t rect = list->rectangles[i];
 
-		gui_mch_clear_block(Y_2_ROW(rect.y), 1,
-			Y_2_ROW(rect.y + rect.height - 1), Columns);
+		gui_mch_clear_block(Y_2_ROW((int)rect.y), 0,
+			Y_2_ROW((int)(rect.y + rect.height)) - 1, Columns - 1);
+	    }
 
+	    for (i = 0; i < list->num_rectangles; i++)
+	    {
+		const cairo_rectangle_t rect = list->rectangles[i];
 		if (blink_mode)
 		    gui_gtk3_redraw(rect.x, rect.y, rect.width, rect.height);
 		else
@@ -6723,6 +6728,11 @@ gui_mch_clear_block(int row1, int col1, int row2, int col2)
     color.pixel = gui.back_pixel;
 #endif
 
+    col1 = check_col(col1);
+    col2 = check_col(col2);
+    row1 = check_row(row1);
+    row2 = check_row(row2);
+
 #if GTK_CHECK_VERSION(3,0,0)
     {
 	/* Add one pixel to the far right column in case a double-stroked
```

@nuko8  I hope this is the right set of patched lines. 

I removed the `<<<<` characters in the test files given.

Test 1: Cursor is blinking *almost* normally.
Test 2: Cursor is blinking normally.
Test 3: [I changed `sleep 80 ms` to `sleep 0.080` and the other sleep too, because my bash cannot handle the unit "ms"]: Cursor is blinking normally.

**Comment by nuko8** [comment]
@luchr 

> Test 1: Cursor is blinking almost normally.
> Test 2: Cursor is blinking normally.
> Test 3: [I changed sleep 80 ms to sleep 0.080 and the other sleep too, because my bash cannot handle the unit "ms"]: Cursor is blinking normally.

Thanks!  I also tested them on my machine and had a similar result.  Seems the updated patch introduces no regression with respect to cursor blink while job or timer feature is being used.

> I removed the <<<< characters in the test files given.

Very sorry about the inconvenience.  The characters are my `'showbreak'` and now you see how I made such a mess :)
