### ISSUE TITLE
screenpos() doesn't respect conceallevel option

### ISSUE THREAD

**Issue by monkoose** [vim/vim#8483]
**Describe the bug**
`screenpos()` function return wrong screen column if there are hidden with conceal characters on a line.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean` (or `gvim --clean`, etc.)
2. `:h getpos()`
3. `/getting`
4. `set conceallevel=2` (should be default i guess)
5. `echo screenpos(0, line('.'), col('.')`
6. `set conceallevel=0`
7. `echo screenpos(0, line('.'), col('.')`

Will return the same result in both cases, but cursor column position on the screen is different. 

**Expected behavior**
`screenpos()` should return correct column when there are hidden conceal characters.

Related #8476

**Comment by brammool** [comment]
I'm afraid this can't be made to work in general.  I'll add a note in the help of screenpos().

**Comment by monkoose** [comment]
@brammool, for my needs i found a workaround with `wincol()` and temporal set of cocneallevel to 0, calculate the difference. And then just subtract that number from result of `screenpos().col`.
