### ISSUE TITLE
Vim9: no check for missing catch in try block at script level

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8487]
**Describe the bug**

In Vim9 script, there is no check for a missing `:catch` in a `:try` block at the script level.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        try
            eval 0
        endtry
    EOF
    )

No error is given.

**Expected behavior**

An error is given, because the `:try` block doesn't contain any `:catch`/`:finally` clause.

**Environment**

 - Vim version: 8.2 Included patches: 1-3081
 - OS: Ubuntu 20.04.2 LTS
 - Terminal: XTerm(353)

**Additional context**

In compiled code, an error is given:
```vim
vim9script
def Func()
    try
        eval 0
    endtry
enddef
defcompile
```
    E1032: Missing :catch or :finally

Which seems inconsistent.

**Comment by lacygoill** [comment]
Something else looks weird.  Consider this code:
```vim
vim9script
function Throw()
    try
        eval [][0]
    catch
        throw 'error'
    endtry
endfunction
silent! Throw()
try
    Unknown()
catch
endtry
```
    E117: Unknown function: Unknown

The error should have been caught.  This is a known legacy bug, for which there is a todo item:

   > Problem that a previous silent ":throw" causes a following try/catch not to
   > work. (ZyX, 2013 Sep 28) With examples: (Malcolm Rowe, 2015 Dec 24)

<https://github.com/vim/vim/blob/11a632d60bde616feb298d180108819ebb1d04a0/runtime/doc/todo.txt#L1423-L1424>

Now, here is the same code, but this time `Throw()` is refactored into a Vim9 function:
```vim
vim9script
def Throw()
    try
        eval [][0]
    catch
        throw 'error'
    endtry
enddef
silent! Throw()
try
    Unknown()
catch
endtry
```
    no error

This time, the error is correctly caught.

Was the legacy bug fixed in Vim9?  Or is it hidden by another Vim9 bug?

**Comment by brammool** [comment]
About the existing problem: using a :def function the commands are handled in a separate execution context.  Thus the side effect of the silent throw happens elsewhere.
