### ISSUE TITLE
Vim9: no documentation for triple dot notation when funcrefs in list have different number of arguments

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8489]
If we store multiple funcrefs in a composite data type, like a list or a dictionary, the type of the latter will contain a triple dot, which is not documented:
```vim
vim9script
def Foo(x: bool)
enddef
def Bar(x: bool, y: bool)
enddef
var l = [Foo, Bar]
echo l->typename()
```
    list<func(...)>
              ^^^

Notice the triple dot.  It means that the 2 function signatures don't have the same number of arguments.  I can't find this explained in the help.  The only occurrences of "..." are:

   - english ellipses used to omit some code which the reader can complete
   - used for variable arguments (i.e. arguments which can be omitted when calling a function, and whose number can vary)
   - used for repetition

The closest occurrence is this one:

   > func(...{type})                 function with type of variable number of
   >                                 arguments, does not return a value

It refers to this kind of output:
```vim
vim9script
def Func(...variable: list<any>)
enddef
echo typename(Func)
```
    func(...list<any>)
         ^^^

While it looks similar, that's not the same "...".

Anyway, none of these match the triple dot mentioned at the top of this post.  Maybe it should be documented.  Otherwise, the user might wonder what it means when a type mismatch error is given:
```vim
vim9script
def Foo(a: bool)
enddef
def Bar(b: number, c: float)
enddef
var l: list<func>
l = 0
```
    E1012: Type mismatch; expected list<func(...): unknown> but got number
                                             ^^^

As a suggestion here is a patch:
```diff
diff --git a/runtime/doc/vim9.txt b/runtime/doc/vim9.txt
index e8d97a9c3..21dd59244 100644
--- a/runtime/doc/vim9.txt
+++ b/runtime/doc/vim9.txt
@@ -1114,6 +1114,16 @@ func({type}, ?{type}, ...{type}): {type}
 
 If the return type is "void" the function does not return a value.
 
+If several funcrefs are saved in a list or dictionary, and the number of their
+arguments don't match, their types will be reported as "...": >
+	def Foo(a: bool)
+	enddef
+	def Bar(b: number, c: float)
+	enddef
+	var l = [Foo, Bar]
+	echo typename(l)
+<	list<func(...)>
+
 The reference can also be a |Partial|, in which case it stores extra arguments
 and/or a dictionary, which are not visible to the caller.  Since they are
 called in the same way the declaration is the same.
```

**Comment by brammool** [comment]
I'll add something like that to the help.
