### ISSUE TITLE
Vim9: meaning of "any" type is ambiguous for list/dict of funcrefs

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8490]
Consider this code:
```vim
vim9script
def ReturnNumber(): number
    return 0
enddef
def ReturnString(): string
    return ''
enddef
var l = [ReturnNumber, ReturnString]
echo l->typename()
```
    list<func(): any>

`any` is ambiguous here.  It can be read as:

   > All functions in the list return a value of type "any".

Or it can be read as:

   > Not all functions return the same type of value.

In practice, it's the second interpretation which is correct.  Maybe this should be documented.

---

Same ambiguity when `any` is used for a funcref argument:
```vim
vim9script
def ExpectNumber(x: number)
enddef
def ExpectString(x: string)
enddef
var l = [ExpectNumber, ExpectString]
echo l->typename()
```
    list<func(any)>

Again, this `any` is ambiguous; it can be read as:

   > All functions in the list expect a value of type "any".

Or it can be read as:

   > Not all functions expect the same type of value.

And again, in practice, it's the second interpretation which is correct.  Maybe this should be documented.

---

Note that a paragraph in the current documentation could be misunderstood:

   > These types can be used in declarations, but no value will have this type:
   >         {type}|{type}  {not implemented yet}
   >         void
   >         any

https://github.com/vim/vim/blob/11a632d60bde616feb298d180108819ebb1d04a0/runtime/doc/vim9.txt#L1087-L1090

One could infer that `any` will never appear in the type of a value (as reported in an error message or by `typename()`).  Which is not entirely true; as seen in the previous snippets, it can appear in the type of a list/dict of funcrefs.

---

As a suggestion, here is a patch:
```diff
diff --git a/runtime/doc/vim9.txt b/runtime/doc/vim9.txt
index e8d97a9c3..b502bf8d3 100644
--- a/runtime/doc/vim9.txt
+++ b/runtime/doc/vim9.txt
@@ -1114,6 +1114,17 @@ func({type}, ?{type}, ...{type}): {type}
 
 If the return type is "void" the function does not return a value.
 
+If several funcrefs are saved in a list or dictionary, and the type of their
+argument doesn't match in a given position, its type will be reported as "any": >
+	def Foo(a: bool)
+	enddef
+	def Bar(b: number)
+	enddef
+	var l = [Foo, Bar]
+	echo typename(l)
+<	list<func(any)>
+Same thing for their return type, if they don't match.
+
 The reference can also be a |Partial|, in which case it stores extra arguments
 and/or a dictionary, which are not visible to the caller.  Since they are
 called in the same way the declaration is the same.
```

**Comment by brammool** [comment]
There already is a remark that when a list has a mix of types it becomes a list of "any".
I'll change that remark about "no value will have this type.   {type}|{type} is not implemented and likely won't be.
A simple value won't have the type "any", but that is difficult to explain.  Better to just leave it out.
There can be no variable using "void", so that can remain.
