### ISSUE TITLE
Vim9: type checking uses inferred "any" type inconsistently for list/dict of funcrefs

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8491]
**Describe the bug**

In Vim9 script, type checking uses an inferred `any` type inconsistently for a list/dict of funcrefs.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def ExpectNumber(x: number)
        enddef
        def ExpectString(x: string)
        enddef
        var l: list<func(bool)> = [ExpectNumber, ExpectString]
    EOF
    )

No error is given for the assignment; even though none of the function signatures match the `func(bool)` type specified in the declaration of the `l` variable.

Now, run this other shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def ReturnNumber(): number
            return 123
        enddef
        def ReturnString(): string
            return 'string'
        enddef
        var l: list<func(): bool> = [ReturnNumber, ReturnString]
    EOF
    )

This time, a type mismatch error is given:

    E1012: Type mismatch; expected list<func(): bool> but got list<func(): any>

**Expected behavior**

Not sure, but to be consistent, it seems that either the first command should give an error, like the second one; or the second command should not give any error, like the first one.

IMO, the most useful choice would be for the second command to give an error like the first one.

**Environment**

 - Vim version: 8.2 Included patches: 1-3081
 - OS: Ubuntu 20.04.2 LTS
 - Terminal: XTerm(353)

**Additional context**

I think the reason why Vim doesn't give an error in the first command is because of the `any` type which was inferred for the functions argument:
```vim
vim9script
def ExpectNumber(x: number)
enddef
def ExpectString(x: string)
enddef
echo [ExpectNumber, ExpectString]->typename()
```
    list<func(any)>
              ^^^

During type checking, it seems that this inferred `any` matches any type; including the `bool` that we wrote in the list variable declaration:

    var l: list<func(bool)> = [ExpectNumber, ExpectString]
                     ^--^

But that's not how type checking uses an `any` inferred for a funcref return type.  If it was, there would be no error in the second command:

    E1012: Type mismatch; expected list<func(): bool> but got list<func(): any>
                                                                           ^^^

Notice the `any` at the end of the message.  It means that Vim is much stricter when checking the return type; it doesn't accept any return type; it really wants all funcrefs to have the return type `any`.

IOW, the only way to fix this error is to write `any` for the return type:

                         ✘
                        v--v
    var l: list<func(): bool> = [ReturnNumber, ReturnString]

    →

    var l: list<func(): any> = [ReturnNumber, ReturnString]
                        ^^^
                         ✔

The fact that an inferred `any` is used differently for a function argument compared to a function return value seems inconsistent.  Is this working as intended?  If so, maybe it should be documented.

---

IMO, the behavior in the second command is good, because it gives us the most guarantees about the validity of our code.  For example, if we write this:

    var l: list<func(): number> = [A, B, C]

And Vim doesn't complain, then we have the guarantee that all 3 functions `A`, `B`, `C` do return numbers.
The only exception to this guarantee is the `any` return type:

    var l: list<func(): any> = [A, B, C]

This time, if Vim doesn't complain, it doesn't mean that each of the 3 functions can return any type of values.  It means that – *as a whole* – the set of the 3 return types could contain any type.  IOW, it doesn't mean anything useful.  It's a bit like saying "I have no idea what any of these functions return".

OTOH, maybe the behavior in the first command should be changed because:

   - it would be more consistent with the second one
   - it would give us more guarantees about the validity of the argument types that we write

So maybe this command:
```vim
vim9script
def ExpectNumber(x: number)
enddef
def ExpectString(x: string)
enddef
var l: list<func(bool)> = [ExpectNumber, ExpectString]
```
Should give an error, such as:

    E1012: Type mismatch; expected list<func(bool)> but got list<func(any)>

And to fix this, we should have to rewrite our declaration like this:

                      ✘
                     v--v
    var l: list<func(bool)> = [ExpectNumber, ExpectString]

    →

    var l: list<func(any)> = [ExpectNumber, ExpectString]
                     ^^^
                      ✔

**Comment by lacygoill** [comment]
> it really wants all funcrefs to have the return type any.

No, sorry, that's not what I meant.  Vim just wants `any` in the declaration.  But that doesn't change the rest of the post.

**Comment by brammool** [comment]
The reason that "any" is accepted for the argument type is that lambda's may use "any" and in that case we can't give an error.
The argument type will be checked at runtime.
We could perhaps add a flag in the type that the function type comes from a lambda, but that gets complicated.
It would be nice to get an error more early, but other than that it's not really wrong.
