### ISSUE TITLE
Vim9: no error when assigning list of funcrefs with variable number of arguments to variable declared with fixed number of arguments

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8492]
**Describe the bug**

In Vim9 script, no error is given when we assign a list/dict of funcrefs with different number of arguments, to a variable declared with a fixed number of arguments.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def OneArg(x: bool)
        enddef
        def TwoArgs(x: bool, y: bool)
        enddef
        var l: list<func(bool, bool, bool)> = [OneArg, TwoArgs]
    EOF
    )

No error is given.

**Expected behavior**

A type mismatch error is given; such as this one:

    E1012: Type mismatch; expected list<func(bool, bool, bool)> but got list<func(...)>

And to fix this error, we should be required to write `func` (without parens):

    var l: list<func> = [OneArg, TwoArgs]
                ^--^

Because there is currently no specification which can match funcrefs with different numbers of arguments.
IOW, the only acceptable solution is to not specify anything with regards to the funcref arguments.  Besides, in its current form, the previous code is misleading:

    var l: list<func(bool, bool, bool)> = [OneArg, TwoArgs]
                ^-------------------^

When we read it, we might wrongly think that all the funcrefs respect the specification.  We currently have no such guarantee, because Vim doesn't give any error when the funcrefs have different numbers of arguments.

**Environment**

 - Vim version: 8.2 Included patches: 1-3081
 - OS: Ubuntu 20.04.2 LTS
 - Terminal: XTerm(353)

**Additional context**

In the future, if this syntax gets implemented:

   > These types can be used in declarations, but no value will have this type:
   >         {type}|{type}  {not implemented yet}

Then, we could also write:

    var l: list<func(bool)|func(bool, bool)> = [OneArg, TwoArgs]

Although, it could quickly get too cumbersome to read/write.

---

Note that currently, during a simple funcref assignment, Vim does check that the number of arguments matches:
```vim
vim9script
def Func(b: bool, _)
enddef
var Ref: func(bool) = Func
```
    E1012: Type mismatch; expected func(bool) but got func(bool, unknown)
```vim
vim9script
var Ref: func(bool): number = (_, _) => 0
```
    E1012: Type mismatch; expected func(bool): number but got func(any, any): number

In both cases, Vim complains because the funcref expects 2 arguments, while we declared only one (in the variable type).

IMO, this is good, but it's also inconsistent with what happens in a list/dict of funcrefs assignment.

**Comment by lacygoill** [comment]
> When we read it, we might wrongly think that all the funcrefs respect the specification. We currently have no such guarantee, because Vim doesn't give any error when the funcrefs have different numbers of arguments.

And by "Vim doesn't give any error", I mean not even the types are checked:
```vim
vim9script
def OneArg(x: bool)
enddef
def TwoArgs(x: bool, y: bool)
enddef
var l: list<func(job, job, job)> = [OneArg, TwoArgs]
```
    no error

I guess it makes sense.  Since there is no third argument in the functions, the third `job` can't be checked; so Vim drops type checking for the previous 2 `job`.  But Vim should still warn us about the number of arguments which don't match.

**Comment by lacygoill** [comment]
> Because there is currently no specification which can match funcrefs with different numbers of arguments.

We could also introduce the `(...)` specification.  It would be consistent with what Vim already writes in an error message, and with the output of `typename()`.

So, we could write this:

    var l: list<func(...)> = [OneArg, TwoArgs]
                    ^---^

Right now, this specification gives an error:

    E1010: Type not recognized: )>

The benefit over a simple `func` is that it gives more meaning to the code:

    # this is a list of funcrefs; I have no idea what kind
    var l: list<func>

    # this is a list of funcrefs; I know that they expect arguments, but their number don't match
    var l: list<func(...)>

**Comment by brammool** [comment]
>    > Because there is currently no specification which can match funcrefs with different numbers of arguments.
> 
> We could also introduce the `(...)` specification.  It would be
> consistent with what Vim already writes in an error message, and with
> the output of `typename()`.
> 
> So, we could write this:
> 
>     var l: list<func(...)> = [OneArg, TwoArgs]
>                     ^---^
> 
> Right now, this specification gives an error:
> 
>     E1010: Type not recognized: )>
> 
> The benefit over a simple `func` is that it gives more meaning to the code:
> 
>     # this is a list of funcrefs; I have no idea what kind
>     var l: list<func>
> 
>     # this is a list of funcrefs; I know that they expect arguments, but their number don't match
>     var l: list<func(...)>

Just leaving out the (...) will have that effect.  It looks a bit
strange, since with the () missing it does not look like a function
call.

We could add "(...)" to mean "any number of arguments", but then we
should probably require it.  That makes it asymmetric to "unknown return
type" though.

	func		any arguments, unknown return type
	func: void	any arguments, no return
	func: type	any arguments, with return type
	func()		no arguments, no return
	func(): void	no arguments, no return
	func(): type	no arguments, with return type

So what's not possible is to specify arguments but unknown return type
(including none).  Perhaps this could work:
	func(): ...	no arguments, unknown return type

But it doesn't make much sense to specify arguments and not have an
unknown return type.

-- 
From "know your smileys":
 !-|	I-am-a-Cylon-Centurian-with-one-red-eye-bouncing-back-and-forth

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
I think the patch 8.2.3100 has broken something; or it has revealed an inconsistency:
```vim
vim9script
def Foo(b: bool)
enddef
var Partial: func(bool) = function(Foo, [true])
```
    no error
```vim
vim9script
def Foo(b: bool)
enddef
def Func()
    var Partial: func(bool) = function(Foo, [true])
enddef
Func()
```
    E1012: Type mismatch; expected func(bool) but got func(...): unknown

I would expect both snippets to give the same result; either they both work, or they both fail.

---

Before the patch, the second snippet worked.  Reading the help, it *seems* as if it's working as intended:

> When using `function()` the resulting type is "func", a function with any
> number of arguments and any return type.

However, it seems to contradict this simple test:
```vim
vim9script
def Foo(b: bool): number
    return 0
enddef
echo Foo->function()->typename()
```
    func(bool): number
```vim
vim9script
def Foo(b: bool): number
    return 0
enddef
def Func()
    var Ref = function(Foo)
    echo typename(Ref)
enddef
Func()
```
    func(bool): number

The result is not a function with any number of arguments and any return type.  It's a function expecting exactly 1 argument, and a `number` return type.

And I don't understand why Vim should forget everything it knows about a function as soon as we use `function()`.  If Vim knows the signature of `Foo`, then I would expect the latter to be used when type inferrence kicks in, whether we use `function()` or not.  Although, maybe the quotes should be dropped around the function name as a requirement; not sure.

**Comment by brammool** [comment]
> I think the patch 8.2.3100 has broken something; or it has revealed an inconsistency:
> ```vim
> vim9script
> def Foo(b: bool)
> enddef
> var Partial: func(bool) = function(Foo, [true])
> ```
>     no error
> ```vim
> vim9script
> def Foo(b: bool)
> enddef
> def Func()
>     var Partial: func(bool) = function(Foo, [true])
> enddef
> Func()
> ```
>     E1012: Type mismatch; expected func(bool) but got func(...): unknown
> 
> I would expect both snippets to give the same result; either they both
> work, or they both fail.

Yeah, this happens because the type returned by function() is
incomplete, and now we check the type.

I think it's best worked around by having function() return a slightly
different type, which indicates to not check the type at all.
Not sure if this really works, let's give it a try.

There is an error though:
     var Partial: func(bool) = function(Foo, [true])
Since the argument is provided by the partial, the declaration should
be:
     var Partial: func() = function(Foo, [true])


> And I don't understand why Vim should forget everything it knows about
> a function as soon as we use `function()`.  If Vim knows the signature
> of `Foo`, then I would expect the latter to be used when type
> inferrence kicks in, whether we use `function()` or not.  Although,
> maybe the quotes should be dropped around the function name as a
> requirement; not sure.

This works at runtime, but at compile type the type returned by
function() is used, which is incomplete.  The function used can be
defined later.

-- 
From "know your smileys":
 :-)-O	Smiling doctor with stethoscope

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> There is an error though:

Ah right, but Vim doesn't complain:
```vim
vim9script
def Foo(b: bool)
enddef
var Partial: func(bool) = function(Foo, [true])
```
    no error
```vim
vim9script
def Foo(b: bool)
enddef
def Func()
    var Partial: func(bool) = function(Foo, [true])
enddef
Func()
```
    no error

---

> Since the argument is provided by the partial, the declaration should be:
>
>     var Partial: func() = function(Foo, [true])

This works in compiled code:
```vim
vim9script
def Foo(b: bool)
enddef
def Func()
    var Partial: func() = function(Foo, [true])
enddef
Func()
```
    no error

But not at the script level:
```vim
vim9script
def Foo(b: bool)
enddef
var Partial: func() = function(Foo, [true])
```
    E1012: Type mismatch; expected func() but got func(bool)

**Comment by brammool** [comment]
> > There is an error though:
> 
> Ah right, but Vim doesn't complain:
> ```vim
> vim9script
> def Foo(b: bool)
> enddef
> var Partial: func(bool) = function(Foo, [true])
> ```
>     no error
> ```vim
> vim9script
> def Foo(b: bool)
> enddef
> def Func()
>     var Partial: func(bool) = function(Foo, [true])
> enddef
> Func()
> ```
>     no error

As mentioned, function() does not return the actual type.  It has to be
figured out at runtime.

> > Since the argument is provided by the partial, the declaration should be:
> >
> >     var Partial: func() = function(Foo, [true])
> 
> This works in compiled code:
> ```vim
> vim9script
> def Foo(b: bool)
> enddef
> def Func()
>     var Partial: func() = function(Foo, [true])
> enddef
> Func()
> ```
>     no error
> 
> But not at the script level:
> ```vim
> vim9script
> def Foo(b: bool)
> enddef
> var Partial: func() = function(Foo, [true])
> ```
>     E1012: Type mismatch; expected func() but got func(bool)

That is a bug.

-- 
You are only young once, but you can stay immature indefinitely.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
Not sure whether this is a bug:
```vim
vim9script
def Func(b: bool)
enddef
var Ref: func() = function(Func, [true])
echo typename(Ref)
Ref()
```
    func()
    no error
```vim
vim9script
def Func(b: bool)
enddef
var Ref: func = function(Func, [true])
echo typename(Ref)
Ref()
```
    func()
    E118: Too many arguments for function: <80><fd>R1_Func

I would expect the second snippet to not raise any error; considering that both snippets are almost identical (the only difference is `func` in the first snippet compared to `func()` in the second one), and `typename()` reports the exact same type in both.

**Comment by lacygoill** [comment]
I mean, the error message seems confusing:

    E118: Too many arguments for function: <80><fd>R1_Func

If it has to be raised, it should be by the first snippet (the one using `func()`), not the second one (which uses `func`).  Because `func()` is more specific than `func`; it asserts no arguments.  But in practice, it's the opposite.

**Comment by lacygoill** [comment]
Assigning a partial with a wrong signature correctly gives an error at the script level:
```vim
vim9script
def Func(b: bool)
enddef
var Partial: func(string)
Partial = function(Func, [true])
```
    E1012: Type mismatch; expected func(string) but got func()

But not in compiled code; not even at runtime:
```vim
vim9script
def Func(b: bool)
enddef
var Partial: func(string)
def Foo()
    Partial = function(Func, [true])
enddef
Foo()
```
    no error

**Comment by lacygoill** [comment]
Ah, I guess the error is meant to be raised only when the partial is used; not assigned.  If so, there are still what seems to be 2 issues.  First, why giving an error at the script level, on the assignment?  Why not delay the error until the partial is used (just like in compiled code)?

Second, once we try to use the wrong partial, the error message seem confusing:
```vim
vim9script
def Func(b: bool)
enddef
var Partial: func(string)
def Foo()
    Partial = function(Func, [true])
    Partial()
enddef
Foo()
```
    E119: Not enough arguments for function: Partial

First reaction: OK, not enough arguments, so let's try to pass an argument:
```vim
vim9script
def Func(b: bool)
enddef
var Partial: func(string)
def Foo()
    Partial = function(Func, [true])
    Partial('')
enddef
Foo()
```
    E118: Too many arguments for function: <80><fd>R1_Func

Now, there are too many arguments.  I don't know which error should be raised, nor at which moment.  On assignment?  When the function in which the partial is assigned is compiled?  When the partial is invoked?

**Comment by lacygoill** [comment]
> Now, there are too many arguments.

Ah, but that's not for the same function.  "Not enough" is for the partial; "too many" is for the final function.  It's still a bit confusing.

**Comment by brammool** [comment]
This is not different from the first version:
```vim
def Func()
    var Partial: func(bool) = function(Foo, [true])
    Partial()   # error for missing argument to Partial, since it was declared to take a bool argument
    Partial(true)  # error for too many arguments for Foo, since it gets two but expects one
enddef
```
Ideally there would be an error when Partial is assigned to, but as mentioned that is difficult.

**Comment by lacygoill** [comment]
> This is not different from the first version:
   > def Func()
   >     var Partial: func(bool) = function(Foo, [true])
   >     Partial()   # error for missing argument to Partial, since it was declared to take a bool argument
   >     Partial(true)  # error for too many arguments for Foo, since it gets two but expects one
   > enddef

This example only handles the case of compiled code.  I was talking about an inconsistency between compiled code and script level.

I still think there is an inconsistency, and that this snippet should not give an error:
```vim
vim9script
def Func(n: number)
enddef
var Ref: func(string) = function(Func)
```
    E1012: Type mismatch; expected func(string) but got func(number)

Because the same assignment doesn't give any error in compiled code:
```vim
vim9script
def Func(n: number)
enddef
def Foo()
    var Ref: func(string) = function(Func)
enddef
Foo()
```
    no error

These snippets gave consistent results until 8.2.3100.  The latter patch introduced a regression which was fixed in 8.2.3104.  From there, the snippets gave consistent results.  Then, another issue was reported which was fixed in the next patch 8.2.3105.  Since then, both snippets give inconsistent results.

Considering that the behavior between script level and compiled code has changed several times, I'm really not sure that the current one is correct.

Besides, I think 8.2.3105 introduced a regression, because its purpose was to fix a different issue.  It was about a wrong type for a partial with argument.  There is no partial in the 2 snippets I've just posted.  There is no reason for 8.2.3105 to have such an effect.

**Comment by lacygoill** [comment]
Also, usually, when there is an inconsistency between script level and `:def` function, it's because of an error at compile time when Vim has less information with regards to the types, than at runtime when Vim has full knowledge of all the types.

Which means that usually, when there is an inconsistency, it's the compiled code which gives an error, while there is no error at the script level.  But here, it's the opposite.  The compiled code doesn't give any error – even when the function is called – while there is an error at the script level.  That doesn't make sense.

**Comment by lacygoill** [comment]
Something else looks weird:
```vim
vim9script
def Func(n: number)
enddef
def Compiled()
    var Ref: func(string) = function(Func)
enddef
Compiled()
```
    no error

Why isn't there any error?

If we quote the function name, an error is given:
```vim
vim9script
def Func(n: number)
enddef
def Compiled()
    var Ref: func(string) = function('Func')
enddef
Compiled()
```
    E1012: Type mismatch; expected func(string) but got func(...): any

Where is it documented that quotes can have such an effect?
There are 4 occurrences for the pattern `quote` at `:help vim9`; not one of them explains this effect.

---

Also, at the script level, the quotes no longer matter.  An error is always given:
```vim
vim9script
def Func(n: number)
enddef
var Ref: func(string) = function(Func)
```
    E1012: Type mismatch; expected func(string) but got func(number)
```vim
vim9script
def Func(n: number)
enddef
var Ref: func(string) = function('Func')
```
    E1012: Type mismatch; expected func(string) but got func(number)

Why do the quotes matter in compiled code, but not at the script level?

**Comment by brammool** [comment]
The main problem appears to be that at compile time the type is checked, but this only returns OK or FAIL.  There should be a third value for when assigning "any" to a specific type, which requires a runtime type check.  This doesn't currently happen for a function reference, where the arguments and return type may need to be checked.
I'll make a patch, but it's likely not going to cover all corner cases.  if you find other things that don't work properly yet, please give examples.

**Comment by lacygoill** [comment]
I think the patch 8.2.3844 makes the snippets much more consistent.  But there is still something weird:
```vim
vim9script
def Func(b: bool)
enddef
def Compiled()
    var Ref: func(number) = function('Func')
enddef
defcompile
```
    E1012: Type mismatch; expected func(number) but got func(...): any
```vim
vim9script
def Func(b: bool)
enddef
def Compiled()
    var Ref: func(number) = function(Func)
enddef
defcompile
```
    no error

Both snippets are nearly identical.  The only difference is in the `Ref` assignment.  In the first snippet, `Func` is quoted:

    var Ref: func(number) = function('Func')
                                     ^    ^

but not in the second one:

    var Ref: func(number) = function(Func)

Why does that matter with regards to type checking at compile time?  Is it documented somewhere that omitting quotes can suppress type checking at compile time?

The closest excerpt I can think of is:

   > Omitting function() ~
   >
   > A user defined function can be used as a function reference in an expression
   > without `function()`. The argument types and return type will then be checked.
   > The function must already have been defined. >
   >
   >         var Funcref = MyFunction
   >
   > When using `function()` the resulting type is "func", a function with any
   > number of arguments and any return type (including void).  The function can be
   > defined later.

But this deals with the possible omission of `function()`.  The previous snippets are about the possible omissions of quotes.

**Comment by brammool** [comment]
> I think the patch 8.2.3844 makes the snippets much more consistent.  But there is still something weird:
> ```vim
> vim9script
> def Func(b: bool)
> enddef
> def Compiled()
>     var Ref: func(number) = function('Func')
> enddef
> defcompile
> ```
>     E1012: Type mismatch; expected func(number) but got func(...): any
> ```vim
> vim9script
> def Func(b: bool)
> enddef
> def Compiled()
>     var Ref: func(number) = function(Func)
> enddef
> defcompile
> ```
>     no error
> 
> Both snippets are nearly identical.  The only difference is in the
> `Ref` assignment.  In the first snippet, `Func` is quoted:
> 
>     var Ref: func(number) = function('Func')
>                                      ^    ^
> 
> but not in the second one:
> 
>     var Ref: func(number) = function(Func)
> 
> Why does that matter with regards to type checking at compile time?
> Is it documented somewhere that omitting quotes can suppress type
> checking at compile time?

It should not matter.  Also, using funcref() does not make this
difference, while it should be the same.

I think we should allow the assignment and use a runtime type check,
since when using function() or funcref() the returned value cannot be
set by the user, thus we have to allow the "any" type.


-- 
If your nose runs, and your feet smell, you might be upside down.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> It should not matter.

Here is another example where the quotes matter:
```vim
vim9script
def Compiled()
    var Ref = function(Func)
enddef
defcompile
def Func()
enddef
```
    E1001: Variable not found: Func
```vim
vim9script
def Compiled()
    var Ref = function('Func')
enddef
defcompile
def Func()
enddef
```
    no error

In both snippets, the same code is run.  The only difference is the `Ref` assignment:

    # snippet 1
    var Ref = function(Func)

    # snippet 2
    var Ref = function('Func')
                       ^    ^

The first snippet uses quotes, but not the second one.  If this is working as intended, maybe we should add something about this pitfall in the `Omitting function()` section.  The latter says:

   > When using `function()` the resulting type is "func", a function with any
   > number of arguments and any return type.  **The function can be defined later.**

That's true in the second snippet, but not in the first one.  So, maybe we should say that the function name must be quoted.

**Comment by brammool** [comment]
I'll add a note that when using function() quotes need to be used if the function doesn't exist yet.
