### ISSUE TITLE
Event CursorMoved does not work.

### ISSUE THREAD

**Issue by AnnoyingUserName** [vim/vim#8493]
**Describe the bug**
When enter a window with text cursor at (1, 1) from another window with text cursor at (1, 1), CursorMoved would not be triggered. It also appear when both of their cursor are at the ending of the content.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean` or `gvim --clean`.
2. Use `new` or `vnew` to create several windows and type some words in them.
3. Make sure the text cursor at the beginning of each window.
4. Add auto command `autocmd! CursorMoved * echom 'Moved to ' . winnr()`.
5. Use `wincmd w` or just use 'ctrl-w + w` to move cursor to other window.

**Screenshots**
![image](https://user-images.githubusercontent.com/86779711/124119546-3d6dd800-daa5-11eb-9cbd-64e92167a229.png)

**Environment (please complete the following information):**
 - Vim version:
![image](https://user-images.githubusercontent.com/86779711/124120442-5fb42580-daa6-11eb-832a-6ef8bb6854cc.png)
 - OS: Ubuntu 18.04.5

It also appear with GVim8.2 on Windows 7.

**Comment by lacygoill** [comment]
Use any of these events:

    BufLeave
    WinLeave
    WinEnter
    BufEnter

There is nothing at `:help CursorMoved` which suggests that the event should be fired when focusing a different window.  The help says that it should be fired when the cursor is moved while in Normal mode or Visual mode.

**Comment by AnnoyingUserName** [comment]
> Use any of these events:
> 
> ```
> BufLeave
> WinLeave
> WinEnter
> BufEnter
> ```
> 
> There is nothing at `:help CursorMoved` which suggests that the event should be fired when focusing a different window. The help says that it should be fired when the cursor is moved while in Normal mode or Visual mode.

In my understanding, moving from one window to another window is also a moving, do you agree it? And in general, say, cursor is not at the beginning or ending of the content, "CursorMoved" would be triggered.

**Comment by lacygoill** [comment]
> In my understanding, moving from one window to another window is also a moving, do you agree it?

Not necessarily, and what I think doesn't matter; I'm not a dev.  One could argue that it's anything listed at `:help cursor-motions` (from which `:wincmd w` is absent), and nothing else.  Others could argue that `:help window-move-cursor` should be included too.  In any case, as mentioned in the previous post, there are more accurate events to listen to if we want to execute arbitrary commands when focusing a different buffer/window.

**Comment by brammool** [comment]
If you consider the output of getcurpos(), if it doesn't change then CursorMoved probably should not trigger.
I see no good reason to change the current behavior, even when it may seem the cursor moved to another window, this was not really the intention of this event.
