### ISSUE TITLE
visual block yank changes behaviour when `virtualedit=block` is set

### ISSUE THREAD

**Issue by marcotrosi** [vim/vim#8495]
I don't know if this is a bug or if this is intentionally, but I would like to figure out what the reason is for it.

**Describing the behaviour**
When a visual block at line end is extended using the `$` command, then the yanking changes the behaviour when `virtualedit` is set to "block" compared to empty `virtualedit` settings.
1. when `virtualedit` is empty, then the yanking of lines with varying length will not contain trailing whitespaces.
2. when `virtualedit` is set to "block" and the selection is also extended using the `$` command, then the yanked text contains trailing whitespaces. Be aware that I did not make use of the virtual block editing, I only pressed `$`. I only changed the settings to `virtualedit=block`.
I don't see why the `virtualedit=block` setting would change the behaviour of the `y` command when the selection is exactly the same. 
I'm aware that now with the new `zy` command I can work my around this behaviour, but I still would like to know if this is a bug or a feature.

**To Reproduce**
create the following file lines for both scenarios ...
```
aaaaa
bbb
cc
```

scenario 1:
`:set virtualedit=""`
Select the text with visual block and extend with `$`, yank with the `y` command, run `:registers` and check the nameless register if it contains trailing whitespaces. there should be none.

scenario 2:
`:set virtualedit=block`
repeat the rest of scenario 1, and there should be whitespaces.

<img width="174" alt="virtual block with dollar" src="https://user-images.githubusercontent.com/8596795/124162820-3348db00-da9f-11eb-944f-b742bc632b09.png">

The screenshot shows how the selection should look  like. Use `$`. Don't make use of the virtual block.

**Expected behaviour**
I would expect that the register contents for both scenarios are the same. I don't see why the `virtualedit=block` setting would change the behaviour of the `y` command. If you want a rectangular yanked text with trailing whitespaces, then I simply would make use of the actual virtual block editing feature. But when I use `$` to extend the selection then I want what I selected.

**Environment**
- VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun 29 2021 18:36:25), macOS version - x86_64, Included patches: 1-3075, Compiled by Homebrew
 - OS: macOS 10.14
 - Terminal: kitty

**Comment by chrisbra** [comment]
Hm, I would say, this should have initially only been done after pressing `$` a second time, so that you also visually create a rectangular area. This might have been a bug, that no one noticed before.

**Comment by brammool** [comment]
This is a feature.  If you start the selection with CTRL-V on "cc" and move the cursor to the last "a" without using "$" you see that the trailing white space is selected.  Then using "$" should not change the selection, but the area highlighting is wrong.
So that is a bug, but what is yanked is OK.

**Comment by marcotrosi** [comment]
Thanks for the fast reaction, but I just build Vim with this modification and now `$` does not extend the selection anymore til end of the longest line but only til end of the current line.
<img width="242" alt="dollar changed" src="https://user-images.githubusercontent.com/8596795/124362703-ef88d980-dc36-11eb-9c88-eedd777b9347.png">
I understood that before only the highlighting was buggy, and the correct text was yanked, but now with this update the behaviour has changed.
I personally would like to get back the old behaviour of `$` (extending to longest line of selection), but of course with the correct highlighting which was buggy. Actually I think this is what you wanted to do, but now has been changed accidentally.
Of course we could go one step further and decide that pressing `$` repeatedly toggles between end of longest line and end of current line. This would be a mix of the original behaviour and what is implemented now, in case you prefer that.

**Comment by Ceda-EI** [comment]
I agree with @marcotrosi. The previous behavior would select the following content
![image](https://user-images.githubusercontent.com/19731116/124363100-d547ff00-dc28-11eb-988a-7ff01b908be3.png)
but it would display it as 
![image](https://user-images.githubusercontent.com/19731116/124363106-e264ee00-dc28-11eb-82b0-1c215865c878.png)

Although the bug was only in the are highlighting, the selection behavior seems to have changed.
