### ISSUE TITLE
Native support for JSON5/JSONC in Vim

### ISSUE THREAD

**Issue by IzhakJakov** [vim/vim#8499]
```
:version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul  1 2021 23:24:51)
Included patches: 1-3082
Compiled by tstUser@debianContainer
Huge version without GUI.  Features included (+) or not (-):
+acl               -clientserver      +diff              +folding           +langmap           +mouse_dec         +num64             +reltime           +syntax            +title             +windows
+arabic            -clipboard         +digraphs          -footer            +libcall           -mouse_gpm         +packages          +rightleft         +tag_binary        -toolbar           +writebackup
+autocmd           +cmdline_compl     -dnd               +fork()            +linebreak         -mouse_jsbterm     +path_extra        -ruby              -tag_old_static    +user_commands     -X11
+autochdir         +cmdline_hist      -ebcdic            -gettext           +lispindent        +mouse_netterm     -perl              +scrollbind        -tag_any_white     +vartabs           -xfontset
-autoservername    +cmdline_info      +emacs_tags        -hangul_input      +listcmds          +mouse_sgr         +persistent_undo   +signs             -tcl               +vertsplit         -xim
-balloon_eval      +comments          +eval              +iconv             +localmap          -mouse_sysmouse    +popupwin          +smartindent       +termguicolors     +virtualedit       -xpm
+balloon_eval_term +conceal           +ex_extra          +insert_expand     -lua               +mouse_urxvt       +postscript        -sodium            +terminal          +visual            -xsmp
-browse            +cryptv            +extra_search      +ipv6              +menu              +mouse_xterm       +printer           -sound             +terminfo          +visualextra       -xterm_clipboard
++builtin_terms    +cscope            -farsi             +job               +mksession         +multi_byte        +profile           +spell             +termresponse      +viminfo           -xterm_save
+byte_offset       +cursorbind        +file_in_path      +jumplist          +modify_fname      +multi_lang        -python            +startuptime       +textobjects       +vreplace
+channel           +cursorshape       +find_in_path      +keymap            +mouse             -mzscheme          -python3           +statusline        +textprop          +wildignore
+cindent           +dialog_con        +float             +lambda            -mouseshape        +netbeans_intg     +quickfix          -sun_workshop      +timers            +wildmenu
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -O2 -fno-strength-reduce -Wall -Wno-deprecated-declarations -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc -L/usr/local/lib -Wl,--as-needed -o vim -lm -ltinfo -ldl
```

I see more and more tools using jsonc and json5 formats for their configuration files.  I believe this trend will only increase and VIM should consider supporting these formats

### [jsonc](https://komkom.github.io)
Basically a JSON with C-style line (`//`) and block (`/**/`) comments.
Exiting vim plugin: https://github.com/kevinoid/vim-jsonc

### [json5](https://json5.org) 
Described as a json for humans.
Here is the specifications: https://spec.json5.org
Existing vim plugin for it already: https://github.com/gutenye/json5.vim

### Steps to reproduce using `vim -u NONE`

```
$ vim -u NONE sample.jsonc
<opened as a plain text>

$ vim -u NONE sample.json5
<opened as a plain text>
```

### Actual behaviour
opens up as a plain text

### Expected behaviour
Opened as a jsonc/json5 file:
- proper syntax highlighting
- proper error messages
- proper indentation and formatting

**Comment by izhakjakov** [comment]
Please add labels: syntax,  runtime

**Comment by izhakjakov** [comment]
I already created a JSONC indent and syntax files.  I'll for and push changes to my fork then link it here.

**Comment by k-takata** [comment]
If you're talking about Neovim, you should report [there](https://github.com/neovim/neovim/issues).

**Comment by izhakjakov** [comment]
I tested it on both

**Comment by izhakjakov** [comment]
https://github.com/neovim/neovim/issues/14947

**Comment by izhakjakov** [comment]
PR for VIM: https://github.com/vim/vim/pull/8500

**Comment by brammool** [comment]
there is no need for an issue when there is a pull request.

**Comment by izhakjakov** [comment]
At the moment only changes to support jsonc have will be committed in PR https://github.com/vim/vim/pull/8500
I am looking into adding native support for json5 as well.

**Comment by mazunki** [comment]
Is there any particular reason why we don't simply copy the linked plugin to support json5? Is there something missing in it, or any reason to not include json5 upstream?

**Comment by chrisbra** [comment]
what plugin you are talking about? As far  as I can see, the linked PR was included. So is there anything missing?

**Comment by mazunki** [comment]
I'm talking about the json5 plugin (https://github.com/gutenye/json5.vim). The PR which was included adds support for jsonc. While similar, jsonc lacks support for trailing commas, newlines in strings, hexadecimal numbers... which json5 supports.

**Comment by IzhakJakov** [comment]
json5 seems to be a better version of jsonc I would suggest using [the plugin](https://github.com/gutenye/json5.vim) for both.  I currently use treesitter for syntax highlighting so maybe should be removed from the vim runtime version.

**Comment by mike-clark-8192** [comment]
`jsonc` and `json5` are distinct enough that I'd like to see support for both. `jsonc` is widely used throughout VSCode and orbiting technologies like TypeScript (example: tsconfig.json).  I don't think `json5` is as widely deployed as `jsonc` at this time. But, `json5` is a better spec -- not least of which because it actually has a spec. All jsonc has is a [defacto reference implementation](https://github.com/microsoft/node-jsonc-parser/).

I would like to see a bundled `jsonc.vim` have a configuration option to allow trailing commas, like [node-jsonc-parser](https://github.com/microsoft/node-jsonc-parser/) has.  That parser has support for it turned off by default, but you can flip a boolean to support it.
