### ISSUE TITLE
`:caddexpr` doesn't remember directories entered (and left)

### ISSUE THREAD

**Issue by LucHermitte** [vim/vim#850]
Note: The long term objective is to call `:caddexpr` on the text received through `job_start()` callback.

Given the current directory that contains: `tests/caddexpr-directory.vim` which is the script being executed.

The following doesn't work as expected. While `Entering directory` is correctly processed when the qflist is build from several lines, the current directory information is lost in between two calls to `:caddexpr`.

The following Minimal Working Example demonstrates the problem.

``` vim
let s:file = expand('<sfile>:.')
let s:dir = expand('<sfile>:.:h')

let s:messages = [
      \ s:file . ':5: in the correct directory',
      \ "vim[1]: Entering directory '".s:dir."'",
      \ expand('<sfile>:t').':7: Not in the correct directory',
      \ "vim[1]: Leaving directory '".s:dir."'",
      \ ]

function! s:RunMultipleAddexpr()
  echomsg "Multiple uses of caddexpr"
  call setqflist([])
  for msg in s:messages
    caddexpr msg
  endfor
  copen

  let qf = getqflist()
  call assert_equal(s:file, bufname(qf[2].bufnr))
endfunction

function! s:RunOneAddexpr()
  echomsg "Single use of caddexpr"
  call setqflist([])
  caddexpr s:messages
  copen

  let qf = getqflist()
  call assert_equal(s:file, bufname(qf[2].bufnr))
endfunction

let v:errors = []
call s:RunOneAddexpr()
call s:RunMultipleAddexpr()
echomsg join(v:errors, "\n")

```

**Comment by brammool** [comment]
Luc Hermitte wrote:

> Note: The long term objective is to call `:caddexpr` on the text received through `job_start()` callback.
> 
> Given the current directory that contains:
> `tests/caddexpr-directory.vim` which is the script being executed.
> 
> The following doesn't work as expected. While `Entering directory` is
> correctly processed when the qflist is build from several lines, the
> current directory information is lost in between two calls to
> `:caddexpr`.

Yes, the directory stack is only kept in internal state.  It should not
be too difficult to store it with the quickfix list and only clear it
when clearing the list.

## 

hundred-and-one symptoms of being an internet addict:
57. You begin to wonder how on earth your service provider is allowed to call
    200 hours per month "unlimited."

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by LucHermitte** [comment]
This issue seems to have been fixed. Do you remember the patch number that has fixed it?

**Comment by LucHermitte** [comment]
It looks like to be the patch 7.4-1980. I close the issue. 
Thank you!
