### ISSUE TITLE
E435 / Hit-enter appears to cause E12 and interrupt job callback

### ISSUE THREAD

**Issue by airblade** [vim/vim#8511]
**Describe the bug**
A tag search resulting in an E435 (couldn't find tag) and hit-enter prompt appears to cause an E12 (command not allowed) and break a job's callback.

The full description is here: https://github.com/airblade/vim-gitgutter/issues/787.

I wonder whether the E12 causes the job callback to fail?  I don't know why an E435 would cause an E12 though.

**To Reproduce**
Unfortunately I cannot reproduce this; it was reported to me (see link above).

**Expected behavior**
Tag searching errors do not interrupt a job callback.

**Environment**
Vim 8.2.3000
macOS

**Additional context**
Searching the issues here turned up https://github.com/vim/vim/issues/3705; I don't know if it is relevant.

**Comment by brammool** [comment]
Andy Stewart wrote:

> **Describe the bug**
> A tag search resulting in an E435 (couldn't find tag) and hit-enter prompt appears to cause an E12 (command not allowed) and break a job's callback.
> 
> The full description is here: https://github.com/airblade/vim-gitgutter/issues/787.
> 
> I wonder whether the E12 causes the job callback to fail?  I don't know why an E435 would cause an E12 though.
> 
> **To Reproduce**
> Unfortunately I cannot reproduce this; it was reported to me (see link above).
> 
> **Expected behavior**
> Tag searching errors do not interrupt a job callback.
> 
> **Environment**
> Vim 8.2.3000
> macOS
> 
> **Additional context**
> Searching the issues here turned up
> https://github.com/vim/vim/issues/3705; I don't know if it is
> relevant.

One of the methods to locate the tag in a file is using a command.
Theoretically someone could sneak in a bad command in a tag file.
Thus Vim executes the command in a kind of sandbox.

I think what happens is that during the search we check for CTRL-C
typed, which also handles channel messages.  A channel callback then
runs into this sandbox.

Looking at jumpto_tag(), I don't think the sandbox need to be used when
searching.  We can probably move the sandbox stuff to around the call to
do_cmdline_cmd().

Try this patch:


--- vim/src/tag.c	2021-05-18 21:46:27.720961234 +0200
+++ vim/vim82/src/tag.c	2021-07-05 19:58:43.361996309 +0200
@@ -3312,7 +3312,6 @@
     int		forceit,	// :ta with !
     int		keep_help)	// keep help flag (FALSE for cscope)
 {
-    int		save_secure;
     optmagic_T	save_magic_overruled;
     int		save_p_ws, save_p_scs, save_p_ic;
     linenr_T	save_lnum;
@@ -3500,11 +3499,6 @@
 	curwin->w_set_curswant = TRUE;
 	postponed_split = 0;
 
-	save_secure = secure;
-	secure = 1;
-#ifdef HAVE_SANDBOX
-	++sandbox;
-#endif
 	save_magic_overruled = magic_overruled;
 	magic_overruled = OPTION_MAGIC_OFF;	// always execute with 'nomagic'
 #ifdef FEAT_SEARCH_EXTRA
@@ -3621,22 +3615,28 @@
 	}
 	else
 	{
+	    int		save_secure = secure;
+
+	    // Setup the sandbox for executing the command from the tags file.
+	    secure = 1;
+#ifdef HAVE_SANDBOX
+	    ++sandbox;
+#endif
 	    curwin->w_cursor.lnum = 1;		// start command in line 1
 	    do_cmdline_cmd(pbuf);
 	    retval = OK;
-	}
 
-	/*
-	 * When the command has done something that is not allowed make sure
-	 * the error message can be seen.
-	 */
-	if (secure == 2)
-	    wait_return(TRUE);
-	secure = save_secure;
-	magic_overruled = save_magic_overruled;
+	    // When the command has done something that is not allowed make
+	    // sure the error message can be seen.
+	    if (secure == 2)
+		wait_return(TRUE);
+	    secure = save_secure;
 #ifdef HAVE_SANDBOX
-	--sandbox;
+	    --sandbox;
 #endif
+	}
+
+	magic_overruled = save_magic_overruled;
 #ifdef FEAT_SEARCH_EXTRA
 	// restore no_hlsearch when keeping the old search pattern
 	if (search_options)

-- 
From "know your smileys":
 8<}}	Glasses, big nose, beard

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by airblade** [comment]
Thank you very much for the reply and the patch.

As I was never able to reproduce the problem I can't confirm whether the patch solves it.  @jparise Are you able to test the patch?

**Comment by jparise** [comment]
After rebuilding my `tags` file, I'm no longer able to reproduce the original issue, so I unfortunately can't verify the patch.

However, the idea that this is related to the sandbox is consistent with a similar bug reported for ALE: https://github.com/dense-analysis/ale/issues/338

**Comment by jparise** [comment]
I was able to "break" my `tags` file once again by manually editing it. I'll build a local `vim` with the proposed patch and report back.

**Comment by jparise** [comment]
I can verify that the proposed patch fixes the issue I was seeing. It now behaves like we'd expect when a tag search results in a "guess":

```
E435: Couldn't find tag, just guessing!
Press ENTER or type command to continue
```

... without an error in the async job callback.
