### ISSUE TITLE
Add listchars option to customize all control characters

### ISSUE THREAD

**Issue by defdefred** [vim/vim#8517]
Vim is perfectly able to display control characters with ^A to ^Z and more appearance, but it could be fun to customize these "not really printable" characters with unicode glyphe. 

The set listchars command seems the good candidate to handle this using the common name of control characters: https://en.wikipedia.org/wiki/C0_and_C1_control_codes#Basic_ASCII_control_codes

**Comment by marcotrosi** [comment]
I would be interested in the use case you had that made you write this issue. (but I generally like the idea, but I would like to understand it more if possible and if you don't mind)

**Comment by chrisbra** [comment]
you might be able to use concealing for that.

**Comment by marcotrosi** [comment]
@defdefred I tried as @chrisbra suggested
works nicely.

<img width="622" alt="ccc" src="https://user-images.githubusercontent.com/8596795/125788512-b3021464-80d7-4f19-a5d8-8c6b6c670313.png">

**Comment by defdefred** [comment]
> I would be interested in the use case you had that made you write this issue. (but I generally like the idea, but I would like to understand it more if possible and if you don't mind)

It will be a wonderfull way to re-use these abandoned characters as field separator in binary files what will be friendly readable with vim.

**Comment by defdefred** [comment]
> you might be able to use concealing for that.

Thanks!

**Comment by defdefred** [comment]
> @defdefred I tried as @chrisbra suggested
> works nicely.
> 
> <img alt="ccc" width="622" src="https://user-images.githubusercontent.com/8596795/125788512-b3021464-80d7-4f19-a5d8-8c6b6c670313.png">

Thanks! will try :-)

**Comment by chrisbra** [comment]
> But why two method to change how character are displayed? listchar vs conceal ?

Those are somehow overlapping features. Initially, there was only the possibility to display certain characters differently, most notably, the `tab` and the end-of-line character. Later it has been improved to allow additional characters, like spaces and others. At the same time, the conceal feature was introduced, that allows some more flexibility on what parts of the text (so not just single characters) to show differently. This is much more flexible (e.g. by allowing syntax files to configure it per language and window), but also introduced several new bugs and may slow down vim a bit. So we now have both methods. Use whatever works for you.

So I assume we can close this.

**Comment by defdefred** [comment]
Thanks!
I saw also that behavior is not the same.
listchar => permanent display
conceal => only when not editing

*This is already fine*

Maybe listchar will also permit permanent display of alternate glyphe for control charactère sometime, in a distant future :-)

**Comment by chrisbra** [comment]
> conceal => only when not editing

`:h concealcursor`

**Comment by defdefred** [comment]
You are a boss, Thanks!

I tried all control character and 2 are not working:
- nul 0 (I may have found a bug!)
- eol (understandable and working with listchars)
