### ISSUE TITLE
[Doc][Proposal] Add sample code to avoid possible misreading about map() and mapnew()

### ISSUE THREAD

**Issue by obcat** [vim/vim#8518]
**Problem**

Below `:h E1024`, there is a paragraph that describes a map()'s limitation in Vim9 script:

```help
One consequence is that the item type of a list or dict given to map() must
not change.  This will give an error in Vim9 script: >
	map([1, 2, 3], (i, v) => 'item ' .. i)
	E1012: Type mismatch; expected number but got string
Instead use |mapnew()|.  If the item type was determined to be "any" it can
change to a more specific type.  E.g. when a list of mixed types gets changed
to a list of numbers.
```

The last two sentence `If the item ...  E.g. when a ...` is about map(), not about mapnew(), in my understanding, but it looks like about mapnew() because the the previous sentence `Instead use |mapnew()|.` changed the topic to mapnew().

Actually, in a Japanese Vim community, I and some people did this misreading when reading first time.

**Proposal**

To avoid this misreading, I propose adding an example code like this:

```diff
diff --git a/runtime/doc/vim9.txt b/runtime/doc/vim9.txt
index e8d97a9c3..b36eeeda3 100644
--- a/runtime/doc/vim9.txt
+++ b/runtime/doc/vim9.txt
@@ -1211,7 +1211,10 @@ not change.  This will give an error in Vim9 script: >
 	E1012: Type mismatch; expected number but got string
 Instead use |mapnew()|.  If the item type was determined to be "any" it can
 change to a more specific type.  E.g. when a list of mixed types gets changed
-to a list of numbers.
+to a list of numbers: >
+	var mylist = [1, 2.0, '3']  # list<any>
+	map(mylist, (i, v) => 'item ' .. i)
+	# No error, now typename(mylist) == 'list<number>'
 Same for |extend()|, use |extendnew()| instead, and for |flatten()|, use
 |flattennew()| instead.
```

**Environment**
 - Vim 8.2.3113

**Comment by brammool** [comment]
Thanks for the suggestion, it's indeed confusing.
Additionally, we can also repeat the first example but with mapnew():

One consequence is that the item type of a list or dict given to map() must
not change.  This will give an error in Vim9 script:
        vim9 echo map([1, 2, 3], (i, v) => 'item ' .. i)
        E1012: Type mismatch; expected number but got string
Instead use |mapnew():
        vim9 echo mapnew([1, 2, 3], (i, v) => 'item ' .. i)
        ['item 0', 'item 1', 'item 2']

**Comment by obcat** [comment]
That's good. More examples would help reduce confusion.

Oh, I found a mistake in my patch... (s/number/string)
Here is a corrected version with a similar additional example:

```help
One consequence is that the item type of a list or dict given to |map()| must
not change.  This will give an error in Vim9 script: >
	var numList = [1, 2, 3]
	map(numList, (i, v) => 'item ' .. i)
	# E1012: Type mismatch; expected number but got string
Instead use |mapnew()| to create a new one: >
	var strList = mapnew(numList, (i, v) => 'item ' .. i)
If the item type was determined to be "any" it can change to a more specific
type.  E.g. when a list of mixed types gets changed to a list of strings: >
	var xList = [1, 2.0, '3']           # list<any>
	map(xList, (i, v) => 'item ' .. i)  # No error, changed to list<string>
```

I hope this helps. Thank you.
