### ISSUE TITLE
popup windows with the same zindex default behavior

### ISSUE THREAD

**Issue by monkoose** [vim/vim#8522]
**Describe the bug**
Current behavior of the popups with the same zindex is that visible is the first one created.
Isn't that in almost all the cases you want to see the last one opened popup even if it has the same zindex? In a lot of cases thinking about zindex will just add a lot of unnecessary workaround.

If there is some implementation design behind it, can you explain why it was chosen to act like so? Thank you.

**Expected behavior**
Last one opened popup should have precedence over others even with the same zindex.

**Comment by brammool** [comment]
you should really use the "zindex" to organize popups.  Using the first one is just an explanation of what happens in case of a mistake or two plugins not working well together.
Since the change would be rather arbitrary and might break existing plugins, I rather leave it as it is.
