### ISSUE TITLE
Visual glitches with specific settings

### ISSUE THREAD

**Issue by fedorenchik** [vim/vim#8524]
**Describe the bug**
Visual glitches with specific settings, please see screenshots.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `gvim --clean`
2. Edit file or enter some text with empty and non-empty lines, for example:
```
aaa
aaa
aaa


aa
aa

a

aaaaaaaaaaaaa
```
3. Enter following commands:
```vim
set columns=80 lines=25
vsplit | vsplit
windo set signcolumn=yes foldcolumn=1 winminwidth=0 nowrap list listchars=extends:>,precedes:<
23wincmd >
" first glitch: non-empty lines render '>', empty lines render signcolumn
2wincmd >
" second glitch: non-empty lines render '>', empty lines render signcolumn and border of window on left disappears for those lines only
```
4. Observe glitches 1 and 2.

**Expected behavior**
No glitches.

**Screenshots**

Glitch 1:

![Screenshot from 2021-07-08 10-20-18](https://user-images.githubusercontent.com/391735/124852236-9a521c80-dfd6-11eb-97b9-aa79f8a21dd3.png)

Glitch 2:

![Screenshot from 2021-07-08 10-20-24](https://user-images.githubusercontent.com/391735/124852269-a5a54800-dfd6-11eb-9069-663f4937d24b.png)

**Environment (please complete the following information):**
 - Vim version 8.2.3113
 - OS: Manjaro Gnome
 - Terminal: GUI GTK3, kitty

**Additional context**
Appears both in GUI (gvim) and terminal (vim).

**Comment by brammool** [comment]
I think there is no use of showing the "exceeds" character inside the signcolumn, it only indicates non-empty lines.
