### ISSUE TITLE
Visual glitches with 'foldcolumn' and 'signcolumn'

### ISSUE THREAD

**Issue by fedorenchik** [vim/vim#8525]
**Describe the bug**
Visual glitches with 'foldcolumn' and 'signcolumn' in certain conditions.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean` or `gvim --clean`
2. Enter text:
```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa



aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```
3. Type following commands:
```vim
set columns=80 lines=25
vsplit | vsplit
windo set signcolumn=yes foldcolumn=4
20wincmd >
" glitch 1: whole middle window is filled with foldcolumn and signcolumn
wincmd h
normal gg
14wincmd <
" glitch 2: cursor in signcolumn on last line
5wincmd >
normal j
5wincmd <
" glitch 3: cursor in @@@ line (maybe it's expected ?)
set nowrap
" giltch 4: cursor on last line of window
```
4. Observe the glitches (also in screenshots).

**Expected behavior**
No glitches.

**Screenshots**

Glitch 1:

![Screenshot from 2021-07-08 11-01-53](https://user-images.githubusercontent.com/391735/124856729-a1305d80-dfdd-11eb-84f4-b11a389a3147.png)

Glitch 2:

![Screenshot from 2021-07-08 11-02-41](https://user-images.githubusercontent.com/391735/124856739-a68da800-dfdd-11eb-969f-4e92a2927482.png)

Glitch 3:

![Screenshot from 2021-07-08 11-03-14](https://user-images.githubusercontent.com/391735/124856748-abeaf280-dfdd-11eb-876c-35b2ff292f34.png)

Glitch 4:

![Screenshot from 2021-07-08 11-03-47](https://user-images.githubusercontent.com/391735/124856757-b1483d00-dfdd-11eb-8243-ffb1a4297f37.png)

**Environment (please complete the following information):**
 - Vim version: 8.2.3113
 - OS: Manjaro Gnome
 - Terminal: kitty, GUI GTK3

**Comment by brammool** [comment]
Leonid V. Fedorenchik wrote:

> **Describe the bug**
> Visual glitches with 'foldcolumn' and 'signcolumn' in certain conditions.
> 
> **To Reproduce**
> Detailed steps to reproduce the behavior:
> 1. Run `vim --clean` or `gvim --clean`
> 2. Enter text:
> ```
> aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
> 
> 
> 
> aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
> ```
> 3. Type following commands:
> ```vim
> set columns=80 lines=25
> vsplit | vsplit
> windo set signcolumn=yes foldcolumn=4
> 20wincmd >
> " glitch 1: whole middle window is filled with foldcolumn and signcolumn

This is more or less consistent with how the sign and foldcolumns grow
when there is less space for text.

> wincmd h
> normal gg
> 14wincmd <
> " glitch 2: cursor in signcolumn on last line

Well, where else to put it?  No text is visible.

> 5wincmd >
> normal j
> 5wincmd <
> " glitch 3: cursor in @@@ line (maybe it's expected ?)

This was fixed by patch 8.2.3121.

> set nowrap
> " giltch 4: cursor on last line of window
> ```
> 4. Observe the glitches (also in screenshots).

That is a bit unexpected, since it is not in the displayed lines.

-- 
From "know your smileys":
 C=}>;*{)) Drunk, devilish chef with a toupee in an updraft,
	   a mustache, and a double chin

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
