### ISSUE TITLE
Vim9: could the definition of a nested function persist after failing to compile?

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8526]
If a function fails to compile, we can still retrieve its definition, and its exact location:
```vim
vim9script
def g:Func()
    eval 1
    eval 2
    eval 3
    var x: number = ''
enddef
defcompile
```
    Error detected while compiling ... function g:Func:
    E1012: Type mismatch; expected number but got string

Then:

    :verbose def Func

Gives:

    def Func()
         Last set from ... line 2

But if the function which fails to compile is nested, we can no longer retrieve its definition, nor its location:
```vim
vim9script
def A()
    def B()
        eval 1
        eval 2
        eval 3
        var x: number = ''
    enddef
enddef
defcompile
```
    Error detected while compiling ... function <SNR>1_A[1]..<lambda>1:
    E1012: Type mismatch; expected number but got string

This time, `:def` and `:verbose` fail to give us any information regarding the problematic function:

    :verbose def <lambda>1
    E123: Undefined function: <lambda>1

The limitation is specific to an error detected at compile time.  We can still retrieve the definition if the error was detected later, at runtime:
```vim
vim9script
def A()
    def B()
        eval 1
        eval 2
        eval 3
        eval [][0]
    enddef
    B()
enddef
A()
```
    Error detected while processing ... function <SNR>1_Func[7]..<lambda>1:
    E684: list index out of range: 0

Then:

    :verbose def <lambda>1

Gives:

    def <lambda>1()
         Last set from ... line 4
                       ^--------^

I need this information to improve [a plugin](https://github.com/lacygoill/vim-stacktrace) which populates the quickfix list with the exact locations of the last given errors.  It currently fails to jump to an error given from a nested function which failed to compile.  It stops at the outer function.

I thought I could implement a workaround, but it would probably be brittle.  In particular, it wouldn't be easy to handle multiple level of nesting:
```vim
vim9script
def A()
    def B()
        def C()
            eval 1
            eval 2
            eval 3
            var x: number = ''
        enddef
    enddef
enddef
defcompile
```
    Error detected while compiling ... function <SNR>1_A[1]..<lambda>1[1]..<lambda>2:
    E1012: Type mismatch; expected number but got string

We can retrieve the definition/location of a regular function which failed to compile.
We can retrieve the definition/location of a lambda which failed to evaluate at runtime.
Why can't we retrieve the definition/location of a lambda which failed to compile?

**Comment by brammool** [comment]
The reason is that the nested function is not referenced anywhere.  If the compilation succeeds, a reference to the function will be in the generated instructions for the containing function.  If the compilation fails this doesn't happen.  If we would keep the function it would leak memory.
I don't think your specific use case justifies leaking lambda's.
