### ISSUE TITLE
Strange page in wiki

### ISSUE THREAD

**Issue by rhysd** [vim/vim#8528]
**Describe the bug**

Someone created wiki page in Chinese at top level of tree. I don't understand Chinese so I'm not sure what is written, but it seems not related to Vim.

https://github.com/vim/vim/wiki/utils%E6%A8%A1%E5%9D%97%E8%AF%B4%E6%98%8E

I want to confirm two things:

- Is the page intended? If not, I think it should be removed
- Is it intended configuration that anyone can edit Wiki page of vim/vim?

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Environment (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by kuuote** [comment]
I deleted the page because the content was obviously not relevant.
I'm sorry I only noticed this issue after I deleted it.

**Comment by thinca** [comment]
`Popup-window-gallery.md` was removed instead.
https://github.com/vim/vim/wiki/_compare/b8258bc6f614f49f9acee77c23ee46f1f17b998b...7be11ca67f2f885c7600541b0f64e17f8c37fef2

All histries can be found here https://github.com/vim/vim/wiki/_history

FYI

GitHub Wiki is just a Git repository, so we can destroy these histories with `git push -f` if you wish:

```
$ git clone https://github.com/vim/vim.wiki.git
$ cd vim.wiki
$ git reset --hard b8258bc
$ git push -f
```

**Comment by k-takata** [comment]
Thank you @thinca. I have fixed it.

**Comment by k-takata** [comment]
I'm thinking if we should restrict editing the wiki page.

**Comment by brammool** [comment]
Only logged in github users can edit the wiki, right?  Hopefully that prevents too much spam.

The page was removed, so we can close this issue.
