### ISSUE TITLE
:find incorrectly searches parent directory of path

### ISSUE THREAD

**Issue by numEricL** [vim/vim#8533]
**Describe the bug**
`:find` and similar functions incorrectly searches the parent directory of a relative path.

**To Reproduce**
1. Create the following directory structure so that dir2 is the working directory
```
dir1
├── dir2
│   └── base.txt
└── file.txt
```
2. Run `vim --clean -c 'set path=../include' base.txt`
3. execute `:find file.txt`
4. `file.txt` is loaded, even though the path points to the nonexistent `../include` directory.

**Expected behavior**
An error such as the following should be produced
`E447: Can't find file "file.txt" in path`

**Environment (please complete the following information):**
Reproducible on an ubuntu 20.04 machine with vim 8.1 patches 1-2269.
The correct behavior is observed wtih vim 7.4 patches 1-160

**Comment by lacygoill** [comment]
The new behavior was introduced in [7.4.885](https://github.com/vim/vim/releases/tag/v7.4.885).

**Comment by chrisbra** [comment]
Hm, Vim checks, whether the directory given by the path option does exist, and if not, it starts adding the beginning of the path option to the path to start looking for, which means, vim will search in `/path/to/dir1/dir2/..`. This seems to be done on purpose, so not sure why this is done.

Here is a simple patch to fix this behaviour, not sure it works correctly:
```patch
diff --git a/src/findfile.c b/src/findfile.c
index a72fe45ad..c335f4198 100644
--- a/src/findfile.c
+++ b/src/findfile.c
@@ -579,6 +579,12 @@ vim_findfile_init(
            if (p > search_ctx->ffsc_fix_path)
            {
                len = (int)(p - search_ctx->ffsc_fix_path) - 1;
+               // do not add '..' to the path and start upwards searching
+               if (STRNCMP(search_ctx->ffsc_fix_path, "..", 2) == 0)
+               {
+                   vim_free(buf);
+                   goto error_return;
+               }
                STRNCAT(ff_expand_buffer, search_ctx->ffsc_fix_path, len);
                add_pathsep(ff_expand_buffer);
            }
``` 

(let's see if this breaks anything)

**Comment by chrisbra** [comment]
hm, perhaps it also needs to check that stopdirs is null.
