### ISSUE TITLE
netrw_sizestyle not working as expected

### ISSUE THREAD

**Issue by pguerin3** [vim/vim#8535]
**Describe the bug**
I'm using gvim 8.2 in Windows 10, and I have the following in the vimrc
```
set nocompatible
filetype plugin on
let g:netrw_sizestyle = "H"
```

However when I open gvim, I always get the bytes listing when viewing the long format in netrw.
If I change the value to h, there is on change in behaviour.

**Expected behavior**
I always get bytes, instead of the human readable format.

**Environment (please complete the following information):**
 - Vim version 
```
 - VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 25 2020 11:44:06)
Included patches: 1-1895
```
 - OS:
```
Microsoft Windows 10.0.19042
```
 - Terminal: [GUI]

**Comment by brammool** [comment]
@cecamp

**Comment by cecamp** [comment]
I'll look into it.

**Comment by trysten** [comment]
For me, `qf` responds to the setting but the detailed listing does not.

**Comment by pguerin3** [comment]
I'm using Vim 9 now.
This feature works for me, regardless of if I cycle through the different views using 'i', or I create another netrw with 'e .'.
Also works if I enter the configuration interactively, or I enter it inside the config file.
So as far as I'm concerned my issue is fixed.
