### ISSUE TITLE
Vim9: no error when passing invalid string expression to getline()

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8536]
**Describe the bug**

In Vim9 script, no error is given when we pass an invalid string expression to `getline()`.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        var intro = 'once upon a time'
        intro->setline(1)
        echo getline('1') == intro
    EOF
    )

`false` is echo'ed.

**Expected behavior**

Nothing is echo'ed.  An error is given.  Something like:

    E1234: Invalid line position for getline()

**Environment**

 - Vim version: 8.2 Included patches: 1-3132
 - OS: Ubuntu 20.04.2 LTS
 - Terminal: XTerm(353)

**Additional context**

In legacy, the same code works:
```vim
vim9script
function Legacy()
    let intro = 'once upon a time'
    eval intro->setline(1)
    echo getline('1') == intro
endfunction
Legacy()
```
    1

IMO, the fact that it works in legacy was wrong.  A string should not be automatically coerced into a number; at least not here.  So, Vim9 is better in that regard.  However, it is not OK for Vim9 to accept any string, and silently discard the ones which don't match any known position.

While I was working on a legacy plugin, I've lost quite a bit of time trying to figure out why it behaved differently once it was refactored in Vim9.  It would have been much easier if Vim had given an error when I passed an invalid string to `getline()`, instead of silently accepting it, and returning an empty string.

Here is a relevant excerpt from `:help getline()`:

   > When {lnum} is a String that doesn't start with a
   > digit, |line()| is called to translate the String into a Number.

About the first part of this sentence: we might want to add something about Vim9 not handling a string which starts with a number like in legacy.  In legacy, the string `'123foo'` is handled like the number `123` (which is bad).  Maybe we should say that – in Vim9 – the same string is currently discarded (or, if this issue is fixed, an error is given).

About the second part of this sentence: here is what `:help line()` says:

   > The result is a Number, which is the line number of the file
   > position given with {expr}.  The accepted positions are:
   >     .       the cursor position
   >     $       the last line in the current buffer
   >     'x      position of mark x (if the mark is not set, 0 is
   >             returned)
   >     w0      first line visible in current window (one if the
   >             display isn't updated, e.g. in silent Ex mode)
   >     w$      last line visible in current window (this is one
   >             less than "w0" if no lines are visible)
   >     v       In Visual mode: the start of the Visual area (the
   >             cursor is the end).  When not in Visual mode
   >             returns the cursor position.  Differs from |'<| in
   >             that it's updated right away.

There are only 6 strings which are valid:

    '.'
    '$'
    "'x"
    'w0'
    'w$'
    'v'

Actually, `'x` stands for any local mark; there can be quite a few (they probably match this regex `[a-zA-Z'[\]<>0-9"^.(){}]`), so it's a bit more than that.  In any case, the number of valid strings is still limited.  I think Vim9 should only accept those strings; for anything else, an error should be given.  Possibly at compile time; at least at runtime.

---

The issue is not specific to `getline()`.  It applies to any builtin function which accepts a string expression to denote a position in the current buffer:

    appendbufline()
    col()
    deletebufline()
    getline()
    getpos()
    line()
    sign_getplaced()
    sign_place()
    sign_placelist()

Here is yet another example with `append()`:
```vim
vim9script
append('0', 'text')
echo 'no error'
```
    no error

Again, an error should have been given. Only a number should be accepted; as well as the few string expressions documented at `:help line()`.  `'0'` is not one of them.

Same issue in compiled code:
```vim
vim9script
def Func()
    append('0', 'text')
    echo 'no error'
enddef
Func()
```
    no error

**Comment by lacygoill** [comment]
Not sure whether it's exhaustive, but here is a more complete list of builtin functions accepting strings to represent a position in the current buffer:

    append()
    appendbufline()
    cindent()
    col()
    deletebufline()
    diff_filler()
    diff_hlID()
    foldclosed()
    foldclosedend()
    foldlevel()
    foldtextresult()
    getbufline()
    getline()
    getpos()
    indent()
    line()
    line2byte()
    lispindent()
    nextnonblank()
    prevnonblank()
    setbufline()
    setline()
    sign_getplaced()
    sign_place()
    sign_placelist()
    synID()
    synconcealed()
    synstack()

Although, not all of them accept all the strings documented at `:help line()`.  For example, I think `appendbufline()` only accepts the string `'$'`.

**Comment by lacygoill** [comment]
I wonder whether it would help to allow a coercion from string to number, but only if the string matches a whole number.  No text before, no text after:

    echo getline('abc123')
    # error

    echo getline('123abc')
    # error

    echo getline('123')
    # OK

**Comment by brammool** [comment]
We should try to keep this simple, rules with exceptions make it unpredictable.
Generally, in Vim9 script there is no automatic conversion from a string with digits to a number.
I think we should not have too many exceptions to this rule.
For a line number, it's clear that a number is expected.  A string can be used for what line() supports, but not for a number.
This isn't completely implemented yet, Yegappan is working on the compile time checks.
I see that the runtime type check isn't done properly, let's use this issue for that.
