### ISSUE TITLE
Vim9: allowing variable to shadow Ex command causes too many issues

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8538]
**The problem.**

Right now, when a token can be parsed as an Ex command or a variable, Vim9 gives the priority to the variable:
```vim
vim9script
setline(1, 'this should be undone, but will not')
var undo: bool
undo
echo getline(1)
```
    this should be undone, but will not

This is working as intended:

   > Variables may shadow Ex commands, rename the variable if needed.

The suggestion given by the help ("rename the variable if needed") is OK when we work on some new and simple code.  But it is not OK otherwise.

I've just finished refactoring a popular legacy plugin into Vim9.  All went well until the last function implementing an interactive command.

Here is the [problematic line](https://github.com/junegunn/vim-easy-align/blob/12dd6316974f71ce333e360c0260b4e1f81169c3/autoload/easy_align.vim#L638):

    silent! undo

It works in legacy but not in Vim9.  That's because:

   - in this particular function, the author named their variable just like a well-known Ex command
   - when there is ambiguity between an Ex command and a variable, Vim gives the priority to the variable

The issue seems simple, but it's not always easy to debug.  Note that [the body of the function contains 200 lines of code](https://github.com/junegunn/vim-easy-align/blob/12dd6316974f71ce333e360c0260b4e1f81169c3/autoload/easy_align.vim#L623-L820), with poorly-named variables.  Most of which is a while loop with deeply nested function calls (which in total runs more than 1K lines), and is only meant to be called interactively.  The issue only had consequences at the end of another function called at the top of a stack of 4 function calls:

    Interactive()
    →
    Process()
    →
    DoAlign()
    →
    SplitLine()

And the last function was – just by itself – hard to debug.  It took me a good part of the day to travel from the consequence of the issue back to its real origin.  I'm sure other people will encounter similar issues.  I'm not sure what, but something *definitely* needs to be changed.

**A possible solution.**

Luckily, we already had a similar issue in the past, and the way we solved it could work here again.  There is an ambiguity between a dictionary and a block.  To lift the ambiguity, we need to surround the dictionary with parentheses:
```vim
vim9script
{
  a: 1,
  b: 2
}->keys()->setline(1)
```
    E121: Undefined variable: a:

Here, Vim conflates the dictionary `{a: 1, b: 2}` with a block of statements.
```vim
vim9script
[0]->mapnew((_, v) => {a: 1, b: 2})->setline(1)
```
    E488: Trailing characters: a: 1, b: 2})->setline(1)

And here again, Vim conflates the dictionary `{a: 1, b: 2}` with a block of statements.

In both cases, to lift the ambiguity, we can surround the dictionary with parens:
```vim
vim9script
  # v
    ({
      a: 1,
      b: 2
    })->setline(1)
  #  ^
```
    {'a': 1, 'b': 2}
```vim
vim9script
[0]->mapnew((_, v) => ({a: 1, b: 2}))->setline(1)
  #                   ^            ^
```
    {'a': 1, 'b': 2}

We could extend this rule to variables named like Ex commands: if we want to write a variable at the start of a line, it should be surrounded with parentheses.  This way, the original snippet would work as expected:
```vim
vim9script
setline(1, 'this should be undone, but will not')
var undo: bool
undo
```
    the line would be undone

And if we want to write the variable at the start of a line, we simply put parens around:
```vim
vim9script
var undo = true
    (undo)->setline(1)
  # ^    ^
```
    true

[This suggestion would fix other issues](https://github.com/vim/vim/issues/6593#issuecomment-866077728), at the same time, making the language more predictable.

**A question.**

I suspect that giving the priority to variables versus commands creates other issues.  Is there a good reason for this?  Do we really need to be able to write a variable – without parens – at the start of a line?

The only case where it makes sense to write a variable at the start of a line is when it's passed to a function via a method.  Otherwise, it doesn't even work:
```vim
vim9script
var nope = 0
nope + 1 - 2
```
    E492: Not an editor command: nope + 1 - 2

As for the method case:
```vim
vim9script
var ok = 123
ok->setline(1)
echo getline(1)
```
    123

It's trivial to add parens:
```vim
vim9script
var ok = 123
(ok)->setline(1)
echo getline(1)
```
    123

BTW, the current situation is really inconsistent:
```vim
vim9script
var name: number
name
echo 'no error'
```
    no error
```vim
vim9script
var name: number
name + 1
```
    E492: Not an editor command: name + 1
```vim
vim9script
var name: number
name->setline(1)
echo 'no error'
```
    no error

Sometimes, Vim parses `name` as a command; sometimes as a variable.  Which criteria are used to determine whether `name` should be parsed as a command or a variable?

IMO, they should all give errors.  This way, the rules are very simple to understand, and Vim's behavior is easy to predict:

    no paren = command
       paren = variable

**Comment by lacygoill** [comment]
> Do we really need to be able to write a variable – without parens – at the start of a line?

Ah yes, for assignments:
```vim
vim9script
var name: number
name = 123
```
But maybe Vim could look at what follows the token?  If it's an assignment operator, parse the token as a variable;  otherwise as a command.  Would this be possible?

**Comment by lacygoill** [comment]
> But maybe Vim could look at what follows the token? If it's an assignment operator, parse the token as a variable; otherwise as a command. Would this be possible?

Ah no.  Because some commands can accept an argument starting with something which looks like an assignment operator, but is not one. For example,  `:put`.  Closing the issue then, because I don't think this can be changed.

**Comment by lacygoill** [comment]
> But maybe Vim could look at what follows the token? If it's an assignment operator, parse the token as a variable; otherwise as a command. Would this be possible?

Although, in the original issue, `undo` is followed by nothing:

    silent! undo

It seems useless to parse it as a variable then.  There is no useful side-effect when retrieving the value of a variable.  Maybe Vim could at least handle this special case differently; that is, if:

   - a variable is named like a command,
   - is written at the start of a line (without parens)
   - is not followed by anything

then, parse it as a command.  Would that be possible?  It would have saved me quite some time.

**Comment by lacygoill** [comment]
I re-open because I think the issue can be fixed in many cases, if not most.

What makes me think that, is that Vim already applies some (undocumented?) logic to determine how shadowing works:
```vim
vim9script
setline(1, 'some text')
var silent = 0
@" = ''
silent yank
echo @"
```
Here, notice that `silent` was not shadowed by the `silent` variable; it was correctly parsed as a command.  Parsing it as variable would have made no sense, because a variable must be followed by an operator, and `yank` is not one.

Same thing in the original issue:

    silent! undo

There is nothing after `undo`; thus, it doesn't make sense to parse it as a variable.

One could argue that `undo` could be a variable followed by a method on the next line:

    undo
        ->somefunc()

But that's a corner case which doesn't justify all the other issues it creates.
If for some reason, we really want to write this, then we should put parens:

    (undo)
        ->somefunc()

**Comment by brammool** [comment]
The reason a variable needs to shadow a command is that we can add more commands later.
Suppose someone use the variable "doit" and has a statement "doit = 5".  If we later add a command ":doit" this must not break the existing statement.
That "undo" by itself is not an error but "undo + 1" is, probably something we can fix.

**Comment by lacygoill** [comment]
> The reason a variable needs to shadow a command is that we can add more commands later.
> Suppose someone use the variable "doit" and has a statement "doit = 5". If we later add a command ":doit" this must not break the existing statement.

Yes, I had the exact same thought when I was trying to figure out the purpose behind the current design.

However, I have 2 questions, and 1 suggestion.

**Question 1**

If someone writes `doit` on a line, all by itself, why parsing it as a variable?  It's useless, and can cause very hard to debug issues.

**Question 2**

Correct me if I'm wrong, but there are only 2 cases where a variable can be at the start of a line.

Either the variable is followed by a method (`->`).  Or it's followed by some assignment operator (`=`, `+=`, `*=`, ...).  Right?

If that's the case, it means that we can reliably guess whether the first token is a variable: it should be followed by a non word character like `=`, `-`, `+`, ...  I had a look at the list of all operators at `:help expression-syntax`.  They all start with a non word character.  There are only 2 exceptions: `is` and `isnot`.

So, when Vim finds a token at the start of a line, which could be a variable, *before* parsing it as a variable, could it first check the presence of a non word character right after (plus `is` or `isnot`)?  That would fix so many possible pitfalls...

If it can't be fixed, so be it.  But I think it's very important to make Vim as smart as possible when trying to determine whether the first token on a line is a command or a variable.  Otherwise, it could cause issues which take too much time to be fixed.

**Suggestion**

Functions don't suffer from this issue.  So, moving forward, making sure that a new command has also a function counterpart would help.

---

> That "undo" by itself is not an error

Sorry, I don't understand.  Does it mean that `undo` is really meant to be parsed as a variable, even if not followed by any operator?  Why?

**Comment by brammool** [comment]
I mean "undo" is currently not an error, but it should be.
The thing is that "undo" might be followed by "->someFunc" in the next line. At the point of recognizing the command we don't know.  But after evaluating the expression we do, so that's when we can check for an error.
For now "undo + 1" would still be accepted, even though it's pointless.  It's harder to check for an expression without any side effect.
