### ISSUE TITLE
:command with -complete but without -nargs has inconsistent behaviour

### ISSUE THREAD

**Issue by arp242** [vim/vim#8541]
With the command (note the lack of `-nargs`):

    :comm! -complete=file Test echo

If you use `:Test <Tab>` (or `:Test <C-d>`) then it will complete the file listing for the current directory as expected, but if you type anything, for example:

	:Test e<Tab>

To complete `etc` it will insert just a literal tab, leaving you with `:Test e^I`, as if no completion was defined.

I'd send a patch, but I'm not entire sure what the desired behaviour is:

1. Always have completion work.
2. Never have completion work.
3. Error out on the `:command`.

Personally I'd lean towards the third, but I'm not sure if there's a reason it behaves like it does now, and it may also cause issues with people who have (broken) commands that do work, but will start erroring out after an update (not sure if we need to worry about that though).

Either way, the current way it works is rather confusing; I lost about 20 minutes figuring out why my completion didn't work because I forgot `-nargs=?` 🤦

Vim 8.2.3135; 5b73992d8 – reproducible with `vim --clean`.

**Comment by brammool** [comment]
Yes, it appears to be best that when -complete is given but there are no arguments accepted, an error is given right away.
