### ISSUE TITLE
Vim9: cannot filter list of lists while profiling

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8543]
**Describe the bug**

In Vim9 script, we cannot filter a list of lists while profiling.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            var n = 3
            echo [[1, 2], [3, 4]]->filter((_, l) => l[0] == n)
        enddef
        profile start /tmp/profile.log
        profile func Func
        Func()
    EOF
    )

`E1001` is raised:

    E1001: Variable not found: n

**Expected behavior**

No error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-3134
 - OS: Ubuntu 20.04.2 LTS
 - Terminal: XTerm(353)

**Additional context**

The code works fine if we don't profile:
```vim
vim9script
def Func()
    var n = 3
    echo [[1, 2], [3, 4]]->filter((_, l) => l[0] == n)
enddef
Func()
```
    [[3, 4]]

**Comment by lacygoill** [comment]
Same issue with a nested function:
```vim
vim9script
profile start /tmp/profile.log
profile func *
def Func()
    var x = 0
    def Nested(): any
        return x
    enddef
    Nested()
enddef
Func()
```
    E1001: Variable not found: x

**Comment by lacygoill** [comment]
The patch 8.2.3147 did not fix the issue; the same code still unexpectedly gives an error.

I might be wrong, but I suspect that the test wrongly passes because of this line:

    profile func ProfiledNested

When I tried to find a MWE, I made the same mistake.  I gave the name of the nested function to `:profile`.  That didn't work.  Presumably, because internally, the nested function is implemented as a lambda.  To be sure that I profiled the function, I just used the pattern `*`.  But we could be a little more specific with the pattern `<lambda>*`.  Unfortunately, I think we need a wildcard, because I don't think we can know in advance the number of the lambda.

**Comment by lacygoill** [comment]
> I gave the name of the nested function to :profile. That didn't work.

I meant that I gave the name of the outer function; that didn't work.
I then tried to give the name of the nested function; that didn't work either.

---

BTW, it would have helped to implement nested functions in a way that they retain their original name (to make the debugging process easier).

**Comment by lacygoill** [comment]
> BTW, it would have helped to implement nested functions in a way that they retain their original name (to make the debugging process easier).

Although, not sure how it would have worked.  I guess we would have needed a new scope...

**Comment by brammool** [comment]
When I revert the change in vim9compile.c, the test fails.  Thus it does appear to fix that problem.
But there is another problem when the nested function is profiled, it seems.
