### ISSUE TITLE
cursor in wrong position when removing text property on CursorMoved

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8559]
**Describe the bug**

Removing a text property on `CursorMoved` might cause the cursor to be displayed on the command-line, while in normal mode.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        &lines = 24
        &columns = 80
        &showcmd = true
        &incsearch = true
        (['xxx']->repeat(&lines + 10) + [''] + ['xxx'])->setline(1)
        prop_type_add('name', {highlight: 'ErrorMsg'})
        autocmd CursorMoved * prop_remove({type: 'name'}, line('w0'), line('w$'))
    EOF
    )

Then, press:

   - `V` to select the first line
   - `G` to extend the selection down to the last line
   - `:` to enter the command-line
   - `g/^$/d` to write a global command deleting all the empty lines inside the visual selection
   - `Enter` to execute the global command

The cursor is on the command-line, below the last line of the buffer.

**Expected behavior**

The cursor is above the command-line, on the last line of the buffer.

**Screenshots**

![gif](https://user-images.githubusercontent.com/8505073/125378788-a7348e80-e38f-11eb-8431-aa63e6c526de.gif)

**Environment**

 - Vim version: 8.2 Included patches: 1-3154
 - OS: Ubuntu 20.04.2 LTS
 - Terminal: XTerm(353)

**Additional context**

The issue is hard to reproduce.  For example, it seems that the terminal geometry must be set with particular values, and/or the number of lines in the buffer must have a certain value.  Also, I couldn't get an example where the keypresses were automated with `feedkeys()`.  They need to be pressed interactively.

**Comment by brammool** [comment]
I can fix the problem, but I haven't been able to turn the example into a test that fails.
