### ISSUE TITLE
Cannot import `xxx.vim` in "after/import" directory by using `:import 'xxx.vim'`

### ISSUE THREAD

**Issue by obcat** [vim/vim#8572]
**Describe the bug**

We cannot import a script in an "import" subdirectory of an "after" directory by using this form for the script name:

```help
The script name after `import` can be:
- (omit)
- (omit)
- A path not being relative or absolute.  This will be found in the
  "import" subdirectories of 'runtimepath' entries.  The name will usually be
  longer and unique, to avoid loading the wrong file.
```

https://github.com/vim/vim/blob/c816a2c22667108fcd61f445de2c926f78ff9fa7/runtime/doc/vim9.txt#L1363-L1365

**To Reproduce**

1. Run `vim --clean`.

1. Source this script:

    ```vim
    vim9script
    set runtimepath=/tmp/.vim/after
    delete('/tmp/.vim/after', 'rf')
    mkdir('/tmp/.vim/after/import', 'p')
    var lines =<< trim END
      " foo.vim
      vim9script
      export def Foo()
        echo 'foo'
      enddef
    END
    writefile(lines, '/tmp/.vim/after/import/foo.vim')
    import Foo from 'foo.vim'
    Foo()
    ```

    This error is raised from line 13:

    ```
    E1053: Could not import "foo.vim"
    ```

**Expected behavior**

No error is raised. `foo` is echo'ed.

If this behavior is intended, then maybe it should be mentioned in the help.

**Environment**

 - Vim 8.2.3134
 - macOS Catalina (version 10.15.7)
 - iTerm2

**Comment by brammool** [comment]
The "after" directories are currently intentionally skipped.  Would there be enough use for searching there?  The "after" directory is mainly for adding on top of the distributed scripts, e.g. additional syntax items.  For an import only the first script matters, one cannot add on top of it.  To overrule a distributed script one would need to make it found first, not last.

The help only mentions searching in the "import" directory.  I can add a note that this means "after/import" is not used.

**Comment by obcat** [comment]
> The "after" directories are currently intentionally skipped.

Honestly, I thought so 🙂

> Would there be enough use for searching there? The "after" directory is mainly for adding on top of the distributed scripts, e.g. additional syntax items. For an import only the first script matters, one cannot add on top of it. To overrule a distributed script one would need to make it found first, not last.

Yes, I also don't think it is needed to search the "after" directories. I just happened to find this behavior when I was writing an import-related issue to a plugin.

> The help only mentions searching in the "import" directory. I can add a note that this means "after/import" is not used.

The help says that when [the third form](https://github.com/vim/vim/blob/c816a2c22667108fcd61f445de2c926f78ff9fa7/runtime/doc/vim9.txt#L1363) is used Vim will search in the "import" subdirectories of 'runtimepath' entries. I think this means that if 'runtimepath' contains "/tmp/.vim/after" entry, and "/tmp/.vim/after/import" directory exists, "/tmp/.vim/after/import" will be used. 
Either way, adding a note would be helpful :)

Thank you.

**Comment by obcat** [comment]
A note for this limitation was added to the help via https://github.com/vim/vim/commit/4db572eeb2b42819268e934e76c67163316d873f.

So we can close this issue. Thank you very much.
