### ISSUE TITLE
Vim9: need a way to pass variable to Python

### ISSUE THREAD

**Issue by lilydjwg** [vim/vim#8573]
**Describe the bug**

I'd like to pass a variable to Python in Vim9, but `vim.eval` cannot find it.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. `vim --clean`
2. Source this:
```vim
vim9script

py3 import vim

def s:func(): string
  var a_var = "pass me"
  return py3eval("vim.eval('a_var')")
enddef

s:func()
```
3. Get error
```
Traceback (most recent call last):                                                                                                                                                    
  File "<string>", line 1, in <module>                                                                                                                                                
vim.error: Vim:E121: 未定义的变量: a_var                                                                                                                                              
E858: Eval did not return a valid python object                                                                                                                                       
```

**Expected behavior**
There should be no error

**Environment (please complete the following information):**
 - Vim version 8.2.3159
 - OS: Arch Linux
 - Terminal: GNOME Terminal

**Comment by lacygoill** [comment]
As a workaround, try to declare the variable at the script level:
```vim
vim9script
py3 import vim
var a_var: any
def Func(): string
  a_var = 'pass me'
  return py3eval("vim.eval('a_var')")
enddef
Func()
```
You can still (re)set the variable in the function.

**Comment by lilydjwg** [comment]
Thanks, that works!

**Comment by brammool** [comment]
> As a workaround, try to declare the variable at the script level:
> ```vim
> vim9script
> py3 import vim
> var a_var: any
> def Func(): string
>   a_var = 'pass me'
>   return py3eval("vim.eval('a_var')")
> enddef
> Func()
> ```
> You can still (re)set the variable in the function.

Right, using a script variable is the best way.

You could use a global variable, but then interference with other
scripts is possible.

You can also use a legacy function, if you prefer.  I have been thinking
of having a mechanism in a compiled function to have a dictionary for
local variables, like legacy functions have, which can be accessed by
the Python code (and others mechanisms that can't see the variables on
the stack).  But this goes in the direction of mixing legacy function
properties with compiled functions. It makes the compiled code slower
and adds complexity.  I don't think it's worth it, since using a script
variable is still local to the script, thus the mechanism is contained
inside the script.  And it should only be needed in specific cases.

-- 
If Apple would build a car...
... it would be powered by the sun, be reliable, five times
as fast and twice as easy to drive; but would only run on
five percent of the roads.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lilydjwg** [comment]
We can add another argument to `py3eval` to pass Vim variables to Python, so `vim.eval / bindeval` is not needed in the Python code.

But if you think a script-local variable is enough please close this issue. It's best to have docs about this, but since Vim9 is still under development...

**Comment by puremourning** [comment]
I posted this to vim-dev a while back. Copying here for posterity.


> I don't think it's worth it, since using a script
variable is still local to the script, thus the mechanism is contained
inside the script. And it should only be needed in specific cases.

In big plugins that heavily rely on the python API (such as mine, YouCompleteMe and Vimspector), this will be quite painful. We cross the (legacy) vimscript/python boundary quite frequently and use vim.eval( 'a:argument' ) or vim.eval( 'l:local' ) equivalents a lot.

I would very much like to have the vimscript parts of these plugins eventually migrate to vim9script, but I think without a way to access the values of locals in python code, I can't see that happening.

Here's a handful of examples:

```
$ grep vim.eval vimspector.vim
28:  _vimspector_session._logger.debug( *vim.eval( 'a:000' ) )
51:  py3 _vimspector_session.Start( *vim.eval( 'a:000' ) )
58:  py3 _vimspector_session.Start( launch_variables = vim.eval( 'a:settings' ) )
70:  py3 _vimspector_session.Reset( **vim.eval( 'options' ) )
96:  py3 _vimspector_session.ToggleBreakpoint( vim.eval( 'options' ) )
109:        \ vim.eval( 'a:file_name' ),
110:        \ int( vim.eval( 'a:line_num' ) ),
111:        \ vim.eval( 'options' ) )
119:        \ vim.eval( 'a:file_name' ),
120:        \ int( vim.eval( 'a:line_num' ) ) )
129:        \ vim.eval( "expand( '%' )" ),
130:        \ int( vim.eval( "line( '.' )" ) ) )
143:  py3 _vimspector_session.AddFunctionBreakpoint( vim.eval( 'a:function' ),
144:                                               \ vim.eval( 'options' ) )
205:  py3 _vimspector_session.Stop( **vim.eval( 'options' ) )
222:    py3 _vimspector_session.SetVariableValue( new_value = vim.eval( 'a:1' ) )
270:  py3 _vimspector_session.AddWatch( vim.eval( 'expr' ) )
287:  py3 _vimspector_session.EvaluateConsole( vim.eval( 'a:expr' ), True )
296:  py3 _vimspector_session.EvaluateConsole( vim.eval( 'a:expr' ), False )
304:    py3 _vimspector_session.ShowOutput( vim.eval( 'a:1' ) )
316:        \           int( vim.eval( 'a:win_id' ) ),
317:        \           vim.eval( 'a:category' ) )
362:                      \ . 'vim.eval( "a:ArgLead" ), '
363:                      \ . 'int( vim.eval( "prev_non_keyword_char" ) ) )' ),
393:                   \.'  vim.eval( "line" ), '
394:                   \.'  int( vim.eval( "col" ) ) )' )
488:        \           vim.eval( 'prefix' ),
489:        \           vim.eval( 'a:bang' ) == '!',
490:        \           *vim.eval( 'a:000' ) )
511:        \           vim.eval( 'prefix' ),
512:        \           vim.eval( 'a:bang' ) == '!',
513:        \           *vim.eval( 'a:000' ) )
541:  py3 _vimspector_session.RefreshSigns( vim.eval( 'a:file_name' ) )
548:                      \ . '    int( vim.eval( "winbufnr( winnr() )" ) ) )' )
555:                \ . ' int( vim.eval( "winnr()" ) ), "'

```

Question arises - if you're using vim9script, then why use the python API at all? Well, lots of existing code and testing for one key reason. I'd like to rewrite the vimscript-only parts on vim9script, as these are performance sensitive aspects (like talking to servers using channels, working with UI popups etc.), but I wouldn't want to rewrite the entire codebases.

So if there's a way to support this use case going forwards, it would get my vote. 

Thanks.

**Comment by puremourning** [comment]
PS. I took a look at adding a second argument to `py3eval` as in `py3eval( 'expr', { dict of local variables } )`. This looks (at a quick glance) relatively simple to achieve. Thoughts? Worth me working on it?

**Comment by brammool** [comment]
Ben Jackson wrote:

> PS. I took a look at adding a second argument to `py3eval` as in
> `py3eval( 'expr', { dict of local variables } )`. This looks (at a
> quick glance) relatively simple to achieve. Thoughts? Worth me working
> on it?

You can use bindeval() to get a script-local variable and use it from
Python code:

	vim9script

	var d = {key: 'value'}

	py3 pyd = vim.bindeval('d')
	py3 print(pyd.items())

	d['new'] = 'added'
	py3 print(pyd.items())

	py3 pyd.update({'py': 'thon'})
	echo d

Do you need any more?

-- 
Bad programs can be written in any language.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by puremourning** [comment]
In practice, this looks like this:

```
vim9script

var python_local_args_holder = {}

py3 << EOF
def some_python_function( first, second ):
  print( "First: " + first.decode( "utf-8" ) )
  print( "Second: " + str( second ) )
  return 7
EOF

export def PublicVimscriptFunction( first: string, second: number ): number
  # marshal the arguments into the script-local dict
  python_local_args_holder = { first: first, second: second }
  # pass the arguments to the python function
  return py3eval( 'some_python_function( vim.bindeval( "python_local_args_holder" )[ "first" ], vim.bindeval( "python_local_args_holder" )[ "second" ] )' )
enddef

PublicVimscriptFunction( 'test', 1 )
```

In practice, the `some_python_function` is defined elsewhere of course.

This _works_, sure but the following is syntactically easier to read/write and reason about, and also better performing (fewer bindeval/eval calls):

```
vim9script

py3 << EOF
def some_python_function( first, second ):
  print( "First: " + first.decode( "utf-8" ) )
  print( "Second: " + str( second ) )
  return 7
EOF

export def PublicVimscriptFunction( first: string, second: number ): number
  return py3eval( 'some_python_function( first, second )', {
    'first': first,
    'second': second
  } )
enddef

PublicVimscriptFunction( 'test', 1 )
```

**Comment by puremourning** [comment]
FWIW here's a very rough change that implements it (kind of): https://github.com/vim/vim/pull/10594

I just threw that together - it's not quality, but it shows what I was thinking.
