### ISSUE TITLE
[Doc] A strange criterion for fuzzy search scoring

### ISSUE THREAD

**Issue by obcat** [vim/vim#8577]
This is one of the criteria for fuzzy search scoring written in `:h fuzzy-match`:

```help
    - Matches after a camel case character or a path separator or a hyphen.
```

I think it makes sense that matches after

- a path separator or
- a hyphen

will affect the score, but I wonder if it is true that matches AFTER

- a camel case character

will also affect. (I'm assuming here that "a camel case character" stands for an uppercase letter in a lower-camel-cased word, e.g. "C" in "camalCase".)

So I think this may be some kind of mistake. Perhaps this patch may fix it:

```diff
diff --git a/runtime/doc/pattern.txt b/runtime/doc/pattern.txt
index 962882765..8e2d8a45e 100644
--- a/runtime/doc/pattern.txt
+++ b/runtime/doc/pattern.txt
@@ -1472,7 +1472,8 @@ criteria:
     - The number of characters (distance) between two consecutive matching
       characters.
     - Matches at the beginning of a word
-    - Matches after a camel case character or a path separator or a hyphen.
+    - Matches at a camel case character.
+    - Matches after a path separator or a hyphen.
     - The number of unmatched characters in a string.
 The matching string with the highest score is returned first.
 
```

**Comment by obcat** [comment]
cc @yegappan

**Comment by vim-ml** [comment]
Hi,

On Thu, Jul 15, 2021 at 7:50 PM naohiro ono ***@***.***>
wrote:

> This is one of the criteria for fuzzy search scoring written in :h
> fuzzy-match:
>
>     - Matches after a camel case character or a path separator or a hyphen.
>
> I think it makes sense that matches after
>
>    - a path separator or
>    - a hyphen
>
> will affect the score, but I wonder if it is true that matches AFTER
>
>    - a camel case character
>
> will also affect. (I'm assuming here that "a camel case character" stands
> for an uppercase letter in a lower-camel-cased word, e.g. "C" in
> "camalCase".)
>
> So I think this may be some kind of mistake. Perhaps this patch may fix it:
>
> diff --git a/runtime/doc/pattern.txt b/runtime/doc/pattern.txt
> index 962882765..8e2d8a45e 100644--- a/runtime/doc/pattern.txt+++ b/runtime/doc/pattern.txt@@ -1472,7 +1472,8 @@ criteria:
>      - The number of characters (distance) between two consecutive matching
>        characters.
>      - Matches at the beginning of a word-    - Matches after a camel case character or a path separator or a hyphen.+    - Matches at a camel case character.+    - Matches after a path separator or a hyphen.
>      - The number of unmatched characters in a string.
>  The matching string with the highest score is returned first.
>
>
>
Yes. The description looks good to me. The matches starting with a camel
case character are given an additional score.

Regards,
Yegappan

**Comment by obcat** [comment]
@yegappan Thank you so much for the check. Then we can include this in the next update of runtime files. :)

**Comment by brammool** [comment]
It is more precise, I'll include that change.
