### ISSUE TITLE
`complete_info()['selected'] == -1` doesn't always mean "showing typed text only"

### ISSUE THREAD

**Issue by echasnovski** [vim/vim#8584]
**Describe the bug**
Value `-1` of `complete_info()['selected']` does not always mean "showing typed text only" (as it says in documentation).

**To Reproduce**
1. Create the following configuration file (for example, 'init-completion-selected.vim'):
```vim
au CompleteChanged * echo complete_info(['selected'])

set nocompatible
set shortmess+=c
set noshowmode
```
2. Run `vim -u init-completion-selected.vim`.
3. In insert mode type `aaa<cr>bbb<cr>`
4. Type `<c-n>`. It should echo `{'selected': 0}` and text 'aaa' should be shown.
5. Type `<up>`. It should echo `{'selected': -1}` and text 'aaa' should be still shown. However, user didn't type it.

**Expected behavior**
Either `complete_info()['selected'] == -1` always means "showing typed text only" or documentation is more accurate about this case.

**Screenshots**
Animation of behavior:

![vim_completion-selected](https://user-images.githubusercontent.com/24854248/126062335-5cae9028-7605-40fa-9c84-77b3ebc9cbab.gif)

**Environment (please complete the following information):**
 - Vim version: 8.2.2815
 - OS: Ubuntu 18.04
 - Terminal: GNOME Terminal

**Comment by brammool** [comment]
Right, when using the Up or Down key and it wraps around, no item is selected, the last completion remains.
I'll adjust the help to avoid the confusion.
