### ISSUE TITLE
VIM, windows – document navigation don't work on cyryllic texts in Windows but works in Linux

### ISSUE THREAD

**Issue by VisualCoder123** [vim/vim#8588]
Good morning!

**Describe the bug**

Recently I installed gvim (bug happens in usual vim too) on windows 10 and started vimtutor. My home language is Russian and vimtutor was translated by default.

After entering lesson 2.1 I found out that I can't use dw to delete words. Using this command I can delete 1 or sometimes 2 letters in a word. I can't delete the whole word as vimtutor says.

**To Reproduce**
1. Start Russian vimtutor or type some text using cyrillic letters (for example, "Несколько слов рафинад в этом предложении автокран излишни.").
2. Move the cursor to the beginning the cyrillic word and type dw.

**Expected behavior**
dw should delete the world "Несколько" in the example line above. Instead, it deletes only the letter "Н" (En).

**Environment (please complete the following information):**
 - Vim version 8.2
 - OS: Windows 10  2004.
 - Terminal: CMD and GUI.

**Additional context**
I continued my research and found out that console version of vim in windows 10 has the same problem: I can't edit texts with cyrillic symbols.

Then I loaded my OpenSUSE i3 system and launched vimtutor there (vimtutor in OpenSUSE was also in Russian). Suddenly, all commands worked correctly and I could complete vimtutor (even if it mostly contains cyrillic characters).

I asked about the problem on SA but got no answer: https://stackoverflow.com/questions/68360134/vim-document-navigation-dont-work-on-cyryllic-texts-in-windows-but-works-in-l

**Comment by k-takata** [comment]
> * Vim version 8.2

What is the patch number? Could you try the latest version (at least 8.2.2912 or later)?

**Comment by habamax** [comment]
Check if you have encoding set to utf-8.

**Comment by VisualCoder123** [comment]
> 
> 
> Check if you have encoding set to utf-8.
> 
> "Old" versions of vim for windows didn't use UTF-8 as default encoding and that causes the issue you have. Either download and use most recent vim for windows (https://github.com/vim/vim-win32-installer/releases) or add
> 
> ```
> set encoding=utf-8
> ```
> 
> as a very first line of your vimrc.

Thank you very much for your answer, everything works correctly after editing vimrc!
