### ISSUE TITLE
Buffer opened early on startup isn't fully initialized

### ISSUE THREAD

**Issue by xaizek** [vim/vim#8590]
**Describe the bug**

Executing `:edit` before Vim finished its startup doesn't work as usual.

**To Reproduce**

With a `.vimrc` containing only this:
```vim
syntax on
au BufEnter * edit ~/.vimrc
```

Execute `vim` and observe that syntax highlighting is missing. Running `:edit` fixes it.

**Expected behavior**

Buffer should have `&syntax` set, but instead it's empty.

**Screenshots**

There are some in https://github.com/vifm/vifm.vim/issues/65.

**Environment (please complete the following information):**
 - Vim version: 8.2.2876
 - OS: Slackware 14.2
 - Terminal: xterm

**Additional context**

I suspect running some autocommand might be suspended due to nesting, but I'm not sure, because after startup everything works fine.

**Comment by brammool** [comment]
This is expected: you are not using ++nested.  However, using the * pattern with ++nested is going to get you into trouble, thus you probably want do this this differently.
