### ISSUE TITLE
Vim9: should we enforce a colon before "!" to disambiguate Ex command from logical operator?

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8593]
Consider this snippet:
```vim
vim9script
def Func(): bool
    return true
enddef
!Func()->setline(1)
```
It doesn't give any error.  Just a hit-enter prompt (at least with my shell, zsh).

This might be confusing for the user; they probably expect `false` to be written in the buffer.

The issue is that – in Vim9 – there is ambiguity between `!` the logical operator and `:!` the Ex command, when they are written at the start of a line.

Here's what the help says about ambiguity:

   > In the rare case there is ambiguity between a function name and an Ex command,
   > prepend ":" to make clear you want to use the Ex command.  For example, there
   > is both the `:substitute` command and the `substitute()` function.  When the
   > line starts with `substitute(` this will use the function. Prepend a colon to
   > use the command instead: >
   >         :substitute(pattern (replacement (

Maybe we should enforce the same rule for `!`.  If we really want the Ex command, we should prepend a colon; otherwise, `!` at the start of a line would always be parsed as the NOT logical operator.

**Comment by brammool** [comment]
I think that using !shellCommand is very common, while using !expr->method() is quite rare.
I even think that most users don't see the ambiguity.

If we would require a colon before !shellCommand, and the user uses !shellCommand anyway, we would get an error that shellCommand does not exist.  That might be confusing.

For me, using bash, the example you give does result in an error:  Badly placed (. 
Shell syntax is a mess, thus you might get no error or something weird.

The solution would be to put the expression in (): (!Func())->setline(1)
That's simple enough.

I think this is rare enough to just explain it in the help.

**Comment by lacygoill** [comment]
> I think this is rare enough to just explain it in the help.

Yes, it is a rare corner case.  When Vim did not abort sourcing a script after an error was encountered, I sometimes had very confusing errors because of this.  Now that Vim aborts, I guess those errors are gone.

In practice, I don't like the ambiguity between `!` the logical operator and `:!` the Ex command.  I'm not sure how to correctly distinguish the latter for syntax highlighting, so I don't highlight it.  I do support `:!` when used as a filter command, because then it's easy: there must be a range before.

In any case, I prefer `:terminal` over `:!`.  It makes the code more readable, and provides a buffer which can be searched, contrary to `:!`'s pager.
