### ISSUE TITLE
Popup menu closed unexpectedly in GVim

### ISSUE THREAD

**Issue by zoumi** [vim/vim#8595]
_Instructions: 
Popup menu closed unexpectedly.

**Describe the bug**
The detail is at here:
https://github.com/prabirshrestha/asyncomplete-lsp.vim/issues/38
It's more like a bug of gvim. I have test it with coc.vim, the problem is the same.
Or it just because my OS's settings?

**To Reproduce**
1.Start gvim with a minimal setting file
2,Press something to trigger an LSP autocomplete

**Expected behavior**
When the popup menu is shown, I should be able to select between items with arrow keys.

**Screenshots**
![popup2](https://user-images.githubusercontent.com/5162901/126178316-52c00765-977c-4804-acfc-42b1fabb7332.gif)

**Environment (please complete the following information):**
 - Vim version:
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul 18 2021 22:02:48)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-3182
Compiled by appveyor@APPVYR-WIN
Huge version with GUI.  Features included (+) or not (-):
```
 - OS: Windows10 Home 64bit

**Comment by zoumi** [comment]
1,This only happen when the item has an balloon tip.
2,The problem is gone after I changing the screen resolution.

**Comment by brammool** [comment]
Is the problem really dependent on the screen resolution, or the size of the Vim window (check the 'lines' and 'columns' values)

**Comment by zoumi** [comment]
I entered Windows 'safe mode' yesterday. And I was amazing that gvim works well in 'safe mode'.
So I change screen resolution,and find out that the problem is gone.
But I can't reproduce this with changing back the screen resolution.
I will re-open this issue if it happens again. 
Thank you!

**Comment by zoumi** [comment]
I get it again.
lines=37
columns=146

This time it happens when I maximize the gvim's window, and disappears when the window exit maximize state.

**Comment by zoumi** [comment]
But it doesn't reproduce when I maximize the gvim window again.

**Comment by zoumi** [comment]
@brammool Any tip for debugging this？How can I know why the popup is closed？

**Comment by chrisbra** [comment]
I am not sure, maybe you can use `:call ch_logfile('vim_logfile.log', 'w')` to see what is happeneing and received

**Comment by zoumi** [comment]
@chrisbra Here is the log data:

```
 17.814481 : looking for messages on channels
 21.839784 SEND on 0(in): '[0,["CocAutocmd",["MenuPopupChanged",{"col":42,"row":13,"scrollbar":false,"completed_item":{"word":"Record","menu":"[T]","user_data":"{\"cid\":1631585935,\"source\":\"tag\",\"index\":1580}","info":"D:/my_notexxxx.rs","kind":"","abbr":"Record"},"width":23,"height":4,"size":4},12]]]
'
 21.839991 : looking for messages on channels
 21.888098 RECV on 0(out): '["call","coc#api#call",["call_function",["coc#float#create_pum_float",[0,0,["D:/my_xxxx.rs","D:/my_xxx.rs","D:/my_xxxxx.rs"],{"codes":[{"filetype":"rust","startLine":0,"endLine":4}],"highlights":[],"maxWidth":80,"pumbounding":{"col":42,"row":13,"height":4,"width":23,"scrollbar":false}}]]],-98]
'
 21.888186 on 0: Calling 'coc#api#call'
 21.912794 SEND on 0(in): '[-98,[null,[1003,4]]]
'
 21.935270 RECV on 0(out): '["call","coc#api#notify",["command",["redraw"]]]
'
 21.935306 : looking for messages on channels
 21.935373 on 0: Calling 'coc#api#notify'
 21.935623 : looking for messages on channels
 22.334978 SEND on 0(in): '[0,["CocAutocmd",["CompleteDone",{}]]]
'
 22.345729 SEND on 0(in): '[0,["CocAutocmd",["CursorMovedI",1,[146,38]]]]
'
 22.346350 SEND on 0(in): '[0,["CocAutocmd",["TextChangedI",1,{"lnum":146,"col":38,"changedtick":46,"pre":"fn get_ocv(start_index,rs:&Vec<record"}]]]
'
 22.346566 : SafeState: Start triggering
 22.350169 RECV on 0(out): '["call","coc#api#notify",["call_function",["coc#float#close",[1003]]]]
["call","coc#api#notify",["command",["redraw"]]]
["call","coc#api#notify",["call_atomic",[[["nvim_command",["noa set completeopt=menuone,noselect,popup"]],["nvim_command",["let g:coc#_context = {'start': 0, 'preselect': -1,'candidates': []}"]]]]]]
'
 22.350179 : looking for messages on channels
 22.350198 on 0: Calling 'coc#api#notify'
 22.350514 SEND on 0(in): '[0,["CocAutocmd",["BufWinLeave",4,-1]]]
'
```
What did I do:
1,Open a rust file
2,Type "record" (because there is a rust struct Record, so coc.nvim will trigger an autocomplete.)
3,When the popup is shown, the "Record" item is the last one item in popup menu. So,I press <Shirft-Tab> try to select the last one item.
4,But when "Record" became the highlighted one, a float windows is flashing(this float windows describe the detail of "Record"), and the popup menu is close unexpectedly.

Sorry for my poor English.

**Comment by chrisbra** [comment]
I would guess, this is a problem with the coc vim plugin. I see a couple of autocommands that get triggered like `TextChangedI`, `CursorMovedI` and `BufWinLeave`. Not sure why those would be triggered.

**Comment by zoumi** [comment]
@chrisbra The bug is initially found with prabirshrestha/asyncomplete-lsp.vim.
Both they has the same bug?

**Comment by chrisbra** [comment]
It's hard to tell. You did not provide much details on how to reproduce it.

**Comment by zoumi** [comment]
Sorry,CursorMovedI and BufWinLeave is triggered because I close the gvim.

**Comment by zoumi** [comment]
I'll record ch_log with asyncomplete-lsp.vim later.
And the source of the problem is the float window.
It will be OK if I set the coc's config   ```"suggest.floatEnable": false``` to disable the float window.
