### ISSUE TITLE
visual remap <Esc> changes behaviour of <Right> and cannot be undone

### ISSUE THREAD

**Issue by EdwardGallant** [vim/vim#8596]
**Describe the bug**
visual remap of `<Esc>` changes the behaviour of `<Right>` and cannot be undone

(in fact, the same bug is present with `nno`)

**To Reproduce**
Start with `vim --clean`
source a file with the following content
```
vno <Esc> :<C-u>echo "anything"<CR>
```
type the command `v<Right>` on a line of text
above that line you are in insert mode with a capital C already inserted

type the command `vno <Right> <Right>`
observe no change in bug; `verbose vno <Right> <Right>` makes it appear like it succeeded (no mapping found, eg default)

type the command `vno <Esc> <Esc>`
still no change in bug

**Expected behavior**
It should not affect the behaviour of `<Right>`

**Screenshots**
If applicable, copy/paste the text or add screenshots to help explain your problem.
<img width="388" alt="Screen Shot 2021-07-20 at 10 13 00 AM" src="https://user-images.githubusercontent.com/64599516/126339313-f64e03d8-eaed-4f1e-b89e-4681e652f04e.png">
<img width="332" alt="Screen Shot 2021-07-20 at 10 13 10 AM" src="https://user-images.githubusercontent.com/64599516/126339260-8eae1f52-4345-48e0-86a2-b4d104be0480.png">

**Environment (please complete the following information):**
Using iterm2
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 17 2021 15:59:19)
macOS version - x86_64
Included patches: 1-2775
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
-autoservername    +folding           +multi_byte        +termguicolors
-balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
-browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              +perl              +title
-clientserver      +job               +persistent_undo   -toolbar
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           -python            +visual
+conceal           +linebreak         +python3           +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua               +ruby              +wildmenu
+dialog_con        +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
-dnd               +mouse             -sound             -xfontset
-ebcdic            -mouseshape        +spell             -xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              -mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DMACOS_X -DMACOS_X_DARWIN -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -o vim -lm -lncurses -liconv -lintl -framework AppKit -L/usr/local/opt/lua/lib -llua5.4 -mmacosx-version-min=11.2 -fstack-protector-strong -L/usr/local/lib -L/usr/local/Cellar/perl/5.32.1_1/lib/perl5/5.32.1/darwin-thread-multi-2level/CORE -lperl -L/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/config-3.9-darwin -lpython3.9 -framework CoreFoundation -lruby.3.0 -L/usr/local/Cellar/ruby/3.0.1/lib
```

**Additional context**
This was a bit frustrating to track down, since the mappings seem totally unrelated and cause bugs far down the line.

I'm suspicious it has something to do with overlapping keycodes, but I don't really understand. Without the visual remap of `<Esc>` of course <Right> works fine and can be changed to whatever I like.

It's somewhat of an edge case, but it came up while working with a project I use to create new modes (apart from insert, visual etc) when I need <Esc> to do something special to unmap my mode's mappings first.

The following can reproduce the same bug, basically as above.

```
nno <Esc> :echo "anything"<CR>
```

**Comment by lacygoill** [comment]
Mapping `<Esc>` is known to cause many issues.  See [here](https://github.com/lacygoill/wiki/blob/master/vim/mapping.md#why-should-i-avoid-a-mapping-with-an-esc-in-its-lhs).

**Comment by EdwardGallant** [comment]
Okay, I will close this. I came across this with terminal-mode, but I didn't think it would affect normal vim modes. That seems to be a limitation of escaping in vim.

**Comment by lacygoill** [comment]
> That seems to be a limitation of escaping in vim.

Maybe, but I suspect that – even with a lot of work – there would be still corner cases where it wouldn't work.

> imo though vim should at least warn if not throw when we try to do this.

I agree.  But it could bring us many complaints from users of plugins which remap `<Esc>`.  Although, that didn't stop a PR with a similar purpose ( https://github.com/vim/vim/pull/8544 ) from being merged.  So, why not.

**Comment by EdwardGallant** [comment]
If a plugin remaps `<Esc>` and breaks `<Right>` for me without me realising it quickly, I'm probably very unhappy anyway 🤔

I agree that stability is very important. One way that could be addressed is something like `verbose source %` or `strict source %` so the user can say they explicitly want to be informed when something is break. A similar prefix to `packadd` would be nice. But this is turning into a vim9 feature request :p and I think vim9 already has some better strictness, so I will wait and see.

**Comment by lacygoill** [comment]
> One way that could be addressed is something like verbose source % or strict source % so the user can say they explicitly want to be informed when something is likely a bug.

Another way would be a custom `:CheckHealth` command (similar to the one in Neovim), which would check whether the user has some setting which is known to cause issues.  Among other things, it would:

   - warn against mapping `<Esc>`
   - make sure that the `*timeout*` options are set with sensible values (that might prevent issues such as https://github.com/vim/vim/issues/8082 )
   - check that $TERM is set with a correct value when Vim is run inside tmux

This could be provided as an optional package (like termdebug), or a default plugin (like TOhtml).
