### ISSUE TITLE
strftime("%z") not working correctly

### ISSUE THREAD

**Issue by 3e4** [vim/vim#860]
I am running vim 4.7.1913 on Windows 7, and using Python 3.5 as default python interpreter.

%z and %Z yield the same result in the strftime() statement.

`:echo strftime("%z __ %Z")`
`W. Europe Daylight Time __ W. Europe Daylight Time`

This is a wrong behavior based on [Man page of strftime](http://man7.org/linux/man-pages/man3/strftime.3.html). This [issue](https://github.com/itchyny/calendar.vim/issues/86) might be related but only a workaround for calendar.vim was discussed.

**Comment by jamessan** [comment]
The man page isn't relevant for Windows.

%z isn't a standard strftime format code.  The `(SU)` at the end of the description indicates that it is an extension from the initial specification introduced by the Single Unix Specification.

Microsoft treats %z and %Z the [same](https://msdn.microsoft.com/en-us/library/fe06s4ak.aspx).

**Comment by 3e4** [comment]
Thank you for this clarification. I was not sure it's implemented in Windows or in vim itself. Guess I'll have to live with it.
