### ISSUE TITLE
Vim9: inconsistent error message when using method to pass too many arguments to lambda

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8604]
**Describe the bug**

In Vim9 script, using a method to pass too many arguments to a lambda gives an inconsistent error message.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            echo ((a) => a)('bb', 'cc')
        enddef
        defcompile
    EOF
    )

`E118` is raised with this message:

    E118: Too many arguments for function: ((a) => a)('bb', 'cc')

Now, run this other shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            echo 'bb'->((a) => a)('cc')
        enddef
        defcompile
    EOF
    )

`E118` is raised with this message:

    E118: Too many arguments for function: [expression]

**Expected behavior**

The second message prints the lambda expression as it was called, and without the generic "[expression]" placeholder, just like in the first message.  Because the 2 commands run the exact same code.  The only difference is that – in the second one – we pass one argument via a method.  It is unexpected for that to matter when an error message is given.  Besides, the second message seems more useful, because it gives us more information.

**Environment**

 - Vim version: 8.2 Included patches: 1-3189
 - OS: Ubuntu 20.04.2 LTS
 - Terminal: XTerm(353)

**Additional context**

A similar issue was fixed in 8.2.1915.

**Comment by lacygoill** [comment]
Not sure if it could be made to work, but Vim doesn't print the body of the lambda at the script level:
```vim
vim9script
echo ((a) => a)('bb', 'cc')
```
    E118: Too many arguments for function: <lambda>1

But it does in compiled code:
```vim
vim9script
def Func()
    echo ((a) => a)('bb', 'cc')
enddef
defcompile
```
    E118: Too many arguments for function: ((a) => a)('bb', 'cc')

IMO, the second message is more useful, because we can't use `:def <lambda>1` to retrieve the definition.

**Comment by brammool** [comment]
In compiled code we do not actually do the call, we still have the expression from before the "(".
At the script level it does all the work for actually calling the function, the expression before the "(" is not passed down to the code that implements that.  Changing that is quite difficult.
