### ISSUE TITLE
vim9: The vim9 readme should make a comparison to LuaJIT instead of Lua

### ISSUE THREAD

**Issue by shaunsingh** [vim/vim#8606]
I was messing around with Vim9 this morning, and was wondering how fast it was compared to the competing LuaJIT that neovim uses. The first test case for Vim9

```vim
vim9script

let start = reltime()

def VimNew(): number
  let sum = 0
  for i in range(1, 2999999)
    sum = sum + i
  endfor

  return sum
enddef

echo VimNew()
echo reltimestr(reltime(start))

" Result:
" 4499998500000
" 0.082964
```
Gave the following result. The equivalent code in Lua

```lua
local start = vim.fn['reltime']()
local function VimNew()
  local sum = 0
  for i = 1, 2999999, 1 do
    sum = sum + i
  end
  return sum
end
vim.cmd(string.format([[%s %s]], 'echo', VimNew()))
vim.cmd(string.format([[%s %s]], 'echo', vim.fn['reltimestr'](vim.fn['reltime'](start))))

--4499998500000
-- 0.002857
```

Since the result for lua looks much quicker in comparison to vim9 than the one in the vim9 README, I assume the example testing uses lua instead of luaJIT. Considering neovim is using LuaJIT instead of lua (and therefore is what Vim9 is being compared to), shouldn't LuaJIT performance be included?

There is a small message towards the bottom that mentions LuaJIT performance, but it makes sense to include it for both benchmarks. 

**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
The feature request would just involve a few more benchmarks, shouldn't be very hard to accomplish

**Describe the solution you'd like**
The benchmarks in the vim9 readme should either 
1. Change the lua benchmarks to LuaJIT benchmarks 
2. Add LuaJIT benchmarks in addition to lua ones

**Comment by dpelle** [comment]
I built vim-8.2.32197 with and without luajit on xubuntu-18.04.5
and ran the VIM9 benchmarks (sum and indent from README_VIM9.md).
In both cases, I built with `clang-12 -O2` on a `i7-7700T CPU @ 2.90GHz`.

I built with luajit as follows:
```
$ sudo apt-get install luajit
$ vim vim
$ CC=clang-12 ./configure --with-features=huge --enable-gui=none --enable-python3interp=yes --enable-pythoninterp=yes --enable-perlinterp=yes --enable-tclinterp=yes --enable-rubyinterp=yes --enable-luainterp=yes  --with-luajit --enable-fail-if-missing
$ make -j8
$ sudo make install
```

```
:version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul 22 2021 06:56:34)
Included patches: 1-3197
Compiled by pel@pel-cirrus7
Huge version without GUI.  Features included (+) or not (-):
+acl               -dnd               +listcmds          +postscript        +termresponse
+arabic            -ebcdic            +localmap          +printer           +textobjects
+autocmd           +emacs_tags        +lua               +profile           +textprop
+autochdir         +eval              +menu              +python/dyn        +timers
-autoservername    +ex_extra          +mksession         +python3/dyn       +title
-balloon_eval      +extra_search      +modify_fname      +quickfix          -toolbar
+balloon_eval_term -farsi             +mouse             +reltime           +user_commands
-browse            +file_in_path      -mouseshape        +rightleft         +vartabs
++builtin_terms    +find_in_path      +mouse_dec         +ruby              +vertsplit
+byte_offset       +float             +mouse_gpm         +scrollbind        +virtualedit
+channel           +folding           -mouse_jsbterm     +signs             +visual
+cindent           -footer            +mouse_netterm     +smartindent       +visualextra
+clientserver      +fork()            +mouse_sgr         +sodium            +viminfo
+clipboard         +gettext           -mouse_sysmouse    +sound             +vreplace
+cmdline_compl     -hangul_input      +mouse_urxvt       +spell             +wildignore
+cmdline_hist      +iconv             +mouse_xterm       +startuptime       +wildmenu
+cmdline_info      +insert_expand     +multi_byte        +statusline        +windows
+comments          +ipv6              +multi_lang        -sun_workshop      +writebackup
+conceal           +job               -mzscheme          +syntax            +X11
+cryptv            +jumplist          +netbeans_intg     +tag_binary        +xfontset
+cscope            +keymap            +num64             -tag_old_static    -xim
+cursorbind        +lambda            +packages          -tag_any_white     -xpm
+cursorshape       +langmap           +path_extra        +tcl               +xsmp_interact
+dialog_con        +libcall           +perl              +termguicolors     +xterm_clipboard
+diff              +linebreak         +persistent_undo   +terminal          -xterm_save
+digraphs          +lispindent        +popupwin          +terminfo
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang-12 -c -I. -Iproto -DHAVE_CONFIG_H -g -O2 -Wall -Wextra -Wshadow -Wmissing-prototypes
-Wpedantic -Wunreachable-code -Wunused-result -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang-12 -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-
export-dynamic -Wl,-E -L/usr/local/lib -Wl,--as-needed -o vim -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -
lICE -lm -ltinfo -lselinux -lcanberra -lsodium -lacl -lattr -lgpm -ldl -L/usr/lib/x86_64-linux-gnu -llua
jit-5.1 -Wl,-E -fstack-protector-strong -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu/perl/5.26/CORE -lpe
rl -ldl -lm -lpthread -lcrypt -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm -lruby-2.5 -lp
thread -lgmp -ldl -lcrypt -lm -L/usr/lib
```

```
:lua print(_VERSION)
Lua 5.1

:lua print(jit.version)
LuaJIT 2.1.0-beta3
```


I built without luajit as follows:
```
$ CC=clang-12 ./configure --with-features=huge --enable-gui=none --enable-python3interp=yes --enable-pythoninterp=yes --enable-perlinterp=yes --enable-tclinterp=yes --enable-rubyinterp=yes --enable-luainterp=yes  --enable-fail-if-missing
$ make -j8
$ sudo make install
```

```
:version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul 22 2021 07:03:09)
Included patches: 1-3197
Compiled by pel@pel-cirrus7
Huge version without GUI.  Features included (+) or not (-):
+acl               -dnd               +listcmds          +postscript        +termresponse
+arabic            -ebcdic            +localmap          +printer           +textobjects
+autocmd           +emacs_tags        +lua               +profile           +textprop
+autochdir         +eval              +menu              +python/dyn        +timers
-autoservername    +ex_extra          +mksession         +python3/dyn       +title
-balloon_eval      +extra_search      +modify_fname      +quickfix          -toolbar
+balloon_eval_term -farsi             +mouse             +reltime           +user_commands
-browse            +file_in_path      -mouseshape        +rightleft         +vartabs
++builtin_terms    +find_in_path      +mouse_dec         +ruby              +vertsplit
+byte_offset       +float             +mouse_gpm         +scrollbind        +virtualedit
+channel           +folding           -mouse_jsbterm     +signs             +visual
+cindent           -footer            +mouse_netterm     +smartindent       +visualextra
+clientserver      +fork()            +mouse_sgr         +sodium            +viminfo
+clipboard         +gettext           -mouse_sysmouse    +sound             +vreplace
+cmdline_compl     -hangul_input      +mouse_urxvt       +spell             +wildignore
+cmdline_hist      +iconv             +mouse_xterm       +startuptime       +wildmenu
+cmdline_info      +insert_expand     +multi_byte        +statusline        +windows
+comments          +ipv6              +multi_lang        -sun_workshop      +writebackup
+conceal           +job               -mzscheme          +syntax            +X11
+cryptv            +jumplist          +netbeans_intg     +tag_binary        +xfontset
+cscope            +keymap            +num64             -tag_old_static    -xim
+cursorbind        +lambda            +packages          -tag_any_white     -xpm
+cursorshape       +langmap           +path_extra        +tcl               +xsmp_interact
+dialog_con        +libcall           +perl              +termguicolors     +xterm_clipboard
+diff              +linebreak         +persistent_undo   +terminal          -xterm_save
+digraphs          +lispindent        +popupwin          +terminfo
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang-12 -c -I. -Iproto -DHAVE_CONFIG_H -g -O2 -Wall -Wextra -Wshadow -Wmissing-prototypes
-Wpedantic -Wunreachable-code -Wunused-result -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang-12 -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-
export-dynamic -Wl,-E -L/usr/local/lib -Wl,--as-needed -o vim -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -
lICE -lm -ltinfo -lselinux -lcanberra -lsodium -lacl -lattr -lgpm -ldl -L/usr/lib -llua5.2 -Wl,-E -fstac
k-protector-strong -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu/perl/5.26/CORE -lperl -ldl -lm -lpthread
 -lcrypt -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm -lruby-2.5 -lpthread -lgmp -ldl -lc
rypt -lm -L/usr/lib
```

```
:lua print(_VERSION)
Lua 5.2

:lua print(jit.version)
[string "vim chunk"]:1: attempt to index global 'jit' (a nil value)

```
Result of the sum benchmarks in README_VIM9.md:

```
WITH LUAJIT                    WITHOUT LUAJIT
-------------------            -------------------
4499998500000                  4499998500000
Vim old:   6.008484            Vim old:   6.035722
4499998500000                  4499998500000
Python:   0.370065             Python:   0.364257
4499998500000                  4499998500000
Lua:   0.004245                Lua:   0.098556
4499998500000                  4499998500000
Vim new:   0.137208            Vim new:   0.131980
```

Result of the indent benchmarks in README_VIM9.md:
```
WITH LUAJIT                    WITHOUT LUAJIT
-------------------            -------------------
888890                         888890
Vim old:   0.597904            Vim old:   0.578598
888890                         888890
Python:   0.157938             Python:   0.152040
888890                         888890
Lua:   0.128400                Lua:   0.164917
888890                         888890
Vim new:   0.079692            Vim new:   0.080802
```

So:
- vim9 is 32.3 times slower than luajit and 1.33 times slower than lua on sum benchmark
- vim9 is 1.61 times faster than luajit and 2.04 times faster than lua on indent benchmark

Notice that lua version was different with jit (lua-5.1) and without jit (lua-5.2) somehow
which perhaps has an impact on speed besides the jit difference.

It would indeed to be be better if README_VIM9.md indicates benchmarks with and without luajit.  

luajit is faster than lua, but is there any drawbacks of using luajit?

**Comment by jamessan** [comment]
> luajit is faster than lua, but is there any drawbacks of using luajit?

LuaJIT requires architecture-specific work to implement the JIT, so it's not available everywhere. On those systems where it isn't available, you have to fallback to Lua.

LuaJIT also specifically targets the Lua 5.1 API and, more importantly, ABI.

**Comment by brammool** [comment]
Dominique wrote:

> I built vim-8.2.32197 with and without luajit on xubuntu-18.04.5
> and ran the VIM9 benchmarks (sum and indent from README_VIM9.md).
> In both cases, I built with `clang-12 -O2` on a `i7-7700T CPU @ 2.90GHz`.

[...]

Thanks for doing this.  I'll include the LuaJit numbers and add some
remarks.  Looks like LuaJit got a lot better since when I tried.

The compilation options matter a lot.  I normally build without
optimization, because debugging works better.  But it's also two or
three times slower.

> Result of the sum benchmarks in README_VIM9.md:
> 
> ```
> WITH LUAJIT                    WITHOUT LUAJIT
> -------------------            -------------------
> 4499998500000                  4499998500000
> Vim old:   6.008484            Vim old:   6.035722
> 4499998500000                  4499998500000
> Python:   0.370065             Python:   0.364257
> 4499998500000                  4499998500000
> Lua:   0.004245                Lua:   0.098556
> 4499998500000                  4499998500000
> Vim new:   0.137208            Vim new:   0.131980
> ```
> 
> Result of the indent benchmarks in README_VIM9.md:
> ```
> WITH LUAJIT                    WITHOUT LUAJIT
> -------------------            -------------------
> 888890                         888890
> Vim old:   0.597904            Vim old:   0.578598
> 888890                         888890
> Python:   0.157938             Python:   0.152040
> 888890                         888890
> Lua:   0.128400                Lua:   0.164917
> 888890                         888890
> Vim new:   0.079692            Vim new:   0.080802
> ```
> 
> So:
> - vim9 is 32.3 times slower than luajit and 1.33 times slower than lua
>   on sum benchmark
> - vim9 is 1.61 times faster than luajit and 2.04 times faster than lua
>   on indent benchmark

It appears Vim9 has become a bit slower, most likely because of the
interrupt and exception handling, which is done between every
instruction.  Also, the switch on the instruction enum has grown to
become huge, there must be ways to do this better.

I haven't done profiling lately, it's really the only way to figure out
how to improve performance.  As an example, I tried removing the checks
for interrupt from the loop and that made it more than 10% faster.  I
then figured out that (for my compiler) making the break check counter
static helped quite a bit.

I would appreciate it if someone can try a few things and see what makes
the exec_instructions() function faster.  Using a good profiler would
help a lot.


-- 
hundred-and-one symptoms of being an internet addict:
202. You're amazed to find out Spam is a food.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
