### ISSUE TITLE
vim9: error message if map() returns a different type is unclear

### ISSUE THREAD

**Issue by arp242** [vim/vim#8608]
Long story short, when converting my vimrc to Vim9 I spent a long time figuring out why this:

    synstack(line('.'), col('.'))->map((_, id) => synIDattr(id, 'name'))

Outputs:

    E1012: Type mismatch; expected number but got string
    [124]

Eventually I figured out that it's (trying to) change the type of the list item as map() operates in-place. The solution is simple: replace map() with mapnew().

The error message on this could be improved a lot IMHO; perhaps something like:

    E1012: Type mismatch: map function operated on number but returned string.

And I would imagine the same applies to other functions that modify a list in-place from a function such as filter().

Vim 8.2.3197

**Comment by lacygoill** [comment]
[I agree](https://github.com/lacygoill/wiki/blob/master/bug/vim.md#-33), the current error message does not give us enough information.

It's even worse in this example:
```vim
vim9script
setline(1, '()')
searchpairpos('(', '', ')', 'nW', '[0]->map(''synIDattr(v:val, "name")'')->filter(''v:val =~? "string\\|character\\|singlequote\\|escape\\|symbol\\|comment"'')->empty()')
```
    E1012: Type mismatch; expected number but got string
    E1072: Cannot compare number with string

Who is complaining?  `searchpairpos()`?  `map()`?  `filter()`?

It turns out that it's `map()`, but it's not obvious.

**Comment by brammool** [comment]
> [I agree](https://github.com/lacygoill/wiki/blob/master/bug/vim.md#-33), the current error message does not give us enough information.
> 
> It's even worse in this example:
> ```vim
> vim9script
> setline(1, '()')
> searchpairpos('(', '', ')', 'nW', '[0]->map(''synIDattr(v:val, "name")'')->filter(''v:val =~? "string\\|character\\|singlequote\\|escape\\|symbol\\|comment"'')->empty()')
> ```
>     E1012: Type mismatch; expected number but got string
>     E1072: Cannot compare number with string
> 
> Who is complaining?  `searchpairpos()`?  `map()`?  `filter()`?
> 
> It turns out that it's `map()`, but it's not obvious.

It's hard to pass down the location down to where the error happens.
There are a few places where it can be done, that might help a bit.

-- 
$ echo pizza > /dev/oven

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> It's hard to pass down the location down to where the error happens.

In addition to the newly added location:

    E1012: Type mismatch; expected number but got string in map()
                                                         ^------^

We might want to clearly state that the error comes from a disallowed mutation.  I mean, I understand the current message, but I think it can be confusing to a new user.  They might still ask themselves:

   - Where was a number expected?  In the arguments?  In the return value?
   - Why is a number expected in the first place?  The code worked fine in legacy.

That's why I think that the message originally suggested by @arp242 is still better than the current one:

    E1012: Type mismatch: map function operated on number but returned string

The improvement would be only needed for functions which have a `*new()` counterpart.  That is `extend()`, `flatten()`, and `map()`.

**Comment by arp242** [comment]
Yeah, that it was the `map()` function and not one of the others was just part of the confusion: mutating the list entries was the other part – about 50/50.

It's confusing because the anonymous functions are generic (i.e. no type parameters), and because the in-place operation may be surprising (even though I already knew this, connecting all the parts still took some time and a lot of `:vim9cmd echo [..]` experimentation, partly just because I'm used to VimScript's more dynamic typing).

**Comment by lacygoill** [comment]
In fact, there is no reason not to suggest mapnew() right in the error message:

    E1012: Type mismatch: map() operated on number but returned string; use mapnew()
                                                                        ^----------^

This way, no need to look in the help for the solution.
