### ISSUE TITLE
Vim9: example about closures sharing same context does not work

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8614]
In `:help vim9`, under the section titled "Limitations", we can read this:

> Closures defined in a loop will share the same context.  For example: >
> 	var flist: list<func>
> 	for i in range(10)
> 	  var inloop = i
> 	  flist[i] = () => inloop
> 	endfor

> The "inloop" variable will exist only once, all closures put in the list refer
> to the same instance, which in the end will have the value 9.  This is
> efficient.  If you do want a separate context for each closure call a function
> to define it: >
> 	def GetFunc(i: number): func
> 	  var inloop = i
> 	  return () => inloop
> 	enddef

> 	var flist: list<func>
> 	for i in range(10)
> 	  flist[i] = GetFunc(i)
> 	endfor

The first snippet does not work:
```vim
vim9script
var flist: list<func>
for i in range(10)
    var inloop = i
    flist[i] = () => inloop
endfor
```
    E1001: Variable not found: inloop

But it does work when run from a function:
```vim
vim9script
def Func()
    var flist: list<func>
    for i in range(10)
        var inloop = i
        flist[i] = () => inloop
    endfor
    echo range(10)->map((i, _) => flist[i]())
enddef
Func()
```
    [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]

The first error looks a bit unexpected.  Is it working as intended?

If not, the issue might come from `inloop` which is local to a block in a script.
If it is working as intended, the first snippet might need an update:
```diff
diff --git a/runtime/doc/vim9.txt b/runtime/doc/vim9.txt
index a0681d287..63eed722d 100644
--- a/runtime/doc/vim9.txt
+++ b/runtime/doc/vim9.txt
@@ -1046,11 +1046,13 @@ For these the backtick expansion can be used.  Example: >
 	enddef
 
 Closures defined in a loop will share the same context.  For example: >
-	var flist: list<func>
-	for i in range(10)
-	  var inloop = i
-	  flist[i] = () => inloop
-	endfor
+	def Loop()
+	  var flist: list<func>
+	  for i in range(10)
+	    var inloop = i
+	    flist[i] = () => inloop
+	  endfor
+	enddef
 
 The "inloop" variable will exist only once, all closures put in the list refer
 to the same instance, which in the end will have the value 9.  This is
@@ -1061,10 +1063,12 @@ to define it: >
 	  return () => inloop
 	enddef
 
-	var flist: list<func>
-	for i in range(10)
-	  flist[i] = GetFunc(i)
-	endfor
+	def Loop()
+	  var flist: list<func>
+	  for i in range(10)
+	    flist[i] = GetFunc(i)
+	  endfor
+	enddef
 
 ==============================================================================
 
```
In the second snippet, the code doesn't need to be run from the `Loop()` function; only in the first one.  But omitting `Loop()` would make the snippets asymmetrical, and look a bit confusing.

**Comment by lacygoill** [comment]
Also, the current snippets don't give any output which makes it more difficult for the reader to understand what is happening.  Updated diff which makes the code give some useful output:
```diff
diff --git a/runtime/doc/vim9.txt b/runtime/doc/vim9.txt
index a0681d287..d2413d907 100644
--- a/runtime/doc/vim9.txt
+++ b/runtime/doc/vim9.txt
@@ -1046,13 +1046,20 @@ For these the backtick expansion can be used.  Example: >
 	enddef
 
 Closures defined in a loop will share the same context.  For example: >
-	var flist: list<func>
-	for i in range(10)
-	  var inloop = i
-	  flist[i] = () => inloop
-	endfor
+	def Loop()
+	  var flist: list<func>
+	  for i in range(10)
+	    var inloop = i
+	    flist[i] = () => inloop
+	  endfor
+	  echo flist->len()->range()->map((i, _) => flist[i]())
+	enddef
+	Loop()
 
-The "inloop" variable will exist only once, all closures put in the list refer
+Outputs: >
+	[9, 9, 9, 9, 9, 9, 9, 9, 9, 9]
+
+The "inloop" variable will exist only once, all closures put in the list refer
 to the same instance, which in the end will have the value 9.  This is
 efficient.  If you do want a separate context for each closure call a function
 to define it: >
@@ -1061,10 +1068,17 @@ to define it: >
 	  return () => inloop
 	enddef
 
-	var flist: list<func>
-	for i in range(10)
-	  flist[i] = GetFunc(i)
-	endfor
+	def Loop()
+	  var flist: list<func>
+	  for i in range(10)
+	    flist[i] = GetFunc(i)
+	  endfor
+	  echo flist->len()->range()->map((i, _) => flist[i]())
+	enddef
+	Loop()
+
+Outputs: >
+	[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
 
 ==============================================================================
 
```

**Comment by lacygoill** [comment]
Also, some of the function names and variable names are not clear enough.

For example `GetFunc()` does not return a funcref to a regular function, but to a closure.  So, `GetClosure()` might be better.

And `flist` is not just a list of funcrefs; it's a list of closures.  So, `closures` might be better.

New patch:
```diff
diff --git a/runtime/doc/vim9.txt b/runtime/doc/vim9.txt
index a0681d287..4df293cc9 100644
--- a/runtime/doc/vim9.txt
+++ b/runtime/doc/vim9.txt
@@ -1046,25 +1046,45 @@ For these the backtick expansion can be used.  Example: >
 	enddef
 
 Closures defined in a loop will share the same context.  For example: >
-	var flist: list<func>
-	for i in range(10)
-	  var inloop = i
-	  flist[i] = () => inloop
-	endfor
+	def DefineClosuresInLoop()
+	  var closures: list<func>
+	  for i in range(10)
+	    var inloop = i
+	    closures[i] = () => inloop
+	  endfor
+	  echo closures
+	    ->len()
+	    ->range()
+	    ->map((i, _) => closures[i]())
+	enddef
+	DefineClosuresInLoop()
 
-The "inloop" variable will exist only once, all closures put in the list refer
+Outputs: >
+	[9, 9, 9, 9, 9, 9, 9, 9, 9, 9]
+
+TThe "inloop" variable will exist only once, all closures put in the list refer
 to the same instance, which in the end will have the value 9.  This is
 efficient.  If you do want a separate context for each closure call a function
 to define it: >
-	def GetFunc(i: number): func
+	def GetClosure(i: number): func
 	  var inloop = i
 	  return () => inloop
 	enddef
 
-	var flist: list<func>
-	for i in range(10)
-	  flist[i] = GetFunc(i)
-	endfor
+	def DefineClosuresInLoop()
+	  var closures: list<func>
+	  for i in range(10)
+	    closures[i] = GetClosure(i)
+	  endfor
+	  echo closures
+	    ->len()
+	    ->range()
+	    ->map((i, _) => closures[i]())
+	enddef
+	DefineClosuresInLoop()
+
+Outputs: >
+	[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
 
 ==============================================================================
 
```

**Comment by lacygoill** [comment]
> If not, the issue might come from inloop which is local to a block in a script.

In contrast to a block in a function.

I suspect that there is some undocumented difference between how blocks are implemented at the script level vs in compiled code, which should not exist and explains the error.

**Comment by brammool** [comment]
> > If not, the issue might come from inloop which is local to a block
> > in a script.
> 
> In contrast to a block in a function.
> 
> I suspect that there is some undocumented difference between how
> blocks are implemented at the script level vs in compiled code, which
> should not exist and explains the error.

There is a bug in how the variable in the loop is stored.  A new
variable is created every time, while it should re-use the one from the
previous loop.  Otherwise long loops would create many, many variables.
This will also fix a crash.

-- 
Get a life?  What is the URL where it can be downloaded?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
> Also, the current snippets don't give any output which makes it more
> difficult for the reader to understand what is happening.  Updated
> diff which makes the code give some useful output:

Thanks for the suggestion.  Now that the bugs are fixed we can use this:


Closures defined in a loop will share the same context.  For example: >
	var flist: list<func>
	for i in range(5)
	  var inloop = i
	  flist[i] = () => inloop
	endfor
	echo range(5)->map((i, _) => flist[i]())
	# Result: [4, 4, 4, 4, 4]

The "inloop" variable will exist only once, all closures put in the list refer
to the same instance, which in the end will have the value 4.  This is
efficient, also when looping many times.  If you do want a separate context
for each closure call a function to define it: >
	def GetClosure(i: number): func
	  var infunc = i
	  return () => infunc
	enddef

	var flist: list<func>
	for i in range(5)
	  flist[i] = GetClosure(i)
	endfor
	echo range(5)->map((i, _) => flist[i]())
	# Result: [0, 1, 2, 3, 4]



-- 
"The amigos also appear to be guilty of not citing the work of others who had
gone before them.  Even worse, they have a chapter about modeling time and
space without making a single reference to Star Trek!"
			(Scott Ambler, reviewing the UML User Guide)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
