### ISSUE TITLE
Vim9: strange error when using "++" on inproper expression

### ISSUE THREAD

**Issue by obcat** [vim/vim#8616]
**Describe the bug**

In Vim9 script, using "++" on an improper expression might result in a strange error.

**To Reproduce & Expected behavior**

1. Run `vim --clean`.

1. Source this script

    ```vim
    vim9script
    ++7
    ```

    This error is given:

    ```
    E488: Trailing characters: 7 += 1 |
    ```

**Expected behavior**

A proper error is given, like this:

```
E????: "++" must be followed by a variable: ++7
```

**Environment**

 - Vim 8.2.3204
 - macOS Catalina (version 10.15.7)
 - iTerm2

**Additional context**

Other examples:

```vim
vim9script
++'a'
```

```
E488: Trailing characters: 'a' += 1 |
```

```vim
vim9script
++[]
```

```
E475: Invalid argument: ] += 1 |
```

```vim
vim9script
++
```

```
E475: Invalid argument:  += 1 |
```

```vim
vim9script
++@
```

```
E1004: White space required before and after '+=' at "+= 1 |"
```

```vim
vim9script
++&
```

```
E18: Unexpected characters in :let
```

**Comment by lacygoill** [comment]
Relevant comment:

> This is tricky, because the "++" command is translated into an
> assignment with an operator.  Not sure if this can be made better
> without a lot of work.

[Source](https://github.com/vim/vim/issues/8440#issuecomment-868789309)

But yes, I agree.  A better error would be nice.

**Comment by obcat** [comment]
Thanks for the info. So a lot of work is needed to fix this issue.
I think this should be fixed, but other tasks might be more important.

**Comment by brammool** [comment]
Let's be realistic: If you use "++7" and you get just an error "this is wrong" most people will already see why.
I don't think we should spend time on the exact error message.

**Comment by obcat** [comment]
Yes, most people realize their mistake. And most of them will not care about content of error message.

Then, how about adding a note on this? Some people may report this again, and then we will have to spend time on answering "This won't be fixed."
