### ISSUE TITLE
make test error Test 473, Test_geometry failing

### ISSUE THREAD

**Issue by neilhwatson** [vim/vim#8618]
**Describe the bug**

Make test fails

**To Reproduce**

Configure, make, make test:

```
   ./configure \
      --enable-rubyinterp=yes \
      --enable-python3interp=yes \
      --with-python3-config-dir=$(python3-config --configdir) \
      --enable-perlinterp=yes \
      --enable-gui=gtk3 \
      --enable-cscope \
      --prefix=$HOME

   make -j3
   make test
```

Results: 

Failures:
	Screen size too small! Tests require at least 24 lines with 80 characters, got 50 lines with 71 characters
	From test_startup.vim:
	Found errors in Test_geometry():
	command line..script /home/neil/src/vim/src/testdir/runtest.vim[473]..function RunTheTest[44]..Test_geometry line 24: Expected ['31', '13', '41', '43', '[41, 43]'] but got ['115', '63', '0', '26', '[0, 26]']

**Expected behavior**

Passes on 8.2.2603 but appears to fail as above on all newer patches

**Environment (please complete the following information):**

- Anything above 8.2.2603
 - Debian 11 AMD64
 - Terminal: Teminology

**Comment by brammool** [comment]
I haven't heard this problem from others.  Anything special about your system?
The window manager perhaps?

**Comment by dpelle** [comment]
Could it be related to screen size? What does this report?
```
$ xdpyinfo  | grep dimensions
  dimensions:    3840x2160 pixels (1016x571 millimeters)
```

**Comment by dpelle** [comment]
What's also your window manager.
Perhaps this happens with tiling window managers?

**Comment by neilhwatson** [comment]
Window manager DWM; yes it's tiling.

```
 $ xdpyinfo  | grep dimensions
  dimensions:    2560x1600 pixels (677x423 millimeters)
```

**Comment by chrisbra** [comment]
So with your WM, if you run Vim like this (from the test):

    vim -f -g -geometry 31x13+41+43

I suppose your window manager resizes Vim and the `-geometry` isn't really respected?

**Comment by chrisbra** [comment]
I guess you can then try to ignore that test for your environment:

    export TEST_MAY_FAIL=Test_geometry

**Comment by neilhwatson** [comment]
Correct, geometry option is ignored.

**Comment by chrisbra** [comment]
If there is no way for Vim to detect this (perhaps DWM does export some environment variables), then I would suggest to go with the `TEST_MAY_FAIL` workaround.

**Comment by neilhwatson** [comment]
I did, and it works

**Comment by chrisbra** [comment]
let's close it then
