### ISSUE TITLE
Adding a more useful ChangeLog

### ISSUE THREAD

**Issue by arp242** [vim/vim#8622]
For the last year or two I've been keeping a Vim ChangeLog of sorts at https://www.arp242.net/vimlog, which lists the most prominent and useful user-visible changes.

I think it would be useful to add this to Vim; now it's just this website that few people visit or know about aside from the odd occasion where I mention it somewhere – that's okay, because like I said, I update it for my own reasons. But I think it would be useful for others too.

The question is where and how; the easiest is just a link somewhere, but that's likely easily missed; a new `:help changelog.txt` seems to make the most sense to me, i.e. something like:

    2021           *changelog-2021*
    ----

    Add list to 'breakindentopt'                         8.2.3160, 8.2.3198 (Jul 22)
        Add additional indent for lines that match a numbered or
        bulleted list (using the 'formatlistpat' setting).

    Add |setdigraph()|, |setdigraphlist()|, |getdigraph()|               8.2.3184 (Feb 15)
        |getdigraphlist()|
        List and define digraphs from functions.

    [..]

    2020           *changelog-2020*
    ----

    [..]

Which looks like:

![xscreen-2021-07-24T14:47:18 webp](https://user-images.githubusercontent.com/1032692/126860161-10c9d157-95e0-45c5-956e-51ff250af577.png)

This could also be added to the startup screen maybe. 

The website is generated with a Python script from a list; see [the source](https://github.com/arp242/vimlog/blob/master/gen.py); adding some new format like a plain-text output isn't too much work, I can just do that. After that it can either be updated manually or from the script.

---

Some background and motivation for doing this in the first place:

I mostly maintain this for my own purposes, as there are often small (and sometimes not-so-small) enhancements to Vim. For example I never would have known about the addition of `list` to `breakindentopt` until I hear it through the Vim grapevine on some chat or whatnot, or until Vim 9 is released with a fully updated changelog. This would be a shame as it's quite a useful option. A lot of people are probably missing out on features their Vim supports simple because they don't know about them; `set spelloptions=camel`, `g<Tab>`, the built-in fuzzy matching, `set nrformats+=unsigned`, and a bunch of others.

There's `:help version.txt` etc, but it's not really up-to-date for 8.2; a fixable problem for sure, but grouping things by v8.2, v8.1, etc actually isn't all *that* useful; 8.2.0000 is from December 2019 – a wonderful glorious time in the distant past when we could travel freely and go to pubs whenever we wanted.

Few people – if anyone – upgrade from 8.1.0000 to 8.2.0000, they update from 8.2.[..] to 8.2.[..]. For example going from Debian 10 to Debian 11 means going from Vim 8.1.0875 to Vim 8.2.2434; which useful changes does this have for me as a user? Not so easy to find that out from :help version8.txt as it's not sorted by date; I need to manually diff it against a previous version, or something, to actually know what new stuff and changes I have (and hope it's complete).

Distros like Arch or Void generally include something reasonably close to the latest master; the latest update for Void went from 8.2.2513 to 8.2.2874; not easy to find out what that gives me either.

Getting this from `git log` isn't very easy; just `git log` is very verbose; I generally update this by doing a `git log runtime/doc`, reasoning that user-visible changes come with documentation updates, although you need to filter quite a few things from this as well, and git diffs also isn't really the most user-friendly UI.

It doesn't list absolutely everything, just what's useful for (most) users.. It also groups things if the patches are reasonably close: for example the `fillchars` had several changes in a two-week period several months ago: that's listed as just one entry. In short, it's a good quick overview that adds a lot of value for "normal" users not tracking Vim development.

**Comment by brammool** [comment]
Martin Tournoij wrote:

> For the last year or two I've been keeping a Vim ChangeLog of sorts at
> https://www.arp242.net/vimlog, which lists the most prominent and
> useful user-visible changes.
> 
> I think it would be useful to add this to Vim; now it's just this
> website that few people visit or know about aside from the odd
> occasion where I mention it somewhere – that's okay, because like I
> said, I update it for my own reasons. But I think it would be useful
> for others too.

This can be interesting for users.  Including it with Vim means it would
quickly get outdated, I think it's fine to point to the website.  Since
it starts with Vim 8.0 adding it just above "help new-8" seems like a
good place.


-- 
hundred-and-one symptoms of being an internet addict:
225. You sign up for free subscriptions for all the computer magazines

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by arp242** [comment]
> Including it with Vim means it would quickly get outdated

To be clear: I wouldn't have suggested this if I wasn't also prepared to update it for the foreseeable future. I do this now anyway.

But yeah, just adding a link is also good – whatever you're most comfterable with. Could possible also move the repo to vim/changelog or some such and update it from there(?) That would give that advantage that you, Christian, etc. could also easily update it if need be.

**Comment by chrisbra** [comment]
Ah, yes I remember your webpage, nice work.

We used to have a section on vim.org that included the latest patches. I wonder if we could show the content from your webpage there?

**Comment by chrisbra** [comment]
I suppose this can be closed now, it is mentioned in the help with the recent runtime update https://github.com/vim/vim/commit/53f7fccc9413c9f770694b56f40f242d383b2d5f

**Comment by arp242** [comment]
Cheers, thanks
