### ISSUE TITLE
I want to change color of title bar but have no idea

### ISSUE THREAD

**Issue by hungpham3112** [vim/vim#8625]
i want to change this thing to dark below but i dont know what it is and what command for this in vim
![image](https://user-images.githubusercontent.com/75968004/126867592-e6f0169c-97e2-4dae-8a99-d5809b5432d8.png)
Thanks for helping

**Comment by chrisbra** [comment]
I don't think the color can be adjusted. This may be something you need to do in Windows. I believe you can theme window title bars consistently for all applications.

**Comment by Hungpro3112** [comment]
Thank you , i solved my problem.
