### ISSUE TITLE
Vim9: not enough info for error given because of type mismatch in lambda

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8633]
**Describe the bug**

In Vim9 script, sometimes, we don't get enough information when a type mismatch causes an error in a lambda expression.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func(l: list<any>)
            l->map((_, v: number) => v.key)
        enddef
        Func([123])
    EOF
    )

`E715` is given:

    E715: Dictionary required

**Expected behavior**

A better error is given, with more info.  For example:

    E1234: v is declared as a number but used as a dictionary in v.key

This is *much* better because it answers many questions:

   - Which variable is used as a dictionary? (`v`)
   - Where is this variable used as a dictionary? (`v.key`)
   - Why cannot this variable be used as a dictionary? (because declared as a number)

Bear in mind that the lambda could be much more complex than a simple `v.key`.  So, while the answers to these questions might be easy to find here, that's not true in the general case.

**Environment**

 - Vim version: 8.2 Included patches: 1-3215
 - OS: Ubuntu 20.04.2 LTS
 - Terminal: XTerm(353)

**Additional context**

Same issue when the lambda is replaced with an inline function:
```vim
vim9script
def Func(l: list<any>)
    l->mapnew((_, v: number) => {
        v.key
    })
enddef
Func([123])
```
    E715: Dictionary required

**Comment by lacygoill** [comment]
I hope this can be improved, because errors given from lambdas are often difficult to understand.

It would be very helpful if this kind of template could be followed for any error given by a lambda:

    E1234: NAME is declared as TYPE1 but used as TYPE2 in EXPR

**Comment by brammool** [comment]
I made the error a bit clearer:
E1229: Expected dictionary for using key "key", but got number

Can't do much more than that.  "NAME is declared as" cannot be done, since it can be an expression, and it's already processed and we only have the type.
