### ISSUE TITLE
Vim9: not enough info for error caused by disallowed type mutation

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8634]
**Describe the bug**

In Vim9 script, we don't get enough information when an error is given because of a disallowed type mutation.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        'echo'->setline(1)
        set ft=vim
        syntax on
        echo synstack('.', col('.'))->map((_, id) => id->synIDattr('name'))
    EOF
    )

`E1012` is given with this message:

    E1012: Type mismatch; expected number but got string in map()

**Expected behavior**

The message contains more info.  For example:

    E1234: map() operated on number but returned string; use mapnew()

This message answers several questions which could pop up in the reader's mind:

   - Where was a number expected? In the arguments? In the return value?
   - Why is a number expected in the first place? The code worked fine in legacy.
   - How do I fix this?

**Environment**

 - Vim version: 8.2 Included patches: 1-3215
 - OS: Ubuntu 20.04.2 LTS
 - Terminal: XTerm(353)

**Additional context**

The current issue is a follow-up to https://github.com/vim/vim/issues/8608

The patch fixing the latter has improved the message a little, but IMO, not enough.

---

The same issue probably applies to all functions which have a `*new()` counterpart.  That is `extend()`, `flatten()` and `map()`.

---

Here is another example, where the error is hard to understand:
```vim
vim9script
def Func()
    var l = getline(1, '$')
        ->map((_, v) => ({a: v}))
    l->map((i, v) => ({b: l[i].a}))
enddef
defcompile
```
    Error detected while compiling ...function <SNR>1_Func[3]..<lambda>2:
    line    1:
    E715: Dictionary required

Where is a dictionary required?  `<lambda>2` is not very helpful.  There are several lambdas in the function, and we cannot retrieve the definition of `<lambda>2`, because it failed to compile:

    :def <lambda>2
    E123: Undefined function: <lambda>2

Actually, we can infer that it's the second one thanks to the line number `3`:

    Error detected while compiling ...function <SNR>1_Func[3]..<lambda>2:
                                                           ^

But that's not always possible.  The code could be re-written such as several lambdas are written on the same line (using bars if necessary).

And once we finally know which lambda, we still have to find which token exactly in the latter causes an issue.  That might be difficult in the general case, if the expression is complex.

Also, why is a dictionary required?

As a workaround, we can stop relying on type inferrence in the `l` assignment, and instead, declare its type explicitly:
```vim
vim9script
def Func()
    var l: list<dict<string>> = getline(1, '$')
        ->map((_, v) => ({a: v}))
    l->map((i, v) => ({b: l[i].a}))
enddef
defcompile
```
    Error detected while compiling ...function <SNR>1_Func:
    line    1:
    E1012: Type mismatch; expected list<dict<string>> but got list<string>

This gives a more useful error message, because we can infer from it that the real issue comes from the first `map()` which fails to mutate the list of strings into a list of dictionaries.  Which is expected, because `map()` cannot change the type of the items in a list (only their values).  `mapnew()` can:
```vim
vim9script
def Func()
    var l: list<dict<string>> = getline(1, '$')
        ->mapnew((_, v) => ({a: v}))
    l->map((i, v) => ({b: l[i].a}))
    echo 'no error'
enddef
Func()
```
    no error

But there is still room for improvement.  It would be easier if we didn't have to infer anything.  That would be the case if the message said:

    E1234: map() operated on list<string> but returned list<dict<any>>; use mapnew()

**Comment by lacygoill** [comment]
> Here is another example, where the error is hard to understand:

Not sure, but there might be something wrong in how Vim compiles this function:
```vim
vim9script
def Func()
    var l = getline(1, '$')
        ->map((_, v) => ({a: v}))
    l->map((i, v) => ({b: l[i].a}))
enddef
defcompile
```
    Error detected while compiling ...function <SNR>1_Func[3]..<lambda>2:
    line    1:
    E715: Dictionary required

It's weird that the error is given from the 2nd lambda, while the real issue comes from the 1st one.

It seems that Vim infers that `l` is a list of strings.  But that should not be possible:

   - `getline(1, '$')` is a list of strings
   - `map()` returns a list of dictionaries (which is easy for Vim to infer because of the `({})` syntax)
   - `map()` is not allowed to change the type of an item in a list

I guess that it's yet another case of #8092

**Comment by lacygoill** [comment]
> The message contains more info. For example:
>
>     E1234: map() operated on number but returned string; use mapnew()

Actually, the word "returned" is misleading or confusing here.  Here is another suggestion:

    E1234: map() cannot change type of item from number to string; use mapnew()

**Comment by lacygoill** [comment]
"list item" instead of just "item" to be more clear:

    E1234: map() cannot change type of list item from number to string; use mapnew()

**Comment by brammool** [comment]
>    > Here is another example, where the error is hard to understand:
> 
> Not sure, but there might be something wrong in how Vim compiles this function:
> ```vim
> vim9script
> def Func()
>     var l = getline(1, '$')
>         ->map((_, v) => ({a: v}))
>     l->map((i, v) => ({b: l[i].a}))
> enddef
> defcompile
> ```
>     Error detected while compiling ...function <SNR>1_Func[3]..<lambda>2:
>     line    1:
>     E715: Dictionary required
> 
> It's weird that the error is given from the 2nd lambda, while the real
> issue comes from the 1st one.

It's a bit of a puzzle, but the error is correct: "l[i].a" tries to use
the key "a" on what is a string, not a dict.  This is in the first line
of the second lambda.

Best we can do is give the name of the key.  We don't have much context
otherwise.  Oh, and we can mention what type we got instead.

> It seems that Vim infers that `l` is a list of strings.  But that
> should not be possible:
> 
>    - `getline(1, '$')` is a list of strings
>    - `map()` returns a list of dictionaries (which is easy for Vim to infer because of the `({})` syntax)
>    - `map()` is not allowed to change the type of an item in a list
> 
> I guess that it's yet another case of #8092

map() returns the type of the first argument.  What would be detected is
that the lambda used returns the wrong type.  That is currently not
implemented.

-- 
hundred-and-one symptoms of being an internet addict:
271. You collect hilarious signatures from all 250 mailing lists you
     are subscribed to.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
Using "map() cannot change type of list item from number to string; use mapnew()" is also misleading, because the user may intend to use map() but make an error in the lambda return type.
I think we have done enough for now.
