### ISSUE TITLE
Does the mouse function increase?

### ISSUE THREAD

**Issue by ghost** [vim/vim#8643]
_Instructions for use:
Looking forward to adding the mouse response in the pop-up window

**Description error**
No error

**screenshot**

Operating system Debian

**Comment by chrisbra** [comment]
So if you understand your screen capture correctly, you would like to be able to select items from the popup menu using the mouse, right?

**Comment by chrisbra** [comment]
BTW: what is your mouse setting?

**Comment by qq108201645** [comment]
> 因此，如果您正确理解屏幕截图，您希望能够使用鼠标从弹出菜单中选择项目，对吗？

yes

**Comment by qq108201645** [comment]
> BTW：你的鼠标设置是什么？

set mouse=a and set mouse -=a

**Comment by qq108201645** [comment]
Whether it’s a tablet or an Android, it’s a slow choice. If you can add the left mouse button to drag, click to select the word will be great

https://user-images.githubusercontent.com/50875340/127527775-03c0951e-3ff8-403d-af70-bcd2eb0443e2.mp4
