### ISSUE TITLE
Vim9: cannot use "system()" without "{input}" optional argument

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8650]
**Describe the bug**

In Vim9 script, we cannot use `system()` to start an external process, without the optional argument `{input}`.

**To Reproduce**

Run this shell command:

    vim -Nu NONE +'vim9 system(":")'

`E1224` is given:

    E1224: String or List required for argument 2

**Expected behavior**

No error is given, because we didn't pass the 2nd optional argument.

**Environment**

 - Vim version: 8.2 Included patches: 1-3229
 - OS: Ubuntu 20.04.2 LTS
 - Terminal: XTerm(353)

**Additional context**

Regression introduced in 8.2.3229.

---

Same issue with `systemlist()`:
```vim
vim9script
systemlist(':')
```
    E1224: String or List required for argument 2

---

cc @yegappan via https://github.com/vim/vim/pull/8646

**Comment by vim-ml** [comment]
Hi,

On Tue, Jul 27, 2021 at 1:24 PM lacygoill ***@***.***> wrote:

> *Describe the bug*
>
> In Vim9 script, we cannot use system() to start an external process,
> without the optional argument {input}.
>
> *To Reproduce*
>
> Run this shell command:
>
> vim -Nu NONE +'vim9 system(":")'
>
> E1224 is given:
>
> E1224: String or List required for argument 2
>
> *Expected behavior*
>
> No error is given, because we didn't pass the 2nd optional argument.
>
> *Environment*
>
>    - Vim version: 8.2 Included patches: 1-3229
>    - OS: Ubuntu 20.04.2 LTS
>    - Terminal: XTerm(353)
>
> *Additional context*
>
> Regression introduced in 8.2.3229.
> ------------------------------
>
> Same issue with systemlist():
>
> vim9scriptsystemlist(':')
>
> E1224: String or List required for argument 2
>
> ------------------------------
>
> cc @yegappan <https://github.com/yegappan> via #8646
> <https://github.com/vim/vim/pull/8646>
>
>
>
Thanks for reporting the issue. I have created PR #8651 with
a fix for this. Let me know if you see any other issues with other
functions.

- Yegappan
