### ISSUE TITLE
Vim9: unexpected E1073 error when importing function and using "noclear" argument

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8653]
I have a weird error, which I've reduced to this snippet:
```vim
vim9script
mkdir('/tmp/import', 'p')
var lines =<< trim END
    vim9script
    export def Func(x = 0)
    enddef
END
lines->writefile('/tmp/import/script.vim')
&rtp = '/tmp/import'
lines =<< trim END
    vim9script noclear

    set rtp^=/tmp/import
    import Func from '/tmp/import/script.vim'

    Func()
END
lines->writefile('/tmp/test.vim')
edit /tmp/test.vim
source %
source %
```
    line    5:
    E1073: Name already defined: Func

I'm not sure the error should be given.  Maybe it should because of `noclear`.  But watch this:
```vim
vim9script
mkdir('/tmp/import', 'p')
var lines =<< trim END
    vim9script
    export def Func()
    enddef
END
lines->writefile('/tmp/import/script.vim')
&rtp = '/tmp/import'
lines =<< trim END
    vim9script noclear

    set rtp^=/tmp/import
    import Func from '/tmp/import/script.vim'

    Func()
END
lines->writefile('/tmp/test.vim')
edit /tmp/test.vim
source %
source %
```
This time, no error is given.  And yet, it's the exact same code; the only difference is that we've removed the optional argument from `Func()`'s header:

    # before
    export def Func(x = 0)

    # after
    export def Func()

That should not make any difference with regards to the previous error; this suggests that something is wrong.

---

Also, even if the error is expected, the line number is wrong; it should be 4, not 5.  That's probably another bug, which is related to an empty line below an `import`.

**Comment by lacygoill** [comment]
I forgot; if we remove the `Func()` invocation, the error disappears:
```vim
vim9script
mkdir('/tmp/import', 'p')
var lines =<< trim END
    vim9script
    export def Func(x = 0)
    enddef
END
lines->writefile('/tmp/import/script.vim')
&rtp = '/tmp/import'
lines =<< trim END
    vim9script noclear

    set rtp^=/tmp/import
    import Func from '/tmp/import/script.vim'

END
lines->writefile('/tmp/test.vim')
edit /tmp/test.vim
source %
source %
```
    no error

Again, I don't see why that should matter.  Especially considering that `Func()` is positioned *after* the supposed error.

**Comment by brammool** [comment]
> I have a weird error, which I've reduced to this snippet:
> ```vim
> vim9script
> mkdir('/tmp/import', 'p')
> var lines =<< trim END
>     vim9script
>     export def Func(x = 0)
>     enddef
> END
> lines->writefile('/tmp/import/script.vim')
> &rtp = '/tmp/import'
> lines =<< trim END
>     vim9script noclear
> 
>     set rtp^=/tmp/import
>     import Func from '/tmp/import/script.vim'

Since the import uses an absolute path, setting 'rtp' is not needed.
It would not work anyway with "/tmp/import", it would look in
"/tmp/import/import".

>     Func()
> END
> lines->writefile('/tmp/test.vim')
> edit /tmp/test.vim
> source %
> source %
> ```
>     line    5:
>     E1073: Name already defined: Func
> 
> I'm not sure the error should be given.  Maybe it should because of
> `noclear`.

Correct, Func is redefined.  It is the same thing, but how do we know?

> But watch this:
> ```vim
> vim9script
> mkdir('/tmp/import', 'p')
> var lines =<< trim END
>     vim9script
>     export def Func()
>     enddef
> END
> lines->writefile('/tmp/import/script.vim')
> &rtp = '/tmp/import'
> lines =<< trim END
>     vim9script noclear
> 
>     set rtp^=/tmp/import
>     import Func from '/tmp/import/script.vim'
> 
>     Func()
> END
> lines->writefile('/tmp/test.vim')
> edit /tmp/test.vim
> source %
> source %
> ```
> This time, no error is given.  And yet, it's the exact same code; the only difference is that we've removed the optional argument from `Func()`'s header:
> 
>     # before
>     export def Func(x = 0)
> 
>     # after
>     export def Func()
> 
> That should not make any difference with regards to the previous
> error; this suggests that something is wrong.

Yes, this looks like a bug.  In your next message:

> I forgot; if we remove the `Func()` invocation, the error disappears:

What happens is that calling the function causes it to be compiled and
the type of the argument is inferred from the value.  The newly imported
function has type "unknown", which is different.

I suppose the best we can do is not check the argument type if the new
one is "unknown".

> Also, even if the error is expected, the line number is wrong; it
> should be 4, not 5.  That's probably another bug, which is related to
> an empty line below an `import`.

Yes, it reads ahead to find extra arguments.  I'll fix that.

-- 
Error:015 - Unable to exit Windows.  Try the door.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
