### ISSUE TITLE
How to expand to full path WITH drive letter under windows?

### ISSUE THREAD

**Issue by zdm** [vim/vim#8656]
Hi.
I am unable to find answer so asking here.
I need to get current buffer path `WITH` the windows drive letter.
But `:echo expand( "%:p" )` always strips drive letter.
How I can solve this problem?

**Comment by chrisbra** [comment]
I cannot reproduce this. What version is this? If I do `:gvim --clean -c ':h' -c 'only' -c "echo expand('%:p')" I correctly see the complete path: `C:\Program Files\Vim\vim82\doc\help.txt`

This is version 8.2.3161 from the [vim-win32-installer](https://github.com/vim/vim-win32-installer/)

**Comment by zdm** [comment]
Oh, seems, that this is neovim only issue.
Sorry.

**Comment by vim-ml** [comment]
On 2021-07-29, Dmytro Z. wrote:
> Hi.
> I am unable to find answer so asking here.
> I need to get current buffer path WITH the windows drive letter.
> But :echo expand( "%:p" ) always strips drive letter.
> How I can solve this problem?

I'm afraid I don't know what the problem might be.  It works just
fine for me using Vim 8.2.3227 on Windows 10.  I didn't see anything
in the documentation about optionally removing drive letters.

Regards,
Gary
