### ISSUE TITLE
Vim: Caught deadly signal SEGV

### ISSUE THREAD

**Issue by leihuxi** [vim/vim#866]
when add `include <list>`to any .cc or *.cpp file, got :Vim: Caught deadly signal SEGV(but its ok if save as not a cpp file)
example:
tt.cc

```
#include <list>
int main() {
}
```

build:
./configure --with-features=huge \
    --enable-multibyte \
    --enable-rubyinterp \
    --enable-pythoninterp \
    --with-python-config-dir=/usr/lib/python2.7/config \
    --enable-perlinterp \
    --enable-luainterp \
    --enable-gui=gtk2 --enable-cscope --prefix=/usr
branch:master

system:ubuntu 16.04 lts
my vimrc:
[vimrc.txt](https://github.com/vim/vim/files/313098/vimrc.txt)

**Comment by k-takata** [comment]
Which version on which OS?
Does it occur without plugins? (`vim -N -u NONE`)
Please consider getting a stacktrace: https://github.com/vim/vim/issues/851#issuecomment-225160476

**Comment by leihuxi** [comment]
the plugins syntastic got the vim issue

**Comment by vim-ml** [comment]
Am 2016-06-14 06:28, schrieb leihuxi:

> Closed #866 [1].

Could you please nevertheless post an stacktrace.
In any case, Vim shouldn't segfault

**Comment by vim-ml** [comment]
Dear, 

I've got a nice  surprise for  you,  I think you'll love it! Just take a look <http://opt.peacesystems.com/e4aazkim>

Cheers, paul
