### ISSUE TITLE
"echoerr" test in Ch_communicate() can randomly fail

### ISSUE THREAD

**Issue by ghost** [vim/vim#8662]
**Describe the bug**
On line number 122 in the file testdir/test_channel.vim, an "echoerr"
command is sent using ch_evalexpr() to a python server that has been
created by the test.  The server responds with two JSON arrays:

    ["ex","echoerr \"this is an error\""]
    [1,"echoerr"]

If the Vim instance under test retrieves both with a single read:

    ["ex","echoerr \"this is an error\""][1,"echoerr"]

then the test will fail.  It will fail because Vim will process the
numbered array first, apparently causing the ch_evalexpr() call to return
and control will flow out of the try-catch block that contains it.  Later,
when the "echoerr" command is evaluated, control has left the catch-try
block and the exception is not caught.  Since the purpose of the test is
to catch the exception, the test fails.  

**To Reproduce**
Run the test in testdir:  make test_channel.res

However, as the Title says, the test may or may not fail.  See "Additional Context" below.

**Expected behavior**
The Vim instance under test will read the channel once and retrieve only
the "echoerr" command which is then executed, generating an exception
which is then caught as intended.  A second read will retrieve the
numbered array.  

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Vim version: 8.2.3242 with normal features and no gui
 - OS:  Linux  4.19.0-17-686-pae #1 SMP Debian 4.19.194-3 (2021-07-18) i686 GNU/Linux
 - Terminal: XFCE terminal with TERM=xterm-256

**Additional context**
I have eliminated this error by adding a small time delay in the python
server between the two messages it sends.  Specifically, I inserted 
    time.sleep(0.01)
after line number 116 in file test_channel.py.  I chose that value because
it is the same one used by several other cases that send an unnumbered
response followed by a numbered one.  

This "solution" is not a fix- it simply makes the error less likely to occur.

**Comment by brammool** [comment]
Michael Soyka wrote:

> **Describe the bug**
> On line number 122 in the file testdir/test_channel.vim, an "echoerr"
> command is sent using ch_evalexpr() to a python server that has been
> created by the test.  The server responds with two JSON arrays:
> 
>     ["ex","echoerr \"this is an error\""]
>     [1,"echoerr"]
> 
> If the Vim instance under test retrieves both with a single read:
> 
>     ["ex","echoerr \"this is an error\""][1,"echoerr"]
> 
> then the test will fail.  It will fail because Vim will process the
> numbered array first, apparently causing the ch_evalexpr() call to return
> and control will flow out of the try-catch block that contains it.  Later,
> when the "echoerr" command is evaluated, control has left the catch-try
> block and the exception is not caught.  Since the purpose of the test is
> to catch the exception, the test fails.  

Thanks for observing this.

> **To Reproduce**
> Run the test in testdir:  make test_channel.res
> 
> However, as the Title says, the test may or may not fail.  See "Additional Context" below.
> 
> **Expected behavior**
> The Vim instance under test will read the channel once and retrieve only
> the "echoerr" command which is then executed, generating an exception
> which is then caught as intended.  A second read will retrieve the
> numbered array.  
> 
> **Screenshots**
> N/A
> 
> **Environment (please complete the following information):**
>  - Vim version: 8.2.3242 with normal features and no gui
>  - OS:  Linux  4.19.0-17-686-pae #1 SMP Debian 4.19.194-3 (2021-07-18) i686 GNU/Linux
>  - Terminal: XFCE terminal with TERM=xterm-256
> 
> **Additional context**
> I have eliminated this error by adding a small time delay in the python
> server between the two messages it sends.  Specifically, I inserted 
>     time.sleep(0.01)
> after line number 116 in file test_channel.py.  I chose that value because
> it is the same one used by several other cases that send an unnumbered
> response followed by a numbered one.  
> 
> This "solution" is not a fix- it simply makes the error less likely to
> occur.  

Well, it's as good as a fix.  I had seen Ch_communicate() fail randomly,
especially with IPv6.  Let's see if this sleep fixes it.

-- 
Facepalm statement #4: "3000 year old graves?  That's not possible, it's only
2014!"

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by msoyka-of-wharton** [comment]
The reason I hesitated to call  it a fix is because of the  out-of-order handling of the JSON messages in function "channel_read_json_block".  It appears that when multiple messages are retrieved by a single read that numbered messages will be handled before the others (I've based this opinion on my investigation of this test, not on any other tests I've run).  I may have missed it but I don't see this behavior documented in the help topic "channel-use".  

By the way, I also saw this test fail for IPV6 but neglected to mention it.  The proposed delay fixed that one as well.

**Comment by danainacore** [comment]
> #8672

**Comment by brammool** [comment]
Michael Soyka wrote:

> The reason I hesitated to call  it a fix is because of the
> out-of-order handling of the JSON messages in function
> "channel_read_json_block".  It appears that when multiple messages are
> retrieved by a single read that numbered messages will be handled
> before the others (I've based this opinion on my investigation of this
> test, not on any other tests I've run).  I may have missed it but I
> don't see this behavior documented in the help topic "channel-use".  

The order is not guaranteeded.  Communication is asynchronous by nature.
It's also possible that a message gets split into parts, and there can
be a delay in between, esp. on a busy system.  And the systems running
CI are usually busy.

> By the way, I also saw this test fail for IPV6 but neglected to
> mention it.  The proposed delay fixed that one as well.

It was flaky, thus we'll have to see if this fixes at (and no other
problem pops up).

-- 
Facepalm statement #6: "Estland is a fantasy place, just like Middle Earth and
Madagaskar"

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
fixed by 890ee4e2be1dca0c07a91f836e26baead952ae7c
