### ISSUE TITLE
Vim9: inconsistent handling of number as first argument for "repeat()"

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8664]
**Describe the bug**

In Vim9 script, passing a number as first argument to `repeat()` is accepted at the script level, but not in compiled code, which is inconsistent.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        var s: string
        s ..= repeat(0, 3)
    EOF
    )

No error is given.

Now, run this other shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
          var s: string
          s ..= repeat(0, 3)
        enddef
        defcompile
    EOF
    )

`E1012` is given:

    E1012: Type mismatch; expected string but got number

**Expected behavior**

To be consistent, either the first command should give an error, or the second one should not complain.

**Environment**

 - Vim version: 8.2 Included patches: 1-3249
 - OS: Ubuntu 20.04.2 LTS
 - Terminal: XTerm(353)

**Additional context**

The error message lacks some context:
```vim
vim9script
def Func()
  var s: string
  s ..= repeat(0, strlen(s))
enddef
defcompile
```
    E1012: Type mismatch; expected string but got number

Who expected a string but got a number? `strlen()`?  `repeat()`?  `..=`?
It turns out that it's `repeat()`, but it's not obvious.

Also, since the error is in an argument, why doesn't the message start with `Argument 1:`:

    E1012: Argument 1: Type mismatch; expected string but got number
           ^---------^

Just like here:
```vim
vim9script
def Func()
    strlen({})
enddef
defcompile
```
    E1013: Argument 1: type mismatch, expected string but got dict<unknown>
           ^---------^

**Comment by lacygoill** [comment]
> It turns out that it's `repeat()`, but it's not obvious.

Sorry, I completely misunderstood the issue.  It's not `repeat()` which is buggy.  It's the `..=` assignment operator:
```vim
vim9script
var s: string
s ..= 123
echo 'no error'
```
    no error
```vim
vim9script
def Func()
    var s: string
    s ..= 123
enddef
Func()
```
    E1012: Type mismatch; expected string but got number

This is inconsistent, but I don't know which of these snippets need to be fixed.
One could argue that the first one is OK, because we can concatenate a string with a simple type like a number:
```vim
vim9script
echo 'string' .. 123
```
    string123

**Comment by lacygoill** [comment]
> Sorry, I completely misunderstood the issue.

It would have helped a lot if the error message had clearly stated who expected a number but got a string.  Here, it was actually `..=`; not `repeat()`.

**Comment by brammool** [comment]
> **Describe the bug**
> 
> In Vim9 script, passing a number as first argument to `repeat()` is accepted at the script level, but not in compiled code, which is inconsistent.
> 
> **To Reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(cat <<'EOF'
>         vim9script
>         var s: string
>         s ..= repeat(0, 3)
>     EOF
>     )
> 
> No error is given.
> 
> Now, run this other shell command:
> 
>     vim -Nu NONE -S <(cat <<'EOF'
>         vim9script
>         def Func()
>           var s: string
>           s ..= repeat(0, 3)
>         enddef
>         defcompile
>     EOF
>     )
> 
> `E1012` is given:
> 
>     E1012: Type mismatch; expected string but got number
> 
> **Expected behavior**
> 
> To be consistent, either the first command should give an error, or
> the second one should not complain.

The repeat() function is tolerant, if the first argument is a number it
is used like a string.  Perhaps for Vim9 we should change this?  Might
lead to unexpected errors when converting code to Vim9.

> **Environment**
> 
>  - Vim version: 8.2 Included patches: 1-3249
>  - OS: Ubuntu 20.04.2 LTS
>  - Terminal: XTerm(353)
> 
> **Additional context**
> 
> The error message lacks some context:
> ```vim
> vim9script
> def Func()
>   var s: string
>   s ..= repeat(0, strlen(s))
> enddef
> defcompile
> ```
>     E1012: Type mismatch; expected string but got number
> 
> Who expected a string but got a number? `strlen()`?  `repeat()`?  `..=`?
> It turns out that it's `repeat()`, but it's not obvious.
> 
> Also, since the error is in an argument, why doesn't the message start with `Argument 1:`:
> 
>     E1012: Argument 1: Type mismatch; expected string but got number
>            ^---------^
> 
> Just like here:
> ```vim
> vim9script
> def Func()
>     strlen({})
> enddef
> defcompile
> ```
>     E1013: Argument 1: type mismatch, expected string but got dict<unknown>
>            ^---------^

The error is not with the argument but with the return type.  It is
assumed to be equal to the type of the first argument, but with a number
a string is returned.

-- 
A successful man is one who makes more money than his wife can spend.
A successful woman is one who can find such a man.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
>    > It turns out that it's `repeat()`, but it's not obvious.
> 
> Sorry, I completely misunderstood the issue.  It's not `repeat()` which is buggy.  It's the `..=` assignment operator:
> ```vim
> vim9script
> var s: string
> s ..= 123
> echo 'no error'
> ```
>     no error
> ```vim
> vim9script
> def Func()
>     var s: string
>     s ..= 123
> enddef
> Func()
> ```
>     E1012: Type mismatch; expected string but got number
> 
> This is inconsistent, but I don't know which of these snippets need to be fixed.
> One could argue that the first one is OK, because we can concatenate a string with a simple type like a number:
> ```vim
> vim9script
> echo 'string' .. 123
> ```
>     string123

When using ".." separately it does accept a number.  The idea is that
using ".." is a strong indication the left and right should be strings.
If you then have a number, we automatically convert it to a string.
This is convenient for things like:

	echo 'the result is ' .. count

While it's unlikely this is a mistake that goes unnoticed.

Thus the problem is with "..=" not accepting a string in a :def
function.  Oh, and at script level "s ..= true" doesn't work, while it
does in a :def function.

-- 
GALAHAD: No, please.  Please! I can defeat them!  There's only a hundred.
GIRLS:   He will beat us easily.  We haven't a chance.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
