### ISSUE TITLE
Vim9: partial to builtin function requires extra arguments incorrectly

### ISSUE THREAD

**Issue by obcat** [vim/vim#8667]
**Describe the bug**

In Vim9 script, we cannot call a partial to a builtin function because it requires extra arguments incorrectly.

**To Reproduce**

1. Run `vim --clean`.

1. Source this script:

    ```vim
    vim9script
    var Partial = function('repeat', ['o'])
    echo Partial(5)
    ```

    This error is raised from line 3:

    ```
    E119: Not enough arguments for function: repeat
    ```

**Expected behavior**

No error is raised. `ooooo` is echo'ed.

**Environment**

 - Vim 8.2.3249
 - macOS Catalina (version 10.15.7)
 - iTerm2

**Comment by brammool** [comment]
> **Describe the bug**
> 
> In Vim9 script, we cannot call a partial to a builtin function because it requires extra arguments incorrectly.
> 
> 
> **To Reproduce**
> 
> 1. Run `vim --clean`.
> 
> 1. Source this script:
> 
>     ```vim
>     vim9script
>     var Func = function('repeat', ['o'])
>     echo Func(5)
>     ```
> 
>     This error is raised from line 3:
> 
>     ```
>     E119: Not enough arguments for function: repeat
>     ```
> 
> 
> **Expected behavior**
> 
> No error is raised. `ooooo` is echo'ed.

I actually have it crash.  But this problem persists when fixing that.

-- 
   An extraordinary TALL KNIGHT in all black (possibly John with Mike on his
   shoulders) walks out from the dark trees.  He is extremely fierce and
   gruesome countenance.  He walks towards KING ARTHUR and PATSY, who are
   wazzing like mad.  (Salopian slang, meaning very scared.  almost to the
   point of wetting oneself, e.g. before an important football match or
   prior to a postering.  Salopian slang meaning a beating by the school
   praeposters.  Sorry about the Salopian slant to this stage direction - Ed.)
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by obcat** [comment]
Thank you for the fix! I can now see the olympic rings `ooooo` ;)
