### ISSUE TITLE
e# to return to previous file with cursor position intact

### ISSUE THREAD

**Issue by ericcurtin** [vim/vim#8673]
There is a plugin I maintain that is used to switch between header and implementation files, say a .c file and a .h file. Common use case is change a function signature in one file and then change in the other, just as an example. I simply use `e#` to switch back to the previous file in the plugin as it's nice and fast.

https://github.com/ericcurtin/CurtineIncSw.vim/issues/16

Is there a version of `e#` that preserves cursor position in the previous file?

**Comment by ericcurtin** [comment]
I observe that when I call e# manually/interactively it does preserve cursor position. But in the script (it's a small script if you want to take a peak less than 50 lines), it doesn't reserve cursor position. Can this be solved?

**Comment by chrisbra** [comment]
are you using an autocommand to switch? Try adding the `nested` parameter.

**Comment by lacygoill** [comment]
> I simply use e# to switch back to the previous file in the plugin as it's nice and fast.

No, you just use `:e`.  You can check this by adding a breakpoint in your function:

    breakadd func CurtineIncSw

Then use your mapping, and execute the debugging command `n` (short for `next`) to step through the code.

This test fails:

    if exists("b:previous_file") && b:previous_file == l:next_file

As a result, `:e#` is not executed.  Instead, a simple `:e` is executed:

    exe "e " l:result

I guess this is why the cursor position is not preserved.

As a suggestion, here is a patch (untested):
```diff
diff --git a/plugin/CurtineIncSw.vim b/plugin/CurtineIncSw.vim
index 66c5d3b..97a424f 100644
--- a/plugin/CurtineIncSw.vim
+++ b/plugin/CurtineIncSw.vim
@@ -23,7 +23,11 @@ function! CurtineIncSw()
     let l:result = substitute(system(l:cmd), '\n', '', '')
 
     if filereadable(l:result)
-      exe "e " l:result
+      if l:result == fnamemodify(bufname('#'), ':p')
+        e#
+      else
+        exe "e " l:result
+      endif
     endif
   endif
 endfun
```
If that's not enough, you might need to save and restore the cursor position, possibly via `getcurpos()` and `setpos()`, or `winsaveview()` and `winrestview()`.  Have also a look at `:help restore-cursor` (although, not quite what you want, but you might still borrow some code/idea from it).

**Comment by ericcurtin** [comment]
Correct, thanks @lacygoill didn't know how to use vimscript debugger until now :smile:

**Comment by brammool** [comment]
> I observe that when I call e# manually/interactively it does preserve
> cursor position. But in the script (it's a small script if you want to
> take a peak less than 50 lines), it doesn't reserve cursor position.
> Can this be solved?

I suspect autocommands are not triggered.  Try this after ":e #":

	doau BufWinEnter

-- 
From "know your smileys":
 (\___/)
 (+'.'+)    Bunny
 (")_(")

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
