### ISSUE TITLE
Vim9: all <expr> mappings get disabled when 'indentexpr' gives error from legacy function in try conditional

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8677]
**Describe the bug**

In Vim9 script, if an error is encountered while running a legacy function called from a try conditional executed in a Vim9 function to evaluate `'indentexpr'` while `'debug'` is set to `throw`, all the `<expr>` mappings get broken (as well as the statusline if the latter is set by evaluating a function).

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        set debug=throw
        setlocal indentexpr=g:IndentExpr()
        def g:IndentExpr(): number
          try
            Legacy()
          finally
          endtry
          return -1
        enddef
        function Legacy()
          eval [][0]
        endfunction
        nnoremap <expr> j JK('j')
        nnoremap <expr> k JK('k')
        def g:JK(key: string): string
            return key
        enddef
        ['aaa', 'bbb', 'ccc']->setline(1)
        feedkeys('==')
    EOF
    )

No error is given.

Now, press `j` and `k` to move the cursor up and down: the cursor does not move.

**Expected behavior**

This error is given:

    E684: list index out of range: 0

Because `feedkeys('==')` causes Vim to evaluate `g:IndentExpr()`, which – in the end – runs:

    eval [][0]

After the error, pressing `j` and `k` causes the cursor to move up and down, thanks to these `<expr>` mappings:

    nnoremap <expr> j JK('j')
    nnoremap <expr> k JK('k')
    def g:JK(key: string): string
        return key
    enddef

**Environment**

 - Vim version: 8.2 Included patches: 1-3249
 - OS: Ubuntu 20.04.2 LTS
 - Terminal: XTerm(353)

**Additional context**

If we unset `'debug'`, the `<expr>` mappings are no longer broken, but `eval [][0]` still doesn't give any error:
```vim
vim9script
setlocal indentexpr=g:IndentExpr()
def g:IndentExpr(): number
  try
    Legacy()
  finally
  endtry
  return -1
enddef
function Legacy()
  eval [][0]
endfunction
nnoremap <expr> j JK('j')
nnoremap <expr> k JK('k')
def g:JK(key: string): string
    return key
enddef
['aaa', 'bbb', 'ccc']->setline(1)
feedkeys('==')
```

---

The issue disappears if we remove the try conditional:
```vim
vim9script
set debug=throw
setlocal indentexpr=g:IndentExpr()
def g:IndentExpr(): number
  Legacy()
  return -1
enddef
function Legacy()
  eval [][0]
endfunction
nnoremap <expr> j JK('j')
nnoremap <expr> k JK('k')
def g:JK(key: string): string
    return key
enddef
['aaa', 'bbb', 'ccc']->setline(1)
feedkeys('==')
```
    E684: list index out of range: 0

Notice that this time, an error is correctly given, and the `<expr>` mappings keep working.

---

If the status line evaluates a function to get its contents:

    set statusline=%!g:Stl()

The latter gets temporarily broken; instead of printing its usual text, it prints the name of the function itself:
```vim
vim9script
set debug=throw
set laststatus=2 statusline=%!g:Stl()
def g:Stl(): string
    return 'some text'
enddef
setlocal indentexpr=g:IndentExpr()
def g:IndentExpr(): number
  try
    Legacy()
  finally
  endtry
  return -1
enddef
function Legacy()
  eval [][0]
endfunction
nnoremap <expr> j JK('j')
nnoremap <expr> k JK('k')
def g:JK(key: string): string
    return key
enddef
['aaa', 'bbb', 'ccc']->setline(1)
feedkeys('==')
```
Here, notice that the status line prints:

    g:Stl()

Instead, it should print:

    some text

It gets fixed as soon as we enter the command-line.

**Comment by brammool** [comment]
This is very tricky stuff.  For 'indentexpr' the error is normally suppressed, but by setting 'debug' it's displayed anyway,   But then the try/catch tries to suppress it again...

I'll make a patch, please give it a try.  I won't even attempt making a test for this.
