### ISSUE TITLE
Feature Request: Create an autocmd event for when the current working directory changes

### ISSUE THREAD

**Issue by still-dreaming-1** [vim/vim#868]
The current working directory changing is very significant for my desired workflow. It would be really helpful to have an autocmd event for when Vim's current working directory changes that could be tied into.

Here is an example where I think this would be useful. vim-fugitive uses the VimEnter event for a special case where it uses the current working directory instead of the current file. However, if the user then changes the current working directory before editing a file, I don't know of any way for either the plugin author or a user to make vim-fugitive reference the current directory as an additional special case where there is no current file. The creator of vim-fugitive says that a good autocmd for this is what is missing in order for him to add that feature: https://github.com/tpope/vim-fugitive/issues/45

Another example where this would be useful would be if you wanted to automatically change NERDTree's root directory to match Vim's current working directory.

**Comment by Cimbali** [comment]
This can be closed no? The feature is implemented in b7407d3, and the PR #888 related to this issue is closed as well

**Comment by k-takata** [comment]
Closing.
