### ISSUE TITLE
Wrong horizontal position for first vertical motion when setting virtualedit=all after moving to end with $

### ISSUE THREAD

**Issue by neightchan** [vim/vim#8680]
When virtualedit=all, vertical movement with j (or k) from the end of a long line should increment (or decrement) the cursor's row number and keep the cursor's column number the same.  However, if the cursor has been moved to the end of the line _before_ setting virtualedit=all, the next vertical movement with j (or k) will result in the cursor being at the end of the moved-to line rather than at the same column number as before.

**To Reproduce**
1. Run `vim --clean`.
2. Insert the following two lines:
```
asdf
asdfasdf
```
3. Move the cursor to the beginning of the second line.
4. Press `$` to move to the end of the line.
5. Type `:set virtualedit=all`.
6. Type `k` to move to the first line.

Actual:
The cursor is now on the last character of the first line.

Expected:
The cursor should be on the "eighth character" of the first line.

NOTE: The expected behavior can be seen if virtualedit is enabled _before_ moving to the end of the line.

**Environment (please complete the following information):**
```
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12)
macOS version - x86_64
Included patches: 1-2750
```
OS: macOS 11.4 (20F71)
Terminal Alacritty

**Additional context**
The problem was corroborated by folks on libera#vim using newer versions of vim.

**Comment by habamax** [comment]
I can confirm with
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul 31 2021 17:51:39)
Included patches: 1-3255 
```

**Comment by brammool** [comment]
Is this really a problem?  This depends on how you look at it.  Without 'virtualedit' set the "$" command moves to the end of the line, and sticks there when moving up or down.  With 'virtualedit' set it sticks to that specific column.  So should setting 'virtualedit' change the meaning of the previous command?

**Comment by habamax** [comment]
> With 'virtualedit' set it sticks to that specific column. So should setting 'virtualedit' change the meaning of the previous command?

Not really that big problem I guess, but it doesn't stick to it:
![vim-ve-issue-1](https://user-images.githubusercontent.com/234774/127749352-6e91301c-e696-4733-a792-013825361130.gif)

**Comment by habamax** [comment]
Or do you mean with $ cursor sticks to the end of line and `ve=all` doesn't change it? Then I would assume "stick" to be in place for all following j/k not only the first one.

**Comment by neightchan** [comment]
If I'm understanding right, you're explaining the current behavior as follows:
(1) `$` without virtualedit set means "move to the special end-of-line column"
(2) `$` with virtualedit set means "move to the last numeric column"
Maybe it's even implemented this way.  Looking at it from this angle, changing the column from the special end-of-line column to the last numeric column could be thought of as a weird thing to do when setting virtualedit.

On the other hand, setting virtualedit seems like a request from the user to vim to start thinking entirely in terms of numeric columns rather than in terms of columns that are relative to a line.  From that angle, it would make a great deal of sense to "flatten out" the special end-of-line column to the last numeric column when setting virtualedit.

The current behavior becomes harder to explain when you notice that after changing rows the first time, the column does get "flattened out" to the last numeric column.  So jk from a long line to a short line and then back lands you in the middle of the row.

**Comment by brammool** [comment]
The column to move to is set when moving the cursor.  Setting the 'virtualedit' option (or resetting it) does not have an immediate effect.
Consider this, use "$" to move the cursor, then set 'virtualedit' to "all", then make it empty again.  What should happen now?  If setting the option to "all" would have changed the column to use, then clearing it would restore the old behavior?  You can see that this is very complicated.  So let's not change this.

**Comment by neightchan** [comment]
Another way to fix this would be to check virtualedit during vertical motion and do the column flattening/fixup at that point.  Considering that the column changes to a numeric column at this point anyway, but to the wrong one (the number of characters in the moved-to line rather than in the moved-from line), this sort of thing seems already to be happening . And it addresses your use case of toggling virtualedit on and off too.
