### ISSUE TITLE
Vim9: crash when disassembling function after clearing script-local variable via buffer reload

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8683]
**Describe the bug**

In Vim9 script, disassembling a function after reloading its script makes Vim crash, if it tries to access a script-local variable which has been cleared but not redefined because of an anti-reinclusion guard.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        var lines =<< trim END
            vim9script
            if exists('g:Func')
              finish
            endif
            var name: any
            def g:Func(): number
              g:name = name
              return 0
            enddef
        END
        lines->writefile('/tmp/crash.vim')
        source /tmp/crash.vim
        Func()
        source /tmp/crash.vim
        disassemble Func
    EOF
    )

Vim crashes.

**Expected behavior**

Vim doesn't crash.

**Environment**

 - Vim version: 8.2 Included patches: 1-3263
 - OS: Ubuntu 20.04.2 LTS
 - Terminal: XTerm(353)

**Additional context**

- [backtrace](https://github.com/vim/vim/files/6912207/backtrace.txt)
- [valgrind log](https://github.com/vim/vim/files/6912208/valgrind.log)
- [asan log](https://github.com/vim/vim/files/6912206/asan.log)

---

According to asan, there is a runtime error on line 4950 in `src/vim9execute.c`:

    member access within null pointer of type 'struct svar_T'

That is this line:

    smsg("%s%4d LOADSCRIPT %s-%d from %s", pfx, current,

For more context, it is included inside this block:

    case ISN_LOADSCRIPT:
        {
            scriptref_T	*sref = iptr->isn_arg.script.scriptref;
            scriptitem_T *si = SCRIPT_ITEM(sref->sref_sid);
            svar_T *sv = ((svar_T *)si->sn_var_vals.ga_data)
                                                      + sref->sref_idx;

            smsg("%s%4d LOADSCRIPT %s-%d from %s", pfx, current,
                                    sv->sv_name,
                                    sref->sref_idx,
                                    si->sn_name);
        }
        break;

**Comment by lacygoill** [comment]
No need for `Func()` to return anything.  Slightly simplified MWE:
```vim
vim9script
var lines =<< trim END
    vim9script
    if exists('g:Func')
      finish
    endif
    var name: any
    def g:Func()
      g:name = name
    enddef
END
lines->writefile('/tmp/crash.vim')
source /tmp/crash.vim
Func()
source /tmp/crash.vim
disassemble Func
```

**Comment by lacygoill** [comment]
Something else looks weird.  I have a similar code where a function is correctly compiled, then after a buffer reload, it's no longer compiled; and no error is given (probably because it's used for `'indentexpr'`).

I'll try to make more tests once this crash is fixed.

**Comment by lacygoill** [comment]
> Something else looks weird.

Ah no, that's not weird.  When the function tries to access the script-local variable which no longer exists, Vim probably changes the state of the function from "compiled" to "not compiled".  A bit unexpected, but OK, that might make sense.

**Comment by lacygoill** [comment]
Why does the global function still consider the script-local variable as deleted even if we move the latter *before* the anti-reinclusion guard?
```vim
vim9script
var lines =<< trim END
    vim9script
    var name: any
    if exists('g:Func')
      finish
    endif
    def g:Func()
      g:name = name
    enddef
    defcompile
END
lines->writefile('/tmp/s.vim')
source /tmp/s.vim
source /tmp/s.vim
filter /deleted/ disassemble Func
```
    0 LOADSCRIPT [deleted] from /tmp/s.vim
                 ^-------^

Reloading the script clears the variable, but it also redefines the latter.  Why does `g:Func()` fail to see the redefined variable?

**Comment by lacygoill** [comment]
I guess there is some link between `g:Func()` and `name` which is broken by the reload, and which can't be fixed simply by re-defining the variable.

**Comment by brammool** [comment]
> Why does the global function still consider the script-local variable
> as deleted even if we move the latter *before* the anti-reinclusion
> guard?
> ```vim
> vim9script
> var lines =<< trim END
>     vim9script
>     var name: any
>     if exists('g:Func')
>       finish
>     endif
>     def g:Func()
>       g:name = name
>     enddef
>     defcompile
> END
> lines->writefile('/tmp/s.vim')
> source /tmp/s.vim
> source /tmp/s.vim
> filter /deleted/ disassemble Func
> ```
>     0 LOADSCRIPT [deleted] from /tmp/s.vim
>                  ^-------^
> 
> Reloading the script clears the variable, but it also redefines the
> latter.  Why does `g:Func()` fail to see the redefined variable?

When reloading the script the order of declarations might be different.
The sequence number is used in the compiled function, to make access
fast.  Therefore a function compiled with an older version of the script
might have the wrong index.  In other words: everything from the last
time the script was sourced is gone.

The whole "bailing out halfway" isn't really a good thing for Vim9
scripts.  You should use "vim9script noclear" if you need to.  Or
better: use imports or the autoload mechanism.  Then Vim takes care of
loading things only once.

-- 
You had connectors?  Eeee, when I were a lad we 'ad to carry the
bits between the computer and the terminal with a spoon...

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> The whole "bailing out halfway" isn't really a good thing for Vim9
> scripts.  You should use "vim9script noclear" if you need to.  Or
> better: use imports or the autoload mechanism.  Then Vim takes care of
> loading things only once.

I completely agree.  But I'm trying to rewrite the default Vim indent plugin which does this:

    if exists("*GetVimIndent")
      finish
    endif

https://github.com/vim/vim/blob/1321257317b7d28228a6a9a0d612f81f70290b4c/runtime/indent/vim.vim#L19-L21

Not sure if it would be OK to autoload `GetVimIndent` in a `runtime/autoload/vim.vim` script.
Otherwise, yes, `noclear` fixes the issue entirely.

**Comment by lacygoill** [comment]
> Not sure if it would be OK to autoload GetVimIndent in a runtime/autoload/vim.vim script.

Actually, an import script would be cleaner (in a new `$VIMRUNTIME/import/vim.vim` script).  That's assuming that nobody relies on `GetVimIndent()` being publicly accessible...

**Comment by brammool** [comment]
> > Not sure if it would be OK to autoload GetVimIndent in a
> > runtime/autoload/vim.vim script.
> 
> Actually, an import script would be cleaner (in a new
> `$VIMRUNTIME/import/vim.vim` script).  That's assuming that nobody
> relies on `GetVimIndent()` being publicly accessible...

Originally autoload was intented for this, and several plugins use it.

There might indeed be plugins (under the user's "after" directory) that
rely on GetVimIndent().  You can also define a public GetVimIndent()
function that calls the imported function, besides using the imported
function directly for 'indentexpr'.

Which reminds me that when 'indentexpr' is set to just call a function
and that function is compiled we should be able to avoid a lot of
overhead.


-- 
You were lucky to have a LAKE! There were a hundred and sixty of
us living in a small shoebox in the middle of the road.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
