### ISSUE TITLE
Vim9: cannot compile code which runs on the condition some Vim option exists

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8688]
**Describe the bug**

In Vim9 script, we cannot compile a code which runs on the condition that some Vim option exists.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            if exists('+newoption')
                if &newoption == 'some value'
                endif
            endif
        enddef
        defcompile
    EOF
    )

`E113` is given:

    E113: Unknown option: newoption

**Expected behavior**

No error is given.  If `'newoption'` does not exist, an error is given at runtime, but not before.

**Environment**

 - Vim version: 8.2 Included patches: 1-3273
 - OS: Ubuntu 20.04.2 LTS
 - Terminal: XTerm(353)

**Additional context**

No issue at the script level:
```vim
vim9script
if exists('+newoption')
    if &newoption == 'some value'
    endif
endif
echo 'no error'
```
    no error

**Comment by lacygoill** [comment]
If this is working as intended (i.e. we want to keep the check at compile time), then we might want to document the pitfall (the code works fine in legacy), and suggest `eval()` as a workaround:
```vim
vim9script
def Func()
    if exists('+newoption')
        if eval('&newoption') == 'some value'
        endif
    endif
enddef
defcompile
echo 'no error'
```
    no error

**Comment by brammool** [comment]
We can evaluate some exists() arguments at compile time, if they are string constants.
I'll add this for option names, let me know if there are others that could be checked at compile time.

**Comment by lacygoill** [comment]
I didn't find any other string giving undesirable errors.  Closing the issue because it was fixed in patch [8.2.3276](https://github.com/vim/vim/releases/tag/v8.2.3276).

**Comment by lacygoill** [comment]
Sorry, I didn't test properly.  So, there *might* be 3 problematic cases.

Variable name, user command, builtin functions.
```vim
vim9script
def Func()
    if exists('name')
        eval name + 0
    endif
enddef
defcompile
```
    E1001: Variable not found: name
```vim
vim9script
def Func()
    if exists(':UserCommand') == 2
        UserCommand
    endif
enddef
defcompile
```
    E476: Invalid command: UserCommand
```vim
vim9script
def Func()
    if exists(':builtin_command') == 2
        builtin_command
    endif
enddef
defcompile
```
    E476: Invalid command: builtin_command
```vim
vim9script
def Func()
    if exists('*UserFunc')
        UserFunc()
    endif
enddef
defcompile
```
    E117: Unknown function: UserFunc
```vim
vim9script
def Func()
    if exists('*builtin_func')
        builtin_func()
    endif
enddef
defcompile
```
    E117: Unknown function: builtin_func

Not sure about variable names; it might already be documented and working as intended:

   > Note: In a compiled |:def| function local variables and
   > arguments are not visible to `exists()`.

   > The `exists()` function does not work on local variables or arguments.  These
   > are visible at compile time only, not at runtime.

Same thing for Ex commands:

   > Compilation will fail when encountering a user command that has not been
   > created yet.  In this case you can call `execute()` to invoke it at runtime. >
   >         def MyFunc()
   >           execute('DefinedLater')
   >         enddef

But then, the help might need to be updated, because the issue is not limited to user commands; it also affects the builtin ones.

As for functions, I don't know.  I couldn't find a relevant help section.  But there exists a workaround which might be worth documenting.  `call()`:
```vim
vim9script
def Func()
    if exists('*builtin_func')
        call('builtin_func', [])
    endif
enddef
defcompile
```
    no error

**Comment by brammool** [comment]
> Sorry, I didn't test properly.  So, there *might* be 3 problematic cases.
> 
> Variable name, user command, builtin functions.
> ```vim
> vim9script
> def Func()
>     if exists('name')
>         eval name + 0
>     endif
> enddef
> defcompile
> ```
>     E1001: Variable not found: name

I can make this work at compile time.  However, a side effect is that it
will no longer work at runtime:

   def Func()
     g:someVar = 1
     if exists('g:someVar')
	 echo 'not executed, g:someVar does not exist at compile time'
     endif
   enddef

So either one way to the other won't work as expected.  A workaround for
compile time is using eval():

   def Func()
     g:someVar = 1
     if eval("exists('g:someVar')")
	 echo 'not executed, g:someVar does not exist at compile time'
     endif
   enddef

But that is rather messy.

> ```vim
> vim9script
> def Func()
>     if exists(':UserCommand') == 2
>         UserCommand
>     endif
> enddef
> defcompile
> ```
>     E476: Invalid command: UserCommand
> ```vim
> vim9script
> def Func()
>     if exists(':builtin_command') == 2
>         builtin_command
>     endif
> enddef
> defcompile
> ```
>     E476: Invalid command: builtin_command
> ```vim
> vim9script
> def Func()
>     if exists('*UserFunc')
>         UserFunc()
>     endif
> enddef
> defcompile
> ```
>     E117: Unknown function: UserFunc
> ```vim
> vim9script
> def Func()
>     if exists('*builtin_func')
>         builtin_func()
>     endif
> enddef
> defcompile
> ```
>     E117: Unknown function: builtin_func

Defining a user command or a function inside the :def function is much
less likely, thus these seem useful.


-- 
CUSTOMER:     Well, can you hang around a couple of minutes?  He won't be
              long.
MORTICIAN:    Naaah, I got to go on to Robinson's -- they've lost nine today.
CUSTOMER:     Well, when is your next round?
MORTICIAN:    Thursday.
DEAD PERSON:  I think I'll go for a walk.
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
I have added the compile time check for user commands.  However, it doesn't seem right to do part of it at runtime and part at compile time.  For the has() function this works, because features normally don't change.  For exists() it might work for options, but most other things can change.

I think the best solution is to add a new exists() function that will always be handed at compile time.  That takes away the guessing.  Not sure what to call this.  exists_compiled() is a bit long.

**Comment by lacygoill** [comment]
> Not sure what to call this. exists_compiled() is a bit long.

FWIW, I would move `compiled` before `exists` so that – in the future – it can be used as a kind of namespace for other possible future functions:

    compiled_exists()
    compiled_foo()
    compiled_bar()
    ...

If losing in readability is not a concern, we could make it shorter using something like `ct` (for Compile Time):

    ct_exists()
    ct_foo()
    ct_bar()
    ...

**Comment by brammool** [comment]
>    > Not sure what to call this. exists_compiled() is a bit long.
> 
> FWIW, I would move `compiled` before `exists` so that – in the future – it can be used as a kind of namespace for other possible future functions:
> 
>     compiled_exists()
>     compiled_foo()
>     compiled_bar()
>     ...
> 
> If losing in readability is not a concern, we could make it shorter using something like `ct` (for Compile Time):
> 
>     ct_exists()
>     ct_foo()
>     ct_bar()
>     ...

I think the relation with exists() is stronger than the chance of later
having other "compiled" functions.  It is good that the appear next to
each other in sorted function lists.

If needed we could add different arguments to compiled_exists().
Although it might make it less predictable.

-- 
"It's so simple to be wise.  Just think of something stupid to say
and then don't say it."        -- Sam Levenson

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
