### ISSUE TITLE
Vim9: ":doautocmd" gets broken after error is given from timer + ":noautocmd"

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8690]
**Describe the bug**

In Vim9 script, `:doautocmd` gets broken after an error is given by a command executed with the `:noautocmd` modifier and from a timer.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        autocmd CursorHold * copen
        timer_start(0, (_) => {
            noautocmd eval [][0]
        })
        timer_start(100, (_) => {
            doautocmd CursorHold
        })
    EOF
    )

`E684` is given:

    E684: list index out of range: 0

This is expected.

This message is printed:

    No matching autocommands

This is NOT expected.

**Expected behavior**

After pressing Enter to get rid of the expected error, the quickfix window is opened, thanks to this autocmd:

    autocmd CursorHold * copen

**Environment**

 - Vim version: 8.2 Included patches: 1-3273
 - OS: Ubuntu 20.04.2 LTS
 - Terminal: XTerm(353)

**Additional context**

The issue disappears if the command giving the error is executed without the `:noautocmd` modifier:
```vim
vim9script
autocmd CursorHold * copen
timer_start(0, (_) => {
    eval [][0]
})
timer_start(100, (_) => {
    doautocmd CursorHold
})
```
    the quickfix window is open (after pressing Enter to clear the hit-enter prompt)

It also disappears if we reduce the second timer down to a certain point (somewhere between 5 and 10ms on my machine).

**Comment by lacygoill** [comment]
Actually, it has nothing to do with Vim9.  I can reproduce in legacy too:
```vim
autocmd CursorHold * copen
call timer_start(0, {-> Error()})
call timer_start(100, {-> Doautocmd()})
function Error()
    noautocmd eval [][0]
endfunction
function Doautocmd()
    doautocmd CursorHold
endfunction
```

**Comment by brammool** [comment]
> **Describe the bug**
> 
> In Vim9 script, `:doautocmd` gets broken after an error is given by a
> command executed with the `:noautocmd` modifier and from a timer.

It's not really broken, it's because autocommands are not executed when
handling an error.

> **To Reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(cat <<'EOF'
>         vim9script
>         autocmd CursorHold * copen
>         timer_start(0, (_) => {
>             noautocmd eval [][0]
>         })
>         timer_start(100, (_) => {
>             doautocmd CursorHold
>         })
>     EOF
>     )
> 
> `E684` is given:
> 
>     E684: list index out of range: 0
> 
> This is expected.
> 
> This message is printed:
> 
>     No matching autocommands
> 
> This is NOT expected.

We should not print this message when the autocommands were not executed
because of an error, that is confusing.

I can fix this, but it's not easy to write a test for this.

It would be clearer if the argument was included in the message.

> **Expected behavior**
> 
> After pressing Enter to get rid of the expected error, the quickfix
> window is opened, thanks to this autocmd:
> 
>     autocmd CursorHold * copen
> 
> **Environment**
> 
>  - Vim version: 8.2 Included patches: 1-3273
>  - OS: Ubuntu 20.04.2 LTS
>  - Terminal: XTerm(353)
> 
> **Additional context**
> 
> The issue disappears if the command giving the error is executed without the `:noautocmd` modifier:
> ```vim
> vim9script
> autocmd CursorHold * copen
> timer_start(0, (_) => {
>     eval [][0]
> })
> timer_start(100, (_) => {
>     doautocmd CursorHold
> })
> ```
>     the quickfix window is open (after pressing Enter to clear the hit-enter prompt)
> 
> It also disappears if we reduce the second timer down to a certain
> point (somewhere between 5 and 10ms on my machine).


-- 
WOMAN:   King of the who?
ARTHUR:  The Britons.
WOMAN:   Who are the Britons?
ARTHUR:  Well, we all are. we're all Britons and I am your king.
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Shane-XB-Qian** [comment]
this should be related to one of your 'todo' : 

```
":doau SomeEvent" gives "No matching autocommands".  This message doesn't give
a hint about how to fix it. (#4300)
```

// now looks it is a more readable msg. todo done.
