### ISSUE TITLE
Where to put pythonthreehome and pythonthreedll?

### ISSUE THREAD

**Issue by hungpham3112** [vim/vim#8692]
I install python use msys2 in window but i don't know how to put the path to vim
here is my vim `--version`:
![image](https://user-images.githubusercontent.com/75968004/127948972-95475a9c-f03f-4825-a111-332079ef1600.png)

Here is where i install `python3`:
![image](https://user-images.githubusercontent.com/75968004/127949184-bfeb8835-5956-489f-85d4-700f12387326.png)

And `python3 dll`
![image](https://user-images.githubusercontent.com/75968004/127949424-e4a5f9db-c964-4ac1-9478-aeab3987a1d1.png)

Vimrc config:
![image](https://user-images.githubusercontent.com/75968004/127949499-aab512a9-7acb-4ebc-8091-241e09abf5e4.png)
I change `vimrc` but it not work

I use python for run python-formatter  [https://vimawesome.com/plugin/vim-autoformat](url)
It raises this issue
![image](https://user-images.githubusercontent.com/75968004/127949754-be735042-88e4-4cc3-9b2d-dcbe4b44a7be.png)

But my vim8.2 has python support ???
I don't know what is happening?
Thanks for your help !!!

**Comment by k-takata** [comment]
It looks that you are using an executable from vim-win32-installer which is compiled against the official python 3.9. It is not intended to be combined with the msys2 python. So, please install the official python 3.9.
Even though, if you want to use with the msys2 python, use the python in `C:\msys64\mingw64`, not in `C:\msys64\usr`. In that case, `'pythonthreedll'` should point `libpython3.9.dll`. I don't remember about `'pythonthreehome'`, at least it should point a directory, not `python3.exe`.

BTW, this is not a right place to ask user questions. Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim.

**Comment by fqbqrr9** [comment]
There is also the problem of Chinese windows path recognition , Which errorly recogny Chinese 936 code into Japanese code.
