### ISSUE TITLE
Channel callbacks not called during BufEnter after window close

### ISSUE THREAD

**Issue by tpope** [vim/vim#8697]
**Describe the bug**

[v8.2.1948](https://github.com/vim/vim/releases/tag/v8.2.1948), which prevents handling messages during a window close, also prevents handling messages in subsequent autocommand events like `BufEnter`. This patch appears to remedy the problem while still preserving the intended behavior of the original change:

```diff
diff --git i/src/window.c w/src/window.c
index 8e5d3de26..df98d5d93 100644
--- i/src/window.c
+++ w/src/window.c
@@ -2651,6 +2651,9 @@ win_close(win_T *win, int free_buf)
 	win_equal(curwin, curwin->w_frame->fr_parent == win_frame, dir);
     else
 	win_comp_pos();
+#ifdef MESSAGE_QUEUE
+    --dont_parse_messages;
+#endif
     if (close_curwin)
     {
 	win_enter_ext(wp, FALSE, TRUE, FALSE, TRUE, TRUE);
@@ -2660,9 +2663,6 @@ win_close(win_T *win, int free_buf)
     }
 
     --split_disallowed;
-#ifdef MESSAGE_QUEUE
-    --dont_parse_messages;
-#endif
 
     /*
      * If last window has a status line now and we don't want one,
```

**To Reproduce**

Save this to a `.vim` file and `:source` it:
```vim
augroup bufenterjob
  autocmd!
  autocmd BufEnter /tmp/bufenterjob call s:Trigger()
augroup END

function s:Trigger() abort
  let queue = []
  let job = job_start(['date'], {'callback': { j, d -> add(queue, d) }})
  while empty(queue)
    sleep! 10m
  endwhile
endfunction

only
split /tmp/bufenterjob
wincmd p
redraw
close
```

**Expected behavior**

The file `/tmp/bufenterjob` is opened, and the previously opened window is closed without hanging and requiring `CTRL-C`.

**Environment (please complete the following information):**
 - Vim version 8.2.3281
 - OS: Ubuntu 21.04
 - Terminal: GUI, rxvt-unicode

**Comment by brammool** [comment]
Hmm, but I think the decrement should be after win_enter_ext(), otherwise some state might be wrong.
But autocommands are also triggered in that function.
Thus we would have to do it halfway that function.  Let's first refactor to pass flags instead of a bunch of boolean, so that it's easier to understand.
