### ISSUE TITLE
Vim9: "v:exception" does not include name of executed command in compiled try/catch

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8698]
**Describe the bug**

In Vim9 script, when an error is caught in a compiled try/catch, `v:exception` fails to include the name of the executed command.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            try
                eval [][0]
            catch
                assert_exception('eval')
            endtry
        enddef
        Func()
        echo v:errors
    EOF
    )

`v:errors` contains this string item:

    ['...function <SNR>1_Func line 4: Expected ''eval'' but got ''Vim:E684: list index out of range: 0''']

**Expected behavior**

`v:errors` is empty.

**Environment**

 - Vim version: 8.2 Included patches: 1-3281
 - OS: Ubuntu 20.04.2 LTS
 - Terminal: XTerm(353)

**Additional context**

If the code is run at the script level, `v:exception` correctly contains the name of the executed command:
```vim
vim9script
try
    eval [][0]
catch
    assert_exception('eval')
endtry
echo v:errors
```
    []

---

Same thing if the code is run from a legacy function:
```vim
vim9script
function EvalError()
    eval [][0]
endfunction
try
    EvalError()
catch
    assert_exception('eval')
endtry
echo v:errors
```
    []

**Comment by lacygoill** [comment]
> Same thing if the code is run from a legacy function:

Well obviously, since the code is run at the script level.  What is interesting is that the behavior persists even when the code is compiled:
```vim
vim9script
function EvalError()
    eval [][0]
endfunction
def Func()
    try
        EvalError()
    catch
        assert_exception('eval')
    endtry
enddef
Func()
echo v:errors
```
    []

**Comment by brammool** [comment]
When an expression is compiled the command is not available. Keeping this as a context for a possible error or exception would add overhead, which isn't justified.

**Comment by lacygoill** [comment]
OK, but – for reference – [this breaks a test in the minpac plugin](https://github.com/k-takata/minpac/blob/6cf985065aaeba4c9943c80e9aee61a1b86c1fad/test/test_minpac.vim#L101):

    try
      call minpac#add('k-takata/minpac', {'type': 'foo'})
    catch
      call assert_exception('echoerr')
    endtry

As a workaround, we need to give the error from a legacy function (or maybe rewrite the test in a different way).

**Comment by lacygoill** [comment]
> breaks a test in the minpac plugin

I mean it breaks the test when we rewrite the plugin in Vim9.

**Comment by lacygoill** [comment]
> Keeping this as a context for a possible error or exception would add overhead, which isn't justified.

Understood.  Performance is certainly more important here.
