### ISSUE TITLE
Vim9: cannot add integer to script-local float variable

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8703]
**Describe the bug**

In Vim9 script, we cannot add an integer – in compiled code – to a script-local float variable.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        var f: float
        def Func()
            f += 1
        enddef
        defcompile
    EOF
    )

`E1012` is given:

    E1012: Type mismatch; expected float but got number

**Expected behavior**

No error is given.

**Environment**

 - Vim version: 8.2 Included patches: 1-3290
 - OS: Ubuntu 20.04.2 LTS
 - Terminal: XTerm(353)

**Additional context**

The patch [8.2.3278](https://github.com/vim/vim/releases/tag/v8.2.3278) fixed a similar issue, but only for a function-local variable; not a script-local one.

---

No issue if the incrementation is performed at the script level:
```vim
vim9script
var f: float
f += 1
echo 'no error'
```
    no error

---

Same issue with `-=`, `++` and `--`:
```vim
vim9script
var f: float
def Func()
    f -= 1
enddef
defcompile
```
    E1012: Type mismatch; expected float but got number
```vim
vim9script
var f: float
def Func()
    ++f
enddef
defcompile
```
    E1012: Type mismatch; expected float but got number
```vim
vim9script
var f: float
def Func()
    --f
enddef
defcompile
```
    E1012: Type mismatch; expected float but got number

**Comment by lacygoill** [comment]
> we cannot add an integer – in compiled code – to a script-local variable.

Actually, we can:
```vim
vim9script
var f: float
def Func()
    f = f + 1
enddef
defcompile
```
The issue is limited to `+=`.

**Comment by lacygoill** [comment]
Unrelated, but there is a nice syntax which lets us make big integer numbers more readable, by including quotes:
```vim
vim9script
var BIG_INTEGER = 1'234'567
```
But it doesn't work with floats:
```vim
vim9script
var BIG_FLOAT = 1'234'567.0
```
    E488: Trailing characters: .0
```vim
vim9script
def Func()
    var BIG_FLOAT = 1'234'567.0
enddef
defcompile
```
    E1229: Expected dictionary for using key "0", but got number

Could we support this syntax for floats?  If not, could we get better error messages?  Something like:

    E1234: Can only use quotes in integers, not floats

**Comment by brammool** [comment]
> Unrelated, but there is a nice syntax which lets us make big integer
> numbers more readable, by including quotes:
> ```vim
> vim9script
> var BIG_INTEGER = 1'234'567
> ```
> But it doesn't work with floats:
> ```vim
> vim9script
> var BIG_FLOAT = 1'234'567.0
> ```
>     E488: Trailing characters: .0
> ```vim
> vim9script
> def Func()
>     var BIG_FLOAT = 1'234'567.0
> enddef
> defcompile
> ```
>     E1229: Expected dictionary for using key "0", but got number
> 
> Could we support this syntax for floats?  If not, could we get better
> error messages?  Something like:
> 
>     E1234: Can only use quotes in integers, not floats

It seems useful, especialy for money:  var usd = 12'345'678.00

Please create a separate issue for this feature request.


-- 
DEAD PERSON:  I'm getting better!
CUSTOMER:     No, you're not -- you'll be stone dead in a moment.
MORTICIAN:    Oh, I can't take him like that -- it's against regulations.
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
