### ISSUE TITLE
Enter _ (underscore) in very magic search string freezes gVim

### ISSUE THREAD

**Issue by fatjing** [vim/vim#8704]
Enter the underscore character in search mode freezes gVim

**To Reproduce**
1. Open gVim
2. Press `/` to enter search mode
3. Type `\v_`
4. gVim freezes

**Environment:**
 - Vim version: 8.2.3290
 - OS: Windows 10 2004, 19041.1110

**Additional context**
_vimrc has three lines:
```
set ignorecase
set smartcase
set incsearch
```

**Comment by lacygoill** [comment]
MWE:

    vim -Nu NONE +'set ignorecase smartcase incsearch | call feedkeys("/\\v_")'

---

Regression introduced in [8.2.3265](https://github.com/vim/vim/releases/tag/v8.2.3265).

---

Backtrace:

    #0  utfc_ptr2len (p=0x55d8551c0822 "_") at mbyte.c:2114
    #1  0x000055d8534e1130 in pat_has_uppercase (pat=0x55d8551c0820 "\\v_") at search.c:442
    #2  0x000055d8534e109f in ignorecase_opt (pat=0x55d8551c0820 "\\v_", ic_in=1, scs=1) at search.c:420
    #3  0x000055d8534e1045 in ignorecase (pat=0x55d8551c0820 "\\v_") at search.c:407
    #4  0x000055d8534e0a43 in search_regcomp
        (pat=0x55d8551c0820 "\\v_", pat_save=0, pat_use=2, options=1024, regmatch=0x7ffcddaefb00) at search.c:203
    #5  0x000055d8534e1822 in searchit
        (win=0x55d85516a0e0, buf=0x55d85516c800, pos=0x7ffcddaefd40, end_pos=0x0, dir=1, pat=0x55d8551c0820 "\\v_", count=1, options=3200, pat_use=2, extra_arg=0x7ffcddaefe50) at search.c:672
    #6  0x000055d8534e359b in do_search
        (oap=0x0, dirc=47, search_delim=47, pat=0x55d8551c0823 "", count=1, options=3216, sia=0x7ffcddaefe50)
        at search.c:1564
    #7  0x000055d8533b998e in may_do_incsearch_highlighting (firstc=47, count=1, is_state=0x7ffcddaeffb0)
        at ex_getln.c:500
    #8  0x000055d8533bd35b in getcmdline_int (firstc=47, count=1, indent=0, clear_ccline=1) at ex_getln.c:2394
    #9  0x000055d8533bb85d in getcmdline (firstc=47, count=1, indent=0, do_concat=1) at ex_getln.c:1556
    #10 0x000055d85344f9f8 in nv_search (cap=0x7ffcddaf0150) at normal.c:4336
    #11 0x000055d853449a24 in normal_cmd (oap=0x7ffcddaf01f0, toplevel=1) at normal.c:1099
    #12 0x000055d853608e70 in main_loop (cmdwin=0, noexmode=0) at main.c:1501
    #13 0x000055d85360813e in vim_main2 () at main.c:878
    #14 0x000055d85360783d in main (argc=4, argv=0x7ffcddaf03f8) at main.c:425

---

cc @chrisbra via https://github.com/vim/vim/pull/8682

**Comment by chrisbra** [comment]
wow, what a bad record. Fixing 1 bug, introducing two new ones 🙈 

fix should be in #8707
