### ISSUE TITLE
:command output is not aligned

### ISSUE THREAD

**Issue by ghost** [vim/vim#871]
When you type `:command`, when the command names are long, the formatting is not pretty. It does a partial job of tabularizing but that fails when the names are big. Is it possible to either remove alignments and just show it normally or do some logic to format it correctly depend on the max length size?

`uc_list` function in [ex_docmd.c](https://github.com/vim/vim/blob/master/src/ex_docmd.c#L5873) handles this. Please let me know if you have feedbacks on the PR.

I created a PR https://github.com/vim/vim/pull/876 if it helps. If you have an alterative suggestion please let me know. If you see the `:function` output you will notice that it is clean. I think `:command` should also follow the suit.

**Comment by lacygoill** [comment]
Did the patch [8.1.1860](https://github.com/vim/vim/commit/63d0dad874e6f949c18dd2b3c8c14d59cad58062) help in any way?

**Comment by ghost** [comment]
Yes, it did! I will close this issue.Thanks @lacygoill .

**Comment by lacygoill** [comment]
Since the issue was fixed, then this todo item is no longer relevant:

https://github.com/vim/vim/blob/21829c5f2c86cd525c8468121b4fc54c5d75bf6e/runtime/doc/todo.txt#L1567-L1569
