### ISSUE TITLE
[Question] `packadd` in mapping

### ISSUE THREAD

**Issue by bruhtus** [vim/vim#8720]
I have been wondering, is it safe to add `packadd` in a mapping?

Let's say I have `ThePlugin` at `pack/*/opt/ThePlugin` directory because I don't need it at startup but I have a mapping for one of `ThePlugin` command. Rather than doing `packadd ThePlugin` and then pressing my mapping, can I put the `packadd ThePlugin` inside my mapping? Here's an example mapping:
```vim
nnoremap <leader>n :packadd ThePlugin <Bar> PluginCommand<CR>
```
and let's say I use those mapping multiple times, is it gonna load `ThePlugin` multiple times too? or maybe it depends on the plugin author to implement `if exists('g:loaded_the_plugin') | finish | endif` so that `ThePlugin` only loaded once?

Thank you.

**Comment by lacygoill** [comment]
> can I put the packadd ThePlugin inside my mapping?

Yes, you can.

   > let's say I use those mapping multiple times, is it gonna load ThePlugin multiple times too?

Yes, you can check yourself by temporarily increasing the verbosity level with `:verbose`:

    :2verbose packadd ThePlugin

You should see something like:

    sourcing "/home/user/.vim/pack/mine/opt/ThePlugin/plugin/ThePlugin.vim"
    finished sourcing /home/user/.vim/pack/mine/opt/ThePlugin/plugin/ThePlugin.vim

   > maybe it depends on the plugin author to implement if exists('g:loaded_the_plugin') | finish | endif

Yes, usually plugin authors write an anti-reinclusion guard at the top of the plugin which would be useful here.

---

For more questions, visit the [google mailing list](https://groups.google.com/g/vim_use), the [irc channel](https://www.vi-improved.org/), or [vi.stackexchange.com](https://vi.stackexchange.com/).

**Comment by lacygoill** [comment]
BTW, instead of running `:packadd` on every keypress, first test the existence of the command:

    nnoremap <leader>n :execute (!exists(':PluginCommand') == 2 ? 'packadd ThePlugin | ' : '') .. 'PluginCommand'<CR>

**Comment by bruhtus** [comment]
> Yes, you can check yourself by temporarily increasing the verbosity level with :verbose

So, it can be dangerous to use `packadd` in mapping, especially if the plugin author not using anti-reinclusion?

> BTW, instead of running :packadd on every keypress, first test the existence of the command

That is what I was thinking at first, I just want to be sure if it was safe to use `:packadd` directly in mapping or maybe I need some kind of condition to use `:packadd` in mapping. I need to figure out how to use `:verbose` command in mapping first.

**Comment by lacygoill** [comment]
> So, it can be dangerous to use packadd in mapping, especially if the plugin author not using anti-reinclusion?

Yes, for example, if the plugin installs an autocmd but doesn't wrap it inside a self-clearing augroup:

    autocmd BufEnter * call SomeFunc()

Every time you press your mapping, a duplicate autocmd will be installed; as a result, `SomeFunc()` will be called as many times as you pressed the mapping, on every single `BufEnter` event.  If it is an expensive function, it can slow down Vim noticeably.

> I need to figure out how to use :verbose command in mapping first.

No, you need `:help exists()`.  Maybe the previous code was not clear enough:

    nnoremap <leader>n :call MyFunc()<CR>
    function MyFunc()
        if exists(':PluginCommand') != 2
            packadd ThePlugin
        endif
        PluginCommand
    endfunction

**Comment by bruhtus** [comment]
> No, you need :help exists(). Maybe the previous code was not clear enough

Sorry, I mean I need to figure out how to see the message like this:
```
sourcing "/home/user/.vim/pack/mine/opt/ThePlugin/plugin/ThePlugin.vim"
finished sourcing /home/user/.vim/pack/mine/opt/ThePlugin/plugin/ThePlugin.vim
```
which I forgot that I can just use `:messages`

> Yes, for example, if the plugin installs an autocmd but doesn't wrap it inside a self-clearing augroup

I already test it out, and it indeed sourcing the plugin again and can be dangerous for the user. Thank you for clarifying that, I think I'm gonna close this issue.
