### ISSUE TITLE
setcmdpos() appends '0' character to command line

### ISSUE THREAD

**Issue by noscript** [vim/vim#8722]
**Describe the bug**
When using `setcmdpos()` there a zero (`0`) character appended at the end of the line or after the cursor, depending if `|c_CTRL-R_=|` or `|c_CTRL-R_CTRL-R|` is used.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean -g`.
2. Press `:` and type `hello world` on the command line without hitting `<Enter>`.
3. Set the cursor to position `2` by pressing `<C-R>` twice and type `=setcmdpos(2)` and hit `<Enter>`.

**Expected behavior**
`_` (underscore) denotes the cursor position:
```
:h_ello world
```

**Actual behavior**
```
:h_ello world0
```

**Environment**
 - Vim 8.2.3187
 - OS: Ubuntu 20.04
 - Terminal: GUI

**Comment by lacygoill** [comment]
The 0 is the return value of the function.  You can eliminate it with `[-1]` or `->slice(0, 0)`:

    setcmdpos(2)[-1]
    setcmdpos(2)->slice(0, 0)

**Comment by noscript** [comment]
Thanks @lacygoill , that works. It's worth noting this in documentation to `setcmdpos()`.

**Comment by brammool** [comment]
I'll add an example to the help.
