### ISSUE TITLE
Plugin auto-pairs not working in Vim in Windows Subsystem for Linux 2 (wsl2)

### ISSUE THREAD

**Issue by comiluv** [vim/vim#8726]
**Describe the bug**
Vim plugin [auto-pairs](https://github.com/jiangmiao/auto-pairs) doesn't work when used in vim running in wsl2

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Press M-p few times to ensure auto-pairs plugin is active and enabled
2. Type ""SomeTextThatNeedsToBeWrapped
3. Position cursor between ""s like "|"
4. Press M-e
5. Nothing happens

**Expected behavior**
SomeTextThatNeedsToBeWrapped is automatically wrapped, like below:
"SomeTextThatNeedsToBeWrapped"

**Screenshots**
Same plugin works in win32 version of vim, Powershell Core, Windows 10
![inpwsh](https://user-images.githubusercontent.com/19642705/128597268-ff473a96-d32b-4863-a2f3-fdbcfbb47dfc.gif)

Same plugin also works in gVim, Windows 10
![ingvim](https://user-images.githubusercontent.com/19642705/128597279-c3e84b6e-6511-4393-9c5a-806dd824a129.gif)

in Ubuntu, wsl2, doesn't work:
![inubuntu](https://user-images.githubusercontent.com/19642705/128597293-676f4c5a-f0cc-42b6-9627-508e61a278aa.gif)

**Environment (please complete the following information):**
 - Vim version 8.1.2269
 - OS: Ubuntu 20.04 LTS via wsl2, Windows 10 21H2
 - Terminal: bash and zsh both in Windows Terminal
 - Auto-pairs plugin: https://github.com/jiangmiao/auto-pairs

**Additional context**
Also discussed this problem in https://github.com/jiangmiao/auto-pairs/issues/331

**Comment by chrisbra** [comment]
so what exactly is the problem here? Is it, that the terminal does not recognize the `<M-e>`? Can you reproduce this problem with a minimal example without an external plugin?

**Comment by lacygoill** [comment]
> I had to add below lines in .vimrc to map alt key combination to M- modifier, as described in this stackoverflow answer
   >
   > if has('unix')
   >     map <Esc>e <M-e>
   >     map <Esc>p <M-p>
   >     map <Esc>n <M-n>
   >     map <Esc>b <M-b>
   >     map <Esc>j <M-j>
   >     map <Esc>k <M-k>
   > endif

That's wrong.  It should be:

    if has('unix')
        execute "set <M-e>=\<Esc>e"
        execute "set <M-p>=\<Esc>p"
        execute "set <M-n>=\<Esc>n"
        execute "set <M-b>=\<Esc>b"
        execute "set <M-j>=\<Esc>j"
        execute "set <M-k>=\<Esc>k"
    endif

If it doesn't work.  Try this instead:

    if has('unix')
        execute "set <F31>=\<Esc>e"
        execute "set <F32>=\<Esc>p"
        execute "set <F33>=\<Esc>n"
        execute "set <F34>=\<Esc>b"
        execute "set <F35>=\<Esc>j"
        execute "set <F36>=\<Esc>k"
    endif

Then, in your mappings, instead of writing `<M-e>`, write `<F31>`.  Instead of `<M-p>`, write `<F32>`, etc.

For more info, see [this](https://github.com/lacygoill/wiki/blob/master/vim/mapping.md#how-to-use-a-chord-with-the-meta-modifier-in-my-mappings).

**Comment by lacygoill** [comment]
BTW, you don't need to do anything for meta chords to work OOTB if you use a terminal which supports the modifyOtherKeys feature (like xterm or iterm).  No idea about terminals on Windows.

Relevant help tags:

   - [:help :map-alt-keys](https://vimhelp.org/map.txt.html#%3Amap-alt-keys)
   - [:help modifyOtherKeys](https://vimhelp.org/map.txt.html#modifyOtherKeys)

**Comment by comiluv** [comment]
> > I had to add below lines in .vimrc to map alt key combination to M- modifier, as described in this stackoverflow answer
> > if has('unix')
> > map e 
> > map p 
> > map n 
> > map b 
> > map j 
> > map k 
> > endif
> 
> That's wrong. It should be:
> 
> ```
> if has('unix')
>     execute "set <M-e>=\<Esc>e"
>     execute "set <M-p>=\<Esc>p"
>     execute "set <M-n>=\<Esc>n"
>     execute "set <M-b>=\<Esc>b"
>     execute "set <M-j>=\<Esc>j"
>     execute "set <M-k>=\<Esc>k"
> endif
> ```
> 
> If it doesn't work. Try this instead:
> 
> ```
> if has('unix')
>     execute "set <F31>=\<Esc>e"
>     execute "set <F32>=\<Esc>p"
>     execute "set <F33>=\<Esc>n"
>     execute "set <F34>=\<Esc>b"
>     execute "set <F35>=\<Esc>j"
>     execute "set <F36>=\<Esc>k"
> endif
> ```
> 
> Then, in your mappings, instead of writing `<M-e>`, write `<F31>`. Instead of `<M-p>`, write `<F32>`, etc.
> 
> For more info, see [this](https://github.com/lacygoill/wiki/blob/master/vim/mapping.md?rgh-link-date=2021-08-07T11%3A11%3A01Z#how-to-use-a-chord-with-the-meta-modifier-in-my-mappings).

 I tried your first suggestion to ```<M-e>=\<Esc>e ... ``` in .vimrc, and it solved my problem, which was surprising to me because it seemed remapping of keys was not the source of the problem as I could press Alt-p to input toggling of plugin behavior successfully with my original key remappings.
 Thank you for your help.
