### ISSUE TITLE
complete() not respecting completeopt=longest

### ISSUE THREAD

**Issue by dstein64** [vim/vim#8736]
**Describe the bug**

The `complete()` function does not respect `longest` included in `completeopt`.

**To Reproduce**

1. Run `vim --clean` (or `gvim --clean`, etc.)
2. Edit `script.vim`
3. Insert:

```vim
inoremap <f5> <c-r>=List()<cr>

function! List()
  call complete(col('.'), ['item1', 'item2', 'item3'])
  return ''
endfunction
```

4. `:source script.vim`
5. `:set completeopt=menu,longest`
6. Enter insert mode and type `F5`.

**Expected behavior**

`item` would be inserted, the longest common text of the matches, and a menu would be shown for selecting a match.

**Actual behavior**

`item1` is inserted, and a menu is shown for selecting a match.

**Environment:**
 - Vim version: 8.2.2434
 - OS: Ubuntu 21.04
 - Terminal: Konsole 20.12.3

**Comment by brammool** [comment]
The idea is that complete() gives you exactly what should be inserted, it's under control of the caller.
If the longest common text is to be used, it should be in the list.
This cannot be changed, plugins rely on it.
