### ISSUE TITLE
Vim9: :help no-eval-feature does not work

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8737]
From `:help no-eval-feature`:

   > If you do not want to abort loading the script you can use a trick, as this
   > example shows:
   >
   >         silent! while 0
   >           set history=111
   >         silent! endwhile

It doesn't work in Vim9:
```vim
vim9script
silent! while 0
  set history=111
silent! endwhile
```
    E170: Missing :endwhile

Should it?

**Comment by lacygoill** [comment]
Also, the error message is confusing.  It's better in compiled code:
```vim
vim9script
def Func()
    silent! while 0
      set history=111
    silent! endwhile
enddef
defcompile
```
    E1176: Misplaced command modifier

**Comment by brammool** [comment]
That commit was something else.
