### ISSUE TITLE
yaml: Unexpected indent in simple key: value case

### ISSUE THREAD

**Issue by taralx** [vim/vim#8740]
**Describe the bug**
After entering in a key: value entries in yaml, the next line indent is increased by shiftwidth.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Open a new yaml file.
2. Enter "a: b" and hit enter.

**Expected behavior**
Next line is equal indent.

**Environment (please complete the following information):**
 - Vim version: homebrew (8.2 1-3300)
 - OS: mac 10.15.7
 - Terminal: iTerm2

**Additional context**
The culprit is here: https://github.com/vim/vim/blob/eed9616120f60ad17d5e133f505bba5c559aee89/runtime/indent/yaml.vim#L145-L148

I suspect that final `*` is not desirable.

**Comment by chrisbra** [comment]
why do you think the `*` is not desirable?

**Comment by taralx** [comment]
Because it makes the thing do nothing. As noted in the original report, this line matches every key: value pair, not just the ones that have multi-line indications.

**Comment by brammool** [comment]
Should it be \+   (backslash-plus) instead?

**Comment by taralx** [comment]
That would make a certain amount of sense.

**Comment by brammool** [comment]
OK, let me make that change, please report again if that doesn't work.

**Comment by brammool** [comment]
Changing the "*" into "\\+" actually makes the test fail.  The indent for "value" goes missing in
```
key: something
    value
```

**Comment by taralx** [comment]
Yup, ok, so apparently the indent fixes itself after you type another :, it's just surprising when it initially indents. But still correct.

**Comment by asmka** [comment]
This problem doesn't occur in Vim 8.1. 
I confirmed diff between codes in 8.1 and 8.2.

The following fixes affect this problem.
https://github.com/vim/vim/commit/acc224064033e5cea21ef7f1eefb356ca06ff11d#diff-723cc09b2d0f8f9383c670a8846979363fbc67a741aad1aae657242b8c2667a3L56
https://github.com/vim/vim/commit/acc224064033e5cea21ef7f1eefb356ca06ff11d#diff-723cc09b2d0f8f9383c670a8846979363fbc67a741aad1aae657242b8c2667a3L65

In 8.1, process doesn't enter any `if/elseif prevline` block in GetYAMLIndent function.
In 8.2, process enters the last `elseif prevline` block in GetYAMLIndent function. (https://github.com/vim/vim/blob/master/runtime/indent/yaml.vim#L145)

@brammool
Would you please check these fixes?

**Comment by chrisbra** [comment]
can you please create a PR for that?

**Comment by asmka** [comment]
@chrisbra 
I created the PR.
(and confirmed the problem is resolved)
