### ISSUE TITLE
Vim9: cannot use "." for string concatenation in legacy function defined in Vim9 script

### ISSUE THREAD

**Issue by obcat** [vim/vim#8756]
**Describe the bug**

We cannot use single dot (`.`) for string concatenation in a legacy function defined in a Vim9 script.

**To Reproduce**

1. Run `vim -Nu NONE`.

1. `:source` this script:

    ```vim
    vim9script
    function LegacyFunc()
      echo 'con' . 'cat'
    endfunction
    LegacyFunc()
    ```

    `E15` is raised:

    ```
    E15: Invalid expression: ". 'cat'"
    ```

**Expected behavior**

No error is raised, `concat` is echo'ed.

**Environment**

 - Vim 8.2.3344
 - macOS Catalina (version 10.15.7)
 - iTerm2

**Comment by obcat** [comment]
I'm not sure if this is relevant to the issue:

- This gives `E15` as expected:

    ```vim
    vim9script
    echo 'con' . 'cat'
    ```
    
    ```
    E15: Invalid expression: ". 'cat'"
    ```

- But this does not:

    ```vim
    vim9cmd echo 'con' . 'cat'
    ```
    
    ```
    concat
    ```

Which seems inconsistent.

**Comment by obcat** [comment]
> - But this does not:
> 
>     ```vim
>     vim9cmd echo 'con' . 'cat'
>     ```
>     
>     ```
>     concat
>     ```

This is unexpected because the doc says `:vim9cmd` executes following commands using Vim9 script syntax and semantics:

```help
:vim9[cmd] {cmd}				*:vim9* *:vim9cmd*
		Execute {cmd} using Vim9 script syntax and semantics.
		Useful when typing a command and in a legacy script or
		function.
```

**Comment by brammool** [comment]
Naohiro Ono wrote:

> We cannot use single dot (`.`) for string concatenation in a legacy
> function defined in a Vim9 script.

That is expected, in a legacy function legacy syntax is used.

> I'm not sure if this is relevant to the issue:
> 
> - This gives `E15` as expected:
> 
>     ```vim
>     vim9script
>     echo 'con' . 'cat'
>     ```
>     
>     ```
>     E15: Invalid expression: ". 'cat'"
>     ```
> 
> - But this does not:
> 
>     ```vim
>     vim9cmd echo 'con' . 'cat'
>     ```
>     
>     ```
>     concat
>     ```
> 
> Which seems inconsistent.

That looks like a bug.

-- 
An indication you must be a manager:
You can explain to somebody the difference between "re-engineering",
"down-sizing", "right-sizing", and "firing people's asses".

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by obcat** [comment]
> That looks like a bug.

Thanks for fixing this.


> in a legacy function legacy syntax is used.

That's right, but in legacy syntax (legacy script) single dot can be used for string concatenation:

```vim
echo 'con' . 'cat'
```

```
concat
```

**Comment by obcat** [comment]
Same result with `:legacy`:

```vim
vim9script
legacy echo 'con' . 'cat'
```

```
E15: Invalid expression: ". 'cat'"
```

It seems `:scriptversion 4` is applied in these places:

- inside legacy functions defined in Vim9 script
- `{cmd}` in `:legacy {cmd}` in Vim9 script

```vim
vim9script
function LegacyFunc()
  echo 1'000
endfunction
LegacyFunc()
```

```
1000
```

```vim
vim9script
legacy echo 1'000
```

```
1000
```

If this is working as intended, perhaps we should mention in the help.

**Comment by obcat** [comment]
Unrelated: this error message seems a bit wrong:

```vim
legacy
```

```
E1164: vim9cmd must be followed by a command: legacy
       ^^^^^^^
```

**Comment by brammool** [comment]
Naohiro Ono wrote:

> Same result with `:legacy`:
> 
> ```vim
> vim9script
> legacy echo 'con' . 'cat'
> ```
> 
> ```
> E15: Invalid expression: ". 'cat'"
> ```
> 
> It seems `:scriptversion 4` is applied in these places:
> 
> - inside legacy functions defined in Vim9 script
> - `{cmd}` in `:legacy {cmd}` in Vim9 script
> 
> ```vim
> vim9script
> function LegacyFunc()
>   echo 1'000
> endfunction
> LegacyFunc()
> ```
> 
> ```
> 1000
> ```
> 
> ```vim
> vim9script
> legacy echo 1'000
> ```
> 
> ```
> 1000
> ```
> 
> If this is working as intended, perhaps we should mention in the help.

There are a few more places where the script version is used but there
is no check for the :legacy modifier.  Let's move the logic to a
function.  I'll try to find all places where it should be used.

-- 
Lose weight, NEVER Diet again with
                  The "Invisible Weight Loss Patch"
						(spam e-mail)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by obcat** [comment]
Oh, I completely missed this remark in vim9.txt:


```help
When using `:function` in a Vim9 script file the legacy syntax is used, with
the highest |scriptversion|.  However, this can be confusing and is therefore
discouraged.
```

Indeed, as for `:function`, it was not a bug. Sorry for this noise...
