### ISSUE TITLE
Vim9: using "g:1" can reference numbered function "1" only a few times

### ISSUE THREAD

**Issue by obcat** [vim/vim#8760]
**Describe the bug**

In Vim9 script, we can use `g:1` to reference a numbered function `1` only a few times.

**To Reproduce**

1. Run `vim -Nu NONE`.

1. `:source` this script to create numbered function `1`:

    ```vim
    let mydict = {}
    function mydict.func()
      echo self.key
    endfunction
    ```

1. `:source` this script:

    ```vim
    vim9script
    function(g:1, [], {key: 42})()
    ```

    This is echo'ed:

    ```
    42
    ```

1. `:source` this again:

    ```vim
    vim9script
    function(g:1, [], {key: 42})()
    ```

    These errors are given:

    ```
    E121: Undefined variable: g:1
    E116: Invalid arguments for function function(g:1, [], {key: 42})()
    ```

**Expected behavior**

I'm not sure, but maybe the numbered function `1` should not be referenced with `g:1`, so the former `:source` should give the same error as the latter one.

**Environment**

 - Vim 8.2.3346
 - macOS Catalina (version 10.15.7)
 - iTerm2

**Additional context**

Same for any numbered function (`2`, `3`, ...) as far as I have tested at hand.

**Comment by brammool** [comment]
> **Describe the bug**
> 
> In Vim9 script, we can use `g:1` to reference a numbered function `1` only a few times.
> 
> 
> **To Reproduce**
> 
> 1. Run `vim -Nu NONE`.
> 
> 1. `:source` this script to create numbered function `1`:
> 
>     ```vim
>     let mydict = {}
>     function mydict.func()
>       echo self.key
>     endfunction
>     ```
> 
> 1. `:source` this script:
> 
>     ```vim
>     vim9script
>     function(g:1, [], {key: 42})()
>     ```
> 
>     This is echo'ed:
> 
>     ```
>     42
>     ```
> 
> 1. `:source` this again:
> 
>     ```vim
>     vim9script
>     function(g:1, [], {key: 42})()
>     ```
> 
>     These errors are given:
> 
>     ```
>     E121: Undefined variable: g:1
>     E116: Invalid arguments for function function(g:1, [], {key: 42})()
>     ```
> 
> 
> **Expected behavior**
> 
> I'm not sure, but maybe the numbered function `1` should not be referenced with `g:1`, so the former `:source` should give the same error as the latter one.
> 
> 
> **Environment**
> 
>  - Vim 8.2.3346
>  - macOS Catalina (version 10.15.7)
>  - iTerm2
> 
> 
> **Additional context**
> 
> Same for any numbered function (`2`, `3`, ...) as far as I have tested
> at hand.

This looks like a reference counting error.  The function disappears:

	let mydict = {}
	function mydict.func()
	  echo self.key
	endfunction

	func mydict.func
	func g:1

	vim9cmd function(g:1, [], {key: 42})()

	func mydict.func
	func g:1

It should not be possible to access the function with "g:1" anyway.
Looks like legacy script allows it, we should probably disable that in
Vim9 script.


-- 
MONK: ... and the Lord spake, saying, "First shalt thou take out the Holy Pin,
      then shalt thou count to three, no more, no less.  Three shalt be the
      number thou shalt count, and the number of the counting shalt be three.
      Four shalt thou not count, neither count thou two, excepting that thou
      then proceed to three.  Five is right out.  Once the number three, being
      the third number, be reached, then lobbest thou thy Holy Hand Grenade of
      Antioch towards thou foe, who being naughty in my sight, shall snuff it.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by obcat** [comment]
@brammool Thanks for the patch.

But, yes... I'm slightly confused.
After the patch, we can consistently reference numbered function `1` with `g:1`:

```vim
let mydict = {}
function mydict.func()
  echo self.key
endfunction
vim9cmd function(g:1, [], {key: 42})()
vim9cmd function(g:1, [], {key: 42})()
vim9cmd function(g:1, [], {key: 42})()
```

```
42
42
42
```

So accessing the function `1` with `g:1` seems now legal, but it appears contradictory to this comment:

> It should not be possible to access the function with "g:1" anyway.
> Looks like legacy script allows it, we should probably disable that in
> Vim9 script.

(Addtionally I can't find the way to access the function with `g:1` in legacy script.)

Is this working as intended...?

**Comment by obcat** [comment]
> (Addtionally I can't find the way to access the function with g:1 in legacy script.)

Oh sorry... Actually it can be used for the argument of `:function` (I had only tested with other stuffs; `:echo`, `function()`, ...). Please ignore this part 🥵

**Comment by brammool** [comment]
Naohiro Ono wrote:

> @brammool Thanks for the patch.
> 
> But, yes... I'm slightly confused.
> After the patch, we can consistently reference numbered function `1`
> with `g:1`:
> 
> ```vim
> let mydict = {}
> function mydict.func()
>   echo self.key
> endfunction
> vim9cmd function(g:1, [], {key: 42})()
> vim9cmd function(g:1, [], {key: 42})()
> vim9cmd function(g:1, [], {key: 42})()
> ```
> 
> ```
> 42
> 42
> 42
> ```
> 
> So accessing the function `1` with `g:1` seems now legal, but it appears contradictory to this comment:
> 
> > It should not be possible to access the function with "g:1" anyway.
> > Looks like legacy script allows it, we should probably disable that in
> > Vim9 script.
> 
> (Addtionally I can't find the way to access the function with `g:1` in
> legacy script.)
> 
> Is this working as intended...?

Good question.  It's a bit strange to do this.  After all, how would you
know the number in the first place?  On the other hand, I was wondering
if there is any valid reason to do it anyway.  Still, I think
disallowing it in Vim9 script makes sense.  But then the test that I
added won't work anymore.


-- 
SIGFUN -- signature too funny (core dumped)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by obcat** [comment]
> Good question.  It's a bit strange to do this.  After all, how would you
know the number in the first place?  On the other hand, I was wondering
if there is any valid reason to do it anyway.  Still, I think
disallowing it in Vim9 script makes sense.  But then the test that I
added won't work anymore.

I also think disallowing this strange way in Vim9 script would be OK.

If an error occurs in a numbered function, the `<num>`ber can be found in the error message. In that case, it is useful to use `:function {<num>}` - _unlike `:function g:<num>`, this syntax is documented at `:h numbered-function`_ - to see the definition of the function. And prepending `:verbose` can find the script where the function defined. But here, I think no one would want to get a reference to a function; it is unlikely anyone will call the function directly for debugging.

**Comment by obcat** [comment]
I found another bug which is reproduced by accessing a numbered function this way.

1. Run `vim -Nu NONE`

1. `:source` this script:

    ```vim
    let mydict = {}
    function mydict.afunc()
    endfunction
    delfunction g:1
    unlet mydict
    ```

    An internal error is given:

    ```
    line    5:
    E685: Internal error: func_unref()
    ```

- Vim 8.2.3346
- macOS 10.15.7
- iTerm2

**Comment by obcat** [comment]
> - Vim 8.2.3346

https://github.com/vim/vim/issues/8760#issuecomment-904332399

Sorry, I'm on 8.2.3370.

**Comment by brammool** [comment]
It might be useful to reference a numbered function in case an error is displayed with the function number.  The legacy way was to use ":function {42}", which does not work in Vim9.  Using ":function g:42" looks a bit strange, but I can't think of a problem allowing this.
