### ISSUE TITLE
user-functions doesn't show in cmdline-completion since v8.2.3337

### ISSUE THREAD

**Issue by lixiao-t4f** [vim/vim#8765]
**Describe the bug**
When pressing `<Tab>` to complete function name, user-functions (starting with uppercase character) does not show.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. create a temporary directory as `vimfiles` (I will call it `~/vim-2` below);
2. In this directory, create a empty file (`touch empty.vim` on unix like system); create another file `file-2.vim` with the following content:
```vim
" define a dict function.
function! s:hahaha() dict
endfunction
```
3. cd to vim source code directory (I will call it `~/repos/vim` below), and build a vim binary (generate `src/vim`);
4. create a temporary vimrc: `tmp.vimrc`, with the following content:
```vim
set nocp

function! Date()
endfunction

set rtp=~/vim-2,~/repos/vim/runtime

" source order matters
source ~/vim-2/empty.vim
source ~/vim-2/file-2.vim

" this is required
let g:loaded_logiPat = 1
```

5. launch vim with: `./src/vim -u tmp.vimrc`;
6. In command line mode, press `call D<Tab>` to trigger completion.

**Expected behavior**
`Date` (as we defined in step 4) should be put in cmd line.

**Screenshots**
none.

**Environment (please complete the following information):**
 - Vim version since v8.2.3337
 - OS: tested in Alpine Linux 3.14, macOS 11.5.2
 - Terminal: tmux inside alacritty

**Additional context**
I use `git bisect` to figure out that v8.2.3337 (069f90852f1444cac50491c10dfbd339a3f9e0c8) introduces this bug.

It is rather strange to run these steps. But it is the cleanest environment I have found that will trigger the bug right now.

EDIT:
reproduce steps fix / improve.

**Comment by lixiao-tap4fun** [comment]
Sorry the reproduce step seems not to trigger the behavior. (`define user-function via command line mode`)

The following step should work:

define user-function in vimrc.

**Comment by habamax** [comment]
Can't reproduce with:

1. `vim -Nu NONE`
2. `source test.vim`
3. `:call H<tab>`

`test.vim`
```
func Hello()
endfunc
```

Although with my full config I can't get `Hello` completed...

**Comment by habamax** [comment]
This is strange, for me presence of the file `/.vim/pack/plug/start/vim-swap/plugin/swap.vim`:

```
" The vim plugin to reorder delimited items.
" Last Change: 07-Jun-2019.
" Maintainer : Masaaki Nakamura <mckn@outlook.jp>

" License    : NYSL
"              Japanese <http://www.kmonos.net/nysl/>
"              English (Unofficial) <http://www.kmonos.net/nysl/index.en.html>

if &compatible || exists("g:loaded_swap")
  finish
endif
let g:loaded_swap = 1

" keymappings
nnoremap <silent> <Plug>(swap-interactive) :<C-u>call swap#prerequisite('n')<CR>g@l
xnoremap <silent> <Plug>(swap-interactive) :<C-u>call swap#prerequisite('x')<CR>gvg@
nnoremap <silent> <Plug>(swap-prev) :<C-u>call swap#prerequisite('n', repeat([['#', '#-1']], v:count1))<CR>g@l
nnoremap <silent> <Plug>(swap-next) :<C-u>call swap#prerequisite('n', repeat([['#', '#+1']], v:count1))<CR>g@l
noremap <silent> <Plug>(swap-textobject-i) :<C-u>call swap#textobj#select('i')<CR>
noremap <silent> <Plug>(swap-textobject-a) :<C-u>call swap#textobj#select('a')<CR>

""" default keymappings
" If g:swap_no_default_key_mappings has been defined, then quit immediately.
if exists('g:swap_no_default_key_mappings') | finish | endif

nmap gs <Plug>(swap-interactive)
xmap gs <Plug>(swap-interactive)
nmap g< <Plug>(swap-prev)
nmap g> <Plug>(swap-next)
```

If I do `:finish` on the top of the file it still "influences" and I can't get function completed.

**Comment by lixiao-tap4fun** [comment]
I find an even easier reproduce step:

1. run vim with `VIMRUNTIME=/a-not-exist-dir vim -u test-vimrc.vim`;
2. try to call `:call D<Tab>` to complete function.

content of test-vimrc.vim:

```vim
set nocp

function! Date()
endfunction

set rtp=
source empty.vim
source non-empty.vim
```

empy.vim is empty. (I guess file with any content should also behave the same)

content of non-empty.vim:

```vim
function! s:a_dict_func() dict
endfunction
```

@habamax can you post the output of `:scr` in vim?

With this minimal setup, the output is:
```
  1: ~/repos/vim/tmp.vimrc
  2: ~/repos/vim/empty.vim
  3: ~/repos/vim/non-empty.vim
```

**Comment by habamax** [comment]
I can't repro it with your steps, @lixiao-tap4fun .

But I have this issue with a single and only (all others are removed) vim-swap plugin (and even with a single file from that plugin). Weird.

**Comment by habamax** [comment]
For me it looks like this:

![vim-func-issue-1](https://user-images.githubusercontent.com/234774/129714694-59d4f76b-8064-4fba-b8cc-ac8feff16b95.gif)

**Comment by lixiao-tap4fun** [comment]
I will try to share the step to build, run vim and reproduce this inside docker tomorrow (I think a clean docker container should be easy to setup for everyone).

**Comment by habamax** [comment]
> **Additional context**
> I use `git bisect` to figure out that v8.2.3337 ([069f908](https://github.com/vim/vim/commit/069f90852f1444cac50491c10dfbd339a3f9e0c8)) introduces this bug.

I have reverted this patch and all functions could be completed.

**Comment by lxhillwind** [comment]
I have verified that <https://github.com/vim/vim/issues/8765#issuecomment-900168795> is reproducable on gVim for win32 (using 32-bit installer in Windows 8.1; installer is here: <https://github.com/vim/vim-win32-installer/releases/tag/v8.2.3356>)

**Comment by obcat** [comment]
I can reproduce the issue without sourcing `empty.vim` in https://github.com/vim/vim/issues/8765#issuecomment-900168795.

1. Run `vim -Nu NONE`.

2. `:source` this script:

    ```vim
    function Date()
    endfunction
    let lines =<< END
      function s:a_dict_func() dict
      endfunction
    END
    call writefile(lines, '/tmp/s.vim')
    source /tmp/s.vim
    call feedkeys(":call D\<C-a>\<Home>\"\<CR>", 'tx')
    echo @:
    ```
    
    Actual:
    
    ```
    "call D
    ```

    Expect:
    
    ```
    "call Date()
    ```

- Vim 8.2.3358
- macOS 10.15.7
- iTerm2


- - -

When making the dictionary function global, the issue disappears:

```vim
function Date()
endfunction
let lines =<< END
  function ADictFunc() dict
  endfunction
END
call writefile(lines, '/tmp/s.vim')
source /tmp/s.vim
call feedkeys(":call D\<C-a>\<Home>\"\<CR>", 'tx')
echo @:
```

```
"call Date()
```

**Comment by lixiao-tap4fun** [comment]
Even the `writefile` can be omitted:

1. Run `vim -Nu NONE`.
2. `:source` this script:

```vim
function Date()
endfunction

function s:a_dict_func() dict
endfunction

call feedkeys(":call D\<C-a>\<Home>\"\<CR>", 'tx')
echo @:
```

will get the same result.

**Comment by obcat** [comment]
@lixiao-tap4fun Oh, you are right. Presumably that is the simplest way to reproduce.

**Comment by habamax** [comment]
So the added check `*name != NUL` somehow conflicts with dict functions.

**Comment by obcat** [comment]
I've created a pull-request #8774 that will fix this issue. I'm not sure it is a proper way though...
