### ISSUE TITLE
Vim 8.2.2825 on Windows is unable to load UTF-16 files correctly

### ISSUE THREAD

**Issue by bradenbest** [vim/vim#8771]
**Describe the bug**
Using the latest stable GVIM for windows, it is unable to reason about UTF-16 Big Endian formatted text. Codepoints above U+FFFF seem to confuse it and cause it to interpret the file as latin-1 encoding, rather than UTF16. Tested on Windows (GVim 8.2.2825, Console Vim 8.1.1) and Linux (8.1.2269). Linux version works fine, Both Windows versions choke with identical input.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run vim
2. `:set enc=utf16 fenc=utf-16be ff=unix noeol bomb`
3. Enter some basic text, e.g. "Hello World"
4. Enter a high Unicode codepoint, e.g. `^vU0001f415`
5. `:wq test`
6. `vim test`

**Actual behavior**
On Linux, the file will load just fine, showing a placeholder or a dog emoji depending on local character sets. On Windows, Vim will get confused and interpret the file as `latin-1`, causing a bunch of NUL characters to show up in the buffer. Other text editors such as notepad interpret the file just fine (as long as a BOM is present)

**Expected behavior**
Linux and Windows behavior should be consistent--vim should be able to read and decode utf-16be without defaulting to latin-1.

**Screenshots**
Here is an xxd dump of the file I tested with

    00000000: feff 0048 0065 006c 006c 006f 0020 0057  ...H.e.l.l.o. .W
    00000010: 006f 0072 006c 0064 000a d83d dc15       .o.r.l.d...=..

**Environment (please complete the following information):**
 - GVim 8.2.2825
 - OS: Windows 10 [e.g. Ubuntu 18.04, Windows 10 1809, macOS 10.14]
 - Terminal: GUI and cmd.exe, issue shows up in both.

**Additional context**
I realize that UTF-16be is an extremely rare and outdated text format (hence why it's slipped through so many cracks), but Vim is able to encode UTF-16be, so it should be able to decode it, too. My guess is that the error is related to endianness and surrogate pairs, vim is probably failing some sanity check and falling back to latin-1. Does Vim sanity-check that the host system's endianness matches the BOM's endianness before attempting to decode UTF-16?

**Comment by bradenbest** [comment]
Oh, I should note that `:set enc=utf16` does not fix it. Vim just gets more confused.

**Comment by bradenbest** [comment]
Huh, you know what? Vim chokes on utf-16le as well.

**Comment by bradenbest** [comment]
![image](https://user-images.githubusercontent.com/6936507/130023218-d5ad3921-fa92-407c-bf0f-fafe77b33375.png)

**Comment by jottkaerr** [comment]
What's the output of
```
verbose set enc? fencs? ffs?
```
after you start vim but before you load your test file?

**Comment by bradenbest** [comment]
> What's the output of
> 
> ```
> verbose set enc? fencs? ffs?
> ```
> 
> after you start vim but before you load your test file?

![image](https://user-images.githubusercontent.com/6936507/130024005-7220989b-e630-4c78-a66b-72650d45696b.png)

**Comment by bradenbest** [comment]
![image](https://user-images.githubusercontent.com/6936507/130024250-22b78560-ded2-4501-95e0-da8cd2a0d28d.png)
here it is without any vimrc

**Comment by bradenbest** [comment]
here is the same file on a linux machine:
![image](https://user-images.githubusercontent.com/6936507/130024411-aea52cf8-84b5-4a18-ac03-0a8c7bb1e897.png)
And here is vim on linux loading that file (`vim -u NONE`):
![image](https://user-images.githubusercontent.com/6936507/130024506-c80ede34-dcfc-4771-b67d-a7c3df95d0be.png)
Something is definitely wrong here 🤔

**Comment by bradenbest** [comment]
I'm headed to bed. Let me know whether you're able to reproduce, the GVim I tested it on is fresh out of the box from vim.org. I wanted to do my due diligence and make sure that I was testing on the latest stable version before I went forward with the bug report.

**Comment by bradenbest** [comment]
oh, one last thing before I go: I did test setting the parameters you asked for to match those of my linux environment. Same result.

![image](https://user-images.githubusercontent.com/6936507/130025974-200457df-bf08-4906-acf3-291006a7e6ae.png)
![image](https://user-images.githubusercontent.com/6936507/130026002-fb42faec-28e1-4d8e-8fdb-1ffaa4a04eee.png)
![image](https://user-images.githubusercontent.com/6936507/130026022-1b691ed9-e3d8-4fac-8224-2de9b8400f86.png)

Hope that helps

**Comment by jottkaerr** [comment]
Linux versions of Vim usually (always?) use UTF-8 as default for the 'encoding' option. Until recently the default value on Windows has corresponded to the current Windows ANSI code page, i.e. "latin1" was more or less "CP1252". This has changed with patch 8.2.2912. Now UTF-8 is also the default on Windows.

When 'encoding' is set to latin1, Vim might be able to correct the encoding with its heuristics configured via the 'fileencodings' option, but it cannot represent the text if it contains a non-latin1 character.

You should make sure that 'encoding' is set to utf-8 as early in your .vimrc as possible or switch to a newer version of Vim.

**Comment by jottkaerr** [comment]
%s/correct the encoding/correctly identify the encoding/

**Comment by bradenbest** [comment]
![image](https://user-images.githubusercontent.com/6936507/130026811-9c163add-2622-4b3e-bdc1-5c9906e6b62e.png)
thoughts?

**Comment by jottkaerr** [comment]
Too late. :-) "+set ..." is only executed after testutf16gen has been loaded. Better use
```
--cmd "set en=utf-8 fencs=ucs-bom,latin1 ffs=unix,dos"
```
for a test. If this works, put these commands in your _vimrc.

**Comment by bradenbest** [comment]
![image](https://user-images.githubusercontent.com/6936507/130027524-3d573abb-d27b-41fa-ba81-f2f443757838.png)
you mad genius! Please tell me that this is something vim-sensible does.

**Comment by jottkaerr** [comment]
It's the effect of the 'encoding' option having a value ("latin1" in your case) which cannot represent all characters found in the file. Vim actually did correctly identify the encoding of your test file. You can check this if you remove the dog from the second line---the file is correctly loaded, because all of the remaining characters are representable in latin1 encoding. You can even put some umlauts (like "äöüÄÖÜ") in your file, and the file would still be correctly loaded.

If you regularly work with files that must be encoded with UTF-16 (BE or LE) or UTF-8, you should make sure 'encoding' is set to utf-8 as early as possible---either by putting "set encoding=utf-8" near the start of your ~/_vimrc or by using at least Vim version 8.2.2912. (If you cannot compile Vim yourself you can find pre-compiled versions and up-to-date installers for Windows at https://github.com/vim/vim-win32-installer/releases)

**Comment by k-takata** [comment]
It looks that the issue has been solved.
