### ISSUE TITLE
Vim9: findfile() for nonexistant file returns string 

### ISSUE THREAD

**Issue by mark2185** [vim/vim#8776]
**Describe the bug**
Storing `findfile` result with a negative `count` that results in no matches into a `list< string >` raises an error, but it should not, according to the docs.
The docs (albeit for `finddir()`) say:
`When {count} is negative return all the matches in a |List|.`

And it does return an empty list when I print it, and `type( result )` gives `3`, but `vimscript9` cannot compile it.

**To Reproduce**
This code causes the error:
```
vim9script

export def Function(): void
    const variable: list< string > = findfile( 'nonexistant', '**', -1 )
enddef

defcompile
E1012: Type mismatch; expect list< string > but got string
```

**Expected behavior**
It should compile.

**Environment (please complete the following information):**
 - Vim version: 8.2, included patches 1-2891
 - OS: Arch linux 5.13.10-arch1-1
 - Terminal: Terminator v2.1.1

**Comment by brammool** [comment]
About the white space: I think it's OK to allow for white space inside the <>.  At least to me it doesn't look bad, might even make a complicated type easier to read.  The "<" character can be seen as part of the "list" type , just like we don't allow a space before the "(" in a function call: "Func(  arg  )".  Oh, actually ":call Func  ( arg )"  works, that should be an error.
