### ISSUE TITLE
Vim9: cannot pass Vim option to function via method after linebreak

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8779]
**Describe the bug**

In Vim9 script, we cannot pass a Vim option to a function via a method written after a linebreak.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        &matchpairs
            ->setline(1)
    EOF
    )

`E488` is given:

    E488: Trailing characters: matchpairs

**Expected behavior**

No error is given.  The value of `'matchpairs'` is written on the first line of the buffer:

    (:),{:},[:]

**Environment**

 - Vim version: 8.2 Included patches: 1-3360
 - OS: Ubuntu 20.04.3 LTS
 - Terminal: XTerm(353)

**Additional context**

As a workaround we can wrap the option inside parentheses to make sure Vim knows that `&matchpairs` is an expression to be evaluated:
```vim
vim9script
(&matchpairs)
    ->setline(1)
```
    (:),{:},[:]

One could infer from this snippet that everything works fine, and that we are meant to use parentheses because of the ambiguity around the `&` token.  The latter can be used as a sigil for Vim options, or as an Ex command (`:h :&`).  But no; that's not a good explanation:
```vim
vim9script
&matchpairs->setline(1)
```
    (:),{:},[:]

Notice that no error is given when we move the method before the linebreak.  If Vim is smart enough to infer that `&matchpairs` is an expression when a method follows on the same line, then it should be smart enough to come to the same conclusion when a method follows on the next line.  IOW, it should skip the linebreak.

---

Same issue in compiled code:
```vim
vim9script
def Func()
  &matchpairs
    ->setline(1)
enddef
defcompile
```
    line    2:
    E1050: Colon required before a range: ->setline(1)

Although, the error message is:

   - confusing
   - inconsistent with the one at the script level
   - given from the wrong line (*if* there is an issue, then it's on line 1; not on line 2)

**Comment by lacygoill** [comment]
Not sure whether it should be changed, but a similar issue exists with registers:
```vim
vim9script
@r = 'text'
@r->setline(1)
```
    E492: Not an editor command: text

Vim parses the token `@r` like the Ex command `:@r` instead of the string expression `@r`.
In this context, I can't see how it's useful to parse it that way.  It would make sense if we could use `:@r` as the start of a command:
```vim
vim9script
@r = 'unsilent echomsg '
@r 'TEST'
messages
```
But it doesn't work.  `TEST` has not been logged in `:messages`, which means that `@r` has not been expanded into `:echomsg`, which means that `:@r` can only be used alone.

If `:@r` is followed by something else, maybe the latter could be first parsed, instead of being immediately discarded.  And if it's a method call, `@r` could be parsed as a string then passed to the following function.

Anyway, if this is working as intended, maybe it should be documented.  As a suggestion, here is a patch:
```diff
diff --git a/runtime/doc/eval.txt b/runtime/doc/eval.txt
index db74f9c10..d469cb619 100644
--- a/runtime/doc/eval.txt
+++ b/runtime/doc/eval.txt
@@ -1485,6 +1485,9 @@ The result is the contents of the named register, as a single string.
 Newlines are inserted where required.  To get the contents of the unnamed
 register use @" or @@.  See |registers| for an explanation of the available
 registers.
+NOTE: In Vim9 script, if you want to pass the contents of a register to a
+function via a method call, using this notation, you need to surround it with
+parentheses, to prevent @r from being executed as an Ex command.
 
 When using the '=' register you get the expression itself, not what it
 evaluates to.  Use |eval()| to evaluate it.
```
---

Same issue with a number:
```vim
vim9script
123->setline(1)
```
    E1050: Colon required before a range: 123->setline(1)

Same solution:
```vim
vim9script
(123)->setline(1)
```
    123

**Comment by brammool** [comment]
> Not sure whether it should be changed, but a similar issue exists with
> registers:
> ```vim
> vim9script
> @r = 'text'
> @r->setline(1)
> ```
>     E492: Not an editor command: text
> 
> Vim parses the token ***@***.***` like the Ex command ***@***.***` instead of the
> string expression ***@***.***`.
> In this context, I can't see how it's useful to parse it that way.  It
> would make sense if we could use ***@***.***` as the start of a command:
> ```vim
> vim9script
> @r = 'unsilent echomsg '
> @r 'TEST'
> messages
> ```
> But it doesn't work.  `TEST` has not been logged in `:messages`, which
> means that ***@***.***` has not been expanded into `:echomsg`, which means
> that ***@***.***` can only be used alone.
> 
> If ***@***.***` is followed by something else, maybe the latter could be
> first parsed, instead of being immediately discarded.  And if it's a
> method call, ***@***.***` could be parsed as a string then passed to the
> following function.

I noticed this while making the changes for a line starting with
"&option".  There is a conflict: In legacy script ***@***.***" executes register
"r".  We currently do recognize ***@***.*** = expr":

	@a = 'echo "text"'
	@a

If we keep it backwards compatible, then this won't work:
	@a
		->setline(2)

We could do away with backwards compatibility and require using :exec:

	exec @a

How often would one want to execute a register with the old syntax?
Is it more surprising that ***@***.***" does not execute register "a", or is it
more surprising that ***@***.***>func()" does not work?

I would think that consistency is more important.  Since we expect ***@***.*** =
expr" to work, just like "&option = expr" and "g:var = expr" works, we
would also expect ***@***.***>func()" to work.

Not allowing ***@***.***" to execute a register and using "exe @a" instead
somehow feels the same as requiring a colon before a range.


-- 
JOHN CLEESE PLAYED: SECOND SOLDIER WITH A KEEN INTEREST IN BIRDS, LARGE MAN
                    WITH DEAD BODY, BLACK KNIGHT, MR NEWT (A VILLAGE
                    BLACKSMITH INTERESTED IN BURNING WITCHES), A QUITE
                    EXTRAORDINARILY RUDE FRENCHMAN, TIM THE WIZARD, SIR
                    LAUNCELOT
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
I would have thought that we could use a colon rather than `:execute` to express that `@r` is meant to be parsed as an Ex command; but that's not too important.

However, I'm not sure it's OK for `@r` to be silently ignored:
```vim
vim9script
@r = 'echo "text"'
@r
```
Nothing happens.  No error is given; no message is echo'ed.

For someone coming from legacy, they might expect `@r` to execute the register.  If nothing happens, this might lead to confusing issues later in the code.  Maybe we should give `E1207`:

    E1207: Expression without an effect: @r

**Comment by mg979** [comment]
@lacygoill this works for me
```
vim9script
@a = 'echo "text"'
@a
exe @a
```

it prints two times `text` on vim restart.

> We could do away with backwards compatibility and require using :exec:

@brammool 👍🏻 it's less ambiguous that way, so that one knows that `@a` is always a string.

**Comment by lacygoill** [comment]
> @lacygoill this works for me

Not for me; `text` is printed only once; not twice.  I'm on 8.2.3367.

Here is another snippet which doesn't rely on `:echo` but on incrementing a variable:
```vim
vim9script
var i = 0
@a = '++i'
@a
exe @a
echo i
```
    1

If the `@a` on line 4 had an effect, then `i` should be 2 not 1.

---

   > @brammool 👍🏻 it's less ambiguous that way, so that one knows that @a is always a string.

We can also use a leading colon:
```vim
vim9script
@a = "echo 'text'"
:@a
```
    text

**Comment by lacygoill** [comment]
We correctly get an error for alphanumeric registers:
```vim
vim9script
@r
```
    E1207: Expression without an effect: @r

But not for `@-`, `@*`, `@+`, `@/`, `@"`, `@=`:
```vim
vim9script
@-
@*
@+
@/
@"
@=
echo 'no error'
```
    no error
