### ISSUE TITLE
Vim9: ":elseif" statement wrongly skipped in debug mode

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8781]
**Describe the bug**

In Vim9 script, an `:elseif` statement is sometimes wrongly skipped in debug mode.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            var b = false
            if b
                eval 1 + 0
            elseif !b
                eval 2 + 0
            endif
        enddef
        breakadd func Func
        Func()
    EOF
    )

Press `n` then `Enter` to execute the `>next` debugging command, and jump to the `if` statement.  Do it again to jump to the `elseif` statement.

Vim stops right before the `eval 2 + 0` statement and prints this line:

    line 5: eval 2 + 0

**Expected behavior**

Vim stops right before the `elseif` statement (because `b` is false and the `if` test failed), and prints this line:

    line 4: elseif !b

**Environment**

 - Vim version: 8.2 Included patches: 1-3360
 - OS: Ubuntu 20.04.3 LTS
 - Terminal: XTerm(353)

**Additional context**

If `b` is replaced with its value (`false`), Vim does stop right before the `elseif` statement:
```vim
vim9script
def Func()
    var b = false
    if false
        eval 1 + 0
    elseif !b
        eval 2 + 0
    endif
enddef
breakadd func Func
Func()
```
    # after pressing:  n, Enter, Enter
    line 4: elseif !b

However, something else happens which is not expected.  After the first `>next`, instead of only printing the `if` statement:

    line 2: if false

Vim also prints the subsequent line:

    line 2: if false  eval 1 + 0

In fact, it joins all the lines which are going to be skipped:
```vim
vim9script
def Func()
    if false
        eval 1 + 0
        eval 2 + 0
        eval 3 + 0
    endif
enddef
breakadd func Func
Func()
```
    line 1: if false  eval 1 + 0  eval 2 + 0  eval 3 + 0  endif

Is it working as intended?  That's not what happens in legacy:
```vim
vim9script
function Func()
    if v:false
        eval 1 + 0
        eval 2 + 0
        eval 3 + 0
    endif
endfunction
breakadd func Func
Func()
```
    line 1: if v:false

**Comment by lacygoill** [comment]
The issue is fixed, but when reaching an `:if`/`elseif` statement whose test fails, Vim keeps printing all the skipped lines.  Not a big deal, but it looks a bit weird, and that's not what happens in legacy.

**Comment by brammool** [comment]
I would say this is correct, those are the lines that "next" skips over.  Whether they are comment lines or lines that are omitted because they are never executed doesn't really matter when compiling.  In real debugging you will understand what happens.  Although a condition always being false or true is rare anyway.
