### ISSUE TITLE
vimdiff yields false results

### ISSUE THREAD

**Issue by Anton-Wessel** [vim/vim#8782]
Using vim 8.1 in kubuntu 20.04 (see output of vim --version in  #attachment WEx1) to compare two long files. The result is unusable because:
1. the context lines in the two windows are different,
2. the lines markes as different are totally wrong lines,
3. in upper window the text in the first fold is false.

see screenshot in attechment WEx2.
because in the screenshot the text in the fold-line is hard to read, the text is copied into a .txt file, see WEx3.
the real difference of the two files is given by :: diff -U0
see WEx4.
greetings, Anton_Wessel@t-online.de

**Comment by tonymec** [comment]
1. I don't see any attachment.
2. How exactly do you start vimdiff? Please describe every single step so that even someone stupid could reproduce them.

**Comment by brammool** [comment]
Please use a more recent Vim, at least 8.2.  It includes xdiff, which keeps the diffs up-to-date much better.

**Comment by chrisbra** [comment]
closing, as I do not see any screenshots or reproducible examples. If you can reproduce the issue with an updated Vim, please report exact reproduction steps.

Thanks.

**Comment by Anton-Wessel** [comment]
good morning,
ticket #8782

fine that I can reply via email and can send attachments via email.

sending attachments with github seems not to work (android 10, smartphone 
Galacy S10+).
please note that the dialogs and handlings within Github are very very hard 
to use and faulty.

I have found what I intended to send.

the beginning was:

I had open the two files in vim in the upper window and in the lower window.

then I used
difft
on both windows.

on a two years old PC kubuntu 20.04   was running from a bought USB stick.

I have tried very often.
and also I have deinstalled all vim packages and reinstalled them by aptitude.
all was of no help.

my four attachments I have added now.

WEx1 is a .txt file
WEx2 is .PNG, can be viewed as image
WEx3 is .txt
WEx4 is .txt
thanks
***@***.***



=====

Am 30. August 2021 11:38:38 schrieb Christian Brabandt 
***@***.***>:

**Comment by chrisbra** [comment]
Sorry, I cannot understand the problem and there are no attachments here. 

Please try with an updated Vim first.  Also try to reproduce the case starting with `vim --clean` and mention all the commands that you run.

Also, if you find it easier, you can directly subscribe to the vim-dev mailinglist and send messages there. Attachments can be included there as well.

**Comment by Anton-Wessel** [comment]
good evening,

sending my email of today, 30.08.2021 18:24 again, all four attachments are 
attached.

thanks
***@***.***

=====


good morning,
ticket #8782

fine that I can reply via email and can send attachments via email.

sending attachments with github seems not to work (android 10, smartphone 
Galacy S10+).
please note that the dialogs and handlings within Github are very very hard 
to use and faulty.

I have found what I intended to send.

the beginning was:

I had open the two files in vim in the upper window and in the lower window.

then I used
difft
on both windows.

on a two years old PC kubuntu 20.04   was running from a bought USB stick.

I have tried very often.
and also I have deinstalled all vim packages and reinstalled them by aptitude.
all was of no help.

my four attachments I have added now.

WEx1 is a .txt file
WEx2 is .PNG, can be viewed as image
WEx3 is .txt
WEx4 is .txt
thanks
***@***.***



=====

Am 30. August 2021 11:38:38 schrieb Christian Brabandt 
***@***.***>:

**Comment by Anton-Wessel** [comment]
thank you for your email.

regarding the version of vim:

I am running kubuntu 20.04 from an USB stick which I have bought, received 
on 07.07.2021 on a PC which is about 2 years old.

In my tests I have a few times deinstalled all packages belonging to vim.

and then reinstalled via aptitude. this was of no help.
I remember perhaps that I also have worked with package manager muon.

and by this way the vim version 8.1 was, is installed.
it is not possible for me with given tools to install a newer version than 
this.

my attachment WEx1 is the total output of
vim --version


regarding my attechments:

within Github seemingly the sending of attatchmemts does not work.
though I had clicked on the respective button.

but now as I can use normal email, I send the four attachments, succsessfully.

WEx1 is a .txt file
WEx2 is .PNG, can be viewed as image
WEx3 is .txt
WEx4 is .txt

thanks, greetings, sincerely
***@***.***


=====

Am 21. August 2021 17:17:02 schrieb Bram Moolenaar ***@***.***>:

**Comment by chrisbra** [comment]
please: Either send mails (with attachments) to the vim-dev mailinglist or upload attachments using the github web interface.

In any case, please provide exact reproduction steps (and you need to verify using a self-compiled vim using the latest git-master version. 

Thanks for your understanding.

**Comment by Anton-Wessel** [comment]
I have to give up.

1.
github does not work, though I used the button for attachments, my 
attachmenets you have not received.

2.
***@***.***
and
***@***.***
the delivery subsystem has returned my email.

all is bad.

***@***.***


=====

Am 30. August 2021 22:16:13 schrieb Christian Brabandt 
***@***.***>:

**Comment by Anton-Wessel** [comment]
I have to give up.

1.
github does not work, though I used the button for attachments, my 
attachmenets you have not received.

2.
***@***.***
and
***@***.***
the delivery subsystem has returned my email.

all is bad.

***@***.***


=====

Am 30. August 2021 22:16:13 schrieb Christian Brabandt 
***@***.***>:
