### ISSUE TITLE
Builtin function to stop ins-completion without side-effects

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#8784]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

Calling `complete()` can start ins-completion, but there is no builtin function to stop ins-completion. Calling `complete(some_column, [])` closes the popup menu, but doesn't stop ins-completion. One has to press `CTRL-E` twice to insert the character below the cursor in this case.

**Describe the solution you'd like**

A builtin function to stop ins-completion.

**Comment by lacygoill** [comment]
> A command to end Insert mode completion can also be helpful, but I can't find an existing one either.

Not sure this is what you're looking for, but there is [`:help :stopinsert`](https://vimhelp.org/insert.txt.html#%3Astopinsert).

**Comment by zeertzjq** [comment]
> > A command to end Insert mode completion can also be helpful, but I can't find an existing one either.
> 
> Not sure this is what you're looking for, but there is [`:help :stopinsert`](https://vimhelp.org/insert.txt.html#%3Astopinsert).

That's stopping Insert mode, not stopping Insert mode completion.

**Comment by zeertzjq** [comment]
I just found out the following can achieve this purpose:

```vim
if mode(1) ==# 'ic'
  feedkeys("\<C-E>", 'n')
endif
```

**Comment by zeertzjq** [comment]
Reopened: `feedkeys` doesn't work in some circumstances, e.g. when `i_CTRL-V` is waiting for a key.

**Comment by lacygoill** [comment]
Maybe the `feedkeys()` workaround could be improved, but without any actual code, it's hard to make any test.

**Comment by lacygoill** [comment]
How do you start the completion?  A mapping, an autocmd, a user command, ...?
How do you want to end the completion?

> Reopened: feedkeys doesn't work in some circumstances.

Which circumstances exactly?

Post some real code showing exactly what happens currently, and what you would want to happen if the requested function existed.

Here is a start where `feedkeys()` works:

    vim9script
    inoremap <F5> <C-R>=g:ListMonths()<CR>
    inoremap <F3> <Cmd>call <SID>EndInsCompletion()<CR>
    def EndInsCompletion()
        feedkeys("\<C-E>", 'n')
    enddef
    def g:ListMonths(): string
      ['', 'the quick brown fox jumps over the lazy dog']->setline(1)
      complete(col('.'), ['January', 'February', 'March',
            'April', 'May', 'June', 'July', 'August', 'September',
            'October', 'November', 'December'])
      return ''
    enddef
    feedkeys("i\<F5>\<F3>")

Try to adapt it or create another snippet showing how it fails.

**Comment by zeertzjq** [comment]
I guess I'll just close this since the problems is only specific to a very complicated Neovim-only plugin.

**Comment by zeertzjq** [comment]
Ah, I think what I actually wanted is to stop completion without changing the match, and I guess currently there is no way to do that without inserting any extra characters. I'll open another issue later.

**Comment by lacygoill** [comment]
> what I actually wanted is to stop completion without changing the match

[`:help complete_CTRL-Y`](https://vimhelp.org/insert.txt.html#complete_CTRL-Y)

**Comment by zeertzjq** [comment]
> > what I actually wanted is to stop completion without changing the match
> 
> [`:help complete_CTRL-Y`](https://vimhelp.org/insert.txt.html#complete_CTRL-Y)

CTRL-Y inserts the whole match. I actually want this behavior, but without the "insert the typed character":
```
Any non-special character:
		  Stop completion without changing the match and insert the
		  typed character.
```

**Comment by zeertzjq** [comment]
I'll wait for #8793 first.

**Comment by zeertzjq** [comment]
Ah, `feedkeys("\<C-G>\<C-G>", 'n')` still has a problem: it doesn't trigger `CompleteDone` immediately. Changing `'n'` to `'ni'` doesn't trigger `CompleteDone` immediately either, and adding `x` doesn't stop completion at all.

Example:
1. Run `vim --clean`
2. Create autocommand `:autocmd CompleteDone * echomsg col('.')`
3. Create mapping `:inoremap <F2> <C-R>=feedkeys("\<C-G>\<C-G>", 'ni') + cursor(1, 10) ? '' : ''<CR>`
4. Press keys `i<Space>testtesttest<Home><C-X><C-V><F2><C-E><Esc>`
5. `:messages` shows `10`

In contrast:
1. Run `vim --clean`
2. Create autocommand `:autocmd CompleteDone * echomsg col('.')`
3. Create mapping `:inoremap <F2> <C-G><C-G><C-R>cursor(1, 10) ? '' : ''<CR>`
4. Press keys `i<Space>testtesttest<Home><C-X><C-V><F2><C-E><Esc>`
5. `:messages` shows `2`

**Comment by lacygoill** [comment]
Try this:
```vim
autocmd CompleteDone * echomsg col('.')
inoremap <Plug>(exit-ins-compl) <C-G><C-G>
inoremap <Plug>(after-exit) <Cmd>call cursor(1, 10)<CR>
inoremap <F2> <C-R>=feedkeys("\<Plug>(exit-ins-compl)\<Plug>(after-exit)", 'i') ? '' : ''<CR>
```

**Comment by zeertzjq** [comment]
> Try this:
> 
> ```viml
> autocmd CompleteDone * echomsg col('.')
> inoremap <Plug>(exit-ins-compl) <C-G><C-G>
> inoremap <Plug>(after-exit) <Cmd>call cursor(1, 10)<CR>
> inoremap <F2> <Cmd>call feedkeys("\<lt>Plug>(exit-ins-compl)\<lt>Plug>(after-exit)", 'i')<CR>
> ```

Ah, this seems to be a good solution.

**Comment by lacygoill** [comment]
Or this:
```vim
autocmd CompleteDone * echomsg col('.')
inoremap <Plug>(exit-ins-compl-and-move-cursor) <C-G><C-G><Cmd>call cursor(1, 10)<CR>
inoremap <F2> <Cmd>call feedkeys("\<lt>Plug>(exit-ins-compl-and-move-cursor)", 'i')<CR>
```

**Comment by zeertzjq** [comment]
Thanks!

**Comment by zeertzjq** [comment]
I have another idea: How about making `complete()` stop `ins-completion` when it accepts a negative starting column number? This is currently no-op.

**Comment by brammool** [comment]
> I have another idea: How about making `complete()` stop
> `ins-completion` when it accepts a negative starting column number?
> This is currently no-op.

If we are going to add this to the code somehow, it's better to add a
new function.  Reusing an existing function with an exotic argument just
makes it obscure.

-- 
OLD WOMAN: King of the WHO?
ARTHUR:    The Britons.
OLD WOMAN: Who are the Britons?
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
