### ISSUE TITLE
getcurpos() loses column position in visual line mode

### ISSUE THREAD

**Issue by DJMcMayhem** [vim/vim#879]
I'm using vim version 7.4.1023 on windows. Here is my vimrc:

```
function! CurPos()
  echo getcurpos()
endfunction

nnoremap <space> :<C-u>call CurPos()<cr>
xnoremap <space> :<C-u>call CurPos()<cr>
```

This prints the right column position in normal, visual, and visual block mode. However, if I enter visual line mode with `V`, it always prints `1` for the column.

**Comment by chrisbra** [comment]
that is not a bug. By the time the ex command is executed, Vim has reset the cursor position to the beginning of the visual selection, thus you are seeing column 1. I think something like this works around the problem:

``` viml
function! CurPos()
  return getcurpos()
endfunction

nnoremap <space> :<C-u>call CurPos()<cr>
xnoremap <expr> <space> ":\<C-u>echom '". string(CurPos()). "'\n"
```
