### ISSUE TITLE
cursor() and setcursorcharpos() don't stop ins-completion

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#8793]
**Describe the bug**

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean`
2. Create mapping `:inoremap <F2> <C-R>=cursor(1, 10) ? '' : ''<CR>`
3. Press keys `i<Space>testtesttest<Home><C-X><C-V><F2><C-E>`
4. The content of the buffer becomes `ttest`

**Expected behavior**
The content of the buffer becomes `! testtesttest` (`cursor()` stops ins-completion like `<Left>` and `<Right>` and the last `<C-E>` does nothing)

**Comment by brammool** [comment]
> **Describe the bug**
> 
> **To Reproduce**
> Detailed steps to reproduce the behavior:
> 1. Run `vim --clean`
> 2. Create mapping `:inoremap <F2> <C-R>=cursor(1, 10) ? '' : ''<CR>`
> 3. Press keys `i<Space>testtesttest<C-X><C-V><F2><C-E>`
> 4. The content of the buffer becomes `ttest`
> 
> **Expected behavior**
> The content of the buffer becomes `! testtesttest`

What are you trying to do?

Using cursor() here may mess up things, so be careful where the cursor
ends up.

Stopping completion when the cursor is moved is tricky, there are valid
ways to move the cursor, and when inserting text the line may wrap and
end up on the next text line.  Only stopping when the cursor moves to a
previous line is rather arbitrary.

In short: You probably need to accept how Vim works and see what you can
do with that.

-- 
How come wrong numbers are never busy?

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
