### ISSUE TITLE
RFE: Indent better when typing bullet lists in txt files

### ISSUE THREAD

**Issue by m1027** [vim/vim#8794]
vim already detects a leading dash as bullet in txt files and can reformat a bullet list nicely (visual selection + gq).

But when actually *typing in* a long line, starting with a bullet (dash) and when the line break kicks in, the second row is indented as if there was no bullet.

Desired behaviour: When the line break kicks in, the next line should (optionally) start a little more to the right, just like gq does on paragraphs with leading dahes.

**Comment by Konfekt** [comment]
With

```vim
setlocal formatlistpat=^\s*\d\+[\]:.)}\t ]\s*\\\|^\\s*[-+*]\\s\\+
" instead of the default value formatlistpat=^\s*\d\+[\]:.)}\t ]\s*
setlocal formatoptions+=n
```

the second row is indented after the line break kicks in.

**Comment by m1027** [comment]
I am super happy that there is a solution already!

I am just stumbling accross an error when applying the formatlistpat. This happens even when I try to set the default pattern!
```
:set formatlistpat=^\s*\d\+[\]:.)}\t ]\s*
E518: Unknown option: ]\s
```
I am probably missing something trivial?
I am using neovim-4.4 (in case this matters).

**Comment by Konfekt** [comment]
I missed that everything needs to be doubly escaped. Correct should be

```vim
setlocal formatlistpat=^\s*\d\+[\]:.)}\t ]\s*\\\|^\\s*[-+*]\\s\\+
```

**Comment by vim-ml** [comment]
Hi,

On Wed, Aug 25, 2021 at 4:08 AM m1027 ***@***.***> wrote:

> vim already detects a leading dash as bullet in txt files and can reformat
> a bullet list nicely (visual selection + gq).
>
> But when actually *typing in* a long line, starting with a bullet (dash)
> and when the line break kicks in, the second row is indented as if there
> was no bullet.
>
> Desired behaviour: When the line break kicks in, the next line should
> (optionally) start a little more to the right, just like gq does on
> paragraphs with leading dahes.
>
>
> You can set the 'breakindentopt' and 'formatlistpat' options to  indent
bulleted lists as described above:

    set formatlistpat=^\\s*-\\s*
    set breakindent
    set breakindentopt=list:-1

The above assumes the bulleted lists start with a "-".

- Yegappan
