### ISSUE TITLE
Showcmd Position

### ISSUE THREAD

**Issue by Dosx001** [vim/vim#8801]
I just want to change the position of the showcmd setting. Preferably, changing it from the right side to the left side. Having it on the right side while using an ultrawide is killing my neck.

If possible maybe create a menu like the ctrl+p clipboard. The menu would be displayed in the center of the screen while in Insert mode.

**Comment by luukvbaal** [comment]
It can now be placed in the command line or statusline through 'showcmdloc' and the `%S` 'statusline' item.

**Comment by gdupras** [comment]
You could try `:set showcmdloc=statusline`. The command will appear in the status line of the active window. Useful if you have vertical splits.
