### ISSUE TITLE
Vim9: execution does not stop when using ":breakadd expr" and "expr" is assigned from ":def" function

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8803]
**Describe the bug**

In Vim9 script, the execution does not stop when we set a breakpoint with `:breakadd expr`, and `expr` is assigned from a `:def` function.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        g:curfile = ''
        breakadd expr g:curfile
        def Func()
            g:curfile = @%
            eval 1 + 0
        enddef
        autocmd BufEnter * Func()
        edit foo
        edit bar
    EOF
    )

The execution doesn't stop.

**Expected behavior**

The execution does stop when the value of `g:curfile` changes from `foo` to `bar`.

**Environment**

 - Vim version: 8.2 Included patches: 1-3377
 - OS: Ubuntu 20.04.3 LTS
 - Terminal: XTerm(353)

**Additional context**

No issue when `Func()` is re-written as a legacy function:
```vim
vim9script
g:curfile = ''
breakadd expr g:curfile
function Func()
    let g:curfile = @%
    eval 1 + 0
endfunction
autocmd BufEnter * Func()
edit foo
edit bar
```
---

I suspect that there are other issues with `:breakadd expr`, not necessarily related to Vim9.  But it's hard to be sure how the command is supposed to work, because there are no examples and no tests.  It was introduced in the patch [8.0.1505](https://github.com/vim/vim/commit/c6f9f739d32084923c3031cbf6f581f8c8bf7fd2).

I'll try to make more tests once this issue is fixed.  If it can be made to work reliably, it should make debugging Vim scripts much faster.

**Comment by brammool** [comment]
A :def function needs to be compiled specifically for debugging.  That currently only happens when a breakpoint was set in the function.  When an expression breakpoint is set, all functions need to be compiled for debugging.  It's inefficient, but there is no other way.  I'll see if that can be made to work without too many changes.
