### ISSUE TITLE
Map single Ctrl key tap to ESC

### ISSUE THREAD

**Issue by funcrab** [vim/vim#8806]
This is the action I want to do

- Hold Ctrl key does not work
- Tap Ctrl alone to convert to ESC

Maybe I'm not looking hard enough, but I couldn't find a solution.
I think a lot of people would like to have this feature.
Because on modern keyboards that are not ADM3A, the ESC key is too far away.

**Comment by zeertzjq** [comment]
At Vim level this should only be possible in GUI.

**Comment by k-takata** [comment]
As already mentioned, this is basically not possible at the application level.
So closing.
