### ISSUE TITLE
fnamemodify() fails to expand ".."

### ISSUE THREAD

**Issue by matveyt** [vim/vim#8808]
Under *nix ".." is only expanded when followed by path separator:

```VimL
call assert_equal(fnamemodify("/home/./", ":p"), "/home/")               " okay
call assert_equal(fnamemodify("/home/.", ":p"), "/home/")                " okay
call assert_equal(fnamemodify("/home/../", ":p"), "/")                   " okay
call assert_equal(fnamemodify("/home/..", ":p"), "/home/../")            " fail
```

Tested with Vim 8.2.3378 on Linux. Does not occur on Windows.

**Comment by lacygoill** [comment]
Not sure it has the same cause, but a long time ago, I noticed what seemed to be a similar inconsistency with regards to how `fnamemodify()` resolved a path depending on whether the latter ended with a path separator or not:
```vim
cd /tmp
echo [fnamemodify('/tmp', ':.'), fnamemodify('/tmp/', ':.')]
```
    ['/tmp', '']

**Comment by brammool** [comment]
> Under *nix ".." is only expanded when followed by path separator:
> 
> ```VimL
> call assert_equal(fnamemodify("/home/./", ":p"), "/home/")               " okay
> call assert_equal(fnamemodify("/home/.", ":p"), "/home/")                " okay
> call assert_equal(fnamemodify("/home/../", ":p"), "/")                   " okay
> call assert_equal(fnamemodify("/home/..", ":p"), "/home/../")            " fail
> ```

The purpose of fnamemodify() is to apply modifiers to a path, it is not
intended to shorten the result.  You can use simplify() to do that.
fnamemodify() only does the basic things.

-- 
"The future's already arrived - it's just not evenly distributed yet."
		-- William Gibson

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by matveyt** [comment]
1. The difference between (3) and (4) should be seen as a bug
2. In fact I need abspath() / realpath() but Vim doesn't provide it.

**Comment by chrisbra** [comment]
so does it work if you add simplify() to it?

**Comment by matveyt** [comment]
@chrisbra It is a plugin and it is... complicated. But a bug is still a bug.
