### ISSUE TITLE
lua: How to print without saving in message history

### ISSUE THREAD

**Issue by wsdjeg** [vim/vim#8813]
in viml, we have `echo` and `echom`, but when use `:lua` command, there is only a `print()` function, which will saving text into message history.

**Comment by vim-ml** [comment]
Hi,

On Sun, Aug 29, 2021 at 12:41 AM Wang Shidong ***@***.***>
wrote:

> in viml, we have echo and echom, but when use :lua command, there is only
> a print() function, which will saving text into message history.
>
>
>
Did you try using the Vim echo command directly from lua?

    lua vim.command("echo 'Test'")

- Yegappan

**Comment by k-takata** [comment]
There is a workaround. I think this can be closed.
