### ISSUE TITLE
No completion event is triggered when popup just disappeared but completion is active

### ISSUE THREAD

**Issue by echasnovski** [vim/vim#8814]
**Describe the bug**
There is no completion event triggered when doing the following:
- Initialize completion popup.
- Type to the point when popup just disappeared after most recent character. In this case completion is still active (if delete previous character, popup reappears).

**To Reproduce**
- Create the following configuration file (for example, under 'completion-event.vim')

```vim
let g:count_changed = 0
function TrackCompleteChanged()
  let g:count_changed = g:count_changed + 1
  echo 'CompleteChanged #' . g:count_changed
endfunction

let g:count_done_pre = 0
function TrackCompleteDonePre()
  let g:count_done_pre = g:count_done_pre + 1
  echo 'CompleteDonePre #' . g:count_done_pre
endfunction

let g:count_done = 0
function TrackCompleteDone()
  let g:count_done = g:count_done + 1
  echo 'CompleteDone #' . g:count_done
endfunction

au CompleteChanged * call TrackCompleteChanged()
au CompleteDonePre * call TrackCompleteDonePre()
au CompleteDone * call TrackCompleteDone()

set nocompatible
set shortmess+=c
set noshowmode
```

- Run `vim -u completion-event.vim`.
- Type `aaa<CR>bbb<CR>`.
- Initialize complete with `<C-N>` (`CompleteChanged` is triggered).
- Empty completion suggestion with `<C-P>` (`CompleteChanged` is triggered).
- Type `a` (`CompleteChanged` is triggered) and then type `c` (**no** event is triggered).
- Type `<DEL>` to see that completion is still active (`CompleteChanged` is triggered).

**Expected behavior**
Some completion event is triggered. More intuitively, it should be `CompleteChanged` as it does trigger when no item is selected.

Maybe even more intuitive would be to stop completion at this point (and thus trigger both `CompleDonePre` and `CompleteDone`). But this is probably too drastical. Is this behavior (not stopping completion when typing one character beyond all suggestions) intentional, because I couldn't find any reference?

**Screenshots**
Gif of behavior:

![vim_complete-event](https://user-images.githubusercontent.com/24854248/131244967-69775ab2-b39a-4d55-90d8-eb15ae669859.gif)

**Environment (please complete the following information):**
 - Vim version: 8.2.2815
 - OS: Ubuntu 18.04.5
 - Terminal: GNOME Terminal

**Comment by zeertzjq** [comment]
```
						*popupmenu-keys*
In the first state these keys have a special meaning:
<BS> and CTRL-H   Delete one character, find the matches for the word before
		  the cursor.  This reduces the list of matches, often to one
		  entry, and switches to the second state.
Any non-special character:
		  Stop completion without changing the match and insert the
		  typed character.

In the second and third state these keys have a special meaning:
<BS> and CTRL-H   Delete one character, find the matches for the shorter word
		  before the cursor.  This may find more matches.
CTRL-L		  Add one character from the current match, may reduce the
		  number of matches.
any printable, non-white character:
		  Add this character and reduce the number of matches.
```

**Comment by FelipeRuizGarcia** [comment]
I think you forget to specify the Linux Distro @echasnovski

**Comment by echasnovski** [comment]
Thanks, updated.

**Comment by echasnovski** [comment]
The #13982 fixed this issue. Now `CompleteChanged` event is triggered if completion list is empty.
