### ISSUE TITLE
`call popup_create(buf_num, {})` is much much slower than `call popup_create('hello', {})`

### ISSUE THREAD

**Issue by Yggdroot** [vim/vim#8823]
**Describe the bug**
`call popup_create(buf_num, {})` is 100 times slower than `call popup_create('hello', {})`

**To Reproduce**

```vim
let buf_num = bufadd('')

let start = reltime()
call popup_create(buf_num, {})
echom reltimefloat(reltime(start))

let start = reltime()
call popup_create('hello', {})
echom reltimefloat(reltime(start))
```

Detailed steps to reproduce the behavior:
1. so %
2. :mess to see the output

**Expected behavior**
The costs are similar.

**Environment (please complete the following information):**
 - Vim version [e.g. 8.2.2282] (Or paste the result of `vim --version`.)
 - OS: Linux
 - Terminal:

**Comment by chrisbra** [comment]
I have run a similar script a hundred times: `:>timings.txt; for i in {0..100}; do ./vim --clean -c 'source popup_test.vim'; done`
The average was  0,0000638020s for your first version vs. 0,0000502376s for the second version.

Did you run it using `vim --clean`. That looks okay, I would say.

**Comment by Yggdroot** [comment]
Sorry, I did not using `vim --clean`.
I find that the issue is because `call popup_create(buf_num, {})` will trigger `BufEnter, BufWinEnter` but `call popup_create('hello', {})` won't.
