### ISSUE TITLE
html/css file opening - rgb2xterm very slow

### ISSUE THREAD

**Issue by fetchinson** [vim/vim#8825]
I'm on vim 8.2 using it from a plain xterm. When I start up html or css files the startup time is extremely slow, can be 3-4 seconds. This is the summary of the profiling log:

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
  294   1.590729   0.847627  <SNR>67_Rgb2xterm()
224910              0.743102  <SNR>67_pow()
 2599              0.032777  <SNR>67_PreviewCSSColorInLine()
  147   1.598205   0.005605  <SNR>67_SetNamedColor()
  255              0.004275  <SNR>67_Xterm2rgb()
  147              0.001871  <SNR>67_FGforBG()
    3              0.000565  <SNR>60_AddITags()
    2   0.000613   0.000549  <SNR>8_LoadFTPlugin()
    1              0.000445  <SNR>56_define_commands()
    2   3.323722   0.000407  <SNR>3_SynSet()
    1   0.000316   0.000271  <SNR>14_EchoFuncInitialize()
    2              0.000208  HtmlIndent_CheckUserSettings()
    2              0.000183  <SNR>56_Map()
    1   0.000220   0.000172  FugitiveExtractGitDir()
    1   1.665048   0.000166  dist#ft#FThtml()
    2   0.002720   0.000149  <SNR>10_LoadIndent()
    1   0.000215   0.000144  fugitive#Find()
    1   0.000184   0.000099  <SNR>56_TempReadPre()
    5              0.000091  <SNR>60_AddBlockTag()
    1   0.001002   0.000084  fugitive#Init()

So it looks like Rgb2xterm is the culprit. As I was searching around found this with more or less the same problem from about 10 years ago:

https://github.com/skammer/vim-css-color/issues/3

Since a lot has changed in the past 10 years I was wondering what I could do to cut down on the startup time.

Strange thing is that I haven't had this problem before when I was using vim 7.

Maybe the problem has to do with xterm settings and vim is perfectly fine?

**Comment by lilydjwg** [comment]
Try https://github.com/RRethy/vim-hexokinase instead and `set termguicolors`.

**Comment by fetchinson** [comment]
This requires a fully functional go-lang installation which seems a giganormous overkill.

What I'm wondering is that since there isn't a problem with other file types and those other file types also have syntax highlighting and pretty colors, probably the problem is only with vim trying to render color codes in the actual colors in html and css (and probably other file types as well). For me a perfectly fine solution would be to simply switch this feature off. How would I do that (while keeping all pretty colors and visual niceties that I enjoy with C files for example?

**Comment by chrisbra** [comment]
that version is unmaintained. Try one of the other forks (note: I also maintain a colorizer plugin). 

Note: this is not a vim issue.

**Comment by fetchinson** [comment]
I don't use any plugins other than the ones shipped by fedora.

So basically my question is this: why is loading html/css so much slower than loading c/txt/tex or anything else?

I guess it's because some extra features are switched on by default for html/css and I'd like to turn these off.

**Comment by chrisbra** [comment]
> So basically my question is this: why is loading html/css so much slower than loading c/txt/tex or anything else?

because that plugin is injecting expansive calculations into the default html/css syntax scripts. Use a different one. There exist better colorizer plugins.

**Comment by fetchinson** [comment]
Would it be possible to only alter the html/css behavior and not the rest?

**Comment by brammool** [comment]
This is a problem with a plugin, not Vim itself.  Not sure what is the best place to continue the discussion.
