### ISSUE TITLE
`gd` bug?

### ISSUE THREAD

**Issue by eggeek** [vim/vim#883]
When I used `gd` in my source code, something weird happened.
1.  use `gd` at 1st place (line 32),  it's work;
2.  use `gd` at 2nd place (line 60), it doesn't work (no response, high cpu);
3.  use `,gf` (Youcompleme: GoToDefinition), it's work;
- [source code](https://www.dropbox.com/s/hatjs75j37j4mbz/HardProof.cpp?dl=0)
- [YouTube](https://youtu.be/9SeiGIfsZh8)

In the youtube video, the vim run with plugins (because I wanna show that `,gf` is work), and If i run without plugins(using `vim -N -u NONE`),  `gd` still has same problem.

Is this a bug of `gd`? I don't know how to figure it out.
Thanks.

More information:
- system: OS X El Capitan 10.11.5 (15F34)
- vim version: 7.4.1816
- which : `vim -> ../Cellar/macvim/7.4-103/bin/vim`

**Comment by vim-ml** [comment]
Hi eggeek,

2016-6-22(Wed) 11:37:51 UTC+9 eggeek:

> When I used gd in my source code, something weird happened.
> 1.  use gd at 1st place (line 32),  it's work;
> 2.  use gd at 2nd place (line 60), it doesn't work (no response, high cpu);
> 3.  use ,gf (Youcompleme: GoToDefinition), it's work;
> 
> source code
> YouTube
> 
> In the youtube video, the vim run with plugins (because I wanna show that ,gf is work), and If i run without plugins(using vim -N -u NONE),  gd still has same problem.
> 
> Is this a bug of gd? I don't know how to figure it out.
> 
> Thanks.
> 
> More information:
> 
> system: OS X El Capitan 10.11.5 (15F34)
> vim version: 7.4.1816
> which : vim -> ../Cellar/macvim/7.4-103/bin/vim

Reported problem was fixed in Vim 7.4.1940
https://github.com/vim/vim/commit/23c60f21b07b04351d846e6fbf4f4abd9aa09345

## Thanks.

Best regards,
Hirohito Higashi (a.k.a. h_east)
