### ISSUE TITLE
Mouse scrolling partially works in Vim 8.1

### ISSUE THREAD

**Issue by jclark42796** [vim/vim#8830]
**Describe the bug**
On AWS ec2 Linux 2 instance, we started to use Vim 8.1 (ncluded patches 1-1602).  Noticed that mouse scroll up works, but mouse scroll down does not work.  Previously on Vim 8.0 (patches 1-503, 1365) does not have this issue

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean` (or `gvim --clean`, etc.)
2. Edit large enough file that allows for scrolling
3. :set mouse=a
4. Shift-G to go to bottom of file.  Scroll up and then attempt to scroll down using mouse.

**Expected behavior**
Scroll up and down should work.

**Environment (please complete the following information):**
 - Vim 8.1 (ncluded patches 1-1602)
 - OS: Windows 10 10.0.18363.1734
 - Putty 2008-01-16:r7834

**Additional context**
Not sure if this is related
https://github.com/microsoft/terminal/issues/10321

**Comment by brammool** [comment]
I very much doubt this is a Vim issue.  Anyway, version 8.1 is old and if we would make a fix it would go in 8.2.
Have you tried a recent 8.2 build?

**Comment by jclark42796** [comment]
> 
> 
> I very much doubt this is a Vim issue. Anyway, version 8.1 is old and if we would make a fix it would go in 8.2.
> Have you tried a recent 8.2 build?

Thank you for your reply.  Unfortunately, in my environment, I'm limited to version 8.1.   I've created a ticket w/ Amazon and will let you know what I find out.

Jim

**Comment by jclark42796** [comment]
Turns out this issue is due to the version of Putty I was using.  Upgrading Putty fixed the issue.
