### ISSUE TITLE
Unreachable code for `:z!` command

### ISSUE THREAD

**Issue by dpelle** [vim/vim#8832]
In `ex_cmds.c`, we have:
```
  3434     void
  3435 ex_z(exarg_T *eap)
  3436 {
  3437     char_u      *x;
  3438     long        bigness;
  3439     char_u      *kind;
  3440     int         minus = 0;
  3441     linenr_T    start, end, curs, i;
  3442     int         j;
  3443     linenr_T    lnum = eap->line2;
  3444 
  3445     // Vi compatible: ":z!" uses display height, without a count uses
  3446     // 'scroll'
  3447     if (eap->forceit)
  3448         bigness = curwin->w_height;
  ...
```
Line `ex_cmds.c:3448` is not covered with tests according to 
https://codecov.io/gh/vim/vim/src/87e1587b8add93e40340170e4261cdadc4c8940e/src/ex_cmds.c#L3448

In fact, it looks unreachable because despite the comment at line 3445
saying "Vi compatible: ":z!" uses display height [...]", the `:z` Ex command
actually does not accept the exclamation mark.

Either:
- lines 3445...3448 should be removed
-  or `EX_BANG` should be added in `ex_cmds.h` like this:
```
diff --git a/src/ex_cmds.h b/src/ex_cmds.h
index 480bf3c04..1ea74422c 100644
--- a/src/ex_cmds.h
+++ b/src/ex_cmds.h
@@ -1824,7 +1824,7 @@ EXCMD(CMD_yank,           "yank",         ex_operators,
        EX_RANGE|EX_WHOLEFOLD|EX_REGSTR|EX_COUNT|EX_TRLBAR|EX_CMDWIN|EX_LOCK_OK,
        ADDR_LINES),
 EXCMD(CMD_z,           "z",            ex_z,
-       EX_RANGE|EX_WHOLEFOLD|EX_EXTRA|EX_FLAGS|EX_TRLBAR|EX_CMDWIN|EX_LOCK_OK,
+       EX_RANGE|EX_WHOLEFOLD|EX_BANG|EX_EXTRA|EX_FLAGS|EX_TRLBAR|EX_CMDWIN|EX_LOCK_OK,
        ADDR_LINES),
 
 // commands that don't start with a letter
```
And then `:z!` should also be documented (currently ":help z!" shows no help).

I could not find evidence that Vi or Vim should support the `:z!` command.

**Environment**
 - Vim version 8.2.3397

**Comment by vim-ml** [comment]
On Do, 02 Sep 2021, Dominique Pellé wrote:

> In `ex_cmds.c`, we have:
> ```
>   3434     void
>   3435 ex_z(exarg_T *eap)
>   3436 {
>   3437     char_u      *x;
>   3438     long        bigness;
>   3439     char_u      *kind;
>   3440     int         minus = 0;
>   3441     linenr_T    start, end, curs, i;
>   3442     int         j;
>   3443     linenr_T    lnum = eap->line2;
>   3444 
>   3445     // Vi compatible: ":z!" uses display height, without a count uses
>   3446     // 'scroll'
>   3447     if (eap->forceit)
>   3448         bigness = curwin->w_height;
>   ...
> ```
> Line `ex_cmds.c:3448` is not covered with tests according to 
> https://codecov.io/gh/vim/vim/src/87e1587b8add93e40340170e4261cdadc4c8940e/src/ex_cmds.c#L3448
> 
> In fact, it looks unreachable because despite the comment at line 3445
> saying "Vi compatible: ":z!" uses display height [...]", the `:z` Ex command
> actually does not accept the exclamation mark.
> 
> Either:
> - lines 3445...3448 should be removed
> -  or `EX_BANG` should be added in `ex_cmds.h` like this:
> ```
> diff --git a/src/ex_cmds.h b/src/ex_cmds.h
> index 480bf3c04..1ea74422c 100644
> --- a/src/ex_cmds.h
> +++ b/src/ex_cmds.h
> @@ -1824,7 +1824,7 @@ EXCMD(CMD_yank,           "yank",         ex_operators,
>         EX_RANGE|EX_WHOLEFOLD|EX_REGSTR|EX_COUNT|EX_TRLBAR|EX_CMDWIN|EX_LOCK_OK,
>         ADDR_LINES),
>  EXCMD(CMD_z,           "z",            ex_z,
> -       EX_RANGE|EX_WHOLEFOLD|EX_EXTRA|EX_FLAGS|EX_TRLBAR|EX_CMDWIN|EX_LOCK_OK,
> +       EX_RANGE|EX_WHOLEFOLD|EX_BANG|EX_EXTRA|EX_FLAGS|EX_TRLBAR|EX_CMDWIN|EX_LOCK_OK,
>         ADDR_LINES),
>  
>  // commands that don't start with a letter
> ```
> And then `:z!` should also be documented (currently ":help z!" shows no help).
> 
> I could not find evidence that Vi or Vim should support the `:z!` command.

It is required by posix: 
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/ex.html#tag_20_40_13_51

So we should add the EX_BANG argument and amend the documentation.

Best,
Christian
-- 
Es ist nicht immer nötig, dass das Wahre sich verkörpere: Schon
genug, wenn es geistig umherschwebt und Übereinstimmung bewirkt, wenn
es wie Glockenton ernst-freundlich durch die Lüfte wogt.
		-- Goethe, Maximen und Reflektionen, Nr. 42

**Comment by brammool** [comment]
Taken care of by 8.2.3400.
