### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [vim/vim#8835]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by chrisbra** [comment]
See e.g. the help (:h bug-reports)

> 3. Send bug reports to: Vim Developers <vim-dev@vim.org>
>    This is a maillist, you need to become a member first and many people will
>    see the message.  If you don't want that, e.g. because it is a security
>    issue, send it to <bugs@vim.org>, this only goes to the Vim maintainer
>    (that's Bram)

.

**Comment by JamieSlome** [comment]
@chrisbra - thanks for the help!

Got an e-mail sent over to @brammool!
