### ISSUE TITLE
Updated xml.vim Syntax File

### ISSUE THREAD

**Issue by amadeus** [vim/vim#884]
I've made some changes to `xml.vim` to add some consistency. I attempted to go through the normal process of emailing the current maintainer listed on the file but he has not responded. 

The updated file is here:

https://gist.github.com/amadeus/0e9fd9e7e5ab0024ff6f81b1fbb2f952

I can open up a PR with the changes if you prefer, however I know you like to handle syntax file updates separately (or at least used too).

**The changes in summary are this:**

Currently when matching an xml tag like `<tag>`, there's a separate contained match group inside the `<` and `>` to match the actual `tag` text, the `tagName` match group. However, this ONLY applied to the opening tag, and not the closing tag. This updated file adds a match group of `tagName` to the closing tag for consistency with the opening tag.

**Comment by chrisbra** [comment]
closed as of 96f45c0b6fc9e9d404e6805593ed1e0e6795e470

**Comment by lacygoill** [comment]
Can confirm that https://github.com/vim/vim/commit/96f45c0b6fc9e9d404e6805593ed1e0e6795e470 fixes the issue.
