### ISSUE TITLE
E488 occurs when `foo()` throws an error in `:call foo().bar()`

### ISSUE THREAD

**Issue by thinca** [vim/vim#8842]
**Describe the bug**

Uses `:call` with a chained function calls(`foo().bar()`) and an error occurs in the middle, we will get E488 error instead of the error that occurred.

**To Reproduce**

Assumes the following script.

```vim
function s:get_dict() abort
  throw 'my_error'
endfunction

try
  call s:get_dict().foo()
catch /my_error/
  echo 'Catch the error!'
catch
  echo "Couldn't catch: " . v:exception
endtry
```

Detailed steps to reproduce the behavior:
1. Run `vim --clean`
2. `:source example.vim`
4. `Couldn't catch: Vim(call):E488: Trailing characters: .foo()` is shown.

**Expected behavior**
`Catch the error!` is shown.

**Environment (please complete the following information):**
 - Vim version: 8.2.3408
 - OS: Arch Linux
 - Windows Terminal with tmux 3.2a

**Additional context**

`let value = s:get_dict().foo()` has no problem.

**Comment by habamax** [comment]
That is a correct error as far as I can see:

```
func! Hello()
    return "Hello "
endfunc

func! World()
    return "world!"
endfunc

" Error 488
call Hello().World()

" No error, string concatenation
echo Hello().World()
```

E488 happens before your `throw`.

**Comment by thinca** [comment]
E488 occurred after `s:get_dict()` called.

```vim
function s:get_dict() abort
  echomsg 'get_dict() called'
  throw 'my_error'
endfunction

try
  call s:get_dict().foo()
catch /my_error/
  echo 'Catch the error!'
catch
  echo "Couldn't catch: " . v:exception
endtry
```

Result:

```
get_dict() called
Couldn't catch: Vim(call):E488: Trailing characters: .foo()
```

**Comment by thinca** [comment]
Thank you!
