### ISSUE TITLE
To change "Vim with all enhancements" comment to "Example _vimrc"

### ISSUE THREAD

**Issue by john-cj** [vim/vim#8844]
Vim for Windows has a default `_vimrc` with the following contents:

```
" Vim with all enhancements
source $VIMRUNTIME/vimrc_example.vim

" Use the internal diff if available.
" Otherwise use the special 'diffexpr' for Windows.
if &diffopt !~# 'internal'
  set diffexpr=MyDiff()
endif
function MyDiff()
  ...
endfunction
```

To my humble opinion, the initial part is quite confusing.

```
" Vim with all enhancements
source $VIMRUNTIME/vimrc_example.vim
```

* First, the comment and the filename don't match well. "Why does the file is named 'example,' but the comment implies it is a set of things I would probably like to keep," the user would ask himself/herself.

  I would say the best solution is simply change the comment to something neutral:

  ```
  " Example _vimrc
  source $VIMRUNTIME/vimrc_example.vim
  ```

* And second, because of such a comment ("Vim with all enhancements"), some users, especially the ones who just started to learn and configure the editor, may skip, overlook, or don't take serious enough the filename, which is `vimrc_example.vim`.

  They have read a comment and they see that some file is included... What would they expect? Right, they would expect something like `defaults.vim` there! "Hey, this is probably a file with all the basic configurations I need. Thanks!" And then such a user may set `textwidth` to e.g. 80 and notice that sometimes it is 78 instead...

  ```
  " ...because of the following line in vimrc_example, of which he/she is not aware.
  autocmd FileType text setlocal textwidth=78
  ```

Also, it can be a good idea to explain how to use `MyDiff()` fuction and whether it is OK to remove it. Or maybe just move it to `vimrc_example.vim`.

**Comment by brammool** [comment]
> Vim for Windows has a default `_vimrc` with the following contents:
> 
> ```
> " Vim with all enhancements
> source $VIMRUNTIME/vimrc_example.vim
> 
> " Use the internal diff if available.
> " Otherwise use the special 'diffexpr' for Windows.
> if &diffopt !~# 'internal'
>   set diffexpr=MyDiff()
> endif
> function MyDiff()
>   ...
> endfunction
> ```

This is only when during installation the choice is made for the last
option in this list:

   "\nChoose the default way to run Vim:",
    "Vi compatible",
    "Vim default",
    "with some Vim enhancements",
    "with syntax highlighting and other features switched on",

Depending on how you installed Vim you may not have seen this choice or
ignored it.

> To my humble opinion, the initial part in quite confusing.
> 
> ```
> " Vim with all enhancements
> source $VIMRUNTIME/vimrc_example.vim
> ```
> 
> * First, the comment and the filename don't match well. "Why does the
> file is named 'example,' but the comment implies it is a set of things
> I would probably like to keep," the user would ask himself/herself.
> 
>   I would say the best solution is simply change the comment to
>   something neutral:
> 
>   ```
>   " Example _vimrc
>   source $VIMRUNTIME/vimrc_example.vim
>   ```

The comment reflects the choice made during installation.

> * And second, because of such a comment, some users, especially the
> ones who just started to learn and configure the editor, may skip,
> overlook, or don't take serious enough the filename, which is
> `vimrc_example.vim`.
> 
>   They have read a comment and they see some file is included... What
>   would they expect? Right, they would expect something `defaults.vim`
>   there! "Hey, this is probably a file will all the basic
>   configurations I need. Thanks!" And then such a user may set
>   `textwidth` to e.g. 80 and notice that sometimes it is 78 instead...

The choice of defaults is difficult, it's impossible to please everyone.
Users range from "I just want the defaults, nothing else" to "I want all
features enabled by default".

Considering we haven't had much discussion about this, and making
changes often confuses people who installed Vim before, I rather leave
this as it is.

-- 
Everybody wants to go to heaven, but nobody wants to die.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by john-cj** [comment]
Hmm, but what about just change the comment to something neutral, so that the comment will not imply anything about whether the settings in `vimrc_example` are recommended or not?

```
" Example _vimrc
source $VIMRUNTIME/vimrc_example.vim
```

This is a key part of what I talked about.
