### ISSUE TITLE
Vim9: builtin command can be shadowed by base name of import

### ISSUE THREAD

**Issue by obcat** [vim/vim#8845]
**Describe the bug**

A builtin command can be shadowed by a base name of `:import` when no arguments are given.

**To Reproduce**

1. Run `vim -Nu NONE`.

1. `:source` this script:

    ```vim
    vim9script
    writefile([], '/tmp/new.vim')
    import * as new from '/tmp/new.vim'
    new
    ```

    `E1029` is given for line 4:

    ```
    E1029: Expected '.' but got 
    ```

**Expected behavior**

No error is given. A new window is created.

**Environment**

- Vim 8.2.3412
- macOS 10.15.7
- iTerm2

**Additional context**

Not shadowed when one or more arguments are given:

```vim
vim9script
writefile([], '/tmp/new.vim')
import * as new from '/tmp/new.vim'
new some.txt
```

```
no error, a new window "some.txt" is created
```

**Comment by obcat** [comment]
BTW, I wonder if we are too permissive about the base name:

```vim
vim9script
writefile([], '/tmp/s.vim')
import * as _#:#_  from '/tmp/s.vim'
import * as a:b:c  from '/tmp/s.vim'
import * as g:some from '/tmp/s.vim'
```

```
no error
```

Especially, `g:some` is likely to interfere with a global variable having the same name, if exists.
Should we be more strict about this? For example, how about accepting strings that match `^\h\w*$`?

**Comment by obcat** [comment]
> Describe the bug

> A builtin command can be shadowed by a base name of :import when no arguments are given.

Sorry, this should be intentional. I will write here more detail later, not having enough time now;;

**Comment by brammool** [comment]
> BTW, I wonder if we are too permissive about the base name:
> 
> ```vim
> vim9script
> writefile([], '/tmp/s.vim')
> import * as _#:#_  from '/tmp/s.vim'
> import * as a:b:c  from '/tmp/s.vim'
> import * as g:some from '/tmp/s.vim'
> ```
> 
> ```
> no error
> ```
> 
> Especially, `g:some` is likely to interfere with a global variable
> having the same name, if exists.
> Should we be more strict about this? For example, how about accepting
> strings that match `^\h\w*$`?

Yes, it was using the check for the second character of a variable,
which includes ':' and '#' (for autoload), which we don't want here.

-- 
hundred-and-one symptoms of being an internet addict:
4. Your eyeglasses have a web site burned in on them.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
> **Describe the bug**
> 
> A builtin command can be shadowed by a base name of `:import` when no arguments are given.
> 
> 
> **To Reproduce**
> 
> 1. Run `vim -Nu NONE`.
> 
> 1. `:source` this script:
> 
>     ```vim
>     vim9script
>     writefile([], '/tmp/new.vim')
>     import * as new from '/tmp/new.vim'
>     new
>     ```
> 
>     `E1029` is given for line 4:
> 
>     ```
>     E1029: Expected '.' but got 
>     ```
> 
> 
> **Expected behavior**
> 
> No error is given. A new window is created.

We do allow for imports to shadow commands.  This may indeed have
unexpected effects, but at least these are local to the script.

The example you used may have a bit of a confusing error message, but I
think it won't happen often.  I will add a remark in the help for
:import to not use a name that shadows a command.

I'm not sure if we can change the rules to avoid confusion, suggestions
are welcome.


-- 
hundred-and-one symptoms of being an internet addict:
6. You refuse to go to a vacation spot with no electricity and no phone lines.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by obcat** [comment]
> Yes, it was using the check for the second character of a variable,
which includes ':' and '#' (for autoload), which we don't want here.

Thank you for the clarification and the patch.

> We do allow for imports to shadow commands.

The reason for that is the same as [the reason why a variable needs to shadow a builtin command](https://github.com/vim/vim/issues/8538#issuecomment-877668472), right?
I should have looked for simillar issue before opening this one. Sorry for the noise.

> The example you used may have a bit of a confusing error message, but I
think it won't happen often.  I will add a remark in the help for
:import to not use a name that shadows a command.

The remark should help. Thank you for the consideration! 🙇
