### ISSUE TITLE
[Feature] 'or' keyword as in lua

### ISSUE THREAD

**Issue by mg979** [vim/vim#8846]
`get()` has the problem that the default expression is always evaluated, so:

    a = get(g:, 'a', SomeExpensiveFunc())

And SomeExpensiveFunc() is always evaluated. In lua, with the `or` keyword this wouldn't happen.

In most cases this form is better:
```vim
if !exists('g:a')
	a = SomeExpensiveFunc()
endif
```

**Describe the solution you'd like**

`or` keyword that would make:

	a = g:a or SomeExpensiveFunc()

equivalent to:

	a = !exists('g:a') || g:a is v:null ? SomeExpensiveFunc() : g:a

So it would be different from `get()`, that is equivalent to:

	a = !exists('g:a') ? SomeExpensiveFunc() : g:a

It would make expressions like this more coincise:

	a = SomeFunc() or SomeOtherFunc()

So that if SomeFunc() returns null, SomeOtherFunc() is evaluated (and not both).

**Comment by mg979** [comment]
Anyway the form

    a = !exists('g:a') || g:a is v:null ? SomeFunc() : SomeOtherFunc()

is already reasonable, so this would just be syntactic sugar. Feel free to ignore it.

**Comment by brammool** [comment]
There is the falsy operator ??.  
```
a = get(g: 'a', false) ?? SomeExpensiveFunc()
```

This doesn't work if the value of g['a'] can be falsy though.

**Comment by mg979** [comment]
```vim

function! SomeFunc()
    return v:null
endfunction

function! SomeOtherFunc()
    return 1
endfunction

echo SomeFunc() ?? SomeOtherFunc()
```

Well it works, I didn't know about this operator, thanks!
