### ISSUE TITLE
Vim9: unexpected type mismatch error when using "add()" to add list item

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8847]
**Describe the bug**

In Vim9 script, using `add()` to add a list item might give an unexpected type mismatch error at runtime.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func(): list<string>
          var l: list<any>
          l->add('string')
          return l
        enddef
        Func()
    EOF
    )

`E1012` is given:

    E1012: Type mismatch; expected list<string> but got list<any>

This error is unexpected because:

   - it's given at runtime, not at compile time
   - at runtime, the value of `l` is `['string']`
   - the type of `['string']` is `list<string>`, not `list<any>`

**Expected behavior**

No error is given.

**Environment**

 - Vim version: 8.2 Included patches: 1-3416
 - OS: Ubuntu 20.04.3 LTS
 - Terminal: XTerm(353)

**Additional context**

Regression introduced in patch 8.2.3326.

---

No issue if we replace `add()` with `+=`:
```vim
vim9script
def Func(): list<string>
  var l: list<any>
  l += ['string']
  return l
enddef
echo Func()
```
    ['string']

Which is expected, but inconsistent with the previous snippet.

**Comment by brammool** [comment]
Actually, I would think that the second one, using +=, is wrong.  Consider this:
```

def Func(): list<string>
  var l: list<any>
  l += ['string']
  l += [1234]
  return l
enddef
```
That creates a list with different types and does give an error.
The type of "l" should not change because of what commands are executed, it's always list<any>.

**Comment by brammool** [comment]
If we add a compile time check for this, several tests will fail.
It's mainly because the return type can be "any" at compile time, but a more specific type at runtime.
Thus I don't think we can make this work better.

**Comment by lacygoill** [comment]
> Thus I don't think we can make this work better.

OK, fair enough.  Closing then.

**Comment by brammool** [comment]
> **Describe the bug**
> 
> In Vim9 script, using `add()` to add a list item might give an
> unexpected type mismatch error at runtime.
> 
> **To Reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(cat <<'EOF'
>         vim9script
>         def Func(): list<string>
>           var l: list<any>
>           l->add('string')
>           return l
>         enddef
>         Func()
>     EOF
>     )
> 
> `E1012` is given:
> 
>     E1012: Type mismatch; expected list<string> but got list<any>
> 
> This error is unexpected because:
> 
>    - it's given at runtime, not at compile time
>    - at runtime, the value of `l` is `['string']`
>    - the type of `['string']` is `list<string>`, not `list<any>`
> 
> **Expected behavior**
> 
> No error is given.
> 
> **Environment**
> 
>  - Vim version: 8.2 Included patches: 1-3416
>  - OS: Ubuntu 20.04.3 LTS
>  - Terminal: XTerm(353)
> 
> **Additional context**
> 
> Regression introduced in patch 8.2.3326.
> 
> ---
> 
> No issue if we replace `add()` with `+=`:
> ```vim
> vim9script
> def Func(): list<string>
>   var l: list<any>
>   l += ['string']
>   return l
> enddef
> echo Func()
> ```
>     ['string']
> 
> Which is expected, but inconsistent with the previous snippet.

I would think it's the other way around.  The variable "l" is declared
as a list<any>, and that is what is being returned.  Depending on a
runtime type check here is a bad idea, we like to catch errors at
compile time.

It should work to add a type cast, then the type check can be
intentionally done at runtime.

-- 
hundred-and-one symptoms of being an internet addict:
18. Your wife drapes a blond wig over your monitor to remind you of what she
    looks like.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
