### ISSUE TITLE
<Cmd> mapping defined in {} block of user-command may not work

### ISSUE THREAD

**Issue by obcat** [vim/vim#8849]
**Describe the bug**

A `<Cmd>` mapping defined in a {} block of a user-command may not work.

**To Reproduce**

1. Run `vim -Nu NONE`.

1. `:source` this script:

    ```vim
    set debug=beep
    command DefineAMap {
      nnoremap \f <Cmd>echo 'Fish!'<CR>
    }
    DefineAMap
    normal \f
    ```

    Bell rings, `Beep!` is echo'ed:

    ```
    Beep!
    ```

**Expected behavior**

Bell does not ring, `Fish!` is echo'ed:

```
Fish!
```

**Environment**

- Vim 8.2.3416
- macOS 10.15.7
- iTerm2

**Additional context**

No issue when we replace `<Cmd>` with `:`:

```vim
set debug=beep
command DefineAMap {
  nnoremap \f :echo 'Fish!'<CR>
}
DefineAMap
normal \f
```

```
Fish!
```

**Comment by brammool** [comment]
This is unrelated to using a block, same thing happens without it.
The ":command" eats the <Cmd> and converts it to the special key.  To avoid that use <lt> for the first "<":
```
command DefineAMap nnoremap \f <lt>Cmd>echo 'Fish!'<CR>
```
or
```
command DefineAMap {
               nnoremap \f <lt>Cmd>echo 'Fish!'<CR>
          }
```

**Comment by obcat** [comment]
> This is unrelated to using a block, same thing happens without it.
> The ":command" eats the and converts it to the special key.

I assumed that `:command` would only convert `<line1>`, `<line2>`, `<range>`, ..., which are listed below `:help <line1>`.

> To avoid that use for the first "<":
> 
> ```
> command DefineAMap nnoremap \f <lt>Cmd>echo 'Fish!'<CR>
> ```
> 
> or
> 
> ```
> command DefineAMap {
>                nnoremap \f <lt>Cmd>echo 'Fish!'<CR>
>           }
> ```

It does work well. Thank you so much for the help!
