### ISSUE TITLE
Wrong tag destination in :only documentation

### ISSUE THREAD

**Issue by Masquue** [vim/vim#8854]
In the help of `:only`, there is 

> For {count} see :quit command.

, in which the `:quit` tag will jump to the `:quit` in editing.txt, where there is no information about the {count}.

This `:quit` actually refers to the `:quit` in windows.txt, which is a synonym of `CTRL-W q`.

Maybe this should be changed to 

> For {count} see CTRL-W_q command.

By the way, I don't know why there are two occurrences of the same command.

**Comment by brammool** [comment]
Let's add a new tag for this and refer to it.
