### ISSUE TITLE
Can we increase the hard-coded value SEARCH_STAT_DEF_MAX_COUNT?  

### ISSUE THREAD

**Issue by aemonge** [vim/vim#8855]
https://github.com/vim/vim/blob/bc67e5a0a494f5fc48e872d747371e31a782d171/src/search.c#L40

Maybe move this from 99 to 9999 ?

**Comment by chrisbra** [comment]
do you actually run into that limit? If so, when and how? I had that problem just recently with a huge logfile, but before that, I have never run into it and I have used that feature right from the beginning. So I am wondering.

**Comment by brammool** [comment]
If you have more than 99 matches, does the number matter?  The larger the number, the slower it gets.

**Comment by vim-ml** [comment]
On 2021-09-09, Bram Moolenaar wrote:
> If you have more than 99 matches, does the number matter? The larger the
> number, the slower it gets.

I run into this maybe once a week.  If the number is >99, it would
be nice to know how big it is and where the cursor is currently in
the list--all the reasons it's nice to have those stats in the first
place.

I know that larger is slower and I've assumed that you've found 99
to be a good trade-off.  I can live with 99, but I've run into that
limit often enough that it would be nice if it could be bigger or
changeable.  Maybe I should bump it up and see how big it gets and
how slow it gets.

Regards,
Gary

**Comment by aemonge** [comment]
I can't remember now where I found the limit frustrating. But as said, it happened once only, so I would agree with you all that it's not necessary if performance will be affected.
