### ISSUE TITLE
Vimscript syntax highlighting of token 'sub' in strings broken when string on its own line

### ISSUE THREAD

**Issue by hoelzro** [vim/vim#886]
For example, take this snippet of Vimscript:

``` vim
function! MyFunction()
  let string =
\ 'sub {'
  echomsg string
endfunction

call MyFunction()
```

This is how my Vim (7.4.1902) currently highlights it:

![vim-sub-highlight](https://cloud.githubusercontent.com/assets/107804/16291590/304ddfc2-38ce-11e6-8621-b6f51bf7303a.png)

Note how `sub` is highlighted as if it were `:substitute`, and how the highlighting on subsequent lines is broken.

**Comment by lacygoill** [comment]
Fixed by https://github.com/vim/vim/commit/1ff14ba24c4d85c008d7abe5e140dbb497ffea8d.
