### ISSUE TITLE
gvim (vim-gtk3) has significant scroll-lag in Debian-11 Dolphin

### ISSUE THREAD

**Issue by gvimlag** [vim/vim#8861]
Debian package maintainer (vim-gtk@packages.debian.org) said that this problem is an "upstream" issue, and to contact the gvim developers.

**Describe the bug**
In Dolphin, gvim scroll-up/down lags significantly and is choppy.
In Konsole, gvim scroll-up/down has no lag and is smooth.
It appears that the gvim configuration given to Dolphin needs an adjustment to match the performance of the Konsole configuration.

**To Reproduce**
rm ~/.vimrc                                           #remove all gvim configuration settings (clean tests)

1) Open Dolphin                                          #Example: Dolphin gvim has scroll lag
right-click on: /usr/share/vim/vim82/doc/version8.txt #open large file
select:         Open with->GVim                       #open large file
maximize gvim window                                  #maximum gvim widow size
Hold CTL-e for 10 seconds                             #scroll-down for 10 seconds
Release CTL-e                                         #>>>> SCROLL-DOWN CONTINUES FOR *ANOTHER 5 SECONDS* AFTER RELEASE

2) Open Konsole                                          #Example: Konsole gvim has no scroll lag
gvim /usr/share/vim/vim82/doc/version8.txt            #open large file
maximize gvim window                                  #maximum gvim widow size
Hold CTL-e for 10 seconds                             #scroll-down for 10 seconds
Release CTL-e                                         #>>>> SCROLL-DOWN STOPS *IMMEDIATELY* AFTER RELEASE

**Expected behavior**
No scroll-lag after releasing CTL-e.

**Environment (please complete the following information):**
Debian-11 (Bullseye), KDE
Konsole Version 20.12.3
Dolphin Version 20.12.2
vim-gtk3 (gvim) package version 2:8.2.2434-3
vim version 8.2

Edit:
**Additional information:**
Mistake: For Konsole, I stated: "SCROLL-DOWN STOPS *IMMEDIATELY* AFTER RELEASE".
Correction: For Konsole, should state: "SCROLL-DOWN STOPS 1-1.5 SECONDS AFTER RELEASE".

Online research indicates that this gvim scroll-lag issue is due to a difference in gtk2(fast) vs. gtk3(slow):
  https://groups.google.com/g/vim_dev/c/1V8EC5lFcf0/m/VdHuTo_UDwAJ
  https://wiki.pine64.org/index.php/Pinebook_Pro

This scroll-lag problem is *NOT* present in gvim (vim-gtk2) (gtk2 is available in Debian 10, but not available in Debian 11).
This scroll-lag problem is present in gvim (vim-gtk3).
Unfortunately, new Debian-11 dropped gvim (vim-gtk2); forcing the use gvim (vim-gtk3).

Speed check of nvim-qt (gvim equivalent) in Debian-11 showed that nvim-qt does not have this scroll-lag problem.
gvim is based on gtk3.
nvim-qt is based on Qt5 GUI.

So this scroll lag problem appears to be associated with gtk3.

**Comment by brammool** [comment]
With Dolphin do you mean the file manager?
Does that really matter, or is it just the difference between gtk2 and gtk3?

**Comment by gvimlag** [comment]
`With Dolphin do you mean the file manager?`
Yes, Dolphin is the file manager.

`Does that really matter, or is it just the difference between gtk2 and gtk3?`
The main problem is the difference between gtk2 and gtk3.  (Using Dolphin just makes the problem worse.)
The problem is not present in gvim (vim-gtk2); but is present in gvim (vim-gtk3) (I tested both using Debian 10).
Unfortunately, Debian-11 dropped gvim (vim-gtk2); forcing the use gvim (vim-gtk3).

**Comment by jamessan** [comment]
As you stated when initially emailing me, you found https://github.com/vim/vim/issues/1199 which reports the same issue.  Not sure why a new issue needed to be created.

**Comment by gvimlag** [comment]
Because that issus was created in 2016, and still hadn't been addressed.

**Comment by brammool** [comment]
Even though that issue is old, it contains relevant information.  Therefore closing this one.
You might want to ask the GTK developers about this.  Creating a new issue doesn't help.
