### ISSUE TITLE
When I Save file it case Incorrect checksum for freed object

### ISSUE THREAD

**Issue by owner888** [vim/vim#8865]
**Describe the bug**
When I Save file it case Incorrect checksum for freed object, My computer is Macbook M1 

**To Reproduce**

1. Run `:w` to save file
2. Vim(45965,0x101387d40) malloc: Incorrect checksum for freed object 0x132eb2ee8: probably modified after being freed.
Corrupt value: 0x0
Vim(45965,0x101387d40) malloc: *** set a breakpoint in malloc_error_break to debug
Vim: Finished.
Vim: Double signal, exiting

**Expected behavior**

**Screenshots**
If applicable, copy/paste the text or add screenshots to help explain your problem.

**Environment (please complete the following information):**
 - Vim version 8.2
 - OS: macOS 11.5.2 M1
 - Terminal: MacVim

**Additional context**
![2021-09-11 at 11 31 PM](https://user-images.githubusercontent.com/4317332/132954801-e9289891-66c2-4814-a333-dae4da7a6f35.png)

**Comment by brammool** [comment]
Does not sound like a core Vim problem, you might want to report this at https://github.com/macvim-dev/macvim

Please include the steps made from starting Vim, preferably with "vim --clean".

**Comment by chrisbra** [comment]
Can you please post the output of `vim --version`? Also to help getting this fixed, it is useful to print a gdb backtrace. This usually means to compile a debug version of Vim so that gdb can print out a nice stack-trace. Alternatively, you may want to compile an asan built and run that. This should also point to where the problem is.  Also please check with the latest master version, to make sure you are not hunting a bug, that has already been fixed (that's why the full version output is also helpful).

Thanks.

**Comment by owner888** [comment]
> Can you please post the output of `vim --version`? Also to help getting this fixed, it is useful to print a gdb backtrace. This usually means to compile a debug version of Vim so that gdb can print out a nice stack-trace. Alternatively, you may want to compile an asan built and run that. This should also point to where the problem is. Also please check with the latest master version, to make sure you are not hunting a bug, that has already been fixed (that's why the full version output is also helpful).
> 
> Thanks.

Yeah, Macvim include Vim in /Applications/MacVim.app/Contents/MacOS/Vim

$/Applications/MacVim.app/Contents/Resources/Vim --version

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr  1 2021 08:37:51)
macOS version - arm64
包含补丁: 1-2681
编译者 GitHub Actions
巨型版本 带 MacVim 图形界面。  可使用(+)与不可使用(-)的功能:
+acl               +file_in_path      -mouse_sysmouse    -tag_old_static
+arabic            +find_in_path      +mouse_urxvt       -tag_any_white
+autocmd           +float             +mouse_xterm       -tcl
+autochdir         +folding           +multi_byte        +termguicolors
-autoservername    -footer            +multi_lang        +terminal
+balloon_eval      +fork()            -mzscheme          +terminfo
+balloon_eval_term +fullscreen        +netbeans_intg     +termresponse
+browse            +gettext           +num64             +textobjects
++builtin_terms    -hangul_input      +odbeditor         +textprop
+byte_offset       +iconv             +packages          +timers
+channel           +insert_expand     +path_extra        +title
+cindent           +ipv6              +perl/dyn          +toolbar
+clientserver      +job               +persistent_undo   +transparency
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           +python/dyn        +visual
+conceal           +linebreak         +python3/dyn       +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua/dyn           +ruby/dyn          +wildmenu
+dialog_con_gui    +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
+dnd               +mouse             -sound             -xfontset
-ebcdic            +mouseshape        +spell             +xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              -mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
-farsi             +mouse_sgr         +tag_binary        
     系统 vimrc 文件: "$VIM/vimrc"
     用户 vimrc 文件: "$HOME/.vimrc"
 第二用户 vimrc 文件: "~/.vim/vimrc"
      用户 exrc 文件: "$HOME/.exrc"
    系统 gvimrc 文件: "$VIM/gvimrc"
    用户 gvimrc 文件: "$HOME/.gvimrc"
第二用户 gvimrc 文件: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
        系统菜单文件: "$VIMRUNTIME/menu.vim"
         $VIM 预设值: "/Applications/MacVim.app/Contents/Resources/vim"
编译方式: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe -DMACOS_X -DMACOS_X_DARWIN -g -O2 -arch x86_64 -arch arm64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Wall -Wextra -Wshadow -Werror -Wno-error=missing-field-initializers -Wno-error=deprecated-declarations -Wno-error=unused-function 
链接方式: clang -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib -arch x86_64 -arch arm64 -L/usr/local/lib -o Vim -lm -lncurses -liconv /usr/local/lib/libintl.a -framework AppKit -fstack-protector -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE

**Comment by chrisbra** [comment]
please try with an updated vim first (and as mentioned before, try to get a backtrace)

**Comment by owner888** [comment]
> please try with an updated vim first (and as mentioned before, try to get a backtrace)

Already the latest version，Unable to update

**Comment by chrisbra** [comment]
so, can you reproduce with latest built vim (I mean clone this repo and build yourself from the master branch, e.g. by using homebrew, not using MacVim)?

**Comment by brammool** [comment]
We really need full reproduction steps to find out why this happens.  Start with "vim --clean" or "vim -u NONE"
and write down everything you do until the problem occurs.

It might be helpful to run Vim under valgrind to see if can locate the problem.  You do need to build Vim for debugging for this to be useful though.

**Comment by chrisbra** [comment]
any update here?
