### ISSUE TITLE
((1) of 2) in titlestring arglist

### ISSUE THREAD

**Issue by john-cj** [vim/vim#8867]
gVim 8.2.2824 on Windows.

```
set titlestring=
set titlestring+=%F
set titlestring+=%(\ %M%)
set titlestring+=%a
```

From `cmd.exe`:

```
gvim a.txt b.txt
```

results in the following titles:

```
C:\foo\bar\a.txt (1 of 2)
C:\foo\bar\b.txt ((1) of 2)
```

For gvimdiff, it works fine:

```
C:\foo\bar\a.txt (1 of 2)
C:\foo\bar\b.txt (2 of 2)
```

**Comment by brammool** [comment]
The one in parenthesis means that the first argument is the current position in the argument list, but you are editing another file.  So how did you navigate to b.txt?

**Comment by john-cj** [comment]
> So how did you navigate to b.txt?

I navigate to them by using menu. In the menu bar, I select "Buffers" and then "a.txt" or "b.txt".

**Comment by brammool** [comment]
That is normal: navigating buffers does not update the argument index.  If you type :next you would see (2 of 2).

**Comment by john-cj** [comment]
I see, thanks.
