### ISSUE TITLE
Update sh.vim

### ISSUE THREAD

**Issue by ghost** [vim/vim#887]
As said by @Chiel92 Chiel92/vim-autoformat#142 [sh.vim](https://github.com/vim/vim/blob/master/runtime/indent/sh.vim) doesn't support here documents.

**Comment by chrisbra** [comment]
please discuss with the maintainer of the syntax file. Thanks.

**Comment by k-takata** [comment]
@chrisbra Are you not the maintainer?
https://github.com/vim/vim/blob/master/runtime/indent/sh.vim#L3

**Comment by chrisbra** [comment]
Oops, now that is embarassing ;)
@guiwp please create a new issue here: https://github.com/chrisbra/vim-sh-indent/
and describe clearly what you want/expect. Thanks.

**Comment by ghost** [comment]
:) ok @chrisbra
