### ISSUE TITLE
autoread: only has 1 second resolution to detect changes

### ISSUE THREAD

**Issue by leahneukirchen** [vim/vim#8873]
**Describe the bug**
A buffer with the option `autoread` is not detected as modified (and thus reloaded) if the file size doesn't change and the change happens within the same second as the previous write.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. `vim /tmp/foo`
2. `ibar<ESC>`
3. `:w | !echo qux >%`
4. the buffer is not changed, the file is not reloaded
5. `:e!` will reload the file with the changed content

Note that 3. is made for easy reproducibility, but if you are editing fast enough
you can hit it occasionally with manual typing.

**Expected behavior**
The file should be reloaded after the `!echo qux >%`.
This is possible when looking at the nanosecond mtime, for example.

**Environment (please complete the following information):**
 - Vim version 8.2.2874
 - OS: Void Linux x86_64/glibc

**Additional context**
I recommend also comparing the nanosecond timestamp in `buf_check_timestamp` to detect fast changes.
POSIX.1‐2017 provides this as st.st_mtim.tv_nsec (MacOS needs a different field, and some
older OS may not have it, so this requires configure support).

**Comment by chrisbra** [comment]
so, could you come up with a PR?

**Comment by leahneukirchen** [comment]
I'd be willing to prepare a patch, but I need to figure out some details of the build system first. Give me a few days. :)

**Comment by gdupras** [comment]
I cannot reproduce this on Windows 10. With `:set autoread` and your steps, the file is automatically reloaded. With `:set noautoread` instead, Vim warns me that the file has changed and ask me if I want to reload it.

**Comment by leahneukirchen** [comment]
I forgot to mention that `autoread` should be set. But even if it isn't, on my Linux system the change is not detected when the two writes happen fast enough.

**Comment by brammool** [comment]
You could make it check that nanosecond value, but keep in mind that many filesystems simply have only second resolution.
Would be useful to add a remark in the help about a few often used filesystems and whether it works there.

**Comment by leahneukirchen** [comment]
I think all commonly used file systems have sub-second resolution, except for FAT32 which has 2s resolution and NFS on older setups. But OS should either fill tv_nsec with 0 or not provide it at all, and we check for it at compile time.

**Comment by leahneukirchen** [comment]
I looked closer at the code, and on Linux it actually only has 2 second resolution to take FAT into account (which shouldn't be needed when comparing results of stat.st_mtime to previous ones), I think this is indeed very possible to trigger by "casual" fast editing.
