### ISSUE TITLE
gVim consumes 160 MB without vimrc, 300-400 MB with vimrc

### ISSUE THREAD

**Issue by john-cj** [vim/vim#8888]
For some reason, gVim started to consume about 160 MB or RAM without vimrc and about 300-400 MB with my regular vimrc. I don't know why. I have tried to reinstall it, but it doesn't help. If I run it as `gvim --clean`, it consumes only 4 MB. What should I do?

- Vim 8.2.2824
- Windows 7

**Comment by john-cj** [comment]
I just found the following suspicious files:

_viminfo - 309 MB
_viminfy.tmp - 90 MB
_viminfz.tmp - 89 MB

If I rename them, the problem is gone. But what is the reason they became so huge and how should I avoid it in the future?

**Comment by dpelle** [comment]
@john-cj wrote:

> For some reason, gVim started to consume about 160 MB or RAM without vimrc and about 300-400 MB with my regular vimrc.

Hard to tell why without profiling memory.  I don't know what memory
profilers exist on Windows, but on Linux one can e.g. use valgrind massif,
or heaptrack (much faster than massif), or gperftool.  heaptrack is
my favorite (fast and nice UI to analyze results).

Some vim options can cause to consume more memory such as undo, `regexpengine=2`, and possibly more to find out where allocated 
memory comes from.

Your `_viminfo` should be human readable, so maybe looking at it
can give a clue.  If you think you can share it, consider providing
a download link to it.

**Comment by brammool** [comment]
> For some reason, gVim started to consume about 160 MB or RAM without
> vimrc and about 300-400 MB with my regular vimrc. I don't know why. I
> have tried to reinstall it, but it doesn't help. If I run it as `gvim
> --clean`, it consumes only 4 MB. What should I do?

One reason can be that you are using the undofile feature.  Undo
information is kept in memory, thus if you made big changes, e.g. with
"%s/$/</", it grows rapidly.

So long as you don't notice the slowdown I would not worry too much
about it.

> I just found the following suspicious files:
> 
> _viminfo - 309 MB
> _viminfy.tmp - 90 MB
> _viminfz.tmp - 89 MB
> 
> If I rename them, the problem is gone. But what is the reason they
> became so huge and how should I avoid it in the future?

A similar reason: Deletes are put in a register, with big deletes the
contents can become large.  You can tune it with 'viminfo'.  You can
edit the file to see what is taking up much space.

-- 
To define recursion, we must first define recursion.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
