### ISSUE TITLE
Odd spaces in vim.man

### ISSUE THREAD

**Issue by ptzz** [vim/vim#889]
Are the odd spaces in vim.man intentional for some reason? E.g in the intro:

```
Vim  is a text editor that is upwards compatible to Vi.  It can be used
       to edit all kinds of plain text.  It is especially useful  for  editing
programs.
```

**Comment by k-takata** [comment]
I don't see the problem.
https://github.com/vim/vim/blob/master/runtime/doc/vim.man#L20-L22

**Comment by ptzz** [comment]
There is double space instead of single space at several places. After the first occurence of "Vim" and after "useful" for example.

**Comment by chrisbra** [comment]
Am 2016-06-29 17:22, schrieb ptzz:

> There is double space instead of single space at several places. After
> the first occurence of "Vim" and after "useful" for example.

Yes, but I don't see the wrong breaking of lines. The double
spacing probably has been done to justify the text.

**Comment by ptzz** [comment]
Line breaks were probably my bad copypaste.

You mean extra spaces is for justifying the right margin..? First time I've seen that in man text :)

**Comment by chrisbra** [comment]
I guess this is not a problem, so I am closing this.
