### ISSUE TITLE
Not clear content in x11-selection which from autoselect visual mode after vim exit 

### ISSUE THREAD

**Issue by zyf0330** [vim/vim#8891]
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
When enable autoselect and use visual mode to select text, it appears in x11-selection and can paste into other appliaction from X clipboard.
But after vim exits, the content disappears, and original content in X clipboard appears.

**Describe the solution you'd like**
After vim exits, content from autoselect visual mode still exists and can be paste from X clipboard.
**Describe alternatives you've considered**

**Additional context**

**Comment by chrisbra** [comment]
That is the way interprocess communication works in Unix. If you do not 
like this, you can use  a clipboard manager.


Am 2021-09-18 06:30, schrieb zhaoyunfeng:

**Comment by zyf0330** [comment]
Sorry, I know now. Other applications have the same behavior too.
