### ISSUE TITLE
Nim syntax

### ISSUE THREAD

**Issue by 89z** [vim/vim#8892]
It seems Nim [1] syntax is not currently available. I have been using this [2] and it works well. I filed an issue with the maintainer some months ago, but they never responded.

Can we add it anyway? I can maintain the Nim code if need be.

1. https://nim-lang.org
2. https://github.com/zah/nim.vim

**Comment by mattn** [comment]
Sorry, I don't know that I did work.

**Comment by chrisbra** [comment]
I am closing this. If you want to maintain the script, please create a PR with nim code (make sure the license is okay to redistribute this and bonus points for an ACK from the nim maintainers for this).

**Comment by 89z** [comment]
https://github.com/vim/vim/pull/9237
