### ISSUE TITLE
echomsg left dangling

### ISSUE THREAD

**Issue by oblitum** [vim/vim#891]
On 802a0d9 an echomsg was left dangling at https://github.com/vim/vim/commit/802a0d902fca423acb15f835d7b09183883d79a0#diff-9aa7419d9504f85f995d943175f49e46R95. It shows up anytime a tex or related file is open.

**Comment by chrisbra** [comment]
cc @cecamp 
closing. I am sure, charles will submit a new version soon. Thanks.

**Comment by oblitum** [comment]
Sorry but I don't see a reason to close the issue before the fact? Specifically I (or anyone interested) will miss the notification for when it's really fixed.

**Comment by oblitum** [comment]
Fixed by v7.4.1986 at https://github.com/vim/vim/commit/e18dbe865d190e74fb5d43ac8bc6ac22507d0223#diff-9aa7419d9504f85f995d943175f49e46L95 ....
