### ISSUE TITLE
how about auto adjust tab title position if there lots of tabs opened?

### ISSUE THREAD

**Issue by Shane-XB-Qian** [vim/vim#8911]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
![image](https://user-images.githubusercontent.com/13550529/134610415-dad1a846-7c3b-4338-8543-e1013d00e0e7.png)
// looks if there are lots tabs opened, then cur tab's title probably was not displayed.

**Describe the solution you'd like**
// how about auto adjust tab title position if there lots of tabs opened?

**Describe alternatives you've considered**
// though `tabs` cmd can help.

**Additional context**
n/a.

**Comment by brammool** [comment]
I'm not sure if I understand the suggestion.  The current tab, assuming it's displaying one file, will result in the window title showing the name, thus there is no need to make the tab title show more.
For other tabs there simply isn't room to show more.

**Comment by Shane-XB-Qian** [comment]
for example above screen-cut, there 'aaaa' 'bbbb' 'cccc' 'dddd' 'eeee' 'ffff' 6 tabs opened, now the 7th tab 'ggggggg' no room to show, but current active tab is 'ggggggg'.
what i proposed is move out 'aaaa' (and maybe 'bbbb' too) to release room to show 'ggggggg'.
// note: the order of tabs did not change, so it was not doing ':tabm'.
// perhaps whatever using 'tabline' option or not, should/better same?

**Comment by Shane-XB-Qian** [comment]
@lacygoill your example code is for 'tabline' option, but when if (default) none (did not set) tabline?
besides:
1, user may change terminal emulator size (resize), even set your example code, but the shortness of 'no room to display' would be still there..
2, if user did not open a tab with name 'file1' but 'foooooooooooooooooooooooooooooooooooooooooooooooo1', your example code would not move out other tabs to release room for that, but just 'shorten' it.
3, looks it's a bit difficult to naturely compatible your example code with others 3rd part tabline plugin.

**Comment by Shane-XB-Qian** [comment]
a problem but did not impact too much, so let it be, closing.......
