### ISSUE TITLE
Vim crashes at start

### ISSUE THREAD

**Issue by Nadve** [vim/vim#8916]
**Describe the bug**
Vim crashes at start.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run vim or gvim after fresh install on Windows 10 machine

**Expected behavior**
Vim starts

**Environment:**
 - Vim version: 8.2.3444.0
 - OS: Windows 10

**Additional context**
Error: The application was unable to start correctly (0xc0000005)
ID of the faulty procces: 0xdec

I don't know how to deal with this problem or how to debug it further.
If you deem this report not sufficient please tell me how to obtain more information about the problem.

**Comment by chrisbra** [comment]
Does it work when starting `vim --clean`

**Comment by Nadve** [comment]
No, it doesn't.
Exactly same behaviour is observed => nothing happens at all, AppCrash log can be seen in Event Viewer

**Comment by chrisbra** [comment]
So is this the release from https://github.com/vim/vim-win32-installer/releases ? The current information isn't very useful. We may need your help to produce better stack traces. You can possibly use the `.pdb` files for your release from https://github.com/vim/vim-win32-installer/releases 

However I do not actually know how to use those. According to this microsoft documentation https://docs.microsoft.com/en-us/visualstudio/debugger/specify-symbol-dot-pdb-and-source-files-in-the-visual-studio-debugger?view=vs-2019 you would need microsoft visual studio to debug this crash

**Comment by Nadve** [comment]
1) Yes it is a release from https://github.com/vim/vim-win32-installer/releases
2) I opened gVim in a Visual Studio and included .pdb files but as soon as I started debugging I received a Search Folder dialog VS prompting me to locate mbyte.c which I don't have
I suppose I need vim source code to succesfully debug this problem

**Comment by chrisbra** [comment]
yes, quite possible. Can you try with the source and point us to a useful stacktrace?

**Comment by zuloloxi** [comment]
@ https://github.com/vim/vim/issues/8916#issuecomment-930335789
Hello ! Could you build from vim source code ( the src vim folder ) on you windozs in debug mode with nmake script make_mvc,mak ? 
To help   find the crash line change in make_mvc,mak file the CFLAGS, and add these options to cl compiler: 
> /FAcs /Fa$(OUTDIR) /Fo$(OUTDIR)
 also conflags
> conflags = /nologo /subsystem:$(SUBSYSTEM) /DYNAMICBASE:NO /FIXED /NXCOMPAT /MACHINE:X86 /opt:ref
I attached a modified file of make_mvc,mak ...
Before to compile, in VS studio 2019 Community ed, you have to start the cmd : 

> x86 Native Tools Command Prompt for VS 2019, 
to configure compiler and linker PATH. 

In command prompt windows build vim executable with, change to the vim source code, src folder, by example  ;

> cd  c:\your_vim_folder\vim-51491adfa86fd66a857cd7ec50d0b57dbdf3da59\src

and compile

> nmake -f make_mvc.mak FEATURES=HUGE MBYTE=YES GETTEXT=NO MAP=YES
[Make_mvc.mak.txt](https://github.com/vim/vim/files/7271107/Make_mvc.mak.txt)

**Comment by k-takata** [comment]
Actually, you don't need to compile Vim by yourself.

> 2\. I opened gVim in a Visual Studio and included .pdb files but as soon as I started debugging I received a Search Folder dialog VS prompting me to locate mbyte.c which I don't have

You should download the corresponding version of the Vim source code by the following commands (using [Git for Windows](https://gitforwindows.org/)):

```
git clone https://github.com/vim/vim
cd vim
git checkout v8.2.XXXX
```

**Comment by chrisbra** [comment]
any update or can this issue be closed?

**Comment by Nadve** [comment]
Sorry I didn't have time to sit down and work on it.

@zuloloxi
This part is confusing me a lot and I don't know what to do:

/FAcs /Fa$(OUTDIR) /Fo$(OUTDIR)
also conflags
conflags = /nologo /subsystem:$(SUBSYSTEM) /DYNAMICBASE:NO /FIXED /NXCOMPAT /MACHINE:X86 /opt:ref
I attached a modified file of make_mvc,mak ...
Before to compile, in VS studio 2019 Community ed, you have to start the cmd :

x86 Native Tools Command Prompt for VS 2019,
to configure compiler and linker PATH.

**Comment by chrisbra** [comment]
any update here?

**Comment by Nadve** [comment]
So the issue was caused by my windows account user name. It contained characters from czech alphabet which broke the program.
My username: Tomáš
Issue was solved by creating account with ascii characters
