### ISSUE TITLE
intro.txt lists `<FF>` as the notation of a key that can be used in ":map" command but it is only used in documentation

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#8918]
intro.txt lists `<FF>` as the notation of a key that can be used with ":map" command:

<https://github.com/vim/vim/blob/be01090efad242e30728275dea05420db6f96257/runtime/doc/intro.txt#L413-L424>

However, ~mapping `<FF>` doesn't actually work~ `<FF>` doesn't actually get translated to a single key. `<FF>` is only used in documentation and only in one place:

<https://github.com/vim/vim/blob/be01090efad242e30728275dea05420db6f96257/runtime/doc/eval.txt#L1420>

**Comment by chrisbra** [comment]
I tried the following:

    nnoremap <ff> :echomsg "<ff> received"<cr>
    nmap <f5> <ff>

Now pressing `<f5>`  shows `<ff>` received. So I guess it works.

**Comment by zeertzjq** [comment]
> I tried the following:
> 
> ```
> nnoremap <ff> :echomsg "<ff> received"<cr>
> nmap <f5> <ff>
> ```
> 
> Now pressing `<f5>` shows `<ff>` received. So I guess it works.

I think it mapped to four separate characters `<`, `f`, `f`, `>`.

**Comment by zeertzjq** [comment]
Also, `:echo "\<FF>"` doesn't print a special character, whereas `:echo "\<CR>"` does.

**Comment by zeertzjq** [comment]
I also searched the history of [misc2.c](https://github.com/vim/vim/blob/master/src/misc2.c), and found out that `"FF"` never appeared in that file.

**Comment by chrisbra** [comment]
ah yes possible

**Comment by brammool** [comment]
Not sure if it every worked or how it ended up in the help text.  Let me remove it from the help now.
