### ISSUE TITLE
Directories raise "Error: no write since last change"

### ISSUE THREAD

**Issue by NeilGirdhar** [vim/vim#893]
Directories that have been browsed raise "Error: no write since last change" on quit.  Directories are not editable in vim.  Quitting again closes the directory, but other directories can also raise this error.

**Comment by chrisbra** [comment]
did you modify those directory buffers?

**Comment by NeilGirdhar** [comment]
What does that mean?

**Comment by NeilGirdhar** [comment]
Anyway, the directory buffers are read only, so I don't see why they should be allowed to raise that error?

**Comment by chrisbra** [comment]
looks like something (a plugin perhaps?) is setting the `modified` setting on those buffers, hence Vim will complain. Can you check, if this happens when you start Vim with `vim -u NONE -N`
Also you might want to check with a recent Vim (you didn't say what version you are using) with updated runtime files, as well try charles latest netrw from [here](http://www.drchip.org/astronaut/vim/index.html#NETRW)
(I assume, this happens with the builtin file explorer and not any other plugin. If that is the case, please report as bug there).

**Comment by cecamp** [comment]
I don't see this problem using Linux and the latest netrw (v162c).  I suggest upgrading (http://www.drchip.org/astronaut/vim/index.html#NETRW).  If you persist in having this problem, please give us a specific set of commands/actions that evoke the issue so I can try to duplicate it.

**Comment by NeilGirdhar** [comment]
@cecamp what does netrw have to do with this?

**Comment by chrisbra** [comment]
netrw is used for browsing directories.

**Comment by cecamp** [comment]
How are you browsing directories?  If you type ":e .", for example, netrw (by default) is running and showing a display of the directory contents.  There are other tools to do directory browsing; if you're using one of them, please be specific and let their authors know.

**Comment by NeilGirdhar** [comment]
Oh!  I didn't realize what it was called. Yes, I'm doing ":e ." as you said.  I can't seem to figure out how to upgrade.  I am using MacVim 8.0 installed with MacPorts.

**Comment by nuko8** [comment]
Visit http://www.drchip.org/astronaut/vim/index.html#NETRW and click the link just below the header _"Network Oriented Reading, Writing, and Browsing"_ to download the file http://www.drchip.org/astronaut/vim/vbafiles/netrw.vba.gz .

Then, if you are using Safari, the file is to be downloaded and unzipped in the Downloads folder; you'll find `netrw.vba` there.

Open MacVim and have it read the file.

Next, type <kbd>:so %</kbd>, which extracts files from `netrw.vba` and put those extracted files in place (most likely into `~/.vim`).

That's it. :)

As to uninstallation, you can use <kbd>:RmVimball netrw</kbd>.

What is used to install netrw here is Vim's native package management system for plugins, called _Vimball_.   For details, <kbd>:help vimball</kbd>.

**Comment by NeilGirdhar** [comment]
Thanks, that makes sense.  I hope the vundle mirror gets updated (https://github.com/eiginn/netrw/issues/17)

**Comment by NeilGirdhar** [comment]
@nuko8 Okay, I followed your instructions.  How do I check the version?

**Comment by vim-ml** [comment]
Hi Neil

> How do I check the version?

:echo g:loaded_netrwPlugin

## 

Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by nuko8** [comment]
Or, open MacVim and type <kbd>:Explore</kbd>.

You should see `(netrw v162d)` on the top-right corner of the window.  If not and you only see a file listing, type <kbd>I</kbd> to toggle the banner.

**Comment by NeilGirdhar** [comment]
Thank you, I have 162d.  If this error happens again, I'll reopen this bug.
