### ISSUE TITLE
Adding an autocommand for TextChangedI suppresses TextChanged events

### ISSUE THREAD

**Issue by malcolmr** [vim/vim#8932]
Loading matchparen (i.e. by default) appears to cause some TextChanged events to be swallowed, breaking plugins that want to take action when the text has changed.

**To Reproduce**

1. vim --clean
2. `:au TextChanged * echo 'TextChanged ' . b:changedtick` to emit a visible message whenever TextChanged is raised.
3. Type `ifoo<ESC>`
4. You'll see "TextChanged 5" appear.

vs.

1. vim --clean
2. `:runtime plugin/matchparen.vim`
3. `:au TextChanged * echo 'TextChanged ' . b:changedtick`
4. Type `ifoo<ESC>`
5. (nothing happens; the TextChanged event appears not to be delivered.)
6. Type `D` to delete to EOL.
7. You'll see "TextChanged 6" appear.

**Expected behavior**
TextChanged should be delivered to plugins whether or not matchparen is loaded.

**Environment (please complete the following information):**
 - Vim version: Debian's 8.1.2269, but I also reproduced back to 8.0.1493 myself.
 - OS: Debian testing
 - Terminal: gnome-terminal

**Additional context**
I assume this is something caused by matchparen's `Highlight_Matching_Pair()`, which runs on both TextChangedI and TextChanged.

**Comment by malcolmr** [comment]
Now that I write the above, is it possible that the _existence_ of the TextChangedI autocmd is what's suppressing the TextChanged event after insert finishes?

**Comment by chrisbra** [comment]
I think this is caused by the `TextChangedI` autocommand. It resets `curbuf->b_last_changedtick`  (see here: https://github.com/vim/vim/blob/be01090efad242e30728275dea05420db6f96257/src/edit.c#L1477-L1493 ) and then the check in main.c to trigger TextChanged does not return true, because `curbuf->b_last_changedtick` is no longer different than `b:changedtick` (see here: https://github.com/vim/vim/blob/be01090efad242e30728275dea05420db6f96257/src/main.c#L1321-L1327)

**Comment by malcolmr** [comment]
I think that analysis is correct. That unfortunately means that TextChanged fires differently based on whether or not a TextChangedI autocommand is registered (i.e. `has_textchangedI()`), which doesn't _sound_ like it'd be intended behavior.

I'm also wondering what a reasonable workaround is.

If it is TextChangedI that's suppressing this (and assuming that a plugin doesn't want to know about changes while the user is in insert mode), then perhaps adding an additional autocommand for InsertLeave would work for now (and perhaps checking `b:changedtick` if it was important to know whether or not the text had actually changed).

**Comment by chrisbra** [comment]
Hm, I think something like the following patch should fix it:
```patch
diff --git a/src/edit.c b/src/edit.c
index 070d84c60..f41407c2f 100644
--- a/src/edit.c
+++ b/src/edit.c
@@ -22,6 +22,8 @@
 // which is not allowed.
 static int     compl_busy = FALSE;

+static varnumber_T b_last_changedtick_saved;
+

 static void ins_ctrl_v(void);
 static void insert_special(int, int, int);
@@ -154,6 +156,9 @@ edit(
     // Remember whether editing was restarted after CTRL-O.
     did_restart_edit = restart_edit;

+    // Remember b_last_changedtick for TextChanged autocommands
+    b_last_changedtick_saved = curbuf->b_last_changedtick;
+
     // sleep before redrawing, needed for "CTRL-O :" that results in an
     // error message
     check_for_delay(TRUE);
@@ -839,6 +844,7 @@ doESCkey:
                if (cmdchar != 'r' && cmdchar != 'v' && c != Ctrl_C)
                    ins_apply_autocmds(EVENT_INSERTLEAVE);
                did_cursorhold = FALSE;
+               curbuf->b_last_changedtick = b_last_changedtick_saved;
                return (c == Ctrl_O);
            }
            continue;
```

**Comment by brammool** [comment]
> I think that analysis is correct. That unfortunately means that
> TextChanged fires differently based on whether or not a TextChangedI
> autocommand is registered (i.e. `has_textchangedI()`), which doesn't
> _sound_ like it'd be intended behavior.
> 
> I'm also wondering what a reasonable workaround is.
> 
> If it is TextChangedI that's suppressing this (and assuming that a
> plugin doesn't want to know about changes while the user is in insert
> mode), then perhaps adding an additional autocommand for InsertLeave
> would work for now (and perhaps checking `b:changedtick` if it was
> important to know whether or not the text had actually changed).

Yes, this is not intended.  The TextChanged and TextChangedI events
should be independent.  I don't think that Christian's proposal is the
right fix, we need to have two last_changedtick values, one for Insert
and one for Normal mode.

Christian, can you give that a go?


-- 
How many light bulbs does it take to change a person?

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
of course. Will prepare a PR after the weekend.
