### ISSUE TITLE
I think I found an issue with `errorformat` for `:compiler jest`

### ISSUE THREAD

**Issue by refaelsh** [vim/vim#8938]
Hi all,

I think I found an issue with `errorformat` for `:compiler jest`. It does not filter out `console.log` thingies. Here are some screenshots (you can see the `console.log` thingies):
![6_002](https://user-images.githubusercontent.com/2750775/135728554-24c830de-1e8f-4b58-b418-83445a8cfb9e.jpg)
Then I press enter and I see the `console.log` thingies in the quicklist window:
![6_001](https://user-images.githubusercontent.com/2750775/135728570-95c183c3-2fee-4b86-9c8d-da25b561428b.jpg)
I think its a problem with the `errorformat` for `:compiler jest`. What do you guys think?

Thanks.

**Comment by dkearns** [comment]
I think you are correct, thanks.

I know the 'efm' needs improving generally and I'll, at least, take at look at addressing this specific issue in the next week or so.

**Comment by refaelsh** [comment]
@dkearns Thank you very much! :-)

**Comment by dkearns** [comment]
Sorry, I have been a bit side-tracked.

Maybe this will fix your immediate problem until I take a better look.

```diff
--- a/jest.vim  2020-08-16 17:41:56.336030379 +1000
+++ b/jest.vim  2021-11-14 22:41:54.604720497 +1100
@@ -18,9 +18,10 @@
 " CompilerSet makeprg=npx\ jest\ --no-colors

 CompilerSet makeprg=jest\ --no-colors
-CompilerSet errorformat=%E\ \ ●\ %m,
+CompilerSet errorformat=%E\ \ ●\ %\\%%(Console%\\)%\\@!%m,
                       \%Z\ %\\{4}%.%#Error:\ %f:\ %m\ (%l:%c):%\\=,
                       \%Z\ %\\{6}at\ %\\S%#\ (%f:%l:%c),
+                      \%Z\ %\\{6}at\ %\\S%#\ %f:%l:%c,
                       \%+C\ %\\{4}%\\w%.%#,
                       \%+C\ %\\{4}%[-+]%.%#,
                       \%-C%.%#,
```

**Comment by rsheink** [comment]
Yes, it definitely helps. Thank you very much!

**Comment by refaelsh** [comment]
Yes, that helps a lot! Thank you very much!

**Comment by brammool** [comment]
I received updated files from Doug, will be in the next runtime update.
