### ISSUE TITLE
'make scripttests' fails with Python 3.10

### ISSUE THREAD

**Issue by zdohnal** [vim/vim#8959]
**Describe the bug**
Vim test suite fails with python 3.10 rc2 - python changed the output messages a little.

**To Reproduce**
1. ./configure --with-features=huge --enable-python3interp=dynamic --enable-gui=none
2. make
3. make scripttests

**Expected behavior**
Tests passed

**Environment (please complete the following information):**
 - vim-8.2, patchlevel 3477 (clean upstream master)
 - OS: Fedora 36 (rawhide)
 - Terminal: GNOME Terminal

[Reported failures](https://github.com/vim/vim/files/7286262/failures.txt)

There are two failures, because the actual result doesn't match/equal expected string:

1.
```
command line..script /home/user/vim/src/testdir/runtest.vim[486]..function RunTheTest[44]..Test_python3_dict[2]..
AssertException line 9: Pattern 'Vim(py3):SystemError: \\(<built-in function eval> returned NULL without setting an error\\|error return without exception set\\)' does not match 'Vim(py3):SystemError: <built-in function eval> returned NULL without setting an exception'
```

2.
```
command line..script /home/user/vim/src/testdir/runtest.vim[486]..function RunTheTest[44]..Test_python3_errors
line 1204: Expected 'vim.foreach_rtp(NoArgsCall()):(<class ''TypeError''>, TypeError(''__call__() takes exactly 1 positional argument (2 given)'',))' but got 'vim.foreach_rtp(NoArgsCall()):(<class ''TypeError''>, TypeError(''__call__() takes 1 positional argument but 2 were given'',))'
```

I can provide a PR for the first (adding a new 'or' into system error pattern), but the second is tricky for me - ```Test_python3_errors``` uses ```assert_equal()``` in the test, so I've tried to change it to ```assert_match()``` and change the corresponding line in ```expected``` variable into a pattern (so the test can pass even with older pythons), but it didn't work - the test suite started to report 'mismatch' even for two identical lines...

I'll create a PR once I verify the fix for 1. didn't break anything for older pythons (at least for python 3.9.7, which is in stable Fedoras).

**Comment by brammool** [comment]
#8969 was included, can this issue be closed or is there a remaining problem.

**Comment by chrisbra** [comment]
so let's close it. If there are remaining problems, please let us know.
