### ISSUE TITLE
MicroPython Support

### ISSUE THREAD

**Issue by binaryben** [vim/vim#896]
Is it possible to include support for MicroPython in the same way Ruby, Python, Python 3, etc. is?

**Comment by chrisbra** [comment]
what would be the advantage over regular python?

**Comment by binaryben** [comment]
Availability on certain microcontrollers is the main benefit in reality. I have a variant of Tiny Core Linux (PiCore) on my Raspberry Pi, which has MicroPython installed by default as it is lightweight. 

I would like to be able to use Vim on that, and be able to code for microcontrollers which use MicroPython (mainly the ESP8266/8285 at this point).

**Comment by chrisbra** [comment]
closing as not planned
