### ISSUE TITLE
mode() indicates current mode is Operator-pending in operatorfunc

### ISSUE THREAD

**Issue by obcat** [vim/vim#8960]
**Describe the bug**

In an operatorfunc, `mode(1)` indicates the current mode is Operator-pending; it returns `no`, `nov`, `noV` or `noCTRL-V`. But it seems a bit strange because the text to be operated on has already been determined at that moment. I think it makes more sense if it returns a Normal mode that the operator was used in, i.e. `n`, `niI`, `niR` or `niV`.

**To Reproduce**

1. Run `vim -Nu NONE`.

1. `:source` this script:

    ```vim
    nnoremap <expr> ,o SetOperatorFunc() .. 'g@'
    function SetOperatorFunc()
      set operatorfunc=OperatorFunc
      return ''
    endfunction
    function OperatorFunc(_)
      echo mode(1)
    endfunction
    let outputs = ''
    let outputs ..= execute("normal ,ol")
    let outputs ..= execute("normal ,ovl")
    let outputs ..= execute("normal i\<C-o>,ol")
    let outputs ..= execute("normal i\<C-o>,ovl")
    echo outputs[1 :]
    ```

    This is echo'ed:

    ```
    no
    nov
    no
    nov
    ```

**Expected behavior**

This is echo'ed:

```
n
n
niI
niI
```

**Environment**

- Vim 8.2.3469
- macOS 10.15.7
- iTerm2

**Additional context**

Making this change not only makes sense, but also brings some benefits I believe; we can use it to change the operator behavior depending on the kind of the Normal mode, like this:

```vim
nnoremap <expr> ,p SetOperatorFunc() .. 'g@l'
function SetOperatorFunc()
  set operatorfunc=PutWithHighlight
  return ''
endfunction
function PutWithHighlight(_)
  normal! p
  if mode(1)[: 1] ==# 'ni' && getregtype('"') ==# 'v' && len(getreg('"', 1, 1)) == 1
    " Adjust the cursor position.
    normal! l
  endif
  call Highlight(getpos("'["), getpos("']"))
endfunction
```

**Comment by zeertzjq** [comment]
> Making this change not only makes sense, but also brings some benefits I believe; we can use it to change the operator behavior depending on the kind of the Normal mode, like this:

I can think of an alternative to this in #8967.

**Comment by obcat** [comment]
Fixed by https://github.com/vim/vim/commit/75c30e96cf280a8cc01ac01c41a9252db3e503cc.
