### ISSUE TITLE
heap-buffer-overflow in vim at do_put (src/register.c:2040)

### ISSUE THREAD

**Issue by irfanariq** [vim/vim#8962]
Hello,

We are currently working on fuzz testing feature, and we found a **heap-buffer-overflow** on `vim`.

The stack traces are as follow:
```st
==25120==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7ff42e60063a at pc 0x7ff4330bcd82 bp 0x7ffc8afb0370 sp 0x7ffc8afafb18
WRITE of size 2 at 0x7ff42e60063a thread T0
    #0 0x7ff4330bcd81 in __interceptor_memmove (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x7ad81)
    #1 0x55678d795cde in do_put .../vim-git/src/register.c:2040
    #2 0x55678d672799 in nv_put_opt .../vim-git/src/normal.c:7515
    #3 0x55678d671c18 in nv_put .../vim-git/src/normal.c:7396
    #4 0x55678d64893b in normal_cmd .../vim-git/src/normal.c:1099
    #5 0x55678da6c76a in main_loop .../vim-git/src/main.c:1501
    #6 0x55678da6b501 in vim_main2 .../vim-git/src/main.c:878
    #7 0x55678da6abc5 in main .../vim-git/src/main.c:425
```
Here is the full stack trace : [full_stacktrace_poc_4.zip](https://github.com/vim/vim/files/7288116/full_stacktrace_poc_4.zip)

**Step to reproduce**

We configured `vim` using `CFLAGS="-g -O0 -fsanitize=address" CXXFLAGS="-g -O0 -fsanitize=address" LDFLAGS="-g -O0 -fsanitize=address" ./configure --prefix=$(pwd)/` and build it using `make -j10`, and run it with:

```
./vim -s <attached file> NONE -e ':qa!' -d -- -p1 -r -C + -M -m
```
Attachment: [input_vim_poc_4.zip](https://github.com/vim/vim/files/7288118/input_vim_poc_4.zip)

**Environment**
- OS: Ubuntu 18.04.5 LTS
- GCC version: gcc 7.5.0
- vim version: latest commit (f67d3fb7) of master branch in github ([link](https://github.com/vim/vim/tree/f67d3fb7363ebc9454f9bb582de3978609a4fd6b))

Thank you.

**Comment by brammool** [comment]
Please reduce the input to the absolute minimum to reproduce the problem.
