### ISSUE TITLE
DIfference between ^ and _ in normal mode?

### ISSUE THREAD

**Issue by trusktr** [vim/vim#897]
They same to do the same thing, so was wondering if there's any difference. If there's no difference, maybe the key can be changed so by default one of them is more useful for something else? Or is there a reason for them to be the same?

**Comment by chrisbra** [comment]
the difference becomes apparent, once you use them in operator pending mode.

If you want to map them away, you are free to do so however.

**Comment by trusktr** [comment]
@chrisbra If I map them, no one benefits. If you make different behaviors in vim, everyone benefits (people who really want old behavior can easily add the mapping).

**Comment by brammool** [comment]
Please don't use issues for discussions, the maillist is for that.
