### ISSUE TITLE
Vim doesn't correctly clear its pager during scrolling, when launched inside tmux and 'termguicolors' enabled

### ISSUE THREAD

**Issue by bfrg** [vim/vim#8973]
**Describe the bug**

Vim doesn't clear the pager screen correctly when the `more-prompt` is displayed and the pager is first scrolled down and then back up again. This happens only when Vim is launched inside tmux with `termguicolors` enabled and a non-default `colorscheme` loaded.

**To Reproduce**
1. Run `tmux -L foo -f /dev/null`
2. Run `vim --clean -S test.vim`, with
   ```vim
   let &t_8f = "\<esc>[38;2;%lu;%lu;%lum"
   let &t_8b = "\<esc>[48;2;%lu;%lu;%lum"
   set termguicolors
   colorscheme koehler
   ```
3. Run `:hi`, scroll down to the bottom with `G`, then back to the top with `g`.
4. Result: The top part of the output of `:hi` is displayed along with the bottom output of `:hi`. It seems that Vim doesn't clear the pager screen before scrolling to the top again (see screenshots below).

**Screenshots**
![output](https://user-images.githubusercontent.com/6266600/136388072-bc43e5d2-34c9-4579-bafb-2dc6a935ae8b.png)
**Left:** after running `:hi`, **Center:** after pressing `G`, **Right:** after pressing `g`

**Environment**
 - Vim version `8.2.3484`
 - OS: Gentoo Linux
 - Terminal: `xfce4-terminal`, `alacritty`, `st`

**Comment by bfrg** [comment]
`$TERM` is set to `tmux-256color`.

**Comment by lacygoill** [comment]
> But when I run vim --clean instead of the above test.vim script inside tmux, t_ut is empty and yet there's no issue with the pager.

Because the `ctermbg` attribute of the `Normal` highlight group is not set:

    $ vim --clean
    :hi Normal

    Normal         xxx cleared

**Comment by lacygoill** [comment]
IOW, the issue is that Vim fails to properly clear the top line of the pager when it uses the background color of the `Normal` highlight group, instead of the background color of the terminal.

**Comment by bfrg** [comment]
> IOW, the issue is that Vim fails to properly clear the top line of the pager when it uses the background color of the Normal highlight group, instead of the background color of the terminal.

It's not just the top line. Try it on the output of `:scriptnames`.

Scrolling up with `k` works fine, but not when jumping to the top with `g`, or scrolling with  `u` and `b`.
