### ISSUE TITLE
zipfile opens an empty buffer after 8.2.3468

### ISSUE THREAD

**Issue by lilydjwg** [vim/vim#8974]
**To Reproduce**
1. Create a non-empty zip file, e.g. xxx.zip
1. Run `vim xxx.zip`
2. Select one entry inside the zip listing and press Enter to open/view it
3. An empty buffer is open. Buffer name is `~/.../zipfile:/.../xxx.zip::xxx.txt`, i.e. with current directory prepended.

**Expected behavior**
netrw should read the zipped xxx.txt's content into new buffer.

**Environment (please complete the following information):**
 - Vim version: from 8.2.3468 (found by git bisect, first bad commit: c6376c798433bcb9ee38a8664299d11454546950) to 8.2.3486 (latest)
 - OS: Arch Linux
 - Terminal: GNOME Terminal

**Comment by Shane-XB-Qian** [comment]
looks it's not related to 'netrw' but 'zip.vim', though same auther: @cecamp 
// looks 'zip.vim' was not a complete runtime, it set ft of zip to 'tar' also?!......

**Comment by Shane-XB-Qian** [comment]
FYI: 
the difference between tar and zip:
- `tarfile::bar.txt`
- `~/zipfile:/home/shane/bar.zip::bar.txt`

// bar.tar and bar.zip and bar.txt all located at /home/shane same.

**Comment by Shane-XB-Qian** [comment]
um.. actually tar.vim is working still somehow for now, but zip.vim is not.
// **~/zipfile:** that `~/` looks odd to me as first impression.

// i did not verify your patch above.

**Comment by Shane-XB-Qian** [comment]
#8903
#9023

**Comment by itchyny** [comment]
Okay, thanks. Unfortunate that fixing a bug broke an existing plugin, but using `zipfile://` looks better solution than proposed in this thread. The zip plugin implementation is valid under the idea of URI, where `//authority` is optional, but Vim cannot distinguish this resource identifier from actual (relative) file paths. Based on the implementation of `path_with_url` (and `vim_isAbsName`), using `://` in plugins looks a good convention to me.

**Comment by itchyny** [comment]
@cecamp @chrisbra @lacygoill Do you have any thoughts?

**Comment by lacygoill** [comment]
Fixed in the latest [update of the runtime files](https://github.com/vim/vim/commit/519cc559b08b800edc429688aece7ad6a00d41eb#diff-c3431e35dce9ef0098df28d227c4539fc744a55e32dca0291be3eeddab0fe245).
