### ISSUE TITLE
documentation improvement for modeline implied 'set'

### ISSUE THREAD

**Issue by wwalker** [vim/vim#8979]
**Describe the bug**
A clarification on the vim modeline help documentation.

Move this:
```
Note that for the first form all of the rest of the line is used, thus a line
like:
   /* vi:ts=4: */
will give an error message for the trailing "*/".  This line is OK:
   /* vi:set ts=4: */
....
```

from modeline-version up into modeline, and Move it from a sentence "Note that ..." to a real `NOTE:`

I believe this would make finding out why `/* vi:ts=4: */` throws an error, yet `/* vi:ts=4:` does not.

I will provide a PR.

**Comment by chrisbra** [comment]
closing for #8980
