### ISSUE TITLE
Vim website advertises other editors.

### ISSUE THREAD

**Issue by trusktr** [vim/vim#898]
For example, here's a screenshot of vim.org suggesting to use IntelliJ instead, which seems somewaht out of place:

![screen shot 2016-07-03 at 11 46 03 am](https://cloud.githubusercontent.com/assets/297678/16547051/ca28f13e-4113-11e6-8006-ec32417a463f.png)

**Comment by brammool** [comment]
The ads rotate and depend on your history.
