### ISSUE TITLE
Parsing of `g:` can be confusing in vim9script

### ISSUE THREAD

**Issue by tjdevries** [vim/vim#8982]
This is more of a question about vim9script than a feature request exactly.

It seems a bit difficult to parse/understand the setting of global variables vs. a `:global` command in vim9script at the moment. For example:

```vim
# This sets hello to true
g:hello = true

# This does :global command
g:^var:norm! dd

# This gives an error
g:var:norm! dd
```

It might be nice if you just could not call `global` in short form in vim9script?

**Comment by dpelle** [comment]
@lacygoill wrote:

>  I doubt many people would complain; most of the time, they use the slash anyway.

The colon `:` delimiter is often used as as slash `/` is not convenient when the string is a path.

**Comment by brammool** [comment]
> > g:pat:cmd is clearly confusing.  We should at least not recognize g: as
> > the :global command.
> 
> Same thing for `s:pat:rep`:
> ```vim
> vim9script
> 
> 'pat'->setline(1)
> 
>  # This executes a :substitute command
> s:^pat:rep
> 
>  # This gives an "Undefined variable" error
> s:pat:rep
> ```

Yes, what applies to g: also applies to s:.

> > Do we need to disallow more characters?
> 
> Yes, at least the hyphen/minus.

You mean for g->func()

For "g - var" we can say that "g" followed by space is not the :global
command.  I don't think that users write a space after "g" used as a
global command, thus that should work.

> Probably the number sign too (`#`).

Well, "g#" can't be the start of anything but a global command, I don't
think we need to do anything about tha.

> Possibly the dot as well.

OK, "g.pat.cmd" is unusual, while "g.member" could be the start of an
expression.  Using "g" as a variable is unusual though.

> And maybe the arithmetic operators (`+`,
> `*`, `/`, `%`) when they are followed by an equal sign; because in
> that specific case, there is ambiguity with assignment operators.
> 
> For example:
> ```vim
> g += a + b
> ```
> Is this a global command using `+` as a pattern delimiter?  Or is it
> an assignment which increments the variable `g`?  It turns out that
> Vim parses this line as a global command, but it's not obvious.  For
> the reader, it looks like an incrementation.

That can be avoided by not seeing "g " as the global command.  We can
still allow "g+pat+cmd".

> > Again, it might irritate some users who are used to certain characters.
> 
> That's the price to pay to be able to drop `:let`/`:var` for every
> assignment, and it's a small price.  IMO, predictability is more
> important, and I don't see why we couldn't – at least temporarily –
> disallow some characters, then wait for feedback.

The rules for when "g" means ":global" are getting a bit complicated,
requiring the use of "global" always makes it easier.  Still, I'm so
used to using g/pat/cmd that it's a surprise if that doesn't work.

Requiring a colon for every Ex command seems too much, I don't think we
need that.


-- 
hundred-and-one symptoms of being an internet addict:
126. You brag to all of your friends about your date Saturday night...but
     you don't tell them it was only in a chat room.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> Well, "g#" can't be the start of anything but a global command, I don't
   > think we need to do anything about that.

The issue is not about ambiguity but consistency.

This works:
```vim
vim9script
'pat'->setline(1)
g #pat# ls
```
This does not:
```vim
vim9script
filter #pat# ls
```
    E476: Invalid command: filter #pat# ls

Either it should work in both cases, or it should fail in both cases.

Besides, `#` is a comment leader; so one could expect that `g # pat # cmd` fails, because everything after the first `# ` is ignored.  The fact that it works creates an exception to remember.

**Comment by brammool** [comment]
> > Requiring a colon for every Ex command seems too much, I don't think
> > we
> > need that.
> 
> I actually feel that is quite nice to be forced to prepend Ex commands
> with colons. For example, I have been looking at some of the plugins
> that have been written in vim9 already and it is already a pattern I
> see sometimes anyway.
> 
> For example: https://github.com/monkoose/vim9-stargate/
> 
> ```vim
> vim9script
> 
> 
> def Message(text: string, color: string)
>   :redraw
>   :execute 'echohl StargateVIM9000'
>   :echo ' VIM9000 '
>   :execute 'echohl ' .. color
>   :echon ' ' .. text .. ' '
>   :echohl None
> enddef
> 
> 
> export def ErrorMessage(text: string)
>   Message(text, 'StargateErrorMessage')
> enddef
> 
> 
> export def StandardMessage(text: string)
>   Message(text, 'StargateMessage')
> enddef
> ```
> 
> I think this is quite a nice pattern and make its very obvious to
> future readers of the plugin which lines are calling functions / doing
> expressions and which lines are calling Ex commands. In fact, several
> files in this plugin do not have any Ex commands, so you don't see a
> single line prefixed with `:`
> [Example](https://github.com/monkoose/vim9-stargate/blob/main/_import/galaxies.vim).
> 
> If you do not want to further consider the idea, that is fine though
> :) I will stop talking about it in this thread.

One of the main targets for Vim 9 script is to be more like mainstream
languages and reduce Vim-specific syntax.  If we require a colon for
every command, then also get ":for" / ":endfor", ":if" / ":endif", etc.
I think this will make Vim script look too different and unusual.
Only requiring ":" for some commands would be inconsistent.

Requiring a colon for what is Vim-specific seems OK, thus requiring the
use of a colon before a range, something you won't see in another
language anyway.

-- 
Amazing but true: If all the salmon caught in Canada in one year were laid
end to end across the Sahara Desert, the smell would be absolutely awful.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
> If requiring a colon for Ex commands is too much, why not at least
> require full command names in `vim9script` files? Being able to write
> `:s/foo/bar` instead of `:substitute/foo/bar` is great on the
> command-line, but hardly a life changer in script files. It's not like
> everyone is writing 100 plugins every day. Personally I never had the
> need for shorter Ex commands in script files, and I can't think of
> another language providing this feature. Who really needs `:s`, `:su`,
> `:sub`, `:subs`, `:subst`, `:substi`, `:substit`, `:substitu`,
> `:substitut`? And that's only for _one_ command. Forcing the full name
> `:substitute` in script files will also make plugins look more
> consistent.

For long time Vim (and Vi) users, it's very unusual to type "substitute"
as a full command name.  Some may not even know that "s" is short for
"substitute" and just always use s/pat/repl/ without even thinking about
it.

I also think that requiring full command names is a step back from
legacy Vim script.  And it creates a difference between typing an Ex
command and writing Vim script.

Thus I think it is drifting too far away from what Vim and Vi users are
used to.

-- 
hundred-and-one symptoms of being an internet addict:
138. You develop a liking for cold coffee.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
