### ISSUE TITLE
cannot expand wildcard when 'wildignorecase' is set and Vim used as manpager

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8991]
**Describe the bug**

We cannot expand a wildcard when `'wildignorecase'` is set and Vim is used as a manpager.

**To Reproduce**

Run this shell command:

    cd /tmp && MANPAGER='vim -Nu NONE +"set wildignorecase" -' man man

Write this Ex command on the command-line:

    :find *

Press the `Tab` key to expand the `*` wildcard.

The wildcard is not expanded.

**Expected behavior**

The wildcard is expanded into the first directory present under `/usr/include` (on my machine, that's `CppUTest/`).

**Environment**

 - Vim version: 8.2 Included patches: 1-3496
 - OS: Ubuntu 20.04.3 LTS
 - Terminal: XTerm(353)

**Additional context**

The issue disappears when `'wildignorecase'` is reset:

    cd /tmp && MANPAGER='vim -Nu NONE +"set nowildignorecase" -' man man
                                            ^^

---

I don't see why `'wildignorecase'` would have such an effect, but if there is a good reason, then maybe it suggests that the option should be turned from a global one into a buffer-local one; so that we can turn it on in all buffers exept the ones used to read manpages.

---

The help for `'wildignorecase'` and `'fileignorecase'` could be slightly improved:
```diff
diff --git a/runtime/doc/options.txt b/runtime/doc/options.txt
index 6bf0a5820..7fb3d9b8a 100644
--- a/runtime/doc/options.txt
+++ b/runtime/doc/options.txt
@@ -3255,7 +3255,7 @@ A jump table for the options with a short description can be found at |Q_op|.
 'fileignorecase' 'fic'	boolean	(default on for systems where case in file
 				 names is normally ignored)
 			global
-	When set case is ignored when using file names and directories.
+	If set, case is ignored when using file names and directories.
 	See 'wildignorecase' for only ignoring case when doing completion.
 
 					*'filetype'* *'ft'*
@@ -8820,7 +8820,7 @@ A jump table for the options with a short description can be found at |Q_op|.
 			*'wildignorecase'* *'wic'* *'nowildignorecase'* *'nowic'*
 'wildignorecase' 'wic'	boolean	(default off)
 			global
-	When set case is ignored when completing file names and directories.
+	If set, case is ignored when completing file names and directories.
 	Has no effect when 'fileignorecase' is set.
 	Does not apply when the shell is used to expand wildcards, which
 	happens when there are special characters.
```
Rationale: the current repetition of the "when" conjunction sounds awkward, and the absence of a comma between the 2 propositions makes the sentences harder to understand.

**Comment by chrisbra** [comment]
I think it fails when trying to open the directory `/` at `opendir()` here: 

https://github.com/vim/vim/blob/53ba95e4f0a82f6dab1791bb01f6cddc9b3f61b3/src/filepath.c#L3707-L3709

I get a permission denied error, I have no idea why this would fail or why `:set wildignorecase` matters here. Here is a part from strace:

```
  select(3, [2], [], [2], NULL)           = 1 (in [2])
  read(2, ":", 4096)                      = 1
  select(3, [2], [], [2], {tv_sec=0, tv_usec=0}) = 0 (Timeout)
  ioctl(1, TCGETS, {B38400 opost -isig -icanon -echo ...}) = 0
  ioctl(2, TCGETS, {B38400 opost -isig -icanon -echo ...}) = 0
  select(3, [2], [], [2], {tv_sec=0, tv_usec=0}) = 0 (Timeout)
  write(1, "\33[?25l\33[66;1H\33[K\33[66;1H:\33[34h\33[?"..., 35) = 35
  select(3, [2], [], [2], {tv_sec=4, tv_usec=0}) = 1 (in [2], left {tv_sec=3, tv_usec=600849})
  read(2, "f", 4096)                      = 1
  select(3, [2], [], [2], {tv_sec=0, tv_usec=0}) = 0 (Timeout)
  select(3, [2], [], [2], {tv_sec=0, tv_usec=0}) = 0 (Timeout)
  write(1, "f", 1)                        = 1
  select(3, [2], [], [2], {tv_sec=4, tv_usec=0}) = 1 (in [2], left {tv_sec=3, tv_usec=936275})
  read(2, "i", 4096)                      = 1
  select(3, [2], [], [2], {tv_sec=0, tv_usec=0}) = 0 (Timeout)
  select(3, [2], [], [2], {tv_sec=0, tv_usec=0}) = 0 (Timeout)
  write(1, "i", 1)                        = 1
  select(3, [2], [], [2], {tv_sec=4, tv_usec=0}) = 1 (in [2], left {tv_sec=3, tv_usec=913120})
  read(2, "n", 4096)                      = 1
  select(3, [2], [], [2], {tv_sec=0, tv_usec=0}) = 0 (Timeout)
  select(3, [2], [], [2], {tv_sec=0, tv_usec=0}) = 0 (Timeout)
  write(1, "n", 1)                        = 1
  select(3, [2], [], [2], {tv_sec=4, tv_usec=0}) = 1 (in [2], left {tv_sec=3, tv_usec=966589})
  read(2, "d", 4096)                      = 1
  select(3, [2], [], [2], {tv_sec=0, tv_usec=0}) = 0 (Timeout)
  select(3, [2], [], [2], {tv_sec=0, tv_usec=0}) = 0 (Timeout)
  write(1, "d", 1)                        = 1
  select(3, [2], [], [2], {tv_sec=4, tv_usec=0}) = 1 (in [2], left {tv_sec=3, tv_usec=914822})
  read(2, " ", 4096)                      = 1
  select(3, [2], [], [2], {tv_sec=0, tv_usec=0}) = 0 (Timeout)
  select(3, [2], [], [2], {tv_sec=0, tv_usec=0}) = 0 (Timeout)
  write(1, " ", 1)                        = 1
  select(3, [2], [], [2], {tv_sec=4, tv_usec=0}) = 1 (in [2], left {tv_sec=3, tv_usec=842718})
  read(2, "*", 4096)                      = 1
  select(3, [2], [], [2], {tv_sec=0, tv_usec=0}) = 0 (Timeout)
  select(3, [2], [], [2], {tv_sec=0, tv_usec=0}) = 0 (Timeout)
  write(1, "*", 1)                        = 1
  select(3, [2], [], [2], {tv_sec=4, tv_usec=0}) = 1 (in [2], left {tv_sec=3, tv_usec=622954})
  read(2, "\4", 4096)                     = 1
  select(3, [2], [], [2], {tv_sec=0, tv_usec=0}) = 0 (Timeout)
  getcwd("/home/chrisbra/code/vim-src/src", 4096) = 32
  openat(AT_FDCWD, "/", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = -1 EACCES (Permission denied)
  openat(AT_FDCWD, "/", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = -1 EACCES (Permission denied)
  write(1, "\33[?25l\r\r\n", 9)           = 9
  select(3, [2], [], [2], {tv_sec=0, tv_usec=0}) = 0 (Timeout)
  write(1, ":find *\33[34h\33[?25h", 18)  = 18
  select(3, [2], [], [2], {tv_sec=4, tv_usec=0} <detached ...>
```

**Comment by chrisbra** [comment]
Ah, I found it. 

It's not a Vim problem. We are running `man` and in my case the apparmor profile was active and prevented opening `/`, even so my user has permissions for that. I found by inspecting `dmesg -T`, which mentioned:

    [Tue Nov 30 22:17:34 2021] audit: type=1400 audit(1638307055.326:87): apparmor="DENIED" operation="open" profile="/usr/bin/man" name="/" pid=285015 comm="vim" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0

This can be disabled, by using `sudo aa-complain /etc/apparmor.d/usr.bin.man` in which case it starts to work again :)

(Re-enable it by using `sudo aa-enforce /etc/apparmor.d/usr.bin.man` again).

Note: `wildignorecase` is required, because only in this case will Vim try to open the `/` directory handle, while without it, it will directly start to traverse at `/usr/include`, which apparently is allowed for `man`.

**Comment by lacygoill** [comment]
Thank you very much for looking into this.  I can confirm that this command fixes the issue:

    $ sudo aa-complain /etc/apparmor.d/usr.bin.man

    [Tue Nov 30 17:50:17 2021] audit: type=1400 audit(1638291018.489:66): apparmor="DENIED" operation="open" profile="/usr/bin/man" name="/" pid=37378 comm="vim" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0

I'll need time to study it.  I think it might be worth documenting at some point at `:help man.vim`.  I'll try to come up with a patch once I better understand how `man(1)` works.
