### ISSUE TITLE
assignment in loop makes gradually slow.

### ISSUE THREAD

**Issue by mattn** [vim/vim#8996]
### Steps to reproduce

1. Create vim9script below.
```vim
vim9script
var k = 0
for i in range(0, 999)
  redraw
  echon i
  for j in range(0, 999)
    k = j
  endfor
endfor
echon 'Goal!'
```

2. `:so test.vim`

### Expected behaviour

Even processing time per each iteration.

### Operating system

Windows 10

### Version of Vim

8.2.3494

**Comment by chrisbra** [comment]
I tried unletting some of those variables, but apparently :unlet of those variables does not work? This throws E1081, but that does not have a help tag :(

interestingly, this is much faster:
```vim
vim9script
def Func()
for i in range(0, 999)
	var k = 0
  redraw
  echon i
  for j in range(0, 999)
    k = j
  endfor
endfor
echon 'Goal!'
enddef
call Func()
```

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> 1. Create vim9script below.
> ```vim
> vim9script
> var k = 0
> for i in range(0, 999)
>   redraw
>   echon i
>   for j in range(0, 999)
>     k = j
>   endfor
> endfor
> echon 'Goal!'
> ```
> 
> 2. `:so test.vim`
> 
> ### Expected behaviour
> 
> Even processing time per each iteration.

This appears to create a million script variables.
The "j" variable is not reused, but created every time.  I don't think
that is needed.  Let me change that and check that nothing breaks.

-- 
hundred-and-one symptoms of being an internet addict:
154. You fondle your mouse.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
