### ISSUE TITLE
smartcase requires ignorecase

### ISSUE THREAD

**Issue by 89z** [vim/vim#9001]
### Steps to reproduce

use `set smartcase` or similar

### Expected behaviour

search for `case`, only `case` is found, not `Case`

### Operating system

Windows

### Version of Vim

v8.2.3386

**Comment by vim-ml** [comment]
On 2021-10-15, Steven Penny wrote:
> Steps to reproduce
> 
> use set smartcase or similar
> 
> Expected behaviour
> 
> search for case, only case is found, not Case
> 
> Operating system
> 
> Windows
> 
> Version of Vim
> 
> v8.2.3386

That is intentional.  From ":help 'smartcase'":

    Override the 'ignorecase' option if the search pattern contains upper
    case characters.  Only used when the search pattern is typed and
    'ignorecase' option is on.

Regards,
Gary

**Comment by brammool** [comment]
The idea is that you can set 'smartcase' always, and then selectively set 'ignorecase' when desired.
Anyway, it has always worked like this, changing it now will not be appreciated by existing users.
