### ISSUE TITLE
Arch Linux PKGBUILD failed to build on latest version 

### ISSUE THREAD

**Issue by pheiduck** [vim/vim#9008]
### Steps to reproduce

1. Build Archlinux PKGBUILD with latest version 8.2.3523
2. Failed with: ```Expected 'bar' but got 'foo' Flaky test failed too often, giving up```

### Expected behaviour

no build errors

### Operating system

Arch Linux

### Version of Vim

8.2.3516 < 8.2.3523

**Comment by dpelle** [comment]
@pheiduck wrote:

> Failed with: Expected 'bar' but got 'foo' Flaky test failed too often, giving up

This ticket description is currently too short. We don't even know which test failed.
You need to copy more lines from the log in this ticket. Possibly attach the entire log when running tests.
