### ISSUE TITLE
Vim doesn't load YouCompleteMe if put in $HOME/.vim/pack/ycm/opt/YouCompleteMe

### ISSUE THREAD

**Issue by bstaletic** [vim/vim#901]
If [YouCompleteMe](https://github.com/Valloric/YouCompleteMe) is placed in `$HOME/.vim/pack/ycm/start/YouCompleteMe` it works perfectly, but if it is place in opt in stead of start it doesn't even load.

Output of [`vim --version`](https://bpaste.net/show/0a0ab9ad486f)
[My .vimrc](https://bpaste.net/show/9a356737b7dd)

Additional info:
- I don't believe this is a bug of YouCompleteMe as it is not even loaded
- YouCompleteMe is successfully loaded when need using [vim-plug](https://github.com/junegunn/vim-plug)
- I'm successfully running other packages residing in opt, namely taglist, YCM-Generator and Conque-GDB

Steps to reproduce:
1. mkdir -p $HOME/.vim/pack/ycm/opt
2. cd $HOME/.vim/pack/ycm/opt
3. git clone https://github.com/Valloric/YouCompleteMe
4. cd YouCompleteMe
5. git submodule update --init --recursive
6. mkdir -p $HOME/ycmd_build
7. cd $HOME/ycmd_build
8. cmake . ~/.vim/pack/ycm/opt/YouCompleteMe/third_party/ycmd/cpp
9. cmake --build . --target ycm_core --config Release
10. vim
11. :packadd YouCompleteMe

This is reproducible no matter how one compiles ycmd, or if one uses shallow cloneof the repo.

**Comment by ZyX-I** [comment]
If you _type_ `:packadd YouCompleteMe` it may be too late. This should work fine if you place this in the vimrc or e.g. use vim-addon-manager to load, but `:packadd` is not doing some things which Vim do at startup. Specifically, some autocommands like VimEnter which may be defined by plugin loaded at runtime are not run by `:packadd`, so making YCM load correctly with `:packadd` may require either editing YCM or Vim code.

VAM (vim-addon-manager) was mentioned because it does run these autocommands (AFAIR I coded this myself), don’t know whether or which of other plugin managers with such capability do as well.

**Comment by brammool** [comment]
bstaletic wrote:

> If [YouCompleteMe](https://github.com/Valloric/YouCompleteMe) is placed in `$HOME/.vim/pack/ycm/start/YouCompleteMe` it works perfectly, but if it is place in opt in stead of start it doesn't even load.
> 
> Output of [`vim --version`](https://bpaste.net/show/0a0ab9ad486f)
> [My .vimrc](https://bpaste.net/show/9a356737b7dd)
> 
> Additional info:
> - I don't believe this is a bug of YouCompleteMe as it is not even loaded
> - YouCompleteMe is successfully loaded when need using [vim-plug](https://github.com/junegunn/vim-plug)
> - I'm successfully running other packages residing in opt, namely taglist, YCM-Generator and Conque-GDB
> 
> Steps to reproduce:
> 1. mkdir -p $HOME/.vim/pack/ycm/opt
> 2. cd $HOME/.vim/pack/ycm/opt
> 3. git clone https://github.com/Valloric/YouCompleteMe
> 4. cd YouCompleteMe
> 5. git submodule update --init --recursive
> 6. mkdir -p $HOME/ycmd_build
> 7. cd $HOME/ycmd_build
> 8. cmake . ~/.vim/pack/ycm/opt/YouCompleteMe/third_party/ycmd/cpp
> 9. cmake --build . --target ycm_core --config Release
> 10. vim
> 11. :packadd YouCompleteMe
> 
> This is reproducible no matter how one compiles ycmd, or if one uses shallow cloneof the repo.

Can you check with 'verbose' set to 9 (or a bit higher or lower) what
happens when it is in the "start" directory and when it is in the "opt"
directory?  Also check the resulting value of 'runtimepath'.

What is your patch level?

## 

% cat /usr/include/sys/errno.h
#define EPERM       1       /\* Operation not permitted _/
#define ENOENT      2       /_ No such file or directory _/
#define ESRCH       3       /_ No such process _/
[...]
#define EMACS       666     /_ Too many macros */
%

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bstaletic** [comment]
My patch level is 1821. The 'runtimepath' lists YouCompleteMe's path after running packadd
I was trying to type `:packadd YouCompleteMe` If I use something like `au Filetype c packadd YouCompleteMe` in my vimrc it loads and works correctly.

Here are the log files with 'verbose' set to 9:
[YouCompleteMe in start](https://bpaste.net/show/8614036f5577)
[YouCompleteMe in opt loaded manually](https://bpaste.net/show/9cab31c8b61e)
[YouCompleteMe in opt loaded from vimrc](https://bpaste.net/show/a40fc4fc3d8d)
[This is the diff of the first two - just the interesting part][YouCompleteMe in opt loaded from vimrc](https://bpaste.net/show/7479819b0430)

**Comment by ZyX-I** [comment]
@bstaletic Last two links are broken.

**Comment by bstaletic** [comment]
Sorry about that. It's fixed now.

**Comment by ZyX-I** [comment]
@bstaletic As I said, you see VimEnter here. YCM may be written to run its VimEnter if `!has('vim_starting')`, or `:packadd` needs to be modified to run new missed autocommands (not only VimEnter).

**Comment by ZyX-I** [comment]
@bstaletic As a temporary solution just `:call youcompleteme#Enable()` after `packadd`.

**Comment by bstaletic** [comment]
@ZyX-I  Alright, thanks. Calling youcompleteme#Enable() after packadd doesn't seem too bad.

**Comment by k-takata** [comment]
The following message is not forwarded to github:
https://groups.google.com/d/msg/vim_dev/GGtxV9Dxuww/6EwyJGycCAAJ

> On 2016-07-03 20:38:02 +0000, Nicola said:
> 
> > On 2016-07-03 20:24:27 +0000, bstaletic (Vim Github Repository) said:
> > 
> > > If YouCompleteMe is placed in $HOME/.vim/pack/ycm/start/YouCompleteMe 
> > > it works perfectly, but if it is place in opt in stead of start it 
> > > doesn't even load.
> > 
> > As the manual says, packadd just sources the plugin file. YCM does some 
> > initialization on VimEnter, and that needs to be performed manually:
> > 
> > packadd youcompleteme
> > call youcompleteme#Enable()
> 
> Btw, there's an open pull request addressing that:
> https://github.com/Valloric/YouCompleteMe/pull/2084.
> 
> Nicola

Maybe he doesn't have a github account?

**Comment by ZyX-I** [comment]
@k-takata Third-party script cannot pretend to be different persons without having their password or access token (especially given that these messages are not even signed; not that it would make a difference if they were with current github API, but that at least makes possible to modify API to do such action securely), so forwarded messages are posted from @vim-ml account, not from users account: e.g. see https://github.com/vim/vim/issues/899#issuecomment-230173708. Thus if there was no such message then there is some problem with the script or its mail delivery service, not with somebody not having github account.

**Comment by brammool** [comment]
bstaletic wrote:

> My patch level is 1821. The 'runtimepath' lists YouCompleteMe's path after running packadd
> I was trying to type `:packadd YouCompleteMe` If I use something like `au Filetype c packadd YouCompleteMe` in my vimrc it loads and works correctly.
> 
> Here are the log files with 'verbose' set to 9:
> [YouCompleteMe in start](https://bpaste.net/show/8614036f5577)
> [YouCompleteMe in opt loaded manually](https://bpaste.net/show/9cab31c8b61e)
> [YouCompleteMe in opt loaded from vimrc](https://bpaste.net/show/a40fc4fc4d8d)
> [This is the diff of the first two - just the interesting part][YouCompleteMe in opt loaded from vimrc](https://bpaste.net/show/74719819b0430)

That's a bit much to dig thorugh.

Nikolai's hint might be right: if YouCompleteMe is not written be be
loaded later, then using :packadd after startup is done might not work.

When you say it works with the Filetype autocommand, is that when you
start Vim editing a C file, or when you edit a C file later?

## 

Some of the well known MS-Windows errors:
    EMULTI      Multitasking attempted, system confused
    EKEYBOARD   Keyboard locked, try getting out of this one!
    EXPLAIN     Unexplained error, please tell us what happened
    EFUTURE     Reserved for our future mistakes

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bstaletic** [comment]
@brammool 
It works with autocmd if that autocmd is to be run on start up, else it doesn't do anything. On the other hand calling `youcompleteme#Enable()` after `packadd` works always.

**Comment by chrisbra** [comment]
I suppose, this can be closed then?

**Comment by bstaletic** [comment]
That's fine by me.

**Comment by puremourning** [comment]
I will take a look at the YCM PR
