### ISSUE TITLE
Vim patterns on vim.org

### ISSUE THREAD

**Issue by fkromer** [vim/vim#902]
While discovering Vim I recognized that there do exist patterns and also anti-patterns related to using Vim. There are a lot of video tutorials and other resources where this patterns (and anti-patterns) do repeat over and over again. But I did not find any centralized pattern reference for Vim. I summarized some patterns already and would be interested in sharing them. Would you be interested in hosting Vim patterns on vim.org?
BTW: I send you this request per email to vim-dev@vim.org but I received an response that the group does not exist.

**Comment by ZyX-I** [comment]
@fkromer vim-dev mailing list is hosted on google groups. I do not know where you got `@vim.org`, but this site is hosted by sourceforge which also provides mailing list services so you got some reply.

**Comment by vim-ml** [comment]
Hi Nikolai!

On So, 03 Jul 2016, Nikolai Aleksandrovich Pavlov wrote:

> @fkromer vim-dev mailing list is hosted on google groups. I do not
> know where you got `@vim.org`, but this site is AFAIR hosted by
> sourceforge which also provides mailing list services so you got some
> reply.

http://www.vim.org/maillist.php
Those mails are alias for the googlegroups.com mails and independent of 
the sourceforge.net mailing list that is also available IIRC. The alias 
is also the reason, why sometimes we see double mails on the list.

Best,

## Christian

Es ist das Priveleg der Intellektuellen, sich zwischen alle Stühle zu
setzen.
        -- Max Bense

**Comment by fkromer** [comment]
@ZyX-I I took a look onto the [Vim project root page on github](https://github.com/vim) where I found vim-dev@vim.org

vim@vim.org ("This list is for Vim user support. You can send general questions to this list to be answered by other Vim users.") should be the right choice for an issue like mine I guess...

**Comment by chrisbra** [comment]
You might want to ask Bram directly. In the meantime, I think the best place to share those patterns and antipatterns would be the [wiki](http://vim.wikia.com/wiki/Vim_Tips_Wiki)

**Comment by fkromer** [comment]
Does the wiki provide some functionality to relate patterns to each other graphically? I do prefer [graphical representations to relate patterns to each other like here](http://eswp3.readthedocs.io/en/latest/design_languages/python_exception_handling.html) (or like in the GOF book) over "textual hyperlinking" (usually the only possibility in wikis) due to several reasons (better to memorize -> relations betweens patterns and the patterns itself, little maintainance cost -> graphs can be generated from "tagged" text with scripts automatically).

**Comment by k-takata** [comment]
(sorry, off topic)
In the page http://www.vim.org/maillist.php, it says:

> - The maillists are hosted by Google Groups. The @vim.org addresses are aliases. For some things you need to use the original @googlegroups.com address

but the @googlegroups.com addresses are not listed in the page. I think it's better to list the googlegroups addresses too. (E.g. vim_dev@googlegroups.com)
Additionally, the page doesn't mention that the mailing lists are moderated for the first post. It would be better to mention it. We often see some people post the same mail several times.

**Comment by chrisbra** [comment]
@fkromer I don't know. You can certainly add pictures however.

**Comment by fkromer** [comment]
@chrisbra I will try it in the wiki...

**Comment by chrisbra** [comment]
I think the wiki should be used for that. Closing.
