### ISSUE TITLE
BufWinEnter * is triggered twice when opening the quickfix window or a location list window

### ISSUE THREAD

**Issue by yorickpeterse** [vim/vim#9022]
### Steps to reproduce

1. Start Vim
2. Run `:au BufWinEnter * echo 'test'`
3. Run `:cope`

After this, the message `'test'` is outputted twice, instead of once. Note that this _only_ happens when the file type pattern is a wildcard. If you use `au BufWinEnter quickfix echo 'test'`, the message is only displayed once.

### Expected behaviour

The message `'test'` is only displayed once, because I as the user only enter the quickfix window once. This can also mess with plugins that act upon `BufWinEnter *` but don't expect it to be called twice.

### Operating system

Arch Linux

### Version of Vim

8.2.3

**Comment by YorickPeterse** [comment]
The only way I can think of to work around is to use a counter, start it at 0, increment for every invocation, and only act when the counter is set to `1`. This of course is a total hack.
