### ISSUE TITLE
Why is the API for async jobs incompatible to neovim?

### ISSUE THREAD

**Issue by tomtom** [vim/vim#904]
Serious question: Why are the functions used to run async jobs incompatible from neovim? Are there technical reasons for that or is just some kind of NIH syndrome?
- https://neovim.io/doc/user/job_control.html
- https://neovim.io/doc/user/eval.html#jobstart()
- https://vimhelp.appspot.com/channel.txt.html
- https://vimhelp.appspot.com/eval.txt.html#job_start()

Is there some kind of compatibility layer available or planned, given that neovim had this feature first? (Maybe I simply missed it which would be great.)

Do you actually think, fragmentation and incompatible APIs are a good thing?

**Comment by chrisbra** [comment]
that is no issue. Please discuss user questions on the mailing list.
