### ISSUE TITLE
Unknown option argument: "--multiprocessing-fork"

### ISSUE THREAD

**Issue by Yggdroot** [vim/vim#906]
On Windows vim version 7.4.1923. 

To reproduce: 
:py from multiprocessing import Pool 
:py p = Pool(4)

It seems vim does not support multiprocess of python, how can it be fixed?

**Comment by vim-ml** [comment]
Am 2016-07-05 15:49, schrieb Yggdroot:

> On Windows vim version 7.4.1923.
> 
> To reproduce:
> :py from multiprocessing import Pool
> :py p = Pool(4)
> 
> It seems vim does not support multiprocess of python, how can it be
> fixed?

This is a problem of the multiprocess package of Python,
as it seems to assume to always be running in python and
not in some embedded application.

No problem Vim can fix.

Best,
Christian

**Comment by chrisbra** [comment]
closing as invalid.

**Comment by Yggdroot** [comment]
Is there any way to work around it?

**Comment by k-takata** [comment]
How about using `multiprocessing.set_executable()`?
https://docs.python.org/2/library/multiprocessing.html#multiprocessing.set_executable

**Comment by char101** [comment]
You need the python executable, then set `sys.executable`/use `multiprocessing.set_executable()` as suggested by k-takata above to it before creating the pool.

``` viml
py import sys; sys.executable = 'path to python/python.exe'
py from multiprocessing import Pool
py p = Pool(4)
```
