### ISSUE TITLE
[Windows] Cannot use :let in Vim9 script when vimrc is in vim9 and encoding is set and filename is given on the command line

### ISSUE THREAD

**Issue by char101** [vim/vim#9068]
### Steps to reproduce

1. write _vimrc in vim9
2. add `set encoding='utf-8` in _vimrc
2. run gvim test.txt

Vim works when started first without file name, but failed to start if file name is given on the command line. Verbose log shows that vim is trying to run `let SaVe_WIG`. Grepping the source code results in the statement located in [os_win32.c](https://github.com/vim/vim/blob/master/src/os_win32.c#L7771). Also I have encoding=utf-8 in vimrc (although apparently that is the default value).

### Expected behaviour

GVim is running.

### Operating system

Windows 10

### Version of Vim

8.2.3567

### Logs and stack traces

```shell
line   24:
E1126: Cannot use :let in Vim9 script
line 24: :let SaVe_WIG = &wig|set wig=
E1126: Cannot use :let in Vim9 script
line 24: :let &isf = SaVe_ISF|unlet SaVe_ISF
E1126: Cannot use :let in Vim9 script
line 24: :let &wig = SaVe_WIG|unlet SaVe_WIG
E1126: Cannot use :let in Vim9 script
```

**Comment by bfrg** [comment]
`let` is not supported in `vim9script`, you need to replace it with `var`. See `:help vim9-differences`.

**Comment by char101** [comment]
The let statement is located in vim source code, not my vimrc.

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> 1. write _vimrc in vim9
> 2. run gvim test.txt
> 
> Vim works when started first without file name, but failed to start if file name is given on the command line. Verbose log shows that vim is trying to run `let SaVe_WIG`. Grepping the source code results in the statement located in [os_win32.c](https://github.com/vim/vim/blob/master/src/os_win32.c#L7771). Also I have encoding=utf-8 in vimrc (although apparently that is the default value).
> 
> ### Expected behaviour
> 
> GVim is running.
> 
> ### Operating system
> 
> Windows 10
> 
> ### Version of Vim
> 
> 8.2.3567
> 
> ### Logs and stack traces
> 
> ```shell
> line   24:
> E1126: Cannot use :let in Vim9 script
> line 24: :let SaVe_WIG = &wig|set wig=
> E1126: Cannot use :let in Vim9 script
> line 24: :let &isf = SaVe_ISF|unlet SaVe_ISF
> E1126: Cannot use :let in Vim9 script
> line 24: :let &wig = SaVe_WIG|unlet SaVe_WIG
> E1126: Cannot use :let in Vim9 script
> ```

Can you compile Vim from source?  Then please try changing the lines you
referred to:

    if (!used_file_literal)
    {
	static char *legacy_cmds[4] = {
	    "let SaVe_ISF = &isf|set isf+=(,)"),
	    "let SaVe_WIG = &wig|set wig="),
	    "let &isf = SaVe_ISF|unlet SaVe_ISF"),
	    "let &wig = SaVe_WIG|unlet SaVe_WIG"),
	};
	static char *vim_cmds[4] = {
	    "g:SaVe_ISF = &isf|set isf+=(,)"),
	    "g:SaVe_WIG = &wig|set wig="),
	    "&isf = g:SaVe_ISF|unlet g:SaVe_ISF"),
	    "&wig = g:SaVe_WIG|unlet g:SaVe_WIG"),
	};
	char **cmds = in_vim9script() ? vim_cmds : legacy_cmds;

	// Now expand wildcards in the arguments.
	// Temporarily add '(' and ')' to 'isfname'.  These are valid
	// filename characters but are excluded from 'isfname' to make
	// "gf" work on a file name in parenthesis (e.g.: see vim.h).
	// Also, unset wildignore to not be influenced by this option.
	// The arguments specified in command-line should be kept even if
	// encoding options were changed.
	do_cmdline_cmd((char_u *)cmds[0]);
	do_cmdline_cmd((char_u *)cmds[1]);
	alist_expand(fnum_list, used_alist_count);
	do_cmdline_cmd((char_u *)cmds[2]);
	do_cmdline_cmd((char_u *)cmds[3]);
    }

I can't build on MS-Windows right now, it might not work.  Perhaps
someone can turn this into a PR.  Bonus points for adding a test.


-- 
There is a fine line between courage and foolishness.
Unfortunately, it's not a fence.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by char101** [comment]
Fortunately I usually compiled vim from source. I have added those lines and can confirm that it fixes the problem (notice: there are extra closing parantheses in the assignments).

Thank you.

**Comment by chrisbra** [comment]
Can't we use the `:legacy` modifier here?

**Comment by brammool** [comment]
Christian wrote:

> Can't we use the `:legacy` modifier here?

That should work and it's simpler.  Can you give it a try?

-- 
"Time flies like an arrow".  So I put an arrow on my desk, now
awaiting one of these time flies showing up.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
