### ISSUE TITLE
Add Scala Syntax Highlighting

### ISSUE THREAD

**Issue by Petesta** [vim/vim#907]
Currently there is no default syntax highlighting for Scala but other JVM languages such as Clojure and Java already have their files available.

There is already one maintained by [Derek Wyatt](https://github.com/derekwyatt) called [vim-scala](https://github.com/derekwyatt/vim-scala). The licensing on the project is through Apache. What are the next steps needed to get something like this merged in?

**Comment by vim-ml** [comment]
Am 2016-07-06 00:45, schrieb Pete Cruz:

> Currently there is no default syntax highlighting for Scala but other
> JVM languages such as Clojure and Java already have their files
> available.
> 
> There is already one maintained by Derek Wyatt [1] called vim-scala
> [2]. The licensing on the project is through Apache. What are the next
> steps needed to get something like this merged in?

I think best would be to create an issue at that repository and ask the
author to include the runtime files with Vim. He would then need to send 
all
files to Bram for inclusion and possibly needs to dual-license his files
under the Vim License. But I am not sure about the licensing stuff. 
Might
be, that the Apache is enough to distribute it together with Vim.

In any case, getting an explicit permission to distribute his files with
Vim would be nice.

However there are some folders, for which I don't know if they would fit 
with
Vim. Perhaps only including the syntax script would be good enough and 
leave
the rest as plugin?

**Comment by Petesta** [comment]
I'll get in touch with him and see what needs to be done about dual license.

I see, yea, the syntax script would be good enough for a runtime file and the rest could be left as the [vim-scala](https://github.com/derekwyatt/vim-scala) plugin.

Will follow up after receiving a response.

**Comment by Petesta** [comment]
We got in contact with one another and Derek said that having the syntax script integrated works for him and that he's willing to change the license to whatever is necessary to make things easier.

What would be the next steps apart from getting the syntax script to Bram and updating the current `vim-scala` license?

Here is the opened [issue](https://github.com/derekwyatt/vim-scala/issues/133).

**Comment by chrisbra** [comment]
From my opinion, whenever the upstream author is ready to have some parts include it, upstream should send them to Bram mention tits full name and explicit permission to distribute it with Vim, refer to this issue and then we should be okay. I think Bram does some basic checks for runtime file updates, so you might expect some feedback before including it. But that should be basically it.

**Comment by Petesta** [comment]
https://github.com/vim/vim/pull/995
