### ISSUE TITLE
Test_very_large_count fails on 32bit systems

### ISSUE THREAD

**Issue by mimi1vx** [vim/vim#9072]
### Steps to reproduce

run vim testsuite on i586

### Expected behaviour

test pass

### Operating system

openSUSE, Tumbleweed, 

### Version of Vim

8.2.3567

### Logs and stack traces

```shell
1095s] Found errors in Test_very_large_count():
[ 1095s] command line..script /home/abuild/rpmbuild/BUILD/vim-8.2.3567/src/testdir/runtest.vim[450]..function RunTheTest[44]..Test_very_large_count line 6: command did not fail: norm 44444444444444p
```

**Comment by tonymec** [comment]
I thought current openSUSE operating systems were published for 64-bit processors only? Or are you compiling and running 32-bit Vim on a 64-bit OS? (It _is_ possible on openSUSE, but only if the appropriate -32bit packages are installed.)

**Comment by jamessan** [comment]
This is also an issue on Debian.  There are multiple 32-bit architectures where Linux is still used.

**Comment by brammool** [comment]
Please check that the issue is actually fixed.  Perhaps we should also add v:intsize so we can fix the FIXME.  Although the most interesting is that sizeof(long) != sizeof(char *).  What would we call that, v:longnopointer?

**Comment by jamessan** [comment]
This doesn't fix the test.  On i386 Linux builds, `v:numbersize` is still 64 because `varnumber_T` is `int64_t`.  Also, `sizeof(long)` is always the same as the size of a pointer type on Linux.  As mentioned in the test comment, the fix the test is trying to check doesn't work when `sizeof(int) == sizeof(long)`, which is the case on 32-bit Linux.

**Comment by mimi1vx** [comment]
@tonymec openSUSE:Tumbleweed still ships i586 flavor

@brammool  same error as before

**Comment by mimi1vx** [comment]
ahh , and also looks like this test is problematic on BigEndian systems like s390x

**Comment by brammool** [comment]
I thought using a float would work, but the test still fails on MS-Windows.  Not sure why, the float multiplication cannot overflow and comparing with the int value should be false.

One alternative is to use an unsigned long.  Not sure if we always catch the overflow then.
Any other ideas?
