### ISSUE TITLE
Test `Test_colornames_overwrite_default` fails

### ISSUE THREAD

**Issue by dpelle** [vim/vim#9073]
### Steps to reproduce

Test `Test_colornames_overwrite_default` fails when vim is configured as follows:
```
$ cd vim
$ ./configure --with-features=normal --enable-gui=none --enable-cscope=yes
$ make -j8
$ make test_highlight
…
Executed 34 tests                        in   0.079528 seconds
1 FAILED:
Found errors in Test_colornames_overwrite_default():
Caught exception in Test_colornames_overwrite_default(): Vim(let):E716: Key not present in Dictionary: "rebecca purple" @ command line..script /home/pel/sb/vim/src/testdir/runtest.vim[450]..function RunTheTest[44]..Test_colornames_overwrite_default, line 4
...
```

### Expected behaviour

All tests should pass.

### Operating system

xubuntu-18.04.6

### Version of Vim

vim-8.2.3567

**Comment by dpelle** [comment]
CC @dvogel who added the test in:
```
commit e30d10253fa634c4f60daa798d029245f4eed393 (tag: v8.2.3562)
Author: Drew Vogel <dvogel@github>
Date:   Sun Oct 24 20:35:07 2021 +0100

    patch 8.2.3562: cannot add color names
    
    Problem:    Cannot add color names.
    Solution:   Add the v:colornames dictionary. (Drew Vogel, closes #8761)
```

**Comment by dvogel** [comment]
Thanks for tagging me. I'm away from a computer for most of this week but I'll take a look at this as soon as I'm back. My first impression is that I should have added a feature/option check to the test because `--enable-gui=none` is a use of the configure script I hadn't considered.

**Comment by chrisbra** [comment]
I think the test should either test, that either a gui or `termguicolors` is available in Vim, or `load_default_color_lists()` should be moved out of the `#if defined(FEAT_GUI) || defined(FEAT_TERMGUICOLORS) || defined(PROTO)` in line 2194 of highlight.c. 

It might make sense to have the color definitions available, even if the current vim is compiled without Gui/termgui feature set.
