### ISSUE TITLE
vim syntax after 'startinsert' looks incorrect.

### ISSUE THREAD

**Issue by Shane-XB-Qian** [vim/vim#9075]
### Steps to reproduce

![image](https://user-images.githubusercontent.com/13550529/139625715-88da69cc-eb38-461a-bb2e-ed709a3baaa4.png)

### Expected behaviour

highlight correctly.

### Operating system

linux

### Version of Vim

vim 8.2.3568

**Comment by Shane-XB-Qian** [comment]
the problem looks was here:
```vim
syn region vimInsert	matchgroup=vimCommand start="^[: \t]*\(\d\+\(,\d\+\)\=\)\=a\%[ppend]$"		matchgroup=vimCommand end="^\.$""
syn region vimInsert	matchgroup=vimCommand start="^[: \t]*\(\d\+\(,\d\+\)\=\)\=c\%[hange]$"		matchgroup=vimCommand end="^\.$""
syn region vimInsert	matchgroup=vimCommand start="^[: \t]*\(\d\+\(,\d\+\)\=\)\=i\%[nsert]$"		matchgroup=vimCommand end="^\.$""
syn region vimInsert	matchgroup=vimCommand start="^[: \t]*\(\d\+\(,\d\+\)\=\)\=starti\%[nsert]$"	matchgroup=vimCommand end="^\.$""
```
// syntax/vim.vim
@cecamp

**Comment by lacygoill** [comment]
Even though `:startinsert` contains the keyword `insert`, it does not serve the same purpose as `:insert`.  In particular, it does not read the following text (until a dot alone on a line) as a string to insert into the buffer;  it just switches the current mode to insert mode.  I think the last rule can be dropped:
```diff
diff --git a/runtime/syntax/vim.vim b/runtime/syntax/vim.vim
index 1fd94752b..8f4df6ad4 100644
--- a/runtime/syntax/vim.vim
+++ b/runtime/syntax/vim.vim
@@ -192,7 +192,6 @@ syn keyword vimCommand  contained	in
 syn region vimInsert	matchgroup=vimCommand start="^[: \t]*\(\d\+\(,\d\+\)\=\)\=a\%[ppend]$"		matchgroup=vimCommand end="^\.$""
 syn region vimInsert	matchgroup=vimCommand start="^[: \t]*\(\d\+\(,\d\+\)\=\)\=c\%[hange]$"		matchgroup=vimCommand end="^\.$""
 syn region vimInsert	matchgroup=vimCommand start="^[: \t]*\(\d\+\(,\d\+\)\=\)\=i\%[nsert]$"		matchgroup=vimCommand end="^\.$""
-syn region vimInsert	matchgroup=vimCommand start="^[: \t]*\(\d\+\(,\d\+\)\=\)\=starti\%[nsert]$"	matchgroup=vimCommand end="^\.$""
 
 " Behave! {{{2
 " =======
```

**Comment by Shane-XB-Qian** [comment]
it is not a specific issue to 'starti[nsert]' only, but append/change/insert too.

**Comment by lacygoill** [comment]
> it is not a specific issue to 'starti[nsert]' only, but append/change/insert too.

No, the issue is specific to `:startinsert`.  For `:append`, `:change`, `:insert`, the highlighting is correct.

**Comment by Shane-XB-Qian** [comment]
![image](https://user-images.githubusercontent.com/13550529/139630698-d6a4130a-2fb3-429d-b477-071e99d28519.png)

**Comment by lacygoill** [comment]
There is nothing wrong in this screenshot.  `echo 'bar'` is highlighted as a string, because it's treated as data/text (!= code), whose purpose is to be written in the buffer.  It ends with a dot alone on a line; like this:
```vim
echo 'this is a string before :append'
append
this is a literal text
which is appended by :append
in the buffer
.
echo 'this is a string after :append'
```
Again, the highlighting (`vimInsert`) is correct.  See [`:help :append`](https://vimhelp.org/insert.txt.html#%3Aappend) for more info.

**Comment by Shane-XB-Qian** [comment]
yes, sort of correct..
just 'startinsert' is a more clear issue (than others 3), since not req had a 'dot' at end.

but incorrect if those in cmd window (e.g cmd hist).

**Comment by lacygoill** [comment]
> but incorrect if those in cmd window (e.g cmd hist).

No, the highlighting after `:append` is still correct, even in the command-line window.

FWIW, I don't like `:append`, `:insert`, and `:change`, because a small typo can mess up the highlighting of all the subsequent text, but it's technically correct.

Vim9 script does not support these commands, so [no issues there](https://github.com/lacygoill/vim9-syntax); one more reason to prefer Vim9 over legacy.

**Comment by Shane-XB-Qian** [comment]
![image](https://user-images.githubusercontent.com/13550529/139636782-364c3b80-f919-4f0d-a8ed-a5312aa3a5fc.png)

ok, but IMO looks append/insert/change in cmd window looks meaningless..
or anyway, i actually did not use those 3, but 'startinsert' without 'dot' was a common usage in script, wish to be correct soon.

**Comment by lacygoill** [comment]
> ok, but IMO looks append/insert/change in cmd window looks meaningless..

Yes, maybe.  My commands in the command-line window are often completely wrongly highlighted because of `:append`, `:insert`, or `:change`; especially since they can abbreviated into `:a`, `:i`, `:c` which can be typed by mistake.  And then, there is no easy way to fix the issue; you can remove the offending command, but then, as soon as you quit the command-line window and re-open it, the issue appears again.  I guess you have to quit Vim and edit the `.viminfo` file.

As a workaround, maybe you could clear the syntax with an autocmd:

    autocmd CmdwinEnter * syntax clear vimInsert

   > but 'startinsert' without 'dot' was a common usage in script, wish to be correct soon.

Yes, the text after `:startinsert` is definitely wrongly highlighted right now.

**Comment by lacygoill** [comment]
> but incorrect if those in cmd window (e.g cmd hist).

   > ok, but IMO looks append/insert/change in cmd window looks meaningless..

Actually, you might be right.  If I execute an `:insert` command interactively, the string data is not logged in the history.  As a suggestion here is a new patch, which does 2 things:

   - remove the wrong rule about `:startinsert`
   - check we are in a regular file (and not in the command-line window) before installing the rules about `:insert`, `:append`, `:change`

```diff
diff --git a/runtime/syntax/vim.vim b/runtime/syntax/vim.vim
index 1fd94752b..7a94a47e6 100644
--- a/runtime/syntax/vim.vim
+++ b/runtime/syntax/vim.vim
@@ -189,10 +189,12 @@ syn keyword vimCommand  contained	in
 
 " Insertions And Appends: insert append {{{2
 " =======================
-syn region vimInsert	matchgroup=vimCommand start="^[: \t]*\(\d\+\(,\d\+\)\=\)\=a\%[ppend]$"		matchgroup=vimCommand end="^\.$""
-syn region vimInsert	matchgroup=vimCommand start="^[: \t]*\(\d\+\(,\d\+\)\=\)\=c\%[hange]$"		matchgroup=vimCommand end="^\.$""
-syn region vimInsert	matchgroup=vimCommand start="^[: \t]*\(\d\+\(,\d\+\)\=\)\=i\%[nsert]$"		matchgroup=vimCommand end="^\.$""
-syn region vimInsert	matchgroup=vimCommand start="^[: \t]*\(\d\+\(,\d\+\)\=\)\=starti\%[nsert]$"	matchgroup=vimCommand end="^\.$""
+" only in regular file; not in the command-line window
+if &buftype != 'nofile'
+  syn region vimInsert	matchgroup=vimCommand start="^[: \t]*\(\d\+\(,\d\+\)\=\)\=a\%[ppend]$"		matchgroup=vimCommand end="^\.$""
+  syn region vimInsert	matchgroup=vimCommand start="^[: \t]*\(\d\+\(,\d\+\)\=\)\=c\%[hange]$"		matchgroup=vimCommand end="^\.$""
+  syn region vimInsert	matchgroup=vimCommand start="^[: \t]*\(\d\+\(,\d\+\)\=\)\=i\%[nsert]$"		matchgroup=vimCommand end="^\.$""
+endif
 
 " Behave! {{{2
 " =======
```

**Comment by lacygoill** [comment]
Comparing `'buftype'` to an empty string should be easier to understand and give the same result:
```diff
diff --git a/runtime/syntax/vim.vim b/runtime/syntax/vim.vim
index 1fd94752b..7a94a47e6 100644
--- a/runtime/syntax/vim.vim
+++ b/runtime/syntax/vim.vim
@@ -189,10 +189,12 @@ syn keyword vimCommand  contained	in
 
 " Insertions And Appends: insert append {{{2
 " =======================
-syn region vimInsert	matchgroup=vimCommand start="^[: \t]*\(\d\+\(,\d\+\)\=\)\=a\%[ppend]$"		matchgroup=vimCommand end="^\.$""
-syn region vimInsert	matchgroup=vimCommand start="^[: \t]*\(\d\+\(,\d\+\)\=\)\=c\%[hange]$"		matchgroup=vimCommand end="^\.$""
-syn region vimInsert	matchgroup=vimCommand start="^[: \t]*\(\d\+\(,\d\+\)\=\)\=i\%[nsert]$"		matchgroup=vimCommand end="^\.$""
-syn region vimInsert	matchgroup=vimCommand start="^[: \t]*\(\d\+\(,\d\+\)\=\)\=starti\%[nsert]$"	matchgroup=vimCommand end="^\.$""
+" only in a regular file; not in the command-line window
+if &buftype == ''
+  syn region vimInsert	matchgroup=vimCommand start="^[: \t]*\(\d\+\(,\d\+\)\=\)\=a\%[ppend]$"		matchgroup=vimCommand end="^\.$""
+  syn region vimInsert	matchgroup=vimCommand start="^[: \t]*\(\d\+\(,\d\+\)\=\)\=c\%[hange]$"		matchgroup=vimCommand end="^\.$""
+  syn region vimInsert	matchgroup=vimCommand start="^[: \t]*\(\d\+\(,\d\+\)\=\)\=i\%[nsert]$"		matchgroup=vimCommand end="^\.$""
+endif
 
 " Behave! {{{2
 " =======
```

**Comment by Shane-XB-Qian** [comment]
'startinsert' had been fixed in last patch yesterday. so closing this.
~~// though others 3 still a bit flaw there.~~
