### ISSUE TITLE
Impossible to uninstall

### ISSUE THREAD

**Issue by alessandroDeIturbe** [vim/vim#9082]
### Steps to reproduce

make VIMRUNTIMEDIR=/usr/share/vim/vim73
sudo make uninstall

### Expected behaviour

In every wiki I found says it will be deleted

### Operating system

MacOS Monterey

### Version of Vim

8.2

### Logs and stack traces

```shell
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `uninstall'.  Stop.
```

**Comment by lacygoill** [comment]
What's the output of the shell command `pwd` when you run `sudo make uninstall`?
Same question with the shell command  `ls | grep -i makefile`.

**Comment by alessandroDeIturbe** [comment]
alessandrodeiturbe@MacBook-Air-di-Alessandro vim % pwd
/usr/share/vim
alessandrodeiturbe@MacBook-Air-di-Alessandro vim % make VIMRUNTIMEDIR=/usr/share/vim/vim73
make: *** No targets specified and no makefile found.  Stop.
alessandrodeiturbe@MacBook-Air-di-Alessandro vim % sudo make uninstall
Password:
make: *** No rule to make target `uninstall'.  Stop.
alessandrodeiturbe@MacBook-Air-di-Alessandro vim % ls | grep -i makefile
alessandrodeiturbe@MacBook-Air-di-Alessandro vim %

**Comment by lacygoill** [comment]
> alessandrodeiturbe@MacBook-Air-di-Alessandro vim % pwd
   > /usr/share/vim

So you are in `/usr/share/vim`.  That's probably where the system's Vim gets installed, but not where you cloned the project.  How did you get Vim?  Where did you clone the repo?  You need to run the `make` commands in the root directory where your personal copy of the Vim project is located.

For example:

    $ mkdir ~/test
    $ cd ~/test
    $ git clone https://github.com/vim/vim
    $ cd ~/test/vim
    $ ./configure
    $ make
    $ sudo make install
    $ sudo make uninstall

   > alessandrodeiturbe@MacBook-Air-di-Alessandro vim % ls | grep -i makefile
   > alessandrodeiturbe@MacBook-Air-di-Alessandro vim %

Yes, there is no `Makefile` under `/usr/share/vim`.  If you want to uninstall the Vim binary installed by your system, you need to use your OS package manager.

**Comment by alessandroDeIturbe** [comment]
I haven't installed vim via package manager, but I've compiled it from the code downloaded on the Vim's Github page, but I've deleted the folder

**Comment by lacygoill** [comment]
> I've deleted the folder

Try to re-create it by cloning the repo again.

**Comment by lacygoill** [comment]
Then run `make uninstall` from this folder.  Only then can you delete it.

**Comment by alessandroDeIturbe** [comment]
I did everything, but If I type `vim` in the terminal still starts vim

**Comment by lacygoill** [comment]
> If I type vim in the terminal still starts vim

This Vim was probably installed by your OS.  You need to learn how to uninstall packages managed by your OS (`brew uninstall vim`?).

In any case, that's not a Vim bug.  I suggest you ask further questions on [apple.stackexchange.com](https://apple.stackexchange.com/questions/252433/how-to-upgrade-system-default-vim).
