### ISSUE TITLE
Some ex commands with [range] move point while they shouldn't

### ISSUE THREAD

**Issue by the42** [vim/vim#9088]
### Steps to reproduce

open any text file or type some random lines into a buffer
Move to the last line (any line but the first)
run `:1p`

The first line is printed in the command area and point moves to first line in buffer.

I would expect this behavior if no command is given, so only `:1` is executed, but not with ex commands `p`, `l`,  others? Much in the sense as `:1=` doesn't move point either.

### Expected behaviour

The first line in the buffer is printed in the command area, point remains at current location

### Operating system

any

### Version of Vim

8.2

**Comment by chrisbra** [comment]
I believe this is required by POSIX: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/ex.html#tag_20_40_13_31 and is how vi in general behaves.

**Comment by the42** [comment]
Thank you for pointing to the spec, though I do not read therein, that
point shall or must be moved.

The behavior of moving point in ex mode when a range is given is
inconsistent at best and especially for `p`, `l` (others) it doesn't make
sense to me, although my use case for using these commands today might be
different to the intention back in the days they were conceived.

Imagine I am deep down at line 68954 in a csv file and I forgot the column
order. A quick `:1p` would remind me about this. If point is moved, this
becomes somewhat tedious to use.

Am Do., 4. Nov. 2021 um 09:41 Uhr schrieb Christian Brabandt <
***@***.***>:

**Comment by brammool** [comment]
As Christian mentioned, this has historic reasons.  Changing it might cause others to complain.
You will be able to find a workaround.  You can add a user command using "echo getline(1)" perhaps.
