### ISSUE TITLE
Could not :filter mappings by {lhs}

### ISSUE THREAD

**Issue by VKondakoff** [vim/vim#9091]
### Steps to reproduce

1. Run (check if mapping exists):
```shell
vim -u NONE -N --cmd "nmap"
n  <D-v>         "*P
```
<img width="544" alt="Снимок экрана 2021-11-05 в 14 08 03" src="https://user-images.githubusercontent.com/230824/140501908-90d2e4fc-fe24-4a67-a886-1d0aa2de92d4.png">

2. Run (:filter by {rhs}):
```shell
vim -u NONE -N --cmd "filter /\"\*P/ nmap"
n  <D-v>         "*P
```
<img width="672" alt="Снимок экрана 2021-11-05 в 14 11 34" src="https://user-images.githubusercontent.com/230824/140501990-4fdd38f5-8bec-4302-845c-1993d2285842.png">

3. Run (:filter by {lhs}) - there is no output:
```shell
vim -u NONE -N --cmd "filter /\<D-v\>/ nmap"
```
<img width="693" alt="Снимок экрана 2021-11-05 в 14 13 36" src="https://user-images.githubusercontent.com/230824/140502225-4d034d57-5122-40ad-a2b4-3d33dde2fdf1.png">

### Expected behaviour

I was expected to be able to :filter nmap by {lhs}. Here is an excerpt from the docs:
> The :filter command can be used to select what mappings to list. The
pattern is matched against the {lhs} and {rhs} in the raw form" (https://vimhelp.org/map.txt.html)

What's wrong here? Or there is a special syntax to enter keys in `raw format`?

### Operating system

macOS Monterey 12.0.1

### Version of Vim

8.2.2671

**Comment by chrisbra** [comment]
Note: it mentions raw form, so you need to pass in the raw-keycode, e.g. using `<C-V>`, `<D-v>` (whatever that key is).

**Comment by VKondakoff** [comment]
Thanks for helping! As far as I understand, the `<D-v>` is a `Control-v`. Do you have an idea how it should be entered in raw form?
There is another example. Here is the output of `nmap`:
```vim
n  gh          *@:call <SNR>64_xkb_switch(1, 1)<CR>gh
n  <C-L>       * <Cmd>nohlsearch|diffupdate<CR><C-L>
n  <Space>wd   * :hide<CR>
n  <Space>w-   * :split<CR>
```
How can I filter all the mappings with `<Space>` in raw form? Entering `:filter / / nmap` (using `<C-v><Space>` as a pattern) shows all of the mappings, as every mapping contains ` ` symbol.
Any ideas?
Thank you!

**Comment by VKondakoff** [comment]
Aha! Thanks for the workaround, `:map <space>` and `:map <D-v>` works great!

BTW, you can make `:filter` work with lhs <space> like this: `:filter /^ / map`. But I'm still unable to enter `<D-v>` in raw form...

**Comment by chrisbra** [comment]
> As far as I understand, the <D-v> is a Control-v. Do you have an idea how it should be entered in raw form?

Yes, press `<C-V><D-v>` to enter the keycode literally.

**Comment by lacygoill** [comment]
> BTW, you can make :filter work with lhs like this: :filter /^ / map.

I stand corrected.  You're right, the `^` anchor works.
