### ISSUE TITLE
Opening help in the current window, through HelpCurwin creates new splits.

### ISSUE THREAD

**Issue by DasOhmoff** [vim/vim#9096]
### Steps to reproduce

I tried to force the help window to only ever open in the current window, without splitting, etc. I looked through the documentation and found the following:
```
Opening help in the current window				*help-curwin*

By default, help is displayed in a split window.  If you prefer it opens in
the current window, try this custom `:HelpCurwin` command:
>
	command -bar -nargs=? -complete=help HelpCurwin execute s:HelpCurwin(<q-args>)
	let s:did_open_help = v:false
	
	function s:HelpCurwin(subject) abort
	  let mods = 'silent noautocmd keepalt'
	  if !s:did_open_help
	    execute mods .. ' help'
	    execute mods .. ' helpclose'
	    let s:did_open_help = v:true
	  endif
	  if !empty(getcompletion(a:subject, 'help'))
	    execute mods .. ' edit ' .. &helpfile
	  endif
	  return 'help ' .. a:subject
	endfunction
```
I tried using this, but it causes issues. When I code, I use a buffer line (like tabline) which shows me the open buffers. I added to shortcut to wipe out all inactive buffers, so the bufferline gets cleared up. The help window does not get opened in the current window, but in a new split, in the following scenario:
1. Use the HelpCurwin command
2. Close the window and wipe out the help buffer
3. Use the HelpCurwin command again
4. Now there are two help windows open with the same content

How can I make this work properly.

### Expected behaviour

The help window should always open in the current window.

### Operating system

Windows 10

### Version of Vim

Neovim v0.5.1

**Comment by chrisbra** [comment]
Is this a neovim issue or a vim issue?

**Comment by chrisbra** [comment]
I think you need to add `:set buftype=help` in the function, so possibly like this:
```
	command! -bar -nargs=? -complete=help HelpCurwin execute s:HelpCurwin(<q-args>)
	let s:did_open_help = v:false
	
	function! s:HelpCurwin(subject) abort
	  let mods = 'silent noautocmd keepalt'
	  if !s:did_open_help
	    execute mods .. ' help'
	    execute mods .. ' helpclose'
	    let s:did_open_help = v:true
	  endif
	  if !getcompletion(a:subject, 'help')->empty()
			let mods = 'silent keepalt'
	    execute ' edit ' .. &helpfile
			set buftype=help
	  endif
	  return 'help ' .. a:subject
	endfunction
```

**Comment by lacygoill** [comment]
> Version of Vim
   >
   > Neovim v0.5.1

If we only had a few dozen open issues, I wouldn't mind trying to fix bugs for Neovim, Emacs, and Nano; but we are well beyond a thousand open issues.  Next time, at least check the issue is reproducible in Vim.

   > How can I make this work properly.

As a suggestion, here is a patch:
```diff
diff --git a/runtime/doc/tips.txt b/runtime/doc/tips.txt
index af78965e9..73fea3fb9 100644
--- a/runtime/doc/tips.txt
+++ b/runtime/doc/tips.txt
@@ -538,14 +538,12 @@ By default, help is displayed in a split window.  If you prefer it opens in
 the current window, try this custom `:HelpCurwin` command:
 >
 	command -bar -nargs=? -complete=help HelpCurwin execute s:HelpCurwin(<q-args>)
-	let s:did_open_help = v:false
 	
 	function s:HelpCurwin(subject) abort
 	  let mods = 'silent noautocmd keepalt'
-	  if !s:did_open_help
+	  if !bufloaded(&helpfile)
 	    execute mods .. ' help'
 	    execute mods .. ' helpclose'
-	    let s:did_open_help = v:true
 	  endif
 	  if !getcompletion(a:subject, 'help')->empty()
 	    execute mods .. ' edit ' .. &helpfile
```
Although, the better fix would be to stop caring about the buffer list.

**Comment by lacygoill** [comment]
> I think you need to add :set buftype=help in the function, so possibly like this:

I think your fix is better.

**Comment by brammool** [comment]
I'll add the suggested "set buftype=help".  Can this issue be closed then?

**Comment by DasOhmoff** [comment]
>  Next time, at least check the issue is reproducible in Vim.

Ah, ok sorry, I will do so next time.
Thank you for the fix, it seems to have solved the issue.

I also wanted to mention the following: If one uses the line 
```
return 'keepjumps help ' .. a:subject
```
instead of the line 
```
return 'help ' .. a:subject
```
at the very end of the function, then the jump list does not get polluted with a jump to the `help.txt` file. Maybe it is a good idea to add this to the doc as well.

**Comment by lacygoill** [comment]
> at the very end of the function, then the jump list does not get polluted with a jump to the help.txt file. Maybe it is a good idea to add this to the doc as well.

Yes, good catch.  So, merging your patch with the previous one, it gives:
```diff
diff --git a/runtime/doc/tips.txt b/runtime/doc/tips.txt
index af78965e9..e61be2b1c 100644
--- a/runtime/doc/tips.txt
+++ b/runtime/doc/tips.txt
@@ -549,8 +549,9 @@ the current window, try this custom `:HelpCurwin` command:
 	  endif
 	  if !getcompletion(a:subject, 'help')->empty()
 	    execute mods .. ' edit ' .. &helpfile
+	    set buftype=help
 	  endif
-	  return 'help ' .. a:subject
+	  return 'keepjumps help ' .. a:subject
 	endfunction
 <
 
```
   > Can this issue be closed then?

I guess it can.  The fixed tip will be available in the next update of the runtime files.

**Comment by DasOhmoff** [comment]
Ok thank you
