### ISSUE TITLE
netrw on .vim/ directory gets vim filetype

### ISSUE THREAD

**Issue by habamax** [vim/vim#9099]
### Steps to reproduce

1. `vim --clean`
2. `:runtime plugin/netrwPlugin.vim`
3. `:Ex ~/.vim`

### Expected behaviour

netrw buffer with `filetype=netrw`

![image](https://user-images.githubusercontent.com/234774/140599838-5daa9190-1b1e-4e56-91f3-d6fc9476606a.png)

### Operating system

WSL debian

### Version of Vim

8.2.3582

**Comment by lacygoill** [comment]
Not sure it's the right way, but this patch should fix the issue:
```diff
diff --git a/runtime/autoload/netrw.vim b/runtime/autoload/netrw.vim
index 7d1a35c1a..3a3d06608 100644
--- a/runtime/autoload/netrw.vim
+++ b/runtime/autoload/netrw.vim
@@ -1789,7 +1789,7 @@ fun! s:NetrwOptionsRestore(vt)
 "  call Dfunc("s:NetrwOptionsRestore(vt<".a:vt.">) win#".winnr()." buf#".bufnr("%")."<".bufname("%")."> winnr($)=".winnr("$"))
 "  call Decho("(s:NetrwOptionsRestore) lines=".&lines)
 "  call Decho("settings buf#".bufnr("%")."<".bufname("%").">: ".((&l:ma == 0)? "no" : "")."ma ".((&l:mod == 0)? "no" : "")."mod ".((&l:bl == 0)? "no" : "")."bl ".((&l:ro == 0)? "no" : "")."ro fo=".&l:fo." a:vt=".a:vt,'~'.expand("<slnum>"))
-  if !exists("{a:vt}netrw_optionsave")
+  if !exists("{a:vt}netrw_optionsave") && &filetype != 'netrw'
 "   call Decho("case ".a:vt."netrw_optionsave : doesn't exist",'~'.expand("<slnum>"))
 "   call Decho("..doing filetype detect anyway")
    filetype detect
```

**Comment by habamax** [comment]
> Not sure it's the right way, but this patch should fix the issue:

Yes, indeed.

**Comment by brammool** [comment]
I'll include #11290 to fix this.

**Comment by cecamp** [comment]
I've had a different solution for this on my [website](http://www.drchip.org/astronaut/vim/index.html#NETRW) since Sep 19, 2022; ie. v172g. Want to try that and tell me if it fixes your issue?
