### ISSUE TITLE
Highlight on empty line not being drawn

### ISSUE THREAD

**Issue by Tarmean** [vim/vim#910]
If `:match Visual /.*/<cr>` is executed on an empty line while the cursor is on that line it is not highlighted. Similarly if you have the cursor on a highlighted empty line and redraw with `:redraw!<cr>` or `<c-l>` that line won't be highlighted.
If you move the cursor and force a redraw the highlight will show up.

[Here is a video of the bug](https://www.youtube.com/watch?v=kXXvyHqhfgs&feature=youtu.be). This is recorded with -N -u NONE on the default Ubuntu version which is 7.4 with patches: 1-1689 .

**Comment by chrisbra** [comment]
seems to be fixed in the meanwhile (tested on Vim 8.1.561)
