### ISSUE TITLE
noremap does not honor  settings 

### ISSUE THREAD

**Issue by benibilme** [vim/vim#9114]
### Steps to reproduce

Hello, 

I have following sample .vimrc. In the end of the vimrc file there are two mappings. Based on these mappings, if I am not mistaken `m` should behave like `k` and when I press `m`, the cursor should move upwards. When I press `m` in normal mode it momentarily does what it is supposed to  but  it stucks at first special character, specifically `"`. The changed behavior of `k` is correct and based on the mapping it behaves like `j`

This behaviour can be tested in the vimrc file itself such as `vim -u vimrc  vimrc`   

````
set nocompatible
filetype on 

" disable toolbar 
" set guioptions -=T

" needed no resize windows in tmux
set mouse=a
if has("mouse_sgr")
    set ttymouse=sgr
else
    set ttymouse=xterm2
end

set autowrite "auto write the contents of the buffer

set encoding=utf-8  " The encoding displayed.
set fileencoding=utf-8  " The encoding written to file.
  
filetype plugin indent on

" let use of global reqisters with any y command
set clipboard=unnamedplus

" COLORS 
syntax enable              " enable syntax processing
set background=dark


" SPACES & TABS 
set tabstop=2       " number of visual spaces per TAB
set shiftwidth=2
set softtabstop=2   " number of spaces in tab when editing
set expandtab       " tabs are spaces 
set smarttab

" UI CONFIG
set number              " show line numbers
set showcmd             " show command in bottom bar
set cursorline          " highlight current line
filetype indent on      " load filetype-specific indent files
set wildmenu            " visual autocomplete
set lazyredraw          " redraw only when we need to
set showmatch           " highlight matching [{()}]
set ruler               " Show ruler
set showtabline=2       " show tabs

" SEARCH 
set incsearch           " search as characters are entered
set hlsearch            " highlight matches
set ignorecase          " Use case insensitive search, except
set smartcase           " when using capital letters

" When opening a new line and no filetype-specific indenting is enabled, keep
" the same indent as the line you're currently on. Useful for READMEs, etc.
set autoindent
set smartindent

" hate folds
" no folding 
" set foldmethod=syntax
set nofoldenable

noremap m k 
noremap k j 
```` 

### Expected behaviour

Based on mappings, m should behave like j in normal mode. 

### Operating system

manjaro 

### Version of Vim

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 15 2021 21:48:21) Included patches: 1-3441

**Comment by lacygoill** [comment]
You have an undesirable trailing whitespace at the end of the rhs of your mapping:

    noremap m k 
               ^
               ✘

Remove it.

For `:noremap`, a space has a meaning.  It's a normal command documented at [`:help <Space>`](https://vimhelp.org/motion.txt.html#l).  It causes the cursor to be moved one character to the right, or to the first character on the next line.  So, if `k` makes the cursor jump on the last character of a line, `<space>` makes it jump on the next line (provided that `s` is in `'whichwrap'`).  Both motions cancel each other out.

---

You have other trailing whitespaces in your vimrc.  I suggest you remove all of them:

    :%s/\s\+$//c

Press `y` or `n` to accept/refuse each change.

---

For more questions, visit the [google mailing list](https://groups.google.com/g/vim_use), the [irc channel](https://www.vi-improved.org/), or [vi.stackexchange.com](https://vi.stackexchange.com/).

**Comment by chrisbra** [comment]
```
noremap m k 
noremap k j 
```

So if you want `m` to behave like `j`, in that case besides the point that @lacygoill mentioned, I think you also want recursive mappings, e.g. use `nmap` instead of `noremap`.

Also, user questions are better asked at other channels as mentioned. This one here is for actual bug reports and we cannot support individual help here, we can barely manage the number of issues here. Thanks for understanding. Closing.

**Comment by benibilme** [comment]
Hello, thank you all for the reponses. I have asked similar questions in stackexchange, overflow even in vim mailing list. I have been using vim since I believe 2004.  So please bear with me. I would not post here the question really, if I would not have thought, it had been a bug. I have never heard anything about the space sensitivity in vimrc file, do not remember anything reading in the documentation even though it has been many years since I fully read the documentation.   However I looked at noremap and langmap from the documentation before asking here. Anyhow thank you again for the support.  

> ```
> noremap m k 
> noremap k j 
> ```
> 
> So if you want `m` to behave like `j`, in that case besides the point that @lacygoill mentioned, I think you also want recursive mappings, e.g. use `nmap` instead of `noremap`.
> 
> Also, user questions are better asked at other channels as mentioned. This one here is for actual bug reports and we cannot support individual help here, we can barely manage the number of issues here. Thanks for understanding. Closing.

**Comment by lacygoill** [comment]
There is this paragraph somewhere under [`:help map-listing`](https://vimhelp.org/map.txt.html#map-listing):

> Everything from the first non-blank after {lhs} up to the end of the line
> (or '|') is considered to be part of {rhs}.  This allows the {rhs} to end
> with a space.

But this issue is a common pitfall.  Maybe we should make the information more visible.  Right under [`:help :map`](https://vimhelp.org/map.txt.html#%3Amap) seems like a good choice (for most users, it should be the first help tag they check).  As a suggestion, here is a patch:
```diff
diff --git a/runtime/doc/map.txt b/runtime/doc/map.txt
index 2c7735571..51d46a122 100644
--- a/runtime/doc/map.txt
+++ b/runtime/doc/map.txt
@@ -61,6 +61,9 @@ modes.
 			where the map command applies.  The result, including
 			{rhs}, is then further scanned for mappings.  This
 			allows for nested and recursive use of mappings.
+			Note: Trailing spaces are included in the {rhs}.  This
+			matters because `<Space>` is a valid command in normal
+			mode.
 
 						*:nore* *:norem*
 :no[remap]  {lhs} {rhs}		|mapmode-nvo|	*:no*  *:noremap* *:nor*
```
---

This is a such a common pitfall that I wonder whether we should change this in Vim9.  If one wants a trailing space in a mapping written in a Vim9 script, maybe we could require for them to write `<Space>` explicitly to avoid any ambiguity.

**Comment by brammool** [comment]
I don't like changing the semantics of arbitrary commands in Vim 9 script. The map command is not related to Vim 9 at all.

**Comment by lacygoill** [comment]
> I don't like changing the semantics of arbitrary commands in Vim 9 script. The map command is not related to Vim 9 at all.

OK, fair enough.  What about this snippet:
```vim
vim9script
var name: any
def Func()
    lockvar nameX
enddef
Func()
```
    no error

It doesn't give any error right now, neither at compile time, nor at runtime.  And yet `nameX` is not an existing variable.  One of the goals of Vim9 is to help the user spot simple mistakes, by being stricter.  Should we give an error here (only in Vim9, I guess, to not break existing legacy scripts) to help the user spot their mistake?  Or is it like `:map`; i.e. not related to Vim9?

**Comment by lacygoill** [comment]
Also, we already did something similar in patch [8.2.3124](https://github.com/vim/vim/commit/deb108ba0a8599c1307ddc1507c73e7b60f17d36):
```vim
set foldlevel =1
echo 'no error'
```
    no error
```vim
vim9script
set foldlevel =1
```
    E1205: No white space allowed between option and: =1

The space between an option name and the assignment operator is not an error in legacy, but it now is in Vim9, because it can lead to confusing errors (just like in the current issue); and yet `:set` is not related to Vim9 any more than `:map` is.  So, making a trailing space ignored in the rhs of a mapping would not have been a first.

I guess the difference between the 2 situations is that nobody relied on the space in the `:set` case, while there might be people who do rely on a trailing space in the `:map` case.

**Comment by chrisbra** [comment]
not sure if it would be helpful, but perhaps trailing spaces could be fixed/disallowed by a new scriptversion then? Although I think this may add to the confusion, so I not sure if this is actually a good idea.

**Comment by lacygoill** [comment]
> I think this may add to the confusion, so I not sure if this is actually a good idea.

Actually, you're probably right.  Sorry for the noise.

**Comment by brammool** [comment]
>    > I don't like changing the semantics of arbitrary commands in Vim 9 script. The map command is not related to Vim 9 at all.
> 
> OK, fair enough.  What about this snippet:
> ```vim
> vim9script
> var name: any
> def Func()
>     lockvar nameX
> enddef
> Func()
> ```
>     no error
> 
> It doesn't give any error right now, neither at compile time, nor at
> runtime.  And yet `nameX` is not an existing variable.  One of the
> goals of Vim9 is to help the user spot simple mistakes, by being
> stricter.  Should we give an error here (only in Vim9, I guess, to not
> break existing legacy scripts) to help the user spot their mistake?
> Or is it like `:map`; i.e. not related to Vim9?

That is a completely different thing.  Please create a new issue for
this.


-- 
"A mouse can be just as dangerous as a bullet or a bomb."
             (US Representative Lamar Smith, R-Texas)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
