### ISSUE TITLE
Django highlight: update blocktranslate tags

### ISSUE THREAD

**Issue by Huy-Ngo** [vim/vim#9125]
Starting from version 3.1, Django [renamed blocktrans to blocktranslate](https://docs.djangoproject.com/en/3.2/topics/i18n/translation/)

The new tag should be added to support this.

**Comment by lacygoill** [comment]
```diff
diff --git a/runtime/syntax/django.vim b/runtime/syntax/django.vim
index d3ca4de0e..3b784555b 100644
--- a/runtime/syntax/django.vim
+++ b/runtime/syntax/django.vim
@@ -28,7 +28,7 @@ syn keyword djangoStatement contained endspaceless ssi templatetag openblock
 syn keyword djangoStatement contained closeblock openvariable closevariable
 syn keyword djangoStatement contained openbrace closebrace opencomment
 syn keyword djangoStatement contained closecomment widthratio url with endwith
-syn keyword djangoStatement contained get_current_language trans noop blocktrans
+syn keyword djangoStatement contained get_current_language trans noop blocktrans blocktranslate
 syn keyword djangoStatement contained endblocktrans get_available_languages
 syn keyword djangoStatement contained get_current_language_bidi plural
 
```

**Comment by Huy-Ngo** [comment]
Also add  `endblocktranslate` to the next line.

**Comment by brammool** [comment]
Have you managed to contact the maintainer?

**Comment by Huy-Ngo** [comment]
Sorry, I didn't. Just read the CONTRIBUTING.md now; I'm supposed to discuss in the mailing list beforehand right?

**Comment by chrisbra** [comment]
the idea is to first contact the upstream maintainer, so that the files here in the vim repository and the ones managed by the maintainer do not start to conflict. So please try to contact the maintainer.

https://github.com/vim/vim/blob/125ffd21f9601a90b845f1d50c24da0d3938bb59/runtime/syntax/django.vim#L1-L4

If he is unresponsive, Bram may still decide to merge this change.

**Comment by lacygoill** [comment]
Fixed in the latest [update of the runtime files](https://github.com/vim/vim/commit/4700398e384f38f752b432e187462f404b96847d).
