### ISSUE TITLE
sign_getplaced() does not return the placed signs

### ISSUE THREAD

**Issue by rickhowe** [vim/vim#9136]
### Steps to reproduce

For example, after running the following code, 
```
for ln in range(1, 10)
    call sign_define(ln, {'text': ln})
    call sign_place(0, 'test', ln, bufnr(), {'lnum': ln})
endfor
```
`:echo sign_getdefined()`
returns a list of all the defined signs as expected.

But,
`:echo sign_getplaced()`
returns
`[{'signs': [], 'buffer': 1}]`.

### Expected behaviour

As help says, it is expected to return a list of all the placed signs.

### Operating system

Windows 10

### Version of Vim

vim 8.2.3595

**Comment by vim-ml** [comment]
Hi,

On Sun, Nov 14, 2021 at 11:11 PM rickhowe ***@***.***> wrote:

> Steps to reproduce
>
> For example, after running the following code,
>
> for ln in range(1, 10)
>     call sign_define(ln, {'text': ln})
>     call sign_place(0, 'test', ln, bufnr(), {'lnum': ln})
>
>
Note that with this call the signs are placed in a group called 'test' and
not in the global group. To place a sign in the global group, the second
argument should be an empty string.


>
> endfor
>
> :echo sign_getdefined()
> returns a list of all the defined signs as expected.
>
> But,
> :echo sign_getplaced()
>

The sign_getplaced() function without any arguments returns only signs in
the
global group. To display the signs in the group 'test', you need to use:

:echo sign_getplaced(bufnr(), {'group': 'test'})

- Yegappan

>
> returns
> [{'signs': [], 'buffer': 1}].
> Expected behaviour
>
> As help says, it is expected to return a list of all the placed signs.
> Operating system
>
> Windows 10
> Version of Vim
>
> vim 8.2.3595
> Logs and stack traces
>
> *No response*
>
>
>
