### ISSUE TITLE
URI without authority is considered as a local file

### ISSUE THREAD

**Issue by noscript** [vim/vim#9139]
### Steps to reproduce

According to [URI specification](https://datatracker.ietf.org/doc/html/rfc3986/#page-16) the authority component (which is preceded by two slashes `//`) is optional. If the path to `:edit {path}` command doesn't contain an authority component, VIM considers it as a path to local file relative to the current directory. 

For example `news:comp.infosystems.www.servers.unix` is also a valid URI.

Not allowing URIs without authority components limits the possibility to add support for custom protocols and IPC.

To reproduce:
```
:edit myscheme:hello/world
:echo expand('%:p')
:edit myscheme://hello/world
:echo expand('%:p')
```
Prints:
```
/home/my_username/myscheme:hello/world
myscheme://hello/world
```

### Expected behaviour

Prints:
```
myscheme:hello/world
myscheme://hello/world
```

### Operating system

Debian 11

### Version of Vim

gVim 8.2.3593

**Comment by chrisbra** [comment]
Aren't we talking about a niche use case here? What problem are you trying to solve here?

> For example news:comp.infosystems.www.servers.unix is also a valid URI.

Yes, or it could happen to be a local file I am going to edit in which case Vim behaves correctly.

I suspect this is going to be backwards incompatible to change this and I also think, it is much more likely to edit a local file that happens to have a colon in its name rather than trying to access an unusual URI.

**Comment by noscript** [comment]
I've added support for a custom archive format and I was able to use `~` as an alias to home directory:
```
xr:~/path/to/file.xr:some/internal/file.txt
```
But recent changes to VIM (within last 3 months or so) broke that. Now I would need to change the implementation to use `//` and it already starts looking odd:
```
xr://~/path/to/file.xr:some/internal/file.txt
```

>I suspect this is going to be backwards incompatible

Just the opposite, backwards incompatible is the current behavior.

**Comment by chrisbra** [comment]
ah, so fallout from c6376c7, duplicate issue: #8974

I would suggest to simply use `scheme://` format instead. 

Not sure what you mean with: 

> and it already starts looking odd

> Just the opposite, backwards incompatible is the current behavior.

No, how are we going to differentiate between a legal local file called `scheme:file` and a URI: `scheme:file`?

**Comment by noscript** [comment]
> No, how are we going to differentiate between a legal local file called `scheme:file` and a URI: `scheme:file`?

Maybe there could be option to list schemes that denote non-local files.

**Comment by chrisbra** [comment]
personally, I don't think the difference between: 
```
xr:~/path/to/file.xr:some/internal/file.txt
```
and 
```
xr://~/path/to/file.xr:some/internal/file.txt
```

is that much significant and therefore using yet another option is not nice, because it requires users to know and set yet another option. 

So, I'll leave this for others to comment.

**Comment by brammool** [comment]
I'm not quite sure what you are expecting.  Vim does not support editing anything but a local file by default.  Plugins can extend that by using autocommands to inspect the file name and doing something else.  If that doesn't happen, Vim assumes the name is a local file.  Without a preceding slash that is expected relative to the current directory.
There is minimal recognizing of URLs, when the name is very unlikely to be a local file name.  A name with a colon in it is not recognized, as this is a valid local file name.
