### ISSUE TITLE
E474: Invalid argument: cscopequickfix=a-

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#914]
version：7.4.2028 (both gvim & vim)

reproduce:

``` VimL
:set cscopequickfix=a-
```

result:
E474: Invalid argument: cscopequickfix=a-

expect:
as `:help cscopequickfix` said:

``` text
{not available when compiled without the |+quickfix| feature}
'cscopequickfix' specifies whether to use quickfix window to show cscope
results.  This is a list of comma-separated values. Each item consists of
|cscope-find| command (s, g, d, c, t, e, f, i or a) and flag (+, - or 0).
'+' indicates that results must be appended to quickfix window,
'-' implies previous results clearance, '0' or command absence - don't use
quickfix.  Search is performed from start until first command occurrence.
The default value is "" (don't use quickfix anyway).  The following value
seems to be useful: >
    :set cscopequickfix=s-,c-,d-,i-,t-,e-,a-
```

`:set cscopequickfix=a-` is supposed to be ok, not a E474

**Comment by k-takata** [comment]
Maybe this will fix the problem:

``` diff
--- a/src/option.h
+++ b/src/option.h
@@ -429,7 +429,7 @@ EXTERN char_u   *p_csprg;   /* 'cscopeprg' *
 EXTERN int p_csre;     /* 'cscoperelative' */
 # ifdef FEAT_QUICKFIX
 EXTERN char_u  *p_csqf;    /* 'cscopequickfix' */
-#  define  CSQF_CMDS   "sgdctefi"
+#  define  CSQF_CMDS   "sgdctefia"
 #  define  CSQF_FLAGS  "+-0"
 # endif
 EXTERN int p_cst;      /* 'cscopetag' */
```

(Sorry, not tested.)

**Comment by brammool** [comment]
Ken Takata wrote:

> Maybe this will fix the problem:
> 
> ``` diff
> --- a/src/option.h
> +++ b/src/option.h
> @@ -429,7 +429,7 @@ EXTERN char_u *p_csprg;   /* 'cscopeprg' *
>  EXTERN int   p_csre;     /* 'cscoperelative' */
>  # ifdef FEAT_QUICKFIX
>  EXTERN char_u    *p_csqf;    /* 'cscopequickfix' */
> -#  define    CSQF_CMDS   "sgdctefi"
> +#  define    CSQF_CMDS   "sgdctefia"
>  #  define    CSQF_FLAGS  "+-0"
>  # endif
>  EXTERN int   p_cst;      /* 'cscopetag' */
> ```
> 
> (Sorry, not tested.)

That looks right, thanks.

## 

Linux is just like a wigwam: no Windows, no Gates and an Apache inside.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
Since the issue was fixed, then this todo item is no longer relevant:

https://github.com/vim/vim/blob/21829c5f2c86cd525c8468121b4fc54c5d75bf6e/runtime/doc/todo.txt#L3291-L3292
