### ISSUE TITLE
Several inconsistencies regarding 'autochdir'

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#9142]
Vim has several inconsistencies regarding `'autochdir'`:
1. If `'autochdir'` is set and unset and the current window uses global working directory, the global working directory is lost. However, if `'autochdir'` is set and unset and the current window has a local working directory, the global working directory (as returned by `getcwd(-1)`) is not lost.
2. If Vim's current working directory is set by `'autochdir'`, `:verbose pwd` prints the narrowest scope for which the current window has a working directory, but this is not really accurate, as Vim's current working directory is set by `'autochdir'`, not an Ex command.
3. If Vim's current working directory is set by `'autochdir'`, and the current window has a local working directory, `getcwd()` returns the current window's local working directory (which is not Vim's real current working directory)~, while`getcwd(-1)` returns Vim's real current working directory~.
4. It is hard to tell if Vim's current working directory is set by `'autochdir'` without setting up a `DirChanged` autocommand, as `chdir()` can change Vim's working directory again after `'autochdir'`.

**Comment by chrisbra** [comment]
does 0526815c15170a5926e1008600ec29d42d8b64c2 fix those inconsistencies and this issue can be closed?

**Comment by brammool** [comment]
":verbose pwd" should now show the context for the directory. I hope that is sufficient.
There are many places where Vim changes directory, I'm not 100% all of them are covered now.
Let us know if something was missed.

**Comment by zeertzjq** [comment]
Global working directory being lost is not a big deal. I think this is fine. I haven't tested yet.

**Comment by zeertzjq** [comment]
I feel `last_chdir_reason` should be set to `NULL` even if a `:cd`, `:tcd`, `:lcd` command changes to the same directory, as, for example, using `:lcd` to change the current directory to the same directory last set by `:cd` also changes scope output of `:pwd` from `[global]` to `[window]`.

**Comment by zeertzjq** [comment]
> I feel `last_chdir_reason` should be set to `NULL` even if a `:cd`, `:tcd`, `:lcd` command changes to the same directory, as, for example, using `:lcd` to change the current directory to the same directory last set by `:cd` also changes scope output of `:pwd` from `[global]` to `[window]`.

I opened #9160 to change that.
