### ISSUE TITLE
Proposal: Add support for colon delimited line number when opening files

### ISSUE THREAD

**Issue by danielbaak** [vim/vim#9144]
Many compilers, runtimes and loggers output lines containing filename colon line number.

Currently i need to run `vim /home/user/repo/myfile +123` to open a file at line number 123.

I'd like to instead run `vim /home/user/repo/myfile:123`; i.e. just cut and paste the log output including the line number into my command line.

I'd expect this behaviour to also apply to `:tab new` `:vsp` etc. (as the +123 version does now).

The +123 version would still have to be supported, in order not to break existing workflows and or scripts.

I know it's a minor difference, but it's a common usecase for me and I'm curious if others feel the same.

**Comment by lacygoill** [comment]
Duplicate of https://github.com/vim/vim/issues/4707 and https://github.com/vim/vim/issues/7224

---

You might be interested in one of these plugins:

   - [vim-fetch](https://github.com/wsdjeg/vim-fetch)
   - [file-line](https://github.com/lervag/file-line)
   - [search-and-view](https://github.com/lilydjwg/search-and-view)

**Comment by carli2** [comment]
> Duplicate of [#4707](https://github.com/vim/vim/issues/4707) and [#7224](https://github.com/vim/vim/issues/7224)
> 
> You might be interested in one of these plugins:
> 
>     * [vim-fetch](https://github.com/wsdjeg/vim-fetch)
> 
>     * [file-line](https://github.com/lervag/file-line)
> 
>     * [search-and-view](https://github.com/lilydjwg/search-and-view)


I tried https://github.com/lervag/file-line and it didn't work. `vim info:5` opens a new file called `info:5` instead of opening file info at line 5

**Comment by chrisbra** [comment]
ping @lervag then

**Comment by lervag** [comment]
My `file-line` plugin works as expected for me. Feel free to open an issue on the repo @carli2.
