### ISSUE TITLE
No bold font on a light terminal theme

### ISSUE THREAD

**Issue by tehkonst** [vim/vim#9145]
### Steps to reproduce

1. open any directory in gnome-terminal with a dark theme: `vim .`
![image](https://user-images.githubusercontent.com/2618162/142179871-27a3126b-8fb5-47b1-a54d-bc448ab2fc02.png)
2. exit vim `:q`
3. apply any light theme to the terminal
4. open a directory again `vim .`
![image](https://user-images.githubusercontent.com/2618162/142180380-549476fc-78b1-42ae-aaaa-b1edd6a09c9f.png)

As you see on the screenshots the text isn't bold on a light theme. It's the same in a code with enabled syntax. There's no boldness of a text on vim with any light theme.

### Expected behaviour

The text should be bold on dark and light themes at the same places. At least there should be possibility to enable it.

### Operating system

Xubuntu 20.04 xfce4

### Version of Vim

GNOME Terminal v3.36.2; Vim 8.1.2269

**Comment by chrisbra** [comment]
what theme/colortheme are you using?

**Comment by tehkonst** [comment]
I tested on gnome-terminal with "north" and "paper color light" themes. But I also have this problem with my custom colors on xfce4-terminal.

**Comment by chrisbra** [comment]
> I tested on gnome-terminal with "north" and "paper color light" themes

Is that the dark or light colorscheme?

The thing is, I don't see bold keynames in my netrw. You can check yourself. Netrw uses the highlighting group `netrwHelpCmd` for those keys. Check the output of `:hi netrwHelpCmd` to see the definition (or where it links to).  For me it links to `Function` which again links to `Identifier`. None of those declare a bold attribute. 

So I would think, this is an issue of the light colortheme that you are using.

**Comment by tehkonst** [comment]
I don't use any theme in vim.  I only change colors in the  terminal.
 And I don't understand why with one color scheme the text is bold and on the other it's not.
![image](https://user-images.githubusercontent.com/2618162/142191341-1136c7e1-a5b8-437f-9d42-19fad89648f9.png)
![image](https://user-images.githubusercontent.com/2618162/142191437-7cabb172-2456-4e2d-a6ce-38bb40c1ad94.png)

**Comment by chrisbra** [comment]
you are apparently using a dark colorscheme, that defines the bold attribute for certain highlighting groups. Now if you switch to a light background, either the same colorscheme does not support bold for the light background, or you are simply using the default light colorscheme, which does not define bold colors.

**Comment by lacygoill** [comment]
> And I don't understand why with one color scheme the text is bold and on the other it's not.

Because when `&background` is `dark`, the `Identifier` highlight group is given the `cterm=bold` attribute:

    SynColor Identifier	term=underline cterm=bold ctermfg=Cyan ctermbg=NONE gui=NONE guifg=#40ffff guibg=NONE
                                       ^--------^

[source](https://github.com/vim/vim/blob/9459b8d461d6f8345bfa3fb9b3b4297a7950b0bc/runtime/syntax/syncolor.vim#L37)

But not when `&background` is `light`:

    SynColor Identifier	term=underline cterm=NONE ctermfg=DarkCyan ctermbg=NONE gui=NONE guifg=DarkCyan guibg=NONE

[source](https://github.com/vim/vim/blob/9459b8d461d6f8345bfa3fb9b3b4297a7950b0bc/runtime/syntax/syncolor.vim#L48)

The reason for that is given [here](https://github.com/vim/vim/blob/9459b8d461d6f8345bfa3fb9b3b4297a7950b0bc/runtime/syntax/syncolor.vim#L31-L32):

   > " Careful with "cterm=bold", it changes the color to bright for some terminals.

---

As a workaround, you could try this:
```vim
vim9script
augroup BoldFontOnLightTheme
    autocmd!
    autocmd ColorScheme * BoldFontOnLightTheme()
augroup END

def BoldFontOnLightTheme()
    var hl: dict<any> = hlget('Identifier')->get(0, {})
    if hl->empty()
        return
    endif
    if hl->has_key('cterm')
        [hl->extend({cterm: hl.cterm->extend({bold: true})})]->hlset()
    else
        [hl->extend({cterm: {bold: true}})]->hlset()
    endif
enddef
```
This requires the patch [8.2.3578](https://github.com/vim/vim/releases/tag/v8.2.3578) for the [`hlget()`](https://vimhelp.org/eval.txt.html#hlget%28%29) and [`hlset()`](https://vimhelp.org/eval.txt.html#hlset%28%29) functions.

**Comment by chrisbra** [comment]
> SynColor Identifier term=underline cterm=bold ctermfg=Cyan ctermbg=NONE gui=NONE guifg=#40ffff guibg=NONE

ah, i did not see that. Thanks for correction.

**Comment by lacygoill** [comment]
I forgot there were other highlight groups which could be affected by this issue:
```vim
vim9script

augroup BoldFontOnLightTheme
    autocmd!
    autocmd ColorScheme * BoldFontOnLightTheme()
augroup END

const TO_BE_BOLD: list<string> = readfile($VIMRUNTIME .. '/syntax/syncolor.vim')
    ->filter((_, v: string): bool => v =~ '^\s*SynColor\>.*\<\%(cterm\|gui\)=bold\>')
    ->map((_, v: string) => v
    ->matchstr('SynColor\s*\zs\S\+'))
    ->sort()
    ->uniq()

def BoldFontOnLightTheme()
    if &background != 'light'
        return
    endif

    for name: string in TO_BE_BOLD
        var hl: dict<any> = hlget(name, true)->get(0, {})
        if hl->empty()
            return
        endif
        var cterm: dict<bool> = hl->get('cterm', {})->extend({bold: true})
        var newhl: dict<any> = hl->extend({cterm: cterm})
        hlset([newhl])
    endfor
enddef
```
Write the script somewhere and source it with `:source` *before* setting the color scheme in your vimrc.

**Comment by brammool** [comment]
So this is not a problem with Vim?  closing.

**Comment by lacygoill** [comment]
It seems there are still 2 inconsistencies.  Not sure they can be fixed without annoying users who are accustomed to the current attributes.

First, if `cterm=bold` is too unreliable (because we don't know whether the terminal will interpret it as "bold", "bright" or "bold and bright"), then it's weird to use it for `Identifier` on a dark background.  Even weirder, it's not used in the GUI for the same group on the same kind of background.  And it's not used on a light background, neither in the TUI, nor in the GUI.  To be consistent, maybe it should be replaced with `cterm=NONE`:
```diff
diff --git a/runtime/syntax/syncolor.vim b/runtime/syntax/syncolor.vim
index 5b907a3b8..326c403a3 100644
--- a/runtime/syntax/syncolor.vim
+++ b/runtime/syntax/syncolor.vim
@@ -34,7 +34,7 @@ if &background == "dark"
   SynColor Comment	term=bold cterm=NONE ctermfg=Cyan ctermbg=NONE gui=NONE guifg=#80a0ff guibg=NONE
   SynColor Constant	term=underline cterm=NONE ctermfg=Magenta ctermbg=NONE gui=NONE guifg=#ffa0a0 guibg=NONE
   SynColor Special	term=bold cterm=NONE ctermfg=LightRed ctermbg=NONE gui=NONE guifg=Orange guibg=NONE
-  SynColor Identifier	term=underline cterm=bold ctermfg=Cyan ctermbg=NONE gui=NONE guifg=#40ffff guibg=NONE
+  SynColor Identifier	term=underline cterm=NONE ctermfg=Cyan ctermbg=NONE gui=NONE guifg=#40ffff guibg=NONE
   SynColor Statement	term=bold cterm=NONE ctermfg=Yellow ctermbg=NONE gui=bold guifg=#ffff60 guibg=NONE
   SynColor PreProc	term=underline cterm=NONE ctermfg=LightBlue ctermbg=NONE gui=NONE guifg=#ff80ff guibg=NONE
   SynColor Type		term=underline cterm=NONE ctermfg=LightGreen ctermbg=NONE gui=bold guifg=#60ff60 guibg=NONE
```
Second, for the `Statement` and `Type` groups, we currently set the bold attribute in the GUI, but not in the TUI.  That makes sense, but what if the user has set `'termguicolors'` to `true`?  In that case, Vim will use `cterm=NONE`, even though `gui=bold` would be more consistent.  And we have the guarantee that using the bold attribute would not cause any issue, because when `'termguicolors'` is set, Vim does not send sequences in which the colors are indexed in a limited palette (like `CSI 30m`) which the terminal can then unexpectedly map to some brighter equivalent.  Instead, the sequences describe the exact red/green/blue components of the color (e.g. `CSI 38;2;95;135;135m`).  There is no way for the terminal to mess up such a color, because there is no obvious mapping like there is for indexed colors between 0 and 7 (0 into 8, 1 into 9, 2 into 10 ...).

IMO, this would make a default light color scheme nicer to look at, and it would give the results that the OP expected (provided that they write `set termguicolors` in their vimrc):
```diff
diff --git a/runtime/syntax/syncolor.vim b/runtime/syntax/syncolor.vim
index 5b907a3b8..c2841861f 100644
--- a/runtime/syntax/syncolor.vim
+++ b/runtime/syntax/syncolor.vim
@@ -30,31 +30,43 @@ endif
 " too many colors anyway.
 " Careful with "cterm=bold", it changes the color to bright for some terminals.
 " There are two sets of defaults: for a dark and a light background.
+let s:gui = has('termguicolors') && &termguicolors || has('gui_running')
 if &background == "dark"
   SynColor Comment	term=bold cterm=NONE ctermfg=Cyan ctermbg=NONE gui=NONE guifg=#80a0ff guibg=NONE
   SynColor Constant	term=underline cterm=NONE ctermfg=Magenta ctermbg=NONE gui=NONE guifg=#ffa0a0 guibg=NONE
   SynColor Special	term=bold cterm=NONE ctermfg=LightRed ctermbg=NONE gui=NONE guifg=Orange guibg=NONE
-  SynColor Identifier	term=underline cterm=bold ctermfg=Cyan ctermbg=NONE gui=NONE guifg=#40ffff guibg=NONE
-  SynColor Statement	term=bold cterm=NONE ctermfg=Yellow ctermbg=NONE gui=bold guifg=#ffff60 guibg=NONE
+  SynColor Identifier	term=underline cterm=NONE ctermfg=Cyan ctermbg=NONE gui=NONE guifg=#40ffff guibg=NONE
   SynColor PreProc	term=underline cterm=NONE ctermfg=LightBlue ctermbg=NONE gui=NONE guifg=#ff80ff guibg=NONE
-  SynColor Type		term=underline cterm=NONE ctermfg=LightGreen ctermbg=NONE gui=bold guifg=#60ff60 guibg=NONE
   SynColor Underlined	term=underline cterm=underline ctermfg=LightBlue gui=underline guifg=#80a0ff
   SynColor Ignore	term=NONE cterm=NONE ctermfg=black ctermbg=NONE gui=NONE guifg=bg guibg=NONE
+  if s:gui
+    SynColor Statement	term=bold cterm=bold ctermfg=Yellow ctermbg=NONE gui=bold guifg=#ffff60 guibg=NONE
+    SynColor Type	term=underline cterm=bold ctermfg=LightGreen ctermbg=NONE gui=bold guifg=#60ff60 guibg=NONE
+  else
+    SynColor Statement	term=bold cterm=NONE ctermfg=Yellow ctermbg=NONE gui=bold guifg=#ffff60 guibg=NONE
+    SynColor Type	term=underline cterm=NONE ctermfg=LightGreen ctermbg=NONE gui=bold guifg=#60ff60 guibg=NONE
+  endif
 else
   SynColor Comment	term=bold cterm=NONE ctermfg=DarkBlue ctermbg=NONE gui=NONE guifg=Blue guibg=NONE
   SynColor Constant	term=underline cterm=NONE ctermfg=DarkRed ctermbg=NONE gui=NONE guifg=Magenta guibg=NONE
   " #6a5acd is SlateBlue
   SynColor Special	term=bold cterm=NONE ctermfg=DarkMagenta ctermbg=NONE gui=NONE guifg=#6a5acd guibg=NONE
   SynColor Identifier	term=underline cterm=NONE ctermfg=DarkCyan ctermbg=NONE gui=NONE guifg=DarkCyan guibg=NONE
-  SynColor Statement	term=bold cterm=NONE ctermfg=Brown ctermbg=NONE gui=bold guifg=Brown guibg=NONE
   " #6a0dad is Purple
   SynColor PreProc	term=underline cterm=NONE ctermfg=DarkMagenta ctermbg=NONE gui=NONE guifg=#6a0dad guibg=NONE
-  SynColor Type		term=underline cterm=NONE ctermfg=DarkGreen ctermbg=NONE gui=bold guifg=SeaGreen guibg=NONE
   SynColor Underlined	term=underline cterm=underline ctermfg=DarkMagenta gui=underline guifg=SlateBlue
   SynColor Ignore	term=NONE cterm=NONE ctermfg=white ctermbg=NONE gui=NONE guifg=bg guibg=NONE
+  if s:gui
+    SynColor Statement	term=bold cterm=bold ctermfg=Brown ctermbg=NONE gui=bold guifg=Brown guibg=NONE
+    SynColor Type	term=underline cterm=bold ctermfg=DarkGreen ctermbg=NONE gui=bold guifg=SeaGreen guibg=NONE
+  else
+    SynColor Statement	term=bold cterm=NONE ctermfg=Brown ctermbg=NONE gui=bold guifg=Brown guibg=NONE
+    SynColor Type	term=underline cterm=NONE ctermfg=DarkGreen ctermbg=NONE gui=bold guifg=SeaGreen guibg=NONE
+  endif
 endif
 SynColor Error		term=reverse cterm=NONE ctermfg=White ctermbg=Red gui=NONE guifg=White guibg=Red
 SynColor Todo		term=standout cterm=NONE ctermfg=Black ctermbg=Yellow gui=NONE guifg=Blue guibg=Yellow
+unlet! s:gui
 
 " Common groups that link to default highlighting.
 " You can specify other highlighting easily.
```

**Comment by brammool** [comment]
Changing the default colors is more likely to cause problems than solve them.  If someone cares about this then using a color scheme is the most obvious solution. Changing the defaults for consistency is not a good idea.

**Comment by lacygoill** [comment]
Understood.  I just post this here for anyone interested:
```vim
vim9script

augroup ColorschemeCustomizations
    autocmd!
    # Make sure  the `cterm` and  `gui` attributes of the  "preferred" highlight
    # groups are in sync.  Make sure `cterm=bold` is not used in a terminal with
    # a limited palette.
    autocmd ColorScheme * FixPreferredHL()
augroup END

 # `:help group-name`
const PREFERRED_HL: list<string> =<< trim END
    Comment
    Constant
    Identifier
    Ignore
    PreProc
    Special
    Statement
    Type
    Underlined
END
def FixPreferredHL()
    for name: string in PREFERRED_HL
        var hl: dict<any> = hlget(name, true)->get(0, {})
        var gui: dict<bool> = hl->get('gui', {})
        var cterm: dict<bool> = hl->get('cterm', {})
        # We're going to copy the value of `gui` into `cterm`.
        # But we  don't want to  copy the bold  attribute in a  terminal without
        # `'termguicolors'`, because the terminal could interpret it as "bright"
        # or "bold and bright":  https://askubuntu.com/a/875228
        if gui->get('bold') && !&termguicolors
            gui->remove('bold')
        endif
        # if `gui` and `cterm` are not in sync, sync them
        if gui != cterm
            var fixed_attr: dict<any> = hl->extend({cterm: gui})
            hlset([fixed_attr])
        endif
    endfor
enddef
```
It's much better than the previous code:

   - doesn't read any file (so faster)
   - make sure that `cterm` and `gui` are always in sync (so the colorscheme is always consistent)
   - never use `cterm=bold` in a terminal with a limited palette (so no surprise, even in a console)
