### ISSUE TITLE
Terminal buffer can be modified through user input while a terminal job is still running

### ISSUE THREAD

**Issue by bfrg** [vim/vim#9151]
### Steps to reproduce

1. Run: `vim --clean -c 'call term_start("sleep 10", {})'`
2. Start typing text into the terminal window.
3. Result: The text is added permanently to the terminal buffer, even though the buffer is set `'nomodifiable'` by default.

### Expected behaviour

I would have expected Vim to print an error when the terminal buffer is trying to be modified while a job is still running since the terminal job still "owns" the buffer.

On the other hand, changing the buffer with something like `call setline(1, 'test')` will throw the error `E21: Cannot make changes, 'modifiable' is off` as one would have expected.

### Operating system

Gentoo Linux

### Version of Vim

8.2.3613

**Comment by chrisbra** [comment]
Doesn't that mean, that you have fed those keys to the sleep command and the sleep command just did nothing with the input?

What I mean is:  If I run in a normal terminal with a bash `:sleep 10` and type some letters, you will also see those letters, even so sleep doesn't do anything with it.

So I don't think this is a bug.

**Comment by bfrg** [comment]
Yes, I guess you're right. I will close it.
