### ISSUE TITLE
expandcmd() expands $* to 'nonomatch'

### ISSUE THREAD

**Issue by bfrg** [vim/vim#9153]
### Steps to reproduce

I used `expandcmd()` on one of my `&makeprg` that contains a `$*`. It seems like Vim replaces each occurrence of `$*` with `nonomatch`.

1. Run `vim --clean -c 'echomsg expandcmd("$*")'`
2. Result: nonomatch

### Expected behaviour

I don't know what the best approach would be. But 'nonomatch' seems odd. 

Maybe one of the following makes more sense:
1. Replace each occurrence of `$*` with an empty string, just like any non-existent environment variable is replaced with an empty string.
2. Add an optional argument to `expandcmd({string} [, {args}])` and replace each occurrence of `$*` in `{string}` by `{args}`. This is equivalent to the original purpose of `$*` on the command line.

### Operating system

Gentoo Linux

### Version of Vim

8.2.3613

**Comment by chrisbra** [comment]
Hm, interesting. This comes from your shell, try running the command using `:set verbose=5` and you'll see that vim expands those variables by the shell. The command run is (for zsh): `set nonomatch; print -N "$*"`. Unfortunately, the `set` commands also set the positional parameters, so the `$*` will be expanded to the `nonomatch` by your shell.

I think the idea is, to prevent an error if the shell pattern does not match any file in the current directory. The `nonomatch` seems to be necessary for csh like shells, bash doesn't really understand it and therefore assigns this to the positional parameter. For zsh, one could use  `set -o`  not sure for other shells, bash specifically doesn't seem to have a way to set this option without affecting the positional parameters.

See also https://github.com/vim/vim/blob/master/src/os_unix.c#L6668-L6675

**Comment by chrisbra** [comment]
not sure, possibly this patch could be used? Note, this will not expand '$*', but leave it as is.

```diff
diff --git a/src/os_unix.c b/src/os_unix.c
index 0b2b5725e..0ed02f680 100644
--- a/src/os_unix.c
+++ b/src/os_unix.c
@@ -6691,10 +6691,18 @@ mch_expand_wildcards(
     }
     else
     {
-       if (flags & EW_NOTFOUND)
-           STRCPY(command, "set nonomatch; ");
+       if (shell_style == STYLE_GLOB)
+       {
+           // Assume the nonomatch option is valid only for csh
+           // like shells, otherwise, this may set the
+           // positional parameters for the shell, e.g. $*
+           if (flags & EW_NOTFOUND)
+               STRCPY(command, "set nonomatch; ");
+           else
+               STRCPY(command, "unset nonomatch; ");
+       }
        else
-           STRCPY(command, "unset nonomatch; ");
+           STRCPY(command, "");
        if (shell_style == STYLE_GLOB)
            STRCAT(command, "glob >");
        else if (shell_style == STYLE_PRINT)
```

**Comment by chrisbra** [comment]
BTW: quoting from `http://litux.nl/Books/books/www.leothreads.com/e-book/oreillybookself/unix/upt/ch06_09.htm`

> Set nonomatch when you want the C shell to treat nonmatching wildcards like the Bourne shell does . (15.4)

which references: http://litux.nl/Books/books/www.leothreads.com/e-book/oreillybookself/unix/upt/ch15_04.htm

This makes it sounds, as if the `nonomatch` should only be used for C-like shells.

**Comment by brammool** [comment]
The fix makes sense.  Can you make a PR for it?

**Comment by chrisbra** [comment]
of course!
