### ISSUE TITLE
Vim9: no default links when `:syntax enable` run from vimrc

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9161]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        syntax enable
        highlight clear String
        highlight String
    EOF
    )

This is printed on the command-line:

    String         xxx cleared

That's wrong.  `:syntax enable` causes `$VIMRUNTIME/syntax/syncolor.vim` to be sourced which defines `String` like this:

    SynLink String		Constant

In turn, `:SynLink` is defined like this:

    command -nargs=* SynLink hi def link <args>

IOW, `String` is defined like this:

    hi def link String Constant
       ^^^

Notice the `def` argument which is passed to `:hi`.  It means that the link should survive after `:hi clear`, as documented at [`:help :highlight-default`](https://vimhelp.org/syntax.txt.html#%3Ahighlight-default).

**Expected behavior**

This is printed on the command-line:

    String         xxx links to Constant

**Operating system**

Ubuntu 20.04.3 LTS

**Version of Vim**

8.2 Included patches: 1-3619

**Additional Context**

No issue if `:syntax enable` is run from the legacy context:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        legacy syntax enable
        highlight clear String
        highlight String
    EOF
    )

    String         xxx links to Constant

But why should that matter?  If there is a reason, then maybe it should be documented.

---

Patch adding a test:
```diff
diff --git a/src/testdir/test_vim9_cmd.vim b/src/testdir/test_vim9_cmd.vim
index ee381ed1d..d163bd339 100644
--- a/src/testdir/test_vim9_cmd.vim
+++ b/src/testdir/test_vim9_cmd.vim
@@ -1581,5 +1581,13 @@ def Test_previewpopup()
   set previewpopup&
 enddef
 
+def Test_syntax_enable()
+  syntax clear
+  syntax enable
+  highlight clear String
+  assert_equal(true, hlget('String')->get(0, {})->get('default', false))
+  syntax clear
+enddef
+
 
 " vim: ts=8 sw=2 sts=2 expandtab tw=80 fdm=marker
```

**Comment by lacygoill** [comment]
The issue comes from `g:syntax_cmd` whose value should be `enable` when `$VIMRUNTIME/syntax/syncolor.vim` is sourced, but which is *sometimes* empty in the Vim9 context.

**Comment by lacygoill** [comment]
> which is sometimes empty in the Vim9 context.

s/empty/undefined/

**Comment by lacygoill** [comment]
The issue comes from `set_internal_string_var()` which wrongly assumes that it's being evaluated in legacy where a variable is global without a scope.  That's not true in Vim9.  Prefixing `syntax_cmd` with `g:` fixes the issue:
```diff
diff --git a/src/syntax.c b/src/syntax.c
index b3545b37b..3002bc90a 100644
--- a/src/syntax.c
+++ b/src/syntax.c
@@ -3777,7 +3777,7 @@ syn_cmd_on(exarg_T *eap, int syncing UNUSED)
     static void
 syn_cmd_enable(exarg_T *eap, int syncing UNUSED)
 {
-    set_internal_string_var((char_u *)"syntax_cmd", (char_u *)"enable");
+    set_internal_string_var((char_u *)"g:syntax_cmd", (char_u *)"enable");
     syn_cmd_onoff(eap, "syntax");
     do_unlet((char_u *)"g:syntax_cmd", TRUE);
 }
@@ -3792,7 +3792,7 @@ syn_cmd_reset(exarg_T *eap, int syncing UNUSED)
     set_nextcmd(eap, eap->arg);
     if (!eap->skip)
     {
-	set_internal_string_var((char_u *)"syntax_cmd", (char_u *)"reset");
+	set_internal_string_var((char_u *)"g:syntax_cmd", (char_u *)"reset");
 	do_cmdline_cmd((char_u *)"runtime! syntax/syncolor.vim");
 	do_unlet((char_u *)"g:syntax_cmd", TRUE);
     }
```

**Comment by lacygoill** [comment]
There are other places where `do_cmdline_cmd()` is invoked to execute an Ex command:

    src/normal.c:3349:3:		do_cmdline_cmd((char_u *)"$tabnew");
    src/normal.c:3360:3:		do_cmdline_cmd((char_u *)"browse $tabnew");
    src/normal.c:5901:2:	do_cmdline_cmd((char_u *)"%s//~/&");
    src/session.c:1086:5:    do_cmdline_cmd((char_u *)"let Save_VV_this_session = v:this_session");
    src/session.c:1088:5:    do_cmdline_cmd((char_u *)"let v:this_session = Save_VV_this_session");

I wonder whether we should make sure they're using the legacy syntax.

**Comment by lacygoill** [comment]
> I wonder whether we should make sure they're using the legacy syntax.

For example, in Vim9, a line specifier or a range such as `$` and `%` must be preceded by a colon:

    ✘
    $tabnew

    ✔
    :$tabnew
```diff
diff --git a/src/normal.c b/src/normal.c
index aab336a5f..819f187d4 100644
--- a/src/normal.c
+++ b/src/normal.c
@@ -3346,7 +3346,7 @@ handle_tabmenu(void)
 
 	case TABLINE_MENU_NEW:
 	    if (current_tab == 0)
-		do_cmdline_cmd((char_u *)"$tabnew");
+		do_cmdline_cmd((char_u *)":$tabnew");
 	    else
 	    {
 		vim_snprintf((char *)IObuff, IOSIZE, "%dtabnew",
@@ -3357,7 +3357,7 @@ handle_tabmenu(void)
 
 	case TABLINE_MENU_OPEN:
 	    if (current_tab == 0)
-		do_cmdline_cmd((char_u *)"browse $tabnew");
+		do_cmdline_cmd((char_u *)"browse :$tabnew");
 	    else
 	    {
 		vim_snprintf((char *)IObuff, IOSIZE, "browse %dtabnew",
@@ -5898,7 +5898,7 @@ nv_g_cmd(cmdarg_T *cap)
 	break;
 
     case '&':
-	do_cmdline_cmd((char_u *)"%s//~/&");
+	do_cmdline_cmd((char_u *)":%s//~/&");
 	break;
 
     /*
diff --git a/src/session.c b/src/session.c
index d2b360df8..bcc044474 100644
--- a/src/session.c
+++ b/src/session.c
@@ -1083,9 +1083,9 @@ write_session_file(char_u *filename)
     ssop_flags = (SSOP_BLANK|SSOP_CURDIR|SSOP_FOLDS|SSOP_GLOBALS
 		  |SSOP_HELP|SSOP_OPTIONS|SSOP_WINSIZE|SSOP_TABPAGES);
 
-    do_cmdline_cmd((char_u *)"let Save_VV_this_session = v:this_session");
+    do_cmdline_cmd((char_u *)"legacy let Save_VV_this_session = v:this_session");
     failed = (do_cmdline_cmd((char_u *)mksession_cmdline) == FAIL);
-    do_cmdline_cmd((char_u *)"let v:this_session = Save_VV_this_session");
+    do_cmdline_cmd((char_u *)"legacy let v:this_session = Save_VV_this_session");
     do_unlet((char_u *)"Save_VV_this_session", TRUE);
 
     ssop_flags = save_ssop_flags;
```

**Comment by lacygoill** [comment]
There might be more locations where `do_cmdline_cmd()` wrongly assumes to be allowed to use the legacy syntax, because sometimes it's not always passed a simple string (which is what I looked for).  Sometimes, it receives a variable.  For example:
```diff
diff --git a/src/normal.c b/src/normal.c
index aab336a5f..72a962261 100644
--- a/src/normal.c
+++ b/src/normal.c
@@ -3349,7 +3349,7 @@ handle_tabmenu(void)
 		do_cmdline_cmd((char_u *)"$tabnew");
 	    else
 	    {
-		vim_snprintf((char *)IObuff, IOSIZE, "%dtabnew",
+		vim_snprintf((char *)IObuff, IOSIZE, ":%dtabnew",
 							     current_tab - 1);
 		do_cmdline_cmd(IObuff);
 	    }
```

**Comment by brammool** [comment]
I fixed the problem with ":syntax enable".
For the others I see no way to execute them in Vim 9 context.
If you can find an example, please open a new issue.
