### ISSUE TITLE
Vim9: cannot unlet! non-existing variable

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9165]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE +'vim9 unlet! non_existing'

`E1081` is given:

    E1081: Cannot unlet non_existing

**Expected behavior**

No error is given, because `:unlet` is appended a bang.

**Operating system**

Ubuntu 20.04.3 LTS

**Version of Vim**

8.2 Included patches: 1-3627

**Additional Context**

No issue in legacy:

    vim -Nu NONE +'legacy unlet! non_existing'

---

I couldn't find anything at `:help vim9` nor at `:help :unlet` explaining that `:unlet!` behavior should be different in Vim9.

**Comment by lacygoill** [comment]
That's because in Vim9 we cannot unlet a script-local variable.  Sorry for the noise.

**Comment by brammool** [comment]
```vim -Nu NONE +'vim9 unlet! g:non_existing'``` works silently.  I think it's good, so you don't accidentally forget the g: prefix.

**Comment by lacygoill** [comment]
I was confused because there are 2 rules to consider, independent from each other, and which can be summarized with this table:

    ┌────────────────┬────────────────────────────────────────────────────────┐
    │ CAN I UNLET A  │                         context                        │
    │ VARIABLE ?     ├─────────────────────────────────┬──────────────────────┤
    │                │              legacy             │          Vim9        │
    ├──────────┬─────┼─────────────────────────────────┼──────────────────────┤
    │ variable │ yes │ yes                             │ only if not declared │
    │ exists   ├─────┼─────────────────────────────────┼──────────────────────┤
    │          │ no  │ only with a bang                │ ?                    │
    └──────────┴─────┴─────────────────────────────────┴──────────────────────┘

The bottom-right cell is tricky; I wasn't sure which rule should win over the other.
The one which states that we can delete anything by appending a bang after `:unlet`?
Or the one which states that we can delete anything provided it's not declared?

Because in the case of a non-existing script-local variable, the two rules give contradictory answers.

**Comment by lacygoill** [comment]
> Because in the case of a non-existing script-local variable, the two rules give contradictory answers.

Here is what I mean:

A script-local variable can be declared, so the rule which states that we can delete anything provided that it cannot be declared would say that `unlet! non_existing` should fail.

But according to the rule which states that we can delete a non-existing variable if we append a bang to `:unlet`, the same command should actually work.

I guess it's better to give an error though, in case the variable does start to exist later (after some change in the code), at which point an error should necessarily be given.

**Comment by brammool** [comment]
> I was confused because there are 2 rules to consider, independent from
> each other, and which can be summarized with this table:
> 
>     ┌────────────────┬────────────────────────────────────────────────────────┐
>     │ CAN I UNLET A  │                         context                        │
>     │ VARIABLE ?     ├─────────────────────────────────┬──────────────────────┤
>     │                │              legacy             │          Vim9        │
>     ├──────────┬─────┼─────────────────────────────────┼──────────────────────┤
>     │ variable │ yes │ yes                             │ only if not declared │
>     │ exists   ├─────┼─────────────────────────────────┼──────────────────────┤
>     │          │ no  │ only with a bang                │ ?                    │
>     └──────────┴─────┴─────────────────────────────────┴──────────────────────┘
> 
> The bottom-right cell is tricky; I wasn't sure which rule should win
> over the other.  The one which states that we can delete anything by
> appending a bang after `:unlet`?  Or the one which states that we can
> delete anything provided it's not declared?
> 
> Because in the case of a non-existing script-local variable, the two
> rules give contradictory answers.

Both rules apply.  You can never unlet a variable that was declared and
the bang doesn't silence that, because it is a mistake.

The bang is only to avoid an error if the variable doesn't exist.

-- 
John:   When I'm playing tennis with friends I always get carried away
George: You hurt your foot each time?

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
