### ISSUE TITLE
Count passed to dot command is not used when repeating Visual mode operator

### ISSUE THREAD

**Issue by obcat** [vim/vim#9176]
**Describe the issue**

A count passed to the dot command might not be used when repeating a Visual mode operator that takes a count.
I could observe this issue with these ones:

- `CTRL-A`
- `g CTRL-A`
- `CTRL-X`
- `g CTRL-X`
- `>`
- `<`

**To Reproduce**

1. Run `vim -Nu NONE`.

1. Write these lines to the buffer:

    ```
    0
    0
    ```

1. Press `v3<C-a>` at line 1.

    The buffer becomes:

    ```
    3
    0
    ```

    This is expected.

1. Press `5.` at line 2.

    The buffer becomes:

    ```
    3
    3
    ```

    This is not expected.

**Expected behavior**

The buffer becomes:

```
3
5
```

Because the document of the dot command says:

> If you enter a count, it will replace the last one.

[source](https://github.com/vim/vim/blob/3c19b5050040fb74e4e39048f17dce853fdafc08/runtime/doc/repeat.txt#L30-L31)

**Environment**

- Vim 8.2.3635
- macOS 10.15.7
- iTerm2

**Comment by brammool** [comment]
The count for a visual change repeat is not used.  See ":help visual-repeat".
It will certainly not be passed to CTRL-A, only the text change is remembered.

If we would implement a count for the visual operator repeat somehow, it would affect the size of the area, not the text.

**Comment by obcat** [comment]
> The count for a visual change repeat is not used. See ":help visual-repeat". It will certainly not be passed to CTRL-A, only the text change is remembered.
> 
> If we would implement a count for the visual operator repeat somehow, it would affect the size of the area, not the text.

I got it, but It seems there is no description about how a count is handled at `:help visual-repeat`.
As a suggestion here is a patch:

```diff
diff --git a/runtime/doc/visual.txt b/runtime/doc/visual.txt
index 1fcee21f6..8ad561f32 100644
--- a/runtime/doc/visual.txt
+++ b/runtime/doc/visual.txt
@@ -370,7 +370,8 @@ same amount of text as the last time:
   last line the same number of characters as in the last line the last time.
 The start of the text is the Cursor position.  If the "$" command was used as
 one of the last commands to extend the highlighted text, the repeating will
-be applied up to the rightmost column of the longest line.
+be applied up to the rightmost column of the longest line.  The count passed
+to the |.| command is not used.
 
 
 ==============================================================================
```

Closing, since it turns out this is not a bug. Thank you.
