### ISSUE TITLE
Patch 8.2.3607 (commit 9459b8d46) is breaking guiligatures in gvim on cursor movement

### ISSUE THREAD

**Issue by dusanx** [vim/vim#9181]
### Steps to reproduce

1. Set guiligatures so something reasonable like `:set guiligatures=!#$&*+-./:<=>?@[]^\|~\"`
2. Type line with ligature characters, for instance `==>  >-- && || /= != !==`, if font supports it this char combinations will be shown like proper ligatures.
3. Move cursor over this characters, left and right, ligatures are not restored after cursor passes.

### Expected behaviour

Since we draw cursor as separate string, every underlying ligature combo was shown as ligature, while cursor char was being shown as non-ligaturized char, exactly as it should be. On cursor movement we did restore more than just a cursor char, which in turn redraws entire ligature combo properly. With patch 9459b8d46 cursor redrawing is optimized so we don't restore underlying ligature combo.

Solution:
9459b8d46 is going in good direction but when restoring screen on cursor movement we need to test and if it was ligature char on previous cursor position we need to restore (left and right) all other nested ligature chars, which will in turn restore ligature as whole.

I'll take a look at this in next day or two, of course if somebody wants to jump in just let me know.

### Operating system

Linux

### Version of Vim

9459b8d46 and onwards

**Comment by dusanx** [comment]
@presuku after looking at code for 9459b8d46, maybe it is wiser if you have time to look at this. I have described possible solution above but I am not that great with GTK3 -- I can fix the problem but it can take couple of days. What do you think?

**Comment by dusanx** [comment]
Update: 9459b8d46 is not directly responsible for this, it is well written, it just exposed underlying things that need fixing. Fix will be in gui.c, gui_undraw_cursor() so we can keep everything done so far. I'll have PR in couple of days. Two questions:

1. Working in gui.c and gui_undraw_cursor() I need to add GTK specific code. Is it Ok to do it in gui.c?
2. gui.cursor_col is holding cursor col position. How do I find out last visible column for that view? (I can look this up somewhere in code but I would appreciate help so I don't waste time digging).

**Comment by brammool** [comment]
> Update: 9459b8d46 is not directly responsible for this, it is well
> written, it just exposed underlying things that need fixing. Fix will
> be in gui.c, gui_undraw_cursor() so we can keep everything done so
> far. I'll have PR in couple of days. Two questions:
> 
> 1. Working in gui.c and gui_undraw_cursor() I need to add GTK specific
> code. Is it Ok to do it in gui.c?

Yes, there are already a few blocks with:
	#ifdef FEAT_GUI_GTK
If the same might also be used by other GUI implementations a gui_mch_
function can be used, but then it needs to be added to several files.

> 2. gui.cursor_col is holding cursor col position. How do I find out
> last visible column for that view? (I can look this up somewhere in
> code but I would appreciate help so I don't waste time digging).

Perhaps you are looking for getvcol().  But it not fast, you can use
win->w_wrow and win->w_wcol if they are valid.


-- 
User:       I'm having problems with my text editor.
Help desk:  Which editor are you using?
User:       I don't know, but it's version VI (pronounced: 6).
Help desk:  Oh, then you should upgrade to version VIM (pronounced: 994).

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by presuku** [comment]
Sorry for the late reply, I was out with my family visiting my wife's mother.
I'm not using ligature fonts and I'm not sure what is the best solution for ligature.
But, I also found issues of rendering italic font (include a cursor update issue), so I hope that both ligature and italic are well.

**Comment by dusanx** [comment]
No worries, I found my way trough code and none of your patch actually broke anything, it just exposed what needs fixing. If that italic problem persists please document is somewhere, I am working on optimizing italic/bold/bolditalic trough glyphs so better to fix all we can upfront.

**Comment by brammool** [comment]
The problem of this issue is taken care of in #9190, thus we can close this.
Problems with italic fonts is old.  Vim already redraws the character before the cursor in an attempt to fix most problems,
but there are likely more.  But that's a separate issue.
