### ISSUE TITLE
Vim9: no error for giving a non-existing variable to `:lockvar`

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9188]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        var name: any
        def Func()
            lockvar nameX
        enddef
        Func()
    EOF
    )

No error is given.

**Expected behavior**

An error is given because there is a typo in the variable name passed to `:lockvar`:

    lockvar nameX
                ^
                ✘

**Operating system**

Ubuntu 20.04.3 LTS

**Version of Vim**

8.2 Included patches: 1-3640

**Additional Context**

The same thing happens in legacy:
```vim
vim9script
var name: any
function Legacy()
    lockvar s:nameX
endfunction
Legacy()
echo 'no error'
```
    no error

Maybe it's a convenient feature, I don't know.
But since Vim9 tries to be more strict, and help the user find their mistakes early, I thought we could give an error, instead of letting them with a variable which they think is locked while in reality it can still mutate, which could give confusing errors much later in their code.

**Comment by brammool** [comment]
I'm not sure why there was no error for trying to lock or unlock a non-existing variable, but it indeed makes it very hard to spot a typo.
