### ISSUE TITLE
How to build vim from source code in Unicode?

### ISSUE THREAD

**Issue by qinzhaokun** [vim/vim#920]
I work with vim in Windows, But not full windows, is Nano server which is a new window operation system developed by Microsoft. Some windows' APIs are missing. Like

```
GetDligItemTextA
```

can I build source code in Unicode and let the program use the function GetDligItemTextW (unicode) directly? 

Is there any configuration file or command to set this?

**Comment by k-takata** [comment]
Currently Vim uses both ANSI APIs and Unicode APIs, and select them on run time (not on compile time).
So there is no such configuration for now.

BTW, we are planning to remove old codes for Win9x after Vim 8.0 is released. Maybe we can stop using ANSI APIs at that time. (However ANSI APIs are used when `'enc'` is same as the current codepage. If we want to stop using ANSI APIs, we need to convert the encoding of characters even when `'enc'` is same as the current codepage.)

**Comment by chrisbra** [comment]
Please use the mailinglist for such issues. Closing.
