### ISSUE TITLE
Signed Integer Overflow (Undefined Behavior) and Flawed Checks

### ISSUE THREAD

**Issue by weichslgartner** [vim/vim#9202]
### Steps to reproduce

@iamvineeth23 provided me with some fuzz targets which resulted in the following findings.

To reproduce, build with clang sanitizers:
```
CC=clang CFLAGS="-fsanitize=address,undefined" LDFLAGS="-fsanitize=address,undefined" ./configure && make
```

## Signed Integer Overflow (Undefined Behavior) in ex_docmd.c:4407
```
echo "|.44444444444444444444444" > ub.txt
 ./src/vim -u NONE -X -Z -e -s -S ub.txt -c :qa!                                        
ex_docmd.c:4407:12: runtime error: signed integer overflow: 9223372036854775807 + 1 cannot be represented in type 'long int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ex_docmd.c:4407:12
```

## Signed Integer Overflow (Undefined Behavior) in normal.c:634

Open ``./src/vim``
type "|4444444444444444444"

```
normal.c:634:25: runtime error: signed integer overflow: 4444444444444444444 * 10 cannot be represented in type 'long int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior normal.c:634:25
```

The overflow check in  [normal.c:634](https://github.com/vim/vim/blob/2228cd72cf7c6f326e4e41179e88d37595ca4abc/src/normal.c#L634) assumes that signed integer will wrap around, however, signed integer overflow is already UB and may summon [nasal demons](http://www.catb.org/jargon/html/N/nasal-demons.html) or just may lead to optimizing out the check.

```
ca.count0 = ca.count0 * 10 + (c - '0');
if (ca.count0 < 0)	    // overflow
    ca.count0 = 999999999L;
```

Similar flawed check at [normal.c#L706](https://github.com/vim/vim/blob/2228cd72cf7c6f326e4e41179e88d37595ca4abc/src/normal.c#L706)

Other checks seems also to be UB:
https://github.com/vim/vim/blob/a1198124370a366ff02811a43845a631b5c6e7f0/src/ex_getln.c#L2723
https://github.com/vim/vim/blob/a1198124370a366ff02811a43845a631b5c6e7f0/src/ex_getln.c#L3537
https://github.com/vim/vim/blob/a1198124370a366ff02811a43845a631b5c6e7f0/src/regexp_nfa.c#L1726

### Expected behaviour

no undefined behavior 

### Operating system

Ubuntu 18.04 LTS

### Version of Vim

v8.2.3656

**Comment by brammool** [comment]
That the error mentions 9223372036854775807 already indicates a problem: atol() has limited the value to LONG_MAX.

We cannot possibly check for all overflows, we do need to add checks where it causes a problem when the value is wrong.

**Comment by weichslgartner** [comment]
Saw that it is fixed now. Also closes  https://github.com/vim/vim/issues/2248
