### ISSUE TITLE
Vim9: not enough lines joined for multiline statement when sourcing script in debug mode

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9203]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        var lines =<< trim END
            vim9script
            var s = ['c', 'b', 'a']
                ->reverse()
                ->join()
        END
        var fname = '/tmp/t.vim'
        lines->writefile(fname)
        execute 'debug source ' .. fname
    EOF
    )

Then, execute the debugging command `step` to step through the sourced file.
Finally, execute the debugging command `next` to execute `:vim9script` and come back to debug mode before the following assignment.

This is printed:

    line 2: var s = ['c', 'b', 'a']

Notice that the chain of 2 methods (`->reverse()` and `->join()`) is missing.

**Expected behavior**

This is printed:

    line 2: var s = ['c', 'b', 'a']    ->reverse()    ->join()

Notice the presence of the 2 methods `reverse()` and `join()`.

**Operating system**

Ubuntu 20.04.3 LTS

**Version of Vim**

8.2 Included patches: 1-3657

**Additional Context**

In legacy, with the exact same code, the methods are correctly joined with the first line of the assignment:
```vim
vim9script
var lines =<< trim END
    let s = ['c', 'b', 'a']
        \->reverse()
        \->join()
END
var fname = '/tmp/t.vim'
lines->writefile(fname)
execute 'debug source ' .. fname
```
    # after executing >step
    line 1: let s = ['c', 'b', 'a']->reverse()->join()
                                   ^-----------------^

**Comment by brammool** [comment]
This will not be possible.  The debug prompt is invoked before executing the command, we don't even know what kind of command it is.  Thus we don't know if any following lines will be included.  That only happens when parsing the expression.
We could guess that if the next line starts with "->" it's likely a continuation, but many others can't be so easily recognized, and doing it sometimes would be confusing.

**Comment by lacygoill** [comment]
> This will not be possible. The debug prompt is invoked before executing the command, we don't even know what kind of command it is. Thus we don't know if any following lines will be included. That only happens when parsing the expression.

Understood.  But it works in legacy (I assume that's a benefit of explicit continuation lines), so we might want to document this difference.  I'll try to come up with a patch later.

**Comment by lacygoill** [comment]
```diff
diff --git a/runtime/doc/starting.txt b/runtime/doc/starting.txt
index d4e8cf818..96895157d 100644
--- a/runtime/doc/starting.txt
+++ b/runtime/doc/starting.txt
@@ -345,6 +345,10 @@ a slash.  Thus "-R" means recovery and "-/R" readonly.
 							*-D*
 -D		Debugging.  Go to debugging mode when executing the first
 		command from a script. |debug-mode|
+
+		NOTE: In Vim9 script, if a command is written at the script
+		level and continues on the next line, only the first line is
+		printed before the debugging prompt.
 		{not available when compiled without the |+eval| feature}
 
 							*-C*
```
