### ISSUE TITLE
Can't copy 

### ISSUE THREAD

**Issue by NsdHSO** [vim/vim#9205]
I use macos and Iterm2
And I want to copy in vim can not because he puts on - insert (line of sight) -
![Screenshot 2021-11-24 at 09 19 29](https://user-images.githubusercontent.com/37635083/143192643-c1082f7b-c246-41f6-b660-9ae11f41c79c.png)

What can be done. Because it's frustrating
![Screenshot 2021-11-24 at 09 19 54](https://user-images.githubusercontent.com/37635083/143192754-0bab206b-dffc-4741-b04d-d067a7baaadf.png)

**Comment by k-takata** [comment]
If you use the GUI version of Vim on mac, you should be able to use Command+C/X/V. (See `:help mac-standard-mappings`.)
If you use the console version of Vim, you may have two options:

* Disable Vim's mouse handling (`set mouse=`) and let your terminal handle the clipboard.
* Use clipboard-enabled version of Vim and use the clipboard register (`"*`).
  E.g. select a text using visual mode, then type `"*y` to copy the text to the clipboard.

The second one should be the Vim way.

**Comment by k-takata** [comment]
I think this is a user question rather than a feature request.
Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com.
