### ISSUE TITLE
Got error compiling the latest source code

### ISSUE THREAD

**Issue by illusorypan** [vim/vim#921]
Hi all,

I got an error when compiling the latest source code (7.4.2033). See screen capture below.
![2016-07-13_215544](https://cloud.githubusercontent.com/assets/17306686/16826657/a5d540ce-4944-11e6-9663-bb1ec3548e4f.jpg)

Thanks in advance.

**Comment by k-takata** [comment]
Can you show the result of the following command?

```
gcc -dumpmachine
```

**Comment by illusorypan** [comment]
That gives out "mingw32"

**Comment by k-takata** [comment]
Oh, that was not expected. How about this patch?

``` diff
--- a/src/Make_cyg_ming.mak
+++ b/src/Make_cyg_ming.mak
@@ -149,7 +149,7 @@ WINDRES_CC = $(CC)

 # Get the default ARCH.
 ifndef ARCH
-ARCH := $(shell $(CC) -dumpmachine | sed -e 's/-.*//' -e 's/_/-/')
+ARCH := $(shell $(CC) -dumpmachine | sed -e 's/-.*//' -e 's/_/-/' -e 's/^mingw32$$/i686/')
 endif


```

**Comment by illusorypan** [comment]
Thanks for the comment. It works!
