### ISSUE TITLE
Allow dragging popups without borders

### ISSUE THREAD

**Issue by noscript** [vim/vim#9218]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

It would be great to allow dragging popups from any point, whether the mouse is on its border or not. Popup borders are very painful and difficult to precisely click on.

**Describe the solution you'd like**

Introduce a new option to `popup_create()` to start dragging the popup by clicking inside of it.

**Describe alternatives you've considered**

I tried to make popup borders really thick but they  take too much screen space.

**Comment by brammool** [comment]
If the mouse is used to move the popup, then it will not be possible to select text in it.
Have you tried making the border thick only on one side?

**Comment by noscript** [comment]
I tried to use only on one side border, but still it is still not very comfortable for small popups. If the the pop is meant to be dragged from any point then it is expected that it will conflict with text selection. But just like with status lines which are also draggable, it is still possible to select with Ctrl-Shift.

**Comment by noscript** [comment]
I think it would be best to call the new option something `noselect` to explicitly tell what is the the side effect. 

Anyways, the text selection on popups is not fully featured. It cannot be extended with keyboard and leaves a lot of artifacts if mouse goes outside of popup area.

![image](https://user-images.githubusercontent.com/717109/143684578-1e7ba828-fb65-480c-843e-0027f76cf659.png)

It acts just like Ctrl-Shift selection which is not going anywhere.

**Comment by brammool** [comment]
I don't find it difficult to pick up a popup and drag it from the one-cell border.
I wonder how many people actually have trouble dragging a popup.

We could add a "fat corner", but it makes rendering text more difficult and the corner may be outside of the visible area.
Disabling selection is one of those options that has the wrong value either way...

**Comment by noscript** [comment]
I'm building a UI with many one-line height popups where rearranging the nodes would be an important feature. And to keep the UI compact I had to disable the borders.

>We could add a "fat corner"

I think "fat corner" would not allow stacking many popups close to each other and still keep them graggable.

>Disabling selection is one of those options that has the wrong value either way...

Disabling selection is not the goal but it would help avoiding accidental text selection.

>I don't find it difficult to pick up a popup and drag it from the one-cell border.

Yes, 1 cell border is my last resort and it's definitely better than nothing.

Another not very practical example, what if someone was making a game using popups with non-rectangular shapes (like killersheep) where dragging game characters would be part of the game play. A gamer would be having difficulties to play, because instead of dragging he would be selecting text inside popups most of the time.

**Comment by brammool** [comment]
> I'm building a UI with many one-line height popups where rearranging
> the nodes would be an important feature. And to keep the UI compact I
> had to disable the borders.
> 
> >We could add a "fat corner"
> 
> I think "fat corner" would not allow stacking many popups close to
> each other and still keep them graggable.
> 
> >Disabling selection is one of those options that has the wrong value either way...
> 
> Disabling selection is not the goal but it would help avoiding
> accidental text selection.
> 
> >I don't find it difficult to pick up a popup and drag it from the one-cell border.
> 
> Yes, 1 cell border is my last resort and it's definitely better than nothing.
> 
> Another not very practical example, what if someone was making a game
> using popups with non-rectangular shapes (like killersheep) where
> dragging game characters would be part of the game play. A gamer would
> be having difficulties to play, because instead of dragging he would
> be selecting text inside popups most of the time.

OK, you convinced me. It's quite easy to implement.  But then a test
needs to be made...

-- 
ARTHUR: The swallow may fly south with the sun, or the house martin or the
        plover seek warmer hot lands in winter, yet these are not strangers to
        our land.
SOLDIER: Are you suggesting coconuts migrate?
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by noscript** [comment]
Thank you so much!
