### ISSUE TITLE
Octave ftdetect is overly generous and matches Objective-C files too

### ISSUE THREAD

**Issue by anntzer** [vim/vim#9220]
### Steps to reproduce

```sh
printf '#include <header.h>\n' >inc.m && vim -u NONE -c 'filetype on | e inc.m | set ft?'
printf '#define SOME_MACRO\n#include<header.h>\n' >def.m && vim -u NONE -c 'filetype on | e def.m | set ft?'
```

The first file is detected as objc but the second as octave because of the overly generous regex at https://github.com/vim/vim/commit/deba5eb195d6ac70171d4973091fa884809fa3fa#diff-eacc3172370ae087a8cfbfee30922eccb8a166e55ea33062b557d03a126bda8cR288, which I guess was intended to detect octave block comments (https://octave.org/doc/v4.2.0/Block-Comments.html) but also matches simple `#define`s.  Either the regex should exclude `#define`s, or `#define`s need to be added to the regex detecting objc just above.

### Expected behaviour

objc is detected twice.

### Operating system

Arch Linux

### Version of Vim

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov 09 2021 19:35:34) Included patches: 1-3582

**Comment by dkearns** [comment]
Overly generous is a kind description of the pattern.  It was simplified about a week later but it's still getting this wrong.  I'll fix it later today.

As you've probably noticed you can use `let g:filetype_m = "objc"` to override it if you don't use anything else with that extension.

Thanks.
