### ISSUE TITLE
debcontrol: Fields XS-Debian-Vcs-Git and such are not highlighted

### ISSUE THREAD

**Issue by elboulangero** [vim/vim#9224]
### Steps to reproduce

Get a package from a Debian derivative (eg. Ubuntu) that defines a field such as `XS-Debian-Vcs-Git`

    wget http://archive.ubuntu.com/ubuntu/pool/main/g/gnome-keyring/gnome-keyring_40.0-3ubuntu1.debian.tar.xz
    tar -xf gnome-keyring_40.0-3ubuntu1.debian.tar.xz
    vi debian/control

What I see is that the fields `Vcs-Git` and `Vcs-Browser` are properly highlighted, but the fields `XS-Debian-Vcs-Git` and `XS-Debian-Vcs-Browser` are not.

![Screenshot from 2021-11-26 15-56-42](https://user-images.githubusercontent.com/1942580/143554783-f2039c5e-0de5-41dc-b6fe-fbd67fb28c4c.png)

### Expected behaviour

The values for the fields `XS-Debian-Vcs-Git` and `XS-Debian-Vcs-Browser` should be highlighted.

### Operating system

Debian Sid

### Version of Vim

`2:8.2.3565-1+b1`

**Comment by elboulangero** [comment]
More background on that.

Fields such as `XS-Debian-Vcs-*` were discussed as back as 2007 in the Ubuntu mailing lists: https://lists.ubuntu.com/archives/ubuntu-devel/2007-March/023366.html.

In short, these fields  are used to keep track of the values from the upstream package, in a forked package. This is similar to the field `XSBC-Original-Maintainer` (which is explicitly supported by vim's `debcontrol.vim`), except that they decided to go for the naming convention `XS-<origin>-Vcs-Git` instead of `XS-Original-Vcs-Git`.

It seems to be quite widely used. If we look at the `/var/lib/apt/lists` on a Ubuntu Impish system:

```
$ grep ^Debian-Vcs *_Sources | wc -l
147

$ grep -h ^[a-zA-Z]*-Vcs *_Sources | cut -d: -f1 | sort | uniq -c
     73 Debian-Vcs-Browser
     71 Debian-Vcs-Git
      3 Debian-Vcs-Svn
      2 Original-Vcs-Browser
      1 Original-Vcs-Bzr
      1 Original-Vcs-Git
      1 Orig-Vcs-Browser
      1 Orig-Vcs-Svn
```

**Comment by chrisbra** [comment]
those are maintained as part of the debian project: https://salsa.debian.org/vim-team/vim-debian/blob/master/syntax/debcontrol.vim ping @jamessan

**Comment by elboulangero** [comment]
@chrisbra Thanks for the quick feedback!

@jamessan Please tell me what's the preferred workflow, I can open a PR in Salsa, or open a bug in the Debian bugtracker if you prefer. Note that I created a PR #9225 with a tentative fix.
