### ISSUE TITLE
Popup dragging with vertical borders is reported only for one direction

### ISSUE THREAD

**Issue by noscript** [vim/vim#9227]
### Steps to reproduce

1. Source:
```vim
call popup_clear()
call popup_create("hello", #{drag: 1, border: [0,1,0,1]})

function! MyFunc()
  call feedkeys("\<LeftDrag>", 'n')

  let mouse_pos = getmousepos()
  if mouse_pos.winid->win_gettype() != "popup"
    return
  endif

  echom 'drag' mouse_pos.screenrow mouse_pos.screencol
endfunction
map <LeftDrag> <Cmd>call MyFunc()<CR>
```
2. Try dragging the popup around. The coordinates are printed only when dragging popup strictly in right direction. Nothing when dragging down or up or left.

### Expected behaviour

Coordinates are printed when dragging the popup up or down or left. 

### Operating system

Debian 11

### Version of Vim

8.2.3640

**Comment by brammool** [comment]
This works as expected: When you drag left, down or up the mouse is not in the popup window but in the window below it.
If you remove the check for the window type you get the message on every move.
