### ISSUE TITLE
Vim9: leaving colon in 'indentkeys' breaks blockwise edition of dictionary containing lambdas

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9229]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        var lines =<< trim END
            var d = {
            a: () => 0,
            b: () => 0,
            c: () => 0,
            }
        END
        lines->setline(1)
        filetype indent on
        &filetype = 'vim'
        execute "normal! jf)\<C-V>jjA: number"
    EOF
    )

The buffer contains this:

    var d = {
            a: (): number => 0,
    b: ()   a: (): number => 0,
    c: ()   a: (): number => 0,
    }

**Expected behavior**

The buffer contains this:

    var d = {
    a: (): number => 0,
    b: (): number => 0,
    c: (): number => 0,
    }

**Operating system**

Ubuntu 20.04.3 LTS

**Version of Vim**

8.2 Included patches: 1-3682

**Additional Context**

The issue comes from the `:` item in the value of the `'indentkeys'` option.

From `:help indentkeys-format`:

   > ":"      if you type ':' after a label or case statement

AFAIK, there is no label or case statement in Vim script.

Can we drop `:`?  If we do, the issue is fixed:
```diff
diff --git a/runtime/indent/vim.vim b/runtime/indent/vim.vim
index d5d0d94b5..3f0c17a3b 100644
--- a/runtime/indent/vim.vim
+++ b/runtime/indent/vim.vim
@@ -12,6 +12,7 @@ let b:did_indent = 1
 setlocal indentexpr=GetVimIndent()
 setlocal indentkeys+==end,=},=else,=cat,=finall,=END,0\\,0=\"\\\ 
 setlocal indentkeys-=0#
+setlocal indentkeys-=:
 
 let b:undo_indent = "setl indentkeys< indentexpr<"
 
```

**Comment by brammool** [comment]
We need to fix both the way the inserted text is obtained and adjust 'indentkeys'.  I'll make a patch for the first one.

**Comment by lacygoill** [comment]
I can still reproduce the issue.
I think that's because the colon is still in `'indentkeys'` in the Vim indent plugin.

**Comment by lacygoill** [comment]
I had a look at the test in patch [8.2.3684](https://github.com/vim/vim/releases/tag/v8.2.3684).

That's what it runs:
```vim
vim9script
var lines =<< trim END
    var d = {
    a: () => 0,
    b: () => 0,
    c: () => 0,
    }
END
lines->setline(1)
set runtimepath=$VIMRUNTIME
filetype plugin indent on
setlocal shiftwidth=2 expandtab filetype=vim
setlocal indentkeys+=:
execute "normal! 2Gf)\<c-v>2jA: asdf\<Esc>"
```
Which gives this (expected):

    var d = {
      a: (): asdf => 0,
    b: (): asdf => 0,
    c: (): asdf => 0,
    }

Now, if we run the same code but without setting `'expandtab'` nor `'shiftwidth'`:
```vim
vim9script
var lines =<< trim END
    var d = {
    a: () => 0,
    b: () => 0,
    c: () => 0,
    }
END
lines->setline(1)
set runtimepath=$VIMRUNTIME
filetype plugin indent on
setlocal filetype=vim
setlocal indentkeys+=:
execute "normal! 2Gf)\<c-v>2jA: asdf\<Esc>"
```
Which gives this (NOT expected):

    var d = {
            a: (): asdf => 0,
    b: ()   a: (): asdf => 0,
    c: ()   a: (): asdf => 0,
    }

**Comment by brammool** [comment]
> I can still reproduce the issue.
> I think that's because the colon is still in `'indentkeys'` in the Vim
> indent plugin.

You mean that typing a colon re-indents?  The filetype plugin was
updated, will be in the next runtime files update.

-- 
The MS-Windows registry is no more hostile than any other bunch of state
information... that is held in a binary format... a format that nobody
understands... and is replicated and cached in a complex and largely
undocumented way... and contains large amounts of duplicate and obfuscated
information...  (Ben Peterson)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
I submitted patch 8.2.3687 that should handle this better.  At least the examples, with and without Tabs, work now.

**Comment by lacygoill** [comment]
> I submitted patch 8.2.3687 that should handle this better. At least the examples, with and without Tabs, work now.

I can confirm that 8.2.3687 fixes the issue.  Thank you very much.
