### ISSUE TITLE
Vim9: allow consolidation of multiple declarations of same type

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9230]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

It is cumbersome to write several consecutive variable declarations with the same type.
```vim
vim9script

var lnum: number
var col: number
var off: number
var curswant: number
[_, lnum, col, off, curswant] = getcurpos()
```
**Describe the solution you'd like**

Let the user merge several declarations with the same type into a single one.  This way, the previous snippet could be re-written like this:
```vim
vim9script

var lnum, col, off, curswant: number
[_, lnum, col, off, curswant] = getcurpos()
```
Which is easier to write, and IMO doesn't make the code less readable.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by brammool** [comment]
I'm not a fan of this short form.  It's less easy to get an overview of the variables.  When adding or removing one it's more work.
Let's keep it simple and not add another mechanism.

For the unpack mechanism it can be useful to declare the variable at the same time:
```var [lnum: number, col: number, off: number, curswant: number] = getcurpos()```
However, this does not allow for some variables to already exist. it would have to be a bit more verbose:
```
var lnum: number
...
[number, var col: number, var off: number, var curswant: number] = getcurpos()
```
It's not that much better than just declaring them all beforehand though.

**Comment by lacygoill** [comment]
> I'm not a fan of this short form. It's less easy to get an overview of the variables.
   > When adding or removing one it's more work.
   > Let's keep it simple and not add another mechanism.

OK, understood.  Closing then.
