### ISSUE TITLE
Vim9: \`=expr\` not expanded for enough commands

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9232]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            var name = '/tmp/file'
            windo edit `=name`
        enddef
        Func()
    EOF
    )

An error is given:

    E121: Undefined variable: name

**Expected behavior**

No error is given, because according to the help, even though a command which is not compiled cannot directly see variables local to a function, it can still see them via the \`=expr\` syntax:

   > The same is true for commands that are not compiled, such as `:global`.
   > For these the backtick expansion can be used.  Example: >
   > 	def Replace()
   > 	  var newText = 'blah'
   > 	  g/pattern/s/^/`=newText`/
   > 	enddef

And it does seem that `:windo` is executed (like `:global`):
```vim
vim9script
def Func()
    var name = '/tmp/file'
    windo edit `=name`
enddef
filter /EXE/ disassemble Func
```
    2 EXEC     windo edit `=name`
      ^--^

**Operating system**

Ubuntu 20.04.3 LTS

**Version of Vim**

8.2 Included patches: 1-3682

**Additional Context**

A backtick expansion works in a `:global` command:
```vim
vim9script
def Func()
    var name = '/tmp/file'
    global/^/edit `=name`
enddef
Func()
```
    no error

A `:vglobal` command:
```vim
vim9script
def Func()
    var name = '/tmp/file'
    vglobal/not found/edit `=name`
enddef
Func()
```
    no error

A `:folddoopen` command:
```vim
vim9script
def Func()
    var name = '/tmp/file'
    folddoopen edit `=name`
enddef
Func()
```
    no error

And a `:folddoclosed` command:
```vim
vim9script
def Func()
    var name = '/tmp/file'
    folddoclosed edit `=name`
enddef
Func()
```
    no error

This seems inconsistent.  Why does a backtick expansion work for some commands/functions which execute other Ex commands, but not for all of them?

It does not work for `:bufdo`:
```vim
vim9script
def Func()
    var name = '/tmp/file'
    bufdo edit `=name`
enddef
Func()
```
    E121: Undefined variable: name

Nor `:argdo`:
```vim
vim9script
def Func()
    var name = '/tmp/file'
    args /tmp/file
    argdo edit `=name`
enddef
Func()
```
    E121: Undefined variable: name

Nor `:cdo`:
```vim
vim9script
def Func()
    var name = '/tmp/file'
    silent helpgrep grail
    cdo edit `=name`
enddef
Func()
```
    E121: Undefined variable: name

Nor `:cfdo`:
```vim
vim9script
def Func()
    var name = '/tmp/file'
    silent helpgrep grail
    cfdo edit `=name`
enddef
Func()
```
    E121: Undefined variable: name

Nor `:ldo`:
```vim
vim9script
def Func()
    var name = '/tmp/file'
    silent lhelpgrep grail
    ldo edit `=name`
enddef
Func()
```
    E121: Undefined variable: name

Nor `:lfdo`:
```vim
vim9script
def Func()
    var name = '/tmp/file'
    silent lhelpgrep grail
    lfdo edit `=name`
enddef
Func()
```
    E121: Undefined variable: name

Nor `execute()`:
```vim
vim9script
def Func()
    var name = '/tmp/file'
    execute('edit `=name`')
enddef
Func()
```
    E121: Undefined variable: name

Nor `win_execute()`:
```vim
vim9script
def Func()
    var name = '/tmp/file'
    win_execute(win_getid(), 'edit `=name`')
enddef
Func()
```
    E121: Undefined variable: name

**Comment by lacygoill** [comment]
Well, I guess it's useless to support the syntax for `execute()` and `win_execute()`, since they already expect a string argument, moving the variable out of it is probably easier to read/write:
```vim
vim9script
def Func()
    var name = '/tmp/file'
    execute('edit ' .. name)
enddef
Func()
```
So the only remaining issue are all the `:*do` commands.

**Comment by brammool** [comment]
This was implemented for commands that expand their argument, but not for commands that take an argument which is a command, which is then expanded later.  I'll make it work, there might be some side effects in corner cases though.
