### ISSUE TITLE
inconsistent handling of numbers with quotes

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9240]
A legacy script using [`:help scriptversion-4`](https://vimhelp.org/eval.txt.html#scriptversion-4), or a Vim9 script, supports a syntax where a big number can include quotes so as to make it more readable:

    :vim9 echo 1'234'567
    1234567

It works fine when used as a number expression.  But it works inconsistently when passed as a suffix argument to an Ex command.  For example, it works for a user Ex command:
```vim
vim9script
command -nargs=1 Cmd Func(<args>)
def Func(n: number)
    echomsg n
enddef
Cmd 1'234
```
    1234

But it seems that it doesn't work when passed to builtin Ex commands, like `:all`:
```vim
vim9script
for i in range(1, 20)
    execute 'argadd file' .. i
endfor
all 1'2
```
    E488: Trailing characters: '2: :all 1'2

Or sleep:
```vim
vim9script
sleep 1'234
```
    E475: Invalid argument: '234

Should this syntax be supported in this context?  If not, do we need a proper error message?  Like:

    E1234: cannot use number with quotes as Ex command argument

---

The same issue applies when the command argument is passed in prefix position (rather than suffix):
```vim
vim9script
for i in range(1, 20)
    execute 'argadd file' .. i
endfor
echomsg argidx()
silent :1'2next
echomsg argidx()
```
    0
    1

But this time, it seems worse because no error is given at all.  So the user might think that their code is working fine while it does not.  In the last snippet, notice that we jump from argument 0 to argument 1 in the arglist.  But the user wrote `1'2`.  If the syntax was supported, the quote would have been removed, and the jump would have been from argument 0 to argument 12.  IOW, the last command should have output:

    0
    12

Again, should a proper error be given?

---

At the very least, we might want to document this limitation.  As a suggestion, here is a patch:
```diff
diff --git a/runtime/doc/eval.txt b/runtime/doc/eval.txt
index 004f9d4bb..2011a0e15 100644
--- a/runtime/doc/eval.txt
+++ b/runtime/doc/eval.txt
@@ -14889,6 +14889,8 @@ instead of failing in mysterious ways.
 	easier to read: >
 		echo 1'000'000
 <	The quotes must be surrounded by digits.
+	NOTE: This syntax only works in an expression; not when passed as a
+	count argument to a builtin Ex command.
 
 	Test for support with: >
 		has('vimscript-4')
```

**Comment by brammool** [comment]
> A legacy script using [`:help
> scriptversion-4`](https://vimhelp.org/eval.txt.html#scriptversion-4),
> or a Vim9 script, supports a syntax where a big number can include
> quotes so as to make it more readable:
> 
>     :vim9 echo 1'234'567
>     1234567
> 
> It works fine when used as a number expression.  But it works
> inconsistently when passed as a suffix argument to an Ex command.  For
> example, it works for a custom user Ex command:
> ```vim
> vim9script
> command -nargs=1 Cmd Func(<args>)
> def Func(n: number)
>     echomsg n
> enddef
> Cmd 1'234
> ```
>     1234
> 
> But it seems that it doesn't work when passed to builtin Ex commands,
> like `:all`:
> ```vim
> vim9script
> for i in range(1, 20)
>     execute 'argadd file' .. i
> endfor
> all 1'2
> ```
>     E488: Trailing characters: '2: :all 1'2
> 
> Or sleep:
> ```vim
> vim9script
> sleep 1'234
> ```
>     E475: Invalid argument: '234
> 
> Should this syntax be supported in this context?  If not, do we need a
> proper error message?  Like:
> 
>     E1234: cannot use number with quotes as Ex command argument

I think we can support it, at least where it currently gives an error
message.  There is one generic place to get a count for an Ex command, I
can change that one.  But some commands may have their own way of
getting a number, we need to find each of them and handle it separately.

I'm not 100% sure there is some command where a following single quote
would be accepted.  To stay on the safe side we could do this only for
Vim9 script.

> The same issue applies when the command argument is passed in prefix position (rather than suffix):
> ```vim
> vim9script
> for i in range(1, 20)
>     execute 'argadd file' .. i
> endfor
> echomsg argidx()
> silent :1'2next
> echomsg argidx()
> ```
>     0
>     1
> 
> But this time, it seems worse because no error is given at all.  So
> the user might think that their code is working fine while it does
> not.  In the last snippet, notice that we jump from argument 0 to
> argument 1 in the arglist.  But the user wrote `1'2`.  If the syntax
> was supported, the quote would have been removed, and the jump would
> have been from argument 0 to argument 12.  IOW, the last command
> should have output:
> 
>     0
>     12
> 
> Again, should a proper error be given?

In a range we can use marks, thus using a single quote embedded in a
number will quickly be confusing.

It should indeed give an error instead of silently accepting the wrong
range.


-- 
How come wrong numbers are never busy?

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
In legacy, for `:argument`, no error is given when using a number with a quote; although everything after the quote is silently ignored:
```vim
vim9script
for i in range(1, 20)
    execute printf(':$ argadd file%02d', i)
endfor
legacy silent argument 1'2
echomsg argidx()
```
    0

But for `:bNext`, still in legacy, an error is given because of the quote:
```vim
vim9script
for i in range(1, 20)
    execute printf('edit file%02d', i)
endfor
legacy bNext 1'2
```
    E488: Trailing characters: '2: legacy bNext 1'2

This seems a bit inconsistent.

**Comment by lacygoill** [comment]
We can't use a number with a quote to express a buffer number:
```vim
vim9script
for i in range(1, 20)
    execute printf('edit file%02d', i)
endfor
bdelete 1'2
```
    E94: No matching buffer for 1'2

Because the quote is parsed literally.  It's probably working as intended, although maybe it could be documented.

**Comment by lacygoill** [comment]
In Vim9 and in legacy, we cannot use a number with a quote for `:breakadd`.  Weirdly enough, the latter parses the quote as being part of the function name which doesn't make sense, because a quote is not a valid character in a function name:
```vim
vim9script
def Func()
    eval 01 + 0
    eval 02 + 0
    eval 03 + 0
    eval 04 + 0
    eval 05 + 0
    eval 06 + 0
    eval 07 + 0
    eval 08 + 0
    eval 09 + 0
    eval 10 + 0
    eval 11 + 0
    eval 12 + 0
enddef
breakadd func 1'2 Func
breaklist
```
    1  func '2 Func  line 1
            ^-----^

**Comment by lacygoill** [comment]
Sorry, I'll open separate issues later.
