### ISSUE TITLE
Vim9: should we enforce delimiters around the pattern passed to :vimgrep?

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9244]
Suppose a script executes `:vimgrep` without using delimiters to surround the pattern argument, and write a special bracket expression such as `<cWORD>` for the pattern:

    :vimgrep <cWORD> %

The semantics of this command cannot be known in advance.  It depends on the text.

Consider this snippet:
```vim
vim9script
edit /tmp/file
'foo !x!bar'->setline(1)
cursor(1, 6)
vimgrep <cWORD> %
```
    Cannot open file "bar"

Vim looks for the pattern `x` in the file `bar` and in the current file.  And if there is no file named `bar`, an error is given.
But the user who wrote this command probably expected Vim to look for the pattern `!x!bar` in the current file.

The issue is that Vim actually executed this:

    :vimgrep !x!bar %
             ^ ^
             parsed as delimiters, not as pattern

More generally, any character in the expansion might be parsed as anything: delimiter, pattern, flag, filename...

If we don't enforce delimiters, this kind of command can sometimes work, and sometimes give weird errors.

OTOH, if we do enforce delimiters around the pattern, then the command would consistently fail with a useful message, making the user rewrite the `:vimgrep` command like this:

    execute printf('vimgrep /%s/ %%', expand('<cWORD>'))
                            ^  ^
Test:
```vim
vim9script
edit /tmp/file
'foo !x!bar'->setline(1)
cursor(1, 6)
execute printf('vimgrep /%s/ %%', expand('<cWORD>'))
```
    no weird error

---

A similar issue can affect `<cword>`.
```vim
vim9script
edit /tmp/file
'foo !'->setline(1)
cursor(1, 5)
vimgrep <cword> %
```
    E682: Invalid search pattern or delimiter

Here, `E682` is given because `!` was parsed as a delimiter instead of a pattern.

**Comment by lacygoill** [comment]
Just to be clear: the suggestion is not to change the semantics of `:vimgrep` in Vim9, but to disallow a special syntax which is too unpredictable (the one allowing the user to drop the delimiters in legacy).

**Comment by brammool** [comment]
I often use :grep without delimiters, let's not change that.
What we can do is not expand <word> and the like until after the pattern.

**Comment by brammool** [comment]
Actually, `:grep <cword> *.c` is a useful command.  I rather not change this.
