### ISSUE TITLE
Vim9: Error when passing a lambda name to function() then calling it

### ISSUE THREAD

**Issue by mityu** [vim/vim#9251]
### Steps to reproduce

Run this shell script:
```bash
vim -Nu NONE -S <(cat <<'EOF'
  vim9script

  def Func()
    var outer = 'foo'
    var F = () => {
      outer = 'bar'
    }
    execute printf('call %s()', string(F))
  enddef
  Func()
EOF
)
```

This error is given:
```
Error detected while processing command line..script /dev/fd/63[10]..function <SNR>1_Func[5]..<lambda>1:
line    1:
LOADOUTER depth more than scope levels
```

### Expected behaviour

No error is given.

### Operating system

macOS Big Sur

### Version of Vim

Vim 8.2.3715

**Comment by mityu** [comment]
### Additional information
No error is given in these context:
- at script level in Vim9 script

```bash
vim -Nu NONE -S <(cat <<'EOF'
  vim9script

  var outer = 'foo'
  var F = () => {
    outer = 'bar'
  }
  execute printf('call %s()', string(F))
EOF
)
```

- in legacy Vim script (both in function and at script level)

```bash
vim -Nu NONE -S <(cat <<'EOF'
  function Func()
    let outer = 'foo'
    let F = {-> outer}
    execute printf('call %s()', string(F))
  endfunction
  call Func()
EOF
)
```

```bash
vim -Nu NONE -S <(cat <<'EOF'
  let s:outer = 'foo'
  let F = {-> s:outer}
  execute printf('call %s()', string(F))
EOF
)
```

**Comment by brammool** [comment]
Yeah, the scope for the closure is not available when called from a legacy context.  It should give a relevant error message.

**Comment by lacygoill** [comment]
> the scope for the closure is not available when called from a legacy context

Does this mean that a command `:execute`d from a function is run in a legacy context?
Because that's exactly what the original snippet does:

    def Func()
      ...
      execute printf('call %s()', string(F))
    enddef

But if that's the case, then we should have to use the legacy syntax.  That's not the case:
```vim
vim9script
def Func()
    execute 'g:name = 123'
enddef
Func()
echo g:name
```
    123

Notice that `123` was echo'ed.  Which means that the `g:name` assignment succeeded even without `:let`.  Which means the command was run in a Vim9 context; not a legacy one.

This is also confirmed with this snippet:
```vim
vim9script
def Func()
    execute 'eval "x" is# "x"'
enddef
Func()
```
    E15: Invalid expression: "is# "x""

An error is given because the comparison operator `is#` is not supported in Vim9.  But it is in legacy.

**Comment by brammool** [comment]
>    > the scope for the closure is not available when called from a legacy context
> 
> Does this mean that a command `:execute`d from a function is run in a legacy context?
> Because that's exactly what the original snippet does:
> 
>     def Func()
>       ...
>       execute printf('call %s()', string(F))
>     enddef
> 
> But if that's the case, then we should have to use the legacy syntax.  That's not the case:
> ```vim
> vim9script
> def Func()
>     execute 'g:name = 123'
> enddef
> Func()
> echo g:name
> ```
>     123
> 
> Notice that `123` was echo'ed.  Which means that the `g:name` assignment succeeded even without `:let`.  Which means the command was run in a Vim9 context; not a legacy one.
> 
> This is also confirmed with this snippet:
> ```vim
> vim9script
> def Func()
>     execute 'eval "x" is# "x"'
> enddef
> Func()
> ```
>     E15: Invalid expression: "is# "x""
> 
> An error is given because the comparison operator `is#` is not
> supported in Vim9.  But it is in legacy.

The call itself is executed in the normal script command handling, not
in the execution context of a compiled function.  That means the
execution context, where the variable is defined on the stack, is not
available.

I looked into how this could be made to work, but it requires the
original execution context be made globally available (or passed down
through many, many levels of functions) to where the compiled function
is called.  Not sure if we can then know what stack frame the referenced
variable would be in.  Quite complicated.

-- 
FIRST VILLAGER: We have found a witch.  May we burn her?
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> I looked into how this could be made to work, but it requires the
   > original execution context be made globally available (or passed down
   > through many, many levels of functions) to where the compiled function
   > is called.  Not sure if we can then know what stack frame the referenced
   > variable would be in.  Quite complicated.

It's not an issue here anyway, since `:execute` was not necessary (neither `:call`):

    execute printf('call %s()', string(F))
    ⇔
    execute printf('%s()', string(F))
    ⇔
    call (F, [])
    ⇔
    F()

So, the original code could be fixed like this:
```vim
vim9script
def Func()
  var outer = 'foo'
  var F = () => {
    outer = 'bar'
  }
  F()
enddef
Func()
```
    no error

And if for some reason, an `:execute` is really necessary, then `F` can be declared at the script-level:
```vim
vim9script
var F: func
def Func()
  var outer = 'foo'
  F = () => {
    outer = 'bar'
  }
  execute 'F()'
enddef
Func()
```
    no error
