### ISSUE TITLE
cannot use modified function keys without setting 'ttymouse'

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9256]
**Steps to reproduce**

Open a gnome terminal, and run this shell command:

    TERM=gnome vim -Nu NONE -i NONE -S <(cat <<'EOF'
        execute "set <xF1>=\<Esc>[1;*P"
        nnoremap <S-F1> <Cmd>echomsg "'S-F1'"<CR>
    EOF
    )

Press `<S-F1>`.  After about 1s, `E353: Nothing in register "` is given.

**Expected behavior**

No error is given, `S-F1` is immediately echo'ed on the command-line because of the user mapping whose lhs is `<S-F1>`.

**Operating system**

Ubuntu 20.04.3 LTS

**Version of Vim**

8.2 Included patches: 1-3723

**Additional Context**

The issue can be fixed by setting `'ttymouse'` to `sgr`, `xterm`, `xterm2` or `urxvt`.  But why is that necessary?  This option is for mouse codes, not for modified function keys.  There is nothing at [`:help 'ttymouse'`](https://vimhelp.org/options.txt.html#%27ttymouse%27) which suggests that it should be set in a certain way for modified function keys to be usable in mappings.

This is the source of a lot of confusion.  As an example, see [this comment](https://github.com/vim/vim/issues/9131#issuecomment-967775117), [this issue](https://github.com/vim/vim/issues/9254), [this other issue](https://github.com/alacritty/alacritty/issues/5508), and [this other long issue](https://github.com/alacritty/alacritty/issues/919) with 24 comments.

If that's not a bug, we might want to document this requirement:
```diff
diff --git a/runtime/doc/options.txt b/runtime/doc/options.txt
index b0000adf9..5f455da53 100644
--- a/runtime/doc/options.txt
+++ b/runtime/doc/options.txt
@@ -8366,7 +8366,9 @@ A jump table for the options with a short description can be found at |Q_op|.
 	If you do not want 'ttymouse' to be set to "xterm2" or "sgr"
 	automatically, set t_RV to an empty string: >
 		:set t_RV=
-<
+<	On non-xterm terminals, if you want to map modified function keys, you
+	may need to set this option to "sgr", "xterm", "xterm2", or "urxvt".
+
 						*'ttyscroll'* *'tsl'*
 'ttyscroll' 'tsl'	number	(default 999)
 			global
```
But IMO that's not enough.  It is still too difficult for users to know the right commands to execute to be able to map all the modified function keys they might want to use.

It's the same issue in tmux, for which there is already this snippet at `:help tmux-integration`:

    " Enable modified arrow keys, see  :help xterm-modifier-keys
    execute "silent! set <xUp>=\<Esc>[@;*A"
    execute "silent! set <xDown>=\<Esc>[@;*B"
    execute "silent! set <xRight>=\<Esc>[@;*C"
    execute "silent! set <xLeft>=\<Esc>[@;*D"

That only covers the arrow keys, and only if `'ttymouse'` is set correctly.  It doesn't cover the other function keys.  For those, the documentation would need another patch, which I already suggested in issue https://github.com/vim/vim/issues/9131

There are 3 possibilities:

   1. we improve the help to clearly explain how to map all modified function keys in non xterm terminals (gnome, tmux, alacritty, ...)
   2. we automatically set the relevant termcap entries (as well as `'ttymouse'` if necessary) when `&term` is a modern terminal
   3. we do both

With regards to `1.`, the patch from issue https://github.com/vim/vim/issues/9131 could easily be adapted.

Note that issues related to modified function keys are frequent.  Just in the last few weeks/months, there were also https://github.com/vim/vim/issues/9059 and https://github.com/vim/vim/issues/9009.

**Comment by lacygoill** [comment]
Basically, this is what most users need in their vimrc if they use a modern terminal:

    " why is that necessary?
    set ttymouse=sgr

    " Enable modified arrow keys, see  :help xterm-modifier-keys
    execute "set <xUp>=\<Esc>[@;*A"
    execute "set <xDown>=\<Esc>[@;*B"
    execute "set <xRight>=\<Esc>[@;*C"
    execute "set <xLeft>=\<Esc>[@;*D"

    " Enable modified Home, End, and F1 to F4 function keys,
    " see  :help xterm-function-keys
    execute "set <xHome>=\<Esc>[1;*H"
    execute "set <xEnd>=\<Esc>[1;*F"
    execute "set <xF1>=\<Esc>[1;*P"
    execute "set <xF2>=\<Esc>[1;*Q"
    execute "set <xF3>=\<Esc>[1;*R"
    execute "set <xF4>=\<Esc>[1;*S"

    " Enable modified PageUp, PageDown, and F5 to F12 function keys:
    execute "set <PageUp>=\<Esc>[5;*~"
    execute "set <PageDown>=\<Esc>[6;*~"
    execute "set <F5>=\<Esc>[15;*~"
    execute "set <F6>=\<Esc>[17;*~"
    execute "set <F7>=\<Esc>[18;*~"
    execute "set <F8>=\<Esc>[19;*~"
    execute "set <F9>=\<Esc>[20;*~"
    execute "set <F10>=\<Esc>[21;*~"
    execute "set <F11>=\<Esc>[23;*~"
    execute "set <F12>=\<Esc>[24;*~"

Can we set some of those termcap entries automatically when `&term` matches a recent terminal?  At the very least, the first four ones, because that's the ones which are causing most issues.

**Comment by lacygoill** [comment]
> The issue can be fixed by setting 'ttymouse' to sgr, xterm, xterm2 or urxvt. But why is that necessary?

Because:

   - modified function keys start with the CSI sequence (i.e. `^[[`)
   - in a non-xterm terminal, the `<DecMouse>` key is assigned CSI
   - setting `'ttymouse'` to `sgr`, `xterm`, `xterm2`, or `urxvt` removes the `<DecMouse>` key from the termcap database

Now the new question is this:  why does Vim (wrongly) translate CSI into `<DecMouse>` on non-xterm terminals, when it's used at the start of *some* keys but not all?

For example, in a gnome terminal, here is how `<F5>` is set:

    set <F5>=^[[15~
             ^^^
             CSI

And there is no issue.  We can map `<F5>`.  Which means that Vim does not translate the CSI inside `<F5>` into `<DecMouse>`.  Why can't Vim do the same with the CSI inside `<xUp>`?

    set <xUp>=^[[@;*A
              ^^^
              CSI

The only difference I can in `:set termcap` is the position of the keys.  `<xUp>` is positioned *after* `<DecMouse>`, while `<PageUp>` is before.

Does the order of the key definitions matter when Vim translates byte sequences into Vim keysyms?  If so, can we move `<DecMouse>` at the very end, *after* any modified function key?

**Comment by brammool** [comment]
This is tricky.  The DEC mouse code is recognized by starting with CSI.  But then later it's rejected because the arguments are not right.
We can specifically check for four number arguments.  That should at least solve it for when DEC mouse is used, which is whenever compiled with more than normal features.
