### ISSUE TITLE
Cause error when calling list2blob() with range() result

### ISSUE THREAD

**Issue by kuuote** [vim/vim#9261]
### Steps to reproduce

1. launch vim with `vim --clean`
2. execute `:echo list2blob(range(4))`

### Expected behaviour

Displays `0z00010203`

### Operating system

Arch Linux

### Version of Vim

v8.2.3724

### Logs and stack traces

```shell
E685: Internal error: tv_get_number(UNKNOWN)
0z
```

**Comment by chrisbra** [comment]
if you are going to create a PR, you don't have to create a corresponding issue for the same problem first. So let's just close this one here and leave the PR open.

**Comment by kuuote** [comment]
I'm sure. move comment to PR.
