### ISSUE TITLE
[BUG] Syntax highlighting error when using multiple brackets in zsh

### ISSUE THREAD

**Issue by CoelacanthusHex** [vim/vim#9263]
### Steps to reproduce

1. write a file contained lines below:
```zsh
$((1+(2+(3))))
```
2. `set filetype=zsh`
3. look at highlight, it will be like this
![图片](https://user-images.githubusercontent.com/43064781/144605362-e3a52d14-76b3-4e9a-bbbb-0e2b93fc3ca6.png)

You also can see it using one command: `echo '$((1+(2+(3))))' | vim -Nu NONE - -c "syntax on | set ft=zsh bt=nofile | colo desert"`

### Expected behaviour

The parentheses are highlighted right.
That is, the first two parentheses and the last two parentheses are rendered in pairs.

### Operating system

Arch Linux rolling

### Version of Vim

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov 28 2021 05:08:35) Included patches: 1-3687

**Comment by CoelacanthusHex** [comment]
@91khr thinks it can be fixed by one line patch.
But she was too shy, so I posted here instead of her.
```patch
From 7a3feacade18aeabcd1ecd5f903a6c98a8b9f821 Mon Sep 17 00:00:00 2001
From: Virginia Senioria <91khr@users.noreply.github.com>
Date: Fri, 3 Dec 2021 19:27:41 +0800
Subject: [PATCH] fix: highlight zsh arithmetic expression parentheses
 correctly

---
 runtime/syntax/zsh.vim | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/runtime/syntax/zsh.vim b/runtime/syntax/zsh.vim
index 819c41922..03a10e469 100644
--- a/runtime/syntax/zsh.vim
+++ b/runtime/syntax/zsh.vim
@@ -365,7 +365,7 @@ syn region  zshGlob             start='(#' end=')'
 syn region  zshMathSubst        matchgroup=zshSubstDelim transparent
                                 \ start='\%(\$\?\)[<=>]\@<!((' skip='\\)' end='))'
                                 \ contains=zshParentheses,@zshSubst,zshNumber,
-                                \ @zshDerefs,zshString keepend fold
+                                \ @zshDerefs,zshString fold
 " The ms=s+1 prevents matching zshBrackets several times on opening brackets
 " (see https://github.com/chrisbra/vim-zsh/issues/21#issuecomment-576330348)
 syn region  zshBrackets         contained transparent start='{'ms=s+1 skip='\\}'
-- 
2.34.1
```

It is git format patch, so you can `git apply` it directly.

**Comment by chrisbra** [comment]
Please move this discussion over to https://github.com/chrisbra/vim-zsh/
