### ISSUE TITLE
One todo item have been fixed

### ISSUE THREAD

**Issue by presuku** [vim/vim#9266]
I think this todo item could be removed from the list, because this has been fixed after [v8.1.2029](https://github.com/vim/vim/commit/017ba07fa2cdc578245618717229444fd50c470d).
https://github.com/vim/vim/blob/04b7b4bf7fe57375bf3c4ed3fd087fc0bb0147ba/runtime/doc/todo.txt#L1473-L1475

I'm not sure why the above todo item was fixed in v8.1.2029, but it was fixed.

v8.1.2028
![v8 1 2028](https://user-images.githubusercontent.com/7233193/144629798-d1469cd6-78fe-46f7-9aa4-5bb97e2c8a73.png)

v8.1.2029 (CursorLine overrides SpecialKey)
![v8 1 2029](https://user-images.githubusercontent.com/7233193/144629825-6db9b15b-99d0-4a73-9f0d-a9c33ced850d.png)

original discussion:
https://groups.google.com/g/vim_dev/c/oYeTcHINrrg

original issue reported at:
vim-jp/issues#67

step to reproduce:
* save as test.vim
```viml
set nocompatible
set nu
set cursorline list listchars=eol:$,tab:>-,trail:~,nbsp:%
syntax on
setf c
colorscheme delek
hi clear SpecialKey
hi SpecialKey guibg=green guifg=blue

call setline(1, "\t/*%")
call setline(2, "\t *~~~~")
call setline(3, "\t */")
call cursor(2, 3)
```
* `./src/vim -g -S test.vim --clean`

**Comment by brammool** [comment]
I'll remove those lines, thanks.

**Comment by presuku** [comment]
It removed at 4700398e384f38f752b432e187462f404b96847d.
Thanks !
