### ISSUE TITLE
Add solidity to language packs

### ISSUE THREAD

**Issue by daweth** [vim/vim#9267]
nuff said

**Comment by brammool** [comment]
Insufficient information.

**Comment by lacygoill** [comment]
I would close the issue.  The issue template is there for a reason.

FWIW, [that's what the maintainer of `fzf.vim` does on his bug tracker](https://github.com/junegunn/fzf.vim/blob/d6aa21476b2854694e6aa7b0941b8992a906c5ec/.github/ISSUE_TEMPLATE.md?plain=1#L1).
