### ISSUE TITLE
too difficult to make modified arrow keys work on non-xterm terminals

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9269]
**Steps to reproduce**

Run this shell command:

    TERM=gnome vim -Nu NONE +'eval "foo bar"->setline(1)'

Press `<C-Right>`: the cursor does not move.

**Expected behavior**

The cursor jumps to the start of the next word (i.e. `bar`), because that's how it's documented to work at [`:help <C-Right>`](https://vimhelp.org/motion.txt.html#<C-Right>).

**Operating system**

Ubuntu 20.04.3 LTS

**Version of Vim**

8.2 Included patches: 1-3731

**Additional Context**

The issue comes from the fact that `<xRight>` is not set when `&term` does not contain the pattern `xterm`.
It is a very common pitfall.  Here is a sample of a few reports (with more time I could gather *much* more):

   - [Control arrow keys don't move word per word when used with alacritty](https://github.com/vim/vim/issues/9254)
   - [Ctrl-Left and Ctrl-Right not jumping words](https://github.com/alacritty/alacritty/issues/5508)
   - [Jumping word by word using control + arrow keys doesn't works in vim](https://github.com/alacritty/alacritty/issues/919)
   - [How to remap ctrl + Left/Right](https://github.com/vim/vim/issues/9059)
   - [Ctrl-Right does not work as expected inside tmux](https://github.com/vim/vim/issues/9009)
   - [How to get vim to work with tmux properly?](https://unix.stackexchange.com/questions/29907/how-to-get-vim-to-work-with-tmux-properly/34723)

The solution is this snippet:

    execute "set <xUp>=\<Esc>[@;*A"
    execute "set <xDown>=\<Esc>[@;*B"
    execute "set <xRight>=\<Esc>[@;*C"
    execute "set <xLeft>=\<Esc>[@;*D"

But it's not easy to discover.  It is only documented at [`:help tmux-integration`](https://vimhelp.org/term.txt.html#tmux-integration), but it is NOT specific to tmux.  Again, it affects Vim whenever `&term` does not match `xterm`.

Ideally, we would automatically set `<xUp>`, `<xDown>`, `<xRight>`, `<xLeft>` for more terminals (e.g. gnome, alacritty).

But if that's not possible, at least we should do a better job at documenting the solution.  What is the first keyword a user is going to look for in the help if `<C-Right>` does not work?  "arrow"
There is no help tag containing the word "arrow" which documents the previously mentioned snippet.  So, how about this patch:
```diff
diff --git a/runtime/doc/term.txt b/runtime/doc/term.txt
index d6f31d379..14b692915 100644
--- a/runtime/doc/term.txt
+++ b/runtime/doc/term.txt
@@ -151,7 +151,7 @@ terminal that tmux is running in): >
         let &t_fe = "\<Esc>[?1004h"
         let &t_fd = "\<Esc>[?1004l"
 
-        " Enable modified arrow keys, see  :help xterm-modifier-keys
+        " Enable modified arrow keys, see  :help modified-arrows
         execute "silent! set <xUp>=\<Esc>[@;*A"
         execute "silent! set <xDown>=\<Esc>[@;*B"
         execute "silent! set <xRight>=\<Esc>[@;*C"
@@ -528,6 +528,16 @@ If your terminal supports both inversion and standout mode, you can see two
 different modes.  If your terminal supports only one of the modes, both will
 look the same.
 
+							*modified-arrows*
+If the terminal is not recognized as being compatible with xterm, some key
+codes are not set, which may prevent you from using modified arrow keys.
+In that case, this snippet may fix the issue: >
+	" see :help xterm-modifier-keys
+	execute "set <xUp>=\<Esc>[@;*A"
+	execute "set <xDown>=\<Esc>[@;*B"
+	execute "set <xRight>=\<Esc>[@;*C"
+	execute "set <xLeft>=\<Esc>[@;*D"
+<
 							*keypad-comma*
 The keypad keys, when they are not mapped, behave like the equivalent normal
 key.  There is one exception: if you have a comma on the keypad instead of a
```

**Comment by lacygoill** [comment]
Actually, we should also add a link to this snippet somewhere around `:help <C-Right>`.  I'll try to send an updated patch later.

**Comment by lacygoill** [comment]
> I'll try to send an updated patch later.
```diff
diff --git a/runtime/doc/motion.txt b/runtime/doc/motion.txt
index b50bd65c5..b98c24e05 100644
--- a/runtime/doc/motion.txt
+++ b/runtime/doc/motion.txt
@@ -386,6 +386,7 @@ w			[count] words forward.  |exclusive| motion.
 
 <C-Right>	or					*<C-Right>* *W*
 W			[count] WORDS forward.  |exclusive| motion.
+			NOTE: If it doesn't work, see |modified-arrows|.
 
 							*e*
 e			Forward to the end of word [count] |inclusive|.
diff --git a/runtime/doc/term.txt b/runtime/doc/term.txt
index d6f31d379..5b8a4285b 100644
--- a/runtime/doc/term.txt
+++ b/runtime/doc/term.txt
@@ -151,11 +151,11 @@ terminal that tmux is running in): >
         let &t_fe = "\<Esc>[?1004h"
         let &t_fd = "\<Esc>[?1004l"
 
-        " Enable modified arrow keys, see  :help xterm-modifier-keys
-        execute "silent! set <xUp>=\<Esc>[@;*A"
-        execute "silent! set <xDown>=\<Esc>[@;*B"
-        execute "silent! set <xRight>=\<Esc>[@;*C"
-        execute "silent! set <xLeft>=\<Esc>[@;*D"
+        " Enable modified arrow keys, see  :help modified-arrows
+        execute "set <xUp>=\<Esc>[@;*A"
+        execute "set <xDown>=\<Esc>[@;*B"
+        execute "set <xRight>=\<Esc>[@;*C"
+        execute "set <xLeft>=\<Esc>[@;*D"
     endif
 <
 							*cs7-problem*
@@ -528,6 +528,16 @@ If your terminal supports both inversion and standout mode, you can see two
 different modes.  If your terminal supports only one of the modes, both will
 look the same.
 
+							*modified-arrows*
+If the terminal is not recognized as being compatible with xterm, some key
+codes are not set, which may prevent you from using modified arrow keys.
+In that case, this snippet may fix the issue: >
+	" see :help xterm-modifier-keys
+	execute "set <xUp>=\<Esc>[@;*A"
+	execute "set <xDown>=\<Esc>[@;*B"
+	execute "set <xRight>=\<Esc>[@;*C"
+	execute "set <xLeft>=\<Esc>[@;*D"
+<
 							*keypad-comma*
 The keypad keys, when they are not mapped, behave like the equivalent normal
 key.  There is one exception: if you have a comma on the keypad instead of a
```

**Comment by lacygoill** [comment]
I had a look at what were the most popular terminals on linux:

   - alacritty
   - gnome-terminal
   - konsole
   - st
   - terminator
   - xfce4-terminal

For all of them, if `TERM` is correctly set to reflect the true identity of the terminal, then `<C-Left>` and `<C-Right>` fail to properly work as documented in Vim's help.  And for all of them, the previous snippet fixes the issue.

**Comment by lacygoill** [comment]
> I had a look at what were the most popular terminals on linux:

urxvt is problematic because `<C-Right>` emits a different kind of sequence.

kitty is also popular, but it should work fine by default, because it sets `TERM` with `xterm-kitty`.  Thanks to the presence of `xterm` in `TERM`, Vim correctly sets `<C-Left>` and `<C-Right>`.

**Comment by brammool** [comment]
Thanks.  I'll include something like this.

The hints are spread out in the help.  If someone is using a specific terminal, it would be nice to have one section to collect information for that terminal.  Thus if you use Konsole, you would find hints in one place (possibly with a number of lines to copy to the vimrc and links to more information).
