### ISSUE TITLE
Using `:file` in `win_execute()` or an autocommand triggered for non-current buffer while `'autochdir'` is enabled leads to wrong current directory

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#9276]
### Steps to reproduce

1. Create three directories `/tmp/a`, `/tmp/b`, `/tmp/c`.
2. Run `vim --clean -o /tmp/a/foo /tmp/b/foo`.
3. `:set autochdir`
3. Make some changes to `/tmp/a/foo`.
4. Press `<C-W>w` to change current buffer to `/tmp/b/foo`.
5. `:autocmd BufWritePost /tmp/a/foo silent file /tmp/c/foo`
6. `:verbose pwd` prints `[autochdir] /tmp/b`.
6. `:wall`
7. `:verbose pwd` prints `[autochdir] /tmp/c`.

### Expected behaviour

`:verbose pwd` prints `[autochdir] /tmp/b` just like before running `:wall`.

### Operating system

Arch Linux

### Version of Vim

8.2.3732

**Comment by zeertzjq** [comment]
I just noticed this problem also exists with `win_execute()`:

1. Create three directories `/tmp/a`, `/tmp/b`, `/tmp/c`.
2. Run `vim --clean -o /tmp/a/foo /tmp/b/foo`.
3. `:set autochdir`
4. `:echo win_getid()` shows the current window's id is `1001`, so the other window's id is `1000`.
5. `:call win execute(1000, 'file /tmp/c/foo')`
6. `:verbose pwd` prints `[autochdir] /tmp/c`.

**Comment by zeertzjq** [comment]
Two solutions I can think of:
1. Make `switch_win_noblock` and `aucmd_prepbuf` set a global flag to inhibit `'autochdir'`.
2. Call `DO_AUTOCHDIR;` in `restore_win_noblock` and `aucmd_restbuf`.

The first solution can make some commands behave inconsistently when invoked in different situations, while the second solution is a bit slower, but doesn't cause inconsistencies.

**Comment by zeertzjq** [comment]
Does this fix the problem with autocommands?

**Comment by brammool** [comment]
The patch fixes the problem when using win_execute(), which was clearly wrong.
The first mentioned problem with an BufWritePost autocommand changing the buffer name, well, I don't really know what you expected from that.  I would say "don't do that"...

**Comment by zeertzjq** [comment]
OK.

**Comment by lacygoill** [comment]
The current working directory changes from `/tmp/b` to `/tmp/c` when `BufWritePost /tmp/a/foo` is fired by `:wall`:
```vim
vim9script
&autochdir = true
mkdir('/tmp/a', 'p')
mkdir('/tmp/b', 'p')
mkdir('/tmp/c', 'p')
silent edit /tmp/b/foo
silent split /tmp/a/foo
'some changes'->setline(1)
var id: number = win_getid()
wincmd w
autocmd BufWritePost /tmp/a/foo win_execute(id, 'file /tmp/c/foo')
def g:Func()
    verbose pwd
    silent wall
    verbose pwd
enddef
feedkeys(":call g:Func()\<CR>")
```
    [autochdir] /tmp/b
    [autochdir] /tmp/c

But it doesn't change when `BufWritePost /tmp/a/foo` is fired by `:doautocmd`:
```vim
vim9script
&autochdir = true
mkdir('/tmp/a', 'p')
mkdir('/tmp/b', 'p')
mkdir('/tmp/c', 'p')
silent edit /tmp/b/foo
silent split /tmp/a/foo
'some changes'->setline(1)
var id: number = win_getid()
wincmd w
autocmd BufWritePost /tmp/a/foo win_execute(id, 'file /tmp/c/foo')
def g:Func()
    verbose pwd
    &eventignore = 'all'
    silent wall
    &eventignore = ''
    doautocmd BufWritePost /tmp/a/foo
    verbose pwd
enddef
feedkeys(":call g:Func()\<CR>")
```
    [autochdir] /tmp/b
    [autochdir] /tmp/b

Why the difference?

**Comment by lacygoill** [comment]
> Why the difference?

Never mind.  That's probably because `:doautocmd` executes the autocmd for the current buffer, while `:wall` fires `BufWritePost` in a different buffer.  Still not sure why the current working directory changes in the first snippet.

**Comment by lacygoill** [comment]
> Still not sure why the current working directory changes in the first snippet.

The only explanation I could see is that the buffer for which the autocmd is run is different than the current one.
But if that was the case, then [`:help BufWritePost`](https://vimhelp.org/autocmd.txt.html#BufWritePost) would include this note:

   > NOTE: When this autocommand is executed, the
   > current buffer "%" may be different from the
   > buffer being written "&lt;afile>".

It does not.  And even if that was the case, I thought using `win_execute()` would avoid the pitfall, but it does not (because the cwd changes in the first snippet).

**Comment by zeertzjq** [comment]
In the first case I think these things happen:
1. `/tmp/a/foo` is written.
2. The current buffer is changed to `/tmp/a/foo` to apply autocommands.
3. `BufWritePost` autocommands are applied: `:file` changes `/tmp/a/foo` to `/tmp/c/foo`, and `'autochdir'` is triggered, so working directory changes from `/tmp/b` to `/tmp/c`.
4. As current buffer is already `/tmp/a/foo` when `win_execute()` is called, running `:file` using `win_execute()` is the same as running `:file` directory.
5. The current buffer is changed back to `/tmp/b/foo`, but working directory is still `/tmp/c/foo`.

**Comment by lacygoill** [comment]
> 2. The current buffer is changed to /tmp/a/foo to apply autocommands.

Ah, that's the missing piece of information which explains everything else.

I guess it means that the effect of `'autochdir'` is suppressed while `:wall` does its job.  The solution would be for it to take effect when `:wall` restores the original buffer in the current window at the end.  And to be consistent, also maybe whenever it temporarily loads a modified buffer in the current window to write it.

**Comment by lacygoill** [comment]
> I guess it means that the effect of 'autochdir' is suppressed while :wall does its job.

Actually no.  If it was suppressed/ignored, then the current working directory would not be changed by `:file`.  It's only ignored whenever `:wall` itself changes the current buffer.

---

If this is not considered as a bug, we might still want to document this pitfall.  As a suggestion, here is a patch:
```diff
diff --git a/runtime/doc/options.txt b/runtime/doc/options.txt
index 73c92122f..5873d36c0 100644
--- a/runtime/doc/options.txt
+++ b/runtime/doc/options.txt
@@ -784,6 +784,11 @@ A jump table for the options with a short description can be found at |Q_op|.
 	It will change to the directory containing the file which was opened
 	or selected.
 	Note: When this option is on some plugins may not work.
+	Note: This option is ignored while `:wall` changes the current buffer
+	to write a modified buffer.  This might cause the current working
+	directory to be unexpectedly changed if you have an autocmd listening
+	to `BufWritePost` which triggers the option.  In that case, use
+	`:noautocmd` before `:wall`.
 
 			*'autoshelldir'* *'asd'* *'noautoshelldir'* *'noasd'*
 'autoshelldir' 'asd'	boolean (default off)
```
---

As a workaround, we can disable all the autocmds with `:noautocmd`:

    noautocmd silent wall
    ^-------^

Test:
```vim
vim9script
&autochdir = true
mkdir('/tmp/a', 'p')
mkdir('/tmp/b', 'p')
mkdir('/tmp/c', 'p')
silent edit /tmp/b/foo
silent split /tmp/a/foo
'some changes'->setline(1)
var id: number = win_getid()
wincmd w
autocmd BufWritePost /tmp/a/foo win_execute(id, 'file /tmp/c/foo')
def g:Func()
    verbose pwd
    noautocmd silent wall
    verbose pwd
enddef
feedkeys(":call g:Func()\<CR>")
```
    [autochdir] /tmp/b
    [autochdir] /tmp/b

**Comment by lacygoill** [comment]
> As a workaround, we can disable all the autocmds with :noautocmd:

Never mind, that's a bad idea.  The user might have another autocmd on `BufWritePost` which they want to run some program like a linter or a formatter.  So let's remove the `:noautocmd` recommendation:
```diff
diff --git a/runtime/doc/options.txt b/runtime/doc/options.txt
index 73c92122f..677dd9600 100644
--- a/runtime/doc/options.txt
+++ b/runtime/doc/options.txt
@@ -784,6 +784,10 @@ A jump table for the options with a short description can be found at |Q_op|.
 	It will change to the directory containing the file which was opened
 	or selected.
 	Note: When this option is on some plugins may not work.
+	Note: This option is ignored while `:wall` changes the current buffer
+	to write a modified buffer.  This might cause the current working
+	directory to be unexpectedly changed if you have an autocmd listening
+	to `BufWritePost` which triggers the option.
 
 			*'autoshelldir'* *'asd'* *'noautoshelldir'* *'noasd'*
 'autoshelldir' 'asd'	boolean (default off)
```

**Comment by zeertzjq** [comment]
I think this behavior applies to many autocommands. If I understand the source code of function `buf_write()` in `bufwrite.c` correctly, it at least applies to:
- FileAppendCmd
- FileAppendPre
- FilterWritePre
- BufWriteCmd
- BufWritePre
- FileWriteCmd
- FileWritePre
- FileAppendPost
- FilterWritePost
- BufWritePost
- FileWritePost

**Comment by Yggdroot** [comment]
The fix for this issue introduce a critical bug which breaks my plugin https://github.com/Yggdroot/LeaderF.
See the issue https://github.com/Yggdroot/LeaderF/issues/864.

I think win_execute() should not change directory.
To reproduce:

bug.vim

```vim
py3 << EOF

import os, vim

vim.command("set acd")
print(os.getcwd())
os.chdir("/tmp")
print(os.getcwd())
vim.command("call win_execute(1000, 'echo')")
print(os.getcwd())

EOF
```

suppose current directory is `/`, source the code, the expected output is
```
/
/tmp
/tmp
```
but actually it is
```
/
/tmp
/
```

**Comment by brammool** [comment]
> The fix for this issue introduce a critical bug which breaks my plugin https://github.com/Yggdroot/LeaderF.
> See the issue https://github.com/Yggdroot/LeaderF/issues/864.
> 
> I think win_execute() should not change directory.
> To reproduce:
> 
> bug.vim
> 
> ```vim
> py3 << EOF
> 
> import os, vim
> 
> vim.command("set acd")
> print(os.getcwd())
> os.chdir("/tmp")
> print(os.getcwd())
> vim.command("call win_execute(1000, 'echo')")
> print(os.getcwd())
> 
> EOF
> ```
> 
> suppose current directory is `/`, source the code, the expected output is
> ```
> /
> /tmp
> /tmp
> ```
> but actually it is
> ```
> /
> /tmp
> /
> ```

So, you set 'autochdir' but change to another directory.
Then win_execute() does not restore that directory but applies
'autochdir'.

I would say that if you use 'autochdir' you can expect some commands to
change to the directory of the file.  But I suppose backwards
compatibility is more important in this case.

-- 
"Microsoft is like Coke.  It's a secret formula, all the money is from
distribution, and their goal is to get Coke everywhere.  Open source is like
selling water.  There are water companies like Perrier and Poland Spring, but
you're competing with something that's free."   -- Carl Howe


 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Yggdroot** [comment]
@brammool I don't understand why `call win_execute(1000, 'echo')` will change the directory, I think the directory should keep unchanged.

**Comment by brammool** [comment]
> @brammool I don't understand why `call win_execute(1000, 'echo')` will
> change the directory, I think the directory should keep unchanged. 

Since 'autochdir' is set, changing windows will apply it and set the
directory depending on the file.  But you will argue that win_execute()
does not actually change windows.

Patch 8.2.3920 changes this.  I hope it didn't break something else.
At least it avoids manipulating the directory when it is not at all
needed, such as when using line().


-- 
I'm writing a book.  I've got the page numbers done.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Yggdroot** [comment]
@brammool confirmed that the issue has been fixed. thanks a lot.
