### ISSUE TITLE
Please recognize `reportbug-*` as ft=mail

### ISSUE THREAD

**Issue by joshtriplett** [vim/vim#928]
Debian's vim configuration includes the following line, which I think
would make sense to incorporate upstream:

``` vim
autocmd BufRead reportbug-* set ft=mail
```

**Comment by brammool** [comment]
Josh Triplett wrote:

> Debian's vim configuration includes the following line, which I think
> would make sense to incorporate upstream:
> 
> ``` vim
> autocmd BufRead reportbug-* set ft=mail
> ```

I can add this to filetype.vim:

au BufNewFile,BufRead reportbug-\*       call s:StarSetf('mail')

## 

I'd like to meet the man who invented sex and see what he's working on now.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by joshtriplett** [comment]
@brammool That seems reasonable (though the BufNewFile case should never happen).  Please do.
