### ISSUE TITLE
crash when setting 'tagfunc' via `:set` then `:let`

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9290]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        set tagfunc=function('TagFunc')
        let &tagfunc = function('TagFunc')
        tag name
    EOF
    )

Vim crashes.

**Expected behavior**

Vim doesn't crash.

**Operating system**

Ubuntu 20.04.3 LTS

**Version of Vim**

8.2 Included patches: 1-3754

**Logs and stack traces**

Regression introduced in [8.2.3665](https://github.com/vim/vim/releases/tag/v8.2.3665).

---

According to ubsan, there is a runtime error on line 26 in `src/strings.c`:

    strings.c:26:11: runtime error: null pointer passed as argument 1, which is declared to never be null

That should be this line:

    len = STRLEN(string) + 1;
                 ^----^
                 null pointer which is declared to never be null

---

Backtrace:

    Starting program: /home/lgc/Vcs/vim/src/vim -Nu NONE -S /tmp/crash.vim
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

    Program received signal SIGSEGV, Segmentation fault.
    __strlen_sse2 () at ../sysdeps/x86_64/multiarch/../strlen.S:120
    120	../sysdeps/x86_64/multiarch/../strlen.S: No such file or directory.
    #0  __strlen_sse2 () at ../sysdeps/x86_64/multiarch/../strlen.S:120
    #1  0x00005555557a1605 in vim_strsave (string=0x0) at strings.c:26
    #2  0x00005555557fc1c1 in call_func
        (funcname=0x0, len=0, rettv=0x7fffffff96e0, argcount_in=3, argvars_in=0x7fffffff9700, funcexe=0x7fffffff95c0)
        at userfunc.c:3275
    #3  0x00005555557fbef3 in call_callback
        (callback=0x55555597f538, len=0, rettv=0x7fffffff96e0, argcount=3, argvars=0x7fffffff9700) at userfunc.c:3166
    #4  0x00005555557b798a in find_tagfunc_tags
        (pat=0x555555981f60 "name", ga=0x7fffffff9a90, match_count=0x7fffffff9798, flags=40, buf_ffname=0x0) at tag.c:1393
    #5  0x00005555557b86dc in find_tags
        (pat=0x555555981f60 "name", num_matches=0x7fffffffb200, matchesp=0x7fffffffb260, flags=40, mincount=2147483647, buf_ffname=0x0) at tag.c:1815
    #6  0x00005555557b5b08 in do_tag (tag=0x5555559e00f4 "name", type=1, count=1, forceit=0, verbose=1) at tag.c:610
    #7  0x0000555555636031 in ex_tag_cmd (eap=0x7fffffffb4a0, name=0x5555558a9b28 "tag") at ex_docmd.c:8830
    #8  0x0000555555635f1a in ex_tag (eap=0x7fffffffb4a0) at ex_docmd.c:8781
    #9  0x0000555555629df2 in do_one_cmd (cmdlinep=0x7fffffffb6d0, flags=7, cstack=0x7fffffffb7b0, fgetline=
        0x555555765a4b <getsourceline>, cookie=0x7fffffffbf00) at ex_docmd.c:2578
    #10 0x000055555562702b in do_cmdline (cmdline=0x55555596feb0 "set tagfunc=function('TagFunc')", fgetline=
        0x555555765a4b <getsourceline>, cookie=0x7fffffffbf00, flags=7) at ex_docmd.c:1000
    #11 0x0000555555765043 in do_source (fname=0x555555983b43 "/tmp/crash.vim", check_other=0, is_vimrc=0, ret_sid=0x0)
        at scriptfile.c:1420
    #12 0x000055555576428d in cmd_source (fname=0x555555983b43 "/tmp/crash.vim", eap=0x7fffffffc070) at scriptfile.c:985
    #13 0x000055555576436b in ex_source (eap=0x7fffffffc070) at scriptfile.c:1011
    #14 0x0000555555629df2 in do_one_cmd (cmdlinep=0x7fffffffc2a0, flags=11, cstack=0x7fffffffc380, fgetline=
        0x0, cookie=0x0) at ex_docmd.c:2578
    #15 0x000055555562702b in do_cmdline (cmdline=0x555555982a00 "so /tmp/crash.vim", fgetline=0x0, cookie=0x0, flags=11)
        at ex_docmd.c:1000
    #16 0x00005555556264b6 in do_cmdline_cmd (cmd=0x555555982a00 "so /tmp/crash.vim") at ex_docmd.c:594
    #17 0x0000555555897f8f in exe_commands (parmp=0x555555961d60 <params>) at main.c:3080
    #18 0x0000555555894806 in vim_main2 () at main.c:774
    #19 0x00005555558940c5 in main (argc=5, argv=0x7fffffffcb88) at main.c:426

---

cc @yegappan via https://github.com/vim/vim/pull/9204

**Comment by brammool** [comment]
Patch 8.2.3756 should fix this.
