### ISSUE TITLE
`timer_info()->repeat` is off by one

### ISSUE THREAD

**Issue by noscript** [vim/vim#9294]
### Steps to reproduce

1. Run
```sh
vim -g --clean +'call timer_start(1000, {tid -> execute("echom timer_info(tid)[0].repeat", "")}, #{repeat: 3})'
```
Prints
```
3
2
1
```

### Expected behaviour

Prints
```
2
1
0
```

### Operating system

Debian 11

### Version of Vim

8.2.3733

**Comment by chrisbra** [comment]
I believe it is not off by one, but simply decremented after the timer callback has been triggered. 

https://github.com/vim/vim/blob/f7f7aaf8aaad34a38d3f159e031c5bcf3394f8f1/src/time.c#L548-L584

Is this a problem?

**Comment by noscript** [comment]
I think it should be decremented before the callback. Otherwise this contradicts the documentation and is counter-intuitive.
