### ISSUE TITLE
where the privacy policy page ?

### ISSUE THREAD

**Issue by ys-oo** [vim/vim#9299]
I would ask about vim and privacy, does :
1.vim connect to wifi or have any online connection
2.vim have tracking or something like bug report
3.is vim privacy friendly.

Thank you for your response and for your hard work ☺️

**Comment by habamax** [comment]
1. no
2. no
3. define "privacy friendly". Vim has plugins...

**Comment by ys-oo** [comment]
Ok very nice , so what the tips that i should follow to protect my privacy in VIM should i stop using plugins or what sbould i do ?

**Comment by habamax** [comment]
> Ok very nice , so what the tips that i should follow to protect my privacy in VIM should i stop using plugins or what sbould i do ?

Define "to protect my privacy", otherwise it is too vague.

PS, I think this discussion is better to route to vim-use maillist or vi.stackexchange.com.

**Comment by chrisbra** [comment]
Let's close it here, it's off topic.
