### ISSUE TITLE
Closing quickfix window unlist the buffer even if it is still visible in a different tab

### ISSUE THREAD

**Issue by eight04** [vim/vim#9300]
### Steps to reproduce

1. Open a tab, run `:copen`.
2. Run `:set buflisted?`
2. Open the second tab, run `:copen`.
3. Run `:cclose`.
4. Switch to the first tab, run `:set buflisted?`.

### Expected behaviour

Since the quickfix window is always visible in the first tab, it should probably print `buflisted` twice.

Currently, it prints `buflisted` and `nobuflisted`.

### Operating system

Windows 10 x64

### Version of Vim

CMD / VIM 8.2 (2019 Dec 12, compiled Nov  4 2021 23:03:47)

**Comment by lacygoill** [comment]
MWE:

    vim -Nu NONE -S <(cat <<'EOF'
        copen
        tabnew
        copen
        cclose
        tabfirst
        ls
    EOF
    )

Expected:

    1 #a   "[No Name]"                    line 1
    2u%a-  "[Quickfix List]"              line 1
    3  a   "[No Name]"                    line 0

Actual:

    1 #a   "[No Name]"                    line 1
    3  a   "[No Name]"                    line 0

**Comment by lacygoill** [comment]
Regression introduced in [8.1.1015](https://github.com/vim/vim/releases/tag/v8.1.1015).

cc @yegappan via https://github.com/vim/vim/pull/4113
