### ISSUE TITLE
tabnext doesn't update message line

### ISSUE THREAD

**Issue by Keith-S-Thompson** [vim/vim#9305]
### Steps to reproduce

```
echo ONE > 1.txt
echo TWO > 2.txt
vim -p 1.txt 2.txt
```
vim now shows the contents of 1.txt with the message line showing
```
 "1.txt" 1L, 4B ...
```

Now type `:nexttab` (or `gt`) to go to the second tab. Now the message line still shows information for `1.txt`, though we're now viewing `2.txt`.

There's a similar issue with `vim -o` and `vim -O` except that the message line shows information for the last file rather than the first.

By contrast, if you run `vim 1.txt 2.txt`, the `:next` command update the message line to show information about the current file.

### Expected behaviour

If you navigate to a new buffer, whether it's a tab, a window, or something else, the message line should be updated to show information about the new current file being edited.

### Operating system

Ubuntu 20.04.3

### Version of Vim

xterm, vim 8.2.3570

**Comment by brammool** [comment]
This is working as intended.  The message is just the last thing that happened, it is not a buffer title or status.
If you don't like it you could use a TabLeave autocommand to display an empty string.

**Comment by Keith-S-Thompson** [comment]
I still think that visiting a new tab via `:tabnext` should behave more similarly to visiting a new file via `:next`, but thanks to your hint I can make it do so, so I'm content to leave this as closed.

I've added this to my `.vimrc`:
```
autocmd TabEnter * file
autocmd WinEnter * file
```

**Comment by brammool** [comment]
> I still think that visiting a new tab via `:tabnext` should behave more similarly to visiting a new file via `:next`, but thanks to your hint I can make it do so, so I'm content to leave this as closed.
> 
> I've added this to my `.vimrc`:
> ```
> autocmd TabEnter * file
> autocmd WinEnter * file
> ```

The message comes from loading the file into the buffer.  :tabnext
doesn't do that, it only displays another tab, the buffer was already
loaded.

-- 
How To Keep A Healthy Level Of Insanity:
5. Put decaf in the coffee maker for 3 weeks. Once everyone has gotten
   over their caffeine addictions, switch to espresso.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
