### ISSUE TITLE
should we prevent Vim from squashing current window?

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9307]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        new
        &winminheight = 0
        win_execute(win_getid(2), 'wincmd _')
    EOF
    )

The current window is squashed to 0 lines.  The cursor is printed in the status line.

**Expected behavior**

The current window still has 1 line, so that we can still see where our cursor is, and read what we're typing.

**Operating system**

Ubuntu 20.04.3 LTS

**Version of Vim**

8.2 Included patches: 1-3761

**Additional Context**

Technically, I don't think it's a bug.  Vim does exactly what it's told to do.  Still, it leads to a confusing situation.  Should we prevent Vim from ending in a situation where the user can't even read what they are inserting in the current buffer?

**Comment by lacygoill** [comment]
> Still, it leads to a confusing situation.

 Gif to illustrate:

 ![gif](https://user-images.githubusercontent.com/8505073/145357345-bbcd11a3-7ff3-4667-9dfd-f52e411ee0be.gif)

 When we insert text, notice how the cursor seems to move in the buffer of the bottom window.  In reality, it's still in the buffer of the first one.  And we can't read all the text that we're inserting in the latter.

**Comment by lacygoill** [comment]
Just to be clear: I'm not asking to disallow squashing any window.  Only the current window.  Squashing an unfocused window is OK.  There are users who like [Rolodex Vim](https://vim.fandom.com/wiki/Window_zooming_convenience).

**Comment by lacygoill** [comment]
> Technically, I don't think it's a bug. Vim does exactly what it's told to do.

 Actually, one could argue that it *is* a bug, because Vim ignores `'winheight'` which must be set to a positive number.  Which means that the current window should always have at least 1 line.  Unless, it is intended for `'winminheight'` to be able to have priority over `'winheight'`.  From the documentation, it's not clear to me whether that's the case.

**Comment by lacygoill** [comment]
Same issue with `'winminwidth'`:
```vim
vim9script
vertical new
&winminwidth = 0
win_execute(win_getid(2), 'wincmd |')
```

**Comment by lacygoill** [comment]
`win_execute()` is an easy way to reproduce the issue.  But it can be reproduced in other ways.  For example, with a `BufReadPost` autocmd.

Run this shell command in one terminal window:

    vim -Nu <(cat <<'EOF'
        vim9script
        &t_fe = "\<Esc>[?1004h"
        &t_fd = "\<Esc>[?1004l"
        execute "set <FocusGained>=\<Esc>[I"
        execute "set <FocusLost>=\<Esc>[O"
        &autoread = true
        &winminheight = 0
        autocmd BufReadPost * wincmd _
        autocmd SwapExists * v:swapchoice = 'e'
        silent edit /tmp/file
        new
        wincmd _
    EOF
    )

Run this other shell command in another terminal window:

    vim -Nu NONE --cmd 'autocmd SwapExists * let v:swapchoice = "e"' /tmp/file

Then, execute the `:write` Ex command in this second Vim instance.
Finally, focus back the first terminal window.

Notice how – again – the current window is squashed to 0 lines.

**Comment by brammool** [comment]
If the user (or some script) intentionally makes the window have no line or no column, it should be OK to leave it like that.
But we could enforce at least one line and column when typing.  Then plugins that temporarily change the window layout will still work as before.
