### ISSUE TITLE
display issue when using -p command line option with modeline that sets columns option

### ISSUE THREAD

**Issue by ghost** [vim/vim#9315]
### Steps to reproduce

1.  Create  two files with modelines, e.g.,
         echo "vim: columns=81" > tab1.noft
         echo "vim: columns=81" > tab2.noft
    The file extension was chosen solely to avoid any modifications caused by Vim-supported filetype processing.
2.  Run gVim:
         gvim --clean -N -p tab1.noft tab2.noft

As expected both tabpage windows are 81 characters wide.  However, the tab2.noft window displays a vertical bar character in column 80 as if it were a split window.  This is the bug.  

I spot-checked a few other values of 'columns'.  This also happens when 'columns' is set to other values greater 80 but does not happen if set to something less then 80.  

### Expected behaviour

I didn't expect to see the vertical bar character in the tab2.noft window.  

That character is not seen if the tab2.noft is instead loaded using ":tabnew":
  1.  gvim --clean -N tab1.noft
  2. :tabnew tab2.noft

### Operating system

Windows 10

### Version of Vim

8.2.3761 with normal features, mingw build

**Comment by brammool** [comment]
I could not consistently reproduce the problem, it appears it depends on timing, probably a GUI callback for the window size change.  Therefore I didn't add a test.

**Comment by msoyka-of-wharton** [comment]
Your patch has fixed the problem.  Thank you.
