### ISSUE TITLE
Support inlay hint

### ISSUE THREAD

**Issue by hungpham3112** [vim/vim#9316]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
I use vim for Rust but just neovim support inlay hint, I also want vim support it

**Comment by puremourning** [comment]
Duplicate, again ? https://github.com/vim/vim/issues/9155 / https://github.com/vim/vim/issues/7553 ?

**Comment by chrisbra** [comment]
ok, closing then as duplicate

**Comment by HungPham3112** [comment]
Sorry
