### ISSUE TITLE
noesckeys has no effect in 8.1

### ISSUE THREAD

**Issue by hvanness** [vim/vim#9317]
### Steps to reproduce

1. set noesckeys
2. In insert mode, type esc then O
There's a delay.

### Expected behaviour

I expect to go into normal mode then insert mode in a new line above, without waiting.

### Operating system

Debian Stretch

### Version of Vim

8.1

**Comment by lacygoill** [comment]
I can't reproduce.  I made several tests on master and on 8.1.0001:

                     vim -Nu NONE +'set noesckeys'
          TERM=gnome vim -Nu NONE +'set noesckeys'
               ./src/vim -Nu NONE +'set noesckeys'
    TERM=gnome ./src/vim -Nu NONE +'set noesckeys'
                     vim --clean  +'set noesckeys'
          TERM=gnome vim --clean  +'set noesckeys'
               ./src/vim --clean  +'set noesckeys'
    TERM=gnome ./src/vim --clean  +'set noesckeys'

In all cases, pressing `<Esc>` in insert mode immediately switches from insert mode to normal mode.

---

What's the name of your terminal?
What's the output of `echo $TERM` in your shell?
What's the output of `:echo &term` in Vim?
What's your exact Vim version, up to the number of the minor patch (e.g. 8.1.1234)?

Try to reproduce without config:

    vim -Nu NONE +'set noesckeys'

If you need some config to reproduce, then reduce it as much as you can until you get a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example), and post it here.

   > Version of Vim
   >
   > 8.1

[8.1 is 3 and a half years old](https://github.com/vim/vim/releases/tag/v8.1.0001).  Try to reproduce on master.  In particular, make sure you have the patch [8.1.2261](https://github.com/vim/vim/releases/tag/v8.1.2261) which fixed [an issue](https://github.com/vim/vim/issues/5180) related to `'esckeys'` a few years ago.

**Comment by brammool** [comment]
Version 8.1 is quite old.  Please use a much more recent build.
Make sure you start with "vim -u NONE" or "vim --clean", various startup scripts may influence what happens.

**Comment by hvanness** [comment]
I think this is a Debian 10 (oldstable) problem, but thanks for looking into this, I've been a passionite vim user for over a decade and this has been bugging me.

Note that the issue is with uppercase O (Begin a new line above the cursor.)

```
$ vim --version
...
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 15 2019 16:41:15)
Included patches: 1-875, 878, 884, 948, 1046, 1365-1368, 1382, 1401
...

```
```
$ sudo apt install vim
...
vim is already the newest version (2:8.1.0875-5)."
...

```
`vim -Nu NONE +'set noesckeys'
`

O still has delay.

Isn't it reasonable to expect Debian devs to apply patch 8.1.2261 to vim 8.1? I think it may only have been applied to vim 8.2.

**Comment by lacygoill** [comment]
What's the name of your terminal?
What's the output of echo $TERM in your shell?

**Comment by hvanness** [comment]
> `:set timeout timeoutlen=3000 ttimeoutlen=100`

That resolves the issue, thanks :) I'd still like to help resolve this for other Debian 10 Terminator users.


> What's the name of your terminal?

terminator 1.91

> What's the output of echo $TERM in your shell?
```
$ echo $TERM
xterm-256color
```


Amazingly I'm not getting the issue in "real" TTYs:
```
$ echo $TERM
linux
```

**Comment by lacygoill** [comment]
> I'd still like to help resolve this for other Debian 10 Terminator users.

The way to fix the issue is to set the `'ttimeoutlen'` option.  Its default value is `-1` which means that it copies the value of `'timeoutlen'`.  The default value for the latter is `1000`, which is probably why you experienced a timeout.

If you don't have a vimrc, Vim should use `$VIMRUNTIME/defaults.vim`, which [does set `'ttimeoutlen'`](https://github.com/vim/vim/blob/6ecf58b0d7d9b8fbba780d19d2e6c0f227df715b/runtime/defaults.vim#L44).  If you do have a vimrc, and you don't set `'ttimeoutlen'` in there, then the option keeps its original value `-1`.

You can see which scripts Vim has sourced by executing [`:scriptnames`](https://vimhelp.org/repeat.txt.html#%3Ascriptnames).

---

   > Amazingly I'm not getting the issue in "real" TTYs:

That's because the linux terminal has no capability starting with `<Esc>O`:

    $ infocmp -1x linux | grep -i '\\EO'

Contrary to the xterm-256color terminal:

    $ infocmp -1x xterm-256color | grep -i '\\EO'
    ka1=\EOw,
    ka3=\EOy,
    kb2=\EOu,
    kc1=\EOq,
    kc3=\EOs,
    kcub1=\EOD,
    kcud1=\EOB,
    kcuf1=\EOC,
    kcuu1=\EOA,
    kend=\EOF,
    kent=\EOM,
    kf1=\EOP,
    kf2=\EOQ,
    kf3=\EOR,
    kf4=\EOS,
    khome=\EOH,
    ka2=\EOx,
    kb1=\EOt,
    kb3=\EOv,
    kc2=\EOr,
    kp5=\EOE,
    kpADD=\EOk,
    kpCMA=\EOl,
    kpDIV=\EOo,
    kpDOT=\EOn,
    kpMUL=\EOj,
    kpSUB=\EOm,
    kpZRO=\EOp,
