### ISSUE TITLE
Executing `:normal` inside a function erases forced-motion information from `mode(1)` starting from patch 8.2.2938

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#9332]
### Steps to reproduce

1. Run Vim and source the following file:
```vim
fun! DownByOne()
    echomsg mode(1)
    norm! j
    echomsg mode(1)
endfun
onoremap z :call DownByOne()<cr>
```
2. Press `y<C-V>z`
3. Prints:
```
no^V
no
```

### Expected behaviour

Prints like before patch 8.2.2938:
```
no^V
no^V
```

### Operating system

Arch Linux

### Version of Vim

v8.2.3582

**Comment by zeertzjq** [comment]
A step was missing from my steps to reproduce above. It is "Press `y<C-V>z`".

**Comment by zeertzjq** [comment]
Also it is not `vim -u`. It is "Run Vim and source the following file".

**Comment by lacygoill** [comment]
I don't think it's a bug.  But it's a common pitfall; `:normal` resets various variables:
```vim
vim9script
def g:DownByOne()
    echomsg v:count
    normal! j
    echomsg v:count
enddef
onoremap z <Cmd>call DownByOne()<CR>
feedkeys('3yz')
```
    3
    0
```vim
vim9script
def g:DownByOne()
    echomsg v:register
    normal! j
    echomsg v:register
enddef
onoremap z <Cmd>call DownByOne()<CR>
feedkeys('"ayz')
```
    a
    "

Now, it also resets the motion force flag given by `mode(1)`.  The change was introduced to fix the issue https://github.com/vim/vim/issues/8323.  The latter was about `feedkeys()` (which – when passed the `x` flag – is mostly equivalent to `:normal`).

The usual way to deal with this is to save anything you need at the start of the function in your own variables:
```vim
vim9script
def g:DownByOne()
    var count_save = v:count
    echomsg count_save
    normal! j
    echomsg count_save
enddef
onoremap z <Cmd>call DownByOne()<CR>
feedkeys('3yz')
```
    3
    3
```vim
vim9script
def g:DownByOne()
    var register_save = v:register
    echomsg register_save
    normal! j
    echomsg register_save
enddef
onoremap z <Cmd>call DownByOne()<CR>
feedkeys('"ayz')
```
    a
    a

**Comment by zeertzjq** [comment]
With the other two examples I think this indeed makes sense, but I'll wait for Bram to comment on this.

**Comment by brammool** [comment]
I think the current behavior is OK.  You can argue that using feedkeys() and :normal should not change the state (register, count, Visual mode), but on the other hand these commands are also intentionally used to change the state.  Since you can capture the state before invoking :normal or calling feedkeys() you can make it work.  If we would restore the state then it would be impossible to change it.
