### ISSUE TITLE
Issue cross-compiling Vim on MacOS

### ISSUE THREAD

**Issue by BGR360** [vim/vim#9338]
I'm trying to use MacOS to cross-compile Vim for another platform (specifically, [SerenityOS](https://github.com/SerenityOS/serenity)).

It seems even with `--disable-darwin`, the configure script is setting `MACOS_X=yes`, which is causing compilation to fail because my target compiler doesn't recognize the various MacOS-specific definitions:

```
fileio.c: In function 'vim_fsync':
fileio.c:2940:19: error: 'F_FULLFSYNC' undeclared (first use in this function)
 2940 |     r = fcntl(fd, F_FULLFSYNC);
      |                   ^~~~~~~~~~~
```

Is there another option available in the configure script that will allow me to properly spoof the target platform so I can cross-compile?

**Comment by BGR360** [comment]
My current workaround is to just entirely skip this if clause:

https://github.com/vim/vim/blob/ef082e12df2cafe177b2ac9f6922393223ccf83b/src/configure.ac#L182-L185

That definitely doesn't seem like the Correct thing to do, but :shrug:

**Comment by brammool** [comment]
I'm not familiar with cross-compiling.  Perhaps we should allow setting the output of "uname"?  When not set then the actual output of uname would be used.

**Comment by BGR360** [comment]
That sounds like it could work. I'm also not that familiar with how other projects allow for cross-compilation. Maybe there's inspiration to be gathered from elsewhere, like ncurses for instance
