### ISSUE TITLE
GVim: popup_menu() callback's result arg won't show

### ISSUE THREAD

**Issue by elig0n** [vim/vim#9343]
### Steps to reproduce

1. executing the following command and selecting some menu entry

    :call popup_menu(['test1', 'test2'], #{callback: {id,result -> echoraw(result)} })

  gvim will not show the value of `result` while terminal vim would.

2. `id` would show up alright though:

    :call popup_menu(['test1', 'test2'], #{callback: {id,result -> echoraw(id)} })

Confirmed with two other people.

### Expected behaviour

dump the correct value of `result`

### Version of Vim

GVim 8.2 (2019 Dec 12, compiled Aug 31 2020 09:46:07) Included patches: 1-1551 Compiled by tux0r@ROSAELEFANTC33A

### Environment

Windows 10
Gvim

**Comment by brammool** [comment]
echoraw() writes the output wherever the cursor happens to be, which is undefined here.
If you want to show the result on the command line use execute('echomsg' .. result, '')

**Comment by lacygoill** [comment]
That's not a bug.  The purpose of [`echoraw()`](https://vimhelp.org/eval.txt.html#echoraw%28%29) is not to print something on the screen, but to use the terminal capabilities by sending a [special sequence](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html) (typically starting with OSC or CSI).

Although, maybe the current help can be misunderstood:

   > This can be used to output a terminal code.

Maybe the OP thought that the result of the popup menu callback was some kind of "terminal code".  To be less ambiguous, maybe we should say "terminal capability":
```diff
diff --git a/runtime/doc/eval.txt b/runtime/doc/eval.txt
index 004f9d4bb..bfbe1c368 100644
--- a/runtime/doc/eval.txt
+++ b/runtime/doc/eval.txt
@@ -4384,7 +4384,7 @@ digraph_setlist({digraphlist})				*digraph_setlist()*
 
 echoraw({string})					*echoraw()*
 		Output {string} as-is, including unprintable characters.
-		This can be used to output a terminal code. For example, to
+		This lets you use the terminal capabilities. For example, to
 		disable modifyOtherKeys: >
 			call echoraw(&t_TE)
 <		and to enable it again: >
```

**Comment by elig0n** [comment]
> echoraw() writes the output wherever the cursor happens to be, which is undefined here.

Then why does `id`'s value gets echoed at the cursor while `result` isn't ?

> If you want to show the result on the command line use execute('echomsg' .. result, '')

Thanks

**Comment by lacygoill** [comment]
> Then why does id's value gets echoed at the cursor while result isn't ?

It doesn't matter, because this behavior is not documented.

There are various parameters which influence the effect, including `'lazyredraw'`.  You say that `result` is not echo'ed, but I can see it.  It's just cleared by a redraw.

To avoid any confusion, maybe `echoraw()` should automatically clear the screen?

**Comment by lacygoill** [comment]
> You say that result is not echo'ed, but I can see it. It's just cleared by a redraw.

You *might* be able to see it too by temporarily increasing the value of [`'writedelay'`](https://vimhelp.org/options.txt.html#%27writedelay%27).
