### ISSUE TITLE
Number and Relativenumber Randomly Don't Set with Help Filetype

### ISSUE THREAD

**Issue by Dosx001** [vim/vim#9345]
### Steps to reproduce

I have the following inside my vimrc to turn on number and relativenumber, and turn off signcolumn when opening Vim documentation.
```vim
augroup doc
    au!
    au FileType help setlocal number relativenumber signcolumn=no
augroup END
```
When you open Vim for the first time and you open the manual like ```:tab h  tag```, number and relativenumber will work. After opening another instance for Help type file number and relativenumber will sometimes not work. However, signcolumn=no always works.

### Expected behaviour

For Vim to set number and relativenumber every time I open a Help filetype.

Rant:
I don't understand why if a user sets both number and releativenumber inside their vimrc, why don't those settings transfer over when opening a Help file type. Every other setting seems to transfer over but not number or relativenumber.

### Version of Vim

8.2.3582 

### Environment

WSL Arch Linux
Windows Terminal 1.11.2921.0
xterm-256color
zsh 5.8 (x86_64-pc-linux-gnu)

**Comment by lacygoill** [comment]
Try this autocmd:
```vim
augroup doc
   autocmd!
   autocmd FileType help autocmd BufWinEnter <buffer=abuf> setlocal number relativenumber signcolumn=no
augroup END
```
---

   > I don't understand why if a user sets both number and releativenumber inside their vimrc, why don't those settings transfer over when opening a Help file type.

Because:

   - [`'number'`](https://vimhelp.org/options.txt.html#%27number%27) and [`'relativenumber'`](https://vimhelp.org/options.txt.html#%27relativenumber%27) are window-local options
   - Vim tries to do what the user expects
   - doing what the user expects is complex for window-local options

For more info, see [`:help local-options`](https://vimhelp.org/options.txt.html#local-options).

**Comment by Dosx001** [comment]
@lacygoill thank you! This solved my issue. I will check out ```local-options``` later. Thanks again.

**Comment by brammool** [comment]
That options are set/reset in a help window is documented in helphelp.txt
Let me add a tag there to jump to.
