### ISSUE TITLE
`r` doesn't remove composing characters in Visual mode

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#9351]
### Steps to reproduce

1. Run `vim --clean`
2. Insert `ã̳` and go to Normal mode
3. Press `0vrb`
4. Buffer content becomes `b̳̃`: unlike `r` in Normal mode, composing characters are not removed

### Expected behaviour

Composing characters are removed like `r` in Normal mode

### Version of Vim

8.2.3811

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of `$TERM`: `xterm-kitty`
Shell: fish 3.3.1

**Comment by zeertzjq** [comment]
Maybe this behavior can be sometimes useful, so I'm not sure whether it should be changed. If it should not be changed, I think it should be documented.

**Comment by brammool** [comment]
No, this is not intentional.  "r" and "vr" should do the same thing.
