### ISSUE TITLE
getchar() in a mapping returns 27 when executed with :normal

### ISSUE THREAD

**Issue by dstein64** [vim/vim#9356]
### Steps to reproduce

```vim
:noremap X :<c-u>echo getchar()<cr>
```

Use the mapping by pressing `X`, followed by e.g., pressing `a`.

Use the mapping by running `:normal X`.

### Expected behaviour

When pressing `X`, followed by `a`, Vim outputs 97, the ASCII code for `a`.

When running `:normal X`, there is no opportunity to enter a character. Rather, the call to `getchar()` immediately returns 27, the code for `<esc>`, which is output by the call to `echo`.

I expected that the usage of `:normal X` would have matched the behavior of pressing `X`.

### Version of Vim

Vim 8.2.3700

### Environment

OS: macOS 12.0.1
Terminal: Terminal.app 2.12
$TERM: xterm-256color
Shell: bash 5.1.12

**Comment by chrisbra** [comment]
I think this is expected. For `:norm` you always have to feed the complete characters to be handled, when the "input" ends, it receives an `Escape`. For similar reasons `:norm! A` doesn't keep you in Insert mode. If you need more sophisticated input handling, you can make use of `feedkeys()`

**Comment by lacygoill** [comment]
Yes, it's a common pitfall.

The behavior is documented at [`:help :normal`](https://vimhelp.org/various.txt.html#%3Anormal):

   > {commands} should be a complete command.  If
   > {commands} does not finish a command, the last one
   > will be aborted as if &lt;Esc> or &lt;C-C> was typed.

In your example, `:echo getchar()` is not a complete command.  It needs some input from the user to finish.  `:normal` doesn't like that, so it presses `<Esc>` to finish the command.  See also [my notes on this](https://github.com/lacygoill/wiki/blob/master/vim/mapping.md#my-mapping-invokes-a-command-which-requires-some-user-input--it-doesnt-ask-for-my-input).

The usual workaround is to use `feedkeys()`:

    ✘
    :normal X

    ✔
    :call feedkeys('X')
