### ISSUE TITLE
confusing error for using s: scope when setting '*func' option

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9358]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE +'set operatorfunc=s:Func'

No error is given.

**Expected behavior**

An error is given.  Maybe this one which currently exists:

    E120: Using <SID> not in a script context: s:Func

Or this new one:

    E1234: Cannot use 's:' scope to set '*func' option

**Version of Vim**

8.2 Included patches: 1-3823

**Environment**

Operating system: Ubuntu 20.04.3 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: zsh 5.8

**Additional Context**

Vim is perfectly able to reject a number:

    vim -Nu NONE +'set operatorfunc=123'

    E921: Invalid callback argument
    E474: Invalid argument: operatorfunc=123

Which means that there is already some kind of sanitization in place.  Could we extend this mechanism to reject an `s:` prefix?  If we don't, an error will *necessarily* be given later:
```vim
vim9script
def s:Opfunc()
enddef
set operatorfunc=s:Opfunc
feedkeys('g@_')
```
    E120: Using <SID> not in a script context: s:Opfunc

The problem is that it's a confusing error, because there is no line number, and `s:Opfunc` is written in 2 different locations:  in `:set` and in the function's header.

Yes, here, it's obvious that the issue comes from `:set`.  But in a real example, it's not always obvious.

Besides, there is no `<SID>` in our code, so it looks weird for the message to mention it.  To make things worse, in a real example, we probably have a `<SID>` somewhere in a mapping:

    nnoremap <expr> <F3> <SID>Opfunc()
                         ^---^

But this one is irrelevant, which might add to the confusion.

It would be less confusing if an error was given as soon as possible; that is, right when the option is set, and not at an arbitrary later time, when the opfunc is finally used, and the option is finally read.

---

It would be even better if we could assert the validity of a function name.  Right now, Vim accepts anything:

    vim -Nu NONE +'set operatorfunc=!$%&()*+,-./:;<=>?@[]^\\`{}~' +'echo &operatorfunc'
    !$%&()*+,-./:;<=>?@[]^\`{}~

A function name should probably match one of these regexes:

    g:\w\+
    \u\w*
    \h\w*#\%(\w\|#\)*

**Comment by lacygoill** [comment]
> A function name should probably match one of these regexes:

Actually, matching a valid function name might be too complex.  For example, we would have to handle dictionary functions.

But at least, we could reject `s:`.

**Comment by lacygoill** [comment]
> But at least, we could reject s:.

The main benefit is that it would give us a line number.  We would no longer have to guess where the error is really coming from.

**Comment by lacygoill** [comment]
At least, we could document the pitfall and give a workaround:
```diff
diff --git a/runtime/doc/options.txt b/runtime/doc/options.txt
index a5ff937e0..9e6b39c16 100644
--- a/runtime/doc/options.txt
+++ b/runtime/doc/options.txt
@@ -392,6 +392,12 @@ lambda it will be converted to the name, e.g. "<lambda>123".  Examples:
 	let L = {a, b, c -> MyTagFunc(a, b, c)}
 	let &tagfunc = L
 
+If the value is the name of a script-local function, it cannot start with "s:",
+because it's not used in the context of the script where the option is set.
+In that case, use a funcref: >
+	set opfunc=s:MyOpFunc " ERROR
+	let &opfunc = function('s:MyOpFunc') " OK
+
 In Vim9 script, in a compiled function, you can use a lambda, but a
 closured does not work, because the function will be called without the
 context of where it was defined.
```

**Comment by lacygoill** [comment]
The issue is fixed when `'operatorfunc'` is set from the command-line, but not when it's set from a script:
```vim
vim9script
['set operatorfunc=s:Opfunc']->writefile('/tmp/script.vim')
source /tmp/script.vim
```

**Comment by brammool** [comment]
We should be able to make that work, the script context can be stored with the callback.
Or using the script context where the option was last set.  Then it should also work when using a string.
@yegappan  - can you look into that?

**Comment by vim-ml** [comment]
Hi Bram,

On Thu, Dec 16, 2021 at 1:18 PM Bram Moolenaar ***@***.***>
wrote:

> We should be able to make that work, the script context can be stored with
> the callback.
> Or using the script context where the option was last set. Then it should
> also work when using a string.
> @yegappan <https://github.com/yegappan> - can you look into that?
>
>
>
I have created PR https://github.com/vim/vim/pull/9362 to support using a
script-local
function with the ':set' command for *func options.

- Yegappan

**Comment by vim-ml** [comment]
Yegappan wrote:

> On Thu, Dec 16, 2021 at 1:18 PM Bram Moolenaar ***@***.***>
> wrote:
> 
> > We should be able to make that work, the script context can be stored with
> > the callback.
> > Or using the script context where the option was last set. Then it should
> > also work when using a string.
> > @yegappan <https://github.com/yegappan> - can you look into that?
> >
> >
> >
> I have created PR https://github.com/vim/vim/pull/9362 to support using a
> script-local
> function with the ':set' command for *func options.

Thanks for doing this!

-- 
hundred-and-one symptoms of being an internet addict:
49. You never have to deal with busy signals when calling your ISP...because
    you never log off.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
