### ISSUE TITLE
[feature-request] can we have a win_close(winid, force) function

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#9373]
Currently, if we want to close a window by its ID, we have to switch to the tabpage where the window locates and use "close".

Tabpage/window switching will break key combo, trigger unnecessary events.

Can we have a universal win_close function to close window by window ID without tabpage/window switching ?

I want to close a terminal window if job is finished but if the window is the last window and the tabpage is the last tabpage I will keep them to prevent exiting vim.

Because "term_finish=close" cannot be used (it will exit vim if it is the last window), I need to detect the last window in the term callback then close the window manually. So, it would be nice to have a universal `win_close(winid, force)` function.

My current simulation:

```VimL
function! CloseWin(winid, force)
    let [tnr, wnr] = win_id2tabwin(a:winid)
    if tnr == 0 || wnr == 0
        return 0
    endif
    if has('nvim') == 0
        let last = win_getid()
        " switch to taget tabpage / window and close it
        noautocmd exec 'tabn ' . tnr
        noautocmd exec 'normal! ' . wnr . "\<c-w>w"
        if win_getid() == a:winid
            exec 'close' . ((a:force == 0)? '' : '!')
        else
            echohl ErrorMsg
            echom "ERROR: winid mismatch"
            echohl None
        endif
        " return the previous window
        if last != a:winid
            let [tnr, wnr] = win_id2tabwin(last)
            if tnr != 0 && wnr != 0
                noautocmd exec 'tabn ' . tnr
                noautocmd exec 'normal! ' . wnr . "\<c-w>w"
            endif
        endif
    else
        call nvim_win_close(a:winid, a:force)
    endif
    return 0
endfunc
```

**Comment by brammool** [comment]
If closing the window triggers autocommands, they will be executed in the current tabpage, which might differ from where the window is.  Wouldn't that cause problems?

**Comment by lacygoill** [comment]
Could [`win_execute()`](https://vimhelp.org/eval.txt.html#win_execute%28%29) help here (provided in patch [8.1.1418](https://github.com/vim/vim/releases/tag/v8.1.1418))?
```vim
function! CloseWin(winid, force)
    let [tnr, wnr] = win_id2tabwin(a:winid)
    if tnr == 0 || wnr == 0
        return 0
    endif
    if has('nvim') == 0
        call win_execute(a:winid, 'noautocmd close' .. (a:force == 0 ? '' : '!'))
    else
        call nvim_win_close(a:winid, a:force)
    endif
    return 0
endfunction
```

**Comment by skywind3000** [comment]
@lacygoill , thanks, problem solved. 
@brammool , still nice to have a `win_close`

**Comment by skywind3000** [comment]
btw: finally I choosed `:bdelete` to delete the terminal buffer in the finish callback, so the terminal related window should be closed and will keep vim from exit if terminal window is the last window.
