### ISSUE TITLE
error at `:help g@`

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9375]
From [`:help g@`](https://vimhelp.org/map.txt.html#g%40):

   > Although "block" would rarely appear, since it can
   > only result from Visual mode where "g@" is not useful.

That's wrong for 2 reasons.

First, the `block` type is not limited to Visual mode (see [`:help o_CTRL-V`](https://vimhelp.org/motion.txt.html#o_CTRL-V)):
```vim
vim9script
nnoremap <expr> <F4> CountSpaces()
def g:CountSpaces(type = ''): string
  if type == ''
    set opfunc=CountSpaces
    echomsg 'the current mode is: ' .. mode(1)
    return 'g@'
  endif
  echomsg 'the current mode is: ' .. mode(1)
  echomsg 'the type of the text-object is: ' .. type
  return ''
enddef
['xxx', 'xxx']->setline(1)
feedkeys("\<F4>\<C-V>j", 'x')
messages
```
    the current mode is: n
    the current mode is: n
    the type of the text-object is: block

Second, `g@` is useful *even* in Visual mode:
```vim
vim9script
xnoremap <expr> <F4> UpperCaseSelection()
def g:UpperCaseSelection(type = ''): string
  if type == ''
    set opfunc=UpperCaseSelection
    return 'g@'
  endif
  getline("'<", "'>")
      ->map((_, v) => v->toupper())
      ->setline('.')
  return ''
enddef
var lines =<< trim END
    xxx
    uppercase these lines
    from visual mode
    xxx
END
lines->setline(1)
feedkeys("2GVj\<F4>", 'x')
```
For these reasons, I think the 2 lines should be removed.

---

Still from [`:help g@`](https://vimhelp.org/map.txt.html#g%40):

   > "block"	{motion} was |blockwise-visual|

Again, `block` is not limited to visual mode, so the `|o_CTRL-V|` tag should probably be mentioned.

As a suggestion, here is a patch:
```diff
diff --git a/runtime/doc/map.txt b/runtime/doc/map.txt
index fc3f42584..ed80bead4 100644
--- a/runtime/doc/map.txt
+++ b/runtime/doc/map.txt
@@ -962,8 +962,7 @@ g@{motion}		Call the function set by the 'operatorfunc' option.
 			    "line"	{motion} was |linewise|
 			    "char"	{motion} was |characterwise|
 			    "block"	{motion} was |blockwise-visual|
-			Although "block" would rarely appear, since it can
-			only result from Visual mode where "g@" is not useful.
+					or forced to blockwise |o_CTRL-V|
 			{not available when compiled without the |+eval|
 			feature}
 
```

**Comment by lacygoill** [comment]
Unrelated, but at [`:help option-value-function`](https://vimhelp.org/options.txt.html#option-value-function), an example is given to illustrate how we can set a `'*func'` option to a funcref; the `string()` invocation is useless:

    let &tagfunc = string(Fn)
                   ^-----^  ^

Test:
```vim
function Func()
endfunction
let Fn = function('Func')
let &tagfunc = Fn
echo 'no error'
```
    no error

So, the example can be simplified a little by dropping `string()`:
```diff
diff --git a/runtime/doc/options.txt b/runtime/doc/options.txt
index a5ff937e0..d5f607976 100644
--- a/runtime/doc/options.txt
+++ b/runtime/doc/options.txt
@@ -385,7 +385,7 @@ lambda it will be converted to the name, e.g. "<lambda>123".  Examples:
 	set opfunc={a\ ->\ MyOpFunc(a)}
 	" set using a funcref variable
 	let Fn = function('MyTagFunc')
-	let &tagfunc = string(Fn)
+	let &tagfunc = Fn
 	" set using a lambda expression
 	let &tagfunc = {t -> MyTagFunc(t)}
 	" set using a variable with lambda expression
```

**Comment by brammool** [comment]
Thanks, I'll update the help.
