### ISSUE TITLE
Add native support for JSON RPC use by LSP protocol

### ISSUE THREAD

**Issue by prabirshrestha** [vim/vim#9390]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
It is is possible to do in vimscript or lua but is slow. 

**Describe the solution you'd like**
I would like vim to support json-rpc protocol (https://www.jsonrpc.org/specification) used by language server protocol (https://microsoft.github.io/language-server-protocol/specifications/specification-current/#baseProtocol) which is written in C and can be very fast. 

I'm looking for an alternative for json-rpc parsing protocol only and not a full blow language server protocol. 
https://github.com/microsoft/vscode-languageserver-node/tree/main/jsonrpc. This implementation has a lot of interesting optimizations.

**Describe alternatives you've considered**
would have penalty of converting string from vimscript string type to lua string type. Neovim has native support for lua types in vimscript and even added support for [lua-cjson](https://github.com/neovim/neovim/commits/912a6e5a9c58fce74134f9f8c2801373928e8289/src/cjson/lua_cjson.c).

**Additional context**
There are some codebase with 10k lines of code in files or servers that send lot of data so parsing past and making the editor responsive would be good.
Would need to support both stdio/tcp while most language server supports both some only support one or the other.

This could also potentially lay the future of remote plugins and make it easy for everyone without writing parsers on both side.

This is similar to fuzzy matching while it can be written in vimscript9 or lua for faster, having native support that is faster would be even better.

**Comment by brammool** [comment]
I'm not sure what you are asking for.  The JSON parsing is already implemented in C, in src/json.c, the core is in json_decode_item().
Try using the new Vim9 support with compiled :def functions, that should be much faster than legacy script and functions.
Perhaps some parts are inefficient, that should be located by profiling.

**Comment by CoelacanthusHex** [comment]
There already seems to be a Vim9 LSP implementation, https://github.com/yegappan/lsp
As Bram said, it uses Vim9 and native json_decode to optimize speed.

**Comment by chrisbra** [comment]
No further replies for clarification? I guess we can then close this.

**Comment by prabirshrestha** [comment]
@yegappan This is awesome. I will play around with this in the next few days.

This should also pave path for remote plugins similar to neovim so we can probably close this issue https://github.com/vim/vim/issues/2115
