### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by chrisbra** [vim/vim#9396]
### Steps to reproduce

N/A

### Expected behaviour

N/A

### Version of Vim

8.2.3697

### Environment

N/A

### Logs and stack traces

```shell
errors.h contains this part:

https://github.com/vim/vim/blob/28fbbeac7046f33db350294908eecb380042d553/src/errors.h#L753-L754

> "E1205: No white space allowed between option and"

I am wondering, should that mean "E1205: No white space allowed between option and *value*"?
```

**Comment by lacygoill** [comment]
> I am wondering, should that mean "E1205: No white space allowed between option and *value*"?

I don't understand how the code works, but looking at the tests, `E1205` seems to be given for these kind of mistakes (extra whitespace between option name and flag or assignment operator):

    set foldlevel =1
    set foldlevel +=1
    set foldlevel ^=1
    set foldlevel -=1
    set hlsearch &
    set hlsearch   !

I made a quick test, to check which error message Vim printed for those commands (whether at the script level or in compiled code):
```vim
vim9script
const MISTAKES: list<string> =<< END
    set foldlevel =1
    set foldlevel +=1
    set foldlevel ^=1
    set foldlevel -=1
    set hlsearch &
    set hlsearch   !
END

for cmd: string in MISTAKES
    try
        execute cmd
    catch
        echomsg v:exception
    endtry
    try
        execute(['def! g:Func()', printf('execute %s', cmd->string()), 'enddef'])
        g:Func()
    catch
        echomsg v:exception
    endtry
endfor
```
    Vim(set):E1205: No white space allowed between option and: =1
    Vim(set):E1205: No white space allowed between option and: =1
    Vim(set):E1205: No white space allowed between option and: +=1
    Vim(set):E1205: No white space allowed between option and: +=1
    Vim(set):E1205: No white space allowed between option and: ^=1
    Vim(set):E1205: No white space allowed between option and: ^=1
    Vim(set):E1205: No white space allowed between option and: -=1
    Vim(set):E1205: No white space allowed between option and: -=1
    Vim(set):E1205: No white space allowed between option and: &
    Vim(set):E1205: No white space allowed between option and: &
    Vim(set):E1205: No white space allowed between option and: !
    Vim(set):E1205: No white space allowed between option and: !

It seems that the value is always correctly included in the message.

But again, I don't understand the code well enough to see whether there is something to fix.

**Comment by chrisbra** [comment]
ah yes, it's further down. I was just going through the strings to be translated and this particular message confused me.
