### ISSUE TITLE
Vim9: cannot remove "M" flag from original value of 'cpoptions'

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9403]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE +'set cpoptions+=M' -S <(cat <<'EOF'
        vim9script
        set cpoptions-=M
    EOF
    ) +'echomsg &cpoptions'

This is echo'ed:

    aABceFsM

Notice the presence of the `M` flag.

**Expected behavior**

This is echo'ed:

    aABceFs

Notice the absence of the `M` flag.

**Version of Vim**

8.2 Included patches: 1-3890

**Environment**

Operating system: Ubuntu 20.04.3 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: zsh 5.8

**Additional Context**

At the start of a Vim9 script, `'cpoptions'` is automatically reset to its default Vim value.
At the end of the script, the original value is restored.

But according to [`:help vim9-namespace`](https://vimhelp.org/vim9.txt.html#vim9-namespace), a flag removed in the script should also be removed from the original value:

   > The original value of 'cpoptions' is restored at the end of the script, while
   > flags added or removed in the script are also added to or removed from the
   > original value to get the same effect.

Since `M` is removed in the script, it should be removed from the original value.

---

No issue when sourcing a legacy script:

    vim -Nu NONE +'set cpoptions+=M' -S <(cat <<'EOF'
        set cpoptions-=M
    EOF
    ) +'echomsg &cpoptions'

    aABceFs

---

The issue is specific to some flags but not all.

For example, it also affects the `n`, `y` and `>` flags; but not the `B`, `c`, `e`, `F`, and `s` flags:

    vim -Nu NONE +'set cpoptions=BceFsMny>' -S <(cat <<'EOF'
        vim9script
        set cpoptions=
    EOF
    ) +'echomsg &cpoptions'

    Mny>

---

Here is the list of all the flags which can't be removed from a Vim9 script:

    bCdDEfgHiIjJkKlLmMnoOpPqrRStuvwWxXyZ$!%*-+<>;#&./\{|

That is all the flags which are absent from the Vim default value.

Test:

    $ vim -Nu NONE +'set cpoptions&vi cpoptions+=#&./\\{\|' -S <(cat <<'EOF'
        vim9script
        set cpoptions=
    EOF
    ) +'echomsg &cpoptions'

    bCdDEfgHiIjJkKlLmMnoOpPqrRStuvwWxXyZ$!%*-+<>;#&./\{|

And here is the list of all the flags which can't be added from a Vim9 script:

    aABceFs

Test:

    $ vim -Nu NONE +'set cpoptions=' -S <(cat <<'EOF'
        vim9script
        set cpoptions&vi
        set cpoptions+=#&./\\{\|
    EOF
    ) -S <(cat <<'EOF'
        let g:cpo = &cpoptions->split('\zs')
        set cpoptions&vi cpoptions+=#&./\\{\|
        echomsg &cpoptions->split('\zs')->filter({_, v -> g:cpo->index(v) == -1})->join('')
    EOF
    )

    aABceFs

That is all the flags which are present in the Vim default value.

**Comment by lacygoill** [comment]
> $ vim -Nu NONE +'set cpoptions&vi cpoptions+=#&./\\{\|' -S <(cat <<'EOF'
   >     vim9script
   >     set cpoptions=
   > EOF
   > ) +'echomsg &cpoptions'
   >
   > bCdDEfgHiIjJkKlLmMnoOpPqrRStuvwWxXyZ$!%*-+<>;#&./\{|

Adding the `#&./\{|` flags looks weird.  Here is a better test:

    $ VIM_POSIX=yes vim -Nu NONE +'set cpoptions&vi' -S <(cat <<'EOF'
        vim9script
        set cpoptions=
    EOF
    ) +'echomsg &cpoptions'

    bCdDEfgHiIjJkKlLmMnoOpPqrRStuvwWxXyZ$!%*-+<>#{|&/\.;

**Comment by brammool** [comment]
"Since M is removed in the script, it should be removed from the original value."
But the M flag is not removed, because at this point it is not present.
Thus the "set cpoptions-=M" command has no effect.

I don't think there is a way around this.  You can use a SourcePost autocommand to change 'cpoptions' later.

**Comment by lacygoill** [comment]
Understood.  But I suspect it can cause a few confusing situations.  I need to do more tests to be sure.

**Comment by lacygoill** [comment]
> But I suspect it can cause a few confusing situations.

Sometimes, when I need to find a MWE for a bug, I try various weird shell commands.  Among those, there is this one:

    vim --cmd 'filetype on'

It gives a lot of confusing errors (in part because `'cpoptions'` is set to its Vi default value which includes the `C` flag).  Maybe it is to be expected (not sure), but it's still distracting when we're focused on a different issue.  To avoid this distraction, I thought about adding this in my vimrc:

    set cpoptions&vim

But it has no effect when `:filetype on` is executed before the vimrc is sourced.  `'cpoptions'` is still reset to its Vi default value.

**Comment by lacygoill** [comment]
> But it has no effect when :filetype on is executed before the vimrc is sourced. 'cpoptions' is still reset to its Vi default value.

But only if the vimrc is written in a Vim9 script file.

Here is how to test this:

    $ printf 'set cpoptions&vim' >/tmp/.vimrc && HOME=/tmp vim --cmd 'filetype on' +'echomsg &cpoptions'
    aABceFs

    $ printf 'vim9script\nset cpoptions&vim' >/tmp/.vimrc && HOME=/tmp vim --cmd 'filetype on' +'echomsg &cpoptions'
    aAbBcCdDeEfFgHiIjJkKlLmMnoOpPqrRsStuvwWxXyZ$!%*-+<>;

**Comment by brammool** [comment]
An alternative could be that if 'cpoptions' was changed in the Vim9 script file, then it is not restored.
This is tricky though, if a plugin written in Vim9 script changes (and perhaps restores) cpoptions then this may have
a drastic effect for other scripts the user has.

Another alternative is to not restore 'cpoptions' for the main .vimrc file. That has the side effect that when the vimrc file is written in Vim9 script then 'cpoptions' will default to the Vim value.  That doesn't sound too bad.

**Comment by lacygoill** [comment]
> Another alternative is to not restore 'cpoptions' for the main .vimrc file. That has the side effect that when the vimrc file is written in Vim9 script then 'cpoptions' will default to the Vim value. That doesn't sound too bad.

I think it makes sense.  If the vimrc is written in Vim9 script, the user will most probably not want `'cpoptions'` to be set by default with the Vi value, which sets 52 flags causing all sorts of unexpected issues for recent plugins.
