### ISSUE TITLE
[BUG] Syntax highlighting error when using multiple brackets in POSIX sh (as same as #9263 )

### ISSUE THREAD

**Issue by CoelacanthusHex** [vim/vim#9404]
### Steps to reproduce

1. write a file contained lines below:
```sh
$((((1+2))+3-$((6))))
```
2. `set filetype=sh` or `set filetype=bash`
3. look at highlight, it will be like this
![图片](https://user-images.githubusercontent.com/43064781/147384495-33a46eea-6f87-4c5b-af07-09e14e5d54a2.png)

You also can see it using one command: `echo '$((((1+2))+3-$((6))))' | vim --clean - -c "syntax on | set ft=sh bt=nofile | colo desert"`

### Expected behaviour

The parentheses are highlighted right. At least, parentheses should be match correctly.

### Version of Vim

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 25 2021 04:18:14) Included patches: 1-3890

### Environment

Arch Linux rolling

**Comment by CoelacanthusHex** [comment]
POSIX sh has this syntax, so all POSIX compatible shell in sh.vim should fix this problem.

**Comment by 91khr** [comment]
> POSIX sh has this syntax, so all POSIX compatible shell in sh.vim should fix this problem.

In fact, `bash.vim` links to `sh.vim`...
Senioria skimmed `syntax/*sh.vim`, and it seems that only sh and zsh need to be noted... ?

**Comment by CoelacanthusHex** [comment]
> In fact, `bash.vim` links to (more accurately, sources) `sh.vim`... Senioria skimmed `syntax/*sh.vim`, and it seems that only sh and zsh need to be noted... ?

This sounds like good news.

**Comment by 91khr** [comment]
BTW, this is not matched correctly either:

```sh
$(( ((1) + 2) * 3 ))
```

**Comment by chrisbra** [comment]
closing for #9407 then
