### ISSUE TITLE
Vim9: second argument of `sort()` not checked

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9415]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            getbufinfo()
                ->sort((a: dict<float>, b: dict<float>) => 0)
        enddef
        Func()
    EOF
    )

No error is given.

**Expected behavior**

An error is given at runtime, because `getbufinfo()` outputs a list of dictionaries with mixed values:

    :echo getbufinfo()->typename()
    list<dict<any>>

But in the second argument of `sort()`, we've specified that the items in the list were all dictionaries with float values.  The types don't match.

**Version of Vim**

8.2 Included patches: 1-3908

**Environment**

Operating system: Ubuntu 20.04.3 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: zsh 5.8

**Additional Context**

If we replace `sort()` with `mapnew()`, an error is correctly given at runtime:
```vim
vim9script
def Func()
    getbufinfo()
        ->mapnew((_, v: dict<float>) => 0)
enddef
Func()
```
    E1013: Argument 2: type mismatch, expected dict<float> but got dict<any>

Which is expected, but also inconsistent with regards to what happens with `sort()`.

**Comment by brammool** [comment]
The error is given when the function is called.  In the first case the function is never called, because the list only has one item. If you create another buffer then the list has two items, the function is called and the error is given.

**Comment by lacygoill** [comment]
Right.  Sorry for the noise.

---

How about this one:
```vim
vim9script
def Func()
    [{k: 1}, {k: 2}]
        ->sort((a: dict<float>, b: dict<float>): number => a.k > b.k ? a.k - b.k : 0)
enddef
defcompile
```
    no error

We pass dictionaries of numbers to `sort()`; but we've specified to `sort()` that it should operate on dictionaries of floats.  Shouldn't `E1013` be given?

    E1013: Argument 2: type mismatch, expected func(dict<number>, dict<number>): number but got func(dict<float>, dict<float>): number

Note that if the `?:` operator is removed, an error is correctly given at compile time:
```vim
vim9script
def Func()
    [{k: 1}, {k: 2}]
        ->sort((a: dict<float>, b: dict<float>): number => a.k - b.k)
enddef
defcompile
```
    E1012: Type mismatch; expected number but got float

Although, this error is about the return type, not the arguments type.

**Comment by brammool** [comment]
The type checking is done at runtime, when the function is called.
I did notice it doesn't quit sorting, I made a patch for that.

**Comment by lacygoill** [comment]
> The type checking is done at runtime, when the function is called.

The second snippet shows that without `?:`, type checking can be done at compile time:
```vim
vim9script
def Func()
    [{k: 1}, {k: 2}]
        ->sort((a: dict<float>, b: dict<float>): number => a.k - b.k)
enddef
defcompile
```
    E1012: Type mismatch; expected number but got float

Does this mean that `?:` can suppress type checking at compile time?

---

Also, if we keep `?:`, but remove `sort()`, an error is correctly given at compile time:
```vim
vim9script
def Func()
    ((a: dict<float>, b: dict<float>): number => a.k > b.k ? a.k - b.k : 0)({k: 1}, {k: 2})
enddef
defcompile
```
    E1013: Argument 1: type mismatch, expected dict<float> but got dict<number>

Why is type checking delayed until runtime with `sort()`, but not without?
