### ISSUE TITLE
Vim9: no type checking for first argument of `append()`

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9417]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        append(-1, 'text')
    EOF
    )

No error is given.

**Expected behavior**

An error is given because the first argument of `append()` should describe a valid line address.  But here, we gave the address `-1` which is not valid.

Maybe `E1174`:

    E1174: Positive number required for argument 1
    E1174: Positive number or String required for argument 1

**Version of Vim**

8.2 Included patches: 1-3913

**Environment**

Operating system: Ubuntu 20.04.3 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: zsh 5.8

**Additional Context**

The first argument can also be a string.  But then again, no type checking is performed, which can lead to seemingly unexpected and inconsistent results:
```vim
vim9script
append('.aa', 'text')
```
    "text" is appended
```vim
vim9script
append('a.a', 'text')
```
    E1209: Invalid value for a line number: "a.a"

If the user specifies the line address via a string, could/should we check that it's valid?

I think the only valid strings are given at [`:help line()`](https://vimhelp.org/eval.txt.html#line%28%29):

   > .	    the cursor position
   > $	    the last line in the current buffer
   > 'x	    position of mark x (if the mark is not set, 0 is
   >         returned)
   > w0	    first line visible in current window (one if the
   >         display isn't updated, e.g. in silent Ex mode)
   > w$	    last line visible in current window (this is one
   >         less than "w0" if no lines are visible)
   > v	    In Visual mode: the start of the Visual area (the
   >         cursor is the end).  When not in Visual mode
   >         returns the cursor position.  Differs from |'<| in
   >         that it's updated right away.

**Comment by lacygoill** [comment]
> The first argument can also be a string.  But then again, no type checking is performed, which can lead to seemingly unexpected and inconsistent results:

It's inconsistent because both `'.aa'` and `'a.a'` are invalid; and yet, they give different results.
`'.aa'` is parsed as `'.'` but there is no reason to assume that the user wants that.
`'a.a'` is ignored which is worse, because the user won't know that their code is broken.

**Comment by lacygoill** [comment]
> 'a.a' is ignored which is worse, because the user won't know that their code is broken.

Ah no, it's not ignored.  That's in legacy.  So the issue is limited to `'.aa'`.

**Comment by brammool** [comment]
I added some more checks, also for other functions where the line number is used.
There are probably others, let me know if you find one.

**Comment by lacygoill** [comment]
Sometimes, `E966` is given unexpectedly:
```vim
vim9script
append('.aa', 'text')
```
    E1209: Invalid value for a line number: ".aa"
    E966: Invalid line number: -1

There is no line number `-1` in the code.
The first error is expected though.

---

I started some tests, but I don't know what is expected.  For example, in Vim9, all these functions accept a negative or 0 line number:

    diff_filler()
    foldclosed()
    foldclosedend()
    foldlevel()
    foldtextresult()
    getline()
    line2byte()
    nextnonblank()

That's obviously wrong but that's how it's documented to work in legacy.  For example, from [`:help getline()`](https://vimhelp.org/builtin.txt.html#getline%28%29):

> <               When {lnum} is a number smaller than 1 or bigger than the
>                 number of lines in the buffer, an empty string is returned.

**Comment by brammool** [comment]
> Sometimes, `E966` is given unexpectedly:
> ```vim
> vim9script
> append('.aa', 'text')
> ```
>     E1209: Invalid value for a line number: ".aa"
>     E966: Invalid line number: -1
> 
> There is no line number `-1` in the code.
> The first error is expected though.

Yes, there should be a check that an error was already given and bail
out.  I'll fix a few that I can find.

> I started some tests, but I don't know what is expected.  For example, in Vim9, all these functions accept a negative or 0 line number:
> 
>     diff_filler()
>     foldclosed()
>     foldclosedend()
>     foldlevel()
>     foldtextresult()
>     getline()
>     line2byte()
>     nextnonblank()
> 
> That's obviously wrong but that's how it's documented to work in
> legacy.  For example, from [`:help
> getline()`](https://vimhelp.org/builtin.txt.html#getline%28%29):
> 
> > <               When {lnum} is a number smaller than 1 or bigger than the
> >                 number of lines in the buffer, an empty string is returned.

Generally for "get" functions you get an empty result if the line range
is wrong.  That isn't necessarily an error, and the caller can usually
check for that.  For "append" and "delete" it's easy for a wrong line
number to go unnoticed, giving an error is useful.

However, using an invalid argument such as "$x" is clearly a mistake and
should result in an error.

-- 
hundred-and-one symptoms of being an internet addict:
125. You begin to wonder how often it REALLY is necessary to get up
     and shower or bathe.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
