### ISSUE TITLE
Diff gets misaligned on files with uneven NULL bytes

### ISSUE THREAD

**Issue by chris-morgan** [vim/vim#9418]
### Steps to reproduce

Create two similar files with a different number of ␀ (null, U+0000) bytes, and diff them:

```console
$ printf 'a\nb\nc\000\nd\ne\nf\ng\n' > a
$ printf 'A\nb\nc\nd\nE\nf\ng\n' > b
$ vimdiff -u NONE a b
```

Here’s a screenshot of the results I observe:

<img width=364 height=247 alt="Screenshot demonstrating the misaligned diff" src="https://user-images.githubusercontent.com/392868/147551040-bc76aac1-a02e-4901-8c09-914593b2619b.png">

### Expected behaviour

- The `c^@`/`c` line should show a diff.
- The diff should not get out of sync by one line below that point.

### Version of Vim

8.2.3890

### Environment

Arch Linux, Alacritty.

**Comment by chrisbra** [comment]
This might be a problem of `diff_write_buffer()`, it works if you use `:set diffopt-=internal`.

**Comment by chrisbra** [comment]
I think we need this patch:
```patch
diff --git a/src/diff.c b/src/diff.c
index e9367b568..bb5974e90 100644
--- a/src/diff.c
+++ b/src/diff.c
@@ -769,9 +769,14 @@ diff_write_buffer(buf_T *buf, diffin_T *din)
                int     orig_len;
                char_u  cbuf[MB_MAXBYTES + 1];

-               // xdiff doesn't support ignoring case, fold-case the text.
-               c = PTR2CHAR(s);
-               c = MB_CASEFOLD(c);
+               if (*s == NL)
+                   c = NUL;
+               else
+               {
+                   // xdiff doesn't support ignoring case, fold-case the text.
+                   c = PTR2CHAR(s);
+                   c = MB_CASEFOLD(c);
+               }
                orig_len = mb_ptr2len(s);
                if (mb_char2bytes(c, cbuf) != orig_len)
                    // TODO: handle byte length difference
@@ -783,7 +788,10 @@ diff_write_buffer(buf_T *buf, diffin_T *din)
                len += orig_len;
            }
            else
-               ptr[len++] = *s++;
+           {
+               ptr[len++] = *s == NL ? NUL : *s;
+               s++;
+           }
        }
        ptr[len++] = NL;
     }
```

Will create a PR with this and a test later today

**Comment by chris-morgan** [comment]
Thanks for the super-quick patch! 🙂

> ASCII NUL is internally stored as NL

Ah, so I guess *that’s* why `:s/./\n/` puts NUL and you have to use `\r` or <kbd>\<C-V\></kbd><kbd>\<C-M\></kbd> instead of `\n` to get an actual line break? I just internalised that that was necessary ten or fifteen years ago and stopped wondering why. I see via #7744 that that’s now considered a bug rather than a feature. Pity.

**Comment by Shane-XB-Qian** [comment]
```
foo

bar
```

to hex:

```
00000000: 666f 6f0a 0a62 6172 0a                   foo..bar.
```

2ed line it is a `0a`, but `ga` cmd thought it is a `NUL`.
~~so it is intended or confused?~~

**Comment by Shane-XB-Qian** [comment]
doc said:

```
			The <Nul> character in a file is stored internally as
			<NL>, but it will be shown as:
				<^@>  0,  Hex 00,  Octal 000 ~
```

here the 2ed line stored a `0a` ~~but~~ showed as `NUL`.
