### ISSUE TITLE
incsearch makes a matchadd() highlighting invisible on 8.2

### ISSUE THREAD

**Issue by rickhowe** [vim/vim#9425]
### Steps to reproduce

For example. when a line is highlighted with:
`:call matchaddpos('Error', [10])`

And
`:set incsearch`

Then, enter `:s/.` to try to substitute something, the matchadd highlighting becomes invisible.

### Expected behaviour

Keep the highlighting visible.

### Version of Vim

8.2 and latest patches (but not on 8.1 and 8.0)

### Environment

 Windows 10

**Comment by lacygoill** [comment]
The change started in [8.1.0275](https://github.com/vim/vim/releases/tag/v8.1.0275).

[Possible relevant discussion](https://github.com/vim/vim/commit/b0acacd767a2b0618a7f3c08087708f4329580d0#commitcomment-30043706) in the commit 8.1.0271.

---

As a workaround, you might temporarily reset [`'incsearch'`](https://vimhelp.org/options.txt.html#%27incsearch%27) while on the Ex command-line:

    augroup no-incsearch-highlight
      autocmd!
      autocmd CmdlineEnter : set noincsearch
      autocmd CmdlineLeave : set incsearch
    augroup END
