### ISSUE TITLE
[Regression] `fnamemodify('', ':p')` returns nothing only on Windows from (some around) 8.2.3832

### ISSUE THREAD

**Issue by lambdalisue** [vim/vim#9427]
### Steps to reproduce

1. Open [GVim 8.2.3832 on Windows](https://github.com/vim/vim-win32-installer/releases/tag/v8.2.3832)
2. Hit `:echo fnamemodify('', ':p')`

### Expected behavior

An absolute path of the current working directory is shown.

### Actual behavior

With GVim 8.2.3832 on Windows, it shows nothing (an empty string).

### Version of Vim

- v8.2.3930 - Failed
- v8.2.3832 - Failed
- v8.2.3821 - Correct

### Environment

- OS: Windows 11
- Terminal: Windows Terminal

### Additional note

The correct behavior could be observed when [GVim 8.2.3821 on Windows](https://github.com/vim/vim-win32-installer/releases/tag/v8.2.3821) or earlier is used or Vim on Linux/macOS.

Because vim-win32-installer does not provide versions between v8.2.3821 and v8.2.3832, I only can say that this regression was introduced between those versions.

It's also happened on `windows-latest` runner on GitHub Actions.

https://github.com/lambdalisue/fern.vim/runs/4657915766?check_suite_focus=true

**Comment by lambdalisue** [comment]
For user who faced this issue, use `fnamemodify('.', ':p')` instead of `fnamemodify('', ':p')` as a temporal workaround.
https://github.com/lambdalisue/fern.vim/pull/381

**Comment by chrisbra** [comment]
So short question: Why were you using an empty argument for the filename of `fnamemodify()`?

**Comment by chrisbra** [comment]
I mean, it looks like you actually want to use `getcwd()`?

**Comment by brammool** [comment]
Patch 8.2.3824 changed this.  An empty string is considered a full path.
Christian, perhaps you can make a PR changing the "return TRUE" in mch_isFullName() to return FALSE?
I suspect some test will fail.

**Comment by chrisbra** [comment]
I can do it, but @yegappan  already addressed this issue, so @yegappan will you take it or shall I?

**Comment by yegappan** [comment]
I have already created PR #9428 with this change and a test for this.

**Comment by chrisbra** [comment]
thanks

**Comment by lambdalisue** [comment]
Thanks a lot 🎉
