### ISSUE TITLE
Warning when compiling diff.c

### ISSUE THREAD

**Issue by bonidydy** [vim/vim#9429]
### Steps to reproduce

Start make, CONF_OPT_FEAT = --with-features=normal

### Expected behaviour

No warnings from the compiler

### Version of Vim

8.2.3941

### Environment

Debian, gcc 11.2.0

### Logs and stack traces

```shell
gcc -c -I. -Iproto -DHAVE_CONFIG_H     -O2 -fno-strength-reduce -Wall -Wno-deprecated-declarations -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/diff.o diff.c
diff.c: In function ‘diff_try_update’:
diff.c:3284:26: warning: ‘hunk’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 3284 |         hunk->count_orig = oldcount;
      |         ~~~~~~~~~~~~~~~~~^~~~~~~~~~
diff.c:1639:18: note: ‘hunk’ was declared here
 1639 |     diffhunk_T  *hunk;
      |                  ^~~~
```

**Comment by tonymec** [comment]
I confirm this problem in all builds from Normal to Huge. (N.B. Small and Tiny, which don't have this warning, are, among other features, built without +diff. They include a diff.c which I guess is entirely [or almost] #ifdef'd away.)

**Comment by tonymec** [comment]
P.S. I'm on openSUSE Leap 5.3 with gcc 7.5.0.
