### ISSUE TITLE
Unexpected Behavior After Adding `noremap <C-[> <NOP>` to .vimrc

### ISSUE THREAD

**Issue by z3ht** [vim/vim#9430]
### Steps to reproduce

1. Add `noremap <C-[> <NOP>` to `~/.vimrc`
2. Run `vim`
3. See that the program begins in `REPLACE` mode

### Expected behaviour

I would expect this command to map the `Ctrl + [` key to nothing. However, it starts Vim in REPLACE mode. This is problematic because anything after this line in the `.vimrc` is added incorrectly.

This is a low priority issue because the `Ctrl + [` key appears to do nothing by default so the problem can be avoided by simply not adding the above line to the `.vimrc` file.

Thanks!! I'm happy to provide any more details if needed.

### Version of Vim

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov 09 2021 19:35:34) Included patches: 1-3582 Compiled by Arch Linux

### Environment

Operating System: Arch Linux
Terminal: Both alacritty and xterm
Shell: zsh

**Comment by lacygoill** [comment]
`<C-[>`/`<Esc>` is used at the start of various escape sequences which let Vim communicate with the terminal.  [Mapping any of these keysyms is a bad idea](https://github.com/lacygoill/wiki/blob/master/vim/mapping.md#why-should-i-avoid-a-mapping-with-an-esc-in-its-lhs).

[The only reliable solution is to not map it.](https://github.com/vim/vim/issues/2581#issuecomment-639746235)

---

During startup, Vim sends various sequences to the terminal including a DSR one (Device Status Report):

    ^[[6n

It asks the terminal what is the position of the cursor:

   > CSI Ps n  Device Status Report (DSR).
   >             Ps = 5  -> Status Report.
   >           Result ("OK") is CSI 0 n
   >             Ps = 6  -> Report Cursor Position (CPR) [row;column].
   >           Result is CSI r ; c R

[source](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Functions-using-CSI-_-ordered-by-the-final-character_s_)

The latter answers with a sequence such as:

    ^[[1;2R

Vim doesn't know whether this sequence was typed by the user, or sent by the terminal.  So, it's subject to mappings like any sequence, and if you map `<C-[>` too early, then Vim will remap `^[` to `<Nop>`.  As a result, the answer from the terminal gets broken; Vim no longer understands it as a cursor position, but as a regular sequence of commands in normal mode.  In particular, `R` enters Replace mode.

You can check all of this by logging the keys which are sent back and forth between Vim and the terminal, invoking [`ch_logfile()`](https://vimhelp.org/channel.txt.html#ch_logfile%28%29):

    $ vim -Nu NONE --cmd 'call ch_logfile("/tmp/logfile", "w")' +'nnoremap <C-[> <Nop>'
    CTRL-C
    :quit
    $ vim /tmp/logfile
    :% vglobal /raw/ delete _

You should find lines similar to these ones:

    0.002882 : raw terminal output: "^[[2;1H▽^[[6n"
    0.002902 : raw terminal output: "^[[2;1H  ^[[3;1H^[Pzz^[\^[[0%m^[[6n"

`^[[6n` is logged when Vim asks the terminal for the cursor position.

And you should find lines similar to these ones:

    0.003064 : raw key input: "^[[2;2R"
    0.003107 : raw key input: "^[[3;1R^[[>41;353;0c"

`^[[2;2R` and `^[[3;1R` are logged when the terminal tells Vim where the cursor is.

---

You could fix this particular issue by preventing Vim from requesting the cursor position.  For that, you need to clear the [`'t_u7'`](https://vimhelp.org/term.txt.html#%27t_u7%27) option:

    set t_u7=

But you would probably get other similar issues, forcing you to also clear [`'t_RB'`](https://vimhelp.org/term.txt.html#%27t_RB%27) and [`'t_RF'`](https://vimhelp.org/term.txt.html#%27t_RF%27):

    set t_RB= t_RF=

Not sure what all the consequences would be.

Alternatively, you could delay the mapping via a timer, after the terminal has sent its answers:

    $ vim -Nu NONE +'autocmd VimEnter * call timer_start(100, {-> execute("nnoremap <C-[> <Nop>")})'

---

   > This is problematic because anything after this line in the .vimrc is added incorrectly.

Each line in the `.vimrc` is interpreted as an Ex command.  And most of the Ex commands that you can find in a `.vimrc` set options, or install mappings and autocmds.  These commands don't care about the current mode.  Besides, the issue doesn't start immediately after the mapping has been installed, but after the terminal has sent the cursor position, which can happen at any time during startup.

**Comment by chrisbra** [comment]
I am closing this as a duplicate.

**Comment by chrisbra** [comment]
BTW: I think in newer vims you can also use `:set noxtermcodes`. It may also fix this issue, not sure

**Comment by z3ht** [comment]
Thanks for all of the help on this! I'll just stop using Ctrl+[ in my key bindings.
