### ISSUE TITLE
Can't make funcref to Vim9 autoload function prior to calling

### ISSUE THREAD

**Issue by dstein64** [vim/vim#9445]
### Steps to reproduce

1. Create an autoload script, `~/.vim/autoload/test.vim`.
2. Add the following:

```vim
vim9script

def test#Hello(): string
  return 'hello'
enddef
```

3. Relaunch Vim and create a `funcref`.

```vim
let X = funcref('test#Hello')
```

### Expected behaviour

I expected the funcref could be created.

Rather, I received the following error: "E700: Unknown function: test#Hello"

At first, I thought that this could be expected behaviour of Vim9, but if I call the function first, then the funcref could be created without an error, so I thought there might be an issue.

```vim
call test#Hello()
let X = funcref('test#Hello')
```

### Version of Vim

8.2.3700

### Environment

Operating System: macOS 12.1
Terminal: Terminal.app 2.12
Value of $TERM: xterm-256color
Shell: bash 5.1.12

**Comment by dstein64** [comment]
I just realized that this same behaviour occurs with ordinary Vimscript. Sorry for the erroneous bug report.

**Comment by dstein64** [comment]
I could presumably use `function()` instead of `funcref()` in this scenario.

**Comment by brammool** [comment]
Not sure if you actually used the wrong file name or only mentioned the wrong name in this issue: If you use "test#Hello" then the file should be autoload/test.vim, not autoload/hello.vim.

**Comment by dstein64** [comment]
> "Not sure if you actually used the wrong file name or only mentioned the wrong name in this issue"

I mistakenly mentioned the wrong name, as I had intended to name the file "hello.vim", but actually named the file "test.vim". I updated the text above to have "test.vim" in step 1.

**Comment by brammool** [comment]
The help for funcref() is unclear, it should mention that an autoload function must have been loaded.  The reference does not work with the name, it's easy to make a mistake and unintentionally load the autoload script.
