### ISSUE TITLE
Colors missing in 7.4.2098

### ISSUE THREAD

**Issue by Safari77** [vim/vim#945]
```
Error detected while processing /usr/share/vim/vim74/syntax/syncolor.vim:
line   46:
E254: Cannot allocate color SlateBlue
```

also `Grey40` and `Orange` are missing.

running on Fedora 23.

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul 24 2016 14:18:45)
Included patches: 1-2098
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    -mouse_sysmouse  -tag_any_white
+arabic          +find_in_path    +mouse_urxvt     -tcl
+autocmd         +float           +mouse_xterm     +termguicolors
-balloon_eval    +folding         +multi_byte      +terminfo
-browse          -footer          +multi_lang      +termresponse
++builtin_terms  +fork()          -mzscheme        +textobjects
+byte_offset     +gettext         -netbeans_intg   +timers
+channel         -hangul_input    +num64           +title
+cindent         +iconv           +packages        -toolbar
-clientserver    +insert_expand   +path_extra      +user_commands
-clipboard       +job             +perl            +vertsplit
+cmdline_compl   +jumplist        +persistent_undo +virtualedit
+cmdline_hist    +keymap          +postscript      +visual
+cmdline_info    +langmap         +printer         +visualextra
+comments        +libcall         +profile         +viminfo
+conceal         +linebreak       +python          +vreplace
+cryptv          +lispindent      -python3         +wildignore
+cscope          +listcmds        +quickfix        +wildmenu
+cursorbind      +localmap        +reltime         +windows
+cursorshape     +lua             +rightleft       +writebackup
+dialog_con      +menu            +ruby            -X11
+diff            +mksession       +scrollbind      -xfontset
+digraphs        +modify_fname    +signs           -xim
-dnd             +mouse           +smartindent     -xsmp
-ebcdic          -mouseshape      +startuptime     -xterm_clipboard
+emacs_tags      +mouse_dec       +statusline      -xterm_save
+eval            +mouse_gpm       -sun_workshop    -xpm
+ex_extra        -mouse_jsbterm   +syntax          
+extra_search    +mouse_netterm   +tag_binary      
+farsi           +mouse_sgr       +tag_old_static  
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim74"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -O2 -g -pipe -Wall -Werror=format-security -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -fPIE -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -L. -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,--enable-new-dtags -Wl,-z,relro   -pie -Wl,-z,relro -Wl,-z,now -L/usr/local/lib -Wl,--as-needed -o vim        -lm -lelf -lnsl   -lncurses -lacl -lattr -lgpm -ldl  -L/usr/lib -llua -Wl,--enable-new-dtags -Wl,-z,relro  -Wl,-z,relro  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib64/perl5/CORE -lperl -lpthread -lresolv -lnsl -ldl -lm -lcrypt -lutil -lc -L/usr/lib64/python2.7/config -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic   -lruby -lpthread -ldl -lcrypt -lm     
```

**Comment by Safari77** [comment]
Found the problem, `/usr/share/vim/vim74/rgb.txt` was not included in the vim-common package.

**Comment by pine-byte** [comment]
hi, i has the same problem, but i don't understand you answered, please teach me how to solve it.

**Comment by chrisbra** [comment]
you need rgb.txt in your $VIMRUNTIME directory, because Vim uses it for determining the values for color names. If you still have problems, please ask at vi.stackexchange.com or use the vim-use mailinglist, sorry this is no support channel here.

**Comment by xxoolltt** [comment]
@Safari77  /usr/share/vim/vim74/rgb.txt .  It works!

**Comment by ngara** [comment]
For me, using homebrew's version of vim, I found this to work: export VIMRUNTIME=/opt/brew/share/vim/vim82

**Comment by JWCS** [comment]
For future reference, for others still having issues with `E254: Cannot allocate color SlateBlue` and `failed to load colors/lists/default.vim`, [this is the vi.SE.com link](https://vi.stackexchange.com/questions/34639/e254-cannot-allocate-color-slateblue) @Safari77 made.
The bigger problem (for me, compiling a fresh pull today 8.2.3582) was that _all_ the runtime files were missing or unable to be found, not just rgb.txt, but since I compiled vim, and vim makes a runtime/ subdirectory with everything, a solution was as simple as adding this line to the `.bashrc`:
`export VIMRUNTIME=~/path/to/vim(repo)/runtime/`

**Comment by chrisbra** [comment]
if you compiled yourself, did you not run `make install`? Note, that with a recent change, the file `rgb.txt` is no longer needed, because Vim now allows to define colors using the mentioned `colors/lists/default.vim`, however that one will only get loaded, if you have a build with a gui or `termguicolors` setting included. see also #9073

**Comment by JWCS** [comment]
Interesting. I did have a "failed to load" for that defaults file, and there was no VIMRUNTIME env variable set. I pulled 8.2.3582, changed config to use gtk3 gui with python3 support, apt installed all dependencies, and both make and make-install'ed. Not all the tests passed - some 22 failed, but I figured that was close enough. I did pull / update the repo from an older version of 8.2, but the runtime/ subdir was there with all the necessary files. Other than the info already provided, here's the version number.

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov  5 2021 15:21:24)
Included patches: 1-3582
Compiled by me@mypc
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
+balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +gettext           +num64             +textobjects
+browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     -perl              +title
+channel           +ipv6              +persistent_undo   +toolbar
+cindent           +job               +popupwin          +user_commands
+clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           -python            +visual
+cmdline_info      +libcall           +python3           +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
+cscope            +localmap          -ruby              +wildmenu
+cursorbind        -lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con_gui    +mksession         +smartindent       +X11
+diff              +modify_fname      -sodium            -xfontset
+digraphs          +mouse             -sound             +xim
+dnd               +mouseshape        +spell             +xpm
-ebcdic            +mouse_dec         +startuptime       +xsmp_interact
+emacs_tags        +mouse_gpm         +statusline        +xterm_clipboard
+eval              -mouse_jsbterm     -sun_workshop      -xterm_save
+ex_extra          +mouse_netterm     +syntax            
+extra_search      +mouse_sgr         +tag_binary        
-farsi             -mouse_sysmouse    -tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -O2 -fno-strength-reduce -Wall -Wno-deprecated-declarations -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: gcc -L/usr/local/lib -Wl,--as-needed -o vim -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE -lm -ltinfo -lselinux -lacl -lattr -lgpm -ldl -L/home/me/.pyenv/versions/3.8.9/lib/python3.8/config-3.8-x86_64-linux-gnu -lpython3.8 -lcrypt -lpthread -ldl -lutil -lm -lm
```

**Comment by SKOHscripts** [comment]
Hi, 
I still have exactly the same pb : 
```bash
failed to load colors/lists/default.vim
Erreur détectée en traitant /home/.vimrc[104]..function plug#end[86]..script /home/.local/share/vim/vim82/syntax/syntax.vim[19]../usr/share/vim/vim81/syntax/synload.vim[21]../usr/share/vim/vim81/syntax/syncolor.vim
```
The fact is that I have a vim81 installed in `/usr/share/vim/vim81`, but I compiled a vim82 in `$HOME/.local/share/vim/vim82`. I followed what @chrisbra said with `export VIMRUNTIME=$HOME/.local/share/vim/vim82`, but that does not solves the pb. 
I still see in the error above, that system still tries to get `syncolor.vim` from /usr folder… is there a link ?!
I need your help to resolve this. 

I can precise that I do not have root access, that is why I need to install it in `.local` folder.

**Comment by SKOHscripts** [comment]
You’re right, the rtp says : 
```
runtimepath=/usr/share/vim/vim81, …
```
("…" being all installed plugins)
But I did `export RUNTIMEPATH=~/.local/share/vim/vim82`, so I don’t understand why this is overrided

**Comment by chrisbra** [comment]
you should use `$VIMRUNTIME`

**Comment by SKOHscripts** [comment]
> you should use `$VIMRUNTIME`

mea culpa, what I did is `export VIMRUNTIME=$HOME/.local/share/vim/vim82`, not "runtimepath"
To resume:
I have a `/usr/share/vim/vim81` and a `~/.local/share/vim/vim82` freshly maked and make installed.
With `~/.local` I have colors importation pb. 
So I use `export VIMRUNTIME=$HOME/.local/share/vim/vim82`
Pb is still here and `set rtp?` says `runtimepath=/usr/share/vim/vim81, …`

**Comment by chrisbra** [comment]
hard to guess. try with a clean shell session (so you don't have any references to environment variables lying around). Make sure you run the self-compiled binary using `vim --clean`. I don't know why it wouldn't work for you otherwise, you'll have to find out.

BTW: 
- why are you compiling vim81 and not latest master?
- why did you not use `make install` ?

**Comment by SKOHscripts** [comment]
I'm not clear
I'm in a Debian10 environment, so I have the latest version of the vim package available (8.1). That's why I want to create a new vim installation (8.2 is enough for me, that's why I chose it). 

So I did :
```bash
./configure --prefix=$HOME/.local
make && make install
```

All went well. I switched to a new terminal session and my PATH is: `/usr/local/bin:/usr/bin:/bin:/home/h78681/.local/bin`
So normally the local bin should override. 
I then do: `export VIMRUNTIME=$HOME/.local/share/vim/vim82`
and vim continues to return an error on `colors/lists/default.vim`. 
Especially as set rtp? returns `runtimepath=/usr/share/vim/vim81, ...`
and I'd expect to see `runtimepath=$HOME/.local/share/vim/vim82, ...`

I'll keep investigating, but it's hard to find, as I don't grasp all the internal interactions and dependencies.

**Comment by k-takata** [comment]
Also try `:verbose set rtp?` to see where it is set.

**Comment by SKOHscripts** [comment]
It is set for the last time in : `/usr/share/vim/vim81/macros/matchit.vim`

**Comment by k-takata** [comment]
> and my PATH is: `/usr/local/bin:/usr/bin:/bin:/home/h78681/.local/bin`

Then, your self-compiled vim has the lower priority than the system vim.
* Check `type -a vim` and make sure that your self-compiled vim is loaded.
* Execute vim with `vim --clean`.
* Check `:ver`.

**Comment by SKOHscripts** [comment]
Ok found it ! 
I had a line in my vimrc that was looking for a vimxx folder in my root folder, to add it to the runtimepath… As I had both ~/.local and /usr installation, /usr was used. 
So I had this bite in my vimrc to prefer ~/.local installation if it exists and get the latest installation : 
```vim
"Get the name of the folder starting with "vim" in "~/.local/share/vim".
let local_vim_folders = systemlist('ls ~/.local/share/vim | grep "^vim[0-9]\{2\}$"')
"Choose the folder with the largest numeric suffix
let max_local_vim_suffix = 0
let preferred_local_vim_folder = ''
for folder in local_vim_folders
    let suffix = matchstr(folder, '\d\+$')
    if str2nr(suffix) > max_local_vim_suffix
        let max_local_vim_suffix = str2nr(suffix)
        let preferred_local_vim_folder = folder
    endif
endfor
"Define the runtimepath according to the folder selected in ~/.local/share/vim
if !empty(preferred_local_vim_folder)
  let local_vim_path = '~/.local/share/vim/' . fnameescape(preferred_local_vim_folder)
  execute 'set runtimepath+=' . local_vim_path
else
  let usr_vim_path = substitute(system('ls /usr/share/vim | grep "^vim[0-9]\{2\}$"'), '\n', '', '')
  if !empty(usr_vim_path)
    execute 'set runtimepath+=' . '/usr/share/vim/' . fnameescape(usr_vim_path)
  endif
endif
```

**Comment by chrisbra** [comment]
Now you know, why we suggested the use of `vim --clean`.
