### ISSUE TITLE
Vim9: cannot stop execution before buggy :for command in debug mode

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9456]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        def Func()
            eval 0 + 0
            for [a, b] in [0]
            endfor
        enddef
        breakadd func Func
        Func()
    EOF
    )

Execute the `>next` debugging command to step over `:eval 0 + 0`, and stop execution right before the `:for` command.

`E1140` is given:

    E1140: :for argument must be a sequence of lists

**Expected behavior**

No error is given, because the execution stops right before the `:for` command.

**Version of Vim**

8.2 Included patches: 1-3978

**Environment**

Operating system: Ubuntu 20.04.3 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: zsh 5.8

**Additional Context**

No issue if `Func()` is re-written as a legacy function:
```vim
vim9script
function Func()
    eval 0 + 0
    for [a, b] in [0]
    endfor
endfunction
breakadd func Func
Func()
```
    # execute >next
    # execution stops before :for

---

To be clear: the issue is not the given error.  The error is expected.  What is not expected is that we can't  stop execution right before the problematic command.  This is an issue if we want to inspect the result of the previous command.  Suppose `eval 0 + 0` is replaced with `var name = SomeOtherFunc()`, and we want to inspect the value of `name`.  We can't.

**Comment by brammool** [comment]
> **Steps to reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(tee <<'EOF'
>         vim9script
>         def Func()
>             eval 0 + 0
>             for [a, b] in [0]
>             endfor
>         enddef
>         breakadd func Func
>         Func()
>     EOF
>     )
> 
> Execute the `>next` debugging command to step over `:eval 0 + 0`, and
> stop execution right before the `:for` command.
> 
> `E1140` is given:
> 
>     E1140: :for argument must be a sequence of lists
> 
> **Expected behavior**
> 
> No error is given, because the execution stops right before the `:for`
> command.

Currently the place where debug stops is after assigning the next value
to the loop variable.  But that means there is no stop before the
expression is evaluated.  And not when coming back to "for" just before
finishing.

Let's add another debug stop before even evaluating the expression, and
move the other one up, before deciding to use the next item or finish.
That does mean it will stop there twice the first round, but it does do
two things.
The loop variable can be inspected before the next instruction is
executed.

Note that you can use "disassemble debug Func" to see where it stops.


-- 
hundred-and-one symptoms of being an internet addict:
190. You quickly hand over your wallet, leather jacket, and car keys
     during a mugging, then proceed to beat the crap out of your
     assailant when he asks for your laptop.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
