### ISSUE TITLE
inconsistent parsing of negative count for user-defined command

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9457]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE +'command -count -addr=other Cmd echo <count>' +'-1 Cmd'

`0` is output:

    0

Run this other shell command:

    vim -Nu NONE +'command -count -addr=other Cmd echo <count>' +'Cmd -1'

`E488` is given:

    E488: Trailing characters: -1: Cmd -1

**Expected behavior**

Not sure.  To be consistent, either the first command should give an error, like the second one; or the second command should work, like the first one.

**Version of Vim**

8.2 Included patches: 1-3978

**Environment**

Operating system: Ubuntu 20.04.3 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: zsh 5.8

**Additional Context**

Same results if we replace `-count` with `-range`:

    vim -Nu NONE +'command -range -addr=other Cmd echo <count>' +'-1 Cmd'
    0

    vim -Nu NONE +'command -range -addr=other Cmd echo <count>' +'Cmd -1'
    E488: Trailing characters: -1: Cmd -1

---

I can't find where it's documented that:

   - a negative count is subtracted from the current line address, even when we use the `-addr=other` attribute
   - an error is meant to be given if the result is negative
   - no error is meant to be given if the result is 0 (which is weird, because there can't be any line with the address 0)

So, even if the current issue is not a bug, we might want to improve the help in that regard.  I'll try to send a patch later.

**Comment by lacygoill** [comment]
> To be consistent, either the first command should give an error, like the second one; or the second command should work, like the first one.

Because the only difference between the 2 commands is the position of the count relative to the command name.

**Comment by brammool** [comment]
> **Steps to reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE +'command -count -addr=other Cmd echo <count>' +'-1 Cmd'
> 
> `0` is output:
> 
>     0
> 
> Run this other shell command:
> 
>     vim -Nu NONE +'command -count -addr=other Cmd echo <count>' +'Cmd -1'
> 
> `E488` is given:
> 
>     E488: Trailing characters: -1: Cmd -1
> 
> **Expected behavior**
> 
> Not sure.  To be consistent, either the first command should give an error, like the second one; or the second command should work, like the first one.
> 
> **Version of Vim**
> 
> 8.2 Included patches: 1-3978
> 
> **Environment**
> 
> Operating system: Ubuntu 20.04.3 LTS
> Terminal: xterm
> Value of $TERM: xterm-256color
> Shell: zsh 5.8
> 
> **Additional Context**
> 
> Same results if we replace `-count` with `-range`:
> 
>     vim -Nu NONE +'command -range -addr=other Cmd echo <count>' +'-1 Cmd'
>     0
> 
>     vim -Nu NONE +'command -range -addr=other Cmd echo <count>' +'Cmd -1'
>     E488: Trailing characters: -1: Cmd -1
> 
> ---
> 
> I can't find where it's documented that:
> 
>    - a negative count is subtracted from the current line address, even when we use `-addr=other` attribute
>    - an error is meant to be given if the result is negative
>    - no error is meant to be given if the result is 0 (which is weird, because there can't be any line with the address 0)
> 
> So, even if the current issue is not a bug, we might want to improve the help in that regard.  I'll try to send a patch 

The "-count" argument to a user command basically uses the existing
mechanism to pass a count to an Ex command.  This is coming from Vi, and
the rules are a bit strange.  Being backwards compatible is more
important here than to try and create better rules.

This is documented at the help for :range.  I think the only thing
missing there that if you use "+' or '-' without anything preceding,
then the current line is used.  Thus "2" is different from "+2", 
hopefully it is obvious this means ".+2".  However, this also means that
"-2" means ".-2", which is less obvious, the meaning of '-' is
ambiguous: negate the number or subtract from the previous number (which
is the current line if there is nothing).

A count following a command can only be positive.  It's not explicitly
mentioned, but it's implied in that it is intended for a number of lines.

-- 
hundred-and-one symptoms of being an internet addict:
192. Your boss asks you to "go fer" coffee and you come up with 235 FTP sites.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> This is coming from Vi, and
> the rules are a bit strange.  Being backwards compatible is more
> important here than to try and create better rules.

Understood.

Here is another pitfall we might want to document:
```vim
command -count -nargs=+ Test echo printf("count: %s\n<lt>q-args>: %s", <count>, <q-args>)
:12 Test 34abc
```
    count: 34
    <q-args>: abc

A count given in the prefix position might be ignored if the command is followed by an argument which starts with a number.
