### ISSUE TITLE
Session script is unable to restore "help" buffers properly

### ISSUE THREAD

**Issue by matveyt** [vim/vim#9458]
### Steps to reproduce

```
$vim --clean

:help
:setlocal filetype? buftype? modifiable?
"  filetype=help
"  buftype=help
"  nomodifiable
:set sessionoptions=blank,help  "no 'options'
:mksession!
:bdelete  "make sure help buffer is not reused
:source Session.vim
:setlocal filetype? buftype? modifiable?
"  filetype=help
"  buftype=
"  modifiable
```

### Expected behaviour

I expect Session script to setup essential "help-related" options even if `&ssop` does not contain `options` value. Without setting `&buftype` tag jumps won't work, `&modifiable` could allow for accidental file change and so on.

The problem is that some of "help" options are normally set by https://github.com/vim/vim/blob/b3bd1d39e68e2d697c014b9f85482c2c12a3f909/src/help.c#L637 that is only called by `:help` command. While Session script does `:edit` only.

At first it seems promising to move all the settings under `$VIMRUNTIME/ftplugin/help.vim`, 'cause it exists anyway, but that could fail miserably if `:filetype plugin off` (was this the main reason for having `prepare_help_buffer()` separate from `ftplugin` subsystem?).

I also considered modifying session script to write `"help " . gettagstack().items[-1].tagname` instead. But this could lead to adding a feature like `:current help` or `:help ++curwin` to comply with session script logic.

### Version of Vim

Any

### Environment

Any

**Comment by brammool** [comment]
This appears to be a chicken-egg problem: A help buffer is recognized by the 'buftype' option having the "help" value.  Without that Vim doesn't recognize the file as a help file.  So, just include "options" in 'sessionoptions' and it will be OK.

**Comment by matveyt** [comment]
`options` apply to all buffers and all options, not just `help`. Also, it is nowhere said that `set ssop+=help` de facto requires `set ssop+=options` "to make it finally working". And it can be confusing, isn't it?

So I guess the solution could be to save the relevant options for "help" buffer even if `&ssop` doesn't contain `options`. Probably not ideal, as we'll end up having the same list of options in two different places, but still...
