### ISSUE TITLE
`ml_get: invalid lnum` when redrawing with visual selection active

### ISSUE THREAD

**Issue by seandewar** [vim/vim#9479]
### Steps to reproduce

```vim
call setline(1, ['a', 'b'])
new | wincmd p
call feedkeys("G\<C-V>", 'txn')
call win_execute(winnr('#')->win_getid(), 'redraw')
```

When switching to the new buffer which is being viewed by the previous window in this example, the global visual selection state still refers to the selected range in the original buffer, which is out-of-bounds for the new buffer.

While this example uses `win_execute`, maybe this is also possible in places that use `aucmd_prepbuf`, for example? (like with Neovim's `nvim_buf_call`: https://github.com/neovim/neovim/issues/16937)

### Expected behaviour

No error (visual selection in original buffer should also remain unchanged).

### Version of Vim

8.2.4014

### Environment

OS: Fedora 35
Term: GNOME Terminal 3.42.2
$TERM: `xterm-256color`

### Logs and stack traces

```shell
E315: ml_get: invalid lnum: 2
```

**Comment by lacygoill** [comment]
Backtrace:

    Starting program: /home/lgc/Vcs/vim/src/vim -Nu NONE -S /tmp/t.vim
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

    Program received signal SIGABRT, Aborted.
    __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
    50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
    #0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
    #1  0x00007ffff6f55859 in __GI_abort () at abort.c:79
    #2  0x000055555589ffad in siemsg (s=0x555555953060 <e_ml_get_invalid_lnum_nr> "E315: ml_get: invalid lnum: %ld")
        at message.c:865
    #3  0x00005555556afde9 in ml_get_buf (buf=0x5555559e2ad0, lnum=2, will_change=0) at memline.c:2618
    #4  0x0000555555892d02 in getvcol
        (wp=0x5555559df250, pos=0x55555596c410 <VIsual>, start=0x7fffffff7ffc, cursor=0x0, end=0x7fffffff8004)
        at charset.c:1238
    #5  0x0000555555893318 in getvvcol
        (wp=0x5555559df250, pos=0x55555596c410 <VIsual>, start=0x7fffffff7ffc, cursor=0x0, end=0x7fffffff8004)
        at charset.c:1424
    #6  0x000055555589344c in getvcols
        (wp=0x5555559df250, pos1=0x55555596c410 <VIsual>, pos2=0x5555559df288, left=0x7fffffff8034, right=0x7fffffff8038)
        at charset.c:1449
    #7  0x00005555555e60a5 in win_update (wp=0x5555559df250) at drawscreen.c:2020
    #8  0x00005555555e2094 in update_screen (type_arg=20) at drawscreen.c:317
    #9  0x00005555556369b3 in ex_redraw (eap=0x7fffffff8280) at ex_docmd.c:8191
    #10 0x000055555562b996 in do_one_cmd (cmdlinep=0x7fffffff84b0, flags=11, cstack=0x7fffffff8590, fgetline=
        0x0, cookie=0x0) at ex_docmd.c:2570
    #11 0x0000555555628bbc in do_cmdline (cmdline=0x5555559e7090 "redraw", fgetline=0x0, cookie=0x0, flags=11)
        at ex_docmd.c:993
    #12 0x0000555555628047 in do_cmdline_cmd (cmd=0x5555559e7090 "redraw") at ex_docmd.c:587
    #13 0x0000555555604ff0 in execute_common (argvars=0x7fffffffb100, rettv=0x7fffffffb2e0, arg_off=1) at evalfunc.c:3670
    #14 0x000055555561ab2a in f_win_execute (argvars=0x7fffffffb100, rettv=0x7fffffffb2e0) at evalwindow.c:733
    #15 0x0000555555602e95 in call_internal_func
        (name=0x5555559e70b0 "win_execute", argcount=2, argvars=0x7fffffffb100, rettv=0x7fffffffb2e0) at evalfunc.c:2689
    #16 0x00005555557ff45f in call_func
        (funcname=0x5555559e2ab0 "win_execute", len=-1, rettv=0x7fffffffb2e0, argcount_in=2, argvars_in=0x7fffffffb100, funcexe=0x7fffffffb310) at userfunc.c:3489
    #17 0x00005555557fb9c1 in get_func_tv
        (name=0x5555559e2ab0 "win_execute", len=-1, rettv=0x7fffffffb2e0, arg=0x7fffffffb2a8, evalarg=0x7fffffffb360, funcexe=0x7fffffffb310) at userfunc.c:1788
    #18 0x000055555580367d in ex_call (eap=0x7fffffffb4a0) at userfunc.c:5216
    #19 0x000055555562b996 in do_one_cmd (cmdlinep=0x7fffffffb6d0, flags=7, cstack=0x7fffffffb7b0, fgetline=
        0x55555576789e <getsourceline>, cookie=0x7fffffffbf00) at ex_docmd.c:2570
    #20 0x0000555555628bbc in do_cmdline (cmdline=0x555555977eb0 "call setline(1, ['a', 'b'])", fgetline=
        0x55555576789e <getsourceline>, cookie=0x7fffffffbf00, flags=7) at ex_docmd.c:993
    #21 0x0000555555766e80 in do_source (fname=0x5555559923d3 "/tmp/t.vim", check_other=0, is_vimrc=0, ret_sid=0x0)
        at scriptfile.c:1423
    #22 0x00005555557660b5 in cmd_source (fname=0x5555559923d3 "/tmp/t.vim", eap=0x7fffffffc070) at scriptfile.c:985
    #23 0x0000555555766193 in ex_source (eap=0x7fffffffc070) at scriptfile.c:1011
    #24 0x000055555562b996 in do_one_cmd (cmdlinep=0x7fffffffc2a0, flags=11, cstack=0x7fffffffc380, fgetline=
        0x0, cookie=0x0) at ex_docmd.c:2570
    #25 0x0000555555628bbc in do_cmdline (cmdline=0x55555598b080 "so /tmp/t.vim", fgetline=0x0, cookie=0x0, flags=11)
        at ex_docmd.c:993
    #26 0x0000555555628047 in do_cmdline_cmd (cmd=0x55555598b080 "so /tmp/t.vim") at ex_docmd.c:587
    #27 0x000055555589b695 in exe_commands (parmp=0x55555596a020 <params>) at main.c:3080
    #28 0x0000555555897f02 in vim_main2 () at main.c:774
    #29 0x00005555558977c1 in main (argc=5, argv=0x7fffffffcb88) at main.c:426

Valgrind log:

    ==27295== Memcheck, a memory error detector
    ==27295== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
    ==27295== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
    ==27295== Command: ./src/vim -Nu NONE -S /tmp/t.vim
    ==27295== Parent PID: 9076
    ==27295== 
    ==27295== 
    ==27295== Process terminating with default action of signal 6 (SIGABRT)
    ==27295==    at 0x573555B: kill (syscall-template.S:78)
    ==27295==    by 0x2B248A: may_core_dump (os_unix.c:3502)
    ==27295==    by 0x2B2425: mch_exit (os_unix.c:3468)
    ==27295==    by 0x44E650: getout (main.c:1710)
    ==27295==    by 0x2731D7: preserve_exit (misc1.c:2194)
    ==27295==    by 0x2AFA3A: deathtrap (os_unix.c:1155)
    ==27295==    by 0x573520F: ??? (in /usr/lib/x86_64-linux-gnu/libc-2.31.so)
    ==27295==    by 0x573518A: __libc_signal_restore_set (internal-signals.h:86)
    ==27295==    by 0x573518A: raise (raise.c:48)
    ==27295==    by 0x5714858: abort (abort.c:79)
    ==27295==    by 0x4553DB: siemsg (message.c:865)
    ==27295==    by 0x264782: ml_get_buf (memline.c:2618)
    ==27295==    by 0x448130: getvcol (charset.c:1238)
    ==27295==    by 0x448746: getvvcol (charset.c:1424)
    ==27295==    by 0x44887A: getvcols (charset.c:1449)
    ==27295==    by 0x19A5BF: win_update (drawscreen.c:2020)
    ==27295==    by 0x1965AE: update_screen (drawscreen.c:317)
    ==27295==    by 0x1EB0CA: ex_redraw (ex_docmd.c:8191)
    ==27295==    by 0x1E0056: do_one_cmd (ex_docmd.c:2570)
    ==27295==    by 0x1DD27C: do_cmdline (ex_docmd.c:993)
    ==27295==    by 0x1DC707: do_cmdline_cmd (ex_docmd.c:587)
    ==27295==    by 0x1B9569: execute_common (evalfunc.c:3670)
    ==27295==    by 0x1CF1B6: f_win_execute (evalwindow.c:733)
    ==27295==    by 0x1B740E: call_internal_func (evalfunc.c:2689)
    ==27295==    by 0x3B46C7: call_func (userfunc.c:3489)
    ==27295==    by 0x3B09FE: get_func_tv (userfunc.c:1788)
    ==27295==    by 0x3B88EF: ex_call (userfunc.c:5216)
    ==27295==    by 0x1E0056: do_one_cmd (ex_docmd.c:2570)
    ==27295==    by 0x1DD27C: do_cmdline (ex_docmd.c:993)
    ==27295==    by 0x31BBF0: do_source (scriptfile.c:1423)
    ==27295==    by 0x31AE25: cmd_source (scriptfile.c:985)
    ==27295==    by 0x31AF03: ex_source (scriptfile.c:1011)
    ==27295==    by 0x1E0056: do_one_cmd (ex_docmd.c:2570)
    ==27295==    by 0x1DD27C: do_cmdline (ex_docmd.c:993)
    ==27295==    by 0x1DC707: do_cmdline_cmd (ex_docmd.c:587)
    ==27295==    by 0x450AC3: exe_commands (main.c:3080)
    ==27295==    by 0x44D330: vim_main2 (main.c:774)
    ==27295==    by 0x44CBEF: main (main.c:426)
    ==27295== 
    ==27295== HEAP SUMMARY:
    ==27295==     in use at exit: 722,364 bytes in 3,380 blocks
    ==27295==   total heap usage: 5,380 allocs, 2,000 frees, 1,409,724 bytes allocated

**Comment by seandewar** [comment]
Even after this fix it's still possible to get this error:

```vim
call setline(1, ['a', 'b'])
new | wincmd p
call feedkeys("G\<C-V>", 'txn')
call win_execute(winnr('#')->win_getid(), 'redraw')
```

We can instead make a visual selection in the new buffer thats out-of-bounds for the original buffer.

**Comment by seandewar** [comment]
Sorry, I pasted the wrong snippet just then. Here's the correct snippet in case it's wrong in the automated e-mail:

```vim
enew | new
call setline(1, ['a', 'b'])
wincmd p
call feedkeys("\<C-V>", 'txn')
call win_execute(winnr('#')->win_getid(), 'call feedkeys("G\<C-V>", ''txn'')')
```

**Comment by seandewar** [comment]
> While this example uses win_execute, maybe this is also possible in places that use aucmd_prepbuf, for example?

Seems this is also a problem:

```vim
call setline(1, ['a', 'b'])
new | wincmd p
call feedkeys("G\<C-V>", 'txn')
autocmd User Explode ++once redraw
doautoall User Explode
```

**Comment by lacygoill** [comment]
For the first snippet:

Backtrace:

    #0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
    #1  0x00007ffff6f55859 in __GI_abort () at abort.c:79
    #2  0x000055555589ff96 in siemsg (s=0x555555953080 <e_ml_get_invalid_lnum_nr> "E315: ml_get: invalid lnum: %ld")
        at message.c:865
    #3  0x00005555556afdd9 in ml_get_buf (buf=0x5555559859a0, lnum=2, will_change=0) at memline.c:2618
    #4  0x0000555555892ceb in getvcol
        (wp=0x555555983270, pos=0x55555596c430 <VIsual>, start=0x7fffffffc76c, cursor=0x0, end=0x7fffffffc774)
        at charset.c:1238
    #5  0x0000555555893301 in getvvcol
        (wp=0x555555983270, pos=0x55555596c430 <VIsual>, start=0x7fffffffc76c, cursor=0x0, end=0x7fffffffc774)
        at charset.c:1424
    #6  0x0000555555893435 in getvcols
        (wp=0x555555983270, pos1=0x55555596c430 <VIsual>, pos2=0x5555559832a8, left=0x7fffffffc7a4, right=0x7fffffffc7a8)
        at charset.c:1449
    #7  0x00005555555e60a5 in win_update (wp=0x555555983270) at drawscreen.c:2020
    #8  0x00005555555e2094 in update_screen (type_arg=20) at drawscreen.c:317
    #9  0x00005555555e32df in update_curbuf (type=20) at drawscreen.c:845
    #10 0x0000555555898b7b in main_loop (cmdwin=0, noexmode=0) at main.c:1388
    #11 0x00005555558980b5 in vim_main2 () at main.c:879
    #12 0x00005555558977aa in main (argc=5, argv=0x7fffffffcb88) at main.c:426

[Valgrind log](https://github.com/vim/vim/files/7823724/valgrind.log)

---

For the second snippet:

Backtrace:

    #0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
    #1  0x00007ffff6f55859 in __GI_abort () at abort.c:79
    #2  0x000055555589ff96 in siemsg (s=0x555555953080 <e_ml_get_invalid_lnum_nr> "E315: ml_get: invalid lnum: %ld")
        at message.c:865
    #3  0x00005555556afdd9 in ml_get_buf (buf=0x5555559ec190, lnum=2, will_change=0) at memline.c:2618
    #4  0x0000555555892ceb in getvcol
        (wp=0x5555559e8990, pos=0x55555596c430 <VIsual>, start=0x7fffffffa58c, cursor=0x0, end=0x7fffffffa594)
        at charset.c:1238
    #5  0x0000555555893301 in getvvcol
        (wp=0x5555559e8990, pos=0x55555596c430 <VIsual>, start=0x7fffffffa58c, cursor=0x0, end=0x7fffffffa594)
        at charset.c:1424
    #6  0x0000555555893435 in getvcols
        (wp=0x5555559e8990, pos1=0x55555596c430 <VIsual>, pos2=0x5555559e89c8, left=0x7fffffffa5c4, right=0x7fffffffa5c8)
        at charset.c:1449
    #7  0x00005555555e60a5 in win_update (wp=0x5555559e8990) at drawscreen.c:2020
    #8  0x00005555555e2094 in update_screen (type_arg=20) at drawscreen.c:317
    #9  0x00005555556369a3 in ex_redraw (eap=0x7fffffffa810) at ex_docmd.c:8191
    #10 0x000055555562b986 in do_one_cmd (cmdlinep=0x7fffffffaa40, flags=7, cstack=0x7fffffffab20, fgetline=
        0x5555555a034e <getnextac>, cookie=0x7fffffffb270) at ex_docmd.c:2570
    #11 0x0000555555628bac in do_cmdline (cmdline=0x0, fgetline=
        0x5555555a034e <getnextac>, cookie=0x7fffffffb270, flags=7) at ex_docmd.c:993
    #12 0x000055555559fca9 in apply_autocmds_group
        (event=EVENT_USER, fname=0x5555559e4b70 "/home/lgc/Vcs/vim/Explode", fname_io=0x0, force=1, group=-3, buf=0x5555559ec190, eap=0x0) at autocmd.c:2181
    #13 0x000055555559e963 in do_doautocmd
        (arg_start=0x5555559e4c2a "User Explode", do_msg=0, did_something=0x7fffffffb394) at autocmd.c:1349
    #14 0x000055555559eacf in ex_doautoall (eap=0x7fffffffb4a0) at autocmd.c:1400
    #15 0x000055555562b986 in do_one_cmd (cmdlinep=0x7fffffffb6d0, flags=7, cstack=0x7fffffffb7b0, fgetline=
        0x55555576788e <getsourceline>, cookie=0x7fffffffbf00) at ex_docmd.c:2570
    #16 0x0000555555628bac in do_cmdline (cmdline=0x555555977eb0 "call setline(1, ['a', 'b'])", fgetline=
        0x55555576788e <getsourceline>, cookie=0x7fffffffbf00, flags=7) at ex_docmd.c:993
    #17 0x0000555555766e70 in do_source (fname=0x5555559923d3 "/tmp/u.vim", check_other=0, is_vimrc=0, ret_sid=0x0)
        at scriptfile.c:1423
    #18 0x00005555557660a5 in cmd_source (fname=0x5555559923d3 "/tmp/u.vim", eap=0x7fffffffc070) at scriptfile.c:985
    #19 0x0000555555766183 in ex_source (eap=0x7fffffffc070) at scriptfile.c:1011
    #20 0x000055555562b986 in do_one_cmd (cmdlinep=0x7fffffffc2a0, flags=11, cstack=0x7fffffffc380, fgetline=
        0x0, cookie=0x0) at ex_docmd.c:2570
    #21 0x0000555555628bac in do_cmdline (cmdline=0x55555598b080 "so /tmp/u.vim", fgetline=0x0, cookie=0x0, flags=11)
        at ex_docmd.c:993
    #22 0x0000555555628037 in do_cmdline_cmd (cmd=0x55555598b080 "so /tmp/u.vim") at ex_docmd.c:587
    #23 0x000055555589b67e in exe_commands (parmp=0x55555596a040 <params>) at main.c:3080
    #24 0x0000555555897eeb in vim_main2 () at main.c:774
    #25 0x00005555558977aa in main (argc=5, argv=0x7fffffffcb88) at main.c:426

[Valgrind log](https://github.com/vim/vim/files/7823725/valgrind.log)
