### ISSUE TITLE
Vim9: unexpected error when timer callback executed in debug mode

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9481]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        def Outer()
            def Inner()
            enddef
            timer_start(1'000, (_) => Inner(), {repeat: -1})
        enddef
        Outer()
        def Func()
            eval 1 + 1
            eval 2 + 2
        enddef
        breakadd func Func
        Func()
    EOF
    )

Execute the `>next` debugging command, and wait up to 1 second.

`E117` and `E1091` are given:

    E117: Unknown function: Inner
    E1091: Function is not compiled: <lambda>2

**Expected behavior**

No error is given.

**Version of Vim**

8.2 Included patches: 1-4018

**Environment**

Operating system: Ubuntu 20.04.3 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: zsh 5.8

**Additional Context**

No error is given if `Outer()` is re-written as a legacy function:
```vim
vim9script
function Outer()
    def Inner()
    enddef
    vim9cmd timer_start(1'000, (_) => Inner(), {repeat: -1})
endfunction
Outer()
def Func()
    eval 1 + 1
    eval 2 + 2
enddef
breakadd func Func
Func()
```

**Comment by brammool** [comment]
A timer callback may cause any kind of trouble while stepping through Vim code.
I think the best is to disable timers while at the debug prompt.
I'll make that happen, check if anything else breaks then.
