### ISSUE TITLE
Vim9: cannot import from vimrc

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9484]
**Steps to reproduce**

Run these 5 shell commands:

    rm -rf /tmp/home

    mkdir -p /tmp/home/.vim/plugin/

    tee <<'EOF' >/tmp/home/.vim/vimrc
        vim9script
        export def Func()
            echomsg 'from imported function'
        enddef
    EOF

    tee <<'EOF' >/tmp/home/.vim/plugin/foo.vim
        vim9script
        import $MYVIMRC
        vimrc.Func()
    EOF

    HOME=/tmp/home vim

`E1257` is given:

    E1257: Imported script must end in .vim: vimrc

**Expected behavior**

No error is given.  `from imported function` is echo'ed.

**Version of Vim**

8.2 Included patches: 1-4023

**Environment**

Operating system: Ubuntu 20.04.3 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: zsh 5.8

**Additional Context**

*If* this is considered as a bug, then it's a regression introduced in [8.2.4019](https://github.com/vim/vim/releases/tag/v8.2.4019).

It was handy to be able to import/export from our vimrc.  Could this feature be restored?

---

If we move the vimrc from `~/.vim/vimrc` to `~/.vimrc`, `:import` no longer gives any error.  But nothing is imported, which is why `vimrc.Func()` gives `E121`:

    rm -rf /tmp/home

    mkdir -p /tmp/home/.vim/plugin/

    tee <<'EOF' >/tmp/home/.vimrc
        vim9script
        export def Func()
            echomsg 'from imported function'
        enddef
    EOF

    tee <<'EOF' >/tmp/home/.vim/plugin/foo.vim
        vim9script
        import $MYVIMRC
        vimrc.Func()
    EOF

    HOME=/tmp/home vim

Output:

    E121: Undefined variable: vimrc

This is not OK.  If we don't want to restore the feature, at least we should give an error earlier; that is, as soon as `:import` fails to import any item from the given filepath, no matter where our vimrc is located.

**Comment by brammool** [comment]
Importing ".vimrc" is not a good example, it is very unusual to export things from ".vimrc".

There is an error that ".vimrc" is not flagged as an error, I'll fix that.  Also ".vim" by itself should be an error.

I do encourage people to use the ".vim" extension for plugins .  The current way import works is that it is required when there is no ".vim" extension. You can still use any name if you use the "as name" addition.  I think that is good: the usual case is simple, the unusual case is a bit more work.
