### ISSUE TITLE
Vim9: cannot call imported function from mapping

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9485]
**Steps to reproduce**

Run these 5 shell commands:

    rm -rf /tmp/home

    mkdir -p /tmp/home/.vim/import/

    tee <<'EOF' /tmp/home/.vim/import/script.vim
        vim9script
        export def Bar()
            echomsg 'From Bar()'
        enddef
    EOF

    tee <<'EOF' /tmp/home/.vim/vimrc
        vim9script
        import 'script.vim'
        const Foo = script.Bar
        nnoremap <F3> <Cmd>call <SID>Foo()<CR>
        feedkeys("\<F3>")
    EOF

    HOME=/tmp/home vim

`E117` is given.

    E117: Unknown function: <SNR>1_Foo

**Expected behavior**

No error is given.  `From Bar()` is echo'ed.

**Version of Vim**

8.2 Included patches: 1-4023

**Environment**

Operating system: Ubuntu 20.04.3 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: zsh 5.8

**Additional Context**

Regression introduced in [8.2.4019](https://github.com/vim/vim/releases/tag/v8.2.4019).

**Comment by Shane-XB-Qian** [comment]
yea, cannot import `var` from another vim9 script fs too -since yesterday update/patch.
```E121: Undefined variable: foo```
