### ISSUE TITLE
3 issues in vim9script 'import' after yesterday's refactor

### ISSUE THREAD

**Issue by Shane-XB-Qian** [vim/vim#9490]
### Steps to reproduce

```vim
vim9script

def Test_vim9_reload_noclear()
  var lines =<< trim END
    vim9script
    export var exported = 'thexport'

    export def TheFunc(x = 0)
    enddef
  END
  writefile(lines, 'XExportReload.vim')
  lines =<< trim END
    vim9script noclear
    g:loadCount += 1
    var s:reloaded = 'init'
    # import './XExportReload' as exp      # <---
    import './XExportReload.vim'           # <---

    def Again(): string
      return 'again'
    enddef

    # exp.TheFunc()                        # <---
    echom XExportReload.exported           # <---

    if exists('s:loaded') | finish | endif
    var s:loaded = true

    var s:notReloaded = 'yes'
    s:reloaded = 'first'
    def g:Values(): list<string>
      return [s:reloaded, s:notReloaded, Again(), Once(), exp.exported]
    enddef

    def Once(): string
      return 'once'
    enddef
  END
  writefile(lines, 'XReloaded')
  g:loadCount = 0
  source XReloaded
  assert_equal(1, g:loadCount)
  assert_equal(['first', 'yes', 'again', 'once', 'thexport'], g:Values())      # <---
  source XReloaded
  assert_equal(2, g:loadCount)
  assert_equal(['init', 'yes', 'again', 'once', 'thexport'], g:Values())
  source XReloaded
  assert_equal(3, g:loadCount)
  assert_equal(['init', 'yes', 'again', 'once', 'thexport'], g:Values())

  delete('XReloaded')
  delete('XExportReload.vim')
  # delfunc g:Values                 # <--- would raised err 'no g:Values' func IF not commented out IF to do second 'source' this
  unlet g:loadCount
enddef

Test_vim9_reload_noclear()
```

### Expected behaviour

1, if sourced this at second time (if `delfunc g:Values` was not comment out`), would raise err 'no func g:Values'.
// is that expected? looks g:Values was not re-defined at second 'source'.

2, before the day before yesterday, it call `exported` that imported 'var' directly, but now it had to be `exp.exported` or `XExportReload.exported` (as well as 'func' case).
// not sure should be or not, but looks this is a bit un-compatible, existing vim9 scripts/plugins had to add such 'prefix'.

3, `E1257: Imported script must use "as" or end in .vim: XExportReload`
// my broken english but perhaps `end *with* .vim` (or the extension must be '.vim') maybe more understandable. :-)

### Version of Vim

v8.2.4036

### Environment

linux

### Logs and stack traces

```shell
#9484
#9485
```

**Comment by brammool** [comment]
I am not quite sure what you did and what you have problems with.

As the script is given it won't work, because this line is commented
out:

	 # import './XExportReload' as exp

But "exp.exported" is used.  "exp" will not be defined.

It is a change in behavior, Vim9 scripts that used import will have to
be changed.

Loading a second time is expected to give different behavior, since the
"s:loaded" variable exists and "finish" is invoked.

-- 
hundred-and-one symptoms of being an internet addict:
255. You work for a newspaper and your editor asks you to write an
     article about Internet addiction...in the "first person."

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Shane-XB-Qian** [comment]
> I am not quite sure what you did and what you have problems with.

pls try following demo code, perhaps a bit more clear..
// for the second issue:
pls check those `case_1` and `case_2` and `case_3` in following code, before the day before yesterday, `case_3` worked, but now looks only `case_1` and `case_2` works. this is a bit un-compatible, IF this had to be changed, then some existing vim9script had to be re-factor too.............. 

```vim
vim9script

def Test_vim9_reload_noclear()
  var lines =<< trim END
    vim9script
    export var exported = 'thexport'

    export def TheFunc(x = 0)
    enddef
  END
  writefile(lines, 'XExportReload.vim')
  lines =<< trim END
    vim9script noclear
    g:loadCount += 1
    var s:reloaded = 'init'
    # # import './XExportReload' as exp           # <---
    # import './XExportReload.vim' as exp         # <---
    # import './XExportReload.vim'                # <---
    import exported from './XExportReload.vim'    # <---

    def Again(): string
      return 'again'
    enddef

    # exp.TheFunc()                        # <--- case_1
    # echom XExportReload.exported         # <--- case_2
    echom exported                         # <--- case_3

    if exists('s:loaded') | finish | endif
    var s:loaded = true

    var s:notReloaded = 'yes'
    s:reloaded = 'first'
    def g:Values(): list<string>
      # return [s:reloaded, s:notReloaded, Again(), Once(), exp.exported]
      # return [s:reloaded, s:notReloaded, Again(), Once(), XExportReload.exported]
      return [s:reloaded, s:notReloaded, Again(), Once(), exported]
    enddef

    def Once(): string
      return 'once'
    enddef
  END
  writefile(lines, 'XReloaded')
  g:loadCount = 0
  source XReloaded
  assert_equal(1, g:loadCount)
  assert_equal(['first', 'yes', 'again', 'once', 'thexport'], g:Values())      # <---
  source XReloaded
  assert_equal(2, g:loadCount)
  assert_equal(['init', 'yes', 'again', 'once', 'thexport'], g:Values())
  source XReloaded
  assert_equal(3, g:loadCount)
  assert_equal(['init', 'yes', 'again', 'once', 'thexport'], g:Values())

  delete('XReloaded')
  delete('XExportReload.vim')
  # delfunc g:Values                 # <--- would raised err 'no g:Values' func IF not commented out IF to do second 'source' this
  unlet g:loadCount
enddef

Test_vim9_reload_noclear()
```

**Comment by Shane-XB-Qian** [comment]
oh........... my bad, i did not notice that `finish`.
pls ignore the first issue.
// but how about the second issue? had to add such 'prefix'? (would broken some existing ones if so)

**Comment by Shane-XB-Qian** [comment]
i saw you committed new patch (8.2.4044) and updated doc a bit as well,
but `import exported from './XExportReload.vim'` such style 'import' (keyword 'from') still / no longer supported..  :-(

**Comment by Shane-XB-Qian** [comment]
looks this vim9 'import' style change had been made as permanent, so/then let it be..
// and patch 8.2.4063 yesterday helped and fixed a big mess, so ok then... :-)

**Comment by brammool** [comment]
> looks this vim9 'import' style change had been made as permanent,
> so/then let it be..
> // and patch 8.2.4063 yesterday helped and fixed a big mess, so ok then... :-)

I'm still adding some more tests, there might be a couple remaining
problems.  Let me know if you have an example of what doesn't work.

-- 
Microsoft's definition of a boolean: TRUE, FALSE, MAYBE
"Embrace and extend"...?

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Shane-XB-Qian** [comment]
v8.2.4264 revoked the '#' style function name in vim9, but:
1, that made some complex to call such vim9 func in legacy vim script e.g vimrc.
2, that exported func name had to be 'Uppercase' first letter?
```vim
-   func auto9#getsome()
+   export func Getsome()
```
3, in some languages, if that first letter of function name is Uppercase, that means 'public' already, as my understanding, if it do req 'Uppercase' then maybe no req 'export' keyword?!

**Comment by brammool** [comment]
> v8.2.4264 revoked the '#' style function name in vim9, but:
> 1, that made some complex to call such vim9 func in legacy vim script
> e.g vimrc.

I don't see how.  You can still call the autoload function using the #
form.

> 2, that exported func name had to be 'Uppercase' first letter?
> ```vim
> -   func auto9#getsome()
> +   export func Getsome()
> ```

Yes, that is intentional.  In legacy script there was an inconsistency,
allowing lower case function names.  It was OK there since you always
had to prefix "scriptname#".  But in Vim9 script you can call the
function without the prefix inside the script, therefore the leading
capital is required.

> 3, in some languages, if that first letter of function name is
> Uppercase, that means 'public' already, as my understanding, if it do
> req 'Uppercase' then maybe no req 'export' keyword?!

No, we do not do it that way.

-- 
I once paid $12 to peer at the box that held King Tutankhamen's little
bandage-covered midget corpse at the De Young Museum in San Francisco.  I
remember thinking how pleased he'd be about the way things turned out in his
afterlife.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
Hi,

On Tue, Feb 1, 2022 at 8:05 AM Bram Moolenaar ***@***.***>
wrote:

>
> > v8.2.4264 revoked the '#' style function name in vim9, but:
> > 1, that made some complex to call such vim9 func in legacy vim script
> > e.g vimrc.
>
> I don't see how. You can still call the autoload function using the #
> form.
>

The recent changes to disallow the use of '#' in a function name and the
changes to the import mechanism resulted in quite a bit of changes to the
LSP Vim9 plugin.

You can see the impact in the following commits:

https://github.com/yegappan/lsp/commit/aeede042a93441f038f6b36448aaf383969bc86b
https://github.com/yegappan/lsp/commit/d7105d210391ad8fe3733d81f048df7a970b2488

In particular look at the changes to the plugin/lsp.vim. As all the users
may not
have the latest Vim, the plugin needs to support an older version of Vim
and the latest
version. This is difficult.

Regards,
Yegappan


>
> > 2, that exported func name had to be 'Uppercase' first letter?
> > ```vim
> > - func auto9#getsome()
> > + export func Getsome()
> > ```
>
> Yes, that is intentional. In legacy script there was an inconsistency,
> allowing lower case function names. It was OK there since you always
> had to prefix "scriptname#". But in Vim9 script you can call the
> function without the prefix inside the script, therefore the leading
> capital is required.
>
> > 3, in some languages, if that first letter of function name is
> > Uppercase, that means 'public' already, as my understanding, if it do
> > req 'Uppercase' then maybe no req 'export' keyword?!
>
> No, we do not do it that way.
>
>
>

**Comment by vim-ml** [comment]
Yegappan wrote:

> On Tue, Feb 1, 2022 at 8:05 AM Bram Moolenaar ***@***.***>
> wrote:
> 
> > > v8.2.4264 revoked the '#' style function name in vim9, but:
> > > 1, that made some complex to call such vim9 func in legacy vim script
> > > e.g vimrc.
> >
> > I don't see how. You can still call the autoload function using the #
> > form.
> 
> The recent changes to disallow the use of '#' in a function name and the
> changes to the import mechanism resulted in quite a bit of changes to the
> LSP Vim9 plugin.
> 
> You can see the impact in the following commits:
> 
> https://github.com/yegappan/lsp/commit/aeede042a93441f038f6b36448aaf383969bc86b
> https://github.com/yegappan/lsp/commit/d7105d210391ad8fe3733d81f048df7a970b2488
> 
> In particular look at the changes to the plugin/lsp.vim. As all the users
> may not have the latest Vim, the plugin needs to support an older
> version of Vim and the latest version. This is difficult.

The autoload mechanism in Vim9 was introduced only recently.  But I
suppose you were relying on the legacy mechanism.

The change indeed had bigger impact than I anticipated.  But I do think
that it is better in the long run.

So far you could have an autoload function call anywhere, just use
"scriptname#Funcname()".  Although this is convenient, it also hides a
dependency on another script, which must be present for this to work.
Now you need an "import autoload 'scriptname.vim'" and then you can use
"scriptname.Funcname()".  Now the import, thus the dependency, is
explicit.  The cost is an extra line.

There is one loophole though: When using a legacy function it can use
the "scritpname#Funcname()" form, also in a Vim9 script.  Perhaps you
can use that as a temporary workaround?

In a cleanly written Vim9 script you would not define a legacy function.

-- 
If your company is not involved in something called "ISO 9000" you probably
have no idea what it is.  If your company _is_ involved in ISO 9000 then you
definitely have no idea what it is.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Shane-XB-Qian** [comment]
to be honest, i had been some kind confused how to use those:
`s:fooFunc`
`g:FooFunc`
`export def FooFunc`
or `def fooFunc`
or what if was not a func but a var
and what if those in `autoload/` folder
and what if those in `plugin/` folder
and specially what/how if call those vim9 func in legacy vim script..............   :-(
// looks made things a bit complex...

**Comment by lacygoill** [comment]
> So far you could have an autoload function call anywhere, just use
> "scriptname#Funcname()".
> [...]
> Now you need an "import autoload 'scriptname.vim'" and then you can use
> "scriptname.Funcname()".

We can still call an autoload function with `scriptname#Funcname()` from anywhere.
```vim
vim9script
var dir = '/tmp/.vim'
dir->delete('rf')
&runtimepath = dir
dir ..= '/autoload'
dir->mkdir('p')
var lines =<< trim END
    vim9script
    export def Funcname()
        echomsg 'from scriptname#Funcname()'
    enddef
END
lines->writefile(dir .. '/scriptname.vim')
scriptname#Funcname()
```
    from scriptname#Funcname()

Notice that we don't even need `:import autoload`.
And it has to remain allowed, because there are still 6 contexts where we can't use the Vim9 syntax (because the code is run in the global context):

   - `:help i_CTRL-R_=`
   - `:help c_CTRL-\_e`
   - `:help stl-%{`
   - `:help 'statusline'`, and `:help 'tabline'` (`%!Func()`)
   - `:help input()` (third `{completion}` argument)
   - `:help undo_ftplugin`

**Comment by Shane-XB-Qian** [comment]
@brammool :

```vim
call foo#Bar()
call FooBar()     # or `call g:FooBar()`
```

~~looks once if above such func had `s:` scope action or var in it,~~
~~// or it is, e.g `g:Foo = s:abc.Foo`~~
~~then~~ first one is ok when run directly in vimrc (not call in a legacy vim script func),
but second one would be failed (err: not found func).
~~// but looks (or i guess) No Err if no `s:` scope action or var in it, or run it manually when vim had enter done.~~

@yegappan : 
if specific to your lsp plugin, the err happened at LspAddServer(cfg), and LspOptionsSet.

**Comment by vim-ml** [comment]
Hi,

On Thu, Feb 3, 2022 at 8:12 AM Shane-XB-Qian ***@***.***>
wrote:

> @brammool <https://github.com/brammool> :
>
> call foo#Bar()call FooBar()     # or `call g:FooBar()`
>
> looks once if above such func had s: scope action or var in it,
> // or it is, e.g g:Foo = s:abc.Foo
> then first one is ok when run directly in vimrc (not call in a legacy vim
> script func),
> but second one would be failed (err: not found func).
> // but looks (or i guess) No Err if no s: scope action or var in it, or
> run it manually when vim had enter done.
>
> @yegappan <https://github.com/yegappan> :
> if specific to your lsp plugin, the err happened at LspAddServer(cfg), and
> LspOptionsSet.
>
>
> I am not able to reproduce this error. Where are you calling the
LspAddServer() function from?
Are you calling it from a legacy vimrc file or a vim9 vimrc file? Are you
calling it at the script
level or inside a function?

BTW, I have updated the plugin to use a global function instead of a global
funcref variable for
these two functions. Can you update the plugin and try again?

Thanks,
Yegappan

**Comment by Shane-XB-Qian** [comment]
issue happened at legacy vimrc and calling a vim9 global (or Uppercase first letter) func.

as the description, the different is foo#Bar() is ok, but FooBar() was failed,
but they both are ok if manually call it at cmdline (of course vim had been enter at then).

// no chance to try your new update yet, but seems this a vim9 bug (if style kept change) too, which perhaps can be workaround by your new update though.
// coz if i guess correctly, FooBar() style vim9 func had init timing issue which diff like foo#Bar() style?

**Comment by Shane-XB-Qian** [comment]
@yegappan i tried your new update.
the different is from `lspoptions#LspOptionsSet()` to `lspoptions#OptionsSet()` (your new update changed that name).
// so far this is the workaround, which if using `global` style vim9 function then failed.

**Comment by Shane-XB-Qian** [comment]
// so far `#` style (with `Uppercase` first letter -IF compare to legacy `#` style) is the workaround.
// and looks it is a bit complex to make it be compatible if user's vim was not using latest version...

**Comment by Shane-XB-Qian** [comment]
#9967

// closing..
