### ISSUE TITLE
Support for localised command prompts

### ISSUE THREAD

**Issue by bitigchi** [vim/vim#9495]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

There is no support for localised command prompts except for (y)es and (no).

**Describe the solution you'd like**
It would be nice to have localised command prompts to make the text more coherent.

**Comment by brammool** [comment]
> **Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
> 
> There is no support for localised command prompts except for (y)es and (no).
> 
> **Describe the solution you'd like**
> It would be nice to have localised command prompts to make the text more coherent.

Can you give a list of commands and functions that give these prompts
that should be translated?

-- 
hundred-and-one symptoms of being an internet addict:
267. You get an extra phone line so you can get phone calls.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bitigchi** [comment]
I could find four instances of untranslated prompts, here's a list:

**ask_yesno (misc1.c)**
bufwrite.c:537
ops.c:744
undo.c:760

**Custom string**
ex_cmds.c:4301

`vim_dialog_yesnoallcancel, `vim_dialog_yesnocancel`, and `vim_dialog_yesnocancel` seem to provide localised prompts.

**Comment by brammool** [comment]
Looks like this was already done.  If you find one, please quote the line (the line number may change).

**Comment by bitigchi** [comment]
If I'm not mistaken, `ask_yesno` function still seems to use hardcoded `y` and `n` characters for the prompt input, as well as the second one in ex_cmds.c:

`				_("replace with %s (y/n/a/q/l/^E/^Y)?"), sub);`

**Comment by mattn** [comment]
If you just want the translated message,

```vim
:echo gettext("&Yes\n&No")
```
