### ISSUE TITLE
vim9script: error when returning an imported void function

### ISSUE THREAD

**Issue by bfrg** [vim/vim#9497]
### Steps to reproduce

Run `vim --clean -S test.vim` with the following two files:

File `script.vim`:
```vim
vim9script
export def Msg()
    echomsg 'in Msg()...'
enddef
```

File `test.vim`:
```vim
vim9script
import './script.vim'

def Test()
    return script.Msg()
enddef
Test()
```

Result:
```
E1096: Returning a value in a function without a return type
```

---

When the function is not imported, everything works as expected:
```vim
vim9script

def Msg()
    echomsg 'in Msg()...'
enddef

def Test()
    return Msg()
enddef

Test()
```

### Expected behaviour

No errors

### Version of Vim

8.2.4049

### Environment

Linux

**Comment by brammool** [comment]
The bug is in the version without the import, "Msg()" results in void, thus "return Msg()" looks like a mistake.
Technically it may look OK, since "return void" might be considered the same as "return", but a void value is not the same as nothing.

**Comment by bfrg** [comment]
Well, it's valid in C, so I assumed it would also be possible in vim. I prefer the following
```vim
def Test()
    return Msg()
enddef
```
because it's more compact than
```vim
def Test()
    Msg()
    return
enddef
```
For such simple functions the `return` statement is completely redundant but for larger functions with several `if` branches, writing `return Func()` looks cleaner.

And it used to work with the old `import` syntax. That's why I thought it was a bug.

**Comment by brammool** [comment]
> Well, it's valid in C, so I assumed it would also be possible in vim.

The C language suffers from a history of minimal type checking.  It's
not a good example of how type checking should be done.  Many C
compilers have added extra warnings for the many things you can do wrong
even when C allows it.

> I prefer the following
> ```vim
> def Test()
>     return Msg()
> enddef
> ```
> because it's more compact than
> ```vim
> def Test()
>     Msg()
>     return
> enddef
> ```
> For such simple functions the `return` statement is completely
> redundant but for larger functions with several `if` branches, writing
> `return Func()` looks cleaner.
> 
> And it used to work with the old `import` syntax. That's why I thought
> it was a bug.

To me "return Msg()" looks like Msg() returns something that is then
passed on to the return statement.  That is confusing and might hide a
mistake.

It's easy enough to just use "Msg()" in this case.  Or if this is in a
block then indeed add "return" below it.  It's not as compact, but I
don't think that is more important.

-- 
Women are probably the main cause of free software starvation.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
