### ISSUE TITLE
Vim9: make Ex command executed from mapping after <Cmd> be run in context of current script

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9499]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

Mappings are always entirely processed in the global context; never in the context of the script where they are installed.  This can cause problems and inconsistencies.

---

First, it forces us to always write the pseudo-key `<SID>`, whenever we need to call a script-local function from the rhs of a mapping:
```vim
vim9script
def Func()
    echomsg 'from Func()'
enddef
nnoremap <F3> <Cmd>call <SID>Func()<CR>
feedkeys("\<F3>")
```
    from Func()

For a new user, it's not easy to understand what `<SID>` means, nor why it's necessary.
Also, we never *need* `<SID>` anywhere else; neither in a function's header, nor in a user-defined command, nor in an autocmd:
```vim
vim9script
def Func()
    echomsg 'from Func()'
enddef
command Cmd Func()
autocmd CursorHold * Func()
Cmd
doautocmd CursorHold
```
    from Func()
    from Func()

For these reasons, `<SID>` looks weird, which goes against one of the goals of Vim9 script; that is, avoid weird syntaxes:

   > Removing clutter and weirdness ~
   >
   > Once decided that `:def` functions have different syntax than legacy functions,
   > we are free to add improvements to make the code more familiar for users who
   > know popular programming languages.  In other words: remove weird things that
   > only Vim does.

---

Second, when executing an Ex command from the rhs of a mapping, we need to use the legacy syntax even if we're actually writing a Vim9 script.  That's a consequence of a mapping being processed in the global context.

Again, this looks weird.  If I'm writing a Vim9 script, I would expect to be able to use the Vim9 syntax everywhere in the script.  The only case where using the legacy syntax doesn't look weird is after `:legacy`, because this modifier explicitly tells us that we're switching to a different syntax.  In contrast, `:map` doesn't tell us anything in that regard; we have to remember that – implicitly – `:map` switches to the legacy syntax.

---

Third, because of this implicit switch to the legacy syntax, it is more difficult for a Vim9 syntax plugin to correctly highlight an Ex command in the rhs of a mapping.  For example, `:let` is disallowed in Vim9, so it's useful to highlight this command as an error.  But in a mapping, `:let` is actually valid, so the syntax plugin has to make an exception, which makes the syntax rules more complex.  And since there are other differences, it's much easier to give up and not highlight anything in the rhs.

---

Fourth, we currently have no way to tell in which context (legacy vs Vim9) a mapping will actually be processed.  Here are a few examples:
```vim
vim9script
nnoremap <F3> <Cmd>let g:name = 0<CR>
feedkeys("\<F3>")
```
    no error
```vim
vim9script
nnoremap <F3> <Cmd>let g:name = 0<CR>
feedkeys("\<F3>", 'x')
```
    E1126: Cannot use :let in Vim9 script
```vim
vim9script
nnoremap <F3> <Cmd>let g:name = 0<CR>
legacy call feedkeys("\<F3>", 'x')
```
    E1126: Cannot use :let in Vim9 script
```vim
vim9script
nnoremap <F3> <Cmd>let g:name = 0<cr>
function Legacy()
    call feedkeys("\<F3>", 'x')
endfunction
Legacy()
```
    no error

Notice that the mapping is always exactly the same in the four snippets.  And yet, they give different results, which is confusing.

---

Fifth, in a mapping, we can't call an imported function directly:
```vim
vim9script
var dir = '/tmp/import'
dir->mkdir('p')
var lines =<< trim END
    vim9script
    export def Func()
        echomsg 'from Func()'
    enddef
END
lines->writefile(dir .. '/script.vim')
import '/tmp/import/script.vim'
nnoremap <F3> <Cmd>call script.Func()<CR>
feedkeys("\<F3>")
```
    E121: Undefined variable: script

As a result, we have to use an intermediate variable storing a reference to the imported function:
```vim
vim9script
var dir = '/tmp/import'
dir->mkdir('p')
var lines =<< trim END
    vim9script
    export def Func()
        echomsg 'from Func()'
    enddef
END
lines->writefile(dir .. '/script.vim')
import '/tmp/import/script.vim'
const Ref = script.Func
nnoremap <F3> <Cmd>call <SID>Ref()<CR>
feedkeys("\<F3>")
```
    from Func()

Which looks awkward.

Worse, this workaround fails if the imported function is also autoloaded:
```vim
vim9script
var dir = '/tmp/some'
&runtimepath = dir
dir ..= '/autoload'
dir->mkdir('p')
var lines =<< trim END
    vim9script autoload
    export def Func()
        echomsg 'from Func()'
    enddef
    sleep 3
END
lines->writefile(dir .. '/script.vim')
import autoload 'script.vim'
const Ref = script.Func
```
Notice that Vim is frozen for 3 seconds.  This means that `:sleep 3` was executed, which in turn means that Vim has sourced the whole autoload script, even though we haven't called the function once.  This defeats the whole purpose of autoloading, which is to defer the sourcing of a function until it's called.

Usually, to prevent Vim from sourcing an autoload script too early (i.e. as soon as we refer to an autoload function), we need to quote its name before passing it to another function (like `function()` or `call()`) .  But here, it doesn't work:
```vim
vim9script
var dir = '/tmp/some'
&runtimepath = dir
dir ..= '/autoload'
dir->mkdir('p')
var lines =<< trim END
    vim9script autoload
    export def Func()
        echomsg 'from Func()'
    enddef
    sleep 3
END
lines->writefile(dir .. '/script.vim')
import autoload 'script.vim'
const Ref = function('script.Func')
```
    E700: Unknown function: script.Func

Not only does it not work, but again, notice the 3 seconds we need to wait, even though we haven't called the autoload function yet.  We've merely tried to assign a funcref, while making sure to quote its name.

**Describe the solution you'd like**

In the rhs of a mapping installed in a Vim9 script, between `<Cmd>` and `<CR>`, give the guarantee to the user that the code will be processed in the context of the script where the mapping is installed.

This proposal would fix all the previously mentioned problems:

   - We would no longer need the weird `<SID>` pseudo-key:

```vim
vim9script
def Func()
    echomsg 'from Func()'
enddef
nnoremap <F3> <Cmd>Func()<CR>
```
   - We would no longer need to switch to a different syntax in a mapping installed in a Vim9 script.

   - We would no longer get unexpected errors when using `feedkeys()`.

   - We would no longer need an intermediate variable to call an imported function from a mapping.

   - We could call an imported function from a mapping even if it's autoloaded.

   - A Vim9 syntax plugin could easily highlight an Ex command in the rhs of a mapping installed in a Vim9 script.

**Describe alternatives you've considered**

N/A

**Additional context**

There are 4 counter arguments.

1. It would break the compatibility with existing scripts.

2. It's not possible, because Vim can't know if keys are being typed interactively or not; it has to assume they are typed interactively.  Therefore, it has to assume we are in the global context.

3. It would introduce an inconsistency; some parts of a mapping would be processed in the global context, others in the script context.

4. It's too difficult to implement.

Answer to `1.`:

That's why I suggest that this change is limited to a Vim9 script.

One could argue that this change has nothing to do with Vim9.  It has: mappings being always processed in the global context is more problematic in a Vim9 script than in a legacy script.

Also, I argue that whether a proposal is considered to be related to Vim9 or not is subjective and irrelevant.  What matters is whether the proposal makes Vim script more reliable, and easier to read/write.  And if the proposal breaks compatibility with existing legacy scripts, then we should still consider the possibility of limiting the change to Vim9.  That's already what we did on several occasions in the past.  For example in issue #8562:  `reltime()` is not specific to Vim9, and yet we've changed its behavior.  Same thing in issue #9188:  we've changed the behavior of `:lockvar`.  In both cases, the rationale was that the change made Vim script more reliable.  The same principle applies here:  the current proposal would make Vim script more reliable.

Answer to `2.`:

That's true most of the time, but not when `<Cmd>` is pressed.  The latter can only come from a mapping.  So, whatever command is executed afterward, Vim knows that it's a scripted command, not an interactive one.

Answer to `3.`:

The current situation is already inconsistent, and confusing.  Worse, it's unpredictable.  If this proposal is implemented, Vim would be more predictable.

Also, I would argue that the benefits far outweigh the inconsistency.

Also, there is no real inconsistency.  The proposal can be summarized with these 2 rules:

   - what is known to be executed interactively should be run in the global context
   - what is known to be executed non-interactively should be run in the script context

There would be an inconsistency if these rules were contradictory.  They are not.  Or if they did not make sense.  They do: a non-interactive command is scripted; therefore, it makes more sense to process it in the context of its script.

Answer to `4.`:

OK, that's understandable.  But maybe there is another solution to the previously mentioned problems?  Otherwise, feel free to close the issue.

**Comment by habamax** [comment]
I was expecting new `vim9script autoload` would work with `<expr>` mappings but it doesn't work due to the reason(s) you have described.

https://groups.google.com/g/vim_dev/c/gYoPwAnHPAw/m/TMkVno6EAAAJ

I personally would expect that if `map` and friends are executed in `vim9script` context it would understand vim9script.

**Comment by brammool** [comment]
> **Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
> 
> Mappings are always entirely processed in the global context; never in
> the context of the script where they are installed.  This can cause
> problems and inconsistencies.

Keep in mind that what a mapping does is replacing some typed characters
with other characters.  This mechanism isn't aware of any syntax or
semantics of these characters, it's just a text replacement.  And this
happens early on where typed characters are buffered, before they are
passed to the code that parses them and gives them meaning.

> First, it forces us to always write the pseudo-key `<SID>`, whenever we need to call a script-local function from the rhs of a mapping:
> ```vim
> vim9script
> def Func()
>     echomsg 'from Func()'
> enddef
> nnoremap <F3> <Cmd>call <SID>Func()<CR>
> feedkeys("\<F3>")
> ```
>     from Func()
> 
> For a new user, it's not easy to understand what `<SID>` means, nor
> why it's necessary.
> Also, we never *need* `<SID>` anywhere else; neither in a function's
> header, nor in a user-defined command, nor in an autocmd:
> ```vim
> vim9script
> def Func()
>     echomsg 'from Func()'
> enddef
> command Cmd Func()
> autocmd CursorHold * Func()
> Cmd
> doautocmd CursorHold
> ```
>     from Func()
>     from Func()
> 
> For these reasons, `<SID>` looks weird, which goes against one of the
> goals of Vim9 script; that is, avoid weird syntaxes:

This has nothing to do with scripts, legacy or Vim9.  The <SID> special
character gets translated when the mapping is defined into a special
code for the script, so that script-local items can be found.  Without
it that would not work.

> Second, when executing an Ex command from the rhs of a mapping, we
> need to use the legacy syntax even if we're actually writing a Vim9
> script.  That's a consequence of a mapping being processed in the
> global context.
> 
> Again, this looks weird.  If I'm writing a Vim9 script, I would expect
> to be able to use the Vim9 syntax everywhere in the script.  The only
> case where using the legacy syntax doesn't look weird is after
> `:legacy`, because this modifier explicitly tells us that we're
> switching to a different syntax.  In contrast, `:map` doesn't tell us
> anything in that regard; we have to remember that – implicitly –
> `:map` switches to the legacy syntax.

We will need something to mark the text as being special and executed in
the context of the script.  Perhaps the meaning of <Cmd> can be adjusted
to use Vim9 script syntax if the mapping is defined in a Vim9 script.
It's probably the only way, since only Ex commands can use Vim9 script
syntax, and only <Cmd> can be recognized as a prefix for an Ex command.

> Third, because of this implicit switch to the legacy syntax, it is
> more difficult for a Vim9 syntax plugin to correctly highlight an Ex
> command in the rhs of a mapping.  For example, `:let` is disallowed in
> Vim9, so it's useful to highlight this command as an error.  But in a
> mapping, `:let` is actually valid, so the syntax plugin has to make an
> exception, which makes the syntax rules more complex.  And since there
> are other differences, it's much easier to give up and not highlight
> anything in the rhs.

In a mapping you cannot really know what is valid, it's just text.  The
meaning depends on where it is used, which is hard to figure out.  Only
with <Cmd> you can predict what it means.

> Fourth, we currently have no way to tell in which context (legacy vs
> Vim9) a mapping will actually be processed.  Here are a few examples:
> ```vim
> vim9script
> nnoremap <F3> <Cmd>let g:name = 0<CR>
> feedkeys("\<F3>")
> ```
>     no error
> ```vim
> vim9script
> nnoremap <F3> <Cmd>let g:name = 0<CR>
> feedkeys("\<F3>", 'x')
> ```
>     E1126: Cannot use :let in Vim9 script
> ```vim
> vim9script
> nnoremap <F3> <Cmd>let g:name = 0<CR>
> legacy call feedkeys("\<F3>", 'x')
> ```
>     E1126: Cannot use :let in Vim9 script
> ```vim
> vim9script
> nnoremap <F3> <Cmd>let g:name = 0<cr>
> function Legacy()
>     call feedkeys("\<F3>", 'x')
> endfunction
> Legacy()
> ```
>     no error
> 
> Notice that the mapping is always exactly the same in the four
> snippets.  And yet, they give different results, which is confusing.

We already have different mappings for different modes.  Do we also need
different mappings for being in legacy or Vim9 script context?  I don't
think that makes it simpler.  I don't see why a mapping would be
executed from a script context anyway, this is not a common way of using
mappings.

> Fifth, in a mapping, we can't call an imported function directly:
> ```vim
> vim9script
> var dir = '/tmp/import'
> dir->mkdir('p')
> var lines =<< trim END
>     vim9script
>     export def Func()
>         echomsg 'from Func()'
>     enddef
> END
> lines->writefile(dir .. '/script.vim')
> import '/tmp/import/script.vim'
> nnoremap <F3> <Cmd>call script.Func()<CR>
> feedkeys("\<F3>")
> ```
>     E121: Undefined variable: script

Since the import exists in the script context <SID> needs to be used:

   nnoremap <F3> <Cmd>call <SID>script.Func()<CR>

But that probably doesn't work anyway (haven't tried it).
 
> As a result, we have to use an intermediate variable storing a reference to the imported function:
> ```vim
> vim9script
> var dir = '/tmp/import'
> dir->mkdir('p')
> var lines =<< trim END
>     vim9script
>     export def Func()
>         echomsg 'from Func()'
>     enddef
> END
> lines->writefile(dir .. '/script.vim')
> import '/tmp/import/script.vim'
> const Ref = script.Func
> nnoremap <F3> <Cmd>call <SID>Ref()<CR>
> feedkeys("\<F3>")
> ```
>     from Func()
> 
> Which looks awkward.
> 
> Worse, this workaround fails if the imported function is also autoloaded:

The autoload mechanism isn't fully working yet.  More work to do.

> **Describe the solution you'd like**
> 
> In the rhs of a mapping installed in a Vim9 script, between `<Cmd>`
> and `<CR>`, give the guarantee to the user that the code will be
> processed in the context of the script where the mapping is installed.

We could change the meaning for <Cmd> in Vim9 script.  I'll have to
check if this can work.  Something special has to be put in the RHS of
the mapping so that it can set the context of the script where the
mapping was defined.

For legacy script <Cmd> has been in use for a while, thus I don't think
we can change how it works without causing trouble.  Having <Cmd> work
differently in legacy and Vim9 script might be confusing.  Perhaps it's
better to use a new special key code and leave <Cmd> as it was.
Something like <Script> perhaps.

> 2. It's not possible, because Vim can't know if keys are being typed
> interactively or not; it has to assume they are typed interactively.
> Therefore, it has to assume we are in the global context.

When a mapping is typed, the context can be the global context, I don't
see a problem with that.

> 3. It would introduce an inconsistency; some parts of a mapping would
> be processed in the global context, others in the script context.

That is what was intended, right?

> That's why I suggest that this change is limited to a Vim9 script.

Although that is possible, it can be confusing.  Especially when
converting a legacy script to Vim9.  There would be no error until you
actually try the mapping.  And then it can be hard to figure out why it
does not work.  Using a new special key would avoid this.


-- 
       We're knights of the Round Table
       Our shows are formidable
       But many times
       We're given rhymes
       That are quite unsingable
       We're opera mad in Camelot
       We sing from the diaphragm a lot.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> Keep in mind that what a mapping does is replacing some typed characters
   > with other characters.  This mechanism isn't aware of any syntax or
   > semantics of these characters, it's just a text replacement.  And this
   > happens early on where typed characters are buffered, before they are
   > passed to the code that parses them and gives them meaning.

I know, which is why I've always been reluctant to open this issue.  I just think there is an opportunity to significantly improve Vim9.  Again, if it's too hard to implement, I don't mind the issue being closed.

   > This has nothing to do with scripts, legacy or Vim9.  The <SID> special
   > character gets translated when the mapping is defined into a special
   > code for the script, so that script-local items can be found.  Without
   > it that would not work.

I know, `<SID>` is translated into `<SNR>123_`, where `123` is the ID of the script.  That's how Vim is able to find a script-local function even from the global context.  I was giving the perspective of someone who doesn't understand this detail of implementation.  Let's put this another way:  it might look weird to some people that an Ex command is run in the context of a script when it's run at the script level, when it's run in a user-defined command, and when it's run in an autocmd; but not when it's run in a mapping.

   > We will need something to mark the text as being special and executed in
   > the context of the script.  Perhaps the meaning of <Cmd> can be adjusted
   > to use Vim9 script syntax if the mapping is defined in a Vim9 script.
   > It's probably the only way, since only Ex commands can use Vim9 script
   > syntax, and only <Cmd> can be recognized as a prefix for an Ex command.

Yes, that would be the ideal solution.

   > In a mapping you cannot really know what is valid, it's just text.  The
   > meaning depends on where it is used, which is hard to figure out.  Only
   > with <Cmd> you can predict what it means.

Yes, but:

   - the current issue is only about Ex commands
   - to execute an Ex command, `<Cmd>` should be preferred over `:`
   - with `<Cmd>`, we know the meaning of what follows (not with `:`)

This change would not entirely fix the issue.  There would be still the case of an Ex command for which the command-line was entered in a different way `:`, `gQ`, ...  But I think most of the time, `<Cmd>` can be used.

   > We already have different mappings for different modes.  Do we also need
   > different mappings for being in legacy or Vim9 script context?  I don't
   > think that makes it simpler.  I don't see why a mapping would be
   > executed from a script context anyway, this is not a common way of using
   > mappings.

Fair enough.  `feedkeys()` can be considered as a corner case.

   > Since the import exists in the script context <SID> needs to be used:
   >
   >    nnoremap <F3> <Cmd>call <SID>script.Func()<CR>
   >
   > But that probably doesn't work anyway (haven't tried it).

Ah, right.  I forgot `<SID>`.  But that doesn't work anyway, because `script` is considered as a variable.  That's yet another pitfall which has always bothered me.  We can access a script-local function from the global context, provided we know its ID (via the pseudo-key `<SNR>`), but we can't do the same for a script-local variable.

   > The autoload mechanism isn't fully working yet.  More work to do.

OK, I wasn't sure how the mechanism is supposed to work here.

   > For legacy script <Cmd> has been in use for a while, thus I don't think
   > we can change how it works without causing trouble.  Having <Cmd> work
   > differently in legacy and Vim9 script might be confusing.  Perhaps it's
   > better to use a new special key code and leave <Cmd> as it was.
   > Something like <Script> perhaps.

`<Cmd>` is still somewhat recent.  It was added in patch [8.2.1978](https://github.com/vim/vim/releases/tag/v8.2.1978) which is 13 months old.  And I would assume there is some lag; it probably takes some time for a new feature to become widely used.

If we try to use a different key code, I don't think `<Script>` can be used because it might conflict with [`:help :map-<script>`](https://vimhelp.org/map.txt.html#%3Amap-%3Cscript%3E).  Maybe `<scriptcontext>`?   Although it's a bit verbose...

   > When a mapping is typed, the context can be the global context, I don't
   > see a problem with that.

Right.  The problem is that the proposal would introduce context switching.  I argue that it's worth it.

   > Although that is possible, it can be confusing.  Especially when
   > converting a legacy script to Vim9.  There would be no error until you
   > actually try the mapping.  And then it can be hard to figure out why it
   > does not work.  Using a new special key would avoid this.

OK, now I understand.  Making Vim9 stricter than legacy is OK, because if there is an issue, the user will have an immediate feedback.  But the current proposal would not make Vim9 stricter; it would just make it different.

The only solution is indeed a new `:map` argument; like `<silent>`, `<nowait>`, ...

**Comment by lacygoill** [comment]
Also, as pointed out earlier by @habamax, in addition to `<Cmd>`, there is one other case where we know the meaning of the expanded keys:  a mapping defined with the `<expr>` argument.  Then, we know that the keys stand for an expression.  In that case too, using the context of the current script would be helpful.  Possibly in combination with a new key code like `<scriptcontext>`.

**Comment by lacygoill** [comment]
> <Cmd> is still somewhat recent. It was added in patch 8.2.1978 which is 13 months old. And I would assume there is some lag; it probably takes some time for a new feature to become widely used.

Also, I suspect it would not cause many issues in practice even in a legacy script.  Here is a typical mapping using `<Cmd>`:

    nnoremap <F3> <Cmd>call Func()<CR>

That should give the same result whether we are in the global context or the script-local one.  Without `s:`, `Func()` is always global.

   > If we try to use a different key code, I don't think <Script> can be used because it might conflict with :help :map-<script>. Maybe <scriptcontext>? Although it's a bit verbose...

Ah no, there would be no conflict, because they would not be used in the same positions.  The current `<script>` is an argument to `:map`; the new one would be a pseudo-key.

**Comment by brammool** [comment]
> Also, as pointed out earlier by @habamax, in addition to `<Cmd>`,
> there is one other case where we know the meaning of the expanded
> keys:  a mapping defined with the `<expr>` argument.  Then, we know
> that the keys stand for an expression.  In that case too, using the
> context of the current script would be helpful.  Possibly in
> combination with a new key code like `<scriptcontext>`.

Perhaps like we could have <Cmd> and <ScriptCmd> we could have <expr>
and <scriptExpr>.


-- 
MAN:     You don't frighten us, English pig-dog!  Go and boil your bottoms,
         son of a silly person.  I blow my nose on you, so-called Arthur-king,
         you and your silly English K...kaniggets.
   He puts hands to his ears and blows a raspberry.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
>    > Since the import exists in the script context <SID> needs to be used:
>    >
>    >    nnoremap <F3> <Cmd>call <SID>script.Func()<CR>
>    >
>    > But that probably doesn't work anyway (haven't tried it).
> 
> Ah, right.  I forgot `<SID>`.  But that doesn't work anyway, because
> `script` is considered as a variable.  That's yet another pitfall
> which has always bothered me.  We can access a script-local function
> from the global context, provided we know its ID (via the pseudo-key
> `<SNR>`), but we can't do the same for a script-local variable.

I do not see a big need to being able to access variables from a
mapping.  You can always define a function to get or set the value.

> If we try to use a different key code, I don't think `<Script>` can be
> used because it might conflict with [`:help
> :map-<script>`](https://vimhelp.org/map.txt.html#%3Amap-%3Cscript%3E).
> Maybe `<scriptcontext>`?   Although it's a bit verbose...

Since the meaning is very similar to <Cmd> a variant of that would work
best.  Perhaps <ScriptCmd>?

>    > Although that is possible, it can be confusing.  Especially when
>    > converting a legacy script to Vim9.  There would be no error until you
>    > actually try the mapping.  And then it can be hard to figure out why it
>    > does not work.  Using a new special key would avoid this.
> 
> OK, now I understand.  Making Vim9 stricter than legacy is OK, because
> if there is an issue, the user will have an immediate feedback.  But
> the current proposal would not make Vim9 stricter; it would just make
> it different.
> 
> The only solution is indeed a new `:map` argument; like `<silent>`,
> `<nowait>`, ...

It is not really possible to change context when encountering a mapping.
It would require putting something special in the typeahead, which might
then end up being discarded (e.g. when CTRL-C is typed or an error is
encountered) and hard to restore.

Using the mechanism that <Cmd> already uses, and has been working for a
while, sounds much better.

-- 
"Time flies like an arrow".  So I put an arrow on my desk, now
awaiting one of these time flies showing up.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by habamax** [comment]
now with 8.2.4059 mappings with `<expr>` works:

```
import autoload 'comment.vim'
nnoremap <silent> <expr> gc comment.Toggle()
```

Now I have "converted" to vim9script vimrc that has bunch of mappings to autoloaded files and it doesn't look consistent (example):

```
import autoload 'comment.vim'
nnoremap <silent> <expr> gc comment.Toggle()
" the same autoload/comment.vim but I have to use vim9 func differently
" and I actually don't have to import autoload 'comment' to use it like this.
nnoremap <C-l> :call comment#Test()<CR>
```

**Comment by brammool** [comment]
> now with 8.2.4059 mappings with `<expr>` works:
> 
> ```
> import autoload 'comment.vim'
> nnoremap <silent> <expr> gc comment.Toggle()
> ```
> 
> Now I have "converted" to vim9script vimrc that has bunch of mappings to autoloaded files and it doesn't look consistent (example):
> 
> ```
> import autoload 'comment.vim'
> nnoremap <silent> <expr> gc comment.Toggle()
> " the same autoload/comment.vim but I have to use vim9 func differently
> " and I actually don't have to import autoload 'comment' to use it like this.
> nnoremap <C-l> :call comment#Test()<CR>
> ```

There was a discussion that when using a mapping the script context of
where it was defined is not used.  That was now fixed for <expr>
mappings, which is possible since it already is evaluated separately,
where we can set the context.  For other mappings we have no place to
set the context, thus the thought is to make a variant of <Cmd>,
possibly <ScriptCmd> that does this.  Then your mapping can be:

   nnoremap <C-l> <ScriptCmd>comment.Test()<CR>

I think that should work well.

-- 
FIRST HEAD:  Oh! quick! get the sword out I want to cut his head off.
THIRD HEAD:  Oh, cut your own head off.
SECOND HEAD: Yes - do us all a favour.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
The patch [8.2.4099](https://github.com/vim/vim/releases/tag/v8.2.4099) introduces the new keycode `<ScriptCmd>`, which fixes the issue.
```vim
vim9script
def ScriptLocal()
    echomsg 'from ScriptLocal()'
enddef
nnoremap <F3> <ScriptCmd>ScriptLocal()<CR>
feedkeys("\<F3>")
```

Thank you very much.

---

BTW, `<silent>` is not necessary when `<ScriptCmd>` is used, just like it's not necessary with `<Cmd>`.  So the help example can be simplified:
```diff
diff --git a/runtime/doc/map.txt b/runtime/doc/map.txt
index 1072d56..409f323 100644
--- a/runtime/doc/map.txt
+++ b/runtime/doc/map.txt
@@ -353,7 +353,7 @@ useful for |Vim9| script.  It also works to access an import, which is useful
 in a plugin using an autoload script: >
        vim9script
        import autoload 'implementation.vim' as impl
-	nnoremap <silent> <F4> <ScriptCmd>impl.DoTheWork()<CR>
+	nnoremap <F4> <ScriptCmd>impl.DoTheWork()<CR>
 
 No matter where <F4> is typed, the "impl" import will be found in the script
 context of where the mapping was defined.  And since it's an autoload import,
```
