### ISSUE TITLE
Tabulators are not highlighted completely with 'linebreak' enabled

### ISSUE THREAD

**Issue by wrtlprnft** [vim/vim#9500]
### Steps to reproduce

Run this shell command:

```
vim -Nu NONE -S <(cat <<'EOF'
	call matchadd('ErrorMsg', '\t', 5)
	set linebreak
	normal ix
	normal >>
EOF
)
```

### Expected behaviour

I expect all columns that belong to the tab character to be highlighted, like this:

![Screenshot_20220110_154450](https://user-images.githubusercontent.com/2631947/148784911-16d42ac8-551f-45e0-9a4b-54a9e5589231.png)

This is the behavior of vim up to v8.2.3697.

Instead, only the first column gets highlighted:

![Screenshot_20220110_154715](https://user-images.githubusercontent.com/2631947/148785246-63f39063-c87d-4335-a7f2-98d636625fe5.png)

This is the behavor with v8.2.3698 (the fix for issue #9242) and v8.2.4051 (current master).

### Version of Vim

8.2.4051

### Environment

OS: Gentoo
$TERM: screen.xterm-256color (also happens with GTK GUI)

**Comment by chrisbra** [comment]
Hm, I think we just need this one:
```patch
diff --git a/src/drawline.c b/src/drawline.c
index 8a042ed3e..1c7859acd 100644
--- a/src/drawline.c
+++ b/src/drawline.c
@@ -2043,7 +2043,7 @@ win_line(
                        if (n_extra < 0)
                            n_extra = 0;
                    }
-                   if (on_last_col)
+                   if (on_last_col && c != TAB)
                        // Do not continue search/match highlighting over the
                        // line break.
                        search_attr = 0;
```
@lacygoill I didn't fully understand your #9242 but I think this change shouldn't affect it.

**Comment by lacygoill** [comment]
> @lacygoill I didn't fully understand your #9242 but I think this change shouldn't affect it.

I can confirm that the patch doesn't introduce a regression, and that it fixes the current issue:
```diff
diff --git a/src/drawline.c b/src/drawline.c
index 8a042ed3e..1c7859acd 100644
--- a/src/drawline.c
+++ b/src/drawline.c
@@ -2043,7 +2043,7 @@ win_line(
 			if (n_extra < 0)
 			    n_extra = 0;
 		    }
-		    if (on_last_col)
+		    if (on_last_col && c != TAB)
 			// Do not continue search/match highlighting over the
 			// line break.
 			search_attr = 0;
```
Thank you very much for the quick fix.

**Comment by wrtlprnft** [comment]
I can confirm that this patch also fixes the actual issue/regression I have with my full vimrc. Thank you very much for the quick replies!

**Comment by chrisbra** [comment]
okay I have created #9507 to address this
