### ISSUE TITLE
Buffer with buftype=prompt lost the prompt icon after running `dd`

### ISSUE THREAD

**Issue by rockyzhang24** [vim/vim#9502]
### Steps to reproduce

1. Open a new buffer
2. run set buftype=prompt
3. go into insert mode
4. type something
5. dd
6. prompt icon is gone.
7. back to insert, prompt icon is back

### Expected behaviour

I think the prompt icon should always be visible. 

### Version of Vim

8.2.3489

### Environment

OS: macOS 12.1 (the latest)
terminal: kitty
$TERM: xterm-kitty
shell: zsh 5.8

**Comment by brammool** [comment]
With "prompt icon" you mean the "%" at the start of the line?
If you delete the line then there is no line to put "%" in front of.
Thus I would say this is expected.

**Comment by yanzhang0219** [comment]
Okay, make sense. Thank you very much. Closing this.
