### ISSUE TITLE
Can't bind `<a-bs>`

### ISSUE THREAD

**Issue by andmis** [vim/vim#9503]
### Steps to reproduce

`:imap <a-bs> <c-w>` or `:imap <m-bs> <c-w>` -- just doesn't work.

I've tried the suggestions in https://github.com/vim/vim/issues/4974 and they don't seem to help. I've also spent a bunch of time on Google trying to figure this out.

On a fresh `brew install nvim`, `:imap <a-bs> <c-w>` just works out of the box -- so it's not my terminal emulator or anything. (I'm on an up-to-date kitty on macOS 12, if it matters.)

### Expected behaviour

`:imap <a-bs> <c-w>` should bind alt-backspace to ctrl-w in insert mode.

### Version of Vim

8.2

### Environment

TERM=xterm-kitty

But I also tried this on macOS's built-in Terminal.app and got the same result.

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 09 2022 21:36:37)
macOS version - arm64
Included patches: 1-4050
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
-balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +gettext           +num64             +textobjects
-browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     +perl              +title
+channel           +ipv6              +persistent_undo   -toolbar
+cindent           +job               +popupwin          +user_commands
-clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           -python            +viminfo
+cmdline_info      +libcall           +python3           +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
+cscope            +localmap          +ruby              +wildignore
+cursorbind        +lua               +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con        +mksession         +smartindent       +writebackup
+diff              +modify_fname      -sodium            -X11
+digraphs          +mouse             -sound             -xfontset
-dnd               -mouseshape        +spell             -xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        -mouse_gpm         +statusline        -xsmp
+eval              -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary        
-farsi             -mouse_sysmouse    -tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/opt/homebrew/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DMACOS_X -DMACOS_X_DARWIN -g -O2 -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: clang -L. -fstack-protector-strong -L/opt/homebrew/lib -L/opt/homebrew/opt/libyaml/lib -L/opt/homebrew/opt/openssl@1.1/lib -L/opt/homebrew/opt/readline/lib -o vim -lm -lncurses -liconv -lintl -framework AppKit -L/opt/homebrew/opt/lua/lib -llua5.4 -mmacosx-version-min=12.0 -fstack-protector-strong -L/opt/homebrew/Cellar/perl/5.34.0/lib/perl5/5.34.0/darwin-thread-multi-2level/CORE -lperl -L/opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/lib/python3.10/config-3.10-darwin -lpython3.10 -framework CoreFoundation -lruby.3.0 -L/opt/homebrew/Cellar/ruby/3.0.3/lib

**Comment by andmis** [comment]
Oh yeah, <c-v><a-bs> in Insert mode inserts nothing (at least nothing that I can see).

I can do `:imap <esc><bs> <c-w>` and that will apparently work, although I can also hit the key sequence <esc><bs> literally and that triggers the mapping too, which I really don't want.

`:imap <a-left> <c-w>` *does* seem to work, and to not be conflated with <esc><left>. Is there some rule about which alt-bindings work? Is it possible to make <a-bs> work?

**Comment by lacygoill** [comment]
> I can do :imap &lt;esc>&lt;bs> &lt;c-w> and that will apparently work, although I can also hit the key sequence <esc><bs> literally and that triggers the mapping too, which I really don't want.

Does this help?

    execute "set <M-BS>=\<Esc>\<BS>"
    imap <M-BS> <C-W>

**Comment by andmis** [comment]
Trying to run the first line gives me the following:

![image](https://user-images.githubusercontent.com/5308024/148871151-525fd1f7-9780-4e16-85d1-fb26f636f872.png)

The second line runs fine but the binding continues not to work.

**Comment by andmis** [comment]
I don't know if this is related, but bindings using `<c-space>` also seem not to work. Is there a list somewhere of what key sequences will not work as bindings, workarounds, etc.? I can't find this in the docs.

**Comment by lacygoill** [comment]
> Trying to run the first line gives me the following:

Then I don't think `<A-BS>` is currently supported.  If you're OK with a hack, you could try this:

    execute "<F13>=\<Esc>\<BS>"
    imap <F13> <C-W>

You can replace `<F13>` with any function key up to `<F37>`.  And you can combine it with the Shift modifier.

   > I don't know if this is related, but bindings using <c-space> also seem not to work.

It works if the terminal supports the [`modifyOtherKeys`](https://vimhelp.org/map.txt.html#modifyOtherKeys) feature in mode 2:

![gif](https://user-images.githubusercontent.com/8505073/148872851-931a8fc8-03e5-4740-ab11-cbea09b02e56.gif)

That's the case in xterm for example.

> Is there a list somewhere of what key chords will not work as bindings, workarounds, etc.? I can't find this in the docs.

I don't think so, but if I'm wrong and there is something, then it should be somewhere at [`terminal-info`](https://vimhelp.org/term.txt.html#terminal-info).

**Comment by andmis** [comment]
Assuming you meant this:

```
execute "set <F13>=\<Esc>\<BS>"
imap <F13> <C-W>
```

This also didn't work for me.

**Comment by lacygoill** [comment]
> This also didn't work for me.

This should work:

    execute "set <F13>=\<Esc>" .. &t_kb
    inoremap <F13> <C-W>

**Comment by andmis** [comment]
I tried https://github.com/tpope/vim-rsi, which uses similar hacks, and yeah that stuff does seem to work. Thanks for your help!
