### ISSUE TITLE
Extra indent for regular lines with `breakindentopt=list:-1`

### ISSUE THREAD

**Issue by habamax** [vim/vim#9512]
### Steps to reproduce

1. `vim -Nu NONE`
2. `100iasdf <ESC>`
3. `:set breakindent breakindentopt=list:-1`

**UPD**:

1. `vim -Nu NONE`
2. `:set breakindent breakindentopt=list:-1`
3. `100iasdf <ESC>I1. <ESC>G`
4. `100iasdf <ESC>`

### Expected behaviour

Not indented wrapped lines.
But I see following:
![image](https://user-images.githubusercontent.com/234774/149192073-a0cf7841-a696-45c9-b4ab-697aa67adc0a.png)

### Version of Vim

8.2.4071

### Environment

OS: WSL debian
Terminal: wsltty

**Comment by habamax** [comment]
Actually not only order matters but whether there is/was a list item created too:

1. `vim -Nu NONE`
2. `:set breakindent breakindentopt=list:-1`
3. `100iasdf <ESC>I1. <ESC>G`
4. `100iasdf <ESC>`

![image](https://user-images.githubusercontent.com/234774/149192833-42671a07-12a8-4618-8a25-5bbf5df2ad8f.png)

**Comment by habamax** [comment]
Actually if you have non wrapped listitem and wrapped non-listitem long line then there is no indent.

![vim-indent-bug](https://user-images.githubusercontent.com/234774/149194570-68461f49-8c6f-48c0-a958-0bdd336d6162.gif)

**Comment by lacygoill** [comment]
I noticed that too a few days ago, without being able to reproduce.

Here is a test which currently fails, while it should pass:
```vim
vim9script
&breakindent = true
&breakindentopt = 'list:-1'
var text: string = 'word '
var len: number = text->strcharlen()
var line1: string = text->repeat((&columns / len) * 2)
var line2: string = repeat(' ', 10) .. '1. ' .. line1
[line1, line2]->setline(1)
redraw
range(1, 20)
    ->mapnew((_, c: number): string => screenstring(2, c))
    ->join('')
    ->assert_equal(' word word word word')
echo v:errors
```
    ['... Expected '' word word word word'' but got ''              word w''']

Regression introduced in [8.2.4029](https://github.com/vim/vim/releases/tag/v8.2.4029).  One of the purposes of the patch was to fix #9309.

The latter did not include a test.  I tried to write one:
```vim
vim9script
&breakindent = true
&breakindentopt = 'list:-1'
&formatlistpat = '^-'
:50 vnew
var line: string = printf('- y %s y %s', repeat('x', 50), repeat('x', 50))
line->setline(1)
&hlsearch = true
@/ = '\%>3v[y]'
redraw
searchcount().total->assert_equal(1)
```
Both tests as a patch:
```diff
diff --git a/src/testdir/test_breakindent.vim b/src/testdir/test_breakindent.vim
index 0c143b194..4d6661029 100644
--- a/src/testdir/test_breakindent.vim
+++ b/src/testdir/test_breakindent.vim
@@ -849,4 +849,34 @@ func Test_window_resize_with_linebreak()
   %bw!
 endfunc
 
+def Test_no_spurious_match()
+  new
+  :50 vnew
+  &breakindent = true
+  &breakindentopt = 'list:-1'
+  &formatlistpat = '^-'
+  var line: string = printf('- y %s y %s', repeat('x', 50), repeat('x', 50))
+  line->setline(1)
+  &hlsearch = true
+  @/ = '\%>3v[y]'
+  redraw!
+  searchcount().total->assert_equal(1)
+  :% bwipeout!
+enddef
+
+def Test_no_extra_indent()
+  new
+  :50 vnew
+  &breakindent = true
+  &breakindentopt = 'list:-1'
+  var text: string = 'word '
+  var len: number = text->strcharlen()
+  var line1: string = text->repeat((winwidth(0) / len) * 2)
+  var line2: string = repeat(' ', 10) .. '1. ' .. line1
+  [line1, line2]->setline(1)
+  redraw!
+  ScreenLines(2, 20)->assert_equal([' word word word word'])
+  :% bwipeout!
+enddef
+
 " vim: shiftwidth=2 sts=2 expandtab
```
Note that I'm not used writing tests, so the patch might need to be updated.  Still, it does the job.  The tests fail/pass as expected.

---

CC @chrisbra via #9482

**Comment by chrisbra** [comment]
I feared that  8.2.4029 could have introduced this. I'll check it later today

**Comment by chrisbra** [comment]
I think the fix is pretty simple, the cache wasn't properly initialized :( 
```patch
diff --git a/src/indent.c b/src/indent.c
index b74bae6e6..2980be8a9 100644
--- a/src/indent.c
+++ b/src/indent.c
@@ -953,6 +953,7 @@ get_breakindent_win(
                                     (int)wp->w_buffer->b_p_ts, wp->w_p_list);
 # endif
        prev_listopt = wp->w_briopt_list;
+       prev_list = 0;
        // add additional indent for numbered lists
        if (wp->w_briopt_list != 0)
        {

```
PR coming. 

BTW: @brammool are vim9 tests okay (and can we freely mix vim9 tests with legacy tests) in the test suite or should we stay with legacy tests in the test suit (apart from the vim9 tests of course)?

**Comment by brammool** [comment]
Christian wrote:

> I think the fix is pretty simple, the cache wasn't properly initialized :( 
> ```patch
> diff --git a/src/indent.c b/src/indent.c
> index b74bae6e6..2980be8a9 100644
> --- a/src/indent.c
> +++ b/src/indent.c
> @@ -953,6 +953,7 @@ get_breakindent_win(
>                                      (int)wp->w_buffer->b_p_ts, wp->w_p_list);
>  # endif
>         prev_listopt = wp->w_briopt_list;
> +       prev_list = 0;
>         // add additional indent for numbered lists
>         if (wp->w_briopt_list != 0)
>         {
> 
> ```
> PR coming. 
> 
> BTW: @brammool are vim9 tests okay (and can we freely mix vim9 tests
> with legacy tests) in the test suite or should we stay with legacy
> tests in the test suit (apart from the vim9 tests of course)?

Feel free to use Vim9 tests.  Some places test with both legacy and Vim9
script, depending on what is being tested either one can cover the code.

-- 
Why doesn't Tarzan have a beard?

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
I see, so mixing vim9 and legacy vimscript in the same test is okay. But for #9526 I have kept to the style in the existing test, so using legacy VimScript.

**Comment by brammool** [comment]
> I see, so mixing vim9 and legacy vimscript in the same test is okay.
> But for #9526 I have kept to the style in the existing test, so using
> legacy VimScript. 

These test functions are only executed once, thus there is no advantage
in compiling them.  Also, they are always invoked, thus the compile time
type checking doesn't help.

You can leave out "call" and many "let" statements, that's a small
advantage.  You have to make sure about white space, which helps
avoiding hard-to-read code.

-- 
FATHER:    Who are you?
PRINCE:    I'm ... your son ...
FATHER:    Not you.
LAUNCELOT: I'm ... er ... Sir Launcelot, sir.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
