### ISSUE TITLE
Add termdebug option to open sources readonly if SwapExists

### ISSUE THREAD

**Issue by jwakely** [vim/vim#9518]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

I often have multiple separate gvim windows running, with different sources in each (maybe one has the code I'm writing, and another has the tests for that code). When debugging with TermDebug and stepping through the code, the source window will open new files as needed. But if that file is already being edited in another Gvim window I get the **VIM -ATTENTION Swap file ".foo.cpp.swap" already exists!** dialog and have to confirm I want to open it.

The code I want to debug is already open in the gvim window. But when other source files are opened by termdebug, I don't usually need to edit those sources if I'm just stepping through a stack frame before getting to the code I actually want to debug.

So is there any way to tell TermDebug to open new source files readonly by default, so I don't get that dialog?

**Describe the solution you'd like**

I think my ideal solution would be for TermDebug to set `autocmd SwapExists * let v:swapchoice = "o"` temporarily while I'm debugging, then reset it afterwards. Maybe make that optional, controlled by some `let:termdebug_ro_if_swapexists` setting.

This way if a file isn't being edited in another session, open if modifable as normal. But if a swap file exists, just silently open it readonly without requiring confirmation. (N.B. I don't want to use `v:swapchoice = "o"` globally, because I usually *do* want the confirmation dialog ... just not when stepping into code in the debugger).

**Describe alternatives you've considered**

Another solution that would work for me would be a `let:termdebug_ro_source` option that just uses `view` to open *all* new source files instead of `edit`. For files that are already opened modifiable in a buffer, keep them that way, but when opening a new file, do so readonly by default (I can always override that if I decide I do want to edit that file).

That would work for me (it avoids the confirmation popup which is my main concern) but IMHO making it depend on `SwapExists` would be the ideal.

**Additional context**

TermDebug is amazing, I love it, and it's been a real gamechanger for me. Thank you!

**Comment by brammool** [comment]
I think it is OK to just always open the file read-only and avoid being interrupted by the prompt when stepping through code.
I'll make that change, try it out a bit and it will be in the next runtime files update.

**Comment by jwakely** [comment]
Great, thanks!

If it's possible to do this somehow using `au User TermdebugStartPost` and `TermdebugStopPost` I'd be happy to add those autocmds to my vimrc, but I couldn't get it working.

**Comment by GitMensch** [comment]
I'm confused: is this "always on" and/or configurable?

**Comment by chrisbra** [comment]
looks like it is always on by default:

[HandleCursor](https://github.com/vim/vim/blob/87f74106f96737e7b8ceaafe1a131aa718077de6/runtime/pack/dist/opt/termdebug/plugin/termdebug.vim#L1274-L1282)

@brammool  aren't we missing an explicit `:au!` inside the augroup? It looks like this is accumulating SwapExists autocommands in the `Termdebug` group.

**Comment by brammool** [comment]
> looks like it is always on by default:
> 
> [HandleCursor](https://github.com/vim/vim/blob/87f74106f96737e7b8ceaafe1a131aa718077de6/runtime/pack/dist/opt/termdebug/plugin/termdebug.vim#L1274-L1282)
> 
> @brammool  aren't we missing an explicit `:au!` inside the augroup? It
> looks like this is accumulating SwapExists autocommands in the
> `Termdebug` group.

The autocommand is deleted 17 lines lower.  Would it ever fail before
that?

-- 
hundred-and-one symptoms of being an internet addict:
65. The last time you looked at the clock it was 11:30pm, and in what
    seems like only a few seconds later, your sister runs past you to
    catch her 7am school bus.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
