### ISSUE TITLE
Better b:match_words for ftplugin/html.vim?

### ISSUE THREAD

**Issue by pmorch** [vim/vim#952]
`b:match_words` is for the matchit plugin that is disabled by default. If I enable it, it matches especially `<ul>` tags in a way that appears wrong to me.

If I have this html:

``` html
<ul>
    <li>List Item</li>
    <li>List Item</li>
    <li>List Item</li>
    <li>List Item</li>
    <li>List Item</li>
    <li>List Item</li>
</ul>
```

and put my cursor in the `<ul>` tag and hit `%`, I expect to end in the `</ul>` tag (the whole point of the plugin), but instead I'm unexpectedly placed at the first `<li>` tag. It works fine for `<div>` and other tags.

`b:match_words` gets set up for HTML files in `html.vim` with:

``` vim
    let b:match_words = '<:>,' .
    \ '<\@<=[ou]l\>[^>]*\%(>\|$\):<\@<=li\>:<\@<=/[ou]l>,' .
    \ '<\@<=dl\>[^>]*\%(>\|$\):<\@<=d[td]\>:<\@<=/dl>,' .
    \ '<\@<=\([^/][^ \t>]*\)[^>]*\%(>\|$\):<\@<=/\1>'
```

I don't understand why there is special handling for `<ul>`, `<ol>` and `<li>` tags (second line) and similar special handling for definition lists on the third line. If I remove them and just leave the fourth line's default handling, it seems to work perfectly as I expect.

``` diff
$ git diff
diff --git a/runtime/ftplugin/html.vim b/runtime/ftplugin/html.vim
index 7579080..d192201 100644
--- a/runtime/ftplugin/html.vim
+++ b/runtime/ftplugin/html.vim
@@ -29,8 +29,6 @@ endif
 if exists("loaded_matchit")
     let b:match_ignorecase = 1
     let b:match_words = '<:>,' .
-    \ '<\@<=[ou]l\>[^>]*\%(>\|$\):<\@<=li\>:<\@<=/[ou]l>,' .
-    \ '<\@<=dl\>[^>]*\%(>\|$\):<\@<=d[td]\>:<\@<=/dl>,' .
     \ '<\@<=\([^/][^ \t>]*\)[^>]*\%(>\|$\):<\@<=/\1>'
 endif
```

The value of `b:match_words` was introduced in the first version of `html.vim` in 071d4279d6ab81b7187b48f3a0fc61e587b6db6c from 2004 where files were added in bulk so I have no idea why it is like that.

Would it be reasonable to replace the current version with the simpler general-handling-only version? Or add a comment as to why it is like it is?

(I just override this default setting in my `~/.vimrc` with the following so my itch has been scratched, but perhaps others wonder too...)

``` vim
  autocmd FileType html      let b:match_words = '<:>,' .
    \ '<\@<=\([^/][^ \t>]*\)[^>]*\%(>\|$\):<\@<=/\1>'
```

**Comment by k-takata** [comment]
The cursor jumps `<ul>` → `<li>` → ... → `<li>` → `</ul>`, then `<ul>` again. I think this is intended.
BTW, please contact the script maintainer. You will find his name on top of `ftplugin/html.vim`.

**Comment by pmorch** [comment]
Ok, my bad. I missed that. I can see how that could be useful for some, though not for me. I'll close this issue and contact Dan Sharp &lt;dwsharp at users dot sourceforge dot net&gt; directly instead.

**Comment by muneebullashariff** [comment]
How to write b:match_words for:
if
else if  "Note the space"
else

Help appreciated.
