### ISSUE TITLE
Resize commands for terminal windows are bugged

### ISSUE THREAD

**Issue by emandret** [vim/vim#9528]
### Steps to reproduce

1. open Vim;
2. split terminal vertically with `:vert term`;
3. try to resize with `CTRL-w_<` or `CTRL-w_>`;
4. exchange the two windows with `CTRL-w_x`;
5. switch to the terminal window with `CTRL-w_w`;
6. repeat step nb. 3 and notice the two commands are now inverted.

### Expected behaviour

The terminal window should remap the `CTRL-w_<` and `CTRL-w_>` bindings after the two windows have been exchanged.

### Version of Vim

8.2.4000

### Environment

macOS Monterey 12.1
Terminal.app
xterm-256color
zsh 5.8

**Comment by lacygoill** [comment]
> repeat step nb. 3 and notice the two commands are now inverted.

They are not inverted.  Their behavior is consistent with the documentation.  `<C-W>>` increases the width of the current window, while `<C-W><` decreases it.

If you don't like the documented behavior, try these mappings:
```vim
nnoremap <expr> <C-W>< winnr('l') == winnr() ? '<C-W>>' : '<C-W><'
nnoremap <expr> <C-W>> winnr('l') == winnr() ? '<C-W><' : '<C-W>>'
tnoremap <expr> <C-W>< winnr('l') == winnr() ? '<C-W>>' : '<C-W><'
tnoremap <expr> <C-W>> winnr('l') == winnr() ? '<C-W><' : '<C-W>>'
```
For more info, see:

   - [`:help :nnoremap`](https://vimhelp.org/map.txt.html#%3Annoremap)
   - [`:help :tnoremap`](https://vimhelp.org/map.txt.html#%3Atnoremap)
   - [`:help :map-<expr>`](https://vimhelp.org/map.txt.html#%3Amap-%3Cexpr%3E)
   - [`:help winnr()`](https://vimhelp.org/builtin.txt.html#winnr%28%29)

For more questions, visit the [google mailing list](https://groups.google.com/g/vim_use), the [irc channel](https://www.vi-improved.org/), or [vi.stackexchange.com](https://vi.stackexchange.com/).

**Comment by lacygoill** [comment]
> <C-W>> increases the width of the current window, while <C-W>< decreases it.

Usually, this is done by moving the right vertical separator, but when you're in the rightmost window, there is no vertical separator on the right, so Vim has to perform the resize by moving the left one.  And depending on which vertical separator is moved, the direction of the motion is not the same.  But the help gives no guarantee with regards to the direction: `<C-W>>` can move a separator to the right or to the left.  It gives a guarantee with regards to the new width:  `<C-W>>` will make it bigger no matter what.
