### ISSUE TITLE
g:netrw_liststyle=3 causes <C-O> to misbehave

### ISSUE THREAD

**Issue by jshort** [vim/vim#953]
I like to set the netrw setting for list style to:

```
g:netrw_liststyle=3
```

And when I hop around within a file or to go back to the file explorer, I prefer`<C-O>` but if the netrw file explorer is in mode 3, `<C-O>` sometimes sends you back to an empty buffer with NetrwTreeListing 1 in the status bar and just stays there. Other times if you hit return shortly after `<C-O>` it will show the file explorer (not always, however). If I cycle in the file explorer with `i` to go to a different liststyle and open a file and then use `<C-O>`, it immediately takes me back to the file explorer without fail.

I'm on OSX with VIM 7.3 (2010 Aug 15, compiled Jun 14 2016 16:06:49) netrw v140

**Comment by chrisbra** [comment]
That is an old version. Please try with a newer Version. You can get the most recent version from [here](http://www.drchip.org/astronaut/vim/#NETRW), but that probably also needs a new Vim. Homebrew should have a newer Vim for you. Please verify if the issue still occurs. If not, please send reproducible example.

**Comment by jshort** [comment]
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul 21 2016 12:31:02)
MacOS X (unix) version
Included patches: 1-2085
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):

netrw v156

And this issue _does not_ occur.  Note that :Rex works in both the 7.3/v140 above.
