### ISSUE TITLE
Vim9: global context not restored after pressing mapping using <ScriptCmd>

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9536]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        nnoremap <F3> <ScriptCmd>eval 1 + 2<CR>
        feedkeys("\<F3>:eval 3+4\<CR>")
    EOF
    )

`E1004` is given:

    E1004: White space required before and after '+' at "+4"

**Expected behavior**

No error is given, because `:eval 3+4` is executed from an interactive command-line; i.e. from the global context, where only the legacy syntax is valid, and where there is no requirement about white space around binary operators.

**Version of Vim**

8.2 Included patches: 1-4103

**Environment**

Operating system: Ubuntu 20.04.3 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: zsh 5.8

**Logs and stack traces**

The issue is not somehow caused by `feedkeys()`.  It can be reproduced interactively.  Press:

   - `<F3>` to use the mapping
   - `:` to enter the command-line
   - `eval 3+4` to populate the command-line with an Ex command valid in legacy
   - `Enter` to execute the Ex command

`E1004` is again unexpectedly given.

**Comment by lacygoill** [comment]
This can break a legacy plugin.  Suppose that a user has 2 plugins, one written in legacy, the other in Vim9; and the Vim9 mapping uses `<ScriptCmd>`.

The legacy mapping will initially work, but as soon as the Vim9 mapping is pressed, it will get broken.

Here is an example:
```vim
nnoremap <F3> <ScriptCmd>eval 1 + 2<CR>
function Legacy()
    nnoremap <F4> :eval 'x' is# 'x'<CR>
endfunction
Legacy()
feedkeys("\<F3>\<F4>")
```
    E15: Invalid expression: "is# 'x'"

Right now, this already affects the matchit plugin:
<https://github.com/vim/vim/blob/38ecd9722664049d636f4fba759b3ebbfd34e97d/runtime/pack/dist/opt/matchit/plugin/matchit.vim#L49-L55>

Because the latter doesn't add spaces after the commas which separate arguments in function calls.  That's only fine as long as `<ScriptCmd>` is not used in another script.

**Comment by lacygoill** [comment]
> This can break a legacy plugin.

It also makes anything typed on an interactive command-line evaluated with the Vim9 syntax, which is rather neat, but still unexpected.

**Comment by brammool** [comment]
The first example is not right, the feedkeys() call is inside the Vim9 script.  You omitted the execute argument, and hopefully the eval command is then done after the script finishes, but when adding execute it will fail.  I'll have to think of another way to test this...

**Comment by lacygoill** [comment]
Not sure how it happened but I've just had the opposite issue: a Vim9 mapping was processed in the legacy context.

I have these mappings in my vimrc:

    xnoremap d d<ScriptCmd>getreginfo('"')->setreg('v')<CR>
    xnoremap y y<ScriptCmd>getreginfo('"')->setreg('v')<CR>

And one of them has given this error:

    E492: Not an editor command: getreginfo('"')->setreg('v')

That should not be possible because my vimrc is a Vim9 script, and there is no need for `:eval` in Vim9.  Unfortunately, I can't reproduce anymore.  Hopefully, the next time it happens, I'll be able to notice what are the necessary steps to reproduce.

**Comment by lacygoill** [comment]
Hypothesis: Maybe some legacy plugin has invoked `maparg()` to get the rhs of the `y` mapping, then executed it.  That would not work in a legacy script or function.

But this highlights some possible limitation of `maparg()`:  it doesn't tell us the context in which the mapping is installed:
```vim
vim9script
xnoremap y y<ScriptCmd>getreginfo('"')->setreg('v')<CR>
echomsg maparg('y', 'x', false, true)->keys()
```
    ['lnum', 'script', 'mode', 'silent', 'noremap', 'lhs', 'lhsraw', 'nowait', 'expr', 'sid', 'rhs', 'buffer']

Notice that there is no `context` key.  And `script` is irrelevant here; it's just a boolean which is true if the mapping was defined with the `<script>` argument.

**Comment by lacygoill** [comment]
Also, the missing information is an issue for `mapset()`, because it means that it's not able to properly restore a Vim9 mapping:
```vim
vim9script
xnoremap y y<ScriptCmd>getreginfo('"')->setreg('v')<CR>
function Legacy() abort
    let save = maparg('y', 'x', v:false, v:true)
    xunmap y
    " ...
    call mapset('x', v:false, save)
endfunction
Legacy()
feedkeys('vy')
```
    E492: Not an editor command: getreginfo('"')->setreg('v')

If `mapset()` had correctly restored the `y` mapping, no error would have been given.

**Comment by brammool** [comment]
> Also, the missing information is an issue for `mapset()`, because it means that it's not able to properly restore a Vim9 mapping:
> ```vim
> vim9script
> xnoremap y y<ScriptCmd>getreginfo('"')->setreg('v')<CR>
> function Legacy() abort
>     let save = maparg('y', 'x', v:false, v:true)
>     xunmap y
>     " ...
>     call mapset('x', v:false, save)
> endfunction
> Legacy()
> feedkeys('vy')
> ```
>     E492: Not an editor command: getreginfo('"')->setreg('v')
> 
> If `mapset()` had correctly restored the `y` mapping, no error would
> have been given.

The "sid" is used, which is the script ID.  But I don't think there is a
way to find out what the syntax of a script is.

We can add the "scriptversion" to the functions.

-- 
WOMAN:   King of the who?
ARTHUR:  The Britons.
WOMAN:   Who are the Britons?
ARTHUR:  Well, we all are. we're all Britons and I am your king.
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
