### ISSUE TITLE
syntax/rc.vim has colors that doesn't play well with :colo

### ISSUE THREAD

**Issue by habamax** [vim/vim#9542]
### Steps to reproduce

1. `gvim -Nu NONE`
2. `:syntax on`
3. `:set ft=rc`
4. `:hi normal guibg=darkgreen` -- imagine we have a colorscheme that uses darkgreen as a background.
5. `iSTYLE` (or open vim.rc from vim project)

STYLE is invisible.

### Expected behaviour

All the highlight groups are linked to some of the `:h group-name`.

There actually a set of colors in `syntax/rc.vim` that will not work OK for some/many colorschemes:
```
" Default color overrides
hi def rcLanguage›      term=reverse ctermbg=Red ctermfg=Yellow guibg=Red guifg=Yellow
hi def rcMainObject›    term=underline ctermfg=Blue guifg=Blue
hi def rcSubObject›     ctermfg=Green guifg=Green
hi def rcCaptionParam›  term=underline ctermfg=DarkGreen guifg=Green
hi def rcParam› ctermfg=DarkGreen guifg=DarkGreen
hi def rcStatement›     ctermfg=DarkGreen guifg=DarkGreen
hi def rcCommonAttribute›       ctermfg=Brown guifg=Brown
```

![image](https://user-images.githubusercontent.com/234774/149666679-93f9c52a-84b2-4f08-91f2-e82e2535c583.png)

@chrisbra 

### Version of Vim

8.2.4103

### Environment

win10, Gvim

**Comment by habamax** [comment]
Found it out with my colorscheme where for example `rcSubObject` is barely visible:

![image](https://user-images.githubusercontent.com/234774/149666916-b40da363-7699-4b4d-bbdc-4ac2a7be4ba6.png)

**Comment by brammool** [comment]
I think it's a bad idea for a syntax file to define colors.  This is very likely to collide with anyone not using standard colors.

**Comment by chrisbra** [comment]
Please check, if my changes make at least some sense 🤔

**Comment by habamax** [comment]
@chrisbra yep, much better.
