### ISSUE TITLE
Repeating "gp" is not very consistent with repeating "gP"

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#9549]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

Both "gp" and "gP" place the cursor one character after the end of the pasted text. IMO this makes repeating "gp" not very consistent with repeating "gP". For example, consider the following buffer content:
```
[]123456789
aaa
bbb
```

If I press `2gg0vjllygg2|gP..........`, the buffer content becomes:
```
[aaa
bbbaaa
bbbaaa
bbbaaa
bbbaaa
bbbaaa
bbbaaa
bbbaaa
bbbaaa
bbbaaa
bbbaaa
bbb]123456789
aaa
bbb
```

All the `aaabbb`s are inside the square brackets.

If I press `2gg0vjllygg0gp..........`, the buffer content becomes:
```
[aaa
bbb]aaa
bbb1aaa
bbb2aaa
bbb3aaa
bbb4aaa
bbb5aaa
bbb6aaa
bbb7aaa
bbb8aaa
bbb9aaa
bbb
aaa
bbb
```

Only the first `aaabbb` is inside the square brackets.

IMO the behavior of "gP" looks more consistent. For example, repeating with `10.` is the same as repeating with `..........` for "gP", but not the same for "gp".

Also, the current cursor placement of "gp" is inconsistent when in the middle of a line and when at the end of the line with `'virtualedit'` disabled, as the cursor cannot be moved past end of the line here. This makes it require extra calculation for a plugin to predict the cursor placement of "gp".

**Describe the solution you'd like**

Make "gp" place the cursor on the last character of the pasted text instead of one character after it. This can also make predicting the cursor placement of "gp" simpler. I'm not sure how much backward compatibility this will break.

**Comment by brammool** [comment]
We can't change this without breaking backwards compatibility.
Instead of repeating "gp" you can use one "gp" and then "gP" and repeat that.
That's not really different from some other put commands, depending on where the cursor ends up you can repeat the same command or need to use another one.
It should not be too difficult to get used to the current behavior.
