### ISSUE TITLE
Vim9: cannot use method call with imported and autoloaded function

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9550]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        var dir = '/tmp/.vim/autoload'
        dir->mkdir('p')
        var lines =<< trim END
            vim9script autoload
            export def Item(arg: string)
                echomsg arg
            enddef
        END
        lines->writefile(dir .. '/script.vim')
        set rtp^=/tmp/.vim
        import autoload 'script.vim'
        def Func()
            'base'->script.Item()
        enddef
        Func()
    EOF
    )

`E121` is given:

    E121: Undefined variable: g:script#Item

**Expected behavior**

No error is given.  `base` is echo'ed.

**Version of Vim**

8.2 Included patches: 1-4128

**Environment**

Operating system: Ubuntu 20.04.3 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: zsh 5.8

**Additional context**

No issue if the method call is used at the script level:
```vim
vim9script
var dir = '/tmp/.vim/autoload'
dir->mkdir('p')
var lines =<< trim END
    vim9script autoload
    export def Item(arg: string)
        echomsg arg
    enddef
END
lines->writefile(dir .. '/script.vim')
set rtp^=/tmp/.vim
import autoload 'script.vim'
'base'->script.Item()
```
    base

---

No issue when using a regular `import/` script (i.e. not autoloaded):
```vim
vim9script
var dir = '/tmp/.vim/import'
dir->mkdir('p')
var lines =<< trim END
    vim9script
    export def Item(arg: string)
        echomsg arg
    enddef
END
lines->writefile(dir .. '/script.vim')
set rtp^=/tmp/.vim
import  'script.vim'
def Func()
    'base'->script.Item()
enddef
Func()
```
    base

**Comment by lacygoill** [comment]
Also, if we try to import an autoloaded script, and Vim fails to find it, a confusing error is given:
```vim
vim9script
var dir = '/tmp/.vim/autoload'
dir->mkdir('p')
['vim9script autoload']->writefile(dir .. '/script.vim')
import autoload 'script.vim'
```
    E1264: Autoload import cannot use absolute or relative path: script.vim

It's confusing because we *can* use a relative path:
```vim
vim9script
var dir = '/tmp/.vim/autoload'
dir->mkdir('p')
['vim9script autoload']->writefile(dir .. '/script.vim')
&runtimepath = '/tmp/.vim'
import autoload 'script.vim'
```
    no error

There is an ambiguity: `script.vim` can be seen as a filename, or as a path relative to `/tmp/.vim/autoload/`.

Anyway, the issue is not that we have used a path (relative or absolute); the issue is simply that we haven't properly updated the runtimepath so that Vim can find the autoload directory containing the script.

A better error message would be:

    E1234: cannot find autoload script "script.vim" in runtimepath

**Comment by lacygoill** [comment]
> It's confusing because we can use a relative path:

Actually, what's really confusing is that Vim refers to `script.vim` as a path, while for the user it seems to be a simple file name.

**Comment by lacygoill** [comment]
> Actually, what's really confusing is that Vim refers to script.vim as a path, while for the user it seems to be a simple file name.

I think the error message should be different depending on whether the argument passed to `import autoload` contains a path separator (slash on Unix-like systems, backslash on Windows?).

**Comment by brammool** [comment]
> **Steps to reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(tee <<'EOF'
>         vim9script
>         var dir = '/tmp/.vim/autoload'
>         dir->mkdir('p')
>         var lines =<< trim END
>             vim9script autoload
>             export def Item(arg: string)
>                 echomsg arg
>             enddef
>         END
>         lines->writefile(dir .. '/script.vim')
>         set rtp^=/tmp/.vim
>         import autoload 'script.vim'
>         def Func()
>             'base'->script.Item()
>         enddef
>         Func()
>     EOF
>     )
> 
> `E121` is given:
> 
>     E121: Undefined variable: g:script#Item

Using disassemble we see that the instructions are trying to load
"script.Item" as a variable:


This happens because "script.Item" is compiled without knowing whether
it is a function reference or something else.

  'base'->script.Item()
   0 PUSHS "base"
   1 LOADG g:script#Item
   2 PCALL (argc 1)

Sourcing it again makes it work, because it uses PUSHFUNC:

  'base'->script.Item()
   0 PUSHS "base"
   1 PUSHFUNC "script#Item"
   2 PCALL (argc 1)

We'll have to deal with this at runtime.

-- 
Windows
M!uqoms

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> This happens because "script.Item" is compiled without knowing whether
   > it is a function reference or something else.

I forgot: the issue only affected a method call:

    # ERROR
    'base'->script.Item()

    # OK
    script.Item('base')

I would have thought that if Vim was able to infer that `script.Item` was a function reference in the second case, it would come to the same conclusion in the first one.

   > We'll have to deal with this at runtime.

The error was already given at runtime.  I hope it doesn't mean that we lose some type checking at compile time when we use a method call.  Otherwise, I might be tempted to avoid methods when calling a function from an import autoload script.

**Comment by brammool** [comment]
> Also, if we try to import an autoloaded script, and Vim fails to find
> it, a confusing error is given:
> ```vim
> vim9script
> var dir = '/tmp/.vim/autoload'
> dir->mkdir('p')
> ['vim9script autoload']->writefile(dir .. '/script.vim')
> import autoload 'script.vim'
> ```
>     E1264: Autoload import cannot use absolute or relative path: script.vim
> 
> It's confusing because we *can* use a relative path:
> ```vim
> vim9script
> var dir = '/tmp/.vim/autoload'
> dir->mkdir('p')
> ['vim9script autoload']->writefile(dir .. '/script.vim')
> &runtimepath = '/tmp/.vim'
> import autoload 'script.vim'
> ```
>     no error
> 
> There is an ambiguity: `script.vim` can be seen as a filename, or as a path relative to `/tmp/.vim/autoload/`.
> 
> Anyway, the issue is not that we have used a path (relative or absolute); the issue is simply that we haven't properly updated the runtimepath so that Vim can find the autoload directory containing the script.
> 
> A better error message would be:
> 
>     E1234: cannot find autoload script "script.vim" in runtimepath

I'll fix that.

-- 
ARTHUR:  Shut up!  Will you shut up!
DENNIS:  Ah, now we see the violence inherent in the system.
ARTHUR:  Shut up!
DENNIS:  Oh!  Come and see the violence inherent in the system!
         HELP! HELP!  I'm being repressed!
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
