### ISSUE TITLE
Autoload-imported scripts are added to the output of :scriptnames even before the script is sourced

### ISSUE THREAD

**Issue by bfrg** [vim/vim#9552]
### Steps to reproduce

Run `vim --clean -S test.vim` with the following two files:

1. File `/tmp/vim/autoload/test.vim`:
   ```vim
   vim9script autoload
   export def Test()
       echomsg 'Hello from autoloaded test.Test()...'
   enddef
   ```
2. File `test.vim`:
   ```vim
   vim9script
   set runtimepath^=/tmp/vim
   import autoload 'test.vim'
   command Test call test.Test()
   ```

In Vim run `:scriptnames`. The output looks like this on my computer:
```
...
 17: /tmp/test.vim
 18: /tmp/vim/autoload/test.vim
```

It looks like `autoload/test.vim` has been sourced.

On the other hand, when running `vim --clean --startuptime foo -S test.vim`, the file `autoload/test.vim` is not listed in the timing file `foo`.

### Expected behaviour

In my opinion, autoload-imported scripts should not be added to the output of `:scriptnames` until the scripts are actually sourced.

### Version of Vim

8.2.4131

### Environment

Linux

**Comment by lacygoill** [comment]
[I agree](https://github.com/lacygoill/wiki/blob/master/bug/vim.md#-27), although, I thought that the script could be listed with a special flag to denote that it had not been really sourced yet.  But maybe not listing the script at all makes more sense.  I don't know.

**Comment by brammool** [comment]
The "import autoload" is checking that the script actually exists, assigns an ID and creates the autoload prefix to be used.
This matters for when the import is used, the prefix is then used in the generated instructions.

We could add something in the ":scriptnames" output to indicate the script is an autoload script that wasn't sourced yet.

**Comment by bfrg** [comment]
`:scriptnames!` is already used, see `:h script`.

**Comment by lacygoill** [comment]
> :scriptnames! is already used, see :h script.

Yes, but only if an argument is passed.  Here, no argument would be passed.  Although, I get what you mean.  The bang would have a different semantics depending on whether an argument is passed, which might look ugly.

**Comment by lacygoill** [comment]
A flag is correctly added, but after the autoload script has been sourced, the flag is removed and the order is not updated:

   >                                                 > *:scr* *:scriptnames*
   > > :scr[iptnames]          List all sourced script names, in the order they were
   >                         > first sourced.

If the autoload script has the ID `123`, but is sourced after the script `456`, it's still positioned in the 123th position.

**Comment by lacygoill** [comment]
To make debugging easier, it would help if the order was updated.  But if this is working as intended, then maybe we should update the help.  Instead of talking about the moment when scripts are sourced, we should talk about the moment when they're assigned an ID:
```diff
diff --git a/runtime/doc/repeat.txt b/runtime/doc/repeat.txt
index 067234a01..7c0803ced 100644
--- a/runtime/doc/repeat.txt
+++ b/runtime/doc/repeat.txt
@@ -378,7 +378,7 @@ For writing a Vim script, see chapter 41 of the user manual |usr_41.txt|.
 
 						*:scr* *:scriptnames*
 :scr[iptnames]		List all sourced script names, in the order they were
-			first sourced.  The number is used for the script ID
+			assigned a number ID, which is used for the script ID
 			|<SID>|.
 			For a script that was used with `import autoload` but
 			was not actually sourced yet an "A" is shown after the
```

**Comment by brammool** [comment]
Right, that help isn't exactly right.  I'll adjust it.
