### ISSUE TITLE
Compilation fails if FEAT_PERSISTENT_UNDO is not included in build

### ISSUE THREAD

**Issue by elcfd** [vim/vim#9557]
### Steps to reproduce

When compiling vim (normal option) I have a use case where I do not want the feature persistent_undo. I removed this feature by commenting out the feature in ``feature.h`` as I believe this is the only way to not include this feature at compile time.

```
diff --git a/src/feature.h b/src/feature.h
iindex 14489968f..3879b7a32 100644
--- a/src/feature.h
+++ b/src/feature.h
@@ -1241,9 +1241,9 @@
  * +persistent_undo	'undofile', 'undodir' options, :wundo and :rundo, and
  * implementation.
  */
-#ifdef FEAT_NORMAL
-# define FEAT_PERSISTENT_UNDO
-#endif
+//#ifdef FEAT_NORMAL
+//# define FEAT_PERSISTENT_UNDO
+//#endif
```

This causes compilation of vim to fail:

```
| fileio.c: In function 'readfile':
| fileio.c:1308:25: error: 'read_undo_file' undeclared (first use in this function); did you mean 'f_undofile'?
|  1308 |                         read_undo_file = FALSE;
|       |                         ^~~~~~~~~~~~~~
|       |                         f_undofile
| fileio.c:1308:25: note: each undeclared identifier is reported only once for each function it appears in
```
I believe the following patch will solve the issue:

```
diff --git a/src/fileio.c b/src/fileio.c
index 1fcf0d983..abccfa63d 100644
--- a/src/fileio.c
+++ b/src/fileio.c
@@ -1300,7 +1300,7 @@ retry:
 		    cryptkey = check_for_cryptkey(cryptkey, ptr, &size,
 						  &filesize, newfile, sfname,
 						  &did_ask_for_key);
-# ifdef CRYPT_NOT_INPLACE
+# ifdef defined(CRYPT_NOT_INPLACE) && defined(FEAT_PERSISTENT_UNDO)
 		    if (curbuf->b_cryptstate != NULL
 				 && !crypt_works_inplace(curbuf->b_cryptstate))
 			// reading undo file requires crypt_decode_inplace()
-- 
```

### Expected behaviour

Successful compilation

### Version of Vim

8.2.3752

### Environment

Ubuntu 20.04

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> When compiling vim (normal option) I have a use case where I do not want the feature persistent_undo. I removed this feature by commenting out the feature in ``feature.h`` as I believe this is the only way to not include this feature at compile time.
> 
> ```
> diff --git a/src/feature.h b/src/feature.h
> iindex 14489968f..3879b7a32 100644
> --- a/src/feature.h
> +++ b/src/feature.h
> @@ -1241,9 +1241,9 @@
>   * +persistent_undo	'undofile', 'undodir' options, :wundo and :rundo, and
>   * implementation.
>   */
> -#ifdef FEAT_NORMAL
> -# define FEAT_PERSISTENT_UNDO
> -#endif
> +//#ifdef FEAT_NORMAL
> +//# define FEAT_PERSISTENT_UNDO
> +//#endif
> ```
> 
> This causes compilation of vim to fail:
> 
> ```
> | fileio.c: In function 'readfile':
> | fileio.c:1308:25: error: 'read_undo_file' undeclared (first use in this function); did you mean 'f_undofile'?
> |  1308 |                         read_undo_file = FALSE;
> |       |                         ^~~~~~~~~~~~~~
> |       |                         f_undofile
> | fileio.c:1308:25: note: each undeclared identifier is reported only once for each function it appears in
> ```
> I believe the following patch will solve the issue:
> 
> ```
> diff --git a/src/fileio.c b/src/fileio.c
> index 1fcf0d983..abccfa63d 100644
> --- a/src/fileio.c
> +++ b/src/fileio.c
> @@ -1300,7 +1300,7 @@ retry:
>  		    cryptkey = check_for_cryptkey(cryptkey, ptr, &size,
>  						  &filesize, newfile, sfname,
>  						  &did_ask_for_key);
> -# ifdef CRYPT_NOT_INPLACE
> +# ifdef defined(CRYPT_NOT_INPLACE) && defined(FEAT_PERSISTENT_UNDO)
>  		    if (curbuf->b_cryptstate != NULL
>  				 && !crypt_works_inplace(curbuf->b_cryptstate))
>  			// reading undo file requires crypt_decode_inplace()
> -- 
> ```

Yes, that looks like the right solution.  I'll make a patch with this.

-- 
BLACK KNIGHT:  Come on you pansy!
    [hah] [parry thrust]
    [ARTHUR chops the BLACK KNIGHT's right arm off]
ARTHUR:        Victory is mine!  [kneeling]
               We thank thee Lord, that in thy merc-
    [Black Knight kicks Arthur in the head while he is praying]
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
