### ISSUE TITLE
gvim starts blank, except for line 1 column 1, sometimes

### ISSUE THREAD

**Issue by jlittlenz** [vim/vim#9560]
### Steps to reproduce

The problem only occurs sometimes; in the simplified case below 1 in 20, but with my normal .vimrc, .gvimrc and file type plugin maybe 1 in 3. Necessary conditions are:
.vimrc has
```
    filetype plugin on
    finish
```
the filetype plugin increases the columns
```
    let &columns = 100
    finish
```
.gvimrc sets the font to a size less than 10
```
    set guifont=Liberation\ Mono\ 8
    finish
```
The whole window is blank, including the status line, except where the cursor is.  If ^L is pressed, the file is drawn normally.  Moving the cursor around the window causes where the cursor goes to be displayed, with the changed parts of the status line.  menu.vim starts with finish.

### Expected behaviour

Text is displayed normally.

### Version of Vim

8.2.4141 with GTK3 GUI

### Environment

Ubuntu 21.10
X windows

**Comment by jlittlenz** [comment]
I'm still getting this, a real nuisance sometimes.  Now with 8.2.5074.

I've just found a workaround, 

`call feedkeys("\<c-l>", "L")`

at the end of .gvimrc.  Without the "L" it didn't help.

**Comment by jlittlenz** [comment]
(My workaround stopped working, perhaps with Vim 9).  

I've reduced to a minimal set of files that shows the problem.  The essential thing is a file type plugin that changes the number of columns.

I've provoked the problem on a fresh Ubuntu 22.04 install, the only change from as installed being to install vim-gtk3, then copy three files to the home directory: lorem.c82, .vim/ftdetect/c82.vim, and .vim/ftplugin/c82.vim.  Note no .vimrc or .gvimrc, or anything else in .vim.  :scriptnames shows only the two c82 files other than scripts from Ubuntu's installation.

I've reproduced an inherently flaky problem by running vim a lot of times from a terminal emulator whose window is not too large (if the window is to big it causes gvim to maximize vertically and the problem doesn't appear.  If the test file is too small the problem is less likely.)
`$ for ((i=1; i<= 40; ++i));do gvim -R lorem.c82;done`
From 40 I might get no blank windows, or one, but often 3 or 4. I'll attach a screen shot showing 3 blank windows and one correct showing the text; the blank windows should like the one with the text.  Note I clicked in the "GVIM7" window and vim drew a couple of characters where I clicked:
![c82](https://user-images.githubusercontent.com/3046559/183242109-39b997f2-5bb3-4150-ad6c-c2c5b99b62c8.png)

Here's a tar of the three files:
[c82.tar.gz](https://github.com/vim/vim/files/9274725/c82.tar.gz)

**Comment by errael** [comment]
This last message made me think of #10123, but further reading makes me think not. The fix, https://github.com/vim/vim/commit/9f53e7bd7f0865585a5447fa3665c5d4c4f91408,  has some logging that can be turned on in src/gui_gtk_x11.c, but if this problem is unrelated then it may be of no use.

**Comment by jlittlenz** [comment]
My current workaround is to do the file type column change at the OS level, in a wrapper script around starting vim, so that vim starts with the right size.

**Comment by jlittlenz** [comment]
Prompted by another issue that may have a GTK race condition, I've just retried my repro procedure and the problem did not occur.  Looking at the commit that errael referred to, which would seem to apply, maybe that fixed it, though I'm unsure about the timing.  I'll undo my workaround and report back after a week or so.

**Comment by jlittledc** [comment]
Yes, the problem hasn't recurred.

**Comment by jlittlenz** [comment]
Yes, the problem hasn't recurred.
