### ISSUE TITLE
script context not always set when using <ScriptCmd>

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9568]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        var n = 123
        nnoremap <F4> <ScriptCmd><CR>
        autocmd CmdlineEnter * silent! nunmap <F4>
        nnoremap <F3> :<ScriptCmd>eval n + 0<CR>
        feedkeys("\<F3>")
    EOF
    )

`E121` is given:

    E121: Undefined variable: n

**Expected behavior**

No error is given because:

   1. `eval n + 0` is executed between `<ScriptCmd>` and `<CR>`
   2. between `<ScriptCmd>` and `<CR>`, the context is set to the script where the mapping is defined
   3. in the script where the mapping is defined, `n` is a defined variable

**Version of Vim**

8.2 Included patches: 1-4146

**Environment**

Operating system: Ubuntu 20.04.3 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: zsh 5.8

**Additional context**

If we remove the autocmd, the issue disappears:
```vim
vim9script
var n = 123
nnoremap <F4> <ScriptCmd><CR>
nnoremap <F3> :<ScriptCmd>eval n + 0<CR>
feedkeys("\<F3>")
```
    no error

If we unmap a different key than `<F4>` (e.g. `<F5>`), again, the issue disappears:
```vim
vim9script
var n = 123
nnoremap <F4> <ScriptCmd><CR>
autocmd CmdlineEnter * silent! nunmap <F5>
nnoremap <F3> :<ScriptCmd>eval n + 0<CR>
feedkeys("\<F3>")
```
    no error

**Comment by 1gahs81** [comment]
can i contbrute to vim?

**Comment by brammool** [comment]
Anyone can contribute
