### ISSUE TITLE
Software vulnerabilities detected during code analysis with ESBMC-WR tool

### ISSUE THREAD

**Issue by janislley** [vim/vim#9571]
### Steps to reproduce

Hello,

3 potential software vulnerabilities were found in code.
To identify this kind of vulnerabilities I used tool ESBMC-WR: https://github.com/thalestas/esbmc-wr

More about the tool: https://arxiv.org/pdf/2102.02368.pdf

Please, check the logs of analysis:

### Expected behaviour

Our main objective was to check memory safety
properties (e.g., pointer dereference and memory leaks) while
performing the verification code.

### Version of Vim

8.2.3908 

### Environment

Ubuntu 20.4

### Logs and stack traces

```shell
issue #1
--------

[FILE] src/xxd/xxd.c

State 1 file xxd.c line 271 function huntype thread 0
----------------------------------------------------
p = 0 (00000000 00000000 00000000 00000000)

State 2 file io.c line 50 function fclose thread 0
----------------------------------------------------
Violated property:
file io.c line 50 function fclose
dereference failure: invalid pointer freed

issue #2
--------

[FILE] runtime/tools/ccfilter.c

State 4  thread 0
----------------------------------------------------
argv[1073741824] = 0

State 5 file ccfilter.c line 131 function main thread 0
----------------------------------------------------
Violated property:
file ccfilter.c line 131 function main
dereference failure: array bounds violated

issue #3
--------

[FILE] src/tee/tee.c

State 1 file tee.c line 72 function myfread thread 0
----------------------------------------------------
Violated property:
file tee.c line 72 function myfread
dereference failure: invalid pointer
```

**Comment by brammool** [comment]
Issue #1: I do not see the "io.c" file, xxd.c line 271 does not call fclose().

Issue #2:  I do not see how using argv[i][0]  can be wrong.  I don't understand the remark "argv[1073741824]"

Issue #3: I do not see how there can be an invalid pointer.

None of these have reproduction steps.  This is not useful, closing.

**Comment by janislley** [comment]
Hello @brammool 
Thank you for the quick update and analysis.

In order to check the reproducibility of the issue 1, follow the steps:

1 - install esbmc-wr: https://pypi.org/project/esbmc-wr/ 
2 - Go to source code: /vim/src/xxd and check the code by command: esbmc-wr -v -e "--unwind 1" -f

Logs details:

########################################
[FILE] xxd.c
[ARGS] ['--unwind', '1']
[FUNCTION] huntype
########################################

ESBMC version 6.7.0 64-bit x86_64 linux
file xxd.c: Parsing
Converting
Generating GOTO Program
GOTO program creation time: 0.107s
GOTO program processing time: 0.002s
Starting Bounded Model Checking
**** WARNING: no body for function perror
**** WARNING: no body for function putc
**** WARNING: no body for function perror
Not unwinding loop 24 iteration 1 file xxd.c line 335 function huntype
Not unwinding loop 27 iteration 1 file xxd.c line 276 function huntype
**** WARNING: no body for function perror
**** WARNING: no body for function perror
**** WARNING: no body for function perror
Symex completed in: 0.002s (170 assignments)
Slicing time: 0.000s (removed 110 assignments)
Generated 4 VCC(s), 4 remaining after simplification (60 assignments)
No solver specified; defaulting to Boolector
Encoding remaining VCC(s) using bit-vector/floating-point arithmetic
Encoding to solver time: 0.000s
Solving with solver Boolector 3.2.0
Encoding to solver time: 0.000s
Runtime decision procedure: 0.078s
Building error trace

Counterexample:

State 1 file xxd.c line 271 function huntype thread 0
----------------------------------------------------
p = 0 (00000000 00000000 00000000 00000000)

State 2 file xxd.c line 291 function huntype thread 0
----------------------------------------------------
n1 = 8 (00000000 00000000 00000000 00001000)

State 3 file xxd.c line 328 function huntype thread 0
----------------------------------------------------
have_off = -9223372036854775808 (10000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000)

State 4 file xxd.c line 276 function huntype thread 0
----------------------------------------------------
Violated property:
file xxd.c line 276 function huntype
unwinding assertion loop

VERIFICATION FAILED

**Comment by k-takata** [comment]
What is the exact version of Vim you are using?
You wrote 8.2.3908, but line 271 of that version is not in the function huntype.

**Comment by janislley** [comment]
Hello @k-takata 

Line 271 is:
`int c, ign_garb = 1, n1 = -1, n2 = 0, n3, p = cols;`

**Comment by chrisbra** [comment]
can you please be specific on what version you tested?

https://github.com/vim/vim/blob/27708e6c7b6f444fd599f3dc5015336b002b874d/src/xxd/xxd.c#L270-L273

L271 for neither master nor v8.2.3908 isn't that line.

**Comment by k-takata** [comment]
@janislley It looks that it is v8.2.3552 or older.
There are many changes in xxd.c after that. Could you test with the latest source code?

**Comment by brammool** [comment]
> Hello @brammool 
> Thank you for the quick update and analysis.
> 
> In order to check the reproducibility of the issue 1, follow the steps:
> 
> 1 - install esbmc-wr: https://pypi.org/project/esbmc-wr/ 
> 2 - Go to source code: /vim/src/xxd and check the code by command: esbmc-wr -v -e "--unwind 1" -f
> 
> Logs details:
> 
> ########################################
> [FILE] xxd.c
> [ARGS] ['--unwind', '1']
> [FUNCTION] huntype
> ########################################
> 
> ESBMC version 6.7.0 64-bit x86_64 linux
> file xxd.c: Parsing
> Converting
> Generating GOTO Program
> GOTO program creation time: 0.107s
> GOTO program processing time: 0.002s
> Starting Bounded Model Checking
> **** WARNING: no body for function perror
> **** WARNING: no body for function putc
> **** WARNING: no body for function perror
> Not unwinding loop 24 iteration 1 file xxd.c line 335 function huntype
> Not unwinding loop 27 iteration 1 file xxd.c line 276 function huntype
> **** WARNING: no body for function perror
> **** WARNING: no body for function perror
> **** WARNING: no body for function perror
> Symex completed in: 0.002s (170 assignments)
> Slicing time: 0.000s (removed 110 assignments)
> Generated 4 VCC(s), 4 remaining after simplification (60 assignments)
> No solver specified; defaulting to Boolector
> Encoding remaining VCC(s) using bit-vector/floating-point arithmetic
> Encoding to solver time: 0.000s
> Solving with solver Boolector 3.2.0
> Encoding to solver time: 0.000s
> Runtime decision procedure: 0.078s
> Building error trace
> 
> Counterexample:
> 
> State 1 file xxd.c line 271 function huntype thread 0
> ----------------------------------------------------
> p = 0 (00000000 00000000 00000000 00000000)
> 
> State 2 file xxd.c line 291 function huntype thread 0
> ----------------------------------------------------
> n1 = 8 (00000000 00000000 00000000 00001000)
> 
> State 3 file xxd.c line 328 function huntype thread 0
> ----------------------------------------------------
> have_off = -9223372036854775808 (10000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000)
> 
> State 4 file xxd.c line 276 function huntype thread 0
> ----------------------------------------------------
> Violated property:
> file xxd.c line 276 function huntype
> unwinding assertion loop
> 
> VERIFICATION FAILED

This doesn't mean anything to me.  With reproducing the issue I mean to
run xxd with some parameters and input, resulting in a crash, asan or
valgrind error.  Static analysis very often has false positives.

-- 
There is no right or wrong, there is only your personal opinion.
                 (Bram Moolenaar)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
