### ISSUE TITLE
Changing another window with the same buffer to another buffer while editing breaks undo history

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#9575]
### Steps to reproduce

1. Same these lines as `/tmp/tmp.vim`:
```vim
new
buffer 1
wincmd w
call setline(1, ['test'])
autocmd InsertEnter * call timer_start(1000, { -> win_execute(1001, 'buffer 2') })
```
2. Run `vim --clean -S /tmp/tmp.vim`
3. Press `O` (this is upper-case `O`)
4. Type `aaaaa` quickly and wait for one second
5. Press `<CR>` and type `bbbbb`
6. Press `<Esc>`
7. Press `u`
8. Buffer content becomes:
```
bbbbb
test
```
The `aaaaa` typed first is undone, while the `bbbbb` typed after it is not.

### Expected behaviour

Buffer content becomes:
```
test
```
Both the `aaaaa` and the `bbbbb` are undone.

### Version of Vim

8.2.4156

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish 3.3.1

**Comment by brammool** [comment]
Well, this is a bit of a corner case.  Typing "u" again also removes "bbbb".  But an empty line remains.
I can fix this specific situation, but it is not unusual for undo to be synced when something is done with the buffer, also when in a timer.

**Comment by flaphoschi** [comment]
Thank you brammool :slightly_smiling_face:
