### ISSUE TITLE
vim9: vim9CommentTitle syntax match is not defined

### ISSUE THREAD

**Issue by craigmac** [vim/vim#9587]
vim9CommentTitle should be defined right here, but we are missing that one:

https://github.com/vim/vim/blob/e70dd11ef41f69bd5e94f630194e6b3c4f3f2102/runtime/syntax/vim.vim#L652

I don't know much about the complexitites of this so didn't dare touch it.

**Comment by chrisbra** [comment]
ping @cecamp

**Comment by chrisbra** [comment]
Hi @craigmac is this still relevant?
