### ISSUE TITLE
Strange problem with syntax hilighting in .txt files.

### ISSUE THREAD

**Issue by moon-chilled** [vim/vim#959]
I'm not quite sure how to describe this bug, so I'll just explain how to reproduce it.  Basically, open vim on a new .txt file (it doesn't appear to work for other types of files).  Type on open curly-brace, enter, close-curly-brace.  Then `O`, and you'll be in insert mode in between the curly braces.  The bottom curly-brace will continue to be hilighted no matter what you insert between the braces.  This is also present a little bit with square brackets and parentheses &mdash; with those, the bottom brace will continue to be hilighted after pressing `O`, but not after <enter> is pressed.

**Comment by chrisbra** [comment]
sounds like the showmatch setting being somehow reset. Please give complete reproducible example [see faq](https://vimhelp.appspot.com/vim_faq.txt.html#faq-2.5) and also mention your complete :version output.

**Comment by brammool** [comment]
I recall a problem with matchit in Insert mode that was fixed several months ago.  Please get the latest matchit version.

**Comment by k-takata** [comment]
> I recall a problem with matchit in Insert mode that was fixed several months ago.

I'm closing this.
