### ISSUE TITLE
Vim9: `exists()` cannot test existence of imported autoload function

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9598]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        var dir = '/tmp/.vim'
        &runtimepath = dir
        dir ..= '/autoload'
        dir->mkdir('p')
        var lines =<< trim END
            vim9script
            export def Func()
                echomsg 'from Func()'
            enddef
        END
        lines->writefile(dir .. '/script.vim')
        import autoload 'script.vim'
        script.Func()
        echomsg exists('*script.Func')
    EOF
    )

This is echo'ed:

    from Func()
    0

**Expected behavior**

This is echo'ed:

    from Func()
    1

Because the `script.Func` name translates to the `script#Func` name, which – at the time `exists()` is invoked – does match an existing function; it was called right before, causing Vim to look up its definition in the autoloaded `script.vim`.

**Version of Vim**

8.2 Included patches: 1-4186

**Environment**

Operating system: Ubuntu 20.04.3 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: zsh 5.8

**Additional context**

No issue if we use the translated name of the autoload function:

    :echomsg exists('*script#Func')
    1

Test:
```vim
vim9script
var dir = '/tmp/.vim'
&runtimepath = dir
dir ..= '/autoload'
dir->mkdir('p')
var lines =<< trim END
    vim9script
    export def Func()
        echomsg 'from Func()'
    enddef
END
lines->writefile(dir .. '/script.vim')
import autoload 'script.vim'
script#Func()
echomsg exists('*script#Func')
```
    from Func()
    1

**Comment by lacygoill** [comment]
Actually, it works if we remove the star:

    ✘
    echomsg exists('*script.Func')

    ✔
    echomsg exists('script.Func')

So, I guess the issue can be closed.  Although, we might want to update [`:help exists()`](https://vimhelp.org/builtin.txt.html#exists%28%29), because this is not currently documented.
```diff
diff --git a/runtime/doc/builtin.txt b/runtime/doc/builtin.txt
index 403f592fc..c1c8e7010 100644
--- a/runtime/doc/builtin.txt
+++ b/runtime/doc/builtin.txt
@@ -2093,6 +2093,8 @@ exists({expr})	The result is a Number, which is |TRUE| if {expr} is defined,
 					|user-functions|) that is implemented.
 					Also works for a variable that is a
 					Funcref.
+					For an imported function, the asterisk
+					must be removed.
 			?funcname	built-in function that could be
 					implemented; to be used to check if
 					"funcname" is valid
@@ -2141,6 +2143,7 @@ exists({expr})	The result is a Number, which is |TRUE| if {expr} is defined,
 			exists("$HOSTNAME")
 			exists("*strftime")
 			exists("*s:MyFunc")
+			exists("import.MyFunc")
 			exists("bufcount")
 			exists(":Make")
 			exists("#CursorHold")
```

**Comment by lacygoill** [comment]
> Although, we might want to update :help exists(), because this is not currently documented.

One could argue that it's already documented, because `script` is some kind of dictionary, and `Func` one of its keys.  So, this is covered by this excerpt:

   > varname         internal variable (see
   >                 |internal-variables|).  Also works
   >                 for |curly-braces-names|, |Dictionary|
   >                 entries, |List| items, etc.

But it's not obvious that `script` is a regular dictionary variable.  It's special.  For example, we can't use `has_key()` with it:
```vim
vim9script
var dir = '/tmp/.vim'
&runtimepath = dir
dir ..= '/autoload'
dir->mkdir('p')
var lines =<< trim END
    vim9script
    export def Func()
        echomsg 'from Func()'
    enddef
END
lines->writefile(dir .. '/script.vim')
import autoload 'script.vim'
script.Func()
echomsg has_key('script', 'Func')
```
    E1206: Dictionary required for argument 1
```vim
vim9script
var dir = '/tmp/.vim'
&runtimepath = dir
dir ..= '/autoload'
dir->mkdir('p')
var lines =<< trim END
    vim9script
    export def Func()
        echomsg 'from Func()'
    enddef
END
lines->writefile(dir .. '/script.vim')
import autoload 'script.vim'
script.Func()
echomsg script->has_key('Func')
```
    E1060: Expected dot after name: script->has_key('Func')

**Comment by brammool** [comment]
I'll mention import.Func explicitly.  Also adding an example for dict and list items.
