### ISSUE TITLE
no sublist error

### ISSUE THREAD

**Issue by nhooyr** [vim/vim#960]
Under `:h sublist` it says that "indexes out of range cause an error".

So why does `:echo [1,2][5:9]` not cause an error?

**Comment by grochmal** [comment]
That is the correct behaviour, this is explained in `:h list-index`

```
If the first index is beyond the last item of the List or the second item is
before the first item, the result is an empty list.  There is no error
message.

If the second index is equal to or greater than the length of the list the
length minus one is used: 
```

Therefore the empty list should be (and is) returned.  i.e. `[1,2][5:9]` is evaluated as `[1,2][5:]`, the `9` does not need to be even checked.

Funny enough this is analogous to the behaviour of lists in `python`.

**Comment by nhooyr** [comment]
Shouldn't the docs under sublist be changed to reflect that?
