### ISSUE TITLE
Ability to clear only one type of cmdline history

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#9622]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

AFAIK there is currently no way to clear only one type of cmdline history (e.g. debug mode history only) without clear all types cmdline history (by setting `'history'` to `0`).

**Describe the solution you'd like**

Add a feature to clear only one type of cmdline history.

**Comment by vim-ml** [comment]
Hi,

On Mon, Jan 24, 2022 at 7:09 PM zeertzjq ***@***.***> wrote:

> *Is your feature request about something that is currently impossible or
> hard to do? Please describe the problem.*
>
> AFAIK there is currently no way to clear only one type of cmdline history
> (e.g. debug mode history only) without clear all types cmdline history (by
> setting 'history' to 0).
>
> *Describe the solution you'd like*
>
> Add a feature to clear only one type of cmdline history.
>
>
>
Can't you use the histdel({history}) function to clear only one type of
cmdline history?
e.g. :call histdel("debug")

- Yegappan

**Comment by zeertzjq** [comment]
Oh, I didn't notice this function.
