### ISSUE TITLE
`winsaveview()` is not always current after `CursorMoved` event

### ISSUE THREAD

**Issue by echasnovski** [vim/vim#9625]
### Steps to reproduce

1. `vim --clean -u NONE`.
2. `:set nowrap | let g:counter=0`
3. `:au CursorMoved * let g:counter+=1 | echo '#' . g:counter . ' leftcol=' . winsaveview()['leftcol']`
4. Type `abcde` and move cursor to first column.
5. Execute `zl` two times (should scroll window horizontally by two columns, correctly showing current `leftcol` in the meantime).
6. Move cursor to left (**should show that `leftcol=2` when it is currently equal to 0**).
7. Move cursor to right (should show current `leftcol`).

<details>
<summary>Animation of behavior</summary>

![vim_cursormoved-winsaveview-leftcol](https://user-images.githubusercontent.com/24854248/151007057-5f1d3fda-626a-4a95-821f-2f84ff5f4dfb.gif)

</details>

### Expected behaviour

`winsaveview()` always contains "current"  information (meaning such, which user can visually verify after `CursorMoved` event). Similar to how `col('.')` shows cursor "current" position.

This seems to indicate that window data is updated *after* `CursorMoved` event, which is unfortunate.

My true goal is to get horizontal offset (the most left buffer column shown in the window) after every cursor movement. After searching, #7190 stated that `leftcol` from `winsaveview()` is the way to get this information at the moment.

### Version of Vim

8.2.4051

### Environment

OS: Ubuntu 20.04
Terminal: kitty 0.23.1
Value of `$TERM`: xterm-kitty
Shell: zsh 5.8

**Comment by brammool** [comment]
This happens because CursorMoved is triggered before the screen is redrawn.
I don't think we should force a redraw just because someone might use "leftcol" in a CursorMoved autocommand.
You can put "redraw" in the autocommand to fix it.
