### ISSUE TITLE
Vim9: unexpected error when extending undeclared list

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9626]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        def GetList(): list<number>
            var l: list<number> = [0]
            return l
        enddef
        echo GetList()->extend(['a'])
    EOF
    )

`E1013` is given:

    E1013: Argument 2: type mismatch, expected list<number> but got list<string> in extend()

**Expected behavior**

No error is given, because since patch [8.2.3994](https://github.com/vim/vim/releases/tag/v8.2.3994), `extend()` is meant to complain only when the type of its first argument was declared.  But here, its first argument is `GetList()` which is not declared; it's just a value.

**Version of Vim**

8.2 Included patches: 1-4219

**Environment**

Operating system: Ubuntu 20.04.3 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: zsh 5.8

**Additional context**

If we don't declare the type of `l` in `GetList()`, no error is given:
```vim
vim9script
def GetList(): list<number>
    var l = [0]
    return l
enddef
echo GetList()->extend(['a'])
```
    [0, 'a']

This is inconsistent.  This is also unexpected, because the specified type `list<number>` is correct, and should be identical to the one inferred by Vim.  So, why does it matter whether we write it explicitly or not?

**Comment by lacygoill** [comment]
> But here, its first argument is GetList() which is not declared; it's just a value.

Actually, it's just a list with one number inside: `[0]`.
That list is assigned to a variable with a declared type inside the `GetList()` function: `l`.  But `l` is local to the function.  At the time `extend()` receives `[0]`, `l` no longer exists.  What `extend()` receives is just the list `[0]`, which is not assigned to any declared variable.

**Comment by brammool** [comment]
The returned list has type list<number> from the variable declaration.
This type sticks to the list when it is passed on.  Thus appending a string item is an error.

In the "additional context" example the list itself is not declared to be list<number>
When the type is checked in the return statement, the runtime type is found to be correct.

In my opinion this is OK.

**Comment by lacygoill** [comment]
> This type sticks to the list when it is passed on.

Not sure, but I think it will be surprising to users that the type sticks beyond the existence of the variable.  But that's not a big issue right now.  If I'm wrong, nothing needs to be changed.  If I'm right, and enough people complain in the future, we could still change this without breaking compatibility with existing scripts.

   > When the type is checked in the return statement, the runtime type is found to be correct.

I guess it means that there is a fundamental difference between a declared type and an inferred one: a declared type sticks beyond the existence of the variable; an inferred one does not.  Maybe this should be documented.  I'll try to come up with a patch later.
