### ISSUE TITLE
incsearch highlight broken when calling searchcount in TabLine() function

### ISSUE THREAD

**Issue by derbroti** [vim/vim#9633]
### Steps to reproduce

0. build 8.2.4221 with default configure options

1. set minimal vimrc
```
set nocompatible
set hlsearch
set incsearch
set showtabline=2

function MyTabLine()
  call searchcount(#{recompute: 1, maxcount: -1})
  return ''
endfunction

:set tabline=%!MyTabLine()
```
2. Testfile:
```
abc--c
--------abc
--abc
```

3. start search:
/abc

4. move to next match (3 times) to highlight each of the "abc" matches individually, one after the other
CTRL-G

but what happens:
- when in the first line "abc--" is highlighted
- when in the second line nothing is highlighted
- when in the third line: "abc" 

### Expected behaviour

Each "abc", nothing more, nothing less, should be highlighted, one after another by moving though the matches.

(Why would one call searchcount in the Tabline? -> I wrote a plugin that shows the current search (incsearch) in the Tabline - it works but calling searchcount in the tabline function messes up the insearch highlighting when stepping through the matches.

### Version of Vim

8.2.4221

### Environment

MacOS 12.1
iTerm2 3.14.15
zsh 5.8 (x86_64-apple-darwin21.0)
xterm-256color

**Comment by chrisbra** [comment]
so is the isssue, that we `update_search_stat()` is called recursively and we need to save and restore those state variables? Or would it be enough to prevent running this recursively?

**Comment by brammool** [comment]
I don't see how it is used recursively.
The problem appears to be that searchcount() calls update_search_stat() with a different pattern, which pollutes the static variables.  I haven't looked at it in a debugger, but I suspect that is the problem.

**Comment by chrisbra** [comment]
ah okay. I'll have a look at it this weekend

**Comment by derbroti** [comment]
May I cautiously poke if there is any update on this?

**Comment by chrisbra** [comment]
Hm, the pattern does not really change. The fix here: https://github.com/vim/vim/compare/master...chrisbra:gh_9633?expand=1 basically prevents calling f_searchcount() when we are currently calculating the new searchstats(). It also prevents this error here. Not sure if this is the right fix however.

**Comment by chrisbra** [comment]
@brammool let me know what you think

**Comment by brammool** [comment]
This doesn't look right.  the "ctx" field is set but never used.
Bailing out from f_searchstat() means that it won't work.

**Comment by chrisbra** [comment]
Okay, I had another look. The problem is not the search_stat functions, but that the `search_match_` highlighting variables are overwritten before they have been used in the `win_line()` function. So I think we need to save and restore those variables at least for the `searchcount()` function, because I do not think that function should influence the incsearch highlighting at all.
