### ISSUE TITLE
Vim9: cannot omit `g:` to call global function after same name being found in script-local namespace

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9637]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        var lines =<< trim END
            vim9script
            def g:Func()
                echomsg 'from Func()'
            enddef
            Func()
        END
        lines->writefile('/tmp/t.vim')
        silent edit /tmp/t.vim
        source %
        silent :2 substitute/g:// | silent update
        source %
        silent undo | silent update
        source %
    EOF
    )

`from Func()` is echo'ed twice, then `E117` is given:

    E117: Unknown function: Func

**Expected behavior**

`from Func()` is echo'ed three times.  No error is given.

Because when we refer to a function without an explicit scope, as a last resort Vim looks in the global namespace:

    When referring to a function and no "s:" or "g:" prefix is used, Vim will
    search for the function:
    - in the function scope, in block scopes
    - in the script scope, possibly imported
    - in the list of global functions

source: [`:help vim9-scopes`](https://vimhelp.org/vim9.txt.html#vim9-scopes)

**Version of Vim**

8.2 Included patches: 1-4227

**Environment**

Operating system: Ubuntu 20.04.3 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: zsh 5.8

**Additional context**

No issue if we write the global scope `g:` explicitly in the `Func()` call:

    Func()
    →
    g:Func()

Test:
```vim
vim9script
var lines =<< trim END
    vim9script
    def g:Func()
        echomsg 'from Func()'
    enddef
    g:Func()
END
lines->writefile('/tmp/t.vim')
silent edit /tmp/t.vim
source %
silent :2 substitute/g:// | silent update
source %
silent undo | silent update
source %
```
    from Func()
    from Func()
    from Func()

---

The issue disappears if we pass `noclear` to `:vim9script`:
```vim
vim9script
var lines =<< trim END
    vim9script noclear
    def g:Func()
        echomsg 'from Func()'
    enddef
    Func()
END
lines->writefile('/tmp/t.vim')
silent edit /tmp/t.vim
source %
silent :2 substitute/g:// | silent update
source %
silent undo | silent update
source %
```
    from Func()
    from Func()
    from Func()

This is unexpected.  `noclear` only determines whether script-local items will be cleared on reload.  It is not documented that it can also have an effect on global items.

---

It seems that after finding `Func()` in the script-local namespace, Vim no longer considers the possibility that it could also be defined in the global one.  Should it?

**Comment by lacygoill** [comment]
Not enforcing `g:` when calling a global function lets people write confusing code.  When we read a function call without `g:`, it's not always easy to know whether it refers to a global function or a script-local one.

We cannot omit `g:`:

   - when defining a global variable
   - when defining a global function
   - when referring to a global variable

But we can when referring to a global function.  Unless the referrence is compiled, and the global function does not exist at compile time:
```vim
vim9script
def Func()
    Global()
enddef
defcompile
def g:Global()
enddef
```
    E117: Unknown function: Global

This can happen when we refer to a global function provided by a third-party plugin which is sourced later.  `g:` fixes the issue:
```vim
vim9script
def Func()
    g:Global()
enddef
defcompile
def g:Global()
enddef
```
    no error

Enforcing `g:` would have several benefits:

   - the syntax would be more consistent (no need to remember the rules to know whether `g:` can be omitted)
   - the code would be more readable (no need to guess whether the function is global or local)
   - no unexpected error in compiled code

It would also avoid unexpected errors such as the one given in the OP.

**Comment by lacygoill** [comment]
It's even recommended at [`:help vim9-scopes`](https://vimhelp.org/vim9.txt.html#vim9-scopes):

> However, it is recommended to always use "g:" to refer to a global function
> for clarity.

Why not go all the way, and enforce it?

**Comment by brammool** [comment]
It is indeed inconsistent to require g: for a global variable, but not require it for a global function.
Also that the g: is required when defining a global function, but not when calling it.

It can also hide mistakes in a function name, if a global function happens to exist the wrong function may be called.
This has only a small chance, but when it happens it can be hard to figure out.

I wonder if there is a good argument to keep the current behavior.

**Comment by lacygoill** [comment]
> It can also hide mistakes in a function name, if a global function happens to exist the wrong function may be called.
   > This has only a small chance, but when it happens it can be hard to figure out.

Ah right.  I forgot about this pitfall.  Losing time debugging this kind of issue is annoying.

   > I wonder if there is a good argument to keep the current behavior.

I think allowing `g:` to be omitted is a leftover from legacy, where everything is global by default.  It seems weird to perpetuate this in Vim9, where the opposite is true: everything is script-local by default.

Another reason to keep this allowed might be that it's convenient.  But in a real plugin, we rarely call global functions.  Most of the code should be local to the script to avoid collisions in the user's global namespace which we know nothing about.  Besides, that's just 2 extra characters to write.  It's a small price to pay for a more reliable and readable code.

Also, if we enforce `g:`, we probably can get rid of [`exists_compiled()`](https://vimhelp.org/builtin.txt.html#exists_compiled%28%29).  I prefer to read this:
```vim
vim9script
def Func()
    g:Global()
enddef
defcompile
def g:Global()
enddef
```
Than this:
```vim
vim9script
def Func()
    if exists_compiled('Global')
        Global()
    endif
enddef
defcompile
def g:Global()
enddef
```
FWIW, I never had to use `exists_compiled()`.  When I had an error at compile time, using `g:` instead has always fixed the issue.  And IMO it's nicer to read, because it's less verbose, and doesn't refer to compile time.  When I read a *working* function, I only want to know what it will do at runtime.  I don't want to also think about how Vim will handle compile time.

**Comment by lacygoill** [comment]
> FWIW, I never had to use exists_compiled().

In fact, it seems that `exists_compiled()` is not reliable:
```vim
vim9script
def Func()
    if exists_compiled('Global')
        Global()
    endif
enddef
defcompile
def g:Global()
    echomsg 'from Global()'
enddef
Func()
```
Notice that no message is echo'ed, because at compile time `Global()` did not exist.  But it does exist at the time `Func()` is finally called.

Suppose that `Global()` is provided by a third-party plugin, and the user wants to call it from `Func()`.  If they omit `g:`, they need to make sure that `Func()` will not be compiled before `Global()` is defined.  Otherwise, an error is given:
```vim
vim9script
def Func()
    Global()
enddef
defcompile
```
    E117: Unknown function: Global

And using `exists_compiled()` won't help:
```vim
vim9script
def Func()
    if exists_compiled('Global')
        Global()
    endif
enddef
defcompile
def g:Global()
    echomsg 'from Global()'
enddef
Func()
```
Notice that the error was correctly suppressed, but `from Global()` was not echo'ed.  `Func()` is broken: it doesn't call `Global()` as the user wants it to.

The solution is to write `g:` explicitly:
```vim
vim9script
def Func()
    g:Global()
enddef
defcompile
def g:Global()
    echomsg 'from Global()'
enddef
Func()
```
    from Global()

**Comment by lacygoill** [comment]
> The solution is to write g: explicitly:

Or use `call()`:
```vim
vim9script
def Func()
    call('Global', [])
enddef
defcompile
def g:Global()
    echomsg 'from Global()'
enddef
Func()
```
But IMO `g:Global()` is nicer to read.  In any case, I don't see the need for `exists_compiled()`.

**Comment by brammool** [comment]
>    > FWIW, I never had to use exists_compiled().
> 
> In fact, it seems that `exists_compiled()` is not reliable:
> ```vim
> vim9script
> def Func()
>     if exists_compiled('Global')
>         Global()
>     endif
> enddef
> defcompile
> def g:Global()
>     echomsg 'from Global()'
> enddef
> Func()
> ```
> Notice that no message is echo'ed, because at compile time `Global()`
> did not exist.  But it does exist at the time `Func()` is finally
> called.

This specific example is tricky, because the second time you source it
something else happens.  This is easily seen when using "disassemble
Func" instead of "defcompile":  the first time "Global" does not exist
and the result of exists_compiled() is false, resulting in the while
"if" block to be dropped.

Even though it is tricky, it might be needed in some situations.

-- 
SUPERIMPOSE "England AD 787".  After a few more seconds we hear hoofbeats in
the distance.  They come slowly closer.  Then out of the mist comes KING
ARTHUR followed by a SERVANT who is banging two half coconuts together.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
There might be another inconsistency related to the omission of the `g:` prefix.

We can omit `g:` in front of the name of an autoload function in its header, and at any call site:
```vim
vim9script
var dir = '/tmp/.vim'
dir->delete('rf')
&runtimepath = dir
dir ..= '/autoload'
dir->mkdir('p')
var lines =<< trim END
    vim9script
    def script#func()
        echomsg 'script#func()'
    enddef
END
lines->writefile(dir .. '/script.vim')
script#func()
```
    script#func()

But we cannot omit `g:` when *declaring* an autoload variable:
```vim
vim9script
var script#num = 123
```
    E461: Illegal variable name: script#num
```vim
vim9script
script#num = 123
```
    E1144: Command "script" is not followed by white space: script#num = 123
```vim
vim9script
g:script#num = 123
```
    no error

However, we can omit `g:` when *referring* to an autoload variable:
```vim
vim9script
g:script#num = 123
echo script#num
```
    123

Allowing to drop `g:` when declaring an autoload variable would make the rules simpler to remember, and more consistent.

**Comment by brammool** [comment]
> There might be another inconsistency related to the omission of the `g:` prefix.
> 
> We can omit `g:` in front of the name of an autoload function in its header, and at any call site:
> ```vim
> vim9script
> var dir = '/tmp/.vim'
> dir->delete('rf')
> &runtimepath = dir
> dir ..= '/autoload'
> dir->mkdir('p')
> var lines =<< trim END
>     vim9script
>     def script#func()
>         echomsg 'script#func()'
>     enddef
> END
> lines->writefile(dir .. '/script.vim')
> script#func()
> ```
>     script#func()
> 
> But we cannot omit `g:` when *declaring* an autoload variable:
> ```vim
> vim9script
> var script#num = 123
> ```
>     E461: Illegal variable name: script#num
> ```vim
> vim9script
> script#num = 123
> ```
>     E1144: Command "script" is not followed by white space: script#num = 123
> ```vim
> vim9script
> g:script#num = 123
> ```
>     no error
> 
> However, we can omit `g:` when *referring* to an autoload variable:
> ```vim
> vim9script
> g:script#num = 123
> echo script#num
> ```
>     123
> 
> Allowing to drop `g:` when declaring an autoload variable would make
> the rules simpler to remember, and more consistent.

The main use of a Vim9 autoload script is to use "export" for those
things that should be visible externally.  Currently in some places the
scriptname#itemname form is still allowed.  I have been wondering if we
should disallow this, and insist on using "export".

Whether using "g:" is needed or not is a secondary choice.  If we
disallow the form with "#" then it's irrelevant.

The "export" way has an important advantage: the name of the file can be
changed without changing the file contents.  Well, the place the
autoload script is imported still needs to change, of course.

Is there any good reason to define a function with the "scriptname#Func"
name, instead of using an export?  If not, then we could disallow it.


-- 
There are two ways of constructing a software design. One way is to make
it so simple that there are obviously no deficiencies. The other way
is to make it so complicated that there are no obvious deficiencies.
                                                           -C.A.R. Hoare

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> Whether using "g:" is needed or not is a secondary choice.  If we
> disallow the form with "#" then it's irrelevant.

But an autoload variable is not necessarily declared in an autoload script.  It can be declared anywhere, including in a regular plugin script under `plugin/`.

From [`:help autoload`](https://vimhelp.org/eval.txt.html#autoload):

   > When assigning a value to such a variable nothing special happens.  This can
   > be used to pass settings to the autoload script before it's loaded: >
   >
   >         :let foo#bar#toggle = 1
   >         :call foo#bar#func()

Are we meant to be allowed to write `:export` outside `import/` and `autoload/`?  It does not give any error when written under `plugin/`.  But the `path#to#script#` prefix is obviously not added, so we can't write `script#num` to refer to an autoload variable.  However, we can import it, so we can refer to it with `script.num`:
```vim
vim9script
var dir = '/tmp/.vim'
dir->delete('rf')
&runtimepath = dir
dir ..= '/plugin'
dir->mkdir('p')
var lines =<< trim END
    vim9script
    export const PI = 3.14159
END
lines->writefile(dir .. '/script.vim')
import dir .. '/script.vim'
echo script.PI
```
    3.14159

If we are allowed to write `:export` anywhere, then yes, whether `g:` can be omitted or not is no longer an issue.

> Is there any good reason to define a function with the "scriptname#Func"
> name, instead of using an export?  If not, then we could disallow it.

I have 470 autoload functions.  Not one of them needs to use the `scriptname#Func` name.  So I guess it would be OK.

**Comment by brammool** [comment]
> > Whether using "g:" is needed or not is a secondary choice.  If we
> > disallow the form with "#" then it's irrelevant.
> 
> But an autoload variable is not necessarily declared in an autoload
> script.  It can be declared anywhere, including in a regular plugin
> script under `plugin/`.

The system can be abused, yes.  But this is a side effect of how it was
implemented, and no effort was made to disallow it.  I think it would be
good to disallow it in Vim9 script, because it does look like abuse and
not valid usage.

> From [`:help autoload`](https://vimhelp.org/eval.txt.html#autoload):
> 
>    > When assigning a value to such a variable nothing special happens.  This can
>    > be used to pass settings to the autoload script before it's loaded: >
>    >
>    >         :let foo#bar#toggle = 1
>    >         :call foo#bar#func()

That happened to work, but is now defenitely not the right way.
Script-local items must be defined in the script.

> Are we meant to be allowed to write `:export` outside `import/` and
> `autoload/`?

Sure.  You can import with a relative path.  Scripts under "import" will
be found if the import does not use a relative or absolute path.

For a script under "autoload" the directory name is meaningful.

> It does not give any error when written under `plugin/`.
> But the `path#to#script#` prefix is obviously not added, so we can't
> write `script#num` to refer to an autoload variable.  However, we can
> import it, so we can refer to it with `script.num`:
> ```vim
> vim9script
> var dir = '/tmp/.vim'
> dir->delete('rf')
> &runtimepath = dir
> dir ..= '/plugin'
> dir->mkdir('p')
> var lines =<< trim END
>     vim9script
>     export const PI = 3.14159
> END
> lines->writefile(dir .. '/script.vim')
> import dir .. '/script.vim'
> echo script.PI
> ```
>     3.14159
> 
> If we are allowed to write `:export` anywhere, then yes, whether `g:`
> can be omitted or not is no longer an issue.
> 
> > Is there any good reason to define a function with the "scriptname#Func"
> > name, instead of using an export?  If not, then we could disallow it.
> 
> I have 470 autoload functions.  Not one of them needs to use the
> `scriptname#Func` name.  So I guess it would be OK.

I'll have a look at making this stricter.


-- 
"I've been teaching myself to play the piano for about 5 years and now write
most of my songs on it, mainly because I can never find any paper."
		Jeff Lynne, ELO's greatest hits

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
The patch [8.2.4257](https://github.com/vim/vim/releases/tag/v8.2.4257) correctly requires `g:` to call a global function in compiled code:
```vim
vim9script
def g:Func()
    echomsg 'from Func()'
enddef
def Foo()
    Func()
enddef
Foo()
```
    E117: Unknown function: Func

But not at the script-level:
```vim
vim9script
def g:Func()
    echomsg 'from Func()'
enddef
Func()
```
    from Func()

---

Also, we can still refer to a global function without `g:`, using `call()` for example, even in compiled code:
```vim
vim9script
def g:Func()
    echomsg 'from Func()'
enddef
def Foo()
    call(Func, [])
enddef
Foo()
```
    from Func()

**Comment by brammool** [comment]
This should now all be taken care of.  The impact of requiring "g:" is bigger than I anticipated, especially in tests.  Before this change a function name would be used without worrying about whether it was global or script-local, now it matters.  That is good by itself, but can make things a bit more complicated.  Especially the functions to support testing were global.  Using an import is cleaner, but it's quite a lot of work, as the change to import "vim9.vim" shows.

**Comment by lacygoill** [comment]
There is still an excerpt in the help, which wrongly mentions that we can omit `g:` when calling a global function.  I think we need to update it:
```diff
diff --git a/runtime/doc/vim9.txt b/runtime/doc/vim9.txt
index 2baf46c59..6726fb1d2 100644
--- a/runtime/doc/vim9.txt
+++ b/runtime/doc/vim9.txt
@@ -372,13 +372,13 @@ Global variables must be prefixed with "g:", also at the script level. >
 	g:global = 'value'
 	var Funcref = g:ThatFunction
 
-Global functions must be prefixed with "g:" when defining them, but can be
-called without "g:". >
+Global functions must be prefixed with "g:" when defining them, and when
+called. >
 	vim9script
 	def g:GlobalFunc(): string
 	  return 'text'
 	enddef
-	echo GlobalFunc()
+	echo g:GlobalFunc()
 The "g:" prefix is not needed for auto-load functions.
 
 					*vim9-function-defined-later*
```
