### ISSUE TITLE
C-W doesn't delete complete word in some cases

### ISSUE THREAD

**Issue by sigsergv** [vim/vim#964]
VIm ignores option `start` in `:set backspace=indent,eol,start`

How to reproduce:
- start vim and type a few words like "aaaa bbbbb ccccc"
- make sure that command `:set backspace=indent,eol,start` or at least `:set backspace=start` executed;
- exit insert mode
- move cursor in the middle of word "bbbbb", press "a" to enter insert mode
- using arrow keys move cursor to the end of this word, then press C-W

**Expected result:**

Complete word "bbbbb" is deleted.

**Actual result:**

Only tail part of the word deleted, up until the position where you've switched to insert mode.

I've made git bisect and found commit where this behavior started — https://github.com/vim/vim/commit/3d1956bcc9b2f606a8b6b03b3852a6eed9847348

**Comment by brammool** [comment]
The help for 'backspace' says: 
    start   allow backspacing over the start of insert; CTRL-W and CTRL-U
        stop once at the start of insert.
So that's what happens, CTRL-W stops one where insert started.  Moving the cursor doesn't change that, only typing text sets a new insert-start position.

**Comment by sigsergv** [comment]
Oh, looks I've totally missed the point and thought that CTRL-W works the same way as backspace. It was very handy before fix in https://github.com/vim/vim/commit/3d1956bcc9b2f606a8b6b03b3852a6eed9847348

May we have an additional backspace option for this behavior for CTRL-U/CTRL-W?

**Comment by sigsergv** [comment]
Nevermind, solved by .vimrc editing:

```
imap <C-w> <C-o>db
```

**Comment by tomtomjhj** [comment]
This mapping does something similar to @sigsergv's solution without breaking undo sequence.
```vim
inoremap <C-w> <C-\><C-o><ESC><C-w>
```

**Comment by sigsergv** [comment]
Actually, I'm using another sequence now:

~~~
inoremap <C-w> <C-\><C-o>dB
~~~

It's working much better than my original one.
