### ISSUE TITLE
Bug using `autocmd BufWritePost * execute`

### ISSUE THREAD

**Issue by ghost** [vim/vim#9649]
### Steps to reproduce

1.  Add the following snippet into `~/.vimrc`:  

```
autocmd BufWritePost * execute 'silent ! if [ -d .git ] ; then git add % ; git commit -a ; fi'
```

2.  Change to some directory that has the sub-directory `.git`
3.  Open some file that's on the current directory
4.  Edit, save, and also quit from it.

### Expected behaviour

Vim shows me the buffer of the current file instead of a pseudo-terminal. By this I mean: [asciinema.org/a/464935](https://asciinema.org/a/464935)

### Version of Vim

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 15 2020 06:40:31) Included patches: 1-2269 Modified by team+vim@tracker.debian.org Compiled by team+vim@tracker.debian.org Huge version without GUI.  Features included (+) or not (-): +acl               -farsi             -mouse_sysmouse    -tag_any_white +arabic            +file_in_path      +mouse_urxvt       -tcl +autocmd           +find_in_path      +mouse_xterm       +termguicolors +autochdir         +float             +multi_byte        +terminal -autoservername    +folding           +multi_lang        +terminfo -balloon_eval      -footer            -mzscheme          +termresponse +balloon_eval_term +fork()            +netbeans_intg     +textobjects -browse            +gettext           +num64             +textprop ++builtin_terms    -hangul_input      +packages          +timers +byte_offset       +iconv             +path_extra        +title +channel           +insert_expand     -perl              -toolbar +cindent           +job               +persistent_undo   +user_commands -clientserver      +jumplist          +postscript        +vartabs -clipboard         +keymap            +printer           +vertsplit +cmdline_compl     +lambda            +profile           +virtualedit +cmdline_hist      +langmap           -python            +visual +cmdline_info      +libcall           +python3           +visualextra +comments          +linebreak         +quickfix          +viminfo +conceal           +lispindent        +reltime           +vreplace +cryptv            +listcmds          +rightleft         +wildignore +cscope            +localmap          -ruby              +wildmenu +cursorbind        -lua               +scrollbind        +windows +cursorshape       +menu              +signs             +writebackup +dialog_con        +mksession         +smartindent       -X11 +diff              +modify_fname      +sound             -xfontset +digraphs          +mouse             +spell             -xim -dnd               -mouseshape        +startuptime       -xpm -ebcdic            +mouse_dec         +statusline        -xsmp +emacs_tags        +mouse_gpm         -sun_workshop      -xterm_clipboard +eval              -mouse_jsbterm     +syntax            -xterm_save +ex_extra          +mouse_netterm     +tag_binary         +extra_search      +mouse_sgr         -tag_old_static        system vimrc file: "$VIM/vimrc"      user vimrc file: "$HOME/.vimrc"  2nd user vimrc file: "~/.vim/vimrc"       user exrc file: "$HOME/.exrc"        defaults file: "$VIMRUNTIME/defaults.vim"   fall-back for $VIM: "/usr/share/vim" Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-iU6mZD/vim-8.1.2269=. -fstack-protector-strong -Wformat -Werror=format-security -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        Linking: gcc   -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lcanberra -lacl -lattr -lgpm -ldl     -L/usr/lib/python3.8/config-3.8-x86_64-linux-gnu -lpython3.8 -lcrypt -lpthread -ldl -lutil -lm -lm  
```

### Environment

- OS : Windows 11 (WSL2 - Ubuntu)
- Terminal: xterm-256color
- Shell: bash 5.0.16

**Comment by lacygoill** [comment]
You need to prevent the autocmd from being fired in the `/.git/COMMIT_EDITMSG` file.  Otherwise, you end up in a never-ending cycle:

   - you save a regular file: the autocmd runs `$ git commit` which opens `COMMIT_EDITMSG`
   - you write a commit message, and save the file: the autocmd runs `$ git commit` which tries to re-open `COMMIT_EDITMSG`
   - ...

IOW, this shell condition is not strict enough:

    if [ -d .git ]

Try this one:

    if [ -d .git ] && \! [[ %:p:S =~ /.git/ ]]

It should test that a `.git/` directory exists, and that the current file is not under a `/.git/` directory.

Note that – in a `:!` command – you need to escape any `!` character to prevent Vim from expanding it into the previous external command:

>                         Any '!' in {cmd} is replaced with the previous
>                         external command (see also 'cpoptions').  But not when
>                         there is a backslash before the '!', then that
>                         backslash is removed.  Example: ":!ls" followed by
>                         ":!echo ! \! \\!" executes "echo ls ! \!".

That's why this backslash is necessary here:

    if [ -d .git ] && \! [[ %:p:S =~ /.git/ ]]
                      ^

Also, Vim will expand `%:p:S` into the full path to the current file, and take care of escaping any character which might be special to the shell.  From [`:help filename-modifiers`](https://vimhelp.org/cmdline.txt.html#filename-modifiers):

   > :p      Make file name a full path.  Must be the first modifier.

   > :S      Escape special characters for use with a shell command (see
   >         |shellescape()|). Must be the last one.

---


You also probably need a `redraw!` after executing `silent :!`.  From [`:help :!`](https://vimhelp.org/various.txt.html#%3A%21):

> <                       The screen is not redrawn then, thus you have to use
>                         CTRL-L or ":redraw!" if the command did display
>                         something.

---

All in all, you could try this autocmd:

    autocmd BufWritePost * execute 'silent ! if [ -d .git ] && \! [[ %:p:S =~ /.git/ ]]; then git add %:p:S ; git commit -a ; fi' | redraw!

---

For more questions, visit the [google mailing list](https://groups.google.com/g/vim_use), the [irc channel](https://www.vi-improved.org/), or [vi.stackexchange.com](https://vi.stackexchange.com/).

**Comment by lacygoill** [comment]
> Version of Vim
> VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 15 2020 06:40:31) ...

This is almost 4 years old.  If you still have issues, try to reproduce on master.

**Comment by ezvrtgs** [comment]
> This is almost 4 years old. If you still have issues, try to reproduce on master.

@lacygoill Excuse me, ubuntu usually doesn't have the latest version of packages. Installing from the source code, VIM is just now `8.2`. Nevertheless, after updating, the snippet has simply fallen apart. [Here's the evidence](https://asciinema.org/a/465091). 

I edited and saved a file several times but the `autocmd` doesn't work. Moreover, and as seen from evidence, the file's current directory has a `.git` sub-directory. And also I checked out that snippet is on `~/.vimrc`.

If these details don't help, there's my new VIM info:

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 28 2022 10:01:03)
Included patches: 1-4239
Compiled by root@DESKTOP-ERPP0NK
Huge version without GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
-balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term -gettext           +num64             +textobjects
-browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     -perl              +title
+channel           +ipv6              +persistent_undo   -toolbar
+cindent           +job               +popupwin          +user_commands
-clientserver      +jumplist          +postscript        +vartabs
-clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           -python            +viminfo
+cmdline_info      +libcall           -python3           +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
+cscope            +localmap          -ruby              +wildignore
+cursorbind        -lua               +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con        +mksession         +smartindent       +writebackup
+diff              +modify_fname      -sodium            -X11
+digraphs          +mouse             -sound             -xfontset
-dnd               -mouseshape        +spell             -xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        -mouse_gpm         +statusline        -xsmp
+eval              -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary        
-farsi             -mouse_sysmouse    -tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -O2 -fno-strength-reduce -Wall -Wno-deprecated-declarations -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: gcc -L/usr/local/lib -Wl,--as-needed -o vim -lm -ltinfo -ldl 
```

**Comment by lacygoill** [comment]
I don't think it will help, but it would probably be better for the autocmd to be inside a self-clearing augroup:

    augroup MyGitSetup
        autocmd!
        autocmd BufWritePost * execute 'silent ! if [ -d .git ] && \! [[ %:p:S =~ /.git/ ]]; then git add %:p:S ; git commit -a ; fi' | redraw!
    augroup END

---

As for the issue, I can't reproduce.  Maybe because we're using different shells.  I have zsh 5.8.

You could try to enter debug mode to get more information.  Try to execute this Ex command:

    :debug write

Then in debug mode, execute this command:

    >step

Remove the leading `>`.  It just means "debug mode", just like `:` stands for the regular Ex command-line.

After `>step`, I get this:

    BufWritePost Autocommands for "*"
    cmd: execute 'silent ! if [ -d .git ] && \! [[ %:p:S =~ /.git/ ]]; then git add %:p:S ; git commit -a ; fi' | redraw!

After a second `>step`, I get this:

    cmd: ! if [ -d .git ] && \! [[ %:p:S =~ /.git/ ]]; then git add %:p:S ; git commit -a ; fi

Do you get the same results?

---

Also, if I execute this Ex command:

    :! if [ -d .git ] && \! [[ '/run/user/1000/tmp/sample.txt' =~ /.git/ ]]; then echo 'SHOULD COMMIT'; fi

The shell prints this message on the terminal:

    SHOULD COMMIT

Do you get the same result (you will need to adapt the full path to `sample.txt` to your current working directory)?

If not, what do you get if you re-run the same command, but prefix it with `:4verbose`, like this:

    :4verbose :! if [ -d .git ] && \! [[ '/run/user/1000/tmp/sample.txt' =~ /.git/ ]]; then echo 'SHOULD COMMIT'; fi

Try to include the result as well as the exact shell command which Vim actually runs.  It should be printed after the text "Calling shell to execute".  For example:

    Calling shell to execute: " if [ -d .git ] && ! [[ '/run/user/1000/tmp/sample.txt' =~ /.git/ ]]; then echo 'SHOULD COMMIT'; fi"
    SHOULD COMMIT

---

Also, does the shell command work outside Vim?  It does for me:

    $ if [ -d .git ] && ! [[ '/run/user/1000/tmp/sample.txt' =~ /.git/ ]]; then echo 'SHOULD COMMIT'; fi
    SHOULD COMMIT

**Comment by ezvrtgs** [comment]
> I don't think it will help, but it would probably be better for the autocmd to be inside a self-clearing augroup:
>
> ```
> augroup MyGitSetup
>    autocmd!
>    autocmd BufWritePost * execute 'silent ! if [ -d .git ] && \! [[ %:p:S =~ /.git/ ]]; then git add %:p:S ; git commit -a ; fi' | redraw!
> augroup END
> ```

I would have liked it to work, but I fear that I still have the same problem. `Autocmd` doesn't works properly...

---

> As for the issue, I can't reproduce. Maybe because we're using different shells. I have zsh 5.8.
>
> You could try to enter debug mode to get more information. Try to execute this Ex command:
>
> ```
> :debug write
> ```
>
> Then in debug mode, execute this command:
>
> ```
> >step
> ```
> Remove the leading `>`. It just means "debug mode", just like : stands for the regular Ex command-line.
> 
> After `>step`, I get this:
>
> ```
> BufWritePost Autocommands for "*"
> cmd: execute 'silent ! if [ -d .git ] && \! [[ %:p:S =~ /.git/ ]]; then git add %:p:S ; git commit -a ; fi' | redraw!
>
> ```
> After a second `>step`, I get this:
>
> ```
> cmd: ! if [ -d .git ] && \! [[ %:p:S =~ /.git/ ]]; then git add %:p:S ; git commit -a ; fi
> ```
>
> Do you get the same results?

Yep, I got them. Here's the complete result:

```
Entering Debug mode. Type "cont" to continue
cmd: write
>step
"sample.txt" 8 lines, 68 bytes written
BufWritePost Autocommands for "*"
cmd: execute 'silent ! if [ -d .git ] && \! [[ %:p:S =~ /.git/ ]]; then git add %:p:S ; git commit -a ; fi' | redraw!
>step
BufWritePost Autocommands for "*"
cmd: ! if [ -d .git ] && \! [[ %:p:S =~ /.git/ ]]; then git add %:p:S ; git commit -a ; fi
>
```

---

> Also, if I execute this Ex command:
>
> ```
> :! if [ -d .git ] && \! [[ '/run/user/1000/tmp/sample.txt' =~ /.git/ ]]; then echo 'SHOULD COMMIT'; fi
> ```
>
> The shell prints this message on the terminal:
>
> ```
> SHOULD COMMIT
> ```
> 
> Do you get the same result (you will need to adapt the full path to sample.txt to your current working directory)?

Absolutely. I got that message without any problems or conflicts. 

> If not, what do you get if you re-run the same command, but prefix it with :4verbose, like this:
>
> ```
> :4verbose :! if [ -d .git ] && \! [[ '/run/user/1000/tmp/sample.txt' =~ /.git/ ]]; then echo 'SHOULD COMMIT'; f
> ```
> Try to include the result as well as the exact shell command which Vim actually runs. It should be printed after the text "Calling > shell to execute". For example:
> 
> ```
> Calling shell to execute: " if [ -d .git ] && ! [[ '/run/user/1000/tmp/sample.txt' =~ /.git/ ]]; then echo 'SHOULD COMMIT'; fi"
> SHOULD COMMIT
> ```

Even if the above command was successful, I added `:4 verbose` to snippet. So that I got your same result:

```
Calling shell to execute: " if [ -d .git ] && ! [[ '/home/user/.gitrepos/test/sample.txt' =~ /.git/ ]]; then echo 'SHOULD COMMIT'; fi"
SHOULD COMMIT
```

> Also, does the shell command work outside Vim? It does for me:
> 
> ```
> $ if [ -d .git ] && ! [[ '/run/user/1000/tmp/sample.txt' =~ /.git/ ]]; then echo 'SHOULD COMMIT'; fi
> SHOULD COMMIT
> ```

It does for me, too. 

---

**What VIM version do you use currently?** 

This problem emerged after updating VIM from the source code. My reasons for updating weren't only about the version that I had, but also a bug after quitting. In essence, VIM'S color scheme kept on the whole shell. I fixed that bug by pressing `CTRL + L` or just executing the `clear` command.  I am thinking return to `8.1` or even testing the snippet on some hard drive distro.

**Comment by lacygoill** [comment]
> What VIM version do you use currently?

**Version of Vim**

8.2 Included patches: 1-4242

**Environment**

Operating system: Ubuntu 20.04.3 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: zsh 5.8

**Comment by lacygoill** [comment]
> Absolutely. I got that message without any problems or conflicts.

OK, and what happens if you execute the command manually from Vim:

    :! if [ -d .git ] && \! [[ %:p:S =~ /.git/ ]]; then git add %:p:S ; git commit -a ; fi

And how about this one:

    :!git add %:p:S ; git commit -a

Does any of these start Vim to edit a commit message?

**Comment by ezvrtgs** [comment]
>  > What VIM version do you use currently?
>
> **Version of Vim:**
>
> 8.2 Included patches: 1-4242
>
> **Environment:**
>
> Operating system: Ubuntu 20.04.3 LTS
> Terminal: xterm
> Value of $TERM: xterm-256color
> Shell: zsh 5.8


@lacygoill now I'm using VIM 8.2 on a hard drive distro without snippet conflicts, and the way I see it, there's some problem with WSL2. If not, there might be wrong steps on the compiling process I did. Here are those steps:

```
$ sudo apt-get install ncurses-dev
$ git clone https://github.com/vim/vim.git
$ cd vim/src
$ make
$ sudo make install
```
And also my new environment details:

- OS: Slackware 15.0 x86_64
- Terminal: xterm
- Value of $TERM: xterm-256color
- Shell: Bash 5.1.12(1)-release

**Comment by ezvrtgs** [comment]
> >  Absolutely. I got that message without any problems or conflicts.
>
> OK, and what happens if you execute the command manually from Vim:
>
> ```
> :! if [ -d .git ] && \! [[ %:p:S =~ /.git/ ]]; then git add %:p:S ; git commit -a ; fi
> ```
> And how about this one:
>
> ```
> :!git add %:p:S ; git commit -a
> ```
> Does any of these start Vim to edit a commit message?

I didn't have luck with either. Nonetheless, I got this message from the shell:
```
hint: Waiting for your editor to close the file... fatal: cannot run /usr/bin/vim: No such file or directory
error: unable to start editor '/usr/bin/vim'
Please supply the message using either -m or -F option.

shell returned 1

Press ENTER or type command to continue
```

It seems to me the $EDITOR environment variable was the problem all along. The value of it is `/usr/bin/vim` and that it's not on:

``` 
$ whereis vim
vim: /usr/bin/vim.tiny /etc/vim /usr/local/bin/vim /usr/share/vim /usr/share/man/man1/vim.1.gz
```

**Comment by ezvrtgs** [comment]
I export the new path (/usr/bin/vim.tiny) as `EDITOR`, everything should be fine. Isn't it?

```
Error detected while processing BufWritePost Autocommands for "*":
E319: Sorry, the command is not available in this version: execute 'silent ! if [ -d .git ] && \! [[ %:p:S =~ /.git/ ]]; then git add %:p:S ; git commit -a ; fi' | redraw!
```
Oh boy!

**Comment by lacygoill** [comment]
> It seems to me the $EDITOR environment variable was the problem all along. The value of it is /usr/bin/vim and that it's not on:

You don't need to set `EDITOR` with an absolute path.  By default, `make(1)` should install the vim binary at `/usr/local/bin/vim`.  The shell should find it provided that `/usr/local/bin` is in your `PATH`.  You probably just need to set `EDITOR` to `vim`.

FWIW, here is how [I set `EDITOR`](https://github.com/lacygoill/config/blob/8a0ad6d4e918042dbc2a49399820a46685f99d19/.zshenv#L98-L109) and similar variables:

    export VISUAL='vim'
    export EDITOR="$VISUAL"
    export SUDO_EDITOR="$VISUAL"

> I export the new path (/usr/bin/vim.tiny) as EDITOR, everything should be fine. Isn't it?

vim.tiny has limited capabilities compared to a Vim compiled from source (i.e. with `--with-features=huge`).

That's probably why you get this error:

    E319: Sorry, the command is not available in this version: execute 'silent ! if [ -d .git ] && \! [[ %:p:S =~ /.git/ ]]; then git add %:p:S ; git commit -a ; fi' | redraw!

See [`:help install-home`](https://vimhelp.org/usr_90.txt.html#install-home):

    --with-features=huge            Compile with most features enabled.
                                    See |+feature-list| for which feature
                                    is enabled in which case.
