### ISSUE TITLE
Compilation fail on centos 8

### ISSUE THREAD

**Issue by yabb85** [vim/vim#9651]
### Steps to reproduce

Step to reproduce
```
git clone https://github.com/vim/vim.git
cd vim
./configure --with-features=huge --enable-multibyte --enable-rubyinterp --enable-python3interp=yes --with-python3-command=/usr/bin/python3.9 --with-python3-config-dir=/usr/lib64/python3.9/config-3.9-x86_64-linux-gnu --enable-perlinterp --enable-luainterp --enable-cscope --with-tlib=ncurses
```

the result is
```
checking for tgetent()... configure: error: NOT FOUND!
      You need to install a terminal library; for example ncurses.
      On Linux that would be the libncurses-dev package.
      Or specify the name of the library with --with-tlib.
```

I try without --enable-perlinterp
The configure result is 
```
configuration finish with 
configure: updating cache auto/config.cache
configure: creating auto/config.status
config.status: creating auto/config.mk
config.status: creating auto/config.h
```
But compilation result is:
```
objects/testing.o: In function `f_test_gui_tabline_event':
/home/laurent/dev/software/vim/src/testing.c:1357: undefined reference to `send_tabline_event'
objects/testing.o: In function `f_test_gui_tabmenu_event':
/home/laurent/dev/software/vim/src/testing.c:1375: undefined reference to `send_tabline_menu_event'
collect2: error: ld returned 1 exit status
link.sh: Linking failed
make[1]: *** [Makefile:2159: vim] Error 1
```

### Expected behaviour

Compile correctly and produce new vim executable

### Version of Vim

v8.2.4237

### Environment

OS: Centos 8
term: gnome-terminal
$TERM value: xterm-256color
shell: zsh

**Comment by chrisbra** [comment]
> checking for tgetent()... configure: error: NOT FOUND!

You need libncurses-dev or whatever the package is called on Centos 8

```
objects/testing.o: In function `f_test_gui_tabline_event':
/home/laurent/dev/software/vim/src/testing.c:1357: undefined reference to `send_tabline_event'
objects/testing.o: In function `f_test_gui_tabmenu_event':
/home/laurent/dev/software/vim/src/testing.c:1375: undefined reference to `send_tabline_menu_event'
collect2: error: ld returned 1 exit status
link.sh: Linking failed
make[1]: *** [Makefile:2159: vim] Error 1
```

It looks like you need to have `FEAT_GUI_TABLINE` defined. Possibly we need to adjust the ifdefs in testing.c

**Comment by yabb85** [comment]
Normally ncurses package are alreay installed
```
> rpm -qa | grep ncurses
ncurses-libs-6.1-9.20180224.el8.x86_64
ncurses-base-6.1-9.20180224.el8.noarch
ncurses-compat-libs-6.1-9.20180224.el8.x86_64
ncurses-6.1-9.20180224.el8.x86_64
ncurses-devel-6.1-9.20180224.el8.x86_64
ncurses-libs-6.1-9.20180224.el8.i686
ncurses-c++-libs-6.1-9.20180224.el8.x86_64
```
I can see these lib in my /usr/lib64/ directory
```
> ls -l /usr/lib64/libncurses*
lrwxrwxrwx. 1 root root     17 Jun  1  2021 /usr/lib64/libncurses++.so -> libncurses++.so.6
lrwxrwxrwx  1 root root     19 Jun  1  2021 /usr/lib64/libncurses++.so.5 -> libncurses++.so.5.9
-rwxr-xr-x  1 root root  75304 Jun  1  2021 /usr/lib64/libncurses++.so.5.9
lrwxrwxrwx. 1 root root     19 Jun  1  2021 /usr/lib64/libncurses++.so.6 -> libncurses++.so.6.1
-rwxr-xr-x. 1 root root  75304 Jun  1  2021 /usr/lib64/libncurses++.so.6.1
lrwxrwxrwx. 1 root root     18 Jun  1  2021 /usr/lib64/libncurses++w.so -> libncurses++w.so.6
lrwxrwxrwx  1 root root     20 Jun  1  2021 /usr/lib64/libncurses++w.so.5 -> libncurses++w.so.5.9
-rwxr-xr-x  1 root root  75312 Jun  1  2021 /usr/lib64/libncurses++w.so.5.9
lrwxrwxrwx. 1 root root     20 Jun  1  2021 /usr/lib64/libncurses++w.so.6 -> libncurses++w.so.6.1
-rwxr-xr-x. 1 root root  75312 Jun  1  2021 /usr/lib64/libncurses++w.so.6.1
-rw-r--r--. 1 root root     31 Jun  1  2021 /usr/lib64/libncurses.so
lrwxrwxrwx  1 root root     17 Jun  1  2021 /usr/lib64/libncurses.so.5 -> libncurses.so.5.9
-rwxr-xr-x  1 root root 163264 Jun  1  2021 /usr/lib64/libncurses.so.5.9
lrwxrwxrwx. 1 root root     17 Jun  1  2021 /usr/lib64/libncurses.so.6 -> libncurses.so.6.1
-rwxr-xr-x. 1 root root 180224 Jun  1  2021 /usr/lib64/libncurses.so.6.1
-rw-r--r--. 1 root root     32 Jun  1  2021 /usr/lib64/libncursesw.so
lrwxrwxrwx  1 root root     18 Jun  1  2021 /usr/lib64/libncursesw.so.5 -> libncursesw.so.5.9
-rwxr-xr-x  1 root root 217456 Jun  1  2021 /usr/lib64/libncursesw.so.5.9
lrwxrwxrwx. 1 root root     18 Jun  1  2021 /usr/lib64/libncursesw.so.6 -> libncursesw.so.6.1
-rwxr-xr-x. 1 root root 255032 Jun  1  2021 /usr/lib64/libncursesw.so.6.1
```

**Comment by lacygoill** [comment]
On 8.2.4239, this works for me on centos 8 in a docker container:

    $ sudo docker run --interactive=true --tty=true --rm=true centos:8
    $ yum install gcc git make ncurses-devel
    $ cd home/
    $ git clone https://github.com/vim/vim.git
    $ cd vim/
    $ ./configure --with-features=huge --enable-multibyte --enable-rubyinterp --enable-python3interp=yes --with-python3-command=/usr/bin/python3.9 --with-python3-config-dir=/usr/lib64/python3.9/config-3.9-x86_64-linux-gnu --enable-luainterp --enable-cscope --with-tlib=ncurses
    $ make
    $ ./src/vim

I had to remove `--enable-perlinterp ` because it gave this error when compiling with `make(1)`:

    /usr/bin/perl -e 'unless ( $] >= 5.005 ) { for (qw(na defgv errgv)) { print "#define PL_$_ $_\n" }}' > auto/if_perl.c
    /usr/bin/perl  -prototypes -typemap \
        /usr/share/perl5/ExtUtils/typemap if_perl.xs >> auto/if_perl.c
    Unrecognized switch: -rototypes  (-h will show valid options).
    make[1]: *** [Makefile:3092: auto/if_perl.c] Error 29
    make[1]: Leaving directory '/home/vim/src'
    make: *** [Makefile:29: first] Error 2

**Comment by yabb85** [comment]
this error can be fixed by installing package
- perl-ExtUtils-Embed
- perl-ExtUtils-ParseXS

I retry to compile without this option in docker and ... It works
But if I add perl packages, the configure command fail with error:
```
checking for tgetent()... configure: error: NOT FOUND!
      You need to install a terminal library; for example ncurses.
      On Linux that would be the libncurses-dev package.
      Or specify the name of the library with --with-tlib.
```

**Comment by lacygoill** [comment]
I can confirm the issue.  A first google search says that on centos `ncurses-devel` should be installed, but it doesn't help.

Full log at [`./src/auto/config.log`](https://github.com/vim/vim/files/7961760/config.log).

Relevant section:

    configure:12126: checking for tgetent()
    configure:12139: gcc -o conftest -g -O2  -Wl,--enable-new-dtags -Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld   -L/usr/local/lib conftest.c  -lncurses >&5
    /usr/bin/ld: /tmp/ccP59uKl.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
    /usr/bin/ld: final link failed: Nonrepresentable section on output
    collect2: error: ld returned 1 exit status
    configure:12139: $? = 1
    configure: failed program was:
    | /* confdefs.h */
    | #define PACKAGE_NAME ""
    | #define PACKAGE_TARNAME ""
    | #define PACKAGE_VERSION ""
    | #define PACKAGE_STRING ""
    | #define PACKAGE_BUGREPORT ""
    | #define PACKAGE_URL ""
    | #define UNIX 1
    | #define STDC_HEADERS 1
    | #define HAVE_SYS_WAIT_H 1
    | #define HAVE_UNSIGNED_LONG_LONG_INT 1
    | #define HAVE_LONG_LONG_INT 1
    | #define HAVE_SYS_TYPES_H 1
    | #define HAVE_SYS_STAT_H 1
    | #define HAVE_STDLIB_H 1
    | #define HAVE_STRING_H 1
    | #define HAVE_MEMORY_H 1
    | #define HAVE_STRINGS_H 1
    | #define HAVE_INTTYPES_H 1
    | #define HAVE_STDINT_H 1
    | #define HAVE_UNISTD_H 1
    | #define FEAT_HUGE 1
    | #define USE_XSMP_INTERACT 1
    | #define FEAT_DIFF 1
    | #define FEAT_PERL 1
    | #define FEAT_CSCOPE 1
    | #define X_DISPLAY_MISSING 1
    | #define PROC_EXE_LINK "/proc/self/exe"
    | #define HAVE_DATE_TIME 1
    | #define HAVE_ATTRIBUTE_UNUSED 1
    | #define HAVE_DIRENT_H 1
    | #define HAVE_STDINT_H 1
    | #define HAVE_STDLIB_H 1
    | #define HAVE_STRING_H 1
    | #define HAVE_SYS_SELECT_H 1
    | #define HAVE_SYS_UTSNAME_H 1
    | #define HAVE_TERMCAP_H 1
    | #define HAVE_FCNTL_H 1
    | #define HAVE_SGTTY_H 1
    | #define HAVE_SYS_IOCTL_H 1
    | #define HAVE_SYS_TIME_H 1
    | #define HAVE_SYS_TYPES_H 1
    | #define HAVE_TERMIO_H 1
    | #define HAVE_ICONV_H 1
    | #define HAVE_INTTYPES_H 1
    | #define HAVE_LANGINFO_H 1
    | #define HAVE_MATH_H 1
    | #define HAVE_UNISTD_H 1
    | #define HAVE_ERRNO_H 1
    | #define HAVE_SYS_RESOURCE_H 1
    | #define HAVE_LOCALE_H 1
    | #define HAVE_TERMIOS_H 1
    | #define HAVE_SYS_STATFS_H 1
    | #define HAVE_POLL_H 1
    | #define HAVE_SYS_POLL_H 1
    | #define HAVE_PWD_H 1
    | #define HAVE_UTIME_H 1
    | #define HAVE_SYS_PARAM_H 1
    | #define HAVE_LIBINTL_H 1
    | #define HAVE_LIBGEN_H 1
    | #define HAVE_SYS_SYSINFO_H 1
    | #define HAVE_WCHAR_H 1
    | #define HAVE_WCTYPE_H 1
    | #define HAVE_SYS_SYSCTL_H 1
    | #define HAVE_STRINGS_H 1
    | #define TIME_WITH_SYS_TIME 1
    | /* end confdefs.h.  */
    | int tgetent(char *, const char *);
    | int
    | main ()
    | {
    | char s[10000]; int res = tgetent(s, "thisterminaldoesnotexist");
    |   ;
    |   return 0;
    | }
    configure:12143: error: NOT FOUND!
          You need to install a terminal library; for example ncurses.
          On Linux that would be the libncurses-dev package.
          Or specify the name of the library with --with-tlib.

---

Does it help if you set `CFLAGS` to `-fPIC`?

    CFLAGS=-fPIC ./configure --with-features=huge --enable-multibyte --enable-rubyinterp --enable-python3interp=yes --with-python3-command=/usr/bin/python3.9 --with-python3-config-dir=/usr/lib64/python3.9/config-3.9-x86_64-linux-gnu --enable-perlinterp --enable-luainterp --enable-cscope --with-tlib=ncurses

**Comment by lacygoill** [comment]
> Does it help if you set CFLAGS to -fPIC?

The reason why I ask is because in the log, that's what the first error message suggests:

    /usr/bin/ld: /tmp/ccP59uKl.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC

**Comment by lacygoill** [comment]
This pull request seems relevant: https://github.com/vim/vim/pull/4047

But it was closed, and I can't find the change on master.  Maybe it was reverted, I don't know.

FWIW, it seems there was an issue in one of the shell commands that it executed:

    RH_OS=`cat /etc/os-release 2>/dev/null | grep -e 'Fedora\|Red Hat'`

I think we should have made `grep(1)` ignore the case.

    RH_OS=`cat /etc/os-release 2>/dev/null | grep -i -e 'Fedora\|Red Hat'`
                                                  ^^

Because on centos 8, here is the contents of `/etc/os-release`:

    NAME="CentOS Linux"
    VERSION="8"
    ID="centos"
    ID_LIKE="rhel fedora"
    VERSION_ID="8"
    PLATFORM_ID="platform:el8"
    PRETTY_NAME="CentOS Linux 8"
    ANSI_COLOR="0;31"
    CPE_NAME="cpe:/o:centos:centos:8"
    HOME_URL="https://centos.org/"
    BUG_REPORT_URL="https://bugs.centos.org/"
    CENTOS_MANTISBT_PROJECT="CentOS-8"
    CENTOS_MANTISBT_PROJECT_VERSION="8"

Notice that `fedora` is written in lowercase, while the pattern passed to `grep(1)` was using a mixed case.

**Comment by yabb85** [comment]
I set my environment in docker with following command:
```
$ sudo docker run --interactive=true --tty=true --rm=true centos:8
$ yum install install gcc git make ncurses-devel lua-devel python39-devel gpm-devel ruby-devel
$ cd home/
$ git clone https://github.com/vim/vim.git
$ cd vim/
$ CFLAGS=-fPIC ./configure --with-features=huge --enable-multibyte --enable-rubyinterp=dynamic --enable-python3interp=dynamic --with-python3-command=/usr/bin/python3.9 --with-python3-config-dir=/usr/lib64/python3.9/config-3.9-x86_64-linux-gnu --enable-perlinterp=dynamic --enable-luainterp=dynamic --enable-cscope --with-tlib=ncurses --enable-gpm
$ make
$ ./src/vim
```

The issue is fixed for perlinterp but not work if ruby-devel package is installed
```
checking for linking with ncurses library... configure: error: FAILED
```
full log [src/auto/config.log](https://github.com/vim/vim/files/7961910/config.log)

**Comment by lacygoill** [comment]
It's caused by this error:

    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-ld: No such file or directory

But the file does exist.  It's provided by the `redhat-rpm-config-125-1.el8.noarch` package which is installed.  Could it be a problem of file permissions?

**Comment by lacygoill** [comment]
Do you have the `redhat-rpm-config` package installed?

    $ yum install redhat-rpm-config

**Comment by lacygoill** [comment]
Also, what's the output of this shell command on your system?

    $ rpm -q --whatprovides /usr/lib/rpm/redhat/redhat-hardened-ld

**Comment by yabb85** [comment]
Very big thanks!
it works now.

**Comment by mthbrown** [comment]
I did what @yabb85 suggested and remove `ruby-devel` and it worked

**Comment by adrianconstantin-leroy** [comment]
Still have this problem on Rocky Linux 8 (based on Redhat)

Manually adding CFLAGS=-fPIC  to ./configure command fixed it.

**Comment by chrisbra** [comment]
This most likely comes from the PERL CFLAGS include. Check the configure log and output.
