### ISSUE TITLE
JSON syntax highlightes colon after an escaped quote as error

### ISSUE THREAD

**Issue by vibhavsinha** [vim/vim#967]
json does not require colons to be escaped in a json value. However, if there is a colon after an escaped quote, rest of the string is wrongly highlighted.

``` json
{
    "a" : "a:bc",
    "b" : "a\":bc",
    "c" : "a\"b:c"
}
```

![screenshot from 2016-08-05 23-01-12](https://cloud.githubusercontent.com/assets/1254236/17445020/8997e6cc-5b60-11e6-86cf-a655ac2bbf24.png)

**Comment by cecamp** [comment]
Take this up with the json syntax maintainer. Look in the syntax file for his/her contact info.

C Campbell

**Comment by vibhavsinha** [comment]
Thanks @cecamp 
@elzr Please check this at your convenience.
