### ISSUE TITLE
gvim win32: unexpected and unclear `:!{cmd}` behavior

### ISSUE THREAD

**Issue by shawnhatori** [vim/vim#9677]
### Steps to reproduce
Running a shell command opens a new Command Prompt window, runs the command in there, requires manual closing of the window, and then hitting [Enter] within the gVim window.

1. Open `gvim.exe` with _or without_ a `.vimrc`.
2. Run a test Command Prompt command like `:!VER`.

![gvim](https://user-images.githubusercontent.com/5499686/151873893-32e01834-32f4-4a5d-9f9d-4588f9644271.png)

### Expected behaviour

Output of shell command is displayed in gVim window, in the bottom buffer.

1. Open `gvim.exe` with arguments `-u NONE`.
2. Run a test Command Prompt command like `:!VER`.

![image](https://user-images.githubusercontent.com/5499686/151874721-8482e257-f495-4a0f-8846-caa767625b29.png)

I have tested this with my regular `.vimrc`, an empty `.vimrc`, and no `.vimrc` at all. All exhibit the same unexpected behavior. The only way I can seem to get the shell command output in the gVim window is with `-u NONE`. At first I thought it was just my configuration, but as noted, I have tried to isolate any configuration as the cause.

### Version of Vim

8.2

### Environment

Operating System: Windows 11

**Comment by k-takata** [comment]
`:set noshelltemp` changes the behavior.

**Comment by shawnhatori** [comment]
@k-takata Thanks! That's exactly what I was looking for.

`:help shelltemp` answers my confusion as well.
```
'shelltemp' 'stmp'	boolean	(Vi default off, Vim default on)
```

That explains why it was enabled when I added a config, which disables vi compatibility.

Thanks again, closing this.

**Comment by chrisbra** [comment]
you may also use `:set guioptions+=!`
