### ISSUE TITLE
Add an option for a vertical wildmenu

### ISSUE THREAD

**Issue by jclsn** [vim/vim#9679]
_**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
Imo the horizontal wildmenu is hard to read. You always have to move yours eyes over the whole screen, plus there would be more entries possible in a vertical fashion. 

**Describe the solution you'd like**
Since the drop-down menu is already there, it would probably be best to pass the wildmenu to a drop-down menu.

**Additional context**
Neovim already has this feature. It is one of the few things I like better about Neovim.

**Comment by lacygoill** [comment]
Relevant [todo item](https://vimhelp.org/todo.txt.html#todo):

    - Use popup (or popup menu) for command line completion

---

Relevant issue: https://github.com/vim/vim/issues/5432
The latter includes a link to the [CLPUM](https://h-east.github.io/vim/). patch mentioned in the issue.

**Comment by brammool** [comment]
The current wildmenu is very old, from the time that updating more than one line would be slow.  Using a vertical menu would work better.  It's a matter of someone implementing this.  There are some things to take care of, especially the positioning, handling a wrapped command line, etc.

**Comment by coldspark29** [comment]
@lacygoill Nice, so there are already plans. I don't feel like compiling Vim and will wait until this feature is fully functional with the required APIs.Or hasn't anyone continued working on that issue?

@brammool I believe that. It was a great enhancement over vi then, that is for sure. It is amazing how enhanced with has become already and I am looking forward to all the feature to come!

**Comment by bfrg** [comment]
I think this can be closed now. See `:h 'wildoptions'` for details on how to set it up.

**Comment by jclsn** [comment]
@bfrg I just rebuilt and I can see nothing new under wildoptions

**Comment by bfrg** [comment]
@jclsn Try this `:set wildoptions=pum`.

See also the description under `:h 'wildmenu'`.
