### ISSUE TITLE
Vim9: no error for changing type of iteration variable with `extend()`  in `:def` function

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9683]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        def Func()
            var l: list<dict<any>> = [{n: 0}]
            for item: dict<number> in l
                item->extend({s: ''})
            endfor
        enddef
        Func()
    EOF
    )

No error is given.

**Expected behavior**

`E1013` is given:

    E1013: Argument 2: type mismatch, expected dict<number> but got dict<string> in extend()

Because:

   1. the iteration variable `item` was declared with the type `dict<number>`
   2. in the loop's body, we try to extend `item` with `{s: ''}` whose type is `dict<string>`
   3. if it was allowed, the result would be `{n: 0, s: ''}` whose type is `dict<any>`
   4. `dict<any>` is different than the declared `dict<number>`
   5. we are not allowed to change the type of a declared variable

**Version of Vim**

8.2 Included patches: 1-4281

**Environment**

Operating system: Ubuntu 20.04.3 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: zsh 5.8

**Additional context**

At the script level, the exact same code gives `E1013`:
```vim
vim9script
var l: list<dict<any>> = [{n: 0}]
for item: dict<number> in l
    item->extend({s: ''})
endfor
```
    E1013: Argument 2: type mismatch, expected dict<number> but got dict<string> in extend()

**Comment by lacygoill** [comment]
> Expected behavior
>
> E1013 is given:

Actually, one might argue that the type declared in the `:for` statement is only used to check that we're iterating on the right kind of list.  IOW, it might be intended to be used only for the `:for` statement itself, not its body.  Maybe what really counts is the type of the items which is implicitly specified in the list declaration:

    var l: list<dict<any>> = [{n: 0}]
                ^-------^

Here, it's `dict<any>`.  If so, there is indeed no reason to give any error.  However, the current situation is still inconsistent between the script level and compiled code.  We should get the same result, no matter the context.

**Comment by brammool** [comment]
It should give an error, because "item" is declared as "dict<number>", thus adding a string item is wrong.
There is no error for using a list of "dict<any>" for the item of "dict<number>", since "any" can mean "number".
We do need a runtime type check then.
