### ISSUE TITLE
`:help :import-cycle` can be improved

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9684]
From [`:help :import-cycle`](https://vimhelp.org/vim9.txt.html#%3Aimport-cycle):

   > The `import` commands are executed when encountered.  If that script (directly
   > or indirectly) imports the current script, then items defined after the
   > `import` won't be processed yet.  Therefore cyclic imports can exist, but may
   > result in undefined items.

This is confusing:

   - Which script is referred to in "If that script"?  There are at least 2 of them.
   - Which `:import` is referred to in "items defined after the `import`"?  There can be `:import`s in several scripts.

This seems easier to understand because less ambiguous:

   > The `import` commands are executed when encountered.  If a script A imports a
   > script B, and B (directly or indirectly) imports A, then B won't process items
   > defined after the `import` in A yet.  Therefore cyclic imports can exist, but
   > may result in undefined items.

As a suggestion, here is a patch:
```diff
diff --git a/runtime/doc/vim9.txt b/runtime/doc/vim9.txt
index 06f89255c..a8a23164f 100644
--- a/runtime/doc/vim9.txt
+++ b/runtime/doc/vim9.txt
@@ -1526,10 +1526,10 @@ line, there can be no line break: >
 	echo that
 		.name  # Error!
 <							*:import-cycle*
-The `import` commands are executed when encountered.  If that script (directly
-or indirectly) imports the current script, then items defined after the
-`import` won't be processed yet.  Therefore cyclic imports can exist, but may
-result in undefined items.
+The `import` commands are executed when encountered.  If a script A imports a
+script B, and B (directly or indirectly) imports A, then B won't process items
+defined after the `import` in A yet.  Therefore cyclic imports can exist, but
+may result in undefined items.
 
 
 Importing an autoload script ~
```

**Comment by lacygoill** [comment]
Also, we can import a script from itself, and use the imported item from the imported/importing script using the `script.item` notation:
```vim
vim9script
var dir = '/tmp/.vim'
dir->delete('rf')
&runtimepath = dir
dir ..= '/import'
dir->mkdir('p')
var lines =<< trim END
   vim9script
   import 'script.vim'
   export def Func()
       echomsg 'from Func()'
   enddef
   script.Func()
END
lines->writefile(dir .. '/script.vim')
import 'script.vim'
```
    from Func()

Same thing for an autoload script:
```vim
vim9script
var dir = '/tmp/.vim'
dir->delete('rf')
&runtimepath = dir
dir ..= '/autoload'
dir->mkdir('p')
var lines =<< trim END
   vim9script
   import autoload 'script.vim'
   export def Func()
       echomsg 'from Func()'
   enddef
   script.Func()
END
lines->writefile(dir .. '/script.vim')
import autoload 'script.vim'
script.Func()
```
    from Func()
    from Func()

It seems confusing.

Is it a special case of cyclic imports?  Should we disallow it?

**Comment by brammool** [comment]
I'll update the text a bit more.  It should also mention that it's different for autoload imports, since this won't source the script at all.

A script importing itself is weird.  I see no reason to do anything about it though.
