### ISSUE TITLE
Question: How to save the output of interactive buffers (Termdebug and others)?

### ISSUE THREAD

**Issue by GitMensch** [vim/vim#9695]
I've tried `:%!tee new-filename` but got an error about "not writable".

What would be the most reasonable way to "save" interaction sessions (kind of a log) when the process which has an active terminal in there is still running?

**Comment by lacygoill** [comment]
> I've tried :%!tee new-filename but got an error about "not writable".

Because `:!` tries to replace lines in the buffer when preceded by a range, but that's not possible if the buffer is not writable.

Try this instead:

    :silent write !tee new-filename >/dev/null

See [`:help :write_c`](https://vimhelp.org/editing.txt.html#%3Awrite_c).

**Comment by GitMensch** [comment]
Thank you, that works perfect.
