### ISSUE TITLE
Vim9: wrong runtime check when passing list of dictionaries to `deepcopy()`

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9696]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        var ldn: list<dict<number>> = [{a: 0}]->deepcopy()
    EOF
    )

`E1012` is given:

    E1012: Type mismatch; expected list<dict<number>> but got list<dict<any>>

**Expected behavior**

No error is given, because `[{a: 0}]->deepcopy()` evaluates to `[{a: 0}]` whose type is `list<dict<number>>`, which matches the specification given in the variable declaration.

**Version of Vim**

8.2 Included patches: 1-4297

**Environment**

Operating system: Ubuntu 20.04.3 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: zsh 5.8

**Additional context**

Regression introduced in patch 8.2.4286.

---

No issue with a list of lists:
```vim
vim9script
var lln: list<list<number>> = [[0]]->deepcopy()
```
    no error

**Comment by lacygoill** [comment]
> No issue with a list of lists:

The error seems useless, but if we really need to give one, then at least it should be done consistently; i.e. no matter whether the item is a list or a dictionary.

**Comment by lacygoill** [comment]
This looks similar to the issue fixed in patch [8.2.4293](https://github.com/vim/vim/releases/tag/v8.2.4293), but for `deepcopy()` instead of `copy()`.

Note that if this is considered as a bug, then it also applies to declared variables; not just simple values.

At runtime, Vim has full knowledge of all the types, so it seems unexpected to give these kind of errors.  If I assign a list of dictionary of numbers to a variable declared with the type `list<dict<number>>`, then I would expect no error to be given, regardless of how the initializer was obtained; including with `deepcopy()`.

**Comment by brammool** [comment]
The mistake was to use dict<any>, thinking that this means that the dict is allowed to contain anything.
But this is actually used as the dict being declared as such, which isn't correct after deepcopy().
Using no type is what is needed.

**Comment by lacygoill** [comment]
I have 2 other snippets for which I'm not sure there is a bug or not.

Here is the first one:
```vim
vim9script
def Func(lds: list<dict<string>>)
    lds->slice(0, 1)->map(Lambda())
enddef
def Lambda(): func(number, dict<any>): dict<any>
    return (_, _) => ({})
enddef
Func([{key: 'value'}])
```
    E1013: Argument 2: type mismatch, expected func(...): dict<string> but got func(number, dict<any>): dict<any>

If we replace `slice(0, 1)` with `copy()`, no error is given:
```vim
vim9script
def Func(lds: list<dict<string>>)
    lds->copy()->map(Lambda())
enddef
def Lambda(): func(number, dict<any>): dict<any>
    return (_, _) => ({})
enddef
Func([{key: 'value'}])
```
    no error

But `slice()` is somewhat similar to `copy()`, in the sense that it gives us a new list which we can manipulate without altering the original.  So, why give an error with `slice()`?

**Comment by lacygoill** [comment]
The patch 8.2.4304 fixes the issue for a slice obtained with the `slice()` function, but not for a slice obtained with the `[ : ]` syntax:
```vim
vim9script
var lds = [1, 2, 3]
def Func()
    echo lds[ : ]->map((_, _) => 'x')
enddef
Func()
```
    E1013: Argument 2: type mismatch, expected func(...): number but got func(any, any): string

No error at the script level:
```vim
vim9script
var lds = [1, 2, 3]
echo lds[ : ]->map((_, _) => 'x')
```
    ['x', 'x', 'x']

Note that `[ : ]` gives a copy, just like `slice()`.  If we change it, the original list is preserved:
```vim
vim9script
var lds = [1, 2, 3]
echo lds[ : ]->map((_, _) => 'x')
echo lds
```
    ['x', 'x', 'x']
    [1, 2, 3]
