### ISSUE TITLE
request for `buf_execute()` function

### ISSUE THREAD

**Issue by wsdjeg** [vim/vim#9698]
In latest version of vim, we have a function called `win_execute()`, this is usful to run command without switch windows. and it is better to has a function called `buf_execute()`, just same as `win_execute()`. It should be able to run command on specific buffer without switch to that one.

**Comment by brammool** [comment]
When a buffer is not in a window, many commands will fail.  E.g. there is no cursor position.  The only way operations can be performed on a buffer properly is to have it in a window.  Some commands might work without a window, but this is unpredictable.  Internally there are a few tricks to operate on a buffer, but many times a problem was uncovered.  Autocommands also make this difficult, since they can do anything (often unintentionally).

**Comment by wsdjeg** [comment]
@brammool Thank you for your reply. What I need to achieve now is to save the specified buffer without switching to that buffer. `:bufdo` commands switches buffers.

**Comment by lacygoill** [comment]
> What I need to achieve now is to save the specified buffer without switching to that buffer.

If you don't care about being specific, you can execute [`:wall`](https://vimhelp.org/editing.txt.html#%3Awall),  to save all changed buffers.

If you do want to be specific, then indeed we would need a new function; `bufwrite()` or `buf_execute()` for example.

In the meantime, it's a hack, but maybe you could display the buffer in a hidden popup, then call `win_execute()`:
```vim
vim9script
var buf: number = bufadd('/tmp/file')
bufload(buf)
appendbufline(buf, 1, ['some', 'text'])
var id: number = popup_create(buf, {hidden: true})
win_execute(id, 'noautocmd write')
popup_close(id)
```

**Comment by wsdjeg** [comment]
Thanks, `hidden popup` is a nice idea.

**Comment by matveyt** [comment]
Speaking of hacks,

```VimL
call getbufline(bufno, 1, "$")->writefile(bufname(bufno))
call setbufvar(bufno, "&modified", v:false)
```

**Comment by wsdjeg** [comment]
@matveyt thanks, it works well for me, but I think you should use `call setbufvar(bufno, "&modified", 0)`, when use `v:false`, I get `E521: Number required: &modified = 'false'`

**Comment by lacygoill** [comment]
> Maybe this is a bug, we should be able to use v:false to set &modified.

Related issues:

   - #7603
   - #7615 

They were fixed about a year ago in patches [8.2.2284](https://github.com/vim/vim/releases/tag/v8.2.2284), [8.2.2285](https://github.com/vim/vim/releases/tag/v8.2.2285) and [8.2.2297](https://github.com/vim/vim/releases/tag/v8.2.2297).

**Comment by zeertzjq** [comment]
How do you define "without switching to that buffer"?

**Comment by chrisbra** [comment]
> Speaking of hacks,

I wouldn't call this a hack

**Comment by chrisbra** [comment]
let's close this.
