### ISSUE TITLE
Can not get v:char when Enter key is pressed in insert mode

### ISSUE THREAD

**Issue by jdhao** [vim/vim#9699]
### Steps to reproduce

1. Use the following `test.vim` as conf and open vim `vim -u test.vim`
```
augroup demo
  autocmd!
  autocmd InsertCharPre * call s:my_demo()
augroup END

function! s:my_demo() abort
  echomsg "v:char is" char2nr(v:char)
endfunction
```

2. Enter insert mode, input `abc` and then press Enter and input `abc` again.

### Expected behaviour

I can see the ASCII code for all the press keys. Instead, I can only see the following message:

```
v:char is 97
v:char is 98
v:char is 99
v:char is 97
v:char is 98
v:char is 99
```

ASCII code of enter is not shown here.

### Version of Vim

8.2

### Environment

OS: macOS
terminal: kitty

**Comment by brammool** [comment]
> ASCII code of enter is not shown here.

Right, only characters that are inserted trigger the InsertCharPre
autocommand.  Also triggering it for Return would break existing
plugins.

What would you want to use it for?  You can't really change the
character, like what is possible with InsertCharPre.

-- 
All good vision statements are created by groups of people with bloated
bladders who would rather be doing anything else.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by jdhao** [comment]
I am writing some code where I want to do something only where the user has pressed Enter key in insert mode. So I want to know whether the pressed key is Enter key or not.

**Comment by brammool** [comment]
> I am writing some code where I want to do something only where the
> user has pressed Enter key in insert mode. So I want to know whether
> the pressed key is Enter key or not.

You could use an expression mapping, with the expression returning the
Enter key:
	inoremap <expr> <CR> YourFunction()

-- 
A)bort, R)etry, D)o it right this time

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
