### ISSUE TITLE
Vim9: unexpected type mismatch error when changing undeclared list with `map()` in `:def` function

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9701]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        def Func()
            echo getline(1, 3)->map((_, v) => 3)
        enddef
        Func()
    EOF
    )

An error is given:

    E1013: Argument 2: type mismatch, expected func(...): string but got func(any, any): number

**Expected behavior**

No error is given, because `getline(1, 3)` is not a declared variable, and it is allowed for `map()` to change the type of the items in a list, provided that it's not assigned to a variable with a declared type.

**Version of Vim**

8.2 Included patches: 1-4301

**Environment**

Operating system: Ubuntu 20.04.3 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: zsh 5.8

**Additional context**

At the script level, the exact same code does not give any error:
```vim
vim9script
echo getline(1, 3)->map((_, v) => 3)
```
    [3]

---

In compiled code, Vim has no problem with us doing the opposite; i.e. use `map()` to turn a list of numbers into a list of strings:
```vim
vim9script
def Func()
    echo range(3)->map((_, v) => 'x')
enddef
Func()
```
    ['x', 'x', 'x']

If `map()` can do this on an undeclared variable:

    number → string

Then it should be allowed to do this too:

    string → number

**Comment by lacygoill** [comment]
Also, this error is useless:
```vim
vim9script
def Func()
    echo [{a: 0}]->map((_, v) => 'x')
enddef
Func()
```
    E1013: Argument 2: type mismatch, expected func(...): dict<any> but got func(any, any): string

Because `[{a: 0}]` is not a declared variable.  If the error was useful, Vim would give it at the script level too, but it does not:
```vim
vim9script
echo [{a: 0}]->map((_, v) => 'x')
```
    ['x']

**Comment by lacygoill** [comment]
> Also, this error is useless:

Although, I don't know how hard it would be to suppress it, because it's given at compile time, when Vim has less information than at runtime.

**Comment by brammool** [comment]
These are corner cases.  At least changing the list that getline() returns does not cause problems.
So is it useful to give an error?  Or are we just making it harder to do what you want to do?

I would think the error is more annoying than useful.  Especially the example with range()->map() seems common.

**Comment by brammool** [comment]
Taken care of by patch 8.2.4302
