### ISSUE TITLE
Error on opening .tex files

### ISSUE THREAD

**Issue by svitalsky** [vim/vim#9704]
### Steps to reproduce

1. Create a file file.tex containing three lines, first a TeX comment, second empty, third with some text (see the attached file file.tex).
2. Open it with command `vim --clean ./file.tex`
3. An error message appears:
`Error detected while processing BufRead Autocommands for "*.tex"..function dist#ft#FTtex:`
`line   20:`
`E1023: Using a Number as a Bool: 3`
4. After pressing Enter or Esc the file is open.

The last working version is 8.2.4295.

[file.tex.gz](https://github.com/vim/vim/files/8008659/file.tex.gz)

### Expected behaviour

The file is open for editing &c.

### Version of Vim

8.2.4296–8.2.4301

### Environment

Linux, various versions of Ubuntu. Both terminal version run from Bash and GUI version (gVim).

**Comment by lacygoill** [comment]
```diff
diff --git a/runtime/autoload/dist/ft.vim b/runtime/autoload/dist/ft.vim
index d4e7be44b..8e8259fc1 100644
--- a/runtime/autoload/dist/ft.vim
+++ b/runtime/autoload/dist/ft.vim
@@ -755,7 +755,7 @@ export def FTtex()
     var save_cursor = getpos('.')
     call cursor(1, 1)
     var firstNC = search('^\s*[^[:space:]%]', 'c', 1000)
-    if firstNC # Check the next thousand lines for a LaTeX or ConTeXt keyword.
+    if firstNC > 0 # Check the next thousand lines for a LaTeX or ConTeXt keyword.
       var lpat = 'documentclass\>\|usepackage\>\|begin{\|newcommand\>\|renewcommand\>'
       var cpat = 'start\a\+\|setup\a\+\|usemodule\|enablemode\|enableregime\|setvariables\|useencoding\|usesymbols\|stelle\a\+\|verwende\a\+\|stel\a\+\|gebruik\a\+\|usa\a\+\|imposta\a\+\|regle\a\+\|utilisemodule\>'
       var kwline = search('^\s*\\\%(' .. lpat .. '\)\|^\s*\\\(' .. cpat .. '\)',
```

**Comment by lacygoill** [comment]
There is a second similar error:
```diff
diff --git a/runtime/autoload/dist/ft.vim b/runtime/autoload/dist/ft.vim
index d4e7be44b..7d49cf1ef 100644
--- a/runtime/autoload/dist/ft.vim
+++ b/runtime/autoload/dist/ft.vim
@@ -722,7 +722,7 @@ export def FTperl(): number
   endif
   var save_cursor = getpos('.')
   call cursor(1, 1)
-  var has_use = search('^use\s\s*\k', 'c', 30)
+  var has_use = search('^use\s\s*\k', 'c', 30) > 0 ? true : false
   call setpos('.', save_cursor)
   if has_use
     setf perl
```

**Comment by lacygoill** [comment]
I guess we can remove the `? true : false` part:
```diff
diff --git a/runtime/autoload/dist/ft.vim b/runtime/autoload/dist/ft.vim
index d4e7be44b..7d49cf1ef 100644
--- a/runtime/autoload/dist/ft.vim
+++ b/runtime/autoload/dist/ft.vim
@@ -722,7 +722,7 @@ export def FTperl(): number
   endif
   var save_cursor = getpos('.')
   call cursor(1, 1)
-  var has_use = search('^use\s\s*\k', 'c', 30)
+  var has_use = search('^use\s\s*\k', 'c', 30) > 0
   call setpos('.', save_cursor)
   if has_use
     setf perl
```
I seem to remember a case where it was necessary, but probably not here.

**Comment by brammool** [comment]
Thanks for the suggested fixes.
For the FTperl() change, is there a way to test this?
We should actually have a test for each of these.

**Comment by lacygoill** [comment]
> For the FTperl() change, is there a way to test this?

On 8.2.4304, the issue can be reproduced with this shell command:

    $ vim --clean --cmd 'call setline("", "use a")' /tmp/pl.t

    Error detected while processing BufRead Autocommands for "*.t"..function dist#ft#FTperl:
    line   14:
    E1023: Using a Number as a Bool: 2

**Comment by lacygoill** [comment]
Sorry, I think the code was wrong (even though it worked).  This one should be correct:

    $  vim --clean --cmd 'call setline(1, ["", "use a"])' /tmp/pl.t

**Comment by lacygoill** [comment]
Still not correct actually.  Here is yet another try:

    $ vim --clean --cmd 'filetype on | call setline(1, ["", "use a"])' /tmp/pl.t

**Comment by svitalsky** [comment]
Thank you.

**Comment by lacygoill** [comment]
Using `search()` in an `:if` test is a common idiom in Vimscript.  And forgetting to turn it into a boolean is a common mistake.  Maybe we should add a check at compile time to spot all this mistake earlier via `:defcompile`.

It doesn't matter that – in some special cases – `search()` can output 0 or 1 which are boolean numbers.  In the general case, we have no guarantee that `search()` will give such numbers.

**Comment by brammool** [comment]
> Using `search()` in an `:if` test is a common idiom in Vimscript.  And
> forgetting to turn it into a boolean is a common mistake.  Maybe we
> should add a check at compile time to spot all this mistake earlier
> via `:defcompile`.
> 
> It doesn't matter that – in some special cases – `search()` can output
> 0 or 1 which are boolean numbers.  In the general case, we have no
> guarantee that `search()` will give such numbers.

We do make a difference between the "number" type and a "number" type
that could be just 0 or 1.  However, there are several corner cases
where giving an error during compilation can be annoying.  Especially
for functions that return the number 0 or 1.

For example, append() returns 1 for failure, 0 for success.  Using that
directly in a condition would work at compile time, because we know this:

	if append(...)
	  # failed

But if we store the result in a variable and then use it, we would get
an error:

	var result: number = append(...)
	if result  # Error

Well, you can use the right type:

	var result: bool = append(...)
	if result
	  # failed

I could make the change and see who complains?

Another corner case: executable() normally returns 0 or 1, but can also
return -1.

Also 'completefunc' first argument is a number, but it can only be 0 or
1.

I think it's better not to change this.  There will still be an error at
runtime.

-- 
hundred-and-one symptoms of being an internet addict:
10. And even your night dreams are in HTML.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> I think it's better not to change this.  There will still be an error at
> runtime.

Right.  The intent was to reduce bug reports.  If this change causes more issues to be opened, then it's not worth it.
