### ISSUE TITLE
Vim9: unexpected error when using `map()` to change items in list whose type is inferred

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9705]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        var ls = ['a']
        echo ls->map((_, v) => v->len())
    EOF
    )

An error is given:

    E1012: Type mismatch; expected string but got number in map()

**Expected behavior**

No error is given, because when the type of a variable is inferred, the type of the items is allowed to change.  From [`:help type-inference`](https://vimhelp.org/vim9.txt.html#type-inference):

   > If the type is inferred then the type is allowed to change: >
   >         [1, 2, 3]->extend(['x'])  # result: [1, 2, 3, 'x']

**Version of Vim**

8.2 Included patches: 1-4302

**Environment**

Operating system: Ubuntu 20.04.3 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: zsh 5.8

**Additional context**

Here is another useless error:
```vim
vim9script
var ls1 = ['a']
var ls2 = ['bb']
def Func()
    echo (ls1 + ls2)->map((_, v) => v->len())
enddef
Func()
```
    E1013: Argument 2: type mismatch, expected func(...): string but got func(any, any): number

It's useless because we didn't pass a declared variable with an explicit type to `map()`.  Instead, we passed it `ls1 + ls2` which is an unassigned expression.  If the error was useful, Vim would give it at the script level too.  It does not:
```vim
vim9script
var ls1 = ['a']
var ls2 = ['bb']
echo (ls1 + ls2)->map((_, v) => v->len())
```
    [1, 2]

**Comment by lacygoill** [comment]
Also, "string" looks weird here:

   > When a type has been declared this is attached to a list or string.

Shouldn't it be "dictionary" instead?
```diff
diff --git a/runtime/doc/vim9.txt b/runtime/doc/vim9.txt
index afa3239f0..fba7b4e4d 100644
--- a/runtime/doc/vim9.txt
+++ b/runtime/doc/vim9.txt
@@ -1398,7 +1398,7 @@ Results in:
 For script-local variables in Vim9 script the type is checked, also when the
 variable was declared in a legacy function.
 
-When a type has been declared this is attached to a list or string.  When
+When a type has been declared this is attached to a list or dictionary.  When
 later some expression attempts to change the type an error will be given: >
 	var ll: list<number> = [1, 2, 3]
 	ll->extend(['x'])  # Error, 'x' is not a number
```

**Comment by brammool** [comment]
The quote from the help is for an inline constant.  Such a list is not declared.  However, if a variable is declared then the type is inferred from the value, and that is a declaration thus the type cannot change.  I'll add an example in the help:

```
When a type has been declared this is attached to a List or Dictionary.  When
later some expression attempts to change the type an error will be given: >
	var ll: list<number> = [1, 2, 3]
	ll->extend(['x'])  # Error, 'x' is not a number

If the type is not declared then it is allowed to change: >
	[1, 2, 3]->extend(['x'])  # result: [1, 2, 3, 'x']

For a variable declaration an infered type matters: >
	var ll = [1, 2, 3]
	ll->extend(['x'])  # Error, 'x' is not a number
That is because the declaration looks like a list of numbers, thus is
equivalent to: >
	var ll: list<number> = [1, 2, 3]
If you do want a more permissive list you need to declare the type: >
	var ll: list<any = [1, 2, 3]
	ll->extend(['x'])  # OK
```

**Comment by lacygoill** [comment]
I think there is a typo on line 9:

    For a variable declaration an infered type matters: >
                                  ^-----^
                                  inferred

---

> However, if a variable is declared then the type is inferred from the value, and that is a declaration thus the type cannot change.

OK, but it seems inconsistent with how an inferred type is used for a returned value:
```vim
vim9script
var ll = [1, 2, 3]
ll->extend(['x'])
```
    E1013: Argument 2: type mismatch, expected list<number> but got list<string> in extend()
```vim
vim9script
def GetList(): list<number>
    var ll = [1, 2, 3]
    return ll
enddef
echo GetList()->extend(['x'])
```
    [1, 2, 3, 'x']

Why give an error in the first snippet, but not in the second one?

**Comment by lacygoill** [comment]
We can extend a list of numbers created at the script level or in a `:def` function.  And we can declare its type explicitly, or let type inferrence guess it.  That gives 2 x 2 = 4 possibilities:
```vim
vim9script
var l = [1, 2, 3]
echo l->extend(['x'])
```
    E1013: Argument 2: type mismatch, expected list<number> but got list<string> in extend()
```vim
vim9script
var l: list<number> = [1, 2, 3]
echo l->extend(['x'])
```
    E1013: Argument 2: type mismatch, expected list<number> but got list<string> in extend()
```vim
vim9script
def ListNumber(): list<number>
    var l: list<number> = [1, 2, 3]
    return l
enddef
echo ListNumber()->extend(['x'])
```
    E1013: Argument 2: type mismatch, expected list<number> but got list<string> in extend()
```vim
vim9script
def ListNumber(): list<number>
    var l = [1, 2, 3]
    return l
enddef
echo ListNumber()->extend(['x'])
```
    [1, 2, 3, 'x']

All of them give an error, except the last one.  I still think the last one should give an error just like all the other ones.  I don't see why we should make an exception here.  It makes the rules harder to understand.
