### ISSUE TITLE
Vim9: crash when emulating python iterator

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9706]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        var l = ['a', 'b', 'c']
        def Iter(c: any): any
            var idx = -1
            var iterator = {
                container: c,
                idx: idx,
            }
            def g:__NextItem__(self: dict<any>): any
                ++idx
                return self.container[idx]
            enddef
            iterator.__next__ = function('g:__NextItem__', [iterator])
            return iterator
        enddef
        var it = Iter(l)
        echo it.__next__()
        echo it.__next__()
        echo it.__next__()
    EOF
    )

Vim crashes.

**Expected behavior**

Vim doesn't crash.  The strings `'a'`, `'b'` and `'c'` are echo'ed.

**Version of Vim**

8.2 Included patches: 1-4306

**Environment**

Operating system: Ubuntu 20.04.3 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: zsh 5.8

**Additional context**

- [ubsan log](https://github.com/vim/vim/files/8009817/asan.log)
- [backtrace](https://github.com/vim/vim/files/8009818/gdb.txt)
- [valgrind log](https://github.com/vim/vim/files/8009819/valgrind.log)

There is a runtime error in `src/vim9execute.c` on line 3184:

https://github.com/vim/vim/blob/500761b1cf666f030009d2dcdacfdce28f68f43d/src/vim9execute.c#L3184

    member access within null pointer of type 'struct garray_T'

---

In legacy Vim script, the code works as expected:
```vim
let l = ['a', 'b', 'c']
function s:iter(c)
    let idx = -1
    let iterator = #{
        \ container: a:c,
        \ idx: idx,
        \ }
    function iterator.__next__() closure dict
        let idx += 1
        return self.container[idx]
    endfunction
    return iterator
endfunction
let it = s:iter(l)
echo it.__next__()
echo it.__next__()
echo it.__next__()
```
    a
    b
    c

---

In the call to `function()`, if we remove the quotes around the function name `g:__NextItem__`, Vim no longer crashes.  Instead, it gives an unexpected error at runtime:
```vim
vim9script
var l = ['a', 'b', 'c']
def Iter(c: any): any
    var idx = -1
    var iterator = {
        container: c,
        idx: idx,
    }
    def g:__NextItem__(self: dict<any>): any
        ++idx
        return self.container[idx]
    enddef
    iterator.__next__ = function(g:__NextItem__, [iterator])
    return iterator
enddef
var it = Iter(l)
echo it.__next__()
echo it.__next__()
echo it.__next__()
```
    E121: Undefined variable: g:__NextItem__

Simplified MWE:
```vim
vim9script
def Outer()
    def g:Inner()
        echomsg 'from g:Inner()'
    enddef
    g:Inner()
enddef
Outer()
```
    from g:Inner()
```vim
vim9script
def Outer()
    def g:Inner()
        echomsg 'from g:Inner()'
    enddef
    call(g:Inner, [])
enddef
Outer()
```
    E121: Undefined variable: g:Inner

Why can Vim find `g:Inner` when we call it directly, but not via `call()`?

**Comment by lacygoill** [comment]
Also, we can nest a legacy function inside a Vim9 one:
```vim
vim9script
def Func()
    function g:ObjMethod()
    endfunction
enddef
defcompile
```
    no error

But not if it's a dictionary one:
```vim
vim9script
g:Obj = {}
def Func()
    function g:Obj.Method()
    endfunction
enddef
defcompile
```
    E476: Invalid command: function g:Obj.Method()

Is it working as intended?

[`:help vim9-no-dict-function`](https://vimhelp.org/vim9.txt.html#vim9-no-dict-function) says that we cannot define a Vim9 dict function.  But here, we're trying to define a *legacy* dict function inside a Vim9 one.

**Comment by brammool** [comment]
The code isn't quite right, when calling a global function there is no execution context, thus "idx" does not exist.
The NextItem function can use self.idx instead.
But there should be no crash, I'll fix that.

**Comment by lacygoill** [comment]
> The code isn't quite right, when calling a global function there is no execution context, thus "idx" does not exist.

Ah right.  No need of a global function; this works:
```vim
vim9script
var l = ['a', 'b', 'c']
var idx = -1
def Iter(c: any): any
    var iterator = {
        container: c,
        idx: idx,
    }
    def __NextItem__(self: dict<any>): any
        ++idx
        return self.container[idx]
    enddef
    iterator.__next__ = function(__NextItem__, [iterator])
    return iterator
enddef
var it = Iter(l)
echo it.__next__()
echo it.__next__()
echo it.__next__()
```
    a
    b
    c

However, it stops working if we quote `__NextItem__`:
```vim
vim9script
var l = ['a', 'b', 'c']
var idx = -1
def Iter(c: any): any
    var iterator = {
        container: c,
        idx: idx,
    }
    def __NextItem__(self: dict<any>): any
        ++idx
        return self.container[idx]
    enddef
    iterator.__next__ = function('__NextItem__', [iterator])
    return iterator
enddef
var it = Iter(l)
echo it.__next__()
echo it.__next__()
echo it.__next__()
```
    E700: Unknown function: __NextItem__

I guess that's because internally the function is implemented as a lambda, and the quotes prevent `__NextItem__` from being evaluated into `function('<lambda>123')`.

**Comment by lacygoill** [comment]
> Ah right. No need of a global function; this works:

Actually, the code is not correct, because for `Iter()` to be a proper [generator function](https://docs.python.org/3/glossary.html#term-generator), I think `idx` must be set from `Iter()`:
```vim
vim9script
var l = ['a', 'b', 'c']
def Iter(c: any): any
    var idx: number = -1
    var iterator = {
        container: c,
        idx: idx,
    }
    def __NextItem__(self: dict<any>): any
        ++idx
        return self.container[idx]
    enddef
    iterator.__next__ = function(__NextItem__, [iterator])
    return iterator
enddef
var it = Iter(l)
echo it.__next__()
echo it.__next__()
echo it.__next__()
```
    E1248: Closure called from invalid context

The help about this error suggests that the issue could come from evaluating a Vim9 closure from legacy context:

   > In some situations, especially when calling a Vim9 closure from legacy
   > context, the evaluation will fail.  *E1248*

But there is no legacy context here.  Everything is in Vim9.
