### ISSUE TITLE
.tbz files don't work well

### ISSUE THREAD

**Issue by avnersh** [vim/vim#9711]
### Steps to reproduce

1. tar jvcf something.tbz <list of files>
2. gvim something.tbz

instead of the expected list of files, I get:
gzip: /home/avner/list.tbz: not in gzip format
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors

### Expected behaviour

just like opening something.tar.bz2 - a list of the files should appear (as was before my last upgrade)

### Version of Vim

8.2.3402, 8.2.3403, 8.2.3409, 8.2.3428

### Environment

OS: Debian GNU/Linux 11 (bullseye)

### Logs and stack traces

```shell
my proposed fix:
in line 168, instead of:
    let filekind= system("file ".shellescape(tarfile,1)) =~ "bzip2"
write:
    let filekind= system("file ".shellescape(tarfile,1))


this will ensure filekind is "bzip2" and not "1" as assigned now(?).
```

**Comment by chrisbra** [comment]
it looks like this is fixed with v33 of tar.vim: http://www.drchip.org/astronaut/vim/index.html#TAR

**Comment by chrisbra** [comment]
closing, I guess will be updated with a new runtime file update
