### ISSUE TITLE
Vim install broken on macos 12.2

### ISSUE THREAD

**Issue by vinitkumar** [vim/vim#9717]
### Steps to reproduce

Tried upgrading my vim. I run the head version of the vim installed via homebrew and got this error instead.

### Expected behaviour

The upgrade shouldn't crash

### Version of Vim

HEAD-f681cfb_1 

### Environment

macos 12.2

### Logs and stack traces

```shell
==> Upgrading vim
  HEAD-135e152 -> HEAD-f681cfb_1 

==> ./configure --prefix=/usr/local --mandir=/usr/local/Cellar/vim/HEAD-f681cfb_1/share/man --enable-multibyte --with-tlib=ncurses --with-compiledby=Homebrew --enable-cscope --enable-terminal --enable-perlinterp --enable-ruby
==> make
Last 15 lines from /Users/vinitkumar/Library/Logs/Homebrew/vim/02.make:
2783 translated messages.
OLD_PO_FILE_INPUT=yes msgfmt -v -o ja.sjis.mo ja.sjis.po
2783 translated messages.
OLD_PO_FILE_INPUT=yes msgfmt -v -o pl.UTF-8.mo pl.UTF-8.po
1858 translated messages.
OLD_PO_FILE_INPUT=yes msgfmt -v -o pl.cp1250.mo pl.cp1250.po
1858 translated messages.
rm -f ru.cp1251.po
iconv -f utf-8 -t cp1251 ru.po | \
		sed -e 's/charset=[uU][tT][fF]-8/charset=cp1251/' -e 's/# Original translations/# Generated from ru.po, DO NOT EDIT/' > ru.cp1251.po
sed: RE error: illegal byte sequence
make[2]: *** [ru.cp1251.po] Error 1
make[1]: *** [languages] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [first] Error 2
```

**Comment by lacygoill** [comment]
[Google](https://stackoverflow.com/a/23584470) says that setting `LC_ALL` to `C` in the `sed(1)` process could fix the issue.  If there is an issue in `src/po/Makefile`, I don't know how to set the variable over there.

**Comment by lacygoill** [comment]
Does this patch help?
```diff
diff --git a/src/po/Makefile b/src/po/Makefile
index e46bceaf3..0a79e726e 100644
--- a/src/po/Makefile
+++ b/src/po/Makefile
@@ -152,7 +152,7 @@ ko.po: ko.UTF-8.po
 ru.cp1251.po: ru.po
 	rm -f ru.cp1251.po
 	iconv -f utf-8 -t cp1251 ru.po | \
-		sed -e 's/charset=[uU][tT][fF]-8/charset=cp1251/' -e 's/# Original translations/# Generated from ru.po, DO NOT EDIT/' > ru.cp1251.po
+		LC_ALL=C sed -e 's/charset=[uU][tT][fF]-8/charset=cp1251/' -e 's/# Original translations/# Generated from ru.po, DO NOT EDIT/' > ru.cp1251.po
 
 # Convert uk.po to create uk.cp1251.po.
 uk.cp1251.po: uk.po
```

**Comment by vinitkumar** [comment]
@lacygoill Thanks for taking the time.

Question, I can't use this patch, unless I add these changes on my fork and apply this patch and rebuild this version, instead of the homebrew one, right?

**Comment by lacygoill** [comment]
> Question, I can't use this patch, unless I add these changes on my fork and apply this patch and rebuild this version, instead of the homebrew one, right?

Yes, I don't know homebrew, but I guess you would need to apply the patch on a local copy.

I don't think it's the right fix, but it could temporarily help.

**Comment by chrisbra** [comment]
It might work to temporarily export LC_ALL=C before running `make` or `make install`

**Comment by vinitkumar** [comment]
Closing it as the latest head builds just fine, so whatever was wrong has been fixed in the recent commits.
