### ISSUE TITLE
Mark "double quote" does not saved in file ".viminfo" since patch 7.4.320.

### ISSUE THREAD

**Issue by guraga** [vim/vim#974]
Prepare:

``` bash
git clone https://github.com/vim/vim
cd vim

# Compile two versions of vim

git checkout v7.4.319
make
cp ./src/vim ../vim-7.4.319

git checkout v7.4.320
make
cp ./src/vim ../vim-7.4.320

cd ..

# Create test file
seq 3 > test_file.txt

```

Content of "~/.vimrc":

``` vim
set nocompatible

autocmd BufReadPost *
   \ if
   \    line( "'\"" ) > 1
   \    &&
   \    line( "'\"" ) <= line( '$' )
   \ |
   \    execute 'normal! g`"'
   \ |
   \ endif
```

Directories "~/.vim", "/usr/local/share/vim", "/usr/share/vim" does not exists.

Begin of test.

``` bash

# Remove file "~/.viminfo"
rm -f ~/.viminfo

# Run vim
./vim-7.4.319

```

Type ":tabnew test_file.txt" and press Enter.
Cursor will be in line 1.
Press "j" (or "Down arrow"), "ZQ", "ZQ".
Vim will store mark "double quote" in file "~/.viminfo" and exit.

Run vim:

``` bash
./vim-7.4.319
```

Vim will read file "~/.viminfo".

Type ":tabnew test_file.txt" and press Enter.

End of test.

If you run executable "./vim-7.4.319",
after execute given steps
cursor will be at line 2 (as expected).

If you run executable "./vim-7.4.320",
after execute given steps
cursor will be at line 1 (bug).

Bug: since vim patch 7.4.320,
when using given steps (":tabnew" and "ZQ"),
mark "double quote"
not saved in file "~/.viminfo".

**Comment by vim-ml** [comment]
On Wed, Aug 10, 2016 at 4:08 AM, guraga vim-dev-github@256bit.org wrote:

> Prepare:
> 
> git clone https://github.com/vim/vim
> cd vim
> 
> # Compile two versions of vim
> 
> git checkout v7.4.319
> make
> cp ./src/vim ../vim-7.4.319
> 
> git checkout v7.4.320
> make
> cp ./src/vim ../vim-7.4.320
> 
> cd ..
> 
> # Create test file
> 
> seq 3 > test_file.txt
> 
> Content of "~/.vimrc":
> 
> set nocompatible
> 
> autocmd BufReadPost *
>    \ if
>    \    line( "'\"" ) > 1
>    \    &&
>    \    line( "'\"" ) <= line( '$' )
>    \ |
>    \    execute 'normal! g`"'
>    \ |
>    \ endif
> 
> Directories "~/.vim", "/usr/local/share/vim", "/usr/share/vim" does not exists.
> 
> Begin of test.
> 
> # Remove file "~/.viminfo"
> 
> rm -f ~/.viminfo
> 
> # Run vim
> 
> ../vim-7.4.319
> 
> Type ":tabnew test_file.txt" and press Enter.
> Cursor will be in line 1.
> Press "j" (or "Down arrow"), "ZQ", "ZQ".
> Vim will store mark "double quote" in file "~/.viminfo" and exit.
> 
> Run vim:
> 
> ./vim-7.4.319
> 
> Vim will read file "~/.viminfo".
> 
> Type ":tabnew test_file.txt" and press Enter.
> 
> End of test.
> 
> If you run executable "./vim-7.4.319",
> after execute given steps
> cursor will be at line 2 (as expected).
> 
> If you run executable "./vim-7.4.320",
> after execute given steps
> cursor will be at line 1 (bug).
> 
> Bug: since vim patch 7.4.320,
> when using given steps (":tabnew" and "ZQ"),
> mark "double quote"
> not saved in file "~/.viminfo".

The ZQ command means "quit and don't save", just as ":q!". If I don't
save the changes, I wouldn't be worried if the cursor position was
lost too: maybe the earlier behaviour (saving the cursor position even
when forgetting the changes) was the bug.

I usually quit Vim by :wa|wv followed by :qa and in that case (and
with the autocommand in the vimrc_example.vim) the cursor position is
restored on restart, or whenever I reopen a file which is not too old
for its history to be "remembered".

Best regards,
Tony.

**Comment by guraga** [comment]
Mark "double quote" does not saved in file "~/.viminfo", even if execute ":tabnew test_file.txt", than edit buffer and:
- press "ZZ" (to close tab) and "ZZ" (to close vim);
- or execute ":write", ":quit" (to close tab), ":quit" (to close vim).

**Comment by guraga** [comment]
Mark saved, if run

``` bash
./vim-7.4.230 test_file.txt
```

move cursor and press "ZQ".

Also mark saved, if run

``` bash
./vim-7.4.230
```

execute ":edit test_file.txt", move cursor, press "ZQ".

Why it is not saved, if executed ":tabnew" command? It's seems as a bug.

**Comment by vim-ml** [comment]
Hi guraga and list,

2016-8-11(Thu) 16:54:13 UTC+9 guraga:

> Mark saved, if run
> 
> ./vim-7.4.230 test_file.txt
> 
> move cursor and press "ZQ".
> 
> Also mark saved, if run
> 
> ./vim-7.4.230
> 
> execute ":edit test_file.txt", move cursor, press "ZQ".
> 
> Why it is not saved, if executed ":tabnew" command? It's seems as a bug.

I investegasted and grasped.
This problem occurs with a combination of tabpage closed and buffer closed.

I'm writing a patch now.

## Please wait a few hours.

Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by vim-ml** [comment]
Hi,

2016-8-11(Thu) 18:50:11 UTC+9 h_east:

> Hi guraga and list,
> 
> 2016-8-11(Thu) 16:54:13 UTC+9 guraga:
> 
> > Mark saved, if run
> > 
> > ./vim-7.4.230 test_file.txt
> > 
> > move cursor and press "ZQ".
> > 
> > Also mark saved, if run
> > 
> > ./vim-7.4.230
> > 
> > execute ":edit test_file.txt", move cursor, press "ZQ".
> > 
> > Why it is not saved, if executed ":tabnew" command? It's seems as a bug.
> 
> I investegasted and grasped.
> This problem occurs with a combination of tabpage closed and buffer closed.
> 
> I'm writing a patch now.
> Please wait a few hours.

I attached a patch.
I am glad if you could confirm.

Investigation result:
When `close_buffer()` has been called from `win_close_othertab()`, `curtab` does not contained `win`.
So `win_valid()` result is FALSE, then doesn't save the last cursor position of file.

I add the `tabpage_T *tp` to the argument of `close_buffer()`, it has been changed to window validation check using it.
In order to realize this, I add the function `win_valid_in_tabpage()`.

## Please confirm this.

Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by guraga** [comment]
This patch work. Thank you.
