### ISSUE TITLE
Using compiled functions in ftplugin breaks let statements in b:undo_ftplugin

### ISSUE THREAD

**Issue by itchyny** [vim/vim#9741]
### Steps to reproduce

1. Execute `set ft=rust` twice.
2. Get following error.

```
Error detected while processing FileType Autocommands for "*"..function <SNR>5_LoadFTPlugin:
line    2:
E1126: Cannot use :let in Vim9 script
```

This is likely a breaking change by https://github.com/vim/vim/commit/3e79c97c18c50f97797ab13ed81c4011eba9aba0 .
The current rust ftplugin contains b:undo_ftplugin including let statements (https://github.com/vim/vim/blob/v8.2.4300/runtime/ftplugin/rust.vim#L151).
The undo ftplugin looks the similar problem too.
For compatibility of executing undo_* variables, maybe we should not migrate these functions to Vim9 script.

### Expected behaviour

Shows no error.

### Version of Vim

8.2.4300

### Environment

macOS 12.2, iTerm2 3.4.12

**Comment by itchyny** [comment]
> The undo ftplugin looks the similar problem too.

Oops, I mean runtime/indent.vim.

**Comment by matveyt** [comment]
I guess that implies executing `b:undo_ftplugin` (as well as `b:undo_indent`) in legacy mode. However the problem is that `legacy exe b:undo_ftplugin` is still executed in the current mode (i.e. vim9script). Is that another bug?

**Comment by brammool** [comment]
Using "legacy exe" appears to fix it.  What other problem do you see?

**Comment by lacygoill** [comment]
Actually, maybe it's a bug.  Because here, `:legacy` doesn't stop at the bar:

    :legacy execute 'eval 0 is# 0 | eval 0 is# 0'

**Comment by lacygoill** [comment]
Ah no, I was right, `:legacy` does stop at the bar in Vim9 context:
```vim
vim9script
legacy execute 'if true | eval 0 is# 0 | endif'
```
    E15: Invalid expression: "is# 0 | endif"
    E171: Missing :endif

**Comment by lacygoill** [comment]
Actually, it's not even the bar which is problematic.  It's the fact that the modifier is not applied at all with an `:execute`.  And it's not specific to `:legacy`.  Same issue with `:vim9cmd`:

    :vim9cmd execute 'eval () => 123'

**Comment by matveyt** [comment]
>The question is: should it?

IMO, it should NOT. Consider also that both `:execute` and `execute()` do supersede, while `:eval` and `eval()` do not. This is really confusing.

**Comment by brammool** [comment]
> I noticed [this issue](https://github.com/lacygoill/wiki/blob/master/bug/vim.md#-72) a long time ago, but I thought it was working as intended.  I think that `:execute` automatically runs the command at the script level.  Here, the script is written in Vim9 context.  Therefore, the command is executed in Vim9 context.  IOW, `:execute` supersedes `:legacy` and `:vim9cmd`.   The question is: should it?  If it should, then there is no bug, and the solution is simply to execute `b:undo_ftplugin` from a legacy function.
> ```diff
> diff --git a/runtime/ftplugin.vim b/runtime/ftplugin.vim
> index 2500a7f27..01c092e8f 100644
> --- a/runtime/ftplugin.vim
> +++ b/runtime/ftplugin.vim
> @@ -22,7 +22,7 @@ endif
>  def LoadFTPlugin()
>    if exists("b:undo_ftplugin")
>      # We assume b:undo_ftplugin is using legacy script syntax
> -    legacy exe b:undo_ftplugin
> +    call s:UndoFtplugin()
>      unlet! b:undo_ftplugin b:did_ftplugin
>    endif
>  
> @@ -41,3 +41,7 @@ def LoadFTPlugin()
>      endfor
>    endif
>  enddef
> +
> +function s:UndoFtplugin() abort
> +  exe b:undo_ftplugin
> +endfunction
> ```

This looks more like a workaround than a solution.  When using
"legacy exe" I would think most people expect "legacy" to apply to the
commands that "exe" will execute.  It's mostly pointless otherwise.
Well, it could apply to evaluating the argument of ":execute" I suppose.
Would someone read it that way?

Let me make this work for :legacy and :vim9script.  There might be other
modifiers that need to be handled like this, please come up with
examples if you can think of some.

-- 
The History of every major Galactic Civilization tends to pass through
three distinct and recognizable phases, those of Survival, Inquiry and
Sophistication, otherwise known as the How, Why and Where phases.
For instance, the first phase is characterized by the question 'How can
we eat?' the second by the question 'Why do we eat?' and the third by
the question 'Where shall we have lunch?'
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by wez** [comment]
I just ran into this on Fedora 35 after installing today's critical updates.  The error message is not easy to run down: it doesn't show a filename to give clues on what to look at, so I spent some time trying to figure out why vim9 was mentioned when I had vim8.2 and whether this was something I needed to fix in my dotfiles :-(

Is there scope for making that error messaging clearer?

**Comment by brammool** [comment]
It is working properly after the latest fixes, right?

It's difficult to give better error messages, since there are so many places involved.

**Comment by lacygoill** [comment]
For this kind of reasons, I've been thinking we should have a builtin package which populates the quickfix list with the last errors logged in `:messages`.  Similar to [`cfilter-plugin`](https://vimhelp.org/quickfix.txt.html#cfilter-plugin).

I have [something](https://github.com/lacygoill/vim-stacktrace) like that:

![gif](https://user-images.githubusercontent.com/8505073/153787886-39a8249a-005f-4887-b32e-7c34052c1df8.gif)

But I still need to improve it in a corner case (the parsing doesn't fully handle an error given for a lambda which failed to compile).  Also, not sure about the order of the display (first errors at the top vs at the bottom; in a given stack, last frame at the top vs at the bottom).

**Comment by cuviper** [comment]
> I just ran into this on Fedora 35 after installing today's critical updates.

> It is working properly after the latest fixes, right?

It's working for me with Fedora's update to [vim-8.2.4386-1.fc35](https://bodhi.fedoraproject.org/updates/FEDORA-2022-9cef12c14c).
