### ISSUE TITLE
Esc is sometimes interpreted as Enter while command-line popup menu is displayed

### ISSUE THREAD

**Issue by bfrg** [vim/vim#9749]
### Steps to reproduce

1. Run `vim --clean -S test.vim`, with
```vim
" test.vim
function MyStatusLine() abort
    return '%<%f %h%m%r%=%-14.(%l,%c%V%) %P'
endfunction

set statusline=%!MyStatusLine()
set laststatus=2
set wildoptions=pum
```

2. Open the command-line popup menu, for example with `:is<tab>`. While the popup menu is displayed, press `<Esc>`.
3. Result:
```
E389: Couldn't find pattern
```

The error is thrown because `<Esc>` is interpreted as a `<Cr>` while the popup menu is shown.

This seems to happen only when a user function is used in `'statusline'` and the statusline is displayed.

### Expected behaviour

`<Esc>` should always behave the same when the command-line popup menu is displayed.

### Version of Vim

8.2.4342

### Environment

Linux

**Comment by lacygoill** [comment]
I can confirm the issue, but we need to enable `'wildmenu'`:
```vim
vim9script
function MyStatusLine() abort
    return ''
endfunction
set statusline=%!MyStatusLine()
set laststatus=2
set wildoptions=pum
set wildmenu
```
I tried to log the channel activity to see if something unexpected was happening, but didn't find anything:

    ==== start log session ====
      0.000069 : raw terminal output: "[2;1H▽[6n"
      0.000103 : raw terminal output: "[2;1H  [3;1HPzz\[0%m[6n"
      0.000141 : SafeState: Start triggering
      0.000523 : raw terminal output: "[?25l[2;1H[94m~                                                                                                                      [3;1H~                                                                                                                      [4;1H~                                                                                                                      [5;1H~                                                                                                                      [6;1H~                                                                                                                      [7;1H~                                                                                                                      [8;1H~                                                                                                                      [9;1H~                                                                                                                      [10;1H~                                                                                                                      [11;1H~                                                                                                                      [12;1H~                                                                                                                      [13;1H~                                                                                                                      [0m[14;1H[1m[7m                                                                                                                       ]0;[No Name] - VIM"
      0.000568 : raw key input: "[2;2R[3;1R"
      0.000580 : looking for messages on channels
      0.000585 : SafeState: back to waiting, triggering SafeStateAgain
      0.775224 : raw key input: ":"
      0.775293 : SafeState: reset: key typed
      0.775398 : SafeState: Start triggering
      0.775441 : looking for messages on channels
      0.775451 : SafeState: back to waiting, triggering SafeStateAgain
      1.007321 : raw key input: "i"
      1.007388 : SafeState: reset: key typed
      1.007418 : SafeState: Start triggering
      1.007455 : looking for messages on channels
      1.007464 : SafeState: back to waiting, triggering SafeStateAgain
      1.119235 : raw key input: "s"
      1.119298 : SafeState: reset: key typed
      1.119325 : SafeState: Start triggering
      1.119358 : looking for messages on channels
      1.119366 : SafeState: back to waiting, triggering SafeStateAgain
      1.359323 : raw key input: "	"
      1.359391 : SafeState: reset: key typed
      1.359975 : looking for messages on channels
      1.793521 : raw key input: ""
      1.793597 : looking for messages on channels
      2.794909 : ERROR: E389: Couldn't find pattern
      2.795000 : SafeState: Start triggering
      2.795117 : looking for messages on channels
      2.795134 : SafeState: back to waiting, triggering SafeStateAgain

Between the escape keypress, and the error message, there is nothing except for a "looking for messages on channels":

      1.793521 : raw key input: ""
      1.793597 : looking for messages on channels
      2.794909 : ERROR: E389: Couldn't find pattern
