### ISSUE TITLE
terminal window not cleared in the GUI when calling `system()` from completion function and `!` flag in 'guioptions'

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9759]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -g -S <(tee <<'EOF'
        vim9script
        &guioptions ..= '!'
        &wildchar = 9
        &wildmenu = true
        command -nargs=* -complete=custom,Complete Cmd eval 0 + 0
        def Complete(..._): string
            system(':')
            return "a\nb"
        enddef
        feedkeys(":Cmd \<Tab>")
    EOF
    )

`:Cmd ...` is printed on the command-line.
A hit-enter prompt is given.
A terminal window is open in a top split.

**Expected behavior**

`:Cmd a` is printed on the command-line.
No hit-enter prompt is given.
No terminal window is open.

**Version of Vim**

8.2 Included patches: 1-4359

**Environment**

Operating system: Ubuntu 20.04.3 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: zsh 5.8

**Logs and stack traces**

N/A

**Comment by brammool** [comment]
have you tried putting "silent" or "silent!" before the system() call?

**Comment by lacygoill** [comment]
Yes, sorry, `:silent[!]` does suppress the hit-enter prompt, and correctly prints the first suggestion.  The issue is simply the terminal window which is distracting.  `:silent` doesn't prevent its display.  Even more distracting, as long as the wildmenu is open, all the windows are equalized.

So, instead of writing this:

    def TldrCompletion(_, _, _): string
        return return system('tldr --list 2>/dev/null | tr -s "[ \t]" "\n"')
    enddef

I have to write this:

    def TldrCompletion(_, _, _): string
        var go_save: string = &guioptions
        set guioptions-=!
        silent var suggestions: string = system('tldr --list 2>/dev/null | tr -s "[ \t]" "\n"')
        &guioptions = go_save
        return suggestions
    enddef

I guess it's just a corner case, so I'll close the issue.

**Comment by brammool** [comment]
> Yes, sorry, `:silent[!]` does suppress the hit-enter prompt, and
> correctly prints the first suggestion.  The issue is simply the
> terminal window which is distracting.  `:silent` doesn't prevent its
> display.  Even more distracting, as long as the wildmenu is open, all
> the windows are equalized.
> 
> So, instead of writing this:
> 
>     def TldrCompletion(_, _, _): string
>         return return system('tldr --list 2>/dev/null | tr -s "[ \t]" "\n"')
>     enddef
> 
> I have to write this:
> 
>     def TldrCompletion(_, _, _): string
>         var go_save: string = &guioptions
>         set guioptions-=!
>         silent var suggestions: string = system('tldr --list 2>/dev/null | tr -s "[ \t]" "\n"')
>         &guioptions = go_save
>         return suggestions
>     enddef
> 
> I guess it's just a corner case, so I'll close the issue.

There is a section in the win32 FAQ that mentions using /min or /b to
avoid a window showing up.  Not sure if that helps in this situation.

On older Windows systems the console window was required to avoid Vim
crashed with some external commands.  Not sure if that is still true
these days.  Perhaps a hidden terminal window could work.

-- 
Just remember...if the world didn't suck, we'd all fall off.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
