### ISSUE TITLE
'cursorline' and 'relativenumber' not updated if win_execute() moves cursor

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#9766]
### Steps to reproduce

1. Run `vim --clean`
2. Source the following file:
```vim
call setline(1, ['aaa', 'bbb'])
set relativenumber cursorline
call cursor(1, 1)
split
```
3. Type `:call win_execute(win_getid(winnr('#')), 'call cursor(2, 1)')`
4. `'relativenumber'` and `'cursorline'` are not updated in the bottom window

### Expected behaviour

`'relativenumber'` and `'cursorline'` are updated in the bottom window

### Version of Vim

8.2.4350

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

**Comment by lacygoill** [comment]
Does adding a `:redraw` help?

    :call win_execute(win_getid(winnr('#')), ['call cursor(2, 1)', 'redraw'])

**Comment by zeertzjq** [comment]
That should work. However there is already <https://github.com/vim/vim/commit/345f28df5482cd35f5fa74b06443376379f113b0> which updates the statusline, so I think something similar should be done for `'relativenumber'` and `'cursorline'`.

**Comment by brammool** [comment]
When the cursor moves in a window other than the current one there is no redraw.  I don't think there is a good reason to change that.  As mentioned, you can use :redraw if you do want to see the update.
