### ISSUE TITLE
v8.2.4002 broke the terminal of vim.exe (using VIMDLL)

### ISSUE THREAD

**Issue by ghost** [vim/vim#9769]
### Steps to reproduce

1. make vim.exe using VIMDLL=yes
2. vim.exe -c "term"
3. Use the mouse in the window opened by :term

### Expected behaviour

Wrong escape sequence is issued and editing cannot be continued.

### Version of Vim

8.2.4002

### Environment

Windows 11, cmd.exe, 

### Logs and stack traces

```shell
Function to convert CSI called from multiple places getchar.c/fix_input_buffer().
Temporarily invert and call the important flag gui.in_use from one location, and do not invert it from another. Inconsistency due to it.

This patch removes ifndef MSWIN to get it through, causing some catastrophic processing that MSWIN doesn't need.

I wrote a patch to fix it, did not submit it, did not have time to verify it, and cared for a bedridden mother.
I reverted the local.
A long time ago, there was a person who scattered dangling in the source tree, who is this too?
```

**Comment by brammool** [comment]
Does it work OK when using Vim without VIMDLL=yes ?
Thus is it a problem of VIMDLL?

**Comment by k-takata** [comment]
#9469 removed `#ifndef MSWIN` but actually it is needed for VIMDLL. (I added it in 8.1.1230).
Restoring the `#ifndef` should fix the issue.

```diff
--- a/src/getchar.c
+++ b/src/getchar.c
@@ -3671,6 +3671,7 @@ fix_input_buffer(char_u *buf, int len)
 	    p += 2;
 	    i -= 2;
 	}
+# ifndef MSWIN
 	// When the GUI is not used CSI needs to be escaped.
 	else if (!gui.in_use && p[0] == CSI)
 	{
@@ -3680,6 +3681,7 @@ fix_input_buffer(char_u *buf, int len)
 	    *p = (int)KE_CSI;
 	    len += 2;
 	}
+# endif
 	else
 #endif
 	if (p[0] == NUL || (p[0] == K_SPECIAL
```

CSI is handled differently in the Windows console version and in the Unix console version. So, this `#ifndef` is needed.

BTW, I'm not sure how to add a test for this.

**Comment by k-takata** [comment]
```c
3674 | # ifndef MSWIN
3675 | 	// When the GUI is not used CSI needs to be escaped.
3676 | 	else if (!gui.in_use && p[0] == CSI)
```

Line 3674 can be also `# ifndef VIMDLL`. This may clarify that this block is needed when VIMDLL is not used.
However, `!gui.in_use` in line 3676 will never be true on the Windows GUI version without VIMDLL. So, I use `# ifndef MSWIN` here.

**Comment by brammool** [comment]
Hmm, putting back the #ifndef caused a test to fail.  We probably need another solution.

**Comment by brammool** [comment]
This is because in ins_char_typebuf() gui.in_use is temporarily set to FALSE.

**Comment by brammool** [comment]
The proper solution would be to pass a flag to fix_input_buffer() to behave differently, instead of temporarily resetting gui.in_use (which is very confusing).

**Comment by zeertzjq** [comment]
Maybe some logic in `add_char_buff()` can be extracted into a separate function and used here instead?

**Comment by zeertzjq** [comment]
Oh, there is also similar logic in `add_char2buf()`. That one seems better.
