### ISSUE TITLE
cl-pum: <ESC> has been treated as <ENTER> in cmdline when pum is visible

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#9776]
### Steps to reproduce

1. edit `minimal.vim`:

```viml
set nocompatible
set ttimeout ttimeoutlen=80 
set wildmenu
set wop=pum 
set showtabline=2 number laststatus=2 signcolumn=yes

function! My_TabLine()
        let s = 'My Tab Line'
        return s
endfunc

set tabline=%!My_TabLine()
```

2. start vim with `minimal.vim`:

```bash
vim -u minimal.vim
```

3. enter manually:

```
:h index<tab>
```

4. select the first entry in the pum window, then press `<ESC>`.

### Expected behaviour

The pum window should be closed and I will leave the command mode after pressing `<ESC>`, just like the old wildmenu.

![图片](https://user-images.githubusercontent.com/3035071/153922606-329c6cd0-9b8c-488f-afe5-b9d1e8ca9deb.png)

But actually, the `<ESC>` has been treated as `<ENTER>` and the command `:h index` got executed:

![图片](https://user-images.githubusercontent.com/3035071/153922960-1fa2e502-a606-4326-8cee-e365db6fe648.png)

100% reproducable, introduced after: https://github.com/vim/vim/pull/9707 

### Version of Vim

8.2.4370

### Environment

OS: Debian 11.2
terminal, 
$TERM: xterm-256colors
shell: zsh-5.8

**Comment by skywind3000** [comment]
Some clues:

1. this issue will be triggerred if I provide a customized tabline function, if the tabline is commented, it works as expected.
2. maybe I discovered an old potential issue in the cmdline:

```bash
vim -u NONE -c 'call feedkeys(":h index\<esc>", "")'
```

A similar issue applied to all vim, the `<esc>` above will be treated as `<enter>`, and will display the `:h index` page after start.

```

**Comment by brammool** [comment]
Looks like Patch 8.2.4346 did not solve it completely

That Esc executes the command line when 'compatible' is set is normal, this is how Vi worked.
See ":help cpo-x".

**Comment by skywind3000** [comment]
thanks, I read the document and double check the `cpo-x` with a new script `escape.vim`:

```VimL
set nocompatible
set cpo-=x
call feedkeys(":h index\<esc>")
```

command:

```bash
vim -u escape.vim
```

and found that the `<esc>` were still working in the compatible mode.
