### ISSUE TITLE
Ignore nore on <Plug> mappings

### ISSUE THREAD

**Issue by shadmansaleh** [vim/vim#9789]
### Issue
`<Plug>` maps don't work if they are mapped with `nore` (when remaping the key is disabled) as they relay on repamping.

This leads to a lot of confusion especially among new users.
I think every one had that one time when a mapping wasn't working and after lots of looking you figured out you need to remove that `nore` from the command.
 
### Possible solution
I think this can be avoided if vim just ignores `nore` part for `<Plug>` mappings and always remaps that key .

So no matter whether
```vim
:nmap abcd <Plug>(xyz)
```
Or
```vim
:nnoremap abcd <Plug>(xyz)
```
used to define the mapping vim behaves as if first one was used.

**Comment by brammool** [comment]
Maybe when using "noremap" with "<Plug>" in the rhs we should give an error?

**Comment by shadmansaleh** [comment]
> Maybe when using "noremap" with "" in the rhs we should give an error?

We could . But I'd definitely prefer if it worked with `noremap` too. That way users mostly doesn't need to be concerned about nore part of map commands (less mental burden :) . As far as I'm aware recursive maps are only used for \<Plug> mappings for other mappings non recursive maps are always recommended.  

I think adding a condition around here to check if m_str starts with <Plug> will be enough for this ?
https://github.com/vim/vim/blob/d288eaad846f0e07e0141226f97d858dcf96cb78/src/getchar.c#L2893

**Comment by nickspoons** [comment]
`<plug>` maps _are_ recursive. Just catching the incorrect usage and adding an invisible workaround makes the terms "map" and "noremap" even more opaque. I like the idea of raising an error though, that will help users understand what's happening, rather than simply facilitating continuing to use the wrong command without knowing why.

**Comment by shadmansaleh** [comment]
Consider something like this
```vim
let loaded_my_special_plugin=1
nnoremap <Plug>(sp_delete_line) <Cmd>delete<CR>
" unlet loaded_my_special_plugin

func! s:delete_line()
  if exists("g:loaded_my_special_plugin")
    return "\<Plug>(sp_delete_line)"
  else
    return "dd"
  endif
endf

nnoremap <expr> <leader>d <SID>delete_line()
```
Where a `expr` map returns a regular or a \<Plug> map . Which is appropriate for this remaped or nonremaped . For the \<Plug> part of the map to work this needs to be remaped . But then when it's remaped I can no longer trust dd is actually builtin dd not some other map .

This is a reason why I think making noremap fill maps usecase is actually an improvement . With \<Plug> maps working with `nmap` can almost always be skiped as `noremap` will be a better alternative.

**Comment by shadmansaleh** [comment]
Relevant neovim patch  https://github.com/neovim/neovim/pull/16969/commits/0347875a5c11258ebb6377a1ab79b04fe9c55bc9

If you guys are in favor of the idea it shouldn't be hard to port it over to vim.

Also @brammool what do you think about adding an autocmd event on highlight change . That gets triggered if user changes a highlight definition or creates a mew highlight (:hi/hlset() uses) . It would be useful for updating plugins highlight groups that depend on other hl_groups. For example say I create a hl group MyPlugNormal that has same bg as Normal but fg is different . If I can detect change in Normal I can update background of MyPlugNormals bg to match Normal easily . Is there currently any way to track change in highlight groups ?

**Comment by brammool** [comment]
The help for the NeoVim patch is unclear:
```
Note: "nore" is ignored for a mapping whose result
starts with <Plug>.  <Plug> is always remapped even if
"nore" is used.
```
It first says "nore" is ignored, which would mean that the whole RHS, also whatever follows <Plug>, is remapped.
The second sentence says that "nore" only applies to <Plug> itself.  Which one is it?

If the <Plug> in a "noremap" would be mapped, but the rest isn't, that sounds useful.
It would be quite difficult to get this effect in another way (best I can think of is using two mappings).

**Comment by nickspoons** [comment]
The neovim PR includes [this comment](https://github.com/neovim/neovim/pull/16969#issuecomment-1052292967), which does indeed look more useful:

> Now this should only ignore `<Plug>` mappings previously cases like
> 
>     nnoremap d dgg<Plug>(what-ever)dG
> 
> wasn't handled correctly . Now `nore` will be respected for prefix `dgg` and suffix `dG` but will be ignored for the `<Plug>(what-ever)` map.

**Comment by zeertzjq** [comment]
I've changed the doc in <https://github.com/neovim/neovim/pull/17557>.

**Comment by brammool** [comment]
> > It first says "nore" is ignored, which would mean that the whole RHS,
> > also whatever follows , is remapped.
> > The second sentence says that "nore" only applies to <Plug> itself.
> > Which one is it?
> 
> Second one . Nore is only ignored for the \<Plug> part of rhs. Other
> portions respect nore . The docs got out of sync . As zeertzjq said he
> updated the docs later on a separate pr 

OK, that sounds useful.  Can someone create a PR for that?

-- 
hundred-and-one symptoms of being an internet addict:
143. You dream in pallettes of 216 websafe colors.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
