### ISSUE TITLE
Some directory and file permissions not set when installed from source.

### ISSUE THREAD

**Issue by danzollers** [vim/vim#9793]
### Steps to reproduce

(As root)
```
# umask 027
# mkdir /opt/vim   # Can be any new directory, permissions `755`
# ./configure --prefix=/opt/vim && make && make install
```

### Expected behaviour

All directories created during the install have permission `755`, and all files have (at least) `644`.

But with `umask 027`, I find:
```
# find /opt/vim -type d ! -perm -004
./share
./share/vim/vim82/colors/lists
./share/man
./share/man/fr.ISO8859-1
./share/man/tr.UTF-8
./share/man/de
./share/man/de.UTF-8
./share/man/tr.ISO8859-9
./share/man/pl.ISO8859-2
./share/man/fr
./share/man/da.ISO8859-1
./share/man/de.ISO8859-1
./share/man/da
./share/man/tr
./share/man/fr.UTF-8
./share/man/da.UTF-8
./share/man/it
./share/man/ru.UTF-8
./share/man/pl
./share/man/it.UTF-8
./share/man/ja
./share/man/pl.UTF-8
./share/man/it.ISO8859-1
./share/man/ru.KOI8-R
```
and

```
# find /opt/vim -type f ! -perm -004
/opt/vim/share/vim/vim82/ftplugin/logtalk.dict
/opt/vim/share/vim/vim82/colors/lists/default.vim
/opt/vim/share/vim/vim82/colors/lists/csscolors.vim
```
The directories have permissions `750` and files have permissions `640`.

### Version of Vim

8.2.4411

### Environment

Operating System: Arch Linux
Terminal: XTerm(370)
Value of $TERM: xterm-256color
Shell: zsh

**Comment by brammool** [comment]
Permissions 750 and 640 do not appear in src/Makefile.  No idea where they came from.
Perhaps your environment defined them?  Unfortunately, "make" picks up random environment variables, that can be confusing.

**Comment by brammool** [comment]
I see.  Those files were added without updating the permissions.
The others should be in install-sh.
I'll make a patch.  Please check and reopen the issue if not everything is covered.
