### ISSUE TITLE
Vim9: documentation about exists() could be improved

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9796]
From [`:help exists()`](https://vimhelp.org/builtin.txt.html#exists%28%29):

    *funcname       built-in function (see |functions|)
                    or user defined function (see
                    |user-functions|) that is implemented.
                    Also works for a variable that is a
                    Funcref.

For a user-defined function, the asterisk can be removed.  Whether it's local to the current script:
```vim
vim9script
def Func()
enddef
echomsg exists('Func')
```
    1

Or global:
```vim
vim9script
def g:Func()
enddef
echomsg exists('g:Func')
```
    1

Is it working as intended?  If so, maybe it should be documented:
```diff
diff --git a/runtime/doc/builtin.txt b/runtime/doc/builtin.txt
index 299bcba63..f34baf23b 100644
--- a/runtime/doc/builtin.txt
+++ b/runtime/doc/builtin.txt
@@ -2105,6 +2105,8 @@ exists({expr})	The result is a Number, which is |TRUE| if {expr} is defined,
 					|user-functions|) that is implemented.
 					Also works for a variable that is a
 					Funcref.
+					Note that in Vim9 script, the asterisk
+					can be omitted.
 			?funcname	built-in function that could be
 					implemented; to be used to check if
 					"funcname" is valid
```

---

Still at [`:help exists()`](https://vimhelp.org/builtin.txt.html#exists%28%29), this example is given:

    exists("*s:MyFunc")

It doesn't work in Vim9 script:
```vim
vim9script
def MyFunc()
enddef
echo exists("*s:MyFunc")
```
    E1268: Cannot use s: in Vim9 script: s:MyFunc

I think the `s:` prefix is no longer allowed in a Vim9 script since the patch [8.2.4360](https://github.com/vim/vim/releases/tag/v8.2.4360).

How about giving 2 examples?  One for legacy Vim script, the other for Vim9 script:
```diff
diff --git a/runtime/doc/builtin.txt b/runtime/doc/builtin.txt
index 299bcba63..c209d5165 100644
--- a/runtime/doc/builtin.txt
+++ b/runtime/doc/builtin.txt
@@ -2137,7 +2137,8 @@ exists({expr})	The result is a Number, which is |TRUE| if {expr} is defined,
 			exists("&shortname")
 			exists("$HOSTNAME")
 			exists("*strftime")
-			exists("*s:MyFunc")
+			exists("*s:MyFunc") " in legacy Vim script
+			exists("MyFunc")    # in Vim9 script
 			exists("bufcount")
 			exists(":Make")
 			exists("#CursorHold")
```
---

From [`:help vim9-reload`](https://vimhelp.org/vim9.txt.html#vim9-reload):

    You want to use this in scripts that use a `finish` command to bail out at
    some point when loaded again.  E.g. when a buffer local option is set: >
            vim9script noclear
            setlocal completefunc=SomeFunc
            if exists('*g:SomeFunc')
              finish
            endif
            def g:SomeFunc()
            ....

There is no need for a global function.  If the reader wants to install a completion function, they should put it in the script-local namespace over which they have total control, rather than the global one for which they don't know what will be in there at runtime.

I think the example was written at a time when it was not easy to assign a script-local function to a `'*func'` option.  That's no longer the case since the patch [8.2.3838](https://github.com/vim/vim/releases/tag/v8.2.3838).

Maybe the example should reflect that:
```diff
diff --git a/runtime/doc/vim9.txt b/runtime/doc/vim9.txt
index edd61d968..05cd9ac78 100644
--- a/runtime/doc/vim9.txt
+++ b/runtime/doc/vim9.txt
@@ -284,11 +284,11 @@ If you do want to keep items, use: >
 You want to use this in scripts that use a `finish` command to bail out at
 some point when loaded again.  E.g. when a buffer local option is set: >
 	vim9script noclear
-	setlocal completefunc=SomeFunc
-	if exists('*g:SomeFunc')
+	setlocal completefunc=s:SomeFunc
+	if exists('SomeFunc')
 	  finish
 	endif
-	def g:SomeFunc()
+	def SomeFunc()
 	....
 
 
```

**Comment by lacygoill** [comment]
> I think this works:

It would be nice if it did, but unfortunately we still need the `s:` prefix when setting the option.

    setlocal completefunc=SomeFunc
                          ^
                          ✘

    setlocal completefunc=s:SomeFunc
                          ^^
                          ✔

Without, an error is given:
```vim
vim9script noclear
setlocal completefunc=SomeFunc
if exists('*SomeFunc')
    finish
endif
def SomeFunc(findstart: bool, base: string): any
    if findstart
        return searchpos('\<', 'bcnW')[1]
    else
        var res: list<string>
        for m in split('Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec')
            if m =~ '^' .. base
                res->add(m)
            endif
        endfor
        return res
    endif
enddef
feedkeys("i\<C-X>\<C-U>")
```
    E117: Unknown function: SomeFunc

That's a pitfall common to all `'*func'` options.  In contrast, we can drop `s:` when setting `'*expr'` options:
```vim
vim9script
var lines =<< trim END
    # title 1
    aaa
    # title 2
    bbb
END
lines->writefile('/tmp/file')
set foldexpr=FoldExpr() foldmethod=expr
def FoldExpr(): string
    return getline(v:lnum) =~ '^#' ? '>1' : '='
enddef
edit /tmp/file
```

**Comment by brammool** [comment]
> > I think this works:
> 
> It would be nice if it did, but unfortunately we still need the `s:` prefix when setting the option.
> 
>     setlocal completefunc=SomeFunc
>                           ^
>                           ✘
> 
>     setlocal completefunc=s:SomeFunc
>                           ^^
>                           ✔

Ah yes, get_scriptlocal_funcname() recognizes "s:" and "<SID>" but
doesn't try looking up the function without a prefix.  We can fix that.


-- 
hundred-and-one symptoms of being an internet addict:
71. You wonder how people walk

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
