### ISSUE TITLE
[BUG] Wrong VIM directory in Termux (compiling from source)

### ISSUE THREAD

**Issue by pokemaniac05** [vim/vim#9798]
# Termux details
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
## sources.list
deb https://grimler.se/termux-packages-24/ stable main
## x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
debianutils/stable 5.7 aarch64 [upgradable from: 5.5]
harfbuzz/stable 3.4.0 aarch64 [upgradable from: 3.3.1]
python/stable 3.10.2-3 aarch64 [upgradable from: 3.10.2-2]
Android version:
10
Kernel build information:
Linux localhost 4.14.116 #1 SMP PREEMPT Wed Dec 1 14:29:20 CST 2021 aarch64 Android
Device manufacturer:
HUAWEI
Device model:
ART-L29

## Description of the problem
I installed Termux from Fdroid on HUAWEI P40 lite E and I compiled vim to get latest version using the following commands:
`./configure --prefix=$PREFIX --with-x`

`make -j4`

`make install`

VIM is installed successfully in PREFIX, but it looks for VIM directory in `/usr/local/share/vim` even if I set prefix.
I found the following workaround: setting the correct directory as VIM variable in `~/.bashrc`

**Comment by lacygoill** [comment]
I can't reproduce in a docker container:

    $ sudo --preserve-env=DOCKER_CONFIG docker run --interactive=true --tty=true --rm=true kcubeterm/termux:latest
    $ mkdir prefix_dir
    $ export PREFIX=$HOME/prefix_dir
    $ export PATH=$PREFIX/bin/:$PATH
    $ pkg install clang git libx11 libxt make xorgproto
    $ git clone --depth=1 https://github.com/vim/vim
    $ cd vim/
    $ ./configure --prefix=$PREFIX --with-x
    $ make
    $ make install
    $ vim

    :scriptnames
      1: ~/prefix_dir/share/vim/vim82/defaults.vim
      2: ~/prefix_dir/share/vim/vim82/filetype.vim
      3: ~/prefix_dir/share/vim/vim82/ftplugin.vim
      4: ~/prefix_dir/share/vim/vim82/indent.vim
      5: ~/prefix_dir/share/vim/vim82/syntax/syntax.vim
      6: ~/prefix_dir/share/vim/vim82/syntax/synload.vim
      7: ~/prefix_dir/share/vim/vim82/syntax/syncolor.vim
      8: ~/prefix_dir/share/vim/vim82/colors/lists/default.vim
      9: ~/prefix_dir/share/vim/vim82/plugin/getscriptPlugin.vim
     10: ~/prefix_dir/share/vim/vim82/plugin/gzip.vim
     11: ~/prefix_dir/share/vim/vim82/plugin/logiPat.vim
     12: ~/prefix_dir/share/vim/vim82/plugin/manpager.vim
     13: ~/prefix_dir/share/vim/vim82/plugin/matchparen.vim
     14: ~/prefix_dir/share/vim/vim82/plugin/netrwPlugin.vim
     15: ~/prefix_dir/share/vim/vim82/plugin/rrhelper.vim
     16: ~/prefix_dir/share/vim/vim82/plugin/spellfile.vim
     17: ~/prefix_dir/share/vim/vim82/plugin/tarPlugin.vim
     18: ~/prefix_dir/share/vim/vim82/plugin/tohtml.vim
     19: ~/prefix_dir/share/vim/vim82/plugin/vimballPlugin.vim
     20: ~/prefix_dir/share/vim/vim82/plugin/zipPlugin.vim

The last Ex command prints all the scripts that Vim sourced since it started up the current session.  None of them is under `/usr/local/share/vim`.  They are all under `~/prefix_dir/share/vim/`.

---

In Vim, what's the output of `:version`?
In the shell, what's the output of `type -a vim`?

---

In case it helps, have a look at [`:help $VIM`](https://vimhelp.org/starting.txt.html#%24VIM).  It explains how Vim decides where to look for scripts during startup.

**Comment by pokemaniac05** [comment]
I tried to unset VIM variable used to fix and vim starts normally. Vim version is 8.2.4362
