### ISSUE TITLE
Vim9: no error for passing argument with wrong type to lambda used in `map()`

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9802]
If we pass an argument with a wrong type to a lambda, an error is given at compile time:
```vim
vim9script
def Func()
    ((s: string) => 0)(123)
enddef
defcompile
```
    E1013: Argument 1: type mismatch, expected string but got number

But if we pass the same argument with the same wrong type to a lambda which is run by a higher order function such as `map()`, no error is given:
```vim
vim9script
def Func()
    [123]->map((_, s: string) => 0)
enddef
defcompile
```
    no error

We need to wait until runtime:
```vim
vim9script
def Func()
    [123]->map((_, s: string) => 0)
enddef
Func()
```
    E1013: Argument 2: type mismatch, expected string but got number

Could we give an error earlier (i.e. at compile time) when passing wrong arguments to a lambda which is used by `map()`, `filter()`, ... ?

**Comment by brammool** [comment]
> If we pass an argument with a wrong type to a lambda, an error is
> given at compile time:
> ```vim
> vim9script
> def Func()
>     ((s: string) => 0)(123)
> enddef
> defcompile
> ```
>     E1013: Argument 1: type mismatch, expected string but got number
> 
> But if we pass the same argument with the same wrong type to a lambda which is run by a higher order function such as `map()`, no error is given:
> ```vim
> vim9script
> def Func()
>     [123]->map((_, s: string) => 0)
> enddef
> defcompile
> ```
>     no error
> 
> We need to wait until runtime:
> ```vim
> vim9script
> def Func()
>     [123]->map((_, s: string) => 0)
> enddef
> Func()
> ```
>     E1013: Argument 2: type mismatch, expected string but got number
> 
> Could we give an error earlier (i.e. at compile time) when passing
> wrong arguments to a lambda which is used by `map()`, `filter()`, ...

I looked into this, and for the specific example it's not so easy, since
this is not a list with a declared type, it may end up being a list of
strings, e.g. if there was another map in between.

We can do a better check for a declared type, thus if [123] was assigned
to a variable:

	var l = [123]
     	l->map((_, s: string) => 0)

We can also check the first argument matches the type, for a list it
must be a number and for a dictionary a string.

-- 
hundred-and-one symptoms of being an internet addict:
83. Batteries in the TV remote now last for months.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
In the case of a variable, the issue has been fixed for a list:
```vim
vim9script
def Func()
    var s = ['a', 'b', 'c']
    s->map((_, v: number) => '')
enddef
defcompile
```
    E1013: Argument 2: type mismatch, expected func(?number, ?string): string but got func(any, number): string

but not for a string:
```vim
vim9script
def Func()
    var s = 'abc'
    s->map((_, v: number) => '')
enddef
defcompile
```
    no error

We can map and filter a string since the patch [8.2.3818](https://github.com/vim/vim/releases/tag/v8.2.3818).

**Comment by brammool** [comment]
> In the case of a variable, the issue has been fixed for a list:
> ```vim
> vim9script
> def Func()
>     var s = ['a', 'b', 'c']
>     s->map((_, v: number) => '')
> enddef
> defcompile
> ```
>     E1013: Argument 2: type mismatch, expected func(?number, ?string): string but got func(any, number): string
> 
> but not for a string:
> ```vim
> vim9script
> def Func()
>     var s = 'abc'
>     s->map((_, v: number) => '')
> enddef
> defcompile
> ```
>     no error
> 
> We can map and filter a string since the patch [8.2.3818](https://github.com/vim/vim/releases/tag/v8.2.3818).

I'll check string and blob too.

I also discovered this didn't work:
	0z1234->map()

That should work, just like it does for a string:
	'abc'->map()

-- 
hundred-and-one symptoms of being an internet addict:
85. Choice between paying Compuserve bill and paying for kids education
    is a no brainer -- although a bit painful for your kids.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
I'm closing the issue because we can't do much more for `map()`.  But the issue persists for other functions which accept a lambda as argument, such as `filter()`:
```vim
vim9script
def Func()
    [123]->filter((_, s: string) => true)
enddef
defcompile
```
    no error

Or `sort()`:
```vim
vim9script
def Func()
    [12, 34]->sort((a: string, b: blob) => 0)
enddef
defcompile
```
    no error

Or `setqflist()`:
```vim
vim9script
def Func()
    setqflist([], ' ', {lines: v:oldfiles, efm: '%f', quickfixtextfunc: (info: job) => ''})
    cwindow
enddef
defcompile
```
    no error

I'll try to open separate issues later.

**Comment by brammool** [comment]
I have done filter() and sort().  We can probably do more checks at compile time, but it's quite a bit of work to implement and write tests.  Feel free to open an issue for specific functions, give examples of what should work and what should fail.
