### ISSUE TITLE
`:h E1263` is outdated

### ISSUE THREAD

**Issue by LunarWatcher** [vim/vim#9805]
## Steps to reproduce

I have a few Vim9 plugins that still rely on `file#func`. I went into this assuming this was a bug based on `:h E1263`. Invoking autoload files with # in the function names produce:

```
Error detected while processing /mnt/LinuxData/programming/vim/obscure-vim9-autoload-mcve/autoload/badautoload.vim:
line    3:
E1263: cannot use name with # in Vim9 script, use export instead
E117: Unknown function: badautoload#trigger
```

Note particularly that this happens in an autoload file. According to `:h E1263`:

> In |Vim9| script you will get error *E1263* if you use a function name with a
> "#" character when **not** in an autoload script.

This function is clearly defined in an autoload script, so this exception should apply. Based on #9724, however, it seems that this is not longer possible in Vim9 in any context. If this is the case, it seems the docs for E1263 need an update to reflect this. 

## Version of Vim

8.2.4424

**Comment by brammool** [comment]
This changed over time.  Now E1263 is given when trying to define a function with # in the name, no matter if it is in an autoload script or not.  I'll adjust the help for that.
