### ISSUE TITLE
the indentation of 'end*' works as 'end' in vimscript when 'filetype indent on'

### ISSUE THREAD

**Issue by xvim64** [vim/vim#9808]
### Steps to reproduce

vim --clean t.vim

:filetype indent on

[ t.vim ]
```
let ends = 100
if 1
    end   // <-- indented to the left automatically befor entering 's'
```

[ vim82/indent/vim.vim ]
```
setlocal indentkeys+==end,=},=else,=cat,=finall,=END,0\\,0=\"\\\ 
```

to

[ vim82/indent/vim.vim (mod) ]
```
setlocal indentkeys+==enddef,=endf,=endif,=endtry,=endw,=},=else,=cat,=finall,=END,0\\,0=\"\\\ 
```

This modification diminish the words that start with end*.

### Expected behaviour

no indentation end* variable

### Version of Vim

8.2

### Environment

Windows 10 x64

**Comment by k-takata** [comment]
`:end` (and also `:en`) is an abbreviated form of `:endif`.
Some people might expect it is automatically indented to the left when `end` is typed.

**Comment by brammool** [comment]
Although ":end" stands for "endif", I doubt anybody who cares about correct indent uses it like that.
It's not unusual to have a variable start with "end".  And we should encourage using clear commands.
Besides 'indentkeys' there is also the rule further down, which would recognize "ends" as the end of a block.
Let me change both and see how well that works.
