### ISSUE TITLE
E117: Unknown function: dist#script#DetectFiletype

### ISSUE THREAD

**Issue by filip2cz** [vim/vim#9809]
**About problem**:
When I want to use Vim, I have this error:
```
Error detected while processing /usr/share/vim/vim82/suse.vimrc[10]../usr/share/vim/vim82/syntax/syntax.vim[42]..BufRead Autocommands for "*"..script /usr/share/vim/vim82/scripts.vim:
line   30:
E117: Unknown function: dist#script#DetectFiletype
Press ENTER or type command to continue
```
When I press enter, Vim normally runs.

**Something about my OS**:
OS: GeckoLinux Rolling (based on openSUSE Tumbleweed)
platform: x86_64
kernel: 5.16.8-1-default

**Comment by brammool** [comment]
Please check the value of 'runtimepath'.
In one of the directories there should be autoload/dist/script.vim
Does it start with "vim9script" ?

**Comment by chrisbra** [comment]
also, this might be a packaging issue. Can you try with a self-compiled version from this repository instead of using your distribution package?

**Comment by sainnhe** [comment]
OpenSUSE Tumbleweed here, I can confirm that in `/usr/share/vim/vim82/autoload/dist/` directory, there is only one file `ft.vim`, but in arch linux there is also a file named `script.vim` .

This should be a packaging issue in openSUSE Tumbleweed.

**Comment by chrisbra** [comment]
okay, then please report to the OpenSuse developers. Closing here then.

**Comment by cesarizu** [comment]
Just for anyone that finds this with the same error, on openSUSE you need to install `vim-data` which contains the missing file.

**Comment by chrisbra** [comment]
wondering why it wasn't installed by default. That should have been a dependency

**Comment by MichaelSodeke** [comment]
> Just for anyone that finds this with the same error, on openSUSE you need to install `vim-data` which contains the missing file.

Thanks. This resolved the issue for me.

Take care.

**Comment by lidalve** [comment]
> Just for anyone that finds this with the same error, on openSUSE you need to install `vim-data` which contains the missing file.

Thanks,  resolved.

**Comment by Hywfred** [comment]
> Just for anyone that finds this with the same error, on openSUSE you need to install `vim-data` which contains the missing file.

Thank you verr much. I solved my problem. My machines is running SLES15-SP3.

**Comment by nodeg** [comment]
For reference: https://bugzilla.suse.com/show_bug.cgi?id=1200184
