### ISSUE TITLE
Dead code after `return`

### ISSUE THREAD

**Issue by dpelle** [vim/vim#9815]
### Steps to reproduce

File `src/evalfunc.c` in `arg_map_func()` has these lines:
```
589             if (args[0] == NULL)                                                              
590                 args[0] = &t_unknown;
591             return check_arg_type(&t_func_exp, type, context);
592 
593             where.wt_index = 2;
594             return check_type(&t_func_exp, type, TRUE, where);
```
Line 591 returns, so lines 593 and 594 are dead code.
I'm not sure what it was meant to do.

### Expected behaviour

No dead code.

### Version of Vim

8.2.4430

### Environment

N/A

**Comment by dpelle** [comment]
`git blame` indicates that the offending code in this ticket was introduced recently in patch 8.2.4425 (Feb 20, 2022).

https://github.com/vim/vim/commit/eddd4fc4f6d9d626374a73861c891f95ef999133#diff-a4bde4e6cdd803bf45433cf5966ea421ac70ddc84534709877f40751436b87e4R591

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> File `src/evalfunc.c` in `arg_map_func()` has these lines:
> ```
> 589             if (args[0] == NULL)                                                              
> 590                 args[0] = &t_unknown;
> 591             return check_arg_type(&t_func_exp, type, context);
> 592 
> 593             where.wt_index = 2;
> 594             return check_type(&t_func_exp, type, TRUE, where);
> ```
> Line 591 returns, so lines 993 and 594 are dead code.
> I'm not sure what it was meant to do.
> 
> ### Expected behaviour
> 
> No dead code.

This must be a leftover from checking the tests.  check_arg_type() also
adds a runtime type check, but that should not be needed in this case.

-- 
From "know your smileys":
 ~#:-(	I just washed my hair, and I can't do nuthin' with it.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
