### ISSUE TITLE
Segfault with EXITFREE, closed stdin, tabs, and cmdwin starting from patch 8.2.4428

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#9817]
### Steps to reproduce

1. Compile Vim with `EXITFREE`
2. Run `printf ':tabnew\rq:' | vim --clean`
3. Vim exits with SIGSGEV

### Expected behaviour

Vim exits without SIGSGEV. This is the behavior before patch 8.2.4428.

### Version of Vim

8.2.4436

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

**Comment by brammool** [comment]
I don't get a SIGSEGV:
Vim: Warning: Input is not from a terminal
Vim: Error reading input, exiting...
Vim: Finished.

Can you reproduce it using a script?

**Comment by brammool** [comment]
I can make it crash by putting those commands in a script file and using "< script".
