### ISSUE TITLE
terminwinsize stays constant after moving splits

### ISSUE THREAD

**Issue by jclsn** [vim/vim#9819]
### Steps to reproduce

1. Open a terminal buffer in horizontal split with a fixed terminwinsize, e.g. ``set termwinsize=20x0``
2. Move the terminal buffer to the left or right
3. Enter a command with a long output
4. Terminal output lines are still restricted by 20

### Expected behaviour

termwinsize should only set the size of the split and not the number of lines in the window. If the latter is absolutely necessary, the number of lines should be updated when the split window is moved.

### Version of Vim

8.2

**Comment by brammool** [comment]
I don't understand: with a horizontal split you cannot move the window left or right.
Perhaps you mean a vertical split?
Please give the exactly commands you use, starting with "vim --clean".

**Comment by jclsn** [comment]
I meant changing from a horizontal split to a vertical split.

```
vim --clean
:set termwinsize=20x0
:ter
Ctrl+w,l
```
Then just run any command that will result in many lines being printed, e.g. system update. The full window will not be used. It will stay reduced to 20 lines, although there are more available in the vertical split.

**Comment by brammool** [comment]
Well, that's what you asked for.  Perhaps you want to set 'termwinsize' to "20*0" ?

**Comment by jclsn** [comment]
Oh yeah, that is actually in the documentation. My bad. 

Thank you
