### ISSUE TITLE
vim does not handle STDIN set to /dev/null

### ISSUE THREAD

**Issue by apeschel** [vim/vim#982]
As described in this StackOverflow question:

http://superuser.com/questions/336016/invoking-vi-through-find-xargs-breaks-my-terminal-why

Invoking `vim` with STDIN set to `/dev/null` issues an error and breaks the terminal.

```
Vim: Warning: Input is not from a terminal
```

This is a common case when piping `find` to `xargs` with `vim` as the command, eg

```
find . -type f | xargs vim
```

Running this chain breaks the tty interaction in vim, and breaks the shell tty upon exit from vim.

A workaround is to run `reset` or `stty sane` upon exit from vim, but the tty still has issues while using vim. One annoying example is the backspace button not actually deleting, but inserting a backspace character.

**Comment by apeschel** [comment]
I have also discovered the `-o` flag will reopen STDIN with xargs, which also fixes the issue.

```
find . -type f -print0 | xargs -o -0 vim
```

**Comment by sebma** [comment]
@apeschel Hi `xargs -o` is not a GNU xargs option but a BSD xargs option.
Any workaround for Linux ?

> I have also discovered the `-o` flag will reopen STDIN with xargs, which also fixes the issue.
> 
> ```
> find . -type f -print0 | xargs -o -0 vim
> ```

**Comment by vim-ml** [comment]
On 2020-10-02, sebma wrote:
>     I have also discovered the -o flag will reopen STDIN with xargs, which also
>     fixes the issue.
> 
>     find . -type f -print0 | xargs -o -0 vim
> 
> @apeschel Hi xargs -o is not a GNU xargs option but a BSD xargs option.
> Any workaround for Linux ?

I use GNU parallel instead of xargs for this.  For example:

    find -type f | parallel --tty -X vim

Ubuntu has a package for parallel.  You can also find it here:

    https://www.gnu.org/software/parallel/

Regards,
Gary

**Comment by sebma** [comment]
@vim-ml I just found this command thanks to [james-mcguigan's answer on superuser](https://superuser.com/a/427881/528454) : 
`find ..... | xargs sh -c 'vim </dev/tty "$@"' whatever`
With that command you don't need to install `parallel` on the machine anymore :smile:

**Comment by chrisbra** [comment]
> @apeschel Hi xargs -o is not a GNU xargs option but a BSD xargs option.

FWIW: This has been added to GNU xargs as of https://git.savannah.gnu.org/cgit/findutils.git/commit/?id=40cd25147 (2017) 

So any recent linux distribution should have it.

**Comment by sebma** [comment]
> > @apeschel Hi xargs -o is not a GNU xargs option but a BSD xargs option.
> 
> FWIW: This has been added to GNU xargs as of https://git.savannah.gnu.org/cgit/findutils.git/commit/?id=40cd25147 (2017)
> 
> So any recent linux distribution should have it.

My `findutils` package is my Linux distrib is from 2016.

**Comment by tonymec** [comment]
2016? Four years ago? Don't you think it might perhaps be time to think, just think, of getting ready for, I don't know, an upgrade?

**Comment by chrisbra** [comment]
well Ubuntu 14.04 LTS is still maintained until around 2022 and I remember having to work with an older Cent OS release that was still available. 

Anyhow, I am currently tending to close this issue, as this thread has shown various ways to prevent  or work around closing of stdin.

**Comment by sebma** [comment]
@chrisbra Ubuntu 16.04 LTS has findutils version `4.6.0+git+20160126-2`
On Ubuntu 14.04 LTS findutils is older
