### ISSUE TITLE
cannot find script local func

### ISSUE THREAD

**Issue by Shane-XB-Qian** [vim/vim#9820]
### Steps to reproduce

```vim
function! s:watch_callback(...) abort
  let s:timer = timer_start(
        \ g:foo#update_interval,
        \ function('s:watch_callback')
        \)
endfunction
```
something script local func in one legacy vim script plugin in autoload,
then while you playing vim in some seconds later:
`E117: Unknown function: <SNR>80_watch_callback`

### Expected behaviour

no err.
not sure if you can reprocedure it (i cannot minimal case it too),
and not sure if it was a corner case after `8.2.4429`, 
there were some weird case in recent change/patches, 
e.g `with` or `without` single quote to `function('FooFunc')` vs `function(FooFunc)` was a matter?

// if it can be addressed then ok, or waiting someone else to simply it.

### Version of Vim

8.2.4436

### Environment

linux

**Comment by lacygoill** [comment]
There always had [issues](https://github.com/lacygoill/wiki/blob/master/bug/vim.md#inconsistent-rules-wrt-to-s-dropping) with script-local callback functions.  They seem to be all fixed since a recent patch.  I guess it's thanks to [8.2.4429](https://github.com/vim/vim/releases/tag/v8.2.4429).

I had a dozen snippets which gave different results; some of them gave the error you report.  All of them are working fine now.

**Comment by Shane-XB-Qian** [comment]
patch 8.2.4429 should be from the case i chatted with yegappan in one lsp plugin ticket.
but i guess it didnot or make new issue like this, notice here `s:watch_callback` the outter func name is same str in inner `function('s:watch_callback')` of `timer_start()`, maybe that's a corner case which was not noticed?

**Comment by brammool** [comment]
I tried to reproduce it with this script:
```vim
function s:watch_callback(...) abort
  if a:0 == 0
    let s:timer = timer_start(
	  \ 2000,
	  \ function('s:watch_callback')
	  \)
  else
    echomsg 'called'
  endif
endfunction

call s:watch_callback()
```

But it works fine.  Please try to come up with a reproduction script.

**Comment by Shane-XB-Qian** [comment]
that func should be in a `autoload` fs, then in `plugin` registers a init call `foo#watch()` to call that func:
```vim
function! foo#watch() abort
  let s:timer = timer_start(0, function('s:watch_callback'))
endfunction
```

perhaps can be using tpop's pathogen to test that.
// but yea, i am not sure if that's a minimal case which to be reproduce, or then should wait someone else if met and simply it.. :-(

**Comment by vim-ml** [comment]
Hi,

On Tue, Feb 22, 2022 at 5:06 AM Shane-XB-Qian ***@***.***>
wrote:

> that func should be in a autoload fs, then in plugin registers a init
> call foo#watch() to call that func:
>
> function! foo#watch() abort
>   let s:timer = timer_start(0, function('s:watch_callback'))endfunction
>
>
Where is the s:watch_callback() function defined? Is it in the plugin file
or in the
autoload file? If it is defined in the autoload file, then you cannot use
it from the
plugin file (as it is script local to the autoload file).

- Yegappan


> perhaps can be using tpop's pathogen to test that.
> // but yea, i am not sure if that's a minimal case which to be reproduce,
> or then should wait someone else if met and simply it.. :-(
>
>
>

**Comment by Shane-XB-Qian** [comment]
> Where is the s:watch_callback() function defined?

1, `s:watch_callback()` and `foo#watch()` both defined in autoload/foo.vim
2, then `call foo#watch()` in `plugin/foo.vim`


and i just do a bisect, looks patch v8.2.4429 is the cause.
// no err if with v8.2.4428

and more weird is looks it happened if vim just startup with a fs which its ft is your lsp supported (and lsp#lsp#AddServer(cfg) registerred) -_-#


-- 
shane.xb.qian

**Comment by brammool** [comment]
Hmm, maybe the bug that 8.2.4429 fixed uncovered a problem in the plugin?
Previously when using s:Function in a callback, it could call s:Function in another script. when the callback is executed.
While the intention is that s:Function is used from the script where the callback is created.
In other words: was the plugin relying on the bug that was fixed?

**Comment by Shane-XB-Qian** [comment]
once i changed foo#watch() to this:
```vim
function! foo#watch() abort
  let s:timer = timer_start(1000, function('s:watch_callback'))
endfunction
```
Note: from `0` to `1000`, seems issue is gone! -_-#
// not sure why, but looks there was vim9/legacy script compile timing conflict?!

**Comment by Shane-XB-Qian** [comment]
in vim-go: @bhcleek
```log
vim-go/autoload/go/lsp.vim|1332| <SNR>245_debug[5]
|| E700: Unknown function: s:debugasync
vim-go/autoload/go/lsp.vim|136| 298[3]
|| E714: List required
```

in siginify:
```log
vim-signify/autoload/sy/repo.vim|102| sy#repo#get_diff[29]
|| E700: Unknown function: s:callback_vim_close
```

though err happened at extra plugins and those are legacy vim script, but i think those all caused by recently vim9 `s:` change.

**Comment by bhcleek** [comment]
I can't duplicate that error with 8.2.4450. If there's something about vim-go that you think needs to change, please open a proper bug report there.

**Comment by Shane-XB-Qian** [comment]
yea, once i delayed the lsp startup after vimenter, then everything looks ok.
// seems a compile timing conflict... FYI. anyway.

**Comment by Shane-XB-Qian** [comment]
seems finally fixed after long searching...
thanks everyone!! and saving others people's time in advance.. :-)
