### ISSUE TITLE
Problem with noexpandtab virtualedit=all

### ISSUE THREAD

**Issue by Rafagd** [vim/vim#9823]
### Steps to reproduce

1. Use `:set nocompatible`, not a pure vi fan...
2. Use `:set list listchars=eol:↵,tab:>·,trail:~,extends:>,precedes:<,space:␣` to make tabs and spaces visible
3. Make sure you have expandtabs off `:set noexpandtab`, you can add your favorite tabstop, shiftwidth, autoindent, smartindent doesn't matter.
4.  Type a 4 line code, that adds one indentation level and leave one of the two internal lines blank
```
>··· is a tab, ␣ is a space, | is the cursor, ↵ is the eol
int main() {↵
>···|printf("something");↵
↵
}↵
```
5. Then move the cursor to the empty line, without actually creating it 
```
>··· is a tab, ␣ is a space, | is the cursor
int main() {↵
>···printf("something");↵
↵   |
}↵
```
6. Now just add something to the line, it will insert the line at the correct position, but it will be space-indented instead of tab-indented
```
>··· is a tab, ␣ is a space, | is the cursor
int main() {↵
>···printf("something");↵
␣␣␣␣something|↵
}↵
```

### Expected behaviour

I expected the new line would respect noexpandtab and be tab-indented
```
>··· is a tab, ␣ is a space, | is the cursor
int main() {↵
>···printf("something");↵
>···something|↵
}↵
```

### Version of Vim

8.2

### Environment

FreeBSD
$TERM=xterm-256color
bash

**Comment by brammool** [comment]
Well, this is how it always was done.  I'm not sure if this is a bug or intentional.
Users may depend on this behavior, thus I'm in doubt whether we should change this.
Also considering that I can't remember someone complaining about this, and it has been implemented a long time ago.

**Comment by Rafagd** [comment]
Is it possible to turn this into a new feature proposal for a new flag (idk, something like `:set tabsonvirtualedit` or something) or wouldn't be worth it?

For future reference, I've been adviced to `<esc>==` in case that happens in the future. Doesn't solve the problem, but hey, it's something.

**Comment by brammool** [comment]
You could use a mapping to ":retab!", which should change the spaces to tabs without other effects.
E.g. when pressing Enter or Space.

**Comment by Rafagd** [comment]
I can't ":retab!" the file, my company requires me to not retab code I'm not changing. Plus retabbing the whole file every time I press enter is a bit of a radical move. I think I'll remap something to `<esc><^><i><enter><esc><up>dd`instead.

I've tried using the `<esc>==` trick, but it didn't reindent the line if it was indented "correctly" as well. e.g. It doesn't reindent this line (`:retab!` does, but it's a bit of a nuclear bomb against a fly):
```
[bla bla bla]
>···>···line 1
>···>···line 2
>···␣␣␣␣line 3|
```

**Comment by zeertzjq** [comment]
You can try `:.,.retab`

**Comment by chrisbra** [comment]
Just use `:.retab!`

**Comment by matveyt** [comment]
Throwing my two cents, to start Insert mode on empty line press `S` or `cc`, and not "move your cursor somewhere and press i". This way a proper indentation level will be created automatically with all the tabs and spaces as needed.

**Comment by Rafagd** [comment]
Not sure if it's something in my configs, but `S` or `cc` are just changing to Insert-Mode and placing the cursor at the EOL for me, when run on a completely empty line, of course. `:.retab!` and `:.,.retab!`, both do exactly what I want, but `<esc>==` is more convenient. They don't really solve the problem, but at least they do make it less aggravating when it happens.
