### ISSUE TITLE
Can't change to default shell after set to powershell.exe

### ISSUE THREAD

**Issue by hungpham3112** [vim/vim#9831]
Recently, I'm working with shell in vim, so I decided to `set shell=C:\\Windows\System32\WindowsPowershell\v1.0\powershell.exe -ExecutionPolicy Bypass`, but after remove that from my settings, the shell still is powershell not cmd. How do I fix that. I opened `vim --clean ` and shell is cmd but I don't know how to find the bug.

**Comment by chrisbra** [comment]
Simply use:  `:let &shell='C:\windows\system32\cmd.exe'`. 

Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. Closing.

**Comment by hungpham3112** [comment]
> Simply use: `:let &shell='C:\windows\system32\cmd.exe'`.
> 
> Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. Closing.

I know that, I mean I can't change shell to default after change it to powershell.

**Comment by k-takata** [comment]
Use `:verbose set shell?` to see where it is set.

**Comment by hungpham3112** [comment]
> Use `:verbose set shell?` to see where it is set.

shell=C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass
	Last set from ~\scoop\apps\vim\current\vimrc line 1
