### ISSUE TITLE
Cannot read working directory from non-current tab

### ISSUE THREAD

**Issue by noscript** [vim/vim#9832]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

When working with multiple tab pages, it is impossible to tell if `:tcd` was used in a tab, without switching to that tab first.

**Describe the solution you'd like**
There could be `t:cwd` and `w:cwd` variables that would be synchronized with `:tcd` and `:lcd`.

**Describe alternatives you've considered**
* `getcwd(-1, <tabnr>)` returns the working directory for specific tab page but it is impossible to tell if the value is global or local.
* `:verbose pwd` can tell is the value is local or global but the command works only for the current tab. One has to switch to another tab and then parse the output from `:verbose pwd`.

**Comment by noscript** [comment]
Thank you. Couldn't figure it out myself.

**Comment by vim-ml** [comment]
Hi,

On Wed, Feb 23, 2022 at 5:24 AM Sergey Vlasov ***@***.***>
wrote:

> *Is your feature request about something that is currently impossible or
> hard to do? Please describe the problem.*
>
> When working with multiple tab pages, it is impossible to tell if :tcd
> was used in a tab, without switching to that tab first.
>
> *Describe the solution you'd like*
> There could be t:cwd and w:cwd variables that would be synchronized with
> :tcd and :lcd.
>
> *Describe alternatives you've considered*
>
>    - getcwd(-1, <tabnr>) returns the working directory for specific tab
>    page but it is impossible to tell if the value is global or local.
>    - :verbose pwd can tell is the value is local or global but the
>    command works only for the current tab. One has to switch to another tab
>    and then parse the output from :verbose pwd.
>
>
> Did you try using the haslocaldir() function? This function will return 2
if a tabpage
has a  tab-local directory.

- Yegappan

**Comment by noscript** [comment]
Yes, `haslocaldir()` solves the problem.
