### ISSUE TITLE
Wrong colors in terminal window in cmd.exe

### ISSUE THREAD

**Issue by gdupras** [vim/vim#9836]
### Steps to reproduce

1. Open the command prompt (cmd.exe)
2. `vim --clean`
3. `:hi Normal ctermbg=blue`
4. `:hi Terminal ctermbg=blue`
5. `:terminal`

The terminal window is red:

![ctermbg_blue](https://user-images.githubusercontent.com/57042631/155368597-2f4bc835-5af1-44a1-be00-9afed6c24771.png)

### Expected behaviour

The terminal window should be blue, just like the bottom window.

This bug was first reported here:

https://github.com/vim/colorschemes/issues/150

### Version of Vim

8.2.4428

### Environment

Operating system: Windows 10
Terminal: cmd

**Comment by habamax** [comment]
Also cyan is yellow and vice versa.

**Comment by gdupras** [comment]
Some more examples:

`:hi Normal ctermbg=red | hi Terminal ctermbg=red`:

![ctermbg_red](https://user-images.githubusercontent.com/57042631/155393268-3cdbf144-0c25-44fd-bf64-b32d0d0b8bbf.png)

`:hi Normal ctermbg=cyan | hi Terminal ctermbg=cyan`:

![ctermbg_cyan](https://user-images.githubusercontent.com/57042631/155393523-852854bb-d57b-4381-90ea-c6d91a630c77.png)

`:hi Normal ctermbg=green | hi Terminal ctermbg=green` (this one is correct for some reason):

![ctermbg_green](https://user-images.githubusercontent.com/57042631/155393824-ca7576e2-2674-4b00-b2df-2d4304dcc31b.png)

**Comment by brammool** [comment]
Looks fine with xterm in Linux, must be a Windows-specific problem.

**Comment by lifepillar** [comment]
The easiest fix would be to make the top green window orange.

[Please forgive me]

**Comment by habamax** [comment]
Looks like it is fixed, thank you!
