### ISSUE TITLE
Broken syntax in tex when defining custom math column type

### ISSUE THREAD

**Issue by bartbkr** [vim/vim#984]
### The issue

When defining a custom math column type, the syntax highlighting in the
rest of the document seems to break. It seems as though the syntax
highlighting assumes that the rest of the document is in math mode.
### Minimal working example

``` tex

\documentclass{article}

\newcolumntype{R}{>{$}r<{$}}

\begin{document}

This is colored as if it is in a math section, rather than the default text
color.

\end{document}
```

(As you can see, it also seems to broken in the Markdown syntax for tex).

**Comment by lacygoill** [comment]
Fixed by 6d5ad4c4118cab5fd96db157621c3aa9af368edb.
