### ISSUE TITLE
Vim9: no compile-time error for assigning value of `any` variable to other variable with more specific type

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9842]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        def Func()
            var x: any = 0
            var y: string = x
        enddef
        defcompile
    EOF
    )

No error is given.

**Expected behavior**

`E1012` is given:

    E1012: Type mismatch; expected string but got any

**Version of Vim**

8.2 Included patches: 1-4463

**Environment**

Operating system: Ubuntu 20.04.4 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: zsh 5.8

**Additional context**

At the script level, the code gives an error:
```vim
vim9script
var x: any = 0
var y: string = x
```
    E1012: Type mismatch; expected string but got number

At runtime, the code gives an error:
```vim
vim9script
def Func()
    var x: any = 0
    var y: string = x
enddef
Func()
```
    E1012: Type mismatch; expected string but got number

At compile time, if we remove the `any` type, and let type inferrence guess the type of `x` from the initialization value, an error is given:
```vim
vim9script
def Func()
    var x = 0
    var y: string = x
enddef
defcompile
```
    E1012: Type mismatch; expected string but got number

Giving an error in the first snippet would be consistent with these last 3 ones.
It will give an error no matter what at runtime anyway.

**Comment by lacygoill** [comment]
I'm not sure it's a bug.  On the lhs of an assignment, `any` means that we don't want any type checking at compile time.  But what about the rhs?  Is `any` meant to suppress type checking at compile time no matter where it's used (lhs vs rhs)?

**Comment by lacygoill** [comment]
Never mind, it might be annoying to give an error.  `any` can be useful while we're trying to find the correct types.  If we give an error, it might make the process more painful than it should be.

**Comment by brammool** [comment]
"any" often requires a runtime type check.  You should be able to see this if you use "disas Func".
Consider something like this;
```
var v: any = cond ? 'string' : 123
if cond
  # use v as a string
else
  # use v as a number
endif
```
Perhaps some day we can have static analysis of the script and be more clever.  Don't expect that soon though.
