### ISSUE TITLE
git regression: keywordprg is not set to git show anymore

### ISSUE THREAD

**Issue by jirislaby** [vim/vim#9845]
### Steps to reproduce

1. Open vim in a git directory
2. Paste a SHA (or use `git rebase -i @^^`)
3. Press shift-k while having cursor on a SHA.

### Expected behaviour

`git show` is run with the above SHA. But `man` is run instead. This is apparently a result of https://github.com/vim/vim/commit/2f0936cb9a2eb026acac03e6a8fd0b2a5d97508b#diff-e92ab7d5e3bfe3e88cfb645f5ce7d4e05cc4f6495d72e8458e97f95c229fdb7e

Why was the file removed?

### Version of Vim

8.2.4375

### Environment

- openSUSE Tumbleweed
- xterm
- xterm-256color
- bash

**Comment by jirislaby** [comment]
This is coming from https://github.com/tpope/vim-git/commit/6ee5e1f20039f90b73fc4c5ffd972498c4cf7141 . @tpope, why do you think there is no good idea there? Is there any replacement now?

**Comment by chrisbra** [comment]
this comes from https://github.com/vim/vim/pull/9477 I'd suggest to discuss this with @tpope  at his upstream repo: https://github.com/tpope/vim-git

**Comment by tpope** [comment]
This was never an officially documented feature, just an ill-conceived idea that leaked out of `ftplugin/git.vim`. If you want to bring it back, you can add it yourself in `after/ftplugin/gitrebase.vim`:

```vim
setlocal keywordprg=git\ show
```

**Comment by ddiss** [comment]
> This was never an officially documented feature, just an ill-conceived idea that leaked out of `ftplugin/git.vim`. If you want to bring it back, you can add it yourself in `after/ftplugin/gitrebase.vim`:
> 
> ```viml
> setlocal keywordprg=git\ show
> ```

Thanks for the workaround. I'm also a heavy user of this functionality (it makes `git rebase -i` *really* nice) so had hoped to see the regression fixed, but I guess I'll have to live with the local modification.

**Comment by chrisbra** [comment]
closing then.

**Comment by jirislaby** [comment]
@ddiss: https://build.opensuse.org/request/show/960651
