### ISSUE TITLE
Align right current line number when `set nu rnu`

### ISSUE THREAD

**Issue by habamax** [vim/vim#9847]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

It would be nice if there were a way to have current line number aligned right when `set number relativenumber` is active:

![image](https://user-images.githubusercontent.com/234774/155730941-ddd69c3c-25c9-47eb-b998-3a501c28e507.png)

**Describe the solution you'd like**
A setting, like `set relativenumberopt=right` that aligns current relativenumber line right.

**Comment by chrisbra** [comment]
I think this is a duplicate of #1875, #680 and possibly #1368

**Comment by habamax** [comment]
True, didn't search it properly

**Comment by chrisbra** [comment]
I think the reason for the left-alignment was, that it would look confusing for a file with 3 lines:
```
  1  cursorline
  1  1 line before the cursor
  2  2nd line after cursor
```

Which looks strange, so we made the decision to left align it to make it stand out more. 

But now we have highlighting groups `LineNr`, `LineNrAbove` and `LineNrBelow` so perhaps it's time to revisit this decision ?

**Comment by habamax** [comment]
Do you think about option or change of the current default alignment to what `set rnu` has?

![image](https://user-images.githubusercontent.com/234774/155733453-dac98156-bb2a-491e-99b3-4fd3942f11e7.png)

**Comment by chrisbra** [comment]
Personally, I don't want another option for such a small change. But this would be  a backwards-incompatible change, so not sure

**Comment by habamax** [comment]
So I have removed a single line:

https://github.com/vim/vim/blob/4d56b971cbae01cc454eb09713326224993e38ed/src/drawscreen.c#L1227

and it "works":

![image](https://user-images.githubusercontent.com/234774/155736938-76aac441-048f-4749-8faa-6904ebc735a1.png)

**Comment by vim-ml** [comment]
On Fr, 25 Feb 2022, Maxim Kim wrote:

> So I have removed a single line:
> 
> https://github.com/vim/vim/blob/4d56b971cbae01cc454eb09713326224993e38ed/src/drawscreen.c#L1227

There should be a similar line in drawline.c which you also need to 
change: 

https://github.com/vim/vim/blob/master/src/drawline.c#L1150


Best,
Chris
-- 
Die Menge glaubt, alles zu wissen und alles zu begreifen. Je dümmer
sie ist, um so weiter ist der Horizont, den sie zu haben vorgibt.
		-- Anton Pawlowitsch Tschechow

**Comment by habamax** [comment]
> There should be a similar line in drawline.c which you also need to
change:

Yes, indeed:
![image](https://user-images.githubusercontent.com/234774/155740487-05aadfe7-273e-4c2c-a730-4dda0a9e1107.png)


Do you think it makes sense to PR it?

**Comment by brammool** [comment]
When not using clearly different highlighting, near the start of the file, with wrapping lines, it becomes very hard to spot the line number.  Maybe it doesn't look nice left aligned, but it is functional.

**Comment by habamax** [comment]
> When not using clearly different highlighting, near the start of the file, with wrapping lines, it becomes very hard to spot the line number. Maybe it doesn't look nice left aligned, but it is functional.

That is true. And an option is not an option here?

**Comment by brammool** [comment]
> > When not using clearly different highlighting, near the start of the
> > file, with wrapping lines, it becomes very hard to spot the line
> > number. Maybe it doesn't look nice left aligned, but it is functional.
> 
> That is true. And an option is not an option here?

'rightaligncursorlinenumber' ?

-- 
hundred-and-one symptoms of being an internet addict:
99. The hum of a cooling fan and the click of keys is comforting to you.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by habamax** [comment]
> 'rightaligncursorlinenumber' ?

Indeed, it doesn't look and sound very good.

I can live without it.

**Comment by felixakiragreen** [comment]
it's not complete! I can't live like this.
