### ISSUE TITLE
seg fault when set fuzzy

### ISSUE THREAD

**Issue by Shane-XB-Qian** [vim/vim#9851]
### Steps to reproduce

vim --clean
set nowildmenu
set wildoptions=fuzzy
typing `:cnoremap <expr> <esc>` then issue a `<tab>`
seg fault.

### Expected behaviour

no seg fault or no err.

### Version of Vim

8.2.4476

### Environment

linux

**Comment by brammool** [comment]
I made a quick fix.  I expect Yegappan to make a proper one.  Oh wait, after reloading I already see it.

**Comment by Shane-XB-Qian** [comment]
yes, fixed. thx. :-)
