### ISSUE TITLE
Unable to enable focus tracking for terminals where `use_xterm_like_mouse` returns false

### ISSUE THREAD

**Issue by bcat** [vim/vim#9859]
### Steps to reproduce

1. Use the [hterm terminal emulator](https://chromium.googlesource.com/apps/libapps/+/HEAD/hterm) (part of Chrome OS's Secure Shell extension).
2. Set `TERM=hterm-256color` (added to the terminfo database as of ncurses 6.3) instead of pretending to be XTerm.
3. Add the following to `~/.vimrc`:
```
let &t_fe = "\e[?1004h"
let &t_fd = "\e[?1004l"
execute "set <FocusGained>=\e[I"
execute "set <FocusLost>=\e[O"
autocmd FocusGained * echo 'FocusIn'
autocmd FocusLost * echo 'FocusOut'
```
4. Run Vim and cause it to gain & lose focus.

### Expected behaviour

Expected behavior: When focus is gained and lost, "FocusIn" and "FocusOut" messages are printed.

Actual behavior: No such messages are printed because the events never fire.

It appears that regardless of whether or not `t_fe` is set, [Vim only attempts to enable focus tracking if `focus_mode` is set internally](https://github.com/vim/vim/blob/afd4ae35d66b2e7732eceb5ad9f6b4ece6b7c64c/src/term.c#L3635-L3637). And [`focus_mode` is only set if `use_xterm_like_mouse` returns true](https://github.com/vim/vim/blob/afd4ae35d66b2e7732eceb5ad9f6b4ece6b7c64c/src/term.c#L2050-L2068).

As far as I can tell, this means that even if the user configures the relevant termcap extensions in their `~/.vimrc`, focus tracking will only work for the hardcoded list of terminals that Vim thinks support XTerm-style mouse reporting. For actual mouse reporting, you can always set `ttymouse` manually, but there doesn't appear to be an equivalent for focus tracking.

It would be really nice to be able to enable focus reporting whenever `ttymouse` was `xterm`, `xterm2`, or `sgr`, regardless of what Vim thought at compile time. (Or perhaps this should be entirely independent of mouse reporting and depend entirely on the setting of `t_fe`?)

### Version of Vim

8.2.3995

### Environment

Operating system: gLinux Rodete (Debian rolling release)
Terminal: Secure Shell 0.43
Value of $TERM: hterm-256color
Shell: Bash 5.1.8

**Comment by brammool** [comment]
Interestingly, the "focus_mdoe" flag is set for xterm, but never reset.
Can you verify that setting 'term' to "xterm" first makes it work?

I actually see no point for the "focus_mode" flag.  If we remove it, doesn't everything just work?

**Comment by bcat** [comment]
Yes, precisely, if I run `set term=xterm` when running Vim inside hterm, then the focus autocmds work just fine. It's purely a limitation of not supporting focus at all when `term=hterm-256color`.

But yes, I can't tell what additional value `focus_mode` adds vs. simply checking the presence/absence of the relevant termap entries. :)
