### ISSUE TITLE
no error for setting option with invalid value when using `:let` instead of `:set`

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9864]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE +'let &commentstring = "invalid"'

No error is given, even though the value is invalid; it should contain a `%s` item.

**Expected behavior**

An error is given so that we know that something went wrong, and can fix the issue immediately.

**Version of Vim**

8.2 Included patches: 1-4485

**Environment**

Operating system: Ubuntu 20.04.4 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: zsh 5.8

**Additional context**

With `:set`, an error is correctly given:

    vim -Nu NONE +'set commentstring=invalid'
    E537: 'commentstring' must be empty or contain %s: commentstring=invalid

**Comment by brammool** [comment]
It looks like this is a long existing problem: When assigning an invalid value to an option with :let, then the original value is kept, and no error is given.  It's easy to fix, but I wonder what mistakes this is going to uncover.
