### ISSUE TITLE
Vim9: not easy to test output of `getenv()`

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9866]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE +'vim9cmd echo getenv("does_not_exist") == v:null'

`true` is echo'ed.

Run this other shell command:

    vim -Nu NONE +'vim9cmd echo getenv("HOME") == v:null'

An error is given:

    E1072: Cannot compare string with special

**Expected behavior**

Not sure, but the current situation makes it difficult to write readable code when we have to handle the output of a function which can return different types of values.  Like here, `getenv()` can return a string or a special (`v:null`).

Could we make an exception, and accept a comparison between a string and `v:null`, when one of the operands is a function which we know can return `v:null`?

---

Alternatively, could we introduce a new comparison operator (`===`?) which could compare any types of operands?

This way, we could refactor this line:

    vim9cmd echo getenv('HOME') == v:null
                                ^^

Into this line:

    vim9cmd echo getenv('HOME') === v:null
                                ^^^

---

Or we could introduce a new function `getenvstr()` which would always return a string; never `v:null`.
I think we had a similar issue with `getchar()`, which can return a number or a string.  To fix it, we introduced `getcharstr()` in patch [8.2.2957](https://github.com/vim/vim/releases/tag/v8.2.2957):

   > Yeah, that getchar() sometimes returns a number and sometimes a string
   > doesn't agree with type checking.
   >
   > How about adding getcharstr(), which always returns a string?  An empty
   > string if no character is available.

[source](https://github.com/vim/vim/issues/8343#issuecomment-856009496)

**Version of Vim**

8.2 Included patches: 1-4485

**Environment**

Operating system: Ubuntu 20.04.4 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: zsh 5.8

**Additional context**

Same issue with `term_getjob()`.  The latter can return a job or a special.
This can make a refactoring more difficult than it should be.  For example, here is some code from [`$VIMRUNTIME/pack/dist/opt/termdebug/plugin/termdebug.vim`](https://github.com/vim/vim/blob/3e7637bd266da43c9158f0e1cfe3f7f7843d7147/runtime/pack/dist/opt/termdebug/plugin/termdebug.vim#L195):

    if gdbproc == v:null || job_status(gdbproc) !=# 'run'

To convert this command in Vim9 script, we need to write:

    if gdbproc->typename() == 'special' && gdbproc == null || job_status(gdbproc) != 'run'

This is more verbose and less readable than the original line.

**Comment by brammool** [comment]
The simplest is to use the falsy operator:  ```echo (getenv("HOME") ?? '') == ''```
That doesn't work when you actually want to check for a null value, not an empty string.
I suppose we could allow for comparing v:null to anything.

**Comment by lacygoill** [comment]
> The simplest is to use the falsy operator: echo (getenv("HOME") ?? '') == ''

That doesn't look too bad.  Unfortunately, it doesn't work for `term_getjob()`.  While there is such a thing as an empty string, I can't think of an equivalent value for a job.

This causes another issue.  For example, in the killersheep plugin, the variable `s:music_job` is `:unlet`.  But we cannot unlet a script-local variable in Vim9 script.  What's the alternative?  If `s:music_job` was a number, we could reset it to 0; but which value should we use to reset a job variable? Neither `v:none` nor `v:null` work:
```vim
vim9script
var name: job = v:none
```
    E1012: Type mismatch; expected job but got special
```vim
vim9script
var name: job = v:null
```
    E1012: Type mismatch; expected job but got special

**Comment by brammool** [comment]
> > The simplest is to use the falsy operator: echo (getenv("HOME") ?? '') == ''
> 
> That doesn't look too bad.  Unfortunately, it doesn't work for
> `term_getjob()`.  While there is such a thing as an empty string, I
> can't think of an equivalent value for a job.

Comparing with v:null should work now.

> This causes another issue.  For example, in the killersheep plugin,
> the variable `s:music_job` is `:unlet`.  But we cannot unlet a
> script-local variable in Vim9 script.  What's the alternative?  If
> `s:music_job` was a number, we could reset it to 0; but which value
> should we use to reset a job variable? Neither `v:none` nor `v:null`
> work:
> ```vim
> vim9script
> var name: job = v:none
> ```
>     E1012: Type mismatch; expected job but got special
> ```vim
> vim9script
> var name: job = v:null
> ```
>     E1012: Type mismatch; expected job but got special

Assigning v:null to a job or channel could be made to work.  It can also
work for a list or dict.  But how about a number or bool?  That should
fail.  Thus you need to know the type, unlike with using :unlet.

Since we cannot use :unlet, but we do want to clear the value, it should
be more straightforward and easier to understand if we have a way to
clear a variable.  Then the type doesn't matter.

We can use ":clear varname".  Currently the ":clearjumps" command
exists, but it doesn't take an argument.  Thus we could use it.

If that is too weird, we could use :reset.  But that's not a very good
name.  Perhaps there is a better name?

-- 
The coffee just wasn't strong enough to defend itself -- Tom Waits

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> Assigning v:null to a job or channel could be made to work.

I think that would be enough to fix the issue.

> Since we cannot use :unlet, but we do want to clear the value, it should
> be more straightforward and easier to understand if we have a way to
> clear a variable.

Not sure it would be a good idea to introduce such a command considering that Vim9 tries to be less weird than other existing languages.  For example, is there such a concept as clearing a variable in TypeScript?

> If that is too weird, we could use :reset.  But that's not a very good
> name.  Perhaps there is a better name?

`:clear` sounds indeed better than `:reset`.  I can't think of a better name right now.

**Comment by lacygoill** [comment]
> I can't think of a better name right now.

Or maybe `:empty`, or `:reinit` (short for reinitializing)...

**Comment by brammool** [comment]
True, an assignment is more similar to how this works in other languages.  Also, what would happen if we clear a variable of type "any"?
It would still be preferred to assign an empty list, empty dict, empty string, zero, etc.  Assigning v:null can be made possible for consistency, as in going back to a variable that is declared but doesn't have a value.

**Comment by lacygoill** [comment]
It would also be useful to allow `null` to be assigned to a funcref variable:

    var f: func = null

For the same reason as for jobs and channels.  But also for when we declare an optional argument in a function's header:

    def Func(f: func = ???)
                       ^^^

Currently, there is no "empty" value that we can assign to the optional `f` argument.  We have to write something like `function('tr')` which looks awkward:

    def Func(f: func = function('tr'))
                       ^------------^

`null` would be easier to read and write:

    def Func(f: func = null)
                       ^--^

**Comment by lacygoill** [comment]
If we go that route, it might make sense to not give an error here:

    var d: dict<func> = {a: function('tr'), b: null}
    E1012: Type mismatch; expected dict<func(...): unknown> but got dict<any>

Even though the `b` key is mapped to `null` and not to a funcref.

**Comment by lacygoill** [comment]
Not sure whether it's working as intended, but `getenv('not_set')` matches any type of null value:
```vim
vim9script
for X in [
    null_blob,
    null_channel,
    null_dict,
    null_function,
    null_job,
    null_list,
    null_partial,
    null_string,
]
    echo getenv('not_set') == X
endfor
```
    true
    true
    true
    true
    true
    true
    true
    true

Since `getenv()` is meant to return a string (when the environment variable is set), I would have expected `true` to be given only for `null_string`; not for `null_blob`, `null_channel`, ...
