### ISSUE TITLE
Indentation missing for vimscript functions defined with `function!`

### ISSUE THREAD

**Issue by telemachus** [vim/vim#9868]
### Steps to reproduce

1. Open a vimscript file. Enter `function! Foo()` and then a newline.
2. The result is no indentation.
3. Compare `function Foo()` and then a newline.

(You can see the same thing if you try to reindent functions defined with `function!` using visual select and `=`.)

### Expected behaviour

I expect there to be indentation for functions that begin with `function!` as well as those that begin with `function`.

### Version of Vim

8.2.4485 (by report in IRC, 8.2.3455 still works)

### Environment

macOS (BigSur and Monterey)
iTerm2
$TERM = xterm-256color
bash 5.1.16

The change seems to be [here, in a recent commit](https://github.com/vim/vim/commit/c51cf0329809c7ae946c59d6f56699227efc9d1b#diff-48cf28a80003168943d20d7d40a2454ff6980019c84a3e4ac9cb7e819da22876R108).

**Comment by brammool** [comment]
I see the problem, I'll fix it.
