### ISSUE TITLE
Vim9: should we disallow some obsolete Ex commands?

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9870]
From right above [`:help :popup`](https://vimhelp.org/gui.txt.html#%3Apopup):

    This command is for backwards compatibility, using it is discouraged, because
    it behaves in a strange way.

I guess it still works in Vim9 script:
```vim
vim9script
popup
```
    E337: Menu not found - check menu names

If it didn't work, Vim would probably give a similar error as for `:x`:

    E1100: Command not supported in Vim9 script (missing :var?): x

Since the help discourages its use, maybe it should be completely disallowed in Vim9.

---

From [`:help :helpfind`](https://vimhelp.org/helphelp.txt.html#%3Ahelpfind):

                            *:helpfind* *:helpf*
    :helpf[ind]             Like |:help|, but use a dialog to enter the argument.
                            Only for backwards compatibility.  It now executes the
                            ToolBar.FindHelp menu entry instead of using a builtin
                            dialog.  {only when compiled with |+GUI_GTK|}

The help mentions "Only for backwards compatibility".  Not sure if there is a better alternative.

---

From [`:help :Print`](https://vimhelp.org/various.txt.html#%3APrint):

                                                            *:P* *:Print*
    :[range]P[rint] [count] [flags]
                            Just as ":print".  Was apparently added to Vi for
                            people that keep the shift key pressed too long...
                            Note: A user command can overrule this command.
                            See |ex-flags| for [flags].

`:Print` is weird.  Most builtin commands start with a lowercase character, and `:print` is an existing alternative.

---

From [`:help :winsize`](https://vimhelp.org/gui.txt.html#%3Awinsize):

    :win[size] {width} {height}
                    Set the window height to {width} by {height} characters.
                    Obsolete, use ":set lines=11 columns=22".

The `:winsize` Ex command is obsolete.  We could disallow executing it in Vim9.  Instead, we can set the `'lines'` and `'columns'` options.

---

From [`:help :mode`](https://vimhelp.org/term.txt.html#%3Amode):

    Without argument this only detects the screen size and redraws the screen.
    [mode] was used on MS-DOS, but it doesn't work anymore.

Also from [`:help Q_vc`](https://vimhelp.org/quickref.txt.html#Q_vc):

    |:mode|         :mode N         set screen mode to N (obsolete)

It seems `:mode` is useless nowadays.  But no error is given if we execute it in Vim9:
```vim
vim9script
mode
```
    no error

Should we give one?

**Comment by brammool** [comment]
The :popup command works: ":popup File".  It may not be useful, but disallowing it only in Vim9 script doesn't really help.
Same for ":helpfind".

Disallowing ":Print" makes sense, currently there is a confusing rule how a user command can replace it.

The "obsolete" remark for ":winsize" is a bit too strong worded.  I don't see a reason to remove this command.

We can remove :mode.  Currently it's silently skipped, which may hide a mistake.
Then we would get an "unknown command" error.
