### ISSUE TITLE
Vim9: should we disallow some obsolete options and options values?

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9871]
From [`:help i_backspacing`](https://vimhelp.org/insert.txt.html#i_backspacing):

    For backwards compatibility the values "0", "1" and "2" are also allowed, see |'backspace'|.

First, this is not documented but `3` is also allowed.

Second, it still works in Vim9 script:
```vim
vim9script
set backspace=3
```
    no error

Third, instead of these magic numbers, there are much more readable alternative documented at [`:help 'backspace'`](https://vimhelp.org/options.txt.html#%27backspace%27):

    0   same as ":set backspace=" (Vi compatible)
    1   same as ":set backspace=indent,eol"
    2   same as ":set backspace=indent,eol,start"
    3   same as ":set backspace=indent,eol,nostop"

Should we disallow setting `'backspace'` to a number, and enforce the human-readable values instead?

---

From [`:help 'backupdir'`](https://vimhelp.org/options.txt.html#%27backupdir%27):

    <       - For backwards compatibility with Vim version 3.0 a '>' at the start
              of the option is removed.

[Version 3.0](https://github.com/vim/vim-history/tree/v3.0) is 28 years old.  Do we need to remain compatible with it?  Not sure what was the rationale back then, but it seems weird to remove `<` at the start of the option.  Why only at the start?  And why only `<`?

BTW, the same removal occurs when setting [`'directory'`](https://vimhelp.org/options.txt.html#%27directory%27).

---

From [`:help 'textmode'`](https://vimhelp.org/options.txt.html#%27textmode%27):

    This option is obsolete.  Use 'fileformat'.

It still seems to work in Vim9:
```vim
vim9script
set textmode
```
    no error

At least, no error is given.  Since it's obsolete, should we give an error?

Same thing with [`:help 'textauto'`](https://vimhelp.org/options.txt.html#%27textauto%27):
```vim
vim9script
set textauto
```
    no error

---

From [`:help 'langnoremap'`](https://vimhelp.org/options.txt.html#%27langnoremap%27)

                            *'langnoremap'* *'lnr'* *'nolangnoremap'* *'nolnr'*
    'langnoremap' 'lnr'     boolean (default off, set in |defaults.vim|)
                            global
                            {only available when compiled with the |+langmap|
                            feature}
            This is just like 'langremap' but with the value inverted.  It only
            exists for backwards compatibility.  When setting 'langremap' then
            'langnoremap' is set to the inverted value, and the other way around.

This is confusing, and inconsistent with other options.  For example, there is no `'autonoread'` option, even though `'autoread'` is a boolean option just like `'langremap'`.

Besides, it lets us write unreadable code.  It's easier to read this:
```vim
vim9script
set langremap
```
Than this:
```vim
vim9script
set nolangnoremap
```
Maybe it should be disallowed to set the option in Vim9.

---

From [`:help 'path'`](https://vimhelp.org/options.txt.html#%27path%27):

    <       - Spaces can also be used to separate directory names (for backwards
              compatibility with version 3.0).  To have a space in a directory
              name, precede it with an extra backslash, and escape the space: >
                    :set path=.,/dir/with\\\ space

Having to write 3 backslashes instead of 1 in front of a space is confusing and inconsistent with other special characters (like the comma).  If the only reason is to be compatible with 3.0, maybe a single backslash should be allowed in Vim9.

---

From [`:help 'weirdinvert'`](https://vimhelp.org/options.txt.html#%27weirdinvert%27):

    This option has the same effect as the 't_xs' terminal option.
    It is provided for backwards compatibility with version 4.x.

[Version 4.0](https://github.com/vim/vim-history/tree/v3.0) is 26 years old.  Do we need to remain compatible with it?  As documented, `'t_xs'` is an alternative.

---

From [`:help dos-colors`](https://vimhelp.org/os_dos.txt.html#dos-colors):

    A DOS console does not support attributes like bold and underlining.  You can
    set the color used in five modes with nine terminal options.  Note that this
    is not necessary since you can set the color directly with the ":highlight"
    command; these options are for backward compatibility with older Vim versions.

Do we need to support these options in Vim9?

---

From [`:help efm-ignore`](https://vimhelp.org/quickfix.txt.html#efm-ignore):

    The scanf()-like "%*[]" notation is supported for backward-compatibility
    with previous versions of Vim.  However, it is also possible to specify
    (nearly) any Vim supported regular expression in format strings.

Should we disallow the `%*[]` syntax when setting `'errorformat'`?

---

From [`:help hebrew`](https://vimhelp.org/hebrew.txt.html#hebrew):

    NOTE: these three ('hkmap', 'hkmapp' and 'aleph') are obsolete.  You should
          use ":set keymap=hebrewp" instead.

The `'hkmap'`, `'hkmapp'` and `'aleph'` are obsolete.  We could disallow setting them in Vim9, and enforce setting the `'keymap'` option to `hebrewp` instead.

---

From [`:help encoding-values`](https://vimhelp.org/mbyte.txt.html#encoding-values):

    1   ansi	same as latin1 (obsolete, for backward compatibility)

In Vim9, we could disallow setting the `'encoding'` option to `ansi`, and enforce `latin1` instead.

---

From [`:help 'altkeymap'`](https://vimhelp.org/options.txt.html#%27altkeymap%27):

    This option was for using Farsi, which has been removed.  See |farsi.txt|.

Also, from [`:help option-list`](https://vimhelp.org/quickref.txt.html#option-list):

    'altkeymap'	  'akm'	    obsolete option for Farsi

The `'altkeymap'` option is obsolete.  We could give an error if it's set in Vim9.

Same thing for the `'fkmap'` option, for the same reason.

**Comment by tonymec** [comment]
`'altkeymap'` already has been removed:
			{only available when compiled with the |+farsi|
			feature}
Nowadays, it is not possible to compile with `+farsi` anymore.

**Comment by brammool** [comment]
In my opinion, having the value of an option or the allowed values depend on in what kind of script they are set in is illogical.  There is a strong connection between the value and the option.  There is not a strong relation with the type of script.  E.g. part of the users setup could be in legacy script, some part may be in Vim9 script.  Allowing different options and option values would be confusing.

**Comment by lacygoill** [comment]
> In my opinion, having the value of an option or the allowed values depend on in what kind of script they are set in is illogical. There is a strong connection between the value and the option. There is not a strong relation with the type of script. E.g. part of the users setup could be in legacy script, some part may be in Vim9 script. Allowing different options and option values would be confusing.

Fair enough.  Closing the issue.
