### ISSUE TITLE
Vim9: should we disallow various obsolete syntaxes?

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9872]
From [`:help :autocmd`](https://vimhelp.org/autocmd.txt.html#%3Aautocmd):

    See |autocmd-nested| for [++nested].  "nested"
    (without the ++) can also be used, for backwards
    compatibility.

In Vim9, maybe we should disallow the `nested` argument and enforce `++nested` instead.  The latter is more consistent with `++once` (the latter can only work with the `++` prefix).

---

From [`:help :s_r`](https://vimhelp.org/change.txt.html#%3As_r):

    For compatibility with Vi these two exceptions are allowed:
    "\/{string}/" and "\?{string}?" do the same as "//{string}/r".
    "\&{string}&" does the same as "//{string}/".

These weird syntaxes still work in Vim9 script:
```vim
vim9script
['pat', 'string']->setline(1)
:/pat
:s\/string/
```
```vim
vim9script
['pat', 'string']->setline(1)
:/pat
:s\?string?
```
```vim
vim9script
['pat', 'string']->setline(1)
:/pat
:s\&string&
```
But `:s//string/r` and `:s//string/` seem more readable.

---

From [`:help extension-removal`](https://vimhelp.org/cmdline.txt.html#extension-removal):

    If a "<" is appended to "%", "#", "#n" or "CTRL-V p" the extension of the file
    name is removed (everything after and including the last '.' in the file
    name).  This is included for backwards compatibility with version 3.0, the
    ":r" form is preferred.

The `<` suffix still work in Vim9 script:
```vim
vim9script
silent edit /tmp/file.txt
echomsg expand('%<')
```

But `%:r` seems more readable than `%<`, and more consistent with other filename modifiers which are usually introduced by a colon.

---

From [`:help map_space_in_rhs`](https://vimhelp.org/map.txt.html#map_space_in_rhs):

    If you want a {rhs} that starts with a space, use "<Space>".  To be fully Vi
    compatible (but unreadable) don't use the |<>| notation, precede {rhs} with a
    single CTRL-V (you have to type CTRL-V two times).

The help says that this is unreadable, and `<Space>` is an alternative, so maybe it should no longer be supported in Vim9.

---

From [`:help map_bar`](https://vimhelp.org/map.txt.html#map_bar):

    When 'b' is present in 'cpoptions', "\|" will be recognized as a mapping
    ending in a '\' and then another command.  This is Vi compatible, but
    illogical when compared to other commands.

The help says that this is illogical compared to other commands.  Should it be disallowed in Vim9?

---

From [`:help modeline`](https://vimhelp.org/options.txt.html#modeline):

    There is one exception: "vi:" and "vim:" can also be at the start of the line
    (for compatibility with version 3.0).

[Version 3.0](https://github.com/vim/vim-history/tree/v3.0) is 28 years old.  Do we need to remain compatible with it?

---

From [`:help mac-darwin-feature`](https://vimhelp.org/os_mac.txt.html#mac-darwin-feature):

    For backward compatibility, you can still use `macunix` instead of `osxdarwin`.

Should we enforce `osxdarwin` in Vim9?

---

From [`:help E486`](https://vimhelp.org/pattern.txt.html#E486):

    Note that for the |:global| command this behaves like a normal message, for Vi compatibility.

I've always found weird that a "Pattern not found" error was highlighted and numbered (`E486`) for `:substitute`, but not for `:global`.  Should we make `:global` behave like `:substitute`?

---

From [`:help syntax-loading`](https://vimhelp.org/syntax.txt.html#syntax-loading):

    |   +-  Source the user's optional file, from the |mysyntaxfile| variable.
    |       This is for backwards compatibility with Vim 5.x only. *synload-2*

[Version 5.0](https://github.com/vim/vim-history/tree/v5.0) is 24 years old.  Do we need to remain compatible with it and still support this `mysyntaxfile` variable even in Vim9?

Same question about the `myfiletype` variable documented shortly afterward:

    |   +-  Source the user's optional file, from the *myfiletypefile*
    |   |   variable.  This is for backwards compatibility with Vim 5.x only.
    |   |   *synload-4*

And same question about the `myscriptsfile` variable:

    |   +-  Source the user's optional file, from the *myscriptsfile*
    |   |   variable.  This is for backwards compatibility with Vim 5.x only.

---

From [`:help :syn-lc`](https://vimhelp.org/syntax.txt.html#%3Asyn-lc):

    Note: This is an obsolete feature, only included for backwards compatibility
    with previous Vim versions.  It's now recommended to use the |/\@<=| construct
    in the pattern.

`\@<=` is more readable than this `lc` argument.  And contrary to the latter, it can be used in any regex; not just if it's passed as an argument of a `:syntax` command.  I think that when 2 syntaxes serve a similar purpose, only the more powerful one should be preserved (i.e. the one which can handle the most cases).  Here, `\@<=` is more powerful.

Keeping `lc` can only bring confusion in the reader's mind.  Removing it makes the language easier to read and understand.

---

From [`:help emacs-tags`](https://vimhelp.org/tagsrch.txt.html#emacs-tags):

                                            *emacs-tags* *emacs_tags* *E430*
    Emacs style tag files are only supported if Vim was compiled with the
    |+emacs_tags| feature enabled.  Sorry, there is no explanation about Emacs tag
    files here, it is only supported for backwards compatibility :-).

The help doesn't even explain what is the syntax of lines inside an emacs tag file.  Do we need to support such files in Vim9?

---

From [`:help :redir`](https://vimhelp.org/various.txt.html#%3Aredir):

    :redi[r] @+>            Redirect messages to the selection or clipboard. For
                            backward compatibility, the ">" after the register
                            name can be omitted. See |quotestar| and |quoteplus|.

It seems that `>` is currently optional for all registers; not just the clipboard.
Should we enforce it in Vim9?  It's probably inspired by the shell `>` redirection operator.  It would be more consistent with `@+>>` where the redirection suffix is not optional.

---

From [`:help changed-5.2`](https://vimhelp.org/version5.txt.html#changed-5%2E2):

    Renamed functions:
                    buffer_exists()    -> bufexists()
                    buffer_name()      -> bufname()
                    buffer_number()    -> bufnr()
                    file_readable()    -> filereadable()
                    highlight_exists() -> hlexists()
                    highlightID()      -> hlID()
                    last_buffer_nr()   -> bufnr("$")

[5.2](https://github.com/vim/vim-history/tree/v5.2) is 24 years old.  Maybe we could give errors when those old function names are used, to enforce the new ones.

**Comment by matveyt** [comment]
My two cents,

1. `mysyntaxfile` is a useful hook to catch Syntax event. Current implementation of synload.vim is "non-friendly", i.e. it does `au! Syntax *`, so it becomes impossible for other plugins to inject into all syntaxes at once, e.g. indentation guides and such. mysyntaxfile is a good way to overcome this limitation, imo.
2. `redir` looks obsolete to me. Maybe we could remove it from vim9script at all?

**Comment by tonymec** [comment]
@matveyt : the `:redir` command is not obsolete AFAIK, and I use it a lot. What is optional is adding a > after a register name, when redirecting to a register while erasing any previous value in that register, and even that may be useful.

**Comment by matveyt** [comment]
@tonymec What's good in `:redir` compared to `execute()`?

**Comment by lacygoill** [comment]
> All these are not very well founded reasons, much more opinions and preferences.

Understood, closing the issue then.
