### ISSUE TITLE
the background highlight from scrollbar from popupmenu messed with near multipl-char-space

### ISSUE THREAD

**Issue by Shane-XB-Qian** [vim/vim#9874]
### Steps to reproduce

![image](https://user-images.githubusercontent.com/13550529/156329927-f08794ac-84ec-4b28-a448-e0dd5a5760c2.png)

pls check the screen-cut above.

### Expected behaviour

no overlap.

### Version of Vim

8.2.4488

### Environment

linux

**Comment by Shane-XB-Qian** [comment]
1. `set lines=18`
2. copy following txt into 'foo.txt'
```txt
a
            啊啊啊
             哦哦哦
              呃呃呃

aa1aa
aa2aa
aa3aa
aa4aa
aa5aa
aa6aa
aa7aa
aa8aa
aa9aa
aa10aa
aa11aa
aa12aa
aa13aa
aa14aa
aa15aa
aa16aa
aa17aa
aa18aa
aa19aa
aa20aa
aa21aa
aa22aa
```
3. issue `<c-n>` after letter `a` in the first line.
4. check the popup menu scrollbar -there is a 'overlap'.

![image](https://user-images.githubusercontent.com/13550529/156509461-4c29b5d8-f384-4d6e-a430-0369b9223d6f.png)

**Comment by Shane-XB-Qian** [comment]
after this change/patch, the highlight looks normal/right, but the text looked missed (lost half of that wild-char).
// so actually not sure if it was intended (to design like that), or better to not only correct the highlight but also show the 'half char' too?

**Comment by brammool** [comment]
> after this change/patch, the highlight looks normal/right, but the
> text looked missed (lost half of that wild-char).  // so actually not
> sure if it was intended (to design like that), or better to not only
> correct the highlight but also show the 'half char' too?

How to reproduce this problem?  Does it show in the screenshots of the
test?  If not, then perhaps you can add a test case that shows the
problem (and can be used as a test when it's fixed).

-- 
hundred-and-one symptoms of being an internet addict:
192. Your boss asks you to "go fer" coffee and you come up with 235 FTP sites.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Shane-XB-Qian** [comment]
> Does it show in the screenshots of the
test?

yes. pls check the second char '哦' of the second line in these three Chinese chars lines.
the scrollbar hidden the half the '哦', best result is to show the half of that char (but now it is a space instead vs it was a bold highlight space same color like scrollbar). but not sure if it is easy or not for vim to implement, since was it two layers of paint or it was a plain?

--
shane.xb.qian

**Comment by brammool** [comment]
> > Does it show in the screenshots of the test?
> 
> yes. pls check the second char '哦' of the second line in these three
> Chinese chars lines.
> the scrollbar hidden the half the '哦', best result is to show the
> half of that char (but now it is a space instead vs it was a bold
> highlight space same color like scrollbar). but not sure if it is easy
> or not for vim to implement, since was it two layers of paint or it
> was a plain?

Aha, not showing the half of a wide character.  That is not possible in
general.  Perhaps in some GUI it can be made to work, but most terminals
cannot show half a character.  It may work for a moment, by first
drawing the whole character and then drawing the normal wide character
on top, but it may then disappear any moment.

In Vim it would require quite a few changes, currently it's not possible
to draw one character on top of another one.  I don't think it is worth
it.

-- 
hundred-and-one symptoms of being an internet addict:
194. Your business cards contain your e-mail and home page address.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Shane-XB-Qian** [comment]
ok. then perhaps it was intended. so now do we needed to fill something (other than one bold space which had same color like upper layer scrollbar or one empty space char) to indicate there actually was half char there?

--
shane.xb.qian

**Comment by Shane-XB-Qian** [comment]
> When a character doesn't fit at the end of the line we show ">".
> When the left half is missing we could show "<" perhaps.

I think it is a good choice, but just here actually is two layers vs not the Wild-char faced the window's border.
I think we should fill something, otherwise those chars/lines would look like some holes which missed something.
perhaps bold space was ok, but highlight to something else (different color, not same like scroll bar, not same like general chars too)

--
shane.xb.qian

**Comment by Shane-XB-Qian** [comment]
like `〿` this one.

**Comment by Shane-XB-Qian** [comment]
or let it be, i am not sure if it's worth or better or not..
// seems the wild-char under/near `popup term` 's border is same (same did not paint the half-char).
