### ISSUE TITLE
Directories named *.com treated as dcl files

### ISSUE THREAD

**Issue by teoljungberg** [vim/vim#9875]
### Steps to reproduce

0. Setup vim with netrw.

```
% cat test.vim
set nocompatible
filetype plugin on
```

2. Create a directory `% mkdir -p google.com/example`.
3. Open said directory in vim `% vim -u test.vim google.com/example`
4. Press `-` to open the `google.com` directory
5. `echo &ft` returns `dcl`.

### Expected behaviour

I expect the directory to have a filetype of `netrw` as other directories do, not `dcl`.

I'm fine being able to override this, and have tried to do so with:

```viml
autocmd BufReadPost *.com set filetype=netrw
```

And failed.

### Version of Vim

8.2.4227

### Environment

OS: macOS 12.0.1
Terminal: Kitty
$TERM: xterm-256color
shell: zsh 5.8

### Logs and stack traces

```shell
```

**Comment by teoljungberg** [comment]
There probably is a way to override the filetypes directly to be the expected ones when opening the `google.com` directory, I cannot get it to work with opening `google.com/example` and then navigating back to it.

**Comment by brammool** [comment]
@cecamp

**Comment by teoljungberg** [comment]
A naive suggestion would be a patch similar to this:

```diff
diff --git a/runtime/filetype.vim b/runtime/filetype.vim
index 77c736c18..b7988d0a0 100644
--- a/runtime/filetype.vim
+++ b/runtime/filetype.vim
@@ -520,7 +520,7 @@ au BufNewFile,BufRead *.rul
 	\ endif
 
 " DCL (Digital Command Language - vms) or DNS zone file
-au BufNewFile,BufRead *.com			call dist#ft#BindzoneCheck('dcl')
+au BufNewFile,BufRead *.com			if filereadable(<afile>) | call dist#ft#BindzoneCheck('dcl') | endif
 
 " DOT
 au BufNewFile,BufRead *.dot,*.gv		setf dot
```

**Comment by brammool** [comment]
> A naive suggestion would be a patch similar to this:
> 
> ```diff
> diff --git a/runtime/filetype.vim b/runtime/filetype.vim
> index 77c736c18..b7988d0a0 100644
> --- a/runtime/filetype.vim
> +++ b/runtime/filetype.vim
> @@ -520,7 +520,7 @@ au BufNewFile,BufRead *.rul
>  	\ endif
>  
>  " DCL (Digital Command Language - vms) or DNS zone file
> -au BufNewFile,BufRead *.com			call dist#ft#BindzoneCheck('dcl')
> +au BufNewFile,BufRead *.com			if filereadable(<afile>) | call dist#ft#BindzoneCheck('dcl') | endif
>  
>  " DOT
>  au BufNewFile,BufRead *.dot,*.gv		setf dot
> ```

The problem is not specific for .com directory names, is it?

-- 
hundred-and-one symptoms of being an internet addict:
147. You finally give up smoking...because it made the monitor dirty.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by teoljungberg** [comment]
Having limited experience with `.dcl` files - I only ran into this due to my local project structure is `~/src/github.com/vim/vim` as the path to the vim repository. And navigating to that directory via netrw is what made me find this issue.

**Comment by teoljungberg** [comment]
Circling back to this, I ran into the same issue with other directories and netrw as well.

Opening a directory named `.vim`, then navigating to a directory above or inside it, and then back again - this changes the `&filetype` from `netrw` to `vim`.

**Comment by cecamp** [comment]
Just saw this thread today. Netrw is getting the filetype from: `filetype detect`.

**Comment by brammool** [comment]
Charles wrote:

> Just saw this thread today. Netrw is getting the filetype from:
> `filetype detect`.

Perhaps that should only be done for regular files, not directories.

-- 
hundred-and-one symptoms of being an internet addict:
99. The hum of a cooling fan and the click of keys is comforting to you.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by teoljungberg** [comment]
I’ve opened #11290 to resolve this issue.
