### ISSUE TITLE
kill jokes that said how to exit from vim

### ISSUE THREAD

**Issue by ayoubelmhamdi** [vim/vim#9880]
the new users can't quit vim as they expect
I propose to set the default mapping to quit `vim` as `nano`
`ctrl+x/ctrl+q`
like that:
```vim
if no vimrc config
  map <c-q> <cmd>qa!
else
  do nothing
end
```

**Comment by brammool** [comment]
Why like nano?  Seems rather arbitrary.
We anticipate users will try CTRL-C, and then Vim will give a helpful message.

**Comment by ayoubelmhamdi** [comment]
- Yeah new users maybe use  `CTRL-C` to exit 
- my be use other keybinding

**Comment by chrisbra** [comment]
> Yeah new users maybe use CTRL-C to exit

You have seen the message when pressing Ctrl-C, right?
![image](https://user-images.githubusercontent.com/244927/156584673-d047fb30-4d4d-46f7-aceb-c3279b98428f.png)

**Comment by ayoubelmhamdi** [comment]
yes
