### ISSUE TITLE
Vim9: no error for declaring variable with wrong type from the command-line with `:vim9cmd`

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9881]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE +'vim9cmd var x: job = [123, "abc", true] | echo x'

No error is given.  This list constant is echo'ed:

    [123, 'abc', v:true]

**Expected behavior**

Not sure.  To be consistent with a Vim9 script, we might want to enforce type checking even when an assignment is executed from the command-line via `:vim9cmd`.  In that case, an error should be given, because a list constant containing items with mixed types has the type `list<any>`.  But in the assignment, we specified `job` which cannot be satisfied by `list<any>`.

What happens is that when we declare a variable from the command-line, it's automatically turned into a global variable:

    $ vim -Nu NONE +'vim9cmd var x: job = [123, "abc", true] | echo g:
    {'x': [123, 'abc', v:true]}
    ^                         ^

That makes sense.  It's the only available scope: the assignment command is not executed from inside a block, a function, a script ...  Besides, global variables cannot be declared, and have no types.  Hence why no error is given.

However, silently ignoring the declaration without giving an error could be confusing (“why does this declaration fail in my script but not on the command-line?”).  Maybe we should give an error, or a warning.  Alternatively, if this is considered to be a convenient feature, then at least we might want to document what happens.  As a suggestion here is a patch:
```diff
diff --git a/runtime/doc/vim9.txt b/runtime/doc/vim9.txt
index 385238bfb..370c548df 100644
--- a/runtime/doc/vim9.txt
+++ b/runtime/doc/vim9.txt
@@ -60,6 +60,9 @@ rewrite old scripts, they keep working as before.  You may want to use a few
 		Evaluate and execute {cmd} using Vim9 script syntax and
 		semantics.  Useful when typing a command and in a legacy
 		script or function.
+		Note that if `:vim9` is used on the command line, and {cmd} is
+		`:var`, the variable will be global no matter what.  Any type
+		specification is silently ignored.
 
 :leg[acy] {cmd}					*:leg* *:legacy* *E1189* *E1234*
 		Evaluate and execute {cmd} using legacy script syntax and
```

**Version of Vim**

8.2 Included patches: 1-4495

**Environment**

Operating system: Ubuntu 20.04.4 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: zsh 5.8

**Comment by brammool** [comment]
Having "var x" declare a global variable would be very weird. You would use "g:x = value".
I don't see a reason to allow any variable declaration on the command line.  Most likely it would be a mistake.

**Comment by Shane-XB-Qian** [comment]
why `:vim9cmd g:foo = 123` is disallowed too ?

**Comment by lacygoill** [comment]
> :vim9cmd g:foo = 123 is disallowed too ?

There is no reason to disallow publically available variables from being assigned (`b:foo`, `g:foo`, `t:foo`, `v:oldfiles`, `w:foo`).  Also, for those variables, the current error message is irrelevant, because they have no types and thus cannot be declared.  It looks like a regression.

**Comment by brammool** [comment]
> why `:vim9cmd g:foo = 123` is disallowed too ?

That was a mistake, I'll fix it.

-- 
Apathy Error: Don't bother striking any key.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
