### ISSUE TITLE
spell check: adding a word with zg adds it to the wrong dictionary

### ISSUE THREAD

**Issue by acardona** [vim/vim#9888]
### Steps to reproduce

1. Set the dictionary to another language, e.g. Catalan with :set spell spelllang=ca
2. Encounter a word not present in the dictionary, but which is correct. For example "moltíssim".
3. Push zg to add it to the dictionary. Reports:
```
Word 'moltíssim' added t...im/spell/en_gb.utf-8.add
```
... which the British English dictionary, specified system-wide, and not the dictionary I had set for use when starting to edit this file.

### Expected behaviour

That the new word added with zg gets added instead to ~/.vim/spell/ca.utf-8.add

### Version of Vim

VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 01 2022 09:16:32) Included patches: 1-2269, 3612, 3625, 3669, 3741 Modified by team+vim@tracker.debian.org Compiled by team+vim@tracker.debian.org Huge version with GTK3 GUI.

### Environment

OS: Ubuntu 20.04
Terminal: gnome-terminal

**Comment by brammool** [comment]
When I try the reproduction steps, I get: "Word 'moltíssim' added to ~/.vim/spell/ca.utf-8.add"

I suspect you have some option set to use a different spell file. See ":help spell-load".

**Comment by chrisbra** [comment]
closing as unreproducible
