### ISSUE TITLE
0xff will be displayed as 0x3f in xxd mode when "set fileencodings=ucs-bom"

### ISSUE THREAD

**Issue by zoumi** [vim/vim#9899]
### Steps to reproduce

1,set fileencodings=ucs-bom in vimrc
2,start gvim and open a binary file with content 0xff 0xff
3,switch to xxd mode with :%!xxd

### Expected behaviour

0xff be displayed as 0xff

### Version of Vim

gvim 8.2

### Environment

Windows 10 64bit

**Comment by brammool** [comment]
I assume your 'encoding' is set to "utf-8".
Your value for 'fileencodings' does not match the encoding of the file, so the conversion fails.
Use the value "ucs-bom,latin1" and it should work.

**Comment by matveyt** [comment]
You open file in default (text) mode, and so it's a subject to undesired conversion. Open binary files in binary mode to avoid this. For example,

```VimL
" open binary file
:e ++bin foobar.bin
" hex print it
:%!xxd
"optional settings
:set nobinary nomodified
:setf xxd
```

**Comment by zoumi** [comment]
Thank you.
