### ISSUE TITLE
Incorrect behaviour with nested substitution groups

### ISSUE THREAD

**Issue by HarmtH** [vim/vim#990]
I've tried [this](https://github.com/vim/vim/blob/v7.4.2228/runtime/doc/change.txt#L871) example from the documentation in v7.4.2228, and Vim's behaviour didn't agree with the documentation.

As a better example I tried on the text:
`aa ab x`
The command:
`s/\(\(a[a-d] \)*\)\(x\)/\?/` with `?`=1..3
And found out:
`\1` contains `aa ab`
`\2` is empty
`\3` contains `x`

**Comment by brammool** [comment]
Harm te Hennepe wrote:

> I've tried [this](https://github.com/vim/vim/blob/v7.4.2228/runtime/doc/change.txt#L871) example from the documentation in v7.4.2228, and Vim's behaviour didn't agree with the documentation.
> 
> As a better example I tried on the text:
> `aa ab x`
> The command:
> `s/\(\(a[a-d] \)*\)\(x\)/\?/` with `?`=1..3
> And found out:
> `\1` contains `aa ab`
> `\2` is empty
> `\3` contains `x`

What example?

What did you do exactly?

## 

You have the right to remain silent. Anything you say will be
misquoted, then used against you.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by HarmtH** [comment]
The example in the given paragraph states `\2` should give `ab`,
but in 7.4.2228 `\1` gives `aa ab` and `\2` gives nothing.

**Comment by brammool** [comment]
[fixed the quote order]

Harm te Hennepe wrote:

> > > I've tried [this](https://github.com/vim/vim/
> > > blob/v7.4.2228/runtime/doc/change.txt#L871) example from the
> > > documentation in v7.4.2228, and Vim's behaviour didn't agree with the
> > > documentation.
> > > 
> > > As a better example I tried on the text:
> > > `aa ab x`
> > > The command:
> > > `s/\(\(a[a-d] \)*\)\(x\)/\?/` with `?`=3D1..3
> > > And found out:
> > > `\1` contains `aa ab`
> > > `\2` is empty
> > > `\3` contains `x`
> > 
> > What example?
> > 
> > What did you do exactly?
> 
> The example in the given paragraph states `\2` should give `ab`,
> but in 7.4.2228 `\1` gives `aa ab` and `\2` gives nothing.

OK, so I need to decipher a URL to see what you mean...

It appears to work correctly when 'regexpengine' is set to 1, thus it
must be a bug with the new engine.

## 

I wonder how much deeper the ocean would be without sponges.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///
