### ISSUE TITLE
Missing vim9script error location for python vim.command

### ISSUE THREAD

**Issue by errael** [vim/vim#9901]
### Steps to reproduce

Given t.vim
```
vim9script

def F2(v: string)
    F1('a' .. v 'c')
enddef

def F3()
    F2('b')
enddef

command -nargs=0 F3 F3()

py3file t.py

```
and t.py in the same directory
```
import vim

vim.command('F3')
```
In vim do `source t.vim` and get the following, which gives no clue as to the location of the problem
```
Error detected while processing /home/err/play/t.vim[13]../home/err/play/t.vim:
line   13:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "t.py", line 3, in <module>
    vim.command('F3')
vim.error: Vim(eval):E1123: Missing comma before argument: 'c')
```

### Expected behaviour

Doing `F3()`, instead of `py3file t.py`, gives the following. It points straight to the problem. This info would be ideal.
```
Error detected while compiling /home/err/play/t.vim[13]..function <SNR>35_F3[1]..<SNR>35_F2:
line    1:
E1123: Missing comma before argument: 'c')
```

### Version of Vim

8.2.4507

### Environment

ubuntu 21.10, gvim gtk-3

**Comment by errael** [comment]
I came across the various "v:" stuff. Tried echo v:errors, v:exception, no luck. v:errmsg has
```
vim.error: Vim(eval):E1123: Missing comma before argument: 'c')
```
Anywhere else the info might be captured/stashed?

**Comment by lacygoill** [comment]
Possible duplicate of https://github.com/vim/vim/issues/7870

I don't think the issue is related to the python interface.  I think the issue comes from executing a user-defined command.  When the expansion of such a command contains a syntax error, we need to know where it was defined to fix the issue.  Instead, Vim tells us where it's executed which is less useful.

**Comment by lacygoill** [comment]
Actually, it's not the exact same issue, because here, the syntax error is not in the rhs of a user-defined command but inside a function call.

**Comment by errael** [comment]
Noise, closing
