### ISSUE TITLE
py3 returns bytes not strings for vim.options

### ISSUE THREAD

**Issue by errael** [vim/vim#9917]
### Steps to reproduce

:py3 import vim
:py3 print(vim.options['bg'])

outputs: b'light'

### Expected behaviour

outputs: light

NOTE: this works with :py (python 2.7)

### Version of Vim

8.2.4507 (I think all patch levels)

### Environment

windows, ubuntu

Before I look much at the sources, I wanted to get some feedback. This could be intentional or considered an enhancement.

**Comment by puremourning** [comment]
More generally, I think it returns 'bytes' for _any dict members_ which are strings.

I work around this generally thus, though it's not ideal (hard-coding utf-8 is likely wrong and it should use `&encoding` or whatever): https://github.com/puremourning/vimspector/blob/master/python3/vimspector/utils.py#L807-L817

I suspect that changing this is going to break things that are already handling/expecting it

FWIW, there's another discrepancy around dict keys, which is a little awkward, particularly if you wish to support both vim and neovim, which has a completely different if_python implementation with many little differences, such as: https://github.com/puremourning/vimspector/blob/master/python3/vimspector/settings.py#L99-L108

**Comment by errael** [comment]
This is noise, closing
