### ISSUE TITLE
xxd prematurely cuts data

### ISSUE THREAD

**Issue by nicexe** [vim/vim#9922]
### Steps to reproduce

1. `docker run alpine /bin/sh -c "printf 'c3cc3bb82a5c682c525075d7e0033c307d189577f8075dcff162dff98325f2f8c7195d65d131f89038df6c0816d6cf259ac965da55e8d0aef33fe47896f15b2f' | xxd -r -p | xxd"`

### Expected behaviour

The output should include the complete hex of the input hex string:
```
00000000: c3cc 3bb8 2a5c 682c 5250 75d7 e003 3c30  ..;.*\h,RPu...<0
00000010: 7d18 9577 f807 5dcf f162 dff9 8325 f2f8  }..w..]..b...%..
00000020: c719 5d65 d131 f890 38df 6c08 16d6 cf25  ..]e.1..8.l....%
00000030: 9ac9 65da 55e8 d0ae f33f e478 96f1 5b2f  ..e.U....?.x..[/
```
but instead cuts everything after the 30th byte (0x1e):
```
00000000: c3cc 3bb8 2a5c 682c 5250 75d7 e003 3c30  ..;.*\h,RPu...<0
00000010: 7d18 9577 f807 5dcf f162 dff9 8325       }..w..]..b...%
```

### Version of Vim

BusyBox v1.34.1 (2021-11-23 00:57:35 UTC) multi-call binary.

### Environment

Operating system: alpine:latest (this is the Dockerfile at the time of writing [docker-alpine/Dockerfile at 818c831891a18d2453ad6458011ea8cbff74d0e1 · alpinelinux/docker-alpine](https://github.com/alpinelinux/docker-alpine/blob/818c831891a18d2453ad6458011ea8cbff74d0e1/x86_64/Dockerfile))
value of $TERM: xterm
shell: SVR4 Bourne shell (SunOS 5 schily variant, since 2016-08-08, in posix mode)

**Comment by brammool** [comment]
When I run this at a bash prompt it works fine.  I doubt this is a problem with xxd.

**Comment by nicexe** [comment]
> When I run this at a bash prompt it works fine. I doubt this is a problem with xxd.

same happens with bash
```
$ docker run -ti alpine
/ # apk update
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
v3.15.0-334-g372c6a106a [https://dl-cdn.alpinelinux.org/alpine/v3.15/main]
v3.15.0-339-g2443b921b6 [https://dl-cdn.alpinelinux.org/alpine/v3.15/community]
OK: 15859 distinct packages available
/ # apk add bash
(1/4) Installing ncurses-terminfo-base (6.3_p20211120-r0)
(2/4) Installing ncurses-libs (6.3_p20211120-r0)
(3/4) Installing readline (8.1.1-r0)
(4/4) Installing bash (5.1.16-r0)
Executing bash-5.1.16-r0.post-install
Executing busybox-1.34.1-r3.trigger
OK: 8 MiB in 18 packages
/ # bash
bash-5.1# printf 'c3cc3bb82a5c682c525075d7e0033c307d189577f8075dcff162dff98325f2f8c7195d65d131f89038df6c0816d6cf259ac965da55e8d0aef33fe47896f15b2f' | xxd -r -p | xxd
00000000: c3cc 3bb8 2a5c 682c 5250 75d7 e003 3c30  ..;.*\h,RPu...<0
00000010: 7d18 9577 f807 5dcf f162 dff9 8325       }..w..]..b...%
bash-5.1#
```

**Comment by nicexe** [comment]
setting `-c` to the length of the input bytes makes it work

```
$ docker run alpine /bin/sh -c "printf 'c3cc3bb82a5c682c525075d7e0033c307d189577f8075dcff162dff98325f2f8c7195d65d131f89038df6c0816d6cf259ac965da55e8d0aef33fe47896f15b2f' | xxd -r -p -c 64 | xxd"
00000000: c3cc 3bb8 2a5c 682c 5250 75d7 e003 3c30  ..;.*\h,RPu...<0
00000010: 7d18 9577 f807 5dcf f162 dff9 8325 f2f8  }..w..]..b...%..
00000020: c719 5d65 d131 f890 38df 6c08 16d6 cf25  ..]e.1..8.l....%
00000030: 9ac9 65da 55e8 d0ae f33f e478 96f1 5b2f  ..e.U....?.x..[/
$ 
```

So this might be due to inconsistent defaults (working on some systems and not on others)

**Comment by brammool** [comment]
Since it works fine for me I can't try to figure out what happens.  Can you add some debug statements or run xxd in a debugger?

**Comment by nicexe** [comment]
This can be reproduced using this exact command (though it needs docker):
`docker run alpine /bin/sh -c "printf 'c3cc3bb82a5c682c525075d7e0033c307d189577f8075dcff162dff98325f2f8c7195d65d131f89038df6c0816d6cf259ac965da55e8d0aef33fe47896f15b2f' | xxd -r -p | xxd"`

To get shell you can instead do `docker run -ti alpine` and later invoke xxd or other commands.

**Comment by chrisbra** [comment]
alpine is using busybox xxd, not this one. It works if you install the original xxd `apk add xxd`.

I suggest you raise this issue with the busybox developers instead.
