### ISSUE TITLE
Use better high resolution icons

### ISSUE THREAD

**Issue by chrisbra** [vim/vim#9930]
Hi,
the default Vim icon that is used on Windows Desktops looks quite ugly:
![image](https://user-images.githubusercontent.com/244927/157854984-dccf37ea-9869-481a-ac30-e4e4f81c5184.png)

BTW: that is one of the reasons I immediately delete those icons after installation they just make my desktop look ugly.

I remember some time ago, there was a thread on vim-dev to use a better icon: https://groups.google.com/g/vim_dev/c/g-sV7iAVgVE/m/_XMUpPumUpsJ 

That would make it look like this:
![image](https://user-images.githubusercontent.com/244927/157856043-fbfb0f09-3faa-40ed-af83-ff91153b231b.png)

and I know @dertuxmalwieder is already using this icon for his builds https://tuxproject.de/projects/vim/

My suggestion is, to start using that icon at least with the next release of Vim 9

**Describe alternatives you've considered**
Create new proper hi-dpi icons. But that would need someone elses work and will probably just be quite some effort.

Thanks,
Chris

**Comment by dertuxmalwieder** [comment]
Good idea. One thing less to maintain for me. ;-)

Not sure about the license though. I vaguely remember to have asked for (and been granted) permission explicitly.

**Comment by brammool** [comment]
I would appreciate it if someone can figure out the right file and create a PR.
About the license: I'm not sure if applying some scaling tools to produce the icon in a different format means a license is needed.
For the image itself we won't have a problem.
