### ISSUE TITLE
Survey of scrollbar colors in Motif

### ISSUE THREAD

**Issue by qsmodo** [vim/vim#9933]
### Steps to reproduce

```
xrdb /dev/null
gvim -u NONE -xrm 'Vim.scrollForeground: red'
gvim -u NONE -xrm 'Vim.scrollForeground: red' -xrm 'Vim.scrollBackground: blue'
```

![2022-03-11-173731_355x375_scrot](https://user-images.githubusercontent.com/75080827/157963879-bfaf415a-ea80-4cab-a2a9-33bc82fa3a85.png)

### Expected behaviour

As per `:h gui-resources`, 
```
    scrollBackground	Color of trough portion of scrollbars.
    scrollForeground	Color of slider and arrow portions of scrollbars.
```

So the slider and arrow should be red in both cases.

### The root of the problem

Is Motif's style of giving things a 3D (?) look with fancy borders and shades. By default, **sliderVisual** (see [XmScrollBar](https://sites.ualberta.ca/dept/chemeng/AIX-43/share/man/info/C/a_doc_lib/libs/motiftr/XmScrollBar.htm)) takes

> XmSHADOWED_BACKGROUND
>
>    Specifies that the slider visual is in the background color, with a shadow. This is the default for a regular slider.

So, you might think, the solution is simple, just use **XmFOREGROUND_COLOR** instead, which yields

![/usr/local/bin/gvim -u NONE -xrm 'Vim.background:black' -xrm 'Vim.scrollForeground: red' -xrm 'Vim.scrollBackground: black'](https://user-images.githubusercontent.com/75080827/157963806-df2d9d6a-d625-4f58-a890-b772131ffc96.png)

Might look good enough, but if you look closely, the area of the trough is of a darker blue, and things get ugly in a dark background:

![/usr/local/bin/gvim -xrm 'Vim.scrollForeground: red' -xrm 'Vim.scrollBackground: black'](https://user-images.githubusercontent.com/75080827/157965160-ea34faab-ba0c-46c0-9aaa-2059394c4a3f.png)

One way to decrease the ugliness a bit this is by suppressing shadows by passing `-xrm 'Vim*scrollBar.shadowThickness: 0'`:

![/usr/local/bin/gvim -xrm 'Vim.scrollForeground: red' -xrm 'Vim.scrollBackground: black' -xrm 'Vim*scrollBar.shadowThickness: 0'](https://user-images.githubusercontent.com/75080827/157966454-b8b03732-e257-4170-9199-fcdf4dc9649d.png)

Too bad, the trough is somewhat gray (not the mention the scroll arrows that became almost invisible; but I don't really like them and use the `Vim*showArrows: NONE` X-resource to make them disappear).

This all you caused by

https://github.com/vim/vim/blob/fb43cfc2c6a003b850343bfd27cb3059c734d7d4/src/gui_motif.c#L1897-L1903

> XmChangeColor handles all color modifications for the specified widget when a new background pixel value is specified. __The function recalculates the foreground, select, and shadow colors based on the new background color__ and sets the corresponding resources for the widget.

So, the natural question is: What if we always go with **XtVaSetValues** (which is not deprecated)? Then we have this picture below, with the top window being the new default look of Gvim, and beneath it we have `gvim -xrm 'Vim.scrollForeground: red' -xrm 'Vim.scrollBackground: black' -xrm 'Vim*scrollBar.shadowThickness: 0'`, with a dark colorscheme.

![2022-03-11-181828_358x376_scrot](https://user-images.githubusercontent.com/75080827/157968017-ea5189a4-ac3e-4438-bf79-f07dbb8ef627.png)

The simplest solution is to take away `scrollForeground` from Motif, but as we've seen the result is very ugly for dark themes. If we don't, then we either have to take away the Motif look from the scrollbar (by using **XmFOREGROUND_COLOR** and removing **XmChangeColor**, entirely removing its shadows, giving a sane default foreground color, etc.):

![/usr/local/bin/gvim -u NONE -xrm 'Vim*scrollBar.shadowThickness: 0' -xrm 'Vim*scrollForeground: gray50'](https://user-images.githubusercontent.com/75080827/157972459-c919935b-71dc-46f7-acea-575344904db5.png)

or let dark theme users live with its ugliness. Unless someone can envisage a simpler solution.

By the way, this is a reason I prefer Athena with its no frills interface. The scrollbar is easily and completely customizable by the end user via X-resources.

### Version of Vim

8.2.4318

### Environment

OS: Gentoo
Motif: 2.3.8

**Comment by brammool** [comment]
It looks like I can make it work by also setting the XmNbackground:
```
	if (gui.scroll_fg_pixel != INVALCOLOR)
	    XtVaSetValues(sb->id,
		    XmNforeground, gui.scroll_fg_pixel,
//#if (XmVersion<1002)
		    XmNbackground, gui.scroll_fg_pixel,
//#endif
		    NULL);
```
At least then the color of the thumb is red.

**Comment by brammool** [comment]
I haven't tried it, but perhaps it is also possible to both call XmChangeColor() and then call  XtVaSetValues() to set the XmNtroughColor as well?  Not sure if that would make any difference.

**Comment by qsmodo** [comment]
> It looks like I can make it work by also setting the XmNbackground:
> 
> ```
> 	if (gui.scroll_fg_pixel != INVALCOLOR)
> 	    XtVaSetValues(sb->id,
> 		    XmNforeground, gui.scroll_fg_pixel,
> //#if (XmVersion<1002)
> 		    XmNbackground, gui.scroll_fg_pixel,
> //#endif
> 		    NULL);
> ```
> 
> At least then the color of the thumb is red.

True, but we also need to

> both call XmChangeColor() and then call XtVaSetValues() to set the XmNtroughColor as well

otherwise the through won't honor the background color (it will get slightly altered, such as that dark grey look instead of black in one of the pictures above).

Also, the initialization of the scrollbar colors is lacking `gui_get_color`, so it currently doesn't pull color definitions from the X server database. As such, we need

```
-       gui.menu_fg_pixel = gui.menu_def_fg_pixel;
-       gui.menu_bg_pixel = gui.menu_def_bg_pixel;
-       gui.scroll_fg_pixel = gui.scroll_def_fg_pixel;
-       gui.scroll_bg_pixel = gui.scroll_def_bg_pixel;
+       gui.menu_fg_pixel = gui_get_color((char_u *)gui.rsrc_menu_fg_name);
+       gui.menu_bg_pixel = gui_get_color((char_u *)gui.rsrc_menu_bg_name);
+       gui.scroll_fg_pixel = gui_get_color((char_u *)gui.rsrc_scroll_fg_name);
+       gui.scroll_bg_pixel = gui_get_color((char_u *)gui.rsrc_scroll_bg_name);
```

Putting it all in [this patch](https://github.com/vim/vim/files/8237790/scrollbar.txt), the result is good for all the forms I tested, as long as one gets rid of shadowThickness in a dark theme:

![](https://user-images.githubusercontent.com/75080827/158022630-f19f2316-ab09-4cd7-a3fd-f59430b166f0.png)

From top to bottom:

```
$ xrdb ~/.Xresources; seq 1 12 | gvim -
$ xrdb ~/.Xresources; seq 1 12 | gvim - -xrm 'Vim*shadowThickness: 0'
$ xrdb /dev/null;     seq 1 12 | gvim - -u NONE
$ xrdb /dev/null;     seq 1 12 | gvim - -u NONE -xrm 'Vim*scrollForeground: red' -xrm 'Vim*scrollBackground:blue'
```

**Comment by brammool** [comment]
> > It looks like I can make it work by also setting the XmNbackground:
> > 
> > ```
> > 	if (gui.scroll_fg_pixel != INVALCOLOR)
> > 	    XtVaSetValues(sb->id,
> > 		    XmNforeground, gui.scroll_fg_pixel,
> > //#if (XmVersion<1002)
> > 		    XmNbackground, gui.scroll_fg_pixel,
> > //#endif
> > 		    NULL);
> > ```
> > 
> > At least then the color of the thumb is red.
> 
> True, but we also need to
> 
> > both call XmChangeColor() and then call XtVaSetValues() to set the
> > XmNtroughColor as well
> 
> otherwise the through won't honor the background color (it will get
> slightly altered, such as that dark grey look instead of black in one
> of the pictures above).

OK, that matches with what I'm seeing.

> Also, the initialization of the scrollbar colors is lacking `gui_get_color`, so it currently doesn't pull color definitions from the X server database. As such, we need
> 
> ```
> -       gui.menu_fg_pixel = gui.menu_def_fg_pixel;
> -       gui.menu_bg_pixel = gui.menu_def_bg_pixel;
> -       gui.scroll_fg_pixel = gui.scroll_def_fg_pixel;
> -       gui.scroll_bg_pixel = gui.scroll_def_bg_pixel;
> +       gui.menu_fg_pixel = gui_get_color((char_u *)gui.rsrc_menu_fg_name);
> +       gui.menu_bg_pixel = gui_get_color((char_u *)gui.rsrc_menu_bg_name);
> +       gui.scroll_fg_pixel = gui_get_color((char_u *)gui.rsrc_scroll_fg_name);
> +       gui.scroll_bg_pixel = gui_get_color((char_u *)gui.rsrc_scroll_bg_name);
> ```

That is what Athena does.  I would think gui.menu_def_fg_pixel has the
value from gui.rsrc_menu_fg_name.  They are set in
gui_x11_create_widgets() and gui_mch_create_scrollbar().
What is missing here?  The color may have been overruled by the
"Scrollbar" highlight group, after using the resources.
 

-- 
"Marriage is a wonderful institution...
but who wants to live in an institution?"
 - Groucho Marx

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by qsmodo** [comment]
>That is what Athena does.  I would think gui.menu_def_fg_pixel has the
value from gui.rsrc_menu_fg_name.  They are set in
gui_x11_create_widgets() and gui_mch_create_scrollbar().
What is missing here?  The color may have been overruled by the
"Scrollbar" highlight group, after using the resources.

Sorry, I don't quite understand what you mean. `gui_athena.c` does this, but `gui_motif.c` doesn't. 

As far as I know, one can't just do

```
	XtVaGetValues(menuBar,
	    XmNbackground, &gui.menu_def_bg_pixel,
	    XmNforeground, &gui.menu_def_fg_pixel,
	    NULL);
```

(and similarly for the scrollbar) and expect to retrieve what the user has chosen as `Vim.{menu,scrollbar}{Background,Foreground}` in its X resources file because that is not a canonical resource structure and therefore Xt is oblivious to them. So Xt always retrieves the default, hardcoded value instead of the user defined one. The canonical structure would be of the kind `Vim*scrollBar.background: color` and `Vim*menuBar.background: color`, and if you set that in your X-resources, you won't need `gui_get_color`; but the former structure, not the latter, is what `:h gui-resources` documents.

**Comment by brammool** [comment]
> > That is what Athena does.  I would think gui.menu_def_fg_pixel has the
> > value from gui.rsrc_menu_fg_name.  They are set in
> > gui_x11_create_widgets() and gui_mch_create_scrollbar().
> > What is missing here?  The color may have been overruled by the
> > "Scrollbar" highlight group, after using the resources.
> 
> Sorry, I don't quite understand what you mean. `gui_athena.c` does
> this, but `gui_motif.c` doesn't. 
> 
> As far as I know, one can't just do
> 
> ```
> 	XtVaGetValues(menuBar,
> 	    XmNbackground, &gui.menu_def_bg_pixel,
> 	    XmNforeground, &gui.menu_def_fg_pixel,
> 	    NULL);
> ```
> 
> (and similarly for the scrollbar) and expect to retrieve what the user
> has chosen as `Vim.{menu,scrollbar}{Background,Foreground}` in its X
> resources file because that is not a canonical resource structure and
> therefore Xt is oblivious to them. So Xt always retrieves the default,
> hardcoded value instead of the user defined one. The canonical
> structure would be of the kind `Vim*scrollBar.background: color` and
> `Vim*menuBar.background: color`, and if you set that in your
> X-resources, you won't need `gui_get_color`; but the former structure,
> not the latter, is what `:h gui-resources` documents.

Using vim.scrollbarBackground only looks at the X resources.  In Vim the
normal way to set colors (from .gvimrc) is:

	highlight Scrollbar guibg=lightblue guifg=blue

That should have higher priority than X resources (which are not that
easy to figure out for an averge Vim user).

-- 
"After a few years of marriage a man can look right at a woman
without seeing her and a woman can see right through a man
without looking at him."
 - Helen Rowland

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by qsmodo** [comment]
>That should have higher priority than X resources (which are not that
easy to figure out for an averge Vim user).

According to my tests, the patch does exactly that. Did you observe a different behavior?
