### ISSUE TITLE
statusline is reevaluated even if cursor hasn't moved

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#9935]
### Steps to reproduce

1. Run `vim --clean` and source the following file
```vim
let g:statusline_counter = 0

function MyStatusline()
  let g:statusline_counter = g:statusline_counter + 1
  return g:statusline_counter
endfunction

set laststatus=2
setlocal statusline=%!MyStatusline()

nnoremap <F2> <Cmd><CR>
nnoremap <F3> <Cmd><CR><Cmd><CR><Cmd><CR>
```
2. The number on statusline increases by one every time `<F2>` is pressed, and increases by three every time `<F3>` is pressed.

### Expected behaviour

I'm not sure whether the current behavior is intended or just hasn't been considered yet, as I found these comments before `void showruler(int always)` (which is called by every main loop iteration with `always=FALSE`) in `drawscreen.c`:
```c
/*
 * Show current status info in ruler and various other places
 * If always is FALSE, only show ruler if position has changed.
 */
```
This means pressing `<F2>` or `<F3>` should not reevaluate statusline, as they do not change cursor position.

However, a `<Cmd>` mapping can do anything (e.g. setting variables), and a custom statusline can depend on any variable, so the current behavior indeed can be useful (not sure how), and in this case the comment should be changed.

Something else I noticed: a timer can also do anything, and a timer doesn't cause statusline to be reevaluated. Is some consistency needed here?

### Version of Vim

8.2.4464

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

**Comment by brammool** [comment]
As you already mentioned, a custom statusline can depend on just about anything.  There have been several reports in the past that the status line wasn't updated even though something changed that would make it show differently.  So don't be surprised that it is updated even though nothing actually changed.

**Comment by zeertzjq** [comment]
In most cases a timer does not do something that affect statusline, while mappings are more likely to affect statusline. I'll close this then.
