### ISSUE TITLE
Cannot continue typing commands in the hit-enter prompt when the ":" key is remapped

### ISSUE THREAD

**Issue by bfrg** [vim/vim#9938]
### Steps to reproduce

Since I type `:` a lot more often than `;`, I have switched both keys. Unfortunately, when the `:` is remapped, it is not possible to type a command in the `hit-enter-prompt` anymore.

1. Run `vim --clean -S test.vim`, with
```vim
noremap ; :
noremap : ;
```
2. Type `;map<CR>` to open the `hit-enter` prompt.
3. Pressing either `;` or `:` will close the prompt. No command can be typed to continue after the `hit-enter` prompt.

### Expected behaviour

I thought it would be possible to continue typing commands in the `hit-enter` prompt even when the `:` key is remapped.

### Version of Vim

8.2.4553

### Environment

Linux

**Comment by brammool** [comment]
For me typing semicolon at the hit enter prompt does respect the mapping, I can type a command then.

**Comment by bfrg** [comment]
> For me typing semicolon at the hit enter prompt does respect the mapping, I can type a command then.

Without closing the output of the previous command?

**Comment by bfrg** [comment]
I should have been more specific. By default (without the above mappings), when I hit `:` at the `hit-enter` prompt, the pager is still shown. But with the mapping, the pager is closed before entering command-line mode.

I like the default behavior since sometimes I need the output of the previous command for typing a follow-up command. A very simple example would be `:ls`, and then `:buffer ...`

**Comment by brammool** [comment]
Characters at the hit-enter prompt are not mapped.  The typed character is put back in the typeahead, then the mapping is applied.  There is no way to avoid a redraw here.

**Comment by bfrg** [comment]
Well that's too bad. I guess I can close this issue.

**Comment by qsmodo** [comment]
I have the exact same problem and use case. Can we please keep this open (unless the maintainer decides this is a "won't fix")?

**Comment by bfrg** [comment]
Maybe a new option for specifying the prompt key could be added, something like `set promptkey=;` or `set cmdlinekey=;`.  Then we wouldn't have to remap `:` using `noremap`.
