### ISSUE TITLE
problem with "val = g:->get('globalX', null)"

### ISSUE THREAD

**Issue by errael** [vim/vim#9948]
### Steps to reproduce

```
vim9script
# Verify a value provided in .vimrc
# Want to minimize function calls.
# Use: var val = g:->get('globalX', null)
# problem when t_number, t_bool

g:splice_wrap = 42
def VerifySetting()
    var wrap = g:->get('splice_wrap', null) ### same problem with v:null
    echo 'splice_wrap: ' wrap ' type:' type(wrap)
    if wrap == null 
        echo 'adjust since no setting in .vimrc'
    endif
    echo 'process/verify user setting'
enddef
VerifySetting()

# FAILS with: E1072: Cannot compare number with special
# or          E1072: Cannot compare bool with special

# WORKAROUND: if type(wrap) == v:t_none, but another function call
```

### Expected behaviour

No error, `== null` works

I understand they are "primitive" types and there is a workaround.

### Version of Vim

8.2.4559

### Environment

gtk3

**Comment by errael** [comment]
Took a closer look at the doc, string is not a good choice. But `var uniq = []` and if it's script local, rather than function, any overhead is amortized.

**Comment by errael** [comment]
final `UNIQ = []` works well, wonder if there's something interesting or useful I can stuff into the list.

**Comment by brammool** [comment]
i'm glad you found a solution.  Nevertheless, perhaps we should just allow comparing anything with null.
When comparing with a number, bool or float the result will always be false, but without an error message.

**Comment by errael** [comment]
> allow comparing anything with null

Does feel more consistent and useful.
