### ISSUE TITLE
Xfile present in $HOME after compiling

### ISSUE THREAD

**Issue by pheiduck** [vim/vim#9953]
### Steps to reproduce

Use Arch Linux
use PKGBUILD for vim
compile it `makepkg -src`
`ls $HOME`
see Xfile.bak

### Expected behaviour

no leftover files in userspace

### Version of Vim

8.2.4562

### Environment

github CI
OS: Ubuntu 20.04
shell: bash

**Comment by brammool** [comment]
I can only see Xfile.bak in a test, and it's deleted there.
The tests should not use $HOME anyway.
Problem should be with PKGBUILD, whereever you get that.

**Comment by pheiduck** [comment]
> I can only see Xfile.bak in a test, and it's deleted there. The tests should not use $HOME anyway. Problem should be with PKGBUILD, whereever you get that.

Yes, that was the last thing I thought of, and that there might be a way to prevent the file from being created upstream. But if it only affects the PKGBUILD I have already fixed it :)

**Comment by yegappan** [comment]
This issue is addressed by https://github.com/vim/vim/commit/6e2e2cc95b913e33145047e0fade5193da6e4379. Now the Xfile.bak file is created in a local Xbackup directory.

**Comment by pheiduck** [comment]
> This issue is addressed by [6e2e2cc](https://github.com/vim/vim/commit/6e2e2cc95b913e33145047e0fade5193da6e4379). Now the Xfile.bak file is created in a local Xbackup directory.

Perfect than I can remove my workaround.
