### ISSUE TITLE
Vim9: no error if autoload script imports itself while being loaded for completion function

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9958]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        var dir = '/tmp/.vim'
        dir->delete('rf')
        &runtimepath = dir
        dir ..= '/autoload'
        dir->mkdir('p')
        var lines =<< trim END
            vim9script
            import autoload 'script.vim'
            export def Complete(..._): string
                return 'match'
            enddef
        END
        lines->writefile(dir .. '/script.vim')
        import autoload 'script.vim'
        command -nargs=* -complete=custom,script.Complete Cmd eval 0 + 0
        &wildcharm = char2nr("\<Tab>")
        feedkeys(":Cmd \<Tab>")
    EOF
    )

No error is given.  The command-line contains the text `:Cmd match`.

**Expected behavior**

An error is given:

    E1088: Script cannot import itself

Because the autoload script is trying to import itself:

    import autoload 'script.vim'

That should be disallowed since the patch [8.2.4330](https://github.com/vim/vim/releases/tag/v8.2.4330).

**Version of Vim**

8.2 Included patches: 1-4574

**Environment**

Operating system: Ubuntu 20.04.4 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: zsh 5.8

**Additional context**

If we turn the `Complete()` function into a generic function (i.e. it's no longer used to complete a user-defined Ex command), then an error is correctly given:
```vim
vim9script
var dir = '/tmp/.vim'
dir->delete('rf')
&runtimepath = dir
dir ..= '/autoload'
dir->mkdir('p')
var lines =<< trim END
    vim9script
    import autoload 'script.vim'
    export def Func()
        echomsg 'from Func()'
    enddef
END
lines->writefile(dir .. '/script.vim')
import autoload 'script.vim'
script.Func()
```
    E1088: Script cannot import itself

**Comment by brammool** [comment]
This is because call_vim_function() sets emsg_off when trying to dereference the name.  If it's not a function reference, this will fail and we use the name as-is.  Unforrunately this also hides any other error.  It's not easy to find a solution for this.
