### ISSUE TITLE
Vim9: wrong shadowing error at compile time when `call()`ing nested function

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9959]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        def Foo(b: bool)
            call(Bar, [b])
        enddef
        def Bar(b: bool)
        enddef
        defcompile
    EOF
    )

An error is given:

    E1167: Argument name shadows existing variable: b

**Expected behavior**

No error is given, because there is no shadowing.  In particular, the `b` argument of the `Bar()` function does not shadow the `b` argument of the `Foo()` function.  The only way that could be true was if we could refer to the `b` argument of `Foo()` from `Bar()`.  But we can't; those are different functions, with their own local namespace.

**Version of Vim**

8.2 Included patches: 1-4574

**Environment**

Operating system: Ubuntu 20.04.4 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: zsh 5.8

**Additional context**

Regression introduced in patch [8.2.4575](https://github.com/vim/vim/releases/tag/v8.2.4575).

---

No issue if we remove `call()`, and call `Bar()` directly:
```vim
vim9script
def Foo(b: bool)
    Bar(b)
enddef
def Bar(b: bool)
enddef
defcompile
```
This is inconsistent.  If an error must be given, why should it depend on whether `call()` is called?

**Comment by lacygoill** [comment]
> 8.2 Included patches: 1-4574

Sorry, wrong information.  I tested the issue on patch 8.2.4576.  But then, I had to get back to to 8.2.4574 because 8.2.4575 broke too many things.

**Comment by brammool** [comment]
> **Steps to reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(tee <<'EOF'
>         vim9script
>         def Foo(b: bool)
>             call(Bar, [b])
>         enddef
>         def Bar(b: bool)
>         enddef
>         defcompile
>     EOF
>     )
> 
> An error is given:
> 
>     E1167: Argument name shadows existing variable: b

I cannot reproduce this problem.  Not with 8.2.4579 and not with
8.2.4559.

I do not see a reason why recent patches may have changed something
related to shadowing.


-- 
MAN:    Fetchez la vache!
GUARD:  Quoi?
MAN:    Fetchez la vache!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
One of the recent patches definitely introduced a regression; it broke several of my plugins.

But the issue has been fixed in an even more recent patch.  I guess thanks to [8.2.4580](https://github.com/vim/vim/releases/tag/v8.2.4580).
