### ISSUE TITLE
sort() in Windows works differently from Linux with function

### ISSUE THREAD

**Issue by mg979** [vim/vim#9961]
### Steps to reproduce

    :echo sort([1,3,2], {a,b -> a > b})

Output: [1, 3, 2]

Also it doesn't work if using a non-lambda function.
It works in Linux/WSL.

But this works:

    :echo sort([1,3,2], { a,b -> a == b ? 0 : a > b ? 1 : -1})

Probably not a bug, just a different implementation of sort().

### Expected behaviour

    :echo sort([1,3,2], {a,b -> a > b})

Output: [1, 2, 3]

### Version of Vim

8.2.4576

### Environment

Windows 11

**Comment by mg979** [comment]
Probably not a bug, just a different implementation of sort().

**Comment by k-takata** [comment]
This should work as expected:
```
:echo sort([1,3,2], {a,b -> a - b})
```
