### ISSUE TITLE
E121: Undefined variable: vim8#complete in legacy script with custom command-completion function

### ISSUE THREAD

**Issue by bfrg** [vim/vim#9962]
### Steps to reproduce

1. Run `vim --clean -S vim8.vim`, with
```vim
function vim8#complete(...)
    return ['aaa', 'bbb', 'ccc']
endfunction
command -nargs=1 -complete=customlist,vim8#complete Test echomsg <q-args>
```
2. Type: `:Test <tab>`
3. Result:
```
E121: Undefined variable: vim8#complete
```

### Expected behaviour

No error messages when using the old syntax in legacy scripts.

### Version of Vim

8.2.4583

### Environment

Linux

**Comment by Shane-XB-Qian** [comment]
i cannot reproduce it at v8.2.4567, so perhaps it is a regression. :-)

**Comment by brammool** [comment]
It does work to do the completion, but it gives the error message first.  That error was added by 8.2.4578, apparently there was no test for using an autoload function for completion.
