### ISSUE TITLE
tmux: toggling zoom state on a tmux pane may send vim to background 

### ISSUE THREAD

**Issue by zkrx** [vim/vim#9965]
Since not long ago (I would say my last arch linux update, so 1 month or a couple of months?), I have this weird bug when zooming/unzooming on a pane under tmux while using Vim. Vim gets sent to background sometimes.

### Steps to reproduce

- Have at least 2 panes in one tmux window.
- In one pane, start vim
- send vim to background by using ^z
- get vim to foreground by using "fg"
- zoom in (or out) on pane with ^b z
- vim is inadequately sent to background

I can reproduce using "vim --clean".

The issue isn't reproducible using other commands, not even using standard Vi.

I initially opened a ticket on the tmux project where it was suggested that this is a Vim issue:
https://github.com/tmux/tmux/issues/3122

### Expected behaviour

Vim stays in foreground while zooming/unzooming on a tmux pane.

### Version of Vim

:version VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 16 2022 12:09:56) Included patches: 1-4106 Compiled by Arch Linux

### Environment

Arch Linux
[laptop]$ uname -sp && tmux -V && echo $TERM
Linux unknown
tmux 3.2a
screen

Reproduced under guake and xfce4-terminal

**Comment by lacygoill** [comment]
Try to reproduce on master.  In particular, make sure you have this patch:

[8.2.4195](https://github.com/vim/vim/releases/tag/v8.2.4195)  resizing terminal may cause to behave like CTRL-Z

**Comment by chrisbra** [comment]
can you please reproduce with latest master?

**Comment by zkrx** [comment]
I have another machine with:
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 24 2022 18:41:57)
Included patches: 1-4464
and I cannot reproduce.

On the machine where I have the buggy version, I downloaded and built the latest release (v8.2.4594) and the bug is no longer present.

Thank you for your help and sorry for the noise, I should have updated my system first.
