### ISSUE TITLE
vim9script: when using the new syntax "&quickfixtextfunc = qftf.Main", the script file qftf.vim is always sourced according to :scriptnames

### ISSUE THREAD

**Issue by bfrg** [vim/vim#9966]
### Steps to reproduce

1. Run `vim --clean -S test.vim`, with
```vim
vim9script

const file: list<string> =<< trim END
    vim9script
    export def Test(info: dict<number>): list<string>
        return []
    enddef
END

set runtimepath^=/tmp/vim
mkdir('/tmp/vim/autoload', 'p')
writefile(file, '/tmp/vim/autoload/qftf.vim')

import autoload 'qftf.vim'
&quickfixtextfunc = qftf.Test
```
2. Now run `:scriptnames`. The output looks something like this:
```
:scriptnames
  1: /usr/share/vim/vim82/defaults.vim
  ⋮
  9: /tmp/test.vim
 10: /tmp/vim/autoload/qftf.vim
```
It seems that the autoload script (10) has already been sourced.

---

With the syntax `set quickfixtextfunc=qftf.Test`, the output of `:scriptnames` looks like we would have expected:
```
:scriptnames
  1: /usr/share/vim/vim82/defaults.vim
  ⋮
  9: /tmp/test.vim
 10 A: /tmp/vim/autoload/qftf.vim
```
i.e. the autoload script hasn't been sourced yet.

Using the old syntax `set quickfixtextfunc=qftf#Test`, and removing the `import autoload 'qftf.vim'` statement, the script file `qftf.vim` doesn't even appear in the output of `:scriptnames` as expected.

### Expected behaviour

I wouldn't have expected the autoload script to be sourced until the quickfix window was opened.

### Version of Vim

8.2.4584

### Environment

Linux

**Comment by lacygoill** [comment]
There is a fundamental difference between this:

    set quickfixtextfunc=qftf.Test

And this:

    &quickfixtextfunc = qftf.Test

In the first command, the operand on the right-hand side of the assignment is implicitly a string.  In the second command, it's explicitly a function reference.

IOW, they are not really equivalent.  OTOH, these are equivalent:

    set quickfixtextfunc=qftf.Test
    &quickfixtextfunc = 'qftf.Test'

And if you quote the function reference, then you get the desired result:
```vim
vim9script

const file: list<string> =<< trim END
    vim9script
    export def Test(info: dict<number>): list<string>
        return []
    enddef
END

set runtimepath^=/tmp/vim
mkdir('/tmp/vim/autoload', 'p')
writefile(file, '/tmp/vim/autoload/qftf.vim')

import autoload 'qftf.vim'
&quickfixtextfunc = 'qftf.Test'
scriptnames
```
    1: /proc/83419/fd/17
    2 A: /tmp/vim/autoload/qftf.vim
      ^

Notice the `A` flag which is prepended before the path to the autoload script.  It means the script has not been sourced yet; just marked as being an autoload script in which an unknown function definition can be looked up at runtime.

---

While [this behavior is intended](https://github.com/vim/vim/issues/8124#issuecomment-822568891), I don't know whether it's properly documented.  If it's not, it probably should be, because making sure that an autoload script is lazy-loaded is important to not increase Vim's startup time.

**Comment by lacygoill** [comment]
There is a [similar issue](https://github.com/lacygoill/wiki/blob/master/bug/vim.md#-36) which I haven't had the time to report so far.

This takes 5 seconds to compile:
```vim
vim9script
var dir = '/tmp/.vim'
dir->delete('rf')
&runtimepath = dir
dir ..= '/autoload'
dir->mkdir('p')
var lines =<< trim END
    vim9script
    sleep 5
    export def Func()
        echomsg 'from Func()'
    enddef
END
lines->writefile(dir .. '/script.vim')
import autoload 'script.vim'
def Foo()
    call(script#Func, [])
enddef
defcompile
```
This compiles immediately:
```vim
vim9script
var dir = '/tmp/.vim'
dir->delete('rf')
&runtimepath = dir
dir ..= '/autoload'
dir->mkdir('p')
var lines =<< trim END
    vim9script
    sleep 5
    export def Func()
        echomsg 'from Func()'
    enddef
END
lines->writefile(dir .. '/script.vim')
import autoload 'script.vim'
def Foo()
    call(script.Func, [])
enddef
defcompile
```
Why the difference?  It seems inconsistent.

**Comment by bfrg** [comment]
> While https://github.com/vim/vim/issues/8124#issuecomment-822568891, I don't know whether it's properly documented. If it's not, it probably should be, because making sure that an autoload script is lazy-loaded is important to not increase Vim's startup time.

I agree, it should definitively be documented.

So, currently there are 5 different ways to set `quickfixtextfunc` (and other options):
```
set quickfixtextfunc=qftf#Main    # qftf.vim is not sourced (no import required)
&quickfixtextfunc = 'qftf#Main'   # qftf.vim is not sourced (no import required)

import autoload 'qftf.vim'
set quickfixtextfunc=qftf.Main    # qftf.vim is not sourced
&quickfixtextfunc = 'qftf.Main'   # qftf.vim is not sourced
&quickfixtextfunc = qftf.Main     # qftf.vim is sourced immediately
```
When using the last syntax, it seems the `autoload` in the `import autoload 'qftf.vim'` statement is useless, so it might as well just be omitted.

This is quite complicated, many users will be confused by the amount of different ways to set one option.

**Comment by bfrg** [comment]
Maybe a warning could be given, when the last syntax is encountered during startup:
```vim
import autoload 'qftf.vim'
&quickfixtextfunc = qftf.Main
```

Something like:
```
Warning: File qftf.vim is sourced despite autoload import
```

Just a thought...

**Comment by bfrg** [comment]
Since this has already been discussed in https://github.com/vim/vim/issues/8124#issuecomment-822568891, I'm closing this. But it should definitively be documented somewhere.

**Comment by brammool** [comment]
When compiling a function, without calling it, the autoload script is not sourced yet, as is documented:

When compiling a `:def` function and a function in an autoload script is
encountered, the script is not loaded until the `:def` function is called.
This also means you get any errors only at runtime, since the argument and
return types are not known yet.

I just checked that this is true.

I'll add a remark that the autoload script is sourced when referring to a function directly.  The advantage of sourcing and compiling it is that you get any error message right away, not later.

**Comment by lacygoill** [comment]
> When compiling a function, without calling it, the autoload script is not sourced yet, as is documented:

This is true when we use the new `script.Func` syntax:
```vim
vim9script
var dir = '/tmp/.vim'
dir->delete('rf')
&runtimepath = dir
dir ..= '/autoload'
dir->mkdir('p')
var lines =<< trim END
    vim9script
    export def Func()
        echomsg 'from Func()'
    enddef
END
lines->writefile(dir .. '/script.vim')
import autoload 'script.vim'
def Foo()
    call(script.Func, [])
enddef
defcompile
filter /autoload/ scriptnames
```
    2 A: /tmp/.vim/autoload/script.vim
      ^
      ✔

But not when we use the old `script#Func` syntax:
```vim
vim9script
var dir = '/tmp/.vim'
dir->delete('rf')
&runtimepath = dir
dir ..= '/autoload'
dir->mkdir('p')
var lines =<< trim END
    vim9script
    export def Func()
        echomsg 'from Func()'
    enddef
END
lines->writefile(dir .. '/script.vim')
import autoload 'script.vim'
def Foo()
    call(script#Func, [])
enddef
defcompile
filter /autoload/ scriptnames
```
    2: /tmp/.vim/autoload/script.vim
      ^
      ✘

Why the difference?  If it's intended, is it documented?

**Comment by brammool** [comment]
Well, that is the old way of using an autoload function.  The "script#" part is part of the function name, thus to find the function the script must be loaded.  Using the auloload import was added to avoid that.
Although this is a result of how it's implemented, I think it is OK to leave it like that.  I'll add a remark in the help where needed.
