### ISSUE TITLE
old 'cursorline' not removed with timer, sign_unplace() and cursor()

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#9970]
### Steps to reproduce

1. Run `vim --clean`
2. Source the following file:
```vim
call setline(1, ['aaaaa', 'bbbbb', 'ccccc', 'ddddd', 'eeeee', 'fffff'])
set cursorline
call cursor(6, 1)
call sign_define('foo', { 'text': '>' })
call sign_place(1, 'bar', 'foo', bufnr(), { 'lnum': 3 })
call sign_place(2, 'bar', 'foo', bufnr(), { 'lnum': 2 })

func Func(timer)
  call sign_unplace('bar', { 'id': 1 })
  call cursor(3, 1)
  1,6yank
endfunc

call timer_start(1000, 'Func')
```
3. After 1 second, 'cursorline' is shown on both line 3 and line 6

### Expected behaviour

After 1 second, 'cursorline' is only shown on line 3

### Version of Vim

8.2.4590

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

**Comment by brammool** [comment]
Without the sign_unplace() the cursorline isn't update at all.  Thus it seems the only reason it's drawn in line 3 is because of the change in the placed signs.

**Comment by zeertzjq** [comment]
wait a minute

**Comment by zeertzjq** [comment]
How about this then:
```vim
call setline(1, ['aaaaa', 'bbbbb', 'ccccc', 'ddddd', 'eeeee', 'fffff'])
set cursorline
call cursor(6, 1)
call sign_define('foo', { 'text': '>' })
call sign_place(1, 'bar', 'foo', bufnr(), { 'lnum': 3 })
call sign_place(2, 'bar', 'foo', bufnr(), { 'lnum': 2 })

func Func(timer)
  call sign_unplace('bar', { 'id': 1 })
  call cursor(3, 1)
  1,6yank
  call feedkeys('k')
endfunc

call timer_start(1000, 'Func')
```
Without the `sign_unplace()` the cursorline is only shown on line 2. With the `sign_unplace()` the cursorline is shown on both line 2 and line 6.

**Comment by zeertzjq** [comment]
The linked PR still solves this. I'll update the test.

**Comment by zeertzjq** [comment]
Wait a minute

**Comment by zeertzjq** [comment]
Oh, the `:yank` isn't required for the redrawing problem.

**Comment by zeertzjq** [comment]
So I guess the real fix should be in `win_line()`.
