### ISSUE TITLE
vim9: echo garbles output

### ISSUE THREAD

**Issue by errael** [vim/vim#9976]
### Steps to reproduce

I guess the echo implementation makes this a nested echo

run the following
```
vim9script
def X(): string
    echo 'foo'
    return 'baz'
enddef

echo 'bar' X()
```
observe output
```
bar
foo baz
```

### Expected behaviour

expect output
```
foo
bar baz
```
which can be obtained with a tmp
```
var t = X()
echo 'bar' t
```

### Version of Vim

8.2.4589

### Environment

ubuntu; gvim; vim-gtk3

**Comment by brammool** [comment]
This works as intended.  ":echo" evaluates and prints each argument in sequence.
If you want to first evaluate the arguments before printing anything, use string concatenation: "echo 'bar ' .. X()".
