### ISSUE TITLE
Typo in documentation: usr_03.txt section 3.7

### ISSUE THREAD

**Issue by robin-lee** [vim/vim#998]
[Line 271](https://github.com/vim/vim/blob/0b9e4d1224522791c0dbbd45742cbd688be823f3/runtime/doc/usr_03.txt#L271)
`The CTRL-U command scrolls down half a screen of text.  Think of looking`
should be
`The CTRL-U command scrolls up half a screen of text.  Think of looking`

Do I need to submit a pull request for this?

**Comment by brammool** [comment]
The text is correct

**Comment by robin-lee** [comment]
Ah I see now. My bad.
