### ISSUE TITLE
[assertion 'GDK_IS_DRAWABLE (drawable)' failed] errors show up in terminal while scrolling the right side of vertically split gvim windows.

### ISSUE THREAD

**Issue by carpetaa** [vim/vim#9982]
### Steps to reproduce

1. Install vim:
```
set vimtopdir = $HOME
set python3dir = `python3-config --configdir`
git clone --depth 1 --branch v8.2.4598 https://github.com/vim/vim.git
./configure --with-features=huge \
            --enable-multibyte \
            --enable-rubyinterp=yes \
            --enable-python3interp=yes \
            --with-python3-config-dir=$python3dir \
            --enable-perlinterp=yes \
            --enable-luainterp=yes \
            --enable-gui=gtk2 \
            --enable-cscope \
            --prefix=$vimtopdir
make
make install
```
2. Run in terminal: `gvim --clean ~/utilities/installmyvim.csh`
3. Run in gvim: `:vs`
4. Scroll the right side of split window.

### Expected behaviour

No assertion failed message showed in terminal.

### Version of Vim

8.2.4598

### Environment

**OS:** 
`cat /proc/version`
Linux version 3.10.0-1160.49.1.el7.x86_64 (mockbuild@x86-vm-43.build.eng.bos.redhat.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Tue Nov 9 16:09:48 UTC 2021
**terminal:**
GNOME Terminal 3.28.2
**$TERM:**
xterm-256color
**$shell**
tcsh-6.19.00

### Logs and stack traces

```shell
(gvim:9401): Gdk-CRITICAL **: 23:02:22.141: IA__gdk_drawable_get_size: assertion 'GDK_IS_DRAWABLE (drawable)' failed
```

### Related issue

#8324 

https://github.com/vim/vim/issues/8324#issuecomment-855244150

**Comment by brammool** [comment]
I can fix it by adding GDK_IS_DRAWABLE().  I'm not sure if this is right, but it fixes the problem and scrolling still works.

**Comment by hyperion009** [comment]
@brammool where to add GDK_IS_DRAWABLE()?

**Comment by brammool** [comment]
Look at patch  8.2.4599
