### ISSUE TITLE
python3complete leaves documentation window behind

### ISSUE THREAD

**Issue by fancsali** [vim/vim#9983]
### Steps to reproduce

1. Open a `.py` file
2. Start to type and use OmniCompletion (drop-down and a scratch buffer with the docs will be displayed)
3. Pick one from the suggestions
4. Scratch window with docs stays open

### Expected behaviour

The scratch window should disappear.

### Version of Vim

8.2

### Environment

Linux Mint 20.2 Xfce 64-bit

**Comment by lacygoill** [comment]
Not sure whether it's working as intended, but here is a MWE:
```vim
vim9script
&completeopt = 'preview,menuone'
def OmniFunc(findstart: bool, base: string): any
    if findstart
        return 0
    else
        return [{word: 'word', info: 'info'}]
    endif
enddef
&omnifunc = OmniFunc
feedkeys("i\<C-X>\<C-O>", 'nxt')
```
---

As a workaround, you could replace the `preview` item with the `popup` one inside the value of the [`'completeopt'`](https://vimhelp.org/options.txt.html#%27completeopt%27) option:

    set completeopt-=preview completeopt+=popup

Test:
```vim
vim9script
&completeopt = 'popup,menuone'
def OmniFunc(findstart: bool, base: string): any
    if findstart
        return 0
    else
        return [{word: 'word', info: 'info'}]
    endif
enddef
&omnifunc = OmniFunc
feedkeys("i\<C-X>\<C-O>", 'nxt')
```
