### ISSUE TITLE
vim9: :source of ":finish" can hang vim

### ISSUE THREAD

**Issue by errael** [vim/vim#9988]
### Steps to reproduce

Start gvim with a buffer of
```
vim9script
echo 'here'
finish
```
run
```
:source
```
Observe a screen full of `here`. ^C stops it.

Delete the `echo` line. Run `:source` again. Observe gvim hangs and must be killed.

Take out the finish and things work as expected

### Expected behaviour

finish doesn't cause problems

### Version of Vim

8.2.4602

### Environment

ubuntu, gtk3

**Comment by vim-ml** [comment]
Hi,

The support for sourcing a Vim9 script (https://github.com/vim/vim/pull/9974)
is not yet merged.
This problem will be addressed by that PR.

- Yegappan

**Comment by errael** [comment]
Oops, misunderstood/anxious, clearly want to get my hands on it. Apologies for the noise.

**Comment by errael** [comment]
Then again the script,
```
echo 'here'
finish
```
also hangs vim. So not a vim9issue
