### ISSUE TITLE
Vim9: nested recursive functions not supported

### ISSUE THREAD

**Issue by noscript** [vim/vim#9989]
### Steps to reproduce

1. Create and source the script:
```vim
vim9script

def MyFunc()
  def Fib(n: number): number
    if n < 2
      return 1
    endif
    return Fib(n - 2) + Fib(n - 1)
  enddef

  echo Fib(5)
enddef

MyFunc()
```
2. Error:
```
Error detected while compiling function <SNR>1_source[2]..script vim9fib.vim[14]..function <SNR>
210_MyFunc[1]..<lambda>144:
line    4:
E117: Unknown function: Fib
```

### Expected behaviour

No error and prints result `8`.

### Version of Vim

8.2.4532

### Environment

OS: Debian 11
Terminal: GUI

**Comment by bfrg** [comment]
This one works:
```vim
vim9script

def Myfunc()
    var Fib: func(number): number

    Fib = (n: number): number => {
        if n < 2
            return 1
        endif
        return Fib(n - 2) + Fib(n - 1)
    }

    echo Fib(5)
enddef

defcompile
```

But when assigning the lambda directly to the variable, the same error occurs:
```vim
vim9script

def Myfunc()
    const Fib = (n: number): number => {
        if n < 2
            return 1
        endif
        return Fib(n - 2) + Fib(n - 1)
    }

    echo Fib(5)
enddef

defcompile
```
Result:
```
Error detected while compiling command line..script /tmp/test.vim[27]..function <SNR>17_Myfunc[1]..<lambda>1:
line    4:
E117: Unknown function: Fib
```

**Comment by Shane-XB-Qian** [comment]
> But when assigning the lambda directly to the variable, the same error occurs:

seems still not working after this patch.

```vim
const Xx = (n: number): number => {
  if n < 2
    return 1
  endif
  return Xx(n - 2) + Xx(n - 1)
}

echom Xx(5)
```
// but such working.
// sounds like last time that #9820 that fix.

// though personally felt lambda is a bit less readable than direct func..

**Comment by brammool** [comment]
> > But when assigning the lambda directly to the variable, the same
> > error occurs:
> 
> seems still not working after this patch.
> 
> ```vim
> const Xx = (n: number): number => {
>   if n < 2
>     return 1
>   endif
>   return Xx(n - 2) + Xx(n - 1)
> }
> 
> echom Xx(5)
> ```

This is expected.  You cannot use a variable in the expression on the
RHS of its own declaration.  Just like this does not work:

	var nr = nr+ 2


-- 
ARTHUR:    Will you ask your master if he wants to join my court at Camelot?!
GUARD #1:  But then of course African swallows are not migratory.
GUARD #2:  Oh, yeah...
GUARD #1:  So they couldn't bring a coconut back anyway...
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bfrg** [comment]
It is valid in some other languages. For example, in C++ the following works:
```cpp
#include <functional>

int main()
{
    std::function<int(int)> fib = [&](int n) -> int {
        if (n < 2)
            return n;

        return fib(n - 2) + fib(n - 1);
    };

    return fib(4);
}
```

However, it won't compile when the `auto` keyword is used to automatically deduce the type:
```cpp
int main()
{
    auto fib = [&](int n) -> int {
        if (n < 2)
            return n;

        return fib(n - 2) + fib(n - 1);
    };

    return fib(4);
}
```

Result:
```
test.cpp: In lambda function:
test.cpp:7:16: error: use of ‘fib’ before deduction of ‘auto’
    7 |         return fib(n - 2) + fib(n - 1);
      |                ^~~
test.cpp:7:29: error: use of ‘fib’ before deduction of ‘auto’
    7 |         return fib(n - 2) + fib(n - 1);
      |                             ^~~
```

---

In Python:
```python
fib = lambda n: n if n < 2 else fib(n - 2) + fib(n - 1)
print(fib(4))
```
