### ISSUE TITLE
go1.18 new built-in type `any`

### ISSUE THREAD

**Issue by jackieli-tes** [vim/vim#9998]
In the latest go 1.18 release, `any` has become an built-in type: https://go.dev/ref/spec#Interface_types. The syntax should reflect this.

**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

`any` should be highlighted so users know it's a special type

**Describe the solution you'd like**

Add `any` to https://github.com/vim/vim/blob/master/runtime/syntax/go.vim#L120

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by jackieli-tes** [comment]
@bhcleek & @fzipp I believe this is already in vim-go: https://github.com/fatih/vim-go/pull/3351

**Comment by bhcleek** [comment]
This issue can be closed. Support for `any` was added in https://github.com/vim/vim/commit/d13166e788fcaef59ec65c20b46ca4be16625669.
